### PR TITLE
mon/ConfigKeyService: add 'config-key dump' to show keys and vals

### PR DESCRIPTION
**Pull request by dmick**
Signed-off-by: Dan Mick <dan.mick@redhat.com>

### CODE REVIEW

**Comment by liewegas** [comment]
Add to qa/workunits/mon/cephtool.sh ?

**Comment by dmick** [comment]
maybe you mean qa/workunits/cephtool/test.sh, but there's no config-key testing at all there currently.  There's qa/workunits/mon/test_mon_config_key.py, but it wasn't even currently testing list; I could add both, certainly.

**Comment by dmick** [comment]
Added test in qa/workunits/mon/test_mon_config_key.py

**Comment by yuriw** [comment]
http://pulpito.ceph.com/yuriw-2017-05-01_17:26:44-rados-wip-yuri-testing_2017_4_29_2-distro-basic-smithi/

http://pulpito.ceph.com/yuriw-2017-05-01_21:57:19-rados-wip-yuri-testing_2017_4_29_2---basic-smithi/

**Pull request merged**
