### PR TITLE
mon: use ceph_clock_now if message is self-generated

### PR DESCRIPTION
**Pull request by hjwsm1989**
Signed-off-by: huangjun <huangjun@xsky.com>

### CODE REVIEW

**Comment by tchaikov** [comment]
was introduced by #12826

**Comment by liewegas** [comment]
oops!

**Comment by liewegas** [comment]
http://pulpito.ceph.com/sage-2017-08-29_05:18:12-rados-wip-sage-testing-20170828-distro-basic-smithi/

**Comment by liewegas** [comment]
https://github.com/ceph/ceph/pull/17345

**Pull request merged**
