### PR TITLE
mimic: multisite: data sync error repo processing does not back off on empty

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/35979

### CODE REVIEW

**Comment by smithfarm** [comment]
Non-trivial conflict resolution in the last commit

**Comment by smithfarm** [comment]
```
/home/jenkins-build/build/workspace/ceph-pull-requests/src/rgw/rgw_data_sync.cc: In member function 'utime_t RGWDataSyncShardCR::get_idle_interval() const':
/home/jenkins-build/build/workspace/ceph-pull-requests/src/rgw/rgw_data_sync.cc:1538:62: error: no matching function for call to 'utime_t::utime_t(std::chrono::time_point<ceph::time_detail::coarse_real_clock>)'
     return utime_t(ceph::coarse_real_clock::zero() + interval);
                                                              ^
```

**Comment by cbodley** [comment]
@smithfarm it looks like that pr depends on changes to utime_t from https://github.com/ceph/ceph/pull/21893

**Comment by yuriw** [comment]
[wip-yuri-testing-2018-10-15-2110-mimic](https://trello.com/c/VnZerOBe/442-wip-yuri-testing-2018-10-15-2110-mimic)

**Pull request merged**
