### PR TITLE
ceph-disk: add multipath support

### PR DESCRIPTION
**Pull request by dachary**
http://tracker.ceph.com/issues/11881

### CODE REVIEW

**Comment by dachary** [comment]
@liewegas if that looks sane I'll add tests in ceph-disk.sh and update udev-rules accordingly

**Comment by dachary** [comment]
@bigkraig this is inspired by what you did at https://github.com/ceph/ceph/pull/1229. How does that look ? Note that the journal_uuid is assumed to exist and I don't think we need https://github.com/ceph/ceph/pull/1229/files#diff-788c3cea6213c27f5fdb22f8337096d5R1041 as long as /dev/disk/by-partuuid/ is properly populated.

**Comment by bigkraig** [comment]
Hey thanks for picking this up, this looks good from what I can tell. I'd test it out for you but we dropped the project that needed that patch.

**Comment by dachary** [comment]
@bigkraig thanks for taking a look :-)

**Comment by dachary** [comment]
wip-11881-multipath is building on http://ceph.com/gitbuilder.cgi

**Comment by dachary** [comment]
It has been tested semi manually on CentOS 7 with:

* installing 9.0.2 via ceph-deploy and creating a mon
* getting the wip-11881-multipath branch and installing manually ceph-disk and the udev rules
* ceph-disk prepare / activate a multipath device (details in issue 11881) 
* running src/test/ceph-disk-root.sh (verifies there is no regression in the dmcrypt logic)
* ceph-disk prepare / activate a /dev/vdb device manually

**Comment by dachary** [comment]
teuthology tests for CentOS 7 are blocked by http://tracker.ceph.com/issues/12725 but the ceph-deploy suite passes for Ubuntu 14.04 http://149.202.169.83:8081/ubuntu-2015-08-18_18:38:46-ceph-deploy-wip-11881-multipath---basic-openstack/

**Comment by dachary** [comment]
the ceph-deploy test apparently never succeeded on CentOS 7 ( http://tracker.ceph.com/issues/12726 ) and we have to rely on manual testing in the meantime.

**Pull request closed without merging**
