### PR TITLE
rgw_log_backing: error code not returned 

### PR DESCRIPTION
**Pull request by Suyashd999**
Fixes: https://tracker.ceph.com/issues/68031

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Comment by Suyashd999** [comment]
Hi @yuvalif! I have created the PR

**Comment by yuvalif** [comment]
@adamemerson can you please have a look?

**Comment by adamemerson** [comment]
jenkins test make check

**Comment by yuvalif** [comment]
teuthology. see: https://github.com/ceph/ceph/pull/59731#issuecomment-2361439032

**Comment by ivancich** [comment]
@Suyashd999, it looks like you broke the indentation pattern. In the future please follow the code block's indentation and use the CodingStyle file to reduce friction for future developers moving through the code. Thanks!

**Comment by ivancich** [comment]
@Suyashd999 Will this need backports? If so, please update the tracker accordingly. If it needs no backports, change the tracker status to _Resolved_. If it needs backports then please update the _backport_ field and change the status to _Pending Backports_. Thanks!

**Comment by Suyashd999** [comment]
> @Suyashd999, it looks like you broke the indentation pattern. In the future please follow the code block's indentation and use the CodingStyle file to reduce friction for future developers moving through the code. Thanks!

Apologies. Will keep in mind from next time.

**Comment by Suyashd999** [comment]
> @Suyashd999 Will this need backports? If so, please update the tracker accordingly. If it needs no backports, change the tracker status to _Resolved_. If it needs backports then please update the _backport_ field and change the status to _Pending Backports_. Thanks!

Hi @yuvalif, @adamemerson! can you help me with this? Does this need backporting?

**Comment by adamemerson** [comment]
> > @Suyashd999 Will this need backports? If so, please update the tracker accordingly. If it needs no backports, change the tracker status to _Resolved_. If it needs backports then please update the _backport_ field and change the status to _Pending Backports_. Thanks!
> 
> Hi @yuvalif, @adamemerson! can you help me with this? Does this need backporting?

Yes. I think it should be applicable to both supported versions.

**Comment by Suyashd999** [comment]
> > > @Suyashd999 Will this need backports? If so, please update the tracker accordingly. If it needs no backports, change the tracker status to _Resolved_. If it needs backports then please update the _backport_ field and change the status to _Pending Backports_. Thanks!
> > 
> > 
> > Hi @yuvalif, @adamemerson! can you help me with this? Does this need backporting?
> 
> Yes. I think it should be applicable to both supported versions.

Thanks!

**Pull request merged**
