### PR TITLE
mimic: simple: when 'type' file is not present activate fails

### PR DESCRIPTION
**Pull request by jan--f**
https://tracker.ceph.com/issues/41022

### CODE REVIEW

**Comment by alfredodeza** [comment]
jenkins test ceph-volume tox

**Comment by alfredodeza** [comment]
Seems like we are hitting valid failures, but those are not related to this PR:

```
_____ TestMixedTypeWithExplicitDevices.test_wal_device_is_not_large_enough _____

self = <ceph_volume.tests.devices.lvm.strategies.test_bluestore.TestMixedTypeWithExplicitDevices object at 0x7f7e0959d978>
stub_vgs = <function stub_vgs.<locals>.apply at 0x7f7e0958f510>
fakedevice = <function fakedevice.<locals>.apply at 0x7f7e0958f2f0>
factory = <class 'ceph_volume.tests.conftest.Factory'>
conf_ceph = <function conf_ceph.<locals>.apply at 0x7f7e0958f598>

    def test_wal_device_is_not_large_enough(self, stub_vgs, fakedevice, factory, conf_ceph):
        conf_ceph(get_safe=lambda *a: None)
        args = factory(filtered_devices=[], osds_per_device=2,
                       block_db_size=None, block_wal_size=None,
                       osd_ids=[])
        ssd = fakedevice(used_by_ceph=False, is_lvm_member=False, rotational=False, sys_api=dict(size=1610612736))
        hdd = fakedevice(used_by_ceph=False, is_lvm_member=False, rotational=True, sys_api=dict(size=60073740000))
    
        with pytest.raises(RuntimeError) as error:
            bluestore.MixedType(args, [hdd], [], [ssd]).computed['osds'][0]
        expected = 'Unable to use device 1.50 GB /dev/sda, LVs would be smaller than 1GB'
>       assert expected in str(error), str(error)
E       AssertionError: <ExceptionInfo RuntimeError tblen=5>
E       assert 'Unable to use device 1.50 GB /dev/sda, LVs would be smaller than 1GB' in '<ExceptionInfo RuntimeError tblen=5>'
E        +  where '<ExceptionInfo RuntimeError tblen=5>' = str(<ExceptionInfo RuntimeError tblen=5>)
```

That type of assertion check on exceptions is no longer allowed in newer pytest versions. It recently changed. It was fixed with this PR https://github.com/ceph/ceph/pull/28866 which I guess it needs to be backported

**Comment by alfredodeza** [comment]
There are some odd errors with the tests, the assertion error is known and has a fix already. I am fine if you want to wait for the backports or move forward with this one @jan--f

**Comment by jan--f** [comment]
@alfredodeza I'll look into the backports...will let you know.

**Comment by jan--f** [comment]
Yeah I made a mistake in a backport. https://github.com/ceph/ceph/pull/29243/files#diff-78f0a822e775d7f8a95fe8c16917df32R202

Will add a fix here.

**Comment by jan--f** [comment]
jenkins test ceph-volume tox

**Comment by jan--f** [comment]
tox only fails on a flake8 error.

**Pull request merged**
