### PR TITLE
doc: Fixes the description of the purpose of a cache pool

### PR DESCRIPTION
**Pull request by GaelFG**
Completing the description of the cache purpose.
Fixes : #11096
Signed-off-by: Gaël Fenet-Garde <gael.fenet.garde@gmail.com>

### CODE REVIEW

**Comment by dachary** [comment]
The 
<pre>
Signed-off-by: Gaël Fenet-Garde gael.fenet.garde@gmail.com
</pre>
must be in the commit message itself as
<pre>
Signed-off-by: Gaël Fenet-Garde &lt;gael.fenet.garde@gmail.com>
</pre>

**Comment by dachary** [comment]
@GaelFG you need to **git --amend** then **git push --force** to modify the commit message. The GitHub web interface won't do it for you, unfortunately ;-)

**Comment by GaelFG** [comment]
Should be good now :)

**Comment by dachary** [comment]
please ignore the #4912 related false negative from the bot

**Pull request merged**
