### PR TITLE
cmake: selectively rewrite install rpath

### PR DESCRIPTION
**Pull request by tchaikov**
we use rpath for finding libceph-common, which is an internal library
not supposed to be used by 3rd party applications.

before this change, `CMAKE_INSTALL_RPATH` is set globally. so cmake is
asked to rewrite the RPATH for all installed targets. but this is not
needed. as some executables do not link against libceph-common. hence,
cmake complains when installing them, like:

CMake Error at src/test/mon/cmake_install.cmake:90 (file):
  file RPATH_CHANGE could not write new RPATH:
    /usr/lib64/ceph
   to the file:
    /home/abuild/rpmbuild/BUILDROOT/ceph-15.0.0-4347.g85a07b9.x86_64/usr/bin/ceph_test_log_rss_usage
   No valid ELF RPATH or RUNPATH entry exists in the file;

so, in this change, we only apply `INSTALL_RPATH` to libceph-common.

Fixes: https://tracker.ceph.com/issues/41524
Signed-off-by: Kefu Chai <kchai@redhat.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`

</details>

### CODE REVIEW

**Comment by tchaikov** [comment]
@smithfarm could you help test the update change? after a second thought, i found that the install path of a library cannot be populate to that of RPATH of executables linked against it. so i changed this PR to skip the global RPATH settings for those executables who don't link against the libraries from ceph.

**Comment by tchaikov** [comment]
being built at https://shaman.ceph.com/builds/ceph/wip-rpath-kefu/e8c66f5664c655488fcffb6dcf0f34d7db341465/

**Comment by smithfarm** [comment]
@tchaikov openSUSE 15.1 is now built, along with CentOS, Ubuntu, etc., and reported to Shaman whenever you push a branch to ceph-ci.

The last Shaman/Chacra build (obtained by clicking on the link you posted) is green for openSUSE 15.1, I see, but it does not include the latest two commits.

Of course I can trigger a build directly in OBS but the result is almost certain to be exactly the same since Jenkins uses "osc build" to do the build on openSUSE 15.1.

**Comment by smithfarm** [comment]
@tchaikov Could you revert 021eb0af23f944105c408ff36c554cc9e7c6a7f2 as part of this PR? As it is implicated in [1].

[1] https://bugzilla.novell.com/show_bug.cgi?id=1140346

**Comment by tchaikov** [comment]
> but it does not include the latest two commits.

why do you mean by "the latest two commits"? i think https://github.com/ceph/ceph-ci/commits/wip-rpath-kefu includes both commits in this PR. if you think these commits was pushed after i post the link. that's because i removed #30065 from this PR. as it's not related.

> Could you revert 021eb0af23f944105c408ff36c554cc9e7c6a7f2 as part of this PR? As it is implicated in [1].

again, i am not following you. 021eb0af23f944105c408ff36c554cc9e7c6a7f2 is not in upstream master. so i am afraid i cannot revert it.

**Comment by tchaikov** [comment]
https://shaman.ceph.com/builds/ceph/wip-kefu-testing-2019-09-02-1658/afdb06fdd413f806d952fb51dd1d3220c16b3dec/

**Comment by smithfarm** [comment]
@tchaikov Never mind - I was confused. I will watch the latest Shaman build and approve if it's green.

**Comment by smithfarm** [comment]
OK, I can confirm that Shaman is green for the current state of this PR. However, I have two questions:

First question: The commit message says:

```
some executables like ceph_test_mon_memory_target does not link against
libradies built from source tree, like librados or libceph-common. so
cmake does not set RPATH for them. hence cmake complains like:
```

Can you fix the typo "libradies" -> "libraries" ?

Second question: The commit message says:

```
before this change, `CMAKE_INSTALL_RPATH` is set globally.
```

Is it still expected that this PR is removing the code that sets `CMAKE_INSTALL_RPATH` globally?

**Comment by smithfarm** [comment]
Third question. Should this PR change all instances of `INSTALL_RPATH ""` to `SKIP_RPATH TRUE`? There are many.

**Comment by smithfarm** [comment]
Fourth question: All of the `INSTALL_RPATH ""` lines were added to address various RPATH-related build failures. These build failures keep recurring on different files - they don't happen all at once, and sometimes the builds are green.

I don't understand the root cause of these failures. Before, we were adding `INSTALL_RPATH ""`. Now we are fixing them by adding `SKIP_RPATH TRUE`. Is there any semantic difference between these two?

Could it be said that, in general, the RPATH build failures are a side effect of libceph-common?

**Comment by tchaikov** [comment]
> I will watch the latest Shaman build and approve if it's green.

OK.

> Can you fix the typo "libradies" -> "libraries" ?

yes.

> Is it still expected that this PR is removing the code that sets CMAKE_INSTALL_RPATH globally?

no.

**Comment by tchaikov** [comment]
well, there are more than 2 questions =)

> Is there any semantic difference between these two?

sure. i am revising the commit message, hopefully it's more readable.

> Could it be said that, in general, the RPATH build failures are a side effect of libceph-common?

could you be more specific?

**Comment by sseshasa** [comment]
LGTM

**Comment by tchaikov** [comment]
- http://pulpito.ceph.com/kchai-2019-09-02_13:19:21-rados-wip-kefu-testing-2019-09-02-1658-distro-basic-mira/
- http://pulpito.ceph.com/kchai-2019-09-06_15:05:18-rados-wip-kefu-testing-2019-09-06-1807-distro-basic-smithi/

**Comment by smithfarm** [comment]
the second commit message still says:

```
before this change, `CMAKE_INSTALL_RPATH` is set globally. so cmake is
asked to rewrite the RPATH for all installed targets. but this is not
needed.
```

but I guess that no longer applies in the final version of this PR.

**Comment by smithfarm** [comment]
Still getting FTBFS in OBS even with this patch applied:

```
[ 5036s] CMake Error at src/test/mon/cmake_install.cmake:90 (file):
[ 5036s]   file RPATH_CHANGE could not write new RPATH:
[ 5036s] 
[ 5036s]     /usr/lib64/ceph
[ 5036s] 
[ 5036s]   to the file:
[ 5036s] 
[ 5036s]     /home/abuild/rpmbuild/BUILDROOT/ceph-15.0.0-5052.4.x86_64/usr/bin/ceph_test_log_rss_usage
[ 5036s] 
[ 5036s]   No valid ELF RPATH or RUNPATH entry exists in the file;
[ 5036s] Call Stack (most recent call first):
[ 5036s]   src/test/cmake_install.cmake:268 (include)
[ 5036s]   src/cmake_install.cmake:378 (include)
[ 5036s]   cmake_install.cmake:42 (include)
[ 5036s] 
[ 5036s] 
[ 5036s] make: *** [Makefile:84: install] Error 1
[ 5036s] error: Bad exit status from /var/tmp/rpm-tmp.ju5s2T (%install)
[ 5036s] 
[ 5036s] 
[ 5036s] RPM build errors:
[ 5036s]     Bad exit status from /var/tmp/rpm-tmp.ju5s2T (%install)
[ 5036s] 
```

Reopened #29922

**Pull request merged**
