### PR TITLE
osd: clear extra mark_started

### PR DESCRIPTION
**Pull request by XinzeChi**
1. use swap to reassign src_obc in do_op
2. Mark_started call twice in sub_op_modify_impl.

Signed-off-by: Xinze Chi <xmdxcxz@gmail.com>

### CODE REVIEW

**Comment by XinzeChi** [comment]
@tchaikov , mark_started call twice in sub_op_modify_impl.

**Comment by tchaikov** [comment]
@XinzeChi , sorry, i should have read your comment more carefully.

looks good to me.

**Comment by liewegas** [comment]
can you rebase (there's a merge conflict now) and separate out the swap() change into a different patch?     thanks!

**Comment by XinzeChi** [comment]
Repush code based on @liewegas 's comments.

**Pull request merged**
