### PR TITLE
nautilus: monitoring: Provide a base set of Prometheus alert manager rules that notify the user about common Ceph error conditions

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/39540

### CODE REVIEW

**Comment by smithfarm** [comment]
Note to reviewers: I cherry-picked https://github.com/ceph/ceph/pull/27996 into this PR.

**Comment by smithfarm** [comment]
jenkins test docs

**Comment by smithfarm** [comment]
`159/171 Test #162: unittest_rgw_dmclock_scheduler ..........***Failed    0.52 sec`

**Comment by smithfarm** [comment]
jenkins re-test this please

**Comment by yuriw** [comment]
[wip-yuri5-testing-2019-05-29-1613-nautilus](https://trello.com/c/q7wFCEp3/622-wip-yuri5-testing-2019-05-29-1613-nautilus)

**Pull request merged**
