### PR TITLE
quincy: cmake: bump node version to 14 

### PR DESCRIPTION
**Pull request by nizamial09**
to update the angular to 13, we need a node version of either 12.20.x or 14.15.x or 16.10.x. But inorder to not break the angular 12 run for now
   we  need to choose the node which works for both 12 and 13. which is
14.15.x. So I went with that node version here.

Signed-off-by: Nizamudeen A <nia@redhat.com>
(cherry picked from commit 5f95db33e912ca2b4a8a9d265d8cb537a6ceab03) (cherry picked from commit 34dc871be599a44eb813b10fb49cf89a64a996c1)

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by nizamial09** [comment]
jenkins test dashboard

**Comment by nizamial09** [comment]
api-test failure tracker here: https://github.com/ceph/ceph/pull/50234

**Review by epuertat — APPROVED** [review]
Thanks @nizamial09 ! Can't we store the node version in some file (NODE_VERSION) and simply fetch it from there, instead of hardcoding it?

**Comment by nizamial09** [comment]
jenkins test api

**Comment by nizamial09** [comment]
> Can't we store the node version in some file (NODE_VERSION) and simply fetch it from there, instead of hardcoding it?

We'll have to hardcode it there as well right? even if its in a different file?

**Pull request merged**
