### PR TITLE
qa/orch/cephadm: test_orch_cli_mon.yaml

### PR DESCRIPTION
**Pull request by kamoltat**
Added test_orch_cli_mon.yaml to recreate
the bug in https://tracker.ceph.com/issues/50089.
basically test how `ceph orch apply mon 3` reduces
the number of monitors from 5 to 3, and see if we
can get a crash to occur.

Fixes:  https://tracker.ceph.com/issues/50088,
https://tracker.ceph.com/issues/50089

Signed-off-by: Kamoltat <ksirivad@redhat.com>

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [x] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by kamoltat** [comment]
Test Passed 4/4 (meaning we weren't able to recreate the problem, need some more work)
https://pulpito.ceph.com/ksirivad-2022-01-31_06:33:46-orch:cephadm-master-distro-basic-smithi/

**Comment by neha-ojha** [comment]
@gregsfortytwo any thoughts on a reproducer for https://tracker.ceph.com/issues/50089?

**Comment by kamoltat** [comment]
Was able to recreate the problem with this run: 
https://pulpito.ceph.com/ksirivad-2022-02-02_21:54:22-orch:cephadm-master-distro-basic-smithi/6656444/

/a/ksirivad-2022-02-02_21:54:22-orch:cephadm-master-distro-basic-smithi/6656444$ grep -nr "ranks.size" *

ceph-17.0.0-10469-g29e1fc17/src/mon/MonMap.h: 404: FAILED ceph_assert(m < ranks.size())

**Comment by gregsfortytwo** [comment]
> @gregsfortytwo any thoughts on a reproducer for https://tracker.ceph.com/issues/50089?

I looked at this briefly and I don't remember exactly what I had concluded the issue was, except that I expected the crash to occur 100% of the time under certain conditions. I'd first try removing only the highest-ranked monitor and only removing a single interior-rank monitor and see if one of those does it. The bug was somewhere in how the Elector (or its subcomponents) handled the mapping from mon ID to mon rank, and moving around the data structures indexed by rank.

**Comment by neha-ojha** [comment]
> > @gregsfortytwo any thoughts on a reproducer for https://tracker.ceph.com/issues/50089?
> 
> I looked at this briefly and I don't remember exactly what I had concluded the issue was, except that I expected the crash to occur 100% of the time under certain conditions. I'd first try removing only the highest-ranked monitor and only removing a single interior-rank monitor and see if one of those does it. The bug was somewhere in how the Elector (or its subcomponents) handled the mapping from mon ID to mon rank, and moving around the data structures indexed by rank.

thanks @gregsfortytwo, this PR now reproduces the issue!

**Comment by kamoltat** [comment]
Closing and Moving this PR to  #44993

**Pull request closed without merging**
