### PR TITLE
vstart: Add a --ipv6 option to vstart that sets ms_bind_ipv6

### PR DESCRIPTION
**Pull request by matthewoliver**
If you want to deploy a vstart cluster over ipv6, you want the msgr to
bind to ipv6 or things don't go well.

This patch adds a `--ipv6` option that does 2 things:

1. adds `ms bind ipv6 = true` so the msgr on all components bind to
ipv6.
2. If the ip is set to `127.0.0.1` usually set by `-l` and `--ipv6` is
also passed then change the ip to `[::1]`.
3. If `--cephadm` is passed in as well set the `ms bind ipv6` in the
global config store.

I guess 3 may actually cover 1.

Signed-off-by: Matthew Oliver <moliver@suse.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by batrick** [comment]
please rebase

**Comment by matthewoliver** [comment]
Rebased and added setting `ms bind ipv6` to config store when `--cephadm` so containers talk and bind to both ipv6 and ipv4

**Comment by matthewoliver** [comment]
Addressed a few more ipv6 vstart issues.

**Comment by matthewoliver** [comment]
I wonder if I should add changes to cstart.sh in this patch too? or should we consider that out of scope?

**Comment by sebastian-philipp** [comment]
adding cephadm it keep this on my radar.

**Comment by matthewoliver** [comment]
I'll need to rebase this and make sure the public-network check added here: https://github.com/ceph/ceph/pull/36335
becomes ipv6 friendly. This is just a comment so I remember to do that thing :)

**Comment by sebastian-philipp** [comment]
unstale

**Comment by sebastian-philipp** [comment]
:cry:

**Pull request closed without merging**
