### PR TITLE
rbd-mirror: remove journal-specific logic from image replay and bootstrap state machines

### PR DESCRIPTION
**Pull request by dillaman**
## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by dillaman** [comment]
This is the third (and final) portion of issue 41556 [1]
(pending teuthology test run)

[1] https://tracker.ceph.com/issues/41556

**Comment by dillaman** [comment]
http://pulpito.ceph.com/jdillaman-2020-01-09_16:20:49-rbd-wip-jd-testing-distro-basic-smithi/

(memory leak fixed in re-push of last commit)

**Comment by trociny** [comment]
@dillaman Observing this crash [1]:
```
/ceph/teuthology-archive/trociny-2020-01-10_18:15:56-rbd-wip-mgolub-testing-distro-basic-smithi/4653661/remote/smithi146/log/cluster1-client.mirror.0.13747.log.gz

2020-01-10T19:40:15.290+0000 7efecd2b4700 -1 /build/ceph-15.0.0-9183-g3d3eb46/src/tools/rbd_mirror/image_replayer/journal/Replayer.cc: In function 'void rbd::mirror::image_replayer::journal::Replayer<ImageCtxT>::close_local_image() [with ImageCtxT = librbd::ImageCtx]' thread 7efecd2b4700 time 2020-01-10T19:40:15.296183+0000
/build/ceph-15.0.0-9183-g3d3eb46/src/tools/rbd_mirror/image_replayer/journal/Replayer.cc: 496: FAILED ceph_assert(m_state_builder->local_image_ctx != nullptr)

 ceph version 15.0.0-9183-g3d3eb46 (3d3eb467f550d0bef299a35f35b3ce377f2c9c32) octopus (dev)
 1: (ceph::__ceph_assert_fail(char const*, char const*, int, char const*)+0x152) [0x7efed291a258]
 2: (ceph::__ceph_assertf_fail(char const*, char const*, int, char const*, char const*, ...)+0) [0x7efed291a433]
 3: (rbd::mirror::image_replayer::journal::Replayer<librbd::ImageCtx>::close_local_image()+0x29c) [0x56244916eb6c]
 4: (rbd::mirror::image_replayer::journal::Replayer<librbd::ImageCtx>::handle_wait_for_event_replay(int)+0x68) [0x56244916ee68]
 5: (ThreadPool::PointerWQ<Context>::_void_process(void*, ThreadPool::TPHandle&)+0x147) [0x5624490a7ae7]
 6: (ThreadPool::worker(ThreadPool::WorkThread*)+0x9fa) [0x7efed29cdeda]
 7: (ThreadPool::WorkThread::entry()+0x11) [0x7efed29cedc1]
 8: (()+0x76db) [0x7efed24976db]
 9: (clone()+0x3f) [0x7efed147588f]
```
There are other failures for this run [2] though I have not had chance to look at them yet, if they are related.
[1] http://pulpito.ceph.com/trociny-2020-01-10_18:15:56-rbd-wip-mgolub-testing-distro-basic-smithi/4653661/
[2] http://pulpito.ceph.com/trociny-2020-01-10_18:15:56-rbd-wip-mgolub-testing-distro-basic-smithi/

**Comment by trociny** [comment]
@ceph-jenkins retest this please

**Comment by dillaman** [comment]
FYI - There was one additional failure not related to "out of order ops" that I am tracking here [1] since it's unrelated to this PR.

[1] https://tracker.ceph.com/issues/43589

**Pull request merged**
