### PR TITLE
mgr: dashboard improvements

### PR DESCRIPTION
**Pull request by jcsp**
This is the refreshed health page view.

Depends on https://github.com/ceph/ceph/pull/15643, https://github.com/liewegas/ceph/pull/51

### CODE REVIEW

**Comment by liewegas** [comment]
ready for rebase

**Comment by jcsp** [comment]
@liewegas @dillaman this is rebased now

**Comment by dillaman** [comment]
@jcsp thx

**Comment by jcsp** [comment]
This should be good to go!

**Pull request merged**
