### PR TITLE
osd: trigger the cache agent after a promotion

### PR DESCRIPTION
**Pull request by dachary**
When a proxy read happens, the object promotion is done in parallel. The
agent_choose_mode function must be called to reconsider the situation.

http://tracker.ceph.com/issues/12673 Fixes: #12673

Signed-off-by: Loic Dachary <ldachary@redhat.com>

### CODE REVIEW

**Comment by dachary** [comment]
I tried to test it manually with the script in the descirption of http://tracker.ceph.com/issues/12673 and it works (i.e. the object is evicted as it should, and the log show something consistent). I'm however unsure this is a proper fix. What do you think ?

**Comment by tchaikov** [comment]
tested
```
$ ceph df
*** DEVELOPER MODE: setting PATH, PYTHONPATH and LD_LIBRARY_PATH ***
GLOBAL:
    SIZE     AVAIL     RAW USED     %RAW USED
    664G      158G         505G         76.08
POOLS:
    NAME     ID     USED     %USED     MAX AVAIL     OBJECTS
    rbd      0         0         0        54233M           0
    slow     1       904         0        54233M           1
    fast     2         0         0        54233M           0
$ rados -p slow get obj3 /tmp/obj3
$ ceph df
*** DEVELOPER MODE: setting PATH, PYTHONPATH and LD_LIBRARY_PATH ***
GLOBAL:
    SIZE     AVAIL     RAW USED     %RAW USED
    664G      158G         505G         76.08
POOLS:
    NAME     ID     USED     %USED     MAX AVAIL     OBJECTS
    rbd      0         0         0        54233M           0
    slow     1       904         0        54233M           1
    fast     2         0         0        54233M           0
```

@dachary do you mind adding a test for it? `ceph df` support `--format` also.

**Comment by dachary** [comment]
@tchaikov I'm glad this fix makes sense to you :-) I'll ask for a second look and add the test.

**Comment by dachary** [comment]
@tchaikov the tests are in a different commit because they will probably conflict when backporting.

**Comment by tchaikov** [comment]
`Reviewed-by: Kefu Chai <kchai@redhat.com>` after the rados qa run

**Comment by tchaikov** [comment]
tested at

- http://pulpito.ceph.com/kchai-2015-08-29_02:02:16-rados-wip-kefu-testing---basic-multi/
- http://pulpito.ceph.com/kchai-2015-08-30_06:42:05-rados-wip-kefu-testing---basic-multi/
- http://pulpito.ceph.com/kchai-2015-08-30_06:43:51-rados-wip-kefu-testing---basic-multi/

the failed tests are known issues are either 
- being fixed https://github.com/ceph/ceph/pull/5713
- tracked at http://tracker.ceph.com/issues/12861

**Pull request merged**
