### PR TITLE
[WIP] kv/RocksDBStore: Improved RocksDB Settings and Tombstone behavior

### PR DESCRIPTION
**Pull request by markhpc**
Multi-part PR for implementing RocksDB tuning improvements for higher performance and better tombstone cleanup during iteration.  So far mostly just rocksdb tuning settings from the new blog article, last-ditch attempts to compact when data gets too old, and compaction during iteration when we have an excessively high number of tombstone entries.  Does not yet solve the problem of slow iteration over tombstones in memtables.  That will likely require issuing a per-coumn family memtable flush.  Thus, next step is per-column family memtable flushing and DB compaction on rmkey(s). 

See commit messages from this PR and addition information at:

https://tracker.ceph.com/issues/53926
https://github.com/ceph/ceph.io/pull/413

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [X] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [X] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [X] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by markhpc** [comment]
Some generic 1 OSD sanity benchmarks:

RBD 4KB IOPS (higher is better)
test | main | wip-faster-rocksdb
-- | -- | --
randread | 114597 | 113057
randwrite | 75530 | **94072**
read | 28192 | 29888
write | 298033 | 322859

RBD 4KB Cycles/OP (lower is better)
test | main | wip-faster-rocksdb
-- | -- | --
randread | 221096 | 224686
randwrite | 585403 | **560758**
read | 189125 | 186563
write | 30013 | **26119**

RBD 4KB Lat (lower is better)
test | main (avg ms) | main (99% ms) | wip-faster-rocksdb (avg ms) | wip-faster-rocksdb (99% ms)
-- | -- | -- | -- | --
randread | 4.701 | 43.385 | 4.812 | 41.353
randwrite | 8.065 | 67.158 | **6.060** | **34.275**
read | 19.359 | 163.414 | **17.319** | **90.735**
write | 1.714 | 3.113 | **1.583** | **2.695**

RGW:
test | main | wip-faster-rocksdb
-- | -- | --
puts/second | 5536 | 5515
list time (seconds) | **593** | 718
gets/second | 12743 | 12760
deletes/second | 7187 | **7832**

Overall write and delete gains as expected (though we may need more RGW instances to see the write benefit in the hsbench test).  bucket list performance is down, which may be consistent with extra overhead of reads in a bigger L0 with more data and overlapping key ranges (some potential evidence of this also with limited CPU and compression enabled on in the blog article).  It's possible that on a real cluster with multiple OSDs we don't see the effect of the list performance impact due to bucket index sharding across multiple OSDs.

**Comment by markhpc** [comment]
@baergj yeah, my hope is that we can perhaps back this off even farther if the other methods to compact during iteration and compact/flush on hitting a certain number of deletes between compactions.  Maybe we only fall back on that every 24 hours or something.

Generally speaking we are going to increase write amp here though.  One possible way to claw some of that back could be compression.  I don't think it's helping with write-amp much for RBD, but RGW it appeared to have a pretty massive effect.

**Comment by baergj** [comment]
I wonder if this is starting to approach the limit of what makes sense for index OSDs vs. data OSDs, given the vastly different workloads between the two of them?

FWIW, I had also wondered about backing TTL off to 24h+ for data OSDs, but we haven't had much reason to apply TTL to our data OSDs. IIRC rocksdb had a 30day default TTL; not sure if that's still there at HEAD.

**Review by aclamk — APPROVED** [review]
Let's get it testing!

**Comment by ljflores** [comment]
@markhpc @yaarith somehow this PR has a telemetry commit in it?

**Comment by yaarith** [comment]
@ljflores @markhpc interesting, looks like the original commit (https://github.com/ceph/ceph/pull/47001/commits/b8bbf642c1bc985e5e08639f44adc0e0d7c686da) was merged in July 21, when Mark created this PR, so this might have been a rebase/fork issue. I'll check to see that there are no issues with the second commit in the telemetry code.

**Comment by yaarith** [comment]
The telemetry code looks ok to me.

**Pull request merged**
