### PR TITLE
doc/dev/cephadm: fix host maintenance enter/exit syntax -

### PR DESCRIPTION
**Pull request by RanjiniMandyam**
Signed-off-by: Ranjini Mandyam Narasiodeyar <rmandyam@rmandyam.remote.csb>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [x] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [x] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by RanjiniMandyam** [comment]
@adk3798 As per the discussion, I have created the PR for the host maintenance syntax edits. Request you to review and let me know if it looks okay..

**Review by anthonyeleven — APPROVED** [review]
Docs LGTM.

Note:  `src/pybind/mgr/dashboard/frontend/cypress/integration/cluster/hosts.po.ts`  contains a button labeled `enter-maintenance`. @adk3798 might we want to align that as well?

**Review by adk3798 — APPROVED** [review]
LGTM

**Comment by adk3798** [comment]
> Docs LGTM.
> 
> Note: `src/pybind/mgr/dashboard/frontend/cypress/integration/cluster/hosts.po.ts` contains a button labeled `enter-maintenance`. @adk3798 might we want to align that as well?

I don't know for sure but it looks like that's an internal naming the dashboard team is using for the action, which is fine. They don't need their naming to always match the command syntax. The one in this PR needed to be fixed because it was referencing the actual command and therefore needed the correct syntax to be useful.

**Comment by anthonyeleven** [comment]
> > Docs LGTM.
> > Note: `src/pybind/mgr/dashboard/frontend/cypress/integration/cluster/hosts.po.ts` contains a button labeled `enter-maintenance`. @adk3798 might we want to align that as well?
> 
> I don't know for sure but it looks like that's an internal naming the dashboard team is using for the action, which is fine. They don't need their naming to always match the command syntax. The one in this PR needed to be fixed because it was referencing the actual command and therefore needed the correct syntax to be useful.

Ack, I suspected so but wanted to be sure.

**Pull request merged**
