### PR TITLE
crimson/os/seastore/cache: report lru usage/in/out with trans and extent type

### PR DESCRIPTION
**Pull request by cyx1231st**
The main change refer to the last commit, the rest are related refactors/cleanups.

The report looks like:
```
INFO  2024-08-14 15:46:35,714 [shard 0:main] seastore_cache - Cache::LRU::get_stats:
lru total(64.00MiB,4.52KiB,14501)
  data(55.79MiB,4.00KiB,14283)
  mdat(7.88MiB,60.63KiB,133)
  phys(0.33MiB,4.00KiB,85)
lru io: trans-in(0.40MiB/s,5.71KiB,72.50ps) out(0.28MiB/s,5.06KiB,56.50ps); other-in(0.00MiB/s,-nanKiB,0.00ps) out(0.12MiB/s,7.76KiB,16.50ps)
  MUTATE: in(0.37MiB/s,5.95KiB,63.50ps) out(0.23MiB/s,4.59KiB,51.00ps)
    data: in(0.22MiB/s,4.00KiB,57.50ps) out(0.20MiB/s,4.00KiB,50.50ps)
    mdat: in(0.13MiB/s,45.33KiB,3.00ps) out(0.03MiB/s,64.00KiB,0.50ps)
    phys: in(0.01MiB/s,4.00KiB,3.00ps) out(0.00MiB/s,-nanKiB,0.00ps)
  TRIM_DIRTY: in(0.02MiB/s,4.00KiB,4.50ps) out(0.02MiB/s,4.00KiB,4.00ps)
    data: in(0.00MiB/s,-nanKiB,0.00ps) out(0.02MiB/s,4.00KiB,4.00ps)
    mdat: in(0.00MiB/s,-nanKiB,0.00ps) out(0.00MiB/s,-nanKiB,0.00ps)
    phys: in(0.02MiB/s,4.00KiB,4.50ps) out(0.00MiB/s,-nanKiB,0.00ps)
  TRIM_ALLOC: in(0.02MiB/s,4.00KiB,4.50ps) out(0.04MiB/s,24.00KiB,1.50ps)
    data: in(0.00MiB/s,-nanKiB,0.00ps) out(0.00MiB/s,4.00KiB,1.00ps)
    mdat: in(0.00MiB/s,-nanKiB,0.00ps) out(0.03MiB/s,64.00KiB,0.50ps)
    phys: in(0.02MiB/s,4.00KiB,4.50ps) out(0.00MiB/s,-nanKiB,0.00ps)
...
INFO  2024-08-14 15:46:35,715 [shard 0:main] seastore - SeaStore: cache lru: total(255.96MiB,4.53KiB,57895) in(1.35MiB/s,4.64KiB,298.38ps) out(1.34MiB/s,4.86KiB,282.86ps); per-shard: total(63.99MiB,4.53KiB,14473) in(0.34MiB/s,4.64KiB,74.59ps) out(0.33MiB/s,4.87KiB,70.59ps)
```
This prints the details of LRU cache in shard 0, and a summary at the seastore level.

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [x] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Comment by cyx1231st** [comment]
jenkins test submodules

**Comment by cyx1231st** [comment]
make check failed: 
```
ERROR 2024-08-14 09:20:36,882 [shard 0:main] test - caller: init, extent type: RETIRED_PLACEHOLDER, input generation: 2, expected generation : 1, adjust result from EPM: 2
/home/jenkins-build/build/workspace/ceph-pull-requests/src/test/crimson/seastore/test_transaction_manager.cc:1046: Failure
Expected equality of these values:
  expected_generations[t][gen]
    Which is: '\x1' (1)
  epm_gen
    Which is: '\x2' (2)
```

**Comment by cyx1231st** [comment]
^ Fix inplace in the commit "crimson/os/seastore/seastore_types: unify checks to the extent types"

**Comment by cyx1231st** [comment]
jenkins test api

**Comment by cyx1231st** [comment]
https://pulpito.ceph.com/yingxin-2024-08-16_01:59:29-crimson-rados-wip-yingxin-testing-2024-08-15-1551-distro-default-smithi/, specifically:
* 7857439: https://tracker.ceph.com/issues/66852

No new issues.

**Review by athanatos — APPROVED** [review]

**Review by xxhdx1985126 — APPROVED** [review]

**Pull request merged**
