### PR TITLE
XIO: Isolate the frequently accessed atomic variable 'connected' on a separate cache line

### PR DESCRIPTION
**Pull request by vsjulu**
@tchaikov  I am re-submitting the changes to isolate the 'connected' variable on a cache line. Since the last discussion, you had one remaining comment - you wanted to remove the 'pad' and instead align the next data item ( entitiy_inst_t peer) in the structure. We want to stick to the pad because we dont want to tie this to whatever be the next data item. The comment conveys the idea to whoever is going through the code. If we align the next data item and a new item is introduced again in between, it may introduce more data items into the same cache line..

### CODE REVIEW

**Comment by mattbenjamin** [comment]
Ok, is there a blocker on this conceptually?

**Comment by vsjulu** [comment]
@mattbenjamin -  No, this is not blocking anything. It is a part of performance enhancement though.

**Comment by mattbenjamin** [comment]
Kefu is correct, GCC and clang compilers will emit warnings regarding this with our current compile settings.  Can you fix?
-tx

**Comment by athanatos** [comment]
It doesn't look like there's much movement on this one, so I'm going to close it for now

@vsjulu Feel free to reopen once you get a chance to address the comments!

**Pull request closed without merging**
