### PR TITLE
rgw: code to display the complete user id that includes tenant, names…

### PR DESCRIPTION
**Pull request by pritha-srivastava**
…pace,

and id for a GET request to admin ops for user info.

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Comment by cbodley** [comment]
this change broke at least one api test:
```
2024-02-05 10:23:18,962.962 INFO:__main__:----------------------------------------------------------------------
2024-02-05 10:23:18,963.963 INFO:__main__:Traceback (most recent call last):
2024-02-05 10:23:18,963.963 INFO:__main__:  File "/home/jenkins-build/build/workspace/ceph-api/qa/tasks/mgr/dashboard/test_rgw.py", line 591, in test_create_get_update_delete_w_tenant
2024-02-05 10:23:18,963.963 INFO:__main__:    self.assertEqual(data['user_id'], 'teuth-test-user')
2024-02-05 10:23:18,963.963 INFO:__main__:AssertionError: 'test01$teuth-test-user' != 'teuth-test-user'
```
to make breaking changes to APIs, we usually need to create a 'version 2' and leave the behavior of v1 as is. for this one, maybe we just add a query param like `&full-user-id` to enable the new output?
```c++
bool full_user_id = false;
RESTArgs::get_bool(s, "full-user-id", false, &full_user_id);
```
then the dashboard would need to add that param

**Comment by pritha-srivastava** [comment]
> this change broke at least one api test:
> 
> ```
> 2024-02-05 10:23:18,962.962 INFO:__main__:----------------------------------------------------------------------
> 2024-02-05 10:23:18,963.963 INFO:__main__:Traceback (most recent call last):
> 2024-02-05 10:23:18,963.963 INFO:__main__:  File "/home/jenkins-build/build/workspace/ceph-api/qa/tasks/mgr/dashboard/test_rgw.py", line 591, in test_create_get_update_delete_w_tenant
> 2024-02-05 10:23:18,963.963 INFO:__main__:    self.assertEqual(data['user_id'], 'teuth-test-user')
> 2024-02-05 10:23:18,963.963 INFO:__main__:AssertionError: 'test01$teuth-test-user' != 'teuth-test-user'
> ```
> 
> to make breaking changes to APIs, we usually need to create a 'version 2' and leave the behavior of v1 as is. for this one, maybe we just add a query param like `&full-user-id` to enable the new output?
> 
> ```c++
> bool full_user_id = false;
> RESTArgs::get_bool(s, "full-user-id", false, &full_user_id);
> ```
> 
> then the dashboard would need to add that param

@cbodley do I need to open a tracker issue for this? I believe I should, let me know.

**Comment by cbodley** [comment]
i like the change to add "full_user_id" and "namespace" fields without modifying the "user_id"

> @cbodley Does admin ops also allow the user to query individual fields, I haven't worked with them before, so I dont know how that works.

no, it's an http request that returns a json document. clients can parse out the pieces they care about. for example, you see the dashboard looking at `data['user_id']`

> do I need to open a tracker issue for this? I believe I should, let me know.

tracker issue for what, the dashboard part? we should try to update that in the same pr

**Comment by pritha-srivastava** [comment]
> i like the change to add "full_user_id" and "namespace" fields without modifying the "user_id"
> 
```bool full_user_id = false;
RESTArgs::get_bool(s, "full-user-id", false, &full_user_id);
```
Isn't the above needed for maintaining some sort of backward compatibility

> > @cbodley Does admin ops also allow the user to query individual fields, I haven't worked with them before, so I dont know how that works.
> 
> no, it's an http request that returns a json document. clients can parse out the pieces they care about. for example, you see the dashboard looking at `data['user_id']`
> 
> > do I need to open a tracker issue for this? I believe I should, let me know.
> 
> tracker issue for what, the dashboard part? we should try to update that in the same pr

**Comment by cbodley** [comment]
> Isn't the above needed for maintaining some sort of backward compatibility

nope! if we're only adding new fields, we won't break anything

**Comment by pritha-srivastava** [comment]
> > Isn't the above needed for maintaining some sort of backward compatibility
> 
> nope! if we're only adding new fields, we won't break anything

So IIUC, the only part remaining is to figure out how to make changes in the dashboard part?

**Comment by cbodley** [comment]
cc @nizamial09 this adds a "full_user_id" to the "GET /admin/user" response for https://bugzilla.redhat.com/show_bug.cgi?id=2255255

could you help us track down all of the places in dashboard and api tests that need updating?

**Comment by nizamial09** [comment]
For the back-end, we have this GET request which fetches the user info. Here we are doing [our own processing to create a `full_user_id`](https://github.com/ceph/ceph/blob/main/src/pybind/mgr/dashboard/controllers/rgw.py#L529) I guess and calling it `uid`. If we are getting this info from the admin ops API itself, maybe we can remove that logic and use that as our `uid`.

The easiest change would be to[ remove this](https://github.com/ceph/ceph/blob/main/src/pybind/mgr/dashboard/controllers/rgw.py#L568) `self._append_uid(request)` from here and do something like `result[uid] = result['full_user_id']` (assuming that `full_user_id` is indeed the `tenat$username`) and return the `result`. This way the front-end can be left without any further modifications and even the API versioning might not be needed. And I would expect the tests might pass as well without doing anything.

**Comment by pritha-srivastava** [comment]
> cc @nizamial09 this adds a "full_user_id" to the "GET /admin/user" response for https://bugzilla.redhat.com/show_bug.cgi?id=2255255
> 
> could you help us track down all of the places in dashboard and api tests that need updating?

@nizamial09 : can you review the last commit and also point out changes that I may have missed. (provided that there are no jenkins failure here)

**Comment by nizamial09** [comment]
thank you @pritha-srivastava. looks good to me.

only thing left is to adapt the unit test in a couple of places which would be the below patch.
```
diff --git a/src/pybind/mgr/dashboard/tests/test_rgw.py b/src/pybind/mgr/dashboard/tests/test_rgw.py
index d9b8593a7d7..b84838d1016 100644
--- a/src/pybind/mgr/dashboard/tests/test_rgw.py
+++ b/src/pybind/mgr/dashboard/tests/test_rgw.py
@@ -282,6 +282,7 @@ class RgwUserControllerTestCase(ControllerTestCase):
         mock_proxy.return_value = {
             'tenant': '',
             'user_id': 'my_user_id',
+            'full_user_id': 'my_user_id',
             'keys': [],
             'swift_keys': []
         }
@@ -297,6 +298,7 @@ class RgwUserControllerTestCase(ControllerTestCase):
         mock_proxy.return_value = {
             'tenant': '',
             'user_id': 'my_user_id',
+            'full_user_id': 'my_user_id',
             'keys': [],
             'swift_keys': []
         }
```

also we can remove the `_append_uid()` function since its a dead-code now.

**Comment by pritha-srivastava** [comment]
jenkins test dashboard

**Comment by pritha-srivastava** [comment]
jenkins test make check arm64

**Comment by pritha-srivastava** [comment]
jenkins test dashboard cephadm

**Comment by nizamial09** [comment]
jenkins test windows

**Review by nizamial09 — APPROVED** [review]
Thank you @pritha-srivastava 

Dashboard e2e failures are unrelated and traced differently. Atleast in the e2e the rgw users page tests are passing which is a good sign so dashboard lgtm.

**Review by cbodley — APPROVED** [review]
rgw bits look great 👍

**Comment by cbodley** [comment]
@nizamial09 i'll be running this through the rgw suite. do you want to do any other testing? do any of these 'ceph dashboard' jenkins check failures look related?

**Comment by cbodley** [comment]
jenkins test windows

**Comment by cbodley** [comment]
passed rgw qa in https://pulpito.ceph.com/cbodley-2024-02-16_18:58:19-rgw-wip-cbodley-testing-distro-default-smithi/

**Comment by cbodley** [comment]
@pritha-srivastava the squid branch has already forked. if you'd like this change in squid, please prepare a backport

**Pull request merged**
