### PR TITLE
jewel: mds: log rotation doesn't work if mds has respawned

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/19466

### CODE REVIEW

**Comment by smithfarm** [comment]
This backport needs 3ba63063 which appears challenging to backport.

**Comment by jcsp** [comment]
If the jewel branch doesn't already have the compat.h stuff then I presume it doesn't work on the non-linux platforms already, so we can just s/ceph_pthread_setname/pthread_setname_np/ in this patch.

@wjwithagen am I right here?  You're not relying on compatibility stuff in the jewel branch for the freebsd or anything like that?

**Comment by smithfarm** [comment]
@wjwithagen Ping, did you see the question in the previous comment?

**Comment by wjwithagen** [comment]
@jcsp @smithfarm 
I'm not really tracking older releases for FreeBSD, so I'm not concerned about Jewel on FreeBSD.
The current set of packages is build from master, and only after the official luminous release do I want to start cutting "stable" releases for FreeBSD.
So backports to Jewel are not relevant to FreeBSD.

**Comment by smithfarm** [comment]
@batrick @ukernel @jcsp This passed an fs suite at http://tracker.ceph.com/issues/20613#note-7 with two occurrences of the following transient failure: http://tracker.ceph.com/issues/16881

I see @batrick has already approved, but I'll leave it to you guys to merge after considering the implications of http://tracker.ceph.com/issues/16881 - thanks!

**Pull request merged**
