### PR TITLE
buffer.cc: Using lambda for buffers iterations

### PR DESCRIPTION
**Pull request by shinobu-x**
Signed-off-by: Shinobu Kinjo <shinobu@redhat.com>

### CODE REVIEW

**Comment by mattbenjamin** [comment]
@branch-predictor well, it's prettier.  I think performance counts a lot more, though;  @adamemerson, @cbodley (mr. lambda ;) thoughts?

**Comment by branch-predictor** [comment]
@mattbenjamin Why not change it to ```for (auto& i : _buffers)``` ? That's already prettier and with no performance implications.

**Comment by mattbenjamin** [comment]
@branch-predictor sounds reasonable to me

**Comment by shinobu-x** [comment]
test this please

**Comment by adamemerson** [comment]
There's no performance inclination. When you look at the assembly for a template function like that that has a lambda or other inlinable function passed in, it compiles down to basically the same thing as doing it as a loop.

**Comment by branch-predictor** [comment]
@adamemerson sorry, but that's totally not true. Here's a disassembly of @shinobu-x version of buffer::list::zero(void) that I benchmarked:
```
(gdb) disassemble ceph::buffer::list::zero(void)                                                   
Dump of assembler code for function ceph::buffer::list::zero():                                    
   0x00000000009f1f30 <+0>:     push   %r12                                                        
   0x00000000009f1f32 <+2>:     push   %rbp                                                        
   0x00000000009f1f33 <+3>:     push   %rbx                                                        
   0x00000000009f1f34 <+4>:     sub    $0x10,%rsp                                                  
   0x00000000009f1f38 <+8>:     mov    (%rdi),%rbx                                                 
   0x00000000009f1f3b <+11>:    cmp    %rdi,%rbx                                                   
   0x00000000009f1f3e <+14>:    je     0x9f1f74 <ceph::buffer::list::zero()+68>                    
   0x00000000009f1f40 <+16>:    mov    %rdi,%r12                                                   
   0x00000000009f1f43 <+19>:    mov    %rsp,%rbp                                                   
   0x00000000009f1f46 <+22>:    nopw   %cs:0x0(%rax,%rax,1)                                        
   0x00000000009f1f50 <+32>:    lea    0x10(%rbx),%rsi                                             
   0x00000000009f1f54 <+36>:    mov    %rbp,%rdi                                                   
   0x00000000009f1f57 <+39>:    callq  0x9ec6a0 <ceph::buffer::ptr::ptr(ceph::buffer::ptr const&)> 
   0x00000000009f1f5c <+44>:    mov    %rbp,%rdi                                                   
   0x00000000009f1f5f <+47>:    callq  0x9f1f20 <ceph::buffer::ptr::zero()>                        
   0x00000000009f1f64 <+52>:    mov    %rbp,%rdi                                                   
   0x00000000009f1f67 <+55>:    callq  0x9ec970 <ceph::buffer::ptr::release()>                     
   0x00000000009f1f6c <+60>:    mov    (%rbx),%rbx                                                 
   0x00000000009f1f6f <+63>:    cmp    %rbx,%r12                                                   
   0x00000000009f1f72 <+66>:    jne    0x9f1f50 <ceph::buffer::list::zero()+32>                    
   0x00000000009f1f74 <+68>:    add    $0x10,%rsp                                                  
   0x00000000009f1f78 <+72>:    pop    %rbx                                                        
   0x00000000009f1f79 <+73>:    pop    %rbp                                                        
   0x00000000009f1f7a <+74>:    pop    %r12                                                        
   0x00000000009f1f7c <+76>:    retq                                                               
   0x00000000009f1f7d <+77>:    mov    %rax,%rbx                                                   
   0x00000000009f1f80 <+80>:    mov    %rbp,%rdi                                                   
   0x00000000009f1f83 <+83>:    callq  0x9ec970 <ceph::buffer::ptr::release()>                     
   0x00000000009f1f88 <+88>:    mov    %rbx,%rdi                                                   
   0x00000000009f1f8b <+91>:    callq  0x39aa80 <_Unwind_Resume@plt>  
```
And here's an ```for (auto& i : _buffers)``` version:
```
(gdb) disassemble ceph::buffer::list::zero(void)                               
Dump of assembler code for function ceph::buffer::list::zero():                
   0x00000000009f1f30 <+0>:     push   %rbp                                    
   0x00000000009f1f31 <+1>:     push   %rbx                                    
   0x00000000009f1f32 <+2>:     sub    $0x8,%rsp                               
   0x00000000009f1f36 <+6>:     mov    (%rdi),%rbx                             
   0x00000000009f1f39 <+9>:     cmp    %rbx,%rdi                               
   0x00000000009f1f3c <+12>:    je     0x9f1f59 <ceph::buffer::list::zero()+41>
   0x00000000009f1f3e <+14>:    mov    %rdi,%rbp                               
   0x00000000009f1f41 <+17>:    nopl   0x0(%rax)                               
   0x00000000009f1f48 <+24>:    lea    0x10(%rbx),%rdi                         
   0x00000000009f1f4c <+28>:    callq  0x9f1f20 <ceph::buffer::ptr::zero()>    
   0x00000000009f1f51 <+33>:    mov    (%rbx),%rbx                             
   0x00000000009f1f54 <+36>:    cmp    %rbx,%rbp                               
   0x00000000009f1f57 <+39>:    jne    0x9f1f48 <ceph::buffer::list::zero()+24>
   0x00000000009f1f59 <+41>:    add    $0x8,%rsp                               
   0x00000000009f1f5d <+45>:    pop    %rbx                                    
   0x00000000009f1f5e <+46>:    pop    %rbp                                    
   0x00000000009f1f5f <+47>:    retq                                           
```
Note the implicit call to copy constructor and destructor in lambda version. The "old" auto iterator version is also shorter.

**Comment by branch-predictor** [comment]
Before someone asks:
```
$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/7/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 7.2.0-1ubuntu1~14.04' --with-bugurl=file:///usr/share/doc/gcc-7/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-7 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=gcc4-compatible --disable-libstdcxx-dual-abi --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --with-system-zlib --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 7.2.0 (Ubuntu 7.2.0-1ubuntu1~14.04) 
```

**Comment by adamemerson** [comment]
@branch-predictor Well, that's surprising. I got he same results when I was comparing similar cases with gcc -s a while back. I'll have to see if something changed between then and now or if there's something about this case that makes it different.

**Comment by cbodley** [comment]
re: the performance delta, it's because these lambdas are taking a `const ceph::buffer::ptr p` by value. the extra construct/destruct involves expensive atomic ref-counting

performance concerns aside, this for_each(lambda) pattern has just as much boilerplate as the code it replaces:
```patch
-    for (std::list<ptr>::const_iterator it = _buffers.begin(); it != _buffers.end(); ++it) 
+    for_each(_buffers.begin(), _buffers.end(), [&b, align](const ceph::buffer::ptr p) {
```
i think this is an obvious win for the ranged-for syntax:
```c++
  for (auto& p : _buffers) {
```

**Comment by mattbenjamin** [comment]
yeah, it's actually the cleanest of the styles, IMO

**Pull request closed without merging**
