### PR TITLE
common: fix RWLock

### PR DESCRIPTION
**Pull request by XinzeChi**
we should reset locked to false before unlock

Signed-off-by: Xinze Chi <xinze@xsky.com>

### CODE REVIEW

**Comment by XinzeChi** [comment]
@tchaikov , Please review it. Thanks.

**Comment by dzafman** [comment]
The order doesn't matter here because these sub-classes are only used to create an auto variable that holds the lock.  The unlock in the destructor is called when it leaves scope.  There is no race which requires the ordering change.

**Comment by XinzeChi** [comment]
@dzafman , I do not know why we add unlock function for RLocker(). I think it is possible that the lock would be release twice.
There is the race: in Objecter::handle_osd_op_reply, when the op should be redirect , calling _op_submit(op, lc) ->lc.promote()->unlock().
But when return from handle_osd_op_reply , we also calling unlock (RWLock::~RLocker()) for rwlock.

**Comment by dzafman** [comment]
@XinzeChi The assumption is that this lock is never passed to another thread and that handle_os_op_reply() has locked rwlock and is responsible for doing the unlock.  Also, even though handle_os_op_reply() initially locked for read, after _op_submit() it may have been promoted to write.  Notice that the "RWLock::Context lc" isn't built from "RWLock::RLocker l" but from rwlock directly, so it isn't able to change the "bool locked" in RLocker.  Rlocker and Wlocker are exactly the same except for the initial lock type taken.

**Comment by XinzeChi** [comment]
@dzafman , RWLock is promoted to write and calling RWLock.unlock(), but 'bool locked' is not change and keep true, so when return from handle_osd_op_reply , we also calling RWLock.unlock (RWLock::~RLocker()) for rwlock. so the RWLock.unlock() is called twice.

**Pull request closed without merging**
