### PR TITLE
DNM: backport stretch clusters to nautilus

### PR DESCRIPTION
**Pull request by gregsfortytwo**
I don't think we want to merge this, but I've done the work for downstream. Putting up as an FYI. (Hopefully I can find the draft mode thing, but it's not visible yet?)

https://github.com/ceph/ceph/pull/35906

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by gregsfortytwo** [comment]
Okay, make check failure is caused by a test in ceph_test_argparse.py that was somehow missed in mainline before backport. There's a new commit to fix that at the end.

I ran things through teuthology at https://pulpito.ceph.com/gregf-2020-09-16_10:41:40-rados-wip-nautilus-stretch-distro-basic-smithi/ and those results look good. They did expose one bug with my backport of tests in cephtool/test.sh, so the force-push that's about to arrive is to fix that.

**Comment by neha-ojha** [comment]
https://github.com/neha-ojha/ceph/commit/87af537abc97962b584052129379b3a30aaa34e7 is needed to fix FTBS and the commands

**Comment by gregsfortytwo** [comment]
Jenkins test make check

**Comment by gregsfortytwo** [comment]
jenkins test make check

**Comment by gregsfortytwo** [comment]
jenkins test make check

**Comment by gregsfortytwo** [comment]
jenkins test make check

**Comment by tchaikov** [comment]
the test failure should be fixed by #40536

**Comment by tchaikov** [comment]
jenkins test api

**Pull request closed without merging**
