### PR TITLE
os/filestore/FileStore.cc: remove unneeded loop

### PR DESCRIPTION
**Pull request by dragonylffly**
Signed-off-by: Li Wang <li.wang@kylin-cloud.com>

### CODE REVIEW

**Comment by dachary** [comment]
jenkins test this please (test-erasure-eio.sh http://tracker.ceph.com/issues/17757)

**Comment by tchaikov** [comment]
@dragonylffly could you rebase this change?

**Comment by dragonylffly** [comment]
@tchaikov updated

**Comment by tchaikov** [comment]
http://pulpito.ceph.com/kchai-2017-03-06_11:46:50-rados-wip-kefu-testing---basic-mira/

**Pull request merged**
