### PR TITLE
squid: mgr/cephadm: bump monitoring stacks version

### PR DESCRIPTION
**Pull request by nizamial09**
## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Comment by nizamial09** [comment]
@adk3798 i also added the [alertmanager fix](https://github.com/ceph/ceph/pull/59373) here. so probably we can do a round of testing and get this in?

**Comment by adk3798** [comment]
> @adk3798 i also added the [alertmanager fix](https://github.com/ceph/ceph/pull/59373) here. so probably we can do a round of testing and get this in?

I haven't done a squid run in a while. I'll try to go through our open squid backport trackers and then include this in the run I do with them

**Comment by nizamial09** [comment]
jenkins test make check

**Comment by adk3798** [comment]
https://pulpito.ceph.com/adking-2024-11-11_04:01:43-orch:cephadm-wip-adk4-testing-2024-11-07-1210-squid-distro-default-smithi/

Failures:

- a number of upgrade tests failed due to https://tracker.ceph.com/issues/68802 as the patch hasn't been merged in the older branches the test was trying to upgrade from (it initially bootstrap with a ci image built from the tip of the branch)
- test_cephadm task failed for the same reason as the upgrade tests
- the nvmeof test actually failed for the same reason. I don't know why that test isn't using the image from the build and I'll probably change that, but that's the failure that occurred in this run
- 1 failure due to `rados/test_pool_quota.sh` failing, not familiar with the error, but looks unrelated to PRs in the run
- test_nfs task failed with
```
024-11-11T04:36:09.006 INFO:tasks.cephfs_test_runner:Traceback (most recent call last):
2024-11-11T04:36:09.006 INFO:tasks.cephfs_test_runner:  File "/home/teuthworker/src/git.ceph.com_ceph-c_5cac643e0c2c6484aecd3c481836e0c8a5cc6b15/qa/tasks/cephfs/test_nfs.py", line 1180, in test_cephfs_export_update_at_non_dir_path
2024-11-11T04:36:09.006 INFO:tasks.cephfs_test_runner:    self.update_export(self.cluster_id, "/testfile",
2024-11-11T04:36:09.006 INFO:tasks.cephfs_test_runner:AttributeError: 'TestNFS' object has no attribute 'update_export'
```
looks like an issue with the test to me.

Probably shouldn't merge anything nvmeof, nfs or upgrade related, otherwise looks okay.

**Comment by adk3798** [comment]
jenkins test make check

**Review by adk3798 — APPROVED** [review]

**Pull request merged**
