### PR TITLE
qa : misc fixes to stabilize test-erasure-code suite

### PR DESCRIPTION
**Pull request by guangyy**
Hi @dachary ,
I did some misc fix to stabilize the ec testing, please help to check. Thanks!

### CODE REVIEW

**Comment by dachary** [comment]
it looks better :-)

**Comment by guangyy** [comment]
Hi @dachary , this patch is proven to be stable on my local hosts. Thanks.

**Comment by dachary** [comment]
@guangyy why do you need to add these ?
<pre>
+    	CEPH_ARGS='' ./ceph --admin-daemon $dir/ceph-osd.${initial_osds[$shardid]}.asok config set \
+            filestore_fail_eio false || return 1
</pre>

**Comment by dachary** [comment]
I understand the logic of the test as follows:
* create an ec pool
* inject an error on a replica OSD via injectdataerr
* write / read an object known to belong to a PG that will trigger the error on this replica OSD
* verify the write / read succeeds (that's what rados_put_get do)
* verify the replica OSD crashed
* restart the replica OSD

I do not understand why other OSDs would crash and why it is necessary to re-activate all OSD instead of just the one that crashed. If I'm not mistaken the injectdataerr is not stored on disk and won't be poluting the OSD after it is restarted.

Maybe I'm missing something ?

P.S. It would be nice to have a detailed explanation of the commit in the commit message itself.

**Comment by guangyy** [comment]
Hi @dachary ,
When there is a read error (on replica), it will crash the primary OSD, and then the second replica will be promoted as primary and crash, so on so forth.. the purpose (the previously instability) was that it only tried to restart the primary.

Sure, I can explain in details in the commit message.

**Comment by dachary** [comment]
@guangyy ah, right, the primary crashes, not the secondary... what was I thinking. Indeed that's an obvious source of instability.

**Pull request merged**
