### PR TITLE
common/config: cleanup remove some unused macros

### PR DESCRIPTION
**Pull request by yaozongyou**
Signed-off-by: Yao Zongyou <yaozongyou@vip.qq.com>

### CODE REVIEW

**Comment by yaozongyou** [comment]
retest this please

**Comment by yaozongyou** [comment]
retest this please

**Comment by yaozongyou** [comment]
retest this please

**Comment by tchaikov** [comment]
- http://pulpito.ceph.com/kchai-2017-12-23_05:58:55-rados-wip-kefu-testing-2017-12-23-1241-distro-basic-mira/
- http://pulpito.ceph.com/kchai-2017-12-24_02:41:14-rados-wip-kefu-testing-2017-12-23-1241-distro-basic-mira/

the coredump is tracked by http://tracker.ceph.com/issues/22527

**Pull request merged**
