### PR TITLE
ceph-volume: fix broken workaround for atari partitions

### PR DESCRIPTION
**Pull request by guits**
broken by bea9f4b643ce32268ad79c0fc257b25ff2f8333c
This commits fixes that regression.

Fixes: https://tracker.ceph.com/issues/62001

### CODE REVIEW

**Review by asm0deuz — APPROVED** [review]
LGTM

**Review by adk3798 — APPROVED** [review]

**Comment by guits** [comment]
http://pulpito.ceph.com/gabrioux-2023-07-13_23:14:03-orch:cephadm-wip-guits-testing-4-2023-07-13-1258-distro-default-smithi/
http://pulpito.ceph.com/gabrioux-2023-07-14_01:35:55-orch:cephadm-wip-guits-testing-4-2023-07-13-1258-distro-default-smithi/
http://pulpito.ceph.com/gabrioux-2023-07-14_05:53:07-orch:cephadm-wip-guits-testing-4-2023-07-13-1258-distro-default-smithi/

**Comment by guits** [comment]
jenkins test make check

**Comment by guits** [comment]
jenkins test make check

**Comment by guits** [comment]
closing in favor of #52429

**Pull request closed without merging**
