### PR TITLE
Fix libatomic_ops-devel in SUSE and specfile cleanup

### PR DESCRIPTION
**Pull request by smithfarm**
Fixes: http://tracker.ceph.com/issues/16645

### CODE REVIEW

**Comment by smithfarm** [comment]
@ktdreyer @b-ranto Care to review?

gitbuilders now chewing on `wip-16645`

**Comment by b-ranto** [comment]
lgtm

**Comment by smithfarm** [comment]
gitbuilders failing - looks like cmake is not creating the `/usr/include/rados` directory

**Comment by ktdreyer** [comment]
LGTM, thanks

**Comment by smithfarm** [comment]
rebased, re-pushed

**Comment by smithfarm** [comment]
Passes gitbuilders. Merging.

**Pull request merged**
