### PR TITLE
jewel: cephfs metadata pool: deep-scrub error omap_digest != best guess omap_digest

### PR DESCRIPTION
**Pull request by dachary**
http://tracker.ceph.com/issues/18183

### CODE REVIEW

**Comment by dachary** [comment]
jenkins test this please

**Comment by smithfarm** [comment]
@tchaikov This passed a rados suite at http://tracker.ceph.com/issues/17851#note-45 with some (few, unrelated) failures as well as an fs suite at http://tracker.ceph.com/issues/17851#note-49

OK to merge?

**Comment by smithfarm** [comment]
This passed another rados run at http://tracker.ceph.com/issues/17851#note-53

**Comment by badone** [comment]
@dachary can we merge this?

**Pull request merged**
