### PR TITLE
run-cmake-check.sh: Actually run the tests

### PR DESCRIPTION
**Pull request by badone**
Actually run the tests from run-cmake-check.sh

Signed-off-by: Brad Hubbard <bhubbard@redhat.com>

### CODE REVIEW

**Comment by liewegas** [comment]
rebase?

**Comment by badone** [comment]
@liewegas sorry, fixed.

**Comment by liewegas** [comment]
Oh good, I was going to suggest on the other PR that you just run do_cmake.sh.  FWIW the git submodule line is probably no longer needed now..

**Comment by badone** [comment]
@liewegas thanks, I believe the git submodule line *is* still needed as I fell foul of this while testing (googletest/googlemock non-existent because that submodule not initialised). Thinking about getting rid of the modprobe of rbd.ko in a future commit though...

**Pull request merged**
