### PR TITLE
DNM: osd: force promote for ops which ec base pool can't handle

### PR DESCRIPTION
**Pull request by liewegas**
http://tracker.ceph.com/issues/14762

### CODE REVIEW

**Comment by liewegas** [comment]
Hmm, this cherry-pick brought with it a few other commits that added cases to the init_op_flags switch statement.  It now almost matches master (with teh exception of the locking forced promotions, which hasn't been backported yet).  I'm not sure it matters unless we are concerned about git archaeology...

**Comment by liewegas** [comment]
I take it back, need to handle the history cleanly as a bunch of other stuff is missing.  Needs further testing.

**Comment by smithfarm** [comment]
@liewegas Please rebase?

**Comment by dachary** [comment]
jenkins test this please (no logs)

**Comment by dachary** [comment]
jenkins test this please (no logs)

**Comment by liewegas** [comment]
I think we can drop this hammer backport at this point.

**Pull request closed without merging**
