### PR TITLE
mds: disallow layout changes for files with data

### PR DESCRIPTION
**Pull request by ukernel**
Fixes: #10737
Signed-off-by: Yan, Zheng <zyan@redhat.com>

### CODE REVIEW

**Comment by gregsfortytwo** [comment]
The existing Server::handle_client_layout() function has checks for this; it returns -ENOTEMPTY and looks at size and truncate_seq. We probably want to match that logic and return code (or change it to match this, if it's better?).

**Comment by ukernel** [comment]
updated

**Comment by gregsfortytwo** [comment]
Can you check this out @jcsp since I added a libcephfs test?

Don't think it's been through proper testing yet so wait to merge (I'll take care of the testing).

**Comment by jcsp** [comment]
Looks good to me.

**Comment by gregsfortytwo** [comment]
http://qa-proxy.ceph.com/teuthology/gregf-2015-02-10_16:11:29-fs-greg-fs-testing2---basic-multi/

in short: a few more errors than we like but all are known (mostly OSD ones) and the tests we need ran and passed.

**Pull request merged**
