### PR TITLE
jewel: class rbd.Image discard----OSError: [errno 2147483648] error discarding region

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/22191
http://tracker.ceph.com/issues/22913

### CODE REVIEW

**Comment by smithfarm** [comment]
This might be totally wrong. . . feel free to close.

**Comment by trociny** [comment]
@smithfarm Your cherry-pick (librbd.cc part) looks correct to me. But I think we also need to backport Image::discard change ec259dfd. And then I would change the release note a bit, removing " to match the C++ API's Image::discard method".

**Comment by smithfarm** [comment]
@trociny Done - please re-review the pending release note.

**Comment by smithfarm** [comment]
retest this please

**Comment by smithfarm** [comment]
This PR is included in the integration run at: http://tracker.ceph.com/issues/21742#note-13

So far, one rbd suite with 78 jobs passed. Another one, with 154 jobs, is scheduled.

**Comment by smithfarm** [comment]
RBD integration run passed at http://tracker.ceph.com/issues/21742#note-13

@dillaman OK to merge?

**Pull request merged**
