### PR TITLE
mon: "ceph osd crush rule rename" support

### PR DESCRIPTION
**Pull request by xiexingguo**
User may specify a rule with the same name of the pool that it serves.
Since a pool can be renamed, so does the rule.

Signed-off-by: xie xingguo <xie.xingguo@zte.com.cn>

### CODE REVIEW

**Comment by xiexingguo** [comment]
@liewegas Ping

**Comment by xiexingguo** [comment]
@liewegas Can we get these two commands into Luminous too? They might be helpful wrappers for the new "device-class" feature.

**Comment by liewegas** [comment]
http://pulpito.ceph.com/sage-2017-08-24_16:14:07-rados-wip-sage-testing-20170824a-distro-basic-smithi/

**Comment by liewegas** [comment]
https://github.com/ceph/ceph/pull/17260

**Pull request merged**
