### PR TITLE
qa/standalone: bugfix for wait_for_scrub

### PR DESCRIPTION
**Pull request by liangmingyuanneo**
Further fix for https://github.com/ceph/ceph/pull/57888

https://tracker.ceph.com/issues/67818

Signed-off-by: Mingyuan Liang <liangmingyuan@baidu.com>

### CODE REVIEW

**Comment by ronen-fr** [comment]
We have a separate problem, which is unrelated to this PR, nor to the previous addition of the wait.
See https://github.com/ceph/ceph/pull/59437

I'd recommend checking the effect of 59437 before making any more attempts.

**Comment by rzarzynski** [comment]
https://github.com/ceph/ceph/pull/59437 got merged 2 days ago. Let's see.

**Comment by liangmingyuanneo** [comment]
@ronen-fr @rzarzynski @ljflores  The job in https://github.com/ceph/ceph/pull/59437 is very excellent, but if I'm not wrong, this pr is necessary for solving https://tracker.ceph.com/issues/67818. 

```
function wait_for_scrub() {
    local pgid=$1
    local last_scrub="$2"
    local sname=${3:-last_scrub_stamp}

    for ((i=0; i < $TIMEOUT; i++)); do
        if test "$(get_last_scrub_stamp $pgid $sname)" '>' "$last_scrub" ; then
            return 0
        fi
        sleep 1
    done
    return 1
}
```

If TIMEOUT is set to 1 before calling `wait_for_scrub()`, there is no sleeping before judgement, so `get_last_scrub_stamp` may equal with `$last_scrub`, then return 1. So IMO, another judgement is essential after sleep for $TIMEOUT.

Anyway, if you think this pr is unnecessary, I will just revert https://github.com/ceph/ceph/pull/57888, which is solved by https://github.com/ceph/ceph/pull/59437.

**Comment by ronen-fr** [comment]
checking...

**Comment by liangmingyuanneo** [comment]
> Instead - maybe just making sure that TIMEOUT is not <2 (failing the test if it is.

@ronen-fr  Done, please review at your time.

**Comment by ronen-fr** [comment]
> @ronen-fr Done, please review at your time.

Not exactly the change I've suggested, but it will probably work anyway

**Review by ronen-fr — APPROVED** [review]

**Comment by ronen-fr** [comment]
@yuriw - specifically, the Teu tests should include the standalone suite

**Comment by liangmingyuanneo** [comment]
jenkins test make check

**Comment by liangmingyuanneo** [comment]
jenkins test windows

**Comment by ljflores** [comment]
Rados approved: https://tracker.ceph.com/projects/rados/wiki/MAIN#httpstrackercephcomissues68911

**Pull request merged**
