### PR TITLE
ceph-disk: key management support

### PR DESCRIPTION
**Pull request by dachary**
http://tracker.ceph.com/issues/14669

### CODE REVIEW

**Comment by dachary** [comment]
<code>cw ceph-qa-suite --verbose --teuthology-git-url http://github.com/dachary/teuthology --teuthology-branch openstack --ceph-qa-suite-git-url http://github.com/ceph/ceph-qa-suite --suite-branch master --ceph-git-url http://github.com/dachary/ceph --ceph wip-14669-key-management --suite ceph-disk --upload</code>

* **running** http://167.114.232.46:8081/ubuntu-2016-02-26_12:12:58-ceph-disk-wip-14669-key-management---basic-openstack/

**Comment by dachary** [comment]
@liewegas I believe this is ready for your review. Running integration tests for the record and also because they were not run on Ubuntu 14.04 yet.

**Comment by dachary** [comment]
<code>cw ceph-qa-suite --verbose --teuthology-git-url http://github.com/dachary/teuthology --teuthology-branch openstack --ceph-qa-suite-git-url http://github.com/ceph/ceph-qa-suite --suite-branch master --ceph-git-url http://github.com/dachary/ceph --ceph wip-14669-key-management --suite ceph-disk --upload</code>

* **running**

**Comment by dachary** [comment]
@liewegas I think the scenarii we discussed are covered by https://github.com/dachary/ceph/commit/886c94fc123328abe7abac4001fc34b4e3f71e77 . When prepared the lockbox creates osd-uuid, journal-uuid, block-uuid files. When activated it ceph-disk trigger each of them  ( https://github.com/dachary/ceph/commit/c1f1cc4ee6640c12e5cef67c17cb727e752774c8#diff-cca3df73f74b7cc44c31596303d95b44R2343 )

**Comment by dachary** [comment]
<code>cw ceph-qa-suite --verbose --teuthology-git-url http://github.com/dachary/teuthology --teuthology-branch openstack --ceph-qa-suite-git-url http://github.com/ceph/ceph-qa-suite --suite-branch master --ceph-git-url http://github.com/dachary/ceph --ceph wip-14669-key-management --suite ceph-disk --upload</code>

* **running** http://167.114.243.73:8081/ubuntu-2016-02-29_11:40:54-ceph-disk-wip-14669-key-management---basic-openstack/

**Comment by liewegas** [comment]
The next step here is to support the block.db and block.wal devices, too.  
That'll just be a matter of adding them to the NAMES list (at least for 
activate), right?

**Comment by dachary** [comment]
@liewegas yes, that should be straightforward

**Comment by dachary** [comment]
<pre>
test/journal/test_JournalPlayer.cc:376: Failure
Value of: wait_for_entries(player, 5, &entries)
  Actual: false
Expected: true
[  FAILED  ] TestJournalPlayer.PrefetchSkippedObject (10008 ms)
</pre>
unrelated journal test failure. The ubuntu integration tests fail though. But the centos 7 pass at last, yeah.

**Comment by dachary** [comment]
<code>cw ceph-qa-suite --verbose --teuthology-git-url http://github.com/dachary/teuthology --teuthology-branch openstack --ceph-qa-suite-git-url http://github.com/ceph/ceph-qa-suite --suite-branch master --ceph-git-url http://github.com/dachary/ceph --ceph wip-14669-key-management --suite ceph-disk --upload</code>

* **running** http://167.114.243.73:8081/ubuntu-2016-03-02_09:49:43-ceph-disk-wip-14669-key-management---basic-openstack/

**Comment by dachary** [comment]
<code>cw ceph-qa-suite --verbose --teuthology-git-url http://github.com/dachary/teuthology --teuthology-branch openstack --ceph-qa-suite-git-url http://github.com/ceph/ceph-qa-suite --suite-branch master --ceph-git-url http://github.com/dachary/ceph --ceph wip-14669-key-management --suite ceph-disk --upload</code>

* **running** http://167.114.243.73:8081/ubuntu-2016-03-03_12:34:23-ceph-disk-wip-14669-key-management---basic-openstack/

**Comment by dachary** [comment]
@liewegas I think it's safe to merge now. Whatever error the ubuntu 14.04 run may uncover, I'm confident it won't be a major issue. It currently fails because ansible fails, I suspect because of the git.ceph.com connectivity troubles.

<pre>
2016-03-03T14:39:14.756 ERROR:teuthology.run_tasks:Saw exception from tasks.
Traceback (most recent call last):
  File "/home/ubuntu/teuthology/teuthology/run_tasks.py", line 69, in run_tasks
    manager.__enter__()
  File "/home/ubuntu/teuthology/teuthology/task/__init__.py", line 121, in __enter__
    self.begin()
  File "/home/ubuntu/teuthology/teuthology/task/ansible.py", line 236, in begin
    self.execute_playbook()
  File "/home/ubuntu/teuthology/teuthology/task/ansible.py", line 262, in execute_playbook
    self._handle_failure(command, status)
  File "/home/ubuntu/teuthology/teuthology/task/ansible.py", line 285, in _handle_failure
    raise AnsibleFailedError(failures)
AnsibleFailedError: {'target167114229224.teuthology': {'invocation': {'module_name': 'apt', 'module_args': ''}, 'failed': True, 'msg': 'Could not fetch updated apt files'}}
2016-03-03T14:39:14.758 DEBUG:teuthology.run_tasks:Unwinding manager ansible.cephlab
</pre>

**Comment by dachary** [comment]
@liewegas strike that : we have a clean run at http://teuthology-logs.public.ceph.com/ubuntu-2016-03-03_14:59:50-ceph-disk-wip-14669-key-management---basic-openstack/ :-)

**Pull request merged**
