### PR TITLE
Improvments and fixes to radosgw-admin bucket check command

### PR DESCRIPTION
**Pull request by oritwas**
Fixes: http://tracker.ceph.com/issues/25116

### CODE REVIEW

**Comment by yuriw** [comment]
@oritwas this seems like a suspect for failures in this run http://pulpito.ceph.com/yuriw-2018-08-09_16:02:29-rgw-wip-yuri-testing-2018-08-07-1718-distro-basic-smithi/

**Comment by cbodley** [comment]
@oritwas there are a lot of ragweed test failures in this run that all hit an assertion after calling the rest api for this (`RGWOp_Check_Bucket_Index` from `GET /admin/bucket?index`). the json decoder complains about `ValueError: Extra data: line 1 column 3 - line 1 column 621 (char 2 - 620)`. is it possible this extra data is coming from that last commit, `rgw: print bucket stat after fixing index`?

**Comment by oritwas** [comment]
@cbodley , yes I see that ragweed expect the result to be empty. I will update the test ...

**Comment by oritwas** [comment]
@cbodley , @yuriw fixed output to be a single json

**Comment by cbodley** [comment]
@oritwas i'm still seeing these ragweed failures in [this run](http://pulpito.ceph.com/cbodley-2018-09-18_13:25:30-rgw-wip-cbodley-testing-distro-basic-smithi/), for example [this job](http://qa-proxy.ceph.com/teuthology/cbodley-2018-09-18_13:25:30-rgw-wip-cbodley-testing-distro-basic-smithi/3038030/teuthology.log)

**Comment by yuriw** [comment]
[wip-yuri4-testing-2018-11-15-2120](https://trello.com/c/rED6z2kY/473-wip-yuri4-testing-2018-11-15-2120)

**Comment by cbodley** [comment]
still failing ragweed.tests.tests.r_test_multipart_index_versioning.test:
> ValueError: Extra data: line 1 column 3 - line 1 column 621 (char 2 - 620)

http://qa-proxy.ceph.com/teuthology/cbodley-2018-11-19_16:45:29-rgw-wip-yuri4-testing-2018-11-15-2120-distro-basic-smithi/3270291/teuthology.log

**Pull request closed without merging**
