### PR TITLE
os/bluestore: Persist cid of an onode as part of cleaning metadata.

### PR DESCRIPTION
**Pull request by agayev**
Signed-off-by: Abutalib Aghayev <agayev@psu.edu>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by agayev** [comment]
@ifed01 Please take a look. I'm reading the code to understand how collection splitting/merging works so that we can handle those cases as well. It looks like we may need to store the number of significant bits as well and update it upon split/merge, which sounds a lot of work.

**Comment by ifed01** [comment]
> @ifed01 Please take a look. I'm reading the code to understand how collection splitting/merging works so that we can handle those cases as well. It looks like we may need to store the number of significant bits as well and update it upon split/merge, which sounds a lot of work.

Perhaps my comment which inspired this PR was a bit premature, Indeed one shouldn't persist CID since it's volatile due to PG merge/split. IIUC that's oid's hash which is persistent and is used for CID calculation. Hence you can keep oid only and then take proper number of bits from that hash value to get a CID.

**Comment by agayev** [comment]
@ifed01 but how do we know the proper number of bits needed to form the cid?

**Comment by ifed01** [comment]
> @ifed01 but how do we know the proper number of bits needed to form the cid?

May be something like that:
Locate a collection belonging to a pool (oid.pool to match cid.pool) and take number of bits 
from that collection, IIUC all the collections from a single pool should have the same bit number....

**Pull request closed without merging**
