### PR TITLE
rpm,install-deps,run-make-check: enable WITH_ZBD build on demand

### PR DESCRIPTION
**Pull request by tchaikov**
## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by tchaikov** [comment]
cc @agayev

**Comment by tchaikov** [comment]
- https://pulpito.ceph.com/kchai-2020-09-20_14:54:48-rados-wip-kefu-testing-2020-09-18-1517-distro-basic-smithi/
- https://pulpito.ceph.com/kchai-2020-09-20_14:54:48-rados-wip-kefu-testing-2020-09-18-1517-distro-basic-smithi/

**Review by neha-ojha — APPROVED** [review]

**Comment by neha-ojha** [comment]
jenkins test api

**Comment by tchaikov** [comment]
jenkins test docs

**Pull request merged**
