### PR TITLE
mgr/dashboard: update dashboard typography

### PR DESCRIPTION
**Pull request by nSedrickm**
Increase base font size to 16px
Add Red Hat Text fonts
Signed-off-by: nsedrickm <nsedrick101@gmail.com>
Fixes: https://tracker.ceph.com/issues/57286

image

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [x] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Review by Pegonzal — COMMENTED** [review]
Hey @nSedrickm , the PR looks good to me, good job.

But when I tried it locally I just thought that the text looks huge, and for some reason kinda wierd to me (might need to get used to it). I understand this is a change to improve accesibility issues, which is great but wanted to give my two cents on it.

Also, could you link the tracker for this fix in the PR? Thanks!

**Comment by nSedrickm** [comment]
> Hey @nSedrickm , the PR looks good to me, good job.
> 
> But when I tried it locally I just thought that the text looks huge, and for some reason kinda wierd to me (might need to get used to it). I understand this is a change to improve accesibility issues, which is great but wanted to give my two cents on it.
> 
> Also, could you link the tracker for this fix in the PR? Thanks!

Thanks @Pegonzal, Indeed it does. This is still a WIP. will make some improvements soon!

**Comment by ljflores** [comment]
@nSedrickm, as another reviewer said, let's link this issue to a Tracker.

**Comment by nSedrickm** [comment]
jenkins test make check

**Comment by nSedrickm** [comment]
jenkins test windows

**Comment by ljflores** [comment]
jenkins retest this please

**Review by ljflores — COMMENTED** [review]
@nSedrickm can you link the Patternfly guides that you followed? Also, for clarification, this is your suggestion, but not something that's violating accessibility guidelines?

**Comment by nSedrickm** [comment]
> @nSedrickm can you link the Patternfly guides that you followed? Also, for clarification, this is your suggestion, but not something that's violating accessibility guidelines?

Yes @ljflores this one is not accessibility related. While working on #46757 some typography adjustments were made and we thought the rest of the dashboard could also benefit these updates aswell. It sure would make thing more consistent.

https://www.patternfly.org/v4/guidelines/typography/

I am converting to a draft for now since its not high priority

**Pull request closed without merging**
