### PR TITLE
mgr/progress: Add PG recovery event when OSD is marked in 

### PR DESCRIPTION
**Pull request by kamoltat**
keeps track of affected PGs
similar to how funciton _osd_out works
but instead of tracking up+acting set
we only care about acting. Also made
a minor change on the function pg_update:
we consider pg to be complete when it
is active and clean and nothing else.

Signed-off-by: Kamoltat (Junior) Sirivadhna ksirivad@redhat.com

- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by batrick** [comment]
Hi Junior, please remove the merge commits from your PR. You should probably do this by doing a hard reset on master and cherry-picking the commits from your branch.

**Comment by kamoltat** [comment]
> Hi Junior, please remove the merge commits from your PR. You should probably do this by doing a hard reset on master and cherry-picking the commits from your branch.

Hi, so I had some problem with my forked master branch, so I just reset it to be at the same level with ceph master. Therefore I'm just gonna make  a new PR and branch for this.

**Comment by liewegas** [comment]
https://tracker.ceph.com/issues/40825

**Comment by kamoltat** [comment]
@liewegas
Yep so my updated test suite is in this PR https://github.com/ceph/ceph/pull/29111

**Pull request closed without merging**
