### PR TITLE
mgr/cephadm: some master -> main cleanup

### PR DESCRIPTION
**Pull request by adk3798**
Signed-off-by: Adam King <adking@redhat.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/master/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Review by rkachach — APPROVED** [review]

**Comment by adk3798** [comment]
jenkins test api

**Review by djgalloway — APPROVED** [review]

**Comment by adk3798** [comment]
https://pulpito.ceph.com/adking-2022-06-07_15:52:19-orch:cephadm-wip-adk-testing-2022-06-07-0930-distro-default-smithi/

4 failures due to infra/teuthology issues

- `Command failed on smithi125 with status 1: 'sudo fuser -v /var/lib/dpkg/lock-frontend'`
- `Failed to connect to the host via ssh: ssh: connect to host smithi125.front.sepia.ceph.com port 22: No route to host`
- `Stale jobs detected, aborting.`
- `Error reimaging machines: 'ssh_keyscan smithi125.front.sepia.ceph.com' reached maximum tries (5) after waiting for 5 seconds`

1 failure with agent on test_nfs test. Did 5 rerun of the test, 4 passed and the other failued with another teuthology/infra issue 

- `Failed to update apt cache: unknown reason`

I think there might be a legitimate sporadic failure with that test_nfs test, but I don't think it's caused by any PRs in this run

**Comment by ljflores** [comment]
@adk3798 I think this needs to be backported to Quincy, and possible Pacific: https://tracker.ceph.com/issues/58146

**Comment by adk3798** [comment]
> @adk3798 I think this needs to be backported to Quincy, and possible Pacific: https://tracker.ceph.com/issues/58146

okay, I can open some backports. Going to mark that tracker as needing backports so the bot will open the backport trackers

**Pull request merged**
