### PR TITLE
DNM: mon: add possibility to make command nonforwardable

### PR DESCRIPTION
**Pull request by trociny**
As it was discussed on ceph-devel, "mon: forwarding user commands" thread.

Note, this pull request expects the following commit to be merged:

 https://github.com/ceph/ceph/pull/3473  d5d1e27 msg: fixup for 2ffacbe (crc configuration in messenger) 

which fixes the forwarding issue between monitors of different versions.

### CODE REVIEW

**Comment by trociny** [comment]
Updated after Sage comments.

Also, during testing an issue with _get_moncommand() was found, which has been fixed.

**Comment by trociny** [comment]
Rebased after updating tests

**Comment by jecluis** [comment]
I've been trying to wrap my head around this change but it doesn't feel right.  In a nutshell, I don't think the client has the need to know a certain command in non-forwardable, nor should we expose than on the command signature -- this is entirely monitor specific.

I do believe it should be kept on the MonCommand struct though, and integer flags seems like a correct way to handle this -- I just don't like it on the COMMAND(...) in mon/MonCommands.h, especially as a string.

I would very much prefer if we were to detach this sort of flags from the command signature.  I've been thinking for a while and, although not awesome, I think something like this would feel more appropriate:

Every COMMAND() on mon/MonCommands.h would stay as it is.

For each command not supposed to be forwarded, have a new COMMAND_V2 (or something) with a format such as (or a variation of):

```
COMMAND_V2(prefix, \
  COMMAND(sig, desc, module, caps, flags), \
  FLAGS(flag_a | flag_b)
)
```

and have the mon_commands struct array being populated like:

```
#undef COMMAND_V2
#undef FLAGS
#define FLAGS(x) x
#define EXPAND_COMMAND(a, b, c, d, e) {a, b, c, d, e}
struct commands_v2_t cmds_v2[] = {
#undef COMMAND
#define COMMAND_V2(prefix, cmd, flags) \
  {prefix, EXPAND_##cmd, flags},
#define COMMAND(a, b, c, d, e) \
  COMMAND_V2(a, COMMAND(a,b,c,d,e),0)
#include "cmd_macros.h"
};
```

I have created a gist (https://gist.github.com/jecluis/3e34f7f4db91ffdd6bec) with some sample code.  Note that I've pruned most of MonCommands.h for that example, so as to make it reasonable in size.

You may also notice that my 'COMMAND_V2' above will hope to get a 'prefix' on the first argument, and the COMMAND() signature as the second.  COMMAND() takes both 'prefix' and 'arguments' as its first argument.  This is merely wishful thinking.  If we were to be able to have a prefix independent from the command signature, we would then be able to have a mon_command map, not only an array, which we could then lookup when matching caps and all -- instead of having to run through all the commands in the array and perform string comparisons to figure out which entry in the array we want.

We could probably be able to get away with just modifying every single COMMAND to a COMMAND_V2() without a huge history footprint.  In such case, we should probably use the following syntax instead, which I believe is more appropriate:

```
COMMAND(prefix,
  SIGNATURE(sig, desc, module, caps, flags),
  FLAGS(flag_a | flag_b)
)
```

**Comment by liewegas** [comment]
On Sat, 31 Jan 2015, João Eduardo Luís wrote:
> the need to know a certain command in non-forwardable, nor should we expose than on the command signature -- this is
> entirely monitor specific.

The key thing is that

 ceph tell mon.b foo bar

should tell mon.b foo bar, not mon.$leader or mon.$random.  That's the 
only reason for the client-side flag, I think.  It's a problem with 
version, but also any other command we may dream up later that has 
mon-specific effects.

Hmm, okay, I guess it is still a command property whether or not we are 
mon-specific or not.  The ones I can think of are

 compact
 injectargs
 version
 heap

and I can't think of one that isn't clearly one or the other.  Okay.

> I do believe it should be kept on the MonCommand struct though, and integer flags seems like a correct way to handle this
> -- I just don't like it on the COMMAND(...) in mon/MonCommands.h, especially as a string.

I think we can simplify this by just taking the existing COMMAND macro and 
turning the availability field into a flags field.  Right now only 'cli' 
and 'rest' are defined, but we can just call those flags and add 
'noforward' to the list.  Then there is no need to touch the existing 
definitions (except the ones that get noforward)...

**Comment by jecluis** [comment]
>The key thing is that
>
> ceph tell mon.b foo bar
>
>should tell mon.b foo bar, not mon.$leader or mon.$random.  That's the
>only reason for the client-side flag, I think.  It's a problem with
>version, but also any other command we may dream up later that has
>mon-specific effects.

By using 'tell mon.b foo bar', the user is already specifying this command should reach a given monitor.  It's the monitor's job to figure out whether 'foo bar' is forwardable or not.  We can add the noforward flag to the command flags, alongside rest and cli, but I still think this is information that the client does not care about nor will it use it at all -- regardless of having that information in the message sent by the client, the monitor will still have to check whether the command is forwardable or not.

Actually, I think that we're tackling this problem the wrong way.  The bug these patches attempt to fix is not about figuring out which commands are to be forwarded to the leader or not.  The bug is that we are handling some commands, which are completely specific to a given monitor, as if they were monitor service commands.  We shouldn't even be considering forwarding 'version' or 'heap' or 'injectargs'.  The ceph tool shouldn't even allow them to be run as 'ceph version', for instance, but force the user to always specify 'ceph tell mon.foo version'.

I don't think we need flags or any other means to handle this.  We need a list of commands that are to be considered monitor (as the actual entity) specific and that's it.  We could add a hardcoded list of commands that would fall under this category directly on the monitor.  Instead, adding 'tell' availability to the availability string on the COMMAND() would be enough.

Then we'd just check that on the monitor, and have the cephtool also checking it and making sure the client would explicitly use 'ceph tell mon.foo bar baz'.

When handling the command, if the monitor does not support the command but the leader does, just drop the command entirely. Don't forward it; don't even consider forwarding it -- not because it has a noforward flag, but because the command was not supposed to be forwarded in the first place.

**Comment by trociny** [comment]
1) I think being able to tell from client that the command mustn't be forwarded is useful. Yes, for some commands that are not supposed to be forwarded (like version) we can forbid forwarding on the server side. Still consider an example below:
```sh
ceph health
ceph tell mon.c health
```
If a user issues the second type of the command I think it expects to see the output exactly from mon.c (e.g. when testing or troubleshooting). So sending *noforwad* flag in tell command looks useful. The flag might be named *tell* instead, it does not matter to me, just a mark that this is the command initiated via tell.

2) I agree with the idea of having only integer flags and not exposing it in the signature (e.g. dump_cmddesc_to_json). I thought it might be useful somehow, but it looks not much. I will update the patch.

3) I don't really understand all these complications with COMMAND_V2. Is this just to touch lesser lines so the git history is more readable? Although this is a noble goal, I think having readable code is more important. For a casual reader seeing COMMAND_V2 might be confusing. Or may I miss the point? Also I don't like very much the idea of renaming *availability* to *flags*. It looks a little hackish to me and I suppose will cause some unnecessary compatibility complications.

Still I am ready to go any way when a consensus is reached.

**Comment by trociny** [comment]
@jecluis, I sent my last comment before reading your last message. What you say here have much sense to me still the implementation is not clear.

If we added *tell* to availability, what would this actually mean? That the command is supported via tell interface, I guess. But how can it help to decide that it mustn't be forwarded? I might miss something, need to think more about this.

Also we have to recognize somehow that the command is sent via tell. Right now I see only the way is to add a flag in to the command sent by the client (e.g. 'tell' instead of 'noforward', which I added). May be there is other option?

**Comment by liewegas** [comment]
I like the simplicity of adding 'tell' to availability and using that on the mon to decide not to forward.  We could make the cli error out as well but I think that's a compatbility problem with new clients and old mons that don't put 'tell' in availability.

This doesn't let you do 'health' on a specific mon but that command is about cluster state, not individual mon state.  I think if there is info that we want to report per-mon we can break it out into a separate command, similar to how mon_status is distinct from status.

So.. I think this wild goose chase (sorry, @trociny !) can be resolved with a simple check to skip forwarding if availability includes tell?  I'm guess that is a pretty simple check (tho i haven't checked).

**Comment by trociny** [comment]
I still have problems with understanding the new approach (add 'tell' to availability).

Here is my implementation:

https://github.com/trociny/ceph/commit/5cca41bc9d5193b66d109531c4904c52451443ce

There is a fundamental problem with it: availability string in tell commands is changed. That means that if a tell command is sent to an older non-leader monitor in cluster, the  check 
(*leader_cmd != *mon_cmd) will always return true and the tell command is forwarded to the leader (and rejected) . I can't see how to preserve compatibility without preserving availability string.

The solution I see is to add flags field similarly what I did, but which is filled  from availability:
```c
#define COMMAND(parsesig, helptext, modulename, req_perms, avail) \
+ {parsesig, helptext, modulename, req_perms, avail, MonCommand::str2flags(avail)},
```
And in MonCommand::encode(), when preparing v1 array, parse availability, removing 'tell', and sending flags in v2 array.

Other question. I just added 'tell' to availability of tell commands. May be it should replace 'cli', and an additional check is implemented to reject tell commands if they are not sent as tell (i.e. 'ceph mon_status' is rejected) and vice versa ('ceph tell mon.a health' is rejected too)? It looks like currently availability is not used in any way on the monitor side.

**Comment by liewegas** [comment]
Hmm, 'availability' should probably not be part of the comparison when deciding whether the command has changed...

It seems like we have 2 options:

1. mange the commands the leader shares with old mons to remove the 'tell' they won't understand
2. make a separate flags field, as one of your earlier patches did

bah, feels like we're going in circles :(

**Comment by jecluis** [comment]
On 02/02/2015 08:23 AM, Mykola Golub wrote:
> I still have problems with understanding the new approach (add 'tell' to
> availability).
>
> Here is my implementation:
>
> trociny@5cca41b
> <https://github.com/trociny/ceph/commit/5cca41bc9d5193b66d109531c4904c52451443ce>
>
> There is a fundamental problem with it: availability string in tell
> commands is changed. That means that if a tell command is sent to an
> older non-leader monitor in cluster, the check
> (*leader_cmd != *mon_cmd) will always return true and the tell command
> is forwarded to the leader (and rejected) . I can't see how to preserve
> compatibility without preserving availability string.

And this is why I really don't want to touch the command signature 
unless we really have to.  And I don't believe we have to. Changing the 
command signature can be a headache.

> The solution I see is to add flags field similarly what I did, but which
> is filled from availability:
>
> #define  COMMAND(parsesig, helptext, modulename, req_perms, avail) \
> + {parsesig, helptext, modulename, req_perms, avail,MonCommand::str2flags(avail)},
>
> And in MonCommand::encode(), when preparing v1 array, parse
> availability, removing 'tell', and sending flags in v2 array.

This could work, but I don't think we need it.  The way we're currently 
handling mixed version clusters, with mixed version command sets is fine 
and I don't think we need to touch it.

> Other question. I just added 'tell' to availability of tell commands.
> May be it should replace 'cli', and an additional check is implemented
> to reject tell commands if they are not sent as tell (i.e. 'ceph
> mon_status' is rejected) and vice versa ('ceph tell mon.a health' is
> rejected too)? It looks like currently availability is not used in any
> way on the monitor side.

I see 'availability' as a hint for clients, not at all binding. 
Especially because we don't have much way to tell, on the monitor, how a 
client is contacting the monitor, cli, rest or otherwise.  We should not 
replace cli unless we have to and are fully aware of the impact that can 
have.  As you may have figured by now, I'm not thrilled with changing 
what is currently the only interface we expose to clients :)

> On 02/02/2015 01:00 PM, Sage Weil wrote:
>
>> Hmm, 'availability' should probably not be part of the comparison when
>> deciding whether the command has changed...
>>
>> It seems like we have 2 options:
>>
>>  1. mange the commands the leader shares with old mons to remove the
>>     'tell' they won't understand
>>  2. make a separate flags field, as one of your earlier patches did
>>
>> bah, feels like we're going in circles :(

3. Much like 2. but without adding to the signature itself.

My take on this:

Let the current COMMAND() be as it is, and for each command that needs 
this behavior change it instead to something of the sorts of what I 
mentioned earlier:

EXPANDED_COMMAND(COMMAND(current stuff), MON_FLAGS("no-forward"))

Given we deal with this on compile time we can handle it whichever way 
we want, and as long as we honor the COMMAND(current stuff) we should 
not get into trouble down the road.

Then have a struct MonCommand much like what @trociny suggested, with a 
flags field initialized to 0.  When building the mon_command array, have 
it parsing all COMMAND(...wtv...) just as before, and then parse the 
EXPANDED_COMMAND(COMMAND(current stuff), MON_FLAGS("no-forward")) such 
that COMMAND(current stuff) is honored in the same way as 
COMMAND(...wtv..), but also initializes the struct's 'flags' field to 
MonCommand::NO_FORWARD.

We don't encode this flags field on MonCommand::encode() at all.  Even 
if we needed, we would have to be creative about it and tread lightly, 
because individual commands are not versioned -- yet another good reason 
not to change the command signature by adding new fields.

All we need to do on the Monitor, besides populating the mon_commands 
array's individual structs with the flags, is to either forward or not 
forward based on our local mon_commands array, no need to take the 
leader into account.  test/common/get_command_descriptions.cc will also 
need to be changed to reflect the EXPANDED_COMMAND() and print only the 
COMMAND() portion of it (disregarding MON_FLAGS(...)).

We will then have to figure out if we will want the monitors to share 
these flags amongst them in the future, in which case we will have to 
change how MonCommand::encode/decode() works, but I don't think that's 
in the scope of this PR.

I don't think I'm missing anything about this PR but please, feel free 
to point out whatever incorrect assumptions I'm making.

   -Joao

**Comment by jecluis** [comment]
last comment via email ended up garbled.  Trying to edit now to make it work. :(

**Comment by trociny** [comment]
Actually, my current implementation (958c36b) already adds versioning to encode_array, to send flags. We need leader flags for older non-leader monitor, so if a requested command is not found locally but there is in the leader array, we could check if it may be forwarded.

**Comment by jecluis** [comment]
The only way an older monitor would understand the flags would be to backport the patch.  Given this is a feature rather than a bug fix, I don't think that's going to happen.  Thus, given an older monitor will have no concept of flags, we can easily just care about this locally.

**Comment by liewegas** [comment]
Ah, but if the old mon doesn't understand and decode the flags, then 
teh commands will appear to be equal locally and it will not forward. 
Which is what we want..  which is exactly what the latest patch is doing.  
Sounds right to me!

**Comment by liewegas** [comment]
Sigh.. ok, rereading the original commit that looks pretty reasonable.  Maybe we could rename flags to be compat_flags and operator== to be is_compat() so that the fact that it ignores that field is less of a surprise.  I think it'll work okay as-is, though!

**Comment by trociny** [comment]
This functionality (check the leader command flag if the command is not known locally) was intended for future, when a new command is added, then it would work as described.

For current commands, it looks only newly added "version" is affected, so yes in this case the command would be forwarded to the leader and rejected only there.

**Comment by jecluis** [comment]
Can we at least not expose it to the client (i.e., ignore it for command signature purposes)?  We can always make it visible in the future if need be.

**Comment by trociny** [comment]
The patches have been updated:

* operator== to be is_compat()
* flags are stored only as integer
* flags are not exposed to the client
* I did my best to not touch command definitions

I have not changed flags to compat_flags because I don't see actually why. Should I?

Also, I still keep the patch 7b84ed that makes 'ceph tell' to set a flag to forbid forwarding. This additional safeguard was proposed previously, it is not necessary though. Should I drop it?

**Comment by jecluis** [comment]
I believe it's safe to drop the tell patch.

**Comment by trociny** [comment]
Rebased after dropping 'ceph tell' patch.

Reminder, this pull is not very useful until the forwarding issue between old and new monitors is not fixed:

#3473 d5d1e27 msg: fixup for 2ffacbe (crc configuration in messenger)

**Comment by liewegas** [comment]
@jecluis @trociny does my change at http://github.com/liewegas/ceph/commit/wip-noforward look ok?

**Comment by jecluis** [comment]
@liewegas yeah, looks good

**Comment by trociny** [comment]
@liewegas, sorry for delay. The changes look good to me. Thanks

Just a note, I added COMMAND_FLAGS instead of something like COMMAND_WITH_FLAG, because it looked more extendable to me: when in future one need to specify 2 flags, a macro
COMMAND_FLAGS2(falg1, flag2) could be introduced and used where it is needed.

But I am perfectly fine with your solution.

**Comment by liewegas** [comment]
merged manually

**Pull request closed without merging**
