### PR TITLE
tracing: don't include oid when tracing at dequeue_op()

### PR DESCRIPTION
**Pull request by yehudasa**
Signed-off-by: Yehuda Sadeh <yehuda@redhat.com>

### CODE REVIEW

**Comment by liewegas** [comment]
why not?

**Comment by yehudasa** [comment]
@liewegas because it crashes otherwise ... oid cannot be retrieved at that point (according to @athanatos)

**Comment by liewegas** [comment]
retest this please

**Comment by tchaikov** [comment]
retest this please, (log expired)

**Pull request merged**
