### PR TITLE
OSD: small cleanups

### PR DESCRIPTION
**Pull request by xiexingguo**

### CODE REVIEW

**Comment by xiexingguo** [comment]
@tchaikov Some simple and small cleanups. I would really appreciate it if you take a look at. Thanks.

**Comment by xiexingguo** [comment]
@tchaikov Ping~

**Comment by xiexingguo** [comment]
@tchaikov Since you are here, could you review this request for me too? It's some small cleanups. I think it will only take you a couple of minutes:)))

**Comment by xiexingguo** [comment]
@tchaikov Any suggestions?

**Comment by tchaikov** [comment]
lgtm with a rados qa run.

**Pull request merged**
