### PR TITLE
[DNM, WIP] luminous: Secure Token Service (STS Lite) API feature

### PR DESCRIPTION
**Pull request by mattbenjamin**
https://docs.ceph.com/docs/master/radosgw/STSLite/

### CODE REVIEW

**Comment by mattbenjamin** [comment]
@pritha-srivastava I made an effort to backport this, keeping the branch buildable at each commit;  can you look over?  is this viable without further changes/rebasing?  if not, I worked through enough stuff for this to be helpful anyway, I think

**Comment by mattbenjamin** [comment]
@pritha-srivastava ok, added my 1 commit :)

**Comment by smithfarm** [comment]
jenkins re-test this please

**Comment by smithfarm** [comment]
@mattbenjamin Status? (Needs rebase now....)

Also, is there a (master) Redmine tracker for this feature?

**Comment by smithfarm** [comment]
@mattbenjamin No response from you, so I'm closing it.

**Pull request closed without merging**
