### PR TITLE
Crimson: bump up seastar version 

### PR DESCRIPTION
**Pull request by Matan-B**
Update seastar's sub module to: https://github.com/ceph/seastar/commits/seastar-upgrade-feb24/  (patched branch)

Which is using dpdk sub module of: https://github.com/ceph/dpdk/tree/dpdk-seastar-upgrade-feb24 (same as scylladb/seastar)

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Comment by Matan-B** [comment]
jenkins retest this please

**Comment by Matan-B** [comment]
jenkins retest this please

**Comment by Matan-B** [comment]
jenkins retest this please

**Comment by Matan-B** [comment]
https://github.com/scylladb/seastar/pull/2076 compilation error fix is included in https://github.com/ceph/seastar/commits/seastar-upgrade-feb24/

**Comment by Matan-B** [comment]
https://shaman.ceph.com/builds/ceph/wip-crimson-seastar-upgrade/

**Review by athanatos — APPROVED** [review]

**Comment by Svelar** [comment]
jenkins test make check arm64

**Comment by Matan-B** [comment]
Build and CI are ok but the upgrade exposes runtime issues around alienstore:
```
DEBUG 2024-02-04 15:35:45,933 [shard 2:main] osd - OSDSingletonState::dispatch_context_transaction: do_transaction ...
DEBUG 2024-02-04 15:35:45,933 [shard 1:main] osd - OSDSingletonState::dispatch_context_transaction: do_transaction ...
/home/jenkins-build/build/workspace/ceph-dev-new-build/ARCH/x86_64/AVAILABLE_ARCH/x86_64/AVAILABLE_DIST/centos9/DIST/centos9/MACHINE_SIZE/gigantic/release/19.0.0-1236-g2ddfc3fe/rpm/el9/BUILD/ceph-19.0.0-1236-g2ddfc3fe/redhat-linux-build/boost/include/boost/intrusive/detail/list_node.hpp:66:16: runtime error: member access within null pointer of type 'struct list_node'
Segmentation fault/home/jenkins-build/build/workspace/ceph-dev-new-build/ARCH/x86_64/AVAILABLE_ARCH/x86_64/AVAILABLE_DIST/centos9/DIST/centos9/MACHINE_SIZE/gigantic/release/19.0.0-1236-g2ddfc3fe/rpm/el9/BUILD/ceph-19.0.0-1236-g2ddfc3fe/redhat-linux-build/boost/include/boost/intrusive/detail/list_node.hpp:66:16: runtime error: member access within null pointer of type 'struct list_node'
 on shard 1.
Backtrace:
 2# 0x000056082F3B9503 in ceph-osd
 3# crimson::os::AlienStore::do_transaction_no_callbacks(boost::intrusive_ptr<crimson::os::FuturizedCollection>, ceph::os::Transaction&&) in ceph-osd
 4# 0x00005608273D4EFA in ceph-osd
 5# crimson::osd::ShardServices::dispatch_context_transaction(boost::intrusive_ptr<crimson::os::FuturizedCollection>, PeeringCtx&) in ceph-osd
 6# crimson::osd::ShardServices::dispatch_context(boost::intrusive_ptr<crimson::os::FuturizedCollection>, PeeringCtx&&) in ceph-osd
```

**Comment by Matan-B** [comment]
@athanatos, changeset: 
* https://github.com/scylladb/seastar/pull/2076/commits/cc7c8ecb3b1d16cef9cb38e0440b762f623bbe16 was replaced by (merged in seastar) https://github.com/ceph/seastar/commit/3c4582b9d3e22cfb2f22d610c5c4c6963603b62c to allow comilation with clang 14 (used by make check).

* The runtime errors were caused due to: https://github.com/scylladb/seastar/pull/1329. I have disabled the new debug macro and opened a relevant tracker.
https://github.com/ceph/seastar/commit/f3a1484c83b8b8ed774582f85fe33bf957390400
https://tracker.ceph.com/issues/64332

Tests look ok:
https://pulpito.ceph.com/matan-2024-02-06_13:20:17-crimson-rados-wip-crimson-seastar-upgrade-distro-crimson-smithi/

**Comment by athanatos** [comment]
Yeah, I'm fine with updating the submodule and the fixing the bugs.  That should probably be top priority, though.

**Comment by dmick** [comment]
This was not sufficient to handle the runtime dependencies.  There is a protobuf package in centos8, but it contains libprotobuf.so.15; building with the packages in this COPR results in a dependency from ceph-osd on libprotobuf.so.30, which can't be satisfied.  This will break both the execution of ceph-osd and the building of the centos8 container.

**Pull request merged**
