### PR TITLE
luminous: tests: use curl in wait_for_radosgw() in util/rgw.py 

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/40347

### CODE REVIEW

**Comment by smithfarm** [comment]
@alimaredia Could you have a look at the conflict resolution here?

**Comment by alimaredia** [comment]
@smithfarm could you elaborate more on what you mean by "conflict resolution"? I just approved the PR and it says the branch has no merge conflicts.

**Comment by smithfarm** [comment]
@alimaredia By "conflict resolution" what I meant was the way the cherry-pick was done. Since the master commit did not apply cleanly (i.e. there were conflicts), the conflicts had to be resolved manually. You can see this conflict resolution by comparing the cherry-pick with the master commit.

**Comment by smithfarm** [comment]
@alimaredia In this case the conflict was in "qa/tasks/rgw.py":

```
<<<<<<< HEAD
    for client in config.keys():
        host, port = ctx.rgw.role_endpoints[client]
        endpoint = 'http://{host}:{port}/'.format(host=host, port=port)
        log.info('Polling {client} until it starts accepting connections on {endpoint}'.format(client=client, endpoint=endpoint))
        wait_for_radosgw(endpoint)
=======
    for client in clients:
        endpoint = ctx.rgw.role_endpoints[client]
        url = endpoint.url()
        log.info('Polling {client} until it starts accepting connections on {url}'.format(client=client, url=url))
        (remote,) = ctx.cluster.only(client).remotes.iterkeys()
        wait_for_radosgw(url, remote)
>>>>>>> 9c6afa3fb5... qa: use curl in wait_for_radosgw() in util/rgw.py
```

which I resolved like so: https://github.com/ceph/ceph/pull/28669/commits/e0bdc42644bf6b518397ca2db8561c3090c03147

**Comment by alimaredia** [comment]
@smithfarm I see, thanks for elaborating. This PR lgtm.

**Pull request merged**
