### PR TITLE
reef: qa: fix krbd_msgr_segments and krbd_rxbounce failing on 8.stream

### PR DESCRIPTION
**Pull request by idryomov**
backport tracker: https://tracker.ceph.com/issues/65549

---

backport of https://github.com/ceph/ceph/pull/56908
parent tracker: https://tracker.ceph.com/issues/65481

### CODE REVIEW

**Comment by idryomov** [comment]
jenkins test make check

**Comment by idryomov** [comment]
jenkins test windows

**Comment by idryomov** [comment]
jenkins test windows

**Comment by ajarr** [comment]
I don't see the 'cherry picked from' labels in the commit message. `cherry-pick -x` wasn't used?

**Comment by idryomov** [comment]
> I don't see the 'cherry picked from' labels in the commit message. `cherry-pick -x` wasn't used?

Not sure what happened -- quincy and squid PRs are fine.  I will redo and push.

**Review by ajarr — APPROVED** [review]

**Comment by idryomov** [comment]
jenkins test api

**Pull request merged**
