### PR TITLE
Rebased wip-ifed-bluefs-migrate feature for Mimic

### PR DESCRIPTION
**Pull request by vitalif**
Hi!
This is my attempt to rebase https://github.com/ceph/ceph/pull/23103 onto Mimic.
In fact I tried it on one of live OSD and it was corrupted and failed to start. Igor Fedotov suggested me in PR #23103 to open a pull request with my rebase for easier investigation.
So... here it is :)

### CODE REVIEW

**Comment by ifed01** [comment]
@vitalif - this doesn't build in my lab. I'm a bit surprised that make check builds successfully here but please look at add_devices() method in your bluestore_tool.cc. 
1) it returns nullptr despite being declared as void
2) it references id var which is absent.
That's the first showstopper I found, may be more exist.

**Comment by vitalif** [comment]
In fact this was slightly different from what I've tried originally - I've rebased it once more before submitting PR to newer mimic and it seems it conflicted with your 682c048dd33ef416822793a6995aab2e8153ca88

OK, I'll try again :)

**Comment by vitalif** [comment]
I mean, originally I've tried it based on 13.2.2

**Comment by vitalif** [comment]
Rechecked what I've built originally - it seems duplicates add_devices() was the only problem and now everything looks the same... (or almost the same)
I also pushed what I've tested originally into https://github.com/vitalif/ceph/tree/wip-ifed-bluefs-migrate-mimic-13.2.2
What bothers me is that I've cherry-picked your "get rid off allocator's reserve method" before bluefs-migrate commits - was it a good thing to do with mimic? Or there is some other dependent code...

**Comment by vitalif** [comment]
No, it seems it was not a good thing to do :) but without it, `ceph-bluestore-tool` crashes with assertion failed - num_reserved >= 0 in the end of `StupidAllocator::allocate_int()`. Like:

```
#9  0x000055938add98d1 in StupidAllocator::allocate (this=0x55938d6e3500, want_size=5242880, alloc_unit=1048576, max_alloc_size=5242880, 
    hint=<optimized out>, extents=0x7ffe5696e180) at /home/big/ceph/src/os/bluestore/StupidAllocator.cc:223
#10 0x000055938ac233fd in Allocator::allocate (extents=0x7ffe5696e180, hint=0, alloc_unit=1048576, want_size=5242880, this=<optimized out>)
    at /home/big/ceph/src/os/bluestore/Allocator.h:41
#11 BlueFS::_allocate_without_fallback (this=this@entry=0x55938d544f00, id=id@entry=1 '\001', len=len@entry=4198400, extents=extents@entry=0x7ffe5696e180)
    at /home/big/ceph/src/os/bluestore/BlueFS.cc:2341
#12 0x000055938ac35767 in BlueFS::_rewrite_log_sync(bool, int, int, int, int) () at /home/big/ceph/src/os/bluestore/BlueFS.cc:1617
#13 0x000055938ac3698b in BlueFS::device_migrate_to_existing(CephContext*, std::set<int, std::less<int>, std::allocator<int> > const&, int) ()
    at /home/big/ceph/src/os/bluestore/BlueFS.cc:1119
#14 0x000055938acbe8c7 in BlueStore::migrate_to_existing_bluefs_device(std::set<int, std::less<int>, std::allocator<int> > const&, int) ()
    at /home/big/ceph/src/os/bluestore/BlueStore.cc:5813
```

**Comment by vitalif** [comment]
I understood, it's simple to fix - I only need to add reserve() before allocate() and unreserve() on unsuccessful allocate. OK, I rebased it once more - `osd-bluefs-volume-ops.sh` now pass.

**Comment by ifed01** [comment]
@vitalif - I gave a brief try to this PR including running corresponding test case from QA suite - no evident issues so far.
I'll be glad to guide you through the testing process against your existing image if you give it another try.
Or we can start with investigating against broken image if it's still present.

**Comment by vitalif** [comment]
No, I purged the corrupted one and recreated it. I think it should succeed this time.
However I'm slightly afraid of trying it again before I resolve the issue of my cluster eating space after rebalance :)
When Ceph was backfilling the recreated lost osd last week it filled up to 95% (the original was ~80% full) and the cluster stopped. It was a surprise for me. After that I tried to change weights several times, then added 3 more disks, then increased the PG count... and it ended up with the cluster filled again on saturday. O_o. Of course my mistake was that PG count was way too low... but the problem is that I still can't finish rebalance because after moving each PG the "raw used space" grows and grows more. Most PGs are now pinned back to their original locations using pg-upmap. It has grown up +1.8TB (!!) during move of 31 PGs of 200.
I've just described the situation in the mailing list: http://lists.ceph.com/pipermail/ceph-users-ceph.com/2018-October/030906.html
Maybe you could also suggest something?) I promise to test bluefs move after that :))

**Comment by ifed01** [comment]
@vitalif - sorry, no ideas on usage growth. Please ping me if(when) you need help with migrate stuff roubleshooting.

**Comment by ifed01** [comment]
@vitalif - you might want to backport this one too once it's merged: https://github.com/ceph/ceph/pull/24948

**Comment by vitalif** [comment]
Okaaaay. I've tested your tool again on an OSD which I've previously taken out from cluster.
It finished successfully:
```
[root@sill-03 bluefs-migrate]# ./ceph-bluestore-tool --path=/var/lib/ceph/osd/ceph-3 --devs-source /var/lib/ceph/osd/ceph-3/block --dev-target /var/lib/ceph/osd/ceph-3/block.db --command=bluefs-bdev-migrate
inferring bluefs devices from bluestore path
```
But then I ran export:
```
[root@sill-03 t]# ceph-bluestore-tool --path=/var/lib/ceph/osd/ceph-3 --out-dir=t bluefs-export
inferring bluefs devices from bluestore path
 slot 1 /var/lib/ceph/osd/ceph-3/block.db
 slot 2 /var/lib/ceph/osd/ceph-3/block
db/
db/030897.log
db/030900.sst
db/030901.sst
db/CURRENT
db/IDENTITY
db/LOCK
db/MANIFEST-030896
db/OPTIONS-030559
db/OPTIONS-030899
db.slow/
db.slow/030060.sst
db.slow/030101.sst
db.slow/030145.sst
db.slow/030472.sst
db.slow/030476.sst
db.slow/030685.sst
db.slow/030686.sst
db.slow/030687.sst
db.slow/030735.sst
db.slow/030736.sst
db.slow/030737.sst
db.slow/030786.sst
db.slow/030787.sst
```
So... does this mean SSTs are still on db.slow?

**Comment by vitalif** [comment]
More experiments:

1) I ran the migrate command with `block.db` as source and `block` as target - it successfully removed the device, BUT the OSD couldn't start after that with
```
2018-11-09 00:57:15.396 7fe0ea2df1c0 -1 *** Caught signal (Segmentation fault) **
 in thread 7fe0ea2df1c0 thread_name:ceph-osd

 ceph version 13.2.2 (02899bfda814146b021136e9d8e80eba494e1126) mimic (stable)
 1: (()+0x902970) [0x558997b6c970]
 2: (()+0xf6d0) [0x7fe0de27a6d0]
 3: (std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(std::string const&)+0x1b) [0x7fe0ddc08d5b]
 4: (rocksdb::Version::~Version()+0x105) [0x558997c6eb45]
 5: (rocksdb::Version::Unref()+0x21) [0x558997c6ebe1]
 6: (rocksdb::ColumnFamilyData::~ColumnFamilyData()+0x6c) [0x558997d4cefc]
 7: (rocksdb::ColumnFamilySet::~ColumnFamilySet()+0xa8) [0x558997d4e2d8]
 8: (rocksdb::VersionSet::~VersionSet()+0x5c) [0x558997c6217c]
 9: (rocksdb::DBImpl::CloseHelper()+0x4f8) [0x558997b9e0b8]
 10: (rocksdb::DBImpl::~DBImpl()+0x3b2) [0x558997bad2f2]
 11: (rocksdb::DBImpl::~DBImpl()+0x11) [0x558997bad341]
 12: (rocksdb::DBImpl::Open(rocksdb::DBOptions const&, std::string const&, std::vector<rocksdb::ColumnFamilyDescriptor, std::allocator<rocksdb::ColumnFamilyDescriptor> > const&, std::vector<rocksdb::ColumnFamilyHandle*, std::allocator<rocksdb::ColumnFamilyHandle*> >*, rocksdb::DB**, bool)+0x772) [0x558997bdde72]
 13: (rocksdb::DB::Open(rocksdb::DBOptions const&, std::string const&, std::vector<rocksdb::ColumnFamilyDescriptor, std::allocator<rocksdb::ColumnFamilyDescriptor> > const&, std::vector<rocksdb::ColumnFamilyHandle*, std::allocator<rocksdb::ColumnFamilyHandle*> >*, rocksdb::DB**)+0x22) [0x558997bdf5b2]
 14: (RocksDBStore::do_open(std::ostream&, bool, std::vector<KeyValueDB::ColumnFamily, std::allocator<KeyValueDB::ColumnFamily> > const*)+0x1638) [0x558997ac4698]
 15: (BlueStore::_open_db(bool, bool)+0xd69) [0x558997a51a59]
 16: (BlueStore::_mount(bool, bool)+0x4d1) [0x558997a81fc1]
 17: (OSD::init()+0x28f) [0x558997630f4f]
 18: (main()+0x23a0) [0x558997512250]
 19: (__libc_start_main()+0xf5) [0x7fe0dd287445]
 20: (()+0x37d7f0) [0x5589975e77f0]
 NOTE: a copy of the executable, or `objdump -rdS <executable>` is needed to interpret this.
```

2) I did export again and it was clear from iostat that it's reading SSTs from the HDD

3) I ran `./ceph-bluestore-tool --path=/var/lib/ceph/osd/ceph-3 --dev-target /dev/ceph-journals/lvol0 bluefs-bdev-new-db` - it successfully added the journal, but OSD also didn't start with a permission error. `umount /var/lib/ceph/osd/ceph-3; ceph-volume lvm activate --all` helped

4) I ran the first command (migrate block -> block.db) and then export again. DBs are still said to be in db.slow, but `iostat` tells they're read from the SSD. Interesting - is it how your tool works? Does it make the whole `db.slow` reside on SSD? If yes is it correct i.e. would SSTs still spill to HDD if the SSD overflows?

**Pull request closed without merging**
