### PR TITLE
kraken: rgw: multisite: EPERM when trying to read SLO objects as system/admin user

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/19475

### CODE REVIEW

**Comment by smithfarm** [comment]
```
Error EIO: load dlopen(/home/jenkins-build/build/workspace/ceph-pull-requests/build/lib/libec_FAKE.so): /home/jenkins-build/build/workspace/ceph-pull-requests/build/lib/libec_FAKE.so: cannot open shared object file: No such file or directory
```

This is missing a test fix . . . as I vaguely recall. Need to track it down.

**Comment by tchaikov** [comment]
@smithfarm, no. this issue also exists in master, i posted #14468 in hope to help root cause this.

**Comment by smithfarm** [comment]
Jenkins re-test this please

**Comment by smithfarm** [comment]
Jenkins re-test this please

**Comment by smithfarm** [comment]
@tchaikov I moved the `qa/workunits/ceph-helpers.sh` change to #16069 so you might consider "moving" your review there, too.

**Comment by smithfarm** [comment]
@yehudasa @mattbenjamin @oritwas @cbodley @rzarzynski This PR passed an rgw suite at http://tracker.ceph.com/issues/19009#note-60 and, provided there are no objections, I'll merge it as soon as it gets a positive review from one of you.

**Pull request merged**
