### PR TITLE
tools/rados: correct the bench read offset

### PR DESCRIPTION
**Pull request by thinkercui**
the offset is limited by num_objects, which makes it impossible to read all the blocks that bench has written.  correct this with num_ops to make bench seq read or rand read right. 

Signed-off-by: Xiaofei Cui <cuixiaofei@sangfor.com.cn>

- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by tchaikov** [comment]
retest this please

**Comment by jdurgin** [comment]
@markhpc does this look good to you? the conflict looks trivial to resolve

**Comment by thinkercui** [comment]
@markhpc  @jdurgin  I have resolved the conflict.  Does this looks good to you?

**Comment by thinkercui** [comment]
retest this please

**Comment by gregsfortytwo** [comment]
Eek sorry for the lack of review. :(

**Comment by jdurgin** [comment]
is this fixed with #29734 ?

**Comment by thinkercui** [comment]
> is this fixed with #29734 ?

yes, I think so. It is the same problem.

**Comment by neha-ojha** [comment]
Closing this in favor of https://github.com/ceph/ceph/pull/29734.

@thinkercui thanks for your contribution!

**Pull request closed without merging**
