### PR TITLE
doc/rados/operations: Fix double prompt

### PR DESCRIPTION
**Pull request by bluikko**
In monitoring.rst a double prompt was rendered, one non-selectable and one selectable. Remove the selectable prompt.

Signed-off-by: Ville Ojamo <14869000+bluikko@users.noreply.github.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [x] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [x] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by zdover23** [comment]
@bluikko: That's a curious discovery. Thank you.

Alter this PR so that it is no longer a draft, and I will merge it and generate backports.

**Comment by bluikko** [comment]
> Alter this PR so that it is no longer a draft, and I will merge it and generate backports.

I marked it as draft since this is the first time I am working with such a construct, being a RST newbie. I wanted to wait for the RTD build to confirm it looks right.

And excuse me for blasting all these PRs all around - maybe I should've just put them all in a single PR. But every time I think I'm done I spotted some new small issue. This one should really be it for now!

**Comment by zdover23** [comment]
> > Alter this PR so that it is no longer a draft, and I will merge it and generate backports.
> 
> I marked it as draft since this is the first time I am working with such a construct, being a RST newbie. I wanted to wait for the RTD build to confirm it looks right.
> 
> And excuse me for blasting all these PRs all around - maybe I should've just put them all in a single PR. But every time I think I'm done I spotted some new small issue. This one should really be it for now!

@bluikko: You're doing it right. The only thing I see in your work that is nonstandard is a lack of squashed commits. If you need help with that, let me know and I'll step you through it. I've been meaning to write up the process in the documentation, but as you yourself have noticed, one damn thing leads to another.

Please feel free to make as many commits like this as you like.

**Comment by bluikko** [comment]
> @bluikko: You're doing it right. The only thing I see in your work that is nonstandard is a lack of squashed commits. If you need help with that, let me know and I'll step you through it.

Thanks for the feedback. I'll keep that in mind for the future, perhaps marking the PR as draft until there is no more commits for sure and then squash + mark as ready.

> I've been meaning to write up the process in the documentation, but as you yourself have noticed, one damn thing leads to another.

Indeed.  
I am familiar with git (a bit less familiar with GitHub though) - there is an OK Ceph developer contributor guide/documentation (which I should read more in detail...) but it would be helpful to learn more about issues specific to documentation contributions!

**Review by zdover23 — APPROVED** [review]

**Comment by zdover23** [comment]
https://github.com/ceph/ceph/pull/49898 - Quincy backport
https://github.com/ceph/ceph/pull/49899 - Pacific backport

**Pull request merged**
