### PR TITLE
tools/rbd-ggate: close log before running postfork

### PR DESCRIPTION
**Pull request by wjwithagen**
Otherwise the assert in Log:open() will trigger since
all data is kept during the fork and also the `is_started` flag

Fixes: https://tracker.ceph.com/issues/41592

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`

</details>

### CODE REVIEW

**Comment by trociny** [comment]
@wjwithagen I wonder isn't a350c8032af4 fixed the similar issue in rbd-nbd? Could you please try? (Right now I don't have an evironment with freshly built ceph to try it myself).

**Comment by trociny** [comment]
Also, don't you want to backport the fix to the stable releases? Then it would be good to create a tracker ticket for this issue.

**Comment by wjwithagen** [comment]
> 
> 
> Also, don't you want to backport the fix to the stable releases? Then it would be good to create a tracker ticket for this issue.

I think this needs to go for backport, once I has the correct fix.

Usually I first fix master, and see what comes of it. Sometimes it is a totally different problem from what I first thought.
If it then requires backporting, I make a tracker, and ask for back-ports.
I'm rather clumsy at creating back-ports, so unless I have to, I avoid them.
I also cheat, because I can add patches to the FreeBSD ports (and my jenkins tests) , in case they did not (yet) make it in the Ceph tree.

**Comment by wjwithagen** [comment]
> 
> 
> @wjwithagen I wonder isn't [a350c80](https://github.com/ceph/ceph/commit/a350c8032af41452b8f9a200f86e7f0dc0db7345) fixed the similar issue in rbd-nbd? Could you please try? (Right now I don't have an evironment with freshly built ceph to try it myself).

I tried looking in what `nbd-stuff` did, but overlooked the more interresting stuff.
Will try also this aproach.

**Comment by wjwithagen** [comment]
@trociny
The rbd-ndb example works....
I'll redo this PR that way.

**Comment by trociny** [comment]
@wjwithagen Excellent! So, could you please create a tracker ticket, squash your commits into one and add 'Fixes: ...' to the commit log message?

**Comment by wjwithagen** [comment]
@trociny
https://tracker.ceph.com/issues/41592

**Pull request merged**
