### PR TITLE
nautilus: mon/OSDMonitor: drop stale failure_info even if can_mark_down()

### PR DESCRIPTION
**Pull request by tchaikov**
backport of https://github.com/ceph/ceph/pull/41516

Fixes: https://tracker.ceph.com/issues/50988

(cherry picked from commit 2d21ab905889c36bf9a9ecc6f0b66f4142c826e3)

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by tchaikov** [comment]
please note, the master PR of this change at #41516 has not yet been merged. but i really want to get this change tested sooner to ensure that this change can be included in the nautilus branch.

**Comment by ideepika** [comment]
hey @tchaikov I do not directly suspect, this change to be relate to :
```
   <frame>
      <ip>0x6B7F69</ip>
      <obj>/usr/bin/ceph-osd</obj>
      <fn>OSD::ms_handle_authentication(Connection*)</fn>
      <dir>/usr/src/debug/ceph-14.2.21-257-gfce0bffa/src/osd</dir>
      <file>OSD.cc</file>
      <line>7633</line>
    </frame>
    <frame>
      <ip>0xE0840D</ip>
      <obj>/usr/bin/ceph-osd</obj>
      <fn>Messenger::ms_deliver_verify_authorizer(Connection*, int, int, ceph::buffer::v14_2_0::list&amp;, ceph::buffer::v14_2_0::list&amp;, bool&amp;, CryptoKey&amp;, std::string*, std::unique_ptr&lt;AuthAuthorizerChallenge, std::default_delete&lt;AuthAuthorizerChallenge&gt; &gt;*)</fn>
      <dir>/usr/src/debug/ceph-14.2.21-257-gfce0bffa/src/msg</dir>
      <file>Messenger.cc</file>
      <line>160</line>
    </frame>
    <frame>
      <ip>0xFCA664</ip>
      <obj>/usr/bin/ceph-osd</obj>
      <fn>Pipe::accept()</fn>
      <dir>/usr/src/debug/ceph-14.2.21-257-gfce0bffa/src/msg/simple</dir>
      <file>Pipe.cc</file>
      <line>527</line>
    </frame>
    <frame>
      <ip>0xFD135F</ip>
      <obj>/usr/bin/ceph-osd</obj>
      <fn>Pipe::reader()</fn>
      <dir>/usr/src/debug/ceph-14.2.21-257-gfce0bffa/src/msg/simple</dir>
      <file>Pipe.cc</file>
      <line>1656</line>
    </frame>
    <frame>
      <ip>0xFD32DC</ip>
      <obj>/usr/bin/ceph-osd</obj>
      <fn>Pipe::Reader::entry()</fn>
```
valgrind failure caught while testing this PR, just wanted to check with you as well since this is new issue for nautilus, before filing a tracker. Do you think this might be related?

**Comment by tchaikov** [comment]
@ideepika could you please paste the full error report or the link to the run? i cannot find the what the error was in the backtrace. also, i don't think it's related.

**Comment by ideepika** [comment]
> @ideepika could you please paste the full error report or the link to the run? 

/a/yuriw-2021-05-25_18:52:10-rados-wip-yuri-testing-2021-05-25-0847-nautilus-distro-basic-smithi/6134350/
https://pulpito.ceph.com/yuriw-2021-05-25_18:52:10-rados-wip-yuri-testing-2021-05-25-0847-nautilus-distro-basic-smithi

> i cannot find the what the error was in the backtrace. also, i don't think it's related.
ack, thanks!

**Comment by tchaikov** [comment]
looks like session leak, quote from `remote/*/log/valgrind/osd.6.log.gz`

```xml
<error>
  <unique>0x5ca5b4</unique>
  <tid>1</tid>
  <kind>Leak_DefinitelyLost</kind>
  <xwhat>
    <text>1,656 (488 direct, 1,168 indirect) bytes in 1 blocks are definitely lost in loss record 53 of 57</text>
    <leakedbytes>1656</leakedbytes>
    <leakedblocks>1</leakedblocks>
  </xwhat>
  <stack>
    <frame>
      <ip>0xA6F5C38</ip>
      <obj>/usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so</obj>
      <fn>operator new[](unsigned long)</fn>
      <dir>/builddir/build/BUILD/valgrind-3.15.0/coregrind/m_replacemalloc</dir>
      <file>vg_replace_malloc.c</file>
      <line>433</line>
    </frame>
    <frame>
      <ip>0x6B7F69</ip>
      <obj>/usr/bin/ceph-osd</obj>
      <fn>OSD::ms_handle_authentication(Connection*)</fn>
      <dir>/usr/src/debug/ceph-14.2.21-257-gfce0bffa/src/osd</dir>
      <file>OSD.cc</file>
      <line>7633</line>
    </frame>
```

might be an occurrence of https://tracker.ceph.com/issues/43915 .

**Comment by ideepika** [comment]
> looks like session leak, quote from `remote/*/log/valgrind/osd.6.log.gz`
> 
> ```
> <error>
>   <unique>0x5ca5b4</unique>
>   <tid>1</tid>
>   <kind>Leak_DefinitelyLost</kind>
>   <xwhat>
>     <text>1,656 (488 direct, 1,168 indirect) bytes in 1 blocks are definitely lost in loss record 53 of 57</text>
>     <leakedbytes>1656</leakedbytes>
>     <leakedblocks>1</leakedblocks>
>   </xwhat>
>   <stack>
>     <frame>
>       <ip>0xA6F5C38</ip>
>       <obj>/usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so</obj>
>       <fn>operator new[](unsigned long)</fn>
>       <dir>/builddir/build/BUILD/valgrind-3.15.0/coregrind/m_replacemalloc</dir>
>       <file>vg_replace_malloc.c</file>
>       <line>433</line>
>     </frame>
>     <frame>
>       <ip>0x6B7F69</ip>
>       <obj>/usr/bin/ceph-osd</obj>
>       <fn>OSD::ms_handle_authentication(Connection*)</fn>
>       <dir>/usr/src/debug/ceph-14.2.21-257-gfce0bffa/src/osd</dir>
>       <file>OSD.cc</file>
>       <line>7633</line>
>     </frame>
> ```
> 
> might be an occurrence of https://tracker.ceph.com/issues/43915 .

ahan, got it, was in doubt as this one involved `ms_deliver_verify_authorizer` thanks for taking a look! will add!

**Review by yuriw — APPROVED** [review]

**Review by ideepika — APPROVED** [review]

**Pull request merged**
