### PR TITLE
Enable running libcephfs tests on Windows

### PR DESCRIPTION
**Pull request by petrutlucian94**
We're enabling libcephfs tests to run on Windows, addressing all the incompatibilities that we have encountered:

* always use CEPHFS_E* error codes, avoid mixing those with host errno values
* added missing definitions to fs_compat.h
* the "nobody" user is ignored on Windows, which is why we'll skip the tests that rely on it
*  sys/mman.h and sys/resource.h are not available on Windows and will be skipped
* skip rlimit, not available on Windows
* "fork" is not available on Windows, some tests are skipped
* use "strchr" instead of "index" or "strchrnul"
* avoid trimming inodes on Windows
* skip "dirent" checks on Windows, can't hold a uint64_t inode
* use _setattrx when changing timestamps, better time resolution on Windows
* disable flaky timestamp assertion on Windows

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [x] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Review by anthonyeleven — APPROVED** [review]
Docs LGTM by virtue of there not really being docs changes here.  I might pick at capitalization in code comments but that would no doubt lead to being pelted with rocks and garbage ;)

**Review by vshankar — APPROVED** [review]
Looks fine. BTW, do run any windows specific tests before merging? @batrick

**Comment by petrutlucian94** [comment]
> Looks fine. BTW, do run any windows specific tests before merging? @batrick

the windows tests have been executed by this job: https://jenkins.ceph.com/job/ceph-windows-pull-requests/13846/console

**Comment by vshankar** [comment]
> > Looks fine. BTW, do run any windows specific tests before merging? @batrick
> 
> the windows tests have been executed by this job: https://jenkins.ceph.com/job/ceph-windows-pull-requests/13846/console
> 
> fwiw, it doesn't actually run `ceph_test_*`, that required a few other minor fixes so I went with a separate PR #48127) in order to keep this one simple and easy to review.

So, I presume this is blocked on https://github.com/ceph/ceph/pull/48127 (which is draft atm).

**Comment by petrutlucian94** [comment]
> > > Looks fine. BTW, do run any windows specific tests before merging? @batrick
> > 
> > 
> > the windows tests have been executed by this job: https://jenkins.ceph.com/job/ceph-windows-pull-requests/13846/console
> > fwiw, it doesn't actually run `ceph_test_*`, that required a few other minor fixes so I went with a separate PR #48127) in order to keep this one simple and easy to review.
> 
> So, I presume this is blocked on #48127 (which is draft atm).

No, it can be merged right away (well, after getting the green light from the qa team since it has the "needs-qa" label). The other PR is just a follow-up that's still wip - I'm currently fixing some test crashes.

**Comment by vshankar** [comment]
ready to merge once we get a QA ack.

**Comment by yuriw** [comment]
@vshankar I am confused why we have "ready-to-merge" here?

**Comment by vshankar** [comment]
> @vshankar I am confused why we have "ready-to-merge" here?

I was under the assumption that this is being run through teuthology and is good to merge once verified.

**Comment by vshankar** [comment]
> No, it can be merged right away (well, after getting the green light from the qa team since it has the "needs-qa" label). The other PR is just a follow-up that's still wip - I'm currently fixing some librados test crashes.

@petrutlucian94 Which QE team do you mean here? I checked with Yuri regarding this, but Yuri does not test changes for PRs in main branch (until told explicitly). Which mean we need to run this through teuthology as part of our PR test process.

**Comment by petrutlucian94** [comment]
> > No, it can be merged right away (well, after getting the green light from the qa team since it has the "needs-qa" label). The other PR is just a follow-up that's still wip - I'm currently fixing some librados test crashes.
> 
> @petrutlucian94 Which QE team do you mean here? I checked with Yuri regarding this, but Yuri does not test changes for PRs in main branch (until told explicitly). Which mean we need to run this through teuthology as part of our PR test process.

@vshankar I may have misunderstood the testing process, please correct me if I'm wrong. For most of my PRs, the approver added the ``needs-qa`` label and then someone else stepped in (who I assumed would be part of the qa team) and provided the teuthology test results. Some examples: https://github.com/ceph/ceph/pull/47303 https://github.com/ceph/ceph/pull/45272.

I don't have access to the Sepia lab, nor am I familiar with the teuthology tests. What can we do to get the PR merged?

**Comment by vshankar** [comment]
> > > No, it can be merged right away (well, after getting the green light from the qa team since it has the "needs-qa" label). The other PR is just a follow-up that's still wip - I'm currently fixing some librados test crashes.
> > 
> > 
> > @petrutlucian94 Which QE team do you mean here? I checked with Yuri regarding this, but Yuri does not test changes for PRs in main branch (until told explicitly). Which mean we need to run this through teuthology as part of our PR test process.
> 
> @vshankar I may have misunderstood the testing process, please correct me if I'm wrong. For most of my PRs, the approver added the `needs-qa` label and then someone else stepped in (who I assumed would be part of the qa team) and provided the teuthology test results. Some examples: #47303 #45272.

I guess things have changed a bit since then. We need to explicitly inform @yuriw to pick the changes and run it through various suites.

> 
> I don't have access to the Sepia lab, nor am I familiar with the teuthology tests. What can we do to get the PR merged?

I will include this in my test branch and run it though fs suite. If all goes well (which I think should), I'll merge the changes.

**Comment by petrutlucian94** [comment]
> I guess things have changed a bit since then. We need to explicitly inform @yuriw to pick the changes and run it through various suites.
> 
> > I don't have access to the Sepia lab, nor am I familiar with the teuthology tests. What can we do to get the PR merged?
> 
> I will include this in my test branch and run it though fs suite. If all goes well (which I think should), I'll merge the changes.

Awesome, thanks! I think the workflow should be documented (e.g. here https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst). It can be very confusing, especially for new contributors that may wonder why the PRs are stuck.

**Comment by petrutlucian94** [comment]
jenkins test make check

**Review by rishabh-d-dave — APPROVED** [review]
Looks good.

Perhaps you missed replacing in a few following places -
https://github.com/petrutlucian94/ceph/blob/tests/src/libcephfs.cc#L666
https://github.com/petrutlucian94/ceph/blob/tests/src/test/libcephfs/test.cc#L1361
https://github.com/petrutlucian94/ceph/blob/tests/src/test/libcephfs/test.cc#L271

**Comment by petrutlucian94** [comment]
jenkins test api

**Comment by petrutlucian94** [comment]
@rishabh-d-dave I've updated the PR. The Windows job failed on all recent PRs while trying to download the vm image:

``
Downloading VM image from https://filedump.ceph.com/windows/ceph-win-ltsc2019-ci-image.qcow2
+ curl -s -L https://filedump.ceph.com/windows/ceph-win-ltsc2019-ci-image.qcow2 -o /home/jenkins-build/build/workspace/ceph-windows-pull-requests/libvirt/ceph-windows-client.qcow2
```

As far as I understood from my colleague, the file server VM has to be restarted by someone who has access to drop.front.sepia.ceph.com. Would you be able to assist us with that?

**Comment by petrutlucian94** [comment]
jenkins test api

**Comment by rishabh-d-dave** [comment]
jenkins test windows

**Comment by rishabh-d-dave** [comment]
@petrutlucian94 
> @rishabh-d-dave I've updated the PR. The Windows job failed on all recent PRs while trying to download the vm image:
> 
> ```
> Downloading VM image from https://filedump.ceph.com/windows/ceph-win-ltsc2019-ci-image.qcow2
> + curl -s -L https://filedump.ceph.com/windows/ceph-win-ltsc2019-ci-image.qcow2 -o /home/jenkins-build/build/workspace/ceph-windows-pull-requests/libvirt/ceph-windows-client.qcow2
> ```
> 
> As far as I understood from my colleague, the file server VM has to be restarted by someone who has access to drop.front.sepia.ceph.com. Would you be able to assist us with that?

I don't if that would be appropriate, I have never done that before. Perhaps it would be appropriate to ask this in IRC channel #sepia?

**Comment by petrutlucian94** [comment]
> @petrutlucian94
> 
> > @rishabh-d-dave I've updated the PR. The Windows job failed on all recent PRs while trying to download the vm image:
> > ```
> > Downloading VM image from https://filedump.ceph.com/windows/ceph-win-ltsc2019-ci-image.qcow2
> > + curl -s -L https://filedump.ceph.com/windows/ceph-win-ltsc2019-ci-image.qcow2 -o /home/jenkins-build/build/workspace/ceph-windows-pull-requests/libvirt/ceph-windows-client.qcow2
> > ```
> > 

> > As far as I understood from my colleague, the file server VM has to be restarted by someone who has access to drop.front.sepia.ceph.com. Would you be able to assist us with that?
> 
> I don't if that would be appropriate, I have never done that before. Perhaps it would be appropriate to ask this in IRC channel #sepia?

For sure. Looks like http://pulpito.front.sepia.ceph.com is also down and I think @dmick might be able to help us.

**Comment by rishabh-d-dave** [comment]
Hi, @petrutlucian94. I've excluded this PR from the current batch for integration testing because building Ceph binaries for this PR branch fails due to a C++ error.  I spent some time with the error messages and this PR and wrote a patch to fix it. 

I can't push a commit to your PR branch (because I am not permitted to do so), so I've posted the patch here instead - https://github.com/rishabh-d-dave/ceph/commit/dea9b713a24372200b17c21faea9ed0914596f72. Please review and include this patch so that this PR can be put through testing.

I am removing my testing label for now, please tag me (@rishabh-d-dave ) or @vshankar when it's ready.

**Comment by petrutlucian94** [comment]
jenkins test windows

**Comment by petrutlucian94** [comment]
jenkins test windows

**Review by vshankar — APPROVED** [review]

**Comment by vshankar** [comment]
@petrutlucian94 apologies for the delay in merging this - we are having some issued with shaman builds.

**Comment by petrutlucian94** [comment]
jenkins test make check

**Comment by petrutlucian94** [comment]
I've triggered a make check just to ensure that it still works as expected.

**Comment by vshankar** [comment]
FYI - The teuthology queue is loaded, so tests are not getting scheduled as I expected. I'm running libcephfs specific tests which have far more lesser jobs than a full blown run. I think that's the best way forward to get this tested and merged. Find the test run here - https://pulpito.ceph.com/vshankar-2023-02-13_06:07:50-fs-wip-vshankar-testing-20230207.045711-testing-default-smithi/

**Comment by vshankar** [comment]
https://pulpito.ceph.com/vshankar-2023-02-13_06:07:50-fs-wip-vshankar-testing-20230207.045711-testing-default-smithi/

**Pull request merged**
