### PR TITLE
rgw: add subuser to user policy condition check

### PR DESCRIPTION
**Pull request by Inode1**
Add rgw:subuser field (with subuser name) to user policy condition for managing multi keys in user policy engine. So that if user has multiple keys, user policy by condition can defined which key from user is requesting.

Signed-off-by: ivan [i.makarychev@tinkoff.ru](mailto:i.makarychev@tinkoff.ru)

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [X] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [X] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [X] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [X] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by Inode1** [comment]
jenkins test make check

**Comment by cbodley** [comment]
for posterity, there was some earlier discussion in https://github.com/ceph/ceph/pull/53750:

> so my only objection is that we're calling this condition s3:subuser rather than rgw:subuser. i think that would help make it clear which parts of the policy are general, and which rely on rgw extensions

this was addressed, thanks

**Comment by pritha-srivastava** [comment]
@Inode1 : Can you give an example of a policy where you would use 'subuser' . In the commit message you mention that this is for User Policies, since a User Policy does not have a `Principal`, are you planning to use 'subuser' in the `Condition` element of the Policy?

**Comment by Inode1** [comment]
> @Inode1 : Can you give an example of a policy where you would use a 'subuser' . In the commit message you mention that this is for User Policies, since a User Policy does not have a `Principal`, are you planning to use 'subuser' in the `Condition` element of the Policy?

Yup, here you are, I use `rgw:subuser` in the `Condition` element of the Policy to give differrent permission for subusers:
`{
        "Version": "2012-10-17",
        "Statement": [
            {
                "Sid": "Allow",
                "Effect": "Allow",
                "Action": [
                    "s3:ListAllMyBuckets",
                    "s3:ListBucket",
                ],
                "Condition": {
                    "StringEqualsIgnoreCase": {
                        "rgw:subuser": "test-subuser"
                    }
                },
                "Resource": "*"
            },
            {
                "Sid": "Deny",
                "Effect": "Deny",
                "Action": [
                    "s3:CreateBucket",
                    "s3:DeleteBucket"
                ],
                "Condition": {
                    "StringEqualsIgnoreCase": {
                        "rgw:subuser": "test-subuser"
                    }
                },
                "Resource": "*"
            }
        ]
}`

**Comment by pritha-srivastava** [comment]
> > @Inode1 : Can you give an example of a policy where you would use a 'subuser' . In the commit message you mention that this is for User Policies, since a User Policy does not have a `Principal`, are you planning to use 'subuser' in the `Condition` element of the Policy?
> 
> Yup, here you are, I use `rgw:subuser` in the `Condition` element of the Policy to give differrent permission for subusers: `{ "Version": "2012-10-17", "Statement": [ { "Sid": "Allow", "Effect": "Allow", "Action": [ "s3:ListAllMyBuckets", "s3:ListBucket", ], "Condition": { "StringEqualsIgnoreCase": { "rgw:subuser": "test-subuser" } }, "Resource": "*" }, { "Sid": "Deny", "Effect": "Deny", "Action": [ "s3:CreateBucket", "s3:DeleteBucket" ], "Condition": { "StringEqualsIgnoreCase": { "rgw:subuser": "test-subuser" } }, "Resource": "*" } ] }`



> > @Inode1 : Can you give an example of a policy where you would use a 'subuser' . In the commit message you mention that this is for User Policies, since a User Policy does not have a `Principal`, are you planning to use 'subuser' in the `Condition` element of the Policy?
> 
> Yup, here you are, I use `rgw:subuser` in the `Condition` element of the Policy to give differrent permission for subusers: `{ "Version": "2012-10-17", "Statement": [ { "Sid": "Allow", "Effect": "Allow", "Action": [ "s3:ListAllMyBuckets", "s3:ListBucket", ], "Condition": { "StringEqualsIgnoreCase": { "rgw:subuser": "test-subuser" } }, "Resource": "*" }, { "Sid": "Deny", "Effect": "Deny", "Action": [ "s3:CreateBucket", "s3:DeleteBucket" ], "Condition": { "StringEqualsIgnoreCase": { "rgw:subuser": "test-subuser" } }, "Resource": "*" } ] }`

@cbodley : Do we not allow multiple subusers to be created for a user? 
Also by allowing a subuser in the `Condition` element of a policy, we are allowing access to a resource to a subuser without actually authenticating with the subuser (I don't know whether clients can sign requests using credentials of a subuser) - if this is acceptable, then `subusers` can be used in bucket policies and other identity policies supported in rgw.

**Comment by cbodley** [comment]
> @cbodley : Do we not allow multiple subusers to be created for a user? Also by allowing a subuser in the `Condition` element of a policy, we are allowing access to a resource to a subuser without actually authenticating with the subuser (I don't know whether clients can sign requests using credentials of a subuser) - if this is acceptable, then `subusers` can be used in bucket policies and other identity policies supported in rgw.

@pritha-srivastava you can add multiple subusers to a given user. the user can also have multiple access/secret key pairs. `struct RGWAccessKey` has an optional `string subuser` field to associate each credential with a specific subuser. when authenticating with such an access key, the associated subuser is exposed via `s->auth.identity->get_subuser()`

**Comment by Inode1** [comment]
@pritha-srivastava @adamemerson: Hello, could you review this pr, plz.

**Comment by cbodley** [comment]
i'll give Pritha and Adam some time to voice objections, but we can go ahead with qa in the meantime

**Comment by pritha-srivastava** [comment]
> > @cbodley : Do we not allow multiple subusers to be created for a user? Also by allowing a subuser in the `Condition` element of a policy, we are allowing access to a resource to a subuser without actually authenticating with the subuser (I don't know whether clients can sign requests using credentials of a subuser) - if this is acceptable, then `subusers` can be used in bucket policies and other identity policies supported in rgw.
> 
> @pritha-srivastava you can add multiple subusers to a given user. the user can also have multiple access/secret key pairs. `struct RGWAccessKey` has an optional `string subuser` field to associate each credential with a specific subuser. when authenticating with such an access key, the associated subuser is exposed via `s->auth.identity->get_subuser()`

@cbodley : Do you mean that when we create a subuser with certain credentials, the credentials actually belong to the user and the subuser is associated with those credentials via `s->auth.identity->get_subuser()`? What I mean to ask is that will the request be signed by the same credential as the subuser's while sending the request as given in this PR?

**Comment by pritha-srivastava** [comment]
> > > @cbodley : Do we not allow multiple subusers to be created for a user? Also by allowing a subuser in the `Condition` element of a policy, we are allowing access to a resource to a subuser without actually authenticating with the subuser (I don't know whether clients can sign requests using credentials of a subuser) - if this is acceptable, then `subusers` can be used in bucket policies and other identity policies supported in rgw.
> > 
> > 
> > @pritha-srivastava you can add multiple subusers to a given user. the user can also have multiple access/secret key pairs. `struct RGWAccessKey` has an optional `string subuser` field to associate each credential with a specific subuser. when authenticating with such an access key, the associated subuser is exposed via `s->auth.identity->get_subuser()`
> 
> @cbodley : Do you mean that when we create a subuser with certain credentials, the credentials actually belong to the user and the subuser is associated with those credentials via `s->auth.identity->get_subuser()`? What I mean to ask is that will the request be signed by the same credential as the subuser's while sending the request as given in this PR?

Ok, I get it now, the subuser here is associated with an s3 credentials pair using this command - `radosgw-admin key create --subuser=foo:bar --key-type=s3 --access-key barAccessKey --secret-key barSecretKey`, and for the access-key/secret-key pair used to sign this request, the associated subuser will be used to verify with the one given in the policy.

**Review by pritha-srivastava — APPROVED** [review]

**Comment by cbodley** [comment]
passed qa after rerun in https://pulpito.ceph.com/cbodley-2023-11-03_18:34:54-rgw-wip-cbodley-testing-distro-default-smithi/

**Pull request merged**
