### PR TITLE
luminous: mgr: Module 'influx' has failed

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/25201

### CODE REVIEW

**Comment by smithfarm** [comment]
@wido And the way I did the backport looks OK to you? The name of the function changed between luminous and mimic.

**Comment by wido** [comment]
Yes, that's where you want to make this change indeed. So I'm LGTM

**Comment by tserong** [comment]
> @wido And the way I did the backport looks OK to you? The name of the function changed between luminous and mimic.

Wait a sec, it looks like Luminous calls `get_metadata()` in `get_daemon_stats()`, and Mimic calls `get_metadata()` in _two_ places, once in `get_pg_summary()` and once in `get_daemon_stats()`. #22794 only added the skip logic to `get_pg_summary()`, not to `get_daemon_stats()`. Should Mimic also have this logic added to its `get_daemon_stats()`?

So this backport LGTM, but has it just highlighted an omission in Mimic? Or am I just not familiar enough with this module? :-)

**Comment by smithfarm** [comment]
> but has it just highlighted an omission in Mimic?

And master, too, for that matter.

**Comment by wido** [comment]
I would need to check that. Currently swamped with a big backlog of other things.

I think in this case the PR is good to merge for backport, but master and Mimic should be checked indeed.

**Comment by smithfarm** [comment]
> Should I open a bug or something?

Yes, please - it looks to me like this will need a follow-up PR in master, which means it'll need a tracker issue and a mimic backport.

**Comment by tserong** [comment]
Done: https://tracker.ceph.com/issues/37377

**Comment by yuriw** [comment]
[wip-yuri3-testing-2018-11-27-2241-luminous](https://trello.com/c/ntdQZjkB/481-wip-yuri3-testing-2018-11-27-2241-luminous)

**Pull request merged**
