### PR TITLE
 systemd/rbdmap.service: order us before remote-fs-pre.target

### PR DESCRIPTION
**Pull request by idryomov**

### CODE REVIEW

**Comment by dillaman** [comment]
@idryomov Can you open a tracker ticket so this can be backported to mimic and luminous?

**Comment by idryomov** [comment]
@dillaman I can, but it's not strictly a bug fix -- more of a minor improvement.

**Comment by idryomov** [comment]
Opened http://tracker.ceph.com/issues/24713 and added a Fixes tag.  Didn't mark it for backporting though -- can decide later.

**Comment by dillaman** [comment]
I read "interfering with systemd shutdown logic" as being a bad thing that should be fixed.  Seems like a trivial backport if it improves some issue w/ shutdown.

**Comment by idryomov** [comment]
Yeah, it's probably best to have the same unit file in all supported releases, to minimize confusion when debugging if nothing else.

**Comment by idryomov** [comment]
retest this please

**Comment by idryomov** [comment]
retest this please

**Pull request merged**
