### PR TITLE
cls_rgw: use more effective container operations in get_obj_vals

### PR DESCRIPTION
**Pull request by cfanz**
Signed-off-by: Xinying Song <songxinying@cloudin.cn>

### CODE REVIEW

**Comment by cbodley** [comment]
thanks, looks good! we should probably add some extra test coverage to `test/cls_rgw/test_cls_rgw.cc` though, to make sure we got both sides of the `BI_PREFIX_CHAR` right

**Comment by cfanz** [comment]
@cbodley I have added a test case. It writes 4 kinds utf8 object names: single byte, double byte, treble byte and quadruple byte, and one invalid object name belong to rgw's private namespace BI_PREFIX_CHAR. Except for BI_PREFIX_CHAR, other invalid utf8 characters will never occur in bucket index.

**Comment by yuriw** [comment]
[wip-yuri-testing-2017-12-12-1602](https://trello.com/c/a1IyuU7P/210-wip-yuri-testing-2017-12-12-1602)

**Comment by yuriw** [comment]
[wip-yuri-testing-2017-12-12-1602](https://trello.com/c/a1IyuU7P/210-wip-yuri-testing-2017-12-12-1602)

**Pull request merged**
