### PR TITLE
jewel: rgw: s3website error handler uses original object name

### PR DESCRIPTION
**Pull request by cbodley**
backport tracker http://tracker.ceph.com/issues/23311

includes the commit from https://github.com/ceph/ceph/pull/15703

### CODE REVIEW

**Comment by smithfarm** [comment]
@cbodley Thanks

**Comment by smithfarm** [comment]
@cbodley Maybe some C++17-ism in the code?

```
rgw/rgw_rest_s3.cc: In member function ‘bool RGWHandler_REST_S3Website::web_dir() const’:
rgw/rgw_rest_s3.cc:4304:54: error: too few arguments to function ‘bool url_decode(const string&, std::__cxx11::string&, bool)’
   std::string subdir_name = url_decode(s->object.name);
                                                      ^
In file included from rgw/rgw_op.h:30:0,
                 from rgw/rgw_rest.h:12,
                 from rgw/rgw_rest_s3.cc:15:
rgw/rgw_common.h:1894:13: note: declared here
 extern bool url_decode(const string& src_str, string& dest_str, bool in_query = false);
             ^
rgw/rgw_rest_s3.cc:4315:11: error: ‘class RGWObjectCtx’ has no member named ‘obj’
   obj_ctx.obj.set_atomic(obj);
           ^
rgw/rgw_rest_s3.cc:4316:11: error: ‘class RGWObjectCtx’ has no member named ‘obj’
   obj_ctx.obj.set_prefetch_data(obj);
           ^
rgw/rgw_rest_s3.cc:4319:72: error: no matching function for call to ‘RGWRados::get_obj_state(RGWObjectCtx*, RGWBucketInfo&, rgw_obj&, RGWObjState**, bool)’
   if (store->get_obj_state(&obj_ctx, s->bucket_info, obj, &state, false) < 0) {
                                                                        ^
In file included from rgw/rgw_op.h:31:0,
                 from rgw/rgw_rest.h:12,
                 from rgw/rgw_rest_s3.cc:15:
rgw/rgw_rados.h:2732:7: note: candidate: int RGWRados::get_obj_state(RGWObjectCtx*, rgw_obj&, RGWObjState**, bool)
   int get_obj_state(RGWObjectCtx *rctx, rgw_obj& obj, RGWObjState **state, bool follow_olh);
       ^
rgw/rgw_rados.h:2732:7: note:   candidate expects 4 arguments, 5 provided
rgw/rgw_rados.h:2733:7: note: candidate: int RGWRados::get_obj_state(RGWObjectCtx*, rgw_obj&, RGWObjState**)
   int get_obj_state(RGWObjectCtx *rctx, rgw_obj& obj, RGWObjState **state) {
       ^
rgw/rgw_rados.h:2733:7: note:   candidate expects 3 arguments, 5 provided
Makefile:24907: recipe for target 'rgw/librgw_la-rgw_rest_s3.lo' failed
make[3]: *** [rgw/librgw_la-rgw_rest_s3.lo] Error 1
make[3]: *** Waiting for unfinished jobs....
rgw/rgw_swift_auth.cc: In member function ‘virtual void RGW_SWIFT_Auth_Get::execute()’:
rgw/rgw_swift_auth.cc:144:15: warning: unused variable ‘token_tag’ [-Wunused-variable]
   const char *token_tag = "rgwtk";
               ^
```

**Comment by cbodley** [comment]
> @cbodley Maybe some C++17-ism in the code?

just more conflicts, i'll fix those up. jewel is too much of a pain to build locally, so i'll rely on help from jenkins here :)

**Comment by cbodley** [comment]
@smithfarm okay, looks ready now

**Comment by smithfarm** [comment]
This PR passed a rados run at http://tracker.ceph.com/issues/21742#note-21 and an rgw run at http://tracker.ceph.com/issues/21742#note-24

It's already been approved by @cbodley so I'm merging.

**Pull request merged**
