### PR TITLE
crimson: misc fixes

### PR DESCRIPTION
**Pull request by athanatos**
<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Comment by athanatos** [comment]
https://pulpito.ceph.com/sjust-2023-12-16_03:12:47-crimson-rados-wip-sjust-crimson-testing-2023-12-15-distro-default-smithi/

**Review by Matan-B — APPROVED** [review]
LGTM

https://tracker.ceph.com/issues/63845 is a duplicate and therefore not related to the changes here (tracker updated).

nit: commit message typo - set::set

Can we cherry-pick 42d2c82125656bcb38618ba4767cee7975505935 (#54609) to here?

cc: @xxhdx1985126

**Comment by xxhdx1985126** [comment]
> LGTM
> 
> https://tracker.ceph.com/issues/63845 is a duplicate and therefore not related to the changes here (tracker updated).
> 
> nit: commit message typo - set::set
> 
> Can we cherry-pick [42d2c82](https://github.com/ceph/ceph/commit/42d2c82125656bcb38618ba4767cee7975505935) (from #54609) to here?
> 
> cc: @xxhdx1985126

Done.:-)

**Comment by Matan-B** [comment]
https://shaman.ceph.com/builds/ceph/wip-matanb-crimson-testing-misc

**Comment by athanatos** [comment]
@Matan-B Any reason not to merge the changes I tested above in the mean time?

**Comment by Matan-B** [comment]
> @Matan-B Any reason not to merge the changes I tested above in the mean time?

No particular reason, I scheduled a run with all the changes:
https://pulpito.ceph.com/matan-2023-12-18_19:29:45-crimson-rados-wip-matanb-crimson-testing-misc-distro-crimson-smithi/
We can wait for it to complete and merge all or omit the cherry-pick and merge based on your tests.

**Comment by Matan-B** [comment]
jenkins test api

**Comment by athanatos** [comment]
@Matan-B I'm going to merge the original PR -- we can do https://github.com/ceph/ceph/commit/42d2c82125656bcb38618ba4767cee7975505935 as a follow up PR.

**Pull request merged**
