### PR TITLE
rados cli --striper

### PR DESCRIPTION
**Pull request by liewegas**

### CODE REVIEW

**Comment by liewegas** [comment]
@sponce These are rebased on master but they're segfaulting.. did I screw up the rebase or is there an issue there?

**Comment by sponce** [comment]
I'll try to look at it tomorrow. It was not segfaulting when I wrote it, but in the meantime, the libradosstriper that it uses has been somehow broken by the introduction of LTTng, so it could come from there. Although I would expect a clean exit with some message about duplicated tracepoints, not a segfault.

**Comment by sponce** [comment]
I've just tested a rebase on master and everything worked for me. But it did not compile ! I had to fix the Makefile.am of the src/tools directory that had been split into client/server pieces and thus did not merge well.
I've also fixed on my way the man page.
I've put the resulting code into my github : https://github.com/sponce/ceph/tree/wip-10759
Should I create a new pull request ?

**Comment by liewegas** [comment]
yeah, just do a new pull request.  thanks!

**Comment by sponce** [comment]
New pull request created : #4166

**Pull request closed without merging**
