### PR TITLE
ceph-volume: Fix TypeError: join() takes exactly one argument (2 given)

### PR DESCRIPTION
**Pull request by sebastian-philipp**
Signed-off-by: Sebastian Wagner <sebastian.wagner@suse.com>
Fixes: http://tracker.ceph.com/issues/37595

### CODE REVIEW

**Comment by LenzGr** [comment]
Fixing a regression introduced in #25425

**Comment by alfredodeza** [comment]
This needs to have unit tests associated with this function. Otherwise regressions like the one this PR is fixing can keep going undetected. Please include the unit tests needed to cover all cases in this function.

**Comment by sebastian-philipp** [comment]
This regression was found by #25236 which will add Teuthology testing to the orchestrator (which will invoke c-v). So, #25236 can already be seen as the integration test code for this PR.

Right now, I don't have time to add additional unit tests for this function. If you want to, I can look into adding unit tests for this PR tomorrow.

**Comment by alfredodeza** [comment]
Sure, I don't mind other functional tests. But for sure we don't want to pursue more changes without having tests that verify the patch.

**Comment by alfredodeza** [comment]
jenkins test ceph-volume tox

**Pull request merged**
