### PR TITLE
Server: drop locks and auth pins if wait for pending truncate

### PR DESCRIPTION
**Pull request by xiexingguo**
Signed-off-by: xie xingguo <xie.xingguo@zte.com.cn>

### CODE REVIEW

**Comment by xiexingguo** [comment]
@jcsp I reopen one based on your suggestion(https://github.com/ceph/ceph/pull/9713#discussion_r67127129). Thanks!

**Comment by gregsfortytwo** [comment]
I've got the same concern about reordering operations here I have with the other PR.

**Comment by xiexingguo** [comment]
retest this please

**Comment by jcsp** [comment]
@xiexingguo please can you have a look at greg's comments on #9713 about this potentially leading to reordered operations

**Comment by gregsfortytwo** [comment]
I'll reproduce here for easier conversation.

gregsfortytwo commented 12 days ago:
>I guess I missed the window, but can somebody explain why it's okay to drop locks here? Amongst other things, we've already succeeded in locking and the mdr remembers that, so it won't try to acquire the locks again on the next go-round...

gregsfortytwo commented 12 days ago:
> Oh, I guess we do clear out the done_locking flag. So it's just a question of whether we're okay re-ordering ops. I don't really think we are since we've already started removing the file data, but we haven't changed the truncate sizes yet?

**Comment by xiexingguo** [comment]
@gregsfortytwo @jcsp 
I'll recheck with these, thanks!

**Comment by gregsfortytwo** [comment]
So I looked at this more carefully and it *might* be okay? In that

- the MDS is currently deleting file data, for a truncate which has been reported complete
- We are choosing to pause a truncate op before reporting it as complete
- any ops which come in simultaneous with it can be ordered before or after the truncate, as we choose

But, I'm concerned that by releasing locks right now, and retrieving them later, we might start the truncate while other ops are in flight or something and expose non-atomic updates as a result. Not sure.

**Comment by xiexingguo** [comment]
@gregsfortytwo 
Aren't the ops that have to wait always ordered before we queuing them?

```
  void add_waiter(uint64_t mask, MDSInternalContextBase *c) {
    parent->add_waiter((mask << get_wait_shift()) | MDSCacheObject::WAIT_ORDERED, c);
  }

```
Also I have checked that there are a couple of cases we handle the client ops the same way:

```
void Server::handle_client_readdir(MDRequestRef& mdr)
void Server::handle_client_file_setlock(MDRequestRef& mdr)
void Server::handle_client_setattr(MDRequestRef& mdr)

```

Not sure whether I understand it correctly, but to me it is generally not a good idea to queue a op
with locks held in hand.

**Comment by xiexingguo** [comment]
@gregsfortytwo @jcsp 
Is this one still relevant?

**Comment by gregsfortytwo** [comment]
I'll dig into the ordering question in the morning after I get some sleep. :)

**Comment by xiexingguo** [comment]
@gregsfortytwo :+1:  Have a good rest.

**Comment by gregsfortytwo** [comment]
Yeah, I think this is fine and I was just confused when I saw it go by the first time. Sorry! :(

**Comment by gregsfortytwo** [comment]
Reviewed-by:

**Comment by xiexingguo** [comment]
@gregsfortytwo Thanks for the clarification.

I see @jcsp  john already done testing at:

http://pulpito.ceph.com/jspray-2016-06-28_01:48:02-fs-wip-jcsp-testing-20160627-xxg-distro-basic-mira/

And you make check the branch below for detail:
https://github.com/ceph/ceph/commits/wip-jcsp-testing-20160627-xxg

So seems this one is safe to merge and we don't have to test again:-)

**Comment by xiexingguo** [comment]
@jcsp Can you merge this? It's been hanging for about a month and I don't want to keep an eye on it from time to time...

Thanks!

**Comment by xiexingguo** [comment]
@jcsp Thanks!

**Pull request merged**
