### PR TITLE
mgr/dashboard: replace ngx-datatable by carbon datatable

### PR DESCRIPTION
**Pull request by ivoalmeida**
Fixes: https://tracker.ceph.com/issues/66965

* replaced ngx-datatable by carbon datatable
* created carbon themes for content and tables
* redesigned table actions to render as kebab menu options per data row
* keep only primary actions on datatable toolbar
* implemented carbon batch actions

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [x] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [x] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [x] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

image
image
image

### CODE REVIEW

**Comment by nizamial09** [comment]
Thank you @ivoalmeida. I was testing this and observed couple of issues. I'll attach videos and photos to the issues that I saw

When the table refresh happens (every 5 sec), I see I am getting automatically restored to the top of the page for some reason even if I am scrolling down.
https://github.com/user-attachments/assets/9418a3de-9b15-4904-900d-eea04eb8f60d


When you try to do the table actions, I see the tableactions are disabled on alternative click probably because its selecting and deselecting in between clicks and sometimes when the action menu opens the row is not selected and the actions are disabled.
https://github.com/user-attachments/assets/5a68e1e6-24df-4169-ba3a-1941030f2684

In Hosts page, the `Service Instances` column is missing items. It used to show all the services or daemons running in that node along with its count in badges
Screenshot from 2024-07-17 12-29-23

Nit: (can be dealt separately), In OSDs page, i think `Delete`, `Destroy` and `Purge` should be danger actions (buttons)
Screenshot from 2024-07-17 12-31-31

On the RBD Mirroring page, we used to have a an action button here for Creating and Importing the Bootstrap token which is missing now.
Screenshot from 2024-07-17 12-34-37

On User management page, when you create a Role, that page used to show a table to select the permissions or scopes that can be associated with a user. That's now missing and its saying No data to show in the table.
Screenshot from 2024-07-17 12-36-00

the same issue as above in the Subvolume and Subvolume group page.
Screenshot from 2024-07-17 12-36-30

Services page is broken
Screenshot from 2024-07-17 12-39-14

In the Upgrade page, there is a table that shows the daemon versions which shows empty now.
Screenshot from 2024-07-17 12-39-41


On the Monitoring page, the Alert details are empty. Also I notice that it takes some time for `Alerts` page to show all the Alerts available. not sure why..
https://github.com/user-attachments/assets/0c2d327e-4c1e-4714-aec8-63a5df9e789f

**Comment by nizamial09** [comment]
the navbar looks a bit messed up with increased spacing between icon and the name, and the child items have a lot of padding. Also the active hamburger color is changed to a grey shade now
Screenshot from 2024-07-17 12-28-11

**Comment by nizamial09** [comment]
also what about adding skeletons when the data is loading? Right now it just shows No data to display while the data is being loaded
https://carbondesignsystem.com/patterns/loading-pattern/#skeleton-states

**Comment by epuertat** [comment]
Awesome work, @ivoalmeida ! As in Carbon corners and everything seems to be squared instead of rounded (and without outlines, just plain colors), are you planning to update badges/tabs/etc to match that visual style?

**Comment by epuertat** [comment]
BTW, should we keep the page background in white or Carbon suggests another color?

**Comment by ivoalmeida** [comment]
jenkins test api

**Comment by ivoalmeida** [comment]
jenkins test windows

**Comment by ivoalmeida** [comment]
jenkins retest this please

**Comment by ivoalmeida** [comment]
jenkins retest this please

**Comment by ivoalmeida** [comment]
jenkins retest this please

**Comment by ivoalmeida** [comment]
jenkins retest this please

**Comment by ivoalmeida** [comment]
jenkins test windows

**Comment by ivoalmeida** [comment]
jenkins test dashboard cephadm

**Review by nizamial09 — COMMENTED** [review]
apart from the below 2 issues, everything looks good, thank you. 

> When the table refresh happens (every 5 sec), I see I am getting automatically restored to the top of the page for some reason even if I am scrolling down.
> https://github.com/user-attachments/assets/9418a3de-9b15-4904-900d-eea04eb8f60d

the above issue is still there.. 



> the navbar looks a bit messed up with increased spacing between icon and the name, and the child items have a lot of padding. Also the active hamburger color is changed to a grey shade now
> Screenshot from 2024-07-17 12-28-11

nav bar is still a bit weird

**Comment by ivoalmeida** [comment]
> apart from the below 2 issues, everything looks good, thank you.
> 
> > When the table refresh happens (every 5 sec), I see I am getting automatically restored to the top of the page for some reason even if I am scrolling down.
> > https://github.com/user-attachments/assets/9418a3de-9b15-4904-900d-eea04eb8f60d
> 
> the above issue is still there..
> 
> > the navbar looks a bit messed up with increased spacing between icon and the name, and the child items have a lot of padding. Also the active hamburger color is changed to a grey shade now
> > Screenshot from 2024-07-17 12-28-11
> 
> nav bar is still a bit weird

The first issue should be resolved now.

The second one regarding the nav bar I don't understand. There are no more overrides there. The spacing is correct and the colours are correct too. Can you point what exactly looks "weird"?

Thanks

**Comment by ivoalmeida** [comment]
jenkins test dashboard cephadm

**Comment by ivoalmeida** [comment]
jenkins test dashboard cephadm

**Comment by ivoalmeida** [comment]
jenkins test dashboard cephadm

**Comment by ivoalmeida** [comment]
jenkins test make check

**Comment by ivoalmeida** [comment]
jenkins test api

**Comment by ivoalmeida** [comment]
jenkins retest this please

**Comment by ivoalmeida** [comment]
jenkins test dashboard cephadm

**Comment by nizamial09** [comment]
jenkins test dashboard cephadm

**Comment by nizamial09** [comment]
jenkins test make check

**Comment by ivoalmeida** [comment]
jenkins test dashboard cephadm

**Comment by ivoalmeida** [comment]
jenkins test make check

**Comment by ivoalmeida** [comment]
jenkins test dashboard cephadm

**Comment by ivoalmeida** [comment]
jenkins test dashboard cephadm

**Comment by ivoalmeida** [comment]
jenkins test dashboard cephadm

**Comment by ivoalmeida** [comment]
jenkins test make check

**Review by nizamial09 — APPROVED** [review]

**Comment by nizamial09** [comment]
Let's fix the tests in a separate PR.

@ivoalmeida: meanwhile we'll have to look at the performance improvements of this new datatable. Is there a way to compare the new one with the older one as it is now and then do the performance improvements to the new one, test it once more with the older and newer one? Let's try to have some numbers so we know we are not off by a lot.

**Pull request merged**
