### PR TITLE
mimic: CLI: ability to change file ownership

### PR DESCRIPTION
**Pull request by pdvian**
http://tracker.ceph.com/issues/38511

### CODE REVIEW

**Comment by smithfarm** [comment]
jenkins re-test this please

**Comment by batrick** [comment]
jenkins retest make check

**Comment by batrick** [comment]
retest make check

**Comment by batrick** [comment]
retest this please

**Comment by yuriw** [comment]
[wip-yuri3-testing-2019-04-29-1935-mimic](https://trello.com/c/1OdZ5zIb/598-wip-yuri3-testing-2019-04-29-1935-mimic)

**Comment by yuriw** [comment]
[wip-yuri4-testing-2019-04-30-1543-mimic](https://trello.com/c/A2lSYsdc/600-wip-yuri4-testing-2019-04-30-1543-mimic)

**Comment by yuriw** [comment]
[wip-yuri4-testing-2019-04-30-1620-mimic](https://trello.com/c/A2lSYsdc/600-wip-yuri4-testing-2019-04-30-1620-mimic)

**Pull request merged**
