### PR TITLE
pacific: mgr/prometheus: expose ceph healthchecks as metrics

### PR DESCRIPTION
**Pull request by avanthakkar**
Also includes backport for:  https://github.com/ceph/ceph/pull/43783

backport tracker: https://tracker.ceph.com/issues/53616

---

backport of https://github.com/ceph/ceph/pull/43293, https://github.com/ceph/ceph/pull/43783
parent trackers: https://tracker.ceph.com/issues/52638, https://tracker.ceph.com/issues/53111

this backport was staged using ceph-backport.sh version 16.0.0.6848
find the latest version at https://github.com/ceph/ceph/blob/master/src/script/ceph-backport.sh

### CODE REVIEW

**Review by nizamial09 — APPROVED** [review]

**Comment by avanthakkar** [comment]
Included backport for https://github.com/ceph/ceph/pull/43783 as well. BTW I faced a conflict while cherry-picking: snmp README.md doesn't exist in pacific yet, so should it be included @pcuzner ? I've ignored it for now.

**Comment by avanthakkar** [comment]
jenkins test docs

**Comment by avanthakkar** [comment]
jenkins test dashboard

**Comment by avanthakkar** [comment]
jenkins test docs

**Comment by avanthakkar** [comment]
jenkins test dashboard

**Comment by pcuzner** [comment]
> Included backport for #43783 as well. BTW I faced a conflict while cherry-picking: snmp README.md doesn't exist in pacific yet, so should it be included @pcuzner ? I've ignored it for now.

@avanthakkar if possible I think the README should be there since it describes the OID structure of the MIB. However, it's not user facing so you can drop to expedite the PR, IMO.

**Review by pcuzner — APPROVED** [review]
LGTM, thanks!

**Comment by avanthakkar** [comment]
jenkins test dashboard cephadm

**Comment by avanthakkar** [comment]
jenkins test api

**Comment by avanthakkar** [comment]
jenkins test api

**Comment by epuertat** [comment]
As discussed in today's meeting, I'm gonna launch a package build for this PR to ensure it doesn't break any distro and if passing, we can merge this.

**Pull request merged**
