### PR TITLE
 do_freebsd.sh: disable rdma features

### PR DESCRIPTION
**Pull request by tchaikov**

### CODE REVIEW

**Comment by tchaikov** [comment]
@tanghaodong25 i wonder if we cannot disable librdma-cm support at compile-time if we want RDMA (i.e. libiverbs), probably we should consolidate `WITH_VERBS` and `WITH_RDMACM` into a single option `WITH_RDMA`?

**Comment by tanghaodong25** [comment]
@tchaikov Right, we can't disable librdmacm if we just want libibverbs. Class "Infiniband" depends on both of these two libraries and it is the basic class used by all the RDMA protocol (Infiniband, RoCE, iWARP).

**Comment by tchaikov** [comment]
@tanghaodong25 @wjwithagen updated and repushed.

**Comment by tanghaodong25** [comment]
ok to me, thanks Kefu.

**Comment by tchaikov** [comment]
http://pulpito.ceph.com/kchai-2018-06-29_01:58:46-rados-wip-kefu-testing-2018-06-28-2341-distro-basic-smithi/

**Pull request merged**
