### PR TITLE
crush/CrushWrapper: make get_immediate_parent[_id] ignore per-class shadow hierarchy

### PR DESCRIPTION
**Pull request by liewegas**
Fixes: http://tracker.ceph.com/issues/20546
Signed-off-by: Sage Weil <sage@redhat.com>

### CODE REVIEW

**Comment by liewegas** [comment]
rebase and merge after https://github.com/ceph/ceph/pull/15643

**Comment by liewegas** [comment]
retest this please

**Comment by gregsfortytwo** [comment]
Is this still in progress or ready for review?

**Comment by liewegas** [comment]
ready for review. in my latest testing branch.

**Comment by liewegas** [comment]
http://pulpito.ceph.com/sage-2017-07-13_20:38:15-rados-wip-sage-testing-distro-basic-smithi/

**Pull request merged**
