### PR TITLE
Revert "src/ceph-crash.in: remove unused frame in handler()"

### PR DESCRIPTION
**Pull request by guits**
Revert "src/ceph-crash.in: remove unused frame in handler()"

This reverts commit 432c766a99f70884049bf7a1f268287a5a809777.

unused but required:

```
Traceback (most recent call last):
File "/usr/bin/ceph-crash", line 102, in <module>
main()
File "/usr/bin/ceph-crash", line 98, in main
time.sleep(args.delay * 60)
TypeError: handler() takes exactly 1 argument (2 given)
```

Fixes: https://tracker.ceph.com/issues/54422

Signed-off-by: Guillaume Abrioux <gabrioux@redhat.com>

### CODE REVIEW

**Review by asm0deuz — APPROVED** [review]

**Comment by rzarzynski** [comment]
The QA suite has `qa/suites/rados/singleton/all/test-crash.yaml`.

**Comment by adk3798** [comment]
jenkins retest this please

**Comment by adk3798** [comment]
I've scheduled a run of these `test-crash` tests with a build including this PR https://pulpito.ceph.com/adking-2022-09-14_18:08:58-rados:singleton-wip-adk-testing-2022-09-13-1304-distro-default-smithi/

**Comment by adk3798** [comment]
https://pulpito.ceph.com/adking-2022-09-14_18:08:58-rados:singleton-wip-adk-testing-2022-09-13-1304-distro-default-smithi/

test-crash run was green

**Pull request merged**
