### PR TITLE
luminous: Mimic build fails with -DWITH_RADOSGW=0

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/24774

### CODE REVIEW

**Comment by jcsp** [comment]
@bassam nothing on your end still relies on cephd from old stable branches, right?

**Comment by bassam** [comment]
@jcsp no. All good to go.

**Comment by smithfarm** [comment]
jenkins re-test this please

**Comment by yuriw** [comment]
[wip-yuri-testing-2018-08-01-1605-luminous](https://trello.com/c/DxuaJWNO/360-wip-yuri-testing-2018-08-01-1605-luminous)

**Pull request merged**
