### PR TITLE
mgr/prometheus: collect pg inconsistent info

### PR DESCRIPTION
**Pull request by Rjerk**
Collect pgs inconsistent info in prometheus.

Example:

No inconsistent pgs in cluster, prometheus:

```
# HELP ceph_pg_inconsistent_info PG Inconsistent Info
# TYPE ceph_pg_inconsistent_info untyped
ceph_pg_inconsistent_info{pg_id="",object="",primary_osd="",errors=""} 0.0
```

If there's pgs are inconsistent and the scrub happened, prometheus will collect the inconsistent pgs info:

```
# HELP ceph_pg_inconsistent_info PG Inconsistent Info
# TYPE ceph_pg_inconsistent_info untyped
ceph_pg_inconsistent_info{pg_id="5.4",object="ceph.doc",primary_osd="0",errors="[u'data_digest_mismatch', u'size_mismatch']"} 1.0
ceph_pg_inconsistent_info{pg_id="5.9",object="make",primary_osd="1",errors="[u'size_mismatch']"} 1.0
```

Repair the inconsistent pg using `pg_id` or `primary_osd`:

```
ceph pg repair 5.9
ceph osd repair 0
```

prometheus:

```
# HELP ceph_pg_inconsistent_info PG Inconsistent Info
# TYPE ceph_pg_inconsistent_info untyped
ceph_pg_inconsistent_info{pg_id="",object="",primary_osd="",errors=""} 0.0
```

Signed-off-by: Lan Liu <liulan@umcloud.com>

### CODE REVIEW

**Comment by LenzGr** [comment]
> Again, great idea, prometheus is just not the monitoring system to do this.

@jan--f so would it be better to put this information in log files that could be aggregated and analyzed by an ELK stack (Logstash/Kibana or similar)?

**Comment by Rjerk** [comment]
@jan--f  sounds resonable, thanks. What if we only list a certain number of new times series (for example, 50) to avoid overload problems ?

**Comment by jan--f** [comment]
@Rjerk Sorry I think this is not going to work. The intended use is simply not what Prometheus was designed for. With this exporter we already bend the Prometheus Best Practice quite a bit and I'd like to avoid bending them further.

**Comment by b-ranto** [comment]
The missing `string` type handling is a known deficiency of prometheus. While it is technically possible to pass strings through labels like you do here, you should really use something else if you need to pass strings.

**Pull request closed without merging**
