### PR TITLE
pybind: Fixed ceph tell 'missing required parameter' output

### PR DESCRIPTION
**Pull request by joscollin**
Fixes: http://tracker.ceph.com/issues/22344

Signed-off-by: Jos Collin <jcollin@redhat.com>

### CODE REVIEW

**Comment by joscollin** [comment]
retest this please

**Comment by joscollin** [comment]
retest this please

**Comment by joscollin** [comment]
@liewegas Could you please re-review, as I have pushed in a better fix ?

In my testing, I found that my first fix messes up the other command's output. For instance: `$ ./bin/ceph tell osd.0 pg jospool.0 query`, which is not a `missing required parameter`. The current fix doesn't affect the other cases.

Thanks.

**Comment by tchaikov** [comment]
- http://pulpito.ceph.com/kchai-2017-12-12_02:50:14-rados-wip-kefu-testing-2017-12-11-2343-distro-basic-mira/
- http://pulpito.ceph.com/kchai-2017-12-13_08:50:46-rados-wip-kefu-testing-2017-12-13-1539-distro-basic-mira/

**Comment by joscollin** [comment]
@tchaikov @liewegas Shall we merge this ?

**Comment by tchaikov** [comment]
no, i think i have a better fix: #19547

**Comment by joscollin** [comment]
@tchaikov I'm testing https://github.com/ceph/ceph/pull/19547.

**Comment by joscollin** [comment]
Jenkins retest this please

**Comment by joscollin** [comment]
retest this please

**Pull request closed without merging**
