### PR TITLE
backport #13769: EC async "fast read" patchset for hammer

### PR DESCRIPTION
**Pull request by tsg-**
EC read latency improvement.  Commits backported:

131214dc ec: add support for fast read on PGBackend/ECBackend async read

5eb2a77d mon: add a new pool setting to configure fast read for EC pool

54090f18 mon: add a configuration for default fast read setting

### CODE REVIEW

**Comment by dachary** [comment]
@tsg backports should be against the hammer branch, not the hammer-backports branch. You will find more information about backporting at http://tracker.ceph.com/projects/ceph-releases/wiki/HOWTO_backport_commits

**Comment by tsg-** [comment]
Thanks @dachary!  Sorry newbie error.  Let me resubmit.  :^)

**Comment by dachary** [comment]
@tsg thanks :-)

**Comment by tsg-** [comment]
@dachary I am back.  :-) - resubmitted this pull request as https://github.com/ceph/ceph/pull/6611 with the required commit format etc.  Thanks.

**Pull request closed without merging**
