### PR TITLE
mimic: [test] periodic seg faults within unittest_librbd

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/36238

### CODE REVIEW

**Comment by smithfarm** [comment]
jenkins test docs

**Comment by smithfarm** [comment]
Test failures: 156 - unittest_rbd_mirror (Timeout)

**Comment by smithfarm** [comment]
jenkins re-test this please

**Comment by trociny** [comment]
> Test failures: 156 - unittest_rbd_mirror (Timeout)

Unfortunately I didn't see the jenkins log (is it possible to access it after retest?) but it might be this [1].

[1] http://tracker.ceph.com/issues/36236

**Comment by smithfarm** [comment]
@trociny Ah, sorry - it must be possible to access the log after retest, but I don't have access to the Jenkins GUI. @tchaikov can you help?

**Comment by dillaman** [comment]
@smithfarm https://jenkins.ceph.com/job/ceph-pull-requests/7593/console

> [ RUN      ] TestMockImageMap.AddInstancePingPongImageTest
> /home/jenkins-build/build/workspace/ceph-pull-requests/src/test/rbd_mirror/test_mock_ImageMap.cc:295: Failure
> Value of: it != peer_ack_ctxs->end()
>   Actual: false
> Expected: true

**Comment by dillaman** [comment]
... I'll look into it, but my first hunch is that it's not related to this PR.

**Comment by yuriw** [comment]
[wip-yuri2-testing-2018-10-23-1513-mimic](https://trello.com/c/UXS8kH5Z/450-wip-yuri2-testing-2018-10-23-1513-mimic)

**Pull request merged**
