### PR TITLE
hammer: rgw: S3: set EncodingType in ListBucketResult

### PR DESCRIPTION
**Pull request by robbat2**
http://tracker.ceph.com/issues/15897

### CODE REVIEW

**Comment by robbat2** [comment]
@liewegas this is the backport of PR7712. Please tag bug-fix, rgw, milestone hammer.

In the original commit comments, it was already confirmed working with Hammer per https://github.com/ceph/ceph/commit/180ca7b56ba91a3995c76dac698aa4ee31d9a2ce#commitcomment-16876098.

@Xavion sorry this got dropped.

**Comment by Xavion** [comment]
So, when is this fix actually going to "go live"?  Like, when will DreamObjects behave normally again?  I'm sick to death of having to reupload unchanged files all the time.

**Comment by dachary** [comment]
test this please

**Comment by robbat2** [comment]
@liewegas merge this too?

**Comment by Xavion** [comment]
Guys, I'm well beyond being fed up with waiting for this trivial bug to be fixed.  I cannot understand how something so significant can receive such a low priority.  If it isn't fixed (and implemented in DreamObjects) by next Sunday (June 12), I will be filing a formal complaint.

**Comment by robbat2** [comment]
@Xavion I'm still waiting for this to be merged this for 0.94.8 release, and until that happens, there's not much you can do either.

While I do work on DreamObjects, I don't have the power to merge this into upstream Ceph, and upstream's priority is on fixing things in the Jewel release presently (like multisite).

**Comment by Xavion** [comment]
Well, I think upstream needs to get its priorities straight.  Maybe you can install a rocket up the relevant guy's arse in order to get him moving on this.  Failing that, perhaps DreamHost's complaints department can do so instead.  I guess we shall see, come June 12 :-).

**Pull request merged**
