### PR TITLE
osd: put osdmap in mempool

### PR DESCRIPTION
**Pull request by liewegas**

### CODE REVIEW

**Comment by liewegas** [comment]
retest this please

**Comment by Liuchang0812** [comment]
I know how to put something in  ceph's mempool now. :smiley:

**Comment by liewegas** [comment]
retest this please

**Comment by liewegas** [comment]
http://pulpito.ceph.com/sage-2017-04-25_17:36:45-rados-wip-sage-testing---basic-smithi/

**Pull request merged**
