### PR TITLE
doc: 16.2.4, 15.2.12, 14.2.21 Release Notes

### PR DESCRIPTION
**Pull request by djgalloway**
Signed-off-by: David Galloway <dgallowa@redhat.com>

### CODE REVIEW

**Comment by djgalloway** [comment]
I don't have the bandwidth to write the 3 CVE RST files.

**Review by jdurgin — APPROVED** [review]

**Review by neha-ojha — APPROVED** [review]

**Comment by liewegas** [comment]
jenkins render docs

**Comment by liewegas** [comment]
jenkins render docs

**Comment by liewegas** [comment]
jenkins render docs

**Pull request merged**
