### PR TITLE
mds: adjust cap acquisition throttles

### PR DESCRIPTION
**Pull request by batrick**
For production workloads, these defaults rarely help. Adjust accordingly. For a steady state "find" workload, these new throttles will prevent acquiring more than ~2300 caps/second which is quite manageable with typical recall rates.

    -ln(0.5) / 30 * 100k = 2310

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by vshankar** [comment]
> For production workloads, these defaults rarely help. Adjust accordingly. For a steady state "find" workload, these new throttles will prevent acquiring more than ~2300 caps/second which is quite manageable with typical recall rates.

Could you explain a bit more about why its manageable? From my interpretation, I guess you are talking about

- mds_recall_max_caps
- mds_recall_max_decay_rate

for recall rates, for which the steady state is ~14000 with 128K being the throttle point. So, the client is acquiring caps (via readdir) far slowly than what the MDS would recall with the defaults), which is good in relation with the "cache pressure" warning that shows up at times, right?

**Comment by batrick** [comment]
> > For production workloads, these defaults rarely help. Adjust accordingly. For a steady state "find" workload, these new throttles will prevent acquiring more than ~2300 caps/second which is quite manageable with typical recall rates.
> 
> Could you explain a bit more about why its manageable? From my interpretation, I guess you are talking about
> 
>     * mds_recall_max_caps
> 
>     * mds_recall_max_decay_rate
> 
> 
> for recall rates, for which the steady state is ~14000 with 128K being the throttle point.

Yes, that's accurate.

> So, the client is acquiring caps (via readdir) far slowly than what the MDS would recall with the defaults), which is good in relation with the "cache pressure" warning that shows up at times, right?

Yes.

At this point, I think we need to do be more conservative with the default here so it triggers reliably. Then, if it's obstructive, the operator can relax the defaults gently until things improve, i.e. no slow requests.

**Review by vshankar — APPROVED** [review]

**Comment by batrick** [comment]
jenkins test windows

**Comment by vshankar** [comment]
https://pulpito.ceph.com/?branch=wip-vshankar-testing-20230808.093601

**Review by vshankar — APPROVED** [review]
https://tracker.ceph.com/projects/cephfs/wiki/Main#14-Aug-2023

**Pull request merged**
