### PR TITLE
luminous: qa: misc cache drop fixes

### PR DESCRIPTION
**Pull request by vshankar**
http://tracker.ceph.com/issues/38340
http://tracker.ceph.com/issues/38445

### CODE REVIEW

**Comment by vshankar** [comment]
should be good for review.

**Comment by batrick** [comment]
Great work Venky, thanks!

**Comment by yuriw** [comment]
[wip-yuri4-testing-2019-06-13-1541-luminous](https://trello.com/c/1kU7OZL0/640-wip-yuri4-testing-2019-06-13-1541-luminous)

**Comment by vshankar** [comment]
Reviewed-by: Venky Shankar <vshankar@redhat.com>

**Pull request merged**
