### PR TITLE
quincy: qa/fs/mixed-clients: specify distros for tests

### PR DESCRIPTION
**Pull request by dparmar18**
backport tracker: https://tracker.ceph.com/issues/58604
backport of https://github.com/ceph/ceph/pull/48049
parent tracker: https://tracker.ceph.com/issues/57280

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by yuriw** [comment]
@dparmar18 @vshankar 
This PR has to pass mandatory tests and be reviewed/approved before integration testing

**Review by vshankar — APPROVED** [review]

**Comment by vshankar** [comment]
jenkins retest this please

**Comment by vshankar** [comment]
https://tracker.ceph.com/projects/cephfs/wiki/Quincy#2023-Mar-02

**Comment by batrick** [comment]
@vshankar @dparmar18 https://github.com/ceph/ceph/pull/51029

```
2023-04-11 14:00:37,553.553 INFO:teuthology.suite:Using random seed=1735
2023-04-11 14:00:37,554.554 INFO:teuthology.suite.run:kernel sha1: distro
2023-04-11 14:00:37,830.830 INFO:teuthology.suite.run:ceph sha1: 687b814f6a8c4db74daf97d825bbfa90b5560fa3
2023-04-11 14:00:37,830.830 INFO:teuthology.suite.util:container build centos/8, checking for build_complete
2023-04-11 14:00:38,124.124 INFO:teuthology.suite.run:ceph version: 17.2.6-134.g687b814f
2023-04-11 14:00:38,377.377 INFO:teuthology.suite.run:ceph-ci branch: wip-pdonnell-testing-20230410.205400-quincy 687b814f6a8c4db74daf97d825bbfa90b5560fa3
2023-04-11 14:00:38,383.383 INFO:teuthology.repo_utils:Fetching wip-pdonnell-testing-20230410.205400-quincy from origin
2023-04-11 14:00:38,694.694 INFO:teuthology.repo_utils:Resetting repo at /home/pdonnell/src/git.ceph.com_ceph-c_wip-pdonnell-testing-20230410.205400-quincy to origin/wip-pdonnell-testing-20230410.205400-quincy
2023-04-11 14:00:38,963.963 INFO:teuthology.suite.run:teuthology branch: main 8d156aede5efdae00b53d8d3b8d127082980e7ec
2023-04-11 14:00:38,980.980 INFO:teuthology.suite.build_matrix:Subset=21/128
2023-04-11 14:00:39,069.069 INFO:teuthology.suite.run:Suite fs in /home/pdonnell/src/git.ceph.com_ceph-c_wip-pdonnell-testing-20230410.205400-quincy/qa/suites/fs generated 182 jobs (not yet filtered or merged)
2023-04-11 14:00:39,908.908 INFO:teuthology.suite.util:container build centos/8, checking for build_complete
2023-04-11 14:00:40,201.201 INFO:teuthology.suite.util:container build centos/8, checking for build_complete
2023-04-11 14:00:41,038.038 ERROR:teuthology.suite.run:Packages for os_type 'ubuntu', flavor default and ceph hash '687b814f6a8c4db74daf97d825bbfa90b5560fa3' not found
```

With #51029, the scheduling succeeds.

@vshankar AFAICT, this PR was not part of [1]?

[1] https://trello.com/c/KUfgqSfy/1694-wip-yuri4-testing-2023-02-22-0817-quincy

**Comment by batrick** [comment]
Oh, I see your review was a combo of two sets. This PR is in:

https://trello.com/c/MMn8gArA/1699-wip-yuri10-testing-2023-02-28-0752-quincy

but it looks like no ubuntu jobs were in the subset perhaps, avoiding the problem by sheer luck.

**Comment by dparmar18** [comment]
> > Oh, I see your review was a combo of two sets. This PR is in:
> > https://trello.com/c/MMn8gArA/1699-wip-yuri10-testing-2023-02-28-0752-quincy
> > but it looks like no ubuntu jobs were in the subset perhaps, avoiding the problem by sheer luck.
> 
> Wow, really? And we got super lucky with main branch fs suite runs too then. o_O

What a luck

**Comment by vshankar** [comment]
> > > Oh, I see your review was a combo of two sets. This PR is in:
> > > https://trello.com/c/MMn8gArA/1699-wip-yuri10-testing-2023-02-28-0752-quincy
> > > but it looks like no ubuntu jobs were in the subset perhaps, avoiding the problem by sheer luck.
> > 
> > 
> > Wow, really? And we got super lucky with main branch fs suite runs too then. o_O
> 
> `main` branch does build 22.04: https://shaman.ceph.com/repos/ceph/main/a182bc7eb4560ceb79c5a00c8cab625c7040f234/

Right. So, the PR for main branch said:

```
The OS Type and OS Version for mixed-clients tests is left blank on teuthology and they appear to be trying to
run ubuntu jammy which is causing failures. We should specify what distros the tests should run on.
```

Without this change 22.04 was getting picked up, so the distro was added. So, this change was never supposed to be backported to p/q then.

**Comment by vshankar** [comment]
> > > > Oh, I see your review was a combo of two sets. This PR is in:
> > > > https://trello.com/c/MMn8gArA/1699-wip-yuri10-testing-2023-02-28-0752-quincy
> > > > but it looks like no ubuntu jobs were in the subset perhaps, avoiding the problem by sheer luck.
> > > 
> > > 
> > > Wow, really? And we got super lucky with main branch fs suite runs too then. o_O
> > 
> > 
> > `main` branch does build 22.04: https://shaman.ceph.com/repos/ceph/main/a182bc7eb4560ceb79c5a00c8cab625c7040f234/
> 
> Right. So, the PR for main branch said:
> 
> ```
> The OS Type and OS Version for mixed-clients tests is left blank on teuthology and they appear to be trying to
> run ubuntu jammy which is causing failures. We should specify what distros the tests should run on.
> ```
> 
> Without this change 22.04 was getting picked up, so the distro was added. So, this change was never supposed to be backported to p/q then.

EDIT: Since we don't build 22.04 pkgs for p/q.

**Pull request merged**
