### PR TITLE
hammer: rgw: Don't loop forever when reading data from 0 sized segment.

### PR DESCRIPTION
**Pull request by oritwas**
The 0 sized segment can arise depending on how
the client uploads the object in the first place.
The cpu loop then happens during a swift `GET'.

Signed-off-by: Marcus Watts mwatts@redhat.com
(cherry picked from commit 46c5f9773246522e66bb2cca49345d0b62a16c42)

### CODE REVIEW

**Comment by oritwas** [comment]
http://tracker.ceph.com/issues/17677

**Comment by smithfarm** [comment]
@oritwas Can you rebase please?

**Comment by oritwas** [comment]
@smithfarm , done

**Comment by smithfarm** [comment]
Updated PR description to contain link to backport tracker.

**Comment by smithfarm** [comment]
This PR causes a merge conflict when preparing the hammer integration branch.

**Comment by smithfarm** [comment]
It appears to conflict with 2175b688358455472ac6320bb82ac6bef7133e59 @oritwas could you take a look?

**Comment by smithfarm** [comment]
@oritwas Nevermind, that's simple enough that I can resolve the conflict myself.

**Comment by smithfarm** [comment]
@oritwas @yehudasa This PR was tested by rgw suite as described here: http://tracker.ceph.com/issues/17151#note-11

All tests passed except one that failed with "saw valgrind issues" - see http://pulpito.front.sepia.ceph.com/smithfarm-2016-11-18_10:00:20-rgw-hammer-backports---basic-smithi/558612/

Do you think this PR is OK to merge? (Full disclosure: I have not yet attempted to debug the valgrind failure.)

**Comment by smithfarm** [comment]
DNM until https://github.com/ceph/ceph/pull/11951 is merged (because it causes a trivial merge conflict).

**Comment by smithfarm** [comment]
Note that, due to the trivial merge conflict, this PR has not been included in any of the hammer integration testing runs.

**Comment by smithfarm** [comment]
@oritwas Can you rebase again, please - to get rid of the conflict - and then can you also remove DNM? Thanks.

**Comment by oritwas** [comment]
@smithfarm done

**Comment by smithfarm** [comment]
@yehudasa @oritas This PR just passed an rgw run at http://tracker.ceph.com/issues/17151#note-24

Do you think it can be merged?

**Comment by oritwas** [comment]
lgtm

**Pull request merged**
