### PR TITLE
osd: handle ceph specific config changes for the mclock scheduler

### PR DESCRIPTION
**Pull request by sunnyku**
This patch will basically prevent users from modifying Ceph options that are associated
with the active mclock built-in profile.

The below ceph parameters are set automatically
while enabling the mclock scheduler with a built-in profile.
The user in this case will not be able to modify these
ceph specific config options during runtime.
 
  a. osd_async_recovery_min_cost
  b. osd_recovery_max_active{_hdd,_ssd}
  c. osd_max_backfills
  d. osd_recovery_sleep{_hdd,_ssd,_hybrid}

If the custom profile is enabled for the mclock scheduler,
the user can modify these parameters.

Signed-off-by: Sunny Kumar <sunkumar@redhat.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by sunnyku** [comment]
jenkins retest this please

**Review by sunnyku — COMMENTED** [review]
jenkins retest this please

**Comment by sunnyku** [comment]
Had some issue with my local repository causing make failure.
Closing this PR.

**Comment by jdurgin** [comment]
superseded by #38920

**Pull request closed without merging**
