### PR TITLE
rgw/sysobj: pool_list_objects_init() initializes marker

### PR DESCRIPTION
**Pull request by cbodley**
Fixes: https://tracker.ceph.com/issues/63717

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Comment by cbodley** [comment]
seems to be working based on radosgw-admin testing (the 'user list'  command uses the same admin op that the admin api does):
```
~/ceph/build $ bin/radosgw-admin user list --max-entries 1
{
    "keys": [
        "56789abcdef0123456789abcdef0123456789abcdef0123456789abcdef01234"
    ],
    "truncated": true,
    "count": 1,
    "marker": "4:24c867eb:users.uid::testid.buckets:head"
}
~/ceph/build $ bin/radosgw-admin user list --max-entries 1 --marker 4:24c867eb:users.uid::testid.buckets:head
{
    "keys": [
        "testx$9876543210abcdef0123456789abcdef0123456789abcdef0123456789abcdef"
    ],
    "truncated": true,
    "count": 1,
    "marker": "4:3e9bbbc3:users.uid::test.buckets:head"
}
```

**Comment by cbodley** [comment]
jenkins test api

**Review by adamemerson — APPROVED** [review]

**Comment by cbodley** [comment]
> The following tests FAILED:
	 31 - run-rbd-unit-tests-1.sh (Timeout)

**Comment by cbodley** [comment]
i pushed another commit after i noticed that --max-entries wasn't working as expected when there's a prefix filter. RGWSI_RADOS had this same behavior, so it wasn't a regression from `rgw_list_pool()`

**Comment by cbodley** [comment]
> The slave crashed or was restarted

**Comment by cbodley** [comment]
jenkins test make check

**Comment by cbodley** [comment]
(finally) passed qa in https://pulpito.ceph.com/cbodley-2023-12-12_19:44:34-rgw-wip-cbodley-testing-distro-default-smithi/

**Pull request merged**
