### PR TITLE
cephadm: validate `fsid` command arg

### PR DESCRIPTION
**Pull request by mgfritch**
after #42356

Signed-off-by: Michael Fritch <mfritch@suse.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Review by liewegas — APPROVED** [review]

**Review by adk3798 — APPROVED** [review]

**Comment by adk3798** [comment]
jenkins test make check

**Comment by tchaikov** [comment]
jenkins test make check

**Comment by tchaikov** [comment]
jenkins test make check

**Comment by tchaikov** [comment]
jenkins test make check

**Comment by tchaikov** [comment]
- https://pulpito.ceph.com/kchai-2021-07-29_08:05:42-rados-wip-kefu-testing-2021-07-29-1336-distro-basic-smithi/
- https://pulpito.ceph.com/kchai-2021-07-30_04:58:53-rados-wip-kefu-testing-2021-07-30-0947-distro-basic-smithi/
- https://pulpito.ceph.com/kchai-2021-07-30_10:20:53-rados-wip-kefu-testing-2021-07-30-1358-distro-basic-smithi/

**Pull request merged**
