### PR TITLE
pacific: rgw: Initialize Layout Logs

### PR DESCRIPTION
**Pull request by smithfarm**
backport tracker: https://tracker.ceph.com/issues/48971

---

backport of:

* https://github.com/ceph/ceph/pull/39032
* https://github.com/ceph/ceph/pull/39042

parent tracker: https://tracker.ceph.com/issues/48967

this backport was staged using ceph-backport.sh version 16.0.0.6848
find the latest version at https://github.com/ceph/ceph/blob/master/src/script/ceph-backport.sh

### CODE REVIEW

**Comment by smithfarm** [comment]
```
The following tests FAILED:
	 12 - run-rbd-unit-tests-127.sh (Failed)
	 13 - run-cli-tests (Failed)
	200 - unittest-seastar-messenger (Child aborted)
```

**Comment by smithfarm** [comment]
jenkins test make check

**Review by cbodley — APPROVED** [review]

**Comment by smithfarm** [comment]
```
The following tests FAILED:
	 13 - run-cli-tests (Failed)
	200 - unittest-seastar-messenger (Child aborted)
```

**Comment by smithfarm** [comment]
The run-cli-tests part of "make check" is failing like this:

```
Failed to build cram
Installing collected packages: cram
    Running setup.py install for cram: started
    Running setup.py install for cram: finished with status 'done'
  DEPRECATION: cram was installed using the legacy 'setup.py install' method, because a wheel could not be built for it. pip 21.0 will remove support for this functionality. A possible replacement is to fix the wheel build issue reported above. You can find discussion regarding this at https://github.com/pypa/pip/issues/8368.
Successfully installed cram-0.5.0ceph.2011-01-14
/home/jenkins-build/build/workspace/ceph-pull-requests/src/test/run-cli-tests-maybe-unset-ccache: 20: exec: /home/jenkins-build/build/workspace/ceph-pull-requests/src/test/virtualenv/bin/cram: not found
/home/jenkins-build/build/workspace/ceph-pull-requests/src/test/run-cli-tests-maybe-unset-ccache: 20: exec: /home/jenkins-build/build/workspace/ceph-pull-requests/src/test/virtualenv/bin/cram: not found
/home/jenkins-build/build/workspace/ceph-pull-requests/src/test/run-cli-tests-maybe-unset-ccache: 20: exec: /home/jenkins-build/build/workspace/ceph-pull-requests/src/test/virtualenv/bin/cram: not found
/home/jenkins-build/build/workspace/ceph-pull-requests/src/test/run-cli-tests-maybe-unset-ccache: 20: exec: /home/jenkins-build/build/workspace/ceph-pull-requests/src/test/virtualenv/bin/cram: not found
/home/jenkins-build/build/workspace/ceph-pull-requests/src/test/run-cli-tests-maybe-unset-ccache: 20: exec: /home/jenkins-build/build/workspace/ceph-pull-requests/src/test/virtualenv/bin/cram: not found
/home/jenkins-build/build/workspace/ceph-pull-requests/src/test/run-cli-tests-maybe-unset-ccache: 20: exec: /home/jenkins-build/build/workspace/ceph-pull-requests/src/test/virtualenv/bin/cram: not found
/home/jenkins-build/build/workspace/ceph-pull-requests/src/test/run-cli-tests-maybe-unset-ccache: 20: exec: /home/jenkins-build/build/workspace/ceph-pull-requests/src/test/virtualenv/bin/cram: not found
/home/jenkins-build/build/workspace/ceph-pull-requests/src/test/run-cli-tests-maybe-unset-ccache: 20: exec: /home/jenkins-build/build/workspace/ceph-pull-requests/src/test/virtualenv/bin/cram: not found
Tests that failed:  ceph-authtool ceph-conf ceph-kvstore-tool crushtool monmaptool osdmaptool radosgw-admin rbd
```

Which would seem to be a problem that would affect all pacific PRs, but I see other PRs targeting pacific are getting merged.

**Comment by smithfarm** [comment]
jenkins test make check

**Comment by smithfarm** [comment]
```
The following tests FAILED:
	 11 - run-rbd-unit-tests-109.sh (Failed)
	 13 - run-cli-tests (Failed)
```

**Comment by smithfarm** [comment]
Ah! Needs https://github.com/ceph/ceph/pull/39042 to be backported, maybe?

**Comment by idryomov** [comment]
jenkins test make check

**Comment by smithfarm** [comment]
```
CMake Error at /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find zbd (missing: ZBD_LIBRARIES ZBD_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  cmake/modules/Findzbd.cmake:17 (find_package_handle_standard_args)
  CMakeLists.txt:211 (find_package)


-- Configuring incomplete, errors occurred!
```

The make check failure seems unrelated to this PR. 

@tchaikov @djgalloway Have you seen it before?

**Comment by idryomov** [comment]
This is coming from https://github.com/ceph/ceph-build/pull/1664.  Looks like we need to pull https://github.com/ceph/ceph/pull/39051 and https://github.com/ceph/ceph/pull/39077 into pacific too.  I think I'll open a separate "fix `make check` on pacific" PR with cram and zbd fixes, since bringing in cram fixes in an rgw PR seems wrong.

**Comment by smithfarm** [comment]
@idryomov Sounds good to me! This PR can't be merged until pacific make check is fixed, anyway.

**Comment by idryomov** [comment]
Opened https://github.com/ceph/ceph/pull/39088.

**Comment by idryomov** [comment]
Looks like https://github.com/ceph/ceph-build/pull/1664 broke master too, see my comment in #39088.

**Comment by tchaikov** [comment]
my apologies. created #39091

**Comment by idryomov** [comment]
jenkins test make check

**Comment by cbodley** [comment]
jenkins test make check

**Pull request merged**
