### PR TITLE
doc/dev/index.rst: fix headings

### PR DESCRIPTION
**Pull request by smithfarm**
This commit fixes the headings so they render properly on http://ceph.com

Signed-off-by: Nathan Cutler <ncutler@suse.com>

### CODE REVIEW

**Comment by smithfarm** [comment]
Let's not merge this until I figure out how to integrate the CSS into the Dockerized test environment.

**Comment by dachary** [comment]
@smithfarm ok. Looks good to me.

<pre>
Reviewed-by: Loic Dachary &lt;ldachary@redhat.com>
</pre>

**Comment by smithfarm** [comment]
@dachary Added some more stuff, all tested. The CSS issue in the testing environment is now fixed.

**Comment by smithfarm** [comment]
@dachary Unified commit messages. Fixed another link.

**Pull request merged**
