### PR TITLE
rgwlc: fix segfault during lc

### PR DESCRIPTION
**Pull request by mkogan1**
commonly caused by abort from very large tcmalloc memory allocation like
`radosgw[318347]: tcmalloc: large alloc 94059315200000 bytes == (nil) @  0x7fadf8b06650 0x7fadf8b272f4 0x558bdc2f09ca 0x558bdc2f2612 0x558bdc2f8e28 0x558bdc2fc480 0x558bdc2fd52d 0x558bdc2fd756 0x7fadec6a117a 0x7fadebaa1dc3
`

Fixes: https://tracker.ceph.com/issues/54363

Signed-off-by: Mark Kogan <mkogan@redhat.com>

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by mkogan1** [comment]
@mattbenjamin @cbodley which upstream versions backports are required?

**Review by mattbenjamin — APPROVED** [review]
this looks clearly correct

**Comment by mattbenjamin** [comment]
@mkogan1 rhcs-4.3 and rhcs-5.1, for upstream, we should include for Q, P, O, N (if those are all still active)

**Review by cbodley — APPROVED** [review]

**Comment by mkogan1** [comment]
jenkins test make check

**Comment by mkogan1** [comment]
jenkins test make check

**Comment by cbodley** [comment]
passed qa in https://pulpito.ceph.com/cbodley-2022-03-17_18:05:42-rgw-wip-cbodley-testing-distro-default-smithi/

**Pull request merged**
