### PR TITLE
cmake changes

### PR DESCRIPTION
**Pull request by tchaikov**

### CODE REVIEW

**Comment by tchaikov** [comment]
retest this please.

**Comment by dillaman** [comment]
librbd changes lgtm

**Comment by tchaikov** [comment]
changlog

- fixed the link failures of some rbd related tests.

**Comment by tchaikov** [comment]
retest this please.

**Comment by tchaikov** [comment]
gitbuilders are happy. per discussion with @alimaredia over irc, the PR looks good to him. so merging.

**Pull request merged**
