### PR TITLE
qa/cephadm: specify using container host distros for workunits

### PR DESCRIPTION
**Pull request by adk3798**
Right now, the OS Type and OS Version for these workunits
tests is left blank on pulpito and they appear to be trying to
run ubuntu jammy currently which is causing failures. We should
specify what distros the tests should run on then very explicitly
tell it to start trying new distros when we can get the tests to
pass.

Signed-off-by: Adam King <adking@redhat.com>

Not entirely sure the patch as I have it is correct. Will need to just try it and make sure cephadm/workunits tests
are assigned a proper distro and and also the test-iscsi-pids-limit test in particular is still only tested on centos

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by adk3798** [comment]
example of what I mean by the os type/version being left blank from https://pulpito.ceph.com/adking-2022-08-18_01:28:05-orch:cephadm-wip-adk-testing-2022-08-17-1914-distro-default-smithi/

image

you can see the last test was explicitly given rhel 8.6, but the other ones, which are all workunits, have blank fields. They appear to be trying to run on ubuntu jammy given
```
2022-08-18T08:17:11.283 DEBUG:teuthology.orchestra.run.smithi153:> cat /etc/os-release
2022-08-18T08:17:11.287 INFO:teuthology.orchestra.run.smithi153.stdout:PRETTY_NAME="Ubuntu 22.04 LTS"
2022-08-18T08:17:11.287 INFO:teuthology.orchestra.run.smithi153.stdout:NAME="Ubuntu"
2022-08-18T08:17:11.288 INFO:teuthology.orchestra.run.smithi153.stdout:VERSION_ID="22.04"
2022-08-18T08:17:11.288 INFO:teuthology.orchestra.run.smithi153.stdout:VERSION="22.04 LTS (Jammy Jellyfish)"
2022-08-18T08:17:11.288 INFO:teuthology.orchestra.run.smithi153.stdout:VERSION_CODENAME=jammy
2022-08-18T08:17:11.288 INFO:teuthology.orchestra.run.smithi153.stdout:ID=ubuntu
2022-08-18T08:17:11.289 INFO:teuthology.orchestra.run.smithi153.stdout:ID_LIKE=debian
2022-08-18T08:17:11.289 INFO:teuthology.orchestra.run.smithi153.stdout:HOME_URL="https://www.ubuntu.com/"
2022-08-18T08:17:11.289 INFO:teuthology.orchestra.run.smithi153.stdout:SUPPORT_URL="https://help.ubuntu.com/"
2022-08-18T08:17:11.289 INFO:teuthology.orchestra.run.smithi153.stdout:BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
2022-08-18T08:17:11.289 INFO:teuthology.orchestra.run.smithi153.stdout:PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
2022-08-18T08:17:11.290 INFO:teuthology.orchestra.run.smithi153.stdout:UBUNTU_CODENAME=jammy
```

**Comment by adk3798** [comment]
jenkins test api

**Review by ljflores — APPROVED** [review]

**Comment by adk3798** [comment]
jenkins test api

**Comment by ljflores** [comment]
jenkins test api

**Comment by adk3798** [comment]
jenkins test api

**Comment by adk3798** [comment]
without this change https://pulpito.ceph.com/adking-2022-08-23_20:19:52-orch:cephadm-wip-adk-main-testing-2022-08-23-1319-distro-default-smithi/

and with it https://pulpito.ceph.com/adking-2022-08-24_13:29:10-orch:cephadm-wip-adk-main-testing-2022-08-24-0725-distro-default-smithi/

lots of dead jobs due to an unrelated thing causing rhel jobs to fail, but overall the cephadm/workunits tests are much better with this change. Additionally, that has revealed we seem to have 2 other failures in the suite now, not caused by this I think

https://tracker.ceph.com/issues/57287
https://tracker.ceph.com/issues/57290

**Comment by ljflores** [comment]
@adk3798 will this PR also help with https://tracker.ceph.com/issues/57303?

**Comment by adk3798** [comment]
> @adk3798 will this PR also help with https://tracker.ceph.com/issues/57303?

I would think so. I see what looks like the same failure in https://pulpito.ceph.com/adking-2022-08-23_20:19:52-orch:cephadm-wip-adk-main-testing-2022-08-23-1319-distro-default-smithi/6988142 which was my run without this change and don't see anything similar in runs with this change. I'm going to mark the tracker as resolved by this PR, but we can open again if it pops up in builds that include this patch

**Comment by ljflores** [comment]
Thx! I'll reopen it if I see it again. It was happening very consistently in the rados suite, so we'll know.

**Pull request merged**
