### PR TITLE
os/tests: fix garbageCollection test case from store_test suite.

### PR DESCRIPTION
**Pull request by ifed01**
While running the test case using SSD as block device one could face
a failure caused by unexpectidly small blob size limit - compression
resulted in two blocks rather than single one which violated was test case
constraints.
Here is the output for failing test case:
```
[ RUN      ] ObjectStore/StoreTestSpecificAUSize.garbageCollection/2
Creating collection meta
Creating object #-1:68309cac:::Object 1:head#
/home/if/nvme/ceph.3/src/test/objectstore/store_test.cc:6720: Failure
      Expected: statfs.data_compressed_allocated
      Which is: 0
To be equal to: 0x10000
      Which is: 65536
==> rm -r bluestore.test_temp_dir
[  FAILED  ] ObjectStore/StoreTestSpecificAUSize.garbageCollection/2, where GetParam() = "bluestore" (1173 ms)
[----------] 1 test from ObjectStore/StoreTestSpecificAUSize (1173 ms total)

```
Signed-off-by: Igor Fedotov <ifedotov@suse.com>

- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by tchaikov** [comment]
- http://pulpito.ceph.com/kchai-2018-08-28_04:25:25-rados-wip-kefu-testing-2018-08-28-0811-distro-basic-mira/
- http://pulpito.ceph.com/kchai-2018-08-29_07:26:03-rados-wip-kefu-testing-2018-08-28-0811-distro-basic-mira/
- http://pulpito.ceph.com/kchai-2018-08-29_11:04:40-rados-wip-kefu-testing-2018-08-28-0811-distro-basic-mira/
- http://pulpito.ceph.com/kchai-2018-08-29_13:22:00-rados-wip-kefu-testing-2018-08-28-0811-distro-basic-mira/
- http://pulpito.ceph.com/kchai-2018-08-29_15:16:19-rados-wip-kefu-testing-2018-08-28-0811-distro-basic-mira/

**Comment by tchaikov** [comment]
@ifed01 what the test failure the default bluestore_max_blob_size could trigger? could you post a link? or point me to a backtrace / error message ?

**Comment by ifed01** [comment]
@tchaikov: updated the PR description with the info you asked for

**Comment by ifed01** [comment]
@tchaikov - ping

**Comment by tchaikov** [comment]
@ifed01 i am sorry for the latency. this PR fell off through the cracks in my desk.

as i am not familiar with bluestore and its compression policy, i am noting down my understanding regarding to the connection between `bluestore_max_blob_size` and a zero `statfs.data_compressed_allocated`, which is supposed to be `0x10000`.

so, if we are using a device for testing `StoreTestSpecificAUSize.garbageCollection`, the `max_blob_size` is determined by the default `bluestore_max_blob_size_ssd`, which is in turn 64KiB instead of 512KiB. and the `alloc_hints` is not set for `StoreTestSpecificAUSize.garbageCollection`, `wctx->target_blob_size` should be `bluestore_compression_min_blob_size`, in this case, 256KiB, which is also the size of the `data` in this test.

but we want to clamp the `target_blob_size` in between `min_alloc_size * 2` (`bluestore_min_alloc_size_ssd`, 16KiB by default) and `max_blob_size` at the end of `BlueStore::_choose_write_options()`, so `wctx->target_blob_size` is changed to `64KiB`. this practically disable the compression. as the minimum blob size for compression is, as set at the beginning of the test, 256KiB.

by increasing `bluestore_max_blob_size` to 512KiB, the `wtx->target_blob_size` won't be decreased down to `64KiB` anymore. it will be 256KiB. and we will always compress the `data` chunk.

**Pull request merged**
