### PR TITLE
luminous: radosgw-admin sync status improvements

### PR DESCRIPTION
**Pull request by cbodley**
backports for http://tracker.ceph.com/issues/24060

### CODE REVIEW

**Comment by cbodley** [comment]
also backported commits from https://github.com/ceph/ceph/pull/19878

**Comment by yuriw** [comment]
[wip-yuri2-testing-2018-05-11-1543-luminous](https://trello.com/c/oM7u01zs/313-wip-yuri2-testing-2018-05-11-1543-luminous)

**Comment by yuriw** [comment]
@cbodley I see failed build:

std::_Identity<std::basic_string<char> >; _Compare = std::less<std::basic_string<char> >; _Alloc = std::allocator<std::basic_string<char> >]'
/usr/include/c++/4.8/bits/stl_set.h:518:4:   required from 'void std::set<_Key, _Compare, _Alloc>::insert(_InputIterator, _InputIterator) [with _InputIterator = std::move_iterator<std::_Rb_tree_const_iterator<std::basic_string<char> > >; _Key = std::basic_string<char>; _Compare = std::less<std::basic_string<char> >; _Alloc = std::allocator<std::basic_string<char> >]'
/build/ceph-12.2.5-131-gb511a16/src/rgw/rgw_data_sync.cc:2043:77:   required from here
/usr/include/c++/4.8/bits/stl_iterator.h:963:37: error: invalid initialization of reference of type 'std::move_iterator<std::_Rb_tree_const_iterator<std::basic_string<char> > >::reference {aka std::basic_string<char>&&}' from expression of type 'std::remove_reference<const std::basic_string<char>&>::type {aka const std::basic_string<char>}'
       { return std::move(*_M_current); }

caused by this ?
https://shaman.ceph.com/builds/ceph/wip-yuri2-testing-2018-05-11-1543-luminous/

**Comment by cbodley** [comment]
@yuriw i pushed an updated branch, and documented that confict as `rgw_data_sync.cc (make_move_iterator fails to build with gcc<5)`

**Pull request merged**
