### PR TITLE
luminous: PGLog.cc: saw valgrind issues while accessing complete_to->version

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/26910

### CODE REVIEW

**Comment by xiexingguo** [comment]
This should include https://github.com/ceph/ceph/pull/23546 too

**Comment by smithfarm** [comment]
@xiexingguo Thanks; done.

**Comment by smithfarm** [comment]
@xiexingguo And https://github.com/ceph/ceph/pull/23894 as well?

**Comment by smithfarm** [comment]
Closing in favor of https://github.com/ceph/ceph/pull/23211

**Pull request closed without merging**
