### PR TITLE
rgw: civetweb: use poll instead of select while waiting on sockets

### PR DESCRIPTION
**Pull request by theanalyst**
Currently when trying to push data > bufsize, civetweb will wait on the output
socket using `select` which uses `FD_SET` on the fd, which can easily exceed
1024 which is the default `FD_SETSIZE` for most systems. Since it is very likely
that most RGW installations will exceed this limit, use `poll` instead.

Fixes: http://tracker.ceph.com/issues/24364
Signed-off-by: Abhishek Lekshmanan <abhishek@suse.com>

- [x] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by theanalyst** [comment]
rgw suite: http://pulpito.ceph.com/abhi-2018-09-11_13:13:02-rgw-wip-civetweb-poll-distro-basic-smithi/

**Comment by theanalyst** [comment]
updated to reflect latest ceph-master sha1 in civetweb

**Comment by theanalyst** [comment]
jenkins test this please

**Comment by theanalyst** [comment]
@yehudasa  @mattbenjamin can this be merged, it has gone through qa (and also already merged for mimic )

**Comment by cbodley** [comment]
ping @mattbenjamin @yehudasa, needs override to merge

**Comment by theanalyst** [comment]
bump, can this merged (since we already merged in mimic)

**Comment by theanalyst** [comment]
@mattbenjamin @yehudasa, can this be merged (already merged in mimic)

**Pull request merged**
