### PR TITLE
luminous: core: osd: Fix for compatibility of encode/decode of osd_stat_t

### PR DESCRIPTION
**Pull request by dzafman**
Fix for ceph/ceph#30230

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`

</details>

### CODE REVIEW

**Comment by smithfarm** [comment]
Since this is a follow-on fix for a PR that is already in 12.2.13, my assumption is that this one also needs to go in for 12.2.13.

**Comment by dzafman** [comment]
@smithfarm Yes, we need this change or to revert the network ping time feature for 12.2.13

**Comment by dzafman** [comment]
Standalone tests passed:
ALL 44 TESTS PASSED

**Comment by yuriw** [comment]
[wip-yuri5-testing-2019-11-04-2055-luminous](https://trello.com/c/YohtmFrD/744-wip-yuri5-testing-2019-11-04-2055-luminous)

**Pull request merged**
