### PR TITLE
pacific: cephadm/ceph-volume: do not use lvm binary in containers

### PR DESCRIPTION
**Pull request by guits**
backport tracker: https://tracker.ceph.com/issues/53280

---

backport of https://github.com/ceph/ceph/pull/43536
parent tracker: https://tracker.ceph.com/issues/52926

this backport was staged using ceph-backport.sh version 16.0.0.6848
find the latest version at https://github.com/ceph/ceph/blob/master/src/script/ceph-backport.sh

### CODE REVIEW

**Comment by sebastian-philipp** [comment]
This needs to go through the rados/cephadm suite.

**Comment by guits** [comment]
jenkins test ceph-volume tox

**Comment by guits** [comment]
jenkins test windows

**Comment by guits** [comment]
jenkins test windows

**Comment by guits** [comment]
jenkins test ceph dashboard

**Comment by guits** [comment]
jenkins test ceph dashboard cephadm

**Comment by guits** [comment]
jenkins test dashboard cephadm

**Comment by leseb** [comment]
jenkins test windows

**Comment by guits** [comment]
jenkins test ceph-volume tox

**Comment by guits** [comment]
jenkins test ceph-volume all

**Comment by guits** [comment]
jenkins test dashboard cephadm

**Comment by guits** [comment]
jenkins test windows

**Comment by guits** [comment]
jenkins test ceph-volume tox

**Comment by guits** [comment]
jenkins test ceph-volume all

**Comment by guits** [comment]
http://pulpito.front.sepia.ceph.com:80/gabrioux-2021-11-18_15:57:43-rados:cephadm-wip-guits-testing-2021-11-18-1333-pacific-distro-default-smithi/

**Comment by guits** [comment]
jenkins test ceph-volume batch centos8-bluestore-mixed_type_dmcrypt_explicit

**Comment by guits** [comment]
jenkins test dashboard cephadm

**Comment by guits** [comment]
jenkins test dashboard cephadm

**Comment by guits** [comment]
jenkins test ceph-volume all

**Comment by guits** [comment]
jenkins test ceph-volume tox

**Comment by guits** [comment]
jenkins test ceph-volume all

**Comment by guits** [comment]
jenkins test ceph-volume tox

**Comment by guits** [comment]
jenkins test make check

**Comment by guits** [comment]
jenkins test make check

**Comment by guits** [comment]
jenkins test make check

**Comment by guits** [comment]
jenkins test ceph-volume tox

**Comment by guits** [comment]
jenkins test ceph-volume all

**Review by leseb — APPROVED** [review]

**Comment by sebastian-philipp** [comment]
I think we caused https://pulpito.ceph.com/swagner-2021-12-15_12:52:12-rados:cephadm-wip-swagner2-testing-2021-12-15-1027-pacific-distro-default-smithi/ here.

**Pull request merged**
