### PR TITLE
jewel: include/fs_types: fix unsigned integer overflow

### PR DESCRIPTION
**Pull request by ukernel**
http://tracker.ceph.com/issues/22494

### CODE REVIEW

**Comment by smithfarm** [comment]
@tchaikov GCC bug is still getting triggered on jewel make check :-(

**Comment by joscollin** [comment]
retest this please

**Comment by joscollin** [comment]
retest this please

**Comment by tchaikov** [comment]
retest this please

**Comment by smithfarm** [comment]
This PR is included in the CephFS integration run: http://tracker.ceph.com/issues/21742#note-12

The run looks like it will pass (still waiting on one job).

Unfortunately, we are having trouble getting the PR past "make check". . .

**Comment by smithfarm** [comment]
CephFS integration run passed at http://tracker.ceph.com/issues/21742#note-12

**Comment by smithfarm** [comment]
retest this please

**Comment by smithfarm** [comment]
retest this please

**Comment by smithfarm** [comment]
Not sure how relevant this is, but this PR passed a rados integration run at http://tracker.ceph.com/issues/21742#note-14 with two bugs reproducing:

    http://tracker.ceph.com/issues/23006
    http://tracker.ceph.com/issues/23007

(Neither appears to be related to this PR, and the PR will be merged as soon as I can get it past "make check"!)

**Comment by joscollin** [comment]
> Not sure how relevant this is

@smithfarm This is a customer reported issue: Case#01996425, BZ#1527548.

**Comment by smithfarm** [comment]
jenkins re-test this please

**Pull request merged**
