### PR TITLE
small probability sigabrt when setting rados_osd_op_timeout

### PR DESCRIPTION
**Pull request by dachary**
http://tracker.ceph.com/issues/13340

### CODE REVIEW

**Comment by dachary** [comment]
@liewegas does this backport look good to merge ? It passed a run of the hammer rados suite ( see http://tracker.ceph.com/issues/13356#note-11 and  for details ).

**Comment by liewegas** [comment]
needs to be backported with 0635b1358354b19ae44105576f730381f3b5b963

otherwise, :+1:

**Comment by dachary** [comment]
@liewegas good catch ! I failed to notice the issue was fixed by **two** pull requests, https://github.com/ceph/ceph/pull/6078 with 0635b13.

**Comment by dachary** [comment]
It passed a run of the hammer rados suite ( see http://tracker.ceph.com/issues/13356#note-28 for details ).

**Pull request merged**
