### PR TITLE
mon: remove mds code "mds set_state" command since...

### PR DESCRIPTION
**Pull request by rishabh-d-dave**
it's deprecated now.

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [x] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by lxbsz** [comment]
@rishabh-d-dave BTW, where says it's deprecated ? I didn't find it. Could you add this in the commit comments ?

If we are removing this, should we doc it ? And also we should fix the doc like `doc/man/8/ceph.rst`.

**Comment by vshankar** [comment]
> @rishabh-d-dave BTW, where says it's deprecated ? I didn't find it. Could you add this in the commit comments ?
> 
> If we are removing this, should we doc it ? And also we should fix the doc like `doc/man/8/ceph.rst`.

I spoke to @rishabh-d-dave yesterday regarding this. This interface is out in the field and we should probably check in ceph list to see if anyone (script) relies on this. Moreover, IMO, we should include in the docs that this interface is going to be removed in the future (and provide an alternate interface/cli to achieve what this does).

**Comment by vshankar** [comment]
As far as the word "deprecated" is concerned, @rishabh-d-dave mentioned that it came from me. If I did, I was wrong, though I don't recall mentioning it.

**Comment by lxbsz** [comment]
> > If we are removing this, should we doc it ? And also we should fix the doc like `doc/man/8/ceph.rst`.
> 
> The Ceph man page has been modified accordingly. Let me know if anything more needs to be changed in Ceph man page in your opinion.

Okay, I just missed that.

**Comment by lxbsz** [comment]
`qa/workunits/cephtool/test.sh` mentions the `set_state`, just a comments.

**Comment by dparmar18** [comment]
are you sure this is deprecated? this code was added in https://github.com/ceph/ceph/commit/f113fa80a9b1ee994663f3175a633083de1f5718 and there looks no mention of `mds set_state` getting deprecated. Or I missed something?

**Comment by vshankar** [comment]
@rishabh-d-dave IMO, the way this should be cleaned up would be to mark the interface as to be deprecated in future releases, provide an alternate way to achieve the same result as this interface. You could also consider sending out a PSA in ceph-users list.

**Comment by vshankar** [comment]
@rishabh-d-dave https://github.com/ceph/ceph/pull/50638#issuecomment-1511376128 PTAL

**Comment by vshankar** [comment]
@rishabh-d-dave Closing this due to inactivity.

**Pull request closed without merging**
