### PR TITLE
[DNM] hammer: kclient: intermittent log warnings client.XXXX isn't responding to mclientcaps(revoke)

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/13932

### CODE REVIEW

**Comment by smithfarm** [comment]
test this please

**Comment by smithfarm** [comment]
```
mds/Locker.cc: In member function 'void Locker::handle_client_caps(MClientCaps*)':
mds/Locker.cc:2471:2: error: 'session' was not declared in this scope
  session->have_completed_flush(m->get_client_tid())) {
  ^
```

**Comment by gregsfortytwo** [comment]
looks like this would also require 0ca7a49ba8294a9e9406fcda58221fd8c89a7491. That changes SessionMap encoding so you'd need to see if that's a safe change or not. (If the existing hammer already has the encoding version that patch moves from, it should be fine.)

**Comment by smithfarm** [comment]
@gregsfortytwo I tried, but 0ca7a49 is non-trivial to cherry-pick. I rebased the PR, but that's all I'm capable of ATM. What do you suggest we do next?

**Comment by gregsfortytwo** [comment]
I'll try and take a look at some point, but since we have (stable) Jewel out the backport to Hammer isn't as interesting as it used to be for FS bits.

**Comment by gregsfortytwo** [comment]
I don't think I'm ever going to get to this unless we start seeing issues we decide are important, so closing...if somebody else wants to take a look, feel free to reopen!

**Pull request closed without merging**
