### PR TITLE
support rados bench randseq option

### PR DESCRIPTION
**Pull request by tdeneau**
This pull request adds a new read option to rados bench called randseq.  Basically, the files are read in a random sequence, but like the seq option, each file  will only be read once (whereas in the original rand option, files are just randomly read until the timer expires).

### CODE REVIEW

**Comment by liewegas** [comment]
Can you please rebase this on master?

**Comment by tdeneau** [comment]
This new pull request is rebased on master as of Feb 2.
I should add that it works with the new logic in rados bench which allows op_size and obj_size to be different but that new logic seems to have some problems:

1. The function aio_read in src/tools/rados/rados.cc was ignoring the offset parameter.  This meant that if a write bench used different op_size and obj_size, a subsequent read benchmark would always fail.  I fixed this  as part of this pull request even though it is not strictly part of the randseq change.

2. The transition to separate op_size and obj_size seems incomplete in that the write benchmark tries to write as metadata the count of objects (rather than ops), and the seq_read_bench really uses the incoming num_objects as if it were a count of ops.  So the read benchmark cannot read all of the ops that the write benchmark wrote.  Note also that the final object written by the write benchmark can be shorter than the other objects but passing the number of objects, there is no way to indicate this.  I did not make any changes in this logic as part of this pull request, but I may submit a separate pull request to fix this logic (I think the metadata should just store the number of ops written, not the number of objs, along with op size and obj size.)

**Comment by liewegas** [comment]
@tdeneau thanks for identifying the op/object issues.

Can you please add Signed-off-by: lines to these commits (see SubmittingPatches file to see what this means), and rebase on top of master (instead of merging with master) so that the merge commits aren't present?  Also, please prefix commits with the tool or subsystem, e.g. "rados: add randseq bench option\n\nSigned-off-by: ...".  Thanks!

**Comment by tdeneau** [comment]
Sage  --

OK, will give rebase a try.   Would you prefer a rebased pull request that only has the randseq logic or one that incorporates fixes for the op_size, obj_size issues?

-- Tom

**Comment by liewegas** [comment]
all together is fine!

**Comment by tdeneau** [comment]
I submitted a new pull request at https://github.com/ceph/ceph/pull/7487

**Pull request closed without merging**
