### PR TITLE
added boost timegm impl for cross platform support

### PR DESCRIPTION
**Pull request by rohanmars**
Signed-off-by: Rohan Mars <code@rohanmars.com>

### CODE REVIEW

**Comment by rohanmars** [comment]
this timegm implementation is available in boost 1.55, ubuntu 14.04 is currently using 1.54.

**Comment by liewegas** [comment]
Can we put the timegm.h stuff in a .cc file instead so that it does not pollute the namespace (and isn't all inline)?

**Comment by tchaikov** [comment]
@rohanmars i am sure why we need to use the `timegm()` implementation in boost. i agree that this function does not confirm to any standard. but it is available in real world. by "real world", i mean gnu/linux + BSD. as we always have `timegm(3)` on these platforms, do we?

**Comment by rohanmars** [comment]
@liewegas will move to cc

@tchaikov, timegm doesn't exist on AIX or Solaris unfortunately.

**Comment by liewegas** [comment]
1. timegm.h needs to go in the NOINST_HEADERS list in common/Makefile.am

2. can you squash the first 3 commits into one?

Thanks!

**Comment by rohanmars** [comment]
@ liewegas done as requested.

**Comment by rohanmars** [comment]
@liewegas, done as requested.

**Comment by liewegas** [comment]
Looks good.  Thanks!

**Comment by liewegas** [comment]
on osd startup,

 2015-08-22 09:58:31.813666 7f5403f21900  0 _load_class could not open class /usr/lib64/rados-classes/libcls_refcount.so (dlopen failed): /usr/lib64/rados-classes/libcls_refcount.so: undefined symbol: _Z15internal_timegmPK2tm

**Comment by liewegas** [comment]
Hrm, perhaps it should be inline after all!

**Comment by rohanmars** [comment]
@liewegas,  it looks like the libcls_refcount.so doesn't link against librados.so (the included file utime.h is a header implementation, but my change wants to pull in impl in librados.so). I'll inline, otherwise there will need to be a library reference.

**Pull request merged**
