### PR TITLE
quincy: monitoring: ceph mixin backports

### PR DESCRIPTION
**Pull request by MrFreezeex**
Backports of https://github.com/ceph/ceph/pull/47284, https://github.com/ceph/ceph/pull/47334, https://github.com/ceph/ceph/pull/47633, https://github.com/ceph/ceph/pull/47669, https://github.com/ceph/ceph/pull/47675, https://github.com/ceph/ceph/pull/47707

Only one pr got a tracker: https://tracker.ceph.com/issues/56948

### CODE REVIEW

**Comment by MrFreezeex** [comment]
jenkins test make check

**Review by aaSharma14 — APPROVED** [review]

**Comment by aaSharma14** [comment]
jenkins test make check

**Comment by nizamial09** [comment]
I triggered [shaman builds](https://shaman.ceph.com/builds/ceph/wip-nia-testing-2022-09-02-1039-quincy/) for this PR. We don't need a full teuthology, if shaman passes we can go ahead and merge this.

**Comment by nizamial09** [comment]
shaman passed apart from one issue and it looks unrelated. https://shaman.ceph.com/builds/ceph/wip-nia-testing-2022-09-02-1039-quincy/

**Review by nizamial09 — APPROVED** [review]

**Pull request merged**
