### PR TITLE
reef: pybind/mgr: reopen database handle on blocklist

### PR DESCRIPTION
**Pull request by batrick**
backport tracker: https://tracker.ceph.com/issues/62022

---

backport of https://github.com/ceph/ceph/pull/50291
parent tracker: https://tracker.ceph.com/issues/55606

this backport was staged using ceph-backport.sh version 16.0.0.6848
find the latest version at https://github.com/ceph/ceph/blob/main/src/script/ceph-backport.sh

### CODE REVIEW

**Comment by batrick** [comment]
jenkins test make check

**Comment by batrick** [comment]
jenkins test make check

**Review by lxbsz — APPROVED** [review]
Checked 19 failure and 2 dead jobs, none of them is related to these PRs: https://pulpito.ceph.com/yuriw-2023-10-16_14:43:00-fs-wip-yuri4-testing-2023-10-11-0735-reef-distro-default-smithi

**Comment by batrick** [comment]
> Possible related failure: https://tracker.ceph.com/issues/63433 @batrick FYI

https://tracker.ceph.com/issues/63433#note-2

**Pull request merged**
