### PR TITLE
mgr/cephadm:Enable cephadm device scan to use libstoragemgmt

### PR DESCRIPTION
**Pull request by pcuzner**
Using libstoragemgmt (LSM) in ceph-volume was disabled by default,
(nov 2020) which meant cephadm's inventory never had a way to
request the LSM data. This patch adds a module option called
'device_enhanced_scan' (bool), that if set will append the
--with-lsm parameter to the ceph-volume inventory call.

Signed-off-by: Paul Cuzner <pcuzner@redhat.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by sebastian-philipp** [comment]
#38149

**Review by tserong — COMMENTED** [review]
Looks reasonable to me. This means sites that _don't_ have the crusty old hardware mentioned in #38149 have a way of getting extra metadata from LSM

**Comment by dmick** [comment]
Seems okayish to me with caveats, as I said to Paul in private email; it seems to me that we ought to, at a minimum:

1) be very very careful about how we document this, since it can wedge an entire server immediately if things go wrong, and perhaps
2) even supply a small test program (a little python snippet is plenty; I may even have put it in the original bug) to allow people to test an offline server, not running ceph, or at least not involving it, to find out if they are going to have issues.

I had also suggested looking for a way to use sg directly (or more likely through libsgutils2.so.2), but I can't find any healthy Python bindings, or even documentation (other than the header files).  The only advantage is trial-by-fire; sg has been through a lot of buggy hardware, and with SCSI that's a lot of hardware.

I know it may seem overcautious, but the consequences are large, and the affected hardware is really unknown.  We've seen one instance but that definitely doesn't mean there aren't others (and I've got past experience at Sun with a lot of others).

**Comment by pcuzner** [comment]
@dmick the test could even be cephadm itself - i.e. cephadm ceph-volume inventory --with-lsm --format=json

**Comment by dmick** [comment]
Yeah, probably so

**Comment by sebastian-philipp** [comment]
https://pulpito.ceph.com/swagner-2021-02-22_13:53:31-rados:cephadm-wip-swagner3-testing-2021-02-22-1135-distro-basic-smithi/

**Comment by tasleson** [comment]
@pcuzner @dmick @tbzatek
> I had also suggested looking for a way to use sg directly (or more likely through libsgutils2.so.2), but I can't find any healthy 
Python bindings, or even documentation (other than the header files). The only advantage is trial-by-fire; sg has been through a lot of buggy hardware, and with SCSI that's a lot of hardware.

If you want the benefit of trial-by-fire with regards to sg utils I believe you need to leverage the sg command line utilities.  For example, looking at the header files for issuing an inquiry command `sg_ll_inquiry` the caller needs to specify the return buffer size.  If you look at the sg_inq utility source code there is a good comment on the approach one should take when issuing an inquiry, e.g. initial inquiry should be limited to 36 bytes.  Thus the acquired knowledge of safely talking to devices appears lost if one utilizes the sg library calls.

**Comment by dmick** [comment]
@tasleson good point.  Perhaps opt-in with libstoragemgmt is our safest option at this point.

**Comment by pcuzner** [comment]
@sebastian-philipp where should this be documented? I was thinking cephadm/osd.rst ?

**Comment by sebastian-philipp** [comment]
> @sebastian-philipp where should this be documented? I was thinking cephadm/osd.rst ?

yeah, maybe somewhere around https://docs.ceph.com/en/latest/cephadm/osd/#list-devices ?

**Comment by pcuzner** [comment]
@sebastian-philipp @dmick docs added to cover the benefit and potential issues that turning libstoragemgmt introduces.

**Review by dmick — APPROVED** [review]

**Pull request merged**
