### PR TITLE
rgw: incorporate the Transfer-Encoding fix for CivetWeb.

### PR DESCRIPTION
**Pull request by rzarzynski**
This commit updates the version of CivetWeb used for RadosGW to get the fix for handling clients that send `Content-Length` together with `Transfer-Encoding`. The current handling differs from S3 and thus affects AWSv4.

DEPENDS ON: https://github.com/ceph/civetweb/pull/22.

Fixes: http://tracker.ceph.com/issues/21015
Signed-off-by: Radoslaw Zarzynski <rzarzyns@redhat.com>

### CODE REVIEW

**Comment by ZVampirEM77** [comment]
jenkins retest this please

**Comment by theanalyst** [comment]
This needs to be modified to update the now merged https://github.com/ceph/civetweb/pull/22

**Comment by rzarzynski** [comment]
@theanalyst: just updated.

**Comment by yuriw** [comment]
[wip-yuri4-testing-2017-11-17-1645](https://trello.com/c/covJSIzf/204-wip-yuri4-testing-2017-11-17-1645)

**Comment by yuriw** [comment]
ready for merge

**Comment by yuriw** [comment]
test this please

**Pull request merged**
