### PR TITLE
test/librbd: handle rbd_move_to_trash_on_remove case

### PR DESCRIPTION
**Pull request by trociny**
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by trociny** [comment]
@dillaman Some questions:
-  I have quick fixed v1 images removal to ignore "rbd_move_to_trash_on_remove" by just checking the return status of trash move. It looks more cleaner though to check the image version before calling trash move, but then it would need to open it just for this only purpose. What do you think?
- Do we want python tests to honor "rbd_move_to_trash_on_remove" too?
- Do we want to add "rbd_move_to_trash_on_remove" test cases to teuthology (similarly to "rbd_skip_partial_discard")? It is easy but will significantly increase the number of generated jobs for the rbd suite.
- When moving a mirroring image to the trash, shouldn't we disable mirroring first? Right now, if a primary image is moved to the trash the slave image remains in the rbd directory on its site.

**Comment by dillaman** [comment]
> * I have quick fixed v1 images removal to ignore "rbd_move_to_trash_on_remove" by just checking the return status of trash move. It looks more cleaner though to check the image version before calling trash move, but then it would need to open it just for this only purpose. What do you think?

Perhaps just ```stat``` the v2 header first if ```rbd_move_to_trash_on_remove``` is enabled. If the ```stat``` passes, it's a v2 image so you can proceed to move to the trash.

> * Do we want python tests to honor "rbd_move_to_trash_on_remove" too?

I don't think we need to create a Python-specific test for this since it doesn't impact the Python API. I think the C/C++ API tests really only need to test it once (set it to true and verify v1 images are removed and v2 images get moved to the trash) and then just assume it's disabled for the remainder of tests (i.e. no need to special-case all the tests for either-or-mode).

> * Do we want to add "rbd_move_to_trash_on_remove" test cases to teuthology (similarly to "rbd_skip_partial_discard")? It is easy but will significantly increase the number of generated jobs for the rbd suite.

I don't think that's necessary. The ```rbd_skip_partial_discard``` test was there because it's on the IO path and we need to cover corner-cases for potential data corruption.

> * When moving a mirroring image to the trash, shouldn't we disable mirroring first? Right now, if a primary image is moved to the trash the slave image remains in the rbd directory on its site.

Yeah, that makes sense to me -- but on trash restore it would have to re-enable mirroring (if in pool mode and if the image had journaling enabled).

**Comment by trociny** [comment]
> Perhaps just `stat` the v2 header first if `rbd_move_to_trash_on_remove` is enabled. If the `stat` passes, it's a v2 image so you can proceed to move to the trash.

Ah and I forgot I had had yet another related question. Right now `rbd_move_to_trash_on_remove` can be set on global or per pool level. But it looks to me it makes sense on the image level too. Wouldn't we want to change this?

**Comment by dillaman** [comment]
> Wouldn't we want to change this?

Yeah, would be good if you could add a new ```librbd::api::Config::apply_image_overrides(librados::IoCtx&, const std::string &image_id, ConfigProxy*)``` method to load per-image config options w/o the need to open the image.

**Comment by trociny** [comment]
> I don't think we need to create a Python-specific test for this since it doesn't impact the Python API. I think the C/C++ API tests really only need to test it once (set it to true and verify v1 images are removed and v2 images get moved to the trash) and then just assume it's disabled for the remainder of tests (i.e. no need to special-case all the tests for either-or-mode).

So, basically it means that the status of [1] will be "Won't fix"? It is ok to me though I also see a value in having  the tests working (and continuously running) when the option is set. The spotted here issues are an example of this usefulness.

[1] https://tracker.ceph.com/issues/37539

**Comment by dillaman** [comment]
> So, basically it means that the status of [1] will be "Won't fix"? It is ok to me though I also see a value in having the tests working (and continuously running) when the option is set. The spotted here issues are an example of this usefulness.

We run into issues similar to that when you disable the RBD cache, or increase debug logging, etc. We can always just override the configuration on test startup to avoid issues like this.

**Comment by trociny** [comment]
By "spotted issues" I meant real issue, not just due to wrong test expectations. Like the issue with mirroring not being disabled on move to trash, or error returned when removing v1 format image, or returning EINVAL when removing a migrating image, when EBUSY looks more correct.

And we run api tests with rbd cache both enabled and disabled :)

**Comment by dillaman** [comment]
> By "spotted issues" I meant real issue, not just due to wrong test expectations. Like the issue with mirroring not being disabled on move to trash, or error returned when removing v1 format image, or returning EINVAL when removing a migrating image, when EBUSY looks more correct.

Sure, but once you know of the issue, you can write a specific unit test case to test for it and not have to obfuscate other tests with lots of "if (this config setting is X and that config setting is Y)" style logic. That's my real concern.

> And we run api tests with rbd cache both enabled and disabled :)

We do indeed -- but the mock tests cases complicate things w/ their expectations.

**Comment by MahatiC** [comment]
@trociny @dillaman Not sure if this is being abandoned, but upcoming changes like this https://github.com/ceph/ceph/pull/25438 could use these tests - I noticed these test failures on master while trying to make this change

**Comment by trociny** [comment]
I created another PR (#27136) for the first commit.

**Pull request closed without merging**
