### PR TITLE
jewel: osd: scrub_to specifies clone ver, but transaction include head write ver

### PR DESCRIPTION
**Pull request by dzafman**
http://tracker.ceph.com/issues/20780

### CODE REVIEW

**Comment by smithfarm** [comment]
@dzafman I gather this bug is already fixed in master?

**Comment by dzafman** [comment]
@smithfarm No, we are waiting for the Jewel version to be tested.  Then we'll merge master version #16404 before this one.

**Comment by smithfarm** [comment]
@yuriw Can you test this jewel PR? I'm working on kraken atm.

**Comment by smithfarm** [comment]
master PR has been merged.

**Comment by smithfarm** [comment]
@jdurgin This passed a rados run at http://tracker.ceph.com/issues/20613#note-40 with some failures, all of which I tried to reproduce. The only one that is reliably reproducible is http://tracker.ceph.com/issues/20981

Please review.

**Pull request merged**
