### PR TITLE
cmake, script: run "make check" with fmtlib v9

### PR DESCRIPTION
**Pull request by tchaikov**
## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by tchaikov** [comment]
jenkins test api

**Comment by tchaikov** [comment]
jenkins test api

**Comment by tchaikov** [comment]
jenkins test api

**Review by cbodley — APPROVED** [review]
this looks okay, but maybe we should just require v9 in cmake since we have the submodule as a backup. then we wouldn't need `#if FMT_VERSION >= 90000` checks in the code

**Comment by tchaikov** [comment]
> this looks okay, but maybe we should just require v9 in cmake since we have the submodule as a backup. then we wouldn't need `#if FMT_VERSION >= 90000` checks in the code

hi @cbodley i also pondered on this option. but this is a bigger decision than to be compatible with fmtlib v9. as i noticed that @yehudasa asked if we can avoid the need for the package upgrade at https://github.com/ceph/ceph/pull/48705#issuecomment-1353381177 .

**Comment by batrick** [comment]
Hi Kefu, I'm getting a baffling error when running `do_cmake.sh` now:

```
pdonnell@vossi04 ~/ceph$ rm -rf build && ./do_cmake.sh -DWITH_BABELTRACE=OFF -DWITH_MANPAGE=OFF -DWITH_RBD=OFF -DWITH_KRBD=OFF -DWITH_RADOSGW=OFF -DWITH_LTTNG=OFF -DWITH_RDMA=OFF -DWITH_SEASTAR=OFF -DWITH_CEPH_DEBUG_MUTEX=ON
...
CMake Error at src/CMakeLists.txt:325 (find_package):
  find_package called with invalid argument "OFF"


-- Could not find fmt, will build it
...
-- Configuring incomplete, errors occurred!
See also "/home/pdonnell/ceph/build/CMakeFiles/CMakeOutput.log".
See also "/home/pdonnell/ceph/build/CMakeFiles/CMakeError.log".
+ exit 1
```

I don't see how it can be "OFF" on that line in `src/CMakeLists.txt`. In any case, if I set it to 7.0.0 then it completes as expected.

**Comment by tchaikov** [comment]
@batrick sorry for the regression. should be fixed by #49489

**Pull request merged**
