### PR TITLE
mimic: mgr/dashboard: Fix dashboard compile error

### PR DESCRIPTION
**Pull request by tspmelo**
New version of lodash was generating a compile error.
With this change npm will install an older version of lodash.

Fixes: https://tracker.ceph.com/issues/38590
Fixes: https://tracker.ceph.com/issues/38602

Signed-off-by: Tiago Melo <tmelo@suse.com>

### CODE REVIEW

**Comment by callithea** [comment]
FYI @yuriw @smithfarm @theanalyst

**Comment by tspmelo** [comment]
jenkins retest this please

**Comment by smithfarm** [comment]
@yuriw @theanalyst I can't merge this, but once it does get merged it should fix the mimic build/make check failure.

**Comment by yuriw** [comment]
Thank you all !

**Pull request merged**
