### PR TITLE
mgr/dashboard: capacity-card set interval and display bytes used

### PR DESCRIPTION
**Pull request by Pegonzal**
Now data is beinged updated every five seconds.
Changed the use of the Angular async pipe as it was causing problems when refreshing the data with the card and chart, as shown in the video:

[screen-capture (2).webm](https://user-images.githubusercontent.com/106810838/204514648-75dbf24b-63ff-46c1-a37a-3a13b4275c62.webm)

tracker: https://tracker.ceph.com/issues/57862
Reasoning on the styling:
doc: https://docs.google.com/document/d/1t4H5ErQGVQ1IKzZxHnnsqOB4apWUBsxouptgPbrl6pQ/edit

Signed-off-by: Pedro Gonzalez Gomez <pegonzal@redhat.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [x] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by pereman2** [comment]
jenkins test make check

**Review by aaSharma14 — APPROVED** [review]

**Comment by pereman2** [comment]
jenkins test dashboard

**Comment by Pegonzal** [comment]
jenkins test dashboard

**Comment by Pegonzal** [comment]
jenkins test make check

**Comment by Pegonzal** [comment]
jenkins test dashboard

**Pull request merged**
