### PR TITLE
rbd: add missing switch arguments for recognition by get_command_spec()

### PR DESCRIPTION
**Pull request by idryomov**
Currently this

  $ rbd --all children img

doesn't work, while this

  $ rbd children --all img

or this

  $ rbd children img --all

does.  The issue is that -a/--all isn't on the list of known switch
arguments.  The "rbd children" example may seem contrived but for more
complicated commands such as "rbd device map" mixing switches and
positional arguments occurs naturally:

  $ rbd device --device-type nbd --options try-netlink --show-cookie map img

Fixes: https://tracker.ceph.com/issues/53935
Signed-off-by: Ilya Dryomov <idryomov@gmail.com>

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [x] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by idryomov** [comment]
This addresses this failure:

http://qa-proxy.ceph.com/teuthology/dis-2022-01-19_08:39:11-rbd-wip-dis-testing-distro-default-smithi/6626548/teuthology.log

**Comment by idryomov** [comment]
For the record, I don't really see a need for a list of known switches.  I think `get_command_spec()` could for example assume that no option value starts with `-`/`--` or similar.

**Comment by idryomov** [comment]
jenkins test make check

**Comment by idryomov** [comment]
jenkins test make check

**Comment by idryomov** [comment]
jenkins test make check

**Comment by idryomov** [comment]
jenkins test make check

**Comment by idryomov** [comment]
jenkins test make check

**Comment by idryomov** [comment]
make check is blocked on https://github.com/ceph/ceph/pull/44706.

**Review by trociny — APPROVED** [review]
LGTM

It would be nice if we found a way to automatize checking for this. Otherwise in future I suppose we will hit this again for some new option.

**Comment by idryomov** [comment]
I identified the missing ones by grepping for `bool_switch()`, so it wouldn't be very hard to cross-check or even generate at compile time.  But honestly, I just don't see why the list of switches is needed at all.  Do you see a problem with assuming that no option value starts with `-`/`--`?

**Comment by idryomov** [comment]
jenkins test make check

**Comment by trociny** [comment]
> Do you see a problem with assuming that no option value starts with -/--? A standalone - could be special cased, as it may be used to signify stdin in some places.

No. Nothing that could break comes to my mind.

**Comment by idryomov** [comment]
I'm going to merge this as is because it's obviously correct and addresses a quincy test failure.

> > Do you see a problem with assuming that no option value starts with -/--? A standalone - could be special cased, as it may be used to signify stdin in some places.
> 
> No. Nothing that could break comes to my mind.

https://tracker.ceph.com/issues/53980

**Comment by idryomov** [comment]
https://pulpito.ceph.com/dis-2022-01-19_18:51:51-rbd-wip-dis-testing-distro-default-smithi/

**Pull request merged**
