### PR TITLE
mon: adding exsting pool as tier with --force-nonempty clobbers removed_snaps

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/12312

### CODE REVIEW

**Comment by smithfarm** [comment]
Merge conflict

**Comment by dachary** [comment]
@smithfarm could you cherry-pick -x bef09e0cdb274cb1c87335a2af9ee532d14a4596 into this pull request as well ? I'll test it manually.

**Comment by smithfarm** [comment]
@dachary done

**Comment by dachary** [comment]
@smithfarm ? 48e0adf is intended ?

**Comment by smithfarm** [comment]
@dachary Oops, sorry - fixed now.

**Comment by dachary** [comment]
<pre>
CEPH_PORT=7000 MON=1 OSD=3 ./vstart.sh -X -d -n -l mon osd
PATH=:$PATH bash -x ../qa/workunits/rados/test.sh 
</pre>
passes.

**Pull request merged**
