### PR TITLE
rgw: post object should account usage bytes

### PR DESCRIPTION
**Pull request by fangyuxiangGL**

### CODE REVIEW

**Comment by fangyuxiangGL** [comment]
Hi @cbodley 

Generally, web browser should use POST to upload file, but we didn't account the bytes usage in this instance.

**Comment by cbodley** [comment]
@fangyuxiangGL this looks reasonable to me.

@mdw-at-linuxbox @rzarzynski were looking into similar issues with usage accounting - could you guys take a look please?

**Comment by rzarzynski** [comment]
Guys, what do you think about [a change that simplifies and enables accounting globally](https://github.com/ceph/ceph/pull/16904)? I believe we can have many buried bugs like this one.

**Comment by cbodley** [comment]
@rzarzynski thanks, i'd also prefer a general solution as long as it has appropriate test coverage

**Pull request closed without merging**
