### PR TITLE
test: add librados-based startup/shutdown racer test

### PR DESCRIPTION
**Pull request by jtlayton**
We have a testcase for libcephfs that spawns a bunch of threads that then create separate ceph mounts and immediately tear them down. Recently, we've started seeing some failures that don't seem to be cephfs specific (see https://tracker.ceph.com/issues/42026).

This PR just adds a librados-based equivalent test that also seems to exhibit the same problem.
When run under valgrind, you'll see out-of-bounds accesses and complaints about bogus file descriptors, mostly down in the EventCenter code.

### CODE REVIEW

**Comment by jtlayton** [comment]
We probably should not merge this until the race is fixed, so setting DNM for now.

**Comment by batrick** [comment]
cc @liewegas @jdurgin @neha-ojha

**Comment by batrick** [comment]
@jtlayton please note the tracker ticket in the commit message, something like:

`Test-for: http...`

**Comment by jtlayton** [comment]
Done

**Comment by jtlayton** [comment]
Patrick suggested we could merge this ahead of the fix for the races, so removing DNM tag.

**Comment by jtlayton** [comment]
Retest this please

**Comment by batrick** [comment]
http://pulpito.ceph.com/pdonnell-2019-09-27_00:41:34-rados:basic-wip-pdonnell-testing-20190926.135019-distro-basic-smithi/

**Comment by batrick** [comment]
````
2019-09-27T01:06:34.220 INFO:tasks.workunit.client.0.smithi144.stdout:                 api_misc: [ RUN      ] LibRadosMisc.ShutdownRace
2019-09-27T01:06:34.220 INFO:tasks.workunit.client.0.smithi144.stdout:                 api_misc: [       OK ] LibRadosMisc.ShutdownRace (27405 ms)
````

Hmmm, might be this doesn't show up with async v1.

**Comment by batrick** [comment]
http://pulpito.ceph.com/?branch=wip-pdonnell-testing-20190926.135019

**Comment by jdurgin** [comment]
if it's async v2, perhaps @rjfd could look at the underlying issue

**Comment by jtlayton** [comment]
Toss in patch that fixes `-DWITH_TSAN=ON` builds.

**Comment by jtlayton** [comment]
@rzarzynski : @liewegas said you might be interested in this. See the ASAN output here, in particular:

https://tracker.ceph.com/issues/42026#note-5

I'm looking at the make_unique calls in ceph::crypto::onwire::rxtx_t::create_handler_pair and wondering whether those need to be refcounted or something...

**Comment by rzarzynski** [comment]
>  I'm looking at the make_unique calls in ceph::crypto::onwire::rxtx_t::create_handler_pair and wondering whether those need to be refcounted or something...

@jtlayton: the lifetime of crypto handlers coming from `ceph::crypto::onwire::rxtx_t::create_handler_pair()` is managed entirely by `ProtocolV2`. I think it does it wrongly. TX handler is freed in `reset_recv_state()` before discarding the out queue:

```cpp
void ProtocolV2::stop() {
  // ...
  reset_recv_state();
  discard_out_queue();
  // ...
}
```

**Comment by batrick** [comment]
````
2019-10-01T03:19:21.026 INFO:tasks.workunit.client.0.smithi139.stdout:                 api_misc: [ RUN      ] LibRadosMisc.ShutdownRace
2019-10-01T03:19:21.026 INFO:tasks.workunit.client.0.smithi139.stdout:                 api_misc: *** Caught signal (Segmentation fault) **
2019-10-01T03:19:21.026 INFO:tasks.workunit.client.0.smithi139.stdout:                 api_misc:  in thread 7f31c2d55700 thread_name:msgr-worker-1
2019-10-01T03:19:21.026 INFO:tasks.workunit.client.0.smithi139.stdout:                 api_misc:  ceph version 15.0.0-5472-g66b6f06 (66b6f06f5d8f8e5ff6108c37453bbf01c5f42dcf) octopus (dev)
2019-10-01T03:19:21.027 INFO:tasks.workunit.client.0.smithi139.stdout:                 api_misc:  1: (()+0xf5d0) [0x7f34586215d0]
2019-10-01T03:19:21.027 INFO:tasks.workunit.client.0.smithi139.stdout:                 api_misc:  2: (ProtocolV2::write_message(Message*, bool)+0x639) [0x7f344f6e6719]
2019-10-01T03:19:21.027 INFO:tasks.workunit.client.0.smithi139.stdout:                 api_misc:  3: (ProtocolV2::write_event()+0x17b) [0x7f344f6fcc0b]
2019-10-01T03:19:21.027 INFO:tasks.workunit.client.0.smithi139.stdout:                 api_misc:  4: (AsyncConnection::handle_write()+0x40) [0x7f344f6b8fd0]
2019-10-01T03:19:21.027 INFO:tasks.workunit.client.0.smithi139.stdout:                 api_misc:  5: (EventCenter::process_events(unsigned int, std::chrono::duration<unsigned long, std::ratio<1l, 1000000000l> >*)+0x1427) [0x7f344f709af7]
2019-10-01T03:19:21.027 INFO:tasks.workunit.client.0.smithi139.stdout:                 api_misc:  6: (()+0x54cd07) [0x7f344f710d07]
2019-10-01T03:19:21.027 INFO:tasks.workunit.client.0.smithi139.stdout:                 api_misc:  7: (()+0x816baf) [0x7f344f9dabaf]
2019-10-01T03:19:21.028 INFO:tasks.workunit.client.0.smithi139.stdout:                 api_misc:  8: (()+0x7dd5) [0x7f3458619dd5]
2019-10-01T03:19:21.028 INFO:tasks.workunit.client.0.smithi139.stdout:                 api_misc:  9: (clone()+0x6d) [0x7f344d3ba02d]
2019-10-01T03:19:21.028 INFO:tasks.workunit.client.0.smithi139.stdout:                 api_misc: 2019-10-01T03:19:21.022+0000 7f31c2d55700 -1 *** Caught signal (Segmentation fault) **
2019-10-01T03:19:21.028 INFO:tasks.workunit.client.0.smithi139.stdout:                 api_misc:  in thread 7f31c2d55700 thread_name:msgr-worker-1
2019-10-01T03:19:21.028 INFO:tasks.workunit.client.0.smithi139.stdout:                 api_misc:
2019-10-01T03:19:21.028 INFO:tasks.workunit.client.0.smithi139.stdout:                 api_misc:  ceph version 15.0.0-5472-g66b6f06 (66b6f06f5d8f8e5ff6108c37453bbf01c5f42dcf) octopus (dev)
2019-10-01T03:19:21.028 INFO:tasks.workunit.client.0.smithi139.stdout:                 api_misc:  1: (()+0xf5d0) [0x7f34586215d0]
2019-10-01T03:19:21.029 INFO:tasks.workunit.client.0.smithi139.stdout:                 api_misc:  2: (ProtocolV2::write_message(Message*, bool)+0x639) [0x7f344f6e6719]
2019-10-01T03:19:21.032 INFO:tasks.workunit.client.0.smithi139.stdout:                 api_misc:  3: (ProtocolV2::write_event()+0x17b) [0x7f344f6fcc0b]
2019-10-01T03:19:21.035 INFO:tasks.workunit.client.0.smithi139.stdout:                 api_misc:  4: (AsyncConnection::handle_write()+0x40) [0x7f344f6b8fd0]
2019-10-01T03:19:21.035 INFO:tasks.workunit.client.0.smithi139.stdout:                 api_misc:  5: (EventCenter::process_events(unsigned int, std::chrono::duration<unsigned long, std::ratio<1l, 1000000000l> >*)+0x1427) [0x7f344f709af7]
2019-10-01T03:19:21.035 INFO:tasks.workunit.client.0.smithi139.stdout:                 api_misc:  6: (()+0x54cd07) [0x7f344f710d07]
2019-10-01T03:19:21.036 INFO:tasks.workunit.client.0.smithi139.stdout:                 api_misc:  7: (()+0x816baf) [0x7f344f9dabaf]
2019-10-01T03:19:21.036 INFO:tasks.workunit.client.0.smithi139.stdout:                 api_misc:  8: (()+0x7dd5) [0x7f3458619dd5]
2019-10-01T03:19:21.036 INFO:tasks.workunit.client.0.smithi139.stdout:                 api_misc:  9: (clone()+0x6d) [0x7f344d3ba02d]
2019-10-01T03:19:21.036 INFO:tasks.workunit.client.0.smithi139.stdout:                 api_misc:  NOTE: a copy of the executable, or `objdump -rdS <executable>` is needed to interpret this.
````
From: http://pulpito.ceph.com/pdonnell-2019-10-01_02:49:04-rados:basic-wip-pdonnell-testing-20190926.135019-distro-basic-smithi/4348936/

See also:

http://pulpito.ceph.com/pdonnell-2019-10-01_02:49:04-rados:basic-wip-pdonnell-testing-20190926.135019-distro-basic-smithi/


Going to merge; test works as advertised.

**Comment by batrick** [comment]
For posterity: yemporarily reverted by #31092

**Pull request merged**
