### PR TITLE
jewel: several backports

### PR DESCRIPTION
**Pull request by liewegas**
http://tracker.ceph.com/issues/15677
http://tracker.ceph.com/issues/15662

### CODE REVIEW

**Comment by liewegas** [comment]
please test this

**Comment by smithfarm** [comment]
you could remove the OSDMonitor commit which was merged via #9006

**Comment by dachary** [comment]
test this please

**Comment by liewegas** [comment]
repushed

**Comment by dachary** [comment]
test this please

**Comment by dachary** [comment]
test this please

**Pull request merged**
