### PR TITLE
tests: use python3 compatible print

### PR DESCRIPTION
**Pull request by kshtsk**
master tracker: https://tracker.ceph.com/issues/42210

### CODE REVIEW

**Comment by kshtsk** [comment]
Corresponding ticket https://tracker.ceph.com/issues/42210

**Comment by tchaikov** [comment]
@kshtsk next time, could you please create PRs from your own repo?

**Comment by kshtsk** [comment]
> @kshtsk next time, could you please create PRs from your own repo?

Oh... sorry, it was my oversight, I can create a replacement for this PR from my own repo.

**Comment by kshtsk** [comment]
Closing this PR in favor of #30758

**Pull request closed without merging**
