### PR TITLE
quincy: qa: Add tests to validate synced images on rbd-mirror

### PR DESCRIPTION
**Pull request by ajarr**
backport tracker: https://tracker.ceph.com/issues/64555

---

backport of https://github.com/ceph/ceph/pull/54802 and https://github.com/ceph/ceph/pull/56077
parent tracker: https://tracker.ceph.com/issues/61617

this backport was staged using ceph-backport.sh version 16.0.0.6848
find the latest version at https://github.com/ceph/ceph/blob/main/src/script/ceph-backport.sh

### CODE REVIEW

**Review by idryomov — APPROVED** [review]

**Review by pereman2 — APPROVED** [review]
https://tracker.ceph.com/projects/rados/wiki/QUINCY#httpstrellocomceHj274bp1967-wip-yuri3-testing-2024-02-28-0755-quincy rados approved

**Comment by yuriw** [comment]
jenkins test make check

**Comment by yuriw** [comment]
@ajarr pls merge when all checks passed
ref: https://trello.com/c/eHj274bp

**Comment by idryomov** [comment]
@yuriw Could you please link a RBD suite run where this PR was included?

**Comment by ajarr** [comment]
@idryomov , can you please take a look?

Once Ilya approves this PR, @yuriw can you please include the latest version of this PR in your testing instead? I had to include a fix that got merged into main earlier today. Thanks!

**Review by idryomov — CHANGES_REQUESTED** [review]
> Conflicts:
	qa/workunits/rbd/rbd_mirror_journal.sh
        -  Commit https://github.com/ajarr/ceph/commit/3fd8a03887354a0c5a11d1eaae386b09242c14a9 not backported
           "qa/workunits/rbd: merge journal and snapshot test scripts"

@ajarr The resolution turns out to be incomplete.  This commit also introduced `wait_for_replaying_status_in_pool_dir()` which is used in `compare_mirror_images.sh`.  Need to replace that with a call to `wait_for_status_in_pool_dir()` and spell out the status.

**Comment by ajarr** [comment]
> > Conflicts:
> > qa/workunits/rbd/rbd_mirror_journal.sh
> > -  Commit [ajarr@3fd8a03](https://github.com/ajarr/ceph/commit/3fd8a03887354a0c5a11d1eaae386b09242c14a9) not backported
> > "qa/workunits/rbd: merge journal and snapshot test scripts"
> 
> @ajarr The resolution turns out to be incomplete. This commit also introduced `wait_for_replaying_status_in_pool_dir()` which is used in `compare_mirror_images.sh`. Need to replace that with a call to `wait_for_status_in_pool_dir()` and spell out the status.

Oops! Fixed now

**Review by idryomov — APPROVED** [review]

**Comment by idryomov** [comment]
jenkins test make check

**Comment by idryomov** [comment]
jenkins test make check

**Pull request merged**
