### PR TITLE
qa/suites/rgw/tempest: valgrind on centos only

### PR DESCRIPTION
**Pull request by liewegas**
Signed-off-by: Sage Weil <sage@redhat.com>

### CODE REVIEW

**Comment by yuriw** [comment]
@liewegas do we need to force this on centos ?

**Comment by cbodley** [comment]
our other suites force centos for valgrind testing, but i don't think i've ever seen tempest suite failures related to valgrind

**Comment by liewegas** [comment]
the valgrind leak checks only works on centos, although i forget the 
details.  it might have been a trusty+xenial issue that is better in 
bionic, but regardless we've limited the valgrind stuff to centos for a 
year+ now

**Comment by liewegas** [comment]
nope, i didn't see failures.. i was just auditing the valgrind runs and noticed this one wasn't centos.

**Comment by neha-ojha** [comment]
We had seen some rados suite failures due to this, listed here https://tracker.ceph.com/issues/24975

**Pull request merged**
