### PR TITLE
jewel: osd: replica read can trigger cache promotion

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/22403

### CODE REVIEW

**Comment by smithfarm** [comment]
retest this please (FAIL: test/osd/osd-scrub-repair.sh)

**Comment by smithfarm** [comment]
@jdurgin This PR was included in a rados run at http://tracker.ceph.com/issues/21742#note-25

Initially there were several failures similar to http://tracker.ceph.com/issues/22063 and http://tracker.ceph.com/issues/22064

After three re-runs these were narrowed down to what seems like a pretty reproducible assert in the radosbench task of a test in "rados/upgrade". I opened a new bug for that, due to the newly increased reproducibility: http://tracker.ceph.com/issues/22598

Since the failing test includes both snaps-many-objects.yaml and test_cache-pool-snaps.yaml I'm musing whether the issue might be related to this PR.

**Comment by jdurgin** [comment]
@smithfarm this pr might make failures like http://tracker.ceph.com/issues/22063 and http://tracker.ceph.com/issues/22064 more likely to appear, but these aren't fixable in jewel.

**Comment by smithfarm** [comment]
@jdurgin Sorry there's a typo in my comment. The correct URL of the bug I opened is http://tracker.ceph.com/issues/23598

But I guess it's just a case of the increased frequency of http://tracker.ceph.com/issues/22063 and http://tracker.ceph.com/issues/22064

Anyway, the rate of this type of failure has increased substantially, so I thought it worth mentioning.

**Pull request merged**
