### PR TITLE
objectstore/store_test: fix lack of flush prior to collection_empty()…

### PR DESCRIPTION
**Pull request by ifed01**
… call

Signed-off-by: Igor Fedotov <ifedotov@suse.com>

### CODE REVIEW

**Comment by tchaikov** [comment]
http://tracker.ceph.com/issues/22409

**Comment by liewegas** [comment]
http://pulpito.ceph.com/sage-2018-01-08_20:16:48-rados-wip-sage3-testing-2018-01-08-1100-distro-basic-smithi/

**Comment by smithfarm** [comment]
@ifed01 The test code this is fixing appears to be in luminous as well. Shall we backport to get the benefit of the test fix there as well?

**Comment by smithfarm** [comment]
To trigger the backport, we would need to set the Backport field to "luminous" in https://tracker.ceph.com/issues/22409

**Comment by liewegas** [comment]
done

**Pull request merged**
