### PR TITLE
os/RocksDBStore: use effective Get API instead of iterator api

### PR DESCRIPTION
**Pull request by yuyuyu101**
Signed-off-by: Haomai Wang <haomai@xsky.com>

### CODE REVIEW

**Comment by liewegas** [comment]
YES!

**Comment by jjhuo** [comment]
Merged with below PR, thanks.
https://github.com/ceph/ceph/pull/9215

**Comment by jjhuo** [comment]
@yuyuyu101 Haomai, instead of merging your leveldb commit with my PR, could you please cherry-pick my rocksdb commit(last one in my PR)? in order to benchmark my block/row cache changes, it's better to have those two commits first, then it'll be fair to my baseline.

**Comment by markhpc** [comment]
Linking Haomai's benchmark for posterity:

http://www.spinics.net/lists/ceph-devel/msg30551.html

**Comment by liewegas** [comment]
using #9215

**Comment by yuyuyu101** [comment]
I update multiget api too. It doesn't make sense to use iterator api because it doesn't have any relation between keys and current impl call multi Seeks.

**Comment by liewegas** [comment]
This doesn't compile:

http://gitbuilder.sepia.ceph.com/gitbuilder-ceph-deb-trusty-amd64-basic/log.cgi?log=f9688e18b4d0025862f3a92dfdf03b2c226ef3af

**Comment by yuyuyu101** [comment]
yes, I'm waiting for #9471

**Comment by yuyuyu101** [comment]
@liewegas @markhpc  
I cherry-pick your commits from #9471 again. I hope we can backport this PR to jewel since it's clear/simple and help for lots of performance(especially for rgw). Then since mark'pr qa test is pending, and in order to ease for backporting, I reconstruct this pr.

@liewegas if free plz add to your testing candidate!

**Comment by yuriw** [comment]
@liewegas tested by http://pulpito.ceph.com/yuriw-2016-07-15_16:58:50-rados-wip-yuri-testing2_2016_7_15-distro-basic-smithi/ and merged

**Pull request merged**
