### PR TITLE
osd: scrub_to specifies clone ver, but transaction include head write…

### PR DESCRIPTION
**Pull request by dzafman**
… ver

Fixes: http://tracker.ceph.com/issues/20041

Signed-off-by: David Zafman <dzafman@redhat.com>

### CODE REVIEW

**Comment by dzafman** [comment]
Waiting for  testing of this based on Jewel cluster from original reporter of tracker. 

5 fails: dzafman-2017-07-18_21:53:08-rados-wip-zafman-testing-distro-basic-smithi
1418366 Error ENOENT: osd.3 does not exist.  create it before updating the crush map
1418387 Segmentation violation in cephx_verify_authorizer()
1418434 status 124: 'sudo adjust-ulimits ceph-coverage /home/ubuntu/cephtest/archive/coverage timeout 120 ceph --cluster ceph quorum_status'
1418448 Error compiling test crush map; probably need newer crushtool
1418521 src/osd/OSD.cc: 4701: FAILED assert(curmap) in handle_osd_ping()

**Comment by dzafman** [comment]
@jdurgin Before merging should we wait for Stefan to test the Jewel version on his cluster?

**Comment by jdurgin** [comment]
Yeah, let's see how it goes on Stefan's cluster

**Comment by dzafman** [comment]
Stefan is reporting no hanging scrubs on original reporting cluster.

**Pull request merged**
