### PR TITLE
mimic: qa: test_recovery_pool tries asok on wrong node

### PR DESCRIPTION
**Pull request by pdvian**
http://tracker.ceph.com/issues/24928

### CODE REVIEW

**Comment by smithfarm** [comment]
@batrick Ping

**Comment by smithfarm** [comment]
Ah, now I see that mimic backport of #21885 is already open https://github.com/ceph/ceph/pull/23105

Marking this one DNM for now

**Comment by batrick** [comment]
PR #23105 is merged. Please rebase.

**Comment by pdvian** [comment]
@batrick kindly review.

**Comment by batrick** [comment]
jenkins retest

**Comment by batrick** [comment]
jenkins retest this

**Comment by batrick** [comment]
retest this please

**Comment by yuriw** [comment]
[wip-yuri4-testing-2018-10-15-0002-mimic](https://trello.com/c/hEUw3v8h/440-wip-yuri4-testing-2018-10-15-0002-mimic)

**Pull request merged**
