### PR TITLE
reef: mds: do not evict clients if OSDs are laggy

### PR DESCRIPTION
**Pull request by dparmar18**
backport tracker: https://tracker.ceph.com/issues/61842, https://tracker.ceph.com/issues/62443, https://tracker.ceph.com/issues/63271
parent tracker: https://tracker.ceph.com/issues/58023, https://tracker.ceph.com/issues/61907, https://tracker.ceph.com/issues/63105
backport of https://github.com/ceph/ceph/pull/49971, https://github.com/ceph/ceph/pull/52342, https://github.com/ceph/ceph/pull/53839/

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Review by lxbsz — APPROVED** [review]
LGTM.

**Comment by vshankar** [comment]
jenkins test api

**Review by vshankar — APPROVED** [review]
https://tracker.ceph.com/projects/cephfs/wiki/Reef#25-July-2023

**Comment by yuriw** [comment]
jenkins test api

**Comment by yuriw** [comment]
jenkins test api

**Comment by yuriw** [comment]
@dparmar18 @vshankar this is ready for merge as soon as apo check passes

ref: https://trello.com/c/A7beUbNB

**Comment by yuriw** [comment]
jenkins test api

**Comment by ljflores** [comment]
https://github.com/ceph/ceph/pull/53005

@dparmar18 you may want to cherry-pick this commit onto yours. If you go that route, you can then close my PR.

**Comment by dparmar18** [comment]
> Revoking approval since we need additional fix related to the beacon warnings.

@vshankar added commits and also updated the PR description with the details. PTAL

**Comment by dparmar18** [comment]
last push addressed make check failure

**Review by vshankar — APPROVED** [review]

**Comment by yuriw** [comment]
@dparmar18 I suspect this PR broke the build

https://jenkins.ceph.com/job/ceph-dev-new-build/ARCH=x86_64,AVAILABLE_ARCH=x86_64,AVAILABLE_DIST=centos8,DIST=centos8,MACHINE_SIZE=gigantic/73693//consoleFull

[ 46%] Building CXX object src/mds/CMakeFiles/mds.dir/Server.cc.o
/home/jenkins-build/build/workspace/ceph-dev-new-build/ARCH/x86_64/AVAILABLE_ARCH/x86_64/AVAILABLE_DIST/centos8/DIST/centos8/MACHINE_SIZE/gigantic/release/18.2.0-1178-g8b7031f3/rpm/el8/BUILD/ceph-18.2.0-1178-g8b7031f3/src/mds/Server.cc: In member function ‘void Server::handle_client_readdir_snapdiff(MDRequestRef&)’:
/home/jenkins-build/build/workspace/ceph-dev-new-build/ARCH/x86_64/AVAILABLE_ARCH/x86_64/AVAILABLE_DIST/centos8/DIST/centos8/MACHINE_SIZE/gigantic/release/18.2.0-1178-g8b7031f3/rpm/el8/BUILD/ceph-18.2.0-1178-g8b7031f3/src/mds/Server.cc:11444:41: error: ‘class ConfigValues’ has no member named ‘mds_max_xattr_pairs_size’
11444 |     max_bytes = (512 << 10) + g_conf()->mds_max_xattr_pairs_size;
      |                                         ^~~~~~~~~~~~~~~~~~~~~~~~

**Comment by vshankar** [comment]
> @dparmar18 I suspect this PR broke the build
> 
> https://jenkins.ceph.com/job/ceph-dev-new-build/ARCH=x86_64,AVAILABLE_ARCH=x86_64,AVAILABLE_DIST=centos8,DIST=centos8,MACHINE_SIZE=gigantic/73693//consoleFull
> 
> [ 46%] Building CXX object src/mds/CMakeFiles/mds.dir/Server.cc.o /home/jenkins-build/build/workspace/ceph-dev-new-build/ARCH/x86_64/AVAILABLE_ARCH/x86_64/AVAILABLE_DIST/centos8/DIST/centos8/MACHINE_SIZE/gigantic/release/18.2.0-1178-g8b7031f3/rpm/el8/BUILD/ceph-18.2.0-1178-g8b7031f3/src/mds/Server.cc: In member function ‘void Server::handle_client_readdir_snapdiff(MDRequestRef&)’: /home/jenkins-build/build/workspace/ceph-dev-new-build/ARCH/x86_64/AVAILABLE_ARCH/x86_64/AVAILABLE_DIST/centos8/DIST/centos8/MACHINE_SIZE/gigantic/release/18.2.0-1178-g8b7031f3/rpm/el8/BUILD/ceph-18.2.0-1178-g8b7031f3/src/mds/Server.cc:11444:41: error: ‘class ConfigValues’ has no member named ‘mds_max_xattr_pairs_size’ 11444 | max_bytes = (512 << 10) + g_conf()->mds_max_xattr_pairs_size; | ^~~~~~~~~~~~~~~~~~~~~~~~

Its https://github.com/ceph/ceph/pull/53340 which needs to be rectified. I had left a comment there but did not follow up with @trociny since I was on vacation.

**Comment by vshankar** [comment]
> > @dparmar18 I suspect this PR broke the build
> > https://jenkins.ceph.com/job/ceph-dev-new-build/ARCH=x86_64,AVAILABLE_ARCH=x86_64,AVAILABLE_DIST=centos8,DIST=centos8,MACHINE_SIZE=gigantic/73693//consoleFull
> > [ 46%] Building CXX object src/mds/CMakeFiles/mds.dir/Server.cc.o /home/jenkins-build/build/workspace/ceph-dev-new-build/ARCH/x86_64/AVAILABLE_ARCH/x86_64/AVAILABLE_DIST/centos8/DIST/centos8/MACHINE_SIZE/gigantic/release/18.2.0-1178-g8b7031f3/rpm/el8/BUILD/ceph-18.2.0-1178-g8b7031f3/src/mds/Server.cc: In member function ‘void Server::handle_client_readdir_snapdiff(MDRequestRef&)’: /home/jenkins-build/build/workspace/ceph-dev-new-build/ARCH/x86_64/AVAILABLE_ARCH/x86_64/AVAILABLE_DIST/centos8/DIST/centos8/MACHINE_SIZE/gigantic/release/18.2.0-1178-g8b7031f3/rpm/el8/BUILD/ceph-18.2.0-1178-g8b7031f3/src/mds/Server.cc:11444:41: error: ‘class ConfigValues’ has no member named ‘mds_max_xattr_pairs_size’ 11444 | max_bytes = (512 << 10) + g_conf()->mds_max_xattr_pairs_size; | ^~~~~~~~~~~~~~~~~~~~~~~~
> 
> Its #53340 which needs to be rectified. I had left a comment there but did not follow up with @trociny since I was on vacation.

@yuriw Please exclude PR #53340 from the branch for now.

**Comment by rishabh-d-dave** [comment]
@dparmar18  This [commit](https://github.com/ceph/ceph/pull/52268/commits/55d315d1c70479de4f58ea5bff49060e87021955) has multiple `cherry-picked from commit xyz` lines. Second on is not needed.

**Review by rishabh-d-dave — COMMENTED** [review]
@dparmar18 This [commit](https://github.com/ceph/ceph/pull/52268/commits/55d315d1c70479de4f58ea5bff49060e87021955) has multiple cherry-picked from commit xyz lines. Second on is not needed.

**Review by rishabh-d-dave — APPROVED** [review]
Otherwise looks good, approving on behalf of CephFS https://tracker.ceph.com/projects/cephfs/wiki/Reef#21-Nov-2023

**Pull request merged**
