### PR TITLE
jewel: rgw: rgw_file: FHCache residence check should be exhaustive

### PR DESCRIPTION
**Pull request by mattbenjamin**
Fixes: http://tracker.ceph.com/issues/19143
Replaces https://github.com/ceph/ceph/pull/13840

### CODE REVIEW

**Comment by ktdreyer** [comment]
@mattbenjamin would you please rebase this on to the latest jewel so it will merge cleanly?

**Comment by mattbenjamin** [comment]
@ktdreyer rebasd (dup of 0e5299f3 removed)

**Comment by ktdreyer** [comment]
@mattbenjamin , is `rgw_file:  use fh_hook::is_linked() to check residence` missing from this PR?

Looking at [Redmine issue 19143](http://tracker.ceph.com/issues/19143) and its [parent issue 19111](http://tracker.ceph.com/issues/19111), those tickets link to https://github.com/ceph/ceph/pull/13703 . But I don't see that commit in this PR.

**Comment by mattbenjamin** [comment]
@ktdreyer added

**Pull request merged**
