### PR TITLE
add rados api set_client_priority

### PR DESCRIPTION
**Pull request by tianshan**
Add new rados api set_client_priority, allow client to set message priority after connected to the cluster.
If set, will skip profile value.

### CODE REVIEW

**Comment by dachary** [comment]
@tianshan I get the general idea and it makes sense to me :-) However, it would be nice to get more input on this new API call from other people. Would you mind sending a mail to ceph-devel ? It would be most helpful to describe an actual use case and explain why setting osd_client_op_priority (either in the configuration file or via injectargs) is not enough.

**Comment by yuyuyu101** [comment]
@dachary I think it should be the part of (Messenger - priorities for Client)[http://tracker.ceph.com/projects/ceph/wiki/Messenger_-_priorities_for_Client)

**Comment by dachary** [comment]
@yuyuyu101 so you approve the principle of this pull request, right ?

**Comment by yuyuyu101** [comment]
Yep!

**Comment by dachary** [comment]
@tianshan ping ?

**Comment by tianshan** [comment]
yes

**Comment by dachary** [comment]
@tianshan did you start a thread on the ceph-devel mailing list as suggested ? @yuyuyu101 supports the idea, it will go well I think ;-)

**Comment by tianshan** [comment]
have @yuyuyu101 explain to you? I think maybe we should test more of the 'Messenger - priorities for Client' before start a thread

**Comment by yuyuyu101** [comment]
@dachary hi, do we need to call for more people involved in?

**Comment by dachary** [comment]
@tianshan @yuyuyu101 exposing a new function in the API deserve at least a discussion and approval from a lead, don't you think ? I don't see that this is going to be a difficult discussion :-) But going ahead without discussion does not seem like the right thing to do.

**Comment by tianshan** [comment]
ok I will start a thread for discussion

**Comment by dachary** [comment]
For the record the mailing list thread on ceph-devel is **A new rados api set_client_priority**

**Comment by dachary** [comment]
@tianshan could we close this pull request ? It can be re-opened later on, when a decision is made (as a conclusion of [A new rados api set_client_priority](http://www.spinics.net/lists/ceph-devel/msg26139.html) or any other mean).

**Comment by tianshan** [comment]
ok, after the work done I may reopen this

**Pull request closed without merging**
