### PR TITLE
doc: fixed broken links in nautilus release page

### PR DESCRIPTION
**Pull request by falcon78921**
- [x] References tracker ticket
- [x] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

Fixes: https://tracker.ceph.com/issues/39712
Signed-off-by: James McClune <jmcclune@mcclunetechnologies.net>

### CODE REVIEW

**Comment by theanalyst** [comment]
jenkins render docs

**Comment by tchaikov** [comment]
retest this please.

**Comment by falcon78921** [comment]
jenkins retest this please

**Comment by theanalyst** [comment]
jenkins test this please

**Comment by falcon78921** [comment]
jenkins retest this please

**Comment by tchaikov** [comment]
retest this please

**Comment by falcon78921** [comment]
I'm just following up on this PR. If there's anything else that needs done, please let me know :)

**Comment by tchaikov** [comment]
@falcon78921 thanks for your persistence! i think we were stopped by the "make check" failure when we we were about to merge this PR. but this time, it's not an issue anymore!

**Comment by falcon78921** [comment]
@tchaikov Awesome! :) Thank you Kefu for merging!

**Pull request merged**
