### PR TITLE
tools/ceph-kvstore-tool: print db stats

### PR DESCRIPTION
**Pull request by ifed01**
Signed-off-by: Igor Fedotov <ifedotov@suse.com>

In fact this command will provide zeros for most of compaction stuff as completed compactions are required to provide most of numbers. But one can use it to learn per-level DB statistics: (amount of files,
occupied space, etc).
Here is output extract:
db_statistics {
    "rocksdb_compaction_statistics": "",
    "": "",
    "": "** Compaction Stats [default] **",
    "": "Level    Files   Size     Score Read(GB)  Rn(GB) Rnp1(GB) Write(GB) Wnew(GB) Moved(GB) W-Amp Rd(MB/s) Wr(MB/s) Comp(sec) Comp(cnt) Avg(sec) KeyIn KeyDrop",
    "": "----------------------------------------------------------------------------------------------------------------------------------------------------------",
    "": "  L0      3/0   667.25 MB   2.6      0.0     0.0      0.0       0.0      0.0       0.0   0.0      0.0      0.0         0         0    0.000       0      0",
    "": "  L1      5/0   246.06 MB   1.0      0.0     0.0      0.0       0.0      0.0       0.0   0.0      0.0      0.0         0         0    0.000       0      0",
    "": "  L2     39/0    2.45 GB   1.0      0.0     0.0      0.0       0.0      0.0       0.0   0.0      0.0      0.0         0         0    0.000       0      0",
    "": "  L3     11/0   707.18 MB   0.0      0.0     0.0      0.0       0.0      0.0       0.0   0.0      0.0      0.0         0         0    0.000       0      0",
    "": " Sum     58/0    4.03 GB   0.0      0.0     0.0      0.0       0.0      0.0       0.0   0.0      0.0      0.0         0         0    0.000       0      0",
    "": " Int      0/0    0.00 KB   0.0      0.0     0.0      0.0       0.0      0.0       0.0   0.0      0.0      0.0         0         0    0.000       0      0",

- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by liewegas** [comment]
```
/home/jenkins-build/build/workspace/ceph-pull-requests/src/test/cli/ceph-kvstore-tool/help.t: failed
--- /home/jenkins-build/build/workspace/ceph-pull-requests/src/test/cli/ceph-kvstore-tool/help.t
+++ /home/jenkins-build/build/workspace/ceph-pull-requests/src/test/cli/ceph-kvstore-tool/help.t.err
@@ -18,4 +18,5 @@
     compact-prefix <prefix>
     compact-range <prefix> <start> <end>
     destructive-repair  (use only as last resort! may corrupt healthy data)
+    stats
```

The signed-off-by check also failed... i think it wants a newline between the first line and signed-off-by line?

**Comment by liewegas** [comment]
http://pulpito.ceph.com/sage-2019-03-26_03:52:56-rados-wip-sage-testing-2019-03-25-1934-distro-basic-smithi/ pass

**Comment by ifed01** [comment]
@liewegas - fixed

**Comment by hoerup** [comment]
will this be backported to nautilus ?

**Comment by ifed01** [comment]
@hoerup - probably, yes. This looks like quite an easy backport

**Comment by hoerup** [comment]
@ifed01 thanks. Nice to know, because a backport will affect both https://tracker.ceph.com/issues/40492 and https://tracker.ceph.com/issues/40491

**Pull request merged**
