### PR TITLE
mgr/dashboard: Edit host label dialog is crashing

### PR DESCRIPTION
**Pull request by votdev**
Fixes: https://tracker.ceph.com/issues/46370

Signed-off-by: Volker Theile <vtheile@suse.com>

## Checklist
- [x] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by tspmelo** [comment]
jenkins retest this please

**Comment by votdev** [comment]
jenkins test dashboard

**Comment by tspmelo** [comment]
Could you please add the following e2e test to prevent future problems:
```
diff --git a/src/pybind/mgr/dashboard/frontend/cypress/integration/cluster/hosts.e2e-spec.ts b/src/pybind/mgr/dashboard/frontend/cypress/integration/cluster/hosts.e2e-spec.ts
index 045b18f60cd..db1870969aa 100644
--- a/src/pybind/mgr/dashboard/frontend/cypress/integration/cluster/hosts.e2e-spec.ts
+++ b/src/pybind/mgr/dashboard/frontend/cypress/integration/cluster/hosts.e2e-spec.ts
@@ -35,4 +35,10 @@ describe('Hosts page', () => {
       hosts.check_services_links();
     });
   });
+
+  describe('edit modal', () => {
+    it('should open the edit modal', () => {
+      hosts.open_edit_modal('mgr');
+    });
+  });
 });
diff --git a/src/pybind/mgr/dashboard/frontend/cypress/integration/cluster/hosts.po.ts b/src/pybind/mgr/dashboard/frontend/cypress/integration/cluster/hosts.po.ts
index d3e75400bba..a4d61bf03f7 100644
--- a/src/pybind/mgr/dashboard/frontend/cypress/integration/cluster/hosts.po.ts
+++ b/src/pybind/mgr/dashboard/frontend/cypress/integration/cluster/hosts.po.ts
@@ -28,4 +28,10 @@ export class HostsPageHelper extends PageHelper {
         expect(links_tested).gt(0);
       });
   }
+
+  open_edit_modal(name: string) {
+    this.getFirstTableCell(name).click();
+    cy.contains('button', 'Edit').click();
+    cy.get('cd-form-modal').should('exist');
+  }
 }
```

**Comment by bk201** [comment]
> Could you please add the following e2e test to prevent future problems:

It might not work because in Jenkins we don't have Orchestrator-deployed hosts. (The edit button is disabled).

**Comment by votdev** [comment]
> Could you please add the following e2e test to prevent future problems:
> 
> ```
> diff --git a/src/pybind/mgr/dashboard/frontend/cypress/integration/cluster/hosts.e2e-spec.ts b/src/pybind/mgr/dashboard/frontend/cypress/integration/cluster/hosts.e2e-spec.ts
> index 045b18f60cd..db1870969aa 100644
> --- a/src/pybind/mgr/dashboard/frontend/cypress/integration/cluster/hosts.e2e-spec.ts
> +++ b/src/pybind/mgr/dashboard/frontend/cypress/integration/cluster/hosts.e2e-spec.ts
> @@ -35,4 +35,10 @@ describe('Hosts page', () => {
>        hosts.check_services_links();
>      });
>    });
> +
> +  describe('edit modal', () => {
> +    it('should open the edit modal', () => {
> +      hosts.open_edit_modal('mgr');
> +    });
> +  });
>  });
> diff --git a/src/pybind/mgr/dashboard/frontend/cypress/integration/cluster/hosts.po.ts b/src/pybind/mgr/dashboard/frontend/cypress/integration/cluster/hosts.po.ts
> index d3e75400bba..a4d61bf03f7 100644
> --- a/src/pybind/mgr/dashboard/frontend/cypress/integration/cluster/hosts.po.ts
> +++ b/src/pybind/mgr/dashboard/frontend/cypress/integration/cluster/hosts.po.ts
> @@ -28,4 +28,10 @@ export class HostsPageHelper extends PageHelper {
>          expect(links_tested).gt(0);
>        });
>    }
> +
> +  open_edit_modal(name: string) {
> +    this.getFirstTableCell(name).click();
> +    cy.contains('button', 'Edit').click();
> +    cy.get('cd-form-modal').should('exist');
> +  }
>  }
> ```

This does not work because the `Edit` action is only selectable for Orchestrator deployed hosts which are not available in the E2E test environment.

**Comment by tspmelo** [comment]
When I create a vstart cluster I'm able to select and click the edit button for `mgr` and  `osd0`.
Editing doesn't seem to do anything, but the modal opens.
Maybe there is a bug in the table?
image

**Comment by votdev** [comment]
> When I create a vstart cluster I'm able to select and click the edit button for `mgr` and `osd0`.
> Editing doesn't seem to do anything, but the modal opens.
> Maybe there is a bug in the table?
> image

How did you create the mgr0 and osd0 hosts? The `Edit` button is disabled if the field `orchestrator` is `False`. So i'm wondering how it is possible that the backend identifies an host as managed by Orchestrator in a vstart environment.

**Comment by tspmelo** [comment]
@votdev I just created the cluster using `start-ceph.sh` on `ceph-dev-docker`.
I'm using an old version of ceph, I will compile master and check again.

**Comment by votdev** [comment]
> When I create a vstart cluster I'm able to select and click the edit button for `mgr` and `osd0`.
> Editing doesn't seem to do anything, but the modal opens.
> Maybe there is a bug in the table?
> image

I've opened https://github.com/ceph/ceph/pull/36007 to add some more unit tests.

**Pull request merged**
