### PR TITLE
rgw: rgwgc:process coredump in some special case。 

### PR DESCRIPTION
**Pull request by cethikdata**
rgw: rgwgc:process coredump in some special case. last_pool is the name of pool and ctx is the io context of the pool. If the object's pool does not exit, the ctx is delete, but last_pool is not clear. So if the pool of the next object is last_pool, the ctx is a new one (with an empty pointer) and rgwgc will coredump.

We want the last_pool and ctx to be consistent. But in some special case, they are not.

Fixes:http://tracker.ceph.com/issues/23199

Signed-off-by: zhaokun develop@hikdata.com

### CODE REVIEW

**Comment by cbodley** [comment]
http://pulpito.ceph.com/cbodley-2018-12-06_14:35:32-rgw-wip-cbodley-testing-distro-basic-smithi

**Comment by mattbenjamin** [comment]
best to adopt this commit into a new PR

**Comment by cbodley** [comment]
there was a merge conflict, and my fix generated a merge commit that broke the Signed-off-by check. i reopened this https://github.com/ceph/ceph/pull/25430

**Comment by cbodley** [comment]
https://github.com/ceph/ceph/pull/25430 merged, thanks for the fix!

**Pull request closed without merging**
