### PR TITLE
kraken: osd: calc_clone_subsets misuses try_read_lock vs missing 

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/18723

### CODE REVIEW

**Comment by smithfarm** [comment]
Jenkins retest this please

**Comment by smithfarm** [comment]
Jenkins re-test this please

**Comment by smithfarm** [comment]
@athanatos This passed a rados suite at http://tracker.ceph.com/issues/19009#note-37 (3 tests failed initially, but passed the second time around)

Please review/approve when you get the chance. Thanks!

**Comment by smithfarm** [comment]
Can be merged once make check passes.

**Comment by smithfarm** [comment]
@tchaikov @jdurgin I just realized that the jewel equivalent of this backport - #12978 - was reverted by @athanatos in #13280 (don't know why, exactly). So now I'm doubting whether this should have been merged at all?

**Comment by smithfarm** [comment]
Ah, maybe this gives a clue: http://tracker.ceph.com/issues/18724#note-5

Would it be enough to backport http://tracker.ceph.com/issues/18809 to kraken?

**Comment by jdurgin** [comment]
Yes, backporting https://github.com/ceph/ceph/pull/13342 from http://tracker.ceph.com/issues/18809 should fix it

**Comment by smithfarm** [comment]
OK, see #16132

**Comment by smithfarm** [comment]
And we need to backport http://tracker.ceph.com/issues/18927 as well, according to Sam's comment http://tracker.ceph.com/issues/17831#note-21

**Pull request merged**
