### PR TITLE
Wip cephfs snap

### PR DESCRIPTION
**Pull request by ukernel**
only fix snapshot for single mds case.

### CODE REVIEW

**Comment by gregsfortytwo** [comment]
I'm giving this to @liewegas because he mentioned this morning (or yesterday?) that he had started reviewing it.

**Comment by dachary** [comment]
please ignore the bot, master is broken http://tracker.ceph.com/issues/10547

**Comment by gregsfortytwo** [comment]
@liewegas, @ukernel I believe you were talking about merging most of this branch up to some of the old inode changes. Can we do that soon? I'd like to stop seeing hung snaptests in the nightlies. ;)

**Comment by liewegas** [comment]
the patches i'd like to wait on are:

  c61a4c0
  f8ca585

i don't understand teh context behind 937b7c7

The rest look good to me but i don't know what the dependencies are...

**Comment by ukernel** [comment]
the new commits bring old behavior of COWing inode back. For f8ca585, I still think there is no need to recovery size of snap inode. because we can't guarantee data with the size has been properly flushed to OSD.

**Comment by liewegas** [comment]
These look good!  Looks like it needs a rebase.

I thinkI see the point now with the snapped file size recovery (it only matters when the client fails anyway).  I wish there was a way to prune the snaps we had to consider.. but, shrug.  Maybe we can just wrap this in a config option and default off?

With that, Reviewed-by:!  Thanks, sorry this took so long

**Comment by ukernel** [comment]
rebased one https://github.com/ceph/ceph/pull/3468

**Pull request closed without merging**
