### PR TITLE
hammer: config set with negative value results in "error setting 'filestore_merge_threshold' to '-40': (22) Invalid argument"

### PR DESCRIPTION
**Pull request by badone**
Fixes: http://tracker.ceph.com/issues/16680

### CODE REVIEW

**Comment by smithfarm** [comment]
Adding DNM just to keep this very new PR out of the next hammer integration testing round. Will remove it afterwards.

**Comment by badone** [comment]
@smithfarm understood but... somehow this missed being backported when it should have (my fault) and now we are pushing a deadline for a downstream release. If it can be included I'd appreciate it.

**Comment by smithfarm** [comment]
@badone I see you're adding a test to `qa/workunits` - is there anything that needs done on the ceph-qa-suite side to accommodate this?

**Comment by badone** [comment]
@smithfarm I don't think so. The test is in a file covered by the "cephtool" test. I did a run on sepia today that passed (wip-badone-testing branch) and will provide some details tomorrow as well as try and get this merged. Sleeping now :)

**Comment by smithfarm** [comment]
@badone I noticed that test, but it consists of only 2 jobs. . . So it doesn't really check for regressions.

**Comment by badone** [comment]
@smithfarm I worked out the command with @tchaikov but if it needs more then please let me know specifically what you need.

**Comment by jdurgin** [comment]
lgtm

**Comment by smithfarm** [comment]
@athanatos @tchaikov Are you OK to merge this without a full integration run? It will still go through QE of course.

**Comment by athanatos** [comment]
Yeah, looks ok to me.

**Comment by tchaikov** [comment]
@smithfarm lgtm.

**Pull request merged**
