### PR TITLE
mgr/cephadm: allow colocation of nfs daemons

### PR DESCRIPTION
**Pull request by mgfritch**
- generate a unique daemon_id per host
- allow nfs daemons to co-locate on a single host
- dynamically assign nfs ports using 2049 as the start port

Signed-off-by: Michael Fritch <mfritch@suse.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by mgfritch** [comment]
still wip, needs logic to avoid port conflicts between multiple nfs clusters

**Comment by sebastian-philipp** [comment]
> still wip, needs logic to avoid port conflicts between multiple nfs clusters

is this really blocking this particular PR or is this somewhat orthogonal and we can merge this anyway?

**Comment by mgfritch** [comment]
> > still wip, needs logic to avoid port conflicts between multiple nfs clusters
> 
> is this really blocking this particular PR or is this somewhat orthogonal and we can merge this anyway?

yeah, let's handle it in a subsequent PR

**Comment by mgfritch** [comment]
jenkins test api

**Comment by liewegas** [comment]
waiting on this until we have some clarity around how to handle initial support for NFS HA

**Comment by mgfritch** [comment]
closed in favor of #41007

**Pull request closed without merging**
