### PR TITLE
common,config: OPT_FLOAT and OPT_DOUBLE  output format in "config show" 

### PR DESCRIPTION
**Pull request by gmayyyha**
Fixes: http://tracker.ceph.com/issues/20104

Signed-off-by: Yanhu Cao <gmayyyha@gmail.com>

### CODE REVIEW

**Comment by Liuchang0812** [comment]
would you mind adding some test cases to `qa/workunits/cephtool/test.sh`?

**Comment by Liuchang0812** [comment]
@gmayyyha LGTM, but you need to squash and sign-off all your commits

**Comment by Liuchang0812** [comment]
try this command: `git rebase -i HEAD~4`, and `fixup` the last 3 commits. then `git push origin tell-injectargs-float -f`.

**Comment by gmayyyha** [comment]
@Liuchang0812 thanks for your advice

**Comment by Liuchang0812** [comment]
@gmayyyha there are 4 commits. it would be better to squash them.

```
try this command: git rebase -i HEAD~4, and fixup the last 3 commits. then git push origin tell-injectargs-float -f.

```

**Comment by tchaikov** [comment]
if this problem also exists in master, we should fix it in master. and then backport it to jewel and kraken.

**Comment by tchaikov** [comment]
and the title of the commit is misleading: it is related to the float point output format in"config show" , and has nothing to do with "injectargs".

**Comment by Liuchang0812** [comment]
This prolem also exists in master. @tchaikov 

 @gmayyyha could you change target branch to `master`?

```
➜  build git:(try-cpp-sdk) ✗ ceph tell osd.2 injectargs "--osd_deep_scrub_interval 2419200" 
*** DEVELOPER MODE: setting PATH, PYTHONPATH and LD_LIBRARY_PATH ***
2017-06-09 16:47:43.908831 7f2f218ee700 -1 WARNING: all dangerous and experimental features are enabled.
2017-06-09 16:47:43.914172 7f2f218ee700 -1 WARNING: all dangerous and experimental features are enabled.
osd_deep_scrub_interval = '2.4192e+06' (not observed, change may require restart) 
➜  build git:(try-cpp-sdk) ✗ ceph daemon osd.2 config show | grep osd_deep_scrub_interval 
*** DEVELOPER MODE: setting PATH, PYTHONPATH and LD_LIBRARY_PATH ***
    "osd_deep_scrub_interval": "2.4192e+06",
```

**Comment by gmayyyha** [comment]
@Liuchang0812 OK

**Comment by gmayyyha** [comment]
@Liuchang0812 replace commit or create a new pr ?

**Comment by Liuchang0812** [comment]
you could edit it online. for example, click "Edit"  at first(fig 1), then choose master branch(fig 2).

image

image

**Comment by gmayyyha** [comment]
@Liuchang0812 
lots of conflicts, then use these command ?
git checkout b tell-injectargs-float
git push origin tell-injectargs-float -f

**Comment by Liuchang0812** [comment]
You need to rebase your `gmayyyha:tell-injectargs-float` branch into master.

```
git checkout tell-injectargs-float

git rebase master 
```

**Comment by gmayyyha** [comment]
@Liuchang0812 
jewel code:
qq20170613-092325

kraken、luminous and master code:
qq20170613-092221


Implementation in different ways.  Do what you have commented on before ?

**Comment by Liuchang0812** [comment]
well, you could close this PR and re-create a new one if you don't know how to use git.

**Pull request closed without merging**
