### PR TITLE
mgr/dashboard: Improve RGW address parser

### PR DESCRIPTION
**Pull request by votdev**
- Add ability to parse IPv6 addresses
- Validate parsed RGW address

Signed-off-by: Volker Theile <vtheile@suse.com>

- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [x] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by sebastian-philipp** [comment]
It's depressing that we need to do that ourselves. And there is really no way to just pass-through the IPs as they are?

**Comment by votdev** [comment]
> Looks ok and I like doctests! Just a quick question: why not using [`ipaddress` Python library](https://cpython-test-docs.readthedocs.io/en/latest/library/ipaddress.html), which includes specific functions for validating IPv4 and v6 addresses, and checking network classes?

Hmmm, i think because of not knowing that this library is part of a standard Python installation.

**Comment by LenzGr** [comment]
> OK because it works as expected, or do you want to see it refactored?

I personally would be in favor of making use of existing libraries, where available. But since you already came up with a custom solution, I am fine with sticking to your implementation for now. But please submit a cleanup issue on the tracker to keep this in mind for future improving/refactoring (sounds like a low-hanging fruit to me)

**Comment by votdev** [comment]
> > OK because it works as expected, or do you want to see it refactored?
> 
> I personally would be in favor of making use of existing libraries, where available. But since you already came up with a custom solution, I am fine with sticking to your implementation for now. But please submit a cleanup issue on the tracker to keep this in mind for future improving/refactoring (sounds like a low-hanging fruit to me)

The socket library is a standard library and using inet_pton() is a common way (e.g. in C) to validate an IP address. So IMHO there is no need to use something else.

**Comment by p-na** [comment]
> > > OK because it works as expected, or do you want to see it refactored?
> > 
> > 
> > I personally would be in favor of making use of existing libraries, where available. But since you already came up with a custom solution, I am fine with sticking to your implementation for now. But please submit a cleanup issue on the tracker to keep this in mind for future improving/refactoring (sounds like a low-hanging fruit to me)
> 
> The socket library is a standard library and using inet_pton() is a common way (e.g. in C) to validate an IP address. So IMHO there is no need to use something else.

I also think that there's no need to do that now, but keeping track of a reasonable simplification makes sense to me. Using the `ipaddress` library would save at least 40 lines of code (including tests) and by that,  reduce the complexity of the code. I don't see a reason why we shouldn't use standard library functions whenever available.

**Comment by callithea** [comment]
QA run was successful: http://pulpito.ceph.com/laura-2019-01-16_12:16:39-rados:mgr-wip-lpaduano-testing-25870-distro-basic-smithi/

**Comment by votdev** [comment]
jenkins test make check

**Comment by votdev** [comment]
jenkins test make check64

**Comment by votdev** [comment]
jenkins retest this please

**Pull request merged**
