### PR TITLE
osd,bluestore: gracefully handle a failure during meta collection load

### PR DESCRIPTION
**Pull request by ifed01**
It looks like we don't have good enough handling when (for whatever reasons) meta collection is not loaded. Let's report and shutdown gracefully.

Relates-to: https://tracker.ceph.com/issues/53184

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Review by jdurgin — APPROVED** [review]

**Comment by jdurgin** [comment]
shall we use https://tracker.ceph.com/issues/53184 to track backporting this?

**Comment by ifed01** [comment]
> shall we use https://tracker.ceph.com/issues/53184 to track backporting this?

Probably no - #53184 revealed the issue with proper diagnosis but it's about a different issue IMO. So if one rather needs a different ticket if  we want to backport the patch. The latter isn't crucial though, the modification is rather a minor stuff.

**Review by neha-ojha — APPROVED** [review]
nit: you could drop `os/` from the commit title of f7772e2c4203d68b6e44a1c7c96cc13a0b466263 or use `osd/OSD.cc:`

**Comment by ifed01** [comment]
> nit: you could drop `os/` from the commit title of [f7772e2](https://github.com/ceph/ceph/commit/f7772e2c4203d68b6e44a1c7c96cc13a0b466263) or use `osd/OSD.cc:`

Yeah, thanks! Done.

**Comment by sseshasa** [comment]
Teuthology Test Results:

 http://pulpito.front.sepia.ceph.com/yuriw-2021-12-07_16:02:55-rados-wip-yuri11-testing-2021-12-06-1619-distro-default-smithi/

**Unrelated Failures:**

1. 16/22 jobs related to mds_upgrade_sequence failed with the  errors:
    Predominant Failure reason:
    Command failed on smithi001 with status 32: 'sudo nsenter --net=/var/run/netns/ceph-ns--home-ubuntu-cephtest-mnt.0 adjust-ulimits ceph-coverage /home/ubuntu/cephtest/archive/coverage /bin/mount -t ceph :/ /home/ubuntu/cephtest/mnt.0 -v -o norequire_active_mds,conf=/etc/ceph/ceph.conf,norbytes,name=0,mds_namespace=cephfs,nofallback'

    Existing tracker: https://tracker.ceph.com/issues/53487

2. http://pulpito.front.sepia.ceph.com/yuriw-2021-12-07_16:02:55-rados-wip-yuri11-testing-2021-12-06-1619-distro-default-smithi/6550482
   http://pulpito.front.sepia.ceph.com/yuriw-2021-12-07_16:02:55-rados-wip-yuri11-testing-2021-12-06-1619-distro-default-smithi/6550909
    Command failed (workunit test cephadm/test_dashboard_e2e.sh) on smithi101 with status 1
    New tracker created: https://tracker.ceph.com/issues/53499

3. http://pulpito.front.sepia.ceph.com/yuriw-2021-12-07_16:02:55-rados-wip-yuri11-testing-2021-12-06-1619-distro-default-smithi/6550484
    [Errno 2] Cannot find file on the remote 'ubuntu@smithi027.front.sepia.ceph.com': 'rook/cluster/examples/kubernetes/ceph/operator.yaml' 
    New tracker created: https://tracker.ceph.com/issues/53501

4. http://pulpito.front.sepia.ceph.com/yuriw-2021-12-07_16:02:55-rados-wip-yuri11-testing-2021-12-06-1619-distro-default-smithi/6550873
    Valgrind error during handle_recovery_delete()
    Existing tracker: https://tracker.ceph.com/issues/52124


5. http://pulpito.front.sepia.ceph.com/yuriw-2021-12-07_16:02:55-rados-wip-yuri11-testing-2021-12-06-1619-distro-default-smithi/6550960
    ceph_abort_msg("block checksum mismatch: stored = 632344828, computed = 928675071  in db/000047.sst offset 264241 size 3745")
    Existing tracker: https://tracker.ceph.com/issues/47453

**Pull request merged**
