### PR TITLE
qa: fix test_perf_stats_stale_metrics

### PR DESCRIPTION
**Pull request by joscollin**
* This patch replaces the time.sleep with wait_for_state.
* `client_metadata` and `global_metrics` would be empty after a failover (not just stale). So used 'get()' and added checks for that.

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [x] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [x] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Review by neesingh-rh — APPROVED** [review]
LGTM

**Comment by vshankar** [comment]
@joscollin Is there a tracker for this?

**Comment by joscollin** [comment]
> @joscollin Is there a tracker for this?

No, this depends on https://github.com/ceph/ceph/pull/46068.

**Comment by vshankar** [comment]
> > @joscollin Is there a tracker for this?
> 
> No, this depends on #46068.

OK -- I'll add this to my branch.

**Comment by vshankar** [comment]
> > @joscollin Is there a tracker for this?
> 
> No, this depends on #46068.

@joscollin This change has a merge conflict with https://github.com/ceph/ceph/pull/46068 -- I'm picking this up in a separate branch.

**Comment by joscollin** [comment]
@vshankar FYI, This PR is to be tested with the new 'perf stats' structure changes.

**Comment by vshankar** [comment]
> @vshankar FYI, This PR is to be tested with the new 'perf stats' structure changes.

could you mark this as dependent on that or include the commits in that pr?

**Comment by joscollin** [comment]
> > @vshankar FYI, This PR is to be tested with the new 'perf stats' structure changes.
> 
> could you mark this as dependent on that or include the commits in that pr?

I don't know how to mark PR dependencies in github. 

@neesingh-rh Please take this commit and apply it to https://github.com/ceph/ceph/pull/46068. 
Note: You may need to revert your test_perf_stats_stale_metrics() changes in https://github.com/ceph/ceph/pull/46068 while adding this commit. When you are done, please close this PR.

**Comment by vshankar** [comment]
@joscollin @neesingh-rh dropping this for now -- please reach out when the issues have been fixed.

**Comment by neesingh-rh** [comment]
Added this commit to https://github.com/ceph/ceph/pull/46068 .So, closing this PR.

**Pull request closed without merging**
