### PR TITLE
msg/async/rdma: ensure CephContext existed

### PR DESCRIPTION
**Pull request by yuyuyu101**
Signed-off-by: Haomai Wang <haomai@xsky.com>

### CODE REVIEW

**Comment by alekseymmm** [comment]
I have done some tests with the last changes and it fixed the problem.

**Comment by alekseymmm** [comment]
I have done some tests and I think that last patch fixed the problem. I tested it with fio 2.13 and 2.15, both works fine.

**Comment by yuriw** [comment]
http://pulpito.ceph.com/yuriw-2016-11-22_16:38:08-rados-wip-yuri-testing2_2016_11_21-distro-basic-smithi/

http://pulpito.ceph.com/yuriw-2016-11-22_16:38:08-rados-wip-yuri-testing2_2016_11_21-distro-basic-smithi/

**Comment by yuriw** [comment]
@yuyuyu101 - I see no tracker ticket reference, it'd be useful if you can link it.

**Pull request merged**
