### PR TITLE
errorator: improve general error handlers

### PR DESCRIPTION
**Pull request by athanatos**

### CODE REVIEW

**Comment by athanatos** [comment]
@rzarzynski Hrm, apparently this series had a significant effect on throughput.  Does anything jump out at you as a likely culprit?

**Comment by rzarzynski** [comment]
@athanatos: nothing obvious apart from a false alarm. Is your concern solely based on the `perf test`'s result? Recently the bot behaved weird.

```
02:14:49 - WARNING  - cbt      - rand/incerta08.front.sepia.ceph.com/0: bandwidth: (or (greater) (near 0.05)):: 233.476/274.037  => rejected
```
In general the patches LGTM.

**Comment by athanatos** [comment]
Yeah, I'm worried about the perf result.  I'm fine with merging it if you think it's nothing to worry about though.

**Comment by rzarzynski** [comment]
Let's retest.

jenkins test crimson perf

**Comment by rzarzynski** [comment]
jenkins test crimson perf

**Comment by athanatos** [comment]
@rzarzynski Ah, I guess it was a false positive.  I can merge it if you approve it.

**Pull request merged**
