### PR TITLE
rgw: s3 object lock avoids overflow in retention date

### PR DESCRIPTION
**Pull request by cbodley**
with `int days`, `days*24*60*60` would overflow above 24855

Fixes: https://tracker.ceph.com/issues/56993

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Review by mattbenjamin — APPROVED** [review]
lgtm

**Comment by cbodley** [comment]
@mattbenjamin i added an extra commit that uses c++20's `days` and `years` conversions. it's a separate commit that isn't intended for backports

from https://en.cppreference.com/w/cpp/chrono/duration:
> Each of the predefined duration types days, weeks, months and years covers a range of at least ±40000 years. years is equal to 365.2425 days (the average length of a Gregorian year). months is equal to 30.436875 days (exactly 1/12 of years).

**Comment by mattbenjamin** [comment]
the conversions are nice.  but what I saw is that iff your original change was correct "int days" is a narrowing conversion, and assumed that was the case.  is it not?  do we really want to use int here (what does get_days() return)?

**Comment by cbodley** [comment]
> the conversions are nice. but what I saw is that iff your original change was correct "int days" is a narrowing conversion, and assumed that was the case. is it not? do we really want to use int here (what does get_days() return)?

`get_days()` returns int. the overflow happened during the multiplication `days*24*60*60`, so one of those operands needed to be 64-bit. i changed it back to `int` now that std::chrono is handling the conversion

**Comment by cbodley** [comment]
passed qa in https://pulpito.ceph.com/cbodley-2023-07-21_18:36:50-rgw-wip-cbodley-testing-distro-default-smithi/

**Pull request merged**
