### PR TITLE
luminous: common/config: hold lock while accessing mutable container

### PR DESCRIPTION
**Pull request by dillaman**
https://tracker.ceph.com/issues/41772

### CODE REVIEW

**Comment by smithfarm** [comment]
jenkins test make check

**Comment by smithfarm** [comment]
jenkins test docs

**Comment by smithfarm** [comment]
```
+ ./admin/build-doc
./admin/build-doc: missing required packages, please install them:
sudo apt-get install -o APT::Install-Recommends=true cython
```

**Comment by smithfarm** [comment]
```
73 tests failed out of 149
```

Not sure what to think about that...

**Comment by smithfarm** [comment]
The `docs: build check` failure is addressed by https://github.com/ceph/ceph/pull/30665

**Comment by smithfarm** [comment]
@dillaman Is the massive "make check" failure a real issue or a red herring?

**Comment by dillaman** [comment]
@smithfarm it's real -- let me take a look

**Comment by dillaman** [comment]
@smithfarm fixed

**Comment by yuriw** [comment]
[wip-yuri5-testing-2019-10-08-2016-luminous](https://trello.com/c/2sPmnyf7/713-wip-yuri5-testing-2019-10-08-2016-luminous)

**Pull request merged**
