### PR TITLE
Octopus rgwlc mtime

### PR DESCRIPTION
**Pull request by mattbenjamin**
## Checklist
- [x] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by yuriw** [comment]
[wip-yuri5-testing-2020-09-14-1601-octopus](https://trello.com/c/kF99paA9/1009-wip-yuri5-testing-2020-09-14-1601-octopus)

**Comment by cbodley** [comment]
jenkins test api

**Comment by cbodley** [comment]
jenkins test api

**Review by yuriw — APPROVED** [review]

**Comment by cbodley** [comment]
jenkins test api

**Review by cbodley — APPROVED** [review]

**Comment by smithfarm** [comment]
@mattbenjamin Use `git cherry-pick -x` next time?

**Pull request merged**
