### PR TITLE
mailmap updates

### PR DESCRIPTION
**Pull request by dupont-y**
I preferred to make another pull request, please disregard previous one.
I based this work on a cleaned up .mailmap.
Somewhat too much cleaned. 

The first patch is probably a bit over optimistic ; It's ok for the current run , but if you run credits.sh on historic releases, you may find again some non canonical names appears. That's because I assumed that a line like Zhiqiang Wang zhiqiang.wang@intel.com wonzhq@hotmail.com catch ALL zhiqiang.wang@intel.com and ALL wonzhq@hotmail.com. That's not the case, it only cath the 2nd one. To be complete you also need a first line like this : Zhiqiang Wang zhiqiang.wang@intel.com

I'll correct this tomorrow.

### CODE REVIEW

**Comment by dupont-y** [comment]
This is the cleaned & corrected version.
This one gives correct output for current versions & historic ones. Made a diff with this .mailmap and old ones for a bunch of runs, and they're giving me same results.

**Comment by dupont-y** [comment]
scienceluo -> Luo Kexue
ritz_303 -> Aron Gunn

**Comment by dachary** [comment]
Very nice cleanup :-) To verify it does not introduce regressions, I ran bash ../credits.sh tags/v0.67..ceph/master on your branch. I'm not sure if the following are regression or mapping that did not yet exist but I'm not sure how to sort out the difference.

<pre>
shun-s &lt;songshun134@126.com>
root &lt;root@clove83.zte.com.cn>
atwardowski &lt;adam.twardowski@gmail.com>
shishir gowda &lt;shishir.gowda@sandisk.com>
changtao &lt;changtao@hihuron.com>
git-harry &lt;git-harry@live.co.uk>
jingkai &lt;jingkai.yuan@intel.com>
fangdong &lt;yp.fangdong@gmail.com>
</pre>

And the following people are not affiliated (i.e. they show in the "Organization" lists)

<pre>
Barbora Ančincová &lt;bancinco@redhat.com>
Erwan Velu &lt;erwan@redhat.com>
Robert LeBlanc &lt;robert.leblanc@endurance.com>
Marcel Lauhoff &lt;ml@irq0.org>
Sahithi R V &lt;tansy.rv@gmail.com>
Marcel Lauhoff &lt;lauhoff@uni-mainz.de>
Jianjian Huo &lt;samuel.huo@gmail.com>
Xinze Chi &lt;xinze@xksy.com>
Wei Jin &lt;wjin.cn@gmail.com>
shun-s &lt;songshun134@126.com>
root &lt;root@clove83.zte.com.cn>
Roi Dayan &lt;roid@mellanox.com>
Rachana Patel &lt;rachana83.patel@gmail.com>
Patrick Donnelly &lt;batrick@batbytes.com>
Mauricio Garavaglia &lt;mauriciogaravaglia@gmail.com>
Lukasz Jagiello &lt;lukasz@wikia-inc.com>
Kevin Jones &lt;k.j.jonez@gmail.com>
JP François &lt;francoisjp@gmail.com>
jingkai &lt;jingkai.yuan@intel.com>
Jeffrey Lu &lt;lzhng2000@hotmail.com>
Ivan Grcic &lt;igrcic@gmail.com>
Gu Zhongyan &lt;guzhongyan@360.cn>
git-harry &lt;git-harry@live.co.uk>
fangdong &lt;yp.fangdong@gmail.com>
chuanhong-wang &lt;chuanhong.wang@163.com>
Benoît Knecht &lt;benoit.knecht@fsfe.org>
atwardowski &lt;adam.twardowski@gmail.com>
Alexey Sheplyakov &lt;asheplyakov@mirantis.com>
Alan Grosskurth &lt;code@alan.grosskurth.ca>
</pre>

**Comment by dupont-y** [comment]
Le 08/02/16 02:02, Loic Dachary a écrit :
>
> Very nice cleanup :-) To verify it does not introduce regressions, I 
> ran bash ../credits.sh tags/v0.67..ceph/master on your branch. I'm not 
> sure if the following are regression or mapping that did not yet exist 
> but I'm not sure how to sort out the difference.
>

If you want to compare old and new .mailmap , please test ../credits.sh 
tags/v0.67..ceph/v10.0.2 with old & new .mailmap because it's where the 
work begun.

There should be 1 difference, but this one should be ok, I let you find 
it :) If it's not the case, please let me know.

My current work is based on upstream/jewel branch, so output is OK if 
you do ../credits.sh tags/v0.67..ceph/jewel , assuming ceph is the 
upstream name you're using.

in master there is lots of others patches and others authors too. I 
think it's what you're seeing.

I'm going to add them now.

Cheers,

**Comment by dupont-y** [comment]
Last round of updates, now in sync with upstream/master

BTW loïc, some of the entries given yesterday were very old ones. I suppose some were forgotten long, long time ago.

Now I'll send missing mails, and one last thing to do after commiting this work is to sort files.

Cheers,

**Comment by dachary** [comment]
LGTM and ready to send the emails asking for review.

**Comment by dupont-y** [comment]
BTW, apart from confirmations received directly by authors, should I also add reviewed by Loic & Abishek on all the commits ? I remember doing this the first timz a

**Comment by dupont-y** [comment]
BTW, apart from confirmations received directly by authors, should I also add reviewed by Loic & Abishek on all the commits ? I remember doing this the first time and forgot this other times.

**Comment by dachary** [comment]
@dupont-y no need to add my reviewed-by, we don't usually do that.

**Comment by dupont-y** [comment]
Le 12/02/16 07:14, Loic Dachary a écrit :
>
> Merged #7528 <https://github.com/ceph/ceph/pull/7528>.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/ceph/ceph/pull/7528#event-548155624>.
>
A bit late, but thanks :)

**Pull request merged**
