### PR TITLE
osd: deep-scrub optimization

### PR DESCRIPTION
**Pull request by yanghonggang**
skip short life object's read when do deep scrub

Signed-off-by: Yang Honggang <yanghonggang@cmss.chinamobile.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [x] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by yanghonggang** [comment]
@ronen-fr please help to review

**Comment by ronen-fr** [comment]
@yanghonggang: before delving into the implementation details - a few
questions:

First - can you specify the rationale for the change?
I can guess, but I think it should  be specified clearly in the commit message.

and - regarding that rationale: deep-scrub guards both against bit-rot and against
Ceph bugs. Do you have real-world measurements or experience with this patch,
to justify giving up on the second reason?

And a design question (sorry if I missed the handling of that in the code):
the suggested change affects the backends of both Primary and replicas. Suppose a
data problem causes the size to be below the threshold on a replica, but above that
threshold - on the Primary (or some other replica). How should the logic handle that?

**Comment by yanghonggang** [comment]
> First - can you specify the rationale for the change?
> I can guess, but I think it should  be specified clearly in the commit message.

When do deep scrub, all objects within one pg will be read from disk. Intuitively, it is unnecessary to read the newly written objects and check its data( for the data corruption probability is low). And if these new objects will be deleted soon(short life objects), we don't need to check their data at all. Maybe we should call this optimization `lazy deep scrub`.

> and - regarding that rationale: deep-scrub guards both against bit-rot and against
> Ceph bugs. Do you have real-world measurements or experience with this patch,
> to justify giving up on the second reason?

This PR provides an option to skip the latest update object when deep scrubbing instead of unconditionally scrubbing all objects, and is disabled by default. And scrub on objects that live longer than the threshold can also catch Ceph's bugs. 
This feature has only been self-tested in the vstart environment, and no long-term testing has been carried out.

> And a design question (sorry if I missed the handling of that in the code):
> the suggested change affects the backends of both Primary and replicas. Suppose a
> data problem causes the size to be below the threshold on a replica, but above that
> threshold - on the Primary (or some other replica). How should the logic handle that?

The difference in `local_mtime` between replicas/data shards usually is small (e.g. 336289.378759 seconds for one shard and 336289.378814 seconds for the other). Some shards/replica performs real read and others not have no serious consequences. If the object existence time exceeds the threshold, deep scrub will be performed as before.

@ronen-fr

**Comment by yanghonggang** [comment]
@ronen-fr  ping

**Comment by ronen-fr** [comment]
> When do deep scrub, all objects within one pg will be read from disk. Intuitively, it is unnecessary to read the newly written objects and check its data( for the data corruption probability is low). And if these new objects will be deleted soon(short life objects), we don't need to check their data at all. Maybe we should call this optimization `lazy deep scrub`.
> 
I surely understand. But what I meant was - this explanation should go into the commit message.

**Comment by ronen-fr** [comment]
> The difference in `local_mtime` between replicas/data shards usually is small (e.g. 336289.378759 seconds for one shard and 336289.378814 seconds for the other). Some shards/replica performs real read and others not have no serious consequences. If the object existence time exceeds the threshold, deep scrub will be performed as before.

There seem to be a miscommunication here. What I am asking is this:
the timeout check is performed separately by the primary and each replica. What are the consequences of some of the nodes deciding to perform the deep-scrub while others decide not to? can you specify how this affects the comparisons performed by the primary when all results are received?

**Comment by ronen-fr** [comment]
> This PR provides an option to skip the new object's read when deep scrubbing instead of unconditionally read all objects, and is disabled by default. And scrub on objects that live longer than the threshold can also catch Ceph's bugs. This feature has only been self-tested in the vstart environment, and no long-term testing has been carried out.
> 
> >

See my review summary.

**Review by ronen-fr — CHANGES_REQUESTED** [review]
The suggested change adds complexity to the scrub code - complexity that has
its own cost. This must be justified by an analysis of the performance gains in actual
usage. And on the face of it - if only "temporary" objects are excluded (for some configured
definition of 'temporary'), it seems the gains are expected to be limited.

I would vote against including this code without a very strong and detailed reason (and - of course - resolution to the issues already mentioned, and a few more that come to mind (e.g. - the setting should be ignored for some types of scrubs, e.g. after-repair scrubs))

**Pull request closed without merging**
