### PR TITLE
[DNM] jewel: Don't lose deep-scrub information

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/18502

### CODE REVIEW

**Comment by dachary** [comment]
jenkins test this please

**Comment by dachary** [comment]
jenkins test this please

**Comment by smithfarm** [comment]
@dzafman This fails src/test/osd/osd-scrub-repair.sh . . . Do you think https://github.com/ceph/ceph/commit/d30056a1 would help?

**Comment by smithfarm** [comment]
```
/home/jenkins-build/build/workspace/ceph-pull-requests/qa/workunits/ceph-helpers.sh:911: objectstore_tool:  ceph-objectstore-tool --data-path td/osd-scrub-repair/3 --journal-path td/osd-scrub-repair/3/journal SOMETHING list-attrs
Error getting attr on : 2.0s0_head,0#-4:00000000:::scrub_2.0s0:head#, (61) No data available
_
hinfo_key
snapset
```

**Comment by smithfarm** [comment]
Changelog:

* cherry-picked 907e79e into the PR to fix the make check failure

**Comment by dzafman** [comment]
This needs cherry-picked of 85e0774a7dded4aa6c67f237416041e25a7680bc to be included.  It was a required ceph-qa-suite change now part of the ceph repo.

**Comment by smithfarm** [comment]
@dzafman Done, please take a look at it, though - log-whitelist in jewel is quite different than in master.

**Comment by dzafman** [comment]
@smithfarm Looks fine

**Comment by dzafman** [comment]
@smithfarm @ldachary I wish we could get all the backports merged to jewel without conflicts.  Could we use a jewel-next?  Merge pull requests into jewel-next, integration test then manually merge jewel-next to jewel which should be a fast-forward.

**Comment by smithfarm** [comment]
@dzafman In the past we have merged PRs that touch the same areas of code into "super PRs".

**Comment by smithfarm** [comment]
Might be replaced by #13146

**Comment by smithfarm** [comment]
FWIW this passed a rados suite at http://tracker.ceph.com/issues/17851#note-53

**Comment by dzafman** [comment]
Merged with ceph/ceph#13146

**Pull request closed without merging**
