### PR TITLE
osd/ECBackend: Send write message to peers first, then do local write

### PR DESCRIPTION
**Pull request by hjwsm1989**
Like ReplicatedBackend did, this will improve write performance.

  Signed-off-by: huangjun <hjwsm1989@gmail.com>

### CODE REVIEW

**Comment by hjwsm1989** [comment]
as discussed in https://github.com/ceph/ceph/pull/11888

**Comment by hjwsm1989** [comment]
@athanatos please review it

**Comment by athanatos** [comment]
I'm really not convinced that this makes a difference.  The local write and message sends here are async.

**Comment by athanatos** [comment]
Please reopen if there is evidence that it makes a difference.

**Comment by liewegas** [comment]
With bluestore a non-trivial amount of work is now happening in queue_transaction (everything but io).  Is there a downside to doing this?  It can't hurt

**Comment by athanatos** [comment]
Ok, that's a valid reason!

**Comment by hjwsm1989** [comment]
did the failed test related to this PR?

**Comment by liewegas** [comment]
retest this please

**Pull request merged**
