### PR TITLE
WIP: pacific: qa/suites/upgrade: upgrade test autoscale profile

### PR DESCRIPTION
**Pull request by kamoltat**
Introduce an upgrade test for the autoscale profile
v16.2.5 - v16.2.6

We test to see after the upgrade to v16.2.6 if the newly created
pool will have a `scale-up` profile and that
the existing pool that was created in v16.2.5 also
has a `scale-up` profile.

Pending for https://github.com/ceph/ceph/pull/43999 to be merged and backported to Pacific

Signed-off-by: Kamoltat <ksirivad@redhat.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Review by yuriw — APPROVED** [review]

**Comment by kamoltat** [comment]
jenkins retest

**Comment by kamoltat** [comment]
jenkins retest this please

**Comment by neha-ojha** [comment]
@yuriw you don't need to test this, @kamoltat is already on it!

**Comment by neha-ojha** [comment]
@kamoltat Let's re-target this for master, along with the PR that will implement max pg num and change the default to scale-down as described in https://tracker.ceph.com/issues/53309

**Comment by kamoltat** [comment]
This PR became Irrelevant

**Pull request closed without merging**
