### PR TITLE
qa/erasure-code: override min_size to 2

### PR DESCRIPTION
**Pull request by tchaikov**
Fixes: http://tracker.ceph.com/issues/19770

### CODE REVIEW

**Comment by tchaikov** [comment]
being tested at http://pulpito.ceph.com/kchai-2017-04-28_14:27:25-rados-wip-14820-kefu---basic-mira/

**Comment by liewegas** [comment]
Hmm, your diagnosis in the bug has me worried.  Shouldn't this be backfilling even though it is below min_size?

**Comment by tchaikov** [comment]
```c++
  // We go incomplete if below min_size for ec_pools since backfill
  // does not currently maintain rollbackability
  // Otherwise, we will go "peered", but not "active"
  if (num_want_acting < pool.info.min_size &&
      (pool.info.ec_pool() ||
       !cct->_conf->osd_allow_recovery_below_min_size)) {
    want_acting.clear();
    dout(10) << "choose_acting failed, below min size" << dendl;
    return false;
  }
```

quote from `PG::choose_acting()`.

does this answer your q?

**Comment by liewegas** [comment]
yep!  i'll add this to teh rados backlog in trello.

**Comment by tchaikov** [comment]
@yuriw sorry the tests involving "qa/erasure-code/ec-rados-plugin=isa-k=2-m=1.yaml" would fail, see http://pulpito.ceph.com/kchai-2017-04-28_14:27:25-rados-wip-14820-kefu---basic-mira/.

rerunning the test at http://pulpito.ceph.com/kchai-2017-04-29_02:44:22-rados-wip-14820-kefu---basic-smithi/

**Comment by tchaikov** [comment]
yuriw, both run passed so i am merging this

- http://pulpito.ceph.com/kchai-2017-04-29_02:44:22-rados-wip-14820-kefu---basic-smithi/
- http://pulpito.ceph.com/kchai-2017-04-29_03:45:19-rados-wip-14820-kefu---basic-smithi/

**Pull request merged**
