### PR TITLE
qa: check pool full flags

### PR DESCRIPTION
**Pull request by batrick**
Cluster-wide flag removed in b4ca5ae462c6f12ca48b787529938862646282cd.

Signed-off-by: Patrick Donnelly <pdonnell@redhat.com>

### CODE REVIEW

**Comment by yuriw** [comment]
[wip-yuri4-testing-2017-12-19-1722](https://trello.com/c/xgMNUBoj/215-wip-yuri4-testing-2017-12-19-1722)

**Comment by batrick** [comment]
@yuriw still working on this so it's not ready yet for testing.

**Comment by yuriw** [comment]
@batrick this is part of mimic-dev1 branch we are testing now

**Comment by batrick** [comment]
It hasn't been merged into mimic-dev1 yet?

Anyway, it's fine if you're testing this but it doesn't fix the problem yet.

**Comment by batrick** [comment]
Nevermind, this patch fixes the issue as advertised but there are other issues.

http://tracker.ceph.com/issues/22482

**Comment by batrick** [comment]
@liewegas https://github.com/ceph/ceph/pull/19602

**Pull request merged**
