### PR TITLE
nautilus: ceph-volume: add utility functions

### PR DESCRIPTION
**Pull request by mogeb**
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by mogeb** [comment]
@alfredodeza anything blocking this?

**Comment by alfredodeza** [comment]
jenkins test ceph-volume lvm all

**Comment by alfredodeza** [comment]
jenkins test ceph-volume batch all

**Comment by alfredodeza** [comment]
jenkins test ceph-volume tox

**Comment by mogeb** [comment]
Looks like we're still hitting the git fetch issue here.

**Comment by mogeb** [comment]
FWIW, all tests (and the linter) pass on my system:
```

**Comment by alfredodeza** [comment]
jenkins test ceph-volume lvm all

**Comment by alfredodeza** [comment]
ungh, I re-triggered the wrong ones

**Pull request merged**
