### PR TITLE
async: skip unnecessary steps when parsing simple messages

### PR DESCRIPTION
**Pull request by yuyuyu101**
Signed-off-by: Haomai Wang <haomai@xsky.com>

### CODE REVIEW

**Comment by yuyuyu101** [comment]
@branch-predictor what about this changes? it should be more clearly

**Comment by branch-predictor** [comment]
@yuyuyu101 it's pretty much the same as https://github.com/ceph/ceph/pull/8000, I'll close mine.

**Comment by yuyuyu101** [comment]
passed http://pulpito.ceph.com/haomai-2016-05-01_23:40:37-rados-wip-haomai-testing-distro-basic-smithi/

**Comment by tchaikov** [comment]
@yuyuyu101 could you add a "Reviewed-by" line next time?

**Comment by yuyuyu101** [comment]
ok

**Pull request merged**
