### PR TITLE
mgr/cephadm: make type annotations for module.py mandatory

### PR DESCRIPTION
**Pull request by sebastian-philipp**
Fixing bogus json representation for registry-login

Signed-off-by: Sebastian Wagner <sebastian.wagner@suse.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by mgfritch** [comment]
jenkins retest this please

**Comment by sebastian-philipp** [comment]
```
Traceback (most recent call last):
  File "/home/jenkins-build/build/workspace/ceph-pr-docs/doc/scripts/../../src/script/gen_static_command_descriptions.py", line 169, in 
    print(json.dumps(gen_commands_dicts(), indent=2, sort_keys=True))
  File "/home/jenkins-build/build/workspace/ceph-pr-docs/doc/scripts/../../src/script/gen_static_command_descriptions.py", line 164, in gen_commands_dicts
    comms = from_mon_commands_h() + from_mgr_modules()
  File "/home/jenkins-build/build/workspace/ceph-pr-docs/doc/scripts/../../src/script/gen_static_command_descriptions.py", line 86, in from_mgr_modules
    comms = sum([list_mgr_module(name) for name in names], [])
  File "/home/jenkins-build/build/workspace/ceph-pr-docs/doc/scripts/../../src/script/gen_static_command_descriptions.py", line 86, in 
    comms = sum([list_mgr_module(name) for name in names], [])
  File "/home/jenkins-build/build/workspace/ceph-pr-docs/doc/scripts/../../src/script/gen_static_command_descriptions.py", line 66, in list_mgr_module
    mgr_mod = __import__(m_name, globals(), locals(), [], 0)
  File "/home/jenkins-build/build/workspace/ceph-pr-docs/src/pybind/mgr/cephadm/__init__.py", line 6, in 
    from .module import CephadmOrchestrator
  File "/home/jenkins-build/build/workspace/ceph-pr-docs/src/pybind/mgr/cephadm/module.py", line 120, in 
    metaclass=CLICommandMeta):
  File "/home/jenkins-build/build/workspace/ceph-pr-docs/src/pybind/mgr/cephadm/module.py", line 987, in CephadmOrchestrator
    def _executable_path(self, conn: remoto.backends.BaseConnection, executable: str) -> str:
AttributeError: 'NoneType' object has no attribute 'backends'
```

**Comment by sebastian-philipp** [comment]
https://pulpito.ceph.com/swagner-2020-12-09_11:23:12-rados:cephadm-wip-swagner3-testing-2020-12-09-1003-distro-basic-smithi/

Failures: 

* https://tracker.ceph.com/issues/48142
* docker.io rate limit for podman on ubuntu
* dashboard e2e

**Comment by sebastian-philipp** [comment]
jenkins test make check

**Comment by sebastian-philipp** [comment]
jenkins test api

**Review by jmolmo — APPROVED** [review]

**Pull request merged**
