### PR TITLE
cephfs-shell: modify and add descriptions for commands

### PR DESCRIPTION
**Pull request by tengjie5**
Fixes: https://tracker.ceph.com/issues/62074
Signed-off-by: jie teng tengjie5@asiainfo.com

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by tengjie5** [comment]
@neesingh-rh  I'm sorry.  Due to my incorrect operation, the previous pr 52756 was closed，please review it again, thanks.

**Comment by neesingh-rh** [comment]
> @neesingh-rh I'm sorry. Due to my incorrect operation, the previous pr 52756 was closed，please review it again, thanks.

No worries!!

**Review by neesingh-rh — COMMENTED** [review]
Pls sign off your commit correctly, otherwise LGTM

**Comment by neesingh-rh** [comment]
> Pls sign off your commit correctly, otherwise LGTM

```
Set you config using these:
Your name: git config user.name "FIRST_NAME LAST_NAME"
Your email: git config user.email "MY_NAME@example.com"
and then do commit : git commit -s
```

**Comment by tengjie5** [comment]
thanks，Sign has been modified.

**Comment by joscollin** [comment]
> thanks，Sign has been modified.

Please read https://docs.ceph.com/en/quincy/start/documenting-ceph/#commit-the-change

**Review by joscollin — CHANGES_REQUESTED** [review]
Please read https://docs.ceph.com/en/quincy/start/documenting-ceph/#commit-the-change

**Comment by tengjie5** [comment]
> Please read https://docs.ceph.com/en/quincy/start/documenting-ceph/#commit-the-change
Thanks.

**Review by vshankar — APPROVED** [review]

**Comment by vshankar** [comment]
@joscollin You have an outstanding change request. Please approve/comment as necessary.

**Review by joscollin — APPROVED** [review]
The `Signed-off-by` looks good and build passed.

**Pull request merged**
