### PR TITLE
mgr/dashboard: Improve Notification sidebar

### PR DESCRIPTION
**Pull request by tspmelo**
Remove the external package and add custom scrollbar.

Fix random e2e tests.

Fixes: https://tracker.ceph.com/issues/43804
Fixes: https://tracker.ceph.com/issues/43593

Signed-off-by: Tiago Melo <tmelo@suse.com>

## Checklist
- [x] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by tspmelo** [comment]
Without changing any code I could not reproduce the e2e error in my env.
I will run the tests multiple times here to see if it happens again.

**Comment by votdev** [comment]
The layout does not fit for some error notifications.

Tested with Firefox 72.0.1.
Bildschirmfoto vom 2020-01-28 13-26-24

**Comment by Devp00l** [comment]
The notification page is still failing on Jenkins.

**Comment by tspmelo** [comment]
I'm still working on this.

**Comment by tspmelo** [comment]
PR is passing all tests now. ready to review.

**Comment by callithea** [comment]
> PR is passing all tests now. ready to review.

Would it be okay to trigger the dashboard e2e tests a few more times or did you already do that?
Also I tested your PR on my local env, the sidebar-related changes lgtm, but at the moment I'm struggling with running the e2e tests - most of the time I don't even get to the point where the "Notification page" tests start (only passed once so far) :/

**Comment by tspmelo** [comment]
@callithea It passed twice. I'm ok with running more times.

**Comment by tspmelo** [comment]
jenkins test dashboard

**Comment by tspmelo** [comment]
jenkins test dashboard

**Comment by tspmelo** [comment]
jenkins test dashboard

**Comment by tspmelo** [comment]
jenkins test dashboard

**Comment by tspmelo** [comment]
jenkins test dashboard

**Comment by tspmelo** [comment]
@votdev I was not able to reproduce the problem you mention, if you can please review the PR again.
otherwise it can be merged.

**Pull request merged**
