### PR TITLE
os/bluestore: show some additional osd/pool stats on fsck completion.

### PR DESCRIPTION
**Pull request by ifed01**
Sometime we might want to learn actual OSD utilization by means alternative to regular stats reporting.
This patch enables such an accounting during fsck. 
E.g. this could be helpful to investigate stats reporting discrepancies or something.
Relevant log output looks like the following:

... 2 bluestore(dev/osd0) _fsck_on_open Per-pool stats:
... 2 bluestore(dev/osd0) _fsck_on_open pool -1 -> (58 objects, 0 shared blobs, 278 omaps, 6798 bytes in omap keys, 52863 bytes in omap vals, 70038 bytes stored, 229376 bytes allocated)
... 2 bluestore(dev/osd0) _fsck_on_open pool 1 -> (3 objects, 0 shared blobs, 0 omaps, 0 bytes in omap keys, 0 bytes in omap vals, 459280 bytes stored, 462848 bytes allocated)
... 2 bluestore(dev/osd0) _fsck_on_open pool 2 -> (44 objects, 0 shared blobs, 0 omaps, 0 bytes in omap keys, 0 bytes in omap vals, 0 bytes stored, 0 bytes allocated)
... 1 bluestore(dev/osd0) _fsck_on_open \<\<\<FINISH\>\>\> with 0 errors, 0 warnings, 0 repaired, 0 remaining in 0.039815 seconds

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Comment by ifed01** [comment]
jenkins test make check

**Comment by ifed01** [comment]
jenkins test api

**Comment by ifed01** [comment]
jenkins test api

**Review by pereman2 — APPROVED** [review]

**Comment by yuriw** [comment]
This PR is under test in [https://tracker.ceph.com/issues/65798](https://tracker.ceph.com/issues/65798).

**Comment by NitzanMordhai** [comment]
Rados approved: https://tracker.ceph.com/projects/rados/wiki/MAIN#httpstrackercephcomissues65798

**Pull request merged**
