### PR TITLE
Lookup monitors through DNS, feature #14527

### PR DESCRIPTION
**Pull request by rjfd**
If no monitor host info is found in ceph.conf file or from CLI arguments, the construction of monmap fallbacks to query the DNS for SRV records with "ceph-mon" as the default service name.

The service name can be changed with the "mon_dns_srv_name" config option.

Ticket url: http://tracker.ceph.com/issues/14527

### CODE REVIEW

**Comment by rjfd** [comment]
I have implemented this feature on top of a 2 weeks old commit. I'm now merging the implementation with the recent commits from upstream.
I will make a new push when I finish the merging,

**Comment by tchaikov** [comment]
reviewed all the changes including the rgw part, seems it is just a refactory which moves the cname resolving functionality into the new `DNSResolver` class.

**Comment by rjfd** [comment]
Addressed all review comments and pushed the changes.

**Comment by rjfd** [comment]
Rebased with upstream master branch to solve conflicts.

**Comment by tchaikov** [comment]
@rjfd , could you squash the 4befe4f, 0be0c20, 2f55962, 7a0511b into the previous commits respectively? so it would be easier for reviewers. what do you think?

**Comment by rjfd** [comment]
I agree.
Already pushed the squashed commits.

**Comment by rjfd** [comment]
I addressed all the comments and pushed the new commit.

**Comment by tchaikov** [comment]
lgtm modulo the nits.

**Comment by tchaikov** [comment]
lgtm.

**Comment by tchaikov** [comment]
@yehudasa does the rgw part look good to you?

**Comment by jecluis** [comment]
The only thing I find missing - which I should have mentioned to @rjfd before - is a small mention of the new option on PendingReleaseNotes. Also would be nice to document this at some point.

**Comment by jecluis** [comment]
i.e., otherwise LGTM

**Comment by rjfd** [comment]
Updated PendingReleaseNotes.

**Comment by tchaikov** [comment]
@rjfd need rebase

**Comment by rjfd** [comment]
rebase on top of master done

**Comment by yehudasa** [comment]
@rjfd it's hard for me to sign off it. We don't have a good test coverage for this feature in rgw, and the diff is not as trivial due to code movement. @mattbenjamin maybe one of you guys can take a look at this one?

**Comment by mattbenjamin** [comment]
@yehudasa @rjfd I can verify it and merge it.  Unless otherwise directed, this will need to be for Kraken.

**Comment by mattbenjamin** [comment]
@athanatos just noticed pending-discussion; is there double about the basic idea?

**Comment by tchaikov** [comment]
@jecluis did @rjfd 's change passed the test?

@mattbenjamin @athanatos  maybe what we need is just a manual test for this very feature, and that's all?

**Comment by athanatos** [comment]
I don't have an opinion, I added the pending-discussion flag because it didn't look like there was consensus -- I didn't look too closely.

**Comment by rjfd** [comment]
@mattbenjamin @tchaikov @jecluis I rebased on top of master. Now the PR is ready again for reviewing or testing. Thanks.

**Comment by tchaikov** [comment]
@rjfd, looks good to me. just need to run it through the integration test suite. and it would be ideal if @mattbenjamin could verify it also.

**Pull request merged**
