### PR TITLE
nautilus: librbd: async open/close should free ImageCtx before issuing callback

### PR DESCRIPTION
**Pull request by dillaman**
http://tracker.ceph.com/issues/39428

### CODE REVIEW

**Comment by smithfarm** [comment]
@dillaman Does this build for you?

**Comment by dillaman** [comment]
retest this please

**Comment by smithfarm** [comment]
`159/171 Test #162: unittest_rgw_dmclock_scheduler ..........***Failed    0.34 sec`

**Comment by smithfarm** [comment]
retest this please

**Comment by yuriw** [comment]
[wip-yuri3-testing-2019-05-28-2039-nautilus](https://trello.com/c/l4Xj7ECB/621-wip-yuri3-testing-2019-05-28-2039-nautilus)

**Pull request merged**
