### PR TITLE
infernalis: RPM packaging puts ceph_daemon.py in ceph-common, Debian packaging puts it in ceph (should be ceph-common) 

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/15048

### CODE REVIEW

**Comment by smithfarm** [comment]
@FlorentCoppint Please review.

**Comment by smithfarm** [comment]
@ktdreyer @alimaredia Please review.

**Comment by smithfarm** [comment]
@ktdreyer It implements the "daemon" subcommand of the "ceph" executable.

**Comment by smithfarm** [comment]
I should have considered that last comment more carefully. Looking at the code, I see now that `ceph_daemon.py` exports `DaemonWatcher` and `admin_socket`. These are used to implement the `daemonperf` and `daemon` subcommands, respectively.

**Comment by dachary** [comment]
infernalis has been EOL for a few months now, there does not seem to be a need for another release, even for upgrade purposes

**Pull request closed without merging**
