### PR TITLE
quincy: qa: add subvolume option flavors

### PR DESCRIPTION
**Pull request by mchangir**
backport tracker: https://tracker.ceph.com/issues/59201

---

backport of https://github.com/ceph/ceph/pull/45556
parent tracker: https://tracker.ceph.com/issues/54317

this backport was staged using ceph-backport.sh version 16.0.0.6848
find the latest version at https://github.com/ceph/ceph/blob/main/src/script/ceph-backport.sh

### CODE REVIEW

**Comment by mchangir** [comment]
pulled in commit from #51049

**Comment by vshankar** [comment]
jenkins retest this please

**Comment by vshankar** [comment]
@mchangir what about the failing dashboard jenkins test?

**Comment by mchangir** [comment]
jenkins test dashboard cephadm

**Comment by mchangir** [comment]
> @mchangir what about the failing dashboard jenkins test?

Supposedly `ceph dashboard cephadm e2e tests` is **not a required** test to pass

**Comment by vshankar** [comment]
jenkins test dashboard cephadm

**Comment by mchangir** [comment]
removed spurious space

**Comment by yuriw** [comment]
jenkins test make check

**Comment by vshankar** [comment]
jenkins test make check

**Comment by vshankar** [comment]
I guess this is ready to merge and we just forgot to merge it after triggering jenkins tests.

**Comment by vshankar** [comment]
@mchangir this seems to be causing failures like: /a/yuriw-2023-09-27_19:23:53-fs-wip-yuri-testing-2023-09-27-0906-quincy-distro-default-smithi/7403437

```
Traceback (most recent call last):
  File "/home/teuthworker/src/git.ceph.com_teuthology_54e62bcbac4e53d9685e08328b790d3b20d71cae/teuthology/run_tasks.py", line 109, in run_tasks
    manager.__enter__()
  File "/usr/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/home/teuthworker/src/github.com_ceph_ceph-c_471b6dfd2d990acf7f03e5d073b84a1b39d1ad28/qa/tasks/kclient.py", line 112, in task
    kernel_mount.mount(mntopts=client_config.get('mntopts', []))
  File "/home/teuthworker/src/github.com_ceph_ceph-c_471b6dfd2d990acf7f03e5d073b84a1b39d1ad28/qa/tasks/cephfs/kernel_mount.py", line 54, in mount
    retval = self._run_mount_cmd(mntopts, check_status)
  File "/home/teuthworker/src/github.com_ceph_ceph-c_471b6dfd2d990acf7f03e5d073b84a1b39d1ad28/qa/tasks/cephfs/kernel_mount.py", line 69, in _run_mount_cmd
    mount_cmd = self._get_mount_cmd(mntopts)
  File "/home/teuthworker/src/github.com_ceph_ceph-c_471b6dfd2d990acf7f03e5d073b84a1b39d1ad28/qa/tasks/cephfs/kernel_mount.py", line 118, in _get_mount_cmd
    stx_opt = self._make_mount_cmd_old_or_new_style()
  File "/home/teuthworker/src/github.com_ceph_ceph-c_471b6dfd2d990acf7f03e5d073b84a1b39d1ad28/qa/tasks/cephfs/kernel_mount.py", line 91, in _make_mount_cmd_old_or_new_style
    assert(self.cephfs_mntpt)
AssertionError
```

We should revert this change for now.

**Comment by vshankar** [comment]
I merged this ~3 weeks ago since it was marked TESTED and tageed ready-to-merge.

**Pull request merged**
