### PR TITLE
mgr/dashboard: Clean up HTML

### PR DESCRIPTION
**Pull request by ishanrai05**
Fixes: https://tracker.ceph.com/issues/44848

Signed-off-by: Ishan Rai <ishanrai05@gmail.com>

## Checklist
- [x] References tracker ticket
- [x] Updates documentation if necessary
- [x] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by ishanrai05** [comment]
Screenshot from 2020-03-31 16-54-31

**Comment by s0nea** [comment]
jenkins test dashboard

**Comment by tspmelo** [comment]
There are a few more code that can be cleaned up.

**Comment by callithea** [comment]
jenkins test dashboard

**Comment by callithea** [comment]
jenkins test dashboard

**Comment by callithea** [comment]
jenkins test dashboard

**Comment by ishanrai05** [comment]
I figured a lot of files where similar changes could be made, I will update the patch.

**Comment by ishanrai05** [comment]
`modal-footers` have a `justify-content: flex-end` so we don't need `text-right` or `float-right` with them. At other places in footers, I have simply removed the `button-group` CSS class because it is not defined anywhere.

@tspmelo This is ready for review,

**Comment by tspmelo** [comment]
lgtm.
Please update the commit message:
- Use a shorter title, you can use the one I updated on this PR. 
- On the message body you can quickly mention that you cleaned up all the footer and the component.

**Comment by LenzGr** [comment]
jenkins test dashboard

**Pull request merged**
