### PR TITLE
Backport ceph-objectstore-tool changes to firefly

### PR DESCRIPTION
**Pull request by dzafman**
This passes unit test and the ceph-qa-suite test tasks/ceph_objectstore_tool.py.

Currently scheduled rados:thrash suite

Requires ceph/ceph-qa-suite#361 to test.

### CODE REVIEW

**Comment by dzafman** [comment]
rados:thrash results
139 PASSED
26 fail wget failures - infrastructure
1 dead - timeout trying to copy an export file - infrastructure
1 fail - unexplained ceph-objectstore-tool SIGSEGV doing list-pgs (no core or log found)
1 running hung because /dev/sdg failed on burnupi50

**Comment by dachary** [comment]
@dzafman it's in the branch firefly-backport integration branch now

**Comment by dachary** [comment]
@dzafman a rados suite came back green ( http://tracker.ceph.com/issues/11090#teuthology-run-b0d9b862d7f1a9a98cf4b41ff7cb0eb428740633-march-2015 ). Good to merge in my opinion. Since it's a very large patch series, could you confirm that it's ready to merge in your opinion ?

**Comment by dzafman** [comment]
@dachary @athanatos The only issue I found in my testing using the ceph/ceph-qa-suite#361 is a race with pool deletion causing a ceph-objectstore-tool --op list-pgs to SIGSEGV.  I'll file a bug report.  This is ready to merge subject to code review.  I think Sam should look at it, but another set of eyes would be nice.

A suggested way to code review would be as follows.  Examine all changes NOT in src/tools/ceph_objectstore_tool.cc.  Then check-out the differences in the tool with git diff hammer wip-cot-firefly -- src/tools/ceph_objectstore_tool.cc.   All the changes should be to newer features/changes like map CRC checking, removal changes, META_COLL, NO_SHARD etc...

**Pull request merged**
