### PR TITLE
nautilus: rgw: add quota enforcement to CopyObj

### PR DESCRIPTION
**Pull request by smithfarm**
backport tracker: https://tracker.ceph.com/issues/45925

---

backport of https://github.com/ceph/ceph/pull/35073
parent tracker: https://tracker.ceph.com/issues/45382

this backport was staged using ceph-backport.sh version 15.1.1.389
find the latest version at https://github.com/ceph/ceph/blob/master/src/script/ceph-backport.sh

### CODE REVIEW

**Comment by smithfarm** [comment]
```
/home/jenkins-build/build/workspace/ceph-pull-requests/src/rgw/rgw_op.cc: In member function 'virtual void RGWCopyObj::execute()':
/home/jenkins-build/build/workspace/ceph-pull-requests/src/rgw/rgw_op.cc:5069:21: error: 'class RGWRados' has no member named 'getRados'
 5069 |     op_ret = store->getRados()->get_obj_state(s->obj_ctx, src_bucket_info, src_obj,
      |                     ^~~~~~~~
/home/jenkins-build/build/workspace/ceph-pull-requests/src/rgw/rgw_op.cc:5075:21: error: 'class RGWRados' has no member named 'getRados'
 5075 |     op_ret = store->getRados()->check_quota(dest_bucket_info.owner,
      |                     ^~~~~~~~
src/rgw/CMakeFiles/rgw_common.dir/build.make:1578: recipe for target 'src/rgw/CMakeFiles/rgw_common.dir/rgw_op.cc.o' failed
make[3]: *** [src/rgw/CMakeFiles/rgw_common.dir/rgw_op.cc.o] Error 1
CMakeFiles/Makefile2:26117: recipe for target 'src/rgw/CMakeFiles/rgw_common.dir/all' failed
make[2]: *** [src/rgw/CMakeFiles/rgw_common.dir/all] Error 2
```

**Comment by smithfarm** [comment]
```
In file included from /home/jenkins-build/build/workspace/ceph-pull-requests/src/rgw/rgw_op.cc:26:
/home/jenkins-build/build/workspace/ceph-pull-requests/src/rgw/rgw_rados.h:2036:7: note: candidate: 'int RGWRados::get_obj_state(RGWObjectCtx*, const RGWBucketInfo&, const rgw_obj&, RGWObjState**, bool, bool)'
 2036 |   int get_obj_state(RGWObjectCtx *rctx, const RGWBucketInfo& bucket_info, const rgw_obj& obj, RGWObjState **state,
      |       ^~~~~~~~~~~~~
/home/jenkins-build/build/workspace/ceph-pull-requests/src/rgw/rgw_rados.h:2036:7: note:   candidate expects 6 arguments, 7 provided
/home/jenkins-build/build/workspace/ceph-pull-requests/src/rgw/rgw_rados.h:2038:7: note: candidate: 'int RGWRados::get_obj_state(RGWObjectCtx*, const RGWBucketInfo&, const rgw_obj&, RGWObjState**)'
 2038 |   int get_obj_state(RGWObjectCtx *rctx, const RGWBucketInfo& bucket_info, const rgw_obj& obj, RGWObjState **state) {
      |       ^~~~~~~~~~~~~
/home/jenkins-build/build/workspace/ceph-pull-requests/src/rgw/rgw_rados.h:2038:7: note:   candidate expects 4 arguments, 7 provided

src/rgw/CMakeFiles/rgw_common.dir/build.make:1578: recipe for target 'src/rgw/CMakeFiles/rgw_common.dir/rgw_op.cc.o' failed
make[3]: *** [src/rgw/CMakeFiles/rgw_common.dir/rgw_op.cc.o] Error 1
```

**Comment by smithfarm** [comment]
```
130/170 Test   #4: smoke.sh ................................***Failed  318.92 sec
```

**Comment by smithfarm** [comment]
jenkins test make check

**Comment by yuriw** [comment]
[wip-yuri2-testing-2020-07-20-1544-nautilus](https://trello.com/c/yeDOGUZS/970-wip-yuri2-testing-2020-07-20-1544-nautilus)

**Pull request merged**
