### PR TITLE
osdc/Objecter: fix relock race

### PR DESCRIPTION
**Pull request by liewegas**
In commit a863ae1c0fab636eabced0979889cbb3be74bf74 we tried
to fix a race but failed because we didn't update the
session pointer.  Add a proper test for this case with
a delay injection and fix the bug.

Fixes: http://tracker.ceph.com/issues/17942
Signed-off-by: Sage Weil <sage@redhat.com>

### CODE REVIEW

**Comment by liewegas** [comment]
@tchaikov mind looking?

**Comment by tchaikov** [comment]
no, looking.

**Comment by tchaikov** [comment]
the failed test is fixed by #12235

**Comment by liewegas** [comment]
retest this please

**Pull request merged**
