### PR TITLE
qa: remove obsolete deactivate routines

### PR DESCRIPTION
**Pull request by batrick**

### CODE REVIEW

**Comment by batrick** [comment]
https://tracker.ceph.com/projects/cephfs/wiki/Master#2021-June-03

**Comment by batrick** [comment]
ping @ceph/cephfs

**Review by vshankar — COMMENTED** [review]
LGTM

**Comment by batrick** [comment]
@vshankar need approval to merge :)

**Review by vshankar — APPROVED** [review]

**Comment by batrick** [comment]
https://tracker.ceph.com/projects/cephfs/wiki/Master#2021-June-13

**Pull request merged**
