### PR TITLE
client: always return ESTALE directly in handle_reply

### PR DESCRIPTION
**Pull request by lxbsz**
If MDS return ESTALE, that means the MDS have already iterated all the possible active MDSes or the inode is under purging.

So no need to retry in auth MDS and will just return ESTALE directly.

Fixes: https://tracker.ceph.com/issues/53504
Signed-off-by: Xiubo Li <xiubli@redhat.com>

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [x] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by lxbsz** [comment]
We need to fix the kclient too.

**Comment by lxbsz** [comment]
jenkins retest this please

**Review by batrick — APPROVED** [review]
Makes sense to me. Were you able to reproduce with a test-case?

**Comment by batrick** [comment]
jenkins test make check

**Comment by lxbsz** [comment]
> Makes sense to me. Were you able to reproduce with a test-case?

Not yet, locally I will try it later and try to add one test case for it.

**Comment by lxbsz** [comment]
吴羡 reported a same bug in his product use case, and he can see the client stuck almost every 2 weeks.

I went through the MDS side code again, just guess that it must be the opened inode has missed from the MDCache after recovery, and the Openfiletable will be commited to the disk in the tick() thread. That means once the MDS crashes in theory there has chances that the openfile journal may lose. So in the replacing MDS it won't find the inode.

And let him tried to list all the sub-files or sub-direcotries from the mountpoint. And the bug resolved immediately. Because when listing from the mountpoint it will load all the file into the MDCache.

I have updated the PR and after checking from all the peers if it still fails will try to open the ino and load it from the disk and retry the request again.

**Review by mchangir — APPROVED** [review]
LGTM

**Review by vshankar — COMMENTED** [review]
LGTM

**Pull request merged**
