### PR TITLE
rgw: Backport of cache fixes to Jewel

### PR DESCRIPTION
**Pull request by adamemerson**

### CODE REVIEW

**Comment by mattbenjamin** [comment]
those are some whopper lambdas :)

**Comment by mattbenjamin** [comment]
http://pulpito.ceph.com/mbenjamin-2017-12-05_10:55:19-rgw-jewel-cache-fixes---basic-smithi/

**Comment by cbodley** [comment]
this will need a backport tracker ticket

**Comment by tchaikov** [comment]
retest this please.

**Comment by adamemerson** [comment]
Jenkins, retest this please.

**Pull request closed without merging**
