### PR TITLE
 qa: reduce mon-client-hunt-interval-max-multiple to 2

### PR DESCRIPTION
**Pull request by tchaikov**
in hope to address http://pulpito.ceph.com/kchai-2017-10-12_16:33:11-rados-wip-kefu-testing-2017-10-12-2302-distro-basic-mira/

### CODE REVIEW

**Comment by tchaikov** [comment]
http://pulpito.ceph.com/kchai-2017-10-13_09:13:45-rados-wip-kefu-testing-2017-10-13-1223-distro-basic-mira/

**Comment by tchaikov** [comment]
@jecluis mind taking a look?

**Comment by tchaikov** [comment]
@gregsfortytwo @jecluis mind taking a look?

**Comment by gregsfortytwo** [comment]
jenkins test this please

**Pull request merged**
