### PR TITLE
mds: validate inotable according session prealloc inos after replay done

### PR DESCRIPTION
**Pull request by yunfeiguan**
Due to less rigorous inotable save mechanism the inotable may not be
what it should be. So we need validate it after replay done prevent
it from occuring a core or happen inode reuse case after start success.

Fixes: http://tracker.ceph.com/issues/16842
Signed-off-by: Guan yunfei <yunfei.guan@xtaotech.com>

### CODE REVIEW

**Comment by ukernel** [comment]
I don't think mds should repair inconsistence  automatically. mds should go to damage state and let admin to repair it

**Comment by yunfeiguan** [comment]
How should the administrator fix this problem? If the repair principle is the same as mine, why don't we let it become automatic? Moreover not all users can fix the problem mamually.

**Comment by yunfeiguan** [comment]
I think  i had located the root cause of this bug. Mds will prealloc mds_client_prealloc_ino inos to every session and will record this action to disk.But there is a risk mds may record the old free table to disk.
1.create a file and prealloc 1000 inos to session and projected_version++
2.try_to_expire coming update the inotable(note the free table is old)
3. write create journal callback update free table, but it doesn't have opportunity to update if the mds restart before nest prealloc operation happened.

So i think we should fix this bug or repair mds inotable after this bug occur. What do you think about it?

**Comment by ukernel** [comment]
I don't see any problem in the events you described.  inotable that was save to disk can be a little old, but any new modification of inotable should be recorded in journal

**Comment by ukernel** [comment]
No. if session prealloc_inos has bad information, it may consume all free ino number

**Comment by batrick** [comment]
@ukernel @yunfeiguan what are the next steps to get this PR merged?

**Comment by ukernel** [comment]
I suggest close this PR

**Pull request closed without merging**
