### PR TITLE
ceph-disk: implement prepare --no-locking

### PR DESCRIPTION
**Pull request by dachary**

### CODE REVIEW

**Comment by dachary** [comment]
<pre>teuthology-suite -k distro --verbose --suite ceph-disk --ceph wip-ceph-disk-lock  --machine-type vps</pre>

* **running** http://pulpito.ceph.com/loic-2017-04-22_09:43:16-ceph-disk-wip-ceph-disk-lock-distro-basic-vps/

**Comment by dachary** [comment]
@tchaikov thanks for the quick review :-) Removing the needs-qa because I still have doubts about not locking at all. IIRC there are race conditions even when preparing a single device. The global lock is clearly overkill but safe. However it may be necessary to have a per-device prepare lock so that activate does not happen until the prepare lock is lifted for a given partition *and* its associated auxiliary devices (journal etc.).

**Comment by dachary** [comment]
Hum, I remembered incorrectly. The activate lock is the one that is tricky, the prepare lock should not cause problems. Let see how the ceph-disk suite behaves.

**Comment by tchaikov** [comment]
all but one tests passed at http://pulpito.ceph.com/loic-2017-04-22_09:43:16-ceph-disk-wip-ceph-disk-lock-distro-basic-vps/

rerunning the failed one at http://pulpito.ceph.com/kchai-2017-04-25_16:12:01-ceph-disk-wip-ceph-disk-lock---basic-vps/.

**Comment by dachary** [comment]
The one that failed was because of infrastructure noise.

**Comment by tchaikov** [comment]
all three tests in ceph-disk suite passed.

**Comment by yuriw** [comment]
http://pulpito.ceph.com/yuriw-2017-04-25_19:49:20-rados-wip-yuri-testing2_2017_4_26-distro-basic-smithi/

http://pulpito.ceph.com/yuriw-2017-04-25_19:49:20-rados-wip-yuri-testing2_2017_4_26-distro-basic-smithi/

==============
CEPH_DISK

http://pulpito.ceph.com/yuriw-2017-04-26_03:20:49-ceph-disk-wip-yuri-testing2_2017_4_26-distro-basic-vps/

**Pull request merged**
