### PR TITLE
mgr/cephadm: disable dashboard's grafana cert ssl_verify if we generate it

### PR DESCRIPTION
**Pull request by liewegas**
This will help dashboard work out of the box.

Signed-off-by: Sage Weil <sage@redhat.com>

### CODE REVIEW

**Comment by sebastian-philipp** [comment]
#31129

**Comment by sebastian-philipp** [comment]
missed this PR due to the missing cephadm tag

**Comment by callithea** [comment]
- [pkg build](https://shaman.ceph.com/builds/ceph/wip-laura-testing-34223/)
- [QA run](http://pulpito.ceph.com/laura-2020-04-03_13:15:32-rados:cephadm-wip-laura-testing-34223-distro-basic-smithi/) (scheduled with `--suite rados/cephadm` and `--subset 1111/9999`)
- [QA run](http://pulpito.ceph.com/laura-2020-04-03_13:19:18-rados-wip-laura-testing-34223-distro-basic-smithi/) (scheduled with `--suite rados --filter cephadm` and `--subset 1111/9999`)

**Comment by sebastian-philipp** [comment]
qa run crashed and burned with `RuntimeError: Failed command: /bin/podman pull quay.io/ceph-ci/ceph:wip-sage4-testing-2020-03-19-1456`

**Comment by sebastian-philipp** [comment]
@callithea : #34406 was merged. want to retest?

**Comment by callithea** [comment]
> @callithea : #34406 was merged. want to retest?

Thanks for letting me know, @sebastian-philipp! Sure, will re-run it through QA!

**Pull request merged**
