### PR TITLE
Wip undo pulls 10312 10514

### PR DESCRIPTION
**Pull request by dzafman**
Pull requests 10312 and 10514 break ceph_objectstore_tool.py test which vstarts with -n and vstarts without -n to bring back cluster from previous state.  These changes break that.

### CODE REVIEW

**Comment by dzafman** [comment]
@wjwithagen When I revert #10312 and #10514  the test/ceph_objectstore_tool.py test works again.  Sorry that I haven't figured out what the problem is, but this tests need to start and stop the daemons using the same config and filestore.

**Comment by dzafman** [comment]
The Jenkins test failure is fixed by #10535

**Comment by wjwithagen** [comment]
@dzafman 
If you look at the error message that it generates, the path is actually 115 characters.
So that is 8 (or 9 with \0) more than allowed.
Which I think is due to the rather long Jenkins-prepath.
But it could be fixed by using a less long testdir path.
Now it is:
ceph_objectstore_tool_dir/out/client.admin.25541.asok

perhaps:
objectstore_dir/out/client.admin.25541.asok

Otherwise you'd have to fix other tools and start putting the sockets in /tmp.

**Comment by wjwithagen** [comment]
@dzafman @batrick @yuriw 
 #10514 is a "simple" fix to actually keep going if the config file is not there to be deleted. And was the first obstacle to get ceph_objectstore_tool.py to start running.
#10312 is a more invasive commit, but even there I don't really see anything that extents the path of CEPH_ROOT
So it is a puzzle why we do not get the path to long error right now.

sad thing is also that vstart does not really report error to ceph_objectstore_tool.py when it fails, and then the whole script just runs into scrambles. I Just got DONE, even when it could not delete the config file.

**Comment by batrick** [comment]
Looking into this.

**Comment by batrick** [comment]
#10543 resolves this. Closing.

**Comment by batrick** [comment]
See also:

**Pull request closed without merging**
