### PR TITLE
mon: skip crush smoke test when running under valgrind

### PR DESCRIPTION
**Pull request by liewegas**
Valgrind tries to analyze the forked child process, and is slow enough
that it times out pretty reliably.

http://tracker.ceph.com/issues/20602

### CODE REVIEW

**Comment by liewegas** [comment]
Note this will likely get rebased on top of https://github.com/ceph/ceph/pull/16211 with the config option marked DEV.

**Comment by liewegas** [comment]
http://pulpito.ceph.com/sage-2017-07-15_01:35:06-rados-wip-sage-testing-distro-basic-smithi/

**Comment by liewegas** [comment]
retest this please

**Comment by tchaikov** [comment]
retest this please

**Pull request merged**
