### PR TITLE
luminous: client: dirty caps may never get the chance to flush

### PR DESCRIPTION
**Pull request by batrick**
http://tracker.ceph.com/issues/22696

### CODE REVIEW

**Comment by taodd** [comment]
@batrick this pr depends on one of your PR.
  cap_list is introduced in your PR

**Comment by batrick** [comment]
@taodd thanks i'll fix it.

**Comment by batrick** [comment]
@taodd  please take another look.

**Comment by ukernel** [comment]
there is  a leftover "cap_list.push_back(&in->cap_item);"  in add_update_cap()

**Comment by batrick** [comment]
Thanks @ukernel, please take another look.

**Comment by ukernel** [comment]
The updated code looks exact the same as the code in wip-luminous-integration-20180530

http://pulpito.ceph.com/?branch=wip-luminous-integration-20180530

**Pull request merged**
