### PR TITLE
osd: When deep-scrub errors present upgrade regular scrubs

### PR DESCRIPTION
**Pull request by dzafman**
Previously, if a weekly deep-scrub found errors the next daily scrub
would cause the deep-scrub information to be removed.

Signed-off-by: David Zafman <dzafman@redhat.com>

### CODE REVIEW

**Comment by athanatos** [comment]
That seems reasonable to me. LGTM

**Comment by dzafman** [comment]
Marked as DNM because the new tests case is in osd-scrub-repair.sh which is currently switched off.

**Comment by dzafman** [comment]
Tests passed.

http://pulpito.ceph.com/dzafman-2016-12-10_15:31:06-rados-wip-zafman-testing-distro-basic-smithi   7 failures
http://pulpito.ceph.com/dzafman-2016-12-12_16:51:43-rados-wip-zafman-testing-distro-basic-smithi   2 failures remain from previous 7
http://pulpito.ceph.com/dzafman-2016-12-13_15:35:36-rados-wip-zafman-testing-distro-basic-smithi/ 1 failure from previous 2 caused by Bluestore

**Comment by dzafman** [comment]
The additional osd-scrub-repair.sh sub-test won't run until we re-enable the script.

**Comment by dzafman** [comment]
@athanatos Ready for review.

**Comment by athanatos** [comment]
Oh, it did.

**Pull request merged**
