### PR TITLE
quincy: log: writes to stderr (pipe) may not be atomic

### PR DESCRIPTION
**Pull request by batrick**
https://tracker.ceph.com/issues/58188

### CODE REVIEW

**Comment by batrick** [comment]
jenkins test make check

**Comment by batrick** [comment]
jenkins test make check

**Comment by batrick** [comment]
jenkins test make check

**Comment by batrick** [comment]
https://tracker.ceph.com/projects/cephfs/wiki/Quincy#2023-Apr-2124

**Review by vshankar — APPROVED** [review]

**Pull request merged**
