### PR TITLE
MClientRequest: properly handle ceph_mds_request_head_legacy for ext_num_retry, ext_num_fwd, owner_uid, owner_gid

### PR DESCRIPTION
**Pull request by mihalicyn**
Fix for https://github.com/ceph/ceph/pull/53139#issuecomment-1771388202

Reproducer:
1. use old enough Linux kernel ceph client (Linux kernel v5.4 works fine for this purpose)
2. mount ceph on `/mnt/ceph`
3. `touch /mnt/ceph/123`
4. MDS will crash with assertion on `ceph_assert(_inode->gid != (unsigned)-1)`.

https://tracker.ceph.com/issues/63288

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [x] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [x] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by mihalicyn** [comment]
cc @lxbsz

**Comment by mihalicyn** [comment]
jenkins retest this please

**Comment by mihalicyn** [comment]
I'm not sure if we want to incorporate fix from https://github.com/ceph/ceph/pull/54121 to this PR.

**Comment by mihalicyn** [comment]
jenkins test make check arm64

**Review by lxbsz — APPROVED** [review]
Good catch. LDTM.

**Comment by mihalicyn** [comment]
jenkins test make check arm64

**Comment by mihalicyn** [comment]
jenkins test api

**Comment by mihalicyn** [comment]
Rebased and added "Fixes" tags to the commit descriptions.

**Comment by mihalicyn** [comment]
jenkins test make check arm64
jenkins test api

**Comment by mihalicyn** [comment]
jenkins test api

**Comment by mihalicyn** [comment]
jenkins test make check arm64

**Comment by mihalicyn** [comment]
jenkins test make check arm64

**Comment by mihalicyn** [comment]
jenkins test make check arm64

**Comment by mihalicyn** [comment]
cc @batrick

**Review by batrick — APPROVED** [review]

**Comment by mihalicyn** [comment]
cc @vshankar

**Review by vshankar — APPROVED** [review]
LGTM

**Review by rishabh-d-dave — APPROVED** [review]
CephFS integration tests were successful - https://tracker.ceph.com/projects/cephfs/wiki/Main#7-Nov-2023

**Pull request merged**
