### PR TITLE
reef: rgw: fix consistency bug with OLH objects

### PR DESCRIPTION
**Pull request by cfsnyder**
backport tracker: https://tracker.ceph.com/issues/62065

---

backport of https://github.com/ceph/ceph/pull/51700
parent tracker: https://tracker.ceph.com/issues/61359

this backport was staged using ceph-backport.sh version 16.0.0.6848
find the latest version at https://github.com/ceph/ceph/blob/main/src/script/ceph-backport.sh

### CODE REVIEW

**Comment by cfsnyder** [comment]
jenkins test make check

**Comment by cbodley** [comment]
jenkins test make check

**Comment by cbodley** [comment]
passed qa in https://pulpito.ceph.com/cbodley-2023-07-18_20:26:56-rgw-pr-52525-distro-default-smithi/

**Review by cbodley — APPROVED** [review]

**Comment by cbodley** [comment]
'make check' is busted because of python stuff, tracked in https://tracker.ceph.com/issues/62082

**Comment by yuriw** [comment]
jenkins test make check

**Comment by cbodley** [comment]
jenkins test make check

**Comment by cbodley** [comment]
jenkins test make check

**Comment by yuriw** [comment]
jenkins test make check

**Comment by yuriw** [comment]
jenkins test make check

**Pull request merged**
