### PR TITLE
pacific: os/bluestore: proper override rocksdb::WritableFile::Allocate

### PR DESCRIPTION
**Pull request by ifed01**
Failing to do that makes BlueFS file frgmentation higher.

backport of https://github.com/ceph/ceph/pull/50469

backport tracker: https://tracker.ceph.com/issues/61309
parent tracker: https://tracker.ceph.com/issues/58966

Signed-off-by: Igor Fedotov <igor.fedotov@croit.io>
(cherry picked from commit 2d8b9e9ed58bca4917b90ea5eaa43264a89dff75)

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Review by aclamk — APPROVED** [review]

**Comment by sseshasa** [comment]
@ifed01  The following teuthology ObjectStore test https://pulpito.ceph.com/yuriw-2023-07-27_22:37:12-rados-wip-yuri6-testing-2023-07-24-0819-pacific-distro-default-smithi/7354890 failed.

The following tests failed: ObjectStore/StoreTestSpecificAUSize.SpilloverFixedTest and
ObjectStore/StoreTestSpecificAUSize.SpilloverFixed2Test. Can you please check and confirm if the failure is related to this PR?

I will remove the relevant test tag and 'needs-qa' label for now. Please add the 'needs-qa' label back once the PR is ready for a re-test.

Alternatively, if the failure is unrelated, a new tracker may be raised for the above failure and this PR may be merged. Please update accordingly.

**Comment by ifed01** [comment]
> @ifed01 The following teuthology ObjectStore test https://pulpito.ceph.com/yuriw-2023-07-27_22:37:12-rados-wip-yuri6-testing-2023-07-24-0819-pacific-distro-default-smithi/7354890 failed.
> 

@sseshasa - looks like this PR is a culprit. I adjusted some test cases to reflect the changes. Ready to another QA round.

**Comment by ifed01** [comment]
jenkins test make check

**Comment by ifed01** [comment]
jenkins test api

**Comment by sseshasa** [comment]
> @sseshasa - looks like this PR is a culprit. I adjusted some test cases to reflect the changes. Ready to another QA round.

@ifed01 Sure, this and #51418  will go through another QA round.

**Comment by ifed01** [comment]
jenkins test make check

**Comment by ifed01** [comment]
jenkins test api

**Comment by ljflores** [comment]
Rados approved: https://tracker.ceph.com/projects/rados/wiki/PACIFIC#httpstrellocomc8HALLv9T1813-wip-yuri6-testing-2023-08-03-0807-pacific-old-wip-yuri6-testing-2023-07-24-0819-pacific2-old-wip-yuri6-testing-2023-07-24-0819-p

**Pull request merged**
