### PR TITLE
luminous: MDSMonitor: mons should reject misconfigured mds_blacklist_interval

### PR DESCRIPTION
**Pull request by shinobu-x**
http://tracker.ceph.com/issues/21948

### CODE REVIEW

**Comment by shinobu-x** [comment]
test this please

**Comment by smithfarm** [comment]
If @tchaikov agrees, I would prefer to cherry-pick https://github.com/ceph/ceph/commit/3704fe283b606737533d62a082337381b95bdbd9 into this PR to avoid the conflict (and all future similar conflicts).

**Comment by tchaikov** [comment]
@smithfarm yeah, good idea!

**Comment by smithfarm** [comment]
Superseded by https://github.com/ceph/ceph/pull/19871

**Pull request closed without merging**
