### PR TITLE
mgr/dashboard: Bug Fix Error on Mgr Dashboard NFS

### PR DESCRIPTION
**Pull request by NurFaizin**
This PR fixes error on NFS Ganesha management dashboard that throws an error when request daemon list.

Fixes: https://tracker.ceph.com/issues/39709
Signed-off-by: Nur Faizin <nur.faizin91@gmail.com>

### CODE REVIEW

**Comment by sebastian-philipp** [comment]
is there a test that verifies this fix?

**Comment by tchaikov** [comment]
retest this please.

**Comment by sebastian-philipp** [comment]
Thanks for the fix. Could you please add a `Signed-off-by` line to your commit?

**Comment by NurFaizin** [comment]
Just added sign and prefix.

**Comment by sebastian-philipp** [comment]
jenkins test dashboard

**Comment by ricardoasmarques** [comment]
jenkins retest this please

**Comment by ricardoasmarques** [comment]
jenkins retest this please

**Comment by ricardoasmarques** [comment]
jenkins retest this please

**Comment by ricardoasmarques** [comment]
jenkins test make check

**Comment by callithea** [comment]
Unfortunately the QA run failed (but I don't think it's related to the PR):
http://pulpito.ceph.com/laura-2019-05-17_12:28:45-rados:mgr-wip-lpaduano-testing-28075-distro-basic-smithi/
Some of the test failures are already tracked here:
- https://tracker.ceph.com/issues/39648

**Comment by callithea** [comment]
jenkins test make check

**Comment by callithea** [comment]
jenkins test make check

**Comment by LenzGr** [comment]
retest this please

**Comment by callithea** [comment]
QA run was successful:
http://pulpito.ceph.com/laura-2019-05-23_07:20:49-rados:mgr-wip-lpaduano-testing-27945-28075-distro-basic-smithi/

**Comment by LenzGr** [comment]
Thank you for your contribution, @NurFaizin !

**Pull request merged**
