### PR TITLE
os/bluestore: Unify on preadv for io_uring and future refactor.

### PR DESCRIPTION
**Pull request by markhpc**
We may want to do a much bigger refactor of KernelDevice and ceph_aio for io_uring, but this is a first step to unify on preadv since io_uring doesn't support pread which is a problem for https://github.com/ceph/ceph/pull/27392.

Signed-off-by: Mark Nelson <mnelson@redhat.com>

- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by markhpc** [comment]
Performance results in the works to make sure this doesn't cause any regressions.

**Comment by markhpc** [comment]
retest this please

**Comment by markhpc** [comment]
Performance tests did not appear to show significant performance variation with using preadv vs pread:

https://docs.google.com/spreadsheets/d/184bA08AqEQeNPuhfyD4aUPnmYj76KV3v6s8FTjEJxKI/edit?usp=sharing

**Comment by tchaikov** [comment]
- http://pulpito.ceph.com/kchai-2019-05-27_10:18:11-rados-wip-kefu-testing-2019-05-27-1206-distro-basic-smithi/
- http://pulpito.ceph.com/kchai-2019-05-28_01:35:41-rados-wip-kefu-testing-2019-05-27-1206-distro-basic-mira/

failures tracked by

- http://tracker.ceph.com/issues/23947
- http://tracker.ceph.com/issues/39644

**Pull request merged**
