### PR TITLE
mgr/dashboard: use relative font sizes

### PR DESCRIPTION
**Pull request by ishanrai05**
Fixes: https://tracker.ceph.com/issues/38890

Signed-off-by: Ishan Rai <ishanrai05@gmail.com>

## Checklist
- [x] References tracker ticket
- [x] Updates documentation if necessary
- [x] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by ishanrai05** [comment]
jenkins test dashboard

**Comment by ishanrai05** [comment]
@tspmelo Hi. Do we want to use `relative font sizes` or `responsive font sizes`?

**Comment by ishanrai05** [comment]
jenkins test make check
jenkins test dashboard backend
jenkins test docs

**Comment by ishanrai05** [comment]
jenkins test make check

**Comment by ishanrai05** [comment]
jenkins test make check

**Comment by ishanrai05** [comment]
jenkins test dashboard backend

**Comment by ishanrai05** [comment]
jenkins test docs

**Comment by ishanrai05** [comment]
jenkins test make check

**Comment by ishanrai05** [comment]
jenkins test make check

**Comment by ishanrai05** [comment]
jenkins test make check

**Comment by votdev** [comment]
Hmmm, what about https://mindtheshift.wordpress.com/2015/04/02/r-i-p-rem-viva-css-reference-pixel/

**Pull request merged**
