### PR TITLE
quincy: qa: Fix test_subvolume_snapshot_info_if_orphan_clone

### PR DESCRIPTION
**Pull request by kotreshhr**
backport tracker: https://tracker.ceph.com/issues/57722

---

backport of https://github.com/ceph/ceph/pull/47991
backport of https://github.com/ceph/ceph/pull/48642
parent tracker: https://tracker.ceph.com/issues/57446

this backport was staged using ceph-backport.sh version 16.0.0.6848
find the latest version at https://github.com/ceph/ceph/blob/main/src/script/ceph-backport.sh

### CODE REVIEW

**Comment by mchangir** [comment]
@yuriw this PR got missed in the NEW BATCH of PRs
please include it again in another run

**Comment by kotreshhr** [comment]
The testcase is failed because of the following.

```
2022-10-18T04:59:36.357 INFO:tasks.cephfs_test_runner:======================================================================
2022-10-18T04:59:36.358 INFO:tasks.cephfs_test_runner:ERROR: test_subvolume_snapshot_info_if_orphan_clone (tasks.cephfs.test_volumes.TestSubvolumeSnapshotClones)
2022-10-18T04:59:36.358 INFO:tasks.cephfs_test_runner:----------------------------------------------------------------------
2022-10-18T04:59:36.358 INFO:tasks.cephfs_test_runner:Traceback (most recent call last):
2022-10-18T04:59:36.359 INFO:tasks.cephfs_test_runner:  File "/home/teuthworker/src/github.com_ceph_ceph-c_fb60e8264336e5e17223a4291988089aae347166/qa/tasks/cephfs/test_volumes.py", line 5782, in test_subvolume_snapshot_info_if_orphan_clone
2022-10-18T04:59:36.359 INFO:tasks.cephfs_test_runner:    pending_clones_result = self.mount_a.run_shell(f"sudo grep \"clone snaps\" -A3 {meta_path}", omit_sudo=False, stdout=StringIO(), stderr=StringIO())
2022-10-18T04:59:36.359 INFO:tasks.cephfs_test_runner:  File "/home/teuthworker/src/github.com_ceph_ceph-c_fb60e8264336e5e17223a4291988089aae347166/qa/tasks/cephfs/mount.py", line 711, in run_shell
2022-10-18T04:59:36.360 INFO:tasks.cephfs_test_runner:    omit_sudo=omit_sudo, **kwargs)
2022-10-18T04:59:36.360 INFO:tasks.cephfs_test_runner:  File "/home/teuthworker/src/git.ceph.com_git_teuthology_35ea38a9840006713a3d42472a2c536a25e88c15/teuthology/orchestra/remote.py", line 525, in run
2022-10-18T04:59:36.360 INFO:tasks.cephfs_test_runner:    r = self._runner(client=self.ssh, name=self.shortname, **kwargs)
2022-10-18T04:59:36.361 INFO:tasks.cephfs_test_runner:  File "/home/teuthworker/src/git.ceph.com_git_teuthology_35ea38a9840006713a3d42472a2c536a25e88c15/teuthology/orchestra/run.py", line 455, in run
2022-10-18T04:59:36.361 INFO:tasks.cephfs_test_runner:    r.wait()
2022-10-18T04:59:36.361 INFO:tasks.cephfs_test_runner:  File "/home/teuthworker/src/git.ceph.com_git_teuthology_35ea38a9840006713a3d42472a2c536a25e88c15/teuthology/orchestra/run.py", line 161, in wait
2022-10-18T04:59:36.362 INFO:tasks.cephfs_test_runner:    self._raise_for_status()
2022-10-18T04:59:36.362 INFO:tasks.cephfs_test_runner:  File "/home/teuthworker/src/git.ceph.com_git_teuthology_35ea38a9840006713a3d42472a2c536a25e88c15/teuthology/orchestra/run.py", line 183, in _raise_for_status
2022-10-18T04:59:36.362 INFO:tasks.cephfs_test_runner:    node=self.hostname, label=self.label
2022-10-18T04:59:36.363 INFO:tasks.cephfs_test_runner:teuthology.exceptions.CommandFailedError: Command failed on smithi008 with status 2: '(cd /home/ubuntu/cephtest/mnt.0 && exec sudo grep \'"clone\' \'snaps"\' -A3 ./volumes/_nogroup/subvolume_0000000000856603/.meta)'
```
This is not related to this fix. This is because the grep for two words separated by a space i.e., 'clone snaps' is treated as separate ones. If it's an issue, I wonder how did it pass master branch! ?

```
pending_clones_result = self.mount_a.run_shell(f"sudo grep \"clone snaps\" -A3 {meta_path}", omit_sudo=False, stdout=StringIO(), stderr=StringIO())

is being converted to 

2022-10-18T04:59:24.147 DEBUG:teuthology.orchestra.run.smithi008:> (cd /home/ubuntu/cephtest/mnt.0 && exec sudo grep '"clone' 'snaps"' -A3 ./volumes/_nogroup/subvolume_0000000000856603/.meta)
2022-10-18T04:59:24.226 INFO:teuthology.orchestra.run.smithi008.stderr:grep: snaps": No such file or directory

```

**Comment by vshankar** [comment]
> The testcase is failed because of the following.
> 
> ```
> 2022-10-18T04:59:36.357 INFO:tasks.cephfs_test_runner:======================================================================
> 2022-10-18T04:59:36.358 INFO:tasks.cephfs_test_runner:ERROR: test_subvolume_snapshot_info_if_orphan_clone (tasks.cephfs.test_volumes.TestSubvolumeSnapshotClones)
> 2022-10-18T04:59:36.358 INFO:tasks.cephfs_test_runner:----------------------------------------------------------------------
> 2022-10-18T04:59:36.358 INFO:tasks.cephfs_test_runner:Traceback (most recent call last):
> 2022-10-18T04:59:36.359 INFO:tasks.cephfs_test_runner:  File "/home/teuthworker/src/github.com_ceph_ceph-c_fb60e8264336e5e17223a4291988089aae347166/qa/tasks/cephfs/test_volumes.py", line 5782, in test_subvolume_snapshot_info_if_orphan_clone
> 2022-10-18T04:59:36.359 INFO:tasks.cephfs_test_runner:    pending_clones_result = self.mount_a.run_shell(f"sudo grep \"clone snaps\" -A3 {meta_path}", omit_sudo=False, stdout=StringIO(), stderr=StringIO())
> 2022-10-18T04:59:36.359 INFO:tasks.cephfs_test_runner:  File "/home/teuthworker/src/github.com_ceph_ceph-c_fb60e8264336e5e17223a4291988089aae347166/qa/tasks/cephfs/mount.py", line 711, in run_shell
> 2022-10-18T04:59:36.360 INFO:tasks.cephfs_test_runner:    omit_sudo=omit_sudo, **kwargs)
> 2022-10-18T04:59:36.360 INFO:tasks.cephfs_test_runner:  File "/home/teuthworker/src/git.ceph.com_git_teuthology_35ea38a9840006713a3d42472a2c536a25e88c15/teuthology/orchestra/remote.py", line 525, in run
> 2022-10-18T04:59:36.360 INFO:tasks.cephfs_test_runner:    r = self._runner(client=self.ssh, name=self.shortname, **kwargs)
> 2022-10-18T04:59:36.361 INFO:tasks.cephfs_test_runner:  File "/home/teuthworker/src/git.ceph.com_git_teuthology_35ea38a9840006713a3d42472a2c536a25e88c15/teuthology/orchestra/run.py", line 455, in run
> 2022-10-18T04:59:36.361 INFO:tasks.cephfs_test_runner:    r.wait()
> 2022-10-18T04:59:36.361 INFO:tasks.cephfs_test_runner:  File "/home/teuthworker/src/git.ceph.com_git_teuthology_35ea38a9840006713a3d42472a2c536a25e88c15/teuthology/orchestra/run.py", line 161, in wait
> 2022-10-18T04:59:36.362 INFO:tasks.cephfs_test_runner:    self._raise_for_status()
> 2022-10-18T04:59:36.362 INFO:tasks.cephfs_test_runner:  File "/home/teuthworker/src/git.ceph.com_git_teuthology_35ea38a9840006713a3d42472a2c536a25e88c15/teuthology/orchestra/run.py", line 183, in _raise_for_status
> 2022-10-18T04:59:36.362 INFO:tasks.cephfs_test_runner:    node=self.hostname, label=self.label
> 2022-10-18T04:59:36.363 INFO:tasks.cephfs_test_runner:teuthology.exceptions.CommandFailedError: Command failed on smithi008 with status 2: '(cd /home/ubuntu/cephtest/mnt.0 && exec sudo grep \'"clone\' \'snaps"\' -A3 ./volumes/_nogroup/subvolume_0000000000856603/.meta)'
> ```
> 
> This is not related to this fix. This is because the grep for two words separated by a space i.e., 'clone snaps' is treated as separate ones. If it's an issue, I wonder how did it pass master branch! ?

Possibly due to some missing qa backports.

**Comment by kotreshhr** [comment]
@vshankar I think using `clone\ snaps` instead of `\"clone snaps\"` is better option to behave sanely across platforms. Wdyt ?

```
pending_clones_result = self.mount_a.run_shell(f"sudo grep \"clone snaps\" -A3 {meta_path}", omit_sudo=False, stdout=StringIO(), stderr=StringIO())
```
to 
```
pending_clones_result = self.mount_a.run_shell(f"sudo grep clone\ snaps -A3 {meta_path}", omit_sudo=False, stdout=StringIO(), stderr=StringIO())
```

**Comment by kotreshhr** [comment]
> Possibly due to some missing qa backports.

Could be, I am not very sure.

**Comment by vshankar** [comment]
> @vshankar I think using `clone\ snaps` instead of `\"clone snaps\"` is better option to behave sanely across platforms. Wdyt ?
> 
> ```
> pending_clones_result = self.mount_a.run_shell(f"sudo grep \"clone snaps\" -A3 {meta_path}", omit_sudo=False, stdout=StringIO(), stderr=StringIO())
> ```
> 
> to
> 
> ```
> pending_clones_result = self.mount_a.run_shell(f"sudo grep clone\ snaps -A3 {meta_path}", omit_sudo=False, stdout=StringIO(), stderr=StringIO())
> ```

As I mentioned in stand-up, let's get this change in main and include the change with this backport.

**Comment by kotreshhr** [comment]
> > @vshankar I think using `clone\ snaps` instead of `\"clone snaps\"` is better option to behave sanely across platforms. Wdyt ?
> > ```
> > pending_clones_result = self.mount_a.run_shell(f"sudo grep \"clone snaps\" -A3 {meta_path}", omit_sudo=False, stdout=StringIO(), stderr=StringIO())
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > to
> > ```
> > pending_clones_result = self.mount_a.run_shell(f"sudo grep clone\ snaps -A3 {meta_path}", omit_sudo=False, stdout=StringIO(), stderr=StringIO())
> > ```
> 
> As I mentioned in stand-up, let's get this change in main and include the change with this backport.

Done. What about Pacific ?

**Comment by vshankar** [comment]
> > > @vshankar I think using `clone\ snaps` instead of `\"clone snaps\"` is better option to behave sanely across platforms. Wdyt ?
> > > ```
> > > pending_clones_result = self.mount_a.run_shell(f"sudo grep \"clone snaps\" -A3 {meta_path}", omit_sudo=False, stdout=StringIO(), stderr=StringIO())
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > to
> > > ```
> > > pending_clones_result = self.mount_a.run_shell(f"sudo grep clone\ snaps -A3 {meta_path}", omit_sudo=False, stdout=StringIO(), stderr=StringIO())
> > > ```
> > 
> > 
> > As I mentioned in stand-up, let's get this change in main and include the change with this backport.
> 
> Done. What about Pacific ?

If this is getting backported to pacific, then yes.

**Comment by kotreshhr** [comment]
The fix was still failing in pacific (https://github.com/ceph/ceph/pull/48647#issuecomment-1333080710) with the usgae of  'clone\ snaps' as grep argument. Fixed this by using run.Raw(). Hopefully, it passes this time.

**Comment by joscollin** [comment]
jenkins retest this please

**Comment by joscollin** [comment]
jenkins test windows

**Review by joscollin — CHANGES_REQUESTED** [review]
@kotreshhr `test_subvolume_snapshot_info_if_orphan_clone` fails in [1]. But that seems to be a different issue than this PR fixes. Can you confirm?

[1] https://pulpito.ceph.com/yuriw-2023-02-16_19:08:52-fs-wip-yuri3-testing-2023-02-16-0752-quincy-distro-default-smithi/7176542/

**Comment by yuriw** [comment]
Untagged
@kotreshhr @joscollin Letting you guys to merge it, thx

**Review by joscollin — APPROVED** [review]

**Pull request merged**
