### PR TITLE
qa/suites/crimson-rados: add seastore

### PR DESCRIPTION
**Pull request by xxhdx1985126**
Signed-off-by: Xuehan Xu <xuxuehan@qianxin.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [x] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [x] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Review by Matan-B — COMMENTED** [review]
Can we use `qa/suites/crimson-rados-experimental` for seastore?
I'm ok with moving seastore test gradually to `crimson-rados` as they become more stable.

It's possible also to test changes to qa directory without actually merging to main.

**Comment by xxhdx1985126** [comment]
> Can we use `qa/suites/crimson-rados-experimental` for seastore? I'm ok with moving seastore test gradually to `crimson-rados` as they become more stable.

Yeah, but seastore can already pass the `crimson-rados` suite once the following PR merged:
https://github.com/ceph/ceph/pull/56025
https://github.com/ceph/ceph/pull/55978
https://github.com/ceph/ceph/pull/56114
https://github.com/ceph/ceph/pull/55947
https://github.com/ceph/ceph/pull/55735

> 
> It's possible also to test changes to qa directory without actually merging to main.

**Comment by cyx1231st** [comment]
See another comment https://github.com/ceph/ceph/pull/55806#issuecomment-1972293154. SeaStore is already in the experimental suite, IIUC the goal of this PR is to move it (maybe not yet entirely?) into the standard teuthology suites.

Or, is there a way to specialize `max-attr-len` for seastore in `crimson-rados`?

**Comment by Matan-B** [comment]
> Or, is there a way to specialize `max-attr-len` for seastore in `crimson-rados`?

In the seastore yaml or by adding a new seastore-overrides yaml (same as we have `crimson_qa_overrides.yaml`), you can try setting:
```
overrides:
  tasks:
  - rados:
      max_attr_len: 8192
```

---

Moreover, instead of introducing 3 copies of seastore.yaml we can store bluestore.yaml and seastore.yaml in a common objectstore directory and create symlink instead of copies. (Can be in a future PR if preferred)

**Comment by xxhdx1985126** [comment]
> > Or, is there a way to specialize `max-attr-len` for seastore in `crimson-rados`?
> 
> In the seastore yaml or by adding a new seastore-overrides yaml (same as we have `crimson_qa_overrides.yaml`), you can try setting:
> 
> ```
> overrides:
>   tasks:
>   - rados:
>       max_attr_len: 8192
> ```

Um, I tried to put this setting in a common yaml file, but it seems that there are workloads that are not doing rados tests in which case this setting will force the rados tests while other necessary settings are missing. So I only put this setting in workloads that are doing rados tests.

> 
> Moreover, instead of introducing 3 copies of seastore.yaml we can store bluestore.yaml and seastore.yaml in a common objectstore directory and create symlink instead of copies. (Can be in a future PR if preferred)

Yeah, will do.

**Comment by cyx1231st** [comment]
Seems there are dependent fixes waiting for QA, @xxhdx1985126 if you have troubles accessing the sepia lab, I can help to run the suites if you have builds available in https://shaman.ceph.com/builds/ceph/

**Comment by xxhdx1985126** [comment]
> Seems there are dependent fixes waiting for QA, @xxhdx1985126 if you have troubles accessing the sepia lab, I can help to run the suites if you have builds available in https://shaman.ceph.com/builds/ceph/

It seems that I still can't run teuthology tests in sepia, here's this PR's build: https://shaman.ceph.com/builds/ceph/wip-seastore-teuthology/, thanks very much:-)

**Comment by cyx1231st** [comment]
https://pulpito.ceph.com/yingxin-2024-04-02_05:40:31-crimson-rados-wip-seastore-teuthology-distro-default-smithi/

**Comment by Matan-B** [comment]
My suggestion would be to disable the failing new yamls and enable them gradually to keep the suite green as much as possible. @xxhdx1985126, what do you think?

**Comment by Matan-B** [comment]
Let me know if you need any help scheduling test runs before merging this.

**Comment by cyx1231st** [comment]
Shoud we change this into draft before seastore is really stable as part of `crimson-rados`?

**Comment by xxhdx1985126** [comment]
> Shoud we change this into draft before seastore is really stable as part of `crimson-rados`?

Ok

**Comment by xxhdx1985126** [comment]
> > Shoud we change this into draft before seastore is really stable as part of `crimson-rados`?
> 
> @xxhdx1985126, Since it will probably take time to stabilize all the tests with seastore, we can try introducing them gradually. Green ones can move to crimson-rados and non stable ones will stay in the experimental suite (with a dedicated tracker if that helps).

Yeah, I'll try to split it.

**Comment by Matan-B** [comment]
Rebased, scheduling a test run

**Comment by Matan-B** [comment]
https://pulpito.ceph.com/matan-2024-06-27_11:06:04-crimson-rados-main-distro-crimson-smithi/

**Comment by Matan-B** [comment]
diff: symlinked bluestore since some tests run with seastore only

**Comment by Matan-B** [comment]
Disabling thrasher/default with seastore until https://tracker.ceph.com/issues/66760 is resolved.
Test run with latest changes:
https://pulpito.ceph.com/matan-2024-06-30_09:33:44-crimson-rados-main-distro-crimson-smithi/

**Review by Matan-B — APPROVED** [review]
Can be be merged based on:
https://pulpito.ceph.com/matan-2024-06-30_09:33:44-crimson-rados-main-distro-crimson-smithi/

**Review by cyx1231st — APPROVED** [review]
> https://pulpito.ceph.com/matan-2024-06-30_09:33:44-crimson-rados-main-distro-crimson-smithi/

Q1: Are the 2 failed seastore tests know issues?
* 7779810:  [  FAILED  ] TestLibRBD.TestEncryptionLUKS2
* 7779831:  [ FAILED  ] LibRadosAio.PoolEIOFlag

Q2: Is this a reasonable command to validate seastore related PRs in the future?
`teuthology-suite -m smithi -e <mail> -p <priority> -s crimson-rados -c <branch> --filter-out perf,'objectstore/bluestore' --limit 25`

Q3: Is the issue https://tracker.ceph.com/issues/66721 already addressed using 50G seastore device size?

**Comment by xxhdx1985126** [comment]
> Disabling thrasher/default with seastore until https://tracker.ceph.com/issues/66760 is resolved. Test run with latest changes: https://pulpito.ceph.com/matan-2024-06-30_09:33:44-crimson-rados-main-distro-crimson-smithi/

LGTM!

**Comment by Matan-B** [comment]
> Q1: Are the 2 failed seastore tests know issues?
> 
> * 7779810:  [  FAILED  ] TestLibRBD.TestEncryptionLUKS2
> * 7779831:  [ FAILED  ] LibRadosAio.PoolEIOFlag

* LibRadosAio.PoolEIOFlag - https://tracker.ceph.com/issues/66761
* TestLibRBD.TestEncryptionLUKS2 - We had few instances of it in the past - https://tracker.ceph.com/issues/63844. Still not sure if this is specific to Seastore only.

> Q2: Is this a reasonable command to validate seastore related PRs in the future? `teuthology-suite -m smithi -e <mail> -p <priority> -s crimson-rados -c <branch> --filter-out perf,'objectstore/bluestore' --limit 25`

Yes!

> Q3: Is the issue https://tracker.ceph.com/issues/66721 already addressed using 50G seastore device size?

SeaStore will be tested with the default device size (50GB). The issue appeared when there were no space in the machine due to larger image size. I'll keep https://tracker.ceph.com/issues/66721 open since I think that we have a double close in the case described above (low priority for now).

**Pull request merged**
