### PR TITLE
rgw:CivetWeb http and https be support in the same time.

### PR DESCRIPTION
**Pull request by dwj192**
Fixes: 13718

Signed-off-by: Weijun Duan <duanweijun@h3c.com>

### CODE REVIEW

**Comment by dwj192** [comment]
yehudasa: I took a look at your pull request, overall it looks ok. My question is though whether isn't specifying multiple frontends enough, e.g.:
```
rgw frontends = civetweb port=80, civetweb port=443s ssl_certificate=/home/dwj/ssl/server.pem
```

@yehudasa 
there will create two civetweb instance, ues up method.
 ues: civetweb port=80, civetweb port=443s ssl_certificate=/home/dwj/ssl/server.pem
```
$pstree -p 51429
229
```
use:  civetweb port=80 sport=443 ssl_certificate=/home/dwj/ssl/server.pem
```
$pstree -p 20566
128
```
I think in one rgw instance, generally there will only need one http and(or) one https.

**Comment by dwj192** [comment]
@mdw-at-linuxbox
    civetweb one instance support listen more than one port in the same time, but now i want support 2 port it will start 2 civetweb instance. i thank should support 1 http and 1 https in one instance at least, it is the usual do of config. thanks!

**Comment by mattbenjamin** [comment]
@yehudasa @mdw-at-linuxbox @oritwas is there any interest in supporting 2 civetweb instances in this way?

**Comment by mdw-at-linuxbox** [comment]
I have pull request #8339 - which allows you to run both http and https with *one* civetweb instance (and one pool of request threads to service.)  Matt and I think that's preferable.

**Pull request closed without merging**
