### PR TITLE
jewel: mds: FAILED assert(get_version() < pv) in CDir::mark_dirty

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/22031

### CODE REVIEW

**Comment by tchaikov** [comment]
retest this please.

**Comment by tchaikov** [comment]
retest this please.

**Comment by smithfarm** [comment]
@tchaikov Logs already gone. Jenkins has been acting up again.

**Comment by tchaikov** [comment]
retest this please.

**Comment by smithfarm** [comment]
```
Usage:   
  pip install [options] <requirement specifier> [package-index-options] ...
  pip install [options] -r <requirements file> [package-index-options] ...
  pip install [options] [-e] <vcs project url> ...
  pip install [options] [-e] <local project path> ...
  pip install [options] <archive url/path> ...

no such option: --use-wheel
```

**Comment by tchaikov** [comment]
@smithfarm please check my mail sent to ceph-devel, its title is "make check failure of PRs due to pip". and see also #21159

**Comment by tchaikov** [comment]
retest this please.

**Comment by smithfarm** [comment]
retest this please

**Pull request merged**
