### PR TITLE
ceph-fuse: fuse_disable_pagecache

### PR DESCRIPTION
**Pull request by ukernel**

### CODE REVIEW

**Comment by jcsp** [comment]
So is inode_invalidate_cb unsuitable for this sort of use case (is that just metadata?)

Would it be reasonable for us to think about extending fuse to provide a callback that would allow us to invalidate regions of the page cache in response to capability messages from the MDS?

**Comment by ukernel** [comment]
On Tue, Aug 11, 2015 at 5:02 AM, John Spray <notifications@github.com>
wrote:

> So is inode_invalidate_cb unsuitable for this sort of use case (is that
> just metadata?)
>
> Would it be reasonable for us to think about extending fuse to provide a
> callback that would allow us to invalidate regions of the page cache in
> response to capability messages from the MDS?
>

inode_invalidate_cb invalidates page cache, but kernel still can add data
to page cache later. For the multiple clients case, we want read/write
bypass page cache and go to OSD directly.

**Comment by eric0e** [comment]
I understand that setting fuse_disable_pagecache=true may reduce performance, but I would prefer the default setting support the correct operation that matches the kernel mount, and a user could then set  fuse_disable_pagecache=false if they needed better performance.

**Comment by gregsfortytwo** [comment]
Is it feasible to try and get a FUSE extension into the kernel that lets us block writes/return of writes to the file? Disabling the page cache entirely seems like a really big hammer, although we may need it.

**Comment by ukernel** [comment]
the overhead of blocking writes/return of writes is large, I don't think it's feasible. The simplest solution is make fuse switch buffered/direct IO dynamically. But it still require quite a long time to get it merged into fuse.

**Comment by liewegas** [comment]
Being able to switch from buffered to direct on a per-inode basis really seems like the best solution.  It'd be great to get this added to fuse.

In the meantime, the config option hammer will have to do..

**Comment by gregsfortytwo** [comment]
We need to set up a test for this. I'm working on that nowish.

**Comment by jcsp** [comment]
@gregsfortytwo I see this going into a bunch of testing branches, any outcome from that?

**Comment by gregsfortytwo** [comment]
No, the test code got interrupted and never made it back to the top of my pile. (pingpong is not friendly to automated systems.)

**Comment by jcsp** [comment]
@ukernel this needs a rebase

@gregsfortytwo when you said you were working on setting up a test, did you mean you were working on a new test or just scheduling a run on this?

**Comment by gregsfortytwo** [comment]
A new test. I haven't done anything active on it in a while, but given
where it came from we need to try and integrate the
(automated-test-unfriendly) pingpong.c into our nightlies.

**Comment by jcsp** [comment]
I've created a ticket for creating a pingpong test http://tracker.ceph.com/issues/16228

For now, I will just include this PR on a test branch to check there are no regressions and then merge.

**Comment by jcsp** [comment]
http://pulpito.ceph.com/jspray-2016-06-14_01:19:46-fs-wip-jcsp-testing-20160610-distro-basic-mira/

**Pull request merged**
