### PR TITLE
mon: try to realase forward op which is dropped by leader mon

### PR DESCRIPTION
**Pull request by yanqiang-ux**
when leader mon drop a osd_alive forward op，the src mon will always wait for the forwarded op. 
need reply to the src mon to release the forwarded op.

Fixes: https://tracker.ceph.com/issues/58194

Signed-off-by: yanqiang-ux <yanqiang_ux@163.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [x] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by yanqiang-ux** [comment]
https://tracker.ceph.com/issues/58194   please refer to this bug.

**Comment by yanqiang-ux** [comment]
@kamoltat pls have a review，thanks a lot.

**Review by kamoltat — CHANGES_REQUESTED** [review]
Hi [yanqiang-ux](https://github.com/yanqiang-ux),

Sorry for just getting to this.

nit:

The change looks good to me, however, it would be great if you can include a reproducer or a simple unit-test that would verify this fix. 

Also, can you please  add the PR description in the commit message and also add this line: ``Fixes: https://tracker.ceph.com/issues/58194`` Thanks!

**Comment by kamoltat** [comment]
jenkins retest this please

**Comment by kamoltat** [comment]
@yanqiang-ux ping

**Comment by yanqiang-ux** [comment]
Hi [yanqiang-ux](https://github.com/yanqiang-ux),

Sorry for just getting to this.

> Hi [yanqiang-ux](https://github.com/yanqiang-ux),
> 
> Sorry for just getting to this.
> 
> nit:
> 
> The change looks good to me, however, it would be great if you can include a reproducer or a simple unit-test that would verify this fix.
> 
> Also, can you please add the PR description in the commit message and also add this line: `Fixes: https://tracker.ceph.com/issues/58194` Thanks!

Hi kamoltat:
    Sorry for just see this.  I thhink you can reproduce it by kill diffrent osds will heavy IO. 
    "Fixes: https://tracker.ceph.com/issues/58194" has been added to the commit.
Thanks.

**Pull request closed without merging**
