### PR TITLE
debian/control: add python-routes dependency for dashboard

### PR DESCRIPTION
**Pull request by emmericp**
Our build broken because we only had python-routes installed by coincident, some unrelated change in our image removed the dependency on python-routes.
This patch ensures that python-routes is always installed

https://tracker.ceph.com/issues/24420

- [x] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by emmericp** [comment]
retest this please

**Comment by tchaikov** [comment]
@emmericp could update the commit message to note that this runtime dependency is introduced by cherrypy/_cpdispatch.py ?

see https://tracker.ceph.com/issues/24420#note-11

**Comment by emmericp** [comment]
done

**Comment by emmericp** [comment]
retest this please

**Comment by tchaikov** [comment]
https://shaman.ceph.com/builds/ceph/wip-kefu-testing-2019-07-03-2150/38c405b39396bdb0ecbd7d2ab495459cc9e85748/

the failure is caused by https://tracker.ceph.com/issues/40646

**Pull request merged**
