### PR TITLE
msg/async: Separated nonfast message and fast dispatch message thread

### PR DESCRIPTION
**Pull request by yuyuyu101**

### CODE REVIEW

**Comment by yuyuyu101** [comment]
Fixes http://tracker.ceph.com/issues/15758

**Comment by yuyuyu101** [comment]
passed http://pulpito.ceph.com/haomai-2016-05-08_21:22:48-rados-wip-15758-distro-basic-smithi/

**Comment by liewegas** [comment]
This looks great!  I'll tag it for one more run through the suite just to be on the safe side.

**Comment by yuriw** [comment]
Per ICR chat with @athanatos we suspect the test failed in test run due to this PR, e.g. leaking throttle
See this log: http://qa-proxy.ceph.com/teuthology/yuriw-2016-05-19_07:57:01-rados-wip-yuri-testing2-distro-basic-smithi/201730/teuthology.log

2016-05-19T08:40:25.187 INFO:tasks.rados.rados.0.smithi023.stdout:65: write oid 7 oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo current snap is 0
2016-05-19T08:40:25.187 INFO:tasks.rados.rados.0.smithi023.stdout:65:  seq_num 52 ranges {473964=611066,1826593=546335,2778819=95145}
2016-05-19T08:40:25.188 INFO:tasks.rados.rados.0.smithi023.stderr:common/Throttle.cc: In function 'int64_t Throttle::put(int64_t)' thread 7f2567fff700 time 2016-05-19 15:40:25.167184
2016-05-19T08:40:25.188 INFO:tasks.rados.rados.0.smithi023.stderr:common/Throttle.cc: 230: FAILED assert(((int64_t)count.read()) >= c)
2016-05-19T08:40:25.188 INFO:tasks.rados.rados.0.smithi023.stderr: ceph version 10.2.0-1044-g920b893 (920b893494a2faa8d61328e4d17b36208ed0e084)
2016-05-19T08:40:25.188 INFO:tasks.rados.rados.0.smithi023.stderr: 1: (()+0x172275) [0x7f2573753275]
2016-05-19T08:40:25.189 INFO:tasks.rados.rados.0.smithi023.stderr: 2: (()+0x16b11c) [0x7f257374c11c]
2016-05-19T08:40:25.189 INFO:tasks.rados.rados.0.smithi023.stderr: 3: (()+0x30dc40) [0x7f25738eec40]
2016-05-19T08:40:25.189 INFO:tasks.rados.rados.0.smithi023.stderr: 4: (()+0x340a61) [0x7f2573921a61]
2016-05-19T08:40:25.189 INFO:tasks.rados.rados.0.smithi023.stderr: 5: (()+0x34566f) [0x7f257392666f]
2016-05-19T08:40:25.189 INFO:tasks.rados.rados.0.smithi023.stderr: 6: (()+0x349f54) [0x7f257392af54]
2016-05-19T08:40:25.189 INFO:tasks.rados.rados.0.smithi023.stderr: 7: (()+0x354b11) [0x7f2573935b11]
2016-05-19T08:40:25.190 INFO:tasks.rados.rados.0.smithi023.stderr: 8: (()+0x365fe7) [0x7f2573946fe7]
2016-05-19T08:40:25.190 INFO:tasks.rados.rados.0.smithi023.stderr: 9: (()+0x35a696) [0x7f257393b696]
2016-05-19T08:40:25.190 INFO:tasks.rados.rados.0.smithi023.stderr: 10: (()+0x7dc5) [0x7f2572a4ddc5]
2016-05-19T08:40:25.190 INFO:tasks.rados.rados.0.smithi023.stderr: 11: (clone()+0x6d) [0x7f257193428d]
2016-05-19T08:40:25.190 INFO:tasks.rados.rados.0.smithi023.stderr: NOTE: a copy of the executable, or `objdump -rdS <executable>` is needed to interpret this.
2016-05-19T08:40:25.193 CRITICAL:root:  File "gevent/corecext.pyx", line 360, in gevent.corecext.loop.handle_error (gevent/gevent.corecext.c:6344)

**Comment by yuyuyu101** [comment]
@liewegas @yuriw done, plz rescheduler to next round :-)

**Comment by liewegas** [comment]
Leaks!

<pre>
  <kind>Leak_DefinitelyLost</kind>
  <xwhat>
    <text>200 (56 direct, 144 indirect) bytes in 1 blocks are definitely lost in loss record 155 of 255</text>
    <leakedbytes>200</leakedbytes>
    <leakedblocks>1</leakedblocks>
  </xwhat>
  <stack>
    <frame>
      <ip>0xAD34105</ip>
      <obj>/usr/lib64/valgrind/vgpreload_memcheck-amd64-linux.so</obj>
      <fn>operator new(unsigned long)</fn>
    </frame>
    <frame>
      <ip>0xB5074C</ip>
      <obj>/usr/bin/ceph-osd</obj>
      <fn>allocate</fn>
      <dir>/usr/include/c++/4.8.2/ext</dir>
      <file>new_allocator.h</file>
      <line>104</line>
    </frame>
    <frame>
      <ip>0xB5074C</ip>
      <obj>/usr/bin/ceph-osd</obj>
      <fn>_M_get_node</fn>
      <dir>/usr/include/c++/4.8.2/bits</dir>
      <file>stl_tree.h</file>
      <line>370</line>
    </frame>
    <frame>
      <ip>0xB5074C</ip>
      <obj>/usr/bin/ceph-osd</obj>
      <fn>_M_create_node&lt;const std::piecewise_construct_t&amp;, std::tuple&lt;const std::pair&lt;long unsigned int, long unsigned int&gt;&amp;&gt;, std::tuple&lt;&gt; &gt;</fn>
      <dir>/usr/include/c++/4.8.2/bits</dir>
      <file>stl_tree.h</file>
      <line>403</line>
    </frame>
    <frame>
      <ip>0xB5074C</ip>
      <obj>/usr/bin/ceph-osd</obj>
      <fn>std::_Rb_tree_iterator&lt;std::pair&lt;std::pair&lt;unsigned long, unsigned long&gt; const, std::pair&lt;unsigned int, unsigned int&gt; &gt; &gt; std::_Rb_tree&lt;std::pair&lt;unsigned long, unsigned long&gt;, std::pair&lt;std::pair&lt;unsigned long, unsigned long&gt; const, std::pair&lt;unsigned int, unsigned int&gt; &gt;, std::_Select1st&lt;std::pair&lt;std::pair&lt;unsigned long, unsigned long&gt; const, std::pair&lt;unsigned int, unsigned int&gt; &gt; &gt;, std::less&lt;std::pair&lt;unsigned long, unsigned long&gt; &gt;, std::allocator&lt;std::pair&lt;std::pair&lt;unsigned long, unsigned long&gt; const, std::pair&lt;unsigned int, unsigned int&gt; &gt; &gt; &gt;::_M_emplace_hint_unique&lt;std::piecewise_construct_t const&amp;, std::tuple&lt;std::pair&lt;unsigned long, unsigned long&gt; const&amp;&gt;, std::tuple&lt;&gt; &gt;(std::_Rb_tree_const_iterator&lt;std::pair&lt;std::pair&lt;unsigned long, unsigned long&gt; const, std::pair&lt;unsigned int, unsigned int&gt; &gt; &gt;, std::piecewise_construct_t const&amp;, std::tuple&lt;std::pair&lt;unsigned long, unsigned long&gt; const&amp;&gt;&amp;&amp;, std::tuple&lt;&gt;&amp;&amp;)</fn>
      <dir>/usr/include/c++/4.8.2/bits</dir>
      <file>stl_tree.h</file>
      <line>1669</line>
    </frame>
    <frame>
      <ip>0xB4D180</ip>
      <obj>/usr/bin/ceph-osd</obj>
      <fn>operator[]</fn>
      <dir>/usr/include/c++/4.8.2/bits</dir>
      <file>stl_map.h</file>
      <line>465</line>
    </frame>
    <frame>
      <ip>0xB4D180</ip>
      <obj>/usr/bin/ceph-osd</obj>
      <fn>set_crc</fn>
      <dir>/usr/src/debug/ceph-10.2.0/src/common</dir>
      <file>buffer.cc</file>
      <line>229</line>
    </frame>
    <frame>
      <ip>0xB4D180</ip>
      <obj>/usr/bin/ceph-osd</obj>
      <fn>ceph::buffer::list::crc32c(unsigned int) const</fn>
      <dir>/usr/src/debug/ceph-10.2.0/src/common</dir>
      <file>buffer.cc</file>
      <line>2295</line>
    </frame>
    <frame>
      <ip>0xA927E4</ip>
      <obj>/usr/bin/ceph-osd</obj>
      <fn>decode_message(CephContext*, int, ceph_msg_header&amp;, ceph_msg_footer&amp;, ceph::buffer::list&amp;, ceph::buffer::list&amp;, ceph::buffer::list&amp;)</fn>
      <dir>/usr/src/debug/ceph-10.2.0/src/msg</dir>
      <file>Message.cc</file>
      <line>288</line>
    </frame>
</pre>
and others.  see /a/sage-2016-05-23_05:47:51-rados-wip-sage-testing---basic-smithi/208625/remote/*/log/v*/osd.0*

**Comment by yuyuyu101** [comment]
passed http://pulpito.ceph.com/haomai-2016-05-24_23:52:45-rados-wip-15758---basic-smithi/

**Comment by yuyuyu101** [comment]
@liewegas plz rescheduler again! thanks!

**Comment by liewegas** [comment]
great, let's retest!

**Comment by yuyuyu101** [comment]
@yuriw hi, what's the status of wip-yuri-testing?

**Comment by yuyuyu101** [comment]
@tchaikov this should also be tested like https://github.com/ceph/ceph/pull/8963 ?

**Comment by tchaikov** [comment]
tested at 

- http://pulpito.ceph.com/kchai-2016-06-15_04:31:07-rados-wip-kefu-testing---basic-mira/
- http://pulpito.ceph.com/kchai-2016-06-15_10:14:46-rados-wip-kefu-testing---basic-mira/
- http://pulpito.ceph.com/kchai-2016-06-17_02:37:57-rados-wip-kefu-testing---basic-mira/

**Comment by yuyuyu101** [comment]
@liewegas it has passed two round tests:

http://pulpito.ceph.com/haomai-2016-05-08_21:22:48-rados-wip-15758-distro-basic-smithi/ (a valgrind issue fixed later)
http://pulpito.ceph.com/kchai-2016-06-15_10:14:46-rados-wip-kefu-testing---basic-mira/ (seemed master issue mostly)

I think it's ready although wip-yuri-testing is pending...?

**Pull request merged**
