### PR TITLE
[WIP] mgr/cephadm: cephadm support password connect

### PR DESCRIPTION
**Pull request by strenuous-life**
In some scenes sshkey is not permitted. So password need be supported when deploy ceph cluster by means of cephadm.

Reference: https://lists.ceph.io/hyperkitty/list/dev@ceph.io/message/FGFHNWWFAUH5F33ETI5MYMB5ASRZCCT5/

Signed-off-by: jianglong01 <jianglong01@qianxin.com>

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Review by sebastian-philipp — CHANGES_REQUESTED** [review]

**Comment by sebastian-philipp** [comment]
Now things are starting to get interesting. I added this to next week's Ceph Developer Monthly to discuss this: https://tracker.ceph.com/projects/ceph/wiki/CDM_01-DEC-2021

**Comment by strenuous-life** [comment]
> 



> Now things are starting to get interesting. I added this to next week's Ceph Developer Monthly to discuss this: https://tracker.ceph.com/projects/ceph/wiki/CDM_01-DEC-2021

**Comment by strenuous-life** [comment]
> Now things are starting to get interesting. I added this to next week's Ceph Developer Monthly to discuss this: https://tracker.ceph.com/projects/ceph/wiki/CDM_01-DEC-2021

@sebastian-philipp Can I know that whether the pr is discussed? What are the results? Thanks.

**Comment by sebastian-philipp** [comment]
Just to clarify: are you aware that if you store it in the config-key store, the password is stored as secure as the ssh key itself? There is a big potential that you're deceiving yourself that having a password protected key is more secure that an unencrypted key. Which is not the case as implemented in this PR

**Comment by strenuous-life** [comment]
> Just to clarify: are you aware that if you store it in the config-key store, the password is stored as secure as the ssh key itself? There is a big potential that you're deceiving yourself that having a password protected key is more secure that an unencrypted key. Which is not the case as implemented in this PR

emm, that's a problem really. Do you have some good suggestions to our scenario that ssh-key is not permitted but password only is.

**Comment by sebastian-philipp** [comment]
> > Just to clarify: are you aware that if you store it in the config-key store, the password is stored as secure as the ssh key itself? There is a big potential that you're deceiving yourself that having a password protected key is more secure that an unencrypted key. Which is not the case as implemented in this PR
> 
> emm, that's a problem really. Do you have some good suggestions to our scenario that ssh-key is not permitted but password only is. Thanks. @sebastian-philipp

What are your requirements?

**Comment by strenuous-life** [comment]
> > > Just to clarify: are you aware that if you store it in the config-key store, the password is stored as secure as the ssh key itself? There is a big potential that you're deceiving yourself that having a password protected key is more secure that an unencrypted key. Which is not the case as implemented in this PR
> > 
> > 
> > emm, that's a problem really. Do you have some good suggestions to our scenario that ssh-key is not permitted but password only is. Thanks. @sebastian-philipp
> 
> What are your requirements?

When add host, ssh-copy-id is a nessary step. For the sake of omitting the step, the method of password is thought by us (provided that passwords of all hosts is identical).

**Comment by sebastian-philipp** [comment]
> > > > Just to clarify: are you aware that if you store it in the config-key store, the password is stored as secure as the ssh key itself? There is a big potential that you're deceiving yourself that having a password protected key is more secure that an unencrypted key. Which is not the case as implemented in this PR
> > > 
> > > 
> > > emm, that's a problem really. Do you have some good suggestions to our scenario that ssh-key is not permitted but password only is. Thanks. @sebastian-philipp
> > 
> > 
> > What are your requirements?
> 
> When add host, ssh-copy-id is a nessary step. For the sake of omitting the step, the method of password is thought by us (provided that passwords of all hosts is identical).

I'd like to talk with you directly about this. You think we can schedule a quick meeting for this?

**Comment by strenuous-life** [comment]
> > > > > Just to clarify: are you aware that if you store it in the config-key store, the password is stored as secure as the ssh key itself? There is a big potential that you're deceiving yourself that having a password protected key is more secure that an unencrypted key. Which is not the case as implemented in this PR
> > > > 
> > > > 
> > > > emm, that's a problem really. Do you have some good suggestions to our scenario that ssh-key is not permitted but password only is. Thanks. @sebastian-philipp
> > > 
> > > 
> > > What are your requirements?
> > 
> > 
> > When add host, ssh-copy-id is a nessary step. For the sake of omitting the step, the method of password is thought by us (provided that passwords of all hosts is identical).
> 
> I'd like to talk with you directly about this. You think we can schedule a quick meeting for this?



> > > > > Just to clarify: are you aware that if you store it in the config-key store, the password is stored as secure as the ssh key itself? There is a big potential that you're deceiving yourself that having a password protected key is more secure that an unencrypted key. Which is not the case as implemented in this PR
> > > > 
> > > > 
> > > > emm, that's a problem really. Do you have some good suggestions to our scenario that ssh-key is not permitted but password only is. Thanks. @sebastian-philipp
> > > 
> > > 
> > > What are your requirements?
> > 
> > 
> > When add host, ssh-copy-id is a nessary step. For the sake of omitting the step, the method of password is thought by us (provided that passwords of all hosts is identical).
> 
> I'd like to talk with you directly about this. You think we can schedule a quick meeting for this?

Sorry for late reply. I have sent you an email.

**Pull request closed without merging**
