### PR TITLE
Wip cot from giant

### PR DESCRIPTION
**Pull request by dzafman**
Backport all ceph-objectstore-tool commits from giant into firefly.  Passes test/ceph_objectstore_tool.py unit test.   Aside from all commits affecting tools/ceph_filestore_dump.cc, tools/ceph_objectstore_tool.cc (renamed) and test/ceph_objectstore_tool.py, I had to bring in related changes 6149f85 and 998419e.  The commit 214eb2c makes the unit test work so vstart.sh cluster can go health_ok.

### CODE REVIEW

**Comment by dzafman** [comment]
I forgot that I need add a branch/pull request for ceph-qa-suite for testing in firefly too.

**Comment by dachary** [comment]
@dzafman please let me know when the ceph-qa-suite patch is ready and I'll run the rados suite.

**Comment by dzafman** [comment]
For now we aren't going to put this into firefly.  Also, I'm working on a hammer backport to giant which would probably easily be added to this firefly branch.  ceph-qa-suite could then be updated and proper testing started.  Currently, giant has ceph-objectstore-tool testing disabled due to failures.

**Comment by dachary** [comment]
@dzafman ack, thanks for the update

**Pull request closed without merging**
