### PR TITLE
Cache tier bug fixs

### PR DESCRIPTION
**Pull request by majianpeng**

### CODE REVIEW

**Comment by majianpeng** [comment]
@liewegas . Have you time review this? Thanks!

**Comment by liewegas** [comment]
does https://github.com/ceph/ceph/pull/3879 look ok to you?

**Comment by majianpeng** [comment]
@liewegas . Updated please review again! Thanks!

**Comment by liewegas** [comment]
Looks right, but not sure if it could be simpler, what do you think?

**Comment by liewegas** [comment]
Also, can you put Fixes: #11026 in teh commit message?

Thanks!

**Comment by majianpeng** [comment]
Make last_force_resend into op_target_t, i think it's not a good idea. Because they have no any relation. OK, i'll update #11026.

**Comment by liewegas** [comment]
sounds good, thanks!

**Comment by liewegas** [comment]
Can you drop the middle commit (the redirect)?  Other than that this looks good.  Thanks!

**Comment by majianpeng** [comment]
The middle commit(the redirect) is my origin aim. At first, i want in _calc_target do this work(in this case send to basetier). But you said: make this in server is good idea. Why remove this?  Thanks!

**Comment by liewegas** [comment]
I think the redirect (probably) makes sense if the only kind of tier is a cache tier.  But we want to keep the door open for different kinds of tiers and tiering scenarios, like, say, lots of read-only caches (here i guess teh cache_mode wouldn't be none) or cold tiers with redirects from the base tier into them (here the cache_mode would be none because it isn't a cache).  I don't think we should commit to these sorts of guards until we know more about how we'll be using things.

This leaves the user with the ability to misconfigure things and shoot themselves in the foot, but that's what the add-cache command is for.  If the other warnings aren't enough, we can make a HEALTH_WARN to cover this situation; those can be removed later and don't effect IO.  A behavior like the middle patch someone could unknowingly come to rely on and and when we find we have to remove it later it will be hard to.

**Comment by majianpeng** [comment]
Thanks your detail explanation. Updated, Thanks!

**Comment by liewegas** [comment]
Invalid command:  missing required parameter size(<int[0-]>)
osd tier add-cache <poolname> <poolname> <int[0-]> :  add a cache <tierpool> (the second one) of size <size> to existing pool <pool> (the first one)

from the test!

**Comment by majianpeng** [comment]
updated & please review again! Thanks!

**Pull request merged**
