### PR TITLE
rgw/auth/s3: validate x-amz-content-sha256 for empty payloads

### PR DESCRIPTION
**Pull request by cbodley**
when is_v4_payload_empty(), we return a null completer so never try to validate the x-amz-content-sha256 for signed payloads. add this checksum comparison to get_auth_data_v4() before we create the completer

Fixes: https://tracker.ceph.com/issues/64084

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Review by dang — APPROVED** [review]

**Comment by climb-mountain123** [comment]
when I use the shell script to create bucket with the header of x_amz_content_sha256, a error that is ERR_AMZ_CONTENT_SHA256_MISMATCH occurs.

**Comment by climb-mountain123** [comment]
Sorry, this was a mistake caused by my negligence.

**Comment by cbodley** [comment]
@climb-mountain123 thanks for testing!

**Comment by cbodley** [comment]
passed qa after rerun https://pulpito.ceph.com/cbodley-2024-02-10_20:17:29-rgw-wip-cbodley-testing-distro-default-smithi/

**Pull request merged**
