### PR TITLE
librbd: deadlock during cooperative exclusive lock transition

### PR DESCRIPTION
**Pull request by dillaman**
http://tracker.ceph.com/issues/12235

Note: contains commits included in PR #5296 that can be rebased away once they merge.

### CODE REVIEW

**Comment by dachary** [comment]
Marked DNM to ack that it is on top of PR #5280 and PR #5296

**Comment by dachary** [comment]
@dillaman could you please rebase now that #5280 is merged ?

**Comment by dillaman** [comment]
@dachary should I just wait until #5296 merges as well?

**Comment by dachary** [comment]
@dillaman I'll try a new strategy for integration that should deal with dependencies. Simply by merging into the integration branch in the same order commits are merged in master. That should automatically merge in order and if one pull request is indeed including all the commits from another, that should just work nicely. So you can rebase this one, it won't be a loss of time: both can be tested at the same time even though they depend on each other.

**Comment by dillaman** [comment]
@dachary sweet ... I'll take care of the rebases tonight.

**Comment by dachary** [comment]
@dillaman when I try to merge this pull request on top of https://github.com/ceph/ceph/pull/5296, it conflicts. Which suggests the commits that look like they come from #5296 that are included in #5319 are not exactly the same really. Or I'm missing something ;-)

<pre>
Auto-merging src/librbd/ImageWatcher.cc
CONFLICT (content): Merge conflict in src/librbd/ImageWatcher.cc
Auto-merging src/common/Mutex.cc
CONFLICT (content): Merge conflict in src/common/Mutex.cc
Automatic merge failed; fix conflicts and then commit the result.
</pre>

**Comment by dillaman** [comment]
@dachary try this -- I rebuilt the branch

**Comment by dachary** [comment]
@dillaman this is what I see: http://paste2.org/fExaxzhm . FYI the reference is fetched with git fetch --force ceph +refs/pull/$pr/head:refs/remotes/ceph/pull/$pr/head

**Comment by dillaman** [comment]
@dachary this is what I see: http://fpaste.org/249506/81929831/  (I have a slightly different PR ref)

**Comment by dachary** [comment]
@dillaman all is well, I shot myself in the foot (the ref of this pr was *not* updated because it was not selected because it had DNM in the title). After fetching the updated pr things are as you describe. Thanks for your patience.

**Comment by dachary** [comment]
Passes the rbd suite http://tracker.ceph.com/issues/12701#rbd

**Pull request merged**
