### PR TITLE
crimson/common: specialize seastar::is_future<> for interruptible_fut…

### PR DESCRIPTION
**Pull request by tchaikov**
…ure<>

this ensures that seastar helper functions are able to accept
interruptible_future<> in place of vanilla seastar::future<>.

for instance, if concepts is enabled, seastar::when_all_succeed()
has a set of constraits which include:

is_future<std::remove_reference_t<decltype(*i)>>::value

where i is the iterator passed to this function. so, to ensure
seastar::when_all_succeed() works with interruptible_future,
we need to teach the is_future<> to accept interruptible_future
as well.

Signed-off-by: Kefu Chai <tchaikov@gmail.com>

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [x] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by tchaikov** [comment]
this change is included as a part of #45133. i am proposing it separately in hope to get it reviewed and merged sooner.

**Review by rzarzynski — APPROVED** [review]

**Comment by tchaikov** [comment]
jenkins test make check

**Comment by tchaikov** [comment]
@rzarzynski hi Radek, could you take another look at this PR? i just added another commit to it.

**Comment by tchaikov** [comment]
see https://jenkins.ceph.com/job/ceph-pull-requests/91159/console for the error message regarding the `seastar::parallel_for_each()` FTBFS failure.

**Comment by tchaikov** [comment]
jenkins test make check

**Comment by tchaikov** [comment]
jenkins test make check

**Comment by tchaikov** [comment]
jenkins test make check

**Review by xxhdx1985126 — APPROVED** [review]

**Review by rzarzynski — COMMENTED** [review]
LGTM.

**Pull request merged**
