### PR TITLE
nautilus: cephfs-shell: various backports

### PR DESCRIPTION
**Pull request by smithfarm**
https://tracker.ceph.com/issues/40898
https://tracker.ceph.com/issues/41089
https://tracker.ceph.com/issues/41105
https://tracker.ceph.com/issues/41112
https://tracker.ceph.com/issues/41118
https://tracker.ceph.com/issues/41268
https://tracker.ceph.com/issues/41283

---

Ganged up a bunch of cephfs-shell backports in a not-entirely-successful bid to avoid cherry pick conflicts.

The commits come from the following master PRs:

https://github.com/ceph/ceph/pull/28239 (1 commit)
https://github.com/ceph/ceph/pull/28447 (1 commit)
https://github.com/ceph/ceph/pull/28652 (1 commit)
https://github.com/ceph/ceph/pull/28793 (8 commits)
https://github.com/ceph/ceph/pull/29374 (5 commits)
https://github.com/ceph/ceph/pull/29149 (2 commits)
https://github.com/ceph/ceph/pull/29554 (1 commit)

### CODE REVIEW

**Comment by batrick** [comment]
retest this please

**Comment by yuriw** [comment]
@smithfarm need rebase

--- pr 29764 --- pulling https://github.com/smithfarm/ceph.git branch wip-41089-nautilus
remote: Enumerating objects: 90, done.
remote: Counting objects: 100% (90/90), done.
remote: Total 109 (delta 90), reused 90 (delta 90), pack-reused 19
Receiving objects: 100% (109/109), 19.69 KiB | 2.46 MiB/s, done.
Resolving deltas: 100% (96/96), completed with 17 local objects.
From https://github.com/smithfarm/ceph
 * branch                  wip-41089-nautilus -> FETCH_HEAD
Auto-merging src/tools/cephfs/cephfs-shell
CONFLICT (content): Merge conflict in src/tools/cephfs/cephfs-shell
Auto-merging qa/tasks/vstart_runner.py
Auto-merging qa/tasks/cephfs/mount.py
Automatic merge failed; fix conflicts and then commit the result.
Traceback (most recent call last):
  File "/home/yuriw/wip_master/src/script/build-integration-branch", line 67, in <module>
    assert not r
AssertionError

**Comment by smithfarm** [comment]
```
 10/173 Test   #9: run-tox-cephfs-shell ....................***Failed   10.14 sec
flake8 create: /home/jenkins-build/build/workspace/ceph-pull-requests/src/tools/cephfs/.tox/flake8
flake8 installdeps: flake8
flake8 installed: entrypoints==0.3,flake8==3.7.9,mccabe==0.6.1,pkg-resources==0.0.0,pycodestyle==2.5.0,pyflakes==2.1.1
flake8 runtests: PYTHONHASHSEED='3102783978'
flake8 runtests: commands[0] | flake8 --ignore=W503 --max-line-length=100 cephfs-shell
cephfs-shell:19:4: E111 indentation is not a multiple of four
ERROR: InvocationError: '/home/jenkins-build/build/workspace/ceph-pull-requests/src/tools/cephfs/.tox/flake8/bin/flake8 --ignore=W503 --max-line-length=100 cephfs-shell'
___________________________________ summary ____________________________________
ERROR:   flake8: commands failed
```

**Comment by yuriw** [comment]
[wip-yuri-testing-2019-11-17-1559-nautilus](https://trello.com/c/4yagFli7/766-wip-yuri-testing-2019-11-17-1559-nautilus)

**Comment by vshankar** [comment]
build fails with this pr: https://jenkins.ceph.com/job/ceph-dev-new-build/ARCH=x86_64,AVAILABLE_ARCH=x86_64,AVAILABLE_DIST=xenial,DIST=xenial,MACHINE_SIZE=huge/33030//consoleFull

**Comment by ajarr** [comment]
@yuriw , I think this backport PR isn't complete and is missing some commits. Can you please drop this from the current batch of nautilus backports?

**Comment by ajarr** [comment]
@rishabh-d-dave please check whether https://github.com/ceph/ceph/pull/28793 has been backported correctly here

**Comment by smithfarm** [comment]
I'm very sorry, but I don't have time to work on this anymore.

**Comment by smithfarm** [comment]
feel free to use my wip branch if it could be useful.

**Pull request closed without merging**
