### PR TITLE
qa/rgw: verify suite tests civetweb with ssl

### PR DESCRIPTION
**Pull request by cbodley**
adds an 'ssl' task to generate certificates with openssl and install them as trusted. if the rgw task specifies a certificate, it's added to the rgw_frontends configuration, and the s3test/swift tasks will configure ssl as well

### CODE REVIEW

**Comment by cbodley** [comment]
several s3test failures: http://qa-proxy.ceph.com/teuthology/cbodley-2018-02-14_20:53:24-rgw:verify-master-distro-basic-smithi/2188351/teuthology.log

**Comment by theanalyst** [comment]
s3tests also does not have an option to run against a non trusted ssl; (which is not the case here) but that is also worth adding

**Comment by cbodley** [comment]
with help from @mdw-at-linuxbox, i figured out how to resolve the failing s3tests. tests that were using the python 'requests' library directly weren't able to verify the certificate, because 'requests' uses its own ca bundle. the s3test task now overrides this by providing the system's ca bundle in the REQUESTS_CA_BUNDLE environment variable

see latest test run at http://qa-proxy.ceph.com/teuthology/cbodley-2018-02-15_15:48:33-rgw:verify-master-distro-basic-smithi/2191725/teuthology.log

**Comment by cbodley** [comment]
suite run: http://pulpito.ceph.com/cbodley-2018-03-06_18:37:37-rgw-wip-cbodley-testing-distro-basic-smithi/

**Comment by cbodley** [comment]
full suite run: http://pulpito.ceph.com/cbodley-2018-03-09_21:57:24-rgw-wip-cbodley-testing-distro-basic-smithi/

known failures from lifecycle expiration, ragweed upgrade tests, and segfault in multisite tests (fixed in master, but not in wip-cbodley-testing)

**Comment by epuertat** [comment]
Thanks, @cbodley!

When resolving the 2 merge conflicts, I get:
- A new file `qa/tasks/ragweed.py` added.
- `qa/tasks/rgw.py`:
  - imports method `util.get_remote_for_role`
  - adds class `RGWEndpoint`,
  - In function `start_rgw()`:
    - `ctx.rgw.role_endpoints[client]` returns kind of named tuple (`endpoint.hostname` and `endpoint.port`, instead of a regular tuple `(host, port)`)
    - The following code was expected (should I backport something else before?):
    ```python
        frontends = ctx.rgw.frontend
        frontend_prefix = client_config.get('frontend_prefix', None)
        if frontend_prefix:
            frontends += ' prefix={pfx}'.format(pfx=frontend_prefix)
    ```
    - And adds the following snippet:
    ```python
        if endpoint.cert:
            # add the ssl certificate path
            frontends += ' ssl_certificate={}'.format(endpoint.cert.certificate)
            if ctx.rgw.frontend == 'civetweb':
                frontends += ' port={}s'.format(endpoint.port)
            else:
                frontends += ' ssl_port={}'.format(endpoint.port)
        else:
            frontends += ' port={}'.format(endpoint.port)
    ```
I see nothing unreasonable over there, but would like to get some expert advice: is everything above ok?

**Comment by epuertat** [comment]
Thank you so much for your help, @cbodley! Unfortunately and for the time being, I'll put this on hold, as the commit that triggered this (98e4b331aa) was to fix the ssl.py clashing, which currently does not happen in Luminous. The agreement for the dashboard_v2 backporting was to minimize the number of non-dashboard commits, so even if this is just testing, it's better to skip these ones. Anyway, if this QA backporting happens, I expect that linking this PR to the later fix will help do that.

**Pull request merged**
