### PR TITLE
test: put unittest_librbd in the check_PROGRAMS, not noinst

### PR DESCRIPTION
**Pull request by gregsfortytwo**
A community member reported that the build doesn't work without the "with-debug" flag to configure, and this is why.

### CODE REVIEW

**Comment by gregsfortytwo** [comment]
@jdurgin, @dachary, please take a look. If this is wrong we'll need a better fix.

**Comment by jdurgin** [comment]
If you look at the history the last commit intentionally move this from check to noinst so a helper script could run it with different rbd feature combinations instead of just the defaults.

I think a better fix would be to decouple the TESTS target (which defines things that are run by make check) from check_PROGRAMS (which are things that should only be built during make check). Right now TESTS = $(check_PROGRAMS), which isn't what we want for things like this script (and probably others in the future).

This change, in addition to replacing other instances of check_PROGRAMS += with TESTS +=  and initializing 'TEST =' in the root makefile may work.

**Comment by gregsfortytwo** [comment]
I must have misread git blame, I thought it said all of these lines were
from a big blanket change.

In any case, I don't think I understand what different targets you're
interested in having and the distinction between them. It looks like this
binary is called from a script which is itself used in "make check", so you
want a separate build target that gets built at the same time but not
executed with them?

**Comment by gregsfortytwo** [comment]
Actually, congratulations, you subtly broke the build @dillaman! Please be fixing. :)

**Comment by dillaman** [comment]
@gregsfortytwo @jdurgin I just wrapped it w/ a conditional to prevent it from being built if gtest isn't available / debug is disabled.

**Comment by dillaman** [comment]
Alternative solution that allows ```run-rbd-unit-tests`` to run successfully with ```make check``` even if debugging isn't enabled.  It avoids the need to swap all the ```check_PROGRAMS += ``` to some intermediate variable which would be assigned to ```check_PROGRAMS``` and ```TESTS```.

**Comment by jdurgin** [comment]
I thought this looked good, but the package builders are failing: http://gitbuilder.sepia.ceph.com/gitbuilder-ceph-deb-precise-amd64-basic/log.cgi?log=031cfe73baa711d2e8a241c51111ddfe8434292c

**Pull request merged**
