### PR TITLE
make install-deps clean up

### PR DESCRIPTION
**Pull request by liewegas**

### CODE REVIEW

**Comment by tchaikov** [comment]
@liewegas: lgtm. 
@dachary what do you think?

**Comment by dachary** [comment]
the install-deps.sh leftover were intentional: it takes time to re-create them every time install-deps.sh is installed and they are removed by make clean. If there is no objection, I'd rather .gitignore install-deps-* and consider them part of a normal outcome of a successfull build.

**Comment by ktdreyer** [comment]
do we need to revert this and take #4843 instead?

**Comment by liewegas** [comment]
i think not making the mess is better than ignoring it.  closed the other one

**Pull request merged**
