### PR TITLE
rgw: remove unnecessary bucket name check already done in base class

### PR DESCRIPTION
**Pull request by Huachao**
Signed-off-by: Huachao Mao <huachaomao@gmail.com>

### CODE REVIEW

**Comment by tchaikov** [comment]
could you prefix the title of your commit message with the subcomponent your are changing ? see https://github.com/ceph/ceph/blob/master/SubmittingPatches.rst#3-describe-your-changes

**Comment by Huachao** [comment]
@tchaikov already created a new commit with updated commit message. Thanks 😄

**Comment by tchaikov** [comment]
could you squash these two commits into a single one?

**Comment by Huachao** [comment]
@tchaikov fixed, thx

**Comment by mattbenjamin** [comment]
@Huachao it seems like it's safest to allow Swift to override this in general?

**Pull request closed without merging**
