### PR TITLE
octopus: mgr/dashboard: test prometheus rules through promtool

### PR DESCRIPTION
**Pull request by aaSharma14**
backport tracker: https://tracker.ceph.com/issues/49657

---

backport of

* https://github.com/ceph/ceph/pull/39246
* https://github.com/ceph/ceph/pull/40205 (one commit)
* https://github.com/ceph/ceph/pull/40300
* https://github.com/ceph/ceph/pull/40395

parent tracker: https://tracker.ceph.com/issues/45415

this backport was staged using ceph-backport.sh version 16.0.0.6848
find the latest version at https://github.com/ceph/ceph/blob/master/src/script/ceph-backport.sh

### CODE REVIEW

**Comment by singuliere** [comment]
jenkins test make check

**Comment by aaSharma14** [comment]
https://github.com/ceph/ceph/pull/39854 needs to be merged before merging this PR

**Comment by aaSharma14** [comment]
jenkins test dashboard

**Review by callithea — APPROVED** [review]

**Comment by tchaikov** [comment]
@aaSharma14 are you going to redo this backport?

**Review by avanthakkar — APPROVED** [review]

**Review by tchaikov — CHANGES_REQUESTED** [review]
this change has been reworked on master. could please cherry-pick the follow-up changes as well?

**Review by idryomov — CHANGES_REQUESTED** [review]
Please drop unrelated libzbd and boost changes.

**Comment by aaSharma14** [comment]
jenkins test api

**Review by idryomov — DISMISSED** [review]
Similar to the nautilus PR: missing `cherry picked from` annotations and conflict resolution notes in *each* commit.

**Comment by smithfarm** [comment]
The first thing to clarify is: which commits from master need to be cherry-picked?

I see one commit from #39246 and then there is #40205 which seems to be related...

**Comment by smithfarm** [comment]
ah, I see the Pacific backport has 4 commits: https://github.com/ceph/ceph/pull/40929

maybe those 4, then?

**Comment by aaSharma14** [comment]
> Similar to the nautilus PR: missing `cherry picked from` annotations and conflict resolution notes in _each_ commit.

Thanks @idryomov .Addressed your comments.

**Review by idryomov — COMMENTED** [review]
My concerns have been addressed. Deferring to the Dashboard team -- the PR has changed quite a lot, please re-review.

**Review by nizamial09 — APPROVED** [review]

**Review by nizamial09 — COMMENTED** [review]
I see only one `backport tracker: https://tracker.ceph.com/issues/49657` but lot of commits are there. Shouldn't each of the backport tracker added to the Description?

**Comment by smithfarm** [comment]
>  Shouldn't each of the backport tracker added to the Description?

@nizamial09 If there really are multiple relevant backport tracker issues, then yes. Feel free to edit the description to add them. In that case, it's also necessary to edit the backport tracker issues themselves, so they properly point to this PR.

**Comment by smithfarm** [comment]
Please note, this octopus PR is emulating the pacific backport PR #40929 so whatever changes happen here, similar changes should happen there as well, and then there is the nautilus PR which is also very similar and should be kept in synch.

(In general, it's good to consider what tangible benefits are brought by any additional administrative work we make for ourselves.)

**Review by epuertat — APPROVED** [review]

**Pull request merged**
