### PR TITLE
cephfs-top: adding filesystem menu in cephfs-top script

### PR DESCRIPTION
**Pull request by neesingh-rh**
Feature to have filesystem menu on running cephfs-top script.

fix: https://tracker.ceph.com/issues/54978
Signed-off-by: Neeraj Pratap Singh <neesingh@redhat.com>

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Review by joscollin — COMMENTED** [review]
> Feature to open separate tabs for each filesystem on running cephfs-top script.

I think this is an insane requirement. What's the benefit of opening a new tab for each filesystem? I think this would rather create a bad user experience. A better approach would be an option (--group) to group lines based on filesystem, and introducing a line/space in between each groups? Something that doesn't contradict with the order-by option TODO in [1].

[1] https://tracker.ceph.com/issues/55121

**Comment by neesingh-rh** [comment]
> > Feature to open separate tabs for each filesystem on running cephfs-top script.
> 
> I think this is an insane requirement. What's the benefit of opening a new tab for each filesystem? I think this would rather create a bad user experience, when there are great number of filesystems. A better approach would be an option (--group) to group lines based on filesystem, and introducing a line/space in between each groups? Something that doesn't contradict with the order-by option TODO in [1].
> 
> [1] https://tracker.ceph.com/issues/55121

For small number of filesystems,it looks ok from user point of view.But if we do have a lot number of filesystems,then its bad for user experience,though,I don't have idea about the number of filesystems that can be possible in use cases.

**Comment by joscollin** [comment]
> > > Feature to open separate tabs for each filesystem on running cephfs-top script.
> > 
> > 
> > I think this is an insane requirement. What's the benefit of opening a new tab for each filesystem? I think this would rather create a bad user experience, when there are great number of filesystems. A better approach would be an option (--group) to group lines based on filesystem, and introducing a line/space in between each groups? Something that doesn't contradict with the order-by option TODO in [1].
> > [1] https://tracker.ceph.com/issues/55121
> 
> For small number of filesystems,it looks ok from user point of view.But if we do have a lot number of filesystems,then its bad for user experience,though,I don't have idea about the number of filesystems that can be possible in use cases.

may be this req. considers just 3 mounted filesystems (mds: 3/3 daemons up). Still opening different tabs seems a bad design to me.

**Comment by lxbsz** [comment]
@neesingh-rh Do you have a screenshot ? Maybe just add one field instead of spliting them into different windows ?

**Comment by neesingh-rh** [comment]
I am adding some snapshots of current working:
1. Menu 
tkinter_window
2. Screen with single fs
single_fs
3. Screen with all fs
multifs

**Comment by joscollin** [comment]
> I am adding some snapshots of current working:
> 
>     1. Menu
>        tkinter_window
> 

@neesingh-rh @lxbsz @mchangir:
The idea is that we need a top(1) kind of interface that display clients and sort them using different fields. Basically, to know which clients are using more resources - that's the current use case. So if you are changing the cephfs-top display based on fs selection, let's do it like the 'f' command or 'Z' command in top(1). Use a command alphabet to display a separate screen where you can select the filesystem from and on confirmation, update the display in the main cephfs-top screen. If you find any better UI idea from top(1) let me know.

Another thing to consider is how we would limit [1] the number of clients in 'all fs' screen, as there are groups (headers) for each fs now. I assume, the user has to judge a max value based on the 'all fs' display size like display maximum 5 groups.
[1] https://tracker.ceph.com/issues/55121

**Comment by vshankar** [comment]
> The idea is that we need a top(1) kind of interface that display clients and sort them using different fields. Basically, to know which clients are using more resources - that's the current use case. So if you are changing the cephfs-top display based on fs selection, let's do it like the 'f' command or 'Z' command in top(1). Use a command alphabet to display a separate screen where you can select the filesystem from and on confirmation, update the display in the main cephfs-top screen. If you find any better UI idea from top(1) let me know.

I agree to this. Let's align to top(1)'s interface.

**Pull request closed without merging**
