### PR TITLE
doc: Add Glance integration with Openstack Mitaka and Ceph Jewel.

### PR DESCRIPTION
**Pull request by FranBarrera**
Signed-off-by: Fran Barrera <franbarrera6@gmail.com>

### CODE REVIEW

**Comment by theanalyst** [comment]
it would make sense to move the text before the conf section... and the conf section needs to begin with a `::` for it to be displayed as preformatted

**Comment by FranBarrera** [comment]
I think it's fixed now.

**Comment by theanalyst** [comment]
thanks, lgtm

**Comment by FranBarrera** [comment]
I think that I can't do it, but I can create new pr with only one commit.

**Pull request closed without merging**
