### PR TITLE
mgr/prometheus: health_status provide detail health info

### PR DESCRIPTION
**Pull request by kungf**
now health_status only offer ceph HEALTH_* status, like:
0:HEALTH_OK
1:HEALTH_WARN
2:HEALTH_ERR

that's may not enough, people always want to know why ceph warn in the grafana dashboard or in the mail which monitoring platform  sent.

if one osd down without this patch, ceph_health_status metrics is:
`ceph_health_status 1.0`
but after this patch, it is :
`ceph_health_status{checks="{u'OSD_DOWN': {u'detail': [{u'message': u'osd.1 (root=default,host=wybld) is down'}], u'severity': u'HEALTH_WARN', u'summary': {u'message': u'1 osds down'}}, u'PG_DEGRADED': {u'detail': [{u'message': u'pg 2.0 is active+undersized+degraded, acting [2,0]'}, {u'message': u'pg 2.3 is active+undersized+degraded, acting [2,0]'}], u'severity': u'HEALTH_WARN', u'summary': {u'message': u'Degraded data redundancy: 7/63 objects degraded (11.111%), 2 pgs degraded'}}}"} 1.0`

Signed-off-by: kungf <yang.wang@easystack.cn>

### CODE REVIEW

**Comment by kungf** [comment]
@jcsp need a review, please

**Comment by kungf** [comment]
commit again， make warn more readable。
eg.
ceph_health_status{summary="1/3 mons down, quorum b,c; 21/63 objects misplaced (33.333%); "} 1.0

**Comment by jan--f** [comment]
I like the idea of having more detailed status information. The thought crossed my mind one or twice in the past. However I think its not a good solution to pass this detailed status as a label. The issue is that every time the labels changes a new time series is created. This will seriously bloat the prometheus database. (cp. https://prometheus.io/docs/practices/naming/#labels)
Grafana (one of the consumers of this data) and its prometheus plugin has no string manipulation capabilities on label values I know of, so presenting the health details messages is also an issue.
One potential solution would be to use a state table like we use now for the general health status. This would obviously be longer and we'd have to map all or most of the health messages to an arbitrary number and be aware of that mapping in Grafana. Data redundancy is also an issue since we already report down OSDs and PG status through other metrics.

**Comment by jcsp** [comment]
I agree with @jan--f that labels are not the right place for extra detail like this.

Each health check has a unique identifier (OSD_FULL, SLOW_OPS, etc): see http://docs.ceph.com/docs/mimic/rados/operations/health-checks/ .  The natural way to expose more detail about which health checks are failing would be to add a 0/1 prometheus metric for each of those health checks.  

As for adding string detail, I think prometheus just isn't the right place for that -- it does not have a string metric type, and afaik there is no right/efficient way to put strings in there.

**Comment by kungf** [comment]
@jan--f @jcsp learned, ths. hope a better way to store string information

**Pull request closed without merging**
