### PR TITLE
cephadm: enforce black formatting for cephadmlib

### PR DESCRIPTION
**Pull request by phlogistonjohn**
A few months ago when we were starting the cephadm refactoring effort in
earnest we agreed to use `black` to format the python files we moved
into `cephadmlib` (while leaving the formatting of cephadm.py as-is).
We created tox rules to check or apply black formatting but promptly
got lazy and stopped running the checks manually - they were not run
automatically.

Change the default environment list to call check-black to start
enforcing the use of black style formatting. At the same time, remove
the `fix` environment entirely. It is liable to leave uncommitted changes
in your working tree when run - unlike check-black. This moves cephadm
practices closer to ones I've seen widely used in other python
codebases.

Note that cephadm.py remains outside of this rule - it only requires
pep8 formatting (via flake8). cephadm.py should continue to be
disassembled and components moved into cephadmlib over time. flake8 also remains
in effect for cephadmlib, it's fast, finds obvious mistakes and does
some code-level linting (like unused vars) that black does not.

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [x] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [x] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), :pencil2: reformatting only
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests
  - [x] :fountain_pen: reformatting only

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Comment by phlogistonjohn** [comment]
jenkins test make check

**Review by adk3798 — APPROVED** [review]

**Comment by phlogistonjohn** [comment]
jenkins test dashboard cephadm

**Comment by phlogistonjohn** [comment]
Please continue reviewing/merging this PR. However, I don't think this is PR is sufficient any more because the ceph test runs in jenkins are driven by cmake and the cmake files are not-DRY - they require the exact tox environments to be run to be listed in the CMakeLists.txt.  I find this highly annoying and will look into an approach that makes running tox more DRY soon.

**Comment by adk3798** [comment]
https://pulpito.ceph.com/adking-2024-03-16_05:03:17-orch:cephadm-wip-adk-testing-2024-03-15-1513-distro-default-smithi/

mostly cluster log stuff + mds_upgrade_sequence. Other failures were either known or not reproducible.

**Comment by adk3798** [comment]
https://pulpito.ceph.com/adking-2024-03-16_05:03:17-orch:cephadm-wip-adk-testing-2024-03-15-1513-distro-default-smithi/

Tons of cluster log failures, not a problem for now. Other than that, it was just the mds_upgrade_sequence, staggered upgrade with agent (both of which are known problems), some failures installing things at the beginning of tests (known to happen occasionally), and a failure in the test_cephadm test related to idmap overrides for nfs, which I missed when we tested that PR originally `ERROR: required file missing from config-json: idmap.conf` but is not being caused by any PRs in this run.

Nothing to block merging PRs from this run.

**Pull request merged**
