### PR TITLE
objecter: can get stuck in redirect loop if osdmap epoch == last_force_op_resend

### PR DESCRIPTION
**Pull request by xinxinsh**
http://tracker.ceph.com/issues/11026

### CODE REVIEW

**Comment by dachary** [comment]
@xinxinsh how come the author of aced7aa is you although the signed-off-by are Jianpeng Ma and Sage Weil ?

**Comment by xinxinsh** [comment]
@dachary ,jianpeng directly modify on my branch, is there any problem?

**Comment by dachary** [comment]
@xinxinsh it's not a problem, I was just curious if it was an accident or intended.

**Comment by smithfarm** [comment]
@xinxinsh: could you add 

```
(cherry picked from def4fc4ae51174ae92ac1fb606427f4f6f00743e)
```

to the commit? This makes it identifiable as a backport.

**Comment by xinxinsh** [comment]
@smithfarm , updated

**Comment by dachary** [comment]
@smithfarm @xinxinsh it conflicts with #5043, could you please make it so they do not ? I will help with integration :-)

**Comment by xinxinsh** [comment]
@dachary , i will take a look

**Comment by xinxinsh** [comment]
@dachary , @smithfarm , merge conflict is introduced by variable last_force_resend in PR 4597 and variable ctx_budgeted in PR 5043, these two variables are added in the same location, can we just add   new commit to resolve this conflict when we merge these two PR, or adjust the location of one of variable ?

**Comment by dachary** [comment]
@xinxinsh @smithfarm I think the right way to deal with this is to wait for one of them to be merged and then deal with the others. I'll send a mail to the list, it's worth a discussion.

**Comment by dachary** [comment]
the objecter is used everywhere, http://pulpito.ceph.com/loic-2015-07-09_21:09:04-rados-firefly-backports---basic-multi is green, meaning this backport is ok to merge and see more tests.

**Pull request merged**
