### PR TITLE
mgr/dashboard: Prevent angular of getting stuck during installation

### PR DESCRIPTION
**Pull request by tspmelo**
Signed-off-by: Tiago Melo <tmelo@suse.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`

</details>

### CODE REVIEW

**Comment by tspmelo** [comment]
jenkins test dashboard

**Comment by bk201** [comment]
I did some tests and I'm afraid that `NG_CLI_ANALYTICS` environment variable is not presented when executing npm commands. I fight this for a while and find a [related page](https://stackoverflow.com/questions/35029277/how-to-modify-environment-variables-passed-to-custom-cmake-target). Turn out that `set(env{})` works in cmake configuration phase but not real make phase.

To simulate a "clean" environment, we can back up and remove `.angular-config.json` file under home directory. Here is its content if we had answered no for analytics question before:
```
{
  "version": 1,
  "cli": {
    "analytics": false
  }
}
```

The analysis question will show up again if we remove this file:
```
cd <build_dir>
rm ~/.angular-config.json
rm -r ../src/pybind/mgr/dashboard/frontend/node_modules
make mgr-dashboard-frontend-deps

# ... will ask for collecting permission again
```

Can't find an elegant way to fix this, one possible ugly fix is:

```diff
diff --git a/src/pybind/mgr/dashboard/CMakeLists.txt b/src/pybind/mgr/dashboard/CMakeLists.txt
index 03c4b4b571..08131ea456 100644
--- a/src/pybind/mgr/dashboard/CMakeLists.txt
+++ b/src/pybind/mgr/dashboard/CMakeLists.txt
@@ -6,7 +6,7 @@ function(add_npm_command)
   cmake_parse_arguments(NC "${options}" "${single_kw}" "${multi_kw}" ${ARGN})
   string(REPLACE ";" " " command "${NC_COMMAND}")
   if(NC_NODEENV)
-    string(REGEX REPLACE "^(npm .*)$" ". ${mgr-dashboard-nodeenv-dir}/bin/activate && \\1 && deactivate" command ${command})
+    string(REGEX REPLACE "^(npm .*)$" ". ${mgr-dashboard-nodeenv-dir}/bin/activate && NG_CLI_ANALYTICS=false \\1 && deactivate" command ${command})
   endif()
   string(REPLACE " " ";" command "${command}")
   add_custom_command(
@@ -48,12 +48,16 @@ else()
   )
 endif()
```

**Comment by tspmelo** [comment]
@bk201 pushed some changes that should fix that problem.
Could you try again? thanks

**Comment by bk201** [comment]
> @bk201 pushed some changes that should fix that problem.
> Could you try again? thanks

Thanks! Got this error:

```
dashboard frontend is being created
/bin/sh: npm: command not found
make[3]: *** [src/pybind/mgr/dashboard/CMakeFiles/mgr-dashboard-frontend-build.dir/build.make:712: ../src/pybind/mgr/dashboard/frontend/dist] Error 127
make[2]: *** [CMakeFiles/Makefile2:4901: src/pybind/mgr/dashboard/CMakeFiles/mgr-dashboard-frontend-build.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:4913: src/pybind/mgr/dashboard/CMakeFiles/mgr-dashboard-frontend-build.dir/rule] Error 2
make: *** [Makefile:1514: mgr-dashboard-frontend-build] Error 2

```
looks like this npm command is not replaced with a venv https://github.com/ceph/ceph/blob/cf10c66e529d16af8cb6a850aeb81a192e31ce16/src/pybind/mgr/dashboard/CMakeLists.txt#L86-L92

**Comment by jecluis** [comment]
fwiw, after the last push this is working for me. I also had the `npm missing` issue, but it was fixed once I properly patched the code rather than copying the changes manually (had a space in one of the regex).

**Comment by epuertat** [comment]
jenkins test make check

**Comment by tspmelo** [comment]
jenkins test make check

**Pull request merged**
