### PR TITLE
doc/rgw/lua: add info uploading a script in cephadm deployment

### PR DESCRIPTION
**Pull request by yuvalif**
## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [x] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [x] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by yuvalif** [comment]
jenkins test signed

**Comment by yuvalif** [comment]
updated doc: https://ceph--51422.org.readthedocs.build/en/51422/radosgw/lua-scripting/

**Comment by yuvalif** [comment]
jenkins test signed

**Comment by yuvalif** [comment]
jenkins test signed

**Comment by yuvalif** [comment]
@ceph/doc-writers ping

**Review by zdover23 — APPROVED** [review]
LGTM.

I'll attempt backports to Reef and Quincy now, but I don't expect them to work. ceph-pr-docs and the Docs check have been failing for the past forty-eight hours.

**Comment by zdover23** [comment]
https://github.com/ceph/ceph/pull/52298 - Reef backport
https://github.com/ceph/ceph/pull/52299 - Quincy backport

**Pull request merged**
