### PR TITLE
rgw: dump Last-Modified in Swift's responses for GET/HEAD on container.

### PR DESCRIPTION
**Pull request by rzarzynski**
Fixes: http://tracker.ceph.com/issues/20883
Signed-off-by: Radoslaw Zarzynski <rzarzyns@redhat.com>

### CODE REVIEW

**Comment by mattbenjamin** [comment]
@rzarzynski sounds like this is a bug fix;  in addition, have you found this is needed for tempest in downstream L testing?

**Comment by rzarzynski** [comment]
@mattbenjamin: IIRC Tempest doesn't enforce the header. The problem has been found with the functional tests of Swift.

**Comment by yuriw** [comment]
[wip-yuri3-testing-2018-02-15-1735](https://trello.com/c/E8jcp4b2/264-wip-yuri3-testing-2018-02-15-1735)

**Comment by cbodley** [comment]
jenkins test docs

**Comment by cbodley** [comment]
jenkins test docs

**Pull request merged**
