### PR TITLE
STS Testing Files

### PR DESCRIPTION
**Pull request by TRYTOBE8TME**
(cherry picked from commit c2c90eaf524087925b8a0993098a87132d4940bd)

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by alimaredia** [comment]
@TRYTOBE8TME Do you have any runs of this working via teuthology-suite?

**Comment by TRYTOBE8TME** [comment]
> @TRYTOBE8TME Do you have any runs of this working via teuthology-suite?

Yes, I've tested this in teuthology and all the cases were passing. Here's the link for the reference: https://pulpito.ceph.com/kapandya-2020-07-09_08:47:53-rgw:sts-master-distro-basic-smithi/

**Comment by TRYTOBE8TME** [comment]
jenkins test make check

**Comment by TRYTOBE8TME** [comment]
jenkins test dashboard backend

**Comment by TRYTOBE8TME** [comment]
jenkins test make check

**Comment by TRYTOBE8TME** [comment]
The "make check" is failing with the error "run-tox-qa", which doesn't seem to be an error due to any changes in my code. So, @pritha-srivastava I think this is ready to go.

**Comment by pritha-srivastava** [comment]
@alimaredia : This PR has tests for AssumeRole and GetSessionToken. Kalpesh is still working on AssumeRoleWithWebIdentity. I think this PR can be merged? @mattbenjamin

**Comment by cbodley** [comment]
jenkins test make check

**Comment by TRYTOBE8TME** [comment]
I've merged the test file in s3tests_boto3 and have checked it's running in pulpito and it passes all the cases successfully. Following  is the link of the run: http://pulpito.front.sepia.ceph.com/kapandya-2020-08-17_13:35:45-rgw:sts-master-distro-basic-smithi/

So, @alimaredia, @pritha-srivastava should I go ahead and merge this PR?

**Comment by cbodley** [comment]
seeing tests failures here: https://tracker.ceph.com/issues/47588

**Comment by TRYTOBE8TME** [comment]
I'll check and update the required changes.

**Pull request merged**
