### PR TITLE
qa/tests:  Excluded  "'python34-cephfs','python34-rados'" for runs on nautilus

### PR DESCRIPTION
**Pull request by yuriw**
Signed-off-by: Yuri Weinstein <yweinste@redhat.com>

- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by yuriw** [comment]
http://pulpito.ceph.com/teuthology-2019-05-01_20:20:00-upgrade:client-upgrade-luminous-nautilus-distro-basic-smithi/

**Comment by dillaman** [comment]
Need to drop ```test_librbd_api``` tests

**Comment by yuriw** [comment]
@dillaman I want to finish https://github.com/ceph/ceph/pull/27078 and see how to apply it here.
One issue is that we keep this suite on `luminous' and if we drop `test_librbd_api` tests we may need to have another suite on `nautilus`

**Comment by dillaman** [comment]
... well the ```test_librbd_api``` test will always fail since the Nautilus ```librados``` C++ ABI is different (i.e. you cannot use Nautilus ```ceph_test_librbd_api``` using a Luminous ```librados.so```).

**Pull request merged**
