### PR TITLE
pacific: mgr/dashboard: dashboard help command showing wrong syntax for login-banner 

### PR DESCRIPTION
**Pull request by Sarthak0702**
backport tracker: https://tracker.ceph.com/issues/56164

---

backport of https://github.com/ceph/ceph/pull/46765
parent tracker: https://tracker.ceph.com/issues/56137

this backport was staged using ceph-backport.sh version 16.0.0.6848
find the latest version at https://github.com/ceph/ceph/blob/main/src/script/ceph-backport.sh

### CODE REVIEW

**Comment by Sarthak0702** [comment]
jenkins test dashboard

**Comment by Sarthak0702** [comment]
jenkins test dashboard

**Comment by Sarthak0702** [comment]
jenkins test dashboard

**Comment by Sarthak0702** [comment]
jenkins test dashboard cephadm

**Comment by Sarthak0702** [comment]
jenkins test api

**Comment by epuertat** [comment]
Unrelated failure: https://tracker.ceph.com/issues/56388

**Pull request merged**
