### PR TITLE
qa/workunits: identify ceph test clusters

### PR DESCRIPTION
**Pull request by yaarith**
When testing telemetry, we identify clusters with
organization = 'ceph-qa'.

Signed-off-by: Yaarit Hatuka <yaarit@redhat.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [x] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by yaarith** [comment]
fix for https://github.com/ceph/ceph/pull/48291

**Review by ljflores — APPROVED** [review]

**Comment by ljflores** [comment]
LGTM!

**Comment by ljflores** [comment]
@yaarith the jobs are taking a very long time. It seems like we might be hitting https://tracker.ceph.com/issues/57756 again, which is not a Telemetry issue, but an orchestrator one. If I'm right, the jobs will likely die due to a timeout. If that happens, I will ask Adam King to take a look.

**Comment by ljflores** [comment]
@yaarith I checked the logs; the tests failed because they are referencing quay.ceph.io (which points to the corrupted VM) in order to perform the upgrade. Dan Mick is currently trying to fix this, so I will rerun the jobs once I get the all-clear.

**Comment by yaarith** [comment]
Thanks @ljflores, the logs look good, we can merge this.

**Pull request merged**
