### PR TITLE
osd: check fsid is normal before osd mkfs

### PR DESCRIPTION
**Pull request by songbaisen**
osd:  check fsid is normal before osd mkfs

Signed-off-by: song baisen <song.baisen@zte.com.cn>

### CODE REVIEW

**Comment by songbaisen** [comment]
@liewegas  Done! By the way would you like give me the right to put the label myself. :smile:

**Comment by liewegas** [comment]
What is the specific motivation for this change?  looking at it more closely, i'm worried there is a valid case where the caller isn't explicitly providing the uuid and we are pulling it out of the existing superblock.  Not sure, though, there are so many paths to this code...

**Comment by songbaisen** [comment]
@liewegas   The motivation  is  we can early  find the error before the osd mkfs.

**Comment by tchaikov** [comment]
http://pulpito.ceph.com/kchai-2017-04-21_03:04:04-rados-wip-kefu-testing---basic-mira/

**Comment by tchaikov** [comment]
@liewegas shall we merge this change?

**Pull request merged**
