### PR TITLE
rgw/rgw_op.cc: avoid copying in for loops

### PR DESCRIPTION
**Pull request by stiopaa1**
Signed-off-by: Michal Jarzabek <stiopa@gmail.com>

### CODE REVIEW

**Comment by mattbenjamin** [comment]
lgtm

**Comment by stiopaa1** [comment]
@mattbenjamin what do you propose for a commit message?

**Comment by yehudasa** [comment]
@mattbenjamin ping?

**Comment by mattbenjamin** [comment]
@oritwas @yuriw this has had needs-qa for 21 days;  does that mean it has been through a testing branch?  if not, can we add it to one now?  (if not, I'll merge later today)

**Pull request merged**
