### PR TITLE
test/cephadm: fix timeout issue

### PR DESCRIPTION
**Pull request by Svelar**
test/cephadm: fix timeout issue

When run make check(arm64) on omani series servers, eg.
https://jenkins.ceph.com/job/ceph-pull-requests-arm64/54751/
Shows:
python: timeout after 30 seconds
INFO     root:call_wrappers.py:284 Non-zero exit code 124 from /home/jenkins-build/build/workspace/ceph-pull-requests-arm64/src/cephadm/.tox/py3/bin/python -c for i in range(1000000): print(i, flush=True)

Fixes: https://tracker.ceph.com/issues/65355

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [x] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Comment by Svelar** [comment]
jenkins test make check arm64

**Comment by Svelar** [comment]
jenkins test make check arm64

**Comment by Svelar** [comment]
jenkins test make check

**Comment by Svelar** [comment]
jenkins test make check

**Comment by Svelar** [comment]
jenkins test make check

**Comment by adk3798** [comment]
jenkins test make check

**Review by phlogistonjohn — COMMENTED** [review]
Hi there, this test is intended to try and ensure that the internal libs in cephadm properly handle lots of output from a child process. I'm a little worried that just doing 10x fewer iterations will cause the original problem case no longer to occur, at least on x86 machines in the lab. 

That said, I'm not strictly against the change, I am just trying to think if we can do something not too complicated would work well for a wider variety of hosts. Let me think on it a day or two and if you don't hear back ping me and I'll approve in order not to let perfect be the enemy of good enough.

**Comment by phlogistonjohn** [comment]
After hitting send I thought what if we figure out how long the 1000000 iterations on an x86_64 machine is and then convert it to generate output for that length of time? That should avoid the timeout and even if it might not produce as much output on the arm machines it may better capture the spirit of the test. WDYT?

**Comment by Svelar** [comment]
> After hitting send I thought what if we figure out how long the 1000000 iterations on an x86_64 machine is and then convert it to generate output for that length of time? That should avoid the timeout and even if it might not produce as much output on the arm machines it may better capture the spirit of the test. WDYT?

Hi @phlogistonjohn , thanks for reviewing.

First of all, how '1000000' is picked at beginning? This issue only occurs on omani machines (arm) in the lab, but 'generate output for that length of time' would be a great idea.

**Comment by phlogistonjohn** [comment]
> > After hitting send I thought what if we figure out how long the 1000000 iterations on an x86_64 machine is and then convert it to generate output for that length of time? That should avoid the timeout and even if it might not produce as much output on the arm machines it may better capture the spirit of the test. WDYT?
> 
> Hi @phlogistonjohn , thanks for reviewing.
> 
> First of all, how '1000000' is picked at beginning? 

I don't think I was being particularly scientific. I vaguely remember adding zeros until I hit an issue with the older code.

This issue only occurs on omani machines (arm) in the lab, but 'generate output for that length of time' would be a great idea.
> 

OK, thanks!

> I've found that reducing the jobs number (e.g. 22 -> 8) could solve this problem nicely. It's hard to decide whether to change this number globally.

Yeah, understood.

Let me look into the time limited version. I'll ping here when I have something.

**Comment by Svelar** [comment]
@phlogistonjohn Or can we increase timeout from 30 to like 60? 

```
class FakeContext:
    """FakeContext is a minimal type for passing as a ctx, when
    with_cephadm_ctx is not appropriate (it enables too many mocks, etc).
    """

    timeout = 60
```

**Comment by phlogistonjohn** [comment]
If that works for you it works for me.

**Comment by Svelar** [comment]
> If that works for you it works for me.

Re-check plz. @phlogistonjohn

**Review by phlogistonjohn — COMMENTED** [review]
looks ok to me, thanks

**Comment by Svelar** [comment]
jenkins retest this please

**Comment by Svelar** [comment]
> looks ok to me, thanks

Could you approve this?

**Review by phlogistonjohn — APPROVED** [review]

**Comment by Svelar** [comment]
https://jenkins.ceph.com/job/ceph-pull-requests-arm64/55163/consoleFull#596024309e840cee4-f4a4-4183-81dd-42855615f2c1

Seems like 60 seconds is not enough, any idea? @phlogistonjohn

**Pull request merged**
