### PR TITLE
rgw: add bucket request payment feature usage statistics integration

### PR DESCRIPTION
**Pull request by jmunhoz**
Add usage statistics support for the bucket request payment feature.

Fixes: #13834

Signed-off-by: Javier M. Mellid <jmunhoz@igalia.com>

### CODE REVIEW

**Comment by jmunhoz** [comment]
@yehudasa usage log example covering different cases available at:

http://tracker.ceph.com/attachments/download/2086/bpr-ul-example-001.txt

**Comment by jmunhoz** [comment]
@yehudasa Not sure if I am understanding rightly. It is expected breaking the compatibility with older entries due to indexation change (by bucket user instead of bucket owner with the new code). Would it make sense some kind of compatibility with the old entries?

**Comment by yehudasa** [comment]
@jmunhoz the problem is that it would be incompatible with previously created entries, so people who upgrade will lose their history.

**Comment by liewegas** [comment]
@jmunhoz Does Yehuda's comment make sense?  Do you need additional guidance?

**Comment by jmunhoz** [comment]
@liewegas yes, the Yehuda's comment makes a lot of sense. Right now I am working on the AWS4 auth corner cases and the testing coverage with Yehuda but my idea is coming back here asap. I would have to review the code again but I remember I didn't find any clear way to guarantee this compatibility in a quick look. As seen at

http://tracker.ceph.com/attachments/download/2086/bpr-ul-example-001.txt

the approach looks quite different from the current one. Any suggestion to connect both approaches? thanks sage!

**Comment by yehudasa** [comment]
@jmunhoz seehttps://github.com/yehudasa/ceph/commit/0bfeef25f71bf9902039b773292c2c8d86e61800

it's incomplete, but that's the basic idea. (there's also a needed string -> rgw_user transition that we need to do now that is missing).

**Comment by jmunhoz** [comment]
@yehudasa I got the idea. I have the code compiling now. I will try to fit the missing bits. thanks!

**Comment by jmunhoz** [comment]
@yehudasa https://github.com/jmunhoz/ceph/commits/wip-rgw-payer-yehuda

I did some changes over your initial patch although I am not getting the expected result. Operations with payer are added under the owner statistics. All things are compiling and it looks working ok but the way how we insert the puser and its log_add_op datapath. I suspect encoding/decoding could be the reason. Do you see any strange thing in the new encoding/decoding code? I think the transitions between strings and rgw_user are ok.

**Comment by yehudasa** [comment]
@jmunhoz see https://github.com/yehudasa/ceph/tree/wip-rgw-payer-yehuda

**Pull request merged**
