### PR TITLE
[DNM] performance verification

### PR DESCRIPTION
**Pull request by changchengx**
## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by changchengx** [comment]
test this please

**Comment by changchengx** [comment]
@tchaikov 
Do you know how to enable "perf test" for this PR?
I need to make some experiments for below PR to check the system level performance problem.
  https://github.com/ceph/ceph/pull/35080 (use AVX2 to accelerate base64 encode/decode)
However, I don't want to push the experimental changes to PR 35080.

**Comment by tchaikov** [comment]
@changchengx i'd suggest you do the perf test by yourself with different workloads and to understand the bottle neck. as the "perf test" performed by jenkins is very primitive, it is merely served as a reference of reviewer.

**Comment by tchaikov** [comment]
jenkins test classic perf

**Comment by tchaikov** [comment]
@changchengx i discussed with the team, we think it might not be worthy to trade the extra complexity and maintenance overhead with this improvement even if the performance does not hurt if the executable does not run a CPU with does not have AVX2 support.

**Comment by changchengx** [comment]
@tchaikov 
Thanks for your feedback.
I need to check whether system-level performance is really downgraded and how it happened.
I'll feedback to you when I get the result.

**Pull request closed without merging**
