### PR TITLE
rgw: bucket listing hangs on versioned buckets

### PR DESCRIPTION
**Pull request by theanalyst**
http://tracker.ceph.com/issues/13536

### CODE REVIEW

**Comment by dachary** [comment]
@dang  does this backport look good to merge ? It passed a run of the hammer rgw suite ( see http://tracker.ceph.com/issues/13356#note-23 ).

**Comment by dachary** [comment]
@dang ping ?

**Comment by dang** [comment]
@dachary Sorry, missed it the first time around.  Looks good.

**Comment by dachary** [comment]
@dang no worries, there was no urgency of any kind :-) Thanks ! The next time you merge, it would be great if you could add a Reviewed-by: line at then end of the merge commit message.

**Pull request merged**
