### PR TITLE
rgw:bucket check remove _multipart_ prefix

### PR DESCRIPTION
**Pull request by dwj192**
Fixes: 13724

Signed-off-by: Weijun Duan <duanweijun@h3c.com>

### CODE REVIEW

**Comment by dwj192** [comment]
root@compiler:/home/dwj/git/ceph/src# ./radosgw-admin bucket check --bucket=key-bkt
[
"_multipart_TODO",
"_multipart_vstart.sh" 
]

my modify：
root@compiler:/home/dwj/git/ceph/src# ./radosgw-admin bucket check --bucket=key-bkt
[
"TODO",
"vstart.sh" 
]

**Comment by dwj192** [comment]
@yehudasa  
1. I can't understand why there add _multipart_ to every obj, even the obj is not multipart obj
2. there will generate  a obj named objname.meta in what situation?
3. In the function check_bad_index_multipart 
 
```
    string name = oid.substr(0, pos);
        string suffix = oid.substr(pos + 1);

        if (suffix.compare("meta") == 0) {
          meta_objs[name] = true;
        } else {
          all_objs[key] = name;
        }
```
then 
```
for (aiter = all_objs.begin(); aiter != all_objs.end(); ++aiter) {
    string& name = aiter->second;

    if (meta_objs.find(name) == meta_objs.end()) {
      objs_to_unlink.push_back(aiter->first);
    }
  }
```
according to the code，the logic is : 
  a. when my obj name is: myfile, then there must had a obj named: _multipart_myfile.meta, the obj _multipart_myfile will not unlink; 
  b.when my obj name is: myfile1.txt. then there  must had a obj named: _multipart_myfile1.meta, the obj _multipart_myfile1.txt will not unlink;
what it means?

thanks yehudasa!

**Comment by yehudasa** [comment]
@dwj192 maybe we shouldn't display these entries at all? It's incorrect to just remove the namespace.

**Comment by liewegas** [comment]
@dwj192 ping

**Comment by mattbenjamin** [comment]
@dwj192 hi weijun, could you acknowledge?  yehudasa is suggesting just not projecting the inapplicable objects;  do you concur?  if so, would you amend the change?

(@oritwas)

**Comment by yehudasa** [comment]
@dwj192 sorry for the late turn around, took me a while to understand what this bug is actually about.

**Pull request merged**
