### PR TITLE
common: use unordered_map instead of map in cache

### PR DESCRIPTION
**Pull request by XinzeChi**
Search complexity.

For map, it is O(lgN)
For unordered_map, it is O(1) 

Signed-off-by: Xinze Chi <xmdxcxz@gmail.com>

### CODE REVIEW

**Comment by tchaikov** [comment]
@XinzeChi xinze, could you put the rationale in the commit message? why unordered_map is better than map in this case? for example, its impacts on performance? thanks.

**Comment by tchaikov** [comment]
thanks @XinzeChi for explaining the reason in the comment. i meant you could update it in the commit log. but i get your point. the `std::unordered_map` has its advantage over `std::map` in some cases. but the cache could be fairly large and sparse. in that case, the rb tree would perform better, i guess. and `std::unordered_map` could suffer from the rehash and bad distribution of inserted elements.

anyway, it's just my two cents.

**Comment by yuyuyu101** [comment]
@liewegas Maybe we can add a new label named "performance" to track any potential performance PRs, it will be good to look back for performance reason.

**Comment by dachary** [comment]
@XinzeChi looks good to me. Since lower_bound is only used on the weak_refs, order does not matter. Could you please rebase and repush ? Just so that the bot compiles against the current master. After it confirms,
<pre>
Reviewed-by: Loic Dachary &lt;ldachary@redhat.com>
</pre>

**Comment by tchaikov** [comment]
@dachary yes, the order of std::map is a bonus feature we don't care, but its performance is very stable. unordered_map has its downsides as a hashmap as listed in my last comment. that's why i was not 100% sure about this pull request. anyway, i am good if you think it's a safe change.

**Comment by dachary** [comment]
@tchaikov I don't have actual experience with that but I'd be surprised if it's doing worse, overall. And I can't think of a situation where the hash rehash time would create a problem. 

The worst possible case would be that a thread is blocked long enough to trigger timeouts or a race condition that was not previously discovered. Is it what you also had in mind ?

**Comment by gregsfortytwo** [comment]
Woah, no way guys. Hash maps take up *way* more space than maps do, and we've had memory issues in the past from using hash_maps on a per-PG basis (like we use the SharedLRU). And as a rule we don't merge performance-only patches (especially ones with performance tradeoffs!) without performance data.

If we have performance tests indicating that the use of a regular map is an issue for some code, then we can look at changing things (probably on a configurable basis so we only use it for the hot one). But the usual size of these caches is on the order of 1024 entries, and that doesn't take many instructions to descend to the bottom.

**Comment by dachary** [comment]
@XinzeChi maybe you have performance analysis results that suggest this pull request would significantly improve things ?

**Comment by mslovy** [comment]
Hi all. @XinzeChi  @tchaikov  @gregsfortytwo @dachary. Any evidence indicates that unordered_map really cost much more memery, and impact performance because of rehash?
Based on my knowledge,  bucket acts as a slot, but actually allocate memory when real data inserted? I not sure, but under my test, when half of elements erased, buckets_size remains the same but memory is already free. 
Also, no evidence shows unordered_map costs more memory than map, but save insertion and searching times?

For map:
memery init--> %CPU:0.0	                MEM:2572KB
cost for 100000 insert: 57334800ns
memory after 100000 insert-->               MEM:16764KB
memory after 50000 items erased-->      MEM:9900KB
cost for 200000 insert: 114140824ns
memory after 200000 insert-->           MEM:30884KB

For unordered_map:
memery init-->                                    MEM:2612KB
cost for 100000 insert: 30892844ns
memory after 100000 insert-->             MEM:16396KB
memory after 50000 items erased-->   MEM:10092KB
cost for 200000 insert: 49562857ns
memory after 200000 insert-->             MEM:29760KB 

Am I right, or missing something?
test program in attachment and change it to .cc,  with complie flag -std=c++0x -ltcmalloc -lrt
[map_test.txt](https://github.com/ceph/ceph/files/59346/map_test.txt)

On the other side, FDcache is no need to use get_next and low_bound, so weak_ref also cannot be used as unordered_map. And with my test, save the lookup() execute time as below:

Searching speed:
current map<>
cache_size     shard      average cost
5120             128          1.74us
5120             10            2.43us
    
with unordered_map<>
cache_size     shard      average cost
5120             128          1.21us
5120             10            1.39us

1)save cpu about 0.2% under all-hits cases, will save more under low hit rates and,
2)release the ratio (cache_size:shard) to make cache more effective

**Comment by liewegas** [comment]
IIRC the memory explosion we observed was ages ago with hash_map from old versions of the STL; perhaps it is better now.

Also, the issue was that even a small/sparse map used lots of memory.  We have a SharedLRU for every PG with just 64 items.  The SharedLRU knows the expected size of the map... if that can be passed into the unordered_map to inform the number of buckets then I think we're fine (this is true with boost::intrusive::unordered_set, but I haven't looked at unordered_map).

**Comment by mslovy** [comment]
Yes, we can call rehash(int bucket_number) to pre-set the bucket number. 
refer to http://www.cplusplus.com/reference/unordered_map/unordered_map/rehash/
I think this kind of work would make sense now? wait others comment

**Comment by liewegas** [comment]
That's perfect. If the SharedLRU etc constructor calls that to size the bucket array accordingly that should work great!

**Pull request closed without merging**
