### PR TITLE
mgr/dashboard: Update node version

### PR DESCRIPTION
**Pull request by tspmelo**
Updated node version to the latest LTS.

Updated 'HACKING.rst' to reflect the current node/npm version requirements.

Signed-off-by: Tiago Melo <tmelo@suse.com>

### CODE REVIEW

**Comment by tchaikov** [comment]
@wjwithagen what are the npm and node versions in FreeBSD?

**Comment by s0nea** [comment]
Which Teuthology tests are required to test this PR? - Is it sufficient to run the dashboard related tests?

**Comment by tchaikov** [comment]
@s0nea i think so. the dashoboard related tests would suffice.

**Comment by s0nea** [comment]
QA test run was successful:
- https://shaman.ceph.com/builds/ceph/wip-tdehler-testing-22639/
- http://pulpito.ceph.com/tdehler-2018-06-22_09:13:04-rados:mgr-wip-tdehler-testing-22639-distro-basic-smithi/

**Pull request merged**
