### PR TITLE
rgw: correct "radosgw-admin zone rm" and " radosgw-admin zonegroup rm“ cmd

### PR DESCRIPTION
**Pull request by zhangsw**
Fixes: Http://tracker.ceph.com/issues/38196

Signed-off-by: zhang Shaowen <zhangshaowen@cmss.chinamobile.com>

### CODE REVIEW

**Comment by cbodley** [comment]
thanks @zhangsw, there's been some discussion about this issue in https://github.com/ceph/ceph/pull/29573#issuecomment-526596549

**Comment by cbodley** [comment]
@zhangsw that change merged in https://github.com/ceph/ceph/pull/30060

**Comment by zhangsw** [comment]
@cbodley Sorry for the late replay. It seems that `zonegroup delete` hasn't been fixed in #30060

**Comment by cbodley** [comment]
> @cbodley Sorry for the late replay. It seems that `zonegroup delete` hasn't been fixed in #30060

oops! would you mind applying that same fix for zonegroup delete?

**Comment by zhangsw** [comment]
@cbodley At present, `zonegroup delete` is used for deleteing a zonegroup, and `zonegroup rm` is used for removing a zone from zonegroup. Should we keep using the `zonegroup delete` cmd and just correct the help info?

**Comment by cbodley** [comment]
> Should we keep using the zonegroup delete cmd and just correct the help info?

yeah, that sounds good!

**Pull request closed without merging**
