### PR TITLE
provide an additional hint when running into I/O closed exception

### PR DESCRIPTION
**Pull request by michaelalang**
…rom execnet seen as

            Error EINVAL: Can't communicate with remote host `127.0.0.1`, possibly because python3 is not installed there: cannot send (already closed?)

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Review by adk3798 — APPROVED** [review]

**Comment by adk3798** [comment]
@michaelalang this looks good, but we need to do some fixup for the commit. Ceph likes commit messages to start with what component is being affected. In this case it's "mgr/cephadm" for hte component so you would want the commit to start with something like "mgr/cephadm: provide an additional hint when . . ." Additionally, we require all commits to the Ceph repo to be signed off (Signed-off-by: Firstname Lastname <email>) in the commit message. If you do a "git commit --amend -s" it should add the signature. You can see in the checks on this PR the "Signed-off-by" check is failing for this reason. We can't merge without that check passing. If you fix those couple thing up we should be good here.

**Comment by michaelalang** [comment]
Hi @adk3798,

I tried following your suggestion to amend the commit with the signed-off and commit log changes. The checks still seem to fail. 
Please let me know what I can change to get this working. Apologies for _wasting_ your time with such things ...

All the best and kind regards
Michi

**Comment by adk3798** [comment]
> Hi @adk3798,
> 
> I tried following your suggestion to amend the commit with the signed-off and commit log changes. The checks still seem to fail. Please let me know what I can change to get this working. Apologies for _wasting_ your time with such things ...
> 
> All the best and kind regards Michi

What you did was correct. It was just the Signed-off-by check in particular I was talking about which is now passing. Some of the other checks are just a bit flaky and fail sometimes. I can rerun them later, but everything should be okay here from your side. I'm just going to include this in a testing batch and should be able to merge it after.

**Comment by michaelalang** [comment]
@adk3798 okay thanks for the explanation and support.
All the best and kind regards
Michi

**Comment by adk3798** [comment]
https://pulpito.ceph.com/adking-2022-08-09_15:27:00-orch:cephadm-wip-adk-testing-2022-08-09-0854-distro-default-smithi/

failures due to infra issues with rhel tests. All passed in rerun
https://pulpito.ceph.com/adking-2022-08-09_20:24:21-orch:cephadm-wip-adk-testing-2022-08-09-0854-distro-default-smithi/

**Pull request merged**
