### PR TITLE
[DNM] jewel: client: dual client segfault with racing ceph_shutdown

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/21526

### CODE REVIEW

**Comment by smithfarm** [comment]
Does this need rados suite as well as fs?

**Comment by jcsp** [comment]
@smithfarm probably just need the `rados/verify` bit rather than the whole rados suite

**Comment by smithfarm** [comment]
This PR adds ShutdownRace test case to ceph_test_libcephfs, but it appears to segfault every time: http://tracker.ceph.com/issues/23556

Removing this PR from the integration branch and retesting.

**Comment by smithfarm** [comment]
This PR passed a rados suite at http://tracker.ceph.com/issues/21742#note-21

**Comment by batrick** [comment]
http://tracker.ceph.com/issues/21526#note-4

**Pull request closed without merging**
