### PR TITLE
mds: add override in headers

### PR DESCRIPTION
**Pull request by Liuchang0812**
Signed-off-by: liuchang0812 <liuchang0812@gmail.com>

### CODE REVIEW

**Comment by batrick** [comment]
Can you explain how you generated this patch?

**Comment by jcsp** [comment]
This has merge conflicts.

**Comment by Liuchang0812** [comment]
@batrick LLVM has a tool called clang-tidy, that it could do a lot of things base on semantic analyse. I use clang-tidy's  `clang-tidy -checks="-*, modernize-use-override"  a.cpp -- -std=c++11` commond to add override automatically. 

@jcsp Roger that, I will rebase it.

**Comment by Liuchang0812** [comment]
change log:
1. rebased forward to master

**Comment by batrick** [comment]
@Liuchang0812 thanks for explaining. Can you add a note about that to the commit message for posterity. Thanks.

**Comment by Liuchang0812** [comment]
@batrick roger that, I will add explaining to commit message soon

**Comment by Liuchang0812** [comment]
change log:

1. add note about clang-tidy in commit message

**Comment by Liuchang0812** [comment]
@batrick @jcsp hi, would you mind taking a look?

**Comment by batrick** [comment]
`Reviewed-by: Patrick Donnelly <pdonnell@redhat.com>`

**Comment by Liuchang0812** [comment]
@batrick @jcsp thanks. It would be better to merge it as soon as possible, because it contains a lot of changes and conflicts with other patches easily.

**Pull request merged**
