### PR TITLE
msg: daemonize before create msgrs

### PR DESCRIPTION
**Pull request by yuyuyu101**

### CODE REVIEW

**Comment by yuyuyu101** [comment]
replacing https://github.com/ceph/ceph/pull/10600

**Comment by liewegas** [comment]
This seems to be breaking a bunch of little stuff.  MDS's won't start properly, and also e.g.
<pre>
2017-02-16T00:40:50.602 INFO:tasks.workunit.client.0.smithi203.stdout:                 api_lock: [ RUN      ] LibRadosLockECPP.ListLockersPP
2017-02-16T00:40:50.602 INFO:tasks.workunit.client.0.smithi203.stdout:                 api_lock: /tmp/buildd/ceph-12.0.0-413-g1c5648d/src/test/librados/lock.cc:330: Failure
2017-02-16T00:40:50.603 INFO:tasks.workunit.client.0.smithi203.stdout:                 api_lock:       Expected: me
2017-02-16T00:40:50.603 INFO:tasks.workunit.client.0.smithi203.stdout:                 api_lock:       Which is: "client.0"
2017-02-16T00:40:50.603 INFO:tasks.workunit.client.0.smithi203.stdout:                 api_lock: To be equal to: it->client
2017-02-16T00:40:50.603 INFO:tasks.workunit.client.0.smithi203.stdout:                 api_lock:       Which is: "client.4548"
2017-02-16T00:40:50.603 INFO:tasks.workunit.client.0.smithi203.stdout:                 api_lock: [  FAILED  ] LibRadosLockECPP.ListLockersPP (734 ms)
2017-02-16T00:40:50.603 INFO:tasks.workunit.client.0.smithi203.stdout:                 api_lock: [ RUN      ] LibRadosLockECPP.BreakLockPP
2017-02-16T00:40:50.603 INFO:tasks.workunit.client.0.smithi203.stdout:                 api_lock: /tmp/buildd/ceph-12.0.0-413-g1c5648d/src/test/librados/lock.cc:371: Failure
2017-02-16T00:40:50.603 INFO:tasks.workunit.client.0.smithi203.stdout:                 api_lock:       Expected: me
2017-02-16T00:40:50.603 INFO:tasks.workunit.client.0.smithi203.stdout:                 api_lock:       Which is: "client.0"
2017-02-16T00:40:50.604 INFO:tasks.workunit.client.0.smithi203.stdout:                 api_lock: To be equal to: it->client
2017-02-16T00:40:50.604 INFO:tasks.workunit.client.0.smithi203.stdout:                 api_lock:       Which is: "client.4548"
2017-02-16T00:40:50.604 INFO:tasks.workunit.client.0.smithi203.stdout:                 api_lock: [  FAILED  ] LibRadosLockECPP.BreakLockPP (233 ms)
</pre>

**Comment by yuyuyu101** [comment]
this error confused me... @liewegas @tchaikov @gregsfortytwo do you have any idea to this problem?

**Comment by gregsfortytwo** [comment]
I don't know how the init code works at all, but I can't imagine this working without changing that since it's obviously designed to handle moving the OS-allocated messenger data structures around between the parent and child processes correctly.

**Pull request closed without merging**
