### PR TITLE
mgr/dashboard: amend the look & feel of the login password form

### PR DESCRIPTION
**Pull request by s0nea**
Amend the look & feel a bit in order to be more similar to the login form.

**Before:**
Screenshot_2020-11-13_11-31-53

**After:**
Screenshot_2020-11-13_15-47-36

Fixes: https://tracker.ceph.com/issues/48222
Signed-off-by: Tatjana Dehler <tdehler@suse.com>

## Checklist
- [x] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by nizamial09** [comment]
jenkins test docs

**Review by nizamial09 — COMMENTED** [review]
LGTM apart from one thing.

You can see the difference in padding between those two text warnings in login form and login password change form.

warning

warning-password

**Comment by s0nea** [comment]
> You can see the difference in padding between those two text warnings in login form and login password change form.

Thanks for the comment @nizamial09! I'll take a look at it.

**Comment by s0nea** [comment]
@nizamial09 better now? :smile:

Screenshot_2020-11-16_13-36-20

**Comment by nizamial09** [comment]
> @nizamial09 better now? 

@s0nea Perfect ;) Thank you

**Review by nizamial09 — APPROVED** [review]

**Comment by s0nea** [comment]
What I still don't like about the PR is the red border here:

Screenshot_2020-11-16_14-09-16

I think it's because the component extends `UserPasswordFormComponent`. I'll take a look if it's possible to hide it.

**Review by votdev — APPROVED** [review]
Looks really nice.

**Pull request merged**
