### PR TITLE
mimic: qa/rgw: move ragweed upgrade test into upgrade/luminous-x

### PR DESCRIPTION
**Pull request by cbodley**

### CODE REVIEW

**Comment by cbodley** [comment]
@liewegas this cherry-picks the two original commits, then adds another commit to rename all of the test branches to ceph-mimic. how do we prevent that last change from being merged back into master?

**Comment by cbodley** [comment]
http://pulpito.ceph.com/cbodley-2018-05-07_13:04:57-upgrade:luminous-x:parallel-mimic-distro-basic-smithi/

**Comment by cbodley** [comment]
the rgw suite passes when targeting ceph-mimic test branches: http://pulpito.ceph.com/cbodley-2018-05-07_13:05:31-rgw-mimic-distro-basic-smithi/

**Comment by liewegas** [comment]
Hmm, easiest is probably to merge to mimic, merge to master, then revert 
the change in master.

**Comment by liewegas** [comment]
http://pulpito.ceph.com/sage-2018-05-22_02:42:59-rgw-wip-sage3-testing-2018-05-21-1130-distro-basic-smithi/

**Pull request merged**
