### PR TITLE
luminous: osd: replica read can trigger cache promotion

### PR DESCRIPTION
**Pull request by shinobu-x**
http://tracker.ceph.com/issues/22402

### CODE REVIEW

**Comment by shinobu-x** [comment]
test this please

**Comment by shinobu-x** [comment]
test this please

**Comment by yuriw** [comment]
[wip-yuri4-testing-2018-01-29-1824-luminous](https://trello.com/c/PmEPazkj/249-wip-yuri4-testing-2018-01-29-1824-luminous)

**Comment by yuriw** [comment]
[wip-yuri5-testing-2018-01-31-1611-luminous](https://trello.com/c/zMXuucNR/252-wip-yuri5-testing-2018-01-31-1611-luminous)

**Pull request merged**
