### PR TITLE
quincy: qa/suites/krbd: stress test for recovering from watch errors for -o exclusive

### PR DESCRIPTION
**Pull request by idryomov**
backport tracker: https://tracker.ceph.com/issues/67171

---

backport of https://github.com/ceph/ceph/pull/58781
parent tracker: https://tracker.ceph.com/issues/67097

### CODE REVIEW

**Review by ajarr — APPROVED** [review]

**Comment by idryomov** [comment]
jenkins test make check

**Comment by idryomov** [comment]
jenkins test make check

**Comment by idryomov** [comment]
jenkins test make check

**Comment by idryomov** [comment]
jenkins test make check

**Comment by idryomov** [comment]
jenkins test make check

**Comment by idryomov** [comment]
jenkins test make check

**Comment by idryomov** [comment]
https://pulpito.ceph.com/dis-2024-07-25_18:15:40-krbd-quincy-wip-exclusive-option-states-default-smithi/
https://pulpito.ceph.com/dis-2024-07-25_18:18:27-krbd-quincy-testing-default-smithi/

**Pull request merged**
