### PR TITLE
nautilus: mgr/dashboard: list configured prometheus alerts

### PR DESCRIPTION
**Pull request by votdev**
backport tracker: https://tracker.ceph.com/issues/44690

---

backport of https://github.com/ceph/ceph/pull/31937
parent tracker: https://tracker.ceph.com/issues/42877

this backport was staged using ceph-backport.sh version 15.1.1.389
find the latest version at https://github.com/ceph/ceph/blob/master/src/script/ceph-backport.sh

### CODE REVIEW

**Comment by votdev** [comment]
jenkins test make check

**Comment by votdev** [comment]
jenkins test make check

**Comment by votdev** [comment]
jenkins test make check

**Comment by votdev** [comment]
jenkins test make check

**Comment by callithea** [comment]
- [pkg build](https://shaman.ceph.com/builds/ceph/wip-laura-testing-nautilus-31586-34238/)
- [QA run](http://pulpito.ceph.com/laura-2020-04-01_12:54:07-rados:dashboard-wip-laura-testing-nautilus-31586-34238-distro-basic-smithi/) [WIP]

**Comment by smithfarm** [comment]
@votdev I'm confused why the commit ea1c8c7ef7f494208aec1c59d12fec2da759784a "mgr/dashboard: check if user has config-opt permissions before retrie..." is cherry-picked here - it was already backported to nautilus by https://github.com/ceph/ceph/pull/32827 ? 

Also, cherry-picking a number of commits and then adding an extra commit adapting the cherry-picks is not ideal. Ideally, the adaptations needed for each commit would be made in the commit itself, and described in a "Conflicts" section.

(Note: there is a common misconception that "Conflicts" section is only for cherry-pick conflicts, but that is not the case - it is for any manual change that must be made, for whatever reason, to adapt the cherry-pick to the target branch.)

**Comment by votdev** [comment]
Superseded by https://github.com/ceph/ceph/pull/34373.

**Pull request closed without merging**
