### PR TITLE
osd/scrub: add scrub duration to pg stats

### PR DESCRIPTION
**Pull request by amathuria**
Addition of a SCRUB_DURATION column that shows how long the scrub/deep-scrub of a pg took.
This column will be displayed in the output of the "ceph pg dump --format=json" and "ceph pg ls-by-pool" commands.

Signed-off-by: Aishwarya Mathuria <amathuri@redhat.com>

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [x] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by amathuria** [comment]
```
[amathuri@localhost build]$ sudo bin/ceph pg ls-by-pool testbench
PG    OBJECTS  DEGRADED  MISPLACED  UNFOUND  BYTES     OMAP_BYTES*  OMAP_KEYS*  LOG  STATE         SINCE  VERSION  REPORTED  UP         ACTING     SCRUB_STAMP                      DEEP_SCRUB_STAMP                 LAST_SCRUB_DURATION  SCRUB_SCHEDULING                                            SCRUB_DURATION
1.0         2         0          0        0   8388608            0           0    2  active+clean   116s     17'2     17:23  [1,0,2]p1  [1,0,2]p1  2022-03-10T13:27:31.677610+0530  2022-03-10T13:27:31.677610+0530                    1  periodic scrub scheduled @ 2022-03-11T09:04:49.703708+0000       0.0835267
1.1         4         0          0        0  16777216            0           0    4  active+clean   110s     17'4     17:25  [2,0,1]p2  [2,0,1]p2  2022-03-10T13:27:37.633666+0530  2022-03-10T13:27:37.633666+0530                    1  periodic scrub scheduled @ 2022-03-11T14:03:04.722306+0000        0.268612
1.2         2         0          0        0   8388608            0           0    2  active+clean   114s     17'2     17:23  [0,1,2]p0  [0,1,2]p0  2022-03-10T13:27:34.297845+0530  2022-03-10T13:27:34.297845+0530                    1  periodic scrub scheduled @ 2022-03-11T15:31:53.398183+0000       0.0832727
1.3         6         0          0        0  25165824            0           0    6  active+clean   108s     17'6     17:27  [1,2,0]p1  [1,2,0]p1  2022-03-10T13:27:40.114649+0530  2022-03-10T13:27:40.114649+0530                    1  periodic scrub scheduled @ 2022-03-11T09:45:43.774958+0000        0.369524
1.4         3         0          0        0  12582912            0           0    3  active+clean   102s     17'3     17:24  [1,0,2]p1  [1,0,2]p1  2022-03-10T13:27:45.764404+0530  2022-03-10T13:27:45.764404+0530                    1  periodic scrub scheduled @ 2022-03-11T08:19:19.454109+0000        0.115048
1.5         3         0          0        0  12582912            0           0    3  active+clean     2m     17'3     17:24  [2,0,1]p2  [2,0,1]p2  2022-03-10T13:27:26.635825+0530  2022-03-10T13:27:26.635825+0530                    1  periodic scrub scheduled @ 2022-03-11T13:06:00.165791+0000        0.125908
1.6         1         0          0        0   4194304            0           0    1  active+clean     2m     17'1     17:22  [1,0,2]p1  [1,0,2]p1  2022-03-10T13:26:59.728810+0530  2022-03-10T13:26:59.728810+0530                    1  periodic scrub scheduled @ 2022-03-11T08:22:51.702469+0000        0.047607
1.7         3         0          0        0  12582912            0           0    3  active+clean   103s     17'3     17:24  [1,2,0]p1  [1,2,0]p1  2022-03-10T13:27:44.796895+0530  2022-03-10T13:27:44.796895+0530                    1  periodic scrub scheduled @ 2022-03-11T09:14:22.736813+0000        0.114108
```

**Comment by ljflores** [comment]
jenkins test make check

**Comment by neha-ojha** [comment]
jenkins test api

**Comment by neha-ojha** [comment]
> ```
> [amathuri@localhost build]$ sudo bin/ceph pg ls-by-pool testbench
> PG    OBJECTS  DEGRADED  MISPLACED  UNFOUND  BYTES     OMAP_BYTES*  OMAP_KEYS*  LOG  STATE         SINCE  VERSION  REPORTED  UP         ACTING     SCRUB_STAMP                      DEEP_SCRUB_STAMP                 LAST_SCRUB_DURATION  SCRUB_SCHEDULING                                            SCRUB_DURATION
> 1.0         2         0          0        0   8388608            0           0    2  active+clean   116s     17'2     17:23  [1,0,2]p1  [1,0,2]p1  2022-03-10T13:27:31.677610+0530  2022-03-10T13:27:31.677610+0530                    1  periodic scrub scheduled @ 2022-03-11T09:04:49.703708+0000       0.0835267
> 1.1         4         0          0        0  16777216            0           0    4  active+clean   110s     17'4     17:25  [2,0,1]p2  [2,0,1]p2  2022-03-10T13:27:37.633666+0530  2022-03-10T13:27:37.633666+0530                    1  periodic scrub scheduled @ 2022-03-11T14:03:04.722306+0000        0.268612
> 1.2         2         0          0        0   8388608            0           0    2  active+clean   114s     17'2     17:23  [0,1,2]p0  [0,1,2]p0  2022-03-10T13:27:34.297845+0530  2022-03-10T13:27:34.297845+0530                    1  periodic scrub scheduled @ 2022-03-11T15:31:53.398183+0000       0.0832727
> 1.3         6         0          0        0  25165824            0           0    6  active+clean   108s     17'6     17:27  [1,2,0]p1  [1,2,0]p1  2022-03-10T13:27:40.114649+0530  2022-03-10T13:27:40.114649+0530                    1  periodic scrub scheduled @ 2022-03-11T09:45:43.774958+0000        0.369524
> 1.4         3         0          0        0  12582912            0           0    3  active+clean   102s     17'3     17:24  [1,0,2]p1  [1,0,2]p1  2022-03-10T13:27:45.764404+0530  2022-03-10T13:27:45.764404+0530                    1  periodic scrub scheduled @ 2022-03-11T08:19:19.454109+0000        0.115048
> 1.5         3         0          0        0  12582912            0           0    3  active+clean     2m     17'3     17:24  [2,0,1]p2  [2,0,1]p2  2022-03-10T13:27:26.635825+0530  2022-03-10T13:27:26.635825+0530                    1  periodic scrub scheduled @ 2022-03-11T13:06:00.165791+0000        0.125908
> 1.6         1         0          0        0   4194304            0           0    1  active+clean     2m     17'1     17:22  [1,0,2]p1  [1,0,2]p1  2022-03-10T13:26:59.728810+0530  2022-03-10T13:26:59.728810+0530                    1  periodic scrub scheduled @ 2022-03-11T08:22:51.702469+0000        0.047607
> 1.7         3         0          0        0  12582912            0           0    3  active+clean   103s     17'3     17:24  [1,2,0]p1  [1,2,0]p1  2022-03-10T13:27:44.796895+0530  2022-03-10T13:27:44.796895+0530                    1  periodic scrub scheduled @ 2022-03-11T09:14:22.736813+0000        0.114108
> ```

Having both `LAST_SCRUB_DURATION` and `SCRUB_DURATION` in this output can be confusing. Will just including scrub duration in the json output suffice?

**Comment by amathuria** [comment]
> 
@neha-ojha made the change to have scrub duration only in the json output. I have updated the commit message too.

**Review by sseshasa — APPROVED** [review]
LGTM

**Comment by amathuria** [comment]
jenkins test make check

**Review by neha-ojha — APPROVED** [review]

**Pull request merged**
