### PR TITLE
rgw: make beast the default for rgw_frontends

### PR DESCRIPTION
**Pull request by cbodley**

### CODE REVIEW

**Comment by cbodley** [comment]
we should probably make a similar change to ceph-ansible, though i don't know how to make that only apply for nautilus

https://github.com/ceph/ceph-ansible/blob/master/roles/ceph-defaults/defaults/main.yml#L379
> radosgw_frontend_type: civetweb # For additionnal frontends see: http://docs.ceph.com/docs/mimic/radosgw/frontends/

**Comment by theanalyst** [comment]
Can we also add a small note in the docs saying beast is the recommended frontend.

**Comment by leseb** [comment]
@dsavineau and @guits for the ceph-ansible piece.

**Comment by cbodley** [comment]
jenkins test make check

**Pull request merged**
