### PR TITLE
Buffer: Fix bufferlist::zero bug

### PR DESCRIPTION
**Pull request by yuyuyu101**
Fix #12252

### CODE REVIEW

**Comment by gregsfortytwo** [comment]
So this was previously failing on trying to zero a buffer past its end point?

**Comment by yuyuyu101** [comment]
Exactly!

I spent nearly two days to figure out why my feature implementation broken, it's surprised that the bug from bufferlist::zero :-(

**Comment by yuyuyu101** [comment]
@gregsfortytwo do you think we need to backport this fix?

**Comment by gregsfortytwo** [comment]
Heh, I asked you that on the ticket. I don't know where we use the zero
stuff but it's a bug in a bit of central infrastructure; I think we should.

**Pull request merged**
