### PR TITLE
backfill_toofull seen on cluster where the most full OSD is at 1%

### PR DESCRIPTION
**Pull request by dzafman**
## Checklist
- [x] References tracker ticket
- [x] ~Updates documentation if necessary~
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`

</details>

### CODE REVIEW

**Comment by dzafman** [comment]
jenkins test Signed-off-by

**Comment by dzafman** [comment]
jenkins retest this please

**Comment by tchaikov** [comment]
retest this please.

**Comment by tchaikov** [comment]
- http://pulpito.ceph.com/kchai-2019-08-27_15:50:13-rados-wip-kefu-testing-2019-08-27-1807-distro-basic-mira/
- http://pulpito.ceph.com/kchai-2019-08-29_03:14:53-rados-wip-kefu-testing-2019-08-27-1807-distro-basic-mira/

**Comment by smithfarm** [comment]
@dzafman In https://tracker.ceph.com/issues/41255 the reporter said he did not see the bug on his Luminous (12.2.12) clusters. Can you double-check whether the backport to L is really needed?

**Pull request merged**
