### PR TITLE
qa: update fs:upgrade to test from n-1/n-2 to main

### PR DESCRIPTION
**Pull request by dparmar18**
## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Comment by dparmar18** [comment]
looks like teuth machines dont have lua or lua modules im making use of 
```
lupa.lua54.LuaError: [string "teuthology"]:1: attempt to call a nil value (global 'require')
```

**Comment by dparmar18** [comment]
or i suspect it isn't allowed, i see this [commit](https://github.com/ceph/teuthology/pull/1776/commits/96f38f2136dd2a4f64cc741919b85dc65a9df536#diff-4cbbf0fe96ac472d6667530e401138571a2713b823879c84d9f031607c91fd31R1-R19) where there is an allowist consisting of only few lua builtins

**Comment by dparmar18** [comment]
> or i suspect it isn't allowed, i see this [commit](https://github.com/ceph/teuthology/pull/1776/commits/96f38f2136dd2a4f64cc741919b85dc65a9df536#diff-4cbbf0fe96ac472d6667530e401138571a2713b823879c84d9f031607c91fd31R1-R19) where there is an allowist consisting of only few lua builtins

yeah this is it, it is missing `require` function in the allowlist. Without its inclusion in the allowlist, this patch cannot move ahead

**Comment by vshankar** [comment]
@dparmar18 What't the status of this? IMO, we should just hand edit the yaml for now and get that merged to start testing upgrades.

**Comment by dparmar18** [comment]
> @dparmar18 What't the status of this? IMO, we should just hand edit the yaml for now and get that merged to start testing upgrades.

ive texted on slack for help, im trying to solve issues currently.

**Comment by dparmar18** [comment]
```
lupa.lua54.LuaError: error loading module 'socket.core' from file './socket/core.so':
	dynamic libraries not enabled; check your Lua installation
```

**Comment by leonid-s-usov** [comment]
It's a lot of fun playing with the lua scripting and inventing new ways of injecting dynamic values.
However, taking a step back and looking at the task at hand, I have the following question: was it considered to encode an n-1 and n-2 branches with dedicated branch name syntax and then resolve them already as part of the upgrade python task itself? It could be as simple as

- install.upgrade:
    # upgrade the single cluster node, which is running all the mon/mds/osd/mgr daemons
    mon.a:
      branch: "@+1"
where @ would mean the tested branch and ±n would go up/down the release lineup. This would need to be supported as a syntax to install branch as well

**Comment by leonid-s-usov** [comment]
It's a lot of fun playing with the lua scripting and inventing new ways of injecting dynamic values.
However, taking a step back and looking at the task at hand, I have the following question: was it considered to encode an `n-1` and `n-2` branches with dedicated branch name syntax and then resolve them already as part of the `upgrade` python task itself? It could be as simple as

```
- install.upgrade:
    # upgrade the single cluster node, which is running all the mon/mds/osd/mgr daemons
    mon.a:
      branch: "@+1"
```

where `@` would mean the tested branch and `±n` would go up/down the release lineup. This would need to be supported as a syntax to `install` branch as well

**Comment by dparmar18** [comment]
> It's a lot of fun playing with the lua scripting and inventing new ways of injecting dynamic values. However, taking a step back and looking at the task at hand, I have the following question: was it considered to encode an `n-1` and `n-2` branches with dedicated branch name syntax and then resolve them already as part of the `install` and `install.upgrade` python task itself? It could be as simple as
> 
> ```
> - install.upgrade:
>     # upgrade the single cluster node, which is running all the mon/mds/osd/mgr daemons
>     mon.a:
>       branch: "@+1"
> ```
> 
> where `@` would mean the tested branch and `±n` would go up/down the release lineup. This would need to be supported as a syntax to `install` branch as well
> 
> UPD: maybe we could even avoid using `@` and just use `±n` to denote the relation to the current build, where the current build is the one installed, or if it's the install command, then the build of the test branch

So let me try to summarise this and I hope I understand it well - You're saying is we enable `install` and `install.upgrade` through teuthology code by using `@` or `±n` which would trigger some logic that fetches the latest ceph version and installs/upgrade automatically?

**Comment by leonid-s-usov** [comment]
> So let me try to summarise this and I hope I understand it well - You're saying is we enable `install` and `install.upgrade` through teuthology code by using `@` or `±n` which would trigger some logic that fetches the latest ceph version and installs/upgrade automatically?

That is correct!
I think it would be best to implement it on the teuthology side, but if for any reason we would not like that, there's also an option of creating our local cephfs wrapper task for both install and upgrade, that will only deal with the special branch names but after injecting the correct parameters will simply call the standard implementation by importing it from teuthology

**Comment by vshankar** [comment]
@dparmar18 - are you still planning to work on this? IIRC, we had stumbled upon couple of not-so-straightforward roadblocks related to automatic upgrades.

**Comment by dparmar18** [comment]
> @dparmar18 - are you still planning to work on this? IIRC, we had stumbled upon couple of not-so-straightforward roadblocks related to automatic upgrades.

right, this one should be closed since we all agreed that the automation requires significant efforts for something like this that requires minor changes once or twice a year

**Pull request closed without merging**
