### PR TITLE
rgw:remove an unnecessary assignment of the variable 'marker'

### PR DESCRIPTION
**Pull request by weiqiaomiao**
Signed-off-by: weiqiaomiao <wei.qiaomiao@zte.com.cn>

### CODE REVIEW

**Comment by xiexingguo** [comment]
LGTM

**Comment by mattbenjamin** [comment]
@yehudasa, @oritwas I don't see a problem with this, but it has no effect;  defer to K*?

**Comment by weiqiaomiao** [comment]
@mattbenjamin , 'marker"  will assignement at  line 1380, so  it is unnecessary do it here.
       map<string, RGWBucketEnt>::reverse_iterator riter = m.rbegin();
       marker = riter->first;

**Comment by oritwas** [comment]
lgdm

**Pull request merged**
