### PR TITLE
luminous: cephfs-journal-tool: get and check layout info during dump/undump

### PR DESCRIPTION
**Pull request by pdvian**
http://tracker.ceph.com/issues/24934

### CODE REVIEW

**Comment by yuriw** [comment]
[wip-yuri5-testing-2018-08-01-2158-luminous](https://trello.com/c/sUiX40Jw/362-wip-yuri5-testing-2018-08-01-2158-luminous)

**Comment by yuriw** [comment]
@smithfarm @batrick I suspect this broke the build

https://jenkins.ceph.com/job/ceph-dev-new-build/ARCH=x86_64,AVAILABLE_ARCH=x86_64,AVAILABLE_DIST=centos7,DIST=centos7,MACHINE_SIZE=huge/13481//consoleFull

build/ARCH/x86_64/AVAILABLE_ARCH/x86_64/AVAILABLE_DIST/centos7/DIST/centos7/MACHINE_SIZE/huge/release/12.2.7-176-g619f2c3/rpm/el7/BUILD/ceph-12.2.7-176-g619f2c3/src/tools/cephfs/Dumper.cc: In member function 'int Dumper::dump(const char*)':
/home/jenkins-build/build/workspace/ceph-dev-new-build/ARCH/x86_64/AVAILABLE_ARCH/x86_64/AVAILABLE_DIST/centos7/DIST/centos7/MACHINE_SIZE/huge/release/12.2.7-176-g619f2c3/rpm/el7/BUILD/ceph-12.2.7-176-g619f2c3/src/tools/cephfs/Dumper.cc:118:6: error: 'fsid_str' was not declared in this scope
      fsid_str,
      ^

**Comment by batrick** [comment]
@pdvian there's a dependency on https://github.com/ceph/ceph/pull/22111 for this backport

**Comment by yuriw** [comment]
[wip-yuri5-testing-2018-08-03-2114-luminous](https://trello.com/c/O6q0j5Gf/366-wip-yuri5-testing-2018-08-03-2114-luminous)

**Comment by yuriw** [comment]
still seems breaking the build

https://jenkins.ceph.com/job/ceph-dev-new-build/ARCH=x86_64,AVAILABLE_ARCH=x86_64,AVAILABLE_DIST=centos7,DIST=centos7,MACHINE_SIZE=huge/13557//consoleFull

https://shaman.ceph.com/builds/ceph/wip-yuri5-testing-2018-08-03-2114-luminous/

Pls add `needs-qa` when fixed.

**Comment by smithfarm** [comment]
Closing in favor of https://github.com/ceph/ceph/pull/24033

**Pull request closed without merging**
