### PR TITLE
pacific: pybind/mgr/mirroring: directory snapshot mirror support

### PR DESCRIPTION
**Pull request by vshankar**
## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by vshankar** [comment]
jenkins test make check

**Comment by vshankar** [comment]
jenkins test make check

**Comment by vshankar** [comment]
@fullerdj suggested that I test this PR in teuthology and merge after getting an ACK. I'll be doing this today (w/ rebase).

@mchangir please take a look at the changes and ack if ok.

**Review by mchangir — APPROVED** [review]
looks good to me

**Comment by vshankar** [comment]
rebased and updated.

fs suite run with mirroring,snap_schedule,volumes filter: https://pulpito.ceph.com/vshankar-2021-02-02_05:28:00-fs-wip-mgr-mirroring-pacific-20210201-225248-distro-basic-smithi/

Failures are in volumes related tests and do not seem to be related to this PR. @kotreshhr Appreciate if you could take a look at those.

**Comment by kotreshhr** [comment]
> rebased and updated.
> 
> fs suite run with mirroring,snap_schedule,volumes filter: https://pulpito.ceph.com/vshankar-2021-02-02_05:28:00-fs-wip-mgr-mirroring-pacific-20210201-225248-distro-basic-smithi/
> 
> Failures are in volumes related tests and do not seem to be related to this PR. @kotreshhr Appreciate if you could take a look at those.

1. test_idempotency: This is known failure and fix [1] is pushed.
2. test_async_subvolume_rm: This looks to me system issue. Lot of errors like Pipetimeout, ssh connection lost, socket timeout tracebacks are seen.
3. test_subvolume_subvolumegroup_snapshot_name_conflict: This also looks to me system issue. 'No route to host', ssh connection lost traceback are seen.

[1] https://github.com/ceph/ceph/pull/39038

**Comment by vshankar** [comment]
Thanks @kotreshhr 

Rerun: https://pulpito.ceph.com/vshankar-2021-02-03_04:18:05-fs-wip-mgr-mirroring-pacific-20210201-225248-distro-basic-smithi/

**Comment by vshankar** [comment]
test run: https://pulpito.ceph.com/vshankar-2021-02-04_09:16:45-fs-wip-mgr-mirroring-pacific-20210203-234930-distro-basic-gibba/

Known failures in test_volume_client.

@mchangir -- Included the doc commit. Please take a look.

**Review by mchangir — APPROVED** [review]
looks good to me

**Pull request merged**
