### PR TITLE
osd: select more suitable shard as auth shard

### PR DESCRIPTION
**Pull request by XinzeChi**
If there are A,B,C shards for some object. The oi.size == ondisk size
for A and B. The oi.size != ondisk_size for C. The origin algorithm
would select C as auth shard. The PR would select A.

Signed-off-by: Xinze Chi <xinze@xsky.com>
@

### CODE REVIEW

**Comment by liewegas** [comment]
Can you decribe in the commit message what the change is and why it is better?

**Comment by XinzeChi** [comment]
@liewegas , Do you think it make sense?

**Comment by liewegas** [comment]
Ah, yeah, that makes sense to me!

@athanatos ?

**Comment by tchaikov** [comment]
> If there are A,B,C shards for some object. The oi.size == ondisk size for A and B. The oi.size != ondisk_size for C. The origin algorithm would select C as auth shard. The PR would select A.

the reason why it selects C is that neither A or B is able to pass all the tests, and C does not have serious problem like read error or OI attr corruption. for example, A's data digest does not match, and B's omap digest fails to match. and we returns with C, simply because "something is better than nothing".

in your example, it selects A instead of C, not because A is better than C, just it has the preference for choosing the first shard (when the first candidate fails the test).

so i don't think this PR is superior than existing algorithm. but i agree, neither of them is perfect.

**Comment by XinzeChi** [comment]
The PR would has the preference for the shard which has no read error, not missing oi attr, data digest match and omap digest match.

**Comment by tchaikov** [comment]
if we has such a candidate, both algorithm return it.

**Comment by liewegas** [comment]
I think @tchaikov  is right--I missed the break statement. We'll stop looking once we find a candidate that passes all the checks.

**Comment by XinzeChi** [comment]
oh, I miss it too. close it.

**Pull request closed without merging**
