### PR TITLE
[DNM] jewel: build/ops: Default kernel.pid_max is easily exceeded during recovery on high OSD-count system 

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/22195

### CODE REVIEW

**Comment by smithfarm** [comment]
@ddiss Could you review this (conflict resolution, completeness, etc.)?

**Comment by ddiss** [comment]
@smithfarm backport looks fine, but I think we should also pull in 89a48189ea7b9bd58db1bc95ccd7b3d9fb9b1bb3 .

**Comment by smithfarm** [comment]
@ddiss Very good point. Done here and in #19133 as well.

**Comment by smithfarm** [comment]
retest this please

**Comment by smithfarm** [comment]
retest this please

**Comment by smithfarm** [comment]
FACEPALM - I lulled myself into believing that jewel uses cmake

The cmake parts of this PR will need to be adapted to autotools.

**Comment by ddiss** [comment]
> The cmake parts of this PR will need to be adapted to autotools.

I'll take a look at this today.

**Pull request closed without merging**
