### PR TITLE
jewel: ceph-create-keys loops forever

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/17754

### CODE REVIEW

**Comment by dachary** [comment]
It passed the rados (http://tracker.ceph.com/issues/17851#note-4) suite. It also passed the upgrade/jewel-x and upgrade/hammer-x (http://tracker.ceph.com/issues/17851#note-7) suites, except for one job which should be fixed by https://github.com/ceph/ceph-qa-suite/pull/1256 and does not seem related to this pull request. Note that it won't be included in 10.2.4, reason why it targets jewel-next.

**Comment by dachary** [comment]
@smithfarm could you please repush without  	2538ed4 ? It has already been merged in jewel.

**Comment by smithfarm** [comment]
@dachary Looks like "git rebase ceph/jewel-next" was enough to get rid of it :-)

**Comment by dachary** [comment]
<pre>
flake8 runtests: PYTHONHASHSEED='3298675756'
flake8 runtests: commands[0] | flake8 --ignore=H105,H405,E127 ceph_disk tests
ceph_disk/main.py:173:1: E305 expected 2 blank lines after class or function definition, found 1
ceph_disk/main.py:5011:1: E305 expected 2 blank lines after class or function definition, found 1
ERROR: InvocationError: '/home/jenkins-build/build/workspace/ceph-pull-requests/src/ceph-disk/.tox/flake8/bin/flake8 --ignore=H105,H405,E127 ceph_disk tests'
</pre>

**Comment by smithfarm** [comment]
@dachary That's odd; this PR doesn't touch ceph-disk as far as I can see?

**Comment by dachary** [comment]
@smithfarm right, this is odd... I must have merged something that triggers that problem

**Comment by dachary** [comment]
@smithfarm you should remove 8692d1b : the problem is not the extra lines, it is that flake8 should not complain about them. Unless ... it started doing so by default !

**Comment by smithfarm** [comment]
@dachary Removed.

**Comment by dachary** [comment]
jenkins test this please (flake8 error now fixed in jewel-next)

**Comment by dachary** [comment]
It passed the rados (http://tracker.ceph.com/issues/17851#note-12) suite. It also passed the upgrade/jewel-x and upgrade/hammer-x (http://tracker.ceph.com/issues/17851#note-15) suites.

**Pull request merged**
