### PR TITLE
[DNM] mimic: cmake: fix build WITH_SYSTEM_BOOST=ON

### PR DESCRIPTION
**Pull request by wjwithagen**
http://tracker.ceph.com/issues/38225

### CODE REVIEW

**Comment by smithfarm** [comment]
@wjwithagen This does not build. cmake fails with:

```
CMake Error at cmake/modules/BuildBoost.cmake:284 (_add_executable):
  Target "ceph-mgr" links to target "Boost::python2" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?
Call Stack (most recent call first):
  src/CMakeLists.txt:770 (add_executable)


CMake Error at cmake/modules/BuildBoost.cmake:284 (_add_executable):
  Target "ceph-mgr" links to target "Boost::python2" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?
Call Stack (most recent call first):
  src/CMakeLists.txt:770 (add_executable)
```

**Comment by wjwithagen** [comment]
@smithfarm 
I noticed. And it is due to the fact that `python_version_minor` does not exists...
Fixing that requires importing the addition of that to `CMakeLists.txt`, but then it is getting close to backporting the whole of #23510 
Perhaps @tchaikov can suggest if this is workable....

**Comment by tchaikov** [comment]
> And it is due to the fact that `python_version_minor` does not exists...
> 
> Fixing that requires importing the addition of that to `CMakeLists.txt`, but then it is getting close to backporting the whole of #23510 

why not?

**Comment by smithfarm** [comment]
I gave it a try. The only (presumably minor) issue is that there is no `src/mgr/CMakeLists.txt` in mimic, so the modification of that file would have to be done manually.

**Comment by wjwithagen** [comment]
Closing this.
Might look at backporting #23510 but for now I'll take this to the patching set included in the FreeBSD ports.

**Pull request closed without merging**
