### PR TITLE
luminous: Possible deadlock in 'list_children' when refresh is required

### PR DESCRIPTION
**Pull request by kmroz**
http://tracker.ceph.com/issues/21688

### CODE REVIEW

**Comment by theanalyst** [comment]
Passed teuthology run http://tracker.ceph.com/issues/21830#note-17

**Comment by theanalyst** [comment]
jenkins test this please

**Comment by theanalyst** [comment]
jenkins test this please

**Comment by smithfarm** [comment]
jenkins re-test this please

**Comment by yuriw** [comment]
[wip-yuri4-testing-2018-01-22-2213-luminous](https://trello.com/c/ZyHjeq8C/240-wip-yuri4-testing-2018-01-22-2213-luminous)

**Pull request merged**
