### PR TITLE
Wip mds snap

### PR DESCRIPTION
**Pull request by ukernel**
tested by running snaptest scripts locally on both fuse and kernel client

### CODE REVIEW

**Comment by ukernel** [comment]
http://pulpito.ceph.com/zyan-2016-03-02_06:21:11-fs-wip-zyan-testing-testing-basic-mira/

**Comment by liewegas** [comment]
:+1:

**Comment by gregsfortytwo** [comment]
Why would a dentry's "first" differ from its inode, if it's a primary link?

**Comment by ukernel** [comment]
see CInode::cow_old_inode and MDCache::cow_inode

**Comment by gregsfortytwo** [comment]
http://pulpito.ceph.com/gregf-2016-03-09_00:11:22-fs-greg-fs-testing-38-1---basic-mira/, 2 failures in new (unrelated) tests and one failure from http://tracker.ceph.com/issues/14962.

**Pull request merged**
