### PR TITLE
octopus: mon: Log "ceph health detail" periodically in cluster log

### PR DESCRIPTION
**Pull request by smithfarm**
backport tracker: https://tracker.ceph.com/issues/48228

---

backport of https://github.com/ceph/ceph/pull/37902
parent tracker: https://tracker.ceph.com/issues/48042

this backport was staged using ceph-backport.sh version 15.1.1.389
find the latest version at https://github.com/ceph/ceph/blob/master/src/script/ceph-backport.sh

### CODE REVIEW

**Comment by smithfarm** [comment]
jenkins test make check

**Comment by smithfarm** [comment]
```
E: dpkg was interrupted, you must manually run 'sudo dpkg --configure -a' to correct the problem. 
```

**Review by neha-ojha — APPROVED** [review]

**Comment by smithfarm** [comment]
jenkins test make check

**Comment by yuriw** [comment]
[wip-yuri7-testing-2020-12-11-1139-octopus](https://trello.com/c/FcAMvcql/1083-wip-yuri7-testing-2020-12-11-1139-octopus)

**Pull request merged**
