### PR TITLE
mimic: qa/suites/rgw/verify/tasks/cls_rgw: test cls_rgw

### PR DESCRIPTION
**Pull request by pdvian**
http://tracker.ceph.com/issues/25024

### CODE REVIEW

**Comment by yuriw** [comment]
[wip-yuri4-testing-2018-08-20-2118-mimic](https://trello.com/c/EK2RH5M2/379-wip-yuri4-testing-2018-08-20-2118-mimic)

**Comment by cbodley** [comment]
it looks like this one is causing a lot of test failures, because it depends on changes in https://github.com/ceph/ceph/pull/22249 that weren't backported to mimic. could you please pull in the commit from that pr?

**Comment by yuriw** [comment]
pls tags when fixed

**Comment by smithfarm** [comment]
@pdvian ping, could you please respond to https://github.com/ceph/ceph/pull/23197#issuecomment-415104531

**Comment by pdvian** [comment]
@cbodley @smithfarm Let me pull #22249 changes.

**Comment by smithfarm** [comment]
@pdvian The changes from #22249 depend on an earlier commit. See https://github.com/ceph/ceph/pull/24070 (it hasn't been tested yet, but it looks sane).

**Comment by pdvian** [comment]
@smithfarm Agree. @cbodley have pulled #22249 changes. Kindly review.

**Comment by smithfarm** [comment]
@pdvian Could you please model this PR after https://github.com/ceph/ceph/pull/24070 - i.e. three cherry-picked commits from master, and change `ceph-master` branch to `ceph-mimic`.

**Comment by pdvian** [comment]
@smithfarm sure. Let me do it.

**Comment by smithfarm** [comment]
This looks good to me now. @cbodley Do you agree?

**Comment by cbodley** [comment]
@smithfarm yep :+1:

**Comment by yuriw** [comment]
[wip-yuri-testing-2018-10-15-2110-mimic](https://trello.com/c/VnZerOBe/442-wip-yuri-testing-2018-10-15-2110-mimic)

**Pull request merged**
