### PR TITLE
luminous: RGWCrashError: RGW will crash if a putting lc config request does not include an ID tag in the request xml

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/22016
http://tracker.ceph.com/issues/22024

### CODE REVIEW

**Comment by theanalyst** [comment]
The crash itself will not manifest in Luminous yet, as far as the random changes also are not backported to Luminous, but shouldn't hurt backporting this patch if we have a clean rgw run

**Comment by smithfarm** [comment]
@theanalyst I cherry-picked https://github.com/ceph/ceph/pull/18536 into this PR - is that what you're referring to?

**Comment by smithfarm** [comment]
@theanalyst Nevermind, now I see it's https://github.com/ceph/ceph/pull/17972

**Comment by theanalyst** [comment]
@smithfarm yeah, having said that this patch by itself isn't harmful, only that the crash itself wouldn't occur until the random changes, if we see clean rgw runs shouldn't hurt to have this in.

**Comment by ZVampirEM77** [comment]
@smithfarm @theanalyst Thank you~

**Comment by ZVampirEM77** [comment]
Jenkins, retest this please.

**Comment by yuriw** [comment]
[luminous rgw => wip-yuri2-testing-2018-01-18-2229](https://trello.com/c/ssqTxeTy/235-luminous-rgw-wip-yuri2-testing-2018-01-18-2229)

**Comment by yuriw** [comment]
@smithfarm @theanalyst @cbodley ready for merge

**Pull request merged**
