### PR TITLE
hammer: test/librados/tier.cc doesn't completely clean up EC pools

### PR DESCRIPTION
**Pull request by xiaoxichen**
http://tracker.ceph.com/issues/15051

### CODE REVIEW

**Comment by smithfarm** [comment]
@dachary Please review.

**Comment by smithfarm** [comment]
@xiaoxichen The commit is missing the "(cherry-picked from . . .)" line.

**Comment by xiaoxichen** [comment]
@smithfarm sorry , my bad , forgot -x option:) will do it

**Comment by smithfarm** [comment]
@dachary Prepared and pushed an integration branch `hammer-pr-8052` specially for this one PR. Could you run the analogous test to the one you are running in #7987?

**Comment by smithfarm** [comment]
Hm. I tried to trigger that test for hammer, but it doesn't seem to exist in hammer ceph-qa-suite:

```
smithfarm@teuthology:~/teuthology$ filter="rados/thrash/{hobj-sort.yaml 0-size-min-size-overrides/3-size-2-min-size.yaml 1-pg-log-overrides/normal_pg_log.yaml clusters/{fixed-2.yaml openstack.yaml} fs/ext4.yaml msgr/simple.yaml msgr-failures/osd-delay.yaml thrashers/default.yaml workloads/rados_api_tests.yaml}"
smithfarm@teuthology:~/teuthology$ ./virtualenv/bin/teuthology-suite --priority 999 --suite rados --filter="$filter" --suite-branch hammer --email ncutler@suse.cz --ceph hammer-pr-8052 --machine-type smithi,mira
2016-03-18 22:51:56,814.814 INFO:teuthology.suite:ceph sha1: 57fd7f858c220af362b330d12db0e87de82b4346
2016-03-18 22:51:56,844.844 INFO:teuthology.suite:ceph version: v0.94.6-198.g57fd7f8
2016-03-18 22:51:56,844.844 INFO:teuthology.suite:teuthology branch: master
2016-03-18 22:51:57,846.846 INFO:teuthology.suite:ceph-qa-suite branch: hammer b2b543e5cdbaa248de99ab14fb84d631cd955b34
2016-03-18 22:51:58,053.053 INFO:teuthology.repo_utils:Fetching from upstream into /home/smithfarm/src/ceph-qa-suite_hammer
2016-03-18 22:51:59,991.991 INFO:teuthology.repo_utils:Resetting repo at /home/smithfarm/src/ceph-qa-suite_hammer to branch hammer
2016-03-18 22:52:01,598.598 INFO:teuthology.suite:Suite rados in /home/smithfarm/src/ceph-qa-suite_hammer/suites/rados generated 3233 jobs (not yet filtered)
2016-03-18 22:52:01,611.611 INFO:teuthology.suite:Suite rados in /home/smithfarm/src/ceph-qa-suite_hammer/suites/rados scheduled 0 jobs.
2016-03-18 22:52:01,611.611 INFO:teuthology.suite:Suite rados in /home/smithfarm/src/ceph-qa-suite_hammer/suites/rados -- 3233 jobs were filtered out.
```

**Comment by smithfarm** [comment]
@yuriw: I staged this hammer backport for the fix as you requested, but the test that verifies the fix does not seem to exist in hammer ceph-qa-suite. See comments above.

**Comment by yuriw** [comment]
@smithfarm the failure was triggered by upgrading from infernalis=>jewel (see for example this dupe http://tracker.ceph.com/issues/14927), so the test in in jewel.  

Note: same for similar backport   http://tracker.ceph.com/issues/15051, triggered by upgrading from hammer=>jewel, the test is in jewel as well.

Thanks!

**Comment by smithfarm** [comment]
**running** http://pulpito.ceph.com/smithfarm-2016-03-19_09:18:11-upgrade:hammer-x-hammer-pr-8052---basic-multi/

```
./virtualenv/bin/teuthology-suite --priority 999 --suite upgrade/hammer-x --suite-branch jewel --email ncutler@suse.cz --ceph hammer-pr-8052 --filter 'upgrade:hammer-x/parallel/{0-tz-eastern.yaml 4-infernalis.yaml 0-cluster/start.yaml 1-hammer-install/hammer.yaml 2-workload/{ec-rados-default.yaml rados_api.yaml rados_loadgenbig.yaml test_rbd_api.yaml test_rbd_python.yaml} 3-upgrade-sequence/upgrade-all.yaml 5-final-workload/{rados-snaps-few-objects.yaml rados_loadgenmix.yaml rados_mon_thrash.yaml rbd_cls.yaml rbd_import_export.yaml rgw_swift.yaml} distros/ubuntu_14.04.yaml}'
```

**Comment by smithfarm** [comment]
**runnin** http://149.202.190.143:8081/ubuntu-2016-03-19_16:24:35-upgrade:hammer-x-hammer-pr-8052---basic-openstack/

```
cw ceph-qa-suite --verbose --simultaneous-jobs 10 --suite upgrade/hammer-x --suite-branch jewel --ceph hammer-pr-8052 --filter 'upgrade:hammer-x/parallel/{0-tz-eastern.yaml 4-infernalis.yaml 0-cluster/start.yaml 1-hammer-install/hammer.yaml 2-workload/{ec-rados-default.yaml rados_api.yaml rados_loadgenbig.yaml test_rbd_api.yaml test_rbd_python.yaml} 3-upgrade-sequence/upgrade-all.yaml 5-final-workload/{rados-snaps-few-objects.yaml rados_loadgenmix.yaml rados_mon_thrash.yaml rbd_cls.yaml rbd_import_export.yaml rgw_swift.yaml} distros/ubuntu_14.04.yaml}'
```

**Comment by smithfarm** [comment]
Pushed a `jewel-pr-8052` branch to `ceph/ceph-qa-suite.git` - in this branch I have edited `suites/upgrade/hammer-x/parallel/1-hammer-install/hammer.yaml` like so:

```
- branch: hammer
+ branch: hammer-pr-8052
```
Next I will schedule a run of the failing job from `update/hammer-x` based on this modified jewel suitebranch.

**Comment by smithfarm** [comment]
**running** http://pulpito.ceph.com/smithfarm-2016-03-19_10:16:39-upgrade:hammer-x-jewel---basic-multi/

```
./virtualenv/bin/teuthology-suite --priority 999 --suite upgrade/hammer-x --suite-branch jewel-pr-8052 --machine-type mira,smithi --email ncutler@suse.cz --ceph jewel --filter 'upgrade:hammer-x/parallel/{0-tz-eastern.yaml 4-infernalis.yaml 0-cluster/start.yaml 1-hammer-install/hammer.yaml 2-workload/{ec-rados-default.yaml rados_api.yaml rados_loadgenbig.yaml test_rbd_api.yaml test_rbd_python.yaml} 3-upgrade-sequence/upgrade-all.yaml 5-final-workload/{rados-snaps-few-objects.yaml rados_loadgenmix.yaml rados_mon_thrash.yaml rbd_cls.yaml rbd_import_export.yaml rgw_swift.yaml} distros/ubuntu_14.04.yaml}'
```

**Comment by smithfarm** [comment]
@yuriw: the suggested reproducer http://pulpito.ceph.com/teuthology-2016-03-17_14:34:14-upgrade:hammer-x-jewel-distro-basic-smithi/69819/ fails with:

```
2016-03-17T14:55:30.579 INFO:tasks.workunit.client.0.smithi053.stdout:[       OK ] ClsHello.WriteReturnData (4141 ms)
2016-03-17T14:55:30.580 INFO:tasks.workunit.client.0.smithi053.stdout:[ RUN      ] ClsHello.Loud
2016-03-17T14:55:30.580 INFO:tasks.workunit.client.0.smithi053.stdout:test/cls_hello/test_cls_hello.cc:103: Failure
2016-03-17T14:55:30.580 INFO:tasks.workunit.client.0.smithi053.stdout:Value of: create_one_pool_pp(pool_name, cluster)
2016-03-17T14:55:30.580 INFO:tasks.workunit.client.0.smithi053.stdout:  Actual: "cluster.pool_create(test-rados-api-smithi053-5139-4) failed with error -22"
2016-03-17T14:55:30.580 INFO:tasks.workunit.client.0.smithi053.stdout:Expected: ""
2016-03-17T14:55:30.580 INFO:tasks.workunit.client.0.smithi053.stdout:[  FAILED  ] ClsHello.Loud (1503 ms)
2016-03-17T14:55:30.581 INFO:tasks.workunit.client.0.smithi053.stdout:[ RUN      ] ClsHello.BadMethods
```

and this PR when applied as described in https://github.com/ceph/ceph/pull/8052#issuecomment-198750979 does not help. It fails in the exact same way.

**Comment by yuriw** [comment]
@smithfarm the hope was that this backport would fix this problem, so if confirmed it may set us back to square one :/

**Comment by jdurgin** [comment]
Investigated a bit, seems that there are indeed no extra ec profiles hanging around, but this time at least the failure was not from the 5 second timeout for crushtool testing - the pool create op that failed did so in under 1 second.

I looked at the crushmaps and osdmaps and saw nothing else out of the ordinary.
@smithfarm @tchaikov I think the next step is to add more logging on top of this patch to figure out exactly where the EINVAL is originating. Could one of you look into this?

**Comment by tchaikov** [comment]
i just pushed a branch with more logging messages (baabce385f41684834f3ba2f9fb2d4019a0c3502) to https://github.com/ceph/ceph/tree/wip-15051-hammer, will test it along with this reproducer.

**Comment by tchaikov** [comment]
https://github.com/ceph/ceph-qa-suite/commit/fcde1f6b9f1357e799fe65ce9baaf4b4bb517fbf#diff-ac3024427664a6a26320bd4d92ac18ffL9 fixes the issue but i failed to test it using the jewel branch. and #8295 is supposed to fix this problem.

**Comment by tchaikov** [comment]
@smithfarm your test is not a valid case, as per sage

> The user is required to upgrade to 0.94.4 before moving on to infernalis or jewel. Does that mean they avoid this problem?

see https://github.com/ceph/ceph/pull/8295#issuecomment-201293228.

**Comment by tchaikov** [comment]
as http://tracker.ceph.com/issues/14927 is resolved, i think we can move on.

**Comment by smithfarm** [comment]
@tchaikov I don't understand. My test case did not involve upgrading a pre-0.94.4 hammer to jewel, or did it?

**Comment by dachary** [comment]
@tchaikov while http://tracker.ceph.com/issues/14927 is resolved by https://github.com/ceph/ceph-qa-suite/commit/fcde1f6b9f1357e799fe65ce9baaf4b4bb517fbf, the underlying issue deserves backporting, IMHO. But maybe there is a reason why it is not worth it ?

**Comment by tchaikov** [comment]
@smithfarm my bad, i was looking at a different run.

**Comment by dachary** [comment]
It passed the hammer upgrade suite ( http://tracker.ceph.com/issues/14692#note-52 ) and the rados suite http://tracker.ceph.com/issues/14692#note-51).

**Pull request merged**
