### PR TITLE
mgr/progress: 0 affected PG doesn't break test case

### PR DESCRIPTION
**Pull request by kamoltat**
Currently in qa/tasks/mgr/test_progress.py
we don't have a case where PG recovery event
doesn't get triggered when osd is marked in/out
due to the osd not being in any of the PGs acting
sets in both old osd map and new osd map.

Fixes: https://tracker.ceph.com/issues/53984

Signed-off-by: Kamoltat <ksirivad@redhat.com>

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [x] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [x] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [x] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [x] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by kamoltat** [comment]
Run passed 8/8 

4 runs of:
https://pulpito.ceph.com/ksirivad-2022-01-24_19:09:07-rados:mgr-wip-kisirvad-mgr-progress-improve-test-distro-basic-smithi/
+
4 runs of:
https://pulpito.ceph.com/ksirivad-2022-01-24_19:09:07-rados:mgr-wip-kisirvad-mgr-progress-improve-test-distro-basic-smithi/

**Comment by kamoltat** [comment]
jenkins test make check

**Review by neha-ojha — COMMENTED** [review]
@kamoltat could you please make the test changes in a separate commit?

**Comment by kamoltat** [comment]
> @kamoltat could you please make the test changes in a separate commit?

done

**Comment by kamoltat** [comment]
@neha-ojha think this one should be fine to merge

**Comment by kamoltat** [comment]
@neha-ojha  running https://pulpito.ceph.com/ksirivad-2022-07-08_20:23:04-rados:mgr-main-distro-default-smithi/ just to check if the problem still exists

**Comment by kamoltat** [comment]
28/30 Jobs Passed
2/30 Dead due to https://tracker.ceph.com/issues/56391

Seems like the problem went away for now, closing this PR and marking Tracker as "Can't reproduce"

**Pull request closed without merging**
