### PR TITLE
rgw/restore: Fixed status codes and response headers

### PR DESCRIPTION
**Pull request by shreyanshjain7174**
Added x-amz-restore header and fixed status codes for both restore-cli and read_through.

Fixes: https://tracker.ceph.com/issues/68013

Signed-off-by: shreyanshjain7174 <ssanchet@redhat.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Comment by shreyanshjain7174** [comment]
`jenkins test make check`
`jenkins test api`

**Comment by shreyanshjain7174** [comment]
jenkins test api

**Comment by shreyanshjain7174** [comment]
jenkins test make check

**Comment by shreyanshjain7174** [comment]
jenkins test api

**Comment by shreyanshjain7174** [comment]
jenkins test api

**Comment by shreyanshjain7174** [comment]
jenkins test api

**Review by soumyakoduri — APPROVED** [review]
Looks good to me (as reviewed on https://github.com/soumyakoduri/ceph/pull/15 )

**Comment by shreyanshjain7174** [comment]
jenkins test api

**Comment by shreyanshjain7174** [comment]
jenkins test make check arm64

**Comment by shreyanshjain7174** [comment]
jenkins test windows

**Comment by shreyanshjain7174** [comment]
jenkins test api

**Comment by shreyanshjain7174** [comment]
jenkins test make check arm64

**Comment by shreyanshjain7174** [comment]
jenkins test api

**Comment by soumyakoduri** [comment]
@cbodley @mattbenjamin @adamemerson .. please review and let us know if you have any comments.

**Comment by soumyakoduri** [comment]
@shreyanshjain7174 .. can you paste teuthology test results link.

**Comment by shreyanshjain7174** [comment]
https://pulpito.ceph.com/ssancheti-2024-10-10_09:56:20-rgw-wip-skoduri-cloud-restore-distro-default-smithi/

**Comment by soumyakoduri** [comment]
http://pulpito.front.sepia.ceph.com/soumyakoduri-2024-11-29_12:18:29-rgw-wip-skoduri-test-distro-default-smithi/detail

**Pull request merged**
