### PR TITLE
 auth: reuse PK11Context in nss_aes_operation

### PR DESCRIPTION
**Pull request by rzarzynski**
Need to move to the `ScopedPK11Context` (UPDATE: or `pk11_context_ptr` depending on what gets merged; postponing for now and proceeding with raw pointers to `PK11Context`).

### CODE REVIEW

**Comment by tchaikov** [comment]
@rzarzynski this idea was proved as a no-go, see #21179, as the PK11Context is not thread-safe.

**Comment by rzarzynski** [comment]
@tchaikov: oops, haven't read your comment in the PR. :-(
Anyway, maybe there still is a chance. `CephxSessionHandler` appears as the critical `CryptoKey` user in profiling. If an instance the handler has is accessed from different cores relatively rarely, then we could try.

**Comment by rzarzynski** [comment]
http://tracker.ceph.com/issues/23552

In short:
1. reusing `PK11Context` just for the Cephx doesn't look impossible;
2. even with that there still is huge overhead from NSS.

**Comment by rzarzynski** [comment]
Closing in favor of moving to NSS (#21540).

**Pull request closed without merging**
