### PR TITLE
cmake: should link against ${ALLOC_LIBS}

### PR DESCRIPTION
**Pull request by tchaikov**
rocksdb references some jemalloc specific symbols (malloc_stats_print()
for example), if jemalloc is enabled. this fails the build. so we need
to link against ${ALLOC_LIBS} when appropriate.

Signed-off-by: Kefu Chai <kchai@redhat.com>

### CODE REVIEW

**Comment by tchaikov** [comment]
@varadakari could you give this PR a spin?

**Comment by wjwithagen** [comment]
@tchaikov 
FreeBSD has jemalloc as default malloc, So perhaps I should just try and modify `./src/rocksdb/CMakeLists.txt` to do the right thing.

**Comment by wjwithagen** [comment]
@tchaikov 
Fixed some of the code within rocksdb upstream.

**Comment by tchaikov** [comment]
the upstream PR is https://github.com/facebook/rocksdb/pull/1516

**Comment by dachary** [comment]
jenkins test this please (eio now ignored in master)

**Comment by liewegas** [comment]
https://github.com/ceph/ceph/pull/12056 pulls up to latest rocksdb

**Comment by liewegas** [comment]
@tchaikov that includes the upstream version of your patch, and @wjwithagen 's latest other fix.

**Comment by dachary** [comment]
jenkins test this please (ceph-disk tox failed, now fixed in master)

**Comment by yuriw** [comment]
test this please

**Comment by varadakari** [comment]
@tchaikov Sorry for the delayed reply. will try it today. Changes look good.

**Comment by tchaikov** [comment]
@varadakari thanks for testing!

**Comment by dachary** [comment]
jenkins test this please (eio now ignored in master)

**Pull request merged**
