### PR TITLE
cephadm: fix selinux mount mis-indent

### PR DESCRIPTION
**Pull request by liewegas**
We want to map this path even if we had to create the empty directory.

Signed-off-by: Sage Weil <sage@newdream.net>

### CODE REVIEW

**Review by b-ranto — APPROVED** [review]

**Review by sebastian-philipp — APPROVED** [review]

**Comment by sebastian-philipp** [comment]
so the problem with the current approach is: this is going to fail, if someone enables selinux **after** deploying the OSDs. I think this is ok as it is for now

**Comment by liewegas** [comment]
yeah.  not sure how else to do it since (I think/) /sys/fs/selinux appears
when selinux is enabled...

**Review by jmolmo — APPROVED** [review]
Sorry and thanks for the fix!

**Comment by ktdreyer** [comment]
Longer term, I wonder if we could avoid mounting all of `/sys`, and only mount the exact paths that ceph-volume and the OSDs require.

**Comment by liewegas** [comment]
I like the sound of that!  Putting it on my list.. it might be a pretty
easy change.

**Comment by sebastian-philipp** [comment]
> I like the sound of that! Putting it on my list.. 

Do you want to make a tracker issue?

**Pull request merged**
