### PR TITLE
octopus: mgr: don't update osd stat which is already out

### PR DESCRIPTION
**Pull request by ifed01**
Fixes: https://tracker.ceph.com/issues/48401

---

Ceph status still reports slow requests on the OSD which is already out.
When orignal PG monitor handled PGSTATS msg, it wouldn't update osd stat
if this OSD is not in OSD map, but current MGR had no checks on that.

Fixes: https://tracker.ceph.com/issues/46440

Signed-off-by: Zhi Zhang <zhangz.david@outlook.com>
(cherry picked from commit 493ec9d3acd3f57eed3e4b96ad7c6739c2089ff1)

### CODE REVIEW

**Comment by tchaikov** [comment]
@ifed01 could you redo the cherry-pick. somehow this PR pulled in lots of unrelated changes.

**Comment by ifed01** [comment]
> @ifed01 could you redo the cherry-pick? somehow this PR pulled in lots of unrelated changes.

yeah, looks like Josh made something with octopus branch:
> jdurgin force-pushed the ceph:octopus branch from 3b1861a to 99e6b83 5 hours ago

Seen this issue to multiple Octopus PR's today....

**Comment by ifed01** [comment]
@tchaikov - updated

**Comment by smithfarm** [comment]
test this please

**Review by neha-ojha — APPROVED** [review]

**Comment by yuriw** [comment]
[wip-yuri2-testing-2021-01-04-0837-octopus](https://trello.com/c/Fk0Aj3z8/1096-wip-yuri2-testing-2021-01-04-0837-octopus)

**Pull request merged**
