### PR TITLE
pacific: cephadm: August batch 1

### PR DESCRIPTION
**Pull request by sebastian-philipp**
Backport of #41854, #42108, #42134, #42017, #41906, #42032, #41829, #41938, #42177, #42092, #42113, #42209, #42227, #42291, #42288, #42244, #42327, #42220, #42290, #42341, #42379, #42391, #42372, #42304, #41280, #42028, #42289, #42415, #42342, #42433, #42468, #42467, #42466, #42389, #42511, #42538, #42523, #42356, #42553, #42400, #42551, #42446, #42518, #42567, #42594, #42395, #42462, #42242, #42665, #42664, #42673, #42686, #42726

```
➜  mgr git:(pacific-backport-41854-42108-42134-42017-41906-42032-41829-41938-42177-42092-) ✗ git log -n 200 | grep -C 3 Conflicts
    Signed-off-by: Sebastian Wagner <sewagner@redhat.com>
    (cherry picked from commit 0c78d239a1933338fea14e21fde2638a418bc660)
    
    Conflicts:
            src/cephadm/cephadm

commit d2012a27d1d9f13b13d8a145c8d75cd5da383030
--
    Signed-off-by: Michael Fritch <mfritch@suse.com>
    (cherry picked from commit 25d62794fc3cfb6496da12a265c97871a470fa4f)
    
    Conflicts:
            src/cephadm/tests/test_cephadm.py
```

### CODE REVIEW

**Comment by sebastian-philipp** [comment]
both tests succeeded, but we not able to deliver the status to github

**Comment by sebastian-philipp** [comment]
jenkins retest this please

**Review by liewegas — APPROVED** [review]

**Comment by sebastian-philipp** [comment]
https://pulpito.ceph.com/swagner-2021-08-18_13:52:43-rados:cephadm-wip-swagner2-testing-2021-08-18-1238-pacific-distro-basic-smithi/ 

looks reasonable good

**Comment by sebastian-philipp** [comment]
https://pulpito.ceph.com/swagner-2021-08-20_11:35:16-rados:cephadm-wip-swagner2-testing-2021-08-18-1238-pacific-distro-basic-smithi/

Known issue: https://tracker.ceph.com/issues/49287

**Pull request merged**
