### PR TITLE
doc: removed warning for resolved errata

### PR DESCRIPTION
**Pull request by CharlotteRose**
Signed-off-by: Scoots Hamilton <scoots@redhat.com>

### CODE REVIEW

**Comment by CharlotteRose** [comment]
jenkins render docs

**Comment by CharlotteRose** [comment]
removed whitespace

**Comment by batrick** [comment]
@CharlotteRose missing signed-off

**Comment by CharlotteRose** [comment]
Signed-off-by: Scoots Hamilton scoots@redhat.com

**Comment by batrick** [comment]
@CharlotteRose I mean you need to the `Signed-off-by` in every commit message. It is only in your first commit. You can change it using `git rebase --signoff upstream/master` and then force pushing to your branch on github `git push -f ...`.

**Comment by CharlotteRose** [comment]
> @CharlotteRose I mean you need to the `Signed-off-by` in every commit message. It is only in your first commit. You can change it using `git rebase --signoff upstream/master` and then force pushing to your branch on github `git push -f ...`.

Im sorry! I will get it right soon. Pinky promise ^_^

**Pull request merged**
