### PR TITLE
doc: update .rst file with their .8 counterparts

### PR DESCRIPTION
**Pull request by tchaikov**
this also pave the road to a git repo without .8 files!

### CODE REVIEW

**Comment by dachary** [comment]
I don't see .8 files here ?

**Comment by dachary** [comment]
maybe these are necessary because the .8 files already in the repository have that change already ?

**Comment by tchaikov** [comment]
@dachary yes, i am trying to keep the rst files up to date before the .8 files are nuked.

**Comment by dachary** [comment]
the bot FAIL is a false negative that can be ignored

**Pull request merged**
