### PR TITLE
mimic: qa/ceph-ansible: Move "branch" out of "vars" section

### PR DESCRIPTION
**Pull request by badone**
This was mistakenly added to the wrong section.

Signed-off-by: Brad Hubbard <bhubbard@redhat.com>

- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by badone** [comment]
@yuriw ping?

**Comment by smithfarm** [comment]
test this please

**Comment by yuriw** [comment]
[wip-yuri3-testing-2018-12-13-1649-mimic](https://trello.com/c/zJ9D5cyL/490-wip-yuri3-testing-2018-12-13-1649-mimic)

**Comment by badone** [comment]
jenkins, test this please

**Pull request merged**
