### PR TITLE
common/TrackedOp: add op priority for TrackedOp

### PR DESCRIPTION
**Pull request by es-gyt**
https://tracker.ceph.com/issues/49789

Signed-off-by: Yite Gu <yite.gu@easystack.cn>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by es-gyt** [comment]
I want to add priority of TrackedOp, this value will display in dump_historic_ops.
This patch is convenient for us to investigate problems.
like:
`{
            "description": "osd_op(mds.0.4:35 2.7 2:f83d65d8:::200.00000004:head [delete] snapc 0=[] ondisk+write+known_if_redirected+full_force e11)",
            "priority": 63,
            "initiated_at": "2021-03-12 17:55:23.017862",
            "age": 291.562088,
            "duration": 0.055059,
            "type_data": {
                "flag_point": "started",
                "events": [
                    {
                        "time": "2021-03-12 17:55:23.017862",
                        "event": "initiated"
                    },
                    {
                        "time": "2021-03-12 17:55:23.017912",
                        "event": "queued_for_pg"
                    },
                    {
                        "time": "2021-03-12 17:55:23.062920",
                        "event": "reached_pg"
                    },
                    {
                        "time": "2021-03-12 17:55:23.065793",
                        "event": "started"
                    },
                    {
                        "time": "2021-03-12 17:55:23.072921",
                        "event": "done"
                    }
                ]
            }
        }`

**Comment by es-gyt** [comment]
@tchaikov Can you help me see

**Comment by es-gyt** [comment]
@aclamk I'm sorry to disturb you, my this patch make check failed, the detail for this failed:

../src/test/test_mempool.cc:430: Failure
Expected: (VarX) < (200), actual: 217.5 vs 200

How should I fix it?

**Comment by tchaikov** [comment]
@es-gyt it's a known issue tracked by https://tracker.ceph.com/issues/49781.

**Comment by tchaikov** [comment]
jenkins test make check

**Comment by es-gyt** [comment]
@tchaikov thx, make check succeeded.

**Comment by es-gyt** [comment]
@tchaikov please help me review code

**Comment by tchaikov** [comment]
@es-gyt will do.

**Comment by tchaikov** [comment]
@es-gyt hi Yite, sorry for the latency. could you help me understand the use case of the "priority" property ? how do you plan to take advantage of it when, for instance, looking into a performance issue?

**Pull request closed without merging**
