### PR TITLE
os/bluestore/KernelDevice: fix sync write vs flush

### PR DESCRIPTION
**Pull request by liewegas**

### CODE REVIEW

**Comment by markhpc** [comment]
Before merging this, I want to retest.  It turns out I had forgotten to explicitly disable rbd cache in the ceph.conf file I was using, potentially resulting in a client side bottleneck for small random writes on NVMe.

**Comment by liewegas** [comment]
http://pulpito.ceph.com/sage-2017-05-12_14:53:12-rados-wip-sage-testing---basic-smithi/

**Comment by liewegas** [comment]
should retest with the latest patch too.

**Comment by yuriw** [comment]
http://pulpito.ceph.com/yuriw-2017-05-15_22:59:10-rados-wip-yuri-testing_2017_5_16-distro-basic-smithi/

http://pulpito.ceph.com/yuriw-2017-05-16_13:48:34-rados-wip-yuri-testing_2017_5_16---basic-smithi/

**Comment by markhpc** [comment]
Test results attached
[fixed_tests.xlsx](https://github.com/ceph/ceph/files/1008406/fixed_tests.xlsx)

**Pull request merged**
