### PR TITLE
luminous: cmake: pass -march to detect compiler support of arm64 crc/crypto

### PR DESCRIPTION
**Pull request by tchaikov**
http://tracker.ceph.com/issues/36080

### CODE REVIEW

**Comment by tchaikov** [comment]
@smithfarm sorry for the confusion. the master PR is still pending on review, see #24168. because the luminous's build requirement on compiler is quite different than that of master and mimic, i tried to prepare the luminous backport earlier than normal. 

i am adding the "DNM" label now. will re-open it and re-cherry-pick it once the master PR is approved and merged.

**Comment by smithfarm** [comment]
@tchaikov OK, I added the URL of your (new) master PR to the (old) bug. Since that old bug already had a fix with a backport, and was all marked resolved, I would have preferred to open a new bug in this case. Less confusion.

**Comment by tchaikov** [comment]
will do so next time.

**Comment by tchaikov** [comment]
@smithfarm could you revoke the request-to-change?

**Comment by smithfarm** [comment]
@tchaikov Done. Backport is also needed to mimic, right? I added it at http://tracker.ceph.com/issues/17516

**Comment by yuriw** [comment]
[wip-yuri2-testing-2019-07-15-1956-luminous](https://trello.com/c/5QdUgJyi/667-wip-yuri2-testing-2019-07-15-1956-luminous)

**Comment by yuriw** [comment]
@tchaikov @smithfarm ready for merge if all resolved

**Comment by tchaikov** [comment]
@smithfarm yeah, we need to backport it to mimic.

**Comment by tchaikov** [comment]
@yuriw this PR still needs to be approved before getting merged.

**Comment by smithfarm** [comment]
Far from being an ARM compiler expert, I'm definitely not the right person to review this.

It's not clear (to me) exactly which bug this is fixing.

**Comment by tchaikov** [comment]
sure. will see of @jdurgin could help on this -- he reviewed the original PR.

**Comment by tchaikov** [comment]
@jdurgin ping?

**Pull request merged**
