### PR TITLE
reef: client: do not proceed with I/O if filehandle is invalid

### PR DESCRIPTION
**Pull request by dparmar18**
Backport of https://github.com/ceph/ceph/pull/57576 and some commits from https://github.com/ceph/ceph/pull/55457
Backport tracker: https://tracker.ceph.com/issues/64740
Parent tracker: https://tracker.ceph.com/issues/64313

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [x] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Comment by joscollin** [comment]
jenkins test make check

**Review by joscollin — COMMENTED** [review]
@dparmar18 The `make check` fails again.

**Comment by lxbsz** [comment]
jenkins test make check

**Comment by lxbsz** [comment]
@dparmar18 Could you rebase this PR to the latest ? The make check failure couldn't be fixed by retrying it. Thanks.

**Comment by dparmar18** [comment]
```The following tests FAILED:
	 31 - run-rbd-unit-tests-1.sh (Failed)```

**Comment by dparmar18** [comment]
@lxbsz rebased

**Comment by vshankar** [comment]
@dparmar18 Please include fixes from https://github.com/ceph/ceph/pull/59300 in this backport.

**Comment by dparmar18** [comment]
> @dparmar18 Please include fixes from #59300 in this backport.

Done. Just a note: since async i/o doesn't exist in reef, the snippet patching `Client::ll_preadv_pwritev` has not been included.

**Comment by rishabh-d-dave** [comment]
This PR is under test in [https://tracker.ceph.com/issues/67981](https://tracker.ceph.com/issues/67981).

**Review by vshankar — APPROVED** [review]
https://tracker.ceph.com/projects/cephfs/wiki/Reef#wip-rishabh-testing-20240910100730-reef

**Comment by vshankar** [comment]
jenkins test make check

**Pull request merged**
