### PR TITLE
doc: 15.2.16 Release Notes

### PR DESCRIPTION
**Pull request by yuriw**
Signed-off-by: Yuri Weinstein <yweinste@redhat.com>

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by yuriw** [comment]
@djgalloway I don't know why PRs started with `* b"octopus:` pls take a look

**Comment by djgalloway** [comment]
> @djgalloway I don't know why PRs started with `* b"octopus:` pls take a look

What command did you run to generate them?  Looks like you might've used python2 instead of python3?

**Comment by yuriw** [comment]
@djgalloway
`(v) yuriw@vossi02:~/ceph/src/script$ LANG=en_US.UTF-8 python3 ./ceph-release-notes -r tags/v15.2.15..origin/octopus $(git rev-parse --show-toplevel) --token $(cat ~/.github_token)`

**Comment by djgalloway** [comment]
> @djgalloway `(v) yuriw@vossi02:~/ceph/src/script$ LANG=en_US.UTF-8 python3 ./ceph-release-notes -r tags/v15.2.15..origin/octopus $(git rev-parse --show-toplevel) --token $(cat ~/.github_token)`

Make sure you're running `ceph-release-notes` from the master branch and not octopus.

**Pull request merged**
