### PR TITLE
RPM: move runtime dependencies to ceph-base and fix other packaging issues

### PR DESCRIPTION
**Pull request by smithfarm**
This PR aggregates a number of packaging fixes. Hopefully this will ease the load on the gitbuilders.

### CODE REVIEW

**Comment by smithfarm** [comment]
Pushed to gitbuilders.

**Comment by smithfarm** [comment]
This PR passes the deb+rpm amd64 gitbuilders.

**Comment by smithfarm** [comment]
However, OBS says:

```
[ 5133s] found conflict of ceph-base-10.0.3+git.1456694378.081fbf0-1.1.x86_64 with ceph-osd-10.0.3+git.1456694378.081fbf0-1.1.x86_64:
[ 5133s]   - /usr/lib/udev/rules.d/60-ceph-partuuid-workaround.rules
[ 5133s]   - /usr/lib/udev/rules.d/95-ceph-osd.rules
[ 5133s]   - /usr/lib64/rados-classes/libcls_hello.so
[ 5133s]   - /usr/lib64/rados-classes/libcls_kvs.so
[ 5133s]   - /usr/lib64/rados-classes/libcls_lock.so
[ 5133s]   - /usr/lib64/rados-classes/libcls_log.so
[ 5133s]   - /usr/lib64/rados-classes/libcls_rbd.so
[ 5133s]   - /usr/lib64/rados-classes/libcls_refcount.so
[ 5133s]   - /usr/lib64/rados-classes/libcls_replica_log.so
[ 5133s]   - /usr/lib64/rados-classes/libcls_rgw.so
[ 5133s]   - /usr/lib64/rados-classes/libcls_statelog.so
[ 5133s]   - /usr/lib64/rados-classes/libcls_user.so
[ 5133s]   - /usr/lib64/rados-classes/libcls_version.so
```

**Comment by smithfarm** [comment]
Now we are getting: 

```
[ 5056s] RPM build errors:
[ 5056s]     File listed twice: /var/lib/ceph/mds
[ 5056s]     File listed twice: /var/lib/ceph/mon
[ 5056s]     File listed twice: /var/lib/ceph/osd
[ 5056s]     Installed (but unpackaged) file(s) found:
[ 5056s]    /usr/lib64/rados-classes/libcls_cephfs.so
[ 5056s]    /usr/lib64/rados-classes/libcls_journal.so
[ 5056s]    /usr/lib64/rados-classes/libcls_numops.so
[ 5056s]    /usr/lib64/rados-classes/libcls_timeindex.so
```

**Comment by ktdreyer** [comment]
* Those rados-classes libraries should be added into ceph-base (and the duplicate rados-classes entries removed from ceph-osd).
* Those two udev rules should be in ceph-osd (and the duplicate entries removed from ceph-base).
* The `/var/lib/ceph/*` directories are each listed twice, once with an `%attr`, and once without. The entries without `%attr` should be removed.

**Comment by smithfarm** [comment]
@ktdreyer How does this look?

**Comment by ktdreyer** [comment]
Looks right to me. Thanks. If it passes gitbuilder, we can merge

**Comment by smithfarm** [comment]
Pushed latest version to gitbuilders.

**Comment by smithfarm** [comment]
@ktdreyer: It passes the RPM gitbuilders. I can't make out whether it passed the deb ones or not - can you?

**Comment by ktdreyer** [comment]
http://gitbuilder.sepia.ceph.com/gitbuilder-ceph-deb-trusty-amd64-basic/log.cgi?log=4de86bf373e8c3041bbb4fbaf560e4427aed42ab looks good! (it has `PASS` at the end)

**Pull request merged**
