### PR TITLE
mgr/dashboard: fix test_dashboard_e2e.sh errors

### PR DESCRIPTION
**Pull request by bk201**
This PR contains two fixes, they need to be tested together to fix the e2e test error.

- Adapt changes in https://github.com/ceph/ceph/pull/37994.
   - The preview button should not spin.
   - The preview button should be enabled again after destroying the  preview modal.
- Adapt changes in https://github.com/ceph/ceph/pull/35039.
- Tweak the way to get row by OSD ID.

Fixes: https://tracker.ceph.com/issues/48421
Fixes: https://tracker.ceph.com/issues/48406

Signed-off-by: Kiefer Chang <kiefer.chang@suse.com>

## Checklist
- [x] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by bk201** [comment]
jenkins test make check

**Comment by alfonsomthd** [comment]
jenkins test make check

**Review by callithea — APPROVED** [review]
lgtm

**Comment by bk201** [comment]
jenkins test make check

**Comment by bk201** [comment]
- CI branch: [wip-kiefer-testing-2020-12-03-2349](https://github.com/ceph/ceph-ci/commits/wip-kiefer-testing-2020-12-03-2349)
- [CI packages](https://shaman.ceph.com/builds/ceph/wip-kiefer-testing-2020-12-03-2349/)
- QA runs: **PASS**
  Suite|Total|Pass|Fail|Dead
  -|-|-|-|-
  [rados:cephadm:dashboard](https://pulpito.ceph.com/kchang-2020-12-04_01:30:42-rados:cephadm:dashboard-wip-kiefer-testing-2020-12-03-2349-distro-basic-smithi)|1|1|0|0

**Comment by bk201** [comment]
jenkins test dashboard

**Comment by bk201** [comment]
jenkins test make check

**Review by alfonsomthd — APPROVED** [review]

**Review by s0nea — APPROVED** [review]
Thank you for the fixes @bk201 :+1:

**Comment by tchaikov** [comment]
- https://pulpito.ceph.com/kchai-2020-12-10_14:22:12-rados-wip-kefu-testing-2020-12-10-1827-distro-basic-smithi/
- https://pulpito.ceph.com/kchai-2020-12-11_07:09:12-rados-wip-kefu-testing-2020-12-10-1827-distro-basic-smithi/

failures are not related.

**Pull request merged**
