### PR TITLE
jewel: mds: multimds flock fixes

### PR DESCRIPTION
**Pull request by batrick**
http://tracker.ceph.com/issues/20564

Backport of https://github.com/ceph/ceph/pull/15440/

### CODE REVIEW

**Comment by batrick** [comment]
@ukernel I had to remove 75ce2a9 because it depends on a cleanup commit in master. It didn't look essential. Is that right?

**Comment by batrick** [comment]
@smithfarm thanks for the link. Sorry I forgot!

**Comment by smithfarm** [comment]
Backport staged in the tracker. Once the cherry-picks are re-done I'll dismiss my review.

**Comment by smithfarm** [comment]
@batrick Here's the latest jewel integration fs run: http://tracker.ceph.com/issues/20613#note-42

There were 4 failures, 3 of which passed on the second try. The one that failed both times was Java-related, and we have ignored these in the past.

This is JFYI.

**Pull request merged**
