### PR TITLE
tools: fix ceph perf local build on i386

### PR DESCRIPTION
**Pull request by tchaikov**

### CODE REVIEW

**Comment by tchaikov** [comment]
@gregsfortytwo @yuyuyu101 could you help to review this change?

**Comment by yuyuyu101** [comment]
Reviewed-by

**Comment by tchaikov** [comment]
@yuyuyu101 thanks for your review. i added the `Fixes: #11827` line in the 63343ce

**Comment by tchaikov** [comment]
will merge this once the build bot returns or any gitbuilder confirms it again.

**Pull request merged**
