### PR TITLE
mgr/volumes: drop unused size

### PR DESCRIPTION
**Pull request by joscollin**
Fixes: https://tracker.ceph.com/issues/41752

### CODE REVIEW

**Comment by joscollin** [comment]
jenkins test make check

**Comment by ajarr** [comment]
I'm not sure. Should we remove this option, or try setting quota at the root of the file system?

@batrick what do you think?

**Comment by batrick** [comment]
If volumes eventually become disposable then a root quota could be useful. But for now, removing the size is probably fine.

**Comment by batrick** [comment]
@joscollin this needs a tracker ticket for backport

**Comment by joscollin** [comment]
> @joscollin this needs a tracker ticket for backport

I thought this is trivial. I will create the tracker ticket.

**Comment by joscollin** [comment]
Created the tracker and updated the commit.

**Comment by batrick** [comment]
@joscollin you can start doing targeted teuthology QA runs for volumes plugin PRs. Just use `--filter volumes` on the fs suite and link the results in these PRs.

**Pull request merged**
