### PR TITLE
squid: rgw/beast: optimize for accept when meeting error in listenning

### PR DESCRIPTION
**Pull request by liangmingyuanneo**
backport tracker: https://tracker.ceph.com/issues/67957

backport of https://github.com/ceph/ceph/pull/59014
parent tracker: https://tracker.ceph.com/issues/67338

Signed-off-by: Mingyuan Liang [liangmingyuan@baidu.com](mailto:liangmingyuan@baidu.com)

### CODE REVIEW

**Review by cbodley — CHANGES_REQUESTED** [review]
thanks @liangmingyuanneo 

the requirements for backports are documented in [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/main/SubmittingPatches-backports.rst) - the main requirement is that commits are cherry-picked with `git cherry-pick -x`

most people use [src/script/ceph-backport.sh](https://github.com/ceph/ceph/blob/main/src/script/ceph-backport.sh) to prepare backport prs. you can find instructions on its use under [Opening a Backport PR](https://github.com/ceph/ceph/blob/main/SubmittingPatches-backports.rst#opening-a-backport-pr)

**Comment by liangmingyuanneo** [comment]
@cbodley squid still uses `spawn::spawn()` that doesn't contain `bind_cancellation_slot()`, do you have advices to do it? I researched and found it is hard to kill new spawned coroutine.

**Comment by liangmingyuanneo** [comment]
If it is not worth backporting, should we retry some times in the way that blocking the calling thread when meeting error in `l.acceptor.async_accept()`? If I am not wrong, for `boost::system::errc::too_many_files_open` and `boost::system::errc::not_enough_memory`, though we aren't blocking the calling thread, the subsequent connections may can not be built successfully. And blocking is better than stoping directly?

**Comment by liangmingyuanneo** [comment]
> @adamemerson do you think that's worth backporting? pretty sure that didn't depend on boost 1.85.

Yep. boost 1.79 already contains `bind_cancellation_slot()`, which means reef can merge the pr too. Now that when  I try to merge that to squid, meeting many conflicts. So I believe more conflicts will be met in reef. But I'm happy to continue backporting if you think it is nessesary.

Should I continue to do it?

**Comment by adamemerson** [comment]
> > @cbodley squid still uses `spawn::spawn()` that doesn't contain `bind_cancellation_slot()`, do you have advices to do it?
> 
> ah, crap. i think we'd need to backport #55592 to squid for this
> 
> @adamemerson do you think that's worth backporting? pretty sure that didn't depend on boost 1.85. it did cause at least one regression, so #57630 would need to be backported too

Possibly.

It's performance rather than correctness, but if it's significant performance or helps a pathology we expect to run into, I'd say yes.

If using `boost::asio::spawn` would make future backports easier by removing a source of difference, and we're not going to EoL Squid any time soon, I'd say that's also a yes, though I kind of doubt it would

**Comment by cbodley** [comment]
@liangmingyuanneo thanks for backporting https://github.com/ceph/ceph/pull/60133! after its merge, i was able to run the ceph-backport.sh script for https://tracker.ceph.com/issues/67957 with no conflicts. the result is in https://github.com/ceph/ceph/pull/60244, so i'm closing this one

**Pull request closed without merging**
