### PR TITLE
mgr/dashboard: Move unit-test-helper into the new testing folder

### PR DESCRIPTION
**Pull request by tspmelo**
Angular [1] suggest us to create a `src/testing` folder where we can put files that will be used in tests.
I created that folder on #22829 and to keep it consistent I'm now moving `unit-test-helper.ts` to that folder.

[1] https://angular.io/guide/testing#activatedroutestub

### CODE REVIEW

**Comment by tspmelo** [comment]
jenkins retest this please

**Comment by tspmelo** [comment]
Rebased.

**Comment by ricardoasmarques** [comment]
Jenkins retest this please

**Comment by smithfarm** [comment]
@lenzgr Oops, sorry. I guess you guys are using "needs-backport"? How do you know which branches it needs backporting to?

**Pull request merged**
