### PR TITLE
nautilus: cephfs: client: dump which fs is used by client for multiple-fs

### PR DESCRIPTION
**Pull request by batrick**
https://tracker.ceph.com/issues/48374

### CODE REVIEW

**Comment by yuriw** [comment]
[wip-yuri-testing-2021-01-04-0849-nautilus](https://trello.com/c/TeeQ4Sgg/1097-wip-yuri-testing-2021-01-04-0849-nautilus)

**Comment by batrick** [comment]
`Reviewed-by: Patrick Donnelly <pdonnell@redhat.com>`

**Comment by smithfarm** [comment]
@yuriw It looks like you already tested this and it got approved, but since you didn't merge it, I'm flagging it for another round of testing.

**Review by smithfarm — APPROVED** [review]
`Reviewed-by: Patrick Donnelly <pdonnell@redhat.com>`

**Pull request merged**
