### PR TITLE
octopus: global: reexpand conf meta in child process

### PR DESCRIPTION
**Pull request by smithfarm**
backport trackers:

* https://tracker.ceph.com/issues/48084
* https://tracker.ceph.com/issues/48456

---

backport of

* https://github.com/ceph/ceph/pull/37898
* https://github.com/ceph/ceph/pull/38058

parent trackers:

* https://tracker.ceph.com/issues/48046
* https://tracker.ceph.com/issues/48240

this backport was staged using ceph-backport.sh version 15.1.1.389
find the latest version at https://github.com/ceph/ceph/blob/master/src/script/ceph-backport.sh

### CODE REVIEW

**Comment by smithfarm** [comment]
jenkins test docs

**Comment by smithfarm** [comment]
jenkins test api

**Comment by smithfarm** [comment]
jenkins test make check

**Review by dillaman — APPROVED** [review]
:+1:  -- but it will be reverted by [1]

[1] https://tracker.ceph.com/issues/48240

**Review by trociny — APPROVED** [review]
LGTM, though as Jason noticed it will be reverted after backporting [1] so it probably makes sense to backport both in one PR.

[1] https://tracker.ceph.com/issues/48240

**Comment by smithfarm** [comment]
@dillaman @trociny OK, I brought in the second related backport as suggested.

**Review by trociny — APPROVED** [review]
:+1:

**Review by lxbsz — APPROVED** [review]
LGTM, thanks.

**Comment by smithfarm** [comment]
```
7/197 Test   #8: run-rbd-unit-tests-0.sh .................***Failed  109.74 sec
```

**Comment by smithfarm** [comment]
jenkins test make check

**Comment by yuriw** [comment]
[wip-yuri7-testing-2020-12-14-0841-octopus](https://trello.com/c/WBLPidv7/1086-wip-yuri7-testing-2020-12-14-0841-octopus)

**Pull request merged**
