### PR TITLE
squid: qa: use centos9 for fs:upgrade

### PR DESCRIPTION
**Pull request by vshankar**
backport tracker: https://tracker.ceph.com/issues/66519

---

backport of https://github.com/ceph/ceph/pull/57991
parent tracker: https://tracker.ceph.com/issues/65580

this backport was staged using ceph-backport.sh version 16.0.0.6848
find the latest version at https://github.com/ceph/ceph/blob/main/src/script/ceph-backport.sh

### CODE REVIEW

**Comment by vshankar** [comment]
@dparmar18 @batrick For this backport the upgrades are started from quincy/reef releases.

cc @yuriw

**Comment by vshankar** [comment]
@joscollin @leonid-s-usov This needs to be put to test once we get a review approval.

**Comment by ljflores** [comment]
jenkins test api

**Comment by ljflores** [comment]
jenkins test make check

**Comment by leonid-s-usov** [comment]
@vshankar please take the action item to run tests with this one, as I wasn't following this one and I'm not sure what kind of tests to schedule.

**Comment by vshankar** [comment]
> @vshankar please take the action item to run tests with this one, as I wasn't following this one and I'm not sure what kind of tests to schedule.

Sure. @yuriw would likely put this to test soon.

**Comment by ljflores** [comment]
@vshankar I scheduled tests here:
https://pulpito.ceph.com/lflores-2024-06-19_18:08:35-upgrade:cephfs-squid-distro-default-smithi/
```
./teuthology/virtualenv/bin/teuthology-suite -v -m smithi -c squid -S e8c97fb65c524873cff8a6429d7a412fbf41145c -s upgrade/cephfs --subset 111/120000 --suite-repo https://github.com/vshankar/ceph.git --suite-branch wip-66519-squid -p 75 --force-priority
```

**Comment by vshankar** [comment]
https://pulpito.ceph.com/vshankar-2024-06-27_04:50:01-fs:upgrade-wip-yuri10-testing-2024-06-19-1225-testing-default-smithi/

**Comment by vshankar** [comment]
@yuriw this is good to merge once the change gets a review approval.

**Review by batrick — APPROVED** [review]

**Comment by NitzanMordhai** [comment]
rados approved: https://tracker.ceph.com/projects/rados/wiki/SQUID#httpstrackercephcomissues66569

**Pull request merged**
