### PR TITLE
rgw: fix CompleteMultipart error handling regression

### PR DESCRIPTION
**Pull request by cbodley**
https://github.com/ceph/ceph/pull/54569 moved some CompleteMultipart code around, and introduced a regression in the error path that causes the 'multipart meta object' to be deleted prematurely

Fixes: https://tracker.ceph.com/issues/65746

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Comment by cbodley** [comment]
the `test_ps_s3_multipart_on_master_http` test case from https://github.com/ceph/ceph/pull/54569 is still passing

**Comment by mattbenjamin** [comment]
could be helpful to have brief comment in the commit messages explaining it's intended affect

**Review by AliMasarweh — APPROVED** [review]
Looks good

**Review by mattbenjamin — APPROVED** [review]
lgtm

**Comment by cbodley** [comment]
passed qa in https://pulpito.ceph.com/cbodley-2024-05-04_01:44:24-rgw-wip-65746-distro-default-smithi/ with rerun https://pulpito.ceph.com/cbodley-2024-05-06_13:28:12-rgw-wip-65746-distro-default-smithi/

**Pull request merged**
