### PR TITLE
osd: dout more log info to track io request

### PR DESCRIPTION
**Pull request by XinzeChi**
This is useful for tracking io request.

Signed-off-by: Xinze Chi <xmdxcxz@gmail.com

### CODE REVIEW

**Comment by liewegas** [comment]
looks okay to me

**Comment by athanatos** [comment]
This does not merge cleanly, removing needs-qa.

**Comment by XinzeChi** [comment]
rebase @athanatos

**Comment by tchaikov** [comment]
tested at http://pulpito.ceph.com/ubuntu-2015-06-12_21:23:04-rados-wip-kefu-testing---basic-multi/, the failed one is not relevant, and it passed in a second run at http://pulpito.ceph.com/ubuntu-2015-06-14_06:07:33-rados-wip-kefu-testing---basic-multi/933027/. the failed test was tracked at http://tracker.ceph.com/issues/12013 .

@athanatos ping?

**Pull request merged**
