### PR TITLE
mon: Fix ceph versions command

### PR DESCRIPTION
**Pull request by pdvian**
The commit-id d3cca1d has introduced a bug where mgr/osd/mds
    version information goes missing during the cluster upgrade.
    Collect version information before checking the emptiness
    of the map.
    
    Fixes: https://tracker.ceph.com/issues/61453
    
    Signed-off-by: Prashant D <pdhange@redhat.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [x] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Review by neha-ojha — COMMENTED** [review]
@pdvian let's refer to d3cca1d5ae692f332f5d3ed94ca1cec8e1ac0a8a instead of the merge commit in the commit message

**Comment by ljflores** [comment]
jenkins test api

**Review by ljflores — APPROVED** [review]

**Review by shreyanshjain7174 — APPROVED** [review]
LGTM! earlier it was checking if the field is empty.

**Comment by pdvian** [comment]
https://pulpito.ceph.com/?branch=wip-yuri-testing-2023-05-26-1204

Failures, unrelated:
1. https://tracker.ceph.com/issues/49961
2. https://tracker.ceph.com/issues/61497     -- new tracker
3. https://tracker.ceph.com/issues/61225
4. https://tracker.ceph.com/issues/58560
5. https://tracker.ceph.com/issues/59057
6. https://tracker.ceph.com/issues/55347


Details:
1. scrub/osd-recovery-scrub.sh: TEST_recovery_scrub_1 failed - Ceph - RADOS
2. ERROR:gpu_memory_buffer_support_x11.cc(44)] dri3 extension not supported - Dashboard
3. TestClsRbd.mirror_snapshot failure - Ceph - RBD
4. test_envlibrados_for_rocksdb.sh failed to subscribe to repo - Infrastructure
5. rados/test_envlibrados_for_rocksdb.sh: No rule to make target 'rocksdb_env_librados_test' on centos 8 - Ceph - RADOS
6. SELinux Denials during cephadm/workunits/test_cephadm - Infrastructure

Additionally : 
* 4 Rook test failured due to signature validation failed for https://packages.cloud.google.com/apt repo
  - GPG error: https://packages.cloud.google.com/apt kubernetes-xenial InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY B53DC80D13EDEF05

**Pull request merged**
