### PR TITLE
rgw: fix the bug that the s3cmd abortmp operation may delete the bucket by mistake.

### PR DESCRIPTION
**Pull request by qwer506**
Fixes: https://tracker.ceph.com/issues/48727

Signed-off-by: houfei <houfei@chinatelecom.cn>

### CODE REVIEW

**Comment by houfei001** [comment]
@mattbenjamin @cbodley Please take a review. Thanks

**Comment by ofriedma** [comment]
@houfei001 Thank you for your contribution.
Can you please squash it into 1 commit.
I don't think this is a complete solution for this bug, It may happen if someone will send DELETE /<bucket>/?versions for exapmle too, I think we need to cover all those cases.
It looks like we fallback immediately to bucket although we got arg that match only to object context, so maybe we should check that the args we send to bucket are part of the bucket context.

`    if (s->init_state.url_bucket.empty()) {
      handler = new RGWHandler_REST_Service_S3(auth_registry, enable_sts, enable_iam, enable_pubsub);
    } else if (rgw::sal::RGWObject::empty(s->object.get())) {
      handler = new RGWHandler_REST_Bucket_S3(auth_registry, enable_pubsub);
    } else {
      handler = new RGWHandler_REST_Obj_S3(auth_registry);
    }
  }` 

Maybe add `else if (rgw::sal::RGWObject::empty(s->object.get()))` to this section a check that it will verify the args so it will not go to the bucket code path.

@houfei001 what do you think?

**Comment by houfei001** [comment]
@ofriedma That's a good point. I'll try to deal with it.

**Comment by BryceCao** [comment]
@ofriedma  this is a complete solution for this bug  https://github.com/ceph/ceph/pull/38741

**Comment by houfei001** [comment]
@ofriedma Happy New Year.
Well in my opinion, if the request_uri does not include  the object, the request should naturally go to the bucket path.  We don't need to check the args in **else if (rgw::sal::RGWObject::empty(s->object.get()))**, since that's not elegant. Naturally, we should filter out illegal args after going to the bucket path.
@ofriedma Please take a review. Thanks!

**Comment by houfei001** [comment]
> @ofriedma Happy New Year.
> Well in my opinion, if the request_uri does not include the object, the request should naturally go to the bucket path. We don't need to check the args in **else if (rgw::sal::RGWObject::empty(s->object.get()))**, since that's not elegant. Naturally, we should filter out illegal args after going to the bucket path.
> @ofriedma Please take a review. Thanks!

In other words, we only allow legal args to pass through.

**Comment by houfei001** [comment]
I think if we have no object, we should go to the bucket handler. Even if we restrict non object exclusive access to the bucket handler，there would be some problems. That can't fix this problem. We can make complete restrictions in the bucket handler.
@dang @ofriedma @cbodley @mattbenjamin what do you think?

**Comment by houfei001** [comment]
I've tested it, it's OK, and this modification has minimal impact on the existing code. Would you like to take a review again. @ofriedma

**Comment by BryceCao** [comment]
@houfei001  nice work when illegal args exist, maybe It's better to add this check for object delete handler as well.

**Pull request closed without merging**
