### PR TITLE
ceph-volume: import mock.mock instead of unittest.mock (py2)

### PR DESCRIPTION
**Pull request by jan--f**
Fixes: bb4de1a3fc238eaf9f717dc59c6bdf338ef6d657
Fixes: https://tracker.ceph.com/issues/42970

Signed-off-by: Jan Fajerski <jfajerski@suse.com>

### CODE REVIEW

**Comment by jan--f** [comment]
jenkins test ceph-volume tox

**Comment by jan--f** [comment]
jenkins test make check

**Comment by alfredodeza** [comment]
is patching with the monkeypatch problematic? why does this need to use mock at all?

**Comment by jan--f** [comment]
> is patching with the monkeypatch problematic? why does this need to use mock at all?

`mock.patch´ imho offers more flexibility (can be used as a decorator and as acontext manager), is more explicit as to patch location and more powerful when it comes to tracking calls and triggering side effects.

**Pull request merged**
