### PR TITLE
 kv/RocksDBStore: add rocksdb_cf_compact_on_deletion_ratio options

### PR DESCRIPTION
**Pull request by Wangwenjuan1105**
The default deletion ratio of the community is 0, which disables triggering compression based on the deletion ratio. As the sliding window optimization does not take effect, the deletion ratio configuration item is added. The default value is 0.5

Fixes: https://tracker.ceph.com/issues/63280

Signed-off-by: Wangwenjuan wangwenjuan_yewu@cmss.chinamobile.com

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by aclamk** [comment]
@Wangwenjuan1105 
It seems some commits missing from the solution, can you verify?

**Comment by markhpc** [comment]
@Wangwenjuan1105 Hello!  It appears that this PR adds a new option, but doesn't actually implement any code that uses it?

**Comment by Wangwenjuan1105** [comment]
Thank you for your careful review. I'm sorry that the code I submitted was wrong and the use of the new option was missing. But I can't seem to update this PR. 

So I resubmitted the new PR and submitted the correct code. The PR is:https://github.com/ceph/ceph/pull/54203.

Please help review again, thank you @aclamk @markhpc

**Comment by ifed01** [comment]
@Wangwenjuan1105 - your patch still brings new setting definition but there is no code for its processing. Please fix,

**Comment by markhpc** [comment]
@Wangwenjuan1105 ok, I'm going to close this PR in favor of #54203 then.  Please feel free to re-open if that is in error.  Thanks!

**Pull request closed without merging**
