### PR TITLE
nautilus: rgw: remove rgw_num_rados_handles; set autoscale parameters or rgw metadata pools

### PR DESCRIPTION
**Pull request by liewegas**
Backport of #27102 and #27375.  The rados handles removal got rid of conflicts with rgw_init_ioctx() in svc_rados.cc ... maybe there is an easier way?

### CODE REVIEW

**Comment by smithfarm** [comment]
@liewegas This PR now has a conflict in PendingReleaseNotes - can you please fix?

@cbodley Review?

**Comment by smithfarm** [comment]
@liewegas Pinging second time for rebase

**Comment by smithfarm** [comment]
This just needs a PendingReleaseNotes tweak.

**Comment by smithfarm** [comment]
@yuriw This just needs a PendingReleaseNotes tweak and it's good to go into testing.

**Comment by theanalyst** [comment]
updated release notes

**Comment by yuriw** [comment]
@liewegas @cbodley pls rebase

--- pr 27684 --- pulling https://github.com/liewegas/ceph.git branch wip-rgw-pgs-nautilus
remote: Enumerating objects: 50, done.
remote: Counting objects: 100% (50/50), done.
remote: Compressing objects: 100% (8/8), done.
remote: Total 50 (delta 42), reused 46 (delta 42), pack-reused 0
Unpacking objects: 100% (50/50), done.
From https://github.com/liewegas/ceph
 * branch            wip-rgw-pgs-nautilus -> FETCH_HEAD
Auto-merging src/rgw/rgw_op.cc
Auto-merging src/rgw/rgw_gc.cc
CONFLICT (content): Merge conflict in src/rgw/rgw_gc.cc
Automatic merge failed; fix conflicts and then commit the result.
Traceback (most recent call last):
  File "/home/yuriw/wip_master/src/script/build-integration-branch", line 62, in <module>
    assert not r
AssertionError

**Comment by yuriw** [comment]
[wip-yuri5-testing-2019-08-15-2024-nautilus](https://trello.com/c/TxDAX9EW/692-wip-yuri5-testing-2019-08-15-2024-nautilus)

**Comment by smithfarm** [comment]
Needs another rebase.

**Comment by theanalyst** [comment]
done

**Comment by smithfarm** [comment]
Thanks, @cbodley

**Pull request merged**
