### PR TITLE
pybind: add flock to libcephfs python bindings

### PR DESCRIPTION
**Pull request by jcsp**
Depends on: https://github.com/ceph/ceph/pull/7901

### CODE REVIEW

**Comment by gregsfortytwo** [comment]
@ukernel, please review

**Comment by ukernel** [comment]
reviewed by

**Comment by jcsp** [comment]
Updated to use fd2 correctly in test

**Comment by ukernel** [comment]
reviewed-by

**Comment by jcsp** [comment]
Passing (on top of https://github.com/ceph/ceph/pull/7901 with qa suite https://github.com/ceph/ceph-qa-suite/pull/853)

http://pulpito.ceph.com/jspray-2016-03-15_08:58:50-fs:basic-wip-pycephfs-flock---basic-mira/

**Pull request merged**
