### PR TITLE
monitoring: grafana mons out of quorum should be count - sum

### PR DESCRIPTION
**Pull request by paulreece42**
not count / sum

For example, with 3 mons total, all in quorum, original will do 3/3 = 1, showing 1 out of quorum (likely just fixing a typo)

Signed-off-By: Paul Reece <paulreece42@gmail.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by avanthakkar** [comment]
jenkins test dashboard cephadm

**Review by aaSharma14 — APPROVED** [review]

**Review by avanthakkar — APPROVED** [review]
LGTM! 
I've created a Ceph tracker for this issue https://tracker.ceph.com/issues/61923. 
Can you add it to your commit message
https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst#id8

**Comment by paulreece42** [comment]
Sure thing, added now!

**Comment by avanthakkar** [comment]
IT should be `Signed-off-by: ` in commit message

**Comment by paulreece42** [comment]
Ah I see, should be amended now, thanks!

**Comment by nizamial09** [comment]
Thank you @paulreece42! took me some time to circle back to it, sorry for that!

**Pull request merged**
