### PR TITLE
rgw: Fix for Policy Parse exception in case of multiple statements.

### PR DESCRIPTION
**Pull request by pritha-srivastava**
Signed-off-by: Pritha Srivastava <prsrivas@redhat.com>

### CODE REVIEW

**Comment by adamemerson** [comment]
Jenkins, retest this please

**Comment by adamemerson** [comment]
For the love of Pete, Jenkins. Retest this, please!

**Comment by adamemerson** [comment]
I am so sick of you, Jenkins. Retest this, please.

**Comment by cbodley** [comment]
༼ つ ◕_◕ ༽つ TAKE MY ENERGY JENKINS ༼ つ ◕_◕ ༽つ

**Pull request merged**
