### PR TITLE
rbd: add deep cp CLI method

### PR DESCRIPTION
**Pull request by Songweibin**
Signed-off-by: songweibin <song.weibin@zte.com.cn>

### CODE REVIEW

**Comment by dillaman** [comment]
This will need to be rebased once PR #19821 is merged

**Comment by dillaman** [comment]
retest this please

**Comment by Songweibin** [comment]
@dillaman  Rebased, thank you.

**Comment by dillaman** [comment]
The ```cli_generic.sh``` test fails:

```
2018-01-23T03:42:24.515 INFO:tasks.workunit.client.0.smithi115.stderr:+ rbd deep copy testimg1 testimg4
2018-01-23T03:42:24.550 INFO:tasks.workunit.client.0.smithi115.stderr:
Image deep copy: 0% complete...failed.2018-01-23 03:42:24.752 7f80fb8f0780 -1 librbd: rbd image testimg4 already exists
2018-01-23T03:42:24.550 INFO:tasks.workunit.client.0.smithi115.stderr:
2018-01-23T03:42:24.550 INFO:tasks.workunit.client.0.smithi115.stderr:rbd: deep copy failed: (17) File exists
2018-01-23T03:42:24.551 INFO:tasks.workunit.client.0.smithi115.stderr:2018-01-23 03:42:24.752 7f80fb8f0780 -1 librbd::api::Image: deep_copy: header creation failed
```

http://qa-proxy.ceph.com/teuthology/jdillaman-2018-01-22_15:45:01-rbd-wip-jd-testing-distro-basic-smithi/2101139/teuthology.log

**Comment by Songweibin** [comment]
@dillaman  Add `testimg4 testimg5 testimg6` in `IMGS`. Thank you.
```
-IMGS="testimg1 testimg2 testimg3 testimg-diff1 testimg-diff2 testimg-diff3 foo foo2 bar bar2 test1 test2 test3 clone2"
+IMGS="testimg1 testimg2 testimg3 testimg4 testimg5 testimg6 testimg-diff1 testimg-diff2 testimg-diff3 foo foo2 bar bar2 test1 test2 test3 clone2"
```

**Pull request merged**
