### PR TITLE
mds: fix hangs involving re-entrant calls to journaler

### PR DESCRIPTION
**Pull request by jcsp**
Fixes: http://tracker.ceph.com/issues/20165
Signed-off-by: John Spray <john.spray@redhat.com>

### CODE REVIEW

**Comment by jcsp** [comment]
Updated to wrap the main objecter completion in a finisher, because I was seeing MDS hangs occasionally -- I think the existing code may have only been working in the (normal) case where taking objecter's internal write lock was not needed.

**Comment by ukernel** [comment]
this does not compile. following patch can fix it
<pre>
diff --git a/src/mds/PurgeQueue.cc b/src/mds/PurgeQueue.cc
index b854973..430d3ee 100644
--- a/src/mds/PurgeQueue.cc
+++ b/src/mds/PurgeQueue.cc
@@ -462,7 +462,7 @@ void PurgeQueue::_execute_item(
             journaler.trim();
             }));
     }
-  }, finisher)));
+  }), &finisher));
 
   gather.activate();
 }
</pre>

**Comment by jcsp** [comment]
Already updated

**Comment by jcsp** [comment]
retest this please (jenkins)

**Pull request merged**
