### PR TITLE
DNM : osd: avoid multi set osd_op.outdata in tier pool

### PR DESCRIPTION
**Pull request by Abhishekvrshny**
http://tracker.ceph.com/issues/13036

### CODE REVIEW

**Comment by dachary** [comment]
> It may require commit 90e5f410ee35a614e1d49771226064d012d8b85e to be in hammer, as per my understanding.

**Comment by Abhishekvrshny** [comment]
@XinzeChi this commit does not apply cleanly, would you mind taking a look ?

http://jenkins.ceph.dachary.org/job/ceph/LABELS=centos-7&&x86_64/7703/console
<pre>
osd/ReplicatedPG.cc:11761:76: error: expected '}' at end of input
 void intrusive_ptr_release(ReplicatedPG::RepGather *repop) { repop->put(); }
                                                                            ^
osd/ReplicatedPG.cc:11761:76: error: expected '}' at end of input
</pre>

**Comment by XinzeChi** [comment]
@Abhishekvrshny , it conflicts with proxy write.
So I submit another patch for hammer?

**Comment by Abhishekvrshny** [comment]
@dachary : What do we suggest to @XinzeChi ?

**Comment by dachary** [comment]
@XinzeChi it would be great if you could adapt your patch to hammer. If the differences are such that it does not make sense to resolve the conflicts, a new patch is also fine. 

@Abhishekvrshny thanks for the reminder :-)

**Comment by XinzeChi** [comment]
@dachary , @Abhishekvrshny , I have fix this conflict at https://github.com/ceph/ceph/pull/6060

**Comment by tchaikov** [comment]
closing this pr, as #6060 supersedes it.

**Pull request closed without merging**
