### PR TITLE
rbd-mirror: do not auto-create peers in non-default namespaces

### PR DESCRIPTION
**Pull request by dillaman**
## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by tchaikov** [comment]
jenkins test make check

**Comment by trociny** [comment]
@dillaman Interestingly, testing this PR I started to observe failures [1] which I think are related to #32257 though I seemed not to observe them before.  It fails for rbd_mirror.sh 'no blacklists' test, though usually the root cause is rbd-mirror crashes like below [2]: there is a race when image replayer cancels the start, begins the shutdown process, but at that time it may still receive a notification from the replayer. Not sure why it became much easier to trigger this with the current patch (it might be just an coincidence), though it seems to observe for image replayers for images from a non-default namespace.

The fix could probably be just to ignore a replayer notification when the state is 'stopping'?

[1] http://pulpito.ceph.com/trociny-2019-12-23_09:31:31-rbd-wip-mgolub-testing-distro-basic-smithi/
[2]
```
/ceph/teuthology-archive/trociny-2019-12-23_09:31:31-rbd-wip-mgolub-testing-distro-basic-smithi/4628083/remote/smithi017/log/cluster1-client.mirror.1.34124.log.gz:

2019-12-23T10:09:21.353+0000 7f247fa34700 10 rbd::mirror::ImageReplayer: 0x556273a63500 [2/da93a258-adbd-4fe3-a32a-b2a2e76bc9f4] stop: on_finish=0x5562739e7cd0, manual=1, desc=
2019-12-23T10:09:21.353+0000 7f247fa34700 10 rbd::mirror::ImageReplayer: 0x556273a63500 [2/da93a258-adbd-4fe3-a32a-b2a2e76bc9f4] stop: canceling start
...

2019-12-23T10:09:21.357+0000 7f246ca0e700 10 rbd::mirror::ImageReplayer: 0x556273a63500 [2/da93a258-adbd-4fe3-a32a-b2a2e76bc9f4] handle_start_replay: r=0
2019-12-23T10:09:21.357+0000 7f246ca0e700 10 rbd::mirror::ImageReplayer: 0x556273a63500 [2/da93a258-adbd-4fe3-a32a-b2a2e76bc9f4] on_start_fail: r=-125, desc=
2019-12-23T10:09:21.357+0000 7f249425d700 10 rbd::mirror::ImageReplayer: 0x556273a63500 [2/da93a258-adbd-4fe3-a32a-b2a2e76bc9f4] operator(): start canceled
2019-12-23T10:09:21.357+0000 7f249425d700 10 rbd::mirror::ImageReplayer: 0x556273a63500 [2/da93a258-adbd-4fe3-a32a-b2a2e76bc9f4] set_state_description: r=-125, desc=
2019-12-23T10:09:21.357+0000 7f249425d700 15 rbd::mirror::ImageReplayer: 0x556273a63500 [2/da93a258-adbd-4fe3-a32a-b2a2e76bc9f4] update_mirror_image_status: force=0, state=--
2019-12-23T10:09:21.357+0000 7f249425d700 15 rbd::mirror::ImageReplayer: 0x556273a63500 [2/da93a258-adbd-4fe3-a32a-b2a2e76bc9f4] update_mirror_image_status: shut down in-progress: ignoring update
2019-12-23T10:09:21.357+0000 7f249425d700 10 rbd::mirror::ImageReplayer: 0x556273a63500 [2/da93a258-adbd-4fe3-a32a-b2a2e76bc9f4] shut_down: r=-125
2019-12-23T10:09:21.357+0000 7f249425d700 10 rbd::mirror::image_replayer::journal::Replayer: 0x556277b1dc00 shut_down: 
2019-12-23T10:09:21.357+0000 7f246ca0e700 20 rbd::mirror::Mirror: 0x556273a06980 register_cache: JournalPlayer/2/journal_data.2.15f3683145a4. min_size=131072 max_size=134217728 handler=0x556277866068
2019-12-23T10:09:21.357+0000 7f246ca0e700 10 rbd::mirror::image_replayer::journal::Replayer: 0x556277b1dc00 notify_status_updated: 
2019-12-23T10:09:21.357+0000 7f249425d700 10 rbd::mirror::image_replayer::journal::Replayer: 0x556277b1dc00 shut_down_local_journal_replay: 
2019-12-23T10:09:21.357+0000 7f249425d700 10 rbd::mirror::ImageReplayer: 0x556273a63500 [2/da93a258-adbd-4fe3-a32a-b2a2e76bc9f4] handle_replayer_notification: 
2019-12-23T10:09:21.357+0000 7f246ca0e700 10 rbd::mirror::image_replayer::journal::Replayer: 0x556277b1dc00 handle_shut_down_local_journal_replay: r=0
2019-12-23T10:09:21.357+0000 7f246ca0e700 10 rbd::mirror::image_replayer::journal::Replayer: 0x556277b1dc00 wait_for_event_replay: 
2019-12-23T10:09:21.357+0000 7f249425d700 -1 /build/ceph-15.0.0-8804-g5f248e6/src/tools/rbd_mirror/ImageReplayer.cc: In function 'void rbd::mirror::ImageReplayer<ImageCtxT>::handle_replayer_notification() [with ImageCtxT = librbd::ImageCtx]' thread 7f249425d700 time 2019-12-23T10:09:21.359213+0000
/build/ceph-15.0.0-8804-g5f248e6/src/tools/rbd_mirror/ImageReplayer.cc: 1062: FAILED ceph_assert(m_state == STATE_REPLAYING)

 ceph version 15.0.0-8804-g5f248e6 (5f248e6f4079b29f44c6cb9f87fc3ca9d888bd0c) octopus (dev)
 1: (ceph::__ceph_assert_fail(char const*, char const*, int, char const*)+0x152) [0x7f24998e94cc]
 2: (()+0x2916a4) [0x7f24998e96a4]
 3: (rbd::mirror::ImageReplayer<librbd::ImageCtx>::handle_replayer_notification()+0x73b) [0x55627189878b]
 4: (Context::complete(int)+0x9) [0x55627181ccf9]
 5: (rbd::mirror::image_replayer::journal::Replayer<librbd::ImageCtx>::C_TrackedOp::finish(int)+0xe) [0x5562718e708e]
 6: (ThreadPool::PointerWQ<Context>::_void_process(void*, ThreadPool::TPHandle&)+0x148) [0x55627183bdb8]
 7: (ThreadPool::worker(ThreadPool::WorkThread*)+0xdab) [0x7f24999d01db]
 8: (ThreadPool::WorkThread::entry()+0x11) [0x7f24999d09a1]
 9: (()+0x76db) [0x7f24994406db]
 10: (clone()+0x3f) [0x7f249841e88f]
```

**Comment by dillaman** [comment]
I have a couple of fixes (that one included) tacked on your the end of [1] 

[1] https://github.com/ceph/ceph/pull/32399

**Comment by trociny** [comment]
Ah, indeed. Thanks.

**Pull request merged**
