### PR TITLE
rbd-mirror: rename per-image replication perf counters

### PR DESCRIPTION
**Pull request by trociny**
The same names for aggregated and per image counters cause
problems for prometheus.

Fixes: https://tracker.ceph.com/issues/43004
Signed-off-by: Mykola Golub <mgolub@suse.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by trociny** [comment]
The same counter names for aggregated and per image stats make the prometheus module generate metrics with duplicate HELP and TYPE lines, something like this:
```
# HELP ceph_rbd_mirror_replay_latency_count Replay latency Count
# TYPE ceph_rbd_mirror_replay_latency_count counter
ceph_rbd_mirror_replay_latency_count{ceph_daemon="rbd-mirror.222864335"} 175509171.0
...
# HELP ceph_rbd_mirror_replay_latency_count Replay latency Count
# TYPE ceph_rbd_mirror_replay_latency_count counter
ceph_rbd_mirror_replay_latency_count{ceph_daemon="rbd-mirror.222864335",pool="cephrescue",namespace="",image="vm-138-disk-1"} 15473541.0
```
This leads to a parsing error on prometheus side.

Instead of renaming I could modify `_perfpath_to_path_labels` [1] to generate something like this for aggregated stats:
```
ceph_rbd_mirror_replay_latency_count{ceph_daemon="rbd-mirror.222864335",pool="*",namespace="*",image="*"} 15473541.0
```
But I suppose it would be harder for users to work with such format on the prometheus side.

[1] https://github.com/ceph/ceph/blob/master/src/pybind/mgr/mgr_module.py#L813

**Comment by dillaman** [comment]
I wonder if it would be better to rename the per-image stats instead -- like `ceph_rbd_mirror_image_replay_latency_count`?

**Comment by trociny** [comment]
@dillaman updated

**Comment by jan--f** [comment]
> ```
> # HELP ceph_rbd_mirror_replay_latency_count Replay latency Count
> # TYPE ceph_rbd_mirror_replay_latency_count counter
> ceph_rbd_mirror_replay_latency_count{ceph_daemon="rbd-mirror.222864335"} 175509171.0
> ...
> # HELP ceph_rbd_mirror_replay_latency_count Replay latency Count
> # TYPE ceph_rbd_mirror_replay_latency_count counter
> ceph_rbd_mirror_replay_latency_count{ceph_daemon="rbd-mirror.222864335",pool="cephrescue",namespace="",image="vm-138-disk-1"} 15473541.0
> ```
> ceph_rbd_mirror_replay_latency_count{ceph_daemon="rbd-mirror.222864335",pool="*",namespace="*",image="*"} 15473541.0
> ```
> 
> But I suppose it would be harder for users to work with such format on the prometheus side.

To clarify: In the metric listing above, is the first instance (with a single label) the aggregation of the later ones?

In this case the _prometheus-way_ would be to not export the aggregated metric and leave that to a prometheus query. See https://prometheus.io/docs/instrumenting/writing_exporters/#labels

**Comment by trociny** [comment]
> To clarify: In the metric listing above, is the first instance (with a single label) the aggregation of the later ones?

Basically yes, though it is done on the rbd-mirror side, so aggregated counters may include stats from images that has already been removed or migrated to another instance, so you do not necessary see the same numbers when doing aggregation on the prometheus side.

> In this case the prometheus-way would be to not export the aggregated metric and leave that to a prometheus query. See https://prometheus.io/docs/instrumenting/writing_exporters/#labels

We renamed the per-image metrics to `ceph_rbd_mirror_image_replay...`, so now there should not be problems described in the doc.

The aggregated counters seem redundant in prometheus case, which can do aggregation on its side. I suppose we could add some handler to mgr/prometheus module to skip those counters coming from the rbd-monitor, but I would not like to do this. It does not look like a big harm to have them too. Also, being collected on the rbd-mirror side they may provide a little different result, especially if the images are being remove/added or migrating from one rbd-mirro instance to another. So I vote to leave it as it is now, but I don't mind much to change if people still do not like this.

**Comment by trociny** [comment]
I have tested it on prometheus-2.14.0. It seems to work.

prometheus

**Comment by trociny** [comment]
Also, note, we might consider (as a separate PR) to have different priorities for aggregated perf conters and per-image perf counters, so a user could configure e.g. the rbd-mirror to send only aggregated stats to the mgr, or vice versa.

**Comment by trociny** [comment]
> Also, note, we might consider (as a separate PR) to have different priorities for aggregated perf conters and per-image perf counters, so a user could configure e.g. the rbd-mirror to send only aggregated stats to the mgr, or vice versa.

I have added a second commit to show what I meant. I will remove it if it does not look appealing.

**Comment by jan--f** [comment]
> I have added a second commit to show what I meant. I will remove it if it does not look appealing.

LGTM

**Pull request merged**
