### PR TITLE
common: Introduce set_max to Option

### PR DESCRIPTION
**Pull request by shinobu-x**
Signed-off-by: Shinobu Kinjo <shinobu@redhat.com>

### CODE REVIEW

**Comment by shinobu-x** [comment]
This idea comes with f284bbb0593eafc25013c01c8aa7b8bdfc39d906.
In case that, we are really interested in **maximum size** of the value, `set_max` is the option to use.

**Comment by shinobu-x** [comment]
test this please

**Comment by shinobu-x** [comment]
test this please

**Comment by liewegas** [comment]
I think any place we set a max we can also set a min at the same time (e.g., 0)

**Pull request closed without merging**
