### PR TITLE
[qa]: Removing distros othern than rhel 7.x and rhel 8.x

### PR DESCRIPTION
**Pull request by racpatel**
Signed-off-by: Rachanaben Patel <racpatel@redhat.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by smithfarm** [comment]
@racpatel What is the issue that this change is addressing? Just cleanup?

**Comment by smithfarm** [comment]
Oh, now I see this is targeting the `rh-nautilus` branch.

Just out of curiosity, what is the rationale for doing RH downstream work in the upstream repo? (At SUSE, we are doing downstream work in our `SUSE/ceph` fork...)

**Comment by liewegas** [comment]
i'm all for cleaning out the cruft in master (e.g. 6.x and the old fedoras).

for rh-nautilus, if you just want to restrict what you test on, you just need to adjust the symlinks in qa/distros/supported*

**Comment by vasukulkarni** [comment]
@racpatel lets try what sage is recommending but changing qa distro links in supported folder.

**Pull request merged**
