### PR TITLE
Update rbd-snapshot.rst

### PR DESCRIPTION
**Pull request by xiewen**
doc: snapshot misspelled as shapshot

### CODE REVIEW

**Comment by theanalyst** [comment]
Missing a signed-off-by line in commit message

**Comment by dachary** [comment]
jenkins test this please (no logs)

**Comment by theanalyst** [comment]
@xiewen can you add a signed-Off-By to your commit as mentioned in https://github.com/ceph/ceph/blob/master/SubmittingPatches.rst#1-sign-your-work

**Comment by tchaikov** [comment]
@xiewen ping?

**Comment by tchaikov** [comment]
closing, please reopen this once you are ready to continue working on this issue.

**Pull request closed without merging**
