### PR TITLE
luminous: rgw: orphans find perf improvments

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/39180

### CODE REVIEW

**Comment by smithfarm** [comment]
@theanalyst FYI

**Comment by cbodley** [comment]
jenkins test make check

**Comment by smithfarm** [comment]
```
OSError: [Errno 13] Permission denied: '/usr/lib/python2.7/site-packages/wheel'
You are using pip version 8.1.2, however version 19.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

**Comment by smithfarm** [comment]
jenkins re-test this please

**Comment by yuriw** [comment]
[wip-yuri5-testing-2019-06-11-0036-luminous](https://trello.com/c/dOCwVIFT/636-wip-yuri5-testing-2019-06-11-0036-luminous)

**Comment by yuriw** [comment]
[vv](https://trello.com/c/3nRScc3r/637-vv)

**Pull request merged**
