### PR TITLE
pybind/rbd: add list_children3 and restore list_children2 compatibility

### PR DESCRIPTION
**Pull request by trociny**
Fixes: http://tracker.ceph.com/issues/37729
Signed-off-by: Mykola Golub <mgolub@suse.com>

- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by neha-ojha** [comment]
This doesn't seem to fix the failures tracked in https://tracker.ceph.com/issues/37729

branch: https://github.com/neha-ojha/ceph/commits/wip-test-25742
http://pulpito.ceph.com/nojha-2019-01-04_18:43:21-upgrade:mimic-x:stress-split-master-distro-basic-smithi/

**Comment by trociny** [comment]
@neha-ojha It looks like install.upgrade task in your run was using master (645e465f6e479b00ce6cb202a0a64eef90c665cd) not wip-test-25742 (c8c485742e2661aee6ea4f8b95c8373e4783f2e8):
```
2019-01-04T20:18:41.392 INFO:teuthology.run_tasks:Running task install.upgrade...
2019-01-04T20:18:41.402 INFO:teuthology.task.install:project ceph config {'client.0': None, 'osd.4': None} overrides {'sha1': '645e465f6e479b00ce6cb202a0a64eef90c665cd'}
...
2019-01-04T20:18:41.617 DEBUG:teuthology.packaging:Querying https://shaman.ceph.com/api/search?status=ready&project=ceph&flavor=default&distros=centos%2F7%2Fx86_64&sha1=645e465f6e479b00ce6cb202a0a64eef90c665cd
2019-01-04T20:18:41.775 INFO:teuthology.task.install:Ceph rpm upgrade from 13.2.4-0.el7 to 14.0.1-2194.g645e465
```

**Comment by trociny** [comment]
Ok, I just had an impression (now not sure why) that adding a new key to a dict was considered as API breakage. On the other hand, keeping it as it is could be a little awkward: list_children2 C/C++ functions do not correspond to list_chilren2 Python function.

**Comment by neha-ojha** [comment]
@trociny you are right, http://pulpito.ceph.com/nojha-2019-01-06_19:36:48-upgrade:mimic-x:stress-split-wip-test-25742-distro-basic-smithi/ looks much better.

**Comment by trociny** [comment]
@dillaman I created a new PR [1] that just filters out unknown keys in the test. Fill free to chose a PR you like more and close another.

[1] https://github.com/ceph/ceph/pull/25832

**Comment by dillaman** [comment]
Closing in favor of test change.

**Pull request closed without merging**
