### PR TITLE
pacific: os/bluestore: dump bluefs alloc unit sizes with perf counters dump

### PR DESCRIPTION
**Pull request by YiteGu**
Signed-off-by: Igor Fedotov <igor.fedotov@croit.io>
(cherry picked from commit d17986306d23cfbf410434aaf789546707dd7dc9)

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [x] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Comment by YiteGu** [comment]
jenkins test make check

**Comment by YiteGu** [comment]
hi, @ifed01 I don't know why there are segmentation fault at ceph::common::PerfCounters::set :(
```
*** Caught signal (Segmentation fault) **
 in thread 7f23edcec9c0 thread_name:unittest_deferr
 ceph version Development (no_version) pacific (stable)
 1: /home/jenkins-build/build/workspace/ceph-pull-requests/build/bin/unittest_deferred(+0xed4075) [0x55f7f3491075]
 2: /lib/x86_64-linux-gnu/libc.so.6(+0x42520) [0x7f23edefd520]
 3: (ceph::common::PerfCounters::set(int, unsigned long)+0x2a) [0x7f23f0118ea6]
 4: (BlueFS::_init_alloc()+0x1a9) [0x55f7f33ffebb]
 5: (BlueFS::mount()+0x396) [0x55f7f3402896]
 6: (BlueStore::_open_bluefs(bool, bool)+0x643) [0x55f7f3231f67]
 7: (BlueStore::_prepare_db_environment(bool, bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*)+0x8dd) [0x55f7f3233c4b]
 8: (BlueStore::_open_db(bool, bool, bool)+0xf1) [0x55f7f3235251]
 9: (BlueStore::_open_db_and_around(bool, bool)+0x610) [0x55f7f3232e3a]
 10: (BlueStore::_fsck(BlueStore::FSCKDepth, bool)+0x1a2) [0x55f7f324d9d4]
 11: (BlueStore::fsck(bool)+0x3a) [0x55f7f32cc9c2]
 12: (BlueStore::mkfs()+0x205f) [0x55f7f323bd8f]
 13: (create_deferred_and_terminate()+0x3a8) [0x55f7f30adb21]
 14: main()
 15: /lib/x86_64-linux-gnu/libc.so.6(+0x29d90) [0x7f23edee4d90]
 16: __libc_start_main()
 17: _start()
2023-11-17T10:26:14.691+0000 7f23edcec9c0 -1 *** Caught signal (Segmentation fault) **
```

**Comment by ifed01** [comment]
> hi, @ifed01 I don't know why there are segmentation fault at ceph::common::PerfCounters::set :(
> 
> ```
> *** Caught signal (Segmentation fault) **
>  in thread 7f23edcec9c0 thread_name:unittest_deferr
>  ceph version Development (no_version) pacific (stable)
>  1: /home/jenkins-build/build/workspace/ceph-pull-requests/build/bin/unittest_deferred(+0xed4075) [0x55f7f3491075]
>  2: /lib/x86_64-linux-gnu/libc.so.6(+0x42520) [0x7f23edefd520]
>  3: (ceph::common::PerfCounters::set(int, unsigned long)+0x2a) [0x7f23f0118ea6]
>  4: (BlueFS::_init_alloc()+0x1a9) [0x55f7f33ffebb]
>  5: (BlueFS::mount()+0x396) [0x55f7f3402896]
>  6: (BlueStore::_open_bluefs(bool, bool)+0x643) [0x55f7f3231f67]
>  7: (BlueStore::_prepare_db_environment(bool, bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*)+0x8dd) [0x55f7f3233c4b]
>  8: (BlueStore::_open_db(bool, bool, bool)+0xf1) [0x55f7f3235251]
>  9: (BlueStore::_open_db_and_around(bool, bool)+0x610) [0x55f7f3232e3a]
>  10: (BlueStore::_fsck(BlueStore::FSCKDepth, bool)+0x1a2) [0x55f7f324d9d4]
>  11: (BlueStore::fsck(bool)+0x3a) [0x55f7f32cc9c2]
>  12: (BlueStore::mkfs()+0x205f) [0x55f7f323bd8f]
>  13: (create_deferred_and_terminate()+0x3a8) [0x55f7f30adb21]
>  14: main()
>  15: /lib/x86_64-linux-gnu/libc.so.6(+0x29d90) [0x7f23edee4d90]
>  16: __libc_start_main()
>  17: _start()
> 2023-11-17T10:26:14.691+0000 7f23edcec9c0 -1 *** Caught signal (Segmentation fault) **
> ```

This is due to BlueFS::mount() calls init_logger() and init_alloc in wrong order. init_alloc() call must follow init_logger() one.

**Comment by YiteGu** [comment]
> > hi, @ifed01 I don't know why there are segmentation fault at ceph::common::PerfCounters::set :(
> > ```
> > *** Caught signal (Segmentation fault) **
> >  in thread 7f23edcec9c0 thread_name:unittest_deferr
> >  ceph version Development (no_version) pacific (stable)
> >  1: /home/jenkins-build/build/workspace/ceph-pull-requests/build/bin/unittest_deferred(+0xed4075) [0x55f7f3491075]
> >  2: /lib/x86_64-linux-gnu/libc.so.6(+0x42520) [0x7f23edefd520]
> >  3: (ceph::common::PerfCounters::set(int, unsigned long)+0x2a) [0x7f23f0118ea6]
> >  4: (BlueFS::_init_alloc()+0x1a9) [0x55f7f33ffebb]
> >  5: (BlueFS::mount()+0x396) [0x55f7f3402896]
> >  6: (BlueStore::_open_bluefs(bool, bool)+0x643) [0x55f7f3231f67]
> >  7: (BlueStore::_prepare_db_environment(bool, bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*)+0x8dd) [0x55f7f3233c4b]
> >  8: (BlueStore::_open_db(bool, bool, bool)+0xf1) [0x55f7f3235251]
> >  9: (BlueStore::_open_db_and_around(bool, bool)+0x610) [0x55f7f3232e3a]
> >  10: (BlueStore::_fsck(BlueStore::FSCKDepth, bool)+0x1a2) [0x55f7f324d9d4]
> >  11: (BlueStore::fsck(bool)+0x3a) [0x55f7f32cc9c2]
> >  12: (BlueStore::mkfs()+0x205f) [0x55f7f323bd8f]
> >  13: (create_deferred_and_terminate()+0x3a8) [0x55f7f30adb21]
> >  14: main()
> >  15: /lib/x86_64-linux-gnu/libc.so.6(+0x29d90) [0x7f23edee4d90]
> >  16: __libc_start_main()
> >  17: _start()
> > 2023-11-17T10:26:14.691+0000 7f23edcec9c0 -1 *** Caught signal (Segmentation fault) **
> > ```
> 
> This is due to BlueFS::mount() calls init_logger() and init_alloc in wrong order. init_alloc() call must follow init_logger() one.

I got it :)

**Review by aclamk — APPROVED** [review]

**Comment by YiteGu** [comment]
https://github.com/ceph/ceph/pull/54434 already include this backport

**Pull request closed without merging**
