### PR TITLE
 cephadm: ignore UnicodeDecodeError when reading sysctl 

### PR DESCRIPTION
**Pull request by p-se**
For some unknown reason, on my machine the `sunrpc.transports` value is
broken and returns giberish. While this definitely shouldn't happen, it
is still possible to prevent `cephadm` from stopping to work. Restart
fixed the issue for me.

```
user@home ~ » sudo sysctl -a | rg sunrpc.transports
sysctl: reading key "kernel.spl.hostid"
sunrpc.transports = sb#R�
user@home ~ » sudo sysctl -a | rg sunrpc.transports
sysctl: reading key "kernel.spl.hostid"
sunrpc.transports = £»M�
user@home ~ » sudo sysctl -a | rg sunrpc.transports
sysctl: reading key "kernel.spl.hostid"
sunrpc.transports = ¨>�
user@home ~ » sudo sysctl -a | rg sunrpc.transports
sysctl: reading key "kernel.spl.hostid"
sunrpc.transports = �í�
user@home ~ » sudo sysctl -a | rg sunrpc.transports
sysctl: reading key "kernel.spl.hostid"
sunrpc.transports = V¡�
user@home ~ » sudo sysctl -a | rg sunrpc.transports
sysctl: reading key "kernel.spl.hostid"
sunrpc.transports = ëCõ�
user@home ~ » sudo sysctl -a | rg sunrpc.transports
sysctl: reading key "kernel.spl.hostid"
sunrpc.transports = #^ÿ~
user@home ~ »
```

Signed-off-by: Patrick Seidensal <pseidensal@suse.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by sebastian-philipp** [comment]
thing is, no one is looking into any log files as long as things work. My thoughts.

`gather-facts` should probably not fail silently, if we try to read data that we actually care about. like

https://github.com/ceph/ceph/blob/90f908a84dd1dd4fdea3426d890c89f6e6b639a0/src/pybind/mgr/cephadm/serve.py#L529

hm. 

https://github.com/ceph/ceph/blob/90f908a84dd1dd4fdea3426d890c89f6e6b639a0/src/pybind/mgr/cephadm/serve.py#L165-L169

plus

https://github.com/ceph/ceph/blob/90f908a84dd1dd4fdea3426d890c89f6e6b639a0/src/pybind/mgr/cephadm/serve.py#L202-L208

means you'll get a `CEPHADM_REFRESH_FAILED` warning if gather-facts fails.

**Comment by p-se** [comment]
> Maybe we should introduce a special warning for gather-facts to let users disable this specific warning?

As I see it, there's something wrong with the host when this error occurs, like it was on mine. I've no ECC memory and the machine ran for nearly two weeks without reboot.

So, we might want to let it fail at this point and enable the user to try to continue anyways (like with a `--force` switch), as restarting a host (which was necessary in my case) might not be a viable solution to a customer. On the other hand, I'm not sure how likely it is that a server with ECC memory and whatnot actually has this kind of issue, but who knows. Maybe we'll want to have that option for just that (unlikely?) case?

I would then simply let it fail like it does now but add a message on how to (try to) ignore that error. Maybe a switch or environment variable. Which would only work if whatever data was read isn't used by cephadm. What I like about this approach is that the user would
1. always see an error first,
2. would get the chance to ignore it, which might work or
3. would be told that this kind of error cannot be ignored because the value which was failed to read is used by cephadm.

How about that?

**Comment by p-se** [comment]
I should add that I've no strong opinion on that issue. It might even be good to have that error raised and not ignored at all.

**Comment by sebastian-philipp** [comment]
I'd like to see gather-facts fail for important data. I'm ok with letting it fail here as well.

**Comment by p-se** [comment]
Closing for the time being to see if this is actually an error that is to be met in the wild.

**Pull request closed without merging**
