### PR TITLE
mon: reset lease_timeout_event when handling 'begin' message

### PR DESCRIPTION
**Pull request by Sandy4999**
Give Peons a bit more time to wait for Paxos updating finished

Signed-off-by: Sangdi Xu xu.sangdi@h3c.com

### CODE REVIEW

**Comment by Sandy4999** [comment]
The issue we encountered is that under heavy workloads, a Peon periodically calls for new election which is caused by its `lease_timeout_event` during Paxos updating phase. It seems there is no sense to keep this event as the Peon has already cancelled its lease, and the Leader has cancelled `lease_renew_event` as well (maybe right before it would otherwise be triggered). However, we do need some `timeout_event` for Peons in case the Leader falls down after sending out `begin` message. Thus, we may try to reset the `lease_timeout_event` to give Peons some extra time to wait for a new lease. Do you have any other suggestions @jecluis ? Thank you!

**Comment by liewegas** [comment]
@jecluis @tchaikov ?

**Comment by tchaikov** [comment]
@Sandy4999 IIUC, you are 

1. letting the peon be more patient when waiting for the lease message from leader, i.e. waiting the pending proposal to be committed by leader. as it might take longer than `mon_lease*mon_lease_ack_timeout_factor` to finish this process.
1. reusing the lease_timeout for the peon-side begin_accept_commit_timeout

> It seems there is no sense to keep this event as the Peon has already cancelled its lease

it depends on how we look at the lease mechanism. i agree that both the leader and the peons have reset the `lease_expire`, so none of the monitors is readable when they are updating themselves. but imho, the peons are always expecting a lease before the timeout. it could be a lease for existing proposal **or** a lease for the proposal that will be committed. in this case, it's a lease for the pending proposal. that's why it could take longer to accept, refresh and commit the proposal. i did find that in some large cluster, the `OSDMonitor::check_subs()`could take quite a while to send the updated osdmap to its subscribers.

maybe we might need to differentiate the timeout for a lease-renew from the timeout for the leader's `OP_COMMIT` message after `OP_BEGIN` is received? but i have no strong objection to repurposing the `lease_timeout_event` and `reset_lease_timeout()` for this.

@jecluis what do you think?

**Comment by Sandy4999** [comment]
@tchaikov  yes that's exactly what I mean. In our experimenting environment, most of time everything goes well. However, when workloads become heavier, the monitor quorum falls unstable (periodically re-election). This situation can be relieved by just increasing the `mon_lease`, but I believe it's still a good thing to make Peons a bit more patient.

**Comment by songbaisen** [comment]
@Sandy4999  We have also meet the same problem twice.The first time is because our network problem we found there are a lot of loss packet.The second time is because the monitor host load average is very high.There are a lot of compute task in the monitor host.But the computa task not generate by ceph, it is other software affect ceph.

**Comment by athanatos** [comment]
@jecluis @tchaikov It sounds like this may not be the right direction?

**Comment by liewegas** [comment]
@jecluis ?

**Comment by dachary** [comment]
jenkins test this please (no logs)

**Comment by dachary** [comment]
@jecluis feel free to re-open if you think this is going in the right direction

**Comment by jecluis** [comment]
I think this is an early attempt at accomplishing the same as #9450. I think it can remain closed.

**Pull request closed without merging**
