### PR TITLE
bug fix 

### PR DESCRIPTION
**Pull request by majianpeng**

### CODE REVIEW

**Comment by majianpeng** [comment]
@liewegas . By your suggestion, change the code. For replicated pool,  1 <= min_size <= size; For ec pool, k <= min_size <= size(k+m).

**Comment by liewegas** [comment]
Reviewed-by:

**Comment by athanatos** [comment]
There are tests in src/test which test this kind of checking.  You need to add this in so it is tested in make check.  You can re-add needs-qa once that is done.

**Comment by majianpeng** [comment]
@athanatos . Updated but  i don't have permisson to add  needs-qa.

**Pull request merged**
