### PR TITLE
[WIP] luminous user admin

### PR DESCRIPTION
**Pull request by mattbenjamin**
Luminous backport for librgw_user_admin.so

- [ ] References tracker ticket
- [ x] Updates documentation if necessary
- [x ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by smithfarm** [comment]
@mattbenjamin @epuertat @LenzGr Do we care whether this is backported to mimic or not?

**Comment by LenzGr** [comment]
> Do we care whether this is backported to mimic or not?

At this point, I think this would be premature. To my knowledge, the dashboard does not make use of this functionality yet. Unless there are other reasons that would justify backporting this?

**Comment by smithfarm** [comment]
The reason I ask is: this is a luminous backport PR but there is no tracker issue for it. As a result, I don't know whether there's a companion mimic backport PR?

(In other words, I'm concerned this could get merged into luminous and then we forget to backport it to mimic.)

**Comment by epuertat** [comment]
@smithfarm @LenzGr I was convinced that master's Dashboard was already using `librgw_admin_user` instead of the API key (my ignorance comes from my lately living in this 3-month old version of master), and I asked @mattbenjamin if we could have this (and the corresponding python bindings #21539 ) in Luminous.

**Comment by LenzGr** [comment]
> I was convinced that master's Dashboard was already using `librgw_admin_user` instead of the API key

@votdev - can you confirm this is the case? If yes, then it would of course make sense to get this backported/merged.

**Comment by LenzGr** [comment]
I don't think there is a point in still merging this into luminous at this point, but the functionality itself has merit and would be a nice dashboard usability improvement.

@mattbenjamin - if these changes are in master already, I assume this PR can be closed?

**Comment by rjfd** [comment]
Closing this PR as ceph-dashboard uses API keys to manage RGW in luminous

**Pull request closed without merging**
