### PR TITLE
cmake: require libpmem 1.7 and cleanups

### PR DESCRIPTION
**Pull request by tchaikov**
## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by tchaikov** [comment]
test failure should be addressed by #40579

**Comment by tchaikov** [comment]
jenkins test make check

**Review by cyx1231st — APPROVED** [review]
IIUC specify version in find_package() looks reasonable to me.

**Comment by tchaikov** [comment]
- https://pulpito.ceph.com/kchai-2021-04-05_10:46:36-rados-wip-kefu-testing-2021-04-05-1650-distro-basic-gibba/
- https://pulpito.ceph.com/kchai-2021-04-06_02:58:54-rados-wip-kefu-testing-2021-04-05-1650-distro-basic-smithi/
- https://pulpito.ceph.com/kchai-2021-04-06_05:17:42-rados-wip-kefu-testing-2021-04-06-1109-distro-basic-smithi/
- https://pulpito.ceph.com/kchai-2021-04-06_06:26:47-rados-wip-kefu-testing-2021-04-06-1117-distro-basic-smithi/

**Pull request merged**
