### PR TITLE
test: librbd features test case should only disable active features

### PR DESCRIPTION
**Pull request by dillaman**
Fixes: http://tracker.ceph.com/issues/16898
Signed-off-by: Jason Dillaman dillaman@redhat.com

### CODE REVIEW

**Comment by trociny** [comment]
@dillaman Testing this on teuthology, unfortunately it does not work:

http://qa-proxy.ceph.com/teuthology/trociny-2016-09-13_13:47:46-upgrade-jewel---basic-vps/413558/teuthology.log

I have addded some debugging and increased `debug rbd` to have more details:
```
2016-09-13T14:11:10.263 INFO:tasks.workunit.client.0.vpm069.stdout:[ RUN      ] TestLibRBD.UpdateFeatures
2016-09-13T14:11:10.264 INFO:tasks.workunit.client.0.vpm069.stdout:using new format!
2016-09-13T14:11:10.330 INFO:tasks.workunit.client.0.vpm069.stdout:XXXMG: features=13
2016-09-13T14:11:10.330 INFO:tasks.workunit.client.0.vpm069.stdout:XXXMG: disable_features=12
2016-09-13T14:11:10.330 INFO:tasks.workunit.client.0.vpm069.stdout:XXXMG: image.update_features(12, false)
2016-09-13T14:11:10.357 INFO:tasks.workunit.client.0.vpm069.stdout:test/librbd/test_librbd.cc:3036: Failure
2016-09-13T14:11:10.357 INFO:tasks.workunit.client.0.vpm069.stdout:Value of: image.update_features(disable_features, false)
2016-09-13T14:11:10.357 INFO:tasks.workunit.client.0.vpm069.stdout:  Actual: -22
2016-09-13T14:11:10.358 INFO:tasks.workunit.client.0.vpm069.stdout:Expected: 0
2016-09-13T14:11:10.379 INFO:tasks.workunit.client.0.vpm069.stdout:[  FAILED  ] TestLibRBD.UpdateFeatures (116 ms)
```

So, it failed for disable_features=12. In client logs, there is 'update requires at least one feature' error but this was from the previous test (expected result), while the error for this failed case is generated by cls_client::set_features:
```
2016-09-13 14:11:10.356179 7f83dde21840 10 librbd: update_features: features=1, mask=76
2016-09-13 14:11:10.358015 7f83dde21840 -1 librbd: failed to update features: (22) Invalid argument
```
I suppose because jewel library adds RBD_FEATURE_JOURNALING to features_mask, which is unknown on infernalis.

**Comment by dillaman** [comment]
@trociny Definitely related to the mask -- any idea why we didn't see this before? The "cls_rbd" set_features function should mask the incoming mask with its version of RBD_FEATURES_ALL at the start to avoid this issue.

**Comment by dillaman** [comment]
@trociny Whoops -- didn't look close enough.  I thought this was your dynamic features PR. Thanks!

**Comment by trociny** [comment]
@dillaman I don't have a good idea why we didn't see this before -- not sure when it was noticed the first time. I see the qa test was added in Nov 2015, and then it worked because the default features did not include exclusive lock. In Feb 2016 the default features was changed, and there were also related changes in update_features, so I expect it should have started to fail since then.

**Comment by dillaman** [comment]
Requires PR #11155 to be merged to the jewel branch

**Comment by trociny** [comment]
The test passes now: http://pulpito.ceph.com/trociny-2016-11-02_05:50:21-upgrade-jewel---basic-vps/

**Pull request merged**
