### PR TITLE
ceph-volume: fix TestMigrate tests

### PR DESCRIPTION
**Pull request by guits**
ae5ef432845 broke some unit tests.
This commit fixes that.

### CODE REVIEW

**Comment by guits** [comment]
jenkins test ceph-volume tox

**Comment by guits** [comment]
jenkins test ceph-volume tox

**Comment by guits** [comment]
@ifed01 FYI

**Review by adk3798 — APPROVED** [review]

**Comment by guits** [comment]
jenkins test api

**Pull request merged**
