### PR TITLE
osd: fix missing adjacent snaps when handling manifest object

### PR DESCRIPTION
**Pull request by myoungwon**
The manifest object needs adjacent clones to increment/decrement
refcount when acessing the object. So, recover the clones first
if there are missing clones.

Fixes: https://tracker.ceph.com/issues/49427

Signed-off-by: Myoungwon Oh <myoungwon.oh@samsung.com>

### CODE REVIEW

**Comment by myoungwon** [comment]
@athanatos  hmm.. What do you think?

**Comment by athanatos** [comment]
This might work, but I'm going to have to go through this carefully.  I will note, however, that this is relatively rare and failing to release the top level reference is actually safe -- maybe we just let the reference leak in this case?

**Comment by athanatos** [comment]
I think this should work.

**Review by athanatos — APPROVED** [review]
LGTM pending a test run (also, remove the WIP:)

**Comment by tchaikov** [comment]
- https://pulpito.ceph.com/kchai-2021-03-09_12:22:01-rados-wip-kefu-testing-2021-03-09-1847-distro-basic-smithi/
- https://pulpito.ceph.com/kchai-2021-03-10_06:55:19-rados-wip-kefu-testing-2021-03-09-1847-distro-basic-gibba/

the crash of 

- https://pulpito.ceph.com/kchai-2021-03-10_06:55:19-rados-wip-kefu-testing-2021-03-09-1847-distro-basic-gibba/5952985/
- https://pulpito.ceph.com/kchai-2021-03-10_06:55:19-rados-wip-kefu-testing-2021-03-09-1847-distro-basic-gibba/5952993/

are new ones. i need to rerun the tests without this change.

**Comment by tchaikov** [comment]
the failures are tracked by https://tracker.ceph.com/issues/49726

**Pull request merged**
