### PR TITLE
rgw: Fix typo in comment

### PR DESCRIPTION
**Pull request by simransinghal**
Replace "dont" with "don't". "Dont" is not same as "Do not" or "Don't".

Signed-off-by: Simran Singhal <singhalsimran0@gmail.com>

### CODE REVIEW

**Comment by wjwithagen** [comment]
@simransinghal 
Typos in comments are only fixed if there is also a code fix at the same location.
And then I forgo the very long discussion we had about 1 year ago about all kind of colloquialisms, UK vs US english, and other languages style prefferences. 
So might I polittely suggest to close this.

**Comment by ArushiSinghal** [comment]
@wjwithagen Thanks for the explanation.

**Comment by joscollin** [comment]
@wjwithagen May be this one. https://github.com/ceph/ceph/pull/16705.  :-)

But `dont` is incorrect I think.

**Comment by simransinghal** [comment]
@wjwithagen @joscollin 
Yes, "dont" is not a dictionary word.
And even Linux kernel style does not prefer such kind of mistakes. So it's good if we change this.

**Pull request merged**
