### PR TITLE
nautilus: rgw: throw error NoSuchBucket when bucket not exists

### PR DESCRIPTION
**Pull request by Huber-ming**
throw error ERR_NO_SUCH_BUCKET when bucket not exists
fix: https://tracker.ceph.com/issues/50107
Signed-off-by: Huber-ming <zhangsm01@inspur.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by tchaikov** [comment]
jenkins test make check

**Comment by tchaikov** [comment]
jenkins test make check

**Review by mattbenjamin — APPROVED** [review]
This is the general behavior for related cases, so it seems correct.

**Comment by ivancich** [comment]
@Huber-ming Does this need a tracker for backports? It seems to be a bug fix.

**Comment by Huber-ming** [comment]
> @Huber-ming Does this need a tracker for backports? It seems to be a bug fix.

@ivancich  https://tracker.ceph.com/issues/50107

**Comment by smithfarm** [comment]
@mattbenjamin @ivancich @Huber-ming This does not explain why it is targeting nautilus. Do you know how this bug got fixed in Octopus and later?

**Comment by smithfarm** [comment]
> This does not explain why it is targeting nautilus. Do you know how this bug got fixed in Octopus and later?

Nevermind, I figured it out:

https://tracker.ceph.com/issues/38420 was missing nautilus backport. The bug has been fixed (since Octopus) by #26569 which I just backported to nautilus here: 

https://github.com/ceph/ceph/pull/40668

This PR is superseded by

**Pull request closed without merging**
