### PR TITLE
mgr/dashboard: Splitting tenant$user when creating rgw user

### PR DESCRIPTION
**Pull request by nizamial09**
Splits the Username field into Tenant and User ID. User can specify tenant and user_id seperately and then click on the generate icon the Username field to generate the username.

Fixes: https://tracker.ceph.com/issues/47378
Signed-off-by: Nizamudeen A <nia@redhat.com>
**BEFORE**
rgw_tenant

**AFTER**
Screencast 2021-02-17 at 13 28 - Ceph

## Checklist
- [x] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Review by avanthakkar — APPROVED** [review]
Tested it locally & it LGTM! Just one thing I wanted to point out for the current functionality that shouldn't we have `Username` field enabled & as required field instead?(removing user_id as required field and user can still click generate icon if both tenant & user_id are specified). So that the previous functionality of specifying username as `tenant$user_id` still remains. 
Any thoughts on this @epuertat @alfonsomthd @votdev @s0nea ?

**Comment by nizamial09** [comment]
jenkins test make check

**Review by epuertat — APPROVED** [review]
👍🏼 thanks @nizamial09 !

**Comment by epuertat** [comment]
```ts
.............................................................................
  â RgwUserFormComponent âº username validation âº should validate that username is required

    Control 'uid' could not be found!

      26 |     const control = this._get(controlName);
      27 |     if (!control) {
    > 28 |       throw new Error(`Control '${controlName}' could not be found!`);
         |             ^
      29 |     }
      30 |     return control;
      31 |   }

      at CdFormGroup.get (src/app/shared/forms/cd-form-group.ts:28:13)
      at FormHelper.getControl (src/testing/unit-test-helper.ts:158:24)
      at FormHelper.setValue (src/testing/unit-test-helper.ts:148:20)
      at FormHelper.expectErrorChange (src/testing/unit-test-helper.ts:187:27)
      at src/app/ceph/rgw/rgw-user-form/rgw-user-form.component.spec.ts:159:18
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invoke (node_modules/zone.js/dist/zone.js:386:30)
      at ProxyZoneSpec.Object.<anonymous>.ProxyZoneSpec.onInvoke (node_modules/zone.js/dist/proxy.js:117:43)
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invoke (node_modules/zone.js/dist/zone.js:385:36)
      at Zone.Object.<anonymous>.Zone.run (node_modules/zone.js/dist/zone.js:143:47)

  â RgwUserFormComponent âº username validation âº should validate that username is valid

    Control 'uid' could not be found!

      26 |     const control = this._get(controlName);
      27 |     if (!control) {
    > 28 |       throw new Error(`Control '${controlName}' could not be found!`);
         |             ^
      29 |     }
      30 |     return control;
      31 |   }

      at CdFormGroup.get (src/app/shared/forms/cd-form-group.ts:28:13)
      at FormHelper.getControl (src/testing/unit-test-helper.ts:158:24)
      at FormHelper.setValue (src/testing/unit-test-helper.ts:148:20)
      at src/app/ceph/rgw/rgw-user-form/rgw-user-form.component.spec.ts:164:18
      at node_modules/zone.js/dist/fake-async-test.js:610:34
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invoke (node_modules/zone.js/dist/zone.js:386:30)
      at ProxyZoneSpec.Object.<anonymous>.ProxyZoneSpec.onInvoke (node_modules/zone.js/dist/proxy.js:117:43)
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invoke (node_modules/zone.js/dist/zone.js:385:36)
      at Zone.Object.<anonymous>.Zone.run (node_modules/zone.js/dist/zone.js:143:47)

  â RgwUserFormComponent âº username validation âº should validate that username is invalid

    Control 'uid' could not be found!

      26 |     const control = this._get(controlName);
      27 |     if (!control) {
    > 28 |       throw new Error(`Control '${controlName}' could not be found!`);
         |             ^
      29 |     }
      30 |     return control;
      31 |   }

      at CdFormGroup.get (src/app/shared/forms/cd-form-group.ts:28:13)
      at FormHelper.getControl (src/testing/unit-test-helper.ts:158:24)
      at FormHelper.setValue (src/testing/unit-test-helper.ts:148:20)
      at src/app/ceph/rgw/rgw-user-form/rgw-user-form.component.spec.ts:171:18
      at node_modules/zone.js/dist/fake-async-test.js:610:34
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invoke (node_modules/zone.js/dist/zone.js:386:30)
      at ProxyZoneSpec.Object.<anonymous>.ProxyZoneSpec.onInvoke (node_modules/zone.js/dist/proxy.js:117:43)
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invoke (node_modules/zone.js/dist/zone.js:385:36)
      at Zone.Object.<anonymous>.Zone.run (node_modules/zone.js/dist/zone.js:143:47)

  â RgwUserFormComponent âº RgwUserCapabilities âº capability button disabled when all capabilities are added

    Control 'uid' could not be found!

      26 |     const control = this._get(controlName);
      27 |     if (!control) {
    > 28 |       throw new Error(`Control '${controlName}' could not be found!`);
         |             ^
      29 |     }
      30 |     return control;
      31 |   }

      at CdFormGroup.get (src/app/shared/forms/cd-form-group.ts:28:13)
      at CdFormGroup.getValue (src/app/shared/forms/cd-form-group.ts:52:17)
      at RgwUserFormComponent.setCapability (src/app/ceph/rgw/rgw-user-form/rgw-user-form.component.ts:404:31)
      at src/app/ceph/rgw/rgw-user-form/rgw-user-form.component.spec.ts:320:19
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invoke (node_modules/zone.js/dist/zone.js:386:30)
      at ProxyZoneSpec.Object.<anonymous>.ProxyZoneSpec.onInvoke (node_modules/zone.js/dist/proxy.js:117:43)
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invoke (node_modules/zone.js/dist/zone.js:385:36)
      at Zone.Object.<anonymous>.Zone.run (node_modules/zone.js/dist/zone.js:143:47)
```

**Comment by nizamial09** [comment]
jenkins test make check

**Comment by nizamial09** [comment]
jenkins test api

**Pull request merged**
