### PR TITLE
quincy: mgr/stats: be resilient to offline MDS rank-0

### PR DESCRIPTION
**Pull request by joscollin**
Resolves: https://tracker.ceph.com/issues/54480
Resolves: https://tracker.ceph.com/issues/55337

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [x] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [x] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by joscollin** [comment]
jenkins test make check

**Comment by idryomov** [comment]
jenkins test windows

**Comment by ljflores** [comment]
http://pulpito.front.sepia.ceph.com/yuriw-2022-04-22_21:06:04-rados-wip-yuri3-testing-2022-04-22-0534-quincy-distro-default-smithi/
http://pulpito.front.sepia.ceph.com/yuriw-2022-04-25_14:14:44-rados-wip-yuri3-testing-2022-04-22-0534-quincy-distro-default-smithi/
http://pulpito.front.sepia.ceph.com/lflores-2022-04-26_15:57:44-rados-wip-yuri3-testing-2022-04-22-0534-quincy-distro-default-smithi/

Failures, unrelated:
    https://tracker.ceph.com/issues/54509
    https://tracker.ceph.com/issues/51076
    https://tracker.ceph.com/issues/44595
    https://tracker.ceph.com/issues/54329
    https://tracker.ceph.com/issues/55443
    https://tracker.ceph.com/issues/52657

Details:
    1. FAILED ceph_assert due to issue manifest API to the original object - Ceph - RADOS
    2. "wait_for_recovery: failed before timeout expired" during thrashosd test with EC backend. - Ceph - RADOS
    3. cache tiering: Error: oid 48 copy_from 493 returned error code -2 - Ceph - RADOS
    4. test_nfs.py: NFS Ganesha cluster deployment timeout - Ceph
    5. "SELinux denials found.." in rados run - Infrastructure
    6. MOSDPGLog::encode_payload(uint64_t): Assertion `HAVE_FEATURE(features, SERVER_NAUTILUS)' - Ceph - RADOS

**Review by joscollin — COMMENTED** [review]
@yuriw @ljflores This needs an `fs` suite run and check if `test_perf_stats_stale_metrics` fails.

**Pull request merged**
