### PR TITLE
mgr/dashboard: Unify remaining action labels

### PR DESCRIPTION
**Pull request by tspmelo**
Fixes: http://tracker.ceph.com/issues/39102

Signed-off-by: Tiago Melo <tmelo@suse.com>

### CODE REVIEW

**Comment by tspmelo** [comment]
jenkins test make check

**Comment by callithea** [comment]
jenkins test make check

**Comment by ricardoasmarques** [comment]
jenkins test make check

**Comment by ricardoasmarques** [comment]
jenkins retest this please

**Comment by ricardoasmarques** [comment]
jenkins test make check arm64

**Pull request merged**
