### PR TITLE
rgw: include string header

### PR DESCRIPTION
**Pull request by wjwithagen**
Otherwise we get complaints from the compiler on FreeBS/Clang:
In file included from /home/jenkins/workspace/ceph-master/src/rgw/rgw_sync_module_es.cc:4:
/home/jenkins/workspace/ceph-master/src/rgw/rgw_b64.h:28:22: error: implicit instantiation of undefined template 'std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >'
  inline std::string to_base64(std::string_view sview)
                     ^
/usr/include/c++/v1/iosfwd:210:32: note: template is declared here
    class _LIBCPP_TEMPLATE_VIS basic_string;
                               ^
In file included from /home/jenkins/workspace/ceph-master/src/rgw/rgw_sync_module_es.cc:4:
/home/jenkins/workspace/ceph-master/src/rgw/rgw_b64.h:51:17: error: implicit instantiation of undefined template 'std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >'
    std::string outstr(b64_iter(sview.data()),
                ^
/usr/include/c++/v1/iosfwd:210:32: note: template is declared here
    class _LIBCPP_TEMPLATE_VIS basic_string;

.............. more errors
                               ^
/home/jenkins/workspace/ceph-master/src/rgw/rgw_sync_module_es.cc:193:59: error: no matching function for call to 'to_base64'
      default_headers.emplace("AUTHORIZATION", "Basic " + rgw::to_base64(auth_string));
                                                          ^~~~~~~~~~~~~~
/home/jenkins/workspace/ceph-master/src/rgw/rgw_b64.h:28:22: note: candidate template ignored: substitution failure [with wrap_width = 2147483647]
  inline std::string to_base64(std::string_view sview)

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by tchaikov** [comment]
jenkins retest this please

**Comment by ivancich** [comment]
@wjwithagen Will this need backports? If so please add a tracker.

**Comment by ivancich** [comment]
Teuthology Results:
http://pulpito.ceph.com/ivancich-2020-07-09_17:27:12-rgw-wip-eric-testing-1-distro-basic-smithi/
http://pulpito.ceph.com/ivancich-2020-07-09_17:27:31-rgw-wip-eric-testing-1-distro-basic-smithi/

Re-run of Errors:
http://pulpito.ceph.com/ivancich-2020-07-09_22:59:32-rgw-wip-eric-testing-1-distro-basic-smithi/

**Comment by wjwithagen** [comment]
> 
> 
> @wjwithagen Will this need backports? If so please add a tracker.

Yes I should, if the original PR is backported.
Will try to that this weekend.

**Pull request merged**
