### PR TITLE
jewel: ceph-disk: do not setup_statedir on trigger

### PR DESCRIPTION
**Pull request by Vicente-Cheng**
http://tracker.ceph.com/issues/20151

### CODE REVIEW

**Comment by Vicente-Cheng** [comment]
retest this please

**Comment by smithfarm** [comment]
@Vicente-Cheng Please rebase.

**Comment by smithfarm** [comment]
Jenkins re-test this please

**Comment by Vicente-Cheng** [comment]
@smithfarm  rebase done!

**Comment by smithfarm** [comment]
@jdurgin This passed a ceph-disk suite at http://tracker.ceph.com/issues/19538#note-84 and it would be nice to have it in 10.2.8. OK to merge?

**Pull request merged**
