### PR TITLE
WIP: RFC: include/ceph_features: annotate client features, reclaim a few

### PR DESCRIPTION
**Pull request by liewegas**
Two goals here:

- first, catalogue the origins of all of these feature bits
- whether clients advertise them
- whether clients pay attention to them
- whether clients support them

Particularly with the kernel.  Features that are not advertised and also ignored by all clients we care about can be ignored.  If we pick a sufficiently old kernel that we no longer care about, we can also start the long process of phasing feature bits out.

### CODE REVIEW

**Comment by liewegas** [comment]
@idryomov I started going through these earlier this week but didn't get too far.  I was also a bit worried that I would miss features that were used previously but ignored by the latest code.  When you have some time do you mind looking through these?  If we can identify some feature bits we can phase out that would be great.

**Comment by jdurgin** [comment]
@idryomov @liewegas still want to do this?

**Comment by liewegas** [comment]
Yeah, I still think we should do this audit at some point... even if we only manage to annotate which version/commit of the kernel client added support for a feature.

**Comment by jdurgin** [comment]
retest this please

**Comment by idryomov** [comment]
I started documenting these in a branch, but never finished.  I'll resurrect it -- I think we might be able to deprecate some of those that have been required by the kernel client for a while.

**Comment by liewegas** [comment]
Thanks, @idryomov !

**Comment by idryomov** [comment]
Our deprecation process doesn't work for client facing feature bits, but if we wanted to go down that path, we can probably deprecate most of pre-argonaut feature bits.  I think it's safe to assume that no one serious about their data is running pre-argonaut clusters, so we can stop checking for those feature bits and get rid of the fallback code in nautilus and 4.20.  Then, in some years or if we are short on feature bits again, we can reuse them (thus breaking pre-nautilus and pre-4.20 clients by allowing misinterpretation).

This has already happened for NOSRCADDR -- Haomai removed the fallback from both simple and async messengers last year.  Here is where we are on client facing argonaut features:

- NOSRCADDR     -- 2.6.35 req
- FLOCK         -- 2.6.36
- SUBSCRIBE2    -- 4.6 req
- MONNAMES      -- not in kernel, might need one day?
- RECONNECT_SEQ -- 3.10 req
- DIRLAYOUTHASH -- 2.6.38
- OBJECTLOCATOR -- not in kernel, won't need
- PGID64        -- 3.9 req
- INCSUBOSDMAP  -- not in kernel, might need one day?
- PGPOOL3       -- 3.9 req
- OSDREPLYMUX   -- not in kernel, will need for handling multiple cls payloads
- OSDENC        -- 3.9 req
- MONENC        -- not in kernel, might need one day?

So it looks like we can safely deprecate (but continue to advertise):

- NOSRCADDR
- FLOCK
- SUBSCRIBE2
- RECONNECT_SEQ
- DIRLAYOUTHASH
- OBJECTLOCATOR
- PGID64
- PGPOOL3
- OSDENC

**Comment by liewegas** [comment]
Let's just replace this PR so I'm not holding anything up.

For that list of features to deprecate, that means we also need to make changes in 4.20 for the client to stop checking for those bits, right?

The alternative to all of this is to figure out how to do add a second set of 64 feature bits everywhere.  Maybe that is something we should build into msgr2 regardless.  In which case, we might wan to just do the minimal set of bits we can reclaim now because they aren't checked by the kernel at all... are there any of those?

**Comment by idryomov** [comment]
Yes, the above list is from the client point of view.  By making those changes on the client side (e.g. in nautilus and 4.20), we establish a lower bound.  We obviously can't drop all fallback code on the server side because of old kernels.

That was my thought as well.  I'm not a fan of compatibility breakage -- I think the kernel can still execute some shell utility binaries from 1994.  Given that the day we could conceivably abolish pre-4.20 clients is many years away, I think we should ensure that the new msgr v2 handshake has enough space for feature bits to last us a lifetime and just condition the use of new features on msgr v2 if we run out of  retired ones.

**Comment by idryomov** [comment]
As mentioned in the commit message, all features that don't have a kernel version comment are not and have been checked by the kernel.

**Comment by idryomov** [comment]
Opened #24949.

**Comment by idryomov** [comment]
That PR is just for annotating, we can continue discussing reclaiming here.

Do you think it's worth making changes for assuming argonaut in 4.20 to keep all doors open?

**Comment by liewegas** [comment]
Yes... assuming argonaut (on the server side at least) is definitely safe.  :)

**Pull request closed without merging**
