### PR TITLE
doc/rbd: add mutual CHAP authentication example

### PR DESCRIPTION
**Pull request by idryomov**
Based on https://github.com/ceph/ceph-iscsi/pull/260.

Signed-off-by: Ilya Dryomov <idryomov@gmail.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/master/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [x] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [x] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by lxbsz** [comment]
We need to mention that, the uersnames/passwords should be the same for admin and mutual, I didn't find any doc about this but just from my tests.

And also please mention the chars allowed for the usernames/passwords and more detail about the chars allowed for the username/password please see https://github.com/ceph/ceph-iscsi/blob/main/gwcli/utils.py#L172.

All the others look good to me.

**Comment by idryomov** [comment]
> We need to mention that, the uersnames/passwords should be the same for admin and mutual, I didn't find any doc about this but just from my tests.

Did you mean "should NOT be the same"?  If so, that is already mentioned.

> 
> And also please mention the chars allowed for the usernames/passwords and more detail about the chars allowed for the username/password please see https://github.com/ceph/ceph-iscsi/blob/main/gwcli/utils.py#L172.

Done.

**Comment by lxbsz** [comment]
> > We need to mention that, the uersnames/passwords should be the same for admin and mutual, I didn't find any doc about this but just from my tests.
> 
> Did you mean "should NOT be the same"? If so, that is already mentioned.
> 
Oh, sorry. Right.

Thanks

> > And also please mention the chars allowed for the usernames/passwords and more detail about the chars allowed for the username/password please see https://github.com/ceph/ceph-iscsi/blob/main/gwcli/utils.py#L172.
> 
> Done.

**Review by lxbsz — APPROVED** [review]
LGTM.

**Comment by idryomov** [comment]
Tweaked formatting.

**Pull request merged**
