### PR TITLE
jewel: ReplicatedBackend: take read locks for clone sources during recovery

### PR DESCRIPTION
**Pull request by asheplyakov**
http://tracker.ceph.com/issues/18581
http://tracker.ceph.com/issues/18724

### CODE REVIEW

**Comment by jdurgin** [comment]
http://tracker.ceph.com/issues/18583 should be backported at the same time - it fixes a bug in this

**Comment by smithfarm** [comment]
@asheplyakov To implement the previous comment, could you please:

1. cherry-pick 3833440 into this PR
2. add http://tracker.ceph.com/issues/18724 to the PR description
3. set status of http://tracker.ceph.com/issues/18724 to "In Progress" and put the URL of this PR in the description

If any of this doesn't make sense, just ping me.

**Comment by asheplyakov** [comment]
@jdurgin thanks for a tip
@smithfarm done

**Comment by smithfarm** [comment]
@jdurgin This passed a rados suite at http://tracker.ceph.com/issues/17851#note-45 with some (few, unrelated) failures. OK to merge?

**Comment by smithfarm** [comment]
This passed another rados run at http://tracker.ceph.com/issues/17851#note-53

**Comment by smithfarm** [comment]
NOTE: this backport was later reverted by https://github.com/ceph/ceph/pull/13280

**Comment by shinobu-x** [comment]
@smithfarm You are great :)

**Pull request merged**
