### PR TITLE
remove autotools

### PR DESCRIPTION
**Pull request by liewegas**
Signed-off-by: Sage Weil <sage@redhat.com>

### CODE REVIEW

**Comment by tchaikov** [comment]
lgtm, once jenkins build passes.

**Comment by alimaredia** [comment]
Love the branch name

**Comment by tchaikov** [comment]
unittest_http_manager times out, it's a known issue, see http://tracker.ceph.com/issues/17052

**Comment by liewegas** [comment]
\o/

**Comment by xiexingguo** [comment]
> Love the branch name

+1

**Pull request merged**
