### PR TITLE
[DNM][RFC] os/bluestore: refactor bluefs log mechanics

### PR DESCRIPTION
**Pull request by ifed01**
This rework attempts to make BlueFS log implementation less complicated and less error prone.

The major design idea is to get rid off dynamic log allocations and use two statically allocated ones, 16MB is the proposed single log size atm.
At every given time single log is in use, when it becomes full switching to another one (coupled with compaction) occurs. To perform such a switching in a safe manner each log is coupled with a stamp (a small disk block-aligned structure) which keeps monotonically incremented log compaction/switching number, first owned operation seq number and a checksum. 
Related stamp is written as a last step during log switching/compaction. On OSD restart this allows to learn which of the two logs is the effective one - attached log compaction number is used for that, the one with a higher value is chosen. Checksum permits to handle stamp write failure and the first owned operation seq number allows to filter out legacy records during log replay.

Additionally the patch introduces an ability to log op_update operation in an incremental manner, i.e. instead of logging the whole allocation map from fnode it writes out just a new portion of it (if any). The full allocation map is recovered during log replay on startup or from a full op_update record produced during log compaction. 
This works fine given that we do not perform partial trimming on bluefs files. The feature is pretty independent from the log refactoring though.

Signed-off-by: Igor Fedotov <ifedotov@suse.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by aclamk** [comment]
Part 1. Twin BlueFs logs - ino 1 and ino 2.

I assume that this is introduced to avert uncommon, but critical failure that happens when we lack BlueFS log space, but need to write transaction. If there are more goals that I missed please inform me.
Proposed solution does fix the problem (excluding pathological cases like when streaming files to log make a transaction longer then 16MB, but it is extremely unlikely).
I do not like the fact that it requires a lot of changes, including on-disk format change, two inos for logs and new logic for replay file detection.

How about different approach:
When bluefs transaction does not fit in runway:
1) create new log writer
2) sync stream everything to new log
3) update super
4) drop currently constructed transaction (it's contents is already written in step 2)
?

Part 2. OP_FILE_UPDATE_INC

That thing is useful and not very invasive. 
Can you please extract it to separate PR while we ponder on first part?

**Comment by ifed01** [comment]
> Part 2. OP_FILE_UPDATE_INC
> 
> That thing is useful and not very invasive.
> Can you please extract it to separate PR while we ponder on first part?

https://github.com/ceph/ceph/pull/42734

**Comment by ifed01** [comment]
> Part 1. Twin BlueFs logs - ino 1 and ino 2.
> 
> I assume that this is introduced to avert uncommon, but critical failure that happens when we lack BlueFS log space, but need to write transaction. If there are more goals that I missed please inform me.

Make the code simpler/more straightforward.

> Proposed solution does fix the problem (excluding pathological cases like when streaming files to log make a transaction longer then 16MB, but it is extremely unlikely).
> I do not like the fact that it requires a lot of changes, including on-disk format change, two inos for logs and new logic for replay file detection.
> 
> How about different approach:
> When bluefs transaction does not fit in runway:
> 
> 1. create new log writer
> 2. sync stream everything to new log
> 3. update super
Two points I don't like in superblock updating which apply to the original implementation as  well:

- I'm not sure that writing to super is absolutely safe - what would happen if the host dies during its write?
- superblob has limited space for log's allocation map (kept inside fnode_t) - how to avoid the potential overflow on e.g. a fragmented disk?

> 4. drop currently constructed transaction (it's contents is already written in step 2)
>    ?
> 
> Part 2. OP_FILE_UPDATE_INC
> 
> That thing is useful and not very invasive.
> Can you please extract it to separate PR while we ponder on first part?

**Comment by liewegas** [comment]
The primary concern with having a fixed log buffer is that it effectively limits the maximum number of (rocksdb) files that you can have in the fs.  That would in turn limit the amount of metadata (either onodes or omap data) can we can store on the OSD.  Do you have a sense of how much that is with 16MB?  Shouldn't it be based on the overall size of the OSD?  The problem is that if we get to close to that limit we end up having to frequently rewrite the entirety of the bluefs metadata to make space.  And if we ever hit 16MB we're screwed.

I think we either need to be obscenely conservative with this log size (i.e., biggest we can imagine, *10), or may look for some middle road that lets us simplify the current wandering log in some other way.  Or maybe even just keep the existing wandering log, but make it allocate chunks that are 16MB (or more) so that in practice they never need to wander?

**Pull request closed without merging**
