### PR TITLE
hammer: scrub bogus results when missing a clone

### PR DESCRIPTION
**Pull request by dzafman**
Backport most features of ceph-objectstore-tool including snapshot handling
Backport improved scrub snapshot handling

The Backport issues fixed by this pull request: 

http://tracker.ceph.com/issues/14891
http://tracker.ceph.com/issues/14076
http://tracker.ceph.com/issues/14077
http://tracker.ceph.com/issues/14886
http://tracker.ceph.com/issues/14893
http://tracker.ceph.com/issues/14892
http://tracker.ceph.com/issues/14897
http://tracker.ceph.com/issues/14896
http://tracker.ceph.com/issues/14898
http://tracker.ceph.com/issues/14895
http://tracker.ceph.com/issues/14890
http://tracker.ceph.com/issues/14889
http://tracker.ceph.com/issues/14888
http://tracker.ceph.com/issues/14887
http://tracker.ceph.com/issues/14884
http://tracker.ceph.com/issues/14885
http://tracker.ceph.com/issues/14894
http://tracker.ceph.com/issues/14899

### CODE REVIEW

**Comment by dachary** [comment]
@dzafman could you replace the merge commit https://github.com/ceph/ceph/commit/79196b83fc1b41bc0661c9a04dcbf6fc1b5e9b6c with the individual commits instead ? Other than this it looks less tricky than I thought it would :-)

It would be very helpful to detail the conflict resolution as much as possible. When you mention that ceph-helpers.sh location has changed, it's self expanatory. However when you write "No sequencer in transactions in hammer", it makes me wonder how difficult it was to resolve the associated conflicts and if you had to adapt because the logic of the code was different.

Last but not least, this backports a large number of fixes that had individual fixes. As much as possible it would be a lot better to split this long series into individual pull requests addressing a given backport. I realize this is a lot more work from an administrative point of view. But I think it's also valuable to keep hammer stable despite the magnitude of the change.

For instance maybe 

 	ceph-objectstore-tool: Check pgid validity earlier like we did before … 	b5525b5
	@dzafman 	ceph-objectstore-tool: Eliminate obscure "Invalid params" error … 	74481bf
	@dzafman 	ceph-objectstore-tool: Check for keyvaluestore experimental feature … 	4bd0b7d
	@dzafman 	ceph-objectstore-tool: Add dump-journal op … 	c5151e3

could be made into a pull request that is the hammer backport of http://tracker.ceph.com/issues/11135. And when this is tested and merged, we can have 

        https://github.com/ceph/ceph/commit/a5878ff36430961cbfbb9cf70ba8e8b7d1186100

which is the hammer backport of http://tracker.ceph.com/issues/10809 and so on.

What do you think ?

P.S. in any case I'll run a rados suite with this PR, just to assert the end result is ok. Unless you did that already ?

**Comment by dzafman** [comment]
@dachary https://github.com/ceph/ceph/commit/79196b83fc1b41bc0661c9a04dcbf6fc1b5e9b6c is confusing because it was a change made as part of a merge not the other content of the merge.  I tried to explain that in the comment because I knew it would be confusing. https://github.com/ceph/ceph/commit/79196b83fc1b41bc0661c9a04dcbf6fc1b5e9b6c has the cherry-pick of the commit after which Sage renamed the function at merge time.

As far as putting them in as individual pull requests.  I'm not sure how to go about finding the original pull request merges other than manually looking at every commit.  I'll see how hard that looks.

I ran a rados run, but have already started another on smithi only for a more accurate run.

**Comment by dachary** [comment]
> 79196b8 is confusing because it was a change made as part of a merge not the other content of the merge. I tried to explain that in the comment because I knew it would be confusing. 

Oh, thanks for point that out. I did not even look at the comment and reacted on the commit title alone.

**Comment by dachary** [comment]
@dzafman As far as putting them in as individual pull requests. I'm not sure how to go about finding the original pull request merges other than manually looking at every commit. 

Yes. It's not hard but tedious. However I believe it is essential to keep the backports organized. For instance, if we were to commit this series, http://tracker.ceph.com/issues/11135 would be backported although the issue does not have "hammer" in the Backport field, nor an associated Backport issue dedicated to hammer. Also, someone interested in finding how http://tracker.ceph.com/issues/11135 was backported would end up in this large series and it would be non trivial to find which commits are relevant to this specific issue (i.e. is it just the commit with "fixes 11135" ? or are there more ? Having a separate pull request makes all that easier.

I'm trying to rationalize the backport organization and its benefits because I feel you should not do all that work by yourself. Would you like me to help ? When you've completed the tests that show the whole series work, I can research the issues that need backporting and create the associated issues / pull requests to split all this in smaller pieces.

**Comment by dzafman** [comment]
@dachary I found a script that at least finds the merge above any given commit.  I the 90 commits group into 15 groups based do on the merge commit.

**Comment by dzafman** [comment]
@dachary I've created 2 new branches/pull requests.

See #7722 and #7724.  If I take the final commit from  #7724 and rebase each change into the commit where it belongs I should end up with exactly or almost exactly the same thing as #7722.

Should we test this all at once and when ready to merge, create pull requests one at a time and merge them one after the other?  The dependencies probably won't allow me to have 15 pull requests all against hammer to be created.

Example: Say I have 4 commits for 3 original merges (A - B) merge 1, C merge 2 and D merge 3,  I want to create 3 pull requests so that each goes in with a merge commit (MC)

hammer -- A -- B -- C --D

After 3 pull requests are merged.

hammer -- A -- B -- MC -- C -- MC -- D -- MC (new hammer)

**Comment by dachary** [comment]
@dzafman I would do the following:

* list all pull requests from which the commits originate, as well as the associated issue (and create one for the purpose of tracing if a pull request has no issue associated with it, which sometime happens)
* order the original pull requests in chronological order, by date of merge (using the date of the merge commit)
* backport each issue in that order, using this pr (#7702) as a guide for conflict resolution
* create an integration branch with all the backport PRs (at least 15 of them according to your findings). the integration branch should look exactly as #7702 except it would be the merge of all individual pull requests
* test the integration branch in the same way you tested #7702 

This is essentially what we usually do for backporting. In this case, there are a lot of interdependencies between pull requests. But thanks to what you did with #7702, we know exactly in which order the merge should happen for the conflicts to resolve.

Does that make sense ?

**Comment by dachary** [comment]
@dzafman could you please list the merges that you found ?

**Comment by dzafman** [comment]
The order of commits in the branch in #7722 corresponds with the merge table order and counts.

**Comment by dachary** [comment]
Nice table, easy to read :-)

https://github.com/ceph/ceph/pull/3686 has been merged feb 2015 and the "crushtool: process commands in a sensible order" commit it contains does not show in #7722. Or did I get something wrong in how to read the table ?

**Comment by dachary** [comment]
@dzafman the table is very helpful. It clearly shows that there is a series of cot backports and I think we can group them together in a single pull requests without risking any confusion later on. The only pull request that would be worth separating is the backport of https://github.com/ceph/ceph/pull/5783. And since https://github.com/ceph/ceph/pull/6545 seems to depend on it, that one would need to be in a separate pull request as well. That would be a total of three backport pull requests instead of over a dozen.

Does this sound like a sensible approach to you ?

**Comment by dzafman** [comment]
> #3686 has been merged feb 2015 and the "crushtool: process commands in a sensible order" commit it > contains does not show in #7722. Or did I get something wrong in how to read the table ?

The single commit dca345280e4f6124a8b5aea73e6219488111c356 was back ported, so I list its original pull request #3686 as to where it came from.  And that is why there is only 1 shown as the number of commits even though the original pull request had 7 commits.

I only pull in whatever individual commits I needed.

**Comment by dachary** [comment]
> The single commit dca3452 was back ported, so I list its original pull request #3686 as to where it came from. 

I got confused, sorry for the noise.

**Comment by dachary** [comment]
Master merge sha1|Commits|Pull|Issue|Notes
-------------------|--------|----------|------------------------------------
92d26bb82b94998a7b3b8d842bb33d5c796503fe|1(7)|#3686|http://tracker.ceph.com/issues/14874
8d596bfa24c9c3e2aadbb87494284cb5fd824e55|1(1) + 1|wip-journal-header|http://tracker.ceph.com/issues/????| This merge also cherry-picked
00c4fc890737b0c57224d223d002d02e94ef097b|41(48)|#4473|http://tracker.ceph.com/issues/????
228ee47cfdef5371e29fa823ad2660e83535c7e1|8(9)|#4784|http://tracker.ceph.com/issues/????|Exclude actual fix for 10794
267177543799bffa0a80294373c4bd3e75f6a41b|1(12)|#4863|http://tracker.ceph.com/issues/????
9c6da3b0875dec3ca88fc6dd7de6214439e91b39|1(1)|#4915|http://tracker.ceph.com/issues/????
0698bde96a1acedc3b44f8c9420455a6b95b18fc|1(1)|#4932|http://tracker.ceph.com/issues/????
b30610c5bc63e7c16c7278c691c23d871eb02a96|3(3)|wip-temp|http://tracker.ceph.com/issues/????
661205899be3e3f7b53682a3b87c1340e395b62e|6(7)|#5197|http://tracker.ceph.com/issues/????|Don't add meta-list COT option
9e7955e42f47f93dd802401505d2e642abce491a|6(6)|#5127|http://tracker.ceph.com/issues/????
cdca05feb0250c6c1c7be59d3df6f57c2eb12285|2(2)|#5842|http://tracker.ceph.com/issues/????
86dbfc88f84e71f71ebd96cead0439664f4c35e0|1(1)|#5031|http://tracker.ceph.com/issues/????
19565e19d8f6ffbc667bccf098711edc9dcbb96f|22(22)|#5783|http://tracker.ceph.com/issues/????
b75d1074f67f3409ab97c0731f948efe5c1e8622|6(7)|#6545|http://tracker.ceph.com/issues/????|Still need remove_coll()

**Comment by dachary** [comment]
@dzafman I don't understand (I think you explained but I did not write it down and forgot) why you included https://github.com/ceph/ceph/commit/8d596bfa24c9c3e2aadbb87494284cb5fd824e55 instead of https://github.com/ceph/ceph/commit/8f80ae3fbaba7b0e64b6e4df6c2dddd10ac50e5a ?

**Comment by dachary** [comment]
@dzafman giving it a cute name. The backport is much more extensive but that is the issue that prompted it. If you think another name would be more appropriated, please update :-)

**Comment by dachary** [comment]
http://tracker.ceph.com/projects/ceph-releases/wiki/Tmp is the hammer-backports-loic integration branch running on gitbuilders. I'll run a rados suite on it to compare with the other integration branch.

**Comment by dzafman** [comment]
> @dzafman I don't understand (I think you explained but I did not write it down and forgot) why you included 8d596bf instead of 8f80ae3 ?

I actually include both because that is how it went into the master branch.  One is the fix and the other was the merge commit that renamed the function.

**Comment by dachary** [comment]
> One is the fix and the other was the merge commit that renamed the function.

Ah, right s/write_header/write_header_sync/ (added to the note of the table above for the record).

**Comment by dachary** [comment]
Redmine friendly display
<pre>
git --no-pager log --format='%H %s' --graph hammer..wip-14077-hammer | perl -p -e 's/"/ /g; if (/\w+\s+Merge pull request #(\d+)/) { s|\w+\s+Merge pull request #(\d+).*|"Pull request $1":https://github.com/ceph/ceph/pull/$1|; } else { s|(\w+)\s+(.*)|"$2":https://github.com/ceph/ceph/commit/$1|; } s/\*/+/; s/^/* /;' 
</pre>

**Comment by dachary** [comment]
Passed a run of the rados suite (http://tracker.ceph.com/issues/14692#note-27) and the upgrade suite (http://tracker.ceph.com/issues/14692#note-29).

**Comment by dachary** [comment]
The companion pull request https://github.com/ceph/ceph-qa-suite/pull/834 contains new tests that have been run by david already, this is good enough for the purpose of merging this pull request.

**Pull request merged**
