### PR TITLE
Reduce CPU usage by reusing stringstream in stringify function

### PR DESCRIPTION
**Pull request by efirs**
About 10% CPU reduction and 10% TPS bump in CPU bound workload.
Blanks in the fourth column is saved CPU after the change.

screen shot 2015-10-07 at 11 10 15 am

### CODE REVIEW

**Comment by XinzeChi** [comment]
@efirs , what tools do you use to generate this image? is it public?

**Comment by efirs** [comment]
> what tools do you use to generate this image? is it public?

It is Intel vtune.

**Comment by yuyuyu101** [comment]
LGTM... but the performance difference is still a shock to me. The perf is applied in the osd process level or a specified thread?

**Comment by efirs** [comment]
@yuyuyu101 Its full osd process profile.

**Pull request merged**
