### PR TITLE
crimson/osd/osd_operations/internal_client_request: always provide the latest osdmap epoch to IOInterruptCondition

### PR DESCRIPTION
**Pull request by xxhdx1985126**
Fixes: https://tracker.ceph.com/issues/68068
Signed-off-by: Xuehan Xu <xuxuehan@qianxin.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Review by Matan-B — CHANGES_REQUESTED** [review]
This commit is a revert of 238f15e42df3d0bd3e699ba24e8a940af9ae20ba from #58463. See Also: https://tracker.ceph.com/issues/66827

IIUC, the infinite loop of `stored epoch_started e2578 < interval_start e2685` may be actually correct in a way. I think that the issue is that we handle internal requests in `seastar::repeat` without dropping the request on errors unless `should_abort_request` is true.

On acting set changed, we are not dropping the request, we instead try again with the same `start_epoch`:
```
      if (e.is_primary()) {
        logger().debug("{} {} operation restart, acting set changed", __func__, op);
        return false;
      } 
``` 

Perhaps we should update start_epoch when retrying an internal req?

---

In case I'm missing something, can you please change this commit to a revert one?

**Comment by athanatos** [comment]
This doesn't look right to me -- if the InternalClientRequest was constructed at an epoch prior to the current interval, it *should* be canceled.  What is causing this to be constantly rescheduled?

**Comment by xxhdx1985126** [comment]
> This doesn't look right to me -- if the InternalClientRequest was constructed at an epoch prior to the current interval, it _should_ be canceled. What is causing this to be constantly rescheduled?
> 
> The only user I see of InternalClientRequest is WatchTimeoutRequest via do_watch_timeout(). If the epoch at which the event was originally constructed is in the prior interval, we do not want to retry -- we want to simply drop it on the ground. If the osd in question is still primary, the pg will eventually get around to kicking off a fresh do_watch_timeout() in the new interval. Continuing to retry the old one will at best be unnecessary and at worst cause bugs if it causes conflicting updates to the obc. Generally, any operation started during an interval should be (safety) canceled and ignored when the interval changes (client requests where the primary did not change are the only exception because the client implementation will not resend them).
> 
> It's not clear to me, however, what's causing it to be retried, so I'm presumably missing something.

Just as @Matan-B pointed out, `should_abort_request` doesn't abort internal requests as long as the osd is still primary, which caused the retries. Maybe we should treat `client requests` and `internal requests` differently in `should_abort_requests`, although only `internal requests` resort to `should_abort_request`?

**Comment by Matan-B** [comment]
> Just as @Matan-B pointed out, `should_abort_request` doesn't abort internal requests as long as the osd is still primary, which caused the retries. Maybe we should treat `client requests` and `internal requests` differently in `should_abort_requests`, although only `internal requests` resort to `should_abort_request`?

How about changing `should_abort_request` to also drop the request on primary when acting set is changed?

**Comment by athanatos** [comment]
Ah, I got confused.  I was looking at a branch with some InternalClientRequest refactors -- one of those refactors is a removal of the seastar::repeat and should_abort_request portions from InternalClientRequest.

CommonClientRequest::should_abort_request isn't actually used for normal ClientRequests -- 5aa342c9f08df251917020d2a0970f94d9d66ec0 removed it in favor of the current ClientRequest::Orderer implementation.  I probably should have removed it from InternalClientRequest at the time, but I didn't notice.  With the removal from InternalClientRequest, should_abort_request has no other callers and can be removed entirely.

https://github.com/ceph/ceph/pull/59815 has commits removing the seastar::repeat and should_abort_request portions of InternalClientRequest::start.

**Comment by xxhdx1985126** [comment]
Closing in favour of #59815.

**Pull request closed without merging**
