### PR TITLE
mimic: os/filestore: ceph_abort() on fsync(2) or fdatasync(2) failure

### PR DESCRIPTION
**Pull request by pdvian**
http://tracker.ceph.com/issues/38317

### CODE REVIEW

**Comment by smithfarm** [comment]
`156/156 Test   #3: test_objectstore_memstore.sh ............***Timeout 3600.02 sec`

**Comment by smithfarm** [comment]
jenkins re-test this please

**Comment by yuriw** [comment]
[wip-yuri-testing-2019-02-18-1714-mimic](https://trello.com/c/vJf3xQOH/539-wip-yuri-testing-2019-02-18-1714-mimic)

**Comment by yuriw** [comment]
[wip-yuri3-testing-2019-02-20-1755-mimic](https://trello.com/c/1TLmDcrx/542-wip-yuri3-testing-2019-02-20-1755-mimic)

**Pull request merged**
