### PR TITLE
qa/task/rgw: instruct Valgrind to don't exit on first error.

### PR DESCRIPTION
**Pull request by rzarzynski**
This requires https://github.com/ceph/teuthology/pull/1600.

Signed-off-by: Radoslaw Zarzynski <rzarzyns@redhat.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by cbodley** [comment]
thanks @rzarzynski!

@jdurgin any idea what this will look like with cephadm?

**Review by cbodley — APPROVED** [review]
we'll have to coordinate merging of this with the teuthology pr, but i'll pull it into my valgrind branch for testing

**Comment by jdurgin** [comment]
@cbodley cephadm isn't running valgrind yet, we should keep this in mind when we add that

**Comment by cbodley** [comment]
jenkins test docs

**Comment by cbodley** [comment]
thank you gentlemen

**Comment by mattbenjamin** [comment]
> 
> 
> thank you gentlemen

+1 !!

**Pull request merged**
