### PR TITLE
rbd-mirror: Set the data pool correctly when creating images

### PR DESCRIPTION
**Pull request by adamwg**
Previously the data-pool option was ignored by rbd-mirror, so when using
erasure coding data for the image on the secondary site would end up in
the metadata pool.

Configure the data-pool using the data-pool's name from the primary site
when creating images on the secondary site.

Fixes: http://tracker.ceph.com/issues/20567

Signed-off-by: Adam Wolfe Gordon <awg@digitalocean.com>

### CODE REVIEW

**Comment by trociny** [comment]
The proposed fix looks good to me as a default behaviour. Still it would be nice if a user could change this. I can imagine a use case when one cluster has erasure coding pools for image data and another one does not.

**Comment by adamwg** [comment]
@trociny Agreed. I'm planning to start work soon on allowing the data-pool to be specified when a peer is added. Of course, I won't be upset if someone beats me to it ;-).

**Comment by dillaman** [comment]
As is, I think we need to update the mirroring documentation to state that now not only do the mirrored pools need to match across clusters, but also any data pools. Alternatively, you could add a new ```rbd_mirror_data_pools_enabled```-like configuration option.

**Comment by adamwg** [comment]
@dillaman I've added a note to the docs regarding pool names; please let me know if there are other spots that should be updated as well.

**Comment by dillaman** [comment]
jenkins render docs

**Pull request merged**
