### PR TITLE
[RGW] Fix the handling of HEAD requests that do not comply with RFC standards

### PR DESCRIPTION
**Pull request by VVoidV**
According to RFC 9110, The HEAD method is identical to GET except that the server MUST NOT send content in the response.

The following HEAD OP is using chunked encoding and send the final chunk

| HTTP Request                 | Function                            |
|------------------------------|-------------------------------------|
| HEAD /bucket?uploads         | RGWListBucketMultiparts_ObjStore_S3 |
| HEAD /bucket/abc?uploadId    | RGWListMultipart_ObjStore_S3        |
| HEAD /                       | RGWListBuckets_ObjStore_S3          |

Clients using persistent connections, such as nginx, will be unable to handle subsequent requests after processing such requests because the final chunk remains in the TCP byte stream, preventing the next HTTP response from being correctly parsed.

Ref: https://www.rfc-editor.org/rfc/rfc9110.html#section-9.3.2
Tracker: https://tracker.ceph.com/issues/66938?next_issue_id=66937

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [x] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Comment by cbodley** [comment]
thanks, this makes sense 👍 

according to rfc 7230, we also have the option to omit Transfer-Encoding entirely:
> Transfer-Encoding MAY be sent in a response to a HEAD request or in a
   304 (Not Modified) response ([Section 4.1 of [RFC7232]](https://www.rfc-editor.org/rfc/rfc7232#section-4.1)) to a GET
   request, neither of which includes a message body, to indicate that
   the origin server would have applied a transfer coding to the message
   body if the request had been an unconditional GET.  This indication
   is not required, however, because any recipient on the response chain
   (including the origin server) can remove transfer codings when they
   are not needed.

this saves a tiny bit of bandwidth, and the fix for that is more concise:
```diff
diff --git a/src/rgw/rgw_rest.cc b/src/rgw/rgw_rest.cc
index 102f05d7862..d0cdd4716aa 100644
--- a/src/rgw/rgw_rest.cc
+++ b/src/rgw/rgw_rest.cc
@@ -397,7 +397,9 @@ void dump_content_length(req_state* const s, const uint64_t len)
 
 static void dump_chunked_encoding(req_state* const s)
 {
-  try {
+  // omit transfer-encoding for HEAD requests so ChunkingFilter doesn't
+  // try to write the final chunk
+  if (s->op != OP_HEAD) try {
     RESTFUL_IO(s)->send_chunked_transfer_encoding();
   } catch (rgw::io::Exception& e) {
     ldpp_dout(s, 0) << "ERROR: RESTFUL_IO(s)->send_chunked_transfer_encoding()"
```
what do you think?

**Comment by VVoidV** [comment]
> thanks, this makes sense 👍
> 
> according to rfc 7230, we also have the option to omit Transfer-Encoding entirely:
> 
> > Transfer-Encoding MAY be sent in a response to a HEAD request or in a
> > 304 (Not Modified) response ([Section 4.1 of [RFC7232]](https://www.rfc-editor.org/rfc/rfc7232#section-4.1)) to a GET
> > request, neither of which includes a message body, to indicate that
> > the origin server would have applied a transfer coding to the message
> > body if the request had been an unconditional GET.  This indication
> > is not required, however, because any recipient on the response chain
> > (including the origin server) can remove transfer codings when they
> > are not needed.
> 
> this saves a tiny bit of bandwidth, and the fix for that is more concise:
> 
> ```diff
> diff --git a/src/rgw/rgw_rest.cc b/src/rgw/rgw_rest.cc
> index 102f05d7862..d0cdd4716aa 100644
> --- a/src/rgw/rgw_rest.cc
> +++ b/src/rgw/rgw_rest.cc
> @@ -397,7 +397,9 @@ void dump_content_length(req_state* const s, const uint64_t len)
>  
>  static void dump_chunked_encoding(req_state* const s)
>  {
> -  try {
> +  // omit transfer-encoding for HEAD requests so ChunkingFilter doesn't
> +  // try to write the final chunk
> +  if (s->op != OP_HEAD) try {
>      RESTFUL_IO(s)->send_chunked_transfer_encoding();
>    } catch (rgw::io::Exception& e) {
>      ldpp_dout(s, 0) << "ERROR: RESTFUL_IO(s)->send_chunked_transfer_encoding()"
> ```
> 
> what do you think?


Agree with you. 

However, The standard is a bit ambiguous on this.

The current standard is RFC-9110(HTTP Semantics) and RFC-9112(HTTP/1.1). 
For HEAD requests, [RFC-9110](https://www.rfc-editor.org/rfc/rfc9110.html#section-9.3.2-2) mentions that the headers should be the same as for GET requests, but some headers that are determined when generating the body can be omitted. 


> The server SHOULD send the same header fields in response to a HEAD request as it would have sent if the request method had been GET. However, a server MAY omit header fields for which a value is determined only while generating the content. For example, some servers buffer a dynamic response to GET until a minimum amount of data is generated so that they can more efficiently delimit small responses or make late decisions with regard to content selection. Such a response to GET might contain [Content-Length](https://www.rfc-editor.org/rfc/rfc9110.html#field.content-length) and [Vary](https://www.rfc-editor.org/rfc/rfc9110.html#field.vary) fields, for example, that are not generated within a HEAD response. These minor inconsistencies are considered preferable to generating and discarding the content for a HEAD request, since HEAD is usually requested for the sake of efficiency.

The  [RFC-9112](https://www.rfc-editor.org/rfc/rfc9112#section-6.1-9) retains the same description from 7230: Transfer-Encoding is not required in HEAD requests.

> Transfer-Encoding MAY be sent in a response to a HEAD request or in a 304 (Not Modified) response ([Section 15.4.5](https://www.rfc-editor.org/rfc/rfc9110#section-15.4.5) of [[HTTP](https://www.rfc-editor.org/rfc/rfc9112#HTTP)]) to a GET request, neither of which includes a message body, to indicate that the origin server would have applied a transfer coding to the message body if the request had been an unconditional GET. This indication is not required, however, because any recipient on the response chain (including the origin server) can remove transfer codings when they are not needed.
> [](https://www.rfc-editor.org/rfc/rfc9110.html#section-9.3.2-2)
>

**Comment by cbodley** [comment]
> However, The standard is a bit ambiguous on this.

thanks for the links. it says we _should_ return the same headers, with some exceptions like Transfer-Encoding/Content-Length etc. that doesn't sound ambiguous to me

**Review by cbodley — APPROVED** [review]

**Comment by ivancich** [comment]
Teuthology results, no regressions:
* https://pulpito.ceph.com/ivancich-2024-07-23_19:16:42-rgw-wip-eric-testing-1-distro-default-smithi/
* https://pulpito.ceph.com/ivancich-2024-07-23_19:29:16-rgw-wip-eric-testing-1-distro-default-smithi/

**Pull request merged**
