### PR TITLE
bluestore: latest and greatest

### PR DESCRIPTION
**Pull request by liewegas**
rename newstore -> bluestore
use a block device
back rocksdb with BlueRocksEnv, which share block device(s) with bluestore

### CODE REVIEW

**Comment by yuyuyu101** [comment]
COOL, so fast

**Comment by dzafman** [comment]
Jenkins:
os/bluestore/bluefs_tool.cc:38:27: error: no matching function for call to 'BlueFS::mount(int, int)'
   int r = fs.mount(0, 4096);

**Comment by dzafman** [comment]
Once it builds I'm tempted to modify the  test/ceph_objectstore_tool.py to vstart using --bluestore option and test using --type bluestore to see what happens.

**Comment by liewegas** [comment]
On Fri, 11 Dec 2015, David Zafman wrote:
> Once it builds I'm tempted to modify the test/ceph_objectstore_tool.py to vstart using --bluestore option and test using --type bluestore to see
> what happens.

That'd be great!

**Comment by dzafman** [comment]
4 problems found:
keyvaluestore_rocksdb_options as empty string is not handled maybe because RocksDBStore::ParseOptionsFromString() never calls rocksdb::GetOptionsFromString() in that case.  I set to "write_buffer_size=1024,max_write_buffer_number=2" as a work around.

Code to handle bluestore_bluefs_env_mirror won't link so I just disabled it because config is false by default anyway.

_open_bdev can't delete bdev without first calling bdev->close();

Bluestore disklabel is overwritten after --mkfs is used to create it, so OSDs just crash with bad decode on start-up with vstart.  I saw the the dev/osd0/block had the disklabel after it was written, but when I let the mkfs complete and checked again.

**Comment by dzafman** [comment]
See changes in https://github.com/dzafman/ceph/commit/a99dbfdc6f25582a2a58cd5b04315df497bcc4f0

**Comment by dzafman** [comment]
The empty keyvaluestore_rocksdb_options isn't an issue.  It might be related to either the rocksdb build in my tree at one point, or misidentified the cause of a mount failure.

**Comment by dzafman** [comment]
I was able to use vstart.sh after making _check_or_set_bdev_label() alway return success instead of even calling _read_bdev_label() which fails.

The test/ceph_objectstore_tools.py test unfortunately relies on looking at the filestore format.  So instead of trying to rewrite that test, I created some objects and ran a good portion of the commands with ceph-objectstore-tool and using --type bluestore.  I saw no failures.  Maybe we should have a generic non-filestore ceph-objectstore-tool test which can supplement the current test.  It could then also be used for keyvaluestore or any future objectstores.

**Pull request merged**
