### PR TITLE
ceph.spec.in: add librdmacm-devl package.

### PR DESCRIPTION
**Pull request by majianpeng**
When complie:
In file included from /opt/ceph/src/msg/async/rdma/RDMAStack.h:30:0,
                 from /opt/ceph/src/msg/async/Stack.cc:22:
/opt/ceph/src/msg/async/rdma/Infiniband.h:21:27: fatal error:
rdma/rdma_cma.h: No such file or directory
 #include <rdma/rdma_cma.h>

Signed-off-by: Jianpeng Ma <jianpeng.ma@intel.com>

### CODE REVIEW

**Comment by majianpeng** [comment]
@tchaikov . On fedora/ubuntu, i met this bug. please review.

**Comment by tchaikov** [comment]
@majianpeng thanks for fixing this, maybe we should add this dependency to debian/control also? see https://jenkins.ceph.com/job/ceph-pull-requests/21073/consoleFull#19442965567dc3600c-28d8-42e2-9653-291a0c275fdf. i am posting #14245 to revert that change at this moment.

**Comment by yuyuyu101** [comment]
sure, librdmacm-dev for debian

**Comment by tchaikov** [comment]
closing, as it turns out we don't need that header.

**Pull request closed without merging**
