### PR TITLE
luminous: osd: backport recent upmap fixes

### PR DESCRIPTION
**Pull request by xiexingguo**
This pr backports the following fixes:
https://github.com/ceph/ceph/pull/23734 (included to reduce conflicts)
https://github.com/ceph/ceph/pull/25952
https://github.com/ceph/ceph/pull/26039
https://github.com/ceph/ceph/pull/26179
https://github.com/ceph/ceph/pull/26187
https://github.com/ceph/ceph/pull/26478

Related backport tickets:
http://tracker.ceph.com/issues/37889
http://tracker.ceph.com/issues/38037
http://tracker.ceph.com/issues/38162

- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by neha-ojha** [comment]
Hey @xiexingguo, looks like this PR contains a backport of https://github.com/ceph/ceph/pull/26187, which hasn't merged in master. Can we get that one merged and cherry-pick it to luminous?

**Comment by xiexingguo** [comment]
Sorry, I add that one fix by accident, will drop that one for now.

I'll send new backports once they get merged into master.

**Comment by yuriw** [comment]
[wip-yuri2-testing-2019-02-11-1725-luminous](https://trello.com/c/TeEVo8B7/534-wip-yuri2-testing-2019-02-11-1725-luminous)

**Comment by yuriw** [comment]
[wip-yuri6-testing-2019-02-13-1800-luminous](https://trello.com/c/B96YdIDM/538-wip-yuri6-testing-2019-02-13-1800-luminous)

**Comment by xiexingguo** [comment]
Including more fixes recently identified. 
(Prepare the backports myself since the conflicts are non-trivial/hard to resolve)

**Comment by yuriw** [comment]
[wip-yuri3-testing-2019-02-21-2350-luminous](https://trello.com/c/rVcrtd6V/545-wip-yuri3-testing-2019-02-21-2350-luminous)

**Comment by yuriw** [comment]
@xiexingguo FYI

**Comment by xiexingguo** [comment]
The failures are all caused by https://github.com/ceph/ceph/pull/26501 and should be resolved now.

@yuriw Please re-schedule.

**Comment by yuriw** [comment]
[wip-yuri4-testing-2019-02-27-2159-luminous](https://trello.com/c/rdUQQoLb/550-wip-yuri4-testing-2019-02-27-2159-luminous)

**Pull request merged**
