### PR TITLE
jewel: multimds: allow_multimds not required when max_mds is set in ceph.conf at startup

### PR DESCRIPTION
**Pull request by batrick**
http://tracker.ceph.com/issues/17264

### CODE REVIEW

**Comment by dachary** [comment]
jenkins test this please (the logs are gone)

**Comment by dachary** [comment]
@batrick could you please **git cherry-pick -x** instead so that it has a well formed **cherry picked from...** line ? It's not mandatory but will help scripts that expect it. Thanks :-)

**Comment by batrick** [comment]
@dachary done.

**Comment by dachary** [comment]
jenkins test this please (bluefs core)

**Comment by dachary** [comment]
@batrick perfect, thanks !

**Comment by dachary** [comment]
jenkins test this please (bluefs core)

**Comment by dachary** [comment]
tested at http://pulpito.ceph.com/jspray-2016-10-10_15:27:25-fs-wip-jcsp-backports-20161010-distro-basic-mira/

**Pull request merged**
