### PR TITLE
rgw: add support for metadata upload during PUT on Swift container

### PR DESCRIPTION
**Pull request by rzarzynski**

### CODE REVIEW

**Comment by rzarzynski** [comment]
This is a partial fix only. Full solution (with attrs removal, proper merge etc.) needs PR #3894. I will provide it as fast as the dependency is available.

**Comment by dachary** [comment]
@rzarzynski ping ?

**Comment by rzarzynski** [comment]
@dachary pong. This PR waits for #3894.

**Comment by rzarzynski** [comment]
@yehudasa rebased to master, improved support for metadata removal and added fix for ```EAGAIN``` from ```rgw_bucket_set_attrs```.

The [https://github.com/rzarzynski/ceph/tree/wip-11147-old-1](old branch) is available as well.

**Comment by smithfarm** [comment]
@rzarzynski ping, #3894 has been merged.

**Comment by yehudasa** [comment]
@rzarzynski what's the status of this feature?

**Comment by rzarzynski** [comment]
This PR - after substantial rework - has been reincarnated as #8002. Closing.

**Pull request closed without merging**
