### PR TITLE
Dynamic control optracker

### PR DESCRIPTION
**Pull request by majianpeng**
make osd/mds can dynamic control optracker settting.

### CODE REVIEW

**Comment by majianpeng** [comment]
@tchaikov . Have you time review this?  Thanks!

**Comment by tchaikov** [comment]
@majianpeng generally looks good. we might want to add this to the pending release notes.

**Comment by gregsfortytwo** [comment]
I think the dynamic control is okay, but we definitely want to leave the optracker enabled by default. It's just too useful for debugging when user clusters get stuck, but that doesn't work if the tracking was off when things broke.

**Comment by majianpeng** [comment]
@dachary . Can you fix  this failure(not related w/ my code)?  Thanks!

**Comment by tchaikov** [comment]
lgtm after a rados qa run.

**Comment by dachary** [comment]
@majianpeng it needs rebasing

**Comment by tchaikov** [comment]
@majianpeng ping?

**Comment by majianpeng** [comment]
@tchaikov .  Rebased. Thanks!

**Comment by dachary** [comment]
Please ignore the make check bot error on Ubuntu, it is a false negative (http://tracker.ceph.com/issues/13136).

**Comment by tchaikov** [comment]
@majianpeng not sure why your change fails the test of http://pulpito.ceph.com/kchai-2015-09-25_06:02:07-rados-wip-kefu-testing---basic-multi/1068857/ . i am removing your pr from my test branch at this moment.

**Pull request merged**
