### PR TITLE
pybind: misc fixes

### PR DESCRIPTION
**Pull request by marcan**
Three minor fixes discovered while writing AIO support for pybind/rbd (will be a separate PR).

### CODE REVIEW

**Comment by liewegas** [comment]
@jdurgin ?

**Comment by jdurgin** [comment]
thanks, lgtm

**Comment by marcan** [comment]
Not sure what the checks failing issue is. I updated this branch to the parent commit of #9292, which had passed, but it also failed, which doesn't really make sense. Looks like the tests that failed are unrelated to this PR.

**Comment by jdurgin** [comment]
Yeah, definitely unrelated to this PR. filing a bug

**Comment by yuriw** [comment]
test run http://pulpito.ceph.com/yuriw-2016-05-26_19:14:40-rbd-wip-yuri-testing2-distro-basic-smithi/

**Pull request merged**
