### PR TITLE
mgr/dashboard: form field validation icons overlap with other icons

### PR DESCRIPTION
**Pull request by Sarthak0702**
Before:
image

After:
image

Fixes: https://tracker.ceph.com/issues/55604
Signed-off-by: Sarthak0702 <sarthak.dev.0702@gmail.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/master/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [x] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by Sarthak0702** [comment]
jenkins test windows

**Comment by Sarthak0702** [comment]
jenkins test dashboard cephadm

**Comment by Sarthak0702** [comment]
jenkins test dashboard

**Comment by Sarthak0702** [comment]
jenkins retest this please

**Comment by Sarthak0702** [comment]
jenkins test api

**Comment by Sarthak0702** [comment]
jenkins test dashboard

**Comment by Sarthak0702** [comment]
jenkins test dashboard

**Review by pereman2 — APPROVED** [review]
Tested locally and looks like it works!

**Review by avanthakkar — APPROVED** [review]
LGTM!

**Comment by Sarthak0702** [comment]
jenkins test dashboard

**Comment by epuertat** [comment]
@Sarthak0702 could you plz paste a screenshot of the Before & After, including a validation error (you can try with the Pools - Create form, for example). And could we have a visual regression testing (Applitools) of a form? That way we ensure this never breaks again (or at least we notice it) :D

**Comment by Sarthak0702** [comment]
> @Sarthak0702 could you plz paste a screenshot of the Before & After, including a validation error (you can try with the Pools - Create form, for example). And could we have a visual regression testing (Applitools) of a form? That way we ensure this never breaks again (or at least we notice it) :D

Done! Shouldn't we add the test after the PR is merged?

**Comment by epuertat** [comment]
Looks good! But... I observed the same issue I faced when I tried to fix this: the fields with removed class, now have a different left-alignment than the other ones... For example compare "rbd2" to "erasure" and "on" in the before & after screenshots.

Given this issue is less visible than the other one, I'll merge this and ask you to track this defect in a follow-up issue.

**Comment by epuertat** [comment]
Dashboard tests are failing only due to Applitools browser upgrade (Chrome 101 and Firefox 100).

**Comment by Sarthak0702** [comment]
> Looks good! But... I observed the same issue I faced when I tried to fix this: the fields with removed class, now have a different left-alignment than the other ones... For example compare "rbd2" to "erasure" and "on" in the before & after screenshots.
> 
> Given this issue is less visible than the other one, I'll merge this and ask you to track this defect in a follow-up issue.

Created this tracker: https://tracker.ceph.com/issues/55754.

**Pull request merged**
