### PR TITLE
jewel: krbd-related CLI patches

### PR DESCRIPTION
**Pull request by idryomov**
http://tracker.ceph.com/issues/17555

### CODE REVIEW

**Comment by idryomov** [comment]
Original master PRs: #11303 #11313 #11370.

**Comment by dachary** [comment]
@idryomov good to merge with a description of the krbd test that was run to verify it does work.

<pre>
Reviewed-by: Loic Dachary &lt;ldachary@redhat.com>
</pre>

**Comment by idryomov** [comment]
Repushed with conflict descriptions.

**Comment by idryomov** [comment]
These commits allow passing certain options to the rbd kernel module and don't bring in any new functionality.  Tested manually by myself.

**Pull request merged**
