### PR TITLE
octopus: qa: krbd_blkroset.t: update for separate hw and user read-only flags

### PR DESCRIPTION
**Pull request by idryomov**
backport tracker: https://tracker.ceph.com/issues/49874

---

backport of https://github.com/ceph/ceph/pull/40175
parent tracker: https://tracker.ceph.com/issues/49858

### CODE REVIEW

**Comment by idryomov** [comment]
jenkins test make check

**Comment by idryomov** [comment]
jenkins test make check

**Review by dillaman — APPROVED** [review]
:+1:

**Comment by idryomov** [comment]
jenkins test make check

**Comment by idryomov** [comment]
https://pulpito.ceph.com/dis-2021-03-19_15:44:21-krbd-octopus-testing-basic-smithi/

**Pull request merged**
