### PR TITLE
src,qa,dashboard: Upgrade to mypy 0.790

### PR DESCRIPTION
**Pull request by sebastian-philipp**
dashboard/tools: Make sure {begin,end}_time are set.

Signed-off-by: Sebastian Wagner <sebastian.wagner@suse.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by sebastian-philipp** [comment]
lint: ERROR: /home/jenkins-build/build/workspace/ceph-pull-requests/src/pybind/mgr/dashboard/tools.py Imports are incorrectly sorted and/or formatted.

**Comment by sebastian-philipp** [comment]
jenkins test make check

**Comment by sebastian-philipp** [comment]
jenkins test api

**Review by jmolmo — APPROVED** [review]

**Review by s0nea — APPROVED** [review]
LGTM :+1: 

@sebastian-philipp should the PR go through Dashboard QA?

**Comment by sebastian-philipp** [comment]
@callithea ^^ ?

**Comment by callithea** [comment]
- [pkg build](https://shaman.ceph.com/builds/ceph/wip-laura-testing-38490/)
- [QA run](https://pulpito.ceph.com/laura-2020-12-10_19:00:52-rados:dashboard-wip-laura-testing-38490-distro-basic-smithi/) [WIP]

**Review by callithea — APPROVED** [review]

**Comment by callithea** [comment]
@sebastian-philipp should we run it through any other QA suite or is this sufficient?

**Pull request merged**
