### PR TITLE
admin/doc-requirements: bump sphinx to 4.4.0

### PR DESCRIPTION
**Pull request by tchaikov**
bump sphinx to latest stable. to address following build failure

ERROR: sphinx-autodoc-typehints 1.17.0 has requirement Sphinx>=4, but you'll have sphinx 3.5.4 which is incompatible.
ERROR: sphinx-substitution-extensions 2022.2.16 has requirement sphinx>=4.0.0, but you'll have sphinx 3.5.4 which is incompatible.

also bump bump sphinx-rtd-theme

otherwise we'd have

ERROR: sphinx-rtd-theme 0.5.2 has requirement docutils<0.17, but you'll have docutils 0.17.1 which is incompatible.

Signed-off-by: Kefu Chai <tchaikov@gmail.com>

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by tchaikov** [comment]
jenkins test docs

**Comment by tchaikov** [comment]
retest this please.

**Comment by ljflores** [comment]
jenkins test docs

**Review by ljflores — APPROVED** [review]

**Comment by tchaikov** [comment]
jenkins test docs

**Comment by tchaikov** [comment]
@ljflores hi Laura, thanks for your review and approval. but it seems sphinx 4.x is more picky, and it considers the warnings as errors and hence fails the `sphinx-build` command. i just added a couple commits to address the warnings. but two of the new changes are related to the orchestrator, so i am adding @sebastian-philipp as another reviewer so he could help review the related change. also, could you help review the new changes added on top of the existing commits, namely the "[doc/conf.py: silence warnings from breathe](https://github.com/ceph/ceph/pull/45266/commits/8891d653198c30f9578499126e1ee9ee67eca04a) change.


@sebastian-philipp hi Sebastian, could you please help review the orchestrator related change? the goal is to silence the new warnings from Sphinx 4.4.0.

**Comment by tchaikov** [comment]
regarding the change in the docstring of shim'ed methods, please see the difference between

- https://docs.ceph.com/en/latest/mgr/orchestrator_modules/#orchestrator.OrchestratorClientMixin
- https://ceph--45266.org.readthedocs.build/en/45266/mgr/orchestrator_modules/#orchestrator.OrchestratorClientMixin

**Review by mgfritch — APPROVED** [review]

**Comment by ljflores** [comment]
jenkins test api

**Pull request merged**
