### PR TITLE
rgw/multisite: add cls versioning for data sync per shard status object

### PR DESCRIPTION
**Pull request by smanjara**
Signed-off-by: Shilpa Jagannath <smanjara@redhat.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Review by cbodley — COMMENTED** [review]
this is a good start! we found all the places that need version tracking

as a next step, we need to arrange for each datalog shard to have its own instance of `RGWObjVersionTracker`, so it can use that same instance for every step of the process (Read, Init, List, and Sync). this way, we can detect racing writes at any point of the process, instead of just in between the new reads and their writes

`RGWDataSyncCR` has a member variable `rgw_data_sync_status sync_status` that stores a map of the per-shard sync markers, which gets passed to each of these coroutines `RGWReadDataSyncStatusMarkersCR`, `RGWInitDataSyncStatusCoroutine`, and `RGWListBucketIndexesCR`. each `RGWDataSyncShardCR` also gets a pointer to its own shard marker

we'll need to do something similar for the storage of these `RGWObjVersionTracker`s. for example, by adding a `std::vector<RGWObjVersionTracker>` to `RGWDataSyncCR` that gets passed along with the sync status and shard markers. `RGWDataSyncShardCR` should get its `RGWObjVersionTracker&` by reference, and share that with its `RGWDataSyncShardMarkerTrack`

**Comment by cbodley** [comment]
p.s. just be aware of conflicts with @adamemerson's work in https://github.com/ceph/ceph/pull/47422 and https://github.com/ceph/ceph/pull/47566

**Comment by smanjara** [comment]
> this is a good start! we found all the places that need version tracking
> 
> as a next step, we need to arrange for each datalog shard to have its own instance of `RGWObjVersionTracker`, so it can use that same instance for every step of the process (Read, Init, List, and Sync). this way, we can detect racing writes at any point of the process, instead of just in between the new reads and their writes
> 
> `RGWDataSyncCR` has a member variable `rgw_data_sync_status sync_status` that stores a map of the per-shard sync markers, which gets passed to each of these coroutines `RGWReadDataSyncStatusMarkersCR`, `RGWInitDataSyncStatusCoroutine`, and `RGWListBucketIndexesCR`. each `RGWDataSyncShardCR` also gets a pointer to its own shard marker
> 
> we'll need to do something similar for the storage of these `RGWObjVersionTracker`s. for example, by adding a `std::vector<RGWObjVersionTracker>` to `RGWDataSyncCR` that gets passed along with the sync status and shard markers. `RGWDataSyncShardCR` should get its `RGWObjVersionTracker&` by reference, and share that with its `RGWDataSyncShardMarkerTrack`


> this is a good start! we found all the places that need version tracking
> 
> as a next step, we need to arrange for each datalog shard to have its own instance of `RGWObjVersionTracker`, so it can use that same instance for every step of the process (Read, Init, List, and Sync). this way, we can detect racing writes at any point of the process, instead of just in between the new reads and their writes
> 
> `RGWDataSyncCR` has a member variable `rgw_data_sync_status sync_status` that stores a map of the per-shard sync markers, which gets passed to each of these coroutines `RGWReadDataSyncStatusMarkersCR`, `RGWInitDataSyncStatusCoroutine`, and `RGWListBucketIndexesCR`. each `RGWDataSyncShardCR` also gets a pointer to its own shard marker
> 
> we'll need to do something similar for the storage of these `RGWObjVersionTracker`s. for example, by adding a `std::vector<RGWObjVersionTracker>` to `RGWDataSyncCR` that gets passed along with the sync status and shard markers. `RGWDataSyncShardCR` should get its `RGWObjVersionTracker&` by reference, and share that with its `RGWDataSyncShardMarkerTrack`

makes sense

**Comment by smanjara** [comment]
> this is a good start! we found all the places that need version tracking
> 
> as a next step, we need to arrange for each datalog shard to have its own instance of `RGWObjVersionTracker`, so it can use that same instance for every step of the process (Read, Init, List, and Sync). this way, we can detect racing writes at any point of the process, instead of just in between the new reads and their writes
> 
> `RGWDataSyncCR` has a member variable `rgw_data_sync_status sync_status` that stores a map of the per-shard sync markers, which gets passed to each of these coroutines `RGWReadDataSyncStatusMarkersCR`, `RGWInitDataSyncStatusCoroutine`, and `RGWListBucketIndexesCR`. each `RGWDataSyncShardCR` also gets a pointer to its own shard marker
> 
> we'll need to do something similar for the storage of these `RGWObjVersionTracker`s. for example, by adding a `std::vector<RGWObjVersionTracker>` to `RGWDataSyncCR` that gets passed along with the sync status and shard markers. `RGWDataSyncShardCR` should get its `RGWObjVersionTracker&` by reference, and share that with its `RGWDataSyncShardMarkerTrack`

Addressing this in a rebased version #47682

**Comment by smanjara** [comment]
Closing against  #47682

**Pull request closed without merging**
