### PR TITLE
msg: resurrect support for !CEPH_FEATURE_MSG_AUTH

### PR DESCRIPTION
**Pull request by idryomov**

### CODE REVIEW

**Comment by yuyuyu101** [comment]
because kernel client needs?

**Comment by idryomov** [comment]
@yuyuyu101 Yes, as noted in the commit message.

**Comment by idryomov** [comment]
Test run (covers both old and new kernels): http://pulpito.ceph.com/dis-2017-11-20_18:39:51-krbd:unmap-wip-resurrect-msg-auth-testing-basic-smithi/

**Comment by tchaikov** [comment]
- http://pulpito.ceph.com/kchai-2017-11-21_16:17:37-rados-wip-kefu-testing-2017-11-21-1844-distro-basic-mira/1874213/
- http://pulpito.ceph.com/kchai-2017-11-21_16:17:37-rados-wip-kefu-testing-2017-11-21-1844-distro-basic-mira/1874305/
- http://pulpito.ceph.com/kchai-2017-11-21_16:17:37-rados-wip-kefu-testing-2017-11-21-1844-distro-basic-mira/1874376/

dropping from my test batch.

**Comment by idryomov** [comment]
@tchaikov Looks like an existing bug -- reproduced on your 
wip-kefu-testing-2017-11-21-1844 with this PR reverted (603eacea7771).
```
     0> 2017-11-22 17:10:30.934 7fa3d5af0700 -1 /build/ceph-13.0.0-3422-g603eace/src/msg/async/AsyncConnection.cc: In function 'void AsyncConnection::process()' thread 7fa3d5af0700 time 2017-11-22 17:10:30.936672
/build/ceph-13.0.0-3422-g603eace/src/msg/async/AsyncConnection.cc: 705: FAILED assert(0 == "old msgs despite reconnect_seq feature")

 ceph version 13.0.0-3422-g603eace (603eacea77714074209fe75bf162922b8c839890) mimic (dev)
 1: (ceph::__ceph_assert_fail(char const*, char const*, int, char const*)+0x10e) [0x7fa3dbb77f0e]
 2: (AsyncConnection::process()+0x27d4) [0x7fa3dbe044a4]
 3: (EventCenter::process_events(int, std::chrono::duration<unsigned long, std::ratio<1l, 1000000000l> >*)+0x331) [0x7fa3dbc07821]
 4: (()+0xb6733e) [0x7fa3dbc0a33e]
 5: (()+0xb1a60) [0x7fa3d8f29a60]
 6: (()+0x8184) [0x7fa3d95a1184]
 7: (clone()+0x6d) [0x7fa3d8690ffd]
 NOTE: a copy of the executable, or `objdump -rdS <executable>` is needed to interpret this.
```

**Comment by tchaikov** [comment]
@idryomov could you attach the link to the test? or the steps how you reproduced this issue? or better off file a ticket in tracker. i am afraid that it's a serious issue.

**Comment by tchaikov** [comment]
@idryomov could you fill http://tracker.ceph.com/issues/22231 with more details?

**Comment by idryomov** [comment]
@tchaikov Done.

**Pull request merged**
