### PR TITLE
[DNM] Wip rgw sts abac doc

### PR DESCRIPTION
**Pull request by pritha-srivastava**
## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Review by mattbenjamin — COMMENTED** [review]
ok, everything in this PR looks fine.  I'm actually concerned 
a) that not everything currently supported by the PR is documented
b) the overall of the effect of the change is not described in any particular commit

**Comment by pritha-srivastava** [comment]
> ok, everything in this PR looks fine. I'm actually concerned
> a) that not everything currently supported by the PR is documented
> b) the overall of the effect of the change is not described in any particular commit

@mattbenjamin : i am adding documentation corresponding to each commit in PR https://github.com/ceph/ceph/pull/39849. So please ignore the code changes. Also once done I will add all these doc related commits back to #39849. I created this PR just for my reference.

**Comment by pritha-srivastava** [comment]
jenkins render docs

**Comment by pritha-srivastava** [comment]
jenkins render docs

**Comment by pritha-srivastava** [comment]
jenkins render docs

**Comment by pritha-srivastava** [comment]
jenkins render docs

**Comment by pritha-srivastava** [comment]
jenkins render docs

**Comment by mattbenjamin** [comment]
The title still says DNM...how close is it to "code complete?"

**Comment by pritha-srivastava** [comment]
> The title still says DNM...how close is it to "code complete?"

Hi @mattbenjamin : This PR is dnm because it is only for doc changes. The code changes are complete and are here: https://github.com/ceph/ceph/pull/39849. I plan to rebase it and finalise it by tomorrow with all doc related changes also.

**Pull request closed without merging**
