### PR TITLE
nautilus: rgw: RGWCoroutine::call(nullptr) sets retcode=0

### PR DESCRIPTION
**Pull request by pdvian**
https://tracker.ceph.com/issues/41627

### CODE REVIEW

**Comment by smithfarm** [comment]
Build failure:

```
In file included from /home/jenkins-build/build/workspace/ceph-pull-requests/src/include/encoding.h:30:0,
                 from /home/jenkins-build/build/workspace/ceph-pull-requests/src/include/uuid.h:8,
                 from /home/jenkins-build/build/workspace/ceph-pull-requests/src/include/types.h:21,
                 from /home/jenkins-build/build/workspace/ceph-pull-requests/src/common/ceph_json.h:4,
                 from /home/jenkins-build/build/workspace/ceph-pull-requests/src/rgw/rgw_auth_keystone.cc:13:
/home/jenkins-build/build/workspace/ceph-pull-requests/src/common/ceph_time.h:504:16: warning: variable templates only available with -std=c++14 or -std=gnu++14
 constexpr bool converts_to_timespec_v = converts_to_timespec<Clock>::value;
                ^~~~~~~~~~~~~~~~~~~~~~
In file included from /home/jenkins-build/build/workspace/ceph-pull-requests/src/include/encoding.h:34:0,
                 from /home/jenkins-build/build/workspace/ceph-pull-requests/src/include/uuid.h:8,
                 from /home/jenkins-build/build/workspace/ceph-pull-requests/src/include/types.h:21,
                 from /home/jenkins-build/build/workspace/ceph-pull-requests/src/common/ceph_json.h:4,
                 from /home/jenkins-build/build/workspace/ceph-pull-requests/src/rgw/rgw_auth_keystone.cc:13:
/home/jenkins-build/build/workspace/ceph-pull-requests/src/common/convenience.h:46:24: error: 'result_of_t' is not a member of 'std'
   boost::optional<std::result_of_t<F(const std::decay_t<T>)>>
                        ^~~~~~~~~~~
/home/jenkins-build/build/workspace/ceph-pull-requests/src/common/convenience.h:46:24: note: suggested alternative: 'result_of'
   boost::optional<std::result_of_t<F(const std::decay_t<T>)>>
                        ^~~~~~~~~~~
                        result_of
/home/jenkins-build/build/workspace/ceph-pull-requests/src/common/convenience.h:46:24: error: 'result_of_t' is not a member of 'std'
```

**Comment by tchaikov** [comment]
jenkins test make check

**Comment by badone** [comment]
The build failure happened because sometimes when building Nautilus on Xenial we use gcc 7.4 and sometimes we use gcc 8.3.0. 7.4 seems to fail due to a dance it does with cmake 3.5.1 and the addition of --std=gnu++11 to the compiler command lines for certain targets.

**Comment by smithfarm** [comment]
@badone Thanks for the analysis!

**Comment by tchaikov** [comment]
i don't think it's related to GCC. see #30283

**Comment by badone** [comment]
> i don't think it's related to GCC. see #30283

Builds succeed using 8.3 and fail using 7.4. Your PR explains/resolves the 7.4 build failure but teh fact remains that the same source built successfully using 8.3.

**Comment by yuriw** [comment]
[wip-yuri7-testing-2019-10-02-1628-nautilus](https://trello.com/c/476MnND5/703-wip-yuri7-testing-2019-10-02-1628-nautilus)

**Pull request merged**
