### PR TITLE
 mds: some request errors come from errno.h rather than fs_types.h

### PR DESCRIPTION
**Pull request by batrick**
## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Comment by batrick** [comment]
jenkins test make check

**Comment by leonid-s-usov** [comment]
As discussed in the other ticket, I don't think it is correct to change the response code. These should be host codes everywhere, and only when we cross a boundary of one host by sending it over the network to another ceph entity then should we convert the errors.

**Comment by batrick** [comment]
> As discussed in the other ticket, I don't think it is correct to change the response code. These should be host codes everywhere, and only when we cross a boundary of one host by sending it over the network to another ceph entity then should we convert the errors.

Yes, that fix needs done but this one still fixes the extant issue of the MDS returning host-os error codes to clients via the `tell` interface.

**Review by leonid-s-usov — CHANGES_REQUESTED** [review]
Looking at the usages of the `dump_cache`, it's only reported via the asock interface, which is expecting a host error, so I don't think that changes in the function are correct.

As for the `check_dir_max_entries`, the change is required since it's passed on to the `respond_to_request`, ending up in the MClientReply, which does expect a CEPHFS error code on the input.

**Comment by leonid-s-usov** [comment]
Related: https://tracker.ceph.com/issues/64611

**Comment by batrick** [comment]
> Maybe `MDSMap::update_num_mdss_in_rank_mask_bitset` and `MDSMap::hex2bin` needs changes too, they're using `EINVAL`

If the error stays local to the MDS then it does not need converted.

**Comment by batrick** [comment]
> Looking at the usages of the `dump_cache`, it's only reported via the asock interface, which is expecting a host error, so I don't think that changes in the function are correct.

The current code does pass `CEPHFS_E` errors to the tell/asok interface for MCommandReply. The transformation it does for hostos->ceph will still work.

**Comment by leonid-s-usov** [comment]
> > Looking at the usages of the `dump_cache`, it's only reported via the asock interface, which is expecting a host error, so I don't think that changes in the function are correct.
> 
> The current code does pass `CEPHFS_E` errors to the tell/asok interface for MCommandReply. The transformation it does for hostos->ceph will still work.

Sorry, I'm not following.

Whatever is passed as the result code to the `MCommandReply` should be a host error. That's the case today with the `dump_cache`, which is why I said this method shouldn't be changed. 
This PR changes errors in the method to CEPHFS_E, which is not correct, because they will be converted to CEPHFS_E namespace again by the `errorcode32_t` in the `MCommandReply`

**Comment by batrick** [comment]
> > > Looking at the usages of the `dump_cache`, it's only reported via the asock interface, which is expecting a host error, so I don't think that changes in the function are correct.
> > 
> > 
> > The current code does pass `CEPHFS_E` errors to the tell/asok interface for MCommandReply. The transformation it does for hostos->ceph will still work.
> 
> Sorry, I'm not following.
> 
> Whatever is passed as the result code to the `MCommandReply` should be a host error. That's the case today with the `dump_cache`, which is why I said this method shouldn't be changed. This PR changes errors in the method to CEPHFS_E, which is not correct, because they will be converted to CEPHFS_E namespace again by the `errorcode32_t` in the `MCommandReply`

You're right. I've pulled out that commit and left only `mds: use cephfs errno for fragment size check`.

**Review by leonid-s-usov — APPROVED** [review]

**Review by lxbsz — APPROVED** [review]

**Comment by batrick** [comment]
jenkins test api

**Comment by mchangir** [comment]
Teuthology Job Status

Job: snap-schedule
URL: https://pulpito.ceph.com/mchangir-2024-03-22_09:41:51-fs-wip-mchangir-testing-main-20240318.032620-testing-default-smithi/
Status: 11 jobs failed with PG_AVAILABILITY issues, whereas they actual tests passed as seen below

```
mchangir:logs$ for log in $(find /teuthology/mchangir-2024-03-22_09:41:51-fs-wip-mchangir-testing-main-20240318.032620-testing-default-smithi -mindepth 2 -maxdepth 2 -name 'teuthology.log'); do grep -H 'cephfs_test_runner:OK' $log; done
/teuthology/mchangir-2024-03-22_09:41:51-fs-wip-mchangir-testing-main-20240318.032620-testing-default-smithi/7616249/teuthology.log:2024-03-22T12:09:40.070 INFO:tasks.cephfs_test_runner:OK
/teuthology/mchangir-2024-03-22_09:41:51-fs-wip-mchangir-testing-main-20240318.032620-testing-default-smithi/7616252/teuthology.log:2024-03-22T12:11:43.760 INFO:tasks.cephfs_test_runner:OK
/teuthology/mchangir-2024-03-22_09:41:51-fs-wip-mchangir-testing-main-20240318.032620-testing-default-smithi/7616255/teuthology.log:2024-03-22T12:10:44.872 INFO:tasks.cephfs_test_runner:OK
/teuthology/mchangir-2024-03-22_09:41:51-fs-wip-mchangir-testing-main-20240318.032620-testing-default-smithi/7616251/teuthology.log:2024-03-22T12:20:18.371 INFO:tasks.cephfs_test_runner:OK
/teuthology/mchangir-2024-03-22_09:41:51-fs-wip-mchangir-testing-main-20240318.032620-testing-default-smithi/7616258/teuthology.log:2024-03-22T12:15:45.875 INFO:tasks.cephfs_test_runner:OK
/teuthology/mchangir-2024-03-22_09:41:51-fs-wip-mchangir-testing-main-20240318.032620-testing-default-smithi/7616254/teuthology.log:2024-03-22T12:20:04.651 INFO:tasks.cephfs_test_runner:OK
/teuthology/mchangir-2024-03-22_09:41:51-fs-wip-mchangir-testing-main-20240318.032620-testing-default-smithi/7616248/teuthology.log:2024-03-22T12:22:11.607 INFO:tasks.cephfs_test_runner:OK
/teuthology/mchangir-2024-03-22_09:41:51-fs-wip-mchangir-testing-main-20240318.032620-testing-default-smithi/7616250/teuthology.log:2024-03-22T12:23:09.965 INFO:tasks.cephfs_test_runner:OK
/teuthology/mchangir-2024-03-22_09:41:51-fs-wip-mchangir-testing-main-20240318.032620-testing-default-smithi/7616256/teuthology.log:2024-03-22T12:22:24.853 INFO:tasks.cephfs_test_runner:OK
/teuthology/mchangir-2024-03-22_09:41:51-fs-wip-mchangir-testing-main-20240318.032620-testing-default-smithi/7616257/teuthology.log:2024-03-22T12:20:46.343 INFO:tasks.cephfs_test_runner:OK
/teuthology/mchangir-2024-03-22_09:41:51-fs-wip-mchangir-testing-main-20240318.032620-testing-default-smithi/7616253/teuthology.log:2024-03-22T12:22:12.682 INFO:tasks.cephfs_test_runner:OK
```

Job: fs:upgrade
URL: https://pulpito.ceph.com/mchangir-2024-03-22_09:46:06-fs:upgrade-wip-mchangir-testing-main-20240318.032620-testing-default-smithi/
Status: 5 of 13 failed

all are known issues


Job: fs:libcephfs
URL: https://pulpito.ceph.com/mchangir-2024-03-22_09:48:09-fs:libcephfs-wip-mchangir-testing-main-20240318.032620-testing-default-smithi/
Status: 2 fail, 2 pass

all are known issues


Job: snap_schedule
URL: https://pulpito.ceph.com/mchangir-2024-03-22_09:40:19-fs-wip-mchangir-testing-main-20240318.032620-testing-default-smithi/
Status: 12 of 12 passed

Wiki: https://tracker.ceph.com/projects/cephfs/wiki/Main#2024-03-25

**Comment by batrick** [comment]
jenkins test api

**Comment by batrick** [comment]
https://tracker.ceph.com/issues/65215#note-8

**Pull request merged**
