### PR TITLE
octopus: mon scrub testing

### PR DESCRIPTION
**Pull request by badone**
## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Review by jdurgin — APPROVED** [review]

**Comment by badone** [comment]
jenkins test make check

**Comment by badone** [comment]
jenkins test make check

**Comment by badone** [comment]
jenkins test make check

**Comment by badone** [comment]
make check failure is caused by https://github.com/ceph/ceph/pull/38396

**Comment by smithfarm** [comment]
@badone The **run-tox-mgr-insights** test started failing (because it can't load the `six` module) recently. Do you know if a fix is already in the works?

**Comment by badone** [comment]
jenkins test make check

**Pull request merged**
