### PR TITLE
mgr/rook: fix API version and object types for recent rook changes

### PR DESCRIPTION
**Pull request by jtlayton**
The rook project recently renamed these objects and promoted the version
to v1. Make the corresponding changes in the ceph rook module.

Signed-off-by: Jeff Layton <jlayton@redhat.com>

### CODE REVIEW

**Comment by jtlayton** [comment]
This allows volume creation and removal to work properly again. Note that I did not test the objectstore changes, but it seems to follow the same pattern as the filesystem changes.

Do we expect this to ever change in the future? I wonder if we ought to make the api version and some of these type names configurable in some fashion if so.

**Comment by travisn** [comment]
correct, it should be `CephCluster(s)` everywhere it was previously `Cluster(s)`

**Comment by jtlayton** [comment]
Good catch. I made that change as well.

**Comment by sebastian-philipp** [comment]
jenkins retest this please

**Comment by sebastian-philipp** [comment]
Regarding the arm failure:
```
In file included from /home/jenkins-build/build/workspace/ceph-pull-requests-arm64/src/googletest/googletest/include/gtest/gtest.h:58:0,
                 from /home/jenkins-build/build/workspace/ceph-pull-requests-arm64/src/test/librbd/test_fixture.h:7,
                 from /home/jenkins-build/build/workspace/ceph-pull-requests-arm64/src/test/librbd/test_mock_fixture.h:7,
                 from /home/jenkins-build/build/workspace/ceph-pull-requests-arm64/src/test/librbd/managed_lock/test_mock_GetLockerRequest.cc:4:
/home/jenkins-build/build/workspace/ceph-pull-requests-arm64/src/googletest/googletest/include/gtest/internal/gtest-internal.h:1217:56: internal compiler error: Segmentation fault
   GTEST_TEST_CLASS_NAME_(test_case_name, test_name)() {}\
                                                        ^
/home/jenkins-build/build/workspace/ceph-pull-requests-arm64/src/googletest/googletest/include/gtest/internal/gtest-internal.h:1217:56: note: in definition of macro 'GTEST_TEST_'
   GTEST_TEST_CLASS_NAME_(test_case_name, test_name)() {}\
                                                        ^~
  private:\
                                                         
/home/jenkins-build/build/workspace/ceph-pull-requests-arm64/src/test/librbd/managed_lock/test_mock_GetLockerRequest.cc:81:1: note: in expansion of macro 'TEST_F'
 TEST_F(TestMockManagedLockGetLockerRequest, SuccessExclusive) {
 ^
Please submit a full bug report,
with preprocessed source if appropriate.
```

**Pull request merged**
