### PR TITLE
cmake: update FindPython3 module

### PR DESCRIPTION
**Pull request by tchaikov**
* use the ones shiped from the latest cmake.
* use the new policy to use the new find strategy.
* accomodate the vanilla FindPython3 module to Ceph by:
  - drop the `cmake_policy()` calls which sets the policy not supported by 3.16.
  - `include (FindPackageHandleStandardArgs)` without specifying the relative path.

the new FindPython3 module from CMake:

* enables us to find the recent python intepreter and development files,
* finds intepreter with the new `Python_FIND_STRATEGY`. the old and default strategy always finds the most recent version with all specified name and in all locations. so, if /usr/bin/python exists, it would accept, even if it is  a symlink to python3.9 and what we want is python3.6. while the new policy stops at the one which satisfies the constraints. simpler this way and less error prone.

Fixes: https://tracker.ceph.com/issues/62428

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by tchaikov** [comment]
tested using
```console
$ which python
/usr/bin/python
$ python -V
Python 3.9.13
$ cmake -DWITH_PYTHON3=3.6 -GNinja -Bbuild
$ ninja -C build unittest_any
$ touch CMakeLists.txt
$ ninja -C build unittest_any
```

**Review by batrick — APPROVED** [review]

**Comment by batrick** [comment]
This works for me. Thanks so much @tchaikov ! Good to see you still around. :smiley:

**Review by zmc — APPROVED** [review]
Thanks so much @tchaikov!

**Comment by batrick** [comment]
@yuriw @ljflores please include this in the next RADOS run.

**Comment by tchaikov** [comment]
gentlemen, it's my pleasure.

**Comment by ljflores** [comment]
@tchaikov ubuntu focal fails from:

https://jenkins.ceph.com/job/ceph-dev-new-build/ARCH=x86_64,AVAILABLE_ARCH=x86_64,AVAILABLE_DIST=focal,DIST=focal,MACHINE_SIZE=gigantic/72080/consoleFull
```
-- crypto soname: libcrypto.so.1.1
CMake Error at /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:210 (message):
  Unknown keywords given to FIND_PACKAGE_HANDLE_STANDARD_ARGS():
  "HANDLE_VERSION_RANGE"
Call Stack (most recent call first):
  cmake/modules/FindPython/Support.cmake:3863 (find_package_handle_standard_args)
  cmake/modules/FindPython3.cmake:545 (include)
  CMakeLists.txt:519 (find_package)


-- Configuring incomplete, errors occurred!
```

Can you take a look? And let me know when this is ready to be tested again.

**Comment by ljflores** [comment]
The same failure did not occur with jammy, so it seems specific to focal. Let me know if I can help out in any way!

**Comment by tchaikov** [comment]
being tested at https://shaman.ceph.com/builds/ceph/kefu-cmake-python3/27c05edc8ef6f4b37dc5f0b38f8baff9364117d6/

**Comment by ljflores** [comment]
> being tested at https://shaman.ceph.com/builds/ceph/kefu-cmake-python3/27c05edc8ef6f4b37dc5f0b38f8baff9364117d6/

Focal passed. Centos 8 builds failed for a different reason (the latest nfs-ganesha build failed - has since been rebuilt). Adding this to a new batch!

**Pull request merged**
