### PR TITLE
squid: suites/ec-rados-plugin=jerasure-k=8-m=6-crush: roles set with overrides

### PR DESCRIPTION
**Pull request by NitzanMordhai**
backport tracker: https://tracker.ceph.com/issues/67348

---

backport of https://github.com/ceph/ceph/pull/57863
parent tracker: https://tracker.ceph.com/issues/66209

this backport was staged using ceph-backport.sh version 16.0.0.6848
find the latest version at https://github.com/ceph/ceph/blob/main/src/script/ceph-backport.sh

### CODE REVIEW

**Comment by NitzanMordhai** [comment]
jenkins test api

**Review by Matan-B — CHANGES_REQUESTED** [review]
This is not a cherry-pick of the commit mentioned. If this was intentional, can you cherry-pick all the dependencies commits as well? (Or explain the manual change in the commit).

**Comment by NitzanMordhai** [comment]
> This is not a cherry-pick of the commit mentioned. If this was intentional, can you cherry-pick all the dependencies commits as well? (Or explain the manual change in the commit).

it came from that PR that didn't got backported: https://github.com/ceph/ceph/pull/53308

**Comment by Matan-B** [comment]
> > This is not a cherry-pick of the commit mentioned. If this was intentional, can you cherry-pick all the dependencies commits as well? (Or explain the manual change in the commit).
> 
> it came from that PR that didn't got backported: #53308

Can you please cherry-pick the dependencies commits as well? Otherwise the "cherry-picked from" is not true.

**Comment by NitzanMordhai** [comment]
jenkins test make check

**Pull request closed without merging**
