### PR TITLE
osd: reject rados ops with bad PARALLELEXEC flag

### PR DESCRIPTION
**Pull request by liewegas**

### CODE REVIEW

**Comment by athanatos** [comment]
lgtm

**Comment by xiexingguo** [comment]
lgtm also

**Comment by dvanders** [comment]
Thanks. This solved our crashy osd's IRL.
+ Tested-by: CERN

**Comment by yuriw** [comment]
tested http://pulpito.ceph.com/yuriw-2016-05-25_20:42:59-rados-wip-yuri-testing-distro-basic-smithi/

**Comment by smithfarm** [comment]
@liewegas Does this fix http://tracker.ceph.com/issues/16012 ? What about backport ?

**Comment by liewegas** [comment]
yeah.  still probably needs a backport!

**Pull request merged**
