### PR TITLE
cephadm: check hostname resolution before adding host; fix /etc/hosts

### PR DESCRIPTION
**Pull request by Daniel-Pivonka**
/etc/hosts is no longer passed to containers #40223
/etc/hosts is still passed to the shell

check hostname resolution before adding host so the user can notified of name resolution problems
fix docs to remove /etc/hosts from list of resolution method
provide way to check connection without /etc/hosts passed to shell

Fixes: https://tracker.ceph.com/issues/50306
Signed-off-by: Daniel Pivonka <dpivonka@redhat.com>

### CODE REVIEW

**Comment by tchaikov** [comment]
jenkins test api

**Comment by tchaikov** [comment]
jenkins test docs

**Review by adk3798 — APPROVED** [review]

**Review by liewegas — APPROVED** [review]

**Comment by liewegas** [comment]
jenkins test docs

**Comment by liewegas** [comment]
jenkins test api

**Pull request merged**
