### PR TITLE
mgr: Expose rgw perf counters

### PR DESCRIPTION
**Pull request by b-ranto**
We are filtering rgw perf counters in mgr_module. This commit allows us
to expose perf counters to the mgr modules. This also directly exports
the rgw perf counters via prometheus module since the module calls the
get_all_perf_counters method to get all the counters and then exports them.

Signed-off-by: Boris Ranto <branto@redhat.com>

### CODE REVIEW

**Comment by b-ranto** [comment]
The following rgw perf counters are being exposed:

```
['client.rgw.node1.put_b', 'client.rgw.node1.get',
'client.rgw.node1.get_b', 'client.rgw.node1.cache_miss',
'client.rgw.node1.get_initial_lat', 'client.rgw.node1.cache_hit',
'client.rgw.node1.failed_req',
'client.rgw.node1.keystone_token_cache_hit', 'objecter.op_w',
'client.rgw.node1.qlen', 'client.rgw.node1.keystone_token_cache_miss',
'objecter.op_r', 'objecter.op_active', 'objecter.op_rmw',
'client.rgw.node1.put_initial_lat', 'client.rgw.node1.qactive',
'client.rgw.node1.req', 'client.rgw.node1.put']
```

This makes me a bit worried since it makes the metrics exported by prometheus look like this:

```ceph_client_rgw_node1_get_b```

We should probably change the prefix from `client.rgw.<name>` to just `rgw`.

**Comment by b-ranto** [comment]
I have pushed the commit that should sanitize the prefix that I was talking about in my previous comment.

**Comment by cbodley** [comment]
> We should probably change the prefix from client.rgw.<name> to just rgw.

is there still a way to differentiate which radosgw instance the counters are from, so we can have separate views for each gateway?

**Comment by jcsp** [comment]
I agree that having the client name in the counter name was pretty weird!

**Comment by jcsp** [comment]
@b-ranto this probably should have gone through teuthology rados and rgw suites before merging (although it's unlikely to have broken anything)

**Comment by b-ranto** [comment]
@jcsp I did not see any needs-qa or testing label so I went ahead and merged it, sorry about that. We can run it through the suites for the back-port PR #21303 ?

**Pull request merged**
