### PR TITLE
mds: rework FSMap to avoid shared_ptrs

### PR DESCRIPTION
**Pull request by batrick**
There's zero reason to complicate the interface with shared_ptr<Filesystem> when a Filesystem's lifetime is tied to the FSMap.

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [x] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by batrick** [comment]
Blocking #51993

**Comment by vshankar** [comment]
@mchangir I assigned this to you for review and tests. PTAL.

**Comment by batrick** [comment]
jenkins test windows

**Comment by batrick** [comment]
jenkins test make check arm64

**Comment by vshankar** [comment]
Building now: https://shaman.ceph.com/builds/ceph/wip-vshankar-testing-20230824.045828/

Test runs in ~2h.

**Comment by vshankar** [comment]
https://pulpito.ceph.com/vshankar-2023-08-24_07:29:19-fs-wip-vshankar-testing-20230824.045828-testing-default-smithi/

**Comment by vshankar** [comment]
> https://pulpito.ceph.com/vshankar-2023-08-24_07:29:19-fs-wip-vshankar-testing-20230824.045828-testing-default-smithi/

Run looks good. Preparing the run wiki and will merge soon.

**Review by vshankar — APPROVED** [review]
https://tracker.ceph.com/projects/cephfs/wiki/Main#31-Aug-2023

**Comment by rishabh-d-dave** [comment]
PR #51942 will be backport. If this PR is backported, commit 8e39a00ed184838e16f1114bcfe3d362bc88a012 needs to be backported along so that the build for the branch for which backport is being done doesn't break.

**Comment by batrick** [comment]
> PR #51942 will be backported. And the combination of this PR with PR #51942 will break the branch. Therefore, if this PR is backported, commit [8e39a00](https://github.com/ceph/ceph/commit/8e39a00ed184838e16f1114bcfe3d362bc88a012) needs to be backported along so that the build for the branch for which backport is being done doesn't break.

I have no plans to backport this cleanup.

**Pull request merged**
