### PR TITLE
mgr/dashboard: Update translations

### PR DESCRIPTION
**Pull request by Exotelis**
Updates the Czech, German, Spanish, French, Indonesian, Polish, Portuguese (Portugal) and Chinese (simplified) translation
Adds the English, Italian, Japanese, Portuguese (Brazil) and Chinese (traditional) translation

Fixes: http://tracker.ceph.com/issues/39701
Signed-off-by: Sebastian Krah <skrah@suse.com>

- [X] References tracker ticket
- [X] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by tspmelo** [comment]
I think we had a discussion in IRC regarding Portuguese translations and we concluded that PT-PT and PT-BR are too similar to justify having both. 
I think since we have real translator for PT-BR that should be the language that will be used.
PT-PT should be removed.

**Comment by Exotelis** [comment]
> I think we had a discussion in IRC regarding Portuguese translations and we concluded that PT-PT and PT-BR are too similar to justify having both.
> I think since we have real translator for PT-BR that should be the language that will be used.
> PT-PT should be removed.

Good point, I'm going to remove it from transifex.

**Comment by Exotelis** [comment]
jenkins test make check

**Comment by tspmelo** [comment]
`messages.pt-PT.xlf` can be removed.

**Comment by callithea** [comment]
jenkins test make check

**Comment by tspmelo** [comment]
jenkins test make check

**Comment by LenzGr** [comment]
jenkins test make check

**Pull request merged**
