### PR TITLE
src,cmake: define BOOST_ASIO_USE_TS_EXECUTOR_AS_DEFAULT for Boost.Asio users and cleanups

### PR DESCRIPTION
**Pull request by tchaikov**
## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Review by cbodley — APPROVED** [review]

**Review by dillaman — APPROVED** [review]
lgtm

**Review by adamemerson — APPROVED** [review]

**Comment by tchaikov** [comment]
https://pulpito.ceph.com/kchai-2020-11-26_05:04:35-rados-wip-kefu-testing-2020-11-26-1029-distro-basic-smithi/

**Comment by Keruspe** [comment]
Could this be backported to nautilus?

**Comment by tchaikov** [comment]
@Keruspe you mean "cmake: define BOOST_ASIO_USE_TS_EXECUTOR_AS_DEFAULT for Boost.Asio users", right? in that case, i can prepare a backport for it.

**Comment by Keruspe** [comment]
I guess, yeah. What's necessary to build with boost 1.74

**Comment by tchaikov** [comment]
- nautilus backport : #38760
- octopus backport : #38759

**Pull request merged**
