### PR TITLE
osd: Revert use of dmclock message feature bit since not yet finalized

### PR DESCRIPTION
**Pull request by ivancich**
osd: Revert use of dmclock message feature bit since not yet finalized

Because the updated use of dmclock is not yet finalized and the
unfinished functionality uses a valuable messaging feature bit that we
don't want to waste, we're removing it for the mimic release.

Reverts most of the following commits for mimic:

  de8110ebb39401d3e09cb871f843776421ccd56f
  739d7e462f3a03c4e188fcfa48eb05c0063970c9
  2361e9c790306e789393323ef349d8b4a20bc70d
  9b702cf8fc2ff881ca16edc78874f2118a2e4641

Signed-off-by: J. Eric Ivancich <ivancich@redhat.com>

### CODE REVIEW

**Comment by ivancich** [comment]
Replaces https://github.com/ceph/ceph/pull/21355, which was inadvertently closed.

**Comment by tchaikov** [comment]
@ivancich could you rebase your PR against master? to be specific, your change conflicts with 6e90be1ac93, which was merged into master already.

**Comment by ivancich** [comment]
@tchaikov: My understanding was that this was for mimic and therefore it is based on the current mimic branch. I'm happy to move it to master as well. But should that be a separate PR?

**Comment by tchaikov** [comment]
@ivancich ahh, my apologies! was trying to apply your changes to master. and i didn't realize that you are targeting mimic, as mimic was one week away 3 days before.

so i think the changes aiming mimic should be still targeting master, am i right? also quite a few PRs labeled mimic are targeting master branch.

**Comment by liewegas** [comment]
sync up mimic to master to avoid some confusion, hopefully!

**Comment by ivancich** [comment]
I just changed target to master and I rebased the branch on master and resolved the conflict.

**Comment by ivancich** [comment]
jenkins test docs

**Comment by tchaikov** [comment]
- http://pulpito.ceph.com/kchai-2018-04-14_03:18:44-rados-wip-kefu-testing-2018-04-14-0918-distro-basic-mira/
- http://pulpito.ceph.com/kchai-2018-04-15_01:40:50-rados-wip-kefu-testing-2018-04-14-0918-distro-basic-smithi/
- http://pulpito.ceph.com/kchai-2018-04-15_13:37:16-rados-wip-kefu-testing-2018-04-14-2138-distro-basic-mira/

the failure is addressed by #21433

**Comment by tchaikov** [comment]
retest this please.

**Pull request merged**
