### PR TITLE
Revert "reef: qa: add support/qa for cephfs-shell on CentOS 9 / RHEL9"

### PR DESCRIPTION
**Pull request by vshankar**
Reverts ceph/ceph#54865

### CODE REVIEW

**Review by mchangir — APPROVED** [review]
LGTM

https://pulpito.ceph.com/vshankar-2024-02-02_11:17:23-fs-wip-vshankar-testing1-reef-2024-02-02-1152-testing-default-smithi/
https://pulpito.ceph.com/vshankar-2024-02-01_07:00:26-fs-wip-vshankar-testing1-reef-2024-01-29-1551-reef-testing-default-smithi/

**Comment by yuriw** [comment]
@vshankar pls fix and merge 
ref: https://trello.com/c/yfAnvDKa

**Comment by vshankar** [comment]
> @vshankar pls fix and merge ref: https://trello.com/c/yfAnvDKa

Sure.

**Comment by vshankar** [comment]
fixed and updated.

**Comment by batrick** [comment]
@vshankar can you expand why this was necessary as asked here https://tracker.ceph.com/issues/63782#note-6

**Comment by vshankar** [comment]
> @vshankar can you expand why this was necessary as asked here https://tracker.ceph.com/issues/63782#note-6

Update in tracker.

**Pull request merged**
