### PR TITLE
qa: try snap format upgrade with multimds cluster

### PR DESCRIPTION
**Pull request by batrick**
http://tracker.ceph.com/issues/24002

### CODE REVIEW

**Comment by batrick** [comment]
`Reviewed-by: Patrick Donnelly <pdonnell@redhat.com>`

**Comment by batrick** [comment]
http://pulpito.ceph.com/pdonnell-2018-05-03_23:55:31-fs:upgrade-master-testing-basic-mira/

**Comment by batrick** [comment]
@smithfarm, yes I think that is the plan. (See Sage's email to ceph-devel.)

**Comment by smithfarm** [comment]
@batrick Thanks. My understanding is that these commits should be `git cherry-pick -x`'d into mimic, without any review or testing, immediately upon merging this PR. In other words, there is no need for a backporting "process" at this point, since mimic has not been declared stable.

**Pull request merged**
