### PR TITLE
jewel: CephFSVolumeClient: read-only authorization for volumes

### PR DESCRIPTION
**Pull request by Abhishekvrshny**
http://tracker.ceph.com/issues/15999

### CODE REVIEW

**Comment by Abhishekvrshny** [comment]
test this please

**Comment by ajarr** [comment]
tests are here, https://github.com/ceph/ceph-qa-suite/pull/1041

**Comment by ajarr** [comment]
@Abhishekvrshny , is this a note to the release team, "test this please", or is this something that I need to do?

**Comment by jcsp** [comment]
@ajarr it's a (rather confusing) command syntax that is consumed by a (jenkins?) bot somewhere

**Comment by ajarr** [comment]
@Abhishekvrshny , the commit has been merged as part of https://github.com/ceph/ceph/pull/10453
This PR can be closed.

**Pull request closed without merging**
