### PR TITLE
Wip rgw role as owner

### PR DESCRIPTION
**Pull request by pritha-srivastava**
## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by pritha-srivastava** [comment]
Output of radosgw-admin stats looks like following for a bucket created by a federated user:
{
        "bucket": "my-bucket-1",
        "num_shards": 11,
        "tenant": "",
        "zonegroup": "4dd4c2db-03ae-4f98-b407-e26c5e4740ec",
        "placement_rule": "default-placement",
        "explicit_placement": {
            "data_pool": "",
            "data_extra_pool": "",
            "index_pool": ""
        },
        "id": "0ad7bdf8-3b16-4fbc-bfd5-d4d0c09da628.4137.2",
        "marker": "0ad7bdf8-3b16-4fbc-bfd5-d4d0c09da628.4137.2",
        "index_type": "Normal",
        "owner": "S3Access",
        "is_owner_role": true,
        "federated_user_name": "4ecc89ca-783e-481f-9bda-aecae1df58d7",
        "ver": "0#1,1#1,2#2,3#1,4#2,5#1,6#1,7#1,8#1,9#1,10#1",
        "master_ver": "0#0,1#0,2#0,3#0,4#0,5#0,6#0,7#0,8#0,9#0,10#0",
        "mtime": "2020-06-10T04:19:51.589079Z",
        "creation_time": "2020-06-10T04:19:51.317350Z",
        "max_marker": "0#,1#,2#,3#,4#,5#,6#,7#,8#,9#,10#",
        "usage": {
            "rgw.main": {
                "size": 2097152,
                "size_actual": 2097152,
                "size_utilized": 2097152,
                "size_kb": 2048,
                "size_kb_actual": 2048,
                "size_kb_utilized": 2048,
                "num_objects": 2
            }
        },
        "bucket_quota": {
            "enabled": false,
            "check_on_raw": false,
            "max_size": -1,
            "max_size_kb": 0,
            "max_objects": -1
        }
    }

**Comment by mattbenjamin** [comment]
@adamemerson what are your thoughts?

**Comment by adamemerson** [comment]
Looks good and straightforward so far.

**Comment by mattbenjamin** [comment]
pritha is going to add some remarks to guide further discussion;  open questions include, if we go forward with role-as-owner, will not quota-enforcement be possible only for the role?  this might well be a show-stopper, let's discuss.  In a conversation a couple of months ago, @cbodley expressed concerns, possibly for more reasons, and suggested that he preferred continuing with 'shadow users.'  In discussion today, Pritha and I agreed that if we go the shadow user route, we should consider reworking that concept.  I'm inclined to say we should have namespacing for them, maybe even explicit "realms" that are created w/admin commands and then linked to the auth setup explicitly.  thoughts?

**Comment by pritha-srivastava** [comment]
> pritha is going to add some remarks to guide further discussion; open questions include, if we go forward with role-as-owner, will not quota-enforcement be possible only for the role? this might well be a show-stopper, let's discuss. In a conversation a couple of months ago, @cbodley expressed concerns, possibly for more reasons, and suggested that he preferred continuing with 'shadow users.' In discussion today, Pritha and I agreed that if we go the shadow user route, we should consider reworking that concept. I'm inclined to say we should have namespacing for them, maybe even explicit "realms" that are created w/admin commands and then linked to the auth setup explicitly. thoughts? @adamemerson

I have tried to cover all the commands/ apis that need to be changed to accomodate 'role as a owner' in case of federated users. But it will be helpful if someone can take a look and see whether I have missed out any command/ api. Matt has already pointed out that user quota is one area which may not be addressed by 'role as owner'.

**Pull request closed without merging**
