### PR TITLE
pacific: mgr/snap_schedule: fix concurrent db usage

### PR DESCRIPTION
**Pull request by mchangir**
Serialize DB Connection usage for db transactions.

Fixes: https://tracker.ceph.com/issues/53760
Signed-off-by: Milind Changire <mchangir@redhat.com>

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [x] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by mchangir** [comment]
I'll be running a 5 job teuthoogy job run to validate the changes done here.
Please wait for the job completion link.

**Comment by mchangir** [comment]
@vshankar [Teuthology run for this PR executed with `--filter snap-schedule`](https://pulpito.ceph.com/mchangir-2022-03-01_19:18:39-fs-wip-mchangir-pacific-mgr-snap_schedule-fix-condurrent-db-usage-distro-default-smithi/)

3 of 8 runs failed with known but unrelated issue:

    cluster [WRN] Health check failed: Reduced data availability: 2 pgs peering (PG_AVAILABILITY)" in cluster log

I've also verified in all `teuthology.log` that all snap-schedule tests have passed in this set of runs.

**Comment by vshankar** [comment]
jenkins test make check

**Review by vshankar — APPROVED** [review]

**Comment by yuriw** [comment]
jenkins test make check

**Comment by yuriw** [comment]
jenkins test make check

**Comment by djgalloway** [comment]
`make check` looks like either a legitimate failure or that test needs to be fixed because I see that test fail often.

```
mypy create: /home/jenkins-build/build/workspace/ceph-pull-requests/src/pybind/mgr/.tox/mypy
mypy installdeps: cython, -rrequirements.txt, mypy==0.790
WARNING: Discarding $PYTHONPATH from environment, to override specify PYTHONPATH in 'passenv' in your configuration.
mypy installed: attrs==21.4.0,cachetools==5.0.0,-e git+https://github.com/ceph/ceph.git@e1c5d5cc341e1313ec06ea11ddae8ee9bf6fcbed#egg=ceph&subdirectory=src/python-common,certifi==2021.10.8,cffi==1.15.0,charset-normalizer==2.0.12,coverage==6.3.2,cryptography==36.0.2,Cython==0.29.28,execnet==1.9.0,google-auth==2.6.2,idna==3.3,iniconfig==1.1.1,Jinja2==3.1.1,kubernetes==23.3.0,MarkupSafe==2.1.1,mypy==0.790,mypy-extensions==0.4.3,oauthlib==3.2.0,packaging==21.3,pluggy==1.0.0,prettytable==3.2.0,py==1.11.0,pyasn1==0.4.8,pyasn1-modules==0.2.8,pycparser==2.21,pyfakefs==4.5.6,pyOpenSSL==22.0.0,pyparsing==3.0.7,pytest==7.1.1,pytest-cov==2.7.1,python-dateutil==2.8.2,PyYAML==6.0,remoto==1.2.1,requests==2.27.1,requests-mock==1.9.3,requests-oauthlib==1.3.1,rsa==4.8,six==1.16.0,tomli==2.0.1,typed-ast==1.4.3,typing_extensions==4.1.1,urllib3==1.26.9,wcwidth==0.2.5,websocket-client==1.3.2
mypy run-test-pre: PYTHONHASHSEED='1815123030'
mypy run-test: commands[0] | mypy --config-file=../../mypy.ini -m cephadm -m dashboard -m devicehealth -m mds_autoscaler -m mgr_module -m mgr_util -m mirroring -m nfs -m orchestrator -m pg_autoscaler -m progress -m prometheus -m rook -m snap_schedule -m stats -m test_orchestrator -m volumes
snap_schedule/module.py:10: note: In module imported here,
snap_schedule/__init__.py:9: note: ... from here:
snap_schedule/fs/schedule_client.py: note: In member "store_schedule_db" of class "SnapSchedClient":
snap_schedule/fs/schedule_client.py:182: error: Name 'CephfsConnectionException' is not defined
snap_schedule/fs/schedule_client.py:183: error: Name 'errno' is not defined
snap_schedule/fs/schedule_client.py:187: error: "DBInfo" has no attribute "__enter__"
snap_schedule/fs/schedule_client.py:187: error: "DBInfo" has no attribute "__exit__"
snap_schedule/fs/schedule_client.py:188: error: "DBInfo" has no attribute "iterdump"
snap_schedule/__init__.py:9: note: In module imported here:
snap_schedule/module.py: note: In member "snap_schedule_get" of class "Module":
snap_schedule/module.py:78: error: Argument 2 to "get_snap_schedules" of "SnapSchedClient" has incompatible type "Optional[str]"; expected "str"
snap_schedule/module.py: note: In member "snap_schedule_list" of class "Module":
snap_schedule/module.py:97: error: Argument 3 to "list_snap_schedules" of "SnapSchedClient" has incompatible type "Optional[bool]"; expected "bool"
Found 7 errors in 2 files (checked 17 source files)
ERROR: InvocationError for command /home/jenkins-build/build/workspace/ceph-pull-requests/src/pybind/mgr/.tox/mypy/bin/mypy --config-file=../../mypy.ini -m cephadm -m dashboard -m devicehealth -m mds_autoscaler -m mgr_module -m mgr_util -m mirroring -m nfs -m orchestrator -m pg_autoscaler -m progress -m prometheus -m rook -m snap_schedule -m stats -m test_orchestrator -m volumes (exited with code 1)
```

**Comment by yuriw** [comment]
@mchangir @vshankar this was tested and approved as part of https://trello.com/c/MptR4VKa
Please resolve and merge or send back for retesting

**Comment by mchangir** [comment]
@djgalloway @yuriw sorry about this guys
the backport had gone haywire
the last update should fix it

**Comment by mchangir** [comment]
jenkins retest this please

**Comment by yuriw** [comment]
jenkins test api

**Comment by vshankar** [comment]
superseded by https://github.com/ceph/ceph/pull/45906

**Pull request closed without merging**
