### PR TITLE
qa/workunits/rados/test_crash.sh: do not rm coredump

### PR DESCRIPTION
**Pull request by tchaikov**
they are moved away by crash module already

Signed-off-by: Kefu Chai <kchai@redhat.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by tchaikov** [comment]
http://pulpito.ceph.com/kchai-2020-01-26_14:43:29-rados-wip-kefu-testing-2020-01-26-1633-distro-basic-smithi/

**Comment by tchaikov** [comment]
this change reverts 290992e5195d8959a4d9b9f175f46f41aedbf81f

**Comment by liewegas** [comment]
What do you mean the core files are moved away by the crash module?  You mean by the test?

**Comment by tchaikov** [comment]
@liewegas i was trying to understand why the crashdumps were not found in `$TESTDIR/archive/coredump/`. but they are in `remote/*/crash/posted/`, like
```
kchai@teuthology:/a/kchai-2020-01-26_14:43:29-rados-wip-kefu-testing-2020-01-26-1633-distro-basic-smithi/4709310$ ls -l remote/*/crash/posted/*
remote/smithi204/crash/posted/2020-01-26T15:01:51.583638Z_0df6b68a-048e-46b5-9bb9-ff73b18782fd:
total 1678
-rw-rw-r-- 1 teuthworker teuthworker       0 Jan 26 15:03 done
-rw-rw-r-- 1 teuthworker teuthworker 1716770 Jan 26 15:03 log
-rw-rw-r-- 1 teuthworker teuthworker    1001 Jan 26 15:03 meta

remote/smithi204/crash/posted/2020-01-26T15:01:51.585200Z_580b1072-9957-4e3e-982f-c4b6fc5a7198:
total 1748
-rw-rw-r-- 1 teuthworker teuthworker       0 Jan 26 15:03 done
-rw-rw-r-- 1 teuthworker teuthworker 1788612 Jan 26 15:03 log
-rw-rw-r-- 1 teuthworker teuthworker    1001 Jan 26 15:03 meta

remote/smithi204/crash/posted/2020-01-26T15:01:51.585371Z_a024afa3-2c77-4de7-a4d2-715bd7f7cc67:
total 1640
-rw-rw-r-- 1 teuthworker teuthworker       0 Jan 26 15:03 done
-rw-rw-r-- 1 teuthworker teuthworker 1678013 Jan 26 15:03 log
-rw-rw-r-- 1 teuthworker teuthworker    1001 Jan 26 15:03 meta
```

so i think it's the mgr "crash" module who collected them.

**Comment by tchaikov** [comment]
this change should address the failure referenced by https://tracker.ceph.com/issues/43653#note-3

**Comment by liewegas** [comment]
the crash records are there, but we don't do anything special with the core dumps themselves

**Comment by liewegas** [comment]
I'm not sure why the rm command is failing.. is it because of escaping or because there are no core files there?  If there aren't core files, maybe something is wrong with the test environment (we should be producing cores!)

**Comment by tchaikov** [comment]
> because there are no core files there?

yeah, that's my theory. and the fix verified it.

**Comment by liewegas** [comment]
maybe put a find command before the rm and lets merge that?  i suspect the failure depends on the distro or something.  i just fixed a problem with core_pattern not getting set on el8 a week or so back

**Comment by tchaikov** [comment]
@liewegas done. being tested at http://pulpito.ceph.com/kchai-2020-01-26_17:21:41-rados-wip-kefu-testing-2020-01-26-1633-distro-basic-smithi/

**Pull request merged**
