### PR TITLE
pacific: do not evict clients if OSDs are laggy

### PR DESCRIPTION
**Pull request by dparmar18**
backport tracker: https://tracker.ceph.com/issues/61841
parent tracker: https://tracker.ceph.com/issues/58023
backport of https://github.com/ceph/ceph/pull/49971

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Review by lxbsz — APPROVED** [review]
LGTM.

**Comment by sseshasa** [comment]
@dparmar18 The teuthology test https://pulpito.ceph.com/yuriw-2023-07-27_22:37:12-rados-wip-yuri6-testing-2023-07-24-0819-pacific-distro-default-smithi/7354866 failed due to
the MDS_CLIENTS_LAGGY warning. Should this test add the warning to the ignore list? If so, the PR may need additional changes. Please take a look.

I will remove the relevant test tag and 'needs-qa' label for now. Please add it back once the PR is ready for a re-test.

**Comment by sseshasa** [comment]
> @dparmar18 The teuthology test https://pulpito.ceph.com/yuriw-2023-07-27_22:37:12-rados-wip-yuri6-testing-2023-07-24-0819-pacific-distro-default-smithi/7354866 failed due to the MDS_CLIENTS_LAGGY warning. Should this test add the warning to the ignore list? If so, the PR may need additional changes. Please take a look.
> 
> I will remove the relevant test tag and 'needs-qa' label for now. Please add the 'needs-qa' label back once the PR is ready for a re-test.

@dparmar18 Please note the above failure and see if it needs to be addressed. Once you confirm, this PR can be included in the next QA round. Thanks!

**Comment by dparmar18** [comment]
> 



> > @dparmar18 The teuthology test https://pulpito.ceph.com/yuriw-2023-07-27_22:37:12-rados-wip-yuri6-testing-2023-07-24-0819-pacific-distro-default-smithi/7354866 failed due to the MDS_CLIENTS_LAGGY warning. Should this test add the warning to the ignore list? If so, the PR may need additional changes. Please take a look.
> > I will remove the relevant test tag and 'needs-qa' label for now. Please add the 'needs-qa' label back once the PR is ready for a re-test.
> 
> @dparmar18 Please note the above failure and see if it needs to be addressed. Once you confirm, this PR can be included in the next QA round. Thanks!

Hey @sseshasa my bad, i totally lost your comment among other PRs. I think @ljflores had a PR that got merged for it https://github.com/ceph/ceph/pull/52342, seems like it needs to be backoorted

**Comment by sseshasa** [comment]
> Hey @sseshasa my bad, i totally lost your comment among other PRs. I think @ljflores had a PR that got merged for it #52342, seems like it needs to be backported
@dparmar18 Thanks! @ljflores We can include the backport of #52342 in the batch and run the QA batch.

**Comment by vshankar** [comment]
jenkins test api

**Comment by ljflores** [comment]
@dparmar18 make sure to include https://github.com/ceph/ceph/pull/52342 in the backport

**Comment by ljflores** [comment]
@dparmar18 https://github.com/ceph/ceph/pull/53007

**Comment by ljflores** [comment]
Rados approved: https://tracker.ceph.com/projects/rados/wiki/PACIFIC#httpstrellocomc8HALLv9T1813-wip-yuri6-testing-2023-08-03-0807-pacific-old-wip-yuri6-testing-2023-07-24-0819-pacific2-old-wip-yuri6-testing-2023-07-24-0819-p

**Comment by dparmar18** [comment]
> @dparmar18 #53007
> 
> You may in fact want to combine that commit with this PR since it will help the API check pass. If you decide to go that route, you can `cherry-pick -x` my commit on this PR and close the backport PR.

yeah makes sense, I'll cherry pick it here and close that one. Thanks @ljflores

**Comment by ljflores** [comment]
Rados approved: https://trello.com/c/qRJogcXu/1827-wip-yuri2-testing-2023-08-16-1142-pacific

**Comment by batrick** [comment]
> > @dparmar18 #53007
> > You may in fact want to combine that commit with this PR since it will help the API check pass. If you decide to go that route, you can `cherry-pick -x` my commit on this PR and close the backport PR.
> 
> yeah makes sense, I'll cherry pick it here and close that one. Thanks @ljflores

In the future, update your PR description when you include more fixes.

**Review by batrick — APPROVED** [review]
https://tracker.ceph.com/projects/cephfs/wiki/Pacific#2023-August-16-2

**Comment by dparmar18** [comment]
> > > @dparmar18 #53007
> > > You may in fact want to combine that commit with this PR since it will help the API check pass. If you decide to go that route, you can `cherry-pick -x` my commit on this PR and close the backport PR.
> > 
> > 
> > yeah makes sense, I'll cherry pick it here and close that one. Thanks @ljflores
> 
> In the future, update your PR description when you include more fixes.

ACK

**Pull request merged**
