### PR TITLE
mimic: common: data race in OutputDataSocket

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/40268

### CODE REVIEW

**Comment by smithfarm** [comment]
```
In file included from /home/jenkins-build/build/workspace/ceph-pull-requests/src/common/convenience.h:15,
                 from /home/jenkins-build/build/workspace/ceph-pull-requests/src/include/encoding.h:35,
                 from /home/jenkins-build/build/workspace/ceph-pull-requests/src/include/uuid.h:8,
                 from /home/jenkins-build/build/workspace/ceph-pull-requests/src/include/types.h:21,
                 from /home/jenkins-build/build/workspace/ceph-pull-requests/src/msg/msg_types.h:21,
                 from /home/jenkins-build/build/workspace/ceph-pull-requests/src/common/entity_name.h:20,
                 from /home/jenkins-build/build/workspace/ceph-pull-requests/src/common/config.h:21,
                 from /home/jenkins-build/build/workspace/ceph-pull-requests/src/common/dout.h:22,
                 from /home/jenkins-build/build/workspace/ceph-pull-requests/src/include/Context.h:19,
                 from /home/jenkins-build/build/workspace/ceph-pull-requests/src/common/Cond.h:19,
                 from /home/jenkins-build/build/workspace/ceph-pull-requests/src/common/OutputDataSocket.h:18,
                 from /home/jenkins-build/build/workspace/ceph-pull-requests/src/common/OutputDataSocket.cc:15:
/usr/include/c++/8/mutex: In instantiation of 'std::scoped_lock<_Mutex>::scoped_lock(std::scoped_lock<_Mutex>::mutex_type&) [with _Mutex = Mutex; std::scoped_lock<_Mutex>::mutex_type = Mutex]':
/home/jenkins-build/build/workspace/ceph-pull-requests/src/common/OutputDataSocket.cc:305:35:   required from here
/usr/include/c++/8/mutex:610:19: error: 'using mutex_type = class Mutex' {aka 'class Mutex'} has no member named 'lock'; did you mean 'nlock'?
       { _M_device.lock(); }
         ~~~~~~~~~~^~~~
         nlock
/usr/include/c++/8/mutex: In instantiation of 'std::scoped_lock<_Mutex>::~scoped_lock() [with _Mutex = Mutex]':
/home/jenkins-build/build/workspace/ceph-pull-requests/src/common/OutputDataSocket.cc:305:35:   required from here
/usr/include/c++/8/mutex:617:19: error: 'using mutex_type = class Mutex' {aka 'class Mutex'} has no member named 'unlock'; did you mean 'nlock'?
       { _M_device.unlock(); }
         ~~~~~~~~~~^~~~~~
         nlock
src/CMakeFiles/common-objs.dir/build.make:351: recipe for target 'src/CMakeFiles/common-objs.dir/common/OutputDataSocket.cc.o' failed
make[3]: *** [src/CMakeFiles/common-objs.dir/common/OutputDataSocket.cc.o] Error 1
```

**Comment by smithfarm** [comment]
So, no `std::scoped_lock` in mimic. What to do?

**Comment by smithfarm** [comment]
```
157/157 Test   #3: test_objectstore_memstore.sh ............***Timeout 3600.01 sec
```

**Comment by smithfarm** [comment]
jenkins test make check

**Comment by yuriw** [comment]
[wip-yuri6-testing-2019-07-23-2000-mimic](https://trello.com/c/PkgNbUWw/673-wip-yuri6-testing-2019-07-23-2000-mimic)

**Pull request merged**
