### PR TITLE
rgw: delegate out buffering and chunking in the FastCGI front-end.

### PR DESCRIPTION
**Pull request by rzarzynski**

### CODE REVIEW

**Comment by liewegas** [comment]
is this obsolete now?

**Comment by mattbenjamin** [comment]
I think this is worth revisiting

**Comment by rzarzynski** [comment]
Well, closed this one under assumption the FastCGI front-end becomes less and less important over time.

**Comment by mattbenjamin** [comment]
It is, but we have some downstream users, it turns out.  If we have to bring FastCGI back (not having module drivers), is this still relevant?

**Comment by liewegas** [comment]
IMO anything relating to fastcgi is the "wrong kind of work" (as federico puts it).  Unless it is *absolutely* necessary let's focus our efforts on work with future value.

**Pull request closed without merging**
