### PR TITLE
[DNM] add socket backlog for fastcgi

### PR DESCRIPTION
**Pull request by diluga**
http://tracker.ceph.com/issues/16436

global option in ceph.conf for socket backlog for fastcgi

### CODE REVIEW

**Comment by smithfarm** [comment]
@diluga How was this patch created? Typically, we require patches to released, stable versions (like hammer) to be cherry-picked from patches that are in the `master` branch.

**Comment by smithfarm** [comment]
Changelog:
* added tracker xref to PR description

**Comment by diluga** [comment]
The default rgw socket backlog = 1024，in some case，this number is too small，so i create a patch to fix it，maybe useful to someone.and it needs to be backported to hammer(or hammer 0.94.8)

http://tracker.ceph.com/issues/16436 (hammer backport)
http://tracker.ceph.com/issues/16406 (master)

**Comment by smithfarm** [comment]
@diluga Thanks for clarifying. Once you have squashed the commits in your master PR, please re-do this hammer PR using "git cherry-pick -x".

**Comment by smithfarm** [comment]
Changelog:
* marked DNM until master PR is merged and commit is fixed to include cherry-pick message

@diluga Please wait until the master PR has been merged and then re-do this commit using "git cherry-pick -x $SHA1_OF_MASTER_COMMIT" Thanks!

**Comment by diluga** [comment]
rename   rgw_socket_backlog - > rgw_fcgi_socket_backlog,commit again.

**Comment by smithfarm** [comment]
@diluga Instead of merge, look into rebase. After rebasing, force-push ("git push -f") your wip branch and the PR will be automagically updated.

**Comment by diluga** [comment]
sorry，i re commit with :  https://github.com/ceph/ceph/pull/9912

**Pull request closed without merging**
