### PR TITLE
rgw: Adding documentation for Roles.

### PR DESCRIPTION
**Pull request by pritha-srivastava**
Signed-off-by: Pritha Srivastava <prsrivas@redhat.com>

- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by LenzGr** [comment]
jenkins render docs

**Comment by LenzGr** [comment]
The rendered doc is here: http://docs.ceph.com/ceph-prs/24714/radosgw/role/

**Comment by pritha-srivastava** [comment]
@mattbenjamin @LenzGr I have created a separate PR for the code changes.

**Comment by mattbenjamin** [comment]
jenkins retest this please

**Comment by pritha-srivastava** [comment]
@mattbenjamin : Can this be merged? I have taken care of all review comments.

**Pull request merged**
