### PR TITLE
librados: add NOREUSE fadvise hint

### PR DESCRIPTION
**Pull request by liewegas**

### CODE REVIEW

**Comment by liewegas** [comment]
for the filestore patch, we should probably map it to DONTNEED for now? or a no-op?  not sure... :/

**Comment by majianpeng** [comment]
@liewegas . In my option. If there is only one used he can use DONTCACHE. If there are much user, he should use NOREUSE(his aim is don't cache anydata but don't effect others).
So i think for fs it's a no-op is better.

**Comment by liewegas** [comment]
Yeah, I think you're right.  Will drop the second patch!

**Comment by liewegas** [comment]
...er, actually, I'll leave the second patch (which is a no-op on Linux), so that it will work if/when it is implemented properly.

**Comment by liewegas** [comment]
.. or not.  using an api that is a no-op today but may do some unknown magic later is dangerous.   dropping the patch.

**Pull request merged**
