### PR TITLE
librados,libradosstriper,test: migrate atomic_t to std::atomic (baragon)

### PR DESCRIPTION
**Pull request by chardan**
refer-to: https://github.com/ceph/ceph/pull/14655

### CODE REVIEW

**Comment by chardan** [comment]
@ceph-jenkins retest

**Comment by chardan** [comment]
@ceph-jenkins jenkins test this please

**Comment by liewegas** [comment]
Does not compile due to system assert.h clobbering our assert.h.  Need to tweak #include order..

**Comment by chardan** [comment]
@ceph-jenkins jenkins retest this please

**Comment by chardan** [comment]
Jenkins re-test this please

**Comment by chardan** [comment]
@liewegas BTW, I didn't notice that you had changed the title and I thought I'd just forgotten-- didn't mean to gratuitously change it back. Would you prefer I remove kaiju references?

**Comment by chardan** [comment]
Jenkins re-test this please

**Comment by liewegas** [comment]
I can't tell what the names mean or signify.  The important part is the prefix each pr with the subsystem that it affects.

**Comment by liewegas** [comment]
http://pulpito.ceph.com/sage-2017-05-25_17:58:50-rados-wip-sage-testing2---basic-smithi/

**Pull request merged**
