### PR TITLE
squid: rgw: replicate v2 topic/notification metadata

### PR DESCRIPTION
**Pull request by cbodley**
backport tracker: https://tracker.ceph.com/issues/64818
parent tracker: https://tracker.ceph.com/issues/50078

backports of:
- [x] https://github.com/ceph/ceph/pull/55688
- [x] https://github.com/ceph/ceph/pull/55657
- [x] https://github.com/ceph/ceph/pull/56005
- [x] https://github.com/ceph/ceph/pull/56179
- [x] https://github.com/ceph/ceph/pull/55795
- [x] https://github.com/ceph/ceph/pull/55214
- [x] https://github.com/ceph/ceph/pull/56712 for https://tracker.ceph.com/issues/64571
- [x] https://github.com/ceph/ceph/pull/55663 for https://tracker.ceph.com/issues/63909

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Comment by yuriw** [comment]
Tested ref: https://tracker.ceph.com/issues/64973

**Comment by ljflores** [comment]
Rados approved: https://tracker.ceph.com/projects/rados/wiki/SQUID#httpstrackercephcomissues64973

**Comment by cbodley** [comment]
documented a minor conflict with the cherry-pick of "RGW/Rados: Migrate topics to data path v2" due to changes from https://github.com/ceph/ceph/pull/55795

**Comment by cbodley** [comment]
@kchheda3 @yuvalif i included the commits from https://github.com/ceph/ceph/pull/55795, and was able to re-cherry-pick https://github.com/ceph/ceph/pull/55214 with no conflicts

**Comment by cbodley** [comment]
cherry-picked fixes from https://github.com/ceph/ceph/pull/55663 and rebased on latest squid

**Comment by cbodley** [comment]
https://pulpito.ceph.com/cbodley-2024-04-11_21:30:33-rgw-wip-64818-squid-distro-default-smithi/ looks clean except for a test_others crash (https://tracker.ceph.com/issues/65337)

**Comment by cbodley** [comment]
@yuvalif i chose not to treat https://tracker.ceph.com/issues/65337 as a blocker for merge, so i can get the accounts feature to squid in time for the release candidate. but i do plan to treat https://tracker.ceph.com/issues/65337 as a blocker for final release. does that make sense?

**Review by adamemerson — APPROVED** [review]

**Pull request merged**
