### PR TITLE
doc/cephadm: Fix prompts in host-management.rst

### PR DESCRIPTION
**Pull request by bluikko**
Fix indentation on commands after prompt.
Also separate command output block from the command itself to avoid prefixing it with the prompt; and remove double prompt from the command.

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [x] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [x] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Review by zdover23 — APPROVED** [review]

**Comment by zdover23** [comment]
@bluikko: Are you able to squash these two commits into one?

**Comment by bluikko** [comment]
@zdover23 Will squash the merges soon, thanks.

**Review by adk3798 — APPROVED** [review]

**Comment by zdover23** [comment]
https://github.com/ceph/ceph/pull/49900 - Quincy backport
https://github.com/ceph/ceph/pull/49901 - Pacific backport

**Comment by adk3798** [comment]
> #49900 - Quincy backport #49901 - Pacific backport

@zdover23 the `--detail` flag on on `ceph orch host ls` was only added in https://github.com/ceph/ceph/pull/49189 and isn't actually in quincy or pacific,  (will probably be backported to quincy at some point, but probably never to pacific) so that part of this PR needs to be left out of those backports.

**Comment by zdover23** [comment]
@adk3798 - Roger that, Adam. I've cancelled the backports. Thanks for letting me know.

**Comment by bluikko** [comment]
I had noticed that the version in main was different from even quincy docs. If I see this situation in the future should I note it somewhere?

**Comment by zdover23** [comment]
> I had noticed that the version in main was different from even quincy docs. If I see this situation in the future should I note it somewhere?

@bluikko: That just means that the version in main hasn't been backported to Quincy (which in this situation is because the --detail flag isn't in Quincy, but sometimes is just because the Ceph docs are vast and it takes about eighteen months to work through all of them). When you notice this in the future, you can send an email to zac.dover@proton.me and I'll keep track of the places where main doesn't match the release branches (Quincy and Pacific and their ilk are release branches).

**Pull request merged**
