### PR TITLE
mgr: handle "module.set_config(.., None)" correctly 

### PR DESCRIPTION
**Pull request by tchaikov**

### CODE REVIEW

**Comment by tchaikov** [comment]
@nrdmn could you please help review this PR?

**Comment by tchaikov** [comment]
retest this please.

**Comment by nrdmn** [comment]
@tchaikov sure I can do that this evening

**Comment by liewegas** [comment]
http://pulpito.ceph.com/sage-2017-08-03_18:16:40-rados-wip-sage-testing2-20170803-distro-basic-smithi/

**Pull request merged**
