### PR TITLE
mgr/dashboard: wait for PG unknown state to be cleared

### PR DESCRIPTION
**Pull request by s0nea**
Give the cluster some time to recover from the unknown PG state before checking if the OSD is safe to destroy.

Note: this PR needs further testing because I wasn't able to reproduce it locally.

Fixes: https://tracker.ceph.com/issues/43912
Signed-off-by: Tatjana Dehler <tdehler@suse.com>

## Checklist
- [x] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by s0nea** [comment]
jenkins test dashboard backend

**Comment by s0nea** [comment]
jenkins test dashboard backend

**Comment by s0nea** [comment]
jenkins test dashboard backend

**Comment by p-se** [comment]
jenkins test dashboard

**Comment by callithea** [comment]
jenkins test dashboard

**Comment by p-se** [comment]
jenkins test dashboard

**Comment by p-se** [comment]
@callithea is this a recurring problem?

```Executed 4 of 98 specs[31m (1 FAILED)[39m[33m (94 SKIPPED)[39m in 16 secs. 1) Images page create, edit & delete image test should create image [31m- [39m[31mFailed: No element found using locator: by.cssContainingText("select[name=pool] option", "e2e_images_pool")[39m [31m- [39m[31mExpected 1 to equal 0.[39m ```

**Comment by s0nea** [comment]
The QA test run was successful:

http://pulpito.ceph.com/tdehler-2020-02-03_15:44:04-rados:dashboard-wip-tdehler-testing-33013-32546-distro-basic-smithi/
http://pulpito.ceph.com/tdehler-2020-02-04_12:17:13-rados:dashboard-wip-tdehler-testing-32680-33013-distro-basic-smithi/
http://pulpito.ceph.com/tdehler-2020-02-05_12:35:32-rados:dashboard-wip-tdehler-testing-32546-32680-33013-distro-basic-smithi/ (I don't think the failure is related to the PR)

**Comment by bk201** [comment]
> @callithea is this a recurring problem?
> 
> `Executed 4 of 98 specs�[31m (1 FAILED)�[39m�[33m (94 SKIPPED)�[39m in 16 secs. 1) Images page create, edit & delete image test should create image �[31m- �[39m�[31mFailed: No element found using locator: by.cssContainingText("select[name=pool] option", "e2e_images_pool")�[39m �[31m- �[39m�[31mExpected 1 to equal 0.�[39m `

tracked on https://tracker.ceph.com/issues/44007

**Comment by p-se** [comment]
@liewegas does this PR (seem to) resolve the issues with QA?

**Comment by tchaikov** [comment]
- http://pulpito.ceph.com/kchai-2020-02-14_06:35:26-rados-wip-kefu-testing-2020-02-14-1112-distro-basic-smithi/
- http://pulpito.ceph.com/kchai-2020-02-15_02:54:06-rados-wip-kefu-testing-2020-02-15-0003-distro-basic-smithi/

failures are fixed by #33347 and #33348

**Comment by tchaikov** [comment]
@s0nea shall we merge this change?

**Comment by s0nea** [comment]
@tchaikov sorry for the late reply. Yes, it's ready from my side. Thank you for testing!

**Pull request merged**
