### PR TITLE
doc: mention MDS name and ID format in ceph-mds.rst

### PR DESCRIPTION
**Pull request by joscollin**
## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [x] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [x] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by joscollin** [comment]
jenkins test docs

**Comment by joscollin** [comment]
jenkins retest this please

**Comment by joscollin** [comment]
jenkins render docs

**Comment by joscollin** [comment]
jenkins retest this please

**Comment by vshankar** [comment]
IRC chat:

`<jcollin> overclk: will do that soon. By the way, -n and -i options lead to ceph-mds crash at present. global_init() crashes.`

Where does it _exactly_ crash?

**Comment by vshankar** [comment]
> @vshankar I don't know how to make the `docs/readthedocs` build successful. But these changes build successfully in my local repo (admin/build-doc).

probably rebase and update.

**Comment by joscollin** [comment]
> Where does it _exactly_ crash?

It was a misunderstanding of the defaults. There was no crash. Sorry, my mistake.

**Comment by joscollin** [comment]
> > @vshankar I don't know how to make the `docs/readthedocs` build successful. But these changes build successfully in my local repo (admin/build-doc).
> 
> probably rebase and update.

Yeah, that worked.

**Review by vshankar — APPROVED** [review]

**Pull request merged**
