### PR TITLE
rgw: Backport of datalog improvements to Pacific

### PR DESCRIPTION
**Pull request by adamemerson**
Tracker ticket at: https://tracker.ceph.com/issues/50105

### CODE REVIEW

**Comment by adamemerson** [comment]
Jenkins, run make check

**Comment by adamemerson** [comment]
Jenkins, retest this please.

**Comment by adamemerson** [comment]
Jenkins test docs

**Comment by adamemerson** [comment]
What the heck's with you, today, Jenkins?

**Comment by cbodley** [comment]
@adamemerson please cherry-pick with -x and document any 'Conflicts:' in the commit message

**Comment by adamemerson** [comment]
@cbodley Done

**Comment by adamemerson** [comment]
@cbodley http://pulpito.ceph.com/aemerson-2021-04-05_21:37:07-rgw-wip-50104-pacific-distro-basic-smithi/

**Review by cbodley — APPROVED** [review]

**Comment by cbodley** [comment]
thanks @adamemerson!

**Pull request merged**
