### PR TITLE
rgw: add missing RGWPeriod::reflect() based on new atomic update_latest_epoch()

### PR DESCRIPTION
**Pull request by cbodley**
tests of https://github.com/ceph/ceph/pull/14688 were failing because a `period update --commit` in `test_multi_period_incremental_sync()` was mistakenly removing another zone from the period. this was happening because `RGWPeriodPuller` had store the latest period without also calling `RGWPeriod::reflect()` to update the local zonegroup object. so the `zone modify --master` and `period update --commit` were operating on an old version of the zonegroup

`RGWPeriodPuller` could not safely call `RGWPeriod::reflect()`, because it couldn't determine whether it had the latest epoch of that period (calling reflect() on an older epoch would overwrite the more recent zonegroup object). this was explained by the comment `// XXX: if this is a newer epoch, we should overwrite the existing latest_epoch. but there's no way to do that atomically`

this patch set adds a new `RGWPeriod::update_latest_epoch()` to provide atomic updates to the period's latest_epoch object, which callers can use to safely determine whether to call `RGWPeriod::reflect()` and `RGWRealm::notify_new_period()`

Fixes: http://tracker.ceph.com/issues/19816
Fixes: http://tracker.ceph.com/issues/19817

### CODE REVIEW

**Comment by cbodley** [comment]
turns out this doesn't actually fix my issue in multisite-for-teuthology, but the change is still valid and passed the rgw suite: http://pulpito.ceph.com/cbodley-2017-05-02_14:01:34-rgw-wip-19817---basic-smithi/

(2 known s3test failures due to apache, the rest were valgrind failures in the mon)

**Comment by oritwas** [comment]
jenkins test this please

**Comment by cbodley** [comment]
rebased

**Comment by yuriw** [comment]
http://pulpito.ceph.com/yuriw-2017-07-13_21:26:32-rgw-wip-yuri-testing3_2017_7_14-distro-basic-smithi/

**Comment by smithfarm** [comment]
@oritwas @cbodley So this is fixing failures in the tests introduced by #14688? If that's the case, does it make sense to backport it to jewel given that #14688 is not being so backported?

**Comment by smithfarm** [comment]
I guess the answer is "yes" because the tests in #14688 found a real bug that is being addressed by this PR.

**Pull request merged**
