### PR TITLE
mimic: os/bluestore: fix collection_list ordering

### PR DESCRIPTION
**Pull request by trociny**
backport tracker: https://tracker.ceph.com/issues/47365

---

backport of https://github.com/ceph/ceph/pull/36230
parent tracker: https://tracker.ceph.com/issues/43174

this backport was staged using ceph-backport.sh version 15.1.1.389
find the latest version at https://github.com/ceph/ceph/blob/master/src/script/ceph-backport.sh

### CODE REVIEW

**Review by ifed01 — APPROVED** [review]

**Comment by smithfarm** [comment]
@aclamk @ifed01 @neha-ojha Unless there are any objections, I will go ahead and merge this without a teuthology run - as I did yesterday with #37062

**Comment by ifed01** [comment]
Honestly I think it makes a little sense to backport that complex patches to EOL branch... But on the other hand it's rather safe as it has little chances to get into production...
hence +0 to commit from my side

**Comment by smithfarm** [comment]
@trociny The luminous version of this PR - https://github.com/ceph/ceph/pull/37062 (which we recently merged) - contains an additional commit cherry-picked from #37999

Which of the following options would make most sense to you?

1. cherry-pick #37999 and merge
2. merge in current state
3. do not merge, close because mimic is EOL

**Comment by neha-ojha** [comment]
@trociny @ifed01 @smithfarm given that we have merged the luminous backport, might make sense to merge this to avoid any regressions, WDYT?

**Comment by smithfarm** [comment]
@neha-ojha Makes sense to me. I have the required permissions to merge it if needed.

**Comment by trociny** [comment]
I definitely do not have objections to merge it.

**Comment by ifed01** [comment]
> @trociny @ifed01 @smithfarm given that we have merged the luminous backport, might make sense to merge this to avoid any regressions, WDYT?

indeed, makes sense now

**Comment by ifed01** [comment]
jenkins test make check

**Comment by ifed01** [comment]
@smithfarm - the last make check status is failed, given that we might be unsafe to merge...

**Comment by smithfarm** [comment]
@ifed01 I don't think mimic make check will ever get fixed.

**Comment by ifed01** [comment]
> @ifed01 I don't think mimic make check will ever get fixed.

Ah.. you mean this build failure is unrelated to this patch. OK to merge, then..

**Pull request merged**
