### PR TITLE
tests: TEST_crush_reject_empty must not run a mon

### PR DESCRIPTION
**Pull request by dachary**
http://tracker.ceph.com/issues/12285 and http://tracker.ceph.com/issues/11975

### CODE REVIEW

**Comment by dachary** [comment]
@tchaikov it's test only, no harm done ;-)

**Comment by dachary** [comment]
the bot no longer displays the errors because it assumes make check will, backport 45d95b9 for that to happen

**Comment by tchaikov** [comment]
@dachary need to source `ceph-helpers.sh` for `run_osd()`. will prepare a pull request on top of yours tomorrow.

at least one OSD is needed, because monitor will check the crush map against `max_osd`. a zero `max_id` will disable this feature.

**Comment by dachary** [comment]
@tchaikov I'm trying to figure out why the bot does not show any output even with the VERBOSE thing. Will also include ceph-helpers.sh.

**Comment by dachary** [comment]
@tchaikov nevermind... the VERBOSE patch works, I must have done a combo of bad things to think it did not...

**Comment by dachary** [comment]
<pre>
Error EPERM: Failed to parse crushmap: error running crushmap through crushtool: (1) Operation not permitted
</pre>
this looks like an actual problem. @tchaikov what do you think ?

**Comment by tchaikov** [comment]
@dachary, turns out we need more changes to appease the tests, i pulled together a new pr on top of yours: #5208.

**Comment by dachary** [comment]
#5208 is better

**Pull request closed without merging**
