### PR TITLE
octopus: cephadm: Allow to use paths in all <_devices> drivegroup sections

### PR DESCRIPTION
**Pull request by mgfritch**
backport of #39415

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Review by jmolmo — COMMENTED** [review]
OMG!!! Is incredible how a small change in master  results in an avalanche of changes in octopus...
Do we really want/need to move this amount of code to octopus?

**Comment by idryomov** [comment]
@jmolmo Nope ;)  This was caused by a deficiency in our release process.  Now fixed.

**Comment by mgfritch** [comment]
jenkins retest this please

**Comment by idryomov** [comment]
jenkins test api

**Comment by idryomov** [comment]
jenkins test docs

**Review by sebastian-philipp — APPROVED** [review]

**Comment by smithfarm** [comment]
It can be hard to tell which octopus release a backport PR went into when it has no backport tracker issue associated.

This one went into the 15.2.13 release.

**Pull request merged**
