### PR TITLE
reef: rgw: update options yaml file so LDAP uri isn't an invalid example

### PR DESCRIPTION
**Pull request by ivancich**
backport tracker: https://tracker.ceph.com/issues/65340

backport of https://github.com/ceph/ceph/pull/56645
parent tracker: https://tracker.ceph.com/issues/65277

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Review by dang — COMMENTED** [review]
This includes extra changes from other commits.  Is this intentional?

**Comment by ivancich** [comment]
> This includes extra changes from other commits. Is this intentional?

No, that was not intentional. Thank you for catching that.

**Review by mattbenjamin — APPROVED** [review]
looks good to me

**Comment by smanjara** [comment]
jenkins make check

**Comment by yuriw** [comment]
jenkins test this please

**Comment by yuriw** [comment]
@ivancich @smanjara pls merge when all checks passed
ref: https://tracker.ceph.com/issues/67262

**Comment by dang** [comment]
jenkins test api

**Comment by yuriw** [comment]
jenkins test api

**Comment by ivancich** [comment]
Huh, it appears an Arrow module is being compiled with C++ 11 and one of the include files prohibits C++ versions less than 14.

/usr/bin/ccache /usr/bin/g++-11 -DARROW_EXPORTING -DARROW_HAVE_RUNTIME_AVX2 -DARROW_HAVE_RUNTIME_AVX512 -DARROW_HAVE_RUNTIME_BMI2 -DARROW_HAVE_RUNTIME_SSE4_2 -DARROW_HAVE_SSE4_2 -DARROW_WITH_BACKTRACE -DARROW_WITH_LZ4 -DARROW_WITH_RE2 -DARROW_WITH_SNAPPY -DARROW_WITH_TIMING_TESTS -DARROW_WITH_UTF8PROC -DARROW_WITH_ZLIB -DURI_STATIC_BUILD -DUTF8PROC_STATIC -I/home/jenkins-build/build/workspace/ceph-api/build/src/arrow/cpp/src -I/home/jenkins-build/build/workspace/ceph-api/src/arrow/cpp/src -I/home/jenkins-build/build/workspace/ceph-api/src/arrow/cpp/src/generated -isystem /home/jenkins-build/build/workspace/ceph-api/src/arrow/cpp/thirdparty/flatbuffers/include -isystem /opt/ceph/include -isystem /home/jenkins-build/build/workspace/ceph-api/build/src/arrow/cpp/xsimd_ep/src/xsimd_ep-install/include -isystem /home/jenkins-build/build/workspace/ceph-api/build/src/utf8proc/install/include -isystem /home/jenkins-build/build/workspace/ceph-api/src/arrow/cpp/thirdparty/hadoop/include -Wno-noexcept-type  -fdiagnostics-color=always -ggdb -O0  -Wall -fno-semantic-interposition -msse4.2  -g -fPIC -std=c++11 -MD -MT src/arrow/CMakeFiles/arrow_objlib.dir/ipc/message.cc.o -MF src/arrow/CMakeFiles/arrow_objlib.dir/ipc/message.cc.o.d -o src/arrow/CMakeFiles/arrow_objlib.dir/ipc/message.cc.o -c /home/jenkins-build/build/workspace/ceph-api/src/arrow/cpp/src/arrow/ipc/message.cc
In file included from /usr/include/absl/base/config.h:92,
                 from /usr/include/absl/base/attributes.h:37,
                 from /usr/include/absl/strings/string_view.h:39,
                 from /home/jenkins-build/build/workspace/ceph-api/src/arrow/cpp/thirdparty/flatbuffers/include/flatbuffers/base.h:217,
                 from /home/jenkins-build/build/workspace/ceph-api/src/arrow/cpp/thirdparty/flatbuffers/include/flatbuffers/flatbuffers.h:20,
                 from /home/jenkins-build/build/workspace/ceph-api/src/arrow/cpp/src/arrow/ipc/metadata_internal.h:29,
                 from /home/jenkins-build/build/workspace/ceph-api/src/arrow/cpp/src/arrow/ipc/message.cc:31:
/usr/include/absl/base/policy_checks.h:79:2: error: #error "C++ versions less than C++14 are not supported."
   79 | #error "C++ versions less than C++14 are not supported."
      |  ^~~~~

**Comment by yuriw** [comment]
jenkins test api

**Comment by adamemerson** [comment]
> Huh, it appears an Arrow module is being compiled with C++ 11 and one of the include files prohibits C++ versions less than 14.
> 
> /usr/bin/ccache /usr/bin/g++-11 -DARROW_EXPORTING -DARROW_HAVE_RUNTIME_AVX2 -DARROW_HAVE_RUNTIME_AVX512 -DARROW_HAVE_RUNTIME_BMI2 -DARROW_HAVE_RUNTIME_SSE4_2 -DARROW_HAVE_SSE4_2 -DARROW_WITH_BACKTRACE -DARROW_WITH_LZ4 -DARROW_WITH_RE2 -DARROW_WITH_SNAPPY -DARROW_WITH_TIMING_TESTS -DARROW_WITH_UTF8PROC -DARROW_WITH_ZLIB -DURI_STATIC_BUILD -DUTF8PROC_STATIC -I/home/jenkins-build/build/workspace/ceph-api/build/src/arrow/cpp/src -I/home/jenkins-build/build/workspace/ceph-api/src/arrow/cpp/src -I/home/jenkins-build/build/workspace/ceph-api/src/arrow/cpp/src/generated -isystem /home/jenkins-build/build/workspace/ceph-api/src/arrow/cpp/thirdparty/flatbuffers/include -isystem /opt/ceph/include -isystem /home/jenkins-build/build/workspace/ceph-api/build/src/arrow/cpp/xsimd_ep/src/xsimd_ep-install/include -isystem /home/jenkins-build/build/workspace/ceph-api/build/src/utf8proc/install/include -isystem /home/jenkins-build/build/workspace/ceph-api/src/arrow/cpp/thirdparty/hadoop/include -Wno-noexcept-type -fdiagnostics-color=always -ggdb -O0 -Wall -fno-semantic-interposition -msse4.2 -g -fPIC -std=c++11 -MD -MT src/arrow/CMakeFiles/arrow_objlib.dir/ipc/message.cc.o -MF src/arrow/CMakeFiles/arrow_objlib.dir/ipc/message.cc.o.d -o src/arrow/CMakeFiles/arrow_objlib.dir/ipc/message.cc.o -c /home/jenkins-build/build/workspace/ceph-api/src/arrow/cpp/src/arrow/ipc/message.cc In file included from /usr/include/absl/base/config.h:92, from /usr/include/absl/base/attributes.h:37, from /usr/include/absl/strings/string_view.h:39, from /home/jenkins-build/build/workspace/ceph-api/src/arrow/cpp/thirdparty/flatbuffers/include/flatbuffers/base.h:217, from /home/jenkins-build/build/workspace/ceph-api/src/arrow/cpp/thirdparty/flatbuffers/include/flatbuffers/flatbuffers.h:20, from /home/jenkins-build/build/workspace/ceph-api/src/arrow/cpp/src/arrow/ipc/metadata_internal.h:29, from /home/jenkins-build/build/workspace/ceph-api/src/arrow/cpp/src/arrow/ipc/message.cc:31: /usr/include/absl/base/policy_checks.h:79:2: error: #error "C++ versions less than C++14 are not supported." 79 | #error "C++ versions less than C++14 are not supported." | ^~~~~

Is this still an issue or should we merge?

**Pull request merged**
