### PR TITLE
jewel: mount.ceph: move from ceph-base to ceph-common and add symlink in /sbin for SUSE

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/16748
http://tracker.ceph.com/issues/16795

### CODE REVIEW

**Comment by smithfarm** [comment]
cherry-picked efa7f7b to avoid conflicts when backporting http://tracker.ceph.com/issues/16795

**Comment by dachary** [comment]
It passed http://tracker.ceph.com/issues/16344#note-22

**Comment by smithfarm** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;gcAnk3JY&#x2F;1748-issue-16598-mount-ceph-move-from-ceph-base-to-ceph-common-and-add-symlink-in-sbin-for-suse"> (issue#16598) mount.ceph: move from ceph-base to ceph-common and add symlink in &#x2F;sbin for SUSE</a>

**Comment by smithfarm** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;wcuYLUnt&#x2F;1771-issue-16645-libatomic-ops-devel-was-renamed-in-may-2012-fix-in-ceph-spec"> (issue#16645) libatomic-ops-devel was renamed in May 2012 - fix in ceph.spec</a>

**Pull request merged**
