### PR TITLE
mimic: common: Keyrings created by ceph auth get are not suitable for ceph auth import

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/40547

### CODE REVIEW

**Comment by smithfarm** [comment]
```
157/157 Test   #3: test_objectstore_memstore.sh ............***Timeout 3600.01 sec
```

**Comment by smithfarm** [comment]
jenkins run make check

**Comment by smithfarm** [comment]
jenkins test make check

**Comment by yuriw** [comment]
[wip-yuri4-testing-2019-07-15-1517-mimic](https://trello.com/c/ZszYh3L3/666-wip-yuri4-testing-2019-07-15-1517-mimic)

**Pull request merged**
