### PR TITLE
make-dist: Bump Node.js to v10.18.1

### PR DESCRIPTION
**Pull request by tspmelo**
This will fix an error caused by the usage of the latest version of Angular CLI
and Node.js v10.16.0.

Fixes: https://tracker.ceph.com/issues/43961

Signed-off-by: Tiago Melo <tmelo@suse.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by tspmelo** [comment]
@LenzGr  done.

**Comment by smithfarm** [comment]
@tspmelo Can you push the branch to `ceph-ci`?

**Comment by tspmelo** [comment]
Since we aren't using latest version of angular in nautilus and didn't update node in `src/pybind/mgr/dashboard/CMakeLists.txt`, I'm not sure if we need to backport this...

**Comment by smithfarm** [comment]
https://shaman.ceph.com/builds/ceph/wip-node-10-18-1/74497a39f53433eeed488062a08686f8594da7d8/

**Comment by tspmelo** [comment]
jenkins test dashboard

**Comment by smithfarm** [comment]
I examined the Shaman build log carefully, and it seems that Jenkins runs make-dist *before* the RPM build even starts.

So I guess a Shaman build is not good enough QA for `make-dist` patches.

**Comment by smithfarm** [comment]
@tspmelo With 10.18.1, `gyp` starts complaining about something else:

```
Installing collected packages: nodeenv
Successfully installed nodeenv-1.3.5
 * Install prebuilt node (10.18.1) ..... done.
 * Appending data to /tmp/tmp.8V1zwAA64m/bin/activate
 * Appending data to /tmp/tmp.8V1zwAA64m/bin/activate.fish

> fsevents@1.2.11 install /tmp/tmp.XhF43yUHk1/src/pybind/mgr/dashboard/frontend/node_modules/webpack-dev-server/node_modules/fsevents
> node-gyp rebuild

gyp ERR! build error
gyp ERR! stack Error: not found: make
gyp ERR! stack     at getNotFoundError (/tmp/tmp.8V1zwAA64m/lib/node_modules/npm/node_modules/which/which.js:13:12)
gyp ERR! stack     at F (/tmp/tmp.8V1zwAA64m/lib/node_modules/npm/node_modules/which/which.js:68:19)
gyp ERR! stack     at E (/tmp/tmp.8V1zwAA64m/lib/node_modules/npm/node_modules/which/which.js:80:29)
gyp ERR! stack     at /tmp/tmp.8V1zwAA64m/lib/node_modules/npm/node_modules/which/which.js:89:16
gyp ERR! stack     at /tmp/tmp.8V1zwAA64m/lib/node_modules/npm/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /tmp/tmp.8V1zwAA64m/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:153:21)
gyp ERR! System Linux 4.12.14-lp151.28.36-default
gyp ERR! command "/tmp/tmp.8V1zwAA64m/bin/node" "/tmp/tmp.8V1zwAA64m/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /tmp/tmp.XhF43yUHk1/src/pybind/mgr/dashboard/frontend/node_modules/webpack-dev-server/node_modules/fsevents
gyp ERR! node -v v10.18.1
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok
```

Like the previous error, this gets repeated a bunch of times and then `make-dist` just goes on about its business as if nothing had happened. I.e. the errors appear to be cosmetic. But still.

**Comment by tspmelo** [comment]
Could not reproduce the problem in my docker env, but on my host env `npm ci` was failing with similar errors.
This seems to be related to `fsevents@1.2.11`, after bumping its version to 2.1.2 the errors disappeared.
Please test it again.

**Pull request merged**
