### PR TITLE
common/Finisher: Using queue(list<context*>) instead queue(context*).

### PR DESCRIPTION
**Pull request by majianpeng**
Avoid call many time queue(context*).

Signed-off-by: Jianpeng Ma jianpeng.ma@intel.com

### CODE REVIEW

**Comment by yuyuyu101** [comment]
rebase

**Comment by liewegas** [comment]
sorry, please rebase one more time?  This looks good.

**Comment by majianpeng** [comment]
update

**Comment by tchaikov** [comment]
- http://pulpito.ceph.com/kchai-2017-01-04_05:03:43-rados-wip-kefu-testing---basic-mira/
- http://pulpito.ceph.com/kchai-2017-01-03_09:59:57-rados-wip-kefu-testing---basic-mira/

failed job tracked by http://tracker.ceph.com/issues/17417

**Pull request merged**
