### PR TITLE
mgr/dashboard: Show the OSDs Out and Down panels as red whenever an OSD is in Out or Down state in Ceph Cluster grafana dashboard

### PR DESCRIPTION
**Pull request by aaSharma14**
Fixes: https://tracker.ceph.com/issues/62969

[Screencast from 2023-10-11 12-22-17.webm](https://github.com/ceph/ceph/assets/66050535/1aa0da8d-5029-4217-b695-bdd6a9b87178)

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by aaSharma14** [comment]
> I think a good default behavior for the thresholds are:
> 
>     * OK/Green in the following conditions:
>       
>       * ALL, always green
>       * IN and UP, if = ALL
>       * Out and DOWN, if = 0
> 
>     * Warning/Yellow in the following conditions:
>       
>       * IN and UP, if 1 OSD is down, or
>       * IN and UP, if some or all OSD's within 1 host is down
>       * OUT and DOWN, if 1 OSD is OUT or Down or
>       * OUT and DOWN, if some or all OSD's within 1 host is down
> 
>     * Error/Red in the following conditions:
>       
>       * IN and UP, if exceeding the definition of Warning
>       * OUT and DOWN, if exceeding the definition of Warning

Hi @Ejdesgaard , Thanks for the suggestion. We already have two alerts related to OSDs in ceph dashboard -

1. CephOSDDown - This is fired when we have atleast one OSD down
2. CephOSDDownHigh - This is fired when >=10% OSDs are down

So to be consistent with this behavior, I have updated the PR and attached a recording of the implementation. Please let me know if you any suggestions regarding it.

**Review by cloudbehl — APPROVED** [review]
LGTM

**Comment by Pegonzal** [comment]
jenkins test api

**Review by Pegonzal — APPROVED** [review]

**Comment by anthonyeleven** [comment]
Please take out the apostrophes `'` from the PR and commit titles.  These are plurals not possessives.

**Comment by aaSharma14** [comment]
jenkins test api

**Comment by aaSharma14** [comment]
jenkins test dashboard

**Comment by Ejdesgaard** [comment]
@aaSharma14 I just now saw the backport PR, sorry for being late to the party.
I added a comment to the reef backport, before I saw your comment here.

I just tried to import the changes and "all" is not green
Mon 20 Nov 09:24:21 CET 2023

IMO. the % should be changed to integer values, because a value of 10% is only valid if the cluster is made up of a multiple of 10 nodes, multiplied  by the number of failure domains. In all other configurations.

Using an integer value instead would be much more useful

**Pull request merged**
