### PR TITLE
rgw: document S3 bucket replication support

### PR DESCRIPTION
**Pull request by mattbenjamin**
Support was added at Octopus.

Fixes: https://tracker.ceph.com/issues/48755

Signed-off-by: Matt Benjamin <mbenjamin@redhat.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by yehudasa** [comment]
@mattbenjamin need to add caveat that replication only applies to cross zones cases

**Comment by mattbenjamin** [comment]
> 
> 
> @mattbenjamin need to add caveat that replication only applies to cross zones cases

Ok.  Can that just be a comment in the remarks column?

**Comment by yehudasa** [comment]
@mattbenjamin yeah

**Review by cbodley — APPROVED** [review]
looks good but the commit includes unrelated submodule changes

**Comment by mattbenjamin** [comment]
crap, will fix

**Comment by cbodley** [comment]
jenkins test signed

**Comment by cbodley** [comment]
it looks like jenkins will reject this pr until the commit starts with 'doc'

**Comment by cbodley** [comment]
ping @mattbenjamin

**Comment by mattbenjamin** [comment]
I need to change the subject line in the commit message @cbodley ?

**Comment by cbodley** [comment]
jenkins test signed

**Comment by cbodley** [comment]
logs from the Signed-off-by check:
> E           AssertionError: The title/s of following commit/s is/are not started with 'doc', but they only touch files under 'doc/'. Please make sure the commit titles
E           are started with 'doc'. See the 'Submitting Patches' guide:
E           https://github.com/ceph/ceph/blob/master/SubmittingPatches.rst#commit-title

this seems like pretty useless check to me

**Comment by cbodley** [comment]
jenkins test signed

**Comment by cbodley** [comment]
> I need to change the subject line in the commit message @cbodley ?

@mattbenjamin yeah, i guess jenkins wants the commit to start with 'doc'

**Comment by mattbenjamin** [comment]
I don't understand why doc build is failing NOW

**Comment by cbodley** [comment]
seeing the same in other PRs :(

**Comment by cbodley** [comment]
jenkins test docs

**Pull request merged**
