### PR TITLE
quincy: ceph-fuse: add dedicated snap stag map for each directory

### PR DESCRIPTION
**Pull request by lxbsz**
backport tracker: https://tracker.ceph.com/issues/56055

---

backport of https://github.com/ceph/ceph/pull/45614
parent tracker: https://tracker.ceph.com/issues/54653

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by luis-henrix** [comment]
(copying comment from the original PR, see also tracker comment)

@lxbsz This is breaking my build with `FUSE_VERSION > FUSE_MAKE_VERSION(3, 0)`:
```
/home/miguel/dev/ceph/ceph/src/client/fuse_ll.cc: In constructor ‘CephFuse::Handle::Handle(Client*, int)’:
/home/miguel/dev/ceph/ceph/src/client/fuse_ll.cc:1379:1: error: expected identifier before ‘{’ token
 1379 | {
      | ^
```

**Comment by lxbsz** [comment]
> (copying comment from the original PR, see also tracker comment)
> 
> @lxbsz This is breaking my build with `FUSE_VERSION > FUSE_MAKE_VERSION(3, 0)`:
> 
> ```
> /home/miguel/dev/ceph/ceph/src/client/fuse_ll.cc: In constructor ‘CephFuse::Handle::Handle(Client*, int)’:
> /home/miguel/dev/ceph/ceph/src/client/fuse_ll.cc:1379:1: error: expected identifier before ‘{’ token
>  1379 | {
>       | ^
> ```

Fixed in https://github.com/ceph/ceph/pull/47026.

**Comment by lxbsz** [comment]
Backported https://github.com/ceph/ceph/pull/47026.

**Comment by yuriw** [comment]
@lxbsz this was tested as part of https://trello.com/c/4ng3KVzi

**Comment by ljflores** [comment]
https://pulpito.ceph.com/?branch=wip-yuri7-testing-2022-08-17-0943-quincy

Failures, unrelated:
    1. https://tracker.ceph.com/issues/57303 -- new Tracker; unrelated to PRs in this run
    2. https://tracker.ceph.com/issues/52321
    3. https://tracker.ceph.com/issues/57303
    4. https://tracker.ceph.com/issues/56951
    5. https://tracker.ceph.com/issues/57270 -- Pending Quincy backport
    6. https://tracker.ceph.com/issues/57165 -- Fix under review; pending Quincy backport
    7. https://tracker.ceph.com/issues/49287

Details:
    1. rados/cephadm: Failed to fetch package version from https://shaman.ceph.com/api/search/?status=ready&project=ceph&flavor=default&distros=ubuntu%2F22.04%2Fx86_64&sha1=b34ca7d1c2becd6090874ccda56ef4cd8dc64bf7  - Ceph - Orchestrator
    2. qa/tasks/rook times out: 'check osd count' reached maximum tries (90) after waiting for 900 seconds - Ceph - Rook
    3. AssertionError: Expected to find element: `cd-modal .badge:not(script,style):cy-contains('/^foo$/'), cd-modal .badge[type='submit'][value~='/^foo$/']`, but never found it. - Ceph - Mgr - Dashboard
    4. rook/smoke: Updating cephclusters/rook-ceph is forbidden - Ceph - Orchestrator
    5. cephadm: RuntimeError: Failed command: apt-get update: E: The repository 'https://download.ceph.com/debian-octopus jammy Release' does not have a Release file. - Ceph - Orchestrator
    6. expected valgrind issues and found none - Ceph - RADOS
    7. podman: setting cgroup config for procHooks process caused: Unit libpod-$hash.scope not found - Ceph - Orchestrator

**Comment by ljflores** [comment]
@yuriw this one's still in draft form. Mark it with TESTED and we'll leave it to the author to take it out of draft mode.

**Comment by yuriw** [comment]
@lxbsz this was tested and ready for merge
https://trello.com/c/4ng3KVzi

**Comment by lxbsz** [comment]
> @yuriw this one's still in draft form. Mark it with TESTED and we'll leave it to the author to take it out of draft mode.

Done. Removed it. Thanks!

**Review by kotreshhr — APPROVED** [review]

**Pull request merged**
