### PR TITLE
include/memory.h: remove memory.h

### PR DESCRIPTION
**Pull request by tchaikov**
memory.h was introduced back when the shared_ptrs were still in TR1, but
we've moved to C++17 now. and the C++ clients should be compiled with
a C++11 compatible compiler. so there is no need to have this file anymore.

also replace all references of ceph::shared_ptr and ceph::weak_ptr with
std::shared_ptr and std::weak_ptr accordingly.

Signed-off-by: Kefu Chai <kchai@redhat.com>

### CODE REVIEW

**Comment by tchaikov** [comment]
retest this please.

**Comment by tchaikov** [comment]
https://shaman.ceph.com/builds/ceph/wip-kefu-testing-2018-06-26-1105/4e61d9c16796381f5dc7e61ad700b17b83fc89fe/

**Comment by gregsfortytwo** [comment]
Why do we want to do this? We’ve found the use of a ceph namespace interpolator useful on several other occasions.

**Comment by adamemerson** [comment]
So. I have an argument against this. Two, in fact.

While the stuff in here may not be relevant, this *kind* of file that interpolates things into the Ceph namespace can help with backporting.

As to this specific file, I have a use for it in the future.

As part of my long term project to fix using namespace std, I was planning on following this model.

Using "include/foo.h" to interpolate the subset of things we want from <foo> into the Ceph namespace (along with perhaps relevant functions/types of our own) to make it available unqualified to our code.

So if you pull this out I'm going to have to re-add something similar at some point.

**Comment by tchaikov** [comment]
the ceph namespace is useful. but could you be more specific?

i am not sure how `ceph::shared_ptr` could make backport easier? could you elaborate a little bit?

i think the shared_ptrs are pretty stable. may i know what stuff you plan to re-add back?

**Comment by adamemerson** [comment]
Well!

What I mean is, we would like to be able to use `shared_ptr<Foo>` instead of `std::shared_ptr<Foo>`.

We would like to /not/ use `using namespace std`.

So I'm planning to wrap our core code in namespace ceph and just import things like shared_ptr, weak_ptr, unique_ptr and the other stuff we use most commonly into the ceph namespace.

(Actually inline inline namespace ceph::vocab so RGW and other things could just use ceph::vocab and get the same set of identifiers unqualified.)

**Comment by tchaikov** [comment]
okay, i start to understand your point now. and it's very new to me! so you want to add the commonly used subset of other namespace(s) into `ceph`, so that we can use them without referencing them with their original namespace(s).

i am not sure this practice is commonly accepted, or this plan is (well) discussed yet. IMHO, it'd better to be explicit than implicit. if a "vocab" belongs to namespace `foo`, so be it. why shall we absorb, for instance, the bits in standard library into our own namespace because:

1. `shared_ptr<>` not `std::shared_ptr<>`
1. no `using namespace std`
1. no `using std::shared_ptr`

actually, i think all three approaches have their pros and cons. not necessary all bad things.

**Comment by adamemerson** [comment]
WELL. `using namespace std` pretty much has to go for more than just stylistic reasons as it's already lead to name clashes.

If people want to make a serious case for importing individual symbols into the root namespace instead of the ceph namespace instead of 'our' namespace, I am not necessarily against it. I think it's bad practice for library code, though, and a lot of what we have written is effectively 'libraries' that our own code consumes. (libcommon, for example.)

**Comment by tchaikov** [comment]
@adamemerson makes sense to me. we are not crafting libraries. but "libraries" consumed my our own code.

please note, the reason why i remove `shared_ptr` from `ceph` is not just for cleaning up. it also serves as a part of the crimson project: i plan to use `boost::local_shared_ptr` because it has good interoperability with `boost::shared_ptr` and `boost::weak_ptr`, so i don't need to re-implement the standard compliant `shared_ptr` and `weak_ptr` in a seastar-performant  (i.e. single-threaded) way.

if we put these shared_ptrs back to `ceph` namespace, name clashes will be expected.

**Comment by adamemerson** [comment]
Carry on then. My code will probably merge after yours, so I'll come up with something that doesn't cause a clash.

**Pull request merged**
