### PR TITLE
rgw: set bucket versioninig donot change versioning status if missing status in xml

### PR DESCRIPTION
**Pull request by shashalu**
Fixes: http://tracker.ceph.com/issues/21364

Signed-off-by: Shasha Lu <lu.shasha@eisoo.com>

### CODE REVIEW

**Comment by shashalu** [comment]
@cbodley  please take a look, thx

**Comment by shashalu** [comment]
jenkins test this please

**Comment by cbodley** [comment]
hi @shashalu, i'm looking at the [put bucket versioning api](http://docs.aws.amazon.com/AmazonS3/latest/API/RESTBucketPUTVersioningStatus.html) and it lists the Status as optional, so i would prefer not to reject the request if it's missing. if missing, we should just not change the versioning status of the bucket (if it's enabled, leave it enabled - if suspended, leave suspended). what do you think?

**Comment by shashalu** [comment]
@cbodley  Agree.  If it's nonversioned, leave it nonversioned.   I revised the commit.

**Comment by yuriw** [comment]
http://pulpito.front.sepia.ceph.com:80/yuriw-2017-09-28_17:09:24-rgw-wip-yuri-testing3-2017-09-27-1448-distro-basic-smithi/

http://pulpito.front.sepia.ceph.com:80/yuriw-2017-09-28_17:09:24-rgw-wip-yuri-testing3-2017-09-27-1448-distro-basic-smithi/

**Pull request merged**
