### PR TITLE
mds/FSMap: assign v16.2.4 compat to pre-v16.2.5 standby daemons

### PR DESCRIPTION
**Pull request by batrick**
I'm testing this to see it fixes https://tracker.ceph.com/issues/53150

### CODE REVIEW

**Comment by sebastian-philipp** [comment]
cephadm part lgtm.

**Comment by batrick** [comment]
jenkins test api

**Comment by batrick** [comment]
jenkins test api

**Comment by batrick** [comment]
https://pulpito.ceph.com/pdonnell-2021-11-05_19:13:39-fs:upgrade-wip-pdonnell-testing-20211105.172813-distro-basic-smithi/

Failures is unrelated: https://tracker.ceph.com/issues/53194

**Comment by batrick** [comment]
rebase: updated/clarified wording in one of the commit messages

**Comment by batrick** [comment]
jenkins test api

**Comment by batrick** [comment]
found a bug; retesting

**Comment by batrick** [comment]
jenkins test make check

**Comment by batrick** [comment]
https://pulpito.ceph.com/pdonnell-2021-11-09_03:54:01-fs:upgrade-wip-pdonnell-testing-20211109.015313-distro-basic-smithi/

failure is caused by known assertion in MDS (for v16.2.4). Not sure why cephadm/systemd didn't restart the MDS though.

**Comment by batrick** [comment]
jenkins test dashboard cephadm

**Comment by batrick** [comment]
https://tracker.ceph.com/projects/cephfs/wiki/Master#2021-November-9

**Comment by batrick** [comment]
jenkins test api

**Review by jtlayton — APPROVED** [review]

**Comment by sebastian-philipp** [comment]
followup on #43214

**Pull request merged**
