### PR TITLE
pacific:  mgr/dashboard: RGW buckets async validator performance enhancement and name constraints 

### PR DESCRIPTION
**Pull request by nizamial09**
backport tracker: https://tracker.ceph.com/issues/50769
backport tracker: https://tracker.ceph.com/issues/50767

---

backport of https://github.com/ceph/ceph/pull/41023
parent tracker: https://tracker.ceph.com/issues/50514
parent tracker: https://tracker.ceph.com/issues/50516

this backport was staged using ceph-backport.sh version 16.0.0.6848
find the latest version at https://github.com/ceph/ceph/blob/master/src/script/ceph-backport.sh

### CODE REVIEW

**Comment by nizamial09** [comment]
jenkins test dashboard

**Comment by nizamial09** [comment]
jenkins test dashboard

**Review by avanthakkar — APPROVED** [review]

**Review by epuertat — APPROVED** [review]

**Comment by epuertat** [comment]
[e2e failure](https://dashboard.cypress.io/projects/k7ab29/runs/3065/test-results/a638182a-d6eb-44a9-af6d-8b956b6fe507), but it's not tagged as flaky... 🤔

**Comment by avanthakkar** [comment]
> [e2e failure](https://dashboard.cypress.io/projects/k7ab29/runs/3065/test-results/a638182a-d6eb-44a9-af6d-8b956b6fe507), but it's not tagged as flaky... thinking

Yeah, not the tests but the failure reason has been flaky for [pool-configuration e2e ](https://dashboard.cypress.io/projects/k7ab29/runs/3066/test-results/4beb166c-af89-46ab-8a61-2f15eaf9025c?isFlaky=%5B%7B%22label%22%3A%22Flaky%22%2C%22value%22%3Atrue%7D%5D)

**Comment by avanthakkar** [comment]
jenkins test dashboard

**Comment by nizamial09** [comment]
jenkins test signed

**Pull request merged**
