### PR TITLE
[DNM] rbd: show snap location in rbd info.

### PR DESCRIPTION
**Pull request by yangdongsheng**
Fixes: http://tracker.ceph.com/issues/18917

Build a tree in snapshot for an image. 

```
(snapshot add):                                       
      [init]--->snap1-->snap2--> snap3 
                     |
                     | [snap_location is snap2, add snap4]
                     |
                     v                           |----> snap3
      [init]--->snap1-->snap2--|
                                                  -----> snap4
                                             
(snapshot remove): 
                                                  |----> snap3
      [init]--->snap1-->snap2--|
                                                  -----> snap4
                     |
                     | [remove snap2]
                     |
                     v
                                    |----> snap3
      [init]--->snap1---|
                                    -----> snap4
```
Example:
$ rbd create test -s 1
$ rbd snap add test@snap1
$ rbd info test
rbd image 'test':
	size 1024 kB in 1 objects
	order 22 (4096 kB objects)
	block_name_prefix: rbd_data.103e2ae8944a
	format: 2
	features: layering, exclusive-lock, object-map, fast-diff, deep-flatten
	flags: 
	snapshot location: snap1 Wed Mar  8 22:06:27 2017
$ rbd snap add test@snap2
$ rbd snap add test@snap3
$ rbd info test
rbd image 'test':
	size 1024 kB in 1 objects
	order 22 (4096 kB objects)
	block_name_prefix: rbd_data.103e2ae8944a
	format: 2
	features: layering, exclusive-lock, object-map, fast-diff, deep-flatten
	flags: 
	snapshot location: snap3 Wed Mar  8 22:06:37 2017
$ rbd snap rollback test@snap2
Rolling back to snapshot: 100% complete...done.
$ rbd info test
rbd image 'test':
	size 1024 kB in 1 objects
	order 22 (4096 kB objects)
	block_name_prefix: rbd_data.103e2ae8944a
	format: 2
	features: layering, exclusive-lock, object-map, fast-diff, deep-flatten
	flags: 
	snapshot location: snap2 Wed Mar  8 22:06:33 2017
$ rbd snap remove test@snap2
Removing snap: 100% complete...done.
$ rbd info test
rbd image 'test':
	size 1024 kB in 1 objects
	order 22 (4096 kB objects)
	block_name_prefix: rbd_data.103e2ae8944a
	format: 2
	features: layering, exclusive-lock, object-map, fast-diff, deep-flatten
	flags: 
	snapshot location: snap1 Wed Mar  8 22:06:27 2017

### CODE REVIEW

**Comment by dillaman** [comment]
@yangdongsheng I'm not following the use-case of this PR. If you rollback to snapshot XYZ, the second you write to the image the HEAD revision is no longer at snap XYZ. Additionally, if you delete a snapshot that you had rolled back to, the HEAD revision doesn't start matching the previous snapshot. If this is something that you wanted to track, your tooling could just use the existing "rbd metadata set" action to add any arbitrary labeling that you want.

**Comment by yangdongsheng** [comment]
@dillaman  Yes, the head revision is not equal with the snapshot. Maybe I should not name it as snapshot_location, but last_snapshot. This use-case is inspired by vmware, when we do a rolling back, we can find the location of the head in the snapshot tree. But now in rbd, if I did some rolling back long time ago, I can't remember which snapshot is the last snapshot before current HEAD. So, I linked the all snapshots in a tree, and show the last snapshot of the head in rbd info. Maybe I should add a new command "rbd snapshot tree IMG" to show the snapshot tree. Then we can see the location of HEAD more clear.

**Comment by dillaman** [comment]
@yangdongsheng A rollback is a pretty large sledgehammer (i.e. not efficient) approach to switch between a hierarchy of historical configurations. I wonder if such a use-case is actually better suited to utilize clones?

**Comment by yangdongsheng** [comment]
@dillaman yes, rollback is not a good idea, instead cloning is recommanded. But I think we still need a tool to show the hierarchy of the snapshots of an image, Such as what vmware is doing.



So I implemented an rbd snap tree command for the similar feature.

**Comment by dillaman** [comment]
@yangdongsheng I would like to request that you send out a RFC to the ceph-users mailing list to gauge interest in this feature. The only use-case I've seen for that VMware feature is to support is to switch back-and-forth between software versions. However, I would still argue that clones are a better fit for that use-case. I would guess that the vast majority of users would have lots of clones in a linear line that would run off past the edge of the terminal screen and wrap around when displayed in tree-view.

**Comment by yangdongsheng** [comment]
@dillaman That's okey, will send a mail in ceph-users to collect all opinions about it. Thanx for your suggestion. :)

**Comment by dillaman** [comment]
@yangdongsheng Thanks. In the meantime, I think the tree view could be nice for showing parent/clone relationships if you want to push a PR for something like that.

**Comment by yangdongsheng** [comment]
@dillaman Ha, yea, sounds good. will include this idea in my email to ceph-user. thanx

**Comment by chengtcli** [comment]
I like this idea, I made a [tool named rbd-tree](https://github.com/chengtcli/rbd-tree) to print the structure of rbd image/snapshot. It calls `rbd` command, so not efficient. It would be great if Ceph could implement this feature by itself.

**Pull request closed without merging**
