### PR TITLE
rocksdb: use native rocksdb makefile (and our autotools)

### PR DESCRIPTION
**Pull request by liewegas**
This was a huge PITA, but it builds now on my fc22 box.  This is improtant
because we need to be able to track rocksdb upstream with minimal friction.

I didn't touch cmake here, but rocks isn't being built at all there anyway.

### CODE REVIEW

**Comment by liewegas** [comment]
@dachary i suspect a dirty build tree?  this change requires make distclean

**Comment by dachary** [comment]
@liewegas a **git clean -fqdx** is done prior to building. It looks like it must have a double **f** in this situation. I made the change, could you please amend and repush ?

**Comment by dachary** [comment]
@liewegas the problem was something else: the bot uses autogen.sh from master which no longer works everywhere with this patch. I changed it to use the autogen.sh from the pull request instead. The reason for this trick was because it is the only script that runs with network access. Could you re-push please ?

**Comment by liewegas** [comment]
YAY GITBUILDERS ARE HAPPY OMFG AUTOTOOLS AAAAUUUGGGHHHH

**Comment by dachary** [comment]
In the end the change is straightforward. Great ! 

<pre>
Reviewed-by: Loic Dachary &lt;ldachary@redhat.com>
</pre>

**Pull request merged**
