### PR TITLE
osd: Turn off repair pg state when leaving recovery

### PR DESCRIPTION
**Pull request by dzafman**
## Checklist
- [X] References tracker ticket
- [ ] ~Updates documentation if necessary~
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`

</details>

### CODE REVIEW

**Comment by dzafman** [comment]
jenkins test make check
jenkins test docs

**Comment by dzafman** [comment]
jenkins test make check

**Comment by dzafman** [comment]
jenkins test docs

**Comment by tchaikov** [comment]
- http://pulpito.ceph.com/kchai-2019-10-17_15:27:09-rados-wip-kefu-testing-2019-10-15-1130-distro-basic-mira/
- http://pulpito.ceph.com/kchai-2019-10-15_09:41:56-rados-wip-kefu-testing-2019-10-15-1130-distro-basic-mira/

**Pull request merged**
