### PR TITLE
 [DNM] jewel: msg: IPv6 Heartbeat packets are not marked with DSCP QoS - async messenger

### PR DESCRIPTION
**Pull request by shinobu-x**
http://tracker.ceph.com/issues/19046

### CODE REVIEW

**Comment by shinobu-x** [comment]
```
root@octopus:ceph [wip-18928-jewel]$ git diff --diff-filter=U
diff --cc src/msg/async/net_handler.cc
index 2a89276,53ffdb7..0000000
--- a/src/msg/async/net_handler.cc
+++ b/src/msg/async/net_handler.cc
@@@ -100,9 -120,51 +100,54 @@@ void NetHandler::set_socket_options(in
      ldout(cct,0) << "couldn't set SO_NOSIGPIPE: " << cpp_strerror(r) << dendl;
    }
  #endif
 -  return r;
  }
  
++<<<<<<< HEAD
 +int NetHandler::generic_connect(const entity_addr_t& addr, bool nonblock)
++=======
+ void NetHandler::set_priority(int sd, int prio, int domain)
+ {
+   if (prio >= 0) {
+     int r = -1;
+ #ifdef IPTOS_CLASS_CS6
+     int iptos = IPTOS_CLASS_CS6;
+     r = ::setsockopt(sd, IPPROTO_IP, IP_TOS, &iptos, sizeof(iptos));
+     if (domain == AF_INET) {
+       r = ::setsockopt(sd, IPPROTO_IP, IP_TOS, &iptos, sizeof(iptos));
+       r = -errno;
+       if (r < 0) {
+         ldout(cct,0) << "couldn't set IP_TOS to " << iptos
+                            << ": " << cpp_strerror(r) << dendl;
+       }
+     } else if (domain == AF_INET6) {
+       r = ::setsockopt(sd, IPPROTO_IPV6, IPV6_TCLASS, &iptos, sizeof(iptos));
+       r = -errno;
+       if (r < 0) {
+         ldout(cct,0) << "couldn't set IPV6_TCLASS to " << iptos
+                            << ": " << cpp_strerror(r) << dendl;
+       }
+     } else {
+       ldout(cct,0) << "couldn't set ToS of unknown family to " << iptos
+                          << dendl;
+     }
+ #endif
+ #if defined(SO_PRIORITY) 
+     // setsockopt(IPTOS_CLASS_CS6) sets the priority of the socket as 0.
+     // See http://goo.gl/QWhvsD and http://goo.gl/laTbjT
+     // We need to call setsockopt(SO_PRIORITY) after it.
+ #if defined(__linux__)
+     r = ::setsockopt(sd, SOL_SOCKET, SO_PRIORITY, &prio, sizeof(prio));
+ #endif
+     if (r < 0) {
+       ldout(cct, 0) << __func__ << " couldn't set SO_PRIORITY to " << prio
+                     << ": " << cpp_strerror(errno) << dendl;
+     }
+ #endif
+   }
+ }
+ 
+ int NetHandler::generic_connect(const entity_addr_t& addr, const entity_addr_t
++>>>>>>> eb0f624... msg/async: support IPv6 QoS.
  {
    int ret;
    int s = create_socket(addr.get_family());
diff --cc src/msg/async/net_handler.h
index 980e009,c4fb73e..0000000
--- a/src/msg/async/net_handler.h
+++ b/src/msg/async/net_handler.h
@@@ -39,7 -39,8 +39,12 @@@ namespace ceph 
       *            < 0       need to goto fail
       */
      int reconnect(const entity_addr_t &addr, int sd);
++<<<<<<< HEAD
 +    int nonblock_connect(const entity_addr_t &addr);
++=======
+     int nonblock_connect(const entity_addr_t &addr, const entity_addr_t& bind_
+     void set_priority(int sd, int priority, int domain);
++>>>>>>> eb0f624... msg/async: support IPv6 QoS.
    };
  }
  
* Unmerged path src/msg/async/PosixStack.cc
```

**Comment by smithfarm** [comment]
@shinobu-x Needs conflict resolution description.

**Comment by shinobu-x** [comment]
@smithfarm Got it.

**Comment by smithfarm** [comment]
Closing in favor of #13450 

@shinobu-x The conflicts can be avoided by cherry-picking like this: `git cherry-pick -x 91a29bc 2d6021f`

**Comment by smithfarm** [comment]
@shinobu-x Sorry, I mixed up the simple and async messenger versions. @robbat2 opened #13340 which covers the simple messenger backport. Now we need to figure out how best to backport the async messenger one.

**Pull request closed without merging**
