### PR TITLE
 spdk: update SPDK to v17.10

### PR DESCRIPTION
**Pull request by tchaikov**

### CODE REVIEW

**Comment by smithfarm** [comment]
SUSE build test now running in https://build.opensuse.org/package/show/home:smithfarm:branches:filesystems:ceph:mimic/ceph

**Comment by tchaikov** [comment]
https://shaman.ceph.com/builds/ceph/wip-kefu-testing-2017-11-29-2317/

**Comment by smithfarm** [comment]
@tchaikov Maybe I approved this too soon. I activated the i586 build in OBS and it fails with:

```
[  955s] cc1: sorry, unimplemented: 64-bit mode not compiled in
[  955s] make[2]: *** [/home/abuild/rpmbuild/BUILD/ceph-13.0.0-3535-g8b10d08c04/src/spdk/mk/spdk.common.mk:171: bdev.o] Error 1
[  955s] make[1]: *** [/home/abuild/rpmbuild/BUILD/ceph-13.0.0-3535-g8b10d08c04/src/spdk/mk/spdk.subdirs.mk:35: bdev] Error 2
[  955s] make: *** [/home/abuild/rpmbuild/BUILD/ceph-13.0.0-3535-g8b10d08c04/src/spdk/mk/spdk.subdirs.mk:35: lib] Error 2
[  955s] make[2]: *** [CMakeFiles/spdk-ext.dir/build.make:112: spdk-ext-prefix/src/spdk-ext-stamp/spdk-ext-build] Error 2
[  955s] make[1]: *** [CMakeFiles/Makefile2:105: CMakeFiles/spdk-ext.dir/all] Error 2
[  955s] make: *** [Makefile:141: all] Error 2
```

Is this expected?

**Comment by wjwithagen** [comment]
@tchaikov 
I'm having a bit of trouble in FreeBSD jenkins as well:
```
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
In file included from contigmem.c:57:
/usr/srcs/head/src/sys/vm/vm_phys.h:122:10: error: use of undeclared identifier 'vm_cnt'
        return (vm_cnt.v_free_count += adj);
                ^
1 error generated.
*** Error code 1

Stop.
make[9]: stopped in /home/jenkins/workspace/ceph-master/build/src/dpdk/build/lib/librte_eal/bsdapp/contigmem
gmake[8]: *** [/home/jenkins/workspace/ceph-master/src/spdk/dpdk/mk/rte.bsdmodule.mk:84: contigmem.ko] Error 1
gmake[7]: *** [/home/jenkins/workspace/ceph-master/src/spdk/dpdk/mk/rte.subdir.mk:63: contigmem] Error 2
gmake[7]: *** Waiting for unfinished jobs....
```

**Comment by tchaikov** [comment]
@wjwithagen i suspect it's a bug in FreeBSD. see also https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=204426.

**Comment by asomers** [comment]
Try putting `#include <sys/vmmeter.h>` in contigmem.c, somewhere above line 57.

**Comment by tchaikov** [comment]
@smithfarm which sha1 you were building? `ceph-13.0.0-3535-g8b10d08c04` does look suspicious . as  i have
```
$ git describe
v12.1.2-4707-g2f39a15652
```

and on spdk.common.mk:171, it's related CXX compiling: https://github.com/spdk/spdk/commit/b17d4d91359078a00ec60e6016b8c5c9c6b41a91#diff-7c87b4059369ef6dd77486f206021f01R171 . and `bdev.c` is a C source file. this does not make sense.

**Comment by tchaikov** [comment]
@asomers thanks for chiming in. but IMHO, a public header file is supposed to be self-contained, and https://github.com/freebsd/freebsd/blob/master/sys/vm/vm_phys.h does not `#include` [vmmeter.h](https://github.com/freebsd/freebsd/blob/82974662ad9f9ece5f8374d2c898e83bd03aece9/sys/sys/vmmeter.h),  am i right?

**Comment by asomers** [comment]
@tchaikov FreeBSD doesn't always follow that rule.  There are many functions that require including multiple header files.  For example, [mount(2)](https://www.freebsd.org/cgi/man.cgi?query=mount&apropos=0&sektion=2&manpath=FreeBSD+11.1-RELEASE&arch=default&format=html) requires including two.  You just have to include whatever the man page tells you to include.  And in this case, SPDK is including header files that are normally only used within the kernel itself.  It's even apparently #defining `_KERNEL`.  When you do that, the gloves come off.

**Comment by tchaikov** [comment]
@asomers thank you for the detailed explanation! will send a PR to SPDK then.

**Comment by tchaikov** [comment]
@wjwithagen i sent a patch to DPDK upstream, in the meanwhile, you can watch the tracker ticket filed at http://tracker.ceph.com/issues/22278

**Comment by wjwithagen** [comment]
@tchaikov 
Will do. In the mean time I'll disable the SPDK on the builds

**Comment by wjwithagen** [comment]
@tchaikov @asomers 
So this means that building SPDK on FreeBSD will require kernel sources to be available.
Guess I have to start figuring out how that is done in package building with `poudriere`

**Comment by tchaikov** [comment]
@wjwithagen what exactly the FreeBSD version did you compile with? the upstream maintainer of SPDK replied to me that SPDK compiles fine with FreeBSD 10 and 11.

**Comment by asomers** [comment]
@wjwithagen for an example of a port that needs kernel sources, see [sysutils/graid5](https://svnweb.freebsd.org/ports/head/sysutils/graid5/Makefile?view=markup) or [sysutils/py-zfs](https://svnweb.freebsd.org/ports/head/sysutils/py-zfs/Makefile?view=markup).

**Comment by wjwithagen** [comment]
@tchaikov 
```
wjw@cephdev:~ % uname -a
FreeBSD cephdev.digiware.nl 12.0-CURRENT FreeBSD 12.0-CURRENT #15 r324142M: Sun Oct  1 08:19:29 CEST 2017     root@cephdev.digiware.nl:/usr/obj/usr/srcs/head/src/sys/GENERIC-NODEBUG  amd64
```

**Comment by tchaikov** [comment]
@wjwithagen ack.

**Pull request merged**
