### PR TITLE
[DNM] hammer: osd: filestore: FALLOC_FL_PUNCH_HOLE must be used with FALLOC_FL_KEEP_SIZE

### PR DESCRIPTION
**Pull request by mslovy**
http://tracker.ceph.com/issues/18448

### CODE REVIEW

**Comment by smithfarm** [comment]
@mslovy Please re-do the cherry-pick with `-x` and describe how you resolved any conflicts. Thanks!

**Comment by mslovy** [comment]
@smithfarm , this cherry-pick does not contain any conflicts

**Comment by smithfarm** [comment]
@mslovy Cool, so just do something like this:

```
git checkout wip-18446-hammer
git fetch ceph
git reset --hard ceph/hammer
git cherry-pick -x $SHA1
git push -f origin wip-18446-hammer
```

**Comment by mslovy** [comment]
git cherry-pick -x and repushed

**Comment by smithfarm** [comment]
@mslovy The commit you cherry-picked is not in master. Please re-do the cherry-pick again with `git cherry-pick -x 7bd95b595fddb8a4e618a2c7df1ba04eccf0829d` - thanks!

**Comment by smithfarm** [comment]
This passed a rados suite at http://tracker.ceph.com/issues/17151#note-46

**Comment by smithfarm** [comment]
Now I see there is a conflict - `FileStore.cc` moved. I'll do the backport myself, thanks.

**Comment by smithfarm** [comment]
Note for posterity: the version of this backport that was merged is #13041

**Pull request closed without merging**
