### PR TITLE
osd,librados: cmpext support

### PR DESCRIPTION
**Pull request by wangzhengyong**
This is a follow up to pr [14071](https://github.com/ceph/ceph/pull/14071)
The patch-set carries @ddiss and @mikechristie 's   implementation of OSD cmpext support,
The librados API and  testcase
According to the result of the conversationabove, I rebase the code on @ddiss 's repo, simply the librados API

### CODE REVIEW

**Comment by ddiss** [comment]
@wangzhengyong could you please rebase against my latest push to  https://github.com/ceph/ceph/pull/14071 - it includes the new (-1000 - miscompare_off) API, and reworks the tests atop that.

**Comment by tchaikov** [comment]
@wangzhengyong your signed-off-by lines do not look right, it could be
```
Signed-off-by: Zhengyong Wang <wangzhengyong@cmss.chinamobile.com>
```
if you like.

**Comment by wangzhengyong** [comment]
@tchaikov thx, I have already modified

**Comment by yuriw** [comment]
http://pulpito.ceph.com/yuriw-2017-04-25_19:49:20-rados-wip-yuri-testing2_2017_4_26-distro-basic-smithi/

http://pulpito.ceph.com/yuriw-2017-04-25_19:49:20-rados-wip-yuri-testing2_2017_4_26-distro-basic-smithi/

==============
CEPH_DISK

http://pulpito.ceph.com/yuriw-2017-04-26_03:20:49-ceph-disk-wip-yuri-testing2_2017_4_26-distro-basic-vps/

**Pull request merged**
