### PR TITLE
crush: add chooseleaf_stable tunable

### PR DESCRIPTION
**Pull request by liewegas**

### CODE REVIEW

**Comment by liewegas** [comment]
@Sandy4999 I separated this out into separate patches to improve review, added tests, and made a few fixes to the feature bits.  Please review!

@dachary Would be great if you could take a look too.  Thanks!

**Comment by Sandy4999** [comment]
@liewegas LGTM, thank you for the help!
Again to avoid the failure, we probably need newly encoded test CRUSHMaps/OSDMaps for test/encoding/readable.sh, or maybe just move the encode & decode steps of this new tunable to the end of all the other tunables.

**Comment by liewegas** [comment]
@Sandy4999 Oh right, yep.. repushed!

**Comment by dachary** [comment]
<pre>
crushtool: error reading '/home/jenkins/workspace/ceph/LABELS/ceph-centos-7-jenkins/src/test/cli/crushtool/test-map-hammer-tunables.crushmap': can't open /home/jenkins/workspace/ceph/LABELS/ceph-centos-7-jenkins/src/test/cli/crushtool/test-map-hammer-tunables.crushmap: (2) No such file or directory
</pre>

**Comment by dachary** [comment]
@liewegas it would be good to have a unit test verifying the expected difference between stable == 0 & stable == 1. The change is enough :-) There should also be an associated ceph-qa-suite test to verify it behaves as expected during upgrades ?

**Comment by liewegas** [comment]
@dachary that's what the jewel test mapping is supposed to show, although I just check it and I had made a mistake (chooseleaf_stable = 1 wasn't set in the jewel map).  Fixing that now.

**Comment by liewegas** [comment]
We don't have a good strategy for testing that the feature bits are enforced during upgrades.  :/

**Comment by dachary** [comment]
<pre>
Reviewed-by: Loic Dachary &lt;ldachary@redhat.com>
</pre>

**Pull request merged**
