### PR TITLE
rgw: fix debug build of OpsLogFile

### PR DESCRIPTION
**Pull request by cbodley**
can't use ceph::mutex locks with std::condition_variable::wait() in debug builds. use the ceph::condition_variable wrapper instead

```
... -DCEPH_DEBUG_MUTEX ... ../src/rgw/rgw_log.cc
../src/rgw/rgw_log.cc: In member function ‘virtual void* OpsLogFile::entry()’:
../src/rgw/rgw_log.cc:391:20: error: no matching function for call to ‘std::condition_variable::wait(std::unique_lock<ceph::mutex_debug_detail::mutex_debug_impl<false> >&)’
  391 |     cond_flush.wait(lock);
      |     ~~~~~~~~~~~~~~~^~~~~~
```

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by wjwithagen** [comment]
Arrrgh, just about the one thing I did not think of.
But it had to be something of this sort.
cephfi-fying all kinds of std::-stuff gets me every time

**Review by cfsnyder — APPROVED** [review]
thanks @cbodley !

**Review by wjwithagen — APPROVED** [review]
My Jenkins is happy again with this PR

**Review by mattbenjamin — APPROVED** [review]
approve, I guess;  I was not aware of the need for ceph versions of std::mutex or std::condition_variable;  I would prefer we use the standard types

**Comment by wjwithagen** [comment]
yes, and I guess that Clang pickyness, inc combination with libc++ makes it a compiler error, where GCC and lib allow for silent conversion.

**Comment by cbodley** [comment]
> approve, I guess; I was not aware of the need for ceph versions of std::mutex or std::condition_variable; I would prefer we use the standard types

@mattbenjamin i don't like those debug wrappers in general either. but in this case, `class OpsLogFile` is managing two different locks, so lockdep would at least catch any changes to lock ordering that might result in deadlock

> yes, and I guess that Clang pickyness, inc combination with libc++ makes it a compiler error, where GCC and lib allow for silent conversion.

@wjwithagen i was seeing this error with gcc and CMAKE_BUILD_TYPE=Debug. i'm not sure why the jenkins checks didn't catch it

**Comment by wjwithagen** [comment]
> > yes, and I guess that Clang pickyness, inc combination with libc++ makes it a compiler error, where GCC and lib allow for silent conversion.
> 
> @wjwithagen i was seeing this error with gcc and CMAKE_BUILD_TYPE=Debug. i'm not sure why the jenkins checks didn't catch it

@cbodley 
I'm running my Jenkins always with debug, so I get maximum info in case porting somewhere leaves a problem open. I remember some discussion on running Debug in the basic tests.... Something with image size being to large.

**Pull request merged**
