### PR TITLE
reef: cephfs: add command "ceph fs swap"

### PR DESCRIPTION
**Pull request by rishabh-d-dave**
backport tracker: https://tracker.ceph.com/issues/63834

---

backport of https://github.com/ceph/ceph/pull/50212
parent tracker: https://tracker.ceph.com/issues/58129

Also backports because these commits were necessary to have before PR #50212 could be backported - https://github.com/ceph/ceph/pull/50497, https://github.com/ceph/ceph/pull/50498, https://github.com/ceph/ceph/pull/50665, https://github.com/ceph/ceph/pull/50882

this backport was staged using ceph-backport.sh version 16.0.0.6848
find the latest version at https://github.com/ceph/ceph/blob/main/src/script/ceph-backport.sh

### CODE REVIEW

**Comment by yuriw** [comment]
@rishabh-d-dave pls rebase

**Comment by vshankar** [comment]
> @rishabh-d-dave pls rebase

@rishabh-d-dave ping?

**Comment by vshankar** [comment]
jenkins retest this please

**Comment by rishabh-d-dave** [comment]
jenkins test make check

**Comment by rishabh-d-dave** [comment]
jenkins test make check

**Comment by rishabh-d-dave** [comment]
jenkins test api

**Comment by batrick** [comment]
jenkins test make check

**Comment by batrick** [comment]
jenkins test windows

**Comment by batrick** [comment]
jenkins test api

**Comment by yuriw** [comment]
This PR is a suspect to break build @rishabh-d-dave per @vshankar 

https://shaman.ceph.com/builds/ceph/wip-yuri10-testing-2024-03-15-0748-reef/d02fc9718da759f895a8ebf87e693b5aed62f43e/default/386772/

**Comment by vshankar** [comment]
> This PR is a suspect to break build @rishabh-d-dave per @vshankar 
> 
> https://shaman.ceph.com/builds/ceph/wip-yuri10-testing-2024-03-15-0748-reef/d02fc9718da759f895a8ebf87e693b5aed62f43e/default/386772/

This PR would need a rebase once the PRs in the trello gets merged.

**Comment by yuriw** [comment]
Pls don't assign the milestone before it's fixed.

**Review by rishabh-d-dave — COMMENTED** [review]
QA run was successful - https://tracker.ceph.com/projects/cephfs/wiki/Reef#12-April-2024

**Review by mchangir — APPROVED** [review]
LGTM

**Comment by batrick** [comment]
Follow-up fix: https://github.com/ceph/ceph/pull/57373

Unfortunately the test run for the `tasks/admin` was masked by infrastructure noise.

**Comment by batrick** [comment]
https://tracker.ceph.com/issues/65970

**Pull request merged**
