### PR TITLE
mgr/dashboard: fix orchestrator/02-hosts-inventory.e2e failure

### PR DESCRIPTION
**Pull request by nizamial09**
I removed the `02-hosts-inventory.e2e` file because it is a duplicate
test of one of the test in the `01-hosts.e2e` file and fixed the error
from that file.

Also, in the inventory Identify test, we test for an element to be not
visible. According to the latest cypress docs, this should be `not.exist`
instead of `not.visible` since the cd-modal will not even be present in
the DOM

Fixes: https://tracker.ceph.com/issues/53499
Signed-off-by: Nizamudeen A <nia@redhat.com>

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [x] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by nizamial09** [comment]
jenkins test dashboard

**Comment by nizamial09** [comment]
jenkins test dashboard cephadm

**Comment by alfonsomthd** [comment]
Should this be backported to pacific?

**Review by epuertat — APPROVED** [review]
Looks good! Small suggestion: instead of decrementing the number of the remaining files, can't we let them as they are? I mean, just skipping the 02, and going to 03, 04, etc.? It's just to minimize the impact of changes: just for not running a single file we are touching 6.

**Comment by nizamial09** [comment]
> Should this be backported to pacific?

Yes.

**Comment by nizamial09** [comment]
> Looks good! Small suggestion: instead of decrementing the number of the remaining files, can't we let them as they are? I mean, just skipping the 02, and going to 03, 04, etc.? It's just to minimize the impact of changes: just for not running a single file we are touching 6.

Yup, I'll do that.

**Review by aaSharma14 — APPROVED** [review]

**Comment by epuertat** [comment]
> Yup, I'll do that but it felt odd missing a number between 01 and 03

No need: it's actually more important to use this numbering for univocally identifying tests by ID (or number) than keeping the sequence gapless (although we're actually using the numbering for another purpose here: setting the tests execution order). We barely use IDs for tests, but in other environments is pretty common to assign IDs to tests, so that you can see in which branches/releases that specific test unit is failing (Cypress allows you to do that, but in Jenkins/JUnit we're not leveraging that).

**Review by Waadkh7 — APPROVED** [review]

**Comment by nizamial09** [comment]
Jenkins test make check

**Comment by nizamial09** [comment]
Jenkins test dashboard

**Comment by nizamial09** [comment]
Jenkins test api

**Comment by alfonsomthd** [comment]
@nizamial09 Can you add a comment with the results of the QA run?

**Comment by alfonsomthd** [comment]
> @nizamial09 Can you add a comment with the results of the QA run?

QA run:
- Shaman build: https://shaman.ceph.com/builds/ceph/wip-nizamial09-testing-2021-12-31-1305/
- Pulpito: http://pulpito.front.sepia.ceph.com/alfonsomthd-2022-01-04_11:23:53-rados:dashboard-wip-nizamial09-testing-2021-12-31-1305-distro-default-smithi/

**Comment by nizamial09** [comment]
jenkins test windows

**Comment by nizamial09** [comment]
Looks like the teuthology is green 🥳

**Comment by nizamial09** [comment]
Looks like the teuthology is green 🥳

**Pull request merged**
