### PR TITLE
pacific: librbd/cache/pwl: fix clean vs bytes_dirty cache state inconsistency

### PR DESCRIPTION
**Pull request by idryomov**
backport tracker: https://tracker.ceph.com/issues/58076

---

backport of https://github.com/ceph/ceph/pull/48542
parent tracker: https://tracker.ceph.com/issues/57872

### CODE REVIEW

**Comment by idryomov** [comment]
make check is blocked on https://github.com/ceph/ceph/pull/49058

**Comment by idryomov** [comment]
jenkins test api

**Review by chrisphoffman — APPROVED** [review]

**Comment by ljflores** [comment]
Rados suite review by @amathuria:

https://pulpito.ceph.com/?branch=wip-yuri10-testing-2022-11-28-1042-pacific

Failures, unrelated:
    1. https://tracker.ceph.com/issues/53501 - Failure: [Errno 2] Cannot find file on the remote 'ubuntu@smithi187.front.sepia.ceph.com': 'rook/cluster/examples/kubernetes/ceph/operator.yaml'
    2. https://tracker.ceph.com/issues/44595 - src/test/osd/RadosModel.h: 1942: ceph_abort_msg("abort() called")
    3. https://tracker.ceph.com/issues/58114 - mon: FAILED ceph_assert(rank == new_rank)
    4. https://tracker.ceph.com/issues/58097 - qa/workunits/post-file.sh: kex_exchange_identification: read: Connection reset by peer
    5. https://tracker.ceph.com/issues/58046 - qa/workunits/rados/test_librados_build.sh: specify redirect in curl command
    6. https://tracker.ceph.com/issues/51372 - pacific: libcephsqlite: segmentation fault
    7. https://tracker.ceph.com/issues/54071 - rados/cephadm/osds: Invalid command: missing required parameter hostname(<string>)
    8. https://tracker.ceph.com/issues/58130 -- rados_api_tests: HEALTH_WARN: Degraded data redundancy: 1/5 objects degraded (20.000%), 1 pg degraded - Ceph - RADOS

**Comment by ljflores** [comment]
jenkins test make check

**Comment by ljflores** [comment]
jenkins test make check

**Comment by idryomov** [comment]
jenkins test make check

**Comment by idryomov** [comment]
Unrelated make check failure persists:
```
CMake Error at /usr/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find Python3 (missing: Python3_LIBRARY Python3_INCLUDE_DIR
  Development) (found suitable exact version "3.8.10")
Call Stack (most recent call first):
  /usr/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  cmake/modules/FindPython/Support.cmake:1181 (find_package_handle_standard_args)
  cmake/modules/FindPython3.cmake:181 (include)
  CMakeLists.txt:485 (find_package)
```

**Pull request merged**
