### PR TITLE
Wip erasure common

### PR DESCRIPTION
**Pull request by aclamk**
This work is continuation of Ved-vampir:wip_erasure_common.
Now it compiles with cmake.

Previous pull request: #7661

### CODE REVIEW

**Comment by tchaikov** [comment]
needs rebase.

**Comment by dachary** [comment]
@Ved-vampir the https://jenkins.ceph.com/job/ceph-pull-requests/9939/ looks like it contains real errors, what do you think ?

**Comment by aclamk** [comment]
vstart.sh got broken. #10544 fixes it.

**Comment by aclamk** [comment]
Hey, jenkins test this please (will it work if I am uttering the spell?)

**Comment by dachary** [comment]
Hey, jenkins test this please

**Comment by liewegas** [comment]
needs rebase

**Comment by aclamk** [comment]
Rebased.

**Comment by dachary** [comment]
@aclamk do you see the same error when you run make check locally ?

**Comment by aclamk** [comment]
My make check gives following problems:
The following tests FAILED:
	 15 - run-tox-ceph-detect-init (Failed)
	133 - osd-scrub-snaps.sh (Failed)
	143 - test_ceph_daemon.py (BAD_COMMAND)
	144 - test_ceph_argparse.py (BAD_COMMAND)

**Comment by dachary** [comment]
@aclamk they need to be looked at. As far as I can tell the only transient error that could be unrelated to your changes is with unittest_bluestore. Let me know if the interpretation of the failures cause you trouble, I'd be happy to help :-)

**Comment by aclamk** [comment]
I am sorry. I was under impression that I did not introduce anything new.
I will start from master and recheck to get reference point.
Sorry, but it will take time (my machine is slow), ~2-3h.

**Comment by aclamk** [comment]
I have following on master:
	148 - unittest_rbd_mirror (OTHER_FAULT)
Is it typical?
I configured it with ./do_cmake.sh WITH_RBD=1

**Comment by dachary** [comment]
@aclamk could you paste2.org the full log of the error you get ?

**Comment by dachary** [comment]
https://jenkins.ceph.com/job/ceph-pull-requests/12019/ are the logs of the previous run of make check, jenkins test this please so we know what's transient and what's not

**Comment by dachary** [comment]
@aclamk this needs rebasing. The pull request that was merged is large but not complex, it should not be too much work.

**Comment by aclamk** [comment]
Rebased.

**Comment by dachary** [comment]
pushed in gitbuilders as wip-pr-10504

**Comment by dachary** [comment]
<pre>
teuthology-suite -k distro --suite rados --subset $(expr $RANDOM % 2000)/2000 --suite-branch master --email loic@dachary.org --ceph wip-pr-10504 --machine-type smithi
</pre>

* **running**

**Comment by dachary** [comment]
http://gitbuilder.sepia.ceph.com/gitbuilder-ceph-rpm-centos7-amd64-basic/log.cgi?log=8442d99333f5c6fbf82393c68a7569f31a8cca1c has a failure
<pre>
equires(post): binutils
Processing files: ceph-base-11.0.0-3150.g8442d99.x86_64

    error: File not found by glob: /srv/autobuild-ceph/gitbuilder.git/build/rpmbuild/BUILDROOT/ceph-11.0.0-3150.g8442d99.x86_64/usr/lib64/ceph/erasure-code/libec_*.so* 

RPM build errors:
File not found by glob: /srv/autobuild-ceph/gitbuilder.git/build/rpmbuild/BUILDROOT/ceph-11.0.0-3150.g8442d99.x86_64/usr/lib64/ceph/erasure-code/libec_*.so* 
</pre>

that prevents testing. It took a while to get there because of build troubles last week and yesterday I assumed (wrongly) that the centos 7 build failure was because of last week troubles.

**Comment by dachary** [comment]
@aclamk ping ?

**Comment by aclamk** [comment]
@dachary 
I will take it, rebase and fix. Today.

**Comment by dachary** [comment]
@aclamk ping ?

**Comment by dachary** [comment]
@aclamk ping ?

**Comment by dachary** [comment]
@aclamk feel free to reopen whenever you have time

**Pull request closed without merging**
