### PR TITLE
mgr/cephadm: adding support to copy ceph conf to per fsid config location

### PR DESCRIPTION
**Pull request by rkachach**
Fixes: https://tracker.ceph.com/issues/55685

Signed-off-by: Redouane Kachach <rkachach@redhat.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/master/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [x] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [x] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by rkachach** [comment]
jenkins test make check

**Review by adk3798 — APPROVED** [review]
LGTM, do we also want to now add the documentation we postponed here https://github.com/ceph/ceph/pull/45877#issuecomment-1097949698?

**Comment by rkachach** [comment]
> LGTM, do we also want to now add the documentation we postponed here [#45877 (comment)](https://github.com/ceph/ceph/pull/45877#issuecomment-1097949698)?

yes, that's the next step and it would go on a separate PR to update the documentation :+1:

**Comment by adk3798** [comment]
https://pulpito.ceph.com/adking-2022-05-19_03:28:17-orch:cephadm-wip-adk-testing-2022-05-18-1703-distro-basic-smithi/

1 failure on new staggered upgrade test, unrelated to this PR

**Comment by adk3798** [comment]
gave this a test. Config and keyring were written to /var/lib/ceph<fsid>/config/ on _admin hosts as expected. You could even see it inferring the conf and keyring from that directory (both with and without me manually deleting the one from /etc/ceph)

**Pull request merged**
