### PR TITLE
pacific: cephadm: October batch

### PR DESCRIPTION
**Pull request by sebastian-philipp**
Backport of #42970, #43021, #43039, #43010, #42989, #42859, #43143, #43141, #43115, #43162, #43142, #43237, #43062, #43121, #43275, #43298, #43294, #43160, #43150, #43319, #43309, #43246, #43356, ~~43202~~, #41445, #43401, #43450, #43376 (incomplete), #43490, #43339, #43253, #43214, #43073, #43332, #43564, #43510, #43569, ~~43556~~, #43552, #43366, #42772, #43616, #43604, #43579, #43499, #43560, #43622, #43601, #43330, #43692, #43693, #43260

```
$ git log -n 90 | grep ... Conflicts
commit 450170decd3cea17c44d4b22061bb0a6868065f4
    mgr/orchestrator: add --zap flag to 'orch osd rm'
    Conflicts:
            src/pybind/mgr/cephadm/module.py
            src/pybind/mgr/rook/module.py
commit ab52c56027631221f75e1d2e9226f2754ef88b94
    mgr/cephadm: Monitoring: Verify config file generation
    Conflicts:
            src/pybind/mgr/cephadm/tests/test_services.py
commit a92f06d81a0fb2fba9b2c1c53f1d00915ef9f451
    mgr/cephadm: Monitoring: Grafana: Fix IPv6
    Conflicts:
            src/pybind/mgr/cephadm/tests/test_ssh.py
commit 5e440d905324085217ef03478016ee9dd82dedc7
    mgr/cephadm: set health check warning for apply spec failures and daemon place failures in serve
    Conflicts:
            src/pybind/mgr/cephadm/module.py
            src/pybind/mgr/cephadm/serve.py
commit 29f1cbff49f7e844f35c9a6d9a5014b306f3c7bc
    mgr/cephadm: populate trusted_ip_list in iscsi-gateway.cfg with mgr ips
    Conflicts:
            src/pybind/mgr/cephadm/module.py
commit a0e201b61141259c4bc8de6e6f817cbe89bc2969
    mgr/cephadm: unit tests for maintenance enter/exit properly handling success/failure messages
    Conflicts:
            src/pybind/mgr/cephadm/tests/test_cephadm.py
```

changelog: 

* Dropped #43556 (needs nvme task in pacific)
* Dropped #43202 (no signed-off-by line)
* Dropped a86d0db81d (breaks the upgrade from Octopus)

### CODE REVIEW

**Comment by sebastian-philipp** [comment]
jenkins test docs

**Comment by sebastian-philipp** [comment]
https://pulpito.ceph.com/swagner-2021-11-02_13:14:41-rados:cephadm-wip-swagner2-testing-2021-11-02-1006-pacific-distro-basic-smithi/ passed

**Review by adk3798 — APPROVED** [review]
Gave it all a quick look over. Everything seemed okay.

**Comment by neha-ojha** [comment]
> https://pulpito.ceph.com/swagner-2021-11-02_13:14:41-rados:cephadm-wip-swagner2-testing-2021-11-02-1006-pacific-distro-basic-smithi/ passed

@sebastian-philipp https://pulpito.ceph.com/swagner-2021-11-02_13:14:41-rados:cephadm-wip-swagner2-testing-2021-11-02-1006-pacific-distro-basic-smithi/6477683/ - this test is failing because it is not a valid teuthology test, I think we need https://github.com/ceph/ceph/pull/43556 (fully or partly) in pacific, which https://github.com/ceph/ceph/pull/43260 was building on top of.

**Comment by sebastian-philipp** [comment]
Overlooked this one. Thanks Naha!

**Pull request merged**
