### PR TITLE
erasure-code: sync jerasure/gf-complete submodules

### PR DESCRIPTION
**Pull request by dachary**
Minor changes (leak, compilation warnings).

Signed-off-by: Loic Dachary <loic@dachary.org>

### CODE REVIEW

**Comment by dachary** [comment]
@badone could you please verify the changes you need are here ?

**Comment by dachary** [comment]
<pre>
//home/jenkins-build/build/workspace/ceph-pull-requests/qa/workunits/ceph-helpers.sh:1065: get_num_active_clean:  expression+=')'
//home/jenkins-build/build/workspace/ceph-pull-requests/qa/workunits/ceph-helpers.sh:1069: get_num_active_clean:  ceph --format xml pg dump pgs
//home/jenkins-build/build/workspace/ceph-pull-requests/qa/workunits/ceph-helpers.sh:1070: get_num_active_clean:  xmlstarlet sel -t -m '//pg_stat/state[(contains(.,'\''active'\'') and contains(.,'\''clean'\'') and not(contains(.,'\''stale'\'')))]' -v . -n
//home/jenkins-build/build/workspace/ceph-pull-requests/qa/workunits/ceph-helpers.sh:1071: get_num_active_clean:  grep -cv '^$'
/home/jenkins-build/build/workspace/ceph-pull-requests/qa/workunits/ceph-helpers.sh:1156: is_clean:  test 4 = 4
/home/jenkins-build/build/workspace/ceph-pull-requests/qa/workunits/ceph-helpers.sh:1166: test_is_clean:  return 1
/home/jenkins-build/build/workspace/ceph-pull-requests/qa/workunits/ceph-helpers.sh:1648: run_tests:  return 1
</pre>

**Comment by dachary** [comment]
jenkins test this please (see above error, verifying it's transient)

**Comment by dachary** [comment]
jenkins test this please  (ceph objectstore tool transient failure)

**Comment by badone** [comment]
`E: dpkg was interrupted, you must manually run 'sudo dpkg --configure -a' to correct the problem. 
Using apt-get to install dependencies
E: dpkg was interrupted, you must manually run 'sudo dpkg --configure -a' to correct the problem. 
Build step 'Execute shell' marked build as failure`

No idea.

Jenkins test this please.

**Pull request merged**
