### PR TITLE
cmake changes

### PR DESCRIPTION
**Pull request by tchaikov**

### CODE REVIEW

**Comment by wjwithagen** [comment]
@tchaikov 
I do like this restructuring. Makes things way much more hierarchical.
And excluding certain modules will go way much easier.

**Comment by alimaredia** [comment]
@tchaikov this looks good to me, you wisely chose to leave libcommon in the src directory! you're not adding anything else to this PR right?

**Comment by tchaikov** [comment]
i put all the changes i added in the commit messages.
Ali Maredia <notifications@github.com>于2016年7月20日 周三01:41写道：

**Comment by dmick** [comment]
This appears to have broken the debian build at least: 

cp -a debian/tmp/usr/include/rados/buffer.h debian/librados-dev//usr/include/rados/
cp: cannot stat ‘debian/tmp/usr/include/rados/buffer.h’: No such file or directory

**Comment by tchaikov** [comment]
thanks @dmick,  i am on it.

**Comment by tchaikov** [comment]
@dmick #10360 address the packaging failure.

**Pull request merged**
