### PR TITLE
hammer: cephx: Fix multiple segfaults due to attempts to encrypt or decrypt

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/17346

### CODE REVIEW

**Comment by smithfarm** [comment]
@tchaikov @badone This backport passed a rados suite at http://tracker.ceph.com/issues/17151#note-7 with failures that I believe have been addressed (except for http://tracker.ceph.com/issues/15139 which is caused by the build system no longer providing dumpling-era packages).

I have rebuilt the integration branch to include the two fixes and scheduled a new run at http://tracker.ceph.com/issues/17151#note-14

Do you think it's OK to merge provided the second run succeeds?

**Comment by badone** [comment]
Hey @smithfarm, thsnkd for working on this. I don't think any of the failures are directly related to this patch right? If they are unrelated I don't see any reason why we can't merge.

**Comment by smithfarm** [comment]
@badone Right, the failures are not related to this PR.

**Comment by smithfarm** [comment]
Second run succeeded; third run here: http://pulpito.front.sepia.ceph.com/smithfarm-2016-11-21_11:52:41-rados-hammer-backports---basic-smithi/

**Comment by tchaikov** [comment]
@smithfarm lgtm.

**Pull request merged**
