### PR TITLE
mds: update imported_inodes counter by removing inappropriate initialization

### PR DESCRIPTION
**Pull request by yongseokoh**
As num_imported variable is redefined in Migrator::decode_import_dir(), imported_inodes counter is not updated. 

fixes: https://tracker.ceph.com/issues/59107

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [x] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by dparmar18** [comment]
the change this PR alters is part of 92f7e6e053a3 which says "trunk/ceph/mds/Migrator.cc". I'm not sure about the idea behind it but 9a193ec3bc9442ef334eaff31f0d89df0d5ea2c2 brought in the arg `int &num_imported` to `Migrator::decode_import_dir`, thus invalidating `int num_imported = 0;`. This removal makes sense to me.

**Comment by yongseokoh** [comment]
I'll identify the suitable location to insert a new test case that will confirm whether the metric has been updated. Do we have to check exported/imported* related metrics?

**Comment by dparmar18** [comment]
> I'll identify the suitable location to insert a new test case that will confirm whether the metric has been updated. Do we have to check exported/imported* related metrics?

I think checking for `imported_inodes` should suffice, Tagging @batrick @gregsfortytwo @lxbsz as I see their contributions  in this code,  would be good to have their opinion about this.

**Comment by vshankar** [comment]
LGTM

**Comment by rishabh-d-dave** [comment]
> @rishabh-d-dave please pick this one with your tests once the changes are updated.

@vshankar ACK

**Comment by vshankar** [comment]
> > @rishabh-d-dave please pick this one with your tests once the changes are updated.
> 
> @vshankar ACK

@rishabh-d-dave I'm including this in my test run.

**Comment by vshankar** [comment]
This would need a retest since there are failing tests in main branch which is being tracked by: https://tracker.ceph.com/issues/59534

**Comment by gregsfortytwo** [comment]
This change looks fine to me, but a bit more explanation in the commit (or a function comment) about the problem, and why it's okay to remove the initialization, would be good. I had to go check that the only caller here already inits to zero and that we can call the function in a loop. :)

**Comment by vshankar** [comment]
Running tests now: https://pulpito.ceph.com/vshankar-2023-05-09_12:06:46-fs-wip-vshankar-testing-20230509.090020-testing-default-smithi/

@yongseokoh https://github.com/ceph/ceph/pull/50594#issuecomment-1526772731

**Review by vshankar — APPROVED** [review]
https://tracker.ceph.com/projects/cephfs/wiki/Main#15-May-2023

**Comment by yongseokoh** [comment]
@vshankar I have added explanations about the problem in the commit.

**Comment by vshankar** [comment]
jenkins retest this please

**Comment by yongseokoh** [comment]
jenkins retest this please

**Comment by vshankar** [comment]
jenkins test make check arm64

**Pull request merged**
