### PR TITLE
[DNM] (cherry picked from commit 85bb43e111692989d2296a389ce45377d2297d6f)

### PR DESCRIPTION
**Pull request by diluga**
RGW: add socket backlog setting for via ceph.conf
http://tracker.ceph.com/issues/16436
Signed-off-by: Feng Guo <diluga@gmail.com>

### CODE REVIEW

**Comment by tchaikov** [comment]
should "cherry-pick -x 3e4df832d34c782795a32b5a30f5c7414a1c3fa9".  please fix your commit message and its title.

**Comment by smithfarm** [comment]
@yehudasa OK to backport this feature to jewel?

**Comment by smithfarm** [comment]
The master PR is #9891

**Comment by yehudasa** [comment]
@smithfarm fine with me

**Comment by smithfarm** [comment]
@diluga As @tchaikov wrote, the command is `git cherry-pick -x 3e4df83` - you are trying to cherry-pick 85bb43e which is the merge commit. That will not work. Once you cherry-pick the correct commit, you will not need to modify the commit message at all, except as described below. 

Here is a more detailed HOWTO:

1. checkout the latest hammer branch
2. `git checkout -b wip-16436-hammer`
3. `git cherry-pick -x 3e4df83`  <- don't modify the commit message unless there are conflict(s). If there are conflicts, just append a brief description of how you resolved the conflict(s).
4. `git push -u origin wip-16436-hammer`
5. open PR against hammer

Hope this helps, and thanks for contributing!

**Comment by smithfarm** [comment]
@diluga I staged the jewel backport at #10216 if you want to look.

**Comment by diluga** [comment]
@smithfarm  thx,a lot! i followed with your guide，and the new PR: https://github.com/ceph/ceph/pull/10219

**Comment by smithfarm** [comment]
@diluga You're welcome! I looked at the commit message in #10219 and there is no description of how the conflicts were resolved. Anyway, don't do anything more until we clarify whether this feature is eligible for backport to hammer at all - it looks like it depends on c52a9fad0a3354f1004716038e3f7190dd9a1d61

**Pull request closed without merging**
