### PR TITLE
osd: filestore merge threadhold and split multiple defaults made ideal

### PR DESCRIPTION
**Pull request by nvedant07**
Fixes : http://tracker.ceph.com/issues/17043
Signed-off-by : Vedant Nanda <vedant15114@iiitd.ac.in>

### CODE REVIEW

**Comment by gregsfortytwo** [comment]
Any change like this needs a great deal of evidence proving that it's better. I think @markhpc has demonstrated a lot of ways increases can be very bad for us. :(
Marking this as closed, but feel free to reopen if you can provide demonstrative proof this is a better default. :)

**Comment by nvedant07** [comment]
@gregsfortytwo How about this(http://tracker.ceph.com/issues/15835) issue then? Wouldn't a random value(say, from 1 to 5) also create problems?

**Comment by gregsfortytwo** [comment]
Oh, I just realized I misread what this was doing — reducing how quickly we merge, but keeping the split threshold the same.

Can you comment about why you think this change is better? Or were you just implementing the ticket, which you'll notice Josh says he's investigating for performance. ;)

**Comment by nvedant07** [comment]
Oh I was just implementing the ticket, though I thought reducing the number of times we merge would increase the overall performance, however, now that you mention it, it really isn't this trivial . 
Sure, Josh would be the right person to decide if this is actually better :)

**Comment by jdurgin** [comment]
I haven't had time to test these effects, and at this point I think any effort around it is better spent on bluestore. If you're looking for a simple bug to fix, check out http://tracker.ceph.com/issues/19400

**Comment by nvedant07** [comment]
@jdurgin here's the PR for http://tracker.ceph.com/issues/19400

**Pull request closed without merging**
