### PR TITLE
mgr/mirroring: remove unnecessary fs_name arg from `daemon status` command

### PR DESCRIPTION
**Pull request by vshankar**
## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Review by leseb — COMMENTED** [review]
Is this backward compatible?

**Comment by vshankar** [comment]
> Is this backward compatible?

Nope. Does rook rely on this? The interface itself would not make sense with the file system name as its intended to show daemon status as a whole.

**Comment by leseb** [comment]
> > Is this backward compatible?
> 
> Nope. Does rook rely on this? The interface itself would not make sense with the file system name as its intended to show daemon status as a whole.

Yes, but we can change the CLI depending on the version. I just wanted to know if I had to do anything :)

**Review by batrick — APPROVED** [review]

**Comment by batrick** [comment]
jenkins test make check arm64

**Comment by tchaikov** [comment]
jenkins test make check arm64

**Comment by batrick** [comment]
https://tracker.ceph.com/projects/cephfs/wiki/Master#2021-September-10

**Pull request merged**
