### PR TITLE
os/bluestore: introduce new BlueFS perf counter to track the amount of

### PR DESCRIPTION
**Pull request by ifed01**
data written to slow device.

Signed-off-by: Igor Fedotov <ifedotov@suse.com>

### CODE REVIEW

**Comment by ifed01** [comment]
retest this please

**Comment by liewegas** [comment]
needs rebase

**Comment by ifed01** [comment]
rebased.

**Comment by tchaikov** [comment]
http://pulpito.ceph.com/kchai-2018-06-29_01:58:46-rados-wip-kefu-testing-2018-06-28-2341-distro-basic-smithi/

**Comment by tchaikov** [comment]
retest this please.

**Pull request merged**
