### PR TITLE
debian: fix logrotate on upgrade on upgrade from Debian

### PR DESCRIPTION
**Pull request by Fabian-Gruenbichler**
Debian Stretch (and probably recent Ubuntu releases as
well) ship a ceph-common package containing a logrotate
script. The logrotate script is shipped in ceph-base under a
different name in the official packages built from git,
which leads to logrotate complaining about multiple
logrotate snippets watching the same files.

Using dpkg-maintscript-helper, the ceph-common logrotate
file is preserved (including any potential user changes) in
a way which logrotate ignores (suffixed with .dpkg-bak). In
case the switch over / upgrade fails and is aborted, the old
ceph-common logrotate file is automatically restored.

Fixes: http://tracker.ceph.com/issues/15569

Signed-off-by: Fabian Grünbichler <f.gruenbichler@proxmox.com>

### CODE REVIEW

**Comment by Fabian-Gruenbichler** [comment]
Note: this only fixes the crossgrade from Ubuntu's/Debian's packaging, and not the original, very similar issue for the uncleanly handled split of ceph into ceph-base and other ceph-XYZ packages. I've updated the Fixes: line to reference http://tracker.ceph.com/issues/19938 instead of http://tracker.ceph.com/issues/15569

**Comment by liewegas** [comment]
"The logrotate script is shipped in ceph-base under a different name in the official packages built from git,"

Is the problem that we're doing something differently than/inconsistent with downstream, or that there was breakage from the package split/transition?

If this is just cleaning up the one-time upgrade transition, then we should only need to put it in jewel, since all upgrades must pass through jewel?  If it's an ongoing difference with downstream, can we get back in sync?

**Comment by Fabian-Gruenbichler** [comment]
there are two separate issues with the same symptom:

1. the logrotate script was incorrectly moved from the "ceph" package to the "ceph-base" package ("official"/upstream packaging in git/ceph.com)

2. the logrotate script is part of ceph-common in (some?) downstream packages (at least in Debian Stretch, not sure about which Ubuntu releases are/were based on that?)

issue 1 happened somewhere between Hammer and Jewel IIRC, and was just a case of moving a conffile between packages and renaming it at the same time, which is not really supported by Debian tooling. this could be cleaned up with a one-time fix to >= Jewel, similar to my changes proposed in this PR (but with a different file name and package).

issue 2 can also be solved by getting downstream and upstream in sync again (moving upstream's logrotate script to the downstream location seems more likely given that Stretch is about to be released and has been frozen for the last couple of months) - but that would require the same cleanup steps (again, with switched around packages and file names) anyhow, so not sure whether it is worth it? I guess that systems are rarely switching back and forth between downstream and upstream packages, and that the main issue is that deployment/provisioning tools will setup the base OS and software first, which might pull in some ceph packages (including ceph-common) as dependencies, and then run ceph-deploy / set up the download.ceph.com repository manually, effectively switching over from downstream to upstream but never actually having used the downstream ones..

**Comment by javacruft** [comment]
The rationale for logrotate in ceph-common is under:

  https://bugs.launchpad.net/landscape/+bug/1609866

specifically using this package ensured that the radosgw log files also got rotated.

This is the case for ceph in >= Ubuntu 16.04; I think it would be good if we could align the upstream ceph packages todo the same.

**Comment by Fabian-Gruenbichler** [comment]
sounds reasonable, I guess I'll prepare a new PR moving the logrotate script to ceph-common, and cleaning it up in ceph-base. it does mean that users which have manually modified it will need to re-apply those changes from the saved .dpkg-bak file (which they are pointed to by the "apt(-get) upgrade" output).

**Comment by Fabian-Gruenbichler** [comment]
superseded by #15567

**Pull request closed without merging**
