### PR TITLE
octopus: mgr/dashboard: Temporary User Lockout if 10 Invalid Login attempts

### PR DESCRIPTION
**Pull request by callithea**
backport tracker: https://tracker.ceph.com/issues/48794

---

backport of https://github.com/ceph/ceph/pull/38316
parent tracker: https://tracker.ceph.com/issues/40914

this backport was staged using ceph-backport.sh version 16.0.0.6848
find the latest version at https://github.com/ceph/ceph/blob/master/src/script/ceph-backport.sh

### CODE REVIEW

**Review by nizamial09 — COMMENTED** [review]
@callithea There's already a backport for the same . https://github.com/ceph/ceph/pull/38810 But it points to a different tracker I think.

**Comment by nizamial09** [comment]
Oh looks like I forgot to update the tracker, sorry @callithea

**Comment by callithea** [comment]
> @callithea There's already a backport for the same . https://github.com/ceph/ceph/pull/38810 But it points to a different tracker I think.

@nizamial09 thanks for letting me know! :)
I'll close this one then and will leave a note in the tracker issue.

**Comment by callithea** [comment]
> Oh looks like I forgot to update the tracker, sorry @callithea 

Ah okay, no worries!

**Comment by nizamial09** [comment]
Thanks @callithea

**Pull request closed without merging**
