### PR TITLE
mds: allow client to request caps when opening file

### PR DESCRIPTION
**Pull request by ukernel**
Allow client to request xattrs while opening file. MDS adds xattrs
and corresponding caps to the reply. This is important for selinux
on kcephfs.

Fixes: #14360
Signed-off-by: Yan, Zheng <zyan@redhat.com>

### CODE REVIEW

**Comment by gregsfortytwo** [comment]
This needs a qa-suite test.

Also, it doesn't seem to include the bits for actually sending back xattrs on an open?

**Comment by ukernel** [comment]
the new line "mdr->getattr_caps = mask" in handle_client_open() does the trick

**Comment by gregsfortytwo** [comment]
Oh, because that's used in encode_inodestat() to include the xattrs on reply.

Still needs a test though. :)

**Comment by ukernel** [comment]
https://github.com/ceph/ceph-qa-suite/pull/876

**Comment by gregsfortytwo** [comment]
Test failed: http://pulpito.ceph.com/gregf-2016-03-16_13:01:47-fs-greg-fs-testing-316---basic-mira/66370/

**Comment by gregsfortytwo** [comment]
@ukernel, also http://pulpito.ceph.com/gregf-2016-03-16_13:01:47-fs-greg-fs-testing-316---basic-mira/66414/

**Comment by gregsfortytwo** [comment]
Oh, didn't read closely enough. Looks like it just needs to run against a different conf file.

>2016-03-16T13:15:26.261 INFO:tasks.cephfs_test_runner:Only have 1 clients, require 2

**Comment by gregsfortytwo** [comment]
Pushed a quick change moving the test into multiclient and will test again.

**Comment by gregsfortytwo** [comment]
http://pulpito.ceph.com/gregf-2016-03-23_23:07:15-fs-greg-fs-testing-323-3---basic-mira/ and http://pulpito.ceph.com/gregf-2016-03-24_15:09:06-fs-greg-fs-testing-323-3---basic-mira/

**Pull request merged**
