### PR TITLE
rgw: fix deadlock on lru evicting

### PR DESCRIPTION
**Pull request by yaozongyou**
fh_lru.insert may evict RGWFileHandle and the mutex
for TreeX::Partition will be acquired a second time,
so we should use recursive_mutex instead. And the
insert_commit_data in struct Latch becomes invalid
after evicting.

Fixes: http://tracker.ceph.com/issues/22736

Signed-off-by: Yao Zongyou <yaozongyou@vip.qq.com>

### CODE REVIEW

**Comment by yaozongyou** [comment]
@mattbenjamin may you please have a look at this?

**Comment by mattbenjamin** [comment]
@yaozongyou I don't think changing the locking design is the right way to address this problem;  I'll see if I can reproduce the issue from the instructions in the tracker--I appreciate the detail

**Comment by mattbenjamin** [comment]
@yaozongyou I have been fighting with nfs-ganesha to properly test the recycle case, but do you see a problem with https://github.com/ceph/ceph/pull/20034 ?

**Comment by yaozongyou** [comment]
@mattbenjamin your solution is great and brilliant, thanks.

**Pull request closed without merging**
