### PR TITLE
luminous: common: data race in OutputDataSocket

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/40266

### CODE REVIEW

**Comment by smithfarm** [comment]
So, no `std::scoped_lock` in luminous. What to do?

**Comment by cbodley** [comment]
> So, no `std::scoped_lock` in luminous. What to do?

std::lock_guard should be equivalent here

**Comment by smithfarm** [comment]
> std::lock_guard should be equivalent here

I guess you mean `Mutex::Locker` (no `std::lock_guard` in luminous, either, IIRC)

**Comment by yuriw** [comment]
[wip-yuri2-testing-2019-10-13-1539-luminous](https://trello.com/c/xIDdD4pF/717-wip-yuri2-testing-2019-10-13-1539-luminous)

**Pull request merged**
