### PR TITLE
kraken: tests: fix upgrade/hammer-jewel-x

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/20348

### CODE REVIEW

**Comment by tchaikov** [comment]
sorry, i missed this. will review this PR tmr.

**Comment by smithfarm** [comment]
@tchaikov Please review https://github.com/ceph/ceph/pull/14612 instead - that one needs to go in first.

**Comment by tchaikov** [comment]
@smithfarm will do, it will take longer..

**Comment by smithfarm** [comment]
@yuriw I haven't had time yet to look at `upgrade/hammer-jewel-x`, unfortunately. But here we are.

**Comment by smithfarm** [comment]
Kraken is EOL.

**Pull request closed without merging**
