### PR TITLE
cmake/FindRocksDB: fix IMPORTED_LOCATION for ROCKSDB_LIBRARIES 

### PR DESCRIPTION
**Pull request by DengkeDu**
Signed-off-by: dudengke <pinganddu90@gmail.com>

- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by tchaikov** [comment]
could you prefix the title of your commit message with the subcomponent your are changing ? see https://github.com/ceph/ceph/blob/master/SubmittingPatches.rst#3-describe-your-changes . int this case, it would be "cmake:"

**Comment by tchaikov** [comment]
```
[ RUN      ] ObjectStore/StoreTest.SimpleCloneTest/0
2019-03-27 03:02:35.570 7f326fc81080  1 memstore(memstore.test_temp_dir) mkfs new fsid 0e989c82-73c4-4a8b-ab88-2b94046f1f74
2019-03-27 03:02:35.570 7f326fc81080 -1 memstore(memstore.test_temp_dir) memstore.test_temp_dir
2019-03-27 03:02:35.570 7f326fc81080  0 memstore(memstore.test_temp_dir) dump:{
    "collections": []
}
Creating collection meta

Creating object and set attr #-1:de000000::key:Object 1:head#
Clone object and rm attr
Invalid rm coll

[WARNING] /home/jenkins-build/build/workspace/ceph-pull-requests/src/googletest/googletest/src/gtest-death-test.cc:836:: Death tests use fork(), which is unsafe particularly in a threaded context. For this test, Google Test detected 4 threads.


99% tests passed, 1 tests failed out of 173

Total Test time (real) = 3600.07 sec

The following tests FAILED:
	  3 - test_objectstore_memstore.sh (Timeout)
```

retest this please.

**Comment by tchaikov** [comment]
https://shaman.ceph.com/builds/ceph/wip-kefu-testing-2019-03-27-1023/e11ba34ef9f5ebdeec89cdbd15d506e7fa195725/

**Comment by shaba** [comment]
backport to nautilus, please.

**Comment by tchaikov** [comment]
@shaba i filed http://tracker.ceph.com/issues/38992 to track the backport. next time, probably you could instead create a tracker ticket so we don't miss the request.

**Pull request merged**
