### PR TITLE
Tempest tests Keystone Fix

### PR DESCRIPTION
**Pull request by alimaredia**
## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by dang** [comment]
You should probably squash the SQUASHME commits?

**Comment by alimaredia** [comment]
@dang I was thinking once I got approval I'd squash the commits.

Here is a run from the last https://pulpito.ceph.com/amaredia-2023-06-14_22:03:28-rgw:tempest-main-distro-default-smithi/

@cbodley I was hoping to pin the tempest suite on `ubuntu_latest` but the builds for main for jammy are not building right now. Should I wait until those issues are resolved and try to pin the subsuite to `ubuntu_latest` instead of 20.04? 

@tobias-urdin let me know what you think about this PR.

**Comment by tobias-urdin** [comment]
LGTM but does the barbican crypto suite pass with this as well?

I'm on vacation until middle of next week can check more in detail  then.

**Comment by alimaredia** [comment]
@tobias-urdin Thanks!

The barbican suite was still failing because of the most recent comments here: https://github.com/ceph/ceph/pull/51238/files. I'll rebase and work on that PR after this is merged.

**Comment by alimaredia** [comment]
Changing the distro to ubuntu latest still led to the tests passing: https://pulpito.ceph.com/amaredia-2023-06-21_18:07:14-rgw:tempest-main-distro-default-smithi/

**Comment by tobias-urdin** [comment]
nice, thanks @alimaredia!

**Comment by alimaredia** [comment]
jenkins test make check

**Review by cbodley — APPROVED** [review]

**Comment by cbodley** [comment]
jenkins test make check

**Comment by cbodley** [comment]
@alimaredia could you please make sure there are tracker issues for the remaining work? unpinning ubuntu_latest, the barbican tests, etc?

**Comment by cbodley** [comment]
```
./tasks/keystone.py:212:5: F841 local variable 'db_path' is assigned to but never used
flake8: exit 1 (3.96 seconds) /home/jenkins-build/build/workspace/ceph-pull-requests/qa> flake8 --select=F,E9 --exclude=venv,.tox pid=1925470
```

**Pull request merged**
