### PR TITLE
rgw:add --reset-regions for regionmap update

### PR DESCRIPTION
**Pull request by dwj192**
Delete a region and update region-map, region-map still contain the deleted region data.
region-map update just add new but did not remove the old.

Since operational errors，The original pull request was closed
https://github.com/ceph/ceph/pull/5363

Signed-off-by: duanweijun duanweijun@h3c.com

### CODE REVIEW

**Comment by dwj192** [comment]
@yehudasa  Sorry, since my operational errors，The original pull request was closed, i comment a new "pull requests".  any problem now?  thank you...

**Comment by dwj192** [comment]
@yehudasa 
I have modified as you said，could you review it for me?  thank you...

**Comment by dwj192** [comment]
@liewegas , could you assigne it to @yehudasa  ,thank you！

**Comment by cxwshawn** [comment]
@liewegas  LGTM, please help to merge, thanks.

**Comment by dwj192** [comment]
http://tracker.ceph.com/issues/12964

**Comment by yehudasa** [comment]
@dwj192 the commit message needs to reference the bug (`Fixes: #12964`). Otherwise looks fine.

**Comment by dwj192** [comment]
@yehudasa   it's OK, please check, thank you!

**Pull request merged**
