### PR TITLE
test/bufferlist: Remove chmod operation.

### PR DESCRIPTION
**Pull request by majianpeng**
@dachary . Have you time to review this? Thanks!

### CODE REVIEW

**Comment by dachary** [comment]
This test checks that a lack of permissions on a file will return **-EACCES**. This indeed does not work when running tests under root. What about skipping the test if uid == 0 instead  ? That was the test is run under the normal case (the user running the test is not root) and does not fail if the user is root.

**Comment by majianpeng** [comment]
@dachary . The test for buffer rather than chmod. So i think remove this don't effect the aim of this case.

**Comment by dachary** [comment]
The test
<pre>
EXPECT_EQ(-EACCES, bl.read_file("testfile", &error));
</pre>
checks that **read_file** will return -EACCESS if the file cannot be read because of permissions problems. It is worth testing, don't you think ?

**Comment by majianpeng** [comment]
@dachary . Sorry i omit this. The origin purpose is test read from file. So for error is also a case. I agree your suggestion. Thanks!

**Comment by majianpeng** [comment]
@dachary .updated & reviewed . Thanks!

**Pull request merged**
