### PR TITLE
rgw: initialize rgw_log_entry::identity_type

### PR DESCRIPTION
**Pull request by cbodley**
uninitialized identity_type field was causing unit test failures from check-generated.sh:
```
**** rgw_log_entry test 2 dump_json check failed ****
   ceph-dencoder type rgw_log_entry select_test 2 dump_json > /tmp/typ-AW7AEODB3
   ceph-dencoder type rgw_log_entry select_test 2 encode decode dump_json > /tmp/typ-0NX4cmLHR
21c21
<     "identity_type": 3599295712
---
>     "identity_type": 2072560864
```

Fixes: https://tracker.ceph.com/issues/58115

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by mattbenjamin** [comment]
@cbodley seems potentially very impactful?

**Comment by cbodley** [comment]
> @cbodley seems potentially very impactful?

@mattbenjamin fortunately not! this only effects a single test case from `rgw_log_entry::generate_test_instances()`: https://github.com/ceph/ceph/blob/0d99c9b/src/rgw/rgw_log.cc#L699-L701

`rgw_log_op()` will always initialize that value: https://github.com/ceph/ceph/blob/0d99c9b/src/rgw/rgw_log.cc#L629-L633

**Review by idryomov — COMMENTED** [review]
Thanks for the quick fixup!  Should a tracker ticket be opened to get this backported?

Also, just from a quick look, what about `delete_multi_obj_meta`?  Its integer fields aren't initialized either, is there a potential for `rgw_log_entry` to get encoded without `RGWDeleteMultiObj::write_ops_log_entry` being called first?

**Comment by cbodley** [comment]
> Thanks for the quick fixup! Should a tracker ticket be opened to get this backported?

attached to https://tracker.ceph.com/issues/58115

> Also, just from a quick look, what about `delete_multi_obj_meta`? Its integer fields aren't initialized either, is there a potential for `rgw_log_entry` to get encoded without `RGWDeleteMultiObj::write_ops_log_entry` being called first?

thanks, added a commit for those too

**Comment by cbodley** [comment]
this can merge once it has an approval

**Review by mattbenjamin — APPROVED** [review]
everything looks initialized

**Pull request merged**
