### PR TITLE
mon: ceph osd map shows NONE when an osd is missing

### PR DESCRIPTION
**Pull request by shylesh**
Signed-off-by: Shylesh Kumar <shmohan@redhat.com>

### CODE REVIEW

**Comment by dachary** [comment]
The fix looks good :-) Could you amend the commit message so that it look more like the others (as shown by git log ) ? The title should be something like **mon: ceph osd map shows NONE when an osd is missing** (note the prefix mon: that says it relates to the monitor code).

**Comment by dachary** [comment]
This is presumably a change we would like to backport. To help with that it is better not to include cosmetic changes (the whitespace cleanup) to minimize the risks of conflicts.

**Comment by dachary** [comment]
@shylesh looks good to me. Let's wait for the bot that runs a make check on each pull request to confirm tests pass ok and it will be merged. Thanks !

**Comment by dachary** [comment]
@tchaikov do you think that *needs-qa* ? Or could it be merged as is because it's straightforward ?

**Comment by tchaikov** [comment]
@dachary no, i don't think so. but i've not took a close look at this pr. should be a straightforward one, and i trust your judgement  :-)

**Comment by tchaikov** [comment]
LGTM. `Reviewed-by: Kefu Chai <kchai@redhat.com>`

**Comment by dachary** [comment]
@tchaikov thanks !

**Pull request merged**
