### PR TITLE
quincy: Combine backport of master PRs 45118 and 45121. 

### PR DESCRIPTION
**Pull request by sseshasa**
This backport PR combines the following:

Backport tracker1: https://tracker.ceph.com/issues/54393  (Backport of https://github.com/ceph/ceph/pull/45118)
Parent Tracker: https://tracker.ceph.com/issues/54364

Backport tracker2: https://tracker.ceph.com/issues/54394  (Backport of https://github.com/ceph/ceph/pull/45121)
Parent Tracker: https://tracker.ceph.com/issues/51554

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by sseshasa** [comment]
jenkins test api

**Review by ljflores — APPROVED** [review]

**Comment by ljflores** [comment]
jenkins test api

**Review by yaarith — APPROVED** [review]
thanks, @sseshasa!

**Comment by ljflores** [comment]
jenkins test api

**Comment by sseshasa** [comment]
jenkins test api

**Review by neha-ojha — APPROVED** [review]

**Comment by ljflores** [comment]
Yay, api test finally seems to be running correctly.

**Comment by sseshasa** [comment]
**Teuthology Test Result:**

http://pulpito.front.sepia.ceph.com/sseshasa-2022-02-24_11:27:07-rados-wip-45118-45121-quincy-testing-distro-default-smithi/

**Comment by sseshasa** [comment]
jenkins test api

**Comment by ljflores** [comment]
Failures, unrelated:
    https://tracker.ceph.com/issues/53246
    https://tracker.ceph.com/issues/53294
    https://tracker.ceph.com/issues/52136
    https://tracker.ceph.com/issues/54086
    https://tracker.ceph.com/issues/54372

Details:
    1. rhel 8.4 and centos stream unable to install cephfs-java - Ceph - Cephfs
    2. rados/test.sh hangs while running LibRadosTwoPoolsPP.TierFlushDuringFlush - Ceph - RADOS
    3. Valgrind reports memory "Leak_DefinitelyLost" errors. - Ceph - RADOS
    4. Permission denied when trying to unlink and open /var/log/ntpstats/... - TOOLS - Teuthology
    5. No module named 'tasks' - Infrastructure
   
There is only one more job running, but it is from the `rados/thrash-erasure-code-big` facet. If it fails, I am sure it will be because of a `wait_for_recovery` assertion error, which is tracked by https://tracker.ceph.com/issues/51076.

**Comment by sseshasa** [comment]
> Failures, unrelated: https://tracker.ceph.com/issues/53246 https://tracker.ceph.com/issues/53294 https://tracker.ceph.com/issues/52136 https://tracker.ceph.com/issues/54086 https://tracker.ceph.com/issues/54372
> 
> Details: 1. rhel 8.4 and centos stream unable to install cephfs-java - Ceph - Cephfs 2. rados/test.sh hangs while running LibRadosTwoPoolsPP.TierFlushDuringFlush - Ceph - RADOS 3. Valgrind reports memory "Leak_DefinitelyLost" errors. - Ceph - RADOS 4. Permission denied when trying to unlink and open /var/log/ntpstats/... - TOOLS - Teuthology 5. No module named 'tasks' - Infrastructure
> 
> There is only one more job running, but it is from the `rados/thrash-erasure-code-big` facet. If it fails, I am sure it will be because of a `wait_for_recovery` assertion error, which is tracked by https://tracker.ceph.com/issues/51076.

Thanks for analyzing the failures @ljflores.

**Pull request merged**
