### PR TITLE
tools/ceph_objectstore_tool: Add duplicate pg log entries injection

### PR DESCRIPTION
**Pull request by NitzanMordhai**
To be able to recreate and test pg log duplicate entries, a new option
added to the COT: --op pg-log-inject-dups we will also need to provide
--file json_arry of dups, it can get as many dups that need to be inject

the json for dups is in the following format:
{"reqid": "client.n.n:n", "version": "n'n", "user_version": n, "return_code": n}

if the json object will have generate, COT will generate that amount of dups out of the current object (by version change)
example: {"reqid": "client.4177.0:0", "version": "3'0", "user_version": "0", "generate": "50000000", "return_code": "0"}
will generate 50M dups entries and will inject them

Signed-off-by: Nitzan Mordechai <nmordec@redhat.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [x] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by NitzanMordhai** [comment]
jenkins test make check

**Comment by neha-ojha** [comment]
Note: This is included in https://github.com/ceph/ceph/pull/47046 as well

**Review by pdvian — COMMENTED** [review]
@NitzanMordhai The json format for array_type mentioned in the commit message example is recognized as obj_type rather than array_type.
With below json dups format : 
`{"reqid": "client.4177.0:0", "version": "3'0", "user_version": "0", "generate": "50000000", "return_code": "0"}`

the ceph-objectstore-tool fails to recognize it as an array_type : 
`$ ./bin/ceph-objectstore-tool --data-path dev/osd2 --op pg-log-inject-dups --file /tmp/dups.json --no-mon-config --pgid 3.1f`
`result is not an array_type - type=0`
`not JSON array_type /tmp/fii.array.json`

We need to pass json_array of dups in below format : 
`[
  {
    "reqid": "client.4177.0:0"
  },
  {
    "version": "3'0"
  },
  {
    "user_version":"0"
  },
  {
    "generate":"50000000"
  },
  {
    "return_code":"0"
  }
]`

Is above json format a right way to generate dups for current object ?

**Comment by nkshirsagar** [comment]
@NitzanMordhai @rzarzynski @pdvian  I'm trying to use this dups injection method to test backport of https://github.com/ceph/ceph/pull/47046 into octopus.

I am able to use this method to inject dups (i take down the OSD which I pass in  --data-path dev/osd1/  .. this is my dups.json)

~~~
root@focal-new:/home/nikhil/Downloads/ceph_build_oct/ceph/build# cat bin/dups.json 
[
	{"reqid": "client.4177.0:0", 
	"version": "3'0", 
	"user_version": "0", 
	"generate": "5000000", 
	"return_code": "0"}
]

root@focal-new:/home/nikhil/Downloads/ceph_build_oct/ceph/build# ceph -s
2022-09-21T06:00:53.736+0000 7f753dbce700 -1 WARNING: all dangerous and experimental features are enabled.
2022-09-21T06:00:53.756+0000 7f753dbce700 -1 WARNING: all dangerous and experimental features are enabled.
  cluster:
    id:     9e7c0a82-8072-4c48-b697-1e6399b4fc9e
    health: HEALTH_WARN
            1 osds down
            Degraded data redundancy: 255/765 objects degraded (33.333%), 64 pgs degraded
 
  services:
    mon: 3 daemons, quorum a,b,c (age 2h)
    mgr: x(active, since 2h)
    mds: a:1 {0=a=up:active}
    osd: 3 osds: 2 up (since 55s), 3 in (since 2h)
    rgw: 1 daemon active (8000)
 
  task status:
 
  data:
    pools:   7 pools, 169 pgs
    objects: 255 objects, 9.5 KiB
    usage:   6.1 GiB used, 297 GiB / 303 GiB avail
    pgs:     255/765 objects degraded (33.333%)
             105 active+undersized
             64  active+undersized+degraded

~~~
then I run 
~~~
root@focal-new:/home/nikhil/Downloads/ceph_build_oct/ceph/build# ./bin/ceph-objectstore-tool --data-path dev/osd1/ --op pg-log-inject-dups --file bin/dups.json --no-mon-config --pgid 6.1b
2022-09-21T06:01:27.724+0000 7f2cdf25fb80 -1 WARNING: all dangerous and experimental features are enabled.
injecting dups into pgid:6.1b num of dups:50001
inject of 50000 dups into pgid:6.1b done...
injecting dups into pgid:6.1b num of dups:50001
inject of 100001 dups into pgid:6.1b done...
injecting dups into pgid:6.1b num of dups:50001
...
~~~
My question is, how do I validate the fix is working fine? Do I simply monitor the dups somehow using the same tool and verify they're "trimmed/reducing"? Any tips please about that?

Regards,
Nikhil.

**Comment by athanatos** [comment]
@NitzanMordhai Looks like this already merged in https://github.com/ceph/ceph/pull/47046 so I'm closing it

**Pull request closed without merging**
