### PR TITLE
mds: use regular dispatch for processing metrics

### PR DESCRIPTION
**Pull request by batrick**
There have been cases where the MDS does an undesirable failover because it misses heartbeat resets after a long recovery in up:replay.  It was observed that the MDS was processing a flood of metrics messages from all reconnecting clients. This likely caused undersiable MetricAggregator::lock contention in the messenger threads while fast dispatching client metrics.

Instead, use the normal dispatch where acquiring locks is okay to do.

See-also: linux.git/f7c2f4f6ce16fb58f7d024f3e1b40023c4b43ff9
Fixes: https://tracker.ceph.com/issues/65658

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Comment by batrick** [comment]
jenkins test api

**Review by vshankar — APPROVED** [review]
This change is fine - I guess we underestimated issues when using fast dispatch in the original PR, especially when using locks - the whole discussion of using spinlocks vs mutexes. I recall that we switched to using a mutex since the code was doing memory allocation (under a spinlock which is a big no no). Maybe it's time to revisit that.

MDS uses fast dispatch with beacon (reply) messages which aren't too frequently received or there isn't a flood of those at any given point. The effect with metrics messages are that they can be huge in number and too frequent.

**Comment by batrick** [comment]
This PR is under test in [https://tracker.ceph.com/issues/65771](https://tracker.ceph.com/issues/65771).

**Comment by batrick** [comment]
I'm not going to merge this right yet: I think we should also increase the priority of metrics messages so they get processed ahead of regular requests.

**Comment by vshankar** [comment]
> I'm not going to merge this right yet: I think we should also increase the priority of metrics messages so they get processed ahead of regular requests.

Does it matter if the processing is delayed a _bit_? Did you see huge lags in metrics updation in tests?

**Comment by batrick** [comment]
> > I'm not going to merge this right yet: I think we should also increase the priority of metrics messages so they get processed ahead of regular requests.
> 
> Does it matter if the processing is delayed a _bit_? Did you see huge lags in metrics updation in tests?

No. But I'm trying to maintain the current behavior of metrics messages being processed *promptly* by the MDS. In any case, it makes sense to me that these messages should not be queued behind potentially thousands of client requests.

**Comment by batrick** [comment]
jenkins test make check

**Comment by batrick** [comment]
This PR is under test in [https://tracker.ceph.com/issues/65867](https://tracker.ceph.com/issues/65867).

**Review by gregsfortytwo — APPROVED** [review]
LGTM

**Comment by gregsfortytwo** [comment]
@vshankar 
> This change is fine - I guess we underestimated issues when using fast dispatch in the original PR, especially when using locks - the whole discussion of using spinlocks vs mutexes. I recall that we switched to using a mutex since the code was doing memory allocation (under a spinlock which is a big no no). Maybe it's time to revisit that.
> 
> MDS uses fast dispatch with beacon (reply) messages which aren't too frequently received or there isn't a flood of those at any given point. The effect with metrics messages are that they can be huge in number and too frequent.

You are just not allowed to block inside of an ms_fast_dispatch function. Like, at all. It's stealing one of the AsyncMessenger threads (default: 8?) to do the fast dispatch and if you go to sleep holding it then messaging work can stop. So holding a mutex for the *entirety* of the work duration is really, really bad, and the client reconnect storms we were getting straightforwardly translate into blocked messaging (because way more than 8 clients can simultaneously send in looooots of MClientMetrics messages, which have to be processed serially, and as they're holding messenger locks while being processed, they will starve any other attempts to use the messenger and back up other MDS worker threads when outgoing throttle limits are hit).

If you look at the OSD, I believe you'll find it grabs one mutex for the duration of an "enqueue" call. But everything else is lock free.

**Comment by gregsfortytwo** [comment]
Actually @vshankar, is there some way we could update the fast_dispatch documentation to be clearer about these requirements? I thought it was already pretty explicit, but it's clearly not good enough.

**Comment by gregsfortytwo** [comment]
@batrick we have similar problems with Beacon https://tracker.ceph.com/issues/66014 so please look at that next. We'll need to backport both of these everywhere.

**Comment by batrick** [comment]
> @batrick we have similar problems with Beacon https://tracker.ceph.com/issues/66014 so please look at that next. We'll need to backport both of these everywhere.

https://github.com/ceph/ceph/pull/57469

**Comment by batrick** [comment]
This PR is under test in [https://tracker.ceph.com/issues/66086](https://tracker.ceph.com/issues/66086).

**Pull request merged**
