### PR TITLE
octopus: ceph-volume: fix filestore/dmcrypt activate

### PR DESCRIPTION
**Pull request by jan--f**
backport tracker: https://tracker.ceph.com/issues/48303

---

backport of https://github.com/ceph/ceph/pull/38147
parent tracker: https://tracker.ceph.com/issues/48271

this backport was staged using ceph-backport.sh version 15.1.1.389
find the latest version at https://github.com/ceph/ceph/blob/master/src/script/ceph-backport.sh

### CODE REVIEW

**Comment by guits** [comment]
jenkins test ceph-volume tox

**Comment by guits** [comment]
jenkins test ceph-volume all

**Comment by jan--f** [comment]
jenkins test ceph-volume tox

**Comment by jan--f** [comment]
jenkins test ceph-volume all

**Review by rishabh-d-dave — APPROVED** [review]
@jan--f All tests passed (including c-v unit and func tests) for this PR too. It's merge ready IMO.

**Review by guits — APPROVED** [review]

**Comment by smithfarm** [comment]
jenkins test api

**Comment by smithfarm** [comment]
jenkins test make check

**Comment by smithfarm** [comment]
```
E: dpkg was interrupted, you must manually run 'sudo dpkg --configure -a' to correct the problem. 
```

@djgalloway Can you kick it?

**Comment by jan--f** [comment]
jenkins test api

**Comment by jan--f** [comment]
jenkins test make check

**Pull request merged**
