### PR TITLE
client: quit on failed remount during dentry invalidate test

### PR DESCRIPTION
**Pull request by batrick**
````   
    Fixes: http://tracker.ceph.com/issues/22269
    
    Signed-off-by: Patrick Donnelly <pdonnell@redhat.com>
````

Based on #19181

### CODE REVIEW

**Comment by shinobu-x** [comment]
@batrick did you notice that `friend class C_Client_Remount;` is already called? just want to make sure calling `C_Client_Remount` twice is intended or not.

**Comment by batrick** [comment]
@shinobu-x it needs to be declared as a `friend class` in order to access `Client`'s private members/methods.

**Comment by shinobu-x** [comment]
@batrick thanks for your confirmation.

**Comment by batrick** [comment]
@shinobu-x looks like you were right. Thanks for pointing it out :)

**Pull request merged**
