### PR TITLE
pybind: Add Python 3 support for rados and rbd modules

### PR DESCRIPTION
**Pull request by dcoles**
Due to some significant behavior changes in Python 3, the rados and rbd modules aren't currently usable  under Python 3. This PR attempts to rectify the situation by converting the code to a form that is compatible with both Python 3 and Python 2.7.

The most significant change is that Python strings are not 8-bit strings and must be explicitly encoded before they can be passed to the Ceph C APIs. Since I couldn't find any specific documentation on the string encoding, I'm currently assuming all strings should be UTF-8 encoded (the alternative being that strings are ASCII encoded which seems an overly restrictive limitation).

I've currently tested this using both Python 2.7 and Python 3.4 implementations. The corresponding unit tests should also pass for both implementations.

### CODE REVIEW

**Comment by dcoles** [comment]
Looks like the build failed here:
```
./test/mon/osd-pool-create.sh:279: TEST_utf8_cli:  ./ceph osd pool create $'\351\273\204' 1024
./test/mon/osd-pool-create.sh:280: TEST_utf8_cli:  grep 'pool '\''黄'\'' created'
./test/mon/osd-pool-create.sh:280: TEST_utf8_cli:  return 1
```

Seems like the ceph command relies pretty heavily on the rados module, thus need to ensure that  it also handles these changes.

**Comment by jdurgin** [comment]
Thanks for working on this - it's certainly clearer with better types. Can we make these changes backwards-compatible, so that existing programs (like the ceph cli, as you discovered) don't need to change?

Perhaps rather than requiring the byte type for data arguments, still accepting string as well and converting internally? I don't have time to look closely at this right now, as I'm heading to a conference, but wanted to suggest this before you got too far modifying other programs.

**Comment by dcoles** [comment]
Hi @jdurgin,

No problem! I'm going to try and avoid any backwards incompatible changes if I can at all help it.

Thankfully on Python 2 `bytes` and `b""` are just aliases for `str` and `""` respectively, thus shouldn't cause any grief. The trouble happens when we attempt to encode a Python 2 string that already has been encoded (like the utf8_cli test above). Python sanely only assumes it's probably an ASCII string (e.g. what you meant by `bstring.encode("utf-8")` was really shorthand for `(bstring.decode("ascii")).encode("utf-8")`) but this blows up if it's already encoded.

Maybe I can do something clever with the `cstr` helper so that on Python 2 it passes `str` through unmodified, but on Python 3 (and for unicode strings on Python 2) we UTF-8 encode it.

**Comment by dcoles** [comment]
I'm also not terribly keen on duplicating the `cstr` helper function in several places (since it's starting to get somewhat complicated). What would your thought be of importing it from the rados module?

**Comment by jdurgin** [comment]
The rbd module needs the rados module to function, so it's fine to import from it.

Things like openstack are also ```.encoding("utf-8")``` things before passing them to these modules, though I think we could use test cases for that here. I'm not very up to date on python 3, but a ```cstr``` helper like that sounds reasonable.

**Comment by dcoles** [comment]
Just quick status update - now looking into how best to support the Python 3 in the ceph utility.

This has uncovered a few more places where I didn't get the unicode-string vs. byte-string choice right, so I'll probably have a couple more updates to this PR shortly. Once the libraries behave properly with Python 2 and Python 3 will put up a new PR with the changes required for the Ceph utility to be usable with Python 3.

For Python 2, I'm preserving the ability to pass raw UTF-8 in a string, but for Python 3 we might want to be a bit more strict on the types (passing bytes to a function that expects a string would be an error).

**Comment by dcoles** [comment]
Same test failure with the UTF-8 images, though at a different layer.
```
./test/mon/osd-pool-create.sh:279: TEST_utf8_cli:  ./ceph osd pool create $'\351\273\204' 1024
./test/mon/osd-pool-create.sh:280: TEST_utf8_cli:  grep 'pool '\''黄'\'' created'
./test/mon/osd-pool-create.sh:280: TEST_utf8_cli:  return 1
```

Now that we support Unicode in the rados and rbd modules, we run into a few interesting cases when sys.stdout.encoding = None. Tthis seems to happen most often in Python 2 when sys.stdout.isatty() is False (when output is being piped to a file such as in the unit tests). A workaround is to set PYTHONIOENCODING=UTF-8 before running the ceph command.

To fix this, either have to convince the ceph command to always use a Unicode compatible encoding (e.g. UTF-8) when writing to stdout/stderr or to escape these characters if the terminal can't handle these characters.

**Comment by jdurgin** [comment]
Thanks, these library changes are looking good. I'm not sure what the best fix for the ceph cli is. 

Some googling suggests:
```import sys
import codecs
sys.stdout = codecs.getwriter('utf8')(sys.stdout)```

**Comment by dcoles** [comment]
Alright. Sounds good. This will mean the ceph cli will always use UTF-8.
My plan is to do something like the following at the beginning of the file:

    from __future__ import print_function

    import sys
    import codecs

    if sys.hexversion < 0x03000000:
        raw_stdout = sys.stdout
    else:
        raw_stdout = sys.stdout.buffer

    # Always use UTF-8 for stdout
    sys.stdout = codecs.getwriter('utf-8')(raw_stdout)

    print("Hello, world!")
    print(u"\u9ec4")
    raw_stdout.write(b"\351\273\204\n")


This should ensure that print always outputs Unicode characters as UTF-8, but we can still write raw bytes via `raw_stdout` (otherwise you get a UnicodeDecodeError or on newer versions of Python 3, the repr). Will probably have to do the same for stderr.

**Comment by dcoles** [comment]
This was the minimum set of changes required to make the ceph CLI work with the module changes.
I'd also like to make the ceph CLI work with Python 3, but that's a bit bigger undertaking.

**Comment by jdurgin** [comment]
A new method was added to librbd and I found a few small fixups were needed to pass the rbd tests under python 3 - do these look good to you? https://github.com/jdurgin/ceph/commits/wip-py3

If so I'll merge them and add running python 3 for test_rbd and test_rados to ceph-qa-suite.

**Comment by dcoles** [comment]
Whoops! Should have pulled master since this branch is almost a month old.

Looks good to me. Only one small comment on `test_pool_lookup_utf8`, everything else looks great.
https://github.com/jdurgin/ceph/commit/1ea88b5e6d78ce4420103cc3d011c036a843cb3b#commitcomment-14361719

**Comment by jdurgin** [comment]
oh one procedural thing I missed before - can you add your signed-off-by to the commits after  'pybind: Use basestring as string type for Python 2' - you have it on the earlier ones

**Comment by dcoles** [comment]
Sure thing. Just reworded those commit messages to include the signed-off-by tag.

**Comment by jdurgin** [comment]
thanks!

**Comment by dmick** [comment]
Sadly, this appears to have broken pdb

**Pull request merged**
