### PR TITLE
nautilus: rgw: fix a bug that lifecycle expiraton generates delete marker continuously

### PR DESCRIPTION
**Pull request by smithfarm**
backport tracker: https://tracker.ceph.com/issues/41588

---

backport of https://github.com/ceph/ceph/pull/28587
parent tracker: https://tracker.ceph.com/issues/40393

this backport was staged using https://github.com/ceph/ceph/blob/master/src/script/ceph-backport.sh

### CODE REVIEW

**Comment by smithfarm** [comment]
jenkins test make check

**Comment by smithfarm** [comment]
jenkins test docs

**Comment by cbodley** [comment]
jenkins test make check

**Comment by yuriw** [comment]
[wip-yuri8-testing-2019-10-02-1628-nautilus](https://trello.com/c/ftSTonIP/704-wip-yuri8-testing-2019-10-02-1628-nautilus)

**Pull request merged**
