### PR TITLE
msg/async/AsyncConnection.cc: give protocol logging a higher loglevel.

### PR DESCRIPTION
**Pull request by wjwithagen**
- Set the loglevel for internal protocl states to be atleast 25.
   This will prevent protocol internals be in the standard testruns.
   Which allows for easier log analysis

Signed-off-by: Willem Jan Withagen <wjw@digiware.nl>

### CODE REVIEW

**Comment by liewegas** [comment]
retest this please

**Comment by yuyuyu101** [comment]
I don't recommend to improve all debug level to 25/25... from my view, level 20 is a verbose level and set to this to debug something. level 25 is much more verbose for each function. level 30 will print network package.

So if you don't need messenger debug info, you can lower these... it will become barrier for others to debug..

**Comment by wjwithagen** [comment]
@yuyuyu101 
Now all this logging ends up in the Jenkins output if a test fails.
And there it is of little use to anybody other than those that really know the intrinsic working of the AsyncMessenger. This is also due to that all mesg stuff falls in the same class.
I'm really having a hard time to track the flow of programs due to the huge amount output.
So that is why I suggested this level, and when there is trouble in the msg-stack to actually only then increase the loglevel.

The other option is to lower the loglevel for this to 19, but then I'm not sure of items that have fallout at the other modules using this debug-option.

**Comment by yuyuyu101** [comment]
I suggest you can debug on your own branch with these commits and extra specified debug level.  Change existing debug level isn't a good idea to others.

**Comment by wjwithagen** [comment]
Oke, I'll close this one, but I would like to urge you and look into some of the log lines as they are non-informative unless you are tracing the code with a pencil. 
Logging is rather expensive due to locking (as I understand).

But anyways.... closing

**Comment by yuyuyu101** [comment]
yes... while debug async msgr internal flow, we need these verbose line to trace call flow..

**Pull request closed without merging**
