### PR TITLE
nautilus: common/options: bluestore 4k min_alloc_size for SSD

### PR DESCRIPTION
**Pull request by neha-ojha**
Backport of https://github.com/ceph/ceph/pull/30698 and https://github.com/ceph/ceph/pull/32809

### CODE REVIEW

**Comment by vumrao** [comment]
cc @vumrao

**Comment by yuriw** [comment]
[wip-yuri2-testing-2020-02-08-1640-nautilus](https://trello.com/c/LEl6x3Tt/819-wip-yuri2-testing-2020-02-08-1640-nautilus)

**Comment by yuriw** [comment]
test this please

**Comment by javagyt** [comment]
why modify bluestore 4k min_alloc_size for SSD？Are you have performan report?

**Pull request merged**
