### PR TITLE
mgr/dashboard: Clone an existing user role

### PR DESCRIPTION
**Pull request by votdev**
Peek 2020-01-15 15-24

Fixes: https://tracker.ceph.com/issues/43603

Signed-off-by: Volker Theile <vtheile@suse.com>

## Checklist
- [x] References tracker ticket
- [ ] Updates documentation if necessary
- [x] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by callithea** [comment]
jenkins test dashboard

**Comment by callithea** [comment]
- [pkg build](https://shaman.ceph.com/builds/ceph/wip-laura-testing-32653/) [WIP]

**Comment by votdev** [comment]
jenkins test make check arm64

**Comment by votdev** [comment]
jenkins test make check arm64

**Comment by votdev** [comment]
> Would be nice to have some kind of feedback, probably a notification, informing me that the operation is running or has finished.
> 
> If you have 2 pages of roles and clone a role from the 1st page with a name that will put it in the 2nd page, you have no idea if anything happened.

Good idea. A notification will be displayed now.

**Comment by callithea** [comment]
Latest QA run passed: http://pulpito.ceph.com/laura-2020-01-22_12:14:03-rados:dashboard-wip-laura-testing-32648-32653-distro-basic-smithi/

**Pull request merged**
