### PR TITLE
common: kick off mimic

### PR DESCRIPTION
**Pull request by liewegas**

### CODE REVIEW

**Comment by liewegas** [comment]
I think we should tag this v13.0.0 as soon as it merges so that the 'git describe' version strings look right.  It probably isn't worth doing an actual build, though.

**Comment by theanalyst** [comment]
should we tag something like 13.0.0-dev right now and tag and release 13.0.0 as soon as 12.2.0 is out of the door?

**Comment by liewegas** [comment]
I don't think it the order matters?  They are in different branches.

**Comment by theanalyst** [comment]
yeah the order doesn't matter, we could technically release 13.0.0 anytime, I just don't want to answer the question on mailing lists on 12.2.0 ;)

**Comment by liewegas** [comment]
I suggest just tagging it but not announcing or releasing anything.

**Comment by theanalyst** [comment]
ack

**Comment by liewegas** [comment]
http://pulpito.ceph.com/sage-2017-08-11_21:54:25-rados-wip-sage-testing2-20170811a-distro-basic-smithi/

**Pull request merged**
