### PR TITLE
common/tracer: fix for tracer provider destruction

### PR DESCRIPTION
**Pull request by zenomri**
due to changes in opentelemetry lib, the destruction of the tracer provider at the end of the init method also destructs the tracer, so we need to keep the tracer provider, as mentioned in opentelemetry documentation.

this bug introduced in #46754, the version of otel was updated, and it caused our tracer wrapper to use the noop tracer because the actual tracer is destroyed right after the initialization.

otel documentation of how to use the Tracer Provider: 
https://opentelemetry-cpp.readthedocs.io/en/latest/sdk/GettingStarted.html#tracerprovider
there was a change in the order of provider d'tor, so with the updated version, once the provider destroyed, it releases also his tracers' configuration.

Signed-off-by: Omri Zeneva <ozeneva@redhat.com>

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [x] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by zenomri** [comment]
jenkins test windows

**Comment by yuvalif** [comment]
can you please add the commit where this issue was introduced?
and also reference the relevant OTEL doc?

**Comment by zenomri** [comment]
> can you please add the commit where this issue was introduced? and also reference the relevant OTEL doc?
done. thanks

**Review by yuvalif — APPROVED** [review]

**Comment by yuvalif** [comment]
> > can you please add the commit where this issue was introduced? and also reference the relevant OTEL doc?
> 
> done. thanks

great. next time please provide such explanation/text inside the commit comment and not the github comment.
this will guarantee that the information is preserved regardless of github

**Comment by zenomri** [comment]
http://pulpito.front.sepia.ceph.com/ozeneva-2022-08-22_06:41:17-rgw-wip-omri-fix-tracer-provider-distro-basic-smithi/

there are failures, but they are seems to be for all other teuthology runs:
1. crypt - cannot create secret
2. hadoop - Failed to fetch package version
3. tempest
4. multisite failures
5. `rgw verify` failures. 

@yuvalif  do you think we can merge it?

**Comment by zenomri** [comment]
jenkins test api

**Comment by yuvalif** [comment]
> http://pulpito.front.sepia.ceph.com/ozeneva-2022-08-22_06:41:17-rgw-wip-omri-fix-tracer-provider-distro-basic-smithi/
> 
> there are failures, but they are seems to be for all other teuthology runs:
> 
> 1. crypt - cannot create secret
> 2. hadoop - Failed to fetch package version
> 3. tempest
> 4. multisite failures
> 5. `rgw verify` failures.
> 
> @yuvalif do you think we can merge it?

i see these failures on other branches. including the: `std::__throw_bad_variant_access(bool)` crash.
however, without the jenkins API tests passing, the PR cannot be merged. this could also be due to the crash.

**Comment by yuvalif** [comment]
jenkins test api

**Comment by zenomri** [comment]
jenkins test api

**Comment by zenomri** [comment]
jenkins test api

**Comment by zenomri** [comment]
jenkins test make check

**Comment by zenomri** [comment]
> > http://pulpito.front.sepia.ceph.com/ozeneva-2022-08-22_06:41:17-rgw-wip-omri-fix-tracer-provider-distro-basic-smithi/
> > there are failures, but they are seems to be for all other teuthology runs:
> > 
> > 1. crypt - cannot create secret
> > 2. hadoop - Failed to fetch package version
> > 3. tempest
> > 4. multisite failures
> > 5. `rgw verify` failures.
> > 
> > @yuvalif do you think we can merge it?
> 
> i see these failures on other branches. including the: `std::__throw_bad_variant_access(bool)` crash. there is already an open tracker for that: https://tracker.ceph.com/issues/57195 however, without the jenkins API tests passing, the PR cannot be merged. this could also be due to the crash.

yup.  api check succeeded.
could you please merge this PR?

**Comment by yuvalif** [comment]
> > > http://pulpito.front.sepia.ceph.com/ozeneva-2022-08-22_06:41:17-rgw-wip-omri-fix-tracer-provider-distro-basic-smithi/
> > > there are failures, but they are seems to be for all other teuthology runs:
> > > 
> > > 1. crypt - cannot create secret
> > > 2. hadoop - Failed to fetch package version
> > > 3. tempest
> > > 4. multisite failures
> > > 5. `rgw verify` failures.
> > > 
> > > @yuvalif do you think we can merge it?
> > 
> > 
> > i see these failures on other branches. including the: `std::__throw_bad_variant_access(bool)` crash. there is already an open tracker for that: https://tracker.ceph.com/issues/57195 however, without the jenkins API tests passing, the PR cannot be merged. this could also be due to the crash.
> 
> yup. api check succeeded. could you please merge this PR?

sorry i miised that in my previous comments, but since this affects the OSD, please run basic OSD suite

**Comment by zenomri** [comment]
> > > > http://pulpito.front.sepia.ceph.com/ozeneva-2022-08-22_06:41:17-rgw-wip-omri-fix-tracer-provider-distro-basic-smithi/
> > > > there are failures, but they are seems to be for all other teuthology runs:
> > > > 
> > > > 1. crypt - cannot create secret
> > > > 2. hadoop - Failed to fetch package version
> > > > 3. tempest
> > > > 4. multisite failures
> > > > 5. `rgw verify` failures.
> > > > 
> > > > @yuvalif do you think we can merge it?
> > > 
> > > 
> > > i see these failures on other branches. including the: `std::__throw_bad_variant_access(bool)` crash. there is already an open tracker for that: https://tracker.ceph.com/issues/57195 however, without the jenkins API tests passing, the PR cannot be merged. this could also be due to the crash.
> > 
> > 
> > yup. api check succeeded. could you please merge this PR?
> 
> sorry i miised that in my previous comments, but since this affects the OSD, please run basic OSD suite

rados basic test run
http://pulpito.front.sepia.ceph.com/?sha1=9362be0fd2139528165dc176efe5d55f67b2bb1a

one test has failed in the first run, so I ran it again, and it succeeded.

**Pull request merged**
