### PR TITLE
osd: fix trivial scrub bug

### PR DESCRIPTION
**Pull request by dragonylffly**
Signed-off-by: Li Wang <li.wang@kylin-cloud.com>

### CODE REVIEW

**Comment by dachary** [comment]
@dragonylffly please ignore the bot false negative (http://tracker.ceph.com/issues/13592).

**Comment by tchaikov** [comment]
lgtm.

**Comment by gregsfortytwo** [comment]
Commits for even trivial fixes need more in the commit message than just "fix trivial bug". :)

**Comment by dragonylffly** [comment]
@tchaikov @gregsfortytwo updated, with commit message revised

**Comment by tchaikov** [comment]
lgtm.

**Pull request merged**
