### PR TITLE
jewel: core: process deletes during recovery instead of peering

### PR DESCRIPTION
**Pull request by jdurgin**
http://tracker.ceph.com/issues/22400
http://tracker.ceph.com/issues/22405
http://tracker.ceph.com/issues/22406

~~This may need to be combined with https://github.com/ceph/ceph/pull/19497 since they both modify the pg log tests extensively.~~ (done)

### CODE REVIEW

**Comment by jdurgin** [comment]
retest this please

**Comment by smithfarm** [comment]
@jdurgin Please rebase?

**Comment by smithfarm** [comment]
@jdurgin Does this need to go into 10.2.11?

**Comment by jdurgin** [comment]
@smithfarm yeah, I'd like to get this and https://github.com/ceph/ceph/pull/18010 in - will rebase them today

**Comment by smithfarm** [comment]
@jdurgin Consider cherry-picking the 3 commits from #19497 when you rebase?

**Comment by jdurgin** [comment]
@smithfarm good idea

**Comment by smithfarm** [comment]
Please remove DNM and add jewel-batch-1 when done, thanks!

**Comment by smithfarm** [comment]
@jdurgin Build error.

**Comment by jdurgin** [comment]
retest this please

**Comment by smithfarm** [comment]
retest this please (logs are gone)

**Comment by smithfarm** [comment]
retest this please

**Comment by smithfarm** [comment]
@jdurgin Could you look at the make check failure?

**Comment by jdurgin** [comment]
bah logs vanished again. retest this please

**Comment by smithfarm** [comment]
```
FAIL: test/encoding/check-generated.sh

2 pg_missing_t
/tmp/typ-ylvvYsRhN /tmp/typ-19hJXLePY differ: byte 151, line 7
**** pg_missing_t test 2 dump_json check failed ****
   ceph-dencoder type pg_missing_t select_test 2 dump_json > /tmp/typ-ylvvYsRhN
   ceph-dencoder type pg_missing_t select_test 2 encode decode dump_json > /tmp/typ-19hJXLePY
diff /tmp/typ-ylvvYsRhN /tmp/typ-19hJXLePY

FAIL: test/encoding/readable.sh

        /home/jenkins-build/build/workspace/ceph-pull-requests/ceph-object-corpus/archive/0.61.4-60-g24c59be/objects/pg_missing_t::item
error: buffer::end_of_buffer
**** failed to decode /home/jenkins-build/build/workspace/ceph-pull-requests/ceph-object-corpus/archive/0.61.4-60-g24c59be/objects/pg_missing_t::item/1681ffc6e046c7af98c9e6c232a3fe0a ****
error: buffer::end_of_buffer
```

Full test logs are saved here: https://paste2.org/Hg4ghAkZ

**Comment by smithfarm** [comment]
@jdurgin I'm starting an integration run now, which I hope will be one of the last, if not the last, before sending 10.2.11 to QE. You had mentioned that you wanted this PR in for 10.2.11 - is that still true?

**Comment by jdurgin** [comment]
@smithfarm at this point it can wait for the next point release, it's going to take a bit of time to fix this one up.

**Comment by theanalyst** [comment]
@jdurgin do we still want this?

**Comment by jdurgin** [comment]
too late for such a large change to jewel

**Pull request closed without merging**
