### PR TITLE
mgr/dashboard: restcontroller: minor improvements and bug fixes

### PR DESCRIPTION
**Pull request by rjfd**
This commit fixes a bug in the resource id inference, and improves
the detection of the type of parameters in methods accessed by GET,
or DELETE.

It also adds the support to override the URL path suffix for
`@Collection` and `@Resource` methods.

Signed-off-by: Ricardo Dias <rdias@suse.com>

### CODE REVIEW

**Comment by votdev** [comment]
While working with this PR i realized that the ``@RESTController.Resource`` decorator needs the ability to configure the status of the response, otherwise all endpoints will return a 200.

```
--- src/pybind/mgr/dashboard/controllers/__init__.py	(date 1528973738000)
+++ src/pybind/mgr/dashboard/controllers/__init__.py	(date 1528979998000)
@@ -554,14 +554,21 @@
     RESOURCE_ID = None
 
     _method_mapping = collections.OrderedDict([
-        ('list', {'method': 'GET', 'resource': False, 'status': 200}),
-        ('create', {'method': 'POST', 'resource': False, 'status': 201}),
-        ('bulk_set', {'method': 'PUT', 'resource': False, 'status': 200}),
-        ('bulk_delete', {'method': 'DELETE', 'resource': False, 'status': 204}),
-        ('get', {'method': 'GET', 'resource': True, 'status': 200}),
-        ('delete', {'method': 'DELETE', 'resource': True, 'status': 204}),
-        ('set', {'method': 'PUT', 'resource': True, 'status': 200})
+        ('list', {'method': 'GET', 'resource': False}),
+        ('create', {'method': 'POST', 'resource': False}),
+        ('bulk_set', {'method': 'PUT', 'resource': False}),
+        ('bulk_delete', {'method': 'DELETE', 'resource': False}),
+        ('get', {'method': 'GET', 'resource': True}),
+        ('delete', {'method': 'DELETE', 'resource': True}),
+        ('set', {'method': 'PUT', 'resource': True})
     ])
+
+    _status_mapping = {
+        'DELETE': 204,
+        'GET': 200,
+        'POST': 201,
+        'PUT': 200
+    }
 
     @classmethod
     def infer_resource_id(cls):
@@ -600,8 +607,8 @@
                         path_params = ["{{{}}}".format(p) for p in res_id_params]
                         path += "/{}".format("/".join(path_params))
 
-                status = meth['status']
                 method = meth['method']
+                status = cls._status_mapping[method]
 
             elif hasattr(func, "_collection_method_"):
                 if func._collection_method_['path']:
@@ -624,6 +631,10 @@
 
                 method = func._resource_method_['method']
                 query_params = func._resource_method_['query_params']
+                if func._resource_method_['status'] is None:
+                    status = cls._status_mapping[method]
+                else:
+                    status = func._resource_method_['status']
 
             else:
                 continue
@@ -660,7 +671,7 @@
         return wrapper
 
     @staticmethod
-    def Resource(method=None, path=None, query_params=None):
+    def Resource(method=None, path=None, query_params=None, status=None):
         if not method:
             method = 'GET'
 
@@ -668,7 +679,8 @@
             func._resource_method_ = {
                 'method': method,
                 'path': path,
-                'query_params': query_params
+                'query_params': query_params,
+                'status': status
             }
             return func
         return _wrapper
```

**Comment by rjfd** [comment]
@votdev thanks! will add that change to the PR.

**Comment by votdev** [comment]
Maybe this also relates to the ``@RESTController.Collection`` decorator.

**Comment by rjfd** [comment]
@votdev pushed the support for specifying the status in `@Resource` and `@Collection` methods. I didn't completely followed your design, the main difference is that `200` is the default status code when no status is specified.

**Comment by votdev** [comment]
@rjfd I like that my solution will choose the status code automatically in my code, but your solution is also ok; it will add the ability to configure the status code.

**Comment by votdev** [comment]
jenkins retest this please

**Comment by votdev** [comment]
@rjfd There are linting errors:
```
************* Module dashboard.controllers
R:582, 4: Too many statements (52/50) (too-many-statements)

------------------------------------
Your code has been rated at 10.00/10

ERROR: InvocationError: '/home/jenkins-build/build/workspace/ceph-pull-requests/build/py27-lint/bin/pylint --rcfile=.pylintrc --jobs=5 . module.py tools.py controllers tests services'
```

**Comment by votdev** [comment]
To fix the lint error use
```
--- src/pybind/mgr/dashboard/controllers/__init__.py	(date 1529001607000)
+++ src/pybind/mgr/dashboard/controllers/__init__.py	(date 1529048804000)
@@ -578,6 +578,7 @@
                         if p['required'] and p['name'] not in path_params]
         return None
 
+    # pylint: disable=too-many-statements
     @classmethod
     def endpoints(cls):
         result = super(RESTController, cls).endpoints()
```

**Comment by s0nea** [comment]
QA test run was successful: 
- https://shaman.ceph.com/builds/ceph/wip-tdehler-testing-22528/
- http://pulpito.ceph.com/tdehler-2018-06-20_06:52:04-rados:mgr-wip-tdehler-testing-22528-distro-basic-smithi/

**Pull request merged**
