### PR TITLE
rgw,unittest_bit_alloc: silence clang analyzer warning

### PR DESCRIPTION
**Pull request by tchaikov**

### CODE REVIEW

**Comment by liewegas** [comment]
retest this please

**Comment by liewegas** [comment]
unit test piece looks fine

**Comment by yuriw** [comment]
test this pls

**Comment by yuriw** [comment]
test this please

**Comment by yuriw** [comment]
http://pulpito.front.sepia.ceph.com:80/yuriw-2017-08-29_19:33:51-rgw-wip-yuri-testing4_2017_8_30-distro-basic-smithi/

http://pulpito.ceph.com/yuriw-2017-08-30_02:10:47-rgw-wip-yuri-testing4_2017_8_30-distro-basic-smithi/

**Pull request merged**
