### PR TITLE
pacific: cpatch: updates

### PR DESCRIPTION
**Pull request by liewegas**

### CODE REVIEW

**Comment by neha-ojha** [comment]
jenkins test docs

**Comment by liewegas** [comment]
jenkins test docs

**Comment by liewegas** [comment]
jenkins test docs

**Comment by liewegas** [comment]
jenkins render docs

**Comment by liewegas** [comment]
not sure what jenkins command will redo the readthedocs job...

**Review by jdurgin — APPROVED** [review]

**Pull request merged**
