### PR TITLE
clang: common/config.cc basename() requires libgen.h includes

### PR DESCRIPTION
**Pull request by wjwithagen**
Signed-off-by: Willem Jan Withagen <wjw@digiware.nl>

### CODE REVIEW

**Comment by wjwithagen** [comment]
@tchaikov 
This version ( just an ifdef around the libgen.h ) compiles and runs on both OSes.
So if you want I can squash/delete the earlier commits, and just have this in the pull

**Comment by liewegas** [comment]
@tchaikov ping

**Comment by tchaikov** [comment]
@wjwithagen could you squash the commits into a single one?

**Comment by wjwithagen** [comment]
@tchaikov Done

**Comment by yuriw** [comment]
http://pulpito.ceph.com/yuriw-2016-05-13_16:00:42-rados-wip-yuri-testing-distro-basic-smithi/

**Comment by wjwithagen** [comment]
@yuriw 
Thanx, It seems to be my happy commit day. :)

**Pull request merged**
