### PR TITLE
rgw: do md5 calculation and filter process concurrent in put_obj

### PR DESCRIPTION
**Pull request by clwluvw**
In cases like filter encryption, the time consumed by the filter process can be the same or even more than calculating the md5. Running the md5 calculation in another thread buys a lot of time on every chunk process and therefore in total.

Fixes: https://tracker.ceph.com/issues/62386

### CODE REVIEW

**Comment by cbodley** [comment]
thanks @clwluvw, there's been a lot of interest in accelerating these md5 computations

i recently opened https://github.com/ceph/ceph/pull/52385 and https://github.com/ceph/ceph/pull/52488 to use avx instructions for batches of md5 calculations. those interfaces are asynchronous, which would allow us to offload the calculations from the thread calling `RGWPutObj::execute()` -> `filter->process()` without having to spawn a new thread for every chunk of data

**Comment by clwluvw** [comment]
@cbodley Thank you for pointing them out. that makes sense and so we don't need this PR to remove the overhead of the filter from the thread.
Just a question would be for a short run until those PRs got delivered, would this approach (implementation) be fine?

**Comment by cbodley** [comment]
> Just a question would be for a short run until those PRs got delivered, would this approach (implementation) be fine?

@clwluvw you're right that it'll be a while before this stuff is ready. we haven't gotten the integration working yet, and once it does work we'll still need to figure out the best tuning for it. i'll make sure you're cc'ed on further discussions here

i don't think we'd want to ship a release with the strategy in this pr, so i wouldn't support merging it to main. but that shouldn't stop us from experimenting with it in other performance testing

**Comment by cbodley** [comment]
cc @mkogan1

**Comment by clwluvw** [comment]
This is a sample trace for a 10MiB object with 4MiB chunks with the change in this pr. `filter` is the encryption process and `calc_md5` is the hash update.
Doing that async would result in different behavior I guess as it won't wait for the thread at all.

Screenshot 2023-08-10 at 20 59 04

**Pull request closed without merging**
