### PR TITLE
librbd: avoid EUCLEAN error after "rbd rm" is interrupted

### PR DESCRIPTION
**Pull request by weixinwei**
If rbd rm process is interrupted (for example, rbd client killed, or ceph_assert fault injection in rbd code), rbd state in trash stays in cls::rbd::TRASH_IMAGE_STATE_MOVING.
Then continue to rbd rm, throw error -EUCLEAN.

Fixes: https://tracker.ceph.com/issues/58060
Signed-off-by: weixinwei <weixw3@lenovo.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by weixinwei** [comment]
@idryomov ping?

**Comment by idryomov** [comment]
While at it, I'd also get rid of the useless `else if (r >= 0)` condition:
```
    r = Trash<I>::list(io_ctx, trash_entries, false);
    if (r < 0) {
      return r;
    }
    for (auto& entry : trash_entries) {
      if (entry.name == image_name &&
          entry.source == RBD_TRASH_IMAGE_SOURCE_REMOVING) {
        cls::rbd::TrashImageSpec spec;
        r = cls_client::trash_get(&io_ctx, entry.id, &spec);
        if (r < 0) {
          lderr(cct) << "error getting image id " << entry.id
                     << " info from trash: " << cpp_strerror(r) << dendl;
          return r;
        }
        if (spec.state == cls::rbd::TRASH_IMAGE_STATE_MOVING) {
          r = Trash<I>::move(io_ctx, entry.source, entry.name, entry.id, 0);
          if (r < 0) {
            return r;
          }
        }
        return Trash<I>::remove(io_ctx, entry.id, true, prog_ctx);
      }
    }
```

**Comment by idryomov** [comment]
The description needs to be added to the commit message as well.  Here is what I'd propose:
```
librbd: avoid EUCLEAN error after "rbd rm" is interrupted

If "rbd rm" command is interrupted (e.g. killed), the image in the
trash stays in cls::rbd::TRASH_IMAGE_STATE_MOVING state.  Later, when
"rbd rm" command is rerun, EUCLEAN error is returned.

Fixes: https://tracker.ceph.com/issues/58060
Signed-off-by: weixinwei <weixw3@lenovo.com>
```
Feel free to stick with your original description (the one in the PR) if you don't like my suggestion, but _some_ description in the commit message is needed.

**Comment by weixinwei** [comment]
> The description needs to be added to the commit message as well. Here is what I'd propose:
> 
> ```
> librbd: avoid EUCLEAN error after "rbd rm" is interrupted
> 
> If "rbd rm" command is interrupted (e.g. killed), the image in the
> trash stays in cls::rbd::TRASH_IMAGE_STATE_MOVING state.  Later, when
> "rbd rm" command is rerun, EUCLEAN error is returned.
> 
> Fixes: https://tracker.ceph.com/issues/58060
> Signed-off-by: weixinwei <weixw3@lenovo.com>
> ```
> 
> Feel free to stick with your original description (the one in the PR) if you don't like my suggestion, but _some_ description in the commit message is needed.

I flip the pr of others, commited message with description indeed is a good habit. Thanks sincerely for your suggestion.

**Review by trociny — APPROVED** [review]

**Comment by idryomov** [comment]
jenkins test windown

**Comment by idryomov** [comment]
jenkins test windows

**Comment by idryomov** [comment]
No related failures:

https://pulpito.ceph.com/dis-2022-12-21_08:46:24-rbd-wip-dis-testing-distro-default-smithi/
https://pulpito.ceph.com/dis-2022-12-21_21:28:24-rbd-wip-dis-testing-distro-default-smithi/
https://pulpito.ceph.com/dis-2022-12-23_14:36:40-rbd-wip-dis-testing-distro-default-smithi/

**Pull request merged**
