### PR TITLE
mgr/rbd_support: don't try to remove localized option on every scheduler load

### PR DESCRIPTION
**Pull request by trociny**
Do this only once if it exists.

Fixes: https://tracker.ceph.com/issues/58192
Signed-off-by: Mykola Golub <mgolub@suse.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by trociny** [comment]
Also we may consider just removing this compatibility code in the main branch.

**Comment by idryomov** [comment]
I notice that https://tracker.ceph.com/issues/58192 has just been filed a few hours ago.  There is an older ticket for this -- https://tracker.ceph.com/issues/57726 -- which Ramana has picked up on Monday.  He has a draft PR up: https://github.com/ceph/ceph/pull/49261.

**Review by idryomov — COMMENTED** [review]
Functionally, this seems to be an exact duplicate of https://github.com/ceph/ceph/pull/49261.

**Comment by idryomov** [comment]
> Also we may consider just removing this compatibility code in the main branch.

I'd rather keep it for now.  Once fixed to not spam the audit channel, it's basically free.  There is quite a lot of compatibility code, particularly in the area of class methods, with comments like "remove this once X goes out of support" but we haven't done it in the end.  I think this "drop compatibility code" effort should be separate with a clear, agreed upon in advance, lower bound for X.

**Comment by trociny** [comment]
Ah, indeed, this is a duplicate. And can be closed then.

**Pull request closed without merging**
