### PR TITLE
doc: correct the quota section

### PR DESCRIPTION
**Pull request by hrchu**
test in ceph version 10.2.2 (45107e21c568dd033c2f0a3107dec8f0b0e58374)

### CODE REVIEW

**Comment by cbodley** [comment]
@hrchu thanks for looking into this! i agree that the current docs are a bit confusing and incomplete. but based on the code, it looks like both methods (http params and json) are supported. from rgw_rest_user.cc:729,

```c++
/**
 * set quota
 *
 * two different ways to set the quota info: as json struct in the message body or via http params.
```

also, both the `uid` and `bucket ` parameters are valid depending on whether `quota-scope` is `user` or `bucket`

**Comment by hrchu** [comment]
Cool, I will update this later.

**Comment by hrchu** [comment]
@cbodley the PR is updated, plz have a look.

I do minimal modification so that people can follow the document and successfully "enable" the quota without getting 400 bad request. :joy_cat:

**Comment by cbodley** [comment]
@hrchu thanks, looks good. we'd like to backport this fix to jewel and kraken, so i created a ticket at http://tracker.ceph.com/issues/19397. could you please add this to your commit message?
```
Fixes: http://tracker.ceph.com/issues/19397
```

**Comment by hrchu** [comment]
@cbodley sure, updated.

**Comment by cbodley** [comment]
@hrchu there are some new changes to rgw_admin.cc mixed in, can you remove those?

**Comment by hrchu** [comment]
@cbodley updated. I should check it.

**Pull request merged**
