### PR TITLE
mds: add missing mds_lock

### PR DESCRIPTION
**Pull request by batrick**
Fixes: http://tracker.ceph.com/issues/36573
Introduced-by: ecbd4a8aa8e6c1c72af4e0be15e0340629bfdc3a
Signed-off-by: Patrick Donnelly <pdonnell@redhat.com>

- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by batrick** [comment]
http://pulpito.ceph.com/?branch=wip-pdonnell-testing-20181023.224346

**Comment by batrick** [comment]
retest this please

**Comment by ukernel** [comment]
LGTM

**Comment by batrick** [comment]
retest this please

**Comment by batrick** [comment]
http://pulpito.ceph.com/?branch=wip-pdonnell-testing-20181023.224346

**Comment by batrick** [comment]
retest this please

**Pull request merged**
