### PR TITLE
nautilus: librbd: new 'write_zeroes' API methods to suppliment the `discard` APIs

### PR DESCRIPTION
**Pull request by dillaman**
https://tracker.ceph.com/issues/46673

### CODE REVIEW

**Comment by smithfarm** [comment]
@dillaman Do the multiple "(cherry picked from commit ...)" lines in the commit messages make sense to you?

**Comment by dillaman** [comment]
> @dillaman Do the multiple "(cherry picked from commit ...)" lines in the commit messages make sense to you?
> 
> (I'm guessing . . . they are cherry-picked from the open octopus PR #36247 ? Should we wait to merge this PR until that one merges, in case the octopus SHA1s change in the meantime?)

Yup and yup. I’ve always found it easier to not start over with a cherry-pick and instead base it on the previous release’s effort.

**Comment by yuriw** [comment]
[wip-yuri2-testing-2020-07-27-1539-nautilus](https://trello.com/c/Lvrpurb9/976-wip-yuri2-testing-2020-07-27-1539-nautilus)

**Comment by smithfarm** [comment]
Oops. Nautilus PR got merged before the Octopus one from which it was cherry-picked :-( Next time I'll try to remember to add DNM.

I also tend to cherry-pick from the newer stable branch if it makes the conflict resolution easier.

**Comment by smithfarm** [comment]
So, apparently this broke the i386 build? See https://github.com/ceph/ceph/pull/36620

**Pull request merged**
