### PR TITLE
doc: remove deprecated 'scrubq' from ceph(8)

### PR DESCRIPTION
**Pull request by rubenk**
The option was removed in a30cbe9adea34782be8699c010d4281d245feb6b

Signed-off-by: Ruben Kerkhof <ruben@rubenkerkhof.com>

- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by tchaikov** [comment]
strictly speaking, we should backport this change to mimic and luminous.

**Comment by tchaikov** [comment]
@rubenk could you add a "Fixed: http://tracker.ceph.com/issues/35813" line in your commit message?

**Comment by rubenk** [comment]
Sure thing, done.

**Comment by tchaikov** [comment]
retest this please.

**Comment by tchaikov** [comment]
retest this please.

**Pull request merged**
