### PR TITLE
erasure code: backend feature to read from all OSDs and silently discard EIO if possible

### PR DESCRIPTION
**Pull request by luowei62**
Bug: http://tracker.ceph.com/issues/9943

Brief: Add osd setting osd_pool_erasure_code_subread_all. Default is false. If set it to true. Will send sub-read op to all OSD and choose the first success read result.

Signed-off-by: Wei Luo <luowei@yahoo-inc.com>

### CODE REVIEW

**Comment by luowei62** [comment]
@athanatos @dachary 
This is pull request 2952. I can't reopen it so create a new one.

**Comment by dachary** [comment]
@luowei62 unassigning myself to clarify the needs-qa is not for me to run.

**Comment by athanatos** [comment]
This no longer merges cleanly.

**Comment by athanatos** [comment]
Re-add needs-qa once fixed.

**Comment by guangyy** [comment]
Hi @athanatos , @luowei62 left Yahoo!, and I will rebase this patch to make sure it can be scheduled for QA. Thanks!

**Comment by dachary** [comment]
@guangyy closing assuming it's now a duplicate of #4312

**Pull request closed without merging**
