### PR TITLE
dokan: cast variable to the expected type before comparison

### PR DESCRIPTION
**Pull request by tchaikov**
to fix the FTBFS due to following warning:

```
/home/jenkins-build/build/workspace/ceph-windows-pull-requests/ceph/build.deps/src/dokany/dokan/dokan.h:723:22: error: narrowing conversion of '-1' from 'int' to 'long unsigned int' [-Wnarrowing]
  723 | #define DOKAN_ERROR -1
      |                      ^
```

also, clean up the following warning:

```
/home/jenkins-build/build/workspace/ceph-windows-pull-requests/ceph/src/dokan/dbg.cc:142:62: warning: NULL used in arithmetic [-Wpointer-arith]
  142 |   o << "\n\tIsDirectory: " << (DokanFileInfo->IsDirectory != NULL);
      |
```

Signed-off-by: Kefu Chai <tchaikov@gmail.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [x] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by tchaikov** [comment]
this change should the FTBFS of https://jenkins.ceph.com/job/ceph-windows-pull-requests/11879/consoleFull#321394754e4bfde06-44c1-4b3c-8379-d9ee175fb257

**Comment by tchaikov** [comment]
jenkins test windows

**Comment by tchaikov** [comment]
```
compile options: '-I/usr/include/python3.10 -I/usr/include/python3.10 -c'
extra options: '-Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fno-var-tracking-assignments -iquote/home/jenkins-build/build/workspace/ceph-api/src/include -w -Dvoid0=dead_function(void) -D__Pyx_check_single_interpreter(ARG)=ARG ## 0 -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2'
cc: /home/jenkins-build/build/workspace/ceph-api/build/src/pybind/rados/rados.c
cc: warning: ##: linker input file unused because linking not done
cc: error: ##: linker input file not found: No such file or directory
cc: warning: 0: linker input file unused because linking not done
cc: error: 0: linker input file not found: No such file or directory
error: Command "/usr/bin/cc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -w -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fno-var-tracking-assignments -iquote/home/jenkins-build/build/workspace/ceph-api/src/include -w -Dvoid0=dead_function(void) -D__Pyx_check_single_interpreter(ARG)=ARG ## 0 -fPIC -I/usr/include/python3.10 -I/usr/include/python3.10 -c /home/jenkins-build/build/workspace/ceph-api/build/src/pybind/rados/rados.c -o /home/jenkins-build/build/workspace/ceph-api/build/lib/cython_modules/temp.linux-x86_64-3.10/home/jenkins-build/build/workspace/ceph-api/build/src/pybind/rados/rados.o -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fno-var-tracking-assignments -iquote/home/jenkins-build/build/workspace/ceph-api/src/include -w -Dvoid0=dead_function(void) -D__Pyx_check_single_interpreter(ARG)=ARG ## 0 -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2" failed with exit status 1
```

presumably a jammy-only issue.

**Comment by tchaikov** [comment]
jenkins test windows

**Comment by tchaikov** [comment]
jenkins test make check

**Comment by tchaikov** [comment]
jenkins test api

**Comment by tchaikov** [comment]
```

++ sudo virsh domifaddr --source agent --interface Ethernet --full ceph-win-ltsc2019-ceph-windows-pull-requests-11884
++ grep ipv4
++ awk '{print $4}'
++ cut -d / -f1
+ VM_IP=
+ echo 'Retrying in 10 seconds'
Retrying in 10 seconds
+ sleep 10
+ continue
+ true
+ [[ 602 -gt 600 ]]
+ echo 'Timeout waiting for the VM to start'
Timeout waiting for the VM to start
+ exit 1
```

**Comment by tchaikov** [comment]
jenkins test api

**Review by petrutlucian94 — APPROVED** [review]
Thanks! I hope we could unblock the windows job before merging the PR.

**Comment by tchaikov** [comment]
the failure is not related. on the contrary, i helps to get us closer to pass the test.

**Comment by djgalloway** [comment]
@petrutlucian94 Do you think it's possible the vagrant VM failed to come up because we're using 2.2.19 instead of 2.2.10 like we have been previously?

**Comment by petrutlucian94** [comment]
> @petrutlucian94 Do you think it's possible the vagrant VM failed to come up because we're using 2.2.19 instead of 2.2.10 like we have been previously?

Not sure about that. I see that virsh is unable to retrieve the VM IP using the qemu agent:

```
sudo virsh domifaddr --source agent --interface Ethernet --full ceph-win-ltsc2019-ceph-windows-pull-requests-11884
```

It may be worth checking the vm state as well as the qemu logs.

**Pull request merged**
