### PR TITLE
quincy: common/bl: fix FTBFS on C++11 due to C++17's if-with-initializer

### PR DESCRIPTION
**Pull request by rzarzynski**
Fixes: https://tracker.ceph.com/issues/55233
Signed-off-by: Radosław Zarzyński <rzarzyns@redhat.com>
(cherry picked from commit 2528f9d07017cf7cc77f4c02a993d97074db0596)

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by rzarzynski** [comment]
jenkins retest this please

**Comment by tchaikov** [comment]
jenkins test make check

**Review by tchaikov — APPROVED** [review]

**Comment by mattbenjamin** [comment]
I still don't see the point of such a change.  In 2022, it's reasonable to expect Ceph to be built with a C++17 compiler.

**Comment by tchaikov** [comment]
jenkins test make check

**Comment by mattbenjamin** [comment]
@adamemerson

**Comment by tchaikov** [comment]
> I still don't see the point of such a change. In 2022, it's reasonable to expect Ceph to be built with a C++17 compiler. And as I wrote in the tracker, I don't think the c++ rados interface is external, obviating the need to think about compilers we don't build the rest of ceph with.

but we do package libradospp-dev. if it is external, we would not need to package it and should hide it just as we do to libceph-common.

**Comment by rzarzynski** [comment]
> I still don't see the point of such a change. In 2022, it's reasonable to expect Ceph to be built with a C++17 compiler. And as I wrote in the tracker, I don't think the c++ rados interface is external, obviating the need to think about compilers we don't build the rest of ceph with.

I think we discussed this during the CDS Reef. The problem is formal in its nature. In theory the API should be C++11 compliant. For `main` we can void any claims on that but older release is a different story.

**Pull request merged**
