### PR TITLE
jewel: ceph-disk: bluestore --setgroup incorrectly set with user

### PR DESCRIPTION
**Pull request by shinobu-x**
http://tracker.ceph.com/issues/18957

### CODE REVIEW

**Comment by dachary** [comment]
http://pulpito.ceph.com/smithfarm-2017-02-20_21:30:56-ceph-disk-wip-jewel-backports-distro-basic-vps/ fails maybe because of this backport, or because of https://github.com/ceph/ceph/pull/13496

**Comment by dachary** [comment]
https://github.com/ceph/ceph/pull/13496 was the cause of the failure, removing the DNM on this one so it can be tested again

**Comment by shinobu-x** [comment]
jenkins test this please

**Comment by smithfarm** [comment]
@dachary This passed a ceph-disk suite at http://tracker.ceph.com/issues/19538?issue_count=4&issue_position=1&next_issue_id=19055#note-9

OK to merge?

**Comment by smithfarm** [comment]
@dachary Note - do not merge it yet! Need to wait until the v10.2.7 tag is added to jewel branch.

**Pull request merged**
