### PR TITLE
mimic: run-standalone.sh: Need double-quotes to handle | in core_pattern on all distributions

### PR DESCRIPTION
**Pull request by ashishkumsingh**
https://tracker.ceph.com/issues/38565

### CODE REVIEW

**Comment by smithfarm** [comment]
compilation error will be fixed by https://github.com/ceph/ceph/pull/26814

**Comment by smithfarm** [comment]
jenkins test make check

**Comment by smithfarm** [comment]
jenkins re-test this please

**Comment by yuriw** [comment]
[wip-yuri-testing-2019-05-01-1606-mimic](https://trello.com/c/rBbnyk01/603-wip-yuri-testing-2019-05-01-1606-mimic)

**Pull request merged**
