### PR TITLE
[DNM] jewel: tests: TestLibRBD.UpdateFeatures tests failed in upgrade:client-upgrade-jewel-distro-basic-vps

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/19080

### CODE REVIEW

**Comment by dillaman** [comment]
@smithfarm I don't think there is a baf17c90980f3c61f75775f561ced5b2a1d2141c build available in shaman

**Comment by dillaman** [comment]
https://shaman.ceph.com/builds/ceph/infernalis/baf17c90980f3c61f75775f561ced5b2a1d2141c/

**Comment by smithfarm** [comment]
@dillaman It's on the way - see http://tracker.ceph.com/issues/18089#note-62

**Comment by dillaman** [comment]
@smithfarm Since David built baf17c90980f3c61f75775f561ced5b2a1d2141c and ensured it won't be deleted, I wonder if this change is even needed since I would think shaman would correctly pull the most recent infernalis branch revision that is available.

**Comment by smithfarm** [comment]
Before David's fix, the test was doing this:

```
2017-02-24T17:58:12.856 INFO:teuthology.packaging:branch: infernalis
2017-02-24T17:58:12.857 INFO:teuthology.packaging:sha1: d9eaab456ff45ae88e83bd633f0c4efb5902bf07
2017-02-24T17:58:12.857 DEBUG:teuthology.packaging:Querying https://shaman.ceph.com/api/search?status=ready&project=ceph&flavor=default&distros=ubuntu%2F14.04%2Fx86_64&ref=infernalis
2017-02-24T17:58:13.127 INFO:teuthology.task.install.deb:Pulling from https://chacra.ceph.com/r/ceph/infernalis/752b6a3020c3de74e07d2a8b4c5e48dab5a6b6fd/ubuntu/trusty/flavors/default/
2017-02-24T17:58:13.128 INFO:teuthology.task.install.deb:Package version is 9.2.1-1trusty
```

After David's fix, it does this:

```
2017-04-13T12:46:48.918 INFO:teuthology.packaging:branch: infernalis
2017-04-13T12:46:48.918 INFO:teuthology.packaging:sha1: abb4e853ac92153045370b75b390b8201ba7c57b
2017-04-13T12:46:48.918 DEBUG:teuthology.packaging:Querying https://shaman.ceph.com/api/search?status=ready&project=ceph&flavor=default&distros=ubuntu%2F14.04%2Fx86_64&ref=infernalis
2017-04-13T12:46:49.016 INFO:teuthology.task.install.deb:Pulling from https://3.chacra.ceph.com/r/ceph/infernalis/baf17c90980f3c61f75775f561ced5b2a1d2141c/ubuntu/trusty/flavors/default/
2017-04-13T12:46:49.016 INFO:teuthology.task.install.deb:Package version is 9.2.1-31-gbaf17c9-1trusty
```

So clearly @dillaman is right and this PR is not needed.

**Pull request closed without merging**
