### PR TITLE
#11481: MDS resilience to weird mdsmaps

### PR DESCRIPTION
**Pull request by jcsp**
Plus some bonus bits from when I was looking through this code.

boot statemachine wasn't the right tool for the job here, as in order to use it we'd have to have code to translate the (oldstate, state) tuple into an event (and reject state transitions that weren't valid events), by which point we would have done all the validation we need.

### CODE REVIEW

**Comment by gregsfortytwo** [comment]
in tonight's greg-fs-testing to make sure it didn't break anything.

**Comment by gregsfortytwo** [comment]
ubuntu@teuthology:/a/ubuntu-2015-05-12_23:32:41-fs-greg-fs-testing-testing-basic-multi/889677

> mds.0.446 Invalid state transition up:replay->up:reconnect

**Comment by jcsp** [comment]
Updated to handle the cases where the MDS skips past RESOLVE or CLIENTREPLAY.

Also the "handle DNE beacon from MDS" was broken too, because it didn't propose the new OSDMap after blacklisting, that's fixed too.

**Comment by gregsfortytwo** [comment]
Running through greg-fs-testing again.

**Comment by jcsp** [comment]
Failure in handle_mds_map, fixing...

http://pulpito.front.sepia.ceph.com/gregf-2015-05-14_21:57:00-fs-greg-fs-testing-testing-basic-multi/893519/
http://pulpito.front.sepia.ceph.com/gregf-2015-05-14_21:57:00-fs-greg-fs-testing-testing-basic-multi/893529/
http://pulpito.front.sepia.ceph.com/gregf-2015-05-14_21:57:00-fs-greg-fs-testing-testing-basic-multi/893553/

**Comment by jcsp** [comment]
Pushed a fix.  @gregsfortytwo are you planning on scheduling another suite today?

**Comment by gregsfortytwo** [comment]
I think so

**Comment by jcsp** [comment]
Scheduled: http://pulpito.front.sepia.ceph.com/john-2015-05-18_12:37:56-fs-wip-11481-testing-basic-multi/

**Comment by gregsfortytwo** [comment]
@ukernel please remember to include Reviewed-by: lines when merging — it's important to demonstrate that the reviews have happened, in addition to leaving breadcrumbs for help when things get broken and the release statistics. ;)

**Pull request merged**
