### PR TITLE
mgr/dashboard: incorporate RBD overall performance grafana dashboard

### PR DESCRIPTION
**Pull request by dillaman**
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by dillaman** [comment]
screenshot from 2019-01-11 14-27-51

**Comment by dillaman** [comment]
jenkins test dashboard

**Comment by callithea** [comment]
For some reason the webdriver-manager seems to fail when the ceph dashboard (end-to-end) tests are about to start. I was able to run the end-to-end tests on my local system (based on this PR) though.

**Comment by LenzGr** [comment]
Fixes: https://tracker.ceph.com/issues/37867

**Pull request merged**
