### PR TITLE
pacific: osd/PGLog.cc: Trim duplicates by number of entries

### PR DESCRIPTION
**Pull request by rzarzynski**
Backport of https://github.com/ceph/ceph/pull/45529.

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/master/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Review by neha-ojha — APPROVED** [review]

**Review by NitzanMordhai — APPROVED** [review]

**Comment by rubenk** [comment]
This PR contains 983 commits, that doesn't seem right.

**Comment by k0ste** [comment]
@rzarzynski, can you rebase please?

**Comment by neha-ojha** [comment]
@rubenk @k0ste I have fixed the commits.

**Comment by cervigni** [comment]
Hello,

Could someone explain me how long this is going to take to be merged and packaged for pacific stable? I thought it was the case when merged into master but I was mistaken, as 16.2.8/9 does not contain the PR. Thanks !

**Comment by gadLinux** [comment]
Yes. Same here. Waiting for this patch to bring up my cluster...

**Comment by gadLinux** [comment]
@k0ste @rubenk Can you check please and merge if properly done?

**Comment by neha-ojha** [comment]
> @neha-ojha This PR is approved by 2 people and all checks have passed. What is the next step to merge this?

This PR will be picked by @yuriw for teuthology testing. We'll merge the PR after reviewing the test results.

**Comment by gadLinux** [comment]
> > @neha-ojha This PR is approved by 2 people and all checks have passed. What is the next step to merge this?
> 
> This PR will be picked by @yuriw for teuthology testing. We'll merge the PR after reviewing the test results.

Is there any repository of ubuntu packages or binaries so I can give it a try in my cluster?... I don't know why but I'm unable to build it.

**Comment by neha-ojha** [comment]
> > > @neha-ojha This PR is approved by 2 people and all checks have passed. What is the next step to merge this?
> > 
> > 
> > This PR will be picked by @yuriw for teuthology testing. We'll merge the PR after reviewing the test results.
> 
> Is there any repository of ubuntu packages or binaries so I can give it a try in my cluster?... I don't know why but I'm unable to build it.

@gadLinux This PR is being tested using https://shaman.ceph.com/builds/ceph/wip-yuri4-testing-2022-06-01-1350-pacific/, and the builds will temporarily be available in shaman. Note that the branch wip-yuri4-testing-2022-06-01-1350-pacific has other patches as well https://github.com/ceph/ceph-ci/tree/wip-yuri4-testing-2022-06-01-1350-pacific. 
I'd suggest waiting a day or two for this PR to be merged and then use pacific builds from https://shaman.ceph.com/builds/ceph/pacific/.

**Comment by ljflores** [comment]
http://pulpito.front.sepia.ceph.com/yuriw-2022-06-02_00:50:42-rados-wip-yuri4-testing-2022-06-01-1350-pacific-distro-default-smithi/
http://pulpito.front.sepia.ceph.com/yuriw-2022-06-02_14:44:32-rados-wip-yuri4-testing-2022-06-01-1350-pacific-distro-default-smithi/

Failures, unrelated:
    1. https://tracker.ceph.com/issues/52321
    2. https://tracker.ceph.com/issues/54992
    3. https://tracker.ceph.com/issues/53939
    4. https://tracker.ceph.com/issues/54071
    5. https://tracker.ceph.com/issues/53501
    6. https://tracker.ceph.com/issues/45318
    7. https://tracker.ceph.com/issues/49888
    8. https://tracker.ceph.com/issues/55906

Details:
    1. qa/tasks/rook times out: 'check osd count' reached maximum tries (90) after waiting for 900 seconds - Ceph - Orchestrator
    2. cannot stat '/etc/containers/registries.conf': No such file or directory - Ceph - Orchestrator
    3. ceph-nfs-upgrade, pacific: Upgrade Paused due to UPGRADE_REDEPLOY_DAEMON: Upgrading daemon osd.0 on host smithi103 failed - Ceph - Orchestrator
    4. rados/cephadm/osds: Invalid command: missing required parameter hostname(<string>) - Ceph - Orchestrator
    5. Exception when running 'rook' task. - Ceph - Orchestrator
    6. octopus: Health check failed: 2/6 mons down, quorum b,a,c,e (MON_DOWN)" in cluster log running tasks/mon_clock_no_skews.yaml - Ceph - RADOS
    7. rados/singleton: radosbench.py: teuthology.exceptions.MaxWhileTries: reached maximum tries (3650) after waiting for 21900 seconds - Ceph - RADOS
    8. qa/standalone/osd/osd-force-create-pg.sh: TEST_reuse_id: return 1 - Ceph - RADOS

**Comment by ljflores** [comment]
http://pulpito.front.sepia.ceph.com/yuriw-2022-06-02_00:50:42-rados-wip-yuri4-testing-2022-06-01-1350-pacific-distro-default-smithi/
http://pulpito.front.sepia.ceph.com/yuriw-2022-06-02_14:44:32-rados-wip-yuri4-testing-2022-06-01-1350-pacific-distro-default-smithi/

Failures, unrelated:
    1. https://tracker.ceph.com/issues/52321
    2. https://tracker.ceph.com/issues/54992
    3. https://tracker.ceph.com/issues/53939
    4. https://tracker.ceph.com/issues/54071
    5. https://tracker.ceph.com/issues/53501
    6. https://tracker.ceph.com/issues/45318
    7. https://tracker.ceph.com/issues/49888
    8. https://tracker.ceph.com/issues/55906

Details:
    1. qa/tasks/rook times out: 'check osd count' reached maximum tries (90) after waiting for 900 seconds - Ceph - Orchestrator
    2. cannot stat '/etc/containers/registries.conf': No such file or directory - Ceph - Orchestrator
    3. ceph-nfs-upgrade, pacific: Upgrade Paused due to UPGRADE_REDEPLOY_DAEMON: Upgrading daemon osd.0 on host smithi103 failed - Ceph - Orchestrator
    4. rados/cephadm/osds: Invalid command: missing required parameter hostname(<string>) - Ceph - Orchestrator
    5. Exception when running 'rook' task. - Ceph - Orchestrator
    6. octopus: Health check failed: 2/6 mons down, quorum b,a,c,e (MON_DOWN)" in cluster log running tasks/mon_clock_no_skews.yaml - Ceph - RADOS
    7. rados/singleton: radosbench.py: teuthology.exceptions.MaxWhileTries: reached maximum tries (3650) after waiting for 21900 seconds - Ceph - RADOS
    8. qa/standalone/osd/osd-force-create-pg.sh: TEST_reuse_id: return 1 - Ceph - RADOS

**Comment by cervigni** [comment]
Due to the bug severity, is this going to be soon released as 16.2.10 or do we have to wait more?
Thanks

**Comment by wvh-github** [comment]
Just to inform everyone following this PR. It is going to be reverted:

https://github.com/ceph/ceph/pull/46610

**Pull request merged**
