### PR TITLE
mgr/dashboard: access_control: add grafana scope read access t…

### PR DESCRIPTION
**Pull request by rjfd**
Fixes: https://tracker.ceph.com/issues/41572

Signed-off-by: Ricardo Dias <rdias@suse.com>

### CODE REVIEW

**Comment by rjfd** [comment]
jenkins test signed

**Comment by rjfd** [comment]
jenkins test docs

**Comment by rjfd** [comment]
jenkins test dashboard

**Comment by rjfd** [comment]
@epuertat totally agree with you. Before doing this fix I considered to remove the grafana scope, but that requires a lot more work and thinking.

Let's create a ticket for it so that it doesn't get forgotten.

**Comment by epuertat** [comment]
> Let's create a ticket for it so that it doesn't get forgotten.

Done: https://tracker.ceph.com/issues/41586

**Pull request merged**
