### PR TITLE
mds: Do flush to insure all locks be released in time

### PR DESCRIPTION
**Pull request by flywayway**
Signed-off-by: Wei Feng <feng.wei@h3c.com>

### CODE REVIEW

**Comment by gregsfortytwo** [comment]
Is there some observed bug this is fixing for you? I don't think it should be necessary — if we did an early reply nobody's blocked waiting on the op to hit disk, and this forces a flush to the mds log on every op! That eliminates the batching, which negates most of the purpose of having an mds log.

**Comment by flywayway** [comment]
When there is more than one mds active. / is assigned to mds0, while /dirnew is assigned to mds1. When I  make dir one by one in /dirnew, the request of getattr of /dirnew will send to mds0, while mkdir will forward to mds1. Mds1 will ask lock for the inode of /dirnew when mkdir, while the next getattr of /dirnew will wait the lock until mds0 to release.

**Comment by ukernel** [comment]
I think this behaviour only happens on ceph-fuse, Am I right?

**Comment by flywayway** [comment]
@ukernel It also happens on kernal mount. You can test like this:
1. Create 100 folders in the root directory (mkdir a1 to a100);
2. Then cd a1, create 100 folders in a1 (mkdir b1 to b100);
3. Then cd .., create 100 folders in the root directory (mkdir c1 to c100);
4. Then cd a1, create 100 folders in a1 (mkdir d1 to d100);
Then it will take five seconds to create a folder.

**Comment by gregsfortytwo** [comment]
In that case we probably want to initiate a log flush when caps are waiting
on it. I think we do that in some cases and must have missed this one?

**Comment by ukernel** [comment]
I try following commands:

for i in `seq 1 100`; do mkdir a$i; done
cd a1
for i in `seq 1 100`; do mkdir b$i; done
cd ..
for i in `seq 1 100`; do mkdir c$i; done
cd a1
for i in `seq 1 100`; do mkdir d$i; done

It tooks less than one second to finish

**Comment by flywayway** [comment]
@ukernel we should operate the 4 step separately(wait greater than 10 seconds after one step) , may be wait mds to finish load rebalance before step 4.

**Comment by flywayway** [comment]
@ukernel 
My test file mkdir.py:
-----------------------------------------------------------------------------------------------------
#!/usr/bin/python

import os
import sys

def mkdir(name, num):
    for i in range (0, int(num)):
        print "mkdir %s%s" %(name, i)
        os.popen("mkdir %s%s" %(name, i))

def main():
    name = sys.argv[1]
    num = sys.argv[2]
    print name
    print num
    mkdir(name, num)

if __name__=="__main__":
    main()
-----------------------------------------------------------------------------------------------------
The history command:

 1221  mount -t ceph 172.16.31.200:6789:/ /root/mnt -o name=admin,secretfile=/etc/ceph/admin.secret
 1222  cp mkdir.py mnt
 1223  cd mnt
 1224  ./mkdir.py a 100
 1225  cp mkdir.py a0
 1226  ./mkdir.py b 100
 1227  cd ..
 1228  umount mnt
 1229  mount -t ceph 172.16.31.200:6789:/ /root/mnt -o name=admin,secretfile=/etc/ceph/admin.secret
 1230  cp mkdir.py mnt
 1231  cd mnt
 1232  ./mkdir.py a 100
 1233  cd ..
 1234  umount mnt
 1235  rm -r mnt
 1236  mkdir mnt
 1237  mount -t ceph 172.16.31.200:6789:/ /root/mnt -o name=admin,secretfile=/etc/ceph/admin.secret
 1238  cp mkdir.py mnt
 1239  cd mnt
 1240  ./mkdir.py a 100
 1241  cp mkdir.py a0
 1242  cd a0
 1243  ./mkdir.py b 100
 1244  cd ..
 1245  ./mkdir.py c 100
 1246  cd a0
 1247  ./mkdir.py d 100
 1248  history

**Comment by flywayway** [comment]
@ukernel Because "os.popen("mkdir %s%s" %(name, i))" has one more step "getattr" before "lookup" and "mkdir", so next "getattr" will wait "mkdir" to release lock.

**Comment by ukernel** [comment]
I think there is better way to handle this. flush the log when MDS changes the lock state from MIX to MIX_SYNC/MIX_LOCK

**Pull request closed without merging**
