### PR TITLE
reef: msgr: AsyncMessenger add faulted connections metrics

### PR DESCRIPTION
**Pull request by pereman2**
backport tracker: https://tracker.ceph.com/issues/62025

---

backport of https://github.com/ceph/ceph/pull/50393
parent tracker: https://tracker.ceph.com/issues/59076

### CODE REVIEW

**Review by jmolmo — APPROVED** [review]

**Review by idryomov — APPROVED** [review]

**Comment by idryomov** [comment]
@pereman2 Please note the edited description.  If not using `ceph-backport.sh` script, it needs to be produced manually.

**Comment by ljflores** [comment]
Building here: https://shaman.ceph.com/builds/ceph/wip-lflores-testing-2023-09-08-1504-reef/3a47b8b8607fe2b47509aab41ab01b756a8979b4/

**Comment by ljflores** [comment]
Jobs scheduled here: http://pulpito.front.sepia.ceph.com/lflores-2023-09-08_18:08:19-rados-wip-lflores-testing-2023-09-08-1504-reef-distro-default-smithi/

**Comment by ljflores** [comment]
The jobs will all likely be finished running by next week Monday.

**Comment by pereman2** [comment]
@ljflores test failures look unrelated, can you confirm?

**Comment by ljflores** [comment]
Hi @pereman2, taking a look

**Comment by ljflores** [comment]
Failures, unrelated:
1. https://tracker.ceph.com/issues/62992
2. https://tracker.ceph.com/issues/61774
3. https://tracker.ceph.com/issues/58946
4. https://tracker.ceph.com/issues/59196

Details:
1. Heartbeat crash in osd - Ceph - RADOS
2. centos 9 testing reveals rocksdb "Leak_StillReachable" memory leak in mons - Ceph - RADOS
3. cephadm: KeyError: 'osdspec_affinity' - Ceph - Orchestrator
5. ceph_test_lazy_omap_stats segfault while waiting for active+clean - Ceph - RADOS

**Comment by pereman2** [comment]
> @pereman2 please see this new failure, which came up three times in the run. I don't think it's related, but see what you think: Heartbeat crash in osd - https://tracker.ceph.com/issues/62992
> 
> Otherwise, everything else is for sure unrelated. If you deem the above tracker to be unrelated, feel free to merge (on behalf of rados).
> 
> Failures, unrelated:
> 
> 1. https://tracker.ceph.com/issues/61774
> 2. https://tracker.ceph.com/issues/58946
> 3. https://tracker.ceph.com/issues/59196
> 
> Details:
> 
> 1. centos 9 testing reveals rocksdb "Leak_StillReachable" memory leak in mons - Ceph - RADOS
> 2. cephadm: KeyError: 'osdspec_affinity' - Ceph - Orchestrator
> 3. ceph_test_lazy_omap_stats segfault while waiting for active+clean - Ceph - RADOS

Thanks @ljflores. I don't think it is related so we might go forward with merging it.

**Comment by aaSharma14** [comment]
@jmolmo , Can you please merge this PR after a final review? Thanks

**Pull request merged**
