### PR TITLE
os/bluestore: recalc_allocated() when decoding bluefs_fnode_t

### PR DESCRIPTION
**Pull request by tchaikov**
Fixes: http://tracker.ceph.com/issues/23212
Signed-off-by: Jianpeng Ma <jianpeng.ma@intel.com>
Signed-off-by: Kefu Chai <kchai@redhat.com>

### CODE REVIEW

**Comment by majianpeng** [comment]
It looks good. And i close my PR.

**Comment by ifed01** [comment]
You might also want to remove existing "fnode.recalc_allocated();" call from BlueFS::_replay function

**Comment by tchaikov** [comment]
@ifed01 fixed and repushed.

**Comment by tchaikov** [comment]
retest this please.

**Comment by tchaikov** [comment]
http://pulpito.ceph.com/kchai-2018-03-05_17:31:09-rados-wip-kefu-testing-2018-03-05-2238-distro-basic-smithi/

**Pull request merged**
