### PR TITLE
rgw: cleanup radosgw-admin url options

### PR DESCRIPTION
**Pull request by mikulely**
+ drop unused --master-url
+ doc --url option

Signed-off-by: Jiaying Ren <jiaying.ren@umcloud.com>

### CODE REVIEW

**Comment by mikulely** [comment]
@joscollin mind to  merge?

**Comment by robbat2** [comment]
@mikulely please rebase

**Comment by mikulely** [comment]
@robbat2 done

**Comment by robbat2** [comment]
@mikulely  Joscollin had also suggested updating the documentation text to match. otherwise LGTM.

**Comment by joscollin** [comment]
No response. So closing in favor of https://github.com/ceph/ceph/commit/ab5a158a3b906e7af44c2e75a31dd686e91751cf.

**Pull request closed without merging**
