### PR TITLE
ceph-objectstore-tool: make 'rm-omap' command support remove many keys

### PR DESCRIPTION
**Pull request by trociny**
We had a case when we needed to clean many (several thousand)  snapmapper keys. Doing this with `rm-omap` took hours.

### CODE REVIEW

**Comment by jdurgin** [comment]
this seems like a good idea to me @dzafman what do you think?

needs rebase as well

**Comment by dzafman** [comment]
@jdurgin I'm not sure how much this is an issue.  I'm afraid this option could be misused, but then again ceph-objectstore-tool is meant for things like this.

Maybe this feature should be just rm-omap without key argument but with --file specified or stdin not a tty.

**Comment by trociny** [comment]
@dzafman I like the idea of  just rm-omap without key argument but with --file. I am going to update this way.

**Comment by dzafman** [comment]
@trociny It makes me nervous that this code will create an arbitrarily large transaction.  Should this code limit the size of any 1 transaction AND queue_transaction() every "osd_target_transaction_size" transactions?

**Comment by trociny** [comment]
@dzafman It worked very well for chunks much larger then osd_target_transaction_size default (30), but I think it is a good idea to have some configurable limit, so thank you for the suggestion.

**Comment by trociny** [comment]
@dzafman, @jdurgin  updated

**Comment by dzafman** [comment]
@trociny My suggestion is to provide a more general --op that can parse arguments from stdin or a file and perform all operations specified.  See http://tracker.ceph.com/issues/38215

**Pull request closed without merging**
