### PR TITLE
mgr/cephadm: increase ingress timeout values

### PR DESCRIPTION
**Pull request by senax**
This commit increases the 'timeout client' and 'timeout server' from 1s to 30s. S3cmd multi-part uploads were failing with the shorter timeout.

Fixes: https://tracker.ceph.com/issues/58183
Signed-off-by: Frank Ederveen <frank.ederveen@gmail.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [x] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by senax** [comment]
Not entirely sure yet how this would have caused this failure:
```
[ RUN      ] TestLibRBD.LargeCacheRead
using new format!
[       OK ] TestLibRBD.LargeCacheRead (95 ms)
[ RUN      ] TestLibRBD.TestPendingAio
using new format!
/home/jenkins-build/build/workspace/ceph-pull-requests/src/test/librbd/test_librbd.cc:8211: Failure
Expected equality of these values:
  1
  rbd_aio_is_complete(comps[i])
    Which is: 0
[  FAILED  ] TestLibRBD.TestPendingAio (150 ms)
[ RUN      ] TestLibRBD.CompareAndWriteCopyup
using new format!
using new format!
[       OK ] TestLibRBD.CompareAndWriteCopyup (548 ms)
```

**Comment by rkachach** [comment]
jenkins test make check

**Comment by adk3798** [comment]
> Not entirely sure yet how this would have caused this failure:
> 
> ```
> [ RUN      ] TestLibRBD.LargeCacheRead
> using new format!
> [       OK ] TestLibRBD.LargeCacheRead (95 ms)
> [ RUN      ] TestLibRBD.TestPendingAio
> using new format!
> /home/jenkins-build/build/workspace/ceph-pull-requests/src/test/librbd/test_librbd.cc:8211: Failure
> Expected equality of these values:
>   1
>   rbd_aio_is_complete(comps[i])
>     Which is: 0
> [  FAILED  ] TestLibRBD.TestPendingAio (150 ms)
> [ RUN      ] TestLibRBD.CompareAndWriteCopyup
> using new format!
> using new format!
> [       OK ] TestLibRBD.CompareAndWriteCopyup (548 ms)
> ```

some of the make check tests are just a bit flaky, unrelated to your change.

**Review by adk3798 — APPROVED** [review]
LGTM, will run through standard testing when the builds are working again

**Comment by adk3798** [comment]
https://pulpito.ceph.com/adking-2023-01-21_05:38:21-orch:cephadm-wip-adk-testing-2023-01-20-1359-distro-default-smithi/

Lots of failures (13) but all accounted for

- 3 instances of `'list' object has no attribute 'get'`. Failure was on new test for setting mon crush location introduced by a PR in the run. That PR can't be merged, but this shouldn't block merging anything else.
- 2 instances of test_cephadm.sh test failing, caused by the same mon crush location PR. Failed with `local variable 'config_json' referenced before assignment`
- 1 instance of https://tracker.ceph.com/issues/49287, known issue
- 2 instances of https://tracker.ceph.com/issues/58524, known issue
- 2 instances of https://tracker.ceph.com/issues/58535, known issue
- 1 instance of https://tracker.ceph.com/issues/57771, known issue
- 1 instance of https://tracker.ceph.com/issues/57755, known issue
- 1 failed basic smoke test that timed out waiting for all 8 OSDs to come up. Did 5 reruns of this test with the same build (https://pulpito.ceph.com/adking-2023-01-22_15:28:20-orch:cephadm-wip-adk-testing-2023-01-20-1359-distro-default-smithi/) all of which passed. My guess is an I/O error creating the last OSD, which I've seen happen (infrequently) when we make a bunch of OSDs on the split up nvme drive we use for having multiple OSDs on these machines. Considering it a 1 off for now, and not blocking merging over it.

Overall, PRs in the run should be okay to merge other than the mon crush location one causing failures. Will start to try and clean up the test suite now that we're able to make builds and run tests again.

**Comment by adk3798** [comment]
jenkins retest this please

**Pull request merged**
