### PR TITLE
mgr/dashboard: bump node version to 10.19

### PR DESCRIPTION
**Pull request by tchaikov**
10.19.0 is the latest stable version of Node.js 10.x

Signed-off-by: Kefu Chai <kchai@redhat.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by tchaikov** [comment]
not sure if this change makes sense. the reason i had this change was to understand why we have
```
Collecting nodeenv
  Using cached nodeenv-1.3.5-py2.py3-none-any.whl (21 kB)
Installing collected packages: nodeenv
Successfully installed nodeenv-1.3.5
 * Install prebuilt node (10.18.1) ..
Traceback (most recent call last):
  File "/tmp/tmp.amYX8D7AvX/bin/nodeenv", line 8, in <module>
    sys.exit(main())
  File "/tmp/tmp.amYX8D7AvX/local/lib/python2.7/site-packages/nodeenv.py", line 1113, in main
    create_environment(env_dir, opt)
  File "/tmp/tmp.amYX8D7AvX/local/lib/python2.7/site-packages/nodeenv.py", line 936, in create_environment
    install_node(env_dir, src_dir, opt)
  File "/tmp/tmp.amYX8D7AvX/local/lib/python2.7/site-packages/nodeenv.py", line 700, in install_node
    install_node_wrapped(env_dir, src_dir, opt)
  File "/tmp/tmp.amYX8D7AvX/local/lib/python2.7/site-packages/nodeenv.py", line 723, in install_node_wrapped
    download_node_src(node_url, src_dir, opt, prefix)
  File "/tmp/tmp.amYX8D7AvX/local/lib/python2.7/site-packages/nodeenv.py", line 570, in download_node_src
    for member in members(archive)
  File "/usr/lib/python2.7/tarfile.py", line 1836, in getmembers
    self._load()        # all members, we first have to
  File "/usr/lib/python2.7/tarfile.py", line 2417, in _load
    tarinfo = self.next()
  File "/usr/lib/python2.7/tarfile.py", line 2348, in next
    self.fileobj.seek(self.offset - 1)
  File "/usr/lib/python2.7/gzip.py", line 443, in seek
    self.read(1024)
  File "/usr/lib/python2.7/gzip.py", line 268, in read
    self._read(readsize)
  File "/usr/lib/python2.7/gzip.py", line 315, in _read
    self._read_eof()
  File "/usr/lib/python2.7/gzip.py", line 354, in _read_eof
    hex(self.crc)))
IOError: CRC check failed 0x7bef799 != 0xec5b3912L
```

when running:

```
nodeenv -p --node=10.18.1
```

**Comment by tspmelo** [comment]
Initially I though it might be related to python version or different arch, but I found other jenkins jobs with the same configuration that passed.
So I will also guess its a random network issue.
Not sure how to prevent this...

**Comment by tchaikov** [comment]
jenkins render docs

**Comment by tspmelo** [comment]
A new version of node is going to be used in https://github.com/ceph/ceph/pull/33121.

**Pull request closed without merging**
