### PR TITLE
rgw: fix s3 website redirection error

### PR DESCRIPTION
**Pull request by joke-lee**
when enable bucket static website as follow configure
```
<WebsiteConfiguration xmlns='http://s3.amazonaws.com/doc/2006-03-01/'>
  <IndexDocument>
    <Suffix>index.html</Suffix>
  </IndexDocument>
  <ErrorDocument>
    <Key>Error.html</Key>
  </ErrorDocument>
  <RoutingRules>
    <RoutingRule>
    <Condition>
      <KeyPrefixEquals>test/</KeyPrefixEquals>
    </Condition>
    <Redirect>
      <ReplaceKeyPrefixWith>tests/</ReplaceKeyPrefixWith>
    </Redirect>
    </RoutingRule>
  </RoutingRules>
</WebsiteConfiguration>
```
```
[root@dev build]# curl http://website01.eos-website.ecloud.today/test/1.html -v
* About to connect() to website01.eos-website.ecloud.today port 80 (#0)
*   Trying 192.168.153.165...
* Connected to website01.eos-website.ecloud.today (192.168.153.165) port 80 (#0)
> GET /test/1.html HTTP/1.1
> User-Agent: curl/7.29.0
> Host: website01.eos-website.ecloud.today
> Accept: */*
>
< HTTP/1.1 200 OK
< Location: http://website01.eos-website.ecloud.today/tests/1.html
< x-amz-request-id: tx000000000000000000001-005a1fb7c6-14882-default
< Content-Length: 0
< Date: Thu, 30 Nov 2017 08:57:25 GMT
<
```

it should return 301  rather  200

Signed-off-by: yuliyang <yuliyang@cmss.chinamobile.com>

### CODE REVIEW

**Comment by joke-lee** [comment]
hi, @cbodley do you mind to help review this ? thanks

**Comment by cbodley** [comment]
thanks @joke-lee - were you able to run the s3tests in test_s3_website.py against this branch?

**Comment by joke-lee** [comment]
test this please

**Comment by joke-lee** [comment]
hi @cbodley , as far as i know ,the `rgw_dns_s3website_name`  can not configure same value as `rgw_dns_name`,  how to configure the s3websitedomain right in s3test?

**Comment by cbodley** [comment]
thanks @joke-lee, it looks like some test cases aren't getting 301 when they expected to, ie test_website_xredirect_public_relative

**Comment by cbodley** [comment]
@robbat2 can you help with review?

**Comment by robbat2** [comment]
This change looks like it breaks those other tests; need a different tweak instead to fix it.

**Comment by cbodley** [comment]
i've been working on getting the s3 website tests running in teuthology at https://github.com/ceph/ceph/pull/20570, so i'll be trying to get all of them passing

**Comment by cbodley** [comment]
when testing this branch, i'm only seeing 3 test failures, and none are related to error codes:

```
FAIL: s3tests.functional.test_s3_website.test_routing_generator({'url': '/x', 'xml': {'RoutingRules': '<RoutingRule><Condition><HttpErrorCodeReturnedEquals>404</Ht
tpErrorCodeReturnedEquals></Condition><Redirect><HostName>ec2-11-22-333-44.compute-1.amazonaws.com</HostName><ReplaceKeyPrefixWith>report-404/</ReplaceKeyPrefixWit
h></Redirect></RoutingRule>'}, 'code': 301, 'location': {'path': '/report-404/x', 'hostname': 'ec2-11-22-333-44.compute-1.amazonaws.com', 'proto': 'http'}},)

AssertionError: Location header should be set "http://ec2-11-22-333-44.compute-1.amazonaws.com/report-404/x/index-aew19svwl0wsdyj5tde3a.html" != "http://ec2-11-22-
333-44.compute-1.amazonaws.com/report-404/x"


FAIL: s3tests.functional.test_s3_website.test_routing_generator({'url': '/images/x', 'xml': {'RoutingRules': '<RoutingRule><Condition><HttpErrorCodeReturnedEquals>
404</HttpErrorCodeReturnedEquals></Condition><Redirect><HostName>ec2-11-22-333-44.compute-1.amazonaws.com</HostName><ReplaceKeyPrefixWith>report-404/</ReplaceKeyPr
efixWith></Redirect></RoutingRule>'}, 'code': 301, 'location': {'path': '/report-404/images/x', 'hostname': 'ec2-11-22-333-44.compute-1.amazonaws.com', 'proto': 'h
ttp'}},)

AssertionError: Location header should be set "http://ec2-11-22-333-44.compute-1.amazonaws.com/report-404/images/x/index-75qu65nudc0p2iozqhygi.html" != "http://ec2
-11-22-333-44.compute-1.amazonaws.com/report-404/images/x"


FAIL: s3tests.functional.test_s3_website.test_routing_generator({'url': '/images/x', 'xml': {'RoutingRules': '<RoutingRule><Condition><KeyPrefixEquals>images/</Key
PrefixEquals><HttpErrorCodeReturnedEquals>404</HttpErrorCodeReturnedEquals></Condition><Redirect><HostName>ec2-11-22-333-44.compute-1.amazonaws.com</HostName><Repl
aceKeyPrefixWith>report-404/</ReplaceKeyPrefixWith></Redirect></RoutingRule>'}, 'code': 301, 'location': {'path': '/report-404/x', 'hostname': 'ec2-11-22-333-44.co
mpute-1.amazonaws.com', 'proto': 'http'}},)

AssertionError: Location header should be set "http://ec2-11-22-333-44.compute-1.amazonaws.com/report-404/x/index-v621d8oinbgd13120gmh3.html" != "http://ec2-11-22-
333-44.compute-1.amazonaws.com/report-404/x"
```
i tracked the failures down to the changes in https://github.com/ceph/ceph/pull/15703 - these test cases just need to be updated to match the new semantics

**Comment by yuriw** [comment]
[wip-yuri-testing-2018-03-01-1701](https://trello.com/c/uPxoMU9v/270-wip-yuri-testing-2018-03-01-1701)

**Pull request merged**
