### PR TITLE
osd: simplify past_intervals representation

### PR DESCRIPTION
**Pull request by liewegas**
This is based on Sam's branch, but with many many changes and fixes.  It's now passing the rados suite.  Ready for another review!

### CODE REVIEW

**Comment by liewegas** [comment]
http://pulpito.ceph.com/sage-2017-04-20_18:05:53-rados-wip-past-intervals---basic-smithi/

**Comment by tchaikov** [comment]
@liewegas needs rebase

**Comment by liewegas** [comment]
/a/sage-2017-04-29_22:06:05-rados-wip-sage-testing2---basic-smithi/1082864
<pre>
2017-04-30T00:45:42.066 INFO:tasks.ceph.osd.5.smithi062.stderr:     0> 2017-04-30 00:45:42.031835 7f478f867700 -1 /build/ceph-12.0.1-1773-g230a4d7/src/osd/osd_types.cc: In function 'static bool PastIntervals::check_new_interval(int, int, const std::vector<int>&, const std::vector<int>&, int, int, const std::vector<int>&, const std::vector<int>&, epoch_t, epoch_t, OSDMapRef, OSDMapRef, pg_t, IsPGRecoverablePredicate*, PastIntervals*, std::ostream*)' thread 7f478f867700 time 2017-04-30 00:45:42.029512
2017-04-30T00:45:42.067 INFO:tasks.ceph.osd.5.smithi062.stderr:/build/ceph-12.0.1-1773-g230a4d7/src/osd/osd_types.cc: 3503: FAILED assert(lastmap->get_pools().count(pgid.pool()))
2017-04-30T00:45:42.067 INFO:tasks.ceph.osd.5.smithi062.stderr:
2017-04-30T00:45:42.067 INFO:tasks.ceph.osd.5.smithi062.stderr: ceph version 12.0.1-1773-g230a4d7 (230a4d79ff6ef8a62bdb8f258f92c58bc7496fee)
2017-04-30T00:45:42.067 INFO:tasks.ceph.osd.5.smithi062.stderr: 1: (ceph::__ceph_assert_fail(char const*, char const*, int, char const*)+0x10e) [0x555aadee085e]
2017-04-30T00:45:42.067 INFO:tasks.ceph.osd.5.smithi062.stderr: 2: (PastIntervals::check_new_interval(int, int, std::vector<int, std::allocator<int> > const&, std::vector<int, std::allocator<int> > const&, int, int, std::vector<int, std::allocator<int> > const&, std::vector<int, std::allocator<int> > const&, unsigned int, unsigned int, std::shared_ptr<OSDMap const>, std::shared_ptr<OSDMap const>, pg_t, IsPGRecoverablePredicate*, PastIntervals*, std::ostream*)+0x58f) [0x555aadbd7f6f]
2017-04-30T00:45:42.067 INFO:tasks.ceph.osd.5.smithi062.stderr: 3: (OSD::build_initial_pg_history(spg_t, unsigned int, utime_t, pg_history_t*, PastIntervals*)+0x594) [0x555aad9dd674]
2017-04-30T00:45:42.067 INFO:tasks.ceph.osd.5.smithi062.stderr: 4: (OSD::handle_pg_create(boost::intrusive_ptr<OpRequest>)+0xb24) [0x555aad9e7ff4]
2017-04-30T00:45:42.067 INFO:tasks.ceph.osd.5.smithi062.stderr: 5: (OSD::dispatch_op(boost::intrusive_ptr<OpRequest>)+0x1b1) [0x555aad9e9f91]
2017-04-30T00:45:42.067 INFO:tasks.ceph.osd.5.smithi062.stderr: 6: (OSD::_dispatch(Message*)+0x377) [0x555aad9ea927]
2017-04-30T00:45:42.068 INFO:tasks.ceph.osd.5.smithi062.stderr: 7: (OSD::ms_dispatch(Message*)+0x74) [0x555aad9ead54]
2017-04-30T00:45:42.068 INFO:tasks.ceph.osd.5.smithi062.stderr: 8: (DispatchQueue::entry()+0x78b) [0x555aae0ac5bb]
2017-04-30T00:45:42.068 INFO:tasks.ceph.osd.5.smithi062.stderr: 9: (DispatchQueue::DispatchThread::entry()+0xd) [0x555aadf58f1d]

</pre>

**Comment by liewegas** [comment]
previous failure was due to http://tracker.ceph.com/issues/19814; waiting for that fix to mege.

**Pull request merged**
