### PR TITLE
Revert "mds: align quota.max_bytes to 4MB or 4KB"

### PR DESCRIPTION
**Pull request by vshankar**
Reverts ceph/ceph#46905 -- for testing purpose.

### CODE REVIEW

**Comment by vshankar** [comment]
I ran this through fs suite and none of the failures are quota related. @lxbsz

**Comment by lxbsz** [comment]
> I ran this through fs suite and none of the failures are quota related. @lxbsz

Okay, if it won't break anything we can revert it first.

**Comment by vshankar** [comment]
> > I ran this through fs suite and none of the failures are quota related. @lxbsz
> 
> Okay, if it won't break anything we can revert it first.

https://tracker.ceph.com/issues/56397 isn't backported to any release yet, so, I think its safe to revert.

**Comment by lxbsz** [comment]
> > > I ran this through fs suite and none of the failures are quota related. @lxbsz
> > 
> > 
> > Okay, if it won't break anything we can revert it first.
> 
> https://tracker.ceph.com/issues/56397 isn't backported to any release yet, so, I think its safe to revert.

Sure, I will include this PR again in another PR.

**Review by lxbsz — APPROVED** [review]

**Comment by vshankar** [comment]
Update with signed-off-by tag.

@lxbsz I'm merging this. Please push an updated PR for the same.

**Comment by lxbsz** [comment]
> Update with signed-off-by tag.
> 
> @lxbsz I'm merging this. Please push an updated PR for the same.

Sure @vshankar.

**Comment by vshankar** [comment]
Unrelated jenkins test failures :/

**Comment by vshankar** [comment]
jenkins test api

**Comment by vshankar** [comment]
jenkins test api

**Comment by vshankar** [comment]
This is ready to merge, but I lost the run wiki that I had recorded locally - need to do that again :/

**Comment by vshankar** [comment]
https://pulpito.ceph.com/vshankar-2023-09-11_04:57:08-fs-wip-vshankar-testing-20230908.065909-testing-default-smithi/

**Comment by vshankar** [comment]
https://tracker.ceph.com/projects/cephfs/wiki/Main#13-Sep-2023

**Pull request merged**
