### PR TITLE
doc/rados/configuration: fix typo in mon-lookup-dns

### PR DESCRIPTION
**Pull request by ektich**
Fix an annoying (for me anyway) typo in the title of the mon-lookup-dns file

Signed-off-by: Vanush "Misha" Paturyan <ektich@gmail.com>

### CODE REVIEW

**Comment by tchaikov** [comment]
@ektich  could you add a "`Signed-off-by`" line at the end of your commit message? "git commit -s" will do the trick for you. see https://github.com/ceph/ceph/blob/master/SubmittingPatches.rst#1-sign-your-work

please note, the first comment in the PR is not the same thing as the commit message.

**Comment by ektich** [comment]
@tchaikov yes, I've noticed the Signed-off-by failing the moment I've created this request. Should I create a new branch/PR or just rewrite the commit and force-push it on this branch?

**Comment by tchaikov** [comment]
@ektich please just revise the commit and force-push it to your `ektich-patch-1` branch.

**Comment by tchaikov** [comment]
```
Collecting six>=1.10.0 (from pytest)
  Could not find a version that satisfies the requirement six>=1.10.0 (from pytest) (from versions: )
No matching distribution found for six>=1.10.0 (from pytest)
```
retest this please.

**Pull request merged**
