### PR TITLE
ceph-volume: fix has_bluestore_label() function

### PR DESCRIPTION
**Pull request by guits**
When using vg/lv, this function throws an error like following:

```
 stderr: unable to read label for test_group/data-lv2: (2) No such file or directory
 stderr: 2020-02-04T21:03:32.153+0000 7fe091af4200 -1 bluestore(test_group/data-lv2) _read_bdev_label failed to open test_group/data-lv2: (2) No such file or directory
```

using `self.abspath` fixes this error.

Fixes: https://tracker.ceph.com/issues/43970

Signed-off-by: Guillaume Abrioux <gabrioux@redhat.com>

### CODE REVIEW

**Comment by dsavineau** [comment]
jenkins test ceph-volume tox

**Comment by guits** [comment]
indeed, this error also shows up on an initial osd creation

**Comment by dsavineau** [comment]
jenkins test ceph-volume tox

**Comment by guits** [comment]
> LGTM. Can you please create a tracker ticket for this and add a `Fixes: <tracker url>` line? This will greatly ease our backporting.

Ticket created and commit amended.

> Also squashing the commits wouldn't hurt.

I would keep these commits separated: although it's modifying the same line, it's well two different modifications.

**Comment by leseb** [comment]
> Does that work when running against a raw device too?

I guess it was late when I posted that question, I thought you were modifying the `ceph-bluetstore-tool` command. Nevermind!

**Pull request merged**
