### PR TITLE
fmt: bump up version to 11.0.2

### PR DESCRIPTION
**Pull request by Matan-B**
Move fmt sub module branch to https://github.com/ceph/fmt/commits/wip-fmt-11.0.2/

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Comment by cbodley** [comment]
no objection, but is this something we could reasonably backport all the way to quincy? we appear to have several constraints from fmt, clang, and gcc versions and need to satisfy those on all releases

for example, the crimson builds for shaman using gcc-13 don't appear to have this issue

**Comment by Matan-B** [comment]
> no objection, but is this something we could reasonably backport all the way to quincy? 

Probably not, this will require a too drastic change.

> for example, the crimson builds for shaman using gcc-13 don't appear to have this issue

Are you suggesting that upgrading compilers will be easier?

**Comment by cbodley** [comment]
> > for example, the crimson builds for shaman using gcc-13 don't appear to have this issue
> 
> Are you suggesting that upgrading compilers will be easier?

@Matan-B hehe, i wouldn't say "easy" based on the mess i've made with https://github.com/ceph/ceph/pull/58384

in the short term, i think the easiest way to fix 'make check' is to uninstall gcc-12 stuff from all of the ubuntu nodes in jenkins

i just don't want to end up stuck there, or we'll never get past gcc-11. i've been trying to raise awareness about this in https://lists.ceph.io/hyperkitty/list/dev@ceph.io/thread/LNMXUFBMFXHIXX334DYOMW5K4PYN4YIM/, but maybe that needs to wait until we've shipped squid. we might just wait until the builders upgrade to ubuntu 24.04 (https://tracker.ceph.com/issues/66914) and go straight to gcc-13

**Comment by Svelar** [comment]
> in the short term, i think the easiest way to fix 'make check' is to uninstall gcc-12 stuff from all of the ubuntu nodes in jenkins
> i just don't want to end up stuck there, or we'll never get past gcc-11. i've been trying to raise awareness about this in https://lists.ceph.io/hyperkitty/list/dev@ceph.io/thread/LNMXUFBMFXHIXX334DYOMW5K4PYN4YIM/, but maybe that needs to wait until we've shipped squid. we might just wait until the builders upgrade to ubuntu 24.04 (https://tracker.ceph.com/issues/66914) and go straight to gcc-13

The point is libstd++-12-dev, I tried to uninstall it on ARM CI servers, works fine. For 'make check', we use clang first, not gcc.

**Comment by Matan-B** [comment]
Will work on the adjustments in this PR - https://github.com/ceph/ceph/pull/58990

**Comment by Matan-B** [comment]
Closing for https://github.com/ceph/ceph/pull/58990

**Pull request closed without merging**
