### PR TITLE
rgw: make sure min objs per shard is appropriate

### PR DESCRIPTION
**Pull request by ivancich**
The admin has control over the rgw_max_objs_per_shard configuration option. Currently the minimum objects per shard is hard-coded. If that max is lowered then we need to be certain that the minimum is an appropriate value, certainly less than the max.

Fixes: https://tracker.ceph.com/issues/66757

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Review by cbodley — COMMENTED** [review]
looks good but there's an unrelated change to the s3select submodule
> Unmodified Submodules — Approval needed: modified submodules found

**Comment by ivancich** [comment]
Fixed the submodule issue, @cbodley .

**Review by cbodley — APPROVED** [review]

**Comment by ivancich** [comment]
ceph check api

**Comment by ivancich** [comment]
jenkins test api

**Comment by ivancich** [comment]
jenkins test make check

**Comment by cbodley** [comment]
jenkins test api

**Comment by cbodley** [comment]
from https://jenkins.ceph.com/job/ceph-api/77353
> ninja: build stopped: interrupted by user.
Terminated

**Comment by cbodley** [comment]
jenkins test api

**Comment by ivancich** [comment]
Teuthology results, no regressions:
* https://pulpito.ceph.com/ivancich-2024-07-16_16:20:28-rgw-wip-eric-testing-1-distro-default-smithi/
* https://pulpito.ceph.com/ivancich-2024-07-16_16:20:51-rgw-wip-eric-testing-1-distro-default-smithi/

**Pull request merged**
