### PR TITLE
mimic: core: crc cache should be invalidated when posting preallocated rx buffers

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/38437

### CODE REVIEW

**Comment by smithfarm** [comment]
I'll wait for review since this backport omits the test.

**Comment by smithfarm** [comment]
@idryomov Thanks - the rename was done by 3730d10623650ce8569be96b28cbba599a9a0db6 which is not being backported to mimic, but I'll manually cherry-pick the test mods into `src/test/librados/io.cc`

**Comment by smithfarm** [comment]
jenkins test docs

**Comment by yuriw** [comment]
[wip-yuri3-testing-2019-09-30-1547](https://trello.com/c/YpGnOoKt/699-wip-yuri3-testing-2019-09-30-1547)

**Pull request merged**
