### PR TITLE
luminous: rocksdb: add more compression algorithms for Luminous.

### PR DESCRIPTION
**Pull request by rzarzynski**
http://tracker.ceph.com/issues/22534

### CODE REVIEW

**Comment by tchaikov** [comment]
```
Unable to checkout '7f810128d76802b9314cabbec7e4b6cbebc9d4e4' in submodule path 'src/rocksdb'
```

@rzarzynski i think you might want to use https://github.com/ceph/rocksdb/commit/8dc2209dc19821d94d6ae87844a0b0bf70376a69 instead ?

**Comment by rzarzynski** [comment]
Oops, thanks for pointing this out!

```
diff --git a/src/rocksdb b/src/rocksdb
index b181f17..8dc2209 160000
--- a/src/rocksdb
+++ b/src/rocksdb
@@ -1 +1 @@
-Subproject commit b181f1714a4baecaf7dff4c8417b20f5e6a41585
+Subproject commit 8dc2209dc19821d94d6ae87844a0b0bf70376a69
```

**Comment by rzarzynski** [comment]
Just for the archives: https://gist.github.com/rzarzynski/bfaab8099f3e9cd7461a6238783ca185.

**Comment by tchaikov** [comment]
@smithfarm hey Nathan, can we include this change in next luminous qa batch? as it address a critical issue which prevents users from upgrading from moving their backend storage from leveldb to rocksdb. because in jewel, leveldb always has snappy enabled. without this change, rocksdb will fail to decompress the compressed chunk by leveldb if user chooses to migrate to rocksdb using ceph-kvstore-tool.

**Comment by rzarzynski** [comment]
@tchaikov: I believe the importance of this patch is a bit lower as the Snappy compressor is already available in `luminous`. The patch brings additional ones like `zlib` to match with `master`.

**Comment by liewegas** [comment]
i'm not sure we want users using anything other htan snappy (if that, even!)

**Pull request closed without merging**
