### PR TITLE
do_cmake.sh: enable amqp and rdma for EL8

### PR DESCRIPTION
**Pull request by tchaikov**
the PowerTools repo now has the related dependencies, so let's enable
them.

Signed-off-by: Kefu Chai <kchai@redhat.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`

</details>

### CODE REVIEW

**Comment by tchaikov** [comment]
@yuvalif ping?

**Comment by yuvalif** [comment]
> @yuvalif ping?



> @yuvalif ping?

@kefu did you manage to build that on centos8? still running into issues there.

**Comment by tchaikov** [comment]
@yuvalif please define "issues". it builds on CentOS8. see https://shaman.ceph.com/builds/ceph/wip-centos8-kefu/536c5232c35a6e627831faa1b0e893f14fc671a6/

**Comment by yuvalif** [comment]
> @yuvalif please define "issues". it builds on CentOS8. see https://shaman.ceph.com/builds/ceph/wip-centos8-kefu/536c5232c35a6e627831faa1b0e893f14fc671a6/ and https://github.com/ceph/ceph-ci/commits/wip-centos8-kefu

I'm trying to do a containerized build on centos8 (dont have a centos8 machine). ran into several issues, fixed most of them (adding stuff to the base image, enabling repos etc.), currently, my issue is:
```
CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find Python (missing: Python_EXECUTABLE Python_LIBRARY
  Python_INCLUDE_DIR Interpreter Development) (Required is exact version
  "2.7")
```
but anyway, if you have a passing build then the problem is probably with my setup.

**Comment by tchaikov** [comment]
@yuvalif i think you might need to install `python2-devel`

**Comment by tconrado** [comment]
@tchaikov 

I saw some commits to RDMA to the Octopus, but one thing that is not clear to me: do we need to build to be use RDMA? or the current master build is capable?

**Comment by tchaikov** [comment]
> @tchaikov
> 
> I saw some commits to RDMA to the Octopus, but one thing that is not clear to me: do we need to build to be use RDMA? or the current master build is capable?

please send this question to ceph-devel and copy me.

**Pull request merged**
