### PR TITLE
script: fix a bug in naming the source branch in ceph-debug-docker.sh

### PR DESCRIPTION
**Pull request by ronen-fr**
'source' mixed with 'branch'

Signed-off-by: Ronen Friedman <rfriedma@redhat.com>

### CODE REVIEW

**Comment by ronen-fr** [comment]
(not that it actually worked with the change, but at least we got the branch right...

built image ronen-fr:ceph-ci-wip-ronenf-scrub-sch-bug1-latest-ubuntu-focal
docker run -ti -v /ceph:/ceph:ro -v /cephfs:/cephfs:ro -v /teuthology:/teuthology:ro ronen-fr:ceph-ci-wip-ronenf-scrub-sch-bug1-latest-ubuntu-focal
Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
Error: statfs /teuthology: no such file or directory
)

**Review by tchaikov — APPROVED** [review]

**Review by badone — APPROVED** [review]
Looks reasonable to me.

**Comment by badone** [comment]
> Error: statfs /teuthology: no such file or directory

It's expecting a teuthology directory in the root so maybe we should make that path configurable?

**Comment by ronen-fr** [comment]
> It's expecting a teuthology directory in the root so maybe we should make that path configurable?
@badone:
What is expected to be there?

BTW - the full listing is in https://gist.github.com/ronen-fr/bb099bac72ebb1bad310c2759b543756

(as for this PR - I'll merge it shortly)

**Comment by badone** [comment]
> > It's expecting a teuthology directory in the root so maybe we should make that path configurable?
> 
> @badone:
> What is expected to be there?

I suspect the teuthology source. It also expects /ceph and /cephfs but they can all be empty AFAICT.

**Pull request merged**
