### PR TITLE
osd,mon: remove pg_pool_t::removed_snaps

### PR DESCRIPTION
**Pull request by liewegas**
Eliminate the pg_pool_t::removed_snaps member (which can grow unbounded over time)

The first half of the patches (aka wip-sloppy-snaps) remove any dependency on pg_pool_t::removed_snaps and SnapSet::snaps, and generally relax the behavior of the client and OSD so that they are less picky about the SnapContext and creating clones.

The second half of the series adds infrastructure for the OSD to mirror the canonical set of purged_snaps locally and to scrub the SnapMapper metadata against that set and clean up any "leaked" clones.

- [x] mon: try to keep (start -> end) key/value pairs in simplest form (merge adjacent on insert; and maybe clean-up later?)
- [ ] mon: compress adjacent removed_snap and purged_snap extents on mon (from pre-octopus mons)
- [x] mon: record per-epoch purged_snaps
- [x] mon: populate pre-octopus purged_snaps (for upgrade path)
- [x] osd: slurp down historical purged_snaps data
- [x] osd: record past purged_snaps on inc maps
- [x] osd: periodic scrub that reconciles purged_snaps with snapmapper
- [x] osd: scrub: if snapmapper has a purged snap, queue a trim on the appropriate pg (based on the object in question)
- [x] osd: scrub: ensure the cleanup trim does not then report (re)purged pg as purged to mgr (mgr/mon already consider the snapid purged)
- [x] consider removing the gap info from MOSDMap messages (probably not worth the complexity?)
- [x] osd: fix key order problem (snapmapper vs purgd_snaps keys)
- [x] osd: simplify/remove is_removed_snap() and other pg_pool_t::removed_snaps dependencies
- [x] mon: clear removed_snaps once all osds are octopus
- [x] osd: automatically trigger scrub_purged_snaps on a schedule?
- [ ] osd: make scrub_purged_snaps more efficient and/or cooperative, pausable, etc.

### CODE REVIEW

**Comment by liewegas** [comment]
My big run turned up a few failures that look unrelated.. still digging through those, but in the meantime this is ready for review!

**Comment by athanatos** [comment]
The main difference in behavior I see is that get_ssc_as_of won't return snaps for which the object didn't exist.  My reading of start_flush is that it won't change the outcome delete/copy_from sequence and should be ok.

LGTM.

**Comment by liewegas** [comment]
@athanatos added a few patches to automatically scrub every deep_scrub_interval (with some randomization on the interval).

**Comment by xiexingguo** [comment]
need to update crimson's send_beacon too since you are changing MOSDBeacon

**Pull request merged**
