### PR TITLE
rgw: fix user.rgw.user-policy attr remove by modify user

### PR DESCRIPTION
**Pull request by Inode1**
Guys, thank you  for your project, would you mind taking a look?
Fix https://tracker.ceph.com/issues/48761 user policy attribute deletion when changing user info. 

https://tracker.ceph.com/issues/63134

Signed-off-by: ivan <i.makarychev@tinkoff.ru>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by Inode1** [comment]
@cbodley, Hello could you check it out, please?

**Comment by Inode1** [comment]
hi @pritha-srivastava , would you mind help to review this pr?(

**Comment by dang** [comment]
Can we split this into two PRs?  The user attributes is a separate issue from the subuser, and requires different discussions.

**Comment by cbodley** [comment]
regarding the policy part: (cc @pritha-srivastava @adamemerson @mattbenjamin @mmgaggle)

in general, i'm wary about hacking these swift tenant/subuser concepts into s3 and iam. especially in places like iam ARNs where the parsing of tenant or subuser names could be ambiguous. but in this case, it's adding a separate condition for subuser which doesn't require special parsing 👍

so my only objection is that we're calling this condition `s3:subuser` rather than `rgw:subuser`. i think that would help make it clear which parts of the policy are general, and which rely on rgw extensions

ultimately, i'd prefer to get iam accounts working so we don't have to rely on this imprecise mapping from iam account/user to rgw user/subuser. development there has been slow, but i'm hoping we can prioritize initial account support for squid

**Comment by mmgaggle** [comment]
@cbodley I kind of feel like the direction we want to go is where the rgw user becomes analogous to a "root user" in aws parlance. Root users are then able create/manage iam users via the iam apis. In aws, there can be associations between root users, where one becomes another's OU (organizational unit). Service control policies can be created at the top level, and cascade down. This is far more flexible than a tenant/subuser model, and teant/subuser can then be modeled by having N root users with a common OU, or having a single root user with N IAM users.

**Comment by Inode1** [comment]
> Can we split this into two PRs? The user attributes is a separate issue from the subuser, and requires different discussions.

**Comment by Inode1** [comment]
> regarding the policy part: (cc @pritha-srivastava @adamemerson @mattbenjamin @mmgaggle)
> 
> in general, i'm wary about hacking these swift tenant/subuser concepts into s3 and iam. especially in places like iam ARNs where the parsing of tenant or subuser names could be ambiguous. but in this case, it's adding a separate condition for subuser which doesn't require special parsing 👍
> 
> so my only objection is that we're calling this condition `s3:subuser` rather than `rgw:subuser`. i think that would help make it clear which parts of the policy are general, and which rely on rgw extensions
> 
> ultimately, i'd prefer to get iam accounts working so we don't have to rely on this imprecise mapping from iam account/user to rgw user/subuser. development there has been slow, but i'm hoping we can prioritize initial account support for squid

Thank you, I take into consideration your comments about field naming and created a new pr https://github.com/ceph/ceph/pull/53997, would you mind taking a look at it?

**Comment by cbodley** [comment]
> @cbodley I kind of feel like the direction we want to go is where the rgw user becomes analogous to a "root user" in aws parlance. Root users are then able create/manage iam users via the iam apis. In aws, there can be associations between root users, where one becomes another's OU (organizational unit). Service control policies can be created at the top level, and cascade down. This is far more flexible than a tenant/subuser model, and tenant/subuser can then be modeled by having N root users with a common OU, or having a single root user with N IAM users.

thanks @mmgaggle. the concept of a 'root user' was part of the account design, and by default would be the only user with full access to the iam apis for that account. but when you say "the rgw user becomes analogous to a root user", does that imply that s3 users created by the root would act like subusers instead?

the plan was to represent them as normal rgw users, just with an associated 'account id'. the 'root user' would also be a normal rgw user, just with a 'root' flag similar to the existing 'admin' and 'system' flags. in iam policy, the Principal string could refer to either using 'account-id:root' or 'account-id:user/userid'

if there's a need for one user to inherit policy from another, we could add that linkage to RGWUserInfo as well. does that sound sensible?

**Comment by Inode1** [comment]
@cbodley, could you give me a hint. What should I do to backport this pr to quincy release? According to this https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst I need to create beckport pr or it will be done automatically?

**Comment by cbodley** [comment]
> @cbodley, could you give me a hint. What should I do to backport this pr to quincy release? According to this https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst I need to create beckport pr or it will be done automatically?

@Inode1 i've tagged https://tracker.ceph.com/issues/63134 for backports to "quincy reef". once this pr gets through qa and merges, we'll use the src/script/ceph-backport.sh script to prepare those

**Comment by ivancich** [comment]
Teuthology results -- no regressions:
* https://pulpito.ceph.com/ivancich-2023-10-19_04:33:51-rgw-wip-eric-testing-1-distro-default-smithi/
* https://pulpito.ceph.com/ivancich-2023-10-19_14:26:37-rgw-wip-eric-testing-1-distro-default-smithi/

**Comment by Inode1** [comment]
> > @cbodley, could you give me a hint. What should I do to backport this pr to quincy release? According to this https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst I need to create beckport pr or it will be done automatically?
> 
> @Inode1 i've tagged https://tracker.ceph.com/issues/63134 for backports to "quincy reef". once this pr gets through qa and merges, we'll use the src/script/ceph-backport.sh script to prepare those

@cbodley, thanks . Could you check this https://github.com/ceph/ceph/pull/53997#issuecomment-1765663779 out?) plz

**Pull request merged**
