### PR TITLE
Oprequest markevent

### PR DESCRIPTION
**Pull request by majianpeng**

### CODE REVIEW

**Comment by gregsfortytwo** [comment]
@athanatos, are you okay with losing the waiting_for_osdmap marker on the ops? It *is* pretty redundant, but only optionally outputting it means the ops don't all hit basically the same event markers anymore.

**Comment by hjwsm1989** [comment]
looks good,even when we want to get the op's event state when it's stucked

**Comment by liewegas** [comment]
looks good to me!

**Comment by liewegas** [comment]
@gregsfortytwo the waiting_for_osdmap event always bothered me anyway (since it wasn't actually waiting for the osdmap)

**Pull request merged**
