### PR TITLE
jewel: osd: objecter sends out of sync with pg epochs for proxied ops

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/23076

### CODE REVIEW

**Comment by smithfarm** [comment]
@tchaikov Jewel make check experience seems better now, but I'm still seeing occasional `test_pidfile.sh` failures - for example just now in this PR. I'll refrain from triggering retest in case you want to take a look.

**Comment by dzafman** [comment]
@smithfarm @tchaikov The test_pidfile.sh test has been a issue for a long time.  The test is disabled in master.  Spent a lot of time unsuccessfully trying to get it to work reliably.

**Comment by smithfarm** [comment]
@dzafman We should disable it in jewel, too, then - seems to be doing more harm than good?

**Comment by dzafman** [comment]
@smithfarm Sure, disable it.

**Comment by smithfarm** [comment]
OK, disabling via https://github.com/ceph/ceph/pull/20520

**Comment by smithfarm** [comment]
retest this please

**Comment by tchaikov** [comment]
ack and thanks, @smithfarm and @dzafman .

**Comment by smithfarm** [comment]
retest this please

**Comment by smithfarm** [comment]
CI logs are disappearing really fast - they used to stick around for at least 2 days, now less than one day??

Jenkins, re-test this please

**Comment by smithfarm** [comment]
http://tracker.ceph.com/issues/23105 strikes again

Jenkins, re-test this please

**Comment by smithfarm** [comment]
This PR was included in the rados suite at http://tracker.ceph.com/issues/21742#note-20

It does not prevent the assert described at http://tracker.ceph.com/issues/22064

**Comment by dzafman** [comment]
@smithfarm @jdurgin I don't see any relationship between those changes and the crash.

**Comment by smithfarm** [comment]
Update: I reproduced the crash on the tip of the jewel branch.

**Comment by smithfarm** [comment]
This PR passed a rados suite at http://tracker.ceph.com/issues/21742#note-20 (with some failed jobs, all of which attributable to known bugs)

**Pull request merged**
