### PR TITLE
luminous: osd: build_initial_pg_history doesn't update up/acting/etc 

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/21236

### CODE REVIEW

**Comment by theanalyst** [comment]
passed a rados run http://tracker.ceph.com/issues/21296#note-3

**Comment by yuriw** [comment]
ready fir merge
http://pulpito.ceph.com/yuriw-2017-09-07_19:30:56-rados-wip-yuri-testing4-2017-09-07-1811-distro-basic-smithi/

http://pulpito.ceph.com/yuriw-2017-09-07_22:14:44-rados-wip-yuri-testing4-2017-09-07-1811-distro-basic-smithi/

**Comment by liewegas** [comment]
also need 4ae053439e526fab0451d1502576dce89eb6b44f

**Comment by liewegas** [comment]
see https://github.com/ceph/ceph/pull/17622

**Pull request merged**
