### PR TITLE
crimson: clean up and refactor asok

### PR DESCRIPTION
**Pull request by tchaikov**
## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by tchaikov** [comment]
> The most important design change you are introducing here is returning to
> hook-by-hook registration vs. "per-server" block registration. My original
> thinking was:
> 
> Pros (of hook-by-hook):
> 
> * the code is somewhat simplified
> 
> Cons:
> 
> * slower registration and deregistration ((a) indeed currently only at startup & shutdown  

i think we probably need to value the simplicity over performance when it comes to the non-critical path. in this change i remove replace 689 LOC with 366 LOC. and also terminate the the asok task when stopping so we can do faster shutdown.

> (b) more important as we complete the set of asok commands. Only  a minimal subset is coded for now);

i don't follow this. a minimal subset of what?

> * no copying during registration; and the APIs description table is compile-time created.

not quite true. if you add a break point in the `std::vector<AsokServiceDef>`. it is constructed when this method is called for the first time as per C++ standard requires.

> * deregistration is especially hurmed:
>   -- one might add an API registration without deregistering it. This may result in
>       a crash if the left-behind hook is used. 

what's the use case of this feature?

>   -- removal requires string search (which I try to avoid if possible); 

i assume we don't remove hooks once it gets added.

>   -- no check is performed whether the removed API was indeed registered by the 
>     de-registering object. A possible bug source in the future.

ditto

>    -- locks are held for longer

personally, i don't think it matters.

> 
> (and one more note on the "pros" side: I was designing for multiple servers registering
> and de-registering their APIs. This is what I saw in the logs, as in the legacy code
> that's what happens in "vstart". That's probably not the case for the Crimson OSD.)

i'd say it's over-engineering. if we were designing mgr which hosts multiple plugins and each of them could implement its own set of commands, then we do need to consider this.

> 
> Another change is the removal of the separation of the OsdAdmin interface from
> the implementation. I usually prefer such separation: easier to reason with when
> debugging or refactoring, and faster to compile.

how about exposing functions like
```c++
unique_ptr<AdminSocketHook> make_config_set_hook();
```

or something like
```c++
template<typename Func> with_hooks(Func&& func);
```

> 
> All in all - both issues are matters of style and taste. I don't see anything wrong with
> your changes.

a bug is also fixed.

**Comment by tchaikov** [comment]
jenkins test crimson perf

**Comment by ronen-fr** [comment]
> not quite true. if you add a break point in the `std::vector<AsokServiceDef>`. it is constructed when this method is called for the first time as per C++ standard requires.

Indeed. Wrong phrasing on my part

**Comment by ronen-fr** [comment]
> > * deregistration is especially hurmed:
> >   -- one might add an API registration without deregistering it. This may result in
> >       a crash if the left-behind hook is used.
> 
> what's the use case of this feature?

I wasn't clear. Not a feature. Just a possible source of bugs in the future (adding without removing new APIs)

**Comment by ronen-fr** [comment]
> how about exposing functions like
> 
> ```c++
> unique_ptr<AdminSocketHook> make_config_set_hook();
> ```
> 
> or something like
> 
> ```c++
> template<typename Func> with_hooks(Func&& func);
> ```

Interesting. Need to think about it.

**Comment by tchaikov** [comment]
> > how about exposing functions like
> > ```c++
> > unique_ptr<AdminSocketHook> make_config_set_hook();
> > ```
> > 
> > 
> > or something like
> > ```c++
> > template<typename Func> with_hooks(Func&& func);
> > ```
> 
> Interesting. Need to think about it.

done.

**Comment by tchaikov** [comment]
jenkins test crimson perf

**Pull request merged**
