### PR TITLE
common: Remove redundant includes - 3

### PR DESCRIPTION
**Pull request by joscollin**
Fixes: http://tracker.ceph.com/issues/19883 (Partially)

Signed-off-by: Jos Collin <jcollin@redhat.com>

### CODE REVIEW

**Comment by liewegas** [comment]
http://pulpito.ceph.com/sage-2017-05-23_06:26:57-rados-wip-sage-testing---basic-smithi/

**Comment by joscollin** [comment]
@wjwithagen : Sorry to hear that it breaks in FreeBSD. I think the best way to optimize the includes is to proceed fixing them in FreeBSD too.

@liewegas  @tchaikov : While doing these series of PRs, which was initiated by @badone,  I was careful not to remove the includes under `#ifdef` s and other suspicious ones, so that I can avoid problem that may occur in other platforms. I have tested these fixes in my system, which is `Fedora/Rawhide x86_64`. And I was expecting fixes when people test in other platforms too.

**Comment by joscollin** [comment]
@liewegas @wjwithagen 

>    Standard inlcudes
>    local includes.
> Same here....

The order of the includes was not strictly followed in many files. I have found instances where it starts with Standard Includes, then comes local includes and then Standard Includes again. So it was confusing. However I have put an effort to group them together.

**Comment by badone** [comment]
@wjwithagen The question I would have is, out of the hundreds of header changes in these PRs specifically how many affected your FreeBSD build and can you tell us which ones?

**Pull request merged**
