### PR TITLE
DNM: jewel: Delete image when a resync is requested

### PR DESCRIPTION
**Pull request by dachary**
http://tracker.ceph.com/issues/16513

### CODE REVIEW

**Comment by dachary** [comment]
@dillaman does this backport look good to merge ? It passed the rbd suite http://tracker.ceph.com/issues/16344#note-11 (except for two failures that seem unrelated http://tracker.ceph.com/issues/16922 and http://tracker.ceph.com/issues/16921)

**Comment by dillaman** [comment]
@dachary I think we will want to ensure this and http://tracker.ceph.com/issues/16513 merge together since they are inter-related. Otherwise, lgtm

**Comment by dachary** [comment]
on hold while https://github.com/ceph/ceph/pull/10678 is being processed

**Comment by dachary** [comment]
Replaced by https://github.com/ceph/ceph/pull/10678

**Pull request closed without merging**
