### PR TITLE
Do not duplicate query-string in ops-log

### PR DESCRIPTION
**Pull request by mattbenjamin**
## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by mattbenjamin** [comment]
Obviously, I don' t intend to leave the ifdef in place here, but this makes it easier to read.  From what can tell (and inspect at runtime) the constructed QUERY_STRING property is always a subset of REQUEST_URI--so this always duplicates the query string portion of the uri we send to ops-log.  I see this behavior on ceph/main, and also going back to our downstream rhcs-5.1+.

I suspect that RGW's REQUEST_URI has always included the query string--but, Apache (and I assume NCSA, from which all web servers inherit REQUEST_URI) documentation states that it shouldn't:
"EQUEST_URI
	The path component of the requested URI, such as "/index.html". This notably excludes the query string which is available as its own variable named QUERY_STRING."
https://httpd.apache.org/docs/2.4/mod/mod_rewrite.html

That said, the alternative change to remove query-string from REQUEST_URI, seems unsafe (it would be an unexpected change affecting several files), and there doesn't seem to be a strong motivation to do it?

**Comment by cbodley** [comment]
the frontend also records a `SCRIPT_URI` that strips off the query string:
https://github.com/ceph/ceph/blob/370e0ed/src/rgw/rgw_asio_client.cc#L76-L84

in the ops log, we might present that as the `REQUEST_URI` instead?

**Comment by cbodley** [comment]
> That said, the alternative change to remove query-string from REQUEST_URI, seems unsafe (it would be an unexpected change affecting quite a lot of code paths in several files), and there doesn't seem to be a strong motivation to do it?

i'm not a fan of `RGWEnv`'s `map<string, string>` for this stuff, and i don't think it's useful for rgw frontends to translate all of this request info into apache terms. i assume that was all just a relic of the fcgi frontend

i'd love to see this cleaned up, possibly as part of [task 57646: stop mangling request header names](https://tracker.ceph.com/issues/57646)

the beast frontend parses directly into a [beast::http::request_header](https://www.boost.org/doc/libs/1_79_0/libs/beast/doc/html/beast/ref/boost__beast__http__request_header.html), then `ClientIO::init_env()` copies everything from that into `RGWEnv`. we might think about exposing a beast type directly to avoid all of this copying and translation. some of the `RGWEnv` variables like SERVER_PORT/SERVER_PORT_SECURE/REMOTE_ADDR come from the tcp socket, not the parsed http header, but we could store those variables separately in `req_state` or `req_info`

**Comment by mattbenjamin** [comment]
@cbodley ok, for now, I'll clean up this PR, adding tracker and removing #ifdef, without changing the logic.  I agree with your take on Apache/NCSA  notations, won't mess with it.

**Review by cbodley — APPROVED** [review]

**Comment by mattbenjamin** [comment]
https://pulpito.ceph.com/mbenjamin-2023-03-14_14:47:25-rgw-wip-dedup-opsqs-distro-default-smithi/

**Comment by cbodley** [comment]
in the meantime, i tried scheduling a rerun of those failed tests with an updated suite-branch, where `rgw_torrent_flag=1` should cause it to populate the torrent info. maybe that succeeds?

https://pulpito.ceph.com/cbodley-2023-03-14_21:07:20-rgw-wip-dedup-opsqs-distro-default-smithi/

**Comment by mattbenjamin** [comment]
> apologies @mattbenjamin, i see that the merge of [ceph/s3-tests#495](https://github.com/ceph/s3-tests/pull/495) caused s3test failures in that run. can you please rebase to pick up #50168?
> 
> i thought that new test case would succeed regardless, but the old torrent code returned `-EINVAL` instead of `-ENOENT` if there wasn't a torrent stored for the object

sure, thanks for reading the results

Matt

**Comment by cbodley** [comment]
the rerun passed in https://pulpito.ceph.com/cbodley-2023-03-16_16:38:14-rgw-wip-dedup-opsqs-distro-default-smithi/

**Pull request merged**
