### PR TITLE
[DNM] librbd: experimenting with live image substitution

### PR DESCRIPTION
**Pull request by trociny**

### CODE REVIEW

**Comment by dillaman** [comment]
@trociny I would recommend putting the API within ```librbd::Operations``` instead of ```ImageCtx``` since the latter is a tangled mess of metadata. It would also be nice if the op tracking could be integrated w/ the new ```librbd::ExclusiveLock::start_op``` so that there is only a single way to track in-flight (non-IO) ops.

**Comment by trociny** [comment]
@dillaman I am not sure I follow your idea about integrating it with `librbd::ExclusiveLock::start_op`. It looks like the purposes are different. `librbd::ExclusiveLock::start_op` is to make sure the exlusive lock is not lost during an operation, while in my case I need to make sure API operations are not running when I manipulate with internal state. I need it for IO ops too. And an image may not have exclusive lock feature (well, actually I think we can always temporary add it if needed).

**Comment by dillaman** [comment]
@trociny well, we already track IO through ```ImageRequestWQ``` and can block them (with or without exclusive lock). The new tracker I added to ```ExclusiveLock``` is currently used for preventing the release of the exclusive lock, but nothing would stop it from being generically moved to a lower level in ```Operations``` but the exclusive lock pre-release step would still temporarily block ops.

**Comment by trociny** [comment]
@dillaman Thanks. I was thinking about `ImageRequestWQ`. There is a difference that complicates things. Instead of returning EROFS when blocked I need to delay operation until it is unblocked. The same is with `librbd::ExclusiveLock::start_op`. I will look if I can generalize this though.

**Comment by trociny** [comment]
Another drawback when using ImageRequestWQ to block API, is that now when I am blocking it in librbd.cc, only ImageCtx and blocker pointers are not allowed to change, and I can change everything else after blocking API operations and ensuring there is no ops in flight. When blocking in ImageRequestWQ I must be more careful what structures I can change.

**Comment by trociny** [comment]
@dillaman I just would like to clarify some things before starting to work on the next iteration.
My initial approach was to track API at the earliest stage, i.e. add ictx->start_api_op (may be ictx->operations->start_api_op) just on an API function enter and ictx->finish_api_op on the funtion exit.

This approach allows me to easily block API and do with ictx anything I want (ensuring only that ImageCtx and blocker pointers are not changed). I expect this in #15831, when I "reload" ImageCtx. This approach has drawbacks though, e.g. we need to add start/finish_api_op to every API function, it might add some overhead.

Another approach as I understand would be to track this lower, somewhere we already track exclusive lock. But then I would need to be very careful when "reloading" ImageCtx and at that moment I don't know if it is doable at all.

What  approach actually would you like I tried?

**Comment by dillaman** [comment]
@trociny I don't mind the explicit start/finish calls for each API op -- they really aren't a concern for high performance.

**Comment by dillaman** [comment]
Closing to PR #15831

**Pull request closed without merging**
