### PR TITLE
doc/rados/operations: Add missing required parameters to stretch-mode CRUSH rule example

### PR DESCRIPTION
**Pull request by elacunza**
Rule example is missing min_size and max_size, both are required.

### CODE REVIEW

**Comment by neha-ojha** [comment]
@elacunza could you please sign your commit using the instructions provided in https://github.com/ceph/ceph/blob/master/SubmittingPatches.rst#sign-your-work

**Review by anthonyeleven — CHANGES_REQUESTED** [review]
Looks okay from a docs perspective in form; as Neha commented I think it's best for Greg to validate it technically

**Review by gregsfortytwo — APPROVED** [review]
Whoops — looks good, thanks!

**Review by anthonyeleven — APPROVED** [review]

**Review by anthonyeleven — CHANGES_REQUESTED** [review]
Please adjust the PR and commit messages as described by the document Neha linked above:

* CR and commit titles something like
`doc/rados/operations: Add missing required parameters to stretch-mode CRUSH rule example`
* `Signed-off-by`

**Comment by elacunza** [comment]
Sorry, I did a quick edit on github and realized about those requirements too late. Hope it's all good now, I don't want to waste your time with such a tiny doc-fix :)

**Comment by anthonyeleven** [comment]
> Sorry, I did a quick edit on github and realized about those requirements too late. Hope it's all good now, I don't want to waste your time with such a tiny doc-fix :)

No problem at all.  I've been through it myself, so I endeavor to help others ramp up.  Improving docs and especially correcting errors is never a waste of time, especially when it helps ensure that others are less likely to be tripped up in the future.

**Review by anthonyeleven — APPROVED** [review]

**Pull request merged**
