### PR TITLE
msg/async: fix a deadlock on Processor::start

### PR DESCRIPTION
**Pull request by majianpeng**
suppose a client do the following:
      main thread			async-work
  Messenger::create
  msgr->start()
  msgr->connect_to_osd
  msgr->add_dispatch_header
        msgr->ready
				  ProtocolV1::handle_server_banner_and_identify
				    msgr->learned_addr
				        msgr->lock.lock()
        msgr->lock.lock()
           Processor::start
                submit_to(async-work, false)

Main thread get msgr->lock and wait the extern-evetn complete. But
extern-work only complte handle_server_banner_and_identify and then do.
So the deadlock is occur.
For client, Processor::start in a no-op extern events. So skip this
extern-events can avoid deadlock.

Signed-off-by: Jianpeng Ma <jianpeng.ma@intel.com>

- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by majianpeng** [comment]
@liewegas . In fact, i don't know why in AsyncMessenger::ready protected by lock?  is it avoiding reentry? If we can remove lock in this function. we can remove the root reason.

**Comment by liewegas** [comment]
> @liewegas . In fact, i don't know why in AsyncMessenger::ready protected by lock? is it avoiding reentry? If we can remove lock in this function. we can remove the root reason.

Yeah, I'm not sure we need that lock there.  @yuyuyu101 ?

**Comment by yuyuyu101** [comment]
@majianpeng this is a real case or not?

**Comment by majianpeng** [comment]
@yuyuyu101 . it's a real bug when i did async-msgr performance with fio_ceph_messenger.

**Comment by majianpeng** [comment]
@liewegas @yuyuyu101  how to handle this ?

**Comment by liewegas** [comment]
I would suggest dropping the lock from ``ready()``.. @yuyuyu101 ?

**Comment by yuyuyu101** [comment]
looks ok

**Comment by majianpeng** [comment]
update. I add a new patch which checks listen_sockets to avoid submit a nonsense event.  @liewegas , @yuyuyu101  please review.

**Comment by majianpeng** [comment]
@liewegas . Ping.

**Pull request closed without merging**
