### PR TITLE
os/bluestore: fixup access a destroy cond cause deadlock or undefine behaviors.

### PR DESCRIPTION
**Pull request by Linbing**
bluestore using temp IOContex to call aio_read, and when _do_read complete, IOContext will be reclaim, means that IOContext::cond will be destroy(pthread_cond_destory). when access a destory cond will cause dedalock or undefined behavior. this bug reproduce in bluestore _do_read, as follow desc:
  
1. read thread has call aio_submit, and before she call aio_wait
2. aio_read has  complete, and take num_running to 0
3. io_complete thread  lose the mutex lock, read thread win the mutex lock 
4. read thread found num_running is 0, so read thread will not call aio_wait and return,
5. complete thread got the mutex lock, if IOContext has been reclaim, then acces the IOContext::cond will case deadlock or undefined behaviors. else nothing happened.

Fixes: <https://tracker.ceph.com/issues/37733>
Signed-off-by: linbing <linbing@t2cloud.net>

- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by liewegas** [comment]
Hmm, yeah.  I was probably trying to avoid taking the mutex in the general case, but it looks like that only matters (1) when it is a read and we are using a cond to signal completion, and (2) we have multiple IOs and thus might skip taking the mutex for all but the last IO.  Looks good to me!

Can you open a tracker ticket for this in teh bluestore section, include a description of what the failure symptom looks like (if you know), and add a Fixes: https://tracker.ceph.com/.... line in the commit message?

Thanks!

**Comment by Linbing** [comment]
> Hmm, yeah. I was probably trying to avoid taking the mutex in the general case, but it looks like that only matters (1) when it is a read and we are using a cond to signal completion, and (2) we have multiple IOs and thus might skip taking the mutex for all but the last IO. Looks good to me!
> 
> Can you open a tracker ticket for this in teh bluestore section, include a description of what the failure symptom looks like (if you know), and add a Fixes: https://tracker.ceph.com/.... line in the commit message?
> 
> Thanks!

yeap, see https://tracker.ceph.com/issues/37733

**Comment by tchaikov** [comment]
http://pulpito.ceph.com/kchai-2018-12-23_02:53:27-rados-wip-kefu2-testing-2018-12-22-1102-distro-basic-smithi/

**Comment by Linbing** [comment]
> @Linbing could you update the commit message and push again?

done,thanks

**Comment by tchaikov** [comment]
@liewegas good to merge?

**Comment by tchaikov** [comment]
@liewegas ping?

**Pull request merged**
