### PR TITLE
luminous: build/ops: move ceph-*-tool binaries out of ceph-test subpackage

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/21869

### CODE REVIEW

**Comment by tchaikov** [comment]
need to run it thru at least one upgrade test

**Comment by smithfarm** [comment]
@theanalyst @tchaikov The reason the ceph-disk suite fails on this PR is because that suite tries to install the ceph-test DEB package along with the other ceph DEB packages. This cannot work because ceph-test declares that it breaks all ceph packages with version < 12.2.2 (current version is 12.2.1).

This doesn't happen on master because the master version number has been bumped to 13.0.0.

This is a Catch-22 situation. . . I vaguely recall that there is a workaround for it, perhaps involving installing ceph-test from a special-purpose repo?

**Comment by smithfarm** [comment]
Another possibility would be to drop the breaking commit 76f5055 from this PR and wait until the 12.2.3 cycle to backport it.

**Comment by tchaikov** [comment]
@smithfarm. if we drop 76f5055, how shall we address following problem?

```
dpkg: error processing archive /var/cache/apt/archives/ceph-osd_13.0.0-2201-g6cc0b41-1trusty_amd64.deb (--unpack):
trying to overwrite '/usr/bin/ceph-osdomap-tool', which is also in package ceph-test 10.2.10-14-gcbaddae-1trusty
```

**Comment by smithfarm** [comment]
@tchaikov If we merge this PR after 12.2.2 is released, we should be OK - right?

**Comment by tchaikov** [comment]
@smithfarm yes. i also replied over the ceph-devel mailing list.

**Comment by tchaikov** [comment]
@smithfarm are we ready to merge this into master, since we've tagged 10.2.2?

**Comment by liewegas** [comment]
does this pr need s/12.2.2/12.2.3/?

**Comment by tchaikov** [comment]
agreed , @smithfarm we need to s/12.2.2/12.2.3/. could you help on this? or i can do it tomorrow.

**Comment by liewegas** [comment]
what about using the 'git describe origin/luminous' version right before merge?

**Comment by tchaikov** [comment]
@liewegas then we need to make create `debian/control` from a `debian/control.in`.

**Comment by liewegas** [comment]
I mean updating this PR to have 12.2.2-5-g117e91ef29 (or thereabouts) instead of 12.2.2 or 12.2.3.

**Comment by tchaikov** [comment]
okay. that would work, but looks a little bit weird though.

**Comment by tchaikov** [comment]
added the change proposed by @liewegas , see #19355.

**Comment by tchaikov** [comment]
closing in favor of #19355.

**Pull request closed without merging**
