### PR TITLE
make the all osd/filestore thread pool suicide timeouts separately configurable

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/11700

### CODE REVIEW

**Comment by smithfarm** [comment]
@swamireddy: could you look at this? I am trying to backport http://tracker.ceph.com/issues/11439 to firefly, and have been looking at it for some time, but all I could figure out was that https://github.com/ceph/ceph/commit/3f2946aa9f9b4b432e8c018283503153a2b1eddc (the target commit) depends on https://github.com/ceph/ceph/commit/06845d0bf6d6fbbb9916df818be0aca10b7f8ae0 - I'm pretty confident that my backport of the latter commit is OK, but beyond that . . . ?

**Comment by somnathr** [comment]
@smithfarm: If you back ported the later commit successfully, what Sam's commit is adding is an extra suicide timeout parameter instead of hard coded ti * 10...
Applying Sam's commit after mine should work fine..Is it giving any problem ?

**Comment by smithfarm** [comment]
@somnathr: the backport doesn't pass "make" because ShardedThreadPool is not defined. I'm guessing I will need to cherry-pick https://github.com/ceph/ceph/commit/06845d0bf6d6fbbb9916df818be0aca10b7f8ae0 first.

**Comment by smithfarm** [comment]
@somnathr: that's good news, but unfortunately my backport of your commit was not successful, after all. It needs the ShardedThreadPool, which is defined in src/common/WorkQueue.{cc,h}

Backporting that will be non-trivial, I am afraid.

**Comment by somnathr** [comment]
Yes, we originally decided not to backport these changes to firefly as changes are quite a bit..Also, if you are not back porting ms_fast_dispatch changes (don't have the commit number), this will not give any performance boost..So, IMO, don't back port it..

**Comment by smithfarm** [comment]
@dachary: what do you think? can we drop this backport as somnathr suggests?

**Comment by dachary** [comment]
@smithfarm what @somnathr writes makes sense to me. I guess a confirmation from sam is all you need to kill this backport :-)

**Comment by smithfarm** [comment]
@athanatos: what do you think? can we drop this backport as somnathr suggests? The reason we tried it was because you had marked it for backport in http://tracker.ceph.com/issues/11439#note-3

**Comment by athanatos** [comment]
Closing, we do not want to backport the sharded thread pool changes.

**Pull request closed without merging**
