### PR TITLE
[DNM] Wip librbd ssd cache

### PR DESCRIPTION
**Pull request by zhouyuan**
RBD Persistent Cache Support
===================
This change introduces RBD Persistent Cache which will do SSD caching on client side.
BP tracker here [[link](http://tracker.ceph.com/projects/ceph/wiki/Rbd_-_ordered_crash-consistent_write-back_caching_extension)] 

Key changes
--------------
- A generic write-thru/write-back caching framework 
- Configurable params to enable/disable and sizing the caching.
- JournalStore for appending all updates in order to be crash consistent.
- ImageStore to do block caching on a sparse file.
- MetaStore to hold cache configuration and serialized the cache state.

Design details
------
http://pad.ceph.com/p/rbd_persistent_cache

### CODE REVIEW

**Comment by zhouyuan** [comment]
Still many TODOs but the general framework is there @tsg- @dillaman

**Comment by zhouyuan** [comment]
Hi @dillaman, I find the unittest_rbd_mirror failures are due to the mismatch read/write size in librados - in the ssd caching layer, the read/write granularity is BLOCK_SIZE(4096). It seems I need to check if persistent cache enabled and do some round up when checking on the read/write size. Or simply disable the persistent cache when on rbd mirror tests?

**Comment by dillaman** [comment]
@zhouyuan The rbd-mirror daemon will never want to use this caching (it already disables the in-memory cache). In the short term, you should probably not initialize the ```FileImageCache``` if ```ImageCtx::cache``` is false.

**Comment by zhouyuan** [comment]
retest this please

**Comment by zhouyuan** [comment]
jenkins retest this please

**Comment by dillaman** [comment]
Closing this PR as its been replaced by others (#20375 and #22573)

**Pull request closed without merging**
