### PR TITLE
osd: fix _process handling for pg vs slot race

### PR DESCRIPTION
**Pull request by liewegas**

### CODE REVIEW

**Comment by liewegas** [comment]
/a/sage-2018-04-30_00:12:46-rados-wip-sage3-testing-2018-04-29-1658-distro-basic-smithi/2453627

**Comment by liewegas** [comment]
http://pulpito.ceph.com/sage-2018-05-01_02:09:39-rados-wip-sage3-testing-2018-04-30-1610-distro-basic-smithi/

**Comment by gregsfortytwo** [comment]
I don't think I understand. The commit message says to bail out, but we're retrying in the code, and I don't see a check that will cause it to bail on that retry that wouldn't have been invoked the first time around.

**Comment by liewegas** [comment]
The commit was updated but hte PR description wasn't :)

**Pull request merged**
