### PR TITLE
RGW: Alias ES permissions to permissions.keyword

### PR DESCRIPTION
**Pull request by matthewoliver**
When `rgw_keystone_implicit_tenants = true` and using the Elasticsearch
sync module the search module when searching for `permissions` don't
work for buckets.

With `rgw_keystone_implicit_tenants` enabled buckets are stored as
`PROJECT_ID$BUCKET_NAME`. And when using permissions it splits by the
'$' and treats the bucket name as 2 word.

If we change permissions to permissions.keyword, then it'll be treated
as a single word.

This patch adds and alias for permissions to map to permissions.keyword.

Before the patch:

  $ radosgw-es 'permissions == projectname$bucketname'
  {"query":{"term":{"permissions":"projectname$bucketname"}}}

afterwards:

  $ radosgw-es 'permissions == projectname$bucketname'
  {"query":{"term":{"permissions.keyword":"projectname$bucketname"}}}

Fixes: https://tracker.ceph.com/issues/45607
Signed-off-by: Matthew Oliver <moliver@suse.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by matthewoliver** [comment]
Really need to test this with an ES sync zone setup. So now just need to figure out how to set that up :P

**Comment by cervigni** [comment]
Any chance that this can be followed up / merged / prioritised?

**Comment by theanalyst** [comment]
LGTM, would love to see a test result (even manual)

**Comment by cervigni** [comment]
I'm new to the process. Could you tell me what you need and how to perform the test? I could give it a shot.

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by theanalyst** [comment]
There is documentation on how to setup sync modules here https://docs.ceph.com/en/latest/radosgw/sync-modules/, we just need a multisite cluster with 2 zones, and a running ES node, for a single node testing just using `tools/mstart.sh` to set up 2 vstart clusters and then just making the secondary zone talk to ES is enough

**Comment by cervigni** [comment]
I know about that.
How to get the patch in the build? The documentation for compiling ceph is very outdated.

Could you give me a hand with that or provide a build for ubuntu 18?

Cheers
________________________________

**Comment by mattbenjamin** [comment]
@cbodley what shall we do with this one?

**Comment by cbodley** [comment]
> @cbodley what shall we do with this one?

it's hard, nobody is maintaining this elasticsearch stuff. it looks like there are some test cases in `src/test/rgw/rgw_multi/tests_es.py`, but there's no automated deployment of elasticsearch in teuthology to run those tests. we'd need a volunteer to set up an environment and run the tests. @yehudasa?

**Pull request closed without merging**
