### PR TITLE
mgr/dashboard: Add support for URI encode

### PR DESCRIPTION
**Pull request by tspmelo**
Created a decorator and pipe to help encode special URI components in the
frontend.

Modified the backend request handler to decode all the string args.

fixes: http://tracker.ceph.com/issues/24621

Signed-off-by: Tiago Melo <tmelo@suse.com>

### CODE REVIEW

**Comment by votdev** [comment]
Prettifying the code makes the review really complicated. Could you split this into a separate PR?

**Comment by tspmelo** [comment]
@votdev I have separated the changes in 2 commits.
One just for prettify and the second for the actual code changes.

**Comment by tspmelo** [comment]
Fixed problems with python 3.

**Comment by tspmelo** [comment]
jenkins retest this please

**Pull request merged**
