### PR TITLE
cmake: set CMAKE_BUILD_TYPE to Debug when .git exists

### PR DESCRIPTION
**Pull request by tchaikov**
if CMAKE_BUILD_TYPE is an empty string, we should also set it to Debug.

Signed-off-by: Kefu Chai <kchai@redhat.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Review by ideepika — APPROVED** [review]
nice addition!

**Comment by tchaikov** [comment]
https://shaman.ceph.com/builds/ceph/wip-kefu-testing-2021-08-17-0902/8b5898830ff89e9ef894d372c8802cccce043e9d/

**Comment by batrick** [comment]
@tchaikov the other commits seem extraneous? Is that to fix `make check` failures?

**Comment by tchaikov** [comment]
@batrick yeah, they are not directly related to this "CMAKE_BUILD_TYPE=Debug" change. actually, they should have been included by #42785 . but because i failed to fix `CMAKE_BUILD_TYPE` in 8e0308c860a9265e8438a978e90090ede08bd647, #42785 failed to the job it claimed to implement -- to fail the build if any warning is reported by the compiler.

so yes, they fix "make check" failures. without them, the "CMAKE_BUILD_TYPE=Debug" commit would fail the "make check" run.

**Review by ideepika — APPROVED** [review]
changes looks good standalone!
Can you add a comment with source of make-check failure or any references if this change intends to address them, thanks!

**Comment by tchaikov** [comment]
> changes looks good standalone!
> Can you add a comment with source of make-check failure or any references if this change intends to address them, thanks!

@ideepika could you be more specific? which "make check failure" you are referencing?

**Comment by ideepika** [comment]
> > changes looks good standalone!
> > Can you add a comment with source of make-check failure or any references if this change intends to address them, thanks!
> 
> @ideepika could you be more specific? which "make check failure" you are referencing? 

> @batrick yeah, they are not directly related to this "CMAKE_BUILD_TYPE=Debug" change. actually, they should have been included by #42785 . but because i failed to fix `CMAKE_BUILD_TYPE` in 8e0308c860a9265e8438a978e90090ede08bd647, #42785 failed to introduce the change it claimed to implement -- to fail the build if any warning is reported by the compiler.
> 
> so yes, they fix "make check" failures. without them, the "CMAKE_BUILD_TYPE=Debug" commit alone would fail the "make check" run.

@tchaikov is the make check failure here the one mentioned in 8e0308c860a9265e8438a978e90090ede08bd647 commit msg?

**Comment by tchaikov** [comment]
@ideepika 8e0308c860a9265e8438a978e90090ede08bd647 does not mention any "make check" failure.

**Comment by ideepika** [comment]
> so yes, they fix "make check" failures. without them, the "CMAKE_BUILD_TYPE=Debug" commit alone would fail the "make check" run.

@tchaikov  is this related to fixing regression https://tracker.ceph.com/issues/52053 or some other "make-check" failure?

**Comment by tchaikov** [comment]
no. this is not.

**Comment by ideepika** [comment]
> no. this is not.

okay, thanks for clarifying :+1:

**Comment by tchaikov** [comment]
jenkins test make check

**Comment by tchaikov** [comment]
https://pulpito.ceph.com/kchai-2021-08-17_04:49:07-rados-wip-kefu-testing-2021-08-17-0902-distro-basic-smithi/

**Review by lxbsz — APPROVED** [review]
LGTM, thanks.

**Pull request merged**
