### PR TITLE
cephfs-mirror: reopen logs on SIGHUP

### PR DESCRIPTION
**Pull request by vshankar**
Fixes: http://tracker.ceph.com/issues/51318
Signed-off-by: Venky Shankar <vshankar@redhat.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by vshankar** [comment]
added cephfs-mirror to logrotate conf.

**Comment by vshankar** [comment]
jenkins test make check

**Comment by vshankar** [comment]
jenkins test make check

**Review by mchangir — COMMENTED** [review]
Would it be too much to add a line in the commit message saying ...
eventually the global ceph context object invokes the method named reopen_logs() of the low level RADOS object ?

**Comment by vshankar** [comment]
> Would it be too much to add a line in the commit message saying ...
> eventually the global ceph context object invokes the method named reopen_logs() of the low level RADOS object ?

Maybe, but its pretty obvious (to me atleast) that there is a ceph context helper that does the job.

**Review by batrick — APPROVED** [review]

**Comment by batrick** [comment]
https://tracker.ceph.com/projects/cephfs/wiki/Master#2021-June-26

**Pull request merged**
