### PR TITLE
Fix nss for cmake

### PR DESCRIPTION
**Pull request by dalgaaf**
It sees that currently cmake only work with cryptopp but doesn't build with libnss. This PR enables build with nss.

### CODE REVIEW

**Comment by liewegas** [comment]
lgtm.  it will conflict with wip-auth, though.. if there's no rush can we merge that first?

**Comment by dalgaaf** [comment]
No problem. Is there already a plan when wip-auth get merged?

**Comment by liewegas** [comment]
as soon as hammer bugs are squashed and we run an integration test against 
master again

**Comment by dalgaaf** [comment]
@liewegas Let me know as soon as wip-auth is in master, then I rebase/fix this PR.

**Comment by dalgaaf** [comment]
@liewegas: is there ny know timeframe for merging wip-auth?

**Comment by liewegas** [comment]
I was about to merge but hit a suspicious make check error, then got 
sidetracked.  very soon...

**Comment by dalgaaf** [comment]
rebased to master

**Comment by liewegas** [comment]
@dalgaaf wip-auth finally merged, okay to rebase!  sorry it took so long

**Comment by dalgaaf** [comment]
rebased to master!

**Comment by dachary** [comment]
@dalgaaf did you notice #4601 ?

**Comment by oritwas** [comment]
Looks good, lets merge this and I will remove the first patch from my series

**Pull request merged**
