### PR TITLE
doc: Add a new document on Dynamic Metadata Management in CephFS

### PR DESCRIPTION
**Pull request by sidharthanup**
Signed-off-by: Sidharth Anupkrishnan <sanupkri@redhat.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`

</details>

### CODE REVIEW

**Comment by sidharthanup** [comment]
@batrick Should there be a separate document for multiple active metadata servers or should it be included as part of dynamic metadata management?

**Comment by sidharthanup** [comment]
jenkins render docs

**Comment by batrick** [comment]
jenkins render docs

**Comment by sidharthanup** [comment]
jenkins render docs

**Comment by sidharthanup** [comment]
jenkins render docs

**Pull request merged**
