### PR TITLE
jewel: A query on a static large object fails with 404 error

### PR DESCRIPTION
**Pull request by Abhishekvrshny**
http://tracker.ceph.com/issues/16085

### CODE REVIEW

**Comment by Abhishekvrshny** [comment]
test this please

**Comment by dachary** [comment]
Hey jenkins, please test this (logs are gone)

**Comment by dachary** [comment]
@mattbenjamin does this backport look good to merge ? It passed the rgw suite http://tracker.ceph.com/issues/16344#note-6 (except for one failure which I believe to be unrelated).

**Comment by dachary** [comment]
Hey jenkins, please test this (logs are gone)

**Comment by dachary** [comment]
Hey jenkins, test this please (logs are gone)

**Comment by dachary** [comment]
@mattbenjamin ping ?

**Comment by dachary** [comment]
@mattbenjamin ping ?

**Comment by dachary** [comment]
@mattbenjamin ping ?

**Pull request merged**
