### PR TITLE
qa/tests: Add supported-random-distro$ links

### PR DESCRIPTION
**Pull request by wusui**
added for fs, kcephfs, and multimds

Fixes: http://tracker.ceph.com/issues/24138
Signed-off-by: Warren Usui <wusui@redhat.com>

### CODE REVIEW

**Comment by yuriw** [comment]
@wusui can you pls paste tests results that is not working ?

**Comment by yuriw** [comment]
trying 
http://pulpito.ceph.com/yuriw-2018-06-12_21:09:43-fs-master-distro-basic-smithi/
http://pulpito.ceph.com/yuriw-2018-06-12_21:15:40-kcephfs-master-testing-basic-smithi/
http://pulpito.ceph.com/yuriw-2018-06-12_21:16:57-multimds-master-testing-basic-smithi/

**Comment by yuriw** [comment]
@batrick I think those ^ look like real issues but PR is ready.  What do you think?  Leaving for you to merge.

**Comment by batrick** [comment]
Please annotate the commit which fixes/resolves a Ceph tracker issue with:

`Fixes: http://tracker.ceph.com/issues/...`

**Comment by batrick** [comment]
Please prefix the title of your commit message with the subcomponent you are changing. See also [1]. This is required for your PR to be merged.

[1] https://github.com/ceph/ceph/blob/master/SubmittingPatches.rst#3-describe-your-changes

**Comment by yuriw** [comment]
logged issues:
http://tracker.ceph.com/issues/24515
http://tracker.ceph.com/issues/24517
http://tracker.ceph.com/issues/24518

**Comment by tchaikov** [comment]
i'd suggest we fix the `--rerun` feature before adding more `$` links. otherwise we cannot reliably rerun the failed tests.

**Comment by zmc** [comment]
A link to the PR: https://github.com/ceph/teuthology/pull/1182

**Comment by batrick** [comment]
Warren, your 'signed-off-by' is not formatted correctly and so it's failing the CI check. (Please use `git commit -s`)

**Comment by wusui** [comment]
Sorry.  I didn't realize that the sign-off was format checked.  I will fix.

**Comment by wusui** [comment]
I did:
 git commit --allow-empty -s
git rebase -i HEAD~2
   and squashed the commit and edited the message.
when I did 'git push origin wip-wusui-24138' i got: 
! [rejected]        wip-wusui-24138 -> wip-wusui-24138 (non-fast-forward)
error: failed to push some refs to 'http://github.com/ceph/ceph'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

What should I do to fix this?

**Comment by batrick** [comment]
That's not the approach I'd suggest. Instead:

````
git co yourbranch
# undo the git commands you tried:
git reset --hard 2e976c3ab087781eb750292008d7711ea5739554
# Now amend the commit and add the signed-off
git commit --amend -s
````

More generally, you could have done:

````
git rebase --signoff upstream/master
````

(I think!)

**Comment by yuriw** [comment]
we need it on `mimic` as well

**Comment by batrick** [comment]
@wusui you need to do `git push ... --force`.

**Comment by yuriw** [comment]
@wusui you need to change 
`Signed off by: Warren Usui <wusui@redhat.com>"` 
to 
`Signed-off-by: Warren Usui <wusui@redhat.com>"`

do something like:
`git commit -s --signoff --amend`
fix this and then
`git push origin +wip-wusui-24138`

**Pull request merged**
