### PR TITLE
luminous: cephfs-journal-tool: make --rank argument mandatory

### PR DESCRIPTION
**Pull request by vshankar**
https://tracker.ceph.com/issues/36217

### CODE REVIEW

**Comment by smithfarm** [comment]
@batrick Pinging for review - does it need a release note?

**Comment by batrick** [comment]
@smithfarm yes I think so. What's the preferred way to do that for backports?

**Comment by smithfarm** [comment]
@batrick Add a commit to this PR. The commit should add a `12.2.11` section to https://github.com/ceph/ceph/blob/luminous/PendingReleaseNotes with the release note underneath.

Unfortunately this will almost certainly conflict with other PRs also adding release notes in the same way, but I don't know of any way to avoid that. In the past we have always managed to deal with these conflicts one way or another.

**Comment by vshankar** [comment]
@batrick @smithfarm -- I've added the release notes -- please check

**Comment by vshankar** [comment]
note that this release notes commit is luminous only -- I was sure about the protocol to include release notes. If needed, that can be sent to master and cherry-picked here.

**Comment by smithfarm** [comment]
@vshankar The protocol for adding release notes is the same in master. Adding the RN to master first and then doing a proper luminous cherry-pick is the preferred workflow, but not absolutely necessary (common sense should always prevail).

**Comment by vshankar** [comment]
@smithfarm -- apologies for getting back late on this. master RN has >=mimic. I think RN for this should just go to luminous?

**Comment by smithfarm** [comment]
@vshankar I looked in `doc/releases/` and `PendingReleaseNotes` (in master) and couldn't find this particular release note. In which version exactly was the feature first included?

**Comment by vshankar** [comment]
@smithfarm release notes for this feature was never added in master. The features got merged during nautilus dev cycle.

**Comment by yuriw** [comment]
[wip-yuri5-testing-2018-12-12-1653-luminous](https://trello.com/c/oXzdX0yM/487-wip-yuri5-testing-2018-12-12-1653-luminous)

**Comment by yuriw** [comment]
[wip-yuri4-testing-2018-12-19-1658-luminous](https://trello.com/c/XKKZA4vr/494-wip-yuri4-testing-2018-12-19-1658-luminous)

**Comment by vshankar** [comment]
Reviewed-by: Venky Shankar vshankar@redhat.com

**Comment by superxor** [comment]
docs require update http://docs.ceph.com/docs/master/cephfs/cephfs-journal-tool/

**Pull request merged**
