### PR TITLE
rgw: aws4: fix buffer sharing issue with chunked uploads

### PR DESCRIPTION
**Pull request by jmunhoz**
Signed-off-by: Javier M. Mellid <jmunhoz@igalia.com>

### CODE REVIEW

**Comment by jmunhoz** [comment]
@mattbenjamin this is the new PR suggested in https://github.com/ceph/ceph/pull/9484#issuecomment-225705070

**Comment by mattbenjamin** [comment]
lgtm -- verfifying

**Comment by jmunhoz** [comment]
@mattbenjamin thanks for the reviewing!

**Comment by smithfarm** [comment]
AFAICT this has not been backported to jewel yet.

**Comment by yehudasa** [comment]
@smithfarm not sure this one is part of the original issue (seems like an optimization, not related to clock skew). @jmunhoz does this fix any known issue, or just a buffer copy optimization?

**Comment by cbodley** [comment]
it's just an optimization to avoid bufferlist reference counting. @mattbenjamin suggested it in https://github.com/ceph/ceph/pull/9484#discussion_r66813531 as a separate pull request

**Comment by jmunhoz** [comment]
yes, as mentioned, it is just an optimization on top of https://github.com/ceph/ceph/pull/9484 I added a brief comment at http://tracker.ceph.com/issues/16146#note-4

**Comment by jmunhoz** [comment]
I added some code and info to ease the backport at http://tracker.ceph.com/issues/16311#note-3

**Pull request merged**
