### PR TITLE
crush: API documentation

### PR DESCRIPTION
**Pull request by dachary**
This mirrors the commit http://libcrush.org/main/libcrush/commit/3b93403369fe92009bd71520b4132a0be02ac0d8 reviewed at http://libcrush.org/main/libcrush/merge_requests/1

### CODE REVIEW

**Comment by liewegas** [comment]
Oops, one thing I should have noticed before: currently these files (crush.h, mapper.[ch]) are easy to sync up with the kernel by copying into the tree and looking for any diffs with git gui (or similar).  The inline doxygen will make that a bit harder, and I imagine the kernel doesn't want doxygen in the tree.   Or maybe they don't care since we're the maintainers... @idryomov do you think it matters?  Worst case we can try to avoid doxygen comments on the same line so that it's easy to exclude them.  But hopefully we can just dump them in the kernel too?

**Comment by dachary** [comment]
Or we can move the doxygen comments in a separate file and not touch the *.[ch] files at all. When we discussed with @adamemerson about various options, it made most sense to keep the documentation close to the functions to help keep it in sync. Either way it's not a blocker :-)

**Comment by idryomov** [comment]
I'd rather not throw a wrench into the documentation effort.  A separate file definitely makes less sense.
I'm fine with pulling it into the kernel -- if it ends up causing problems, stripping everything (including inline comments) should be fairly easy.

**Comment by dachary** [comment]
@idryomov cool :-)

**Pull request merged**
