### PR TITLE
mon: get writeable osdmap for added data pool

### PR DESCRIPTION
**Pull request by batrick**
Continuation of: 435717791ec499f71c9d1485b1e4e63239a343e2

Fixes: http://tracker.ceph.com/issues/21064

Signed-off-by: Patrick Donnelly <pdonnell@redhat.com>

### CODE REVIEW

**Comment by tchaikov** [comment]
removing the "luminous" milestone, as this PR is not targeting luminous, and add "needs-backport" label, as it should be backported to luminous.

**Comment by theanalyst** [comment]
http://tracker.ceph.com/issues/21081

**Comment by batrick** [comment]
Removing needs-backport since we have a tracker ticket.

**Comment by batrick** [comment]
@theanalyst sorry I forgot to add the tracker to the PR description.

**Comment by theanalyst** [comment]
@batrick no issues :) just created one for tracking backports

**Comment by batrick** [comment]
http://pulpito.ceph.com/pdonnell-2017-08-23_01:47:26-fs-wip-pdonnell-testing-20170822b-distro-basic-smithi/
http://pulpito.ceph.com/pdonnell-2017-08-23_01:52:24-multimds-wip-pdonnell-testing-20170822b-testing-basic-smithi/

Resovles the ceph-mon assertion previously seen here:

http://pulpito.ceph.com/pdonnell-2017-08-21_23:13:19-fs-wip-pdonnell-testing-20170821-distro-basic-smithi/1548891/

**Pull request merged**
