### PR TITLE
nautilus: os/bluestore: apply garbage collection against excessive blob count growth

### PR DESCRIPTION
**Pull request by ifed01**
Fixes: https://tracker.ceph.com/issues/40449
Signed-off-by: Igor Fedotov <ifedotov@suse.com>

## Checklist
- [x] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`

</details>

### CODE REVIEW

**Comment by smithfarm** [comment]
jenkins test make check

**Comment by smithfarm** [comment]
jenkins test submodules

**Comment by smithfarm** [comment]
```
171/171 Test   #3: test_objectstore_memstore.sh ............***Timeout 3600.03 sec
```

@tchaikov @liewegas @badone This is happening quite often in "make check" in the stable branches. Would it be worth considering to disable this test in the stable branches?

**Comment by smithfarm** [comment]
jenkins test make check

**Comment by tchaikov** [comment]
@smithfarm yeah. it's annoying. will take a closer look at it.

**Comment by smithfarm** [comment]
@tchaikov Now the build failure is:

```
In file included from /home/jenkins-build/build/workspace/ceph-pull-requests/src/include/encoding.h:30:0,
                 from /home/jenkins-build/build/workspace/ceph-pull-requests/src/include/uuid.h:8,
                 from /home/jenkins-build/build/workspace/ceph-pull-requests/src/include/types.h:21,
                 from /home/jenkins-build/build/workspace/ceph-pull-requests/src/common/ceph_json.h:4,
                 from /home/jenkins-build/build/workspace/ceph-pull-requests/src/rgw/rgw_auth_keystone.cc:13:
/home/jenkins-build/build/workspace/ceph-pull-requests/src/common/ceph_time.h:504:16: warning: variable templates only available with -std=c++14 or -std=gnu++14
```

followed by 70MB of compiler errors.

Could it be that there is still a `-std=c++11` still lurking somewhere?

**Comment by badone** [comment]
Builds fine for me on Xenial using 8.3.0 but I notice this build was using 7.4. Is that right? test_objectstore_memstore.sh also passes for me so, so far, i can't be of much help. I'll try to reproduce this with 7.4 to see if that gives further insight.

**Comment by badone** [comment]
Bingo! It took some doing to get my environment set up the same as the build environment but here we go.

```
ccache /usr/bin/c++   -D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE -D__linux__ -isystem /opt/ceph/include -I/ceph/build/src/include -I/ceph/src -isystem /ceph/build/include -I/usr/include/nss -I/usr/include/nspr -isystem /ceph/src/xxHash -isystem /ceph/src/rapidjson/include -I/ceph/src/dmclock/support/src -isystem /ceph/src/rgw/../rapidjson/include  -Wall -Wtype-limits -Wignored-qualifiers -Winit-self -Wpointer-arith -Werror=format-security -fno-strict-aliasing -fsigned-char -Wno-unknown-pragmas -rdynamic  -ftemplate-depth-1024 -Wnon-virtual-dtor -Wno-unknown-pragmas -Wno-ignored-qualifiers -Wstrict-null-sentinel -Woverloaded-virtual -fno-new-ttp-matching -DCEPH_DEBUG_MUTEX -fstack-protector-strong -std=c++17 -fdiagnostics-color=auto -fno-builtin-malloc -fno-builtin-calloc -fno-builtin-realloc -fno-builtin-free -g -fPIC   -DHAVE_CONFIG_H -D__CEPH__ -D_REENTRANT -D_THREAD_SAFE -D__STDC_FORMAT_MACROS -std=gnu++11 -o CMakeFiles/rgw_a.dir/rgw_auth_keystone.cc.o -c /ceph/src/rgw/rgw_auth_keystone.cc
```
Above is the command to build rgw_auth_keystone.o. Notice '-std=gnu++11' as @smithfarm suspected but also ' -std=c++17' earlier in the command line which is being overridden. Not clear to me why/how. I'll re-engage on this tomorrow if it remains unresolved by then.

**Comment by smithfarm** [comment]
I scoured the Ceph codebase for `gnu++11` and came up empty-handed. But I did find this in master:

```
$ git blame master cmake/modules/CheckCxxAtomic.cmake
...
16976bd42a4d (Kefu Chai 2018-07-10 01:17:54 +0800  8) function(check_cxx_atomics var)
16976bd42a4d (Kefu Chai 2018-07-10 01:17:54 +0800  9)   set(CMAKE_REQUIRED_FLAGS "${CMAKE_REQUIRED_FLAGS} -std=c++11")
```

**Comment by tchaikov** [comment]
it's not related. `CMAKE_REQUIRED_FLAGS` is only used for testings like `check_cxx_source_compiles()`. moreover, this variable is restored using `cmake_push_check_state()` and `cmake_pop_check_state()` calls. see https://cmake.org/cmake/help/latest/module/CMakePushCheckState.html.

**Comment by badone** [comment]
Seems like this is related to CMAKE_CXX11_EXTENSION_COMPILE_OPTION and the lack of c==17 support in cmake 3.5.1. If I hack that variable to "-std=c++17" instead of "-std=gnu++11" the build succeeds. Something appears inconsistent here sine all Nautilus builds should be failing.

**Comment by tchaikov** [comment]
jenkins test make check

**Comment by badone** [comment]
My theory is further buoyed by the fact this PR originally built successfully (per https://github.com/ceph/ceph/pull/30144#issuecomment-528414884) and failed subsequently without any code modification. This also indicates a change in the build environment.

**Comment by badone** [comment]
https://github.com/ceph/ceph/pull/30248 is a good example of what we face I believe. It built nautilus a little while ago on Xenial but it used gcc 8.3.0. So, are we supposed to be using 8.3.0 or 7.4 ?

**Comment by badone** [comment]
This PR now built successfully with 8.3.0

**Comment by smithfarm** [comment]
@liewegas I guess you want this one to bake longer in master?

**Comment by liewegas** [comment]
> @liewegas I guess you want this one to bake longer in master?

I don't have a strong opinion either way.  I did see an unexplained bluestore failure a week or two ago (https://tracker.ceph.com/issues/42010) that might be worth taking a closer look at first to convince ourselves this isn't related.  I couldn't come up with a theory when I first saw the failure.

**Comment by yuriw** [comment]
[wip-yuri-testing-2019-11-12-2351-nautilusyuriw](https://trello.com/c/BBf5fA8p/758-wip-yuri-testing-2019-11-12-2351-nautilusyuriw)

**Comment by yuriw** [comment]
[wip-yuri3-testing-2019-11-14-2348-nautilus](https://trello.com/c/X7R21SYy/762-wip-yuri3-testing-2019-11-14-2348-nautilus)

**Pull request merged**
