### PR TITLE
common/buffer: avoid extra assignment

### PR DESCRIPTION
**Pull request by Aran85**
Signed-off-by: Zengran Zhang <zhangzengran@sangfor.com.cn>

- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by tchaikov** [comment]
@Aran85 i don't think this commit "avoids extra assignment". it's just another way to initialize the member variable.

**Comment by Aran85** [comment]
@tchaikov Thanks for pointed out. I think the class with non-trivial constructor will introduce extra assignment, but POD type with trivial constructor is different?

**Comment by tchaikov** [comment]
@Aran85 i don't follow you. probably you could come up with a minimal sample to show that your change eliminates an assignment? to my best understanding, the advantage of your change is just cosmetic. as there is no difference between

- assign a new value to it in the body of constructor
- assign a new value to it using the member initializing list

as this very constructor does not initialize `align` using its default constructor.

**Comment by Aran85** [comment]
@tchaikov thanks for teaching, closing for unnecessary change.

**Pull request closed without merging**
