### PR TITLE
rgw: remove unused variables

### PR DESCRIPTION
**Pull request by ztczll**
Signed-off-by: ztczll <243290414@qq.com>

### CODE REVIEW

**Comment by amitkumar50** [comment]
@ztczll Is there no tracker which this PR provides solution. Its always good to create an tracker so that reviewer can get Idea for what purpose PR is generated.

**Comment by cbodley** [comment]
hi @ztczll, are you sure about `Signed-off-by: ztczll <243290414@qq.com>`? the ceph project uses these to keep track of contributors and their affiliations (i.e. [v12.0.0 Contributor credits](https://www.spinics.net/lists/ceph-devel/msg35198.html)). i'd invite you to use a real name and email address, but it's not required!

@amitkumar50 generally, tracker issues are only needed when the changes are likely to need a backport. for simple fixes (like removing dead code), the commit message and pr description are sufficient

**Comment by ztczll** [comment]
@amitkumar50 Ok, I'll change my signature.

**Comment by ztczll** [comment]
Ok, I'll change my signature.

**Comment by joscollin** [comment]
Jenkins retest this please

**Comment by joscollin** [comment]
Test Result:

- http://pulpito.front.sepia.ceph.com/jcollin-2017-08-11_03:03:58-rgw-wip-jcollin-testing_08-10-2017-distro-basic-smithi/
- http://pulpito.front.sepia.ceph.com/compare/?branch=wip-jcollin-testing_08-10-2017&suite=rgw

**Pull request merged**
