### PR TITLE
octopus: mgr/dashboard: Always use fast angular unit tests

### PR DESCRIPTION
**Pull request by Devp00l**
backport tracker: https://tracker.ceph.com/issues/46693

---

backport of https://github.com/ceph/ceph/pull/34965
parent tracker: https://tracker.ceph.com/issues/45433

this backport was staged using ceph-backport.sh version 15.1.1.389
find the latest version at https://github.com/ceph/ceph/blob/master/src/script/ceph-backport.sh

### CODE REVIEW

**Comment by alfonsomthd** [comment]
jenkins test make check

**Comment by smithfarm** [comment]
```
Test failures: 141 - mgr-dashboard-frontend-unittests (Failed) 
```

**Comment by Devp00l** [comment]
> ```
> Test failures: 141 - mgr-dashboard-frontend-unittests (Failed) 
> ```

Could not reproduce that locally... Rebased the branch.

**Comment by smithfarm** [comment]
@Devp00l Thanks, tests passed this time.

**Comment by yuriw** [comment]
[wip-yuri4-testing-2020-08-05-1459-octopus](https://trello.com/c/tnhbfTPr/984-wip-yuri4-testing-2020-08-05-1459-octopus)

**Pull request merged**
