### PR TITLE
ceph-disk: modify the disk partition sequence of ceph-disk list

### PR DESCRIPTION
**Pull request by houlinfei**
Signed-off-by: houlinfei <hou.linfei@h3c.com>

### CODE REVIEW

**Comment by houlinfei** [comment]
hi Sage,
this commit modify the disk partition sequence when you use ceph-disk list command. Could you see and merge it? @liewegas

**Comment by houlinfei** [comment]
hi Sage,
this commit modify the disk partition sequence when you use ceph-disk list command. Could you see and merge it? thank you. @liewegas

**Comment by ErwanAliasr1** [comment]
@houlinfei Can you add in your commit the motivation behind such change ?

**Comment by dachary** [comment]
:+1: running the ceph-disk suite to be extra sure

**Pull request closed without merging**
