### PR TITLE
nautilus: os/bluestore: backport more bluestore alerts

### PR DESCRIPTION
**Pull request by ifed01**
https://tracker.ceph.com/issues/39348

### CODE REVIEW

**Comment by smithfarm** [comment]
jenkins test make check

**Comment by ifed01** [comment]
jenkins please test

**Comment by ifed01** [comment]
jenkins retest please

**Comment by ifed01** [comment]
jenkins test make check

**Comment by liewegas** [comment]
retest this please

**Comment by yuriw** [comment]
[wip-yuri4-testing-2019-05-30-2109-nautilus](https://trello.com/c/gp7jSQKF/626-wip-yuri4-testing-2019-05-30-2109-nautilus)

**Pull request merged**
