### PR TITLE
qa: skip internal metadata directory when scanning ceph debugfs direc…

### PR DESCRIPTION
**Pull request by vshankar**
…tory

kclient patchset:

        https://patchwork.kernel.org/project/ceph-devel/list/?series=556049

introduces `meta` directory to add debugging entries. This needs to be filtered
when scanning ceph debugfs directory.

Fixes: https://tracker.ceph.com/issues/52824
Signed-off-by: Venky Shankar <vshankar@redhat.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by vshankar** [comment]
FWIW, we should also be fixing this: https://github.com/ceph/teuthology/blob/master/teuthology/nuke/actions.py#L131

That seems to be scanning ceph debugfs directory to find stale mounts (if any).

**Comment by vshankar** [comment]
jenkins test make check

**Review by jtlayton — APPROVED** [review]

**Review by batrick — CHANGES_REQUESTED** [review]
This needs a separate tracker ticket because this change will need backported to pacific/octopus.

**Comment by vshankar** [comment]
jenkins retest this please

**Pull request merged**
