### PR TITLE
DNM: RGW: Make RADOS handles in RGW to be a configurable option

### PR DESCRIPTION
**Pull request by prallabh**
http://tracker.ceph.com/issues/12894

### CODE REVIEW

**Comment by dachary** [comment]
@prallabh could you please **cherry-pick -x** the commit to be backported and repush ?
<pre>
git reset --hard ceph/hammer
git cherry-pick -x 77e0084
git push --force origin hammer
</pre>
assuming **origin** is the remote of your github clone and **ceph** is the remote of the official repository.

**Comment by dachary** [comment]
@yehudasa could you please confirm that this feature should be backported to hammer ?

**Comment by prallabh** [comment]
@dachary This PR is with your suggestion of 'cheery-pick -x', please let me know if am missing anything else.

**Comment by yehudasa** [comment]
@dachary confirmed

**Comment by dachary** [comment]
@prallabh could you please rebase and repush to trigger the bot again ? It looks like this is a not a real error.

**Comment by dachary** [comment]
@prallabh this PR has a single commit 15234a9 and it is not the result of cherry-pick -x 77e0084

**Comment by dachary** [comment]
@prallabh looks good, thanks

**Comment by dachary** [comment]
@prallabh is there an issue matching this change in http://tracker.ceph.com/ ?

**Comment by prallabh** [comment]
@dachary if you are referring to, whether we have a tracker for this change set, there ain't any. Do you want me to create one? We never had one even for the original PR on the master.

**Comment by dachary** [comment]
@prallabh it's ok to create an issue even after the commits have been merged. And it helps with tracking backports. Could you create one for the original PR on the master ? I'll take care of the things related to the backport.

**Comment by dachary** [comment]
Marked DNM because it's already included in #5717

**Comment by prallabh** [comment]
@dachary Please find the tracker http://tracker.ceph.com/issues/12893. Please update the relevant fields in the tracker appropriately if they are out of place.

**Comment by theanalyst** [comment]
Merged in #5717 onto hammer branch .. this can be closed.

**Comment by dachary** [comment]
@theanalyst nice catch :-)

**Pull request closed without merging**
