### PR TITLE
jewel: osd: pg_pool_t::encode(): be compatible with Hammer <= 0.94.6

### PR DESCRIPTION
**Pull request by asheplyakov**
http://tracker.ceph.com/issues/19508

### CODE REVIEW

**Comment by smithfarm** [comment]
@asheplyakov I will include this in the next jewel integration testing round.

**Comment by smithfarm** [comment]
@jdurgin This passed a rados run at http://tracker.ceph.com/issues/19538#note-39

Please review.

**Comment by smithfarm** [comment]
@jdurgin This passed another rados run at http://tracker.ceph.com/issues/19538#note-49

**Comment by smithfarm** [comment]
@jdurgin Steps to reproduce are set out in detail here: http://tracker.ceph.com/issues/19508#note-6

However, at the end it says "In a cluster with many (>~ 100) OSDs sending that many complete maps can easily overload monitors"

So. . . though we might be able to add such a reproducer to the upgrade/hammer-x suite, it's not likely to trigger the monitor overload due to insufficient number of OSDs.

**Comment by asheplyakov** [comment]
@smithfarm 
> it's not likely to trigger the monitor overload due to insufficient number of OSDs

Can we grep for `failed to encode map e[0-9]+ with expected crc` in the logs?

> do any of the upgrade suites in cover this scenario? 

I've got a related question. As far as I understand upgrade/hammer-x tests the upgrade from the latest  released version of Hammer (0.94.10 at this time), but not from any older Hammer releases?

**Comment by jdurgin** [comment]
@asheplyakov @smithfarm here's an example that tests a specific hammer version upgrade issue, and greps for messages in the logs:

https://github.com/ceph/ceph/blob/jewel/qa/suites/upgrade/hammer-x/v0-94-4-stop/v0-94-4-stop.yaml

seems like it would be useful to write a similar test for this

**Comment by smithfarm** [comment]
> As far as I understand upgrade/hammer-x tests the upgrade from the latest released version of Hammer (0.94.10 at this time), but not from any older Hammer releases?

@asheplyakov It depends on the test yaml (test definition). If it says merely `hammer` then the latest hammer build in Shaman is used. If it says, e.g., `v0.94.3` then that build is used.

**Comment by smithfarm** [comment]
Note: the build is only used if Shaman can satisfy the requirement - see http://tracker.ceph.com/issues/18089

**Comment by smithfarm** [comment]
Initial attempt to implement the upgrade test: #14930

**Comment by smithfarm** [comment]
Jenkins retest this please (logs are gone)

**Comment by smithfarm** [comment]
@asheplyakov Could you rebase this to clean up the Jenkins test report? As it is, the old failed "default" test is causing a red X to be displayed next to the PR, even though the PR passed the required tests.

**Comment by asheplyakov** [comment]
@smithfarm

> Could you rebase this to clean up the Jenkins test report? 

Done

**Comment by smithfarm** [comment]
@jdurgin This PR was included in an `upgrade/hammer-x` run at http://tracker.ceph.com/issues/19538#note-80 which had 3 failures. I'm not sure if any of them are related to this PR and seeing that it's notoriously difficult to get the `upgrade` suites running 100% clean, I guess 15 pass out of 18 is a pretty good result. That run includes the new test at #14930 and it does *not* include #14626 which was whitelisting the "failed to encode" log warning message - in other words, it looks like this PR makes that message go away.

I think this PR and #14930 are ready to merge. Do you agree?

**Pull request merged**
