### PR TITLE
clear data and payload after removed from ops_in_flight

### PR DESCRIPTION
**Pull request by boydc2014**
http://tracker.ceph.com/issues/9916 Fixes: #9916

Signed-off-by: Dong Lei leidong@yahoo-inc.com

### CODE REVIEW

**Comment by boydc2014** [comment]
@liewegas I may need to explain why QA fails on my first commit:

Firstly, I want to  clear data and payload after remove op from ops_in_flight using the following code:
   {
   Mutex::Locker locker(ops_in_flight_lock);
   assert(i->xitem.get_list() == &ops_in_flight);
   utime_t now = ceph_clock_now(cct);
   i->xitem.remove_myself();
   history.insert(now, TrackedOpRef(i));   // here is the problem
   }
   i->request->clear_data();
   i->request->clear_payload();

Why QA fails is that when doing history.insert, the history will try to clear the TrackedOpRef according to the setting of how long history will be kept(0 for now). So the history will remove this TrackedOpRef just after inserting it. And the destructor of op is called. Then I want to call clear_data and clear_payload and fails because the object has been destructed.

**Comment by boydc2014** [comment]
ping @dachary @liewegas

**Comment by liewegas** [comment]
This looks correct to me!  Alternatively, you could take a ref and do teh free after, but this is simpler, and clear should be fast.

Reviewed-by:

**Comment by liewegas** [comment]
Can you redo this pull request, targetting master branch?  and put

 Backport: giant, firefly

in the git commit message so that we can backport it.  Thanks!

**Comment by boydc2014** [comment]
@liewegas Thanks sage, this has been fixed in master https://github.com/ceph/ceph/commit/11082f7aa02f3f41c7c74c5930b67216dba88ea1
I  just redo it in firefly.

**Pull request merged**
