### PR TITLE
pacific: tools/rbd: expand where option rbd_default_map_options can be set

### PR DESCRIPTION
**Pull request by ideepika**
backport tracker: https://tracker.ceph.com/issues/54324

---

backport of https://github.com/ceph/ceph/pull/44904
parent tracker: https://tracker.ceph.com/issues/52850

this backport was staged using ceph-backport.sh version 16.0.0.6848
find the latest version at https://github.com/ceph/ceph/blob/master/src/script/ceph-backport.sh

### CODE REVIEW

**Comment by idryomov** [comment]
Where did
```
 Conflicts:
	qa/suites/big/rados-thrash/ceph/ceph.yaml
	qa/suites/fs/upgrade/volumes/import-legacy/overrides/pg-warn.yaml
	qa/suites/krbd/ms_modeless/.qa
	qa/suites/krbd/ms_modeless/bluestore-bitmap.yaml
	qa/suites/krbd/ms_modeless/ceph/.qa
	qa/suites/krbd/ms_modeless/ceph/ceph.yaml
	qa/suites/krbd/ms_modeless/clusters/.qa
	qa/suites/krbd/ms_modeless/clusters/fixed-3.yaml
	qa/suites/krbd/ms_modeless/conf.yaml
	qa/suites/krbd/ms_modeless/tasks/.qa
	qa/suites/krbd/ms_modeless/tasks/krbd_rxbounce.yaml
	qa/suites/krbd/rxbounce/.qa
	qa/suites/krbd/rxbounce/bluestore-bitmap.yaml
	qa/suites/krbd/rxbounce/ceph/.qa
	qa/suites/krbd/rxbounce/ceph/ceph.yaml
	qa/suites/krbd/rxbounce/clusters/.qa
	qa/suites/krbd/rxbounce/conf.yaml
	qa/suites/krbd/rxbounce/tasks/.qa
	qa/suites/upgrade/nautilus-x-singleton/bluestore-bitmap.yaml
	qa/suites/upgrade/nautilus-x/parallel/2-workload/.qa
	qa/suites/upgrade/nautilus-x/parallel/3-upgrade-sequence/.qa
	qa/suites/upgrade/nautilus-x/parallel/5-final-workload/.qa
	qa/suites/upgrade/nautilus-x/stress-split-erasure-code/.qa
```
come from?

**Comment by ljflores** [comment]
http://pulpito.front.sepia.ceph.com/?branch=wip-yuri3-testing-2022-02-28-0757-pacific

Failures, unrelated:
    https://tracker.ceph.com/issues/47838
    https://tracker.ceph.com/issues/50042
    https://tracker.ceph.com/issues/53501
    https://tracker.ceph.com/issues/45721
    https://tracker.ceph.com/issues/54071
    https://tracker.ceph.com/issues/54469
    https://tracker.ceph.com/issues/53939
    https://tracker.ceph.com/issues/54360

Details:
    1. mon/test_mon_osdmap_prune.sh: first_pinned != trim_to - Ceph - RADOS
    2. sporadic rados/test.sh failures - Ceph - RADOS
    3. Exception when running 'rook' task. - Ceph - Orchestrator
    4. CommandFailedError: Command failed (workunit test rados/test_python.sh) FAIL: test_rados.TestWatchNotify.test - Ceph - RADOS
    5. rados/cephadm/osds: Invalid command: missing required parameter hostname(<string>) - Ceph - RADOS
    6. cephadm/smoke: "Post https://172.21.15.73:8443//api/prometheus_receiver: context deadline exceeded" leads to unresponsive manager - Ceph - Orchestrator
    7. ceph-nfs-upgrade, pacific: Upgrade Paused due to UPGRADE_REDEPLOY_DAEMON: Upgrading daemon osd.0 on host smithi103 failed - Ceph - Orchestrator
    8. Dead job at "Finished running handlers" in rados/cephadm/osds/.../rm-zap-wait - Ceph - Orchestrator

**Comment by ljflores** [comment]
jenkins test make check

**Comment by ideepika** [comment]
updated with clean cherry-picks, thanks!

**Review by idryomov — APPROVED** [review]

**Pull request merged**
