### PR TITLE
qa/rgw: skip swift tests on rhel 7.6+

### PR DESCRIPTION
**Pull request by cbodley**
swift bootstrap fails because libev-devel is not available

Fixes: http://tracker.ceph.com/issues/40304

### CODE REVIEW

**Comment by cbodley** [comment]
i pushed a separate nautilus branch to https://github.com/cbodley/ceph/commits/wip-40304-nautilus

**Comment by cbodley** [comment]
@yuriw can you please test that nautilus upgrade suite with `--suite-repo https://github.com/cbodley/ceph.git --suite-branch wip-40304-nautilus`?

**Comment by yuriw** [comment]
@cbodley http://pulpito.front.sepia.ceph.com:80/yuriw-2019-06-13_19:55:50-upgrade:nautilus-p2p-nautilus-distro-basic-smithi/

**Comment by yuriw** [comment]
test this please

**Pull request merged**
