### PR TITLE
hammer: build/ops: improve ceph.in error message

### PR DESCRIPTION
**Pull request by smithfarm**
Fixes: #11101
Signed-off-by: Kefu Chai kchai@redhat.com
(cherry picked from commit e19e8f1553fdf8b6b642d3222d28f242fab696f0)

### CODE REVIEW

**Comment by smithfarm** [comment]
@tchaikov Do you know of any tests that rely on the old behavior?

**Comment by tchaikov** [comment]
@smithfarm AFAIK, no. it's just a better error message. the old one is sort of misleading.

**Comment by smithfarm** [comment]
@liewegas This backport passed a rados suite at http://tracker.ceph.com/issues/17151#note-7 with failures that I believe have been addressed (except for http://tracker.ceph.com/issues/15139 which is caused by the build system no longer providing dumpling-era packages).

I have rebuilt the integration branch to include the two fixes and scheduled a new run at http://tracker.ceph.com/issues/17151#note-14

Do you think it's OK to merge provided the second run succeeds?

**Comment by liewegas** [comment]
:+1:

**Comment by smithfarm** [comment]
Note this also passed an upgrade suite at http://tracker.ceph.com/issues/17151#note-18

**Pull request merged**
