### PR TITLE
mds: improvements for stray reintegration

### PR DESCRIPTION
**Pull request by ukernel**
this helps stray reintegration in workload that first creates new
hardlink, then removes old hardlink

Signed-off-by: "Yan, Zheng" <zyan@redhat.com>

### CODE REVIEW

**Comment by jcsp** [comment]
This probably isn't exercised well by existing tests.  The person who reminded me about this issue had the following reproducer script:
```

#!/bin/bash -e

declare SRC="sources/"
declare DST="hardlinks/"
declare -i MAX=2000 # max files for each directory

[ ${#} -eq 1 ] || { echo "Usage: ${0} <nb_files>"; exit 1; }

mkdir "${SRC}" "${DST}"
declare -i count=1
declare subdir=""
for i in $(seq 1 ${1})
do
    [ ${count} -ge ${MAX} ] && { count=1; subdir+="sub/"; mkdir "${DST}/${subdir}"; }
    echo "" > "${SRC}/${i}"
    ln "${SRC}/${i}" "${DST}/${subdir}/${i}"
    rm "${SRC}/${i}"
    count+=1
done
```

@ukernel could you add that as a workunit in the fs/basic_workload to exercise this new code path?

**Comment by ukernel** [comment]
http://pulpito.ceph.com/zyan-2017-06-09_13:33:23-fs-wip-zyan-testing-testing-basic-smithi/

**Comment by jcsp** [comment]
test_strays.py is currently failing (http://tracker.ceph.com/issues/20335) on master, and also with this PR applied -- need to fix that before merging this.

**Comment by ukernel** [comment]
mds shutdown problem should be fixed by https://github.com/ceph/ceph/pull/15768

**Comment by ukernel** [comment]
http://pulpito.ceph.com/zyan-2017-06-20_13:07:54-fs-wip-zyan-integration-testing-basic-mira/
http://pulpito.ceph.com/zyan-2017-06-20_13:07:06-fs-wip-zyan-integration-testing-basic-mira/

test passed

**Pull request merged**
