### PR TITLE
rgw: Silence maybe-uninitialized false positives

### PR DESCRIPTION
**Pull request by badone**
Signed-off-by: Brad Hubbard <bhubbard@redhat.com>

### CODE REVIEW

**Comment by badone** [comment]
@cbodley Mind taking a look?

**Comment by cbodley** [comment]
this came up earlier in https://github.com/ceph/ceph/pull/19178, and https://svn.boost.org/trac10/ticket/11169 claims that it's a gcc bug. can you provide the versions of gcc and boost that produce these warnings? i haven't been able to reproduce them in the [compiler explorer](https://godbolt.org) against boost 1.64 or 1.65. i'd really prefer to find a workaround that doesn't involve gcc-specific pragmas

**Comment by badone** [comment]
@cbodley gcc 7.2.1 and boost 1.63.0

**Comment by badone** [comment]
@cbodley As we discussed  boost::optional<size_t> num_shards = boost::make_optional(false, 0UL); (note the explicit unsigned long) resolves the first issue but "int child_ret; child_ret = 0;" does not resolve the second. Updated the branch.

**Comment by cbodley** [comment]
> boost::make_optional(false, 0UL)

thanks - could you add a comment there that explains the workaround?

re: child_ret, i think we'd be better off changing that to a member variable and initializing it in the constructror

**Comment by cbodley** [comment]
ping @badone, could you please try moving `child_ret` into a member variable?

**Comment by badone** [comment]
@cbodley Sure Casey, how's this?

**Comment by cbodley** [comment]
tagged needs-qa just to make sure it compiles on the platforms we care about

**Comment by yuriw** [comment]
[wip-yuri2-testing-2017-12-18-1657](https://trello.com/c/PgmGgEIx/213-wip-yuri2-testing-2017-12-18-1657)

**Pull request merged**
