### PR TITLE
release cycle / timeline updates

### PR DESCRIPTION
**Pull request by dachary**

### CODE REVIEW

**Comment by dachary** [comment]
@liewegas I integrated most of https://github.com/liewegas/ceph/commit/0415040f1ac6cc22259fc409ed8fc33f86e58c35. I hopefully clarified what LTS means to avoid confusion with professional services. Instead of an arbitrary duration it is now explained as an LTS+2 logic matching what we currently do. Is this good enough ?

**Comment by dachary** [comment]
@jecluis good idea, amended :-)

**Comment by dachary** [comment]
@jecluis it would be nice to have something along these lines. My english is not good enough to even draft it though :-(

**Comment by liewegas** [comment]
looks good, thanks!

**Pull request merged**
