### PR TITLE
common/options.cc: document bluestore config options

### PR DESCRIPTION
**Pull request by liewegas**
Signed-off-by: Sage Weil <sage@redhat.com>

### CODE REVIEW

**Comment by liewegas** [comment]
@jdurgin @jcsp now is probably the time to write some guidelines about how tags, service, and so on should be used.

**Comment by liewegas** [comment]
http://pulpito.ceph.com/sage-2017-07-22_22:02:48-rados-wip-sage-testing-distro-basic-smithi/

**Comment by markhpc** [comment]
I'll try to look over these today

**Comment by liewegas** [comment]
@markhpc ping

**Comment by liewegas** [comment]
retest this please

**Pull request merged**
