### PR TITLE
qa/tests: update s3a hadoop versions used for test

### PR DESCRIPTION
**Pull request by vasukulkarni**
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by vasukulkarni** [comment]
@mmgaggle FYI, please review the versions, I will run test and post results

**Comment by vasukulkarni** [comment]
Some failures with v2.8.5 look genuine: http://qa-proxy.ceph.com/teuthology/vasu-2019-01-23_22:57:51-rgw:hadoop-s3a-luminous-distro-basic-ovh/3499094/teuthology.log

other hadoop versions I see have skipped the tests and just passed, looking if any of the Define is causing issues there. 
http://pulpito.ceph.com/vasu-2019-01-23_22:57:51-rgw:hadoop-s3a-luminous-distro-basic-ovh/

**Comment by vasukulkarni** [comment]
@cbodley yep that makes sense to me, thanks!

**Comment by cbodley** [comment]
thanks @vasukulkarni

**Pull request merged**
