### PR TITLE
doc: Replaced "disk or drive" by "disk" in ceph-disk.rs

### PR DESCRIPTION
**Pull request by Aeryax**
Fixes: #12062

Signed-off-by: Gabriel SENTUCQ <perso@kazhord.fr>

### CODE REVIEW

**Comment by dachary** [comment]
@Aeryax the modification looks good. Could you please format the commit message as instructed by https://github.com/ceph/ceph/blob/master/CONTRIBUTING.rst ?

**Comment by dachary** [comment]
@Aeryax could you please squash the three commits into one ?

**Comment by dachary** [comment]
@Aeryax almost good :-) The title should start with doc: and you can copy the title of the issue for clarity. When looking at the list of commits, "Fixes: #XXX" is not informative enough. Thanks !

**Comment by Aeryax** [comment]
It should be ok now

**Pull request merged**
