### PR TITLE
osd/OSD.cc: add 'isvalid=false' when failed to parse caps

### PR DESCRIPTION
**Pull request by gmayyyha**
Signed-off-by: Yanhu Cao <gmayyyha@gmail.com>

### CODE REVIEW

**Comment by gmayyyha** [comment]
@joscollin sorry for that. done.

**Comment by gmayyyha** [comment]
retest this please.

**Comment by gmayyyha** [comment]
retest this please

**Comment by gmayyyha** [comment]
@joscollin called by AsyncConnection
```
 0x55d1276d7e04 : OSD::ms_verify_authorizer(Connection*, int, int, ceph::buffer::list&, ceph::buffer::list&, bool&, CryptoKey&)+0x4c/0xba8 [/home/tiger/ceph/build/bin/ceph-osd]
 0x55d1280ca546 : Messenger::ms_deliver_verify_authorizer(Connection*, int, int, ceph::buffer::list&, ceph::buffer::list&, bool&, CryptoKey&)+0x96/0xfc [/home/tiger/ceph/build/bin/ceph-osd]
 0x55d128405775 : AsyncMessenger::verify_authorizer(Connection*, int, int, ceph::buffer::list&, ceph::buffer::list&, bool&, CryptoKey&)+0x4d/0x50 [/home/tiger/ceph/build/bin/ceph-osd]
 0x55d1283f7216 : AsyncConnection::handle_connect_msg(ceph_msg_connect&, ceph::buffer::list&, ceph::buffer::list&)+0x840/0x4408 [/home/tiger/ceph/build/bin/ceph-osd]
 0x55d1283f402c : AsyncConnection::_process_connection()+0x53d4/0x63b6 [/home/tiger/ceph/build/bin/ceph-osd]
 0x55d1283ee6ee : AsyncConnection::process()+0x5350/0x58ba [/home/tiger/ceph/build/bin/ceph-osd]
 0x55d1284059fd : C_handle_read::do_request(int)+0x27/0x2a [/home/tiger/ceph/build/bin/ceph-osd]
 0x55d1280eae2c : EventCenter::process_events(int, std::chrono::duration<unsigned long, std::ratio<1l, 1000000000l> >*)+0x6c4/0xcfc [/home/tiger/ceph/build/bin/ceph-osd]
 0x55d1280f1f07 : NetworkStack::add_thread(unsigned int)::{lambda()#1}::operator()() const+0x31f/0x586 [/home/tiger/ceph/build/bin/ceph-osd]
 0x55d1280f344e : std::_Function_handler<void (), NetworkStack::add_thread(unsigned int)::{lambda()#1}>::_M_invoke(std::_Any_data const&)+0x20/0x22 [/home/tiger/ceph/build/bin/ceph-osd]
 0x55d1277390c0 : std::function<void ()>::operator()() const+0x32/0x34 [/home/tiger/ceph/build/bin/ceph-osd]
 0x55d1280fbf80 : void std::_Bind_simple<std::function<void ()> ()>::_M_invoke<>(std::_Index_tuple<>)+0x28/0x2a [/home/tiger/ceph/build/bin/ceph-osd]
 0x55d1280fbec4 : std::_Bind_simple<std::function<void ()> ()>::operator()()+0x2a/0x40 [/home/tiger/ceph/build/bin/ceph-osd]
 0x55d1280fbe4e : std::thread::_Impl<std::_Bind_simple<std::function<void ()> ()> >::_M_run()+0x1c/0x1e [/home/tiger/ceph/build/bin/ceph-osd]
 0x7fd96a4dc230 : std::this_thread::__sleep_for(std::chrono::duration<long, std::ratio<1l, 1l> >, std::chrono::duration<long, std::ratio<1l, 1000000000l> >)+0x1c0/0x280 [/usr/lib64/libstdc++.so.6.0.19]
 0x7fd96ab51dc5 : start_thread+0xc5/0x300 [/usr/lib64/libpthread-2.17.so]
 0x7fd969c4576d : clone+0x6d/0x90 [/usr/lib64/libc-2.17.so]
```

**Comment by joscollin** [comment]
@gmayyyha Aah! `Dispatcher`. Sorry my bad.

**Comment by gmayyyha** [comment]
@joscollin fixed.

**Comment by joscollin** [comment]
retest this please

**Comment by joscollin** [comment]
@gregsfortytwo Yes, I will do. Just verifying the test result. Thanks.

**Comment by joscollin** [comment]
Success:

- http://pulpito.front.sepia.ceph.com/jcollin-2017-08-09_10:19:07-rados-wip-jcollin-testing_09-08-2017-distro-basic-smithi/
- 
- http://pulpito.front.sepia.ceph.com/compare/?branch=wip-jcollin-testing_09-08-2017&suite=rados

**Pull request merged**
