### PR TITLE
reef: mon, osd, *: expose upmap-primary in OSDMap::get_features() 

### PR DESCRIPTION
**Pull request by rzarzynski**
This is reef backport of #57776.
Backport tracker: https://tracker.ceph.com/issues/66299.
Parent tracker: https://tracker.ceph.com/issues/61948.

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Review by idryomov — COMMENTED** [review]
LGTM, although I was a bit surprised by the parent tracker getting moved to `Pending Backport` prior to merge.

I didn't mention this on the main PR since it doesn't strictly apply there, but we need a big release note for reef.  Do you want to handle it in this PR or defer to https://github.com/ceph/ceph/pull/56932?

**Comment by rzarzynski** [comment]
https://github.com/ceph/ceph/pull/56932 already needs to be altered. Let's piggy back on it.

Sorry for the surprise. I wanted to get the backport tickets. As this is `immediate`, doing QA in parallel.

**Comment by rzarzynski** [comment]
Looks unrelated:

```
1 tests failed out of 282

Total Test time (real) = 2446.96 sec

The following tests FAILED:
	228 - unittest_rgw_lua (Failed)
```

**Comment by rzarzynski** [comment]
jenkins test make check

**Review by idryomov — APPROVED** [review]

**Review by ljflores — APPROVED** [review]

**Comment by ljflores** [comment]
@rzarzynski since this was already QA'd, I'm going to merge it.

https://tracker.ceph.com/projects/rados/wiki/REEF#Build-5-from-httpstrackercephcomissues65393note-1

**Comment by ljflores** [comment]
@rzarzynski rather, I'll leave it to your judgement. But I've linked the QA results.

**Pull request merged**
