### PR TITLE
common/pick_address: fail if cannot bind with specified network family

### PR DESCRIPTION
**Pull request by tchaikov**
partially reverts #36536

Signed-off-by: Kefu Chai <kchai@redhat.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by tchaikov** [comment]
test fails.

**Review by batrick — APPROVED** [review]

**Comment by batrick** [comment]
````
[ RUN      ] pick_address.ipv4_ipv6_enabled_not_enough_networks
v1:10.1.1.2:0/0
/home/jenkins-build/build/workspace/ceph-pull-requests/src/test/test_ipaddr.cc:1007: Failure
Expected equality of these values:
  -1
  r
    Which is: 0
[  FAILED  ] pick_address.ipv4_ipv6_enabled_not_enough_networks (9 ms)
````

**Comment by tchaikov** [comment]
@matthewoliver hi Matthew, after a second thought, i think it'd be better to fail early if we cannot proceed with user's configuration.

**Comment by tchaikov** [comment]
jenkins test make check

**Comment by matthewoliver** [comment]
Yeah fair enough. Now that I think about it, it does sound a little problematic to potentially run in an user unexpected state. I mean it was warn and run.. fail might be better.
So long as we do

**Review by batrick — APPROVED** [review]

**Review by jdurgin — APPROVED** [review]
failing if the configuration can't be fulfilled sounds good to me

**Review by neha-ojha — APPROVED** [review]

**Comment by tchaikov** [comment]
- https://pulpito.ceph.com/kchai-2020-10-21_07:01:44-rados-wip-kefu-testing-2020-10-21-1144-distro-basic-smithi/
- https://pulpito.ceph.com/kchai-2020-10-22_03:25:39-rados-wip-kefu-testing-2020-10-21-2116-distro-basic-smithi/

**Pull request merged**
