### PR TITLE
pybind/mgr/cephadm/upgrade: allow upgrades without reducing max_mds

### PR DESCRIPTION
**Pull request by dparmar18**
Fixes: https://tracker.ceph.com/issues/55715

Signed-off-by: Dhairya Parmar <dparmar@redhat.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [x] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [x] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by dparmar18** [comment]
teuthology jobs passed - http://pulpito.front.sepia.ceph.com/dparmar-2022-07-13_12:25:42-fs:upgrade-wip-dparmar-cephadm-simple-1-distro-default-smithi/. Will try scheduling with patrick's suite now.

**Review by anthonyeleven — APPROVED** [review]
Docs LGTM, but this approval does not cover code.

**Comment by adk3798** [comment]
> code looks good I think

with the exception of failing mypy check 
```
cephadm/upgrade.py:25:1: E302 expected 2 blank lines, found 1
1     E302 expected 2 blank lines, found 1
ERROR: InvocationError for command /home/jenkins-build/build/workspace/ceph-pull-requests/src/pybind/mgr/.tox/flake8/bin/flake8 --config=tox.ini alerts balancer cephadm cli_api 
```

**Comment by dparmar18** [comment]
> > code looks good I think
> 
> with the exception of failing flake8 check
> 
> ```
> cephadm/upgrade.py:25:1: E302 expected 2 blank lines, found 1
> 1     E302 expected 2 blank lines, found 1
> ERROR: InvocationError for command /home/jenkins-build/build/workspace/ceph-pull-requests/src/pybind/mgr/.tox/flake8/bin/flake8 --config=tox.ini alerts balancer cephadm cli_api 
> ```

Added a blank line there, thanks.

**Comment by dparmar18** [comment]
jenkins test dashboard cephadm

**Comment by adk3798** [comment]
jenkins test make check

**Comment by adk3798** [comment]
jenkins test dashbord cephadm

**Comment by adk3798** [comment]
jenkinst test dashboard cephadm

**Comment by adk3798** [comment]
jenkins test dashboard cephadm

**Comment by adk3798** [comment]
jenkins test make check arm64

**Comment by adk3798** [comment]
https://pulpito.ceph.com/adking-2022-08-09_21:15:41-orch:cephadm-wip-adk2-testing-2022-08-09-1452-distro-default-smithi/

1 failure, transient infra thing, passed (3 times over) in rerun
https://pulpito.ceph.com/adking-2022-08-10_11:05:20-orch:cephadm-wip-adk2-testing-2022-08-09-1452-distro-default-smithi/

Additional 8 runs of new `upgrade_without_reducing_max_mds` tests https://pulpito.ceph.com/adking-2022-08-09_21:14:54-fs-wip-adk2-testing-2022-08-09-1452-distro-default-smithi/
All passed

**Comment by batrick** [comment]
@adk3798  This should not have been merged. It needs approval from CephFS team. I'm going through some results now.

**Comment by batrick** [comment]
Revert in https://github.com/ceph/ceph/pull/47732

**Pull request merged**
