### PR TITLE
rgw: drop misc unused set_attr

### PR DESCRIPTION
**Pull request by mikulely**
Signed-off-by: Jiaying Ren <jiaying.ren@umcloud.com>

### CODE REVIEW

**Comment by mikulely** [comment]
Jenkins, retest this please.

**Comment by theanalyst** [comment]
I was using this in https://github.com/ceph/ceph/pull/17305 which is currently waiting for some testing and another PR to merge

**Comment by theanalyst** [comment]
There is also a couple of places in code where set_attrs can be replaced by set_attr itself, (probably in putting object acls, tagging and similar apis that modify object xattrs) I suggest we keep it

**Comment by mikulely** [comment]
> There is also a couple of places in code where set_attrs can be replaced by set_attr itself

The `set_attrs` are using librados `rmxattr`, as the new bluestore didn't using file system attributes. Maybe `set_attrs` itself would be deprecated by setting`struct MetaParams` ?

**Comment by mikulely** [comment]
Jenkins, retest this please.

**Pull request closed without merging**
