### PR TITLE
Miscellaneous spec file fixes

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/12925
http://tracker.ceph.com/issues/12932
http://tracker.ceph.com/issues/13172
http://tracker.ceph.com/issues/13599

### CODE REVIEW

**Comment by smithfarm** [comment]
Just in case anyone is wondering, we had a large number of spec file fixes in master recently. They need to be backported, but backporting them individually is problematic (merge conflicts).

**Comment by dachary** [comment]
Conflicts when applied on top of #5788
<pre>
diff --cc ceph.spec.in
index 1e5a94c,0c9246d..0000000
--- a/ceph.spec.in
+++ b/ceph.spec.in
@@@ -8,18 -8,6 +8,21 @@@
  
  %{!?_udevrulesdir: %global _udevrulesdir /lib/udev/rules.d}
  
++<<<<<<< HEAD
 +# Use systemd files on RHEL 7 and above and in SUSE/openSUSE.
 +# Note: We don't install unit files for the services yet. For now,
 +# the _with_systemd variable only implies that we'll install
 +# /etc/tmpfiles.d/ceph.conf in order to set up the socket directory in
 +# /var/run/ceph.
 +%if 0%{?fedora} || 0%{?rhel} >= 7 || 0%{?suse_version} > 1300
 +%global _with_systemd 1
 +%endif
 +
 +#################################################################################
 +# common
 +#################################################################################
++=======
++>>>>>>> ceph/pull/5790/head
  Name:		ceph
  Version:	@VERSION@
  Release:	@RPM_RELEASE@%{?dist}
@@@ -29,9 -17,12 +32,12 @@@ License:	GPL-2.
  Group:		System Environment/Base
  URL:		http://ceph.com/
  Source0:	http://ceph.com/download/%{name}-%{version}.tar.bz2
 -%if 0%{?fedora} || 0%{?centos} || 0%{?rhel}
 +%if 0%{?fedora} || 0%{?rhel}
  Patch0:		init-ceph.in-fedora.patch
  %endif
+ #################################################################################
+ # dependencies that apply across all distro families
+ #################################################################################
  Requires:	librbd1 = %{epoch}:%{version}-%{release}
  Requires:	librados2 = %{epoch}:%{version}-%{release}
  Requires:	libcephfs1 = %{epoch}:%{version}-%{release}
@@@ -41,17 -32,15 +47,22 @@@ Requires:	python-rbd = %{epoch}:%{versi
  Requires:	python-cephfs = %{epoch}:%{version}-%{release}
  Requires:	python
  Requires:	python-requests
- Requires:	python-flask
+ Requires:	grep
  Requires:	xfsprogs
 +Requires:	logrotate
  Requires:	parted
  Requires:	util-linux
  Requires:	hdparm
  Requires:	cryptsetup
  Requires(post):	binutils
++<<<<<<< HEAD
 +# We require this to be present for %%{_tmpfilesdir}
 +%if 0%{?_with_systemd}
 +Requires: systemd
++=======
+ %if 0%{with cephfs_java}
+ BuildRequires: sharutils
++>>>>>>> ceph/pull/5790/head
</pre>

**Comment by smithfarm** [comment]
@dachary So, should I merge this one into #5788 and have just one big PR?

**Comment by dachary** [comment]
@smithfarm one big pr seems appropriate since they all deal with the same file really

**Comment by smithfarm** [comment]
@dachary: Ready to go.

**Comment by dachary** [comment]
@smithfarm looks like there are less conflicts, good work !

**Comment by dachary** [comment]
@smithfarm hammer-backports branch in the gitbuilders, with this pull request, are all good !

**Comment by smithfarm** [comment]
@dachary This PR could go into 0.94.5, then?

**Comment by dachary** [comment]
@smithfarm it is in http://tracker.ceph.com/issues/13356#note-1

**Comment by smithfarm** [comment]
rebased and cherry-picked 353a3258968f76deaea4542d2165e9ab32b88de8 on top

**Comment by dachary** [comment]
Without #6390 I get the following error:
<pre>
Checking for unpackaged file(s): /usr/lib/rpm/check-files /tmp/release/CentOS/WORKDIR/BUILDROOT/ceph-0.87.1-37.gffb76d1.el7.x86_64^M
error: Installed (but unpackaged) file(s) found:^M
   /usr/share/man/man8/rbd-replay-prep.8.gz^M
^M
^M
RPM build errors:^M
    Installed (but unpackaged) file(s) found:^M
   /usr/share/man/man8/rbd-replay-prep.8.gz^M
</pre>
would you mind cherry-picking the commit from #6390 into this pull request ?

**Comment by smithfarm** [comment]
@dachary Done

**Comment by dachary** [comment]
@smithfarm one more is needed because it conflicts : #6382

**Comment by smithfarm** [comment]
@dachary done

**Comment by dachary** [comment]
Testing  fixup https://github.com/dachary/ceph/commit/2266c83decf48c70f902238f9fd510fccfb1c774 for **packaging: move rbd-replay* to ceph-common** with

<pre>
teuthology-openstack --verbose --key-name myself  --key-filename ~/Downloads/myself --suite upgrade/hammer --suite-branch hammer --ceph hammer-backports-2 --ceph-git-url https://github.com/dachary/ceph.git --filter='upgrade:hammer/newer/{0-cluster/start.yaml 1-install/v0.94.4.yaml 2-workload/rbd.yaml 3-upgrade-sequence/upgrade-osd-mon-mds.yaml 4-final/{monthrash.yaml osdthrash.yaml testrgw.yaml} distros/ubuntu_14.04.yaml}'
</pre>

at

http://167.114.233.32:8081/ubuntu-2015-11-13_06:02:22-upgrade:hammer-hammer-backports-2---basic-openstack

**Comment by smithfarm** [comment]
@dachary updated `debian/control` as requested

**Comment by dachary** [comment]
@smithfarm thanks, test running at

<pre>
teuthology-openstack --verbose --key-name myself  --key-filename ~/Downloads/myself --suite upgrade/hammer --suite-branch hammer --ceph hammer-backports --ceph-git-url https://github.com/dachary/ceph.git --filter='upgrade:hammer/newer/{0-cluster/start.yaml 1-install/v0.94.4.yaml 2-workload/rbd.yaml 3-upgrade-sequence/upgrade-osd-mon-mds.yaml 4-final/{monthrash.yaml osdthrash.yaml testrgw.yaml} distros/ubuntu_14.04.yaml}'
</pre>

* *running* http://167.114.233.32:8081/ubuntu-2015-11-13_11:58:25-upgrade:hammer-hammer-backports---basic-openstack/

**Comment by dachary** [comment]
@smithfarm could you please update the commit message of 1c9201b to show details on the conflict resolution ?

**Comment by smithfarm** [comment]
@dachary Sure thing - done.

**Comment by dachary** [comment]
@smithfarm the test pass !

**Comment by dachary** [comment]
the upgrade suite for CentOS 7 pass ! http://167.114.233.32:8081/ubuntu-2015-11-19_14:48:00-upgrade:hammer-hammer-backports---basic-openstack/

**Comment by smithfarm** [comment]
Nice to get some good news :-)

**Pull request merged**
