### PR TITLE
nautilus: mgr/dashboard: Use booleanText pipe

### PR DESCRIPTION
**Pull request by alfonsomthd**
backport trackers:

* https://tracker.ceph.com/issues/44095
* https://tracker.ceph.com/issues/44174

backport of:

* https://github.com/ceph/ceph/pull/26733
* https://github.com/ceph/ceph/pull/33206

parent trackers:

* https://tracker.ceph.com/issues/44094
* https://tracker.ceph.com/issues/44075

### CODE REVIEW

**Comment by alfonsomthd** [comment]
@smithfarm @yuriw I want to apply a backport on top of this, so provided this backport is pretty trivial (and tiny), can we merge as it is ?

**Comment by smithfarm** [comment]
> I want to apply a backport on top of this, so provided this backport is pretty trivial (and tiny), can we merge as it is ?

Hi Alfonso, can't you just cherry-pick your new backport into this PR and manually update the PR description to mention it? Practice has shown that combining multiple backports in a single PR can be very useful.

**Comment by alfonsomthd** [comment]
> > I want to apply a backport on top of this, so provided this backport is pretty trivial (and tiny), can we merge as it is ?
> 
> Hi Alfonso, can't you just cherry-pick your new backport into this PR and manually update the PR description to mention it? Practice has shown that combining multiple backports in a single PR can be very useful.

@smithfarm Done.

**Comment by smithfarm** [comment]
jenkins test make check

**Comment by alfonsomthd** [comment]
jenkins test dashboard

**Comment by yuriw** [comment]
[wip-yuri4-testing-2020-03-11-1544-nautilus](https://trello.com/c/rPQZW9rB/841-wip-yuri4-testing-2020-03-11-1544-nautilus)

**Pull request merged**
