### PR TITLE
rgw deleting S3 objects leaves __shadow_ objects behind

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/11720

### CODE REVIEW

**Comment by smithfarm** [comment]
@yehudasa: could you look at this? The idea is to backport the fix for http://tracker.ceph.com/issues/10295 but that patch doesn't apply cleanly to firefly. Based on git blame I cherry-picked https://github.com/ceph/ceph/commit/350e06ddae23ce8ce1dfec39b088a81ef97b838b first.

**Comment by smithfarm** [comment]
Found this in the gitbuilder console log - looks like whatever wrote this error thought it was writing to a VT terminal screen? 
```
CXX      rgw/ceph_dencoder-rgw_acl.o
[01m[Krgw/rgw_main.cc:30:30:[m[K [01;31m[Kfatal error: [m[Kcommon/QueueRing.h: No such file or directory
 #include "common/QueueRing.h"
[01;32m[K                              ^[m[K
compilation terminated.
```

**Comment by smithfarm** [comment]
So I'm definitely missing https://github.com/ceph/ceph/commit/32b9bb7a2b031b3357600a2a405d1f18ac594546 in this pull request.

**Comment by dachary** [comment]
Yeah, the output of make check deserves cleanup for readability.

**Comment by smithfarm** [comment]
Closing here; the saga continues in https://github.com/ceph/ceph/pull/4780

**Pull request closed without merging**
