### PR TITLE
os/bluestore: avoid frequent and massive allocator's dump on bluefs rebalance failure

### PR DESCRIPTION
**Pull request by ifed01**
Signed-off-by: Igor Fedotov <ifedotov@suse.com>

### CODE REVIEW

**Comment by liewegas** [comment]
I wonder if, since this is an allocation we expect to fail, we shouldn't dump it *at all*.  Or, we can have an option bluestore_debug_rebalance_allocation_failure and only dump it then.  I'm worried about a prod OSD having a zillion of these in their log after a few weeks when it is not actually they should worry about.

**Comment by ifed01** [comment]
@liewegas - fixed. Now by default - no dump on allocation failure at all. Or periodic dump if non-zero interval is specified.

**Comment by liewegas** [comment]
@ifed01 should we prepare a luminous backport for this?

**Comment by ifed01** [comment]
@liewegas - I think so.

**Comment by smithfarm** [comment]
@ifed01 Looks like #18494 was backported via https://github.com/ceph/ceph/pull/21394 which went into 12.2.5

**Comment by smithfarm** [comment]
The backporting process is much easier to follow/manage when a tracker issue is created. Something for next time.

**Pull request merged**
