### PR TITLE
osd: fix epoch check in handle_pg_create

### PR DESCRIPTION
**Pull request by athanatos**

### CODE REVIEW

**Comment by athanatos** [comment]
DNM yet, something's wrong with the tests I ran

**Comment by athanatos** [comment]
Nvm, it's fine.  Tested in /a/samuelj-2016-03-29_21:23:46-rados-wip-sam-testing-distro-basic-smithi/

**Comment by athanatos** [comment]
Repushed to change the fixes: line.

**Comment by liewegas** [comment]
LGTM,  I was about to complain about Fixes.  :)

**Pull request merged**
