### PR TITLE
[DNM] ceph.spec.in: include SUSE in _with_systemd

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/11732

### CODE REVIEW

**Comment by dachary** [comment]
@smithfarm please ignore the bot false negative, it will be fixed by #5208

**Comment by dachary** [comment]
@smithfarm the fix was merged, could you please rebase & repush to trigger the bot once more ?

**Comment by dachary** [comment]
@smithfarm this needs rebasing

**Comment by smithfarm** [comment]
@dachary rebased

**Comment by smithfarm** [comment]
Closing in favor of #5788

**Pull request closed without merging**
