### PR TITLE
luminous ceph-volume: dmcrypt support for lvm

### PR DESCRIPTION
**Pull request by alfredodeza**
Backport of  #20054
Fixes: http://tracker.ceph.com/issues/22619

### CODE REVIEW

**Comment by alfredodeza** [comment]
jenkins test ceph-volume lvm

**Comment by alfredodeza** [comment]
jenkins test ceph-volume lvm all

**Comment by andrewschoen** [comment]
jenkins test ceph-volume tox

**Comment by leseb** [comment]
Asking the question again here: @alfredodeza, @andrewschoen does ceph-volume support zap for dmcrypt? Thanks.

**Comment by alfredodeza** [comment]
@leseb there are a couple of issues that are pending for zap to fully work with dmcrypt

**Comment by andrewschoen** [comment]
jenkins test ceph-volume tox

**Comment by andrewschoen** [comment]
jenkins test ceph-volume lvm all

**Comment by andrewschoen** [comment]
jenkins test ceph-volume lvm all

**Comment by andrewschoen** [comment]
jenkins test ceph-volume lvm all

**Comment by andrewschoen** [comment]
jenkins test ceph-volume lvm centos7-filestore-create

**Pull request merged**
