### PR TITLE
rpm: add "Provides: python3-*" for python packages and cleanup

### PR DESCRIPTION
**Pull request by tchaikov**
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by b-ranto** [comment]
btw: My local testing suggests that it should not be an issue if a `package-foo` provides `package-foo` of exactly the same version so this should be fine even if your `python3_pkgversion` resolves to `3`. I'll go ahead and merge this.

**Comment by yuriw** [comment]
@b-ranto @tchaikov  I still see failures http://pulpito.ceph.com/yuriw-2019-04-09_19:12:33-rados-wip-yuri4-testing-2019-04-09-1656-mimic-distro-basic-smithi/

**Comment by b-ranto** [comment]
@yuriw That is because teuthology is trying to install `python34-cephfs` (and similar) instead of `python3-cephfs`. We will probably need some other changes to make teuthology tests work. Since epel7 switched to `python36`, we build `python36-cephfs` by default and provide `python3-cephfs`.

btw: What build did you use? It looks like it is a mimic branch. Did it have this PR back-ported?

**Comment by yuriw** [comment]
@b-ranto I build in `ceph-ci` and yes it's on backported PRs

https://github.com/ceph/ceph/pull/27318 - mimic: include/intarith: enforce the same type for p2*() arguments
https://github.com/ceph/ceph/pull/27298 - mimic: os/bluestore: bitmap allocator might fail to return contiguous chunk despite having enough space
https://github.com/ceph/ceph/pull/27284 - mimic: osd/PGLog.h: print olog_can_rollback_to before deciding to rollback

**Pull request merged**
