### PR TITLE
qa/suites/rados/cephadm/upgrade: start from v15.2.6

### PR DESCRIPTION
**Pull request by mgfritch**
due to 76e5020b106e14284f63bd7cee81822ad6b1fbf0
move upgrade start point v15.2.0 -> v.15.2.6

Fixes  https://tracker.ceph.com/issues/48142
Signed-off-by: Michael Fritch <mfritch@suse.com>

## Blocked by

- [ ] #38530

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by mgfritch** [comment]
DNM: only after 15.2.6 octopus is released

**Comment by mgfritch** [comment]
jenkins test make check

**Comment by neha-ojha** [comment]
@sebastian-philipp We had some discussion on IRC the other day and decided this PR was the best way forward given https://tracker.ceph.com/issues/48142#note-3, would like to know your thoughts on this.

**Comment by sebastian-philipp** [comment]
Nope, not working:

```
2020-12-09T21:20:42.476 INFO:journalctl@ceph.mon.c.smithi191.stdout:Dec 09 21:20:41 smithi191 systemd[1]: Stopped Ceph mon.c for 12d8c8b6-3a64-11eb-9811-001a4aab830c.
2020-12-09T21:20:42.476 INFO:journalctl@ceph.mon.c.smithi191.stdout:Dec 09 21:20:41 smithi191 systemd[1]: Starting Ceph mon.c for 12d8c8b6-3a64-11eb-9811-001a4aab830c...
2020-12-09T21:20:42.476 INFO:journalctl@ceph.mon.c.smithi191.stdout:Dec 09 21:20:42 smithi191 podman[5741]: Error: no container with name or ID ceph-12d8c8b6-3a64-11eb-9811-001a4aab830c-mon.c found: no such container
2020-12-09T21:20:42.477 INFO:journalctl@ceph.mon.c.smithi191.stdout:Dec 09 21:20:42 smithi191 systemd[1]: Started Ceph mon.c for 12d8c8b6-3a64-11eb-9811-001a4aab830c.
2020-12-09T21:20:42.477 INFO:journalctl@ceph.mon.c.smithi191.stdout:Dec 09 21:20:42 smithi191 bash[5816]: Error: Failed to evict container: "": Failed to find container "ceph-12d8c8b6-3a64-11eb-9811-001a4aab830c-mon.c" in state: no container with name or ID ceph-12d8c8b6-3a64-11eb-9811-001a4aab830c-mon.c found: no such container
2020-12-09T21:20:42.477 INFO:journalctl@ceph.mon.c.smithi191.stdout:Dec 09 21:20:42 smithi191 bash[5816]: Error: no container with ID or name "ceph-12d8c8b6-3a64-11eb-9811-001a4aab830c-mon.c" found: no such container
2020-12-09T21:20:42.477 INFO:journalctl@ceph.mon.c.smithi191.stdout:Dec 09 21:20:42 smithi191 bash[5816]: Error: invalid config provided: CapAdd and privileged are mutually exclusive options
```

https://pulpito.ceph.com/swagner-2020-12-09_11:23:12-rados:cephadm-wip-swagner3-testing-2020-12-09-1003-distro-basic-smithi/

**Comment by sebastian-philipp** [comment]
blocked by #38530

**Pull request closed without merging**
