### PR TITLE
radosgw-admin: new 'global quota' commands update period config

### PR DESCRIPTION
**Pull request by cbodley**
global quota settings are stored in `RGWPeriodConfig` which is included in `RGWPeriod`, but `radosgw-admin` didn't expose any way to set them. and as part of the period, there was no way to use global quotas in a default non-multisite configuration where no period/realm exists

this patch set turns `RGWPeriodConfig` into a distinct rados object, so it can be used in the absence of a period configuration. when a period does exist, the `period update` and `period commit` commands handle this local period config object the same as local zone/zonegroup objects - `RGWPeriod::update()` reads the config object and stores it in the staging period, and `RGWPeriod::reflect()` writes the period's config to this local object

new `radosgw-admin` commands `period quota set/enable/disable` match the logic and arguments of the normal `quota set/enable/disable` commands. there's an additional `period quota get` command to query the current configuration

Fixes: http://tracker.ceph.com/issues/19409

### CODE REVIEW

**Comment by cbodley** [comment]
requesting feedback on naming of the commands. `period quota` or `realm quota` may be confusing for non-multisite configurations. `global quota` maybe?

**Comment by oritwas** [comment]
I agree `global quota` is clearer

**Comment by cbodley** [comment]
thanks @oritwas, updated commands and docs to use `global quota`

**Comment by cbodley** [comment]
passed rgw suite: http://pulpito.ceph.com/cbodley-2017-04-03_16:14:27-rgw-wip-cbodley-testing---basic-mira

**Pull request merged**
