### PR TITLE
luminous: rgw: Admin API Support for bucket quota change

### PR DESCRIPTION
**Pull request by mslovy**
http://tracker.ceph.com/issues/23357

### CODE REVIEW

**Comment by mslovy** [comment]
@smithfarm

**Comment by theanalyst** [comment]
missing 46b1186f144c0928394835301fc993d89598398b which was present in the original pr + docs change? Any reason why these do not make sense to be backported

**Comment by yuriw** [comment]
[wip-yuri-testing-2018-04-03-1559-luminous](https://trello.com/c/od7N8Ba6/283-wip-yuri-testing-2018-04-03-1559-luminous)

**Comment by mslovy** [comment]
thanks for you mention, I miss the other two and now added.

**Comment by smithfarm** [comment]
@yuriw Please don't merge this until it passes another run.

**Comment by yuriw** [comment]
@mslovy @theanalyst this is ready for merge

**Comment by smithfarm** [comment]
http://pulpito.ceph.com/yuriw-2018-04-05_16:29:31-rgw-wip-yuri-testing-2018-04-05-1501-luminous-distro-basic-smithi/

**Pull request merged**
