### PR TITLE
Rgw golang example

### PR DESCRIPTION
**Pull request by miracle1504**
Still refactoring my code. Created PR so that I can add to my application process on outreachy

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by miracle1504** [comment]
can you review @yuvalif

**Comment by anthonyeleven** [comment]
Did you mean to close this?

**Comment by ydv-sahitya** [comment]
> Did you mean to close this?

Hey sir, what's your Twitter handle or EMail. how can I contact you? I need some help.

**Comment by miracle1504** [comment]
> Did you mean to close this?

Yes I did. I made a mistake.

**Comment by miracle1504** [comment]
> Hey sir, what's your Twitter handle or EMail. how can I contact you? I need some help.

I'm a Woman. what challenge are you encountering? You could share them on the github gist. I'm happy to help.

**Comment by ydv-sahitya** [comment]
> > Hey sir, what's your Twitter handle or EMail. how can I contact you? I need some help.
> 
> I'm a Woman. what challenge are you encountering? You could share them on the github gist. I'm happy to help.

I man a man. hehe.  hi, what's your Twitter handle. or something else where I can text you. we can collaborate together? what do you say?

**Pull request closed without merging**
