### PR TITLE
luminous: ENOENT in collection_move_rename on EC backfill target

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/38880

### CODE REVIEW

**Comment by smithfarm** [comment]
@liewegas Is the idea to cherry-pick the "more complete fix" from https://github.com/ceph/ceph/pull/27015 into this backport PR? I tried, and there is a non-trivial cherry-pick conflict:

```
public:
  bool is_dirty() const {
<<<<<<< HEAD
    return !touched_log ||
=======
    return dirty_log ||
>>>>>>> 10d0990dc6... OSD: rollforward may need to mark pglog dirty
```

Also, the mimic and nautilus backports have already merged. Do we open new PRs targeting those branches?

**Comment by liewegas** [comment]
no idea, actually.. @neha-ojha ?

**Comment by neha-ojha** [comment]
> no idea, actually.. @neha-ojha ?

@smithfarm @liewegas I do not think we need to rush into backporting https://github.com/ceph/ceph/pull/27015 immediately. Let's open a separate tracker for it including the original tracker reference and mark it as pending backport.

**Comment by neha-ojha** [comment]
> > no idea, actually.. @neha-ojha ?
> 
> @smithfarm @liewegas I do not think we need to rush into backporting #27015 immediately. Let's open a separate tracker for it including the original tracker reference and mark it as pending backport.

http://tracker.ceph.com/issues/40403

**Comment by yuriw** [comment]
[wip-yuri3-testing-2019-07-10-1613-luminous](https://trello.com/c/jcT6CVxq/662-wip-yuri3-testing-2019-07-10-1613-luminous)

**Pull request merged**
