### PR TITLE
rgw/multisite: avoid redundant error repo entry logging

### PR DESCRIPTION
**Pull request by smanjara**
## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Review by adamemerson — APPROVED** [review]
LGTM, but could you please change the commit message to something like:

```
rgw/multisite: avoid redundant error repo entry logging

in bucket incremental sync, if a generation other than the current generation is requested,
we mark it with -EAGAIN and retry in error repo in RGWDataSyncSingleEntry(). within this block, we check
if that requested generation is lesser than the current gen, write it to error repo, set -EAGAIN and write
it to error repo in the outer function once again. don't duplicate error repo entry addition for this condition.

Signed-off-by: Shilpa Jagannath <smanjara@redhat.com>
```

A lot of git tools assume commit messages will have a 50–60 character subject line (so there's room for hashes and stuff) and 72-character (so there's room for `>` marks for email quoting) body after a blank.

**Comment by cbodley** [comment]
passed qa in https://pulpito.ceph.com/cbodley-2024-09-25_19:45:24-rgw-wip-cbodley-testing-distro-default-smithi/ with rerun https://pulpito.ceph.com/cbodley-2024-09-26_12:41:47-rgw-wip-cbodley-testing-distro-default-smithi/

**Comment by cbodley** [comment]
> LGTM, but could you please change the commit message to something like:

@smanjara could you please address Adam's review comment?

**Comment by smanjara** [comment]
> > LGTM, but could you please change the commit message to something like:
> 
> @smanjara could you please address Adam's review comment?

sorry, done.

**Comment by cbodley** [comment]
jenkins test make check

**Comment by cbodley** [comment]
jenkins test windows

**Comment by smanjara** [comment]
jenkins test make check

**Pull request merged**
