### PR TITLE
mgr/dashboard: rbd mirroring status page

### PR DESCRIPTION
**Pull request by dillaman**
_TODO_
- [x] dynamically generated nav bar error/warning counts
- [x] ~allow admin to optionally see error/warning callouts~

### CODE REVIEW

**Comment by dillaman** [comment]
screenshot from 2017-07-17 01-48-28
screenshot from 2017-07-17 01-48-35
screenshot from 2017-07-17 01-48-41

**Comment by jcsp** [comment]
Very cool!

**Comment by dillaman** [comment]
@jcsp still need to dynamically populate the nav bar warning/error counts and I would love to figure out a good way to display the daemon error/warning callouts. I wanted to have the tables dynamically expand by a row when you click an expand icon in a given daemon row, but requires additional JS-fu.

**Comment by liewegas** [comment]
awesome

**Comment by jcsp** [comment]
@dillaman want to merge this or https://github.com/ceph/ceph/pull/16468 first?  I'm guessing they conflict

**Comment by dillaman** [comment]
@jcsp This one first, please -- if they conflict, I can manually resolve the other and merge.

**Pull request merged**
