### PR TITLE
pybind/rados: fix missed changes for PEP484 style type annotations

### PR DESCRIPTION
**Pull request by ifed01**
originally brought by https://github.com/ceph/ceph/pull/36918

As a result improper (unicode string is assigned with byte one) assignment causes assertion in Ioctx.get_omap_keys (defined at src/pybind/rados/rados.pyx) when start_after parameter is non-empty. AFAIU this is bound specifically to Cython since pure Python apparently permits such assignments

Fixes: https://tracker.ceph.com/issues/58304
Signed-off-by: Igor Fedotov <igor.fedotov@croit.io>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [x] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [x] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by rzarzynski** [comment]
@ifed01: I'm having an impression the commit's title doesn't fit the bug referenced by the `Fixes` tag. Could you please ensure there is no an editorial problem?

**Comment by ifed01** [comment]
> @ifed01: I'm having an impression the commit's title doesn't fit the bug referenced by the `Fixes` tag. Could you please ensure there is no an editorial problem?

@rzarzynski - I updated the PR's description to overview the relation between the PR and the ticket. Please let me know if that's not enough..

**Comment by tchaikov** [comment]
sorry for the latency. will review this change in this weekend.

**Comment by ifed01** [comment]
@tchaikov - ping

**Review by tchaikov — APPROVED** [review]

**Comment by ifed01** [comment]
Hey @yuriw,
can we queue this PR for QA run any time soon? Apparently it has been missed...

**Comment by rzarzynski** [comment]
jenkins retest this please

**Comment by rzarzynski** [comment]
@ljflores, @yuriw: would mind taking this into a testing branch?

**Comment by ifed01** [comment]
jenkins test make check

**Comment by ljflores** [comment]
@ifed01 yes, it will go in testing. I usually pick up only PRs with the "core" label, so I added it to make sure I pick it up.

**Comment by ljflores** [comment]
Rados approved: https://tracker.ceph.com/projects/rados/wiki/REEF#httpstrellocomcT9bt0Ezq1871-wip-yuri4-testing-2023-10-31-1447-old-wip-yuri4-testing-2023-10-30-1117-old-wip-yuri4-testing-2023-10-27-1200-old-wip-yuri4-test

**Comment by yuriw** [comment]
jenkins test api

**Comment by yuriw** [comment]
@ifed01 pls merge when checks passed
ref: https://trello.com/c/T9bt0Ezq

**Pull request merged**
