### PR TITLE
qa/suites/upgrade/kraken-x

### PR DESCRIPTION
**Pull request by liewegas**

### CODE REVIEW

**Comment by liewegas** [comment]
http://pulpito.ceph.com/sage-2017-02-18_19:27:07-upgrade:kraken-x-master---basic-smithi/

The failure appears to be the thrasher bug where it didn't finish restoring pgp_num... @tchaikov i think you submitted a fix for that, right?

**Comment by liewegas** [comment]
@yuriw

**Comment by tchaikov** [comment]
@liewegas right, in de59b5102c547c093d07d8e7c671b47312063685. did you suite branch contains that commit, seems wip-kraken-x (0a2d15d8b32141d895d0b32d9c31b0c6730b1a82) is removed.

**Comment by tchaikov** [comment]
@liewegas fixed at #13518

**Comment by yuriw** [comment]
@liewegas @tchaikov trying this run http://pulpito.front.sepia.ceph.com:80/yuriw-2017-02-19_16:16:24-upgrade:kraken-x-luminous-distro-basic-smithi/

**Pull request merged**
