### PR TITLE
pacific: monitoring/grafana: Grafana query tester 

### PR DESCRIPTION
**Pull request by avanthakkar**
backport tracker: https://tracker.ceph.com/issues/53296
backport tracker: https://tracker.ceph.com/issues/53602

---

backport of https://github.com/ceph/ceph/pull/43669
backport of https://github.com/ceph/ceph/pull/44163

parent tracker: https://tracker.ceph.com/issues/53211
parent tracker: https://tracker.ceph.com/issues/53451

this backport was staged using ceph-backport.sh version 16.0.0.6848
find the latest version at https://github.com/ceph/ceph/blob/master/src/script/ceph-backport.sh

### CODE REVIEW

**Review by pereman2 — APPROVED** [review]
Thanks!!

**Comment by avanthakkar** [comment]
jenkins test dashboard cephadm

**Comment by avanthakkar** [comment]
jenkins test dashboard

**Review by aaSharma14 — APPROVED** [review]

**Review by alfonsomthd — APPROVED** [review]

**Review by nizamial09 — APPROVED** [review]

**Comment by epuertat** [comment]
@avanthakkar I cherrypicked https://github.com/ceph/ceph/pull/44163 so that we don't break the ARM build.

**Review by epuertat — APPROVED** [review]

**Pull request merged**
