### PR TITLE
qa/workunits/rados/test_crash: chown crash files to ceph user

### PR DESCRIPTION
**Pull request by tserong**
This PR also makes ceph-crash log a warning if it can't read any of the crash directories.

Fixes: https://tracker.ceph.com/issues/58098

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [x] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by ljflores** [comment]
jenkins test make check

**Review by ljflores — APPROVED** [review]
It seems reasonable to me. If it was only a change to the workunit, I would say that just that one test would be sufficient, but since there is a change to src, it won't hurt to put it through the full rados suite.

**Comment by tserong** [comment]
jenkins test make check

**Comment by tserong** [comment]
No problem @ljflores :-)

**Comment by tserong** [comment]
hrm ... not having much luck with make check here

**Comment by tserong** [comment]
jenkins test make check

**Comment by tserong** [comment]
alright, looks like I got lucky ;-)

**Comment by tchaikov** [comment]
yup, it was fixed this morning.

**Comment by ljflores** [comment]
Rados suite review: https://pulpito.ceph.com/?branch=wip-yuri2-testing-2023-01-23-0928

Failures, unrelated:
    1. https://tracker.ceph.com/issues/58585 -- new tracker
    2. https://tracker.ceph.com/issues/58256 -- fix merged to latest main
    3. https://tracker.ceph.com/issues/58475
    4. https://tracker.ceph.com/issues/57754 -- closed
    5. https://tracker.ceph.com/issues/57546 -- fix is in testing

Details:
    1. rook: failed to pull kubelet image - Ceph - Orchestrator
    2. ObjectStore/StoreTestSpecificAUSize.SpilloverTest/2: Expected: (logger->get(l_bluefs_slow_used_bytes)) >= (16 * 1024 * 1024), actual: 0 vs 16777216 - Ceph - RADOS
    3. test_dashboard_e2e.sh: Conflicting peer dependency: postcss@8.4.21 - Ceph - Mgr - Dashboard
    4. test_envlibrados_for_rocksdb.sh: update-alternatives: error: alternative path /usr/bin/gcc-11 doesn't exist - Ceph - RADOS
    5. rados/thrash-erasure-code: wait_for_recovery timeout due to "active+clean+remapped+laggy" pgs - Ceph - RADOS

**Pull request merged**
