### PR TITLE
osd: don't share osdmap with objecter when preboot

### PR DESCRIPTION
**Pull request by LiumxNL**
Fixes: http://tracker.ceph.com/issues/15025

Signed-off-by: Mingxin Liu <mingxin@xsky.com>

### CODE REVIEW

**Comment by LiumxNL** [comment]
#8080

**Comment by LiumxNL** [comment]
#8080 doesn't work after Hammer
when osd's epoch far bebind cluster osdmap epoch, and osdmap has full set or pool reach quota, this osd cannot boot succuessfully

**Comment by LiumxNL** [comment]
@tchaikov @liewegas pls review. thanks!

**Comment by yuriw** [comment]
http://pulpito.front.sepia.ceph.com:80/yuriw-2017-03-16_15:10:12-rados-wip-yuri-testing_2017_3_16-distro-basic-smithi/

http://pulpito.ceph.com/yuriw-2017-03-16_19:57:54-rados-wip-yuri-testing_2017_3_16---basic-smithi/

http://pulpito.ceph.com/yuriw-2017-03-17_15:28:50-rados-wip-yuri-testing_2017_3_16---basic-smithi/

**Comment by smithfarm** [comment]
@liewegas Should this be backported? To which stable releases?

**Comment by liewegas** [comment]
just kraken and jewel, i think!

**Pull request merged**
