### PR TITLE
DNM Bluestore: Fixed a race condition and a probable crash

### PR DESCRIPTION
**Pull request by somnathr**
Needed to add a new RWLock to protect blob structures.

Signed-off-by: Somnath Roy <somnath.roy@sandisk.com>

### CODE REVIEW

**Comment by somnathr** [comment]
@markhpc Could you please try this and see if it is solving your onode->flush crash ?
I couldn't reproduce this single time in my setup , so, can't guarantee. But, there is a probable cause fixed because within _osr_reap_done , the cache trim is been called without any c->lock.
This should fix the deadlock reported by Jianpeng because of https://github.com/ceph/ceph/pull/10220
Patch is passing all my test and the objecstore test as well, but, since I couldn't able to reproduce either of the problem need your help to verify.

**Comment by markhpc** [comment]
Yep, will try this now!

**Comment by somnathr** [comment]
@markhpc FYI, Jianpeng reported back that the deadlock issue he was seeing is resolved with this PR.

**Comment by markhpc** [comment]
Hi Somnath,

Went through 8 CBT runs using the bitmap allocator with 4K random writes which is quite a bit farther than I was making it before.  I did eventually hit this:

`2016-08-09 21:09:00.894423 7f374603b700 -1 *** Caught signal (Aborted) **
 in thread 7f374603b700 thread_name:tp_osd_tp

 ceph version v11.0.0-1378-g752ab4c (752ab4c049a556b089901093b711f06fbd8bccab)
 1: /usr/local/bin/ceph-osd() [0xbf3f8a]
 2: (()+0xf100) [0x7f3763453100]
 3: (gsignal()+0x37) [0x7f37622725f7]
 4: (abort()+0x148) [0x7f3762273ce8]
 5: (ceph::__ceph_assert_fail(char const*, char const*, int, char const*)+0x267) [0xd6a147]
 6: /usr/local/bin/ceph-osd() [0x6c8cb4]
 7: (BlueStore::_do_alloc_write(BlueStore::TransContext*, BlueStore::WriteContext*)+0x176a) [0xaffaaa]
 8: (BlueStore::_do_write(BlueStore::TransContext*, boost::intrusive_ptr<BlueStore::Collection>&, boost::intrusive_ptr<BlueStore::Onode>, unsigned long, unsigned long, ceph::buffer::list&, unsigned i
nt)+0x391) [0xb21f01]
 9: (BlueStore::_write(BlueStore::TransContext*, boost::intrusive_ptr<BlueStore::Collection>&, boost::intrusive_ptr<BlueStore::Onode>&, unsigned long, unsigned long, ceph::buffer::list&, unsigned int
)+0x10f) [0xb22adf]
 10: (BlueStore::_txc_add_transaction(BlueStore::TransContext*, ObjectStore::Transaction*)+0x1471) [0xb272a1]
 11: (BlueStore::queue_transactions(ObjectStore::Sequencer*, std::vector<ObjectStore::Transaction, std::allocator<ObjectStore::Transaction> >&, std::shared_ptr<TrackedOp>, ThreadPool::TPHandle*)+0x41
a) [0xb28e5a]
 12: (ReplicatedPG::queue_transactions(std::vector<ObjectStore::Transaction, std::allocator<ObjectStore::Transaction> >&, std::shared_ptr<OpRequest>)+0x8c) [0x90e0cc]
 13: (ReplicatedBackend::submit_transaction(hobject_t const&, eversion_t const&, std::unique_ptr<PGBackend::PGTransaction, std::default_delete<PGBackend::PGTransaction> >&&, eversion_t const&, eversi
on_t const&, std::vector<pg_log_entry_t, std::allocator<pg_log_entry_t> > const&, boost::optional<pg_hit_set_history_t>&, Context*, Context*, Context*, unsigned long, osd_reqid_t, std::shared_ptr<OpR
equest>)+0x94d) [0x9d5efd]
 14: (ReplicatedPG::issue_repop(ReplicatedPG::RepGather*, ReplicatedPG::OpContext*)+0x7ac) [0x89be1c]
 15: (ReplicatedPG::execute_ctx(ReplicatedPG::OpContext*)+0x1708) [0x8ee058]
 16: (ReplicatedPG::do_op(std::shared_ptr<OpRequest>&)+0x2810) [0x8f1340]
 17: (ReplicatedPG::do_request(std::shared_ptr<OpRequest>&, ThreadPool::TPHandle&)+0x777) [0x8af457]
 18: (OSD::dequeue_op(boost::intrusive_ptr<PG>, std::shared_ptr<OpRequest>, ThreadPool::TPHandle&)+0x41d) [0x75fc0d]
 19: (PGQueueable::RunVis::operator()(std::shared_ptr<OpRequest> const&)+0x6d) [0x75fe5d]
 20: (OSD::ShardedOpWQ::_process(unsigned int, ceph::heartbeat_handle_d*)+0x73f) [0x78125f]
 21: (ShardedThreadPool::shardedthreadpool_worker(unsigned int)+0x947) [0xd6fbd7]
 22: (ShardedThreadPool::WorkThreadSharded::entry()+0x10) [0xd71d30]
 23: (()+0x7dc5) [0x7f376344bdc5]
 24: (clone()+0x6d) [0x7f376233328d]
 NOTE: a copy of the executable, or `objdump -rdS <executable>` is needed to interpret this.

--- begin dump of recent events ---
     0> 2016-08-09 21:09:00.894423 7f374603b700 -1 *** Caught signal (Aborted) **
 in thread 7f374603b700 thread_name:tp_osd_tp

 ceph version v11.0.0-1378-g752ab4c (752ab4c049a556b089901093b711f06fbd8bccab)
 1: /usr/local/bin/ceph-osd() [0xbf3f8a]
 2: (()+0xf100) [0x7f3763453100]
 3: (gsignal()+0x37) [0x7f37622725f7]
 4: (abort()+0x148) [0x7f3762273ce8]
 5: (ceph::__ceph_assert_fail(char const*, char const*, int, char const*)+0x267) [0xd6a147]
 6: /usr/local/bin/ceph-osd() [0x6c8cb4]
 7: (BlueStore::_do_alloc_write(BlueStore::TransContext*, BlueStore::WriteContext*)+0x176a) [0xaffaaa]
 8: (BlueStore::_do_write(BlueStore::TransContext*, boost::intrusive_ptr<BlueStore::Collection>&, boost::intrusive_ptr<BlueStore::Onode>, unsigned long, unsigned long, ceph::buffer::list&, unsigned i
nt)+0x391) [0xb21f01]
 9: (BlueStore::_write(BlueStore::TransContext*, boost::intrusive_ptr<BlueStore::Collection>&, boost::intrusive_ptr<BlueStore::Onode>&, unsigned long, unsigned long, ceph::buffer::list&, unsigned int
)+0x10f) [0xb22adf]
 10: (BlueStore::_txc_add_transaction(BlueStore::TransContext*, ObjectStore::Transaction*)+0x1471) [0xb272a1]
 11: (BlueStore::queue_transactions(ObjectStore::Sequencer*, std::vector<ObjectStore::Transaction, std::allocator<ObjectStore::Transaction> >&, std::shared_ptr<TrackedOp>, ThreadPool::TPHandle*)+0x41
a) [0xb28e5a]
 12: (ReplicatedPG::queue_transactions(std::vector<ObjectStore::Transaction, std::allocator<ObjectStore::Transaction> >&, std::shared_ptr<OpRequest>)+0x8c) [0x90e0cc]
 13: (ReplicatedBackend::submit_transaction(hobject_t const&, eversion_t const&, std::unique_ptr<PGBackend::PGTransaction, std::default_delete<PGBackend::PGTransaction> >&&, eversion_t const&, eversi
on_t const&, std::vector<pg_log_entry_t, std::allocator<pg_log_entry_t> > const&, boost::optional<pg_hit_set_history_t>&, Context*, Context*, Context*, unsigned long, osd_reqid_t, std::shared_ptr<OpR
equest>)+0x94d) [0x9d5efd]
 14: (ReplicatedPG::issue_repop(ReplicatedPG::RepGather*, ReplicatedPG::OpContext*)+0x7ac) [0x89be1c]
 15: (ReplicatedPG::execute_ctx(ReplicatedPG::OpContext*)+0x1708) [0x8ee058]
 16: (ReplicatedPG::do_op(std::shared_ptr<OpRequest>&)+0x2810) [0x8f1340]
 17: (ReplicatedPG::do_request(std::shared_ptr<OpRequest>&, ThreadPool::TPHandle&)+0x777) [0x8af457]
 18: (OSD::dequeue_op(boost::intrusive_ptr<PG>, std::shared_ptr<OpRequest>, ThreadPool::TPHandle&)+0x41d) [0x75fc0d]
 19: (PGQueueable::RunVis::operator()(std::shared_ptr<OpRequest> const&)+0x6d) [0x75fe5d]
 20: (OSD::ShardedOpWQ::_process(unsigned int, ceph::heartbeat_handle_d*)+0x73f) [0x78125f]
 21: (ShardedThreadPool::shardedthreadpool_worker(unsigned int)+0x947) [0xd6fbd7]
 22: (ShardedThreadPool::WorkThreadSharded::entry()+0x10) [0xd71d30]
 23: (()+0x7dc5) [0x7f376344bdc5]
 24: (clone()+0x6d) [0x7f376233328d]
 NOTE: a copy of the executable, or `objdump -rdS <executable>` is needed to interpret this.

--- logging levels ---
   0/ 5 none
   0/ 0 lockdep
   0/ 0 context
   0/ 0 crush
   0/ 0 mds
   0/ 0 mds_balancer
   0/ 0 mds_locker
   0/ 0 mds_log
   0/ 0 mds_log_expire
   0/ 0 mds_migrator
   0/ 0 buffer
   0/ 0 timer
   0/ 0 filer
   0/ 1 striper
   0/ 0 objecter
   0/ 0 rados
   0/ 0 rbd
   0/ 5 rbd_mirror
   0/ 5 rbd_replay
   0/ 0 journaler
   0/ 0 objectcacher
   0/ 0 client
   0/ 0 osd
   0/ 0 optracker
   0/ 0 objclass
   0/ 0 filestore
   0/ 0 journal
   0/ 0 ms
   0/ 0 mon
   0/ 0 monc
   0/ 0 paxos
   0/ 0 tp
   0/ 0 auth
   1/ 5 crypto
   0/ 0 finisher
   0/ 0 heartbeatmap
   0/ 0 perfcounter
   0/ 0 rgw
   1/10 civetweb
   1/ 5 javaclient
   0/ 0 asok
   0/ 0 throttle
   0/ 0 refs
   1/ 5 xio
   1/ 5 compressor
   1/ 5 newstore
   0/ 0 bluestore
   0/ 0 bluefs
   0/ 0 bdev
   1/ 5 kstore
   4/ 5 rocksdb
   4/ 5 leveldb
   4/ 5 memdb
   1/ 5 kinetic
   1/ 5 fuse
  -2/-2 (syslog threshold)
  -1/-1 (stderr threshold)
  max_recent     10000
  max_new         1000
  log_file /tmp/cbt/ceph/log/osd.11.log
--- end dump of recent events ---
`

**Comment by somnathr** [comment]
@markhpc This could be the allocator issue we faced earlier.
Could you please scroll up in the log and give me the exact assert it is hitting ?

**Comment by markhpc** [comment]
oops, I thought I had grabbed more of that than I did.  Here's teh whole log from that OSD.
[osd.11.log.gz](https://github.com/ceph/ceph/files/411015/osd.11.log.gz)

**Comment by liewegas** [comment]
I'm pretty sure this is resolved by Igor's fix.

**Pull request closed without merging**
