### PR TITLE
qa/cephfs: fix ior build failure

### PR DESCRIPTION
**Pull request by rishabh-d-dave**
Fixes: https://tracker.ceph.com/issues/61399

- [ ] delete old tar from download.ceph.com/qa if new one begins working successfully

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by rishabh-d-dave** [comment]
The current patch (using latest CentOS instead of latest Ubuntu) was suggested by Venky. I re-ran the test and found that this doesn't work. `make` fails with a different error now. So I am trying a different workaround.

**Comment by rishabh-d-dave** [comment]
Building and installing ior on Ubuntu 22.04 from latest tar.bz2 file was successful. So I am trying the same for teuthology run now.

**Comment by vshankar** [comment]
@rishabh-d-dave Please run the changes through qa when ready.

**Comment by rishabh-d-dave** [comment]
> @rishabh-d-dave Please run the changes through qa when ready.

I have been running it through QA, but it's not ready for a final integration test run. Apparently Ubuntu 2.04 in Sepia lab is behaving differently than it does in VM.

**Comment by rishabh-d-dave** [comment]
https://pulpito.ceph.com/rishabh-2023-07-27_12:00:33-fs:multiclient-wip-rishabh-2023Jul13-testing-default-smithi/

**Comment by rishabh-d-dave** [comment]
http://pulpito.front.sepia.ceph.com/rishabh-2023-08-04_21:04:10-fs:multiclient-wip-rishabh-2023aug3-testing-default-smithi/

**Comment by rishabh-d-dave** [comment]
https://pulpito.ceph.com/rishabh-2023-08-05_09:19:23-fs:multiclient-wip-rishabh-2023aug3-testing-default-smithi

**Comment by rishabh-d-dave** [comment]
The current problem is that configure script from ior projects fails with following messages -

```
checking whether mpicc understands -c and -o together... yes
checking dependency style of mpicc... gcc3
checking for function MPI_Init... no
checking for function MPI_Init in -lmpi... no
checking for function MPI_Init in -lmpich... no    
configure: error: in `/home/ubuntu/cephtest/ior-3.3.0':
configure: error: MPI compiler requested, but could not use MPI.               
See `config.log' for more details 
```

This is not the case with Ubuntu VM I have locally. I upgraded all packges on the VM OS before installing MPI and dependencies. I don't think teuthology VM is upgraded so maybe this is the cause of the issue.

**Comment by rishabh-d-dave** [comment]
https://pulpito.ceph.com/rishabh-2023-08-10_12:05:26-fs:multiclient-wip-rishabh-2023aug3-testing-default-smithi

**Comment by rishabh-d-dave** [comment]
https://pulpito.ceph.com/rishabh-2023-08-10_12:02:00-fs:multiclient-wip-rishabh-2023aug3-testing-default-smithi

**Comment by rishabh-d-dave** [comment]
https://pulpito.ceph.com/rishabh-2023-08-10_12:05:26-fs:multiclient-wip-rishabh-2023aug3-testing-default-smithi

**Comment by rishabh-d-dave** [comment]
https://pulpito.ceph.com/rishabh-2023-08-10_13:01:59-fs:multiclient-wip-rishabh-2023aug3-testing-default-smithi/

**Comment by rishabh-d-dave** [comment]
> https://pulpito.ceph.com/rishabh-2023-08-10_13:01:59-fs:multiclient-wip-rishabh-2023aug3-testing-default-smithi/

Finally the test passed.

**Comment by rishabh-d-dave** [comment]
https://pulpito.ceph.com/rishabh-2023-08-10_20:28:01-fs:multiclient-wip-rishabh-2023aug3-b4-testing-default-smithi/

**Comment by rishabh-d-dave** [comment]
Squashed all the commits to delete all code meant to aid debugging and get one final commit.

**Comment by rishabh-d-dave** [comment]
https://pulpito.ceph.com/rishabh-2023-08-10_20:28:01-fs:multiclient-wip-rishabh-2023aug3-b4-testing-default-smithi/

**Comment by rishabh-d-dave** [comment]
> https://pulpito.ceph.com/rishabh-2023-08-10_20:28:01-fs:multiclient-wip-rishabh-2023aug3-b4-testing-default-smithi/

All tests passed.

**Comment by vshankar** [comment]
> > https://pulpito.ceph.com/rishabh-2023-08-10_13:01:59-fs:multiclient-wip-rishabh-2023aug3-testing-default-smithi/
> 
> Finally the test passed.Next running: all variants of ior tests.

Nice. What was the issue btw?

**Comment by rishabh-d-dave** [comment]
Now checking if subset of changes can fix this issue.

**Comment by rishabh-d-dave** [comment]
> > > https://pulpito.ceph.com/rishabh-2023-08-10_13:01:59-fs:multiclient-wip-rishabh-2023aug3-testing-default-smithi/
> > 
> > 
> > Finally the test passed.Next running: all variants of ior tests.
> 
> Nice. What was the issue btw?

Either mpich packages or ior version or both.

**Comment by rishabh-d-dave** [comment]
@vshankar 
> > > https://pulpito.ceph.com/rishabh-2023-08-10_13:01:59-fs:multiclient-wip-rishabh-2023aug3-testing-default-smithi/
> > 
> > 
> > Finally the test passed.Next running: all variants of ior tests.
> 
> Nice. What was the issue btw?

Either mpich packages or ior version or both.

**Review by vshankar — APPROVED** [review]

**Comment by vshankar** [comment]
jenkins test api

**Comment by rishabh-d-dave** [comment]
https://github.com/ceph/ceph/compare/07586429423ae5481772a2f2d0dcaaadd48ae687..e5ff7e1f90b45d77e3a21de39e5fa6285c75b6a5

**Pull request merged**
