### PR TITLE
osd/OSDMap.cc: fix dup assignment for new_blacklist_entries

### PR DESCRIPTION
**Pull request by KerLiu**
Signed-off-by: Ker Liu kerliu818@gmail.com

### CODE REVIEW

**Comment by tchaikov** [comment]
could you remove the merge commit from your pull request?

**Comment by KerLiu** [comment]
@tchaikov 
Sorry, this is the first time I submit code into github project, I didn't find the way to remove the merge commit from my pull request, could you please give me some suggestions?
Below is my procedure to submit this code change:
--------------
1.  fork ceph
2.  in my kerliu/ceph, update the code
3. create a pull request
4. merge pull request and confirm merge in my kerliu/ceph
5. in my master branch, create a new pull request
-------------
it seems I have created pull request twice.

**Comment by tchaikov** [comment]
you should skip step 3, and just create the pull request from the remote branch where you update the code instead.
and now, you can simply "git push -f" the updated code to your master branch. next time, i'd suggest you work on another branch instead of your master, and name it with a name which is more related  to what the change is for.

**Comment by KerLiu** [comment]
Thanks for your response.
I didn't use git bash for this submit, so I can't run "git push -f".
Is there any solution to fix it from github webpage?  Next time I will use git bash to submit code.

**Comment by KerLiu** [comment]
Or please abandon this pull request, I will use git bash to submit it again.

**Comment by tchaikov** [comment]
> Is there any solution to fix it from github webpage?

no, AFAICT.

**Pull request closed without merging**
