### PR TITLE
cmake: set WITH_FMT_VERSION as a STRING option

### PR DESCRIPTION
**Pull request by tchaikov**
option() defines a boolean, so its default value cannot be populated to find_package() as expected. so we need to set it as a cached STRING variable.

this addresses the regression introduced by 051ec194df16927187cbe4b26dacd06c31fa186a

Signed-off-by: Kefu Chai <tchaikov@gmail.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by tchaikov** [comment]
https://shaman.ceph.com/builds/ceph/wip-cmake-with-fmt-version/0d41777cea1720cdf3fc54e182325b4440b08d40/

**Review by mkogan1 — APPROVED** [review]
LGTM, 
for future reference - it fixes the error:
```
CMake Error at src/CMakeLists.txt:325 (find_package):                                                                                                                     
  find_package called with invalid argument "OFF"  
```

until merged `cmake ./build -DWITH_FMT_VERSION="7.0.0"` is a workaround

**Comment by tchaikov** [comment]
jenkins test make check

**Comment by tchaikov** [comment]
jenkins test api

**Comment by tchaikov** [comment]
```
The following tests FAILED:
	  4 - run-tox-mgr (Failed)
	 36 - smoke.sh (Failed)
```

the run-tox-mgr failure should be addressed by #49490

**Review by batrick — APPROVED** [review]

**Pull request merged**
