### PR TITLE
quincy: os/bluestore: Always update the cursor position in AVL near-fit search.

### PR DESCRIPTION
**Pull request by markhpc**
Quincy backport of #45884

Signed-off-by: Mark Nelson <mnelson@redhat.com>

### CODE REVIEW

**Review by jdurgin — APPROVED** [review]

**Comment by ifed01** [comment]
Generally LGTM, just one note. Our best practice is to cherry-pick commits from master when backporting. AFAIU that's not the case for this PR. Do we really need that deviation from the rules?

**Comment by markhpc** [comment]
@ifed01 After discussion yesterday at the rados meeting I thought @neha-ojha wanted to cherry-pick from the PR so the two PRs could be run through QA in parallel to get the quincy release out the door this week.  I don't typically do backports though so I apologize if it's a deviation from normal behavior.

**Review by ifed01 — APPROVED** [review]

**Comment by ifed01** [comment]
> @ifed01 After discussion yesterday at the rados meeting I thought @neha-ojha wanted to cherry-pick from the PR so the two PRs could be run through QA in parallel to get the quincy release out the door this week. I don't typically do backports though so I apologize if it's a deviation from normal behavior.
Got it.
So IMO it makes sense to leave it as-is for QA but do a proper "cherry-pick -x" before merging then.

**Comment by neha-ojha** [comment]
Changelog:

- force-push to fix ` git cherry-pick -x`

**Comment by neha-ojha** [comment]
jenkins test make check

**Comment by markhpc** [comment]
@neha-ojha Thanks, you beat me to it. :)

**Comment by ifed01** [comment]
jenkins test make check

**Comment by ljflores** [comment]
http://pulpito.front.sepia.ceph.com/?branch=wip-yuri-testing-2022-04-13-0703-quincy

Failures in the initial run were due to infrastructure, and therefore unrelated.
All jobs were green in the final re-run.

**Comment by ljflores** [comment]
jenkins test make check

**Comment by yuriw** [comment]
jenkins test make check

**Pull request merged**
