### PR TITLE
 mgr/dashboard: Visual regression tests for dashboard component

### PR DESCRIPTION
**Pull request by aaryanporwal**
Continuation of PR #42328 
Adding visual tests for dashboard component with ignore regions on charts on landing page(dashboard).
[Applitools Eyes Cypress SDK docs](https://github.com/applitools/eyes.sdk.javascript1/tree/master/packages/eyes-cypress/#readme)

---
## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by aaryanporwal** [comment]
Weird, `ceph dashboard tests` check didn't even show up.

**Comment by aaryanporwal** [comment]
jenkins test dashboard

**Comment by avanthakkar** [comment]
jenkins test dashboard

**Comment by aaryanporwal** [comment]
Closing in favour of #42328, all visual tests will be pushed into that pr

**Pull request closed without merging**
