### PR TITLE
quincy: mgr/snap_schedule: support subvol and group arguments

### PR DESCRIPTION
**Pull request by mchangir**
backport tracker: https://tracker.ceph.com/issues/64033

---

backport of https://github.com/ceph/ceph/pull/53999
parent tracker: https://tracker.ceph.com/issues/62892

this backport was staged using ceph-backport.sh version 16.0.0.6848
find the latest version at https://github.com/ceph/ceph/blob/main/src/script/ceph-backport.sh

### CODE REVIEW

**Comment by mchangir** [comment]
@ljflores `make check` fails here with the following ...

```
mypy: commands[0] /home/jenkins-build/build/workspace/ceph-pull-requests/src/pybind/mgr> mypy --config-file=../../mypy.ini -m alerts -m balancer -m cephadm -m crash -m dashboard -m devicehealth -m diskprediction_local -m hello -m influx -m iostat -m localpool -m mds_autoscaler -m mgr_module -m mgr_util -m mirroring -m nfs -m orchestrator -m pg_autoscaler -m progress -m prometheus -m rbd_support -m rgw -m rook -m snap_schedule -m selftest -m stats -m status -m telegraf -m telemetry -m test_orchestrator -m volumes -m zabbix
diskprediction_local/predictor.py:31: note: In module imported here,
diskprediction_local/module.py:17: note: ... from here,
diskprediction_local/__init__.py:2: note: ... from here:
.tox/mypy/lib/python3.10/site-packages/numpy/__init__.pyi:651: error: Positional-only parameters are only supported in Python 3.8 and greater
Found 1 error in 1 file (errors prevented further checking)
```
would you be able to address this issue ?

**Comment by mchangir** [comment]
rebased

**Comment by mchangir** [comment]
jenkins render docs

**Comment by mchangir** [comment]
jenkins test docs

**Comment by vshankar** [comment]
jenkins test make check

**Comment by mchangir** [comment]
rebased

**Comment by mchangir** [comment]
jenkins test make check

**Comment by mchangir** [comment]
jenkins test make check

**Comment by mchangir** [comment]
jenkins test make check

**Comment by mchangir** [comment]
rebased

**Comment by mchangir** [comment]
jenkins test make check

**Comment by mchangir** [comment]
PR is dependent on https://github.com/ceph/ceph/pull/56128

**Comment by mchangir** [comment]
rebased for PR to fix `make check` failures in dashboard

**Comment by mchangir** [comment]
* All [12 jobs](https://pulpito.ceph.com/mchangir-2024-03-14_06:47:01-fs-wip-mchangir-64033-quincy-distro-default-smithi/) have failed with `PG_AVAILABILITY` errors
* All 12 jobs have been verified for successful completion of snap-schedule tests
* This was the only PR being tested

Following command was used to check test completion status:
```
$ grep 'INFO:tasks.cephfs_test_runner:OK' $(find /teuthology/mchangir-2024-03-14_06:47:01-fs-wip-mchangir-64033-quincy-distro-default-smithi -name 'teuthology.log')
/teuthology/mchangir-2024-03-14_06:47:01-fs-wip-mchangir-64033-quincy-distro-default-smithi/7599890/teuthology.log:2024-03-14T09:15:18.387 INFO:tasks.cephfs_test_runner:OK
/teuthology/mchangir-2024-03-14_06:47:01-fs-wip-mchangir-64033-quincy-distro-default-smithi/7599899/teuthology.log:2024-03-14T09:29:04.415 INFO:tasks.cephfs_test_runner:OK
/teuthology/mchangir-2024-03-14_06:47:01-fs-wip-mchangir-64033-quincy-distro-default-smithi/7599896/teuthology.log:2024-03-14T09:19:08.599 INFO:tasks.cephfs_test_runner:OK
/teuthology/mchangir-2024-03-14_06:47:01-fs-wip-mchangir-64033-quincy-distro-default-smithi/7599891/teuthology.log:2024-03-14T09:09:41.373 INFO:tasks.cephfs_test_runner:OK
/teuthology/mchangir-2024-03-14_06:47:01-fs-wip-mchangir-64033-quincy-distro-default-smithi/7599892/teuthology.log:2024-03-14T09:10:40.978 INFO:tasks.cephfs_test_runner:OK
/teuthology/mchangir-2024-03-14_06:47:01-fs-wip-mchangir-64033-quincy-distro-default-smithi/7599895/teuthology.log:2024-03-14T09:16:03.684 INFO:tasks.cephfs_test_runner:OK
/teuthology/mchangir-2024-03-14_06:47:01-fs-wip-mchangir-64033-quincy-distro-default-smithi/7599893/teuthology.log:2024-03-14T09:19:09.171 INFO:tasks.cephfs_test_runner:OK
/teuthology/mchangir-2024-03-14_06:47:01-fs-wip-mchangir-64033-quincy-distro-default-smithi/7599897/teuthology.log:2024-03-14T09:15:16.801 INFO:tasks.cephfs_test_runner:OK
/teuthology/mchangir-2024-03-14_06:47:01-fs-wip-mchangir-64033-quincy-distro-default-smithi/7599898/teuthology.log:2024-03-14T09:18:44.282 INFO:tasks.cephfs_test_runner:OK
/teuthology/mchangir-2024-03-14_06:47:01-fs-wip-mchangir-64033-quincy-distro-default-smithi/7599894/teuthology.log:2024-03-14T09:14:30.630 INFO:tasks.cephfs_test_runner:OK
/teuthology/mchangir-2024-03-14_06:47:01-fs-wip-mchangir-64033-quincy-distro-default-smithi/7599900/teuthology.log:2024-03-14T09:17:03.145 INFO:tasks.cephfs_test_runner:OK
/teuthology/mchangir-2024-03-14_06:47:01-fs-wip-mchangir-64033-quincy-distro-default-smithi/7599889/teuthology.log:2024-03-14T09:07:05.714 INFO:tasks.cephfs_test_runner:OK
```

**Review by vshankar — APPROVED** [review]
LGTM

**Comment by mchangir** [comment]
jenkins test make check

**Comment by mchangir** [comment]
jenkins render docs

**Pull request merged**
