### PR TITLE
jewel: core: librados: Double free in rados_getxattrs_next

### PR DESCRIPTION
**Pull request by pdvian**
http://tracker.ceph.com/issues/22941

### CODE REVIEW

**Comment by smithfarm** [comment]
retest this please

**Comment by smithfarm** [comment]
jenkins test docs

**Comment by smithfarm** [comment]
@jdurgin @gregsfortytwo This PR was included in a rados run [1] in which ceph_test_rados_api_tmap_migrate is apparently failing reproducibly every time (see the assert at [1]). The culprit is suspected to be one of these three:

https://github.com/ceph/ceph/pull/20518 - jewel: osd: objecter sends out of sync with pg epochs for proxied ops
https://github.com/ceph/ceph/pull/20508 - jewel: ceph.restart + ceph_manager.wait_for_clean is racy
https://github.com/ceph/ceph/pull/20381 - jewel: librados: Double free in rados_getxattrs_next

Could you take a look?

[1] http://tracker.ceph.com/issues/21742#note-20

**Comment by smithfarm** [comment]
@gregsfortytwo I tracked the api_tmap_migrate failure down, and it's not caused by this PR. See

* http://tracker.ceph.com/issues/23529
* https://github.com/ceph/ceph/pull/20333

**Comment by smithfarm** [comment]
This PR passed a rados suite at http://tracker.ceph.com/issues/21742#note-20 (with some failed jobs, all of which attributable to known bugs)

Marking DNM until @gregsfortytwo 's objections are clarified.

**Comment by tchaikov** [comment]
> I dunno what's going on or if it's the cause, but it sure looks like this PR causes us to try to free a random pointer when we reach the end of the list.

@gregsfortytwo could you elaborate a little bit.  i am re-reading #20260, it still looks sane.

> (And the rest of the function is a great mess too, using memory after free!)

could you point me to the line where we are using the freed memory?

**Comment by gregsfortytwo** [comment]
Now I think I misunderstood the data structures involved here. But we free it->val before checking if we’re at the end; is what I was concerned about.

**Comment by tchaikov** [comment]
@gregsfortytwo thanks. that makes sense. i am posting #21164, and adding you as a Signed-off-by, as i think it's actually you who found the issue.

**Comment by smithfarm** [comment]
OK, after https://github.com/ceph/ceph/pull/21164 is merged, let's cherry-pick it into this PR .

**Comment by smithfarm** [comment]
Update: #21164 has been closed, and this PR can proceed into the integration testing phase.

**Comment by smithfarm** [comment]
@jdurgin This PR was included in a rados run at http://tracker.ceph.com/issues/21742#note-25

Initially there were several failures similar to http://tracker.ceph.com/issues/22063 and http://tracker.ceph.com/issues/22064

After three re-runs these were narrowed down to what seems like a pretty reproducible assert in the radosbench task of a test in "rados/upgrade". I opened a new bug for that, due to the newly increased reproducibility: http://tracker.ceph.com/issues/22598

(I doubt this PR is implicated in that new issue, because this PR was included in a previous rados run where that issue was not observed so frequently)

**Comment by jdurgin** [comment]
I agree, this PR is not related to those failures.

**Pull request merged**
