### PR TITLE
librbd: Avoid create two threads per image

### PR DESCRIPTION
**Pull request by yuyuyu101**

### CODE REVIEW

**Comment by dillaman** [comment]
LGTM

**Comment by jdurgin** [comment]
check bot is working now - the failure is real:

`librbd/ImageWatcher.cc: In constructor 'librbd::ImageWatcher::ImageWatcher(librbd::ImageCtx&)':
librbd/ImageWatcher.cc:40:3: error: 'cct' was not declared in this scope
   cct->lookup_or_create_singleton_object<TaskFinisher<Task> >(
   ^
librbd/ImageWatcher.cc:40:61: error: expected primary-expression before '>' token
   cct->lookup_or_create_singleton_object<TaskFinisher<Task> >(
                                                             ^
librbd/ImageWatcher.cc:41:22: warning: left operand of comma operator has no effect [-Wunused-value]
     m_task_finisher, "librbd::task_finisher");`

**Comment by yuyuyu101** [comment]
@jdurgin oh, sorry. Fixed now

**Comment by jdurgin** [comment]
The downside to the integrated bot is it doesn't provide a notification afaict. Failed to compile:

`In file included from ./global/global_context.h:18:0,
                 from ./common/dout.h:19,
                 from ./include/Context.h:19,
                 from ./common/Cond.h:22,
                 from ./librbd/ImageWatcher.h:6,
                 from librbd/ImageWatcher.cc:3:
./common/ceph_context.h: In instantiation of 'void CephContext::lookup_or_create_singleton_object(T*&, const string&) [with T = librbd::TaskFinisher<librbd::ImageWatcher::Task>; std::string = std::basic_string<char>]':
librbd/ImageWatcher.cc:41:45:   required from here
./common/ceph_context.h:132:9: error: no matching function for call to 'librbd::TaskFinisher<librbd::ImageWatcher::Task>::TaskFinisher(CephContext* const)'
       p = new T(this);
         ^
./common/ceph_context.h:132:9: note: candidate is:
In file included from librbd/ImageWatcher.cc:11:0:
./librbd/TaskFinisher.h:22:3: note: librbd::TaskFinisher<T>::TaskFinisher(CephContext&) [with Task = librbd::ImageWatcher::Task]
   TaskFinisher(CephContext &cct)
   ^
./librbd/TaskFinisher.h:22:3: note:   no known conversion for argument 1 from 'CephContext* const' to 'CephContext&'`

**Comment by yuyuyu101** [comment]
@jdurgin stupid again... updated and tested locally

**Pull request merged**
