### PR TITLE
pacific: librbd: miscellaneous backports

### PR DESCRIPTION
**Pull request by dillaman**

### CODE REVIEW

**Comment by dillaman** [comment]
Includes #40164

**Review by trociny — APPROVED** [review]

**Comment by dillaman** [comment]
Includes #39290

**Review by trociny — APPROVED** [review]

**Comment by idryomov** [comment]
Added https://github.com/ceph/ceph/pull/40178

**Review by trociny — APPROVED** [review]

**Comment by idryomov** [comment]
Added https://github.com/ceph/ceph/pull/40175

**Comment by idryomov** [comment]
jenkins test signed

**Comment by dillaman** [comment]
Includes #39915

**Comment by idryomov** [comment]
For krbd bits:

https://pulpito.ceph.com/dis-2021-03-17_22:21:55-krbd-wip-librbd-backports-pacific-9-testing-basic-gibba/

Failed jobs have actually passed, they are red due to paddles issue(s).

**Review by idryomov — APPROVED** [review]

**Comment by idryomov** [comment]
jenkins test signed

**Comment by djgalloway** [comment]
jenkins test signed

**Review by trociny — APPROVED** [review]

**Comment by dillaman** [comment]
Includes #40194

**Comment by dillaman** [comment]
Includes #40199

**Review by trociny — APPROVED** [review]

**Comment by dillaman** [comment]
jenkins test make check

**Comment by dillaman** [comment]
jenkins test api

**Comment by dillaman** [comment]
jenkins test api

**Comment by dillaman** [comment]
Lots of jenkins failures across PRs w/:

```
src/CMakeFiles/ceph-common.dir/build.make:429: *** target pattern contains no '%'.  Stop.
CMakeFiles/Makefile2:619: recipe for target 'src/CMakeFiles/ceph-common.dir/all' failed
```

**Comment by dillaman** [comment]
jenkins test api

**Comment by dillaman** [comment]
https://pulpito.ceph.com/jdillaman-2021-03-18_20:45:34-rbd-wip-jd-testing-pacific-distro-basic-smithi/

**Pull request merged**
