### PR TITLE
nautilus: rgw: support delimiter longer then one symbol

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/38777

### CODE REVIEW

**Comment by tchaikov** [comment]
retest this please

**Comment by yuriw** [comment]
[wip-yuri5-testing-2019-04-12-1916-nautilus](https://trello.com/c/tRDDEFxc/592-wip-yuri5-testing-2019-04-12-1916-nautilus)

**Comment by smithfarm** [comment]
@cbodley In the mimic backport of this fix - https://github.com/ceph/ceph/pull/29018 - you mentioned that the change caused a regression which is fixed by https://github.com/ceph/ceph/pull/28192

However that fix is not present in nautilus and 14.2.2 is poised for release. Should we:

(a) hold off on releasing 14.2.2 until the fix can be applied and the release re-tested; or
(b) add an item to "Known Issues" in the release notes PR https://github.com/ceph/ceph/pull/29011

?

**Comment by mattbenjamin** [comment]
@smithfarm we should not take this change without the fix

**Pull request merged**
