### PR TITLE
doc: ref cephfs docs from os-recommendations

### PR DESCRIPTION
**Pull request by jcsp**
...instead of having potentially conflicting kernel
version information.

Signed-off-by: John Spray john.spray@redhat.com

### CODE REVIEW

**Comment by dachary** [comment]
jenkins test this please (no log)

**Comment by jcsp** [comment]
@dillaman I haven't actually changed the RBD-related versions here, but could you confirm they're still correct?

**Comment by idryomov** [comment]
@jcsp I pushed https://github.com/idryomov/ceph/commits/wip-doc-kernel-vers.  Do you want to pull it into your branch or should I do a follow-up?

**Comment by jcsp** [comment]
@idryomov I see that you've already done the merge to get my commit on top of yours, so probably simplest to just close this PR and you open one with both changes in it

**Comment by idryomov** [comment]
Opened #13369.

**Pull request closed without merging**
