### PR TITLE
DNM: RadosGW regression: COPY doesn't preserve Content-Type

### PR DESCRIPTION
**Pull request by dachary**
http://tracker.ceph.com/issues/12199

### CODE REVIEW

**Comment by dachary** [comment]
When merged together with #5714, it fails and the failure can be reproduced with:
<pre>
filter="rgw/singleton/{overrides.yaml all/radosgw-admin-data-sync.yaml frontend/civetweb.yaml rgw_pool_type/ec-profile.yaml}"
./virtualenv/bin/teuthology-suite --priority 101 --suite rgw --filter="$filter" --suite-branch hammer --distro ubuntu --email loic@dachary.org --ceph hammer-backports --machine-type plana,burnupi,mira 
</pre>
where **hammer-backports** is a branch based on hammer in which #5387 and #5714 are merged.

**Comment by dachary** [comment]
@yehudasa I'm afraid I'm going to need your help to sort out this one. It is not environmental : the same job succeeds on hammer.

**Comment by yehudasa** [comment]
@dachary what failed exactly? Can you point at a failing run?

**Comment by dachary** [comment]
@yehudasa here are the failed jobs:

http://pulpito.ceph.com/loic-2015-08-31_00:31:50-rgw-hammer-backports---basic-multi/1039463
http://pulpito.ceph.com/loic-2015-08-31_00:31:50-rgw-hammer-backports---basic-multi/1039442
http://pulpito.ceph.com/loic-2015-08-31_00:31:50-rgw-hammer-backports---basic-multi/1039421

thanks for your help !

P.S. More details about the branch from which these failures were found at http://tracker.ceph.com/issues/12701#teuthology-run-commit-ed64d28d70905d4fbcd465550fc8d32a982d3955-HAMMER-BACKPORTS-August-30

**Comment by theanalyst** [comment]
@dachary @yehudasa this looks similar to another radosgw-agent failure reported upstream 
http://tracker.ceph.com/issues/12661

**Comment by dachary** [comment]
obsoleted by https://github.com/ceph/ceph/pull/6039

**Pull request closed without merging**
