### PR TITLE
rgw-admin: remove deprecated regionmap commands

### PR DESCRIPTION
**Pull request by cbodley**
Fixes: http://tracker.ceph.com/issues/18725

### CODE REVIEW

**Comment by oritwas** [comment]
@yehudasa @cbodley removing regionmap get command will mean we no longer support the sync agent (there is no problem removing the set command). If we decide not to support it than it should be documented

**Comment by oritwas** [comment]
@cbodley as teuthology still test the sync agent we need to remove those tests too.

**Comment by cbodley** [comment]
@oritwas oh yeah, good point. i guess we should leave the `regionmap get` command as is, and just remove it from the usage. lets wait to remove sync agent tests until we have test_multi.py working in teuthology

**Comment by cbodley** [comment]
updated tasks/util/rgw.py (needs testing)

re: support for the sync agent, it looks it's using the `admin/config` rest api to query the regionmap, so i don't think radosgw-admin commands will break the agent itself

**Comment by oritwas** [comment]
@cbodley , the moment it passes teuthology we can merge it

**Comment by cbodley** [comment]
passed teuthology: http://pulpito.ceph.com/cbodley-2017-03-17_11:36:22-rgw-wip-cbodley-testing---basic-mira/

**Comment by oritwas** [comment]
jenkins test this please

**Pull request merged**
