### PR TITLE
mgr/dashboard: Update npm packages

### PR DESCRIPTION
**Pull request by tspmelo**
Angular 10.1 includes extraction of TS translations,
so @locl/cli is no longer needed.

Updating Angular automatically removed the usage of base tsconfig.

Downgraded css-loader to be able to use css modules.

angular-tree-component has been deprecated and
replaced by @circlon/angular-tree-component

Fixes: https://tracker.ceph.com/issues/47289

Signed-off-by: Tiago Melo <tmelo@suse.com>

## Checklist
- [x] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by bk201** [comment]
Not quite sure if that's only me, the color of the rings, icons, some texts seem missing:

Master (2425c4b4de2750d508912bfc3460917d6fb7bce0):

Screen Shot 2020-09-07 at 2 38 54 PM

This PR:

Screen Shot 2020-09-07 at 2 43 11 PM

Other changes work well.

**Comment by callithea** [comment]
> Not quite sure if that's only me, the color of the rings, icons, and some texts seem missing:
I also tested the PR locally and ran into the same issue.
> 
> Master ([2425c4b](https://github.com/ceph/ceph/commit/2425c4b4de2750d508912bfc3460917d6fb7bce0)):
> 
> Screen Shot 2020-09-07 at 2 38 54 PM
> 
> This PR:
> 
> Screen Shot 2020-09-07 at 2 43 11 PM
> 
> Other changes work well.
+1

**Comment by tspmelo** [comment]
jenkins test api

**Review by Devp00l — APPROVED** [review]
Landing page looks good now :) And all tree views work as well :)

Nevertheless you need to rebase :/

**Comment by tspmelo** [comment]
jenkins test make check

**Comment by tspmelo** [comment]
jenkins test docs

**Comment by nizamial09** [comment]
jenkins test make check

**Comment by nizamial09** [comment]
jenkins test make check

**Comment by nizamial09** [comment]
@tspmelo make check error
```
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ceph-dashboard@0.0.0 i18n:extract: `ng xi18n --output-path src/locale --ivy`
npm ERR! Exit status 1
```
But the tests are passing locally for me.

**Review by nizamial09 — APPROVED** [review]
LGTM! Locally works fine.

**Comment by tspmelo** [comment]
@nizamial09 previous version of @angular/cli had a bug in i18n extraction. I Just updated to latest version and this should be fixed now.

**Comment by nizamial09** [comment]
@tspmelo Okay, thank you.

**Pull request merged**
