### PR TITLE
qa: cleanup snapshots before subvolume delete

### PR DESCRIPTION
**Pull request by mchangir**
Fixes: https://tracker.ceph.com/issues/65564
Introduced-by: 006c68f4920
Signed-off-by: Milind Changire <mchangir@redhat.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [x] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Comment by vshankar** [comment]
> @mchangir please run this through snap-schedule tests and link the test run.

I've added to my testing branch.

**Comment by mchangir** [comment]
> > @mchangir please run this through snap-schedule tests and link the test run.
> 
> I've added to my testing branch.

ack

**Comment by vshankar** [comment]
https://pulpito.ceph.com/vshankar-2024-05-07_03:44:24-fs-wip-vshankar-testing-20240506.153513-testing-default-smithi/

(unfortunately, failed are infra issues related to cephadm - would need a rebuild)

**Comment by vshankar** [comment]
This PR is under test in [https://tracker.ceph.com/issues/65882](https://tracker.ceph.com/issues/65882).

**Comment by vshankar** [comment]
Not all tests in this change were run since we ran into https://tracker.ceph.com/issues/66009 early

```
2024-05-11T03:12:02.723 INFO:teuthology.orchestra.run.smithi028.stderr:2024-05-11T03:12:02.722+0000 7f08d2a00640  1 -- 172.21.15.28:0/839653915 <== mon.0 v2:172.21.15.28:3300/0 7 ==== mon_command_ack([{"prefix": "log", "logtext": ["Starting test tasks.cephfs.test_snap_schedules.TestSnapSchedules.test_concurrent_snap_creates"]}]=0  v49) ==== 161+0+0 (secure 0 0 0) 0x7f08cc05b520 con 0x7f08dc06fd10
2024-05-11T03:23:54.170 INFO:teuthology.orchestra.run.smithi028.stderr:2024-05-11T03:23:54.173+0000 7f86c5600640  1 -- 172.21.15.28:0/2834531131 <== mon.0 v2:172.21.15.28:3300/0 7 ==== mon_command_ack([{"prefix": "log", "logtext": ["Starting test tasks.cephfs.test_snap_schedules.TestSnapSchedules.test_multi_snap_schedule"]}]=0  v436) ==== 157+0+0 (secure 0 0 0) 0x7f86b405fc30 con 0x7f86c815e340
```

I'm afraid this change has to be retested :/

**Comment by vshankar** [comment]
This PR is under test in [https://tracker.ceph.com/issues/66327](https://tracker.ceph.com/issues/66327).

**Comment by vshankar** [comment]
This PR is under test in [https://tracker.ceph.com/issues/66522](https://tracker.ceph.com/issues/66522).

**Review by vshankar — APPROVED** [review]
https://tracker.ceph.com/projects/cephfs/wiki/Main#wip-vshankar-testing-20240617094253-debug

(https://tracker.ceph.com/issues/66522)

**Pull request merged**
