### PR TITLE
erasure-code: update ceph-erasure-code-corpus for shec

### PR DESCRIPTION
**Pull request by dachary**
Update the ceph-erasure-code-corpus submodule to include the hammer shec
checks.

Signed-off-by: Loic Dachary <ldachary@redhat.com>

### CODE REVIEW

**Comment by dachary** [comment]
See https://github.com/ceph/ceph-erasure-code-corpus/commits/master to verify the change is what is expected.

**Comment by t-miyamae** [comment]
@dachary I'm sorry I don't understand what to do. Could you explain the meaning of this pull request?

**Comment by dachary** [comment]
@t-miyamae it means that when you run **make check** on the master branch, it will run tests using shec from https://github.com/ceph/ceph-erasure-code-corpus

**Comment by dachary** [comment]
@t-miyamae here is a simple way to test this pull request:
<pre>
git clone -b wip-shec-corpus https://github.com/dachary/ceph
./autogen.sh
./configure
make -j4
cd src
../qa/workunits/erasure-code/encode-decode-non-regression.sh
</pre>
it will use the modified ceph-erasure-code corpus module, which includes the shec tests.

**Comment by dachary** [comment]
running in gitbuilder under the branch wip-shec-corpus to verify it does not disrupt anything

**Comment by t-miyamae** [comment]
@dachary I wander why dachary/ceph version is my_version=v0.56-18654-gd723de6. Do I understand  nothing about erasure-code-corpus?

**Comment by dachary** [comment]
@t-miyamae this is determined by git describe

**Comment by dachary** [comment]
<pre>
(backports)loic@fold:/tmp$ git clone http://github.com/ceph/ceph ceph
Cloning into 'ceph'...
remote: Counting objects: 300093, done.
remote: Compressing objects: 100% (76/76), done.
remote: Total 300093 (delta 38), reused 0 (delta 0), pack-reused 300017
Receiving objects: 100% (300093/300093), 122.12 MiB | 293.00 KiB/s, done.
Resolving deltas: 100% (237602/237602), done.
Checking connectivity... done.
(backports)loic@fold:/tmp$ cd ceph
(backports)loic@fold:/tmp/ceph$ git describe
v9.0.0-958-g9f0d2da
</pre>

**Comment by t-miyamae** [comment]
@dachary I believe I finally understand the purpose of this pull request. However, I'd like to test it after we fix the teuthology's SHEC-specific problem. Could you wait us until that ?

**Comment by dachary** [comment]
@t-miyamae I have 4 pull requests waiting on this one and I would be very grateful if you can test it. We can run it again after you have fixed the teuthology tests: it's one of the advantages of having shec at the experimental stage :-)

**Comment by dachary** [comment]
http://ceph.com/gitbuilder.cgi branch wip-shec-corpus worked on all gitbuilders (except the tarbal that are stuck for unrelated reasons). It means the module update references a SHA1 that actually exists in the intended repository and that it is correctly mirrored in the repositories used by gitbuilder as mirrors.

**Comment by t-miyamae** [comment]
@dachary I'm sorry I did not contribute anything for your work. But I have finished verifying this pull request just now and it seems to work well except that the current master's ceph version shows 9.0.0-971-gd49d816. It seems strange for me but I'm not sure if that is a bug or not.

**Comment by dachary** [comment]
@t-miyamae thanks for the verification: it's very useful event after the merge :-) The ceph version 9.0.0-971-gd49d816 means this is version 971 commits ahead of the 9.0.0 tag (which is SHA d49d816). I would be very grateful if you have time to review https://github.com/ceph/ceph/pull/4708: although it's not strictly related the SHEC, I believe it will help with erasure code plugins in general. Thanks in advance !

**Comment by t-miyamae** [comment]
@dachary I have reviewed #4708 and found nothing to be pointed out.

**Pull request merged**
