### PR TITLE
mimic: mgr/dashboard: Prevent RGW API user deletion

### PR DESCRIPTION
**Pull request by votdev**
Backport issue: https://tracker.ceph.com/issues/24543 (please change status of this issue to "Resolved" when the PR merges - thanks!)

---

Fixes https://tracker.ceph.com/issues/24080

Signed-off-by: Volker Theile <vtheile@suse.com>

### CODE REVIEW

**Comment by smithfarm** [comment]
Also please note that there are separate issues for backports. It makes the backporting team's life easier if you can "take" the relevant backport issue when staging the backport PR and mention the backport issue in the PR description.

**Comment by votdev** [comment]
@smithfarm It's not possible to cherry-pick the changes from master because the issue  has been implemented totally different and there is no special PR for this issue in master, too.

**Comment by smithfarm** [comment]
@votdev Thanks for that explanation why the mimic fix could not be cherry-picked from master. Could you please copy-paste it into the commit message and then I'll dismiss my review.

**Comment by tspmelo** [comment]
jenkins retest this please

**Comment by votdev** [comment]
Can't reproduce the Teuthology errors on my local system. The errors are not related to any changes done in this PR.
```
PhantomJS 2.1.1 (Linux 0.0.0): Executed 56 of 230 SUCCESS (0 secs / 12.101 secs)
ERROR: 'ERROR', TypeError{stack: 'get@http://localhost:9876/_karma_webpack_/main.bundle.js:11204:39
getCounters@http://localhost:9876/_karma_webpack_/main.bundle.js:6175:43

handleEvent@http://localhost:9876/_karma_webpack_/vendor.bundle.js:68290:155
callWithDebugContext@http://localhost:9876/_karma_webpack_/vendor.bundle.js:69799:47
debugHandleEvent@http://localhost:9876/_karma_webpack_/vendor.bundle.js:69386:32
dispatchEvent@http://localhost:9876/_karma_webpack_/vendor.bundle.js:64705:36
http://localhost:9876/_karma_webpack_/vendor.bundle.js:67044:51
http://localhost:9876/_karma_webpack_/vendor.bundle.js:59055:51
__tryOrUnsub@http://localhost:9876/_karma_webpack_/vendor.bundle.js:177539:20
next@http://localhost:9876/_karma_webpack_/vendor.bundle.js:177486:34
_next@http://localhost:9876/_karma_webpack_/vendor.bundle.js:177427:30
next@http://localhost:9876/_karma_webpack_/vendor.bundle.js:177391:23
next@http://localhost:9876/_karma_webpack_/vendor.bundle.js:177121:29
emit@http://localhost:9876/_karma_webpack_/vendor.bundle.js:59023:50
reloadData@http://localhost:9876/_karma_webpack_/main.bundle.js:13516:32
http://localhost:9876/_karma_webpack_/main.bundle.js:13472:48
invoke@http://localhost:9876/_karma_webpack_/polyfills.bundle.js:5997:31
onInvoke@http://localhost:9876/_karma_webpack_/vendor.bundle.js:195254:45
invoke@http://localhost:9876/_karma_webpack_/polyfills.bundle.js:5996:40
onInvoke@http://localhost:9876/_karma_webpack_/vendor.bundle.js:59461:39
invoke@http://localhost:9876/_karma_webpack_/polyfills.bundle.js:5996:40
run@http://localhost:9876/_karma_webpack_/polyfills.bundle.js:5747:49
run@http://localhost:9876/_karma_webpack_/vendor.bundle.js:59278:72
http://localhost:9876/_karma_webpack_/main.bundle.js:13471:37
__tryOrUnsub@http://localhost:9876/_karma_webpack_/vendor.bundle.js:177539:20
next@http://localhost:9876/_karma_webpack_/vendor.bundle.js:177486:34
_next@http://localhost:9876/_karma_webpack_/vendor.bundle.js:177427:30
next@http://localhost:9876/_karma_webpack_/vendor.bundle.js:177391:23
dispatch@http://localhost:9876/_karma_webpack_/vendor.bundle.js:179654:24
_execute@http://localhost:9876/_karma_webpack_/vendor.bundle.js:192326:22
execute@http://localhost:9876/_karma_webpack_/vendor.bundle.js:192301:34
flush@http://localhost:9876/_karma_webpack_/vendor.bundle.js:192404:39
[native code]
invokeTask@http://localhost:9876/_karma_webpack_/polyfills.bundle.js:6030:36
onInvokeTask@http://localhost:9876/_karma_webpack_/vendor.bundle.js:195285:49
invokeTask@http://localhost:9876/_karma_webpack_/polyfills.bundle.js:6029:48
runTask@http://localhost:9876/_karma_webpack_/polyfills.bundle.js:5797:57
invokeTask@http://localhost:9876/_karma_webpack_/polyfills.bundle.js:6105:41
invoke@http://localhost:9876/_karma_webpack_/polyfills.bundle.js:6094:52
timer@http://localhost:9876/_karma_webpack_/polyfills.bundle.js:7663:34', line: 11204, sourceURL: 'http://localhost:9876/_karma_webpack_/main.bundle.js', ngDebugContext: DebugContext_{view: Object{def: ..., parent: ..., viewContainerParent: ..., parentNodeDef: ..., context: ..., component: ..., nodes: ..., state: ..., root: ..., renderer: ..., oldValues: ..., disposables: ..., initIndex: ...}, nodeIndex: 2, nodeDef: Object{nodeIndex: ..., parent: ..., renderParent: ..., bindingIndex: ..., outputIndex: ..., checkIndex: ..., flags: ..., childFlags: ..., directChildFlags: ..., childMatchedQueries: ..., matchedQueries: ..., matchedQueryIds: ..., references: ..., ngContentIndex: ..., childCount: ..., bindings: ..., bindingFlags: ..., outputs: ..., element: ..., provider: ..., text: ..., query: ..., ngContent: ...}, elDef: Object{nodeIndex: ..., parent: ..., renderParent: ..., bindingIndex: ..., outputIndex: ..., checkIndex: ..., flags: ..., childFlags: ..., directChildFlags: ..., childMatchedQueries: ..., matchedQueries: ..., matchedQueryIds: ..., references: ..., ngContentIndex: ..., childCount: ..., bindings: ..., bindingFlags: ..., outputs: ..., element: ..., provider: ..., text: ..., query: ..., ngContent: ...}, elView: Object{def: ..., parent: ..., viewContainerParent: ..., parentNodeDef: ..., context: ..., component: ..., nodes: ..., state: ..., root: ..., renderer: ..., oldValues: ..., disposables: ..., initIndex: ...}}, ngErrorLogger: function () { ... }}
[1A[2KERROR: 'ERROR CONTEXT', DebugContext_{view: Object{def: Object{factory: ..., nodeFlags: ..., rootNodeFlags: ..., nodeMatchedQueries: ..., flags: ..., nodes: ..., updateDirectives: ..., updateRenderer: ..., handleEvent: ..., bindingCount: ..., outputCount: ..., lastRenderRootNode: ...}, parent: Object{def: ..., parent: ..., viewContainerParent: ..., parentNodeDef: ..., context: ..., component: ..., nodes: ..., state: ..., root: ..., renderer: ..., oldValues: ..., disposables: ..., initIndex: ...}, viewContainerParent: null, parentNodeDef: Object{nodeIndex: ..., parent: ..., renderParent: ..., bindingIndex: ..., outputIndex: ..., checkIndex: ..., flags: ..., childFlags: ..., directChildFlags: ..., childMatchedQueries: ..., matchedQueries: ..., matchedQueryIds: ..., references: ..., ngContentIndex: ..., childCount: ..., bindings: ..., bindingFlags: ..., outputs: ..., element: ..., provider: ..., text: ..., query: ..., ngContent: ...}, context: TablePerformanceCounterComponent{performanceCounterService: ..., columns: ..., counters: ..., valueTpl: ...}, component: TablePerformanceCounterComponent{performanceCounterService: ..., columns: ..., counters: ..., valueTpl: ...}, nodes: [..., ..., ..., ..., ..., ..., ..., ...], state: 1038, root: Object{ngModule: ..., injector: ..., projectableNodes: ..., selectorOrNode: ..., sanitizer: ..., rendererFactory: ..., renderer: ..., errorHandler: ...}, renderer: DebugRenderer2{delegate: ..., data: ...}, oldValues: [..., ..., ...], disposables: [..., ...], initIndex: -1}, nodeIndex: 2, nodeDef: Object{nodeIndex: 2, parent: null, renderParent: null, bindingIndex: 0, outputIndex: 0, checkIndex: 2, flags: 33554433, childFlags: 2867203, directChildFlags: 2867203, childMatchedQueries: 2, matchedQueries: Object{}, matchedQueryIds: 0, references: Object{}, ngContentIndex: null, childCount: 4, bindings: [], bindingFlags: 0, outputs: [...], element: Object{ns: ..., name: ..., attrs: ..., template: ..., componentProvider: ..., componentView: ..., componentRendererType: ..., publicProviders: ..., allProviders: ..., handleEvent: ...}, provider: null, text: null, query: null, ngContent: null}, elDef: Object{nodeIndex: 2, parent: null, renderParent: null, bindingIndex: 0, outputIndex: 0, checkIndex: 2, flags: 33554433, childFlags: 2867203, directChildFlags: 2867203, childMatchedQueries: 2, matchedQueries: Object{}, matchedQueryIds: 0, references: Object{}, ngContentIndex: null, childCount: 4, bindings: [], bindingFlags: 0, outputs: [...], element: Object{ns: ..., name: ..., attrs: ..., template: ..., componentProvider: ..., componentView: ..., componentRendererType: ..., publicProviders: ..., allProviders: ..., handleEvent: ...}, provider: null, text: null, query: null, ngContent: null}, elView: Object{def: Object{factory: ..., nodeFlags: ..., rootNodeFlags: ..., nodeMatchedQueries: ..., flags: ..., nodes: ..., updateDirectives: ..., updateRenderer: ..., handleEvent: ..., bindingCount: ..., outputCount: ..., lastRenderRootNode: ...}, parent: Object{def: ..., parent: ..., viewContainerParent: ..., parentNodeDef: ..., context: ..., component: ..., nodes: ..., state: ..., root: ..., renderer: ..., oldValues: ..., disposables: ..., initIndex: ...}, viewContainerParent: null, parentNodeDef: Object{nodeIndex: ..., parent: ..., renderParent: ..., bindingIndex: ..., outputIndex: ..., checkIndex: ..., flags: ..., childFlags: ..., directChildFlags: ..., childMatchedQueries: ..., matchedQueries: ..., matchedQueryIds: ..., references: ..., ngContentIndex: ..., childCount: ..., bindings: ..., bindingFlags: ..., outputs: ..., element: ..., provider: ..., text: ..., query: ..., ngContent: ...}, context: TablePerformanceCounterComponent{performanceCounterService: ..., columns: ..., counters: ..., valueTpl: ...}, component: TablePerformanceCounterComponent{performanceCounterService: ..., columns: ..., counters: ..., valueTpl: ...}, nodes: [..., ..., ..., ..., ..., ..., ..., ...], state: 1038, root: Object{ngModule: ..., injector: ..., projectableNodes: ..., selectorOrNode: ..., sanitizer: ..., rendererFactory: ..., renderer: ..., errorHandler: ...}, renderer: DebugRenderer2{delegate: ..., data: ...}, oldValues: [..., ..., ...], disposables: [..., ...], initIndex: -1}}
PhantomJS 2.1.1 (Linux 0.0.0): Executed 56 of 230 SUCCESS (0 secs / 12.101 secs)
ERROR: 'ERROR CONTEXT', DebugContext_{view: Object{def: Object{factory: ..., nodeFlags: ..., rootNodeFlags: ..., nodeMatchedQueries: ..., flags: ..., nodes: ..., updateDirectives: ..., updateRenderer: ..., handleEvent: ..., bindingCount: ..., outputCount: ..., lastRenderRootNode: ...}, parent: Object{def: ..., parent: ..., viewContainerParent: ..., parentNodeDef: ..., context: ..., component: ..., nodes: ..., state: ..., root: ..., renderer: ..., oldValues: ..., disposables: ..., initIndex: ...}, viewContainerParent: null, parentNodeDef: Object{nodeIndex: ..., parent: ..., renderParent: ..., bindingIndex: ..., outputIndex: ..., checkIndex: ..., flags: ..., childFlags: ..., directChildFlags: ..., childMatchedQueries: ..., matchedQueries: ..., matchedQueryIds: ..., references: ..., ngContentIndex: ..., childCount: ..., bindings: ..., bindingFlags: ..., outputs: ..., element: ..., provider: ..., text: ..., query: ..., ngContent: ...}, context: TablePerformanceCounterComponent{performanceCounterService: ..., columns: ..., counters: ..., valueTpl: ...}, component: TablePerformanceCounterComponent{performanceCounterService: ..., columns: ..., counters: ..., valueTpl: ...}, nodes: [..., ..., ..., ..., ..., ..., ..., ...], state: 1038, root: Object{ngModule: ..., injector: ..., projectableNodes: ..., selectorOrNode: ..., sanitizer: ..., rendererFactory: ..., renderer: ..., errorHandler: ...}, renderer: DebugRenderer2{delegate: ..., data: ...}, oldValues: [..., ..., ...], disposables: [..., ...], initIndex: -1}, nodeIndex: 2, nodeDef: Object{nodeIndex: 2, parent: null, renderParent: null, bindingIndex: 0, outputIndex: 0, checkIndex: 2, flags: 33554433, childFlags: 2867203, directChildFlags: 2867203, childMatchedQueries: 2, matchedQueries: Object{}, matchedQueryIds: 0, references: Object{}, ngContentIndex: null, childCount: 4, bindings: [], bindingFlags: 0, outputs: [...], element: Object{ns: ..., name: ..., attrs: ..., template: ..., componentProvider: ..., componentView: ..., componentRendererType: ..., publicProviders: ..., allProviders: ..., handleEvent: ...}, provider: null, text: null, query: null, ngContent: null}, elDef: Object{nodeIndex: 2, parent: null, renderParent: null, bindingIndex: 0, outputIndex: 0, checkIndex: 2, flags: 33554433, childFlags: 2867203, directChildFlags: 2867203, childMatchedQueries: 2, matchedQueries: Object{}, matchedQueryIds: 0, references: Object{}, ngContentIndex: null, childCount: 4, bindings: [], bindingFlags: 0, outputs: [...], element: Object{ns: ..., name: ..., attrs: ..., template: ..., componentProvider: ..., componentView: ..., componentRendererType: ..., publicProviders: ..., allProviders: ..., handleEvent: ...}, provider: null, text: null, query: null, ngContent: null}, elView: Object{def: Object{factory: ..., nodeFlags: ..., rootNodeFlags: ..., nodeMatchedQueries: ..., flags: ..., nodes: ..., updateDirectives: ..., updateRenderer: ..., handleEvent: ..., bindingCount: ..., outputCount: ..., lastRenderRootNode: ...}, parent: Object{def: ..., parent: ..., viewContainerParent: ..., parentNodeDef: ..., context: ..., component: ..., nodes: ..., state: ..., root: ..., renderer: ..., oldValues: ..., disposables: ..., initIndex: ...}, viewContainerParent: null, parentNodeDef: Object{nodeIndex: ..., parent: ..., renderParent: ..., bindingIndex: ..., outputIndex: ..., checkIndex: ..., flags: ..., childFlags: ..., directChildFlags: ..., childMatchedQueries: ..., matchedQueries: ..., matchedQueryIds: ..., references: ..., ngContentIndex: ..., childCount: ..., bindings: ..., bindingFlags: ..., outputs: ..., element: ..., provider: ..., text: ..., query: ..., ngContent: ...}, context: TablePerformanceCounterComponent{performanceCounterService: ..., columns: ..., counters: ..., valueTpl: ...}, component: TablePerformanceCounterComponent{performanceCounterService: ..., columns: ..., counters: ..., valueTpl: ...}, nodes: [..., ..., ..., ..., ..., ..., ..., ...], state: 1038, root: Object{ngModule: ..., injector: ..., projectableNodes: ..., selectorOrNode: ..., sanitizer: ..., rendererFactory: ..., renderer: ..., errorHandler: ...}, renderer: DebugRenderer2{delegate: ..., data: ...}, oldValues: [..., ..., ...], disposables: [..., ...], initIndex: -1}}
```

**Comment by votdev** [comment]
jenkins retest this please

**Comment by tspmelo** [comment]
jenkins retest this please

**Comment by smithfarm** [comment]
@votdev Ping. Could you please add your comment "It's not possible to cherry-pick the changes from master because the issue has been implemented totally different and there is no special PR for this issue in master, too." to the commit message? This will ensure that the information is available to anyone doing forensic analysis of the mimic git history.

**Comment by LenzGr** [comment]
@smithfarm please note that @votdev is on leave this week - he'll address this when he's back.

**Comment by votdev** [comment]
@smithfarm The commit message was already adapted when you post your comment :-)

**Comment by smithfarm** [comment]
@LenzGr How shall we handle backports that only touch code under `src/pybind/mgr/dashboard/`? Do you want to handle the integration testing/merging, or shall we (backport/QE team) do that? If we were to handle it, our default merge criteria would be:

* you (as Dashboard Lead) have approved the PR
* the PR has passed a rados suite

**Comment by sebastian-philipp** [comment]
```
/home/sebastian/Repos/ceph/build/bin/ceph -c /home/sebastian/Repos/ceph/build/ceph.conf -k /home/sebastian/Repos/ceph/build/keyring tell mgr dashboard set-login-credentials admin admin 
Error EINVAL: TypeError: handle_command() takes exactly 2 arguments (3 given)
```
would it be ok for you to rebase this PR? (Otherwise I would need to recompile for this PR)

**Comment by votdev** [comment]
@sebastian-philipp No problem, done.

**Comment by sebastian-philipp** [comment]
would it make sense to add a test case for it?

**Comment by votdev** [comment]
@yuriw Can you please run the QA?

**Comment by yuriw** [comment]
[wip-yuri4-testing-2018-08-27-2031-mimic](https://trello.com/c/7q6L5uZX/382-wip-yuri4-testing-2018-08-27-2031-mimic)

**Pull request merged**
