### PR TITLE
hammer: rbd: fix possible rbd data corruption

### PR DESCRIPTION
**Pull request by asheplyakov**
http://tracker.ceph.com/issues/16546

### CODE REVIEW

**Comment by smithfarm** [comment]
@asheplyakov Could you rebase please?

**Comment by asheplyakov** [comment]
@smithfarm
> Could you rebase please?

Done. (sorry for a late reply)

**Comment by smithfarm** [comment]
@dillaman This PR was included in this rbd suite: http://tracker.ceph.com/issues/17151#note-12

That run has two issues: the first (OSD suicide timeout) is not reproducible and looks like environmental noise. Then there is a reproducible qemu-iotests failure which matches http://tracker.ceph.com/issues/10773 

Can you take a look? If you think the qemu-iotests failure is unrelated, I guess this PR could be merged?

**Comment by dillaman** [comment]
@smithfarm lgtm

**Pull request merged**
