### PR TITLE
jewel: rgw: only append zonegroups to rest params if not empty

### PR DESCRIPTION
**Pull request by theanalyst**
http://tracker.ceph.com/issues/20078

### CODE REVIEW

**Comment by theanalyst** [comment]
http://pulpito.ceph.com/abhi-2017-05-25_21:01:03-rgw-wip-jewel-rgw-valgrind-fixes-distro-basic-smithi/ was a run with this patch and seems to have the param related failures solved.

**Comment by theanalyst** [comment]
passed the valgrind run, http://pulpito.ceph.com/abhi-2017-05-31_18:12:13-rgw-wip-jewel-rgw-valgrind-fixes---basic-smithi/ couple of env failures one of which passed in the next rerun (the other had an env failure again)

**Comment by cbodley** [comment]
looks good. i'm happy to let the backport team decide when to merge

**Comment by theanalyst** [comment]
@cbodley I'll run a larger RGW suite during the day and then merge the PRs, so far the valgrind failures of earlier seem to not reappear.

**Comment by smithfarm** [comment]
This PR was included in the integration branch tested at http://tracker.ceph.com/issues/19538#note-60 (rgw run, ruled a pass)

**Pull request merged**
