### PR TITLE
debian/control: ceph-dbg steals ceph-objectstore-tool from ceph-test-dbg

### PR DESCRIPTION
**Pull request by dachary**
http://tracker.ceph.com/issues/11546

### CODE REVIEW

**Comment by tchaikov** [comment]
might want to connect this ticket with http://tracker.ceph.com/issues/11546

**Comment by dachary** [comment]
@tchaikov done and also updated with a more substantial commit message

**Comment by dachary** [comment]
tested at http://tracker.ceph.com/issues/11546#note-23

**Comment by ktdreyer** [comment]
I was wondering if it was "ok" to put that into a -dbg package or not. Cool. Merging...

**Pull request merged**
