### PR TITLE
qa/suites/upgrade/hammer-x: set "sortbitwise" for jewel clusters

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/20401

Inspired by 3734280522a913ca8340ebc98b80978f63bade6f

This cannot be cherry-picked from master because master does not have
qa/suites/upgrade/hammer-x

Signed-off-by: Nathan Cutler <ncutler@suse.com>

### CODE REVIEW

**Comment by smithfarm** [comment]
Would hopefully fix, e.g., this failure: http://pulpito.front.sepia.ceph.com/smithfarm-2017-06-22_08:13:28-upgrade:hammer-x-wip-jewel-backports-distro-basic-vps/1316156/

**Comment by smithfarm** [comment]
This PR was included in the `upgrade/hammer-x` run at http://tracker.ceph.com/issues/19538#note-71

There are still 3 failures, but this particular one no longer manifests and the overall experience of running this suite is improved.

**Comment by yuriw** [comment]
@smithfarm @tchaikov we probably need it on master, yes?

**Comment by smithfarm** [comment]
@yuriw There's no hammer-x in master, but @tchaikov did merge this one: #15764

**Comment by yuriw** [comment]
@smithfarm I actually meant kraken :)  and also we need it in hammer-jewel-x

**Comment by tchaikov** [comment]
@yuriw yeah, we need to include `qa/releases/jewel.yaml` or a variant of it in the upgrade tests involving jewel.

**Pull request merged**
