### PR TITLE
cmake: add option WITH_LIBRADOSSTRIPER

### PR DESCRIPTION
**Pull request by tchaikov**
otherwise this cmake variable is never defined, hence all tests
requiring libstriper are broken.

this is a regresssion introduced by 5513a90c62 .

Signed-off-by: Kefu Chai <kchai@redhat.com>

- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by tchaikov** [comment]
this should address 

- http://pulpito.ceph.com/kchai-2018-08-24_14:06:56-rados-wip-kefu2-testing-2018-08-24-1611-distro-basic-mira/2941738/
- http://pulpito.ceph.com/kchai-2018-08-24_14:06:56-rados-wip-kefu2-testing-2018-08-24-1611-distro-basic-mira/2941738/

**Comment by tchaikov** [comment]
http://pulpito.ceph.com/kchai-2018-08-24_16:11:55-rados-wip-kefu2-testing-2018-08-24-1611-distro-basic-mira/

**Comment by tchaikov** [comment]
@cbodley we always package `libradosstriper1` and `libradosstriper-dev`. the root cause of the test failures is:  the preprocessor macro of `WITH_LIBRADOSTRIPER` is not defined without this change, so the libradosstriper feature in `rados` cli tools is always disabled at compile-time. and we are using this tool to test libradosstriper...

**Comment by tchaikov** [comment]
changelog:

- add 9497775cb4426f319987cf2a03ca171281e4e6c7 for the `WITH_LIBRADOSSTRIPER` macro

**Comment by chardan** [comment]
Hm, interesting that I hadn't seen this (but it's been a while since I could run the tests!)-- good catch, thanks!

**Comment by tchaikov** [comment]
@chardan i am wondering how you tested your change ... actually, i would have liked to hold this PR until the test batch passed.

**Pull request merged**
