### PR TITLE
Revert "doc: Use older mistune"

### PR DESCRIPTION
**Pull request by ktdreyer**
This reverts commit ed2ad24a4ba3ad3f8103926bfea2466b9eb61222.

Fixes: https://tracker.ceph.com/issues/65555

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Comment by ktdreyer** [comment]
jenkins test docs

**Comment by ktdreyer** [comment]
The documentation renders fine with this change. Who can review this?

**Comment by zdover23** [comment]
jenkins retest this please

**Comment by zdover23** [comment]
```
Extension error:
Could not import extension sphinxcontrib.openapi (exception: cannot import name 'error_string' from 'docutils.io' (/home/jenkins-build/build/workspace/ceph-pr-docs/build-doc/virtualenv/lib/python3.10/site-packages/docutils/io.py))
+ succeed=false
+ false
+ cat /home/jenkins-build/build/workspace/ceph-pr-docs/build-doc-7qF.out
+ github-check --sphinx --sphinx-root=. --owner ceph --repo ceph --pkey-file **** --app-id 62865 --install-id 8465036 --name ceph-pr-docs --sha 199bbdb635a86507aa01b59bdb1c0f2a59862645 --external-id 99187 --details-url https://jenkins.ceph.com/job/ceph-pr-docs/99187/ --title sphinx-build
+ false
Build step 'Execute shell' marked build as failure
[Checks API] No suitable checks publisher found.
Setting status of 199bbdb635a86507aa01b59bdb1c0f2a59862645 to FAILURE with url https://jenkins.ceph.com/job/ceph-pr-docs/99187/ and message: 'Docs: failed with errors
 '
Using context: Docs: build check
Finished: FAILURE
```

**Pull request closed without merging**
