### PR TITLE
mgr/dashboard: test-promtool-packages

### PR DESCRIPTION
**Pull request by aaSharma14**
test promtool packages

Signed-off-by: Aashish Sharma <aasharma@redhat.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by aaSharma14** [comment]
jenkins test make check

**Comment by aaSharma14** [comment]
jenkins test make check

**Comment by tchaikov** [comment]
@aaSharma14 i think this change is an improvement. why did you abandon it? i resurrected it at #40300 anyway.

**Comment by aaSharma14** [comment]
Just saw that PR. Thanks @tchaikov for taking care.!

**Pull request closed without merging**
