### PR TITLE
common: use ref to avoid unnecessary memory copy

### PR DESCRIPTION
**Pull request by Liuchang0812**
Fixes: http://tracker.ceph.com/issues/19107

Signed-off-by: liuchang0812 <liuchang0812@gmail.com>

### CODE REVIEW

**Comment by Liuchang0812** [comment]
jenkins test this please

**Comment by Liuchang0812** [comment]
jenkins test this please

**Comment by liewegas** [comment]
retest this please

**Comment by Liuchang0812** [comment]
Change log:

1. rebased forward to master

**Pull request merged**
