### PR TITLE
Wip rgw noperiod

### PR DESCRIPTION
**Pull request by yehudasa**
rgw: dont' require that rados pools start with a period, and rename default pool names so that they are much more friendly.

### CODE REVIEW

**Comment by theanalyst** [comment]
Will having a default pool with dots (from previous versions of rgw) affect radosgw during upgrades, since we're renaming the defualt pools?
 (I'm assuming it wouldn't be a problem as region info/zone info would already be populated with the old defaults & rgw checks these.. but just wan't to be sure)

**Comment by yehudasa** [comment]
@theanalyst the default configurable doesn't change, so it'll still try to access .rgw.root as the starting point if not configured otherwise.

**Comment by theanalyst** [comment]
Thanks.

**Comment by dachary** [comment]
@yehudasa this needs a rebase

**Comment by yehudasa** [comment]
closing, it's already part of new multi site branch

**Pull request closed without merging**
