### PR TITLE
pacific: cephfs-top: adding filesystem menu option

### PR DESCRIPTION
**Pull request by neesingh-rh**
backport tracker: https://tracker.ceph.com/issues/57282

---

backport of https://github.com/ceph/ceph/pull/46072
parent tracker: https://tracker.ceph.com/issues/54978

this backport was staged using ceph-backport.sh version 16.0.0.6848
find the latest version at https://github.com/ceph/ceph/blob/master/src/script/ceph-backport.sh

### CODE REVIEW

**Review by anthonyeleven — APPROVED** [review]

**Comment by neesingh-rh** [comment]
jenkins test make check

**Comment by vshankar** [comment]
jenkins test make check

**Comment by vshankar** [comment]
Ready for QA.

**Comment by neesingh-rh** [comment]
jenkins test make check

**Comment by yuriw** [comment]
@neesingh-rh pls rebase

**Comment by neesingh-rh** [comment]
> @neesingh-rh pls rebase

Rebased!!

**Review by vshankar — APPROVED** [review]

**Pull request merged**
