### PR TITLE
osd/PGBackend: build_push_op assert() before dereferencing iter

### PR DESCRIPTION
**Pull request by Aran85**
here i meet a segment fault, maybe assert better

Signed-off-by: Zengran Zhang zhangzengran@h3c.com

### CODE REVIEW

**Comment by Aran85** [comment]
steps to reproduce
./vstart.sh -n
./ceph osd pool set rbd size 2
./rados put testfile /etc/hosts -p rbd
ps: the testfile map to pg0.6 whose upset is [0,1]
rm ./dev/osd0/current/0.6_head/xxxtestfilexxx_0
./ceph osd out osd.1
./ceph osd down osd.1
then osd.0 crash.

bc the fd of testifle is in filestore's fdcache, so it could get the object context of it. so let the osd.0 think testfile is not missing, but when it prepare to push to a new upset osd, it fail to lfn_open it. 

does this situation need to worry about in actual production environment?

**Comment by yuyuyu101** [comment]
I think assert is fine now. Because ceph doesn't have a rule to handle missing file in local filesystem...

**Comment by yuyuyu101** [comment]
And I think this isn't allowed

**Comment by yuyuyu101** [comment]
I don't think this change makes sense, remove this line will result into later segment fault. If you want to have a good error handle. return ENOENT may better.

But since we will hit assert(r == 0) by checking return value. There is no difference in real env. Anyway, return errno give a good sharp to let others handle this case later.

**Comment by Aran85** [comment]
@yuyuyu101 thanks for review. the assert line  added by me,not remove. do you mean we should return errno here?

**Comment by yuyuyu101** [comment]
oh, sorry. my mistake. yes, I think we can return errno.

**Comment by tchaikov** [comment]
- http://pulpito.ceph.com/kchai-2016-11-13_05:09:22-rados-wip-kefu-testing---basic-smithi/
- http://pulpito.ceph.com/kchai-2016-11-11_07:45:56-rados-wip-kefu-testing---basic-smithi/

**Pull request merged**
