### PR TITLE
rbd-mirror: snapshot-based mirroring should use image sync throttler

### PR DESCRIPTION
**Pull request by dillaman**
## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by dillaman** [comment]
http://pulpito.ceph.com/jdillaman-2020-03-18_16:58:14-rbd-wip-jd-testing-distro-basic-smithi/

**Comment by trociny** [comment]
@dillaman When running on a subset of mirroring tests [1] I was observing a failure in rbd_mirror_snapshot.sh "test trash move restore" [2]:
```
2020-03-19T12:19:59.560 INFO:tasks.workunit.cluster1.client.mirror.smithi138.stderr:+ rbd --cluster=cluster2 trash move mirror/test
2020-03-19T12:20:00.607 INFO:tasks.workunit.cluster1.client.mirror.smithi138.stderr:rbd: deferred delete error: (16) Device or resource busy
```
Couldn't it be that the mirror may block trash move at some point and after adding sync throttling we increased a chance of hitting it?

There was another strange failure [3] though it is definitely unrelated. It failed in rbd_mirror_journal.sh  "remove mirroring pool" test:
```
2020-03-19T12:29:01.772 INFO:tasks.workunit.cluster1.client.mirror.smithi120.stderr:+ rbd --cluster cluster2 mirror pool peer add pool_to_remove cluster1
2020-03-19T12:29:02.000 INFO:tasks.workunit.cluster1.client.mirror.smithi120.stderr:rbd: multiple peers are not currently supported
```
It looked like if the pool had already existed before we was trying to create and configure it...

[1] http://pulpito.ceph.com/trociny-2020-03-19_11:38:56-rbd-wip-mgolub-testing-distro-basic-smithi/
[2] http://qa-proxy.ceph.com/teuthology/trociny-2020-03-19_11:38:56-rbd-wip-mgolub-testing-distro-basic-smithi/4867977/teuthology.log
[3] http://qa-proxy.ceph.com/teuthology/trociny-2020-03-19_11:38:56-rbd-wip-mgolub-testing-distro-basic-smithi/4867971/teuthology.log

**Comment by dillaman** [comment]
Yeah, looks like `trash move` disabled mirroring and then immediately failed on attempting to acquire the exclusive lock (since the mirror hadn't shut-down yet). I had tweaked the remove API to just request the lock from the owner to solve that condition (25c2ffe145), so I guess I'll just do the same for the trash move op.

**Comment by dillaman** [comment]
(new build: https://shaman.ceph.com/builds/ceph/wip-jd-testing/5fab8999e1a305f2162923f3cf5e60069e5f1198/)

**Comment by trociny** [comment]
@dillaman running your build on teuthology [1], there are some failures for rbd_mirror_snapshot.sh test. [2,3] looks the same -- failing in "non-default namespace image mirroring - data pool" test. In both cases the test was waiting for replay complete (looking for the complete secodary snapshot) and failed by timeout. When looking at the rbd mirror log for the case [2], I see that the mirror sent "request_sync" but never received the response:
```
/ceph/teuthology-archive/trociny-2020-03-19_20:04:02-rbd-wip-jd-testing-distro-basic-smithi/4869479/remote/smithi007/log/cluster1-client.mirror.1.36750.log.gz:

2020-03-20T04:13:38.104+0000 7fd0cfbae700 15 rbd::mirror::image_replayer::snapshot::Replayer: 0x55c128df4e00 handle_image_update_notify: flagging snapshot rescan required
2020-03-20T04:13:38.109+0000 7fd0ea3e3700 10 rbd::mirror::image_replayer::snapshot::Replayer: 0x55c128df4e00 handle_create_non_primary_snapshot: r=0
2020-03-20T04:13:38.109+0000 7fd0ea3e3700 15 rbd::mirror::image_replayer::snapshot::Replayer: 0x55c128df4e00 handle_create_non_primary_snapshot: local_snap_id_end=19
2020-03-20T04:13:38.109+0000 7fd0ea3e3700 10 rbd::mirror::image_replayer::snapshot::Replayer: 0x55c128df4e00 request_sync: 
```

There was also failure when rbd-mirror failed to stop after kill signal [4]
```
2020-03-20T04:24:08.774 INFO:tasks.workunit.cluster1.client.mirror.smithi129.stderr:+ kill 24577
2020-03-20T04:24:08.774 INFO:tasks.workunit.cluster1.client.mirror.smithi129.stderr:+ for s in 1 2 4 8 16 32
2020-03-20T04:24:08.774 INFO:tasks.workunit.cluster1.client.mirror.smithi129.stderr:+ sleep 1
2020-03-20T04:24:09.775 INFO:tasks.workunit.cluster1.client.mirror.smithi129.stderr:+ ps auxww
2020-03-20T04:24:09.776 INFO:tasks.workunit.cluster1.client.mirror.smithi129.stderr:+ awk -v pid=24577 '$2 == pid {print; exit 1}'
2020-03-20T04:24:09.787 INFO:tasks.workunit.cluster1.client.mirror.smithi129.stdout:ubuntu     24577  0.4  0.2 781936 66656 ?        Ssl  04:19   0:01 rbd-mirror --cluster cluster1 --id mirror.0 --rbd-mirror-delete-retry-interval=5 --rbd-mirror-image-state-check-interval=5 --rbd-mirror-journal-poll-age=1 --rbd-mirror-pool-replayers-refresh-interval=5 --debug-rbd=30 --debug-journaler=30 --debug-rbd_mirror=30 --daemonize=true
...
```
In the rbd-mirror log (/ceph/teuthology-archive/trociny-2020-03-19_20:04:02-rbd-wip-jd-testing-distro-basic-smithi/4869494/remote/smithi129/log/cluster1-client.mirror.0.24568.log.gz) I see that signal was received and the shut down started:
```
2020-03-20T04:24:08.772+0000 7f5181706700 -1 received  signal: Terminated from /bin/sh -ex /home/ubuntu/cephtest/clone.cluster1.client.mirror/qa/workunits/rbd/rbd_mirror_snapshot.sh  (PID: 22716) UID: 1000
2020-03-20T04:24:08.772+0000 7f5181706700 20 rbd::mirror::Mirror: 0x558a6c1a3680 handle_signal: 15
2020-03-20T04:24:08.772+0000 7f518f3bc680 20 rbd::mirror::PoolReplayer: 0x558a6ce28600 stop: enter: manual=0
2020-03-20T04:24:08.772+0000 7f518f3bc680 20 rbd::mirror::PoolReplayer: 0x558a6e678600 stop: enter: manual=0
```
but later there are many entries like these one from the same snapshot replayer:
```
2020-03-20T04:24:37.699+0000 7f51586b4700 10 rbd::mirror::image_replayer::snapshot::Replayer: 0x558a705ba380 handle_image_update_notify: 
2020-03-20T04:24:37.700+0000 7f51586b4700 10 rbd::mirror::image_replayer::snapshot::Replayer: 0x558a705ba380 handle_image_update_notify: 
2020-03-20T04:24:37.700+0000 7f51586b4700 10 rbd::mirror::image_replayer::snapshot::Replayer: 0x558a705ba380 handle_image_update_notify: 
```
Before these for this replayer I see:
```
2020-03-20T04:24:09.687+0000 7f517ff03700 10 rbd::mirror::image_replayer::snapshot::Replayer: 0x558a705ba380 handle_request_sync: r=-125
2020-03-20T04:24:09.687+0000 7f517ff03700  5 rbd::mirror::image_replayer::snapshot::Replayer: 0x558a705ba380 handle_request_sync: image-sync canceled
```

[1] http://pulpito.ceph.com/trociny-2020-03-19_20:04:02-rbd-wip-jd-testing-distro-basic-smithi/
[2] http://qa-proxy.ceph.com/teuthology/trociny-2020-03-19_20:04:02-rbd-wip-jd-testing-distro-basic-smithi/4869479/teuthology.log
[3] http://qa-proxy.ceph.com/teuthology/trociny-2020-03-19_20:04:02-rbd-wip-jd-testing-distro-basic-smithi/4869498/teuthology.log
[4] http://qa-proxy.ceph.com/teuthology/trociny-2020-03-19_20:04:02-rbd-wip-jd-testing-distro-basic-smithi/4869494/teuthology.log

**Comment by dillaman** [comment]
Thanks for the analysis! The first two cases it appears like there is no leader so I'll need to dig into that one more:

> 2020-03-20T04:13:38.109+0000 7fd0ea3e3700 10 rbd::mirror::InstanceWatcher: C_NotifyInstanceRequest: 0x55c128c44600 C_NotifyInstanceRequest: instance_watcher=0x55c125c5e700, instance_id=, request_id=1
> 2020-03-20T04:13:38.109+0000 7fd0ea3e3700 10 rbd::mirror::InstanceWatcher: C_NotifyInstanceRequest: 0x55c128c44600 send
> 2020-03-20T04:13:38.109+0000 7fd0ea3e3700 10 rbd::mirror::InstanceWatcher: C_NotifyInstanceRequest: 0x55c128c44600 send: suspending

For the second case, when `handle_request_sync` is invoked, I really should be calling `is_replay_interrupted` since that is what is going to continue the shut down logic that was already requested. I therefore wonder if a stuck shut down somehow prevented the election of a new leader which exposed the first issue.

**Comment by dillaman** [comment]
... the first case involved namespace instance watchers and they were never initialized w/ the leader instance id due to a race during `PoolReplayer` start up.

**Comment by dillaman** [comment]
Found the bug for the first issue in `LeaderWatcher` -- I will kick off a bunch of snapshot mirroring test runs once re-built

**Comment by dillaman** [comment]
http://pulpito.ceph.com/jdillaman-2020-03-20_15:10:43-rbd-wip-jd-testing-distro-basic-smithi/
http://pulpito.ceph.com/jdillaman-2020-03-20_18:29:30-rbd-wip-jd-testing-distro-basic-smithi/

**Comment by dillaman** [comment]
The snapshot test [1] that failed seemed to just be an unfortunate slow cluster since `Mirror::run` was attempting to start a `PoolReplayer` and it took 5 minutes to connect:

> 2020-03-20T22:57:57.460+0000 7f474a62b680 10 rbd::mirror::PoolReplayer: 0x55c8ccddc600 init: replaying for uuid: e3ff95b6-bbe5-4715-a26e-7667543623d0 cluster: cluster2-DNE client: client.mirror
> .... snip
> 2020-03-20T23:02:57.505+0000 7f474a62b680 10 rbd::mirror::PoolReplayer: 0x55c8ccddc600 init: connected to uuid: e3ff95b6-bbe5-4715-a26e-7667543623d0 cluster: cluster2-DNE client: client.mirror

This blocked the process from shutting down and failed the test.

[1] http://qa-proxy.ceph.com/teuthology/jdillaman-2020-03-20_18:29:30-rbd-wip-jd-testing-distro-basic-smithi/4873915/teuthology.log

**Pull request merged**
