### PR TITLE
jewel: don't loop forever when reading data from 0 sized segment.

### PR DESCRIPTION
**Pull request by oritwas**
http://tracker.ceph.com/issues/17693

The 0 sized segment can arise depending on how
the client uploads the object in the first place.
The cpu loop then happens during a swift `GET'.

Signed-off-by: Marcus Watts <mwatts@redhat.com>
(cherry picked from commit 46c5f9773246522e66bb2cca49345d0b62a16c42)

### CODE REVIEW

**Comment by oritwas** [comment]
http://tracker.ceph.com/issues/17686

**Comment by oritwas** [comment]
teuthology run:
http://pulpito.ceph.com/owasserm-2016-10-24_20:21:59-rgw-wip-jewel-11567---basic-vps/

**Comment by dachary** [comment]
jenkins test this please (jenkins slave failure)

**Comment by dachary** [comment]
@oritwas the rgw run has lots of failures. Are there specific jobs showing this patch does the right thing ?

**Comment by oritwas** [comment]
We have valgrind errors in the teuthology run

**Comment by dachary** [comment]
@oritwas a reminder to explain in the commit message of c128e998558c87c5c6e47e10bec45710342b9b8a why it was necessary to make a jewel only commit (instead of cherry-picking commits) to resolve this issue

**Comment by oritwas** [comment]
@dachary the extra commit is just for testing.
After verifying. I will first merge it to master and backport it here

**Comment by oritwas** [comment]
new run on mira machine type:
http://pulpito.ceph.com/owasserm-2016-10-25_19:45:28-rgw-wip-jewel-11567---basic-mira/
the only valgrind error is for the osd

**Comment by oritwas** [comment]
@dachary this valgrind issue happens only on vps and happens on latest jewel: http://pulpito.ceph.com/owasserm-2016-10-26_11:19:10-rgw-jewel---basic-vps/

We can merge this fix.

**Pull request merged**
