### PR TITLE
DNM: tests: stabilize TestPGLog

### PR DESCRIPTION
**Pull request by dachary**
Do not use EXPECT_DEATH because it is unsafe when there are threads and
lead to intermittent failures.

Fixes: http://tracker.ceph.com/issues/18030

Signed-off-by: Loic Dachary <loic@dachary.org>

### CODE REVIEW

**Comment by dachary** [comment]
@tchaikov I believe this is the right thing to do. I also believe this is an horrible implementation. Would you have a better idea to do the same ?

**Comment by tchaikov** [comment]
```c++
template <bool use_assert=true>
struct PGLog {
  int hello() {
    return 1;
  }
  void pg_assert(bool status);
};

template<>
void PGLog<true>::pg_assert(bool status) {
    assert(status);
}

template <>
inline void PGLog<false>::pg_assert(bool status) {
  if (!status) {
    throw exception{};
  }
}

int main(int argc, const char **argv)
{
  PGLog<true> log;
  log.hello();
  log.pg_assert(false);
}
```

@dachary i have a sample for a templated version of your change. not sure if it's better or worse =)

**Comment by dachary** [comment]
@tchaikov thanks :-) I have to think about that.

**Comment by dachary** [comment]
will reopen when it's sane

**Pull request closed without merging**
