### PR TITLE
mon:validate hit_set values before set

### PR DESCRIPTION
**Pull request by bellaalleb**
Fixes: http://tracker.ceph.com/issues/22659
Signed-off-by: Jing Li lijing@gohighsec.com

### CODE REVIEW

**Comment by bellaalleb** [comment]
@gregsfortytwo Can you help me review this patch? Thanks~

**Comment by gregsfortytwo** [comment]
I think @jecluis did review it, and said you need to add tests...

**Comment by liewegas** [comment]
@jecluis better check than no check, tests or not

**Comment by jecluis** [comment]
@liewegas yeah, fair enough

**Pull request merged**
