### PR TITLE
mgr/cephadm: fallback to normal sorted if cannot import natsorted

### PR DESCRIPTION
**Pull request by rkachach**
This is to provide a simple fallback mechanism in case vstart cannot load orchestrator **natsort** dependency. This could potentially break vstart because of the related issue described in the PR #45643 which has no definitive a fix yet.

Fixes: https://tracker.ceph.com/issues/55113
Signed-off-by: Redouane Kachach <rkachach@redhat.com>

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [x] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Review by adk3798 — APPROVED** [review]

**Review by lxbsz — APPROVED** [review]
It works for me. Thanks.

**Comment by adk3798** [comment]
http://pulpito.front.sepia.ceph.com/adking-2022-03-29_23:26:23-orch:cephadm-wip-adk-testing-2022-03-29-1402-distro-basic-smithi/

Failures:
https://tracker.ceph.com/issues/44587
https://tracker.ceph.com/issues/49287
1 machine failed to install kernel fast enough

**Comment by adk3798** [comment]
> Hi there, what if `sorted` is also not present in my setup? When I did `pip list`, it had no `sorted` or `natsort` in the list, so I had to install `sorted` manually to get it working.

hmm, sorted should be standard python and not need any sort of extra installation to work. It's also what we used before the natsorted addition recently and I haven't heard any complaints about it beforehand.

**Comment by dparmar18** [comment]
> > Hi there, what if `sorted` is also not present in my setup? When I did `pip list`, it had no `sorted` or `natsort` in the list, so I had to install `sorted` manually to get it working.
> 
> hmm, sorted should be standard python and not need any sort of extra installation to work. It's also what we used before the natsorted addition recently and I haven't heard any complaints about it beforehand.

Right, but I did have to install it manually, not sure why. I think there could be some rare scenarios(like mine) where the setup is missing `sorted` therefore some checks could be involved to make sure it doesn't go into the loop again just because it couldn't find that package, just to be 100% foolproof.

**Comment by rkachach** [comment]
@dparmar18 sorted is a builtin function so it must be there by default: https://docs.python.org/3/library/functions.html

**Pull request merged**
