### PR TITLE
examples: replace example go modules with instructions to run

### PR DESCRIPTION
**Pull request by bigjust**
## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [x] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Review by ktdreyer — APPROVED** [review]
For context: the reason we're removing these is that we do not want code scanners to find static, hard-coded version numbers. Other version-number-bumping solutions like dependabot are noisy overkill for demo code that we do not test in CI.

**Review by yuvalif — APPROVED** [review]

**Comment by yuvalif** [comment]
jenkins test api

**Comment by bigjust** [comment]
> can you please add `.gitignore` file in `examples/rgw/golang`:
> 
> ```
> go.sum
> go.mod
> ```

@yuvalif Done!

**Comment by yuvalif** [comment]
@bigjust  why did you close the PR?

**Comment by bigjust** [comment]
I had to delete my branch because the .gitignore wasn't being picked up while using commit --amend, atleast on github. Locally it looked fine. Resubmitted here: https://github.com/ceph/ceph/pull/51423

**Pull request closed without merging**
