### PR TITLE
bash_completion: Install completions to where bash-completion's *.pc says

### PR DESCRIPTION
**Pull request by scop**

### CODE REVIEW

**Comment by tchaikov** [comment]
@scop

```
+ autoconf
configure.ac:1259: error: possibly undefined macro: PKG_CHECK_VAR
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
+ test 1 = 124
+ success=false
```

seems we don't have this macro defined anywhere.

**Comment by scop** [comment]
It should come with pkg-config. I'm not familiar with ceph or its build system or jenkins setup, but I see autogen.sh checks for pkg-config's existence...

**Comment by tchaikov** [comment]
seems the pkg.m4 shipped with centos7 does not include `PKG_CHECK_VAR`. this macro was removed !

**Comment by scop** [comment]
If it was there before, being removed would sound weird to me. Anyway it is included in upstream pkg-config tarball starting from 0.28 (the latest one at the moment, from January 2013), and it is still in git: http://cgit.freedesktop.org/pkg-config/tree/pkg.m4

**Comment by tchaikov** [comment]
@scop 
```
$ rpm -qf /usr/share/aclocal/pkg.m4
pkgconfig-0.27.1-4.el7.x86_64
```

and PKG_CHECK_VAR  is introduced in 0.28: http://lists.freedesktop.org/archives/pkg-config/2013-January/000912.html .

seems rhel7/centos7 didn't backport the goodies. so you might need to define it if it is not defined. which is literally copy it to a local m4 file, and guard it with `m4_ifndef`. please note the license of `pkg.m4` is GPL.

**Comment by scop** [comment]
I think I'm going to leave doing that stuff to someone else who has the environment and interest to make it work with pkgconfig < 0.28.

**Comment by tchaikov** [comment]
yes, we have lots of user still stuck with pkgconfig < 0.28, so i will close this pull request.

**Comment by scop** [comment]
By the way, the >= 0.28 requirement should affect only users who run autotools (autogen.sh), not ones who just run ./configure, their pkgconfig could be older. But if you want to support running autotools on earlier systems, then this would be an issue.

**Comment by branto1** [comment]
Revised PR with fixes mentioned here (and spec file changes):

https://github.com/ceph/ceph/pull/5161

**Pull request closed without merging**
