### PR TITLE
octopus: mgr/volume: subvolume auth_id management and few bug fixes

### PR DESCRIPTION
**Pull request by kotreshhr**
--------------------
backport tracker: https://tracker.ceph.com/issues/48196

backport of https://github.com/ceph/ceph/pull/36998
parent tracker: https://tracker.ceph.com/issues/40401

--------------------

backport tracker: https://tracker.ceph.com/issues/48858

backport of https://github.com/ceph/ceph/pull/38652
parent tracker: https://tracker.ceph.com/issues/48501

--------------------

backport tracker: https://tracker.ceph.com/issues/48900

backport of https://github.com/ceph/ceph/pull/38160
parent tracker: https://tracker.ceph.com/issues/44931

--------------------

backport tracker: https://tracker.ceph.com/issues/49029

backport of https://github.com/ceph/ceph/pull/38786
parent tracker: https://tracker.ceph.com/issues/44928

------------------
backport tracker: https://tracker.ceph.com/issues/49230

backport of https://github.com/ceph/ceph/pull/39038
parent tracker: https://tracker.ceph.com/issues/48830

--------------------
backport tracker: https://tracker.ceph.com/issues/49266

backport of https://github.com/ceph/ceph/pull/39327
parent tracker: https://tracker.ceph.com/issues/49192

-----------------------
Included following commits related to tests as well:
 1. 5945192
 2. The commit 847a7ad is pulled from master for test suite apis. It's part of big PR #32581

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by kotreshhr** [comment]
Teuthology Results:

http://pulpito.front.sepia.ceph.com/khiremat-2021-02-10_07:59:45-fs-wip-khiremat-mgr-authid-bp-0-octopus-distro-basic-smithi/

**Comment by kotreshhr** [comment]
Teuthology result:

http://pulpito.front.sepia.ceph.com/khiremat-2021-02-12_11:22:46-fs-wip-khiremat-mgr-authid-bp-1-octopus-distro-basic-smithi/

**Comment by ajarr** [comment]
@kotreshhr how about commits https://github.com/ceph/ceph/commit/4ca8aaafa32bb7397eec80a8eb366d2dd781a72f and https://github.com/ceph/ceph/commit/59451923d31f5e4f707aa6d22ececc8edd395ca9 
They were backported to nautilus. Maybe do the same here?

**Comment by kotreshhr** [comment]
> @kotreshhr how about commits [4ca8aaa](https://github.com/ceph/ceph/commit/4ca8aaafa32bb7397eec80a8eb366d2dd781a72f) and [5945192](https://github.com/ceph/ceph/commit/59451923d31f5e4f707aa6d22ececc8edd395ca9)

The commit https://github.com/ceph/ceph/commit/4ca8aaafa32bb7397eec80a8eb366d2dd781a72f is already present in octopus.
I will include the https://github.com/ceph/ceph/commit/59451923d31f5e4f707aa6d22ececc8edd395ca9 and update.
> They were backported to nautilus. Maybe do the same here?

**Comment by kotreshhr** [comment]
> > @kotreshhr how about commits [4ca8aaa](https://github.com/ceph/ceph/commit/4ca8aaafa32bb7397eec80a8eb366d2dd781a72f) and [5945192](https://github.com/ceph/ceph/commit/59451923d31f5e4f707aa6d22ececc8edd395ca9)
> 
> The commit [4ca8aaa](https://github.com/ceph/ceph/commit/4ca8aaafa32bb7397eec80a8eb366d2dd781a72f) is already present in octopus.
> I will include the [5945192](https://github.com/ceph/ceph/commit/59451923d31f5e4f707aa6d22ececc8edd395ca9) and update.
> 
> > They were backported to nautilus. Maybe do the same here?

Done

**Comment by kotreshhr** [comment]
Teuthology Results:

http://pulpito.front.sepia.ceph.com/khiremat-2021-02-14_19:04:42-fs-wip-khiremat-mgr-authid-bp-3-octopus-distro-basic-smithi/

**Comment by kotreshhr** [comment]
Rebased and teuthology run:

http://pulpito.front.sepia.ceph.com/khiremat-2021-03-05_10:37:53-fs-wip-khiremat-mgr-authid-bp-7-octopus-distro-basic-smithi/

**Review by ajarr — APPROVED** [review]

**Pull request merged**
