### PR TITLE
luminous: msg/async: backport recent messenger fixes

### PR DESCRIPTION
**Pull request by xiexingguo**
This pr backports the following async-messenger fixes that have been recently identified and successfully merged into master:
https://github.com/ceph/ceph/pull/25755
https://github.com/ceph/ceph/pull/25823
https://github.com/ceph/ceph/pull/25859

This does not follow the normal backport process because the protocol of transport layer of Ceph has been greatly changed for Nautilus.

Related backport tickets:
http://tracker.ceph.com/issues/37897
http://tracker.ceph.com/issues/37905

- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by xiexingguo** [comment]
@liewegas I manually backport some asyn-messenger changes into luminous and mimic. Since the messenger part has been greatly refactored, do you minding double checking this?

**Comment by yuriw** [comment]
[wip-yuri4-testing-2019-02-11-1725-luminous](https://trello.com/c/82sp4VSF/535-wip-yuri4-testing-2019-02-11-1725-luminous)

**Comment by xiexingguo** [comment]
@liewegas Seems we don't want  https://github.com/ceph/ceph/pull/25755/commits/39e8de2d72e2541323f8ed9d8b68075fcbd02701
to be backported.

It turns out the old async-connection implementation will automatically bump
    the global_seq each time it switches to the STATE_CONNECTING state and restarts the connecting process.

See https://github.com/ceph/ceph/blob/luminous/src/msg/async/AsyncConnection.cc#L889

right?

**Comment by liewegas** [comment]
> @liewegas Seems we don't want [39e8de2](https://github.com/ceph/ceph/commit/39e8de2d72e2541323f8ed9d8b68075fcbd02701)
> to be backported.
> 
> It turns out the old async-connection implementation will automatically bump
> the global_seq each time it switches to the STATE_CONNECTING state and restarts the connecting process.
> 
> See https://github.com/ceph/ceph/blob/luminous/src/msg/async/AsyncConnection.cc#L889
> 
> right?

Right!

**Comment by xiexingguo** [comment]
retest this please

**Comment by yuriw** [comment]
[wip-yuri3-testing-2019-02-21-2350-luminous](https://trello.com/c/rVcrtd6V/545-wip-yuri3-testing-2019-02-21-2350-luminous)

**Pull request merged**
