### PR TITLE
doc: cleanups and group tell commands

### PR DESCRIPTION
**Pull request by tchaikov**
## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Review by jdurgin — APPROVED** [review]

**Review by jdurgin — CHANGES_REQUESTED** [review]
whoops, approved too soon. I missed the big theme changes.

I like the rtd theme overall, it looks much more modern. The edit on github link on the upper right is great!

One nit - the hover color on the side toc links is quite constrasting - red text on dark gray is a bit too bright.

**Comment by tchaikov** [comment]
@jdurgin fixed and repushed.

**Comment by tchaikov** [comment]
see https://ceph--39411.org.readthedocs.build/en/39411/api/mon_command_api/#device-info for the rendered output of the API documentation.

**Comment by tchaikov** [comment]
jenkins test api

**Comment by sebastian-philipp** [comment]
Hm, the sphinx_rtd_theme looks generic. like the default theme for any other project out there. Except for some different colors.

**Comment by jdurgin** [comment]
I like it, though I'm no graphic designer. curious what @liewegas thinks

**Comment by liewegas** [comment]
I like the way the content is rendered (nicer colors, fonts), but I like the current them's header/footer format, which extends all way across and replicates the breadcrumbs at the bottom of the page...

**Comment by tchaikov** [comment]
@jdurgin @liewegas i dropped the change switching to sphinx_rtd_theme from this PR.  to change the layout of page i guess i will have to inherit from this theme and change its layout.html. as i am far from an expert in this area, it might take longer. so i will do this in another PR.

**Review by jdurgin — APPROVED** [review]

**Comment by sebastian-philipp** [comment]
thanks kefu!

**Pull request merged**
