### PR TITLE
mgr/orchestrator: Sort 'ceph orch device ls' by host

### PR DESCRIPTION
**Pull request by ricardoasmarques**
This PR will guarantee that `ceph orch device ls` output is always sorted by the `Hostname`.

**Before**
Screenshot from 2020-11-20 10-58-47

**After**
Screenshot from 2020-11-20 11-51-28

Signed-off-by: Ricardo Marques <rimarques@suse.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Review by toabctl — APPROVED** [review]
Thanks

**Review by sebastian-philipp — APPROVED** [review]

**Comment by tchaikov** [comment]
- https://pulpito.ceph.com/kchai-2020-11-26_05:04:35-rados-wip-kefu-testing-2020-11-26-1029-distro-basic-smithi
- https://pulpito.ceph.com/kchai-2020-11-27_02:28:21-rados-wip-kefu-testing-2020-11-26-1029-distro-basic-smithi/

the cephadm failures are due to
```
2020-11-27T02:40:10.388 INFO:teuthology.orchestra.run.smithi062.stderr:DEBUG:cephadm:Running command: /usr/bin/docker pull docker.io/ceph/ceph:v15.2.0
2020-11-27T02:40:10.686 INFO:teuthology.orchestra.run.smithi062.stderr:DEBUG:cephadm:/usr/bin/docker:stderr Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.c
om/increase-rate-limit
```

the "workunits/mon/caps.sh" test failure is tracked by https://tracker.ceph.com/issues/48030

**Comment by smithfarm** [comment]
@sebastian-philipp Will this be included in a mass backport PR?

**Comment by smithfarm** [comment]
> @sebastian-philipp Will this be included in a mass backport PR?

It's not in https://github.com/ceph/ceph/pull/38155 . . . hoping for inclusion in the first December batch backport PR :-)

**Pull request merged**
