### PR TITLE
pybind/rados: notify callback reconnect

### PR DESCRIPTION
**Pull request by NitzanMordhai**
when testing with socket injection, reconnect won't call error callback
for each reconnect, the callback will be called.
changing the callback count of notify by the data and increass only
when the data is changed, if the data is the same, we probably reconnecting
due to socket injection.

Fixes: https://tracker.ceph.com/issues/45721
Signed-off-by: Nitzan Mordechai nmordec@redhat.com

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Review by ljflores — APPROVED** [review]

**Comment by ljflores** [comment]
@NitzanMordhai to test, we could try running a test like http://pulpito.front.sepia.ceph.com/yuriw-2022-08-22_16:21:19-rados-wip-yuri8-testing-2022-08-22-0646-distro-default-smithi/6985089/ 50-100 times to verify instead of running against the whole rados suite.

**Comment by NitzanMordhai** [comment]
> @NitzanMordhai to test, we could try running a test like http://pulpito.front.sepia.ceph.com/yuriw-2022-08-22_16:21:19-rados-wip-yuri8-testing-2022-08-22-0646-distro-default-smithi/6985089/ 50-100 times to verify instead of running against the whole rados suite.

@ljflores good idea, will do it

**Comment by neha-ojha** [comment]
> @ljflores http://pulpito.front.sepia.ceph.com/nmordech-2022-09-08_10:55:54-rados:basic-wip-nitzan-test-rados-watch-notify-callbacks-distro-default-smithi/ 150 jobs scheduled, 11 failed with not related error

@NitzanMordhai do we need any more testing for this PR?

**Comment by NitzanMordhai** [comment]
> @NitzanMordhai do we need any more testing for this PR?

@neha-ojha i think that my run is enough to prove it.

**Pull request merged**
