### PR TITLE
DNM: hammer: osd/ReplicatedPG: fix promotion recency logic

### PR DESCRIPTION
**Pull request by zhouyuan**
http://tracker.ceph.com/issues/14329

### CODE REVIEW

**Comment by zhouyuan** [comment]
@theanalyst   could you please kindly help to have a look? I'm not sure if this is the right way to backport a patch.

**Comment by theanalyst** [comment]
Hi in backports we cherry-pick the respective commit sha using `git cherry-pick -x` so that we have a reference to the original commit in the master branch, can you try doing that from the original pr.. thanks

**Comment by dachary** [comment]
@zhouyuan hi ! Could you please update the backport as @theanalyst suggested ? Thanks :-)

**Comment by rldleblanc** [comment]
Created https://github.com/ceph/ceph/pull/7207 which should incorporate the requested changes.

**Comment by zhouyuan** [comment]
@rldleblanc thanks for the help!

**Pull request closed without merging**
