### PR TITLE
Librbd cache iohint

### PR DESCRIPTION
**Pull request by majianpeng**
make librbd cache handle fadvise flags, especially for noreuse/dontneed.
For read/write with noreuse/dontneed, make the bh into the tail of lru list.

### CODE REVIEW

**Comment by majianpeng** [comment]
@liewegas . Can you review this? Thanks!

**Comment by liewegas** [comment]
Hmm, I'm not sure exactly what semantics we should aim for with NOREUSE.  Does it mean

1. I will not read this again
2. Neither I nor anyone else will read this again

If it's 1, then we should try to avoid affecting the cache at all based on this IO.  Neither push it to the top or the bottom of the LRU.  That way we don't affect caching for other users.  If it's 2, then we should push to the end and/or simply drop it.  I think 2 is what DONTNEED is for, though.

Am I thinking about this wrong?  The way posix_fadvise defines it there is not real concept of different users/clients... instead I think NOREUSE means I *will* use it once soon but not after that (i.e., hint before read).  The way we are using it the hint is attached to the IO itself so that before/after distinction is not very meaningful...

**Comment by liewegas** [comment]
The rest looks correct, but I think we should make sure we have a well defined meaning for these flags.  Sorry that I'm still fuzzy on what they should mean :(

Perhaps defining them carefully in librados.h (or similar) will help make sure we have the right semantics?

**Comment by liewegas** [comment]
Thinking about this a bit more, I think the behavior is fine if you make it only for DONTNEED.  Let's address what NOREUSE means separately.

**Comment by liewegas** [comment]
Ok, a separate patch renamed NOREUSE to NOCACHE so it isn't confused with the POSIX meaning.  Here, let's just focus on DONTNEED and rename the noreuse bool's to dontneed.

With that changed, my only real concern is that we don't break the readx() LRU dance and that the ZERO buffers are handled correctly.

**Comment by majianpeng** [comment]
updated by your suggestion. Thanks your suggestion.
For the NOCACHE, i want to do:
for read op: a)if miss, move bh into bottom and read; b)if hit don't touch bh(still touch ob)
for write op,: a)if miss, move bh into bottom and write; b)if hit don't touch bh
How about this?

**Comment by liewegas** [comment]
That sounds exactly right for NOCACHE.  :)

**Comment by liewegas** [comment]
Looking at readx() and the history more closely it looks like that hit_ls thing was added freaking forever ago (2007), aie.  Your changes look good to me!  I think this patch needs to go through rbd and fs test suites to make sure the caching is working properly.

**Pull request merged**
