### PR TITLE
squid: Telemetry upgrade test fixes

### PR DESCRIPTION
**Pull request by ljflores**
backport tracker: https://tracker.ceph.com/issues/66605

---

backport of https://github.com/ceph/ceph/pull/57974
parent tracker: https://tracker.ceph.com/issues/65189

this backport was staged using ceph-backport.sh version 16.0.0.6848
find the latest version at https://github.com/ceph/ceph/blob/main/src/script/ceph-backport.sh

### CODE REVIEW

**Comment by ljflores** [comment]
Initial tests scheduled here:
https://pulpito.ceph.com/lflores-2024-06-21_22:19:34-upgrade:telemetry-upgrade-squid-distro-default-smithi/

**Comment by yaarith** [comment]
jenkins test docs

**Comment by yaarith** [comment]
jenkins render docs

**Comment by yaarith** [comment]
jenkins test readthedocs

**Comment by yaarith** [comment]
> Initial tests scheduled here: https://pulpito.ceph.com/lflores-2024-06-21_22:19:34-upgrade:telemetry-upgrade-squid-distro-default-smithi/

There was one failure which does not seem related:
https://pulpito.ceph.com/lflores-2024-06-21_22:19:34-upgrade:telemetry-upgrade-squid-distro-default-smithi/7767940/

**Review by yaarith — APPROVED** [review]

**Comment by yaarith** [comment]
The readthedocs test is failing and is unrelated to the changes here.

**Comment by yaarith** [comment]
jenkins test readthedocs

**Comment by ljflores** [comment]
> There was one failure which does not seem related: https://pulpito.ceph.com/lflores-2024-06-21_22:19:34-upgrade:telemetry-upgrade-squid-distro-default-smithi/7767940/

Yeah, this warning can be added to the ignorelist in a separate PR so we can fix it in main too.

**Pull request merged**
