### PR TITLE
monitoring/grafana/build/Makefile: revamp for arm64 builds, pushes to docker and quay, jenkins

### PR DESCRIPTION
**Pull request by dmick**
Fixes: https://tracker.ceph.com/issues/50441

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by dmick** [comment]
I did not request @pereman2 or @Waadkh7, and bots are annoying.  If you want to review, by all means, but I think @pcuzner and @alfonsomthd are right for this

**Comment by tchaikov** [comment]
@epuertat i am afraid this round-robin reviewer assignment could be very confusing.

**Comment by sebastian-philipp** [comment]
Fixes https://tracker.ceph.com/issues/50441

**Comment by epuertat** [comment]
> @epuertat i am afraid this round-robin reviewer assignment could be very confusing.

I know, @tchaikov, but the alternative, using the @ceph/dashboard alias, was too generic, and most of the time no one felt directly compelled to review a specific PR... In any case, there's nothing wrong with adding more/custom reviewers.

**Review by alfonsomthd — APPROVED** [review]

**Comment by dmick** [comment]
Anyone else have any thoughts/suggestions?  If not I will merge

**Pull request merged**
