### PR TITLE
rgw/rados: delete_objs_inline() uses rgw_rados_operate()

### PR DESCRIPTION
**Pull request by cbodley**
IoCtx::operate() will always block. use rgw_rados_operate() so that we can suspend the coroutine when optional_yield is not empty

and a similar change for RGWRados::Object::Read::read()

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Comment by cbodley** [comment]
jenkins test make check

**Review by dang — APPROVED** [review]

**Comment by cbodley** [comment]
jenkins test api

**Comment by cbodley** [comment]
jenkins test windows

**Comment by cbodley** [comment]
passed qa in https://pulpito.ceph.com/cbodley-2024-08-08_20:20:18-rgw-wip-cbodley-testing-distro-default-smithi/

**Pull request merged**
