### PR TITLE
quincy: rgw/notifications: sending metadata in COPY and CompleteMultipartUpload

### PR DESCRIPTION
**Pull request by yuvalif**
backport tracker: https://tracker.ceph.com/issues/58285

---

backport of https://github.com/ceph/ceph/pull/48875
parent tracker: https://tracker.ceph.com/issues/58014

this backport was staged using ceph-backport.sh version 16.0.0.6848
find the latest version at https://github.com/ceph/ceph/blob/main/src/script/ceph-backport.sh

### CODE REVIEW

**Comment by smanjara** [comment]
@yuvalif  Yuri's test found an an amqp notification related failure:
https://pulpito.ceph.com/yuriw-2023-02-22_20:50:25-rgw-wip-yuri7-testing-2023-02-22-0808-quincy-distro-default-smithi/7184272/

`failure_reason: 'Command failed (bucket notification tests against different endpoints)`

**Comment by yuvalif** [comment]
> @yuvalif Yuri's test found an an amqp notification related failure: https://pulpito.ceph.com/yuriw-2023-02-22_20:50:25-rgw-wip-yuri7-testing-2023-02-22-0808-quincy-distro-default-smithi/7184272/
> 
> `failure_reason: 'Command failed (bucket notification tests against different endpoints)`

thanks. the actual error is:
```
======================================================================
2023-02-23T02:48:36.238 INFO:teuthology.orchestra.run.smithi089.stderr:ERROR: test s3 notification of metadata on master
2023-02-23T02:48:36.238 INFO:teuthology.orchestra.run.smithi089.stderr:----------------------------------------------------------------------
2023-02-23T02:48:36.238 INFO:teuthology.orchestra.run.smithi089.stderr:Traceback (most recent call last):
2023-02-23T02:48:36.238 INFO:teuthology.orchestra.run.smithi089.stderr:  File "/usr/lib/python3.6/site-packages/nose/case.py", line 197, in runTest
2023-02-23T02:48:36.238 INFO:teuthology.orchestra.run.smithi089.stderr:    self.test(*self.arg)
2023-02-23T02:48:36.238 INFO:teuthology.orchestra.run.smithi089.stderr:  File "/home/ubuntu/cephtest/ceph/src/test/rgw/bucket_notification/test_bn.py", line 2335, in test_ps_s3_metadata_on_master
2023-02-23T02:48:36.238 INFO:teuthology.orchestra.run.smithi089.stderr:    assert_equal(value[0], meta_value)
2023-02-23T02:48:36.238 INFO:teuthology.orchestra.run.smithi089.stderr:IndexError: list index out of range
```
will investigate

**Comment by yuvalif** [comment]
@yuriw I could not reproduce the issue when running the test locally, so this is probably not a functional issue, but maybe a timing issue with the events sent from amqp. could you please rerun the failed tests?

**Comment by smanjara** [comment]
> @yuriw I could not reproduce the issue when running the test locally, so this is probably not a functional issue, but maybe a timing issue with the events sent from amqp. could you please rerun the failed tests?

hi yuval, there is a failed test coming from` test_bn.py`:

http://qa-proxy.ceph.com/teuthology/yuriw-2023-05-19_15:07:44-rgw-wip-yuri2-testing-2023-05-18-0751-quincy-distro-default-smithi/7278362/teuthology.log

**Comment by yuvalif** [comment]
> > @yuriw I could not reproduce the issue when running the test locally, so this is probably not a functional issue, but maybe a timing issue with the events sent from amqp. could you please rerun the failed tests?
> 
> hi yuval, there is a failed test coming from` test_bn.py`:
> 
> http://qa-proxy.ceph.com/teuthology/yuriw-2023-05-19_15:07:44-rgw-wip-yuri2-testing-2023-05-18-0751-quincy-distro-default-smithi/7278362/teuthology.log

looks like the same issue as in https://github.com/ceph/ceph/pull/50962#issuecomment-1559751594
maybe there is a bug with lifecycle notification on quincy?
can you please check with the quincy baseline?

**Pull request merged**
