### PR TITLE
qa/suites/crimson-rados: bring backfill testing

### PR DESCRIPTION
**Pull request by rzarzynski**
Signed-off-by: Radoslaw Zarzynski <rzarzyns@redhat.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by Matan-B** [comment]
Let's add `crimson_qa_overrides.yaml` to singleton dir as well

**Review by athanatos — APPROVED** [review]
LGTM if it passes!

**Comment by Matan-B** [comment]
https://pulpito.ceph.com/matan-2023-08-21_10:14:07-crimson-rados-main-distro-crimson-smithi/

**Comment by Matan-B** [comment]
This PR can be merged after #53082

**Comment by Matan-B** [comment]
```
crimson/admin/admin_socket: remove path file if it exists #53082
osd/PGLog: return a ready future when found missing objects #53032
crimson/osd/pg: check if backfill_state exists when judging objects' #53031
crimson/osd: put snapmapper's key-value pairs into dedicated objs #52267
qa/suites/crimson-rados: bring backfill testing #48052
crimson/osd/object_context: consider clones found as long as they're in SnapSet::clones #52204
```
https://pulpito.ceph.com/matan-2023-08-24_09:25:19-crimson-rados-wip-matanb-crimson-testing-24.8-v2-distro-crimson-smithi/

**Comment by Matan-B** [comment]
Merging based on:
https://pulpito.ceph.com/matan-2023-08-24_14:53:35-crimson-rados-wip-matanb-crimson-testing-24.8-v3-distro-crimson-smithi/

Failed, unrelated:
7378557, 7378563, 7378597, 7378614 - https://tracker.ceph.com/issues/61651
7378571, 7378575, 7378581, 7378611  - https://tracker.ceph.com/issues/62594
7378560, 7378603, 7378586, 7378601, 7378607, 7378611 - https://tracker.ceph.com/issues/62595

**Comment by Matan-B** [comment]
jenkins test make check

**Comment by Matan-B** [comment]
jenkins test api

**Comment by Matan-B** [comment]
jenkins test api

**Comment by Matan-B** [comment]
jenkins test api

**Pull request merged**
