### PR TITLE
cmake: identify the possible incompatibility of rocksdb and tcmalloc

### PR DESCRIPTION
**Pull request by tchaikov**

### CODE REVIEW

**Comment by jtlayton** [comment]
When trying to build that branch, I get this error:
```
-- Found cython
CMake Error at cmake/modules/BuildRocksDB.cmake:63 (message):
  Incompatible tcmalloc v2.5.93 and rocksdb v5.8.0, please use gperf-tools
  v2.5
Call Stack (most recent call first):
  src/CMakeLists.txt:818 (build_rocksdb)
```
Is that expected with these changes? If so, the error message is not particularly helpful. What does gperf-tools have to do with this? FWIW, I have gperftools-libs-2.5.93-1.fc26.x86_64, so I should be OK, right?

**Comment by tchaikov** [comment]
@jtlayton 

> Is that expected with these changes? 

yes.

> If so, the error message is not particularly helpful. 

i am all ears.

> What does gperf-tools have to do with this?

 see the commit message of https://github.com/ceph/ceph/pull/17788/commits/94fc1f6552e997561bb7f32094537e0c06847659.

> FWIW, I have gperftools-libs-2.5.93-1.fc26.x86_64, so I should be OK, right?

no, you need to either upgrade your gperftools to the latest master or downgrade it to 2.5 (without .93).

**Comment by badone** [comment]
@jtlayton gperftools-libs contains libtcmalloc and this issue is a problem with the interaction of certain versions of rocksdb and tcmalloc. As for gperftools-libs-2.5.93-1.fc26.x86_64 that's the same version I'm running and it's definitely not OK. The reason this has remained undetected since @tchaikov updated rocksdb is that most OS are unaffected (I believe f26 is the only OS so far identified as having this problem).  unittest_rocksdb_option fails in a similar fashion on f26 and yet that unit test has been passing consistently on jenkins systems and presumably others as well.

**Comment by tchaikov** [comment]
http://pulpito.ceph.com/kchai-2017-09-19_14:50:44-rados-wip-kefu-testing-2017-09-19-1954-distro-basic-mira/

**Comment by tchaikov** [comment]
@jtlayton i put some details in the ticket, HTH.

w.r.t. to "If so, the error message is not particularly helpful." i will send a mail to ceph-devel to remind the fc25 users. i agree that the error message can be improved. if anybody can help with it. it will be much appreciated.

**Comment by jtlayton** [comment]
How about "use gperf-tools v2.6 or later" ? Your message says to use v2.5, but that's what I have and it's doesn't work.

**Comment by dmick** [comment]
I'm not saying this is a great idea, but we could maybe also make a local patch to rocksdb to not use alloc_aligned based on the version of libtcmalloc

**Comment by ivancich** [comment]
@tchaikov The error message in `cmake/modules/BuildRocksDB.cmake` is off-by-1. It says "please install gperf-tools 2.5 or **> 2.6.2**" but the code accepts **>= 2.6.2**.

**Comment by tchaikov** [comment]
@jtlayton @ivancich thanks for reviewing this issue , #17901 is posted to address your comments.

**Comment by dillaman** [comment]
Looks like Fedora 26 will release the fix under 2.6.1-5.fc26 so this change is will still prevent Ceph from being built on Fedora 26 since it expect 2.6.2.

[1] https://bugzilla.redhat.com/show_bug.cgi?id=1494309
[2] https://koji.fedoraproject.org/koji/buildinfo?buildID=983827

**Comment by tchaikov** [comment]
@dillaman thanks for the heads-up. i will figure out a way to detect the missing `aligned_alloc()` in an updated cmake script.

**Pull request merged**
