### PR TITLE
osd: Remove aios_size argument from submit_batch

### PR DESCRIPTION
**Pull request by RobinGeuze**
Due to aios_size being a uint16 and the source value for the actual
call being an int there was a possible overflow. This was "fixed"
with an assert, however that still causes a crash.

This pull removes the need for aios_size completely by iterating
over the list and submitting it in max_iodepth batches.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests
- Teuthology
  - [ ] Completed teuthology run
  - [ ] No teuthology test necessary (e.g., documentation)

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by RobinGeuze** [comment]
@tchaikov could you take a look at this? I think its a proper fix for https://tracker.ceph.com/issues/46366

**Comment by RobinGeuze** [comment]
We managed to reproduce the crash described in the issue (and confirmed that it still occurs with master) and verified that this patch fixes it succesfully.

**Review by ljflores — COMMENTED** [review]
Hey @RobinGeuze, can I ask what you did to verify the fix?

Also, per @sebastian-philipp, it looks like this fix may need a test (perhaps a unit test in `test/objectstore/test_bdev.cc` would work).

**Comment by RobinGeuze** [comment]
Hey @ljflores,

We tested this by first reproducing the issue. We set up a minimal ceph cluster (eg 3 OSD's), write some data to it to make sure there is something there. 

Once that is done we kill one of the OSD's. Then we create an object with a very large number of extends, for example using the following python code:
```
import rados

cluster = rados.Rados(conffile='/etc/ceph/ceph.conf')
cluster.connect()

ioctx = cluster.open_ioctx('test')
for i in range(0,1024*1024,2):
    print(i)
    ioctx.write('beep', b'a', i)

print(ioctx.read('beep'))

ioctx.close()
```

If you then bring the OSD back up it will start recovery and crash once it gets to that object. If this patch is applied it does not crash.

I was trying to figure out how to test this properly but I was unable to get teuthology to work locally. Writing a unit test could work though, I might be able to take a look at that later this week.

**Pull request closed without merging**
