### PR TITLE
qa: run cephadm/smoke on opensuse 15.2 instead of 15.1

### PR DESCRIPTION
**Pull request by smithfarm**
Companion PR to https://github.com/ceph/ceph-build/pull/1509

Signed-off-by: Nathan Cutler <ncutler@suse.com>

### CODE REVIEW

**Comment by toabctl** [comment]
We need https://github.com/ceph/ceph-build/pull/1509 be deploed on Jenkins. @djgalloway are you handling that?

**Comment by djgalloway** [comment]
> We need [ceph/ceph-build#1509](https://github.com/ceph/ceph-build/pull/1509) be deployed on Jenkins. @djgalloway are you handling that?

ceph-build.git changes get deployed as soon as they're merged

**Comment by smithfarm** [comment]
```
105/190 Test  #12: run-rbd-unit-tests-127.sh ...............***Failed  200.46 sec
```

**Comment by smithfarm** [comment]
jenkins test make check

**Comment by sebastian-philipp** [comment]
Now, I can no longer schedule teuthology runs:
```
2020-02-25 16:35:55,034.034 INFO:teuthology.suite.run:Scheduling rados/cephadm/smoke/{distro/opensuse_15.1.yaml fixed-2.yaml start.yaml}
Traceback (most recent call last):
  File "/home/swagner/teuthology/virtualenv/bin/teuthology-suite", line 11, in <module>
    load_entry_point('teuthology', 'console_scripts', 'teuthology-suite')()
  File "/home/swagner/teuthology/scripts/suite.py", line 153, in main
    return teuthology.suite.main(args)
  File "/home/swagner/teuthology/teuthology/suite/__init__.py", line 144, in main
    run.prepare_and_schedule()
  File "/home/swagner/teuthology/teuthology/suite/run.py", line 344, in prepare_and_schedule
    num_jobs = self.schedule_suite()
  File "/home/swagner/teuthology/teuthology/suite/run.py", line 548, in schedule_suite
    self.schedule_jobs(jobs_missing_packages, jobs_to_schedule, name)
  File "/home/swagner/teuthology/teuthology/suite/run.py", line 466, in schedule_jobs
    name,
  File "/home/swagner/teuthology/teuthology/suite/util.py", line 72, in schedule_fail
    raise ScheduleFailError(message, name)
teuthology.exceptions.ScheduleFailError: Scheduling swagner-2020-02-25_16:35:15-rados-wip-swagner-testing-2020-02-25-1426-distro-basic-smithi failed: At least one job needs packages that don't exist for hash b99b491fffa55251a14b19e2bab5ef88b7ccc06c.
(virtualenv) swagner@teuthology:~/teuthology$ 
```
https://shaman.ceph.com/builds/ceph/wip-swagner-testing-2020-02-25-1426/b99b491fffa55251a14b19e2bab5ef88b7ccc06c/default/193238/ (25 mins ago)

**Comment by sebastian-philipp** [comment]
Now, I can no longer schedule teuthology runs:
```
2020-02-25 16:35:55,034.034 INFO:teuthology.suite.run:Scheduling rados/cephadm/smoke/{distro/opensuse_15.1.yaml fixed-2.yaml start.yaml}
Traceback (most recent call last):
  File "/home/swagner/teuthology/virtualenv/bin/teuthology-suite", line 11, in <module>
    load_entry_point('teuthology', 'console_scripts', 'teuthology-suite')()
  File "/home/swagner/teuthology/scripts/suite.py", line 153, in main
    return teuthology.suite.main(args)
  File "/home/swagner/teuthology/teuthology/suite/__init__.py", line 144, in main
    run.prepare_and_schedule()
  File "/home/swagner/teuthology/teuthology/suite/run.py", line 344, in prepare_and_schedule
    num_jobs = self.schedule_suite()
  File "/home/swagner/teuthology/teuthology/suite/run.py", line 548, in schedule_suite
    self.schedule_jobs(jobs_missing_packages, jobs_to_schedule, name)
  File "/home/swagner/teuthology/teuthology/suite/run.py", line 466, in schedule_jobs
    name,
  File "/home/swagner/teuthology/teuthology/suite/util.py", line 72, in schedule_fail
    raise ScheduleFailError(message, name)
teuthology.exceptions.ScheduleFailError: Scheduling swagner-2020-02-25_16:35:15-rados-wip-swagner-testing-2020-02-25-1426-distro-basic-smithi failed: At least one job needs packages that don't exist for hash b99b491fffa55251a14b19e2bab5ef88b7ccc06c.
(virtualenv) swagner@teuthology:~/teuthology$ 
```
https://shaman.ceph.com/builds/ceph/wip-swagner-testing-2020-02-25-1426/b99b491fffa55251a14b19e2bab5ef88b7ccc06c/default/193238/ (25 mins ago)

**Comment by smithfarm** [comment]
@sebastian-philipp Can you re-try with `--suite-repo https://github.com/smithfarm/ceph --suite-branch wip-rados-cephadm-smoke-152` ? If that works, we could consider this PR tested and ready to merge.

**Comment by sebastian-philipp** [comment]
> @sebastian-philipp Can you re-try with `--suite-repo https://github.com/smithfarm/ceph --suite-branch wip-rados-cephadm-smoke-152` ? If that works, we could consider this PR tested and ready to merge.

http://pulpito.ceph.com/swagner-2020-02-25_16:47:03-rados-wip-swagner-testing-2020-02-25-1426-distro-basic-smithi/ is scheduled with `--suite-repo https://github.com/smithfarm/ceph --suite-branch wip-rados-cephadm-smoke-152`

**Comment by smithfarm** [comment]
**running** http://pulpito.ceph.com/smithfarm-2020-02-25_16:49:29-rados:cephadm:smoke-master-distro-basic-smithi/

**Comment by smithfarm** [comment]
Sorry, I can't merge this right now - GitHub says it has conflicts (but GitHub has been acting very strangely of late).

**Comment by smithfarm** [comment]
Wow, I've never seen GitHub behaving so strangely...

**Pull request closed without merging**
