### PR TITLE
Assertiveness Training!

### PR DESCRIPTION
**Pull request by adamemerson**
In [this thread,](https://spinics.net/lists/ceph-devel/msg31049.html) it was agreed that we should:

- Use ceph_assert explicitly rather than assert() so we don't need the override
- Replace always-false asserts with ceph_abort()

This frees us up to get rid of the 'clobber guard' that breaks the compiler if the system's assert() macro overrides our own.

(I was in two days of meetings and wanted something to do that was relatively unengaging mentally, so I could still pay attention.)

### CODE REVIEW

**Comment by liewegas** [comment]
Yay!  Needs rebase.  Let's get this tested and merged quickly so we avoid the worst of the conflicts...

**Comment by gregsfortytwo** [comment]
Is there something this PR does, or that we can do in Jenkins, to try and avoid future regressions from people who miss the news or have ingrained habits? ;)

**Comment by adamemerson** [comment]
@liewegas Rebased!

**Comment by liewegas** [comment]
@jdurgin @batrick @yehudasa @dillaman what do you think about merging this on make check pass (vs also running through teuthology)?

**Comment by dillaman** [comment]
@liewegas Since this is pretty straight forward (albeit very large), I'm OK w/ a merge after "make check" pass.

**Pull request merged**
