### PR TITLE
mon: Monitor: validate prefix on handle_command()

### PR DESCRIPTION
**Pull request by liewegas**
http://tracker.ceph.com/issues/16549

### CODE REVIEW

**Comment by liewegas** [comment]
how does on trigger the creation of the backport tickets so i can reference it here?

**Comment by tchaikov** [comment]
@liewegas @xiaoxichen has created a backport ticket for this. i updated the comment with it.

**Comment by dachary** [comment]
> how does one trigger the creation of the backport tickets so i can reference it here?

@liewegas people from the stable release team do it on a regular basis (every other day or so).

**Comment by dachary** [comment]
Hey jenkins, test this please (there is a surprisingly high number of failures)

**Comment by dachary** [comment]
It passed the rados suite http://tracker.ceph.com/issues/16344#note-13

**Pull request merged**
