### PR TITLE
ceph_detect_init: add support for Alpine

### PR DESCRIPTION
**Pull request by dx9**

### CODE REVIEW

**Comment by dachary** [comment]
please test this

@dx9 this is to trigger a make check, not intended for you ;-)

**Comment by dachary** [comment]
@dx9 this commit does two different things: a) it modifies the logic slightly, b) it adds support for alpine. Could you please make it so there are two different commits ? One that modifies the logic and clearly explains in the commit message why this is necessary. And the other that is limited to adding support for alpine.

**Comment by dachary** [comment]
test this please (bluefs crash)

**Comment by dx9** [comment]
@dachary ping

**Comment by tchaikov** [comment]
```
	147 - unittest_http_manager (Timeout)
```
 known issue.

**Comment by dachary** [comment]
Hey jenkins test this please

**Pull request merged**
