### PR TITLE
nautilus: mgr/volume: subvolume auth_id management and few bug fixes

### PR DESCRIPTION
**Pull request by kotreshhr**
--------------------------
backport tracker: https://tracker.ceph.com/issues/48195

backport of https://github.com/ceph/ceph/pull/36998
parent tracker: https://tracker.ceph.com/issues/40401

--------------------
backport tracker: https://tracker.ceph.com/issues/48859

backport of https://github.com/ceph/ceph/pull/38652
parent tracker: https://tracker.ceph.com/issues/48501

--------------------
backport tracker: https://tracker.ceph.com/issues/48901

backport of https://github.com/ceph/ceph/pull/38160
parent tracker: https://tracker.ceph.com/issues/44931

--------------------
backport tracker: https://tracker.ceph.com/issues/49028

backport of https://github.com/ceph/ceph/pull/38786
parent tracker: https://tracker.ceph.com/issues/44928

--------------
backport tracker: https://tracker.ceph.com/issues/49160

backport of https://github.com/ceph/ceph/pull/39038
parent tracker: https://tracker.ceph.com/issues/48830

------------------
backport tracker: https://tracker.ceph.com/issues/49266

backport of #39327
parent tracker: https://tracker.ceph.com/issues/49192

------------------------
Included following commits related to tests as well:

1. https://github.com/ceph/ceph/commit/4ca8aaafa32bb7397eec80a8eb366d2dd781a72f
2. https://github.com/ceph/ceph/commit/59451923d31f5e4f707aa6d22ececc8edd395ca9
3. The commit 847a7ad8c0b is pulled from master for test suite apis. It's part of big PR https://github.com/ceph/ceph/pull/32581

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by kotreshhr** [comment]
http://pulpito.front.sepia.ceph.com/khiremat-2021-02-04_10:50:22-fs-wip-khiremat-mgr-authid-bp-nautilus-5-distro-basic-smithi/

**Comment by kotreshhr** [comment]
jenkins test make check

**Review by ajarr — CHANGES_REQUESTED** [review]
Nice work, Kotresh.

Do we need to add https://github.com/ceph/ceph/pull/39292/commits/113893ec6f748d3baefbdbc2a8749382811aff7a that fixes test_volume_client as part of this PR? We can add that as a different PR but include in the same testing branch, or are the commits intertwined?

The PR to fix mgr/volume tests in master has not merged yet. We'll need to backport the merged commit here instead of https://github.com/ceph/ceph/pull/39292/commits/3aa0bc930dcff25004eaa9f6697ca1a4239b9c5e

**Comment by ajarr** [comment]
@kotreshhr do you think the following commits also need to be backported,
4ca8aaafa32bb7397eec80a8eb366d2dd781a72f
59451923d31f5e4f707aa6d22ececc8edd395ca9

**Comment by kotreshhr** [comment]
> Nice work, Kotresh.
> 
> Do we need to add [113893e](https://github.com/ceph/ceph/commit/113893ec6f748d3baefbdbc2a8749382811aff7a) that fixes test_volume_client as part of this PR? We can add that as a different PR but include in the same testing branch, or are the commits intertwined?

This is already part of this batch.
> 
> The PR to fix mgr/volume tests in master has not merged yet. We'll need to backport the merged commit here instead of [3aa0bc9](https://github.com/ceph/ceph/commit/3aa0bc930dcff25004eaa9f6697ca1a4239b9c5e)

Yes, you are right. I have included that to see if teuthology run looks fine as for some reason those cases are hitting in nautilus branch consistently but I am currently stuck at this crash[1]. I will pull the commit after it's merged in master.

[1] https://tracker.ceph.com/issues/49213

**Comment by kotreshhr** [comment]
> @kotreshhr do you think the following commits also need to be backported,
> [4ca8aaa](https://github.com/ceph/ceph/commit/4ca8aaafa32bb7397eec80a8eb366d2dd781a72f)
> [5945192](https://github.com/ceph/ceph/commit/59451923d31f5e4f707aa6d22ececc8edd395ca9)

Good to have these. I will include them.

**Comment by ajarr** [comment]
@kotreshhr please update the branch with the mgr/volumes test fixes that were merged in master, 
https://github.com/ceph/ceph-ci/commit/4952d2132ffd92594e749a652970d5d9415c721d

Also, as mentioned in the tracker ticket, the MON crash is observed during filesystem removal. Can you try skipping or removing that test_volume_rm  test in the testing branch and run teuthology?

**Comment by ajarr** [comment]
@yuriw I suggest that you remove this from your testing branch. @kotreshhr needs to update this PR. I think it's better if kotresh runs the teuthology tests for this PR.

**Comment by kotreshhr** [comment]
Finally all the tests passed. Thanks @ajarr, adding two test fixes 4ca8aaa, 5945192 helped.

Teuthology Results:

http://pulpito.front.sepia.ceph.com/khiremat-2021-02-12_11:06:00-fs-wip-khiremat-mgr-authid-bp-9-nautilus-distro-basic-smithi/

**Comment by kotreshhr** [comment]
> @kotreshhr please update the branch with the mgr/volumes test fixes that were merged in master,
> [ceph/ceph-ci@4952d21](https://github.com/ceph/ceph-ci/commit/4952d2132ffd92594e749a652970d5d9415c721d)
> 

   Done
> Also, as mentioned in the tracker ticket https://tracker.ceph.com/issues/49213#note-2, the MON crash is observed during filesystem removal. Can you try skipping or removing that test_volume_rm test in the testing branch and run teuthology?

Adding those test cases helped. Didn't have to skip the test case.

**Review by ajarr — APPROVED** [review]

**Comment by batrick** [comment]
follow-up: https://github.com/ceph/ceph/pull/40095

**Pull request merged**
