### PR TITLE
debian: install cephfs-mirror systemd unit files and man page

### PR DESCRIPTION
**Pull request by joscollin**
Fixes: https://tracker.ceph.com/issues/59682

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Review by lxbsz — APPROVED** [review]

**Comment by joscollin** [comment]
Testing is in progress, setting up docker

**Comment by vshankar** [comment]
> Testing is in progress, setting up docker

Change seems correct. Please update here about your tests when done.

**Comment by joscollin** [comment]
jenkins test api

**Comment by joscollin** [comment]
> > Testing is in progress, setting up docker
> 
> Change seems correct. Please update here about your tests when done.

@vshankar 

Please see:

https://2.chacra.ceph.com/r/ceph/wip-B59682-unit-file-manpage-missing/a22abc6f9c619fa6ec3f68867daf16e88ad064de/ubuntu/focal/flavors/default/pool/main/c/ceph/cephfs-mirror_18.0.0-4403-ga22abc6f-1focal_amd64.deb

```
$ dpkg-deb -c cephfs-mirror_18.0.0-4403-ga22abc6f-1focal_amd64.deb
drwxr-xr-x root/root         0 2023-06-14 19:37 ./
drwxr-xr-x root/root         0 2023-06-14 19:37 ./lib/
drwxr-xr-x root/root         0 2023-06-14 19:37 ./lib/systemd/
drwxr-xr-x root/root         0 2023-06-14 19:37 ./lib/systemd/system/
-rw-r--r-- root/root       169 2023-06-14 10:42 ./lib/systemd/system/cephfs-mirror.target
-rw-r--r-- root/root       769 2023-06-14 19:37 ./lib/systemd/system/cephfs-mirror@.service
drwxr-xr-x root/root         0 2023-06-14 19:37 ./usr/
drwxr-xr-x root/root         0 2023-06-14 19:37 ./usr/bin/
-rwxr-xr-x root/root    834040 2023-06-14 19:37 ./usr/bin/cephfs-mirror
drwxr-xr-x root/root         0 2023-06-14 19:37 ./usr/share/
drwxr-xr-x root/root         0 2023-06-14 19:37 ./usr/share/doc/
drwxr-xr-x root/root         0 2023-06-14 19:37 ./usr/share/doc/cephfs-mirror/
-rw-r--r-- root/root      2725 2023-06-14 19:37 ./usr/share/doc/cephfs-mirror/changelog.Debian.gz
drwxr-xr-x root/root         0 2023-06-14 19:37 ./usr/share/man/
drwxr-xr-x root/root         0 2023-06-14 19:37 ./usr/share/man/man8/
-rw-r--r-- root/root      1160 2023-06-14 19:37 ./usr/share/man/man8/cephfs-mirror.8.gz
```

**Review by vshankar — APPROVED** [review]

**Comment by joscollin** [comment]
shaman build: https://shaman.ceph.com/builds/ceph/wip-B59682-unit-file-manpage-missing/

**Comment by vshankar** [comment]
@joscollin minor nit: please change commit and pr title to: debian: install cephfs-mirror systemd unit files and man page.

**Comment by joscollin** [comment]
> @joscollin minor nit: please change commit and pr title to: debian: install cephfs-mirror systemd unit files and man page.

Done.

**Comment by vshankar** [comment]
jenkins test make check

**Pull request merged**
