### PR TITLE
nautilus: cephfs-shell: make compatible with cmd2 versions after 0.9.13

### PR DESCRIPTION
**Pull request by smithfarm**
backport tracker: https://tracker.ceph.com/issues/42327

---

backport of https://github.com/ceph/ceph/pull/30585
parent tracker: https://tracker.ceph.com/issues/42057

this backport was staged using ceph-backport.sh version 15.0.0.6814
find the latest version at https://github.com/ceph/ceph/blob/master/src/script/ceph-backport.sh

### CODE REVIEW

**Comment by smithfarm** [comment]
jenkins test make check

**Comment by smithfarm** [comment]
@batrick still backportable to nautilus, or should be closed/rejected?

**Comment by batrick** [comment]
This one is fairly self-contained. It can be backported since you already did the work.

**Comment by yuriw** [comment]
[wip-yuri6-testing-2020-01-09-1744-nautilus](https://trello.com/c/bfZ3yb9X/798-wip-yuri6-testing-2020-01-09-1744-nautilus)

**Comment by tchaikov** [comment]
jenkins test make check

**Comment by batrick** [comment]
Defer merging this until https://github.com/ceph/ceph/pull/32542 is resolved.

**Comment by rishabh-d-dave** [comment]
OK.

**Comment by ajarr** [comment]
@batrick , I've stopped approving cephfs shell backports (the ones prior to this too) as we discussed.  I realize this one might be needed due to package issues. Do you want me to start looking atthe  cephfs shell backport going forward.

**Comment by smithfarm** [comment]
closing

**Pull request closed without merging**
