### PR TITLE
release-notes.rst: draft 0.94.8 release notes

### PR DESCRIPTION
**Pull request by smithfarm**
Signed-off-by: Nathan Cutler <ncutler@suse.com>

### CODE REVIEW

**Comment by smithfarm** [comment]
```
* build/ops: Add -D_LARGEFILE64_SOURCE to Linux build. (#16611, Ira Cooper)
* build/ops: boost uuid makes valgrind complain (#12736, Sage Weil, Rohan Mars)
* common: add units to rados bench output and clean up formatting (#12248, Dmitry Yatsushkevich, Brad Hubbard, Gu Zhongyan)
* common: config set with negative value results in "error setting 'filestore_merge_threshold' to '-40': (22) Invalid argument" (#13829, Brad Hubbard, Kefu Chai)
* common: linking to -lrbd causes process startup times to balloon (#15225, Richard W.M. Jones)
* doc: fix by-parttypeuuid in ceph-disk(8) nroff (#15867, Ken Dreyer)
* fs: double decreased the count to trim caps which will cause failing to respond to cache pressure (#14319, Zhi Zhang)
* hammer: Scrub error: 0/1 pinned (#15952, Samuel Just)
* hammer: ceph-disk s/by-parttype-uuid/by-parttypeuuid/ (#15867, Nathan Cutler)
* hammer: ceph-osd valgrind invalid reads/writes (#15870, Samuel Just)
* log: do not repeat errors to stderr (#14616, Sage Weil)
* mds: failing file operations on kernel based cephfs mount point leaves unaccessible file behind on hammer 0.94.7 (#16013, Yan, Zheng)
* mds: fix stray purging in 'stripe_count > 1' case (#15050, Yan, Zheng)
* mds: wrongly treat symlink inode as normal file/dir when symlink inode is stale on kcephfs (#15702, Zhi Zhang)
* mon: LibRadosMiscConnectFailure.ConnectFailure (not so intermittent) failure in upgrade/hammer-x  (#13992, Sage Weil)
* mon: Monitor: validate prefix on handle_command() (#16297, You Ji)
* mon: drop pg temps from not the current primary in OSDMonitor (#16127, Samuel Just)
* mon: fix calculation of %USED (#15641, Ruifeng Yang, David Zafman)
* mon: improve reweight_by_utilization() logic (#15686, xie xingguo)
* mon: pool quota alarm is not in effect  (#15478, Danny Al-Gaaf)
* mon: wrong ceph get mdsmap assertion (#14681, Vicente Cheng)
* objecter: LibRadosWatchNotifyPPTests/LibRadosWatchNotifyPP.WatchNotify2Timeout/1 segv (#15760, Sage Weil)
* osd: OSD reporting ENOTEMPTY and crashing (#14766, Samuel Just)
* osd: When generating past intervals due to an import end at pg epoch and fix build_past_intervals_parallel (#12387, #14438, David Zafman)
* osd: acting_primary not updated on split (#15523, Sage Weil)
* osd: assert(!actingbackfill.empty()): old watch timeout tries to queue repop on replica (#15391, Sage Weil)
* osd: assert(rollback_info_trimmed_to == head) in PGLog (#13965, Samuel Just)
* osd: delete one of the repeated op->mark_started in ReplicatedBackend::sub_op_modify_impl (#16572, shun-s)
* osd: fix omap digest compare when scrub (#16000, Xinze Chi)
* osd: is_split crash in handle_pg_create (#15426, Kefu Chai)
* osd: objects unfound after repair (fixed by repeering the pg) (#15006, Jianpeng Ma, Loic Dachary, Kefu Chai)
* osd: rados cppool omap to ec pool crashes osd (#14695, Jianpeng Ma)
* osd: remove all stale osdmaps in handle_osd_map() (#13990, Kefu Chai)
* osd: send write and read sub ops on behalf of client ops at normal priority in ECBackend (#14313, Samuel Just)
* rbd: snap rollback: restore the link to parent (#14512, Alexey Sheplyakov)
* rgw: S3: set EncodingType in ListBucketResult (#15896, Victor Makarov, Robin H. Johnson)
* rgw: backport rgwx-copy-if-newer for radosgw-agent (#16262, Yehuda Sadeh)
* rgw: bucket listing following object delete is partial (#14826, Orit Wasserman)
* rgw: convert plain object to versioned (with null version) when removing (#15243, Yehuda Sadeh)
* rgw: fix multi-delete query param parsing. (#16618, Robin H. Johnson)
* rgw: have a flavor of bucket deletion to bypass GC and to trigger (#15557, Pavan Rallabhandi)
* rgw: keep track of written_objs correctly (#15886, Yehuda Sadeh)
* rgw: multipart ListPartsResult has missing quotes on ETag (#15334, xie xingguo, Robin H. Johnson)
* rgw: no Last-Modified, Content-Size and X-Object-Manifest headers if no segments in DLO manifest (#15812, Radoslaw Zarzynski)
* rgw: radosgw server abort when user passed bad parameters to set quota (#14190, #14191, Dunrong Huang)
* rgw: radosgw-admin region-map set is not reporting the bucket quota correctly (#16815, Yehuda Sadeh, Orit Wasserman)
* rgw: refrain from sending Content-Type/Content-Length for 304 responses (#16327, #13582, #15119, #14005, Yehuda Sadeh, Nathan Cutler, Wido den Hollander)
* rgw: remove bucket index objects when deleting the bucket (#16412, Orit Wasserman)
* rgw: set Access-Control-Allow-Origin to an asterisk if allowed in a rule (#15348, Wido den Hollander)
* rgw: subset of uploaded objects via radosgw are unretrievable when using EC pool (#15745, Yehuda Sadeh)
* rgw: subuser rm fails with status 125 (#14375, Orit Wasserman)
* rgw: the swift key remains after removing a subuser (#12890, #14375, Orit Wasserman, Sangdi Xu)
* rgw: user quota may not adjust on bucket removal (#14507, Edward Yang)
* tests: be more generous with test timeout (#15403, Loic Dachary)
* tests: qa/workunits/rbd: respect RBD_CREATE_ARGS environment variable (#16289, Mykola Golub)
```

**Comment by dachary** [comment]
There are extra hammer prefix here:
<pre>
* hammer: Scrub error: 0/1 pinned (#15952, Samuel Just)
* hammer: ceph-disk s/by-parttype-uuid/by-parttypeuuid/ (#15867, Nathan Cutler)
* hammer: ceph-osd valgrind invalid reads/writes (#15870, Samuel Just)
</pre>

**Comment by smithfarm** [comment]
@dachary Yes, I am aware. The first of these refers to #9496 which was reverted by #9521, so it can be dropped I think. 

The second is a ceph-disk PR - which prefix would you suggest?

The third is #9238 - which prefix would you suggest?

**Comment by smithfarm** [comment]
@dachary Also, did you notice the text version of the release notes shows only the tracker issue number, and not the pr number?

**Comment by dachary** [comment]
> The second is a ceph-disk PR - which prefix would you suggest?

build/ops seems appropriate

**Comment by dachary** [comment]
https://github.com/ceph/ceph/pull/9238 could be msg

**Comment by dachary** [comment]
> did you notice the text version of the release notes shows only the tracker issue number, and not the pr number?

IIRC that was intentional to not clutter the output with references that relate to different namespaces

**Comment by smithfarm** [comment]
Updated the commit and https://github.com/ceph/ceph/pull/10730#issuecomment-239782755

**Pull request merged**
