### PR TITLE
Wip scrub optimization

### PR DESCRIPTION
**Pull request by dragonylffly**
Scrub optimization

Step 1 
'ceph pg get_inconsistent_pgs ' which gets the ids of all inconsistent pgs
Step 2
'ceph pg \<pgid\> get_inconsistent_objects' which gets the ids of all inconsistent objects 
in a specified pg
Step 3
'ceph pg \<pgid\> get_inconsistent_info \<object\>' which gets the inconsistent information 
of the specified object
Step 4
'set_scrub_read_shard()' which enables to set the target osd to read the specified copy 
of an object to determine which one to use for repairing
Step 5
'ceph pg repair_object \<object\> \<osd\>' which uses the object on a specified osd to repair 
the other copies

### CODE REVIEW

**Comment by dragonylffly** [comment]
@liewegas @athanatos your comments are appreciated

**Comment by tchaikov** [comment]
@dragonylffly this pr dups with #6898 . i will take a closer look at your pr tomorrow.

**Comment by liewegas** [comment]
@tchaikov

**Comment by tchaikov** [comment]
@dragonylffly the majority of your work is duplicated with my pull request of #6898. and @dzafman has been on this scrub/repair features for quite a while also. if you please, probably we can work together? otherwise precious time and efforts might be wasted.

anyway, there are some issues i observed:

1. in addition to the pg commands, we need to expose the inconsistent_info using librados API(s), and we will have python bindings for them.
1. better off using the temporary objects for holding the inconsistent_t omap attributes. so they can be wiped off automatically if the pg interval passes
1. you need to pass the start epoch of the PG interval when the scrub is performed.
1. and tests are missing (that's why i marked my pr with DNM =).

**Comment by 363921219** [comment]
@tchaikov I have read your pull request of #6898 and learn a lot.I am new to ceph, it will be my pleasure to work with you.Please feel free to tell me if there is anything I can help.

**Comment by tchaikov** [comment]
@363921219 david is working on the recovery/scrub read. and i am working on rework on my pr to address sam's comments. if you are interested, probably you can write up the python binding for them and work on the recovery/scrub write for this feature. but better off sending your intention/idea to the mailing list to get the attention of interested parties so we can avoid repeat work.

**Pull request closed without merging**
