### PR TITLE
mimic: cephfs: config: drop config::lock when invoking config observer

### PR DESCRIPTION
**Pull request by vshankar**
https://tracker.ceph.com/issues/37761
https://tracker.ceph.com/issues/41770

### CODE REVIEW

**Comment by dillaman** [comment]
Note: this introduces a potential crash -- DNM until [1] is ready for backport.

[1] https://tracker.ceph.com/issues/41354

**Comment by smithfarm** [comment]
@vshankar Please take a look at @dillaman 's comment, above, and - if appropriate - cherry-pick https://github.com/ceph/ceph/pull/29809 into this PR?

**Comment by vshankar** [comment]
> @vshankar Please take a look at @dillaman 's comment, above, and - if appropriate - cherry-pick #29809 into this PR?

ack -- make sense. I'll update when done.

**Comment by yuriw** [comment]
[wip-yuri8-testing-2019-10-29-1542-mimic](https://trello.com/c/2vRMZAh0/735-wip-yuri8-testing-2019-10-29-1542-mimic)

**Comment by yuriw** [comment]
this PR seems to have broken the build 
https://shaman.ceph.com/builds/ceph/wip-yuri8-testing-2019-10-29-1542-mimic/

differing for now

**Comment by smithfarm** [comment]
centos 7 default build error is:

```
[ 90%] Linking CXX executable ../../../bin/ceph_test_librbd_api
/opt/rh/devtoolset-7/root/usr/libexec/gcc/x86_64-redhat-linux/7/ld: ../librados/CMakeFiles/libradostest_obj.dir/test.cc.o: undefined reference to symbol '_ZN4ceph18__ceph_assert_failERKNS_11assert_dataE'
/home/jenkins-build/build/workspace/ceph-dev-new-build/ARCH/x86_64/AVAILABLE_ARCH/x86_64/AVAILABLE_DIST/centos7/DIST/centos7/MACHINE_SIZE/huge/release/13.2.6-855-gf0cda2e/rpm/el7/BUILD/ceph-13.2.6-855-gf0cda2e/build/lib/libceph-common.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [bin/ceph_test_librbd_api] Error 1
```

**Comment by vshankar** [comment]
> [ 90%] Linking CXX executable ../../../bin/ceph_test_librbd_api
> /opt/rh/devtoolset-7/root/usr/libexec/gcc/x86_64-redhat-linux/7/ld: ../librados/CMakeFiles/libradostest_obj.dir/test.cc.o: undefined reference to symbol '_ZN4ceph18__ceph_assert_failERKNS_11assert_dataE'
> /home/jenkins-build/build/workspace/ceph-dev-new-build/ARCH/x86_64/AVAILABLE_ARCH/x86_64/AVAILABLE_DIST/centos7/DIST/centos7/MACHINE_SIZE/huge/release/13.2.6-855-gf0cda2e/rpm/el7/BUILD/ceph-13.2.6-855-gf0cda2e/build/lib/libceph-common.so.0: error adding symbols: DSO missing from command line
> collect2: error: ld returned 1 exit status
> make[2]: *** [bin/ceph_test_librbd_api] Error 1

will take a look -- build is fine here but fails on shaman.

**Comment by smithfarm** [comment]
@vshankar Thanks - adding DNM for now.

**Comment by vshankar** [comment]
> centos 7 default build error is:
> 
> ```
> [ 90%] Linking CXX executable ../../../bin/ceph_test_librbd_api
> /opt/rh/devtoolset-7/root/usr/libexec/gcc/x86_64-redhat-linux/7/ld: ../librados/CMakeFiles/libradostest_obj.dir/test.cc.o: undefined reference to symbol '_ZN4ceph18__ceph_assert_failERKNS_11assert_dataE'
> /home/jenkins-build/build/workspace/ceph-dev-new-build/ARCH/x86_64/AVAILABLE_ARCH/x86_64/AVAILABLE_DIST/centos7/DIST/centos7/MACHINE_SIZE/huge/release/13.2.6-855-gf0cda2e/rpm/el7/BUILD/ceph-13.2.6-855-gf0cda2e/build/lib/libceph-common.so.0: error adding symbols: DSO missing from command line
> collect2: error: ld returned 1 exit status
> make[2]: *** [bin/ceph_test_librbd_api] Error 1
> ```

Required this change for a clean build on centos

```
diff --git a/src/test/librbd/CMakeLists.txt b/src/test/librbd/CMakeLists.txt
index 60502d1d01..d7e9c94ed3 100644
--- a/src/test/librbd/CMakeLists.txt
+++ b/src/test/librbd/CMakeLists.txt
@@ -139,6 +139,7 @@ add_executable(ceph_test_librbd_api
 target_link_libraries(ceph_test_librbd_api
   librbd
   librados
+  ceph-common
   ${UNITTEST_LIBS})
 set_target_properties(ceph_test_librbd_api PROPERTIES COMPILE_FLAGS
   ${UNITTEST_CXX_FLAGS})

```

However, builds fine on luminous without the above change. CMake changes somewhere?

**Comment by vshankar** [comment]
@smithfarm -- any suggestions on comment https://github.com/ceph/ceph/pull/29664#issuecomment-554848170

**Comment by smithfarm** [comment]
I don't have a problem to include that patch here in this PR - just explain in the commit message that it's intentionally targeting mimic because the issue only affects mimic.

**Comment by tchaikov** [comment]
> > @vshankar Please take a look at @dillaman 's comment, above, and - if appropriate - cherry-pick #29809 into this PR?
> 
> ack -- make sense. I'll update when done.

i still cannot find cherry-picked 0cc2dd7bd1021dd8b5e22850495ce97da7d98716 in this PR.

**Comment by vshankar** [comment]
> i still cannot find cherry-picked [0cc2dd7](https://github.com/ceph/ceph/commit/0cc2dd7bd1021dd8b5e22850495ce97da7d98716) in this PR.

I backported that earlier -- got missed when fixing the build issue.

will resend.

**Comment by batrick** [comment]
Closing as Mimic is EOL.

**Pull request closed without merging**
