### PR TITLE
nautilus: rgw: cloud sync module fails to sync multipart objects

### PR DESCRIPTION
**Pull request by theanalyst**
http://tracker.ceph.com/issues/39684

- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by smithfarm** [comment]
@theanalyst Please don't flag for integration testing until "make check" has passed.

**Comment by smithfarm** [comment]
pedantic nit: The 3rd commit is missing the line `Conflicts:` (above the name of the file that had the conflicts)

**Comment by smithfarm** [comment]
Removing the`nautilus-batch-1` label, since the PR has not passed make check yet.

**Comment by theanalyst** [comment]
jenkins test this please

**Comment by theanalyst** [comment]
Previous build error seems environmental 
`stty: standard input: Inappropriate ioctl for device` during unittest run

**Comment by smithfarm** [comment]
jenkins re-test this please

**Comment by yuriw** [comment]
[wip-yuri-testing-2019-05-28-1953-nautilus](https://trello.com/c/OIoMDdvj/620-wip-yuri-testing-2019-05-28-1953-nautilus)

**Pull request merged**
