### PR TITLE
rgw: add option for relaxed region enforcement

### PR DESCRIPTION
**Pull request by mattbenjamin**
Fixes: http://tracker.ceph.com/issues/24507

Signed-off-by: Matt Benjamin <mbenjamin@redhat.com>

### CODE REVIEW

**Comment by mattbenjamin** [comment]
http://pulpito.ceph.com/mbenjamin-2018-06-13_14:00:27-rgw-wip-rgw-24507-distro-basic-smithi/

**Comment by mattbenjamin** [comment]
jenkins retest this please

**Comment by yehudasa** [comment]
@mattbenjamin is the bucket going to be created on the correct region (the one the request was sent to)?

**Comment by mattbenjamin** [comment]
@yehudasa the issue is with specific legacy environments where that will be the case, but 3rd party applications are sending inconsistent region information not under site control

**Comment by yehudasa** [comment]
@mattbenjamin yes, I understand. Just need to make sure that the ending bucket is created in the region (that is: its home region is) where this request is served, and not at a different region.

**Comment by mattbenjamin** [comment]
@yehudasa, @cbodley this is intended only for use at sites which aren't using multi-site replication, so that situation should not arise?  do we need to document this intention?

**Pull request merged**
