### PR TITLE
quincy: mds/client: fail the request if the peer MDS doesn't support getvxattr op

### PR DESCRIPTION
**Pull request by lxbsz**
backport tracker: https://tracker.ceph.com/issues/57240 and https://tracker.ceph.com/issues/57362

---

backport of https://github.com/ceph/ceph/pull/47182 and https://github.com/ceph/ceph/pull/45307
parent tracker: https://tracker.ceph.com/issues/56529 and https://tracker.ceph.com/issues/54461

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by yuriw** [comment]
@vshankar is fixing ref: https://trello.com/c/s9pGC2JL

**Comment by ljflores** [comment]
jenkins test make check

**Comment by ljflores** [comment]
Rados suite review: https://pulpito.ceph.com/?branch=wip-yuri6-testing-2022-09-06-1353-quincy

Failures, unrelated:
    1. https://tracker.ceph.com/issues/57165 -- pending Quincy backport
    2. https://tracker.ceph.com/issues/57290 -- pending Quincy backport
    3. https://tracker.ceph.com/issues/57269
    4. https://tracker.ceph.com/issues/49287
    5. https://tracker.ceph.com/issues/56951

Details:
    1. expected valgrind issues and found none - Ceph - RADOS
    2. orch/cephadm: task/test_cephadm failure due to: ERROR: A cluster with the same fsid '00000000-0000-0000-0000-0000deadbeef' already exists. - Ceph - Orchestrator
    3. rook: unable to read URL "https://docs.projectcalico.org/manifests/tigera-operator.yaml" - Ceph - Orchestrator
    4. podman: setting cgroup config for procHooks process caused: Unit libpod-$hash.scope not found - Ceph - Orchestrator
    5. rook/smoke: Updating cephclusters/rook-ceph is forbidden - Ceph - Orchestrator

**Comment by vshankar** [comment]
@lxbsz This change was breaking scheduling teuthology tests

```
  File "/home/yuriw/teuthology/teuthology/suite/build_matrix.py", line 136, in _build_matrix
    fn)
  File "/home/yuriw/teuthology/teuthology/suite/build_matrix.py", line 136, in _build_matrix
    fn)
  File "/home/yuriw/teuthology/teuthology/suite/build_matrix.py", line 80, in _build_matrix
    raise IOError('%s does not exist (abs %s)' % (path, os.path.abspath(path)))
OSError: /home/yuriw/src/github.com_ceph_ceph-c_wip-yuri6-testing-2022-09-06-1353-quincy/qa/suites/fs/upgrade/upgraded_client/from_nautilus/overrides/ignorelist_health.yaml does not exist (abs /home/yuriw/src/github.com_ceph_ceph-c_wip-yuri6-testing-2022-09-06-1353-quincy/qa/suites/fs/upgrade/upgraded_client/from_nautilus/overrides/ignorelist_health.yaml)```

**Comment by lxbsz** [comment]
> @lxbsz This change was breaking scheduling teuthology tests
> 
> ```
>   File "/home/yuriw/teuthology/teuthology/suite/build_matrix.py", line 136, in _build_matrix
>     fn)
>   File "/home/yuriw/teuthology/teuthology/suite/build_matrix.py", line 136, in _build_matrix
>     fn)
>   File "/home/yuriw/teuthology/teuthology/suite/build_matrix.py", line 80, in _build_matrix
>     raise IOError('%s does not exist (abs %s)' % (path, os.path.abspath(path)))
> OSError: /home/yuriw/src/github.com_ceph_ceph-c_wip-yuri6-testing-2022-09-06-1353-quincy/qa/suites/fs/upgrade/upgraded_client/from_nautilus/overrides/ignorelist_health.yaml does not exist (abs /home/yuriw/src/github.com_ceph_ceph-c_wip-yuri6-testing-2022-09-06-1353-quincy/qa/suites/fs/upgrade/upgraded_client/from_nautilus/overrides/ignorelist_health.yaml)```
> ```

On dependency was missed. And I have backported it.

**Comment by vshankar** [comment]
jenkins retest this please

**Comment by ljflores** [comment]
Rados suite review: http://pulpito.front.sepia.ceph.com/?branch=wip-yuri6-testing-2022-09-23-1008-quincy

Failures, unrelated:
    1. https://tracker.ceph.com/issues/57386
    2. https://tracker.ceph.com/issues/57311
    3. https://tracker.ceph.com/issues/56951
    4. https://tracker.ceph.com/issues/57165 -- pending Quincy backport

Details:
    1. cephadm/test_dashboard_e2e.sh: Expected to find content: '/^foo$/' within the selector: 'cd-modal .badge' but never did - Ceph - Mgr - Dashboard
    2. rook: ensure CRDs are installed first - Ceph - Orchestrator
    3. ook/smoke: Updating cephclusters/rook-ceph is forbidden - Ceph - Orchestrator
    4. expected valgrind issues and found none - Ceph - RADOS

**Review by vshankar — APPROVED** [review]

**Pull request merged**
