### PR TITLE
cmake: bump the required boost version to 1.73

### PR DESCRIPTION
**Pull request by wjwithagen**
Otherwise it will complain (on FreeBSD/Clang):
```

/home/jenkins/workspace/ceph-master-compile/src/librbd/migration/HttpClient.cc:699:37: error: no member named 'host_name_verification' in namespace 'boost::asio::ssl'
      [host, next=boost::asio::ssl::host_name_verification(host),
                  ~~~~~~~~~~~~~~~~~~^
/home/jenkins/workspace/ceph-master-compile/src/librbd/migration/HttpClient.cc:714:16: error: no matching function for call to 'next'
        return next(preverified, ctx);
               ^~~~
```

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Review by tchaikov — CHANGES_REQUESTED** [review]
could you revise the title of commit message so lt looks like:

> cmake: bump the required boost version to 1.73
>
> because ssl::host_name_verification was introduced in Asio 1.16.1 / Boost 1.73, and we
> are using this class in src/librbd/migration/HttpClient.cc
> 
> without this change, on a host with boost 1.72
>
> /home/jenkins/workspace/ceph-master-compile/src/librbd/migration/HttpClient.cc:699:37: 

> error: no member named 'host_name_verification' in namespace 'boost::asio::ssl'
>       [host, next=boost::asio::ssl::host_name_verification(host),
>                   ~~~~~~~~~~~~~~~~~~^
> /home/jenkins/workspace/ceph-master-compile/src/librbd/migration/HttpClient.cc:714:16: error: no matching function for call to 'next'
>         return next(preverified, ctx);
>                ^~~~

**Comment by tchaikov** [comment]
@wjwithagen please note the first comment in a PR is not the same thing as the commit message. also I'd suggest explain the reason of the change in commit message. IMHO, sometimes, the fixes we create start with observing but we should not stop there, we'd better find a verified reasoning of the fix.

**Comment by wjwithagen** [comment]
@tchaikov 
It is even a documented "feature" in Boost.
https://cplusplus.github.io/LWG/issue3171

Fixed the commit.

**Comment by tchaikov** [comment]
@wjwithagen I took the liberty and updated the title also.

**Review by tchaikov — APPROVED** [review]
thanks!

**Comment by tchaikov** [comment]
https://shaman.ceph.com/builds/ceph/wip-kefu-testing-2021-04-02-1506/3d0f85a6c3046372f708a5f2893231db573d2f75/

**Pull request merged**
