### PR TITLE
doc/bootstrap: Add zypper as package management option + minor tweaks

### PR DESCRIPTION
**Pull request by krig**
Just some minor tweaks to the bootstrap document.

## Checklist
- [ ] References tracker ticket
- [x] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by krig** [comment]
@batrick any chance of merging this?

**Comment by sebastian-philipp** [comment]
I'll take care of this, as soon as I have some spare time

**Comment by sebastian-philipp** [comment]
> LGTM. Proceed.

won't wok. I think this pr is stale now.

**Comment by zdover23** [comment]
In my opinion, the matter in this PR has been covered by two things:
1) cephadm, which works differently that ceph-deploy, and
2) doc/cephadm/install.rst, which contains commands that are functionally equivalent to the ones here.

I therefore recommend that this bug be closed, and if SebastianW agrees with me, I think that should be an end on the matter.

**Pull request closed without merging**
