### PR TITLE
doc: fix up rbd snapshot docs around crash consistency

### PR DESCRIPTION
**Pull request by gregsfortytwo**
Signed-off-by: Greg Farnum <gfarnum@redhat.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by gregsfortytwo** [comment]
I just had a coworker point me at this language — unless I'm wildly mistaken, rbd snapshots are *exactly* crash-consistent. @anthonyeleven, can you discuss why you swapped this language? Crash consistency is well defined, and requiring an fsck on filesystems which don't journal is expected behavior, so there's certainly nothing in the documentation explaining why it wouldn't be crash consistent.

**Comment by anthonyeleven** [comment]
> I just had a coworker point me at this language — unless I'm wildly mistaken, rbd snapshots are _exactly_ crash-consistent. @anthonyeleven, can you discuss why you swapped this language? Crash consistency is well defined, and requiring an fsck on filesystems which don't journal is expected behavior, so there's certainly nothing in the documentation explaining why it wouldn't be crash consistent.

Hmm.  Prior language was
```
.. note:: Because RBD does not know about the file system, snapshots are
	  `crash-consistent` if they are not coordinated with the mounting
	  computer. So, we recommend you stop `I/O` before taking a snapshot of
	  an image. If the image contains a file system, the file system must be
	  in a consistent state before taking a snapshot or you may have to run
	  `fsck`. To stop `I/O` you can use `fsfreeze` command. See`
```

When I read through that at the time I tripped trying to parse what it was saying, and one of my ongoing doc goals is to improve ambiguities in phrasing.  There seemed to be a recommendation of stopping IO before snapping as a consequence of `Because RBD does not know about the file system`.  

That said, I operated an environment where RBD snapshots were frequent, and I doubt that many if any users paused IO to make them -- and I don't recall any corruption that wasn't tied to a certain ZFS / *BSD combination.  So I think your interpretation is more correct.

`quiesce` is a traditional term in this context, but I've found that a lot of people don't know it, which is why I left `stop`.  ymmv, I have no issue with changing it.

wrt your change here, I suggest `a` vs `an` here:

```s/may need an `fsck` pass/may need a `fsck` pass/```

and writing `when` instead of `unless`:

```
`s/snapshots are only `crash-consistent` unless they are/snapshots are `crash-consistent` when they are/`
```

**Review by sunnyku — APPROVED** [review]
Thanks.

**Review by trociny — APPROVED** [review]
LGTM

**Pull request merged**
