### PR TITLE
doc/cephadm: Update operations.rst

### PR DESCRIPTION
**Pull request by rhkelson**
Fixed typo 'no' to 'not' in sentence "If this test fails, cephadm will no be able to manage services on that host."

Signed-off-by: rhkelson <119636079+rhkelson@users.noreply.github.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [x] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [x] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Comment by anthonyeleven** [comment]
Thanks for contributing!  Please sign your commits and the PR itself, and fill out the checklist.  https://docs.ceph.com/en/quincy/start/documenting-ceph/#commit-the-change

**Review by adk3798 — APPROVED** [review]

**Comment by adk3798** [comment]
@rhkelson the change itself is good, but the requires signed-off-by check will fail until this is resolved
```
The title/s of following commit/s is/are not started with 'doc', but they only touch files under 'doc/
```
basically, the commit title needs to be `doc/cephadm: Update operations.rst` and then it should be all good.

**Review by anthonyeleven — APPROVED** [review]

**Comment by anthonyeleven** [comment]
Bump

**Comment by anthonyeleven** [comment]
jenkins retest this please

**Comment by adk3798** [comment]
```
"The title/s of following commit/s is/are not started with 'doc', but they only touch files under 'doc/'. Please make sure the commit titles",
"are started with 'doc'. See the 'Submitting Patches' guide:",
"https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst#commit-title",
 ""] +
```

**Comment by zdover23** [comment]
jenkins retest this please

**Comment by zdover23** [comment]
https://github.com/ceph/ceph/pull/60637 - Squid backport
https://github.com/ceph/ceph/pull/60638 - Reef backport
https://github.com/ceph/ceph/pull/60639 - Quincy backport

**Pull request merged**
