### PR TITLE
ceph_test_keyvaluedb_iterators: Fix broken test

### PR DESCRIPTION
**Pull request by yuyuyu101**
Introduced by #6312
Signed-off-by: Haomai Wang <haomai@xsky.com>

### CODE REVIEW

**Comment by liewegas** [comment]
@branch-predictor have time to look?

**Comment by branch-predictor** [comment]
@yuyuyu101 why you consider it broken? Assumption was the raw key has the format "prefix\0key", so it works for that case and when raw key is just "prefix". This change modifies this assumption, so the raw key is expected to be only "prefix".

**Comment by yuyuyu101** [comment]
@branch-predictor KeyValueMemoryDB already separate the prefix and the key. We don't need to split this.

**Comment by branch-predictor** [comment]
@yuyuyu101 OK, lgtm then.

**Pull request merged**
