### PR TITLE
cmake: WITH_GTEST_PARALLEL only with WITH_PYTHON2

### PR DESCRIPTION
**Pull request by smithfarm**
(See commit message)

### CODE REVIEW

**Comment by smithfarm** [comment]
Alternative to https://github.com/ceph/ceph/pull/22924

**Comment by smithfarm** [comment]
Hm, `WARNING` appends a call stack:
```
-- Found PythonInterp: /usr/bin/python3 (found version "3.6.5")
CMake Warning at cmake/modules/AddCephTest.cmake:29 (message):
  No Python 2: disabling WITH_GTEST_PARALLEL
Call Stack (most recent call first):
  src/test/CMakeLists.txt:1 (include)

```

**Comment by tchaikov** [comment]
@smithfarm thanks for updating the PR, i think probably we can disable this feature in `run-make-check.sh`? as we are enabling it there, and we also check for the existence of python2 out there also.

**Comment by smithfarm** [comment]
@tchaikov Yes, we could, but then the bug would still bite anyone running "make check" directly (i.e. not using run-make-check.sh) while setting -DWITH_GTEST_PARALLEL=ON without py2 being available, right?

**Comment by tchaikov** [comment]
@smithfarm then we might want to error out if `-DWITH_GTEST_PARALLEL=ON` on a host w/o python2 instead disabling it against user's will. what do you think?

**Comment by smithfarm** [comment]
@tchaikov Yes, I agree. Fixed.

**Comment by smithfarm** [comment]
Added the run-make-check.sh commit to https://github.com/ceph/ceph/pull/22867

**Comment by tchaikov** [comment]
@smithfarm i just took a closer look at gtest-//, it does support py3.  could you help test #22931 ?

**Comment by smithfarm** [comment]
It does not support py3. I tried it.

**Comment by tchaikov** [comment]
and this change does not look right, as gtest-parallel is orthogonal with WITH_PYTHON2. what gtest-parallel depends on is a python2 interpreter, not a librados binding for python2.

**Comment by smithfarm** [comment]
@tchaikov I guess you're right. But, read on.

At the moment, `-DWITH_PYTHON2=ON` ensures that the python2 interpreter is available in the build environment, via the build dependency https://github.com/ceph/ceph/blob/master/ceph.spec.in#L156

Conversely, if building with `-DWITH_PYTHON2=OFF`, there is a high probability that a python2 interpreter is not available since why else would it be disabled?

Anyway, I guess your PR https://github.com/ceph/ceph/pull/22931 renders this one obsolete? If so, feel free to close.

**Comment by tchaikov** [comment]
> there is a high probability that a python2 interpreter is not available since why else would it be disabled

hmm, i cannot make the call on behalf of our user.

**Pull request closed without merging**
