### PR TITLE
wip: rgw: check keystone auth also for s3 post requests

### PR DESCRIPTION
**Pull request by theanalyst**
This patch adds keystone auth for s3 post requests, once a user fails in
cephx authentication, they are checked for keystone if configured.
This fixes about 17 failures in #10062 caused on post request.
Fixes: #10062
Signed-off-by: Abhishek Lekshmanan <abhishek.lekshmanan@gmail.com>

### CODE REVIEW

**Comment by theanalyst** [comment]
Have fixed the violations... a better diff view can be seen at https://github.com/ceph/ceph/pull/3251/files?w=0 
if this is ok, i'll just squash the commits..

**Comment by theanalyst** [comment]
@yehudasa squashed and fixed according to comments.. let me know if anything else required.

**Comment by theanalyst** [comment]
@yehudasa could you take a look, fixed according to comment

**Comment by theanalyst** [comment]
@yehudasa can you take a look at this?

**Comment by yehudasa** [comment]
@theanalyst it's on my todo list

**Comment by theanalyst** [comment]
@yehudasa thanks

**Comment by valerytschopp** [comment]
I think there is a problem with the code at line 988. 

If the cephx user lookup failed, then keystone is tried but only if enabled and with the keystone url configured. What happens if keystone is not enabled or the keystone url not defined?

**Comment by yehudasa** [comment]
@valerytschopp yeah, there's a missing return there. What will actually happen that it's going to fail later on when checking the bucket permissions (unless bucket has public write permissions). Will basically behave similar to the anonymous user. I opened bug 10698. Thanks!

**Comment by theanalyst** [comment]
Ah sorry missed this! Thanks @valerytschopp for spotting. #3551 should address this now

**Pull request merged**
