### PR TITLE
nautilus: cephfs: client: make Client::open() pass proper cap mask to path_walk

### PR DESCRIPTION
**Pull request by Vicente-Cheng**
backport trackers:

* https://tracker.ceph.com/issues/47254
* https://tracker.ceph.com/issues/47622

---

backport of

* https://github.com/ceph/ceph/pull/36701
* https://github.com/ceph/ceph/pull/37310

parent trackers:

* https://tracker.ceph.com/issues/47011
* https://tracker.ceph.com/issues/47224

this backport was staged using ceph-backport.sh version 15.1.1.389
find the latest version at https://github.com/ceph/ceph/blob/master/src/script/ceph-backport.sh

### CODE REVIEW

**Comment by batrick** [comment]
regression: https://tracker.ceph.com/issues/47224

**Comment by smithfarm** [comment]
@Vicente-Cheng Could you please cherry-pick #37310 into this PR and update https://tracker.ceph.com/issues/47622 to "In Progress"?

**Comment by Vicente-Cheng** [comment]
> @Vicente-Cheng Could you please cherry-pick #37310 into this PR and update https://tracker.ceph.com/issues/47622 to "In Progress"?

@smithfarm, Done!
Thanks for your reminder : )

**Comment by smithfarm** [comment]
> Should I rebase to the latest nautilus?

Rebasing is not necessary unless GitHub says the PR has conflicts (which is not the case ATM).

**Comment by smithfarm** [comment]
jenkins test make check

**Comment by Vicente-Cheng** [comment]
> > Should I rebase to the latest nautilus?
> 
> Rebasing is not necessary unless GitHub says the PR has conflicts (which is not the case ATM).

OK, got it!  thanks for explaining :)

**Comment by yuriw** [comment]
[wip-yuri3-testing-2020-10-05-0922-nautilus](https://trello.com/c/jikOLW3R/1033-wip-yuri3-testing-2020-10-05-0922-nautilus)

**Review by ajarr — APPROVED** [review]

**Pull request merged**
