### PR TITLE
rgw: support json format for admin policy API

### PR DESCRIPTION
**Pull request by mathslinux**
fix #14090 and #14091

Signed-off-by: Dunrong Huang <riegamaths@gmail.com>

### CODE REVIEW

**Comment by mathslinux** [comment]
@yehudasa I was misled by the name of file rgw_json_enc.cc, i wrongly though rgw_json_enc.cc  should  only handle json format, but RGWAccessControlXXX::dump()  was used to convert content to XML and json, so i moved them to their class file. Seems i was wrong, will change them back in v2 pull.

**Comment by yehudasa** [comment]
@mathslinux ping

**Comment by mathslinux** [comment]
@yehudasa Sorry for the late reply, I just reopen a pull a request which address your comments, please help to review

https://github.com/ceph/ceph/pull/7498

**Comment by yehudasa** [comment]
@mathslinux closing this PR, will merge V2 soon.

**Pull request closed without merging**
