### PR TITLE
doc: release/mimic: correct the changelog to the latest version

### PR DESCRIPTION
**Pull request by theanalyst**
We were still having the changelog from mimic-dev1, update this to reflect the
current state of mimic

Signed-off-by: Abhishek Lekshmanan <abhishek@suse.com>

### CODE REVIEW

**Comment by theanalyst** [comment]
jenkins render docs

**Comment by tchaikov** [comment]
retest this please.

**Comment by theanalyst** [comment]
updated, should fix the build failures

**Comment by tchaikov** [comment]
retest this please.

**Comment by theanalyst** [comment]
jenkins render docs

**Pull request merged**
