### PR TITLE
test: correct osd pool default size

### PR DESCRIPTION
**Pull request by NitzanMordhai**
Using the default pool size of 2 with random eio thrashing can cause some of the object to mark as lost.
fixing typo from 'osd default pool size: 3' to 'osd pool default size: 3' so we will have pool size 3 correctly.

Fixes: https://tracker.ceph.com/issues/49888
Signed-off-by: Nitzan Mordechai <nmordech@redhat.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Review by Matan-B — APPROVED** [review]
Same as #51528 is fixing the override typo, can we apply similar changes to the default pool size typo in any other instances of it?

**Review by neha-ojha — APPROVED** [review]
While you are it, would you mind fixing other occurrences of the same typo (e.g. thrash-backfill-full.yaml)? :)

**Review by ljflores — APPROVED** [review]

**Comment by NitzanMordhai** [comment]
> While you are it, would you mind fixing other occurrences of the same typo (e.g. thrash-backfill-full.yaml)? :)

Added to the exist commit.

**Comment by NitzanMordhai** [comment]
> Same as #51528 is fixing the override typo, can we apply similar changes to the default pool size typo in any other instances of it?

Done, for teuthology i'll create another PR, and we will need another discussion regarding that.

**Comment by NitzanMordhai** [comment]
jenkins test api

**Review by rzarzynski — APPROVED** [review]

**Comment by ljflores** [comment]
Rados suite review: https://tracker.ceph.com/projects/rados/wiki/MAIN#httpstrellocomc1LQJnuRh1759-wip-yuri8-testing-2023-05-23-0802

**Pull request merged**
