### PR TITLE
nautilus: pacific: pybind/ceph_volume_client: stat on empty string

### PR DESCRIPTION
**Pull request by batrick**
https://tracker.ceph.com/issues/51493

### CODE REVIEW

**Comment by ajarr** [comment]
Add Fixes: https://tracker.ceph.com/issues/51493 in the commit message?

**Comment by ajarr** [comment]
@yuriw thanks!

**Comment by gouthampacha** [comment]
Changes LGTM, have been tested on a manila environment - Thank you for making and back porting this fix, @batrick!

**Comment by yuriw** [comment]
ref: 
https://trello.com/c/kMyytLIB
https://pulpito.ceph.com/yuriw-2021-07-02_18:54:54-fs-ajarr-nautilus-42162-distro-basic-smithi/

tests passed

**Comment by ajarr** [comment]
Awesome! looks great!

**Review by ajarr — APPROVED** [review]

**Comment by vkmc** [comment]
Awesome, thanks for the quick fix Patrick!

**Pull request merged**
