### PR TITLE
nautilus: mds: initialize MDSlaveUpdate::waiter

### PR DESCRIPTION
**Pull request by ukernel**
introduced by backport commit 4273de4cfaf
"mds: preserve ESlaveUpdate::OP_PREPARE logevent before doing commit"

Fixes: https://tracker.ceph.com/issues/46831
Signed-off-by: "Yan, Zheng" <zyan@redhat.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by ajarr** [comment]
I looked at the original commit https://github.com/ceph/ceph/commit/4940ab62e0d19ce36e53bcc67b2a2161c47f6c6d of the backport commit  that 'introduced' this issue. It too doesn't initialize the `Context *waiter`. It's actually initialized in master by  the commit https://github.com/ceph/ceph/commit/e15651195820 that reorganizes the Mutation header file.

**Comment by batrick** [comment]
> I looked at the original commit [4940ab6](https://github.com/ceph/ceph/commit/4940ab62e0d19ce36e53bcc67b2a2161c47f6c6d) of the backport commit that 'introduced' this issue. It too doesn't initialize the `Context *waiter`. It's actually initialized in master by the commit [e156511](https://github.com/ceph/ceph/commit/e15651195820) that reorganizes the Mutation header file.

`waiter` was initialized before that commit, see: https://github.com/ceph/ceph/commit/e15651195820#diff-c9cc8a892690ff70b1572efe02e60a73L481

You can see the backport commit removed the initialization accidentally: https://github.com/ceph/ceph/commit/4273de4cfaf36f2b5a241d4a1703efd8b438afa7#diff-c9cc8a892690ff70b1572efe02e60a73L425

**Comment by batrick** [comment]
jenkins test api

**Comment by batrick** [comment]
Great work tracking this down Zheng. Thanks!

**Comment by batrick** [comment]
@yuriw one of the two fixes to pull into the next nautilus release. Other one is still TBD. I'll let you know by EOD.

**Comment by ajarr** [comment]
> > I looked at the original commit [4940ab6](https://github.com/ceph/ceph/commit/4940ab62e0d19ce36e53bcc67b2a2161c47f6c6d) of the backport commit that 'introduced' this issue. It too doesn't initialize the `Context *waiter`. It's actually initialized in master by the commit [e156511](https://github.com/ceph/ceph/commit/e15651195820) that reorganizes the Mutation header file.
> 
> `waiter` was initialized before that commit, see: [e156511#diff-c9cc8a892690ff70b1572efe02e60a73L481](https://github.com/ceph/ceph/commit/e15651195820#diff-c9cc8a892690ff70b1572efe02e60a73L481)
> 
> You can see the backport commit removed the initialization accidentally: [4273de4#diff-c9cc8a892690ff70b1572efe02e60a73L425](https://github.com/ceph/ceph/commit/4273de4cfaf36f2b5a241d4a1703efd8b438afa7#diff-c9cc8a892690ff70b1572efe02e60a73L425)

Got it! Thanks!

**Comment by yuriw** [comment]
[wip-yuri4-testing-2020-08-07-1350-nautilus](https://trello.com/c/1sBZ2tvJ/987-wip-yuri4-testing-2020-08-07-1350-nautilus)

**Comment by batrick** [comment]
jenkins test api

**Pull request merged**
