### PR TITLE
FileStore calls syncfs(2) even it is not supported

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/12586

### CODE REVIEW

**Comment by smithfarm** [comment]
@dachary The latest commits demonstrate that when I cherry-pick #3305 and 9921836 first, the cherry-pick of 08210d6 applies cleanly. True, #3305 was not originally slated for backport to firefly, but it looks like it fixes a bug that is present in firefly.

**Comment by smithfarm** [comment]
. . . and 9921836 is a no-brainer.

**Comment by dachary** [comment]
Oh, if it's just a matter of ordering the commits, it's good.

**Comment by smithfarm** [comment]
Well, the order is significant of course, but the question is more about
whether it's OK to bring in the unplanned additional backport (as a
dependency).

**Comment by dachary** [comment]
@smithfarm my understanding of the syncfs related issues is that it's a series of fixes that's not complete yet and that it is important to backport to firefly because it looks like syncfs is going to be removed completely. Therefore I think clustering the backports as you did not only makes sense but also prepares the ground for more backports to come.

**Comment by dachary** [comment]
@tchaikov  does this backport look good to merge ? It passed a run of the firefly rados suite ( see http://tracker.ceph.com/issues/11644#note-110 ). Note that there was a valgrind issues but it is unrelated and fixed by https://github.com/ceph/ceph/pull/6325.

**Comment by tchaikov** [comment]
@dachary and @smithfarm `Reviewed-by: Kefu Chai <kchai@redhat.com>`

**Pull request merged**
