### PR TITLE
ceph-volume: print most logging messages to stderr

### PR DESCRIPTION
**Pull request by jan--f**
Signed-off-by: Jan Fajerski <jfajerski@suse.com>

Fixes: http://tracker.ceph.com/issues/38548

Didn't get any feedback on the tracker, so went ahead with it.

### CODE REVIEW

**Comment by sebastian-philipp** [comment]
Can you also remove this workaround then:

https://github.com/ceph/ceph/blob/58e99319005ebfe461d38d16460ebdfa867ab54e/src/pybind/mgr/test_orchestrator/module.py#L194

This PR actually fixes a bug in the SSH orchestrator.

Teuthology QA run needs to execute rados/mgr then, too.

**Comment by jan--f** [comment]
@sebastian-philipp Like so?

**Comment by andrewschoen** [comment]
jenkins test ceph-volume tox

**Comment by andrewschoen** [comment]
jenkins test ceph-volume lvm all

**Comment by andrewschoen** [comment]
jenkins test ceph-volume batch all

**Comment by jan--f** [comment]
jenkins test ceph-volume tox

**Comment by jan--f** [comment]
jenkins test ceph-volume batch all

**Comment by jan--f** [comment]
jenkins test ceph-volume lvm all

**Comment by sebastian-philipp** [comment]
http://pulpito.ceph.com/swagner-2019-04-30_15:41:50-rados:mgr-wip-swagner-testing-distro-basic-mira/

**Comment by sebastian-philipp** [comment]
> ~http://pulpito.ceph.com/swagner-2019-04-30_15:41:50-rados:mgr-wip-swagner-testing-distro-basic-mira/~
> 
> Failed, caused by an unrelated PR that was tested together with this one.

Actually the test succeeded, but failed with a health check unrelated to this change afterwards.

```
2019-04-30T16:01:51.286 INFO:tasks.cephfs_test_runner:----------------------------------------------------------------------
2019-04-30T16:01:51.286 INFO:tasks.cephfs_test_runner:Ran 25 tests in 214.934s
2019-04-30T16:01:51.286 INFO:tasks.cephfs_test_runner:
2019-04-30T16:01:51.287 INFO:tasks.cephfs_test_runner:OK
```

so from an orchestrator POV, the test succeeded and this PR is good to go.

**Comment by jan--f** [comment]
jenkins test ceph-volume batch all

**Comment by sebastian-philipp** [comment]
jenkins test ceph-volume batch all

**Comment by andrewschoen** [comment]
jenkins test ceph-volume tox

**Comment by sebastian-philipp** [comment]
failed with:
```
There are no active Vagrant environments on this computer! Or,
you haven't destroyed and recreated Vagrant environments that were
started with an older version of Vagrant.
There was an error loading a Vagrantfile. The file being loaded
and the error message are shown below. This is usually caused by
a syntax error.

Path: /home/jenkins-build/build/workspace/ceph-volume-prs-batch-centos7-bluestore-mixed_type/src/ceph-volume/ceph_volume/tests/functional/Vagrantfile
Line number: 0
Message: Errno::ENOENT: No such file or directory @ rb_sysopen - /home/jenkins-build/build/workspace/ceph-volume-prs-batch-centos7-bluestore-mixed_type/src/ceph-volume/ceph_volume/tests/functional/vagrant_variables.yml
Build step 'Execute Scripts' marked build as failure
```

**Comment by guits** [comment]
@andrewschoen is there something we can do to  get this PR merged soon?

**Comment by jan--f** [comment]
jenkins test ceph-volume lvm all

**Comment by jan--f** [comment]
jenkins test ceph-volume lvm all

**Comment by jan--f** [comment]
jenkins test make check

**Comment by guits** [comment]
are these failures actually related to this patch?

**Comment by guits** [comment]
:tada:

**Comment by guits** [comment]
@jan--f @alfredodeza @sebastian-philipp  thanks!

Any chance we can get this patch backported up to luminous?

**Comment by guits** [comment]
follow up: 
 https://tracker.ceph.com/issues/38548#note-11
 https://tracker.ceph.com/issues/41158

**Pull request merged**
