### PR TITLE
doc: dev: introduction to tests

### PR DESCRIPTION
**Pull request by dachary**
Signed-off-by: Loic Dachary <loic@dachary.org>

### CODE REVIEW

**Comment by dachary** [comment]
Applied your comments and repushed, thanks :-)

**Comment by dachary** [comment]
Added a diagram to explain the workflow and its relation to the tests, very high level.

**Comment by smithfarm** [comment]
And thanks for the whitespace cleanup - the wonders of emacs. . .

**Comment by dachary** [comment]
> And thanks for the whitespace cleanup - the wonders of emacs. . 

The whitespace cleanup is an unintended side effect of the picture mode of emacs which I used to draw ascii :-)

**Comment by dachary** [comment]
modifications applied & repushed

**Comment by dachary** [comment]
@smithfarm would you like me to do some more changes on this pull request ?

**Comment by smithfarm** [comment]
@dachary No, it looks fine to me now!

```
Reviewed-by: Nathan Cutler <ncutler@suse.com>
```

**Pull request merged**
