### PR TITLE
crush: fix chooseleaf to do only the necessary pg migrations when osd fails

### PR DESCRIPTION
**Pull request by Sandy4999**
Fix the problem that chooseleaf may cause some unnecessary pg migrations when OSDs states change

Signed-off-by: Sangdi Xu <xu.sangdi@h3c.com>

### CODE REVIEW

**Comment by tchaikov** [comment]
for more context, see also the undergoing discussion at https://www.mail-archive.com/ceph-devel@vger.kernel.org/msg26035.html

**Comment by Sandy4999** [comment]
@liewegas I have added a tunable named 'chooseleaf_stable'. Could you please review the changes? Thank you!

**Comment by Sandy4999** [comment]
@liewegas It seems that the failure is caused because the test objects were encoded by the original encoder. Crushmaps newly built after this change should work fine.

**Comment by xiaoxichen** [comment]
By term of number of changed mapping (I sort and compared the OSD set), this patch do helps a lot as every remapped PG only has one OSD changing.(compared to ~1.5X before, avg from 302 to 210 in 40 OSDs, 10 per node , 2 rep case)

Also tested in 3 rep

**Comment by Sandy4999** [comment]
@xiaoxichen Thanks for your concern and the test work!

**Comment by Sandy4999** [comment]
@liewegas Any suggestion or comment? Thank you

**Comment by liewegas** [comment]
https://github.com/ceph/ceph/pull/6572

**Pull request closed without merging**
