### PR TITLE
qa: suppress SyscallParam error during startup on jammy

### PR DESCRIPTION
**Pull request by cbodley**
Fixes: https://tracker.ceph.com/issues/61428

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by cbodley** [comment]
passed qa in https://pulpito.ceph.com/cbodley-2023-06-13_01:56:44-rgw:verify-main-distro-default-smithi/

no SyscallParam failures, but it did show a Leak_PossiblyLost in d3n: https://tracker.ceph.com/issues/61661

**Review by rzarzynski — APPROVED** [review]

**Comment by cbodley** [comment]
jenkins test this please

**Comment by cbodley** [comment]
jenkins test make check

**Comment by cbodley** [comment]
jenkins test make check

**Pull request merged**
