### PR TITLE
ceph.spec.in: remove setuptools dependency

### PR DESCRIPTION
**Pull request by tchaikov**
in 844b66de, we stopped using pkg_resources for import packaging. and the exact reason why we introduced pkg_resources was for using the packaging python module, see cf608920.

so, let's partially revert cf608920.

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Comment by tchaikov** [comment]
@Matan-B i just realized that it took 1 year to finally converge at your change of #49579 .

**Comment by tchaikov** [comment]
jenkins test api

**Review by Matan-B — COMMENTED** [review]
Is `pkg-resources` still needed in `debian/ceph-mgr-modules-core.requires`?
Added in the partially reverted commit cf6089200d96fc56b08ee17a4e31f19823370dc8

**Comment by tchaikov** [comment]
> Is `pkg-resources` still needed in `debian/ceph-mgr-modules-core.requires`? 

ahh, right! dropped as well.

**Comment by tchaikov** [comment]
v2:

- removed `setuptools` from `debian/ceph-mgr-modules-core.requires` as well.


@Matan-B hi Matan, could you take another look?

**Review by Matan-B — APPROVED** [review]

**Comment by tchaikov** [comment]
being built at https://shaman.ceph.com/builds/ceph/wip-drop-setuptools-kefu/9e3fb11ebc76d30f405f24033c50495e31f511c2/

**Pull request merged**
