### PR TITLE
compressor/zlib: switch to raw deflate

### PR DESCRIPTION
**Pull request by branch-predictor**
By using raw deflate instead of default zlib deflate, we're saving 6 bytes on each compression stream and some CPU time by not calculating Adler32 during both compression and decompression (which is waste of time as Bluestore has its own checksumming code that is *also* executed).
CPU time savings are more visible on decompression (depends on compressed stream length; from 5 to 20% cpu time saved), but compression also sees gains (up to 5% in my testing).

Signed-off-by: Piotr Dałek <git@predictor.org.pl>

### CODE REVIEW

**Comment by liewegas** [comment]
sounds great!  hmm, we should figure out if/how users can configure the compression level, though.

**Comment by branch-predictor** [comment]
On Sun, Sep 18, 2016 at 03:28:52PM -0700, Sage Weil wrote:
> sounds great!  hmm, we should figure out if/how users can configure the compression level, though.

How about changing the Compressor instance constructor and passing
compression level through it?

**Comment by liewegas** [comment]
Yeah.. let's follow up with that later though after @ifed01 's pr merged

**Comment by liewegas** [comment]
retest this please

**Pull request merged**
