### PR TITLE
osd: update erasure code plugin interface to support subchunks

### PR DESCRIPTION
**Pull request by liewegas**
Rebase of https://github.com/ceph/ceph/pull/15193

### CODE REVIEW

**Comment by liewegas** [comment]
@mynaramana hoping to get this merged imminently!  sorry again for all the delays

**Comment by mynaramana** [comment]
Thanks Sage. Will look forward to this.

**Comment by tchaikov** [comment]
```
2017-10-28 10:43:29.181 7f5e3a1f6700 -1 /home/jenkins-build/build/workspace/ceph-dev-new-build/ARCH/x86_64/AVAILABLE_ARCH/x86_64/AVAILABLE_DI
ST/centos7/DIST/centos7/MACHINE_SIZE/huge/release/13.0.0-2490-g9fe792a/rpm/el7/BUILD/ceph-13.0.0-2490-g9fe792a/src/osd/ECUtil.cc: In function
 'int ECUtil::decode(const ECUtil::stripe_info_t&, ceph::ErasureCodeInterfaceRef&, std::map<int, ceph::buffer::list>&, std::map<int, ceph::bu
ffer::list*>&)' thread 7f5e3a1f6700 time 2017-10-28 10:43:29.173148
/home/jenkins-build/build/workspace/ceph-dev-new-build/ARCH/x86_64/AVAILABLE_ARCH/x86_64/AVAILABLE_DIST/centos7/DIST/centos7/MACHINE_SIZE/hug
e/release/13.0.0-2490-g9fe792a/rpm/el7/BUILD/ceph-13.0.0-2490-g9fe792a/src/osd/ECUtil.cc: 89: FAILED assert(min.find(i->first) != min.end())

 ceph version 13.0.0-2490-g9fe792a (9fe792abac94e062f4f959f8fbff03f9487443b1) mimic (dev)
 1: (ceph::__ceph_assert_fail(char const*, char const*, int, char const*)+0x110) [0x5586ccef6cb0]
 2: (ECUtil::decode(ECUtil::stripe_info_t const&, std::shared_ptr<ceph::ErasureCodeInterface>&, std::map<int, ceph::buffer::list, std::less<i
nt>, std::allocator<std::pair<int const, ceph::buffer::list> > >&, std::map<int, ceph::buffer::list*, std::less<int>, std::allocator<std::pai
r<int const, ceph::buffer::list*> > >&)+0xd18) [0x5586ccc91528]
 3: (ECBackend::handle_recovery_read_complete(hobject_t const&, boost::tuples::tuple<unsigned long, unsigned long, std::map<pg_shard_t, ceph:
:buffer::list, std::less<pg_shard_t>, std::allocator<std::pair<pg_shard_t const, ceph::buffer::list> > >, boost::tuples::null_type, boost::tu
ples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_
type>&, boost::optional<std::map<std::string, ceph::buffer::list, std::less<std::string>, std::allocator<std::pair<std::string const, ceph::b
uffer::list> > > >, RecoveryMessages*)+0x6f7) [0x5586ccc6d857]
 4: (OnRecoveryReadComplete::finish(std::pair<RecoveryMessages*, ECBackend::read_result_t&>&)+0x149) [0x5586ccc865c9]
 5: (ECBackend::complete_read_op(ECBackend::ReadOp&, RecoveryMessages*)+0x7f) [0x5586ccc5ad8f]
 6: (ECBackend::handle_sub_read_reply(pg_shard_t, ECSubReadReply&, RecoveryMessages*, ZTracer::Trace const&)+0x1018) [0x5586ccc62738]
 7: (ECBackend::_handle_message(boost::intrusive_ptr<OpRequest>)+0x1af) [0x5586ccc6ccff]
 8: (PGBackend::handle_message(boost::intrusive_ptr<OpRequest>)+0x50) [0x5586ccb79a70]
 9: (PrimaryLogPG::do_request(boost::intrusive_ptr<OpRequest>&, ThreadPool::TPHandle&)+0x5b4) [0x5586ccb312a4]
 10: (OSD::dequeue_op(boost::intrusive_ptr<PG>, boost::intrusive_ptr<OpRequest>, ThreadPool::TPHandle&)+0x3f6) [0x5586cc9794b6]
 11: (PGOpItem::run(OSD*, boost::intrusive_ptr<PG>&, ThreadPool::TPHandle&)+0x5a) [0x5586ccbe463a]
 12: (OSD::ShardedOpWQ::_process(unsigned int, ceph::heartbeat_handle_d*)+0xe91) [0x5586cc98d471]
 13: (ShardedThreadPool::shardedthreadpool_worker(unsigned int)+0x839) [0x5586ccefc7c9]
 14: (ShardedThreadPool::WorkThreadSharded::entry()+0x10) [0x5586ccefe760]
```


/a/kchai-2017-10-28_10:31:03-rados-wip-kefu-testing-2017-10-27-0940-distro-basic-mira/1785126/remote/mira066/log/ceph-osd.7.log.gz

**Comment by mynaramana** [comment]
Hi Sage, Kefu,

How can I access the log to this crash case?  What is the the test case when this crash was seen ?

Thanks
Myna

**Comment by tchaikov** [comment]
@mynaramana the link to the failed test is http://pulpito.ceph.com/kchai-2017-10-28_10:31:03-rados-wip-kefu-testing-2017-10-27-0940-distro-basic-mira/1785126/

and for the logs from the test nodes, please follow the links in http://qa-proxy.ceph.com/teuthology/kchai-2017-10-28_10:31:03-rados-wip-kefu-testing-2017-10-27-0940-distro-basic-mira/1785126/remote/

**Comment by mynaramana** [comment]
Hi Sage, Kefu,

I updated the code with a possible fix in  PR 15193, can you retest this ?

Thanks
Myna.

**Comment by tchaikov** [comment]
@mynaramana sure, i will include it in my next test batch.

**Pull request closed without merging**
