### PR TITLE
src/scripts/ceph-backport.sh: Add PR checklist

### PR DESCRIPTION
**Pull request by kamoltat**
Problem:

Current backport script lacks PR template

Solution:

Add PR template to backport script

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Review by ljflores — APPROVED** [review]

**Comment by cbodley** [comment]
i'm having trouble with the backport script now.. my first attempt to run it from the root of the ceph tree failed with:
> src/script/ceph-backport.sh: line 1737: ../../../ceph/.github/pull_request_template.md: No such file or directory

after cd'ing into ceph/src/script and retrying,
> ceph-backport.sh: ERROR: failed to open backport PR
ceph-backport.sh: GitHub API said:                                             
{
  "message": "Problems parsing JSON",                                          
  "documentation_url": "https://docs.github.com/rest/pulls/pulls#create-a-pull-request"
}                                     
ceph-backport.sh: ERROR: problem detected in your setup
ceph-backport.sh: Run "ceph-backport.sh --setup" to fix

**Comment by cbodley** [comment]
why do we want backport prs to have that checklist? shouldn't all of those items have been addressed by the initial pr that merged to main?

**Comment by kamoltat** [comment]
> why do we want backport prs to have that checklist? shouldn't all of those items have been addressed by the initial pr that merged to main?

when I was reviewing backport PRs I had trouble finding `Show available Jenkins commands` to re-run some of the make checks ... that was the initial motivation, but I also think it would be great for the backport PRs to have a matching format with the main PRs.

**Comment by cbodley** [comment]
i agree that the jenkins commands are useful, but i don't think the checklist belongs there. backports follow a different process with different rules

**Pull request merged**
