### PR TITLE
rgw:modify the error message when operating radosgw-admin metadata list user

### PR DESCRIPTION
**Pull request by liupeiyang**
when no user exists,,the error  message appears by operating radosgw-admin metadata list user .I changed the error message to the "[]".

Signed-off-by:  Peiyang Liu  <liu.peiyang@h3c.com>

### CODE REVIEW

**Comment by liupeiyang** [comment]
@yehudasa  Could you spare me a little time to see my question，thanks very much!

**Comment by yehudasa** [comment]
@liupeiyang which question?

**Comment by liupeiyang** [comment]
@yehudasa   rgw:modify the error message when operating radosgw-admin metadata list user #6024

**Comment by liupeiyang** [comment]
@yehudasa When operating "radosgw-admin metadata list user",there are two error messages ,One of them come from Rgw_rados.cc.The user one has some differences with the bucket one.We can not modify it in a file .would you take a look again?

**Comment by yehudasa** [comment]
@liupelyang yeah, I'll take another look, thanks.

**Comment by yehudasa** [comment]
@liupeiyang I had another comment, did you see it?

**Comment by liupeiyang** [comment]
@yehudasa    which one? I have added spaces before opening bracket and after closing bracke.

**Comment by yehudasa** [comment]
https://github.com/liupeiyang/ceph/commit/3990f7c7760a6446d2400248f7b52208119e50e6#commitcomment-13496380

**Comment by liupeiyang** [comment]
fixing list_keys_next()  like the bucket  instead of modifying two different blocks?
<pre>
 if (ret < 0 && ret != -ENOENT)
      return ret;
    if (ret == -ENOENT) {
      if (truncated)
        *truncated = false;
      return 0;
    }
</pre>

**Comment by yehudasa** [comment]
@liupeiyang yeah, something like thiat

**Comment by dachary** [comment]
@liupeiyang this needs a rebase

**Pull request closed without merging**
