### PR TITLE
librgw: fix librgw fhcache deadlock problem

### PR DESCRIPTION
**Pull request by xxhdx1985126**
Fixes: https://tracker.ceph.com/issues/46439
Signed-off-by: Xuehan Xu <xxhdx1985126@gmail.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by xxhdx1985126** [comment]
@cbodley Please take a look at this, thanks:-)

**Comment by cbodley** [comment]
i don't think the recursive mutex is a good solution for deadlocks in general, but i'll defer to @mattbenjamin

**Comment by mattbenjamin** [comment]
@xxhdx1985126 this is worrisome--it's usually not a real fix for an unexpected race.  We're discussing whether to accept this fix provisionally in Bug Scrub.

**Comment by xxhdx1985126** [comment]
@mattbenjamin Hi, I'm a little confused in that: it seems both fh_cache and fh_lru holds exactly the same set of file handlers, is this right? If so, why keep two caches? Thanks:-)

**Comment by xxhdx1985126** [comment]
@mattbenjamin It seems that fh_cache is responsible for efficient lookup, and fh_lru is responsible for keeping refcnt and further deciding which fh to evict, is this right?

**Comment by mattbenjamin** [comment]
@xxhdx1985126 could you report status after merge of https://github.com/ceph/ceph/pull/36942 -- whether it fixes the issue you hit, or whether it could be generalized to do so?  (That change shows the intended style of negotiation between locks in fh_cache and fh_lru.)

**Comment by xxhdx1985126** [comment]
@mattbenjamin ok:-)

**Pull request closed without merging**
