### PR TITLE
qa: set locale to C.UTF-8 in tox.ini

### PR DESCRIPTION
**Pull request by tchaikov**
as ansible is using UTF-8 encoded characters in the file names, so, to avoid failures like:

  File "/home/jenkins-build/build/workspace/ceph-pull-requests/qa/.tox/py3/lib/python3.10/site-packages/pip/_internal/utils/unpacking.py", line 217, in untar_file
    with open(path, "wb") as destfp:
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 137-140: ordinal not in range(256)

we have to set a locale which is able to handle UTF-8.

see also https://github.com/ceph/teuthology/pull/1671

Signed-off-by: Kefu Chai <tchaikov@gmail.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by tchaikov** [comment]
this change should address the first failure in https://jenkins.ceph.com/job/ceph-pull-requests/107859/console

**Comment by tchaikov** [comment]
@adk3798 hi Adam, could you help review this change as well?

**Comment by adk3798** [comment]
hmm, actually, still seeing
```
sage: mypy [-h] [-v] [-V] [more options; see below]
            [-m MODULE] [-p PACKAGE] [-c PROGRAM_TEXT] [files ...]
mypy: error: Missing target module, package, files, or command.
mypy: exit 2 (0.22 seconds) /home/jenkins-build/build/workspace/ceph-pull-requests/src/pybind/mgr> mypy --config-file=../../mypy.ini pid=3198086
mypy: FAIL ✖ in 35.1 seconds
```
in make check

**Comment by tchaikov** [comment]
that's a different issue from the one fixed by this change. i think this is also a fallout of upgrading tox -- it could be interpreting the newlines in a variable differently.

**Comment by adk3798** [comment]
> that's a different issue from the one fixed by this change. i think this is also a fallout of upgrading tox -- it could be interpreting the newlines in a variable differently.

okay, well this PR looks good then anyway

**Comment by phlogistonjohn** [comment]
I'd also mention that I think my build-and-test-in-containers effort could help avoid these sudden scrambles to fix things when packages on the build hosts change ;-)
If I understand the cause of the sudden need to update our tox.ini files correctly.

**Comment by tchaikov** [comment]
> Hi @tchaikov can we use the C.UTF-8 locale instead? As part of my efforts to build and test in containers, many of the images only have a minimal set of locales included. For example I had to change install-deps.sh to prevent errors when running in the container (see [cd1cd1b](https://github.com/ceph/ceph/commit/cd1cd1bd3350c85aee8f496f63522422dcad73de))
> 
> Thanks!

@phlogistonjohn hi John, done.

**Comment by tchaikov** [comment]
> I'd also mention that I think my build-and-test-in-containers effort could help avoid these sudden scrambles to fix things when packages on the build hosts change ;-)
> If I understand the cause of the sudden need to update our tox.ini files correctly.

looking forward to it!

**Review by phlogistonjohn — APPROVED** [review]
LGTM

**Pull request merged**
