### PR TITLE
[qa/tests]: misc ceph-ansible fixes and udpate

### PR DESCRIPTION
**Pull request by vasukulkarni**
a) catchup with new changes for ceph-ansible
b) adds some additional scenario's

### CODE REVIEW

**Comment by vasukulkarni** [comment]
Test running here: http://pulpito.ceph.com/vasu-2017-08-18_18:14:13-ceph-ansible-master-distro-basic-vps/ , Also needs: https://github.com/ceph/teuthology/pull/1101

**Comment by vasukulkarni** [comment]
http://pulpito.ceph.com/vasu-2017-08-18_18:40:24-ceph-ansible-master-distro-basic-vps/

**Comment by vasukulkarni** [comment]
Raised https://github.com/ceph/ceph-ansible/issues/1775 for CentOS issue seen in runs.

**Comment by vasukulkarni** [comment]
Excluding the 'cls' workunit which needs to be replaced: http://pulpito.ceph.com/vasu-2017-08-29_20:18:05-ceph-ansible-luminous-distro-basic-vps/

**Comment by vasukulkarni** [comment]
@tmuthamizhan some failures I am seeing now are in purge-cluster which is during end and is ceph-ansible issue http://pulpito.ceph.com/vasu-2017-09-08_17:02:15-ceph-ansible-luminous-distro-basic-vps/

**Comment by vasukulkarni** [comment]
master branch run, same issue at the end during cleanup for few tests: http://pulpito.ceph.com/vasu-2017-09-08_17:30:43-ceph-ansible-master-distro-basic-vps/

**Comment by tmuthamizhan** [comment]
@vasu, filed https://github.com/ceph/ceph-ansible/issues/1877 for the purge-cluster issue.

**Comment by vasukulkarni** [comment]
thanks @tmuthamizhan

**Pull request merged**
