### PR TITLE
crimson/os/seastore: do not write empty mutate records

### PR DESCRIPTION
**Pull request by cyx1231st**
Splitted out of https://github.com/ceph/ceph/pull/44127

See commit `crimson/os/seastore: do not write empty mutate records`

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [x] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by cyx1231st** [comment]
Works after applying the fix #44281

**Comment by athanatos** [comment]
I'm a little confused, where are we generating empty records?  This patch causes submission of an empty record to be a noop, but I'd expect it to block until any previously submitted IO (perhaps only on the same sequencer at the SeaStore level) completed.  Mostly though, if we're not generating empty records frequently, I'd be inclined to skip the complexity of optimizing for it.

**Comment by cyx1231st** [comment]
> where are we generating empty records?

I saw the empty records are generated by normal `SeaStore::do_transaction()` during rados bench, not sure how frequent yet. Will need to evaluate again.

> ... but I'd expect it to block until any previously submitted IO (perhaps only on the same sequencer at the SeaStore level) completed.

I think it is a mistake for noop transactions to miss the complete phase, should fix it.

@athanatos I'm on a travel recently, will back to this ASAP.

**Comment by athanatos** [comment]
No hurry.  I think I'd rather identify why we're generating empty records than optimize for it, though.

**Comment by cyx1231st** [comment]
From rados bench, none of the empty transactions are from normal I/O, mostly are from:
* `PG::try_flush_or_schedule_async: do_transaction…`
* `ShardServices::dispatch_context_transaction: do_transaction…`

So I dropped the change to ignore empty records in SeaStore, and added logs to identify where these empty transactions come from.

**Comment by athanatos** [comment]
try_flush_or_schedule_async is scheduling an empty transaction specifically in order to wait for all outstanding IOs to flush.

**Comment by cyx1231st** [comment]
Hmm, so the empty MUTATE transaction is meaningful and we cannot "fix" them from OSD side. It is still worthwhile to optimize out writes from empty MUTATE transaction. Is it correct?

**Comment by athanatos** [comment]
Right, we can optimize out the write, but it still needs to wait for any submitted writes to complete.

**Comment by cyx1231st** [comment]
@athanatos done, see https://github.com/ceph/ceph/pull/44256/commits/205b1e499466db8168907d1d65180626b6ca4e85#diff-360076e90f5dcd0af54e34f11e6000fc07d24e5212ce7f9cf574b5de686d658bR693-R700

**Comment by athanatos** [comment]
As far as I can tell, this really only affects flush transactions during peering.  Is that optimization actually worth this complexity?

**Comment by cyx1231st** [comment]
> As far as I can tell, this really only affects flush transactions during peering

Yeah, the end performance doesn't seem to be impacted.

I'll keep the cleanup and move the optimization into a draft.

**Comment by cyx1231st** [comment]
Every 8 seconds there are 23 empty transactions from OSD, which is about 1MiB every 1 minute and 30 seconds.

**Comment by cyx1231st** [comment]
@athanatos rebased

**Comment by athanatos** [comment]
I think it might be cleaner to add an explicit FuturizedStore::flush() call as in classic.  How about something like https://github.com/athanatos/ceph/tree/sjust/wip-seastore-flush ?

**Pull request closed without merging**
