### PR TITLE
mgr/insights: fix python3 DeprecationWarning

### PR DESCRIPTION
**Pull request by mgfritch**
Fixes deprecation warning:

```
insights/module.py:167: DeprecationWarning: invalid escape sequence \d
    r = "ceph version (?P<release>\d+)\.(?P<major>\d+)\.(?P<minor>\d+)"
```

This only occasionally appears when `insights/__pycache__` is changed or the cache dir is removed

Signed-off-by: Michael Fritch <mfritch@suse.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by mgfritch** [comment]
http://pulpito.ceph.com/mgfritch-2020-05-07_18:59:59-rados-wip-mgfritch-testing-2020-05-07-1029-distro-basic-smithi/

https://tracker.ceph.com/issues/45335

**Comment by sebastian-philipp** [comment]
> http://pulpito.ceph.com/mgfritch-2020-05-07_18:59:59-rados-wip-mgfritch-testing-2020-05-07-1029-distro-basic-smithi/

Kefu, do yuo know, if there are there any QA suites that also test mgr/insights?

**Comment by tchaikov** [comment]
- http://pulpito.ceph.com/kchai-2020-05-05_13:45:45-rados-wip-kefu-testing-2020-05-05-1333-distro-basic-smithi/
- http://pulpito.ceph.com/kchai-2020-05-09_03:42:53-rados-wip-kefu-testing-2020-05-05-1333-distro-basic-smithi/

i am merging this change despite of the failures in the test . i think they are tracked by https://tracker.ceph.com/issues/45255 and https://tracker.ceph.com/issues/45438

**Comment by tchaikov** [comment]
> > http://pulpito.ceph.com/mgfritch-2020-05-07_18:59:59-rados-wip-mgfritch-testing-2020-05-07-1029-distro-basic-smithi/
> 
> Kefu, do yuo know, if there are there any QA suites that also test mgr/insights?

@sebastian-philipp i think they are tests that using the qa/suites/rados/mgr/tasks/insights.yaml facet, namely, `qa/suites/rados/mgr`.

**Pull request merged**
