### PR TITLE
nautilus: tests/krbd: avoid hexdump skip and length options

### PR DESCRIPTION
**Pull request by smithfarm**
backport tracker: https://tracker.ceph.com/issues/41954
backport tracker: https://tracker.ceph.com/issues/42991

---

backport of https://github.com/ceph/ceph/pull/30502
backport of https://github.com/ceph/ceph/pull/31771
parent tracker: https://tracker.ceph.com/issues/41945
parent tracker: https://tracker.ceph.com/issues/42915

this backport was staged using ceph-backport.sh version 15.0.0.6950
find the latest version at https://github.com/ceph/ceph/blob/master/src/script/ceph-backport.sh

### CODE REVIEW

**Comment by smithfarm** [comment]
merged https://github.com/ceph/ceph/pull/32060 into this PR

**Comment by yuriw** [comment]
[wip-yuri8-testing-2020-01-13-2057-nautilus](https://trello.com/c/ZAl5Zb8O/804-wip-yuri8-testing-2020-01-13-2057-nautilus)

**Comment by tchaikov** [comment]
jenkins test make check

**Comment by smithfarm** [comment]
This PR contained 10 unrelated commits when it was merged - yikes

**Comment by idryomov** [comment]
Yeah, looks like it's just github...

**Pull request merged**
