### PR TITLE
quincy: qa/rgw: adapt tests to centos 9

### PR DESCRIPTION
**Pull request by cbodley**
backporting one rgw-specific commit from https://github.com/ceph/ceph/pull/53517 necessary to stop quincy testing on centos 8. has no associated tracker issue

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Comment by yuvalif** [comment]
according to this: https://docs.ceph.com/en/quincy/start/os-recommendations/
quincy supports centos8?

**Comment by cbodley** [comment]
centos stream 8 is eol, and we're not building packages for it any more. so most of our quincy tests in teuthology are broken. this is a followup to https://github.com/ceph/ceph/pull/58520 to switch quincy qa suites to centos 9. this has already happened for main/squid/reef branches

> according to this: https://docs.ceph.com/en/quincy/start/os-recommendations/

https://github.com/ceph/ceph/pull/58391 recently changed that doc, but it doesn't seem to have updated yet

**Review by yuvalif — APPROVED** [review]

**Comment by cbodley** [comment]
qa pending in https://pulpito.ceph.com/cbodley-2024-07-15_16:37:47-rgw-quincy-distro-default-smithi/

(that suite-branch also includes https://github.com/ceph/ceph/pull/58520)

**Comment by cbodley** [comment]
> https://pulpito.ceph.com/cbodley-2024-07-15_16:37:47-rgw-quincy-distro-default-smithi/

lots of failures:
* rgw/cloud-transition: 'cd /home/ubuntu/cephtest/s3-tests-client.0 && ./bootstrap' failed looking for python36-devel? reef and squid branches use tox/pytest instead of bootstrap/nose
* rgw/notifications: 'sudo chkconfig rabbitmq-server on' https://tracker.ceph.com/issues/63205
* rgw/sts: 'cd /home/ubuntu/cephtest/keycloak-11.0.0 && cd bin && ./jboss-cli.sh --file=adapter-elytron-install-offline.cli' https://tracker.ceph.com/issues/62536
* rgw/tempest: 'git clone -b stable/xena https://github.com/openstack/keystone.git /home/ubuntu/cephtest/keystone' maybe https://tracker.ceph.com/issues/58230?
* rgw/verify: 'cd /home/ubuntu/cephtest/s3-tests-java && /opt/gradle/gradle/bin/gradle clean test --rerun-tasks --no-build-cache --tests AWS4Test' https://tracker.ceph.com/issues/61398

**Comment by cbodley** [comment]
> rgw/verify: 'cd /home/ubuntu/cephtest/s3-tests-java && /opt/gradle/gradle/bin/gradle clean test --rerun-tasks --no-build-cache --tests AWS4Test' https://tracker.ceph.com/issues/61398

the fix for this was in the java_s3tests repo at https://github.com/ceph/java_s3tests/pull/15 so i cherry-picked and pushed that to the ceph-quincy branch

**Comment by cbodley** [comment]
> rgw/notifications: 'sudo chkconfig rabbitmq-server on' https://tracker.ceph.com/issues/63205

backport already prepared in https://github.com/ceph/ceph/pull/58313

**Comment by cbodley** [comment]
> rgw/sts: 'cd /home/ubuntu/cephtest/keycloak-11.0.0 && cd bin && ./jboss-cli.sh --file=adapter-elytron-install-offline.cli' https://tracker.ceph.com/issues/62536

included the backport for that here (there was a conflict from https://github.com/ceph/ceph/pull/52216)

**Comment by cbodley** [comment]
scheduled another run with 3/5 fixes in https://pulpito.ceph.com/cbodley-2024-07-15_22:21:07-rgw-quincy-distro-default-smithi

still expecting tempest to fail, and for the java failures to turn into s3test bootstrap failures

**Comment by cbodley** [comment]
i tested a commit https://github.com/ceph/s3-tests/commit/0aa44280c188ef90c3f0ae3cb817bfc080cd3fca that unpins python-3.6 from s3tests bootstrap, and that seemed to work in https://pulpito.ceph.com/cbodley-2024-07-16_18:02:17-rgw:verify-quincy-distro-default-smithi/. i pushed that commit to the ceph-quincy branch

**Comment by cbodley** [comment]
early results from the latest https://pulpito.ceph.com/cbodley-2024-07-18_16:04:57-rgw-quincy-distro-default-smithi/

* rgw/verify: ragweed bootstrap is now failing consistently, despite succeeding on Monday: 'ImportError: cannot import name 'yield_lines' from 'jaraco.text' (/usr/lib/python3.9/site-packages/jaraco/text/__init__.py)'
* rgw/notifications: 'adjust-ulimits ceph-coverage /home/ubuntu/cephtest/archive/coverage radosgw-admin -n client.0 user rm --uid foo.client.0 --purge-data --cluster ceph' https://tracker.ceph.com/issues/64184 (no fix)
* rgw/service-token: 'Health check failed: 1 pool(s) do not have an application enabled (POOL_APP_NOT_ENABLED)' https://tracker.ceph.com/issues/62504
* rgw/crypt/barbican: 'git clone -b stable/xena https://github.com/openstack/keystone.git /home/ubuntu/cephtest/keystone' https://tracker.ceph.com/issues/65334
* rgw/tempest: 'git clone -b stable/xena https://github.com/openstack/keystone.git /home/ubuntu/cephtest/keystone' maybe https://tracker.ceph.com/issues/58230?

**Comment by cbodley** [comment]
> rgw/crypt/barbican: 'git clone -b stable/xena https://github.com/openstack/keystone.git /home/ubuntu/cephtest/keystone' https://tracker.ceph.com/issues/65334

https://tracker.ceph.com/issues/65334 was already backported to quincy, this is just failing on keystone for the same reason as rgw/tempest

**Comment by cbodley** [comment]
the barbican fixes were already staged for quincy in https://github.com/ceph/ceph/pull/57045. i pulled those commits in

**Comment by cbodley** [comment]
rebased over https://github.com/ceph/ceph/pull/58520

**Comment by cbodley** [comment]
> * rgw/verify: ragweed bootstrap is now failing consistently, despite succeeding on Monday: 'ImportError: cannot import name 'yield_lines' from 'jaraco.text' (/usr/lib/python3.9/site-packages/jaraco/text/init.py)'

not really willing to debug this, and i don't think it's worth trying to backport the tox/pytest changes that are working on later releases. i just removed ragweed coverage from quincy entirely

**Comment by cbodley** [comment]
https://pulpito.ceph.com/cbodley-2024-07-26_16:04:08-rgw-quincy-distro-default-smithi/

down to just valgrind errors. cherry-picked the commit from https://github.com/ceph/ceph/pull/53097

**Comment by cbodley** [comment]
jenkins test make check

**Comment by cbodley** [comment]
jenkins test api

**Comment by cbodley** [comment]
rerun 'passed' in https://pulpito.ceph.com/cbodley-2024-07-29_18:03:29-rgw-quincy-distro-default-smithi/. there was still one 'saw valgrind issues' after cherry-picking the suppression, but i think this is good enough

**Comment by cbodley** [comment]
jenkins test make check

**Comment by cbodley** [comment]
https://jenkins.ceph.com/job/ceph-api/78855/
> monitor data filesystem reached concerning levels of available storage space (available: 1% 3.5 GiB)

**Comment by cbodley** [comment]
jenkins test api

**Comment by cbodley** [comment]
https://jenkins.ceph.com/job/ceph-pull-requests/140231/
> CMake Error at /usr/share/cmake-3.22/Modules/CMakeTestCXXCompiler.cmake

**Comment by cbodley** [comment]
jenkins test make check

**Comment by cbodley** [comment]
> CMake Error at /usr/share/cmake-3.22/Modules/CMakeTestCXXCompiler.cmake

**Comment by cbodley** [comment]
jenkins test make check

**Comment by cbodley** [comment]
https://jenkins.ceph.com/job/ceph-api/78870/
>  * Install prebuilt node (14.15.1) .Failed to download from https://nodejs.org/download/release/v14.15.1/node-v14.15.1-linux-x64.tar.gz

**Comment by cbodley** [comment]
jenkins test api

**Comment by cbodley** [comment]
jenkins test make check

**Comment by cbodley** [comment]
jenkins test make check

**Comment by smanjara** [comment]
there is another failed run related to s3-test-java that occured in https://pulpito.ceph.com/?branch=wip-yuri5-testing-2024-08-22-0855-quincy

```
2024-08-23T23:48:16.768 INFO:teuthology.orchestra.run.smithi143.stderr:FAILURE: Build failed with an exception.
2024-08-23T23:48:16.769 INFO:teuthology.orchestra.run.smithi143.stderr:
2024-08-23T23:48:16.769 INFO:teuthology.orchestra.run.smithi143.stderr:* What went wrong:
2024-08-23T23:48:16.769 INFO:teuthology.orchestra.run.smithi143.stderr:Execution failed for task ':test'.
2024-08-23T23:48:16.769 INFO:teuthology.orchestra.run.smithi143.stderr:> There were failing tests. See the report at: file:///home/ubuntu/cephtest/s3-tests-java/build/reports/tests/test/index.html
2024-08-23T23:48:16.769 INFO:teuthology.orchestra.run.smithi143.stderr:
2024-08-23T23:48:16.769 INFO:teuthology.orchestra.run.smithi143.stderr:* Try:
2024-08-23T23:48:16.769 INFO:teuthology.orchestra.run.smithi143.stderr:Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
2024-08-23T23:48:16.769 INFO:teuthology.orchestra.run.smithi143.stderr:
2024-08-23T23:48:16.769 INFO:teuthology.orchestra.run.smithi143.stdout:
2024-08-23T23:48:16.769 INFO:teuthology.orchestra.run.smithi143.stdout:Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
2024-08-23T23:48:16.769 INFO:teuthology.orchestra.run.smithi143.stdout:Use '--warning-mode all' to show the individual deprecation warnings.
2024-08-23T23:48:16.770 INFO:teuthology.orchestra.run.smithi143.stderr:* Get more help at https://help.gradle.org
2024-08-23T23:48:16.770 INFO:teuthology.orchestra.run.smithi143.stderr:
2024-08-23T23:48:16.770 INFO:teuthology.orchestra.run.smithi143.stdout:See https://docs.gradle.org/6.0.1/userguide/command_line_interface.html#sec:command_line_warnings
2024-08-23T23:48:16.770 INFO:teuthology.orchestra.run.smithi143.stdout:5 actionable tasks: 5 executed
2024-08-23T23:48:16.770 INFO:teuthology.orchestra.run.smithi143.stderr:BUILD FAILED in 32s
```

**Comment by cbodley** [comment]
yeah i see a test case failed above:
> suite > Object tests > ObjectTest.testObjectCreateBadContentlengthNegative FAILED
    java.lang.AssertionError at ObjectTest.java:472

**Comment by cbodley** [comment]
we removed that test case in https://github.com/ceph/java_s3tests/pull/14, i'll go ahead and cherry-pick that to the ceph-quincy branch too

**Pull request merged**
