### PR TITLE
rgw_file: save etag and acl info in setattr

### PR DESCRIPTION
**Pull request by taoCH**
Fixes: https://tracker.ceph.com/issues/38327

Signed-off-by: Tao Chen <chentao@umcloud.com>

- [x] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by mattbenjamin** [comment]
@taoCH I need to re-review.  I think this may be fine.  The key point I want to ensure is, that it always be clear that storing an arbitrary value for etag may never be a side effect of SETATTR or SETXATTR.

**Comment by smithfarm** [comment]
@taoCH Please change `Fixed:` to `Fixes:` in this line of the commit message:

```
Fixed: https://tracker.ceph.com/issues/38327
```

(People or scripts might grep the git history for lines starting with `Fixes:`...)

**Comment by taoCH** [comment]
> @taoCH Please change `Fixed:` to `Fixes:` in this line of the commit message:
> 
> ```
> Fixed: https://tracker.ceph.com/issues/38327
> ```
> (People or scripts might grep the git history for lines starting with `Fixes:`...)

done

**Comment by taoCH** [comment]
> @taoCH I need to re-review. I think this may be fine. The key points I want to ensure are,]
> 
> 1. it always be clear that storing an arbitrary value for etag may never be a side effect of SETATTR or SETXATTR
> 2. ETAG is computed by the RGW write cycle, not something else
> 3. ETAG is in the normal case stored as it is now--it must not depend on a SETATTR following WRITE/COMMIT, in general

ok

**Comment by taoCH** [comment]
@mattbenjamin code updated

**Comment by cbodley** [comment]
jenkins test docs

**Pull request merged**
