### PR TITLE
rgw: URL encode bucket name in metadata sync

### PR DESCRIPTION
**Pull request by BryceCao**
I found a bug in metadata sync: some special swift buckets jammed the sync, the scene where I found this bug is:
Bucket names created via swift are allowed to contain symbols, such as "?". I created a bucket named "test???" in master zonegroup, and rgw return me "201 Created", but i found this bucket was not in the list returned by executing "radosgw-admin bucket list" in the slave zonegroup, and corresponding bucket_entrypoint and  bucket_instance object were not in metadata pool. More seriously, the buckets created later were not synchronized to slave zonegroup, the metadata sync was jammed in the shard where "test???" is located. In slave zonegroup, sync status like this: image, rgw log like this: 
image
Then, i find metadata sync coroutine does not URL encode the bucket name, resulting in a "403 Signature doesn't match" error in the request to master zonegroup. So i added this part of code.

Signed-off-by: caolei <halei15848934852@163.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by tchaikov** [comment]
could you prefix the title of your commit message with the subcomponent your are changing ? see https://github.com/ceph/ceph/blob/master/SubmittingPatches.rst#3-describe-your-changes

the title of the commit message reads like a bug report. ideally, the title of the commit message should use the imperative mood. see also https://github.com/ceph/ceph/blob/master/SubmittingPatches.rst#3-describe-your-changes . please use `git commit --amend`  and `git push -f` for revising the commit message and its title.

**Comment by tchaikov** [comment]
@smanjara ping?

**Comment by smanjara** [comment]
jenkins retest

**Comment by tchaikov** [comment]
@yuriw  could you include this change your next rgw test batch ?

**Comment by ivancich** [comment]
@BryceCao, will this need backports? If so, it needs an associated tracker.

**Comment by ivancich** [comment]
Teuthology results -- no regressions noted:

- http://pulpito.ceph.com/ivancich-2020-09-02_13:39:22-rgw-wip-eric-testing-1-distro-basic-smithi/
- http://pulpito.ceph.com/ivancich-2020-09-02_13:39:44-rgw-wip-eric-testing-1-distro-basic-smithi/

**Comment by ivancich** [comment]
@BryceCao @smanjara : There was no tracker for this, and therefore it won't get backported. If it should be backported, please add an appropriate tracker.

**Pull request merged**
