### PR TITLE
rgw: correct comment in function parse_credentials

### PR DESCRIPTION
**Pull request by qrGitHub**
Signed-off-by: Bingyin Zhang <zhangbingyin@cloudin.cn>

### CODE REVIEW

**Comment by qrGitHub** [comment]
hi, @cbodley, @adamemerson, would you help to review this? thanks!

**Comment by joscollin** [comment]
retest this please

**Comment by qrGitHub** [comment]
@joscollin  this is just comment，I cannot follow you.

**Comment by joscollin** [comment]
@qrGitHub: https://wiki.jenkins.io/display/JENKINS/GitHub+pull+request+builder+plugin

**Pull request merged**
