### PR TITLE
quincy: Revert "mon/OSDMonitor: Make the pg_num check more accurate"

### PR DESCRIPTION
**Pull request by Matan-B**
This reverts commit c726ce9e5088b30d29e0db5c0ecc8c03fe41da1d.

This is an intermediate step before fixing the bug completely later on. [1]

Fixes: https://tracker.ceph.com/issues/57105

Verified by QA: https://bugzilla.redhat.com/show_bug.cgi?id=2153654

[1] Follow-up: https://tracker.ceph.com/issues/58288

Signed-off-by: Matan Breizman <mbreizma@redhat.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [x] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by Matan-B** [comment]
jenkins test make check

**Comment by Matan-B** [comment]
jenkins test api

**Review by neha-ojha — APPROVED** [review]
Makes sense to revert for now and create a separate PR with the complete fix.

**Comment by ljflores** [comment]
Rados suite review: http://pulpito.front.sepia.ceph.com/?branch=wip-yuri-testing-2023-02-06-1155-quincy

Failures, unrelated:
    1. https://tracker.ceph.com/issues/58146
    2. https://tracker.ceph.com/issues/58046 -- pending quincy backport
    3. https://tracker.ceph.com/issues/56788
    4. https://tracker.ceph.com/issues/58739
    5. https://tracker.ceph.com/issues/58560
    6. https://tracker.ceph.com/issues/58585

Details:
    1. test_cephadm.sh: Error: Error initializing source docker://quay.ceph.io/ceph-ci/ceph:master - Ceph - Orchestrator
    2. qa/workunits/rados/test_librados_build.sh: specify redirect in curl command - Ceph - RADOS
    3. crash: void KernelDevice::_aio_thread(): abort - Ceph - Bluestore
    4. "Leak_IndirectlyLost" valgrind report on mon.a - Ceph - RADOS
    5. test_envlibrados_for_rocksdb.sh failed to subscrib repo - Ceph - RADOS
    6. rook: failed to pull kubelet image - Ceph - Orchestrator

**Pull request merged**
