### PR TITLE
qa/tasks: cephadm.py don't zap devices before creating OSDs

### PR DESCRIPTION
**Pull request by sebastian-philipp**
## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by liewegas** [comment]
I'm pretty sure the zap is needed because the devices may have been used by a previous test and still have bluestore labels.

**Comment by liewegas** [comment]
> I'm pretty sure the zap is needed because the devices may have been used by a previous test and still have bluestore labels.

Hmm actually maybe not--i think there is a ``dd`` over the first few MB by teuthology.  Not sure about the labels on the LV itself though?

**Comment by sebastian-philipp** [comment]
> > I'm pretty sure the zap is needed because the devices may have been used by a previous test and still have bluestore labels.
> 
> Hmm actually maybe not--i think there is a `dd` over the first few MB by teuthology. Not sure about the labels on the LV itself though?

it seems to work fine for ceph_deploy.py !?

**Comment by liewegas** [comment]
hmm actually ceph-deploy suite is plagued with osd deploy failures.. this is probably why?

**Comment by sebastian-philipp** [comment]
> hmm actually ceph-deploy suite is plagued with osd deploy failures.. this is probably why?

heh

**Comment by jan--f** [comment]
Is the initial zap actually failing?

**Comment by sebastian-philipp** [comment]
superseded by https://tracker.ceph.com/issues/43858

**Pull request closed without merging**
