### PR TITLE
MDSMonitor: handle MDSBeacon messages properly

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/11980

### CODE REVIEW

**Comment by smithfarm** [comment]
@tchaikov pls review

**Comment by gregsfortytwo** [comment]
ping @tchaikov

**Comment by smithfarm** [comment]
@tchaikov, @gregsfortytwo This has passed a rados suite (see http://tracker.ceph.com/issues/11644#rados for details). OK to merge, do you think?

**Comment by tchaikov** [comment]
sorry for the latency. lgtm.

**Pull request merged**
