### PR TITLE
mon/HealthMonitor: split large method into smaller ones and cleanups

### PR DESCRIPTION
**Pull request by tchaikov**
## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by tchaikov** [comment]
- https://pulpito.ceph.com/kchai-2020-12-10_14:22:12-rados-wip-kefu-testing-2020-12-10-1827-distro-basic-smithi/
- https://pulpito.ceph.com/kchai-2020-12-11_07:09:12-rados-wip-kefu-testing-2020-12-10-1827-distro-basic-smithi/

failures are not related.

**Comment by tchaikov** [comment]
rebased against master.

**Comment by tchaikov** [comment]
@dzafman @neha-ojha @jdurgin ping?

**Comment by neha-ojha** [comment]
@tchaikov I added needs-qa considering you've updated the PR since last tests were done, if you think the new changes don't require retesting, please ignore

**Comment by tchaikov** [comment]
- https://pulpito.ceph.com/kchai-2020-12-16_15:58:13-rados-wip-kefu-testing-2020-12-16-1740-distro-basic-smithi
- https://pulpito.ceph.com/kchai-2020-12-17_12:24:37-rados-wip-kefu-testing-2020-12-17-1542-distro-basic-smithi/
- https://pulpito.ceph.com/kchai-2020-12-18_01:47:10-rados-wip-kefu-testing-2020-12-17-1542-distro-basic-smithi/


BTW, i think rebasing against master is a trivial change, so no need to rerun it.

**Pull request merged**
