### PR TITLE
libradosstriper silently fails to delete empty objects in jewel

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/20325

### CODE REVIEW

**Comment by liewegas** [comment]
Is there a set of striper tests that can cover this?

**Comment by smithfarm** [comment]
@liewegas Apparently not. Should the absence of tests be considered a blocker?

**Comment by liewegas** [comment]
Probably not, since we already lack sufficient tests for striper.  (FWIW this is why downstream RHCS removes it.)

**Comment by jdurgin** [comment]
there are basic tests - ceph_test_rados_striper_api_[a]io (from src/test/libradosstriper) - but this fix is obvious enough that I don't think they're a blocker

**Comment by smithfarm** [comment]
http://pulpito.ceph.com:80/smithfarm-2017-08-27_18:29:25-rados-wip-jewel-backports-distro-basic-smithi/

**Comment by smithfarm** [comment]
This passed the following relevant suites:

* rados (with some non-reproducible failures and dying objectstore idempotent tests) at http://tracker.ceph.com/issues/20613#note-25
* upgrade/hammer-x at http://tracker.ceph.com/issues/20613#note-28
* upgrade/client-upgrade at http://tracker.ceph.com/issues/20613#note-32

**Pull request merged**
