### PR TITLE
mgr: change 'bytes' dynamic perf counters to COUNTER type

### PR DESCRIPTION
**Pull request by trociny**
(so they are of the same type as in static perf)

Signed-off-by: Mykola Golub <mgolub@suse.com>

- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by s0nea** [comment]
> @s0nea - do you think this change has an impact on the dashboard or its tests in any way?

@LenzGr - it's hard to tell for me but I'm going to schedule a dashboard test run for it.

**Comment by trociny** [comment]
So far the only consumer is prometheus module, if rbd stats is enabled. Previously it exported these counters (among others):
```
# HELP ceph_rbd_write_bytes_sum RBD image bytes written Total
# TYPE ceph_rbd_write_bytes_sum counter

# HELP ceph_rbd_write_bytes_count RBD image bytes written Count
# TYPE ceph_rbd_write_bytes_count counter

# HELP ceph_rbd_read_bytes_sum RBD image bytes read Total
# TYPE ceph_rbd_read_bytes_sum counter

# HELP ceph_rbd_read_bytes_count RBD image bytes read Count
# TYPE ceph_rbd_read_bytes_count counter
```
that have been changed to:
```
# HELP ceph_rbd_write_bytes RBD image bytes written
# TYPE ceph_rbd_write_bytes counter

# HELP ceph_rbd_read_bytes RBD image bytes read
# TYPE ceph_rbd_read_bytes counter
```

**Comment by dillaman** [comment]
@LenzGr The dashboard doesn't use these values (yet) -- but I do have a forthcoming grafana tab for the block page that does pull these values in.

**Comment by dillaman** [comment]
retest this please

**Comment by dillaman** [comment]
jenkins test docs

**Pull request merged**
