### PR TITLE
quincy: doc/install: fix typos in openEuler-installation doc

### PR DESCRIPTION
**Pull request by zdover23**
Signed-off-by: Rongqi Sun <sunrongqi@huawei.com>
(cherry picked from commit 593ab1ad41467898c57c44baeb947bd238cba645)

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [x] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [x] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Review by anthonyeleven — APPROVED** [review]

**Review by idryomov — CHANGES_REQUESTED** [review]
Holding this backport until https://github.com/ceph/ceph/pull/56366 lands.

**Comment by zdover23** [comment]
It looks like https://github.com/ceph/ceph/pull/56366 has been merged, so as soon as this PR clears its tests, I'll merge it. Or you may, @Svelar.

**Comment by Svelar** [comment]
> It looks like #56366 has been merged, so as soon as this PR clears its tests, I'll merge it. Or you may, @Svelar.

No problem, thanks~

**Comment by zdover23** [comment]
Strangely, I can't approve this or merge it. I'll ask why when people are back at work next week.

**Review by anthonyeleven — APPROVED** [review]

**Comment by anthonyeleven** [comment]
Ilya’s request will need to be resolved.

**Review by Svelar — APPROVED** [review]

**Comment by idryomov** [comment]
This should be rebased, making the merge commit go away.

**Comment by idryomov** [comment]
> This should be rebased, making the merge commit go away.

I went ahead and did that.

**Review by idryomov — APPROVED** [review]

**Pull request merged**
