### PR TITLE
mailmap for 10.0.4

### PR DESCRIPTION
**Pull request by theanalyst**

### CODE REVIEW

**Comment by dachary** [comment]
@theanalyst seems ready for sending the mails :-)

**Comment by theanalyst** [comment]
@dachary Sent mails today, forgot to modify the script, so all mails refer commits in your repo (but it still is a valid link eg. https://github.com/dachary/ceph/commit/178d5b2d3556d49b407074e4d1ec34e5ae27edf3)

**Comment by dachary** [comment]
@theanalyst interesting that these links are still valid, good to know :-)

**Comment by theanalyst** [comment]
@dachary Haven't got any replies to the mails so far (Abhishek Varshney acked his affiliation) I guess this is ok for merge now?

**Pull request merged**
