### PR TITLE
qa/rgw: s3a-hadoop suite does not pin a machine_type

### PR DESCRIPTION
**Pull request by cbodley**

### CODE REVIEW

**Comment by vasukulkarni** [comment]
@cbodley Its pinned to ovh because the ceph-ansible doesn't work nicely with smithi's yet, probably we can force it to use ceph-volume in config instead of ceph-disk if we have to remove the pin.

**Comment by vasukulkarni** [comment]
we will need this as well in ceph-ansible config: osd_scenario: lvm

**Comment by alfredodeza** [comment]
@vasukulkarni how is it that ceph-ansible doesn't play well with smithi's ?

**Comment by vasukulkarni** [comment]
@alfredodeza its because smithi node has 1 nvme drive partitioned into 4, so we have /dev/nvme0p1 to p4 and they are also preconfigured as lvm's now, so you can use with ceph-volume but not ceph-disk,  when using ceph-ansible with ceph-disk the expectation is give atleast 4 drives which acts as block for ceph-disk and when using with ceph-ansible/ceph-volume it needs 4 volumes which are lvm preconfigured, so you have to handle those cases before hand.

**Comment by cbodley** [comment]
okay, thanks @vasukulkarni

**Pull request closed without merging**
