### PR TITLE
common/PrioritizedQueue: dequeue highest priority item in non-strict q

### PR DESCRIPTION
**Pull request by rldleblanc**
Changes the token bucket to dequeue high priority OPs before low priority OPs if they are able to run. Also if there are just enough tokens for the op, let it run.

### CODE REVIEW

**Comment by rldleblanc** [comment]
Signed-off: Robert LeBlanc <robert.leblanc@endurance.com>

**Comment by liewegas** [comment]
Good catch, this looks right to me.

**Comment by tchaikov** [comment]
@rldleblanc Robert, your change makes sense to me. could you revise the title of your commit message like "common/PrioritizedQueue: dequeue highest priority item in non-strict q" ?

and i read in the comment before the class definition
```C++
/**
 * Manages queue for normal and strict priority items
 *
 * On dequeue, the queue will select the lowest priority queue
 * such that the q has bucket > cost of front queue item.
```
this matches with what we have currently.  maybe we need also update this comment along with your change?

and 
```C++
    // if there are multiple buckets/subqueues with sufficient tokens,
    // we behave like a strict priority queue among all subqueues that
    // are eligible to run.
```
right before the code churn you are changing, which matches with your fix.

**Comment by rldleblanc** [comment]
Added requested changes.

Signed-off: Robert LeBlanc <robert.leblanc@endurance.com>

**Comment by gregsfortytwo** [comment]
Isn't this on purpose, to prevent the high-priority queues from entirely starving the lower-priority ones? @athanatos?

**Comment by rldleblanc** [comment]
If that is the intention, then I would argue that a priority queue is the
wrong implementation to achieve that goal. Based on the comments in the
code, I suspect the patch is what was intended.

I do not think a priority queue is the best implementation hence I have
coded up a max-min queue and plan on working on another to test them
against one another, both in terms of handling congestion and efficiency.
Since I don't have good data otherwise yet, I thought it good to get this
in as it seems to help in my congestion testing.

Robert LeBlanc

**Comment by sglwlb** [comment]
What's the latest state? Will this commit be merged to any branch? I didn't find it in any branch.

**Comment by rldleblanc** [comment]
This was abandoned in favor of writing a new queue. I'm going through some
final testing and hope to have a PR this week.

Robert LeBlanc

**Comment by sglwlb** [comment]
@rldleblanc Sure, waiting for you new patch!

**Pull request closed without merging**
