### PR TITLE
rgw/beast: fix interaction between keepalive and 100-continue

### PR DESCRIPTION
**Pull request by cbodley**
if we reject a request with a "Expect: 100-continue" header before sending a "100 Continue" response, the keepalive logic should not try to read/discard request body before parsing the next request headers   

Fixes: https://tracker.ceph.com/issues/58286

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by cbodley** [comment]
cc @BryceCao

**Comment by ljflores** [comment]
jenkins retest this please

**Comment by cbodley** [comment]
this is causing a single failure in java_s3tests:
```
suite > Object tests > ObjectTest.TestObjectCreateBadMd5Empty FAILED
    com.amazonaws.http.timers.client.ClientExecutionTimeoutException at ObjectTest.java:616
```
i describe the problem in https://github.com/ceph/java_s3tests/pull/12

**Review by dang — APPROVED** [review]

**Comment by cbodley** [comment]
this had passed qa in https://pulpito.ceph.com/cbodley-2023-01-19_19:06:01-rgw-wip-cbodley-testing-distro-default-smithi/

**Pull request merged**
