### PR TITLE
#10520: qa: drop iozone tests

### PR DESCRIPTION
**Pull request by ktdreyer**
The iozone software is not available under an open-source license (https://bugzilla.redhat.com/852901). Fedora and EPEL do not ship the iozone package. It is only available in Debian from the non-free repository.

This pull request removes the iozone tests from the ceph codebase. When this is ready to be merged, we should also remove the iozone references from [ceph-qa-suite](https://github.com/ceph/ceph-qa-suite) and [ceph-qa-chef](https://github.com/ceph/ceph-qa-chef).

This relates to http://tracker.ceph.com/issues/10520

### CODE REVIEW

**Comment by gregsfortytwo** [comment]
Please don't merge this until I've had a chance to review how much dropping this right after tiobench is going to hurt our test coverage.

And in future it would be nice if you could ping to get an ack from the relevant leads when nuking their tests. :)

**Comment by ktdreyer** [comment]
Sure, I know this needs some review. I was just posting this in order to start the discussion.

I'm happy to CC whomever we need. Who are the leads I should ask for a review?

**Comment by liewegas** [comment]
we should be able to get teh same coverage from fio, which is a superior 
tool anyway, and i think not part of our current test suite..

**Comment by gregsfortytwo** [comment]
@jdurgin it looks like this has actually turned up more rbd bugs than FS ones (at least in not-totally-ancient-history).

**Comment by gregsfortytwo** [comment]
@liewegas yeah, I think there's probably overlap but I want to be sure. It looks like there's an fio test in the tgt suite, but not anywhere else, so hopefully it wouldn't be too hard to put into all the right places.

**Comment by dachary** [comment]
rescheduling the bot, the error seems to be http://tracker.ceph.com/issues/10539

**Comment by markhpc** [comment]
I don't get why we are (apparently?) distributing the benchmark ourselves?  Are we trying to guarantee that executables are present and specifically versioned for all tasks?

I think long term, switching from iozone to fio is probably a good move (I use it primarily myself!). It seems to me though like we should leave iozone in the qa suites for now since we are close to entering into hammer testing.  There's a RHEL7 DAG package for iozone that could be used during the transition period.  We can't depend on it, but it'd get the job done in the interem.

**Comment by markhpc** [comment]
Ok, I took a little time to examine how we are invoking iozone here and see what the equivalent fio options are.  

Here are how the iozone options work according to the manpage:

-c (include close in timings)
-e (include flush/fflush in timings)
-s <size> (various file sizes)
-r <size> (various record sizes)
-t <threads> (use <threads> thread)
-F <filename> (name the file <filename>)
-i 0 (run a write/rewrite test)
-i 1 (run a read/reread test)
-o (use O_SYNC)
-+D (use O_DSYNC)
-+r (use O_RSYNC)

And here's how we are invoking it:

iozone.sh:

iozone -c -e -s 1024M -r 16K -t 1 -F f1 -i 0 -i 1
iozone -c -e -s 1024M -r 1M -t 1 -F f2 -i 0 -i 1
iozone -c -e -s 10240M -r 1M -t 1 -F f3 -i 0 -i 1

iozone_sync.sh:

iozone -c -e -s 512M -r 1M -t 1 -F osync1 -i 0 -i 1 -o
iozone -c -e -s 512M -r 1M -t 1 -F odsync1 -i 0 -i 1 -+D
iozone -c -e -s 512M -r 1M -t 1 -F orsync1 -i 0 -i 1 -+r

iozone -c -e -s 512M -r 1M -t 1 -F osync2 -i 0 -i 1 -o &
sleep 1
iozone -c -e -s 512M -r 256K -t 1 -F osync2 -i 0
wait $!

iozone -c -e -s 512M -r 1M -t 2 -F osync3 -i 2 -o


Probably the more complicated tests are when we are writing to the same file with 2 threads, one doing buffered writes and the other doing O_SYNC.  

fio has some similar, but different, options that might be able to help us recreate these tests:

fsync=int (How many IOs to perform before fsync)
create_fsync=bool (fsync on create)
fsync_on_close=bool (fsync on close)
end_fsync=bool (fsync on job exit)
size=int (total size of I/O for the job)
filesize=irange (range of individual file sizes)
blocksize=int[, int] (block size for IO)
numjobs=int (number of processes/threads performing the same workload)
rw=write (run write test)
rw=read (run read test)
sync=bool (use synchronous IO for buffered writes)

It looks like Sam Lang wrote the original sync tests and they haven't been updated since.  I'm not totally sure we can exactly recreate the above tests but we could probably do something pretty close.

**Comment by jcsp** [comment]
fio doesn't appear to have a way to set O_RSYNC at all, so we'd be losing that coverage.

It's unclear to me exactly what the correctness check (other than not crashing) is in the two concurrent iozone runs in iozone_sync.sh, I guess the data written is deterministic so that a write-read run running concurrently with a write run will always succeed?  Consequentially unclear to me what we would be losing without it.

I agree with Mark that losing iozone in the long run is fine, but we shouldn't rush it.  I also don't know what the DAG part of RHEL7 DAG is, but also note that there are generic RPMs available from http://www.iozone.org/src/current/

**Comment by gregsfortytwo** [comment]
Okay, based on that discussion I'm making the call for installing the RPMs.

**Pull request closed without merging**
