### PR TITLE
squid: rgw/notification: start/stop endpoint managers in notification manager

### PR DESCRIPTION
**Pull request by yuvalif**
backport tracker: https://tracker.ceph.com/issues/65996

---

backport of https://github.com/ceph/ceph/pull/56979
parent tracker: https://tracker.ceph.com/issues/65337

this backport was staged using ceph-backport.sh version 16.0.0.6848
find the latest version at https://github.com/ceph/ceph/blob/main/src/script/ceph-backport.sh

### CODE REVIEW

**Comment by yuvalif** [comment]
jenkins test api

**Review by cbodley — APPROVED** [review]
thanks!

**Comment by cbodley** [comment]
@yuvalif can you please review the failures in https://qa-proxy.ceph.com/teuthology/cbodley-2024-05-15_17:01:13-rgw-wip-65996-squid-distro-default-smithi/7707330/teuthology.log ?

qa was otherwise clean in https://pulpito.ceph.com/cbodley-2024-05-15_17:01:13-rgw-wip-65996-squid-distro-default-smithi/. rerun pending in https://pulpito.ceph.com/cbodley-2024-05-16_14:27:17-rgw-wip-65996-squid-distro-default-smithi/

**Comment by cbodley** [comment]
the rerun showed two test failures and got stuck: https://qa-proxy.ceph.com/teuthology/cbodley-2024-05-16_14:27:17-rgw-wip-65996-squid-distro-default-smithi/7709243/teuthology.log
> FAIL: test persistent topic stats
FAIL: test that when object is deleted due to lifecycle policy, notification is sent on master

**Comment by yuvalif** [comment]
> the rerun showed two test failures and got stuck: https://qa-proxy.ceph.com/teuthology/cbodley-2024-05-16_14:27:17-rgw-wip-65996-squid-distro-default-smithi/7709243/teuthology.log
> 
> > FAIL: test persistent topic stats
> > FAIL: test that when object is deleted due to lifecycle policy, notification is sent on master

to prevent the test from getting stuck, we need this fix: https://github.com/ceph/ceph/pull/57256
backported. will piggyback to this PR.

as for the actual issue. it is probably an issue with out http cient implementation or some environmental issue on the test machine.
from rgw log:
```
1287606-2024-05-16T19:59:46.597+0000 7f90c8495640 20 ERROR: msg->data.result=7 req_data->id=116426 http_status=0
1287607-2024-05-16T19:59:46.597+0000 7f90c8495640 20 ERROR: curl error: Couldn't connect to server req_data->error_buf=Failed to connect to localhost port 10930 after 0 ms: Connection refused
1287608-2024-05-16T19:59:46.597+0000 7f90c8495640 20 ERROR: msg->data.result=7 req_data->id=116427 http_status=0
1287609-2024-05-16T19:59:46.597+0000 7f90c8495640 20 ERROR: curl error: Couldn't connect to server req_data->error_buf=Failed to connect to localhost port 10930 after 0 ms: Connection refused
1287610-2024-05-16T19:59:46.597+0000 7f90c7c94640  5 rgw notify: WARNING: push entry: 0/27265 to endpoint: http://localhost:10930 failed. error: -2200 (will retry)
1287611:2024-05-16T19:59:46.597+0000 7f90c7c94640 20 rgw notify: INFO: new end marker for removal: 0/24576 from: :wtbyxm-11_topic
1287612:2024-05-16T19:59:46.597+0000 7f90c7c94640 20 rgw notify: INFO: processing of entry: 0/27265 (6/20) from: :wtbyxm-11_topic failed
```

however, the test has checks to verify that the http server is up and running. and even verifies a dummy POST request is sent, and received by the server.
from the test log:
```
2024-05-16T20:21:02.281 INFO:teuthology.orchestra.run.smithi080.stderr:bucket_notification.test_bn: INFO: http server created on ('localhost', 10930)
2024-05-16T20:21:02.281 INFO:teuthology.orchestra.run.smithi080.stderr:bucket_notification.test_bn: INFO: http server started on ('localhost', 10930)
2024-05-16T20:21:02.281 INFO:teuthology.orchestra.run.smithi080.stderr:urllib3.connectionpool: DEBUG: Starting new HTTP connection (1): localhost:10930
2024-05-16T20:21:02.281 INFO:teuthology.orchestra.run.smithi080.stderr:bucket_notification.test_bn: INFO: HTTP Server received iempty event
2024-05-16T20:21:02.282 INFO:teuthology.orchestra.run.smithi080.stderr:urllib3.connectionpool: DEBUG: http://localhost:10930 "POST / HTTP/1.1" 200 None
```
this is probably the same issue as: https://tracker.ceph.com/issues/66033

**Comment by cbodley** [comment]
thanks @yuvalif. the timestamps of those log entries don't match up, as the curl error happened over a minute before the http server started. i guess the latter was from the next test case?

**Review by cbodley — CHANGES_REQUESTED** [review]
waiting on inclusion of https://github.com/ceph/ceph/pull/57256

**Comment by yuvalif** [comment]
> waiting on inclusion of #57256

done

**Comment by cbodley** [comment]
> this is probably the same issue as: https://tracker.ceph.com/issues/66033

i don't think that tracker issue is due to a race with the http server's startup, because the test fails when [looking for the deletion events](https://github.com/ceph/ceph/blob/acdd6bc0/src/test/rgw/bucket_notification/test_bn.py#L1336) after it's already [verified that it saw the creation events](https://github.com/ceph/ceph/blob/acdd6bc0/src/test/rgw/bucket_notification/test_bn.py#L1318)

**Review by cbodley — APPROVED** [review]
thanks, approved but labeled DNM until we cut the squid rc

**Pull request merged**
