### PR TITLE
mgr/ssh: SELinux permits relabeling of /dev and /sys

### PR DESCRIPTION
**Pull request by jschmid1**
depends on https://github.com/ceph/ceph/pull/31457 (rebase after this is merged)

**only https://github.com/ceph/ceph/commit/83557eb441c45ea25f46e26e3c6140c6124d25e5 is relevant**

Adding a note that SELinux needs to be disabled(with the current code). Let's have a discussion here what the right move will be.

note: this should be tracked in a tracker-issue. There's currently no ceph-daemon subject, so I'll keep this here until we've created one. I'll move it over later and reference it properly.

Description:

> ceph orchestrator device ls

calls to `ceph-daemon` which then calls `ceph-volume` with:

> /bin/podman run --rm --net=host --privileged -e CONTAINER_IMAGE=ceph/daemon-base -e NODE_NAME=osd0 -v /run/lvm:/run/lvm:z -v /var/log/ceph/06b007a4-1339-43e2-ac29-79d3082e0a82:/var/log/ceph:z -v /run/udev:/run/udev:z -v /dev:/dev:z -v /run/lock/lvm:/run/lock/lvm:z -v /sys:/sys --entrypoint /usr/sbin/ceph-volume ceph/daemon-base inventory --format=json

resulting in:

> relabel failed "/dev": SELinux relabeling of /dev is not allowed

it also fails with

> relabel failed "/sys": SELinux relabeling of /sys is not allowed

when `/dev` is 'resolved'

following the recommendations from https://github.com/containers/libpod/issues/3683 yields mixed results.

* swapping `--privileged` with `--label=disable` *doesn't* work

* omitting the `z` attribute *works* (we need that to have 'rw' though?)

* setting SELinux to `permissive` *doesn't* work (although it should)

* disabling SELinux *works* (probably not desirable) 

additional output:

```
[root@osd0 ~]# ls -lZd /dev
drwxr-xr-x. root root system_u:object_r:device_t:s0    /dev
[root@osd0 ~]# ls -lZd /sys
dr-xr-xr-x. root root system_u:object_r:sysfs_t:s0     /sys
```

Signed-off-by: Joshua Schmid <jschmid@suse.de>

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by liewegas** [comment]
https://github.com/ceph/ceph/pull/31321

**Comment by liewegas** [comment]
see #31476 .. i think the selinux issues are all resolved now.

**Comment by sebastian-philipp** [comment]
close?

**Comment by jschmid1** [comment]
closed

**Comment by b-ranto** [comment]
What about the `Vangrantfile` changes? They are not needed anymore?

**Comment by jschmid1** [comment]
> What about the `Vangrantfile` changes? They are not needed anymore?

Those are part of #31457

**Pull request closed without merging**
