### PR TITLE
mgr/dashboard: Allow removal of single notification

### PR DESCRIPTION
**Pull request by tspmelo**
Signed-off-by: Tiago Melo <tmelo@suse.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`

</details>

### CODE REVIEW

**Comment by tspmelo** [comment]
Should we have just the icon 
btn-link
or an outlined button
btn-light

**Comment by votdev** [comment]
> Should we have just the icon
> btn-link
> or an outlined button
> btn-light

I vote for using an icon only.

The current implementation using a button looks not so nice on Chrome.
ksnip_20191022-121803

**Comment by votdev** [comment]
By the way, what about adding an option to copy a message to clipboard? This might be helpful in some cases without the need to select and copy the text manually.

Peek 2019-10-22 12-47

**Comment by LenzGr** [comment]
> By the way, what about adding an option to copy a message to clipboard? This might be helpful in some cases without the need to select and copy the text manually.

Agreed, that sounds like a useful follow-up enhancement (and maybe another good low-hanging-fruit task) - please add it to the tracker!

**Comment by LenzGr** [comment]
> Should we have just the icon
> btn-link

Using an icon adds less "visual noise". As discussed during the backlog grooming today, please use an icon (any align it with the Ceph icon below, if possible).

Thanks!

**Comment by tspmelo** [comment]
Updated.
Now it shows only the icon and is centered with the ceph logo.

image

**Comment by votdev** [comment]
Could we increase the icon size a little bit? I have to use a magnifier to identify it :-)

Bildschirmfoto vom 2019-10-28 11-42-44

**Comment by votdev** [comment]
Is it possible to use a link instead a button. With a button, there is an ugly border around the button when i press it.

Peek 2019-10-28 11-46

**Comment by tspmelo** [comment]
@votdev Fixed.

**Comment by votdev** [comment]
> I tested this locally - looks nice! However, I'm observing a strange behavior in that it does not remove the element that I'm actually clicking on, but the last one in the queue? See this animation for an example:
> Peek 2019-10-29 13-10

I assume the list of notifications is reverted before it is displayed to see the latest one at the top. The deletion takes the index of the displayed list item, thus if you try to delete the latest notification it will finally remove the oldest one.

**Comment by tspmelo** [comment]
Notifications are now sorted before being saved.
That way they will have the same order as displayed.

**Comment by LenzGr** [comment]
jenkins test make check

**Pull request merged**
