### PR TITLE
DNM osd: introduce shortcut for reads over replicated pools

### PR DESCRIPTION
**Pull request by rzarzynski**

### CODE REVIEW

**Comment by majianpeng** [comment]
Is there performance data?

**Comment by gregsfortytwo** [comment]
This is for crimson to replicate as an initial step, right? Do we actually want to merge this into master?

**Comment by tchaikov** [comment]
@gregsfortytwo no, i don't think we actually want to merge it into master. it's mainly used to model the crimson osd.

i am translating this to seastar at https://pad.ceph.com/p/crimson-io-path . it's just pseudo code.

**Comment by rzarzynski** [comment]
@majianpeng: below are numbers acquired on the occasion of profiling  the shortcut and some issues it exposed. 4 KB randreads over an RBD image, only one `tp_osd_tp` to strip the effects of `PG::_lock`, values are in KB/s:

```
reference:          83477, 80265, 84564, 85592, 84407,
shortcut:           87127, 90425, 90382, 89185, 89559,
shortcut + eventfd: 93069, 92588, 95790, 92606, 93105,
```

The last raw is with patch that replaces the pipes with eventfd for `EventCenter::wakeup()`.

**Comment by majianpeng** [comment]
@rzarzynski . performance improved at 9%~15%.  If using multi tp_osd_ops, the performance will drop much? and is this  because lock of pg?

**Comment by rzarzynski** [comment]
@majianpeng: I'm hunting for an incerta node. 07 is busy with fragmentation testing.

**Comment by rzarzynski** [comment]
A terribly outdated experimenting before crimson emerged. Closing.

**Pull request closed without merging**
