### PR TITLE
mgr/dashboard: Improve level A accessibility for missing aria labels in tabs and listitems

### PR DESCRIPTION
**Pull request by nSedrickm**
Replace tab component ul and li elements with navs and ng-containers

image

image

Fixes: https://tracker.ceph.com/issues/55872

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [x] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by nSedrickm** [comment]
Hi while working on this I found it difficult understanding where the tab content actually displays when the tab is clicked. An example is the ISCSI page. 

image

The tabs on this page are actually router links which display both the overview and targets below the tabs. While following the [ng-bootstrap docs](https://ng-bootstrap.github.io/releases/10.x/#/components/nav/overview) I expected to find a ngbNavOutlet which I can then match with the ngbNavItem on the nav tab to make it accessible. Currently I can't find it and also do not understand how the whole iscsi component works

**Comment by nizamial09** [comment]
> I expected to find a ngbNavOutlet which I can then match with the ngbNavItem on the nav tab to make it accessible. Currently I can't find it and also do not understand how the whole iscsi component works

You are right! There is no `ngbNavOutlet` for the iscsi component in each tabs. In the [overview page](https://github.com/ceph/ceph/blob/main/src/pybind/mgr/dashboard/frontend/src/app/ceph/block/iscsi/iscsi.component.html) and the [targets page](https://github.com/ceph/ceph/blob/main/src/pybind/mgr/dashboard/frontend/src/app/ceph/block/iscsi-target-list/iscsi-target-list.component.html) you can see the call for `<cd-iscsi-tabs>` which calls the [iscsi-tabs component](https://github.com/ceph/ceph/blob/main/src/pybind/mgr/dashboard/frontend/src/app/ceph/block/iscsi-tabs/iscsi-tabs.component.html), which works differently than all other pages. Are there accessibility issues with this page?

**Comment by ljflores** [comment]
jenkins retest this please

**Comment by ljflores** [comment]
@nSedrickm is there a Tracker for this item? If not, please create one and add it to the commit.

**Comment by ljflores** [comment]
> Are there accessibility issues with this page?

@nizamial09, there are 3 accessibility issues with iscsi according to Sedrick's Tracker. @nSedrickm maybe you could describe the issues for iscsi in detail?

**Comment by nSedrickm** [comment]
> > Are there accessibility issues with this page?
> 
> @nizamial09, there are 3 accessibility issues with iscsi according to Sedrick's Tracker. @nSedrickm maybe you could describe the issues for iscsi in detail?

Thanks @ljflores. In this case, the nav tabs and their outlets for some pages are in seperate components making it difficult to work on their accessibility. It was suggested to do a refactor. I only used the ISCSI page as an example. I will be making updates soon

**Comment by nSedrickm** [comment]
Hi @ljflores @nizamial09, I found a workaround for the issues I was facing earlier. The affected components were:

* prometheus-tabs (monitoring)
* rbd-tabs
* user-tabs(user-managemen)
* iscsi-tabs

Since the tabs are navlinks instead of tab links  they have been refactored to work without ng-bootstrap'ss directives

**Comment by nSedrickm** [comment]
jenkins test api

**Comment by nSedrickm** [comment]
jenkins test dashboard cephadm

**Comment by nSedrickm** [comment]
jenkins test dashboard

**Comment by nSedrickm** [comment]
jenkins test dashboard

**Comment by nSedrickm** [comment]
jenkins test dashboard cephadm

**Comment by nSedrickm** [comment]
jenkins test make check

**Comment by nSedrickm** [comment]
jenkins test make check

**Comment by nSedrickm** [comment]
jenkins test make check

**Comment by nSedrickm** [comment]
jenkins test dashboard

**Comment by nSedrickm** [comment]
jenkins test dashboard cephadm

**Comment by nSedrickm** [comment]
jenkins test windows

**Comment by nSedrickm** [comment]
jenkins test make check

**Comment by nSedrickm** [comment]
jenkins test dashboard cephadm

**Comment by nSedrickm** [comment]
jenkins test dashboard

**Comment by ljflores** [comment]
jenkins test dashboard cephadm

**Comment by ljflores** [comment]
jenkins test dashboard

**Comment by nSedrickm** [comment]
jenkins test dashboard cephadm

**Comment by nSedrickm** [comment]
jenkins test dashboard

**Comment by nSedrickm** [comment]
jenkins test dashboard cephadm

**Comment by nSedrickm** [comment]
jenkins test dashboard

**Comment by nSedrickm** [comment]
jenkins test windows

**Review by ljflores — APPROVED** [review]

**Comment by nSedrickm** [comment]
jenkins test dashboard

**Comment by nSedrickm** [comment]
jenkins test make check

**Comment by ljflores** [comment]
jenkins test make check

**Comment by ljflores** [comment]
jenkins test dashboard

**Comment by ljflores** [comment]
jenkins test dashboard cephadm

**Comment by ljflores** [comment]
@nSedrickm looks like the dashboard check is failing due to visual differences. Can you leave an explanation as to whether or not these are related to your PR? And if so, are they expected?

**Comment by nSedrickm** [comment]
> @nSedrickm looks like the dashboard check is failing due to visual differences. Can you leave an explanation as to whether or not these are related to your PR? And if so, are they expected?

@ljflores actually its the e2e tests failing. No screenshots are taken for this one. Also, I didn't update this branch from main so the dashboard a11y tests are failing. Will do a quick rebase.

**Comment by nSedrickm** [comment]
After taking a closer look as to why the dashboard a11y test was failing, it turns out it was due to an inaccessible pop up introduced on the page while the test was running. 

https://dashboard.cypress.io/projects/k7ab29/runs/13867/test-results/dc1f1625-92dd-4fc8-ab78-18f21b830fdf/screenshots

I'll open a PR addressing the notifications

**Comment by nSedrickm** [comment]
jenkins test dashboard

**Comment by Pegonzal** [comment]
jenkins test dashboard

**Comment by nSedrickm** [comment]
jenkins test dashboard cephadm

**Comment by ljflores** [comment]
@nSedrickm what is your analysis of why the "ceph dashboard cephadm" test is failing?

**Comment by nSedrickm** [comment]
> @nSedrickm what is your analysis of why the "ceph dashboard cephadm" test is failing?

Hi @ljflores, probably unrelated. The error is originating from the orchestrator workflow. Perhaps a rebase will help. @nizamial09 mentioned he was working on a fix

**Comment by nizamial09** [comment]
> > @nSedrickm what is your analysis of why the "ceph dashboard cephadm" test is failing?
> 
> Hi @ljflores, probably unrelated. The error is originating from the orchestrator workflow. Perhaps a rebase will help. @nizamial09 mentioned he was working on a fix

yup https://github.com/ceph/ceph/pull/48163

**Review by nizamial09 — APPROVED** [review]
LGTM! Thanks again @nSedrickm

**Pull request merged**
