### PR TITLE
mds: preparation for async dir operation support

### PR DESCRIPTION
**Pull request by ukernel**
cleanup and preparation pathes for https://github.com/ceph/ceph/pull/27866

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`

</details>

### CODE REVIEW

**Comment by jtlayton** [comment]
jenkins test make check

**Comment by jtlayton** [comment]
jenkins test make check arm64

**Comment by batrick** [comment]
@ukernel I'm going to run this through QA ASAP. Needs rebased though.

**Comment by ukernel** [comment]
updated

**Comment by jtlayton** [comment]
jenkins retest this please

**Comment by batrick** [comment]
http://pulpito.ceph.com/?branch=wip-pdonnell-testing-20191109.183750

**Comment by ukernel** [comment]
Commit 'mds: move 'traverse to auth' logic into MDCache::path_traverse' contains a multi-mds bug. please re-run multimds tests

**Comment by batrick** [comment]
pulpito.ceph.com/?branch=wip-pdonnell-testing-20191111.154849

**Comment by batrick** [comment]
@ukernel let me know if you found any problems in these test runs. I will take a look myself later today.

**Comment by ukernel** [comment]
test runs look good.  A few tests ran two slow, which causes timeout

**Comment by batrick** [comment]
Doubel checking some fs failures are unrelated: http://pulpito.ceph.com/pdonnell-2019-11-20_22:05:02-fs-wip-pdonnell-testing-20191120.192241-distro-basic-smithi/

**Comment by batrick** [comment]
@ukernel 

PTAL @ http://pulpito.ceph.com/pdonnell-2019-11-20_23:37:41-fs-wip-pdonnell-testing-20191120.192241-distro-basic-smithi/4527630/

This failure is new with your PR. Latest master nightly didn't see this: http://pulpito.ceph.com/teuthology-2019-11-19_03:15:03-fs-master-distro-basic-smithi/

**Comment by batrick** [comment]
Sorry, not this PR. It's also happening with another one:

http://pulpito.ceph.com/pdonnell-2019-11-21_22:49:13-fs-wip-pdonnell-testing-20191121.191852-distro-basic-smithi/4530520/

**Comment by batrick** [comment]
https://tracker.ceph.com/issues/42941

**Comment by batrick** [comment]
Zheng, I don't know how but this PR breaks the `config show` test:

http://pulpito.ceph.com/pdonnell-2019-11-20_23:37:41-fs-wip-pdonnell-testing-20191120.192241-distro-basic-smithi/4527596/

and another more recent build:

http://pulpito.ceph.com/pdonnell-2019-11-22_21:28:34-fs-wip-pdonnell-testing-20191122.191531-distro-basic-smithi/4534154/

compare to master:

/ceph/teuthology-archive/pdonnell-2019-11-22_22:39:39-fs-master-distro-basic-smithi/4534608/teuthology.log

mgr logs are different.  It might be something about the MDS changing what it sends to the mgr but I don't see how this PR would do that.

I'm still looking into this but so far I'm pretty confused.

**Comment by batrick** [comment]
cache drop test is also broken but I haven't looked into that one yet: http://pulpito.ceph.com/pdonnell-2019-11-22_21:28:34-fs-wip-pdonnell-testing-20191122.191531-distro-basic-smithi/4534150/

**Comment by ukernel** [comment]
I re-ran the 'config show' tests. They passed.
http://pulpito.ceph.com/zyan-2019-11-24_04:05:41-fs-wip-pdonnell-testing-20191120.192241-distro-basic-smithi/

maybe the failed test ran 'config show' command too fast, before mds reported its configs

**Comment by batrick** [comment]
The cache drop failures look the same as the latest nautilus run: http://pulpito.ceph.com/yuriw-2019-11-21_16:57:10-fs-wip-yuri-nautilus_14.2.5_RC1-distro-basic-smithi/

I'll review this again now and see if I can merge it.

**Pull request merged**
