### PR TITLE
osd: change mutex to spinlock to optimize thread context switch.

### PR DESCRIPTION
**Pull request by cxwshawn**
better use Spinlock since epoch_t is actually a built-in type to reduce 
thread context switch !

Signed-off-by: Xiaowei Chen <chen.xiaowei@h3c.com>

### CODE REVIEW

**Comment by cxwshawn** [comment]
@liewegas @athanatos please help review.

**Comment by liewegas** [comment]
two small issues, otherwise looks good!

**Comment by cxwshawn** [comment]
@liewegas fixed, please review again .

**Comment by liewegas** [comment]
Sorry, there is one other conditional where we might race.

Also, these got combined back into a single patch.. can yo useparate out the spinlock vs the atomic_t changes into separate commits again?

Also, prefix the commit with "osd: foo" instead of "[osd] foo".

Thanks!

**Comment by cxwshawn** [comment]
@liewegas fixed, please review again !

**Pull request merged**
