### PR TITLE
common/PrioritizedQueue: dequeue highest priority item in non-strict q

### PR DESCRIPTION
**Pull request by rldleblanc**
Dequeue the token queue from highest priority to lowest priority like the other queues.

Signed-off: Robert LeBlanc <robert.leblanc@endurance.com>

### CODE REVIEW

**Comment by athanatos** [comment]
I don't think this is right, it can end up starving the lower priority queues.  Those usually won't have enough tokens anyway, so it's harmless.

**Comment by athanatos** [comment]
It is the case, however, that we probably want to avoid the low probability check on the low queues if possible.  I'll have to think about that.

**Comment by athanatos** [comment]
You might get the same improvement by reducing the recovery priority.

**Comment by rldleblanc** [comment]
I do find that when max_backfills is really high (ie 20), you can get into a point were client I/O is waiting for a PG that is in recovery, but the recovery can get starved. I really don't like priority queues for this reason. I'm working on a new queue implementation to try a more fair share option.

Another option would be to not wait for recovery either by passing it to the surviving OSDs or promote the recovery OP in priority but I'm not sure how to find the recovery op in the queue.

I do think that what is currently implemented (before this patch) we can get blocked I/O as well, but it is the other way around (recovery ops can starve client ops) so I don't think either is ideal.

**Pull request closed without merging**
