### PR TITLE
mgr/volumes: subvolume ls command crashes if groupname as '_nogroup'

### PR DESCRIPTION
**Pull request by nmshelke**
If --group_name=_nogroup is provided in the command then it should be
treated as no '--group_name' option is provided.

Fixes: https://tracker.ceph.com/issues/55759
Signed-off-by: Nikhilkumar Shelke <nshelke@redhat.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/master/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [x] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Review by kotreshhr — DISMISSED** [review]

**Comment by kotreshhr** [comment]
As mentioned above,  removing the assert groupname != Group.NO_GROUP_NAME opens up all the subvolumegroup APIs including create, rm to go through on `_nogroup`. I think we should not allow write subvolumegroup operations on `_nogroup`. If we allow, user can create `_nogroup` group with restricted permissions and could break subvolume create API ? I have not tested this but thinking aloud.

The tracker was raised to fix the trace back that the assert was throwing to the user. We should decide on the behavior. There are following possibilities.

1. Allow read operations like subvolume ls when `_nogroup` is passed as group_name and disallow read/write operations like subvolumegroup create/rm
2. Don't allow any subvolume operations when `_nogroup` is passed and throw error message instead of the assert trace back.
    Users should not provide groupname to access subvolumes in `_nogroup`

@vshankar @ajarr @nmshelke  What you guys think ?

**Comment by vshankar** [comment]
> As mentioned above, removing the assert groupname != Group.NO_GROUP_NAME opens up all the subvolumegroup APIs including create, rm to go through on `_nogroup`. I think we should not allow write subvolumegroup operations on `_nogroup`. If we allow, user can create `_nogroup` group with restricted permissions and could break subvolume create API ? I have not tested this but thinking aloud.

We should have a blanket restriction for explicit access/update to `_nogroup` group to avoid any surprises and to have uniform control-flow across commands.

> 
> The tracker was raised to fix the trace back that the assert was throwing to the user. We should decide on the behavior. There are following possibilities.
> 
> 1. Allow read operations like subvolume ls when `_nogroup` is passed as group_name and disallow read/write operations like subvolumegroup create/rm
> 2. Don't allow any subvolume operations when `_nogroup` is passed and throw error message instead of the assert trace back.
>    Users should not provide groupname to access subvolumes in `_nogroup`

I vote for the latter.

**Review by ajarr — CHANGES_REQUESTED** [review]
As Kotresh suggested, let's instead do
"Don't allow any subvolume operations when _nogroup is passed and throw error message instead of the assert trace back. Users should not provide groupname to access subvolumes in _nogroup " . 

I guess throw permission denied message when accessing _nogroup?

**Comment by kotreshhr** [comment]
> As Kotresh suggested, let's instead do "Don't allow any subvolume operations when _nogroup is passed and throw error message instead of the assert trace back. Users should not provide groupname to access subvolumes in _nogroup " .
> 
> I guess throw permission denied message when accessing _nogroup?

Sounds good to me. @nmshelke Please make the changes appropriately.

**Comment by nmshelke** [comment]
> > As Kotresh suggested, let's instead do "Don't allow any subvolume operations when _nogroup is passed and throw error message instead of the assert trace back. Users should not provide groupname to access subvolumes in _nogroup " .
> > I guess throw permission denied message when accessing _nogroup?
> 
> Sounds good to me. @nmshelke Please make the changes appropriately.

@vshankar @kotreshhr @ajarr Fixed the issue as per suggestions.
Could you please take a look?

**Review by kotreshhr — APPROVED** [review]
LGTM

**Review by vshankar — APPROVED** [review]

**Review by vshankar — APPROVED** [review]
https://tracker.ceph.com/projects/cephfs/wiki/Master#2022-June-20

**Pull request merged**
