### PR TITLE
rgw: uploads a part by copying data from an existing object as data source…

### PR DESCRIPTION
**Pull request by zhouruisong**
Uploads a part by copying data from an existing object as data source. You specify the data source by adding the request header x-amz-copy-source in your request and a byte range by adding the request header x-amz-copy-source-range in your request.
detail information as follow:
http://docs.aws.amazon.com/zh_cn/AmazonS3/latest/API/mpUploadUploadPartCopy.html
Fixes: http://tracker.ceph.com/issues/16582

Signed-off-by: zhouruisong 236131368@qq.com

### CODE REVIEW

**Comment by zhouruisong** [comment]
@mattbenjamin how about this feature？please give me some advice and I will update the code, thanks!

**Comment by zhouruisong** [comment]
@cbodley @mattbenjamin this code I have executed and run successfully.

**Comment by zhouruisong** [comment]
@ dang  Do you know about this feature? Is mattbenjamin out?

**Comment by yehudasa** [comment]
@mattbenjamin ping

**Comment by zhouruisong** [comment]
@mattbenjamin do you see this feature？

**Comment by zhouruisong** [comment]
@yehudasa  
is mattbenjamin out?

**Pull request closed without merging**
