### PR TITLE
luminous: rgw: URL-decode S3 and Swift object-copy URLs

### PR DESCRIPTION
**Pull request by mattbenjamin**
http://tracker.ceph.com/issues/22893
http://tracker.ceph.com/issues/22903

### CODE REVIEW

**Comment by mattbenjamin** [comment]
@rzarzynski this was a clean backport, are you available to review this?
@oritwas maybe?
I'd like this to merge today, if at all possible.

**Comment by mattbenjamin** [comment]
http://pulpito.ceph.com/mbenjamin-2018-02-01_21:22:30-rgw-wip-rgw-mploc---basic-smithi/
(passed)

**Comment by mattbenjamin** [comment]
(oops, that was the wrong one)

**Comment by mattbenjamin** [comment]
(will submit an RGW suite run shortly)

**Comment by rzarzynski** [comment]
@mattbenjamin: yeah, having a run would be needed especially as the changes are pretty vulnerable to `nullptr` dereferences (had some on `master` PR).

**Comment by mattbenjamin** [comment]
http://pulpito.ceph.com/mbenjamin-2018-02-03_15:31:48-rgw-luminous-rgw-22121---basic-smithi/

**Comment by yuriw** [comment]
[wip-yuri2-testing-2018-02-21-1824-luminous](https://trello.com/c/qr22U1kB/266-wip-yuri2-testing-2018-02-21-1824-luminous)

**Pull request merged**
