### PR TITLE
rgw: small code fix-ups

### PR DESCRIPTION
**Pull request by ivancich**
A collection of fix-ups that include:
* improved logging
* code documentation
* conforming to ceph coding standards
* ability to output a rgw::sal::Bucket::ListParams struct easily

Signed-off-by: J. Eric Ivancich <ivancich@redhat.com>
Note: no tracker is necessary as no backports are expected.

### CODE REVIEW

**Comment by ivancich** [comment]
@alimaredia : there's really no logic change here, so after review it can probably be merged. Thanks!

**Comment by ivancich** [comment]
jenkins test api

**Review by dang — APPROVED** [review]

**Comment by ivancich** [comment]
Teuthology Results:
* https://pulpito.ceph.com/ivancich-2021-11-16_04:33:57-rgw-wip-eric-testing-1-distro-basic-smithi/
* https://pulpito.ceph.com/ivancich-2021-11-16_04:34:19-rgw-wip-eric-testing-1-distro-basic-smithi/

No regressions.

**Comment by ivancich** [comment]
jenkins test api

**Pull request merged**
