### PR TITLE
cmake: compile C code with c99

### PR DESCRIPTION
**Pull request by tchaikov**
so the functions like snprintf() available in C99 are available without
defining _XOPEN_SOURCE.

Signed-off-by: Kefu Chai <kchai@redhat.com>

### CODE REVIEW

**Comment by tchaikov** [comment]
@wjwithagen thanks for testing!

**Comment by liewegas** [comment]
/home/jenkins-build/build/workspace/ceph-pull-requests/src/arch/intel.c: In function ‘do_cpuid’:
/home/jenkins-build/build/workspace/ceph-pull-requests/src/arch/intel.c:35:9: warning: implicit declaration of function ‘asm’ [-Wimplicit-function-declaration]
         asm("movl %4, %%eax;"
         ^
/home/jenkins-build/build/workspace/ceph-pull-requests/src/arch/intel.c:41:17: error: expected ‘)’ before ‘:’ token
                 : "=r" (*eax), "=r" (*ebx), "=r" (*ecx), "=r" (*edx)
                 ^
/home/jenkins-build/build/workspace/ceph-pull-requests/src/arch/intel.c:33:13: warning: unused variable ‘id’ [-Wunused-variable]
         int id = *eax;
             ^

**Comment by wjwithagen** [comment]
Probably this will get fixed by switching the compiler options on...
`   set(CMAKE_C_EXTENSIONS ON) `
This will get C compilation running with `-std=gnu99` 

Clang does accept it, and still compiles without any warnings

**Comment by tchaikov** [comment]
@liewegas fixed and repushed.

**Comment by tchaikov** [comment]
@wjwithagen got it, thanks!

**Pull request merged**
