### PR TITLE
doc/man/cephfs-shell.rst: add use of exclamation mark with cmds

### PR DESCRIPTION
**Pull request by dparmar18**
Description: `!` -  Exclamation mark can be used to interact with local
                    file system apart from Ceph File System too. This PR intends
                    to document it.

Signed-off-by: Dhairya Parmar <dparmar@redhat.com>

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [x] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [x] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Review by rishabh-d-dave — DISMISSED** [review]
I think this feature ought to be a sub-section in the cephfs-shell man page then just a note point.

More importantly, the usage and example are not a part of the note point. Even if you want to keep details of this feature as a note, the entire text must be a part of it.

**Comment by dparmar18** [comment]
> I think this feature ought to be a sub-section in the cephfs-shell man page then just a note point.
> 
> More importantly, the usage and example are not a part of the note point. Even if you want to keep details of this feature as a note, the entire text must be a part of it.

@rishabh-d-dave , I think it's not much of info, it doesn't look bad/irrelevant as a note. What do you think? Apart from that, I've pushed the changes and now the usage ad example are part of note point. Looking forward for your feedback.

**Comment by rishabh-d-dave** [comment]
@dparmar18 
> @rishabh-d-dave , I think it's not much of info, it doesn't look bad/irrelevant as a note. What do you think?

It's doesn't look bad/irrelevat but we are describing an entire feature with its syntax and usage inside a note. I do feel it deserves a sub-section of it's own. If you think that in certain section of man page using exclamation mark can seriously help, add a note there pointing to this sub-section on cephfs-shell.

**Comment by rishabh-d-dave** [comment]
@dparmar18 

Perhaps the best thing to do it add link to https://cmd2.readthedocs.io/en/latest/features/shortcuts_aliases_macros.html

**Comment by dparmar18** [comment]
> @dparmar18
> 
> Treating exclamation mark as a special symbol is not coded in cephfs-shell but in the library that cephfs-shell uses (which is cmd2). Perhaps the best thing to do is add a note here that would briefly talk about similar features and pass a link to cmd2 doc page. This way we will prevent duplication and the man page will be more complete (because we mention all special symbols and similar features), and more maintainable (since we won't have to synchronize cephfs-shell man page with cmd2 doc page at every cmd2 release).
> 
> cmd2 doc page that needs to be linked - https://cmd2.readthedocs.io/en/latest/features/shortcuts_aliases_macros.html

Nice Idea, maybe we should just add a note mentioning the doc link?

**Comment by dparmar18** [comment]
> > Nice Idea, maybe we should just add a note mentioning the doc link in the COMMANDS section?
> 
> I think having a brief mention of features described on link is vital to get reader's attention. Otherwise, no one would click on the link.

Okay

**Comment by rishabh-d-dave** [comment]
> @dparmar18
> 
> Treating exclamation mark as a special symbol is not coded in cephfs-shell but in the library that cephfs-shell uses (which is cmd2). Perhaps the best thing to do is add a note here that would briefly talk about similar features and pass a link to cmd2 doc page. This way we will prevent duplication and the man page will be more complete (because we mention all special symbols and similar features), and more maintainable (since we won't have to synchronize cephfs-shell man page with cmd2 doc page at every cmd2 release).
> 
> cmd2 doc page that needs to be linked - https://cmd2.readthedocs.io/en/latest/features/shortcuts_aliases_macros.html

@vshankar Any opinion?

**Comment by vshankar** [comment]
> > @dparmar18
> > Treating exclamation mark as a special symbol is not coded in cephfs-shell but in the library that cephfs-shell uses (which is cmd2). Perhaps the best thing to do is add a note here that would briefly talk about similar features and pass a link to cmd2 doc page. This way we will prevent duplication and the man page will be more complete (because we mention all special symbols and similar features), and more maintainable (since we won't have to synchronize cephfs-shell man page with cmd2 doc page at every cmd2 release).
> > cmd2 doc page that needs to be linked - https://cmd2.readthedocs.io/en/latest/features/shortcuts_aliases_macros.html
> 
> @vshankar Any opinion?

I think its fine as it is. We need not overwhelm with links and other information. Just a note (as done in this PR) is good enough.

**Review by vshankar — APPROVED** [review]

**Comment by vshankar** [comment]
@rishabh-d-dave Any more comments for this change?

**Comment by rishabh-d-dave** [comment]
@vshankar The current PR is fine but we are missing informing cephfs-shell user about other features like aliases, macros and other shortcuts other than `!`. I think this is a good opportunity to get this done.

**Comment by vshankar** [comment]
> @vshankar The current PR is fine but we are missing informing cephfs-shell user about other features like aliases, macros and other shortcuts other than `!`. I think this is a good opportunity to get this done.

Let's have a PR that adds all that info in the doc. It need not block this.

**Pull request merged**
