### PR TITLE
TestAsyncDriver: Fix typo in ceph_test_async_driver

### PR DESCRIPTION
**Pull request by yuyuyu101**
Signed-off-by: Haomai Wang <haomaiwang@gmail.com>

### CODE REVIEW

**Comment by yuyuyu101** [comment]
http://tracker.ceph.com/issues/11058

**Comment by dachary** [comment]
@yuyuyu101 could you please add Fixes: #11058 in the commit message for cross reference ?

**Comment by yuyuyu101** [comment]
@dachary done

**Comment by dachary** [comment]
@yuyuyu101 I'm assuming the error came from tests run by sage and will need to be re-incorporated in his test branch, hence the **needs-qa** label. If I'm mistaken, please fix ;-)

**Pull request merged**
