### PR TITLE
osd: fix deadlock in OSD::_committed_osd_maps

### PR DESCRIPTION
**Pull request by XinzeChi**
Fixes: #15701
Signed-off-by: Xinze Chi <xinze@xsky.com>

### CODE REVIEW

**Comment by XinzeChi** [comment]
@liewegas , Do you think it is suitable to fix it?

**Comment by liewegas** [comment]
This looks reasonable to me!  It would be really nice if there were a test for this.. I don't think we have anything that exercises the forced shutdown path.

**Comment by yuyuyu101** [comment]
two possible cases to trigger force shutdown:
1. set osd_max_markdown_count to 1
2. manually set link down, so it can make rebind failed

**Comment by tchaikov** [comment]
better off putting `Fixes: http://tracker.ceph.com/issues/15701` in commit message.

**Comment by liewegas** [comment]
want to run this through one more time since there were some suspicous failures in the last run.

**Pull request merged**
