### PR TITLE
octopus: mon/MonCommands.h: fix target_size_ratio range

### PR DESCRIPTION
**Pull request by kamoltat**
- Modified the range of `target_size_ratio`  from `0.0 -> 1.0 ` to  `0.0 -> nolimit`
- Throw an error when user set `target_size_ratio` to negative using the command:
    `osd pool set <pool> target_size_ratio <float>`
-  Added test cases regarding`target_size_ratio` to qa/workunits/cephtool/test.sh
- Did not cherry-pick  `4add5feff657aad2afbec56a21b544bedf7f9b95` because octopus doesn't contain the commit that contains white space.

Backporting related commits from master PR(s):
#45078

Fixes: https://tracker.ceph.com/issues/54568

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [x] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Review by neha-ojha — APPROVED** [review]

**Comment by neha-ojha** [comment]
jenkins test make check

**Comment by kamoltat** [comment]
jenkins test make check

**Comment by kamoltat** [comment]
@neha-ojha think this one should be good for testing

**Comment by yuriw** [comment]
jenkins test make check

**Comment by yuriw** [comment]
jenkins test make check

**Comment by ljflores** [comment]
jenkins test make check

**Pull request merged**
