### PR TITLE
Pacific ceph mixin backports

### PR DESCRIPTION
**Pull request by MrFreezeex**
Backports of https://github.com/ceph/ceph/pull/47625, https://github.com/ceph/ceph/pull/47284, https://github.com/ceph/ceph/pull/47334, https://github.com/ceph/ceph/pull/47633, https://github.com/ceph/ceph/pull/47669, https://github.com/ceph/ceph/pull/47675, https://github.com/ceph/ceph/pull/47707

Only one pr got a tracker: https://tracker.ceph.com/issues/56948

### CODE REVIEW

**Comment by MrFreezeex** [comment]
jenkins test make check

**Comment by MrFreezeex** [comment]
jenkins test api

**Comment by nizamial09** [comment]
@MrFreezeex I took the liberty of updating the PR. there were some doc related rebase needed so it was only minor.

**Review by nizamial09 — APPROVED** [review]

**Comment by MrFreezeex** [comment]
> @MrFreezeex I took the liberty of updating the PR. there were some doc related rebase needed so it was only minor.

Sure, thank you!

**Comment by nizamial09** [comment]
shaman [ongoing](https://shaman.ceph.com/builds/ceph/wip-nizamial09-testing-2022-09-23-1057-pacific/)  :construction:

**Comment by yuriw** [comment]
@MrFreezeex this PRs was tested as part of https://trello.com/c/zajp2JVu
If this is sufficient pls merge

**Pull request merged**
