### PR TITLE
librgw/notifications: initialize kafka and amqp

### PR DESCRIPTION
**Pull request by yuvalif**
Fixes: https://tracker.ceph.com/issues/49738

Signed-off-by: Yuval Lifshitz <ylifshit@redhat.com>

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Review by mattbenjamin — APPROVED** [review]
lgtm++

**Comment by yuvalif** [comment]
@matt is there a librgw test suite in teuthology i can run against this change?

**Comment by mattbenjamin** [comment]
> 
> 
> @matt is there a librgw test suite in teuthology i can run against this change?

Yes, rgw/verify will exercise the rgw_file call paths.

Matt

**Comment by yuvalif** [comment]
passing teuthology: http://pulpito.front.sepia.ceph.com/yuvalif-2021-03-31_17:47:12-rgw:verify-wip-yuval-fix-49738-distro-basic-gibba/

**Comment by cbodley** [comment]
thanks @yuvalif - when you merge PRs with associated trackers issues, please remember to update the tracker to either Resolved or Pending Backport

**Pull request merged**
