### PR TITLE
mgr/dashboard:add unittest in test_osd.py

### PR DESCRIPTION
**Pull request by zhangmengqianyw**
Add some unittests in src/pybind/mgr/dashboard/tests/test_osd.py
Signed-off-by: Zhang Meng Qian <zhangmengqian_yewu@cmss.chinamobile.com>

### CODE REVIEW

**Comment by zhangmengqianyw** [comment]
@avanthakkar @nizamial09  It has been 14 days since I submitted my code. Please review my code. Is there any problem with it?

**Comment by nizamial09** [comment]
> @avanthakkar @nizamial09 It has been 14 days since I submitted my code. Please review my code. Is there any problem with it?

Hey @zhangmengqianyw sorry for not reviewing it since now. I've kind of missed this since this was not in the Dashboard project board. Also could you confirm if this is the same as of https://github.com/ceph/ceph/pull/43729?

**Comment by nizamial09** [comment]
jenkins test api

**Review by alfonsomthd — APPROVED** [review]
LGTM. Thanks for addressing the previous PR comments!

**Review by avanthakkar — APPROVED** [review]

**Comment by zhangmengqianyw** [comment]
> > @avanthakkar @nizamial09 It has been 14 days since I submitted my code. Please review my code. Is there any problem with it?
> 
> Hey @zhangmengqianyw sorry for not reviewing it since now. I've kind of missed this since this was not in the Dashboard project board. Also could you confirm if this is the same as of #43729?

You are right. Due to my operation error, I deleted the #43729 by mistake. Therefore, I submitted this PR after improvement.

**Review by nizamial09 — APPROVED** [review]

**Pull request merged**
