### PR TITLE
 librados: add OPERATION_ORDERSNAP flag and yet another aio_operate method

### PR DESCRIPTION
**Pull request by trociny**
The new method allows to specify both flags and snap context.

This is going to be used in librbd, object deep copy, in order to allow two or more clients to do a deep-copyup concurrently (#15831).

### CODE REVIEW

**Comment by gregsfortytwo** [comment]
I hadn't heard of ORDERSNAP before, and when I grep, the only thing it actually does in the OSD is return an error if the client's snapc.seq is older than what it's seen locally. (Based on recent-ish commit messages about it being misguided attempts at making cache tiering work with snapshots, I'm also not enthused about it being used again.)

Is that really the semantic you're looking for from this interface?

**Comment by trociny** [comment]
> Is that really the semantic you're looking for from this interface?

Yes, please see this comment: https://github.com/ceph/ceph/pull/15831#issuecomment-361643801

**Comment by dillaman** [comment]
@gregsfortytwo I double-checked w/ @jdurgin and @liewegas last Wednesday about re-using this flag vice creating a RBD "deep_copyup" class method w/ new classobj hooks for reading the current object's snap sequence and they seemed fine w/ it.

**Comment by gregsfortytwo** [comment]
👍

**Comment by dillaman** [comment]
@gregsfortytwo @jdurgin Any additional review comments on this?

**Comment by tchaikov** [comment]
- http://pulpito.ceph.com/kchai-2018-04-20_05:42:59-rados-wip-kefu-testing-2018-04-20-1141-distro-basic-smithi/
- http://pulpito.ceph.com/kchai-2018-04-20_14:33:42-rados-wip-kefu-testing-2018-04-20-1141-distro-basic-mira/

the failures are addressed by 

- #21549
- #21579

**Pull request merged**
