### PR TITLE
common/TrackedOp: fix inaccurate counting for slow requests

### PR DESCRIPTION
**Pull request by xiexingguo**
Also fix implicitly result code cast.

### CODE REVIEW

**Comment by tchaikov** [comment]
@xiexingguo could you elaborated a little bit why the total # of slow request is not accurate? iiuc, we failed to collect the last op in the warning message. but it would better if you can put it in your commit message to help reviewers and other developers to understand your change.

**Comment by xiexingguo** [comment]
@tchaikov 
In the original design there are two counters in charge of collecting potentially problematic requests, namely 'slow' and 'warned'. Counter 'slow' is responsible for capturing all the requests which has already hit the "complain" limit and shall be marked as "slow" while counter 'warned' is responsible for countering those requests which has already hit the "warning interval" and thus shall be logged and then outputted.  

The problem here is if 'warned' counter hits the log_threshold, we will quit the entire __for__ loop but there may be residual shard_queues which may still containing slow requests. As a result, the 'slow' counter does not reflect the real number of total slow requests in all the shard_queues under this case.

The solution for the above problem is to keep counting 'slow' requests until we have finished traversing all the shard_queues,  no matter whether we have gathered enough requests for log or not, and if so, we simply stop counter 'warned' and skip over logging process.

**Comment by xiexingguo** [comment]
@tchaikov  Updated and thank you for your attention. Ping me if there is anything to be further clarified.

**Comment by tchaikov** [comment]
lgtm. @xiexingguo thanks for the excellent explanation! it really helps.

**Comment by xiexingguo** [comment]
My pleasure.  And thank you for your careful review. I've learned so much.

**Pull request merged**
