### PR TITLE
pybind/rados: fix set_omap() crash on py3

### PR DESCRIPTION
**Pull request by liewegas**

### CODE REVIEW

**Comment by liewegas** [comment]
retest this please

**Comment by tchaikov** [comment]
jenins, retest this please

**Comment by sebastian-philipp** [comment]
According to https://github.com/ceph/ceph/pull/30483#issuecomment-535873920 this might need a backport to Nautilus?

**Comment by liewegas** [comment]
@smithfarm ?

**Comment by smithfarm** [comment]
nautilus backport: https://github.com/ceph/ceph/pull/30622

**Pull request merged**
