### PR TITLE
qa/tasks: use items() for py3 compatibility

### PR DESCRIPTION
**Pull request by kshtsk**
Fixes: https://tracker.ceph.com/issues/42267

### CODE REVIEW

**Comment by kshtsk** [comment]
@tchaikov @batrick the idea was to to ease backporting to older branches, @smithfarm what do you recommend?

**Comment by smithfarm** [comment]
@batrick I think having smaller commits makes it easier to backport. Some of the commits might even cherry-pick without any conflicts, and the number of conflicts per commit will be smaller than if we squash them all together.

**Comment by smithfarm** [comment]
@batrick AFAICT we will have no choice but to backport all of the py3 compatibility changes (and there will be many) because, at some point, teuthology will be migrated to py3.

At the moment we have only one tracker issue open: https://tracker.ceph.com/issues/42210

Since, at the moment, there is only one person (@kshtsk) doing this work, it'll be pretty easy to gather all the PRs/commits together and backport them, but I agree that we need trackers for this and trackers there will be!

**Comment by smithfarm** [comment]
added tracker for this PR

**Comment by smithfarm** [comment]
Opened a tracker, https://tracker.ceph.com/issues/42267, for this PR.

Also created an "umbrella" tracker https://tracker.ceph.com/issues/42266 and changed https://tracker.ceph.com/issues/42267 into a subtask of that.

**Comment by batrick** [comment]
> @batrick AFAICT we will have no choice but to backport all of the py3 compatibility changes (and there will be many) because, at some point, teuthology will be migrated to py3.
> 
> At the moment we have only one tracker issue open: https://tracker.ceph.com/issues/42210
> 
> Since, at the moment, there is only one person (@kshtsk) doing this work, it'll be pretty easy to gather all the PRs/commits together and backport them, but I agree that we need trackers for this and trackers there will be!

The other issue to consider is that fixes to master may miss necessary fixes to nautilus/mimic. e.g. some code which was removed in master may exist in nautilus that needs updated.

I'm no longer sure the normal backport strategy applies here unless the backported fix carefully considers whether any other code in the release also needs changed. This is made more difficult since we can't actually test py3 until we do the switch... (What a mess...)

Also, I don't really see any value from a backporter perspective in splitting one logical change into 40 commits. It surely slows down the cherry-pick process as you need to go back to the source tree constantly to fix conflicts? It also clutters up the repo log history.

**Comment by smithfarm** [comment]
> The other issue to consider is that fixes to master may miss necessary fixes to nautilus/mimic. e.g. some code which was removed in master may exist in nautilus that needs updated.

> I'm no longer sure the normal backport strategy applies here

@batrick OK, you convinced me :-)

@kshtsk I no longer have any objection to squashing the commits.

**Comment by kshtsk** [comment]
> > The other issue to consider is that fixes to master may miss necessary fixes to nautilus/mimic. e.g. some code which was removed in master may exist in nautilus that needs updated.
> 
> > I'm no longer sure the normal backport strategy applies here
> 
> @batrick OK, you convinced me :-)
> 
> @kshtsk I no longer have any objection to squashing the commits.

done

**Comment by smithfarm** [comment]
Thanks, @batrick and @tchaikov - can you guys include this in one of your future integration branches?

**Comment by smithfarm** [comment]
@kshtsk Please add to the commit message:

```
Fixes: https://tracker.ceph.com/issues/42267
```

**Comment by kshtsk** [comment]
@smithfarm @batrick I've added iterkeys() patch, since they might be conflicted if try to merge separately, could you please review again.

**Comment by kshtsk** [comment]
If you're okay with that then I can close #30873 as duplicate for this PR.
Should I squash these two commits too?

**Comment by kshtsk** [comment]
jenkins test make check arm64

**Comment by tchaikov** [comment]
@kshtsk needs rebase

**Comment by kshtsk** [comment]
> If you're okay with that then I can close #30873 as duplicate for this PR.
> Should I squash these two commits too?

Okay, I see the  #30873 merged, dropped the iterkeys patch from this PR and rebased again.

**Comment by kshtsk** [comment]
> @kshtsk needs rebase
@tchaikov 
done

**Comment by kshtsk** [comment]
jenkins test make check

**Comment by kshtsk** [comment]
jenkins test make check arm64

**Pull request merged**
