### PR TITLE
mds/Server.cc: Don't evict a slow client if...

### PR DESCRIPTION
**Pull request by stiopaa1**
... it's the only client

Fixes: http://tracker.ceph.com/issues/17855
Signed-off-by: Michal Jarzabek <stiopa@gmail.com>

### CODE REVIEW

**Comment by jcsp** [comment]
Looks good to me, what do you think @ukernel @gregsfortytwo ?

**Comment by gregsfortytwo** [comment]
Yeah, this is a nice simple one. I was debating if we should try and do something even a little more sophisticated like see if the *newest* client is new enough to avoid being evicted?
That doesn't seem much harder but then of course it's a pretty continuous slope.

**Comment by jcsp** [comment]
> see if the newest client is new enough to avoid being evicted?

@gregsfortytwo I don't think I follow?

**Comment by gregsfortytwo** [comment]
This logic is preventing us from booting a single client. A marginally more complicated thing is to see if *all* the clients are in the same laggy/not-laggy state, and not evict them if they are all the same even if they're laggy.

**Comment by jcsp** [comment]
Oh right, that makes sense.

**Comment by jcsp** [comment]
Unrelated: the test for this seems to be failing:
```
2017-01-17T03:09:52.250 INFO:tasks.cephfs_test_runner:======================================================================
2017-01-17T03:09:52.250 INFO:tasks.cephfs_test_runner:FAIL: test_evict_client (tasks.cephfs.test_misc.TestMisc)
2017-01-17T03:09:52.250 INFO:tasks.cephfs_test_runner:----------------------------------------------------------------------
2017-01-17T03:09:52.250 INFO:tasks.cephfs_test_runner:Traceback (most recent call last):
2017-01-17T03:09:52.250 INFO:tasks.cephfs_test_runner:  File "/home/teuthworker/src/github.com_ceph_ceph-c_wip-jcsp-testing-20170116/qa/tasks/cephfs/test_misc.py", line 62, in test_evict_client
2017-01-17T03:09:52.250 INFO:tasks.cephfs_test_runner:    self.assert_session_count(1, ls_data)
2017-01-17T03:09:52.250 INFO:tasks.cephfs_test_runner:  File "/home/teuthworker/src/github.com_ceph_ceph-c_wip-jcsp-testing-20170116/qa/tasks/cephfs/cephfs_test_case.py", line 211, in assert_session_count
2017-01-17T03:09:52.250 INFO:tasks.cephfs_test_runner:    expected, len(ls_data)
2017-01-17T03:09:52.250 INFO:tasks.cephfs_test_runner:AssertionError: Expected 1 sessions, found 2
```

@stiopaa1 is it passing when you run locally with vstart_runner.py?

**Comment by stiopaa1** [comment]
@jcsp 
Yes, it it was definitely passing when I was testing it locally

**Comment by jcsp** [comment]
@stiopaa1 ok, can you look at this log to see if you have a theory about why it's failing when run in automation?

The test script output: http://qa-proxy.ceph.com/teuthology/jspray-2017-01-16_21:41:35-fs-wip-jcsp-testing-20170116-distro-basic-smithi/723026/teuthology.log

The logs from the nodes (including mds etc): http://qa-proxy.ceph.com/teuthology/jspray-2017-01-16_21:41:35-fs-wip-jcsp-testing-20170116-distro-basic-smithi/723026/remote/

**Comment by stiopaa1** [comment]
@jcsp 
I think it should work now.

The previous version worked for me locally only because I had 
mds_session_autoclose equal to mds_session_timeout in ceph.conf

**Comment by ukernel** [comment]
mds may send session flush message to client during subtree migration. If the only client is really dead, it hangs the subtree migration process

**Comment by jcsp** [comment]
Discussed this briefly on CDM call -- I think we need some logic here during export to evict the slow client if we left it alive because it was the only one.

There is also the case where the client is slow on mds A but migration is from B to C -- in this case we just don't care.

**Comment by stiopaa1** [comment]
@jcsp 
>Discussed this briefly on CDM call -- I think we need some logic here during export to evict the slow client if we left it alive because it was the only one.

Not familiar yet with exporting, but just had a quick look and found  Migrator::export_dir function. Is it more or less where I should be looking?

**Comment by ukernel** [comment]
I think we can enable this for single mds only

**Comment by jcsp** [comment]
@stiopaa1 for now, let's just make this code only run when there is a single MDS.

So something like this:
```
if (mds->sessionmap.get_sessions().size() == 1 && mds->mdsmap->get_num_in_mds() == 1)
```

Sorry for the slow response.

**Comment by jcsp** [comment]
(& this needs a rebase)

**Comment by stiopaa1** [comment]
@jcsp 
will have a look into this

**Comment by tchaikov** [comment]
@stiopaa1 ping?

**Comment by stiopaa1** [comment]
@tchaikov 
Sorry, I've been a bit busy recently.  Will try to have a look at this at the weekend.

**Comment by stiopaa1** [comment]
@tchaikov @jcsp 
I have added:
`    mds->mdsmap->get_num_in_mds() == 1`

and rebased

**Comment by jcsp** [comment]
Thanks @stiopaa1, I've pulled this into my latest testing branch so it should merge soon

**Pull request merged**
