### PR TITLE
mon/OSDMonitor.cc refactor

### PR DESCRIPTION
**Pull request by stiopaa1**
@jecluis 
I fixed the issues you mentioned in 
https://github.com/ceph/ceph/pull/3887

### CODE REVIEW

**Comment by jecluis** [comment]
haven't looked at individual commits yet, but you will need to change the commit titles and messages to something more verbose than simply 'refactoring'.

**Comment by jecluis** [comment]
This branch needs to be cleaned up before we can merge it.  I have a few comments throughout, but the blocker is, and will be, the commit message's body's and title.

Also, given this is solely a cleanup that does not fix a particular issue or introduces a new feature, and because this pull request touches a fairly large portion of the OSDMonitor, we should postpone merging it until we make sure we have merged all other pull requests introducing bug fixes or features that could possibly conflict with this patch set.

**Comment by stiopaa1** [comment]
I understand that you might not like titles of the commits(mon/OSDMonitor.cc: refactoring), because they are the same in 4 cases, but what is wrong with the bodies of those commits?

**Comment by jecluis** [comment]
I apologize for not having given context, but I meant to say that your titles could use some of the info on the body. Also, 8f0a5e70cd28090bb6a2de8317657678f017b2e5 looks like it has a lot more than 80 chars on the body - which makes the commit message look funny.

**Comment by stiopaa1** [comment]
Not sure why this is in incorrect order again... my git log shows them in this order:
commit 2857dedead7f70962bb4e5a8e607c91bcbfb757a
commit 85b25ce61270f348eedd281ffc103b1a0da736d6
commit 22cbd87f4f0596189b071fb9a8de0d9ff1a295d5
commit 09604b389c11c0b201ec8d8703480826d9adda78
commit 3bb61517ed72f0b8187bf3045b1325edc4d562f2

**Comment by stiopaa1** [comment]
This would explain it:
https://help.github.com/articles/why-are-my-commits-in-the-wrong-order/

**Comment by dachary** [comment]
As explained in https://github.com/ceph/ceph/blob/master/CONTRIBUTING.rst we do refactoring when also implementing a feature or fixing a bug.

**Comment by stiopaa1** [comment]
@dachary:
This was implemented as a part of #3887, so not sure why this was closed?

**Comment by dachary** [comment]
@stiopaa1 I'm sorry, did I miss that this pull request fixes a bug or implements a feature ?

**Comment by stiopaa1** [comment]
@dachary: this one doesn't. #3887 was implementing the feature in which @jecluis expressed his concerns about this part of code, which this pull request was supposed to fix. 
So I you want to follow  https://github.com/ceph/ceph/blob/master/CONTRIBUTING.rst you are probably right closing this, but from other side I was kind of being encouraged to implement above changes by 2 people, that's why I'm a bit surprised by you closing it.

**Comment by dachary** [comment]
@stiopaa1 I should have created an issue to make sure your work is not lost in the pile of the closed pull request. Here it is http://tracker.ceph.com/issues/12961. Sorry for not doing that in the first place and thanks for your contributions :-)

**Pull request closed without merging**
