### PR TITLE
mds: wrongly treat symlink inode as normal file/dir when symlink inode is stale on kcephfs

### PR DESCRIPTION
**Pull request by david-z**
Fixes: #15702

Backport: hammer

Signed-off-by: Zhi Zhang <zhangz.david@outlook.com>

### CODE REVIEW

**Comment by david-z** [comment]
@ukernel 

Hi Yan, 

I have tested this PR on my local cluster. Could pls take a look? Thanks.

**Comment by ukernel** [comment]
I encountered the same bug a few days ago. see https://github.com/ceph/ceph/pull/8778.

**Comment by ukernel** [comment]
looks good

**Comment by gregsfortytwo** [comment]
That constituted a Reviewed-by, right @ukernel?

**Comment by ukernel** [comment]
Reviewed-by

**Pull request merged**
