### PR TITLE
osd: fix PG::all_unfound_are_queried_or_lost for non-existent osds

### PR DESCRIPTION
**Pull request by trociny**
This is #3858 rebased on master.

This is a fix for http://tracker.ceph.com/issues/10976

I'd like to have this in hammer, firefly and giant.

Signed-off-by: Mykola Golub <mgolub@mirantis.com>

### CODE REVIEW

**Comment by tchaikov** [comment]
@trociny i just asked @athanatos , he believe there are some existing test cases for this scenario in teuthology, i will try to find them. and get back to you once i have any clue. at the mean while, will test the new test case you added in `test_lost.sh`. thanks =)

**Comment by tchaikov** [comment]
@trociny i just ran the `test_lost.sh`. it works great! thank you for fixing the tests !

the test sam was talking about in http://tracker.ceph.com/issues/10976 is https://github.com/ceph/ceph-qa-suite/blob/master/tasks/lost_unfound.py . just confirmed with him over the IRC.

**Comment by trociny** [comment]
@tchaikov thanks for the info. I have never used ceph-qa-suite before. I will try to add the tests there too.

**Comment by tchaikov** [comment]
:+1:

**Pull request merged**
