### PR TITLE
Thou Shalt Not Unwind

### PR DESCRIPTION
**Pull request by adamemerson**
To make debugging easier, as discussed in the refactor call.

### CODE REVIEW

**Review by yehudasa — APPROVED** [review]
lgtm

**Comment by mattbenjamin** [comment]
thank you, gentlebeings

**Review by cbodley — APPROVED** [review]

**Comment by tchaikov** [comment]
- https://pulpito.ceph.com/kchai-2021-01-14_16:22:32-rados-wip-kefu-testing-2021-01-14-2241-distro-basic-smithi/
- https://pulpito.ceph.com/kchai-2021-01-15_15:58:16-rados-wip-kefu-testing-2021-01-15-1726-distro-basic-smithi/

**Comment by tchaikov** [comment]
jenkins test api

**Comment by cbodley** [comment]
@tchaikov would you consider those rados results successful?

@adamemerson has this run through the rgw suite?

**Comment by adamemerson** [comment]
@cbodley I have not.

**Comment by tchaikov** [comment]
@cbodley i think so. but i'd rerun the failed tests once the cephadm failures are addressed.

**Comment by harishmunjulur** [comment]
http://pulpito.front.sepia.ceph.com:80/hmunjulu-2021-01-23_01:07:59-rgw-wip-hmunjulu03-testing-2021-01-22-1346-distro-basic-smithi/

https://trello.com/c/7fdbUI5z

**Pull request merged**
