### PR TITLE
mds: ignore fs full check for CEPH_MDS_OP_SETFILELOCK

### PR DESCRIPTION
**Pull request by ukernel**
Fixes: http://tracker.ceph.com/issues/18953
Signed-off-by: "Yan, Zheng" <zyan@redhat.com>

### CODE REVIEW

**Comment by gregsfortytwo** [comment]
We should only do this if we know it won't spawn off writes, and I'm not sure that's the case. Can't the process of us trying to take locks force lock recalls and things that require journaling?

**Comment by ukernel** [comment]
filelock operations only change in-memory state. mds never journal them

**Comment by gregsfortytwo** [comment]
Yes, but acquire_locks() can twiddle lock states in ways that require journal commits. Right?

**Comment by jcsp** [comment]
This would not be the only full-permitted op that can generate journal writes -- IMO allowing this one is necessary because you could very well see application logic that wanted to acquire a lock before doing some deletions of application data.

**Pull request merged**
