### PR TITLE
mgr/dashboard: Dashboard can't handle self-signed cert on Graf…

### PR DESCRIPTION
**Pull request by votdev**
To configure SSL certificate verification use the following command:
`$ ceph dashboard set-grafana-api-ssl-verify true|false`

Fixes: https://tracker.ceph.com/issues/42445

Signed-off-by: Volker Theile <vtheile@suse.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`

</details>

### CODE REVIEW

**Comment by votdev** [comment]
jenkins test dashboard backend

**Comment by votdev** [comment]
jenkins test dashboard backend

**Comment by votdev** [comment]
jenkins test dashboard

**Comment by tchaikov** [comment]
- http://pulpito.ceph.com/kchai-2019-10-30_09:06:39-rados-wip-kefu-testing-2019-10-30-0922-distro-basic-mira/
- http://pulpito.ceph.com/kchai-2019-10-31_15:08:58-rados-wip-kefu-testing-2019-10-30-0922-distro-basic-mira/
- http://pulpito.ceph.com/kchai-2019-11-01_07:20:07-rados-wip-kefu-testing-2019-11-01-0944-distro-basic-smithi/

failures fixed by

- #30948
- #31314 
- #31315

**Comment by votdev** [comment]
jenkins test dashboard

**Comment by votdev** [comment]
jenkins test dashboard backend

**Comment by votdev** [comment]
jenkins test dashboard

**Comment by votdev** [comment]
jenkins test dashboard

**Comment by votdev** [comment]
jenkins test dashboard

**Comment by votdev** [comment]
> LGTM, thank you. Would you mind adding a note about this new setting and its function to the dashboard documentation?

You're right, i missed that.

**Comment by votdev** [comment]
jenkins test make check arm64

**Comment by votdev** [comment]
jenkins test dashboard

**Comment by votdev** [comment]
If you are using ceph-dev-docker for testing, then have a look on this: https://github.com/ricardoasmarques/ceph-dev-docker/commit/6ff131e54519ab513b9b11bc6da6838ea3cfc8bf

**Pull request merged**
