### PR TITLE
tools/osdmaptool: filter out CRUSH_ITEM_NONE to avoid segfault

### PR DESCRIPTION
**Pull request by hjwsm1989**
Signed-off-by: huangjun <huangjun@xsky.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by hjwsm1989** [comment]
@tchaikov review this please.

**Comment by tchaikov** [comment]
@hjwsm1989 could you share the backtrace of the segfault and the steps to reproduce this issue?

**Comment by hjwsm1989** [comment]
I have an erasure pool
osdmaptool osdmap.4438 --test-map-pgs-dump-all --pool 17
17.65 raw ([11,8,0], p11) up ([10,8,0], p10) acting ([10,8,0], p10)
17.66 raw ([12,15,6], p12) up ([14,15,6], p14) acting ([14,2147483647,6], p14)
*** Caught signal (Segmentation fault) **
 in thread 7f9bd6a69180 thread_name:osdmaptool
 ceph version SDS_4.2.000.0.200327-4-gc9c5a49 (c9c5a49108739a0b42d18e9a9ae7722553c8e8d0) mimic (dev)
 1: (()+0x359c4) [0x7f9bd6abf9c4]
 2: (()+0xf5d0) [0x7f9bcc6615d0]
 3: (main()+0x1701) [0x7f9bd6aa2e61]
 4: (__libc_start_main()+0xf5) [0x7f9bcb0363d5]
 5: (()+0x1d257) [0x7f9bd6aa7257]
2020-03-30 16:45:38.618 7f9bd6a69180 -1 *** Caught signal (Segmentation fault) **
 in thread 7f9bd6a69180 thread_name:osdmaptool

**Comment by tchaikov** [comment]
@hjwsm1989 i am afraid that i still cannot understand this issue or reproduce this issue with the information you provided.

**Comment by tchaikov** [comment]
@hjwsm1989 could you create a tracker ticket and upload the osdmap instead?

**Pull request closed without merging**
