### PR TITLE
qa/suites/orch: add a tests for testing public_addr for smb cluster create cmd

### PR DESCRIPTION
**Pull request by avanthakkar**
Depends on https://github.com/ceph/ceph/pull/59844/

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Comment by phlogistonjohn** [comment]
looks ok on first skim. please go ahead and test it when you can.

**Comment by avanthakkar** [comment]
jenkins test api

**Comment by avanthakkar** [comment]
jenkins test windows

**Comment by avanthakkar** [comment]
jenkins retest this please

**Comment by avanthakkar** [comment]
jenkins retest this please

**Comment by avanthakkar** [comment]
jenkins test api

**Comment by avanthakkar** [comment]
jenkins test make check

**Comment by avanthakkar** [comment]
jenkins test make check arm64

**Comment by avanthakkar** [comment]
Teuthology test run failed for `deploy_smb_mgr_clustering_ips` 
https://pulpito.ceph.com/avan-2024-10-15_08:10:28-orch:cephadm-wip-athakkar-testing-2024-10-14-2015-distro-default-smithi/7947914/

**Comment by avanthakkar** [comment]
jenkins test api

**Comment by avanthakkar** [comment]
> Teuthology test run failed for `deploy_smb_mgr_clustering_ips` https://pulpito.ceph.com/avan-2024-10-15_08:10:28-orch:cephadm-wip-athakkar-testing-2024-10-14-2015-distro-default-smithi/7947914/

Was missing `vip:` to be mentioned in yaml so it wasn't taking any valud for `VIP0`. Just fixed it & will re-run the test

**Comment by avanthakkar** [comment]
The test run failure doesn't seem to be related:
https://pulpito.ceph.com/avan-2024-10-16_17:09:59-orch:cephadm-wip-athakkar-testing-2024-10-16-1649-distro-default-smithi/

`deploy_smb_mgr_clustering_ips` failed due to a timeout, which has been observed in other tests as well.
cc @adk3798

**Comment by adk3798** [comment]
> The test run failure doesn't seem to be related: https://pulpito.ceph.com/avan-2024-10-16_17:09:59-orch:cephadm-wip-athakkar-testing-2024-10-16-1649-distro-default-smithi/
> 
> `deploy_smb_mgr_clustering_ips` failed due to a timeout, which has been observed in other tests as well. cc @adk3798

That issue is no longer present in the other ctdb tests afaik. In this run it looks like only your new test hit that timeout. All the others just hit the stray daemon warning.

**Comment by avanthakkar** [comment]
> > The test run failure doesn't seem to be related: https://pulpito.ceph.com/avan-2024-10-16_17:09:59-orch:cephadm-wip-athakkar-testing-2024-10-16-1649-distro-default-smithi/
> > `deploy_smb_mgr_clustering_ips` failed due to a timeout, which has been observed in other tests as well. cc @adk3798
> 
> That issue is no longer present in the other ctdb tests afaik. In this run it looks like only your new test hit that timeout. All the others just hit the stray daemon warning.

yes there's a timeout due to mismtaching smb service name. I've fixed it now & will re-run tests

**Comment by avanthakkar** [comment]
jenkins test make check

**Comment by avanthakkar** [comment]
jenkins test api

**Comment by avanthakkar** [comment]
Teuthology run for `deploy_smb_mgr_clustering_ips` passed: 
https://pulpito.ceph.com/avan-2024-10-25_19:30:10-orch:cephadm-wip-athakkar-testing-2024-10-25-1859-distro-default-smithi/7966982

cc @phlogistonjohn @adk3798

**Review by phlogistonjohn — APPROVED** [review]
lgtm. thanks

**Review by adk3798 — APPROVED** [review]

**Pull request merged**
