### PR TITLE
os/bluestore: get rid of fake onode nref increment for pinned entry

### PR DESCRIPTION
**Pull request by ifed01**
A follow-up of https://github.com/ceph/ceph/pull/43770, sitting on top of it.

Signed-off-by: Igor Fedotov <igor.fedotov@croit.io>

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [x] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by aclamk** [comment]
Awesome!
I was somehow pretty sure that this modification will make possible to create race condition letting us leave in incoherent pinned=true and nref=1 state.
I cannot find such scenario now.
I am happy that I was wrong.

**Review by aclamk — APPROVED** [review]

**Review by aclamk — APPROVED** [review]

**Comment by markhpc** [comment]
Adding the performance label as this touches fairly performance sensitive code (even if we don't expect it to affect performance).

**Comment by yuriw** [comment]
jenkins test api

**Comment by yuriw** [comment]
unrelated failures

Bug #53723: Cephadm agent fails to report and causes a health timeout - Orchestrator - Ceph
Bug #53499: test_dashboard_e2e.sh Failure: orchestrator/02-hosts-inventory.e2e failed. - Dashboard - Ceph
Bug #53424: CEPHADM_DAEMON_PLACE_FAIL in orch:cephadm/mgr-nfs-upgrade/ - Orchestrator - Ceph
Bug #53680: ERROR:tasks.rook:'waiting for service removal' reached maximum tries (90) after waiting for 900 seconds - Orchestrator - Ceph

**Pull request merged**
