### PR TITLE
reef: qa/standalone/osd/divergent-prior.sh: Divergent test 3 with pg_autoscale_mode on pick divergent osd

### PR DESCRIPTION
**Pull request by NitzanMordhai**
backport tracker: https://tracker.ceph.com/issues/62251

---

backport of https://github.com/ceph/ceph/pull/51909
parent tracker: https://tracker.ceph.com/issues/56034

this backport was staged using ceph-backport.sh version 16.0.0.6848
find the latest version at https://github.com/ceph/ceph/blob/main/src/script/ceph-backport.sh

### CODE REVIEW

**Comment by kamoltat** [comment]
jenkins test make check

**Comment by kamoltat** [comment]
jenkins test api

**Comment by kamoltat** [comment]
@NitzanMordhai So I think how usually format the PR description for backports is by keeping the original description and then write something like:

``Back porting relevant commits from main PR:
https://github.com/ceph/ceph/pull/51909
``

so for you, your PR description should look like:
``
When creating new pool, the current code pick the divergent osd by the first pg out of pg dump pgs, that can be in "unknown" status which means the up_primary = -1 and that will fail the test. We need to wait unitl the first pg is active+clean

Fixes: https://tracker.ceph.com/issues/56034

Back porting relevant commits from main PR:
https://github.com/ceph/ceph/pull/51909

backport tracker: https://tracker.ceph.com/issues/62251

``

**Comment by kamoltat** [comment]
hmm but i can see that you used a script for backporting so I guess you're fine

**Review by kamoltat — APPROVED** [review]
LGTM

**Comment by NitzanMordhai** [comment]
> hmm but i can see that you used a script for backporting so I guess you're fine

@kamoltat yes, i used the backport script, thanks for reviewing!

**Pull request merged**
