### PR TITLE
mimic: crushtool: add --reclassify operation to convert legacy crush maps to use device classes

### PR DESCRIPTION
**Pull request by trociny**
https://tracker.ceph.com/issues/37437

- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by yuriw** [comment]
[wip-yuri-testing-2018-12-13-1649-mimic](https://trello.com/c/sypES05t/489-wip-yuri-testing-2018-12-13-1649-mimic)

**Comment by liewegas** [comment]
This was wading pretty deeply in to teh crush code and i remember making lots of changes to get the thing working.  It cherry-picks cleanly, but a backport still makes me nervous.  Is anyone really asking for this?

Remember, you can use the master versino of crushtool to reclassify a map from a mimic or luminous cluster...

**Comment by trociny** [comment]
We already had users who wanted it and yes we helped them just using the master version. And our field engineer were glad to learn it was going to be backported. But sure if you think it is not safe let's drop it.

Note, we also have a PR for luminous #25307

**Comment by trociny** [comment]
Also note, we were more interested in backporting it to luminous.

**Comment by jdurgin** [comment]
Talking to sage, there aren't as many crush changes beyond the reweight here, so it's pretty low risk, and seems worth backporting.

**Comment by yuriw** [comment]
[wip-yuri-testing-2019-01-25-1635-mimic](https://trello.com/c/NE5iABNk/521-wip-yuri-testing-2019-01-25-1635-mimic)

**Pull request merged**
