### PR TITLE
jewel: osd: osd_scrub_during_recovery only considers primary, not replicas

### PR DESCRIPTION
**Pull request by dzafman**
http://tracker.ceph.com/issues/21117

This required multiple changes to backport to Jewel.

### CODE REVIEW

**Comment by dzafman** [comment]
@liewegas This code only comes into play if osd_scrub_during_recovery is false, but it is true by default in Jewel.  Luminous has it the other way around.  I'll run a rados suite run with this branch plus a commit to switch the value of osd_scrub_during_recovery.

**Comment by dzafman** [comment]
@liewegas @GregMeno @smithfarm We have a user that wants this Jewel pull request.  Testing in progress (5 jobs still running) 3 failures already known issues.

**Comment by dzafman** [comment]
Test run:
dzafman-2017-09-20_11:03:27-rados-wip-zafman-jewel-testing-distro-basic-smithi
1652614 filestore clone EOPNOTSUPP (not related)
1652681 BUG #19737
1652720 BUG #21063

Dead
1652624 _do_transaction() unexpected error and Thread::create() errors
1652697 _do_transaction() unexpected error EIO
1652711  _do_transaction() unexpected error EIO

**Comment by smithfarm** [comment]
@dzafman It's too late for 10.2.10 (unless this is important enough to warrant a 2nd round of QE testing?) but we could do a quick 10.2.11.

**Comment by dzafman** [comment]
@smithfarm Let's get this and ceph/ceph#17082 into the next release.

@liewegas Should we get this into quick 10.2.11 follow on?  Or just let things happen as usual?

**Comment by smithfarm** [comment]
@dzafman OK, please don't merge this (or any other Jewel PR) until 10.2.10 has been tagged.

**Comment by liewegas** [comment]
Let's just plan to merge this after .10 goes out, and carry the patch downstream if we need to until .11

**Comment by tchaikov** [comment]
http://pulpito.ceph.com/kchai-2017-10-02_07:55:29-rados-wip-kefu-testing-2017-10-02-1347-jewel-distro-basic-mira/

**Comment by dzafman** [comment]
I looked at the 14 failures and none were related to this change.  I looked at 2 of the 23 dead jobs which had no logs or cores.  One timed out in wait_for_recovery in the thrasher.  The other timed out in wait_for_all_up in the thrasher test_map_discontinuity.

**Comment by smithfarm** [comment]
@jdurgin @dzafman @tchaikov If you look at the rados runs in http://tracker.ceph.com/issues/20613 they were all reasonably clean until towards the very end of 10.2.10 preparation. At least, that was my impression.

It sure would be nice if we could get rados to run cleaner on jewel. 14 failed and 23 dead is a lot to analyze for each integration round.

**Comment by smithfarm** [comment]
For example, this run [1] was from the very last integration round before the release went into QE. That included everything up to and including "Merge pull request #17626". Here are the PRs that went in after that:

```
951609bd30 Merge pull request #18100 from ceph/wip-yuriw-fix-clients-jewel
c4aa7c3df2 Merge pull request #18044 from ceph/wip-yuriw-fix-clients-jewel
16110b985c Merge pull request #18027 from ceph/wip-yuriw-fix-clients-jewel
750e67cab8 Merge pull request #17892 from smithfarm/wip-p2p-s3-test
189f0c6f27 Merge pull request #17780 from smithfarm/wip-rh-74-jewel
0ffa38ee4d Merge pull request #16297 from smithfarm/wip-20518-jewel
94009032a8 Merge pull request #17781 from smithfarm/wip-drop-11429
d8aa3c502e Merge pull request #16473 from smithfarm/wip-20723-jewel
```

[1] http://pulpito.ceph.com/smithfarm-2017-09-12_17:11:54-rados-wip-jewel-backports-distro-basic-smithi/

**Comment by smithfarm** [comment]
Another example: the latest jewel nightly - 3 failed and 10 dead out of 107 tests

http://pulpito.ceph.com/teuthology-2017-10-07_02:00:03-rados-jewel-distro-basic-smithi/

**Comment by tchaikov** [comment]
@smithfarm thanks for point us to failed tests. the reason why i posted the test result is that i was about to schedule another PR batch for rados qa run, and the test result does not imply that the test is good enough to be a proof that we should merge the tested PRs. i just didn't get a chance to analyze the test result. actually, as you pointed out, we should not live with this without checking the failures and fixing them.

**Comment by tchaikov** [comment]
the failed tests are due to the failed disk, tracked at http://tracker.ceph.com/issues/21150

**Comment by smithfarm** [comment]
@tchaikov I wasn't worried you were going to merge on the basis of that run. My point was that the failures in the run might not be from the PRs under test, because the underlying jewel branch itself is not passing rados cleanly.

**Comment by tchaikov** [comment]
@smithfarm see http://tracker.ceph.com/issues/21150, posted https://github.com/ceph/ceph/pull/18165 to address this.

**Comment by tchaikov** [comment]
- http://pulpito.ceph.com/kchai-2017-10-02_07:55:29-rados-wip-kefu-testing-2017-10-02-1347-jewel-distro-basic-mira/
- http://pulpito.ceph.com/kchai-2017-10-08_04:22:44-rados-wip-kefu-testing-2017-10-02-1347-jewel-distro-basic-smithi/

**Comment by tchaikov** [comment]
@smithfarm i believe this batch is good to merge. the test failures are tracked by http://tracker.ceph.com/issues/21716 and http://tracker.ceph.com/issues/21150

**Comment by smithfarm** [comment]
@tchaikov I'll merge as soon as @jdurgin approves.

**Comment by smithfarm** [comment]
@tchaikov Thanks for your help!

**Comment by smithfarm** [comment]
@tchaikov By "this batch is good to merge" did you mean more PRs than just this one?

**Comment by tchaikov** [comment]
@smithfarm yes!

**Comment by smithfarm** [comment]
@tchaikov Ordinarily for jewel integration we run PRs through larger subset of the test suites, not just rados, and we require the relevant lead (or, failing that, the person who merged the corresponding master PR) to approve for merge. 

I will schedule an integration run soon. Could you go over those PRs and make sure the "jewel" milestone is set on all of them?

**Comment by tchaikov** [comment]
@smithfarm TIL. https://github.com/ceph/ceph/pulls?utf8=✓&q=is%3Apr%20is%3Aopen%20kchai-2017-10-08_04%3A22%3A44-rados-wip-kefu-testing-2017-10-02-1347-jewel-distro-basic-smithi if this is what you want me to do.

**Comment by smithfarm** [comment]
@tchaikov Thanks - I just checked them all the milestone seems to be set correctly.

**Comment by smithfarm** [comment]
Pushed integration branch at http://tracker.ceph.com/issues/21742 - once Shaman builds it, will schedule the integration tests. @tchaikov Thanks once again for your testing round and efforts to improve the rados suite experience. Much appreciated!

**Pull request merged**
