### PR TITLE
qa/cephfs: fix test_disallow_monitor_managed_snaps_for_fs_pools

### PR DESCRIPTION
**Pull request by rishabh-d-dave**
run_cluster_cmd() method is not available anymore because it was deleted
here on this PR -
https://github.com/ceph/ceph/pull/50569/files#diff-1c6c246ba42f343603d7174198dd1fb9c2654b6c883594d1a0891096b7a35875L408

Fixes: https://tracker.ceph.com/issues/62243

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Review by vshankar — APPROVED** [review]

**Comment by vshankar** [comment]
jenkins retest this please

**Comment by rishabh-d-dave** [comment]
http://pulpito.front.sepia.ceph.com/rishabh-2023-08-02_12:24:04-fs:functional-wip-rishabh-2023Aug1-testing-default-smithi/

**Comment by vshankar** [comment]
@rishabh-d-dave I guess this is ready to merge?

**Comment by rishabh-d-dave** [comment]
@vshankar Yes. This PR is ready for merge now since the test ran successfully and `test_disallow_monitor_managed_snaps_for_fs_pools` is passing now successfully -

```
2023-08-02T12:48:45.352 INFO:teuthology.orchestra.run.smithi026.stderr:2023-08-02T12:48:45.345+0000 7f9e57693640  1 -- 172.21.15.26:0/563920022 shutdown_connections
2023-08-02T12:48:45.352 INFO:teuthology.orchestra.run.smithi026.stderr:2023-08-02T12:48:45.345+0000 7f9e57693640  1 -- 172.21.15.26:0/563920022 wait complete.
2023-08-02T12:48:45.370 INFO:tasks.cephfs_test_runner:test_disallow_monitor_managed_snaps_for_fs_pools (tasks.cephfs.test_snapshots.TestMonSnapsAndFsPools) ... ok
```

**Comment by rishabh-d-dave** [comment]
Just for record: this bug fixed on this PR was introduced on PR #50569.

**Pull request merged**
