### PR TITLE
rgw/iam: correcting the result of get role policy.

### PR DESCRIPTION
**Pull request by pritha-srivastava**
Fixes: https://tracker.ceph.com/issues/45671

Signed-off-by: Pritha Srivastava <prsrivas@redhat.com>

## Checklist
- [x] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by mattbenjamin** [comment]
thanks @pritha-srivastava !

**Comment by pritha-srivastava** [comment]
http://pulpito.ceph.com/prsrivas-2020-06-18_07:04:32-rgw-wip-iam-get-role-policy-distro-basic-smithi/

**Comment by pritha-srivastava** [comment]
> http://pulpito.ceph.com/prsrivas-2020-06-18_07:04:32-rgw-wip-iam-get-role-policy-distro-basic-smithi/

Failures are:
1. Command failed on smithi089 with status 1: "cd /home/ubuntu/cephtest/keystone && source .tox/venv/bin/activate && openstack project create --os-username admin --os-password ADMIN --os-user-domain-id default --os-project-name admin --os-project-domain-id default --os-identity-api-version 3 --os-auth-url http://smithi089.front.sepia.ceph.com:35357/v3 --description 'Encryption Tenant' --domain default rgwcrypt --debug" 

2. "2020-06-18T13:56:06.193388+0000 mon.a (mon.0) 238 : cluster [WRN] Health check failed: Reduced data availability: 4 pgs inactive, 4 pgs peering (PG_AVAILABILITY)" in cluster log 

3. Command failed (workunit test rgw/test_rgw_orphan_list.sh) on smithi176 with status 12: 'mkdir -p -- /home/ubuntu/cephtest/mnt.0/client.0/tmp && cd -- /home/ubuntu/cephtest/mnt.0/client.0/tmp && CEPH_CLI_TEST_DUP_COMMAND=1 CEPH_REF=9e1ae9de9905587a227e50d0aff6533e290a8f87 TESTDIR="/home/ubuntu/cephtest" CEPH_ARGS="--cluster ceph" CEPH_ID="0" PATH=$PATH:/usr/sbin CEPH_BASE=/home/ubuntu/cephtest/clone.client.0 CEPH_ROOT=/home/ubuntu/cephtest/clone.client.0 adjust-ulimits ceph-coverage /home/ubuntu/cephtest/archive/coverage timeout 3h /home/ubuntu/cephtest/clone.client.0/qa/workunits/rgw/test_rgw_orphan_list.sh' 

The above failures are not related to changes in this PR, so @cbodley I think this is ready to be merged.

**Comment by ivancich** [comment]
Teuthology Results:
http://pulpito.ceph.com/ivancich-2020-07-09_17:27:12-rgw-wip-eric-testing-1-distro-basic-smithi/
http://pulpito.ceph.com/ivancich-2020-07-09_17:27:31-rgw-wip-eric-testing-1-distro-basic-smithi/

Re-run of Errors:
http://pulpito.ceph.com/ivancich-2020-07-09_22:59:32-rgw-wip-eric-testing-1-distro-basic-smithi/

**Pull request merged**
