### PR TITLE
Fix graph

### PR DESCRIPTION
**Pull request by Fale**
doc: fix the architecture diagram in cephfs.rst

### CODE REVIEW

**Comment by theanalyst** [comment]
Could you add signed-off-by line as mentioned in https://github.com/ceph/ceph/blob/master/SubmittingPatches

**Comment by Fale** [comment]
@theanalyst thanks, fixed :)

**Comment by tchaikov** [comment]
thanks @Fale ! could you update commit log to explain the area you changed, it would help other developers to understand what this change is for. the `Fix graph` does help, but in my case, i can hardly understand what this change fixes until i look at the patch itself. i'd suggest something like this
```
doc: fix the architecture diagram in cephfs.rst
```

what do you think?

**Comment by Fale** [comment]
Thanks for the feedback, @tchaikov, fixed :)

**Pull request merged**
