### PR TITLE
nautilus: mgr/dashboard: install teuthology using pip

### PR DESCRIPTION
**Pull request by smithfarm**
NOTE: the purpose of this PR is to fix https://tracker.ceph.com/issues/45636

backport tracker: https://tracker.ceph.com/issues/45637

---

backport of https://github.com/ceph/ceph/pull/31815
parent tracker: https://tracker.ceph.com/issues/42969

this backport was staged using ceph-backport.sh version 15.1.1.389
find the latest version at https://github.com/ceph/ceph/blob/master/src/script/ceph-backport.sh

### CODE REVIEW

**Comment by alfonsomthd** [comment]
jenkins test dashboard backend

**Comment by smithfarm** [comment]
jenkins test dashboard backend

**Comment by smithfarm** [comment]
This fixes the issue for me. Flagging for integration testing.

**Comment by yuriw** [comment]
[wip-yuri-testing-2020-05-27-1545-nautilus](https://trello.com/c/THUxTWlZ/916-wip-yuri-testing-2020-05-27-1545-nautilus)

**Pull request merged**
