### PR TITLE
rgw/s3select: s3select response handler refactor

### PR DESCRIPTION
**Pull request by galsalomon66**
-- refactor of s3select response handler
-- adding continuation-response to parquet flow (with very big Parquet it causes a Timeout)
-- refactor of error response

https://bugzilla.redhat.com/show_bug.cgi?id=2242924
https://bugzilla.redhat.com/show_bug.cgi?id=2254582

https://github.com/ceph/s3select/pull/152
https://github.com/ceph/s3select/pull/153

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [x] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Comment by galsalomon66** [comment]
https://pulpito.ceph.com/gsalomon-2024-03-21_04:42:08-rgw-long_processing_timeout-distro-default-smithi/
32 success 
41 failed -- not related to changes

**Comment by galsalomon66** [comment]
https://pulpito.ceph.com/gsalomon-2024-03-21_14:16:34-rgw:verify-long_processing_timeout-distro-default-smithi/
all green

**Comment by galsalomon66** [comment]
https://pulpito.ceph.com/gsalomon-2024-03-25_16:22:20-rgw:verify-long_processing_timeout-distro-default-smithi/#
all green

**Comment by galsalomon66** [comment]
https://pulpito.ceph.com/gsalomon-2024-03-27_14:25:58-rgw:verify-long_processing_timeout-distro-default-smithi/
all green

**Comment by galsalomon66** [comment]
https://pulpito.ceph.com/gsalomon-2024-03-27_16:42:46-rgw-long_processing_timeout-distro-default-smithi/
69 passed
4 failures - not related to PR changes

**Comment by galsalomon66** [comment]
jenkins test make check

**Comment by galsalomon66** [comment]
jenkins test api

**Comment by galsalomon66** [comment]
jenkins test windows

**Comment by galsalomon66** [comment]
jenkins test docs

**Comment by galsalomon66** [comment]
jenkins test windows

**Comment by galsalomon66** [comment]
jenkins test make check

**Comment by cbodley** [comment]
please squash commits

**Comment by cbodley** [comment]
if this needs backports, please create a tracker issue for them

**Comment by cbodley** [comment]
>src/test/cli/crushtool/set-choose.t: failed
The following tests FAILED:
	 35 - run-cli-tests (Failed)

**Comment by cbodley** [comment]
jenkins test make check

**Comment by cbodley** [comment]
> ERROR: setUpClass (tasks.mgr.dashboard.test_health.HealthTest)

tracked in https://tracker.ceph.com/issues/47612

**Comment by galsalomon66** [comment]
> > ERROR: setUpClass (tasks.mgr.dashboard.test_health.HealthTest)
> 
> tracked in https://tracker.ceph.com/issues/47612

@cbodley 
looks like a wrong comment

**Comment by galsalomon66** [comment]
jenkins test make check

**Comment by galsalomon66** [comment]
jenkins test make check

**Comment by galsalomon66** [comment]
jenkins test make check

**Comment by mkogan1** [comment]
jenkins test make check

**Comment by cbodley** [comment]
@galsalomon66 can you please create a tracker issue for backports and link it here?

**Comment by galsalomon66** [comment]
@cbodley 
https://tracker.ceph.com/issues/65243
(2 PR's , reef , squid)

**Pull request merged**
