### PR TITLE
tests: cleanup: drop calamari tasks

### PR DESCRIPTION
**Pull request by smithfarm**
qa/tasks/calamari_nosetests.py and qa/tasks/calamari_setup.py are not used by
any of the current suites.

Signed-off-by: Nathan Cutler <ncutler@suse.com>

### CODE REVIEW

**Comment by tchaikov** [comment]
@GregMeno ping?

**Comment by tchaikov** [comment]
@GregMeno ping?

**Comment by smithfarm** [comment]
Any chance of a review on this one? I'll put it through a rados suite in the meantime.

**Comment by smithfarm** [comment]
**running** http://pulpito.ceph.com/smithfarm-2018-04-06_08:00:20-rados-wip-smithfarm-testing-distro-basic-smithi/

**Pull request merged**
