### PR TITLE
luminous: qa: ceph-volume updates

### PR DESCRIPTION
**Pull request by vasukulkarni**
ceph-volume updates and additional tests for ceph-volume

### CODE REVIEW

**Comment by vasukulkarni** [comment]
@yuriw want to test and merge this one please?

**Comment by yuriw** [comment]
http://pulpito.ceph.com/teuthology-2018-01-08_18:03:00-ceph-deploy-luminous-distro-basic-vps/

@vasukulkarni we have 52 jobs now!  was it intentional ?

**Comment by yuriw** [comment]
@vasukulkarni see http://pulpito.ceph.com/teuthology-2018-01-08_18:03:00-ceph-deploy-luminous-distro-basic-vps/
still seems like the same issue.

**Comment by vasukulkarni** [comment]
Running ceph-volume tests, since your branch doesn't include the commits i pushed http://pulpito.ceph.com/vasu-2018-01-17_23:15:40-ceph-deploy-luminous-distro-basic-vps/

**Comment by yuriw** [comment]
[wip-yuri-testing-2018-02-01-2124-luminous](https://trello.com/c/QG0P9o8J/254-wip-yuri-testing-2018-02-01-2124-luminous)

**Pull request merged**
