### PR TITLE
qa/suites/upgrade: ignore PG_AVAILABILITY and MON_DOWN for quincy-x and reef-x upgrade suites

### PR DESCRIPTION
**Pull request by ljflores**
These warnings are expected since we restart daemons during upgrades, which means that mons are temporarily down, and pgs temporarily lose availability.

Fixes: https://tracker.ceph.com/issues/66809 and https://tracker.ceph.com/issues/64460

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [x] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Comment by ljflores** [comment]
jenkins test windows

**Comment by ljflores** [comment]
jenkins test api

**Comment by ljflores** [comment]
jenkins test windows

**Review by rzarzynski — APPROVED** [review]
LGTM with a nit: the second commit has a malformed `Fixes` tag:

```
Fixes: tracker.ceph.com/issues/64460
```

**Comment by ljflores** [comment]
Merging based on results from: https://pulpito.ceph.com/yuriw-2024-07-20_13:42:49-upgrade-wip-yuri2-testing-2024-07-19-0817-distro-default-smithi/

**Comment by ljflores** [comment]
jenkins test windows

**Comment by ljflores** [comment]
Will resolve conflicts..

**Comment by NitzanMordhai** [comment]
Rados approved: https://tracker.ceph.com/projects/rados/wiki/MAIN#httpstrackercephcomissues67027

**Comment by yuriw** [comment]
@ljflores pls rebase and merge
ref: https://tracker.ceph.com/issues/67027

**Comment by ljflores** [comment]
jenkins test api

**Pull request merged**
