### PR TITLE
ceph-volume: Also consider zfs filesystems

### PR DESCRIPTION
**Pull request by sirtoobii**
This PR resolves the issue described here: https://bugs.launchpad.net/ubuntu/+source/zfs-linux/+bug/1881747

Please let me know if there are further steps needed (especially when it comes to testing)

Fixes: https://tracker.ceph.com/issues/55496

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [x] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by sirtoobii** [comment]
@asm0deuz Is there something missing here?

**Comment by guits** [comment]
jenkins test ceph-volume all

**Comment by guits** [comment]
jenkins test ceph-volume tox

**Review by guits — APPROVED** [review]

**Comment by CartCaved** [comment]
@sirtoobii Did you ever learn why this PR got stuck?

**Comment by sirtoobii** [comment]
@CartCaved because this test failed: https://github.com/ceph/ceph/blob/5515138425f6777f89bfe19044c40a5e8804a443/src/ceph-volume/ceph_volume/tests/util/test_disk.py#L509 And since ceph is such a large and complex software project I wanted to test first if this failure is actually related to my changes. But as you can see, not much is going on from the maintainers side. At the end of the [original bug](https://bugs.launchpad.net/ubuntu/+source/zfs-linux/+bug/1881747) report I've added a script to create a patched ceph image

**Comment by sirtoobii** [comment]
@guits @pjjw @carletes Is there anything missing here?

**Pull request closed without merging**
