### PR TITLE
reef: mgr/cephadm: add some NVMEof gateway fields to be configurable by cephadm

### PR DESCRIPTION
**Pull request by adk3798**
backport tracker: https://tracker.ceph.com/issues/65125

---

backport of https://github.com/ceph/ceph/pull/56369
parent tracker: https://tracker.ceph.com/issues/64821

this backport was staged using ceph-backport.sh version 16.0.0.6848
find the latest version at https://github.com/ceph/ceph/blob/main/src/script/ceph-backport.sh

### CODE REVIEW

**Review by phlogistonjohn — APPROVED** [review]

**Comment by adk3798** [comment]
jenkins test make check

**Comment by adk3798** [comment]
jenkins test api

**Comment by VallariAg** [comment]
Hello, @adk3798! Looks like this backport PR was never merged to reef branch. It's merged in main and squid.
Noticed an issue in reef's upgrade because of these missing commits. Please see if it's okay to merge now.

**Review by baum — APPROVED** [review]
lgtm 🖖

**Comment by adk3798** [comment]
jenkins test make check

**Pull request closed without merging**
