### PR TITLE
mgr/cephadm: Fix `orch apply service iscsi`

### PR DESCRIPTION
**Pull request by sebastian-philipp**
## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by sebastian-philipp** [comment]
cc @matthewoliver

**Comment by ricardoasmarques** [comment]
Looks like this PR is fixing https://tracker.ceph.com/issues/45249. If yes, can you add the `Fixes: https://tracker.ceph.com/issues/45249` to the commit message?

**Comment by sebastian-philipp** [comment]
> Looks like this PR is fixing https://tracker.ceph.com/issues/45249. If yes, can you add the `Fixes: https://tracker.ceph.com/issues/45249` to the commit message?

@mgfritch would like to replace this with a slightly better PR

**Comment by sebastian-philipp** [comment]
QA run successful:

* http://pulpito.ceph.com/swagner-2020-04-24_09:32:08-rados-wip-swagner-testing-2020-04-23-1304-distro-basic-smithi/

Failure: https://tracker.ceph.com/issues/45194

**Comment by mgfritch** [comment]
> > Looks like this PR is fixing https://tracker.ceph.com/issues/45249. If yes, can you add the `Fixes: https://tracker.ceph.com/issues/45249` to the commit message?
> 
> @mgfritch would like to replace this with a slightly better PR

https://github.com/ceph/ceph/pull/34814

**Pull request closed without merging**
