### PR TITLE
rgw/multisite: fix bucket shard state init function

### PR DESCRIPTION
**Pull request by yuvalif**
* make sure src/dest shard ids are the same in sync pair
* copy sync pair by value in coroutine loop

Signed-off-by: Yuval Lifshitz <ylifshit@redhat.com>

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by yuvalif** [comment]
when multisite test suite running locally, the following tests fail:
* `test_bucket_sync_disable` - expected since disable/enable is not implemented yet
* `test_bucket_sync_disable_enable` - expected since disable/enable is not implemented yet
* `test_bucket_sync_enable_right_after_disable` - expected since disable/enable is not implemented yet
* `test_zg_master_zone_delete` - @cbodley is this expected?

**Comment by yuvalif** [comment]
@cbodley is [this](https://github.com/ceph/ceph/pull/41337/files#diff-a54fef5ff241c02e9e08a5236595b6e357758b26d01308903baf4df1ceab62e4L2999) a similar issue that needs to be fixed as well?

**Review by cbodley — APPROVED** [review]

**Comment by cbodley** [comment]
> @cbodley is [this](https://github.com/ceph/ceph/pull/41337/files#diff-a54fef5ff241c02e9e08a5236595b6e357758b26d01308903baf4df1ceab62e4L2999) a similar issue that needs to be fixed as well?

it looks like `CheckAllBucketShardStatusIsIncremental` is passing that reference through to the `RGWReadBucketPipeSyncStatusCoroutine` ctor, which uses it in `RGWBucketPipeSyncStatusManager::inc_status_oid()` to generate the object name. it's not storing the reference, so i think it's okay

**Comment by yuvalif** [comment]
> > @cbodley is [this](https://github.com/ceph/ceph/pull/41337/files#diff-a54fef5ff241c02e9e08a5236595b6e357758b26d01308903baf4df1ceab62e4L2999) a similar issue that needs to be fixed as well?
> 
> it looks like `CheckAllBucketShardStatusIsIncremental` is passing that reference through to the `RGWReadBucketPipeSyncStatusCoroutine` ctor, which uses it in `RGWBucketPipeSyncStatusManager::inc_status_oid()` to generate the object name. it's not storing the reference, so i think it's okay

the question was not on storing the name. it was in incrementing the shard id for source and dest in line 2999:
```
sync_pair.dest_bs.shard_id = shard++;
```

**Comment by cbodley** [comment]
okay yeah, that's probably broken too

**Comment by cbodley** [comment]
thanks! i added that fix too, and merged your commit into merged into wip-rgw-multisite-reshard

**Comment by yuvalif** [comment]
> thanks! i added that fix too, and merged your commit into merged into wip-rgw-multisite-reshard

thanks @cbodley !

**Pull request closed without merging**
