### PR TITLE
mimic: core: mon,osd: limit MOSDMap messages by size as well as map count

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/38277

### CODE REVIEW

**Comment by smithfarm** [comment]
```
In file included from /home/jenkins-build/build/workspace/ceph-pull-requests/src/common/dout.h:22:0,
                 from /home/jenkins-build/build/workspace/ceph-pull-requests/src/common/debug.h:18,
                 from /home/jenkins-build/build/workspace/ceph-pull-requests/src/compressor/Compressor.cc:24:
/home/jenkins-build/build/workspace/ceph-pull-requests/src/common/legacy_config_opts.h:607:8: error: 'osd_map_message_max_bytes' has not been declared
 OPTION(osd_map_message_max_bytes, OPT_SIZE)  // max maps per MOSDMap message
        ^
/home/jenkins-build/build/workspace/ceph-pull-requests/src/common/config.h:362:17: note: in definition of macro 'OPTION'
     OPTION_##ty(name)
                 ^~~~
/home/jenkins-build/build/workspace/ceph-pull-requests/src/common/config.h:362:21: error: ISO C++ forbids declaration of 'OPTION_OPT_SIZE' with no type [-fpermissive]
     OPTION_##ty(name)
                     ^
/home/jenkins-build/build/workspace/ceph-pull-requests/src/common/legacy_config_opts.h:607:1: note: in expansion of macro 'OPTION'
 OPTION(osd_map_message_max_bytes, OPT_SIZE)  // max maps per MOSDMap message
 ^
/home/jenkins-build/build/workspace/ceph-pull-requests/src/common/config.h:362:21: error: expected ';' at end of member declaration
     OPTION_##ty(name)
                     ^
/home/jenkins-build/build/workspace/ceph-pull-requests/src/common/legacy_config_opts.h:607:1: note: in expansion of macro 'OPTION'
 OPTION(osd_map_message_max_bytes, OPT_SIZE)  // max maps per MOSDMap message
 ^
src/compressor/CMakeFiles/compressor_objs.dir/build.make:62: recipe for target 'src/compressor/CMakeFiles/compressor_objs.dir/Compressor.cc.o' failed
make[3]: *** [src/compressor/CMakeFiles/compressor_objs.dir/Compressor.cc.o] Error 1
```

**Comment by smithfarm** [comment]
```
/home/jenkins-build/build/workspace/ceph-pull-requests/src/mon/OSDMonitor.cc: In member function 'virtual void OSDMonitor::encode_pending(MonitorDBStore::TransactionRef)':
/home/jenkins-build/build/workspace/ceph-pull-requests/src/mon/OSDMonitor.cc:1071:31: warning: comparison of integer expressions of different signedness: 'std::vector<pg_t>::size_type' {aka 'long unsigned int'} and 'int64_t' {aka 'long int'} [-Wsign-compare]
       if (pgs_to_check.size() < g_conf->mon_clean_pg_upmaps_per_chunk * 2) {
           ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/jenkins-build/build/workspace/ceph-pull-requests/src/mon/OSDMonitor.cc: In member function 'bool OSDMonitor::preprocess_get_osdmap(MonOpRequestRef)':
/home/jenkins-build/build/workspace/ceph-pull-requests/src/mon/OSDMonitor.cc:2166:30: error: 'g_conf' cannot be used as a function
   ssize_t max_bytes = g_conf()->osd_map_message_max_bytes;
                              ^
src/mon/CMakeFiles/mon.dir/build.make:182: recipe for target 'src/mon/CMakeFiles/mon.dir/OSDMonitor.cc.o' failed
make[3]: *** [src/mon/CMakeFiles/mon.dir/OSDMonitor.cc.o] Error 1
```

**Comment by smithfarm** [comment]
```
157/157 Test   #3: test_objectstore_memstore.sh ............***Timeout 3600.01 sec
```

**Comment by smithfarm** [comment]
jenkins test make check

**Comment by yuriw** [comment]
[wip-yuri4-testing-2019-08-05-2052-mimic](https://trello.com/c/negGiBj1/685-wip-yuri4-testing-2019-08-05-2052-mimic)

**Pull request merged**
