### PR TITLE
Mutex Assert from PipeConnection::try_get_pipe

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/12838

### CODE REVIEW

**Comment by dachary** [comment]
@athanatos  does this backport look good to merge ? It passed a run of the firefly rados suite ( see http://tracker.ceph.com/issues/11644#note-110 ). Note that there was a valgrind issues but it is unrelated and fixed by https://github.com/ceph/ceph/pull/6325.

**Comment by athanatos** [comment]
I'll run this one by david since there was a conflict.

**Comment by dachary** [comment]
@athanatos ok ! @dzafman what do you think ?

**Comment by dzafman** [comment]
:+1: The different function names actually identical.

**Pull request merged**
