### PR TITLE
mimic: ceph-volume: add raw mode

### PR DESCRIPTION
**Pull request by jan--f**
Backport of #32095

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by jan--f** [comment]
jenkins test ceph-volume tox

**Comment by liewegas** [comment]
the c-v tox test failed with a bunch of errors.... ?

**Comment by jan--f** [comment]
> the c-v tox test failed with a bunch of errors.... ?

Yep there was a follow up PR to fix those. I'll pull this in here.

**Comment by jan--f** [comment]
jenkins test ceph-volume tox

**Comment by jan--f** [comment]
Includes backports for #32655 and  #33074

**Comment by jan--f** [comment]
Tox is actually green, this is a false positive.

**Pull request merged**
