### PR TITLE
os/bluestore: default cache size of 3gb

### PR DESCRIPTION
**Pull request by liewegas**
Signed-off-by: Sage Weil <sage@redhat.com>

### CODE REVIEW

**Comment by yuyuyu101** [comment]
hmm, it will increase each osd recommend memory size to 5GB(consider recovery and burst io)....

**Comment by liewegas** [comment]
Yeah.  The idea is that bluestore OSDs are newly deployed or converted OSDs, so it is a "safe" opportunity to have a new default.  And that 5gb is more in line with what is deployed in the real world. Also, performance improves pretty dramatically going from 1gb -> 2 or 3gb.

**Comment by xiexingguo** [comment]
I've got the same concern as @yuyuyu101.
3GB is a little bit aggressive and it would be better to keep the current conservative but *safe* default.
Anyway,  this is configurable  and user can re-config if they'd love to.

**Comment by liewegas** [comment]
How much physical memory do you deploy for each OSD?

What value would you recommend?

**Comment by xiexingguo** [comment]
> How much physical memory do you deploy for each OSD?

That depends. We usually deploy ceph on hosts with 48GB/64GB/128GB ram, and each of them may host up to 12 OSDs.



> What value would you recommend?

1GB would be the preferred option, IMO.

**Comment by yuyuyu101** [comment]
depends on disk type. user could adopt large memory size for ssd, small memory size for hdd... so 2-3gb per hdd(4tb) should be fine, 4-5gb per ssd just ok

**Comment by markhpc** [comment]
FWIW, I think we need to fix the memory leak Igor found and see how much memory we end up using after that.  I'd be in favor of a larger cache size (3GB) for NVMe by default and a smaller cache size (1GB) for HDD.  

Especially for configurations where data is on HDD and the DB partition is placed on flash (big enough to hold all onode/extent metadata), I'm not sure how much a large onode cache in bluestore actually matters.  The large flash based DB partition is probably more important.  FWIW it looks like an 8GB DB partition is enough to hold metadata for ~600K objects with min_alloc set to 64k (default for HDD).  

When everything is on NVMe, the onode cache is very important to achieve high IOPS rates.  That's where I think we really want to encourage (perhaps demand) that users allocate plenty of RAM for onode cache.  This may matter less if DB/WAL partitions are on even faster storage technologies (nvdimm, optane, etc).

**Comment by fiskn** [comment]
Currently run between 2-4GB per OSD on current nodes with Filestore (12 disks per node). The difference in cost between 32-64GB of ram per host is not that great and in that price range, performance would be preferable.

**Comment by liewegas** [comment]
http://pulpito.ceph.com/sage-2017-06-28_18:24:01-rados-wip-sage-testing-distro-basic-smithi/

**Comment by liewegas** [comment]
Merging this for now; we can still adjust up/down as we go forward!

**Pull request merged**
