### PR TITLE
jewel: rpm: ceph installs stuff in %_udevrulesdir but does not own that directory

### PR DESCRIPTION
**Pull request by dachary**
http://tracker.ceph.com/issues/17095

### CODE REVIEW

**Comment by smithfarm** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;aWtWpt7W&#x2F;1865-rpm-add-udev-buildrequires-to-provide-usr-lib-udev-directory"> rpm: add udev BuildRequires to provide &#x2F;usr&#x2F;lib&#x2F;udev directory</a>

**Comment by smithfarm** [comment]
@dachary Could this be merged for 10.2.4 ?

**Comment by dachary** [comment]
@smithfarm it needs testing: will run that this week.

**Comment by dachary** [comment]
Pass hammer-x & jewel-x upgrade suites http://tracker.ceph.com/issues/17487#note-15

**Pull request merged**
