### PR TITLE
octopus: mgr/dashboard: NoRebalance flag is added to the Dashboard

### PR DESCRIPTION
**Pull request by nizamial09**
backport tracker: https://tracker.ceph.com/issues/44583

## Checklist
- [x] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by smithfarm** [comment]
The commit message is missing `(cherry picked from commit ...)`

**Comment by nizamial09** [comment]
> The commit message is missing `(cherry picked from commit ...)`

Fixed, thanks

**Comment by nizamial09** [comment]
> Instead of backporting, this could have been merged to `octopus` first. Then it would have gotten pushed to `master` as well. However, since it was merged to `master` first, AFAICT it has to be cherry-picked to `octopus`, which is what I suppose this PR is doing ;-)
> 
> Please re-do with `git cherry-pick -x` to get the `(cherry picked from commit ...)` line. That will make it explicit.
> 
> More information about backporting is available at https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst

Yes. I cherry-picked this from my original commit. I don't know why its not showing in the commit message. Anyways I added it, thanks for the clarification. :)

**Comment by smithfarm** [comment]
Please note: octopus is not released yet, so backporting has not started.

In other words, merging can proceed according to the dashboard team's protocols for PRs targeting master.

**Comment by nizamial09** [comment]
@smithfarm Sorry. I think I did the `cherry-pick` without the `-x`. 
And yes there was a script file with which I used to create a backport for nautilus. But for octopus there was some error occurred that prevented me from doing it. So I just went ahead and manually done it.

**Comment by nizamial09** [comment]
> Please note: octopus is not released yet, so backporting has not started.
> 
> In other words, merging can proceed according to the dashboard team's protocols for PRs targeting master.

Sounds good to me :)

**Pull request merged**
