### PR TITLE
quincy: MClientRequest: properly handle ceph_mds_request_head_legacy for ext_num_retry, ext_num_fwd, owner_uid, owner_gid

### PR DESCRIPTION
**Pull request by mihalicyn**
This PR also restores another backport https://github.com/ceph/ceph/pull/53139 because it was reverted https://github.com/ceph/ceph/pull/54108

backport tracker: https://tracker.ceph.com/issues/63477

---

backport of https://github.com/ceph/ceph/pull/54149
parent tracker: https://tracker.ceph.com/issues/63288

### CODE REVIEW

**Comment by mihalicyn** [comment]
cc @vshankar

**Comment by mihalicyn** [comment]
jenkins test make check

**Comment by mihalicyn** [comment]
jenkins test make check

**Comment by mihalicyn** [comment]
cc @rishabh-d-dave @lxbsz

**Review by vshankar — APPROVED** [review]

**Review by mchangir — APPROVED** [review]
LGTM

https://pulpito.ceph.com/yuriw-2024-01-10_16:13:48-fs-wip-yuri6-testing-2024-01-05-0744-quincy-distro-default-smithi/

**Pull request merged**
