### PR TITLE
rgw: adjust the request_uri to support absoluteURI of http request

### PR DESCRIPTION
**Pull request by vmcloud**
http://tracker.ceph.com/issues/12917 Fixes: #12917

Signed-off-by: Wenjun Huang <wenjunhuang@tencent.com>

Continuously discuss for the original pull request https://github.com/ceph/ceph/pull/5774

### CODE REVIEW

**Comment by mattbenjamin** [comment]
My updated comment is, it would be useful to describe in the commit msg or source how the need for this arises, and what a candidate URL being transformed is.  Thanks!

**Comment by vmcloud** [comment]
The originated cause for this issue described in the tracker http://tracker.ceph.com/issues/12917. Refer to https://github.com/aws/aws-sdk-go/issues/344, you can find the example. And for the absoluteURI scenario, the variables reaching RGW are as below:
`request_uri = http://bucket.s3.amazonaws.com/path/to/file.jpg`
The RGW can not deal with the request_uri, because it want it as **/path/to/file.jpg**. So we should do a transformation for it.

**Comment by yehudasa** [comment]
@vmcloud can you modify the commit description to include your last comment?

**Comment by vmcloud** [comment]
Hi @yehudasa, I have updated the commit description, thanks!

**Comment by mattbenjamin** [comment]
This passed my S3 smoke tests

**Comment by tdsparrow** [comment]
I tested jewel containing this PR with example  listObject.go from aws-sdk-go. This client sent absolute URI in HTTP Header and  it still hit issue http://tracker.ceph.com/issues/12917

This PR only affect code since civetweb_callback, however process_new_connection in civetweb still check uri and failed on absolute uri. Backtrace should looks like 

```
(gdb) bt
#0  civetweb_callback (conn=0x7fdd4003f6c0) at rgw/rgw_civetweb_frontend.cc:8
#1  0x00007fdd691952ef in handle_request (conn=conn@entry=0x7fdd4003f6c0) at civetweb/src/civetweb.c:5795
#2  0x00007fdd691972d8 in process_new_connection (conn=0x7fdd4003f6c0) at civetweb/src/civetweb.c:6576
#3  worker_thread_run (thread_func_param=0x7fdd6992b2e0) at civetweb/src/civetweb.c:6684
#4  worker_thread (thread_func_param=0x7fdd6992b2e0) at civetweb/src/civetweb.c:6719
#5  0x00007fdd5ec8cdf5 in start_thread () from /lib64/libpthread.so.0
#6  0x00007fdd5e2991ad in clone () from /lib64/libc.so.6

```

We'd still need fix from civetweb: https://github.com/civetweb/civetweb/issues/197

**Comment by solaiperi** [comment]
I was trying to use AWS Go SDK against Ceph (in a version where this fix is already there) and still this is not working.

**Pull request merged**
