### PR TITLE
mgr/dashboard: Localization for date picker module

### PR DESCRIPTION
**Pull request by Devp00l**
Fixes: https://tracker.ceph.com/issues/39037
Signed-off-by: Stephan Müller <smueller@suse.com>

- [x] References tracker ticket
- [ ] Updates documentation if necessary
- [x] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by LenzGr** [comment]
@Devp00l thank you! Per our IRC conversation: please update `HACKING.rst` to point out which files need to be updated when new languages are added.

**Comment by Devp00l** [comment]
@LenzGr done

**Comment by Devp00l** [comment]
jenkins test dashboard

**Comment by Devp00l** [comment]
jenkins test dashboard

**Comment by LenzGr** [comment]
jenkins test dashboard

**Comment by LenzGr** [comment]
@Devp00l can you please double check that your PR still covers all available languages at the moment?

**Comment by Devp00l** [comment]
@LenzGr If you are referring that English is not listed, is easy to explain as English is the default and doesn't need to be loaded and set explicitly.

All languages are defined - we can merge this PR.

**Pull request merged**
