### PR TITLE
luminous: cephfs: "ceph tell mds" commands result in "File exists" errors on client admin socket

### PR DESCRIPTION
**Pull request by shinobu-x**
http://tracker.ceph.com/issues/22076
http://tracker.ceph.com/issues/22078

### CODE REVIEW

**Comment by joscollin** [comment]
@smithfarm Please merge.

**Comment by smithfarm** [comment]
@joscollin It will be merged after it goes through integration testing and gets approved by a lead.

**Comment by joscollin** [comment]
@smithfarm ok. Anyway, I have tested it before approving and it works in Luminous.

**Comment by yuriw** [comment]
[cephfs => wip-yuri3-testing-2018-01-24-1514-luminous](https://trello.com/c/QWO1XUPz/241-cephfs-wip-yuri3-testing-2018-01-24-1514-luminous)

**Pull request merged**
