### PR TITLE
mgr/mgr_util: fixing some tox issues

### PR DESCRIPTION
**Pull request by rkachach**
Environment: 

- Python 3.10.6
- tox 4.2.1

This PR fixes the following tox reported issues:

```
mypy: commands[0] cephadm> mypy --config-file=../../mypy.ini -m alerts -m balancer -m cephadm -m crash -m dashboard -m devicehealth -m diskprediction_local -m hello -m influx -m iostat -m localpool -m mds_autoscaler -m mgr_module -m mgr_util -m mirroring -m nfs -m orchestrator -m pg_autoscaler -m progress -m prometheus -m rbd_support -m rook -m snap_schedule -m selftest -m stats -m status -m telegraf -m telemetry -m test_orchestrator -m volumes -m zabbix
mgr_util.py: note: In function "verify_cacrt_content":
mgr_util.py:578: error: Argument 2 to "load_certificate" has incompatible type "str"; expected "bytes"
mgr_util.py:581: error: Item "None" of "Optional[bytes]" has no attribute "decode"
mgr_util.py: note: In function "get_cert_issuer_info":
mgr_util.py:611: error: Argument 2 to "load_certificate" has incompatible type "str"; expected "bytes"
mgr_util.py: note: In function "verify_tls":
mgr_util.py:634: error: Argument 2 to "load_certificate" has incompatible type "str"; expected "bytes"

```

Fixes: https://tracker.ceph.com/issues/58378
Signed-off-by: Redouane Kachach <rkachach@redhat.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [x] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [x] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by phlogistonjohn** [comment]
I can't seem to find any documentation for the `modules` parameter. Is this some "hidden" / deprecated syntax?  I looked in both the 4.x and 3.x docs. Maybe I'm overlooking something obvious though. Can you find anything documenting the expected use of this parameter?

**Comment by phlogistonjohn** [comment]
> > I can't seem to find any documentation for the `modules` parameter. Is this some "hidden" / deprecated syntax? I looked in both the 4.x and 3.x docs. Maybe I'm overlooking something obvious though. Can you find anything documenting the expected use of this parameter?
> 
> I'm a little bit lost here (sorry for that!) . Please, can you explain a little bit more to what `modules` do you refer.
> 
> Is it part of the changes I introduced?

I re-read the existing file much more slowly and did I now realize that `modules` is not part of the expected format of tox ini, but is ignored by tox. The parameter that you changed from ending with just a newline to backslash (\) newline all roll up to a variable named `modules`. I thought this was a tox parameter but rather, the following lines that invoke flake8 use a generic parameter replacement mechanism (flattened to one line): `flake8 --config=tox.ini {posargs} {posargs:{[testenv:flake8]modules}}`

The part `{[testenv:flake8]modules}` is the only thing that "knows about" the modules variable. Annoyingly I still cant find proper clear docs (especially in the newest version of the doc) on the rules around variable replacement in tox. But I'm happy to understand how it is working in practice.

Therefore you can ignore my request because this use of variable substitution was already in the existing code. I now understand it even if I don't like it much (and am unclear it works correctly if you do have posargs.... but that's not your problem :-) )

**Review by phlogistonjohn — APPROVED** [review]

**Review by adk3798 — APPROVED** [review]
LGTM

**Comment by adk3798** [comment]
https://pulpito.ceph.com/adking-2023-01-12_12:11:23-orch:cephadm-wip-adk-testing-2023-01-11-2322-distro-default-smithi/

Quite a few failures, but I think I've pinned all of them down to either a known issue or a failure caused by a specific PR in the run. That being said, we should be able to merge the PRs that are not the two causing the failures or related to cephadm upgrade or ingress service, since those tests were affected by the failures.

11 failed jobs

-  4 mds upgrade sequence jobs failing with `timeout expired in wait_until_healthy`. This was caused by an issue in the prometheus module that, at the time of testing, existed in the latest pacific devel container builds (which those tests use as an upgrade start point). Issue should go away with next pacific devel container build as the fix was merged in pacific already.
- 3 test_nfs task failures `Test failure: test_non_existent_cluster (tasks.cephfs.test_nfs.TestNFS)`. This was caused by one of the PRs in the run adjusting the return code of an nfs module function (not this PR though).
- 2 failed staggered upgrade tests. From what I can tell, the staggered upgrade actually went fine. For whatever reason `ceph versions` json output didn't contain an OSD index with the versions of the OSDs that the test checks.  I ran two instances of the test on main branch and the issue reproduced https://pulpito.ceph.com/adking-2023-01-13_05:56:45-orch:cephadm-main-distro-default-smithi/ 
```
{
    "mon": {
        "ceph version 18.0.0-1762-gcb17f286 (cb17f286272f7ae9dbdf8117ca7b077b0a5cf650) reef (dev)": 3
    },
    "rgw": {
        "ceph version 16.2.0 (0c2054e95bcd9b30fdd908a79ac1d8bbc3394442) pacific (stable)": 2
    },
    "overall": {
        "ceph version 16.2.0 (0c2054e95bcd9b30fdd908a79ac1d8bbc3394442) pacific (stable)": 2,
        "ceph version 18.0.0-1762-gcb17f286 (cb17f286272f7ae9dbdf8117ca7b077b0a5cf650) reef (dev)": 3
    }
}
```
so confident it's not caused by the PRs in the run. Will investigate further later
- 1 instance of https://tracker.ceph.com/issues/57771
- 1 instance of https://tracker.ceph.com/issues/49287

10 Dead Jobs

- 6 failures due to known issue with satellite server during RHEL tests `'The DMI UUID of this host (00000000-0000-0000-0000-0CC47AD93798) matches other registered hosts:`
- 4 failures due to what seems to be mismatch issue between keepalived and haproxy conf, caused by another PR in the run (not this one)

 I think most of the PRs in the run are okay for merging despite the raw failure count.

**Pull request merged**
