### PR TITLE
mgr,pybind/mgr: add OSDMap.build_simple() method

### PR DESCRIPTION
**Pull request by tchaikov**
## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by liewegas** [comment]
What is this used for?  IIRC build_simple() is super-old and mostly only exercised by unit tests

**Comment by tchaikov** [comment]
@liewegas this change is created for testing the performance of serialize and deserialize osdmap of different number of osds in the mgr module. i will try to wrap a more useful constructor if there is a better alternative.

**Comment by liewegas** [comment]
> @liewegas this change is created for testing the performance of serialize and deserialize osdmap of different number of osds in the mgr module. i will try to wrap a more useful constructor if there is a better alternative.

Oh I see.  This is a good fit then!

**Comment by tchaikov** [comment]
- https://pulpito.ceph.com/kchai-2021-06-27_13:33:07-rados-wip-kefu-testing-2021-06-27-1907-distro-basic-smithi/
- https://pulpito.ceph.com/kchai-2021-06-29_07:34:48-rados-wip-kefu-testing-2021-06-27-1907-distro-basic-smithi/

failures either tracked or fixed by


- https://tracker.ceph.com/issues/5024
- https://tracker.ceph.com/issues/50151
- #42084

**Comment by tchaikov** [comment]
jenkins test make check

**Review by epuertat — APPROVED** [review]
LGTM. Thanks @tchaikov !

**Pull request merged**
