### PR TITLE
script/make_rocksdb_makefile.sh: do not include rocksdb/tools/rdb/*

### PR DESCRIPTION
**Pull request by tchaikov**
Fixes: http://tracker.ceph.com/issues/13554
Signed-off-by: Kefu Chai <kchai@redhat.com>

### CODE REVIEW

**Comment by tchaikov** [comment]
@dmick

**Comment by dmick** [comment]
LGTM; if the test passes I'm good

**Comment by tchaikov** [comment]
but if the test fails, it won't be caused by this change, right?

**Comment by dmick** [comment]
well, this should prevent the test from failing for this reason (if it runs on an RPM system) and have no effect (if it runs on a deb system), so it ought to pass with respect to this bug, right?

**Comment by dmick** [comment]
(and it seems to be running on trusty right at the moment)

**Comment by tchaikov** [comment]
but "make_rocksdb_makefile.sh" is not used by "make check", it is launched manually i think. `git grep make_rocksdb_makefile.sh` does not show anything for me.

**Comment by dmick** [comment]
ugh.  :(

**Comment by liewegas** [comment]
I run this manually when updating the rocksdb submodule commit.  If we don't need those files in teh tarball, though, then this looks good!

**Comment by dmick** [comment]
we not only don't need them, they do damage.

**Pull request merged**
