### PR TITLE
crimson/osd/backfill_state: always go to Enqueuing when object is pushed during Waiting

### PR DESCRIPTION
**Pull request by xxhdx1985126**
Fixes: https://tracker.ceph.com/issues/68061
Signed-off-by: Xuehan Xu <xuxuehan@qianxin.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Comment by athanatos** [comment]
Can you expand a bit on why this fixes the linked bug?

**Comment by xxhdx1985126** [comment]
> Can you expand a bit on why this fixes the linked bug?

The issue was like the following:

1. The backfill procedure has finished the primary/replica scans.
2. A new object `O` is created while the peers' `last_backfill`s are not yet advanced beyond that object; which means `O`'s creation is not sent to replica osds.
3. The backfill finishes.
4. A new write to `O` is sent to replica osds.
5. replica osds crash when processing that write because they don't have `O`

The issue was caused by `Waiting` doesn't go to `Enqueuing`, during which BackfillState checks the latest pglog entries to include the newly created objects in further backfills (`BackfillState::Enqueuing::maybe_update_range()`), when waiting for the last round of object pushes to finish. So this PR forces `Waiting` to always go to `Enqueuing` on `ObjectPushed`

**Review by athanatos — APPROVED** [review]
I think there's an pretty good unit test suite for this -- would it be possible to add a test case for this?

**Comment by xxhdx1985126** [comment]
> I think there's an pretty good unit test suite for this -- would it be possible to add a test case for this?

I'll try to add one.

**Comment by xxhdx1985126** [comment]
jenkins test make check

**Comment by xxhdx1985126** [comment]
jenkins test api

**Comment by xxhdx1985126** [comment]
jenkins test windows

**Comment by Matan-B** [comment]
> I'll try to add one.

I don't want to block this PR to avoid conflicts in other backfill PR merges, feel free to add tests in a separate PR :)

**Comment by Matan-B** [comment]
https://pulpito.ceph.com/matan-2024-10-13_10:25:17-crimson-rados-wip-matanb-crimson-testing-oct-10-distro-crimson-smithi/

Failures are 2 infra and one seastore

**Comment by xxhdx1985126** [comment]
Sorry, I forgot to add test cases for this PR, will do it later.

**Pull request merged**
