### PR TITLE
qa/tests: update links for centos latest to point to 7.5

### PR DESCRIPTION
**Pull request by vasukulkarni**
Signed-off-by: Vasu Kulkarni <vasu@redhat.com>

### CODE REVIEW

**Comment by liewegas** [comment]
http://pulpito.ceph.com/sage-2018-07-27_22:46:42-rados-wip-sage3-testing-2018-07-27-0742-distro-basic-smithi/

image seems to be missing or something?

**Comment by vasukulkarni** [comment]
sorry, i filed an issue for fog/ovh, will check with David on monday http://tracker.ceph.com/issues/25147

**Comment by vasukulkarni** [comment]
@yuriw want to pick this in one of your rados wip tests?

**Comment by yuriw** [comment]
http://pulpito.ceph.com/yuriw-2018-11-01_17:05:38-rados-master-distro-basic-smithi/

**Comment by vasukulkarni** [comment]
Looks good! http://pulpito.ceph.com/vasu-2018-11-01_18:16:36-rados-master-distro-basic-smithi/

**Comment by vasukulkarni** [comment]
jenkins retest this please

**Pull request merged**
