### PR TITLE
RadosClient: reduce cpu burning; fix message leak

### PR DESCRIPTION
**Pull request by xiexingguo**

### CODE REVIEW

**Comment by xiexingguo** [comment]
@liewegas Mind having a look at this? Thanks.

**Comment by xiexingguo** [comment]
@liewegas  And this one too, since you are there:-)

**Comment by xiexingguo** [comment]
retest this please

**Comment by liewegas** [comment]
lgtm!

**Comment by yuriw** [comment]
test run http://pulpito.ceph.com/yuriw-2016-06-03_10:48:51-rados-wip-yuri-testing2-distro-basic-smithi/

**Comment by gregsfortytwo** [comment]
@liewegas @xiexingguo, this triggered a build warning and it's a serious one:
>librados/IoCtxImpl.cc:321:15: warning: reference to local variable 'pn' returned [-Wreturn-local-addr]

This looks to be part of the public interface so we can't just change the function interface; I'm not sure if there's an easy solution or not.

**Pull request merged**
