### PR TITLE
pacific: cephadm: November batch

### PR DESCRIPTION
**Pull request by sebastian-philipp**
Backport of #43376, #43602, #43654, #43734, #42838, #43454, #43628, #43762, #43790, #43737, #43827, #43821, #43825, #43789, #43536, #43874

```
git log -n 23 | grep -C 10 Conflicts  
commit 240241dae589f1c6996a9011cbb42dc1792c3927
    qa/suites/orch/cephadm: add 8.stream + container_tools
    
    Conflicts:
            qa/suites/orch/cephadm/dashboard/0-distro/centos_8.2_container_tools_3.0.yaml

commit 7c8a492e5fd43a3c76e630f076ff12d31da06311
    mgr/orchestrator: pass 'force' flag down for remove_service
    
    Conflicts:
            src/pybind/mgr/rook/module.py

commit d62ac37a0e2abfddec22bf698997f87d31e130e0
    mgr/cephadm: Fix RGW ipv6 frontend configuration

    Conflicts:
    
      src/pybind/mgr/cephadm/tests/test_services.py
    
      fix tox test: AttributeError: 'HostCache' object has no
      attribute 'update_host_networks' which was introduced in
      78983ad0d0cce422da32dc4876ac186f6d32c3f5 (not yet in pacific)

commit 385b35569d7fe4c1901f491ffcb43183cccb7bbb
    mgr/cephadm: set health check warning for apply spec failures and daemon place failures in serve
    
    Conflicts:
            src/pybind/mgr/cephadm/module.py
            src/pybind/mgr/cephadm/serve.py
```

Changelog:

Dropped `05125a4533 ceph-volume: implement lvm wrapper`, `d 0dbd9bf9e4 cephadm: mount rootfs in osd containers`

### CODE REVIEW

**Review by adk3798 — APPROVED** [review]
changes from me look good

**Review by Daniel-Pivonka — APPROVED** [review]
commits from me look good

**Comment by sebastian-philipp** [comment]
scheduled: https://pulpito.ceph.com/swagner-2021-11-16_14:11:34-rados:cephadm-wip-swagner2-testing-2021-11-16-1128-pacific-distro-default-smithi/

**Comment by sebastian-philipp** [comment]
```
2021-11-16T19:36:08.182 INFO:teuthology.orchestra.run.smithi039.stderr:/usr/bin/docker: stderr usage: ceph-volume lvm batch [-h] [--db-devices [DB_DEVICES [DB_DEVICES ...]]]
2021-11-16T19:36:08.182 INFO:teuthology.orchestra.run.smithi039.stderr:/usr/bin/docker: stderr                              [--wal-devices [WAL_DEVICES [WAL_DEVICES ...]]]
2021-11-16T19:36:08.182 INFO:teuthology.orchestra.run.smithi039.stderr:/usr/bin/docker: stderr                              [--journal-devices [JOURNAL_DEVICES [JOURNAL_DEVICES ...]]]
2021-11-16T19:36:08.182 INFO:teuthology.orchestra.run.smithi039.stderr:/usr/bin/docker: stderr                              [--auto] [--no-auto] [--bluestore] [--filestore]
2021-11-16T19:36:08.183 INFO:teuthology.orchestra.run.smithi039.stderr:/usr/bin/docker: stderr                              [--report] [--yes]
2021-11-16T19:36:08.183 INFO:teuthology.orchestra.run.smithi039.stderr:/usr/bin/docker: stderr                              [--format {json,json-pretty,pretty}] [--dmcrypt]
2021-11-16T19:36:08.183 INFO:teuthology.orchestra.run.smithi039.stderr:/usr/bin/docker: stderr                              [--crush-device-class CRUSH_DEVICE_CLASS]
2021-11-16T19:36:08.183 INFO:teuthology.orchestra.run.smithi039.stderr:/usr/bin/docker: stderr                              [--no-systemd]
2021-11-16T19:36:08.183 INFO:teuthology.orchestra.run.smithi039.stderr:/usr/bin/docker: stderr                              [--osds-per-device OSDS_PER_DEVICE]
2021-11-16T19:36:08.184 INFO:teuthology.orchestra.run.smithi039.stderr:/usr/bin/docker: stderr                              [--data-slots DATA_SLOTS]
2021-11-16T19:36:08.184 INFO:teuthology.orchestra.run.smithi039.stderr:/usr/bin/docker: stderr                              [--block-db-size BLOCK_DB_SIZE]
2021-11-16T19:36:08.184 INFO:teuthology.orchestra.run.smithi039.stderr:/usr/bin/docker: stderr                              [--block-db-slots BLOCK_DB_SLOTS]
2021-11-16T19:36:08.184 INFO:teuthology.orchestra.run.smithi039.stderr:/usr/bin/docker: stderr                              [--block-wal-size BLOCK_WAL_SIZE]
2021-11-16T19:36:08.184 INFO:teuthology.orchestra.run.smithi039.stderr:/usr/bin/docker: stderr                              [--block-wal-slots BLOCK_WAL_SLOTS]
2021-11-16T19:36:08.185 INFO:teuthology.orchestra.run.smithi039.stderr:/usr/bin/docker: stderr                              [--journal-size JOURNAL_SIZE]
2021-11-16T19:36:08.185 INFO:teuthology.orchestra.run.smithi039.stderr:/usr/bin/docker: stderr                              [--journal-slots JOURNAL_SLOTS] [--prepare]
2021-11-16T19:36:08.185 INFO:teuthology.orchestra.run.smithi039.stderr:/usr/bin/docker: stderr                              [--osd-ids [OSD_IDS [OSD_IDS ...]]]
2021-11-16T19:36:08.185 INFO:teuthology.orchestra.run.smithi039.stderr:/usr/bin/docker: stderr                              [DEVICES [DEVICES ...]]
2021-11-16T19:36:08.185 INFO:teuthology.orchestra.run.smithi039.stderr:/usr/bin/docker: stderr ceph-volume lvm batch: error: Unable to proceed with non-existing device: vg_nvme/lv_4

```

**Review by guits — APPROVED** [review]

**Comment by sebastian-philipp** [comment]
https://pulpito.ceph.com/swagner-2021-11-17_12:55:30-rados:cephadm-wip-swagner2-testing-2021-11-17-1126-pacific-distro-default-smithi/

Failures: 
* mds_update_sequence in the meantime fixed by #43890 
* infra issues
*

**Pull request merged**
