### PR TITLE
luminous: tests: install python3-cephfs for fs suite

### PR DESCRIPTION
**Pull request by tchaikov**
https://tracker.ceph.com/issues/42580

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`

</details>

### CODE REVIEW

**Comment by smithfarm** [comment]
@tchaikov Could you add `Conflicts` sections to the commits? Missing `Conflicts` section means "this commit cherry-picked cleanly"...

**Comment by tchaikov** [comment]
@smithfarm i don't understand why it helps to add `Conflicts` if one wants to compare the backported changes with this PR.

**Comment by smithfarm** [comment]
@tchaikov If you are determined to compare the changes manually, then I suppose it doesn't help you. But the reason we have that rule is to let reviewers know whether the commit cherry-picked cleanly, or whether manual changes were needed.

By omitting the "Conflicts" section, you signaled that this was a clean cherry-pick.

**Comment by tchaikov** [comment]
@smithfarm i still don't understand why it helps the reviewer or posterity.

**Comment by smithfarm** [comment]
@tchaikov Really? Can you elaborate why knowing whether the cherry-pick was clean does not help?

**Comment by tchaikov** [comment]
@smithfarm it's a trivial resolution i'd suggest you check the diff manually. if you still believe this is a must and you think it's a blocker, please feel free to close this PR . its solely purpose is to unblock Yuri.

**Comment by yuriw** [comment]
[wip-yuri8-testing-2019-10-31-1518-luminous](https://trello.com/c/zOlYlKZP/741-wip-yuri8-testing-2019-10-31-1518-luminous)

**Comment by yuriw** [comment]
@smithfarm i actually forgot to run p2p :( apologies, remembered only after merged, hope its still good

**Pull request merged**
