### PR TITLE
luminous: add --add-bucket and --move options to crushtool

### PR DESCRIPTION
**Pull request by tchaikov**
http://tracker.ceph.com/issues/23472

### CODE REVIEW

**Comment by smithfarm** [comment]
retest this please

**Comment by tchaikov** [comment]
i need to de-C++17 this PR.

**Comment by jdurgin** [comment]
```/home/jenkins-build/build/workspace/ceph-pull-requests/src/tools/crushtool.cc: In function ‘int main(int, const char**)’:
/home/jenkins-build/build/workspace/ceph-pull-requests/src/tools/crushtool.cc:1039:81: error: expected ‘)’ before ‘;’ token
     if (int r = do_add_bucket(cct.get(), me, crush, add_name, add_type, add_loc); !r) {
                                                                                 ^
/home/jenkins-build/build/workspace/ceph-pull-requests/src/tools/crushtool.cc:1039:13: warning: unused variable ‘r’ [-Wunused-variable]
     if (int r = do_add_bucket(cct.get(), me, crush, add_name, add_type, add_loc); !r) {
             ^
/home/jenkins-build/build/workspace/ceph-pull-requests/src/tools/crushtool.cc:1039:84: error: ‘r’ was not declared in this scope
     if (int r = do_add_bucket(cct.get(), me, crush, add_name, add_type, add_loc); !r) {
                                                                                    ^
/home/jenkins-build/build/workspace/ceph-pull-requests/src/tools/crushtool.cc:1041:7: error: expected ‘}’ before ‘else’
     } else {
       ^
/home/jenkins-build/build/workspace/ceph-pull-requests/src/tools/crushtool.cc:1042:14: error: ‘r’ was not declared in this scope
       return r;
              ^
/home/jenkins-build/build/workspace/ceph-pull-requests/src/tools/crushtool.cc: At global scope:
/home/jenkins-build/build/workspace/ceph-pull-requests/src/tools/crushtool.cc:1046:3: error: expected unqualified-id before ‘if’
   if (move_item) {
   ^
src/tools/CMakeFiles/crushtool.dir/build.make:62: recipe for target 'src/tools/CMakeFiles/crushtool.dir/crushtool.cc.o' failed```

**Comment by tchaikov** [comment]
@jdurgin fixed and repushed.

**Comment by yuriw** [comment]
[wip-yuri3-testing-2018-04-05-1940-luminous](https://trello.com/c/4WshpfXq/285-wip-yuri3-testing-2018-04-05-1940-luminous)

**Pull request merged**
