### PR TITLE
fix some describle problems in admin.rst

### PR DESCRIPTION
**Pull request by excellentkf**
Signed-off-by: excellentkf <likefei@cmss.chinamobile.com>

### CODE REVIEW

**Comment by excellentkf** [comment]
hi,@cbodley do you mind take a review? thanks

**Comment by excellentkf** [comment]
hi, @xiexingguo do you mind take a review? thanks

**Comment by excellentkf** [comment]
hi @oritwas , @mattbenjamin do you mind take a review? thanks

**Comment by robbat2** [comment]
LGTM

**Pull request closed without merging**
