### PR TITLE
mgr/rbd_support: don't scan pools that don't have schedules

### PR DESCRIPTION
**Pull request by trociny**
Signed-off-by: Mykola Golub <mgolub@suse.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by dillaman** [comment]
Not 100% sure if it's related to this PR, but the CLI tests are failing now:
http://qa-proxy.ceph.com/teuthology/jdillaman-2020-03-11_14:09:34-rbd-wip-jd-testing-distro-basic-smithi/4847407/teuthology.log

**Comment by trociny** [comment]
@dillaman there was a race in the cli test -- it did not wait for schedule status updated. Pushed the fix as an additional commit.

**Comment by trociny** [comment]
@dillaman when looking at that test failure I noticed an issue with the recursive schedule listing, which I fixed in the last pushed commit.

**Comment by dillaman** [comment]
http://pulpito.ceph.com/jdillaman-2020-03-12_14:35:00-rbd-wip-jd-testing-distro-basic-smithi/

**Pull request merged**
