### PR TITLE
cephfs-mirror: teuthology task and tests

### PR DESCRIPTION
**Pull request by vshankar**
mirroring tests and supporting cephfs-mirror teuthology task

requires: PR #35697, #35993, #36131 and #36603

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by vshankar** [comment]
Test run with the above PRs: https://pulpito.ceph.com/vshankar-2020-08-18_11:27:17-fs-wip-cephfs-snap-mirror-18-08-20-053859-distro-basic-smithi/

Failure is due to a cluster health message which needs whitelisting.

**Review by mchangir — COMMENTED** [review]
Looks good to me.
I have some changes to the creation path of backup_fs required for your tests in my PR #37490.
Please take a look there. In essence, since the snap replicator tests need to write data to the file-system, the file-system needs to be mounted. And as far as I can tell, the only way to get a file-system mounted is to define a ceph-fuse section via the yaml.

**Comment by batrick** [comment]
retest this please

**Review by ajarr — COMMENTED** [review]
I have been testing the branch, https://github.com/vshankar/ceph/commits/wip-cephfs-mirror-for-rraja that includes commits in this PR.

Couple of issues I ran into:
-  adding a non-existent directory for snapshot mirroring passed
   $  ceph fs snapshot mirror add <fs-name> <non-existent directory in the fs>
   The above command passed. As per the doc, this is supposed to fail?

- snapshot peer removing a non-existent peer ID passed. Is this expected?

- the steps to setup client IDs for mirroring and starting snapshot mirror daemon were at the end of the document. I think it would be more intuitive if it's moved near the top of the document. This way the documented steps can be executed sequentially to get mirroring working.
https://github.com/vshankar/ceph/blob/e8615c010f660947f47cffd2f3e8e343fb316f3e/doc/dev/cephfs-mirroring.rst#starting-mirror-daemon

**Comment by vshankar** [comment]
> * adding a non-existent directory for snapshot mirroring passed
>   $  ceph fs snapshot mirror add  
>   The above command passed. As per the doc, this is supposed to fail?

Nice catch. The branch fixes Milind's review comment where we allow adding non-existent directories. I updated the docs with the same: https://github.com/ceph/ceph/pull/37876/commits/798abccb25dc8e50c7fe67e632ac6075754147e9#diff-18ba51d5b77ffca4e44c11e9e69a375f55896ed85f6542f24d3e6cbecb945b7dR334

Maybe there are other references in the doc which I missed updating. I'll check.

> * snapshot peer removing a non-existent peer ID passed. Is this expected?

Yeh -- peer commands are idempotent.

> * the steps to setup client IDs for mirroring and starting snapshot mirror daemon were at the end of the document. I think it would be more intuitive if it's moved near the top of the document. This way the documented steps can be executed sequentially to get mirroring working.
>   https://github.com/vshankar/ceph/blob/e8615c010f660947f47cffd2f3e8e343fb316f3e/doc/dev/cephfs-mirroring.rst#starting-mirror-daemon

makes sense.

**Comment by vshankar** [comment]
@ajarr I did miss updating the doc w.r.t. adding non-existent dirs.

**Comment by ajarr** [comment]
> > * adding a non-existent directory for snapshot mirroring passed
> >   $  ceph fs snapshot mirror add
> >   The above command passed. As per the doc, this is supposed to fail?
> 
> Nice catch. The branch fixes Milind's review comment where we allow adding non-existent directories. I updated the docs with the same: [798abcc#diff-18ba51d5b77ffca4e44c11e9e69a375f55896ed85f6542f24d3e6cbecb945b7dR334](https://github.com/ceph/ceph/commit/798abccb25dc8e50c7fe67e632ac6075754147e9#diff-18ba51d5b77ffca4e44c11e9e69a375f55896ed85f6542f24d3e6cbecb945b7dR334)
> 
> Maybe there are other references in the doc which I missed updating. I'll check.
> 

The doc has been updated to fix this. Cool!

> > * snapshot peer removing a non-existent peer ID passed. Is this expected?
> 
> Yeh -- peer commands are idempotent.
> 

Any reason for doing so? I see that we typically don't make removals idempotent (subvolumes, snapshots, etc).

> > * the steps to setup client IDs for mirroring and starting snapshot mirror daemon were at the end of the document. I think it would be more intuitive if it's moved near the top of the document. This way the documented steps can be executed sequentially to get mirroring working.
> >   https://github.com/vshankar/ceph/blob/e8615c010f660947f47cffd2f3e8e343fb316f3e/doc/dev/cephfs-mirroring.rst#starting-mirror-daemon
> 
> makes sense.

The doc has been updated to fix this. Cool!

**Comment by vshankar** [comment]
> > > * snapshot peer removing a non-existent peer ID passed. Is this expected?
> > 
> > 
> > Yeh -- peer commands are idempotent.
> 
> Any reason for doing so? I see that we typically don't make removals idempotent (subvolumes, snapshots, etc).

True. However, IIRC, we were (as in ceph as a whole) moving towards idempotent commands (at least for the new CLIs we introduce).

**Review by mchangir — APPROVED** [review]
looks good to me

**Pull request merged**
