### PR TITLE
pacific: librbd: miscellaneous backports

### PR DESCRIPTION
**Pull request by dillaman**
## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Review by trociny — APPROVED** [review]

**Comment by dillaman** [comment]
Includes #39800

**Comment by dillaman** [comment]
Includes #39821

**Comment by idryomov** [comment]
Added #39781 (commit https://github.com/ceph/ceph/commit/88f1087f9c56a9a6bee42ae465b2e88a66869951 is omitted because all releases use the same version of the script -- the task pulls it from master).

**Review by idryomov — APPROVED** [review]

**Comment by trociny** [comment]
the jenkins `make check` seemed to get stuck in `TestLibRBD.ConcurentOperations`, but this does not look like something new, it has been already reported [1].

jenkins test make check

[1] https://tracker.ceph.com/issues/47596

**Comment by trociny** [comment]
jenkins test make check

**Comment by idryomov** [comment]
https://pulpito.ceph.com/dis-2021-03-10_19:49:31-krbd-pacific-testing-basic-smithi/

**Comment by dillaman** [comment]
Includes #40002

**Pull request merged**
