### PR TITLE
rgw: add delimiter to prefix only when path is specified

### PR DESCRIPTION
**Pull request by lebauce**
http://tracker.ceph.com/issues/13014

### CODE REVIEW

**Comment by lebauce** [comment]
This is just the backport of https://github.com/ceph/ceph/pull/5828 that was just merged

**Comment by dachary** [comment]
@lebauce thanks ! we'll take it from here, your work is complete :-)

**Comment by dachary** [comment]
@yehudasa does this backport look good to merge ? It passed a run of the hammer rgw suite ( see http://tracker.ceph.com/issues/13356#note-5 for details ).

**Comment by yehudasa** [comment]
@dachary yes

**Pull request merged**
