### PR TITLE
spdk: upgrade spdk to v16.12

### PR DESCRIPTION
**Pull request by liupan1111**
Signed-off-by: Pan Liu <pan.liu@istuary.com>

### CODE REVIEW

**Comment by liupan1111** [comment]
@yuyuyu101  @tchaikov @optimistyzy , please help take a look.

**Comment by liupan1111** [comment]
optimistyzy already upgrate ceph/spdk to 16.12 version, but ceph submodule is still old.

**Comment by liupan1111** [comment]
commit 845fd9c841593afe24de642a9bed0ae4e5cca3ad
Author: Pan Liu <pan.liu@istuary.com>
Date:   Mon Dec 26 18:47:18 2016 +0800

    spdk: upgrade spdk to v16.12
    
    Signed-off-by: Pan Liu <pan.liu@istuary.com>

diff --git a/src/spdk b/src/spdk
index 9322c25..df46c41 160000
--- a/src/spdk
+++ b/src/spdk
@@ -1 +1 @@
-Subproject commit 9322c258084c6abdeefe00067f8b310a6e0d9a5a
+Subproject commit df46c41a4ca2edabd642a73b25e54dcb173cf976

**Comment by optimistyzy** [comment]
Suggest updating with the change in the bluestore together.

**Comment by liupan1111** [comment]
@optimistyzy it is fine to update spdk/dpdk/bluestore toghether. But I think it is also ok to upgrade step By step. The current situation is: Even if We don't update spdk version, ceph+spdk compilation also has some errors now... So I prefer We could confirm every step in The right way in different PRs.

**Comment by yuyuyu101** [comment]
yep, keep consistent with spdk and bluestore

**Pull request closed without merging**
