### PR TITLE
doc: s/deamon/daemon/

### PR DESCRIPTION
**Pull request by ashitakasam**
…rc/tools/rbd_recover_tool/README

Signed-off-by: ashitakasam <694240887@qq.com>

### CODE REVIEW

**Comment by tchaikov** [comment]
retest this please

**Comment by Liuchang0812** [comment]
retest this please

**Comment by Liuchang0812** [comment]
retest this please

**Comment by Liuchang0812** [comment]
retest this please

**Comment by joscollin** [comment]
jenkins render docs

**Pull request merged**
