### PR TITLE
rgw: admin rest api support op-mask

### PR DESCRIPTION
**Pull request by joke-lee**
Signed-off-by: yuliyang <yuliyang@cmss.chinamobile.com>

### CODE REVIEW

**Comment by joke-lee** [comment]
jenkins test this please

**Comment by joke-lee** [comment]
hi @mattbenjamin would you mind add this to qa test ?

**Comment by mattbenjamin** [comment]
@joke-lee with the needs-qa tag, that will happen automatically from here, most likely in the next several days

**Comment by cbodley** [comment]
http://pulpito.ceph.com/cbodley-2018-11-07_17:48:22-rgw-wip-cbodley-testing-distro-basic-smithi/

**Pull request merged**
