### PR TITLE
mon/OSDMonitor: make 'osd crush rule rename' idempotent

### PR DESCRIPTION
**Pull request by xiexingguo**
Fixes: http://tracker.ceph.com/issues/21162
Signed-off-by: xie xingguo <xie.xingguo@zte.com.cn>

### CODE REVIEW

**Comment by xiexingguo** [comment]
http://pulpito.ceph.com/xxg-2017-08-29_01:43:41-rados-wip-21162-distro-basic-smithi/

**Comment by xiexingguo** [comment]
@liewegas And this.

**Comment by liewegas** [comment]
Once upon a time there was an environment variable you could set that would make the ceph CLI submit every mon command twice (unless the first one errored out).  That meant you could jsut run the cephtool/test.sh (or similar) script with the var and the idempotency would get tested for everything...

**Comment by liewegas** [comment]
Hmm, and it looks like workunit.py sets it,
<pre>
                    run.Raw('CEPH_CLI_TEST_DUP_COMMAND=1'),
</pre>
and ceph.in implements it,
<pre>
            # debug tool: send any successful command *again* to
            # verify that it is idempotent.
            if not ret and 'CEPH_CLI_TEST_DUP_COMMAND' in os.environ:
                ret, outbuf, outs = new_style_command(parsed_args, childargs,
                                                      target, sigdict, inbuf,
                                                      verbose)
                if ret < 0:
                    ret = -ret
                    print(prefix +
                          'Second attempt of previously successful command '
                          'failed with {0}: {1}'.format(
                              errno.errorcode.get(ret, 'Unknown'), outs),
                          file=sys.stderr)
</pre>
but it doesn't seem to be catching these errors.  Mind taking a look?

**Comment by liewegas** [comment]
http://pulpito.ceph.com/sage-2017-08-29_16:36:17-rados-wip-sage-testing-20170829a-distro-basic-smithi/

**Pull request merged**
