### PR TITLE
librbd: possible QEMU deadlock after creating image snapshots

### PR DESCRIPTION
**Pull request by dillaman**

### CODE REVIEW

**Comment by dillaman** [comment]
@jdurgin requesting review since this isn't a true backport.  I'm running a subset RBD suite to test it before yanking my wip label.

**Comment by jdurgin** [comment]
lgtm - don't see any other deadlocks that could happen from this

**Comment by dillaman** [comment]
Passed rbd suite subset minus environment/test noise: http://pulpito.ceph.com/jdillaman-2016-03-07_15:01:36-rbd-wip-15032-infernalis---basic-multi/

**Comment by vasukulkarni** [comment]
@dillaman fio tests are hanging, in some case a crash is seen http://qa-proxy.ceph.com/teuthology/jdillaman-2016-03-07_15:01:36-rbd-wip-15032-infernalis---basic-multi/49877/teuthology.log , It may be due to different issue but just want to bring up since i was just scanning the output of fio.

**Comment by dillaman** [comment]
@vasukulkarni The OSDs crashed due to the suicide timeout, so I'd expect IO to hang

> stderr:common/HeartbeatMap.cc: 81: FAILED assert(0 == "hit suicide timeout")

**Comment by vasukulkarni** [comment]
@dillaman yep thanks

**Pull request merged**
