### PR TITLE
fix bugs about cache tier.

### PR DESCRIPTION
**Pull request by majianpeng**

### CODE REVIEW

**Comment by majianpeng** [comment]
@liewegas . 
For  33be665bee81d0f6b07f93cc7f998f50cfbf684d，i add support_omap() in pg_pool_t rather than PGBackend. This because for ReplicatedPGBackend, it need flag FLAG_DEBUG_FAKE_EC_POOL. But this flag in pg_pool_t.

For 536dd945624ad30a990dbee06cd5f1084a83e9f1. If promote met error, how to handle
a)don't do anything
b)for some error bypass cache tier 
c)set a global option choose all error bypass or not
My patch implement b).  Is it need c) ?

Thanks!

**Comment by majianpeng** [comment]
@dachary . My pull request don't end up. How to find the reason? Thanks!

**Comment by dachary** [comment]
@majianpeng the best way is to run make check on your own machine (using the run-make-check.sh script is what the bot does) and you will be able to observe precisely why it hangs. If it's still mysterious I'd be happy to help.

**Comment by majianpeng** [comment]
@liewegas . ping

**Comment by liewegas** [comment]
The rest of the series looks good if we drop that promote failure case patch!

**Comment by liewegas** [comment]
Reviewed-by:

**Comment by athanatos** [comment]
Good call on the supports_omap() method, way clearer.  Adding to wip-sam-testing.

**Comment by athanatos** [comment]
Actually, leaving out for this cycle since it conflicts with another branch.  Sorry!  I'll get it on the next pass.

**Comment by liewegas** [comment]
@majianpeng can you rebase this on latest master?

**Comment by liewegas** [comment]
@majianpeng ping

**Comment by majianpeng** [comment]
@liewegas  Sorry for later response. updated & review. Thanks!

**Comment by athanatos** [comment]
Adding to my testing branch.  Sorry for the delay, teuthology cluster was very busy.

**Pull request merged**
