### PR TITLE
luminous: multisite: object metadata operations are skipped by sync

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/24985

### CODE REVIEW

**Comment by smithfarm** [comment]
```
In file included from /home/jenkins-build/build/workspace/ceph-pull-requests/src/rgw/rgw_rados.h:26:0,
                 from /home/jenkins-build/build/workspace/ceph-pull-requests/src/rgw/rgw_user.h:15,
                 from /home/jenkins-build/build/workspace/ceph-pull-requests/src/rgw/rgw_acl.cc:14:
/home/jenkins-build/build/workspace/ceph-pull-requests/src/rgw/rgw_sync_module.h:25:114: error: ‘std::optional’ has not been declared
   virtual RGWCoroutine *sync_object(RGWDataSyncEnv *sync_env, RGWBucketInfo& bucket_info, rgw_obj_key& key, std::optional<uint64_t> versioned_epoch, rgw_zone_set *zones_trace) = 0;
                                                                                                                  ^
/home/jenkins-build/build/workspace/ceph-pull-requests/src/rgw/rgw_sync_module.h:25:122: error: expected ‘,’ or ‘...’ before ‘<’ token
   virtual RGWCoroutine *sync_object(RGWDataSyncEnv *sync_env, RGWBucketInfo& bucket_info, rgw_obj_key& key, std::optional<uint64_t> versioned_epoch, rgw_zone_set *zones_trace) = 0;
                                                                                                                          ^
In file included from /home/jenkins-build/build/workspace/ceph-pull-requests/src/rgw/rgw_user.h:15:0,
                 from /home/jenkins-build/build/workspace/ceph-pull-requests/src/rgw/rgw_acl.cc:14:
/home/jenkins-build/build/workspace/ceph-pull-requests/src/rgw/rgw_rados.h:2824:9: error: ‘optional’ in namespace ‘std’ does not name a type
         std::optional<uint64_t> olh_epoch;
         ^
/home/jenkins-build/build/workspace/ceph-pull-requests/src/rgw/rgw_rados.h:3159:29: error: ‘std::optional’ has not been declared
                        std::optional<uint64_t> olh_epoch,
                             ^
/home/jenkins-build/build/workspace/ceph-pull-requests/src/rgw/rgw_rados.h:3159:37: error: expected ‘,’ or ‘...’ before ‘<’ token
                        std::optional<uint64_t> olh_epoch,
                                     ^
/home/jenkins-build/build/workspace/ceph-pull-requests/src/rgw/rgw_rados.h:4000:3: error: ‘optional’ in namespace ‘std’ does not name a type
   std::optional<uint64_t> olh_epoch;
   ^
/home/jenkins-build/build/workspace/ceph-pull-requests/src/rgw/rgw_rados.h: In member function ‘void RGWPutObjProcessor_Atomic::set_olh_epoch(uint64_t)’:
/home/jenkins-build/build/workspace/ceph-pull-requests/src/rgw/rgw_rados.h:4045:5: error: ‘olh_epoch’ was not declared in this scope
     olh_epoch = epoch;
     ^
make[3]: *** [src/rgw/CMakeFiles/rgw_a.dir/rgw_acl.cc.o] Error 1
make[2]: *** [src/rgw/CMakeFiles/rgw_a.dir/all] Error 2
```

**Comment by theanalyst** [comment]
s/std::optional/boost::optional should mostly do the trick here

**Comment by smithfarm** [comment]
jenkins test docs

**Comment by yuriw** [comment]
[wip-yuri3-testing-2018-09-17-1952-luminous](https://trello.com/c/tDY6qyzl/407-wip-yuri3-testing-2018-09-17-1952-luminous)

**Pull request merged**
