### PR TITLE
mgr/dashboard: Use serial RGW Admin OPS API calls

### PR DESCRIPTION
**Pull request by votdev**
This PR takes care that changes done to a RGW user are submitted (via RGW Admin OPS API) in serial and NOT in parallel.

Fixes: https://tracker.ceph.com/issues/40015

Signed-off-by: Volker Theile <vtheile@suse.com>

- [x] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by votdev** [comment]
jenkins retest this please

**Comment by tchaikov** [comment]
retest this please.

**Comment by votdev** [comment]
jenkins retest this please

**Comment by votdev** [comment]
jenkins test make check arm64

**Pull request merged**
