### PR TITLE
OSD::load_pgs: we need to handle the case where an upgrade from earlier versions which ignored non-existent pgs resurrects a pg with a prehistoric osdmap

### PR DESCRIPTION
**Pull request by xinxinsh**
http://tracker.ceph.com/issues/11429

### CODE REVIEW

**Comment by dachary** [comment]
<pre>
$ commit=6bb24c4 ; picked_from=$(git show --no-patch --pretty=%b $commit  |  perl -ne 'print if(s/.*cherry picked from commit (\w+).*/$1/)') ; diff -u --ignore-matching-lines '^[^+-]' <(git show $picked_from) <(git show $commit)
--- /dev/fd/63	2015-05-12 23:44:17.785047014 +0200
+++ /dev/fd/62	2015-05-12 23:44:17.785047014 +0200
@@ -45,6 +50,7 @@
 +    } else {
 +      pg = _open_lock_pg(osdmap, pgid);
 +    }
-     // there can be no waiters here, so we don't call wake_pg_waiters
++    // there can be no waiters here, so we don't call wake_pg_waiters
  
      // read pg state, log
+     pg->read_state(store, bl);
</pre>

**Comment by dachary** [comment]
@xinxinsh could you update the conflict resolution with the diff above ? It's simpler than explaining and less error prone :-)

**Comment by xinxinsh** [comment]
updated

2015-05-13 5:50 GMT+08:00 Loic Dachary <notifications@github.com>:

**Comment by dachary** [comment]
@athanatos does this backport look good to merge ? It passed a run of the firefly rados suite ( see http://tracker.ceph.com/issues/11090#rados for details ) including 11429.yaml at https://github.com/ceph/ceph-qa-suite/pull/435

**Pull request merged**
