### PR TITLE
qa/suites/rbd: place cache file on tmpfs for xfstests

### PR DESCRIPTION
**Pull request by idryomov**
## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [x] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by CongMinYin** [comment]
Looks good, thanks your effort.

**Comment by CongMinYin** [comment]
Hi  @idryomov ,  I reproduced the issue about   `c_api_tests_with_defaults` failure. I think it is due "no space". The root cause is that some tests need to create two big cache files. So need `2x5G=10G`. This is the result I observed through the experiment, not the conclusion drawn from the code. see the output:
```
root@ssp-ceph105:~# watch -d ls -lh /dev/shm/cache/
Every 2.0s: ls -lh /dev/shm/cache/ ssp-ceph105: Thu May 26 12:48:59 2022total 6.9G
-rw------- 1 root root 5.0G May 26 12:48 rbd-pwl.test-librbd-ssp-ceph105-2482528-1.106872f57
e7e.pool
---------- 1 root root 0 May 26 12:48 rbd-pwl.test-librbd-ssp-ceph105-2482528-1.106a88afd
aae.pool
```
This is the output when I remount `/dev/shm/ size=7G`. Run `ceph_test_librdbd`, and run some test to create 2 cache file but no space then failed.  The direct error should be `ENOSPC: no space`, and it may cause `-16` and `-30` I guessd. So I tried `11G` as /dev/shm/. The size bigger than` 2X5G=10G`. `ceph_test_librbd` passed.  can you check the size of `/dev/shm/rbd-rwl-cache` in your qemu test.

```
#define	EBUSY		16	/* Device or resource busy */
#define	ENOSPC		28	/* No space left on device */
#define	EROFS		30	/* Read-only file system */
```

**Comment by idryomov** [comment]
> The direct error should be ENOSPC: no space, and it may cause -16 and -30 I guessd.

Did you observe errors other than ENOSPC in your test or is it just a guess?

I doubt the root cause is ENOSPC because if that was the case, the failures would be 100 percent reproducible as the "smithi" nodes in the upstream lab are more or less the same.  Yet in some runs (e.g. https://pulpito.ceph.com/dis-2022-04-19_17:35:35-rbd:persistent-writeback-cache-wip-dis-testing-distro-default-smithi/, https://pulpito.ceph.com/dis-2022-04-27_08:22:49-rbd:persistent-writeback-cache-wip-dis-testing-distro-default-smithi/) all `c_api_tests_with_defaults` jobs pass.

Also, `qemu_xfstests` job actually creates three cache files and no ENOSPC was ever observed there.  I picked 5G for `big-cache` for a reason, it's explained in "qa/suites/rbd: place rwl cache file on tmpfs" commit message:
> As /dev/shm tmpfs instance on lab nodes is limited to 16G and
> qemu_xfstests.yaml opens three images at the same time, reduce the
> "big cache" size to 5G.

**Comment by CongMinYin** [comment]
> Did you observe errors other than ENOSPC in your test or is it just a guess?
>
Yes, I observed three type of errors: `-16` `-28` `-30`.  And their mistakes are exactly the same. I compared all the wrong message with the wrong lines, and found that the errors of two tests were exactly the same. It doesn't seem like a coincidence. But I don't have evidence yet. I copied my step and test output to gist.  You can search `Which is` for a simple comparison.

1. https://gist.github.com/CongMinYin/766abe23ebe9fb1d174cf7b46cba296d  
2. http://qa-proxy.ceph.com/teuthology/dis-2022-04-27_08:22:49-rbd:persistent-writeback-cache-wip-dis-testing-distro-default-smithi/6808560/teuthology.log

> Also, qemu_xfstests job actually creates three cache files and no ENOSPC was ever observed there. 
>
The test environment reproduced locally is different from the qemu test environment on the tethology platform. We are trying to debug on teuthology. Could you please share how to fix the `/dev/shm` size in qemu to 16G.  Do we need to change the configuration of qemu?

**Comment by CongMinYin** [comment]
Sorry, I just thought of the reason for the tests why sometimes passed, sometimes failed. I modified the last comment several times and gave the explanation.

**Comment by idryomov** [comment]
> As I said yesterday, an image test can generate at most 2 cache files.

I think this is the key bit I'm missing.  Why would opening a single image generate two cache files?

> because the 3 tests are not synchronized

Why do you mean by "not synchronized"?  The test cases are executed one by one, always in the same order.  Why would the number of cache files vary?

**Comment by idryomov** [comment]
> Could you please share how to fix the `/dev/shm` size in qemu to 16G or 31G. Do I need to change the configuration of qemu?

No, `/dev/shm` size inside qemu is irrelevant as it is the qemu process that opens the images and it runs on the host.  So you should be able to do the same thing you did in your local test (`mount -o remount,size=XG /dev/shm/`), but note that `/dev/shm` should already be `16G`, at least on "smithi" nodes.

**Comment by CongMinYin** [comment]
> Why do you mean by "not synchronized"? The test cases are executed one by one, always in the same order. Why would the number of cache files vary, allowing the test to sometimes succeed and sometimes fail with the same `/dev/shm` size?

Sorry, I took the three images you mentioned as three processes, so I said these confusing words. Please ignore my explanation above. I'm very sorry. 

>So you should be able to do the same thing you did in your local test.

Thanks. I will try to reproduce the errors in the case of 16G locally. And continue to study why the error logs are the same. Sorry to interrupt.

**Comment by idryomov** [comment]
Thanks @majianpeng -- so in the `c_api_tests_with_defaults` case, it's ENOSPC after all!  There is nowhere we can get 51G for `/dev/shm`, so I'll have to rework this PR to place the cache file on tmpfs only for `qemu_xfstests`.

Did you get a chance to look into `qemu_xfstests` failures?

**Comment by majianpeng** [comment]
@idryomov . For xfstest of 259, we talked previous, this is a bug of kernel.  I checked again: it still use old kernel:Linux version 3.2.0-32-virtual (buildd@batsu) (gcc version 4.6.3 (Ubuntu/Linaro 4.6.3-1ubuntu5) ) #51-Ubuntu SMP Wed Sep 26 21:53:42 UTC 2012 (Ubuntu 3.2.0-32.51-virtual 3.2.30).   Why dose not upgrade to ubuntu20.04?

**Comment by majianpeng** [comment]
@idryomov . I agree your comments.  I'll look into 086 of xfstests.  Is it possible to separate this issue from this PR, and merge this PR first if there are no other issues?  Thanks!

**Comment by idryomov** [comment]
Yes, after this PR is updated, if sporadic `086` failures is the only thing that remains, I'm going to merge it as it would be a clear improvement over the status quo where the job just always timing out.

**Comment by idryomov** [comment]
`qemu_xfstests` is the only job that sporadically fails now:
https://pulpito.ceph.com/dis-2022-06-03_20:17:19-rbd:pwl-cache-wip-dis-testing-distro-default-smithi/

20x `qemu_xfstests` job:
https://pulpito.ceph.com/dis-2022-06-05_10:19:26-rbd:pwl-cache-wip-dis-testing-distro-default-smithi/

10x all other jobs:
https://pulpito.ceph.com/dis-2022-06-05_10:21:14-rbd:pwl-cache-wip-dis-testing-distro-default-smithi/

**Comment by idryomov** [comment]
`qemu_xfstests` failures:

086 (e.g. http://qa-proxy.ceph.com/teuthology/dis-2022-06-05_10:19:26-rbd:pwl-cache-wip-dis-testing-distro-default-smithi/6863660)
167 qemu-kvm coredump (https://pulpito.ceph.com/dis-2022-06-05_10:19:26-rbd:pwl-cache-wip-dis-testing-distro-default-smithi/6863685)
199 (http://qa-proxy.ceph.com/teuthology/dis-2022-06-05_10:19:26-rbd:pwl-cache-wip-dis-testing-distro-default-smithi/6863709)
259 (e.g. http://qa-proxy.ceph.com/teuthology/dis-2022-06-05_10:19:26-rbd:pwl-cache-wip-dis-testing-distro-default-smithi/6863682)

**Comment by majianpeng** [comment]
@idryomov  i'll prepare the environment to reproduce qemu-xfstests failed case and to find the root cause.

**Review by ideepika — APPROVED** [review]

**Comment by idryomov** [comment]
Thanks @majianpeng, let's track the investigation in https://tracker.ceph.com/issues/55909.

**Pull request merged**
