### PR TITLE
qa: Added latency to results table in test_rbd_wnbd.py

### PR DESCRIPTION
**Pull request by stefan-chivu**
Added data regarding completion latency (ns) to the fio  results table, such as min, max, mean, stddev, etc.

Signed-off-by: Stefan Chivu <schivu@cloudbasesolutions.com>

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [x] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by petrutlucian94** [comment]
jenkins test windows

**Comment by petrutlucian94** [comment]
jenkins test windows

**Comment by petrutlucian94** [comment]
jenkins test windows

**Comment by petrutlucian94** [comment]
jenkins test windows

**Comment by petrutlucian94** [comment]
jenkins test windows

**Comment by petrutlucian94** [comment]
jenkins test windows

**Comment by petrutlucian94** [comment]
We got the latency results:

```
+-------------------------------------------------------------------------------------------------------------------------------------------------+
|                                               Benchmark results (count: 1, concurrency: 4) op=read                                              |
+-------------------------+----------+-----------+---------------+---------------+---------------+---------------+---------------+----------------+
|           stat          |   min    |    max    |      mean     |     median    |    std_dev    |    max 90%    |    min 90%    |     total      |
+-------------------------+----------+-----------+---------------+---------------+---------------+---------------+---------------+----------------+
|     bandwidth (MB/s)    | 270.6003 |  411.7108 |    341.1555   |    411.7108   |    70.5553    |    411.7108   |    270.6003   |      N/A       |
|       duration (s)      |  0.0001  |   0.0003  |     0.0002    |     0.0003    |     0.0001    |     0.0003    |     0.0001    |     0.0004     |
|          errors         |    0     |     0     |     0.0000    |       0       |     0.0000    |       0       |       0       |       0        |
|      incomplete IOs     |    0     |     0     |     0.0000    |       0       |     0.0000    |       0       |       0       |       0        |
|       dropped IOs       |    0     |     0     |     0.0000    |       0       |     0.0000    |       0       |       0       |       0        |
| completion latency (ns) | 21337800 | 112485100 | 71159968.7500 | 90106737.5000 | 17483363.3637 | 50331648.0000 | 87031808.0000 | 142319937.5000 |
+-------------------------+----------+-----------+---------------+---------------+---------------+---------------+---------------+----------------+
```

We should convert it to seconds though, we're using nanoseconds right now and it's difficult to read. Also, I've just noticed that the "duration" report is incorrect. The reason is that we're dividing it by 1000 twice.

Feel free to apply this: https://github.com/ceph/ceph/pull/49883/commits/d597ea5e84ffc60befe5de7b39b6851156eb9d43

**Review by petrutlucian94 — APPROVED** [review]

**Comment by petrutlucian94** [comment]
jenkins test make check arm64

**Comment by petrutlucian94** [comment]
jenkins test make check

**Comment by stefan-chivu** [comment]
jenkins test make check

**Comment by petrutlucian94** [comment]
jenkins test make check

**Comment by petrutlucian94** [comment]
jenkins test make check

**Comment by petrutlucian94** [comment]
jenkins test make check

**Comment by petrutlucian94** [comment]
jenkins test make check

**Comment by petrutlucian94** [comment]
jenkins test make check

**Comment by stefan-chivu** [comment]
jenkins test make check

**Comment by stefan-chivu** [comment]
jenkins test make check arm64

**Comment by petrutlucian94** [comment]
jenkins test windows

**Comment by petrutlucian94** [comment]
We actually have a mypy failure, we'll probably have to explicitly cast it to float:

```
workunits/windows/test_rbd_wnbd.py:680: error: Unsupported operand types for ** ("str" and "int")
Found 1 error in 1 file (checked 252 source files)
mypy: exit 1 (71.63 seconds) /home/jenkins-build/build/workspace/ceph-pull-requests/qa> mypy . pid=2596252
mypy: FAIL ✖ in 1 minute 19.65 seconds
deadsymlinks: freeze /home/jenkins-build/build/workspace/ceph-pull-requests/qa> python -m pip freeze --all
deadsymlinks: pip==22.3.1,setuptools==65.6.3,wheel==0.38.4
deadsymlinks: commands[0] /home/jenkins-build/build/workspace/ceph-pull-requests/qa> bash -c '! (find . -xtype l | grep ^)'
  flake8: OK (10.03=setup[4.34]+cmd[5.69] seconds)
  mypy: FAIL code 1 (79.65=setup[8.02]+cmd[71.63] seconds)
  deadsymlinks: OK (4.04=setup[3.94]+cmd[0.10] seconds)
  evaluation failed :( (93.81 seconds)
```

**Comment by stefan-chivu** [comment]
jenkins test api

**Comment by petrutlucian94** [comment]
jenkins test api

**Pull request merged**
