### PR TITLE
civetweb: pull up to ceph-master

### PR DESCRIPTION
**Pull request by theanalyst**
Contains the following fixes
- absolute url fixes
- ssl socket closing fixes

Signed-off-by: Abhishek Lekshmanan <abhishek@suse.com>

- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by theanalyst** [comment]
testing branch with the prs cherry-picked, will update sha1 once we have it after merging the two prs.

**Comment by cbodley** [comment]
thanks @theanalyst. does this need to get in the next mimic release too?

**Comment by cbodley** [comment]
cc @yuriw

**Comment by theanalyst** [comment]
Yes preferably

**Comment by theanalyst** [comment]
test branch: http://pulpito.ceph.com/abhi-2019-02-20_09:05:32-rgw-civetweb-fixes-n-distro-basic-smithi/

**Comment by theanalyst** [comment]
Merged the 2 prs to ceph-master in civetweb and updated sha1 correspondingly

**Pull request merged**
