### PR TITLE
mimic: mon: test if gid exists in pending for prepare_beacon

### PR DESCRIPTION
**Pull request by batrick**
https://tracker.ceph.com/issues/35858

### CODE REVIEW

**Comment by yuriw** [comment]
[wip-yuri3-testing-2018-10-02-1639-mimic](https://trello.com/c/aDL8Gcgu/427-wip-yuri3-testing-2018-10-02-1639-mimic)

**Comment by yuriw** [comment]
[wip-yuri5-testing-2018-10-04-2213-mimic](https://trello.com/c/pzqPJek9/437-wip-yuri5-testing-2018-10-04-2213-mimic)

**Comment by neha-ojha** [comment]
@batrick I see `core` and `cephfs` labels on this PR. This has already passed `rados` testing, but is there any other suite that this PR needs to be tested with?

**Comment by batrick** [comment]
Putting this in core was a mistake. This should be tested with cephfs suites.

**Comment by yuriw** [comment]
[wip-yuri4-testing-2018-10-15-0002-mimic](https://trello.com/c/hEUw3v8h/440-wip-yuri4-testing-2018-10-15-0002-mimic)

**Comment by batrick** [comment]
`Reviewed-by: Patrick Donnelly <pdonnell@redhat.com>`

**Pull request merged**
