### PR TITLE
mgr: do not load disabled modules

### PR DESCRIPTION
**Pull request by tchaikov**
Fixes: https://tracker.ceph.com/issues/45147

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by tchaikov** [comment]
https://shaman.ceph.com/builds/ceph/wip-45147-kefu/5e18bbbde40d3c2c3f6258d7e4c235bf00f31132/

**Comment by tchaikov** [comment]
https://shaman.ceph.com/builds/ceph/wip-45147-kefu/64d4dbbfbc46b9d6b4f70a26a08e8c63b32d2479/

**Comment by tchaikov** [comment]
https://shaman.ceph.com/builds/ceph/wip-45147-kefu/26a95096a4064b1a34f54c01b0f2449d5221c794/

**Comment by tchaikov** [comment]
> Hm, what about mon commands that are exposed by disabled modules? are they still registered?

no, they are not anymore. as they are practically invisible from mgr if they are blacklisted.

**Comment by sebastian-philipp** [comment]
what about importing python dependencies in diskprediction_cloud only, if the module is active?

**Comment by tchaikov** [comment]
> seems good for now, we should have a bug open for the long term fix (whatever it ends up being) to get the disk prediction module working with 3.8 and later

@jdurgin how about keeping https://tracker.ceph.com/issues/45147 open after this changeset is merged?

**Comment by tchaikov** [comment]
- http://pulpito.ceph.com/kchai-2020-04-30_13:24:45-rados-wip-kefu-testing-2020-04-30-1835-distro-basic-smithi/
- http://pulpito.ceph.com/kchai-2020-05-01_04:25:09-rados-wip-kefu-testing-2020-04-30-1912-distro-basic-smithi/

**Pull request merged**
