### PR TITLE
jewel: rgw: meta sync thread crash at RGWMetaSyncShardCR

### PR DESCRIPTION
**Pull request by cbodley**
backport for http://tracker.ceph.com/issues/20346

### CODE REVIEW

**Comment by smithfarm** [comment]
Jenkins re-test this please

**Comment by smithfarm** [comment]
The job died or timeout on unittest_throttle.log

Jenkins re-test this please

**Comment by smithfarm** [comment]
@cbodley This passed an rgw suite at http://tracker.ceph.com/issues/20613#note-53

OK to merge as is, or do we need someone else to review?

**Comment by cbodley** [comment]
@yehudasa @oritwas can you please review?

**Pull request merged**
