### PR TITLE
pacific: qa: Fix test_subvolume_snapshot_info_if_orphan_clone

### PR DESCRIPTION
**Pull request by kotreshhr**
backport tracker: https://tracker.ceph.com/issues/57723

backport of https://github.com/ceph/ceph/pull/48642
parent tracker: https://tracker.ceph.com/issues/57446

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by dparmar18** [comment]
jenkins test api

**Comment by ljflores** [comment]
Rados suite review by @amathuria:

https://pulpito.ceph.com/?branch=wip-yuri10-testing-2022-11-28-1042-pacific

Failures:
    1. https://tracker.ceph.com/issues/53501 - Failure: [Errno 2] Cannot find file on the remote 'ubuntu@smithi187.front.sepia.ceph.com': 'rook/cluster/examples/kubernetes/ceph/operator.yaml'
    2. https://tracker.ceph.com/issues/44595 - src/test/osd/RadosModel.h: 1942: ceph_abort_msg("abort() called")
    3. https://tracker.ceph.com/issues/58114 - mon: FAILED ceph_assert(rank == new_rank)
    4. https://tracker.ceph.com/issues/58097 - qa/workunits/post-file.sh: kex_exchange_identification: read: Connection reset by peer
    5. https://tracker.ceph.com/issues/58046 - qa/workunits/rados/test_librados_build.sh: specify redirect in curl command
    6. https://tracker.ceph.com/issues/51372 - pacific: libcephsqlite: segmentation fault
    7. https://tracker.ceph.com/issues/54071 - rados/cephadm/osds: Invalid command: missing required parameter hostname(<string>)
    8. https://tracker.ceph.com/issues/58130 -- rados_api_tests: HEALTH_WARN: Degraded data redundancy: 1/5 objects degraded (20.000%), 1 pg degraded - Ceph - RADOS

**Comment by vshankar** [comment]
@kotreshhr - this still fails with @yuriw latest run: https://pulpito.ceph.com/yuriw-2022-11-29_22:33:39-fs-wip-yuri10-testing-2022-11-29-1005-pacific-distro-default-smithi/7097497/

**Review by vshankar — CHANGES_REQUESTED** [review]
PTAL at the failed run.

**Comment by kotreshhr** [comment]
This was still being failed with the usage of `clone\ snaps` as grep argument. Hence fixed it using `run.Raw()`. Hopefully this should pass this time.

**Comment by vshankar** [comment]
> This was still being failed with the usage of `clone\ snaps` as grep argument. Hence fixed it using `run.Raw()`. Hopefully this should pass this time.

Since this a qa only fix, could you rerun Yuri's test without building packages?

**Comment by kotreshhr** [comment]
> > This was still being failed with the usage of `clone\ snaps` as grep argument. Hence fixed it using `run.Raw()`. Hopefully this should pass this time.
> 
> Since this a qa only fix, could you rerun Yuri's test without building packages?

Converting the commands `args` to list did the trick!

http://pulpito.front.sepia.ceph.com/khiremat-2022-12-02_10:06:01-fs:volumes-wip-yuri10-testing-2022-11-29-1005-pacific-distro-default-smithi/

**Comment by dparmar18** [comment]
> > > This was still being failed with the usage of `clone\ snaps` as grep argument. Hence fixed it using `run.Raw()`. Hopefully this should pass this time.
> > 
> > 
> > Since this a qa only fix, could you rerun Yuri's test without building packages?
> 
> Converting the commands `args` to list did the trick!
> 
> http://pulpito.front.sepia.ceph.com/khiremat-2022-12-02_10:06:01-fs:volumes-wip-yuri10-testing-2022-11-29-1005-pacific-distro-default-smithi/

The second job failed with `Reduced data availability` warning, is this intermittent issue or need to teuthology ignore this warning?

**Comment by kotreshhr** [comment]
> > > > This was still being failed with the usage of `clone\ snaps` as grep argument. Hence fixed it using `run.Raw()`. Hopefully this should pass this time.
> > > 
> > > 
> > > Since this a qa only fix, could you rerun Yuri's test without building packages?
> > 
> > 
> > Converting the commands `args` to list did the trick!
> > http://pulpito.front.sepia.ceph.com/khiremat-2022-12-02_10:06:01-fs:volumes-wip-yuri10-testing-2022-11-29-1005-pacific-distro-default-smithi/
> 
> The second job failed with `Reduced data availability` warning, is this intermittent issue or need to teuthology ignore this warning?

This is a known issue and not related to the test in question. The test in question has passed.

```
2022-12-02T11:04:25.250 INFO:tasks.cephfs_test_runner:test_subvolume_snapshot_info_if_orphan_clone (tasks.cephfs.test_volumes.TestSubvolumeSnapshotClones) ... ok
```

**Comment by kotreshhr** [comment]
jenkins test make check

**Pull request merged**
