### PR TITLE
msg/async: harden error logic handle

### PR DESCRIPTION
**Pull request by yuyuyu101**
This pr don't fix any existing bug. Only fill up the potential error handle leak.

### CODE REVIEW

**Comment by yuyuyu101** [comment]
passed http://pulpito.ceph.com/haomai-2016-06-21_12:24:39-rados-wip-haomai-testing-distro-basic-smithi/

one test issue (fix later)
one vargind issue(rocksdb)
others all network connection errors(including dead jobs)

**Comment by yuyuyu101** [comment]
passed http://pulpito.ceph.com/haomai-2016-06-28_15:13:46-rados-wip-haomai-testing---basic-smithi

vargind issue (rocksdb)
dead job(ec test itself)
others(env problem)

**Comment by xiexingguo** [comment]
@yuyuyu101  Haomai, it seems this pr introduces a compiling error, check:

https://jenkins.ceph.com/job/ceph-pull-requests/8173/console

**Comment by yuyuyu101** [comment]
@xiexingguo yes, it's false rebase

**Comment by tchaikov** [comment]
@yuyuyu101 master is broken. mind taking a look?

```
CC table/plain_table_index.o
/srv/autobuild-ceph/gitbuilder.git/build/src/msg/async/AsyncMessenger.cc: In member function ‘virtual void AsyncMessenger::mark_down(const entity_addr_t&)’:
error: /srv/autobuild-ceph/gitbuilder.git/build/src/msg/async/AsyncMessenger.cc:810:13: no matching function for call to ‘AsyncConnection::stop()’
p->stop();
^
/srv/autobuild-ceph/gitbuilder.git/build/src/msg/async/AsyncMessenger.cc:810:13: note: candidate is:
```
see http://gitbuilder.sepia.ceph.com/gitbuilder-ceph-tarball-trusty-amd64-cmake/log.cgi?log=060b4920129e80ee1a80c33c71777d2d877dd0fc

**Comment by yuyuyu101** [comment]
@tchaikov yes, sorry for this https://github.com/ceph/ceph/pull/9992

**Pull request merged**
