### PR TITLE
pybind/rados: add alignment getter to IoCtx

### PR DESCRIPTION
**Pull request by bmflynn**
Adds alignment method to retrieve the pool alignment bytes for EC pools
to the existing IoCtx class.

Signed-off-by: Bruce Flynn <bmflynn@gmail.com>

### CODE REVIEW

**Comment by gregsfortytwo** [comment]
Makes sense to me. @tchaikov, do you know if there's any real test coverage we can add this to?

**Comment by bmflynn** [comment]
I do have tests which work using a `ceph/demo` docker container but I wasn't sure how they would integrate here, so I did not include them. Mostly I wasn't sure the best way to create an EC pool to test with.

https://github.com/bmflynn/ceph/commit/56bf6fee0802be8fc629a81d24fa7a99c0cc622d

**Comment by gregsfortytwo** [comment]
@bmflynn oh! If you just add that commit to the source, test_pybind is run in (I believe) both our "make check" and nightly teuthology suites. :)

**Comment by bmflynn** [comment]
@gregsfortytwo I've merged in the test code. Is there a simple way to run just the pybind tests?

**Comment by tchaikov** [comment]
@bmflynn you could try something like
```
PYTHONPATH=./build/lib/cython_modules/lib.2 nosetests --stop ../src/test/pybind/test_rados.py
```

**Comment by bmflynn** [comment]
Thanks @tchaikov

**Comment by bmflynn** [comment]
I ended up doing the following to run my specific tests because the `TestIoctx.test_aio_read` test seems to lock up on IO:
```
export  LD_LIBRARY_PATH=$PWD/lib 
export PYTHONPATH=./lib/cython_modules/lib.2 
nosetests -xv ../src/test/pybind/test_rados.py:TestIoctx.test_alignment
nosetests -xv ../src/test/pybind/test_rados.py:TestIoctxEc
```
The `TestIoctxEc` tests fail on setup because I can't figure out the correct JSON command structure to create an EC pool. I'm currently using this 
```
{'prefix': 'osd pool create', 'pg_num': 16,                       
 'pool': 'test_pool_ec', 'erasure_code_profile': 'default'}
```
which fails with "specified rule default doesn't exist".

Can anyone tell me what the correct command structure is?

**Comment by bmflynn** [comment]
Thanks @jdurgin, both tests are now working great!

**Comment by jdurgin** [comment]
@bmflynn looks good to me, could you just squash the extra commits down to one?

**Pull request merged**
