### PR TITLE
mds: optimize getattr file size

### PR DESCRIPTION
**Pull request by xxhdx1985126**
Fixes: http://tracker.ceph.com/issues/22925
Signed-off-by: "Yan, Zheng" <zyan@redhat.com>

### CODE REVIEW

**Comment by xxhdx1985126** [comment]
@ukernel This is your commit that fixes [http://tracker.ceph.com/issues/22925](url), thank you:-)

**Comment by xxhdx1985126** [comment]
jenkins retest this please

**Comment by tchaikov** [comment]
retest this please.

**Comment by ukernel** [comment]
please don't create RP for other people

**Comment by xxhdx1985126** [comment]
@ukernel 
Could you make a PR of this commit?
We really want to use this commit, however, without the approval of
the community, we won't have the courage to put this into our online
clusters.
Thank you:-)

**Comment by xxhdx1985126** [comment]
@ukernel 
I'm very sorry that I created this PR for your commit without your agreement:-)

**Pull request closed without merging**
