### PR TITLE
mount: add option to supports fake mounts in mount.ceph

### PR DESCRIPTION
**Pull request by nmshelke**
Fixes: https://tracker.ceph.com/issues/53903
Signed-off-by: Nikhilkumar Shelke <nshelke@redhat.com>

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by nmshelke** [comment]
jenkins retest this please

**Review by lxbsz — APPROVED** [review]

**Review by kotreshhr — APPROVED** [review]

**Comment by vshankar** [comment]
> Looks fine. It would have been nicer to move this to getopt_long instead of hand-parsing options, but it's not a huge problem here. Note that this won't understand the --fake flag though (if /bin/mount passes that through to the helper as-is).

This would be nice time to move to getopt_long IMO.

**Comment by nmshelke** [comment]
> > Looks fine. It would have been nicer to move this to getopt_long instead of hand-parsing options, but it's not a huge problem here. Note that this won't understand the --fake flag though (if /bin/mount passes that through to the helper as-is).
> 
> This would be nice time to move to getopt_long IMO.

Done

**Review by jtlayton — APPROVED** [review]
Much nicer!

**Review by vshankar — APPROVED** [review]

**Comment by vshankar** [comment]
https://tracker.ceph.com/projects/cephfs/wiki/Master#2022-Feb-09

**Pull request merged**
