### PR TITLE
rgw::lifecycle feature[rebase]

### PR DESCRIPTION
**Pull request by chenji-kael**
old PR was closed due to my git Erroneous operation, now it works well again: 
https://github.com/ceph/ceph/pull/7502

### CODE REVIEW

**Comment by chenji-kael** [comment]
@oritwas 
@yehudasa 
I hope this feature could be merge to master soon ,at least It will not cause rgw crush out, and seem work well at now ,someone has ask me to rebase it, as
his company want to use this patch too

**Comment by tchaikov** [comment]
@chenji-kael could you remove unrelated commits from your PR?

**Comment by tchaikov** [comment]
or you might want to target master instead, i think that's what @yehudasa was asking for.

**Comment by chenji-kael** [comment]
@tchaikov ok I will push PR to master

**Pull request closed without merging**
