### PR TITLE
spdk: pick up spdk v20.07

### PR DESCRIPTION
**Pull request by tchaikov**
## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by tchaikov** [comment]
```
	  7 - run-rbd-unit-tests-0.sh (Failed)
```

**Comment by tchaikov** [comment]
jenkins test make check

**Review by ddiss — CHANGES_REQUESTED** [review]
SPDK v20.07 contains 7dbdf87f63d8c8520570a61a53359967455790c3, so shouldn't we just set TARGET_ARCHITECTURE instead of patching here?

**Comment by tchaikov** [comment]
> SPDK v20.07 contains 7dbdf87f63d8c8520570a61a53359967455790c3, so shouldn't we just set TARGET_ARCHITECTURE instead of patching here?

@ddiss thank you David. but they are different things, `BUILD_CMD` is used for detecting the capabilities of the build host, while `TARGET_ARCHITECTURE` is used for compiling the SPDK libraries.

but yes, changing `BUILD_CMD` does not help with the portability of generated binaries. i updated the changeset to use `--target-arch` option instead.

could you take another look?

**Review by ddiss — COMMENTED** [review]
I don't think I understand the provenance of the new 178291a516fa21ce61a2b7cf4c5b5cd3295be30c spdk HEAD . We were previously at 06d09c1108b16197ea985ae4d67867ed672a1e18 , which was upstream 4cc2d1d814ff41b4c1b9894c603b13b7d926075b plus Nathan's `-march=core2` change. Given that `configure --target-arch=...` makes Nathan's patch unnecessary, shouldn't the spdk HEAD just be moving to the upstream v20.07 tag, i.e. 1a527e501f810e2b39b9862c96f3e8bdc465db80 ?

**Comment by tchaikov** [comment]
> shouldn't the spdk HEAD just be moving to the upstream v20.07 tag, i.e. 1a527e501f810e2b39b9862c96f3e8bdc465db80 ?

@ddiss yes, fixed and repushed.

**Comment by tchaikov** [comment]
cc @rouming

**Comment by rouming** [comment]
> cc @rouming

Yep, looks good to me. The only minor note I have is can you please reorder commits:
        spdk: pick up spdk v20.07 …
        blk/spdk: remove nvme retry count option from NVMEDevice …
and make "blk/spdk: remove nvme retry count option from NVMEDevice …" the first one?

This will eliminate a compilation error if your HEAD is "spdk: pick up...". So firstly "fix" goes and then actual new version.

**Comment by tchaikov** [comment]
> > cc @rouming
> 
> Yep, looks good to me. The only minor note I have is can you please reorder commits:
> spdk: pick up spdk v20.07 …
> blk/spdk: remove nvme retry count option from NVMEDevice …
> and make "blk/spdk: remove nvme retry count option from NVMEDevice …" the first one?
> 
> This will eliminate a compilation error if your HEAD is "spdk: pick up...". So firstly "fix" goes and then actual new version.

@rouming reordered, PTAL.

**Review by ddiss — APPROVED** [review]
LGTM.
One minor nit, but nothing I feel strongly about:
- `nvmf` and other NVMe Over Fabrics dependencies should probably be enabled via a separate commit in https://github.com/ceph/ceph/pull/36768

**Comment by tchaikov** [comment]
> LGTM.
> One minor nit, but nothing I feel strongly about:
> 
> * `nvmf` and other NVMe Over Fabrics dependencies should probably be enabled via a separate commit in #36768

no, they are not "enabled". they are libraries built from SPDK. the job of cmake/modules/BuildSPDK.cmake is to define all the built libraries and to ready them with their dependencies if any, so they can be consumed by any potential targets.

**Comment by ddiss** [comment]
> > nvmf and other NVMe Over Fabrics dependencies should probably be enabled via a separate commit in #36768

> no, they are not "enabled". they are libraries built from SPDK. the job of cmake/modules/BuildSPDK.cmake is to define all the built libraries and to ready them with their dependencies if any, so they can be consumed by any potential targets.

Okay, thanks, looks like I have a lot to learn when it comes to cmake.

**Comment by tchaikov** [comment]
https://shaman.ceph.com/builds/ceph/wip-kefu-testing-2020-08-28-1132/b7344f809b03c5463c1f729e9371fcd9cef8408b/

**Comment by tchaikov** [comment]
- https://pulpito.ceph.com/kchai-2020-08-28_06:18:09-rados-wip-kefu-testing-2020-08-28-1247-distro-basic-smithi/
- https://pulpito.ceph.com/kchai-2020-08-28_13:09:24-rados-wip-kefu-testing-2020-08-28-1247-distro-basic-smithi/

**Comment by tchaikov** [comment]
> I think removal of a config option deserves a release note, otherwise LGTM.

IIUC, SPDK backend is still experimental. so i didn't update the release note. but added anyway. 

@neha-ojha could you take another look?

**Review by ddiss — APPROVED** [review]

**Comment by tchaikov** [comment]
@neha-ojha ping?

**Review by neha-ojha — APPROVED** [review]

**Pull request merged**
