### PR TITLE
jewel: rbd: rbd crashes during map

### PR DESCRIPTION
**Pull request by shinobu-x**
http://tracker.ceph.com/issues/21866

### CODE REVIEW

**Comment by shinobu-x** [comment]
test this please

**Comment by shinobu-x** [comment]
test this please

**Comment by Carbenium** [comment]
Any chance we could get this into the next point release?

**Comment by smithfarm** [comment]
test this please

**Comment by smithfarm** [comment]
retest this please

**Comment by smithfarm** [comment]
retest this please

**Comment by smithfarm** [comment]
This PR is included in the integration run at: http://tracker.ceph.com/issues/21742#note-13

So far, one rbd suite with 78 jobs passed. Another one, with 154 jobs, is scheduled.

**Comment by smithfarm** [comment]
RBD integration run passed at http://tracker.ceph.com/issues/21742#note-13

**Pull request merged**
