### PR TITLE
mgr/cephadm: fix removing offline hosts with ingress daemons

### PR DESCRIPTION
**Pull request by adk3798**
We need to convert the daemon type to service type here or we'll try to access the "haproxy" or "keepalived" index of the cephadm_services dictionary, which doesn't have those keys (but does have an "ingress" key)

Fixes: https://tracker.ceph.com/issues/58537

Signed-off-by: Adam King <adking@redhat.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [x] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Review by rkachach — COMMENTED** [review]
LGTM

**Comment by adk3798** [comment]
https://pulpito.ceph.com/adking-2023-01-22_23:00:58-orch:cephadm-wip-adk-testing-2023-01-22-1523-distro-default-smithi/

lots of failures from infra stuff (re-imaging machines, installing things pre-test) so did a rerun of all failed and dead jobs, resulting in

https://pulpito.ceph.com/adking-2023-01-23_04:36:45-orch:cephadm-wip-adk-testing-2023-01-22-1523-distro-default-smithi/

Leaving us with 6 failures.

- 3 failed jobs were the new `test_set_mon_crush_locations` test introduced in one of the PRs in the run. The test just isn't quite right yet, but it's not relevant in terms of whether we can merge other PRs
- 2 instances of the staggered upgrade test issue (known issue) https://tracker.ceph.com/issues/58535
- 1 instance of failing to install container selinux package (known issue) https://tracker.ceph.com/issues/57771

Overall, nothing that would block merging for anything other than the mon crush location PR.

**Comment by adk3798** [comment]
jenkins test api

**Review by rkachach — APPROVED** [review]

**Review by phlogistonjohn — APPROVED** [review]
Very straightforward. LGTM.

**Pull request merged**
