### PR TITLE
mgr/dashboard: Wrong capitalization of image and pool variables for embedded rbd-details dashboard

### PR DESCRIPTION
**Pull request by juan-ferrer-toribio**
Fixes: https://tracker.ceph.com/issues/67849

The Performance tab of the dashboard is passing the `pool` and `image` variables to the Grafana iframe with the first letter in uppercase, but in the `monitoring/ceph-mixin/dashboards_out/rbd-details.json` dashboard file they are defined in lowercase, this causes them not to be recognized and the graphics display _No data_.

Example of current (wrong) generated URL:

`https://mycephdashboard.com/d/eRtdGrFfgT/rbd-details?var-Pool=pve_rbd_ssd&var-Image=base-501-disk-0 &refresh=5s&var-datasource=Dashboard1&kiosk&from=now-1h&to=now&orgId=1`

It should be:

`https://mycephdashboard.com/d/eRtdGrFfgT/rbd-details?var-pool=pve_rbd_ssd&var-image=base-501-disk-0 &refresh=5s&var-datasource=Dashboard1&kiosk&from=now-1h&to=now&orgId=1`

_Note that the `var-Image` and `var-Pool` URL variables have the first letter capitalized._

This is happening in all versions of ceph.

image

A workaround for this bug for a running production cluster could be rename the variables in the corresponding dashboard file.

```
sed -i \
    -e 's/\$image/\$Image/g' \
    -e 's/"name": "image"/"name": "Image"/g' \
    -e 's/\$pool/\$Pool/g' \
    -e 's/"name": "pool"/"name": "Pool"/g' \
    monitoring/ceph-mixin/dashboards_out/rbd-details.json
```

### CODE REVIEW

**Review by afreen23 — APPROVED** [review]
LGTM @aaSharma14 can you please have a look at this too ?

**Review by aaSharma14 — APPROVED** [review]
LGTM.!

**Comment by afreen23** [comment]
jenkins test api

**Comment by nizamial09** [comment]
@juan-ferrer-toribio thanks for the contribution. I think this will require a backport so could you please create a tracker and attach it to the commit message with `Fixes: <tracker-url>`

**Comment by juan-ferrer-toribio** [comment]
Sorry @nizamial09 I still don't have a tracker account, I've created it but I'm still waiting for administrator aproval.

**Comment by cloudbehl** [comment]
@juan-ferrer-toribio you can use this tracker for now. https://tracker.ceph.com/issues/67849

**Comment by juan-ferrer-toribio** [comment]
> @juan-ferrer-toribio you can use this tracker for now. https://tracker.ceph.com/issues/67849

@nizamial09 Done, @cloudbehl please fix URLs and image on the tracker issue since they are wrong.

**Comment by afreen23** [comment]
Hey ,

Can we squash into one commit and we follow some guidelines for [commit message](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst#commit-title).
The commit title seems missing now.

Here is an [example](https://github.com/ceph/ceph/pull/59510/commits/1b006f47b8f8fe6de9983126988fafd12c361e8e) too.

Thanks

**Comment by juan-ferrer-toribio** [comment]
Moving to #59575, I hope everything is okey now.

**Pull request closed without merging**
