### PR TITLE
ceph-disk: use /sys/dev/block/maj:min/partition to see if partition

### PR DESCRIPTION
**Pull request by trociny**
Fixes: #12706
Signed-off-by: Mykola Golub <mgolub@mirantis.com>

### CODE REVIEW

**Comment by dachary** [comment]
It is related to #5584 which has a partial implementation

**Comment by liewegas** [comment]
Reviewed-by:

**Comment by dachary** [comment]
@trociny could you please re-open a pull request against infernalis ? The context changed slightly but your patch should be good. With that you will also be able to run the ceph-disk suite to validate it works.

**Comment by trociny** [comment]
Re-opened against infernalis as #5728.

**Pull request closed without merging**
