### PR TITLE
osd: fix race condition during send_failures

### PR DESCRIPTION
**Pull request by xiexingguo**
http://tracker.ceph.com/issues/13869

### CODE REVIEW

**Comment by tchaikov** [comment]
@xiexingguo shall we create a pull request targeting master first and then backport it to infernalis and hammer?

and i think it would be better if you could put what you fixed in the comment instead of the symptom or what you found. what do you think?

@dachary i see you changed http://tracker.ceph.com/issues/13821 to "Pending Backport", but i failed to find the change in master, am i missing anything?

**Comment by xiexingguo** [comment]
@tchaikov You may check https://github.com/ceph/ceph/pull/6638 for the original fix to see why I directly patch it to infernalis here. Besides, I add the extra fast check against empty failure_queue logic as @dzafman's kindly advisemnet.

**Comment by xiexingguo** [comment]
And @tchaikov, remove the extra commit as you suggested, please review.

**Comment by liewegas** [comment]
Reviewed-by: David Zafman <dzafman@redhat.com>
Reviewed-by: Sage Weil <sage@redhat.com>

**Comment by dachary** [comment]
> You may check #6638 for the original fix to see why I directly patch it to infernalis here. 

@xiexingguo because it is uncommon for a backport to not be cherry-picked, it needs to be explained in full in the commit message. Could you do that please ? The explanation must contain precise references (the commits that are backported) as well as the rationale for doing a standalone backport instead of a simple cherry-pick -x. 

I'm sorry that this additional administrative burden is imposed on you. It really helps with maintaining the backports in a clean state. 

Thanks for your understanding.

**Comment by xiexingguo** [comment]
@dachary .I’d like to, but I don't quite understand what do you mean. Can you make an example for what does the correct commit message looks like?

**Comment by xiexingguo** [comment]
@dachary  How about this:


OSD: fix race condition during send_failures
Backported from commit 5135292d9557269bab5cefc98d39606174aa6ebe
Fixes: #13869
Backport: hammer, infernalis
Signed-off-by: xie xingguo <xie.xingguo@zte.com.cn>
Reviewed-by: David Zafman <dzafman@redhat.com>
Reviewed-by: Sage Weil <sage@redhat.com>

**Comment by dachary** [comment]
@xiexingguo 5135292 is a merge that contains multiple commits, could you include the sha1 of the commit you backported ?

**Comment by xiexingguo** [comment]
@dachary Well, the original commit I pulled is https://github.com/xiexingguo/ceph/commit/b3a4bc6317681a0327d00e680bea339b8a1ccc59. But when sage told me to rebase, I found this fix has already been resolved by a previous merge 5135292d9557269bab5cefc98d39606174aa6ebe. I just get this message from the commit history-- https://github.com/ceph/ceph/commits/master/src/osd/OSD.cc , so I am unable to found any further information about this problem.

**Comment by dachary** [comment]
@xiexingguo the commits from the 5135292 merge that relate to the send_failures() function can be displayed with:

<pre>
git log -L:send_failures:src/osd/OSD.cc --patch 5135292d9557269bab5cefc98d39606174aa6ebe^1..5135292d9557269bab5cefc98d39606174aa6ebe^2
commit 39c1495406cce3f24c427a3d7a53fb7b26a509c9
Author: Sage Weil <sage@redhat.com>
Date:   Tue Sep 29 21:03:53 2015 -0400

    osd: protect mon reporting with mon_report_lock
    
    We need an exclusive lock over paths that update state related to
    mon reports, lest they step on fields like up_thru_*, *stats_ack*,
    last_mon_report, and so on.  Everybody still needs a read lock
    on map_lock too to get a stable OSDMap epoch.
    
    Signed-off-by: Sage Weil <sage@redhat.com>

diff --git a/src/osd/OSD.cc b/src/osd/OSD.cc
--- a/src/osd/OSD.cc
+++ b/src/osd/OSD.cc
@@ -4783,18 +4790,19 @@
 void OSD::send_failures()
 {
   assert(map_lock.is_locked());
+  assert(mon_report_lock.is_locked());
   Mutex::Locker l(heartbeat_lock);
   utime_t now = ceph_clock_now(cct);
   while (!failure_queue.empty()) {
     int osd = failure_queue.begin()->first;
     entity_inst_t i = osdmap->get_inst(osd);
     if (!failure_pending.count(osd)) {
       int failed_for = (int)(double)(now - failure_queue.begin()->second);
       monc->send_mon_message(new MOSDFailure(monc->get_fsid(), i, failed_for,
 					     osdmap->get_epoch()));
       failure_pending[osd] = make_pair(failure_queue.begin()->second, i);
     }
     failure_queue.erase(osd);
   }
 }
 

commit 8b5b6c85cc6225d961debfb98621927fc50e81b5
Author: Guang Yang <yguang@yahoo-inc.com>
Date:   Tue Sep 22 20:59:28 2015 +0000

    osd: move the monitor report to OSD::tick_without_osd_lock
    
    Fixes: #12722
    Reviewed-by: Guang Yang <yguang@yahoo-inc.com>

diff --git a/src/osd/OSD.cc b/src/osd/OSD.cc
--- a/src/osd/OSD.cc
+++ b/src/osd/OSD.cc
@@ -4773,18 +4782,18 @@
 void OSD::send_failures()
 {
-  assert(osd_lock.is_locked());
+  assert(map_lock.is_locked());
   Mutex::Locker l(heartbeat_lock);
   utime_t now = ceph_clock_now(cct);
   while (!failure_queue.empty()) {
     int osd = failure_queue.begin()->first;
     entity_inst_t i = osdmap->get_inst(osd);
     if (!failure_pending.count(osd)) {
       int failed_for = (int)(double)(now - failure_queue.begin()->second);
       monc->send_mon_message(new MOSDFailure(monc->get_fsid(), i, failed_for,
 					     osdmap->get_epoch()));
       failure_pending[osd] = make_pair(failure_queue.begin()->second, i);
     }
     failure_queue.erase(osd);
   }
 }
 

commit c9534dfb15a595387f2daf2795fa03e6330efb7b
Author: Sage Weil <sage@redhat.com>
Date:   Thu Sep 17 21:45:16 2015 -0400

    osd: do not send dup failure reports
    
    If a failure report is already pending, we do not need to resend
    it.
    
    Signed-off-by: Sage Weil <sage@redhat.com>

diff --git a/src/osd/OSD.cc b/src/osd/OSD.cc
--- a/src/osd/OSD.cc
+++ b/src/osd/OSD.cc
@@ -4739,16 +4739,18 @@
 void OSD::send_failures()
 {
   assert(osd_lock.is_locked());
   Mutex::Locker l(heartbeat_lock);
   utime_t now = ceph_clock_now(cct);
   while (!failure_queue.empty()) {
     int osd = failure_queue.begin()->first;
-    int failed_for = (int)(double)(now - failure_queue.begin()->second);
     entity_inst_t i = osdmap->get_inst(osd);
-    monc->send_mon_message(new MOSDFailure(monc->get_fsid(), i, failed_for,
-					   osdmap->get_epoch()));
-    failure_pending[osd] = make_pair(failure_queue.begin()->second, i);
+    if (!failure_pending.count(osd)) {
+      int failed_for = (int)(double)(now - failure_queue.begin()->second);
+      monc->send_mon_message(new MOSDFailure(monc->get_fsid(), i, failed_for,
+					     osdmap->get_epoch()));
+      failure_pending[osd] = make_pair(failure_queue.begin()->second, i);
+    }
     failure_queue.erase(osd);
   }
 }
 

commit 865ddcac41069f7857a3066b3b04a5c62cc1db8c
Author: Sage Weil <sage@redhat.com>
Date:   Thu Sep 17 21:48:30 2015 -0400

    osd: resend pending failure reports with a new mon session
    
    Signed-off-by: Sage Weil <sage@redhat.com>

diff --git a/src/osd/OSD.cc b/src/osd/OSD.cc
--- a/src/osd/OSD.cc
+++ b/src/osd/OSD.cc
@@ -4722,16 +4739,16 @@
 void OSD::send_failures()
 {
   assert(osd_lock.is_locked());
   Mutex::Locker l(heartbeat_lock);
   utime_t now = ceph_clock_now(cct);
   while (!failure_queue.empty()) {
     int osd = failure_queue.begin()->first;
     int failed_for = (int)(double)(now - failure_queue.begin()->second);
     entity_inst_t i = osdmap->get_inst(osd);
     monc->send_mon_message(new MOSDFailure(monc->get_fsid(), i, failed_for,
 					   osdmap->get_epoch()));
-    failure_pending[osd] = i;
+    failure_pending[osd] = make_pair(failure_queue.begin()->second, i);
     failure_queue.erase(osd);
   }
 }
 

commit b3ca828ae8ebc9068073494c46faf3e8e1443ada
Author: Sage Weil <sage@redhat.com>
Date:   Thu Sep 17 21:42:53 2015 -0400

    osd: fix send_failures() locking
    
    It is unsafe to check failure_queue.empty() without the lock.
    
    Signed-off-by: Sage Weil <sage@redhat.com>

diff --git a/src/osd/OSD.cc b/src/osd/OSD.cc
--- a/src/osd/OSD.cc
+++ b/src/osd/OSD.cc
@@ -4722,20 +4722,16 @@
 void OSD::send_failures()
 {
   assert(osd_lock.is_locked());
-  bool locked = false;
-  if (!failure_queue.empty()) {
-    heartbeat_lock.Lock();
-    locked = true;
-  }
+  Mutex::Locker l(heartbeat_lock);
   utime_t now = ceph_clock_now(cct);
   while (!failure_queue.empty()) {
     int osd = failure_queue.begin()->first;
     int failed_for = (int)(double)(now - failure_queue.begin()->second);
     entity_inst_t i = osdmap->get_inst(osd);
-    monc->send_mon_message(new MOSDFailure(monc->get_fsid(), i, failed_for, osdmap->get_epoch()));
+    monc->send_mon_message(new MOSDFailure(monc->get_fsid(), i, failed_for,
+					   osdmap->get_epoch()));
     failure_pending[osd] = i;
     failure_queue.erase(osd);
   }
-  if (locked) heartbeat_lock.Unlock();
 }
 
</pre>

they are the commits that you backported. Could you please explain in the commit message why they could not be cherry-picked and how you adapted them ?

**Comment by xiexingguo** [comment]
@dachary 
OSD: fix race condition during send_failures
The original pull request is https://github.com/ceph/ceph/pull/6638, which is overridden by a batch commit 5135292d9557269bab5cefc98d39606174aa6ebe, and the related commit finally resolves the same problem is b3ca828ae8ebc9068073494c46faf3e8e1443ada. Because b3ca828ae8ebc9068073494c46faf3e8e1443ada somewhat  underestimates the severity and is not considered as a bug, it's needed to be made trackable and backported here alone. 
Fixes: #13869
Backport: hammer, infernalis
Signed-off-by: xie xingguo <xie.xingguo@zte.com.cn>
Reviewed-by: David Zafman <dzafman@redhat.com>
Reviewed-by: Sage Weil <sage@redhat.com>

Well, loic, please review... btw,  I really have a difficult time  to get through "cherry-picked" as I never use git before.

**Comment by tchaikov** [comment]
@xiexingguo you are adding a comment in the pull request, instead updating your commit message:

you can 
1. ```git cherry-pick -x b3ca828ae8ebc9068073494c46faf3e8e1443ada``` in a clean infernalis branch to cherry-pick Sage's commit.
1. add the change suggested by @dzafman 
1. explain the difference between your change and the cherry-picked version **in the commit message**. (i just confirmed that the empty() of rb tree implemented by GCC is atomic.)

**Comment by xiexingguo** [comment]
@tchaikov Thank you for your reminder. I just want to get confirmation from Loic before I really update the commit message, you know, to avoid the  noise from bot:))

**Comment by dachary** [comment]
@xiexingguo since the suggested change from @dzafman is not yet in master, you can skip it for the purpose of this backport and just do the clean
<pre>
git cherry-pick -x b3ca828ae8ebc9068073494c46faf3e8e1443ada
</pre>
suggested by @tchaikov. You can then make a separate pull request on master to add the if(queue empty) improvement before the lock. And this can be backported separately. It may seem like a detail but we are careful to not implement things in hammer for which there is no equivalent in master, unless there is a good reason to.

Thanks for your patience with this :-) It turns out that this backport is going to be simple after all !

**Comment by xiexingguo** [comment]
@dachary No problem, I'll do it once I am available.

**Comment by xiexingguo** [comment]
@dachary Done.

**Comment by tchaikov** [comment]
@xiexingguo could you also add the "`Fixes: #13869`" line at the end of the commit message? thanks.

**Comment by xiexingguo** [comment]
@tchaikov Added:))

**Comment by dzafman** [comment]
@dachary @xiexingguo I withdraw my suggestion of adding an empty() check before the lock.  Strictly speaking an STL container doesn't guarantee thread safety.  While it might work in this particular case of empty()  for std::map, depending on the container it might break.

**Comment by dachary** [comment]
@dzafman if there is a risk that it breaks, should an issue be open to fix it in master ?

**Comment by dzafman** [comment]
@dachary Sage fixed all issues with b3ca828ae8ebc9068073494c46faf3e8e1443ada in master.

**Comment by xiexingguo** [comment]
@dachary And I did not add any pending pull request for the fast check against empty failure_queue too.

**Comment by dachary** [comment]
It passed a run of the hammer rados suite ( see http://tracker.ceph.com/issues/13750#note-14 for details ), except for rados/singleton-nomsgr/{all/11429.yaml} which also is breaks in various ways on the infernalis branch. Note that all valgrind tests in these suites fail because of an environmental problem ( http://tracker.ceph.com/issues/14664 ). The upgrade/infernalis suite also passes ( http://tracker.ceph.com/issues/13750#note-15 ) except for "radosgw-admin -n client.0 user create" errors ( http://tracker.ceph.com/issues/14665 ) which I believe to be unrelated.

**Pull request merged**
