### PR TITLE
cmake: check for aligned_alloc() instead of checking tcmalloc version

### PR DESCRIPTION
**Pull request by tchaikov**
see also https://bugzilla.redhat.com/show_bug.cgi?id=1494309

### CODE REVIEW

**Comment by tchaikov** [comment]
@dillaman it's the follow-up of https://github.com/ceph/ceph/pull/17788#issuecomment-338665710

**Comment by tchaikov** [comment]
retest this please.

**Comment by dillaman** [comment]
... adding ```-nostdlib``` helped for me:

> /usr/bin/ld: /tmp/ccZ56GEj.o: undefined reference to symbol 'aligned_alloc@@GLIBC_2.16'

**Comment by tchaikov** [comment]
> This doesn't seem to work in my Fedora 26 environment.

@dillaman weird ... did you remove your `CMakeCache.txt` before rerunning `cmake`. i tested with gperftools master HEAD and 2.5.93, it works.  tcmalloc 2.5.93 should assert in `free()` , because the memory chunk is not allocated by it.

anyway, i updated the code to mimic the scenario of rocksdb . hopefully it will work for you.

if it don't, i will just add `-nostdlib`.

**Comment by dillaman** [comment]
@tchaikov w/ the updated commit, it fails regardless if I have the broken or fixed gperftools RPMs installed

**Comment by tchaikov** [comment]
@dillaman thanks for testing. i just fixed a typo stdlib.h => stdlib.h

**Comment by dillaman** [comment]
@tchaikov both the bad and good RPMs are now permitted

**Comment by tchaikov** [comment]
@dillaman fixed and repushed. i have no idea why the "bad" RPM passes w/o debugging it in a fc26 env. probably will leave it for a boring week-end.

**Comment by dillaman** [comment]
@tchaikov Thanks -- latest commit works for me now:

bad RPMs:
> -- Performing Test HAVE_ALIGNED_ALLOC - Failed

good RPMs:
> -- Performing Test HAVE_ALIGNED_ALLOC - Success

**Comment by dillaman** [comment]
@tchaikov ... of course, the second I type "works for me", Jenkins reports that it failed on tcmalloc 2.4

**Comment by tchaikov** [comment]
changelog

- do `check_aligned_alloc()` only if tcmalloc's version is greater than 2.5

**Comment by tchaikov** [comment]
@dillaman i moved the cmake cleanup stuff into #18576. hopefully it'd be easier to review.

**Pull request merged**
