### PR TITLE
jewel: common: Improve linux dcache hash algorithm

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/17600

### CODE REVIEW

**Comment by smithfarm** [comment]
[(SES4) Bug 1005179 - Performance fix is missing in SES4](https://trello.com/c/Jy6slUtt/2093-ses4-bug-1005179-performance-fix-is-missing-in-ses4)

**Comment by dachary** [comment]
jenkins test this please

**Comment by dachary** [comment]
what happens if I just comment ?

**Comment by dachary** [comment]
oh, it triggers a round of checking for some reason

**Comment by dachary** [comment]
@smithfarm could you please rebase against jewel-next ? A number of backports have been merged since the last check and it would be good to get another make check with a more recent rebase.

**Comment by dachary** [comment]
jenkins test this please (jenkins general failure)

**Comment by alfredodeza** [comment]
jenkins test this please

**Comment by alfredodeza** [comment]
jenkins test this please

**Comment by dachary** [comment]
@tchaikov does this backport look good to merge ? It passed the rados (http://tracker.ceph.com/issues/17851#note-4) suite. It also passed the upgrade/jewel-x and upgrade/hammer-x (http://tracker.ceph.com/issues/17851#note-7) suites, except for one job which should be fixed by https://github.com/ceph/ceph-qa-suite/pull/1256 and does not seem related to this pull request. Note that it won't be included in 10.2.4, reason why it targets jewel-next.

**Comment by dachary** [comment]
@tchaikov ping

**Comment by tchaikov** [comment]
@dachary sorry for the latency, lgtm.

**Pull request merged**
