### PR TITLE
osd/OpRequest: fix op event's duration calculation error 

### PR DESCRIPTION
**Pull request by rosinL**
In TrakedOp.h, 'throttled' event is before 'header_read' event,
but the order is not consistent within message receive process,
it caused op event's duration calculation error.
Adjust the event order and use request recv_stamp (header_read event start time)
as the trakedOp initiate time stamp.

Fixes: https://tracker.ceph.com/issues/61226

Signed-off-by: luo rixin <luorixin@huawei.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by rosinL** [comment]
jenkins retest this please

**Comment by rosinL** [comment]
jenkins retest this please

**Comment by rosinL** [comment]
jenkins test make check

**Comment by rosinL** [comment]
jenkins test make check

**Comment by rosinL** [comment]
@rzarzynski please take a review, thanks

**Comment by rzarzynski** [comment]
Argh, duplicative with fresher https://tracker.ceph.com/issues/61388. That's a result of crunching a backlog from newer-to-older. Apologies, @rosinL.

**Comment by rosinL** [comment]
It is ok @rzarzynski, I close this

**Pull request closed without merging**
