### PR TITLE
librbd: retry ENOENT in V2_REFRESH_PARENT as well

### PR DESCRIPTION
**Pull request by idryomov**
## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [x] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by idryomov** [comment]
jenkins test make check

**Review by chrisphoffman — COMMENTED** [review]
What was your thought process on MAX_ENOENT_RETRIES = 10?

**Review by chrisphoffman — APPROVED** [review]
LGTM

**Comment by idryomov** [comment]
> What was your thought process on MAX_ENOENT_RETRIES = 10?

For V2_REFRESH_PARENT case, 1 is definitely enough.  However, for V2_GET_SNAPSHOTS case, if a bunch of snapshots are being removed at the same time, it can legitimately "lose" on the first retry and two or three would be needed.  I went with 10 to err on the safe side, as previously the number of retries in V2_GET_SNAPSHOTS wasn't limited at all.

**Comment by idryomov** [comment]
No related failures:

https://pulpito.ceph.com/dis-2022-09-05_22:46:00-rbd-wip-dis-testing-distro-default-smithi/
https://pulpito.ceph.com/dis-2022-09-06_09:14:15-rbd-wip-dis-testing-distro-default-smithi/

**Pull request merged**
