### PR TITLE
octopus: erasure-code: enable isa-l EC for aarch64 platform

### PR DESCRIPTION
**Pull request by smithfarm**
Any objections to this backport?

### CODE REVIEW

**Review by tchaikov — APPROVED** [review]

**Review by neha-ojha — APPROVED** [review]

**Comment by a16bitsysop** [comment]
When building the isa directory for aarch64 on alpine Linux it fails the alpine checks as it has textrel in libec_isa.so

```
>>> ERROR: ceph-base*: Found textrels:
3395TEXTREL  /builds/a16bitsysop/aports/community/ceph/pkg/ceph-base/usr/lib/ceph/erasure-code/libec_isa.so
```

**Comment by tchaikov** [comment]
@a16bitsysop this PR has been merged. i think a better way to fix it is to either create a PR or file a tracker ticket. also, i don't think disabling the SIMD based optimization is the right way to fix this issue.

**Comment by a16bitsysop** [comment]
@tchaikov I already did a tracker ticket here https://tracker.ceph.com/issues/48681
I tried a few variations to get it to compile here
https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/15899/pipelines

It was the last resort to disable it and I thought the authors of the merge request would know where the textrel’s were.

As mentioned in the tracker ticket if I do a CMakeLists.txt for the aarch64 directory scanelf shows no issues, I can’t compile it locally at the minute.

**Comment by a16bitsysop** [comment]
The one thing I didn’t try is remove
`PROPERTIES COMPILE_FLAGS "-D__ASSEMBLY__"`

from src/erasure-code/isa/CMakeLists.txt

As I was not sure of the consequences

**Comment by tchaikov** [comment]
@a16bitsysop you might want to send a mail to ceph-devel and copy the original author of #32171.

**Comment by a16bitsysop** [comment]
@tchaikov ok thanks, will try that.

**Pull request merged**
