### PR TITLE
luminous: rgw: ability to list bucket contents in unsorted order for efficiency

### PR DESCRIPTION
**Pull request by ivancich**
https://tracker.ceph.com/issues/24916

rgw: ability to list bucket contents in unsorted order for efficiency

luminous backport of https://github.com/ceph/ceph/pull/21026

Add the ability to list the contents of a bucket without the results
being sorted. This can have performance benefits since all bucket
shards do not need to be queried. This is done by adding a parameter
to the REST query string (i.e., "allow_unordered" [note underscore]
for swift or "allow-unordered" [note hyphen] for s3) to true.

This works with other request parameters such as marker, end_marker,
and prefix. But it does not work when delimeter is used. Also, because
the results are not in order, a subsequent marker may precede an
earlier marker.

Signed-off-by: J. Eric Ivancich ivancich@redhat.com

### CODE REVIEW

**Comment by ivancich** [comment]
teuthology results on rgw suite: http://pulpito.ceph.com/ivancich-2018-05-03_18:44:44-rgw-wip-rgw-unordered-luminous-distro-basic-smithi/

**Comment by ivancich** [comment]
@mattbenjamin @cbodley Should we move this along?

**Comment by cbodley** [comment]
@ivancich is there a tracker ticket for the backport? cc @smithfarm

**Comment by ivancich** [comment]
@cbodley I created a tracker -- https://tracker.ceph.com/issues/24916

**Comment by yuriw** [comment]
[wip-yuri-testing-2018-07-30-2054-luminous](https://trello.com/c/A4bkWiei/358-wip-yuri-testing-2018-07-30-2054-luminous)

**Pull request merged**
