### PR TITLE
pybind,doc: build stub using cython and build API doc with RTD

### PR DESCRIPTION
**Pull request by tchaikov**
because we used to create a kludge "libXYZ.so" that contained no-op symbols for all undefined symbols from the Cython-generated binding and we can't do that in the RTD build environment.

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by tchaikov** [comment]
jenkins test make check

**Comment by tchaikov** [comment]
jenkins test api

**Comment by tchaikov** [comment]
https://ceph--38431.org.readthedocs.build/en/38431/rados/api/python/

**Comment by dillaman** [comment]
@tchaikov Is there a quick primer / background about why we need to change? Is it just because we used to create a kludge "libXYZ.so" that contained no-op symbols for all undefined symbols from the Cython-generated binding and we can't do that in the RTD build environment?

**Comment by tchaikov** [comment]
@dillaman yes, i've explored more than 4 approaches. none of them works. the most promising one was https://github.com/readthedocs/sphinx-autoapi, but it does not support cython yet.

**Comment by tchaikov** [comment]
jenkins test make check

**Comment by dillaman** [comment]
Is it possible to always build the "mock" library somehow so that we don't need to wait for a read-the-doc test to inevitably note that someone forgot to add a function to the mock backing file? I think that's my only major concern about this change.

**Comment by tchaikov** [comment]
@dillaman yes, in https://github.com/ceph/ceph/pull/38431/commits/73c5f36cf77798f657b455b3b685b03cfc908703 ("admin/build-doc: do not build stub C binding anymore"), i switched our `admin/build-doc` script to use the "mock" library implemented using Cython instead of the nm + awk based code generation approach. in the "Docs: build check" jenkins job of this PR is actually using this new solution introduced in this changeset.

**Comment by tchaikov** [comment]
- https://pulpito.ceph.com/kchai-2020-12-04_09:24:21-rados-wip-kefu-testing-2020-12-04-1516-distro-basic-smithi/
- https://pulpito.ceph.com/kchai-2020-12-05_08:42:04-rados-wip-kefu-testing-2020-12-05-1217-distro-basic-smithi/

**Comment by tchaikov** [comment]
rebased against master.

**Comment by tchaikov** [comment]
@jdurgin @neha-ojha ping?

**Comment by neha-ojha** [comment]
> @jdurgin @neha-ojha ping?

@tchaikov this is on my list, will try to get to it tomorrow

**Review by neha-ojha — APPROVED** [review]
I understand this change is invasive but required, LGTM. @dillaman @cbodley @batrick might want to take a look.

**Review by batrick — APPROVED** [review]
cephfs changes are fine with me

**Review by dillaman — APPROVED** [review]
RBD changes lgtm

**Pull request merged**
