### PR TITLE
async: fixed coredump when enable dpdk.

### PR DESCRIPTION
**Pull request by liupan1111**
Signed-off-by: Pan Liu <pan.liu@istuary.com>

### CODE REVIEW

**Comment by liupan1111** [comment]
After upgrade to dpdk v16.11, async will coredump when enable dpdk

**Comment by liupan1111** [comment]
@yuyuyu101 @optimistyzy , please help take look.

**Comment by optimistyzy** [comment]
Since DPDK is upgrade, so I do not think that we need to consider the versioning.

**Comment by tchaikov** [comment]
> Since DPDK is upgrade, so I do not think that we need to consider the versioning.

we detect DPDK in `Finddpdk.cmake`, i don't see why we don't need to take the backward compatibility into consideration.

**Comment by liupan1111** [comment]
@tchaikov In my opinion, we don't need to specify the dpdk version in code, dpdk is already a submodule in ceph code, the user should use conrresponding submodule to build. What do you think?

**Comment by optimistyzy** [comment]
I have the same opinion,each ceph version  should uses the corresonding dpdk,which shown in submodulesit can avoid the compatibility issue

**Comment by tchaikov** [comment]
> the user should use conrresponding submodule to build.

i doubt it. at least, we are not forcing our user to do this. if we really want to enforce the dpdk version to 16.11 or up used in ceph, we can bump the minimum required version in #12857. but anyway, maybe we can let @yuyuyu101 to make the call.

**Comment by liupan1111** [comment]
@tchaikov @yuyuyu101 , sorry for lack of info, let me say more about the coredump. 
In the function PerfCountersBuilder::create_perf_counters, it will loop each perf counter, and check whether it none: assert(d->type != PERFCOUNTER_NONE);
If we don't remove #if RTE_VERSION < RTE_VERSION_NUM(16,7,0,0), and use dpdk 16.11, assertion fail will happen.

**Comment by tchaikov** [comment]
@liupan1111 got it, then we might need to conditionalize the 
```c++
enum {
  l_dpdk_dev_first = 58800,
  l_dpdk_dev_rx_mcast,
  l_dpdk_dev_rx_total_errors,
  l_dpdk_dev_tx_total_errors,
  l_dpdk_dev_rx_badcrc_errors,
  l_dpdk_dev_rx_dropped_errors,
  l_dpdk_dev_rx_nombuf_errors,
  l_dpdk_dev_last
};
```
block also.

**Pull request merged**
