### PR TITLE
cmake: include(SIMDExt) in src/CMakeLists.txt

### PR DESCRIPTION
**Pull request by tchaikov**
as we need to check HAVE_ARMV8_CRC in src/CMakeLists.txt.

Signed-off-by: Kefu Chai <kchai@redhat.com>

### CODE REVIEW

**Comment by tchaikov** [comment]
retest this please.

**Comment by alimaredia** [comment]
lgtm!

**Comment by dmick** [comment]
Was on PTO until today.  looking.  1) where does the included module come from so I can see what it does?  2) failing tests?

**Comment by alimaredia** [comment]
@dmick the module comes from ceph/cmake/module (https://github.com/ceph/ceph/blob/master/cmake/modules/SIMDExt.cmake).  @tchaikov told me on IRC that the aarch64 build is back to normal after breaking because of a previous SIMDExt refactor.

**Comment by dmick** [comment]
retest this please

**Pull request merged**
