### PR TITLE
pybind/mgr/volumes: log mutex locks to help debug deadlocks

### PR DESCRIPTION
**Pull request by kotreshhr**
This patch logs the mutex locks which were missed logging as part of the commit cf2a1ad65120. Refer [1] for more details.

[1] https://tracker.ceph.com/issues/49605#note-5
Signed-off-by: Kotresh HR <khiremat@redhat.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [x] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by kotreshhr** [comment]
jenkins test make check arm64

**Comment by kotreshhr** [comment]
jenkins test make check arm64

**Review by vshankar — APPROVED** [review]

**Comment by vshankar** [comment]
So, I'm not sure what is breaking fs:volumes test - https://pulpito.ceph.com/vshankar-2023-08-16_13:07:33-fs:volumes-wip-vshankar-testing-20230816.105627-testing-default-smithi/

(wait for an update on this)

**Comment by vshankar** [comment]
> So, I'm not sure what is breaking fs:volumes test - https://pulpito.ceph.com/vshankar-2023-08-16_13:07:33-fs:volumes-wip-vshankar-testing-20230816.105627-testing-default-smithi/
> 
> (wait for an update on this)

Tests pass -- issue related to PR #52892

**Comment by vshankar** [comment]
@kotreshhr No need to rush backport since this is for debug only, yes?

**Comment by kotreshhr** [comment]
> @kotreshhr No need to rush backport since this is for debug only, yes?

@vshankar I thought of the same. Now, I am think it's good to backport as it makes debugging easier. wdyt?

**Comment by vshankar** [comment]
> > @kotreshhr No need to rush backport since this is for debug only, yes?
> 
> @vshankar I thought of the same. Now, I am think it's good to backport as it makes debugging easier. wdyt?

Agree - let's backport it.

**Pull request merged**
