### PR TITLE
[osd/pg]:change default value of osd_allow_recovery_below_min_size to false

### PR DESCRIPTION
**Pull request by shenhang**
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by shenhang** [comment]
We encountered a sceneria. we scaled up the ceph cluster, added some osds in. Some osds switched between up and down frequently, when data was being rebalanced. After all osds were stable, some pgs were under min-size ,peerd and backfilling. They were not available. There is one common point between these unavailable pgs that osds in the upset after scale-up is totally different from before.   
Assuming a pg with up set [1,2,3] and up set [4,5,6] after scale-up. 2,3 suddenly fail down when data was rebalanced. Then the acting set would be [1] and the up set would be [4,5,6]. The pg would be peered and backfilling. When 2 and 3 became up ,the pg would not be peering again. And the pg ,size of whose acting set is below minsize, would not be available。
So I think this parameter should be default set to false.

**Comment by gregsfortytwo** [comment]
Can you provide more details on how this happens? In general, I'd expect leaving this setting as-is to provide more reliable availability and ESPECIALLY durability, because without it a PG will not be able to recover from going down to a single copy. If you've actually lost the other replicas, that is very bad.

It's also not clear to me from the scenario you've described why a PG starting backfill would prevent it from going active with the old set. I'd expect the new primary to realize it has full copies available on the old nodes, put them into the temp acting set, and move on with life.

**Comment by shenhang** [comment]
> Can you provide more details on how this happens? In general, I'd expect leaving this setting as-is to provide more reliable availability and ESPECIALLY durability, because without it a PG will not be able to recover from going down to a single copy. If you've actually lost the other replicas, that is very bad.
> 
> It's also not clear to me from the scenario you've described why a PG starting backfill would prevent it from going active with the old set. I'd expect the new primary to realize it has full copies available on the old nodes, put them into the temp acting set, and move on with life.

we also changed the pg number when data was rebalancing, and many osds were switching between from up and down.

**Comment by gregsfortytwo** [comment]
I wasn't clear. I mean, can you demonstrate why the OSDs weren't assigning new acting sets and primaries correctly?

I would like to identify the actual cause of the issue, because the config setting you're changing here shouldn't cause the issues you've described on its own, and changing the default *will* cause worse behavior for clusters in different situations than whatever you've seen here.

**Comment by shenhang** [comment]
> I wasn't clear. I mean, can you demonstrate why the OSDs weren't assigning new acting sets and primaries correctly?
> 
> I would like to identify the actual cause of the issue, because the config setting you're changing here shouldn't cause the issues you've described on its own, and changing the default _will_ cause worse behavior for clusters in different situations than whatever you've seen here.

Check the example I mentioned above. Assuming a pg with up set [1,2,3] and up set [4,5,6] after scale-up. 2,3 suddenly fail down when data was being rebalanced. Then the acting set would be [1] and the up set would be [4,5,6]. The pg would be peered and backfilling.Then the acting set of only useful past_interval was [1]，When 2 and 3 became up again ,the pg can only picked the osd from the acting [1].So the size of acting set is definitely below minsize。

**Comment by gregsfortytwo** [comment]
You shouldn't get an acting set of [1] unless you have a min_size of 1, though.
With a min_size of 2, the PG should backfill to [4,5,6] but then when 2 and 3 come up, it can do an acting [1,2,3] since [1] accepted no writes.

I understand that apparently didn't happen, but the bug is not that it started recovery from a single replica. The bug is whatever prevented it from going active with [1,2,3] after those OSDs came back and there were no new writes. It's possible this happened because you did a pg split/merge and the peering code doesn't deal with that when acting sets change.

**Comment by shenhang** [comment]
> You shouldn't get an acting set of [1] unless you have a min_size of 1, though.
> With a min_size of 2, the PG should backfill to [4,5,6] but then when 2 and 3 come up, it can do an acting [1,2,3] since [1] accepted no writes.
> 
> I understand that apparently didn't happen, but the bug is not that it started recovery from a single replica. The bug is whatever prevented it from going active with [1,2,3] after those OSDs came back and there were no new writes. It's possible this happened because you did a pg split/merge and the peering code doesn't deal with that when acting sets change.

Ok, get it .So is there a patch to deal with the situation?

**Comment by gregsfortytwo** [comment]
Unfortunately, AFAIK nobody else has reported this bug so nobody's had a chance to diagnose the full cause and repair it.

**Comment by shenhang** [comment]
> Unfortunately, AFAIK nobody else has reported this bug so nobody's had a chance to diagnose the full cause and repair it.

Thanks.

**Pull request closed without merging**
