### PR TITLE
ceph-volume: update functional testing

### PR DESCRIPTION
**Pull request by guits**
various changes for fixing ceph-volume functional testing. cleaning up deploy.yml (drop py2 references)

Signed-off-by: Guillaume Abrioux <gabrioux@ibm.com>
(cherry picked from commit 90bfaaa2f0ab7e28c0f78189ccb83635e944e758) (cherry picked from commit bf448e3f637f8c8e42f095b1b5ff709e3633dc11)

### CODE REVIEW

**Comment by guits** [comment]
jenkins test ceph-volume all

**Comment by guits** [comment]
jenkins test make check

**Review by yuriw — APPROVED** [review]

**Comment by yuriw** [comment]
jenkins retest this please

**Comment by guits** [comment]
jenkins test ceph-volume batch centos-bluestore-mixed_type

**Comment by guits** [comment]
jenkins test ceph-volume lvm centos-bluestore-dmcrypt

**Comment by guits** [comment]
jenkins test ceph-volume lvm centos-bluestore-create

**Comment by guits** [comment]
jenkins test ceph-volume batch centos-bluestore-single_type_dmcrypt

**Comment by guits** [comment]
jenkins test ceph-volume batch centos-bluestore-single_type

**Comment by guits** [comment]
jenkins test ceph-volume batch centos-bluestore-mixed_type_dmcrypt_explicit

**Comment by guits** [comment]
jenkins test ceph-volume batch centos-bluestore-mixed_type_dmcrypt

**Comment by guits** [comment]
jenkins test ceph-volume batch centos-bluestore-mixed_type_explicit

**Pull request merged**
