### PR TITLE
rgw/dbstore: allow NULL RealmIDs in sqlite schema

### PR DESCRIPTION
**Pull request by cbodley**
when radosgw starts up without a realm, it creates a 'default' zone and zonegroup with no associated realm. update the DBConfigStore to support NULL RealmIDs for this case

Fixes: https://tracker.ceph.com/issues/59639

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by cbodley** [comment]
cc @alimaredia

**Review by dang — APPROVED** [review]

**Review by soumyakoduri — APPROVED** [review]

**Comment by dang** [comment]
This didn't fix the issue for me.  I still get these errors:

2023-05-08T14:30:55.869-0400 7fb22b0caf00  1 rgw main: dbconfig:sqlite:read_default_realm evaluation failed: no more rows available (dbstore:sqlite:101)
statement:
2023-05-08T14:30:55.883-0400 7fb22b0caf00  1 rgw main: dbconfig:sqlite:read_zone_by_name evaluation failed: no more rows available (dbstore:sqlite:101)
statement:
2023-05-08T14:30:55.885-0400 7fb22b0caf00  0 rgw main: failed to create zone with (5) Input/output error
2023-05-08T14:30:55.885-0400 7fb22b0caf00  0 rgw main: failed to create default zone: (5) Input/output error
2023-05-08T14:30:55.885-0400 7fb22b0caf00  0 rgw main: failed to load zone: (5) Input/output error
2023-05-08T14:30:55.886-0400 7fb22b0caf00 -1 Couldn't init storage provider (RADOS)


Did I miss something?

**Comment by cbodley** [comment]
> Did I miss something?

oops! sounds like i got it working, but forget to clear the old schema before retesting the final version in the PR. i'll retest and update

**Comment by dang** [comment]
Removing the existing db fixed it.

**Comment by cbodley** [comment]
passed qa in https://pulpito.ceph.com/cbodley-2023-05-08_18:30:09-rgw-wip-59639-distro-default-smithi/

dbstore run uses `rgw config store = dbstore` successfully: http://qa-proxy.ceph.com/teuthology/cbodley-2023-05-08_18:30:09-rgw-wip-59639-distro-default-smithi/7267034/teuthology.log

**Comment by alimaredia** [comment]
@soumyakoduri @dang I just remembered, shouldn't we also remove the OSDs and the MGR from the dbstore [clusters.yaml](https://github.com/ceph/ceph/blob/main/qa/suites/rgw/dbstore/cluster.yaml#L2) to ensure the tests are running standalone?

**Comment by alimaredia** [comment]
> > @soumyakoduri @dang I just remembered, shouldn't we also remove the OSDs and the MGR from the dbstore [clusters.yaml](https://github.com/ceph/ceph/blob/main/qa/suites/rgw/dbstore/cluster.yaml#L2) to ensure the tests are running standalone?
> 
> i'm not sure how well the `ceph` task will behave if it doesn't have any osds or mgrs, but that's certainly worth trying

Not well it seems:  http://qa-proxy.ceph.com/teuthology/amaredia-2023-05-10_17:15:53-rgw:dbstore-main-distro-default-smithi/7269964/teuthology.log

**Comment by cbodley** [comment]
try adding a `wait-for-healthy: false` override to the ceph task

**Pull request merged**
