### PR TITLE
[DNM] qa: whitelist "mon_osd_down_out_interval" health warning

### PR DESCRIPTION
**Pull request by tchaikov**
Signed-off-by: Kefu Chai <kchai@redhat.com>

### CODE REVIEW

**Comment by tchaikov** [comment]
this addresses most of the "'wait_until_healthy' reached maximum tries (150) after waiting for 900 seconds" failures in http://pulpito.ceph.com/kchai-2017-07-21_02:43:22-rados-wip-kefu-testing-distro-basic-smithi/

**Comment by tchaikov** [comment]
hmm, but i think this warning should go away after we restore the setting.

```
2017-07-21 03:00:48.848867 7f2d0ff01700  0 mon.c@2(peon) e1 handle_command mon_command({"injected_args": ["--mon_osd_down_out_interval 600"], "prefix": "injectargs"} v 0) v1
...
2017-07-21 03:01:04.497697 7f2d0ff01700 20 mon.c@2(peon).health dump:{
    "quorum_health": {
        "mon.0": {},
        "mon.1": {},
        "mon.2": {
            "OSD_NO_DOWN_OUT_INTERVAL": {
                "severity": "HEALTH_WARN",
                "summary": "mon%plurals% %names% %hasorhave% mon_osd_down_out_interval set to 0",
                "detail": [
                    "mon.c has mon_osd_down_out_interval set to 0"
                ]
            }
        }
    },
    "leader_health": {}
}
```

but it stayed with us. see /a/kchai-2017-07-21_02:43:22-rados-wip-kefu-testing-distro-basic-smithi/1426235/remote/smithi078/log/ceph-mon.c.log.gz

this does not look right.

**Comment by xiexingguo** [comment]
> /a/kchai-2017-07-21_02:43:22-rados-wip-kefu-testing-distro-basic-smithi/1426235/remote/smithi078/log/ceph-mon.c.log.gz

Try to taking a look at the log, but I am unable to extract it :-(
Will do some local test to see if I can reproduce this

**Comment by tchaikov** [comment]
@xiexingguo #16477 should address this issue

**Pull request closed without merging**
