### PR TITLE
Get rid of TCMALLOC_MAX_TOTAL_THREAD_CACHE_BYTES environment

### PR DESCRIPTION
**Pull request by aclamk**
Now instead of giving TCMALLOC_MAX_TOTAL_THREAD_CACHE_BYTES
one can set "osd memory thread cache bytes" and get it done.

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by markhpc** [comment]
@aclamk this is fantastic!  Let me try giving it a spin to verify it's working properly, but otherwise this looks great!  I don't know if RGW uses the prioritycache yet but we can work on that too.

**Comment by leseb** [comment]
How does this behave if `TCMALLOC_MAX_TOTAL_THREAD_CACHE_BYTES` is set and we use ` "osd memory thread cache bytes"`, which takes precedence?

**Comment by mattbenjamin** [comment]
> 
> 
> @aclamk this is fantastic! Let me try giving it a spin to verify it's working properly, but otherwise this looks great! I don't know if RGW uses the prioritycache yet but we can work on that too.

Why should it?

**Comment by aclamk** [comment]
@leseb 
TCMALLOC_MAX_TOTAL_THREAD_CACHE_BYTES is used on tcmalloc initialization.
"osd memory thread cache bytes" is used in main(), so it overwrites previous value.

**Comment by aclamk** [comment]
@markhpc 
Listing in from PriorityCache, but I can be also added to "heap" commands. Should it?

**Comment by aclamk** [comment]
@markhpc
Do we need testing of this change, or will it be enough just to observe
```
   "bluestore-pricache": {
        "target_bytes": 4294967296,
        "mapped_bytes": 194625536,
        "unmapped_bytes": 27295744,
        "heap_bytes": 221921280,
        "max_threadcache_bytes": 80740352,
        "current_threadcache_bytes": 2681520,
        "cache_bytes": 2845415832
    },
``` ?

**Comment by markhpc** [comment]
@aclamk yeah, probably.  I don't think etiher the MDS or RGW use the priority cache, but I'm hoping maybe we can get folks on board.

@mattbenjamin So I have sort of a love-hate relationship with tcmalloc.  One of the nice things it does give you is the ability to figure out how much memory a process has mapped and then through a combination of those statistics and periodically releasing memory you can do a semi-reasonable job of keeping the mapped memory for the process under a certain threshold.  For containers that ends up being a big deal because often you are setting some upper bound for how much the container should be able to use.  The prioritycache code basically does this by figuring out how much memory you generically have available for caches and then divvying that memory up to each cache based on some policy.  Right now the policy is pretty static/simplistic, but long term the goal is to balance memory based on the relative age of each cache competing for that memory.  This is really important for the OSD for instance, when determining how much memory should go to onode cache and how much memory should go to rocksdb block cache (for onodes).  IE we want very different ratios depending on if the workload is RBD or if the workload is RGW, and it may be that the same cluster is serving both workloads over different time spans so we want the whole thing to be dynamic rather than static.

As far as RGW goes, the primary benefit would probably be that the user would no longer be required to set the rgw_cache_lru_size explicitly.  We'd look at something like the "rgw_memory_target" and trim the lru to make sure that the overall RGW mapped memory stays under a threshold to keep it there.  Or if we were to shard that cache, the aggregate memory used by all shards would be trimmed to stay under that threshold.

**Comment by markhpc** [comment]
> @markhpc
> Do we need testing of this change, or will it be enough just to observe
> 
> ```
>    "bluestore-pricache": {
>         "target_bytes": 4294967296,
>         "mapped_bytes": 194625536,
>         "unmapped_bytes": 27295744,
>         "heap_bytes": 221921280,
>         "max_threadcache_bytes": 80740352,
>         "current_threadcache_bytes": 2681520,
>         "cache_bytes": 2845415832
>     },
> ``` ?
> ```

Oh, this just made me realize, we should probably decide if we want environment variables to take precidence over the ceph.conf supplied value and (perhaps?) inform the user where the current value came from.  What do you think?

Otherwise I think the perf counter is sufficient for testing.

**Comment by vumrao** [comment]
cc @vumrao

**Comment by liewegas** [comment]
Can we move this into common_init so that we can use it for any daemon type?

**Comment by liewegas** [comment]
Also, we should include patches that (1) remove this from cephadm's container environment, and (2) remove it from the init scripts.

**Comment by aclamk** [comment]
@markhpc Can we add this topic to the next ceph performance weekly?

**Comment by markhpc** [comment]
@aclamk added!

**Pull request closed without merging**
