### PR TITLE
pacific: os/bluestore: separate omap per-pool vs per-pg alerts

### PR DESCRIPTION
**Pull request by liewegas**
backport #40341

Currently the health alert raised does not match the docs, and the docs
do not describe what the health alert indicates.

Octopus added per-pool omap storage.  This improves space accounting
and reporting.

Pacific added per-pg omap storage (object hash in key).  This speeds up
PG removal.

Separate everthing out into two distinct alerts raised from bluestore
and surfaced as health alerts, with corresponding config options to
disable, and update the docs accordingly.

Also update the fsck options for warn vs error, and raise separate
errors for the per-pg and per-pool cases.

Signed-off-by: Sage Weil <sage@newdream.net>
(cherry picked from commit f755e353e88b65fb923289464935ec635daf13b2)

### CODE REVIEW

**Review by ifed01 — APPROVED** [review]

**Comment by neha-ojha** [comment]
jenkins test make check

**Comment by neha-ojha** [comment]
make check failure is https://tracker.ceph.com/issues/48850

**Comment by neha-ojha** [comment]
jenkins test make check

**Comment by liewegas** [comment]
jenkins test make check

**Comment by neha-ojha** [comment]
jenkins test make check

**Pull request merged**
