### PR TITLE
reef: mon,cephfs: require confirmation flag to bring down unhealthy MDS

### PR DESCRIPTION
**Pull request by rishabh-d-dave**
**BACKPORTS 3 related trackes together**

* backport tracker: https://tracker.ceph.com/issues/65927
  * parent tracker: https://tracker.ceph.com/issues/61866
  * PR https://github.com/ceph/ceph/pull/56066

* backport tracker https://tracker.ceph.com/issues/66198
  * parent tracker https://tracker.ceph.com/issues/65864
  * PR #57493

* backport tracker https://tracker.ceph.com/issues/66409
  * parent tracker https://tracker.ceph.com/issues/65841
  * PR #57333
  
---

this backport was staged using ceph-backport.sh version 16.0.0.6848
find the latest version at https://github.com/ceph/ceph/blob/main/src/script/ceph-backport.sh

---

updated using ceph-backport.sh version 16.0.0.6848

### CODE REVIEW

**Review by anthonyeleven — APPROVED** [review]

**Comment by rishabh-d-dave** [comment]
@leonid-s-usov make check passed.

**Comment by rishabh-d-dave** [comment]
> @leonid-s-usov make check passed.

ping

**Comment by rishabh-d-dave** [comment]
@leonid-s-usov 
> @leonid-s-usov make check passed.

ping

**Review by joscollin — APPROVED** [review]

**Comment by joscollin** [comment]
Tested in https://tracker.ceph.com/issues/66468

**Comment by lxbsz** [comment]
@rishabh-d-dave This PR caused the [qa test failure](https://pulpito.ceph.com/jcollin-2024-06-26_02:20:03-fs-wip-jcollin-testing-20240625.103903-reef-distro-default-smithi/7772702), it seems you didn't backport the dependency commit:

```
commit 29610577eece04c028c412f112a66fafa8f70316
Author: Venky Shankar <vshankar@redhat.com>
Date:   Mon Jul 24 00:33:47 2023 -0400

    mds: add mdlog trimming threshold and decay counter
    
    Fixes: http://tracker.ceph.com/issues/61908
    Signed-off-by: Venky Shankar <vshankar@redhat.com>
```

**Pull request merged**
