### PR TITLE
qa/tests: Changed rhel7.4 to rhel7.5

### PR DESCRIPTION
**Pull request by yuriw**
Note: This is a temp fix till we get $ implementaion

Signed-off-by: Yuri Weinstein <yweinste@redhat.com>

### CODE REVIEW

**Comment by djgalloway** [comment]
I haven't created a RHEL7.5 OVH image yet.  Do I need to?

**Comment by yuriw** [comment]
@djgalloway Yes pls !

**Comment by vasukulkarni** [comment]
@djgalloway If ovh image is difficult, then we can run on mira instead.

**Comment by djgalloway** [comment]
OVH image is done

**Comment by vasukulkarni** [comment]
@yuriw lets merge this after the runs are green!

**Pull request merged**
