### PR TITLE
osd:fill_in_one_address's not retry on pick_address.cc

### PR DESCRIPTION
**Pull request by renhwztetecs**
If the server node starts, cluster network configuration and OSD process simultaneously, so some of the OSD boot failure.
Add：Retry in function “fill_in_one_address” find cluster network

Fixes: #12696
Signed-off-by: ren.huanwen@zte.com.cn

### CODE REVIEW

**Comment by liewegas** [comment]
It seems like the right way to fix this is to make systemd or sysvinit start ceph *after* the network is up.  Do you know why that wasn't possible here?  Possibly because of udev triggering the OSD process before networking was configured?

I'm hoping that with systemd we can have the problem solved there, but I'm not quite sure since the udev rules will explicitly do a systemctl start ceph-osd@123, and i'm not sure if the After/Wants stuff will work.  @osynge do you know?

**Comment by renhwztetecs** [comment]
@liewegas 
We are using the centos7
"Ceph service" using the Sysvinit start, as you can see in the Sysvinit ahead of ceph startup sequence is the "Network service"
But the operating system can start Systemd "avahi - daemon service" set the IP address of the front-end ports, while the "avahi - daemon service" relationship with ceph service startup without order

**Comment by renhwztetecs** [comment]
Do not rule out is udev to trigger the osd process
If we need to use udev to trigger the osd process, so how to guarantee the startup sequence, but also ensure the osd process before the mon process can begin?

**Comment by liewegas** [comment]
On Mon, 17 Aug 2015, renhwztetecs wrote:
> Do not rule out is udev to trigger the osd process
> If we need to use udev to trigger the osd process, so how to guarantee the startup sequence, but also ensure the osd process before the mon
> process can begin?

Hmm, when the blanket 'service ceph start' service runs, it should run 
'ceph-disk activate-all' which will catch any OSDs that didn't start 
from udev.  See 
https://github.com/ceph/ceph/blob/master/src/init-ceph.in#L494

**Comment by renhwztetecs** [comment]
@liewegas 
In Pick_address functional modules to increase many times to find the IP address of the available functions, is advantageous to the Ceph in different environment, different operating systems in the deployment and use。

In centos. 7 to use ceph - deploy deployed ceph, ceph. Service will be automatically added to the
SysV services for system after the restart, ceph automatic loading services.
. Why don't the ceph service automatically added to the Systemd service, because at present most of the startup services in Systemd?

thank you！

**Comment by liewegas** [comment]
@renhwztetecs proper systemd support is coming in infernalis, although i'm not certain this case is properly handled yet.  But it still seems like this is a service startup issue, and sleeping in the network config is an awkward workaround.

In your environmnet, doesn't the ceph-disk activate-all catch these cases?

**Comment by renhwztetecs** [comment]
@liewegas

**Comment by liewegas** [comment]
Ah, I just noticed the bug in the tracker.  Let's debug this there!

**Pull request closed without merging**
