### PR TITLE
mon: add an "osd crush dump tree" command

### PR DESCRIPTION
**Pull request by tchaikov**
* to print crush items in a tree

Fixes: #11833
Signed-off-by: Kefu Chai <kchai@redhat.com>

### CODE REVIEW

**Comment by cmgitdream** [comment]
maybe you forget to add the 'ceph crush dump tree' information into man pages;
the content printed by 'crush dump tree' is a subset of 'crush dump', this is somewhat confusing, 
since the user may think the differences only lie in the output format,  
so suggest that they both print the same content, just in different formats (plain vs. tree), 
similar to 'ceph osd df {plain/tree}'

**Comment by tchaikov** [comment]
@cmgitdream , thanks for your review.

> maybe you forget to add the 'ceph crush dump tree' information into man pages;

will do.

> the content printed by 'crush dump tree' is a subset of 'crush dump', this is somewhat confusing, 
since the user may think the differences only lie in the output format,

agreed, it's confusing.

> so suggest that they both print the same content, just in different formats (plain vs. tree), 
similar to 'ceph osd df {plain/tree}'

i assume 

- we need to keep the behaviour of "ceph osd crush dump" unchanged. in addition to listing the buckets and items, it also prints out the device map, type map, rules, and tunables.
- and also we need to offer user with a "tree view" of the buckets in the crush.

the symmetric "plain" and "tree" commands are appealing. but if user is expecting a tree view of buckets reachable from the root, what the value of offering her the device map, type map or the rules?

**Comment by cmgitdream** [comment]
@tchaikov 
tree view of buckets is good, but the command should be modified.
change 'ceph osd crush dump tree' to 'ceph osd crush tree' is more clearly ?

**Comment by liewegas** [comment]
> @tchaikov
> tree view of buckets is good, but the command should be modified.
> change 'ceph osd crush dump tree' to 'ceph osd crush tree' is more clearly ?

:+1:

**Comment by tchaikov** [comment]
@cmgitdream @liewegas , thanks for your review.  the latest pull request should address your comments.

**Comment by cmgitdream** [comment]
looks good to me,
Reviewed-by: Min Chen <minchen@ubuntukylin.com>

**Comment by yuyuyu101** [comment]
Add result format check in unittest to keep user side custom monitor program compatible?

**Comment by tchaikov** [comment]
@yuyuyu101 will pipe it thru `xmlstarlet` to print out, for example, the OSD ids under the root bucket. if this is what you are expecting. and, this is a new command, so i assume your intention is to ensure that the changes in future related to this command will not fail our user's scripts due to format change?

**Comment by yuyuyu101** [comment]
Exactly, I recently meet some upgrade problem related to cli format. I hope we can make it compatible for new feature

**Comment by tchaikov** [comment]
> Exactly, I recently meet some upgrade problem related to cli format.

thanks. then i will see if we can have it checked with a tool which understands DTD or equivalent.

**Comment by tchaikov** [comment]
@yuyuyu101 test added. could you take a look again? thanks.

**Comment by tchaikov** [comment]
@yuyuyu101 ping ?

**Comment by yuyuyu101** [comment]
COOL! LGTM

**Comment by tchaikov** [comment]
thanks @yuyuyu101, since i added a file into the source tree. will push this pr to a wip branch to get it tested by gitbuilders.

**Pull request merged**
