### PR TITLE
osd: fix inaccurate counter and skip over queueing an empty transaction

### PR DESCRIPTION
**Pull request by xiexingguo**
This PR consists of two changes:

the first change tries to fix counter for batch transactions triggered to remove non-meta objects, this is problematic because that we may skip some meta objects which shall not be  counted since they are not really queued. Besides, the counter itself is not very accurate, e.g., if we set osd_target_transaction_size to 30, we may actually queue 31 transactions to trigger a commit.

the second change tries to skip over an empty transaction(especially we have to wait for its finish), which is for the sake of performance.

### CODE REVIEW

**Comment by xiexingguo** [comment]
@liewegas Mind having a look at this one?  Thanks:)

**Comment by xiexingguo** [comment]
@liewegas Append more fixes and ping.

**Comment by liewegas** [comment]
Can you move the map sharing into a separate PR?  I'm not sure those are a good idea, since it will make the receiving OSD pull those maps from the monitor.  The rest looks good!

**Comment by xiexingguo** [comment]
@liewegas  Done.  Move those two changes into https://github.com/ceph/ceph/pull/8117

**Pull request merged**
