### PR TITLE
kraken: core: improve control and throttling of the snap trimmer

### PR DESCRIPTION
**Pull request by gregsfortytwo**
Fixes: http://tracker.ceph.com/issues/19329

### CODE REVIEW

**Comment by gregsfortytwo** [comment]
The jewel version (much more complicated) was reviewed and merged in https://github.com/ceph/ceph/pull/14492/. This one hasn't gone through any integration testing so needs that, but should be fine.

**Comment by smithfarm** [comment]
Needs rebase (please remove DNM when the conflict is gone)

**Comment by gregsfortytwo** [comment]
@smithfarm, rebased.

**Comment by smithfarm** [comment]
@gregsfortytwo This PR is included in the latest `wip-kraken-backports` upon which I scheduled a `upgrade/jewel-x` run. That run [1] has quite some failures that say "failed to complete snap trimming before timeout" that were not appearing in the previous runs. 

[1] http://pulpito.ceph.com/smithfarm-2017-04-20_19:15:47-upgrade:jewel-x-wip-kraken-backports-distro-basic-vps/

**Comment by smithfarm** [comment]
@gregsfortytwo That run doesn't include a bunch of new commits I just added to #14612

**Comment by gregsfortytwo** [comment]
*sigh*
Just searching that string in my email, it's popping up pretty frequently in upgrade tests to master as well. My best guess is the VPS machines are just taking too long and we'd have to bump up the fatal timeout value. Or we could drop this test, or ignore it on upgrade/vps runs.

@smithfarm, any preferences?

**Comment by smithfarm** [comment]
> any preferences?

My preference would be to fix the tests. I opened master PR #14811 and jewel backport #14812 - these double the timeout from 600 to 1200 seconds. Let me know if you think that's too much, or too little.

Also, I merged Sage's PendingReleaseNotes change - could you please rebase and remove DNM.

Then I'll repopulate the integration branch and do another round of tests.

**Comment by smithfarm** [comment]
Testing at #14813

**Comment by smithfarm** [comment]
Jenkins re-test this please

**Comment by smithfarm** [comment]
@gregsfortytwo The make check failure has hopefully been fixed by #16069 - could you please rebase to pick it up?

**Comment by tchaikov** [comment]
retest this please.

**Comment by smithfarm** [comment]
@gregsfortytwo Nevermind; in the meantime I learned that Jenkins merges the PR into the latest version of the base branch.

**Comment by smithfarm** [comment]
@jdurgin This passed a rados suite at http://tracker.ceph.com/issues/19009#note-51http://tracker.ceph.com/issues/19009#note-51 with two failures that I believe are unrelated. Please review/approve the PR if you agree it can be merged.

**Comment by smithfarm** [comment]
JFYI, this PR is holding up #15526 because the two PRs conflict with eachother. Until now I assumed this one should get priority, but since we're waiting for something to be added, now I'm tempted to mark this one DNM and put the other one in the next integration branch.

**Comment by jdurgin** [comment]
Merging #15526 first is fine with me

**Comment by gregsfortytwo** [comment]
Cherry-picked all the stuff from https://github.com/ceph/ceph/pull/15214/commits (didn't test the changes myself, but it was pretty clean).

I'm happy to rebase on top of #15526 if you let me know (the conflicts are pretty minimal) but am not doing so now since it's marked DNM. Let me know, @smithfarm! :)

**Comment by smithfarm** [comment]
DNM removed and will re-test

**Comment by smithfarm** [comment]
test this please

**Comment by smithfarm** [comment]
@gregsfortytwo Compilation error:

```
/home/jenkins-build/build/workspace/ceph-pull-requests/src/osd/PrimaryLogPG.cc: In member function ‘virtual void PrimaryLogPG::on_shutdown()’:
/home/jenkins-build/build/workspace/ceph-pull-requests/src/osd/PrimaryLogPG.cc:10143:18: error: ‘clear_backoffs’ was not declared in this scope
   clear_backoffs(); 
                  ^
```

**Comment by gregsfortytwo** [comment]
Whoops, that bit doesn't exist until Luminous. My bad, dropped the patch!

**Comment by smithfarm** [comment]
Testing running at http://pulpito.front.sepia.ceph.com:80/smithfarm-2017-07-19_21:14:07-rados-wip-kraken-backports-distro-basic-smithi/

**Comment by smithfarm** [comment]
@gregsfortytwo @jdurgin Good news and bad news. The good news is: this passed a rados suite at http://tracker.ceph.com/issues/19009#note-71

The bad news is that this PR causes some `upgrade/jewel-x` jobs to fail with "failed to complete snap trimming before timeout". See http://pulpito.front.sepia.ceph.com/smithfarm-2017-07-20_08:53:03-upgrade:jewel-x-wip-kraken-backports-distro-basic-vps/

I already made one attempt to fix this by increasing the timeout, but it had no effect. @gregsfortytwo suggested that we could just ignore these failures.

Given the time frame and the desirability of having a 11.2.1 point release before kraken goes EOL, I'd say just ignore the failures and merge. What do you think?

**Comment by smithfarm** [comment]
Note that the "failed to complete snap trimming before timeout" failures happen even when the ugprade tests are run on smithi instead of vps. See http://pulpito.front.sepia.ceph.com/smithfarm-2017-07-21_06:55:36-upgrade:jewel-x-wip-kraken-backports-distro-basic-smithi/

**Comment by smithfarm** [comment]
Update: the test failures happen in only two test cases within `upgrade/jewel-x`: `parallel` and `stress-split-erasure-code` on Trusty. Opened https://github.com/ceph/ceph/pull/16493 to drop those two.

**Comment by gregsfortytwo** [comment]
Yeah, I approved the other PR and spot-checked one of the failures and it didn't have any crashes so this all seems fine to me. :)

**Pull request merged**
