### PR TITLE
luminous: rgw: fix issue for CreateBucket with BucketLocation param

### PR DESCRIPTION
**Pull request by mattbenjamin**
backport tracker: https://tracker.ceph.com/issues/41579

---

backport of #22312
parent tracker https://tracker.ceph.com/issues/41401

### CODE REVIEW

**Comment by mattbenjamin** [comment]
@cbodley works for me on downstream L

**Comment by smithfarm** [comment]
jenkins test signed

**Comment by smithfarm** [comment]
jenkins test submodules

**Comment by yuriw** [comment]
[wip-yuri5-testing-2019-10-08-2016-luminous](https://trello.com/c/2sPmnyf7/713-wip-yuri5-testing-2019-10-08-2016-luminous)

**Pull request merged**
