### PR TITLE
add bindsto in ceph.target.It can restart ceph if docker is used and …

### PR DESCRIPTION
**Pull request by dayiguizhen**
…restart

Signed-off-by: yuzhe.xu_UIH-AI <yuzhe.xu@united-imaging.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Review by adk3798 — COMMENTED** [review]
When I was checking this is looked like restarting the docker daemon already restarted the containers without needing this addition to the target file.

image


Is that not the case when you do it?

**Comment by tchaikov** [comment]
@dayiguizhen ping?

**Comment by sebastian-philipp** [comment]
@dayiguizhen ping?

**Comment by dayiguizhen** [comment]
I find 15.2.13 has resolve this question.

**Pull request closed without merging**
