### PR TITLE
rgw: fix for usage truncated flag

### PR DESCRIPTION
**Pull request by yehudasa**

### CODE REVIEW

**Comment by robbat2** [comment]
You want one more fix on my branch as well: 
https://github.com/dreamhost/ceph/commit/cf8c8778ca8ad4376dd983280bac6b22f2397342

**Comment by yehudasa** [comment]
@robbat2 thanks, updated

**Comment by gregsfortytwo** [comment]
These look good to me from what I recall of the structure, but I’ll let somebody from the rgw team do a final sign off.

**Comment by robbat2** [comment]
@oritwas can you eyeball this for merge? Needs backport to luminous.

**Pull request merged**
