### PR TITLE
mimic: rgw: cls_bucket_list_unordered lists a single shard

### PR DESCRIPTION
**Pull request by cbodley**
backport tracker: http://tracker.ceph.com/issues/39411

### CODE REVIEW

**Comment by yuriw** [comment]
[wip-yuri-testing-2019-05-13-1904-mimic](https://trello.com/c/b7ZMIYPQ/613-wip-yuri-testing-2019-05-13-1904-mimic)

**Comment by smithfarm** [comment]
Hm, Jenkins is oddly silent on this PR.

**Comment by smithfarm** [comment]
Guys, let's hold off on adding "*-batch-1" labels until after "make check" completes successfully. Thanks!

**Comment by ivancich** [comment]
jenkins test make check

**Pull request merged**
