### PR TITLE
test/crimson: v2 failover tests with ack/keepalive

### PR DESCRIPTION
**Pull request by cyx1231st**
## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`

</details>

### CODE REVIEW

**Comment by cyx1231st** [comment]
No performance impact should be expected: All changes are wrapped by `#ifdef UNIT_TESTS_BUILT`, or only relate to unit tests.

**Comment by tchaikov** [comment]
```
08:48:10 - INFO     - cbt      - prefill/incerta08.front.sepia.ceph.com/0: bandwidth: (or (greater) (near 0.05)):: 9.64053/9.86259  => accepted
08:48:10 - INFO     - cbt      - prefill/incerta08.front.sepia.ceph.com/0: iops_avg: (or (greater) (near 0.05)):: 2467.0/2524.0  => accepted
08:48:10 - INFO     - cbt      - prefill/incerta08.front.sepia.ceph.com/0: iops_stddev: (or (less) (near 0.50)):: 144.42/207.039  => accepted
08:48:10 - INFO     - cbt      - prefill/incerta08.front.sepia.ceph.com/0: latency_avg: (or (less) (near 0.05)):: 0.00646068/0.00632939  => accepted
08:48:10 - INFO     - cbt      - prefill/incerta08.front.sepia.ceph.com/1: bandwidth: (or (greater) (near 0.05)):: 9.61711/9.9325  => accepted
08:48:10 - INFO     - cbt      - prefill/incerta08.front.sepia.ceph.com/1: iops_avg: (or (greater) (near 0.05)):: 2461.0/2542.0  => accepted
08:48:10 - INFO     - cbt      - prefill/incerta08.front.sepia.ceph.com/1: iops_stddev: (or (less) (near 0.50)):: 148.88/168.921  => accepted
08:48:10 - INFO     - cbt      - prefill/incerta08.front.sepia.ceph.com/1: latency_avg: (or (less) (near 0.05)):: 0.00649184/0.00628459  => accepted
08:48:10 - WARNING  - cbt      - rand/incerta08.front.sepia.ceph.com/0: bandwidth: (or (greater) (near 0.05)):: 55.5799/64.295  => rejected
08:48:10 - WARNING  - cbt      - rand/incerta08.front.sepia.ceph.com/0: iops_avg: (or (greater) (near 0.05)):: 14228.0/16459.0  => rejected
08:48:10 - WARNING  - cbt      - rand/incerta08.front.sepia.ceph.com/0: iops_stddev: (or (less) (near 0.50)):: 470.702/192.779  => rejected
08:48:10 - WARNING  - cbt      - rand/incerta08.front.sepia.ceph.com/0: latency_avg: (or (less) (near 0.05)):: 0.00111666/0.000965617  => rejected
08:48:10 - WARNING  - cbt      - rand/incerta08.front.sepia.ceph.com/1: bandwidth: (or (greater) (near 0.05)):: 56.9672/63.8432  => rejected
08:48:10 - WARNING  - cbt      - rand/incerta08.front.sepia.ceph.com/1: iops_avg: (or (greater) (near 0.05)):: 14583.0/16343.0  => rejected
08:48:10 - WARNING  - cbt      - rand/incerta08.front.sepia.ceph.com/1: iops_stddev: (or (less) (near 0.50)):: 517.311/157.689  => rejected
08:48:10 - WARNING  - cbt      - rand/incerta08.front.sepia.ceph.com/1: latency_avg: (or (less) (near 0.05)):: 0.00109047/0.000972373  => rejected
08:48:10 - WARNING  - cbt      - 8 tests failed out of 16
```

**Comment by tchaikov** [comment]
jenkins test crimson perf

**Comment by tchaikov** [comment]
```
04:36:44 - DEBUG    - cbt      - Nodes : incerta08.front.sepia.ceph.com
04:36:44 - DEBUG    - cbt      - Nodes : incerta08.front.sepia.ceph.com
04:36:44 - WARNING  - cbt      - prefill/incerta08.front.sepia.ceph.com/0: bandwidth: (or (greater) (near 0.05)):: 9.25032/9.90318  => rejected
04:36:44 - WARNING  - cbt      - prefill/incerta08.front.sepia.ceph.com/0: iops_avg: (or (greater) (near 0.05)):: 2368.0/2535.0  => rejected
04:36:44 - INFO     - cbt      - prefill/incerta08.front.sepia.ceph.com/0: iops_stddev: (or (less) (near 0.50)):: 149.663/113.161  => accepted
04:36:44 - WARNING  - cbt      - prefill/incerta08.front.sepia.ceph.com/0: latency_avg: (or (less) (near 0.05)):: 0.00673584/0.00629263  => rejected
04:36:44 - WARNING  - cbt      - prefill/incerta08.front.sepia.ceph.com/1: bandwidth: (or (greater) (near 0.05)):: 9.26038/9.83207  => rejected
04:36:44 - WARNING  - cbt      - prefill/incerta08.front.sepia.ceph.com/1: iops_avg: (or (greater) (near 0.05)):: 2370.0/2517.0  => rejected
04:36:44 - INFO     - cbt      - prefill/incerta08.front.sepia.ceph.com/1: iops_stddev: (or (less) (near 0.50)):: 150.123/107.151  => accepted
04:36:44 - WARNING  - cbt      - prefill/incerta08.front.sepia.ceph.com/1: latency_avg: (or (less) (near 0.05)):: 0.00672736/0.00633831  => rejected
04:36:44 - WARNING  - cbt      - rand/incerta08.front.sepia.ceph.com/0: bandwidth: (or (greater) (near 0.05)):: 56.8043/63.8416  => rejected
04:36:44 - WARNING  - cbt      - rand/incerta08.front.sepia.ceph.com/0: iops_avg: (or (greater) (near 0.05)):: 14541.0/16343.0  => rejected
04:36:44 - WARNING  - cbt      - rand/incerta08.front.sepia.ceph.com/0: iops_stddev: (or (less) (near 0.50)):: 771.408/144.445  => rejected
04:36:44 - WARNING  - cbt      - rand/incerta08.front.sepia.ceph.com/0: latency_avg: (or (less) (near 0.05)):: 0.00109299/0.000972226  => rejected
04:36:44 - WARNING  - cbt      - rand/incerta08.front.sepia.ceph.com/1: bandwidth: (or (greater) (near 0.05)):: 55.7513/63.6769  => rejected
04:36:44 - WARNING  - cbt      - rand/incerta08.front.sepia.ceph.com/1: iops_avg: (or (greater) (near 0.05)):: 14272.0/16301.0  => rejected
04:36:44 - WARNING  - cbt      - rand/incerta08.front.sepia.ceph.com/1: iops_stddev: (or (less) (near 0.50)):: 776.769/169.872  => rejected
04:36:44 - WARNING  - cbt      - rand/incerta08.front.sepia.ceph.com/1: latency_avg: (or (less) (near 0.05)):: 0.00111357/0.000974109  => rejected
04:36:44 - WARNING  - cbt      - 14 tests failed out of 16
```

**Comment by tchaikov** [comment]
jenkins test crimson perf

**Comment by tchaikov** [comment]
jenkins test crimson perf

**Pull request merged**
