### PR TITLE
mds: limit client writable range increment

### PR DESCRIPTION
**Pull request by ukernel**
For very large file, setting the writable range to '2 * file_size'
makes file recovery to run a long time. To recover a 1T file, Filer
needs to probe 1T~2T range.

Fixes: http://tracker.ceph.com/issues/19955
Signed-off-by: "Yan, Zheng" <zyan@redhat.com>

### CODE REVIEW

**Comment by jcsp** [comment]
I agree with this approach

**Comment by ukernel** [comment]
this RP isn't complete. client code also assumes that max_size is '2 * file_size'. need to tune the client code

**Comment by liewegas** [comment]
:+1:

**Comment by ukernel** [comment]
fix some typo in code comment and commit message, no code logic changes

**Pull request merged**
