### PR TITLE
osd: fixes for make_writeable

### PR DESCRIPTION
**Pull request by wonzhq**

### CODE REVIEW

**Comment by tchaikov** [comment]
strictly speaking, a3b000d is a bug fix but not a critical one.

**Comment by tchaikov** [comment]
:+1:

**Comment by athanatos** [comment]
We need to mark dirty even on a non-cache pool since librados clients can set, clear, and query dirtiness even on a non-cache pool (and it breaks a unit test!) I've unset needs-qa for now, ping me when it's ready for testing again.

**Comment by wonzhq** [comment]
Removed that commit, pls add it for testing again, thx! @athanatos

**Pull request merged**
