### PR TITLE
jewel: Failure in snaptest-git-ceph.sh

### PR DESCRIPTION
**Pull request by dachary**
http://tracker.ceph.com/issues/17476

### CODE REVIEW

**Comment by dachary** [comment]
jenkins test this please (unittest_bluefs core)

**Comment by dachary** [comment]
@jcsp does this backport look good to merge ? It passed the fs suite http://tracker.ceph.com/issues/17487#note-13 (except for one known bug that is, I believe, unrelated)

**Comment by dachary** [comment]
jenkins test this please (terminated it seems, no failure visible)

**Comment by jcsp** [comment]
:+1:

**Pull request merged**
