### PR TITLE
mimic: os/bluestore: Fix bluefs - block balance. 

### PR DESCRIPTION
**Pull request by aclamk**
https://tracker.ceph.com/issues/38574

---

Fix problem with bluefs's freespace not being balanced when kv_sync_thread is sleeping.

Signed-off-by: Adam Kupczyk <akupczyk@redhat.com>

### CODE REVIEW

**Comment by neha-ojha** [comment]
retest this please

**Comment by yuriw** [comment]
[wip-yuri3-testing-2019-03-05-1606-mimic](https://trello.com/c/4jMXbkqv/552-wip-yuri3-testing-2019-03-05-1606-mimic)

**Comment by yuriw** [comment]
@aclamk @neha-ojha i am getting failed build on the PR
https://jenkins.ceph.com/job/ceph-dev-new-setup/18860//consoleFull

**Comment by aclamk** [comment]
This fixes https://tracker.ceph.com/issues/38574

**Pull request merged**
