### PR TITLE
qa: add sleep for blocklisting to take effect

### PR DESCRIPTION
**Pull request by batrick**
Fixes: https://tracker.ceph.com/issues/49318
Signed-off-by: Patrick Donnelly <pdonnell@redhat.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by batrick** [comment]
https://pulpito.ceph.com/pdonnell-2021-02-24_05:54:31-fs-wip-pdonnell-testing-20210224.040859-distro-basic-gibba/

New failures:
- https://tracker.ceph.com/issues/49468
- https://tracker.ceph.com/issues/49469
- https://tracker.ceph.com/issues/49465
- https://tracker.ceph.com/issues/49458

Going to wait for unrelated upgrade failures to get resolved before merging this.

**Comment by batrick** [comment]
https://pulpito.ceph.com/?branch=wip-pdonnell-testing-20210303.195715

Failures are:
- https://tracker.ceph.com/issues/49607
- https://tracker.ceph.com/issues/48773
- https://tracker.ceph.com/issues/48805
- https://tracker.ceph.com/issues/49466
- https://tracker.ceph.com/issues/49605
- https://tracker.ceph.com/issues/49511
- https://tracker.ceph.com/issues/45434
- https://tracker.ceph.com/issues/44631

**Comment by batrick** [comment]
Ready for merge after review.

**Comment by batrick** [comment]
Used teuthology's sleep task instead. I'll do another round of QA...

**Review by rishabh-d-dave — APPROVED** [review]

**Comment by batrick** [comment]
https://pulpito.ceph.com/pdonnell-2021-03-09_03:27:39-fs-wip-pdonnell-testing-20210308.214827-distro-basic-smithi/

Failures are:

- https://tracker.ceph.com/issues/49500
- https://tracker.ceph.com/issues/48805
- https://tracker.ceph.com/issues/48773
- https://tracker.ceph.com/issues/45434
- https://tracker.ceph.com/issues/49240
- https://tracker.ceph.com/issues/49466
- https://tracker.ceph.com/issues/49684
- https://tracker.ceph.com/issues/48771

**Pull request merged**
