### PR TITLE
osd: Replace stat() calls with access() in case of lookup only

### PR DESCRIPTION
**Pull request by varadakari**
Replace stat() with access() if we are checking only existence of the path.

Signed-off-by: Varada Kari <varada.kari@sandisk.com>

### CODE REVIEW

**Comment by liewegas** [comment]
simple enough!

**Comment by yangruifeng** [comment]
access have some performance loss than stat.
I test it on Ubuntu 14.04.3 LTS 3.19.0-32-generic.

**Comment by varadakari** [comment]
@yangruifeng is it observed only in 3.19? I am not seeing this degradation in 3.16 with 14.04.2. will try some more runs to verify the same. Can you please any of the results?

**Comment by yangruifeng** [comment]
@varadakari this is the result, what have I missed? cache?
```
int main() {
        int i = 1000000;
        int r = 0;
        while(i--)
                r += access("/etc/hosts", F_OK);
        return r;
}

int main() {
        struct stat buf;
        int i = 1000000;
        int r = 0;
        while(i--)
                r += stat("/etc/hosts", &buf);
        return r;
}

```

root@ubuntu:~# gcc access.c -o access.exe -O2
root@ubuntu:~# gcc stat.c -o stat.exe -O2
root@ubuntu:~# time ./access.exe 

real	0m0.760s
user	0m0.021s
sys	0m0.737s
root@ubuntu:~# time ./stat.exe 

real	0m0.560s
user	0m0.029s
sys	0m0.489s
root@ubuntu:~# time ./stat.exe 

real	0m0.481s
user	0m0.028s
sys	0m0.452s
root@ubuntu:~# time ./access.exe 

real	0m0.832s
user	0m0.032s
sys	0m0.797s
root@ubuntu:~# time ./stat.exe 

real	0m0.488s
user	0m0.025s
sys	0m0.464s
root@ubuntu:~# time ./access.exe 

real	0m0.746s
user	0m0.057s
sys	0m0.686s
~

**Comment by varadakari** [comment]
Seems more of cache effect here. Can you flush all the dentries and cache before and see? An try accessing only once, rest of calls anyways hit the cache. First call to stat will take more time compared to access, if not found in page cache.

**Comment by varadakari** [comment]
@yangruifeng you can use rdtsc() to measure the number of cycles each call took for completion to get the results accurate, after flushing all entries from dentry cache.

**Comment by liewegas** [comment]
Passed testing.  What's the verdict here.. is it worth making this change?

**Comment by yuyuyu101** [comment]
Hmm, I also tested locally, performance degraded happeded. access is slower than 50% compared to stat. I checked the internal impl for stat and access. It seemed that access do a lot of security check than stat.

**Comment by yuyuyu101** [comment]
The test case is that I touch a 1w files and use "attr" shell tool to set xattr for each file. Then run stat/access for each file. 
[root@digital-41 tmp]# time ./stat

real	0m0.008s
user	0m0.000s
sys	0m0.008s
[root@digital-41 tmp]# time ./access

real	0m0.012s
user	0m0.003s
sys	0m0.009s

**Comment by varadakari** [comment]
@liewegas @yuyuyu101 seems access has more degradation than stat. when i tried in my runs, seen some improvement with this change. will have to verify again. user space time consumption in access is more!

**Comment by liewegas** [comment]
Hmm, I suspect access degrades when selinux or ACLs are present, too.  
Let's just stick with stat!

**Pull request closed without merging**
