### PR TITLE
doc/radosgw: remove invalid LUA context options

### PR DESCRIPTION
**Pull request by zdover23**
Remove "background", "getdata", and "putdata" from the list of LUA context options. Passing these options throws the following error: "ERROR: invalid script context: background. must be one of: preRequest, postRequest".

Fixes: https://tracker.ceph.com/issues/64327

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [x] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [x] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Review by anthonyeleven — APPROVED** [review]

**Comment by cbodley** [comment]
this change was definitely not correct. these script types are all supported on main

cc @yuvalif

**Comment by zdover23** [comment]
> let's figure out which release https://tracker.ceph.com/issues/64327 was reported against, we can fix the docs there

Roger that. Would you prefer that I roll this back now?

**Comment by cbodley** [comment]
yes please!

**Comment by zdover23** [comment]
> yes please!

Roger that. I'll do it now. Stand by for about fifteen minutes, and I'll send you a PR.

**Comment by cbodley** [comment]
it looks like the quincy release is the only one that needs adjustment, and it's a minor one - i think the backport commit https://github.com/ceph/ceph/commit/b0c78748c05faed9c6032f490169741ad7fd6cf7 should just be reverted there

**Comment by zdover23** [comment]
@cbodley: https://github.com/ceph/ceph/pull/55525

**Comment by zdover23** [comment]
> it looks like the quincy release is the only one that needs adjustment, and it's a minor one - i think the backport commit [b0c7874](https://github.com/ceph/ceph/commit/b0c78748c05faed9c6032f490169741ad7fd6cf7) should just be reverted there

I'll revert this now.

**Pull request merged**
