### PR TITLE
osd: misc inc-recovery compat fixes 

### PR DESCRIPTION
**Pull request by xiexingguo**

### CODE REVIEW

**Comment by xiexingguo** [comment]
See http://pulpito.ceph.com/xxg-2019-08-19_06:47:16-rados:thrash-wip-scrub-omap-error-distro-basic-smithi/4229697/

**Object benchmark_data_smithi194_16393_object8310 is missing on osd.7(primary) at boot up:**
```
2019-08-19T07:18:56.538+0000 7fd89be05f40 15 bluestore(/var/lib/ceph/osd/ceph-7) getattr 2.5_head #2:a0d67e33:::benchmark_data_smithi194_16393_objec
t8310:head# _
2019-08-19T07:18:56.538+0000 7fd89be05f40 20 bluestore(/var/lib/ceph/osd/ceph-7).collection(2.5_head 0x55721d8c4b40) get_onode oid #2:a0d67e33:::ben
chmark_data_smithi194_16393_object8310:head# key 0x7f8000000000000002a0d67e'3!benchmark_data_smithi194_16393_object8310!='0xfffffffffffffffeffffffff
ffffffff'o'
2019-08-19T07:18:56.538+0000 7fd89be05f40 20 bluestore(/var/lib/ceph/osd/ceph-7).collection(2.5_head 0x55721d8c4b40)  r -2 v.len 0
2019-08-19T07:18:56.538+0000 7fd89be05f40 10 bluestore(/var/lib/ceph/osd/ceph-7) getattr 2.5_head #2:a0d67e33:::benchmark_data_smithi194_16393_objec
t8310:head# _ = -2
2019-08-19T07:18:56.538+0000 7fd89be05f40 15 read_log_and_missing  missing 24'528 (0'0) modify   2:a0d67e33:::benchmark_data_smithi194_16393_object8
310:head by client.4470.0:8311 2019-08-19T07:18:07.718470+0000 0 ObjectCleanRegions clean_offsets: [65536~18446744073709486079], clean_omap: 1, obje
ct_new: 0
```
**missing_item of benchmark_data_smithi194_16393_object8310 for osd.7 (primary):**

`2:a0d67e33:::benchmark_data_smithi194_16393_object8310:head=24'528 flags = none clean_offsets: [0~18446744073709551615], clean_omap: 1, object_new: 0`

**and then the crash:**
```
2019-08-19T07:18:59.342+0000 7fd873bf5700 10 bluestore(/var/lib/ceph/osd/ceph-7) queue_transactions ch 0x55721d8c4b40 2.5_head
2019-08-19T07:18:59.342+0000 7fd873bf5700 20 bluestore(/var/lib/ceph/osd/ceph-7) _txc_create osr 0x55721e7c1040 = 0x557221af9800 seq 30
2019-08-19T07:18:59.342+0000 7fd873bf5700 20 bluestore(/var/lib/ceph/osd/ceph-7).collection(2.5_head 0x55721d8c4b40) get_onode oid #2:a0d67e33:::ben
chmark_data_smithi194_16393_object8310:head# key 0x7f8000000000000002a0d67e'3!benchmark_data_smithi194_16393_object8310!='0xfffffffffffffffeffffffff
ffffffff'o'
2019-08-19T07:18:59.342+0000 7fd873bf5700 20 bluestore(/var/lib/ceph/osd/ceph-7).collection(2.5_head 0x55721d8c4b40)  r -2 v.len 0
2019-08-19T07:18:59.342+0000 7fd873bf5700 10 bluestore(/var/lib/ceph/osd/ceph-7) _txc_add_transaction op 28 got ENOENT on #2:a0d67e33:::benchmark_da
ta_smithi194_16393_object8310:head#
2019-08-19T07:18:59.342+0000 7fd873bf5700 20 bluestore(/var/lib/ceph/osd/ceph-7).collection(2.5_head 0x55721d8c4b40) get_onode oid #2:a0d67e33:::ben
chmark_data_smithi194_16393_object8310:head# key 0x7f8000000000000002a0d67e'3!benchmark_data_smithi194_16393_object8310!='0xfffffffffffffffeffffffff
ffffffff'o'
2019-08-19T07:18:59.342+0000 7fd873bf5700 20 bluestore(/var/lib/ceph/osd/ceph-7).collection(2.5_head 0x55721d8c4b40)  r -2 v.len 0
2019-08-19T07:18:59.342+0000 7fd873bf5700 10 bluestore(/var/lib/ceph/osd/ceph-7) _txc_add_transaction op 12 got ENOENT on #2:a0d67e33:::benchmark_da
ta_smithi194_16393_object8310:head#
2019-08-19T07:18:59.342+0000 7fd873bf5700 20 bluestore(/var/lib/ceph/osd/ceph-7).collection(2.5_head 0x55721d8c4b40) get_onode oid #2:a0d67e33:::ben
chmark_data_smithi194_16393_object8310:head# key 0x7f8000000000000002a0d67e'3!benchmark_data_smithi194_16393_object8310!='0xfffffffffffffffeffffffff
ffffffff'o'
2019-08-19T07:18:59.342+0000 7fd873bf5700 20 bluestore(/var/lib/ceph/osd/ceph-7).collection(2.5_head 0x55721d8c4b40)  r -2 v.len 0
2019-08-19T07:18:59.342+0000 7fd873bf5700 10 bluestore(/var/lib/ceph/osd/ceph-7) _txc_add_transaction op 15 got ENOENT on #2:a0d67e33:::benchmark_da
ta_smithi194_16393_object8310:head#
2019-08-19T07:18:59.342+0000 7fd873bf5700 -1 bluestore(/var/lib/ceph/osd/ceph-7) _txc_add_transaction error (2) No such file or directory not handle
d on operation 15 (op 2, counting from 0)
2019-08-19T07:18:59.342+0000 7fd873bf5700 -1 bluestore(/var/lib/ceph/osd/ceph-7) unexpected error code
2019-08-19T07:18:59.342+0000 7fd873bf5700  0 _dump_transaction transaction dump:
{
    "ops": [
        {
            "op_num": 0,
            "op_name": "rmattrs",
            "collection": "2.5_head",
            "oid": "#2:a0d67e33:::benchmark_data_smithi194_16393_object8310:head#"
        },
        {
            "op_num": 1,
            "op_name": "truncate",
            "collection": "2.5_head",
            "oid": "#2:a0d67e33:::benchmark_data_smithi194_16393_object8310:head#",
            "offset": 65536
        },
        {
            "op_num": 2,
            "op_name": "setattrs",
            "collection": "2.5_head",
            "oid": "#2:a0d67e33:::benchmark_data_smithi194_16393_object8310:head#",
            "attr_lens": {
                "_": 296,
                "snapset": 35
            }
        },
```

**Comment by xiexingguo** [comment]
@neha-ojha please hold on. i am re-investigating..

**Comment by xiexingguo** [comment]
@jdurgin @neha-ojha I refined the original fix and appended some more fixes. Should be ready for re-review now.

**Comment by xiexingguo** [comment]
retest this please

**Comment by jdurgin** [comment]
Do we need some more additions to the qa suite to verify that inc recovery is being used? I'm concerned with how many bugs you've found, we may be missing some important test coverage

**Comment by xiexingguo** [comment]
> we may be missing some important test coverage

I agree. Will come back later to see if i can help with this topic.

**Comment by xiexingguo** [comment]
retest this please

**Comment by liewegas** [comment]
retest this please

**Comment by xiexingguo** [comment]
http://pulpito.ceph.com/xxg-2019-08-24_00:00:29-rados:thrash-wip-37654-distro-basic-smithi/

**Pull request merged**
