### PR TITLE
cmake: link tests against static librados

### PR DESCRIPTION
**Pull request by tchaikov**
Fixes: http://tracker.ceph.com/issues/17260

### CODE REVIEW

**Comment by dachary** [comment]
great ! 

<pre>
Reviewed-by: Loic Dachary &lt;ldachary@redhat.com>
</pre>

**Comment by alimaredia** [comment]
looks good to me!

**Comment by dillaman** [comment]
lgtm - would like to see the modified tests passing under teuthology.

**Comment by tchaikov** [comment]
- rados tests being tested at http://pulpito.ceph.com/kchai-2016-10-21_03:25:07-rados-wip-17260---basic-mira/
- rbd tests being tested at http://pulpito.ceph.com/kchai-2016-10-21_03:28:59-rbd-wip-17260---basic-mira/

**Comment by tchaikov** [comment]
all passed. http://pulpito.ceph.com/kchai-2016-10-21_03:33:58-rbd-master---basic-mira is the comparison group of http://pulpito.ceph.com/kchai-2016-10-21_03:28:59-rbd-wip-17260---basic-mira/, it passes also. but considering [tracker#17260](http://tracker.ceph.com/issues/17260) is a racing issue, it's possible that the test passes some times.

**Pull request merged**
