### PR TITLE
common: use close_range on Linux

### PR DESCRIPTION
**Pull request by edef1c**
Fix rook/rook#10110, which occurs when _SC_OPEN_MAX/RLIMIT_NOFILE is set to very large values (2^30), leaving fork_function pegging a core busylooping.

The glibc wrappers closefrom(3)/close_range(3) are not available before glibc 2.34, so we invoke the syscall directly. When glibc 2.34 is old enough to be a reasonable hard minimum dependency, we should switch to using closefrom.

If we're not running on (recent enough) Linux, we fall back to the existing approach.

## Checklist
- Tracker (select at least one)
  - [x] References [tracker ticket](https://tracker.ceph.com/issues/59125)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by salfers** [comment]
We just tried to boostrap a new Ceph cluster in our company via cephadm using Ceph Quincy, EL9 and Docker and this broke our cluster every time we tried the process from scratch.
If not prioritizing this bug fix the Ceph team should at least edit the documentation to state clearly that **EL9 + Docker do not work with cephadm**, to avoid other people wasting their time with it.

ping @travisn

**Comment by edef1c** [comment]
I believe this PR is still relevant, but I'm not sure what I can do to move it along.

**Comment by idryomov** [comment]
@rzarzynski @ljflores Looks like this is waiting for a review from Core.

**Review by rzarzynski — APPROVED** [review]

**Comment by squaricdot** [comment]
affected by this issue. would be great if it get's merged.

**Comment by rzarzynski** [comment]
All we need is a QA run.

@ljflores, @yuriw: could  you please take this into testing?

**Comment by ljflores** [comment]
@rzarzynski it's in a batch!

**Comment by yuriw** [comment]
@edef1c this a suspect to have broken the build:

https://jenkins.ceph.com/job/ceph-dev-new-build/ARCH=x86_64,AVAILABLE_ARCH=x86_64,AVAILABLE_DIST=focal,DIST=focal,MACHINE_SIZE=gigantic/75440//consoleFull

19.0.0-466-g15215d01/src/common/SubProcess.cc
[ 60%] Building CXX object src/arrow/CMakeFiles/arrow_objlib.dir/compute/kernels/scalar_cast_nested.cc.o
/build/ceph-19.0.0-466-g15215d01/src/common/SubProcess.cc:9:10: fatal error: linux/close_range.h: No such file or directory
    9 | #include <linux/close_range.h>
      |          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[3]: *** [src/common/CMakeFiles/common-common-objs.dir/build.make:1263: src/common/CMakeFiles/common-common-objs.dir/SubProcess.cc.o] Error 1
make[3]: *** Waiting for unfinished jobs....

**Comment by ljflores** [comment]
@yuriw yeah, it is breaking focal.

@edef1c this compile error seems to happen in ubuntu focal if you need to reproduce it.

**Comment by edef1c** [comment]
> @edef1c this compile error seems to happen in ubuntu focal if you need to reproduce it.

Hmm, okay. Seems like focal's linux-libc-dev package doesn't include close_range.h. We don't actually _need_ the header (it just supplies the `CLOSE_RANGE_{UNSHARE,CLOEXEC}` constants), so we can just leave it out.

**Comment by edef1c** [comment]
I've dropped the header include. I think things should be fine now unless `SYS_close_range` isn't available somewhere, in which case we can just `#ifdef` a little more.

**Comment by edef1c** [comment]
I ended up taking a closer look, and found that neither `SYS_close_range` nor `__NR_close_range` are available on focal. I've amended the change to just check if `SYS_close_range` is defined, so nothing should change on systems where it's not available from the headers.

@ljflores @yuriw Could we get another run? It should be fully baked wrt backward compat at this point, as far as I can tell.

**Comment by edef1c** [comment]
The failed API tests seem to go to a Jenkins 404 page, so I'm not sure what's up there.

**Comment by tchaikov** [comment]
jenkins test api

**Comment by heliochronix** [comment]
It seems like this is done and approved. Is this waiting for some milestone to merge?

**Comment by rzarzynski** [comment]
We need rerun the QA per https://github.com/ceph/ceph/pull/50622#issuecomment-1896181352.

Ping @yuriw, @ljflores.

**Comment by amathuria** [comment]
Rados approved: https://tracker.ceph.com/projects/rados/wiki/MAIN#httpstrackercephcomissues64974

**Comment by prazumovsky** [comment]
See the same on Reef v18.2.4, definitely required backport to reef

**Comment by idryomov** [comment]
> See the same on Reef v18.2.4, definitely required backport to reef

Hrm, this hasn't been backported to squid either.  @prazumovsky Can you create a squid backport as well?

**Comment by idryomov** [comment]
> @prazumovsky Can you create a squid backport as well?

It would go under https://tracker.ceph.com/issues/69778.

**Pull request merged**
