### PR TITLE
squid: cephadm: fix apparmor profiles with spaces in the names

### PR DESCRIPTION
**Pull request by k0ste**
backport tracker: https://tracker.ceph.com/issues/66530

---

backport of https://github.com/ceph/ceph/pull/57955
parent tracker: https://tracker.ceph.com/issues/66389

this backport was staged using ceph-backport.sh version 16.0.0.6848
find the latest version at https://github.com/ceph/ceph/blob/main/src/script/ceph-backport.sh

### CODE REVIEW

**Review by adk3798 — APPROVED** [review]

**Comment by ljflores** [comment]
jenkins test make check

**Comment by ljflores** [comment]
Rados approved: https://tracker.ceph.com/projects/rados/wiki/SQUID#httpstrackercephcomissues67045

**Comment by yuriw** [comment]
jenkins test make check

**Comment by yuriw** [comment]
@k0ste pls merge when all checks passed
ref: https://tracker.ceph.com/issues/67045

**Comment by adk3798** [comment]
jenkins test make check

**Comment by yuriw** [comment]
jenkins test make check

**Comment by mathieuHa** [comment]
Hi, any idea when this will land ? after upgrading to Ubuntu 24, and upgrading my Ceph cluster to 19.2 (or trying), i'm getting apparmor errors that seems to be resolved in the PR

**Comment by yuriw** [comment]
jenkins test make check

**Comment by zsolis-ng** [comment]
Installed Cephadm 19.2.1 but still receiving the apparmor error:

```shell
orchestrator._interface.OrchestratorError: cephadm exited with an error code: 1, stderr: Redeploy daemon osd.2 ...
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/var/lib/ceph/65598e0c-cec9-11ee-a2f5-db5748fa7fb4/cephadm.91b52e446d8f1d91339889933063a5070027dc00f54d563f523727c6dd22b172/__main__.py", line 10889, in <module>
  File "/var/lib/ceph/65598e0c-cec9-11ee-a2f5-db5748fa7fb4/cephadm.91b52e446d8f1d91339889933063a5070027dc00f54d563f523727c6dd22b172/__main__.py", line 10877, in main
  File "/var/lib/ceph/65598e0c-cec9-11ee-a2f5-db5748fa7fb4/cephadm.91b52e446d8f1d91339889933063a5070027dc00f54d563f523727c6dd22b172/__main__.py", line 6786, in command_deploy_from
  File "/var/lib/ceph/65598e0c-cec9-11ee-a2f5-db5748fa7fb4/cephadm.91b52e446d8f1d91339889933063a5070027dc00f54d563f523727c6dd22b172/__main__.py", line 6804, in _common_deploy
  File "/var/lib/ceph/65598e0c-cec9-11ee-a2f5-db5748fa7fb4/cephadm.91b52e446d8f1d91339889933063a5070027dc00f54d563f523727c6dd22b172/__main__.py", line 6821, in _dispatch_deploy
  File "/var/lib/ceph/65598e0c-cec9-11ee-a2f5-db5748fa7fb4/cephadm.91b52e446d8f1d91339889933063a5070027dc00f54d563f523727c6dd22b172/__main__.py", line 6686, in get_deployment_container
  File "/var/lib/ceph/65598e0c-cec9-11ee-a2f5-db5748fa7fb4/cephadm.91b52e446d8f1d91339889933063a5070027dc00f54d563f523727c6dd22b172/__main__.py", line 3846, in get_container
  File "/var/lib/ceph/65598e0c-cec9-11ee-a2f5-db5748fa7fb4/cephadm.91b52e446d8f1d91339889933063a5070027dc00f54d563f523727c6dd22b172/__main__.py", line 3560, in get_container_mounts
  File "/var/lib/ceph/65598e0c-cec9-11ee-a2f5-db5748fa7fb4/cephadm.91b52e446d8f1d91339889933063a5070027dc00f54d563f523727c6dd22b172/__main__.py", line 9877, in selinux_enabled
  File "/var/lib/ceph/65598e0c-cec9-11ee-a2f5-db5748fa7fb4/cephadm.91b52e446d8f1d91339889933063a5070027dc00f54d563f523727c6dd22b172/__main__.py", line 9860, in kernel_security
  File "/var/lib/ceph/65598e0c-cec9-11ee-a2f5-db5748fa7fb4/cephadm.91b52e446d8f1d91339889933063a5070027dc00f54d563f523727c6dd22b172/__main__.py", line 9841, in _fetch_apparmor
ValueError: too many values to unpack (expected 2)

cephadm version
cephadm version 19.2.1 (58a7fab8be0a062d730ad7da874972fd3fba59fb) squid (stable)

apt info cephadm
Package: cephadm
Version: 19.2.1-1jammy
Priority: optional
Section: admin
Source: ceph
Maintainer: Ceph Maintainers <ceph-maintainers@ceph.io>
Installed-Size: 855 kB
Depends: adduser (>= 3.11), lvm2, python3
Recommends: podman (>= 2.0.2) | docker.io | docker-ce
Homepage: http://ceph.com/
Download-Size: 797 kB
APT-Manual-Installed: yes
APT-Sources: https://download.ceph.com/debian-19.2.1 jammy/main amd64 Packages
Description: cephadm utility to bootstrap ceph daemons with systemd and containers
 Ceph is a massively scalable, open-source, distributed
 storage system that runs on commodity hardware and delivers object,
 block and file system storage.
 .
 The cephadm utility is used to bootstrap a Ceph cluster and to manage
 ceph daemons deployed with systemd and containers.

N: There are 3 additional records. Please use the '-a' switch to see them.
```

**Pull request merged**
