### PR TITLE
nautilus: mgr/run-tox-tests: Fix issue with PYTHONPATH

### PR DESCRIPTION
**Pull request by badone**
Something changed recently on Bionic which caused tox to fail when
PYTHONPATH is a relative path.  For some reason the path is mangled by
the time it gets to pytest so we need to ensure we are using an absolute
path.

Signed-off-by: Brad Hubbard <bhubbard@redhat.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by badone** [comment]
The 'make check' failure in https://github.com/ceph/ceph/pull/33641 is an example.

**Comment by smithfarm** [comment]
@badone Could you remove the "nautilus: " prefix from the commit title? And, ideally, add a brief sentence to the body of the commit message explaining why the commit can't be cherry-picked from master?

**Comment by tchaikov** [comment]
@smithfarm could you help take another look?

**Comment by smithfarm** [comment]
Thanks for fixing.

**Pull request merged**
