### PR TITLE
rgw: add key parameter conflict check for radosgw-admin command line.

### PR DESCRIPTION
**Pull request by guce**
1.--access-key & --gen-access-key
radosgw-admin key create --uid=aaa --access-key='111' --gen-access-key --gen-secret
--access-key effective

2.--secret & --gen-secret
radosgw-admin key create --uid=aaa --access-key='222' --secret='222' --gen-secret
--gen-secret effective

test fix:
    before: conflict parameters can be configured.
    after changes, do the same procedure, can check for conflicts.

Signed-off-by: guce <guce@h3c.com>

### CODE REVIEW

**Comment by guce** [comment]
@yehudasa excuse me, any suggestions about this change?

**Comment by guce** [comment]
@theanalyst 
excuse me, is there anybody can take a look about this change?
thankyou.

**Comment by guce** [comment]
@yehudasa 
Thank you for your reply, i follow your suggestion to modify the code, please check.

I have two little questions：
1.The **`gen_access_key`** was **`int`** type.In my previous programming habits, i will strictly distinguish between **`bool`** and other types, otherwise some code static checker tool will prompt an error. Do you agree?
2.The return value should write **`EINVAL`** or **`-EINVAL`**, what is the difference?

**Comment by guce** [comment]
@yehudasa 
Excume me, any suggestions about the update?

**Comment by guce** [comment]
@yehudasa Would you please look at this revision? thanks.

**Comment by dachary** [comment]
@guce could you please update the Signed-off-by: of your commit with your name and surname instead of your nick ? See https://github.com/ceph/ceph/blob/master/SubmittingPatches for more information about why this is required. Thanks :-)

**Comment by guce** [comment]
@dachary Thank you for reminding me, i modify it, please check.

**Comment by guce** [comment]
@yehudasa I expect you have time continue deal with this issue.

**Comment by guce** [comment]
@yehudasa

**Comment by guce** [comment]
@yehudasa hi~~~~~

**Comment by guce** [comment]
@dachary @smithfarm
Can someone look at this issue it, thank you

**Pull request merged**
