### PR TITLE
reef: mds: reverse MDSMap encoding of max_xattr_size/bal_rank_mask

### PR DESCRIPTION
**Pull request by batrick**
backport tracker: https://tracker.ceph.com/issues/64505

---

backport of https://github.com/ceph/ceph/pull/55601
parent tracker: https://tracker.ceph.com/issues/64440

this backport was staged using ceph-backport.sh version 16.0.0.6848
find the latest version at https://github.com/ceph/ceph/blob/main/src/script/ceph-backport.sh

### CODE REVIEW

**Comment by batrick** [comment]
This PR drops https://github.com/ceph/ceph/commit/52c09aa1e50e3d9f36909354c43da89dec8f9bb5

which is already addressed in

https://github.com/ceph/ceph/pull/55590

**Comment by yuriw** [comment]
@batrick I could not schedule `fs` suite and suspect it's because of this PR

Pls take a look.

2024-02-21 20:43:28,111.111 INFO:teuthology.suite.run:Scheduling fs/thrash/workloads/{begin clusters/1a5s-mds-1c-client conf/{client mds mon osd} distro/{ubuntu_latest} mount/fuse msgr-failures/osd-mds-delay objectstore-ec/bluestore-ec-root overrides/{client-shutdown frag ignorelist_health ignorelist_wrongly_marked_down prefetch_dirfrags/no races session_timeout thrashosds-health} ranks/3 tasks/{1-thrash/osd 2-workunit/suites/iozone}}
Job scheduled with name yuriw-2024-02-21_20:42:01-fs-wip-yuri10-testing-2024-02-21-0731-reef-distro-default-smithi and ID 7569917
2024-02-21 20:43:28,905.905 INFO:teuthology.suite.run:Scheduling fs/workload/{begin clusters/1a11s-mds-1c-client-3node conf/{client mds mon osd} distro/{ubuntu_latest} mount/kclient/{mount overrides/{distro/testing/{flavor/centos_latest k-testing} ms-die-on-skipped}} ms_mode/{legacy} objectstore-ec/bluestore-comp omap_limit/10 overrides/{frag ignorelist_health ignorelist_wrongly_marked_down osd-asserts session_timeout} ranks/1 scrub/yes standby-replay subvolume/{with-no-extra-options} tasks/{0-check-counter workunit/suites/ffsb} wsync/{no}}
Job scheduled with name yuriw-2024-02-21_20:42:01-fs-wip-yuri10-testing-2024-02-21-0731-reef-distro-default-smithi and ID 7569918
2024-02-21 20:43:29,697.697 INFO:teuthology.suite.run:Scheduling fs/upgrade/upgraded_client/from_nautilus/{bluestore-bitmap centos_latest clusters/{1-mds-1-client-micro} conf/{client mds mon osd} overrides/{ignorelist_health ignorelist_wrongly_marked_down pg-warn} tasks/{0-nautilus 1-client-upgrade 2-client-sanity}}
Job scheduled with name yuriw-2024-02-21_20:42:01-fs-wip-yuri10-testing-2024-02-21-0731-reef-distro-default-smithi and ID 7569919
2024-02-21 20:43:30,485.485 INFO:teuthology.suite.run:Scheduling fs/multifs/{begin clusters/1a3s-mds-2c-client conf/{client mds mon osd} distro/{centos_8} mount/kclient/{mount overrides/{distro/stock/{k-stock rhel_8} ms-die-on-skipped}} objectstore-ec/bluestore-comp-ec-root overrides/{ignorelist_health ignorelist_wrongly_marked_down mon-debug} tasks/failover}
Job scheduled with name yuriw-2024-02-21_20:42:01-fs-wip-yuri10-testing-2024-02-21-0731-reef-distro-default-smithi and ID 7569920
2024-02-21 20:43:31,286.286 INFO:teuthology.suite.run:Scheduling fs/snaps/{begin clusters/1a3s-mds-1c-client conf/{client mds mon osd} distro/{rhel_8} mount/kclient/{mount overrides/{distro/stock/{k-stock rhel_8} ms-die-on-skipped}} objectstore-ec/bluestore-comp-ec-root overrides/{ignorelist_health ignorelist_wrongly_marked_down} tasks/workunit/snaps}
Job scheduled with name yuriw-2024-02-21_20:42:01-fs-wip-yuri10-testing-2024-02-21-0731-reef-distro-default-smithi and ID 7569921
2024-02-21 20:43:32,066.066 INFO:teuthology.suite.run:Scheduling fs/traceless/{begin clusters/fixed-2-ucephfs conf/{client mds mon osd} distro/{rhel_8} mount/fuse objectstore-ec/bluestore-comp-ec-root overrides/{frag ignorelist_health ignorelist_wrongly_marked_down} tasks/cfuse_workunit_suites_dbench traceless/50pc}
Job scheduled with name yuriw-2024-02-21_20:42:01-fs-wip-yuri10-testing-2024-02-21-0731-reef-distro-default-smithi and ID 7569922
2024-02-21 20:43:32,824.824 INFO:teuthology.suite.run:Scheduling fs/functional/{begin clusters/1a3s-mds-4c-client conf/{client mds mon osd} distro/{centos_8} mount/fuse objectstore/bluestore-ec-root overrides/{ignorelist_health ignorelist_wrongly_marked_down no_client_pidfile} tasks/asok_dump_tree}
Job scheduled with name yuriw-2024-02-21_20:42:01-fs-wip-yuri10-testing-2024-02-21-0731-reef-distro-default-smithi and ID 7569923
2024-02-21 20:43:33,542.542 INFO:teuthology.suite.run:Scheduling fs/thrash/multifs/{begin clusters/1a3s-mds-2c-client conf/{client mds mon osd} distro/{centos_8} mount/kclient/{mount overrides/{distro/testing/{flavor/ubuntu_latest k-testing} ms-die-on-skipped}} msgr-failures/none objectstore/bluestore-bitmap overrides/{client-shutdown frag ignorelist_health ignorelist_wrongly_marked_down multifs session_timeout thrashosds-health} tasks/{1-thrash/mon 2-workunit/cfuse_workunit_trivial_sync}}
Job scheduled with name yuriw-2024-02-21_20:42:01-fs-wip-yuri10-testing-2024-02-21-0731-reef-distro-default-smithi and ID 7569924
2024-02-21 20:43:34,280.280 INFO:teuthology.suite.run:Scheduling fs/functional/{begin clusters/1a3s-mds-4c-client conf/{client mds mon osd} distro/{rhel_8} mount/kclient/{mount overrides/{distro/stock/{k-stock rhel_8} ms-die-on-skipped}} objectstore/bluestore-bitmap overrides/{ignorelist_health ignorelist_wrongly_marked_down no_client_pidfile} tasks/auto-repair}
Job scheduled with name yuriw-2024-02-21_20:42:01-fs-wip-yuri10-testing-2024-02-21-0731-reef-distro-default-smithi and ID 7569925
2024-02-21 20:43:35,030.030 INFO:teuthology.suite.run:Scheduling fs/verify/{begin clusters/1a5s-mds-1c-client conf/{client mds mon osd} distro/{ubuntu/{latest overrides}} mount/kclient/{k-testing mount ms-die-on-skipped} objectstore-ec/bluestore-comp overrides/{ignorelist_health ignorelist_wrongly_marked_down mon-debug session_timeout} ranks/3 tasks/fsstress validater/lockdep}
Job scheduled with name yuriw-2024-02-21_20:42:01-fs-wip-yuri10-testing-2024-02-21-0731-reef-distro-default-smithi and ID 7569926
2024-02-21 20:43:35,775.775 INFO:teuthology.suite.run:Scheduling fs/upgrade/volumes/import-legacy/{bluestore-bitmap clusters/1-mds-2-client-micro conf/{client mds mon osd} overrides/{ignorelist_health ignorelist_wrongly_marked_down pg-warn} tasks/{0-nautilus 1-client 2-upgrade 3-verify} ubuntu_18.04}
Traceback (most recent call last):
  File "/cephfs/home/yuriw/teuthology/virtualenv/bin/teuthology-suite", line 8, in <module>
    sys.exit(main())
  File "/cephfs/home/yuriw/teuthology/scripts/suite.py", line 223, in main
    return teuthology.suite.main(args)
  File "/cephfs/home/yuriw/teuthology/teuthology/suite/__init__.py", line 145, in main
    run.prepare_and_schedule()
  File "/cephfs/home/yuriw/teuthology/teuthology/suite/run.py", line 434, in prepare_and_schedule
    num_jobs = self.schedule_suite()
  File "/cephfs/home/yuriw/teuthology/teuthology/suite/run.py", line 683, in schedule_suite
    self.schedule_jobs(jobs_missing_packages, jobs_to_schedule, name)
  File "/cephfs/home/yuriw/teuthology/teuthology/suite/run.py", line 515, in schedule_jobs
    util.schedule_fail(
  File "/cephfs/home/yuriw/teuthology/teuthology/suite/util.py", line 77, in schedule_fail
    raise ScheduleFailError(message, name)
teuthology.exceptions.ScheduleFailError: Scheduling yuriw-2024-02-21_20:42:01-fs-wip-yuri10-testing-2024-02-21-0731-reef-distro-default-smithi failed: At least one job needs packages that don't exist for hash 1c84f5840f7655c17f47847c2a475be6690cabb2.

**Comment by batrick** [comment]
jenkins test api

**Comment by batrick** [comment]
https://pulpito.ceph.com/pdonnell-2024-02-28_18:57:10-fs:upgrade:mds_upgrade_sequence-reef-distro-default-smithi/

with #55590 on v18.2.1.

To see if we reproduce

- https://tracker.ceph.com/issues/64502
- https://tracker.ceph.com/issues/64471

**Comment by vshankar** [comment]
We should merge this asap as teuthology upgrade jobs are failing and occupying system resources.

https://pulpito.ceph.com/teuthology-2024-02-29_02:25:02-upgrade:reef-x-main-distro-default-smithi/

**Review by vshankar — APPROVED** [review]

**Pull request merged**
