### PR TITLE
jewel: client: FAILED assert(root_ancestor->qtree == __null)

### PR DESCRIPTION
**Pull request by xiaoxichen**
http://tracker.ceph.com/issues/16313

### CODE REVIEW

**Comment by dachary** [comment]
infernalis has been EOL for a few months now, there does not seem to be a need for another release, even for upgrade purposes

**Comment by dachary** [comment]
@xiaoxichen I'm setting milestone jewel since this is targeting jewel really. If that's a mistake please let me know.

**Comment by dachary** [comment]
@jcsp does this backport look good to merge ? It passed the fs suite http://tracker.ceph.com/issues/16344#note-21 (except for unrelated valgrind failures and one transient failure that is, I believe, unrelated ).

**Comment by gregsfortytwo** [comment]
@ukernel, can you sign-off on this since John's on vacation another week?

**Comment by jcsp** [comment]
LGTM, this is a clean cherry-pick right?

**Comment by dachary** [comment]
@jcsp yes. Please do not merge anything until 10.2.3 is released. And welcome back :-)

**Comment by ukernel** [comment]
Signed-off-by

**Comment by dachary** [comment]
tested at 
http://pulpito.ceph.com/jspray-2016-10-10_15:27:25-fs-wip-jcsp-backports-20161010-distro-basic-mira/

**Pull request merged**
