### PR TITLE
cephadm: pass '-i' to docker|podman run for shell|enter

### PR DESCRIPTION
**Pull request by liewegas**
This allows us to pipe things to stdin.

Signed-off-by: Sage Weil <sage@newdream.net>

### CODE REVIEW

**Review by adk3798 — COMMENTED** [review]
This looks like it's changing shell/enter so we pass "-i" and "-t" separately rather than "-it" which at first glance I would think makes no difference since it's still just passing both flags. Can you provide an explanation as to how this allows us to pipe things in? I'm guessing there's some details with these flags I'm unaware of.

**Comment by liewegas** [comment]
```
root@eutow:~# echo foo | /usr/bin/docker run --rm  --entrypoint cat ceph/ceph@sha256:6dc0c8165c6c1dcba5cca4061455d954598afd1997c06f7aae21e135f7889b56 
root@eutow:~# echo foo | /usr/bin/docker run --rm -i  --entrypoint cat ceph/ceph@sha256:6dc0c8165c6c1dcba5cca4061455d954598afd1997c06f7aae21e135f7889b56 
foo
```
from the man page,
```
       -i, --interactive=true|false
          Keep STDIN open even if not attached. The default is false.

       When set to true, keep stdin open even if not attached.
```
which doesn't totally explain it for me (if i'm piping something in, isn't it attached?) but whatever--it makes it work (both for docker and podman).

**Review by adk3798 — APPROVED** [review]
I still don't understand how having "-i" and "-t" rather than "-it" produces different results but I also don't see it causing any harm. If it's necessary for your follow up apply function in qa then I see no reason not to merge it.

**Comment by adk3798** [comment]
> > I still don't understand how having "-i" and "-t" rather than "-it" produces different results but I also don't see it causing any harm. If it's necessary for your follow up apply function in qa then I see no reason not to merge it.
> 
> For the path with no command (`cephadm shell`), there is no difference. It's the other path (`cephadm shell foo < in.txt`) where it matters--the `-i` is needed for the pipe to stdin to work.

I understand why we need the -i, I just though by having "-it" as it was we were already providing both the --interactive (-i)  and --tty (-t) flag so that would be covered.

**Comment by liewegas** [comment]
> > > I still don't understand how having "-i" and "-t" rather than "-it" produces different results but I also don't see it causing any harm. If it's necessary for your follow up apply function in qa then I see no reason not to merge it.
> > 
> > 
> > For the path with no command (`cephadm shell`), there is no difference. It's the other path (`cephadm shell foo < in.txt`) where it matters--the `-i` is needed for the pipe to stdin to work.
> 
> I understand why we need the -i, I just though by having "-it" as it was we were already providing both the --interactive (-i) and --tty (-t) flag so that would be covered.

In the current code ``-it`` is only added if ``ctx.command`` is false

**Comment by adk3798** [comment]
> > > > I still don't understand how having "-i" and "-t" rather than "-it" produces different results but I also don't see it causing any harm. If it's necessary for your follow up apply function in qa then I see no reason not to merge it.
> > > 
> > > 
> > > For the path with no command (`cephadm shell`), there is no difference. It's the other path (`cephadm shell foo < in.txt`) where it matters--the `-i` is needed for the pipe to stdin to work.
> > 
> > 
> > I understand why we need the -i, I just though by having "-it" as it was we were already providing both the --interactive (-i) and --tty (-t) flag so that would be covered.
> 
> In the current code `-it` is only added if `ctx.command` is false

Oh, I completely missed this. Oops. All looks good to me in that case.

**Pull request merged**
