### PR TITLE
rbd: make possible to merge image import file with import diff

### PR DESCRIPTION
**Pull request by trociny**
Sometime it is useful to be able to merge an image file obtained with `rbd export` with a consequent diff file obtained with `rbd export-diff` to produce a single "export" file.

Before this change one would need the access to a Ceph cluster (a rbd pool) to merge the files by importing them to an image and exporting back.

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by trociny** [comment]
jenkins test make check

**Comment by satoru-takeuchi** [comment]
How about merging an already-exported image file and a diff by `rbd merge-diff`? IMO, this interface looks more natural than do the same thing in `rbd import-diff`. Anyway, I'm very interested in this feature and would like to contribute to this issue by testing and/or any other ways. 

The related discussion: https://lists.ceph.io/hyperkitty/list/ceph-users@ceph.io/message/3XIF3JJQZ347ASMFF2WBNHNKXX6BUPKL/

**Comment by trociny** [comment]
> How about merging an already-exported image file and a diff by rbd merge-diff? IMO, this interface looks more natural than do the same thing in rbd import-diff.

To me it is arguable what interface looks more natural, and technically it was much easier implement in import-diff (do the same, just write to a file), while in merge-diff merging two diffs and merging an image file and a diff will be different. Also note, the image file may be in v1 or v2 format, and with v2 format import-diff stores snapshots. I.e if you later import the v2 format file to an rbd image it will have the snapshots, the same way if you would import directly to the rbd image.

Anyway I am open to further discussion if people think merge-diff should be better here.

> The related discussion: https://lists.ceph.io/hyperkitty/list/ceph-users@ceph.io/message/3XIF3JJQZ347ASMFF2WBNHNKXX6BUPKL/

With the current (in the tree) code, I suppose you could use a little different approach to achieve your goal: instead of doing `rbd export` to create a full backup in the first step, you could create a snapshot and create a full backup in diff format with `rbd export-diff image@snap`. Then in the step 3 you would merge two files in diff format.

**Comment by satoru-takeuchi** [comment]
> To me it is arguable what interface looks more natural, and technically it was much easier implement in import-diff (do the same, just write to a file), while in merge-diff merging two diffs and merging an image file and a diff will be different. Also note, the image file may be in v1 or v2 format, and with v2 format import-diff stores snapshots. I.e if you later import the v2 format file to an rbd image it will have the snapshots, the same way if you would import directly to the rbd image.

I see. Thank you for the explanation.

> With the current (in the tree) code, I suppose you could use a little different approach to achieve your goal: instead of doing rbd export to create a full backup in the first step, you could create a snapshot and create a full backup in diff format with rbd export-diff image@snap. Then in the step 3 you would merge two files in diff format.

I'll try it.

**Comment by satoru-takeuchi** [comment]
> > With the current (in the tree) code, I suppose you could use a little different approach to achieve your goal: instead of doing rbd export to create a full backup in the first step, you could create a snapshot and create a full backup in diff format with rbd export-diff image@snap. Then in the step 3 you would merge two files in diff format.
> 
> I'll try it.

It worked fine. Thank you very much!

**Pull request closed without merging**
