### PR TITLE
nautilus: qa/tasks/mgr/test_progress: fix wait_until_equal

### PR DESCRIPTION
**Pull request by kamoltat**
Fixes: https://tracker.ceph.com/issues/50006

---

Nautilus ceph_test_case doesn't have period arg
so remove that in wait_until_equal. Also, increase
time to wait for complete events by using RECOVERY_PERIOD
instead of EVENT_CREATION_PERIOD

Also, Nautilus is missing the commit: 
b03537949abd8d453aa06c1580a4578868904bd1
This is a fix to this issue:
https://tracker.ceph.com/issues/40618

backporting the relevant commits from Octopus PRs:
#39360
backporting relevant commits from master PRs:
#30095

Fixes: https://tracker.ceph.com/issues/48824

Signed-off-by: Kamoltat ksirivad@redhat.com

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by kamoltat** [comment]
jenkins run Signed-off-by

**Comment by kamoltat** [comment]
jenkins retest this please

**Comment by neha-ojha** [comment]
@kamoltat you need to fix your signed-off-by format, it needs `< email >`

**Review by tchaikov — CHANGES_REQUESTED** [review]
@kamoltat you need to explain why this change is not cherry-picked from master in the commit message. otherwise please use `git cherry-pick -x` to cherry-pick the fix.

**Comment by kamoltat** [comment]
jenkins test make check

**Comment by kamoltat** [comment]
jenkins test api

**Review by smithfarm — CHANGES_REQUESTED** [review]
@kamoltat In my opinion, a better approach here would be to:

1. wait until the Octopus fix https://github.com/ceph/ceph/pull/39360 is merged
2. cherry-pick the Octopus fix to Nautilus

Would that be OK for you?

**Comment by smithfarm** [comment]
@tchaikov @kamoltat We exhort folks to always "cherry-pick from master" (and, if that can't be done, explain why in the commit message). But there's a wrinkle to that. Actually, fixes shoudl be cherry-picked from the most recent version in which they appear. So, in this case the fix needs to be cherry-picked from octopus once it lands there.

**Comment by smithfarm** [comment]
@ideepika This is still waiting for the octopus commit 8df54fe149c6d9cbc39f7348c959396c02e88235 to be merged. See https://github.com/ceph/ceph/pull/39360

Is this fix needed for 14.2.17 QE? In that case, I suggest to merge #39360 and then merge this one.

**Comment by smithfarm** [comment]
The reason why #39360 should be merged first is because the commit in this PR is a cherry-pick of the commit in #39360. The cherry-pick should not be merged before the original!

**Comment by ideepika** [comment]
> The reason why #39360 should be merged first is because the commit in this PR is a cherry-pick of the commit in #39360. The cherry-pick should not be merged before the original!

Nope, should be fine to keep hold in this case.

**Comment by ideepika** [comment]
@kamoltat can you take a look:
```
2021-03-31T20:19:54.931 INFO:tasks.cephfs_test_runner:ERROR: test_osd_came_back (tasks.mgr.test_progress.TestProgress)
2021-03-31T20:19:54.931 INFO:tasks.cephfs_test_runner:----------------------------------------------------------------------
2021-03-31T20:19:54.932 INFO:tasks.cephfs_test_runner:Traceback (most recent call last):
2021-03-31T20:19:54.932 INFO:tasks.cephfs_test_runner:  File "/home/teuthworker/src/github.com_ceph_ceph-c_d204ff17eed117bbc2af3bca37493c1443640102/qa/tasks/mgr/test_progress.py", line 278, in test_osd_came_back
2021-03-31T20:19:54.933 INFO:tasks.cephfs_test_runner:    timeout=self.RECOVERY_PERIOD)
2021-03-31T20:19:54.933 INFO:tasks.cephfs_test_runner:  File "/home/teuthworker/src/github.com_ceph_ceph-c_d204ff17eed117bbc2af3bca37493c1443640102/qa/tasks/ceph_test_case.py", line 192, in wait_until_true
2021-03-31T20:19:54.934 INFO:tasks.cephfs_test_runner:    if condition():
2021-03-31T20:19:54.935 INFO:tasks.cephfs_test_runner:  File "/home/teuthworker/src/github.com_ceph_ceph-c_d204ff17eed117bbc2af3bca37493c1443640102/qa/tasks/mgr/test_progress.py", line 277, in <lambda>
2021-03-31T20:19:54.935 INFO:tasks.cephfs_test_runner:    self.wait_until_true(lambda: self._is_complete(ev2['id']),
2021-03-31T20:19:54.936 INFO:tasks.cephfs_test_runner:TypeError: 'NoneType' object is not subscriptable
2021-03-31T20:19:54.936 INFO:tasks.cephfs_test_runner:
2021-03-31T20:19:54.937 INFO:tasks.cephfs_test_runner:----------------------------------------------------------------------
2021-03-31T20:19:54.937 INFO:tasks.cephfs_test_runner:Ran 1 test in 95.586s
2021-03-31T20:19:54.938 INFO:tasks.cephfs_test_runner:
2021-03-31T20:19:54.938 INFO:tasks.cephfs_test_runner:FAILED (errors=1)
```
http://qa-proxy.ceph.com/teuthology/yuriw-2021-03-31_19:52:34-rados-wip-yuri8-testing-2021-03-29-0949-nautilus-distro-basic-smithi/6013699/teuthology.log

**Comment by kamoltat** [comment]
> qa/tasks/mgr/test_progress.py

So the problem is actually that it is missing `if ev2 is not None:` I don’t know why in https://github.com/ceph/ceph/commit/5ecd69099d2943e90de88fc7596497c2f86fab91 It it did not get added since all other versions (octopus - current master) has this. But my new push should help fix this.

**Comment by smithfarm** [comment]
Comparing this commit with the octopus commit is is supposed to have been cherry-picked from - https://github.com/ceph/ceph/commit/df41ea7467db3b40776030865896af0102129283 - it seems like this commit is doing a lot more.

Would it make sense to look at `git blame df41ea7467db3b40776030865896af0102129283 -- qa/tasks/mgr/test_progress.py` and find out which commit(s) made those extra changes? And then cherry-pick those commits?

**Comment by kamoltat** [comment]
> git blame

that makes sense, I'll try that thank you

**Review by ideepika — APPROVED** [review]
tests looks good thanks @smithfarm @kamoltat !
https://trello.com/c/R6ClYBUf/1197-wip-yuri8-testing-2021-04-06-1934-nautilus-old-wip-yuri8-testing-2021-04-05-1412-nautilus-old-wip-yuri8-testing-2021-03-29-0949

**Pull request merged**
