### PR TITLE
mon: Don't forget set read_tier/write_tier for 'osd tier add-cache'.

### PR DESCRIPTION
**Pull request by majianpeng**
Signed-off-by: Jianpeng Ma <jianpeng.ma@intel.com>

### CODE REVIEW

**Comment by majianpeng** [comment]
@liewegas . for 'osd tier add-cache' is it include all steps which add/cache-mode/set-overlay? I don't find doc which descript ? Or it only include 'add/cache-mode', it still need set-overlay?  Thanks!

**Comment by liewegas** [comment]
yes, this looks right.  does test/cephtool-test-mon.sh in your build environment?

ideally we should add a qa/cephtool/test.sh test that verifies this is set correctly.  thanks!

**Comment by majianpeng** [comment]
yes mean there is a bug and my patch right?  if so, i'll add do test/cephtool-test-mon.sh and add test case.

**Comment by liewegas** [comment]
yeah, the patch looks right.  please add a test case, too!  thanks

**Comment by majianpeng** [comment]
sage, updated and review again. Thanks!

**Comment by liewegas** [comment]
i'm going to retarget this at hammer in another branch to test.. the rgw teutholgoy task seems to be the only thing using add-cache so it probably hasn't been actually utilizing the cache pool :(

**Comment by liewegas** [comment]
merged manually to hammer branch

**Pull request closed without merging**
