### PR TITLE
luminous: client: dual client segfault with racing ceph_shutdown

### PR DESCRIPTION
**Pull request by shinobu-x**
http://tracker.ceph.com/issues/21525

### CODE REVIEW

**Comment by shinobu-x** [comment]
test this please

**Comment by tchaikov** [comment]
- http://pulpito.ceph.com/kchai-2017-11-07_15:13:35-rados-wip-kefu-testing-2017-11-06-0102-distro-basic-smithi/
- http://pulpito.ceph.com/kchai-2017-11-06_02:23:20-rados-wip-kefu-testing-2017-11-06-0102-distro-basic-mira/
- http://pulpito.ceph.com/kchai-2017-11-08_06:05:18-rados-wip-kefu-testing-2017-11-06-0102-distro-basic-mira/

the failed test is addressed by #18675

**Comment by jdurgin** [comment]
We should include https://github.com/ceph/ceph/pull/18929 at the same time as this one

**Comment by smithfarm** [comment]
closing in favor of https://github.com/ceph/ceph/pull/20082

**Comment by yuriw** [comment]
@shinobu-x @jdurgin pls rebase

--- pr 18721 --- pulling https://github.com/shinobu-x/ceph.git branch wip-luminous-20988
remote: Counting objects: 23, done.
remote: Total 23 (delta 18), reused 18 (delta 18), pack-reused 5
Unpacking objects: 100% (23/23), done.
From https://github.com/shinobu-x/ceph
 * branch            wip-luminous-20988 -> FETCH_HEAD
Auto-merging src/test/libcephfs/test.cc
CONFLICT (content): Merge conflict in src/test/libcephfs/test.cc
Auto-merging src/common/lockdep.cc
CONFLICT (content): Merge conflict in src/common/lockdep.cc
Adding qa/suites/rados/basic/d-require-luminous/at-mkfs.yaml
Adding qa/suites/rados/basic/d-require-luminous/at-end.yaml
Automatic merge failed; fix conflicts and then commit the result.
Traceback (most recent call last):
  File "/home/yuriw/wip_master/src/script/build-integration-branch", line 62, in <module>
    assert not r
AssertionError

**Pull request closed without merging**
