### PR TITLE
  ceph_monstore_tool: fix the illegal memory access when update_paxos

### PR DESCRIPTION
**Pull request by hjwsm1989**
Signed-off-by: huangjun <hjwsm1989@gmail.com>

### CODE REVIEW

**Comment by hjwsm1989** [comment]
@tchaikov please take a look

**Comment by tchaikov** [comment]
@hjwsm1989 before merging this PR, could you update the commit message with a "Conflicts:" section explaining why this change is not cherry-picked from master? thanks!

**Comment by smithfarm** [comment]
It would also be nice to have a tracker issue explaining what the bug is that this is fixing.

**Comment by hjwsm1989** [comment]
@tchaikov this is from the hammer branch, in this PR: https://github.com/ceph/ceph/pull/11125
i want to add commit message like this:
    Conflicts:
        Introduced  in this hammer backport https://github.com/ceph/ceph/pull/11125, we use const char** instead of vector,which result the illegal memory access.

is that ok?

**Comment by tchaikov** [comment]
@hjwsm1989 i understand that you are fixing an issue introduced by #11125, but in general we tend to backport fixes from master. and this fix is only for hammer. that's why we want to explain the reason why we are not doing a cherry-pick here. so i'd recommend something like:

```
    Conflicts:
        we don't use C++11 in hammer. and this fix addresses the issue introduced by https://github.com/ceph/ceph/pull/11125, where we are iterating in a plain array instead of a std::vector in master. so this change is not cherry-picked from master.
```

**Comment by hjwsm1989** [comment]
@tchaikov ok, i will update the commit message.

**Comment by hjwsm1989** [comment]
@smithfarm i opened an issue http://tracker.ceph.com/issues/19070

**Comment by hjwsm1989** [comment]
@smithfarm i add a ticket http://tracker.ceph.com/issues/19070

**Comment by tchaikov** [comment]
@hjwsm1989 could you put "Fixes: http://tracker.ceph.com/issues/19070" in your commit message right before your "Signed-off-by" tag?

**Comment by hjwsm1989** [comment]
@tchaikov done

**Comment by tchaikov** [comment]
thanks!

**Comment by smithfarm** [comment]
@hjwsm1989 Thanks for the fix. We'll do some test runs on it and report back here.

**Comment by smithfarm** [comment]
Hammer is EOL.

**Pull request closed without merging**
