### PR TITLE
ceph-volume: use importlib from stdlib on Python 3.8 and up

### PR DESCRIPTION
**Pull request by tchaikov**
since packaging was apparently removed from pkg_resources, let's use importlib.metadata when it is available and use importlib_metadata on older Python versions.

Refs https://tracker.ceph.com/issues/66201
Signed-off-by: Kefu Chai <tchaikov@gmail.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Comment by tchaikov** [comment]
@guits hi Guillaume, could you help review this change?

**Comment by tchaikov** [comment]
i also need to update `ceph.spec.in` to cater the needs on different distros with rpm packaging system. but would be great if this PR can get some early feedbacks.

**Review by phlogistonjohn — COMMENTED** [review]
Python changes generally look OK to me. Although I had to stare hard at `importlib.metadata` vs `importlib_metadata` for a long while to see the difference.

I'll wait until you have made the spec file changes you mentioned before giving final approval, unless you would like otherwise.

**Comment by tchaikov** [comment]
v2:

- use `pkg_resources.iter_entry_points()` as the fall back.

@phlogistonjohn thank you for your review John. per https://pkgs.org/search/?q=importlib_metadata, this package is not available on, for instance, RHEL8, where the default python3 is Python 3.6.8. so i am using instead `pkg_resources.iter_entry_points` as the fallback in the latest revision. the upside is that it does not require the dependency of `python3-importlib_metadata`, the downside is that the patch is a little bit more complicated as the function name are different in `pkg_resources`.

**Comment by tchaikov** [comment]
jenkins test make check

**Review by phlogistonjohn — APPROVED** [review]
looks ok to me

**Comment by tchaikov** [comment]
jenkins test windows

**Comment by tchaikov** [comment]
jenkins test windows

**Comment by tchaikov** [comment]
i will try to run at least a couple tests involving ceph-volume to sanity test this change.

**Comment by tchaikov** [comment]
https://pulpito.ceph.com/kchai-2024-05-31_06:02:41-ceph-deploy-wip-use-importlib-kefu-2-distro-default-smithi/

**Comment by nizamial09** [comment]
We started getting the below error on our kcli based environments using cephadm probably after this change. Locally I did a normal bootstrap and saw the health warning.

```
[ceph: root@ceph-node-00 /]# ceph health detail
HEALTH_WARN failed to probe daemons or devices; OSD count 0 < osd_pool_default_size 3
[WRN] CEPHADM_REFRESH_FAILED: failed to probe daemons or devices
    host ceph-node-00 `cephadm ceph-volume` failed: cephadm exited with an error code: 1, stderr: Inferring config /var/lib/ceph/8df4cf64-2196-11ef-b317-5254002b3226/mon.ceph-node-00/config
Non-zero exit code 1 from /usr/bin/podman run --rm --ipc=host --stop-signal=SIGTERM --net=host --entrypoint /usr/sbin/ceph-volume --privileged --group-add=disk --init -e CONTAINER_IMAGE=quay.ceph.io/ceph-ci/ceph@sha256:1b15b7a25500815a8f1461030e3e44f7d8c33c82369e3bab6ef02b778d1bd8c9 -e NODE_NAME=ceph-node-00 -e CEPH_VOLUME_SKIP_RESTORECON=yes -e CEPH_VOLUME_DEBUG=1 -v /var/run/ceph/8df4cf64-2196-11ef-b317-5254002b3226:/var/run/ceph:z -v /var/log/ceph/8df4cf64-2196-11ef-b317-5254002b3226:/var/log/ceph:z -v /var/lib/ceph/8df4cf64-2196-11ef-b317-5254002b3226/crash:/var/lib/ceph/crash:z -v /run/systemd/journal:/run/systemd/journal -v /dev:/dev -v /run/udev:/run/udev -v /sys:/sys -v /run/lvm:/run/lvm -v /run/lock/lvm:/run/lock/lvm -v /var/lib/ceph/8df4cf64-2196-11ef-b317-5254002b3226/selinux:/sys/fs/selinux:ro -v /:/rootfs -v /etc/hosts:/etc/hosts:ro -v /tmp/ceph-tmpdsud63i6:/etc/ceph/ceph.conf:z quay.ceph.io/ceph-ci/ceph@sha256:1b15b7a25500815a8f1461030e3e44f7d8c33c82369e3bab6ef02b778d1bd8c9 inventory --format=json-pretty --filter-for-batch
/usr/bin/podman: stderr exception caught by decorator
/usr/bin/podman: stderr Traceback (most recent call last):
/usr/bin/podman: stderr   File "/usr/lib/python3.9/site-packages/ceph_volume/decorators.py", line 59, in newfunc
/usr/bin/podman: stderr     return f(*a, **kw)
/usr/bin/podman: stderr   File "/usr/lib/python3.9/site-packages/ceph_volume/main.py", line 110, in main
/usr/bin/podman: stderr     self.enable_plugins()
/usr/bin/podman: stderr   File "/usr/lib/python3.9/site-packages/ceph_volume/main.py", line 75, in enable_plugins
/usr/bin/podman: stderr     plugins = _load_library_extensions()
/usr/bin/podman: stderr   File "/usr/lib/python3.9/site-packages/ceph_volume/main.py", line 180, in _load_library_extensions
/usr/bin/podman: stderr     for ep in entry_points(group=group):
/usr/bin/podman: stderr TypeError: entry_points() got an unexpected keyword argument 'group'
/usr/bin/podman: stderr Traceback (most recent call last):
/usr/bin/podman: stderr   File "/usr/sbin/ceph-volume", line 33, in <module>
/usr/bin/podman: stderr     sys.exit(load_entry_point('ceph-volume==1.0.0', 'console_scripts', 'ceph-volume')())
/usr/bin/podman: stderr   File "/usr/lib/python3.9/site-packages/ceph_volume/main.py", line 46, in __init__
/usr/bin/podman: stderr     self.main(self.argv)
/usr/bin/podman: stderr   File "/usr/lib/python3.9/site-packages/ceph_volume/decorators.py", line 59, in newfunc
/usr/bin/podman: stderr     return f(*a, **kw)
/usr/bin/podman: stderr   File "/usr/lib/python3.9/site-packages/ceph_volume/main.py", line 110, in main
/usr/bin/podman: stderr     self.enable_plugins()
/usr/bin/podman: stderr   File "/usr/lib/python3.9/site-packages/ceph_volume/main.py", line 75, in enable_plugins
/usr/bin/podman: stderr     plugins = _load_library_extensions()
/usr/bin/podman: stderr   File "/usr/lib/python3.9/site-packages/ceph_volume/main.py", line 180, in _load_library_extensions
/usr/bin/podman: stderr     for ep in entry_points(group=group):
/usr/bin/podman: stderr TypeError: entry_points() got an unexpected keyword argument 'group'
Traceback (most recent call last):
  File "/usr/lib64/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib64/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/var/lib/ceph/8df4cf64-2196-11ef-b317-5254002b3226/cephadm.7007c93708f27a439bb9273ebfa4caf4335548ffd3ae152e4a8b908274ae7f45/__main__.py", line 5647, in <module>
  File "/var/lib/ceph/8df4cf64-2196-11ef-b317-5254002b3226/cephadm.7007c93708f27a439bb9273ebfa4caf4335548ffd3ae152e4a8b908274ae7f45/__main__.py", line 5635, in main
  File "/var/lib/ceph/8df4cf64-2196-11ef-b317-5254002b3226/cephadm.7007c93708f27a439bb9273ebfa4caf4335548ffd3ae152e4a8b908274ae7f45/__main__.py", line 408, in _infer_config
  File "/var/lib/ceph/8df4cf64-2196-11ef-b317-5254002b3226/cephadm.7007c93708f27a439bb9273ebfa4caf4335548ffd3ae152e4a8b908274ae7f45/__main__.py", line 323, in _infer_fsid
  File "/var/lib/ceph/8df4cf64-2196-11ef-b317-5254002b3226/cephadm.7007c93708f27a439bb9273ebfa4caf4335548ffd3ae152e4a8b908274ae7f45/__main__.py", line 436, in _infer_image
  File "/var/lib/ceph/8df4cf64-2196-11ef-b317-5254002b3226/cephadm.7007c93708f27a439bb9273ebfa4caf4335548ffd3ae152e4a8b908274ae7f45/__main__.py", line 310, in _validate_fsid
  File "/var/lib/ceph/8df4cf64-2196-11ef-b317-5254002b3226/cephadm.7007c93708f27a439bb9273ebfa4caf4335548ffd3ae152e4a8b908274ae7f45/__main__.py", line 3380, in command_ceph_volume
  File "/var/lib/ceph/8df4cf64-2196-11ef-b317-5254002b3226/cephadm.7007c93708f27a439bb9273ebfa4caf4335548ffd3ae152e4a8b908274ae7f45/cephadmlib/call_wrappers.py", line 310, in call_throws
RuntimeError: Failed command: /usr/bin/podman run --rm --ipc=host --stop-signal=SIGTERM --net=host --entrypoint /usr/sbin/ceph-volume --privileged --group-add=disk --init -e CONTAINER_IMAGE=quay.ceph.io/ceph-ci/ceph@sha256:1b15b7a25500815a8f1461030e3e44f7d8c33c82369e3bab6ef02b778d1bd8c9 -e NODE_NAME=ceph-node-00 -e CEPH_VOLUME_SKIP_RESTORECON=yes -e CEPH_VOLUME_DEBUG=1 -v /var/run/ceph/8df4cf64-2196-11ef-b317-5254002b3226:/var/run/ceph:z -v /var/log/ceph/8df4cf64-2196-11ef-b317-5254002b3226:/var/log/ceph:z -v /var/lib/ceph/8df4cf64-2196-11ef-b317-5254002b3226/crash:/var/lib/ceph/crash:z -v /run/systemd/journal:/run/systemd/journal -v /dev:/dev -v /run/udev:/run/udev -v /sys:/sys -v /run/lvm:/run/lvm -v /run/lock/lvm:/run/lock/lvm -v /var/lib/ceph/8df4cf64-2196-11ef-b317-5254002b3226/selinux:/sys/fs/selinux:ro -v /:/rootfs -v /etc/hosts:/etc/hosts:ro -v /tmp/ceph-tmpdsud63i6:/etc/ceph/ceph.conf:z quay.ceph.io/ceph-ci/ceph@sha256:1b15b7a25500815a8f1461030e3e44f7d8c33c82369e3bab6ef02b778d1bd8c9 inventory --format=json-pretty --filter-for-batch

```

**Comment by guits** [comment]
> /usr/bin/podman: stderr TypeError: entry_points() got an unexpected keyword argument 'group'

see https://github.com/ceph/ceph/pull/57830

**Comment by zdover23** [comment]
https://github.com/ceph/ceph/pull/58004 - Squid backport
https://github.com/ceph/ceph/pull/58005 - Reef backport
https://github.com/ceph/ceph/pull/58006 - Quincy backport

**Pull request merged**
