### PR TITLE
mimic: ceph-volume prints errors to stdout with --format json

### PR DESCRIPTION
**Pull request by jan--f**
https://tracker.ceph.com/issues/41138

### CODE REVIEW

**Comment by alfredodeza** [comment]
jenkins test ceph-volume tox

**Comment by jan--f** [comment]
jenkins test ceph-volume tox

**Comment by jan--f** [comment]
This needs the missing backport that I added to #29417

**Comment by jan--f** [comment]
jenkins test ceph-volume tox

**Comment by jan--f** [comment]
All test pass now.

**Pull request merged**
