### PR TITLE
jewel: test/ceph_test_msgr: do not use Message::middle for holding transient…

### PR DESCRIPTION
**Pull request by tchaikov**
http://tracker.ceph.com/issues/17748

### CODE REVIEW

**Comment by tchaikov** [comment]
@dachary tested.

**Comment by dachary** [comment]
@tchaikov excellent, thanks !

**Comment by dachary** [comment]
building in gitbuilders at wip-17728-jewel

**Comment by dachary** [comment]
<pre>
teuthology-suite -k distro --priority 101 --suite rados --subset $(expr $RANDOM % 2000)/2000 --suite-branch wip-17734-jewel --email loic@dachary.org --ceph wip-17728-jewel --machi\
ne-type smithi
</pre>

* **running** http://pulpito.ceph.com/loic-2016-11-03_14:51:34-rados-wip-17728-jewel-distro-basic-smithi

**Pull request merged**
