### PR TITLE
doc/man/8: Fix spelling in user rename example

### PR DESCRIPTION
**Pull request by taggelos**
This commit concerns the following page https://docs.ceph.com/en/latest/man/8/radosgw-admin/
Fix user name in Example for radosgw-admin

Signed-off-by: Aggelos Toumasis <toumasis.aggelos@gmail.com>

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [X] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [X] No impact that needs to be tracked
- Documentation (select at least one)
  - [X] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [X] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by anthonyeleven** [comment]
LGTM, nice catch.

**Review by anthonyeleven — APPROVED** [review]

**Review by anthonyeleven — CHANGES_REQUESTED** [review]
Nice catch.  Please amend to the format preferred for Ceph contributions:
* The PR and commit titles should be `directory`:`action`, so here something like `doc/man/8: Fix spelling in user rename example`
* Please add a signed-off-by line to both the PR description and the commit description:
`Signed-off-by: Aggelos Toumasis <youraddress@yourdomain>`

As an example here's one of my doc contributions: https://github.com/ceph/ceph/pull/44793

**Comment by taggelos** [comment]
> Nice catch. Please amend to the format preferred for Ceph contributions:
> 
> * The PR and commit titles should be `directory`:`action`, so here something like `doc/man/8: Fix spelling in user rename example`
> * Please add a signed-off-by line to both the PR description and the commit description:
>   `Signed-off-by: Aggelos Toumasis <youraddress@yourdomain>`
> 
> As an example here's one of my doc contributions: #44793

Thank you for the help!

**Review by anthonyeleven — APPROVED** [review]

**Comment by anthonyeleven** [comment]
Looks good now!  Thanks for contributing.  I know this may seem tedious, but it quickly becomes.  You can simplify the signing:
```
git config --global user.name "Your Name"
git config --global user.email "youremail@yourdomain.com"
git commit -s -m "my/dir: recombinate the zoplex levels"
```

**Pull request merged**
