### PR TITLE
os/bluestore: avoid resharding if the last shard size fall below shar…

### PR DESCRIPTION
**Pull request by ifed01**
…d min size. This might cause permanent resharding since the last shard tend to be small.

Signed-off-by: Igor Fedotov <ifedotov@mirantis.com>

### CODE REVIEW

**Comment by ifed01** [comment]
@somnathr. Yeah it has to be !=  shard.end() indeed. Updated. Thanks.

**Comment by somnathr** [comment]
LGTM

**Comment by xiexingguo** [comment]
LGTM also

**Comment by ifed01** [comment]
[       OK ] ObjectStore/StoreTest.TooManyBlobsTest/2 (75167 ms)
[----------] 66 tests from ObjectStore/StoreTest (11530171 ms total)

[----------] Global test environment tear-down
[==========] 66 tests from 1 test case ran. (11530172 ms total)
[  PASSED  ] 66 tests.

**Pull request merged**
