### PR TITLE
common/TrackedOp: Using xlist.size() when calc ops which in flight.

### PR DESCRIPTION
**Pull request by majianpeng**
Signed-off-by: Jianpeng Ma <jianpeng.ma@intel.com>

### CODE REVIEW

**Comment by majianpeng** [comment]
@tchaikov . Have you time review this?  Thanks!

**Comment by tchaikov** [comment]
@majianpeng, i think the change is safe. but IMO, i am not sure if "dump_ops_in_flight" is the bottleneck of the performance, or if it is worth trading the readability for the performance.

**Comment by majianpeng** [comment]
@tchaikov . Yes, it's not a bottleneck. I think dump_ops_in_flight.size() don't  recount. It already exists.

**Comment by tchaikov** [comment]
yeah, i understand your rationale behind this change. `dump_ops_in_flight.size()` is an O(1), while existing one is a O(n).

maybe we can see if there are other opinions regarding this.

**Comment by majianpeng** [comment]
check again in common/TrackedOp.{h,cc}. There is no like this.

**Comment by majianpeng** [comment]
@tchaikov  ping!

**Comment by majianpeng** [comment]
@tchaikov  Ping!

**Comment by tchaikov** [comment]
@majianpeng sorry for the latency.

> check again in common/TrackedOp.{h,cc}. There is no like this.

could you elaborate a little bit what you mean?

i don't have strong opinion regarding to this pull request though. the reason why i don't like it is

- it is not a bottleneck.
- and the change does not help with readability.

so i'd suggest you wait for other opinions.

**Comment by majianpeng** [comment]
sorry i misunderstand you works. Ok, i cc @gregsfortytwo. Hi Greg, can you review this? Thanks!

**Comment by majianpeng** [comment]
@gregsfortytwo . I close this because #5137. I'll adopt your suggestion which add a count for ops in flight.

**Pull request closed without merging**
