### PR TITLE
qa: suppress __trans_list_add valgrind warning

### PR DESCRIPTION
**Pull request by batrick**
Fixes: https://tracker.ceph.com/issues/65779

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Comment by batrick** [comment]
jenkins test make check arm64

**Comment by batrick** [comment]
This PR is under test in [https://tracker.ceph.com/issues/66609](https://tracker.ceph.com/issues/66609).

**Review by vshankar — APPROVED** [review]

**Comment by batrick** [comment]
This PR is under test in [https://tracker.ceph.com/issues/66822](https://tracker.ceph.com/issues/66822).

**Comment by batrick** [comment]
Tested this specifically after a few iterations on the correct suppression (I was missing an underscore /sigh).

https://pulpito.ceph.com/pdonnell-2024-07-23_17:58:55-fs:verify-main-distro-default-smithi/

It works:

```
<suppcounts>
  <pair>
    <count>21</count>
    <name>libstdc++ leak on xenial</name>
  </pair>
  <pair>
    <count>10</count>
    <name>tracker #65779: __trans_list_add annoyance</name>
  </pair>
  <pair>
    <count>2</count>
    <name>tcmalloc: string</name>
  </pair>
  <pair>
    <count>8</count>
    <name>something in glibc</name>
  </pair>
  <pair>
    <count>10997</count>
    <name>&lt;allthefrees, so we can behave with tcmalloc&gt;</name>
  </pair>
</suppcounts>
```

/teuthology/pdonnell-2024-07-23_17:58:55-fs:verify-main-distro-default-smithi/7814267/remote/smithi067/log/valgrind/mds.a.log.gz

**Comment by batrick** [comment]
@cbodley fyi suppressions are now included in the valgrind logs now.

**Comment by cbodley** [comment]
> @cbodley fyi suppressions are now included in the valgrind logs now.

very cool, cc @mkogan1

**Comment by batrick** [comment]
jenkins test make check arm64

**Comment by batrick** [comment]
jenkins test make check

**Pull request merged**
