### PR TITLE
cmake: bump up required cmake version to 2.8.12

### PR DESCRIPTION
**Pull request by tchaikov**

### CODE REVIEW

**Comment by tchaikov** [comment]
retest this please.

**Comment by alimaredia** [comment]
@tchaikov lgtm, do I need to worry about the `make check (arm64)` failure?

**Comment by tchaikov** [comment]
thanks for your review @alimaredia ! i don't think it's relevant.

let me try the spell:

retest this please.

**Comment by tchaikov** [comment]
fwiw, https://github.com/ceph/ceph/pull/18283 has the same failure of test_objectstore_memstore.sh
```
[ RUN      ] ObjectStore/StoreTest.Synthetic/0

```

see http://tracker.ceph.com/issues/20738

**Pull request merged**
