### PR TITLE
test: monitor thrasher wait until quorum

### PR DESCRIPTION
**Pull request by NitzanMordhai**
With 1 sec. delay we may sometimes fail to get correct length of quorum since the monitor didn't updated on time.
With the following fix, we will wait for quorum and check every few seconds (3) until timeout (30).

Fixes: https://tracker.ceph.com/issues/52316

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by kamoltat** [comment]
@NitzanMordhai instead of increasing the thrash_delay, is there a way we can do this without relying on just waiting 5 seconds and do 1 check? I wonder if we can have something like `wait_until_quorum(3, 30)` where we check the quorum every like 5 seconds for quorum size of 3, but the time limit is 30s total so you get 6 tries, but if you hit 3 in the first try then we move on.

**Comment by NitzanMordhai** [comment]
> @NitzanMordhai instead of increasing the thrash_delay, is there a way we can do this without relying on just waiting 5 seconds and do 1 check? I wonder if we can have something like `wait_until_quorum(3, 30)` where we check the quorum every like 5 seconds for quorum size of 3, but the time limit is 30s total so you get 6 tries, but if you hit 3 in the first try then we move on.

@kamoltat good idea, my code updated, please take a look

**Comment by NitzanMordhai** [comment]
I ran the failing test 50 times with the new code, no new occurrence happened
http://pulpito.front.sepia.ceph.com/nmordech-2023-05-21_12:48:41-rados:monthrash-main-distro-default-smithi/

**Comment by kamoltat** [comment]
Also, minor thing, please change the PR title and commit message to reflect the change you made, currently it is still the old commit message where we are checking just once with 5 seconds. Thanks!

**Review by kamoltat — APPROVED** [review]
LGTM!

**Comment by ljflores** [comment]
Rados suite review: https://tracker.ceph.com/projects/rados/wiki/MAIN#httpstrellocomc1LQJnuRh1759-wip-yuri8-testing-2023-05-23-0802

**Pull request merged**
