### PR TITLE
luminous: core: lazy omap stat collection

### PR DESCRIPTION
**Pull request by badone**
https://tracker.ceph.com/issues/38551

---

Backport of https://github.com/ceph/ceph/pull/26614 and https://github.com/ceph/ceph/pull/28070

- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by badone** [comment]
Working on a fix for the build failure

**Comment by badone** [comment]
There's a linker error on ceph_test_lazy_omap_stats. looking into that.

**Comment by badone** [comment]
The test is broken due to no '--block' option for deep-scrub. Working on a fix.

**Comment by badone** [comment]
Anyone want to take another look or happy to go as is?

**Comment by badone** [comment]
http://pulpito.ceph.com/bhubbard-2019-08-08_07:06:35-rados-wip-badone-testing-distro-basic-mira/

**Comment by badone** [comment]
Minor update to address some memory accounting issues.

**Comment by badone** [comment]
http://pulpito.ceph.com/bhubbard-2019-08-12_10:00:39-rados-wip-badone-testing-distro-basic-smithi/

**Comment by neha-ojha** [comment]
tests running here: http://pulpito.ceph.com/nojha-2019-09-06_01:27:53-rados-wip-luminous-lazy-omap-stats-backport-tracker-38551-distro-basic-smithi/

**Comment by neha-ojha** [comment]
> tests running here: http://pulpito.ceph.com/nojha-2019-09-06_01:27:53-rados-wip-luminous-lazy-omap-stats-backport-tracker-38551-distro-basic-smithi/

unrelated failures

**Pull request merged**
