### PR TITLE
cls/queue: fix empty markers when listing entries

### PR DESCRIPTION
**Pull request by yuvalif**
This PR only add a unit test to identify the issue, which is currently failing.

- [x] fix the actual bug

Signed-off-by: Yuval Lifshitz <ylifshit@redhat.com>

### CODE REVIEW

**Comment by tchaikov** [comment]
- http://pulpito.ceph.com/kchai-2020-04-30_13:24:45-rados-wip-kefu-testing-2020-04-30-1835-distro-basic-smithi/
- http://pulpito.ceph.com/kchai-2020-05-01_04:25:09-rados-wip-kefu-testing-2020-04-30-1912-distro-basic-smithi/

**Comment by pritha-srivastava** [comment]
@yuvalif : Hi Yuval, has this PR been marked for backport to Octopus? The fix for empty markers need to be backported.

**Comment by yuvalif** [comment]
> @yuvalif : Hi Yuval, has this PR been marked for backport to Octopus? The fix for empty markers need to be backported.

@pritha-srivastava  will open a tracker and mark for backport

**Comment by yuvalif** [comment]
> > @yuvalif : Hi Yuval, has this PR been marked for backport to Octopus? The fix for empty markers need to be backported.
> 
> @pritha-srivastava will open a tracker and mark for backport

https://tracker.ceph.com/issues/45533

**Comment by pritha-srivastava** [comment]
> > > @yuvalif : Hi Yuval, has this PR been marked for backport to Octopus? The fix for empty markers need to be backported.
> > 
> > 
> > @pritha-srivastava will open a tracker and mark for backport
> 
> https://tracker.ceph.com/issues/45533

Thank you.

**Pull request merged**
