### PR TITLE
tests: use python3 compatible print

### PR DESCRIPTION
**Pull request by kshtsk**
master tracker: https://tracker.ceph.com/issues/42210

### CODE REVIEW

**Comment by kshtsk** [comment]
jenkins test make check arm64

**Comment by smithfarm** [comment]
@kshtsk Definitely the ceph-volume commit should be split into a separate PR.

**Comment by smithfarm** [comment]
@kshtsk One of the commits - cfafbc2 - is missing a component prefix. Could you change the title of that commit to:

```
tasks/resolve_stuck_peering: use python3 compatible print
```

**Comment by kshtsk** [comment]
> @kshtsk Definitely the ceph-volume commit should be split into a separate PR.
created a PR for that one #30790

**Comment by gregsfortytwo** [comment]
Hmm I admit I've not been thinking too hard about the testing on these py3 patches. I'd probably just try and get Patrick and then (Neha or Kefu) to run it through one of their integrations. *shrug*

**Comment by smithfarm** [comment]
Created an "umbrella" tracker https://tracker.ceph.com/issues/42266 and changed https://tracker.ceph.com/issues/42210 into a subtask of that.

**Comment by smithfarm** [comment]
@kshtsk Please add to the commit message:

```
Fixes: https://tracker.ceph.com/issues/42210
```

**Comment by kshtsk** [comment]
> @kshtsk Please squash all commits into one, and add to the commit message:
> 
> ```
> Fixes: https://tracker.ceph.com/issues/42210
> ```

DONE

**Comment by smithfarm** [comment]
@batrick Care to test this one, as well? Or merge it as-is?

**Comment by tchaikov** [comment]
- http://pulpito.ceph.com/kchai-2019-10-18_15:55:07-rados-wip-kefu-testing-2019-10-18-1835-distro-basic-mira/
- http://pulpito.ceph.com/kchai-2019-10-20_02:57:03-rados-wip-kefu-testing-2019-10-18-1835-distro-basic-mira/
- http://pulpito.ceph.com/kchai-2019-10-20_12:50:42-rados-wip-kefu-testing-2019-10-18-1835-distro-basic-mira/

librbd failures tracked by https://tracker.ceph.com/issues/42384

**Pull request merged**
