### PR TITLE
pacific: mgr/pybind/snap_schedule: do not fail when no fs snapshots are available

### PR DESCRIPTION
**Pull request by leseb**
https://tracker.ceph.com/issues/50538

### CODE REVIEW

**Review by batrick — CHANGES_REQUESTED** [review]
````
snap_schedule/__init__.py:9: note: In module imported here:
snap_schedule/module.py: note: In member "snap_schedule_list" of class "Module":
snap_schedule/module.py:96: error: Name 'Dict' is not defined
snap_schedule/module.py:96: note: Did you forget to import it from "typing"? (Suggestion: "from typing import Dict")
````

**Comment by leseb** [comment]
It's strange that the initial push on master branch didn't catch this. I'll fix next week.

**Comment by batrick** [comment]
jenkins test make check

**Comment by vshankar** [comment]
@leseb ping?

**Comment by leseb** [comment]
jenkins test make check

**Comment by batrick** [comment]
````
snap_schedule/__init__.py:9: note: In module imported here:
snap_schedule/module.py: note: In member "snap_schedule_list" of class "Module":
snap_schedule/module.py:96: error: Need type annotation for 'Dict' (hint: "Dict: Dict[<type>, <type>] = ...")
snap_schedule/module.py:97: error: Variable "Dict" is not valid as a type
snap_schedule/module.py:97: note: See https://mypy.readthedocs.io/en/latest/common_issues.html#variables-vs-type-aliases
Found 2 errors in 1 file (checked 15 source files)
````

@leseb please correct these.

**Comment by leseb** [comment]
> ```
> snap_schedule/__init__.py:9: note: In module imported here:
> snap_schedule/module.py: note: In member "snap_schedule_list" of class "Module":
> snap_schedule/module.py:96: error: Need type annotation for 'Dict' (hint: "Dict: Dict[<type>, <type>] = ...")
> snap_schedule/module.py:97: error: Variable "Dict" is not valid as a type
> snap_schedule/module.py:97: note: See https://mypy.readthedocs.io/en/latest/common_issues.html#variables-vs-type-aliases
> Found 2 errors in 1 file (checked 15 source files)
> ```
> 
> @leseb please correct these.

Fixed.

**Review by batrick — APPROVED** [review]

**Review by vshankar — APPROVED** [review]

**Pull request merged**
