### PR TITLE
hammer: Protect against excessively large object map sizes

### PR DESCRIPTION
**Pull request by Vicente-Cheng**
http://tracker.ceph.com/issues/15129

### CODE REVIEW

**Comment by dachary** [comment]
@dillaman it passed a run of the rbd suite ( http://tracker.ceph.com/issues/14692#note-49 ), do you think it is ready to be merged ?

**Comment by dachary** [comment]
<code>commit=97f474fb6b26ae7b7e2fdd21de4f4bd98cdd56ab ; picked_from=$(git show --no-patch --pretty=%b $commit  | perl -ne 'print if(s/.*cherry pick.* from commit (\w+).*/$1/)') ; diff -u --ignore-matching-lines '^[^+-]'   <(git show $picked_from) <(git show $commit)</code>

returns nothing, proof that the conflict resolution was in the hunk context

**Comment by dachary** [comment]
shoot, closed by accident

**Comment by dillaman** [comment]
lgtm :+1:

**Pull request merged**
