### PR TITLE
mon/Monitor: fix statfs handling before luminous switchover happens

### PR DESCRIPTION
**Pull request by liewegas**
After the mons are luminous but before we switch over to using the
MgrStatMonitor's new info, the version on mgrstat will generally be <<
than that of pgmon, and the client will send that version with the
request.  This means that the statfs message will perpetually appear to be
in the future and fail the is_readable() check.

Fix this with any ugly hack that resets the version to 1 if we haven't
completed the luminous upgrade yet.

Signed-off-by: Sage Weil <sage@redhat.com>

### CODE REVIEW

**Comment by gregsfortytwo** [comment]
Is there a ticket where I can read more about this? I think I get what's happening, but as you say it's an ugly hack...
Also you say you're setting it to version 1 in the commit/comment but appear to set it to version 0?

**Comment by yuriw** [comment]
should fix http://tracker.ceph.com/issues/21930

**Comment by liewegas** [comment]
the ticket doesn't have much info.  you can log into a test machine in this state, though

see smithi185, smithi110 for the mons, and smithi145 for the hung client

<pre>
2017-11-29 21:09:29.694437 7f54aabd8700  1 -- 172.21.15.30:0/283705467 --> 172.21.15.185:6789/0 -- statfs(23901 v26) v1 -- ?+0 0x55b54d886c00 con 0x55b54d528300
...
</pre>
and the mons stuck with
<pre>
2017-11-29 22:02:17.518638 7ff719fee700 10 mon.a@1(peon).paxosservice(mgrstat 25..25) dispatch 0x56439dbc0900 statfs(23900 pool -1 v26) v1 from client.14098 172.21.15.30:0/283705467 con 0x56439d490800
2017-11-29 22:02:17.518646 7ff719fee700 10 mon.a@1(peon).paxosservice(mgrstat 25..25)  waiting for paxos -> readable (v26)
2017-11-29 22:02:17.518651 7ff719fee700 10 mon.a@1(peon).paxosservice(mgrstat 25..25) dispatch 0x56439ce5fa80 statfs(23901 pool -1 v26) v1 from client.14098 172.21.15.30:0/283705467 con 0x56439d490800
2017-11-29 22:02:17.518656 7ff719fee700 10 mon.a@1(peon).paxosservice(mgrstat 25..25)  waiting for paxos -> readable (v26)
</pre>

**Comment by theanalyst** [comment]
Do we still want this in 12.2.2?

**Pull request merged**
