### PR TITLE
pybind: fix use of WriteOpCtx and ReadOpCtx

### PR DESCRIPTION
**Pull request by ajarr**
Both classes WriteOpCtx and ReadOpCtx don't take in arguments during instantiation.

Fixes: http://tracker.ceph.com/issues/38946
Signed-off-by: Ramana Raja <rraja@redhat.com>

- [x] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by ajarr** [comment]
@batrick, can we merge this?

**Comment by batrick** [comment]
What caused this? Commit/tracker should reference PR that broke it. Will that PR which caused this be backported?

**Comment by rishabh-d-dave** [comment]
@batrick 
The PR that broke it is #22455, which was trying to fix the [issue 24173](http://tracker.ceph.com/issues/24173). The PR is already backported to luminous and mimic.

I think the test written during PR #22455 also needs an update. It's a negative test (Patrick's comment [here](https://github.com/ceph/ceph/pull/22455#discussion_r195190266) explains the test succinctly). The reason for which the test couldn't catch this bug should be that the exception raised at the line [`with rados.WriteOpCtx(ioctx) as wop`](https://github.com/ceph/ceph/blob/master/src/pybind/ceph_volume_client.py#L1480) was same as the exception we're expecting by providing it a wrong  version (i.e. `CommandFailedError`). Perhaps, we should have a positive test too as I had written back then originally?

Also I feel `CommandFailedError` is a bit too generic; I think we should provide a context for the exceptions we raise during the testing. I've been feeling this since working on PR #26477; I've added messages to the exceptions there.

**Comment by batrick** [comment]
Okay, then the test should also be updated too. Thanks for the explanation @rishabh-d-dave . Please make that change @ajarr

**Comment by ajarr** [comment]
@batrick , @rishabh-d-dave ,  this "bug" was hit while linting the code, not actually while running it.
I executed the put_object_versioned() method again, and wasn't able to hit any issues.

The weird thing is class WriteOpCtx  seems to accept variable number of arguments during instantiation,
e.g., below works
```
import rados
wop = rados.WriteOpCtx("junk", "dfjkkjjfd")
wop = rados.WriteOpCtx("junk", "dfjkkjjfd", "skdjfksdjkfjaksdf", "dkfjdkjfkakjd", "sdkfjdkfjka")
```

We do have positive tests, see test_put_object() in test_volume_client.py that  calls  put_object_versioned() implicitly. I don't think this "bug" is high priority, but it's a nice to have fix.

**Comment by rishabh-d-dave** [comment]
@ajarr @batrick 

@ajarr said
> We do have positive tests, see test_put_object() in test_volume_client.py that calls put_object_versioned() implicitly. I don't think this "bug" is high priority, but is nice to fix.

`put_object` doesn't passes `version` to `put_object_versioned()`. So, `put_object_versioned()` uses the default value for `version` (i.e. `None`) and therefore it skips the version check before writing the object[[1]](https://github.com/ceph/ceph/blob/master/src/pybind/ceph_volume_client.py#L1481). So it doesn't matter if we have a positive test for`put_object()`. IMHO, `put_object_versioned()` needs a positive test of its own.

Perhaps, the name `version` should change to `current_version` or `current_obj_version`? I find only `version` ambiguous.

**Comment by ajarr** [comment]
> 
> `put_object` doesn't passes `version` to `put_object_versioned()`. So, `put_object_versioned()` uses the default value for `version` (i.e. `None`) and therefore it skips the version check before writing the object[[1]](https://github.com/ceph/ceph/blob/master/src/pybind/ceph_volume_client.py#L1481). So it doesn't matter if we have a positive test for`put_object()`. IMHO, `put_object_versioned()` needs a positive test of its own.
> 
> Perhaps, the name `version` should change to `current_version` or `current_obj_version`? I find only `version` ambiguous.

@rishabh-d-dave 
I'm not making a change to the line of code that you refer to in this PR. There is a test that already executes the line of code that I've changed. If you want to enhance test coverage that should be a separate PR.

I don't see why this PR should be blocked.

**Pull request merged**
