### PR TITLE
luminous: os/bluestore: Fix problem with bluefs's freespace.

### PR DESCRIPTION
**Pull request by aclamk**
Fix problem with bluefs's freespace not being balanced when kv_sync_thread is sleeping.
              This is fix for customer issue #1600138

Signed-off-by: Adam Kupczyk <akupczyk@redhat.com>

### CODE REVIEW

**Comment by aclamk** [comment]
@ifed01 This is dual solution to #26657 . Tested, works.

**Comment by ifed01** [comment]
Wondering though if the proper scenario would be to create a PR for mimic and then backport to Luminous

**Comment by aclamk** [comment]
This fixes https://tracker.ceph.com/issues/38574

**Comment by aclamk** [comment]
This PR will be remade by cherry-picking from mimic #26735 .

**Pull request closed without merging**
