### PR TITLE
cmake: enable LZ4 by default

### PR DESCRIPTION
**Pull request by cbodley**
reopening https://github.com/ceph/ceph/pull/17038 so we can get it in for mimic

### CODE REVIEW

**Comment by cbodley** [comment]
jenkins test make check

**Comment by tchaikov** [comment]
retest this please.

**Comment by cbodley** [comment]
looks like make check and [shaman builds](https://shaman.ceph.com/builds/ceph/wip-cmake-lz4/) are failing?
> mk-build-deps: Unable to install ceph-build-deps at /usr/bin/mk-build-deps line 402.

i don't see any error messages related with lz4, so i can't tell what's going wrong

**Comment by cbodley** [comment]
> liblz4-dev (>= 0.0~r131)

thanks @tchaikov, looks like that did the trick

**Comment by cbodley** [comment]
jenkins test make check arm64

**Comment by tchaikov** [comment]
@cbodley sorry, PendingReleaseNotes conflicts again.

**Comment by cbodley** [comment]
rebased

**Comment by tchaikov** [comment]
http://pulpito.ceph.com/kchai-2018-04-12_15:56:07-rados-wip-kefu-testing-2018-04-12-2211-distro-basic-mira/

failed tests are 

- tracked by http://tracker.ceph.com/issues/23699
- caused by #19117
- fixed by #21406

**Comment by cbodley** [comment]
thanks @tchaikov!

**Pull request merged**
