### PR TITLE
luminous: client: explicitly show blacklisted state via asok status command

### PR DESCRIPTION
**Pull request by jonsger**
http://tracker.ceph.com/issues/36456

### CODE REVIEW

**Comment by jonsger** [comment]
jenkins make check

**Comment by jonsger** [comment]
jenkins test make check

**Comment by yuriw** [comment]
[wip-yuri5-testing-2018-12-12-1653-luminous](https://trello.com/c/oXzdX0yM/487-wip-yuri5-testing-2018-12-12-1653-luminous)

**Comment by yuriw** [comment]
[wip-yuri2-testing-2018-12-19-1656-luminous](https://trello.com/c/55NDqzim/493-wip-yuri2-testing-2018-12-19-1656-luminous)

**Pull request merged**
