### PR TITLE
seastore: seperate Journal interface from SegmentedJournal implementation

### PR DESCRIPTION
**Pull request by athanatos**
A subsequent PR will introduce a CircularBoundedJournal implementation
for fast nvme devices.

SegmentCleaner no longer needs a reference to Journal, so dispense with
the set_segment_provider machinery and simply pass it in the
constructor.

Move responsibility for finding the journal segments into the journal
itself.  This does mean that we check the segment headers on the journal
device twice, but that should be a neglible amount of overhead on mount.

SegmentCleaner::init_segments no longer needs to return Journal
segments, so merge with mount().

Signed-off-by: Myoungwon Oh <myoungwon.oh@samsung.com>
Signed-off-by: Samuel Just <sjust@redhat.com>

### CODE REVIEW

**Comment by athanatos** [comment]
@cyx1231st Would you be able to take a look at this?

**Comment by tchaikov** [comment]
hmm, might want to s/seatore/seastore/ in the title of the commit message.

**Comment by athanatos** [comment]
Fixing the unit test failure, missed something in test_seastore_journal in the cleanup.

**Review by cyx1231st — APPROVED** [review]
Reasonable to me.

**Comment by athanatos** [comment]
@myoungwon Does this work for you?

**Comment by myoungwon** [comment]
Looks good to me.

**Pull request merged**
