### PR TITLE
doc/rados/configuration: add links to MON DNS

### PR DESCRIPTION
**Pull request by bluikko**
Add two links to MON DNS lookup and an anchor in the destination document.

Signed-off-by: Ville Ojamo <14869000+bluikko@users.noreply.github.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [x] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [x] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by bluikko** [comment]
The MON DNS lookup document example has messenger v1 port 6789, perhaps it should be updated to v2 port?

**Comment by bluikko** [comment]
I wonder if I should update this (and the other PRs languishing), any comments from reviewers?

**Comment by zdover23** [comment]
> I wonder if I should update this (and the other PRs languishing), any comments from reviewers?

@bluikko: Feel free to resolve the merge conflict here. Or, if you prefer, I can open a new PR that will cleanly ingest this change (and you will not have to undergo the potentially tedious ordeal of resolving this merge conflict).

**Comment by bluikko** [comment]
> and you will not have to undergo the potentially tedious ordeal of resolving this merge conflict

Rebasing is something that will unfortunately happen often so it should not be too difficult. Biggest issue seems to be that my (work) VSCode configuration drops automatically trailing whitespaces.  
Quite a few were eliminated and I guess the options are to either update the PR to list that change; or change that configuration & force push again.

**Comment by bluikko** [comment]
Looking at the existing named references: the style seems to prefer "See [ref]" instead of making a link out of a part of the text, can change these also to:
```
``mon_host`` option. This issue can be avoided by using DNS SRV records.
For more details, see :ref:`mon-dns-lookup`.
```
```
used to identify monitors, a local Ceph configuration file can be avoided
entirely. For more details, see :ref:`mon-dns-lookup`.
```

Or open to other suggestions.

This kind of issue, if there indeed is a preference, might be a great addition to https://docs.ceph.com/en/latest/start/documenting-ceph/#documentation-style-guide -- which, IMHO, while very helpful at its current form, is currently more of an RST tutorial than actual style guide. Specific location could be https://docs.ceph.com/en/latest/start/documenting-ceph/#linking-customs for example.

I get that it would probably have been faster to just close this & let the people who know what they are doing make a new PR. Hoping to learn something so as to get it right the next time.

**Review by zdover23 — APPROVED** [review]

**Comment by zdover23** [comment]
> Looking at the existing named references: the style seems to prefer "See [ref]" instead of making a link out of a part of the text, can change these also to:
> 
> ```
> ``mon_host`` option. This issue can be avoided by using DNS SRV records.
> For more details, see :ref:`mon-dns-lookup`.
> ```
> 
> ```
> used to identify monitors, a local Ceph configuration file can be avoided
> entirely. For more details, see :ref:`mon-dns-lookup`.
> ```
> 
> Or open to other suggestions.
> 
> This kind of issue, if there indeed is a preference, might be a great addition to https://docs.ceph.com/en/latest/start/documenting-ceph/#documentation-style-guide -- which, IMHO, while very helpful at its current form, is currently more of an RST tutorial than actual style guide. Specific location could be https://docs.ceph.com/en/latest/start/documenting-ceph/#linking-customs for example.

The convention of using "see :ref:`anchor`" is an artifact of my habits in the year 2020. When I took the job of Word Guy for the Ceph Foundation, I just started using this formulation so that I didn't have to look two places in the same document to deal with hyperlinks.

Personally, I will accept either convention. It is much more important to me that the documentation is technically accurate and grammatically correct than it is that all of the RST links have the same format.

I plan to write a style guide in 2024 and 2025. I have a stack of 3x5 index cards that contain what will eventually be transmuted into a style guide, but I am only one person. I am currently engaged in a careful, tedious cleaning of the vstart procedures. After that is done (and I expect that it will take until September 1 2023 at the absolute soonest), I have to write the Beginner's Guide to Ceph, which I expect to take sixty to one-hundred and twenty days. When that is done, I will begin the process of improving Ceph's contextual help. I'm not sure how long it will take to improve the contextual help, but I expect that the year will end in a 4 when the task is complete. When that is done, I will begin writing the style guide. Now that we've had this exchange, I think you can expect to be consulted during its composition.

I know that this might sound as though I'm saying that I won't add the :ref: convention to Documenting Ceph, but I don't mean to sound like that. I'll raise a pull request sometime in the next week that adds this convention to Documenting Ceph.

> 
> I get that it would probably have been faster to just close this & let the people who know what they are doing make a new PR. Hoping to learn something so as to get it right the next time.

For what my opinion is worth, I think the way that you handled this is preferable to just closing the PR and letting other people handle it. If you look at my own commit history in 2019 and 2020, you'll see at least a dozen terrible blunders that tell the history of the process of my stubborn, embarrassing, and public chipping away at my ignorance of the conventions governing the documentation of the Ceph project.

**Comment by zdover23** [comment]
https://github.com/ceph/ceph/pull/52612 - Reef backport
https://github.com/ceph/ceph/pull/52613 - Quincy backport

**Comment by bluikko** [comment]
@zdover23 Thank you for the encouraging words. I'd never have any expectations for the outcomes from my suggestions.

**Comment by zdover23** [comment]
> @zdover23 Thank you for the encouraging words. I'd never have any expectations for the outcomes from my suggestions.

@bluikko: Read through https://docs.ceph.com/en/latest/start/documenting-ceph/#internal-links and tell me what you think we should add to that section. Is it just the convention of writing "See X for more information"?

**Comment by bluikko** [comment]
> Is it just the convention of writing "See X for more information"?

Yes, I'd propose to just list what's the policy regarding linking if there is a policy or a preference. If there is no preference one way or the other then perhaps it could list that the two options (part of the text vs. "see x") are equally fine and can be used as appropriate.

For example
> By convention, using a part of a sentence for a hyperlink is discouraged and a form of construct "See [link] for more information" ("For more information, see [link]" etc.) is preferred.

or
> A hyperlink may be a part of a sentence or a form of "See [link] for more information." construct, as appropriate.

I would suggest to use the existing section "Linking customs" in https://docs.ceph.com/en/latest/start/documenting-ceph/#linking-customs for this because then it could include also the preference for external links.  
If the preference for internal/external links is the same then both could be listed here at the same time. If the preferences are different then it might make more sense to list each under the relevant section.

**Comment by zdover23** [comment]
https://github.com/ceph/ceph/pull/52702 - A commit that adds the above-discussed convention to doc/start/documenting-ceph.rst.

**Pull request merged**
