### PR TITLE
luminous: ceph-volume prints log messages to stdout

### PR DESCRIPTION
**Pull request by jan--f**
https://tracker.ceph.com/issues/41202

### CODE REVIEW

**Comment by jan--f** [comment]
jenkins test ceph-volume tox

**Comment by alfredodeza** [comment]
all these tox tests are failing because https://github.com/ceph/ceph/pull/26826 hasn't been backported which includes a commit that skips the functional tests... we might want to get that to stop seeing all these tox failures on backport PRs

**Comment by jan--f** [comment]
Seems like this was backported in #26857 to luminous at least.

**Comment by jan--f** [comment]
Seems like flake8 is an issue, will look into it. THough I'd call it unrelated for these backports.

**Pull request merged**
