### PR TITLE
mimic: mgr: enable inter-module calls

### PR DESCRIPTION
**Pull request by tchaikov**
Fixes: https://tracker.ceph.com/issues/39132

### CODE REVIEW

**Comment by smithfarm** [comment]
@tchaikov The line `Fixes: https://tracker.ceph.com/issues/39132` is not present in the original commit message. When cherry-picking, to avoid polluting the git history we try to avoid changing the text above the line `(cherry picked from commit ...)`.

So this added "Fixes" line, if it's deemed necessary, could be placed under that line, instead of above?

**Comment by sebastian-philipp** [comment]
were there any noteworthy fixes to the remote() call after the initial implementation form John?

**Comment by tchaikov** [comment]
@smithfarm i removed the "Fixes" line. 

@sebastian-philipp thanks for the reminder. i checked. none.

**Comment by tchaikov** [comment]
retest this please.

**Comment by yuriw** [comment]
[wip-yuri5-testing-2019-04-30-2026-mimic](https://trello.com/c/9KYPzFev/602-wip-yuri5-testing-2019-04-30-2026-mimic)

**Comment by neha-ojha** [comment]
Though the original failure was not seen, I think we need a follow up fix for

```
2019-05-02T22:25:20.281 INFO:tasks.ceph.mgr.y.smithi174.stderr:2019-05-02 22:25:20.275 7fede3c3b700 -1 no module 'crash'
2019-05-02T22:25:20.282 INFO:teuthology.orchestra.run.smithi167.stderr:2019-05-02 22:25:20.277 7ff1697fa700  1 -- 172.21.15.167:0/2079532987 <== mgr.5933 172.21.15.174:6800/13624 1 ==== command_reply(tid 0: -22 Traceback (most recent call last):
2019-05-02T22:25:20.282 INFO:teuthology.orchestra.run.smithi167.stderr:  File "/usr/lib/ceph/mgr/telemetry/module.py", line 328, in handle_command
2019-05-02T22:25:20.282 INFO:teuthology.orchestra.run.smithi167.stderr:    self.self_test()
2019-05-02T22:25:20.282 INFO:teuthology.orchestra.run.smithi167.stderr:  File "/usr/lib/ceph/mgr/telemetry/module.py", line 384, in self_test
2019-05-02T22:25:20.282 INFO:teuthology.orchestra.run.smithi167.stderr:    self.compile_report()
2019-05-02T22:25:20.283 INFO:teuthology.orchestra.run.smithi167.stderr:  File "/usr/lib/ceph/mgr/telemetry/module.py", line 291, in compile_report
2019-05-02T22:25:20.283 INFO:teuthology.orchestra.run.smithi167.stderr:    report['crashes'] = self.gather_crashinfo()
2019-05-02T22:25:20.283 INFO:teuthology.orchestra.run.smithi167.stderr:  File "/usr/lib/ceph/mgr/telemetry/module.py", line 214, in gather_crashinfo
2019-05-02T22:25:20.283 INFO:teuthology.orchestra.run.smithi167.stderr:    errno, crashids, err = self.remote('crash', 'do_ls', '', '')
2019-05-02T22:25:20.283 INFO:teuthology.orchestra.run.smithi167.stderr:  File "/usr/lib/ceph/mgr/mgr_module.py", line 845, in remote
2019-05-02T22:25:20.283 INFO:teuthology.orchestra.run.smithi167.stderr:    args, kwargs)
2019-05-02T22:25:20.284 INFO:teuthology.orchestra.run.smithi167.stderr:ImportError: Module not found
2019-05-02T22:25:20.284 INFO:teuthology.orchestra.run.smithi167.stderr:) v1 ==== 614+0+0 (2804853677 0 0) 0x7ff16c115110 con 0x7ff14c0073f0
2019-05-02T22:25:20.284 INFO:teuthology.orchestra.run.smithi167.stderr:2019-05-02 22:25:20.277 7ff1697fa700 20 mgrc handle_command_reply command_reply(tid 0: -22 Traceback (most recent call last):
2019-05-02T22:25:20.284 INFO:teuthology.orchestra.run.smithi167.stderr:  File "/usr/lib/ceph/mgr/telemetry/module.py", line 328, in handle_command
2019-05-02T22:25:20.284 INFO:teuthology.orchestra.run.smithi167.stderr:    self.self_test()
2019-05-02T22:25:20.284 INFO:teuthology.orchestra.run.smithi167.stderr:  File "/usr/lib/ceph/mgr/telemetry/module.py", line 384, in self_test
2019-05-02T22:25:20.285 INFO:teuthology.orchestra.run.smithi167.stderr:    self.compile_report()
2019-05-02T22:25:20.285 INFO:teuthology.orchestra.run.smithi167.stderr:  File "/usr/lib/ceph/mgr/telemetry/module.py", line 291, in compile_report
2019-05-02T22:25:20.285 INFO:teuthology.orchestra.run.smithi167.stderr:    report['crashes'] = self.gather_crashinfo()
2019-05-02T22:25:20.285 INFO:teuthology.orchestra.run.smithi167.stderr:  File "/usr/lib/ceph/mgr/telemetry/module.py", line 214, in gather_crashinfo
2019-05-02T22:25:20.286 INFO:teuthology.orchestra.run.smithi167.stderr:    errno, crashids, err = self.remote('crash', 'do_ls', '', '')
2019-05-02T22:25:20.286 INFO:teuthology.orchestra.run.smithi167.stderr:  File "/usr/lib/ceph/mgr/mgr_module.py", line 845, in remote
2019-05-02T22:25:20.286 INFO:teuthology.orchestra.run.smithi167.stderr:    args, kwargs)
2019-05-02T22:25:20.286 INFO:teuthology.orchestra.run.smithi167.stderr:ImportError: Module not found
2019-05-02T22:25:20.286 INFO:teuthology.orchestra.run.smithi167.stderr:) v1
2019-05-02T22:25:20.287 INFO:teuthology.orchestra.run.smithi167.stderr:Error EINVAL: Traceback (most recent call last):
2019-05-02T22:25:20.287 INFO:teuthology.orchestra.run.smithi167.stderr:  File "/usr/lib/ceph/mgr/telemetry/module.py", line 328, in handle_command
2019-05-02T22:25:20.287 INFO:teuthology.orchestra.run.smithi167.stderr:    self.self_test()
2019-05-02T22:25:20.287 INFO:teuthology.orchestra.run.smithi167.stderr:  File "/usr/lib/ceph/mgr/telemetry/module.py", line 384, in self_test
2019-05-02T22:25:20.288 INFO:teuthology.orchestra.run.smithi167.stderr:    self.compile_report()
2019-05-02T22:25:20.288 INFO:teuthology.orchestra.run.smithi167.stderr:  File "/usr/lib/ceph/mgr/telemetry/module.py", line 291, in compile_report
2019-05-02T22:25:20.288 INFO:teuthology.orchestra.run.smithi167.stderr:    report['crashes'] = self.gather_crashinfo()
2019-05-02T22:25:20.288 INFO:teuthology.orchestra.run.smithi167.stderr:  File "/usr/lib/ceph/mgr/telemetry/module.py", line 214, in gather_crashinfo
2019-05-02T22:25:20.288 INFO:teuthology.orchestra.run.smithi167.stderr:    errno, crashids, err = self.remote('crash', 'do_ls', '', '')
2019-05-02T22:25:20.289 INFO:teuthology.orchestra.run.smithi167.stderr:  File "/usr/lib/ceph/mgr/mgr_module.py", line 845, in remote
2019-05-02T22:25:20.289 INFO:teuthology.orchestra.run.smithi167.stderr:    args, kwargs)
2019-05-02T22:25:20.289 INFO:teuthology.orchestra.run.smithi167.stderr:ImportError: Module not found
```

http://pulpito.ceph.com/yuriw-2019-05-02_16:49:37-rados-wip-yuri5-testing-2019-04-30-2026-mimic-distro-basic-smithi/3919085/

**Pull request merged**
