### PR TITLE
rgwlc: fix lc head marker point to non-exist lc entry

### PR DESCRIPTION
**Pull request by 5cs**
After a single-bucket run and its lc entry is removed since the
bucket is deleted, we will have lc shard object's head marker
point to a non-exist lc entry. Finally, buckets that are hashed
to this lc shard can not have any lifecycle progress. Fix it
by skipping the non-exist marker.

Fixes: https://tracker.ceph.com/issues/57162

Signed-off-by: Tongliang Deng <dengtongliang@gmail.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [x] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Review by mattbenjamin — APPROVED** [review]
lgtm

**Comment by mattbenjamin** [comment]
A tracker issue would be appreciated.

**Comment by 5cs** [comment]
> A tracker issue would be appreciated.

will create one when my newly created tracker account is approved

**Comment by 5cs** [comment]
Tracker issue created: https://tracker.ceph.com/issues/57162, PTAL @mattbenjamin

**Comment by ivancich** [comment]
jenkins test api

**Comment by ivancich** [comment]
@5cs @mattbenjamin Does this need backports? It reads like a bug but I don't know when it was introduced.

**Pull request merged**
