### PR TITLE
kraken: rgw: rgw_file: fix marker computation

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/18810
http://tracker.ceph.com/issues/18902
http://tracker.ceph.com/issues/19144
http://tracker.ceph.com/issues/19149
http://tracker.ceph.com/issues/19154
http://tracker.ceph.com/issues/19162
http://tracker.ceph.com/issues/19166
http://tracker.ceph.com/issues/19168
http://tracker.ceph.com/issues/19170
http://tracker.ceph.com/issues/19229
http://tracker.ceph.com/issues/19470
http://tracker.ceph.com/issues/19471
http://tracker.ceph.com/issues/19526
http://tracker.ceph.com/issues/19661
http://tracker.ceph.com/issues/19663
http://tracker.ceph.com/issues/19723
http://tracker.ceph.com/issues/20158
http://tracker.ceph.com/issues/20195

### CODE REVIEW

**Comment by smithfarm** [comment]
@mattbenjamin This passed an RGW suite at http://tracker.ceph.com/issues/19009#note-8

Please review/approve if you agree it can be merged.

**Comment by smithfarm** [comment]
@mattbenjamin @yehudasa This PR passed another RGW suite at http://tracker.ceph.com/issues/19009#note-18

Please review/approve if you agree it can be merged.

**Comment by smithfarm** [comment]
Rebased.

**Comment by smithfarm** [comment]
Rebased. This can be merged, provided it passes one last rgw suite and "make check".

**Comment by smithfarm** [comment]
Jenkins re-test this please

**Comment by smithfarm** [comment]
I've created a monster!

**Comment by smithfarm** [comment]
@mattbenjamin This should be all the rgw_file fixes that were applied to jewel since kraken was split off from master. With the sole exception of 50955a5 they all applied cleanly.

**Comment by smithfarm** [comment]
This is included in the integration branch now building at https://shaman.ceph.com/builds/ceph/wip-kraken-backports/241c44b083d6e9fc82ff2d1d10379963d65db866/default/52932/

**Comment by smithfarm** [comment]
@yehudasa @mattbenjamin This PR passed an rgw suite at http://tracker.ceph.com/issues/19009#note-60 and @mattbenjamin already approved it before I added a bunch more commits. If there are no objections, I will merge it.

**Comment by smithfarm** [comment]
@mattbenjamin This passed another rgw suite at tracker.ceph.com/issues/19009#note-65 with two valgrind-related failures that I'm currently re-running. Do you think it can be merged? (I know you already approved it, but I expanded it significantly since then.)

**Comment by yehudasa** [comment]
@smithfarm leaving it for @mattbenjamin

**Comment by mattbenjamin** [comment]
@smithfarm go for it

**Pull request merged**
