### PR TITLE
qa/workunits/rbd: remove "trash purge --threshold" test

### PR DESCRIPTION
**Pull request by trociny**
before running "rbd trash purge --threshold 0" test.

Fixes: http://tracker.ceph.com/issues/22803
Signed-off-by: Mykola Golub <mgolub@suse.com>

### CODE REVIEW

**Comment by dillaman** [comment]
@trociny I guess it needs longer than 30 seconds [1] -- maybe time out after 2 minutes.

[1] http://qa-proxy.ceph.com/teuthology/jdillaman-2018-01-30_16:03:05-rbd-wip-jd-testing-distro-basic-smithi/2129127/teuthology.log

**Comment by trociny** [comment]
@dillaman updated. I am going to run this on teuthology.

**Comment by trociny** [comment]
It still fails [1]. I saw two causes:

1) `rbd default data pool` is set, and in this case my calculation for BYTES_USED is wrong. (BTW, `rbd trash purge --threshold` does not also take into account that data can be in a data pool)

2) small cache pool is used, and in this case the pool bytes_used never reach the expected value (probably because some objects are flushed out).

Also there was a failure on `deep copy` test because it tried to copy to old format destination image, but this is a different story.

[1] http://pulpito.ceph.com/trociny-2018-01-31_20:28:15-rbd-wip-mgolub-testing-distro-basic-smithi/

**Comment by trociny** [comment]
> small cache pool is used, and in this case the pool bytes_used never reach the expected value (probably because some objects are flushed out).

Actually, I am calculating BYTES_USED in rbd, not cache, pool. So, not sure why it reported less bytes than I expected [1].

[1] http://qa-proxy.ceph.com/teuthology/trociny-2018-01-31_20:28:15-rbd-wip-mgolub-testing-distro-basic-smithi/2134105/teuthology.log

**Comment by trociny** [comment]
@dillaman Taking that `--threshold` can't be reliable and will only give "approximate" result for the user (probably satisfactory enough to be useful in usual scenarios), may be just remove `--threshold` test from `test_purge()`?

**Comment by dillaman** [comment]
@trociny 

> may be just remove --threshold test from test_purge()?

Given all the trouble it's causing, that sounds good to me.

**Comment by trociny** [comment]
@dillaman updated

**Pull request merged**
