### PR TITLE
rgw: elasticsearch sync module crashing with simple requests

### PR DESCRIPTION
**Pull request by atilaromero**
Without this, a simple curl http://rgwaddress would crash the rgw, if the rgw is used to sync elasticsearch. Upon debugging, s->object was null.

Signed-off-by: Atila Romero <atilaromero@gmail.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Review by dang — CHANGES_REQUESTED** [review]
The correct way to check an object for empty is:
rgw::sal::Object::empty(s->object.get())

Thanks for catching this one.

**Comment by atilaromero** [comment]
Hi, I implemented the requested change, do I have to mark it changed somehow?

**Comment by atilaromero** [comment]
Is there anything else I can do to move this forward?

**Comment by hejiajiudemao** [comment]
It seems that you have missed "!", the correct way should be:
if (!rgw::sal::Object::empty(s->object.get())) {
    return nullptr;
  }

**Comment by atilaromero** [comment]
if not empty return null?

**Pull request closed without merging**
