### PR TITLE
jewel: core: fix the typo of the threadname to signal_handler

### PR DESCRIPTION
**Pull request by andyli029**
the fix to the issue: http://tracker.ceph.com/issues/21432

### CODE REVIEW

**Comment by andyli029** [comment]
@liewegas @smithfarm  please review and merge

**Comment by tchaikov** [comment]
could you prefix the title of your commit message with the subcomponent your are changing ? see https://github.com/ceph/ceph/blob/master/SubmittingPatches.rst#3-describe-your-changes

also could you add a "`Signed-off-by`" line at the end of your commit message? "git commit -s" will do the trick for you. see https://github.com/ceph/ceph/blob/master/SubmittingPatches.rst#1-sign-your-work

and could you drop the "merge" commit(s)? you can always "rebase" on to the latest master, instead "pull" or "merge" it.

**Comment by smithfarm** [comment]
@andyli029 Thanks for the fix. We cannot take it as is, because there is a commit 8b14914a1d128eee107d7bd08c0ab95ab40e8ded in master that fixed the issue. Please use `git cherry-pick -x 8b14914a1d128eee107d7bd08c0ab95ab40e8ded` instead of your manual fix.

**Comment by andyli029** [comment]
I have changed the fix, the former is right? @tchaikov , 
@smithfarm @tchaikov, Thanks, 
and I got it @smithfarm, next time to fix new bug.

**Comment by smithfarm** [comment]
@andyli029 If you'd like to submit the jewel backport, apply the master fix as a cherry-pick onto the tip of jewel, something like this:

```
git fetch ceph
git checkout -b wip-signal-handler ceph/jewel
git cherry-pick -x 8b14914a1d128eee107d7bd08c0ab95ab40e8ded
```

Open that as a PR against jewel. That's all!

**Comment by andyli029** [comment]
@smithfarm please review and merge
https://github.com/ceph/ceph/pull/17883

**Pull request closed without merging**
