### PR TITLE
osd: Delete the logical judgment that is not useful

### PR DESCRIPTION
**Pull request by ShiqiCooperation**
Signed-off-by: shiqi <1454927420@qq.com>

### CODE REVIEW

**Comment by ShiqiCooperation** [comment]
the client snap.seq is always larger then snapset.seq in osd server.
It is judged in PrimaryLogPG::execute_ctx.
if client snap.seq is smaller then snapset.seq, server will return EOLDSNAPC.

**Comment by ShiqiCooperation** [comment]
so,this logic was judged twice

**Comment by gregsfortytwo** [comment]
I don't think that description sounds accurate -- we (unfortunately) have pool snapshots that the clients are completely oblivious to and which also updates the local snap info. Did you account for that?

**Comment by ShiqiCooperation** [comment]
yes, not only client images, maybe pool snapshots, but pool snapshots still go this function call the process

**Comment by gregsfortytwo** [comment]
ORDERSNAP is not always set. In fact the only place I see us setting it is for caching operations. And in fact we usually don't want to get an error if the snapcontext is wrong — different kinds of clients can easily be out of sync when snapshots are being created and we don't want to enforce false ordering.

So we need this later adjustment for all the other cases. :)

**Pull request closed without merging**
