### PR TITLE
jewel: build/ops: ceph-osd-prestart.sh fails confusingly when data directory does not exist

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/17094

### CODE REVIEW

**Comment by dachary** [comment]
Hey jenkins, test this please (bluefs core dump)

**Comment by dachary** [comment]
Hey jenkins, test this please (unrelated osd-scrub failures)

**Comment by dachary** [comment]
osd-scrub-repair.sh consistently fails

**Comment by dachary** [comment]
jenkins test this please (no log)
and I don't see how this commit can make osd-scrub-repair.sh fail...

**Comment by smithfarm** [comment]
make check bot is now happy, removing DNM

**Pull request merged**
