### PR TITLE
ceph-disk: add --filestore argument, default to --bluestore

### PR DESCRIPTION
**Pull request by dachary**
- [x] rados
- [x] ceph-disk

### CODE REVIEW

**Comment by dachary** [comment]
pushed to ceph-ci to debug the workunit

**Comment by dachary** [comment]
@liewegas for rados do we need something else beside removing the experimental status (that was merged at 036470a2a062077c6a5340a1de8dbdefde2ceb75) ?

**Comment by dachary** [comment]
https://shaman.ceph.com/builds/ceph/wip-bluestore/d7fe74b56cebdbde7c3811fdd70e6d17fad4964a/notcmalloc/45798/ failed with

[ 76%] Building CXX object src/test/msgr/CMakeFiles/ceph_test_async_driver.dir/test_async_driver.cc.o
c++: internal compiler error: Killed (program cc1plus)

repushing

**Comment by dachary** [comment]
100 - test-erasure-eio.sh (Failed)

jenkins test this please

**Comment by dachary** [comment]
https://shaman.ceph.com/builds/ceph/wip-bluestore/ad9bd66ea3873c91ad12e99b75f3c9408167ce31/default/45828/

[ 34%] Building CXX object src/mon/CMakeFiles/mon.dir/AuthMonitor.cc.o
{standard input}: Assembler messages:
{standard input}:586375: Warning: end of file not at end of a line; newline inserted
{standard input}: Error: open CFI at the end of file; missing .cfi_endproc directive
c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <http://bugzilla.redhat.com/bugzilla> for instructions.
make[2]: *** [src/mds/CMakeFiles/mds.dir/MDCache.cc.o] Error 4

looks like shaman on centos 7 is having issues, ignoring it

**Comment by dachary** [comment]
<pre>teuthology-suite -k distro --verbose --suite ceph-disk --ceph wip-bluestore --distro ubuntu --filter-out centos --machine-type vps</pre>

* **running** http://pulpito.ceph.com/loic-2017-06-03_10:47:01-ceph-disk-wip-bluestore-distro-basic-vps/

**Comment by dachary** [comment]
100 - test-erasure-eio.sh (Failed)

jenkins test this please

**Comment by liewegas** [comment]
retest this please

**Comment by liewegas** [comment]
http://pulpito.ceph.com/sage-2017-06-05_14:47:27-rados-wip-sage-testing-distro-basic-smithi/

**Comment by liewegas** [comment]
retest this please

**Comment by dachary** [comment]
I'll check the ceph-disk failures

**Comment by liewegas** [comment]
thanks!

**Comment by dachary** [comment]
retest this please (this is getting old ;-)

**Comment by dachary** [comment]
fixed test error on ceph-disk suite & repushed to ceph-ci

**Comment by dachary** [comment]
all ceph-disk suite pass except for the tests verifying backward compatibility pre-lockbox, because it does not know about --filestore.

**Comment by dachary** [comment]
<pre>teuthology-suite -k distro --verbose --suite ceph-disk --ceph wip-bluestore --machine-type vps</pre>

* **running** http://pulpito.ceph.com/loic-2017-06-05_22:42:35-ceph-disk-wip-bluestore-distro-basic-vps

**Comment by dachary** [comment]
added missing --filestore in ceph-helpers.sh and repushed

**Comment by dachary** [comment]
remove remaining --experimental=bluestore in tests, fix osd-dup.sh which created a filestore instead of a bluestore. repushed.

**Comment by dachary** [comment]
running a long live test to debug the ceph-disk suite failure http://pulpito.ceph.com/loic-2017-06-06_07:18:33-ceph-disk-wip-bluestore-distro-basic-vps/1264333/

**Comment by liewegas** [comment]
https://github.com/ceph/ceph/pull/14074 just merged

**Comment by dachary** [comment]
fixed the ceph-disk suite bug (no lockbox compatibility did not create the "type" file and activation was failing). We should be good now ! Repushing to ceph-ci.

**Comment by dachary** [comment]
note to self: once it passes, rebase to verify #14074 did not break things

**Comment by dachary** [comment]
<pre>
========================================================= 23 passed, 1 skipped in 942.95 seconds =========================================================
</pre>
ceph-disk suite passes (manually on Ubuntu 16.04) but I don't see why it would not pass on other OS

**Comment by dachary** [comment]
<pre>teuthology-suite --priority 100 -k distro --verbose --suite ceph-disk --ceph wip-bluestore --machine-type vps</pre>

* **running** http://pulpito.ceph.com/loic-2017-06-06_17:43:31-ceph-disk-wip-bluestore-distro-basic-vps/

**Comment by dachary** [comment]
rebased & repushed

**Comment by dachary** [comment]
vps host disk died, rescheduled a run of the ceph-disk suite

**Comment by dachary** [comment]
I consistently get
<pre>
2017-06-06T21:31:14.150 INFO:tasks.ceph.mgr.x.ovh017.stderr:/home/jenkins-build/build/workspace/ceph-dev-new-build/ARCH/x86_64/AVAILABLE_ARCH/x86_64/AVAILABLE_DIST/centos7/DIST/centos7/MACHINE_SIZE/huge/release/12.0.2-2357-gdd1f471/rpm/el7/BUILD/ceph-12.0.2-2357-gdd1f471/src/mon/PGMap.cc: In function 'void PGMap::apply_incremental(CephContext*, const PGMap::Incremental&)' thread 7f1ee3b94700 time 2017-06-06 21:31:14.130335
2017-06-06T21:31:14.150 INFO:tasks.ceph.mgr.x.ovh017.stderr:/home/jenkins-build/build/workspace/ceph-dev-new-build/ARCH/x86_64/AVAILABLE_ARCH/x86_64/AVAILABLE_DIST/centos7/DIST/centos7/MACHINE_SIZE/huge/release/12.0.2-2357-gdd1f471/rpm/el7/BUILD/ceph-12.0.2-2357-gdd1f471/src/mon/PGMap.cc: 1085: FAILED assert(osd_stat.size() == osd_epochs.size())
2017-06-06T21:31:14.151 INFO:tasks.ceph.mgr.x.ovh017.stderr: ceph version  12.0.2-2357-gdd1f471 (dd1f47126deb239f70a10183867ef6a20d611d69) luminous (dev)
2017-06-06T21:31:14.151 INFO:tasks.ceph.mgr.x.ovh017.stderr: 1: (ceph::__ceph_assert_fail(char const*, char const*, int, char const*)+0x110) [0x7f1eefc7b500]
2017-06-06T21:31:14.151 INFO:tasks.ceph.mgr.x.ovh017.stderr: 2: (PGMap::apply_incremental(CephContext*, PGMap::Incremental const&)+0xf10) [0x7f1eefaf24e0]
2017-06-06T21:31:14.152 INFO:tasks.ceph.mgr.x.ovh017.stderr: 3: (ClusterState::update_delta_stats()+0xa9) [0x7f1eefb2e459]
2017-06-06T21:31:14.152 INFO:tasks.ceph.mgr.x.ovh017.stderr: 4: (DaemonServer::send_report()+0xcd) [0x7f1eefb1f3ed]
2017-06-06T21:31:14.152 INFO:tasks.ceph.mgr.x.ovh017.stderr: 5: (Mgr::tick()+0x70) [0x7f1eefb51990]
2017-06-06T21:31:14.152 INFO:tasks.ceph.mgr.x.ovh017.stderr: 6: (MgrStandby::tick()+0x89) [0x7f1eefb49489]
2017-06-06T21:31:14.152 INFO:tasks.ceph.mgr.x.ovh017.stderr: 7: (FunctionContext::finish(int)+0x2a) [0x7f1eefb2a97a]
2017-06-06T21:31:14.152 INFO:tasks.ceph.mgr.x.ovh017.stderr: 8: (Context::complete(int)+0x9) [0x7f1eefb26939]
2017-06-06T21:31:14.152 INFO:tasks.ceph.mgr.x.ovh017.stderr: 9: (SafeTimer::timer_thread()+0x104) [0x7f1eefc77dc4]
2017-06-06T21:31:14.152 INFO:tasks.ceph.mgr.x.ovh017.stderr: 10: (SafeTimerThread::entry()+0xd) [0x7f1eefc797ed]
2017-06-06T21:31:14.152 INFO:tasks.ceph.mgr.x.ovh017.stderr: 11: (()+0x7dc5) [0x7f1eed5d8dc5]
2017-06-06T21:31:14.152 INFO:tasks.ceph.mgr.x.ovh017.stderr: 12: (clone()+0x6d) [0x7f1eec6bd73d]
2017-06-06T21:31:14.152 INFO:tasks.ceph.mgr.x.ovh017.stderr: NOTE: a copy of the executable, or `objdump -rdS <executable>` is needed to interpret this.
2017-06-06T21:31:14.153 INFO:tasks.ceph.mgr.x.ovh017.stderr:2017-06-06 21:31:14.132289 7f1ee3b94700 -1 /home/jenkins-build/build/workspace/ceph-dev-new-build/ARCH/x86_64/AVAILABLE_ARCH/x86_64/AVAILABLE_DIST/centos7/DIST/centos7/MACHINE_SIZE/huge/release/12.0.2-2357-gdd1f471/rpm/el7/BUILD/ceph-12.0.2-2357-gdd1f471/src/mon/PGMap.cc: In function 'void PGMap::apply_incremental(CephContext*, const PGMap::Incremental&)' thread 7f1ee3b94700 time 2017-06-06 21:31:14.130335
</pre>

**Comment by dachary** [comment]
I don't get why it's failing consistently now. Trying to run the suite manually once more to get a clue.

**Comment by dachary** [comment]
Manual test works... can't figure out the difference with what happens when it is run to completion...

**Comment by dachary** [comment]
Turns out the failure to run the ceph-disk suite comes from a bug on master http://tracker.ceph.com/issues/20208 . Rebasing on a version of master dated a few weeks ago that passes.

**Comment by dachary** [comment]
<pre>teuthology-suite --priority 10 -k distro --verbose --suite ceph-disk --ceph wip-bluestore-old-base --machine-type vps</pre>

* **running** http://pulpito.ceph.com/loic-2017-06-07_08:35:10-ceph-disk-wip-bluestore-old-base-distro-basic-vps

**Comment by dachary** [comment]
@liewegas I believe it is ready to merge. The ceph-disk suite passes now (although using an older version of master from a few weeks ago because of http://tracker.ceph.com/issues/20208).

**Comment by liewegas** [comment]
yay!

**Pull request merged**
