### PR TITLE
cmake: dashboard: enable frontend on arm64

### PR DESCRIPTION
**Pull request by tchaikov**
## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`

</details>

### CODE REVIEW

**Comment by sebastian-philipp** [comment]
Interestingly I don't see how the dashboard is disabled in 

https://github.com/ceph/ceph/blob/master/make-dist

? make-dist is only executed on x86?

**Comment by tchaikov** [comment]
yeah, i checked that file also. it seems so.

**Comment by sebastian-philipp** [comment]
lgtm, **iff** Teuthology creates packages on all platforms.

**Comment by tchaikov** [comment]
> lgtm, **iff** Shaman creates packages on all platforms.

i think shaman does not create package, it servers RESTful service and a web GUI so we can query the build status.

and i am not sure why it's required to build all platforms so we can have this change. there are two reasons that i want get this change merged

- we should allow users to build the dashboard frontend from the source tree as long as the platform/distro allows.
- the cmake file is simpler this way.

**Comment by callithea** [comment]
Do we also want to enable the ``mgr-dashboard-frontend-unittests``?

**Comment by tchaikov** [comment]
@callithea thanks Laura. i think so. will enable it in another PR or i can piggyback it in this one.

**Comment by callithea** [comment]
> @callithea thanks Laura. i think so. will enable it in another PR or i can piggyback it in this one.

As you prefer - both is fine with me. :)

**Comment by rjfd** [comment]
@tchaikov can we merge this, and enable the frontend unit tests in another PR?

**Pull request merged**
