### PR TITLE
msg/async/rdma: event polling thread can block on event

### PR DESCRIPTION
**Pull request by yuyuyu101**

### CODE REVIEW

**Comment by yuyuyu101** [comment]
@Adirl give a look

**Comment by Adirl** [comment]
+      if ((ceph_clock_now(cct) - last_inactive).to_nsec() / 1000 > cct->_conf->ms_async_rdma_polling_us) {

maybe should be with *:

+      if ((ceph_clock_now(cct) - last_inactive).to_nsec() * 1000 > cct->_conf->ms_async_rdma_polling_us) {

**Comment by yuyuyu101** [comment]
@Adirl not follow.. to_nsec() is nanoseconds(ns). we need to divide 1000 to become microseconds(us)

**Comment by Adirl** [comment]
@yuyuyu101 
correct, i checked again, my bad :)

**Comment by Adirl** [comment]
@yuyuyu101 
patch looks important and good to me, 

consider this corner case: 
since you do "continue" after "rearm=true" it could be that when returning to poll_cq() now gets many cqe's and therefore won't never go again into if(!n). meaning blocking on poll() we never happen. is that allowed?  
hope i explained it well, let me know for any question

**Comment by yuyuyu101** [comment]
@Adirl why? if set rearm to true and got many cqe, after processing cqe we still can call poll. why it never happen?

**Comment by Adirl** [comment]
If they stop arriving so yes, you can get to poll

**Pull request merged**
