### PR TITLE
do_cmake.sh: fix ambiguous shell interpreter

### PR DESCRIPTION
**Pull request by iotcg**
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by tchaikov** [comment]
i think install-deps.sh is POSIX compliant. and it does work with dash. in your case, i'd suggest check your  environment variables, such as `PS{1,2,3,4}`, which are also interpreted by dash. probably you could try 


in my case

```sh
$ readlink -f `which sh`
/bin/dash
$ env -i sh -x -c 'PYBUILD="2"'
+ PYBUILD=2
```

**Comment by iotcg** [comment]
@tchaikov Thanks a lot. I start a new session to build ceph just now and hit this problem (never hit it before). I don't know which environment configuration result in different behavior.

This patch solves the ambiguity. If this patch is not needed. I'll abandon it.

BTW, I've changed the "sh" to be "bash" as the default shell interpreter in my system with the command "sudo dpkg-reconfigure dash"

**Comment by tchaikov** [comment]
as `PYBUILD="2"` is apparently compliant to POSIX, and we cannot explain why your change address the failure. i am closing this PR.

good to learn. you could also use `chsh` for changing your shell.

**Comment by iotcg** [comment]
@tchaikov Thanks for your info^_^

**Comment by iotcg** [comment]
@tchaikov You're right. It's PS4 environment var which causes the problem.
https://github.com/rvm/rvm/issues/2612

**Pull request closed without merging**
