### PR TITLE
ceph-volume: avoid unnecessary subprocess calls

### PR DESCRIPTION
**Pull request by guits**
These calls are slowing down `ceph-volume inventory`.
Especially because of the class `ceph_volume.util.device.Devices`.
It calls the class `ceph_volume.util.device.Device` for each device found
on the host which calls many times the binaries `lsblk`, `pvs`, `vgs`, `lvs` itself.
We can make only one call in `Devices()` to gather all details and use them during the whole runtime

current implementation:

```
        1    0.000    0.000    0.892    0.892 device.py:35(__init__) (class Devices)
        8    0.001    0.000    0.853    0.107 device.py:151(_parse)
       56    0.002    0.000    0.882    0.016 process.py:154(call)
        8    0.001    0.000    0.245    0.031 lvm.py:1099(get_lvs)
        8    0.000    0.000    0.026    0.003 disk.py:231(lsblk)
        8    0.000    0.000    0.435    0.054 device.py:278(_set_lvm_membership)
        1    0.000    0.000    0.885    0.885 device.py:38(<listcomp>) (multiple calls to Device() class)
      8/5    0.000    0.000    0.885    0.177 device.py:92(__init__) (class Device)

>>> timeit.timeit('Inventory([]).main()', setup='from ceph_volume.inventory import Inventory', number=1)

Device Path               Size         rotates available Model name
/dev/sdb                  200.00 GB    True    True      QEMU HARDDISK
/dev/sda                  200.00 GB    True    False     QEMU HARDDISK
/dev/sdc                  200.00 GB    True    False     QEMU HARDDISK
/dev/sdd                  200.00 GB    True    False     QEMU HARDDISK
/dev/vda                  11.00 GB     True    False
0.9309048530412838
>>>
```

new approach:

```
        1    0.000    0.000    0.253    0.253 device.py:35(__init__) (class Devices)
        5    0.000    0.000    0.144    0.029 device.py:167(_parse)
       21    0.001    0.000    0.246    0.012 process.py:154(call)
        1    0.000    0.000    0.032    0.032 lvm.py:1110(get_lvs)
        1    0.000    0.000    0.005    0.005 disk.py:236(lsblk_all)
        5    0.000    0.000    0.062    0.012 device.py:309(_set_lvm_membership)
        1    0.000    0.000    0.179    0.179 device.py:41(<listcomp>) (multiple calls to Device() class)
        5    0.000    0.000    0.179    0.036 device.py:99(__init__) (class Device)

>>> timeit.timeit('Inventory([]).main()', setup='from ceph_volume.inventory import Inventory', number=1)

Device Path               Size         rotates available Model name
/dev/sdb                  200.00 GB    True    True      QEMU HARDDISK
/dev/sda                  200.00 GB    True    False     QEMU HARDDISK
/dev/sdc                  200.00 GB    True    False     QEMU HARDDISK
/dev/sdd                  200.00 GB    True    False     QEMU HARDDISK
/dev/vda                  11.00 GB     True    False
0.2486933789914474
>>>
```

Signed-off-by: Guillaume Abrioux <gabrioux@redhat.com>

### CODE REVIEW

**Comment by guits** [comment]
jenkins test ceph-volume tox

**Comment by guits** [comment]
jenkins test ceph-volume tox

**Comment by guits** [comment]
jenkins test ceph-volume tox

**Comment by guits** [comment]
jenkins test api

**Comment by guits** [comment]
jenkins test ceph-volume tox

**Comment by guits** [comment]
jenkins test api

**Comment by guits** [comment]
jenkins test ceph-volume tox

**Comment by guits** [comment]
jenkins test ceph-volume tox

**Comment by guits** [comment]
http://pulpito.front.sepia.ceph.com/gabrioux-2022-06-28_06:50:40-orch:cephadm-wip-guits-testing-2022-06-28-0505-distro-default-smithi/

**Comment by pcuzner** [comment]
Looks good. I tested on a physical machine with a bunch of ssd/nvme drives

Before
<pre>
[ceph: root@f12-h09-000-1029u /]# time ceph-volume inventory                                                                                                                                                                                 

Device Path               Size         rotates available Model name
/dev/sdb                  894.25 GB    False   True      INTEL SSDSC2KB96
/dev/sdc                  894.25 GB    False   True      INTEL SSDSC2KB96
/dev/sdd                  894.25 GB    False   True      INTEL SSDSC2KB96
/dev/sde                  894.25 GB    False   True      INTEL SSDSC2KB96
/dev/nvme0n1              894.25 GB    False   False     SAMSUNG MZ1LW960HMJP-00003
/dev/nvme1n1              894.25 GB    False   False     SAMSUNG MZQLB960HAJR-00007
/dev/nvme2n1              894.25 GB    False   False     SAMSUNG MZQLB960HAJR-00007
/dev/nvme3n1              447.12 GB    False   False     Linux
/dev/nvme3n2              447.12 GB    False   False     Linux
/dev/nvme3n3              447.12 GB    False   False     Linux
/dev/nvme3n4              447.12 GB    False   False     Linux
/dev/nvme3n5              447.12 GB    False   False     Linux
/dev/nvme3n6              447.12 GB    False   False     Linux
/dev/sda                  447.13 GB    False   False     INTEL SSDSC2KB48

real    0m3.559s
user    0m0.931s
sys     0m0.957s

</pre>

After
<pre>
(ceph-volume-testing) [root@f12-h09-000-1029u inventory]# time ceph-volume inventory                                                                                                                                                          
                                                                                                                                                                                                                                              
Device Path               Size         rotates available Model name                                                                                                                                                                           
/dev/sdb                  894.25 GB    False   True      INTEL SSDSC2KB96                                                                                                                                                                     
/dev/sdc                  894.25 GB    False   True      INTEL SSDSC2KB96                                                                                                                                                                     
/dev/sdd                  894.25 GB    False   True      INTEL SSDSC2KB96                                                                                                                                                                     
/dev/sde                  894.25 GB    False   True      INTEL SSDSC2KB96                                                                                                                                                                     
/dev/nvme0n1              894.25 GB    False   False     SAMSUNG MZ1LW960HMJP-00003                                                                                                                                                           
/dev/nvme1n1              894.25 GB    False   False     SAMSUNG MZQLB960HAJR-00007                                                                                                                                                           
/dev/nvme2n1              894.25 GB    False   False     SAMSUNG MZQLB960HAJR-00007                                                                                                                                                           
/dev/nvme3n1              447.12 GB    False   False     Linux                                                                                                                                                                                
/dev/nvme3n2              447.12 GB    False   False     Linux                                                                                                                                                                                
/dev/nvme3n3              447.12 GB    False   False     Linux                                                                                                                                                                                
/dev/nvme3n4              447.12 GB    False   False     Linux
/dev/nvme3n5              447.12 GB    False   False     Linux
/dev/nvme3n6              447.12 GB    False   False     Linux
/dev/sda                  447.13 GB    False   False     INTEL SSDSC2KB48

real    0m1.086s
user    0m0.424s
sys     0m0.295s
(ceph-volume-testing) [root@f12-h09-000-1029u inventory]# deactivate
</pre>

**Comment by adk3798** [comment]
https://pulpito.ceph.com/adking-2022-07-01_05:11:14-orch:cephadm-wip-adk-testing-2022-06-30-2110-distro-default-smithi/

4 Failed tests from
```
Command failed on smithi162 with status 123: "find /home/ubuntu/cephtest/archive/syslog -name '*.log' -print0 | sudo xargs -0 --no-run-if-empty -- gzip --"
```
and 1 dead test from
```
{'smithi050.front.sepia.ceph.com': {'attempts': 12, 'censored': "the output has been hidden due to the fact that 'no_log: true' was specified for this result", 'changed': True}}
```
I believe these are all infra issues and I did see these same failures in another run with different PRs (and notably, not on the same tests) in 
https://pulpito.ceph.com/adking-2022-07-01_05:08:10-orch:cephadm-wip-adk3-testing-2022-06-30-2111-distro-default-smithi/

Quite confident the failures are unrelated to PRs in the run, so I think we're good here.

**Review by adk3798 — APPROVED** [review]
LGTM

**Pull request merged**
