### PR TITLE
mds: do not acquire xlock in xlockdone state

### PR DESCRIPTION
**Pull request by ifed01**
This patch is an alternative to https://github.com/ceph/ceph/pull/42861

It prohibits xlock acquisition in xlock_done state and unconditionally puts the incoming request on wait if the latter is observed.

Fixes: https://tracker.ceph.com/issues/49132

Signed-off-by: Igor Fedotov <igor.fedotov@croit.io>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by vshankar** [comment]
> This patch is an alternative to #42861
> 
> It prohibits xlock acquisition in xlock_done state and unconditionally puts the incoming request on wait if the latter is observed.

The assert seems to be hit only for filelock. This change is generic for all lock types. Is that intentional?

**Comment by ifed01** [comment]
> > This patch is an alternative to #42861
> > It prohibits xlock acquisition in xlock_done state and unconditionally puts the incoming request on wait if the latter is observed.
> 
> The assert seems to be hit only for filelock. This change is generic for all lock types. Is that intentional?

Hi @vshankar, thanks for reviewing..

Indeed the assertion might occur on CEPH_LOCK_IFILE only - there is relevant preceding assert on lock type at set_xlock_snap_sync. Honestly I missed that before you comment. 
Personally at this point I'd prefer to avoid any additional bifurcation on lock type and keep the handling as general as possible. Do you see any negative impact of that? Anyway I'm definitely not an expert in this stuff hence will undoubtedly follow your recommendations - please advise.
More general question - do you think this approach for bug fixing makes sense at all?

**Comment by ifed01** [comment]
> Definitely not any negative impact on functionality as such, however, maybe for other locks types it isn't an issue and I would leave them to function as it is.

Fixed

**Comment by vshankar** [comment]
fs suite runs are fine with this change - https://pulpito.ceph.com/?branch=wip-vshankar-testing-20221130.043104

Failures are teuthology related (unreachable git.ceph.com) and other known issues mentioned here: https://tracker.ceph.com/projects/cephfs/wiki/Main

@lxbsz Could you have a look at this change esp. in comparison with PR https://github.com/ceph/ceph/pull/42861

(note that results from my latest test run are published yet in the run log)

**Comment by vshankar** [comment]
@lxbsz Did you get a change to look at this vs your contending change?

**Comment by lxbsz** [comment]
Sorry I think I just missed this PR. This change looks much simpler than https://github.com/ceph/ceph/pull/42861.

**Review by lxbsz — APPROVED** [review]
It looks good to me.

**Comment by vshankar** [comment]
> Sorry I think I just missed this PR. This change looks much simpler than #42861.

RIght. But I recall you mentioning that the intermediate state you used in your fix was to recall certain caps ('Fb'?) from clients. This change avoids that altogether which looks fine to me as the operation will be put on hold (waiting in queue) since the lock cannot be acquired, but I wanted to confirm that.

**Comment by lxbsz** [comment]
@ifed01 

Could add the detail comments in the commit ? I will close my PR and will revise the tracker and set your PR to it.

**Comment by lxbsz** [comment]
> > Sorry I think I just missed this PR. This change looks much simpler than #42861.
> 
> RIght. But I recall you mentioning that the intermediate state you used in your fix was to recall certain caps ('Fb'?) from clients. This change avoids that altogether which looks fine to me as the operation will be put on hold (waiting in queue) since the lock cannot be acquired, but I wanted to confirm that.

Yeah, I think just queuing the request could resolve that issue too.

**Review by vshankar — APPROVED** [review]
https://tracker.ceph.com/projects/cephfs/wiki/Main#08-Dec-2022

**Pull request merged**
