### PR TITLE
rgw: region data still exist in region-map  after region-map update

### PR DESCRIPTION
**Pull request by dwj192**
Delete a region and update region-map, region-map still contain the region data.
region-map update just add new and did not remove the old.

Signed-off-by: duanweijun duanweijun@h3c.com

### CODE REVIEW

**Comment by yehudasa** [comment]
@dwj192 can you open a ceph tracker issue and reference it in the commit message?

**Comment by dwj192** [comment]
sorry，Since our network restrictions，I can't open a ceph tracker issue.
The following is a description of my problem：

this is my region:
$rados -p .rgw.root ls
<pre>
default.region
region_info.default
zone_info.default
region_info.my-region
</pre>

delete region_info.my-region
$rados -p .rgw.root rm region_info.my-region
<pre>
default.region
region_info.default
region_map
zone_info.default
</pre>

update region-map
$radosgw-admin region-map update
<pre>
{
    "regions": [
        {
            "key": "default",
            "val": {
                "name": "default",
                "api_name": "",
                "is_master": "true",
                "endpoints": [],
                "hostnames": [],
                "master_zone": "",
                "zones": [
                    {
                        "name": "default",
                        "endpoints": [],
                        "log_meta": "false",
                        "log_data": "false",
                        "bucket_index_max_shards": 0
                    }
                ],
                "placement_targets": [
                    {
                        "name": "default-placement",
                        "tags": []
                    }
                ],
                "default_placement": "default-placement"
            }
        },
        {
            "key": "my-region",
            "val": {
                "name": "my-region",
                "api_name": "",
                "is_master": "false",
                "endpoints": [],
                "hostnames": [],
                "master_zone": "",
                "zones": [
                    {
                        "name": "default",
                        "endpoints": [],
                        "log_meta": "false",
                        "log_data": "false",
                        "bucket_index_max_shards": 0
                    }
                ],
                "placement_targets": [
                    {
                        "name": "default-placement",
                        "tags": []
                    }
                ],
                "default_placement": "default-placement"
            }
        }
    ],
    "master_region": "default",
    "bucket_quota": {
        "enabled": false,
        "max_size_kb": -1,
        "max_objects": -1
    },
    "user_quota": {
        "enabled": false,
        "max_size_kb": -1,
        "max_objects": -1
    }
}
</pre>

regiondata (my-region) still exist in region-map
unless, delete region-map and update it, my-region Will disappear
$rados -p .rgw.root rm region_map

**Comment by dwj192** [comment]
@yehudasa  I modified it inappropriate? Could you give me some advice? Thank you!

**Comment by yehudasa** [comment]
@dwj192 the original idea was to not require all the region configurations to reside on all of the regions. You just transfer the region map between the regions, and add the region configuration for each one. With your change we'll need to distribute all the configurations of all the regions everywhere. I suggest that you modify your fix and make it clear the map only if some option was passed to radosgw-admin (e.g., map update --reset-regions)

**Comment by dwj192** [comment]
@yehudasa  Modification is completed, is it OK? Thank you!

**Pull request closed without merging**
