### PR TITLE
core: Dedicate a type to _buffers member of buffer::list

### PR DESCRIPTION
**Pull request by efirs**
Not a functional change.
Helps to easily change _buffers type in the future.

### CODE REVIEW

**Comment by gregsfortytwo** [comment]
If you want to make changes to the _buffers type you can do that, but just include this as part of the PR. It's unlikely to be maintained across other changes to the code base and there's not point to having it in.

If you do want to do something like this, you'll also need to handle all the bufferptr users, not just a few of them — probably by changing the bufferptr declaration in buffer_fwd.h rather than updating each user. ;)

**Comment by efirs** [comment]
> If you want to make changes to the _buffers type you can do that, but just include this as part of the PR. It's unlikely to be maintained across other changes to the code base and there's not point to having it in.

@gregsfortytwo ok. agree. people won't maintain new usages. But, please read weak defensive argument below.
 
> If you do want to do something like this, you'll also need to handle all the bufferptr users, not just a few of them — probably by changing the bufferptr declaration in buffer_fwd.h rather than updating each user. ;)

We don't need to change buffeptr users, just std::list<bufferptr> users. All of them my patch changes, I believe. Those users get access to _buffers by calling buffer::list::buffers(), which violently brakes encapsulation and shouldn't be there in first place, so there shouldn't be new usages of that function :)

**Comment by liewegas** [comment]
Is the motivation here to be able to change from list<ptr> to something else in the future?

**Comment by efirs** [comment]
@liewegas Yes. I already tried to replace it with the list with custom stl allocator. But so as it doesn't support move it was slower. Later it can be replaced with boost small_vector. With this patch we just need to change one line.

**Comment by liewegas** [comment]
Okay, sounds good.

Is the problem that buffer::ptr doesn't have an efficient move operation?

FWIW, this is the other possible buffer direction, which would turn this into an intrusive list: https://github.com/ceph/ceph/pull/5534

**Comment by efirs** [comment]
@liewegas No, this is because std::list loses ability to be moved, so when we copy bufferlist we need to copy every ptr of its _buffers one by one.

**Pull request closed without merging**
