### PR TITLE
common/win32,dokan: include bcrypt.h for NTSTATUS 

### PR DESCRIPTION
**Pull request by tchaikov**
## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [x] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by tchaikov** [comment]
https://shaman.ceph.com/builds/ceph/wip-ntstatus/5623bc3c3ac4d86ce1a37c7a11c76ca615060970/

**Review by adamemerson — APPROVED** [review]

**Comment by tchaikov** [comment]
```
[2022-07-21T23:52:36.000Z] [googletest] unittest_encoding.exe failed. Error: Command returned non-zero code(1): "cmd /c 'C:\ceph\unittest_encoding.exe --gtest_output=xml:C:\workspace\test_results\unittest_encoding_results.xml  > C:\workspace\test_results\unittest_encoding_results.log 2>&1'".
```

**Comment by tchaikov** [comment]
jenkins test windows

**Comment by tchaikov** [comment]
```
[ RUN      ] EncodingException.Macros
../src/test/encoding.cc:341: Failure
Expected equality of these values:
  string(expected_what[i])
    Which is: "void lame_decoder(int) no longer understand old encoding version 100 < 200: Malformed input"
  string(e.what())
    Which is: "void lame_decoder(int) no longer understand old encoding version 100 < 200: Malformed input [buffer:3]"
[  FAILED  ] EncodingException.Macros (0 ms)
```

**Comment by tchaikov** [comment]
needs to address the test failure first.

**Comment by tchaikov** [comment]
jenkins test make check

**Comment by tchaikov** [comment]
@adamemerson i fixed the test. could you please take another look?

**Review by adamemerson — APPROVED** [review]
Looks good to me.

**Comment by tchaikov** [comment]
https://shaman.ceph.com/builds/ceph/wip-ntstatus-kefu/b3151a9c373b472c7e88080205fc256a1304fe9d/

**Comment by djgalloway** [comment]
@adamemerson is this still good after the force pushes?

**Comment by tchaikov** [comment]
changelog

- move `#include <bcrypt.h>` up before `#include <dokan.h>` in `src/dokan/ceph_dokan.h` to avoid undefined type FTBFS.

**Comment by tchaikov** [comment]
@adamemerson @djgalloway i am going to merge this change, as the latest force pushes was trivial changes. if anything looks insane, i will fix it ASAP.

**Pull request merged**
