### PR TITLE
ceph / ceph-dbg steal ceph-objecstore-tool from ceph-test / ceph-test-dbg

### PR DESCRIPTION
**Pull request by dachary**
http://tracker.ceph.com/issues/11806

### CODE REVIEW

**Comment by liewegas** [comment]
LGTM

**Comment by ktdreyer** [comment]
In the future,  when doing these kind of backports where we have to insert a Replaces/Breaks version number, we'll want to alter the "`git describe`" value for each backport, since that value is branch-specific. Right? At least that's how I'd been doing them :)

**Comment by dachary** [comment]
@ktdreyer you are correct... the backport is wrong. Makes me wonder how and why it passed the tests.

**Comment by dachary** [comment]
It's interestingly harmless actually. Just confusing. What matters is that the package claims to break/replace versions that are lower than it is so that older packages are known to have files that will be replaced. But from the point of view of a package that is more recent, it won't be taken into account. And if upgrading to the package that has the same replace/breaks in master, it wont matter either because the files have already moved and it will succeed if these fields are correctly or incorrectly interpreted. 

@ktdreyer am I making sense or am I confused ?

**Comment by ktdreyer** [comment]
I think this particular PR worked in this particular situation because "`git describe`" on master currently returns a smaller version (`0.94`) than the tip of hammer (`0.94.1-something`). After Infernalis is released, "`git describe`" on master is going to print "`9.something`", and it will be more of an issue.

Firefly is already in this situation - the "`git describe` version from master is much higher than "`git describe`" on firefly, so "`Breaks: 0.94-something`" isn't going to have an effect in the Firefly packages.

**Pull request merged**
