### PR TITLE
test/librados: increase pgp_num along with pg_num

### PR DESCRIPTION
**Pull request by tchaikov**
Fixes: http://tracker.ceph.com/issues/23763
Signed-off-by: Kefu Chai <kchai@redhat.com>

### CODE REVIEW

**Comment by tchaikov** [comment]
retest this please

**Comment by tchaikov** [comment]
tested at http://pulpito.ceph.com/kchai-2018-04-24_02:38:23-rados-wip-kefu-testing-2018-04-23-2204-distro-basic-smithi/

the failure are tracked/addressed by 

- http://tracker.ceph.com/issues/23653
- #21607

**Comment by tchaikov** [comment]
retest this please.

**Comment by jcsp** [comment]
@tchaikov yep, I agree with whitelisting PG_AVAILABILITY anywhere we're adjusting pg_num

**Pull request merged**
