### PR TITLE
quincy: osd, mds: fix the "heap" admin cmd printing always to error stream

### PR DESCRIPTION
**Pull request by ljflores**
Quincy backport of #47650

Tracker: https://tracker.ceph.com/issues/57312
Parent tracker: https://tracker.ceph.com/issues/57119

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by ljflores** [comment]
Opening this to test in parallel with the main PR.

**Review by rzarzynski — APPROVED** [review]

**Comment by yaarith** [comment]
https://trello.com/c/g9AE6IT8/1621-wip-lflores-testing-2-2022-08-26-2240-quincy

**Unrelated failures:**
1.7005508/7005511/7005512/7005516/7005517/7005519/7005520/7005523/7005525/7005528/7005529 - Failed to fetch package version from https://shaman.ceph.com
2. 7005509/7005521/7005527 -  The CustomResourceDefinition "installations.operator.tigera.io" is invalid: metadata.annotations: Too long: must have at most 262144 bytes
3. 7005510/7005524 - expected valgrind issues and found none
4. 7005513/7005522 - The repository 'https://download.ceph.com/debian-octopus jammy Release' does not have a Release file
5. 7005514 - test_dashboard_e2e.sh: Expected to find content: 
6. 7005515 - ‘kubectl -n rook-ceph exec rook-ceph-tools-7564bb9799-l72kw -- ceph orch apply osd --all-available-devices'

**Tracked by:**
1. https://tracker.ceph.com/issues/57303 
quincy: rados/cephadm: Failed to fetch package version from https://shaman.ceph.com/api/search/?status=ready&project=ceph&flavor=default&distros=ubuntu%2F22.04%2Fx86_64&sha1=b34ca7d1c2becd6090874ccda56ef4cd8dc64bf7
2. https://tracker.ceph.com/issues/57368 
The CustomResourceDefinition "installations.operator.tigera.io" is invalid: metadata.annotations: Too long: must have at most 262144 bytes
3. https://tracker.ceph.com/issues/57165
 expected valgrind issues and found none
4. https://tracker.ceph.com/issues/57270
 cephadm: RuntimeError: Failed command: apt-get update: E: The repository 'https://download.ceph.com/debian-octopus jammy Release' does not have a Release file.
5. https://tracker.ceph.com/issues/57386
cephadm/test_dashboard_e2e.sh: Expected to find content: '/^foo$/' within the selector: 'cd-modal .badge' but never did
6. https://tracker.ceph.com/issues/56951
 rook/smoke: Updating cephclusters/rook-ceph is forbidden

**Comment by yaarith** [comment]
jenkins test make check

**Comment by yaarith** [comment]
jenkins test windows

**Review by vshankar — APPROVED** [review]

**Comment by rzarzynski** [comment]
jenkins test make check

**Comment by rzarzynski** [comment]
This PR has been labelled as `wip-lflores-testing-2` 1 week ago but I'm not sure what's the status. To check.

**Comment by yaarith** [comment]
> https://trello.com/c/g9AE6IT8/1621-wip-lflores-testing-2-2022-08-26-2240-quincy

@rzarzynski Yuri was testing this again yesterday, see: https://trello.com/c/g9AE6IT8/1621-wip-lflores-testing-2-2022-08-26-2240-quincy

**Comment by yuriw** [comment]
jenkins test make check

**Pull request merged**
