### PR TITLE
octopus: packaging: require ceph-common for immutable object cache daemon

### PR DESCRIPTION
**Pull request by idryomov**
backport tracker: https://tracker.ceph.com/issues/50232

---

backport of https://github.com/ceph/ceph/pull/40641
parent tracker: https://tracker.ceph.com/issues/50207

### CODE REVIEW

**Review by smithfarm — APPROVED** [review]

**Comment by tchaikov** [comment]
- https://pulpito.ceph.com/kchai-2021-04-12_02:35:25-rados-wip-kefu-octopus-testing-2021-04-11-2349-distro-basic-gibba/
- https://pulpito.ceph.com/kchai-2021-04-12_13:55:39-rados-wip-kefu-octopus-testing-2021-04-11-2349-distro-basic-smithi/

i think most of cephadm test failures are caused by https://tracker.ceph.com/issues/49293

**Comment by yuriw** [comment]
test api please

**Comment by idryomov** [comment]
jenkins test api

**Comment by yuriw** [comment]
@smithfarm this PR passed tests and can be merged as soon as API tests pass

**Pull request merged**
