### PR TITLE
pybind/mgr/devicehealth: do not crash if db not ready

### PR DESCRIPTION
**Pull request by batrick**
This is a remote method called by telemtry so the @CLIRequiresDB decorator isn't appropriate.

Fixes: https://tracker.ceph.com/issues/56239

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Review by yaarith — APPROVED** [review]

**Review by ljflores — APPROVED** [review]

**Comment by batrick** [comment]
rebased

**Comment by batrick** [comment]
rebased

**Comment by batrick** [comment]
@yuriw please include in your next RADOS run.

**Comment by batrick** [comment]
https://pulpito.ceph.com/pdonnell-2023-06-22_22:42:21-rados:mgr-wip-pdonnell-testing-20230622.184117-distro-default-smithi/

Failure is unrelated with progress module testing. Will write up a ticket for that later. Merging this to unblock other QA testing requiring a rebase.

**Pull request merged**
