### PR TITLE
rgw: fix all users acl write permission

### PR DESCRIPTION
**Pull request by lnsyyj**
Bugfix,
Anonymous users in the set All Users Write permission to modify the file in the bucket, resulting in bucket owners can not access.

http://tracker.ceph.com/issues/17971

Signed-off-by: JiangYu lnsyyj@hotmail.com

### CODE REVIEW

**Comment by lnsyyj** [comment]
test Methods:
1.set a bucket to all user write permissions
2.use the postman to send a put request, in the bucket to create a file
3.gets the acl of the created file
4.bug recurrence

**Comment by mattbenjamin** [comment]
@lnsyyj please see @yehudasa comment on 17971.

"when a user uploads an object, that user is the owner of that object. This PR changes this semantics and it's incorrect. The question that we have is who should be the owner of an object created by the anonymous user. It can either be the bucket owner, or the anonymous group. It might be that the actual issue is that when the all-users group is the owner, any authenticated user cannot read that object."

**Comment by lnsyyj** [comment]
@mattbenjamin Thank you, I understand. I think, in fact, this is normal. I tested an anonymous user to delete, the object is to operate.
I do not think the problem needs to be revised, is that the case? If you do not need to change, I explain to our company's testers.

**Comment by lnsyyj** [comment]
@mattbenjamin 
We have encountered a problem, the problem is this:
1.bucket is empty, without any object
2.bucket have all-users write permission
3. Using postman, the unauthenticated user deletes the bucket
4. Return to 204
5. Authenticated users can also see the bucket, but can not operate, return 404
6. Use the postman to put the bucket, prompt
<? Xml version = "1.0" encoding = "UTF-8"?>
<Error>
     <Code> AccessDenied </ Code>
     <BucketName> yyyy </ BucketName>
     <RequestId> tx000000000000000000007-00585c88f3-12200-default </ RequestId>
     <HostId> 12200-default-default </ HostId>
</ Error>

**Pull request closed without merging**
