### PR TITLE
mgr/cephadm: specify ports for iscsi

### PR DESCRIPTION
**Pull request by adk3798**
Fixes: https://tracker.ceph.com/issues/57786

Signed-off-by: Adam King <adking@redhat.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [x] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [x] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by adk3798** [comment]
https://pulpito.ceph.com/adking-2022-10-06_23:49:45-orch:cephadm-wip-adk-testing-2022-10-06-1758-distro-default-smithi/7057393/
```
2022-10-07T03:21:06.981 INFO:journalctl@ceph.mon.a.smithi043.stdout:Oct 07 03:21:06 smithi043 bash[12415]: Cannot bind to IP 0.0.0.0 port 3260: [Errno 98] Address already in use
2022-10-07T03:21:06.982 INFO:journalctl@ceph.mon.a.smithi043.stdout:Oct 07 03:21:06 smithi043 bash[12415]: ERROR: TCP Port(s) '5000,3260' required for iscsi already in use
2022-10-07T03:21:06.982 INFO:journalctl@ceph.mon.a.smithi043.stdout:Oct 07 03:21:06 smithi043 bash[12415]: cluster 1665112865.4040878 mgr.y (mgr.14152) 417 : cluster [DBG] pgmap v403: 132 pgs: 132 active+clean; 582 KiB data, 54 MiB used, 715 GiB / 715 GiB avail
2022-10-07T03:21:06.983 INFO:journalctl@ceph.mon.a.smithi043.stdout:Oct 07 03:21:06 smithi043 bash[12415]: cluster 1665112865.6111012 mon.a (mon.0) 705 : cluster [WRN] Health check failed: Failed to place 1 daemon(s) (CEPHADM_DAEMON_PLACE_FAIL)
```

**Comment by adk3798** [comment]
> 

looks like we'll need something a bit different here. We want to make sure the 3260 port is open in the firewall, but we don't actually need iscsi to bind to this port so we shouldn't fail deployment if it's in use.

**Review by phlogistonjohn — APPROVED** [review]
LGTM.

It's a bit unfortunate that the test is so much more complex that then code change, but that's the way tests work out sometimes.

**Comment by adk3798** [comment]
> > 
> 
> looks like we'll need something a bit different here. We want to make sure the 3260 port is open in the firewall, but we don't actually need iscsi to bind to this port so we shouldn't fail deployment if it's in use.

added a new "external_ports" dict object to our Firewall class in the binary for ports that need to be opened for a daemon type but aren't ports the daemon actually needs to bind to itself. The idea is to have a place for ports that we should try to open in the firewall but we shouldn't fail deployment of the daemon if the port cannot be bound to.

**Comment by adk3798** [comment]
jenkins test make check

**Comment by adk3798** [comment]
jenkins test api

**Comment by adk3798** [comment]
https://pulpito.ceph.com/adking-2022-12-02_21:56:44-orch:cephadm-wip-adk-testing-2022-12-02-0932-distro-default-smithi/

Failures tracked by:

- https://tracker.ceph.com/issues/49287
- https://tracker.ceph.com/issues/57755
- https://tracker.ceph.com/issues/57771
- https://tracker.ceph.com/issues/58145
- https://tracker.ceph.com/issues/58173

It's a lot of failures, but other than the the last one, they are all things we were aware of before the run (even the dead mgr-nfs-upgrade job had a `mount.nfs: mounting smithi174:/fake failed, reason given by server: No such file or directory` issue). The last one (https://tracker.ceph.com/issues/58173) as well seems to be a failure on a test setting flags on a pool, and given all the PRs in this run strictly touched mgr modules, I think it's unlikely any of the attached PRs caused the failures. Overall, I think the failures should only block merging on PRs related to nfs due to https://tracker.ceph.com/issues/58145 making it so we can't properly run our nfs related tests currently.

**Comment by adk3798** [comment]
jenkins retest this please

**Comment by adk3798** [comment]
jenkins test make check

**Pull request merged**
