### PR TITLE
install-deps, rpm: use python_provide macro and cleanups

### PR DESCRIPTION
**Pull request by tchaikov**
## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`

</details>

### CODE REVIEW

**Comment by tserong** [comment]
I'm not sure we've got %python_provide on SUSE distros, hang on...

**Comment by badone** [comment]
> I'm not sure we've got %python_provide on SUSE distros, hang on...

The nightmare continues Tim... ;)

**Comment by tchaikov** [comment]
@tserong neither `python3_pkgversion` nor `python_provide` exists in https://github.com/opensuse/python-rpm-macros AFAICT, so 
```
%{?python_provide:%python_provide python%{python3_pkgversion}-rgw}
```
will be a no-op as `python3_pkgversion` defaults to 3.

**Comment by tserong** [comment]
...actually I think this should be OK for SUSE. I did a test build with this patch applied, and packages *still* end up with the correct Provides, even though we don't have %python_provide on openSUSE:

```
# rpm -q --provides -p x86_64/python3-rgw-15.0.0-3155.g1043154123.x86_64.rpm 
python-rgw = 15.0.0-3155.g1043154123
python3-rgw = 15.0.0-3155.g1043154123
python3-rgw(x86-64) = 15.0.0-3155.g1043154123
```

**Comment by tchaikov** [comment]
yeah, that's my understanding. and i think i explained why.

**Comment by tserong** [comment]
Yeah, I got concerned because I noted that the "Provides: python3-$whatever" lines were removed, but hadn't realised that "Provides: python3-$whatever" is added automatically anyway because the package is named python3-$whatever. Also your earlier comment explaining this was somehow not visible in my browser window when I wrote my comment :-/ (probably my fault)

**Comment by tchaikov** [comment]
https://shaman.ceph.com/builds/ceph/wip-rpm-install-deps-python-provide/9ae33df4ca1231b45955626501d264faf9569b94/

**Comment by smithfarm** [comment]
> ...actually I think this should be OK for SUSE. I did a test build with this patch applied, and packages _still_ end up with the correct Provides, even though we don't have %python_provide on openSUSE:
> 
> ```
> # rpm -q --provides -p x86_64/python3-rgw-15.0.0-3155.g1043154123.x86_64.rpm 
> python-rgw = 15.0.0-3155.g1043154123
> python3-rgw = 15.0.0-3155.g1043154123
> python3-rgw(x86-64) = 15.0.0-3155.g1043154123
> ```

That definitely doesn't look right. `python3-rgw` should not provide `python-rgw`.

@tchaikov Don't let that block this PR. If this PR really introduces a SUSE packaging issue, we can fix that in a follow-up PR.

**Comment by smithfarm** [comment]
I tried on the 14.2.2 that I have on my system:

```
# rpm -q --provides python3-rgw
python-rgw = 14.2.2.348+gf6da3d1d18-1.3
python3-rgw = 14.2.2.348+gf6da3d1d18-1.3
python3-rgw(x86-64) = 14.2.2.348+gf6da3d1d18-1.3
```

So it's an unrelated issue.

**Comment by tchaikov** [comment]
> `python3-rgw` should not provide `python-rgw`.

@smithfarm i concur with you. but IIRC, it was intended to fix an issue you were facing.

**Comment by smithfarm** [comment]
@tchaikov Which issue is that?

**Comment by tchaikov** [comment]
@smithfarm ^

**Comment by tchaikov** [comment]
@smithfarm https://github.com/ceph/ceph/pull/30830#issuecomment-540496936

**Comment by smithfarm** [comment]
@tchaikov Thanks for reminding :-) Now I remember - having our `python3-*` packages provide their `python-*` counterparts helps with the upgrade, because it makes the old `python-*` packages go away when the new `python3-*` packages are installed.

**Pull request merged**
