### PR TITLE
luminous: librbd: remove consistency group rbd cli and API support

### PR DESCRIPTION
**Pull request by dillaman**
Signed-off-by: Jason Dillaman <dillaman@redhat.com>

### CODE REVIEW

**Comment by dillaman** [comment]
retest this please

**Comment by shun-s** [comment]
hi, dillaman, 
i want to know wether ceph will support consistency group  after ``` luminous ``` ?
thanks

**Comment by dillaman** [comment]
@shun-s if it's (near) feature complete, yes

**Comment by shun-s** [comment]
@dillaman  
OK, 3q

**Comment by trociny** [comment]
@dillaman in case you have not noticed, it needs rebase

**Comment by dillaman** [comment]
@trociny there aren't any conflicts -- it's just GitHub saying you can merge the contents of the luminous branch into this branch (before merging it back into the luminous branch).

**Pull request merged**
