### PR TITLE
Objecter: potential null pointer access when do pool_snap_list.

### PR DESCRIPTION
**Pull request by xiexingguo**
Objecter: potential null pointer access when do pool_snap_list. Shall check pool existence first.
Fixes: #13639
Signed-off-by: xie xingguo <xie.xingguo@zte.com.cn>

### CODE REVIEW

**Comment by xiexingguo** [comment]
@tchaikov  And this one too~~

**Comment by xiexingguo** [comment]
@tchaikov Do you consider this commit is ready for merge? Since this change is quite simple and obvious. 
Thanks a lot.

**Comment by jdurgin** [comment]
Good catch, the fixes look good to me.

**Comment by tchaikov** [comment]
lgtm also.

**Pull request merged**
