### PR TITLE
reef: backport of rook orchestrator fixes and e2e automated testing

### PR DESCRIPTION
**Pull request by rkachach**
Backport of: 

https://github.com/ceph/ceph/pull/54307 (mgr/dashboard: fix secure_monitoring_stack check)
Tracker: [63444](https://tracker.ceph.com/issues/63444)

https://github.com/ceph/ceph/pull/53747 (mgr/rook: Adding support to automatically discover storage classes)
Tracker: [63484](https://tracker.ceph.com/issues/63484)

https://github.com/ceph/ceph/pull/53910 (mgr/rook: fixing rook-ceph-exporter daemon type handling)
Tracker: [63266](https://tracker.ceph.com/issues/63266)

https://github.com/ceph/ceph/pull/54151 (mgr/rook: fix the namespaces used in rook and removes hard-coded)
Tracker: [63359](https://tracker.ceph.com/issues/63359)

https://github.com/ceph/ceph/pull/54056 (mgr/rook: adding e2e testing for rook orchestrator)
Tracker: [63463](https://tracker.ceph.com/issues/63463)

https://github.com/ceph/ceph/pull/54364 (github: adding command for rook e2e jenkins job)
Tracker: [63489](https://tracker.ceph.com/issues/63489)

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [x] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [x] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by rkachach** [comment]
jenkins test rook e2e

**Comment by rkachach** [comment]
jenkins test dashboard

**Comment by rkachach** [comment]
jenkins test make check

**Comment by rkachach** [comment]
jenkins test rook e2e

**Review by nizamial09 — APPROVED** [review]

**Comment by nizamial09** [comment]
jenkins test api

**Comment by rkachach** [comment]
jenkins test dashboard

**Review by jmolmo — APPROVED** [review]

**Review by adk3798 — APPROVED** [review]

**Pull request merged**
