### PR TITLE
cmake: remove Doxyfile as doxygen run via make

### PR DESCRIPTION
**Pull request by yuvalif**
also update document doxygen behavior
this is to complete: https://github.com/ceph/ceph/pull/35027

Signed-off-by: Yuval Lifshitz <ylifshit@redhat.com>

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by yuvalif** [comment]
jenkins test docs

**Comment by tchaikov** [comment]
jenkins render docs

**Comment by tchaikov** [comment]
please note, we use [Breathe](https://breathe.readthedocs.io/en/latest/) for documenting the C and C++ APIs, if we choose to generate the doxygen XML using CMake. who do you plan to integrate it into our sphinx build pipeline?

**Comment by yuvalif** [comment]
> please note, we use [Breathe](https://breathe.readthedocs.io/en/latest/) for documenting the C and C++ APIs, if we choose to generate the doxygen XML using CMake. who do you plan to integrate it into our sphinx build pipeline?

not sure what is the issue. calling `admin/build-doc` is building the librados C API documentation based on our doxygen notations without the Doxyfile.
is there another pipeline for building docs?

**Comment by tchaikov** [comment]
>  is building the librados C API documentation based on our doxygen notations without the Doxyfile.

this is not true. if you read the document i referenced in last comment, probably you would notice that Breathe does not read the doxygen notations directly. instead, it parses the XML file generated by doxygen, and translate it into the HTML using the sphinx helpers.

**Comment by yuvalif** [comment]
> > is building the librados C API documentation based on our doxygen notations without the Doxyfile.
> 
> this is not true. if you read the document i referenced in last comment, probably you would notice that Breathe does not read the doxygen notations directly. instead, it parses the XML file generated by doxygen, and translate it into the HTML using the sphinx helpers.

but I see the librados API documented using `admin/build-doc` regardless of the existence of the Doxyfile.
when I call:
```
$ rm -rf ../build-doc
$ ../admin/build-doc
```
I can see the generated XMLs under: `../build-doc/breathe/doxygen/Ceph/xml/`
as well as the actual librados C API documentation

**Comment by tchaikov** [comment]
@yuvalif sorry, i was wrong. i misinterpreted breathe's document of https://breathe.readthedocs.io/en/latest/directives.html#confval-breathe_doxygen_config_options, and thought that Breathe used the *merged* output of `Doxyfile` and specified `breathe_doxygen_config_options` for generating the settings for doxygen when generating XML. but it seems that Breathe does not rely on it. see https://github.com/michaeljones/breathe/blob/afd4475e596b1b2f22d14cb84e1da0a15b0ddc89/breathe/process.py#L74

**Review by tchaikov — APPROVED** [review]

**Pull request merged**
