### PR TITLE
hammer: librbd: ceph 10.2.2 rbd status on image format 2 returns "(2) No such file or directory"

### PR DESCRIPTION
**Pull request by Vicente-Cheng**
http://tracker.ceph.com/issues/16952

### CODE REVIEW

**Comment by smithfarm** [comment]
@Vicente-Cheng Could you rebase this please?

**Comment by Vicente-Cheng** [comment]
@smithfarm 
hi Nathan, sorry for late replay.
Already rebase it! : )

**Comment by smithfarm** [comment]
@dillaman This PR was included in this rbd suite: http://tracker.ceph.com/issues/17151#note-12

That run has two issues: the first (OSD suicide timeout) is not reproducible and looks like environmental noise. Then there is a reproducible qemu-iotests failure which matches http://tracker.ceph.com/issues/10773 

Can you take a look? If you think the qemu-iotests failure is unrelated, I guess this PR could be merged?

**Comment by dillaman** [comment]
@smithfarm lgtm

**Pull request merged**
