### PR TITLE
Validate default replicated ruleset config value

### PR DESCRIPTION
**Pull request by idryomov**

### CODE REVIEW

**Comment by idryomov** [comment]
Hmm, a check in CrushWrapper doesn't sit well with simple osdmaps.  I'll redo this.

**Comment by dachary** [comment]
@idryomov Maybe @jcsp would be a better judge of what should be done in this area. I don't feel strongly about how the default ruleset is managed: the current behavior did not bother me, not even once ;-)

**Comment by idryomov** [comment]
@jcsp Both your comments make sense, I wasn't sure about the build_simple() hack myself.

**Comment by idryomov** [comment]
While rethinking the hack in build_simple() I realised that this was not just a "ceph osd pool create" problem, but also a problem with initial osdmaps - we need to respect the conf when creating the initial simple ruleset to make sure rbd pool has a valid ruleset.

**Pull request merged**
