### PR TITLE
common/io_exerciser: Add version argument to callbacks in ceph_radios_io_sequence

### PR DESCRIPTION
**Pull request by JonBailey1993**
common/io_exerciser: Add version argument to callbacks in ceph_radios_io_sequence

Add new version that was missing from ceph_test_rados_io_sequence async_operate callbacks due to interface changes.
Fixes issue breaking compilation introduced in #59857, commit 54e0865cd6ed5242b6cc02a8b942c2527c77f244 (src/test/osd: create ceph_test_rados_io_sequence testing tool)

Signed-off-by: Jon Bailey <jonathan.bailey1@ibm.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [x] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Comment by JonBailey1993** [comment]
Looks like a PR for this change already exists here: https://github.com/ceph/ceph/pull/60180 created by @zhscn so potentially better to merge that as it came first

**Review by athanatos — APPROVED** [review]

**Comment by JonBailey1993** [comment]
ceph API tests:
Hit timeout starting OSDs

`  File "/home/jenkins-build/build/workspace/ceph-api/build/../qa/tasks/vstart_runner.py", line 1610, in <module>
    exec_test()
  File "/home/jenkins-build/build/workspace/ceph-api/build/../qa/tasks/vstart_runner.py", line 1453, in exec_test
    LocalCephCluster(LocalContext()).mon_manager.wait_for_all_osds_up(timeout=30)
  File "/home/jenkins-build/build/workspace/ceph-api/qa/tasks/ceph_manager.py", line 2902, in wait_for_all_osds_up
    assert time.time() - start < timeout, \
AssertionError: timeout expired in wait_for_all_osds_up`

This change does not touch OSD code, will retrigger.

ceps windows tests:
Failed to find storage pool on machine ([172.21.5.38+adami08](https://jenkins.ceph.com/computer/172.21.5.38+adami08)) when running virsh command: 

`+ sudo virsh pool-refresh default
error: failed to get pool 'default'
error: Storage pool not found: no storage pool with matching name 'default'`

Machine possibly not fully set back up completely after infrastructure work. Will retrigger.

make check (arm64):

Failed to load libraries. Both calling code and called libraries unchanged by this PR. Will retrigger.

`Failed to load class: cas (/home/jenkins-build/build/workspace/ceph-pull-requests-arm64/build/lib/libcls_cas.so): /home/jenkins-build/build/workspace/ceph-pull-requests-arm64/build/lib/libcls_cas.so: undefined symbol: _Z26cls_get_manifest_ref_countPvNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
Failed to load class: cmpomap (/home/jenkins-build/build/workspace/ceph-pull-requests-arm64/build/lib/libcls_cmpomap.so): /home/jenkins-build/build/workspace/ceph-pull-requests-arm64/build/lib/libcls_cmpomap.so: undefined symbol: _Z28cls_cxx_map_get_vals_by_keysPvRKSt3setINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESt4lessIS6_ESaIS6_EEPSt3mapIS6_N4ceph6buffer7v15_2_04listES8_SaISt4pairIKS6_SH_EEE
Failed to load class: fifo (/home/jenkins-build/build/workspace/ceph-pull-requests-arm64/build/lib/libcls_fifo.so): /home/jenkins-build/build/workspace/ceph-pull-requests-arm64/build/lib/libcls_fifo.so: undefined symbol: _Z20cls_gen_random_bytesPci
Failed to load class: log (/home/jenkins-build/build/workspace/ceph-pull-requests-arm64/build/lib/libcls_log.so): /home/jenkins-build/build/workspace/ceph-pull-requests-arm64/build/lib/libcls_log.so: undefined symbol: _Z24cls_cxx_map_write_headerPvPN4ceph6buffer7v15_2_04listE
Failed to load class: rgw (/home/jenkins-build/build/workspace/ceph-pull-requests-arm64/build/lib/libcls_rgw.so): /home/jenkins-build/build/workspace/ceph-pull-requests-arm64/build/lib/libcls_rgw.so: undefined symbol: _Z19cls_get_object_infoPv
Failed to load class: user (/home/jenkins-build/build/workspace/ceph-pull-requests-arm64/build/lib/libcls_user.so): /home/jenkins-build/build/workspace/ceph-pull-requests-arm64/build/lib/libcls_user.so: undefined symbol: _Z24cls_cxx_map_write_headerPvPN4ceph6buffer7v15_2_04listE`

**Comment by JonBailey1993** [comment]
jenkins test api
jenkins test windows
jenkins test make check arm64

**Comment by JonBailey1993** [comment]
jenkins test make check arm64

**Comment by JonBailey1993** [comment]
jenkins test windows

**Comment by JonBailey1993** [comment]
jenkins test api

**Pull request merged**
