### PR TITLE
print more information when run ceph-osd cmd with 'check options'

### PR DESCRIPTION
**Pull request by mychoxin**
print more information when run ceph-osd cmd with 'chech options'
Signed-off-by: mychoxin <mychoxin@gmail.com>

### CODE REVIEW

**Comment by mychoxin** [comment]
@liupan1111

**Comment by gregsfortytwo** [comment]
jenkins retest this please

**Comment by gregsfortytwo** [comment]
Presumably it's something unimportant but I want to make sure this change in output doesn't bust any of our cram tests.

**Comment by mychoxin** [comment]
@gregsfortytwo I will look up whether somewhere tests '--check-XXX' option

**Pull request merged**
