### PR TITLE
mds: don't assert empty io context list when shutting down

### PR DESCRIPTION
**Pull request by ukernel**
Fixes: https://tracker.ceph.com/issues/44680
Signed-off-by: "Yan, Zheng" <zyan@redhat.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by gregsfortytwo** [comment]
Hmm the first commit this reverts was fixing a bug which I think this brings back?

Seems like we’d really rather pass back an ESHUTDOWN to the Contexts and have them handle it as appropriate.

**Comment by ukernel** [comment]
The first reverted commit and the third commit fix the same bug by different ways.  I think it's not too bad to let context leak when shutting down mds

**Comment by gregsfortytwo** [comment]
jenkins test make check

**Comment by gregsfortytwo** [comment]
So for this PR we're deliberately leaking the memory on shutdown, so as to avoid calling the Context destructors, is that correct?

I take it we're still not valgrind clean and this is fine as a quick fix but in the long run I'd like us to actually handle the shutdown nicely.

**Comment by gregsfortytwo** [comment]
http://pulpito.front.sepia.ceph.com/gregf-2020-04-01_18:45:43-fs-wip-greg-testing-41-distro-basic-smithi/

**Comment by ukernel** [comment]
> So for this PR we're deliberately leaking the memory on shutdown, so as to avoid calling the Context destructors, is that correct?
> 
> I take it we're still not valgrind clean and this is fine as a quick fix but in the long run I'd like us to actually handle the shutdown nicely.

right

**Comment by gregsfortytwo** [comment]
http://pulpito.front.sepia.ceph.com:80/gregf-2020-04-02_05:22:31-fs-wip-greg-testing-41-3-distro-basic-smithi/
Try, try again — Zheng attributes these failures to https://tracker.ceph.com/issues/44904 so I'll fix that up...

**Pull request merged**
