### PR TITLE
mailmap: David Zhang affiliation

### PR DESCRIPTION
**Pull request by dachary**
And name normalization

Reviewed-by: David Zhang <zhangz@yahoo-inc.com>
Signed-off-by: Loic Dachary <ldachary@redhat.com>

### CODE REVIEW

**Comment by dachary** [comment]
@davidzhang84 does that look right to you ?

**Comment by davidzhang84** [comment]
@dachary  How about changing my name to "Zhi (David) Zhang"?

**Comment by dachary** [comment]
@davidzhang84 like this ? https://github.com/dachary/ceph/commit/2c7006f8b4f67bce3cfd7fd7b6fd88ef359ddf4a

**Comment by davidzhang84** [comment]
@dachary Yes, looks good. Thanks a lot.

**Pull request merged**
