### PR TITLE
mon: some fixes for kv backend failures

### PR DESCRIPTION
**Pull request by liewegas**

### CODE REVIEW

**Comment by liewegas** [comment]
@jecluis @tchaikov mind taking a look?

**Comment by jecluis** [comment]
This looks okay, but I'm curious: what triggered this pull request? Aside from the fs getting full or going read-only, I don't see a good reason for this to happen.

**Comment by liewegas** [comment]
A user's mon fs went read-only and the mon continued calling elections, 
DOSing the cluster.

**Comment by tchaikov** [comment]
lgtm and might need to connect this with http://tracker.ceph.com/issues/13089 . BTW, shall we backport this fix to hammer?

**Comment by tchaikov** [comment]
added `backport=hammer` in the tracker

**Comment by liewegas** [comment]
added fixes: line and needs-qa tag

**Comment by jecluis** [comment]
LGTM

**Comment by smithfarm** [comment]
@dachary Bot failure is false negative?

**Comment by dachary** [comment]
@smithfarm yes, it's a manifestation of http://tracker.ceph.com/issues/13176

**Pull request merged**
