### PR TITLE
rgw: add quota enforcement to CopyObj

### PR DESCRIPTION
**Pull request by cbodley**
Fixes: https://tracker.ceph.com/issues/45382

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by cbodley** [comment]
jenkins test make check

**Comment by ofriedma** [comment]
http://pulpito.ceph.com/ofriedma-2020-05-17_14:47:45-rgw-quota-enfor-i01-distro-basic-smithi/

Most of the tests are failing because of inactive pgs
Some because of:

Command failed on smithi190 with status 1: 'cd /home/ubuntu/cephtest/tempest && /home/ubuntu/cephtest/tox-venv/bin/tox -e venv --notest'
--
Is the second thing is fine?

**Comment by dang** [comment]
I'm seeing these too.  It's because of a broken dependency.

**Comment by ivancich** [comment]
QA run:

- http://pulpito.ceph.com/ivancich-2020-06-06_14:32:27-rgw-wip-eric-testing-1-distro-basic-smithi/
- http://pulpito.ceph.com/ivancich-2020-06-06_14:32:53-rgw-wip-eric-testing-1-distro-basic-smithi/

**Pull request merged**
