### PR TITLE
os/bluestore: fix invalid omap name conversion when upgrading to per-pg.

### PR DESCRIPTION
**Pull request by ifed01**
Fixes: https://tracker.ceph.com/issues/53062
Signed-off-by: Igor Fedotov <igor.fedotov@croit.io>

## Checklist
- [x] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by tmolitor-stud-tu** [comment]
@ifed01 is there a way to recover my crashing osds without this pull request (e.g. vanilla 16.2.6)? See my post on the ceph-users list here: https://lists.ceph.io/hyperkitty/list/ceph-users@ceph.io/thread/NM7UCWXMUDWJECCFW6B2LMMKOXCXSPN3/

**Comment by ifed01** [comment]
> @ifed01 is there a way to recover my crashing osds without this pull request (e.g. vanilla 16.2.6)? See my post on the ceph-users list here: https://lists.ceph.io/hyperkitty/list/ceph-users@ceph.io/thread/NM7UCWXMUDWJECCFW6B2LMMKOXCXSPN3/

@tmolitor-stud-tu - forget to mentions - this specific patch doesn't recover already corrupted data - it just avoids that for new repairs...

**Comment by neha-ojha** [comment]
@ifed01 can you please add a note about this bug in https://github.com/ceph/ceph/blob/master/PendingReleaseNotes?

**Comment by ifed01** [comment]
> @ifed01 can you please add a note about this bug in https://github.com/ceph/ceph/blob/master/PendingReleaseNotes?

@neha-ojha - will do

**Comment by neha-ojha** [comment]
No related failures in run and rerun
- https://pulpito.ceph.com/nojha-2021-10-29_23:22:38-rados-wip-ifed-fix-omap-upgrade-distro-basic-smithi/
- https://pulpito.ceph.com/nojha-2021-11-01_14:26:20-rados-wip-ifed-fix-omap-upgrade-distro-basic-smithi/

Failures tracked in

- https://tracker.ceph.com/issues/49888
- https://tracker.ceph.com/issues/51076
- https://tracker.ceph.com/issues/53123
- https://tracker.ceph.com/issues/52417

**Comment by neha-ojha** [comment]
> > @ifed01 can you please add a note about this bug in https://github.com/ceph/ceph/blob/master/PendingReleaseNotes?
> 
> @neha-ojha - will do

@ifed01 I will go ahead and merge this PR. Please open a separate PR for the release notes, and let's backport the fix and the release notes changes in a single pacific backport PR.

**Pull request merged**
