### PR TITLE
pacific: os/bluestore: incremental update mode for bluefs log

### PR DESCRIPTION
**Pull request by ifed01**
This includes backport for https://github.com/ceph/ceph/pull/42754 "os/bluestore/bluefs: Cleanup allocation consistency check code"
Signed-off-by: Igor Fedotov <igor.fedotov@croit.io>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by ljflores** [comment]
@ifed01 never mind

**Comment by ifed01** [comment]
> @ifed01 is this ready to be tested? If so, can you re-add the qa label?

Done.. In fact I was thinking that we can postpone this to the future pacific release as it's mostly needed for 4K bluefs alloc unit support. The latter will apparently miss the upcoming release hence no much need for incremental update more as well.

**Comment by ljflores** [comment]
@ifed01 good to know that it's not absolutely necessary. We still have time to put it through testing, so I'll go ahead and start that.

**Comment by ljflores** [comment]
https://pulpito.ceph.com/?branch=wip-yuri2-testing-2022-12-07-0821-pacific

Failures, unrelated:
    1. https://tracker.ceph.com/issues/57311
    2. https://tracker.ceph.com/issues/58140
    3. https://tracker.ceph.com/issues/58046
    4. https://tracker.ceph.com/issues/58097
    5. https://tracker.ceph.com/issues/54071
    6. https://tracker.ceph.com/issues/53501
    7. https://tracker.ceph.com/issues/56770
    8. https://tracker.ceph.com/issues/54992
    9. https://tracker.ceph.com/issues/58232 - new tracker created; unrelated to PRs in this batch
    10. https://tracker.ceph.com/issues/56028

Details:
    1. rook: ensure CRDs are installed first - Ceph - Orchestrator
    2. quay.ceph.io/ceph-ci/ceph: manifest unknown - Ceph - Orchestrator
    3. qa/workunits/rados/test_librados_build.sh: specify redirect in curl command - Ceph - RADOS
    4. qa/workunits/post-file.sh: kex_exchange_identification: read: Connection reset by peer - Infrastructure
    5. rados/cephadm/osds: Invalid command: missing required parameter hostname(<string>) - Ceph - Orchestrator
    6. Exception when running 'rook' task. - Ceph - Orchestrator
    7. crash: void OSDShard::register_and_wake_split_child(PG*): assert(p != pg_slots.end()) - Ceph - RADOS
    8. pacific: rados/dashboard: tasks/dashboard: cannot stat '/etc/containers/registries.conf': No such file or directory - Ceph - Mgr - Dashboard
    9. Could not get lock /var/lib/apt/lists/lock - open (11: Resource temporarily unavailable) - Infrastructure
    10. thrash_cache_writeback_proxy_none: FAILED ceph_assert(version == old_value.version) in src/test/osd/RadosModel.h - Ceph - RADOS

**Comment by YiteGu** [comment]
@ifed01 v16.2.13 is include this PR, I upgrade to 16.2.13 from 15.2.7, upgrade successful, but I want to back to 15.2.7 failure:
```
2023-07-20T03:35:48.080+0000 7f3ab061ff40  0 set uid:gid to 167:167 (ceph:ceph)
2023-07-20T03:35:48.080+0000 7f3ab061ff40  0 ceph version 15.2.7 (88e41c6c49beb18add4fdb6b4326ca466d931db8) octopus (stable), process ceph-osd, pid 149
2023-07-20T03:35:48.080+0000 7f3ab061ff40  0 pidfile_write: ignore empty --pid-file
2023-07-20T03:35:48.081+0000 7f3ab061ff40  1 bdev create path /var/lib/ceph/osd/ceph-0/block type kernel
2023-07-20T03:35:48.081+0000 7f3ab061ff40  1 bdev(0x56267cec6000 /var/lib/ceph/osd/ceph-0/block) open path /var/lib/ceph/osd/ceph-0/block
2023-07-20T03:35:48.081+0000 7f3ab061ff40  1 bdev(0x56267cec6000 /var/lib/ceph/osd/ceph-0/block) open size 4000783007744 (0x3a381400000, 3.6 TiB) block_size 4096 (4 KiB) non-rotational discard supported
2023-07-20T03:35:48.081+0000 7f3ab061ff40  1 bdev create path /var/lib/ceph/osd/ceph-0/block type kernel
2023-07-20T03:35:48.081+0000 7f3ab061ff40  1 bdev(0x56267cec6700 /var/lib/ceph/osd/ceph-0/block) open path /var/lib/ceph/osd/ceph-0/block
2023-07-20T03:35:48.082+0000 7f3ab061ff40  1 bdev(0x56267cec6700 /var/lib/ceph/osd/ceph-0/block) open size 4000783007744 (0x3a381400000, 3.6 TiB) block_size 4096 (4 KiB) non-rotational discard supported
2023-07-20T03:35:48.082+0000 7f3ab061ff40  1 bdev(0x56267cec6700 /var/lib/ceph/osd/ceph-0/block) close
2023-07-20T03:35:48.350+0000 7f3ab061ff40  1 bdev(0x56267cec6000 /var/lib/ceph/osd/ceph-0/block) close
2023-07-20T03:35:48.608+0000 7f3ab061ff40  1  objectstore numa_node 1
2023-07-20T03:35:48.608+0000 7f3ab061ff40  0 starting osd.0 osd_data /var/lib/ceph/osd/ceph-0 /var/lib/ceph/osd/ceph-0/journal
2023-07-20T03:35:48.609+0000 7f3ab061ff40 -1 Falling back to public interface
2023-07-20T03:35:48.617+0000 7f3ab061ff40  0 load: jerasure load: lrc load: isa
2023-07-20T03:35:48.617+0000 7f3ab061ff40  1 bdev create path /var/lib/ceph/osd/ceph-0/block type kernel
2023-07-20T03:35:48.617+0000 7f3ab061ff40  1 bdev(0x56267cec6000 /var/lib/ceph/osd/ceph-0/block) open path /var/lib/ceph/osd/ceph-0/block
2023-07-20T03:35:48.617+0000 7f3ab061ff40  1 bdev(0x56267cec6000 /var/lib/ceph/osd/ceph-0/block) open size 4000783007744 (0x3a381400000, 3.6 TiB) block_size 4096 (4 KiB) non-rotational discard supported
2023-07-20T03:35:48.617+0000 7f3ab061ff40  1 bdev(0x56267cec6000 /var/lib/ceph/osd/ceph-0/block) close
2023-07-20T03:35:48.889+0000 7f3ab061ff40  0 osd.0:0.OSDShard using op scheduler ClassedOpQueueScheduler(queue=WeightedPriorityQueue, cutoff=196)
2023-07-20T03:35:48.889+0000 7f3ab061ff40  0 osd.0:1.OSDShard using op scheduler ClassedOpQueueScheduler(queue=WeightedPriorityQueue, cutoff=196)
2023-07-20T03:35:48.889+0000 7f3ab061ff40  0 osd.0:2.OSDShard using op scheduler ClassedOpQueueScheduler(queue=WeightedPriorityQueue, cutoff=196)
2023-07-20T03:35:48.889+0000 7f3ab061ff40  0 osd.0:3.OSDShard using op scheduler ClassedOpQueueScheduler(queue=WeightedPriorityQueue, cutoff=196)
2023-07-20T03:35:48.889+0000 7f3ab061ff40  0 osd.0:4.OSDShard using op scheduler ClassedOpQueueScheduler(queue=WeightedPriorityQueue, cutoff=196)
2023-07-20T03:35:48.889+0000 7f3ab061ff40  0 osd.0:5.OSDShard using op scheduler ClassedOpQueueScheduler(queue=WeightedPriorityQueue, cutoff=196)
2023-07-20T03:35:48.889+0000 7f3ab061ff40  0 osd.0:6.OSDShard using op scheduler ClassedOpQueueScheduler(queue=WeightedPriorityQueue, cutoff=196)
2023-07-20T03:35:48.889+0000 7f3ab061ff40  0 osd.0:7.OSDShard using op scheduler ClassedOpQueueScheduler(queue=WeightedPriorityQueue, cutoff=196)
2023-07-20T03:35:48.889+0000 7f3ab061ff40  2 osd.0 0 init /var/lib/ceph/osd/ceph-0 (looks like ssd)
2023-07-20T03:35:48.889+0000 7f3ab061ff40  2 osd.0 0 journal /var/lib/ceph/osd/ceph-0/journal
2023-07-20T03:35:48.890+0000 7f3ab061ff40  1 bdev create path /var/lib/ceph/osd/ceph-0/block type kernel
2023-07-20T03:35:48.890+0000 7f3ab061ff40  1 bdev(0x56267cec6000 /var/lib/ceph/osd/ceph-0/block) open path /var/lib/ceph/osd/ceph-0/block
2023-07-20T03:35:48.890+0000 7f3ab061ff40  1 bdev(0x56267cec6000 /var/lib/ceph/osd/ceph-0/block) open size 4000783007744 (0x3a381400000, 3.6 TiB) block_size 4096 (4 KiB) non-rotational discard supported
2023-07-20T03:35:48.890+0000 7f3ab061ff40  1 bdev create path /var/lib/ceph/osd/ceph-0/block type kernel
2023-07-20T03:35:48.890+0000 7f3ab061ff40  1 bdev(0x56267cec6700 /var/lib/ceph/osd/ceph-0/block) open path /var/lib/ceph/osd/ceph-0/block
2023-07-20T03:35:48.890+0000 7f3ab061ff40  1 bdev(0x56267cec6700 /var/lib/ceph/osd/ceph-0/block) open size 4000783007744 (0x3a381400000, 3.6 TiB) block_size 4096 (4 KiB) non-rotational discard supported
2023-07-20T03:35:48.914+0000 7f3ab061ff40 -1 bluefs _replay 0x3c9000: stop: unrecognized op 12
2023-07-20T03:35:48.914+0000 7f3ab061ff40 -1 bluefs mount failed to replay log: (5) Input/output error
2023-07-20T03:35:48.914+0000 7f3ab061ff40 -1 bluestore(/var/lib/ceph/osd/ceph-0) _open_bluefs failed bluefs mount: (5) Input/output error
2023-07-20T03:35:48.914+0000 7f3ab061ff40  1 bdev(0x56267cec6000 /var/lib/ceph/osd/ceph-0/block) close
2023-07-20T03:35:49.159+0000 7f3ab061ff40 -1 osd.0 0 OSD:init: unable to mount object store
2023-07-20T03:35:49.159+0000 7f3ab061ff40 -1  ** ERROR: osd init failed: (5) Input/output error
```
this indicate we can not back to old version?

**Comment by ifed01** [comment]
> 
> this indicate we can not back to old version?

Right, you can't do that.

**Comment by YiteGu** [comment]
> > this indicate we can not back to old version?
> 
> Right, you can't do that.

thanks, I got it

**Pull request merged**
