### PR TITLE
Multisite fixes to be merged into main

### PR DESCRIPTION
**Pull request by soumyakoduri**
## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Review by cbodley — APPROVED** [review]
looks good!

the debug logging commit for radosgw-admin seems a bit excessive though. do you think that's still necessary?

**Comment by soumyakoduri** [comment]
> looks good!
> 
> the debug logging commit for radosgw-admin seems a bit excessive though. do you think that's still necessary?

For "behind shards" issue, reading local & remote markers helped me to grep through the logs and analyse few races (wrt marker updates) among the sync servers. The logs are set to level '30' so that it doesn't flood regular dev environment. That said I am okay to keep it only in the downstream builds.

**Comment by cbodley** [comment]
> For "behind shards" issue, reading local & remote markers helped me to grep through the logs and analyse few races (wrt marker updates) among the sync servers

all of that information should already be available from other commands like 'datalog status' on the source zone and 'data sync status' on the destination

**Comment by soumyakoduri** [comment]
> > For "behind shards" issue, reading local & remote markers helped me to grep through the logs and analyse few races (wrt marker updates) among the sync servers
> 
> all of that information should already be available from other commands like 'datalog status' on the source zone and 'data sync status' on the destination

ok.. thanks!

**Comment by soumyakoduri** [comment]
Haven't seen any issues with simple sync tests. Merging into multisite branch.

**Pull request merged**
