### PR TITLE
mgr/dashboard: changes to first layout

### PR DESCRIPTION
**Pull request by Pegonzal**
PR to address improvements to the first stage of the dashboard revamp.

CHANGES:
 - Renamed dashboardcomponents

 - Removed unnecesary styling

 - Added unit tests

Signed-off-by: Pedro Gonzalez Gomez <pegonzal@redhat.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [x] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [x] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by Pegonzal** [comment]
This PR addresses @epuertat 's comments from our last work.

**Comment by avanthakkar** [comment]
jenkins test dashboard

**Comment by avanthakkar** [comment]
jenkins test dashboard cephadm

**Comment by Pegonzal** [comment]
jenkins test api

**Comment by Pegonzal** [comment]
jenkins test dashboard cephadm

**Review by bryanmontalvan — APPROVED** [review]
LGTM,

Everything is looking good to me, not too versed on the tests themselves but I bet @epuertat has more to say on that :+1:

**Review by pereman2 — APPROVED** [review]
```
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✖  orchestrator/workflow/06-cluster-ch      01:41        9        8        1        -        - │
  │    eck.e2e-spec.ts                                                                             │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  orchestrator/workflow/07-osds.e2e-s      00:08        1        1        -        -        - │
  │    pec.ts                                                                                      │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  orchestrator/workflow/08-hosts.e2e-      02:12        4        4        -        -        - │
  │    spec.ts                                                                                     │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✖  orchestrator/workflow/09-services.e      04:51       10        9        1        -        - │
  │    2e-spec.ts                                                                                  │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤

```
Unrelated failures.

**Comment by Pegonzal** [comment]
I'll merge it to keep working over this changes

**Pull request merged**
