### PR TITLE
split python-ceph into python-{rados,rbd,cephfs}

### PR DESCRIPTION
**Pull request by liewegas**
debian and rpm

### CODE REVIEW

**Comment by gregsfortytwo** [comment]
Make sure this gets run through a couple teuthology suite tests before merging so we know it's handling the obsoletes bits correctly? ;)

**Comment by ktdreyer** [comment]
For the RPM change, you may want to cherry-pick https://github.com/ceph/ceph/commit/027a9f1718c7702d6768c16694436eed6957dd31 instead - there were some typos in the original commit's log

**Comment by ktdreyer** [comment]
The Redmine issue for this change is http://tracker.ceph.com/issues/10897

**Comment by ktdreyer** [comment]
LGTM. Echoing @gregsfortytwo above, we need to run through a Teuthology test or two here to verify that we won't break that.

**Comment by liewegas** [comment]
2015-02-24 18:24:19,379.379 INFO:teuthology.orchestra.run.burnupi34.stderr:dpkg: error processing archive /var/cache/apt/archives/ceph_0.92-1234-g381960a-1trusty_amd64.deb (--unpack):
2015-02-24 18:24:19,379.379 INFO:teuthology.orchestra.run.burnupi34.stderr: trying to overwrite '/usr/lib/python2.7/dist-packages/ceph_argparse.py', which is also in package python-ceph 0.87.1-1trusty

**Comment by liewegas** [comment]
passes an upgrade test now

**Comment by ktdreyer** [comment]
Looks good, I'm merging this

**Pull request merged**
