### PR TITLE
LTTng-UST tracing should be dynamically enabled

### PR DESCRIPTION
**Pull request by dillaman**
http://tracker.ceph.com/issues/13541

### CODE REVIEW

**Comment by dillaman** [comment]
@ktdreyer Can you double-check my backport changes to your commit @ 62b40f02a6bf6ba691bf0712274cff8589627233

**Comment by dachary** [comment]
@ktdreyer it should be -2

**Comment by dillaman** [comment]
@dachary @ktdreyer updated to -2

**Comment by ktdreyer** [comment]
Thanks, LGTM

**Comment by dachary** [comment]
DNM until #5790 is merged because it conflicts with it

**Comment by dachary** [comment]
@dillaman could you please rebase & repush & remove the DNM prefix when you do ?

**Comment by dillaman** [comment]
rebase wiped out all the commit somehow. fixed and reopening.

**Comment by dachary** [comment]
passed (all but one) rbd suite http://tracker.ceph.com/issues/13356#note-35

**Comment by dillaman** [comment]
Fix in-progress for broken precise and wheezy builds.

**Pull request merged**
