### PR TITLE
Doc: add the `reweight` step before to mark out an OSD and remove it.

### PR DESCRIPTION
**Pull request by flaf**
Signed-off-by: François Lafont <francois.lafont@ac-versailles.fr>

### CODE REVIEW

**Comment by flaf** [comment]
I had some cases where, without the `reweight` step, the cluster was stuck to a "non OK" state, and with the `reweight` step there was no problem. Some people on IRC confirm to me that the `reweight` step was a good practice.

Regards.

**Comment by jcsp** [comment]
This change might add some confusion in its current form, because "ceph osd out" is equivalent to setting its osd map weight (aka ceph osd reweight) to zero, while this is saying we also need to do "ceph osd crush reweight" (which sets its *other* weight to zero).  There is a terminology problem here that we have two subtly different "weights" for each OSD.

So:
 * Setting either weight to zero should be enough, so is there a bug here that this is trying to work around?
 * If both steps are truly useful, is there a sensible way we can explain both weights and why it's necessary to set both?

**Comment by flaf** [comment]
Hi,
Thanks for your answer. Currently I am not qualified enough to decide between your 2 alternatives. I had just noticed with my cluster (Firefly) that without the `ceph osd crush reweight` my cluster was **systematically** stuck, and with `ceph osd crush reweight` it wasn't. I have explained my experience here http://www.mail-archive.com/ceph-users%40lists.ceph.com/msg17784.html

**Comment by jcsp** [comment]
Ah, so I think that greg is saying (on the list thread) that we should do the "crush reweight" part in order to update the parent bucket's weight, to avoid some CRUSH corner cases.  @gregsfortytwo so do you reckon we should make this a standard part of the OSD removal process?

**Comment by dachary** [comment]
@flaf do you have time to update your contribution to take into account jcsp suggestions ? It was nice seeing you for real at the OpenStack meetup ;-)

**Comment by flaf** [comment]
Hi @dachary,
No problem but I'm not sure of the final commands. Finally, should I keep the `ceph osd crush reweight osd.{osd-num} 0` command and just remove the `ceph osd out {osd-num}` command?

PS: It was nice for me and my colleague too to discuss together. ;)

**Comment by dachary** [comment]
@flaf would it make sense to explain the situation you had and how you fixed it in the troubleshooting section ? For most people what the doc suggests seems to work fine. But for people who face a corner case identical to yours, it would be very useful to have a solution. Which section of http://ceph.com/docs/master/rados/troubleshooting/ seems the most appropriate ?

**Comment by flaf** [comment]
According to @gregsfortytwo in my thread in the ML about this problem, the `ceph osd crush reweight osd.{osd-num} 0` command could avoid some CRUSH corner cases (see [here](http://www.mail-archive.com/ceph-users%40lists.ceph.com/msg18023.html)) typically in a "small" cluster with few hosts. So imho, it make sense to put something directly in the "add-or-rm-osds" section.

Eventually just **add** a remark after the `ceph osd out {osd-num}` command (instead of **change** the section like in my current commit)?

I'm not a ceph expert just a user fallen in a corner cases ;), so I have no certainties, if you think it's really better to put an item in the "troubleshooting" section, no problem to do that.

**Comment by dachary** [comment]
A **note** about that would be a good idea, indeed. There are examples of such notes in the documentation already.

**Comment by flaf** [comment]
Hello,

I have push a new version of the pull request with just a note. Tell me if something is something is wrong. :)

**Comment by dachary** [comment]
@flaf could you please squash the commits for clarity ?

**Comment by dachary** [comment]
@johnwilkins would you be so kind as to proofread this commit ? My english is not so good :-)

**Comment by flaf** [comment]
Sorry @dachary. Here the final modification: https://github.com/flaf/ceph/commit/224d70ef604583de94eb43760fec99bf193d5ac1

For the english syntax, my wife who is english teacher, has checked (because my personal english is bad ;)).

**Comment by dachary** [comment]
@flaf ack, please ignore the bot, I broke it but it should be good now.

**Comment by dachary** [comment]
could you **git push --force** your later commit so that it replaces the current ones ?

**Comment by flaf** [comment]
Sorry, I close this PR and come back with a new and clean PR.
Bye.

**Pull request closed without merging**
