### PR TITLE
src/osd/PG.cc: 6455: FAILED assert(0 == "we got a bad state machine event")

### PR DESCRIPTION
**Pull request by dzafman**

### CODE REVIEW

**Comment by dzafman** [comment]
I ran a failing test run 20 times it passed every time.  Not sure how hard it was to hit this:

http://pulpito.ceph.com/dzafman-2018-03-16_20:00:06-rados-wip-zafman-testing2-distro-basic-smithi/

**Comment by dzafman** [comment]
Should  we run a subset of rados/thrash suite?

**Comment by xiexingguo** [comment]
> I ran a failing test run 20 times it passed every time. Not sure how hard it was to hit this

@dzafman  It might not be rare at it is thought to be. I've hit the same issue a couple of weeks ago and posted a cure at https://github.com/ceph/ceph/pull/20837. It is actual a replica-backfill-revoke vs primary-backfill-finish race.  Well, I'd confess this is a better fix:-)

**Comment by neha-ojha** [comment]
@dzafman It appeared quite frequently for me when I ran rados runs with --subset 3/500. But yes, it was difficult to reproduce in a single test.

**Comment by dzafman** [comment]
http://qa-proxy.ceph.com/teuthology/dzafman-2018-03-21_09:57:19-rados:thrash-wip-zafman-testing2-distro-basic-smithi/

2312022 DEAD Infrastructure
2312125 FAIL scrub stat mismatch
2312148 RUNNING

**Pull request merged**
