### PR TITLE
ceph.spec.in: move BuildRequires out of subpackages

### PR DESCRIPTION
**Pull request by smithfarm**
Since the main package and all the subpackages are built in the
same environment, concentrate all the BuildRequires in the main
package.

Signed-off-by: Nathan Cutler <ncutler@suse.com>

### CODE REVIEW

**Comment by ktdreyer** [comment]
One change that I see here is that we will unconditionally BR: java-devel now, regardless of whether `%{with cephfs_java}` is set or not. I think one of the main points of keeping some BRs in the sub-packages is that they can be wrapped in these conditionals.

But the ones that aren't conditionalized can be moved, for sure.

**Comment by smithfarm** [comment]
Actually, that's not true. I put `BuildRequires: java-devel` in the proper conditional.

**Comment by ktdreyer** [comment]
> Actually, that's not true. I put BuildRequires: java-devel in the proper conditional.


Well that's what I get for not reading closely! 

looking closely

**Comment by smithfarm** [comment]
Ignoring false negative bot result ( http://tracker.ceph.com/issues/13176 strikes again ).

**Comment by smithfarm** [comment]
@ktdreyer Oh, grandma, what big eyes you have! (Seriously, marking this DNM because I want to add some small cleanups later tonight)

**Comment by smithfarm** [comment]
@ktdreyer What's left to do here?

**Comment by ktdreyer** [comment]
This looks good to me, and if it passes gitbuilder, let's merge it

**Comment by smithfarm** [comment]
oh, wait - wrong target!

**Comment by smithfarm** [comment]
Moved to #6191

**Pull request closed without merging**
