### PR TITLE
crimson/os: init PG with pg coll not meta coll

### PR DESCRIPTION
**Pull request by tchaikov**
## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by tchaikov** [comment]
@liu-chunmei

**Comment by tchaikov** [comment]
jenkins test make check

**Comment by tchaikov** [comment]
jenkins test make check

**Comment by tchaikov** [comment]
jenkins test crimson perf

**Comment by tchaikov** [comment]
jenkins test make check

**Comment by tchaikov** [comment]
jenkins test crimson perf

**Comment by liu-chunmei** [comment]
@tchaikov I test this PR, still has the same problem.

**Comment by tchaikov** [comment]
```
17:32:57 - DEBUG    - cbt      - Nodes : incerta08.front.sepia.ceph.com
17:32:57 - DEBUG    - cbt      - Nodes : incerta08.front.sepia.ceph.com
17:32:57 - DEBUG    - cbt      - Nodes : incerta08.front.sepia.ceph.com
17:32:57 - INFO     - cbt      - prefill/incerta08.front.sepia.ceph.com/0: bandwidth: (or (greater) (near 0.05)):: 11.672/11.4667  => accepted
17:32:57 - INFO     - cbt      - prefill/incerta08.front.sepia.ceph.com/0: iops_avg: (or (greater) (near 0.05)):: 2988.0/2935.0  => accepted
17:32:57 - WARNING  - cbt      - prefill/incerta08.front.sepia.ceph.com/0: iops_stddev: (or (less) (near 0.50)):: 146.487/85.2897  => rejected
17:32:57 - INFO     - cbt      - prefill/incerta08.front.sepia.ceph.com/0: latency_avg: (or (less) (near 0.05)):: 0.00533518/0.00542488  => accepted
17:32:57 - INFO     - cbt      - prefill/incerta08.front.sepia.ceph.com/1: bandwidth: (or (greater) (near 0.05)):: 11.5959/11.9225  => accepted
17:32:57 - INFO     - cbt      - prefill/incerta08.front.sepia.ceph.com/1: iops_avg: (or (greater) (near 0.05)):: 2968.0/3052.0  => accepted
17:32:57 - INFO     - cbt      - prefill/incerta08.front.sepia.ceph.com/1: iops_stddev: (or (less) (near 0.50)):: 164.871/125.607  => accepted
17:32:57 - INFO     - cbt      - prefill/incerta08.front.sepia.ceph.com/1: latency_avg: (or (less) (near 0.05)):: 0.00537492/0.00521303  => accepted
17:32:57 - INFO     - cbt      - rand/incerta08.front.sepia.ceph.com/0: bandwidth: (or (greater) (near 0.05)):: 52.6838/52.1218  => accepted
17:32:57 - INFO     - cbt      - rand/incerta08.front.sepia.ceph.com/0: iops_avg: (or (greater) (near 0.05)):: 13487.0/13343.0  => accepted
17:32:57 - INFO     - cbt      - rand/incerta08.front.sepia.ceph.com/0: iops_stddev: (or (less) (near 0.50)):: 159.365/144.762  => accepted
17:32:57 - INFO     - cbt      - rand/incerta08.front.sepia.ceph.com/0: latency_avg: (or (less) (near 0.05)):: 0.00117943/0.00119019  => accepted
17:32:57 - INFO     - cbt      - rand/incerta08.front.sepia.ceph.com/1: bandwidth: (or (greater) (near 0.05)):: 52.8784/52.3629  => accepted
17:32:57 - INFO     - cbt      - rand/incerta08.front.sepia.ceph.com/1: iops_avg: (or (greater) (near 0.05)):: 13536.0/13404.0  => accepted
17:32:57 - INFO     - cbt      - rand/incerta08.front.sepia.ceph.com/1: iops_stddev: (or (less) (near 0.50)):: 148.663/158.441  => accepted
17:32:57 - INFO     - cbt      - rand/incerta08.front.sepia.ceph.com/1: latency_avg: (or (less) (near 0.05)):: 0.0011747/0.00118568  => accepted
17:32:57 - WARNING  - cbt      - 1 tests failed out of 16
```

**Comment by tchaikov** [comment]
@rzarzynski and @athanatos could you take a look?

**Comment by tchaikov** [comment]
```
17:32:57 - INFO     - cbt      - prefill/incerta08.front.sepia.ceph.com/0: bandwidth: (or (greater) (near 0.05)):: 11.672/11.4667  => accepted
17:32:57 - INFO     - cbt      - prefill/incerta08.front.sepia.ceph.com/0: iops_avg: (or (greater) (near 0.05)):: 2988.0/2935.0  => accepted
17:32:57 - WARNING  - cbt      - prefill/incerta08.front.sepia.ceph.com/0: iops_stddev: (or (less) (near 0.50)):: 146.487/85.2897  => rejected
17:32:57 - INFO     - cbt      - prefill/incerta08.front.sepia.ceph.com/0: latency_avg: (or (less) (near 0.05)):: 0.00533518/0.00542488  => accepted
17:32:57 - INFO     - cbt      - prefill/incerta08.front.sepia.ceph.com/1: bandwidth: (or (greater) (near 0.05)):: 11.5959/11.9225  => accepted
17:32:57 - INFO     - cbt      - prefill/incerta08.front.sepia.ceph.com/1: iops_avg: (or (greater) (near 0.05)):: 2968.0/3052.0  => accepted
17:32:57 - INFO     - cbt      - prefill/incerta08.front.sepia.ceph.com/1: iops_stddev: (or (less) (near 0.50)):: 164.871/125.607  => accepted
17:32:57 - INFO     - cbt      - prefill/incerta08.front.sepia.ceph.com/1: latency_avg: (or (less) (near 0.05)):: 0.00537492/0.00521303  => accepted
17:32:57 - INFO     - cbt      - rand/incerta08.front.sepia.ceph.com/0: bandwidth: (or (greater) (near 0.05)):: 52.6838/52.1218  => accepted
17:32:57 - INFO     - cbt      - rand/incerta08.front.sepia.ceph.com/0: iops_avg: (or (greater) (near 0.05)):: 13487.0/13343.0  => accepted
17:32:57 - INFO     - cbt      - rand/incerta08.front.sepia.ceph.com/0: iops_stddev: (or (less) (near 0.50)):: 159.365/144.762  => accepted
17:32:57 - INFO     - cbt      - rand/incerta08.front.sepia.ceph.com/0: latency_avg: (or (less) (near 0.05)):: 0.00117943/0.00119019  => accepted
17:32:57 - INFO     - cbt      - rand/incerta08.front.sepia.ceph.com/1: bandwidth: (or (greater) (near 0.05)):: 52.8784/52.3629  => accepted
17:32:57 - INFO     - cbt      - rand/incerta08.front.sepia.ceph.com/1: iops_avg: (or (greater) (near 0.05)):: 13536.0/13404.0  => accepted
17:32:57 - INFO     - cbt      - rand/incerta08.front.sepia.ceph.com/1: iops_stddev: (or (less) (near 0.50)):: 148.663/158.441  => accepted
17:32:57 - INFO     - cbt      - rand/incerta08.front.sepia.ceph.com/1: latency_avg: (or (less) (near 0.05)):: 0.0011747/0.00118568  => accepted
17:32:57 - WARNING  - cbt      - 1 tests failed out of 16
```

**Pull request merged**
