### PR TITLE
crimson/osd/pg_recovery: backoff if the recovery/backfill is deferred

### PR DESCRIPTION
**Pull request by xxhdx1985126**
Fixes: https://tracker.ceph.com/issues/65399
Signed-off-by: Xuehan Xu <xuxuehan@qianxin.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Comment by Matan-B** [comment]
How is this scenario possible?
Were you able to reproduce it locally?

**Comment by Matan-B** [comment]
> The following op sequence should lead to this scenario:
> 
> 1. PG `P`'s recovery is deferred and its pg state turns to PG_STATE_RECOVERY_WAIT;
> 2. `P`'s last recovery op triggerred by the last round of `start_recovery_ops` is finished;
> 3. the next round of `start_recovery_ops` starts and hit the assert `assert(pg->is_recovering())`

Why  "the next round of `start_recovery_ops`" started again? Is that expected?

**Review by Matan-B — APPROVED** [review]
LGTM, probably worth another pair of eyes.

**Comment by xxhdx1985126** [comment]
@Matan-B The previous version of this PR can lead to infinite recursive call of "Operation::with_throttle_while", I've just added a commit to avoid this, please take a look again, thanks:-)

**Comment by Matan-B** [comment]
> @Matan-B The previous version of this PR can lead to infinite recursive call of "Operation::with_throttle_while", I've just added a commit to avoid this, please take a look again, thanks:-)

Only the first commit is tested and is ready to merge. I have separated the second commit into #57014.
We can:
1) Drop the second commit and merge this PR (only 61c2768672dc929778b79fd9ff8ec4970e89619e)
2) Close #57014 and retest this PR with both commits (after reviewing again).

@xxhdx1985126, Let me know what do you prefer. I'm leaning toward the former.

**Comment by xxhdx1985126** [comment]
> > @Matan-B The previous version of this PR can lead to infinite recursive call of "Operation::with_throttle_while", I've just added a commit to avoid this, please take a look again, thanks:-)
> 
> Only the first commit is tested and is ready to merge. I have separated the second commit into #57014. We can:
> 
> 1. Drop the second commit and merge this PR (only [61c2768](https://github.com/ceph/ceph/commit/61c2768672dc929778b79fd9ff8ec4970e89619e))
> 2. Close [crimson/osd/osd_operation: fix with_throttle_while #57014](https://github.com/ceph/ceph/pull/57014) and retest this PR with both commits (after reviewing again).
> 
> @xxhdx1985126, Let me know what do you prefer. I'm leaning toward the former.

I think we it might be better to merge the two commits together, because the infinite-recursion regression will be brought into the main branch, what do you think?

**Comment by Matan-B** [comment]
jenkins test makecheck

**Comment by Matan-B** [comment]
jenkins test api

**Comment by Matan-B** [comment]
jenkins test make check

**Comment by Matan-B** [comment]
https://shaman.ceph.com/builds/ceph/wip-matanb-crimson-testing-april-22

**Review by athanatos — APPROVED** [review]

**Pull request merged**
