### PR TITLE
rgw: fix AWS SigV4 request failure when uploading empty file

### PR DESCRIPTION
**Pull request by microyahoo**
Fixes: https://tracker.ceph.com/issues/67875
           https://github.com/ceph/ceph/pull/53266

Signed-off-by: Liang Zheng <zhengliang0901@gmail.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).
Signed-off-by: Liang Zheng <zhengliang0901@gmail.com>

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [x] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [x] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Comment by microyahoo** [comment]
https://github.com/ceph/ceph/pull/54856

**Comment by cbodley** [comment]
thanks @microyahoo. i saw your comment in https://github.com/ceph/ceph/pull/53266#issuecomment-2325986330:

> seems this issue has been fixed by https://github.com/ceph/ceph/pull/54856

do we still need your fix?

**Comment by microyahoo** [comment]
> thanks @microyahoo. i saw your comment in [#53266 (comment)](https://github.com/ceph/ceph/pull/53266#issuecomment-2325986330):
> 
> > seems this issue has been fixed by #54856
> 
> do we still need your fix?

hi @cbodley, this PR has been tested and works well on versions v16.2.15 and v18.2.4, maybe not needed again in main branch. Any comments @mattbenjamin

**Comment by cbodley** [comment]
> hi @cbodley, this PR has been tested and works well on versions v16.2.15 and v18.2.4, maybe not needed again in main branch.

thanks @microyahoo. this was already fixed on main with https://github.com/ceph/ceph/pull/54856 for https://tracker.ceph.com/issues/63153. reef will just need to wait for 18.2.5 which has the backported fix (https://tracker.ceph.com/issues/64465)

**Pull request closed without merging**
