### PR TITLE
rgw/admin: fix some return values and indents

### PR DESCRIPTION
**Pull request by Yan-waller**
Maybe we should unify the return values to positive number.

Signed-off-by: Yan Jun <yan.jun8@zte.com.cn>

### CODE REVIEW

**Comment by oritwas** [comment]
The code looks fine, my main issue is that changing the error code may break some of the tests (like rgw teuthology suite and the multisite unit tests). can you test those with your changes?

**Comment by Yan-waller** [comment]
thanks for review, I‘ll try to test it. @oritwas

**Comment by Yan-waller** [comment]
retest this please

**Comment by Yan-waller** [comment]
I have finished the `rgw teuthology suite` testing in local, there is no error about it. @oritwas

**Comment by Yan-waller** [comment]
@oritwas PING

**Pull request merged**
