### PR TITLE
hammer: tests: bufferlist: do not expect !is_page_aligned() after unaligned rebuild

### PR DESCRIPTION
**Pull request by Yan-waller**
http://tracker.ceph.com/issues/15305

### CODE REVIEW

**Comment by dachary** [comment]
please test this

**Comment by alfredodeza** [comment]
test this please

**Comment by dachary** [comment]
@tchaikov  does this backport look good to merge ? It passed the hammer upgrade suite ( http://tracker.ceph.com/issues/14692#note-52 ) and the rados suite http://tracker.ceph.com/issues/14692#note-51).

**Comment by tchaikov** [comment]
@dachary lgtm

**Pull request merged**
