### PR TITLE
LTTng-UST tracing should be dynamically enabled

### PR DESCRIPTION
**Pull request by dillaman**

### CODE REVIEW

**Comment by jdurgin** [comment]
lgtm, push to ceph.git for gitbuilder verification as wip-13274-infernalis

**Comment by jdurgin** [comment]
package gitbuilders look fine, may need to fix up cmake for this though.

scheduled an rbd subset: http://pulpito.ceph.com/joshd-2015-10-13_14:52:30-rbd-wip-13274-infernalis---basic-multi/

**Comment by dillaman** [comment]
Tracking cmake issue via PR #6265 as it was introduced outside this PR.  Waiting for Fedora 22 rebuild to verify that RPM packaging works.

**Comment by liewegas** [comment]
Checking for unpackaged file(s): /usr/lib/rpm/check-files /srv/autobuild-ceph/gitbuilder.git/build/rpmbuild/BUILDROOT/ceph-9.0.3-2121.gfe258b0.fc22.x86_64
error: Installed (but unpackaged) file(s) found:
/usr/lib64/libos_tp.so
/usr/lib64/libosd_tp.so
/usr/lib64/librados_tp.so
/usr/lib64/librbd_tp.so
RPM build errors:
Installed (but unpackaged) file(s) found:
/usr/lib64/libos_tp.so
/usr/lib64/libosd_tp.so
/usr/lib64/librados_tp.so
/usr/lib64/librbd_tp.so

on fedora builder

**Comment by dillaman** [comment]
... and now passing Fedora 22 RPM gitbuilder

**Comment by jdurgin** [comment]
got odd failures to set crush tunables in both runs:

http://pulpito.ceph.com/joshd-2015-10-13_14:52:30-rbd-wip-13274-infernalis---basic-multi/
http://pulpito.ceph.com/joshd-2015-10-14_16:25:11-rbd-wip-13274-infernalis---basic-multi/

not sure why, it looks like it should be successful from the monitor logs, and don't see how it could be related to these patches.

**Comment by dillaman** [comment]
Return code 139 implies that the 'ceph' Python program hit a segfault.

**Comment by liewegas** [comment]
CephContext::~CephContext()
{
  join_service_thread();

  for (map<string, AssociatedSingletonObject*>::iterator it = _associated_objs.begin();
       it != _associated_objs.end(); ++it)
    delete it->second;

it's on the delete line

here's the backtrace:

<pre>(gdb) bt
#0  0x00007fa17c000bf0 in ?? ()
#1  0x00007fa18353cdf7 in CephContext::~CephContext (this=0x7fa17c000bf0, 
    __in_chrg=<optimized out>) at common/ceph_context.cc:468
#2  0x00007fa18346f361 in put (this=0x7fa17c000bf0) at ./common/ceph_context.h:73
#3  librados::RadosClient::~RadosClient (this=0x7fa17c006cb0, __in_chrg=<optimized out>)
    at librados/RadosClient.cc:341
#4  0x00007fa18346f379 in librados::RadosClient::~RadosClient (this=0x7fa17c006cb0, 
    __in_chrg=<optimized out>) at librados/RadosClient.cc:343
#5  0x00007fa18343fe4a in rados_shutdown (cluster=0x7fa17c006cb0)
    at librados/librados.cc:2318
#6  0x00007fa1867c2adc in ffi_call_unix64 () from /usr/lib/x86_64-linux-gnu/libffi.so.6
#7  0x00007fa1867c240c in ffi_call () from /usr/lib/x86_64-linux-gnu/libffi.so.6
#8  0x00007fa1869d95fe in _ctypes_callproc ()
   from /usr/lib/python2.7/lib-dynload/_ctypes.x86_64-linux-gnu.so
#9  0x00007fa1869daf9e in ?? ()
   from /usr/lib/python2.7/lib-dynload/_ctypes.x86_64-linux-gnu.so
#10 0x000000000052e1e6 in PyEval_EvalFrameEx ()
#11 0x000000000052cf32 in PyEval_EvalFrameEx ()
#12 0x000000000052cf32 in PyEval_EvalFrameEx ()
#13 0x000000000056d0aa in ?? ()
#14 0x00000000004d9854 in ?? ()
#15 0x00000000004da20b in PyEval_CallObjectWithKeywords ()
#16 0x00000000005872b2 in ?? ()
#17 0x00007fa1880f1182 in start_thread (arg=0x7fa18148c700) at pthread_create.c:312
#18 0x00007fa187e1e30d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
(gdb) f 1
#1  0x00007fa18353cdf7 in CephContext::~CephContext (this=0x7fa17c000bf0, 
    __in_chrg=<optimized out>) at common/ceph_context.cc:468
</pre>

**Comment by liewegas** [comment]
it's doing it on plana90.. i'll just leave it in its current state if you want to take a look.

**Comment by dillaman** [comment]
@liewegas Thanks -- taking a look now.

**Comment by dillaman** [comment]
CephContext::lookup_or_create_singleton_object performs an unsafe reinterpret_cast to AssociatedSingletonObject -- which has a virtual destructor.  The TracepointProvider::Singleton does not have a virtual destructor so it is effectively invoking a random function.

**Pull request merged**
