### PR TITLE
googletest: pick up change to silence error=maybe-uninitialized warning

### PR DESCRIPTION
**Pull request by djgalloway**
to include the fix of https://github.com/google/googletest/pull/3024

otherwise GCC-11 fails to compile the tests with following warning:

In file included from ../src/googletest/googletest/src/gtest-all.cc:42:
../src/googletest/googletest/src/gtest-death-test.cc: In function ‘bool testing::internal::StackGrowsDown()’:
../src/googletest/googletest/src/gtest-death-test.cc:1301:24: error: ‘dummy’ may be used uninitialized [-Werror=maybe-uninitialized]
 1301 |   StackLowerThanAddress(&dummy, &result);
      |   ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~
../src/googletest/googletest/src/gtest-death-test.cc:1290:13: note: by argument 1 of type ‘const void*’ to ‘void testing::internal::StackLowerThanAddress(const void*, bool*)’ declared here
 1290 | static void StackLowerThanAddress(const void* ptr, bool* result) {
      |             ^~~~~~~~~~~~~~~~~~~~~
../src/googletest/googletest/src/gtest-death-test.cc:1299:7: note: ‘dummy’ declared here
 1299 |   int dummy;
      |       ^~~~~
cc1plus: all warnings being treated as errors

Signed-off-by: Kefu Chai <kchai@redhat.com>
(cherry picked from commit abbdf338d6725febd686ccdbe395b207283c04ab)

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/master/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Review by cbodley — APPROVED** [review]

**Comment by cbodley** [comment]
@djgalloway it looks like we need the other commits from https://github.com/ceph/ceph/pull/38781 too

**Comment by djgalloway** [comment]
The other commits won't apply cleanly and I don't know C

**Comment by djgalloway** [comment]
image

**Comment by cbodley** [comment]
i see that @tchaikov added a couple of the commits. if there's more to do tomorrow, i'll work through the rest

**Comment by cbodley** [comment]
digging into this further.. bumping the googletest submodule did resolve the original failure:
```
gtest-death-test.cc:1301:24: error: ‘dummy’ may be used uninitialized [-Werror=maybe-uninitialized]
```
the new failures are complaining about the lack of a stream output operator for `std::chrono::time_point`, so it *looked* related to the other changes in https://github.com/ceph/ceph/pull/38781. but those changes were all specific to `std::chrono::duration`, so i don't expect them to resolve this

another interesting point is that, where 'make check' failed:
> -- The CXX compiler identification is GNU 9.3.0

the 'ceph API tests' succeeded:
> -- The CXX compiler identification is GNU 11.1.0

**Comment by djgalloway** [comment]
Now we're getting somewhere

```
root@braggi14:~# gcc --version
gcc (Ubuntu 11.1.0-1ubuntu1~20.04) 11.1.0
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

root@braggi15:~# which gcc
/usr/bin/gcc
root@braggi15:~# gcc --version
gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by djgalloway** [comment]
`install-deps.sh` only wants >=9 (https://github.com/ceph/ceph/blob/octopus/install-deps.sh#L301 | https://github.com/ceph/ceph/blob/master/install-deps.sh#L333 )

I don't know what the right option here is.  Change to GCC 11?

**Comment by cbodley** [comment]
> `install-deps.sh` only wants >=9 (https://github.com/ceph/ceph/blob/octopus/install-deps.sh#L301 | https://github.com/ceph/ceph/blob/master/install-deps.sh#L333 )
> 
> I don't know what the right option here is. Change to GCC 11?

it looks like those `>=9`s were specific to ubuntu's bionic release. the only other restriction on compiler versions i see is `g++ (>= 7)` in debian/control

but as long as focal and centos stream 8 both have gcc 11, it should be safe to require that for octopus? we've been planning to do that on master for c++20 support

**Comment by djgalloway** [comment]
All Jenkins builders are running GCC 11 now.  Now I'm just trying to figure out how to get past the gtest errors.  https://github.com/ceph/ceph/pull/46230

**Pull request merged**
