### PR TITLE
Better parsing of arguments passed to mount.fuse.ceph by mount command.

### PR DESCRIPTION
**Pull request by FlorentCoppint**
Fixes http://tracker.ceph.com/issues/14735

Signed-off-by: Florent Bautista <florent@coppint.com>

### CODE REVIEW

**Comment by liewegas** [comment]
What other arguments is mount passing that we need to ignore?

**Comment by FlorentCoppint** [comment]
systemd on Jessie is mounting with "-n" before "-o", so $3 & $4 were not correct.

**Comment by FlorentCoppint** [comment]
Is there a problem with my commit ? I saw build failed but is it related to my (little) diff ?

**Comment by liewegas** [comment]
There's a problem with the builder, not with your patch. Looks good, thanks!

**Pull request merged**
