### PR TITLE
osd/osd_types: pg_num_max reordering

### PR DESCRIPTION
**Pull request by kamoltat**
- Moved `pg_num_max` to be at the end of the list in src/osd/osd_types.cc and src/osd/osd_types.h.
- Added comments to `opt_mapping` and `pool_opts_t` about the importance of the order of options in the list and class.
- Added MDS daemons so that it can create cephFS pools and set options using`do_set_pool()` in FSCommand.cc, such that we can cover corner cases like upgrading.
- Added debug level logs to `do_set_pool()` in src/mon/OSDMonitor.cc.
- Added debug level logs to `_maybe_adjust()` in src/pybind/mgr/pg_autoscaler/module.py.

Fixes https://tracker.ceph.com/issues/54263

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [x] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Review by jdurgin — APPROVED** [review]
Could you add a comment around opt_mapping indicating that order is important and new fields should be added at the end?

**Comment by kamoltat** [comment]
> Could you add a comment around opt_mapping indicating that order is important and new fields should be added at the end?

sure thing!

**Comment by kamoltat** [comment]
1/1 pass sanity check run on upgrade:pacific-x:parallel suite

/a/ksirivad-2022-03-03_05:59:40-upgrade:pacific-x:parallel-wip-ksirivad-pg-num-max-reorder-distro-basic-smithi/6717556/

**Comment by kamoltat** [comment]
jenkins test make check

**Review by neha-ojha — APPROVED** [review]

**Comment by kamoltat** [comment]
jenkins test windows

**Comment by kamoltat** [comment]
/a/yuriw-2022-03-04_21:56:41-rados-wip-yuri4-testing-2022-03-03-1448-distro-default-smithi

and

/a/yuriw-2022-03-04_00:56:58-rados-wip-yuri4-testing-2022-03-03-1448-distro-default-smithi

Rados run analysis: 
https://pad.ceph.com/p/ksirivad_teuthology_analysis#L67

Summary: no failures, dead jobs are related.

**Pull request merged**
