### PR TITLE
nautilus: rgw multisite: set entry to lc index of slave when syncing

### PR DESCRIPTION
**Pull request by IlsooByun**
Fixes: https://tracker.ceph.com/issues/44268
Signed-off-by: Ilsoo Byun <ilsoobyun@linecorp.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by smithfarm** [comment]
jenkins test make check

**Comment by smithfarm** [comment]
@IlsooByun Can you explain - in the commit message, not in a PR comment - why it is not feasible to fix the issue in master/octopus, first, and then cherry-pick it from there to nautilus?

**Comment by IlsooByun** [comment]
> @IlsooByun Can you explain - in the commit message, not in a PR comment - why it is not feasible to fix the issue in master/octopus, first, and then cherry-pick it from there to nautilus?

Sorry for the confusion. Since I am currently using Nautilus in my cluster, I made a patch for Nautilus. I have not yet tested this patch on the master. Would it be better to rewrite this patch for the master?

**Comment by cbodley** [comment]
> Would it be better to rewrite this patch for the master?

yes please! we do all development and testing on master, and backport from there as necessary

**Comment by smithfarm** [comment]
adding DNM until:

* master PR https://github.com/ceph/ceph/pull/34553 is merged
* commit from master PR is cherry-picked into this PR using `git cherry-pick -x` 
* cherry-pick is confirmed to have a Conflicts section if cherry-pick was not clean

**Comment by smithfarm** [comment]
The master PR https://github.com/ceph/ceph/pull/34553 is still open, and is going stale. If and when it merges, we can rely on the regular backporting workflows to create the nautilus backport PR correctly, because the ticket https://tracker.ceph.com/issues/44268 is marked for backport to nautilus. Closing as premature.

**Pull request closed without merging**
