### PR TITLE
pacific: qa: pass arg as list to fix test case failure

### PR DESCRIPTION
**Pull request by dparmar18**
Pacific branch's run_cluster_cmd() code can't split string into a list, and
because backporting is too tricky as a lot of qa code doesn't reach pacific, it
would be tedious to backport the PRs that enabled passing string as arg to
run_cluster_cmd() in ceph_manager.py. For complete details please checkout
note #13 in the tracker attached below

Fixes: https://tracker.ceph.com/issues/61732

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [x] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by vshankar** [comment]
jenkins test make check

**Comment by vshankar** [comment]
jenkins test api

**Comment by dparmar18** [comment]
jenkins test make check

**Comment by dparmar18** [comment]
jenkins test api

**Review by vshankar — DISMISSED** [review]

**Comment by pdvian** [comment]
https://pulpito.ceph.com/?branch=wip-yuri8-testing-2023-08-11-0834-pacific

Failures, related:
1. https://tracker.ceph.com/issues/62450          <---- New tracker
Failures, unrelated:
2. https://tracker.ceph.com/issues/61602
3. https://tracker.ceph.com/issues/57386
4. https://tracker.ceph.com/issues/58560
5. https://tracker.ceph.com/issues/59192
6. https://tracker.ceph.com/issues/59193
7. https://tracker.ceph.com/issues/54071
8. https://tracker.ceph.com/issues/50371
9. https://tracker.ceph.com/issues/62456          <---- New tracker
10. https://tracker.ceph.com/issues/55444

Details:
1. pacific:task/test_nfs: TypeError: 'type' object is not subscriptable - Ceph - CephFS
2. tasks/rados_cls_all: Health check failed: 1 pool(s) do not have an application enabled (POOL_APP_NOT_ENABLED) - Ceph - RADOS 
3. cephadm/test_dashboard_e2e.sh: Expected to find content: '/^foo$/' within the selector: 'cd-modal .badge' but never did - Ceph - Mgr - Dashboard
4. test_envlibrados_for_rocksdb.sh failed to subscribe to repo - Infrastructure
5. cls/test_cls_sdk.sh: Health check failed: 1 pool(s) do not have an application enabled (POOL_APP_NOT_ENABLED) - Ceph - RADOS
6. "Failed to fetch package version from https://shaman.ceph.com/api/search ..." - Infrastructure
7. rados/cephadm/osds: Invalid command: missing required parameter hostname(<string>) - Ceph - Orchestrator
8. Segmentation fault (core dumped) ceph_test_rados_api_watch_notify_pp - Ceph - RADOS
9. Could not get lock /var/cache/apt/archives/lock - open (11: Resource temporarily unavailable) - Infrastructure
10. test_cls_rbd.sh: multiple TestClsRbd failures during upgrade test - Ceph - RBD

**Comment by pdvian** [comment]
@dparmar18 [Tracker#62450](https://tracker.ceph.com/issues/62450) is related to this PR. Kindly look into it.

**Comment by dparmar18** [comment]
> @dparmar18 [Tracker#62450](https://tracker.ceph.com/issues/62450) is related to this PR. Kindly look into it.

can you re-run this please, should be fixed

**Review by batrick — CHANGES_REQUESTED** [review]
https://tracker.ceph.com/projects/cephfs/wiki/Pacific#2023-August-11

Leaving request changes so this isn't merged by accident. I see @dparmar18 has already amended the PR with a fix.

**Comment by kotreshhr** [comment]
Looks good to me. The test passed with the fix.

https://pulpito.ceph.com/yuriw-2023-11-30_16:00:27-rados-wip-yuri8-testing-2023-11-29-0706-pacific-distro-default-smithi/7472315/

**Review by kotreshhr — APPROVED** [review]

**Comment by yuriw** [comment]
@dparmar18 @batrick this PR passed tests and can be merged
ref: https://trello.com/c/8qf5SalC

**Pull request merged**
