### PR TITLE
rgw: sts: add all http args to req_info

### PR DESCRIPTION
**Pull request by joke-lee**
Signed-off-by: yuliyang <yuliyang@cmss.chinamobile.com>
@pritha-srivastava would you mind help review this?

fix https://tracker.ceph.com/issues/44090

### CODE REVIEW

**Comment by cbodley** [comment]
ping @joke-lee, can you explain the motivation of this change?

**Comment by joke-lee** [comment]
https://docs.aws.amazon.com/STS/latest/APIReference/API_AssumeRole.html

```
&Action=AssumeRole
&RoleSessionName=testAR
&RoleArn=arn:aws:iam::123456789012:role/demo
&PolicyArns.member.1.arn=arn:aws:iam::123456789012:policy/demopolicy1
&PolicyArns.member.2.arn=arn:aws:iam::123456789012:policy/demopolicy2
&Policy={"Version":"2012-10-17","Statement":[{"Sid":"Stmt1",
"Effect":"Allow","Action":"s3:*","Resource":"*"}]}
&DurationSeconds=3600
```
we will have may params not have Policy   RoleArn  and Action only

**Comment by joke-lee** [comment]
https://github.com/ceph/ceph/pull/31124

**Comment by theanalyst** [comment]
This is already merged via https://github.com/ceph/ceph/pull/31124 ?

**Comment by joke-lee** [comment]
hi @theanalyst #31124  is only process iam request, this pull process sts request

**Comment by theanalyst** [comment]
Ah understood, sorry, LGTM

**Comment by ivancich** [comment]
@joke-lee would you add a tracker for this?

**Comment by joke-lee** [comment]
@ivancich ok

**Comment by ivancich** [comment]
@joke-lee, @cbodley, @theanalyst I'm adding this to a new QA run. The tracker does not list any backports. If that's incorrect, please update it.

**Pull request merged**
