### PR TITLE
pacific: cephadm: batch backport January

### PR DESCRIPTION
**Pull request by jmolmo**
**backport of:**

 #39040,  #39003, #39016, #38974, #38739, #38978, #38954, #38967, #38946, #38945, #38918, #38904, #38507, #38990, #38910

**Conflicts:**

  src/pybind/mgr/cephadm/services/cephadmservice.py (#38954 c95ba878c66, #38918 657027088e4)
  src/cephadm/cephadm (#38739 da309f21da8 b3b6639b7f9 6cab3f02aad 13addf6f54f bc256983c11 c785dc56796 )
  src/mypy.py (#38507 e308bf89895 )
  src/pybind/mgr/orchestrator/_interface.py  (#38507 e308bf89895 )

Signed-off-by: Juan Miguel Olmo Martínez <jolmomar@redhat.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by jmolmo** [comment]
I do not know how.. but it seems I forgot #38954. (Unit test pass...  let's see if we have everything now)

**Review by sebastian-philipp — CHANGES_REQUESTED** [review]
Please add `-x` to `git cherry-pick`: Backport commits need to be backported using `git cherry-pick -x`

**Comment by jmolmo** [comment]
- Removed from the backport #39035 because it breaks cephadm exporter.
- Fixed mypy issue due to a conflict not solved properly (picked again c95ba878c66 from #38954)

**Comment by sebastian-philipp** [comment]
jenkins test make check

**Review by sebastian-philipp — APPROVED** [review]

**Comment by sebastian-philipp** [comment]
https://pulpito.ceph.com/swagner-2021-01-28_08:43:39-rados:cephadm-wip-swagner-testing-2021-01-27-1649-pacific-distro-basic-smithi/

Failures: https://github.com/containers/podman/issues/9096

**Pull request merged**
