### PR TITLE
nautilus: bind on loopback address if no other addresses are available

### PR DESCRIPTION
**Pull request by tchaikov**
https://tracker.ceph.com/issues/50600

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by tchaikov** [comment]
jenkins test docs

**Comment by tchaikov** [comment]
jenkins test docs

**Comment by tchaikov** [comment]
cc @thomasgoirand

**Comment by tchaikov** [comment]
jenkins test docs

**Comment by tchaikov** [comment]
jenkins test docs

**Comment by tchaikov** [comment]
doc built failure
```
Warning, treated as error:
autodoc: failed to import method 'MgrModule.handle_command' from module 'mgr_module'; the following exception was raised:
dynamic module does not define module export function (PyInit_rados)
+ succeed=false
```

the root cause is that cython failed to generate C extension with the expected symbol.

**Comment by tchaikov** [comment]
build failure of doc should be addressed by #41167

**Comment by yuriw** [comment]
test this please

**Comment by badone** [comment]
Still showing "dynamic module does not define module export function (PyInit_rados)"

**Comment by tchaikov** [comment]
rebased against nautilus branch.

**Comment by tchaikov** [comment]
@yuriw seems all the other PRs in this batch were merged. is there anything this change is pending on ?

**Review by ideepika — APPROVED** [review]
lgtm! https://trello.com/c/RnchWl3A/1226-wip-yuri-testing-2021-05-05-1246-nautilus-wip-yuri-testing-5521-nautilus

**Comment by cleverer** [comment]
Can this be expected to be backported to pacific anytime soon?

If needed I can create the PR myself (should be easy with the script…)

**Comment by tchaikov** [comment]
@cleverer #42477

**Pull request merged**
