### PR TITLE
quincy: rbd backports (batch 1)

### PR DESCRIPTION
**Pull request by idryomov**
Backport https://github.com/ceph/ceph/pull/44381, https://github.com/ceph/ceph/pull/44669, https://github.com/ceph/ceph/pull/44714 and https://github.com/ceph/ceph/pull/44282 to quincy.

### CODE REVIEW

**Comment by idryomov** [comment]
make check is blocked on https://github.com/ceph/ceph/pull/44817

**Comment by idryomov** [comment]
jenkins test make check

**Review by ideepika — APPROVED** [review]
lgtm! thanks @idryomov !

**Comment by idryomov** [comment]
I'm running it through rbd suite here:

https://pulpito.ceph.com/dis-2022-01-28_10:47:04-rbd-wip-rbd-quicy-batch-1-distro-default-smithi/

**Comment by idryomov** [comment]
No related failures:

https://pulpito.ceph.com/dis-2022-01-28_10:47:04-rbd-wip-rbd-quicy-batch-1-distro-default-smithi/
https://pulpito.ceph.com/dis-2022-01-28_22:47:14-rbd-wip-rbd-quicy-batch-1-distro-default-smithi/
https://pulpito.ceph.com/dis-2022-01-29_09:56:02-rbd-wip-rbd-quicy-batch-1-distro-default-smithi/

**Pull request merged**
