### PR TITLE
osd: fix possible crash on sending dynamic perf stats report

### PR DESCRIPTION
**Pull request by trociny**
Fixes: https://tracker.ceph.com/issues/41891
Signed-off-by: Mykola Golub <mgolub@suse.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`

</details>

### CODE REVIEW

**Comment by trociny** [comment]
@dillaman Although it is core (not rbd) related, you reviewed my original code, so could you review the fix too?

It was reported to crash in `DynamicPerfStats::add_to_reports` -> `limits.at(query)`, because the `limits` did not have the `query`.  The crashes were reported to occur when many osds were stopped, i.e. may pgs re-peering.

When initially writing this code I thought it would be impossible that the limit would be missing a query because both limit and queries are set (and reset) in `OSD::set_perf_queries` so at any time the pgs would contain only stats for actual queries.

Now thinking how it could happen, the `pg->is_primary()` condition in `OSD::set_perf_queries` and `OSD::get_perf_reports` looks most suspicious to me. Originally I had an assumption that `pg->is_primary()`  could be stable during the `pg` life. But if it is not true, I think the following scenario could lead to the crash:
- a new query is registered when `pg->is_primary()` is true, some statistics is collected
- the pg state is changed and `pg->is_primary()` is false now;
- the query is unregistered but because of `pg->is_primary()` is false the stats is not reset for this `pg`;
- the state is changed and `pg->is_primary()` is true again;
- `OSD::get_perf_reports` is called, tries to add the stale stats (for the non-existent query) that it found for this `pg` and crashes.

I am not very familiar with these osd internals, but if this scenario is possible my patch should fix it.
Alternatively I could just check `limits.count(query)` in `OSD::get_perf_reports`. Another option is to make sure the stats is reset when the primary state is changed (probably in ` PG::clear_primary_state()`?). Or, I just wonder do we really need `pg->is_primary()` condition in in `OSD::set_perf_queries` and `OSD::get_perf_reports`? May be we should process all pgs unconditionally?

**Comment by dillaman** [comment]
@trociny I think it's probably safer and easier to just pull the `is_primary` checks. If they are not primary for any portion of the stats interval, than `m_dynamic_perf_stats.add` will never be invoked so there won't be any stats to collect. It also might be nice to tweak `DynamicPerfStats::add_to_reports` to use `auto limit_it = limits.find(query); if limit_it == limits.end() continue;` once and avoid the `limits.at` calls.

**Comment by trociny** [comment]
@dillaman thanks, updated

**Comment by tchaikov** [comment]
- http://pulpito.ceph.com/kchai-2019-09-27_14:26:44-rados-wip-kefu-testing-2019-09-27-1811-distro-basic-smithi/
- http://pulpito.ceph.com/kchai-2019-09-28_03:32:20-rados-wip-kefu-testing-2019-09-27-1811-distro-basic-smithi/

**Pull request merged**
