### PR TITLE
tests: rgw.py: put client roles in a separate list

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/20417

### CODE REVIEW

**Comment by cbodley** [comment]
@smithfarm can we also fix the yaml that included a `default_idle_timeout` override? i thought we got them all in https://github.com/ceph/ceph/pull/15420

**Comment by smithfarm** [comment]
@cbodley Yes, you got them all. It was in our downstream fork of teuthology.

**Comment by smithfarm** [comment]
But if any override "creeps in" for any reason, the test breaks with the same cryptic error message.

**Comment by smithfarm** [comment]
`teuthology-suite -k distro --machine-type smithi --priority 101 --email ncutler@suse.com --ceph-repo https://github.com/ceph/ceph.git --ceph master --suite-repo https://github.com/smithfarm/ceph.git --suite-branch wip-20417 --suite rgw --filter="multifs/{clusters/fixed-2.yaml frontend/civetweb.yaml objectstore/bluestore-comp.yaml overrides.yaml rgw_pool_type/ec-cache.yaml tasks/rgw_bucket_quota.yaml}"`

**waiting for build**

**Comment by smithfarm** [comment]
@cbodley Noticed that this change renders the `config` option unused in two of the functions, added a commit to clean that up.

**Comment by smithfarm** [comment]
Running the test again: http://pulpito.front.sepia.ceph.com:80/smithfarm-2017-06-27_12:00:48-rgw-master-distro-basic-smithi/

**Comment by yuriw** [comment]
http://pulpito.ceph.com/yuriw-2017-06-27_19:38:18-rgw-wip-yuri-testing_2017_6_28-distro-basic-smithi/

**Pull request merged**
