### PR TITLE
osd: dump number of missing objects for each peer with pg query

### PR DESCRIPTION
**Pull request by guangyy**
Signed-off-by: Guang Yang <yguang@yahoo-inc.com>

### CODE REVIEW

**Comment by guangyy** [comment]
Hi @athanatos , since this one is target for master, is it good to review? Thanks.

**Comment by liewegas** [comment]
This change makes sense to me. Can you please rebase?  Thanks!

**Comment by guangyy** [comment]
Thanks @liewegas , rebased.

**Comment by guangyy** [comment]
The failure looks like a false positive, rebased and let bot run again.

**Comment by dachary** [comment]
@guangyy recorded the failure as a false negative at http://tracker.ceph.com/issues/13924. Let see if it happens again.

**Pull request merged**
