### PR TITLE
luminous: mgr: hold lock while accessing the request list and submitting request

### PR DESCRIPTION
**Pull request by swinds24**
https://tracker.ceph.com/issues/37272

### CODE REVIEW

**Comment by tchaikov** [comment]
@swinds24 instead of targeting this fix to luminous, could you try to fix it on master first? and then it can be backported to mimic and luminous? as i think this issue also exists in master. ideally, if an issue impacts on master also,  we are inclined to fix it in master first. and update the "backport" field of the tracker ticket so we can ensure that fix will be properly populated to LTS branch(es) when it gets merged.

**Comment by swinds24** [comment]
@tchaikov thanks for sharing the rules with me :).  Another PR for master branch was opened: https://github.com/ceph/ceph/pull/25048

**Comment by swinds24** [comment]
@tchaikov thanks sharing the information with me.  I've renewed the commit for luminous and opened another PR for mimic.  BTW, the tracker (https://tracker.ceph.com/issues/36764) was also updated accordingly.  If there is something I miss, please let me know.  Thanks :)

**Comment by smithfarm** [comment]
jenkins test docs

**Comment by yuriw** [comment]
[wip-yuri-testing-2018-12-10-1551-luminous](https://trello.com/c/U2beq0Sg/484-wip-yuri-testing-2018-12-10-1551-luminous)

**Pull request merged**
