### PR TITLE
os/bluestore: remove unused l_bluestore_read_wait_flush_lat

### PR DESCRIPTION
**Pull request by majianpeng**
Now read don't need flush(). See commit 83e33a32fde7f83.

Signed-off-by: Jianpeng Ma <jianpeng.ma@intel.com>

### CODE REVIEW

**Comment by majianpeng** [comment]
@liewegas . Ping

**Comment by liewegas** [comment]
do you mind rebasing on top of https://github.com/ceph/ceph/pull/13965 ?  
That one is about to merge.  THanks!

**Comment by majianpeng** [comment]
@liewegas . rebase on #13965

**Comment by liewegas** [comment]
retest this please

**Comment by majianpeng** [comment]
@liewegas . I notice #13965 already merged into master. Do I need rebase on master? Thanks!

**Comment by liewegas** [comment]
Merged manually, see 903b3fcf4a12e68113f873edda0d231029c851c4

**Pull request closed without merging**
