### PR TITLE
rhel 5.9 librados compile fix, moved blkid to RBD check/compilation

### PR DESCRIPTION
**Pull request by rohanmars**
Signed-off-by: Rohan Mars <code@rohanmars.com>

### CODE REVIEW

**Comment by smithfarm** [comment]
@dachary Is this bot failure real or bogus?

**Comment by smithfarm** [comment]
@rohanmars Can you describe the bug this commit is fixing? Best would be at http://tracker.ceph.com/projects/devops/issues/new . . . that will also help with backporting. Thanks!

**Comment by dachary** [comment]
@smithfarm it's a false negative indeed http://tracker.ceph.com/issues/13176

**Comment by rohanmars** [comment]
@smithfarm, I've created that issue: http://tracker.ceph.com/issues/13177

**Comment by smithfarm** [comment]
@rohanmars Thanks. Now, if you could do `git commit --amend` and add a line to the commit message: `Fixes: #13177` that would be really nice. (After you amend the commit message, force-push your wip branch and the pull request will be updated.)

**Comment by rohanmars** [comment]
@smithfarm, done as requested. Thanks.

**Comment by dachary** [comment]
Please ignore the make check bot, it is a false negative: http://tracker.ceph.com/issues/13181

**Comment by liewegas** [comment]
looks fine to me.  just need to build test..

**Pull request merged**
