### PR TITLE
luminous: cli/crushtools/build.t sometimes fails in jenkins' make check run

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/21783

### CODE REVIEW

**Comment by tchaikov** [comment]
@smithfarm i am not sure why we need to backport 6902627, as it is just a refactor. or am i missing something?

**Comment by smithfarm** [comment]
@tchaikov If it's not doing anything useful, I can drop it.

**Comment by smithfarm** [comment]
@tchaikov Early in the cycle of a stable release, it's nice to backport commits like that, so their absence doesn't cause repeated cherry-pick conflicts later.

**Comment by tchaikov** [comment]
@smithfarm got it. i have no objection to backporting it, just wanted to confirm with you.

**Comment by liewegas** [comment]
http://pulpito.ceph.com/sage-2017-10-20_12:22:00-rados-wip-sage-testing-2017-10-19-2129-distro-basic-smithi/

**Pull request merged**
