### PR TITLE
spdk: advance to upstream dc82989dd2747db0384cafb3b310f2e8792d5c24

### PR DESCRIPTION
**Pull request by smithfarm**
This fixes a py2/3-related build issue in SPDK.

Signed-off-by: Nathan Cutler <ncutler@suse.com>

### CODE REVIEW

**Comment by tchaikov** [comment]
@smithfarm i am okay with sync'ing up the SPDK submodule. but could you help me understand what py2/py3 build issue you have with SPDK. because, AFAICT, SPDK does not have any py2 or py3 dependencies.

**Comment by smithfarm** [comment]
@tchaikov SPDK has an undeclared python build dependency in that "configure" and "Makefile" run a python script. See https://github.com/spdk/spdk/commit/93bd60e0de6b161567182d965239735bf467e85c (already in our submodule) and https://github.com/spdk/spdk/commit/dc82989dd2747db0384cafb3b310f2e8792d5c24 (being brought in by this PR).

Without the latter commit, there is a Python-related error message in the Ceph build log when building RPMs in py3-only environment:

[ 1780s] [ 45%] Performing build step for 'spdk-ext'
[ 1780s] /bin/sh: python: command not found

**Comment by smithfarm** [comment]
https://shaman.ceph.com/builds/ceph/wip-smithfarm-testing-2018-03-05-1617/

**Comment by smithfarm** [comment]
https://shaman.ceph.com/builds/ceph/wip-smithfarm-testing-2018-03-05-2213/d4778ca1ef5d0da8b2d9c4b28ae703b2c692fd3f/

**Comment by tchaikov** [comment]
http://pulpito.ceph.com/kchai-2018-03-05_17:31:09-rados-wip-kefu-testing-2018-03-05-2238-distro-basic-smithi/

**Pull request merged**
