### PR TITLE
rgw: fix the quota check when S3 multipart upload

### PR DESCRIPTION
**Pull request by Aran85**
when the remainder quota of one bucket exceed the maxnum's 95%,then the next file upload can't succeed if it's multipart num more than maxnum's 5%.

chang the quota check timing,only multi post request check quota,multi put will not check obj num again.

Fix: #13223

Signed-off-by: Zengran Zhang zhangzengran@h3c.com

### CODE REVIEW

**Comment by Aran85** [comment]
for instance :
bucket quota max-objects=100
bucket usage quota = 95
the next upload file will fail if it have 6 multiparts.

**Comment by Aran85** [comment]
for instance :
bucket quota max-objects=100
bucket usage quota = 95
the next upload file will fail if it have 6 multiparts.

@yehudasa could you take a look?

**Comment by smithfarm** [comment]
@yehudasa ping

**Comment by yehudasa** [comment]
@Aran85 I'm not sure this is a good idea. This can be taken advantage of by users that would upload infinite amount of data by creating multipart uploads without completing. We do want to account that data even if the upload is not complete.

**Comment by Aran85** [comment]
@yehudasa maybe the --max-size option will works when anyone upload infinite amount of data by creating multipart uploads?

**Comment by Aran85** [comment]
ping @yehudasa

**Comment by lnsyyj** [comment]
Hi ,    I fixed a aws js sdk support multipart upload questions on github.    But the system that there is no change, I think it is because there is no test case.    How do I contact to test?    https://github.com/ceph/ceph/pull/7064
Sender : YuJiangCountry : China

Date: Sun, 27 Dec 2015 22:13:02 -0800

**Comment by liewegas** [comment]
@Aran85 rebase please?  @yehudasa can you take a look?

**Comment by yehudasa** [comment]
@Aran85 looking at it again, I still don't think we should be doing it. The num_objs might not reflect the exact number of complete objects, but that's really ok. It can't really ever be very accurate. When dealing with small numbers it is very noticeable, but practically the num_objs limit should be set to a much higher number, so the inaccuracy due to in-flight uploads is negligible.

**Comment by Aran85** [comment]
@yehudasa can we make a Independent check for every single multi upload's parts num? or close this PR?

**Comment by yehudasa** [comment]
@Aran85 not sure if I understand what you mean by independent check for every single multi upload's part num. Maybe when completing / aborting a multipart upload we need to deal with the accounting correctly?

**Comment by Aran85** [comment]
the completing/aborting of multipart upload works well now :).  bc i  think the rules of quota check a little hard to explain.

**Comment by yehudasa** [comment]
@Aran85 what is the status of this PR?

**Comment by Aran85** [comment]
@yehudasa have no idea about treat it as bug or strategy.

**Comment by liewegas** [comment]
Closing this, feel free to reopen if it should be resurrected!

**Pull request closed without merging**
