### PR TITLE
mon: reject over-large values of max_mds

### PR DESCRIPTION
**Pull request by jcsp**
Fixes: #12222
Signed-off-by: John Spray <john.spray@redhat.com>

### CODE REVIEW

**Comment by liewegas** [comment]
:+1:

**Comment by jecluis** [comment]
lgtm

**Comment by dachary** [comment]
@jcsp jenkins rebase failure, if you rebase + repush the make check bot will be run. Sorry for the noise.

**Comment by tchaikov** [comment]
looks good other than a nitpicking suggestion.

**Pull request merged**
