### PR TITLE
s3select: update s3select submodule to last commit, and enable s3select s3test

### PR DESCRIPTION
**Pull request by galsalomon66**
Signed-off-by: galsalomon66 <gal.salomon@gmail.com>

Fixes: https://tracker.ceph.com/issues/46257

## Checklist
- [x] References tracker ticket
- [x] Updates documentation if necessary
- [x] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Review by mattbenjamin — APPROVED** [review]
lgtm

**Comment by galsalomon66** [comment]
some of teuthology tests failed

http://pulpito.front.sepia.ceph.com/gsalomon-2020-12-07_04:48:56-rgw:verify-update_s3select_submodule_and_s3tests_-distro-basic-smithi/

**Comment by galsalomon66** [comment]
according to 2 teuthology runs , no crash after the fix (zero size chunk in buffer list)

http://pulpito.front.sepia.ceph.com/gsalomon-2020-12-14_20:09:34-rgw:verify-update_s3select_submodule_and_s3tests_-distro-basic-smithi/

http://pulpito.front.sepia.ceph.com/gsalomon-2020-12-15_00:57:13-rgw:verify-update_s3select_submodule_and_s3tests_-distro-basic-smithi/

**Comment by galsalomon66** [comment]
all tests had passed

http://pulpito.front.sepia.ceph.com/gsalomon-2020-12-15_11:56:50-rgw:verify-update_s3select_submodule_and_s3tests_-distro-basic-smithi/

**Comment by galsalomon66** [comment]
depend on https://github.com/ceph/s3-tests/pull/373

**Comment by galsalomon66** [comment]
moving to #38892

**Pull request closed without merging**
