### PR TITLE
rgw: add basic support for X-Delete-At header of Swift API.

### PR DESCRIPTION
**Pull request by rzarzynski**

### CODE REVIEW

**Comment by rzarzynski** [comment]
Idempotence of DELETE operation in Swift seems to depend on its version. On my local machine:
```
$ curl -i http://localhost:9090/v1/AUTH_test/cont/obj -X DELETE  -H "X-Auth-Token: $token"
HTTP/1.1 204 No Content
Content-Length: 0
Content-Type: text/html; charset=UTF-8
X-Trans-Id: tx4db0169f6c3d48acb0dcf-00554a3fe1
Date: Wed, 06 May 2015 16:22:57 GMT

$ curl -i http://localhost:9090/v1/AUTH_test/cont/obj -X DELETE  -H "X-Auth-Token: $token"
HTTP/1.1 404 Not Found
Content-Length: 70
Content-Type: text/html; charset=UTF-8
X-Trans-Id: tx4b167ad59a5243869d43b-00554a3fe4
Date: Wed, 06 May 2015 16:23:00 GMT

<html><h1>Not Found</h1><p>The resource could not be found.</p></html>

$ dpkg -s swift-proxy | grep Version
Version: 1.13.1-0ubuntu1.1
```

However, in master branch of Swift (commit b54532ca0581738c7c4622cd32e936088e9adf11, file `swift/proxy/controllers/obj.py`) we see:

```python
    @public
    @cors_validation
    @delay_denial
    def DELETE(self, req):
        """HTTP DELETE request handler."""
(...)
        # When deleting objects treat a 404 status as 204.
        status_overrides = {404: 204}
        resp = self.make_requests(req, obj_ring,
                                  partition, 'DELETE', req.swift_entity_path,
                                  headers, overrides=status_overrides)
        return resp
```

**Comment by yehudasa** [comment]
@rzarzynski so we should definitely keep it idempotent

**Comment by rzarzynski** [comment]
Just pushed a new version with _X-Delete-After_ support and check on POST.
Original branch is available as well: [wip-4099_swift_api_layer-old-1](https://github.com/rzarzynski/ceph/tree/wip-4099_swift_api_layer-old-1).

The ceph class (I called it _timeindex_) and garbage collector for expired objects (_radosgw-object-expirer_) will be pushed as separate PRs.

**Comment by rzarzynski** [comment]
@yehudasa tested this branch altogether with #4739 against current master + PR #5047 + PR #5053 (small patches to prohibit early exit of many Tempest tests due to problems with _X-Trans-Id_ and _Content-Type_ HTTP headers). Both Tempest and s3-tests look fine.

* [Results of s3-tests and Tempest run on current Ceph master + PR #5047 + PR #5053](https://gist.github.com/rzarzynski/01d35481d9f7a0a1f052)
* [Results of s3-tests and Tempest run on current Ceph master + PR #5047 + PR #5053 + objexp (PR #4739 + PR #4549)](https://gist.github.com/rzarzynski/472d1ff03367990f2ddc)

**Comment by yehudasa** [comment]
Opened PR #5692 against infernalis that also incorporates my additions

**Pull request closed without merging**
