### PR TITLE
rgw: roles: refactor roles class to the new multisite svc definitions 

### PR DESCRIPTION
**Pull request by theanalyst**
Introduce RGWRole and related services which actually perform the sysobj IO. The RGWRole Class itself is split into a RGWRoleInfo struct that holds the actual data & RGWRole class which provides the same interface as before, so the only change at the callsites was to use the RGWRoleCtl class instead of the rados ctl classes. Role creation will create the related metadata objects for role names & paths, however only role_info metadata object is actually in the metadata log, similar to how user MDLog works.

TODO:
- [ ] forward to meta-master in admin and other create apis
- [x] move list by path prefix out of RGWRole
- [x] Replace read by stat calls for existence check in create apis
- [x] tests 
- [ ] commit cleanup

Fixes: https://tracker.ceph.com/issues/45659

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by theanalyst** [comment]
Sync of creates & deletes is working as expected. While it still needs cleanups before merge, open for reviews.

**Comment by cbodley** [comment]
@adamemerson @pritha-srivastava @mattbenjamin i think this PR would benefit from a similar layer-collapsing (see https://github.com/ceph/ceph/pull/41798) to drop the `RGWSI_Role` and `RGWSI_Role_RADOS` services. the rest of this looks pretty reasonable

**Comment by adamemerson** [comment]
I would hold off on some of this. @dang mentioned having plans to pull apart SysObj into a few different kinds of object as part of Zipper in the last refactor meeting, so rewriting things in terms of the services might be premature.

**Comment by cbodley** [comment]
> I would hold off on some of this. @dang mentioned having plans to pull apart SysObj into a few different kinds of object as part of Zipper in the last refactor meeting, so rewriting things in terms of the services might be premature.

zipper got a `rgw::sal::RGWRole` interface since this PR was created, so we'll need to rebase with that in mind. but any calls involving `SysObj` should be internal to `rgw::sal::RadosRole` so i don't think we're blocked on anything here

**Comment by pritha-srivastava** [comment]
thanks @cbodley @adamemerson , I will look into #41798

**Comment by pritha-srivastava** [comment]
> @adamemerson @pritha-srivastava @mattbenjamin i think this PR would benefit from a similar layer-collapsing (see #41798) to drop the `RGWSI_Role` and `RGWSI_Role_RADOS` services. the rest of this looks pretty reasonable

@cbodley : I think I understand what is to be done to merge Dan's rgw::sal changes, Abhishek's changes here and collapsing the services. Just to be clear here - I need to collapse RGWSI_Role_RADOS and RGWSI_Role into one class (RGWSI_Role) as has been done in #41798?

**Comment by cbodley** [comment]
> 
> 
> > @adamemerson @pritha-srivastava @mattbenjamin i think this PR would benefit from a similar layer-collapsing (see #41798) to drop the `RGWSI_Role` and `RGWSI_Role_RADOS` services. the rest of this looks pretty reasonable
> 
> @cbodley : I think I understand what is to be done to merge Dan's rgw::sal changes, Abhishek's changes here and collapsing the services. Just to be clear here - I need to collapse RGWSI_Role_RADOS and RGWSI_Role into one class (RGWSI_Role) as has been done in #41798?

honestly i would prefer not to have a role service at all. i'm not convinced we need the `RGWRoleCtl` either, if `rgw::sal::RGWRole` already covers all of its functionality

**Comment by pritha-srivastava** [comment]
> > > @adamemerson @pritha-srivastava @mattbenjamin i think this PR would benefit from a similar layer-collapsing (see #41798) to drop the `RGWSI_Role` and `RGWSI_Role_RADOS` services. the rest of this looks pretty reasonable
> > 
> > 
> > @cbodley : I think I understand what is to be done to merge Dan's rgw::sal changes, Abhishek's changes here and collapsing the services. Just to be clear here - I need to collapse RGWSI_Role_RADOS and RGWSI_Role into one class (RGWSI_Role) as has been done in #41798?
> 
> honestly i would prefer not to have a role service at all. i'm not convinced we need the `RGWRoleCtl` either, if `rgw::sal::RGWRole` already covers all of its functionality

rgw::sal::RGWRole with rgw::sal::RadosRole covers all the functionality. But where is the code that handles the replication, if we do away with the service classes?

**Comment by pritha-srivastava** [comment]
> > > > @adamemerson @pritha-srivastava @mattbenjamin i think this PR would benefit from a similar layer-collapsing (see #41798) to drop the `RGWSI_Role` and `RGWSI_Role_RADOS` services. the rest of this looks pretty reasonable
> > > 
> > > 
> > > @cbodley : I think I understand what is to be done to merge Dan's rgw::sal changes, Abhishek's changes here and collapsing the services. Just to be clear here - I need to collapse RGWSI_Role_RADOS and RGWSI_Role into one class (RGWSI_Role) as has been done in #41798?
> > 
> > 
> > honestly i would prefer not to have a role service at all. i'm not convinced we need the `RGWRoleCtl` either, if `rgw::sal::RGWRole` already covers all of its functionality
> 
> rgw::sal::RGWRole with rgw::sal::RadosRole covers all the functionality. But where is the code that handles the replication, if we do away with the service classes?

Should the zone info and be_handler be added to RadosRole/RGWRole for that?

**Comment by cbodley** [comment]
> But where is the code that handles the replication, if we do away with the service classes?

metadata sync uses `RGWMetadataManager::get()` to read metadata, and `RGWMetadataManager::put()` to write it. for each 'type' of metadata, we register a `RGWMetadataHandler` with the manager so it knows how to read/write that type. so it's the `RGWRoleMetadataHandler` part that really matters here

past that, i'm not really clear on how the backend stuff fits in

> Should the zone info and be_handler be added to RadosRole/RGWRole for that?

ok, i guess i missed all the stuff with `class RGWSI_Role_Module` and the 'backend handler'.. i take back what i said about "the rest of this looks pretty reasonable" :(

i guess the only purpose of the `RGWSI_Role` service is to provide ownership of this `RGWSI_Role_Module` memory? i wonder if we can store that in `RGWRoleMetadataHandler` or `RGWMetadataManager` instead

**Comment by pritha-srivastava** [comment]
> > But where is the code that handles the replication, if we do away with the service classes?
> 
> metadata sync uses `RGWMetadataManager::get()` to read metadata, and `RGWMetadataManager::put()` to write it. for each 'type' of metadata, we register a `RGWMetadataHandler` with the manager so it knows how to read/write that type. so it's the `RGWRoleMetadataHandler` part that really matters here
> 
> past that, i'm not really clear on how the backend stuff fits in
> 
> > Should the zone info and be_handler be added to RadosRole/RGWRole for that?
> 
> ok, i guess i missed all the stuff with `class RGWSI_Role_Module` and the 'backend handler'.. i take back what i said about "the rest of this looks pretty reasonable" :(
> 
> i guess the only purpose of the `RGWSI_Role` service is to provide ownership of this `RGWSI_Role_Module` memory? i wonder if we can store that in `RGWRoleMetadataHandler` or `RGWMetadataManager` instead

Yes, it looks like RGWSI_Role_Module and struct Svc {
    RGWSI_Zone *zone{nullptr};
    RGWSI_Meta *meta{nullptr};
    RGWSI_MetaBackend *meta_be{nullptr};
    RGWSI_SysObj *sysobj{nullptr};
  } svc; can be added to RGWRoleMetadataHandler (or RadosRole), Can we do away with the be_handler? I can see that being used in RGWCtl, which ultimately calls svc.meta_be (which is RGWSI_MetaBackend_Sobj). I think the RGW_SI_Role and RGW_SI_Role_RADOS can be done away with if we move the above two (module and svc) to RGWRoleMetadataHandler. It appears that we can also do away with RGWCtl class and have the functionality in RadosRole (introduced by Dan's refactoring).
I can see that RGWRoleMetadataHandler gets instantiated in RGWCtlDef::init and passed in the constructor of RGWRoleCtl, but don't see it being used in the methods of RGWRoleCtl.

**Comment by adamemerson** [comment]
We have the option of ditching the entire RGWSI and module and backend business and just subclassing RGW Metadata Handler directly, which would be my preference, if we have to involve the RGW Metadata Handler stuff at all.

**Pull request closed without merging**
