### PR TITLE
qa/mgr/dashboard: Fix type annotation error.

### PR DESCRIPTION
**Pull request by sebastian-philipp**
Also removed unused import

Signed-off-by: Sebastian Wagner <sebastian.wagner@suse.com>

### CODE REVIEW

**Comment by tchaikov** [comment]
retest this please

**Comment by s0nea** [comment]
Do we need to schedule a QA test run for this PR?

**Comment by s0nea** [comment]
@sebastian-philipp okay, agree.

**Comment by callithea** [comment]
QA run passed: http://pulpito.ceph.com/laura-2018-11-27_08:12:19-rados:mgr-wip-lpaduano-testing-25235-distro-basic-smithi/ - but I guess I need to re-run the tests after this PR has been rebased.

**Pull request merged**
