### PR TITLE
luminous: osd: add numpg_removing metric

### PR DESCRIPTION
**Pull request by badone**
https://tracker.ceph.com/issues/23268

### CODE REVIEW

**Comment by badone** [comment]
Jenkins, retest this please

**Comment by badone** [comment]
@smithfarm Let me know if this is OK or not please mate :)

**Comment by smithfarm** [comment]
@badone LGTM, thanks.

**Comment by yuriw** [comment]
[wip-yuri5-testing-2018-03-27-1535-luminous](https://trello.com/c/0zxXqm9m/281-wip-yuri5-testing-2018-03-27-1535-luminous)

**Pull request merged**
