### PR TITLE
pacific: Update boost url, fixing windows build

### PR DESCRIPTION
**Pull request by petrutlucian94**
backport tracker: https://tracker.ceph.com/issues/50726

---

backport of https://github.com/ceph/ceph/pull/41192 https://github.com/ceph/ceph/pull/41217
parent tracker: https://tracker.ceph.com/issues/50672

this backport was staged using ceph-backport.sh version 16.0.0.6848
find the latest version at https://github.com/ceph/ceph/blob/master/src/script/ceph-backport.sh

### CODE REVIEW

**Comment by tchaikov** [comment]
jenkins, retest this please

**Comment by petrutlucian94** [comment]
jenkins test make check

**Review by tchaikov — APPROVED** [review]

**Comment by tchaikov** [comment]
@petrutlucian94 have you verified if this change addresses the build failure on pacific? if yes, could you paste the link to the build?

**Comment by petrutlucian94** [comment]
> @petrutlucian94 have you verified if this change addresses the build failure on pacific? if yes, could you paste the link to the build?

@tchaikov Yes, here's a failed Pacific build: https://jenkins.ceph.com/job/ceph-dev-new-build/ARCH=x86_64,AVAILABLE_ARCH=x86_64,AVAILABLE_DIST=windows,DIST=windows,MACHINE_SIZE=gigantic/54408/console. Because of the incorrect boost url, it's throwing "gzip: stdin: unexpected end of file" here https://github.com/ceph/ceph/blob/v16.2.3/win32_deps_build.sh#L140

I've also tested locally to make sure that the pacific build works with the updated url and boost version.

**Comment by tchaikov** [comment]
just pushed to https://shaman.ceph.com/builds/ceph/pacific-pr-41259-kefu/6719fda12b645822321e8e8420748641f2af0f7f/

once it builds, this PR is good to merge.

**Pull request merged**
