### PR TITLE
librbd:add an option to limit the number of snapshots an image can have

### PR DESCRIPTION
**Pull request by renhwztetecs**
Get the number of the Snap in the Image
snap_create_helper add rule "determine whether more than the maximum number of snap Settings"

Fixes: #12892
Signed-off-by: ren.huanwen@zte.com.cn

### CODE REVIEW

**Comment by renhwztetecs** [comment]
https://github.com/ceph/ceph/pull/5854

**Comment by renhwztetecs** [comment]
@liewegas 
Since I was lost to the branch, I can't make rebase, so I have to submit it again.
associated:
https://github.com/ceph/ceph/pull/5854

**Comment by dachary** [comment]
@renhwztetecs please ignore the bot failure, it is a known false negative (see http://tracker.ceph.com/issues/14092 for more details). You can get another run after rebasing and repushing.

**Comment by xiexingguo** [comment]
@renhwztetecs Need rebase

**Comment by dillaman** [comment]
@renhwztetecs This PR appears to be abandoned -- I am going to close it.  I have opened a tracker ticket (http://tracker.ceph.com/issues/15706) so that we keep track of the feature.

**Pull request closed without merging**
