### PR TITLE
pacific: cephfs: backport PRs related to RunCephCmd and mds auth cap perms

### PR DESCRIPTION
**Pull request by rishabh-d-dave**
## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Review by vshankar — CHANGES_REQUESTED** [review]
api test fails with

```
2023-12-18 14:46:18,669.669 INFO:__main__:  File "/home/jenkins-build/build/workspace/ceph-api/qa/tasks/mgr/test_dashboard.py", line 16, in setUp
2023-12-18 14:46:18,669.669 INFO:__main__:    super(TestDashboard, self).setUp()
2023-12-18 14:46:18,669.669 INFO:__main__:  File "/home/jenkins-build/build/workspace/ceph-api/qa/tasks/ceph_test_case.py", line 153, in setUp
2023-12-18 14:46:18,669.669 INFO:__main__:    self._init_mon_manager()
2023-12-18 14:46:18,669.669 INFO:__main__:  File "/home/jenkins-build/build/workspace/ceph-api/qa/tasks/ceph_test_case.py", line 143, in _init_mon_manager
2023-12-18 14:46:18,669.669 INFO:__main__:    self.mon_manager = LocalCephManager(ctx=self.ctx)
2023-12-18 14:46:18,669.669 INFO:__main__:TypeError: LocalCephManager.__init__() got an unexpected keyword argument 'ctx'
```

**Comment by vshankar** [comment]
@rishabh-d-dave could you please have a look.

**Comment by vshankar** [comment]
@rishabh-d-dave I think we can leave this out for the last pacific release. WDYT?

**Comment by rishabh-d-dave** [comment]
> @rishabh-d-dave I think we can leave this out for the last pacific release. WDYT?

I am okay if you are sure about this. I don't this any of the changes here are critically needed.

**Comment by rishabh-d-dave** [comment]
Closing this PR in favour of https://github.com/ceph/ceph/pull/54947.

**Pull request closed without merging**
