### PR TITLE
rgw: Change variable length array of std::strings (not legal in C++) to std::vector<std::string>

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/11542

### CODE REVIEW

**Comment by smithfarm** [comment]
@dachary This has passed first round of integration testing as detailed in http://tracker.ceph.com/issues/11644

**Comment by dachary** [comment]
For the record this is http://tracker.ceph.com/issues/11644#teuthology-run-commitb2aaddd3a06ac13c46df659e1f2b3119f5675802-firefly-backports-july-2015

**Comment by smithfarm** [comment]
@liewegas This PR has passed integration tests. Is it OK to merge? I'm asking you because you merged the master commit that this is a backport of: https://github.com/ceph/ceph/pull/1768

**Comment by liewegas** [comment]
yep, looks good to me!

**Pull request merged**
