### PR TITLE
tools: do not closed stdout ; fix overload of "<" operator

### PR DESCRIPTION
**Pull request by xiexingguo**

### CODE REVIEW

**Comment by xiexingguo** [comment]
@liewegas :-)

**Comment by liewegas** [comment]
@xiexingguo did you mean to include the osd patches in this pull request?

**Comment by liewegas** [comment]
the last two patches look good.  note that i don't think teh radosacl code is used by anything?

**Comment by xiexingguo** [comment]
> did you mean to include the osd patches in this pull request?

yep. Would you like me to split them into another PR?

**Comment by xiexingguo** [comment]
> note that i don't think teh radosacl code is used by anything?

Yeah. Then shall we kill the file instead?

**Comment by liewegas** [comment]
please split.  thanks!
>

**Comment by liewegas** [comment]
let's put it on the cleanup list, but wait until we can check with @yehudasa

**Comment by yuriw** [comment]
http://pulpito.ceph.com/yuriw-2016-07-25_09:34:28-rados-wip-yuri-testing_2016_7_20-distro-basic-smithi/
http://pulpito.ceph.com/yuriw-2016-07-20_14:22:00-rados-wip-yuri-testing_2016_7_20-distro-basic-smithi/

**Pull request merged**
