### PR TITLE
mgr/cephadm: Added missing apply_mon()

### PR DESCRIPTION
**Pull request by sebastian-philipp**
Fixes: https://tracker.ceph.com/issues/44302

Regression from a29a78e4e9c732f485e40900c5f00de1804f2d46

Signed-off-by: Sebastian Wagner <sebastian.wagner@suse.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by liewegas** [comment]
I removed apply_mon because simply reusing _apply_service wasn't sufficient.  IMO this needs to do a few more things:

- before removing a mon, verify that stopping+removing it won't break quorum, or else error out
- before removing each mon, 'ceph mon rm $monid' to remove it from the map.

both of those should probably go in the remove_daemon code so that the same checks apply to 'ceph orch daemon rm'?

- maybe: pause between adding and removing to make sure the new mons have come up.  this may take some time, though, so perhaps it should just wait the remove step if it breaks quorum, and try again later (this may be blocked by the persistent apply specs?)
- on the removal step, should it pass --force to delete the data?  this makes me nervous.
- allow 'apply mon' to do something reasonable even if no network spec is passed, so that it will work with a simple 'ceph orch apply mon 5'.  we can probably (1) check for a public_network setting, and if so use that, else (2) assume that the main IP for the host is okay (DNS resolve/use the HostSpec addr).  until we get this final item we don't actually have parity with rook...

**Comment by sebastian-philipp** [comment]
rebased

**Comment by smithfarm** [comment]
Does this change the recommended way to install the remaining MONs, as documented here?

https://docs.ceph.com/docs/master/cephadm/#deploying-additional-monitors

I also noticed that `qa/tasks/cephadm.py` is using this documented method:

https://github.com/ceph/ceph/blob/d27f512d1731988cf7f369559f2fc324f1592047/qa/tasks/cephadm.py#L471

**Comment by sebastian-philipp** [comment]
> Does this PR change the recommended way to install the remaining MONs, as documented here?
> 
> https://docs.ceph.com/docs/master/cephadm/#deploying-additional-monitors
> 
> I also noticed that `qa/tasks/cephadm.py` is using the documented method:
> 
> https://github.com/ceph/ceph/blob/d27f512d1731988cf7f369559f2fc324f1592047/qa/tasks/cephadm.py#L471

Both work for cephadm. (`add mon` is more intuitive for cephadm, but is not implemented for Rook. `apply mon` is more intuitive for Rook, but a bit awkward for cephadm)

**Comment by smithfarm** [comment]
> Both work for cephadm

Got it. So ceph-salt can avoid this error already today simply by using `ceph orch daemon add mon` instead of `ceph orch apply mon`

**Comment by sebastian-philipp** [comment]
yes

**Comment by smithfarm** [comment]
@sebastian-philipp Is there any test in `rados/cephadm` that exercises `ceph orch apply mon` ?

**Comment by sebastian-philipp** [comment]
> @sebastian-philipp Is there any test in `rados/cephadm` that exercises `ceph orch apply mon` ?

Yes, see https://tracker.ceph.com/issues/44302

**Comment by smithfarm** [comment]
> Yes, see https://tracker.ceph.com/issues/44302

Hm, I see that you had test coverage for it in your wip branch, but I was asking where is it tested in master?

**Comment by liewegas** [comment]
see https://github.com/ceph/ceph/pull/33792

**Pull request closed without merging**
