### PR TITLE
rados/cls_fifo_legacy: 'oid' used after it was moved

### PR DESCRIPTION
**Pull request by Suyashd999**
`oid` used after it was moved

Fixes: https://tracker.ceph.com/issues/66223

clang-tidy warning:

```
/home/suyash/ceph/src/rgw/driver/rados/cls_fifo_legacy.cc:1182:54: warning: 'oid' used after it was moved [bugprone-use-after-move]
  std::unique_ptr<FIFO> f(new FIFO(std::move(ioctx), oid));
                                      	^
```

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Comment by yuvalif** [comment]
jenkins test signed

**Comment by yuvalif** [comment]
@Suyashd999 please add the full clang-tidy warning either in the PR or in the tracker

**Review by yuvalif — APPROVED** [review]

**Comment by Suyashd999** [comment]
Hi @pritha-srivastava can you please review this PR?

**Review by adamemerson — APPROVED** [review]

**Comment by cbodley** [comment]
passed qa in https://pulpito.ceph.com/cbodley-2024-05-29_22:01:03-rgw-wip-cbodley-testing-distro-default-smithi with rerun https://pulpito.ceph.com/cbodley-2024-05-30_15:09:56-rgw-wip-cbodley-testing-distro-default-smithi. new test failures are tracked in https://tracker.ceph.com/issues/66336 and https://tracker.ceph.com/issues/66365

**Comment by cbodley** [comment]
thanks @Suyashd999!

**Pull request merged**
