### PR TITLE
librbd: task finisher should distinguish quiesce tasks with different ID

### PR DESCRIPTION
**Pull request by trociny**
Fixes: https://tracker.ceph.com/issues/47068
Signed-off-by: Mykola Golub <mgolub@suse.com>

### CODE REVIEW

**Comment by trociny** [comment]
I am going to run it through my modified (run in loop) teuthology test and will report the results.

**Comment by trociny** [comment]
@dillaman When working on the last patch from this PR (properly serialize quiesce/unqiesce notifications)  I realized we have an issue with `quiesce_complete` in the case when several quiesce handlers are registered, and only one of `quiesce` callbacks fails (see the comment in the patch).

I think we need to change `quiesce_complete` API to also pass the `handle`, so we could distinguish what handler failed, and could call unqiesce callback for those handlers that did not fail (for those that fail we should not call unquiesce). Do you agree?

**Comment by dillaman** [comment]
> I think we need to change `quiesce_complete` API to also pass the `handle`, so we could distinguish what handler failed, and could call unqiesce callback for those handlers that did not fail (for those that fail we should not call unquiesce). Do you agree?

Sure, I'm fine w/ that even if it's probably a major edge case.

**Comment by trociny** [comment]
@dillaman I think it is ready for review.

**Review by dillaman — APPROVED** [review]
lgtm

**Pull request merged**
