### PR TITLE
make openssl easier to use.

### PR DESCRIPTION
**Pull request by mdw-at-linuxbox**
Augment configuration so it's easy to support http & https in one civetweb frontend.

Get rid of an incorrect warning when using openssl.

And document the thing so people can use it.

### CODE REVIEW

**Comment by yehudasa** [comment]
@mdw-at-linuxbox this PR doesn't deal with openssl linking issue, is there another fix for that?

**Comment by mdw-at-linuxbox** [comment]
The ssl linking stuff is already pushed onto jewel, so that's all done.

**Comment by djzort** [comment]
+1 to include this asap

**Comment by mdw-at-linuxbox** [comment]
I created a new pull request (10335) to replace this one - I have a newer branch that is updated against a more current master, and knows about sonames for libssl.so | libcrypto.so .

**Pull request closed without merging**
