### PR TITLE
src/mds: fix MDSMap upgrade decoding

### PR DESCRIPTION
**Pull request by jcsp**
Hammer MDSMonitors did not validate the state in beacons
and would apply anything to the mds_info_t for a standby,
such as setting it to down:dne.  We must handle this
case during upgrade.

Fixes: http://tracker.ceph.com/issues/17837
Signed-off-by: John Spray <john.spray@redhat.com>

### CODE REVIEW

**Comment by jcsp** [comment]
Pushed a rebase to see if that kicks jenkins into proceeding here

**Comment by jcsp** [comment]
@gregsfortytwo yeah, this made me notice how the ceph-object-corpus stuff seems to have gone stale, this is the kind of thing that could have easily slotted in there :-/

**Comment by jcsp** [comment]
(Passed tests here http://pulpito.ceph.com/jspray-2016-11-22_10:40:59-fs-wip-jcsp-testing-20161121-distro-basic-smithi/)

**Comment by gregsfortytwo** [comment]
Hmm, we can probably push our own stuff into the object corpus whenever we want to. @liewegas, was there ever anything formal for building that up, or was it just something that people did and gradually got forgotten?

**Comment by smithfarm** [comment]
@jcsp In http://tracker.ceph.com/issues/17837#note-18 you mentioned that you backported this to jewel. If you still have that backport around, could you open a PR and link it to the backport tracker issue http://tracker.ceph.com/issues/18100 ?

**Pull request merged**
