### PR TITLE
common: Destroy attr of RWLock after initialized

### PR DESCRIPTION
**Pull request by C2python**
Signed-off-by: Wen Zhang <zhangwen1@unionpay.com>

### CODE REVIEW

**Comment by tchaikov** [comment]
i searched around, and failed to find a place where a `prioritize_write` `RWLock` is created. so guess no need to backport it?

**Comment by C2python** [comment]
Tks for review. This feature is not deprecated. Thus, it should be backported.

**Comment by tchaikov** [comment]
@C2python could point me to the place where `prioritize_write` is `true` when a `RWLock` is created?

**Comment by C2python** [comment]
It is not used indeed now. But I mean that prioritize_write is a useful feature which should be backported.  Tks!

**Comment by cbodley** [comment]
@tchaikov i invented that flag in commit c010a3c0288686c5f130bd053cbe0fbd7b544ee9 for rgw's ability to pause the civetweb frontend and reload the multisite configuration (see 30f7485492d463d6a0ffb8c54f5f23074ab2100c). from src/rgw/rgw_frontend.h:

```c++
struct RGWMongooseEnv : public RGWProcessEnv {
  // every request holds a read lock, so we need to prioritize write locks to
  // avoid starving pause_for_new_config()
  static constexpr bool prioritize_write = true;
  RWLock mutex;

  RGWMongooseEnv(const RGWProcessEnv &env)
    : RGWProcessEnv(env),
      mutex("RGWCivetWebFrontend", false, true, prioritize_write) {
  }
};
```

**Comment by cbodley** [comment]
do we know whether pthreads will actually leak resources if we omit the call to `pthread_rwlockattr_destroy()`?

the flag was introduced for jewel, so it probably qualifies for backport

**Comment by C2python** [comment]
@cbodley I read the source code of pthread_rwlockattr_init and  pthread_rwlockattr_setkind_np in Glibc. No leak reource if we omit the call to pthread_rwlockattr_destroy().

**Comment by cbodley** [comment]
@C2python wow, thanks for digging into this. i propose that we merge this then, but don't worry about the backport. sound ok @tchaikov?

**Comment by tchaikov** [comment]
@cbodley agreed. unless we have concern about other libc implementations. FreeBSD's libc is the only [implementation](https://github.com/lattera/freebsd/blob/master/lib/libthr/thread/thr_rwlockattr.c#L43) i found that is impacted by this leak. i checked both glibc and musl libc .

**Comment by C2python** [comment]
@tchaikov @cbodley Could you merge it? Tks~

**Comment by tchaikov** [comment]
will merge it after running it through the rados qa suite. it takes couple days in general.

**Comment by liewegas** [comment]
http://pulpito.ceph.com/sage-2017-08-24_16:14:07-rados-wip-sage-testing-20170824a-distro-basic-smithi/

**Pull request merged**
