### PR TITLE
[WIP]os/bluestore: fix bluestore deadlock issue

### PR DESCRIPTION
**Pull request by CongMinYin**
Fixes: https://tracker.ceph.com/issues/50571

Signed-off-by: Yin Congmin <congmin.yin@intel.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by CongMinYin** [comment]
CC @tchaikov @benhanokh

**Review by aclamk — APPROVED** [review]
OK.

**Review by aclamk — CHANGES_REQUESTED** [review]
I think we should revert #34109.
This solution introduces deadlock.

But I agree that we should solve the original performance problem.

**Comment by tchaikov** [comment]
alas, #41082 is created for reverting the change

**Comment by markhpc** [comment]
Adding the performance tag only because this is a fix for #34109

**Pull request closed without merging**
