### PR TITLE
qa: run scrub post file system recovery

### PR DESCRIPTION
**Pull request by vshankar**
Running file system scrub is recommended post running filesystem data and metadata recovery. Running scrub isn't covered in tests.

Fixes: http://tracker.ceph.com/issues/59527

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by dparmar18** [comment]
Also the commit msg needs removal of second `Signed-off-by` line

**Comment by vshankar** [comment]
> @vshankar This code is repetitive, used at 3 places. The helper you wrote `scrub()` is the same code, it can be modified to accept dir path to eliminate this repetitiveness. What do you think?
> 
> ```
> out_json = self.fs.run_scrub(["start", some_dir, "repair,recursive"])
> self.assertNotEqual(out_json, None)
> self.assertEqual(out_json["return_code"], 0)
> self.assertEqual(self.fs.wait_until_scrub_complete(tag=out_json["scrub_tag"]), True)
> ```

That's because some tests do not subclass `Workload`, so those are repetitive. We can certainly add a helper, however, I think its fine as it for now....

**Comment by vshankar** [comment]
jenkins test make check

**Comment by dparmar18** [comment]
> 



> > @vshankar This code is repetitive, used at 3 places. The helper you wrote `scrub()` is the same code, it can be modified to accept dir path to eliminate this repetitiveness. What do you think?
> > ```
> > out_json = self.fs.run_scrub(["start", some_dir, "repair,recursive"])
> > self.assertNotEqual(out_json, None)
> > self.assertEqual(out_json["return_code"], 0)
> > self.assertEqual(self.fs.wait_until_scrub_complete(tag=out_json["scrub_tag"]), True)
> > ```
> 
> That's because some tests do not subclass `Workload`, so those are repetitive. We can certainly add a helper, however, I think its fine as it for now....

It shouldn't take much time to create a helper, but im fine with this too

**Review by dparmar18 — APPROVED** [review]

**Comment by vshankar** [comment]
jenkins test make check arm64

**Comment by vshankar** [comment]
jenkins retest this please

**Comment by vshankar** [comment]
fs suite run: https://pulpito.ceph.com/vshankar-2023-05-08_02:52:50-fs-wip-vshankar-testing-20230507.032515-testing-default-smithi/

**Review by kotreshhr — APPROVED** [review]

**Comment by vshankar** [comment]
https://pulpito.ceph.com/vshankar-2023-05-09_07:29:33-fs-wip-vshankar-testing-20230509.054005-testing-default-smithi/

(after removing a problematic PR)

**Comment by vshankar** [comment]
jenkins retest this please

**Comment by vshankar** [comment]
Update: Added change to mark the file system as joinable before running scrub for test_rebuild_inotable test.

**Comment by vshankar** [comment]
https://tracker.ceph.com/projects/cephfs/wiki/Main#11-May-2023

**Comment by vshankar** [comment]
jenkins test make check arm64

**Pull request merged**
