### PR TITLE
octopus: Fixes for make check

### PR DESCRIPTION
**Pull request by djgalloway**
## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/master/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by cbodley** [comment]
```
In file included from src/msg/Message.cc:67:
src/messages/MOSDPing.h:67:36: error: 'signedspan' is not a member of 'ceph::time_detail'; did you mean 'ceph::signedspan'?
   67 |   std::optional<ceph::time_detail::signedspan> delta_ub;  ///< ping sender
      |                                    ^~~~~~~~~~
```
```
src/common/iso_8601.cc: In function 'boost::optional<std::chrono::time_point<ceph::real_clock> > ceph::{anonymous}::calculate(const tm&, uint32_t)':
src/common/iso_8601.cc:39:3: error: 'ceph_assert' was not declared in this scope
   39 |   ceph_assert(n < 1000000000);
      |   ^~~~~~~~~~~
src/common/iso_8601.cc: In function 'std::string ceph::to_iso_8601(ceph::real_time, ceph::iso_8601_format)':
src/common/iso_8601.cc:154:3: error: 'ceph_assert' was not declared in this scope
  154 |   ceph_assert(f >= iso_8601_format::Y &&
      |   ^~~~~~~~~~~
```
it looks like these were both fixed in https://github.com/ceph/ceph/pull/37166

**Comment by cbodley** [comment]
@djgalloway let me know if you'd like help with the cherry-picks

**Comment by djgalloway** [comment]
@cbodley I would love help with cherry-picks.  I did notice those files were 2 years behind the version in master but none of the commits applied cleanly so I did my best.

**Comment by cbodley** [comment]
cherry-picked 01f706ca0ffd39680dbfacf348750c9c0f851578, which should be enough. 🤞 the only conflict was in `src/rgw/rgw_sync_error_repo.h` which doesn't exist in octopus

**Comment by cbodley** [comment]
latest attempt failed on dpdk somehow?
```
make[8]: *** [/home/jenkins-build/build/workspace/ceph-pull-requests/src/spdk/dpdk/mk/internal/rte.compile-pre.mk:116: linux/pci_uio.o] Error 1
make[8]: *** Waiting for unfinished jobs....
```
i couldn't find the initial error in an ocean of `warning: loop variable 'e' of type 'const T&'` warnings, so i cherry-picked Kefu's fix for that too

**Comment by cbodley** [comment]
and now the dpdk error went away and builds are green ¯\\\_(ツ)_\/¯

**Review by cbodley — APPROVED** [review]

**Pull request merged**
