### PR TITLE
reef: vstart: remove filestore options and config snippets

### PR DESCRIPTION
**Pull request by Svelar**
vstart.sh: drop filestore support
Backport of #51362 

Signed-off-by: Rongqi Sun <sunrongqi@huawei.com>
(cherry picked from commit 41f2af4f5e70accd3da1a5761f73bda8786b7f4f 27e66f506f10dca7018c10e3e1804f0b3c217b8e)

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [x] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Review by idryomov — COMMENTED** [review]
Adding second `Signed-off-by` is not needed when backporting.

**Comment by Svelar** [comment]
> Adding second `Signed-off-by` is not needed when backporting.

Removed it.

**Comment by idryomov** [comment]
> Removed it.

... and the second commit also got removed.  The cherry pick from `41f2af4f5e70accd3da1a5761f73bda8786b7f4f` seems to contain both commits -- this isn't right.

**Comment by Svelar** [comment]
> > Removed it.
> 
> ... and the second commit also got removed? The cherry pick from [41f2af4](https://github.com/ceph/ceph/commit/41f2af4f5e70accd3da1a5761f73bda8786b7f4f) seems to contain both commits -- this isn't right.

Emm, I also squashed two commits with rebase.

**Comment by idryomov** [comment]
> Emm, I also squashed two commits with rebase.

That needs to be undone.  The relationship between backport commits and original (main branch) commits should be 1:1, which each backport commit containing a corresponding "cherry picked from" annotation.

**Comment by Svelar** [comment]
jenkins test make check

**Comment by Svelar** [comment]
> > Emm, I also squashed two commits with rebase.
> 
> That needs to be undone. The relationship between backport commits and original (main branch) commits should be 1:1, which each backport commit containing a corresponding "cherry picked from" annotation.

Thanks for reminding. Fix it, check again plz.

**Pull request merged**
