### PR TITLE
rgw: url encode common prefixes for List Objects response 

### PR DESCRIPTION
**Pull request by theanalyst**
https://tracker.ceph.com/issues/41870

Don't url encode / keeping in line with the aws behaviour

### CODE REVIEW

**Comment by theanalyst** [comment]
One question that remains is whether to check for url_encoding request parameter like we do for the keys, I found that botocore seems to default this even when not explicitly specified (and seems to be autoset pretty deep), so there isn't an easy way to check the behaviour on aws

**Comment by theanalyst** [comment]
https://github.com/ceph/s3-tests/pull/311

**Comment by theanalyst** [comment]
Added a followup PR https://github.com/ceph/ceph/pull/30993 for supporting encoding-type on multipart uploads as well

**Comment by ivancich** [comment]
@theanalyst Would you mind specifying which backports are needed on the tracker? That will help me when I finish my qa run. Thanks!

**Comment by ivancich** [comment]
No regressions in running s3-tests.

**Comment by ivancich** [comment]
No teuthology regressions:

- rgw/verify: http://pulpito.ceph.com/ivancich-2019-10-27_14:24:03-rgw-wip-eric-testing-1-distro-basic-smithi/
- rgw/(non-)verify: http://pulpito.ceph.com/ivancich-2019-10-27_04:21:38-rgw-wip-eric-testing-1-distro-basic-smithi/

**Comment by ivancich** [comment]
@theanalyst I've merged this. I don't know whether to make the tracker status "Pending Backports" or "Resolved". Would you kindly update the tracker's status appropriately? Thanks!

**Pull request merged**
