### PR TITLE
run-make-check.sh: run make check with cmake if do_cmake.sh is available

### PR DESCRIPTION
**Pull request by liewegas**
Signed-off-by: Sage Weil <sage@redhat.com>

### CODE REVIEW

**Comment by tchaikov** [comment]
```
90% tests passed, 15 tests failed out of 144

Total Test time (real) = 306.78 sec

The following tests FAILED:
	  1 - test-ceph-helpers.sh (Failed)
	 11 - test_pidfile.sh (Failed)
	 13 - run-tox-ceph-disk (Failed)
	 14 - run-tox-ceph-detect-init (Failed)
	 72 - unittest_async_compressor (SEGFAULT)
	104 - rados-striper.sh (Failed)
	113 - osd-crush.sh (Failed)
	116 - test_pool_quota.sh (Failed)
	126 - osd-bench.sh (Failed)
	127 - osd-config.sh (Failed)
	128 - osd-markdown.sh (Failed)
	129 - osd-reactivate.sh (Failed)
	130 - osd-reuse-id.sh (Failed)
	131 - osd-scrub-snaps.sh (Failed)
	132 - osd-copy-from.sh (Failed)
```

will look at the failed tests next week.

**Comment by liewegas** [comment]
I'm having a hard time running ctest tests locally too... getting confusing errors, but running single-threaded seems to be reliable.

**Comment by wjwithagen** [comment]
On 2-7-2016 16:25, Sage Weil wrote:
> I'm having a hard time running ctest tests locally too... getting
> confusing errors, but running single-threaded seems to be reliable.

So could be that the trouble I'm having is related to this, when running
	gmake -j8 check
from my do_freeBSD-cmake script??
ctest is reporting the same things, so I expected it to be scripting
issues and other port problems.

--WjW

**Comment by tchaikov** [comment]
```
2016-07-04 09:50:44.843075 7fc3808c6700 -1 asok(0x1bd8220) AdminSocketConfigObs::init: failed: AdminSocket::bind_and_listen: The UNIX domain socket path /home/jenkins-build/build/workspace/ceph-pull-requests/build/src/test/testdir/test-7202/out/client.admin.1764.asok is too long! The maximum length on this system is 107
```

should fix this also.

**Comment by tchaikov** [comment]
#10116 has some fixes which enable us to move further. only two out of 144 tests failed.

**Pull request closed without merging**
