### PR TITLE
os/bluestore/BlueFS: prevent concurrent async compaction

### PR DESCRIPTION
**Pull request by liewegas**
Tried to fix this in dbe23c94c0074358380a40d47a417f7999920696
but got the condition wrong (log_flushing is for
normal fsync).

Signed-off-by: Sage Weil <sage@redhat.com>

### CODE REVIEW

**Comment by somnathr** [comment]
@liewegas will try this. Shouldn't we also do an assert() if we are trying to access the iterator of an empty vector before the following location ?

bluefs_extent_t& e = log_file->fnode.extents.front();

**Comment by liewegas** [comment]
added!  should be less confusing than a segv :)

**Comment by somnathr** [comment]
Yes..

**Comment by somnathr** [comment]
Do you want to merge it to master ?

**Comment by liewegas** [comment]
yep!

**Pull request merged**
