### PR TITLE
ex-ML

### PR DESCRIPTION
**Pull request by adamemerson**
Remove spurious XML header from the JSON GetBucketPolicy response.

### CODE REVIEW

**Comment by oritwas** [comment]
@adamemerson , does it have a related tracker issue?

**Comment by adamemerson** [comment]
@oritwas No. Someone just emailed me about it

**Comment by joke-lee** [comment]
@oritwas  here is the tracker issue
http://tracker.ceph.com/issues/20247

**Comment by tchaikov** [comment]
retest this please.

**Comment by oritwas** [comment]
@adamemerson , can you update the commit with  tracker issue link?

**Pull request merged**
