### PR TITLE
os/bluestore: Switch from libzbc library to libzbd library

### PR DESCRIPTION
**Pull request by agayev**
Libzbc maintainers recommend switching to libzbd, which is lighter and supports
both ZNS SSDs and HM-SMR HDDs.

Signed-off-by: Abutalib Aghayev <agayev@cs.cmu.edu>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Review by tchaikov — APPROVED** [review]
wondering if the next library is libzbe ;-)

**Comment by tchaikov** [comment]
jenkins test make check

**Comment by agayev** [comment]
> wondering if the next library is libzbe ;-)

@tchaikov  :-).  I've created the rpms that you said you can upload to http://apt-mirror.front.sepia.ceph.com/lab-extras/8/.  Below are the links to RPMs.  So how does this work?  Once you upload them are they automatically installed on the test systems?

https://agayev.github.io/rpm/libzbd-1.1.0-1.el8.src.rpm
https://agayev.github.io/rpm/libzbd-1.1.0-1.el8.x86_64.rpm
https://agayev.github.io/rpm/libzbd-debuginfo-1.1.0-1.el8.x86_64.rpm
https://agayev.github.io/rpm/libzbd-debugsource-1.1.0-1.el8.x86_64.rpm
https://agayev.github.io/rpm/libzbd-devel-1.1.0-1.el8.x86_64.rpm

**Comment by tchaikov** [comment]
> > wondering if the next library is libzbe ;-)
> 
> @tchaikov :-). I've created the rpms that you said you can upload to http://apt-mirror.front.sepia.ceph.com/lab-extras/8/. Below are the links to RPMs. So how does this work? Once you upload them are they automatically installed on the test systems?
> 
> https://agayev.github.io/rpm/libzbd-1.1.0-1.el8.src.rpm
> https://agayev.github.io/rpm/libzbd-1.1.0-1.el8.x86_64.rpm
> https://agayev.github.io/rpm/libzbd-debuginfo-1.1.0-1.el8.x86_64.rpm
> https://agayev.github.io/rpm/libzbd-debugsource-1.1.0-1.el8.x86_64.rpm
> https://agayev.github.io/rpm/libzbd-devel-1.1.0-1.el8.x86_64.rpm

@agayev i will ping @djgalloway to upload them. and then i will update the build script and spec file so we can install them and enable zoned do you have a public repo for the spec file?

currently, we enable libzbc when it's found. but to ensure the build is repeatable, we should enable this feature only if it's enabled. i will change the spec file accordingly, and update the jenkins job to enable libzbc/libzbd.

so i'd suggest we add an cmake option named
```cmake
option(WITH_ZBD "Enable libzbd bluestore backend" OFF)
```

what do you think?

**Comment by tchaikov** [comment]
never mind, i see you also have the src.rpm package uploaded. but it seems it's missing `autoconf-archive` on el8. fixing..

**Comment by agayev** [comment]
> > > wondering if the next library is libzbe ;-)
> > 
> > 
> > @tchaikov :-). I've created the rpms that you said you can upload to http://apt-mirror.front.sepia.ceph.com/lab-extras/8/. Below are the links to RPMs. So how does this work? Once you upload them are they automatically installed on the test systems?
> > https://agayev.github.io/rpm/libzbd-1.1.0-1.el8.src.rpm
> > https://agayev.github.io/rpm/libzbd-1.1.0-1.el8.x86_64.rpm
> > https://agayev.github.io/rpm/libzbd-debuginfo-1.1.0-1.el8.x86_64.rpm
> > https://agayev.github.io/rpm/libzbd-debugsource-1.1.0-1.el8.x86_64.rpm
> > https://agayev.github.io/rpm/libzbd-devel-1.1.0-1.el8.x86_64.rpm
> 
> @agayev i will ping @djgalloway to upload them. and then i will update the build script and spec file so we can install them and enable zoned block device support. BTW, do you have a public repo for the spec file? just want to ensure the build is repeatable in case the rpm files are corrupted or nuked by accident.
> 
> currently, we enable libzbc when it's found. but to ensure the build is repeatable, we should enable this feature only if it's enabled by user. i will change the spec file accordingly, and update the jenkins job to enable libzbc/libzbd.
> 
> so i'd suggest we add an cmake option named
> 
> ```cmake
> option(WITH_ZBD "Enable libzbd bluestore backend" OFF)
> ```
> 
> what do you think?

Sound good!

**Comment by agayev** [comment]
> never mind, i see you also have the src.rpm package uploaded. but it seems it's missing `autoconf-archive` on el8. fixing..

Yes, I built that RPM by cloning https://github.com/westerndigitalcorporation/libzbd.git and following the instructions in README.  I had to download autoconf-archive from here https://centos.pkgs.org/8/centos-powertools-x86_64/autoconf-archive-2018.03.13-1.el8.noarch.rpm.html

**Comment by tchaikov** [comment]
i mean, autoconf-archive should be a build dependency. see  https://github.com/westerndigitalcorporation/libzbd/pull/2

**Comment by agayev** [comment]
> i mean, autoconf-archive should be a build dependency. see [westerndigitalcorporation/libzbd#2](https://github.com/westerndigitalcorporation/libzbd/pull/2)

Oh, I see what you mean.  Thanks for fixing this!

**Comment by tchaikov** [comment]
@agayev https://github.com/agayev/ceph/pull/1

**Comment by tchaikov** [comment]
because the plan is to enable libzbd in our CI, but currently, only rpm packages are available, so we need to conditionally enable libzbd build on centos builders only. i will work on install-deps.sh and ceph-build/ceph-pull-requests to address this later on .

**Comment by agayev** [comment]
> because the plan is to enable libzbd in our CI, but currently, only rpm packages are available, so we need to conditionally enable libzbd build on centos builders only. i will work on install-deps.sh and ceph-build/ceph-pull-requests to address this later on .

Perfect.  Thanks!

**Comment by tchaikov** [comment]
@agayev could you remove the merge commit from your changeset?

**Comment by agayev** [comment]
> @agayev could you remove the merge commit from your changeset?

Removed.  I forgot "-i" during rebase and a few unrelated commits got in, which I then removed, but looks like those commits automatically added "crimson" as a reviewer...

**Comment by tchaikov** [comment]
https://pulpito.ceph.com/kchai-2020-09-08_12:29:35-rados-wip-kefu-testing-2020-09-08-0934-distro-basic-smithi/

**Comment by tchaikov** [comment]
see #37211

**Comment by agayev** [comment]
> see #37211

Perfect!  Thank you very much!

**Pull request merged**
