### PR TITLE
add an option to limit the number of snapshots an image can have

### PR DESCRIPTION
**Pull request by renhwztetecs**
Get the number of the Snap in the Image
snap_create_helper add rule "determine whether more than the maximum number of snap Settings"

Fixes: #12892
Signed-off-by: ren.huanwen@zte.com.cn

### CODE REVIEW

**Comment by tchaikov** [comment]
i am not sure this is the right way to speed up the deep scrub. it's more like cutting the feet to fit the shoes, imho.

**Comment by renhwztetecs** [comment]
@tchaikov
There is no limit to the number of the snap, could be set by "rbd_snap_max_nums" size

**Comment by dillaman** [comment]
I'm not sure how this protects anyone -- since it's a client-side configuration option, I could just run ```rbd --rbd_snap_max_nums <large number> snap create <snap-spec>``` to create a new snapshot if I hit the limit.

**Comment by yuyuyu101** [comment]
Although limit snap number in config isn't a prefer way for me. I guess if we want to impl this feature, you can store this limit as cls-counter(which should be impl at cls class), I mean you can protect this limit number when creating snapshot in osd side.

**Comment by renhwztetecs** [comment]
@yuyuyu101

**Comment by liewegas** [comment]
this needs rebase, please!

**Pull request closed without merging**
