### PR TITLE
qa/tasks: rbd-mirror daemon not properly run in foreground mode

### PR DESCRIPTION
**Pull request by dillaman**
Fixes: http://tracker.ceph.com/issues/20630
Signed-off-by: Jason Dillaman <dillaman@redhat.com>

### CODE REVIEW

**Comment by dillaman** [comment]
http://pulpito.ceph.com/jdillaman-2017-07-14_10:49:25-rbd-master-distro-basic-smithi/

**Comment by smithfarm** [comment]
@liewegas @dillaman Does this fix http://tracker.ceph.com/issues/20475 as well as http://tracker.ceph.com/issues/20630 ? See http://tracker.ceph.com/issues/20475#note-9

**Comment by liewegas** [comment]
Yes, both are fixed!

**Comment by dillaman** [comment]
Well -- once the kraken and jewel branch PRs are merged and all nodes are cleaned through organic distro kernel install reboots, should be good to go.

**Pull request merged**
