### PR TITLE
rgw/logrotate.conf calls service with wrong init script name

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/12503

### CODE REVIEW

**Comment by smithfarm** [comment]
@dachary This PR is classified as rgw, but I don't think any of the suites we are running actually test logrotate. How do you think we should proceed?

**Comment by dachary** [comment]
@smithfarm I would just ask for approval. Maybe the upgrade suite does some logrotate when upgrading ?

**Comment by smithfarm** [comment]
@ktdreyer This is a backport of https://github.com/ceph/ceph/pull/3953. It is included in the integration tests that are currently running - see http://tracker.ceph.com/issues/11644. I am uncertain whether any of these tests are relevant to this PR, however. Assuming the integration tests are green, do you think this is OK to merge?

**Comment by ktdreyer** [comment]
Yeah, I don't think the integration tests cover this :(

**Comment by ktdreyer** [comment]
it's fine to merge it

**Pull request merged**
