### PR TITLE
quincy: os/bluestore: use direct write in BlueStore::_write_bdev_label

### PR DESCRIPTION
**Pull request by ifed01**
On AArch64 with kernel page size 64K, it occurs occasionally "OSD::init(): unable to read osd superblock" when deploying osd. As bluestore use direct write to write the superblock at 0x2000~1000 and BlueStore::_write_bdev_label use buffer write to write label at 0x0~1000, The OS flush the buffer write algined to page size, it will overwrite the superblock(0x2000~1000). Use driect write to avoid overwriting the superblock.

Fixes: https://tracker.ceph.com/issues/57688
Signed-off-by: luo rixin <luorixin@huawei.com>
(cherry picked from commit afdb5e4271dcabb8aaa7f5c797c31dcbb2e387f6)
Signed-off-by: Igor Fedotov [ifedotov@croit.io](mailto:ifedotov@croit.io)

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by rosinL** [comment]
jenkins retest this please

**Comment by rosinL** [comment]
@ifed01 @aclamk , It is suspended for a long time, can we merge this?

**Comment by ifed01** [comment]
jenkins test make check

**Comment by rosinL** [comment]
jenkins retest this please

**Comment by rosinL** [comment]
jenkins retest this please

**Review by aclamk — APPROVED** [review]

**Comment by ifed01** [comment]
jenkins test docs

**Comment by ifed01** [comment]
jenkins test docs

**Comment by ljflores** [comment]
Hey @ifed01, a new failure reproduced twice in this batch: https://tracker.ceph.com/issues/62401

There were 3 bluestore PRs in the batch, so I will leave a similar message on all of them, as I'm not sure which one could be responsible. Can you take a look and see if it's related? If not, the test results were otherwise clean.

Rados suite review here: https://tracker.ceph.com/projects/rados/wiki/QUINCY#httpstrellocomcw1wxAcJO1814-wip-yuri8-testing-2023-07-24-0819-quincy

**Comment by ljflores** [comment]
Feel free to merge if the above failure is unrelated.

**Pull request merged**
