### PR TITLE
osd: fix PG::all_unfound_are_queried_or_lost for non-existent osds

### PR DESCRIPTION
**Pull request by trociny**
This is a fix for http://tracker.ceph.com/issues/10976

I'd like to have this in hammer, firefly and giant.

Signed-off-by: Mykola Golub <mgolub@mirantis.com>

### CODE REVIEW

**Comment by trociny** [comment]
I am not sure about the tests though: if I found the best place for them. Because when I tried other tests from test_lost.sh they failed for me (for recovery1 it failed with "Recovery never finished", for lost1 -- "Unfound objects didn't go away"). I also had to fix some functions in test_common.sh to make it work for me.

So I wander if test_lost.sh is used now?

**Comment by dachary** [comment]
@trociny if test_lost.sh is not run by make check, chances are it is only rarely used.

**Comment by dachary** [comment]
@athanatos how does that look ?

**Comment by trociny** [comment]
Ok, I tried to add test_lost.sh to 'make check' but it looks this requires much more work (using something like vstart_wrapper.sh. The change is reverted. I am interesting in working on this if other think it makes sense (may be different pull request).

I updated test_lost.sh to be more useful for testing current functionality. Do you like these changes, any suggestions?

**Comment by tchaikov** [comment]
@trociny could you rebase your work on the master branch? seems you merged lots of unrelated commits in this PR. after that i will run test_lost.sh to verify your change. last time, when i ran it, some of other tests in it also failed. shall i comment all of them out and just run `all_osds_die`? could you advise me? thanks =)

**Comment by trociny** [comment]
It was my bad: I forgot that the request was for hummer and rebased it on master.

I created a new request #4174. Please close this one.

@tchaikov I updated tests so some works but some still fail. When executing test_lost.sh with no arguments it will run all what works now  (see run() functions for some comments).

**Comment by tchaikov** [comment]
thanks @trociny , closing this PR...

**Pull request closed without merging**
