### PR TITLE
authtool: update --help and manpage to match code.

### PR DESCRIPTION
**Pull request by robbat2**
Signed-off-by: Robin H. Johnson <robin.johnson@dreamhost.com>

### CODE REVIEW

**Comment by liewegas** [comment]
can you update teh cli test?  usually just

 test/run-cli-tests

and mv test/cli/ceph-authtool/whatever.t.err to whatever.t and commit.

**Comment by robbat2** [comment]
@liewegas added a commit for that; i was already working on it last night, but went to bed before finishing.

**Comment by liewegas** [comment]
@robbat2 one small tweak: you need to preserve the regex for the key in the original file since it's random, to avoid this

-  \tkey = AQAcPAVXjubgEhAAqKIRsKThwMkObvcqAZTiOQ== (esc)
+  \tkey = AQCPQwVXH3P3MRAAbutw3y24e/5pUBYY06dxBw== (esc)

**Comment by robbat2** [comment]
@liewegas fyi i fixed that regex

**Comment by liewegas** [comment]
thanks!

**Pull request merged**
