### PR TITLE
os/filestore: fix result handling logic of destroy_collection

### PR DESCRIPTION
**Pull request by xiexingguo**
The problem here is if we fail to remove the original collection,
we may go on to removing the temp collection(if there is any) and
succeed(although the probability can be really small), then the
result code for the former operation can be overwritten, which is
unsafe and can be misleading.

This pr solves the above problem by starting the process of
parallelly removing a temp collection only if we succeed in
removing the original collection.

Signed-off-by: xie xingguo <xie.xingguo@zte.com.cn>

### CODE REVIEW

**Comment by tchaikov** [comment]
the test failure is not relevant and is address at #7723

**Comment by xiexingguo** [comment]
@tchaikov  Thank you for your kind reminder, you are a good man:)

**Comment by liewegas** [comment]
looks good, thanks!

**Comment by xiexingguo** [comment]
Dropped that change and make sure the rest passed the test, as follow:
```
==> rm -r store_test_temp_dir
[       OK ] ObjectStore/StoreTest.SetAllocHint/3 (283 ms)
[----------] 160 tests from ObjectStore/StoreTest (2829882 ms total)

[----------] Global test environment tear-down
[==========] 160 tests from 1 test case ran. (2829882 ms total)
[  PASSED  ] 160 tests.
[root@localhost src]# 
```

**Comment by liewegas** [comment]
passed rados run

**Comment by tchaikov** [comment]
reviewed, lgtm other than some nits. i see the changes in 8b4a592 are not sitting in critical path, but they are not necessary and complicate the code. so i'd suggest remove them from this PR.

**Comment by xiexingguo** [comment]
Fixed again...

**Comment by xiexingguo** [comment]
@tchaikov Thank you for your careful review.

**Comment by tchaikov** [comment]
lgtm

**Comment by tchaikov** [comment]
the failed tests are not relevant, and are addressed by #8107

**Pull request merged**
