### PR TITLE
mon: Omit MANY_OBJECTS_PER_PG warning when autoscaler is on

### PR DESCRIPTION
**Pull request by chrisphoffman**
mon: Omit message when autoscaler is on
Add a conditional statement when autoscaler is
set to ON to omit message when about pool having
many more objects per pg than cluster average.

Fixes: https://tracker.ceph.com/issues/53516

Signed-off-by: Christopher Hoffman <choffman@redhat.com>

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by neha-ojha** [comment]
jenkins test make check

**Review by neha-ojha — APPROVED** [review]
nit: could you please update the commit message to say ```mon: Omit MANY_OBJECTS_PER_PG warning when autoscaler is on```, to make it clear which warning is being omitted and update https://docs.ceph.com/en/latest/rados/operations/health-checks/#many-objects-per-pg accordingly

**Comment by ljflores** [comment]
jenkins test make check

**Comment by ljflores** [comment]
@chrisphoffman this is a nit, but would you mind amending your last commit (the docs one) to say `doc/rados/operations:" at the beginning? This is just to keep commit titles consistent.

After that, go ahead and add the needs-qa tag back

**Comment by chrisphoffman** [comment]
> @chrisphoffman this is a nit, but would you mind amending your last commit (the docs one) to say `doc/rados/operations:" at the beginning? This is just to keep commit titles consistent.
> 
> After that, go ahead and add the needs-qa tag back

Done. Thank you both for your suggestions.

**Comment by chrisphoffman** [comment]
jenkins test api

**Pull request merged**
