### PR TITLE
pacific: cephadm: Batch backport March (1)

### PR DESCRIPTION
**Pull request by sebastian-philipp**
Backport of #39495, #39630, #39536, #39537, #39415, #39421, #39420, #39474, #39562, #39613, #39649, #39614, #39551, #39644, #39714, #39648, #39733, #39760, #39744, #39612, #39352, #38915, #39722, #38995, #39739, #39730, #39770

Conflicts:
        src/pybind/mgr/rook/module.py
        doc/cephadm/index.rst 

Added two missing commits from #39504

### CODE REVIEW

**Comment by liewegas** [comment]
jenkins test docs

**Review by liewegas — APPROVED** [review]

**Comment by sebastian-philipp** [comment]
```
Exception occurred:
  File "/home/jenkins-build/build/workspace/ceph-pr-docs/src/pybind/mgr/rook/__init__.py", line 2, in <module>
    from .module import RookOrchestrator
  File "/home/jenkins-build/build/workspace/ceph-pr-docs/src/pybind/mgr/rook/module.py", line 163
    @handle_orch_error
    ^
Indentatio

**Review by jmolmo — APPROVED** [review]
For me seems to be ok the list of changes and changes to backport.
Once solved the build problems for the code and for docs is OK to merge in pacific.

**Comment by sebastian-philipp** [comment]
```
rook/__init__.py:2: note: In module imported here:
rook/module.py: note: In member "remove_service" of class "RookOrchestrator":
rook/module.py:392: error: Missing return statement
rook/module.py: note: In member "apply_mds" of class "RookOrchestrator":
rook/module.py:412: error: "apply_filesystem" of "RookCluster" does not return a value
rook/module.py: note: In member "apply_nfs" of class "RookOrchestrator":
rook/module.py:422: error: "apply_nfsgw" of "RookCluster" does not return a value
Found 3 errors in 1 file (checked 15 source files)
ERROR: InvocationError for command /home/jenkins-build/build/workspace/ceph-

**Comment by sebastian-philipp** [comment]
failed:
```
2021-03-05T12:39:06.965 INFO:tasks.workunit.client.0.smithi075.stdout:Mar 05 12:38:58 smithi075 bash[42834]: Error: error parsing host port: invalid port number: strconv.Atoi: parsing " 9093": invalid syntax
```

**Review by avanthakkar — APPROVED** [review]

**Comment by sebastian-philipp** [comment]
changelog: added #39822

**Comment by sebastian-philipp** [comment]
changelog: 

Drop `Revert "qa/suites/rados/cephadm: drop 20.04 podman"` from this PR

**Comment by sebastian-philipp** [comment]
next issue: https://paste.opensuse.org/62480748

**Comment by sebastian-philipp** [comment]
https://pulpito.ceph.com/swagner-2021-03-10_16:24:27-rados:cephadm-wip-swagner2-testing-2021-03-09-1019-pacific-distro-basic-smithi/

**Comment by sebastian-philipp** [comment]
jenkins test make check

**Pull request merged**
