### PR TITLE
kill off test_orchestrator

### PR DESCRIPTION
**Pull request by liewegas**
This is incomplete: the dashboard tests still reference test_orchestrator:
```
../qa/suites/rados/dashboard/tasks/dashboard.yaml:        - tasks.mgr.dashboard.test_orchestrator
../qa/tasks/mgr/dashboard/test_host.py:from .test_orchestrator import test_data
../qa/tasks/mgr/dashboard/test_host.py:        cls._load_module("test_orchestrator")
../qa/tasks/mgr/dashboard/test_host.py:        cmd = ['orch', 'set', 'backend', 'test_orchestrator']
../qa/tasks/mgr/dashboard/test_host.py:        cmd = ['test_orchestrator', 'load_data', '-i', '-']
../qa/tasks/mgr/dashboard/test_host.py:        cmd = ['test_orchestrator', 'load_data', '-i', '-']
../qa/tasks/mgr/dashboard/test_orchestrator.py:        cls._load_module('test_orchestrator')
../qa/tasks/mgr/dashboard/test_orchestrator.py:        cmd = ['orch', 'set', 'backend', 'test_orchestrator']
../qa/tasks/mgr/dashboard/test_orchestrator.py:        cmd = ['test_orchestrator', 'load_data', '-i', '-']
../qa/tasks/mgr/dashboard/test_orchestrator.py:        cmd = ['test_orchestrator', 'load_data', '-i', '-']
../qa/tasks/mgr/test_module_selftest.py:    def test_orchestrator(self):
../src/python-common/ceph/tests/test_inventory.py:                             os.path.dirname(__file__) + '/../../../pybind/mgr/test_orchestrator/du'
```

### CODE REVIEW

**Comment by sebastian-philipp** [comment]
can we get mgr/dashboard to use the cephadm task? right now, dashbaord uses the test orch to test it's orch integration

**Comment by sebastian-philipp** [comment]
close? it would be another late breaking change

**Comment by sebastian-philipp** [comment]
that would mean we have to re-implement vstart in an orchestrator.

**Comment by epuertat** [comment]
> that would mean we have to re-implement vstart in an orchestrator. A log of work, unfortunately.

Wouldn't it be awesome? Kidding :stuck_out_tongue_winking_eye:

**Comment by bk201** [comment]
Thanks for keeping test_orchestrator. It makes Dashboard testing easier by loading dummy data.

**Pull request closed without merging**
