### PR TITLE
Revert "qa/workunits/cls: add executable bit to script"

### PR DESCRIPTION
**Pull request by neha-ojha**
This reverts commit 524248748620dbb60a43600f3d6557fefc00ed21.

test_cls_cas tests need to be fixed before running them consistently.

Fixes: https://tracker.ceph.com/issues/50339
Signed-off-by: Neha Ojha <nojha@redhat.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by neha-ojha** [comment]
https://pulpito.ceph.com/nojha-2021-04-14_15:52:05-rados-master-distro-basic-smithi/

**Comment by tchaikov** [comment]
could you please check if this change breaks `src/script/gen-corpus.sh`?

**Comment by tchaikov** [comment]
probably #40867 is a better fix.

**Comment by neha-ojha** [comment]
> probably #40867 is a better fix.

agreed!

**Comment by neha-ojha** [comment]
Closing in favor of https://github.com/ceph/ceph/pull/40867

**Pull request closed without merging**
