### PR TITLE
librbd: use on-disk image name when storing mirror snapshot state

### PR DESCRIPTION
**Pull request by trociny**
Fixes: https://tracker.ceph.com/issues/49115
Signed-off-by: Mykola Golub <mgolub@suse.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by dillaman** [comment]
There is still a potential hole where client (A) owns the lock and receives the rename request and releases the lock to client (B). When client (C) requests the creation of the mirror snapshot from client (B), client (B) will not know about the rename since it's not part of the refresh state machine. The only solution that I could immediately think up would be to have the exclusive-lock post-acquire state machine potentially refresh the image name from disk. In a perfect world we would have always saved the image name in the image's header so it could be refreshed w/o having all clients constantly hitting the `rbd_directory` object for lookups.

**Comment by trociny** [comment]
@dillaman Alternatively it seems we could just modify `mirror::snapshot::SetImageStateRequest` to read the on-disk image name instead of getting it from the memory. What do you think?

**Comment by dillaman** [comment]
I guess that given the fact that we are essentially rate-limited at ~10-20 snapshots per second maximum, that rate of hits against `rbd_directory` should be negligible.

**Comment by trociny** [comment]
@dillaman I pushed a commit that makes `mirror::snapshot::SetImageStateRequest` read the on-disk image name.

I am not sure what to do with my initial commits. I think it is still worth to keep at least one of them (always check on-disk image name when renaming), because it fixes a corner case for a rename proxied to the lock owner, which still may happen if journaling is enabled. I added a test case that illustrates the potential issue. The other patch (make rename be always executed by lock owner) is probably not needed now.

**Review by dillaman — APPROVED** [review]
lgtm as-is

**Comment by dillaman** [comment]
jenkins test make check

**Comment by trociny** [comment]
> lgtm as-is

@dillaman I just added a small commit that makes `TestLibRBD.RenameViaLockOwner` test run not only when journaling is enabled.

**Pull request merged**
