### PR TITLE
DNM tests - Added cluster compatibility settings

### PR DESCRIPTION
**Pull request by yuriw**
Set cluster to have settings:

@ceph set min-compat-client hammer@, @ceph osd crush tunables hammer@

Signed-off-by: Yuri Weinstein <yweinste@redhat.com>

### CODE REVIEW

**Comment by yuriw** [comment]
http://pulpito.front.sepia.ceph.com:80/yuriw-2017-09-26_22:04:08-upgrade:client-upgrade-luminous-distro-basic-smithi/

**Comment by dillaman** [comment]
@yuriw The ceph_test_librbd_api failures might be related to #15611 since we didn't backport it to hammer. For the notify_master issue, it looks like it incorrectly downloaded the master branch test instead of the jewel branch test.

**Comment by dillaman** [comment]
@yuriw ... also, if you can exclude xenial hosts you should since Hammer wasn't available on Xenial which is the cause of the install errors.

**Comment by yuriw** [comment]
@dillaman good points!

**Comment by dillaman** [comment]
@yuriw Note that Luminous has broken the librados C++ API's ABI which is the immediate reason for the seg fault during ```ceph_test_librbd_api``` tests [1].

[1] http://tracker.ceph.com/issues/21573

**Comment by yuriw** [comment]
see https://github.com/ceph/ceph/pull/18009

**Pull request closed without merging**
