### PR TITLE
jewel: cephfs: Processes stuck waiting for write with ceph-fuse

### PR DESCRIPTION
**Pull request by shinobu-x**
http://tracker.ceph.com/issues/22241

### CODE REVIEW

**Comment by shinobu-x** [comment]
test this please

**Comment by shinobu-x** [comment]
test this please

**Comment by shinobu-x** [comment]
test this please

**Comment by shinobu-x** [comment]
https://jenkins.ceph.com/job/ceph-pull-requests/37105/consoleFull#1877343199bf3c8a86-8876-45aa-9016-a5bacffc83b0

**Comment by smithfarm** [comment]
This passed a rados run at http://tracker.ceph.com/issues/21742#note-15

Still waiting for fs run and @batrick or @ukernel review.

**Comment by smithfarm** [comment]
This passed an fs suite at http://tracker.ceph.com/issues/21742#note-18

@batrick @ukernel OK to merge?

**Comment by smithfarm** [comment]
(Note that the flake8 fix is already in jewel via https://github.com/ceph/ceph/pull/19153 so it's harmless)

**Pull request merged**
