### PR TITLE
jewel: rgw multisite: obsolete 'radosgw-admin period prepare' command

### PR DESCRIPTION
**Pull request by gaurav36**
http://tracker.ceph.com/issues/17507

### CODE REVIEW

**Comment by dachary** [comment]
jenkins test this please (rbd failure)

**Comment by gaurav36** [comment]
@dachary  it seems from jenkins All checks have passed

**Comment by dachary** [comment]
jenkins test this please

**Comment by dachary** [comment]
jenkins test this please (jenkins general failure)

**Comment by dachary** [comment]
jenkins test this please (general jenkins failure)

**Comment by dachary** [comment]
@cbodley does this backport look good to merge ? It passed the rgw suite http://tracker.ceph.com/issues/17851#note-3 . Note that it will not be in 10.2.4, reason why it targets jewel-next.

**Comment by cbodley** [comment]
:+1:

**Pull request merged**
