### PR TITLE
nautilus: test/{fs,cephfs}: Get libcephfs and cephfs to compile with FreeBSD

### PR DESCRIPTION
**Pull request by wjwithagen**
Backport tracker: https://tracker.ceph.com/issues/42460

---

Backport of https://github.com/ceph/ceph/pull/30505

Parent tracker: https://tracker.ceph.com/issues/42448

### CODE REVIEW

**Comment by wjwithagen** [comment]
@smithfarm 
'mmmm, that was the last one I picked, and it went straight in without conflict, after having to fix the previous one, which missed a file in Nautilus. So I have no clue as to what happened there.
Can/Should I amend the commit for this?

**Comment by smithfarm** [comment]
@wjwithagen You just forgot the `-x` in `git cherry-pick -x` . . . don't worry. I'll fix it.

**Comment by yuriw** [comment]
[wip-yuri7-testing-2019-11-13-1707-nautilus](https://trello.com/c/bfPMBPx6/759-wip-yuri7-testing-2019-11-13-1707-nautilus)

**Comment by yuriw** [comment]
@smithfarm this can be merged, passed tests

**Pull request merged**
