### PR TITLE
kraken: rbd-mirror: ensure missing images are re-synced when detected

### PR DESCRIPTION
**Pull request by dillaman**
http://tracker.ceph.com/issues/20022

### CODE REVIEW

**Comment by dillaman** [comment]
retest this please

**Comment by smithfarm** [comment]
Jenkins re-test this please

**Comment by smithfarm** [comment]
Jenkins re-test this please

**Comment by smithfarm** [comment]
Jenkins re-test this please (kraken "make check" is showing a *very* high incidence of the "Unix Domain socket path too long" failure)

**Comment by smithfarm** [comment]
@dillaman The make check failure has hopefully been fixed by https://github.com/ceph/ceph/pull/16069 - could you please rebase to pick it up?

**Comment by smithfarm** [comment]
Jenkins re-test this please

**Comment by smithfarm** [comment]
Nevermind, rebase not necessary (Jenkins merges into latest base branch before starting the test).

Jenkins re-test this please

**Comment by smithfarm** [comment]
Conflict with #14577

**Comment by smithfarm** [comment]
@dillaman Please rebase.

**Comment by smithfarm** [comment]
This passed an rbd suite at http://tracker.ceph.com/issues/19009#note-66

**Pull request merged**
