### PR TITLE
jewel: ceph-{mds,mon,osd} packages need scriptlets with systemd code

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/15633

### CODE REVIEW

**Comment by smithfarm** [comment]
@branto1 Like what you see?

**Comment by branto1** [comment]
LGTM but I just noticed we completely ignored the with_systemd bcond. We should follow-up with the patch that drops it.

**Comment by smithfarm** [comment]
@branto1 Yeah, I realized that and was thinking about it, and then forgot. 

So, like backport all of #8720 to jewel?

**Comment by smithfarm** [comment]
The alternative would be to add `%_with_systemd` conditionals to the jewel backport.

**Comment by branto1** [comment]
Looks like we will be back-porting #8720 to jewel. In the mean-time, I think it should be pretty safe to merge this. We don't use the spec file to do sysvinit builds anyway.

**Pull request merged**
