### PR TITLE
ceph.spec.in: pin to gcc-c++-8.2.1

### PR DESCRIPTION
**Pull request by tchaikov**
as an intermediate solution before
https://bugzilla.redhat.com/show_bug.cgi?id=1726630 gets fixed.

Fixes: https://tracker.ceph.com/issues/40646
Signed-off-by: Kefu Chai <kchai@redhat.com>

- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by tchaikov** [comment]
being tested at https://shaman.ceph.com/builds/ceph/wip-40646-kefu/0f907e6eb231462429987b0306469f1764fc575d/

**Comment by tchaikov** [comment]
```
+ sudo yum-builddep -y /tmp/install-deps.4889/ceph.spec
...
Enabling base-source repository
Enabling centos-sclo-rh-source repository
Enabling centos-sclo-sclo-source repository
...
 --> devtoolset-8-gcc-c++-8.2.1-3.el7.x86_64
Package matching devtoolset-8-gcc-c++-8.2.1-3.el7.x86_64 already installed. Checking for update.
...
error: Failed build dependencies:
	devtoolset-8-gcc-c++ = 8.2.1 is needed by ceph-2:15.0.0-2329.g0f907e6.el7.x86_64
+ rm -fr /tmp/install-deps.4889
```

**Comment by tchaikov** [comment]
https://shaman.ceph.com/builds/ceph/wip-40646-3/70a57b75d349917ae41fb7e707ea649424b75fcc/

**Comment by tchaikov** [comment]
```
[ RUN      ] TestMockObjectMapSnapshotRemoveRequest.ScrubCleanObjects
SKIErrors while running CTest
```

retest this please.

**Comment by b-ranto** [comment]
Could you add a comment to the spec file so that we know when to relax the condition again? Other than that lgtm.

**Comment by tchaikov** [comment]
@b-ranto updated and repushed.

**Comment by tchaikov** [comment]
see also https://github.com/ceph/ceph-build/pull/1330

**Comment by tchaikov** [comment]
retest this please.

**Comment by tchaikov** [comment]
retest this please

**Pull request merged**
