### PR TITLE
Fixes for coverity and SCA issues

### PR DESCRIPTION
**Pull request by dalgaaf**
Fixing Coverity issues like:
- USE_AFTER_FREE
- UNREACHABLE
- NEGATIVE_RETURNS
- FORWARD_NULL
- UNINTENDED_INTEGER_DIVISION
- UNINIT_CTOR
- RESOURCE_LEAK
- CTOR_DTOR_LEAK

Other fixes:
- make constructors with one argument explicit
- replace string::find() with compare() for performance reasons
- remove unused variable
- fix manpage for ceph --admin-daemon
- fix and clarify some expressions and calculations
- add tag for cppcheck to suppress intentional memleak
- call free after malloc 
- fix reassignment of variables before use
- fix null pointer deref
- init members in ctor init list
- fix class member hiding member from base

### CODE REVIEW

**Comment by liewegas** [comment]
needs rebase?

**Comment by jcsp** [comment]
@liewegas re. the data scan bit: yeah!

**Comment by tchaikov** [comment]
reviewed all the commits.

**Comment by dalgaaf** [comment]
Fixed comments and rebased to master

**Comment by liewegas** [comment]
@dalgaaf Sorry, missed this one and it needs another rebase.  I'll add needs-qa now so it doesn't get lost again!

**Comment by tchaikov** [comment]
@dalgaaf ping?

**Comment by dalgaaf** [comment]
@tchaikov : I was absent some months ... will rebase the patchset

**Comment by liewegas** [comment]
Welcome back, Danny!  I was just about to adopt this one.  ;)

**Comment by tchaikov** [comment]
@dalgaaf Danny thanks and welcome back!

**Comment by dalgaaf** [comment]
Rebased to master

**Comment by dalgaaf** [comment]
The merge conflict is from the "explicit" patch. If possible I would rebase it directly before the merge, otherwise I would have to rebase the patch every day.

**Comment by liewegas** [comment]
Ah, in that case I'll just merge manually when the time comes.

**Comment by dalgaaf** [comment]
@liewegas Thanks! The issue is that this patch changes many files and each new commit to master can easily break this one.

**Comment by liewegas** [comment]
merged manually!

**Pull request closed without merging**
