### PR TITLE
cmake: set empty INSTALL_RPATH on crypto shared libs

### PR DESCRIPTION
**Pull request by smithfarm**
Fixes: http://tracker.ceph.com/issues/40398
Signed-off-by: Nathan Cutler <ncutler@suse.com>

### CODE REVIEW

**Comment by smithfarm** [comment]
I have a couple more of these left to upstream - if you guys agree, I'll push them into this PR.

**Comment by rjfd** [comment]
> I have a couple more of these left to upstream - if you guys agree, I'll push them into this PR.

sure

**Comment by smithfarm** [comment]
OK, these three commits are all I have for this bug ATM.

**Comment by smithfarm** [comment]
jenkins test docs

**Comment by smithfarm** [comment]
https://shaman.ceph.com/builds/ceph/wip-40398/e445052241c55852bd158a3acce125883b556c97/

**Comment by smithfarm** [comment]
The CentOS builds seem to be fine with this, but the Ubuntu/Debian ones not so. The Ubuntu Bionic "crimson" build failed with this error:

```
	dpkg-shlibdeps -Tdebian/ceph-mon.substvars debian/ceph-mon/usr/bin/ceph-mon debian/ceph-mon/usr/bin/ceph-monstore-tool
dpkg-shlibdeps: warning: debian/ceph-common/usr/lib/ceph/crypto/libceph_crypto_openssl.so contains an unresolvable reference to symbol _ZN4ceph14PluginRegistry3addERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES8_PNS_6PluginE: it's probably a plugin
	install -d debian/ceph-fuse/DEBIAN
	dpkg-shlibdeps -Tdebian/ceph-fuse.substvars debian/ceph-fuse/usr/bin/ceph-fuse
dpkg-shlibdeps: error: cannot find library libceph-common.so.0 needed by debian/ceph-fuse/usr/bin/ceph-fuse (ELF format: 'elf64-x86-64' abi: '0201003e00000000'; RPATH: '')
dpkg-shlibdeps: error: cannot continue due to the error above
Note: libraries are not searched in other binary packages that do not have any shlibs or symbols file.
To help dpkg-shlibdeps find private libraries, you might need to use -l.
dh_shlibdeps: dpkg-shlibdeps -Tdebian/ceph-fuse.substvars debian/ceph-fuse/usr/bin/ceph-fuse returned exit code 2
dpkg-shlibdeps: warning: debian/ceph-common/usr/lib/ceph/crypto/libceph_crypto_isal.so.1.0.0 contains an unresolvable reference to symbol _ZN4ceph14PluginRegistry3addERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES8_PNS_6PluginE: it's probably a plugin
dpkg-shlibdeps: warning: 3 other similar warnings have been skipped (use -v to see them all)
	install -d debian/python-rados/DEBIAN
	dpkg-shlibdeps -Tdebian/python-rados.substvars debian/python-rados/usr/lib/python2.7/dist-packages/rados.x86_64-linux-gnu.so
	install -d debian/python3-rados/DEBIAN
	dpkg-shlibdeps -Tdebian/python3-rados.substvars debian/python3-rados/usr/lib/python3/dist-packages/rados.cpython-36m-x86_64-linux-gnu.so
dh_shlibdeps: Aborting due to earlier error
debian/rules:124: recipe for target 'override_dh_shlibdeps' failed
make[1]: *** [override_dh_shlibdeps] Error 255
make[1]: Leaving directory '/build/ceph-15.0.0-1922-ge445052'
debian/rules:43: recipe for target 'binary' failed
make: *** [binary] Error 2
dpkg-buildpackage: error: fakeroot debian/rules binary subprocess returned exit status 2
```

**Comment by smithfarm** [comment]
Changelog:

* rebased
* dropped the ceph-fuse commit, as the Ubuntu/Debian builds in Shaman found it offensive

**Comment by smithfarm** [comment]
https://shaman.ceph.com/builds/ceph/wip-40398/2e6ce00413edce0e9b91d7abbe17ba7620bf0697/

**Comment by smithfarm** [comment]
@tchaikov Is the "crimson" build failure in Shaman something I need to worry about for the purposes of this PR?

**Comment by smithfarm** [comment]
```
.Traceback (most recent call last):
  File "/home/jenkins-build/build/workspace/ceph-pull-requests/build/src/pybind/mgr/dashboard/node-env/bin/nodeenv", line 10, in <module>
    sys.exit(main())
  File "/home/jenkins-build/build/workspace/ceph-pull-requests/build/src/pybind/mgr/dashboard/node-env/local/lib/python2.7/site-packages/nodeenv.py", line 1076, in main
    create_environment(env_dir, opt)
  File "/home/jenkins-build/build/workspace/ceph-pull-requests/build/src/pybind/mgr/dashboard/node-env/local/lib/python2.7/site-packages/nodeenv.py", line 905, in create_environment
    install_node(env_dir, src_dir, opt)
  File "/home/jenkins-build/build/workspace/ceph-pull-requests/build/src/pybind/mgr/dashboard/node-env/local/lib/python2.7/site-packages/nodeenv.py", line 692, in install_node
    download_node_src(node_url, src_dir, opt, prefix)
  File "/home/jenkins-build/build/workspace/ceph-pull-requests/build/src/pybind/mgr/dashboard/node-env/local/lib/python2.7/site-packages/nodeenv.py", line 549, in download_node_src
    member_list = tarfile_obj.getmembers()
  File "/usr/lib/python2.7/tarfile.py", line 1836, in getmembers
    self._load()        # all members, we first have to
  File "/usr/lib/python2.7/tarfile.py", line 2417, in _load
    tarinfo = self.next()
  File "/usr/lib/python2.7/tarfile.py", line 2348, in next
    self.fileobj.seek(self.offset - 1)
  File "/usr/lib/python2.7/gzip.py", line 443, in seek
    self.read(1024)
  File "/usr/lib/python2.7/gzip.py", line 268, in read
    self._read(readsize)
  File "/usr/lib/python2.7/gzip.py", line 315, in _read
    self._read_eof()
  File "/usr/lib/python2.7/gzip.py", line 354, in _read_eof
    hex(self.crc)))
IOError: CRC check failed 0x95ce16a5 != 0x8265fd40L
src/pybind/mgr/dashboard/CMakeFiles/mgr-dashboard-nodeenv.dir/build.make:60: recipe for target 'src/pybind/mgr/dashboard/node-env/bin/npm' failed
make[3]: *** [src/pybind/mgr/dashboard/node-env/bin/npm] Error 1
CMakeFiles/Makefile2:5613: recipe for target 'src/pybind/mgr/dashboard/CMakeFiles/mgr-dashboard-nodeenv.dir/all' failed
make[2]: *** [src/pybind/mgr/dashboard/CMakeFiles/mgr-dashboard-nodeenv.dir/all] Error 2
make[2]: *** Waiting for unfinished jobs....
```

Looks like a transient (network connectivity-related?) issue in the dashboard front-end build.

**Comment by smithfarm** [comment]
jenkins test make check

**Comment by tchaikov** [comment]
the log of crimson jenkins build was removed. i just rebased this PR onto master and pushed to ceph-ci at https://shaman.ceph.com/builds/ceph/wip-28593-kefu/769419efa4615a864024c5d573b4d7ab658e165b/

**Comment by tchaikov** [comment]
the ci branch builds fine.

the "make check" run failed for unknown reasons though...
```
[ 47%] Building CXX object src/librbd/CMakeFiles/rbd_internal.dir/exclusive_lock/PostAcquireRequest.cc.o
src/librbd/CMakeFiles/rbd_internal.dir/build.make:1094: recipe for target 'src/librbd/CMakeFiles/rbd_internal.dir/exclusive_lock/PostAcquireRequest.cc.o' failed
make[3]: *** [src/librbd/CMakeFiles/rbd_internal.dir/exclusive_lock/PostAcquireRequest.cc.o] Terminated
```

jenkins retest this please

**Comment by smithfarm** [comment]
@tchaikov Thanks!

**Pull request merged**
