### PR TITLE
[RFC] rgw: Libcurl+NSS memory leak mitigation when performing keystone SSL auth

### PR DESCRIPTION
**Pull request by mkogan1**
Tracker issue:
http://tracker.ceph.com/issues/23375

When libcurl is configured with --with-nss
There is a memory leak in the PK11_CreateGenericObject() function (in libnss3.so)
that occurs when keystone users authority authentication is using ssl.
(rgw_keystone_verify_ssl = true)

By calling the curl_global_cleanup() its possible to release the memory in libcurl.

(This patch is currently only for the curl_easy_* flow, can be extended to the curl_multi_* flow also)

### CODE REVIEW

**Comment by mattbenjamin** [comment]
@mkogan1 could this get a rebase?

**Comment by mattbenjamin** [comment]
@cbodley and I discussed--maybe the way forward here is to globally transition out of NSS crypto?

**Comment by mattbenjamin** [comment]
@liewegas ^^

**Comment by liewegas** [comment]
IIRC @rzarzynski said the backport is nontrivial, but it brings along some performance benefits with it.  If it's feasible it seems like a better cost/benefit than spending time fixing old nss code.

**Pull request closed without merging**
