### PR TITLE
rgw: handle http options CORS with v2 auth

### PR DESCRIPTION
**Pull request by tobias-urdin**
If we get a HTTP OPTIONS request for a presigned URL that contains credentials we need to compute the signature using the method given in the access-control-request-method http header.

This is the same as performed for v4 auth in [1].

[1] https://github.com/ceph/ceph/pull/52673

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Comment by tobias-urdin** [comment]
Added testing in https://github.com/ceph/s3-tests/pull/589

**Comment by cbodley** [comment]
> Added testing in [ceph/s3-tests#589](https://github.com/ceph/s3-tests/pull/589)

@tobias-urdin thanks, i hadn't seen this pr yet so created a couple test cases of my own in https://github.com/ceph/s3-tests/pull/590. but those tests are passing against main without this pr to fix. any idea why?

**Comment by tobias-urdin** [comment]
> > Added testing in [ceph/s3-tests#589](https://github.com/ceph/s3-tests/pull/589)
> 
> @tobias-urdin thanks, i hadn't seen this pr yet so created a couple test cases of my own in [ceph/s3-tests#590](https://github.com/ceph/s3-tests/pull/590). but those tests are passing against main without this pr to fix. any idea why?

nice! we can use your pr instead and drop mine if we can add the "tenanted client" case as well, my python autoformatter touched a lot of things that was probably unnecessary as well

since we skip signature verification these should already pass for normal auth, but they don't for keystone auth since we only skip signature verification if the access key + secret is cached already

otherwise for keystone if it's not cached we need to do a real signature verification which means the http method needs to be replaced with the one from the header when calculating the signature, same as we already do for signature v4

sigv2 is still default in AWS CLI (the version i tested with atleast) if you dont specify signature_version=s3v4 when creating a presigned url which is why i found it when trying to reproduce the tracker [1] since i used the cli and not boto3 when testing this time

[1] https://tracker.ceph.com/issues/68149

**Review by cbodley — APPROVED** [review]

**Comment by cbodley** [comment]
created https://tracker.ceph.com/issues/68353 for backports

**Comment by cbodley** [comment]
jenkins test api

**Comment by cbodley** [comment]
jenkins test windows

**Comment by adamemerson** [comment]
jenkins test api

**Comment by cbodley** [comment]
passed qa in https://pulpito.ceph.com/cbodley-2024-10-04_16:30:32-rgw-wip-68353-distro-default-smithi/ against the new test cases in https://github.com/ceph/s3-tests/pull/589:
```
s3tests_boto3/functional/test_s3.py::test_cors_presigned_get_object PASSED [ 68%]
s3tests_boto3/functional/test_s3.py::test_cors_presigned_get_object_tenant PASSED [ 68%]
s3tests_boto3/functional/test_s3.py::test_cors_presigned_get_object_v2 PASSED [ 68%]
s3tests_boto3/functional/test_s3.py::test_cors_presigned_get_object_tenant_v2 PASSED [ 69%]
s3tests_boto3/functional/test_s3.py::test_cors_presigned_put_object PASSED [ 69%]
s3tests_boto3/functional/test_s3.py::test_cors_presigned_put_object_with_acl PASSED [ 69%]
s3tests_boto3/functional/test_s3.py::test_cors_presigned_put_object_v2 PASSED [ 69%]
s3tests_boto3/functional/test_s3.py::test_cors_presigned_put_object_tenant_v2 PASSED [ 69%]
s3tests_boto3/functional/test_s3.py::test_cors_presigned_put_object_tenant PASSED [ 69%]
s3tests_boto3/functional/test_s3.py::test_cors_presigned_put_object_tenant_with_acl PASSED [ 69%]
```

**Pull request merged**
