### PR TITLE
luminous: librbd: refresh image after applying new/removing old metadata

### PR DESCRIPTION
**Pull request by dillaman**
http://tracker.ceph.com/issues/21788

### CODE REVIEW

**Comment by smithfarm** [comment]
```
[ RUN      ] TestJournalReplay.MetadataSet
/home/jenkins-build/build/workspace/ceph-pull-requests/src/test/librbd/journal/test_Replay.cc:759: Failure
      Expected: 9876
To be equal to: ictx->mirroring_replay_delay
      Which is: 0
[  FAILED  ] TestJournalReplay.MetadataSet (40 ms)
[ RUN      ] TestJournalReplay.MetadataRemove
/home/jenkins-build/build/workspace/ceph-pull-requests/src/test/librbd/journal/test_Replay.cc:801: Failure
      Expected: 0
To be equal to: ictx->mirroring_replay_delay
      Which is: 9876
[  FAILED  ] TestJournalReplay.MetadataRemove (25 ms)
[ RUN      ] TestJournalReplay.ObjectPosition
[       OK ] TestJournalReplay.ObjectPosition (31 ms)
[----------] 16 tests from TestJournalReplay (952 ms total)

[----------] Global test environment tear-down
[==========] 504 tests from 51 test cases ran. (34138 ms total)
[  PASSED  ] 502 tests.
[  FAILED  ] 2 tests, listed below:
[  FAILED  ] TestJournalReplay.MetadataSet
[  FAILED  ] TestJournalReplay.MetadataRemove
```

**Comment by trociny** [comment]
@dillaman I suppose it should be backported after or together with http://tracker.ceph.com/issues/21529 (#18042)

**Comment by dillaman** [comment]
@trociny Yes -- with #19447

**Comment by yuriw** [comment]
[rbd => wip-yuri2-testing-2018-01-24-1620-luminous](https://trello.com/c/tD5oVOpi/242-rbd-wip-yuri2-testing-2018-01-24-1620-luminous)

**Comment by dillaman** [comment]
retest this please

**Pull request merged**
