### PR TITLE
librbd: fix merge-diff for >2GB diff-files

### PR DESCRIPTION
**Pull request by dillaman**
http://tracker.ceph.com/issues/14062

### CODE REVIEW

**Comment by jdurgin** [comment]
lgtm

**Comment by dachary** [comment]
@dillaman could you please **git cherry-pick -x** 68125dd01349edf93cfa1af5028c2d438b5ae089 so that there is a reference to the original commit ? Thanks :-)

For the record: 

It passed a run of the infernalis rbd suite ( see http://tracker.ceph.com/issues/13750#note-18 for details ). Note that all valgrind tests in these suites fail because of an environmental problem ( http://tracker.ceph.com/issues/14664 ).

**Comment by dillaman** [comment]
@dachary I can if you think that is a good idea -- but this is essentially a brand new commit since absolutely zero lines would translate from the original.

**Comment by dachary** [comment]
@dillaman oh, sorry I missed that it does not translate. A simple comment in the commit message about that would be enough. The idea is to make it as easy as possible for someone looking at the commit later on to trace it back to its origin.

**Pull request merged**
