### PR TITLE
ceph.in : show the target daemon of cli

### PR DESCRIPTION
**Pull request by XinzeChi**
I think the result of /usr/bin/ceph should also show the target even if the number of targets is 1.
[root@ceph~]# ceph osd pool get rbd min_size 
mon: min_size: 1

This result would tell user that the result is return by monitor.

Signed-off-by: Xinze Chi <xmdxcxz@gmail.com>

### CODE REVIEW

**Comment by XinzeChi** [comment]
@dachary , the loic-bot shows "abort by timeout after 1h". But I do not know why my patch would run so much time.

**Comment by dachary** [comment]
@XinzeChi it is a difficult condition to debug. This is because your test breaks something somewhere and the tests blocks for more than one hour, after which it is killed. I suggest you try to run https://github.com/ceph/ceph/blob/master/src/test/cephtool-test-mon.sh and https://github.com/ceph/ceph/blob/master/src/test/cephtool-test-osd.sh from your source directory and see if they complete.

**Comment by dachary** [comment]
@XinzeChi it looks like src/test/mon/misc.sh is failing : you should try this one first, manually. It's easier to debug this way ;-)

**Comment by XinzeChi** [comment]
@dachary , if user got information from output, such is:
"local size=$(./ceph osd pool get $TEST_POOL size|awk '{print $2}')"
This PR would not compatible with previous version.

**Comment by XinzeChi** [comment]
@dachary , this output of cli is used at many code. Such as "ceph osd getcrushmap > map", if we used this PR, I think It would cause many compatible problem. I close this first. If need, we reopen it.

**Comment by dachary** [comment]
@XinzeChi thanks for the update. Backward compatibility is difficult indeed :-(

**Pull request closed without merging**
