### PR TITLE
jewel: rgw: clear data_sync_cr if RGWDataSyncControlCR fails

### PR DESCRIPTION
**Pull request by cbodley**
http://tracker.ceph.com/issues/17786

### CODE REVIEW

**Comment by cbodley** [comment]
@smithfarm no, but the conflict was trivial (`r = run(data_sync_cr);` vs `int r = run(data_sync_cr);`)

**Comment by smithfarm** [comment]
@cbodley Could you amend the commit message telling which file that conflict was in and how it was resolved? Thanks.

**Comment by cbodley** [comment]
updated commit message:
```
Conflicts:
	src/rgw/rgw_data_sync.cc: declaration of 'int r'
```

**Comment by cbodley** [comment]
jenkins test this please

**Pull request merged**
