### PR TITLE
rgw: add user default-placement cmd

### PR DESCRIPTION
**Pull request by weiqiaomiao**
Add user default-placement cmd to set  or clear default placement rule for a user. The format of this cmd is:

```
radosgw-admin user default-placement --uid=<uid> --default-placement=<placement-rule>
```

e.x.  
set placement-rule named "ssd-placement" to a user named "testuser":

```
radosgw-admin user default-placement --uid=testuser --default-placement="ssd-placement" 
```

and clear it with an empty string specified to "--default-placement" option

```
radosgw-admin user default-placement --uid=testuser --default-placement="" 
```

Signed-off-by: Wei Qiaomiao wei.qiaomiao@zte.com.cn

### CODE REVIEW

**Comment by cbodley** [comment]
retest this please

**Comment by oritwas** [comment]
@weiqiaomiao , please rebase

**Comment by weiqiaomiao** [comment]
@oritwas  rebased

**Comment by liewegas** [comment]
@oritwas ping

**Comment by liewegas** [comment]
@oritwas ping

**Comment by oritwas** [comment]
@weiqiaomiao needs another rebase

**Pull request closed without merging**
