### PR TITLE
mgr/dashboard: Updated existing E2E tests to match new format

### PR DESCRIPTION
**Pull request by nathan-weinberg**
Fixes: https://tracker.ceph.com/issues/38245
Signed-off-by: Nathan Weinberg <nweinber@redhat.com>

### CODE REVIEW

**Comment by nathan-weinberg** [comment]
jenkins test dashboard

**Comment by nathan-weinberg** [comment]
jenkins test dashboard

**Comment by nathan-weinberg** [comment]
@tspmelo @callithea This PR should align all current E2E tests with the format we discussed in PR #26243 - I believe everything is consistent but please double check and let me know what you think. Thanks.

**Comment by callithea** [comment]
jenkins test dashboard

**Pull request merged**
