### PR TITLE
octopus: mgr/dashboard: Proposed About Modal box

### PR DESCRIPTION
**Pull request by callithea**
backport trackers:

* https://tracker.ceph.com/issues/45738
* https://tracker.ceph.com/issues/45787
* https://tracker.ceph.com/issues/45895

backport of

* https://github.com/ceph/ceph/pull/34283
* https://github.com/ceph/ceph/pull/34336

parent trackers:

* https://tracker.ceph.com/issues/44811
* https://tracker.ceph.com/issues/35693

### CODE REVIEW

**Comment by callithea** [comment]
jenkins test dashboard

**Comment by callithea** [comment]
jenkins test dashboard

**Comment by callithea** [comment]
> @callithea, just checked the commit message and you mentioned that `bootstrap-extends.scss` was not in octopus, right? So probably, we need this other PR #34283 before backporting this one. @tspmelo perhaps can shed more light on this?

@epuertat right, it was not in octopus, so I added it.
Yes, currently looking into backporting the commit of #34283 into this one (also, that's what @tspmelo suggested).

**Comment by smithfarm** [comment]
I revised the PR description and linked all three backport issues to this PR. Hopefully I didn't make any mistake, but if I did, I did so with the best of intentions ;-)

**Comment by yuriw** [comment]
[wip-yuri2-testing-2020-06-15-1645-octopus](https://trello.com/c/h9HO5XLe/937-wip-yuri2-testing-2020-06-15-1645-octopus)

**Pull request merged**
