### PR TITLE
script: fix release notes script to include cherry-picked commits

### PR DESCRIPTION
**Pull request by ljflores**
There is a new parameter (`--cherry_picks`, `-c`) added to the
ceph-release-notes script that allows the user to input a list of PR numbers
associated with last-minute cherry-picks.

```
$ LANG=en_US.UTF-8 python3 ceph-release-notes -h
usage: ceph-release-notes [-h] [--rev REV] [--cherry_picks CHERRY_PICKS]
                          [--text] [--html] [--markdown] [--verbose]
                          [--strict] [--token TOKEN] [--use-tags USE_TAGS]
                          [--include-pr-messages]
                          repo

    Make ceph release notes for a given revision. Eg usage:

    $ ceph-release-notes -r tags/v0.87..origin/giant         $(git rev-parse --show-toplevel)

    It is recommended to set the github env. token in order to avoid
    hitting the api rate limits.

positional arguments:
  repo                  path to ceph git repo

optional arguments:
  -h, --help            show this help message and exit
  --rev REV, -r REV     git revision range for creating release notes
  --cherry_picks CHERRY_PICKS, -c CHERRY_PICKS
                        PRs associated with any last-minute cherry-picks. Provide PR numbers as a string separated by commas, i.e. '50575,50625'
  --text, -t            output plain text only, no links
  --html                output html format for (old wordpress) website blog
  --markdown            output markdown format for new ceph.io blog
  --verbose, -v         verbose
  --strict              strict, recommended only for backport releases
  --token TOKEN         Github Access Token ($GITHUB_ACCESS_TOKEN otherwise)
  --use-tags USE_TAGS   Use github tags to guess the component
  --include-pr-messages
                        Include full PR message in addition to PR title, if available
```

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [x] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Review by yuriw — APPROVED** [review]

**Comment by ljflores** [comment]
jenkins test api

**Comment by ljflores** [comment]
jenkins test make check

**Comment by ljflores** [comment]
jenkins test make check

**Comment by ljflores** [comment]
jenkins test make check

**Comment by ljflores** [comment]
jenkins test make check

**Pull request merged**
