### PR TITLE
mgr/dashboard: values of the `Daemons` column of Ganesha exports table

### PR DESCRIPTION
**Pull request by torchiaf**
- Add space after comma symbols

Fixes: https://tracker.ceph.com/issues/47374
Signed-off-by: Francesco Torchia <francesco.torchia@suse.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [x] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Review by pereman2 — APPROVED** [review]

**Comment by pereman2** [comment]
jenkins retest this please

**Comment by pereman2** [comment]
Thanks @torchiaf, can you add the `Fixes: trackerlink` line in the description?

**Comment by torchiaf** [comment]
> Thanks @torchiaf, can you add the `Fixes: trackerlink` line in the description?

HI @pereman2 , sure.

**Review by votdev — APPROVED** [review]

**Comment by Pegonzal** [comment]
jenkins retest this

**Comment by torchiaf** [comment]
jenkins retest this

**Comment by Pegonzal** [comment]
jenkins test api

**Comment by Pegonzal** [comment]
jenkins test make check

**Comment by nizamial09** [comment]
jenkins test make check

**Comment by nizamial09** [comment]
jenkins test api

**Comment by nizamial09** [comment]
jenkins test make check

**Comment by nizamial09** [comment]
jenkins test docs

**Comment by nizamial09** [comment]
jenkins retest this please

**Comment by nizamial09** [comment]
@torchiaf i re triggered the checks several times and it failed. maybe this needs a rebase?

**Comment by torchiaf** [comment]
> @torchiaf i re triggered the checks several times and it failed. maybe this needs a rebase?

Hi @nizamial09 let me try a rebase, thanks.

**Pull request closed without merging**
