### PR TITLE
pacific: os/bluestore: make shared blob fsck much less RAM-greedy.

### PR DESCRIPTION
**Pull request by ifed01**
backport tracker: https://tracker.ceph.com/issues/53890
backport of #43667
parent tracker: https://tracker.ceph.com/issues/44924

Signed-off-by: Igor Fedotov <igor.fedotov@croit.io>
(cherry picked from commit 8fddc8464ee4dbb0ee22a10de21e8c16f38bf1ed)
(cherry picked from commit a902d22b6c785099c704a229db1dc1e6fefee3e2)
 Conflicts:
	src/common/options/global.yaml.in
	src/os/bluestore/BlueStore.cc
	src/os/bluestore/BlueStore.h
	src/test/objectstore/store_test.cc
 Caused by lack of ZNS stuff and options definition in source code
rather than yaml file(s)

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [x] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by ifed01** [comment]
jenkins test make check

**Comment by ifed01** [comment]
jenkins test make check

**Comment by ifed01** [comment]
@aclamk - why you aren't far away from that stuff - could you please take a look as well? ;)

**Review by aclamk — APPROVED** [review]
Seems good!

**Comment by ljflores** [comment]
http://pulpito.front.sepia.ceph.com/?branch=wip-yuri7-testing-2022-02-17-0852-pacific

Failures, unrelated:
    https://tracker.ceph.com/issues/53501
    https://tracker.ceph.com/issues/54337
    https://tracker.ceph.com/issues/52124
    https://tracker.ceph.com/issues/54360
    https://tracker.ceph.com/issues/54406
    https://tracker.ceph.com/issues/53827
    https://tracker.ceph.com/issues/53939
    https://tracker.ceph.com/issues/54411
    https://tracker.ceph.com/issues/54071
    https://tracker.ceph.com/issues/50042

Details:
    1. Exception when running 'rook' task. - Ceph - Orchestrator
    2. Selinux denials seen on fs/rados teuthology runs
    3. Invalid read of size 8 in handle_recovery_delete() - Ceph - RADOS
    4. Dead job at "Finished running handlers" in rados/cephadm/osds/.../rm-zap-wait - Ceph
    5. cephadm/mgr-nfs-upgrade: cluster [WRN] overall HEALTH_WARN no active mgr - Ceph - CephFS
    6. cephadm exited with error code when creating osd: Input/Output error. Faulty NVME? - Infrastructure - Sepia
    7. ceph-nfs-upgrade, pacific: Upgrade Paused due to UPGRADE_REDEPLOY_DAEMON: Upgrading daemon osd.0 on host smithi103 failed - Ceph - Orchestrator
    8. mds_upgrade_sequence: "overall HEALTH_WARN 4 failed cephadm daemon(s); 1 filesystem is degraded; insufficient standby MDS daemons available; 33 daemons have recently crashed" during suites/fsstress.sh - Ceph - CephFS
    9. rados/cephadm/osds: Invalid command: missing required parameter hostname(<string>) - Ceph - Orchestrator
    10. sporadic rados/test.sh failures - Ceph - RADOS

**Comment by ljflores** [comment]
jenkins test api

**Pull request merged**
