### PR TITLE
qa/suites: Reduce fs combination tests for smoke, use bluestore

### PR DESCRIPTION
**Pull request by vasukulkarni**
in testing ..

Signed-off-by: Vasu Kulkarni <vasu@redhat.com>

### CODE REVIEW

**Comment by liewegas** [comment]
see the part where objectstore/ facet is removed, but we also need a symlink to bluestore.yaml to incorporate that?

alternatively, we can use filestore-xfs.yaml for 1node, bluestre.yaml for basic, and filestore-xfs for the systemd facet?

**Comment by vasukulkarni** [comment]
now shows 28 jobs with mostly bluestore, systemd and ceph-deploy still need xfs, although i think ceph-deploy is now ready to test bluestore in master now but needs minor changes

http://pulpito.ceph.com/vasu-2017-04-27_22:28:03-smoke-master---basic-vps/

**Comment by vasukulkarni** [comment]
@liewegas the top folder in basic already has bluestore.yaml link from objectstore, so i just removed the folder since its redundant and correct 1node and systemd still uses xfs.

**Comment by vasukulkarni** [comment]
@liewegas, I checked one of the logs and it is using the bluestore facet, some fs failure are unrelated http://pulpito.ceph.com/vasu-2017-04-27_22:28:03-smoke-master---basic-vps/

**Comment by vasukulkarni** [comment]
@liewegas this one is ready, is there anything you want me to address here?

**Comment by liewegas** [comment]
@vasukulkarni please add a bluestore.yaml to basic and a filestore-xfs.yaml symlink to each of the other two subdirs (systemd and 1node)

**Comment by vasukulkarni** [comment]
@liewegas, the basic folder already has bluestore.yaml from before(It also existed on top folder above objectstore), but no bluestore-comp.yaml (compression option),  systemd is missing filestore-xfs.yaml but its defaults to xfs, I will rework and make both of them clearly visible here.

```
[vakulkar@vakulkar basic]$ pwd
/home/vakulkar/wip-reduce-fs-smoke/ceph/qa/suites/smoke/basic
[vakulkar@vakulkar basic]$ ls -lt
total 8
drwxrwxr-x. 2 vakulkar vakulkar 4096 Apr 27 15:18 tasks
-rw-rw-r--. 1 vakulkar vakulkar    0 Apr 27 15:18 %
lrwxrwxrwx. 1 vakulkar vakulkar   35 Apr 27 15:18 bluestore.yaml -> ../../../objectstore/bluestore.yaml
drwxrwxr-x. 2 vakulkar vakulkar 4096 Apr 27 15:18 clusters
[vakulkar@vakulkar basic]$ ls -lt ../1node/
total 8
-rw-rw-r--. 1 vakulkar vakulkar    0 Apr 27 15:18 %
drwxrwxr-x. 2 vakulkar vakulkar 4096 Apr 27 15:18 clusters
lrwxrwxrwx. 1 vakulkar vakulkar   39 Apr 27 15:18 filestore-xfs.yaml -> ../../../objectstore/filestore-xfs.yaml
drwxrwxr-x. 2 vakulkar vakulkar 4096 Apr 27 15:18 tasks
```

**Comment by vasukulkarni** [comment]
@liewegas I made those changes, Do we want the bluestore-comp.yaml option as well?

**Comment by vasukulkarni** [comment]
@liewegas ping ?

**Pull request merged**
