### PR TITLE
[DNM] Wip librbd shared ro cache hook

### PR DESCRIPTION
**Pull request by zhouyuan**
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by zhouyuan** [comment]
@dillaman Jason, here's the librbd hook part of #22573. There's some dependency on the daemon so it's also included here.  I also wrote a short [notes](https://github.com/ceph/ceph/blob/bddfbeeb2e8f81b2c999da3197e90af2e277225c/src/doc/howtotestsharedrocache.txt) on how to test this

**Comment by dillaman** [comment]
@zhouyuan rebase please

**Comment by shangdehao1** [comment]
@dillaman done. If convenience, could you please help us review this patch? many thanks.

**Comment by zhouyuan** [comment]
@dillaman just discussed with @shangdehao1 he will create another pull request with cleaner & better code, thanks!

**Pull request closed without merging**
