### PR TITLE
crimson/os/seastore: propagate the backref changes about extents remapping to Cache during prepare_record

### PR DESCRIPTION
**Pull request by zhscn**
## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Comment by cyx1231st** [comment]
As discussed, IIRC the specific issue was that reclaiming segments are including segments which still have pending writes.

So it might be simper to exclude those segments until writes are really committed.

**Comment by zhscn** [comment]
> exclude those segments until writes are really committed.

Sorry, I forgot to provide feedback on this design. It's tricky to manage all concurrent transactions writing to a specific segment, so that the segment state can only be set to "committed"(could be reclaimed by gc process) after all transactions have finished. This indicates that the transaction should hold the reference counter for the writing segment and update the segment state when the counter decreases to zero.

Is there anything I missed?

**Comment by cyx1231st** [comment]
> This indicates that the transaction should hold the reference counter for the writing segment and update the segment state when the counter decreases to zero.

Probably possible to be handled at more general `SegmentAllocator` level:
1. In SegmentAllocator::close_segment(), segment-provider will mark the segment as closed, and no further writes will be possible after that.
2. In SegmentAllocator::write(), each write knows when it is started and finished to a specific segment

I think the information is sufficient above to set a segment state from `closed` to `committed`, right?

**Comment by zhscn** [comment]
> * In SegmentAllocator::write(), each write knows when it is started and finished to a specific segment

Probably not enough, at this point, the gc transaction can't retrieve the backref changes about this write.

**Comment by zhscn** [comment]
Here is a simplified model:

drawio

1. segment is not close, gc trans won't select it;
2. segment is close, gc trans is possible to select it to reclaim, but the backref changes are not commited to cache.
3. similar to case 2;
4. segment is safe to reclaim.

**Comment by cyx1231st** [comment]
Yeah, it should be handled atomically with `Cache::complete_commit()`. If implemented in `SegmentAllocator`, it makes the segment available for reclaim unatomically before this point -- they are not guaranteed to be in the same continuation.

**Comment by cyx1231st** [comment]
For the graph, IIUC writing the record will be started after "prepare record".

**Comment by zhscn** [comment]
> For the graph, IIUC writing the record will be started after "prepare record".

Oh, it should be "OOL write".

**Comment by zhscn** [comment]
I'm not sure if there is a more elegant way to handle the gc trans started at point 2, the solution of manually invalidate transaction in this PR looks ugly.

**Comment by cyx1231st** [comment]
> https://github.com/ceph/ceph/commit/0713e29e3722d67fdb4554c21ce93b4e2c26cfdf propagates the remapped backref changes to cache in Cache::prepare_record, so gc is safe to start at point 3.

> https://github.com/ceph/ceph/commit/711a05cbdc7912fcffda2989668bca8c01339801 checks the to be reclaimed range in Cache::prepare_record so it's possible to invalidate the gc transaction started at point 2.

Refering to https://github.com/ceph/ceph/pull/59367, I think it means OOL writes will be allowed be completed after "prepare record", before "record write", and before "complete commit". So without https://github.com/ceph/ceph/pull/59775#issuecomment-2472285049, the same problem will still be possible, right?

**Review by cyx1231st — COMMENTED** [review]
Sorry about the delay. It's reasonable to me to adjust when `backref_entry_mset` should be updated.

**Comment by cyx1231st** [comment]
I'll work with @zhscn to address the reviews.

**Comment by cyx1231st** [comment]
This PR is mostly converted into https://github.com/ceph/ceph/pull/61144/commits/58f7b6e07777228f30d6610f67fff55e1d3fbc41

@zhscn I added you to `Signed-off-by` there, please let me know if there are any concerns.

**Pull request closed without merging**
