### PR TITLE
nautilus: tests: osd-backfill-space.sh test failed in TEST_backfill_multi_partial()

### PR DESCRIPTION
**Pull request by pdvian**
http://tracker.ceph.com/issues/39516

### CODE REVIEW

**Comment by smithfarm** [comment]
jenkins re-test this please

**Comment by smithfarm** [comment]
jenkins re-test this please

**Comment by smithfarm** [comment]
jenkins test make check

**Comment by yuriw** [comment]
[wip-yuri4-testing-2019-07-31-1623-nautilus](https://trello.com/c/Tqzpc0wj/680-wip-yuri4-testing-2019-07-31-1623-nautilus)

**Pull request merged**
