### PR TITLE
pacific: qa: "log [ERR] : error reading sessionmap 'mds2_sessionmap'"

### PR DESCRIPTION
**Pull request by batrick**
https://tracker.ceph.com/issues/50287

### CODE REVIEW

**Comment by batrick** [comment]
retest this please

**Comment by batrick** [comment]
jenkins test docs

**Comment by batrick** [comment]
jenkins test api

**Comment by batrick** [comment]
jenkins test docs

**Comment by batrick** [comment]
`Reviewed-by: Patrick Donnelly <pdonnell@redhat.com>`

**Review by yuriw — APPROVED** [review]
Reviewed-by: Patrick Donnelly <pdonnell@redhat.com>

**Pull request merged**
