### PR TITLE
luminous: possible deadlock in various maintenance operations

### PR DESCRIPTION
**Pull request by pdvian**
http://tracker.ceph.com/issues/22174

### CODE REVIEW

**Comment by pdvian** [comment]
@dillaman @tchaikov @smithfarm

**Comment by dillaman** [comment]
@pdvian http://tracker.ceph.com/issues/21646 should be merged fist since it would resolve some of the conflicts.

**Comment by smithfarm** [comment]
http://tracker.ceph.com/issues/21646 backport staged at https://github.com/ceph/ceph/pull/19447

Marking "DNM" until #19447 is merged and this PR is re-cherry-picked to eliminate conflicts.

@pdvian Another option would be to close this PR and do the cherry-pick directly in #19447 - but if you'd rather keep them separate, that's fine too.

**Comment by dillaman** [comment]
@pdvian This should be ready for re-cherry-picking

**Comment by smithfarm** [comment]
@pdvian Ping

**Comment by pdvian** [comment]
@dillaman @smithfarm Let me resync luminous and re-cherry-pick this PR.

**Comment by pdvian** [comment]
@dillaman @smithfarm please review latest changes.

**Comment by yuriw** [comment]
assuming @dillaman is testing, untagged for now

**Pull request merged**
