### PR TITLE
vstart.sh: move extra_seastar_args up in vstart.sh

### PR DESCRIPTION
**Pull request by liu-chunmei**
add extra_seastar_args in --mkfs

Signed-off-by: Chunmei Liu <chunmei.liu@intel.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by liu-chunmei** [comment]
@tchaikov I am splitting the alien store PR, please review this one for vstart.

**Comment by tchaikov** [comment]
@liu-chunmei could you update the title of the commit message: 

- s/crimson::/vstart.sh:/
- s/ahead/up/

**Comment by liu-chunmei** [comment]
@tchaikov changed.

**Comment by tchaikov** [comment]
@liu-chunmei please note, the title of commit message is different from that of the first comment in a PR. could you "git commit --amend" to update the title and repush?

**Comment by liu-chunmei** [comment]
@tchaikov repushed.

**Pull request merged**
