### PR TITLE
nautilus: mgr/dashboard: switch ng2-toastr to ngx-toastr

### PR DESCRIPTION
**Pull request by epuertat**
NPM package `ng2-toastr` is currently downloaded from a Github repo (https://github.com/zzakir/ng2-toastr). This makes it imossible to use `npm cache`, as non-NPMJS registry packages are always fetched from the original site. This has been fixed in master during the Boostrap upgrade https://github.com/ceph/ceph/pull/25188.

captured

As this means `git` is no longer needed during dashboard build, we could also revert https://github.com/ceph/ceph/pull/24520.

----

Fixes: https://tracker.ceph.com/issues/40768
Signed-off-by: Tiago Melo <tmelo@suse.com>
(cherry picked from commit 67f5e5b18b71ccabcaa8d9e35c57630d17395b06)
Signed-off-by: Ernesto Puerta <epuertat@redhat.com>

Required manual (trivial) fixing of the following files:
Conflicts:
      - src/pybind/mgr/dashboard/frontend/package.json
      - src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/prometheus/alert-list/alert-list.component.spec.ts
      - src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/prometheus/silence-form/silence-form.component.spec.ts
      - src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/prometheus/silence-list/silence-list.component.spec.ts
      - src/pybind/mgr/dashboard/frontend/src/app/ceph/pool/pool-list/pool-list.component.spec.ts
      - src/pybind/mgr/dashboard/frontend/src/app/shared/services/prometheus-notification.service.spec.ts

- [x] References tracker ticket
- [x] Updates documentation if necessary
- [x] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by tspmelo** [comment]
> As this means git is no longer needed during dashboard build, we could also revert #24520.
I hope we don't need to add anymore packages via git, but it could happen again. 
So I would suggest to not revert that.

**Comment by epuertat** [comment]
> > As this means git is no longer needed during dashboard build, we could also revert #24520.
> 
> I hope we don't need to add anymore packages via git, but it could happen again.
> So I would suggest to not revert that.

I think we should revert it (regardless this change) because it's not correct: `install-deps.sh` is meant to install deps, not to fail if some dep is not there, especially when in fact this script installs `git` in RPM, DEB, FreeBSD and Alpine environments. So if `git` is somehow still missing, the expected action is getting it installed, not failing.

Besides, I like how liberal we are with NPM packages compared to Python, but perhaps downloading snapshots from "unofficial" Github forks is going too far (besides it breaks `npm cache` functionality).

**Comment by yuriw** [comment]
[wip-yuri5-testing-2019-07-18-2015-nautilus](https://trello.com/c/1hV01KE7/670-wip-yuri5-testing-2019-07-18-2015-nautilus)

**Comment by smithfarm** [comment]
@epuertat Nit regarding the commit message. We have an established "best practice" of leaving the original commit message intact when cherry-picking. Please limit editing of cherry-pick commit messages to the area below the "(cherry picked from ...)" line.

In this case, you added a line "Fixes: https://tracker.ceph.com/issues/40768" to the original commit message . . . this line does not relate to the original commit, but rather to the backport, so it should have been added below "(cherry picked from. . .)" and not above.

Something for next time - this one is already undergoing integration testing, so let's leave it as-is.

(This suggestion may or may not seem pedantic. FWIW, I believe there is value in having everyone adhere to a consistent format when writing backport commit messages. And all that is really needed is `git cherry-pick -x` and a description of any manually resolved conflicts. Additional information can be added at the backporter's option, but is not required.)

**Comment by epuertat** [comment]
> (This suggestion may or may not seem pedantic. FWIW, I believe there is value in having everyone adhere to a consistent format when writing backport commit messages. And all that is really needed is `git`

Thanks @smithfarm ! Yeah, I (mostly) always follow this practice since you told me (I used `git cp`, which is my alias for `cherry-pick -xsS`), but in this specific case I chose to 'modify' it a bit because the original commit didn't have `Fixes` field and had missing changes (2 missing files that were amended in an unrelated commit of the same PR: 07f28050dba61b851f149a2ed3b63cf5349c04cd), and also there were changes to filenames/locations that made the cherry-picking/backporting not straightforward (not a nightmare but requires some find/grep magic to relocate delta chunks).

Nevertheless, I'll strictly follow these rules next time. Thanks for letting me know!

**Comment by smithfarm** [comment]
@epuertat Thanks. I wouldn't have said a word if you had put the additional information under the original commit message, instead of inside it :-) Happy hacking!

**Pull request merged**
