### PR TITLE
ceph-disk: Add fix subcommand kraken back-port

### PR DESCRIPTION
**Pull request by b-ranto**
http://tracker.ceph.com/issues/19544

This back-ports quite cleanly (the only change is the doc format).

### CODE REVIEW

**Comment by ktdreyer** [comment]
Tracked via http://tracker.ceph.com/issues/19544

**Comment by smithfarm** [comment]
@b-ranto Next time please set the milestone so the PR gets picked up for integration testing.

**Comment by smithfarm** [comment]
@b-ranto Ping? Can you fix the cherry-picks please.

**Comment by smithfarm** [comment]
This passed a ceph-disk suite at http://tracker.ceph.com/issues/19009#note-43

**Comment by b-ranto** [comment]
Redid with the cherry-pick -x.

**Comment by b-ranto** [comment]
jenkins test default

**Comment by smithfarm** [comment]
Jenkins re-test this please

**Comment by b-ranto** [comment]
Jenkins re-test this please

**Pull request merged**
