### PR TITLE
rgw: Should be able to suspend a tenant when the tenant has buckets.

### PR DESCRIPTION
**Pull request by Jing-Scott**
The struct `cls_user_bucket` does not contain tenant of bucket, and the struct `rgw_bucket` need the tenant of bucket if it exists. So when passing the cls_user_bucket to rgw_bucket, we need to add the bucket's tenant.

Fixes: http://tracker.ceph.com/issues/17215
Signed-off-by: Jing Wenjun <jingwenjun@cmss.chinamobile.com>

### CODE REVIEW

**Comment by mattbenjamin** [comment]
@Jing-Scott this looks suspiciously like masking the root cause of a problem, though apologies in advance if I'm mistaken.  Will bring up in today's RGW standup.

In addition, the rationale above should be in the commit message, since that will form the permanent record.

**Comment by Jing-Scott** [comment]
@mattbenjamin I have thought it before. The struct cls_user_bucket, as it defines, that does not need to contain the tenant info of bucket, but in the struct rgw_bucket should be needed. Because the bucket name of tenant in pool .rgw.data.root is like "tenant_name/bucket_name" which is different from the user's bucket. This function rgw_read_user_buckets is the root for rgw to get users' buckets.

**Comment by Jing-Scott** [comment]
@mattbenjamin 
I have added the rationale to the commit message. Please check it. Thanks. ^_^

**Comment by yehudasa** [comment]
@Jing-Scott @mattbenjamin I see a few options in handling this case. 1. make sure that the tenant is string encoded on the buckets list (e.g., tenant:bucket). Since this is not the case (so it seems) it's going to be a problem with backward compatibility. 2. Add a new tenant field (then if the tenant field is not encoded in the structure we can revert to (3) 3. Force user's tenant on the bucket.

(3) seems like a good enough work around for now, but in the future if we'd want to allow cross-tenant buckets ownership we'll need to move to (2).

**Comment by Jing-Scott** [comment]
@yehudasa @mattbenjamin Thanks for your analysis. I have updated the commit . Please check it. ^_^

**Comment by dachary** [comment]
jenkins test this please (osd-scrub-repair.sh http://tracker.ceph.com/issues/17830)

**Comment by Jing-Scott** [comment]
@oritwas Could you help to review it. Thanks!

**Comment by rzarzynski** [comment]
It looks the inability to suspend a tenant is yet another manifestation of the same issue which caused also:
* http://tracker.ceph.com/issues/18364,
* http://tracker.ceph.com/issues/16355.

It has been fixed in 871e1f51afe9d6c8b88debc07460b4316121f999 (PR #13220). I'm going to close this one.

**Pull request closed without merging**
