### PR TITLE
rgw/file: make setattr(...) a no-op on buckets

### PR DESCRIPTION
**Pull request by mattbenjamin**
## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Review by dang — APPROVED** [review]
I can agree with this.  I don't see any attrs that should be settable on a bucket.

**Comment by mattbenjamin** [comment]
in interactive testing, this is working fine

**Comment by mattbenjamin** [comment]
https://pulpito.ceph.com/mbenjamin-2023-07-05_19:54:40-rgw-wip-nochown-bucket-distro-default-smithi/

**Comment by mattbenjamin** [comment]
I think this passed.

**Comment by dang** [comment]
jenkins test api

**Comment by cbodley** [comment]
> I think this passed. The interesting failures don't involve rgw_file: 2023-07-05T20:25:23.601 INFO:teuthology.orchestra.run.smithi110.stdout:ERROR: InvocationError for command /home/ubuntu/cephtest/s3-tests-client.0/.tox/py/bin/pytest -v -m 'not fails_on_rgw and not lifecycle_expiration and not test_of_sts and not webidentity_test and not fails_with_subdomain and not sse_s3 and webidentity_test' (exited with code 5) 2023-07-05T20:25:23.601 INFO:teuthology.orchestra.run.smithi110.stdout:___________________________________ summary ____________________________________ 2023-07-05T20:25:23.601 INFO:teuthology.orchestra.run.smithi110.stdout:ERROR: py: commands failed 2023-07-05T20:25:23.632 DEBUG:teuthology.orchestra.run:got remote process result: 1
> 
> (and logically, doing nothing in the case of a setattr we don't send, can't fail)

👍 yeah, those are known failures. the `InvocationError` should be fixed on main

**Comment by mattbenjamin** [comment]
jenkins retest this please

**Comment by cbodley** [comment]
passed qa in https://pulpito.ceph.com/cbodley-2023-09-29_14:54:02-rgw-wip-cbodley-testing-distro-default-smithi/

**Comment by cbodley** [comment]
@mattbenjamin https://tracker.ceph.com/issues/61689 wasn't tagged for backports, so i moved the status to resolved. if you think this needs backports, please update

**Pull request merged**
