### PR TITLE
Bug fix: ceph.in: connect before ping_monitor

### PR DESCRIPTION
**Pull request by XinzeChi**
Signed-off-by: Xinze Chi <xmdxcxz@gmail.com>

### CODE REVIEW

**Comment by XinzeChi** [comment]
@dmick, @jecluis , please review. Thanks.

**Comment by dachary** [comment]
@XinzeChi could you add a test here also ? It will help backport to firefly. It would also be good to create a bug report for this problem at http://tracker.ceph.com/projects/ceph/issues/new . Would you like to do it ?

**Comment by XinzeChi** [comment]
@dachary, The bug report url : http://tracker.ceph.com/issues/10711.
Add test code. Please review. Thanks.

**Comment by XinzeChi** [comment]
make a mistake in clustet conf.

**Pull request closed without merging**
