### PR TITLE
pacific: mgr/stats: be resilient to offline MDS rank-0

### PR DESCRIPTION
**Pull request by joscollin**
Resolves: https://tracker.ceph.com/issues/54479
Resolves: https://tracker.ceph.com/issues/55338

## Checklist
- [x] References tracker ticket
- [ ] Updates documentation if necessary
- [x] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by joscollin** [comment]
jenkins test make check

**Comment by joscollin** [comment]
jenkins test make check

**Comment by yuriw** [comment]
@joscollin pls rebase

**Comment by joscollin** [comment]
@yuriw Rebased

**Comment by ljflores** [comment]
Rados suite results:
http://pulpito.front.sepia.ceph.com/?branch=wip-yuri-testing-2022-06-06-1014-pacific

Failures, unrelated:
    1. https://tracker.ceph.com/issues/54992
    2. https://tracker.ceph.com/issues/53939
    3. https://tracker.ceph.com/issues/54071
    4. https://tracker.ceph.com/issues/53501
    5. https://tracker.ceph.com/issues/52321
    6. https://tracker.ceph.com/issues/53855
    7. https://tracker.ceph.com/issues/55741
    8. https://tracker.ceph.com/issues/51234 -- pending Pacific backport

Details:
    1. cannot stat '/etc/containers/registries.conf': No such file or directory - Ceph - Orchstrator
    2. ceph-nfs-upgrade, pacific: Upgrade Paused due to UPGRADE_REDEPLOY_DAEMON: Upgrading daemon osd.0 on host smithi103 failed - Ceph - Orchestrator
    3. rados/cephadm/osds: Invalid command: missing required parameter hostname(<string>) - Ceph - Orchestrator
    4. Exception when running 'rook' task. - Ceph - Orchestrator
    5. qa/tasks/rook times out: 'check osd count' reached maximum tries (90) after waiting for 900 seconds - Ceph - Orchestrator
    6. rados/test.sh hangs while running LibRadosTwoPoolsPP.ManifestFlushDupCount - Ceph - RADOS
    7. cephadm/test_dashboard_e2e.sh: Unable to find element `cd-modal .custom-control-label` when testing on orchestrator/01-hosts.e2e-spec.ts - Ceph - Mgr - Dashboard
    8. LibRadosService.StatusFormat failed, Expected: (0) != (retry), actual: 0 vs 0 - Ceph - RADOS

**Review by ljflores — APPROVED** [review]

**Comment by joscollin** [comment]
@yuriw @ljflores 
This PR mainly needs an fs suite run and verify the `TestMDSMetrics` tests.

**Pull request merged**
