### PR TITLE
[DNM] jewel: snap trim blocked behind ec read, never woken, on kraken-x upgrade

### PR DESCRIPTION
**Pull request by shinobu-x**
http://tracker.ceph.com/issues/19208

### CODE REVIEW

**Comment by smithfarm** [comment]
@shinobu-x Could you cherry-pick 70be0db4 first, then 9931798 should apply without conflict?

This way, I don't think the new code gets triggered at all.

**Comment by smithfarm** [comment]
@shinobu-x Nevermind, not clear whether 70be0db can be backported reasonably. This one needs a developer I think.

**Comment by shinobu-x** [comment]
@smithfarm Got it.

**Comment by smithfarm** [comment]
Replaced by #16015

**Pull request closed without merging**
