### PR TITLE
Add rpm conditionals

### PR DESCRIPTION
**Pull request by osynge**
Extracted condionals from SUSE rpm spec fiel to forward port.
Original work done by Thorsten Behrens <tbehrens@suse.com>

Signed-off-by: Owen Synge <osynge@suse.com>

### CODE REVIEW

**Comment by osynge** [comment]
I will change all the conditionals to your recommended value. I was salvaging code as we change workflow.

**Comment by osynge** [comment]
@tchaikov 
I hope I have made the changes changes as recommended.

**Comment by tchaikov** [comment]
>I hope I have made the changes changes as recommended.

@osynge looks good to me. but @ktdreyer is the expert in this area. let's what his call is.

**Comment by ktdreyer** [comment]
This is great, thanks for submitting.

My preference is that first PR should default each of the conditionals to "`%bcond_with`", since that preserves the current behavior of the packaging. A second PR could selectively disable them by default, and that "disable by default" change could be coordinated with the relevant ceph infrastructure changes to turn them back on inside gitbuilder/jenkins/whatever.

It would also be nice to see each of these conditionals broken out into individual commits so they are easier to review/bisect if necessary.

**Comment by ktdreyer** [comment]
I re-read the discussion above and noticed "...I will change all the conditionals to your recommended value" ... maybe GitHub swallowed some previous discussion there that I missed?

**Comment by tchaikov** [comment]
> maybe GitHub swallowed some previous discussion there that I missed?

@ktdreyer github swallowed some inline comments, no idea how to get them back or visit them again...

@osynge just noticed that you have some typos  in your commit message. =)

> condionals from SUSE rpm spec fiel

**Comment by osynge** [comment]
@ktdreyer 
@tchaikov 

To get comments on a previous revision click on the github hash to see comments on an old version.

@tchaikov 

Will fix the typos in the commit message now.

**Comment by osynge** [comment]
@ktdreyer 

Also split into 4 patches as you requested.

**Comment by ktdreyer** [comment]
> To get comments on a previous revision click on the github hash to see comments on an old version.

That's the problem, I don't see a link to the github hash? Mind pasting the URL(s)? Or walking me through how to find them myself? :)

**Comment by osynge** [comment]
Sorry I cant find the old hash too.

**Comment by ktdreyer** [comment]
That's ok. Would you mind changing the defaults from "`%bcond_without`" to "`%bcond_with`", in that case? And open a second PR for the defaults change? (Unless someone else remembers the earlier discussion about defaults?)

**Comment by osynge** [comment]
@ktdreyer I am happy to make the changes.

Sorry for asking you to spell this out, but what should the second PR contain, the same content but with all conditionals set to "%bcond_with" ?

**Comment by tchaikov** [comment]
@ktdreyer i remember them, i asked @osynge to change this way. because if we use `%bcond_with` for all the added conditionals, some of the default behaviour will be changed.

- cephfs_java is enabled by default: by adding an `%bcond_with` will disable it by default.

the same applies to tcmalloc and libs_compat.

**Comment by ktdreyer** [comment]
Wow, my apologies guys. I re-read the docs regarding `%bcond_with`, and now I see that you're correct - the current settings do not imply a behavior change. I misunderstood that. Thanks for clarifying, Kefu.

**Comment by ktdreyer** [comment]
I've pushed this to https://github.com/ceph/ceph/tree/wip_suse_forward_conditionals in order to check it on the gitbuilders; if the build looks good we can merge

**Comment by tchaikov** [comment]
sorry @ktdreyer! thought you were asking for the comments just out of curiosity so i didn't replied you with what we are discussing. =( but until just now i found that you needed them for some other reasons =)

**Comment by osynge** [comment]
@tchaikov @ktdreyer let me know if I need to do more for this patch please :)

**Comment by tchaikov** [comment]
@osynge the build is well ... yellow. so we can merge this pr. but before that, could you rebase it against master?

**Comment by osynge** [comment]
@tchaikov shoudl now be rebased :)

**Comment by tchaikov** [comment]
pushed to wip_suse_forward_conditionals again. so @ktdreyer can check it when he's back.

**Comment by ktdreyer** [comment]
gitbuilder looks good: http://gitbuilder.ceph.com/ceph-rpm-centos7-x86_64-basic/ref/wip_suse_forward_conditionals/x86_64/

merging

**Pull request merged**
