### PR TITLE
doc/cephadm: Added ssh-key import possibility

### PR DESCRIPTION
**Pull request by mohnewald**
Added ssh-key import possibility by using ceph config-key set mgr/cephadm/ssh_identity_key or ceph config-key set mgr/cephadm/ssh_identity_pub

### CODE REVIEW

**Comment by sebastian-philipp** [comment]
please add a DCO by running

```
git checkout patch-1
git commit --amend -s
git push -f

**Comment by mohnewald** [comment]
Signed-off-by: Mario Ohnewald <mario@ohnewald.net>

**Comment by sebastian-philipp** [comment]
Sorry, but you'll need to find a way to add 

```
Signed-off-by: mohnewald <mario@ohnewald.net>
```

to your commit message

**Comment by sebastian-philipp** [comment]
@zdover23 you want to take this PR?

**Comment by zdover23** [comment]
https://github.com/ceph/ceph/pull/35504 supersedes this PR.

The doc that this was meant to update has been refactored into other documents.

After conference with @sebastian-philipp, I decided to close this PR and open the one listed above. mohnewald has been credited in that PR for the material here suggested.

**Pull request closed without merging**
