### PR TITLE
rbd-mirror: quiesce in-flight event commits before shut down

### PR DESCRIPTION
**Pull request by dillaman**

### CODE REVIEW

**Comment by trociny** [comment]
@dillaman Could you please rebase when you have time?

**Comment by dillaman** [comment]
@trociny rebased and pushed

**Comment by trociny** [comment]
lgtm

**Comment by trociny** [comment]
@dillaman I missed that some tests (fsx) got stuck in the teuthology queue, and only today I received the result. One of the fsx tests, which uses journaling, fails when calling `journaler.register_client()`:

http://qa-proxy.ceph.com/teuthology/trociny-2016-09-28_07:53:36-rbd-wip-mgolub-testing---basic-vps/442458/teuthology.log
```
2016-09-28T10:20:05.702 INFO:teuthology.orchestra.run.vpm031.stderr:/srv/autobuild-ceph/gitbuilder.git/build/out~/ceph-11.0.0-2752-g5a03650/src/common/AsyncOpTracker.cc: In function 'AsyncOpTracker::~AsyncOpTracker()' thread 7f03aa415380 time 2016-09-28 10:20:05.700397
2016-09-28T10:20:05.702 INFO:teuthology.orchestra.run.vpm031.stderr:/srv/autobuild-ceph/gitbuilder.git/build/out~/ceph-11.0.0-2752-g5a03650/src/common/AsyncOpTracker.cc: 14: FAILED assert(m_pending_ops == 0)
2016-09-28T10:20:05.702 INFO:teuthology.orchestra.run.vpm031.stderr: ceph version v11.0.0-2752-g5a03650 (5a036504a18c12f3d400c2c1dbe556ebfca6f75e)
2016-09-28T10:20:05.702 INFO:teuthology.orchestra.run.vpm031.stderr: 1: (ceph::__ceph_assert_fail(char const*, char const*, int, char const*)+0x8b) [0x7f03aa0c405b]
2016-09-28T10:20:05.703 INFO:teuthology.orchestra.run.vpm031.stderr: 2: (()+0x143e82) [0x7f03aa0bfe82]
2016-09-28T10:20:05.703 INFO:teuthology.orchestra.run.vpm031.stderr: 3: (journal::JournalMetadata::~JournalMetadata()+0x56) [0x7f03aa096416]
2016-09-28T10:20:05.703 INFO:teuthology.orchestra.run.vpm031.stderr: 4: (journal::JournalMetadata::~JournalMetadata()+0x9) [0x7f03aa0965e9]
2016-09-28T10:20:05.703 INFO:teuthology.orchestra.run.vpm031.stderr: 5: (RefCountedObject::put()+0xe7) [0x7f03aa087207]
2016-09-28T10:20:05.703 INFO:teuthology.orchestra.run.vpm031.stderr: 6: (journal::Journaler::~Journaler()+0x24) [0x7f03aa088b44]
2016-09-28T10:20:05.703 INFO:teuthology.orchestra.run.vpm031.stderr: 7: (()+0xfbaf5) [0x7f03aa077af5]
2016-09-28T10:20:05.704 INFO:teuthology.orchestra.run.vpm031.stderr: 8: (create_image()+0x137) [0x7f03aa077d27]
2016-09-28T10:20:05.704 INFO:teuthology.orchestra.run.vpm031.stderr: 9: (main()+0x6fd) [0x7f03aa072a9d]
2016-09-28T10:20:05.704 INFO:teuthology.orchestra.run.vpm031.stderr: 10: (__libc_start_main()+0xf5) [0x7f039665af45]
2016-09-28T10:20:05.704 INFO:teuthology.orchestra.run.vpm031.stderr: 11: (()+0xf8c13) [0x7f03aa074c13]
```

It look it should wait for journal metadata async_notify_update to complete before completing the context.  What do you think about this PR #11257?

**Pull request merged**
