### PR TITLE
ExclusiveArch for openSUSE

### PR DESCRIPTION
**Pull request by michelmno**

### CODE REVIEW

**Comment by michelmno** [comment]
@smithfarm  the master branch upstream has missing changes versus OBS, so not sure I should base my work on it.  any suggestion ?

**Comment by michelmno** [comment]
I understand what to do for the the signed-off, but waiting for other comments before to pursue

**Comment by smithfarm** [comment]
@michelmno Yes, the changes will need to be backported to jewel and cherry-picked to our downstream branch, but I can take care of that.

The best way to proceed IMO is to open a tracker ticket for each change, and open one PR for each tracker ticket. That way each change can be reviewed separately and we hopefully won't get too confused.

To start with, I opened http://tracker.ceph.com/issues/16936 for the ExclusiveArch.

Can you go ahead an open a ticket for the LTTng change? Registration on http://tracker.ceph.com is easy and you automatically get enough permissions to open a ticket.

Then, in the git commit message, include a line (immediately preceding `Signed-off-by:`) that says

```
Fixes: http://tracker.ceph.com/issues/$ISSUE_NUMBER
```

Please open a tracker ticket at http://tracker.ceph.com

**Comment by smithfarm** [comment]
@michelmno While you're adding Signed-off-by, please add the `Fixes:` line to the ExclusiveArch commit as well.

**Comment by smithfarm** [comment]
It would be preferable to have the ExclusiveArch commit here, and the LTTng-ust commit in the other PR.

**Comment by smithfarm** [comment]
oh... I see you're opening PRs from your master branch. You'll need to make a wip branch for each PR. For example:

```
git remote add ceph git://github.com/ceph/ceph
git fetch ceph
git checkout -b wip-16936 ceph/master
(add commit fixing  http://tracker.ceph.com/issues/16936 )
git push -u origin wip-16936
(open PR)
```

**Comment by michelmno** [comment]
as suggested I am tracking related changes in two different PR, in fact creating two new ones and closing this first one.

http://tracker.ceph.com/issues/16936  about ExclusiveArch
https://github.com/ceph/ceph/pull/10594

http://tracker.ceph.com/issues/16937 about lttng for openSUSE
https://github.com/ceph/ceph/pull/10592

**Pull request closed without merging**
