### PR TITLE
rbd: add ability to rebuild corrupt/missing object maps

### PR DESCRIPTION
**Pull request by dillaman**

### CODE REVIEW

**Comment by jdurgin** [comment]
I'm confused by one thing here, the rest looks good. It makes me wonder if we should optimize the rebuild by accumulating the updates in memory and writing the whole rebuilt object map at once, although the n requests to different objects to check existence are probably slower than n to the object map to update it.

**Comment by dillaman** [comment]
@jdurgin I think my only rationale was just to avoid creating another cls method for writing a ObjectMap received from a client to disk.  I was figuring that there should be very few errors in the object map (since librbd will attempt to keep it in sync even if it is flagged as invalid).  However, for the case where you enable the object map on an image and then rebuild -- this current design would be less than optimal.  Say the word and I'll add the new object_map_save method.

**Comment by jdurgin** [comment]
@dillaman Yeah, I was mainly thinking of the enabling on existing images case, since it's probably already painfully slow to add to many/large images. Since new methods will already be required for dynamic feature enablement, adding another one for faster rebuild doesn't hurt the upgrade story. IOW, go for it.

**Comment by dillaman** [comment]
@jdurgin Sounds good -- I'll get it posted tomorrow.

**Comment by dachary** [comment]
please ignore what seems to be a false negative

**Pull request merged**
