### PR TITLE
mon,osd: do not create rbd pool by default

### PR DESCRIPTION
**Pull request by liewegas**
Fix a zillion tests to make that work.

### CODE REVIEW

**Comment by xiexingguo** [comment]
\o/

**Comment by liewegas** [comment]
retest this pelase

**Comment by liewegas** [comment]
retest this please

**Comment by liewegas** [comment]
retest this please

**Comment by liewegas** [comment]
Need to fix the osd-scrub-repair.sh unit test, and needs final review, but otherwise this is ready to merge!

**Comment by dzafman** [comment]
@liewegas There is a conflict in upmap.t because a new line was added in master and needs what I assume is a change because of the pool number.

ceph osd pg-upmap-items 0.9e 210 209 27 28

**Comment by liewegas** [comment]
Rebased!

**Comment by dzafman** [comment]
@liewegas See https://github.com/ceph/ceph/compare/18e87ee...dzafman:wip-no-default-pool-zafman for 3 more commits for this pull request.  You can skip the one commit that removes the extra log output.

**Comment by liewegas** [comment]
retest this please

**Pull request merged**
