### PR TITLE
squid: rgw: switch back to boost::asio for spawn() and yield_context

### PR DESCRIPTION
**Pull request by liangmingyuanneo**
backport tracker: https://tracker.ceph.com/issues/68400

---

backport of https://github.com/ceph/ceph/pull/55592 and https://github.com/ceph/ceph/pull/57630

Signed-off-by: Mingyuan Liang [liangmingyuan@baidu.com](mailto:liangmingyuan@baidu.com)

### CODE REVIEW

**Comment by liangmingyuanneo** [comment]
@cbodley  merge dependences of https://github.com/ceph/ceph/pull/59708, please review at your time.

**Comment by cbodley** [comment]
https://jenkins.ceph.com/job/ceph-pull-requests/144512/
> Issue with agent

**Review by cbodley — APPROVED** [review]

**Comment by cbodley** [comment]
https://jenkins.ceph.com/job/ceph-pull-requests/144598/
> Issue with agent

**Comment by cbodley** [comment]
jenkins test make check

**Comment by liangmingyuanneo** [comment]
jenkins test make check

**Comment by liangmingyuanneo** [comment]
> jenkins test make check

https://jenkins.ceph.com/job/ceph-pull-requests/144748

> Issue with agent

**Comment by cbodley** [comment]
passed qa in https://pulpito.ceph.com/cbodley-2024-10-09_13:09:48-rgw-wip-68400-distro-default-smithi/

**Pull request merged**
