### PR TITLE
pacific: revival and backport of fix for RocksDB optimized iterators

### PR DESCRIPTION
**Pull request by aclamk**
Revival of: 
https://github.com/ceph/ceph/pull/45963
Backport of:
https://github.com/ceph/ceph/pull/46095

Backport trackers: https://tracker.ceph.com/issues/55518 and https://tracker.ceph.com/issues/55442

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/master/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by neha-ojha** [comment]
jenkins test make check

**Comment by neha-ojha** [comment]
jenkins test make check

**Review by idryomov — APPROVED** [review]
The backport of https://github.com/ceph/ceph/pull/46095 fixes it for my `TestClsJournal` upgrade reproducer.

**Comment by BenoitKnecht** [comment]
This looks great! We're heavily impacted by https://tracker.ceph.com/issues/55324, so I really hope this PR can make it into 16.2.8! :heart:

**Comment by BenoitKnecht** [comment]
I've tested this PR (applied to 16.2.7) on one of our test clusters with a lot of OMAP data. Without this PR, any rebalancing on the OMAP OSDs would lead to terrible performance until we compacted RocksDB to get rid of the tombstones, but with this PR applied, we don't get any performance hit (or small enough that we don't even notice).

**Comment by neha-ojha** [comment]
> I've tested this PR (applied to 16.2.7) on one of our test clusters with a lot of OMAP data. Without this PR, any rebalancing on the OMAP OSDs would lead to terrible performance until we compacted RocksDB to get rid of the tombstones, but with this PR applied, we don't get any performance hit (or small enough that we don't even notice).

Thanks for testing this PR! It will be included in 16.2.8.

**Review by neha-ojha — APPROVED** [review]
Test failures are unrelated https://pulpito.ceph.com/?branch=wip-yuri4-testing-2022-04-29-1830-pacific

**Pull request merged**
