### PR TITLE
jewel: rbd-mirror: snap rename does not properly replicate to peers

### PR DESCRIPTION
**Pull request by dillaman**
http://tracker.ceph.com/issues/16747

### CODE REVIEW

**Comment by dachary** [comment]
Hey jenkins, test this please. unitttest_throttle failed, not sure if it was touched by image-sync throttler though.

**Comment by dachary** [comment]
conflicts with https://github.com/ceph/ceph/pull/10678

**Comment by dachary** [comment]
Hey jenkins, test this please. (bluefs crash)

**Comment by dachary** [comment]
@dillaman could you please rebase ? https://github.com/ceph/ceph/pull/10678 has been merged, hence the conflicts.

**Comment by dillaman** [comment]
@dachary rebased

**Comment by dachary** [comment]
<pre>
CXX      test/rbd_mirror/image_sync/unittest_rbd_mirror-test_mock_SyncPointPruneRequest.o
test/rbd_mirror/image_sync/test_mock_ImageCopyRequest.cc:632:7: error: redefinition of ‘class rbd::mirror::image_sync::TestMockImageSyncImageCopyRequest_EmptySnapSeqs_Test’
 TEST_F(TestMockImageSyncImageCopyRequest, EmptySnapSeqs) {
       ^
test/rbd_mirror/image_sync/test_mock_ImageCopyRequest.cc:610:7: error: previous definition of ‘class 
</pre>

**Comment by dachary** [comment]
Included in https://github.com/ceph/ceph/pull/10684

**Pull request closed without merging**
