### PR TITLE
ceph-volume rollback on failed OSD prepare/create

### PR DESCRIPTION
**Pull request by alfredodeza**
Fixes: http://tracker.ceph.com/issues/22281

### CODE REVIEW

**Comment by andrewschoen** [comment]
jenkins test ceph-volume tox

**Comment by alfredodeza** [comment]
jenkins test ceph-volume lvm centos7-bluestore-create

**Comment by alfredodeza** [comment]
jenkins test ceph-volume lvm centos7-filestore-create

**Comment by alfredodeza** [comment]
jenkins test ceph-volume lvm xenial-bluestore-create

**Comment by alfredodeza** [comment]
jenkins test ceph-volume lvm xenial-filestore-create

**Pull request merged**
