### PR TITLE
rgw: fix linking with tcmalloc when specified by -DALLOCATOR

### PR DESCRIPTION
**Pull request by mkogan1**
Fixes: https://tracker.ceph.com/issues/57140

with
./do_cmake.sh ... -DALLOCATOR=tcmalloc ...

before:
```
❯ ldd ./build/bin/radosgw | grep libtc
```

after:
```
❯ ldd ./build/bin/radosgw | grep libtc
        libtcmalloc.so.4 => /lib64/libtcmalloc.so.4 (0x00007ffff59a0000)
```

Signed-off-by: Mark Kogan <mkogan@redhat.com>

ref og commit: 69a231888e05e4504e20e6a32506ed2a3c48d139

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [x] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by mkogan1** [comment]
jenkins test api

**Review by cbodley — APPROVED** [review]

**Comment by mkogan1** [comment]
teuthology run submitted: https://pulpito.ceph.com/mkogan-2022-08-16_16:41:05-rgw-wip-fix-tcmalloc-link-i01-distro-default-smithi/

**Comment by mkogan1** [comment]
jenkins test windows

**Comment by mkogan1** [comment]
jenkins test make check arm64

**Comment by cbodley** [comment]
thanks @mkogan1, i'm looking through the results and see lots of crashes on startup in the centos jobs:
```
2022-08-16T21:36:41.409 INFO:tasks.rgw.client.0.smithi165.stdout:terminate called after throwing an instance of 'std::bad_variant_access'
2022-08-16T21:36:41.410 INFO:tasks.rgw.client.0.smithi165.stdout:  what():  std::get: wrong index for variant
2022-08-16T21:36:41.410 INFO:tasks.rgw.client.0.smithi165.stdout:*** Caught signal (Aborted) **
2022-08-16T21:36:41.410 INFO:tasks.rgw.client.0.smithi165.stdout: in thread 7fda1019b600 thread_name:radosgw
2022-08-16T21:36:41.411 INFO:tasks.rgw.client.0.smithi165.stdout: ceph version 17.0.0-14275-g51fa3187 (51fa31878e792669fc5aadc3b71b57313796d1f1) quincy (dev)
2022-08-16T21:36:41.412 INFO:tasks.rgw.client.0.smithi165.stdout: 1: /lib64/libpthread.so.0(+0x12ce0) [0x7fda161f9ce0]
2022-08-16T21:36:41.412 INFO:tasks.rgw.client.0.smithi165.stdout: 2: gsignal()
2022-08-16T21:36:41.412 INFO:tasks.rgw.client.0.smithi165.stdout: 3: abort()
2022-08-16T21:36:41.412 INFO:tasks.rgw.client.0.smithi165.stdout: 4: /lib64/libstdc++.so.6(+0x9009b) [0x7fda1594009b]
2022-08-16T21:36:41.413 INFO:tasks.rgw.client.0.smithi165.stdout: 5: /lib64/libstdc++.so.6(+0x9653c) [0x7fda1594653c]
2022-08-16T21:36:41.413 INFO:tasks.rgw.client.0.smithi165.stdout: 6: /lib64/libstdc++.so.6(+0x96597) [0x7fda15946597]
2022-08-16T21:36:41.413 INFO:tasks.rgw.client.0.smithi165.stdout: 7: /lib64/libstdc++.so.6(+0x967f8) [0x7fda159467f8]
2022-08-16T21:36:41.413 INFO:tasks.rgw.client.0.smithi165.stdout: 8: (std::__throw_bad_variant_access(bool)+0) [0x5558a52a2506]
2022-08-16T21:36:41.414 INFO:tasks.rgw.client.0.smithi165.stdout: 9: (void boost::throw_exception<boost::bad_function_call>(boost::bad_function_call const&)+0) [0x5558a52a252a]
2022-08-16T21:36:41.414 INFO:tasks.rgw.client.0.smithi165.stdout: 10: radosgw(+0x559a77) [0x5558a52f5a77]
2022-08-16T21:36:41.414 INFO:tasks.rgw.client.0.smithi165.stdout: 11: main()
```
i recognize these from https://tracker.ceph.com/issues/57050#note-2, which i saw in one of @dang's runs before we merged https://github.com/ceph/ceph/pull/47504

**Comment by cbodley** [comment]
i'm seeing the same crashes in another branches too, so it's not caused by this pr. http://qa-proxy.ceph.com/teuthology/cbodley-2022-08-18_23:33:15-rgw-wip-cbodley-testing-distro-default-smithi/6979641/teuthology.log

**Comment by cbodley** [comment]
i opened https://tracker.ceph.com/issues/57195 to track that crash. because it isn't caused by this PR, i think it's okay to merge

**Pull request merged**
