### PR TITLE
pacific: mgr/dashboard: Pull latest translations from Transifex

### PR DESCRIPTION
**Pull request by votdev**
Get the latest translations for Pacific from Transifex. This can also be used as backup to be able to restore them on Transifex if necessary.

Signed-off-by: Volker Theile <vtheile@suse.com>

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [x] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by votdev** [comment]
Our translation team at SUSE will translate all missing messages for Pacific soon. To do so, we need to update the messages on Transifex beforehand with the outcome of `npm run i18n:extract` of the current Pacific branch. To be able to restore the data on Transifex this PR will backup the translation dictionary to be on the safe side and to have the currently up-to-date translations in the Dashboard.

**Comment by votdev** [comment]
How to find out what is going on with the `visualTests/dashboard.vrt-spec.ts` without having access to `applitools.com`? Isn't there a way to make the results public to everyone when the Ceph project really need to use proprietary tools?

**Comment by votdev** [comment]
FYI, the translation source file for Pacific has been updated on Transifex today.

**Comment by votdev** [comment]
jenkins test dashboard

**Comment by votdev** [comment]
jenkins test dashboard

**Comment by votdev** [comment]
jenkins test dashboard

**Comment by votdev** [comment]
Applitools fail again. Can we get rid of them please.

**Comment by votdev** [comment]
jenkins test dashboard

**Comment by votdev** [comment]
jenkins test dashboard

**Comment by nizamial09** [comment]
jenkins test dashboard

**Review by nizamial09 — APPROVED** [review]

**Comment by votdev** [comment]
jenkins test dashboard

**Review by s0nea — APPROVED** [review]

**Comment by s0nea** [comment]
jenkins test dashboard

**Pull request merged**
