### PR TITLE
rgw: The rgw_bucket overload <operator, need to consider bucket_id

### PR DESCRIPTION
**Pull request by xxcs**
Fixes: https://tracker.ceph.com/issues/42614
Signed-off-by: GaryHyg huygbj@inspur.com

detail:
   1. src/rgw/rgw_quota.cc：RGWUserStatsCache.modified_buckets(map<rgw_bucket, rgw_user>)
   2.map.find uses the < operator

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by mattbenjamin** [comment]
I suspect we were purposely omitting bucket_id;  incorrectly?

**Comment by xxcs** [comment]
> I suspect we were purposely omitting bucket_id; incorrectly?

There will be a problem in the following situations：
1. Create a bucket
2. Upload object
3. Delete the bucket
4. Create a bucket for same name
5. Upload object
result:
"radosgw-admin user stats --tenant=[] --uid=[]" has never been updated
cause:
map.find uses <operator to ...

**Comment by cbodley** [comment]
thanks, this is obviously correct but let's make sure the test suite doesn't uncover anything that was relying on this behavior

**Comment by GaryHyg** [comment]
just for removing the stale label.

**Comment by ivancich** [comment]
@xxcs Sorry this has taken so long to test. Now it requires a rebase due to a recent commit.

**Comment by xxcs** [comment]
> @xxcs Sorry this has taken so long to test. Now it requires a rebase due to a recent commit.



> @xxcs Sorry this has taken so long to test. Now it requires a rebase due to a recent commit.



> @xxcs Sorry this has taken so long to test. Now it requires a rebase due to a recent commit.

The structure rgw_bucket has been moved from rgw_common.h to rgw_basic_types.h, this problem has been solved.

**Comment by ivancich** [comment]
@xxcs Thank you for the rebase. Jenkins is complaining about an unsigned commit. And I don't see any backports listed on the tracker. Since this appears to be a bug, I would think backports are appropriate.

**Comment by tchaikov** [comment]
retest this please

**Comment by ivancich** [comment]
Teuthology results -- no regressions noted:
* http://pulpito.ceph.com/ivancich-2020-09-02_13:40:42-rgw-wip-eric-testing-2-distro-basic-smithi/
* http://pulpito.ceph.com/ivancich-2020-09-02_13:41:02-rgw-wip-eric-testing-2-distro-basic-smithi/

**Comment by ivancich** [comment]
@xxcs @cbodley -- No backports are listed in the tracker. Please update the tracker if backports are appropriate.

**Pull request merged**
