### PR TITLE
pacific: cephadm: use ceph/daemon-base:latest-pacific-devel image

### PR DESCRIPTION
**Pull request by sebastian-philipp**
Fixes: https://tracker.ceph.com/issues/49041
Signed-off-by: Sebastian Wagner <sebastian.wagner@suse.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Review by dsavineau — COMMENTED** [review]
Don't we need to update the `container_image` option default value too ?

https://github.com/ceph/ceph/blob/master/src/common/options.cc#L456-L459

**Comment by sebastian-philipp** [comment]
nice catch

**Comment by liewegas** [comment]
In master I switched this to pull from quay.ceph.io/ceph-ci:master etc.  My long term goal is to switch to move away from the older tags pushed to docker hub.

**Comment by sebastian-philipp** [comment]
> In master I switched this to pull from quay.ceph.io/ceph-ci:master etc. My long term goal is to switch to move away from the older tags pushed to docker hub.

for pacific, I'd be :+1: to move to quay as soon as we have moved the official images to quay.

**Review by jmolmo — APPROVED** [review]
What a pity not to have merged yet:
https://github.com/ceph/ceph/pull/38881
It only would be needed to change the DEFAULT_CEPH_IMAGE ....

LGTM

**Comment by sebastian-philipp** [comment]
cepham tests passed:  https://pulpito.ceph.com/swagner-2021-02-09_10:28:14-rados:cephadm-wip-swagner2-testing-2021-02-08-1109-pacific-distro-basic-smithi/

Failures: 

* https://tracker.ceph.com/issues/49232
* https://tracker.ceph.com/issues/49233

**Pull request merged**
