### PR TITLE
luminous: mon: cluster limit on pgs

### PR DESCRIPTION
**Pull request by liewegas**

### CODE REVIEW

**Comment by jdurgin** [comment]
retest this please

**Comment by jdurgin** [comment]
retest this please

**Comment by liewegas** [comment]
http://pulpito.ceph.com/sage-2017-10-03_12:00:34-rados-wip-sage-testing2-2017-10-02-2121-distro-basic-smithi/

**Comment by shinobu-x** [comment]
@liewegas Now I got you :)

**Pull request merged**
