### PR TITLE
luminous: mds: disallow dumping huge caches to formatter

### PR DESCRIPTION
**Pull request by vshankar**
http://tracker.ceph.com/issues/37608

### CODE REVIEW

**Comment by vshankar** [comment]
Apart from the trivial conflict, the config option type needed fixing as commit 7c25de3799d (which introduces `TYPE_SIZE`) is not in luminous.

**Comment by smithfarm** [comment]
@vshankar Thanks for the nice explanation of how you did the backport - could you put it in the commit message itself, under the Conflicts section?

**Comment by vshankar** [comment]
done

**Comment by yuriw** [comment]
[wip-yuri5-testing-2019-01-04-1743-luminous](https://trello.com/c/qvVpuIUM/500-wip-yuri5-testing-2019-01-04-1743-luminous)

**Comment by vshankar** [comment]
Reviewed-by: Venky Shankar <vshankar@redhat.com>

**Pull request merged**
