### PR TITLE
ceph-volume/migrate: fix make_new_volume()

### PR DESCRIPTION
**Pull request by guits**
Typical error encountered:
```
stderr: Might need DB size specification, please set Ceph bluestore-block-db-size config parameter
```

This wasn't required until pacific. Something must have changed as of Quincy.

Fixes: https://tracker.ceph.com/issues/55260

Signed-off-by: Guillaume Abrioux <gabrioux@redhat.com>

### CODE REVIEW

**Comment by guits** [comment]
jenkins test ceph-volume tox

**Comment by guits** [comment]
jenkins test ceph-volume tox

**Comment by guits** [comment]
jenkins test ceph-volume tox

**Comment by guits** [comment]
jenkins test ceph-volume all

**Comment by guits** [comment]
jenkins test ceph-volume all

**Comment by guits** [comment]
jenkins test make check arm64

**Comment by guits** [comment]
jenkins test ceph-volume all

**Comment by djgalloway** [comment]
jenkins test ceph-volume all

**Comment by djgalloway** [comment]
jenkins test ceph-volume all

**Comment by guits** [comment]
jenkins test ceph-volume lvm centos8-filestore-create

**Comment by guits** [comment]
jenkins test ceph-volume lvm centos8-filestore-create

**Comment by ifed01** [comment]
Alternative fix for "stderr: Might need DB size specification, please set Ceph bluestore-block-db-size config parameter" is included in https://github.com/ceph/ceph/pull/50427

**Comment by ifed01** [comment]
Yet another alternative fix is at https://github.com/ceph/ceph/pull/52193

**Comment by guits** [comment]
closing this one in favor of #52193

**Pull request closed without merging**
