### PR TITLE
ceph-volume: check if we run in an selinux environment

### PR DESCRIPTION
**Pull request by jan--f**
We can't assume SELinux binaries are present. This fixes error handling in such cases. Introduced by 33c8a64a54d9ea8962091caf8564cea3f603c5f5

Fixes: https://tracker.ceph.com/issues/42957

### CODE REVIEW

**Comment by jan--f** [comment]
jenkins test ceph-volume all

**Comment by jan--f** [comment]
jenkins test ceph-volume all

**Comment by alfredodeza** [comment]
Good catch @jan--f

**Comment by alfredodeza** [comment]
On Python 2.7 it will not raise FileNotFoundError it will raise OSError... maybe we want to add onto this and try/catch both?

**Comment by alfredodeza** [comment]
I should've tried that before merging :)

**Comment by jan--f** [comment]
Wondering why tox did not hit that...

**Comment by alfredodeza** [comment]
It didn't hit it because the test is adding `FileNotFoundError` only, it isn't really trying to call out a non-existing executable which would raise `OSError` in Python 2.7

The test correctly checks for handling the former, it doesn't check for the latter

**Comment by badone** [comment]
See https://tracker.ceph.com/issues/42967 for undefined FileNotFoundError on python2

**Pull request merged**
