### PR TITLE
mds: Remove unused declaration of the function

### PR DESCRIPTION
**Pull request by kotreshhr**
Signed-off-by: Kotresh HR <khiremat@redhat.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [x] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Review by dparmar18 — APPROVED** [review]

**Review by rishabh-d-dave — APPROVED** [review]
Any idea why this is unused? Maybe we should check that to avoid potential bug in future and a add note for it to the commit message?

**Comment by rishabh-d-dave** [comment]
jenkins test make check arm64

**Comment by kotreshhr** [comment]
> Any idea why this is unused? Maybe we should check that to avoid potential bug in future and a add note for it to the commit message?

The following commit adds it. I see that only declaration is added while modifying `link_remote` routine of `CDentry` class.

```
git show 4f3a2885cc47
...
...
diff --git a/src/mds/CDentry.h b/src/mds/CDentry.h
index 67c2b5753c0..5c6ec5bd190 100644
--- a/src/mds/CDentry.h
+++ b/src/mds/CDentry.h
@@ -109,6 +109,7 @@ public:
       remote_d_type = d_type;
       inode = 0;
     }
+    void link_remote(CInode *in);
   };
   
 protected:
@@ -233,8 +234,8 @@ public:
   void adjust_nested_anchors(int by);
 
   // remote links
-  void link_remote(CInode *in);
-  void unlink_remote();
+  void link_remote(linkage_t *dnl, CInode *in);
+  void unlink_remote(linkage_t *dnl);
...
...
```

**Comment by rishabh-d-dave** [comment]
https://tracker.ceph.com/projects/cephfs/wiki/Main#31-Mar-2023

**Pull request merged**
