### PR TITLE
common: fix insert empty ptr when bufferlist rebuild

### PR DESCRIPTION
**Pull request by XinzeChi**
This bug may would cause that some ptr defined in bufferlist would be emtpy.
 When use `buffer::list::iterator::copy(unsigned len, char *dest)`
it may `assert(p->length() > 0); `

the test case as:
`https://github.com/XinzeChi/ceph/commit/5d6af86df83c523dab2fabc0caeab98dd14ba31c`

### CODE REVIEW

**Comment by liewegas** [comment]
Shouldn't the rebuild() method exit if _len == 0?  Otherwise we're calling the buffer create with len 0.

**Comment by XinzeChi** [comment]
@liewegas , Yah, when _len == 0, we only _buffers.clear() and return.

**Comment by liewegas** [comment]
lgtm, thanks!

**Comment by tchaikov** [comment]
:+1:

**Comment by XinzeChi** [comment]
@tchaikov , I agree with you. Thanks.

**Pull request merged**
