### PR TITLE
rgw/sts: correcting documentation errors.

### PR DESCRIPTION
**Pull request by pritha-srivastava**
Signed-off-by: Pritha Srivastava <prsrivas@redhat.com>

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [x] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [x] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by pritha-srivastava** [comment]
jenkins render docs

**Review by mattbenjamin — APPROVED** [review]
ok

**Comment by pritha-srivastava** [comment]
jenkins render docs

**Comment by pritha-srivastava** [comment]
jenkins render docs

**Comment by pritha-srivastava** [comment]
jenkins render docs

**Comment by pritha-srivastava** [comment]
jenkins render docs

**Review by anthonyeleven — APPROVED** [review]

**Comment by mattbenjamin** [comment]
unstale

**Comment by anthonyeleven** [comment]
I updated the checklist on this old PR so that it will pass the checklist check, which now requires a different format than was in force at the time of original submission.

**Comment by anthonyeleven** [comment]
jenkins render docs

**Comment by anthonyeleven** [comment]
jenkins test docs

**Comment by frittentheke** [comment]
unstale

**Comment by zdover23** [comment]
I'm going to merge this into main so that I can repair the rendering errors that are preventing the "Docs: render build" from succeeding. A later comment on this conversation page will link to the PR that will repair the rendering errors.

**Comment by zdover23** [comment]
https://github.com/ceph/ceph/pull/50186 

https://github.com/ceph/ceph/pull/50186 repairs the link in this PR that was intended to direct the reader to doc/radosgw/keycloak.rst.

**Pull request merged**
