### PR TITLE
reef: qa: fixing tests in test_cephfs_shell.TestShellOpts

### PR DESCRIPTION
**Pull request by neesingh-rh**
backport tracker: https://tracker.ceph.com/issues/65348

backport of https://github.com/ceph/ceph/pull/55725
parent tracker: https://tracker.ceph.com/issues/63699

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [x] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Comment by joscollin** [comment]
This PR is under test in [https://tracker.ceph.com/issues/66685](https://tracker.ceph.com/issues/66685).

**Comment by lxbsz** [comment]
@neesingh-rh I am afraid this PR caused this [qa test failure](https://pulpito.ceph.com/jcollin-2024-06-26_02:20:03-fs-wip-jcollin-testing-20240625.103903-reef-distro-default-smithi/7772681) , could you help confirm that ?

**Comment by neesingh-rh** [comment]
> @neesingh-rh I am afraid this PR caused this [qa test failure](https://pulpito.ceph.com/jcollin-2024-06-26_02:20:03-fs-wip-jcollin-testing-20240625.103903-reef-distro-default-smithi/7772681) , could you help confirm that ?

Will check

**Comment by neesingh-rh** [comment]
> @neesingh-rh I am afraid this PR caused this [qa test failure](https://pulpito.ceph.com/jcollin-2024-06-26_02:20:03-fs-wip-jcollin-testing-20240625.103903-reef-distro-default-smithi/7772681) , could you help confirm that ?
I did check the log you mentioned above and seeing the output structure of `set editor` command it looks like we don't need this change for reef. 
Earlier, we decided that this shouldn't go for reef as it exists only for centos9 https://tracker.ceph.com/issues/65348#note-2 but after this https://tracker.ceph.com/issues/65348#note-4 I created this PR. 
@joscollin Can u pls re-look to this run https://pulpito.ceph.com/leonidus-2024-06-16_14:17:14-fs-wip-leonidus-testing-20240616.070940-reef-distro-default-smithi/7758404 , what caused this failure.

**Comment by lxbsz** [comment]
> > @neesingh-rh I am afraid this PR caused this [qa test failure](https://pulpito.ceph.com/jcollin-2024-06-26_02:20:03-fs-wip-jcollin-testing-20240625.103903-reef-distro-default-smithi/7772681) , could you help confirm that ?
> 
> I did check the log you mentioned above and seeing the output structure of `set editor` command it looks like we don't need this change for reef. Earlier, we decided that this shouldn't go for reef as it exists only for centos9 https://tracker.ceph.com/issues/65348#note-2 but after this https://tracker.ceph.com/issues/65348#note-4 I created this PR. @joscollin Can u pls re-look to this run https://pulpito.ceph.com/leonidus-2024-06-16_14:17:14-fs-wip-leonidus-testing-20240616.070940-reef-distro-default-smithi/7758404 , what caused this failure.

In reef we hit this too, please see https://pulpito.ceph.com/jcollin-2024-07-02_01:59:44-fs-wip-jcollin-testing-20240701.083303-reef-distro-default-smithi/7783233

**Comment by neesingh-rh** [comment]
> > > @neesingh-rh I am afraid this PR caused this [qa test failure](https://pulpito.ceph.com/jcollin-2024-06-26_02:20:03-fs-wip-jcollin-testing-20240625.103903-reef-distro-default-smithi/7772681) , could you help confirm that ?
> > 
> > 
> > I did check the log you mentioned above and seeing the output structure of `set editor` command it looks like we don't need this change for reef. Earlier, we decided that this shouldn't go for reef as it exists only for centos9 https://tracker.ceph.com/issues/65348#note-2 but after this https://tracker.ceph.com/issues/65348#note-4 I created this PR. @joscollin Can u pls re-look to this run https://pulpito.ceph.com/leonidus-2024-06-16_14:17:14-fs-wip-leonidus-testing-20240616.070940-reef-distro-default-smithi/7758404 , what caused this failure.
> 
> In reef we hit this too, please see https://pulpito.ceph.com/jcollin-2024-07-02_01:59:44-fs-wip-jcollin-testing-20240701.083303-reef-distro-default-smithi/7783233

I don't understand why the output structure of `set editor` is different in two reef runs:
https://pulpito.ceph.com/jcollin-2024-07-02_01:59:44-fs-wip-jcollin-testing-20240701.083303-reef-distro-default-smithi/7783233 :
```2024-07-04T16:39:36.362 INFO:tasks.cephfs.test_cephfs_shell:Running command: cephfs-shell -c /tmp/tmp.fqwx8qBsX3 -- set editor ?, set editor
2024-07-04T16:39:36.362 DEBUG:teuthology.orchestra.run.smithi016:> cephfs-shell -c /tmp/tmp.fqwx8qBsX3 -- 'set editor ?, set editor'
2024-07-04T16:39:36.652 INFO:teuthology.orchestra.run.smithi016.stdout:editor - was: 'vim'
2024-07-04T16:39:36.652 INFO:teuthology.orchestra.run.smithi016.stdout:now: '?'
2024-07-04T16:39:36.652 INFO:teuthology.orchestra.run.smithi016.stdout:Name    Value                           Description
2024-07-04T16:39:36.652 INFO:teuthology.orchestra.run.smithi016.stdout:====================================================================================================
2024-07-04T16:39:36.652 INFO:teuthology.orchestra.run.smithi016.stdout:editor  ?                               Program used by 'edit'
```

and http://qa-proxy.ceph.com/teuthology/jcollin-2024-06-26_02:20:03-fs-wip-jcollin-testing-20240625.103903-reef-distro-default-smithi/7772681/teuthology.log:
```2024-06-29T03:27:59.478 INFO:tasks.cephfs.test_cephfs_shell:Running command: cephfs-shell -c /tmp/tmp.DKVBZHNKyb -- set editor ?, set editor
2024-06-29T03:27:59.478 DEBUG:teuthology.orchestra.run.smithi001:> cephfs-shell -c /tmp/tmp.DKVBZHNKyb -- 'set editor ?, set editor'
2024-06-29T03:27:59.674 INFO:teuthology.orchestra.run.smithi001.stdout:editor - was: vim
2024-06-29T03:27:59.674 INFO:teuthology.orchestra.run.smithi001.stdout:now: ?
2024-06-29T03:27:59.674 INFO:teuthology.orchestra.run.smithi001.stdout:editor: ?
```

**Comment by vshankar** [comment]
Had a conversation with @neesingh-rh regarding this - please check if the upgraded cmd2 module is a part of reef branch and available in the distro's we support.

**Comment by neesingh-rh** [comment]
> > > > @neesingh-rh I am afraid this PR caused this [qa test failure](https://pulpito.ceph.com/jcollin-2024-06-26_02:20:03-fs-wip-jcollin-testing-20240625.103903-reef-distro-default-smithi/7772681) , could you help confirm that ?
> > > 
> > > 
> > > I did check the log you mentioned above and seeing the output structure of `set editor` command it looks like we don't need this change for reef. Earlier, we decided that this shouldn't go for reef as it exists only for centos9 https://tracker.ceph.com/issues/65348#note-2 but after this https://tracker.ceph.com/issues/65348#note-4 I created this PR. @joscollin Can u pls re-look to this run https://pulpito.ceph.com/leonidus-2024-06-16_14:17:14-fs-wip-leonidus-testing-20240616.070940-reef-distro-default-smithi/7758404 , what caused this failure.
> > 
> > 
> > In reef we hit this too, please see https://pulpito.ceph.com/jcollin-2024-07-02_01:59:44-fs-wip-jcollin-testing-20240701.083303-reef-distro-default-smithi/7783233
> 
> I don't understand why the output structure of `set editor` is different in two reef runs: https://pulpito.ceph.com/jcollin-2024-07-02_01:59:44-fs-wip-jcollin-testing-20240701.083303-reef-distro-default-smithi/7783233 :
> 
> ```
> 2024-07-04T16:39:36.362 DEBUG:teuthology.orchestra.run.smithi016:> cephfs-shell -c /tmp/tmp.fqwx8qBsX3 -- 'set editor ?, set editor'
> 2024-07-04T16:39:36.652 INFO:teuthology.orchestra.run.smithi016.stdout:editor - was: 'vim'
> 2024-07-04T16:39:36.652 INFO:teuthology.orchestra.run.smithi016.stdout:now: '?'
> 2024-07-04T16:39:36.652 INFO:teuthology.orchestra.run.smithi016.stdout:Name    Value                           Description
> 2024-07-04T16:39:36.652 INFO:teuthology.orchestra.run.smithi016.stdout:====================================================================================================
> 2024-07-04T16:39:36.652 INFO:teuthology.orchestra.run.smithi016.stdout:editor  ?                               Program used by 'edit'
> ```
> 
> and http://qa-proxy.ceph.com/teuthology/jcollin-2024-06-26_02:20:03-fs-wip-jcollin-testing-20240625.103903-reef-distro-default-smithi/7772681/teuthology.log:
> 
> ```
> 2024-06-29T03:27:59.478 DEBUG:teuthology.orchestra.run.smithi001:> cephfs-shell -c /tmp/tmp.DKVBZHNKyb -- 'set editor ?, set editor'
> 2024-06-29T03:27:59.674 INFO:teuthology.orchestra.run.smithi001.stdout:editor - was: vim
> 2024-06-29T03:27:59.674 INFO:teuthology.orchestra.run.smithi001.stdout:now: ?
> 2024-06-29T03:27:59.674 INFO:teuthology.orchestra.run.smithi001.stdout:editor: ?
> ```

This issue exists only in centos 9, but here http://qa-proxy.ceph.com/teuthology/jcollin-2024-06-26_02:20:03-fs-wip-jcollin-testing-20240625.103903-reef-distro-default-smithi/7772681/teuthology.log along with this patch we are testing it in ubuntu 20.04, that's why it is failing for it.

**Review by vshankar — APPROVED** [review]
https://tracker.ceph.com/projects/cephfs/wiki/Reef#wip-rishabh-testing-20240910100730-reef

**Pull request merged**
