### PR TITLE
kraken: rbd-nbd: check /sys/block/nbdX/size to ensure kernel mapped correctly

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/18910
http://tracker.ceph.com/issues/18970

### CODE REVIEW

**Comment by smithfarm** [comment]
merge conflict in integration branch

**Comment by smithfarm** [comment]
Jenkins retest this please

```
ceph_test_objectstore: /home/jenkins-build/build/workspace/ceph-pull-requests/src/test/objectstore/store_test.cc:3147: virtual void SyntheticWorkloadState::C_SyntheticOnReadable::finish(int): Assertion `bl_eq(state->contents[hoid].data, r2)' failed.
*** Caught signal (Aborted) **
```

**Comment by smithfarm** [comment]
@trociny @dillaman Do you understand the build failure? I'm seeing it in several rbd backports, not just this one.

**Comment by smithfarm** [comment]
It looks like a case of http://tracker.ceph.com/issues/17743

**Comment by trociny** [comment]
@smithfarm Yes the jenkins failure looks unrelated.

**Comment by smithfarm** [comment]
Jenkins re-test this please

**Comment by smithfarm** [comment]
@dillaman @trociny This PR passed an rbd run at http://tracker.ceph.com/issues/19009#note-56 (there were some failures that required a fix - applied via https://github.com/ceph/ceph/pull/16113). Please review/approve the PR if you agree it can be merged.

**Comment by smithfarm** [comment]
This passed another rbd suite at http://tracker.ceph.com/issues/19009#note-66

**Pull request merged**
