### PR TITLE
Add a new tick timer which does not need to hold osd_lock, put sched_scrub to that tick timer

### PR DESCRIPTION
**Pull request by guangyy**
This patch try to fix the lock contention issue mentioned in http://tracker.ceph.com/issues/10183 with the option 2 listed as potential solution in the tracker.

Fixes: #10183
Signed-off-by: Guang Yang <yguang@yahoo-inc.com>

### CODE REVIEW

**Comment by athanatos** [comment]
This seems to cause an osd crash in make check:

At a glance, you need to hold the SafeTimer lock when calling add_event_after.

    -4> 2015-01-07 10:09:13.037208 2b4b5a0373c0 -1 osd.0 0 log_to_monitors {default=true}
    -3> 2015-01-07 10:09:13.037640 2b4b5a0373c0 10 osd.0 0 set_disk_tp_priority class  priority -1
    -2> 2015-01-07 10:09:13.037757 2b4b6720b700 20 osd.0 0 update_osd_stat osd_stat(267 GB used, 179 GB avail, 446 GB total, peers []/[] op hist [])
    -1> 2015-01-07 10:09:13.037777 2b4b6720b700  5 osd.0 0 heartbeat: osd_stat(267 GB used, 179 GB avail, 446 GB total, peers []/[] op hist [])
     0> 2015-01-07 10:09:13.044228 2b4b5a0373c0 -1 common/Timer.cc: In function 'void SafeTimer::add_event_after(double, Context*)' thread 2b4b5a0373c0 time 2015-01-07 10:09:13.037700
common/Timer.cc: 127: FAILED assert(lock.is_locked())

 ceph version 0.90-788-g93666f8 (93666f80adf2db9284226b15a5fb983b05c38dc6)
 1: (ceph::__ceph_assert_fail(char const*, char const*, int, char const*)+0x95) [0x19b840d]
 2: (SafeTimer::add_event_after(double, Context*)+0x48) [0x19a40be]
 3: (OSD::init()+0x1bab) [0x13267c1]
 4: (main()+0x3b48) [0x130d201]
 5: (__libc_start_main()+0xf5) [0x2b4b5c45ede5]
 6: ./ceph-osd() [0x1308e59]
 NOTE: a copy of the executable, or `objdump -rdS <executable>` is needed to interpret this.

--- logging levels ---
   0/ 5 none
   0/ 1 lockdep
   0/ 1 context
   1/ 1 crush


--- begin dump of recent events ---
     0> 2015-01-07 10:09:13.054711 2b4b5a0373c0 -1 *** Caught signal (Aborted) **
 in thread 2b4b5a0373c0

 ceph version 0.90-788-g93666f8 (93666f80adf2db9284226b15a5fb983b05c38dc6)
 1: (ceph::BackTrace::BackTrace(int)+0x2d) [0x1721551]
 2: ./ceph-osd() [0x185a035]
 3: (()+0xfbb0) [0x2b4b5a8eabb0]
 4: (gsignal()+0x37) [0x2b4b5c473f77]
 5: (abort()+0x148) [0x2b4b5c4775e8]
 6: (__gnu_cxx::__verbose_terminate_handler()+0x155) [0x2b4b5bc7f6e5]
 7: (()+0x5e856) [0x2b4b5bc7d856]
 8: (()+0x5e883) [0x2b4b5bc7d883]
 9: (()+0x5eaae) [0x2b4b5bc7daae]
 10: (ceph::__ceph_assert_fail(char const*, char const*, int, char const*)+0x342) [0x19b86ba]
 11: (SafeTimer::add_event_after(double, Context*)+0x48) [0x19a40be]
 12: (OSD::init()+0x1bab) [0x13267c1]
 13: (main()+0x3b48) [0x130d201]
 14: (__libc_start_main()+0xf5) [0x2b4b5c45ede5]
 15: ./ceph-osd() [0x1308e59]
 NOTE: a copy of the executable, or `objdump -rdS <executable>` is needed to interpret this.

--- logging levels ---

**Comment by guangyy** [comment]
@athanatos , sorry for the late response. Updated (and tested locally). Please help to review. Thanks!

**Comment by dachary** [comment]
@guangyy it looks like the following test fails http://workbench.dachary.org/ceph/ceph/blob/master/src/test/ceph-helpers.sh#L911 . 
<pre>
gget_last_scrub_stamp: 798: ceph --format xml pg dump pgs
gget_last_scrub_stamp: 799: xmlstarlet sel -t -m '//pg_stat[pgid='\''1.0'\'']/last_scrub_stamp' -v .
repair: 903: test '2015-01-22 12:18:40.816277' '!=' '2015-01-22 12:18:40.816277'
repair: 906: sleep 1
repair: 902: (( i++ ))
repair: 902: (( i &lt; 60 ))
repair: 908: return 1
test_repair: 918: return 1
run_tests: 982: return 1
</pre>
Meaning the last_scrub_stamp is never updated which is an indication that repair did not work as expected. Does it work for you locally ? You can run just this test it with
<pre>
test/ceph-helpers.sh TESTS test_repair
</pre>

**Comment by guangyy** [comment]
@dachary , thanks Loic! I failed to find the test case in my branch, it looks like my change is based on an old version. I will rebase and check.

BTW, by testing, I meant that I use vstart to launch a cluster locally which fixed the original lock issue.

**Comment by guangyy** [comment]
@dachary @athanatos , the failure of the check was due to that within the tick handler, it did not re-add the event back for next round. Fixed and re-pushed. Please help to review. Thanks!

**Comment by guangyy** [comment]
ping @athanatos , is it good to add back to testing?

**Comment by guangyy** [comment]
ping @athanatos  :)

**Comment by guangyy** [comment]
@athanatos , is it good to schedule testing for this patch? Thanks!

**Pull request merged**
