### PR TITLE
mon: Fixed typo in function comment blocks and in other comments

### PR DESCRIPTION
**Pull request by Linbing**
I found there is a lot of iif error of note, so i grep it and modify all in project

Signed-off-by: linbing linbing@t2cloud.net

### CODE REVIEW

**Comment by Liuchang0812** [comment]
@Linbing `iff` means `if and only if`.

**Comment by Linbing** [comment]
@Liuchang0812 @branch-predictor  look at this https://github.com/ceph/ceph/pull/15191

**Comment by branch-predictor** [comment]
@Linbing the actual error is that it's "iff" (http://mathworld.wolfram.com/Iff.html), not "iif", but please use common sense here. For non-mathematicians it may be obvious typo, but common sense says if same typo occurs so often, it cannot be just a typo.

**Comment by joscollin** [comment]
@Linbing @Liuchang0812 @branch-predictor 

You are changing from iif to if, which is correct. The PR#15191 is also correctly fixed. I think you people are confusing yourself. Please check again.

**Comment by joscollin** [comment]
@branch-predictor The logic is: These headers are probably copy-pasted and then modified for each function, in-order to keep the same format / alignment for all functions. Also the programmer doesn't have  type "@pre", "@post" or "@param" repeatedly. As a consequence, the mistake `iif` is also copied.

**Comment by tchaikov** [comment]
@joscollin next time, when you are merging a PR, could you add a `Reviewed-by` line at the end of the merging commit?

**Comment by joscollin** [comment]
@tchaikov I will surely do that. Thanks for catching that.

**Comment by tchaikov** [comment]
@Linbing 
next time, could you prefix the title of your commit message with the subcomponent your are changing ? see https://github.com/ceph/ceph/blob/master/SubmittingPatches.rst#3-describe-your-changes

**Comment by joscollin** [comment]
@tchaikov Is it `Merged-by` or `Reviewed-by` ? Please clarify. Thanks.

**Comment by tchaikov** [comment]
`Reviewed-by`.

**Pull request merged**
