### PR TITLE
hammer: global/pidfile: do not start two daemons with a single pid-file

### PR DESCRIPTION
**Pull request by tchaikov**
http://tracker.ceph.com/issues/14583

### CODE REVIEW

**Comment by dachary** [comment]
@tchaikov I agree with your conflict resolution decisions

<pre>

Conflicts:
	src/global/global_init.cc
      - the `flag` argument of `global_init_prefork()` is not used, so
        it was removed in master. but the cleanup commit was not
        cherry-picked to hammer, thus the conflict, guess we can just
        keep it around in hammer to minimize the code churn, unless
        it will stand in the way of future backports.)
      - s/nullptr/NULL/ as hammer does not support c++11.
</pre>

You could replace 

> guess we can just  keep it around in hammer to minimize the code churn, unless it will stand in the way of future backports.

with

> we can just  keep it around in hammer to minimize the code churn, although it may stand in the way of future backports.

**Comment by tchaikov** [comment]
@dachary thanks for your review. updated the commit message and repushed.

**Comment by dachary** [comment]
<pre>
Reviewed-by: Loic Dachary &lt;ldachary@redhat.com>
</pre>

after a rados run

**Comment by dachary** [comment]
the test has lingering processes, https://github.com/ceph/ceph/pull/7734

**Comment by tchaikov** [comment]
changelog

- cherry-picked the change posted at #7734
- rebased against latest hammer branch

so i am removing "DNM" from the pull request title.

**Comment by dachary** [comment]
@tchaikov it looks like I broke hammer this morning. What a day :-)

**Comment by dachary** [comment]
@tchaikov https://github.com/ceph/ceph/pull/7801 fixes the make check issue (unrelated to your pull request). It should be merged shortly.

**Comment by dachary** [comment]
@tchaikov #7801 merged, feel free to rebase to get a clean make check run

**Comment by tchaikov** [comment]
@dachary rebased and repushed.

**Comment by dachary** [comment]
<pre>
FAIL: test/test_pidfile.sh
==========================

./test/test_pidfile.sh: line 8: ../qa/workunits/ceph-helpers.sh: No such file or directory
./test/test_pidfile.sh: line 84: main: command not found
</pre>

**Comment by tchaikov** [comment]
```
FAIL: test/test_pidfile.sh
==========================

./test/test_pidfile.sh: line 8: ../qa/workunits/ceph-helpers.sh: No such file or directory
./test/test_pidfile.sh: line 84: main: command not found
```

seems it's non trivial to backport the tests. in comparison to ceph-helper.sh, test-common.sh is like stones in the flakes of stone in the hands of Neanderthals...

**Comment by dachary** [comment]
@tchaikov ok to remove test_pidfile.sh from the pr

**Comment by tchaikov** [comment]
changelog

- cowardly removed the tests for pidfile

**Comment by dachary** [comment]
Passed a rados suite http://tracker.ceph.com/issues/14692#note-27 and an upgrade suite http://tracker.ceph.com/issues/14692#note-29

**Pull request merged**
