### PR TITLE
quincy: doc/rgw: fix caption

### PR DESCRIPTION
**Pull request by zdover23**
Rewrite the third paragraph of the caption to the figure depicting how a zonegroup works.

Follows https://github.com/ceph/ceph/pull/50316.

Signed-off-by: Zac Dover <zac.dover@proton.me>
(cherry picked from commit 8fa521466023635436305c1af31501bbbe20e857)

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [x] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [x] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by HoneyTyagii** [comment]
Hey @anthonyeleven  I noticed that the issue #50395  is still open. I'd love to help out and contribute to the project.

**Comment by anthonyeleven** [comment]
@HoneyTyagii You pasted a reference to this PR, did you mean to reference a tracker issue?

**Comment by anthonyeleven** [comment]
That's the thing, I have no way of knowing which tracker issue you mean?  Anyone is welcome to visit tracker.ceph.com and work on unclaimed tickets.  Be sure to read the documentation about PR and commit conventions.

**Comment by HoneyTyagii** [comment]
> That's the thing, I have no way of knowing which tracker issue you mean? Anyone is welcome to visit tracker.ceph.com and work on unclaimed tickets. Be sure to read the documentation about PR and commit conventions.

@anthonyeleven  Thanks for the information! I'm new to contributing to Ceph, so I appreciate the guidance. I'll be sure to check out the tracker and the documentation. If I have any further questions, would you be available to provide additional support?

**Comment by zdover23** [comment]
> > That's the thing, I have no way of knowing which tracker issue you mean? Anyone is welcome to visit tracker.ceph.com and work on unclaimed tickets. Be sure to read the documentation about PR and commit conventions.
> 
> @anthonyeleven Thanks for the information! I'm new to contributing to Ceph, so I appreciate the guidance. I'll be sure to check out the tracker and the documentation. If I have any further questions, would you be available to provide additional support?

@HoneyTyagii 

https://docs.ceph.com/en/quincy/dev/developer_guide/basic-workflow/#basic-workflow-dev-guide

This might be helpful. This is the document that has been prepared for exactly the situation that you find yourself in.

**Comment by zdover23** [comment]
https://tracker.ceph.com/issues/50395 - This issue is resolved, so whatever was the intended referent of the request to help couldn't be this.

**Comment by HoneyTyagii** [comment]
@zdover23  Thanks for the link and the additional information! I'll definitely take a look at the document you provided. It's great to have such a helpful community to turn to when I'm starting out. Thanks again for all your help!

**Pull request merged**
