### PR TITLE
qa/rgw: extra s3tests tasks use rgw endpoint configuration

### PR DESCRIPTION
**Pull request by cbodley**
the rgw task now defaults to ports 80/443. the s3tests/swift/ragweed tasks were updated accordingly, but I missed some of the other s3test-based tasks that don't run in the rgw suite

Fixes: http://tracker.ceph.com/issues/17882

### CODE REVIEW

**Comment by cbodley** [comment]
scheduled one job with rgw_snaps.yaml at http://pulpito.front.sepia.ceph.com/cbodley-2019-06-18_14:08:02-rados-master-distro-basic-smithi/

**Comment by cbodley** [comment]
testing new commit at http://pulpito.front.sepia.ceph.com/cbodley-2019-06-18_14:51:01-rados-master-distro-basic-smithi/

**Comment by tchaikov** [comment]
@cbodley thanks for looking into this!

**Comment by cbodley** [comment]
@tchaikov the s3readwrite task appeared to work there, but osd.5 aborted during the run with `ceph_abort_msg("out of order op")`

**Comment by cbodley** [comment]
jenkins test make check

**Comment by cbodley** [comment]
verified against rgw suite too: http://pulpito.ceph.com/cbodley-2019-06-18_20:15:16-rgw:verify-wip-cbodley-testing-distro-basic-smithi/

**Comment by tchaikov** [comment]
@cbodley i think the "out of order op" is a dup of http://tracker.ceph.com/issues/23857.

**Pull request merged**
