### PR TITLE
qa/cephfs: move run_shell to mount.py and add methods for negative testing

### PR DESCRIPTION
**Pull request by rishabh-d-dave**

### CODE REVIEW

**Comment by rishabh-d-dave** [comment]
Wrote quick test to exercise newly added methods - [test_dummy.py.log](https://github.com/ceph/ceph/files/4199063/test_dummy.py.log). Here's the log - [vstart_runner.log](https://github.com/ceph/ceph/files/4199062/vstart_runner.log).

**Comment by rishabh-d-dave** [comment]
Testing was successful locally. Here's the code and results - https://gist.github.com/rishabh-d-dave/4f2869edf4a189256eb3d430c3634dd2

**Comment by gregsfortytwo** [comment]
http://pulpito.ceph.com/gregf-2020-03-26_16:03:14-fs-wip-greg-testing-326-distro-basic-smithi/ looks good

**Comment by gregsfortytwo** [comment]
Okay, I screwed up merging this PR because I had managed not to include it in my integration branch. And it turns out it breaks many of the tests using this interface, especially in test_volume etc.
See http://pulpito.front.sepia.ceph.com/gregf-2020-04-03_01:10:37-fs-master-distro-basic-smithi/ (with it reverted) versus http://pulpito.front.sepia.ceph.com/gregf-2020-04-03_01:12:28-fs-master-distro-basic-smithi/ (just master).

I tried to add in the omit_sudo option which Zheng noted got omitted (in the linked PR above), but that PR #34378 did not appear to help: http://pulpito.front.sepia.ceph.com/gregf-2020-04-02_17:05:44-fs-wip-greg-testing-42-distro-basic-smithi/

So I am testing a revert of this in #34386 that I expect will merge ASAP.

**Pull request merged**
