### PR TITLE
mgr/dashboard: get and update bucket replication policies

### PR DESCRIPTION
**Pull request by nizamial09**
Screenshot from 2024-06-07 18-41-30
Screenshot from 2024-06-07 18-41-58
Screenshot from 2024-06-07 18-42-05

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Comment by cloudbehl** [comment]
jenkins retest this please

**Comment by cloudbehl** [comment]
jenkins test api

**Comment by nizamial09** [comment]
jenkins test api

**Comment by cloudbehl** [comment]
I am facing this error while testing the PR on 


Screenshot from 2024-06-21 15-07-36


```
2024-06-21T09:42:06.006+0000 7f2884c00700  0 [dashboard ERROR rest_client] RGW REST API failed PUT req status: 404
2024-06-21T09:42:06.007+0000 7f2884c00700  0 [dashboard ERROR exception] Dashboard Exception
Traceback (most recent call last):
  File "/ceph/src/pybind/mgr/dashboard/controllers/rgw.py", line 292, in proxy
    result = instance.proxy(method, path, params, None)
  File "/ceph/src/pybind/mgr/dashboard/services/rgw_client.py", line 549, in proxy
    params, data)
  File "/ceph/src/pybind/mgr/dashboard/rest_client.py", line 543, in func_wrapper
    **kwargs)
  File "/ceph/src/pybind/mgr/dashboard/services/rgw_client.py", line 543, in _proxy_request
    raw_content=True)
  File "/ceph/src/pybind/mgr/dashboard/rest_client.py", line 325, in __call__
    data, raw_content, headers)
  File "/ceph/src/pybind/mgr/dashboard/rest_client.py", line 428, in do_request
    resp.content)
dashboard.rest_client.RequestException: RGW REST API failed request with status code 404
(b'{"Code":"NoSuchKey","Message":"","RequestId":"tx0000023ad08b55b79cb35-006675'
 b'4aee-13785-zone1-zg1-realm1","HostId":"13785-zone1-zg1-realm1-zg1-realm1"}')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/ceph/src/pybind/mgr/dashboard/services/exception.py", line 47, in dashboard_exception_handler
    return handler(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/cherrypy/_cpdispatch.py", line 54, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/ceph/src/pybind/mgr/dashboard/controllers/_base_controller.py", line 263, in inner
    ret = func(*args, **kwargs)
  File "/ceph/src/pybind/mgr/dashboard/controllers/_rest_controller.py", line 193, in wrapper
    return func(*vpath, **params)
  File "/ceph/src/pybind/mgr/dashboard/controllers/rgw.py", line 545, in set
    json_response=False)
  File "/ceph/src/pybind/mgr/dashboard/controllers/rgw.py", line 298, in proxy
    raise DashboardException(e, http_status_code=http_status_code, component='rgw')
dashboard.exceptions.DashboardException: RGW REST API failed request with status code 404
(b'{"Code":"NoSuchKey","Message":"","RequestId":"tx0000023ad08b55b79cb35-006675'
 b'4aee-13785-zone1-zg1-realm1","HostId":"13785-zone1-zg1-realm1-zg1-realm1"}')
2024-06-21T09:42:06.007+0000 7f2884c00700  0 [dashboard INFO request] [172.20.0.8:52504] [PUT] [500] [0.006s] [admin] [212.0B] /api/rgw/bucket/test1

```

**Comment by nizamial09** [comment]
@cloudbehl updated

**Comment by cloudbehl** [comment]
jenkins test make check

**Review by cloudbehl — APPROVED** [review]
LGTM

**Comment by nizamial09** [comment]
jenkins test dashboard

**Comment by nizamial09** [comment]
jenkins test dashboard

**Comment by nizamial09** [comment]
unrelated e2e error (flaky notification e2e), retriggered again

**Pull request merged**
