### PR TITLE
DNM: zstd: hack test reusing cstream

### PR DESCRIPTION
**Pull request by liewegas**
@Cyan4973: to reproduce,
git checkout, sudo ./install-deps.sh, ./do_cmake.sh, cd build, make ceph_zstd ceph_zlib ceph_snappy unittest_compression (this will take forever, sorry), bin/unittest_compression --gtest_filter=*compress_16*

### CODE REVIEW

**Comment by liewegas** [comment]
here's perf top, fwiw:
<pre>
  25.41%  libceph_zstd.so.2.0.0  [.] ZSTD_insertAndFindFirstIndex
   6.29%  libceph_zstd.so.2.0.0  [.] ZSTD_hash5
   5.86%  libceph_zstd.so.2.0.0  [.] BIT_addBits
   4.83%  libceph_zstd.so.2.0.0  [.] MEM_read64
   4.66%  libceph_zstd.so.2.0.0  [.] ZSTD_hash5Ptr
   4.46%  libceph_zstd.so.2.0.0  [.] ZSTD_hashPtr
   3.80%  libceph_zstd.so.2.0.0  [.] FSE_encodeSymbol
   3.16%  libceph_zstd.so.2.0.0  [.] ZSTD_encodeSequences
   2.68%  libceph_zstd.so.2.0.0  [.] MEM_readLE64
   2.47%  libceph_zstd.so.2.0.0  [.] ZSTD_compressBlock_greedy
   2.31%  libceph_zstd.so.2.0.0  [.] HUF_sort
   2.06%  libceph_zstd.so.2.0.0  [.] MEM_isLittleEndian
   2.03%  libceph_zstd.so.2.0.0  [.] ZSTD_HcFindBestMatch_selectMLS
   2.02%  libceph_zstd.so.2.0.0  [.] FSE_count_simple
   1.98%  libceph_zstd.so.2.0.0  [.] ZSTD_count
   1.89%  libceph_zstd.so.2.0.0  [.] BIT_flushBits
   1.75%  libceph_zstd.so.2.0.0  [.] HUF_encodeSymbol
   1.71%  libceph_zstd.so.2.0.0  [.] HUF_buildCTable_wksp
   1.60%  libceph_zstd.so.2.0.0  [.] BIT_addBitsFast
   1.56%  libceph_zstd.so.2.0.0  [.] ZSTD_storeSeq
</pre>

**Comment by Cyan4973** [comment]
Quick note : 
the `perf top` result seems to imply that
the compression operation itself is pretty slow.

It also show that compression uses `ZSTD_compressBlock_greedy()`,
which means it's probably using level 5 or 6.
`_Edit_ : just looked at source code, indeed `COMPRESSION_LEVEL` is defined to `5`.

2 ideas : 
- These are not fastest levels. For a speed-oriented application, level 1 is recommended.
- Speed is nonetheless very slow. `zstd -5` should be about equivalent in speed with `gzip -2`. Maybe there is some pathological pattern in the data used for test. That will be worthwhile to investigate too.

**Comment by Cyan4973** [comment]
```
make ceph_zstd
make: *** No rule to make target `ceph_zstd'.  Stop.
```

**Comment by Cyan4973** [comment]
```
./install-deps.sh
./install-deps.sh: line 78: /etc/os-release: No such file or directory
```

note  : I was trying to install on Mac OS-X. I suspect Ceph is not compatible with OS-X.

**Comment by liewegas** [comment]
Yeah, it assumes a linux environment currently.

**Comment by Cyan4973** [comment]
built on a Linux Ubuntu Xenial VM : 

```
bin/unittest_compression --gtest_filter=compress_16
Note: Google Test filter = compress_16
[==========] Running 0 tests from 0 test cases.
[==========] 0 tests from 0 test cases ran. (1 ms total)
[  PASSED  ] 0 tests.
```

**Comment by Cyan4973** [comment]
Without `--gtest_filter=compress_16`. it seems to work : 

```
[==========] Running 68 tests from 3 test cases.
[----------] Global test environment set-up.
[----------] 3 tests from ZlibCompressor
[ RUN      ] ZlibCompressor.zlib_isal_compatibility
[       OK ] ZlibCompressor.zlib_isal_compatibility (4 ms)
[ RUN      ] ZlibCompressor.isal_compress_zlib_decompress_random
[       OK ] ZlibCompressor.isal_compress_zlib_decompress_random (80 ms)
[ RUN      ] ZlibCompressor.isal_compress_zlib_decompress_walk
[       OK ] ZlibCompressor.isal_compress_zlib_decompress_walk (50 ms)
[----------] 3 tests from ZlibCompressor (134 ms total)

[----------] 1 test from CompressionPlugin
[ RUN      ] CompressionPlugin.all
[       OK ] CompressionPlugin.all (1 ms)
[----------] 1 test from CompressionPlugin (1 ms total)

[----------] 64 tests from Compressor/CompressorTest
[ RUN      ] Compressor/CompressorTest.load_plugin/0
[plugin zlib (zlib/isal)]
[       OK ] Compressor/CompressorTest.load_plugin/0 (3 ms)
[ RUN      ] Compressor/CompressorTest.load_plugin/1
[plugin zlib (zlib/noisal)]
[       OK ] Compressor/CompressorTest.load_plugin/1 (1 ms)
[ RUN      ] Compressor/CompressorTest.load_plugin/2
[plugin snappy (snappy)]
[       OK ] Compressor/CompressorTest.load_plugin/2 (2 ms)
[ RUN      ] Compressor/CompressorTest.load_plugin/3
[plugin zstd (zstd)]
[       OK ] Compressor/CompressorTest.load_plugin/3 (2 ms)
[ RUN      ] Compressor/CompressorTest.small_round_trip/0
[plugin zlib (zlib/isal)]
orig 77 compressed 168 with zlib/isal
[       OK ] Compressor/CompressorTest.small_round_trip/0 (2 ms)
[ RUN      ] Compressor/CompressorTest.small_round_trip/1
[plugin zlib (zlib/noisal)]
orig 77 compressed 66 with zlib/noisal
[       OK ] Compressor/CompressorTest.small_round_trip/1 (2 ms)
[ RUN      ] Compressor/CompressorTest.small_round_trip/2
[plugin snappy (snappy)]
orig 77 compressed 74 with snappy
[       OK ] Compressor/CompressorTest.small_round_trip/2 (2 ms)
[ RUN      ] Compressor/CompressorTest.small_round_trip/3
[plugin zstd (zstd)]
orig 77 compressed 76 with zstd
[       OK ] Compressor/CompressorTest.small_round_trip/3 (2 ms)
[ RUN      ] Compressor/CompressorTest.big_round_trip_repeated/0
[plugin zlib (zlib/isal)]
orig 4194344 compressed 54878 with zlib/isal
[       OK ] Compressor/CompressorTest.big_round_trip_repeated/0 (28 ms)
[ RUN      ] Compressor/CompressorTest.big_round_trip_repeated/1
[plugin zlib (zlib/noisal)]
orig 4194344 compressed 14306 with zlib/noisal
[       OK ] Compressor/CompressorTest.big_round_trip_repeated/1 (45 ms)
[ RUN      ] Compressor/CompressorTest.big_round_trip_repeated/2
[plugin snappy (snappy)]
orig 4194344 compressed 201194 with snappy
[       OK ] Compressor/CompressorTest.big_round_trip_repeated/2 (10 ms)
[ RUN      ] Compressor/CompressorTest.big_round_trip_repeated/3
[plugin zstd (zstd)]
orig 4194344 compressed 469 with zstd
[       OK ] Compressor/CompressorTest.big_round_trip_repeated/3 (13 ms)
[ RUN      ] Compressor/CompressorTest.big_round_trip_randomish/0
[plugin zlib (zlib/isal)]
orig 10485760 compressed 5989211 with zlib/isal
[       OK ] Compressor/CompressorTest.big_round_trip_randomish/0 (306 ms)
[ RUN      ] Compressor/CompressorTest.big_round_trip_randomish/1
[plugin zlib (zlib/noisal)]
orig 10485760 compressed 4928804 with zlib/noisal
[       OK ] Compressor/CompressorTest.big_round_trip_randomish/1 (991 ms)
[ RUN      ] Compressor/CompressorTest.big_round_trip_randomish/2
[plugin snappy (snappy)]
orig 10485760 compressed 8683058 with snappy
[       OK ] Compressor/CompressorTest.big_round_trip_randomish/2 (263 ms)
[ RUN      ] Compressor/CompressorTest.big_round_trip_randomish/3
[plugin zstd (zstd)]
orig 10485760 compressed 4829428 with zstd
[       OK ] Compressor/CompressorTest.big_round_trip_randomish/3 (1103 ms)
[ RUN      ] Compressor/CompressorTest.compress_decompress/0
[plugin zlib (zlib/isal)]
[       OK ] Compressor/CompressorTest.compress_decompress/0 (2 ms)
[ RUN      ] Compressor/CompressorTest.compress_decompress/1
[plugin zlib (zlib/noisal)]
[       OK ] Compressor/CompressorTest.compress_decompress/1 (3 ms)
[ RUN      ] Compressor/CompressorTest.compress_decompress/2
[plugin snappy (snappy)]
[       OK ] Compressor/CompressorTest.compress_decompress/2 (0 ms)
[ RUN      ] Compressor/CompressorTest.compress_decompress/3
[plugin zstd (zstd)]
[       OK ] Compressor/CompressorTest.compress_decompress/3 (2 ms)
[ RUN      ] Compressor/CompressorTest.sharded_input_decompress/0
[plugin zlib (zlib/isal)]
[       OK ] Compressor/CompressorTest.sharded_input_decompress/0 (2 ms)
[ RUN      ] Compressor/CompressorTest.sharded_input_decompress/1
[plugin zlib (zlib/noisal)]
[       OK ] Compressor/CompressorTest.sharded_input_decompress/1 (2 ms)
[ RUN      ] Compressor/CompressorTest.sharded_input_decompress/2
[plugin snappy (snappy)]
[       OK ] Compressor/CompressorTest.sharded_input_decompress/2 (1 ms)
[ RUN      ] Compressor/CompressorTest.sharded_input_decompress/3
[plugin zstd (zstd)]
[       OK ] Compressor/CompressorTest.sharded_input_decompress/3 (1 ms)
[ RUN      ] Compressor/CompressorTest.compress_1024/0
[plugin zlib (zlib/isal)]
[       OK ] Compressor/CompressorTest.compress_1024/0 (45 ms)
[ RUN      ] Compressor/CompressorTest.compress_1024/1
[plugin zlib (zlib/noisal)]
[       OK ] Compressor/CompressorTest.compress_1024/1 (302 ms)
[ RUN      ] Compressor/CompressorTest.compress_1024/2
[plugin snappy (snappy)]
[       OK ] Compressor/CompressorTest.compress_1024/2 (11 ms)
[ RUN      ] Compressor/CompressorTest.compress_1024/3
[plugin zstd (zstd)]
[       OK ] Compressor/CompressorTest.compress_1024/3 (476 ms)
[ RUN      ] Compressor/CompressorTest.compress_2048/0
[plugin zlib (zlib/isal)]
[       OK ] Compressor/CompressorTest.compress_2048/0 (63 ms)
[ RUN      ] Compressor/CompressorTest.compress_2048/1
[plugin zlib (zlib/noisal)]
[       OK ] Compressor/CompressorTest.compress_2048/1 (420 ms)
[ RUN      ] Compressor/CompressorTest.compress_2048/2
[plugin snappy (snappy)]
[       OK ] Compressor/CompressorTest.compress_2048/2 (15 ms)
[ RUN      ] Compressor/CompressorTest.compress_2048/3
[plugin zstd (zstd)]
[       OK ] Compressor/CompressorTest.compress_2048/3 (1290 ms)
[ RUN      ] Compressor/CompressorTest.compress_4096/0
[plugin zlib (zlib/isal)]
[       OK ] Compressor/CompressorTest.compress_4096/0 (94 ms)
[ RUN      ] Compressor/CompressorTest.compress_4096/1
[plugin zlib (zlib/noisal)]
[       OK ] Compressor/CompressorTest.compress_4096/1 (607 ms)
[ RUN      ] Compressor/CompressorTest.compress_4096/2
[plugin snappy (snappy)]
[       OK ] Compressor/CompressorTest.compress_4096/2 (43 ms)
[ RUN      ] Compressor/CompressorTest.compress_4096/3
[plugin zstd (zstd)]
[       OK ] Compressor/CompressorTest.compress_4096/3 (1606 ms)
[ RUN      ] Compressor/CompressorTest.compress_8192/0
[plugin zlib (zlib/isal)]
[       OK ] Compressor/CompressorTest.compress_8192/0 (132 ms)
[ RUN      ] Compressor/CompressorTest.compress_8192/1
[plugin zlib (zlib/noisal)]
[       OK ] Compressor/CompressorTest.compress_8192/1 (923 ms)
[ RUN      ] Compressor/CompressorTest.compress_8192/2
[plugin snappy (snappy)]
[       OK ] Compressor/CompressorTest.compress_8192/2 (80 ms)
[ RUN      ] Compressor/CompressorTest.compress_8192/3
[plugin zstd (zstd)]
[       OK ] Compressor/CompressorTest.compress_8192/3 (2310 ms)
[ RUN      ] Compressor/CompressorTest.compress_16384/0
[plugin zlib (zlib/isal)]
[       OK ] Compressor/CompressorTest.compress_16384/0 (198 ms)
[ RUN      ] Compressor/CompressorTest.compress_16384/1
[plugin zlib (zlib/noisal)]
[       OK ] Compressor/CompressorTest.compress_16384/1 (1443 ms)
[ RUN      ] Compressor/CompressorTest.compress_16384/2
[plugin snappy (snappy)]
[       OK ] Compressor/CompressorTest.compress_16384/2 (144 ms)
[ RUN      ] Compressor/CompressorTest.compress_16384/3
[plugin zstd (zstd)]
[       OK ] Compressor/CompressorTest.compress_16384/3 (3395 ms)
[ RUN      ] Compressor/CompressorTest.decompress_1024/0
[plugin zlib (zlib/isal)]
[       OK ] Compressor/CompressorTest.decompress_1024/0 (121 ms)
[ RUN      ] Compressor/CompressorTest.decompress_1024/1
[plugin zlib (zlib/noisal)]
[       OK ] Compressor/CompressorTest.decompress_1024/1 (87 ms)
[ RUN      ] Compressor/CompressorTest.decompress_1024/2
[plugin snappy (snappy)]
[       OK ] Compressor/CompressorTest.decompress_1024/2 (9 ms)
[ RUN      ] Compressor/CompressorTest.decompress_1024/3
[plugin zstd (zstd)]
[       OK ] Compressor/CompressorTest.decompress_1024/3 (9 ms)
[ RUN      ] Compressor/CompressorTest.decompress_2048/0
[plugin zlib (zlib/isal)]
[       OK ] Compressor/CompressorTest.decompress_2048/0 (161 ms)
[ RUN      ] Compressor/CompressorTest.decompress_2048/1
[plugin zlib (zlib/noisal)]
[       OK ] Compressor/CompressorTest.decompress_2048/1 (111 ms)
[ RUN      ] Compressor/CompressorTest.decompress_2048/2
[plugin snappy (snappy)]
[       OK ] Compressor/CompressorTest.decompress_2048/2 (5 ms)
[ RUN      ] Compressor/CompressorTest.decompress_2048/3
[plugin zstd (zstd)]
[       OK ] Compressor/CompressorTest.decompress_2048/3 (85 ms)
[ RUN      ] Compressor/CompressorTest.decompress_4096/0
[plugin zlib (zlib/isal)]
[       OK ] Compressor/CompressorTest.decompress_4096/0 (195 ms)
[ RUN      ] Compressor/CompressorTest.decompress_4096/1
[plugin zlib (zlib/noisal)]
[       OK ] Compressor/CompressorTest.decompress_4096/1 (146 ms)
[ RUN      ] Compressor/CompressorTest.decompress_4096/2
[plugin snappy (snappy)]
[       OK ] Compressor/CompressorTest.decompress_4096/2 (21 ms)
[ RUN      ] Compressor/CompressorTest.decompress_4096/3
[plugin zstd (zstd)]
[       OK ] Compressor/CompressorTest.decompress_4096/3 (380 ms)
[ RUN      ] Compressor/CompressorTest.decompress_8192/0
[plugin zlib (zlib/isal)]
[       OK ] Compressor/CompressorTest.decompress_8192/0 (266 ms)
[ RUN      ] Compressor/CompressorTest.decompress_8192/1
[plugin zlib (zlib/noisal)]
[       OK ] Compressor/CompressorTest.decompress_8192/1 (211 ms)
[ RUN      ] Compressor/CompressorTest.decompress_8192/2
[plugin snappy (snappy)]
[       OK ] Compressor/CompressorTest.decompress_8192/2 (46 ms)
[ RUN      ] Compressor/CompressorTest.decompress_8192/3
[plugin zstd (zstd)]
[       OK ] Compressor/CompressorTest.decompress_8192/3 (677 ms)
[ RUN      ] Compressor/CompressorTest.decompress_16384/0
[plugin zlib (zlib/isal)]
[       OK ] Compressor/CompressorTest.decompress_16384/0 (364 ms)
[ RUN      ] Compressor/CompressorTest.decompress_16384/1
[plugin zlib (zlib/noisal)]
[       OK ] Compressor/CompressorTest.decompress_16384/1 (295 ms)
[ RUN      ] Compressor/CompressorTest.decompress_16384/2
[plugin snappy (snappy)]
[       OK ] Compressor/CompressorTest.decompress_16384/2 (71 ms)
[ RUN      ] Compressor/CompressorTest.decompress_16384/3
[plugin zstd (zstd)]
[       OK ] Compressor/CompressorTest.decompress_16384/3 (968 ms)
[----------] 64 tests from Compressor/CompressorTest (20613 ms total)

[----------] Global test environment tear-down
[==========] 68 tests from 3 test cases ran. (20748 ms total)
[  PASSED  ] 68 tests.
```

Presuming this test is good enough, let's investigate the poor performance.

**Comment by liewegas** [comment]
--gtest_filter=*compress_16*  (need the asterisk before and after for the 
wildcard to work).

or --gtest_filter=Compressor/CompressorTest.compress_16384/3

for just the 16k zstd test.

**Comment by Cyan4973** [comment]
works : 

```
bin/unittest_compression --gtest_filter=*compress_16*
Note: Google Test filter = *compress_16*
[==========] Running 8 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 8 tests from Compressor/CompressorTest
[ RUN      ] Compressor/CompressorTest.compress_16384/0
[plugin zlib (zlib/isal)]
[       OK ] Compressor/CompressorTest.compress_16384/0 (215 ms)
[ RUN      ] Compressor/CompressorTest.compress_16384/1
[plugin zlib (zlib/noisal)]
[       OK ] Compressor/CompressorTest.compress_16384/1 (1479 ms)
[ RUN      ] Compressor/CompressorTest.compress_16384/2
[plugin snappy (snappy)]
[       OK ] Compressor/CompressorTest.compress_16384/2 (180 ms)
[ RUN      ] Compressor/CompressorTest.compress_16384/3
[plugin zstd (zstd)]
[       OK ] Compressor/CompressorTest.compress_16384/3 (1810 ms)
[ RUN      ] Compressor/CompressorTest.decompress_16384/0
[plugin zlib (zlib/isal)]
[       OK ] Compressor/CompressorTest.decompress_16384/0 (382 ms)
[ RUN      ] Compressor/CompressorTest.decompress_16384/1
[plugin zlib (zlib/noisal)]
[       OK ] Compressor/CompressorTest.decompress_16384/1 (300 ms)
[ RUN      ] Compressor/CompressorTest.decompress_16384/2
[plugin snappy (snappy)]
[       OK ] Compressor/CompressorTest.decompress_16384/2 (79 ms)
[ RUN      ] Compressor/CompressorTest.decompress_16384/3
[plugin zstd (zstd)]
[       OK ] Compressor/CompressorTest.decompress_16384/3 (1327 ms)
[----------] 8 tests from Compressor/CompressorTest (5777 ms total)

[----------] Global test environment tear-down
[==========] 8 tests from 1 test case ran. (5778 ms total)
[  PASSED  ] 8 tests.
```

**Comment by Cyan4973** [comment]
How is `zstd` or `libzstd` built and invoked ?
Is it considered to be a system-installed dynamic library ?

**Comment by liewegas** [comment]
make ceph_zstd builds the ceph plugin (which links zstd statically).  unittest_compression will load that pluging out of your build/lib dir.

**Comment by Cyan4973** [comment]
It would be interesting to understand how `libceph_zstd.so` is built.

**Comment by liewegas** [comment]
Oh, right: https://github.com/ceph/ceph/blob/master/src/compressor/zstd/CMakeLists.txt

**Comment by Cyan4973** [comment]
For my understanding, how did you successfully generate `perf top` stats ?

**Comment by Cyan4973** [comment]
Looking in more details at the tests with `--gtest_filter=*compress_16*`
all inputs are 16K in size, 
they are all consumed in a single pass.

So a question is : 
is that just a specific design of the test ? Or is it representative of real ceph usage ?
In particular, is data always consumes in a single pass ?

**Comment by liewegas** [comment]
I modified the test to run 100 times longer at https://github.com/ceph/ceph/blob/master/src/test/compressor/test_compression.cc#L246 and did 'perf top -p $(pidof unittest_compression)'

And yeah, this interface always compresses the entirety of the data in a single pass.  There might be some contexts where we could stream/pipeline compression but we haven't needed to yet.

**Comment by Cyan4973** [comment]
If I understand the test correctly, a 16 KB sample is created,
the same sample is then sent repetitively 10000 times to the compression module,
then total time is measured and displayed.

I extracted the sample into a file,
and used a 3rd party benchmark program (`lzbench`) on this sample,
and here are the result : 

```
./lzbench -i999,999 -ezstd,2/zlib,6 ~/dev/bench/cephSample16K 
Compressor name         Compress. Decompress. Compr. size  Ratio Filename
memcpy                  13212 MB/s 36408 MB/s       16384 100.00 /home/cyan/dev/bench/cephSample16K
zstd 1.3.1 -2             473 MB/s  1103 MB/s        1354   8.26 /home/cyan/dev/bench/cephSample16K
zlib 1.2.11 -6             93 MB/s   583 MB/s        2654  16.20 /home/cyan/dev/bench/cephSample16K
done... (cIters=999 dIters=999 cTime=1.0 dTime=2.0 chunkSize=1706MB cSpeed=0MB)
```

It seems that, for this sample, `zstd` result should be < 400ms.
Yet, in my tests, results are ~1800 ms (I tried to change the compression level, it did not changed performance, which feels definitely fishy).

There is something in this test which holds back performance.
I'm still trying to figure out what it could be.

**Comment by Cyan4973** [comment]
>  this interface always compresses the entirety of the data in a single pass.

Yes, but if I understand correctly, data is presented as a list of buffers.
In the test, data is always provided as a single buffer.
I assume this is specific to the test,
otherwise, I don't see the point of using the streaming interface.

**Comment by Cyan4973** [comment]
I tried multiple changes, and none of them is actually able to improve performance.
Quite tellingly, even noticeably changing the compression level wouldn't change the timing.
I confirmed through manual traces that my changes were effectively compiled into the binary.

I see one possible reason for this behaviour : most of the delay comes from an external source, something standing between the compressor and the test output.
I haven't yet identified where this latency source can be. I'm suspecting the solution lies outside of `ZstdCompressor.h`.

**Comment by Cyan4973** [comment]
OK, I'm not sure what's going on, but here is how I proceeded : 

- manually compile `libzstd.a` from `/src/zstd/lib`, using local Makefile and adding the `-fPIC` flag
- replace the `libzstd.a` binary created by `cmake` in `/build/src/zstd/libzstd` by the one above
- recompile `libceph_zstd.so`

And here is the result with `unittest_compression` : 
```
bin/unittest_compression --gtest_filter=*compress_16*                    
Note: Google Test filter = *compress_16*
[==========] Running 8 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 8 tests from Compressor/CompressorTest
[ RUN      ] Compressor/CompressorTest.compress_16384/0
[plugin zlib (zlib/isal)]
[       OK ] Compressor/CompressorTest.compress_16384/0 (228 ms)
[ RUN      ] Compressor/CompressorTest.compress_16384/1
[plugin zlib (zlib/noisal)]
[       OK ] Compressor/CompressorTest.compress_16384/1 (1503 ms)
[ RUN      ] Compressor/CompressorTest.compress_16384/2
[plugin snappy (snappy)]
[       OK ] Compressor/CompressorTest.compress_16384/2 (161 ms)
[ RUN      ] Compressor/CompressorTest.compress_16384/3
[plugin zstd (zstd)]
[       OK ] Compressor/CompressorTest.compress_16384/3 (386 ms)
[ RUN      ] Compressor/CompressorTest.decompress_16384/0
[plugin zlib (zlib/isal)]
[       OK ] Compressor/CompressorTest.decompress_16384/0 (389 ms)
[ RUN      ] Compressor/CompressorTest.decompress_16384/1
[plugin zlib (zlib/noisal)]
[       OK ] Compressor/CompressorTest.decompress_16384/1 (324 ms)
[ RUN      ] Compressor/CompressorTest.decompress_16384/2
[plugin snappy (snappy)]
[       OK ] Compressor/CompressorTest.decompress_16384/2 (82 ms)
[ RUN      ] Compressor/CompressorTest.decompress_16384/3
[plugin zstd (zstd)]
[       OK ] Compressor/CompressorTest.decompress_16384/3 (174 ms)
[----------] 8 tests from Compressor/CompressorTest (3260 ms total)

[----------] Global test environment tear-down
[==========] 8 tests from 1 test case ran. (3272 ms total)
[  PASSED  ] 8 tests.
```

Performance is now within expectation.

It seems the culprit is in the build system.

**Comment by Cyan4973** [comment]
Some more complete results here : 
https://pastebin.com/1fyt3NRV

I also modified the `ZstdCompressor.h` file, in the expectation to improve performance, though clearly the main issue is the way `libzstd.a` is built. I could nonetheless send you the new file. How would you prefer it ?

**Comment by liewegas** [comment]
OMG yes!  That was totally it.  Thank you so much for helping track this down!  That was above and beyond.  :+1: 

https://github.com/ceph/ceph/pull/18879/commits/e9c0f05323216d89a4238072e8b07987a2045a1d

**Comment by Cyan4973** [comment]
If you are interested, here is how was modified `ZstdCompressor.h` to get above results : 

https://gist.github.com/Cyan4973/1d1d104b64f5903fc6200f0712ff570a

Among other things it fixes a possible allocation failure condition.
The same fix should also be ported to the decompression part (which is unmodified).

**Comment by disaster123** [comment]
@Cyan4973 Thanks a lot for your hard work!

**Comment by disaster123** [comment]
@Cyan4973 as far as i know @liewegas told me that your suggestion (https://gist.github.com/Cyan4973/1d1d104b64f5903fc6200f0712ff570a) won't work for ceph as the compression object is used by multiple threads and cctx isn't thread safe.

**Pull request closed without merging**
