### PR TITLE
mgr: Remove service_daemon handling from MMgrUpdate

### PR DESCRIPTION
**Pull request by pdvian**
The service_daemon is only required if client services
needs to be registered with mgr. The service_daemon
handling is not required in case of MMgrUpdate as it
handles mon metadata updates only.

Fixes: https://tracker.ceph.com/issues/55322

Signed-off-by: Prashant D <pdhange@redhat.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by ljflores** [comment]
I will be running some reproducer tests for the restful module bug.

Shaman build here: https://shaman.ceph.com/builds/ceph/wip-version-mgrupdate/

**Review by ljflores — COMMENTED** [review]
Good news @pdvian, the restful test is passing now! (See the latest note on the Tracker). We should still inspect the mgr logs to see if it's behaving as expected with this new MMgrUpdate message; plus, MMgrUpdate still needs to be added to `tools/ceph-dencoder/common_types.h`.

**Review by badone — APPROVED** [review]

**Comment by ljflores** [comment]
jenkins test make check arm64

**Comment by ljflores** [comment]
jenkins test make check arm64

**Comment by pdvian** [comment]
The pacific upgrade tests were successful and failures are not related to PR#46838 (or prometheus upgrade test)
http://pulpito.front.sepia.ceph.com/pdhange-2022-07-15_00:43:02-upgrade:pacific-x:stress-split-wip-pdhange-testing-distro-default-smithi/

**Comment by pdvian** [comment]
FYI used pacific upgrade testcase from #47024 to test this PR.

**Comment by ljflores** [comment]
@yuriw can you add this to your next batch?

**Comment by kamoltat** [comment]
@yuriweinstein Rados approved

Related Failures:

/a/yuriw-2022-07-22_03:30:40-rados-wip-yuri3-testing-2022-07-21-1604-distro-default-smithi/6943775

due to [ceph/ceph: Pull Request 46036](https://github.com/ceph/ceph/pull/46036)

Unrelated Failures already with Tracker:
[Bug #52124: Invalid read of size 8 in handle_recovery_delete() - RADOS - Ceph](https://tracker.ceph.com/issues/52124)
[Bug #52321: qa/tasks/rook times out: 'check osd count' reached maximum tries (90) after waiting for 900 seconds - Orchestrator - Ceph](https://tracker.ceph.com/issues/52321)
[Bug #56652: cephadm/test_repos.sh: rllib.error.HTTPError: HTTP Error 504: Gateway Timeout - Orchestrator - Ceph](https://tracker.ceph.com/issues/56652)
[Bug #55001: rados/test.sh: Early exit right after LibRados global tests complete - RADOS - Ceph](https://tracker.ceph.com/issues/55001)
Bug #53768: timed out waiting for admin_socket to appear after osd.2 restart in thrasher/defaults workload/small-objects  - crimson - Ceph
[Bug #48819: fsck error: found stray (per-pg) omap data on omap_head - bluestore - Ceph](https://tracker.ceph.com/issues/48819)
[Bug #55853: test_cls_rgw.sh: failures in 'cls_rgw.index_list' and 'cls_rgw.index_list_delimited` - rgw - Ceph](https://tracker.ceph.com/issues/55853)
[Bug #52652: ERROR: test_module_commands (tasks.mgr.test_module_selftest.TestModuleSelftest) - mgr - Ceph](https://tracker.ceph.com/issues/52652)
[Bug #55142: [ERR] : Unhandled exception from module 'devicehealth' while running on mgr.gibba002.nzpbzu: disk I/O error - cephsqlite - Ceph](https://tracker.ceph.com/issues/55142)
[Bug #44587: failed to write <pid> to cgroup.procs: - Orchestrator - Ceph](https://tracker.ceph.com/issues/44587)
[Bug #56716: RuntimeError: ceph version 16.2.10-515.g3bc1d6b2 was not installed, found 16.2.10-513.gc2f1041a.el8. - teuthology - Ceph](https://tracker.ceph.com/issues/56716)

Unrelated Failures without Tracker:
[Bug #57015: bluestore::NCB::__restore_allocator::No Valid allocation info on disk (empty file) - RADOS - Ceph](https://tracker.ceph.com/issues/57015)
Infrastructure: [Bug #56717: The package cache file is corrupted - teuthology - Ceph](https://tracker.ceph.com/issues/56717)

**Pull request merged**
