### PR TITLE
 [DNM] hammer: rgw: S3 authentication subsystem should be able to use admin credentials for accessing Keystone

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/14721

### CODE REVIEW

**Comment by dachary** [comment]
@yehudasa does this backport look good to merge ? It passed a run of the hammer rgw suite ( see http://tracker.ceph.com/issues/14692#note-15 ) except one occurrence of a transient bug (Max retries exceeded with url: /metadata/incremental).

**Comment by dachary** [comment]
@yehudasa ping ?

**Comment by smithfarm** [comment]
@yehudasa This backport is staged for 0.94.7. Two weeks ago it passed one run of the hammer rgw suite and just now it passed another. There was some environmental noise and failed jobs had to be re-run twice, but it qualifies as a pass. For details see: http://tracker.ceph.com/issues/14692#note-36

Does the backport look good to merge?

**Comment by yehudasa** [comment]
@smithfarm I think that we may also need to pull in the admin token caching PR with it, otherwise it's going to have some performance implications.

**Comment by smithfarm** [comment]
@theanalyst Do you know which PR is the "admin token caching PR" that @yehudasa referred to?

**Comment by smithfarm** [comment]
Looks like it could be #7630 which does not look like it's been backported.

**Comment by smithfarm** [comment]
Marking DNM until http://tracker.ceph.com/issues/16111 is staged.

**Comment by smithfarm** [comment]
This backport depends on #7630 - a feature which hasn't been backported to hammer yet.

**Comment by smithfarm** [comment]
Since http://tracker.ceph.com/issues/16110 is a dependency of this issue and will not be backported, this issue will not be backported either.

**Pull request closed without merging**
