### PR TITLE
mon: enable msgr2 when legacy port is not 3300

### PR DESCRIPTION
**Pull request by liuchang0812**
Signed-off-by: Chang Liu <liuchang0812@gmail.com>

Hi, @liewegas @tchaikov . Could we relax this port check ?  in some clusters, we are using different ports in MONs. currently `mon enable-msgr2` command enables msgr2 only when the legacy port is 6789. thanks!

```
[root@10 ~]# ceph mon dump
dumped monmap epoch 4
epoch 4
fsid 36cda771-938a-492b-8663-0b2566a48204
last_changed 2019-11-12 10:43:19.686519
created 2019-11-12 10:14:48.396827
min_mon_release 14 (nautilus)
0: [v2:10.104.150.218:3300/0,v1:10.104.150.218:6789/0] mon.10.104.150.218-CLUSTERMON_A
1: v1:10.104.153.16:6790/0 mon.10.104.153.16-CLUSTERMON_B
2: v1:10.104.61.119:6791/0 mon.10.104.61.119-CLUSTERMON_C
```

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by tchaikov** [comment]
@liuchang0812 could you file a ticket on tracker?

**Comment by liewegas** [comment]
The only concern here is that a port != 6789 usually means that 6789 is used by some other cluster, and when that's the case, switching the mon to 3300 is likely to conflict.  For example, if 2 mons on the same cluster are on different ports, this command will break the cluster by preventing one or more mons from being able to bind and start.

Note that you can always convert these mons manually with ``ceph mon set-addrs <name> <addrvec>``...

**Comment by liewegas** [comment]
(For example, if I do vstart with MON=3 and --msgr1 and then run the enable-msgr2 command, the cluster breaks, and it is very tedious to fix.)

**Comment by liuchang0812** [comment]
> (For example, if I do vstart with MON=3 and --msgr1 and then run the enable-msgr2 command, the cluster breaks, and it is very tedious to fix.)

thanks @liewegas @tchaikov . 

to fix this case (2+ MONs on one machine ), we could increase the port number when there are another MON on the machine, for example, MON_A on 3300, MON_B on 3301.  


> The only concern here is that a port != 6789 usually means that 6789 is used by some other cluster, and when that's the case, switching the mon to 3300 is likely to conflict.

great catch. and, if there are two clusters on a machine, one cluster uses msgr2 on 3300, one cluster uses msgr1 on 6789.  `mon enable-msgr2` command is dangerous too.  should we add `--yes-i-really-mean-it` here?

**Pull request closed without merging**
