### PR TITLE
tools/cephfs-shell: fix listing of symbolic links

### PR DESCRIPTION
**Pull request by varshar16**
Fixes: https://tracker.ceph.com/issues/48912
Signed-off-by: Varsha Rao <varao@redhat.com>

~Depends on PR https://github.com/ceph/ceph/pull/39664~

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by varshar16** [comment]
Fixed flake8 issues

**Comment by batrick** [comment]
please rebase

**Comment by varshar16** [comment]
> please rebase

Done.

**Comment by varshar16** [comment]
jenkins retest this please

**Comment by batrick** [comment]
@varshar16 please rebase to fix the dead jenkins job.

**Comment by varshar16** [comment]
> @varshar16 please rebase to fix the dead jenkins job.

Done

**Review by batrick — APPROVED** [review]

**Review by rishabh-d-dave — APPROVED** [review]

**Comment by batrick** [comment]
https://pulpito.ceph.com/pdonnell-2021-03-09_03:27:39-fs-wip-pdonnell-testing-20210308.214827-distro-basic-smithi/

Failures are:

- https://tracker.ceph.com/issues/49500
- https://tracker.ceph.com/issues/48805
- https://tracker.ceph.com/issues/48773
- https://tracker.ceph.com/issues/45434
- https://tracker.ceph.com/issues/49240
- https://tracker.ceph.com/issues/49466
- https://tracker.ceph.com/issues/49684
- https://tracker.ceph.com/issues/48771

**Pull request merged**
