### PR TITLE
jewel: rbd-nbd IO hang

### PR DESCRIPTION
**Pull request by dachary**
http://tracker.ceph.com/issues/17262

### CODE REVIEW

**Comment by dachary** [comment]
<pre>
  CXX      test/librbd/operation/unittest_librbd-test_mock_SnapshotRemoveRequest.o
  CXX      test/librbd/operation/unittest_librbd-test_mock_SnapshotRollbackRequest.o
test/librbd/operation/test_mock_ResizeRequest.cc: In member function ‘virtual void librbd::operation::TestMockOperationResizeRequest_FlushCacheError_Test::TestBody()’:
test/librbd/operation/test_mock_ResizeRequest.cc:298:315: error: no matching function for call to ‘librbd::operation::TestMockOperationResizeRequest_FlushCacheError_Test::when_resize(librbd::MockImageCtx&, uint64_t, bool, int, bool)’
   ASSERT_EQ(-EINVAL, when_resize(mock_image_ctx, ictx->size / 2, true, 0, false));
                                                                                                                                                                                                                                                                                                                           ^
test/librbd/operation/test_mock_ResizeRequest.cc:298:315: note: candidate is:
test/librbd/operation/test_mock_ResizeRequest.cc:136:7: note: int librbd::operation::TestMockOperationResizeRequest::when_resize(librbd::MockImageCtx&, uint64_t, uint64_t, bool)
   int when_resize(MockImageCtx &mock_image_ctx, uint64_t new_size,
       ^
test/librbd/operation/test_mock_ResizeRequest.cc:136:7: note:   candidate expects 4 arguments, 5 provided
</pre>
MockImageCtx should be MockImageTestCtx or something, introduced *after* this commit but backported *before* it

**Comment by dillaman** [comment]
@dachary Do you need help with this PR so we can get the nbd tests functional?

**Comment by dachary** [comment]
I think I can manage it, I'll ask for help if I'm stuck. Will work on it in the next 24h.

**Comment by dachary** [comment]
jenkins test this please (rbd core)

**Comment by dachary** [comment]
building in gitbuilder under wip-17262-jewel

**Comment by dachary** [comment]
jenkins test this please (rbd failure again)

**Comment by dillaman** [comment]
retest this please

**Comment by dachary** [comment]
<pre>
filter="rbd/thrash/{base/install.yaml clusters/{fixed-2.yaml openstack.yaml} fs/xfs.yaml msgr-failures/few.yaml thrashers/cache.yaml workloads/rbd_fsx_nbd.yaml}"
teuthology-suite --priority 101 --suite rbd --filter="$filter" --suite-branch jewel --email loic@dachary.org --ceph wip-17262-jewel --machine-type smithi
</pre>

* **running** http://pulpito.ceph.com/loic-2016-10-24_14:51:44-rbd-wip-17262-jewel---basic-smithi/

**Comment by dillaman** [comment]
@dachary hmm -- assertion failure in the daemon on one test run but no coredump generated.

**Comment by dachary** [comment]
Re-running the above to assert how transient (or not) the failure is 

* **running** http://pulpito.ceph.com/loic-2016-10-24_15:57:09-rbd-wip-17262-jewel---basic-smithi/

**Comment by dillaman** [comment]
@dachary I'm hoping it's just due to the fact that PR #10869 hasn't been merged. Hard to tell since the assertion failure reason wasn't logged.

**Comment by dachary** [comment]
@dillaman the thrashers/default job passed once and the thrashers/cache passed once. Do you think this is good enough to merge ? Or should we wait for PR #10869 to be merged and maybe improve the situation ?

**Comment by dillaman** [comment]
@dachary Let me re-run it a few times w/ rbd debugging enabled to see if I can repeat it today.

**Comment by dillaman** [comment]
@dachary This failure is something different -- I am going to try to get a coredump out of this.

**Comment by dillaman** [comment]
@dachary This PR is good to merge -- but I need to open a new ticket for the associated crash since it's high-pri and isn't related to this change.

**Pull request merged**
