### PR TITLE
qa/worksuits: build the iozone from source before running it

### PR DESCRIPTION
**Pull request by lxbsz**
Fixes: https://tracker.ceph.com/issues/43600
Signed-off-by: Xiubo Li <xiubli@redhat.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by tchaikov** [comment]
i'd avoid rebuilding iozone from source every time we test it. could you rebuild the rpm package and upload it to http://apt-mirror.front.sepia.ceph.com/lab-extras/8/ ?

**Comment by lxbsz** [comment]
> i'd avoid rebuilding iozone from source every time we test it. 

The iozone project building is very fast, around 1 minutes. 

> could you rebuild the rpm package and upload it to http://apt-mirror.front.sepia.ceph.com/lab-extras/8/ ?

Yeah, if that looks not graceful I will rebuild the package and upload to the extra repo.

Thanks.

**Comment by gregsfortytwo** [comment]
Patrick has actually suggested just dropping these tests and we’ve had issues with hosting packages in the past so building in-demand sounds like a good fix for now.

**Comment by tchaikov** [comment]
> > i'd avoid rebuilding iozone from source every time we test it.
> 
> The iozone project building is very fast, around 1 minutes.

still relying on a random thirty party github repo for testing is not an ideal solution.

> 
> > could you rebuild the rpm package and upload it to http://apt-mirror.front.sepia.ceph.com/lab-extras/8/ ?
> 
> Yeah, if that looks not graceful I will rebuild the package and upload to the extra repo.

i recommend so.

> 
> Thanks.

**Comment by lxbsz** [comment]
> > > i'd avoid rebuilding iozone from source every time we test it.
> > 
> > 
> > The iozone project building is very fast, around 1 minutes.
> 
> still relying on a random thirty party github repo for testing is not an ideal solution.
> 
> > > could you rebuild the rpm package and upload it to http://apt-mirror.front.sepia.ceph.com/lab-extras/8/ ?
> > 
> > 
> > Yeah, if that looks not graceful I will rebuild the package and upload to the extra repo.
> 
> i recommend so.
> 
> > Thanks.

Since the license issue, I presumably the ubuntu will also deprecated the iozone in future. So then after the ubuntu upgrade, we sill hitting the same issue. Is there a extra repo for the Ubuntu ?

**Comment by tchaikov** [comment]
> > > > i'd avoid rebuilding iozone from source every time we test it.
> > > 
> > > 
> > > The iozone project building is very fast, around 1 minutes.
> > 
> > 
> > still relying on a random thirty party github repo for testing is not an ideal solution.
> > > > could you rebuild the rpm package and upload it to http://apt-mirror.front.sepia.ceph.com/lab-extras/8/ ?
> > > 
> > > 
> > > Yeah, if that looks not graceful I will rebuild the package and upload to the extra repo.
> > 
> > 
> > i recommend so.
> > > Thanks.
> 
> Since the license issue, presumably the ubuntu will also deprecate the iozone in future. So then after the ubuntu upgraded, we will hit the same issue agin. Is there a extra repo for the Ubuntu ?

i disagree. like debian's non-free section, ubuntu offers multiverse repo which contains non-free softwares.

**Comment by lxbsz** [comment]
> Patrick has actually suggested just dropping these tests and we’ve had issues with hosting packages in the past so building in-demand sounds like a good fix for now.

If so, building from source seems good choice here for now...

**Comment by lxbsz** [comment]
> > Since the license issue, presumably the ubuntu will also deprecate the iozone in future. So then after the ubuntu upgraded, we will hit the same issue agin. Is there a extra repo for the Ubuntu ?
> 
> i disagree. like debian's non-free section, ubuntu offers multiverse repo which contains non-free softwares.

Okay, let me try to push the package to the extra repo later.

**Comment by tchaikov** [comment]
@lxbsz i just built the package and working with @djgalloway to get it uploaded.

**Comment by lxbsz** [comment]
> @lxbsz i just built the package and working with @djgalloway to get it uploaded.

That's cool.

**Comment by lxbsz** [comment]
> i'd suggest install iozone from http://apt-mirror.front.sepia.ceph.com/lab-extras/8/ .

BTW, should add the lab-extra repo in the sh script ? Or in teuthology ?

**Comment by tchaikov** [comment]
> > i'd suggest install iozone from http://apt-mirror.front.sepia.ceph.com/lab-extras/8/ .
> 
> BTW, should add the lab-extra repo in the sh script ? Or in teuthology ?

it's already enabled by https://github.com/ceph/ceph-cm-ansible/blob/master/roles/testnode/defaults/main.yml#L2 and https://github.com/ceph/ceph-cm-ansible/blob/b3e1ea5a327a3d28399e7c550f176d369fb4e2cd/roles/testnode/vars/redhat_8.yml#L6

FWIW, you could add iozone to https://github.com/ceph/ceph-cm-ansible/blob/b3e1ea5a327a3d28399e7c550f176d369fb4e2cd/roles/testnode/vars/redhat_8.yml#L64 or add it to the `extra_packages` list of `install` task.

**Comment by lxbsz** [comment]
> > > i'd suggest install iozone from http://apt-mirror.front.sepia.ceph.com/lab-extras/8/ .
> > 
> > 
> > BTW, should add the lab-extra repo in the sh script ? Or in teuthology ?
> 
> it's already enabled by https://github.com/ceph/ceph-cm-ansible/blob/master/roles/testnode/defaults/main.yml#L2 and https://github.com/ceph/ceph-cm-ansible/blob/b3e1ea5a327a3d28399e7c550f176d369fb4e2cd/roles/testnode/vars/redhat_8.yml#L6
> 
> FWIW, you could add iozone to https://github.com/ceph/ceph-cm-ansible/blob/b3e1ea5a327a3d28399e7c550f176d369fb4e2cd/roles/testnode/vars/redhat_8.yml#L64 or add it to the `extra_packages` list of `install` task.

Okay. Thanks

**Comment by lxbsz** [comment]
https://github.com/ceph/ceph-cm-ansible/pull/561

**Comment by lxbsz** [comment]
> Will install the iozone package from the spia lab repo for centos/rhel 8:
> 
> [ceph/ceph-cm-ansible#561](https://github.com/ceph/ceph-cm-ansible/pull/561)

The ceph-cm-ansible PR has been merged, and the issue has been fixed, will close it.
Thanks @tchaikov very much for the help here and the iozone package.
BRs

**Pull request closed without merging**
