### PR TITLE
rgw/multisite: warn if bucket chown command is run on non-master zone

### PR DESCRIPTION
**Pull request by smanjara**
Signed-off-by: Shilpa Jagannath <smanjara@redhat.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by cbodley** [comment]
@smanjara should this get a nautilus backport too?

**Comment by smanjara** [comment]
> @smanjara should this get a nautilus backport too?

@cbodley  yes, it needs a backport.

**Comment by cbodley** [comment]
ok, can you please add `Fixes: https://tracker.ceph.com/issues/43884` to the commit message?

**Comment by smanjara** [comment]
> ok, can you please add `Fixes: https://tracker.ceph.com/issues/43884` to the commit message?

Done. Thanks for opening the tracker.

**Comment by cbodley** [comment]
thanks for the fix! lets merge this once the checks pass

**Comment by cbodley** [comment]
jenkins test make check

**Pull request merged**
