### PR TITLE
do_cmake:sh: use newer gcc if available

### PR DESCRIPTION
**Pull request by tchaikov**
despite that we are using clang in `run-make-check.sh`, `do_cmake.sh`
is still used by some workflows like jenkins' ceph-pr-api job.
now that we've migrated to C++20, we need to use GCC-11 or up for
building the tree. GCC-11 is installed from PPA repo in
`install-deps.sh`, but to avoid interfere with the build of older
branches which do not use GCC-11, as their builds might break if
we use GCC-11 for building them. we don't use the alternative machinary
to point gcc to gcc-11, see 8f342a32ce4a236c45c67497ae34f508e032a9e1.

so, in this change, we try to use the newest GCC in system when
running `do_cmake.sh`.

Signed-off-by: Kefu Chai <tchaikov@gmail.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [x] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Review by cyx1231st — APPROVED** [review]

**Comment by tchaikov** [comment]
jenkins test make check

**Comment by tchaikov** [comment]
jenkins test make check

**Comment by cherohey** [comment]
I'm run do_cmake.sh with gcc (GCC) 11.2.1 20210728 (Red Hat 11.2.1-1), and get “collect2: error: ld returned 1 exit status”

FAILED: cmTC_96739
: && /opt/rh/gcc-toolset-11/root/usr/bin/gcc   CMakeFiles/cmTC_96739.dir/src.c.o -o cmTC_96739   && :
/opt/rh/gcc-toolset-11/root/usr/bin/ld: CMakeFiles/cmTC_96739.dir/src.c.o: in function `main':
src.c:(.text+0x2d): undefined reference to `pthread_create'
/opt/rh/gcc-toolset-11/root/usr/bin/ld: src.c:(.text+0x39): undefined reference to `pthread_detach'
/opt/rh/gcc-toolset-11/root/usr/bin/ld: src.c:(.text+0x45): undefined reference to `pthread_cancel'
/opt/rh/gcc-toolset-11/root/usr/bin/ld: src.c:(.text+0x56): undefined reference to `pthread_join'
collect2: error: ld returned 1 exit status

**Comment by cherohey** [comment]
and 

FAILED: cmTC_8c1f8
: && /opt/rh/gcc-toolset-11/root/usr/bin/gcc -DCHECK_FUNCTION_EXISTS=pthread_create  CMakeFiles/cmTC_8c1f8.dir/CheckFunctionExists.c.o -o cmTC_8c1f8  -lpthreads && :
/opt/rh/gcc-toolset-11/root/usr/bin/ld: cannot find -lpthreads
collect2: error: ld returned 1 exit status

**Comment by cherohey** [comment]
: && /opt/rh/gcc-toolset-11/root/usr/bin/gcc -DCHECK_FUNCTION_EXISTS=sigdescr_np  CMakeFiles/cmTC_ddc8d.dir/CheckFunctionExists.c.o -o cmTC_ddc8d   && :
/opt/rh/gcc-toolset-11/root/usr/bin/ld: CMakeFiles/cmTC_ddc8d.dir/CheckFunctionExists.c.o: in function `main':
CheckFunctionExists.c:(.text+0x10): undefined reference to `sigdescr_np'
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.

**Comment by cherohey** [comment]
: && /opt/rh/gcc-toolset-11/root/usr/bin/gcc -DCHECK_FUNCTION_EXISTS=pthread_set_name_np  CMakeFiles/cmTC_55af0.dir/CheckFunctionExists.c.o -o cmTC_55af0  -lpthread && :
/opt/rh/gcc-toolset-11/root/usr/bin/ld: CMakeFiles/cmTC_55af0.dir/CheckFunctionExists.c.o: in function `main':
CheckFunctionExists.c:(.text+0x10): undefined reference to `pthread_set_name_np'
collect2: error: ld returned 1 exit status

**Pull request merged**
