### PR TITLE
infernalis: Setting ACL on Object removes ETag

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/13819

### CODE REVIEW

**Comment by Abhishekvrshny** [comment]
@yehudasa this backport passed the rgw suite (http://pulpito.ceph.com/loic-2015-11-27_13:58:16-rgw-infernalis-backports---basic-multi/), do you think it can be merged ?

**Comment by Abhishekvrshny** [comment]
@yehudasa gentle reminder.

**Comment by dachary** [comment]
@yehudasa does this backport look good to merge ? It passed a run of the infernalis rgw suite ( see http://tracker.ceph.com/issues/13750#note-21 ) except one occurrence of a known bug (http://tracker.ceph.com/issues/14361).

**Comment by yehudasa** [comment]
@dachary ack

**Comment by odivlad** [comment]
@dachary, if this PR looks good, could you please merge it to be released in next version?
This problem prevents us from upgrading to infernalis...
As I understand, it can be release in 9.2.2...

**Comment by dachary** [comment]
infernalis has been EOL for a few months now, there does not seem to be a need for another release, even for upgrade purposes

**Pull request closed without merging**
