### PR TITLE
nautilus: cephfs: Allow mount.ceph to get mount info from ceph configs and keyrings

### PR DESCRIPTION
**Pull request by smithfarm**
backport tracker: https://tracker.ceph.com/issues/41890

---

backport of

* https://github.com/ceph/ceph/pull/29817
* https://github.com/ceph/ceph/pull/30462

parent trackers:

* https://tracker.ceph.com/issues/16656
* https://tracker.ceph.com/issues/41892

this backport was staged using https://github.com/ceph/ceph/blob/master/src/script/ceph-backport.sh

### CODE REVIEW

**Comment by smithfarm** [comment]
DNM because of https://tracker.ceph.com/issues/41890#change-146656

"Should pick up backport for https://tracker.ceph.com/issues/41892 as well once it's merged."

**Comment by jtlayton** [comment]
Looks good to me. Note that these patches don't depend on https://tracker.ceph.com/issues/41892 , so it's OK to merge them before that PR is merged.

**Comment by smithfarm** [comment]
```
1 tests failed out of 171

Total Test time (real) = 1077.66 sec

The following tests FAILED:
	  7 - run-tox-mgr-ansible (Failed)
```

**Comment by smithfarm** [comment]
jenkins test make check

**Comment by smithfarm** [comment]
@jlayton If https://tracker.ceph.com/issues/41892 is a follow-on for the feature this PR is backporting, then it makes sense to include its backport in this PR. If we backport that one separately, it's not inconveivable that the follow-on might go in first...

**Comment by batrick** [comment]
needs rebase

**Comment by yuriw** [comment]
@smithfarm needs rebase

--- pr 30521 --- pulling https://github.com/smithfarm/ceph.git branch wip-41890-nautilus
remote: Enumerating objects: 43, done.
remote: Counting objects: 100% (43/43), done.
remote: Total 63 (delta 43), reused 43 (delta 43), pack-reused 20
Unpacking objects: 100% (63/63), done.
From https://github.com/smithfarm/ceph
 * branch                  wip-41890-nautilus -> FETCH_HEAD
Auto-merging src/mount/mount.ceph.c
CONFLICT (content): Merge conflict in src/mount/mount.ceph.c
Auto-merging qa/tasks/cephfs/kernel_mount.py
Auto-merging debian/control
Auto-merging ceph.spec.in
Automatic merge failed; fix conflicts and then commit the result.
Traceback (most recent call last):
  File "/home/yuriw/wip_master/src/script/build-integration-branch", line 67, in <module>
    assert not r
AssertionError

**Comment by smithfarm** [comment]
```
172/172 Test #166: unittest_rbd_mirror .....................***Timeout 3600.03 sec
...
Failed to load class: cas (/home/jenkins-build/build/workspace/ceph-pull-requests/build/lib/libcls_cas.so): /home/jenkins-build/build/workspace/ceph-pull-requests/build/lib/libcls_cas.so: undefined symbol: _Z27cls_cxx_chunk_write_and_setPviiPN4ceph6buffer7v14_2_04listEjS4_i
Failed to load class: cephfs (/home/jenkins-build/build/workspace/ceph-pull-requests/build/lib/libcls_cephfs.so): /home/jenkins-build/build/workspace/ceph-pull-requests/build/lib/libcls_cephfs.so: undefined symbol: _ZTI10PGLSFilter
Failed to load class: hello (/home/jenkins-build/build/workspace/ceph-pull-requests/build/lib/libcls_hello.so): /home/jenkins-build/build/workspace/ceph-pull-requests/build/lib/libcls_hello.so: undefined symbol: _ZTI10PGLSFilter
Failed to load class: log (/home/jenkins-build/build/workspace/ceph-pull-requests/build/lib/libcls_log.so): /home/jenkins-build/build/workspace/ceph-pull-requests/build/lib/libcls_log.so: undefined symbol: _Z23cls_cxx_map_read_headerPvPN4ceph6buffer7v14_2_04listE
```

**Comment by smithfarm** [comment]
jenkins test make check

**Comment by yuriw** [comment]
[wip-yuri-testing-2019-11-17-1559-nautilus](https://trello.com/c/4yagFli7/766-wip-yuri-testing-2019-11-17-1559-nautilus)

**Pull request merged**
