### PR TITLE
qa/rgw: fix for ragweed upgrade suite

### PR DESCRIPTION
**Pull request by cbodley**

### CODE REVIEW

**Comment by cbodley** [comment]
http://pulpito.ceph.com/cbodley-2018-03-08_15:18:48-rgw:upgrade-wip-cbodley-testing-distro-basic-smithi/

**Comment by cbodley** [comment]
@yehudasa with this change, it looks like we're generating the right list of tasks. but after the upgrade, the `ceph.restart` task for `[osd.0, osd.1, osd.2]` is failing with a bunch of `FAILED assert(struct_v >= 10)`

@gregsfortytwo pointed out that upgrades from kraken -> master aren't supported. should this upgrade test start with luminous instead?

**Comment by yehudasa** [comment]
@cbodley probably

**Comment by tchaikov** [comment]
retest this please

**Comment by cbodley** [comment]
closing this one. i'm testing a separate branch that adds ragweed to the existing upgrade/luminous-x suite

**Pull request closed without merging**
