### PR TITLE
mgr: In plugins 'module' classes need not to be called "Module" anymore.

### PR DESCRIPTION
**Pull request by tchaikov**
Fixes: http://tracker.ceph.com/issues/17454
Signed-off-by: bhavishyagopesh <bhavishyagopesh@gmail.com>
Signed-off-by: Kefu Chai <kchai@redhat.com>

### CODE REVIEW

**Comment by tchaikov** [comment]
http://pulpito.ceph.com/kchai-2017-10-25_10:30:53-rados-wip-kefu-testing-2017-10-25-1600-distro-basic-mira/

**Comment by tchaikov** [comment]
need to rebase after https://github.com/ceph/ceph/pull/16651/commits/213cbd6e0f677b7ba9e6b60c41333910624d3ef0 is merged

**Comment by tchaikov** [comment]
@jcsp mind taking a look?

**Comment by jcsp** [comment]
Looks good, let's also update the docs in this PR, in plugins.rst where it says "create a class     
named ``Module`` " and later "a class called ``StandbyModule``"

**Comment by jcsp** [comment]
Let's run the rados/mgr suite on this before merging, as it has several new tests since 213cbd6 merged

**Comment by tchaikov** [comment]
being tested at http://pulpito.ceph.com/kchai-2017-11-02_08:11:58-rados-wip-17454-kefu-distro-basic-mira/

**Comment by tchaikov** [comment]
@jcsp the tests failed: http://pulpito.ceph.com/kchai-2017-11-02_08:11:58-rados-wip-17454-kefu-distro-basic-mira/

but the master branch also failed http://pulpito.ceph.com/kchai-2017-11-02_09:53:26-rados-master-distro-basic-mira/

**Comment by tchaikov** [comment]
http://pulpito.ceph.com/kchai-2017-11-02_11:57:41-rados-wip-17454-kefu-distro-basic-mira/

**Comment by liewegas** [comment]
http://pulpito.ceph.com/sage-2017-11-03_02:06:42-rados-wip-sage-testing-2017-11-02-1619-distro-basic-smithi/

**Comment by liewegas** [comment]
hmm, passed for me

**Pull request merged**
