### PR TITLE
crimson: don't retain InternalClientRequest on interval change even if primary does not change

### PR DESCRIPTION
**Pull request by athanatos**
Fixes: https://tracker.ceph.com/issues/68068

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Comment by athanatos** [comment]
Not yet tested

**Review by xxhdx1985126 — APPROVED** [review]
LGTM, approving despite the minor make check failure.

**Review by Matan-B — APPROVED** [review]

**Comment by athanatos** [comment]
jenkins test make check

**Comment by athanatos** [comment]
jenkins test api

**Comment by athanatos** [comment]
jenkins test make check

**Comment by athanatos** [comment]
jenkins test make check

**Comment by athanatos** [comment]
https://pulpito.ceph.com/sjust-2024-09-18_06:11:27-crimson-rados-wip-sjust-crimson-testing-2024-09-17-distro-default-smithi/
rerun: https://pulpito.ceph.com/sjust-2024-09-18_22:08:13-crimson-rados-wip-sjust-crimson-testing-2024-09-17-distro-default-smithi
rerun (main): https://pulpito.ceph.com/sjust-2024-09-27_21:05:42-crimson-rados-wip-sjust-testing-baseline-2024-09-24-distro-default-smithi

Test runs seem ok (rerun with main saw more failures)

**Comment by athanatos** [comment]
jenkins test api

**Pull request merged**
