### PR TITLE
spdk: enable SPDK on AArch64 by default

### PR DESCRIPTION
**Pull request by tone-zhang**
Enable SPDK in Ceph on AArch64 by default.

Signed-off-by: Tone Zhang <tone.zhang@arm.com>

### CODE REVIEW

**Comment by tchaikov** [comment]
could you prefix the title of your commit message with the subcomponent your are changing ? see https://github.com/ceph/ceph/blob/master/SubmittingPatches.rst#3-describe-your-changes

**Comment by tone-zhang** [comment]
@tchaikov Kefu, thanks for your remind, I will update. :)

**Comment by tone-zhang** [comment]
@tchaikov Let me have a check the compiling error.

**Comment by tchaikov** [comment]
@tone-zhang you might want to update the SPDK submodule and try again?

**Comment by tchaikov** [comment]
@tone-zhang it's fixed by https://github.com/spdk/spdk/commit/29be88fab6bb026df27c93ee89c61965b3c43133. lemme update the submodule.

**Comment by tchaikov** [comment]
#20134

**Comment by tone-zhang** [comment]
@tchaikov 
Kefu, thanks a lot for your update! :)

**Comment by tchaikov** [comment]
closing in favor of #20134

**Pull request closed without merging**
