### PR TITLE
qa/distros: Remove stale kubic distros

### PR DESCRIPTION
**Pull request by sebastian-philipp**
Cause they're broken

Signed-off-by: Sebastian Wagner <sewagner@redhat.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by sebastian-philipp** [comment]
relates to #43021

**Comment by ideepika** [comment]
@sebastian-philipp removing all kubic would also mean we don't have any testing for ubuntu focal + RHEL, we might want to add new files without kubic stuff, if we want to test podman's behaviour on them.

**Review by ideepika — APPROVED** [review]
these should be safe to remove, since not used in any suites.

**Comment by sebastian-philipp** [comment]
> @sebastian-philipp removing all kubic would also mean we don't have any testing for 
> ubuntu focal + 
We still have https://github.com/ceph/ceph/blob/master/qa/distros/all/ubuntu_20.04.yaml using docker.
> RHEL
https://github.com/ceph/ceph/pull/43021/files#diff-c09f47a7208c58db163f9dde92b9a235cce7a032f6dc55965184298c288ed4f2
>, we might want to add new files without kubic stuff, if we want to test podman's behaviour on them(if I am not missing any context from past)
I think with https://github.com/ceph/ceph/blob/master/qa/distros/podman/centos_8.3_container_tools_3.0.yaml we're mostly good to go right now. WDYT?

**Comment by ideepika** [comment]
> > @sebastian-philipp removing all kubic would also mean we don't have any testing for
> > ubuntu focal +
> 
> We still have https://github.com/ceph/ceph/blob/master/qa/distros/all/ubuntu_20.04.yaml using docker.
> 
> > RHEL
> 
> https://github.com/ceph/ceph/pull/43021/files#diff-c09f47a7208c58db163f9dde92b9a235cce7a032f6dc55965184298c288ed4f2
> 
> > , we might want to add new files without kubic stuff, if we want to test podman's behaviour on them(if I am not missing any context from past)
> 
> I think with https://github.com/ceph/ceph/blob/master/qa/distros/podman/centos_8.3_container_tools_3.0.yaml we're mostly good to go right now. WDYT?

yep, that sounds fine, we might want to work on scattered symlinks in future though. :)

**Comment by sebastian-philipp** [comment]
> 
> yep, that sounds fine, we might want to work on scattered symlinks in future though. :)

https://github.com/ceph/ceph/pull/43040

**Pull request merged**
