### PR TITLE
cephadm: only support --name and --fsid for logs command

### PR DESCRIPTION
**Pull request by adk3798**
Fixes: https://tracker.ceph.com/issues/47169

Signed-off-by: Adam King <adking@redhat.com>

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Review by jschmid1 — APPROVED** [review]

**Comment by jschmid1** [comment]
https://pulpito.ceph.com/jschmid-2020-10-06_13:23:40-rados:cephadm-wip-jschmid1-testing-2020-10-06-1118-distro-basic-smithi/

**Review by mgfritch — COMMENTED** [review]
Do we really want to remove this option? It is somewhat nice to pass arbitrary args into journalctl....

for example:
```
$ cephadm logs --name nfs.foo.host1 -- -n 20 # last 20 lines
$ cephadm logs --name osd.1 -- -f # follow the log
```
?

**Comment by sebastian-philipp** [comment]
> > Do we really want to remove this option? It is somewhat nice to pass arbitrary args into journalctl....
> > for example:
> > ```
> > $ cephadm logs --name nfs.foo.host1 -- -n 20 # last 20 lines
> > $ cephadm logs --name osd.1 -- -f # follow the log
> > ```
> > 
> > 
> > ?
> 
> That's a fair point. Maybe we hold off on merging this one until we can get @sebastian-philipp opinion on it?

sounds good. can we add this use case to the man page then?

**Comment by adk3798** [comment]
Closing in favor of https://github.com/ceph/ceph/pull/37731

**Pull request closed without merging**
