### PR TITLE
mgr/dashboard: fix NFS issue if RGW is not configured properly

### PR DESCRIPTION
**Pull request by s0nea**
Except the ValueError (if one of the required RGW settings is missing) here in order to not return the object gateway as a possible storage backend.

Fixes: https://tracker.ceph.com/issues/43053
Signed-off-by: Tatjana Dehler <tdehler@suse.com>

## Checklist
- [x] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by votdev** [comment]
When i correctly understand @epuertat's tracker issue the problem should have been fixed with https://github.com/ceph/ceph/commit/7e7cac98116e76bc9e4c52ac47796e3fcd880667#diff-5953cf1fb459a29d91f0833f3495b72e, right?

**Comment by votdev** [comment]
I think this issue should be fixed this way as @epuertat already mentioned.
```
--- src/pybind/mgr/dashboard/settings.py	(revision a481d25f7fcf5feb474cccfb625e201819251e5e)
+++ src/pybind/mgr/dashboard/settings.py	(date 1580984936288)
@@ -91,13 +91,8 @@
 
 class SettingsMeta(type):
     def __getattr__(cls, attr):
-        default, stype = getattr(Options, attr)
-        if stype == bool and str(mgr.get_module_option(
-                attr,
-                default)).lower() == 'false':
-            value = False
-        else:
-            value = stype(mgr.get_module_option(attr, default))
+        default, _ = getattr(Options, attr)
+        value = mgr.get_module_option(attr, default)
         return value
 
     def __setattr__(cls, attr, value):
```

**Comment by votdev** [comment]
> I think this issue should be fixed this way as @epuertat already mentioned.
> 
> ```
> --- src/pybind/mgr/dashboard/settings.py	(revision a481d25f7fcf5feb474cccfb625e201819251e5e)
> +++ src/pybind/mgr/dashboard/settings.py	(date 1580984936288)
> @@ -91,13 +91,8 @@
>  
>  class SettingsMeta(type):
>      def __getattr__(cls, attr):
> -        default, stype = getattr(Options, attr)
> -        if stype == bool and str(mgr.get_module_option(
> -                attr,
> -                default)).lower() == 'false':
> -            value = False
> -        else:
> -            value = stype(mgr.get_module_option(attr, default))
> +        default, _ = getattr(Options, attr)
> +        value = mgr.get_module_option(attr, default)
>          return value
>  
>      def __setattr__(cls, attr, value):
> ```

Or maybe better because the default value is already set here: https://github.com/ceph/ceph/blob/master/src/pybind/mgr/dashboard/settings.py#L187. This has to be evaluated.

I don't know if SettingsMeta is obsolete because there are done some checks in the `__setattr__` and `__delattr_` methods.

```
--- src/pybind/mgr/dashboard/settings.py	(revision a481d25f7fcf5feb474cccfb625e201819251e5e)
+++ src/pybind/mgr/dashboard/settings.py	(date 1580984936288)
@@ -91,13 +91,8 @@
 
 class SettingsMeta(type):
     def __getattr__(cls, attr):
-        default, stype = getattr(Options, attr)
-        if stype == bool and str(mgr.get_module_option(
-                attr,
-                default)).lower() == 'false':
-            value = False
-        else:
-            value = stype(mgr.get_module_option(attr, default))
+        return mgr.get_module_option(attr)
 
     def __setattr__(cls, attr, value):
```

**Comment by epuertat** [comment]
@votdev yeah, I was talking with @s0nea yesterday and shared with her my idea about how to better fix this. I think the `Settings` helper was great when the mgr lacked some features (typed options, defaults, etc), but now it provides all that stuff, I think it'd be better to simply convert Settings in a wrapper for `mgr.{get|set}_module_option`.

**Comment by s0nea** [comment]
I'm not really sure if we need the fix as it currently is to backport it to nautilus?

**Comment by epuertat** [comment]
@s0nea, this code has barely changed between Nautilus and master

**Comment by s0nea** [comment]
I'm closing the PR because it and the related issue are outdated and need to be updated/changed in general. Feel free to revise it.

**Pull request closed without merging**
