### PR TITLE
nautilus: mgr/dashboard: incorrect help message for minimum blob size

### PR DESCRIPTION
**Pull request by bk201**
http://tracker.ceph.com/issues/39664

### CODE REVIEW

**Comment by callithea** [comment]
jenkins test dashboard

**Comment by callithea** [comment]
jenkins test make check

**Comment by callithea** [comment]
jenkins test make check

**Comment by yuriw** [comment]
[wip-yuri2-testing-2019-05-16-1555-nautilus](https://trello.com/c/VvCEDimT/616-wip-yuri2-testing-2019-05-16-1555-nautilus)

**Pull request merged**
