### PR TITLE
luminous: cephfs: ceph-volume-client: allow setting mode of CephFS volumes

### PR DESCRIPTION
**Pull request by brtknr**
https://tracker.ceph.com/issues/37425

### CODE REVIEW

**Comment by tchaikov** [comment]
@brtknr thanks for backporting f5906585f3a7df823b904e86ba0a11ea81327e10 to luminous. but it would be ideal if you could instead `git cherry-pick -x` it into luminous. so the cherry-picked change can be connected this change.

cc @tombarron .

**Comment by brtknr** [comment]
@tchaikov done :)

**Comment by tombarron** [comment]
@brtknr Thanks!

**Comment by yuriw** [comment]
[wip-yuri2-testing-2018-12-19-1656-luminous](https://trello.com/c/55NDqzim/493-wip-yuri2-testing-2018-12-19-1656-luminous)

**Pull request merged**
