### PR TITLE
pacific: client: fix sync fs to force flush mdlog for all sessions

### PR DESCRIPTION
**Pull request by lxbsz**
backport tracker: https://tracker.ceph.com/issues/62916 and https://tracker.ceph.com/issues/62520

---

backport of https://github.com/ceph/ceph/pull/44255 and https://github.com/ceph/ceph/pull/52335
parent tracker: https://tracker.ceph.com/issues/44916 and https://tracker.ceph.com/issues/56698

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by vshankar** [comment]
jenkins retest this please

**Review by vshankar — CHANGES_REQUESTED** [review]
@lxbsz 

```
/home/jenkins-build/build/workspace/ceph-api/src/client/Client.cc:4813:34: error: base operand of '->' has non-pointer type 'MetaSession'
 4813 |     xlist<Inode*>::iterator p = s->dirty_list.begin();
      |                                  ^~
/home/jenkins-build/build/workspace/ceph-api/src/client/Client.cc: In member function 'void Client::_unmount(bool)':
/home/jenkins-build/build/workspace/ceph-api/src/client/Client.cc:6658:22: error: base operand of '->' has non-pointer type 'MetaSession'
 6658 |       for (auto p = s->dirty_list.begin(); !p.end(); ) {
```

**Comment by vshankar** [comment]
@lxbsz make check still fails which is odd. Requesting to check...

**Comment by vshankar** [comment]
@lxbsz - ceph api test - https://jenkins.ceph.com/job/ceph-api/63157/consoleFull#-14618762777725d52c-2930-43cb-b77a-ae0a919c2170

```
    -5> 2023-10-13T00:48:38.318+0000 7fd17ce2b640 10 monclient: get_auth_request con 0x559c20398800 auth_method 0
    -4> 2023-10-13T00:48:38.374+0000 7fd141f63640  5 client.6692 xattr_permission 0x559c1fbff000 = 0
    -3> 2023-10-13T00:48:38.374+0000 7fd141f63640  5 client.6692 xattr_permission 0x559c1fbff000 = 0
    -2> 2023-10-13T00:48:38.374+0000 7fd141f63640  2 client.6692 unmounting
    -1> 2023-10-13T00:48:38.386+0000 7fd141f63640 -1 /home/jenkins-build/build/workspace/ceph-api/src/client/MetaSession.h: In function 'MetaSession::~MetaSession()' thread 7fd141f63640 time 2023-10-13T00:48:38.378496+0000
/home/jenkins-build/build/workspace/ceph-api/src/client/MetaSession.h: 66: FAILED ceph_assert(caps.empty())
```

**Comment by lxbsz** [comment]
> @lxbsz - ceph api test - https://jenkins.ceph.com/job/ceph-api/63157/consoleFull#-14618762777725d52c-2930-43cb-b77a-ae0a919c2170
> 
> ```
>     -5> 2023-10-13T00:48:38.318+0000 7fd17ce2b640 10 monclient: get_auth_request con 0x559c20398800 auth_method 0
>     -4> 2023-10-13T00:48:38.374+0000 7fd141f63640  5 client.6692 xattr_permission 0x559c1fbff000 = 0
>     -3> 2023-10-13T00:48:38.374+0000 7fd141f63640  5 client.6692 xattr_permission 0x559c1fbff000 = 0
>     -2> 2023-10-13T00:48:38.374+0000 7fd141f63640  2 client.6692 unmounting
>     -1> 2023-10-13T00:48:38.386+0000 7fd141f63640 -1 /home/jenkins-build/build/workspace/ceph-api/src/client/MetaSession.h: In function 'MetaSession::~MetaSession()' thread 7fd141f63640 time 2023-10-13T00:48:38.378496+0000
> /home/jenkins-build/build/workspace/ceph-api/src/client/MetaSession.h: 66: FAILED ceph_assert(caps.empty())
> ```

I think I missed this. Will check it soon.

**Comment by lxbsz** [comment]
jenkins test api

**Comment by lxbsz** [comment]
jenkins test api

**Comment by lxbsz** [comment]
jenkins test api

**Comment by lxbsz** [comment]
jenkins test api

**Comment by lxbsz** [comment]
jenkins test api

**Comment by lxbsz** [comment]
jenkins test api

**Comment by lxbsz** [comment]
jenkins test make check

**Comment by lxbsz** [comment]
@vshankar This is ready now.

**Review by vshankar — APPROVED** [review]

**Review by kotreshhr — APPROVED** [review]

**Pull request merged**
