### PR TITLE
qa/tests: Various whitelists for smoke suite

### PR DESCRIPTION
**Pull request by vasukulkarni**
For http://tracker.ceph.com/issues/21376

Running tests here: http://pulpito.ceph.com/vasu-2017-09-12_20:51:25-smoke-master-distro-basic-ovh/

Signed-off-by: Vasu Kulkarni <vasu@redhat.com>

### CODE REVIEW

**Comment by tmuthamizhan** [comment]
lgtm

**Comment by vasukulkarni** [comment]
The failures just print out the first WRN or ERR, due to head -n 1 but there are many others that need to be handled, finding them or will try to set the osdscrub flag too, bit confusing how the rados/basic tests dont complain for 'noscrub flag(s) set'

**Comment by vasukulkarni** [comment]
@tmuthamizhan http://pulpito.ceph.com/vasu-2017-09-14_18:00:14-smoke-master-distro-basic-ovh/

**Comment by vasukulkarni** [comment]
there is one other minor issue, that I think we could wait and check before whitelisting for rados_api_test
 cluster [WRN] pool 'test-rados-api-ovh033-10279-4' is full (reached quota's max_bytes: 4K)" in cluster log

**Comment by vasukulkarni** [comment]
All Clean run: http://pulpito.ceph.com/vasu-2017-09-14_20:35:09-smoke-master-distro-basic-ovh/ , the one failed test is due to distro kernel which doesn't support all cluster features.

**Pull request merged**
