### PR TITLE
pybind: Rework rbd/setup.py for PyPI

### PR DESCRIPTION
**Pull request by onyb**
The RBD test could be better, but this is what QEMU uses in its `configure` script.

Signed-off-by: Anirudha Bose <ani07nov@gmail.com>

### CODE REVIEW

**Comment by tchaikov** [comment]
lgtm.

**Comment by dillaman** [comment]
Please verify that the doc builders are still able to run

**Comment by tchaikov** [comment]
@dillaman tracked at http://tracker.ceph.com/issues/16940, will take a look at it.

**Comment by tchaikov** [comment]
@dillaman #10623 addresses the issue.

**Comment by dillaman** [comment]
Does this now require the same ```BUILD_DOC``` environment variable / skip sanity check logic?

**Comment by tchaikov** [comment]
@dillaman yeah, thanks for the reminder!
@onyb could you please add `BUILD_DOC` env var as well? see #10623.

**Comment by onyb** [comment]
@tchaikov Done. Thanks!

**Comment by tchaikov** [comment]
lgtm.

**Comment by dillaman** [comment]
lgtm

**Pull request merged**
