### PR TITLE
Coverity and SCA fixes

### PR DESCRIPTION
**Pull request by tchaikov**

### CODE REVIEW

**Comment by joscollin** [comment]
Jenkins retest this please

**Comment by tchaikov** [comment]
- http://pulpito.ceph.com/kchai-2017-09-04_18:32:24-rados-wip-kefu-testing-2017-09-05-0030-distro-basic-smithi/
- http://pulpito.ceph.com/kchai-2017-09-05_04:17:28-rados-wip-kefu-testing-2017-09-05-0030-distro-basic-smithi/

**Comment by dalgaaf** [comment]
@tchaikov thanks for the work! Totally missed my pull request due to other projects!

**Comment by tchaikov** [comment]
@dalgaaf my pleasure!

**Pull request merged**
