### PR TITLE
mgr/balancer: deepcopy best plan - otherwise we get latest

### PR DESCRIPTION
**Pull request by profihost**
Fixes Tracker:
http://tracker.ceph.com/issues/27000

### CODE REVIEW

**Comment by xiexingguo** [comment]
Can you fix the `Signed-off-by` and the tracker line please? 

https://github.com/ceph/ceph/blob/master/SubmittingPatches.rst#1-sign-your-work

**Comment by profihost** [comment]
fixed - new commit online

**Comment by smithfarm** [comment]
jenkins test docs

**Comment by disaster123** [comment]
Test docs?

**Comment by tchaikov** [comment]
@disaster123 i think what @smithfarm intended is to rerun the "docs: build check" task. the "test docs" is a command recognised by our jenkins.

**Comment by tchaikov** [comment]
retest this please.

**Comment by tchaikov** [comment]
retest this please.

**Comment by tchaikov** [comment]
- http://pulpito.ceph.com/kchai-2018-08-24_03:54:41-rados-wip-kefu2-testing-2018-08-23-2301-distro-basic-smithi/
- http://pulpito.ceph.com/kchai-2018-08-24_11:29:30-rados-wip-kefu2-testing-2018-08-23-2301-distro-basic-mira/
- http://pulpito.ceph.com/kchai-2018-08-24_14:06:56-rados-wip-kefu2-testing-2018-08-24-1611-distro-basic-mira/
- http://pulpito.ceph.com/kchai-2018-08-25_02:09:50-rados-wip-kefu2-testing-2018-08-25-0047-distro-basic-mira/

**Pull request merged**
