### PR TITLE
ceph_argparse: Remove code duplication and generalize ceph_argparse_with* routines 

### PR DESCRIPTION
**Pull request by dmitryya**
Would like propose a small improvements for ceph_argparse:
 - remove code duplication by generalizing ceph_argparse_with{int,float,longlong} routines - make one template function instead of three. 

Also indents fixes for rbd.cc and ceph_argparse.cc files.

### CODE REVIEW

**Comment by tchaikov** [comment]
@dmitryya nice refactory and fix !
- regarding to the indent changes. per https://github.com/ceph/ceph/blob/master/CodingStyle#L75, we do use tab for indent.
- might want put some notes explain why to remove `&err` would be more helpful to reviewers.

**Comment by dmitryya** [comment]
@tchaikov Commits are updated. Regarding indents: my fail, but looks bad with mixing spaces and tabs. Should I remove commits with indent fixes.

**Comment by tchaikov** [comment]
@dmitryya , thanks for updating the commit log =)

> Should I remove commits with indent fixes.

i'd suggest you remove the commits for fixing the indent. i know the coding style is always sort of controversial. but we'd better stick to the one we have at this moment.

**Comment by dmitryya** [comment]
@tchaikov indent fix commits are removed.

**Comment by dmitryya** [comment]
I think this is not linked with my changes:
<pre><code>
make[1]: Entering directory `/home/gitlab_ci_runner/r/tmp/builds/ceph-centos-7'
if test -d "ceph-0.93"; then find "ceph-0.93" -type d ! -perm -200 -exec chmod u+w {} ';' && rm -rf "ceph-0.93" || { sleep 5 && rm -rf "ceph-0.93"; }; else :; fi
test -d "ceph-0.93" || mkdir "ceph-0.93"
(cd src && make top_distdir=../ceph-0.93 distdir=../ceph-0.93/src \
am__remove_distdir=: am__skip_length_check=: am__skip_mode_fix=: distdir)
make[2]: Entering directory `/home/gitlab_ci_runner/r/tmp/builds/ceph-centos-7/src'
./make_version -g ./.git_version
if [ -n "$NO_VERSION" ] ; then \
./make_version -g ./.git_version -c ./ceph_ver.h -n ; \
else \
./make_version -g ./.git_version -c ./ceph_ver.h ; \
fi
make[2]: *** No rule to make target `verify-mds-journal.sh', needed by `distdir'. Stop.
make[2]: Leaving directory `/home/gitlab_ci_runner/r/tmp/builds/ceph-centos-7/src'
make[1]: *** [distdir] Error 1
make[1]: Leaving directory `/home/gitlab_ci_runner/r/tmp/builds/ceph-centos-7'
make: *** [dist] Error 2
</code></pre>
Moreover I do not have such error on my host when use run-make-check.sh

**Pull request merged**
