### PR TITLE
qa: Add S3 subuser tests

### PR DESCRIPTION
**Pull request by clwluvw**
qa tests for S3 support subuser

Signed-off-by: Seena Fallah <seenafallah@gmail.com>

### CODE REVIEW

**Comment by clwluvw** [comment]
Hi @cbodley, Can you please take a look at it?

**Comment by tchaikov** [comment]
jenkins test docs

**Comment by clwluvw** [comment]
ping @cbodley

**Comment by clwluvw** [comment]
unstale please

**Comment by clwluvw** [comment]
unstale please

**Comment by frittentheke** [comment]
unstale please

**Pull request closed without merging**
