### PR TITLE
nautilus: mgr/dashboard: REST API: OpenAPI docs require internet connection

### PR DESCRIPTION
**Pull request by shyukri**
backport tracker: https://tracker.ceph.com/issues/42164

---

backport of https://github.com/ceph/ceph/pull/30477
parent tracker: https://tracker.ceph.com/issues/40027

this backport was staged using ceph-backport.sh version 15.0.0.6950
find the latest version at https://github.com/ceph/ceph/blob/master/src/script/ceph-backport.sh

### CODE REVIEW

**Comment by shyukri** [comment]
jenkins test docs

**Comment by callithea** [comment]
jenkins test make check

**Comment by callithea** [comment]
jenkins test dashboard backend

**Comment by callithea** [comment]
jenkins test dashboard

**Comment by shyukri** [comment]
jenkins test make check

**Comment by shyukri** [comment]
jenkins test dashboard backend

**Comment by smithfarm** [comment]
jenkins test make check

**Comment by smithfarm** [comment]
```
npm ERR! Unexpected end of JSON input

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/jenkins-build/.npm/_logs/2020-02-12T14_04_00_624Z-debug.log
src/pybind/mgr/dashboard/CMakeFiles/mgr-dashboard-frontend-deps.dir/build.make:60: recipe for target '../src/pybind/mgr/dashboard/frontend/node_modules' failed
make[3]: *** [../src/pybind/mgr/dashboard/frontend/node_modules] Error 1
```

**Comment by smithfarm** [comment]
Looks like it does not compile.

**Comment by shyukri** [comment]
jenkins test dashboard

**Comment by shyukri** [comment]
Please note: pushing slightly changed package-lock.json generated locally via
'npm install' in order to fix compile issues.

**Comment by yuriw** [comment]
[wip-yuri7-testing-2020-03-19-1610-nautilus](https://trello.com/c/LrERphRb/847-wip-yuri7-testing-2020-03-19-1610-nautilus)

**Pull request merged**
