### PR TITLE
mgr/cephadm: additional debug logging for autotuner

### PR DESCRIPTION
**Pull request by adk3798**
This came from trying to debug behavior of the autotuner in the upstream mailing list. The test case being added was what that user was seeing. The debug logging being added was useful in getting a full understanding of how the autotuner got the result it did. Therefore, why not add the logging to the actual codebase so we can make use of it to debug autotuner issues in the future

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [x] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [x] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Review by phlogistonjohn — APPROVED** [review]
code looks good. approved.

Non-blocking nitpick: because the code change and the test are independent of each other I would prefer to see this as two commits. One for test improvements and one for logging/code improvements. Just a thought for next time.

**Comment by adk3798** [comment]
jenkins retest this please

**Comment by adk3798** [comment]
https://pulpito.ceph.com/adking-2024-04-30_05:42:49-orch:cephadm-wip-adk-testing-2024-04-29-2009-distro-default-smithi/

Most failures were `in cluster log` failures that are still in the process of being cleaned up.

Besides that, failures were:

- 1 instance of https://tracker.ceph.com/issues/65718 (known issue)
- 4 instances of mds_upgrade_sequence test failing (known issue)
- 1 instance of staggered upgrade with agent failing (known issue)
- some dead jobs, either reimaging issue or getting stuck before the test has actually began (seemingly on nvme-loop task) (known issue)

**Comment by adk3798** [comment]
jenkins test api

**Comment by adk3798** [comment]
https://pulpito.ceph.com/adking-2024-05-09_03:09:40-orch:cephadm-wip-adk-testing-2024-05-08-1927-distro-default-smithi/

failures:
- 21 `in cluster log` type failures that are still being cleaned up, known issue
- 3 mds_upgrade_sequence failures, known issue
- 1 test failed installing `ceph-fuse` ` Status code: 503 for https://mirrors.centos.org/metalink?repo=centos-baseos-9-stream&arch=x86_64&protocol=https,http`, happens on occasion, nothing to block merging over

Overall, nothing unexpected in the run

**Pull request merged**
