### PR TITLE
mgr/progress: estimated remaining time for events

### PR DESCRIPTION
**Pull request by xiexingguo**
Fixes: https://tracker.ceph.com/issues/40419
Signed-off-by: xie xingguo <xie.xingguo@zte.com.cn>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`

</details>

### CODE REVIEW

**Comment by xiexingguo** [comment]
it would make more sense to display the estimated remaining time, e.g.,
```
  progress:
    Rebalancing after osd.2 marked out (time remaining: 00h 03m 06s)
      [==............................]
    Rebalancing after osd.1 marked out (time remaining: 00h 00m 41s)
      [===============...............]
```

**Comment by xiexingguo** [comment]
retest this please

**Comment by liewegas** [comment]
I wonder if we shoudl do both, sort of like media progress bars?
```
  progress:
    Rebalancing after osd.2 marked out
      00h 00m 30s [==............................] 00h  03m 06s
    Rebalancing after osd.1 marked out
      00h 02m 01s [===============...............] 00h 00m 41s
```

**Comment by tchaikov** [comment]
- http://pulpito.ceph.com/kchai-2019-09-28_11:33:27-rados-wip-kefu-testing-2019-09-28-1615-distro-basic-smithi/
- http://pulpito.ceph.com/kchai-2019-09-29_02:16:32-rados-wip-kefu-testing-2019-09-28-1615-distro-basic-mira/

**Comment by tchaikov** [comment]
> I wonder if we shoudl do both, sort of like media progress bars?
> 
> ```
>   progress:
>     Rebalancing after osd.2 marked out
>       00h 00m 30s [==............................] 00h 03m 06s
>     Rebalancing after osd.1 marked out
>       00h 02m 01s [===============...............] 00h 00m 41s
> ```

IMHO, this is not intuitive, a typical media progress bar looks like
```
[==............................] 00:00:30 / 00:03:36
```

where "00:00:30" is the current progress. while "00:03:36" is the total length of the video clip.

by looking at 
```
>       00h 00m 30s [==............................] 00h 03m 06s
```
i can hardly connect "00h 03m 06s" to the remaining time.

**Comment by xiexingguo** [comment]
retest this please

**Comment by xiexingguo** [comment]
jenkins test make check

**Comment by tchaikov** [comment]
@sebastian-philipp i don't think this change is related to dashboard.

**Comment by sebastian-philipp** [comment]
> @sebastian-philipp i don't think this change is related to dashboard.

If `ceph -s` shows the time remaining, the Dashboard should do this too!

**Comment by xiexingguo** [comment]
jenkins test make check

**Comment by xiexingguo** [comment]
new version:

```
  progress:
    Rebalancing after osd.5 marked in (since 00h 01m 16s)
      [====........................] (time remaining: 00h 06m 00s)
    Rebalancing after osd.4 marked in (since 00h 02m 16s)
      [===.........................] (time remaining: 00h 16m 27s)
    Rebalancing after osd.3 marked in (since 00h 03m 03s)
      [===========.................] (time remaining: 00h 04m 15s)
```

**Comment by xiexingguo** [comment]
http://pulpito.ceph.com/xxg-2019-09-30_10:05:01-rados-wip-progress-time-remaining-distro-basic-smithi/

merging. we can continue to improve if there comes up better idea later.

**Pull request merged**
