### PR TITLE
pybind: customize compiler before checking cflags

### PR DESCRIPTION
**Pull request by tchaikov**
otherwise we are always looking at the default compiler on 'unix' --
'cc'. and will fail to filter cflags not supported by clang, if we
are compiling the python bindings using clang.

Signed-off-by: Kefu Chai <kchai@redhat.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by mkogan1** [comment]
Thank you very much,

Testing the commit with clang compilation,
there is a python error:
`TypeError: can only concatenate list (not "itertools.filterfalse") to list `

when building the `cython_rados` unit for example:

```
FAILED: lib/cython_modules/lib.3/rados.cpython-37m-x86_64-linux-gnu.so  
cd /mnt/osd--host/src-git/ceph--master/src/pybind/rados && env CC="/usr/bin/clang -pipe -frecord-gcc-switches -grecord-gcc-switches -fno-omit-frame-pointer -fstack-protector-all --param=ssp-buffer-size=4 -fasynchronous-unwind-tables -fstack-check -ggdb3 -gdwarf-4 -march=native -O0 -finstrument-functions -fcf-protection -Wall -Wtype-limits -Wignored-qualifiers -Winit-self -Wpointer-arith -Werror=format-security -fno-strict-aliasing -fsigned-char -Wno-unknown-pragmas -Wno-unused-function -Wno-unused-local-typedef -Wno-varargs -Wno-gnu-designator -Wno-missing-braces -Wno-parentheses -Wno-deprecated-register -fdiagnostics-color=auto -iquote/mnt/osd--host/src-git/ceph--master/src/include -w -D'void0=dead_function(void)' -D'__Pyx_check_single_interpreter(ARG)=ARG ## 0'" CXX="/usr/bin/clang++" LDSHARED="/usr/bin/clang -shared" OPT="-DNDEBUG -g -fwrapv -O2 -w" LDFLAGS=-L/mnt/osd--host/src-git/ceph--master/build/lib CYTHON_BUILD_DIR=/mnt/osd--host/src-git/ceph--master/build/src/pybind/rados CEPH_LIBDIR=/mnt/osd--host/src-git/ceph--master/build/lib /usr/bin/python3.7 /mnt/osd--host/src-git/ceph--master/src/pybind/rados/setup.py build --verbose --build-base /mnt/osd--host/src-git/ceph--master/build/lib/cython_modules --build-platlib /mnt/osd--host/src-git/ceph--master/build/lib/cython_modules/lib.3 
running build 
running build_ext 
building 'rados' extension 
Traceback (most recent call last): 
  File "/mnt/osd--host/src-git/ceph--master/src/pybind/rados/setup.py", line 206, in <module> 
    cmdclass=cmdclass, 
  File "/usr/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup 
    return distutils.core.setup(**attrs) 
  File "/usr/lib64/python3.7/distutils/core.py", line 148, in setup 
    dist.run_commands() 
  File "/usr/lib64/python3.7/distutils/dist.py", line 966, in run_commands 
    self.run_command(cmd) 
  File "/usr/lib64/python3.7/distutils/dist.py", line 985, in run_command 
    cmd_obj.run() 
  File "/usr/lib64/python3.7/distutils/command/build.py", line 135, in run 
    self.run_command(cmd_name) 
  File "/usr/lib64/python3.7/distutils/cmd.py", line 313, in run_command 
    self.distribution.run_command(command) 
  File "/usr/lib64/python3.7/distutils/dist.py", line 985, in run_command 
    cmd_obj.run() 
  File "/usr/lib64/python3.7/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run 
    _build_ext.build_ext.run(self) 
  File "/usr/lib64/python3.7/distutils/command/build_ext.py", line 340, in run 
    self.build_extensions() 
  File "/usr/lib64/python3.7/site-packages/Cython/Distutils/old_build_ext.py", line 194, in build_extensions 
    self.build_extension(ext) 
  File "/usr/lib64/python3.7/distutils/command/build_ext.py", line 534, in build_extension 
    depends=ext.depends) 
  File "/usr/lib64/python3.7/distutils/ccompiler.py", line 574, in compile 
    self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts) 
  File "/usr/lib64/python3.7/distutils/unixccompiler.py", line 127, in _compile 
    extra_postargs) 
TypeError: can only concatenate list (not "itertools.filterfalse") to list 
```

**Comment by tchaikov** [comment]
@mkogan1 thanks for testing. i fixed it. also i fixed the case of "ccache" + "clang".

**Comment by tchaikov** [comment]
jenkins test make check

**Comment by tchaikov** [comment]
https://shaman.ceph.com/builds/ceph/wip-kefu-testing-2020-02-11-0913/6b5a4d571deec6bcbb6b4050de11cb3ceba6a45a/

**Pull request merged**
