### PR TITLE
common/options: make secure mode non-experimental, and prefer/require it for mons

### PR DESCRIPTION
**Pull request by liewegas**
Let's enable this in master so we get lots of testing.  We can backport the config change to nautilus when we are comfortable.

### CODE REVIEW

**Comment by tchaikov** [comment]
i think http://tracker.ceph.com/issues/38827 is related to this change.

**Comment by liewegas** [comment]
@rzarzynski can you take a look?

**Comment by rzarzynski** [comment]
@liewegas: I'm on it.

**Comment by liewegas** [comment]
still seeing the valgrind problem when i test this.. see /a/sage-2019-03-22_15:25:05-rados-wip-sage-testing-2019-03-22-0509-distro-basic-smithi/3761185/

**Pull request merged**
