### PR TITLE
mgr/zabbix: format ceph.[{#POOL},percent_used as float

### PR DESCRIPTION
**Pull request by tchaikov**
also, multiply it with 100, as we are using 1.0 for 100% here.

Fixes: https://tracker.ceph.com/issues/48825
Signed-off-by: Kefu Chai <kchai@redhat.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by tchaikov** [comment]
jenkins test make check

**Comment by tchaikov** [comment]
```
[ RUN      ] TestLibRBD.TestPendingAio
using new format!
/home/jenkins-build/build/workspace/ceph-pull-requests/src/test/librbd/test_librbd.cc:4685: Failure
Expected equality of these values:
  1
  rbd_aio_is_complete(comps[i])
    Which is: 0
[  FAILED  ] TestLibRBD.TestPendingAio (70 ms)
```

**Comment by tchaikov** [comment]
jenkins test make check

**Review by wido — APPROVED** [review]
LGTM

**Pull request merged**
