### PR TITLE
Fix for operations not idempotent when enabling cache

### PR DESCRIPTION
**Pull request by wonzhq**
Fix for issue 8935.

### CODE REVIEW

**Comment by liewegas** [comment]
This looks mostly correct!  The only other (annoying) change I'd suggest is to change 
"object_max_op_logs" to singular "object_max_op_log".

**Comment by liewegas** [comment]
Except now I realize that this is only solving half of the problem.  The 'delete' op is tricky because we want it to also be idempotent and it erases the object_info_t and all trace of past requests.  I think we can resolve that with a couple additional changes:

1. If we are promoting and get ENOENT, then we should check the pg log for deletion operations on the object and use those to prime the whiteout in the cache tier.  This is a bit tricky because the copyget Objecter operation doesn't decode any result on error.  The OSD can return data along with an error code, though.  We have a couple options... we could make a separate op to gather recent ops that follows the copyget (cleanest, but will duplicate the work if the copyget is successful).  Or, we could hack copyget to include the reqid list in the error result.  Older code completely ignores the payload on error, so we're still compatible.  If we do that, we should make a new struct like object_copy_error_t that wraps anything else we decide to include.  Then finish_promote can use this to populate the op_log for the whiteout.

2) Make sure we check the op_log for dups when we find a whiteout... 

3) If we are flushing a whiteout, we'll have a reqid list, but on the backend all we are doing is a delete, so it won't get recorded in a way that will catch a dup deletion.  Maybe we could use the last (delete) reqid for the flush delete operation?  That's pretty hacky... Hrm.

**Comment by liewegas** [comment]
Or, we could bite the bullet and make delete on a non-existent object return 0.  That might be a bit of pain initially but is a much saner thing to support going forward...

**Comment by wonzhq** [comment]
Updated the existing commits per the comments. Will add the additional changes later.

**Comment by wonzhq** [comment]
> Or, we could bite the bullet and make delete on a non-existent object return 0. That might be a bit of pain initially but is a much saner thing to support going forward...

While the first two items look fine to me, I have a question on the 3rd item. If we make delete on a non-existent object return 0, then the idempotent problem on the delete operation doesn't exist any more, does it?

**Comment by liewegas** [comment]
Yeah.. I will start a thread on the list to discuss this.  Perhaps wait before coding anything else up until we have a complete plan.  Thanks!

**Comment by liewegas** [comment]
+1 from @athanatos  on this.  I will change extra_reqids to a multimap and then test...

**Pull request closed without merging**
