### PR TITLE
jewel: Clients without pool-changing caps shouldn't be allowed to change pool_namespace

### PR DESCRIPTION
**Pull request by dachary**
http://tracker.ceph.com/issues/17956

### CODE REVIEW

**Comment by dachary** [comment]
jenkins test this please (change target branch)

**Comment by dachary** [comment]
jenkins test this please (unittest_throttle in jewel)

**Comment by dachary** [comment]
check this please

**Comment by jcsp** [comment]
Tested here: http://pulpito.ceph.com/jspray-2017-01-24_21:53:01-fs-wip-jcsp-backports-20170124-distro-basic-smithi/

**Pull request merged**
