### PR TITLE
kv/RocksdbStore: remove perfcounter l_rocksdb_txns/l_rocksdb_txns_sync

### PR DESCRIPTION
**Pull request by majianpeng**
Perfcounter l_rocksdb_submit_latency/l_rocksdb_submit_sync_latency
contain l_rocksdb_txns/l_rocksdb_txns_sync.

Signed-off-by: Jianpeng Ma <jianpeng.ma@intel.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by majianpeng** [comment]
retest this please

**Comment by tchaikov** [comment]
- https://pulpito.ceph.com/kchai-2020-08-08_13:50:13-rados-wip-kefu-testing-2020-08-08-1822-distro-basic-smithi/
- https://pulpito.ceph.com/kchai-2020-08-09_03:30:55-rados-wip-kefu-testing-2020-08-08-1822-distro-basic-smithi/

failure in upgrade test also exists in master

- https://pulpito.ceph.com/kchai-2020-08-09_05:31:11-rados-master-distro-basic-smithi/

**Comment by majianpeng** [comment]
@tchaikov ,  you mean is you should fix the bugs and retest this pr?

**Comment by tchaikov** [comment]
@majianpeng no, i meant this change was not related to the failure.

**Pull request merged**
