### PR TITLE
rgw: fix index suggest

### PR DESCRIPTION
**Pull request by tianshan**
1.fix the test failure http://tracker.ceph.com/issues/24640
2.fix the race issue http://tracker.ceph.com/issues/24744
3.add test cases for races issues

### CODE REVIEW

**Comment by tianshan** [comment]
@ivancich please help review

**Comment by ivancich** [comment]
@tianshan Will do. Thank you.

**Comment by tianshan** [comment]
the fix for issue 2, seems miss a situation that delete raced with some other op, but the other op is canceled, so the stale index can never be deleted.
for the countless situation, we have an idea that use the epoch or ver to detect if index is changed after last list, if ver is smaller than cur_disk, just discard the index suggest.  this solution maybe more clear to all situations.

**Comment by ivancich** [comment]
@tianshan Do I understand correctly that you'll be updating this PR with a fix that: a) handles the race condition, and b) is clearer? If that's true, I should wait for the update, right?

**Comment by ivancich** [comment]
I ran the race condition inducing test (https://github.com/ivancich/rgw-race-inducer) for about 20 hours and the race did not take place.

@tianshan I remain unclear as to whether you plan on following up with an update to the pr that addresses the issues you raised above.

**Comment by tianshan** [comment]
@ivancich   the first commit fix the ut issue,  and the second race condition is a new issue when I write some new ut cases, so I propose a fix. But after talk with my colleague, we think the fix maybe  introduced some new issue, and discussed with a new fix idea.
I think we can separate the first commit to a new pr which address the ut failure only, than we can discussed the race condition step by step.

**Comment by tianshan** [comment]
@ivancich  the ut failure fix seperate to #22937,  please help review again, may merge that first

**Comment by ivancich** [comment]
This PR has been replaced by https://github.com/ceph/ceph/pull/22937. Closing.

**Pull request closed without merging**
