### PR TITLE
mon: a few health fixes

### PR DESCRIPTION
**Pull request by xiexingguo**

### CODE REVIEW

**Comment by xiexingguo** [comment]
Append one more patch https://github.com/ceph/ceph/pull/16415/commits/47cc691ae84ffb6ba68db2c8cbc066325a9d8dc8 to fix summary of clock skew warn.

**Comment by xiexingguo** [comment]
retest this please

**Comment by xiexingguo** [comment]
retest this please

**Comment by tchaikov** [comment]
- http://pulpito.ceph.com/kchai-2017-07-21_02:43:22-rados-wip-kefu-testing-distro-basic-smithi/
- http://pulpito.ceph.com/kchai-2017-07-20_03:05:27-rados-wip-kefu-testing-distro-basic-mira/

the failed tests are related to health checking and monitor, and they are addressed by #16477. so i don't think they are relevant.

**Pull request merged**
