### PR TITLE
journal: limit number of appends sent in one librados op 

### PR DESCRIPTION
**Pull request by trociny**
Fixes: http://tracker.ceph.com/issues/23526
Signed-off-by: Mykola Golub <mgolub@suse.com>

### CODE REVIEW

**Comment by trociny** [comment]
@dillaman The first commit fixes "Message too long" problem.

For the second one, I wonder if there were some reasons why we wanted simultaneous in flight appends?  It seems to me it is more optimal if we send the next appends chunk only after the previous is complete, because it allows to aggregate many appends in one chunk. Without this I was observing many small in flight appends. I have not done any serious benchmarking, but `rados bench` on a vstart cluster shows significant improvement. If you think it is right approach the patch can be further cleaned up: it looks like m_append_tid and m_in_flight_tids are not need if it is serialized. Also, we could probably detect overflow on the client side: this would save one additional rados operation (sent and rejected due to overflow). Or this cleanup could be done in another PR, only for master.

**Comment by tchaikov** [comment]
retest this please.

**Comment by tchaikov** [comment]
retest this please.

**Comment by dillaman** [comment]
@trociny ```rados bench``` or ```rbd bench```? I would think small IO throughput and latency would be improved when sending multiple in-flight ops. Internally tracking for possible overflow before sending was the goal of ```m_size```. In the future when multiple images can share the same journal (i.e. consistency groups), a client will still need to handle the overflow error.

**Comment by tchaikov** [comment]
retest this please.

**Comment by trociny** [comment]
@dillaman Sorry, `rbd bench`.

Probably in a real cluster, when network latency is much higher than in vstart cluster, multiple in-flight ops are more useful. It looks like I need to benchmark this in a lab.

Then may be limit the scope of this PR only by the first patch?

**Comment by dillaman** [comment]
@trociny 

> Then may be limit the scope of this PR only by the first patch?

Yeah, that will be better for backporting as well.

**Comment by trociny** [comment]
@dillaman updated

**Pull request merged**
