### PR TITLE
common: add constructor for WorkQueue with time_t

### PR DESCRIPTION
**Pull request by wjwithagen**
Otherwise clang/FreeBSD complains:

In file included from /home/jenkins/workspace/ceph-master-compile/src/os/ObjectStore.h:26:
/home/jenkins/workspace/ceph-master-compile/src/common/WorkQueue.h:150:9: error: no matching constructor for initialization of 'ThreadPool::WorkQueue_'
      : WorkQueue_(std::move(n), ti, sti), pool(p) {
        ^          ~~~~~~~~~~~~~~~~~~~~~
/home/jenkins/workspace/ceph-master-compile/src/common/WorkQueue.h:81:5: note: candidate constructor not viable: no known conversion from 'time_t' (aka 'long') to 'ceph::timespan' (aka 'duration<unsigned long, ratio<1LL, 1000000000LL> >') for 2nd argument
    WorkQueue_(std::string n, ceph::timespan ti, ceph::timespan sti)
    ^
/home/jenkins/workspace/ceph-master-compile/src/common/WorkQueue.h:77:10: note: candidate constructor (the implicit copy constructor) not viable: requires 1 argument, but 3 were provided
  struct WorkQueue_ {
         ^
1 warning and 1 error generated.

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by wjwithagen** [comment]
@tchaikov 

That wasn't the fix.... 
Cleary I changed something else as well, since I did get it to compile..
So please hold of on committing this PR

**Comment by wjwithagen** [comment]
Right, definitely not a fix.
But obviously Clang cannot auto convert `time_t` to `ceph::timespan`.
And given both definitions, I can understand that, unless there is something like `ceph::timespan timespan(time_t t)`??

**Comment by tchaikov** [comment]
i think a better fix is #36481

**Comment by wjwithagen** [comment]
> 
> 
> i think a better fix is #36481

Right, just rip out the offencive code... That'll work too. ;-)

**Pull request closed without merging**
