### PR TITLE
test: Need to escape parens in log-whitelist for grep

### PR DESCRIPTION
**Pull request by dzafman**
Any tests that include these yamls without this change wouldn't detect errors in the logs.

### CODE REVIEW

**Comment by dzafman** [comment]
Testing passed:
http://pulpito.ceph.com/dzafman-2018-05-18_11:36:58-rados-wip-zafman-testing-distro-basic-smithi/

All failures either infrastructure, CACHE_POOL_NO_HIT_SET (test issue), MON_DOWN, test_kvstore_tool.sh, or missing hash_info (tracker 24192).

**Comment by dzafman** [comment]
After testing ran I had to rebase.

**Comment by jdurgin** [comment]
@dzafman should we whitelist MON_DOWN for the multimon/mon_clock* checks?

**Comment by dzafman** [comment]
@jdurgin Not familiar with that test, so I don't know if that is appropriate.

**Comment by jdurgin** [comment]
@dzafman can you file a tracker for the MON_DOWN test then?

**Pull request merged**
