### PR TITLE
build/ops: make "patch" build dependency explicit

### PR DESCRIPTION
**Pull request by smithfarm**
Fixes: http://tracker.ceph.com/issues/40175
Signed-off-by: Nathan Cutler <ncutler@suse.com>

### CODE REVIEW

**Comment by tchaikov** [comment]
@smithfarm thanks for fixing this. but i think we always need `patch` as long as we build boost from source, don't we ? in that case, probably we should move `patch` out of the `with_check` block

**Comment by tchaikov** [comment]
- http://pulpito.ceph.com/kchai-2019-06-06_01:54:32-rados-wip-kefu-testing-2019-06-06-0047-distro-basic-mira/
- http://pulpito.ceph.com/kchai-2019-06-08_09:31:11-rados-wip-kefu-testing-2019-06-06-0047-distro-basic-smithi/#

**Comment by smithfarm** [comment]
@tchaikov Good question. Since the bug was found in a "make check" run, I guess I just assumed it was unique to "make check". To find out the answer, I'm triggering an OBS build of latest upstream master here: https://build.opensuse.org/package/show/filesystems:ceph:octopus:upstream/ceph

**Comment by smithfarm** [comment]
Though the build has not completed, I can already see that `patch` got installed, presumably as an indirect dependency of some other build dependency:

```
[   19s] [70/297] cumulate patch-2.7.6-3.10
```

I will do as @tchaikov suggests and make the dependency explicit.

**Comment by smithfarm** [comment]
https://shaman.ceph.com/builds/ceph/wip-40175/fe632e2d886791e2168ee6200b5bf1bfe8c88d0e/

**Comment by smithfarm** [comment]
@tchaikov I was thinking the Shaman build would be "enough" QA. Did you want to include this in one of your teuthology runs?

**Comment by tchaikov** [comment]
@smithfarm agreed. the needs-qa label is just a misleading tag for reminding me that "merge it as long as it builds!".

**Comment by smithfarm** [comment]
@tchaikov Cool. The build is all green.

**Pull request merged**
