### PR TITLE
luminous: tests: test_rebuild_simple_altpool triggers MDS assertion

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/21484
http://tracker.ceph.com/issues/21490

### CODE REVIEW

**Comment by batrick** [comment]
@smithfarm this is missing the commit for http://tracker.ceph.com/issues/21484

**Comment by yuriw** [comment]
@smithfarm waiting for @batrick changes request and the retest

**Comment by smithfarm** [comment]
@yuriw @batrick Oops! Fixed.

**Comment by yuriw** [comment]
http://pulpito.ceph.com/yuriw-2017-09-21_19:45:30-fs-wip-yuri-testing-2017-09-21-1647-distro-basic-smithi/

http://pulpito.ceph.com/yuriw-2017-09-21_19:47:52-kcephfs-wip-yuri-testing-2017-09-21-1647-testing-basic-smithi/

**Pull request merged**
