### PR TITLE
ceph-volume lvm api refactor/move

### PR DESCRIPTION
**Pull request by alfredodeza**
Now that `ceph-volume disk` is being worked on at the same time that `ceph-volume lvm zap` is, both need to interact with the LVM API that was in place for the `lvm` subcommand.

There is a need for that API to be shared across implementations, so it is better to have it in its own, separate module so that others can consume it.

This is just a refactor and does not introduce new functionality, but needed to avoid conflicts for `lvm zap` and `disk` work

### CODE REVIEW

**Comment by alfredodeza** [comment]
jenkins test ceph-volume tox

**Comment by alfredodeza** [comment]
jenkins test ceph-volume centos7-create

**Comment by alfredodeza** [comment]
jenkins test ceph-volume xenial-create

**Comment by andrewschoen** [comment]
jenkins test ceph-volume centos7-create

**Comment by andrewschoen** [comment]
jenkins test ceph-volume xenial-create

**Pull request merged**
