### PR TITLE
DNM: backport chain_xattr thing for xfs to hammer

### PR DESCRIPTION
**Pull request by liewegas**
http://tracker.ceph.com/issues/11981

We should be sure that this is worth the backport because it is a one-way street: once you stripe xattrs over small values you can't downgrade to a previous hammer point release.

### CODE REVIEW

**Comment by dachary** [comment]
Is there an issue associated with this ?

**Comment by liewegas** [comment]
bug was 11969, backport issue 11981

**Comment by yuyuyu101** [comment]
Hi Sage, do we actually do performance benchmark for this improvement?

**Comment by yuyuyu101** [comment]
I mean is it possible it won't behavior better as we expect ?

**Comment by guangyy** [comment]
Just tried this patch on Giant with radosgw, all xattrs can get inline after applying this patch.

I will try to find an environment to test, and hopefully get some results to share.

**Comment by liewegas** [comment]
It has not been benchmarked.  We have high confidence that XFS will inline 
the smaller attrs in the inode, though, so it is hard to see how it could 
be slower.  How much faster it is depends on how cold the inode cache 
gets, or rather what the inode/xattr cache miss rate is.

**Comment by markhpc** [comment]
I was intending to test this but am bogged down in other things at the moment.  Might not happen until after RHS.

**Comment by dachary** [comment]
@athanatos as soon as you think this is ready for testing, we can add it to the backport integration branch

**Comment by liewegas** [comment]
We're choosing not to backport this to hammer.

**Pull request closed without merging**
