### PR TITLE
os/bluestore: make bluestore_sync_transaction = true can work.

### PR DESCRIPTION
**Pull request by majianpeng**
For sync_transaction, it need do other work in _kv_sync_thread like
fm update.

Signed-off-by: Jianpeng Ma <jianpeng.ma@intel.com>

### CODE REVIEW

**Comment by majianpeng** [comment]
@sage, if bluestore_sync_transaction = true, we can't create cluster w/ bluestore. I'm not sure this path whether correctly. But it can fix the bug. Have you time to review this? Thanks!

**Comment by liewegas** [comment]
This won't quite work. The kv thread does a bunch of work to batch things into the transaction (mainly the allocations/deallocations).  That stuff needs to be moved into helpers so that it can be done in the sync path.

**Comment by majianpeng** [comment]
@sage, i redeep into this and found the root reason is deadlock. I change the commit.
But there is other question: for a  write, it will alloca/release. Is it need update fm w/ this transaction?
For example, sync_transaction, it first sync_transaction expect fm info. Later sync transaction fm info. If after sync_transaction and before sync fm info, the osd crash. After reboot, oid has new extent info.But fm don't record this. Is this right?

**Comment by majianpeng** [comment]
@liewegas . This PR fix 3 bugs
a)bluestore_sync_transaction == true, make deadlock
b)extent alloca/release don't update w/ other metdata cause fsck met error.
b)bluestore_sync_submit_transaction == true; extent alloca/release don't write into kv. This cause  fsck met error.

**Comment by majianpeng** [comment]
@liewegas . Ping!

**Comment by majianpeng** [comment]
@liewegas  Ping!

**Comment by majianpeng** [comment]
@liewegas . Have you time to review this? Thanks!

**Pull request merged**
