### PR TITLE
hammer: configure: Add -D_LARGEFILE64_SOURCE to Linux build.

### PR DESCRIPTION
**Pull request by gaurav36**
Fixes: http://tracker.ceph.com/issues/16612

### CODE REVIEW

**Comment by smithfarm** [comment]
@liewegas This PR is in the latest round of hammer-backports integration tests, which passed a rados run (the only failures are a valgrind false positive that has since been fixed by https://github.com/ceph/teuthology/pull/915 and http://tracker.ceph.com/issues/15139 which is an infrastructure issue with two of the tests) - for details, see: http://tracker.ceph.com/issues/15895#note-18

That said, I don't know if rados test exercises this fix at all?

**Comment by smithfarm** [comment]
@liewegas @athanatos This PR passed a /200 rados run on Ubuntu. None of the failures were reproducible. For details see http://tracker.ceph.com/issues/15895#note-18

Do you think it's OK to merge?

**Comment by athanatos** [comment]
I don't really understand the implications of this.  @gaurav36 Why specifically does this need to be backported to hammer?

**Comment by gaurav36** [comment]
@athanatos  Hammer release is having issue while building because of missing (flag) backport

**Comment by athanatos** [comment]
@gaurav36 Why did it work before?  Is this only very new versions of fedora?

**Comment by gaurav36** [comment]
@athanatos   Its fedora23. Without -D_LARGEFILE64_SOURCE we can't build against libxfs,
because off64_t must be defined. Its a backport patch  http://tracker.ceph.com/issues/16611

**Comment by athanatos** [comment]
@gaurav36 Right, was there something introduced recently that required off64_t, or has this been broken on fedora 23 all along?

**Comment by cbodley** [comment]
@athanatos I think it's been broken all along. I had to work around this issue a couple months ago working on a backport.

**Comment by athanatos** [comment]
@cbodley So it makes sense to backport it?

**Comment by cbodley** [comment]
yes, please

**Comment by athanatos** [comment]
@smithfarm go for it

**Pull request merged**
