### PR TITLE
luminous: mgr: request daemon's metadata when receiving a report message from a…

### PR DESCRIPTION
**Pull request by pdvian**
http://tracker.ceph.com/issues/22197

### CODE REVIEW

**Comment by pdvian** [comment]
@Liuchang0812 @tchaikov @smithfarm

**Comment by pdvian** [comment]
@smithfarm sure. Let me rebase and get this PR corrected.

**Comment by pdvian** [comment]
@smithfarm @jcsp @Liuchang0812 Kindly review latest changes (after rebase to latest luminous)

**Comment by jcsp** [comment]
this commit is also in https://github.com/ceph/ceph/pull/17869/ (sorry, it's confusing...)

**Comment by smithfarm** [comment]
Closing in favor of #17869

**Pull request closed without merging**
