### PR TITLE
osd: probabilistic cache tier promotion throttling

### PR DESCRIPTION
**Pull request by liewegas**

### CODE REVIEW

**Comment by fiskn** [comment]
@liewegas Hi Sage, I've been thinking about this over the last couple of days and I was wondering if we could use this throttle to automatically adjust the recency settings. This would go some way to making the cache tiering easier to setup without knowing the precise nature of the IO profile and would allow it to auto adjust to the correct hotness depending on cache size vs base size.

As the recency settings effectively control at a high level the number of promotions that occur, there could be two variables, a min_recency which we currently have and use it as a starting number. A new cur_min_recency will track the current value. If we start hitting this osd_tier_promote_max limit and the cache is at target_max_bytes, then we bump the cur_min_recency to try and limit the number of promotions by limiting them to even hotter objects.

Some thought properly needs to go into how we then decide when to gradually lower the cur_min_recency (maybe by 1 at every hitset creation???) .

Any thoughts?

**Comment by liewegas** [comment]
I really like the idea of autotuning like that. I think it'll be tricky, 
though...

1) We would need to count the promotions we would have considered with 
different recency settings on each maybe_promote call so that we can tell 
if the next higher recency value would keep us at or above our desired 
promotion rate.  Otherwise, we'd end up oscillating between something like 
recency 1 and 2 (or similar).  Anyway, this means we will do more hitset 
queries.  But we could make it only query the next hitset up (so that the 
cost is incremental)...

2) We would need to make adjustments slowly.  Stepping up or down by no 
more than one probably makes sense.  We can adjust prob at the same time.

**Comment by fiskn** [comment]
When I did the varying recency tests (attached), after about a min_recency of 3 there was a very gradual change to the amount of promotions that occurred. I would have to graph it to be sure, but I would guess it would almost be a logarithmic response. I think as long as the auto tuning didn't go below 3 (or a set level) having it oscillate wouldn't cause too many problems. Maybe some sort of damping could be applied if necessary.

If you were tracking number of promotions at recency of N and N+1..etc, I'm not sure if this would help outside of benchmarks. In real workloads you might have many lulls and peaks of activity, which would invalidate any predictions. Promotion rate will change based on total IO load and also on cache Hit/Miss ratio.

Although crude, a closed loop which allows it to climb rapidly and trickle down slower, would hopefully do enough to roughly track changing IO profiles. I guess attack and decay is what I'm imagining. The important thing is that we don't swamp the cluster with promotions, which is handled by this PR. The only risk I see is that following a quiet period, you may end up promoting objects that are not truly the hottest before the recency gets quickly ramped up, how much of an issue this would be, I'm not sure.

Let me know if I have missed the point, It happens often :-)
varying_recency

**Comment by fiskn** [comment]
An interesting question came up on the perf meeting about whether large number of hitsets would cause excess processing time in the fast path, if a large number of sets had to be scanned through. Nobody really knew the answer, but I was wondering if moving the promote_throttle() call to before the hitset checking would be a good optimisation? As then you wouldn't be wasting time checking hitsets if you wouldn't be able to promote anyway.

I believe the promote_counter.attempt() would need to be removed and called separately, if we do actually try and promote though.

**Comment by liewegas** [comment]
passed rados suite

**Comment by athanatos** [comment]
Better to use an atomic for the promotion probability.  lgtm otherwise.

**Pull request merged**
