### PR TITLE
mailmap: sort alphabetically & add Pere and Waad

### PR DESCRIPTION
**Pull request by epuertat**
* Add Waad and Pere
* Regular clean-up (case-insensitive alphabetical sorting, Vim's `sort i`)

Signed-off-by: Ernesto Puerta <epuertat@redhat.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by epuertat** [comment]
@Waadkh7 @pereman2 please check that I haven't messed up [with your names/emails](https://github.com/ceph/ceph/pull/40806/commits/73b83738994b637d969a082c7db88aa69c831bf3) ;-)

**Review by pereman2 — APPROVED** [review]
I've been using my github email for the past PRs but from now on I'll use the redhat one. Anyways, looks good.

**Review by tchaikov — APPROVED** [review]

**Comment by epuertat** [comment]
> I've been using my github email for the past PRs but from now on I'll use the redhat one. Anyways, looks good.

There's no problem with that. I think we can map multiple accounts to the same user.

**Comment by Waadkh7** [comment]
@epuertat looks good to me

**Review by Waadkh7 — APPROVED** [review]

**Pull request merged**
