### PR TITLE
init-ceph.in: reorder mon and others when start/stop daemons

### PR DESCRIPTION
**Pull request by runsisi**
Fixes: #12891

http://tracker.ceph.com/issues/12891

Signed-off-by: runsisi <runsisi@hust.edu.cn>

### CODE REVIEW

**Comment by runsisi** [comment]
@tchaikov you mean `/etc/init.d/ceph start mon`? i think `get_name_list()` will filter out those we want, then in main script, i.e. /etc/init.d/ceph, all we need to do is adjusting the order.

**Comment by tchaikov** [comment]
@runsisi no, i was talking about `/etc/init.d/ceph start`. the `what` variable is assigned in `get_name_list()` , where we collect the daemon names from `/var/lib/ceph/` and then `/etc/ceph/ceph.conf`. but in your case
> mon_data is set to a different location rather than /var/lib/ceph/mon/$cluster-$id
so there are chances that the detected monitor is put **behind** osd. 

1. i am not sure if ceph.init is designed to handle user-modified data paths. as we have quite a few assumptions out there if you look at `init-ceph.in` closer.
1. imho, it is designed to help the init systems to do the right thing, but is not intended to be very flexible.

so, even this change would help in your case, it is not address all the problems if the user tries to customize the data/admin socket path(s). and it is beyond the scope of problem we want to solve.

**Comment by runsisi** [comment]
@tchaikov thank you every much:)
i changed `get_name_list()` as your suggested, now mon(s) will always be put before osd(s)/mds(s), and init-ceph.in is left unchanged.

**Comment by tchaikov** [comment]
@runsisi actually, i don't think your change worth it. as it is fixing a use case we don't expect ceph.init to tackle.

**Comment by runsisi** [comment]
@tchaikov yeah, you are right, this modification only fits my own case:)
actually, i first came across this problem when i deployed a little cluster manually without creating a `sysvinit` file under /var/lib/ceph/mon/ceph-$id, and setting `mon_data` to a different location has the same effect, so i fired a bug~
thank you for your kindness:)

**Pull request closed without merging**
