### PR TITLE
[DNM] qa: increase ffsb test timeout to 5h

### PR DESCRIPTION
**Pull request by lxbsz**
For some test cases it may take more than 3 hours to finish.

Fixes: https://tracker.ceph.com/issues/52438
Signed-off-by: Xiubo Li <xiubli@redhat.com>

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by vshankar** [comment]
This (longer run times) has started showing up frequently now. Do we know why?

**Comment by lxbsz** [comment]
> This (longer run times) has started showing up frequently now. Do we know why?

There has no kclient related logs, and I have checked the huge mds log files, everything seems working well. Locally I haven't reproduce it yet.

**Review by vshankar — APPROVED** [review]

**Comment by vshankar** [comment]
@lxbsz We still have ffsb failures

- https://pulpito.ceph.com/vshankar-2022-02-28_04:32:15-fs-wip-vshankar-testing-20220226-211550-testing-default-smithi/6710269
- https://pulpito.ceph.com/vshankar-2022-02-28_04:32:15-fs-wip-vshankar-testing-20220226-211550-testing-default-smithi/6710280

The increased timeout should have kind of fixed it unless there is something else that's going on (bug?).

**Comment by lxbsz** [comment]
> @lxbsz We still have ffsb failures
> 
> * https://pulpito.ceph.com/vshankar-2022-02-28_04:32:15-fs-wip-vshankar-testing-20220226-211550-testing-default-smithi/6710269
> * https://pulpito.ceph.com/vshankar-2022-02-28_04:32:15-fs-wip-vshankar-testing-20220226-211550-testing-default-smithi/6710280
> 
> The increased timeout should have kind of fixed it unless there is something else that's going on (bug?).

I will check it.

**Comment by lxbsz** [comment]
Actually the `ffsb` test is finished very fast and took 346.70 seconds:

```
2022-02-28T08:29:36.007 INFO:tasks.workunit.client.0.smithi065.stdout:make[1]: Leaving directory '/home/ubuntu/cephtest/mnt.0/client.0/tmp/ffsb'
2022-02-28T08:29:36.014 INFO:tasks.workunit.client.0.smithi065.stdout:FFSB version 6.0-RC2 started
2022-02-28T08:29:36.015 INFO:tasks.workunit.client.0.smithi065.stdout:
2022-02-28T08:29:36.024 INFO:tasks.workunit.client.0.smithi065.stdout:benchmark time = 300
2022-02-28T08:29:36.024 INFO:tasks.workunit.client.0.smithi065.stdout:ThreadGroup 0
2022-02-28T08:29:36.025 INFO:tasks.workunit.client.0.smithi065.stdout:================
...
2022-02-28T08:29:36.037 INFO:tasks.workunit.client.0.smithi065.stdout:checking existing fs: .
2022-02-28T08:29:36.038 INFO:tasks.workunit.client.0.smithi065.stdout:recreating new fileset
...
2022-02-28T08:36:22.993 INFO:tasks.workunit.client.0.smithi065.stdout:Syncing()...43 sec
2022-02-28T08:36:22.993 INFO:tasks.workunit.client.0.smithi065.stdout:FFSB benchmark finished   at: Mon Feb 28 08:36:23 2022
2022-02-28T08:36:22.994 INFO:tasks.workunit.client.0.smithi065.stdout:
2022-02-28T08:36:22.994 INFO:tasks.workunit.client.0.smithi065.stdout:Results:
2022-02-28T08:36:22.994 INFO:tasks.workunit.client.0.smithi065.stdout:Benchmark took 346.70 sec
2022-02-28T08:36:22.995 INFO:tasks.workunit.client.0.smithi065.stdout:
```

But it just timedout when printing the `lseek` individual response times, which as  52705280 items:

```
2022-02-28T08:36:25.706 INFO:tasks.workunit.client.0.smithi065.stdout:
2022-02-28T08:36:25.706 INFO:tasks.workunit.client.0.smithi065.stdout:[  lseek] 0.001000        0.062884        5543.568848         52705280
2022-02-28T08:36:25.706 INFO:tasks.workunit.client.0.smithi065.stdout:           msec_range[0]  5000.000000 - 10000.000000 :        5
2022-02-28T08:36:25.707 INFO:tasks.workunit.client.0.smithi065.stdout:           msec_range[1]  2000.000000 - 5000.000000 :      390
2022-02-28T08:36:25.707 INFO:tasks.workunit.client.0.smithi065.stdout:           msec_range[2]  1000.000000 - 2000.000000 :      444
2022-02-28T08:36:25.707 INFO:tasks.workunit.client.0.smithi065.stdout:           msec_range[3]  500.000000 - 1000.000000 :      395
2022-02-28T08:36:25.707 INFO:tasks.workunit.client.0.smithi065.stdout:           msec_range[4]  200.000000 - 500.000000 :      463
2022-02-28T08:36:25.707 INFO:tasks.workunit.client.0.smithi065.stdout:           msec_range[5]  100.000000 - 200.000000 :     1324
2022-02-28T08:36:25.708 INFO:tasks.workunit.client.0.smithi065.stdout:           msec_range[6]  50.000000 - 100.000000 :     5982
2022-02-28T08:36:25.708 INFO:tasks.workunit.client.0.smithi065.stdout:           msec_range[7]  20.000000 - 50.000000 :     7754
2022-02-28T08:36:25.708 INFO:tasks.workunit.client.0.smithi065.stdout:           msec_range[8]  10.000000 - 20.000000 :     4975
2022-02-28T08:36:25.708 INFO:tasks.workunit.client.0.smithi065.stdout:           msec_range[9]  5.000000 - 10.000000 :     4498
2022-02-28T08:36:25.709 INFO:tasks.workunit.client.0.smithi065.stdout:           msec_range[10] 2.000000 - 5.000000 :     4991
2022-02-28T08:36:25.709 INFO:tasks.workunit.client.0.smithi065.stdout:           msec_range[11] 1.000000 - 2.000000 :     2666
2022-02-28T08:36:25.709 INFO:tasks.workunit.client.0.smithi065.stdout:           msec_range[12] 0.500000 - 1.000000 :     2529
2022-02-28T08:36:25.709 INFO:tasks.workunit.client.0.smithi065.stdout:           msec_range[13] 0.200000 - 0.500000 :     4366
2022-02-28T08:36:25.709 INFO:tasks.workunit.client.0.smithi065.stdout:           msec_range[14] 0.100000 - 0.200000 :     9061
2022-02-28T08:36:25.710 INFO:tasks.workunit.client.0.smithi065.stdout:           msec_range[15] 0.050000 - 0.100000 :    36950
2022-02-28T08:36:25.710 INFO:tasks.workunit.client.0.smithi065.stdout:           msec_range[16] 0.020000 - 0.050000 :   323262
2022-02-28T08:36:25.710 INFO:tasks.workunit.client.0.smithi065.stdout:           msec_range[17] 0.010000 - 0.020000 :  1490253
2022-02-28T08:36:25.710 INFO:tasks.workunit.client.0.smithi065.stdout:           msec_range[18] 0.000000 - 0.010000 : 50804972
...
```

This is not cephfs's bug, let's fix it in `ffsb` instead to disable print this ?

@vshankar @jtlayton Any idea ?

**Comment by lxbsz** [comment]
Created one pr in ffsb https://github.com/ceph/ffsb/pull/3 to fix it.

**Comment by vshankar** [comment]
> Created one pr in ffsb [ceph/ffsb#3](https://github.com/ceph/ffsb/pull/3) to fix it.

I'll pick ffsb changes and not this one (3h should be plenty).

**Comment by lxbsz** [comment]
> > Created one pr in ffsb [ceph/ffsb#3](https://github.com/ceph/ffsb/pull/3) to fix it.
> 
> I'll pick ffsb changes and not this one (3h should be plenty).

Yeah, sure.

**Pull request closed without merging**
