### PR TITLE
qa/tasks: few fixes to get ceph-deploy 1node to working state

### PR DESCRIPTION
**Pull request by vasukulkarni**
Few fixes to get it to green state

1) use admin command to push keys to the node, required due to monitor changes
2) install mgr as well
3) dont test on trusty but use xenial

Signed-off-by: Vasu Kulkarni <vasu@redhat.com>

### CODE REVIEW

**Comment by vasukulkarni** [comment]
@yuriw this tests been failing for some time which was due to create-keys change

Run: (its still failing but for other issue not related to script)
http://pulpito.ceph.com/vasu-2017-04-07_19:22:34-smoke-master---basic-vps/997308/

**Comment by vasukulkarni** [comment]
the single-node test was left behind for sometime, worth fixing and testing the admin cli.

**Comment by vasukulkarni** [comment]
current state is HEALTH_WARN, which i believe is issue with master since the ceph.conf config is set for 1 node.

```
2017-05-04T01:01:38.478 INFO:teuthology.orchestra.run.vpm003:Running: 'sudo ceph -s'
2017-05-04T01:01:38.948 INFO:teuthology.orchestra.run.vpm003.stdout:    cluster 8ebbe91c-6838-42e8-b507-af7cf8e5d60b
2017-05-04T01:01:38.949 INFO:teuthology.orchestra.run.vpm003.stdout:     health HEALTH_WARN
2017-05-04T01:01:38.949 INFO:teuthology.orchestra.run.vpm003.stdout:            15 pgs peering
2017-05-04T01:01:38.949 INFO:teuthology.orchestra.run.vpm003.stdout:     monmap e2: 1 mons at {vpm003=172.21.2.3:6789/0}
2017-05-04T01:01:38.949 INFO:teuthology.orchestra.run.vpm003.stdout:            election epoch 4, quorum 0 vpm003
2017-05-04T01:01:38.949 INFO:teuthology.orchestra.run.vpm003.stdout:        mgr active: vpm003
2017-05-04T01:01:38.949 INFO:teuthology.orchestra.run.vpm003.stdout:     osdmap e17: 3 osds: 3 up, 3 in
2017-05-04T01:01:38.949 INFO:teuthology.orchestra.run.vpm003.stdout:      pgmap v27: 64 pgs, 1 pools, 0 bytes data, 0 objects
2017-05-04T01:01:38.949 INFO:teuthology.orchestra.run.vpm003.stdout:            215 MB used, 389 GB / 389 GB avail
2017-05-04T01:01:38.949 INFO:teuthology.orchestra.run.vpm003.stdout:            23.438% pgs inactive
2017-05-04T01:01:38.949 INFO:teuthology.orchestra.run.vpm003.stdout:                  49 active+clean
2017-05-04T01:01:38.950 INFO:teuthology.orchestra.run.vpm003.stdout:                  15 remapped+peering
```

http://qa-proxy.ceph.com/teuthology/vasu-2017-05-04_00:50:35-smoke-master---basic-vps/1098445/teuthology.log

**Comment by tmuthamizhan** [comment]
changes looks good!

**Pull request merged**
