### PR TITLE
mimic: test gets ENOSPC from bluestore block device

### PR DESCRIPTION
**Pull request by batrick**
http://tracker.ceph.com/issues/24758
http://tracker.ceph.com/issues/24913

### CODE REVIEW

**Comment by smithfarm** [comment]
@batrick The master PR has an additional commit aa3dcb2b2600a979efa7997a07297b098ca03a98 that is omitted here?

**Comment by batrick** [comment]
@smithfarm thanks for pointing that out. It got dropped accidentally. That explains the number of cherry-pick conflicts I had.

**Comment by smithfarm** [comment]
make check failed due to a transient failure in `test_objectstore_memstore.sh` that I've seen in other PRs as well

jenkins re-test this please

**Comment by batrick** [comment]
@smithfarm fixed

**Comment by yuriw** [comment]
[wip-yuri3-testing-2018-07-13-1521-mimic](https://trello.com/c/OL7VSI70/347-wip-yuri3-testing-2018-07-13-1521-mimic)

**Comment by batrick** [comment]
> @batrick Would it make sense to backport https://tracker.ceph.com/issues/24839 as part of this PR, too?

that one should be backported separately

**Comment by batrick** [comment]
`Reviewed-by: Patrick Donnelly <pdonnell@redhat.com>`

**Pull request merged**
