### PR TITLE
qa/rados/dashbord use "random" objectore

### PR DESCRIPTION
**Pull request by sebastian-philipp**
Looking at https://pulpito.ceph.com/kchai-2021-02-24_02:29:54-rados-wip-kefu-testing-2021-02-23-2359-distro-basic-smithi/
is saw a lot (18 jobs times 1:30 hours = 27 job hours) of long running dashboard tests that mainly differ in the objectstore component. 

One super low hanging fruit to reduce the number of long running jobs would be to use a random objctstore. 

@neha-ojha @jdurgin @epuertat what do you think?

1. removed symlink to `.qa/objectstore`
2. added `random-objectstore&` to `.qa/objectstore`

Signed-off-by: Sebastian Wagner <sebastian.wagner@suse.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Review by tchaikov — APPROVED** [review]

**Review by jdurgin — APPROVED** [review]
good idea!

**Review by neha-ojha — APPROVED** [review]
down to 2!

**Review by epuertat — APPROVED** [review]
Good idea! We don't need this level of coverage at dashboard. I'm just wondering if we were testing something specific to the bluestore backend (compression?).

**Review by callithea — APPROVED** [review]
Lgtm! (Just a side note: "objectore" typo in the PR title and commit message)

**Pull request merged**
