### PR TITLE
reef: mgr/snap_schedule: exceptions management and subvol support

### PR DESCRIPTION
**Pull request by mchangir**
backport tracker: https://tracker.ceph.com/issues/61794

---

backport of https://github.com/ceph/ceph/pull/49295
parent tracker: https://tracker.ceph.com/issues/58195

===

backport tracker: https://tracker.ceph.com/issues/64034

---

backport of https://github.com/ceph/ceph/pull/53999
parent tracker: https://tracker.ceph.com/issues/62892

this backport was staged using ceph-backport.sh version 16.0.0.6848
find the latest version at https://github.com/ceph/ceph/blob/main/src/script/ceph-backport.sh

### CODE REVIEW

**Comment by mchangir** [comment]
jenkins test make check

**Comment by mchangir** [comment]
jenkins test windows

**Comment by mchangir** [comment]
jenkins test windows

**Comment by mchangir** [comment]
rebased and resolved conflicts

**Comment by mchangir** [comment]
clubbed 2 PRs
please read the PR description

**Comment by mchangir** [comment]
@vshankar [11 of 12 snap-schedule jobs passed](https://pulpito.ceph.com/mchangir-2024-02-16_11:55:48-fs-wip-mchangir-testing-snap_schedule-reef-distro-default-smithi/)

**Comment by mchangir** [comment]
jenkins test api

**Comment by vshankar** [comment]
jenkins test windows

**Review by vshankar — APPROVED** [review]

**Comment by vshankar** [comment]
@mchangir Please merge this change.

**Pull request merged**
