### PR TITLE
kraken: mds: unresponsive when truncating a very large file

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/20026

### CODE REVIEW

**Comment by smithfarm** [comment]
@ukernel @batrick This PR passed an fs suite at http://tracker.ceph.com/issues/19009#note-67

Please review.

**Comment by smithfarm** [comment]
@batrick Yeah, only two commits from #12607 were needed to make the cherry-pick possible, but I don't know if backporting just those two commits (out of eight total) is sane?

**Comment by smithfarm** [comment]
(But you say it looks okay, so I'm assuming it *is* sane.)

**Comment by batrick** [comment]
Maybe get @ukernel's opinion on whether those commits are okay.

**Comment by smithfarm** [comment]
@ukernel This PR contains a partial backport of #12607 - is that OK, or would we need to cherry-pick the remaining commits as well?

**Comment by ukernel** [comment]
I think it's better not to include extra commits. how about
https://github.com/ukernel/ceph/tree/wip-20026-jewel
https://github.com/ukernel/ceph/tree/wip-20026-kraken

**Comment by smithfarm** [comment]
@ukernel Thanks. I migrated this PR over to your version.

**Comment by smithfarm** [comment]
This passed an fs suite at http://tracker.ceph.com/issues/19009#note-81

Jenkins, re-test this please

**Pull request merged**
