### PR TITLE
 crimson/osd: make osd_op_params::at_version coherent with last log entry 

### PR DESCRIPTION
**Pull request by rzarzynski**
## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Comment by rzarzynski** [comment]
jenkins retest this please

**Review by Matan-B — APPROVED** [review]

**Comment by Matan-B** [comment]
This might explain versioning issues seen in replicated recovery as well
CC: @xxhdx1985126

**Comment by Matan-B** [comment]
https://shaman.ceph.com/builds/ceph/wip-matanb-crimson-testing-at_version/

**Review by Matan-B — CHANGES_REQUESTED** [review]
https://pulpito.ceph.com/matan-2024-04-28_06:58:35-crimson-rados-wip-matanb-crimson-testing-at_version-distro-crimson-smithi/

`[  FAILED  ] LibRadosCWriteOps.WriteOpAssertVersion`

**Comment by Matan-B** [comment]
@rzarzynski, I have adjusted (in the last commit) the test failed to support Crimson's versioning as well. What do you think?

**Comment by Matan-B** [comment]
https://pulpito.ceph.com/matan-2024-04-28_06:58:35-crimson-rados-wip-crimson-coherent-log-and-at_version-distro-crimson-smithi/

**Review by athanatos — APPROVED** [review]

**Comment by Matan-B** [comment]
changeset:
- adjusted another similar test
- rebased on top of #57102 (avoid future conflict)

Blocked-by: #57102

**Comment by Matan-B** [comment]
https://pulpito.ceph.com/matan-2024-05-02_11:41:00-crimson-rados-wip-crimson-only-coherent-log-and-at_version-distro-crimson-smithi/

7685283, 7685284 - https://tracker.ceph.com/issues/62162

**Review by Matan-B — APPROVED** [review]
@rzarzynski, I'll merge after make check passes

**Pull request merged**
