### PR TITLE
use get_linux_version() instead ad-hoc uname().release parsing

### PR DESCRIPTION
**Pull request by idryomov**
Tested by booting various kernels.

### CODE REVIEW

**Comment by idryomov** [comment]
@gregsfortytwo Happy to rebase if system-retcode patch is merged first.

**Comment by liewegas** [comment]
lgtm

**Comment by gregsfortytwo** [comment]
:+1: Did you run any tests on this? It all looks good but we only use it in one place right now so we wouldn't notice if there were any bugs.

**Comment by idryomov** [comment]
On Thu, Apr 30, 2015 at 1:35 AM, Gregory Farnum
<notifications@github.com> wrote:
>
> Did you run any tests on this? It all looks good but we only use it in one place right now so we wouldn't notice if there were any bugs.

Yes I did, as noted above - wouln't want to open us up to an extsize
corruption with such a simple patch.  Booted 4.1, 3.5 and 3.4 for
extsize and 3.18 and 3.17 for ceph-fuse.  I din't try 2.6.39 and less
because systemd happens to require 3.0 but I tested get_linux_version()
with 2.6.* kernels back in the day and it worked.

**Pull request merged**
