### PR TITLE
test/crimson/seastar_runner: set begin_signaled before eventfd_write

### PR DESCRIPTION
**Pull request by cyx1231st**
Signed-off-by: Yingxin Cheng <yingxin.cheng@intel.com>

Fix the observed test failure from https://github.com/ceph/ceph/pull/44478#issuecomment-1009527392 and https://github.com/ceph/ceph/pull/44490#issuecomment-1007185559

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by cyx1231st** [comment]
jenkins test make check

**Review by athanatos — APPROVED** [review]

**Review by liu-chunmei — APPROVED** [review]

**Comment by cyx1231st** [comment]
jenkins test make check

**Comment by cyx1231st** [comment]
jenkins test api

**Comment by cyx1231st** [comment]
jenkins test docs

**Comment by athanatos** [comment]
@cyx1231st rebasing would probably fix the doc issue

**Comment by athanatos** [comment]
or we can just merge @rzarzynski's version https://github.com/ceph/ceph/pull/44532

**Comment by cyx1231st** [comment]
Merged #44532

**Pull request closed without merging**
