### PR TITLE
mgr/dashboard:  Add jenkinsMode and testsuitesTitle to cypress.json 

### PR DESCRIPTION
**Pull request by aaSharma14**
Add jenkinsMode and testsuitesTitle to cypress.json

Signed-off-by: Aashish Sharma <aasharma@redhat.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by aaSharma14** [comment]
jenkins test dashboard

**Comment by nizamial09** [comment]
jenkins test dashboard

**Comment by aaSharma14** [comment]
jenkins test dashboard cephadm

**Review by epuertat — CHANGES_REQUESTED** [review]
By looking at the failing e2e tests in this PR, it looks like this is duplicating the errors (28):
> [Test Result](https://jenkins.ceph.com/job/ceph-dashboard-pull-requests/11080/testReport/) (28 failures / +25)

But then, in the Console Logs (14):

>    ✖  14 of 25 failed (56%)                    43:25      101       52       14        -       35 

Just picking the 2 first ones I see:
> ["before each" hook for "should check default language".Shared pages "before each" hook for "should check default language"](https://jenkins.ceph.com/job/ceph-dashboard-pull-requests/11080/testReport/junit/(root)/%22before%20each%22%20hook%20for%20%22should%20check%20default%20language%22/Shared_pages__before_each__hook_for__should_check_default_language_/)
> ["after each" hook for "should check default language".Shared pages "after each" hook for "should check default language"](https://jenkins.ceph.com/job/ceph-dashboard-pull-requests/11080/testReport/junit/(root)/%22after%20each%22%20hook%20for%20%22should%20check%20default%20language%22/Shared_pages__after_each__hook_for__should_check_default_language_/)

So it looks that it's duplicating tests for the 'before each' and 'after each' hooks.

And also the test titles didn't improve, did they?

I see that the failure I mentioned before matches this console output:

```
────────────────────────────────────────────────────────────────────────────────────────────────────
                                                                                                    
  Running:  ui/language.e2e-spec.ts                                                       (18 of 25)
  Estimated: 32 seconds

  Shared pages
    1) "before each" hook for "should check default language"
    2) "after each" hook for "should check default language"

  0 passing (3m)
  2 failing

  1) Shared pages
       "before each" hook for "should check default language":
     CypressError: `cy.request()` timed out waiting `45000ms` for a response from your server.
```

Ideally we should see something like `Shared pages should check default language` instead.

BTW, I see that Jenkins has a [JUnit Attachment plugin](https://plugins.jenkins.io/junit-attachments/) that allows to attach files (what about cypress screenshots) to JUnit, and [Mocha exporter supports that](https://www.npmjs.com/package/mocha-junit-reporter).

**Comment by aaSharma14** [comment]
jenkins test api

**Pull request closed without merging**
