### PR TITLE
mds/SessionMap.cc:put classes in unnamed namespace

### PR DESCRIPTION
**Pull request by stiopaa1**
So they have internal linkage.

Signed-off-by: Michal Jarzabek <stiopa@gmail.com>

### CODE REVIEW

**Comment by gregsfortytwo** [comment]
What's the advantage here? Does it reduce the size of binaries, or speed up build times, or something?

**Comment by stiopaa1** [comment]
@gregsfortytwo 
https://gcc.gnu.org/wiki/Visibility

**Comment by jcsp** [comment]
@stiopaa1 that link doesn't mention anything about namespace blocks...?

**Comment by gregsfortytwo** [comment]
http://en.cppreference.com/w/cpp/language/namespace#Unnamed_namespaces points out that they do have internal linkage. External linkage basically implies visibility as I read through that and http://en.cppreference.com/w/cpp/language/storage_duration and this does make some sense.

But I'm not sure how big a deal it actually is, and if we *do* care about leaking symbols (which we might! our builds take *forever*) we probably want to start doing this everywhere.

**Comment by gregsfortytwo** [comment]
http://pulpito.ceph.com/gregf-2016-10-06_18:07:58-fs-greg-fs-testing-105---basic-mira/ looks pretty good; OSD failure (http://tracker.ceph.com/issues/17553), pjd failure due to missing qa-suite wip-getuid merge, 2xlibcephfs-java failures (http://tracker.ceph.com/issues/17548), 1 dead job.

Still have to work out level of care.

**Comment by jcsp** [comment]
OK, so this isn't unreasonable, but I'm not sure I want to handle a separate PR for every file you bump into this.  If this is really helping and making an difference, please do a PR that does this across all the MDS .cc files

**Pull request merged**
