### PR TITLE
qa: use centos 8.stream for fs:upgrade tests

### PR DESCRIPTION
**Pull request by vshankar**
https://tracker.ceph.com/issues/62146

fs:upgrade tests use n/o/p release packages which aren't available for centos 9.stream - switch using 8.stream instead.

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Review by cbodley — APPROVED** [review]

**Comment by dparmar18** [comment]
`qa/suites/fs/upgrade/mds_upgrade_sequence` uses `centos_8.stream_container_tools.yaml`, i hope not including those tools is fine?

**Comment by vshankar** [comment]
http://pulpito.ceph.com/vshankar-2023-07-24_13:06:27-fs:upgrade-wip-vshankar-testing-20230720.042515-testing-default-smithi/

**Comment by vshankar** [comment]
> `qa/suites/fs/upgrade/mds_upgrade_sequence` uses `centos_8.stream_container_tools.yaml`, i hope not including those tools is fine?

Test run went fine with the centos_8 yaml. The yaml you mention was introduced in commit

```
commit eb43f2be9c326a522946bb9ebafc9a016828a41b
Author: Sage Weil <sweil@redhat.com>
Date:   Mon Nov 8 11:01:45 2021 -0600

    qa/suites/orch/cephadm: add 8.stream + container_tools
    
    Signed-off-by: Sage Weil <sage@newdream.net>
```

Maybe that would work too and we can look at it. For now, I'm inclined in merging this with centos_8 yaml esp. since fs:upgrade runs fine.

**Comment by vshankar** [comment]
Commit message update with tracker link.

**Comment by vshankar** [comment]
jenkins test make check

**Comment by dparmar18** [comment]
> > `qa/suites/fs/upgrade/mds_upgrade_sequence` uses `centos_8.stream_container_tools.yaml`, i hope not including those tools is fine?
> 
> Test run went fine with the centos_8 yaml. The yaml you mention was introduced in commit
> 
> ```
> commit eb43f2be9c326a522946bb9ebafc9a016828a41b
> Author: Sage Weil <sweil@redhat.com>
> Date:   Mon Nov 8 11:01:45 2021 -0600
> 
>     qa/suites/orch/cephadm: add 8.stream + container_tools
>     
>     Signed-off-by: Sage Weil <sage@newdream.net>
> ```
> 
> Maybe that would work too and we can look at it. For now, I'm inclined in merging this with centos_8 yaml esp. since fs:upgrade runs fine.

I'm curious why `centos_8.stream_container_tools.yaml` was in `mds_upgrade_sequence`, prior to commit you mentioned it was this commit https://github.com/ceph/ceph/commit/b1420e5771927f5c659e0e5edbc5714035f3df09 that added centos 8.3 with container tools, so the container tools have always existed in this suite and somewhere it might be needed, just to be safe I feel we should add container tools too. It also would make it uniform across the suite

**Comment by vshankar** [comment]
> I'm curious why `centos_8.stream_container_tools.yaml` was in `mds_upgrade_sequence`, prior to commit you mentioned it was this commit [b1420e5](https://github.com/ceph/ceph/commit/b1420e5771927f5c659e0e5edbc5714035f3df09) that added centos 8.3 with container tools, so the container tools have always existed in this suite and somewhere it might be needed, just to be safe I feel we should add container tools too. It also would make it uniform across the suite

The commit message does not mention that, so I'm too unsure why - I'll do a follow up PR for that.

**Pull request merged**
