### PR TITLE
doc/cephfs: Changes in cephfs-top doc.

### PR DESCRIPTION
**Pull request by neesingh-rh**
cephfs-top: Changes in cephfs-top doc due to change in structure of perf_stats o/p.
1. filesystem is being added as a field.

Signed-off-by: Neeraj Pratap Singh <neesingh@redhat.com>

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [x] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [x] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Review by lxbsz — CHANGES_REQUESTED** [review]
Could you explain more what has changed in the commit comments ?

**Comment by neesingh-rh** [comment]
> Could you explain more what has changed in the commit comments ?

Will update it after adding more changes.

**Review by joscollin — COMMENTED** [review]
These type of command outputs in the docs makes it hard to maintain, as it needs update every-time something new introduces.

**Comment by anthonyeleven** [comment]
I think it's valuable to give a sense of what to expect, even if the specifics might partially change over time.

**Comment by neesingh-rh** [comment]
Closing this doc PR, will push these changes as part of the code change PR.

**Pull request closed without merging**
