### PR TITLE
rgwlc:  introduce optional_cookie to LCEntry and cognate types

### PR DESCRIPTION
**Pull request by mattbenjamin**
The optional_cookie tracks value of RGWLC::cookie, which is a random
value set at server/instance boot time.  IOW, this is a way to detect
whether the current, running radosgw instance is the one which last
updated a given LC entry.  The intended use is to robustify detection
of stale LC entries.

Signed-off-by: Matt Benjamin <mbenjamin@redhat.com>

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [x] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [x] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Review by soumyakoduri — COMMENTED** [review]
Changes look good to me. 

However I like to understand why and where it is used. Will it be checked in addition to entry.start_time in expired_session()? Will the entries from previous session be removed from the list?

**Comment by mattbenjamin** [comment]
> Changes look good to me.
> 
> However I like to understand why and where it is used. Will it be checked in addition to entry.start_time in expired_session()? Will the entries from previous session be removed from the list?

Yes, that's the idea.  I am imagining making it impossible for sessions to be un-staled if the cookie == event.optional_cookie, unless overridden by an option

**Comment by soumyakoduri** [comment]
> > Changes look good to me.
> > However I like to understand why and where it is used. Will it be checked in addition to entry.start_time in expired_session()? Will the entries from previous session be removed from the list?
> 
> Yes, that's the idea. I am imagining making it impossible for sessions to be un-staled if the cookie == event.optional_cookie, unless overridden by an option; otherwise, no, we'd not alter the event/list

ok. thanks!

**Review by soumyakoduri — APPROVED** [review]

**Comment by mattbenjamin** [comment]
@soumyakoduri here's the rest of it :)

**Comment by mattbenjamin** [comment]
this change is superceded by now-merged "noreset" patchset

**Pull request closed without merging**
