### PR TITLE
mgr/dashboard: Bumped protractor version to 6.0.0

### PR DESCRIPTION
**Pull request by callithea**
Since we're currently facing issues with the
ceph dashboard tests saying that the installed
google-chrome-stable version is too high this might
be a possible fix.

Signed-off-by: Laura Paduano <lpaduano@suse.com>

- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by callithea** [comment]
jenkins test dashboard

**Comment by rjfd** [comment]
jenkins test dashboard

**Comment by callithea** [comment]
jenkins test dashboard

**Comment by callithea** [comment]
jenkins test dashboard

**Comment by callithea** [comment]
jenkins test make check

**Comment by callithea** [comment]
jenkins test make check

**Comment by callithea** [comment]
jenkins retest this please

**Comment by callithea** [comment]
jenkins test make check

**Comment by callithea** [comment]
So now there's a different issue with starting the webdriver-manager:
```
Cannot automatically find webdriver-manager to update.
Update webdriver-manager manually and run 'ng e2e --no-webdriver-update' instead.
Error: Cannot automatically find webdriver-manager to update.
Update webdriver-manager manually and run 'ng e2e --no-webdriver-update' instead.
```

Seems like it's related to https://github.com/angular/protractor/issues/5209

**Pull request closed without merging**
