### PR TITLE
jewel: rgw - default quota fixes

### PR DESCRIPTION
**Pull request by dang**
This is a backport for http://tracker.ceph.com/issues/16447

### CODE REVIEW

**Comment by smithfarm** [comment]
Thanks for the backport! It's missing "cherry picked from" lines, though, and description of how conflicts (if any) were resolved.

**Comment by dachary** [comment]
Hey jenkins, test this please (jenkins general failure)

**Comment by prallabh** [comment]
thanks @dang

**Comment by dachary** [comment]
DNM because it could be responsible for http://tracker.ceph.com/issues/16344#note-38

**Comment by dang** [comment]
New update that fixes a bug in the backport found during downstream testing.  It passes the QA tests now.

**Comment by dachary** [comment]
This backport passed a rgw suite http://tracker.ceph.com/issues/17487#note-3

@dang could you please update this pull request with commits that are obtained with **git cherry-pick -x** ? They are formatted in a way that agrees with scripts. I see you commented on how you resolved conflicts which is really helpful.

**Comment by dang** [comment]
@dachary Done.  Sorry for the noise; git was being uncooperative.

**Comment by dachary** [comment]
It passed the rgw suite http://tracker.ceph.com/issues/17487#note-11.

**Pull request merged**
