### PR TITLE
rgw/auth: fix internal server error for presigned urls

### PR DESCRIPTION
**Pull request by tobias-urdin**
We have special error handling for these cases but we don't check the negative value of the error so it
instead gets caught as an error not defined with a response and throws a http 500.

This was implement by [1] and the same way done
with [2].

[1] https://github.com/ceph/ceph/pull/55371
[2] https://github.com/ceph/ceph/pull/56044

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Comment by tobias-urdin** [comment]
@cbodley this was backported as well so might want to pull this back in those releases as well

**Comment by cbodley** [comment]
> @cbodley this was backported/is in 19.x release as well so might want to pull this back in those releases as well

thanks @tobias-urdin. it looks like https://github.com/ceph/ceph/pull/59984 conflicts with this one. if we need to backport this, it should merge before https://github.com/ceph/ceph/pull/59984

**Comment by cbodley** [comment]
i opened https://tracker.ceph.com/issues/68300 to track the squid backport

**Comment by tobias-urdin** [comment]
you can merge this at your discretion and i will rebase https://github.com/ceph/ceph/pull/59984 on that, proposed as two different patches because this solves the immediate issue while the other patch was a proposal on (imo) a better approach but wasn't sure if it would allow a backport of that

**Review by cbodley — APPROVED** [review]

**Comment by cbodley** [comment]
https://jenkins.ceph.com/job/ceph-pull-requests/143988/
> The following tests FAILED:
	244 - unittest_rgw_lua (Failed)
	245 - unittest_posix_bucket_cache (Failed)

unrelated, but opened https://tracker.ceph.com/issues/68335 and https://tracker.ceph.com/issues/68336 to track

**Comment by cbodley** [comment]
jenkins test make check

**Comment by cbodley** [comment]
https://jenkins.ceph.com/job/ceph-api/82249/
> ERROR: setUpClass (tasks.mgr.dashboard.test_health.HealthTest)

tracked in https://tracker.ceph.com/issues/47612

**Comment by cbodley** [comment]
jenkins test api

**Comment by cbodley** [comment]
https://jenkins.ceph.com/job/ceph-api/82529/
> dashboard.exceptions.DashboardException: Orchestrator is unavailable

**Comment by cbodley** [comment]
jenkins test api

**Comment by cbodley** [comment]
https://jenkins.ceph.com/job/ceph-pull-requests/144257/
> Issue with agent

**Comment by cbodley** [comment]
jenkins test make check

**Comment by cbodley** [comment]
passed qa in https://pulpito.ceph.com/cbodley-2024-10-04_20:33:53-rgw-wip-cbodley-testing-distro-default-smithi/

**Comment by jzhu116-bloomberg** [comment]
is there a s3 test case for this?

**Pull request merged**
