### PR TITLE
monitoring: update grafana-piechart-panel plugin

### PR DESCRIPTION
**Pull request by p-se**
Fixes: https://tracker.ceph.com/issues/51211

Signed-off-by: Patrick Seidensal <pseidensal@suse.com>

## Checklist
- [x] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by p-se** [comment]
Tested it to work with the currently shipped upstream version 6.7.4 of Grafana as well as Grafana 7.

**Comment by p-se** [comment]
jenkins test docs

**Comment by p-se** [comment]
jenkins render docs

**Comment by p-se** [comment]
jenkins retest this

**Comment by p-se** [comment]
jenkins retest this please

**Comment by epuertat** [comment]
@p-se so eventually it was a drop-in replacement? Great then!

**Review by epuertat — APPROVED** [review]

**Comment by p-se** [comment]
> @p-se so eventually it was a drop-in replacement? Great then!

Yes. Any idea how to restart the docs tests? Especially docs/redthedocs.org:ceph. `jenkins retest this please` didn't do the trick.

**Comment by nizamial09** [comment]
jenkins test dashboard

**Comment by nizamial09** [comment]
jenkins render docs

**Comment by nizamial09** [comment]
> Especially docs/redthedocs.org:ceph. `jenkins retest this please` didn't do the trick.

No clue on how to restart this one though. And dashboard cephadm e2e tests are failing for a known reason.

**Review by aaSharma14 — APPROVED** [review]

**Comment by nizamial09** [comment]
jenkins test dashboard

**Comment by epuertat** [comment]
jenkins retest this please

**Pull request merged**
