### PR TITLE
librados: Reject the invalid pool create request at client side, rath…

### PR DESCRIPTION
**Pull request by yanghonggang**
…er than the mon side

Signed-off-by: Yang Honggang <yanghonggang@umcloud.com>

### CODE REVIEW

**Comment by yanghonggang** [comment]
2018-04-09 11:01:42.027 7f0f26fe0700 10 mon.a@0(leader).osd e8 prepare_pool_op pool_op(create pool 0 auid 0 tid 1 name  v0) v4
2018-04-09 11:01:42.027 7f0f26fe0700 10 mon.a@0(leader).osd e8 prepare_new_pool from 0x55b21c18bc00
2018-04-09 11:01:42.027 7f0f26fe0700 10 mon.a@0(leader).osd e8 prepare_new_pool got -22
...
2018-04-09 11:01:42.611 7f0f22fd8700  2 mon.a@0(leader) e1 send_reply 0x55b21c198e40 0x55b21c3a8280 pool_op_reply(tid 1 (22) Invalid argument v9) v1
2018-04-09 11:01:42.611 7f0f22fd8700  1 -- 172.31.16.244:40855/0 --> 172.31.16.244:0/2469472384 -- pool_op_reply(tid 1 (22) Invalid argument v9) v1 -- 0x55b21c3a8280 con 0

**Comment by yanghonggang** [comment]
pool create with empty pool name will fail, **but with our osdmap's epoch increased by one**

**Comment by yanghonggang** [comment]
@xiexingguo please help to review :)

**Comment by tchaikov** [comment]
http://pulpito.ceph.com/kchai-2018-04-23_07:38:14-rados-wip-kefu-testing-2018-04-23-1357-distro-basic-smithi/

test failures are tracked / addressed by

- http://tracker.ceph.com/issues/23653
- #21594
- #21581

**Comment by tchaikov** [comment]
retest this please.

**Pull request merged**
