### PR TITLE
mgr/dashboard: Update RxJS to version 6

### PR DESCRIPTION
**Pull request by tspmelo**
I used rxjs-tslint tool to automatically update most of the necessary code.

I added a new package, rxjs-compat, to maintain the compatibility
of external plugins that are still using RxJS v5.X.

`Signed-off-by: Tiago Melo <tmelo@suse.com>`

This is one of the updates that will be needed for Angular 6.

I would suggest you to watch this presentation by Ben Lesh, where he introduces what's new in v6:
https://www.youtube.com/watch?v=JCXZhe6KsxQ

### CODE REVIEW

**Comment by votdev** [comment]
jenkins retest this please

**Comment by tspmelo** [comment]
@ricardoasmarques This PR can wait till feature freeze is over.

**Comment by tspmelo** [comment]
I rebased this PR and fixed the missing convertions.
Building and testing are working.

**Comment by tspmelo** [comment]
jenkins retest this please

**Pull request merged**
