### PR TITLE
[RFC]osd: avoid send duplicated osdmap.

### PR DESCRIPTION
**Pull request by majianpeng**
For every subop, it check maybe_share_map. But for the currently code,
it firstly sent new osdmap and then update epoch. So multi pgs can sent
the same osdmap to the same osd.
To avoid this, we firstly update epoch and then send the new odsmap.

Signed-off-by: Jianpeng Ma <jianpeng.ma@intel.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by majianpeng** [comment]
retest this please

**Comment by majianpeng** [comment]
@liewegas . have you time review this pr? Thanks!

**Comment by liewegas** [comment]
I remember deliberately structuring the code this way, but I don't quite remember why.  I think the worst case here is that you'd have two threads/PGs and the first would say it was going to send the new map, the second would see it doesn't need to and then send a reply sooner, such that the OSD gets a reply suggesting a newer map exists before that map arrives.  I think the worst thing that could happen on the OSD in that case is asking the mon for the map, though, which isn't that bad. But then again, getting an incremental map twice is that bad either.  @neha-ojha @jdurgin ?

**Comment by majianpeng** [comment]
retest this please

**Comment by majianpeng** [comment]
retest this please

**Comment by majianpeng** [comment]
retest this please

**Comment by majianpeng** [comment]
retest this please

**Comment by majianpeng** [comment]
jenkins retest this please

**Comment by majianpeng** [comment]
jenkins retest this please

**Comment by majianpeng** [comment]
jenkins retest this please

**Comment by majianpeng** [comment]
jenkins retest this please

**Comment by majianpeng** [comment]
retest this please

**Pull request closed without merging**
