### PR TITLE
src/test: add testcase file for low level sync io code paths

### PR DESCRIPTION
**Pull request by dparmar18**
and test that providing null or invalid file handle returns an error as expected

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Comment by dparmar18** [comment]
backports like https://tracker.ceph.com/issues/64740 or https://tracker.ceph.com/issues/64739 which are intended for async io are not possible because older releases do not have that feature(feature is available only since squid), but that doesn't mean we cannot/shouldn't backport the patch https://github.com/ceph/ceph/pull/55457, the code that it fixes also impact the sync code path, we anyways have a tracker for this https://tracker.ceph.com/issues/63712 to add sync io (lower level) code path test cases so let us have this test case merged into main and then this test case along with the source code from https://github.com/ceph/ceph/pull/55457 can be backported for the backport trackers mentioned above.

**Comment by dparmar18** [comment]
Passes locally
```
[       OK ] TestClient.LlreadvLlwritevInvalidFileHandleSync (207 ms)
[----------] 27 tests from TestClient (8600 ms total)

[----------] Global test environment tear-down
[==========] 27 tests from 1 test suite ran. (8600 ms total)
[  PASSED  ] 27 tests.
```

**Comment by dparmar18** [comment]
> backports like https://tracker.ceph.com/issues/64740 or https://tracker.ceph.com/issues/64739 which are intended for async io are not possible because older releases do not have that feature(feature is available only since squid), but that doesn't mean we cannot/shouldn't backport the patch #55457, the code that it fixes also impact the sync code path, we anyways have a tracker for this https://tracker.ceph.com/issues/63712 to add sync io (low level) code path test cases so let us have this test case merged into main and then this test case along with the source code from #55457 can be backported for the backport trackers mentioned above.

once i'm done with my ongoing work, i'll push more test cases to this file for better sync io code coverage

**Comment by vshankar** [comment]
@dparmar18 As discussed, this needs to be backported along with the async test cases. For releases that don't have the async calls, we can backport the sync test cases.

**Comment by vshankar** [comment]
> once i'm done with my ongoing work, i'll push more test cases to this file for better sync io code coverage

Please tag me on the PR when its ready for review.

**Comment by dparmar18** [comment]
> > once i'm done with my ongoing work, i'll push more test cases to this file for better sync io code coverage
> 
> Please tag me on the PR when its ready for review.

this is ready for review, for now this is the only sync io test case that needs to be merged

**Review by vshankar — APPROVED** [review]

**Comment by vshankar** [comment]
This PR is under test in [https://tracker.ceph.com/issues/66327](https://tracker.ceph.com/issues/66327).

**Comment by vshankar** [comment]
This PR is under test in [https://tracker.ceph.com/issues/66522](https://tracker.ceph.com/issues/66522).

**Review by vshankar — APPROVED** [review]
https://tracker.ceph.com/projects/cephfs/wiki/Main#wip-vshankar-testing-20240617094253-debug

(https://tracker.ceph.com/issues/66522)

**Pull request merged**
