### PR TITLE
msg/async/ProtocolV2: assume peer has SERVER_NAUTILUS for encoding v2 frame

### PR DESCRIPTION
**Pull request by liewegas**
The v2 frames may contain entity_addr_t and entity_addrvec_t.  Those have
been understood since the MSG_ADDR2 feature, but with nautilus we've
additionally added the TYPE_ANY, and we encode TYPE_ANY addrs as
TYPE_LEGACY when the peer lacks SERVER_NAUTILUS.

For the purposes of the v2 protocol, we assume the peer understands
TYPE_ANY.

No other complex types are used in the v2 frame protocol, so this has no
effect on, e.g., what features we assume the peer has for the purposes
of encoding actual messages.

Signed-off-by: Sage Weil <sage@redhat.com>

### CODE REVIEW

**Comment by liewegas** [comment]
Note that the alternative for this fix would be to get rid of the somehwat-weird munging of TYPE_ANY to TYPE_LEGACY when encoding addrs.  That was added to make the OSDMap blacklist encoding life a bit easier.. without it, in order to encode the pre-nautilus OSDMap variant, we'd have to go make a copy of the blacklist map, change every addrs type, and encode that.  Bleh.

Another alternative fix is to define a new feature bit specifically for the purpose of understanding TYPE_ANY addrs.  I'm not sure I want to spend one for this.

I think this is a narrow enough kludge, since no other feature-dependent encoding happens in the msgr2 protocol frames...

**Comment by batrick** [comment]
http://pulpito.ceph.com/pdonnell-2019-02-14_23:44:19-fs-wip-pdonnell-testing-20190214.215026-distro-basic-smithi/

**Comment by batrick** [comment]
Seems to resolve the failures mentioned in the email. Thanks @liewegas !

**Comment by liewegas** [comment]
retest this please

**Pull request merged**
