### PR TITLE
quincy: pybind/mgr/progress: enforced try and except on accessing event dictionary

### PR DESCRIPTION
**Pull request by kamoltat**
There is a certain race condition scenario where
an event gets deleted while the progress module
iterates through the ``events`` dictionary,
without a ``try and except``, this will cause
an unhandled exception error and will crash
the module.

This commit will enforce ``try and except``
on every part of the code where we are accessing
the ``events`` dictionary.

Fixes: https://tracker.ceph.com/issues/53803

Backporting the relevant commits from master PR:
#44553

Signed-off-by: Kamoltat <ksirivad@redhat.com>

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Review by neha-ojha — APPROVED** [review]

**Comment by kamoltat** [comment]
Failure due to PG recovery event not getting triggered. This is because no pgs were affected by the osd.0 being marked out, this happened because the osd.0 id was not in any of the PG's acting sets (both old osd map and new osd map). 
https://pulpito.ceph.com/ksirivad-2022-01-19_20:56:10-rados:mgr-wip-ksirivad-quincy-backport-44553-distro-basic-smithi/6628033/

**Comment by yuriw** [comment]
From @ljflores 

"@yuriweinstein @nehaojha looks good from a RADOS standpoint.

Failures, unrelated:
Bug #53843: mgr/dashboard: Error - yargs parser supports a minimum Node.js version of 12. - Dashboard - Ceph
Bug #53827: cephadm exited with error code when creating osd. - Orchestrator - Ceph
Bug #49287: podman: setting cgroup config for procHooks process caused: Unit libpod-$hash.scope not found - Orchestrator - Ceph
Bug #53807: Dead jobs in rados/cephadm/smoke-roleless{...}: ingress jobs stuck - Orchestrator - Ceph

Details:
Bug_#53843: mgr/dashboard: Error - yargs parser supports a minimum Node.js version of 12. - Ceph - Mgr - Dashboard
Bug_#53827: cephadm exited with error code when creating osd: Input/Output error. Faulty NVME? - Infrastructure - Sepia
Bug_#49287: podman: setting cgroup config for procHooks process caused: Unit libpod-$hash.scope not found - Ceph - Orchestrator
Bug_#53807: Dead jobs in rados/cephadm/smoke-roleless{...} - Ceph - Orchestrator"

**Comment by neha-ojha** [comment]
> From @ljflores
> 
> "@yuriweinstein @Nehaojha looks good from a RADOS standpoint.
> 
> Failures, unrelated: Bug #53843: mgr/dashboard: Error - yargs parser supports a minimum Node.js version of 12. - Dashboard - Ceph Bug #53827: cephadm exited with error code when creating osd. - Orchestrator - Ceph Bug #49287: podman: setting cgroup config for procHooks process caused: Unit libpod-$hash.scope not found - Orchestrator - Ceph Bug #53807: Dead jobs in rados/cephadm/smoke-roleless{...}: ingress jobs stuck - Orchestrator - Ceph
> 
> Details: Bug_#53843: mgr/dashboard: Error - yargs parser supports a minimum Node.js version of 12. - Ceph - Mgr - Dashboard Bug_#53827: cephadm exited with error code when creating osd: Input/Output error. Faulty NVME? - Infrastructure - Sepia Bug_#49287: podman: setting cgroup config for procHooks process caused: Unit libpod-$hash.scope not found - Ceph - Orchestrator Bug_#53807: Dead jobs in rados/cephadm/smoke-roleless{...} - Ceph - Orchestrator"

@yuriw looks good to merge!

**Comment by kamoltat** [comment]
Think merging this PR should be fine, the failure I posted above in the comments is more related to how the test case doesn't accurately evaluate when 0 PGs are affected due to marking osd in or out: https://tracker.ceph.com/issues/53984. Therefore, this PR is not affected if it merges first as it fixes another separate issue.

**Comment by epuertat** [comment]
jenkins test api

**Pull request merged**
