### PR TITLE
revert: osd: use GMT time for hitsets

### PR DESCRIPTION
**Pull request by dachary**
"Merge pull request #5825 from tchaikov/wip-12848-hammer"

This reverts commit 39544718dc2f09bcfdc632ac72fd2a3cda87687e, reversing
changes made to 4ad97162026e1eb6e6e948ddf3eb39f711431e45.

http://tracker.ceph.com/issues/13812 Fixes: #13812

Signed-off-by: Loic Dachary <loic@dachary.org>

### CODE REVIEW

**Comment by dachary** [comment]
@tchaikov reverting this series fixes the regression

<pre>
teuthology-openstack --verbose --key-name myself  --key-filename ~/Downloads/myself --ceph-git-url https://github.com/dachary/ceph.git --ceph-qa-suite-git-url https://github.com/dachary/ceph-qa-suite.git --filter='upgrade:hammer/older/{0-cluster/start.yaml 1-install/v0.94.yaml 2-workload/blogbench.yaml 3-upgrade-sequence/upgrade-osd-mon-mds.yaml 4-final/{monthrash.yaml osdthrash.yaml testrados.yaml} distros/ubuntu_14.04.yaml}' --verbose --suite upgrade/hammer --suite-branch wip-buildpackages-refactor-hammer --ceph hammer-backports-bisect-try
</pre>

* *pass* http://167.114.233.32:8081/ubuntu-2015-11-18_20:38:25-upgrade:hammer-hammer-backports-bisect-try---basic-openstack/

**Comment by dzafman** [comment]
@dachary I don't see this reversing changes to 4ad97162026e1eb6e6e948ddf3eb39f711431e45

**Comment by dachary** [comment]
@dzafman 3954471 is a merge and its first parent is 4ad9716. The change 3954471 were on top of 4ad9716 and were reverted. Is that clearer ? I'm not sure actually :-)

**Comment by tchaikov** [comment]
lgtm. let's merge it to unblock other backport commits. and i will figure out what's going on.

**Pull request merged**
