### PR TITLE
jewel: mds: wrongly treat symlink inode as normal file/dir when symlink inode is stale on kcephfs

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/16083

### CODE REVIEW

**Comment by dachary** [comment]
test this please (bluefs mount crash)

**Comment by dachary** [comment]
Hey jenkins, test this please (logs are gone)

**Comment by dachary** [comment]
@ukernel does this backport look good to merge ? It passed the fs suite http://tracker.ceph.com/issues/16344#note-15.

**Comment by dachary** [comment]
@ukernel ping ?

**Comment by gregsfortytwo** [comment]
FYI this looks good to me.

**Pull request merged**
