### PR TITLE
mimic: osd: Add support for osd_delete_sleep configuration value

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/36729

### CODE REVIEW

**Comment by dzafman** [comment]
@smithfarm This isn't building related to configuration value handling _cct->_conf.get_val<double>("osd_delete_sleep")_

**Comment by smithfarm** [comment]
@dzafman Thanks! Added conflicts section:

```
Conflicts:
    src/osd/OSD.cc
- use mimic-style "cct->_conf->osd_delete_sleep" instead of
  "cct->_conf.get_val<double>("osd_delete_sleep")"
```

**Comment by smithfarm** [comment]
```
/home/jenkins-build/build/workspace/ceph-pull-requests/src/osd/PG.cc: In member function 'void PG::_delete_some(ObjectStore::Transaction*)':
/home/jenkins-build/build/workspace/ceph-pull-requests/src/osd/PG.cc:6553:28: error: 'class OSDService' has no member named 'sleep_lock'; did you mean 'superblock'?
       Mutex::Locker l(osd->sleep_lock);
                            ^~~~~~~~~~
                            superblock
/home/jenkins-build/build/workspace/ceph-pull-requests/src/osd/PG.cc:6554:12: error: 'class OSDService' has no member named 'sleep_timer'; did you mean 'agent_timer'?
       osd->sleep_timer.add_event_at(delete_schedule_time,
            ^~~~~~~~~~~
            agent_timer
src/osd/CMakeFiles/osd.dir/build.make:134: recipe for target 'src/osd/CMakeFiles/osd.dir/PG.cc.o' failed
make[3]: *** [src/osd/CMakeFiles/osd.dir/PG.cc.o] Error 1
```

**Comment by yuriw** [comment]
[wip-yuri-testing-2018-12-13-1649-mimic](https://trello.com/c/sypES05t/489-wip-yuri-testing-2018-12-13-1649-mimic)

**Pull request merged**
