### PR TITLE
jewel: mds: fix MDSMap upgrade decoding

### PR DESCRIPTION
**Pull request by jcsp**
Fixes: http://tracker.ceph.com/issues/18100

### CODE REVIEW

**Comment by smithfarm** [comment]
Ah, how easy the cherry-pick becomes when you cherry-pick the right other commit, first :-)

**Comment by smithfarm** [comment]
@jcsp This passed an fs suite at http://tracker.ceph.com/issues/17851#note-49 with 3 valgrind-related failures. OK to merge?

**Comment by oschulz** [comment]
Thanks you so much for this, @jcsp! This patch just saved our cluster, after upgrading from Hammer to Jewel.

**Comment by dachary** [comment]
Passed http://tracker.ceph.com/issues/17851#note-65

**Pull request merged**
