### PR TITLE
jewel: rgw: inefficient buffer usage for PUTs

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/23348

### CODE REVIEW

**Comment by smithfarm** [comment]
retest this please (Jenkins seems to need kicking for new PRs)

**Comment by smithfarm** [comment]
retest this please

**Comment by smithfarm** [comment]
@cbodley @mattbenjamin Could this PR be causing swift testChunkedPut to fail? See http://tracker.ceph.com/issues/23563

**Comment by cbodley** [comment]
@smithfarm that's possible, but worrying. i don't have a jewel environment to test myself with/without this commit

**Comment by smithfarm** [comment]
@cbodley No problem. I'll schedule some runs to get to the bottom of it.

**Comment by smithfarm** [comment]
https://shaman.ceph.com/builds/ceph/wip-smithfarm-testing-2018-04-05-2204/

**Comment by smithfarm** [comment]
@cbodley @mattbenjamin Regarding the testChunkedPut failure [1] I just noticed that **all** the failures are btrfs. Also, they are all in either `rgw/verify` or `rgw/multifs`. I hope to pinpoint the culprit PR soon.

[1] http://tracker.ceph.com/issues/23563

**Comment by smithfarm** [comment]
@cbodley @mattbenjamin Following up on the previous comment, take a look at this (I'm in jewel branch):

```
smithfarm@wilbur:~/src/ceph/smithfarm/ceph> find -L qa/suites/rados -name '*btrfs*'
smithfarm@wilbur:~/src/ceph/smithfarm/ceph> find -L qa/suites/rgw -name '*btrfs*'
qa/suites/rgw/multifs/fs/btrfs.yaml
qa/suites/rgw/verify/fs/btrfs.yaml
```

My tentative conclusion is that whatever it is might be a btrfs issue in rados, that we are no longer testing for because btrfs has been dropped from the jewel rados suite.

**Comment by smithfarm** [comment]
And, if we don't care about btrfs anymore, we could "resolve" the issue by simply dropping btrfs from `rgw/verify` and `rgw/multimds`. . .

**Comment by smithfarm** [comment]
OK, the reproducer passes on baseline jewel, and fails on this PR:

```
2018-04-06T01:01:41.128 INFO:teuthology.orchestra.run.smithi103.stderr:testChunkedPut (test.functional.tests.TestFile) ... FAIL
```

Removing it from the integration branch for now.

**Comment by mattbenjamin** [comment]
@smithfarm let's coordinate on nailing this--there memory growth issue this PR deals with is very significant in some workloads.

Matt

**Comment by smithfarm** [comment]
@mattbenjamin OK. JFYI, the reproducer I used is `--suite rgw --filter="rgw/multifs/{clusters/fixed-2.yaml frontend/apache.yaml fs/btrfs.yaml objectstore/filestore-xfs.yaml overrides.yaml rgw_pool_type/replicated.yaml tasks/rgw_swift.yaml}"` (it completes within 25 minutes)

**Comment by mattbenjamin** [comment]
thanks!

**Comment by smithfarm** [comment]
Looking closer at btrfs/xfs in jewel rgw suite, I see that the current state is rather bogus:

1. `rgw/verify` **only** tests on btrfs
2. `rgw/multifs` includes both `fs/btrfs.yaml` and `objectstore/filestore-xfs.yaml`, with the latter always overriding the former, so it **only** tests on xfs

**Comment by smithfarm** [comment]
It's very unlikely that the testChunkedPut failure has anything to do with btrfs, since the failures occur on both btrfs and xfs.

**Comment by mdw-at-linuxbox** [comment]
I tried out running "swift tests" standalone on a downstream jewel build - everything passes including "testChunkedPut".  I guess I'll look at your integration branch "wip-jewel-backports" next.

**Comment by smithfarm** [comment]
> I tried out running "swift tests" standalone on a downstream jewel build - everything passes including "testChunkedPut". I guess I'll look at your integration branch "wip-jewel-backports" next.

Thanks, @mdw-at-linuxbox - actually, `wip-jewel-backports` no longer includes this PR, so you probably won't reproduce the failure on that one. I reproduced it on `wip-jewel-pr21098` which is jewel + this PR.

**Comment by mdw-at-linuxbox** [comment]
I built a copy of "wip-jewel-pr21098", and it has the same behavior described in tracker 23563.  Since I don't see this behavior in a "downstream" build of jewel, and the patch in this branch applies against logic which has changed since whatever I originally developed against, I think there must be some other code changes somewhere that result in this bug, which only manifest with this patch.  But I don't know yet what that code is.

**Comment by mdw-at-linuxbox** [comment]
Looks like the commit is simply borked after all.
The call to mg_read in RGWMongoose::read_data should read,

ret = mg_read(conn, buf+c, len-c);

**Comment by smithfarm** [comment]
https://shaman.ceph.com/builds/ceph/wip-jewel-pr21098/82e57cfb69f80b3f0c114e51fb88d5fed70e1f4b/

Reproducer **pending build**

**Comment by smithfarm** [comment]
This passed an rgw suite at http://tracker.ceph.com/issues/21742#note-30

**Comment by smithfarm** [comment]
> Probably master should get the same fix

Opened https://github.com/ceph/ceph/pull/21291

**Comment by mattbenjamin** [comment]
@smithfarm I think Marcus and team agreed it should be ok against master, but iirc we could not reproduce the bad behavior on master.

**Pull request merged**
