### PR TITLE
mstart: copy ceph.conf and keyring to VSTART_DEST dir

### PR DESCRIPTION
**Pull request by Leeshine**
Signed-off-by: lvshanchun <lvshanchun@gmail.com>

### CODE REVIEW

**Comment by cbodley** [comment]
hi @Leeshine, can you describe why these steps are needed? are you running mstart.sh manually, or as part of `test/rgw/test_multi.py`?

**Comment by Leeshine** [comment]
I running it manually,  while the  VSTART_DEST dir exist, but ceph.conf and keyring file do not exist.

**Comment by cbodley** [comment]
adding the `-n` flag tells vstart.sh to generate these files in the right place - does that work for you?

**Comment by Leeshine** [comment]
It works， Thank you very much.  And  maybe it's necessary to add some usage info in mstart ? @cbodley

**Comment by cbodley** [comment]
@Leeshine i think the usage looks ok, at least for those familiar with vstart:
> ~/ceph/build $ ../src/mstart.sh
usage: ../src/mstart.sh \<name\> [vstart options]..

**Pull request closed without merging**
