### PR TITLE
mgr/cephadm: add command to expose systemd units of all daemons

### PR DESCRIPTION
**Pull request by adk3798**
Fixes: https://tracker.ceph.com/issues/64299
    
Signed-off-by: Adam King <adking@redhat.com>

Sample Output:

All daemons:

```
[ceph: root@vm-00 /]# ceph orch systemd-unit ls                 
{
    "vm-00": {
        "mon": {
            "mon.vm-00": "ceph-01f9ae7c-c051-11ee-aa2a-5254007f25c2@mon.vm-00"
        },
        "mgr": {
            "mgr.vm-00.mfzewp": "ceph-01f9ae7c-c051-11ee-aa2a-5254007f25c2@mgr.vm-00.mfzewp"
        },
        "ceph-exporter": {
            "ceph-exporter.vm-00": "ceph-01f9ae7c-c051-11ee-aa2a-5254007f25c2@ceph-exporter.vm-00"
        },
        "crash": {
            "crash.vm-00": "ceph-01f9ae7c-c051-11ee-aa2a-5254007f25c2@crash.vm-00"
        },
        "node-exporter": {
            "node-exporter.vm-00": "ceph-01f9ae7c-c051-11ee-aa2a-5254007f25c2@node-exporter.vm-00"
        },
        "alertmanager": {
            "alertmanager.vm-00": "ceph-01f9ae7c-c051-11ee-aa2a-5254007f25c2@alertmanager.vm-00"
        },
        "grafana": {
            "grafana.vm-00": "ceph-01f9ae7c-c051-11ee-aa2a-5254007f25c2@grafana.vm-00"
        },
        "prometheus": {
            "prometheus.vm-00": "ceph-01f9ae7c-c051-11ee-aa2a-5254007f25c2@prometheus.vm-00"
        }
    },
    "vm-01": {
        "crash": {
            "crash.vm-01": "ceph-01f9ae7c-c051-11ee-aa2a-5254007f25c2@crash.vm-01"
        },
        "node-exporter": {
            "node-exporter.vm-01": "ceph-01f9ae7c-c051-11ee-aa2a-5254007f25c2@node-exporter.vm-01"
        },
        "mon": {
            "mon.vm-01": "ceph-01f9ae7c-c051-11ee-aa2a-5254007f25c2@mon.vm-01"
        },
        "ceph-exporter": {
            "ceph-exporter.vm-01": "ceph-01f9ae7c-c051-11ee-aa2a-5254007f25c2@ceph-exporter.vm-01"
        }
    },
    "vm-02": {
        "crash": {
            "crash.vm-02": "ceph-01f9ae7c-c051-11ee-aa2a-5254007f25c2@crash.vm-02"
        },
        "node-exporter": {
            "node-exporter.vm-02": "ceph-01f9ae7c-c051-11ee-aa2a-5254007f25c2@node-exporter.vm-02"
        },
        "mgr": {
            "mgr.vm-02.nkxxam": "ceph-01f9ae7c-c051-11ee-aa2a-5254007f25c2@mgr.vm-02.nkxxam"
        },
        "mon": {
            "mon.vm-02": "ceph-01f9ae7c-c051-11ee-aa2a-5254007f25c2@mon.vm-02"
        },
        "ceph-exporter": {
            "ceph-exporter.vm-02": "ceph-01f9ae7c-c051-11ee-aa2a-5254007f25c2@ceph-exporter.vm-02"
        }
    }
}
```

Filtered by daemon type:

```
[ceph: root@vm-00 /]# ceph orch systemd-unit ls --daemon-type mgr
{
    "vm-00": {
        "mgr": {
            "mgr.vm-00.mfzewp": "ceph-01f9ae7c-c051-11ee-aa2a-5254007f25c2@mgr.vm-00.mfzewp"
        }
    },
    "vm-02": {
        "mgr": {
            "mgr.vm-02.nkxxam": "ceph-01f9ae7c-c051-11ee-aa2a-5254007f25c2@mgr.vm-02.nkxxam"
        }
    }
}
```

TODO: add docs

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [x] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Review by mgfritch — COMMENTED** [review]
the systemd units are already exposed by the cephadm binary:
```
node1:~ # cephadm ls | jq '.[0].systemd_unit'
"ceph-5050680c-92e5-11ee-a5c5-5254005b8a9a@osd.1"
```

Maybe we should simply add this detail to the existing `ceph orch ls --format yaml` command?

**Comment by adk3798** [comment]
https://pulpito.ceph.com/adking-2024-03-16_05:03:17-orch:cephadm-wip-adk-testing-2024-03-15-1513-distro-default-smithi/

mostly cluster log stuff + mds_upgrade_sequence. Other failures were either known or not reproducible.

**Review by phlogistonjohn — CHANGES_REQUESTED** [review]
As briefly discussed verbally: I think that we don't want this as a `ceph orch` command but rather as a `ceph cephadm` command because not all current and future orchestration backends would make use of systemd.

**Comment by adk3798** [comment]
https://pulpito.ceph.com/adking-2024-09-10_02:59:23-orch:cephadm-wip-adk-testing-2024-09-09-1904-distro-default-smithi/

Failures:
- stray daemon warning in smb test, known issue
- `Test failure: test_nfs_export_creation_without_cmount_path (tasks.cephfs.test_nfs.TestNFS)` caused by a PR in the run
- 2x agent on staggered upgrade failure, known issue
- deploy raw test timed out, known issue
- `test_rgw_multisite` test failed to generate token on realm bootstrap, somewhat new but not the first time I've seen it and it's unrelated to PRs in this run
- 4x mds_upgrade_sequence failures, known issue
- rgw-ingress tests timed out, known issue

Nothing to block merging PRs in the run other than the NFS failure related one

**Comment by adk3798** [comment]
jenkins test api

**Review by phlogistonjohn — APPROVED** [review]
thank you. changes lgtm

**Pull request merged**
