### PR TITLE
reef: qa: test_rebuild_simple checks status on wrong file system

### PR DESCRIPTION
**Pull request by batrick**
https://tracker.ceph.com/issues/59366

Parent ticket: https://tracker.ceph.com/issues/59332
Original PR: https://github.com/ceph/ceph/pull/50896

### CODE REVIEW

**Comment by batrick** [comment]
jenkins test api

**Comment by batrick** [comment]
DNM until https://tracker.ceph.com/issues/59425 is fixed.

**Comment by rishabh-d-dave** [comment]
Same, added links to parent ticket and original to PR description.

**Comment by rishabh-d-dave** [comment]
> DNM until https://tracker.ceph.com/issues/59425 is fixed.

The ticket's PR () hasn't been resolved yet. Marking this PR was DNM.

**Comment by ljflores** [comment]
Rados suite review: https://pulpito.ceph.com/?branch=wip-yuri6-testing-2023-04-26-1247-reef

Failures, unrelated:
    1. https://tracker.ceph.com/issues/59049
    2. https://tracker.ceph.com/issues/59057
    3. https://tracker.ceph.com/issues/59142
    4. https://tracker.ceph.com/issues/58797

Details:
    1. WaitReplicas::react(const DigestUpdate&): Unexpected DigestUpdate event - Ceph - RADOS
    2. rados/test_envlibrados_for_rocksdb.sh: No rule to make target 'rocksdb_env_librados_test' on centos 8 - Ceph - RADOS
    3. mgr/dashboard: fix e2e for dashboard v3 - Ceph - Mgr - Dashboard
    4. scrub/osd-scrub-dump.sh: TEST_recover_unexpected fails from "ERROR: Unexpectedly low amount of scrub reservations seen during test" - Ceph - RADOS

**Comment by yuriw** [comment]
ref: https://trello.com/c/A5LEquRG

**Comment by vshankar** [comment]
> > DNM until https://tracker.ceph.com/issues/59425 is fixed.
> 
> The ticket's PR (PR #51030) hasn't been resolved yet. Marking this PR as DNM.

@rishabh-d-dave PR #51030 is merged. Please do the needful for this PR.

**Review by rishabh-d-dave — APPROVED** [review]

**Pull request merged**
