### PR TITLE
rgw: remove expired entries from the cache

### PR DESCRIPTION
**Pull request by mkogan1**
Fixes: http://tracker.ceph.com/issues/23379

Signed-off-by: Mark Kogan <mkogan@redhat.com>

### CODE REVIEW

**Comment by oritwas** [comment]
@mkogan1 can you add a test in teuthology for this?

**Comment by mkogan1** [comment]
it's queued in shaman/teuthology...

**Comment by mkogan1** [comment]
teuthology:
http://pulpito.ceph.com/mkogan-2018-06-05_15:05:10-rgw-wip-rgw-t23379-distro-basic-mira/

**Comment by cbodley** [comment]
http://pulpito.ceph.com/cbodley-2018-06-20_16:02:29-rgw-wip-cbodley-testing-distro-basic-smithi/

**Pull request merged**
