### PR TITLE
rgw: use the forward declaration of CephContext defined in common_fwd.h

### PR DESCRIPTION
**Pull request by wjwithagen**
Clang complains:
In file included from /home/jenkins/workspace/ceph-master-compile/src/rgw/rgw_lua_utils.cc:5:
/home/jenkins/workspace/ceph-master-compile/src/rgw/rgw_lua_utils.h:8:1: error: declaration conflicts with target of using declaration already in scope
class CephContext;
^
/home/jenkins/workspace/ceph-master-compile/src/include/common_fwd.h:10:9: note: target of using declaration
  class CephContext;
        ^
/home/jenkins/workspace/ceph-master-compile/src/include/common_fwd.h:22:24: note: using declaration
using TOPNSPC::common::CephContext;

Which is more that correct.

To declare CephContext forward, include common_fwd.h.
But this was already included in the hierarcy.

fixes: https://github.com/ceph/ceph/pull/35477

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Review by yuvalif — CHANGES_REQUESTED** [review]
this files uses CephContext* and does not include anything that has that forward declaration (directly or indirectly).
best option is to include `common_fwd.h` here.

**Comment by wjwithagen** [comment]
> 
> 
> this files uses CephContext* and does not include anything that has that forward declaration (directly or indirectly).
> best option is to include `common_fwd.h` here.

Well, it seems that Jenkins here can build and test this PR. So that declaration was not needed for the Linux/GCC build.
That in combination that Clang complains about a conflict with a definition in `common_fwd.h `, leads me to conclude that it is already included...

But if you prefer, I'll add the include anyways.

**Comment by yuvalif** [comment]
> > this files uses CephContext* and does not include anything that has that forward declaration (directly or indirectly).
> > best option is to include `common_fwd.h` here.
> 
> Well, it seems that Jenkins here can build and test this PR. So that declaration was not needed for the Linux/GCC build.
> That in combination that Clang complains about a conflict with a definition in `common_fwd.h `, leads me to conclude that it is already included...
> 
> But if you prefer, I'll add the include anyways.

it is nor needed, because currently the cpp files that include this also include something that already have `common_fwd.h `.
however, header files should be "self sufficient", so they work regardless of the current hierarchies in which they currently are.

**Review by yuvalif — APPROVED** [review]

**Comment by wjwithagen** [comment]
@tchaikov 
Can you take a lot at this one as well?

**Review by tchaikov — CHANGES_REQUESTED** [review]
the title of this commit is wrong. what this change does is not "remove **redundant** CephContext declaration". instead what it does is

> use the forward declaration of CephContext defined in common_fwd.h

**Review by tchaikov — APPROVED** [review]

**Comment by wjwithagen** [comment]
Looks  like it got fixed in https://github.com/ceph/ceph/pull/38459

**Pull request closed without merging**
