### PR TITLE
include, common, osd: use std::strong_ordering machinery

### PR DESCRIPTION
**Pull request by tchaikov**
for better readability and maintainability 

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [x] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by tchaikov** [comment]
jenkins test make check

**Comment by tchaikov** [comment]
need to schedule the windows build on a yammy node (braggi17).

**Comment by tchaikov** [comment]
jenkins test windows

**Review by cbodley — APPROVED** [review]
nice cleanup!

**Comment by tchaikov** [comment]
jenkins test windows

**Comment by tchaikov** [comment]
jenkins test windows

**Comment by tchaikov** [comment]
jenkins test windows

**Comment by tchaikov** [comment]
```
configure: error: in `/home/jenkins-build/build/workspace/ceph-windows-pull-requests/ceph/build.deps/src/curl':
configure: error: cannot run test program while cross compiling
See `config.log' for more details
Build step 'Execute shell' marked build as failure
[PostBuildScript] - [INFO] Executing post build scripts.
[ceph-windows-pull-requests] $ /bin/bash /tmp/jenkins12879402375003685306.sh
+ set -o errexit
+ set -o pipefail
+ delete_libvirt_vms
++ sudo virsh list --all --name
error: failed to connect to the hypervisor
```

from https://jenkins.ceph.com/job/ceph-windows-pull-requests/11804/console

**Comment by tchaikov** [comment]
https://shaman.ceph.com/builds/ceph/wip-pr-47427-kefu-1/147b7aacad2c5e9ebf2a9f17890d64bf191bbaa2/

**Comment by tchaikov** [comment]
being built at https://shaman.ceph.com/builds/ceph/wip-pr-47427-kefu-2/218fe6042c3ea1a20a5288db887e1a3e5aac22a6/

**Comment by tchaikov** [comment]
the build related change is extracted into #47449 to ease the review and test.

**Comment by tchaikov** [comment]
https://pulpito.ceph.com/kchai-2022-08-04_16:10:35-rados-wip-pr-47427-kefu-13-distro-default-smithi/

**Comment by tchaikov** [comment]
i am addressing the FTBFS on windows at https://github.com/ceph/ceph/pull/47470

**Comment by ljflores** [comment]
Hey @tchaikov, can you investigate https://tracker.ceph.com/issues/57074? A few people have built the latest version of main on Centos 8 Stream and were running into build failures having to do with the spaceship operator.

**Comment by markhpc** [comment]
This PR breaks the build on GCC compilers older than GCC10.  (IE the stock GCC in Ubuntu 20.04 LTS, CentOS 8 stream, and potentially others).

See:
https://en.cppreference.com/w/cpp/compiler_support/20

**Comment by tchaikov** [comment]
@ljflores and @markhpc i am sorry for the breakage. i should have sent a mail to notify our developers.  have been busy with lots of build failures surfaced recently in the late nights.

let me add more context for those who are interested in the background. the C++20 migration has taken us months since Casey's mail. and in the past couple weeks, to address the FTBFS on windows, we are fix various issues to enable the tree to build and test on ubuntu jammy which provides a new enough GCC targeting MinGW.

it is not plain-less. we were facing similar issues about 5 years ago. back then, we wanted to use devtoolset-7 and gcc-7 on centos7 and trusty.  we were facing the same issues about 3 years ago. back then, we wanted to migrate from xenial and trusty to ubuntu focal. we were facing the similar issues about 2 years ago. back then, we wanted to ditch the python2 support. this time, we need to support both python3.6, python3.8 and python3.10.

but this time is different, we have to tackle these issues in a single run.

**Comment by cbodley** [comment]
there's a 'C++20 and newer C++ compiler' thread on dev@ceph.io. i'd love to everyone's thoughts on how we can improve the situation

**Pull request merged**
