### PR TITLE
rgw: multisite:Controls for default bucket sync status

### PR DESCRIPTION
**Pull request by prasakri**
On a cluster configured with multisite, all newly created buckets are enabled for sync by default. This poses a problem to certain users who want an opt-in behaviour for enabling sync in order to reduce costs and limit multisite sync only to high priority data.

This set of commits introduces two knobs to control this behaviour:
1. A config option that defines the default sync_enabled state of a bucket (default: false)
2. A user-specific setting which defines whether newly created buckets of this user must have sync enabled by default.

The existing command to override the sync status of a bucket will continue to work as usual.

Signed-off-by: Prasad Krishnan <prasad.krishnan@flipkart.com>

### CODE REVIEW

**Comment by prasakri** [comment]
@mattbenjamin @cbodley - Does this feature make sense (in the light of recent changes in Octopus)?
We've found it to be pretty useful in our setup and helps avoid the unnecessary proliferation of data.

**Comment by cbodley** [comment]
> Does this feature make sense (in the light of recent changes in Octopus)?

Hey @prasakri, I think it does. The per-bucket replication work in Octopus does give us some sync policy primitives that could accomplish this same goal (making bucket sync opt-in instead of opt-out), but it's still experimental and there hasn't been much progress in testing/stabilization. We won't drop support for the existing 'bucket sync disable' feature until per-bucket replication is fully supported, and has a documented process for converting the sync-disabled buckets into the equivalent policy.

I don't think there are per-user sync policies, though, so I don't think we could find a direct mapping to this new 'user sync disable' part. How important is the per-user control, apart from the ability to enable/disable globally?

And for global control, I think the setting belongs in the zonegroup configuration (which is consistent across all of its zones and radosgws) instead of a `rgw_bucket_sync_enable` config variable, which could be enabled/disabled on a per-radosgw basis.

**Comment by prasakri** [comment]
> How important is the per-user control, apart from the ability to enable/disable globally?

We have this use case where multiple users are hosted on a multisite sync enabled cluster but a tiny subset of them actually want a remote-site replica. Buckets belonging to the rest of the users don't have to be replicated and its just a wasteful exercise. Add to that the scenario where both types of users create new buckets all the time which are enabled for sync by default.

So we had to resort to an ugly workaround, where we periodically check for new buckets (by comparing and storing the list of buckets in that cluster) and disable them explicitly using `radosgw-admin bucket sync disable`.

Having a per-user sync control knob (along with some nice dashboard or GUI support for control plane) will make it a lot easier for the admins.

**Comment by prasakri** [comment]
@cbodley - Just checking if the previous reply answers your queries and if the PR is ready for review?

**Comment by cbodley** [comment]
> And for global control, I think the setting belongs in the zonegroup configuration (which is consistent across all of its zones and radosgws) instead of a `rgw_bucket_sync_enable` config variable, which could be enabled/disabled on a per-radosgw basis.

@prasakri this is the part i mentioned in the meeting today

**Pull request closed without merging**
