### PR TITLE
pacific: osd: Run osd bench test to override default max osd capacity for mclock

### PR DESCRIPTION
**Pull request by sseshasa**
backport tracker: https://tracker.ceph.com/issues/51117

---

backport of https://github.com/ceph/ceph/pull/41308
parent tracker: https://tracker.ceph.com/issues/51116

this backport was staged using ceph-backport.sh version 16.0.0.6848
find the latest version at https://github.com/ceph/ceph/blob/master/src/script/ceph-backport.sh

Note: The initial backport was created using the backport script. The latest commits (i.e. from commit 0a5f87cc8a52febd98c4115e7ba78743a2636eb2) added to the PR were cherry-picked.

### CODE REVIEW

**Review by neha-ojha — APPROVED** [review]

**Review by tchaikov — DISMISSED** [review]
why do we need to backport a feature to pacific? also i'd suggest put this backport on hold because of the regression of https://tracker.ceph.com/issues/51074.

**Comment by jdurgin** [comment]
feature vs bug is not black and white. in this case, imo it's a usability issue - asking a user to compile and run fio with a librbd backend to be able to try out qos in pacific is too much effort.

I do think we should hold off on merging this backport until the subsequent changes around this area are completed, namely:
1) fixing the tests
2) persisting the benchmark result in the config
3) not running the benchmark every time - if it's already set, don't rerun, unless we set an option (or some other way of indicating to update it tbd in master)

**Comment by neha-ojha** [comment]
Needs to include https://github.com/ceph/ceph/pull/41782

**Comment by sseshasa** [comment]
Summary of master trackers and associated PRs that are a part of this back-port PR:

1. Original master tracker: https://tracker.ceph.com/issues/51116
   Original PR: https://github.com/ceph/ceph/pull/41308
   
2. Added following missing commits that caused a regression in the standalone 
   tests on master. Tracked by: https://tracker.ceph.com/issues/51074.
   - Commit b6e9c0903d5ad9a699b675f9fa7739e9cce9a5f3 from 
     PR: https://github.com/ceph/ceph/pull/40016
   - Back-port commit from PR: https://github.com/ceph/ceph/pull/41782
     associated with https://tracker.ceph.com/issues/51074. See comment:
     https://github.com/ceph/ceph/pull/41731#issuecomment-863550553
     
3. Added all the commits from PR: https://github.com/ceph/ceph/pull/42133
   associated with tracker: https://tracker.ceph.com/issues/51464
   - The commits address the issues mentioned in the comment in this PR:
     https://github.com/ceph/ceph/pull/41731#issuecomment-857445896

**Comment by neha-ojha** [comment]
> Needs to include #41782

My bad, we don't need this because we are not changing the default to mclock_scheduler in pacific, let's include three things in this backport PR:

1 . mechanism to automate benchmarking for qos
2. ability to persist osd_mclock_max_capacity if the benchmark 
3. any test changes needed for (1) and (2)

**Comment by sseshasa** [comment]
> why do we need to backport a feature to pacific? also i'd suggest put this backport on hold because of the regression of https://tracker.ceph.com/issues/51074.

@tchaikov The changes in https://tracker.ceph.com/issues/51074 will not be backported to pacific as we don't plan on changing the default scheduler. Therefore, all commits related to qa/standalone script are now removed. Can you please unblock this review?

**Comment by sseshasa** [comment]
**Standalone Test Results (Just for sanity):**

OSD Tests:
https://pulpito.ceph.com/sseshasa-2021-08-04_14:40:20-rados:standalone-wip-sseshasa2-testing-2021-08-04-1847-pacific-distro-basic-smithi/

Scrub Tests:
https://pulpito.ceph.com/sseshasa-2021-08-04_16:42:42-rados:standalone-wip-sseshasa2-testing-2021-08-04-1847-pacific-distro-basic-smithi/

Erasure-code Tests:
https://pulpito.ceph.com/sseshasa-2021-08-04_16:45:11-rados:standalone-wip-sseshasa2-testing-2021-08-04-1847-pacific-distro-basic-smithi/

Misc Tests:
https://pulpito.ceph.com/sseshasa-2021-08-04_16:44:19-rados:standalone-wip-sseshasa2-testing-2021-08-04-1847-pacific-distro-basic-smithi/

**Review by neha-ojha — APPROVED** [review]

**Comment by neha-ojha** [comment]
> **Standalone Test Results (Just for sanity):**
> 
> OSD Tests:
> https://pulpito.ceph.com/sseshasa-2021-08-04_14:40:20-rados:standalone-wip-sseshasa2-testing-2021-08-04-1847-pacific-distro-basic-smithi/
> 
> Scrub Tests:
> https://pulpito.ceph.com/sseshasa-2021-08-04_16:42:42-rados:standalone-wip-sseshasa2-testing-2021-08-04-1847-pacific-distro-basic-smithi/
> 
> Erasure-code Tests:
> https://pulpito.ceph.com/sseshasa-2021-08-04_16:45:11-rados:standalone-wip-sseshasa2-testing-2021-08-04-1847-pacific-distro-basic-smithi/
> 
> Misc Tests:
> https://pulpito.ceph.com/sseshasa-2021-08-04_16:44:19-rados:standalone-wip-sseshasa2-testing-2021-08-04-1847-pacific-distro-basic-smithi/

Let's run this through a broader rados run.

**Comment by sseshasa** [comment]
Pulpito Run:

https://pulpito.ceph.com/sseshasa-2021-08-06_04:49:51-rados-wip-sseshasa2-testing-2021-08-04-1847-pacific-distro-basic-smithi/

**Comment by neha-ojha** [comment]
> https://pulpito.ceph.com/sseshasa-2021-08-06_04:49:51-rados-wip-sseshasa2-testing-2021-08-04-1847-pacific-distro-basic-smithi/

The failed jobs are unrelated, and are tracked in the following tickets.

https://tracker.ceph.com/issues/52116
https://tracker.ceph.com/issues/51728
https://tracker.ceph.com/issues/52078 - needs backport PR
https://tracker.ceph.com/issues/52129

@sseshasa could you please rerun the dead job that failed due to an infra issue? This PR can be merged if that  rerun looks good.

**Comment by sseshasa** [comment]
> > https://pulpito.ceph.com/sseshasa-2021-08-06_04:49:51-rados-wip-sseshasa2-testing-2021-08-04-1847-pacific-distro-basic-smithi/
> 
> The failed jobs are unrelated, and are tracked in the following tickets.
> 
> https://tracker.ceph.com/issues/52116
> https://tracker.ceph.com/issues/51728
> https://tracker.ceph.com/issues/52078 - needs backport PR
> https://tracker.ceph.com/issues/52129
> 
> @sseshasa could you please rerun the dead job that failed due to an infra issue? This PR can be merged if that rerun looks good.

Thanks for looking into the failures. I couldn't get to them the last couple of days. I have initiated the re-run of the dead job. I will update on how it goes.

**Comment by sseshasa** [comment]
> > why do we need to backport a feature to pacific? also i'd suggest put this backport on hold because of the regression of https://tracker.ceph.com/issues/51074.
> 
> @tchaikov The changes in https://tracker.ceph.com/issues/51074 will not be backported to pacific as we don't plan on changing the default scheduler. Therefore, all commits related to qa/standalone script are now removed. Can you please unblock this review?

@tchaikov Can you please unblock the PR based on my comments above? Thanks!

**Comment by sseshasa** [comment]
> > > why do we need to backport a feature to pacific? also i'd suggest put this backport on hold because of the regression of https://tracker.ceph.com/issues/51074.
> > 
> > 
> > @tchaikov The changes in https://tracker.ceph.com/issues/51074 will not be backported to pacific as we don't plan on changing the default scheduler. Therefore, all commits related to qa/standalone script are now removed. Can you please unblock this review?
> 
> @tchaikov Can you please unblock the PR based on my comments above? Thanks!

@tchaikov Can you take a look at my comments above and unblock? Thanks.

**Comment by tchaikov** [comment]
@neha-ojha sorry for dismissing your approval by accident. could you kindly redo the approve?

**Review by neha-ojha — APPROVED** [review]

**Comment by neha-ojha** [comment]
> @neha-ojha sorry for dismissing your approval by accident. could you kindly redo the approve?

@tchaikov no worries, done.

**Comment by sseshasa** [comment]
TBD: Backport https://github.com/ceph/ceph/pull/42853 as well.

**Comment by sseshasa** [comment]
@neha-ojha @jdurgin The latest pushes include the following commits related to:
- Skip OSD benchmark based on config option.
- Update 'osd profile' caps to allow running the 'config set' command to set the max OSD capacity.
As already decided, I have not included any qa related changes.

If changes look good, then we can remove the DNM label and run this through teuthology.

**Comment by sseshasa** [comment]
**Pulpito Run Info:**
https://pulpito.ceph.com/yuriw-2021-09-22_14:54:43-rados-wip-yuri8-testing-2021-09-21-0415-pacific-distro-basic-smithi/

**Failures (Unrelated):**
1. https://pulpito.ceph.com/yuriw-2021-09-22_14:54:43-rados-wip-yuri8-testing-2021-09-21-0415-pacific-distro-basic-smithi/6402688
    Tracker issue: https://tracker.ceph.com/issues/52116

2. https://pulpito.ceph.com/yuriw-2021-09-22_14:54:43-rados-wip-yuri8-testing-2021-09-21-0415-pacific-distro-basic-smithi/6402710
    Tracker issue not found. Probably a known issue. Error seen during setting up of the environment and is unrelated to
     the PR.

3. https://pulpito.ceph.com/yuriw-2021-09-22_14:54:43-rados-wip-yuri8-testing-2021-09-21-0415-pacific-distro-basic-smithi/6402717
    Tracker Issue: https://tracker.ceph.com/issues/51728

4. https://pulpito.ceph.com/yuriw-2021-09-22_14:54:43-rados-wip-yuri8-testing-2021-09-21-0415-pacific-distro-basic-smithi/6402805
    Tracker issue: https://tracker.ceph.com/issues/52116

5. https://pulpito.ceph.com/yuriw-2021-09-22_14:54:43-rados-wip-yuri8-testing-2021-09-21-0415-pacific-distro-basic-smithi/6402894
    Same as 2 above

6. https://pulpito.ceph.com/yuriw-2021-09-22_14:54:43-rados-wip-yuri8-testing-2021-09-21-0415-pacific-distro-basic-smithi/6402901
    Same as 3 above.

7. https://pulpito.ceph.com/yuriw-2021-09-22_14:54:43-rados-wip-yuri8-testing-2021-09-21-0415-pacific-distro-basic-smithi/6402919
    Same as 4 above.

**Dead Jobs (Unrelated):**
1. https://pulpito.ceph.com/yuriw-2021-09-22_14:54:43-rados-wip-yuri8-testing-2021-09-21-0415-pacific-distro-basic-smithi/6402669
    Job actually passed.  POST to paddles failed with below error messages:
   
2. https://pulpito.ceph.com/yuriw-2021-09-22_14:54:43-rados-wip-yuri8-testing-2021-09-21-0415-pacific-distro-basic-smithi/6402760
    Tracker issue: https://tracker.ceph.com/issues/51076

3. https://pulpito.ceph.com/yuriw-2021-09-22_14:54:43-rados-wip-yuri8-testing-2021-09-21-0415-pacific-distro-basic-smithi/6402802
    Tracker issue: https://tracker.ceph.com/issues/49888

4. https://pulpito.ceph.com/yuriw-2021-09-22_14:54:43-rados-wip-yuri8-testing-2021-09-21-0415-pacific-distro-basic-smithi/6402896
    Test Failed Due to Socket Error during the unwinding phase after the upgrade test. This occurred due an infra issue
    and is  unrelated to the PR.

**Pull request merged**
