### PR TITLE
core: introduce DirectMessenger

### PR DESCRIPTION
**Pull request by cbodley**
DirectMessenger provides an efficient mechanism to support in-process embedding of Ceph components (e.g., embedding of the Ceph OSD in storage targets such as NFSv4 or iSCSI targets).

This is the messenger used by https://github.com/ceph/ceph/pull/13336 to inject OSD operations within the same process, split out for separate review.

### CODE REVIEW

**Comment by gregsfortytwo** [comment]
Notes from @liewegas over bluejeans: we should put it in a test directory since it's for testing.
It's good that this can't be accidentally instantiated, but let's clearly document its purpose (ie, exclusively for testing and IO injection, do not use as a model, does not complete everything).

**Comment by cbodley** [comment]
* moved src/msg/direct to src/test/direct_messenger
* moved unit test into src/test/direct_messenger
* added text to block comment in DirectMessenger.h:
```
 * This is for testing and i/o injection only, and cannot be used
 * for normal messengers with ms_type.
```

**Comment by liewegas** [comment]
@gregsfortytwo ready for merge?

**Comment by liewegas** [comment]
retest this please

**Comment by gregsfortytwo** [comment]
Yep, we just finished discussing this verbally.

**Comment by gregsfortytwo** [comment]
Sadly the fio integration stuff will reportedly take a bit more work. :(

**Comment by yuriw** [comment]
http://pulpito.ceph.com/yuriw-2017-04-25_00:01:03-rados-wip-yuri-testing_2017_4_25-distro-basic-smithi/

http://pulpito.ceph.com/yuriw-2017-04-25_15:01:54-rados-wip-yuri-testing_2017_4_25---basic-smithi/

**Comment by yuriw** [comment]
test this please

**Pull request merged**
