### PR TITLE
os/store_test: Retune tests to current code

### PR DESCRIPTION
**Pull request by aclamk**
After introduction of lazy statfs updates and mechanism to store them at exit, some tests required tune-up.

Simple harmonization, it clears problems most likely introduced by https://github.com/ceph/ceph/pull/46036.

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [x] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by aclamk** [comment]
ceph test api

**Comment by aclamk** [comment]
jenkins test api

**Comment by ifed01** [comment]
@aclamk - could you please elaborate on what exact issue you're fixing with this PR. The test case works fine for me without it....

**Comment by aclamk** [comment]
> @aclamk - could you please elaborate on what exact issue you're fixing with this PR. The test case works fine for me without it....

Interesting... re-checking it now.

**Comment by aclamk** [comment]
@ifed01 
Tested on:
commit e037aac2bc8b514b37d74fe1173b66905e63309f (HEAD, origin/main)
`./bin/ceph_test_objectstore --gtest_filter=\*RepairTest\*/1 --debug_rocksdb=1/1 --debug_bluestore=1/1`

Note. After Filestore removal, "/1" is now BlueStore.

**Comment by ifed01** [comment]
> @ifed01 Tested on: commit [e037aac](https://github.com/ceph/ceph/commit/e037aac2bc8b514b37d74fe1173b66905e63309f) (HEAD, origin/main) `./bin/ceph_test_objectstore --gtest_filter=\*RepairTest\*/1 --debug_rocksdb=1/1 --debug_bluestore=1/1`
> 
> Note. After Filestore removal, "/1" is now BlueStore.

Ah... that did the trick, I'm still using "/2"...

**Comment by ifed01** [comment]
> > @ifed01 Tested on: commit [e037aac](https://github.com/ceph/ceph/commit/e037aac2bc8b514b37d74fe1173b66905e63309f) (HEAD, origin/main) `./bin/ceph_test_objectstore --gtest_filter=\*RepairTest\*/1 --debug_rocksdb=1/1 --debug_bluestore=1/1`
> > Note. After Filestore removal, "/1" is now BlueStore.
> 
> Ah... that did the trick, I'm still using "/2"...

still works for me though... @aclamk - what's the output in your case?

**Comment by aclamk** [comment]
@ifed01 I hope this helps...
```
akupczyk@o08 build]$ ./bin/ceph_test_objectstore --gtest_filter=\*BluestoreRepairTest\*/1 --debug_rocksdb=1/1 --debug_bluestore=1/1 --log_to_stderr=false
Note: Google Test filter = *BluestoreRepairTest*/1
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from ObjectStore/StoreTestSpecificAUSize
[ RUN      ] ObjectStore/StoreTestSpecificAUSize.BluestoreRepairTest/1
create collection + write
fix leaked pextents
fix false free pextents
undecodable shared blob key
misreferencing
repro bug #21040
Zombie spanning blob
fix invalid statfs
../src/test/objectstore/store_test.cc:9357: Failure
Expected: (bstore->fsck(false)) >= (1), actual: 0 vs 1
../src/os/bluestore/BlueStore.cc: In function 'virtual int BlueStore::umount()' thread 7ffff7fcfa40 time 2023-02-27T14:22:56.147455+0000
../src/os/bluestore/BlueStore.cc: 7805: FAILED ceph_assert(_kv_only || mounted)
 ceph version 18.0.0-2536-ge037aac2bc8 (e037aac2bc8b514b37d74fe1173b66905e63309f) reef (dev)
```

**Pull request closed without merging**
