### PR TITLE
ceph-volume: add tests for new functions that run LVM commands

### PR DESCRIPTION
**Pull request by rishabh-d-dave**
... and for supporting functions. Specifically, these functions are
get_pvs(), get_vgs(), get_lvs(), get_first_pv(), get_first_vg(),
get_first_lv() and make_filters_lvmcmd_ready().

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by rishabh-d-dave** [comment]
jenkins test ceph-volume all

**Comment by rishabh-d-dave** [comment]
jenkins test ceph-volume tox

**Comment by rishabh-d-dave** [comment]
On a different PR which is based on same commit from master, dashboard backend API tests passed. Therefore, re-triggering the test again -

**Comment by rishabh-d-dave** [comment]
jenkins test dashboard backend

**Comment by jan--f** [comment]
@rishabh-d-dave Maybe rebase this?

**Comment by rishabh-d-dave** [comment]
Rebased, the branch in on latest commit of master now.

**Comment by rishabh-d-dave** [comment]
jenkins test ceph-volume all

**Comment by rishabh-d-dave** [comment]
jenkins test ceph-volume tox

**Comment by jan--f** [comment]
same tox failure as in #35937

**Comment by jan--f** [comment]
Also same assumption regarding backports as in #35937 :)

**Pull request merged**
