### PR TITLE
octopus: .github: add labels

### PR DESCRIPTION
**Pull request by tchaikov**
## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by tchaikov** [comment]
@smithfarm hope this changeset could save you some clicks =)

**Comment by smithfarm** [comment]
@tchaikov From my POV, a good start would be to edit the PR description so it contains links to the PRs being backported. Then you could ask the folks who reviewed those PRs for their review? 

I don't know anything about the github labeler, so I don't see how my review could be useful.

**Comment by tchaikov** [comment]
@smithfarm i found you were adding labels manually to backported PRs. the github labeler adds the labels to a PR based on the files involved in that very PR. so thought it'd be useful to add them automatically like we do in master. so i wonder if you'd like this change.

to add the original PRs would be a time-consuming and hence non-trivial task to me. if you think it's a must to reference the original PRs, i will close this one. but if it's a nice-to-have, i will add the component leaders as reviewers of this change.

what do you think?

**Comment by smithfarm** [comment]
@tchaikov I am not insisting on anything, and nothing is a "must have" for me here. I appreciate your efforts, but do not feel qualified to be a reviewer.

**Comment by smithfarm** [comment]
@tchaikov Note that the `ceph-backport.sh` script does automatically add labels to backport PRs, but often the folks using the script do not have sufficient permissions on github, so in many cases I found it simpler to add the labels manually. I gather you were doing the same, and that's what motivated you to come up with this automation.

Speaking of "nice-to-have" click-saving features, how about a labeler that automatically adds "needs-qa" and "nautilus-batch-1" when all mandatory checks have passed, and automatically removes them when they fail?

**Comment by tchaikov** [comment]
> I gather you were doing the same, and that's what motivated you to come up with this automation.

that's not true. i think i understand what motivated me.

> Speaking of "nice-to-have" click-saving features, how about a labeler that automatically adds "needs-qa" and "nautilus-batch-1" when all mandatory checks have passed, and automatically removes them when they fail?

i have no idea how to accomplish this. since it's not necessary. i will close it. thanks for your time.

**Comment by smithfarm** [comment]
> > I gather you were doing the same, and that's what motivated you to come up with this automation.
> 
> that's not true. i think i understand what motivated me.

Apparently I phrased my thought wrong? By "come up with this automation" I didn't mean your motivation for creating this PR, I meant the work you and others put into developing this labeler tool in master.

What other motivation could there have been for that than to avoid the manual work of applying labels?

To summarize, I don't understand why you closed the PR. True, I declined to review it (for the reason stated), but surely there are others who would be willing and able to review it?

**Pull request closed without merging**
