### PR TITLE
quincy: Cephadm Batch Backport April

### PR DESCRIPTION
**Pull request by adk3798**
Backport of #44810 #44779 #44997 #45054 #44905 #44896 #44928 #45023 #45132 #45113 #45136 #44923 #45202 #45174 #45039 #45281 #45310 #45362  #45286 #45527 #45401 #45399 #45314 #45241 #45702 #45534 #45275 #45217 #45344 #45349 #45710 #45735 #45685 #45589 #45070 #45768 #45796 #45851 #45765 #45860 #45982 #45931 #45920 #45899 #45877 #45855 #44751 #44895 #44343 #45692 #45248 #45597 #45056 #43796 #45863

Conflicts:
- debian/control
- src/cephadm/cephadm
- src/pybind/mgr/cephadm/module.py

Changelog: Dropped #45333, #44965, #45420, #45347 as the actually had individual backports open elsewhere (that got merged)

Changelog: Fixed failing grafana service unit tests due to #45333 and #44751 going into quincy in opposite order to how they went in master

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by adk3798** [comment]
okay, pretty sure we need https://github.com/ceph/ceph/pull/46065 before this for the natsort stuff. Putting this on hold until that gets in.

**Comment by guits** [comment]
jenkins test ceph-volume tox

**Comment by adk3798** [comment]
https://github.com/ceph/ceph/pull/46065 is merged so we can start testing this again

**Comment by adk3798** [comment]
jenkins test api

**Comment by jozefrebjak** [comment]
@adk3798 I'm looking for https://github.com/ceph/ceph/pull/45735, because with non-root user is Quincy not usable for us. Will be this available in new version of Quincy ? And when to expect the release ? We would like to upgrade from latest Pacific to Quincy. Thank you.

**Comment by adk3798** [comment]
> @adk3798 I'm looking for #45735, because with non-root user is Quincy not usable for us. Will be this available in new version of Quincy ? And when to expect the release ? We would like to upgrade from latest Pacific to Quincy. Thank you.

#45735 is included in this batch already. My guess is this will very likely make it into 17.2.1, although I don't think a release date for that has been planned yet.

**Comment by adk3798** [comment]
jenkins test api

**Comment by adk3798** [comment]
another orch run
https://pulpito.ceph.com/adking-2022-05-04_15:26:28-orch:cephadm-wip-adk3-testing-2022-05-04-0911-distro-basic-smithi/

and rados/cephadm
https://pulpito.ceph.com/adking-2022-05-04_15:33:19-rados:cephadm-wip-adk3-testing-2022-05-04-0911-distro-basic-smithi/

Both green

**Comment by adk3798** [comment]
jenkins test ceph-volume all

**Comment by guits** [comment]
jenkins test ceph-volume tox

**Review by mgfritch — APPROVED** [review]

**Pull request merged**
