### PR TITLE
[DNM] kraken: librbd: relax "is parent mirrored" check when enabling mirroring for pool

### PR DESCRIPTION
**Pull request by trociny**
http://tracker.ceph.com/issues/18555
http://tracker.ceph.com/issues/19227

### CODE REVIEW

**Comment by trociny** [comment]
This PR is also includes #14576

@smithfarm Could you please include this to your test branch?

**Comment by smithfarm** [comment]
@trociny So, if I understand correctly, this replaces both #14576 and #14535

**Comment by trociny** [comment]
@smithfarm
> So, if I understand correctly, this replaces both #14576 and #14535 

Yes

**Comment by smithfarm** [comment]
@trociny There is another backport that depends on commits being backported in this PR. Could you please do the following?

* cherry pick 8f72e74 into this PR
* add http://tracker.ceph.com/issues/19808 to the PR description here
* edit description of http://tracker.ceph.com/issues/19808 so it points to this PR
* close #15462 

Thanks!!

**Comment by smithfarm** [comment]
Jenkins re-test this please

**Comment by smithfarm** [comment]
@trociny The make check failure has hopefully been fixed by #16069 - could you please rebase to pick it up?

**Comment by trociny** [comment]
@smithfarm I thought rebase is not necessary in such a case because Jenkins would always merge this to the latest branch?

**Comment by smithfarm** [comment]
@trociny OK, I wasn't aware of that. Let's try it: Jenkins re-test this please

**Comment by smithfarm** [comment]
@trociny Thanks for the tip; opened #16079 to add it to developer guide.

**Comment by smithfarm** [comment]
Replaced (for now) by #16113 - sorry, @trociny, I needed to add a fix urgently and it needed to be cherry-picked onto this PR. If you bring it into this PR, I'll close mine?

**Comment by trociny** [comment]
@smithfarm I am fine with  #16113. Let me know if I can close this PR (or please close yourself).

**Pull request closed without merging**
