### PR TITLE
qa/tests: removed luminous-x suite

### PR DESCRIPTION
**Pull request by yuriw**
Signed-off-by: Yuri Weinstein <yweinste@redhat.com>

- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by liewegas** [comment]
No, we need to test upgardes from luminous -> nautilus!  We can remove from master after nautilus is released.

**Comment by yuriw** [comment]
@liewegas we have luminous-s on mimic branch, so we can run luminous -> nautilus from there, why do we need it here ?

**Comment by liewegas** [comment]
because nautilus branch won't branch off from master for another ~3  months.. we can't remove this until then or else it won't exist in the nautilus branch.

**Comment by yuriw** [comment]
I maybe missing something, but why do we need it in the nautilus branch as oppose to use `--suite-branch` and call it from its "legit" location in the mimic branch ?

**Comment by yuriw** [comment]
unless for convince ...

**Comment by liewegas** [comment]
The luminous->natuilus upgrade will likely be a bit different than luminous->mimic.  There's no reason mimic should be involved at all in a l->n upgrade.

**Comment by smithfarm** [comment]
I agree with @liewegas

**Pull request closed without merging**
