### PR TITLE
squid: cephadm: pull container images from quay.io

### PR DESCRIPTION
**Pull request by guits**
backport tracker: https://tracker.ceph.com/issues/68556

---

backport of https://github.com/ceph/ceph/pull/60060
parent tracker: https://tracker.ceph.com/issues/68323

this backport was staged using ceph-backport.sh version 16.0.0.6848
find the latest version at https://github.com/ceph/ceph/blob/main/src/script/ceph-backport.sh

### CODE REVIEW

**Comment by adk3798** [comment]
jenkins test make check

**Comment by adk3798** [comment]
jenkins test api

**Review by adk3798 — APPROVED** [review]

**Comment by guits** [comment]
jenkins test make check

**Comment by guits** [comment]
jenkins test make check

**Comment by guits** [comment]
jenkins test api

**Comment by guits** [comment]
jenkins test make check

**Comment by guits** [comment]
https://pulpito.ceph.com/gabrioux-2024-10-22_20:36:30-orch:cephadm-wip-guits-squid-2024-10-22-1533-squid-distro-default-smithi/

**Comment by guits** [comment]
jenkins test dashboard cephadm e2e

**Comment by guits** [comment]
jenkins test dashboard cephadm

**Comment by guits** [comment]
jenkins test rook e2e

**Comment by guits** [comment]
jenkins test dashboard

**Comment by guits** [comment]
jenkins test dashboard cephadm

**Comment by guits** [comment]
jenkins test rook e2e

**Comment by guits** [comment]
jenkins test dashboard

**Pull request merged**
