### PR TITLE
After the abnormal shutdown, the OSD_SUPERBLOCK and OSD_MAP data of several nodes were corrupted, The next time cluster is power on, caused by the OSD_SUPERBLOCK and OSD_MAP's CRC verification failure, Data corruption occurred due to failure to power on OSD in multiple nodes,and more serious is the loss of data.

### PR DESCRIPTION
**Pull request by Stellar-Wang**
## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by Stellar-Wang** [comment]
@tchaikov @neha-ojha

**Review by murolo — COMMENTED** [review]
Why delete the last update

**Comment by datatom-infinity** [comment]
We have the same problem....

**Comment by murolo** [comment]
could you describe the problem scenario in detail?

**Comment by Stellar-Wang** [comment]
@murolo 
1. The node is down abnormally, current epoch 122, and OSD sends message MSG_OSD_MARK_ME_DOWN to Monitor.
2. OSD started to update epoch 123 for incremental osdmap and osdmap, osd_superblock, then aync commit to store transactions.
3. Monitor responded MSG_OSD_Mark_Me_Down ACK, and then processed OSD_SuperBlock,epoch 123.
4. OSD_SUPERBLOCK CRC check failed after being powered on again, OSD startup failed. log detail as follow: 
2021-01-12 13:13:35.500745 7f34ee3a8d00 -1 bluestore(/var/lib/ceph/osd/ceph-0) _verify_csum bad crc32c/0x1000 checksum at blob offset 0x0, got 0x10b29157, expected 0x1791e9d4, device location [0x10000~1000], logical extent 0x0~1000, object #-1:7b3f43c4:::osd_superblock:0#
2021-01-12 13:13:35.500777 7f34ee3a8d00 -1 osd.0 0 OSD::init() : unable to read osd superblock

**Comment by murolo** [comment]
> 
> 
> @murolo
> 
>     1. The node is down abnormally, current epoch 122, and OSD sends message MSG_OSD_MARK_ME_DOWN to Monitor.
> 
>     2. OSD started to update epoch 123 for incremental osdmap and osdmap, osd_superblock, then aync commit to store transactions.
> 
>     3. Monitor responded MSG_OSD_Mark_Me_Down ACK, and then processed OSD_SuperBlock,epoch 123.
> 
>     4. OSD_SUPERBLOCK CRC check failed after being powered on again, OSD startup failed. log detail as follow:
>        2021-01-12 13:13:35.500745 7f34ee3a8d00 -1 bluestore(/var/lib/ceph/osd/ceph-0) _verify_csum bad crc32c/0x1000 checksum at blob offset 0x0, got 0x10b29157, expected 0x1791e9d4, device location [0x10000~1000], logical extent 0x0~1000, object #-1:7b3f43c4:::osd_superblock:0#
>        2021-01-12 13:13:35.500777 7f34ee3a8d00 -1 osd.0 0 OSD::init() : unable to read osd superblock

@Stellar-Wang Have you checked the data and metadata? If the data is wrong, the disk may be corrupted

**Comment by Stellar-Wang** [comment]
@murolo 

> @Stellar-Wang Have you checked the data and metadata? If the data is wrong, the disk may be corrupted
 When the CRC check is ignored, the OSD_SUPERBLOCK can be read and decoded to obtain the epoch as 122.

**Comment by murolo** [comment]
> 
> 
> @murolo
> 
> > @Stellar-Wang Have you checked the data and metadata? If the data is wrong, the disk may be corrupted
> > When the CRC check is ignored, the OSD_SUPERBLOCK can be read and decoded to obtain the epoch as 122.

@Stellar-Wang  
as i know,osd will commit two transactions,to make sure update the latest osdmap and osd-superblock when shutdown normally（like:systemctl stop osd.service）,if abnormal shutdown
the transactions the transactions should roll back or replay. I have two questions about this 
1、the wrong OSD_SUPERBLOCK data is 122 epoch,but kv meta crc is no match?
According to the process the actual expected value is 123 ?  
2、What is the value osdmap epoch？

**Comment by Stellar-Wang** [comment]
@murolo 
hey!
crc errors occurred on four disks in different nodes.
<osd power on failure reason>:
1 :  osd.0,osd.8 :  OSD_SUPERBLOCK CRC check failed,kv meta CRC is correspond with epoch 123,data decode epoch is 122.
2 : osd.15      :  osdmap CRC check failed, expected osdmap epoch is 123，kv can get osdmap.123's key,but when check crc, the data   osd_map.123 is corrupted.
  
Answer 1:
Yes, meta CRC is not match, from the ceph-osd.0.log of power down,some" shutdown logprint "are missing.
Answer 2:
According to the tool ceph-objectstore-tool, the OSD map contain the latest 123 object in kv.
by the way ,The operation is, the cluster is restarted (systemctl stop ceph.target)

**Comment by murolo** [comment]
> 
> 
> @murolo
> hey!
> crc errors occurred on four disks in different nodes.
> :
> 1 : osd.0,osd.8 : OSD_SUPERBLOCK CRC check failed,kv meta CRC is correspond with epoch 123,data decode epoch is 122.
> 2 : osd.15 : osdmap CRC check failed, expected osdmap epoch is 123，kv can get osdmap.123's key,but when check crc, the data osd_map.123 is corrupted.
> 
> Answer 1:
> Yes, meta CRC is not match, from the ceph-osd.0.log of power down,some" shutdown logprint "are missing.
> Answer 2:
> According to the tool ceph-objectstore-tool, the OSD map contain the latest 123 object in kv.
> by the way ,The operation is, the cluster is restarted (systemctl stop ceph.target)



Just make sure I understand：

problem occurs in cluster restart,and 4 osds is not booting,cause the crc chech errors you mentioned.

osd.0,osd.8 : OSD_SUPERBLOCK  is 122,and  not update,but kv object crc is corresponding to123?
osd.15: the latest osdmap.123 is in kv,but the data is corrupted. (the osdmap.122 121...decode ok? )

kv WAL file replay ok? how does you make sure this?
as i know when osd booted again,osd will replay the wal,  it will refresh defer kv record to bluestore,OSD_SUPERBLOCK /osdmap  data rewrite will be executed if the defer exist,If there are no error with the rocksdb wal file, there should be no inconsistencies

**Comment by murolo** [comment]
from the PR , your solution is to choose not to update the last time osdmap and osd-superblock?

**Comment by murolo** [comment]
https://tracker.ceph.com/issues/25006
https://tracker.ceph.com/issues/48025 
https://tracker.ceph.com/issues/48855

@tchaikov @neha-ojha

**Comment by Stellar-Wang** [comment]
@murolo 
Yes，All is ok, the osdmap.122 121 decode is ok.
kv WAL replay is right exactly on power on，ceph-osd.0.log display as below:
rocksdb: EVENT_LOG_v1 {"time_micros": 1610428402070192, "job": 1, "event": "recovery_started", "log_files": [202008, 202014]}
rocksdb: EVENT_LOG_v1 {"time_micros": 1610428403965494, "job": 1, "event": "recovery_finished"}

so kv wal no any exception occurs on power on.

**Comment by tchaikov** [comment]
@Stellar-Wang will take a look this week.

**Comment by tchaikov** [comment]
@Stellar-Wang i am not sure if to skip updating `mounted` and `clean_thru` unconditionally is the right solution to address the issue. CRC mismatch could be the sequence of multiple causes. among the other things, disk failure, a bug in ceph, or even filesystem corruption. avoid avoid writing to superblock does not **fix** any of these issues.

**Pull request closed without merging**
