### PR TITLE
osd: only allocate or write snapset when we need to

### PR DESCRIPTION
**Pull request by liewegas**

### CODE REVIEW

**Comment by liewegas** [comment]
@yuyuyu101 how significant was this in your profiling?  we are worried that this route is complex and error-prone... mainly because we have to explicitly handle the cases where the object gets deleted and recreated and the attr has to be rewritten even tho there is no change...

**Comment by yuyuyu101** [comment]
image

Some notes:
1. Test program running under "-g -O0", in product env, the difference should be less. I think the experience difference is 5us per call.
2. The reduced consuming time mainly is ObjectStore::setattr call(10us) and FileStore::setattr call(13us).

**Comment by athanatos** [comment]
This no longer merges cleanly.

@yuyuyu101: are you able to access the sepia lab yet?  I'm trying to run fewer tests myself, it would be good if you could kick off and analyze a rados suite run (--subset 1/13).  You should link the pulpito results here once you are happy with the run.  #sepia can help with any questions.

**Comment by yuyuyu101** [comment]
@athanatos I'm not following the meaning.

Do you mean to test the correctness of this patch or performance in sepia lab?

**Comment by athanatos** [comment]
Correctness.

**Comment by yuyuyu101** [comment]
@liewegas need rebase :-)

**Comment by liewegas** [comment]
almost a year old now. closing this.  i still think it may be worthwhile at some point, but it'l lneed some work

**Comment by XinzeChi** [comment]
@liewegas , I will continue this work. Any suggestion would be appreciated!

**Comment by liewegas** [comment]
@XinzeChi We dropped this the first time around because it was judged to be complex and difficult to maintain correctness.  I think in order to make this viable we need to find a way to construct the interfaces so that it is difficult to introduce bugs.  It might make sense to wait for @athanatos's current refactor of the write path to do that...

**Pull request closed without merging**
