### PR TITLE
pacific: revert bootstrap network handling changes

### PR DESCRIPTION
**Pull request by adk3798**
Revert the backports of master PRs https://github.com/ceph/ceph/pull/45768 and https://github.com/ceph/ceph/pull/45710 which were backported to pacific in https://github.com/ceph/ceph/pull/45919.

This was causing failures in the way we set the mon public network

http://pulpito.front.sepia.ceph.com/yuriw-2022-04-27_02:52:22-rados-pacific-distro-default-smithi/6807870
http://pulpito.front.sepia.ceph.com/yuriw-2022-04-27_02:52:22-rados-pacific-distro-default-smithi/6807874

Adding an extraneous IP in the same subnet to the public network we resolve, which can't be handled by some versions of docker it seems. Either way, we shouldn't be adding the extra IP I think.

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/master/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [x] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [x] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Review by ljflores — APPROVED** [review]

**Comment by ljflores** [comment]
jenkins test api

**Comment by idryomov** [comment]
Edited the description to include original master and backport PR links.

**Comment by adk3798** [comment]
https://pulpito.ceph.com/adking-2022-04-29_12:06:52-rados:cephadm-wip-adk3-testing-2022-04-28-2054-pacific-distro-basic-smithi/

**Comment by adk3798** [comment]
> @adk3798 Is there a tracker ticket for this revert?

eh, no. Sort of opened this in a hurry so it could get tested quickly and make sure it actually fixed the issue. Still need to make one.

**Comment by adk3798** [comment]
> > @adk3798 Is there a tracker ticket for this revert?
> 
> eh, no. Sort of opened this in a hurry so it could get tested quickly and make sure it actually fixed the issue. Still need to make one.

well, I guess there is this one https://tracker.ceph.com/issues/55492 for tracking the issue itself.

**Comment by idryomov** [comment]
> well, I guess there is this one https://tracker.ceph.com/issues/55492 for tracking the issue itself.

I went ahead and marked it as a regression, linking to https://tracker.ceph.com/issues/55132.

**Pull request merged**
