### PR TITLE
pacific: osd/scrub: expose PGs scrubbing info to the operator

### PR DESCRIPTION
**Pull request by ronen-fr**
Adding the scrub duration, scrub scheduling status and (by necessity - see below)
number-of-objects-scrubbed to the pg_dump (and query) outputs). 

Backport of https://github.com/ceph/ceph/pull/43403 and
https://github.com/ceph/ceph/pull/42977 with follow-up fixes in
https://github.com/ceph/ceph/pull/45599

The pg_stat_t version is set to 27 (Q will be released with 28)
   
    pg_stat_t versions (past and future):
    |------------------------+--------+--------+----------+---------++-------------
    | version                | master | quincy | Pacific  | pacific ||   pacific
    |                        |        |        |    RC1   |  as is  || after patch
    |------------------------+--------+--------+----------+---------++-------------
    | encode:                |   28   |   28   |     27   |   26    ||     27
    | decode:                |   28   |   28   |     26   |   26    ||     27
    |                        |        |        |          |         ||
    | avail_no_missing       |   26   |   26   |     26   |   26    ||     26
    | object_location_counts |   26   |   26   |     26   |   26    ||     26
    | last_scrub_duration    |   27   |   27   |     27   |         ||     27
    | scrub_sched_status     |        |        |          |         ||
    | > m_scheduled_at       |   27   |   27   |     27   |         ||     27
    | > m_duration_seconds   |   27   |   27   |     27   |         ||     27
    | > m_sched_status       |   27   |   27   |     27   |         ||     27
    | > m_is_active          |   27   |   27   |     27   |         ||     27
    | > m_is_deep            |   27   |   27   |     27   |         ||     27
    | > m_is_periodic        |   27   |   27   |     27   |         ||     27
    | objects_scrubbed       |   27   |   27   |      X   |         ||     27
    | scrub_duration         |   28   |   28   |          |         ||    XXXX
    | objects_trimmed        |   28   |   28   |          |         ||
    | snaptrim_duration      |   28   |   28   |          |         ||

Fixes: https://tracker.ceph.com/issues/52609
Co-Authored-By: Aishwarya Mathuria [amathuri@redhat.com](mailto:amathuri@redhat.com)

### CODE REVIEW

**Comment by ronen-fr** [comment]
Note @neha-ojha & @amathuria : here are the full list of three options re the pg_stat_t content in Pacific, of which I chose (in this PR) the first:

<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
<head>

<meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>&lrm;</title>
<meta name="generator" content="Org mode" />
<meta name="author" content="rfriedma" />
<style type="text/css">
 <![CDATA[/*>
</style>
<script type="text/javascript">
// @license magnet:?xt=urn:btih:e95b018ef3580986a04669f1b5879592219e2a7a&dn=public-domain.txt Public Domain
<![CDATA[/*>
// @license-end
</script>
</head>
<body>
<div id="content">
<table border="2" cellspacing="0" cellpadding="6" rules="groups" frame="hsides">


<colgroup>
<col  class="org-left" />

<col  class="org-center" />

<col  class="org-center" />

<col  class="org-center" />

<col  class="org-center" />

<col  class="org-left" />

<col  class="org-center" />

<col  class="org-left" />

<col  class="org-center" />

<col  class="org-center" />

<col  class="org-left" />

<col  class="org-center" />
</colgroup>
<thead>
<tr>
<th scope="col" class="org-left">&#xa0;</th>
<th scope="col" class="org-center">&#xa0;</th>
<th scope="col" class="org-center">&#xa0;</th>
<th scope="col" class="org-center">&#xa0;</th>
<th scope="col" class="org-center">&#xa0;</th>
<th scope="col" class="org-left">&#xa0;</th>
<th scope="col" class="org-center">&#xa0;</th>
<th scope="col" class="org-left">&#xa0;</th>
<th scope="col" class="org-center">&#xa0;</th>
<th scope="col" class="org-center">&#xa0;</th>
<th scope="col" class="org-left">&#xa0;</th>
<th scope="col" class="org-center">&#xa0;</th>
</tr>

<tr>
<th scope="col" class="org-left">&#xa0;</th>
<th scope="col" class="org-center">&#xa0;</th>
<th scope="col" class="org-center">&#xa0;</th>
<th scope="col" class="org-center">&#xa0;</th>
<th scope="col" class="org-center">&#xa0;</th>
<th scope="col" class="org-left">&#xa0;</th>
<th scope="col" class="org-center">PR options</th>
<th scope="col" class="org-left">&#xa0;</th>
<th scope="col" class="org-center">&#xa0;</th>
<th scope="col" class="org-center">&#xa0;</th>
<th scope="col" class="org-left">&#xa0;</th>
<th scope="col" class="org-center">&#xa0;</th>
</tr>
</thead>
<tbody>
<tr>
<td class="org-left">&#xa0;</td>
<td class="org-center">&#xa0;</td>
<td class="org-center">&#xa0;</td>
<td class="org-center">&#xa0;</td>
<td class="org-center">&#xa0;</td>
<td class="org-left">&#xa0;</td>
<td class="org-center">selected</td>
<td class="org-left">&#xa0;</td>
<td class="org-center">&#xa0;</td>
<td class="org-center">&#xa0;</td>
<td class="org-left">&#xa0;</td>
<td class="org-center">&#xa0;</td>
</tr>

<tr>
<td class="org-left">&#xa0;</td>
<td class="org-center">&#xa0;</td>
<td class="org-center">&#xa0;</td>
<td class="org-center">&#xa0;</td>
<td class="org-center">&#xa0;</td>
<td class="org-left">&#xa0;</td>
<td class="org-center">option I</td>
<td class="org-left">&#xa0;</td>
<td class="org-center">option II</td>
<td class="org-center">&#xa0;</td>
<td class="org-left">&#xa0;</td>
<td class="org-center">option III</td>
</tr>

<tr>
<td class="org-left">&#xa0;</td>
<td class="org-center">&#xa0;</td>
<td class="org-center">&#xa0;</td>
<td class="org-center">&#xa0;</td>
<td class="org-center">&#xa0;</td>
<td class="org-left">&#xa0;</td>
<td class="org-center">&#xa0;</td>
<td class="org-left">&#xa0;</td>
<td class="org-center">&#xa0;</td>
<td class="org-center">&#xa0;</td>
<td class="org-left">&#xa0;</td>
<td class="org-center">&#xa0;</td>
</tr>
</tbody>
<tbody>
<tr>
<td class="org-left">master</td>
<td class="org-center">master</td>
<td class="org-center">quincy</td>
<td class="org-center">Pacific RC1</td>
<td class="org-center">pacific</td>
<td class="org-left">&#xa0;</td>
<td class="org-center">pacific</td>
<td class="org-left">&#xa0;</td>
<td class="org-center">modify quincy</td>
<td class="org-center">pacific</td>
<td class="org-left">&#xa0;</td>
<td class="org-center">pacific after patch</td>
</tr>

<tr>
<td class="org-left">&#xa0;</td>
<td class="org-center">&#xa0;</td>
<td class="org-center">&#xa0;</td>
<td class="org-center">&#xa0;</td>
<td class="org-center">as is</td>
<td class="org-left">&#xa0;</td>
<td class="org-center">after patch</td>
<td class="org-left">&#xa0;</td>
<td class="org-center">&#xa0;</td>
<td class="org-center">&#xa0;</td>
<td class="org-left">&#xa0;</td>
<td class="org-center">&#xa0;</td>
</tr>
</tbody>
<tbody>
<tr>
<td class="org-left">encode:</td>
<td class="org-center">28</td>
<td class="org-center">28</td>
<td class="org-center">27</td>
<td class="org-center">26</td>
<td class="org-left">&#xa0;</td>
<td class="org-center">27</td>
<td class="org-left">&#xa0;</td>
<td class="org-center">28</td>
<td class="org-center">28</td>
<td class="org-left">&#xa0;</td>
<td class="org-center">28</td>
</tr>

<tr>
<td class="org-left">decode:</td>
<td class="org-center">28</td>
<td class="org-center">28</td>
<td class="org-center">26</td>
<td class="org-center">26</td>
<td class="org-left">&#xa0;</td>
<td class="org-center">27</td>
<td class="org-left">&#xa0;</td>
<td class="org-center">28</td>
<td class="org-center">28</td>
<td class="org-left">&#xa0;</td>
<td class="org-center">28</td>
</tr>

<tr>
<td class="org-left">&#xa0;</td>
<td class="org-center">&#xa0;</td>
<td class="org-center">&#xa0;</td>
<td class="org-center">&#xa0;</td>
<td class="org-center">&#xa0;</td>
<td class="org-left">&#xa0;</td>
<td class="org-center">&#xa0;</td>
<td class="org-left">&#xa0;</td>
<td class="org-center">&#xa0;</td>
<td class="org-center">&#xa0;</td>
<td class="org-left">&#xa0;</td>
<td class="org-center">&#xa0;</td>
</tr>

<tr>
<td class="org-left">avail<sub>no</sub><sub>missing</sub></td>
<td class="org-center">26</td>
<td class="org-center">26</td>
<td class="org-center">26</td>
<td class="org-center">26</td>
<td class="org-left">&#xa0;</td>
<td class="org-center">26</td>
<td class="org-left">&#xa0;</td>
<td class="org-center">26</td>
<td class="org-center">26</td>
<td class="org-left">&#xa0;</td>
<td class="org-center">26</td>
</tr>

<tr>
<td class="org-left">object<sub>location</sub><sub>counts</sub></td>
<td class="org-center">26</td>
<td class="org-center">26</td>
<td class="org-center">26</td>
<td class="org-center">26</td>
<td class="org-left">&#xa0;</td>
<td class="org-center">26</td>
<td class="org-left">&#xa0;</td>
<td class="org-center">26</td>
<td class="org-center">26</td>
<td class="org-left">&#xa0;</td>
<td class="org-center">26</td>
</tr>

<tr>
<td class="org-left">last<sub>scrub</sub><sub>duration</sub></td>
<td class="org-center">27</td>
<td class="org-center">27</td>
<td class="org-center">27</td>
<td class="org-center">&#xa0;</td>
<td class="org-left">&#xa0;</td>
<td class="org-center">27</td>
<td class="org-left">&#xa0;</td>
<td class="org-center">27</td>
<td class="org-center">27</td>
<td class="org-left">&#xa0;</td>
<td class="org-center">27</td>
</tr>

<tr>
<td class="org-left">scrub<sub>sched</sub><sub>status</sub></td>
<td class="org-center">&#xa0;</td>
<td class="org-center">&#xa0;</td>
<td class="org-center">&#xa0;</td>
<td class="org-center">&#xa0;</td>
<td class="org-left">&#xa0;</td>
<td class="org-center">&#xa0;</td>
<td class="org-left">&#xa0;</td>
<td class="org-center">&#xa0;</td>
<td class="org-center">&#xa0;</td>
<td class="org-left">&#xa0;</td>
<td class="org-center">&#xa0;</td>
</tr>

<tr>
<td class="org-left">&gt; m<sub>scheduled</sub><sub>at</sub></td>
<td class="org-center">27</td>
<td class="org-center">27</td>
<td class="org-center">27</td>
<td class="org-center">&#xa0;</td>
<td class="org-left">&#xa0;</td>
<td class="org-center">27</td>
<td class="org-left">&#xa0;</td>
<td class="org-center">27</td>
<td class="org-center">27</td>
<td class="org-left">&#xa0;</td>
<td class="org-center">27</td>
</tr>

<tr>
<td class="org-left">&gt; m<sub>duration</sub><sub>seconds</sub></td>
<td class="org-center">27</td>
<td class="org-center">27</td>
<td class="org-center">27</td>
<td class="org-center">&#xa0;</td>
<td class="org-left">&#xa0;</td>
<td class="org-center">27</td>
<td class="org-left">&#xa0;</td>
<td class="org-center">27</td>
<td class="org-center">27</td>
<td class="org-left">&#xa0;</td>
<td class="org-center">27</td>
</tr>

<tr>
<td class="org-left">&gt; m<sub>sched</sub><sub>status</sub></td>
<td class="org-center">27</td>
<td class="org-center">27</td>
<td class="org-center">27</td>
<td class="org-center">&#xa0;</td>
<td class="org-left">&#xa0;</td>
<td class="org-center">27</td>
<td class="org-left">&#xa0;</td>
<td class="org-center">27</td>
<td class="org-center">27</td>
<td class="org-left">&#xa0;</td>
<td class="org-center">27</td>
</tr>

<tr>
<td class="org-left">&gt; m<sub>is</sub><sub>active</sub></td>
<td class="org-center">27</td>
<td class="org-center">27</td>
<td class="org-center">27</td>
<td class="org-center">&#xa0;</td>
<td class="org-left">&#xa0;</td>
<td class="org-center">27</td>
<td class="org-left">&#xa0;</td>
<td class="org-center">27</td>
<td class="org-center">27</td>
<td class="org-left">&#xa0;</td>
<td class="org-center">27</td>
</tr>

<tr>
<td class="org-left">&gt; m<sub>is</sub><sub>deep</sub></td>
<td class="org-center">27</td>
<td class="org-center">27</td>
<td class="org-center">27</td>
<td class="org-center">&#xa0;</td>
<td class="org-left">&#xa0;</td>
<td class="org-center">27</td>
<td class="org-left">&#xa0;</td>
<td class="org-center">27</td>
<td class="org-center">27</td>
<td class="org-left">&#xa0;</td>
<td class="org-center">27</td>
</tr>

<tr>
<td class="org-left">&gt; m<sub>is</sub><sub>periodic</sub></td>
<td class="org-center">27</td>
<td class="org-center">27</td>
<td class="org-center">27</td>
<td class="org-center">&#xa0;</td>
<td class="org-left">&#xa0;</td>
<td class="org-center">27</td>
<td class="org-left">&#xa0;</td>
<td class="org-center">27</td>
<td class="org-center">27</td>
<td class="org-left">&#xa0;</td>
<td class="org-center">27</td>
</tr>

<tr>
<td class="org-left">objects<sub>scrubbed</sub></td>
<td class="org-center">27</td>
<td class="org-center">27</td>
<td class="org-center">X</td>
<td class="org-center">&#xa0;</td>
<td class="org-left">&#xa0;</td>
<td class="org-center">27</td>
<td class="org-left">&#xa0;</td>
<td class="org-center">27</td>
<td class="org-center">27</td>
<td class="org-left">&#xa0;</td>
<td class="org-center">27</td>
</tr>

<tr>
<td class="org-left">scrub<sub>duration</sub></td>
<td class="org-center">28</td>
<td class="org-center">28</td>
<td class="org-center">&#xa0;</td>
<td class="org-center">&#xa0;</td>
<td class="org-left">&#xa0;</td>
<td class="org-center">XXXX</td>
<td class="org-left">&#xa0;</td>
<td class="org-center">28</td>
<td class="org-center">28</td>
<td class="org-left">&#xa0;</td>
<td class="org-center">28</td>
</tr>

<tr>
<td class="org-left">objects<sub>trimmed</sub></td>
<td class="org-center">28</td>
<td class="org-center">28</td>
<td class="org-center">&#xa0;</td>
<td class="org-center">&#xa0;</td>
<td class="org-left">&#xa0;</td>
<td class="org-center">&#xa0;</td>
<td class="org-left">&#xa0;</td>
<td class="org-center">29</td>
<td class="org-center">&#xa0;</td>
<td class="org-left">&#xa0;</td>
<td class="org-center">28 - but no data</td>
</tr>

<tr>
<td class="org-left">snaptrim<sub>duration</sub></td>
<td class="org-center">28</td>
<td class="org-center">28</td>
<td class="org-center">&#xa0;</td>
<td class="org-center">&#xa0;</td>
<td class="org-left">&#xa0;</td>
<td class="org-center">&#xa0;</td>
<td class="org-left">&#xa0;</td>
<td class="org-center">29</td>
<td class="org-center">&#xa0;</td>
<td class="org-left">&#xa0;</td>
<td class="org-center">28 - but no data</td>
</tr>
</tbody>
</table>
</div>
<div id="postamble" class="status">
<p class="author">Author: rfriedma</p>
<p class="date">Created: 2022-04-19 Tue 13:07</p>
<p class="validation"><a href="https://validator.w3.org/check?uri=referer">Validate</a></p>
</div>
</body>
</html>

**Comment by ronen-fr** [comment]
http://pulpito.front.sepia.ceph.com/?branch=wip-rf-42977pl-pacific

**Review by neha-ojha — CHANGES_REQUESTED** [review]
@ronen-fr @amathuria I don't think we should be backporting features, especially those with encoding changes. The tracker was never marked for backport and I don't see anybody requesting this feature in Pacific. Is there any other reason for us to backport this else I'd be inclined to close this PR and resolve the parent ticket.

**Comment by ronen-fr** [comment]
@neha-ojha wrote:
> @ronen-fr @amathuria I don't think we should be backporting features, especially those with encoding changes. The tracker was never marked for backport and I don't see anybody requesting this feature in Pacific. Is there any other reason for us to backport this else I'd be inclined to close this PR and resolve the parent ticket.

I am OK with both options. But just to make sure we have the full picture:
- we have discussed this in emails on Sep. 2021, and it seemed reasonable to backport. @amathuria has created a tracker for that (https://tracker.ceph.com/issues/52605)
- @cfsnyder has created his own partial backport, which was marked DNM and is superseded by the current PR;

Anyway - like I said, I'm OK with dropping this backport.

**Comment by ronen-fr** [comment]
Note that if not merging this PR, we should verify that pg_stats_t versions in final Pacific, final Q and master
make sense.

**Comment by ronen-fr** [comment]
@neha-ojha - I plan to close this PR now.

**Pull request closed without merging**
