### PR TITLE
qa/suites/crimson-rados/thrash: enable chance_down

### PR DESCRIPTION
**Pull request by Matan-B**
```
As the thrash tests were introduced, some options were disabled
until the tests are stabilized.

Re-enable chance_down option (default is 0.4) to detect bugs on restart.

Since it will probably take few iterations before thrash and recovery tests ('default.yaml')
will pass successfully, add anoter 'simple.yaml' which should remain stable.

Fixes: https://tracker.ceph.com/issues/65130
```

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [x] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [x] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Comment by Matan-B** [comment]
Testing with https://github.com/ceph/ceph/pull/56376 to verify that we catch the error now.

**Comment by Matan-B** [comment]
We have other issues that involve restarting that require handling before merging, tested this PR on main as well:
https://pulpito.ceph.com/matan-2024-03-27_13:02:57-crimson-rados-main-distro-crimson-smithi/

**Comment by athanatos** [comment]
@Matan-B Ah, that makes sense.  If you have time, it would be helpful to do a first pass of that run and file bugs for the defects.  We can split up the work on fixing them.

**Comment by Matan-B** [comment]
> @Matan-B Ah, that makes sense. If you have time, it would be helpful to do a first pass of that run and file bugs for the defects. We can split up the work on fixing them.

@athanatos,

https://tracker.ceph.com/issues/65203
https://tracker.ceph.com/issues/65201
https://tracker.ceph.com/issues/65200

**Comment by Matan-B** [comment]
> https://tracker.ceph.com/issues/65203
https://tracker.ceph.com/issues/65201
https://tracker.ceph.com/issues/65200

Should be addressed by https://github.com/ceph/ceph/pull/56611 and https://github.com/ceph/ceph/pull/56610, testing

**Comment by Matan-B** [comment]
@athanatos, the previous trackers seem to be ok, new one popped out:

https://tracker.ceph.com/issues/65247

**Comment by Matan-B** [comment]
Updating relevant PRs:
https://github.com/ceph/ceph/pull/56611
https://github.com/ceph/ceph/pull/56610
https://github.com/ceph/ceph/pull/56832
https://github.com/ceph/ceph/pull/56806

CC: @xxhdx1985126, @athanatos

**Review by athanatos — APPROVED** [review]

**Comment by Matan-B** [comment]
I'll merge this based on:
https://pulpito.ceph.com/matan-2024-04-16_14:35:17-crimson-rados-main-distro-crimson-smithi/

@xuxuehan, we can start to test+merge the 'crimson-replicated-recovery' PRs based on the non-recovery thrash tests (as we did before) until both are stable.

**Comment by Matan-B** [comment]
jenkins test api

**Comment by athanatos** [comment]
jenkins test api

**Review by xxhdx1985126 — APPROVED** [review]

**Pull request merged**
