### PR TITLE
dev/developer_guide: add jaegertracing intial developer documentation

### PR DESCRIPTION
**Pull request by ideepika**
Signed-off-by: Deepika Upadhyay <dupadhya@redhat.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by neha-ojha** [comment]
jenkins retest this please

**Comment by zdover23** [comment]
@ideepika: I'll fix this up and send you a revision that builds. Stand by. (If everything goes well, it'll be done during your Thursday.)

**Comment by ideepika** [comment]
@zdover23 great help! I updated somewhat, wanted to update so that you fix the updated version or don't have to do redundant job

**Comment by zdover23** [comment]
Here's a commit that fixes the formatting so that the docs build:

https://github.com/zdover23/ceph/tree/jaegertracing-fix

You also need to add the "Signed-off By" line to the commit, which is described (sort of) here:

https://docs.ceph.com/en/latest/start/documenting-ceph/#commit-the-change

(I know this document is a little confusing. Our Google Season of Docs project this year includes rewriting this so that it's easy to read. If you're not sure what I'm asking for in this context, let me know and I'll write a procedure out for you.)

**Comment by zdover23** [comment]
@ideepika 

"git commit -s" will work only if you've already followed the configuration steps in this section:

https://docs.ceph.com/en/latest/dev/developer_guide/basic-workflow/#configuring-your-local-environment

Specifically, it's these two commands that you have to run:

git config user.name "FIRST_NAME LAST_NAME"
git config user.email "MY_NAME@example.com"

**Comment by zdover23** [comment]
jenkins render docs

**Review by zdover23 — APPROVED** [review]
LGTM.

**Pull request merged**
