### PR TITLE
crimson/.../lba_btree_node_impl: handle relative addr in merge

### PR DESCRIPTION
**Pull request by athanatos**
<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Review by liu-chunmei — APPROVED** [review]

**Comment by athanatos** [comment]
@liu-chunmei Btw, this might explain the crash you saw, not sure.

**Comment by liu-chunmei** [comment]
> @liu-chunmei Btw, this might explain the crash you saw, not sure.

I will try it.

**Comment by liu-chunmei** [comment]
> @liu-chunmei Btw, this might explain the crash you saw, not sure.

still has the problem.

**Comment by athanatos** [comment]
Note hugely surprising, let me know if you find anything.

**Pull request merged**
