### PR TITLE
common: default pg_autoscale_mode=on for new pools  …

### PR DESCRIPTION
**Pull request by dzafman**
Tests to fix
- [X] scrub/osd-recovery-scrub.sh
- [ ] scrub/osd-unexpected-clone.sh https://tracker.ceph.com/issues/41913
- [X] scrub/osd-scrub-snaps.sh
- [X] scrub/osd-scrub-test.sh 
- [ ] scrub/osd-scrub-repair.sh   https://tracker.ceph.com/issues/41923
- [X] mon/mon-osdmap-prune.sh
- [x] erasure-code/test-erasure-eio.sh duplicate with existing trackers
- [ ] erasure-code/test-erasure-code.sh
- [ ] osd/divergent-priors.sh https://tracker.ceph.com/issues/41816
- [x] osd/osd-backfill-prio.sh
- [ ] osd/osd-rep-recov-eio.sh https://tracker.ceph.com/issues/41939
- [ ] osd/osd-backfill-space.sh
- [ ] osd/osd-recovery-space.sh
- [ ] osd/pg-split-merge.sh
- [ ] osd/osd-recovery-stats.sh
- [ ] osd/osd-backfill-stats.sh
- [ ] osd/osd-recovery-prio.sh

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`

</details>

### CODE REVIEW

**Comment by dzafman** [comment]
@liewegas @neha-ojha @jdurgin In the end we might end up turning auto-scaler off in ceph-helpers.sh instead of individual tests, but it would be nice to use this opportunity to fix any crashes that are discovered.  Crashes that involve corruption testing would NOT apply.

Should we have a basic unit test for auto scaling?  I don't see one.

**Comment by liewegas** [comment]
> @liewegas @neha-ojha @jdurgin In the end we might end up turning auto-scaler off in ceph-helpers.sh instead of individual tests, but it would be nice to use this opportunity to fix any crashes that are discovered. Crashes that involve corruption testing would NOT apply.

I was just going to do the setting across teh board, but this is better.  First, though, I'm chasing down the failures I'm seeing.. specifically https://tracker.ceph.com/issues/41816#note-5 and also I'm hitting https://tracker.ceph.com/issues/40684
 
> Should we have a basic unit test for auto scaling? I don't see one.

Yes.. adding this to my todo

**Comment by liewegas** [comment]
> > Should we have a basic unit test for auto scaling? I don't see one.
> 
> Yes.. adding this to my todo

actually we do have one, see ../qa/workunits/mon/pg_autoscaler.sh

**Comment by dzafman** [comment]
See #30475

**Pull request closed without merging**
