### PR TITLE
qa: enable position-independent suite copies without breaking links to top-level qa dir

### PR DESCRIPTION
**Pull request by batrick**
This utilizes the recent feature in teuthology [1] to skip hidden files in
    suites when building the job matrix.
    
    Idea of this change is to enable referring to the top-level qa directory in a
    position-independent way such that copies of a suite to another location do not
    break any symlinks.
    
    [1] https://github.com/ceph/teuthology/pull/1185

### CODE REVIEW

**Comment by batrick** [comment]
cephfs run: http://pulpito.ceph.com/?branch=wip-pdonnell-testing-20180626.223928

**Comment by vasukulkarni** [comment]
@yuriw want to schedule 3 or 4 tests from some suites (smoke/rados/rbd) , just to be sure?

**Comment by batrick** [comment]
@vasukulkarni I've added some runs to: http://pulpito.ceph.com/?branch=wip-pdonnell-testing-20180626.223928

**Comment by batrick** [comment]
Failures unrelated to the qa suite changes.

**Pull request merged**
