### PR TITLE
osd: fix objecter op cancellation vs osdmap update race

### PR DESCRIPTION
**Pull request by liewegas**
Fixes: http://tracker.ceph.com/issues/22123

### CODE REVIEW

**Comment by gregsfortytwo** [comment]
LGTM.

**Comment by smithfarm** [comment]
The bug is presenting in jewel integration testing, too.

**Comment by smithfarm** [comment]
@liewegas @jdurgin @dzafman I have a jewel backport of this ready - OK to run integration tests on it, or is it too late in jewel cycle for this change, and we should just live with the test failures?

**Comment by jdurgin** [comment]
@smithfarm this fix is reasonably small and self-contained, so I'd be ok with it being backported

**Comment by smithfarm** [comment]
@jdurgin Thanks - see #20518

**Pull request merged**
