### PR TITLE
jewel: rgw: for the create_bucket api, if the input creation_time is zero, we …

### PR DESCRIPTION
**Pull request by asheplyakov**
http://tracker.ceph.com/issues/17908

### CODE REVIEW

**Comment by smithfarm** [comment]
@asheplyakov Please append to the commit message a brief description of how you resolved the conflict. Even if it's just "trivial resolution", that provides potentially useful information in case of future forensic investigation.

**Comment by smithfarm** [comment]
See http://tracker.ceph.com/projects/ceph-releases/wiki/HOWTO_backport_commits especially where it says "if there is a conflict explain how it was resolved in the commit message, below the Conflicts line. For instance . . ."

**Comment by asheplyakov** [comment]
@smithfarm 
> Please append to the commit message a brief description of how you resolved the conflict.

Done

**Comment by smithfarm** [comment]
Jenkins re-test this please

**Comment by smithfarm** [comment]
@asheplyakov Next time please use `git cherry-pick -x` - thanks.

**Comment by smithfarm** [comment]
This passed rgw runs at http://tracker.ceph.com/issues/17851#note-50 and http://tracker.ceph.com/issues/17851#note-58

**Comment by smithfarm** [comment]
```
(11:46:45 AM) smithfarm: owasserm: thanks. For jewel integration rgw, then, what it comes down to is verifying that these 6 valgrind failures are all libtcmalloc-related: http://pulpito.front.sepia.ceph.com/smithfarm-2017-01-31_12:35:14-rgw-wip-jewel-backports-distro-basic-smithi/
(11:46:58 AM) smithfarm: owasserm: I will do that now
(11:47:05 AM) owasserm: smithfarm, thanks
(11:47:33 AM) smithfarm: owasserm: and assuming they are tcmalloc related, you said I can directly merge all the rgw PRs? Or do you want me to ask you for review in the PRs first?
(11:47:53 AM) owasserm: smithfarm, yes you can merge them
(11:48:19 AM) smithfarm: ok, will merge and do at least one or two more rgw runs before passing 10.2.6 to QE
```

**Pull request merged**
