### PR TITLE
osd: check adjacent clones are readable when rollback is called

### PR DESCRIPTION
**Pull request by ssdohammer-sl**
When an object executes a rollback op from its clone, it can bring this issue if any of the adjacent clones of rollback destination is unreadable.

To fix this issue, let OSD check if the rollback destination's adjacent clones are readable. If they are unreadable, wait until they are available.

fixes: https://tracker.ceph.com/issues/62167

Signed-off-by: Myoungwon Oh <myoungwon.oh@samsung.com>
Signed-off-by: Sungmin Lee <sung_min.lee@samsung.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Review by ljflores — APPROVED** [review]
Thanks @myoungwon !

**Comment by ljflores** [comment]
@myoungwon the first round of testing revealed this failure:

http://qa-proxy.ceph.com/teuthology/yuriw-2023-08-16_16:34:26-rados-wip-yuri10-testing-2023-08-15-1601-distro-default-smithi/7369938/teuthology.log
```
2023-08-16T17:48:39.725 INFO:tasks.ceph.osd.0.smithi037.stderr:2023-08-16T17:48:39.717+0000 7f8cd9204700 -1 received  signal: Hangup from /usr/bin/python3 /bin/daemon-helper kill ceph-osd -f --cluster ceph -i 0  (PID: 136755) UID: 0
2023-08-16T17:48:39.758 INFO:tasks.ceph.osd.3.smithi037.stderr:2023-08-16T17:48:39.754+0000 7f5354acd700 -1 osd.3 pg_epoch: 153 pg[3.16s1( v 153'74 lc 145'65 (0'0,153'74] local-lis/les=152/153 n=4 ec=45/20 lis/c=152/149 les/c/f=153/150/0 sis=152) [2,3,4]p3(1) r=1 lpr=152 pi=[149,152)/1 crt=153'74 lcod 123'60 mlcod 50'40 active+recovering rops=2 m=2 mbc={0={(1+0)=3},1={(0+1)=2,(1+1)=1},2={(1+0)=3}} trimq=[6c~1] ps=[43~1,45~1,47~2,4c~3,51~1,53~1,58~1,5a~2,5e~1,60~1,62~2,6b~1]] bad op order, already applied 1339 > this 1338
2023-08-16T17:48:39.761 INFO:tasks.ceph.osd.3.smithi037.stderr:/home/jenkins-build/build/workspace/ceph-dev-new-build/ARCH/x86_64/AVAILABLE_ARCH/x86_64/AVAILABLE_DIST/centos8/DIST/centos8/MACHINE_SIZE/gigantic/release/18.0.0-5533-ga036b225/rpm/el8/BUILD/ceph-18.0.0-5533-ga036b225/src/osd/PrimaryLogPG.cc: In function 'void PrimaryLogPG::execute_ctx(PrimaryLogPG::OpContext*)' thread 7f5354acd700 time 2023-08-16T17:48:39.755347+0000
2023-08-16T17:48:39.761 INFO:tasks.ceph.osd.3.smithi037.stderr:/home/jenkins-build/build/workspace/ceph-dev-new-build/ARCH/x86_64/AVAILABLE_ARCH/x86_64/AVAILABLE_DIST/centos8/DIST/centos8/MACHINE_SIZE/gigantic/release/18.0.0-5533-ga036b225/rpm/el8/BUILD/ceph-18.0.0-5533-ga036b225/src/osd/PrimaryLogPG.cc: 4294: ceph_abort_msg("out of order op")
2023-08-16T17:48:39.761 INFO:tasks.ceph.osd.3.smithi037.stderr: ceph version 18.0.0-5533-ga036b225 (a036b225184e28649a78316aac9733c596fb8bb5) reef (dev)
2023-08-16T17:48:39.761 INFO:tasks.ceph.osd.3.smithi037.stderr: 1: (ceph::__ceph_abort(char const*, int, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)+0xd7) [0x557f1421a80f]
2023-08-16T17:48:39.762 INFO:tasks.ceph.osd.3.smithi037.stderr: 2: (PrimaryLogPG::execute_ctx(PrimaryLogPG::OpContext*)+0x13d4) [0x557f144dfe64]
2023-08-16T17:48:39.762 INFO:tasks.ceph.osd.3.smithi037.stderr: 3: (PrimaryLogPG::do_op(boost::intrusive_ptr<OpRequest>&)+0x282a) [0x557f144e651a]
2023-08-16T17:48:39.762 INFO:tasks.ceph.osd.3.smithi037.stderr: 4: (OSD::dequeue_op(boost::intrusive_ptr<PG>, boost::intrusive_ptr<OpRequest>, ThreadPool::TPHandle&)+0x1c6) [0x557f14329e96]
2023-08-16T17:48:39.762 INFO:tasks.ceph.osd.3.smithi037.stderr: 5: (ceph::osd::scheduler::PGOpItem::run(OSD*, OSDShard*, boost::intrusive_ptr<PG>&, ThreadPool::TPHandle&)+0x69) [0x557f1464f939]
2023-08-16T17:48:39.762 INFO:tasks.ceph.osd.3.smithi037.stderr: 6: (OSD::ShardedOpWQ::_process(unsigned int, ceph::heartbeat_handle_d*)+0x113d) [0x557f143407ed]
2023-08-16T17:48:39.762 INFO:tasks.ceph.osd.3.smithi037.stderr: 7: (ShardedThreadPool::shardedthreadpool_worker(unsigned int)+0x43b) [0x557f14a0249b]
2023-08-16T17:48:39.763 INFO:tasks.ceph.osd.3.smithi037.stderr: 8: (ShardedThreadPool::WorkThreadSharded::entry()+0x14) [0x557f14a05744]
2023-08-16T17:48:39.763 INFO:tasks.ceph.osd.3.smithi037.stderr: 9: /lib64/libpthread.so.0(+0x81ca) [0x7f537fe371ca]
2023-08-16T17:48:39.763 INFO:tasks.ceph.osd.3.smithi037.stderr: 10: clone()
```
Can you have a look?

**Comment by myoungwon** [comment]
@ljflores I'll take a look.

**Comment by myoungwon** [comment]
Please see https://github.com/ceph/ceph/pull/53222
The above issue occurs because the transactions are handled in the reversed order. To avoid this issue, I posted https://github.com/ceph/ceph/pull/53222.

**Pull request closed without merging**
