### PR TITLE
kv/KeyValueDB: fix estimate_prefix_size()

### PR DESCRIPTION
**Pull request by aclamk**
This is simple fix for estimate_prefix_size(), with test.

### CODE REVIEW

**Comment by liewegas** [comment]
retest this pelase

**Comment by liewegas** [comment]
retest this please

**Comment by aclamk** [comment]
retest this please

**Comment by aclamk** [comment]
retest this please

**Comment by aclamk** [comment]
retest this please

**Comment by tchaikov** [comment]
- http://pulpito.ceph.com/kchai-2019-08-30_13:08:37-rados-wip-kefu2-testing-2019-08-29-0935-distro-basic-smithi/
- http://pulpito.ceph.com/kchai-2019-08-29_09:35:06-rados-wip-kefu2-testing-2019-08-29-0935-distro-basic-mira/

**Pull request merged**
