### PR TITLE
ceph-volume use realpath when checking mounts

### PR DESCRIPTION
**Pull request by alfredodeza**
on 469d01dc1aee8d6528944ef0acec58df868a9da7 the realpath detection was removed as it would cause issues with dmcrypt, but this is needed to ensure mounts are detected.

This change improves on that with the 4 combinations of realpath vs. plain on devices and paths.

Fixes: http://tracker.ceph.com/issues/22988

### CODE REVIEW

**Comment by alfredodeza** [comment]
jenkins test ceph-volume tox

**Comment by andrewschoen** [comment]
jenkins test ceph-volume all

**Comment by alfredodeza** [comment]
jenkins test ceph-volume all

**Comment by alfredodeza** [comment]
jenkins test ceph-volume lvm centos7-bluestore-dmcrypt

**Comment by andrewschoen** [comment]
jenkins test ceph-volume tox

**Comment by andrewschoen** [comment]
jenkins test ceph-volume all

**Comment by andrewschoen** [comment]
jenkins test ceph-volume simple centos7-filestore-dmcrypt_luks

**Comment by andrewschoen** [comment]
The tests ``lvm centos7-filestore-create`` and ``lvm xenial-filestore-create`` are expected to fail until #20265 is merged.

**Pull request merged**
