### PR TITLE
mailmap: v092 organizationmap

### PR DESCRIPTION
**Pull request by swamireddy**

### CODE REVIEW

**Comment by swamireddy** [comment]
@dachary - Updated the mailmap and organizationmap files.

**Comment by dachary** [comment]
@swamireddy one last detail otherwise looks good ;-)

**Comment by dachary** [comment]
@swamireddy ping ?

**Comment by swamireddy** [comment]
@dachary Updated the mailmap as below:
+Xie Rui <875016668@qq.com> Jerry7X <875016668@qq.com>
Is this NOT OK?

**Comment by swamireddy** [comment]
Thanks...

**Comment by dachary** [comment]
@swamireddy thank you ! :-)

**Pull request merged**
