### PR TITLE
rgw/coroutine: check for null stack on wakeup

### PR DESCRIPTION
**Pull request by cbodley**
Fixes: https://tracker.ceph.com/issues/56920

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Review by adamemerson — APPROVED** [review]

**Comment by tchaikov** [comment]
jenkins test api

**Comment by tchaikov** [comment]
jenkins test make check

**Comment by tchaikov** [comment]
jenkins test make check

**Comment by tchaikov** [comment]
jenkins test api

**Comment by tchaikov** [comment]
```
2022-08-16 12:02:48,778.778 INFO:__main__:test_create_api_key (tasks.mgr.dashboard.test_feedback.FeedbackTest) ... ERROR
```

**Comment by cbodley** [comment]
jenkins test make check

**Comment by cbodley** [comment]
jenkins test api

**Comment by cbodley** [comment]
jenkins test api

**Comment by cbodley** [comment]
passed qa in https://pulpito.ceph.com/cbodley-2022-08-18_23:33:15-rgw-wip-cbodley-testing-distro-default-smithi/

**Comment by cbodley** [comment]
jenkins test api

**Comment by cbodley** [comment]
jenkins test api

**Comment by cbodley** [comment]
jenkins test api

**Comment by cbodley** [comment]
jenkins test api

**Pull request merged**
