### PR TITLE
Optimization the session_handle_reset function.

### PR DESCRIPTION
**Pull request by songbaisen**
OSD: refactor OSD::session_handle_reset()

improve the performance of this method by pulling two loops into one

Fixes: #14182
Signed-off-by: songbaisen <song.baisen@zte.com.cn>

### CODE REVIEW

**Comment by tchaikov** [comment]
@songbaisen you might want to address following issues first:

1. remove the "merge" commit from your pull request
1. add an appropriate prefix for the title of your commit message. in this case, "OSD: " would be good enough.
1. add the "Fixes: #14182" right before your "Signed-off-by" line in your commit message
1. be more specific in your commit message.

**Comment by songbaisen** [comment]
@tchaikov ：Thanks for your good advice.I usually use svn in before.Now I study to use github.But not very familiar with github.In the next time i will be careful.

**Comment by tchaikov** [comment]
@songbaisen you now have two commits in this pr. one with the wrong `Signed-off-by` line, and lots of commits from others; the other with the the issues i put in last comment.

i'd suggest you remove the last commit by "git reset --hard HEAD^", and "git commit --amend" to revise your commit message so it looks like:

```
OSD: refactor OSD::session_handle_reset()

improve the performance of this method by pulling two loops into one

Fixes: #14182
Signed-off-by: songbaisen <song.baisen@zte.com.cn>
```

**Comment by songbaisen** [comment]
@tchaikov  OK, Fix it! Thanks very very much to you!

**Comment by liewegas** [comment]
@tchaikov ping

**Comment by tchaikov** [comment]
lgtm with rados qa run.

**Pull request merged**
