### PR TITLE
osd: fix the comment of RecoveryState hierarchical structure

### PR DESCRIPTION
**Pull request by fengyueqiao**
The Start state should be the inner state of Started.
Beacuse the Started level is changed from the second level to the first level,  all it's inner state levels are updaged also.

Signed-off-by: QinWei <qw.mail@foxmail.com>

### CODE REVIEW

**Review by athanatos — APPROVED** [review]
Sorry for leaving this for so long -- this looks right to me.  I've marked it needs-qa so it can get a test run -- not that it's risky, but we try not to make exceptions :).

**Comment by athanatos** [comment]
retest this please

**Comment by ljflores** [comment]
jenkins test make check

**Comment by ljflores** [comment]
Rados suite summary available here: https://tracker.ceph.com/projects/rados/wiki/MAIN#httpstrellocomc1EFSeXDn1752-wip-yuri10-testing-2023-05-16-1243

**Pull request merged**
