### PR TITLE
infernalis: rgw: swift API returns more than real object count and bytes used when retrieving account metadata

### PR DESCRIPTION
**Pull request by Abhishekvrshny**
http://tracker.ceph.com/issues/13735

### CODE REVIEW

**Comment by Abhishekvrshny** [comment]
@yehudasa this backport passed the rgw suite (http://pulpito.ceph.com/loic-2015-11-27_13:58:16-rgw-infernalis-backports---basic-multi/), do you think it can be merged ?

**Comment by Abhishekvrshny** [comment]
@yehudasa gentle reminder.

**Comment by dachary** [comment]
@yehudasa does this backport look good to merge ? It passed a run of the infernalis rgw suite ( see http://tracker.ceph.com/issues/13750#note-21 ) except one occurrence of a known bug (http://tracker.ceph.com/issues/14361).

**Comment by yehudasa** [comment]
@dachary ack

**Pull request merged**
