### PR TITLE
osdc/Objecter: skip sparse-read result decode if bufferlist is empty

### PR DESCRIPTION
**Pull request by dillaman**

### CODE REVIEW

**Comment by gregsfortytwo** [comment]
I'm not sure I like this quick fix. For one thing, I suspect ObjectOperations that do read-and-write will *not* get the same return values here — the starting read subops will fail since the object doesn't exist, but the write will create them. The subop return codes aren't filled in here because the operations were never even attempted.

This is actually sort of undefined behavior in the Objecter, right? Should we actually be invoking return callbacks on subops that don't exist? Would it be better for the subop's callback to have a bigger view of the system state so they can do the right thing instead?

Skimming through things, this change *will* impact how class operations behave, and I'm not sure it's correct. Did you audit other callers?


Also, let's see if that's a real or fake make check failure. Jenkins, test this please!

**Comment by dillaman** [comment]
The test failure was in the unit test for memstore so I'd hope it isn't affected. 

Any op with read and write subops shouldn't get -ENOENT since the missing object context is created if there is a write subop. Honestly, I figured that if any subop fails, the whole op is aborted -- as least as per do_osd_ops handles it. If that's the true intent, any failure of the op should really just bubble down to the subops I would think.

What do you mean for subops that don't exist? The subop return code was on the MOSDOpReply message with no data, return code of zero since it was never executed and populated. Are you suggesting that the OSD should fail all subops when the op as a whole fails?

**Comment by gregsfortytwo** [comment]
By "subops that don't exist" I mean "didn't get executed because of an earlier failure".

So in this PR, if the object doesn't exist then we return ENOENT to their handlers on subops that were never executed.

But why should ENOENT be the only one that gets that special treatment? We're still going to invoke the handlers on other error responses that may not have filled in the subops — unless there's some fundamental reason that ENOENT is the only special error code here. :/ And because of the class ops, we're returning ENOENT on the special invocation that should perhaps have been short-circuited by ENOENT on the object. I don't know what that does, but there might be issues with eg the rgw lookup codes.

I mean, you're right, ENOENT is definitely *special*. I'm just not sure if it's special *enough* for this.

> Honestly, I figured that if any subop fails, the whole op is aborted -- as least as per PrimaryLogPG::do_osd_ops handles it.

Note the conditional on whether to return or continue:
> if (result < 0 && (op.flags & CEPH_OSD_OP_FLAG_FAILOK) &&
result != -EAGAIN && result != -EINPROGRESS)

**Comment by gregsfortytwo** [comment]
Oh, and actually, it's definitely not safe (though I don't know if we invoke this behavior right now):

* a subop that is not marked failok can return ENOENT.
* That ENOENT will get turned into the overall return code.
* Subops that *were actually performed and succeeded* will get a retcode of ENOENT instead of their real value.

**Comment by dillaman** [comment]
Subops that were actually performed and succeeded will get a retcode of ENOENT instead of their real value.

... but at that point, the operation as a whole was aborted, correct, or is that only for ops that contain one or more write subops? If the former is the case, then the fix needs to come from the OSD where it properly populates an error code in all non-executed subops (e.g. -ERESTART or -ENOEXEC)

**Comment by gregsfortytwo** [comment]
Sure the op was aborted. But let’s say we wanted to look up four omap entries that we expect to exist, and if they don’t exist we (on a different op, because we need the real data) write out default values for them.
So if the first two entries exist, their values get bundled into the return buffers. But the last doesn’t exist, so we return ENOENT and fail the overall op. (Maybe we don’t have it as failok because later values only have meaning if the earlier ones exist.)

On the client, we are told enoent and see that *none* of the values exist, so we generate a write op initializing all of them, overwriting valid data. Whoops!

**Comment by dillaman** [comment]
... so any suggestions for how to fix (preferably without changing the MOSDOpReplay to include the last executed op so that this long-standing bug can be backported)?

**Comment by gregsfortytwo** [comment]
> Would it be better for the subop's callback to have a bigger view of the system state so they can do the right thing instead?

So, yeah, I think we need to change callbacks to see the total op return value. We know what the options are in your use case ops, right? And we may need to tweak the protocol for future versions. (This can be backwards compatible.)

**Comment by dillaman** [comment]
Personally -- it seems like a well chosen error code for all unexecuted ops would be simpler and just as useful result from such a scenario, one just needs to be picked (for example, -EIO has been the go-to error code for buffer ::decode underflow error).

The failure code is enough to tell the caller that that the op failed to execute so the results are not valid and it avoids having to create a special purpose callback handler (and new librados API methods) to handle this case that apparently no one cared about (and again can divine the result given the error code).

**Comment by gregsfortytwo** [comment]
Yeah, we could do that too but it seems like more of an API change. This PR is prompted by performance concerns, not a programming bug, right?

It also occurs to me that an easier fix is probably just to have the decoding callback see if there’s *any* data before attempting to decode — I don’t see any way the buffer can be empty except in this case. That would stop the exceptions and resolve things from your perspective, right?

**Comment by dillaman** [comment]
Sure -- I will gladly punt the real issue w/ just checking if the buffer is empty.

**Comment by liewegas** [comment]
http://pulpito.ceph.com/sage-2017-10-21_08:57:17-rados-wip-sage2-testing-2017-10-20-2318-distro-basic-smithi/

**Pull request merged**
