### PR TITLE
reef: qa/distros: remove centos 8 from supported distros

### PR DESCRIPTION
**Pull request by cbodley**
partial backports of https://github.com/ceph/ceph/pull/53517 and https://github.com/ceph/ceph/pull/53901. those also removed rhel and ubuntu 20.04 as supported distros, but reef will continue to support them

the following commits were omitted from https://github.com/ceph/ceph/pull/53517:
* https://github.com/ceph/ceph/pull/53517/commits/16099bebcfa88add80a8834719608326bd7898af
* https://github.com/ceph/ceph/pull/53517/commits/7a1dce1ebd883741b5003b9e18d4765526cbbb3e
* https://github.com/ceph/ceph/pull/53517/commits/c71698c6a1dde587466a88669f17d1df3307e591

and from https://github.com/ceph/ceph/pull/53901:
* https://github.com/ceph/ceph/pull/53901/commits/b9ba9642fea18055e768c3ddee5ba5e372264ede
* https://github.com/ceph/ceph/pull/53901/commits/7193f76a1502de392af0b407db0073266f9bc9c8
* https://github.com/ceph/ceph/pull/53901/commits/12254d8f5418b31437ba7077fbfc2d015bd88fe1

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Comment by ljflores** [comment]
I added a backport of https://github.com/ceph/ceph/pull/57934 to fix a remaining centos_8 reference in the rados suite as well, but on second thought, that might get too confusing to track. I will take care of backporting this commit separately.

**Review by idryomov — COMMENTED** [review]
I wanted to do a quick sanity check, but got confused:
 
> the following commits were omitted from #53517:
> 
> [16099be](https://github.com/ceph/ceph/commit/16099bebcfa88add80a8834719608326bd7898af)
> [7a1dce1](https://github.com/ceph/ceph/commit/7a1dce1ebd883741b5003b9e18d4765526cbbb3e)
> [c71698c](https://github.com/ceph/ceph/commit/c71698c6a1dde587466a88669f17d1df3307e591)

Not following why this one is (fully) omitted given that it's leaving `qa/suites/fs/mixed-clients/distro/centos_8.yaml` and `qa/suites/fs/verify/distro/centos_8.yaml` in place.  Adding @ceph/cephfs.

> 
> and from #53901:
> 
> [b9ba964](https://github.com/ceph/ceph/commit/b9ba9642fea18055e768c3ddee5ba5e372264ede)
> [7193f76](https://github.com/ceph/ceph/commit/7193f76a1502de392af0b407db0073266f9bc9c8)

These two aren't actually omitted even though they seem to be dealing with rhel, not 8.stream?

I also don't understand where the last commit ("qa/distros: add ubuntu 22.04 for containerized tests", appended by Adam) came from -- it claims to be a partial backport of https://github.com/cbodley/ceph/commit/0fa3eb67387eaf403b5a6e716a81582949dcecf1 which is the SHA of the first commit in this PR...  Regardless, is changing something wrt. ubuntu in a PR that is concerned with dropping 8.stream necessary?

**Comment by cbodley** [comment]
results in https://pulpito.ceph.com/?branch=wip-yuri5-testing-2024-06-08-0902-reef need review

**Comment by cbodley** [comment]
> I wanted to do a quick sanity check, but got confused:

thanks @idryomov, my backport was admittedly sloppy. i'll find time to redo the backports

**Comment by cbodley** [comment]
i pushed a new commit in response to https://tracker.ceph.com/issues/66401#note-20

**Review by adk3798 — APPROVED** [review]
works for orch suite at least

**Comment by amathuria** [comment]
Rados approved: https://tracker.ceph.com/projects/rados/wiki/REEF#httpstrackercephcomissues66401

**Comment by yuriw** [comment]
jenkins test this please

**Comment by guits** [comment]
@cbodley you might want to cherry-pick this https://github.com/ceph/ceph/pull/58290/commits

**Comment by cbodley** [comment]
> @cbodley you might want to cherry-pick this https://github.com/ceph/ceph/pull/58290/commits

thanks, done

**Comment by cbodley** [comment]
from https://jenkins.ceph.com/job/ceph-api/76946/
> FAIL: test_get_indiv_flag (tasks.mgr.dashboard.test_osd.OsdFlagsTest)

**Comment by cbodley** [comment]
jenkins test api

**Comment by dxmoraru** [comment]
Does this mean you will not be providing EL8 RPMs of 18.2.4?  Please see and reply to https://lists.ceph.io/hyperkitty/list/ceph-users@ceph.io/thread/74RQYR7AEH2NIQZJ2P2NMAADQUOAWATA/.

**Pull request merged**
