### PR TITLE
qa: introduce rbd-mirror thrasher to existing tests

### PR DESCRIPTION
**Pull request by dillaman**

### CODE REVIEW

**Comment by dillaman** [comment]
http://pulpito.ceph.com/jdillaman-2018-04-19_18:50:18-rbd-master-distro-basic-smithi/
http://pulpito.ceph.com/jdillaman-2018-04-19_19:28:49-rbd-master-distro-basic-smithi/

**Comment by tchaikov** [comment]
retest this please

**Comment by trociny** [comment]
@dillaman not sure it is problem with the test or it reveals a real problem: I am observing "stop/start/restart mirror via admin socket" test fails after stopping an image replayer via admin socket.

In [1,2] it stopped the replayer on one instance, but when checking the status via admin socket another instance kept reporting it was running there. In [3] the status check via admin socket passed (no instance reported it running) but the status in mirror pool directory was reporting it 'up+replaying'.

[1] http://qa-proxy.ceph.com/teuthology/trociny-2018-04-21_06:50:46-rbd-wip-mgolub-testing-distro-basic-smithi/2425070/teuthology.log
[2] http://qa-proxy.ceph.com/teuthology/trociny-2018-04-21_18:49:24-rbd-wip-mgolub-testing-distro-basic-smithi/2425388/teuthology.log
[3] http://qa-proxy.ceph.com/teuthology/trociny-2018-04-21_06:50:46-rbd-wip-mgolub-testing-distro-basic-smithi/2425083/teuthology.log

**Comment by dillaman** [comment]
Tweaked it a little bit into two classes of tests: (1) daemons managed by teuthology for thrashed tests (which will skip anything related to stop/starting services, and (2) daemons managed by the workunits.

http://pulpito.ceph.com/jdillaman-2018-04-23_15:35:34-rbd-master-distro-basic-smithi/
http://pulpito.ceph.com/jdillaman-2018-04-23_16:17:33-rbd-master-distro-basic-smithi/

**Comment by trociny** [comment]
@dillaman It looks like the thrasher was able to trigger a rbd-mirror daemon crash:
http://pulpito.ceph.com/trociny-2018-04-24_08:17:18-rbd-wip-mgolub-testing-distro-basic-smithi/2434398/

**Comment by dillaman** [comment]
@trociny ... just to close the loop, the crash was caused by a bug in the ```Objecter```: https://github.com/ceph/ceph/pull/21649

**Pull request merged**
