### PR TITLE
osd: fix typos and some cleanups

### PR DESCRIPTION
**Pull request by ZVampirEM77**
1.  There are some unnecessary function called in `PrimaryLogPG::find_object_context`;

2. Use `__func__` for `dout` instead of an explicit function name;

3. Update comment introduction for `PrimaryLogPG::recover_missing` return value;

### CODE REVIEW

**Comment by ZVampirEM77** [comment]
Jenkins, retest this please.

**Comment by ZVampirEM77** [comment]
@tchaikov ping~

**Comment by ZVampirEM77** [comment]
@liewegas @tchaikov ping~

**Comment by tchaikov** [comment]
- http://pulpito.ceph.com/kchai-2017-12-14_08:53:42-rados-wip-kefu-testing-2017-12-14-1157-distro-basic-mira/
- http://pulpito.ceph.com/kchai-2017-12-15_06:17:13-rados-wip-kefu-testing-2017-12-14-1157-distro-basic-mira/

**Pull request merged**
