### PR TITLE
luminous: cephfs: racy is_mounted() checks in libcephfs

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/21359

### CODE REVIEW

**Comment by yuriw** [comment]
@smithfarm pls rebase:

 * branch            wip-21359-luminous -> FETCH_HEAD
Auto-merging src/client/Client.cc
CONFLICT (content): Merge conflict in src/client/Client.cc
Automatic merge failed; fix conflicts and then commit the result.

**Comment by smithfarm** [comment]
@yuriw Rebasing won't help until the conflicting PR is merged. I'll check which PR that is, and possibly move these cherry-picks into that one.

**Comment by yuriw** [comment]
[wip-yuri3-testing-2018-01-29-1703-luminous](https://trello.com/c/Ti9d35jC/247-wip-yuri3-testing-2018-01-29-1703-luminous)

**Comment by batrick** [comment]
This PR is missing https://github.com/ceph/ceph/pull/17095/commits/efca340596ef4da2b254ff1c64ec4c462d7b95a5

is that deliberate?

**Comment by yuriw** [comment]
tag " luminous-batch-1" for retesting

**Comment by theanalyst** [comment]
this PR is still causing conflicts while cherry-pick, and the merge conflict isn't very obvious, @batrick can someone from cephfs backport this one

**Comment by batrick** [comment]
ACK

**Pull request merged**
