### PR TITLE
mgr/dashboard: Fix bucket creation 415 error

### PR DESCRIPTION
**Pull request by pschichtel**
This PR is conceptionally the same as this one: https://github.com/ceph/ceph/pull/40216.

I'm targeting ceph reef because that's what I can test against.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Comment by pschichtel** [comment]
Using haproxy with httpchk checks instead of nginx works around this issue, but it still feels odd. Is there any interest in this change?

Also why is jenkins complains about unsigned commits? My commit has a sign-off and a gpg signature

**Comment by nizamial09** [comment]
@pschichtel thanks for the contribution. Can you create a tracker and attach it to the PR with proper steps for reproducing the issue? And once we have that, probably we can take this forward. I don't have an issue with the change at first glance but its good to test it against a reproducer myself. 

You can check the contributors guideline for info on the PR format: https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst

**Comment by nizamial09** [comment]
btw, test failures looks unrelated, I can manually trigger it again but it will start running again once you repush the branch. And in the changes, there are unrelated changes so it'd be great if you can remove them as well.

**Comment by pschichtel** [comment]
I currently don't have the capacity to follow this through and the recommended haproxy doesn't observe this issue. I have no idea why nginx has this issue but haproxy doesn't.

**Pull request closed without merging**
