### PR TITLE
mgr/ansible: add install tox==2.9.1

### PR DESCRIPTION
**Pull request by tchaikov**
in src/pybind/mgr/ansible/tox.ini, tox>=2.8.1 is required. to be
consistent with other requirements.txt in Ceph, tox 2.9.1 will be
installed for these tox environments.

Signed-off-by: Kefu Chai <kchai@redhat.com>

- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by tchaikov** [comment]
cc @jmolmo

**Comment by jmolmo** [comment]
@kefu: thanks for warn me. LGTM

**Comment by sebastian-philipp** [comment]
could you also copy it to `../orchestrator_cli`?

**Comment by tchaikov** [comment]
@sebastian-philipp done.

**Pull request merged**
