### PR TITLE
qa: ignore cluster warning when fs flag refuse_client_session is set

### PR DESCRIPTION
**Pull request by dparmar18**
Fixes: https://tracker.ceph.com/issues/59667

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by dparmar18** [comment]
@vshankar ran a job and its green http://pulpito.front.sepia.ceph.com/dparmar-2023-05-08_09:08:29-fs:functional-wip-vshankar-testing-20230506.143554-distro-default-smithi/

**Review by batrick — APPROVED** [review]

**Comment by vshankar** [comment]
Can you add `Introduced-by` tag in the commit? And I guess this _does not_ need backporting since the feature wasn't backported, yes?

**Review by kotreshhr — APPROVED** [review]

**Comment by dparmar18** [comment]
Last push: Added `Introduced-by` tag in the commit, no changes to the code

**Review by lxbsz — APPROVED** [review]

**Review by lxbsz — APPROVED** [review]

**Comment by vshankar** [comment]
jenkins test make check arm64

**Comment by vshankar** [comment]
Running test now: https://pulpito.ceph.com/vshankar-2023-05-09_12:06:46-fs-wip-vshankar-testing-20230509.090020-testing-default-smithi/

**Comment by vshankar** [comment]
jenkins test make check arm64

**Comment by vshankar** [comment]
https://pulpito.ceph.com/?branch=wip-vshankar-testing-20230509.090020

**Comment by vshankar** [comment]
https://tracker.ceph.com/projects/cephfs/wiki/Main#15-May-2023

**Pull request merged**
