### PR TITLE
DNM osd: Revert use of dmclock message feature bit since not yet finalized

### PR DESCRIPTION
**Pull request by ivancich**
osd: Revert use of dmclock message feature bit since not yet finalized

Because the updated use of dmclock is not yet finalized and the
unfinished functionality uses a valuable messaging feature bit that we
don't want to waste, we're removing it for the mimic release.

Reverts most of the following commits for mimic:

  de8110ebb39401d3e09cb871f843776421ccd56f
  739d7e462f3a03c4e188fcfa48eb05c0063970c9
  2361e9c790306e789393323ef349d8b4a20bc70d
  9b702cf8fc2ff881ca16edc78874f2118a2e4641

Signed-off-by: J. Eric Ivancich <ivancich@redhat.com>

### CODE REVIEW

**Comment by ivancich** [comment]
Will run it through the rados suite once shaman finishes the build (https://shaman.ceph.com/builds/ceph/wip-revert-dmclock-feature-bit-plus/) and then remove the "DNM".

**Comment by liewegas** [comment]
retest this please

**Comment by ivancich** [comment]
I finally got a good shaman build. Here's the scheduled rados suite: http://pulpito.ceph.com/ivancich-2018-04-12_15:00:57-rados-wip-revert-dmclock-feature-bit-plus-distro-basic-smithi/

**Comment by ivancich** [comment]
@liewegas I mistakenly pushed a small change (creation of a file) to force a shaman rebuild yesterday, adding an unfortunate second commit. I've repushed without that second commit (https://github.com/ivancich/ceph-fork/tree/wip-revert-dmclock-feature-bit-plus), but github is not picking that up in this PR, perhaps because it's "Closed".

**Comment by ivancich** [comment]
Since this was inadvertently closed, is replaced by https://github.com/ceph/ceph/pull/21398.

**Pull request closed without merging**
