### PR TITLE
jewel: osd: Scrub improvements and other fixes

### PR DESCRIPTION
**Pull request by dzafman**
Backport pull request ceph/ceph#11449
Backport pull request ceph/ceph#9613
Backport pull request ceph/ceph-qa-suite#1274
Backport pull request ceph/ceph#9304
Backport pull request ceph/ceph#11914

http://tracker.ceph.com/issues/18116
http://tracker.ceph.com/issues/17970
http://tracker.ceph.com/issues/17857
http://tracker.ceph.com/issues/18502

### CODE REVIEW

**Comment by smithfarm** [comment]
Marked DNM so integration branch population script doesn't pick it up.

**Comment by smithfarm** [comment]
@dzafman So the idea is for this to replace #13047 ?

**Comment by dzafman** [comment]
@smithfarm Yes.   I didn't look at all the backport commits. But the hope is that this will merge to Jewel without any conflict resolution needed.  I've never dealt with a pull request that is rebased on another.  So if we try to merge this last will GitHub get confused?  Or maybe manually merge it?

**Comment by smithfarm** [comment]
@dzafman Github should not have any problem with this. Could you please:

* rebase to get rid of the merge commits
* put all related backport tracker URLs in the PR description
* DNM the PRs this is replacing
* un-DNM this PR

**Comment by dzafman** [comment]
Replaces ceph/ceph#13047, ceph/ceph#12288, ceph/ceph#12088

**Comment by smithfarm** [comment]
@dzafman Thanks! I will do another integration round and let you know the results.

**Comment by smithfarm** [comment]
@dzafman I must have merged something that caused a conflict, sorry (unintentional). Please rebase.

**Comment by smithfarm** [comment]
The conflict arose when I merged this: https://github.com/ceph/ceph/pull/12978/commits/cedaecf88efd3e4807e764d023bb956f806051da

**Comment by dzafman** [comment]
@smithfarm Rebased.  I didn't finishing building it, but Jenkins will too.

**Comment by dzafman** [comment]
@smithfarm There was one RBD failure.  Could this have been caused by a recent merge?

**Comment by dzafman** [comment]
@smithfarm This was an rbd failure.  Could this be from a recent merge?  Nothing in tracker for this librbd assert.

FAILED assert(m_state == STATE_ACQUIRING || m_state == STATE_POST_ACQUIRING || m_state == STATE_WAITING_FOR_PEER)

**Comment by smithfarm** [comment]
Jenkins re-test this please

**Comment by smithfarm** [comment]
> This was an rbd failure. Could this be from a recent merge?

Then it would be affecting all jewel PRs, right? I'm not seeing that.

**Comment by smithfarm** [comment]
@dzafman It was transient.

**Comment by smithfarm** [comment]
Note: close #13047 when this is merged.

**Comment by dzafman** [comment]
@smithfarm Are you going to merge this?

**Comment by smithfarm** [comment]
@dzafman After it clears a rados run, yes.

**Comment by smithfarm** [comment]
@dzafman Will this eliminate the "assert len(objs) == 1" test failures that we are tracking in http://tracker.ceph.com/issues/16516 ?

**Comment by dzafman** [comment]
@smithfarm Tracker 16516 has still been happening very rarely.  This pull request has nothing to do with it.

**Comment by dzafman** [comment]
@smithfarm Rebased again.  Why hasn't this merged?

**Comment by smithfarm** [comment]
@dzafman Because I have a day job?

**Comment by dachary** [comment]
Maybe fails consistently because of http://tracker.ceph.com/issues/17366
- http://pulpito.ceph.com/smithfarm-2017-02-13_20:36:56-rados-wip-jewel-backports-distro-basic-smithi/811116
- http://pulpito.ceph.com/loic-2017-02-20_07:43:57-rados-wip-jewel-backports-distro-basic-smithi/835944

**Comment by dzafman** [comment]
@tchaikov Please review.  You already approved the first 9 commits previously under ceph/ceph#12088.

**Comment by tchaikov** [comment]
@dachary i looked at http://pulpito.ceph.com/smithfarm-2017-02-13_20:36:56-rados-wip-jewel-backports-distro-basic-smithi/811116, the failure is caused by wrong output of "ceph pg dump_stuck unclean 10 --format=json". it is expected that this command only prints "unclean" pgs, but it printed "stale+active+undersized+degraded" pgs also. please, search "2017-02-14T00:18:39.003" in " /a//smithfarm-2017-02-13_20:36:56-rados-wip-jewel-backports-distro-basic-smithi/811116/teuthology.log" for more details. and i also checked the code path to handle the "pg dump_stuck", the changes in this PR is not involved in it. but the tested commit 86f3d99a9d10afc8be7a72b4648550687dcf6cf1 was removed. i cannot check it.

i am pushing a jewel branch with this PR to ceph-ci in hope to reproduce it.

**Comment by tchaikov** [comment]
@smithfarm @dachary could you help rerun the failed tests using ceph-ci/wip-13146-jewel-kefu ?

**Pull request merged**
