### PR TITLE
mimic: ceph-objectstore-tool: Dump hashinfo

### PR DESCRIPTION
**Pull request by ashishkumsingh**
https://tracker.ceph.com/issues/37689

### CODE REVIEW

**Comment by dzafman** [comment]
@ashishkumsingh Did you run the ceph-objectstore-tool comand in a vstart.sh with an erasure coded pool with an object or two?

**Comment by ashishkumsingh** [comment]
> @ashishkumsingh Did you run the ceph-objectstore-tool comand in a vstart.sh with an erasure coded pool with an object or two?

@dzafman nope, I haven't tested that in vstart.sh

**Comment by smithfarm** [comment]
@dzafman Is the lack of the testing you asked for a blocker or something you could help us with?

**Comment by dzafman** [comment]
@smithfarm This is used as a diagnostic tool only.  The change is simple, so I don't see the lack of an automated test case as a blocker.  If I add the test case in qa/standalone/special/ceph_objectstore_tool.py then we'll back port that.

**Comment by dzafman** [comment]
I have a rudimentary test for this in ceph/ceph#26158 in master.  We could backport that pull request in combination with this one.

**Comment by smithfarm** [comment]
@ashishkumsingh Please cherry-pick the commits from https://github.com/ceph/ceph/pull/26158 into this PR.

**Comment by yuriw** [comment]
[wip-yuri3-testing-2019-02-05-1650-mimic](https://trello.com/c/KS5UT0i5/530-wip-yuri3-testing-2019-02-05-1650-mimic)

**Pull request merged**
