### PR TITLE
mgr/dashboards: avoiding relative paths '../../..'

### PR DESCRIPTION
**Pull request by dungdm93**
Sorry you guys but this one is burning my eyes :sunglasses: 
Screenshot from 2020-11-02 18-38-49

You could avoid this problem by config path alias:
```json
"baseUrl": "./",
"paths": {
  "~/*": ["src/*"]
},
```
So now, the import paths look much better:
Screenshot from 2020-11-02 18-43-42

Signed-off-by: Dũng Đặng Minh <dungdm93@live.com>

### CODE REVIEW

**Comment by s0nea** [comment]
Hi @dungdm93 and thank you for your contribution!

Unfortunately `make check` and the `ceph API tests` is failing because the frontend modules can't be found, e.g.:

```
ERROR in src/app/ceph/cephfs/cephfs-list/cephfs-list.component.ts:3:31 - error TS2307: Cannot find module '~/app/shared/api/cephfs.service' or its corresponding type declarations.

3 import { CephfsService } from '~/app/shared/api/cephfs.service';
                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/app/ceph/cephfs/cephfs-list/cephfs-list.component.ts:4:33 - error TS2307: Cannot find module '~/app/shared/classes/list-with-details.class' or its corresponding type declarations.

4 import { ListWithDetails } from '~/app/shared/classes/list-with-details.class';
                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/app/ceph/cephfs/cephfs-list/cephfs-list.component.ts:5:30 - error TS2307: Cannot find module '~/app/shared/enum/cell-template.enum' or its corresponding type declarations.

5 import { CellTemplate } from '~/app/shared/enum/cell-template.enum';
                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/app/ceph/cephfs/cephfs-list/cephfs-list.component.ts:6:31 - error TS2307: Cannot find module '~/app/shared/models/cd-table-column' or its corresponding type declarations.
```
Is there something missing?

Also... are you planning to to squash your commits later? - If not, there are two unsigned commits in the PR.

Let me know if I can help with anything :slightly_smiling_face:

**Comment by LenzGr** [comment]
Thank you for your contribution! This looks like a useful enhancement. Could you please address the comments/concerns that have been raised so far? Thanks in advance!

**Comment by dungdm93** [comment]
@s09816 , @LenzGr thank you for your comments.
I'm going to rebase and signed all my commits and try to fix CI fails.

**Comment by dungdm93** [comment]
Hello @s0nea
import errors are fixed. I missing jest's `moduleNameMapper`
```json
  "jest": {
    "moduleNameMapper": {
      "\\.scss$": "identity-obj-proxy",
      "~/(.*)$": "<rootDir>/src/$1"
    },
```
However CI still fail on test `mgr-dashboard-frontend-unittests`, but it don't show any clear error message.
Could you please take a look?

**Comment by votdev** [comment]
> Hello @s0nea
> import errors are fixed. I miss jest's `moduleNameMapper` config
> 
> ```json
>   "jest": {
>     "moduleNameMapper": {
>       "\\.scss$": "identity-obj-proxy",
>       "~/(.*)$": "<rootDir>/src/$1"
>     },
> ```
> 
> However CI still fail on test `mgr-dashboard-frontend-unittests`, but it don't show any clear error message.
> Could you please take a look?
> 
> P/S: gotcha
> Screenshot from 2020-11-03 10-23-38

Your latest push seems to have fixed the CI issues. Could you please rebase the PR to fix the conflicting files?

**Comment by dungdm93** [comment]
@votdev rebased

**Comment by dungdm93** [comment]
jenkins retest this please

**Comment by dungdm93** [comment]
Hey @ceph/dashboard
I just add a tslint rule to prevent import with more than 1 parent in path (e.g `'../../foobar'`)
Is that OK?
```
"import-blacklist": [true,
  "rxjs/Rx",
  {"@angular/core/testing": ["async"]},
  ["(\\.{1,2}\/){2,}"] // e.g import ../../foobar
],
```

**Comment by dungdm93** [comment]
jenkins test make check

**Review by epuertat — APPROVED** [review]
Awesome clean-up! Thanks a lot, @dungdm93 !

You need to rebase it btw.

**Review by s0nea — APPROVED** [review]
LGTM :+1:

**Comment by dungdm93** [comment]
@tspmelo could you please review this PR.

**Comment by bk201** [comment]
- CI branch: [wip-kiefer-testing-2020-11-09-1149](https://github.com/ceph/ceph-ci/commits/wip-kiefer-testing-2020-11-09-1149)
- [CI packages](https://shaman.ceph.com/builds/ceph/wip-kiefer-testing-2020-11-09-1149/)
- QA runs: **PASS**
  Suite|Total|Pass|Fail|Dead
  -|-|-|-|-
  [rados:cephadm:dashboard](https://pulpito.ceph.com/kchang-2020-11-09_06:15:48-rados:cephadm:dashboard-wip-kiefer-testing-2020-11-09-1149-distro-basic-smithi)|1|1|0|0

**Review by alfonsomthd — APPROVED** [review]

**Review by nizamial09 — APPROVED** [review]

**Comment by callithea** [comment]
@dungdm93 sorry, could you rebase one more time? We should get this PR in as soon as possible, so you don't have to resolve conflicts all the time. :)

**Comment by dungdm93** [comment]
jenkins test api

**Comment by callithea** [comment]
Thanks for rebasing, @dungdm93!

Unfortunately `make check` failed:
```
[lint:tslint  ] Linting "ceph-dashboard"...
[lint:tslint  ] /home/jenkins-build/build/workspace/ceph-pull-requests/src/pybind/mgr/dashboard/frontend/src/app/shared/constants/app.constants.ts:3:30
[lint:tslint  ] ERROR: 3:30  import-blacklist  This import is blacklisted by /(\.{1,2}\/){2,}/
[lint:tslint  ] 

```
https://jenkins.ceph.com/job/ceph-pull-requests/63202/consoleFull#1824705155e2f9bd1b-f570-4eac-a6c0-0080730e3135

**Comment by dungdm93** [comment]
@callithea Yes. I'm working on this.

**Comment by callithea** [comment]
jenkins test dashboard

**Comment by callithea** [comment]
jenkins test api

**Comment by dungdm93** [comment]
jenkins test api

**Comment by dungdm93** [comment]
Hello @callithea 
Could you please help me troubleshoot `ceph API tests` fails. I see some missing packages like `jsonpatch` and `rook` from `pybind/mgr` but not sure it's root cause or not.

**Comment by callithea** [comment]
> Hello @callithea
> Could you please help me troubleshoot `ceph API tests` fails. I see some missing packages like `jsonpatch` and `rook` from `pybind/mgr` but not sure it's root cause or not.

Hi @dungdm93, sure! There's a test case failure in the logs, but it is not related to your PR.:
```
2020-11-10 05:52:58,951.951 INFO:__main__:FAIL: test_full_health (tasks.mgr.dashboard.test_health.HealthTest)
2020-11-10 05:52:58,951.951 INFO:__main__:----------------------------------------------------------------------
2020-11-10 05:52:58,951.951 INFO:__main__:Traceback (most recent call last):
2020-11-10 05:52:58,951.951 INFO:__main__:  File "/home/jenkins-build/build/workspace/ceph-api/qa/tasks/mgr/dashboard/helper.py", line 454, in assertSchema
2020-11-10 05:52:58,951.951 INFO:__main__:    return _validate_json(data, schema)
2020-11-10 05:52:58,951.951 INFO:__main__:  File "/home/jenkins-build/build/workspace/ceph-api/qa/tasks/mgr/dashboard/helper.py", line 668, in _validate_json
2020-11-10 05:52:58,951.951 INFO:__main__:    for key, sub_schema in schema.sub_elems.items()
2020-11-10 05:52:58,951.951 INFO:__main__:tasks.mgr.dashboard.helper._ValError: In `input['mon_status']`: unknown keys: {'stretch_mode'}
2020-11-10 05:52:58,951.951 INFO:__main__:
2020-11-10 05:52:58,952.952 INFO:__main__:During handling of the above exception, another exception occurred:
2020-11-10 05:52:58,952.952 INFO:__main__:
2020-11-10 05:52:58,952.952 INFO:__main__:Traceback (most recent call last):
2020-11-10 05:52:58,952.952 INFO:__main__:  File "/home/jenkins-build/build/workspace/ceph-api/qa/tasks/mgr/dashboard/test_health.py", line 272, in test_full_health
2020-11-10 05:52:58,952.952 INFO:__main__:    self.assertSchema(data, schema)
2020-11-10 05:52:58,952.952 INFO:__main__:  File "/home/jenkins-build/build/workspace/ceph-api/qa/tasks/mgr/dashboard/helper.py", line 456, in assertSchema
2020-11-10 05:52:58,952.952 INFO:__main__:    self.assertEqual(data, str(e))
2020-11-10 05:52:58,952.952 INFO:__main__:AssertionError: {'health': {'status': 'HEALTH_OK', 'check[310005 chars]: 0}} != "In `input['mon_status']`: unknown keys: {'stretch_mode'}"
```
It's already [tracked](https://tracker.ceph.com/issues/48155) and there's also an open [PR](https://github.com/ceph/ceph/pull/37997) to fix it.

**Comment by callithea** [comment]
jenkins test dashboard

**Review by callithea — APPROVED** [review]
lgtm!

**Comment by epuertat** [comment]
Thanks a lot, @dungdm93, for you contribution here! Please, let us know if you want to get more involved with the Dashboard developments or you have more ideas or suggestions!

**Pull request merged**
