### PR TITLE
mgr/prometheus: fix PG state names

### PR DESCRIPTION
**Pull request by jcsp**
...and add a couple of common missing ones.

Fixes: https://tracker.ceph.com/issues/23584
Signed-off-by: John Spray <john.spray@redhat.com>

### CODE REVIEW

**Comment by k0ste** [comment]
@jcsp, proper pg_states. From `osd_types` and special `deep`.
`*_wait` and other should be with underscores, not dashes.

```python
PG_STATES = ['creating', 'active', 'clean', 'down', 'recovery_unfound',        
             'backfill_unfound', 'scrubbing', 'degraded', 'inconsistent',      
             'peering', 'repair', 'recovering', 'backfill_wait', 'incomplete', 
             'stale', 'remapped', 'deep', 'backfilling',                       
             'backfill_toofull', 'recovery_wait', 'undersized', 'activating',  
             'peered', 'snaptrim', 'snaptrim_wait', 'recovery_toofull',        
             'snaptrim_error', 'forced_recovery', 'forced_backfill']           
```

**Comment by jcsp** [comment]
Hmm, I had assume the `-` vs `_` thing was getting handled somewhere else but now I can't see it, were all the states with `-` in just broken the whole time?

**Comment by k0ste** [comment]
> all the states with - in just broken the whole time?
yep.

**Comment by jan--f** [comment]
Regarding the broken states with dashes: I got the original list of pg states from [the docs](http://docs.ceph.com/docs/master/rados/operations/pg-states/), so if this is a legitimate bug, the docs need a fix as well. Happy to push a PR if its valid to just list the states from ```osd_types.cc``` in the doc page.

**Comment by jcsp** [comment]
OK -- I've just gone ahead and updated this PR to match osd_types.cc

Probably ambiguous if the docs are to be considered buggy, as those are "sort of" human readable names, but it probably is simpler to update the docs with underscores to exactly match the output of `ceph status` and prometheus exactly if you have time to do that.

**Comment by k0ste** [comment]
@jcsp, please, don't ignore my `pg_states` list. As mentodied before state `deep_scrub` is not exists, instead this - `deep`. I don't know why.

**Comment by k0ste** [comment]
@jcsp, nice.

**Comment by tchaikov** [comment]
- http://pulpito.ceph.com/kchai-2018-04-11_11:18:50-rados-wip-kefu-testing-2018-04-11-1705-distro-basic-mira/
- http://pulpito.ceph.com/kchai-2018-04-10_16:21:36-rados-wip-kefu-testing-2018-04-10-2058-distro-basic-mira/

**Pull request merged**
