### PR TITLE
mgr/volumes: create bulk data pool for new volumes

### PR DESCRIPTION
**Pull request by leonid-s-usov**
Fixes https://tracker.ceph.com/issues/61595

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by leonid-s-usov** [comment]
@ceph/cephfs

**Review by vshankar — APPROVED** [review]
LGTM

**Comment by leonid-s-usov** [comment]
jenkins test signed

**Comment by vshankar** [comment]
@leonid-s-usov There is a test workflow that each PR needs to go through before merging. Moreover, the integration run results history (known bugs, new bugs) are recorded here - https://tracker.ceph.com/projects/cephfs/wiki/Main - which is maintained by folks responsible for running integration tests (@mchangir, @rishabh-d-dave, @batrick and me) and for bug back-tracking. Furthermore, the merged commit needs a `Reviewed-by` tag mentioning the credentials (name+email) of the folks who approved the PR.

I'm not against you merging PRs, but there is a process for that which this PR did not go through. Its fine for very straightforward fixes to be merged without going through the integrations runs. This does slow down our merging process a bit, but its an process that improves our overall product stability.

Note that there is a `needs-qa` tag that added to PRs that needs testing which is generally followed across ceph, but for cephfs, we additionally use developer specific tags (wip-<>-testing{,1,2,3,..}).

**Comment by leonid-s-usov** [comment]
Sorry, I have misinterpreted your let's get this merged commends. I'll make sure to follow the procedure next time.

What would you like me to do now about this?

**Comment by vshankar** [comment]
> Sorry, I have misinterpreted your let's get this merged comment. I'll make sure to follow the procedure next time.
> 
> What would you like me to do now about this?

No problem. I'll include it in my test branch and run it thorough the relevant test. If it breaks something, we'll have to revert, else we'll backport :)

**Comment by batrick** [comment]
> Sorry, I have misinterpreted your let's get this merged comment. I'll make sure to follow the procedure next time.
> 
> What would you like me to do now about this?

For me, LGTM has always meant "looks good to me". But I guess "let's get this merged" also is the same intent :laughing:

**Comment by leonid-s-usov** [comment]
LOL i don't know how come but I was under the impression that LGTM stands for "let's get this merged". Now that I'm looking it up it appears that "looks good to me" is the common meaning. Now I know.

**Comment by vshankar** [comment]
https://pulpito.ceph.com/vshankar-2023-08-09_05:46:00-fs:volumes-wip-vshankar-testing-20230809.035933-testing-default-smithi/

**Comment by vshankar** [comment]
> https://pulpito.ceph.com/vshankar-2023-08-09_05:46:00-fs:volumes-wip-vshankar-testing-20230809.035933-testing-default-smithi/

@leonid-s-usov Tests pass. LGTM ;P

**Pull request merged**
