### PR TITLE
qa: no need to link the test/scratch to the local directories

### PR DESCRIPTION
**Pull request by lxbsz**
The xfstests-dev tool will mount the test/scratch to the local directories. The soft links here make no sense.

Signed-off-by: Xiubo Li <xiubli@redhat.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by lxbsz** [comment]
@rishabh-d-dave BTW, I saw you added this code before and why do we need to create the soft links for `test` and `scratch` ?

**Review by vshankar — APPROVED** [review]

**Review by rishabh-d-dave — COMMENTED** [review]
This change (along with some more improvements) is already part of PR #46574. See -
https://github.com/ceph/ceph/pull/46574/commits/ac6b4c6cc96a993dcf357062bec192e95d6af3a7

**Comment by rishabh-d-dave** [comment]
@vshankar @lxbsz Removing my testing label for now since a batch of PRs on this label is already being tested.

**Comment by rishabh-d-dave** [comment]
Once that batch is complete, I'll pick this PR again later.

**Comment by vshankar** [comment]
> Once that batch is complete, I'll pick this PR again later.

Sure - just ensure you don't miss it (maybe have a tbd-testing tag)?

**Comment by dparmar18** [comment]
This patch is already there in https://github.com/ceph/ceph/commit/ac6b4c6cc96a993dcf357062bec192e95d6af3a7, do we still need this PR?

**Comment by rishabh-d-dave** [comment]
@vshankar 
> > Once that batch is complete, I'll pick this PR again later.
> 
> Sure - just ensure you don't miss it (maybe have a tbd-testing tag)?

Perhaps, yes. Would the label `needs-qa` be enough?

**Comment by lxbsz** [comment]
The [qa tests](https://pulpito.ceph.com/xiubli-2023-02-23_04:29:43-fs:functional-wip-fscrypt-20230215-0834-distro-default-smithi) are running.

**Comment by vshankar** [comment]
> > This change (along with some more improvements) is already part of PR #46574. See - [ac6b4c6](https://github.com/ceph/ceph/commit/ac6b4c6cc96a993dcf357062bec192e95d6af3a7)
> 
> Sure, let me know if you want me to close this PR.

@rishabh-d-dave Let's merge this and 

> This change (along with some more improvements) is already part of PR #46574. See - [ac6b4c6](https://github.com/ceph/ceph/commit/ac6b4c6cc96a993dcf357062bec192e95d6af3a7)

Let's merge this @rishabh-d-dave since @lxbsz has already run this through relevant tests.

**Comment by vshankar** [comment]
jenkins test make check

**Review by vshankar — APPROVED** [review]

**Review by dparmar18 — APPROVED** [review]

**Review by rishabh-d-dave — APPROVED** [review]

**Comment by vshankar** [comment]
@rishabh-d-dave Is this change still relevant after your PR (which had a similar commit) is merged now?

**Comment by rishabh-d-dave** [comment]
> @rishabh-d-dave Is this change still relevant after your PR (which had a similar commit) is merged now?

This same as 053a1fb8516e7fe6fb4160ebdf8c17b8cc35b71a that was merged recently.

**Pull request closed without merging**
