### PR TITLE
cephadm: bump default keepalived image to 2.2.4

### PR DESCRIPTION
**Pull request by adk3798**
Now that we have a keepalived 2.2.4 image pushed to https://quay.io/repository/ceph/keepalived?tab=tags, we should try to use it.

Fixes: https://tracker.ceph.com/issues/51971

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Review by mgfritch — APPROVED** [review]
Is this Dockerfile still in use? Should it be removed or updated?
https://github.com/ceph/ceph/blob/6c5f7194181a6f2227cb72099d1208cb60df2efb/src/cephadm/containers/keepalived/Dockerfile#L7

cc @guits

**Review by rkachach — APPROVED** [review]
LGTM

**Comment by guits** [comment]
> Is this Dockerfile still in use? Should it be removed or updated?
> 
> https://github.com/ceph/ceph/blob/6c5f7194181a6f2227cb72099d1208cb60df2efb/src/cephadm/containers/keepalived/Dockerfile#L7
> 
> cc @guits

Hi @mgfritch I'm gonna update it

**Comment by adk3798** [comment]
https://pulpito.ceph.com/adking-2023-03-15_01:34:51-orch:cephadm-wip-adk-testing-2023-03-14-1905-distro-default-smithi/

reruns of failed/dead jobs: https://pulpito.ceph.com/adking-2023-03-30_12:19:06-orch:cephadm-wip-adk-testing-2023-03-28-1716-distro-default-smithi/

After reruns, 6 failures:

- 2 failed staggered upgrade test, combination of https://tracker.ceph.com/issues/58535 plus the attempted fix not working
- 2 failed nfs-keepalive-only tests, newly added by a PR in the run, and not an issue in terms of merging any other PR
- 1 instance of https://tracker.ceph.com/issues/49287 (known issue)
- 1 failure in test_nfs task. The failure only happens in the test variation with the agent on (https://pulpito.ceph.com/adking-2023-03-29_11:57:55-orch:cephadm-wip-adk-testing-2023-03-28-1716-distro-default-smithi/7225304 passed) so I believe this is a timing thing related to the agent. Nothing to block merging on anything not specifically related to nfs.

**Pull request merged**
