### PR TITLE
qa: erasure-code benchmark plugin selection

### PR DESCRIPTION
**Pull request by dachary**

### CODE REVIEW

**Comment by dachary** [comment]
@apeters1971 would you have time to look at this pull request ?

**Comment by apeters1971** [comment]
Yes, will do it today! Cheers Andreas.

**Comment by dachary** [comment]
@apeters1971 thanks, much appreciated :-)

**Comment by apeters1971** [comment]
Hi Loic, 
I couldn't see in the code where you actually apply "--erasure-code-dir=<>". Did you evt. miss a commit? Because I don't see that the benchmark tool lists this as on option?

**Comment by dachary** [comment]
@apeters1971 because erasure_code_dir is part of the standard configuration options, it can be set using the existing options parsing code with no extra work :-) https://github.com/ceph/ceph/blob/master/src/common/config_opts.h#L41 Magic !

**Comment by apeters1971** [comment]
Ah thanks. I could have grepped for it ;-) ... 
What about the SHEC plug-in?

Otherwise it looks all fine to me!

**Comment by dachary** [comment]
@apeters1971 the shec and lrc plugins are derived from either isa or jerasure. They should have their individual benchmark to compare recovery speed and bandwidth. But that's another story :-)

**Comment by dachary** [comment]
@liewegas I don't think any lines of this patch are exercised by ceph-qa-suite. Do you have something in mind ?

**Comment by liewegas** [comment]
Oh.. nope! In that case merge at will.

**Pull request merged**
