### PR TITLE
osd: Log audit

### PR DESCRIPTION
**Pull request by badone**
Review current log messages for consistency, accuracy and necessesity as
part of usability initiative. First in a series.

Signed-off-by: Brad Hubbard <bhubbard@redhat.com>

### CODE REVIEW

**Comment by badone** [comment]
@jdurgin how's this for a start?

**Comment by gregsfortytwo** [comment]
I didn't read all the messages, but I don't think function names should be contained in any information going to the central log for admin consumption. Requiring knowledge of what a "past interval" means is bad enough. :/

**Comment by badone** [comment]
Thanks @gregsfortytwo, wondering about these then?

https://github.com/ceph/ceph/blob/master/src/osd/PrimaryLogPG.cc#L3646-#L3661

**Comment by badone** [comment]
Then there's the ones that sneak out such as from read_log_and_missing via PG::read_state.

**Comment by gregsfortytwo** [comment]
Given the complaint is our existing logs don't make much sense, it's probably best not to take them as a standard. ;)

**Comment by badone** [comment]
All suggestions for improving them gratefully accepted :)

**Comment by liewegas** [comment]
I agree with @gregsfortytwo that we don't want __func__ in clog messages.  Thanks for looking at these!

**Comment by badone** [comment]
@liewegas yeah, Josh said the same so it's fairly unanimous :) I'll get this fixed up and push it again, thanks guys!

**Comment by badone** [comment]
@gregsfortytwo @liewegas @jdurgin Reverted the "__func__" additions. Would appreciate a fresh review of the remaining changes.

**Comment by badone** [comment]
Jenkins retest this please.

**Comment by badone** [comment]
I've fixed the tests that were failing due to pattern matching on the old log output. There are some qa tests that need fixing as well but I'd like to get some feedback first to see whether these changes will go ahead as is.

**Comment by liewegas** [comment]
This looks fine to my.  My preference is probably not to include the ":" in there (not really necessary) but I don't feel strongly about it!

**Comment by badone** [comment]
@liewegas a quick "straw poll" says the weight of numbers side with you.

$ ag --nofilename '__func__ << ":'|wc
   1162   12786   70732
$ ag --nofilename '__func__ << " '|wc
   3413   40630  225754

I'll change this back since I think consistency is an important part of the equation. Thanks!

**Comment by badone** [comment]
The files are still inconsistent in the ":" versus no ":" regard but I wanted to restrict changes to what I've already "touched" for this PR. I will revisit these files and address the remaining inconsistencies in a future commit.

**Comment by wjwithagen** [comment]
@badone 
Hi Brad,

If you are trying to get gthings consistent ...

Could you also look at #15261 where we changed __func__ into __FUNC__ as macro.
This allows you to change the layout of the logging prefix if needed for the whole file at once, which I find very helpful during debugging certain files and functions.

**Comment by badone** [comment]
@wjwithagen oh wow, and that PR goes back to ": " format which @liewegas would prefer not to have and which I just removed from this PR. Seems like this is an inconsistent mess. Worth a ML thread and a note in https://github.com/ceph/ceph/blob/master/CodingStyle about what the preferred format should be?

Sigh... Jenkins retest this please

**Comment by badone** [comment]
Closing this as it has succumbed to "feature creep" I'll create a new PR that is more targeted and faithful to the initial task description and work out from there.

**Comment by wjwithagen** [comment]
@badone 
Well at least now it should be in just one simple `#define` where the code is going to change.
And I'm not picky in `;` of `()`, but I find function name and linenumber informative to actually trace back the code where it originates. Same as running the shell tests, and then print the line in the file..

**Pull request closed without merging**
