### PR TITLE
ceph-volume tests.functional add notario dep for ceph-ansible

### PR DESCRIPTION
**Pull request by alfredodeza**
All functional tests are failing because this is missing

### CODE REVIEW

**Comment by alfredodeza** [comment]
This is now displaying a bunch of validation errors from ceph-ansible, lets not merge this until I can verify we need fixes there as well.

**Comment by alfredodeza** [comment]
This is now good to be merged. I think that it is better to consume whatever exists in requirements.txt from ceph-ansible so that when dependencies change there we aren't affected like we are today.

**Comment by andrewschoen** [comment]
jenkins test ceph-volume lvm bluestore create

**Comment by alfredodeza** [comment]
jenkins test ceph-volume lvm all

**Comment by alfredodeza** [comment]
jenkins test ceph-volume lvm all

**Comment by alfredodeza** [comment]
All bionic ones should get ignored.

**Comment by alfredodeza** [comment]
Tried installing requirements.txt from ceph-ansible, but that installs the latest Ansible (2.5.3 at the moment) which doesn't really work with ceph-ansible (see https://github.com/ceph/ceph-ansible/issues/2629) 

Reverting back to just adding the deps manually, since Ansible 2.4 just works.

**Pull request merged**
