### PR TITLE
ObjectCacher: don't loop the extents of OSDWrite in map_write

### PR DESCRIPTION
**Pull request by wonzhq**

### CODE REVIEW

**Comment by wonzhq** [comment]
The changes in `map_write` and `map_read` are just removing the outer for loop and some indention. Github doesn't show it well.

**Comment by dachary** [comment]
please ignore the bot failure, it's a false negative

**Comment by liewegas** [comment]
@jdurgin @dillaman would one of you mind looking at this one?

**Comment by dachary** [comment]
@wonzhq could you please rebase and repush ?

**Comment by yuyuyu101** [comment]
@dillaman ping

**Comment by dillaman** [comment]
@wonzhq ping

**Comment by yuyuyu101** [comment]
@wonzhq need rebase

**Comment by dillaman** [comment]
Testing passed -- will merge post-jewel

**Pull request merged**
