### PR TITLE
Missing "std::" in kvstore_tool.h

### PR DESCRIPTION
**Pull request by jonesmz**
## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by tchaikov** [comment]
@jonesmz  hi Michael, could you add a "`Signed-off-by`" line at the end of your commit message? "git commit -s" will do the trick for you. see https://github.com/ceph/ceph/blob/master/SubmittingPatches.rst#sign-your-work

also, 
could you prefix the title of your commit message with the subcomponent your are changing ? see https://github.com/ceph/ceph/blob/master/SubmittingPatches.rst#3-describe-your-changes, in this case, it would be "tools/kvstoret-tool: ".

and the title of the commit message reads like a bug report. ideally, the title of the commit message should use the imperative mood. see also https://github.com/ceph/ceph/blob/master/SubmittingPatches.rst#3-describe-your-changes . please use `git commit --amend`  and `git push -f` for revising the commit message and its title.

**Comment by jonesmz** [comment]
No can do.

This was edited directly on github. And fixes one of the many compile errors that comes from disabling blue store when configuring the cmake build.

Merge it or don't. I don't care. Its still a bug in the code.

**Comment by tchaikov** [comment]
in that case, i am closing this PR. thanks for your contribution.

**Comment by tchaikov** [comment]
#42235 is created to address this issue.

**Pull request closed without merging**
