### PR TITLE
mds : enable fragmentation of stray dir when conditions are met

### PR DESCRIPTION
**Pull request by simon-rock**
when select a stray, fragment a stray that meets the criteria at the same time

Signed-off-by: Simon Gao <simon29rock@gmail.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by batrick** [comment]
Are you aware of #31521? We have a tracker issue for this: https://tracker.ceph.com/issues/41782

**Comment by batrick** [comment]
cc @mchangir

**Comment by simon-rock** [comment]
> Are you aware of #31521? We have a tracker issue for this: https://tracker.ceph.com/issues/41782

@batrick  no. The customer produced this problem in our cluster. 
I find some logic of mds that assume strays never fragment. so I want fragment it when we choose the next stray.

**Comment by ukernel** [comment]
this one is supplement to https://github.com/ceph/ceph/pull/31521

**Comment by batrick** [comment]
@ukernel Let's keep everything in a single PR. Pull what we want out of #31521 into this PR.

Are the QA tests @mchangir wrote sufficient?

**Comment by gregsfortytwo** [comment]
@ukernel what's the story between this and #31521 now?

**Comment by ukernel** [comment]
#31521 is incomplete.

**Comment by gregsfortytwo** [comment]
http://pulpito.front.sepia.ceph.com/gregf-2020-04-01_18:45:43-fs-wip-greg-testing-41-distro-basic-smithi/

**Comment by gregsfortytwo** [comment]
http://pulpito.front.sepia.ceph.com:80/gregf-2020-04-02_05:22:31-fs-wip-greg-testing-41-3-distro-basic-smithi/
Try, try again — Zheng attributes these failures to https://tracker.ceph.com/issues/44904 so I'll fix that up...

**Comment by ukernel** [comment]
http://pulpito.ceph.com/zyan-2020-04-22_06:14:53-fs-wip_zyan_simon_split_stray-distro-basic-smithi/

**Pull request merged**
