### PR TITLE
#12137: cephfs-data-scan scan_frags

### PR DESCRIPTION
**Pull request by jcsp**
This is the basic version (no fragmented dirs) that lets us repair a system where we've somehow lost the linkage to a directory.

### CODE REVIEW

**Comment by ukernel** [comment]
the reset looks good

**Comment by jcsp** [comment]
(NB jenkins failure because this depends on https://github.com/ceph/ceph/pull/5685)

**Comment by jcsp** [comment]
This is done, but it'll wait for merge until it's tested alongside https://github.com/ceph/ceph/pull/5919

**Comment by gregsfortytwo** [comment]
Did the testing get done on this? I'm not seeing any results here nor on #5919 (which is still labeled DNM)

**Pull request merged**
