### PR TITLE
jewel: osd: Remove extra call to reg_next_scrub() during splits

### PR DESCRIPTION
**Pull request by dzafman**
http://tracker.ceph.com/issues/17666

### CODE REVIEW

**Comment by dzafman** [comment]
jenkins test this please

**Comment by dzafman** [comment]
@dachary Ready for this or the next Jewel release.

**Comment by dachary** [comment]
jenkins test this please

**Comment by dachary** [comment]
@dzafman  could you please rebase against jewel-next ? A number of backports have been merged since the last check and it would be good to get another make check with a more recent rebase.

**Comment by dachary** [comment]
jenkins test this please (jenkins general failure)

**Comment by dzafman** [comment]
jenkins test this please (jenkins general failure)

**Comment by dzafman** [comment]
@dachary It passed this time.

**Comment by dachary** [comment]
\o/

**Comment by dachary** [comment]
It passed the rados (http://tracker.ceph.com/issues/17851#note-4) suite. It also passed the upgrade/jewel-x and upgrade/hammer-x (http://tracker.ceph.com/issues/17851#note-7) suites, except for one job which should be fixed by https://github.com/ceph/ceph-qa-suite/pull/1256 and does not seem related to this pull request. Note that it won't be included in 10.2.4, reason why it targets jewel-next.

**Pull request merged**
