### PR TITLE
octopus: cephadm batch backport August (1)

### PR DESCRIPTION
**Pull request by sebastian-philipp**
Backport of #35374, #35667, #36225, #35839, #36239, #36301, #36262, #36012, #36285, #36235, #36217, #35728, #36232, #36162, #36334, #36335, #36286, #36374, #36284, #36338, #36151, #36360, #36348, #36407, #36356, #36386, #36375, #36383, #36388, #36391, #36441, #36433

### Conflicts:

commit 19df5b7cd0a486883780eef18fd84c26866ff873
mgr/cephadm: Introduce tox and autopep8
Conflicts:
  src/pybind/mgr/tox.ini

---

commit 2d3a5440bfa45f57ff4ac993d7a2e045d6bfdeac
mgr/osd_support: remove module and all traces
Conflicts:
  src/mon/MgrMonitor.cc

---
commit ed0fa3cfa41622d44adac41952547f0d27ee3ea4
cephadm: use src/mypy.ini instead
Conflicts:
  src/cephadm/tox.ini

--- 

commit 7cbaadfd718f377bcd2d909df093e4350022866d
mgr/cephadm: rework --dry-run/previews
Conflicts:
  src/pybind/mgr/orchestrator/module.py

### CODE REVIEW

**Comment by sebastian-philipp** [comment]
and removed `ceph-volume: add drive-group subcommand`

**Comment by sebastian-philipp** [comment]
Blocked by ceph/ceph-container#1706

**Comment by tserong** [comment]
This mentions #35728 in the description, but AFAICT doesn't include the commit from that PR

**Comment by jan--f** [comment]
@tserong The backport for this was just merged in #36558

**Comment by tserong** [comment]
Thanks @jan--f !

**Pull request merged**
