### PR TITLE
doc: release-notes: add missing hammer releases

### PR DESCRIPTION
**Pull request by smithfarm**
Signed-off-by: Nathan Cutler <ncutler@suse.com>

### CODE REVIEW

**Comment by smithfarm** [comment]
added DNM until I can add the `.txt` files

**Comment by dachary** [comment]
<pre>
Reviewed-by: Loic Dachary &lt;ldachary@redhat.com>
</pre>

**Comment by smithfarm** [comment]
@dachary Do we need all these changelogs (see the commit I just added), too?

**Comment by dachary** [comment]
@smithfarm it's nice to have, I think

**Pull request merged**
