### PR TITLE
[DNM] librbd: helping to implement new 'journal' feature

### PR DESCRIPTION
**Pull request by trociny**

### CODE REVIEW

**Comment by trociny** [comment]
Jason, thank you for your comments. I think I addressed them all.

**Comment by dillaman** [comment]
@trociny The journal library has merged upstream.  Can you open a new PR containing just your journal library updates?

**Comment by trociny** [comment]
@dillaman https://github.com/ceph/ceph/pull/6552

**Comment by jdurgin** [comment]
Merged the librbd journal integration - could you rebase?

**Comment by trociny** [comment]
@jdurgin I have created a new branch against the resent master (with merged librbd journal integration). It includes these patches and some my other recent work:

https://github.com/trociny/ceph/tree/wip-librbd-journal

I have not created a pool request yet, because I am observing some issue I want to investigate before. I hope it wont require much time.

**Comment by trociny** [comment]
@jdurgin @dillaman https://github.com/ceph/ceph/pull/6665

**Pull request closed without merging**
