### PR TITLE
mgr: fix invalid escape sequence

### PR DESCRIPTION
**Pull request by kshtsk**
Get rid of DepricationWarning which according to https://docs.python.org/3.11/library/re.html
is going to become a SyntaxError.

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [x] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Review by phlogistonjohn — APPROVED** [review]
Changes look good ot me. Hopefully nothing was relying on these regexes being implemented wrong ;-)

**Comment by phlogistonjohn** [comment]
I suggest @adk3798 include this in an orch teuthology run.

**Comment by adk3798** [comment]
jenkins test make check

**Comment by kshtsk** [comment]
so can we merge it already?

**Comment by adk3798** [comment]
https://pulpito.ceph.com/adking-2024-08-04_22:17:13-orch:cephadm-wip-adk-testing-2024-08-02-0919-distro-default-smithi/7836436

Failures:

- mds_upgrade_sequence, known issue
- staggered upgrade `ceph versions` and `ceph orch ps` mismatch, known issue
- `ceph orch apply nvmeof foo` failure due to PR in the run (that made a group name required for that command)
- test_monitoring_stack test was broken by update of the monitoring stack component versions, known issue
- 2 tests failed with kernel installs, infra/teuthology failure, unrelated to PRs in the run

**Comment by kshtsk** [comment]
thank you

**Pull request merged**
