### PR TITLE
rgw: lock is not released when set sync marker is failed.

### PR DESCRIPTION
**Pull request by zhangsw**
Signed-off-by: Zhang Shaowen <zhangshaowen@cmss.chinamobile.com>

### CODE REVIEW

**Comment by cbodley** [comment]
the fix looks correct, but i'd prefer not to include the whitespace changes

**Comment by zhangsw** [comment]
@cbodley done.

**Comment by cbodley** [comment]
opened https://github.com/ceph/ceph/pull/12223 for the related fix

**Comment by cbodley** [comment]
I created a tracker issue for this so we can get it backported to jewel - can you please add this line to your commit message?
```
Fixes: http://tracker.ceph.com/issues/18077
```

**Comment by zhangsw** [comment]
@cbodley your analysis is pretty right~I have added that line to my commit message.

**Comment by dachary** [comment]
jenkins test this please (https://jenkins.ceph.com/job/ceph-pull-requests/15086/ has readable.sh error)

**Comment by yuriw** [comment]
ready for merge http://pulpito.ceph.com/yuriw-2017-07-12_19:38:07-rgw-wip-yuri-testing2_2017_7_12_2-distro-basic-smithi/

**Pull request merged**
