### PR TITLE
mgr/rook: host add label in rook orchestrator

### PR DESCRIPTION
**Pull request by josephsawaya**
This PR adds the functionality for adding labels to hosts
using the rook orchestrator and orch host label add. The labels
are added to the kubernetes node object as kubernetes labels.

Signed-off-by: Joseph Sawaya <jsawaya@redhat.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Review by jmolmo — APPROVED** [review]
LGTM. 

Lest discuss one additional question in the orch meeting:

When you execute "ceph orch host ls" we are showing all the labels attached to each host.. this includes all the k8s labels... maybe we can show only the labels generated by the orchestrator layer ,, all the labels like "ceph-label/*".

**Comment by liewegas** [comment]
> LGTM.
> 
> Lest discuss one additional question in the orch meeting:
> 
> When you execute "ceph orch host ls" we are showing all the labels attached to each host.. this includes all the k8s labels... maybe we can show only the labels generated by the orchestrator layer ,, all the labels like "ceph-label/*".

Yeah.  If the ceph label is 'foo', then the k8s label is ceph-label/foo, right?  Which means that 'ceph orch host ls' should only show 'foo'?  I think excluding anything that doesn't start with ceph-label/ is a required in order to make things match up...

**Comment by liewegas** [comment]
Should probably implement remove_host_label at the same time?

**Comment by liewegas** [comment]
tests look ok (multinode still failing for unrelated reasons): https://pulpito.ceph.com/sage-2021-09-09_14:42:01-orch:rook-wip-sage-testing-2021-09-08-1213-distro-basic-smithi/

**Comment by liewegas** [comment]
i.e., something like this https://github.com/ceph/ceph/blob/master/qa/suites/orch/cephadm/smoke-roleless/2-services/client-keyring.yaml#L1-L4 (plus a grep to verify it worked, and a remove, and another grep -v, etc.) in this directory https://github.com/ceph/ceph/tree/master/qa/suites/orch/rook/smoke/2-workload

**Review by jmolmo — APPROVED** [review]
Now it seems very complete!

**Pull request merged**
