### PR TITLE
octopus: ceph-volume: major batch refactor

### PR DESCRIPTION
**Pull request by jan--f**
This is an untracked backport

---

backport of:

* [x] #34740
* [x] #37498 
* [x] #37524
* [x] #37531
* [x] #37545
* [x] #37577 
* [x] #37591

### CODE REVIEW

**Comment by jan--f** [comment]
jenkins test ceph-volume all

**Comment by jan--f** [comment]
jenkins test ceph-volume tox

**Comment by smithfarm** [comment]
@jan--f This octopus backport PR has 27 commits, which si 4 less than the corresponding master PR #34740 

Could you explain this discrepancy in the PR description, please?

**Comment by jan--f** [comment]
> @jan--f This octopus backport PR has 27 commits, which si 4 less than the corresponding master PR #34740
> 
> Could you explain this discrepancy in the PR description, please?

Thank you! My mistake in backporting. Fixed now.

**Comment by jan--f** [comment]
jenkins test ceph-volume tox

**Comment by jan--f** [comment]
jenkins test ceph-volume all

**Comment by jan--f** [comment]
I'll also add the backports for #37498 and #37524 here once the PRs are merged.

**Comment by smithfarm** [comment]
> I'll also add the backports for #37498 and #37524 here once the PRs are merged.

OK. Added a checklist to the PR description.

**Comment by smithfarm** [comment]
Also added #37545 to the PR description.

**Comment by smithfarm** [comment]
The changes being backported to octopus by this PR are implicated in https://tracker.ceph.com/issues/47760

(Added an entry to the to-do list.)

**Comment by jan--f** [comment]
jenlins test make check

**Comment by smithfarm** [comment]
I can confirm that this PR does introduce https://tracker.ceph.com/issues/47760 when applied on top of octopus. 

It would be great if the fix for https://tracker.ceph.com/issues/47760 could be backported to octopus right here in this PR.

**Comment by jan--f** [comment]
jenkins test make check

**Comment by jan--f** [comment]
jenkins test make check

**Comment by jan--f** [comment]
jenkins test ceph-volume all

**Comment by jan--f** [comment]
jenkins test ceph-volume tox

**Review by rishabh-d-dave — APPROVED** [review]

**Pull request merged**
