### PR TITLE
DNM: jewel: rbd mirror: after promote, the mirror image often be up+error

### PR DESCRIPTION
**Pull request by dachary**
http://tracker.ceph.com/issues/17065

### CODE REVIEW

**Comment by dachary** [comment]
<pre>
librbd/Journal.cc: In instantiation of 'static int librbd::Journal<ImageCtxT>::create(librados::IoCtx&, const string&, uint8_t, uint8_t, const string&, bool, const string&) [with ImageCtxT = librbd::ImageCtx; std::string = std::basic_string<char>; uint8_t = unsigned char]':
librbd/Journal.cc:1847:24:   required from here
librbd/Journal.cc:387:57: error: no matching function for call to 'allocate_journaler_tag(CephContext*&, librbd::Journal<librbd::ImageCtx>::Journaler*, cls::journal::Client&, const uint64_t&, librbd::journal::TagData&, std::string&, cls::journal::Tag*)'
                              tag_data, mirror_uuid, &tag);
                                                         ^
librbd/Journal.cc:387:57: note: candidate is:
librbd/Journal.cc:216:5: note: template<class J> int librbd::{anonymous}::allocate_journaler_tag(CephContext*, J*, const cls::journal::Client&, uint64_t, const librbd::journal::TagPredecessor&, const string&, cls::journal::Tag*)
</pre>

**Comment by dachary** [comment]
repushed after a rebase, in case the latest rbd related merges improve the situation

**Comment by dachary** [comment]
Same compilation error, needs fixing.

**Comment by dillaman** [comment]
@dachary I'll open up a new PR for this one as it will require custom code on the jewel branch since it has diverged from master (and I am not ready to backport the large change)

**Comment by dillaman** [comment]
Compile error fixed under PR #11241

**Pull request closed without merging**
