### PR TITLE
Updates radosgw man page with configuration for mod_proxy_fcgi

### PR DESCRIPTION
**Pull request by nilamdyuti**

### CODE REVIEW

**Comment by yehudasa** [comment]
@johnwilkins ping

**Comment by dachary** [comment]
@nilamdyuti would you be so kind as to rebase your commits ?

**Comment by nilamdyuti** [comment]
@dachary Done. Thanks!

**Comment by dachary** [comment]
@nilamdyuti sorry for being picky but ... would you mind squashing these into fewer commits ? Maybe one commit per rst file ? It will help with backporting.

**Comment by nilamdyuti** [comment]
@dachary I have removed the extra commits that came due to rebasing and resolving merge conflicts. The number of commits are less now. I hope they are good to be merged. Let me know if any change is required.

**Comment by dachary** [comment]
That looks nice and clean @nilamdyuti. I can only speak for the formal aspect of the pull request though: my rgw knowledge is very limited ;-) @theanalyst would you have time to review these changes ?

**Comment by nilamdyuti** [comment]
@dachary Thanks! :) Lets see if there are more changes to implement after the review.

**Comment by theanalyst** [comment]
overall looks good.

 One undocumented option in quota options for radosgw-admin tool is `--max-buckets` which can be used to set buckets quota for a user, this however is missing in ceph/rgw docs and help options as well, since you are updating everything else, probably this can be updated as well (created #10184 in tracker for this)

**Comment by dachary** [comment]
@theanalyst #10184 be worked on in another pull request ? Or is there a reason to not merge this pull request until it's done ?

**Comment by theanalyst** [comment]
@dachary yeah it can be done seperately, this can be merged.. I remembered about the issue after reading the manpage :)

**Pull request merged**
