### PR TITLE
docs: Update au.ceph.com maintainers, update README.md.

### PR DESCRIPTION
**Pull request by mty22**
mirrors: Update au.ceph.com maintainers, update README.md.

* Update au.ceph.com maintainers
* Update README.md to include mailing list information.

Signed-off-by: Matthew Taylor <matt@mty.net.au>

### CODE REVIEW

**Comment by mty22** [comment]
retest this please

**Comment by mty22** [comment]
test docs

**Comment by mty22** [comment]
All good now @batrick, thank you. :)

**Comment by mty22** [comment]
Is there anything blocking this merge? 

The 'make check' failed, although it is unrelated since it's a documentation change.

**Comment by tchaikov** [comment]
@mty22 nothing is blocking this change. i was just waiting for the test to complete.

**Pull request merged**
