### PR TITLE
do_cmake.sh: build with python3.10 on ubuntu version >= 22.0

### PR DESCRIPTION
**Pull request by ljflores**
Ubuntu 22.04 should be built with Python 3.10. Since we've updated jenkins nodes to 22.04, Pacific PRs seem to be using older python versions when running cmake, which causes failures like:

```
CMake Error at /usr/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find Python3 (missing: Python3_LIBRARY Python3_INCLUDE_DIR
  Development) (found suitable exact version "3.8.10")
Call Stack (most recent call first):
  /usr/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  cmake/modules/FindPython/Support.cmake:1181 (find_package_handle_standard_args)
  cmake/modules/FindPython3.cmake:181 (include)
  CMakeLists.txt:477 (find_package)
```

Although this version mixup primarily affects Pacific PRs, I think it makes sense to enforce this on all branches.

Fixes: https://tracker.ceph.com/issues/57230
Signed-off-by: Laura Flores <lflores@redhat.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by ljflores** [comment]
I think it would make sense to enforce this on all branches. That said, I am only really seeing this on braggi14 (https://jenkins.ceph.com/computer/172.21.2.14%2Bbraggi14/builds), Pacific PRs.

@tchaikov let me know if this makes sense to enforce.

**Comment by ljflores** [comment]
The failure can be recreated by installing Python 3.8 on Ubuntu 22.04, and then running ./do_cmake.sh.

**Comment by ljflores** [comment]
Also seems to help failures tracked in https://tracker.ceph.com/issues/57229.

See https://github.com/ceph/ceph/pull/47744, where the fix is shown to successfully complete do_cmake.sh. (make check and API fail due to another problem).

**Comment by ljflores** [comment]
jenkins test api

**Comment by ljflores** [comment]
jenkins test api

**Comment by ljflores** [comment]
A better fix might already be in #47696. @tchaikov @tserong if this is the case, use the above Tracker for your PR and close this one out.

**Review by tchaikov — APPROVED** [review]

**Comment by tchaikov** [comment]
I think this is the fix — we need to enforce the python version if the distro provides more than one python versions to user. But regarding the issue fixed by the change, I am confused. As, IMHO, CMake is unlikely to detect and use an older python if a newer is also installed.

**Comment by tchaikov** [comment]
also the title can be improved, what we are enforcing is the python version, not ubuntu version, so probably could reword it like:

> build with python3.10 on ubuntu version >= 22.0

**Review by tserong — APPROVED** [review]

**Comment by tserong** [comment]
> But regarding the issue fixed by the change, I am confused. As, IMHO, CMake is unlikely to detect and use an older python if a newer is also installed.

Yeah, it's definitely weird. Maybe (wild guess) both python versions are installed but only the devel bits for one version are installed and that confuses things?

**Comment by ljflores** [comment]
Force-pushed just to amend the commit title.

@tchaikov @tserong I agree-- the failure is definitely weird. So far, I've only seen it happen on braggi14, so whatever the configuration there is causing the problem.

**Comment by ljflores** [comment]
jenkins test make check

**Comment by ljflores** [comment]
jenkins test api

**Comment by tchaikov** [comment]
```
2022-08-23 22:19:55,924.924 INFO:__main__:ERROR: test_clone_role (tasks.mgr.dashboard.test_role.RoleTest)
2022-08-23 22:19:55,924.924 INFO:__main__:----------------------------------------------------------------------
2022-08-23 22:19:55,924.924 INFO:__main__:Traceback (most recent call last):
2022-08-23 22:19:55,924.924 INFO:__main__:  File "/home/jenkins-build/build/workspace/ceph-api/qa/tasks/mgr/dashboard/helper.py", line 271, in setUp
2022-08-23 22:19:55,924.924 INFO:__main__:    self.wait_for_health_clear(self.TIMEOUT_HEALTH_CLEAR)
2022-08-23 22:19:55,924.924 INFO:__main__:  File "/home/jenkins-build/build/workspace/ceph-api/qa/tasks/ceph_test_case.py", line 175, in wait_for_health_clear
2022-08-23 22:19:55,924.924 INFO:__main__:    self.wait_until_true(is_clear, timeout)
2022-08-23 22:19:55,924.924 INFO:__main__:  File "/home/jenkins-build/build/workspace/ceph-api/qa/tasks/ceph_test_case.py", line 212, in wait_until_true
2022-08-23 22:19:55,924.924 INFO:__main__:    raise TestTimeoutError("Timed out after {0}s and {1} retries".format(elapsed, retry_count))
2022-08-23 22:19:55,924.924 INFO:__main__:tasks.ceph_test_case.TestTimeoutError: Timed out after 60s and 0 retries
```

**Comment by tchaikov** [comment]
```
openapi-check run-test: commands[1] | diff openapi.yaml /home/jenkins-build/build/workspace/ceph-pull-requests/src/pybind/mgr/dashboard/.tox/openapi-check/tmp/openapi.yaml
10483c10483
< - description: Get Cluster Details
---
> - description: Get Ceph Users
ERROR: InvocationError for command /usr/bin/diff openapi.yaml .tox/openapi-check/tmp/openapi.yaml (exited with code 1)
```

**Comment by tchaikov** [comment]
jenkins test make check

**Comment by tchaikov** [comment]
jenkins test api

**Comment by tchaikov** [comment]
the failures are not likely related. but i want to see if they are reproducible.

**Comment by ljflores** [comment]
@tchaikov there are lots of make check / api failures right now 😕.

**Comment by ljflores** [comment]
jenkins test make check

**Comment by ljflores** [comment]
jenkins test api

**Comment by ljflores** [comment]
jenkins test make check

**Comment by ljflores** [comment]
jenkins test make check

**Comment by ljflores** [comment]
jenkins test api

**Comment by rzarzynski** [comment]
```
ERROR:   py3: commands failed
SKIPPED:  py37: InterpreterNotFound: python3.7
  mypy: commands succeeded
  flake8: commands succeeded
  jinjalint: commands succeeded
  nooptional: commands succeeded

        Start   3: teardown-venv-for-mgr
280/282 Test   #3: teardown-venv-for-mgr .....................   Passed    0.33 sec
281/282 Test #244: unittest-transaction-manager ..............   Passed  886.58 sec
282/282 Test #144: check-generated.sh ........................   Passed  1295.50 sec

99% tests passed, 1 tests failed out of 282

Total Test time (real) = 1297.18 sec

The following tests FAILED:
	  4 - run-tox-mgr (Failed)
Errors while running CTest
+ sleep 5
```

**Comment by rzarzynski** [comment]
jenkins test make check

**Comment by ljflores** [comment]
jenkins test make check

**Comment by ljflores** [comment]
jenkins test make check

**Comment by ljflores** [comment]
jenkins test make check

**Comment by ljflores** [comment]
Passing make check! I'll merge this since it's gotten approvals.

**Pull request merged**
