### PR TITLE
do_cmake.sh: build with correct python version on Rocky

### PR DESCRIPTION
**Pull request by ShimTanny**
do_cmake.sh: build with correct python version on rocky os 
Fixes: https://tracker.ceph.com/issues/57945
Signed-off-by: ShimTanny <shimon.tanny@nokia.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Review by idryomov — COMMENTED** [review]
Please change the title of the commit from "Update do_cmake.sh" to match the title of the PR so that it's immediately clear what the update is about.  Otherwise LGTM!

**Comment by ShimTanny** [comment]
Title of commit was changed.

**Review by idryomov — APPROVED** [review]

**Review by kobiginon — APPROVED** [review]
Looks good 
thanks, shimon

**Review by tchaikov — APPROVED** [review]

**Comment by rzarzynski** [comment]
from core PR scrub: @yuriw ping.

**Comment by ljflores** [comment]
jenkins test make check

**Comment by ljflores** [comment]
Rados approved: https://tracker.ceph.com/projects/rados/wiki/MAIN#httpstrellocomcBHAY6fGO1801-wip-yuri10-testing-2023-07-10-1345

**Comment by yuriw** [comment]
@ShimTanny  pls merge as soon as it passed the checks
ref: https://trello.com/c/BHAY6fGO

**Comment by ShimTanny** [comment]
make check (arm64) — make check failed - can't see details of failure 
getting 404 not found page
can't merge (no button merge)

**Review by kobigi — APPROVED** [review]

**Pull request merged**
