### PR TITLE
mgr/dashboard: refactor the order of buttons shown in forms

### PR DESCRIPTION
**Pull request by s0nea**
The PR corrects the buttons shown on forms by providing a `FormButtonPanel` component.

**After** <- **Before**
Screenshot_2020-11-18_16-15-14
Screenshot_2020-11-18_16-16-33

Fixes: https://tracker.ceph.com/issues/48016
Signed-off-by: Tatjana Dehler <tdehler@suse.com>

## Checklist
- [x] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by s0nea** [comment]
jenkins test docs

**Comment by s0nea** [comment]
jenkins test docs

**Review by nizamial09 — COMMENTED** [review]
Thank you for taking care of this @s0nea Overall looks good. One thing I noticed is there used to be a little bit more space between the submit button and cancel button. (Atleast in octopus and nautilus and it got lost somewhere in the master). Current spacing is good. But wouldn't it be good to have a little bit more space between them. What do you think @s0nea ?

This image is of nautilus.
edut

**Comment by nizamial09** [comment]
jenkins test dashboard

**Comment by s0nea** [comment]
Hey @nizamial09  I'm not really sure if I understand you correctly. Do you want me to add more space between these buttons for this PR?  Or do you mean the spacing is fine on master and needs to be fixed on octopus, nautilus, ... ?

> Thank you for taking care of this @s0nea Overall looks good. One thing I noticed is there used to be a little bit more space between the submit button and cancel button. (Atleast in octopus and nautilus and it got lost somewhere in the master). Current spacing is good. But wouldn't it be good to have a little bit more space between them. What do you think @s0nea ?
> 
> This image is of nautilus.
> edut

**Comment by nizamial09** [comment]
> Hey @nizamial09 I'm not really sure if I understand you correctly. Do you want me to add more space between these buttons for this PR? Or do you mean the spacing is fine on master and needs to be fixed on octopus, nautilus, ... ?
> 
> > Thank you for taking care of this @s0nea Overall looks good. One thing I noticed is there used to be a little bit more space between the submit button and cancel button. (Atleast in octopus and nautilus and it got lost somewhere in the master). Current spacing is good. But wouldn't it be good to have a little bit more space between them. What do you think @s0nea ?
> > This image is of nautilus.
> > edut

@s0nea I meant to add a little bit more space in this PR. Sorry if I was confusing.

**Comment by s0nea** [comment]
@nizamial09 I increased the spacing a bit. Please have a look if it's enough now :smile:

**Comment by s0nea** [comment]
jenkins test dashboard

**Review by nizamial09 — APPROVED** [review]
LGTM

**Review by CourtneyCCaldwell — APPROVED** [review]
Changes look good to me; works as expected!

**Pull request merged**
