### PR TITLE
mgr/cephadm: increase global scrape interval

### PR DESCRIPTION
**Pull request by p-se**
About scrape_interval and evaluation_interval:

> For simplicity and sanity it's best to have the two intervals the same, so I'd suggest having both as 15s here.

-- https://stackoverflow.com/questions/52167869/scrape-interval-and-evaluation-interval-in-prometheus

About recommended  scrape intervals:

> Thirdly intervals on the order of single-digit seconds is getting into profiling territory. While a metrics-based system like Prometheus can handle that in certain cases, Prometheus is not a general profiling tool and thus not the most appropriate for the job. Profiling with Prometheus takes some care in design, and is not something you always want to mix in with your general monitoring.
> 
> So what would I suggest instead? Keep things simple. Pick one scrape interval, and stick with it. Preferably not just per Prometheus, but across your team/organisation. A value in the range of 10-60s tends to be good.

-- https://www.robustperception.io/keep-it-simple-scrape_interval-id

In addition to that, the time to gather data from the Prometheus manager module on large clusters may exceed five seconds, and would with that configuration (and how the Prometheus manager module currently works) amplify the load on the manager.

Ten seconds should be a reasonable resolution, still.

Signed-off-by: Patrick Seidensal <pseidensal@suse.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by sebastian-philipp** [comment]
Argh. Irritating. Can you rename your PR to `mgr/cephadm: ...`, please?

**Comment by sebastian-philipp** [comment]
I have the impression that we'll end up adding the scrape interval to the grafana service spec.

**Comment by p-se** [comment]
> Argh. Irritating. Can you **rename your commit and PR** to `mgr/cephadm: ...`, please?

Oops, sure!

**Comment by sebastian-philipp** [comment]
http://pulpito.ceph.com/swagner-2020-05-18_08:24:15-rados-wip-swagner-testing-2020-05-15-2348-distro-basic-smithi/

succeeded (except for upgrading some OSDs and upgrading the monitoring)

**Pull request merged**
