### PR TITLE
cmake: fail on unknown attribute

### PR DESCRIPTION
**Pull request by tchaikov**
on Clang, the option for detecting unknown attribute is
-Wunknown-attributes, so "-Wattributes -Werror" does not fail the test
when the C compiler is Clang.

in this change, we just enable all warnings and turn them into errors.
this should fail the test if the compiler does not understand
`__attribute__((__symver__ ...))`

Signed-off-by: Kefu Chai <kchai@redhat.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by wjwithagen** [comment]
@tchaikov 
Just `-Werror` is enough for Clang:
```
[~/master] wjw@quad-b.digiware.nl> cc -Werror /tmp/test.c
/tmp/test.c:1:16: error: unknown attribute '__symver__' ignored [-Werror,-Wunknown-attributes]
__attribute__((__symver__ ("func@v1"))) void func_v1() {};
               ^~~~~~~~~~~~~~~~~~~~~~
/tmp/test.c:2:16: error: unknown attribute '__symver__' ignored [-Werror,-Wunknown-attributes]
__attribute__((__symver__ ("func@v2"))) void func_v2() {};
               ^~~~~~~~~~~~~~~~~~~~~~
2 errors generated.

```

**Comment by tchaikov** [comment]
@wjwithagen updated and repushed.

**Review by b-ranto — APPROVED** [review]
I originally had it this way in the PR but wanted to change it to avoid some new warnings that might come up in the future failing the check. I obviously did not take llvm into consideration there. :-/

**Review by wjwithagen — APPROVED** [review]
@tchaikov
Might want to add:
fixes: #42602
So that it also will get backported

**Comment by wjwithagen** [comment]
> 
> 
> I originally had it this way in the PR but wanted to change it to avoid some new warnings that might come up in the future failing the check. I obviously did not take llvm into consideration there. :-/

No problem.
Advantage now is that if any compiler has an issue with this test code it starts complaining.
OTOH the code is so obvious simple, small chance.

**Comment by tchaikov** [comment]
> @tchaikov
> Might want to add:
> fixes: #42602
> So that it also will get backported

i added `Fixes: https://tracker.ceph.com/issues/40060` anyway. i'd prefer not using github id if possible.

**Pull request merged**
