### PR TITLE
quincy: common: fix compilation and function issues about compressor and crypto to enable latest QAT driver

### PR DESCRIPTION
**Pull request by liumiaomiaoIntel**
backport tracker: https://tracker.ceph.com/issues/54062

---

backport of https://github.com/ceph/ceph/pull/44608
parent tracker: https://tracker.ceph.com/issues/54059

this backport was staged using ceph-backport.sh version 16.0.0.6848
find the latest version at https://github.com/ceph/ceph/blob/master/src/script/ceph-backport.sh

### CODE REVIEW

**Comment by ljflores** [comment]
http://pulpito.front.sepia.ceph.com/yuriw-2022-02-21_18:20:15-rados-wip-yuri11-testing-2022-02-21-0831-quincy-distro-default-smithi/

Failures, unrelated:
    https://tracker.ceph.com/issues/52124
    https://tracker.ceph.com/issues/50280
    https://tracker.ceph.com/issues/54337

Details:
    1. Invalid read of size 8 in handle_recovery_delete() - Ceph - RADOS
    2. cephadm: RuntimeError: uid/gid not found - Ceph
    3. Selinux denials seen on fs/rados teuthology runs - Infrastructure

**Review by ljflores — APPROVED** [review]

**Comment by liumiaomiaoIntel** [comment]
@ljflores Hi Laura, I have replaced the backport link with the auto-created backport ticket [https://tracker.ceph.com/issues/54062]( https://tracker.ceph.com/issues/54062) in this PR. Please let me know if there is anything that needs to be done.

**Comment by ljflores** [comment]
@liumiaomiaoIntel your PR passed the QA tests, so it's in good shape to be merged! Nothing more needs to be done on your side.

I've requested a review from @tchaikov since he was involved with reviewing the original PR. Kefu, if this PR looks good to you, lmk and I'll merge it.

**Review by tchaikov — APPROVED** [review]

**Comment by tchaikov** [comment]
@ljflores Hi Laura, thanks for bring this PR to my attention. looks good to me.

**Pull request merged**
