### PR TITLE
call choose_acting again in all_activated_and_committed

### PR DESCRIPTION
**Pull request by zhouyuey**
if a osd down and up frequently, may cause recovery not in asynchronous, all_activated_and_committed call choose_acting again make sure missing objects be identified, next if want_acting != acting will jump to NeedActingChange event, pg will do peering again.

Fixes: http://tracker.ceph.com/issues/56030
Signed-off-by: zhouy1@wangsu.com <zhouy1@wangsu.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by athanatos** [comment]
I don't understand the problem this is trying to solve.  Can you explain it a bit more clearly?  What state do you observe PGs becoming stuck in?  Is your observation that in some cases we are backfilling rather than going into async recovery because we went active before getting a notify from a osd with a copy of the pg with a long enough log?

**Comment by zhouyuey** [comment]
> @neha-ojha hi, ojha, look my patch if you have time :)



> I don't understand the problem this is trying to solve. Can you explain it a bit more clearly? What state do you observe PGs becoming stuck in? Is your observation that in some cases we are backfilling rather than going into async recovery because we went active before getting a notify from a osd with a copy of the pg with a long enough log?



> I don't understand the problem this is trying to solve. Can you explain it a bit more clearly? What state do you observe PGs becoming stuck in? Is your observation that in some cases we are backfilling rather than going into async recovery because we went active before getting a notify from a osd with a copy of the pg with a long enough log?

Thank you for your reply,
there are enough PG logs for recovery, i set osd_async_recovery_min_cost = 0 hope async recovery anyway.
continuous background write, i down a osd a short time, when it comeback the pg in active+recovering+undersized+degraded+remapped state, ceph pg $pgid query can see async_recovery_targets contains this fault osd id, this is normal, but if down/up this osd frequently, sometime pg in active+recovering+degraded or active+recovering state, ceph pg $pgid query async_recovery_targets is empty, i think pg is not in async recovery mode, this will block op in do_op()/id_degraded_or_backfilling_object()

i added more log, it's too big, so divided into three parts, you can see it in https://tracker.ceph.com/issues/56030 @athanatos

**Comment by athanatos** [comment]
all_activated_committed is a strange place to do this.  If this is important, perhaps it should be in the MNotifyRec handler?  I'm skeptical about this generally, though.  By the time we've chosen to go active, we've completed peering and I'm really not sure it's worth restarting peering to avoid a few synchronous recovery operations.  It's also more complicated.

**Comment by sunxm123** [comment]
after GetMissing , pg info can calc the right num_missing , then peering go on to Activate ,  there  choose_acting again , know the osd have num_missing choose as async target , this help  rgw bucket index recovery  as backfill , prevent block client op

**Comment by zhouyuey** [comment]
> all_activated_committed is a strange place to do this. If this is important, perhaps it should be in the MNotifyRec handler? I'm skeptical about this generally, though. By the time we've chosen to go active, we've completed peering and I'm really not sure it's worth restarting peering to avoid a few synchronous recovery operations. It's also more complicated.

yes, it is not very necessary for general osd, but for the bucket index osd, the index object may contain many omaps key-values, synchronous recovery will have a great impact on the cluster @athanatos

**Comment by neha-ojha** [comment]
The use case described in https://tracker.ceph.com/issues/56030 of "executing command ceph osd down to a bucket index osd every 30s" doesn't seem like a real world use case to me. Therefore, I am not sure it is worth adding another choose_acting() call to optimize for this case. Is there any case where this kind of change will be valuable?

**Comment by zhouyuey** [comment]
> The use case described in https://tracker.ceph.com/issues/56030 of "executing command ceph osd down to a bucket index osd every 30s" doesn't seem like a real world use case to me. Therefore, I am not sure it is worth adding another choose_acting() call to optimize for this case. Is there any case where this kind of change will be valuable?

Thanks, this may be a probabilistic or hardware difference, may be have to try a few more times, it is easy to appear in my environment.
log in osd.4.log.pg6.11-3, pg6.11 in active+recovery_wait+undersized+degraded+remapped state and async=[5] at the begin, after multiple peering, when start recovering, "async=[5]" disappeared, this is my judgment that recovery not in async, can you help me analyze the log?

**Comment by sunxm123** [comment]
another case, when backfill is completed, you will apply for modifying pg_ temp. At this time, if the temporary master accept another client op and writes another object,pg log have one more entry, then  during the peering process again, there will still be a version difference between other OSDs and the temporary master OSD, and there will still be missing objects. If you do not choose again at this time ,these osd will do  normal recovery by default, then will block client's op again 。

**Pull request closed without merging**
