### PR TITLE
octopus: admin/doc-requirements.txt: pin Sphinx at 3.5.4

### PR DESCRIPTION
**Pull request by tchaikov**
* pin Sphinx at 3.5.4
* pin docutils at 0.18

at least the combination of these two versions
is known to compile.

to address the bug reported at
https://sourceforge.net/p/docutils/bugs/431/

the backtrace looks like:

/home/jenkins-build/build/workspace/ceph-pr-docs/build-doc/virtualenv/lib/python3.8/site-packages/sphinx/util/docutils.py:285:
RemovedInSphinx30Warning: function based directive support is now
deprecated. Use class based directive instead.
  warnings.warn('function based directive support is now deprecated. '

Exception occurred:
  File
"/home/jenkins-build/build/workspace/ceph-pr-docs/build-doc/virtualenv/lib/python3.8/site-packages/docutils/writers/html5_polyglot/__init__.py",
line 445, in section_title_tags
    if (ids and self.settings.section_self_link
AttributeError: 'Values' object has no attribute 'section_self_link'

please note this change is not cherry-picked from
master, because master already bumped Sphinx to 3.5.4
in 4968baa2523bd2a5ca6be147b26bc28906a864c9.

Signed-off-by: Kefu Chai <tchaikov@gmail.com>
(cherry picked from commit 6362b554e2e57227c9fda51c7703f14674da8358)

Conflicts:
	admin/doc-requirements.txt: trivial resolution

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by liewegas** [comment]
```
ERROR: Cannot install -r requirements-lint.txt (line 10) and -r requirements-lint.txt (line 2) because these package versions have conflicting dependencies.

The conflict is caused by:
    flake8 3.9.0 depends on pycodestyle<2.8.0 and >=2.7.0
    autopep8 1.6.0 depends on pycodestyle>=2.8.0

```

**Comment by tchaikov** [comment]
> pycodestyle

should be fixed by the backport of 946dab4.

**Comment by tchaikov** [comment]
retest this please.

**Comment by neha-ojha** [comment]
jenkins retest this please

**Review by sebastian-philipp — APPROVED** [review]

**Pull request merged**
