### PR TITLE
mds: fix bug of dump_resolve_status

### PR DESCRIPTION
**Pull request by zhsgao**
Signed-off-by: Zhansong Gao <zhsgao@hotmail.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
  - [x] minor change; no tracker ticket
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by dparmar18** [comment]
Does https://github.com/ceph/ceph/pull/49756 depend on this? Reason to ask is I can see your conversation related to separation of this code from that PR.

**Comment by zhsgao** [comment]
> Does #49756 depend on this? Reason to ask is I can see your conversation related to separation of this code from that PR.

They are not related. At first I wanted to fix this little problem by the way in another PR, but it's better to separate it.

**Comment by dparmar18** [comment]
> > Does #49756 depend on this? Reason to ask is I can see your conversation related to separation of this code from that PR.
> 
> They are not related. At first I wanted to fix this little problem by the way in another PR, but it's better to separate it.

Okay so this PR doesn't block #49756 or vice-versa right?

**Review by dparmar18 — APPROVED** [review]
LGTM

**Review by rishabh-d-dave — APPROVED** [review]

**Comment by rishabh-d-dave** [comment]
@vshankar Should this bug fix be backported? Does this need a tracker ticket?

**Review by kotreshhr — APPROVED** [review]

**Comment by rishabh-d-dave** [comment]
https://tracker.ceph.com/projects/cephfs/wiki/Main#31-Mar-2023

**Pull request merged**
