### PR TITLE
break Makefile into pieces to allow building pieces of the project

### PR DESCRIPTION
**Pull request by liewegas**
This is useful for the downstream packaging.  Also for porting individual
components to other platforms

### CODE REVIEW

**Comment by tchaikov** [comment]
not a big deal, but f645e35 and 3ef8015 depend on 2469bfd where the configure option is added,  would be perfect if we can reorder these commits before merging them.

**Comment by liewegas** [comment]
left in the commented-out WITH_FOO lines since they may be useful later, but fixed everything else!

**Comment by liewegas** [comment]
@branto1 @ktdreyer how does this look?

**Comment by liewegas** [comment]
@branto1  is working on an improved version of this

**Comment by tchaikov** [comment]
#3988 is the "improved version".

**Pull request closed without merging**
