### PR TITLE
mgr/balancer: make crush-compat mode work

### PR DESCRIPTION
**Pull request by liewegas**
This is starting to work!

- [x] better throttling on max_misplaced
- [x] handle 'out' osds
- [x] transparently phase out old osd_weights, if present

My only concern here is that when it breaks (throws an exception in serve()) we don't get a run failure because we don't have mgr health alerts for crashed modules yet.  I don't think that should prevent us from merging, though.  I've done some spot checks and it appears to be doing fine.

### CODE REVIEW

**Comment by liewegas** [comment]
@jcsp: got <pre>
2017-10-30T04:04:18.658 INFO:tasks.ceph.mgr.y.smithi054.stderr:*** Caught signal (Segmentation fault) **
2017-10-30T04:04:18.658 INFO:tasks.ceph.mgr.y.smithi054.stderr: in thread 7f1e50da5700 thread_name:mgr_module_path
2017-10-30T04:04:18.659 INFO:tasks.ceph.mgr.y.smithi054.stderr: ceph version 13.0.0-2610-ge3b3929 (e3b39291fcfea8709351d83c73699f058f89c7ad) mimic (dev)
2017-10-30T04:04:18.659 INFO:tasks.ceph.mgr.y.smithi054.stderr: 1: (()+0x3b7399) [0x7f1e62304399]
2017-10-30T04:04:18.659 INFO:tasks.ceph.mgr.y.smithi054.stderr: 2: (()+0x10330) [0x7f1e609b2330]
2017-10-30T04:04:18.659 INFO:tasks.ceph.mgr.y.smithi054.stderr: 3: (()+0x1bd9e8) [0x7f1e619819e8]
2017-10-30T04:04:18.659 INFO:tasks.ceph.mgr.y.smithi054.stderr: 4: (()+0x1bf1ef) [0x7f1e619831ef]
2017-10-30T04:04:18.659 INFO:tasks.ceph.mgr.y.smithi054.stderr: 5: (()+0x15ecd7) [0x7f1e61922cd7]
2017-10-30T04:04:18.659 INFO:tasks.ceph.mgr.y.smithi054.stderr: 6: (_PyObject_GC_Malloc()+0xcb) [0x7f1e6192390b]
2017-10-30T04:04:18.660 INFO:tasks.ceph.mgr.y.smithi054.stderr: 7: (_PyObject_GC_New()+0xd) [0x7f1e619239ad]
2017-10-30T04:04:18.660 INFO:tasks.ceph.mgr.y.smithi054.stderr: 8: (PyDict_New()+0x74) [0x7f1e6192ac44]
2017-10-30T04:04:18.660 INFO:tasks.ceph.mgr.y.smithi054.stderr: 9: (_PyDict_NewPresized()+0xc) [0x7f1e6192afec]
2017-10-30T04:04:18.660 INFO:tasks.ceph.mgr.y.smithi054.stderr: 10: (PyEval_EvalFrameEx()+0x287f) [0x7f1e6190183f]
2017-10-30T04:04:18.660 INFO:tasks.ceph.mgr.y.smithi054.stderr: 11: (PyEval_EvalCodeEx()+0x80d) [0x7f1e61905c3d]
2017-10-30T04:04:18.660 INFO:tasks.ceph.mgr.y.smithi054.stderr: 12: (PyEval_EvalFrameEx()+0x48d8) [0x7f1e61903898]
2017-10-30T04:04:18.660 INFO:tasks.ceph.mgr.y.smithi054.stderr: 13: (PyEval_EvalCodeEx()+0x80d) [0x7f1e61905c3d]
2017-10-30T04:04:18.660 INFO:tasks.ceph.mgr.y.smithi054.stderr: 14: (PyEval_EvalFrameEx()+0x48d8) [0x7f1e61903898]
2017-10-30T04:04:18.660 INFO:tasks.ceph.mgr.y.smithi054.stderr: 15: (PyEval_EvalCodeEx()+0x80d) [0x7f1e61905c3d]
2017-10-30T04:04:18.660 INFO:tasks.ceph.mgr.y.smithi054.stderr: 16: (PyEval_EvalFrameEx()+0x48d8) [0x7f1e61903898]
2017-10-30T04:04:18.661 INFO:tasks.ceph.mgr.y.smithi054.stderr: 17: (PyEval_EvalFrameEx()+0x4b59) [0x7f1e61903b19]
2017-10-30T04:04:18.661 INFO:tasks.ceph.mgr.y.smithi054.stderr: 18: (PyEval_EvalCodeEx()+0x80d) [0x7f1e61905c3d]
2017-10-30T04:04:18.661 INFO:tasks.ceph.mgr.y.smithi054.stderr: 19: (()+0x141dd0) [0x7f1e61905dd0]
2017-10-30T04:04:18.661 INFO:tasks.ceph.mgr.y.smithi054.stderr: 20: (PyObject_Call()+0x43) [0x7f1e618da0a3]
2017-10-30T04:04:18.661 INFO:tasks.ceph.mgr.y.smithi054.stderr: 21: (()+0xbad6d) [0x7f1e6187ed6d]
2017-10-30T04:04:18.661 INFO:tasks.ceph.mgr.y.smithi054.stderr: 22: (PyObject_Call()+0x43) [0x7f1e618da0a3]
2017-10-30T04:04:18.661 INFO:tasks.ceph.mgr.y.smithi054.stderr: 23: (PyObject_CallMethod()+0x10b) [0x7f1e618901db]
2017-10-30T04:04:18.661 INFO:tasks.ceph.mgr.y.smithi054.stderr: 24: (MgrPyModule::serve()+0x49) [0x7f1e6220e469]
2017-10-30T04:04:18.661 INFO:tasks.ceph.mgr.y.smithi054.stderr: 25: (ServeThread::entry()+0x5f) [0x7f1e622012cf]
2017-10-30T04:04:18.661 INFO:tasks.ceph.mgr.y.smithi054.stderr: 26: (()+0x8184) [0x7f1e609aa184]
2017-10-30T04:04:18.662 INFO:tasks.ceph.mgr.y.smithi054.stderr: 27: (clone()+0x6d) [0x7f1e5fa9037d]
2017-10-30T04:04:18.662 INFO:tasks.ceph.mgr.y.smithi054.stderr:2017-10-30 04:04:18.664 7f1e50da5700 -1 *** Caught signal (Segmentation fault) **
</pre>
on /a/sage-2017-10-30_02:29:13-rados-wip-sage-testing-2017-10-29-1619-distro-basic-smithi/1789687
I thought the ref vs gil thing was in master, but maybe not?

**Comment by jcsp** [comment]
@liewegas no, the fix for MonCommandCompletion wasn't in master yet (was in the big mgr refactor branch we just merged)

**Comment by liewegas** [comment]
http://pulpito.ceph.com/sage-2017-11-01_13:59:53-rados-wip-sage3-testing-2017-11-01-0729-distro-basic-smithi/

**Comment by liewegas** [comment]
jenkins render docs

**Comment by xiexingguo** [comment]
Great!
 Can't wait to try it out!

**Pull request merged**
