### PR TITLE
rgw: drop unused variable in copy_obj_data()

### PR DESCRIPTION
**Pull request by ZVampirEM77**
cleanup unused variable in the function copy_obj_data

### CODE REVIEW

**Comment by mattbenjamin** [comment]
jenkins retest this please

**Comment by ZVampirEM77** [comment]
jenkins retest this please

**Comment by ZVampirEM77** [comment]
@mattbenjamin Do you mind to review it?

**Comment by ZVampirEM77** [comment]
@mattbenjamin ping

**Pull request merged**
