### PR TITLE
doc: Removes references to s3gw.fcgi in simple gateway configuration file...

### PR DESCRIPTION
**Pull request by nilamdyuti**
@ktdreyer I have removed references to s3gw.fcgi from the gateway configuration file as per the tracker #11396. Kindly review it and let me know if anything needs to be changed.

### CODE REVIEW

**Comment by ktdreyer** [comment]
From what I recall there were two locations in the documentation where this section has been added, and we should remove both of the sections that refer to s3gw.fcgi.

You can find all references to s3gw.fcgi in the tree by using `git grep` at the root of your clone. For example:

```
$ git grep -l s3gw.fcgi
doc/radosgw/config.rst
doc/radosgw/federated-config.rst
doc/radosgw/rgw-centos.conf
doc/radosgw/rgw-debian.conf
doc/radosgw/rgw.conf
doc/start/rgw.conf
qa/qa_scripts/rgw_install_config.pl
```

**Comment by ktdreyer** [comment]
CC'ing @yehudasa in case he wants to review.

**Comment by nilamdyuti** [comment]
@ktdreyer Ok but to remove the references from the configuration files means to change the entire configuration to mod_proxy_fcgi because s3gw.fcgi was used for mod_fastcgi. For mod_proxy_fcgi, there are two different configurations, one for usage with localhost tcp and other one with UDS. So, how to make the changes? Do I need to create two different configuration files?

Also, rgw_install_config.pl is a perl file. If I remove the reference from one function, I have to make changes to other functions of the program as well. Basically, my changes will modify the script for configuring radosgw with mod_proxy_fcgi instead of mod_fastcgi. Keeping the script unchanged will enable others to configure radosgw with mod_fastcgi if they want to. If mod_fastcgi is permanently going out of the scene due to licensing issues, then there is no harm in changing it for mod_proxy_fcgi.

So, what do you suggest?

**Comment by ktdreyer** [comment]
@yehudasa , what do you recommend for @nilamdyuti's comments above?

**Comment by johnwilkins** [comment]
I recommend we wait until we have an upstream  procedure for Civetweb that actually works. Currently, the ceph-deploy process seems broken.

**Comment by ktdreyer** [comment]
My understanding was that `s3gw.fcgi` was only for mod_fastcgi? And it is not needed for mod_proxy_fcgi? Is that correct?

**Comment by nilamdyuti** [comment]
@ktdreyer Yes!

**Pull request merged**
