### PR TITLE
osd: sparse_read offset may not be zero for ecpool

### PR DESCRIPTION
**Pull request by kofiliu**
Fixes: http://tracker.ceph.com/issues/16138
Signed-off-by: kofiliu <liu.xuan@h3c.com>

### CODE REVIEW

**Comment by kofiliu** [comment]
@tchaikov Could you review this for me? Thanks!

**Comment by kofiliu** [comment]
@tchaikov Could you review this for me? Thanks!

**Comment by tchaikov** [comment]
@kofiliu thanks for fixing this, could you add a "Fixes: http://tracker.ceph.com/issues/16138: line in your commit message? so we can backport your fix once it gets merged?

**Comment by kofiliu** [comment]
@tchaikov Could you review this for me again? Thanks!

**Comment by tchaikov** [comment]
lgtm

**Comment by kofiliu** [comment]
@tchaikov Could you merge this bug for me? Thanks a lot.

**Comment by tchaikov** [comment]
@kofiliu it's a "needs-qa" PR. so we need to run it through a rados qa test before merging it. i am on it.

**Comment by tchaikov** [comment]
tested at 

- http://pulpito.ceph.com/kchai-2016-06-10_23:14:31-rados-wip-kefu-testing---basic-smithi/
- http://pulpito.ceph.com/kchai-2016-06-07_23:04:35-rados-wip-kefu-testing---basic-mira/

failed test filed as http://tracker.ceph.com/issues/16239

**Comment by kofiliu** [comment]
@tchaikov  thank you very much!

**Pull request merged**
