### PR TITLE
rgw:bugfix for deleting objects name beginning and ending with underscores of one bucket using POST method of AWS's js sdk.

### PR DESCRIPTION
**Pull request by zhouruisong**
Fixes: http://tracker.ceph.com/issues/17888

### CODE REVIEW

**Comment by zhouruisong** [comment]
@dang how about this bugfix？ please give me some advice thanks！

**Comment by dachary** [comment]
jenkins test this please (eio now ignored in master)

**Comment by dachary** [comment]
jenkins test this please (ceph-disk tox failed, now fixed in master)

**Comment by dachary** [comment]
jenkins test this please (eio)

**Comment by zhouruisong** [comment]
@dachary how about this bug? I thinks it is really a bug and it has happened in my cluster. I have modified according to my fix and it is ok now.

**Comment by dachary** [comment]
@zhouruisong you'll have to wait for someone knowledgeable about rgw to review this. Sorry for not being more helpful. And many thanks for this contribution ;-)

**Comment by zhouruisong** [comment]
@dachary ok, please tell me your review result after testing .thanks!

**Comment by theanalyst** [comment]
@zhouruisong have you tried this after https://github.com/ceph/ceph/pull/10939 was merged

**Comment by theanalyst** [comment]
I think this should already have been fixed by #10939

**Comment by zhouruisong** [comment]
@theanalyst #10939 does not fix the bug, I have merge #10939 in my code before this bug producing.
this bug fix in follow function, you can look at my file changed. thanks!

-  void RGWDeleteMultiObj::execute()

**Comment by zhouruisong** [comment]
@oritwas  ok i will remove them,thanks

**Comment by zhouruisong** [comment]
@oritwas I have removed some commits. If any problem, please tell me,thanks!

**Pull request merged**
