### PR TITLE
doc: move Developer Guide to its own subdirectory

### PR DESCRIPTION
**Pull request by smithfarm**
Fixes: https://tracker.ceph.com/issues/38934
Signed-off-by: Nathan Cutler <ncutler@suse.com>

- [x] References tracker ticket
- [x] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by smithfarm** [comment]
jenkins render docs

**Comment by sebastian-philipp** [comment]
jenkins says:
```
/home/jenkins-build/build/workspace/ceph-pr-docs/doc/index.rst:90: WARNING: toctree contains reference to nonexisting document u'dev/developer_guide'
```

**Comment by smithfarm** [comment]
jenkins render docs

**Comment by smithfarm** [comment]
`stderr: error: RPC failed; curl 18 transfer closed with outstanding read data remaining`

**Comment by smithfarm** [comment]
jenkins render docs

**Pull request merged**
