### PR TITLE
jewel: ReplicatedBackend doesn't increment stats on pull, only push

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/16659

### CODE REVIEW

**Comment by dachary** [comment]
Hey jenkins, test this please ! (no logs)

**Comment by dachary** [comment]
Hey jenkins, test this please ! (bluefs crash)

**Comment by dachary** [comment]
@tchaikov does this backport look good to merge ? It passed the rados suite http://tracker.ceph.com/issues/16344#note-17 (except for one known bug that is, I believe, unrelated).

**Comment by tchaikov** [comment]
@dachary good to merge.

**Pull request merged**
