### PR TITLE
cmake/modules/BuildRocksDB.cmake: inherit parent's CMAKE_CXX_FLAGS

### PR DESCRIPTION
**Pull request by tchaikov**
CMake allows us to customize `CMAKE_CXX_FLAGS` by setting CXXFLAGS
environmental variable. and Debian's debhelper also sets CXXFLAGS
when it builds cmake projects for customizing the building flags.

but we fail to populate this setting down when building external
projects. this is important when it comes to the projects which
is critical to the performance. RocksDB is one of them.

in this change, we pass the `CMAKE_CXX_FLAGS` down in
`BuildRocksDB.cmake` so that its `CMAKE_CXX_FLAGS` contains
the same set of `CMAKE_CXX_FLAGS` used by its parent project.

this should help with the performance in the bluestore, where
RocksDB is used.

### CODE REVIEW

**Comment by tchaikov** [comment]
@cbodley hi Casey, could you help review this change?

**Review by cbodley — APPROVED** [review]
looks good if it builds 👍

**Comment by tchaikov** [comment]
yes, it does. 
```
[1449/2707] Performing build step for 'rocksdb_ext'
...
[318/324] Building CXX object CMakeFiles/rocksdb.dir/utilities/transactions/lock/range/range_tree/lib/util/memarena.cc.o
[319/324] Building CXX object CMakeFiles/rocksdb.dir/port/port_posix.cc.o
[320/324] Building CXX object CMakeFiles/rocksdb.dir/env/env_posix.cc.o
[321/324] Building CXX object CMakeFiles/rocksdb.dir/env/fs_posix.cc.o
[322/324] Building CXX object CMakeFiles/rocksdb.dir/env/io_posix.cc.o
[323/324] Building CXX object CMakeFiles/rocksdb.dir/build_version.cc.o
[324/324] Linking CXX static library librocksdb.a
```

see https://jenkins.ceph.com/job/ceph-pull-requests/126506/consoleText

**Comment by markhpc** [comment]
Beyond ensuring it built, did anyone actually do any performance testing to make sure this fixes the original issue?

**Comment by aderumier** [comment]
@markhpc 

I'm going to fix proxmox ceph packages to include your patch or this patch. (or both ?)

I'll try to compare both patches on a real cluster tomorrow. (I have plenty of graphs, so it should be easy to see if latency is lower).

I need to update ceph-osd deb only , right ?

**Comment by aderumier** [comment]
@markhpc I have tested both patches, I have same performance.

It's really night and day, rocksdb submit latency /3 !   o_O

image

**Comment by tchaikov** [comment]
> @markhpc
> 
> I'm going to fix proxmox ceph packages to include your patch or this patch. (or both ?)
> 
> I'll try to compare both patches on a real cluster tomorrow. (I have plenty of graphs, so it should be easy to see if latency is lower).
> 
> I need to update ceph-osd deb only , right ?

@aderumier hi Alexandre, ideally both ceph-osd and ceph-mon should be updated if the vendored RocksDB is used. as monitor also uses RocksDB as the backend of its store backend.

**Comment by markhpc** [comment]
@aderumier Thank you very much for doing that testing and indeed it makes a huge difference.

The work involved in these kinds of fixes isn't the 1-2 line code change, it's the effort that goes into actually identifying the problem, diagnosing why it's happening, and then verifying that the fix actually does what it's supposed to do.  This PR merged before that work was completed and so I thank you for finishing it after the fact.

**Comment by tchaikov** [comment]
i just hope we can work based on facts instead based on guess.

**Comment by markhpc** [comment]
> i just hope we can work based on facts instead based on guesses.

That is precisely my point Kefu.  You blocked a PR that included a diagnosis of the problem, supplied a fix, was built, verified that the flags were properly being set, and actually tested vs the existing version to ensure it *really* fixed the issue.  You then authored a competing PR, and without actually doing any of the same analysis merged it on the (seemingly correct in this case) assumption that it also fixes everything.

I don't think this PR is bad.  I'm open to reasoning why we shouldn't force a release build in the rules file.  What I do think is bad is that in a case as clearly as important as this for Ubuntu builds, we merged a fix without verification over another one that was actually tested.  I find that incredibly disappointing.

**Comment by ifed01** [comment]
@cbodley @tchaikov - what's about backporting this PR?

**Pull request merged**
