### PR TITLE
jewel: auth: ceph auth add does not sanity-check caps

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/23673

### CODE REVIEW

**Comment by smithfarm** [comment]
```
src/Makefile.am:68:   'src/pybind/Makefile.am' included from here
src/Makefile.am: error: object 'mds/MDSAuthCaps.$(OBJEXT)' created both with libtool and without
```

**Comment by smithfarm** [comment]
Hm, trying to figure out how https://www.gnu.org/software/automake/manual/html_node/Objects-created-both-with-libtool-and-without.html is relevant.

**Comment by smithfarm** [comment]
@tchaikov For the jewel backport, the cmake bit in the first commit had to be manually backported to autotools. Looks like that didn't go well. Any idea what's wrong?

**Comment by tchaikov** [comment]
@smithfarm we are including mds/MDSAuthCaps.cc in libmon.a **and** libmds.la . the former does not libtool, and the latter use it, as the filename extension suggests. probably we can change libmds.la to a plain .a, lemme give it a try.

**Comment by smithfarm** [comment]
Closing in favor of #21367

**Pull request closed without merging**
