### PR TITLE
quincy: qa: add diff-continuous and compare-mirror-image tests to rbd and krbd suites respectively

### PR DESCRIPTION
**Pull request by ajarr**
backport tracker: https://tracker.ceph.com/issues/64667

---

backport of https://github.com/ceph/ceph/pull/55797
parent tracker: https://tracker.ceph.com/issues/64574

this backport was staged using ceph-backport.sh version 16.0.0.6848
find the latest version at https://github.com/ceph/ceph/blob/main/src/script/ceph-backport.sh

### CODE REVIEW

**Comment by ajarr** [comment]
**Note to backports team:** This PR depends on https://github.com/ceph/ceph/pull/55763

**Comment by ajarr** [comment]
@yuriw had to push out a new version as @idryomov identified an issue with the backport https://github.com/ceph/ceph/pull/55763#pullrequestreview-1935267262

I think this version works.  Don't see the issue mentioned by Ilya in my run now,
https://qa-proxy.ceph.com/teuthology/rraja-2024-03-14_15:06:20-rbd:mirror-wip-yuri5-testing-2024-03-11-1441-quincy-distro-default-smithi/7600172/teuthology.log

**Comment by yuriw** [comment]
ref: https://trello.com/c/HBqAreB0

**Comment by idryomov** [comment]
@ajarr https://github.com/ceph/ceph/pull/55763 is merged, please rebase.

**Review by idryomov — APPROVED** [review]

**Pull request merged**
