### PR TITLE
jewel: ldap: unhandled exception from rgw::from_base64() in RGW_Auth_S3::authorize_v2()

### PR DESCRIPTION
**Pull request by Abhishekvrshny**
http://tracker.ceph.com/issues/17785

### CODE REVIEW

**Comment by Abhishekvrshny** [comment]
`FAIL: test/ceph_objectstore_tool.py`
```
2016-11-03 10:14:43.433151 2b1afbfbabc0 -1 asok(0x2b1afbfc9d80) AdminSocketConfigObs::init: failed: AdminSocket::bind_and_listen: The UNIX domain socket path /home/jenkins-build/build/workspace/ceph-pull-requests/src/ceph_objectstore_tool_dir/out/client.admin.5458.asok is too long! The maximum length on this system is 107
```

**Comment by dachary** [comment]
jenkins test this please

**Comment by dachary** [comment]
jenkins test this please (general jenkins failure)

**Comment by dachary** [comment]
@mattbenjamin provided an alternate resolution for this backport at https://github.com/ceph/ceph/pull/11672

**Pull request closed without merging**
