### PR TITLE
librados: replace the var name from onack to complete

### PR DESCRIPTION
**Pull request by liupan1111**

### CODE REVIEW

**Comment by liupan1111** [comment]
@tchaikov , please help take a look, thanks!

**Comment by liupan1111** [comment]
After thinking, I think oncomplete is better... @liewegas @tchaikov , what do you think?

**Comment by liupan1111** [comment]
https://github.com/ceph/ceph/commit/af01db76f63a22178509b402776da54164af1eb0

**Comment by liupan1111** [comment]
[](https://github.com/ceph/ceph/commit/af01db76f63a22178509b402776da54164af1eb0)

**Comment by liewegas** [comment]
"oncomplete" seems clearer, yeah

**Comment by liupan1111** [comment]
@liewegas Done.

**Comment by liewegas** [comment]
can you update the commit description to match the new name?  otherwise, lgtm!

**Comment by liupan1111** [comment]
@liewegas updated the commit description, thanks!

**Pull request merged**
