### PR TITLE
quincy: rbd-mirror: fix race preventing local image deletion

### PR DESCRIPTION
**Pull request by nbalacha**
backport tracker: https://tracker.ceph.com/issues/62112

---

backport of https://github.com/ceph/ceph/pull/52057
parent tracker: https://tracker.ceph.com/issues/61672

this backport was staged using ceph-backport.sh version 16.0.0.6848
find the latest version at https://github.com/ceph/ceph/blob/main/src/script/ceph-backport.sh

### CODE REVIEW

**Comment by idryomov** [comment]
Build blocked on https://tracker.ceph.com/issues/62097.

**Review by trociny — APPROVED** [review]

**Comment by idryomov** [comment]
jenkins test make check

**Comment by idryomov** [comment]
jenkins test api

**Comment by idryomov** [comment]
jenkins test make check

**Comment by idryomov** [comment]
`make check` failure is unrelated, seen in other quincy PRs too:
```
ERROR: Cannot install -r requirements.txt (line 3), kubernetes and urllib3==1.26.15 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested urllib3==1.26.15
    kubernetes 11.0.0 depends on urllib3>=1.24.2
    google-auth 2.23.1 depends on urllib3>=2.0.5

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

...

The following tests FAILED:
	  2 - setup-venv-for-mgr (Failed)
	  4 - run-tox-mgr (Not Run)
Errors while running CTest
```

**Comment by idryomov** [comment]
@ljflores It looks you were the one who pinned `urllib3` to 1.26.15 in https://github.com/ceph/ceph/pull/51298.  Could you please take a look?

@nizamial09  Any idea where google-auth dependency is coming from and why this issue isn't hit in main or reef?

**Comment by nizamial09** [comment]
> Any idea where google-auth dependency is coming from and why this issue isn't hit in main or reef?

`google-auth` is coming from the [kubernetes package](https://github.com/kubernetes-client/python/blob/release-11.0/requirements.txt#L6). And they are not pinning it to a certain version `google-auth>=1.0.1`. `google-auth` had a release yesterday where they might have upgraded the urllib which could be causing the dependency issues. Maybe this is not happening in main and reef because of https://github.com/ceph/ceph/pull/52544/files, so probably to quincy might fix it?

**Comment by nizamial09** [comment]
https://github.com/ceph/ceph/pull/53706.

i'll be on vacation from today onwards, so it might be good if someone kept an eye on the PR.

**Comment by idryomov** [comment]
jenkins test make check

**Comment by idryomov** [comment]
jenkins test make check

**Comment by idryomov** [comment]
> Maybe this is not happening in main and reef because of https://github.com/ceph/ceph/pull/52544/files which uses the new pip dep resolver, so probably backport to quincy might fix it?

Yup, that was it, thanks @nizamial09!

**Comment by ljflores** [comment]
Rados approved: https://tracker.ceph.com/projects/rados/wiki/QUINCY#httpstrellocomc1pCzXDL11840-wip-yuri8-testing-2023-09-27-0951-quincy

**Pull request merged**
