### PR TITLE
pacific: os/bluestore: report min_alloc_size through "ceph osd metadata"

### PR DESCRIPTION
**Pull request by ifed01**
backport of https://github.com/ceph/ceph/pull/49958

backport tracker: https://tracker.ceph.com/issues/59010
parent tracker: https://tracker.ceph.com/issues/58421

Signed-off-by: Igor Fedotov [igor.fedotov@croit.io](mailto:igor.fedotov@croit.io)

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Review by anthonyeleven — APPROVED** [review]

**Comment by ljflores** [comment]
jenkins retest this please

**Comment by ljflores** [comment]
Hey @ifed01, I see a potential related failure. Can you take a look? #50321 was also tested in this batch, but I suspect this one is the issue at a glance. I'll also leave a note on #50321 in case that's a culprit.

/a/yuriw-2023-04-04_21:18:37-rados-wip-yuri3-testing-2023-04-04-0833-pacific-distro-default-smithi/7231756/teuthology.log
```
2023-04-05T07:02:12.502 INFO:teuthology.orchestra.run.smithi122.stdout:[ RUN      ] ObjectStore/StoreTest.SimpleCloneTest/2
2023-04-05T07:02:15.408 INFO:teuthology.orchestra.run.smithi122.stderr:Creating collection meta
2023-04-05T07:02:15.408 INFO:teuthology.orchestra.run.smithi122.stderr:Creating object and set attr #-1:de000000::key:Object 1:head#
2023-04-05T07:02:15.408 INFO:teuthology.orchestra.run.smithi122.stderr:Clone object and rm attr
2023-04-05T07:02:16.946 INFO:teuthology.orchestra.run.smithi122.stderr:Invalid rm coll
2023-04-05T18:49:29.148 DEBUG:teuthology.exit:Got signal 15; running 1 handler...
2023-04-05T18:49:29.228 DEBUG:teuthology.task.console_log:Killing console logger for smithi122
2023-04-05T18:49:29.229 DEBUG:teuthology.exit:Finished running handlers
"teuthology.log" [readonly] 3566L, 528305C                                                    
```

/a/yuriw-2023-04-04_21:18:37-rados-wip-yuri3-testing-2023-04-04-0833-pacific-distro-default-smithi/7231756/remote/smithi122/ceph_test_objectstore.log.gz
```
2023-04-05T07:02:09.766+0000 7ff55a886540 20 memstore(memstore.test_temp_dir) _save coll meta 0x5652fe821d40
2023-04-05T07:02:09.766+0000 7ff55a886540 10 memstore(memstore.test_temp_dir) _load
2023-04-05T07:02:09.766+0000 7ff55a886540  0 memstore(memstore.test_temp_dir) dump:{
    "collections": [
        {
            "name": "meta",
            "xattrs": [],
            "objects": [
                {
                    "name": "#-1:de000000::key:Object 1:head#",
                    "data_len": 65536,
                    "omap_header_len": 0,
                    "xattrs": [],
                    "omap": []
                },
                {
                    "name": "#-1:de000000::key:Object 2:head#",
                    "data_len": 65536,
                    "omap_header_len": 0,
                    "xattrs": [],
                    "omap": []
                }
            ]
        }
    ]
}

2023-04-05T07:02:09.790+0000 7ff55a886540 -1 *** Caught signal (Aborted) **
 in thread 7ff55a886540 thread_name:ceph_test_objec

 ceph version 16.2.11-396-g5c985a09 (5c985a09c75a9cc73e9774aadc248a51b2319e16) pacific (stable)
 1: /lib/x86_64-linux-gnu/libpthread.so.0(+0x14420) [0x7ff56424a420]
 2: gsignal()
 3: abort()
 4: ceph_test_objectstore(+0x80fd93) [0x5652fc3b3d93]
 5: ceph_test_objectstore(+0xc06fe6) [0x5652fc7aafe6]
 6: clone()
```

The same failure happened again in a rerun:
/a/yuriw-2023-04-06_15:37:58-rados-wip-yuri3-testing-2023-04-04-0833-pacific-distro-default-smithi/7234287

**Comment by ljflores** [comment]
@ifed01 let me know when this is ready to be retested.

**Comment by ifed01** [comment]
> Hey @ifed01, I see a potential related failure. Can you take a look? https://github.com/ceph/ceph/pull/50321 was also tested in this batch, but I suspect this one is the issue at a glance. I'll also leave a note on https://github.com/ceph/ceph/pull/50321 in case that's a culprit.

Hi @ljflores, thanks for the status update. Unfortunately I'm failing to find any relation between the failures (which at the first glance look relevant indeed) and these PRs. Looks like SimpleCloneTest is crashing for all backends: filestore/memstore/bluestore. But I can hardly see how adding one more param in BlueStore::collect_metadata can introduce such a crash to other backend... #50321 is a bit more tricky but it doesn't go out of BlueStore scope as well. 
Neither this is reproducible for me locally...
Curious if any other PRs were included in your runs?

If not - let's run separate standalone tests for both #50506 and #50321.

**Comment by ljflores** [comment]
> Hi @ljflores, thanks for the status update. Unfortunately I'm failing to find any relation between the failures (which at the first glance look relevant indeed) and these PRs. Looks like SimpleCloneTest is crashing for all backends: filestore/memstore/bluestore. But I can hardly see how adding one more param in BlueStore::collect_metadata can introduce such a crash to other backend... #50321 is a bit more tricky but it doesn't go out of BlueStore scope as well. Neither this is reproducible for me locally... Curious if any other PRs were included in your runs?
> 
> If not - let's run separate standalone tests for both #50506 and #50321.

Hey @ifed01, this was the Trello card for reference: https://trello.com/c/xbDVq4DL/1730-wip-yuri3-testing-2023-04-04-0833-pacific

There were other PRs included in the run, but none aside from yours touched bluestore, which is why I flagged them. I agree that the relation is not obvious though, especially since it's now present in the testing for #50932 without any of your PRs merging.

My suggestion is that we should batch #50932, #50506, and #50321 together and test them without any other PRs involved. What do you think?

**Comment by ifed01** [comment]
> My suggestion is that we should batch #50932, #50506, and #50321 together and test them without any other PRs involved. What do you think?

Sounds good to me.

**Comment by ljflores** [comment]
> Sounds good to me.

@ifed01 cool. I am building those three PRs on the tip of pacific at: https://shaman.ceph.com/builds/ceph/wip-lflores-testing-2023-05-15-2217-pacific/2ff888bbe53f321c633d5507ba77920e9961d877/

What I'll do is run the failing test (`rados/objectstore/{backends/objectstore supported-random-distro$/{ubuntu_latest}}`) 10 times on this build to see if the problem reproduces.

I will do the same on a plain pacific build in case it's already a problem in the branch separate from these PRs.

If the issue does not reproduce, I will use prior runs (or schedule new ones as needed) to validate your PRs.

**Comment by ljflores** [comment]
Scheduled on plain pacific here:
http://pulpito.front.sepia.ceph.com/lflores-2023-05-15_22:30:48-rados-pacific-distro-default-smithi/

`./teuthology/virtualenv/bin/teuthology-suite -v -m smithi -c pacific -S fc049d7e76fec66e358936eea510a3250b55bb07 -s rados --subset 111/120000 --seed 3917 --filter-all "rados/objectstore/{backends/objectstore supported-random-distro$/{ubuntu_latest}}" -N 10 -p 50`

Will schedule tests on the branch with your PRs once it finishes building.

**Comment by ljflores** [comment]
> Scheduled on plain pacific here: http://pulpito.front.sepia.ceph.com/lflores-2023-05-15_22:30:48-rados-pacific-distro-default-smithi/
> 
> `./teuthology/virtualenv/bin/teuthology-suite -v -m smithi -c pacific -S fc049d7e76fec66e358936eea510a3250b55bb07 -s rados --subset 111/120000 --seed 3917 --filter-all "rados/objectstore/{backends/objectstore supported-random-distro$/{ubuntu_latest}}" -N 10 -p 50`
> 
> Will schedule tests on the branch with your PRs once it finishes building.

8/10 jobs failed due to this bug on plain pacific. Looks like this bug already exists in pacific and is untracked. I have tracked the bug here (https://tracker.ceph.com/issues/61193), referencing the first Trello card this was seen on, in case one of those PRs was the issue.

**Comment by ljflores** [comment]
Feel free to merge the PR if you like. Thanks for working with me on this, and now the bug is officially tracked.

**Pull request merged**
