### PR TITLE
Fix the issue of calculating the signature of requests other than PUT object

### PR DESCRIPTION
**Pull request by jmunhoz**
This patchset implements AWS4 completion support for the following operations:

 * RGW_OP_PUT_ACLS
 * RGW_OP_PUT_CORS
 * RGW_OP_COMPLETE_MULTIPART
 * RGW_OP_SET_BUCKET_VERSIONING
 * RGW_OP_DELETE_MULTI_OBJ

beyond of the original support for RGW_OP_PUT_OBJ. It fixes the issue of calculating the signature of requests other than PUT object.

This patchset was tested with the updated s3-tests at https://github.com/ceph/s3-tests/pull/84

### CODE REVIEW

**Comment by jmunhoz** [comment]
@yehudasa this commit passes all rgw ops in s3-tests requiring completion (requests with data in the body) I added this assert (https://github.com/jmunhoz/ceph/commit/fb595a72a6e820fb6ce39e21a88ede0188d1e68e) as part of the patchset in order to catch any possible missing rgw op not having test case in s3-tests and requiring completion.

**Comment by yehudasa** [comment]
@jmunhoz I don't think this is the approach we should take. We should make it seamless so that for the default case where we have data coming in we wouldn't need to handle it explicitly. There might be cases where we would need to handle it explicitly (e.g., where we need to return results before we process all the data), but these should be the special case.

**Comment by jmunhoz** [comment]
@yehudasa OK, I will have a look to see how it can be implemented. Maybe we can implement this step as part of s->cio->read(). The validation could happen at the end and then propagate one validation error code if it doesn't validate. Not sure about the special cases but it could work. What do you think?

**Comment by yehudasa** [comment]
@jmunhoz is this PR obsolete, or are there any commits here that we need to have? Can you take a look at https://github.com/ceph/ceph/pull/7720 ?

**Comment by jmunhoz** [comment]
@yehudasa it is obsolete, I reviewed and the good bits are in #7720 If you are ok I will close it...

**Pull request closed without merging**
