### PR TITLE
script/run_mypy: Sort groups

### PR DESCRIPTION
**Pull request by sebastian-philipp**
Workaround for https://github.com/python/mypy/issues/2144

Signed-off-by: Sebastian Wagner <sebastian.wagner@suse.com>

- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by tchaikov** [comment]
retest this please.

**Comment by sebastian-philipp** [comment]
retest this please.

**Comment by sebastian-philipp** [comment]
> lgtm, though I wasn't able to test it due to a `double requirements` issue.
> 
> ```
> user@work ~/src/ceph-3/src (master*) $ ./script/run_mypy.sh
> Double requirement given: requests (from -r telemetry/server/ceph_telemetry/requirements.txt (line 2)) (already in requests==2.20.0 (from -r pybind/mgr/dashboard/requirements.txt (line 27)), name='requests')
> ```
> 
> This issue is also in master, so I don't think this PR is introducing it.

Hmm. I can still run mypy on my system, despite the message.

**Comment by sebastian-philipp** [comment]
Well. `Need type annotation for` is something like

```python
result = []  # Need type annotation for 'result'
for x in y:
    result.append(foo())
```

To fix this, we need something like

```python
from typing import List
result = []  # type: List[Foo]
```
And I don't know, if we (as the Ceph developer community) are ready to add this stuff into the code base.  
Secondly, the report is filled with hundreds of these errors. 

I've removed these lines on purpose in order to keep the report a bit more readable.

**Comment by alfonsomthd** [comment]
> Well. `Need type annotation for` is something like
> 
> ```python
> result = []  # Need type annotation for 'result'
> for x in y:
>     result.append(foo())
> ```
> 
> To fix this, we need something like
> 
> ```python
> from typing import List
> result = []  # type: List[Foo]
> ```
> 
> And I don't know, if we (as the Ceph developer community) are ready to add this stuff into the code base.
> Secondly, the report is filled with hundreds of these errors.
> 
> I've removed these lines on purpose in order to keep the report a bit more readable.

AFAIK @p-na added this in src/pybind/mgr/dashboard/controllers/osd.py:
```
try:
    from typing import Dict, List, Any, Union  # pylint: disable=unused-import
except ImportError:
    pass  # For typing only
```
and I'm fine with it (in fact, I fixed the aforementioned issue the same way in another PR), so the question is:
Should we take care about this issues or ignoring them?

**Comment by sebastian-philipp** [comment]
> Should we take care about this issues or ignoring them?

I did not expect this to be controversial. I just re-added those!

**Pull request merged**
