### PR TITLE
mgr/dashboard: fix pool size base conversion

### PR DESCRIPTION
**Pull request by yanyixing**
Signed-off-by: Yixing Yan yanyx@umcloud.com
the origin is as blew
image

image
The pool size is not same as ceph df 

After using the dimless_binary function, the pool size is correct. 
image

### CODE REVIEW

**Comment by gmayyyha** [comment]
@yanyixing filesystems pools have same issue.
qq20170803-141537

**Comment by yanyixing** [comment]
@gmayyyha fixed

**Comment by yanyixing** [comment]
Jenkins retest this please

**Comment by yanyixing** [comment]
Jenkins retest this please

**Comment by yanyixing** [comment]
Jenkins retest this please

**Comment by yanyixing** [comment]
Jenkins retest this please

**Comment by yanyixing** [comment]
@jcsp please review

**Comment by tchaikov** [comment]
@yanyixing please fix your "Signed-off-by" line in your commit messages? so it looks like
```
Signed-off-by: Yixing Yan <yanyx@umcloud.com>
```

**Comment by yanyixing** [comment]
@tchaikov correct the commit message

**Pull request merged**
