### PR TITLE
luminous: mon: ops get stuck in "resend forwarded message to leader"

### PR DESCRIPTION
**Pull request by pdvian**
http://tracker.ceph.com/issues/23077

### CODE REVIEW

**Comment by pdvian** [comment]
@gregsfortytwo @smithfarm

**Comment by tchaikov** [comment]
might want to include #21057 also.

**Comment by pdvian** [comment]
@tchaikov Can you add DNM label to this PR as #21057 still not yet merged to master ?

**Comment by tchaikov** [comment]
@pdvian could you cherry-pick  #21057 into this PR? as it has been merged. thanks!

**Comment by yuriw** [comment]
[wip-yuri3-testing-2018-03-28-1639-luminous](https://trello.com/c/4teUwpYf/282-wip-yuri3-testing-2018-03-28-1639-luminous)

**Comment by yuriw** [comment]
@tchaikov it's being tested now, I removed approval so it won't get merged by mistake.

**Comment by yuriw** [comment]
this can be merged

**Comment by theanalyst** [comment]
@smithfarm updated

**Comment by smithfarm** [comment]
@theanalyst @yuriw OK, I removed DNM, but it needs another round of integration testing.

**Comment by yuriw** [comment]
@smithfarm ack wil include into next testing batch

**Comment by yuriw** [comment]
[wip-yuri2-testing-2018-04-03-1604-luminous](https://trello.com/c/IhzuMQzr/284-wip-yuri2-testing-2018-04-03-1604-luminous)

**Pull request merged**
