### PR TITLE
mimic: mgr/dashboard: Use serial RGW Admin OPS API calls

### PR DESCRIPTION
**Pull request by shyukri**
backport tracker: https://tracker.ceph.com/issues/40055

---

backport of https://github.com/ceph/ceph/pull/28223
parent tracker: https://tracker.ceph.com/issues/40015

this backport was staged using ceph-backport.sh version 15.0.0.6950
find the latest version at https://github.com/ceph/ceph/blob/master/src/script/ceph-backport.sh

### CODE REVIEW

**Comment by shyukri** [comment]
Fails to build.

**Comment by smithfarm** [comment]
```
ERROR in src/app/ceph/rgw/rgw-user-form/rgw-user-form.component.ts(257,14): error TS2339: Property 'notificationService' does not exist on type 'RgwUserFormComponent'.
src/app/ceph/rgw/rgw-user-form/rgw-user-form.component.ts(257,39): error TS2304: Cannot find name 'NotificationType'.
src/app/ceph/rgw/rgw-user-form/rgw-user-form.component.ts(257,65): error TS2304: Cannot find name 'notificationTitle'.
```

**Comment by shyukri** [comment]
@votdev i was not able to fix it using only the imports. Probably something else is missing too...

**Comment by votdev** [comment]
Please apply the following patch to fix some issues.
```
--- src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-user-form/rgw-user-form.component.ts	(revision 6a898a72cdee54c4f041dc67c08390d056948d73)
+++ src/pybind/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-user-form/rgw-user-form.component.ts	(date 1587023591994)
@@ -11,7 +11,7 @@
 
 import * as _ from 'lodash';
 import { BsModalService } from 'ngx-bootstrap/modal';
-import { concat as observableConcat, forkJoin as observableForkJoin, Observable } from 'rxjs';
+import { concat as observableConcat, Observable } from 'rxjs';
 
 import { RgwUserService } from '../../../shared/api/rgw-user.service';
 import { FormatterService } from '../../../shared/services/formatter.service';
@@ -254,7 +254,6 @@
         this.userForm.setErrors({ cdSubmitButton: true });
       },
       complete: () => {
-        this.notificationService.show(NotificationType.success, notificationTitle);
         this.goToListView();
       }
     });
```

**Comment by votdev** [comment]
jenkins test dashboard

**Comment by shyukri** [comment]
jenkins test dashboard

**Comment by shyukri** [comment]
jenkins test dashboard

**Comment by votdev** [comment]
jenkins test dashboard

**Comment by yuriw** [comment]
[wip-yuri6-testing-2020-06-03-1848-mimic](https://trello.com/c/9xzWXksA/927-wip-yuri6-testing-2020-06-03-1848-mimic)

**Comment by yuriw** [comment]
@shyukri this passed tests, pls merge

**Comment by shyukri** [comment]
hi @yuriw, I don't have merge rights.

**Comment by smithfarm** [comment]
@LenzGr @callithea @votdev Yuri reports that this passed his teuthology-based testing, but I see it has not passed the Jenkins-based "ceph dashboard tests" test. What is the next step?

**Comment by callithea** [comment]
> @LenzGr @callithea @votdev Yuri reports that this passed his teuthology-based testing, but I see it has not passed the Jenkins-based "ceph dashboard tests" test. What is the next step?

The job fails due to:
`[10:38:50] E/launcher - session not created: Chrome version must be between 71 and 75`

The fix has been backported to `nautilus` https://github.com/ceph/ceph/pull/31371 I guess we would need this for `mimic` as well.

**Comment by smithfarm** [comment]
@callithea OK, I opened https://tracker.ceph.com/issues/45917 and tried to stage the backport, but the conflict is problematic.

I'll leave it to you guys to decide if/when to merge it.

**Comment by callithea** [comment]
> @callithea OK, I opened https://tracker.ceph.com/issues/45917 and tried to stage the backport, but the conflict is problematic.
> 
> I'll leave it to you guys to decide if/when to merge it.

Thanks for looking into this, @smithfarm! Maybe @tspmelo can help out here?

**Comment by votdev** [comment]
jenkins test dashboard

**Comment by callithea** [comment]
> > @callithea OK, I opened https://tracker.ceph.com/issues/45917 and tried to stage the backport, but the conflict is problematic.
> > I'll leave it to you guys to decide if/when to merge it.
> 
> Thanks for looking into this, @smithfarm! Maybe @tspmelo can help out here?

Update: After #32887 has been merged (which includes a protractor version bump) tests should also pass on this PR.

**Comment by callithea** [comment]
jenkins test dashboard

**Comment by LenzGr** [comment]
Closing - Mimic has been retired in the meanwhile: https://ceph.io/releases/mimic-is-retired/

**Pull request closed without merging**
