### PR TITLE
octopus: cephfs-shell: Change tox testenv name to py3

### PR DESCRIPTION
**Pull request by smithfarm**
backport tracker: https://tracker.ceph.com/issues/45476

---

backport of

* https://github.com/ceph/ceph/pull/34121
* https://github.com/ceph/ceph/pull/34536
* https://github.com/ceph/ceph/pull/34546
* https://github.com/ceph/ceph/pull/35021

parent tracker: https://tracker.ceph.com/issues/45071

this backport was staged using ceph-backport.sh version 15.1.1.389
find the latest version at https://github.com/ceph/ceph/blob/master/src/script/ceph-backport.sh

### CODE REVIEW

**Comment by smithfarm** [comment]
unittest_librbd failed - unrelated

**Comment by smithfarm** [comment]
jenkins test make check

**Comment by yuriw** [comment]
[wip-yuri-testing-2020-05-21-2001-octopus](https://trello.com/c/ziCbc1bJ/913-wip-yuri-testing-2020-05-21-2001-octopus)

**Comment by yuriw** [comment]
[wip-yuri6-testing-2020-05-28-2041-octopus](https://trello.com/c/onX1yVYd/918-wip-yuri6-testing-2020-05-28-2041-octopus)

**Comment by tchaikov** [comment]
> Original PR has one commit but for some reason this has 12. What happened @smithfarm ?

@smithfarm neither do i understand the rationales behind this? could you elaborate a little bit?

**Comment by smithfarm** [comment]
@batrick @tchaikov The master PR has a comment that says:

"Please don't merge, the PEP8 issues needs to be fixed.
This patch depends on #34546 and #34121."

That led me to believe that backporting just the one commit would introduce PEP8 issues which could possibly cause test failures. So, if I remember correctly, I found what I believed were fixes for the introduced PEP8 issues and cherry-picked those commits also, so the fixes would be in the same PR together with the commit that introduced the issues.

**Comment by smithfarm** [comment]
jenkins test make check

**Comment by smithfarm** [comment]
```
  2/193 Test   #6: run-tox-cephfs-shell ....................***Failed  131.89 sec
Requirement already satisfied: tox in /home/jenkins-build/build/workspace/ceph-pull-requests/build/cephfs-shell-virtualenv/lib/python3.6/site-packages (3.15.1)
Requirement already satisfied: importlib-metadata<2,>=0.12; python_version < "3.8" in /home/jenkins-build/build/workspace/ceph-pull-requests/build/cephfs-shell-virtualenv/lib/python3.6/site-packages (from tox) (1.6.1)
Requirement already satisfied: py>=1.4.17 in /home/jenkins-build/build/workspace/ceph-pull-requests/build/cephfs-shell-virtualenv/lib/python3.6/site-packages (from tox) (1.8.1)
Requirement already satisfied: toml>=0.9.4 in /home/jenkins-build/build/workspace/ceph-pull-requests/build/cephfs-shell-virtualenv/lib/python3.6/site-packages (from tox) (0.10.1)
Requirement already satisfied: filelock>=3.0.0 in /home/jenkins-build/build/workspace/ceph-pull-requests/build/cephfs-shell-virtualenv/lib/python3.6/site-packages (from tox) (3.0.12)
Requirement already satisfied: six>=1.14.0 in /home/jenkins-build/build/workspace/ceph-pull-requests/build/cephfs-shell-virtualenv/lib/python3.6/site-packages (from tox) (1.15.0)
Requirement already satisfied: pluggy>=0.12.0 in /home/jenkins-build/build/workspace/ceph-pull-requests/build/cephfs-shell-virtualenv/lib/python3.6/site-packages (from tox) (0.13.1)
Requirement already satisfied: virtualenv!=20.0.0,!=20.0.1,!=20.0.2,!=20.0.3,!=20.0.4,!=20.0.5,!=20.0.6,!=20.0.7,>=16.0.0 in /home/jenkins-build/build/workspace/ceph-pull-requests/build/cephfs-shell-virtualenv/lib/python3.6/site-packages (from tox) (20.0.21)
Requirement already satisfied: packaging>=14 in /home/jenkins-build/build/workspace/ceph-pull-requests/build/cephfs-shell-virtualenv/lib/python3.6/site-packages (from tox) (20.4)
Requirement already satisfied: zipp>=0.5 in /home/jenkins-build/build/workspace/ceph-pull-requests/build/cephfs-shell-virtualenv/lib/python3.6/site-packages (from importlib-metadata<2,>=0.12; python_version < "3.8"->tox) (3.1.0)
Requirement already satisfied: importlib-resources<2,>=1.0; python_version < "3.7" in /home/jenkins-build/build/workspace/ceph-pull-requests/build/cephfs-shell-virtualenv/lib/python3.6/site-packages (from virtualenv!=20.0.0,!=20.0.1,!=20.0.2,!=20.0.3,!=20.0.4,!=20.0.5,!=20.0.6,!=20.0.7,>=16.0.0->tox) (1.5.0)
Requirement already satisfied: distlib<1,>=0.3.0 in /home/jenkins-build/build/workspace/ceph-pull-requests/build/cephfs-shell-virtualenv/lib/python3.6/site-packages (from virtualenv!=20.0.0,!=20.0.1,!=20.0.2,!=20.0.3,!=20.0.4,!=20.0.5,!=20.0.6,!=20.0.7,>=16.0.0->tox) (0.3.0)
Requirement already satisfied: appdirs<2,>=1.4.3 in /home/jenkins-build/build/workspace/ceph-pull-requests/build/cephfs-shell-virtualenv/lib/python3.6/site-packages (from virtualenv!=20.0.0,!=20.0.1,!=20.0.2,!=20.0.3,!=20.0.4,!=20.0.5,!=20.0.6,!=20.0.7,>=16.0.0->tox) (1.4.4)
Requirement already satisfied: pyparsing>=2.0.2 in /home/jenkins-build/build/workspace/ceph-pull-requests/build/cephfs-shell-virtualenv/lib/python3.6/site-packages (from packaging>=14->tox) (2.4.7)
py3 create: /home/jenkins-build/build/workspace/ceph-pull-requests/src/tools/cephfs/.tox/py3
py3 installdeps: flake8
WARNING: Discarding $PYTHONPATH from environment, to override specify PYTHONPATH in 'passenv' in your configuration.
py3 installed: -f /home/jenkins-build/build/workspace/ceph-pull-requests/src/tools/cephfs/wheelhouse,flake8==3.8.2,importlib-metadata==1.6.1,mccabe==0.6.1,pycodestyle==2.6.0,pyflakes==2.2.0,zipp==3.1.0
py3 run-test-pre: PYTHONHASHSEED='3207249595'
py3 run-test: commands[0] | flake8 --ignore=W503 --max-line-length=100 cephfs-shell
cephfs-shell:200:17: F522 '...'.format(...) has unused named argument(s): sep
cephfs-shell:205:17: F522 '...'.format(...) has unused named argument(s): sep
cephfs-shell:367:14: E225 missing whitespace around operator
cephfs-shell:704:18: E225 missing whitespace around operator
ERROR: InvocationError for command /home/jenkins-build/build/workspace/ceph-pull-requests/src/tools/cephfs/.tox/py3/bin/flake8 --ignore=W503 --max-line-length=100 cephfs-shell (exited with code 1)
___________________________________ summary ____________________________________
ERROR:   py3: commands failed
```

**Comment by tchaikov** [comment]
@smithfarm i think you also need to backport #35021

**Comment by smithfarm** [comment]
@tchaikov Thanks; done. Let's see if that's the end of it.

**Comment by smithfarm** [comment]
@batrick How is this looking to you now?

**Comment by batrick** [comment]
@smithfarm thanks for the explanation!

**Comment by yuriw** [comment]
[wip-yuri3-testing-2020-06-18-2238-octopus](https://trello.com/c/bz3NLSzQ/939-wip-yuri3-testing-2020-06-18-2238-octopus)

**Pull request merged**
