### PR TITLE
mon: paxos is_recovering calc error

### PR DESCRIPTION
**Pull request by dwj192**
Fix:#14368

Signed-off-by: Weijun Duan <duanweijun@h3c.com>

### CODE REVIEW

**Comment by tchaikov** [comment]
lgtm

**Comment by jecluis** [comment]
I'm okay with this commit, mostly because it seems this function is not currently used.

**Comment by jecluis** [comment]
Also, I don't think this needs qa. That would just waste resources. @tchaikov please confirm this by running a `git grep -ni 'is_recovering(' src/` in case I'm missing something ;)

**Comment by tchaikov** [comment]
ahh, my fault. confirmed.

**Pull request merged**
