### PR TITLE
mon: ceph-monstore-tool must do out_store.close() in "store-copy" comman...

### PR DESCRIPTION
**Pull request by hjwsm1989**
...d.

Like the bug reported http://tracker.ceph.com/issues/10093.

Signed-off-by: huangjun <hjwsm1989@gmail.com>

### CODE REVIEW

**Comment by tchaikov** [comment]
thanks @hjwsm1989 . could you update your commit log a little bit so it looks like

```
tools: ceph-monstore-tool must do out_store.close()

this change fixes the "store-copy" command.
Like the bug reported in http://tracker.ceph.com/issues/10093. 
```

so

-  the summary of the commit log could be more brief. 
- and the details of this change start with an empty line.
- and IMO, this changes is in the area of `tools`. and `mon` is more about the monitor daemon. i think

what do you think? and you don't need to create another pull request if what you just want to update the patch. after you update your patch in your local repo, you can `git push -f` to your own remote branch (in this case, it's `wip-monstore-pool`) for this fix. and this PR will be automatically updated.

**Comment by hjwsm1989** [comment]
thanks, @tchaikov , i have changed the commit info.

**Comment by tchaikov** [comment]
the failed test is not relevant:
```
TEST_bench: 67: local bsize=1048577
TEST_bench: 68: local max_count=3145728000
TEST_bench: 69: ./ceph tell osd.0 bench 3145728001 1048577
TEST_bench: 70: grep osd_bench_large_size_max_throughput testdir/osd-bench/out
TEST_bench: 70: return 1
```

**Comment by dachary** [comment]
@tchaikov filed http://tracker.ceph.com/issues/11441

**Pull request merged**
