### PR TITLE
backport ceph-fuse file locking patches to Firefly

### PR DESCRIPTION
**Pull request by gregsfortytwo**
There is interest in ceph-fuse supporting file locking on firefly. This branch is a straightforward cherry-pick of the patches from wip-client-flock to the firefly branch. There were a few conflicts but nothing that immediately jumped out as a concern.

I'd like comments on whether this ought to be sufficient, especially if anybody can think of other pieces of code that are likely to be required for the file locking to work correctly. The big one I noticed which might be a concern is that we have an objecter_finisher in Hammer which we don't in Firefly. I'm scheduling tests on this branch as well.

Fixes: #10872

### CODE REVIEW

**Comment by gregsfortytwo** [comment]
@ukernel, can you please check if you think this ought to work? :)

**Comment by ukernel** [comment]
I think we also need commit b0e6e85aa08ea74cd209aad04f3f0bf991761e12  (mds: fix neighbor lock check).

**Comment by ukernel** [comment]
I briefly tested this branch, found no problem.

**Comment by gregsfortytwo** [comment]
My previous attempt at running this through the suite failed because of #10893 and my scheduling it against master instead of firefly ceph-qa-suite. I'll try again once the install issues are resolved.

**Comment by gregsfortytwo** [comment]
http://pulpito.ceph.com/gregf-2015-02-24_11:19:29-fs-wip-firefly-flock---basic-multi/

This branch passed everything except for *sigh* the flock locking tests. These failures look to be caused by an old FUSE transposing flock into fcntl locks and I am running that test again with an upgraded kernel.

**Comment by gregsfortytwo** [comment]
I've run the flock locking test a couple times now and all seems well. @dachary, this is in your court now I guess? :)

**Pull request merged**
