### PR TITLE
kraken: build/ops: systemd restarts Ceph Mon to quickly after failing to start

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/18721

### CODE REVIEW

**Comment by wido** [comment]
Seems a lot like #13058, which is for Jewel.

**Comment by smithfarm** [comment]
@wido And? The original issue http://tracker.ceph.com/issues/18635 calls for jewel and kraken backports.

**Comment by wido** [comment]
@smithfarm Oh, don't get me wrong :) Just wanted to get both PRs linked to each other that they are merged.

#13058 seems to be pending on another PR, don't know if that's the case here.

Just want to make sure that the backport only goes to Kraken and not to Jewel for example.

**Comment by smithfarm** [comment]
@wido Got it, no problem! The jewel and kraken backporting/stable release/integration testing process are completely separate. Anyway, both backports look like they are correctly staged, so they should both be merged in due course.

**Comment by smithfarm** [comment]
Passed `upgrade/jewel-x` suite at http://tracker.ceph.com/issues/19009#note-4

**Comment by smithfarm** [comment]
@wido @b-ranto Please review/approve if you agree this can be merged.

**Comment by b-ranto** [comment]
lgtm

**Comment by wido** [comment]
Looks good to me! A 10s backoff is probably a sane thing to do

**Pull request merged**
