### PR TITLE
common/options: extract mgr and mon options out

### PR DESCRIPTION
**Pull request by tchaikov**
the purposes of this change are:

* faster compilation, so the cmake generator can process .yaml.in
  files in parallel.
* allow daemons to include a subset of options which it is
  interested in.
* better maintainability. by grouping options in different .yaml.in
  files, developers understand who are the consumers of an option.

in this change, options only read by mgr are extracted into mgr.yaml.in,
and options only read by mon are extracted into mon.yaml.in.

so all options in mgr.yaml.in should have "services: mgr" in their
definition by default. the ones in mon.yaml.in have "services: mon".

in the case where options are consumed by multiple services or tools,
the option should add "common" to its "services" if it is supposed to be
consumed by a tool, or "mon" if it is read by monitor as well. in
future, when preprocessing the .yaml.in, we have to look up in other
.yaml files for options whose services includes "mon", when compiling
ceph-mon executable in addition to collecting the options in
mon.yaml.in.

but it takes time to audit all the options, so only part of them are
processed.

Signed-off-by: Kefu Chai <kchai@redhat.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by tchaikov** [comment]
i need take a closer look at the failures.

**Comment by tchaikov** [comment]
jenkins test make check

**Comment by tchaikov** [comment]
jenkins test make check

**Comment by tchaikov** [comment]
jenkins test make check

**Review by batrick — APPROVED** [review]

**Comment by batrick** [comment]
jenkins test api

**Comment by tchaikov** [comment]
- https://pulpito.ceph.com/kchai-2021-05-19_06:38:14-rados-wip-kefu-testing-2021-05-19-1041-distro-basic-smithi/
- https://pulpito.ceph.com/kchai-2021-05-19_13:40:13-rados-wip-kefu-testing-2021-05-19-1831-distro-basic-smithi/

failures tracked by

- https://tracker.ceph.com/issues/50151
- https://tracker.ceph.com/issues/50891

**Pull request merged**
