### PR TITLE
octopus: mgr/volumes: A few volumes plugin backport

### PR DESCRIPTION
**Pull request by kotreshhr**
-----
1. Backport Tracker: https://tracker.ceph.com/issues/51201
    Parent Tracker: https://tracker.ceph.com/issues/48231
    Parent PR: https://github.com/ceph/ceph/pull/41403
-----

2. Backport Tracker: https://tracker.ceph.com/issues/51545
    Parent Tracker: http://tracker.ceph.com/issues/51271
    Parent PR: https://github.com/ceph/ceph/pull/41966
------
3. Backport Tracker: https://tracker.ceph.com/issues/53947
    Parent Tracker: https://tracker.ceph.com/issues/53848
    Parent PR: https://github.com/ceph/ceph/pull/44557
------
4. Backport Tracker: https://tracker.ceph.com/issues/54420
    Parent Tracker: https://tracker.ceph.com/issues/54066
    Parent PR: https://github.com/ceph/ceph/pull/44970
------
5. Backported below PR as https://tracker.ceph.com/issues/51201 is dependant
    Parent PR: https://github.com/ceph/ceph/pull/32319

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by kotreshhr** [comment]
@vshankar The dedicated libcephfs handles PR depends on the PR https://github.com/ceph/ceph/pull/41966 which is not backported to octopus. Should we drop dedicated libcephfs handles PR or backport https://github.com/ceph/ceph/pull/41966 ?

**Comment by ajarr** [comment]
I've reviewed 4 commits in this PR. So reviewed all except https://github.com/ceph/ceph/pull/44800/commits/509219e1ea11a65b5d84348eb7780fc858b7a656
Those 4 commits LGTM.

Should https://github.com/ceph/ceph/pull/44970/ also be backported to fix the regression introduced by the PR to solve snapshot clone failure issue?

**Comment by ajarr** [comment]
> @vshankar The dedicated libcephfs handles PR depends on the PR #41966 which is not backported to octopus. Should we drop dedicated libcephfs handles PR or backport #41966 ?

Did you mean the libcephfs handles PR #41966 depends on https://github.com/ceph/ceph/pull/40316 ? If yes, then I think we should backport 40316 to make the backport of 41966 easier.

**Review by ajarr — COMMENTED** [review]
Should https://github.com/ceph/ceph/pull/44970 also be backported to fix the regression introduced by the PR to the solve snapshot clone failure?

**Comment by kotreshhr** [comment]
jenkins test make check

**Comment by kotreshhr** [comment]
> > @vshankar The dedicated libcephfs handles PR depends on the PR #41966 which is not backported to octopus. Should we drop dedicated libcephfs handles PR or backport #41966 ?
> 
> Did you mean the libcephfs handles PR #41966 depends on #40316 ? If yes, then I think we should backport 40316 to make the backport of 41966 easier.

@ajarr Nope, I meant #41966 depends on https://github.com/ceph/ceph/pull/32319 . Sorry for the typo in the original comment.

**Comment by kotreshhr** [comment]
jenkins test make check

**Comment by kotreshhr** [comment]
> Should #44970 also be backported to fix the regression introduced by the PR to the solve snapshot clone failure?

Yes, done.

**Comment by kotreshhr** [comment]
jenkins test make check

**Comment by kotreshhr** [comment]
jenkins test api

**Comment by kotreshhr** [comment]
@ajarr @vshankar PTAL at backport of https://tracker.ceph.com/issues/54420 and https://tracker.ceph.com/issues/51201 These are non-trivial backports.

**Comment by ljflores** [comment]
http://pulpito.front.sepia.ceph.com/?branch=wip-yuri5-testing-2022-02-28-0839-octopus

All green on the rados suite, except for one dead job that was the result of an infrastructure issue.

**Comment by ljflores** [comment]
jenkins test api

**Comment by ljflores** [comment]
@ajarr any review updates? Can this be approved?

**Comment by yuriw** [comment]
@kotreshhr @vshankar @jtlayton 
This passed the tests and needs only review
Pls merge at will

**Review by vshankar — APPROVED** [review]

**Pull request merged**
