### PR TITLE
doc: corrected options of iscsiadm command

### PR DESCRIPTION
**Pull request by ykcowrebbaj**
Signed-off-by: ykcowrebbaj <jabber256@gmail.com>

### CODE REVIEW

**Comment by dillaman** [comment]
@ykcowrebbaj ping re: your "Signed-off-by" line

**Comment by ykcowrebbaj** [comment]
> Please sign your commits. See also [1]. This is required for your PR to be merged.
> 
> [1] https://github.com/ceph/ceph/blob/master/SubmittingPatches.rst#1-sign-your-work

hi @batrick , I'm not family with git and github:-(. Can I "sign my commits" throught web interface of github site directly? I‘m not found any "Signed-off-by" botton in web pages of github. Can you commit this change instead of me？

**Comment by dillaman** [comment]
@ykcowrebbaj You can use "git commit --amend -s" in your branch to add the "Signed-off-by" line and amend the commit. Then just run "git push -f <remote name> patch-1" to push the change back to Github.

**Comment by ykcowrebbaj** [comment]
@dillaman ,I used yours method. "Signed-off-by" check has passed. Thanks.

**Pull request merged**
