### PR TITLE
pacific: ceph-volume: work around phantom atari partitions 

### PR DESCRIPTION
**Pull request by guits**
backport tracker: https://tracker.ceph.com/issues/52133

---

backport of https://github.com/ceph/ceph/pull/42469
parent tracker: https://tracker.ceph.com/issues/52060

this backport was staged using ceph-backport.sh version 16.0.0.6848
find the latest version at https://github.com/ceph/ceph/blob/master/src/script/ceph-backport.sh

### CODE REVIEW

**Comment by guits** [comment]
jenkins test ceph-volume all

**Comment by dsavineau** [comment]
@guits  I think we need to cherry-pick https://github.com/ceph/ceph/commit/651b28f2e3cb39dbe9c7038cd677a01523f08821 because that change wasn't referenced by a tracker (this needs also to be done for the octopus backport)

**Comment by guits** [comment]
jenkins test ceph-volume all

**Comment by guits** [comment]
jenkins test ceph-volume tox

**Review by dsavineau — APPROVED** [review]

**Pull request merged**
