### PR TITLE
jewel: tests: decouple ceph_test_librbd_api from libceph-common

### PR DESCRIPTION
**Pull request by tchaikov**
http://tracker.ceph.com/issues/20532

### CODE REVIEW

**Comment by tchaikov** [comment]
@smithfarm it'd be great if we can have this in jewel. upgrade test of http://pulpito.ceph.com/kchai-2017-06-09_11:53:08-upgrade-master---basic-mira/ fails constantly without it.

**Comment by smithfarm** [comment]
So we'd need to put this through rados and upgrade/client-upgrade first?

**Comment by smithfarm** [comment]
Requesting review from @dillaman because it has some bearing on rbd?

**Comment by liewegas** [comment]
Sounds like we lucked out here with jewel still being statically linked. Does this mean we're going to have the same sort of breakage going forward for any libceph-common.so ABI change?

**Comment by tchaikov** [comment]
@liewegas on the contrary, since we are now linking against libceph-common dynamically, we will be  to problems like this.

**Comment by tchaikov** [comment]
@smithfarm yes. i will do so tomorrow.

**Comment by dillaman** [comment]
@tchaikov Assuming this is due to ```ceph_test_librbd_api``` being linked to ```libcommon.a``` somehow, can't we just yank that dependency?

**Comment by dillaman** [comment]
It looks like it pulls in several classes from ```libcommon.a``` which could all be affected by ABI changes in the future. We can either piecemeal the fixes as we encounter them or convert ```test_librbd.cc``` to use standard C++ classes in-place of Ceph common classes.

**Comment by tchaikov** [comment]
@dillaman we can. it just needs more work.

**Comment by tchaikov** [comment]
#15611 decouples ceph_test_librbd_api from libcommon, i will prepare a jewel backport of it ASAP once it gets merged.

**Comment by tchaikov** [comment]
tested at http://qa-proxy.ceph.com/teuthology/kchai-2017-06-12_12:19:18-upgrade-wip-20175-kefu---basic-mira/1279912/teuthology.log.

```
/home/ubuntu/cephtest/mnt.0/client.0/tmp && cd -- /home/ubuntu/cephtest/mnt.0/client.0/tmp && CEPH_CLI_TEST_DUP_COMMAND=1 CEPH_REF=kraken TESTDIR="/home/ubuntu/cephtest" CEPH_ARGS="--cluster ceph" CEPH_ID="0" PATH=$PATH:/usr/sbin CEPH_BASE=/home/ubuntu/cephtest/clone.client.0 RBD_FEATURES=13 adjust-ulimits ceph-coverage /home/ubuntu/cephtest/archive/coverage timeout 3h /home/ubuntu/cephtest/clone.client.0/qa/workunits/rbd/test_librbd_api.sh'
2017-06-12T12:25:45.773 INFO:tasks.workunit.client.0.mira083.stdout:[==========] Running 82 tests from 3 test cases.
2017-06-12T12:25:45.773 INFO:tasks.workunit.client.0.mira083.stdout:[----------] Global test environment set-up.
2017-06-12T12:25:45.773 INFO:tasks.workunit.client.0.mira083.stdout:[----------] 68 tests from TestLibRBD
2017-06-12T12:25:45.773 INFO:tasks.workunit.client.0.mira083.stdout:seed 17944
2017-06-12T12:25:45.809 INFO:tasks.workunit.client.0.mira083.stdout:[ RUN      ] TestLibRBD.CreateAndStat
2017-06-12T12:25:46.681 INFO:tasks.workunit.client.0.mira083.stdout:using new format!
2017-06-12T12:25:49.756 INFO:tasks.workunit.client.0.mira083.stdout:image has size 2097152 and order 22
2017-06-12T12:25:49.756 INFO:tasks.workunit.client.0.mira083.stdout:[       OK ] TestLibRBD.CreateAndStat (3946 ms)
2017-06-12T12:25:49.756 INFO:tasks.workunit.client.0.mira083.stdout:[ RUN      ] TestLibRBD.CreateAndStatPP
2017-06-12T12:25:49.758 INFO:tasks.workunit.client.0.mira083.stdout:using new format!
2017-06-12T12:25:49.810 INFO:tasks.workunit.client.0.mira083.stdout:[       OK ] TestLibRBD.CreateAndStatPP (54 ms)
2017-06-12T12:25:49.810 INFO:tasks.workunit.client.0.mira083.stdout:[ RUN      ] TestLibRBD.GetId
2017-06-12T12:25:49.810 INFO:tasks.workunit.client.0.mira083.stdout:using new format!
2017-06-12T12:25:49.851 INFO:tasks.workunit.client.0.mira083.stdout:[       OK ] TestLibRBD.GetId (42 ms)
2017-06-12T12:25:49.852 INFO:tasks.workunit.client.0.mira083.stdout:[ RUN      ] TestLibRBD.GetIdPP
2017-06-12T12:25:49.852 INFO:tasks.workunit.client.0.mira083.stdout:using new format!
2017-06-12T12:25:49.895 INFO:tasks.workunit.client.0.mira083.stdout:[       OK ] TestLibRBD.GetIdPP (43 ms)
2017-06-12T12:25:49.895 INFO:tasks.workunit.client.0.mira083.stdout:[ RUN      ] TestLibRBD.GetBlockNamePrefix
2017-06-12T12:25:49.895 INFO:tasks.workunit.client.0.mira083.stdout:using new format!
2017-06-12T12:25:49.934 INFO:tasks.workunit.client.0.mira083.stdout:[       OK ] TestLibRBD.GetBlockNamePrefix (40 ms)
2017-06-12T12:25:49.935 INFO:tasks.workunit.client.0.mira083.stdout:[ RUN      ] TestLibRBD.GetBlockNamePrefixPP
2017-06-12T12:25:49.935 INFO:tasks.workunit.client.0.mira083.stdout:using new format!
2017-06-12T12:25:49.977 INFO:tasks.workunit.client.0.mira083.stdout:[       OK ] TestLibRBD.GetBlockNamePrefixPP (42 ms)
...
2017-06-12T12:26:22.246 INFO:tasks.workunit.client.0.mira083.stdout:[ RUN      ] TestLibRBD.TestClone
2017-06-12T12:26:23.602 INFO:tasks.workunit.client.0.mira083.stdout:made parent image "parent"
2017-06-12T12:26:23.603 INFO:tasks.workunit.client.0.mira083.stdout:parent has no parent info
2017-06-12T12:26:23.603 INFO:tasks.workunit.client.0.mira083.stdout:made snapshot "parent@parent_snap"
2017-06-12T12:26:23.603 INFO:tasks.workunit.client.0.mira083.stdout:can't unprotect an unprotected snap
2017-06-12T12:26:23.603 INFO:tasks.workunit.client.0.mira083.stdout:can't protect a protected snap
2017-06-12T12:26:23.603 INFO:tasks.workunit.client.0.mira083.stdout:made and opened clone "child"
2017-06-12T12:26:23.603 INFO:tasks.workunit.client.0.mira083.stdout:read: 8
2017-06-12T12:26:23.603 INFO:tasks.workunit.client.0.mira083.stdout:read: 8
2017-06-12T12:26:23.604 INFO:tasks.workunit.client.0.mira083.stdout:read: 8
2017-06-12T12:26:23.604 INFO:tasks.workunit.client.0.mira083.stdout:sizes and overlaps are good between parent and child
2017-06-12T12:26:23.604 INFO:tasks.workunit.client.0.mira083.stdout:sized down clone, changed overlap
2017-06-12T12:26:23.604 INFO:tasks.workunit.client.0.mira083.stdout:parent info: size 4194304 obj_size 4194304 parent_pool -1
2017-06-12T12:26:23.604 INFO:tasks.workunit.client.0.mira083.stdout:sized up clone, changed size but not overlap or parent's size
2017-06-12T12:26:23.604 INFO:tasks.workunit.client.0.mira083.stdout:can't remove parent while child still exists
2017-06-12T12:26:23.604 INFO:tasks.workunit.client.0.mira083.stdout:test/librbd/test_librbd.cc:1836: Failure
2017-06-12T12:26:23.604 INFO:tasks.workunit.client.0.mira083.stdout:Value of: rbd_remove(ioctx, child_name.c_str())
2017-06-12T12:26:23.604 INFO:tasks.workunit.client.0.mira083.stdout:  Actual: -95
2017-06-12T12:26:23.604 INFO:tasks.workunit.client.0.mira083.stdout:Expected: 0
2017-06-12T12:26:23.604 INFO:tasks.workunit.client.0.mira083.stdout:[  FAILED  ] TestLibRBD.TestClone (1359 ms)
...
2017-06-12T12:26:40.219 INFO:tasks.workunit.client.0.mira083.stdout:[ RUN      ] TestLibRBD.FlushAio
2017-06-12T12:26:40.219 INFO:tasks.workunit.client.0.mira083.stdout:using new format!
2017-06-12T12:26:40.644 INFO:tasks.workunit.client.0.mira083.stdout:test/librbd/test_librbd.cc:2424: Failure
2017-06-12T12:26:40.644 INFO:tasks.workunit.client.0.mira083.stdout:Value of: rbd_remove(ioctx, name.c_str())
2017-06-12T12:26:40.645 INFO:tasks.workunit.client.0.mira083.stdout:  Actual: -95
2017-06-12T12:26:40.645 INFO:tasks.workunit.client.0.mira083.stdout:Expected: 0
2017-06-12T12:26:40.645 INFO:tasks.workunit.client.0.mira083.stdout:[  FAILED  ] TestLibRBD.FlushAio (426 ms)
...
2017-06-12T12:26:50.104 INFO:tasks.workunit.client.0.mira083.stdout:[ RUN      ] TestLibRBD.ObjectMapConsistentSnap
2017-06-12T12:26:50.104 INFO:tasks.workunit.client.0.mira083.stdout:using new format!
2017-06-12T12:27:00.694 INFO:tasks.workunit.client.0.mira083.stderr:Segmentation fault (core dumped)
```

**Comment by smithfarm** [comment]
@tchaikov Can you redo these as cherry-picks from master? See #15611

**Comment by tchaikov** [comment]
@smithfarm fixed and repushed!

**Comment by smithfarm** [comment]
@tchaikov I took the liberty of removing the following text (now obsolete, right?) from the PR description:


so jewel's libcommon is ABI compatible with luminous

Fixes: http://tracker.ceph.com/issues/20175
Signed-off-by: Kefu Chai <kchai@redhat.com>
Conflict: src/common/perf_counters.*
    this change is not cherry-picked from mater, because:
ceph_test_librbd_api is used to test the API compatibility of librbd,
and in jewel, it is statically linked against libcommon. and in
luminous, we changed the layout of PerfCounters. so the instances
created by jewel's ceph_test_librbd_api cannot be read correctly by the
libceph-common.so in luminous anymore. so we need to either make
libceph-common.so ABI compatible with jewel's ceph_test_librbd_api, or
make jewel's ceph_test_librbd_api compatible with libceph-common.so. a
simple (probably the only) solution is to add the newly added field to
PerfCounters so it looks the same from luminous's libceph-common. at the
first glance, it is wrong to modify the test case to fix the design under
test. it's not. we are not changing librados or librbd, so
we are not break the functionality of ceph_test_librbd_api to verify the
ABI consistency. and user's application does not link against libcommon,
so we do have the luxury to update libcommon.a to address this
incompatibility.

**Comment by tchaikov** [comment]
@smithfarm yes, i wanted to justify the simpler version of fix i posted before back then. now that we go with the better (and more complicated) way, the justification is now obsoleted.

**Comment by smithfarm** [comment]
@tchaikov @jdurgin @dillaman This passed an rbd suite at http://tracker.ceph.com/issues/20613#note-31 (there was 1 failure that passed on rerun).

The rados run is putting up a bit of a fight; there are a couple failures but they don't appear to be reliably reproducible or related to rbd (or this PR, but what do I know?): http://tracker.ceph.com/issues/20613#note-25

I also ran three different upgrade suites; again, some failures failures that were either not reproducible or could be "hand-waved away".

OK to merge?

**Pull request merged**
