### PR TITLE
osd: filestore: restructure journal and op queue throttling

### PR DESCRIPTION
**Pull request by athanatos**
Tested, see below.

### CODE REVIEW

**Comment by athanatos** [comment]
@liewegas Does this make sense?

**Comment by liewegas** [comment]
looks good to me, yep!

**Comment by somnathr** [comment]
@athanatos The commit for changing filestore_max_byte to OPT_U64 is missing in this PR

**Comment by athanatos** [comment]
@liewegas Tested and ready for merge.  Looks ok?  sjust@teuthology:/a/samuelj-2016-02-29_16:00:45-rados-wip-sam-testing-distro-basic-smithi

**Comment by liewegas** [comment]
lgtm

**Comment by wildinto** [comment]
cool

**Pull request merged**
