### PR TITLE
octopus: qa: py3 compatibility

### PR DESCRIPTION
**Pull request by kshtsk**
## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by tchaikov** [comment]
@kshtsk thanks for working on octopus backport, could you cherry-pick the missing commits from #35364 ?

**Comment by tchaikov** [comment]
also could you paste the links of the successful runs of the suites that covered by this change?

**Comment by sebastian-philipp** [comment]
That's really awesome! Honestly, I'm surprised that porting octopus is feasible.

**Comment by kshtsk** [comment]
jenkins test make check

**Comment by kshtsk** [comment]
smoke passed:

suite | teuthology_branch | suite_branch | run
---|---|---|---
smoke | master | wip-octopus-py3-smoke | [open](http://pulpito.ceph.com/kyr-2020-06-05_11:20:24-smoke-octopus-distro-basic-smithi/)
smoke | py2 | wip-octopus-py3-smoke | [open](http://pulpito.ceph.com/kyr-2020-06-05_15:57:54-smoke-octopus-distro-basic-smithi/)

**Comment by sebastian-philipp** [comment]
http://pulpito.ceph.com/kyr-2020-06-07_10:42:16-rados-octopus-distro-basic-smithi/5124502 is interesting. Looks like the mirror registry doesn't work. cc @djgalloway

**Comment by kshtsk** [comment]
Waiting for new runs against build 91d24f498556f86f6d1318d2efd5210c35b36762
suite|branch|teuthology|run|total|failed|dead
---|---|---|---|---|---|---
rados|wip-octopus-py3-smoke|master|[waiting](http://pulpito.ceph.com/kyr-2020-06-11_07:50:51-rados-octopus-distro-basic-smithi/)|331|—|—
rados|wip-octopus-py3-smoke|py2|[waiting](http://pulpito.ceph.com/kyr-2020-06-11_07:56:51-rados-octopus-distro-basic-smithi/)|331|—|—
rgw|wip-octopus-py3-smoke|master|[waiting](http://pulpito.ceph.com/kyr-2020-06-11_08:26:32-rgw-octopus-distro-basic-smithi/)|39|—|—
rgw|wip-octopus-py3-smoke|py2|[waiting](http://pulpito.ceph.com/kyr-2020-06-11_08:29:34-rgw-octopus-distro-basic-smithi/)|39|—|—
fs|wip-octopus-py3-smoke|master|[waiting](http://pulpito.ceph.com/kyr-2020-06-11_08:11:55-fs-octopus-distro-basic-smithi/)|143|—|—
fs|wip-octopus-py3-smoke|py2|[waiting](http://pulpito.ceph.com/kyr-2020-06-11_08:14:42-fs-octopus-distro-basic-smithi/)|143|—|—
multimds|wip-octopus-py3-smoke|master|[waiting](http://pulpito.ceph.com/kyr-2020-06-11_08:19:04-multimds-octopus-testing-basic-smithi/)|24|—|—
multimds|wip-octopus-py3-smoke|py2|[waiting](http://pulpito.ceph.com/kyr-2020-06-11_08:20:34-multimds-octopus-testing-basic-smithi/)|24|—|—
powercycle|wip-octopus-py3-smoke|master|[waiting](http://pulpito.ceph.com/kyr-2020-06-11_08:23:50-powercycle-octopus-testing-basic-smithi/)|15|—|—
powercycle|wip-octopus-py3-smoke|py2|[waiting](http://pulpito.ceph.com/kyr-2020-06-11_08:24:42-powercycle-octopus-testing-basic-smithi/)|15|—|—

**Comment by kshtsk** [comment]
Because @tchaikov is working on his PR https://github.com/ceph/ceph/pull/35364 working on my is duplication of effort and waste of lab's computing resources for running tests, so I am about to close it, however I it can wait until Kefu finish his job.

**Pull request closed without merging**
