### PR TITLE
buffer.h: Removed unnecessary copy constructor, assignment operator a…

### PR DESCRIPTION
**Pull request by stiopaa1**
…nd added some

consts

Signed-off-by: Michal Jarzabek <stiopa@gmail.com>

### CODE REVIEW

**Comment by dachary** [comment]
@stiopaa1 please separate the added const in a different commit.

**Comment by dachary** [comment]
@stiopaa1 removing this copy constructor means the default copy constructor will be used when it is needed, right ? Is it really what we need ?

**Comment by stiopaa1** [comment]
>removing this copy constructor means the default copy constructor will be used when it is needed, right 
Yes, the default copy constructor will now be generated and used. 

>Is it really what we need ?
Unless I'm missing something, the default copy constructor does exactly the same thing as the one that I removed.

**Comment by dachary** [comment]
That made me curious to understand why this copy constructor was inserted in the first place. Originally it was different but now it's the same.
<pre>
$ git log -L294,298:buffer.h
commit 00c31310d734e17399f6731899304da934a88f58
Author: Sage Weil <sage@newdream.net>
Date:   Wed Jul 30 21:43:46 2008 -0700

    buffer: fix iterator assignment to between bufferlists

diff --git a/src/include/buffer.h b/src/include/buffer.h
--- a/src/include/buffer.h
+++ b/src/include/buffer.h
@@ -409,5 +414,5 @@
 	if (this != &other) {
 	  bl = other.bl;
-	  ls = bl->_buffers;
+	  ls = other.ls;
 	  off = other.off;
 	  p = other.p;

commit 6b833354448e4558b51e30f5c5b301e488d7f34c
Author: Sage Weil <sage@newdream.net>
Date:   Wed Apr 16 09:34:33 2008 -0700

    buffer iterator fixed

diff --git a/src/include/buffer.h b/src/include/buffer.h
--- a/src/include/buffer.h
+++ b/src/include/buffer.h
@@ -402,1 +402,5 @@
-	return iterator(other.bl, other.off, other.p, other.p_off);
+	if (this != &other) {
+	  bl = other.bl;
+	  ls = bl->_buffers;
+	  off = other.off;
+	  p = other.p;

commit 53349f2ff904c085488eb241765bcb147f0d660e
Author: Sage Weil <sage@newdream.net>
Date:   Mon Apr 14 08:12:55 2008 -0700

    bufferlist: clear last_p iterator when appropriate

diff --git a/src/include/buffer.h b/src/include/buffer.h
--- a/src/include/buffer.h
+++ b/src/include/buffer.h
@@ -402,1 +402,1 @@
-	return iterator(bl, off, p, p_off);
+	return iterator(other.bl, other.off, other.p, other.p_off);

commit c1865445c5b88cae2df499e4d2047af156225177
Author: Sage Weil <sage@newdream.net>
Date:   Wed Dec 19 13:28:33 2007 -0800

    reorganized source tree

diff --git a/src/include/buffer.h b/src/include/buffer.h
--- /dev/null
+++ b/src/include/buffer.h
@@ -0,0 +396,1 @@
+	return iterator(bl, off, p, p_off);

</pre>

**Pull request merged**
