### PR TITLE
mon: add an "osd crush tree" command

### PR DESCRIPTION
**Pull request by tchaikov**
http://tracker.ceph.com/issues/11833

### CODE REVIEW

**Comment by tchaikov** [comment]
@theanalyst could you help me test it in the next qa run? thanks =)

**Comment by jecluis** [comment]
is this a backport of a feature?

**Comment by tchaikov** [comment]
it's a backport. removing the "feature" tag if "feature" and "backport" are mutual exclusive.

**Comment by jecluis** [comment]
Traditionally, we've backported only bug fixes. This is clearly a feature, regardless of being tagged as such or not. I'm just wondering how lenient is the policy regarding backporting features nowadays :)

**Comment by theanalyst** [comment]
@tchaikov sure all open prs with milestone hammer will make it into the next round of integration testing..

**Comment by smithfarm** [comment]
one would think that at least these two -- "bug fix" and "feature" -- would be mutually exclusive

**Comment by dachary** [comment]
@tchaikov  does this hammer backport looks good to merge ? It went through a rados suite ( http://tracker.ceph.com/issues/11990#rados ). There was a transient error ( http://tracker.ceph.com/issues/12469 ) but I don't think it's related.

**Comment by tchaikov** [comment]
@dachary @theanalyst LGTM.

**Pull request merged**
