### PR TITLE
tools:support printing part cluster map in readable fashion

### PR DESCRIPTION
**Pull request by caibo2014**
You can see more info here:
http://tracker.ceph.com/issues/13079

### CODE REVIEW

**Comment by caibo2014** [comment]
@tchaikov could you review this request?
thanks!  ^-^

**Comment by caibo2014** [comment]
@jecluis  updated.

**Comment by caibo2014** [comment]
@tchaikov updated

**Comment by caibo2014** [comment]
@tchaikov could you review this? thanks!

**Comment by tchaikov** [comment]
@caibo2014, lgtm. will merge it once i have it tested.

**Comment by caibo2014** [comment]
@tchaikov updated, thanks for reminding.

**Comment by caibo2014** [comment]
@tchaikov 
and I don't understand the meaning of the sentence you said "s/crush_map/crushmap/"
#_#

**Comment by tchaikov** [comment]
@caibo2014 would you reconsider https://github.com/ceph/ceph/pull/5921#commitcomment-14307593 ?

and also squash 6962980 into 504870f6cbc1bccd7421e5505d896adfa9415688 ?

**Comment by caibo2014** [comment]
@tchaikov I squash 6962980 into 504870f as you say.
but I do not understand what you say about "would you reconsider #5921 (comment) ?", are you saying there is a problem of these code?  can you explain it?  thanks!

**Comment by caibo2014** [comment]
@tchaikov updated

**Comment by caibo2014** [comment]
@tchaikov hi, are you still here?

**Comment by caibo2014** [comment]
@tchaikov I found my test code and the code I submit discrepancy , I modified the spelling mistakes and re-tested to make sure it is available, thank you for pointing out my mistake.

**Comment by caibo2014** [comment]
@tchaikov anything I can do now?

**Comment by tchaikov** [comment]
@caibo2014 lgtm.

**Comment by tchaikov** [comment]
@jecluis what do you think?

**Comment by caibo2014** [comment]
@jecluis Hi, can you review this, please.

**Comment by caibo2014** [comment]
@tchaikov I think we can merge this...

**Comment by caibo2014** [comment]
@tchaikov Hi, can you merge this?

**Pull request merged**
