### PR TITLE
DNM init: script bug with multiple clusters

### PR DESCRIPTION
**Pull request by gregsfortytwo**
The Ceph init script (src/init-ceph.in) creates pid files without cluster
names. This means that only one cluster can run at a time. The solution
is simple and works fine here: add "$cluster-" as usual.

Backport: hammer, giant, firefly

Signed-off-by: Amon Ott <a.ott@m-privacy.de>
Reviewed-by: Greg Farnum <gfarnum@redhat.com>

### CODE REVIEW

**Comment by gregsfortytwo** [comment]
@liewegas is worried this may prevent an upgraded system from killing daemons started before the name change; I'll investigate.

**Comment by dachary** [comment]
the failure may come from the fact that src/test/ceph_objectstore_tool.py uses the init script

**Comment by liewegas** [comment]
@gregsfortytwo the civetweb submodule commit is updated here, looks like an accident

**Comment by dachary** [comment]
@gregsfortytwo could you repush and rebase to verify the bot is happy about it ? It failed in the gitbuilders tarbal that run make check as well, back two weeks ago.

**Comment by gregsfortytwo** [comment]
After that failure I don't know if this works or not and need to test;
hoping to get to it soon. :)

**Comment by dachary** [comment]
@gregsfortytwo this needs rebasing

**Comment by gregsfortytwo** [comment]
Still needs proper testing too; it's on my list but has fallen pretty far down. :( I'll poke people when I've made more progress.

**Comment by liewegas** [comment]
closing this for now.  sysvinit is deprecated anyway.  reopen if priority bumps up again!

**Pull request closed without merging**
