### PR TITLE
qa/libceph: Fix path in usage

### PR DESCRIPTION
**Pull request by joscollin**
Found this while communicating with @simransinghal 

Signed-off-by: Jos Collin <jcollin@redhat.com>

### CODE REVIEW

**Comment by simransinghal** [comment]
@joscollin I found there is one more problem here
https://github.com/ceph/ceph/blob/6885380c24ed1357c13d293260bed90443462ada/qa/libceph/Makefile#L5-L7
As it should be like below because one of the flag is -lcephfs, which should come after the filename.
$(CC) $@.c $(CFLAGS)  -o $@

**Comment by joscollin** [comment]
@simransinghal 

`cc -Wall -Wextra -D_GNU_SOURCE -lcephfs -L../../build/lib trivial_libceph.c -o trivial_libceph`

This works.

**Comment by simransinghal** [comment]
@joscollin It didn't work for me. I have to explicitly change its order to make it work like this:-
`cc -Wall -Wextra -D_GNU_SOURCE -L ../../build/lib trivial_libceph.c -o trivial_libceph -lcephfs

When I am running what you just mentioned, I am getting linking error:-
ibceph.c -o trivial_libceph
/tmp/ccP4GI6u.o: In function `main':
trivial_libceph.c:(.text+0x6d): undefined reference to `ceph_create'
trivial_libceph.c:(.text+0xc5): undefined reference to `ceph_conf_read_file'
trivial_libceph.c:(.text+0x11b): undefined reference to `ceph_conf_parse_argv'
trivial_libceph.c:(.text+0x167): undefined reference to `ceph_mount'
trivial_libceph.c:(.text+0x1b3): undefined reference to `ceph_chdir'
trivial_libceph.c:(.text+0x212): undefined reference to `ceph_open'
trivial_libceph.c:(.text+0x28a): undefined reference to `ceph_write'
trivial_libceph.c:(.text+0x2be): undefined reference to `ceph_shutdown'
collect2: error: ld returned 1 exit status

**Comment by joscollin** [comment]
@simransinghal It works for me in both ways. I'm not sure why it doesn't work for you. Anyway, please create a different PR for this issue.

**Comment by joscollin** [comment]
@liewegas ping

**Pull request closed without merging**
