### PR TITLE
qa, crimson: bring multimon to the crimson-rados suite

### PR DESCRIPTION
**Pull request by rzarzynski**
Testing
=======
`TEUTH_BRANCH=main teuthology-suite --machine-type smithi -s crimson-rados -p 60  --force-priority --sha1 4f4eedf5af280c0454256e719007cfdac42526e5  --suite-repo https://github.com/rzarzynski/ceph.git --suite-branch wip-crimson-qa-multimon --dry-run`

Currently this PR adds far too many too similar:

```
2022-08-02 17:18:55,036.036 INFO:teuthology.suite.run:Suite crimson-rados in /home/rzarzynski/src/github.com_rzarzynski_ceph_wip-crimson-qa-multimon/qa/suites/crimson-rados scheduled 442 jobs.
2022-08-02 17:18:55,036.036 INFO:teuthology.suite.run:0/442 jobs were filtered out.
```

The reference point is `10`.

### CODE REVIEW

**Review by NitzanMordhai — APPROVED** [review]

**Comment by tchaikov** [comment]
api test failed due to
```
jenkins-build@braggi11:~$ vi /home/jenkins-build/build/workspace/ceph-api/src/pybind/mgr/cephadm/__init__.py
jenkins-build@braggi11:~$ dpkg -S /usr/lib/python3/dist-packages/ceph/deployment/service_spec.py
python3-ceph-common: /usr/lib/python3/dist-packages/ceph/deployment/service_spec.py
```

**Comment by tchaikov** [comment]
jenkins test api

**Comment by tchaikov** [comment]
jenkins test make check

**Review by athanatos — APPROVED** [review]

**Comment by rzarzynski** [comment]
jenkins test make check

**Comment by rzarzynski** [comment]
```
The following tests FAILED:
	  7 - run-tox-mgr-dashboard-py3 (Failed)
	261 - run-tox-qa (Failed)
```

**Comment by rzarzynski** [comment]
jenkins test make check

**Comment by rzarzynski** [comment]
jenkins test make check

**Comment by Matan-B** [comment]
jenkins test make check

**Comment by Matan-B** [comment]
Might be worth rebasing?

**Comment by Matan-B** [comment]
jenkins test make check

**Pull request closed without merging**
