### PR TITLE
doc: object -> file -> disk is wrong for bluestore

### PR DESCRIPTION
**Pull request by anthonyeleven**
doc: object -> file -> disk is wrong for BlueStore

Update the diagram and discussion to reflect the new world order of BlueStore while also acknowledging Filestore.

Replace `disk` with `drive`, misc. editing for flow and paragraph fills.

Fixes: https://tracker.ceph.com/issues/23443
Signed-off-by: Anthony D'Atri <anthony.datri@gmail.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by anthonyeleven** [comment]
@zdover23

**Comment by tchaikov** [comment]
@anthonyeleven instead of having "Address tracker 23443"  in the title of the PR and commit message, i'd suggest have it in the body of commit message.

**Comment by anthonyeleven** [comment]
Thanks.  My first time at addressing tracker tickets, wanted to be thorough.  I've amended.

**Comment by anthonyeleven** [comment]
jenkins test make check

**Comment by anthonyeleven** [comment]
jenkins test make check

**Comment by anthonyeleven** [comment]
jenkins test make check

**Comment by anthonyeleven** [comment]
jenkins test make check

**Review by zdover23 — APPROVED** [review]
LGTM; proceeding with merge.

**Comment by anthonyeleven** [comment]
Thanks!  If you agree that this addresses the tracker ticket, please mark it resolved (I don't have teh_power)

**Comment by zdover23** [comment]
> Thanks! If you agree that this addresses the tracker ticket, please mark it resolved (I don't have teh_power)

Done.

https://tracker.ceph.com/issues/23443

**Pull request merged**
