### PR TITLE
mgr/cephadm: allow config for an iscsi `container_image`

### PR DESCRIPTION
**Pull request by mgfritch**
```
ceph config set client.iscsi container_image <container_image>
```

Fixes: https://tracker.ceph.com/issues/45162
Signed-off-by: Michael Fritch <mfritch@suse.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by mgfritch** [comment]
cc @matthewoliver

**Comment by bk201** [comment]
Can you share how to set the image? Set ceph services like mon, mgr,.etc works. But it doesn't work with `nfs` and `iscsi`.
```
╭─root@ceph-master /ceph/build 
╰─# bin/ceph config set nfs container_image quay.io/ceph-ci/ceph:master
Error EINVAL: unrecognized config target 'nfs'
╭─root@ceph-master /ceph/build 
╰─# bin/ceph config set iscsi container_image quay.io/ceph-ci/ceph:master                                                                                                               
Error EINVAL: unrecognized config target 'iscsi'
```

**Comment by sebastian-philipp** [comment]
```
ceph config set client.nfs container_image quay.io/ceph-ci/ceph:master
```

should do it. See cephadm.utils.name_to_config_section

**Comment by mgfritch** [comment]
QA run successful:

* http://pulpito.ceph.com/mgfritch-2020-04-24_02:15:51-rados-wip-mgfritch-testing-2020-04-23-1900-distro-basic-smithi/

Failure: https://tracker.ceph.com/issues/45194

**Pull request merged**
