### PR TITLE
librbd: fix qos assert m_io_throttled fail

### PR DESCRIPTION
**Pull request by shminjs**
nautilus librbd: fix assert m_io_throttled fail

Fixes: https://tracker.ceph.com/issues/47371
Signed-off-by: shminjs <shminjs@outlook.com>
## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by shminjs** [comment]
@dillaman please help to have a look, this is a bug fix. Thank you.

**Comment by dillaman** [comment]
The issue is hopefully addressed here: #37116

**Comment by shminjs** [comment]
> The issue is hopefully addressed here: #37116

Yes, I propose this issue. And it seems that your implemention is better.

**Comment by dillaman** [comment]
Thanks!

**Comment by shminjs** [comment]
For me, it is a little pity. After all, my first contribution to community is delayed, but I will try hard to make this happen.

**Comment by dillaman** [comment]
Sorry about that. In the future you should indicate on the tracker ticket that you are working on the issue.

**Pull request closed without merging**
