### PR TITLE
pacific: os/bluestore: allow 'fit_to_fast' selector for single-volume osd

### PR DESCRIPTION
**Pull request by ifed01**
backport of https://github.com/ceph/ceph/pull/50095

backport tracker: https://tracker.ceph.com/issues/59338
parent tracker: https://tracker.ceph.com/issues/57855

Signed-off-by: Igor Fedotov [igor.fedotov@croit.io](mailto:igor.fedotov@croit.io)
(cherry picked from commit https://github.com/ceph/ceph/commit/25c8df3df138b9f85a36b4d2bbc582e16e58ed0b)

Conflicts:
src/os/bluestore/BlueStore.cc
Missing backport
 Conflicts:
	src/os/bluestore/BlueStore.cc
 lacking another backport

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Review by aclamk — APPROVED** [review]

**Comment by sseshasa** [comment]
@aclamk The following teuthology ObjectStore test https://pulpito.ceph.com/yuriw-2023-07-27_22:37:12-rados-wip-yuri6-testing-2023-07-24-0819-pacific-distro-default-smithi/7354890 failed.

The following tests failed: ObjectStore/StoreTestSpecificAUSize.SpilloverFixedTest and
ObjectStore/StoreTestSpecificAUSize.SpilloverFixed2Test. Can you please check and confirm if the failure is related to this PR?

I will remove the relevant test tag and 'needs-qa' label for now. Please add the 'needs-qa' label back once the PR is ready for a re-test.

Alternatively, if the failure is unrelated, a new tracker may be raised for the above failure and this PR may be merged. Please update accordingly.

**Comment by ifed01** [comment]
@sseshasa - I updated test cases in https://github.com/ceph/ceph/pull/51773 which is apparently a culprit for the teuthology failures. So both this PR and #51773 are ready for another QA round

**Comment by sseshasa** [comment]
> @sseshasa - I updated test cases in #51773 which is apparently a culprit for the teuthology failures. So both this PR and #51773 are ready for another QA round

@ifed01 Sure, this and #51773 will go through another QA round.

**Comment by ljflores** [comment]
Rados approved: https://tracker.ceph.com/projects/rados/wiki/PACIFIC#httpstrellocomc8HALLv9T1813-wip-yuri6-testing-2023-08-03-0807-pacific-old-wip-yuri6-testing-2023-07-24-0819-pacific2-old-wip-yuri6-testing-2023-07-24-0819-p

**Comment by ljflores** [comment]
Rados approved: https://tracker.ceph.com/projects/rados/wiki/PACIFIC#httpstrellocomcTw3vOIOj1819-wip-yuri2-testing-2023-08-08-0755-pacific

**Pull request merged**
