### PR TITLE
Pacific: osd/scrubber/pg_scrubber.cc: fix bug where scrub machine gets stuck

### PR DESCRIPTION
**Pull request by ronen-fr**
Fixes a scenario where the scrub machine gets stuck if starting
a deep scrub while the noscrub flag is set. It was dropping a
scrub reschedule op, without clearing scrub state, leaving the FSM
stuck in ActiveScrubbing,PendingTimer state.

Fixes: https://tracker.ceph.com/issues/54172
Signed-off-by: Cory Snyder <csnyder@iland.com>
(cherry picked from commit a46a61fdf795af93566dfb8fd92b0b18811083b6)

Backport tracker by @cfsnyder - https://tracker.ceph.com/issues/56409

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by ronen-fr** [comment]
Draft, pending formal merge of picked PR

**Comment by ronen-fr** [comment]
jenkins test api

**Comment by neha-ojha** [comment]
jenkins test api

**Review by neha-ojha — APPROVED** [review]

**Comment by ljflores** [comment]
Rados suite results: https://pulpito.ceph.com/?branch=wip-yuri4-testing-2022-07-05-0719-pacific

Failures, unrelated:
    1. https://tracker.ceph.com/issues/53939
    2. https://tracker.ceph.com/issues/54071
    3. https://tracker.ceph.com/issues/53501
    4. https://tracker.ceph.com/issues/53294
    5. https://tracker.ceph.com/issues/54992
    6. https://tracker.ceph.com/issues/52321

Details:
    1. ceph-nfs-upgrade, pacific: Upgrade Paused due to UPGRADE_REDEPLOY_DAEMON: Upgrading daemon osd.0 on host smithi103 failed - Ceph - Orchestrator
    2. rados/cephadm/osds: Invalid command: missing required parameter hostname(<string>) - Ceph - Orchestrator
    3. Exception when running 'rook' task. - Ceph - Orchestrator
    4. rados/test.sh hangs while running LibRadosTwoPoolsPP.TierFlushDuringFlush - Ceph - RADOS
    5. cannot stat '/etc/containers/registries.conf': No such file or directory - Ceph - Orchestrator
    6. qa/tasks/rook times out: 'check osd count' reached maximum tries (90) after waiting for 900 seconds - Ceph - Rook

**Pull request merged**
