### PR TITLE
jewel: librbd: Possible deadlock performing a synchronous API action while refresh in-progress

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/18496

### CODE REVIEW

**Comment by smithfarm** [comment]
Marking DNM for now because it conflicts with #12890:

```
CONFLICT (content): Merge conflict in src/librbd/ImageState.h
```

Let's remove the DNM and rebase after #12890 is merged.

**Comment by smithfarm** [comment]
**Do not merge until v10.2.7 tag is added - this PR is for v10.2.8**

@dillaman This PR was included in the rbd run at http://tracker.ceph.com/issues/19538#note-11 - all tests passed except for one dead job due to an assert in ceph-objectstore-tool. The assert happens in `rbd/thrash/{base/install.yaml clusters/{fixed-2.yaml openstack.yaml} fs/xfs.yaml msgr-failures/few.yaml thrashers/cache.yaml workloads/rbd_fsx_nbd.yaml}` and appears to be reproducible:

```
2017-04-09T01:48:49.750 INFO:teuthology.orchestra.run.smithi051:Running: 'sudo adjust-ulimits ceph-objectstore-tool --data-path /var/lib/ceph/osd/ceph-2 --journal-path /var/lib/ceph/osd/ceph-2/journal --log-file=/var/log/ceph/objectstore_tool.\\$pid.log --op export --pgid 0.7 --file /home/ubuntu/cephtest/ceph.data/exp.0.7.2'
2017-04-09T01:48:49.850 INFO:teuthology.orchestra.run.smithi051.stderr:osd/PG.cc: In function 'static int PG::peek_map_epoch(ObjectStore*, spg_t, epoch_t*, ceph::bufferlist*)' thread 7f052ae89980 time 2017-04-09 01:48:49.853858
2017-04-09T01:48:49.850 INFO:teuthology.orchestra.run.smithi051.stderr:osd/PG.cc: 2967: FAILED assert(values.size() == 2)
```

Do you think this PR is OK to merge after the v10.2.7 tag is added?

**Comment by dillaman** [comment]
@smithfarm :+1:

**Comment by smithfarm** [comment]
@dillaman Sorry - could you click on the review, then I'll merge.

**Pull request merged**
