### PR TITLE
nautilus: ceph-volume: add raw (--bluestore) mode 

### PR DESCRIPTION
**Pull request by leseb**
## Checklist
- Backport of https://github.com/ceph/ceph/pull/32095
- [ ] References tracker ticket: https://tracker.ceph.com/issues/43669
- [ ] Updates documentation if necessary - N/A
- [ ] Includes tests for new functionality or reproducer for bug - N/A

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by jan--f** [comment]
Probably ideal to wait for #32655 and backport this as well in one go.

**Comment by leseb** [comment]
> Probably ideal to wait for #32655 and backport this as well in one go.

Thanks!

**Comment by leseb** [comment]
> > Probably ideal to wait for #32655 and backport this as well in one go.
> 
> Thanks!

I'll do a bulk backport then.

**Comment by leseb** [comment]
@jan--f updated with f3dca3bfa3d53b7e7a5500f302d89bed0dc04173. PTAL

**Comment by jan--f** [comment]
jenkins test ceph-volume tox

**Comment by leseb** [comment]
@jan--f CI is green :-)

**Comment by jan--f** [comment]
This part at least :)

**Pull request merged**
