### PR TITLE
install-deps.sh: use GCC-9 on bionic

### PR DESCRIPTION
**Pull request by tchaikov**
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by tchaikov** [comment]
see also https://github.com/ceph/ceph-build/pull/1315

**Comment by tchaikov** [comment]
retest this please.

**Comment by tchaikov** [comment]
- http://pulpito.ceph.com/kchai-2019-06-09_04:37:10-rados-wip-kefu-testing-2019-06-09-0009-distro-basic-mira/
- http://pulpito.ceph.com/kchai-2019-06-11_01:51:33-rados-wip-kefu-testing-2019-06-09-0009-distro-basic-smithi/

test failures tracked by 

- http://tracker.ceph.com/issues/17882
- http://tracker.ceph.com/issues/40120
- the misdirected op issue is not related to this issue.

**Comment by markhpc** [comment]
This broke install-deps.sh for me on my bionic dev box:

```
nhm@mocha:~/src/markhpc/ceph$ ./install-deps.sh 
Using apt-get to install dependencies
Reading package lists... Done
Building dependency tree       
Reading state information... Done
equivs is already the newest version (2.1.0).
devscripts is already the newest version (2.17.12ubuntu1.1).
0 upgraded, 0 newly installed, 0 to remove and 539 not upgraded.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
dpkg-dev is already the newest version (1.19.0.5ubuntu2.1).
0 upgraded, 0 newly installed, 0 to remove and 539 not upgraded.
update-alternatives: error: no alternatives for gcc
update-alternatives: error: alternative g++ can't be slave of gcc: it is a master alternative
```

subsequently it left the system without a working /usr/bin/gcc (which could be fixed by manually running update-alternatives or reinstalling the gcc package).  Removing this change fixed install-deps for me.  Note that gcc-9 is in fact installed.

**Pull request merged**
