### PR TITLE
mgr/cephadm: Get host facts data in host cache

### PR DESCRIPTION
**Pull request by jmolmo**
Include "cephadm gather-facts" information in host cache

Signed-off-by: Juan Miguel Olmo Martínez <jolmomar@redhat.com>

### CODE REVIEW

**Review by sebastian-philipp — APPROVED** [review]

**Review by sebastian-philipp — CHANGES_REQUESTED** [review]
ah, just discovered that you also need to add this to 

https://github.com/ceph/ceph/blob/59c6ba580c025759bd8a8dabe046c05861a773f4/src/pybind/mgr/cephadm/inventory.py#L329-L349

**Comment by tchaikov** [comment]
- https://pulpito.ceph.com/kchai-2020-11-27_14:17:32-rados-wip-kefu-testing-2020-11-27-2029-distro-basic-smithi/
- https://pulpito.ceph.com/kchai-2020-11-28_00:28:33-rados-wip-kefu-testing-2020-11-27-2029-distro-basic-smithi/

the failure of "mon-last-epoch-clean.sh" is addressed by #38239 
the cephadm failure is due to out of quota of requests to docker.io

**Review by sebastian-philipp — APPROVED** [review]

**Comment by sebastian-philipp** [comment]
* https://pulpito.ceph.com/jolmomar-2020-12-03_10:21:59-rados:cephadm-wip-jmolmo-testing-2020-12-02-1452-distro-basic-smithi/
rerun:
* https://pulpito.ceph.com/swagner-2020-12-04_10:02:29-rados:cephadm-wip-jmolmo-testing-2020-12-02-1452-distro-basic-smithi/

**Comment by sebastian-philipp** [comment]
jenkins test make check

**Comment by sebastian-philipp** [comment]
jenkins test api

**Comment by sebastian-philipp** [comment]
jenkins test api

**Comment by sebastian-philipp** [comment]
jenkins test api

**Pull request merged**
