### PR TITLE
jewel: rgw: Use decoded URI when verifying TempURL

### PR DESCRIPTION
**Pull request by asheplyakov**
http://tracker.ceph.com/issues/18626

### CODE REVIEW

**Comment by asheplyakov** [comment]
@Werkov: IMHO that mixing doesn't look nice. Extra memory allocations  due to concatenation of strings in temp_url_gen_sig is not nice either. On the other hand I'd like to keep changes minimal to avoid regressions.

**Comment by Werkov** [comment]
The minimal change would be `s/s->info.request_uri/s->decoded_uri/`, wouldn't it?

(Potentially, separating string handling optimization (covering both `allowed_paths` and `allowed_methods`) into another backport. Does that sound good to you?)

**Comment by smithfarm** [comment]
See http://tracker.ceph.com/projects/ceph-releases/wiki/HOWTO_backport_commits (General Guidelines, first bullet point) and http://tracker.ceph.com/projects/ceph-releases/wiki/HOWTO_review_backport_PRs

**Comment by smithfarm** [comment]
(I see now this is a jewel backport, but the comments above still apply.)

**Comment by asheplyakov** [comment]
@Werkov 
> The minimal change would be s/s->info.request_uri/s->decoded_uri/, wouldn't it?

Agree, updated the patch

@smithfarm 
> General Guidelines, first bullet point

Cherry-picking the master commit (4e1318f4dcbfd64c3ec94f4addf6e38ddd6c013a) requires quite a number of unrelated changes and contradicts to " the most minimal way possible" requirement. Should I cherry-pick that commit (and its prerequisites) anyway?

**Comment by smithfarm** [comment]
> Should I cherry-pick that commit (and its prerequisites) anyway?

Definitely not :-)

**Comment by smithfarm** [comment]
Needs integration testing before merge, though.

**Comment by smithfarm** [comment]
@yehudasa This passed an rgw suite at http://tracker.ceph.com/issues/19538#note-24

OK to merge?

**Comment by smithfarm** [comment]
@yehudasa Ping

**Pull request merged**
