### PR TITLE
systemd/ceph-radosgw-prestart.sh: remove

### PR DESCRIPTION
**Pull request by liewegas**
This is unpackaged and unused.

Signed-off-by: Sage Weil <sage@redhat.com>

### CODE REVIEW

**Comment by liewegas** [comment]
@smithfarm i think you guys needed this downstream before.. do you still?

**Comment by smithfarm** [comment]
@liewegas This patch LGTM. @osynge @kmroz care to review?

**Comment by smithfarm** [comment]
For the record, `ceph-radosgw-prestart.sh` used to be called from `ceph-radosgw@.service` but this was dropped in 4d10dc134b817160bab6aecb9f5c08fb2d4f08e6

**Comment by osynge** [comment]
Sage is wanting to remove all config possible from the ${cluster}.conf file.

The main reason for this was to support rgw apache and avoid typos and reduce support effort by failing fast. If this becomes an issue  suitable validation can be placed in rgw and in my opinion is better placed in rgw.

So I am happy for it to be dropped.

**Comment by kmroz** [comment]
I don't see a problem with removing this either. I've been running rgw successfully in master for a couple weeks now. The only glitch thus far is logfile permissions.

However, are we really moving away from configuring ceph via $cluster.conf?

**Comment by liewegas** [comment]
On Fri, 5 Feb 2016, Karol Mroz wrote:
> However, are we really moving away from configuring ceph via $cluster.conf?

No.  We're only dropping startup-related options, that will go in 
/etc/{sysconfig,default}/ceph going forward.  There was a bunch of cruft 
that accumulated over the years that we can drop while moving to 
systemd.

**Comment by kmroz** [comment]
@sage - Ah, ok, thanks. @smithfarm also directed me to the ceph-devel thread related to your proposed config location changes (Subject: /var/lib/ceph/*/*/config) - reading...

**Pull request merged**
