### PR TITLE
test/cls_cas: allow multi hobjects tracked by cls_cas

### PR DESCRIPTION
**Pull request by tchaikov**
in d2737fd41a146e8efe3162cdc39845226bd5a756, we started to use multiset
for tracking the references of hobject for snapshot support. as the same
hobject maps to multiple snapshots. and we don't want to consider
different snapshots as the same entry tracked by cls_cas.

but cls_cas.dup_get() still tries to verify that the `get` operation
is able to dedup the same referenced "source". but this does not apply
to "by_object" trunk ref type anymore.

since we cannot check/choose the chunk ref type used by OSD from the
client of the cls_cas, in this change, cls_cas.dup_get() is updated
to adapt the change solely for "by_object". otherwise we could skip
this test for "by_object" type and/or define another test for other
chunk ref types.

Fixes: https://tracker.ceph.com/issues/50339
Signed-off-by: Kefu Chai <kchai@redhat.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Review by myoungwon — APPROVED** [review]

**Comment by tchaikov** [comment]
```
2021-04-15 03:49:34,371.371 INFO:__main__:ERROR: test_version (tasks.mgr.dashboard.test_api.VersionReqTest)
2021-04-15 03:49:34,371.371 INFO:__main__:----------------------------------------------------------------------
2021-04-15 03:49:34,371.371 INFO:__main__:Traceback (most recent call last):
2021-04-15 03:49:34,371.371 INFO:__main__:  File "/home/jenkins-build/build/workspace/ceph-api/qa/tasks/mgr/dashboard/helper.py", line 271, in setUp
2021-04-15 03:49:34,371.371 INFO:__main__:    self.wait_for_health_clear(self.TIMEOUT_HEALTH_CLEAR)
2021-04-15 03:49:34,371.371 INFO:__main__:  File "/home/jenkins-build/build/workspace/ceph-api/qa/tasks/ceph_test_case.py", line 172, in wait_for_health_clear
2021-04-15 03:49:34,372.372 INFO:__main__:    self.wait_until_true(is_clear, timeout)
2021-04-15 03:49:34,372.372 INFO:__main__:  File "/home/jenkins-build/build/workspace/ceph-api/qa/tasks/ceph_test_case.py", line 203, in wait_until_true
2021-04-15 03:49:34,372.372 INFO:__main__:    raise TestTimeoutError("Timed out after {0}s".format(elapsed))
2021-04-15 03:49:34,372.372 INFO:__main__:tasks.ceph_test_case.TestTimeoutError: Timed out after 60s
```

**Comment by tchaikov** [comment]
jenkins test api

**Comment by tchaikov** [comment]
being tested at https://pulpito.ceph.com/kchai-2021-04-15_05:42:24-rados:basic-wip-50339-kefu-distro-basic-smithi/

**Comment by tchaikov** [comment]
api test failure tracked by https://tracker.ceph.com/issues/50374

**Review by athanatos — APPROVED** [review]

**Pull request merged**
