### PR TITLE
mimic: ceph-volume: refuse to zap mapper devices

### PR DESCRIPTION
**Pull request by andrewschoen**
backport of #22764

### CODE REVIEW

**Comment by jdurgin** [comment]
jenkins test ceph-volume tox

**Comment by jdurgin** [comment]
jenkins test ceph-volume lvm all

**Comment by andrewschoen** [comment]
@jdurgin repos hadn't been built for the functional tests yet, which is why those are failing. Those are building here: https://shaman.ceph.com/builds/ceph/backport-mimic-22764/

**Comment by andrewschoen** [comment]
jenkins test ceph-volume lvm all

**Comment by alfredodeza** [comment]
jenkins test ceph-volume all

**Comment by andrewschoen** [comment]
jenkins test ceph-volume all

**Pull request merged**
