### PR TITLE
doc/cephfs/nfs: Remove outdated doc related to rook

### PR DESCRIPTION
**Pull request by varshar16**
The doc is outdated because the mentioned orch commands have changed[1] and
using dashboard backend script to create exports is buggy[2].

[1] https://docs.ceph.com/en/latest/mgr/orchestrator/#current-implementation-status
[2] https://github.com/rook/rook/issues/6147

Fixes: https://tracker.ceph.com/issues/47784
Signed-off-by: Varsha Rao <varao@redhat.com>

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by batrick** [comment]
(adding this to a test branch to troubleshoot build issues.)

**Review by batrick — CHANGES_REQUESTED** [review]
Please add an explanation to the commit message. i.e. why is it out-dated?

**Comment by varshar16** [comment]
> (adding this to a test branch to troubleshoot build issues.)

Done!

**Comment by varshar16** [comment]
> Please add an explanation to the commit message. i.e. why is it out-dated?

Done!

**Review by batrick — APPROVED** [review]

**Pull request merged**
