### PR TITLE
pacific: crash: pthread_mutex_lock()

### PR DESCRIPTION
**Pull request by batrick**
https://tracker.ceph.com/issues/57183

### CODE REVIEW

**Review by ljflores — APPROVED** [review]

**Comment by yuriw** [comment]
jenkins test this please

**Comment by yuriw** [comment]
@batrick  this is ready for merge but filing make check

**Comment by batrick** [comment]
jenkins test make check

**Comment by batrick** [comment]
jenkins test make check

**Comment by batrick** [comment]
jenkins test api

**Comment by batrick** [comment]
jenkins test make check

**Comment by tchaikov** [comment]
jenkins test make check

**Comment by tchaikov** [comment]
jenkins test api

**Comment by tchaikov** [comment]
jenkins test make check

**Comment by batrick** [comment]
jenkins test make check

**Comment by tchaikov** [comment]
jenkins test make check

**Pull request merged**
