### PR TITLE
mgr/cephadm:  update default NVMEoF container image version

### PR DESCRIPTION
**Pull request by adk3798**
Otherwise the nvmeof daemon fails to start up
```
i148-njpgei[69585]: Traceback (most recent call last):
i148-njpgei[69585]:   File "/usr/lib64/python3.9/runpy.py", line 197, in _run_module_as_main
i148-njpgei[69585]:     return _run_code(code, main_globals, None,
i148-njpgei[69585]:   File "/usr/lib64/python3.9/runpy.py", line 87, in _run_code
i148-njpgei[69585]:     exec(code, run_globals)
i148-njpgei[69585]:   File "/src/control/__main__.py", line 43, in <module>
i148-njpgei[69585]:     gateway.serve()
i148-njpgei[69585]:   File "/src/control/server.py", line 177, in serve
i148-njpgei[69585]:     omap_lock = OmapLock(omap_state, gateway_state)
i148-njpgei[69585]:   File "/src/control/state.py", line 201, in __init__
i148-njpgei[69585]:     self.omap_file_lock_retry_sleep_interval = self.omap_state.config.getint_with_default("gateway",
i148-njpgei[69585]:   File "/src/control/config.py", line 47, in getint_with_default
i148-njpgei[69585]:     return self.config.getint(section, param, fallback=value)
i148-njpgei[69585]:   File "/usr/lib64/python3.9/configparser.py", line 818, in getint
i148-njpgei[69585]:     return self._get_conv(section, option, int, raw=raw, vars=vars,
i148-njpgei[69585]:   File "/usr/lib64/python3.9/configparser.py", line 808, in _get_conv
i148-njpgei[69585]:     return self._get(section, conv, option, raw=raw, vars=vars,
i148-njpgei[69585]:   File "/usr/lib64/python3.9/configparser.py", line 803, in _get
i148-njpgei[69585]:     return conv(self.get(section, option, **kwargs))
i148-njpgei[69585]: ValueError: invalid literal for int() with base 10: '1.0'
```
I've been told 1.2.5 has a patch that allows this value to be a float

Fixes: https://tracker.ceph.com/issues/65718

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [x] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Comment by adk3798** [comment]
have just updated the PR from changing the value to an integer to using a different NVMEoF image that should be able to handle the float value after discussion with a member of the NVMEoF team.

**Comment by adk3798** [comment]
jenkins test make check

**Review by phlogistonjohn — APPROVED** [review]
seems ok to me

**Comment by adk3798** [comment]
https://pulpito.ceph.com/adking-2024-05-09_03:09:40-orch:cephadm-wip-adk-testing-2024-05-08-1927-distro-default-smithi/

failures:
- 21 `in cluster log` type failures that are still being cleaned up, known issue
- 3 mds_upgrade_sequence failures, known issue
- 1 test failed installing `ceph-fuse` ` Status code: 503 for https://mirrors.centos.org/metalink?repo=centos-baseos-9-stream&arch=x86_64&protocol=https,http`, happens on occasion, nothing to block merging over

Overall, nothing unexpected in the run

**Pull request merged**
