### PR TITLE
nautilus: ceph-volume: major batch refactor

### PR DESCRIPTION
**Pull request by jan--f**
This is an untracked backport

---

backport of #34740

Also add:
* [x] #37531
* [x] #37545 
* [x] #37577
* [x] #37591

This drops two commits: 28e33f3025d03008b46b56989e5d939682b5720d and 0f6f2b46a347c41a15f7ab2d532efb299f226698, as the targeted code is not present in nautilus, and adds one nautilus-specific doc commit.

### CODE REVIEW

**Comment by jan--f** [comment]
jenkins test ceph-volume all

**Comment by jan--f** [comment]
jenkins test ceph-volume tox

**Comment by smithfarm** [comment]
@jan--f This nautilus backport PR has 27 commits, which is 4 less than the corresponding master PR #34740 

Could you explain this discrepancy in the PR description, please?

**Comment by jan--f** [comment]
> @jan--f This nautilus backport PR has 27 commits, which is 4 less than the corresponding master PR #34740
> 
> Could you explain this discrepancy in the PR description, please?

Thansk a lot. Updated the commits as well as the description.

**Comment by smithfarm** [comment]
Thanks, @jan--f - I added a mention of the nautilus-only doc commit, too, to make the math work out:

master PR: 31 commits
nautilus PR: -2 commits (not cherry-picked) +1 added = 30 commits

**Comment by smithfarm** [comment]
@jan--f: do we need to cherry-pick  #37545 here as well?

**Comment by rishabh-d-dave** [comment]
jenkins test make check

**Comment by jan--f** [comment]
ok this is ready to merge imo.

**Comment by jan--f** [comment]
retest this please

**Comment by jan--f** [comment]
jenkins test ceph-volume tox

**Comment by smithfarm** [comment]
@jan--f Could you add a PendingReleaseNote?

**Comment by rishabh-d-dave** [comment]
@jan--f 

[Jan wrote](https://github.com/ceph/ceph/pull/37522#issuecomment-703668900)
> ok this is ready to merge imo.

Agreed. I'll approve it after the change request for PendingReleaseNote gets resolved

**Comment by jan--f** [comment]
> Agreed. I'll approve it after the change request for PendingReleaseNote gets resolved

Done.

**Comment by jan--f** [comment]
> > ok this is ready to merge imo.
> 
> Agreed. I'll approve it after the change request for PendingReleaseNote gets resolved

Ping @rishabh-d-dave

**Comment by rishabh-d-dave** [comment]
> Thanks, @jan--f - I added a mention of the nautilus-only doc commit, too, to make the math work out:
> 
> master PR: 31 commits
> nautilus PR: -2 commits (not cherry-picked) +1 added = 30 commits

Plus 4 more commits from #37531, #37545, #37577 and #37591.

**Review by rishabh-d-dave — APPROVED** [review]

**Comment by yuriw** [comment]
@jan--f @Abhishekvrshny FYI https://jenkins.ceph.com/job/ceph-volume-test/440/

**Comment by jan--f** [comment]
@yuriw guess you meant to tag @theanalyst :)

This error can be ignored. The simple test suite is obsolete for nautilus and later, as it tests taking over ceph-disk deployed OSDs and nautilus is the first release to not ship ceph-disk anymore.

I'm currently going through the functional tests and respective jenkins definitions to add some better strucuture.

In any case, please go ahead.

**Pull request merged**
