### PR TITLE
jewel: common: radosstriper: protect aio_write API from calls with 0 bytes

### PR DESCRIPTION
**Pull request by shinobu-x**
http://tracker.ceph.com/issues/18815

### CODE REVIEW

**Comment by smithfarm** [comment]
@shinobu-x Thanks for the backport!

**Comment by shinobu-x** [comment]
@smithfarm Thanks for your advice too :) Please let me know if anything I should or should *NOT*. I'm still learning how I could do SOME effectively and properly.

**Comment by smithfarm** [comment]
@shinobu-x Would you like to try working with us on the stable releases? You could look at http://tracker.ceph.com/projects/ceph-releases/wiki to see in general what this entails. I also forwarded you one of our "Call for participation" emails.

**Comment by shinobu-x** [comment]
@smithfarm Thanks for your proposal. If Sage (and maybe Loic) is (are) o.k, I would be definitely fine to work with your team.

**Comment by smithfarm** [comment]
@shinobu-x Sound good! Discuss with them and let me know, OK? Looking forward to working with you.

**Comment by dachary** [comment]
@shinobu-x of course I agree, that would be great !

**Comment by shinobu-x** [comment]
@dachary thank you :)

**Comment by shinobu-x** [comment]
@smithfarm Please let me know whatever I could do potentially.

**Comment by smithfarm** [comment]
@shinobu-x An easy and satisfying way to get started is cherry-picking PRs/commits from master to the stable branches (now primarily jewel and kraken). Here's how to find the backport queues:

Go to the Ceph project in the tracker [1] and click on "Issues". Then, on the right side, under "CUSTOM QUERIES", you will see links like "Backports: jewel", "Backports: kraken". You can take any backports that are in status "New".

There are some subtleties, but once you do it a couple times it's usually not hard at all. Detailed instructions for backporting commits can be found here: http://tracker.ceph.com/projects/ceph-releases/wiki/HOWTO_backport_commits

If you find a backport is non-trivial due to conflicts, you can set the status to "Need More Info" and assign the backport tracker issue to the developer. Then, go on to the next backport :-)

Also, if you have ideas for how to improve the documentation, let us know!

[1] http://tracker.ceph.com/projects/ceph?jump=welcome

**Comment by shinobu-x** [comment]
@smithfarm Thank you very much for your introduction in detail. I will try to do some following that.

**Comment by smithfarm** [comment]
**Note: this PR is targeting the 10.2.8 release - not to be merged until v10.2.7 tag is added!**

@tchaikov This PR was included in the rados run at http://tracker.ceph.com/issues/19538#note-4 which had the following results:

Of 227 total jobs:

* 222 passed on first try
* 3 passed on second try
* remaining 2 are problematic

(see http://tracker.ceph.com/issues/19538#note-4 for details)

Do you think this run is sufficient to merge this PR once the v10.2.7 tag has been added?

**Pull request merged**
