### PR TITLE
osd/ECBackend: code cleanup

### PR DESCRIPTION
**Pull request by yanghonggang**
Signed-off-by: Yang Honggang <yanghonggang_yewu@cmss.chinamobile.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [x] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by yanghonggang** [comment]
@zenomri  please help to review

**Comment by yanghonggang** [comment]
jenkins test make check

**Comment by yanghonggang** [comment]
@yuvalif this is jspan related, please help to review

**Review by zenomri — APPROVED** [review]
Thanks!

those leftovers come from this change/cleanup:
https://github.com/ceph/ceph/pull/44684/files#diff-f97dc9668558e7cf949d7994ae9f3813cb1d545b720f3e807c5b2709bbf07019L951-L954

**Comment by yuvalif** [comment]
dear core team, can I merge without QA?

**Comment by yanghonggang** [comment]
ping @yuvalif

**Comment by ronen-fr** [comment]
@yuvalif - I think it can be merged

**Review by tchaikov — APPROVED** [review]

**Pull request merged**
