### PR TITLE
ceph.spec.in: add BuildRequires: systemd

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/13860 Fixes: #13860

Signed-off-by: Nathan Cutler <ncutler@suse.com>

### CODE REVIEW

**Comment by ktdreyer** [comment]
I'm not a fan of running `systemd-tmpfiles` in `%post` (versus listing the temp location with `%files`) but iirc this is a SUSE vs Fedora convention thing, and we might as well continue with the current implementation, so :+1: if this helps OBS

**Comment by smithfarm** [comment]
@ktdreyer I think I see what you mean. We could include the files in `%files` and drop `systemd-tmpfiles` from `%post`. Their inclusion in `%files` would ensure that they are created when the package is installed. After the next reboot they will disappear, but `systemd-tmpfiles` is run at boot and will re-create them. Correct?

**Comment by ktdreyer** [comment]
You've got it exactly!

**Comment by smithfarm** [comment]
@ktdreyer I asked the openSUSE maintainers about this, and they are pushing back:

```
The extra directories/files make rpm slower than it already is (its database is
really horribly laid out), and when you are in a rescue system, `rpm -V` will
needlessy complain about the missing file if you did not mark it %ghost,
%noverify, or some combination thereof.

Even the remotely legitimate case of removing /var/run/xyz directories on
  (a) package removal, and
  (b) on ancient system where /var/run is not yet a tmpfs
can be rejected as well, because the program may create any number of run files
which rpm definitely is not tracking and therefore won't remove.

IOW, save yourself the trouble of listing /var/run/xyz.
```

Note: we already had the files in `%files` before (with `%ghost` IIRC), and we switched to running `systemd-tmpfiles` in `%post` . . . if we want to go back to that, we would most likely have to conditionalize it so it doesn't apply to openSUSE, and I would try to avoid that if possible.

**Comment by ktdreyer** [comment]
Thanks for asking the maintainers about this. I think using `%ghost` is preferred in Fedora, but this is such a small issue, let's just continue down the path and BR: systemd here.

**Comment by smithfarm** [comment]
Added a patch to satisfy openSUSE maintenance policy.

**Comment by ktdreyer** [comment]
Can we just define `%tmpfiles_create` if it is undefined, and avoid the distro conditionals? I'm guessing it's something like this:

```
%{!?tmpfiles_create: %global tmpfiles_create %(systemd-tmpfiles --create)}
```

**Comment by smithfarm** [comment]
In openSUSE it is defined in `systemd-rpm-macros` like so:

```
%tmpfiles_create() \
[ -x /usr/bin/systemd-tmpfiles ] && \
	/usr/bin/systemd-tmpfiles --create %{?*} || : \
```

Presumably it is not defined in Fedora, etc. so your idea should work. The only issue I see is that AFAICT I'm supposed to provide `%{_tmpfilesdir}/ceph-common.conf` as an *argument* to `systemd-tmpfiles`

Thanks for reviewing! I will re-do the commit accordingly.

**Comment by smithfarm** [comment]
How does this look?

**Comment by smithfarm** [comment]
This is working nicely in the OBS. Removing [DNM].

**Comment by smithfarm** [comment]
@ktdreyer Ping?

**Comment by ktdreyer** [comment]
LGTM, thanks

**Pull request merged**
