### PR TITLE
hammer: subuser rm fails with status 125

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/16190

### CODE REVIEW

**Comment by smithfarm** [comment]
@oritwas Please review? This appears to be a dependency of #7184

**Comment by oritwas** [comment]
lgtm

**Comment by smithfarm** [comment]
@yehudasa This PR passed an rgw suite with some valgrind-related failures that appear harmless - see http://tracker.ceph.com/issues/15895#note-19 

Do you think this PR is ready to merge?

**Comment by oritwas** [comment]
lgtm

**Pull request merged**
