### PR TITLE
xio: correctly set XioConnection features with fake features for now

### PR DESCRIPTION
**Pull request by vuhuong**
Correctly set XioConnection features with fake features until support
in future

Signed-of-by: Vu Pham <vu@mellanox.com>

### CODE REVIEW

**Comment by yuyuyu101** [comment]
I guess we could assign with m->local_features & XIO_UNSUPPORTED_FEATURES?

**Comment by mattbenjamin** [comment]
That seems fine.  Proper negotiation should come shortly, but that still might be a better way to express the baseline.

**Comment by vuhuong** [comment]
Shouldn't it be (m->local_features & XIO_ALL_FEATURES) or define XIO_UNSUPPORTED_FEATURES then (m->local_features & ~XIO_UNSUPPORTED_FEATURES)

**Comment by mattbenjamin** [comment]
XIO_ALL_FEATURES was just magical, iirc.  Maybe we should however build the positive list of features and define that.

**Comment by vuhuong** [comment]
XIO_ALL_FEATURES is defined as:

#define XIO_ALL_FEATURES (CEPH_FEATURES_ALL & \
                          ~CEPH_FEATURE_MSGR_KEEPALIVE2)

All messengers has m->local_features set to 0 except osd/cluster messenger.
Using m->local_features & XIO_xxx for those messengers will always be 0 and this will cause a crash.

I guess until xio has a proper negotiation, set_features(XIO_ALL_FEATURES) is good for now.

**Comment by mattbenjamin** [comment]
Ok

**Pull request closed without merging**
