### PR TITLE
qa/suites: add minimal performance suite

### PR DESCRIPTION
**Pull request by neha-ojha**
This PR adds a perf-basic suite to be run as a part of teuthology nightly runs. This is a subset of the rados/perf suite and generates 4 jobs.

Signed-off-by: Neha Ojha <nojha@redhat.com>

### CODE REVIEW

**Comment by neha-ojha** [comment]
@yuriw sure.

**Comment by yuriw** [comment]
running http://pulpito.front.sepia.ceph.com:80/yuriw-2018-03-28_22:09:43-perf-basic-master-distro-basic-ovh/

**Comment by neha-ojha** [comment]
http://pulpito.front.sepia.ceph.com/yuriw-2018-03-29_00:50:31-perf-basic-master-distro-basic-smithi/

**Comment by neha-ojha** [comment]
retest this please

**Comment by varadakari** [comment]
Do we still need to test filestore? Or is it for a base line reference?

**Comment by neha-ojha** [comment]
It is for baseline reference in this context.

**Comment by neha-ojha** [comment]
retest this please

**Comment by yuriw** [comment]
added suite to nightlies against master
@neha-ojha do we want it on luminous ?

**Comment by neha-ojha** [comment]
@yuriw just master is fine for now.

**Pull request merged**
