### PR TITLE
rbd:add feature about export with snapshot info

### PR DESCRIPTION
**Pull request by caibo2014**
you can see more info here:
http://tracker.ceph.com/issues/13186
http://tracker.ceph.com/issues/13156

### CODE REVIEW

**Comment by dillaman** [comment]
@caibo2014 The rbd ```export-diff``` and ```import-diff``` commands do what you are attempting to implement.

**Comment by caibo2014** [comment]
@dillaman Hi,
export-diff only export part of a snapshot , you can export all use this , very convenient.
and also export-diff must have two snapshot, but this not.
am I think right?

**Comment by dillaman** [comment]
@caibo2014 The import/export tools are supposed to provide a mechanism to extract a full, *raw* image.  We should not be adding metadata to the export.  

No, export-diff does not require two snapshots.  I can run ```rbd export-diff image@snap1 export``` to generate an export from image creation to snap1.

**Comment by caibo2014** [comment]
@dillaman 
Okay, I know. 
Well, if I add a feature in "rbd export-diff" for export all the snapshots, you think it feasible?
If it's ok, I will change my code in "rbd export-diff" add a options "--with-all-snap"

**Comment by dillaman** [comment]
@caibo2014 That sounds like a better approach.  I might suggest naming the option something like ```--incremental-snaps``` since you should still be able to supply a beginning and end snapshot (thus not all snapshots will be included).

**Comment by dillaman** [comment]
@caibo2014 Are you still working on this feature?  If not, can I close this PR?

**Comment by caibo2014** [comment]
YES!!!
I will impl this sometime.

**Pull request closed without merging**
