### PR TITLE
ceph-objectstore-tool: Add option "dump-import" to examine an export

### PR DESCRIPTION
**Pull request by dzafman**

### CODE REVIEW

**Comment by dzafman** [comment]
Passes qa/run-standalone.sh ceph_objectstore_tool.py

**Comment by dzafman** [comment]
I haven't added any testing of this new feature.

**Comment by liewegas** [comment]
Would something as simple as an infrequent call from the thrasher that pipes to a json parser/validator or dev/null be sufficient?

**Comment by dzafman** [comment]
@liewegas I'll add a "--op dump-import" before every "--op import" in qa/standalone/special/ceph_objectstore_tool.py

**Pull request merged**
