### PR TITLE
Wip 17916 divergent

### PR DESCRIPTION
**Pull request by gregsfortytwo**
We were previously not clearing the divergent_priors set off disk in most cases. This PR fixes that so we *do* clear them, and — with a config option set (off by default) — does not assert out when it encounters a situation which is most likely to have been caused that way.

### CODE REVIEW

**Comment by gregsfortytwo** [comment]
I ran the first two patches against tests which included divergent_priors and got one failure that sort of looked real, but I didn't dig too hard into: http://pulpito.ceph.com/gregf-2017-04-08_00:09:21-rados-wip-17916-divergent---basic-mira/

This was included in a bunch of runs with the snaptrim code, which was noisy against jewel but didn't flag anything, such as http://pulpito.ceph.com/gregf-2017-04-16_16:10:52-rados-wip-jewel-snaps-test---basic-mira/

I'm just waiting on ceph-ci to finish building this version before I run it through a real suite on its own.

**Comment by smithfarm** [comment]
@gregsfortytwo Can you very briefly explain (preferably in the commit message(s)) why this cannot be cherry-picked from master?

**Comment by jdurgin** [comment]
looks like the tests used the clear() method.

I agree the divergent_priors2 test failure is unrelated - looks like rados + jewel hasn't been run much on mira, that test may have a race condition.

**Comment by jdurgin** [comment]
Otherwise looks good.

**Comment by gregsfortytwo** [comment]
@jdurgin, eek, guess I wasn't building those. Dropped that patch.
Although interestingly shaman has the packages hosted just fine, so I guess it doesn't build all the tests either. http://pulpito.ceph.com/gregf-2017-04-18_04:46:12-rados-wip-17916-divergent---basic-smithi/ looks pretty good but has one or two unfamiliar failures I'll check out in the morning.

**Comment by gregsfortytwo** [comment]
@smithfarm it's in the ticket. http://tracker.ceph.com/issues/17916#note-2
> Note: this has been rewritten in master since jewel, no such thing as divergent priors anymore.

Probably some portion of it will end up in kraken, maybe a bit in master, but that's not clear and all the reported instances were in Jewel so I wrote the fix there for everybody's ease. ;)

**Pull request merged**
