### PR TITLE
mds: explain clients retaining Fb during xlock

### PR DESCRIPTION
**Pull request by batrick**
Fixes: https://tracker.ceph.com/issues/64198

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Comment by batrick** [comment]
I'm not sure yet if this is necessary.

**Comment by batrick** [comment]
This was a deliberate decision in 6ffdd4367bc324d8ab9acdf19377bd4a081d2c86 but unfortunately not sure why. @liewegas if you are around and can recall, do you know why you did this? It ended up requiring at least one follow-on fix in 9c65920e7f6febe294e25a67473693ce6f9adfa7 but I don't really understand why we would want to allow clients to continue holding `Fbc` when the filelock is xlocked.

**Comment by vshankar** [comment]
jenkins tests api

**Comment by vshankar** [comment]
> This was a deliberate decision in [6ffdd43](https://github.com/ceph/ceph/commit/6ffdd4367bc324d8ab9acdf19377bd4a081d2c86) but unfortunately not sure why. @liewegas if you are around and can recall, do you know why you did this? It ended up requiring at least one follow-on fix in [9c65920](https://github.com/ceph/ceph/commit/9c65920e7f6febe294e25a67473693ce6f9adfa7) but I don't really understand why we would want to allow clients to continue holding `Fbc` when the filelock is xlocked.

I agree, but, yeh can't tell why Fcb caps were allowed in xlock state o_O

**Comment by vshankar** [comment]
jenkins test api

**Comment by vshankar** [comment]
@batrick This is marked as DNM, but I guess we can still go ahead when this is put through fs suite?

**Comment by batrick** [comment]
> @batrick This is marked as DNM, but I guess we can still go ahead when this is put through fs suite?

We can at least try testing it to see what blows up. I was hoping someone might come in and explain why it's necessary but no such luck :)

**Comment by batrick** [comment]
> > @batrick This is marked as DNM, but I guess we can still go ahead when this is put through fs suite?
> 
> We can at least try testing it to see what blows up. I was hoping someone might come in and explain why it's necessary but no such luck :)

I also wonder if we can consequently revert https://github.com/ceph/ceph/commit/9c65920e7f6febe294e25a67473693ce6f9adfa7 as well.

**Comment by vshankar** [comment]
fs suite run here - https://pulpito.ceph.com/?branch=wip-vshankar-testing-20240217.015652

I'm a bit inclined to have a run with the issues that we currently face in fs suite sorted out first. So, I am deferring the merge for now.

**Comment by batrick** [comment]
> fs suite run here - https://pulpito.ceph.com/?branch=wip-vshankar-testing-20240217.015652
> 
> I'm a bit inclined to have a run with the issues that we currently face in fs suite sorted out first. So, I am deferring the merge for now.

That's reasonable.

I think the argument to be made for a client retaining `Fcb` is that they cannot actually "flush" the buffered writes. That means we can potentially rapidly recall `Fw` without waiting for buffered writes to be flushed. So perhaps this is simply an optimization. I don't think it really matters for quiesce either since writes that have not been `fsync`'d are not guaranteed to be in a snapshot.

**Comment by leonid-s-usov** [comment]
I don't think we need to change this. Indeed, as Patrick mentioned, buffered data is totally fine because it's the client's responsibility to flush buffers for persisted checkpoints. Without WR the client can't flush the buffered writes to the OSDs, but we can't and shouldn't control what the apps are doing while the flushes aren't allowed. They may be buffering anywhere above the client cached - at the OS or even app levels. 

As for the cached data, please note that file XLOCK doesn't allow writing to the xlocker, so it's safe to hold onto the caches. See the `wr` column in this snippet:

```
                      // stable     loner  rep state  r     rp   rd   wr   fwr  l    x    caps(any,loner,xlocker,replica)
    [LOCK_PREXLOCK]  = { LOCK_LOCK, false, LOCK_LOCK, 0,    XCL, 0,   0,   0,   0,   ANY, CEPH_CAP_GCACHE|CEPH_CAP_GBUFFER,0,0,0 },
    [LOCK_XLOCK]     = { LOCK_LOCK, false, LOCK_LOCK, 0,    XCL, 0,   0,   0,   0,   0,   CEPH_CAP_GCACHE|CEPH_CAP_GBUFFER,0,0,0 },
    [LOCK_XLOCKDONE] = { LOCK_LOCK, false, LOCK_LOCK, XCL,  XCL, XCL, 0,   0,   XCL, 0,   CEPH_CAP_GCACHE|CEPH_CAP_GBUFFER,0,CEPH_CAP_GSHARED,0 },
    [LOCK_XLOCKSNAP] = { LOCK_LOCK, false, LOCK_LOCK, 0,    XCL, 0,   0,   0,   0,   0,   CEPH_CAP_GCACHE,0,0,0 },
    [LOCK_LOCK_XLOCK]= { LOCK_PREXLOCK,false,LOCK_LOCK,0,   XCL, 0,   0,   0,   0,   XCL, CEPH_CAP_GCACHE|CEPH_CAP_GBUFFER,0,0,0 },
```

**Comment by vshankar** [comment]
> I don't think we need to change this. Indeed, as Patrick mentioned, buffered data is totally fine because it's the client's responsibility to flush buffers for persisted checkpoints. Without WR the client can't flush the buffered writes to the OSDs, but we can't and shouldn't control what the apps are doing while the flushes aren't allowed. They may as well be buffering above the cephfs client's cache - at the OS or the app levels.
> 
> As for the cached data, please note that file XLOCK doesn't allow writing for anybody, including the xlocker, so it's safe to hold onto the caches. See the `wr` column in this snippet:
> 
> ```
>                       // stable     loner  rep state  r     rp   rd   wr   fwr  l    x    caps(any,loner,xlocker,replica)
>     [LOCK_PREXLOCK]  = { LOCK_LOCK, false, LOCK_LOCK, 0,    XCL, 0,   0,   0,   0,   ANY, CEPH_CAP_GCACHE|CEPH_CAP_GBUFFER,0,0,0 },
>     [LOCK_XLOCK]     = { LOCK_LOCK, false, LOCK_LOCK, 0,    XCL, 0,   0,   0,   0,   0,   CEPH_CAP_GCACHE|CEPH_CAP_GBUFFER,0,0,0 },
>     [LOCK_XLOCKDONE] = { LOCK_LOCK, false, LOCK_LOCK, XCL,  XCL, XCL, 0,   0,   XCL, 0,   CEPH_CAP_GCACHE|CEPH_CAP_GBUFFER,0,CEPH_CAP_GSHARED,0 },
>     [LOCK_XLOCKSNAP] = { LOCK_LOCK, false, LOCK_LOCK, 0,    XCL, 0,   0,   0,   0,   0,   CEPH_CAP_GCACHE,0,0,0 },
>     [LOCK_LOCK_XLOCK]= { LOCK_PREXLOCK,false,LOCK_LOCK,0,   XCL, 0,   0,   0,   0,   XCL, CEPH_CAP_GCACHE|CEPH_CAP_GBUFFER,0,0,0 },
> ```

Well, that's a valid point. Unfortunately, the sheer lack of the cap protocol keeps us guessing and that has happened in the past.

**Comment by leonid-s-usov** [comment]
Yes, that's what I was referring to: since no wrlock operations are allowed in the XLOCK states, it should be safe to be holding on to the read cache by the clients.

**Comment by batrick** [comment]
> Yes, that's what I was referring to: since no wrlock operations are allowed in the XLOCK states, it should be safe to be holding on to the read cache by the clients.

I think there is still confusion here: an mdr with the `filelock` xlocked could do writes to the file. Generally, only the file size is changed, e.g. by `O_TRUNC` or `setattr(...CEPH_SETATTR_SIZE)`.

(So actually, for that reason, perhaps clients should probably not hold `Fc` but there must be other mechanisms in the MDS/client to account for this, at least for file size.)

**Comment by leonid-s-usov** [comment]
> an mdr with the filelock xlocked could do writes to the file.

This is unexpected, thanks for clarifying. Not yet sure if that's reasonable.

I found so far that the xlock is taken for
* client_open with O_TRUNC
* setattr
* setlayout
* setvxattr

technically, none of these operations modify the file contents. The truncate operation is ambiguous in this sense. I think the trick here is that size is technically an attribute, but that's just my speculation

**Comment by batrick** [comment]
> > an mdr with the filelock xlocked could do writes to the file.
> 
> This is unexpected, thanks for clarifying. Not yet sure if that's reasonable.
> 
> I found so far that the xlock is taken for
> 
>     * client_open with O_TRUNC
> 
>     * setattr
> 
>     * setlayout
> 
>     * setvxattr
> 
> 
> technically, none of these operations modify the file contents. The truncate operation is ambiguous in this sense. I think the trick here is that size is technically an attribute, but that's just my speculation

I think part of the problem is that there may be lack of clarity here regarding the filelock. I suppose one could argue that only clients should be allowed to change file data which would mean that this conversation is somewhat irrelevant. If all the MDS can do is change the file size, / layout (for empty files) then the `Fcb` caps are probably safe to be outstanding.

**Comment by batrick** [comment]
jenkins test make check

**Review by leonid-s-usov — APPROVED** [review]

**Pull request merged**
