### PR TITLE
mgr/mgr_module.py: fix doc for set_store/set_store_json

### PR DESCRIPTION
**Pull request by dmick**
Signed-off-by: Dan Mick <dan.mick@redhat.com>

### CODE REVIEW

**Comment by dmick** [comment]
No strong feeling.  I see set_store_json() as a bit of a "why bother" anyway; caller can always do the serialization

**Comment by jcsp** [comment]
The _json methods are indeed not really needed, I think at the time (they were originally for config settings) I was mainly motivated by trying to discourage people from inventing random plaintext serialisations.

**Comment by jcsp** [comment]
Huh, they don't even have any users any more, so let's rim 'em out!
https://github.com/ceph/ceph/pull/22661

**Comment by dmick** [comment]
Actually this can go independently from 22261

**Pull request merged**
