### PR TITLE
[do not review][DNM] -Wvla fixes

### PR DESCRIPTION
**Pull request by tchaikov**
as followup of #15342. seems it's non-trivial to be pedantic.

Signed-off-by: Kefu Chai <kchai@redhat.com>

### CODE REVIEW

**Comment by tchaikov** [comment]
@chardan @liewegas 

i'd recommend revert #15342 before we fix this. or do we really want to be `-pedantic` compliant with effort?

**Comment by chardan** [comment]
@tchaikov Sounds like the best course to me-- there was some IRC discussion, I'll add some patches to accompany this and resubmit.

**Comment by tchaikov** [comment]
@chardan great, looking forward to your PR! BTW, i'd suggest avoid using if possible if we determine to go with `-Wvla`:
```
#pragma GCC diagnostic ignored "-Wvla"
```

**Comment by tchaikov** [comment]
>  I do think this is important to warn about, any mistakes with VLAs are no fun to debug, especially in C++.

could you elaborate a little bit why?

and again, if you don't have enough bandwidth on it in short term. i'd recommend revert your change as an intermediate solution.

**Comment by wjwithagen** [comment]
@chardan @tchaikov 
Clang spews quite a few warnings as well.
So just adding a GCC pragma is not going to cut it.
And going to -pedantic is probably not going to bring much, other than 100% compliance to the standards. With a lot of unnecessary and perhaps sometimes illogical changes?

**Comment by chardan** [comment]
First of all, -pedantic does not promise standard-compliance.

Adding -Wvla is not an attempt at this. It is an attempt to warn against an
innocent yet dangerous practice that some developers might invoke without
realizing it. There are some valid uses of VLAs, but I doubt we are invoking
those, and I think we can always reserve special behavior for when they are
strictly meant.

**Comment by tchaikov** [comment]
closing this PR, as #15469 has been merged.

**Pull request closed without merging**
