### PR TITLE
script: enable nautilus in backport scripts

### PR DESCRIPTION
**Pull request by smithfarm**

### CODE REVIEW

**Comment by smithfarm** [comment]
@theanalyst Like this?

**Comment by tchaikov** [comment]
@smithfarm shall we have this change in nautilus?

**Comment by smithfarm** [comment]
@tchaikov Why would it be needed in nautilus?

**Comment by tchaikov** [comment]
i am following the comment in `ceph-backport.sh`. i am quoting it here
```
# git remote add ceph http://github.com/ceph/ceph.git
# git fetch ceph
# git checkout -b wip-19206-jewel ceph/jewel
# git cherry-pick -x ...
# ceph-backport.sh 19206 jewel
```
in the case of nautilus backport, i guess, the developer is likely to use the `ceph-backport.sh` script in current source tree. probably it's just me. and i am supposed to keep a copy of this script in my `$PATH` instead?

**Comment by sebastian-philipp** [comment]
> @smithfarm i am following the comment in `ceph-backport.sh`. i am quoting it here
> 
> ```
> # git remote add ceph http://github.com/ceph/ceph.git
> # git fetch ceph
> # git checkout -b wip-19206-jewel ceph/jewel
> # git cherry-pick -x ...
> # ceph-backport.sh 19206 jewel
> ```
> in the case of nautilus backport, i guess, the developer is likely to use the `ceph-backport.sh` script in current source tree. probably it's just me. and i am supposed to keep a copy of this script in my `$PATH` instead?

Yep, I hit this, too

**Comment by smithfarm** [comment]
@tchaikov @sebastian-philipp I do not care to maintain this script in multiple places. I have a copy in my `$PATH` and that works for me?

**Comment by tchaikov** [comment]
@smithfarm i don't feel strong either way. and i am already very happy with these two great tools =) just wanted to check with you guys.

**Comment by smithfarm** [comment]
Thanks for using the scripts. Makes my life easier :-)

**Pull request merged**
