### PR TITLE
mon,osd: luminous feature bits, require flags, upgrade gates

### PR DESCRIPTION
**Pull request by liewegas**
- require upgrade to pass through luminous before moving beyond
- require mons upgrade to luminous before osds

### CODE REVIEW

**Comment by liewegas** [comment]
fixed test

**Comment by liewegas** [comment]
I noticed the last few patches weren't using HAVE_FEATURE properly (checks for kraken and lumninous were using simple bit masks).  Fixed.

**Comment by yuriw** [comment]
OKed by @sageweil1 to merge
Outstanding failing PR https://github.com/ceph/ceph/pull/13073

http://pulpito.ceph.com/yuriw-2017-02-08_03:16:03-rados-wip-yuri-testing2_2017_2_8-distro-basic-smithi/

http://pulpito.ceph.com/yuriw-2017-02-08_06:01:00-rados-wip-yuri-testing2_2017_2_8---basic-smithi/

**Comment by yuriw** [comment]
@jdurgin @liewegas this was tested and can be megred

**Pull request merged**
