### PR TITLE
tools: respect set features when adding addresses

### PR DESCRIPTION
**Pull request by rzarzynski**
Fixes: https://tracker.ceph.com/issues/53751

------
RCA: https://tracker.ceph.com/issues/53751#note-16.

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Comment by ljflores** [comment]
jenkins test api

**Review by batrick — CHANGES_REQUESTED** [review]
`tools: monmaptool does respsect --feature-{set,unset} when adding addrs` -> `tools: respect set features when adding addresses` ?

**Review by batrick — APPROVED** [review]

**Comment by rzarzynski** [comment]
jenkins retest this please

**Review by ljflores — COMMENTED** [review]
@rzarzynski can you check if this error found in QA testing is related to your PR? I noticed that the test uses the monmaptool earlier on before the failure.

/a/yuriw-2024-11-13_00:17:56-rados-wip-yuri6-testing-2024-11-12-1317-distro-default-smithi/7992357
```
2024-11-14T01:27:42.818 INFO:tasks.workunit.client.0.smithi183.stderr:+ ceph mon set_location e datacenter=dc3 host=host05
2024-11-14T01:27:49.357 INFO:tasks.workunit.client.0.smithi183.stderr:++ hostname -s
2024-11-14T01:27:49.358 INFO:tasks.workunit.client.0.smithi183.stderr:+ hostname=smithi183
2024-11-14T01:27:49.358 INFO:tasks.workunit.client.0.smithi183.stderr:+ ceph osd crush remove smithi183
2024-11-14T01:27:54.689 INFO:tasks.workunit.client.0.smithi183.stderr:device 'smithi183' does not appear in the crush map
2024-11-14T01:27:54.701 INFO:tasks.workunit.client.0.smithi183.stderr:+ ceph osd getcrushmap
2024-11-14T01:27:55.070 INFO:tasks.workunit.client.0.smithi183.stderr:25
2024-11-14T01:27:55.082 INFO:tasks.workunit.client.0.smithi183.stderr:+ crushtool --decompile crushmap
2024-11-14T01:27:55.098 INFO:tasks.workunit.client.0.smithi183.stderr:+ sed 's/^# end crush map$//' crushmap.txt
2024-11-14T01:27:55.099 INFO:tasks.workunit.client.0.smithi183.stderr:+ cat
2024-11-14T01:27:55.100 INFO:tasks.workunit.client.0.smithi183.stderr:+ crushtool --compile crushmap_modified.txt -o crushmap.bin
2024-11-14T01:27:55.118 INFO:tasks.workunit.client.0.smithi183.stderr:+ ceph osd setcrushmap -i crushmap.bin
2024-11-14T01:27:57.392 INFO:tasks.workunit.client.0.smithi183.stderr:27
2024-11-14T01:27:57.406 INFO:tasks.workunit.client.0.smithi183.stderr:+ ceph mon enable_stretch_mode e stretch_rule datacenter
2024-11-14T01:27:57.751 INFO:tasks.workunit.client.0.smithi183.stderr:Error EINVAL: Monitors must use the connectivity strategy to enable stretch mode
2024-11-14T01:27:57.756 DEBUG:teuthology.orchestra.run:got remote process result: 22
2024-11-14T01:27:57.756 INFO:tasks.workunit:Stopping ['mon/mon-stretch-mode-5-mons-8-osds.sh'] on client.0...
2024-11-14T01:27:57.757 DEBUG:teuthology.orchestra.run.smithi183:> sudo rm -rf -- /home/ubuntu/cephtest/workunits.list.client.0 /home/ubuntu/cephtest/clone.client.0
2024-11-14T01:27:58.079 ERROR:teuthology.run_tasks:Saw exception from tasks.
```
Ref: https://tracker.ceph.com/issues/68911

**Review by ljflores — CHANGES_REQUESTED** [review]
Blocking this from merging until the above comment is addressed.

**Comment by rzarzynski** [comment]
```
2024-11-14T01:27:57.406 INFO:tasks.workunit.client.0.smithi183.stderr:+ ceph mon enable_stretch_mode e stretch_rule datacenter
2024-11-14T01:27:57.751 INFO:tasks.workunit.client.0.smithi183.stderr:Error EINVAL: Monitors must use the connectivity strategy to enable stretch mode
```

@ljflores: this doesn't look to be related to `monmaptool`, at least not in an obvious way.
How about testing this separately?

**Comment by ljflores** [comment]
Rados approved: https://tracker.ceph.com/projects/rados/wiki/MAIN#httpstrackercephcomissues69094

**Comment by ljflores** [comment]
jenkins retest this please

**Review by ljflores — APPROVED** [review]

**Comment by ljflores** [comment]
> @rzarzynski can you check if this error found in QA testing is related to your PR? I noticed that the test uses the monmaptool earlier on before the failure.
> 
> /a/yuriw-2024-11-13_00:17:56-rados-wip-yuri6-testing-2024-11-12-1317-distro-default-smithi/7992357
> 
> ```
> 2024-11-14T01:27:42.818 INFO:tasks.workunit.client.0.smithi183.stderr:+ ceph mon set_location e datacenter=dc3 host=host05
> 2024-11-14T01:27:49.357 INFO:tasks.workunit.client.0.smithi183.stderr:++ hostname -s
> 2024-11-14T01:27:49.358 INFO:tasks.workunit.client.0.smithi183.stderr:+ hostname=smithi183
> 2024-11-14T01:27:49.358 INFO:tasks.workunit.client.0.smithi183.stderr:+ ceph osd crush remove smithi183
> 2024-11-14T01:27:54.689 INFO:tasks.workunit.client.0.smithi183.stderr:device 'smithi183' does not appear in the crush map
> 2024-11-14T01:27:54.701 INFO:tasks.workunit.client.0.smithi183.stderr:+ ceph osd getcrushmap
> 2024-11-14T01:27:55.070 INFO:tasks.workunit.client.0.smithi183.stderr:25
> 2024-11-14T01:27:55.082 INFO:tasks.workunit.client.0.smithi183.stderr:+ crushtool --decompile crushmap
> 2024-11-14T01:27:55.098 INFO:tasks.workunit.client.0.smithi183.stderr:+ sed 's/^# end crush map$//' crushmap.txt
> 2024-11-14T01:27:55.099 INFO:tasks.workunit.client.0.smithi183.stderr:+ cat
> 2024-11-14T01:27:55.100 INFO:tasks.workunit.client.0.smithi183.stderr:+ crushtool --compile crushmap_modified.txt -o crushmap.bin
> 2024-11-14T01:27:55.118 INFO:tasks.workunit.client.0.smithi183.stderr:+ ceph osd setcrushmap -i crushmap.bin
> 2024-11-14T01:27:57.392 INFO:tasks.workunit.client.0.smithi183.stderr:27
> 2024-11-14T01:27:57.406 INFO:tasks.workunit.client.0.smithi183.stderr:+ ceph mon enable_stretch_mode e stretch_rule datacenter
> 2024-11-14T01:27:57.751 INFO:tasks.workunit.client.0.smithi183.stderr:Error EINVAL: Monitors must use the connectivity strategy to enable stretch mode
> 2024-11-14T01:27:57.756 DEBUG:teuthology.orchestra.run:got remote process result: 22
> 2024-11-14T01:27:57.756 INFO:tasks.workunit:Stopping ['mon/mon-stretch-mode-5-mons-8-osds.sh'] on client.0...
> 2024-11-14T01:27:57.757 DEBUG:teuthology.orchestra.run.smithi183:> sudo rm -rf -- /home/ubuntu/cephtest/workunits.list.client.0 /home/ubuntu/cephtest/clone.client.0
> 2024-11-14T01:27:58.079 ERROR:teuthology.run_tasks:Saw exception from tasks.
> ```
> 
> Ref: https://tracker.ceph.com/issues/68911

This turned out to be unrelated.

**Pull request merged**
