### PR TITLE
luminous: core: by pass cache if performing deep scrub

### PR DESCRIPTION
**Pull request by tchaikov**
http://tracker.ceph.com/issues/35067

### CODE REVIEW

**Comment by smithfarm** [comment]
@tchaikov FTBFS

**Comment by tchaikov** [comment]
@smithfarm fixed and repushed.

**Comment by yuriw** [comment]
[wip-yuri4-testing-2018-10-31-2012-luminous](https://trello.com/c/3fWYa0bS/459-wip-yuri4-testing-2018-10-31-2012-luminous)

**Comment by yuriw** [comment]
[wip-yuri2-testing-2018-11-02-1957-luminous](https://trello.com/c/HlVp74P1/462-wip-yuri2-testing-2018-11-02-1957-luminous)

**Comment by smithfarm** [comment]
@yuriw I suggest we stop merging PRs into luminous until v12.2.10 is out. What do you think?

**Pull request merged**
