### PR TITLE
luminous: mds: handle discontinuous mdsmap

### PR DESCRIPTION
**Pull request by ukernel**
https://tracker.ceph.com/issues/25048
https://tracker.ceph.com/issues/26833

### CODE REVIEW

**Comment by batrick** [comment]
QA test without patch: http://pulpito.ceph.com/pdonnell-2018-07-24_00:47:45-fs-wip-pdonnell-pr23169-testing-basic-smithi/

This PR: http://pulpito.ceph.com/pdonnell-2018-07-24_00:48:13-fs-wip-pdonnell-testing-20180723.201737-testing-basic-smithi/

**Comment by batrick** [comment]
looks good to merge!

**Comment by yuriw** [comment]
[wip-yuri5-testing-2018-08-01-2158-luminous](https://trello.com/c/sUiX40Jw/362-wip-yuri5-testing-2018-08-01-2158-luminous)

**Comment by ukernel** [comment]
"mds: handle discontinuous mdsmap" contains a bug. fixed by https://github.com/ceph/ceph/pull/23381

**Comment by batrick** [comment]
add https://tracker.ceph.com/issues/26833

**Comment by smithfarm** [comment]
@yuriw This needs to be re-tested. A commit was added so the SHA1 changed.

**Comment by yuriw** [comment]
[wip-yuri5-testing-2018-08-03-2114-luminous](https://trello.com/c/O6q0j5Gf/366-wip-yuri5-testing-2018-08-03-2114-luminous)

**Pull request merged**
