### PR TITLE
hammer: crush: reset bucket->h.items[i] when removing tree item

### PR DESCRIPTION
**Pull request by Vicente-Cheng**
http://tracker.ceph.com/issues/16584

### CODE REVIEW

**Comment by Vicente-Cheng** [comment]
@smithfarm 
hi Nathan, did this pr also need to rebase?

**Comment by smithfarm** [comment]
@Vicente-Cheng Yes, please rebase.

**Comment by Vicente-Cheng** [comment]
@smithfarm 
hi Nathan, done for rebase.
thx!

**Comment by smithfarm** [comment]
@tchaikov This backport passed a rados suite at http://tracker.ceph.com/issues/17151#note-7 with failures that I believe have been addressed (except for http://tracker.ceph.com/issues/15139 which is caused by the build system no longer providing dumpling-era packages).

I have rebuilt the integration branch to include the two fixes and scheduled a new run at http://tracker.ceph.com/issues/17151#note-14

Do you think it's OK to merge provided the second run succeeds?

**Comment by smithfarm** [comment]
Second run succeeded; third run here: http://pulpito.front.sepia.ceph.com/smithfarm-2016-11-21_11:52:41-rados-hammer-backports---basic-smithi/

**Comment by tchaikov** [comment]
lgtm.

**Pull request merged**
