### PR TITLE
qa/cephfs: change deps for xfstests-dev on centos8

### PR DESCRIPTION
**Pull request by rishabh-d-dave**
btrfs-progs-devel is not available anymore on CentOS 8, update
dependency for xfstests-dev in xfstests_dev.py accordingly.

Also, let's make minor changes to improve readability since we are 
around.

Fixes: https://tracker.ceph.com/issues/43486

The PR also adds a new method, vstart_runner.LocalRemote.sh, since              
teuthology.misc.get_system_type couldn't work with vstart cluster
otherwise.

Fixes: https://tracker.ceph.com/issues/43496

 qa/xfstests_dev: change deps for xfstests-dev on ubuntu

Rename python to python2 if Ubuntu distro release is 19 or later.

Fixes: https://tracker.ceph.com/issues/43522

## Checklist
- [x] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by rishabh-d-dave** [comment]
Forgot to add the label `wip-rishabh-testing`.

**Comment by rishabh-d-dave** [comment]
Oddly, all jobs failed - http://pulpito.front.sepia.ceph.com/rishabh-2020-01-08_04:56:07-kcephfs-xfstests-dev-on-centos8-distro-basic-smithi/

For CentOS 8 and RHEL 8 it the error is ` Failed to fetch package version from https://shaman.ceph.com/api/search/?status=ready&project=kernel&flavor=default&distros=centos%2F8%2Fx86_64&ref=testing `, for Ubuntu 18 it is `Unable to locate package python2` which I've fixed locally

For RHEL 7, too has an issue with dependecy but it doesn't look its due to xfstests_dev.py -
```
CommandFailedError: Command failed on smithi196 with status 1: 'sudo yum -y install ceph-radosgw ceph-test ceph ceph-base cephadm ceph-immutable-object-cache ceph-mgr ceph-mgr-dashboard ceph-mgr-diskprediction-local ceph-mgr-rook ceph-mgr-cephadm ceph-fuse librados-devel libcephfs2 libcephfs-devel librados2 librbd1 python3-rados python3-rgw python3-cephfs python3-rbd rbd-fuse rbd-mirror rbd-nbd python3-cephfs bison flex elfutils-libelf-devel openssl-devel libaio-devel bison flex elfutils-libelf-devel openssl-devel libaio-devel bison flex elfutils-libelf-devel openssl-devel libaio-devel bison flex elfutils-libelf-devel openssl-devel libaio-devel bison flex elfutils-libelf-devel openssl-devel libaio-devel bison flex elfutils-libelf-devel openssl-devel libaio-devel'
```

```
2020-01-08T05:19:32.705 INFO:teuthology.orchestra.run.smithi196.stdout:Error: Package: 2:ceph-mgr-dashboard-15.0.0-9037.gbb94890.el7.noarch (ceph-noarch)
2020-01-08T05:19:32.706 INFO:teuthology.orchestra.run.smithi196.stdout:           Requires: python36-routes
2020-01-08T05:19:32.706 INFO:teuthology.orchestra.run.smithi196.stdout:Error: Package: 2:ceph-mgr-diskprediction-local-15.0.0-9037.gbb94890.el7.noarch (ceph-noarch)
2020-01-08T05:19:32.706 INFO:teuthology.orchestra.run.smithi196.stdout:           Requires: python3-scipy
2020-01-08T05:19:32.706 INFO:teuthology.orchestra.run.smithi196.stdout:Error: Package: 2:ceph-mgr-15.0.0-9037.gbb94890.el7.x86_64 (ceph)
2020-01-08T05:19:32.706 INFO:teuthology.orchestra.run.smithi196.stdout:           Requires: python36-werkzeug
2020-01-08T05:19:32.706 INFO:teuthology.orchestra.run.smithi196.stdout:Error: Package: 2:ceph-mgr-15.0.0-9037.gbb94890.el7.x86_64 (ceph)
2020-01-08T05:19:32.707 INFO:teuthology.orchestra.run.smithi196.stdout:           Requires: python36-cherrypy
2020-01-08T05:19:32.707 INFO:teuthology.orchestra.run.smithi196.stdout:Error: Package: 2:ceph-mgr-dashboard-15.0.0-9037.gbb94890.el7.noarch (ceph-noarch)
2020-01-08T05:19:32.707 INFO:teuthology.orchestra.run.smithi196.stdout:           Requires: python36-cherrypy
2020-01-08T05:19:32.707 INFO:teuthology.orchestra.run.smithi196.stdout:Error: Package: 2:ceph-mgr-cephadm-15.0.0-9037.gbb94890.el7.noarch (ceph-noarch)
2020-01-08T05:19:32.707 INFO:teuthology.orchestra.run.smithi196.stdout:           Requires: python36-remoto
2020-01-08T05:19:32.707 INFO:teuthology.orchestra.run.smithi196.stdout:Error: Package: 2:ceph-mgr-dashboard-15.0.0-9037.gbb94890.el7.noarch (ceph-noarch)
2020-01-08T05:19:32.708 INFO:teuthology.orchestra.run.smithi196.stdout:           Requires: python36-werkzeug
2020-01-08T05:19:32.708 INFO:teuthology.orchestra.run.smithi196.stdout:Error: Package: 2:ceph-mgr-rook-15.0.0-9037.gbb94890.el7.noarch (ceph-noarch)
2020-01-08T05:19:32.708 INFO:teuthology.orchestra.run.smithi196.stdout:           Requires: python36-kubernetes
2020-01-08T05:19:32.708 INFO:teuthology.orchestra.run.smithi196.stdout:Error: Package: 2:ceph-mgr-15.0.0-9037.gbb94890.el7.x86_64 (ceph)
2020-01-08T05:19:32.708 INFO:teuthology.orchestra.run.smithi196.stdout:           Requires: python36-pecan
```

**Comment by rishabh-d-dave** [comment]
Re-triggering led to same issue, so the issue on CentOS and RHEL 8 are not transient - http://pulpito.front.sepia.ceph.com/rishabh-2020-01-08_07:40:27-kcephfs-xfstests-dev-on-centos8-distro-basic-smithi/

**Comment by rishabh-d-dave** [comment]
Somehow, builds for Ubuntu weren't triggered and CentOS 8 and RHEL 8 for same reason as before. I'll update about RHEL 7 soon.

**Comment by rishabh-d-dave** [comment]
Just a rebase.

**Comment by batrick** [comment]
Needs rebased again

**Comment by rishabh-d-dave** [comment]
Tests failed - http://pulpito.front.sepia.ceph.com/rishabh-2020-01-16_06:42:54-kcephfs-xfstests-dev-on-centos8-distro-basic-smithi/

**Comment by rishabh-d-dave** [comment]
I still see RHEL 7 and 8 tests triggered. RHEL 7 shouldn't have been triggered given recent changes, right?

CentOS 8 failure message -
```
 SELinux denials found on ubuntu@smithi170.front.sepia.ceph.com: ['type=AVC msg=audit(1579158165.774:4404): avc: denied { entrypoint } for pid=31754 comm="sh" path="/usr/bin/podman" dev="sda1" ino=55464 scontext=unconfined_u:system_r:rpm_script_t:s0-s0:c0.c1023 tcontext=system_u:object_r:container_runtime_exec_t:s0 tclass=file permissive=1'] 
```

Ubuntu 18 failure message -
```
CommandFailedError: Command failed on smithi115 with status 100: 'sudo apt-get install -y xfslibs-dev uuid-dev libtool-bin e2fsprogs automake gcc libuuid1 quota attr libattr1-dev make libacl1-dev libaio-dev xfsprogs libgdbm-dev gawk fio dbench uuid-runtime python2 sqlite3'
```

**Comment by batrick** [comment]
> I still see RHEL 7 and 8 tests triggered. RHEL 7 shouldn't have been triggered given recent changes, right?

Maybe rebase?

> CentOS 8 failure message -
> 
> ```
>  SELinux denials found on ubuntu@smithi170.front.sepia.ceph.com: ['type=AVC msg=audit(1579158165.774:4404): avc: denied { entrypoint } for pid=31754 comm="sh" path="/usr/bin/podman" dev="sda1" ino=55464 scontext=unconfined_u:system_r:rpm_script_t:s0-s0:c0.c1023 tcontext=system_u:object_r:container_runtime_exec_t:s0 tclass=file permissive=1'] 
> ```

https://tracker.ceph.com/issues/43635

> So CentOS 8 job failed but after xfstests passed -
> 
> ```
> 2020-01-16T07:11:03.810 INFO:teuthology.orchestra.run:Running command with timeout 30
> 2020-01-16T07:11:03.810 INFO:teuthology.orchestra.run.smithi166:running tests for ACLs from xfstests-dev> (cd /tmp/tmp.6U9Rjtp2T4xfstests-dev && exec sudo ./check generic/099)
> 2020-01-16T07:11:04.341 INFO:teuthology.orchestra.run.smithi166.stdout:FSTYP         -- ceph
> 2020-01-16T07:11:04.341 INFO:teuthology.orchestra.run.smithi166.stdout:PLATFORM      -- Linux/x86_64 smithi166 5.5.0-rc5-ceph-ge7c680e455aa #1 SMP Wed Jan 15 18:16:24 UTC 2020
> 2020-01-16T07:11:04.341 INFO:teuthology.orchestra.run.smithi166.stdout:
> 2020-01-16T07:11:05.735 INFO:teuthology.orchestra.run.smithi166.stdout:generic/099	 1s
> 2020-01-16T07:11:05.736 INFO:teuthology.orchestra.run.smithi166.stdout:Ran: generic/099
> 2020-01-16T07:11:05.736 INFO:teuthology.orchestra.run.smithi166.stdout:Passed all 1 tests
> 2020-01-16T07:11:05.736 INFO:teuthology.orchestra.run.smithi166.stdout:
> 2020-01-16T07:11:07.551 INFO:teuthology.orchestra.run.smithi166:> sudo userdel --force --remove fsgqa
> 2020-01-16T07:11:08.938 INFO:teuthology.orchestra.run.smithi166:> sudo userdel --force --remove 123456-fsgqa
> 2020-01-16T07:11:10.311 INFO:teuthology.orchestra.run.smithi166:> sudo groupdel fsgqa
> 2020-01-16T07:11:10.422 INFO:teuthology.orchestra.run.smithi166.stderr:groupdel: group 'fsgqa' does not exist
> 2020-01-16T07:11:10.426 DEBUG:teuthology.orchestra.run:got remote process result: 6
> 2020-01-16T07:11:10.426 INFO:teuthology.orchestra.run.smithi166:> sudo rm -rf /tmp/tmp.6U9Rjtp2T4xfstests-dev
> 2020-01-16T07:11:10.660 INFO:tasks.cephfs_test_runner:test_acls (tasks.cephfs.test_acls.TestACLs) ... ok
> 2020-01-16T07:11:10.660 INFO:tasks.cephfs_test_runner:
> 2020-01-16T07:11:10.660 INFO:tasks.cephfs_test_runner:----------------------------------------------------------------------
> 2020-01-16T07:11:10.660 INFO:tasks.cephfs_test_runner:Ran 1 test in 145.519s
> 2020-01-16T07:11:10.660 INFO:tasks.cephfs_test_runner:
> 2020-01-16T07:11:10.661 INFO:tasks.cephfs_test_runner:OK
> ```
> 
> Ubuntu 18 failure message -
> 
> ```
> CommandFailedError: Command failed on smithi115 with status 100: 'sudo apt-get install -y xfslibs-dev uuid-dev libtool-bin e2fsprogs automake gcc libuuid1 quota attr libattr1-dev make libacl1-dev libaio-dev xfsprogs libgdbm-dev gawk fio dbench uuid-runtime python2 sqlite3'
> ```
> 
> Ubuntu 18 job failed for old reason -
> 
> ```
> 2020-01-16T07:00:18.320 INFO:teuthology.orchestra.run.smithi115.stderr:E: Unable to locate package python2

ACK, let me know how the ubuntu debugging goes.

**Comment by rishabh-d-dave** [comment]
Tests - http://pulpito.front.sepia.ceph.com/rishabh-2020-01-20_04:53:55-kcephfs-wip-rishabh2-xfstests-dev-on-centos8-distro-basic-smithi/

CentOS 8 passed and RHEL 7 and 8 failed. @batrick This is fine for this PR, right?

> ACK, let me know how the ubuntu debugging goes.

Went fine. Spotted and fixed the issue. But test for Ubuntu wasn't triggerred.

**Comment by rishabh-d-dave** [comment]
@batrick, thanks for the all the help!

**Pull request merged**
