### PR TITLE
client: add the capacity statistics of multiple data pools in CephFS

### PR DESCRIPTION
**Pull request by renhwztetecs**
When using ceph-fuse to mount the cephfs file directory, if there are multiple data pools built in FS,
the capacity of all OSDs is displayed. If there is only one data pool in FS, it displays the correct capacity information.

Fixes: http://tracker.ceph.com/issues/36669
Signed-off-by: huanwen ren <ren.huanwen@zte.com.cn>

- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by batrick** [comment]
This behavior is intended: the data pools may overlap in space so simply adding the sizes is not quite correct. There isn't a satisfactory solution to this problem.

**Comment by renhwztetecs** [comment]
If the joined data pool comes from the same shared pool, it will repeat the statistics, but this can also be explained from the client side, after all, we are based on the way of thin provisioning.
This is at least better than not counting, and we will not join the same shared pool when we are using it.

**Comment by renhwztetecs** [comment]
On the other hand, we can also consider culling the statistics of duplicate pools.

**Comment by batrick** [comment]
One suggestion in the past has been to show the space for the data pool the directory's layout refers to. So `statfs("/")` may be different from `statfs("/home/someuser"). I don't think adding up all the data pools is the right way to go.

**Comment by batrick** [comment]
@renhwztetecs ping

**Comment by batrick** [comment]
closing this as stale; please reopen if you want to reconsider it

**Pull request closed without merging**
