### PR TITLE
jewel: ceph.spec.in: drop support for RHEL<7 and SUSE<1210 in jewel and above

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/15739
http://tracker.ceph.com/issues/15742
http://tracker.ceph.com/issues/15744
http://tracker.ceph.com/issues/15825
http://tracker.ceph.com/issues/15894
http://tracker.ceph.com/issues/16008

In addition to #8720 this backports several other spec file PRs. Objective is to keep the jewel spec file as close as possible to master.

### CODE REVIEW

**Comment by dachary** [comment]
test this please

**Comment by branto1** [comment]
@smithfarm Could you please add this PR, here?

https://github.com/ceph/ceph/pull/9045

**Comment by smithfarm** [comment]
@branto1 But it's not merged yet?

**Comment by branto1** [comment]
@smithfarm you already dealt with it so we are good to go :-)

**Comment by dachary** [comment]
test this please

**Comment by ktdreyer** [comment]
Bummer, this missed `v10.2.1`.

**Comment by smithfarm** [comment]
Changelog:
* rebased on top of v10.2.1 tag

**Comment by branto1** [comment]
Did you check that this passes the gitbuilders? I think we should be quite safe to merge this if it does (at least on rhel/suse).

**Comment by smithfarm** [comment]
Pushed to gitbuilders as `wip-15739-jewel`

**Comment by smithfarm** [comment]
Changelog:
* added (trivial) backport of #8782 which fixes http://tracker.ceph.com/issues/15627

**Comment by smithfarm** [comment]
Does anyone know what's causing those make check failures?

**Comment by branto1** [comment]
I'm not sure either but I've seen these occur pretty much randomly in some of the previous PRs.

**Comment by branto1** [comment]
It passed all the fedora/centos gitbuilders so it would be up to me, we should be good to merge.

**Comment by ktdreyer** [comment]
:+1: LGTM

**Comment by dachary** [comment]
test this please

**Comment by smithfarm** [comment]
Changelog:
* rebase on top of latest jewel
* drop commit "rpm: put /sbin/ldconfig into -p" which introduced a regression; for details see #9218 and specifically https://github.com/ceph/ceph/pull/9218#issuecomment-221086302

**Comment by branto1** [comment]
@smithfarm Can you incorporate the rest of #9218, here?

**Comment by smithfarm** [comment]
Changelog:
* added SELinux-related commits from #9218

**Comment by smithfarm** [comment]
Changelog:
* added http://tracker.ceph.com/issues/16008 to PR description

**Comment by branto1** [comment]
@smithfarm Can we merge this or are you waiting on something? I've been playing with packages with these patches for quite some time and they seem to work ok (well, better than before).

**Comment by smithfarm** [comment]
@branto1 Yes, an integration run.

**Comment by branto1** [comment]
@smithfarm Any progress? It would be nice to see this in next (.2) minor release.

**Comment by smithfarm** [comment]
@Abhishekvrshny @dachary Based on the progress of the integration run so far, do you see any indication that this PR is causing a regression?

**Comment by dachary** [comment]
@smithfarm the integration run scheduled last monday were killed over the week-end. I'm not sure we have any indication there.

**Comment by smithfarm** [comment]
@branto1 It still hasn't passed an integration run, but if you and @ktdreyer agree I will merge it now.

**Comment by branto1** [comment]
@smithfarm I am all for that. AFAIK, Ken is currently on PTO so his ack could take a while but I'm pretty sure he will be up for it as well.

**Comment by smithfarm** [comment]
@branto Agreed with @Abhishekvrshny and @loicd to run it through a single `upgrade/hammer-x` job on CentOS 7 - now running at high priority at http://pulpito.ceph.com/smithfarm-2016-06-08_01:25:46-upgrade:hammer-x-jewel-backports---basic-vps/

**Comment by gregsfortytwo** [comment]
@smithfarm, according to http://gitbuilder.sepia.ceph.com/gitbuilder-ceph-tarball-trusty-amd64-basic/#origin/jewel this has broken "make check" on the Jewel branch. :(

**Comment by smithfarm** [comment]
@gregsfortytwo Really? Can you double-check?

**Comment by b-ranto** [comment]
@gregsfortytwo I don't see any failures in the current run. What did the failures look like? AFAICR, I've seen some (random) make check failures on jewel before this was merged.

**Pull request merged**
