### PR TITLE
make the all osd/filestore thread pool suicide timeouts separately configurable

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/11700

### CODE REVIEW

**Comment by smithfarm** [comment]
Waiting for @athanatos review

**Comment by dachary** [comment]
@smithfarm could you explain what the anomaly is and why this pull request needs review from Sam ?

**Comment by smithfarm** [comment]
@dachary The anomaly is that firefly has "scrub_finalize_wq" but hammer and above do not have this. On a hunch, I added a commit bff2f47 (which is not in the original master PR) that adds a configurable suicide timeout for this, in the same manner as the other suicide timeouts. However, I don't know enough about this feature to know for sure that this is the right thing to do. Maybe there is someone else who could review it in Sam's absence?

**Comment by dachary** [comment]
@athanatos  does this backport look good to merge ? It passed a run of the firefly rados suite ( see http://tracker.ceph.com/issues/11644#note-110 ). Note that there was a valgrind issues but it is unrelated and fixed by https://github.com/ceph/ceph/pull/6325.

**Comment by dachary** [comment]
@athanatos ping ?

**Comment by athanatos** [comment]
Yep, that looks fine.

**Pull request merged**
