### PR TITLE
mgr/dashboard: Added NFS Ganesha suite to QA tests

### PR DESCRIPTION
**Pull request by callithea**
Signed-off-by: Laura Paduano <lpaduano@suse.com>

### CODE REVIEW

**Comment by callithea** [comment]
Related to PR#25918

**Comment by callithea** [comment]
QA run: http://pulpito.ceph.com/laura-2019-02-19_15:32:09-rados:mgr-wip-lpaduano-testing-26510-distro-basic-mira/ 5 out of 36 jobs failed.
Failures are related to
- ``Test failure: test_selftest_run (tasks.mgr.test_module_selftest.TestModuleSelftest)``
    (http://tracker.ceph.com/issues/38380)
- ``Test failure: test_standby (tasks.mgr.test_dashboard.TestDashboard)``
     (http://tracker.ceph.com/issues/38362)

**Comment by batrick** [comment]
fyi @jtlayton

**Comment by jtlayton** [comment]
Looks like the dashboard test failure is due to some boost deprecation warning. Likely unrelated to this PR.

**Comment by callithea** [comment]
> Looks like the dashboard test failure is due to some boost deprecation warning. Likely unrelated to this PR.

When I opened the PR all checks passed. After only updating my commit message the dashboard tests failed. I agree that the error is unrelated (I've seen that error within the dashboard tests in other PRs as well). I'll start the tests once more.

**Comment by callithea** [comment]
jenkins test dashboard

**Comment by callithea** [comment]
jenkins test dashboard

**Comment by callithea** [comment]
http://pulpito.ceph.com/laura-2019-02-21_12:17:31-rados:mgr-wip-lpaduano-testing-26510-2-distro-basic-mira/ 
Two out of 40 jobs failed, the failures are not related to this PR and already tracked:
    -  `Test failure: test_standby (tasks.mgr.test_dashboard.TestDashboard)`
      (http://tracker.ceph.com/issues/38362)

**Pull request merged**
