### PR TITLE
neorados: bridge support to librados cluster connections

### PR DESCRIPTION
**Pull request by dillaman**
## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by dillaman** [comment]
jenkins test make check

**Comment by xiexingguo** [comment]
@dillaman Hey, Jason. What does 'neo' mean? The one :)?

**Comment by dillaman** [comment]
> @dillaman Hey, Jason. What does 'neo' mean? The one :)?

Good guess. It’s a new C++ librados API that utilizes boost::asio for handling asynchronous events. The hope is that it’s faster and lighter weight than the existing API that librbd utilizes.

**Comment by xiexingguo** [comment]
Thanks. I look forward to seeing the new boost::asio feature on master soon.

**Pull request merged**
