### PR TITLE
rgw: check zone_id or zone_name not empty for zone get sub-command

### PR DESCRIPTION
**Pull request by david-z**
Fixes: http://tracker.ceph.com/issues/24846

Signed-off-by: Zhi Zhang <zhangz.david@outlook.com>

### CODE REVIEW

**Comment by david-z** [comment]
@oritwas Pls help to review this PR, thanks.

**Comment by tianshan** [comment]
if zone_id & zone_name are both empty, will get the default zone, so I think it's not necessary.

**Comment by david-z** [comment]
@tianshan Pls check the tracker, you can see if run `radosgw-admin zone get`, it will return default zone info, but this doesn't make sense because no zone id or zone name is even specified. And if run `radosgw-admin zone get XXX`, it will return the default zone info. If we don't check both options and return error msg, it will bring much trouble to tell whether this zone info is correct for XXX, especially for cluster operator.

**Comment by tianshan** [comment]
@david-z I think it's another issue about `zone get XXX` that didn't parse the extra param.
 I'm agree that make the cmd more certain is good point, meanwhile it's fine return default zone info for me if no zone id or name provided.

**Comment by david-z** [comment]
@cbodley @tianshan  OK, I understand. If this breaks regression test, can we at least output an warning msg to indicate the default zone is returned. Will the warning msg break the regression test?

Thanks.

**Comment by david-z** [comment]
@cbodley @tianshan 

Hi Guys,

Could you pls take a look at my last comment? Or shall we continue following this issue any way?

**Comment by cbodley** [comment]
hi @david-z, my concern is not that a warning will break tests. it's more that the 'default zone' is itself a feature - it's controlled with the `zone default` command and `--default` option to `zone create/modify`, and means that zone is used by default when no `--rgw-zone` is provided - this applies globally to all radosgw/radosgw-admin commands.

it just doesn't seem right to warn people that make use of this feature. i would rather find a way to improve our documentation to eliminate this kind of confusion

**Comment by david-z** [comment]
Thanks for the explanation. I will close this PR.

**Pull request closed without merging**
