### PR TITLE
[rgw]: Update AWS SDK in Java examples

### PR DESCRIPTION
**Pull request by thiagoarrais**
Just noticed that the [Java S3 Examples](https://docs.ceph.com/en/latest/radosgw/s3/java/) seem to use some old version of the AWS SDK. This PR updates these docs to the current SDK. It also refers to the current SDK version label to make the text a little more future-proof.

## Checklist
- [ ] References tracker ticket
- [x] Updates documentation if necessary
- [x] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by yuvalif** [comment]
@faithuniterh can you please help review this?

**Comment by thiagoarrais** [comment]
Rebased to current `main`

**Comment by mattbenjamin** [comment]
unstale

**Comment by thiagoarrais** [comment]
rebased to current `main`

**Comment by alimaredia** [comment]
@thiagoarrais is this ready for a final review?

**Comment by alimaredia** [comment]
unstale

**Review by alimaredia — APPROVED** [review]

**Pull request merged**
