### PR TITLE
mgr/dashboard: raise dashboard exception of 'no module 'snap_schedule''

### PR DESCRIPTION
**Pull request by Serrini**
Fixes: https://tracker.ceph.com/issues/66066
Signed-off-by: sunlan <sunlan@asiainfo.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

Before:

https://github.com/ceph/ceph/assets/46097738/03cc83f0-a02c-4889-a120-fc98e0fa6192

After:

https://github.com/ceph/ceph/assets/46097738/bd4807fa-b3d2-4c06-8d4c-6f66eb85d0ef

### CODE REVIEW

**Comment by cloudbehl** [comment]
@Serrini Thanks for contribution. Can you follow the commit guideline(https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst) 

With which release you were facing this issue?

**Comment by Serrini** [comment]
> https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst



> @Serrini Thanks for contribution. Can you follow the commit guideline(https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst)
> 
> With which release you were facing this issue?

ceph version 603c5b349 (4603c5b349cf6df38810b75daf32b0de3f8e00f4) squid (dev)

**Comment by Serrini** [comment]
@ivoalmeida @avanthakkar Merging is blocked and would you help me review it?

**Review by avanthakkar — APPROVED** [review]
I think we've already catching exception atleast in frontend & showing option to enable module in UI , 
Screenshot from 2024-07-02 15-58-57

so from Dashboard end it doesn't matter even if we don't have this exception. But ideally just from API perspective this LGTM!

**Comment by cloudbehl** [comment]
jenkins test dashboard cephadm

**Comment by cloudbehl** [comment]
jenkins test docs

**Comment by Serrini** [comment]
@cloudbehl hello! The test has passed.

**Comment by cloudbehl** [comment]
jenkins test docs

**Comment by cloudbehl** [comment]
jenkins render docs

**Comment by Serrini** [comment]
jenkins test docs

**Comment by afreen23** [comment]
jenkins test docs

**Comment by afreen23** [comment]
jenkins test make check arm64

**Comment by afreen23** [comment]
jenkins render docs

**Comment by afreen23** [comment]
jenkins retest this please

**Comment by afreen23** [comment]
jenkins render docs

**Comment by afreen23** [comment]
hey @Serrini can you rebase and push your PR again, to make docs test at least pass ?

**Pull request closed without merging**
