### PR TITLE
cmake/modules/BuildRocksDB.cmake: inherit CMAKE_C_COMPILER from parent

### PR DESCRIPTION
**Pull request by tchaikov**
if we set the CFLAGS globally, and the CFLAGS contains options only acceptable by a certain C compiler, RocksDB could fail to configure. for instance, if we set CXXFLAGS so it contains `--config /usr/lib/rpm/redhat/redhat-hardened-clang.cfg` and use clang++ as the CMAKE_CXX_COMPILER, while keep CMAKE_C_COMPILER unchanged. RocksDB would fail to configure like:

```-- Check for working C compiler: /usr/bin/cc - broken
CMake Error at /usr/share/cmake/Modules/CMakeTestCCompiler.cmake:67 (message):
  The C compiler

    "/usr/bin/cc"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /home/jenkins-build/build/workspace/ceph-dev-new-build/ARCH/x86_64/AVAILABLE_ARCH/x86_64/AVAILABLE_DIST/centos9/DIST/centos9/MACHINE_SIZE/gigantic/release/19.0.0-1717-g0f726187/rpm/el9/BUILD/ceph-19.0.0-1717-g0f726187/redhat-linux-build/src/rocksdb/CMakeFiles/CMakeScratch/TryCompile-RU5UFV

    Run Build Command(s):/usr/bin/cmake -E env VERBOSE=1 /usr/bin/gmake -f Makefile cmTC_65e36/fast && gmake[3]: Entering directory '/home/jenkins-build/build/workspace/ceph-dev-new-build/ARCH/x86_64/AVAILABLE_ARCH/x86_64/AVAILABLE_DIST/centos9/DIST/centos9/MACHINE_SIZE/gigantic/release/19.0.0-1717-g0f726187/rpm/el9/BUILD/ceph-19.0.0-1717-g0f726187/redhat-linux-build/src/rocksdb/CMakeFiles/CMakeScratch/TryCompile-RU5UFV'
    /usr/bin/gmake  -f CMakeFiles/cmTC_65e36.dir/build.make CMakeFiles/cmTC_65e36.dir/build
    gmake[4]: Entering directory '/home/jenkins-build/build/workspace/ceph-dev-new-build/ARCH/x86_64/AVAILABLE_ARCH/x86_64/AVAILABLE_DIST/centos9/DIST/centos9/MACHINE_SIZE/gigantic/release/19.0.0-1717-g0f726187/rpm/el9/BUILD/ceph-19.0.0-1717-g0f726187/redhat-linux-build/src/rocksdb/CMakeFiles/CMakeScratch/TryCompile-RU5UFV'
    Building C object CMakeFiles/cmTC_65e36.dir/testCCompiler.c.o
    /usr/bin/cc   -O2 -flto=thin -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security  -Wp,-D_GLIBCXX_ASSERTIONS --config /usr/lib/rpm/redhat/redhat-hardened-clang.cfg -fstack-protector-strong -m64 -march=x86-64-v2 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection  -fPIE -o CMakeFiles/cmTC_65e36.dir/testCCompiler.c.o -c /home/jenkins-build/build/workspace/ceph-dev-new-build/ARCH/x86_64/AVAILABLE_ARCH/x86_64/AVAILABLE_DIST/centos9/DIST/centos9/MACHINE_SIZE/gigantic/release/19.0.0-1717-g0f726187/rpm/el9/BUILD/ceph-19.0.0-1717-g0f726187/redhat-linux-build/src/rocksdb/CMakeFiles/CMakeScratch/TryCompile-RU5UFV/testCCompiler.c
    cc: error: unrecognized command-line option ‘--config’; did you mean ‘-mpconfig’?
    gmake[4]: *** [CMakeFiles/cmTC_65e36.dir/build.make:78: CMakeFiles/cmTC_65e36.dir/testCCompiler.c.o] Error 1
```

where RocksDB tries to check C compiler -- /usr/bin/cc along with the said CFLAGS, and fails to compile the test C program, because GCC does not support this option.

so, in this change, let's pass the CMAKE_C_COMPILER as well.

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Comment by tchaikov** [comment]
```
/usr/bin/ld: /usr/bin/ld: DWARF error: invalid or unhandled FORM value: 0x23
lib/libseastar.a(prometheus.cc.o): in function `seastar::prometheus::write_protobuf_representation(seastar::output_stream<char>&, seastar::prometheus::config const&, seastar::prometheus::metric_family_range&, std::function<bool (std::map<seastar::basic_sstring<char, unsigned int, 15u, true>, seastar::basic_sstring<char, unsigned int, 15u, true>, std::less<seastar::basic_sstring<char, unsigned int, 15u, true> >, std::allocator<std::pair<seastar::basic_sstring<char, unsigned int, 15u, true> const, seastar::basic_sstring<char, unsigned int, 15u, true> > > > const&)>)::$_4::operator()(seastar::prometheus::metric_family&)':
prometheus.cc:(.text+0x224ba): undefined reference to `google::protobuf::internal::ArenaStringPtr::Set(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&&, google::protobuf::Arena*)'
```

**Comment by tchaikov** [comment]
jenkins test make check

**Review by cbodley — APPROVED** [review]

**Comment by tchaikov** [comment]
jenkins test make check

**Comment by tchaikov** [comment]
```
tests/test_api_auditing.py .F

______________________ ApiAuditingTest.test_audit_delete _______________________

self = <dashboard.tests.test_api_auditing.ApiAuditingTest testMethod=test_audit_delete>

    def test_audit_delete(self):
        self._delete('/foo/test1')
>       mgr.cluster_log.assert_called_once()

tests/test_api_auditing.py:90: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <Mock name='mock.cluster_log' id='140049606637792'>

    def assert_called_once(self):
        """assert that the mock was called only once.
        """
        if not self.call_count == 1:
            msg = ("Expected '%s' to have been called once. Called %s times.%s"
                   % (self._mock_name or 'mock',
                      self.call_count,
                      self._calls_repr()))
>           raise AssertionError(msg)
E           AssertionError: Expected 'cluster_log' to have been called once. Called 0 times.

/usr/lib/python3.10/unittest/mock.py:908: AssertionError
------------------------------ Captured log setup ------------------------------
INFO     cherrypy.error:_cplogging.py:220 [04/Mar/2024:13:15:35] ENGINE Listening for SIGTERM.
INFO     cherrypy.error:_cplogging.py:220 [04/Mar/2024:13:15:35] ENGINE Listening for SIGHUP.
INFO     cherrypy.error:_cplogging.py:220 [04/Mar/2024:13:15:35] ENGINE Listening for SIGUSR1.
INFO     cherrypy.error:_cplogging.py:220 [04/Mar/2024:13:15:35] ENGINE Bus STARTING
INFO     cherrypy.error:_cplogging.py:220 [04/Mar/2024:13:15:36] ENGINE Serving on http://127.0.0.1:54583/
INFO     cherrypy.error:_cplogging.py:220 [04/Mar/2024:13:15:36] ENGINE Bus STARTED
------------------------------ Captured log call -------------------------------
INFO     cherrypy.access.140049600814944:_cplogging.py:292 127.0.0.1 - - [04/Mar/2024:13:15:36] "DELETE /foo/test1 HTTP/1.1" 204 - "" ""

tests/test_api_auditing.py F
```

and many more.
```
=========================== short test summary info ============================
FAILED tests/test_api_auditing.py::ApiAuditingTest::test_audit_delete - Asser...
FAILED tests/test_api_auditing.py::ApiAuditingTest::test_audit_post - Asserti...
FAILED tests/test_api_auditing.py::ApiAuditingTest::test_audit_put - Assertio...
FAILED tests/test_api_auditing.py::ApiAuditingTest::test_no_payload - IndexEr...
FAILED tests/test_auth.py::AuthTest::test_login - AssertionError: Status 400 ...
FAILED tests/test_cluster_upgrade.py::ClusterUpgradeControllerTest::test_start_upgrade
FAILED tests/test_controllers.py::ControllersTest::test_4 - AssertionError: S...
FAILED tests/test_controllers.py::ControllersTest::test_5 - AssertionError: S...
FAILED tests/test_controllers.py::ControllersTest::test_rest_bulk_set - Asser...
FAILED tests/test_controllers.py::ControllersTest::test_rest_collection - Ass...
FAILED tests/test_controllers.py::ControllersTest::test_rest_create - Asserti...
FAILED tests/test_controllers.py::ControllersTest::test_rest_set - AssertionE...
FAILED tests/test_daemon.py::DaemonTest::test_daemon_action - json.decoder.JS...
FAILED tests/test_daemon.py::DaemonTest::test_daemon_invalid_action - json.de...
FAILED tests/test_exceptions.py::RESTControllerTest::test_404 - json.decoder....
FAILED tests/test_exceptions.py::RESTControllerTest::test_internal_server_error
FAILED tests/test_host.py::HostControllerTest::test_add_host - AssertionError...
FAILED tests/test_host.py::HostControllerTest::test_host_drain - AssertionErr...
FAILED tests/test_host.py::HostControllerTest::test_host_maintenance - Assert...
FAILED tests/test_host.py::HostControllerTest::test_identify_device - Asserti...
FAILED tests/test_host.py::HostControllerTest::test_set_labels - AssertionErr...
FAILED tests/test_iscsi.py::IscsiTestController::test_add_bad_client - Assert...
FAILED tests/test_iscsi.py::IscsiTestController::test_add_client - AssertionE...
FAILED tests/test_iscsi.py::IscsiTestController::test_add_client_to_group - A...
FAILED tests/test_iscsi.py::IscsiTestController::test_add_client_to_multiple_groups
FAILED tests/test_iscsi.py::IscsiTestController::test_add_disk - AssertionErr...
FAILED tests/test_iscsi.py::IscsiTestController::test_add_image_to_group_with_client_logged_in
FAILED tests/test_iscsi.py::IscsiTestController::test_add_image_to_initiator_with_client_logged_in
FAILED tests/test_iscsi.py::IscsiTestController::test_bad_discoveryauth - jso...
FAILED tests/test_iscsi.py::IscsiTestController::test_change_client_auth - As...
FAILED tests/test_iscsi.py::IscsiTestController::test_change_client_password
FAILED tests/test_iscsi.py::IscsiTestController::test_change_disk_controls - ...
FAILED tests/test_iscsi.py::IscsiTestController::test_change_disk_image - Ass...
FAILED tests/test_iscsi.py::IscsiTestController::test_create - AssertionError...
FAILED tests/test_iscsi.py::IscsiTestController::test_create_acl_enabled - As...
FAILED tests/test_iscsi.py::IscsiTestController::test_delete - AssertionError...
FAILED tests/test_iscsi.py::IscsiTestController::test_disable_discoveryauth
FAILED tests/test_iscsi.py::IscsiTestController::test_enable_discoveryauth - ...
FAILED tests/test_iscsi.py::IscsiTestController::test_list - AssertionError: ...
FAILED tests/test_iscsi.py::IscsiTestController::test_remove_client - Asserti...
FAILED tests/test_iscsi.py::IscsiTestController::test_remove_client_from_group
FAILED tests/test_iscsi.py::IscsiTestController::test_remove_client_logged_in
FAILED tests/test_iscsi.py::IscsiTestController::test_remove_client_lun - Ass...
FAILED tests/test_iscsi.py::IscsiTestController::test_remove_groups - Asserti...
FAILED tests/test_iscsi.py::IscsiTestController::test_remove_image_from_group_with_client_logged_in
FAILED tests/test_iscsi.py::IscsiTestController::test_rename_client - Asserti...
FAILED tests/test_iscsi.py::IscsiTestController::test_rename_group - Assertio...
FAILED tests/test_iscsi.py::IscsiTestController::test_rename_target - Asserti...
FAILED tests/test_nfs.py::NFSGaneshaExportsTest::test_create_export - Asserti...
FAILED tests/test_nfs.py::NFSGaneshaExportsTest::test_create_export_with_existing_pseudo_fails
FAILED tests/test_nfs.py::NFSGaneshaExportsTest::test_set_export - AssertionE...
FAILED tests/test_osd.py::OsdTest::test_osd_create_bare - AssertionError: Sta...
FAILED tests/test_osd.py::OsdTest::test_osd_create_with_drive_groups - Assert...
FAILED tests/test_osd.py::OsdTest::test_osd_mark_all_actions - AssertionError...
FAILED tests/test_osd.py::OsdTest::test_osd_scrub - AssertionError: Expected ...
FAILED tests/test_osd.py::OsdTest::test_reweight_osd - AssertionError: Status...
FAILED tests/test_plugin_debug.py::TestPluginDebug::test_debug_disabled - jso...
FAILED tests/test_plugin_debug.py::TestPluginDebug::test_debug_enabled - json...
FAILED tests/test_pool.py::PoolControllerTest::test_creation - AssertionError...
FAILED tests/test_pool.py::PoolControllerTest::test_set_pool_name - Assertion...
FAILED tests/test_prometheus.py::PrometheusControllerTest::test_add_silence
FAILED tests/test_prometheus.py::PrometheusControllerTest::test_get_last_notification_with_use_of_last_keyword
FAILED tests/test_prometheus.py::PrometheusControllerTest::test_get_no_notification_since_with_last_notification
FAILED tests/test_prometheus.py::PrometheusControllerTest::test_get_notifications_since_last_notification
FAILED tests/test_prometheus.py::PrometheusControllerTest::test_post_on_receiver
FAILED tests/test_prometheus.py::PrometheusControllerTest::test_update_silence
FAILED tests/test_rbd_mirroring.py::RbdMirroringControllerTest::test_site_name
FAILED tests/test_rbd_mirroring.py::RbdMirroringPoolBootstrapControllerTest::test_peer
FAILED tests/test_rest_tasks.py::TaskControllerTest::test_bar_task - json.dec...
FAILED tests/test_rest_tasks.py::TaskControllerTest::test_create_task - json....
FAILED tests/test_rest_tasks.py::TaskControllerTest::test_foo_task - json.dec...
FAILED tests/test_rest_tasks.py::TaskControllerTest::test_long_set_task - jso...
FAILED tests/test_settings.py::SettingsControllerTest::test_bulk_set - Assert...
FAILED tests/test_settings.py::SettingsControllerTest::test_set - AssertionEr...
FAILED tests/test_tools.py::RESTControllerTest::test_args_from_json - json.de...
FAILED tests/test_tools.py::RESTControllerTest::test_fill - json.decoder.JSON...
FAILED tests/test_tools.py::RESTControllerTest::test_not_implemented - json.d...
FAILED tests/test_tools.py::RequestLoggingToolTest::test_is_logged - Assertio...
=========== 78 failed, 410 passed, 79 warnings in 294.71s (0:04:54) ============
py3: exit 1 (296.75 seconds) /home/jenkins-build/build/workspace/ceph-pull-requests/src/pybind/mgr/dashboard> pytest pid=227452
  py3: FAIL code 1 (342.43=setup[45.68]+cmd[296.75] seconds)
```

**Comment by tchaikov** [comment]
this change was implemented for the sake of correctness. the build failure was identified when we were experimenting using clang for building Ceph packages. but it turned out that GCC-13 was good enough. so this change won't be exercised by any of our CI pipelines.

so, i am merging as it is.

**Pull request merged**
