### PR TITLE
nautilus: fs subvolume clone cancel

### PR DESCRIPTION
**Pull request by ajarr**
Fixes: https://tracker.ceph.com/issues/44670

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by vshankar** [comment]
look ok -- please run it through teuthology for volumes test

**Comment by ajarr** [comment]
http://pulpito.front.sepia.ceph.com/rraja-2020-03-19_06:51:10-fs-nautilus-volumes-cancel-clone-distro-basic-smithi/
```
(virtualenv) rraja@teuthology:~/teuthology$ CEPH_QA_MAIL="rraja@redhat.com"; MACHINE_NAME=smithi; CEPH_BRANCH=nautilus-volumes-cancel-clone
(virtualenv) rraja@teuthology:~/teuthology$ teuthology-suite -v --ceph-repo https://github.com/ceph/ceph-ci.git --suite-repo https://github.com/ceph/ceph-ci.git  -c $CEPH_BRANCH -m $MACHINE_NAME -s fs -k distro -p 20 -e $CEPH_QA_MAIL --suite-branch $CEPH_BRANCH  --filter "volumes" -N 10 --dry-run
```

**Comment by ajarr** [comment]
@vshankar, removed all type check related commits as we discussed. They were causing issues with upstream teuthology testing due to missing 'typing' module.

**Comment by ajarr** [comment]
http://pulpito.front.sepia.ceph.com/rraja-2020-03-19_16:15:22-fs-nautilus-clone-cancel-no-type-check-distro-basic-smithi/

**Comment by ajarr** [comment]
> http://pulpito.front.sepia.ceph.com/rraja-2020-03-19_16:15:22-fs-nautilus-clone-cancel-no-type-check-distro-basic-smithi/

1 job failed out of 20 due to  https://tracker.ceph.com/issues/44276
as observed in the parent octopus PR, https://github.com/ceph/ceph/pull/34018#pullrequestreview-376877589

FYI, the same `volumes` job was run 10 times to identify race related issues.
```
$ teuthology-suite -v --ceph-repo https://github.com/ceph/ceph-ci.git --suite-repo https://github.com/ceph/ceph-ci.git  -c $CEPH_BRANCH -m $MACHINE_NAME -s fs -k distro -p 20 -e $CEPH_QA_MAIL --suite-branch $CEPH_BRANCH  --filter "volumes" -N 10
```

**Comment by ajarr** [comment]
@gregsfortytwo this PR is good to be merged.

**Pull request merged**
