### PR TITLE
luminous: ceph-volume: do not use --key during mkfs

### PR DESCRIPTION
**Pull request by andrewschoen**
backport of #19276

### CODE REVIEW

**Comment by andrewschoen** [comment]
this backport is needed for #20241

**Comment by alfredodeza** [comment]
@liewegas @tchaikov we will need this so that we can get the dmcrypt support in ceph-volume working in Luminous

**Comment by andrewschoen** [comment]
jenkins test ceph-volume tox

**Comment by andrewschoen** [comment]
jenkins test ceph-volume lvm create

**Comment by andrewschoen** [comment]
jenkins test ceph-volume lvm create

**Pull request merged**
