### PR TITLE
ceph-disk: deactivate / destroy PATH arg are optional

### PR DESCRIPTION
**Pull request by dachary**
Signed-off-by: Loic Dachary <loic@dachary.org>

### CODE REVIEW

**Comment by dachary** [comment]
@tchaikov this fails make check, I was too quick to merge #7687 ...

**Comment by dachary** [comment]
hum, there is more to it even

**Comment by dachary** [comment]
@that should be better now.

**Comment by tchaikov** [comment]
yeah, they are not supposed to be collected as lists. instead a single item should be produced.

**Comment by tchaikov** [comment]
tested by running test/test_pidfile.sh.

**Pull request merged**
