### PR TITLE
luminous: core: os/bluestore_tool: fix bluefs expand

### PR DESCRIPTION
**Pull request by ifed01**
Fixes: https://tracker.ceph.com/issues/37495

For now additionally brings commits from https://github.com/ceph/ceph/pull/25187 which are required.

Signed-off-by: Igor Fedotov <ifedotov@suse.com>

- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by smithfarm** [comment]
@ifed01 All the cherry-picks applied cleanly, no conflicts?

**Comment by smithfarm** [comment]
I tried the first two commits - the first one cherry-picked cleanly, but the second one, 71c3b58, had a conflict in `src/os/bluestore/bluestore_tool.cc`.

The commits that required conflict resolution need a `Conflicts:` section listing at least the files that had conflicts requiring manual resolution, and preferably with a brief explanation of the conflict and/or how it was resolved.

**Comment by ifed01** [comment]
@smithfarm - updated commit messages with Conflicts section.

**Comment by ifed01** [comment]
jenkins retest this please

**Comment by ifed01** [comment]
@liewegas - ping! Should we target this to 12.2.11?

**Comment by yuriw** [comment]
I did not have issues merging this into `wip-yuri6-testing-2019-01-09-1618-luminous`

@liewegas @neha-ojha it passed tests, pls approve/merge

**Comment by liewegas** [comment]
@yuriw @ifed01 yeah let's include this in .11. needs rebase, though?

**Comment by yuriw** [comment]
test this please

**Pull request merged**
