### PR TITLE
test/ smb: modify source_type to fix run-tox-mgr failed

### PR DESCRIPTION
**Pull request by Svelar**
source_type should be resource

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Comment by Svelar** [comment]
jenkins test api

**Comment by Svelar** [comment]
jenkins test api

**Comment by Svelar** [comment]
jenkins test api

**Review by idryomov — APPROVED** [review]
LGTM, but let's wait for @phlogistonjohn 

This happened because the checks on https://github.com/ceph/ceph/pull/57180 which got merged yesterday passed on May 2, before https://github.com/ceph/ceph/pull/57096 was merged on May 10, right?

**Comment by idryomov** [comment]
jenkins test api

**Comment by Svelar** [comment]
> LGTM, but let's wait for @phlogistonjohn
> 
> This happened because the checks on #57180 which got merged yesterday passed on May 2, before #57096 was merged on May 10, right?

IMO yes, let's wait for @phlogistonjohn, actually I am not very familiar with this part, just the issue causes almost all make checks failed.

**Review by adk3798 — APPROVED** [review]

**Comment by batrick** [comment]
merging this because it's blocking other PR's ci tests. @phlogistonjohn please take a careful look and make any changes necessary in a followup.

**Review by phlogistonjohn — COMMENTED** [review]
Strange that I didn't notice this when testing the previous PR, but changes look OK to me, thanks!

**Pull request merged**
