### PR TITLE
mgr/smart: fix python3 module loading

### PR DESCRIPTION
**Pull request by rjfd**
Signed-off-by: Ricardo Dias <rdias@suse.com>

### CODE REVIEW

**Comment by xiexingguo** [comment]
Sorry for OT :-(

@tchaikov @jcsp Is **ceph-dev** channel now down? Seems I'm unable to receive any messages for a couple of days...

**Comment by tchaikov** [comment]
@xiexingguo probably it's just you. i am able to chat over \#ceph-devel.

**Comment by xiexingguo** [comment]
> @xiexingguo probably it's just you. i am able to chat over #ceph-devel. and maybe, we can continue the discussion over ceph-devel ML.

Ack. Thanks @tchaikov.

**Comment by rjfd** [comment]
@tchaikov ups, sorry I just noticed that you labeled this PR with `wip-kefu-testing` after merging the PR. Hope that you don't find any problems related to this PR.

**Pull request merged**
