### PR TITLE
cmake: try to find dml only if PMEM is enabled

### PR DESCRIPTION
**Pull request by tchaikov**
as the feature dependent on DML library requires PMEM backend.

Signed-off-by: Kefu Chai <tchaikov@gmail.com>

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by tchaikov** [comment]
cc @optimistyzy

**Review by cbodley — APPROVED** [review]

**Comment by optimistyzy** [comment]
Currently, this PR looks good for me. // DML can also be used to offload other memory operations, e.g., copy, crc32c etc.

**Comment by tchaikov** [comment]
> Currently, this PR looks good for me. // DML can also be used to offload other memory operations, e.g., copy, crc32c etc.

thanks for the filling me with this info. the reason why i am proposing this change is, IMHO, following cmake message is kind of distracting:
```
-- Could NOT find dml (missing: DML_LIBRARIES DML_INCLUDE_DIR DML_HL_LIBRARIES) 
```

to ensure we have a repeatable build, we should only try to find DML on demand. probably if some of us wants to implement DML based optimizations for memcpy and crc32c, we can always introduce a dedicated `WITH_DML` option, which is orthogonal to `WITH_PMEM`. but let's leave it for future.

**Comment by optimistyzy** [comment]
> > Currently, this PR looks good for me. // DML can also be used to offload other memory operations, e.g., copy, crc32c etc.
> 
> thanks for filling me with this info. the reason why i am proposing this change is, IMHO, following cmake message is kind of distracting:
> 
> ```
> -- Could NOT find dml (missing: DML_LIBRARIES DML_INCLUDE_DIR DML_HL_LIBRARIES) 
> ```
> 
> to ensure we have a repeatable build, we should only try to find DML on demand. probably if some of us wants to implement DML based optimizations for memcpy and crc32c, we can always introduce a dedicated `WITH_DML` option, which is orthogonal to `WITH_PMEM`. but let's leave it for future.

I am ok with this PR to merged.

**Comment by tchaikov** [comment]
https://shaman.ceph.com/builds/ceph/wip-pr-45977-kefu/6440ca4fce22507dedad05e0e6b318db045e146b/

**Pull request merged**
