### PR TITLE
pacific: os/bluestore: Always update the cursor position in AVL near-fit search.

### PR DESCRIPTION
**Pull request by ifed01**
backport tracker: https://tracker.ceph.com/issues/55359

backport of https://github.com/ceph/ceph/pull/45884
parent tracker: https://tracker.ceph.com/issues/55358

Signed-off-by: Mark Nelson <mnelson@redhat.com>
(cherry picked from commit 3bed53debfa2f9ec9d31021ce7eaf8b78f78f9e0)

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by ifed01** [comment]
jenkins test make check

**Comment by ifed01** [comment]
jenkins test make check

**Comment by ifed01** [comment]
jenkins test make check

**Comment by neha-ojha** [comment]
@markhpc ping

**Review by markhpc — APPROVED** [review]
LGTM!

**Comment by Matan-B** [comment]
https://pulpito.ceph.com/yuriw-2022-08-22_21:19:34-rados-wip-yuri4-testing-2022-08-18-1020-pacific-distro-default-smithi/

0 Related Failures.
16 Tracked unrelated Failures.
0 Newly Tracked Failures.
0 Tracked dead Jobs.

Rerun of:
https://pulpito.ceph.com/yuriw-2022-08-21_20:22:23-rados-wip-yuri4-testing-2022-08-18-1020-pacific-distro-default-smithi/

Failures, unrelated:
6986464, 6986477, 6986491, 6986503: Infra failure
6986466: https://tracker.ceph.com/issues/54992
6986467, 6986489, 6986502: https://tracker.ceph.com/issues/53939
6986470, 6986482, 6986492: https://tracker.ceph.com/issues/55443
6986471: https://tracker.ceph.com/issues/50536
6986481: https://tracker.ceph.com/issues/54071
6986483, 6986484: https://tracker.ceph.com/issues/49287
6986501: https://tracker.ceph.com/issues/56573


Details:

6986464, 6986477, 6986491, 6986503: The CustomResourceDefinition "installations.operator.tigera.io" is invalid: metadata.annotations: Too long: must have at most 262144 bytes
6986466: cannot stat '/etc/containers/registries.conf': No such file or directory
6986467, 6986489, 6986502:Upgrade Paused due to UPGRADE_REDEPLOY_DAEMON: Upgrading daemon osd.0 on host smithi103 failed
6986470, 6986482, 6986492:"SELinux denials found.." in rados run
6986471: "Command failed (workunit test rados/test.sh)" - rados/test.sh times out on main
6986481: rados/cephadm/osds: Invalid command: missing required parameter hostname(<string>)
6986483, 6986484: podman: setting cgroup config for procHooks process caused: Unit libpod-$hash.scope not found
6986501: test_cephadm.sh: KeyError: 'TYPE'

**Pull request merged**
