### PR TITLE
rgw: honor the tenant part of rgw_bucket during comparisons.

### PR DESCRIPTION
**Pull request by rzarzynski**
Fixes: http://tracker.ceph.com/issues/20897
Signed-off-by: Radoslaw Zarzynski <rzarzyns@redhat.com>

### CODE REVIEW

**Comment by rzarzynski** [comment]
Tempest hasn't found any regression here (tested with multi-tenant Swift API aka `rgw_keystone_implicit_tenants=true`).

**Comment by rzarzynski** [comment]
Stuffing `rgw_bucket::operator<()` with `ceph_abort()` showed it's involved in quota-related calculations:
```
 ceph version 12.1.2-90-g250cfda (250cfda35819724159e585bb493476f5432c4b1e) luminous (rc)
 1: (()+0x1e8944) [0x2f0944]
 2: (()+0x115b0) [0x5d255b0]
 3: (gsignal()+0x9f) [0x111b98df]
 4: (abort()+0x16a) [0x111bb4da]
 5: (()+0x563494) [0x66b494]
 6: (RGWQuotaCache<rgw_bucket>::get_stats(rgw_user const&, rgw_bucket const&, RGWStorageStats&, RGWQuotaInfo&)+0xa5) [0x674f25]
 7: (RGWQuotaHandlerImpl::check_bucket_shards(unsigned long, unsigned long, rgw_user const&, rgw_bucket const&, RGWQuotaInfo&, unsigned long, bool&, unsigned int*)+0x80) [0x675250]
 8: (RGWRados::check_bucket_shards(RGWBucketInfo const&, rgw_bucket const&, RGWQuotaInfo&)+0x91) [0x413861]
 9: (RGWPutObj::execute()+0x1682) [0x3e13a2]
 10: (rgw_process_authenticated(RGWHandler_REST*, RGWOp*&, RGWRequest*, req_state*, bool)+0x172) [0x40b4c2]
 11: (process_request(RGWRados*, RGWREST*, RGWRequest*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, rgw::auth::StrategyRegistry const&, RGWRestfulIO*, OpsLogSocket*)+0x1c0c) [0x40d4ac]
 12: (RGWCivetWebFrontend::process(mg_connection*)+0x37b) [0x2aa1fb]
 13: (()+0x1d95c5) [0x2e15c5]
 14: (()+0x1db030) [0x2e3030]
 15: (()+0x773a) [0x5d1b73a]
 16: (clone()+0x3f) [0x1128be7f]
```

`RGWQuotaCache<...>::get_stats()` locates appropriate instance of `RGWQuotaCacheStats` in the LRU map. As the comparison is broken, the returned stats can be inconsistent.
```cpp
template<class T>
int RGWQuotaCache<T>::get_stats(const rgw_user& user, const rgw_bucket& bucket, RGWStorageStats& stats, RGWQuotaInfo& quota) {
  RGWQuotaCacheStats qs;
  utime_t now = ceph_clock_now();
  if (map_find(user, bucket, qs)) {
    if (qs.async_refresh_time.sec() > 0 && now >= qs.async_refresh_time) {
      int r = async_refresh(user, bucket, qs);
      if (r < 0) {
        ldout(store->ctx(), 0) << "ERROR: quota async refresh returned ret=" << r << dendl;

        /* continue processing, might be a transient error, async refresh is just optimization */
      }
    }

    if (can_use_cached_stats(quota, qs.stats) && qs.expiration >
        ceph_clock_now()) {
      stats = qs.stats;
      return 0;
    }
  }

  int ret = fetch_stats_from_storage(user, bucket, stats);
  if (ret < 0 && ret != -ENOENT)
    return ret;

  set_stats(user, bucket, qs, stats);

  return 0;
}
```

**Comment by rzarzynski** [comment]
Jenkins retest this please (`test_pidfile.sh`)

**Comment by yuriw** [comment]
test this please

**Comment by rzarzynski** [comment]
Yet another failure in the unrelated `test_pidfile.sh`. Rebasing to the current `master`.

**Comment by rzarzynski** [comment]
Trivially rebased. Absolutely no other changes here.

**Comment by yuriw** [comment]
http://pulpito.ceph.com/yuriw-2017-08-08_22:29:19-rgw-wip-yuri-testing3_2017_8_8-distro-basic-smithi/

http://pulpito.ceph.com/yuriw-2017-08-08_22:29:19-rgw-wip-yuri-testing3_2017_8_8-distro-basic-smithi/

**Pull request merged**
