### PR TITLE
Revert "Merge pull request #47092 from dparmar18/wip-dparmar-cephadm-…

### PR DESCRIPTION
**Pull request by batrick**
Reverting https://github.com/ceph/ceph/pull/47092 as the QA suite tests were incomplete and misorganized.

### CODE REVIEW

**Review by adk3798 — APPROVED** [review]
Apologies for premature merge.

**Comment by batrick** [comment]
> Apologies for premature merge.

No worries. I appreciate you having tested it. It was just old code that was unfortunately not updated based on recent but private discussions with @dparmar18 .

**Comment by batrick** [comment]
jenkins test api

**Comment by batrick** [comment]
jenkins test api

**Pull request merged**
