### PR TITLE
cephfs-shell: fixes related to Cmd2ArgparseError

### PR DESCRIPTION
**Pull request by rishabh-d-dave**
Fixes: https://tracker.ceph.com/issues/55710
Fixes: https://tracker.ceph.com/issues/55716
Fixes: https://tracker.ceph.com/issues/55719

Related PR: #46337

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/master/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Review by dparmar18 — APPROVED** [review]
LGTM

**Review by batrick — APPROVED** [review]

**Comment by batrick** [comment]
@rishabh-d-dave please go ahead and run through teuthology and link results.

**Review by dparmar18 — APPROVED** [review]

**Comment by rishabh-d-dave** [comment]
@batrick @dparmar18 PTAL. Changes include a very minor change.

**Comment by rishabh-d-dave** [comment]
The QA run will start in some time.

**Comment by rishabh-d-dave** [comment]
The QA run was partially successful - http://pulpito.front.sepia.ceph.com/rishabh-2022-05-19_23:46:36-fs-wip-rishabh-shell-rm-distro-basic-smithi/. Requires a minor change to be fully successful.

**Comment by rishabh-d-dave** [comment]
QA run was successful - http://pulpito.front.sepia.ceph.com/rishabh-2022-05-20_05:29:37-fs-wip-rishabh-shell-rm-distro-basic-smithi/

**Comment by vshankar** [comment]
> QA run was successful - http://pulpito.front.sepia.ceph.com/rishabh-2022-05-20_05:29:37-fs-wip-rishabh-shell-rm-distro-basic-smithi/

Good to merge then?

**Review by vshankar — APPROVED** [review]

**Pull request merged**
