### PR TITLE
mgr/DaemonServer: "osd safe-to-destroy" - more verbose output

### PR DESCRIPTION
**Pull request by xiexingguo**
For multiple inputs, we want to avoid a situation like:

```
# ceph osd safe-to-destroy 0 1 2
Error EBUSY: OSD(s) 1,2 have 96 pgs currently mapped to them
# ceph osd safe-to-destroy 0
Error EBUSY: OSD(s) 0 last reported they still store some PG data, and not all PGs are active+clean; we cannot be sure they aren't still needed.
```

The first command seems to be implying osd.0 is safe-to-destroy whereas it isn't.
This patch instead gives a complete report of each osd if multiple osds are specified.

Signed-off-by: xie xingguo <xie.xingguo@zte.com.cn>

- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by LenzGr** [comment]
> maybe we have to output in json or other machine parsable format if we want to use this command programmatically..

This might be very useful for the dashboard, as we're performing this "safe to destroy" check in the OSD management (see #24606) - @p-na maybe you can chime in here?

**Comment by xiexingguo** [comment]
> This might be very useful for the dashboard, as we're performing this "safe to destroy" check in the OSD management (see #24606) - @p-na maybe you can chime in here?

I'll do that in a follow-up pr.

**Comment by liewegas** [comment]
I think structure json output would be fabulous!

**Comment by liewegas** [comment]
http://pulpito.ceph.com/sage-2018-10-24_19:59:09-rados-wip-sage-testing-2018-10-24-1258-distro-basic-smithi/

**Comment by liewegas** [comment]
```
2018-11-05T17:32:39.474 INFO:tasks.cephfs_test_runner:======================================================================
2018-11-05T17:32:39.474 INFO:tasks.cephfs_test_runner:FAIL: test_safe_to_destroy (tasks.mgr.dashboard.test_osd.OsdTest)
2018-11-05T17:32:39.474 INFO:tasks.cephfs_test_runner:----------------------------------------------------------------------
2018-11-05T17:32:39.475 INFO:tasks.cephfs_test_runner:Traceback (most recent call last):
2018-11-05T17:32:39.475 INFO:tasks.cephfs_test_runner:  File "/home/teuthworker/src/git.ceph.com_ceph-c_wip-sage3-testing-2018-11-04-2008/qa/tasks/mgr/dashboard/test_osd.py", line 105, in test_safe_to_destroy
2018-11-05T17:32:39.475 INFO:tasks.cephfs_test_runner:    self.assertJsonBody({'safe-to-destroy': True})
2018-11-05T17:32:39.475 INFO:tasks.cephfs_test_runner:  File "/home/teuthworker/src/git.ceph.com_ceph-c_wip-sage3-testing-2018-11-04-2008/qa/tasks/mgr/dashboard/helper.py", line 324, in assertJsonBody
2018-11-05T17:32:39.475 INFO:tasks.cephfs_test_runner:    self.assertEqual(body, data)
2018-11-05T17:32:39.475 INFO:tasks.cephfs_test_runner:AssertionError: {u'message': u'[errno -11] 1 pgs have unknown state; cannot draw any conclusions [truncated]... != {'safe-to-destroy': True}
2018-11-05T17:32:39.475 INFO:tasks.cephfs_test_runner:- {u'message': u'[errno -11] 1 pgs have unknown state; cannot draw any conclusions',
2018-11-05T17:32:39.476 INFO:tasks.cephfs_test_runner:-  u'safe-to-destroy': False}
2018-11-05T17:32:39.476 INFO:tasks.cephfs_test_runner:? ^^                   ^^^^
2018-11-05T17:32:39.476 INFO:tasks.cephfs_test_runner:
2018-11-05T17:32:39.476 INFO:tasks.cephfs_test_runner:+ {'safe-to-destroy': True}
2018-11-05T17:32:39.476 INFO:tasks.cephfs_test_runner:? ^                   ^^^
2018-11-05T17:32:39.476 INFO:tasks.cephfs_test_runner:
2018-11-05T17:32:39.476 INFO:tasks.cephfs_test_runner:
```
/a/sage-2018-11-05_14:43:15-rados-wip-sage3-testing-2018-11-04-2008-distro-basic-smithi/3226964

**Comment by runsisi** [comment]
@LenzGr is this what you wanted? https://github.com/ceph/ceph/pull/24799

**Pull request merged**
