### PR TITLE
radosgw-admin: add command to resync encrypted multipart objects

### PR DESCRIPTION
**Pull request by cbodley**
a recovery command for encrypted multipart objects that were corrupted on replication by https://tracker.ceph.com/issues/46062. depends on a separate fix for the replication logic to remember the source object's part boundaries for decryption

`radosgw-admin bucket resync encrypted multipart` command lists all of the object versions in a given bucket and checks the head object xattrs for encryption and multipart. if found, rewrites the head object with an updated mtime so other zones will resync the data

TODO:
- [x] clean up json format
- [x] test with versioned buckets

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by mattbenjamin** [comment]
@cbodley I assume is there logic to detect that the current site is the originating location of each object?

**Comment by cbodley** [comment]
> @cbodley I assume is there logic to detect that the current site is the originating location of each object?

@mattbenjamin the check for a multipart manifest should cover that, since the replicas aren't multipart. hopefully @mdw-at-linuxbox's fix doesn't change that, but we'll see

**Comment by cbodley** [comment]
tested in a 2-zone multisite setup with default encryption support from https://github.com/ceph/ceph/pull/51786

after creating a `testbucket` and uploading a `6m` multipart object, i ran the command once on the source zone:
```
$ bin/radosgw-admin -c run/c1/ceph.conf bucket resync encrypted multipart --bucket testbucket
{
    "bucket": "testbucket",
    "bucket_id": "550f5338-009b-4020-b8d7-7be0d7d7da98.4190.1",
    "progress": [
        {
            "name": "6m",
            "mtime": "2023-05-30T20:03:16.621151Z"
        },
        {
            "processed": 1,
            "marker": "6m"
        }
    ]
}
```
and verified that the secondary zone re-fetched the object:
```
2023-05-30T16:05:03.643-0400 7fb7ce7886c0 20 HTTP_IF_MODIFIED_SINCE=2023-05-30T20:03:16.621151420Z
2023-05-30T16:05:03.652-0400 7fb7c176e6c0  2 req 2113387870146149013 0.009000324s s3:get_obj http status=200
2023-05-30T16:05:03.652-0400 7fb7c176e6c0  1 ====== req done req=0x7fb6e5db6710 op status=0 http_status=200 latency=0.009000324s ======
```
the request returns the expected `200 OK` instead of `304 Not Modified`, because the source mtime was 1ns higher than the destination's mtime

i then ran the command again:
```

$ bin/radosgw-admin -c run/c1/ceph.conf bucket resync encrypted multipart --bucket testbucket
{
    "bucket": "testbucket",
    "bucket_id": "550f5338-009b-4020-b8d7-7be0d7d7da98.4190.1",
    "progress": [
        {
            "name": "6m",
            "mtime": "2023-05-30T20:03:16.621151Z"
        },
        {
            "processed": 1,
            "marker": "6m"
        }
    ]
}
```
and saw the remote zone fetch it again successfully:
```
2023-05-30T16:06:23.646-0400 7fb77e6e86c0 20 HTTP_IF_MODIFIED_SINCE=2023-05-30T20:03:16.621151421Z
2023-05-30T16:06:23.654-0400 7fb7736d26c0  2 req 5608249310521457762 0.008000289s s3:get_obj http status=200
2023-05-30T16:06:23.654-0400 7fb7736d26c0  1 ====== req done req=0x7fb6e5db6710 op status=0 http_status=200 latency=0.008000289s ======
```

**Comment by zap51** [comment]
Hello Devs,
I'm assuming it might take a while for this to be merged, but please let me know if the question at https://lists.ceph.io/hyperkitty/list/ceph-users@ceph.io/thread/PDDZB6XFB5M2JTDXQPX6WLYLGYUYDOOI/ can be achieved.

Thanks!

**Comment by cbodley** [comment]
after reproducing the checksum mismatch error with the same steps from https://tracker.ceph.com/issues/46062#note-6, i upgraded radosgws with the draft fix in https://github.com/ceph/ceph/pull/52248, and verified that this tool reschedules its replication, and that replication corrects the md5 mismatch

object on secondary zone is corrupted:
```
~/ceph/build $ s3cmd -c ../work/c2.s3cfg get s3://testbucket/6m 6m.c2
download: 's3://testbucket/6m' -> '6m.c2'  [1 of 1]    
 6291456 of 6291456   100% in    0s   176.78 MB/s  done
WARNING: MD5 signatures do not match: computed=4101694a589baca05b76afb00a53206c, received=cca06bdd97b45abef3ac0f28f182ab69
```
repair tool on primary zone detects the encrypted multipart object:
```
~/ceph/build $ bin/radosgw-admin -c run/c1/ceph.conf bucket resync encrypted multipart --bucket testbucket
{
    "bucket": "testbucket",
    "bucket_id": "58fd8dfe-4738-4885-bede-f684962fe59f.4190.1",
    "progress": [
        {
            "modified": [
                {
                    "name": "6m",
                    "mtime": "2023-06-29T17:06:53.860185Z"
                }
            ],
            "total processed": 2,
            "marker": "6m"
        }
    ]
}
```
the re-replicated object has correct checksum:
```
~/ceph/build $ s3cmd -c ../work/c2.s3cfg get s3://testbucket/6m 6m.c2
download: 's3://testbucket/6m' -> '6m.c2'  [1 of 1]
 6291456 of 6291456   100% in    0s   128.03 MB/s  done
```

**Comment by cbodley** [comment]
jenkins test make check

**Comment by cbodley** [comment]
jenkins test api

**Comment by cbodley** [comment]
passed qa in https://pulpito.ceph.com/cbodley-2023-08-02_21:27:38-rgw-wip-cbodley-testing-distro-default-smithi/

**Comment by cbodley** [comment]
jenkins test api

**Comment by cbodley** [comment]
jenkins build docs

**Comment by cbodley** [comment]
jenkins test docs

**Comment by cbodley** [comment]
moved commits into https://github.com/ceph/ceph/pull/52248 to simplify backports

**Pull request closed without merging**
