### PR TITLE
mgr/dashboard: Throw a more meaningful exception

### PR DESCRIPTION
**Pull request by votdev**
When the orchestrator is not available, a HTTP 503 error was thrown. This results in a non meaningful error message in the UI. Because of that this PR will throw a 503 with a description that will help the user to understand the problem.

After:
Bildschirmfoto vom 2019-12-13 11-15-22

Before:
Bildschirmfoto vom 2019-12-13 11-08-04

Signed-off-by: Volker Theile <vtheile@suse.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [x] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by votdev** [comment]
jenkins test make check arm64

**Comment by votdev** [comment]
jenkins test make check arm64

**Comment by votdev** [comment]
jenkins test make check

**Comment by s0nea** [comment]
```
[0;36m./controllers/orchestrator.py[0m:[1;33m4[0m:[1;32m1[0m: [1;31mF401[0m 'cherrypy' imported but unused
1     F401 'cherrypy' imported but unused
```

**Comment by votdev** [comment]
jenkins test dashboard

**Comment by callithea** [comment]
> QA test run failed:
> http://pulpito.ceph.com/tdehler-2019-12-13_19:13:17-rados:dashboard-wip-tdehler-testing-32032-32234-distro-basic-mira/
> 
> The failure seems to be related to #31811

@s0nea do you mean it's related to #32032 instead of #31811?

**Comment by s0nea** [comment]
> @s0nea do you mean it's related to #32032 instead of #31811?

Yes, sorry. Pasted the wrong URL.

**Comment by votdev** [comment]
jenkins test dashboard

**Comment by votdev** [comment]
jenkins test dashboard

**Comment by votdev** [comment]
jenkins test make check arm64

**Comment by votdev** [comment]
jenkins test make check arm64

**Comment by votdev** [comment]
jenkins test dashboard

**Comment by votdev** [comment]
jenkins test dashboard

**Comment by votdev** [comment]
jenkins test dashboard

**Comment by votdev** [comment]
jenkins test dashboard

**Pull request merged**
