### PR TITLE
qa: install build dependencies for cfuse_workunit_kernel_untar_build.yaml

### PR DESCRIPTION
**Pull request by neha-ojha**
Fixes: https://tracker.ceph.com/issues/36076
Signed-off-by: Neha Ojha <nojha@redhat.com>

- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by neha-ojha** [comment]
http://pulpito.ceph.com/nojha-2018-09-19_22:24:50-powercycle-master-distro-basic-smithi/

**Comment by yuriw** [comment]
we need it on `luminous' and maybe `mimic`

**Comment by yuriw** [comment]
`CEPH_QA_MAIL="ceph-qa@ceph.com"; MACHINE_NAME=smithi; CEPH_BRANCH=luminous`
`teuthology-suite -v --ceph-repo https://github.com/ceph/ceph.git --suite-repo https://github.com/ceph/ceph.git -c $CEPH_BRANCH -S $SHA1 -m $MACHINE_NAME -s powercycle -k distro -p 70 -e $CEPH_QA_MAIL --suite-branch master --filter cfuse_workunit_kernel_untar_build`


http://pulpito.ceph.com/yuriw-2018-09-20_15:46:54-powercycle-luminous-distro-basic-smithi/

**Comment by neha-ojha** [comment]
The backport field is appropriate in https://tracker.ceph.com/issues/36076, since this fix is not required in `luminous`.

**Pull request merged**
