### PR TITLE
Bucket naming restrictions

### PR DESCRIPTION
**Pull request by harshalgupta**
Changes for Bucket Name restriction: Added two cofiguration option prameters in place of existing 'rgw_relaxed_s3_bucket_names'
a. rgw_s3_bucket_name_access_strictness (default value = 1) for accessing older buckets(access param)
b. rgw_s3_bucket_name_create_strictness (default value = 2) for creating new ones. (create param)
Both can have values(indepently) 0, 1 and 2 which signifies : 
0 - Follows same validation rules as already present with flag relaxed_name=true.
1 - Follows same validation rules as already present with flag relaxed_names=false.
2 - Follows new naming rules as per DNS compliance. (similar to what S3 follows)
Rules get stricter with increasing value. So a name passing rule 2 will always pass 0 and 1 and a name passing rule 1 will pass 0 but may not pass 2. 
Theses parameters are passed to validate_bucket_name(const string&, bool relaxed_names) in place of bool 'relaxed_names' as int 'name_strictness'. Based on these params checks are done on bucket name when trying to create a new bucket or access an existing one,

Example : 
User created a bucket "bucket1_" and have set option rgw_relaxed_s3_bucket_names = false.
Now after These changes, user need to set appropriate values to both option params. If user sets access param to 2, he/she will not be able to access "bucket1_" as this name will become invalid because it ends with '_' which doesnt confirm to DNS naming convention. So he/she must set rgw_s3_bucket_name_access_strictness = 1/2 to access "bucket1_" .And if he/she wants to create new buckets with names which confirms to DNS compliance, he/she should set rgw_s3_bucket_name_create_strictness =2.

Signed-off-by : Harshal Gupta harshal.gupta001@gmail.com

### CODE REVIEW

**Comment by yehudasa** [comment]
@harshalgupta any reason why you closed this one? Still need to review it

**Comment by harshalgupta** [comment]
Sorry Closed this by mistake. I will reopen it after squashing the commits

**Comment by yehudasa** [comment]
@harshalgupta @robbat2 this entire feature is ~150 loc, but spread over 19 commits. Surely some of the commits here can be squashed together?
@harshalgupta you'll need to amend your commit messages to conform with the usual cephh commit messages. Try to keep the title shorter, prefix it with 'rgw:', add some content that explains what the commit does, and add a Signed-off-by line.
Thanks!

**Comment by harshalgupta** [comment]
I Have squashed some commits and changed the commit messages as per your suggestion. 
Please review this. 
Thanks

**Comment by harshalgupta** [comment]
@yehudasa : Yeah seems like my editor is not showing files properly. I have manually fixed the spacing issues this time and I will check for this from next time onwards. Thanks for pointing it out.

**Comment by dachary** [comment]
@harshalgupta this needs rebasing

**Comment by dachary** [comment]
@harshalgupta feel free to re-open when you have time to rebase

**Comment by hansbogert** [comment]
Did this ever get introduced through another PR?

**Pull request closed without merging**
