### PR TITLE
[DNM] rgw: make cls_user_bucket aware about tenants.

### PR DESCRIPTION
**Pull request by rzarzynski**
Fixes: http://tracker.ceph.com/issues/18364.

### CODE REVIEW

**Comment by rzarzynski** [comment]
s3-tests not Tempest haven't found any regression here.

**Comment by cbodley** [comment]
@rzarzynski there's an existing pr https://github.com/ceph/ceph/pull/9938 to address this, but we found there were issues with backward-compatibility of the bucket stats. can you read through my comments there to see if your approach has the same issues?

**Comment by rzarzynski** [comment]
@cbodley: I've just pushed an *early* rework of the fix. The buckets listing operation should be now aware about tenant though this still needs some testing.

**Comment by yehudasa** [comment]
@rzarzynski what's the status of this one?

**Comment by rzarzynski** [comment]
@yehudasa: the issue with stats-coherency-after-upgrade popped up once again. I'm putting the DNM flag for now and working on a fix.

**Comment by rzarzynski** [comment]
Closing in favor of #13220.

**Pull request closed without merging**
