### PR TITLE
crimson: clear AlienStore::coll_map in umount rather than in stop

### PR DESCRIPTION
**Pull request by athanatos**
A recent BlueStore change added an assert validating that there are no open CollectionRef's at umount time.

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Comment by athanatos** [comment]
Quick crimson-rados --limit 10 seems ok: https://pulpito.ceph.com/sjust-2024-08-08_06:49:22-crimson-rados-wip-sjust-crimson-testing-2024-08-07-distro-default-smithi/

**Comment by cyx1231st** [comment]
jenkins test make check

**Review by cyx1231st — APPROVED** [review]

**Review by Matan-B — APPROVED** [review]

**Comment by athanatos** [comment]
Full crimson-rados run: http://pulpito.ceph.com/sjust-2024-08-12_01:52:07-crimson-rados-wip-sjust-crimson-testing-2024-08-07-distro-default-smithi/

@Matan-B I'm also fine with merging this one without a full run -- my short run above should suffice to show that it's correct and I think main doesn't work now without this fix.

**Comment by Matan-B** [comment]
Main is broken without this PR. Merged.

**Pull request merged**
