### PR TITLE
ceph-dencoder: add RGWPeriodLatestEpochInfo support.

### PR DESCRIPTION
**Pull request by joke-lee**

### CODE REVIEW

**Comment by joke-lee** [comment]
hi @cbodley do you mind help review this?

**Comment by cbodley** [comment]
looks good, and it caught a bug! `make check` failed on this test:
```diff
**** RGWPeriodLatestEpochInfo test 1 dump_json check failed ****
   ceph-dencoder type RGWPeriodLatestEpochInfo select_test 1 dump_json > /tmp/typ-J5Y6pd2gb
   ceph-dencoder type RGWPeriodLatestEpochInfo select_test 1 encode decode dump_json > /tmp/typ-zQgJayoaW
2c2
<     "latest_epoch": 107900952
---
>     "latest_epoch": 120221720
```
because the epoch is used uninitialized. can you please add a default initializer?
```c++
struct RGWPeriodLatestEpochInfo {
  epoch_t epoch = 0;
```

**Comment by joke-lee** [comment]
hi @cbodley ,code update

**Comment by joke-lee** [comment]
retest this please.

**Comment by joke-lee** [comment]
retest this please.

**Pull request merged**
