### PR TITLE
mon: update get_store_prefixes implementations

### PR DESCRIPTION
**Pull request by jcsp**
Fixes: http://tracker.ceph.com/issues/21534

### CODE REVIEW

**Comment by jcsp** [comment]
(merge after https://github.com/ceph/ceph/pull/17929)

**Comment by jcsp** [comment]
make check failed on a download

**Comment by jcsp** [comment]
retest this please

**Comment by jecluis** [comment]
passed monthrash:

http://pulpito.ceph.com/joao-2017-09-25_14:27:49-rados:monthrash-wip-joao-testing_2017-09-25-distro-basic-smithi/
http://pulpito.ceph.com/joao-2017-09-25_18:10:07-rados:monthrash-wip-joao-testing_2017-09-25-distro-basic-smithi/
http://pulpito.ceph.com/joao-2017-09-26_07:26:40-rados:monthrash-wip-joao-testing_2017-09-25-distro-basic-smithi/

**Comment by jecluis** [comment]
I'm okay merging this given the build failure seems solely related with boost not being downloaded on arm64.

**Pull request merged**
