### PR TITLE
rgw: add support for "end_marker" parameter for GET on Swift account.

### PR DESCRIPTION
**Pull request by rzarzynski**

### CODE REVIEW

**Comment by rzarzynski** [comment]
@yehudasa reworked according to your suggestions.

Original branch: https://github.com/rzarzynski/ceph/tree/wip-10682-old-1.

**Comment by rzarzynski** [comment]
@yehudasa rebased due to merge conflict.

**Comment by yehudasa** [comment]
@rzarzynski this looks fine. How has it been tested? Did you run the s3-tests suite against it?

**Comment by rzarzynski** [comment]
@yehudasa rebased due to merge conflict.
I'm attaching the results from s3-tests against [current master](https://gist.github.com/rzarzynski/b0161e4d787dd5ca3e89) and [this branch](https://gist.github.com/rzarzynski/4f088f8dc59791179046).

**Comment by rzarzynski** [comment]
@yehudasa it looks that we have some problem. Tested on vanilla master (e24509b6969ef979752a68735dfd67e5cabe9ad2; without this PR): 

```
$ curl -i http://localhost:8000/swift/v1/ -X GET -H "X-Auth-Token: $token"
HTTP/1.1 204 No Content
X-Timestamp: 1430311840.68982
X-Account-Container-Count: 0
X-Account-Object-Count: 0
X-Account-Bytes-Used: 0
X-Account-Bytes-Used-Actual: 0
Content-Length: 1
Accept-Ranges: bytes
Date: Wed, 29 Apr 2015 12:50:40 GMT

$ curl -i http://localhost:8000/swift/v1/cont -X PUT -H "X-Auth-Token: $token"
HTTP/1.1 201 Created
Content-Length: 0
Accept-Ranges: bytes
Date: Wed, 29 Apr 2015 12:50:56 GMT

$ curl -i http://localhost:8000/swift/v1/ -X GET -H "X-Auth-Token: $token"
HTTP/1.1 200 OK
X-Timestamp: 1430311859.43158
X-Account-Container-Count: 0
X-Account-Object-Count: 0
X-Account-Bytes-Used: 0
X-Account-Bytes-Used-Actual: 0
Content-Length: 1
Accept-Ranges: bytes
Date: Wed, 29 Apr 2015 12:50:59 GMT

c
```

**Comment by yehudasa** [comment]
@rzarzynski do we still have that problem?

**Comment by rzarzynski** [comment]
@yehudasa rebased due to merge conflict. Retested using both _s3-tests_ and Tempest - no regression detected in comparison to current master (7fbf013d446c607af9b3e196680fbdbdc1b5172d).

**Comment by rzarzynski** [comment]
@yehudasa rebased to master due to a merge conflict.

**Comment by rzarzynski** [comment]
@yehudasa output from yesterday test run:
* [s3-tests + Tempest OSOS API campaign against this PR](https://gist.github.com/rzarzynski/e75f0e704d4e45eda9ed),
* [s3-tests + Tempest OSOS API campaign against master](https://gist.github.com/rzarzynski/13249a18e77681b85d6b).

In short summary:
* s3-tests against wip-10682: FAILED (SKIP=4, errors=4, failures=6);
* s3-tests against master: FAILED (SKIP=4, errors=4, failures=6);
* Tempest against wip-10682: FAILED (id=618, failures=46 (-77), skips=2);
* Tempest against master: FAILED (id=619, failures=46, skips=2).

**Comment by rzarzynski** [comment]
@yehudasa switched to _const string&_.

**Comment by yehudasa** [comment]
Will open a new pull request for this that will include my changes and fixes

**Comment by yehudasa** [comment]
oops, closed the wrong PR

**Comment by rzarzynski** [comment]
@yehudasa rebased due to a small merge conflict.

**Comment by rzarzynski** [comment]
@yehudasa rebased due to small conflicts with wip-5073.

**Pull request merged**
