### PR TITLE
mgr/mgr_module:delete invalid judgment

### PR DESCRIPTION
**Pull request by dengchl01**
## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Review by tchaikov — APPROVED** [review]

**Review by tchaikov — CHANGES_REQUESTED** [review]
```
flake8 run-test: commands[0] | flake8 --config=tox.ini alerts balancer cephadm crash devicehealth diskprediction_local hello iostat localpool orchestrator prometheus selftest
diskprediction_local/module.py:96:40: E127 continuation line over-indented for visual indent
diskprediction_local/module.py:97:40: E127 continuation line over-indented for visual indent
2     E127 continuation line over-indented for visual indent
ERROR: InvocationError for command /home/jenkins-build/build/workspace/ceph-pull-requests/src/pybind/mgr/.tox/flake8/bin/flake8 --config=tox.ini alerts balancer cephadm crash devicehealth diskprediction_local hello iostat localpool orchestrator prometheus selftest (exited with code 1)
```

please address the flake8 issues, and  could you add a "`Signed-off-by`" line at the end of your commit message? "git commit -s" will do the trick for you. see https://github.com/ceph/ceph/blob/master/SubmittingPatches.rst#sign-your-work

**Comment by dengchl01** [comment]
Signed-off-by: dengchl01 dengchl01@inspur.com

**Comment by tchaikov** [comment]
@dengchl01 could you please fold these two commits into a single one?

**Comment by dengchl01** [comment]
yes, please merge thanks

 

发件人: Kefu Chai ***@***.***> 
发送时间: 2021年6月9日 16:11
收件人: ceph/ceph ***@***.***>
抄送: Charlie Deng (邓长亮)-云服务集团 ***@***.***>; Mention ***@***.***>
主题: Re: [ceph/ceph] mgr/mgr_module:delete invalid judgment (#41770)

 

@dengchl01 <https://github.com/dengchl01>  could you please fold these two commits into a single one?

**Comment by tchaikov** [comment]
it seems that the update PR was created at #41781.

@dengchl01 in future, i'd suggest use `git push -f` to update existing pull request to address reviewers' comments instead of creating a new one, so that we can preserve the discussion history of a certain PR.

**Comment by tchaikov** [comment]
closing in favor of #41781

**Comment by dengchl01** [comment]
But I can't operate, Please teach me

 

发件人: Kefu Chai ***@***.***> 
发送时间: 2021年6月9日 17:06
收件人: ceph/ceph ***@***.***>
抄送: Charlie Deng (邓长亮)-云服务集团 ***@***.***>; Mention ***@***.***>
主题: Re: [ceph/ceph] mgr/mgr_module:delete invalid judgment (#41770)

 

it seems that the update PR was created at #41781 <https://github.com/ceph/ceph/pull/41781> .

@dengchl01 <https://github.com/dengchl01>  in future, i'd suggest use git push -f to update existing pull request to address reviewers' comments instead of creating a new one, so that we can preserve the discussion history of a certain PR.

**Pull request closed without merging**
