### PR TITLE
kraken: rbd-mirror: failover and failback of unmodified image results in split-brain

### PR DESCRIPTION
**Pull request by dillaman**
http://tracker.ceph.com/issues/19872

### CODE REVIEW

**Comment by trociny** [comment]
@ceph-jenkins retest this please

**Comment by smithfarm** [comment]
Jenkins re-test this please (logs are gone)

**Comment by smithfarm** [comment]
@dillaman Please rebase to get rid of the obsolete failed `default` Jenkins test

**Comment by dillaman** [comment]
@smithfarm sorry -- repushed.

BTW -- what at the odds of a 11.2.1 being released before Kraken is killed off by Luminous 12.2.0?

**Comment by smithfarm** [comment]
@dillaman I'd say 50:50. I'm focusing on 10.2.8 now, and will turn to 11.2.1 once that's in QE.

**Comment by smithfarm** [comment]
Jenkins re-test this please (kraken "make check" is showing a high incidence of the "Unix Domain socket path too long" failure)

**Comment by smithfarm** [comment]
@dillaman The make check failure has hopefully been fixed by #16069 - could you please rebase to pick it up?

**Comment by smithfarm** [comment]
Nevermind, rebase not necessary (Jenkins merges into latest base branch before starting the test).

Jenkins re-test this please

**Comment by smithfarm** [comment]
This PR passed an rbd run at http://tracker.ceph.com/issues/19009#note-56 (there were some failures that required a fix - applied via #16113).

**Pull request merged**
