### PR TITLE
rgw/dbstore: Fix DBstore build conflicts

### PR DESCRIPTION
**Pull request by soumyakoduri**
Fixing build conflicts with latest sal multipart/writer changes

Signed-off-by: Soumya Koduri <skoduri@redhat.com>

### CODE REVIEW

**Comment by soumyakoduri** [comment]
http://pulpito.front.sepia.ceph.com/soumyakoduri-2021-07-31_14:59:06-rgw-wip-skoduri-dbstore-fixes-distro-basic-smithi/

**Comment by soumyakoduri** [comment]
http://pulpito.front.sepia.ceph.com/soumyakoduri-2021-07-31_14:59:06-rgw-wip-skoduri-dbstore-fixes-distro-basic-smithi/

**Comment by cbodley** [comment]
i think we should consider enabling `WITH_RADOSGW_DBSTORE` by default, so our CI can verify that it builds successfully and prevent us from merging any PRs that break it

what do you think @soumyakoduri?

**Comment by cbodley** [comment]
> That really helps. What about package build?

are there any dependencies other than sqlite to worry about?

**Comment by soumyakoduri** [comment]
> > That really helps. What about package build?
> 
> are there any dependencies other than sqlite to worry about?

No. I will enable the cmake option then?

**Comment by soumyakoduri** [comment]
http://pulpito.front.sepia.ceph.com/soumyakoduri-2021-08-04_07:39:25-rgw-wip-skoduri-dbstore-fixes-distro-basic-smithi/

**Review by dang — APPROVED** [review]

**Comment by soumyakoduri** [comment]
http://pulpito.front.sepia.ceph.com/soumyakoduri-2021-08-09_16:30:52-rgw-wip-skoduri-dbstore-fixes-distro-basic-smithi/

**Comment by dang** [comment]
Fix being worked on here: https://github.com/ceph/ceph/pull/42744

**Comment by soumyakoduri** [comment]
> @soumyakoduri
> 
> This does not build under FreeBSD/Clang>
> Next to `char data[datalen+1] ={}` being an illegal construct, I also get tons of linking errors.
> Example:
> 
> ```
> /usr/local/bin/ld: ../../../lib/libsqlite_db.a(sqliteDB.cc.o): in function `SQLiteDB::createTables(DoutPrefixProvider const*)':
> /home/jenkins/workspace/ceph-master-compile/src/rgw/store/dbstore/sqlite/sqliteDB.cc:480: undefined reference to `RGWBucketInfo::RGWBucketInfo()'
> /usr/local/bin/ld: /home/jenkins/workspace/ceph-master-compile/src/rgw/store/dbstore/sqlite/sqliteDB.cc:480: undefined reference to `RGWBucketInfo::~RGWBucketInfo()'
> /usr/local/bin/ld: ../../../lib/libsqlite_db.a(sqliteDB.cc.o): in function `~DBOpBucketInfo':
> /home/jenkins/workspace/ceph-master-compile/src/rgw/store/dbstore/common/dbstore.h:49: undefined reference to `RGWBucketInfo::~RGWBucketInfo()'
> /usr/local/bin/ld: ../../../lib/libsqlite_db.a(sqliteDB.cc.o): in function `decode(rgw_sync_pipe_filter&, ceph::buffer::v15_2_0::list::iterator_impl<true>&)':
> /home/jenkins/workspace/ceph-master-compile/src/rgw/rgw_sync_policy.h:248: undefined reference to `rgw_sync_pipe_filter::decode(ceph::buffer::v15_2_0::list::iterator_impl<true>&)'
> /usr/local/bin/ld: ../../../lib/libsqlite_db.a(sqliteDB.cc.o): in function `DBOpBucketInfo':
> /home/jenkins/workspace/ceph-master-compile/src/rgw/store/dbstore/common/dbstore.h:38: undefined reference to `RGWBucketInfo::~RGWBucketInfo()'
> /usr/local/bin/ld: ../../../lib/libsqlite_db.a(sqliteDB.cc.o): in function `encode(rgw_sync_pipe_filter const&, ceph::buffer::v15_2_0::list&, unsigned long)':
> /home/jenkins/workspace/ceph-master-compile/src/rgw/rgw_sync_policy.h:248: undefined reference to `rgw_sync_pipe_filter::encode(ceph::buffer::v15_2_0::list&) const'
> /usr/local/bin/ld: ../../../lib/libdbstore_lib.a(dbstore.cc.o): in function `rgw::store::DB::get_user(DoutPrefixProvider const*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, RGWUserInfo&, std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, ceph::buffer::v15_2_0::list, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, ceph::buffer::v15_2_0::list> > >*, RGWObjVersionTracker*)':
> /home/jenkins/workspace/ceph-master-compile/src/rgw/store/dbstore/common/dbstore.cc:283: undefined reference to `RGWBucketInfo::RGWBucketInfo()'
> /usr/local/bin/ld: /home/jenkins/workspace/ceph-master-compile/src/rgw/store/dbstore/common/dbstore.cc:283: undefined reference to `RGWBucketInfo::~RGWBucketInfo()'
> /usr/local/bin/ld: ../../../lib/libdbstore_lib.a(dbstore.cc.o): in function `rgw::store::DB::store_user(DoutPrefixProvider const*, RGWUserInfo&, bool, std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, ceph::buffer::v15_2_0::list, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, ceph::buffer::v15_2_0::list> > >*, RGWObjVersionTracker*, RGWUserInfo*)':
> /home/jenkins/workspace/ceph-master-compile/src/rgw/store/dbstore/common/dbstore.cc:328: undefined reference to `RGWBucketInfo::RGWBucketInfo()'
> /usr/local/bin/ld: /home/jenkins/workspace/ceph-master-compile/src/rgw/store/dbstore/common/dbstore.cc:328: undefined reference to `RGWBucketInfo::~RGWBucketInfo()'
> /usr/local/bin/ld: ../../../lib/libdbstore_lib.a(dbstore.cc.o): in function `rgw::store::DB::remove_user(DoutPrefixProvider const*, RGWUserInfo&, RGWObjVersionTracker*)':
> /home/jenkins/workspace/ceph-master-compile/src/rgw/store/dbstore/common/dbstore.cc:390: undefined reference to `RGWBucketInfo::RGWBucketInfo()'
> /usr/local/bin/ld: /home/jenkins/workspace/ceph-master-compile/src/rgw/store/dbstore/common/dbstore.cc:390: undefined reference to `RGWBucketInfo::~RGWBucketInfo()'
> /usr/local/bin/ld: ../../../lib/libdbstore_lib.a(dbstore.cc.o): in function `rgw::store::DB::get_bucket_info(DoutPrefixProvider const*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, RGWBucketInfo&, std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, ceph::buffer::v15_2_0::list, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, ceph::buffer::v15_2_0::list> > >*, std::__1::chrono::time_point<ceph::real_clock, std::__1::chrono::duration<unsigned long, std::__1::ratio<1l, 1000000000l> > >*, obj_version*)':
> /home/jenkins/workspace/ceph-master-compile/src/rgw/store/dbstore/common/dbstore.cc:437: undefined reference to `RGWBucketInfo::RGWBucketInfo()'
> /usr/local/bin/ld: /home/jenkins/workspace/ceph-master-compile/src/rgw/store/dbstore/common/dbstore.cc:438: undefined reference to `RGWBucketInfo::RGWBucketInfo()'
> /usr/local/bin/ld: /home/jenkins/workspace/ceph-master-compile/src/rgw/store/dbstore/common/dbstore.cc:437: undefined reference to `RGWBucketInfo::~RGWBucketInfo()'
> /usr/local/bin/ld: /home/jenkins/workspace/ceph-master-compile/src/rgw/store/dbstore/common/dbstore.cc:438: undefined reference to `RGWBucketInfo::~RGWBucketInfo()'
> /usr/local/bin/ld: ../../../lib/libdbstore_lib.a(dbstore.cc.o): in function `rgw::store::DB::create_bucket(DoutPrefixProvider const*, RGWUserInfo const&, rgw_bucket&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, rgw_placement_rule const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, RGWQuotaInfo const*, std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, ceph::buffer::v15_2_0::list, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, ceph::buffer::v15_2_0::list> > >&, RGWBucketInfo&, obj_version*, obj_version*, std::__1::chrono::time_point<ceph::real_clock, std::__1::chrono::duration<unsigned long, std::__1::ratio<1l, 1000000000l> > >, rgw_bucket*, unsigned int*, optional_yield, bool)':
> /home/jenkins/workspace/ceph-master-compile/src/rgw/store/dbstore/common/dbstore.cc:499: undefined reference to `RGWBucketInfo::RGWBucketInfo()'
> /usr/local/bin/ld: /home/jenkins/workspace/ceph-master-compile/src/rgw/store/dbstore/common/dbstore.cc:504: undefined reference to `RGWBucketInfo::RGWBucketInfo()'
> /usr/local/bin/ld: /home/jenkins/workspace/ceph-master-compile/src/rgw/store/dbstore/common/dbstore.cc:499: undefined reference to `RGWBucketInfo::~RGWBucketInfo()'
> /usr/local/bin/ld: /home/jenkins/workspace/ceph-master-compile/src/rgw/store/dbstore/common/dbstore.cc:522: undefined reference to `RGWObjVersionTracker::generate_new_write_ver(ceph::common::CephContext*)'
> 
> and more
> ```
> 
> Any idee what's up here?

That's strange. 
https://github.com/ceph/ceph/blob/master/src/rgw/store/dbstore/CMakeLists.txt#L30 
It is linked to "rgw_common" library and so all these definitions should have ideally been linked properly. I am not sure why it throws errors on FreeBSD.. 
@kalebskeithley @dang @cbodley  .. any pointers?

**Comment by soumyakoduri** [comment]
@wjwithagen  .. could you please try adding "rgw_common" to the target_link_libraries list (at line shown below) & check if it resolves link issue. 
https://github.com/ceph/ceph/blob/master/src/rgw/store/dbstore/sqlite/CMakeLists.txt#L16

**Comment by wjwithagen** [comment]
> 
> 
> @wjwithagen .. could you please try adding "rgw_common" to the target_link_libraries list (at line shown below) & check if it resolves link issue.
> https://github.com/ceph/ceph/blob/master/src/rgw/store/dbstore/sqlite/CMakeLists.txt#L16

That seems to resolve the issue.

**Pull request merged**
