### PR TITLE
qa/mgr/balancer: Add cram based test for altering target_max_misplaced_ratio setting

### PR DESCRIPTION
**Pull request by shyukri**
Partially fixes: https://tracker.ceph.com/issues/20283

---

Signed-off-by: Shyukri Shyukriev <shshyukriev@suse.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [x] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`

</details>

### CODE REVIEW

**Comment by shyukri** [comment]
Run: http://qa-proxy.ceph.com/teuthology/shyukri-2019-09-30_10:52:40-rados:singleton-nomsgr-master-distro-basic-smithi/4348345/teuthology.log

**Comment by smithfarm** [comment]
"make check" failure is unrelated (obviously)

Added @gregsfortytwo as reviewer because this could be seen as partially addressing https://tracker.ceph.com/issues/20283 (?)

**Comment by gregsfortytwo** [comment]
This looks fine to me at a quick skim but I've never even run the balancer. ;)
(No need to tag me every time somebody adds testing for a command!)

**Comment by smithfarm** [comment]
@jan--f Would you like to take a shot at reviewing this? Or suggest someone who might be game?

**Comment by dzafman** [comment]
@smithfarm I'm not familiar with balancer either.

**Comment by smithfarm** [comment]
jenkins test make check

**Comment by smithfarm** [comment]
jenkins test make check

**Comment by smithfarm** [comment]
jenkins test make check

**Comment by smithfarm** [comment]
@tchaikov I can't seem to get this through "make check". Each time it fails in a different way. Can you think of any way the changes in this PR could be related to the make check failure?

**Comment by smithfarm** [comment]
jenkins test make check

**Comment by tchaikov** [comment]
@smithfarm sorry for the latency. no, i cannot. these failures were caused by dashboard frontend tests. one of them was fixed recently, so we now have better chance to get a green "make check" run now.

**Comment by tchaikov** [comment]
- http://pulpito.ceph.com/kchai-2019-10-17_15:27:09-rados-wip-kefu-testing-2019-10-15-1130-distro-basic-mira/
- http://pulpito.ceph.com/kchai-2019-10-15_09:41:56-rados-wip-kefu-testing-2019-10-15-1130-distro-basic-mira/

**Pull request merged**
