### PR TITLE
mgr/dashboard: Fix zsh support in run-backend-api-tests.sh

### PR DESCRIPTION
**Pull request by sebastian-philipp**
Also properly install python-common

Fixes: https://tracker.ceph.com/issues/42402

Signed-off-by: Sebastian Wagner <sebastian.wagner@suse.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`

</details>

### CODE REVIEW

**Comment by callithea** [comment]
jenkins test dashboard backend

**Comment by sebastian-philipp** [comment]
> jenkins test dashboard backend

Failed with 

```
2019-10-23 12:20:31,325.325 INFO:__main__:======================================================================
2019-10-23 12:20:31,325.325 INFO:__main__:ERROR: test_create_export (tasks.mgr.dashboard.test_ganesha.GaneshaTest)
2019-10-23 12:20:31,325.325 INFO:__main__:----------------------------------------------------------------------
2019-10-23 12:20:31,325.325 INFO:__main__:Traceback (most recent call last):
2019-10-23 12:20:31,325.325 INFO:__main__:  File "/home/jenkins-build/build/workspace/ceph-dashboard-pr-backend/qa/tasks/mgr/dashboard/helper.py", line 154, in setUp
2019-10-23 12:20:31,326.326 INFO:__main__:    self.wait_for_health_clear(20)
2019-10-23 12:20:31,326.326 INFO:__main__:  File "/home/jenkins-build/build/workspace/ceph-dashboard-pr-backend/qa/tasks/ceph_test_case.py", line 131, in wait_for_health_clear
2019-10-23 12:20:31,326.326 INFO:__main__:    self.wait_until_true(is_clear, timeout)
2019-10-23 12:20:31,326.326 INFO:__main__:  File "/home/jenkins-build/build/workspace/ceph-dashboard-pr-backend/qa/tasks/ceph_test_case.py", line 163, in wait_until_true
2019-10-23 12:20:31,326.326 INFO:__main__:    raise RuntimeError("Timed out after {0}s".format(elapsed))
2019-10-23 12:20:31,326.326 INFO:__main__:RuntimeError: Timed out after 20s
```

**Comment by sebastian-philipp** [comment]
jenkins test dashboard backend

**Comment by sebastian-philipp** [comment]
jenkins test make check

**Comment by sebastian-philipp** [comment]
jenkins test make check

**Comment by sebastian-philipp** [comment]
https://tracker.ceph.com/issues/42446

**Comment by sebastian-philipp** [comment]
jenkins test dashboard backend

**Comment by s0nea** [comment]
jenkins test make check

**Comment by sebastian-philipp** [comment]
```
The following tests FAILED:
	175 - unittest_rgw_amqp (Failed)
```
sigh.

**Comment by sebastian-philipp** [comment]
jenkins test dashboard backend

**Comment by sebastian-philipp** [comment]
jenkins test make check

**Comment by sebastian-philipp** [comment]
jenkins test dashboard backend

**Comment by sebastian-philipp** [comment]
https://tracker.ceph.com/issues/42446

**Comment by sebastian-philipp** [comment]
jenkins test dashboard backend

**Comment by sebastian-philipp** [comment]
@p-se does this work for you?

**Comment by sebastian-philipp** [comment]
@callithea I'm constantly hitting https://tracker.ceph.com/issues/42446 here. Is there anything I can do?

**Comment by sebastian-philipp** [comment]
jenkins test dashboard backend

**Comment by callithea** [comment]
> @callithea I'm constantly hitting https://tracker.ceph.com/issues/42446 here. Is there anything I can do?

@sebastian-philipp I think this is causing almost all backend API test runs to fail, it would be great if this could be fixed somehow, but I'm not sure what needs to be done to get rid of this error..
Update: I can reproduce those errors on my local system based on the master branch.
Logs of the job are available here if you want to take a look:
https://jenkins.ceph.com/job/ceph-dashboard-pr-backend/ws/build/out/ (note that they will be gone when a new job is executing the tests).

**Comment by sebastian-philipp** [comment]
So, how do we get this in now? (This PR blocks #30662 )

**Comment by callithea** [comment]
> So, how do we get this in now? (This PR blocks #30662 )

@sebastian-philipp the backend API test is not a required Job to pass and we know that the failures are not related to this PR. At least it's possible to get at the stage where we know that it's possible to still run the tests in Jenkins, if this is sufficient and if you need to merge it to unblock the other PR, feel free to do so.

**Pull request merged**
