### PR TITLE
common: tracked op fixes

### PR DESCRIPTION
**Pull request by wonzhq**
Since there is a bug somewhere in the code which prevents #4190 from passing the teuthology test, I'm extracting some of the commits from #4190 into this PR. These commits should have nothing to do with that bug.

### CODE REVIEW

**Comment by wonzhq** [comment]
@tchaikov do you mind to take a look at this one? It's already reviewed by you in #4190.
Thanks!

**Comment by tchaikov** [comment]
@wonzhq i understand that you are very likely a victim of some unrelated issue [0], but why do you think your slimmed version of #4190 can pass the qa run, in other words, can survive the disturbance of issue [0]? or you have tested this pull request in the lab?

---
[0] http://tracker.ceph.com/issues/10631

**Comment by wonzhq** [comment]
No, I haven't run it through teuthology test yet. The bug happens in the dumping in flight ops case. And the commits in this PR don't touch that part of code. So I am guessing this PR won't expose that bug...

**Comment by tchaikov** [comment]
ack. will schedule a qa run to confirm your theory =)

**Comment by tchaikov** [comment]
tested

http://pulpito.ceph.com/ubuntu-2015-06-15_22:35:49-rados-wip-kefu-testing---basic-multi
http://pulpito.ceph.com/ubuntu-2015-06-16_22:31:53-rados-wip-kefu-testing---basic-multi
http://pulpito.ceph.com/ubuntu-2015-06-17_06:59:09-rados-wip-kefu-testing---basic-multi
http://pulpito.ceph.com/ubuntu-2015-06-18_08:24:05-rados-wip-kefu-testing---basic-multi

**Pull request merged**
