### PR TITLE
[DNM] pacific: qa: add subvolume option flavors

### PR DESCRIPTION
**Pull request by mchangir**
backport tracker: https://tracker.ceph.com/issues/59202

---

backport of https://github.com/ceph/ceph/pull/45556
parent tracker: https://tracker.ceph.com/issues/54317

this backport was staged using ceph-backport.sh version 16.0.0.6848
find the latest version at https://github.com/ceph/ceph/blob/master/src/script/ceph-backport.sh

### CODE REVIEW

**Comment by vshankar** [comment]
@mchangir make check fails with:

```
flake8: commands[0] /home/jenkins-build/build/workspace/ceph-pull-requests/qa> flake8 --select=F,E9 --exclude=venv,.tox
./tasks/cephadm.py:834:16: F821 undefined name 'MDSCluster'
./tasks/cephadm.py:844:20: F821 undefined name 'deepcopy'
./tasks/cephadm.py:849:18: F821 undefined name 'Filesystem'
./tasks/cephfs/fuse_mount.py:90:9: F821 undefined name 'mount_cmd'
```

**Comment by vshankar** [comment]
Oops. @mchangir I meant pull in commit from PR #51050 into this.

**Comment by mchangir** [comment]
> Oops. @mchangir I meant pull in commit from PR #51050 into this.

I'll need to redo #51509 once more using #51050

**Comment by mchangir** [comment]
> > Oops. @mchangir I meant pull in commit from PR #51050 into this.
> 
> I'll need to redo #51509 once more using #51050

main and pacific have diverged making this more painful

**Pull request closed without merging**
