### PR TITLE
jewel: osd: Increase priority for inactive PGs backfill

### PR DESCRIPTION
**Pull request by byo**
http://tracker.ceph.com/issues/18794

### CODE REVIEW

**Comment by smithfarm** [comment]
@byo Thanks for the backport! I can't guarantee that it will make it into 10.2.6 but now that it's correctly staged, there is at least a chance :-)

**Comment by smithfarm** [comment]
This conflicts with #13255 and it also has a cherry-pick difference that is not mentioned in the commit message. @byo Please re-do the cherry-pick using `-x`. All files where you made manual changes should be listed at the bottom of the commit message like this:

```
(cherry picked from ...)

Conflicts:
    PendingReleaseNotes (manually changed 11.1.0 to 10.2.6)
    otherfile1 (how I resolved conflict)
    otherfile2 ( ... )
```

Thanks!

**Comment by byo** [comment]
Note: rebased on top of PR #13255 to resolve conflicts.

**Comment by smithfarm** [comment]
@byo The cherry-pick of 923e7f5ce5ed437af15e178299a61029ff48e4a2 does not have a proper description of how you resolved the conflicts. Not only that, @asheplyakov already did that backport in #13270 

One way to resolve this would be if you cherry-picked (without `-x`) Alexey's backport, with his conflict resolution, into this PR. Alternatively, @asheplyakov could cherry-pick 6a76adcdb1f92c136841d960aa7cd4e5b94addec into his PR.

**Comment by byo** [comment]
@smithfarm The cherry-pick of 923e7f5 was not initially part of this backport, the commit 78d296b I based my backport on was originally made in #13255 and I did it so that conflicts between those two can be resolved easily (i.e. if #13255 is merged first, this PR will shorten to the what is actually needed), we discussed this on IRC, I could have understood this incorrectly.
Actually I don't see proper conflict resolution description in #13255 so I guess that's why it did propagate here.

Regarding #13270 - that's already duplicate of #13255 so only one of them should be merged in fact, from my point of view it doesn't matter which one I'll base on.

**Comment by smithfarm** [comment]
@byo Oh! Thanks. I closed #13270 and removed DNM from this one.

**Comment by ktdreyer** [comment]
@liewegas @jdurgin `BranchPredictor` was asking about this in #ceph-devel today. Ok to merge for v10.2.7?

**Comment by ktdreyer** [comment]
http://pulpito.ceph.com/yuriw-2017-03-25_16:03:45-rados-jewel-integration-ktdreyer---basic-smithi/

**Pull request merged**
