### PR TITLE
crimson/common: let errorator's handlers to conditionally forward errors 

### PR DESCRIPTION
**Pull request by rzarzynski**
The use case is like the following one:

```diff
diff --git a/src/crimson/osd/replicated_recovery_backend.cc b/src/crimson/osd/replicated_recovery_backend.cc
index a96f1b8dd2b..055add2e407 100644
--- a/src/crimson/osd/replicated_recovery_backend.cc
+++ b/src/crimson/osd/replicated_recovery_backend.cc
@@ -516,10 +516,14 @@ ReplicatedRecoveryBackend::read_object_for_push_op(
       recovered_to = push_op->data_included.range_end();
     }
     return seastar::make_ready_future<uint64_t>(recovered_to);
-  }, PGBackend::read_errorator::all_same_way([](auto e) {
+  }, PGBackend::read_errorator::all_same_way([](auto e, auto&& e_raw) -> PGBackend::read_errorator::future<uint64_t> {
     logger().debug("build_push_op: read exception");
-    return seastar::make_exception_future<uint64_t>(e);
-  }));
+    if (42) {
+      return std::move(e_raw);
+    } else {
+      return seastar::make_exception_future<uint64_t>(e);
+    }
+  })).handle_error_interruptible(PGBackend::read_errorator::discard_all{});
 }

 RecoveryBackend::interruptible_future<>
```

Signed-off-by: Radosław Zarzyński <rzarzyns@redhat.com>

-------------

CC: @liu-chunmei.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by liu-chunmei** [comment]
@rzarzynski  LGTM except for  the nits Kefu point out.
BTW, does this has the same result if not return e_raw? 
        return crimson::stateful_ec{e};

**Comment by liu-chunmei** [comment]
@rzarzynski I have verified, return crimson::stateful_ec{e}; can have the same result.  needn't e_raw. FYI.

**Comment by rzarzynski** [comment]
I'm not sure. This depends on whether you want to use it on cold (like it currently is) or hot paths. `stateful_ec` is throwing (therefore slow and even not scalable as we jettisoned the Seastar's exception hack; these are the reasons why, in our discussion, I discouraged using the `stateful_error_t` family). IIUC you want to conditionally pass further around the op execution, if the `CEPH_OSD_OP_FLAG_FAILOK` is not set. I guess it won't be most of the time, so the question boils down into: do we treat all our errors as rarely happening? I believe at least some of them aren't so cold, unfortunately.

**Comment by liu-chunmei** [comment]
jenkins ceph API tests

**Comment by athanatos** [comment]
retest this please

**Review by athanatos — APPROVED** [review]

**Pull request merged**
