### PR TITLE
rpm: bump up required GCC version to 7.3.1

### PR DESCRIPTION
**Pull request by tchaikov**
so we can include the fix of
https://gcc.gnu.org/ml/libstdc++/2017-07/msg00077.html and the fix at
https://github.com/gcc-mirror/gcc/commit/7c78f2e67270187dd755632eafe3a526f4e6df30
. otherwise, if a class offers implicit conversion operator to
std::string and std::string_view, seastar will fail to compile. like

/opt/rh/devtoolset-7/root/usr/include/c++/7/bits/basic_string.h:3946:7:
note: candidate: std::basic_string<_CharT, _Traits, _Alloc>&
std::basic_string<_CharT, _Traits, _Alloc>::operator+=(const
std::basic_string<_CharT, _Traits, _Alloc>&) [with _CharT = char;
_Traits = std::char_traits<char>; _Alloc = std::allocator<char>]
       operator+=(const basic_string& __str)
       ^~~~~~~~
/opt/rh/devtoolset-7/root/usr/include/c++/7/bits/basic_string.h:3988:7:
note: candidate: std::basic_string<_CharT, _Traits, _Alloc>&
std::basic_string<_CharT, _Traits,
_Alloc>::operator+=(std::basic_string<_CharT, _Traits,
_Alloc>::__sv_type) [with _CharT = char; _Traits =
std::char_traits<char>; _Alloc = std::allocator<char>;
std::basic_string<_CharT, _Traits, _Alloc>::__sv_type =
std::basic_string_view<char>]
       operator+=(__sv_type __sv)
       ^~~~~~~~

Signed-off-by: Kefu Chai <kchai@redhat.com>

- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by cbodley** [comment]
if this is only needed for seastar currently, would it make sense to conditionalize this change on with_seastar?

**Comment by tchaikov** [comment]
@cbodley yeah, currently only seastar's `sstring` related code is suffering from this bug. but i think, if we can get the more standard compliant libstdc++ and compiler for free by add `>= 7.3.1` , why would we stay with GCC 7.2 ? and this change does not break anything because it's us who introduced the SCLs dependency, and only we are using the GCC from this repo, so it's a controlled environment.

but if you think otherwise, i'd be happy to guard it with `%if 0%{with seastar}`, but i wonder what's the advantage of doing so...

**Comment by cbodley** [comment]
okay, i'm just not familiar with how SCLs work - as long as this change doesn't effect which distros/versions we can build on, i have no objection to the pr as is

**Comment by tchaikov** [comment]
yeah, it only effects RHEL/CentOS 7.

**Pull request merged**
