### PR TITLE
qa/cephadm: Add roleless mon names to ctx.cluster.remotes role dict

### PR DESCRIPTION
**Pull request by varshar16**
Fixes: https://tracker.ceph.com/issues/45584
Signed-off-by: Varsha Rao <varao@redhat.com>

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by gekios** [comment]
It should fix the issue but maybe better use `remotes_and_roles` instead of `ctx.cluster.remotes` so it's more in accordance with the rest/clear? Apart from that lgtm

**Comment by sebastian-philipp** [comment]
success: http://pulpito.ceph.com/swagner-2020-05-18_15:53:54-rados-wip-swagner-testing-2020-05-18-1513-distro-basic-smithi/

**Comment by varshar16** [comment]
Rebased

**Comment by varshar16** [comment]
> It should fix the issue but maybe better use `remotes_and_roles` instead of `ctx.cluster.remotes` so it's more in accordance with the rest/clear? Apart from that detail lgtm

We cannot use `remotes_and_roles`. It is of type dict items. But we can do something like this
```
diff --git a/qa/tasks/cephadm.py b/qa/tasks/cephadm.py
index 1ffd02553d..c3ee263b77 100644
--- a/qa/tasks/cephadm.py
+++ b/qa/tasks/cephadm.py
@@ -1031,16 +1031,14 @@ def task(ctx, config):
 
     if config.get('roleless', False):
         # mons will be named after hosts
-        n = len(roles)
-        roles = []
         first_mon = None
-        for remote, _ in remotes_and_roles:
-            roles.append(['mon.' + remote.shortname])
+        for remote, role in remotes_and_roles:
+            role.append('mon.' + remote.shortname)
             if not first_mon:
                 first_mon = remote.shortname
                 bootstrap_remote = remote
-        log.info('No roles; fabricating mons %s' % roles)
-        
+        log.info('No mon roles; fabricating mons')
+
     ctx.ceph[cluster_name].mons = get_mons(
         roles, ips, cluster_name,
         mon_bind_msgr2=config.get('mon_bind_msgr2', True),
```

**Comment by tchaikov** [comment]
http://pulpito.ceph.com/kchai-2020-05-21_10:34:02-rados-wip-kefu-testing-2020-05-21-1652-distro-basic-smithi/

the failures are either tracked or fixed by

- https://tracker.ceph.com/issues/44595
- https://tracker.ceph.com/issues/45647
- https://tracker.ceph.com/issues/45631
- https://tracker.ceph.com/issues/44990
- #35139

**Pull request merged**
