### PR TITLE
qa: update featureful_client suite to use octopus instead of nautilus

### PR DESCRIPTION
**Pull request by sidharthanup**
Fixes: https://tracker.ceph.com/issues/49458
Signed-off-by: Sidharth Anupkrishnan <sanupkri@redhat.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by batrick** [comment]
jenkins test make check

**Review by batrick — CHANGES_REQUESTED** [review]
Few other instances:

````
$ git grep nautilus
featureful_client/old_client/tasks/0-octopus.yaml:- print: "**** done installing nautilus"
featureful_client/old_client/tasks/1-client.yaml:- print: "**** done nautilus client"
featureful_client/old_client/tasks/2-upgrade.yaml:    #- ceph osd set-require-min-compat-client nautilus
featureful_client/upgraded_client/tasks/0-octopus.yaml:- print: "**** done installing nautilus"
featureful_client/upgraded_client/tasks/1-client.yaml:- print: "**** done nautilus client"
featureful_client/upgraded_client/tasks/2-upgrade.yaml:    #- ceph osd set-require-min-compat-client nautilus
````

Please also update your commit message prefix, it's missing a space. `qa: `

**Review by tchaikov — APPROVED** [review]
https://pulpito.ceph.com/kchai-2021-03-03_07:53:25-upgrade-wip-kefu2-testing-2021-03-03-1236-distro-basic-gibba/

**Comment by batrick** [comment]
jenkins test make check

**Review by batrick — APPROVED** [review]

**Comment by batrick** [comment]
https://pulpito.ceph.com/?branch=wip-pdonnell-testing-20210303.195715

Failures are:
- https://tracker.ceph.com/issues/49607
- https://tracker.ceph.com/issues/48773
- https://tracker.ceph.com/issues/48805
- https://tracker.ceph.com/issues/49466
- https://tracker.ceph.com/issues/49605
- https://tracker.ceph.com/issues/49511
- https://tracker.ceph.com/issues/45434
- https://tracker.ceph.com/issues/44631

**Pull request merged**
