### PR TITLE
mimic: mgr: unlocked access to daemon by 'config show-with-defaults'

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/37479

### CODE REVIEW

**Comment by yuriw** [comment]
[wip-yuri4-testing-2019-10-08-1529-mimic](https://trello.com/c/nS3vi0wl/712-wip-yuri4-testing-2019-10-08-1529-mimic)

**Comment by dzafman** [comment]
This lock change crashed http://qa-proxy.ceph.com/teuthology/yuriw-2019-10-10_22:40:38-rados-wip-yuri4-testing-2019-10-08-1529-mimic-distro-basic-smithi/4400342

**Comment by smithfarm** [comment]
Thanks, @dzafman 

Unstaged from v13.2.7.

**Comment by smithfarm** [comment]
mimic EOL

**Pull request closed without merging**
