### PR TITLE
RFC common/Formatter: dump_timestamp

### PR DESCRIPTION
**Pull request by liewegas**
This is what it looks like:

```
{
    "epoch": 1,
    "fsid": "40ee807d-704b-4d3e-a94b-e60161c19cbb",
    "modified": "2019-04-25 12:10:01.488223",
    "modified_time": {
        "unix_seconds": 1556212201,
        "unix_nanoseconds": 488223994,
        "iso8601": "2019-04-25 17:10:01.488223Z"
    },
    "created": "2019-04-25 12:10:01.488223",
    "created_time": {
        "unix_seconds": 1556212201,
        "unix_nanoseconds": 488223994,
        "iso8601": "2019-04-25 17:10:01.488223Z"
    },
    "min_mon_release": 15,
    "min_mon_release_name": "octopus",
```
Questions
- Is the format okay?
- In places where we want to maintain schema compatibility, I suggest appending ``_time``.  It's a bit crufty, though.  In order places (e.g., mds/journal.cc), we dump things that nobody ever looks at, and it probably makes more sense to just replace the durring dump_stream calls with dump_timestamp.  Thoughts?

### CODE REVIEW

**Comment by liewegas** [comment]
An alternative proposal would be to simply change the existing dumps to dump_timestamp(), and make the dump_timestamp always use iso8601, which differs from the current output only in that it (1) it UTC and (2) has the 'Z' suffix

**Comment by yehudasa** [comment]
@liewegas probably makes sense to use iso8601 everywhere, unless it breaks compatibility. I also prefer to use `encode_json` wherever possible and not call `dump_xxx()` directly. Note that it can save a lot of the `open_section()` -> `dump()` -> `close_section()` sequences that I see here.

**Comment by liewegas** [comment]
Just switching the format would be the simplest thing, but we should avoid making breaking changes to the json output.

Also, I just noticed that the gmtime() utime_t function, which claims to "aim for ISO 8601", isn't quite compliant... according to the wikipedia page the date and time should be separated by ``T``, not a space.

**Comment by LenzGr** [comment]
> This is what it looks like:
> 
> ```
> {
>     "epoch": 1,
>     "fsid": "40ee807d-704b-4d3e-a94b-e60161c19cbb",
>     "modified": "2019-04-25 12:10:01.488223",
>     "modified_time": {
>         "unix_seconds": 1556212201,
>         "unix_nanoseconds": 488223994,
>         "iso8601": "2019-04-25 17:10:01.488223Z"
>     },
>     "created": "2019-04-25 12:10:01.488223",
>     "created_time": {
>         "unix_seconds": 1556212201,
>         "unix_nanoseconds": 488223994,
>         "iso8601": "2019-04-25 17:10:01.488223Z"
>     },
>     "min_mon_release": 15,
>     "min_mon_release_name": "octopus",
> ```
> 
> Questions
> 
>     * Is the format okay? 
>
>     * In places where we want to maintain schema compatibility, I suggest appending `_time`.  It's a bit crufty, though.  In order places (e.g., mds/journal.cc), we dump things that nobody ever looks at, and it probably makes more sense to just replace the durring dump_stream calls with dump_timestamp.  Thoughts?

Thanks a lot for your proposal! I find it somewhat redundant to return the same information three times, just in a different format. Returning UTC in ISO8601 format is likely the best compromise, but it's a bit difficult to parse.

Keeping in mind that the JSON output is supposed to be primarily consumed by applications, I'd suggest to let them take care of converting this data into the appropriate human-readable format.

I found [this approach](https://weblogs.asp.net/bleroy/dates-and-json) (using a time stamp) quite interesting, but I'd like to get some comments from the dashboard devs that actually have to work with this data on what they'd prefer - I added them as reviewers now.

**Comment by LenzGr** [comment]
Mark Embling [also discusses](https://markembling.info/2011/07/json-date-time) a few options that should be considered.

**Comment by liewegas** [comment]
how about: https://github.com/ceph/ceph/pull/27799

**Comment by votdev** [comment]
I vote for only one value which is ISO8601. IMHO this is better than using Unix time stamps because you do not loose the time zone info. ISO8601 can be parsed easily in many languages like Python, JS and others.

**Pull request closed without merging**
