### PR TITLE
pacific: backport PR #39607

### PR DESCRIPTION
**Pull request by rishabh-d-dave**
Backport of PR https://github.com/ceph/ceph/pull/39607

Fixes: https://tracker.ceph.com/issues/59626

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by vshankar** [comment]
Thx for the backport @rishabh-d-dave

**Comment by rishabh-d-dave** [comment]
https://pulpito.ceph.com/rishabh-2023-05-04_10:14:56-fs-wip-yuri2-testing-2023-04-26-1247-pacific-distro-default-smithi/

**Comment by rishabh-d-dave** [comment]
jenkins retest this please

**Comment by rishabh-d-dave** [comment]
@vshankar Should the message of these backported commits include "Fixes: https://tracker.ceph.com/issues/59626" line?

**Comment by vshankar** [comment]
> @vshankar Should the message of these backported commits include "Fixes: https://tracker.ceph.com/issues/59626"?

Yes.

**Comment by rishabh-d-dave** [comment]
> Thx for the backport @rishabh-d-dave

Welcome. :)

**Comment by rishabh-d-dave** [comment]
https://pulpito.ceph.com/rishabh-2023-05-04_11:13:01-fs:mirror-wip-yuri2-testing-2023-04-26-1247-pacific-distro-default-smithi/

**Comment by rishabh-d-dave** [comment]
https://pulpito.ceph.com/rishabh-2023-05-04_11:21:13-fs:mirror-wip-yuri2-testing-2023-04-26-1247-pacific-distro-default-smithi/

**Comment by vshankar** [comment]
> https://pulpito.ceph.com/rishabh-2023-05-04_11:21:13-fs:mirror-wip-yuri2-testing-2023-04-26-1247-pacific-distro-default-smithi/

Fails with: update_attrs() got an unexpected keyword argument 'createfs'

**Comment by rishabh-d-dave** [comment]
> > https://pulpito.ceph.com/rishabh-2023-05-04_11:21:13-fs:mirror-wip-yuri2-testing-2023-04-26-1247-pacific-distro-default-smithi/
> 
> Fails with: update_attrs() got an unexpected keyword argument 'createfs'

Yes, I'm on it.

**Comment by rishabh-d-dave** [comment]
https://pulpito.ceph.com/rishabh-2023-05-04_13:22:10-fs:mirror-wip-yuri2-testing-2023-04-26-1247-pacific-distro-default-smithi/

**Comment by vshankar** [comment]
jenkins test api

**Comment by rishabh-d-dave** [comment]
Job failed but test passed - https://pulpito.ceph.com/rishabh-2023-05-05_09:32:57-fs:functional-wip-yuri2-testing-2023-04-26-1247-pacific-distro-default-smithi/

```
2023-05-05T10:11:44.745 INFO:tasks.cephfs_test_runner:test_query_mds_filter (tasks.cephfs.test_mds_metrics.TestMDSMetrics) ... ok
2023-05-05T10:11:44.746 INFO:tasks.cephfs_test_runner:
2023-05-05T10:11:44.746 INFO:tasks.cephfs_test_runner:----------------------------------------------------------------------
2023-05-05T10:11:44.746 INFO:tasks.cephfs_test_runner:Ran 16 tests in 1031.487s
2023-05-05T10:11:44.746 INFO:tasks.cephfs_test_runner:
2023-05-05T10:11:44.746 INFO:tasks.cephfs_test_runner:OK
```

**Comment by rishabh-d-dave** [comment]
https://pulpito.ceph.com/rishabh-2023-05-05_10:20:30-fs:functional-wip-yuri2-testing-2023-04-26-1247-pacific-distro-default-smithi/

**Review by vshankar — APPROVED** [review]

**Comment by rishabh-d-dave** [comment]
Failure was not related - https://jenkins.ceph.com/job/ceph-api/54825/

**Pull request merged**
