### PR TITLE
quincy: src/common/options: Correct typo in rgw.yaml.in

### PR DESCRIPTION
**Pull request by zdover23**
Signed-off-by: Anthony D'Atri <anthonyeleven@users.noreply.github.com>
(cherry picked from commit 1796022aa4778226c2d7e04c1cb989ab9d025272)

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [x] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [x] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Review by anthonyeleven — APPROVED** [review]

**Comment by anthonyeleven** [comment]
jenkins retest this please

**Comment by anthonyeleven** [comment]
jenkins retest this please

**Comment by anthonyeleven** [comment]
jenkins test make check

**Comment by anthonyeleven** [comment]
jenkins retest this please

**Comment by anthonyeleven** [comment]
I haven't seen Jenkins act on smaller-granularity retests in quite a while :-/

**Comment by anthonyeleven** [comment]
Jenkins retest this please

**Comment by anthonyeleven** [comment]
Jenkins retest this please

**Comment by zdover23** [comment]
jenkins retest this please

**Comment by anthonyeleven** [comment]
passing really is random isn't it?

**Comment by anthonyeleven** [comment]
jenkins retest this please

**Comment by zdover23** [comment]
> passing really is random isn't it?

It's a post-David-Galloway era for Ceph. I don't think it's anyone's full-time job anymore to keep the CI infrastructure in ship shape. I'll post this to Slack to see if it is indeed random.

**Comment by zdover23** [comment]
If these tests fail again, leave them so that I can comb through the error messages. I'm going to eat lunch now, but I'll check on this in a couple of hours.

**Comment by anthonyeleven** [comment]
The Reef backport eventually passed, so it seems random to me.

**Comment by anthonyeleven** [comment]
feh

**Comment by anthonyeleven** [comment]
jenkins retest this please

**Comment by anthonyeleven** [comment]
jenkins retest this please

**Comment by zdover23** [comment]
jenkins retest this please

**Comment by anthonyeleven** [comment]
jenkins retest this please

**Comment by anthonyeleven** [comment]
jenkins retest this please

**Comment by anthonyeleven** [comment]
jenkins retest this please

**Comment by anthonyeleven** [comment]
jenkins retest this please

**Comment by anthonyeleven** [comment]
The universe clearly does not want this to be backported.

**Comment by anthonyeleven** [comment]
jenkins retest this please

**Comment by zdover23** [comment]
jenkins retest this please

**Comment by anthonyeleven** [comment]
jenkins retest this please

**Comment by anthonyeleven** [comment]
readthedocs failed tho

**Comment by zdover23** [comment]
jenkins retest this please

**Comment by zdover23** [comment]
> readthedocs failed tho

We're waiting on https://github.com/ceph/ceph/pull/55593 to be merged before this PR will pass.

**Comment by ljflores** [comment]
jenkins test make check

**Comment by ljflores** [comment]
jenkins render docs

**Comment by ljflores** [comment]
jenkins test make check

**Pull request merged**
