### PR TITLE
doc: add Python 2 to Ubuntu 18.04 installations

### PR DESCRIPTION
**Pull request by zdover23**
This commit updates the "Create a Cluster" section of the
"Storage Cluster Quick Start" document. Ubuntu 18.04 does
not have Python 2 installed by default. This commit instructs
users of Python 18.04 to install the package "python-minimal"
to provide Python 2 prior to running "ceph-deploy".

This commit fixes Bug number 9 in the list here:
https://pad.ceph.com/p/Report_Documentation_Bugs

Signed-off-by: Zac Dover <zac.dover@gmail.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by liewegas** [comment]
retest this please

**Comment by zdover23** [comment]
Can I do something from my end to initiate another test?

**Comment by liewegas** [comment]
the magic incantation is ``retest this please`` but i'm not sure which jenkins whitelist you need to be on to do it

**Comment by zdover23** [comment]
retest this please

**Comment by zdover23** [comment]
You could add me to all of them and then I could swear upon the altar of God not to abuse my power, but I think that I just managed to re-initiate the battery of tests with whatever powers you have already bestowed upon me.

**Comment by zdover23** [comment]
...or maybe you did it.

**Pull request merged**
