### PR TITLE
client: use non-static dirent for thread-safety

### PR DESCRIPTION
**Pull request by batrick**
Fixes: https://tracker.ceph.com/issues/46832
Signed-off-by: Patrick Donnelly <pdonnell@redhat.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by batrick** [comment]
https://pulpito.ceph.com/pdonnell-2020-08-06_22:30:35-fs-wip-pdonnell-testing-20200806.211150-distro-basic-smithi/

No Traceback but this bug has resisted my attempts to reproduce in master:

https://pulpito.ceph.com/pdonnell-2020-08-07_00:28:25-fs-master-distro-basic-smithi/
https://pulpito.ceph.com/pdonnell-2020-08-07_02:23:20-fs-master-distro-basic-smithi/

so it's hard to verify...

**Comment by vshankar** [comment]
@batrick async threads in mgr/volumes do not perform concurrent readdirs since its guarded by a lock: https://github.com/ceph/ceph/blob/master/src/pybind/mgr/volumes/fs/async_job.py#L35

 However, a readdir (of trash directory) and a rename (to a trash directory) can happen concurrently.

**Comment by batrick** [comment]
> @batrick async threads in mgr/volumes do not perform concurrent readdirs since its guarded by a lock: https://github.com/ceph/ceph/blob/master/src/pybind/mgr/volumes/fs/async_job.py#L35

Two purge threads running `rmtree`s can't readdir at the same time?

> However, a readdir (of trash directory) and a rename (to a trash directory) can happen concurrently.

That also appears to be going on in the logs I've gone through.

**Comment by vshankar** [comment]
> > @batrick async threads in mgr/volumes do not perform concurrent readdirs since its guarded by a lock: https://github.com/ceph/ceph/blob/master/src/pybind/mgr/volumes/fs/async_job.py#L35
> 
> Two purge threads running `rmtree`s can't readdir at the same time?

Ah right! I was stuck in backtrace that was fetching entries from trash dir which is not concurrent. rmtree can run concurrently -- so this looks like the right fix.

> 
> > However, a readdir (of trash directory) and a rename (to a trash directory) can happen concurrently.
> 
> That also appears to be going on in the logs I've gone through.

Excellent catch!

**Comment by batrick** [comment]
Actually, the failures are there in master it's just not obvious with a Traceback grep:

````
$ zgrep '_deleting/[^a-f0-9]'  $(find /a/pdonnell-2020-08-07_00:28:25-fs-master-distro-basic-smithi/ /a/pdonnell-2020-08-07_02:23:20-fs-master-distro-basic-smithi/ -name \*mgr\*)
/a/pdonnell-2020-08-07_00:28:25-fs-master-distro-basic-smithi/5294274/remote/smithi198/log/ceph-mgr.x.log.gz:2020-08-07T01:20:11.761+0000 7f33a9466700  0 [volumes DEBUG volumes.fs.operations.trash] rmtree b'/volumes/_deleting/.\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
/a/pdonnell-2020-08-07_00:28:25-fs-master-distro-basic-smithi/5294274/remote/smithi198/log/ceph-mgr.x.log.gz:2020-08-07T01:20:11.761+0000 7f33a9466700  0 [volumes DEBUG volumes.fs.operations.trash] rmtree b'/volumes/_deleting/.\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00/ba56f502-664a-4206-b1c1-064e03133d6e'
/a/pdonnell-2020-08-07_00:28:25-fs-master-distro-basic-smithi/5294274/remote/smithi198/log/ceph-mgr.x.log.gz:2020-08-07T01:20:11.762+0000 7f33a9466700  0 [volumes DEBUG volumes.fs.operations.trash] rmtree b'/volumes/_deleting/.\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00/ba56f502-664a-4206-b1c1-064e03133d6e/ba56f502-664a-4206-b1c1-064e03133d6e'
/a/pdonnell-2020-08-07_00:28:25-fs-master-distro-basic-smithi/5294274/remote/smithi198/log/ceph-mgr.x.log.gz:2020-08-07T01:20:11.762+0000 7f33a9466700  0 [volumes DEBUG volumes.fs.operations.trash] rmtree b'/volumes/_deleting/.\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00/ba56f502-664a-4206-b1c1-064e03133d6e/ba56f502-664a-4206-b1c1-064e03133d6e/ba56f502-664a-4206-b1c1-064e03133d6e'
/a/pdonnell-2020-08-07_00:28:25-fs-master-distro-basic-smithi/5294274/remote/smithi198/log/ceph-mgr.x.log.gz:2020-08-07T01:20:11.762+0000 7f33a9466700  0 [volumes DEBUG volumes.fs.operations.trash] rmtree b'/volumes/_deleting/.\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00/ba56f502-664a-4206-b1c1-064e03133d6e/ba56f502-664a-4206-b1c1-064e03133d6e/ba56f502-664a-4206-b1c1-064e03133d6e/ba56f502-664a-4206-b1c1-064e03133d6e'
/a/pdonnell-2020-08-07_02:23:20-fs-master-distro-basic-smithi/5294513/remote/smithi151/log/ceph-mgr.y.log.gz:2020-08-07T02:53:07.478+0000 7fab3bfaf700  0 [volumes DEBUG volumes.fs.operations.trash] rmtree b'/volumes/_deleting/s'
/a/pdonnell-2020-08-07_02:23:20-fs-master-distro-basic-smithi/5294532/remote/smithi204/log/ceph-mgr.y.log.gz:2020-08-07T02:58:15.646+0000 7f6150394700  0 [volumes DEBUG volumes.fs.operations.trash] rmtree b'/volumes/_deleting/subvolume_file.0'
````

You can see the `d_name` overwrites by other threads.

**Comment by ajarr** [comment]
> Actually, the failures are there in master it's just not obvious with a Traceback grep:
> 
> ```
> $ zgrep '_deleting/[^a-f0-9]'  $(find /a/pdonnell-2020-08-07_00:28:25-fs-master-distro-basic-smithi/ /a/pdonnell-2020-08-07_02:23:20-fs-master-distro-basic-smithi/ -name \*mgr\*)
> /a/pdonnell-2020-08-07_00:28:25-fs-master-distro-basic-smithi/5294274/remote/smithi198/log/ceph-mgr.x.log.gz:2020-08-07T01:20:11.761+0000 7f33a9466700  0 [volumes DEBUG volumes.fs.operations.trash] rmtree b'/volumes/_deleting/.\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
> /a/pdonnell-2020-08-07_00:28:25-fs-master-distro-basic-smithi/5294274/remote/smithi198/log/ceph-mgr.x.log.gz:2020-08-07T01:20:11.761+0000 7f33a9466700  0 [volumes DEBUG volumes.fs.operations.trash] rmtree b'/volumes/_deleting/.\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00/ba56f502-664a-4206-b1c1-064e03133d6e'
> /a/pdonnell-2020-08-07_00:28:25-fs-master-distro-basic-smithi/5294274/remote/smithi198/log/ceph-mgr.x.log.gz:2020-08-07T01:20:11.762+0000 7f33a9466700  0 [volumes DEBUG volumes.fs.operations.trash] rmtree b'/volumes/_deleting/.\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00/ba56f502-664a-4206-b1c1-064e03133d6e/ba56f502-664a-4206-b1c1-064e03133d6e'
> /a/pdonnell-2020-08-07_00:28:25-fs-master-distro-basic-smithi/5294274/remote/smithi198/log/ceph-mgr.x.log.gz:2020-08-07T01:20:11.762+0000 7f33a9466700  0 [volumes DEBUG volumes.fs.operations.trash] rmtree b'/volumes/_deleting/.\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00/ba56f502-664a-4206-b1c1-064e03133d6e/ba56f502-664a-4206-b1c1-064e03133d6e/ba56f502-664a-4206-b1c1-064e03133d6e'
> /a/pdonnell-2020-08-07_00:28:25-fs-master-distro-basic-smithi/5294274/remote/smithi198/log/ceph-mgr.x.log.gz:2020-08-07T01:20:11.762+0000 7f33a9466700  0 [volumes DEBUG volumes.fs.operations.trash] rmtree b'/volumes/_deleting/.\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00/ba56f502-664a-4206-b1c1-064e03133d6e/ba56f502-664a-4206-b1c1-064e03133d6e/ba56f502-664a-4206-b1c1-064e03133d6e/ba56f502-664a-4206-b1c1-064e03133d6e'
> /a/pdonnell-2020-08-07_02:23:20-fs-master-distro-basic-smithi/5294513/remote/smithi151/log/ceph-mgr.y.log.gz:2020-08-07T02:53:07.478+0000 7fab3bfaf700  0 [volumes DEBUG volumes.fs.operations.trash] rmtree b'/volumes/_deleting/s'
> /a/pdonnell-2020-08-07_02:23:20-fs-master-distro-basic-smithi/5294532/remote/smithi204/log/ceph-mgr.y.log.gz:2020-08-07T02:58:15.646+0000 7f6150394700  0 [volumes DEBUG volumes.fs.operations.trash] rmtree b'/volumes/_deleting/subvolume_file.0'
> ```
> 
> You can see the `d_name` overwrites by other threads.

Great catch and fix!

**Pull request merged**
