### PR TITLE
[DNM] cls_fifo: fifo over RADOS

### PR DESCRIPTION
**Pull request by yehudasa**
This is an implementation of fifo queue over rados. Data is appended to rados object until it's full. At that point data will be written to a new object. Data is read from the tail sequentially (can be iterated using marker). Data can be trimmed (up to and including marker).

Queue has a header object (meta), and zero or more data objects (parts).

The software has two layers: the higher level client operations side that deals with the application apis, and manages the meta and parts, and there’s the objclass level that deals with the rados layout of meta and part objects. There are different objclass methods that deal with reading and modifying each of these entities.

A single part has max possible size, however, it may become full once a certain smaller size is reached (full_size_threshold). It is imperative that once a part has reached its capacity, it will not allow any more writes into it. For this reason, it is important that data being written to the queue does not exceed max_entry_size . This is enforced, by the higher level client api.

Written entries go to the current head object, and when it’s full, a new head part is created. When listing entries, data is iterated from tail to the current head. Trim can either change the pointer within the current tail object, and if needed it removes tail objects.

A unitest has been created to test functionality.

TODO:
 - async api
 - adapt code to new rados writes return value capabilities
 - parallel push test (currently only tests sequential writes from multiple clients)

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`

</details>

### CODE REVIEW

**Comment by mattbenjamin** [comment]
not sure what it should be, but would be useful if code provided a clear hint that this fifo is distributed, e.g., as cls_queue is not

**Comment by adamemerson** [comment]
Maybe squash some of these together to make it more reviewable. Especially the later commits that change decisions made in earlier commits.

**Comment by mattbenjamin** [comment]
be not stale

**Comment by ivancich** [comment]
This seems to be superceded by https://github.com/ceph/ceph/pull/34335 .

**Comment by cbodley** [comment]
this merged in https://github.com/ceph/ceph/pull/35548

thanks @yehudasa!

**Pull request closed without merging**
