### PR TITLE
erasure-code, test, pybind: various arm32 related cleanups.

### PR DESCRIPTION
**Pull request by tchaikov**
## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by tchaikov** [comment]
cc @vbashkirtsev

**Comment by tchaikov** [comment]
jenkins test make check

**Review by jdurgin — APPROVED** [review]
nice cleanups, the 1 day ceph cli timeout should be fine

**Comment by tchaikov** [comment]
- https://pulpito.ceph.com/kchai-2020-12-23_05:37:18-rados-wip-kefu-testing-2020-12-23-1139-distro-basic-smithi/
- https://pulpito.ceph.com/kchai-2020-12-24_04:12:19-rados-wip-kefu-testing-2020-12-23-1139-distro-basic-smithi/

failures tracked by

- https://tracker.ceph.com/issues/48323
- https://tracker.ceph.com/issues/48712

**Pull request merged**
