### PR TITLE
rgw/dbstore: Fix build errors on centos9

### PR DESCRIPTION
**Pull request by soumyakoduri**
Fix build errors on CentOS Stream 9.

Fixes: https://tracker.ceph.com/issues/55454#change-215260
Signed-off-by: Soumya Koduri <skoduri@redhat.com>

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Review by dang — APPROVED** [review]

**Comment by ktdreyer** [comment]
Do we need this in `quincy`? The tracker ticket is not currently marked for backporting.

**Comment by cbodley** [comment]
@ktdreyer tagged for quincy backport, thanks

**Review by bigjust — APPROVED** [review]
fix verified in: https://jenkins.ceph.com/job/ceph-dev-build/ARCH=x86_64,AVAILABLE_ARCH=x86_64,AVAILABLE_DIST=centos9,DIST=centos9,MACHINE_SIZE=gigantic/49480/

**Comment by cbodley** [comment]
jenkins test api

**Comment by ktdreyer** [comment]
Is this ready to merge? It seems v17.2.1 does not build on CentOS 9 without this.

**Comment by cbodley** [comment]
> Is this ready to merge? It seems v17.2.1 does not build on CentOS 9 without this.

yeah, let's merge once checks pass

**Pull request merged**
