### PR TITLE
luminous: Scrub considers dirty backtraces to be damaged, puts in damage table even though it repairs

### PR DESCRIPTION
**Pull request by shinobu-x**
http://tracker.ceph.com/issues/22089

### CODE REVIEW

**Comment by yuriw** [comment]
[wip-yuri3-testing-2018-01-29-1703-luminous](https://trello.com/c/Ti9d35jC/247-wip-yuri3-testing-2018-01-29-1703-luminous)

**Comment by yuriw** [comment]
add tag "luminous-batch-1" when done pls

**Comment by theanalyst** [comment]
redid with -x

**Comment by yuriw** [comment]
[wip-yuri-testing-2018-01-31-2202-luminous](https://trello.com/c/W5H3D6j7/253-wip-yuri-testing-2018-01-31-2202-luminous)

**Comment by batrick** [comment]
I have a suspicion the dead jobs in

http://pulpito.ceph.com/yuriw-2018-01-31_23:48:28-fs-wip-yuri-testing-2018-01-31-2202-luminous-testing-basic-smithi/

are possibly caused or not fixed by this. I need to investigate more.

**Comment by yuriw** [comment]
[wip-yuri-testing-2018-02-04-1734-luminous](https://trello.com/c/SeYBrPx3/255-wip-yuri-testing-2018-02-04-1734-luminous)

**Comment by yuriw** [comment]
[wip-yuri3-testing-2018-02-05-2032-luminous](https://trello.com/c/j0BpLYdX/257-wip-yuri3-testing-2018-02-05-2032-luminous)

**Comment by yuriw** [comment]
@shinobu-x pls add tag luminous-batch-1 when done

**Comment by batrick** [comment]
https://github.com/ceph/ceph/pull/20341

**Pull request closed without merging**
