### PR TITLE
doc/radosgw: Improve language and formatting in config-ref.rst

### PR DESCRIPTION
**Pull request by bluikko**
The "Topic persistency settings" section includes convoluted and incomplete sentences so attempt to improve the language. The section lacks context so add a link to the relevant documentation about Notifications.  
**note:** I am not sure if this should link to `PubSub Sync Module` or to `Bucket Notifications`!!  
I picked Bucket Notifications but would be interesting to know if that is right.

The "Garbage Collection settings" note includes a sentence that looks incomplete so try to improve the language.

Don't capitalize "Ops" in "RGW Ops" especially when the same sentence talks about "op queue" with lower case "o".

Also improve formatting: indentation of a note and wrap several very long lines.

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [x] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [x] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by bluikko** [comment]
Tomorrow have to look at fixing the link.

**Comment by zdover23** [comment]
I'll take care of it when I get to my computer later today.

**Comment by bluikko** [comment]
Let's see if I got this linking right, following the "legacy bottom of the document" style...

**Review by zdover23 — APPROVED** [review]

**Comment by zdover23** [comment]
https://github.com/ceph/ceph/pull/52835 - Reef backport
https://github.com/ceph/ceph/pull/52836 - Quincy backport

**Pull request merged**
