### PR TITLE
ceph-volume: support /dev/dm-X paths for LVM LVs

### PR DESCRIPTION
**Pull request by dseomn**
LVM doesn't appear to provide a field that matches the /dev/dm-X path
itself. I initially tried matching on lv_kernel_major and
lv_kernel_minor, but those don't appear to be available with the
--readonly flag to lvs.

Manually tested with /dev/vg_name/lv_name, vg_name/lv_name,
/dev/mapper/vg_name-lv_name, /dev/dm-X,
/dev/disk/by-id/dm-name-vg_name-lv_name, and a path that doesn't exist.
I did not test on a system where /dev/mapper doesn't exist, but
os.scandir('/nonexistent') raised FileNotFoundError.

Fixes: https://tracker.ceph.com/issues/49582
Signed-off-by: David Mandelberg <dseomn@google.com>

## Checklist
- [x] References tracker ticket
- [ ] Updates documentation if necessary: I don't think it's necessary, since it's a bug fix, and using /dev/dm-X paths is probably pretty rare?
- [ ] Includes tests for new functionality or reproducer for bug: I didn't see any tests for the existing code, and I'm not sure how to test this without the ability to influence LVM in the kernel.

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by tchaikov** [comment]
jenkins test api

**Comment by tchaikov** [comment]
jenkins test docs

**Comment by dseomn** [comment]
Hi,

Is there anything I need to do to move this along? This is blocking the ability to use an encrypted OSD on part of a device in Rook: https://github.com/rook/rook/discussions/7602

**Comment by tchaikov** [comment]
@guits hi Guillaume, could you kindly take a look?

**Comment by dseomn** [comment]
@guits Do you think you'll have time to look at this at some point?

**Comment by guits** [comment]
jenkins test ceph-volume all

**Comment by guits** [comment]
jenkins test ceph-volume tox

**Review by guits — APPROVED** [review]

**Comment by guits** [comment]
jenkins test ceph-volume lvm centos8-filestore-dmcrypt

**Comment by guits** [comment]
jenkins test ceph-volume batch centos8-bluestore-mixed_type_dmcrypt_explicit

**Comment by guits** [comment]
jenkins test ceph-volume batch centos8-bluestore-mixed_type_explicit

**Comment by guits** [comment]
jenkins test ceph-volume batch centos8-bluestore-single_type_dmcrypt

**Comment by dseomn** [comment]
Thanks for taking a look! From a glance, the test failures look unrelated, I think. I'll try retrying them. If that doesn't work, I'll try rebasing this to the latest `master`.

jenkins test ceph-volume batch centos8-bluestore-mixed_type_explicit
jenkins test ceph-volume batch centos8-bluestore-single_type_dmcrypt

**Comment by dseomn** [comment]
jenkins test ceph-volume batch centos8-bluestore-mixed_type_explicit

**Comment by dseomn** [comment]
jenkins test ceph-volume batch centos8-bluestore-single_type_dmcrypt

**Comment by dseomn** [comment]
jenkins test ceph-volume batch centos8-bluestore-mixed_type_explicit

**Comment by dseomn** [comment]
jenkins test ceph-volume batch centos8-bluestore-single_type_dmcrypt

**Comment by dseomn** [comment]
jenkins test ceph-volume all

**Comment by dseomn** [comment]
jenkins test ceph-volume tox

**Comment by dseomn** [comment]
@guits I rebased and the errors still look unrelated to me. Am I interpreting them wrong? Are those errors on `master` too?

**Comment by guits** [comment]
jenkins test ceph-volume batch centos8-bluestore-mixed_type

**Comment by guits** [comment]
> @guits I rebased and the errors still look unrelated to me. Am I interpreting them wrong? Are those errors on `master` too?

I don't think those failures are related to your patch

**Comment by dseomn** [comment]
> This pull request can no longer be automatically merged: a rebase is needed and changes have to be manually resolved

I'll rebase if/when other people want to move this forward, but I don't plan to put more effort into this until then.

**Pull request closed without merging**
