### PR TITLE
cmake: fix build WITH_SYSTEM_BOOST=ON

### PR DESCRIPTION
**Pull request by tchaikov**
FindBoost.cmake from upstream cmake now finds python libraries like

find_package(Boost 1.67 python36)

and it export targets like Boost::python36

but we are still linking against Boost::python, so to be compatible
with FindBoost.cmake, we need to update BuildBoost.cmake and
mgr/CMakeLists.txt accordingly. in other words, to export
Boost::python36 and to link Boost::python36.

Signed-off-by: Kefu Chai <kchai@redhat.com>

- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by wjwithagen** [comment]
@tchaikov 
Not sure if this is going to fly with the CMake stuff that is in FreeBSD packages.
I always have this struggle on a Boost upgrade with FreeBSD that CMake is lagging.
And there might be some different opinions on how to handle python 27 versus 36.
So I'll throw this into Jenkins and see what comes of it.

**Comment by tchaikov** [comment]
https://shaman.ceph.com/builds/ceph/wip-kefu-testing-2018-08-10-1333/a840fb77db52e72436a09180408aeef9a4375984/

**Comment by tchaikov** [comment]
@wjwithagen thanks for testing!

**Comment by wjwithagen** [comment]
@tchaikov 
As far as I can tell I need a small bit of this PR backported to mimic:
`mimic : src/CMakeLists.txt:770`
refers to Boost::python, which fails while building on FreeBSD.
Any chance to cherrypick anything, or should I just commit a PR against mimic?

**Comment by tchaikov** [comment]
no, i don't think so. as it does not break the build. i introduced this fix just to enable Ceph to be able to find pre-built `ceph-libboost-*` packages when running `make check` . please follow the instructions at https://github.com/ceph/ceph/pull/26277#issuecomment-460671923 for backporting the changes.

**Comment by wjwithagen** [comment]
@tchaikov 
I'm not quite getting what you mean? 
I would need to have:
`mimic : src/CMakeLists.txt:770` look like:
```
target_link_libraries(ceph-mgr
  osdc client heap_profiler
  osdc client heap_profiler
  global-static ceph-common
  global-static ceph-common
  Boost::python ${MGR_PYTHON_LIBRARIES} ${CMAKE_DL_LIBS})
  Boost::python${MGR_PYTHON_VERSION_MAJOR}${MGR_PYTHON_VERSION_MINOR}
  ${MGR_PYTHON_LIBRARIES} ${CMAKE_DL_LIBS})
```
But I think that cannot be cherrypicked, so it warants a separate PR.
I can still follow @smithfarm's suggestions on how to backport.

**Comment by tchaikov** [comment]
i was trying to answer your question. 

> Any chance to cherrypick anything, 

no, i don't think so. as it does not break the build. i introduced this fix just to enable Ceph to find pre-built `ceph-libboost-*` packages when running `make check` . 

> or should I just commit a PR against mimic?

please follow the instructions at https://github.com/ceph/ceph/pull/26277#issuecomment-460671923 for backporting the changes.

**Comment by wjwithagen** [comment]
Tracker: http://tracker.ceph.com/issues/38213

**Comment by wjwithagen** [comment]
@smithfarm 
backport PR #26300

**Pull request merged**
