### PR TITLE
tests: ceph-disk.sh should compare with the resolved path

### PR DESCRIPTION
**Pull request by tchaikov**
Signed-off-by: Kefu Chai <kchai@redhat.com>

### CODE REVIEW

**Comment by dachary** [comment]
last time I checked, **realpath** is not available by default. Maybe this changed since we do not support older versions

**Comment by tchaikov** [comment]
@dachary yeah, realpath was introduced in coreutils 8.15.

and 
- centos 7 has coreutils 8.22
- ubuntu 14.04 (trusty) has coreutils 8.21
- fedora 21 has coreutils 8.22

and realpath is easier to understand in comparison with `readlink -f`. but if you think otherwise, i am happy to revert to `readlink -f` .

**Comment by dachary** [comment]
@tchaikov the only reason for not using realpath was because it is was not found on all supported platforms. All good :-)

<pre>
Reviewed-by: Loic Dachary &lt;ldachary@redhat.com>
</pre>

**Comment by tchaikov** [comment]
thanks for your review, Loïc! first merge in the new year!

**Comment by dachary** [comment]
@tchaikov happy new lunar year !

**Pull request merged**
