### PR TITLE
rgw: user stats account for resharded buckets

### PR DESCRIPTION
**Pull request by cbodley**
when bucket reshard completes, rgw_link_bucket() passes the new bucket instance id down to cls_user, but cls_user_set_buckets_info() does not change the instance id when it's updating an existing bucket. so when rgw_user_sync_all_stats() looks up each of the user's buckets, it uses the original bucket instance id instead of the resharded one and calculates user stats that may not match the current bucket stats

as a workaround, rgw_user_sync_all_stats() no longer relies on the bucket instance id it gets from rgw_read_user_buckets(), and instead calls get_bucket_info() to look up the current instance in the bucket entrypoint

Fixes: https://tracker.ceph.com/issues/24505

this includes two separate fixes, each of which resolve the issue independently. but the workaround in rgw_user_sync_all_stats() is the only way to handle previously-resharded buckets

### CODE REVIEW

**Comment by theanalyst** [comment]
Looks correct, will verify again in the morning

**Comment by iliul** [comment]
@cbodley Thanks! 

Need backport to luminous branch ? 

and whether this PR is valid for buckets that have been resharding, if not, how to make the statistics of the buckets that already have resharding correct ?

**Comment by cbodley** [comment]
> Need backport to luminous branch ?

definitely, yeah. i added backports tags for luminous/mimic to https://tracker.ceph.com/issues/24505

> and whether this PR is valid for buckets that have been resharding, if not, how to make the statistics of the buckets that already have resharding correct ?

yes, the change to rgw_user_sync_all_stats() is intended to handle the case of buckets that were already resharded

**Comment by cbodley** [comment]
passed http://pulpito.ceph.com/cbodley-2018-10-18_16:12:28-rgw-wip-cbodley-testing-distro-basic-smithi/

**Pull request merged**
