### PR TITLE
msg/async/rdma: Update fix broken compilation

### PR DESCRIPTION
**Pull request by Adirl**
This commit relates to fix broken compilation commit #eb0f62421dd9722055b3a87bfbe129d1325a723f
Assumption: If "out" is NULL then there is no communication and it is
safe to assert.

Signed-off-by: Sarit Zubakov <saritz@mellanox.com>

### CODE REVIEW

**Comment by Adirl** [comment]
@yuyuyu101

**Comment by Adirl** [comment]
@DanielBar-On

**Comment by yuyuyu101** [comment]
@Adirl would you like to apply the same changes to PosixStack.cc?

**Comment by Adirl** [comment]
@yuyuyu101 @saritz 
Yes, we will do add to Posix as well

**Pull request merged**
