### PR TITLE
rgw: add layout generation info to "bucket stats"

### PR DESCRIPTION
**Pull request by ivancich**
Adds a new field to bucket stats. Also rearranges existing information slightly to make more sense. Also removes the redundancy of showing bucket versioning status in two different ways.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [x] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by ivancich** [comment]
jenkins test api

**Comment by mattbenjamin** [comment]
this is a nice improvement

**Comment by cbodley** [comment]
are you trying to locate individual bucket index shard objects in rados based on this index generation?

there's already a `bucket layout` command that dumps the entire layout as json, which gives you a much more complete view of that structure (including index type, reshard status, bilogs for multisite, etc)

**Comment by ivancich** [comment]
Teuthology results -- no regressions:
- https://pulpito.ceph.com/ivancich-2023-11-04_15:10:30-rgw-wip-eric-testing-1-distro-default-smithi/
- https://pulpito.ceph.com/ivancich-2023-11-03_20:37:04-rgw-wip-eric-testing-1-distro-default-smithi/

**Review by cbodley — APPROVED** [review]

**Comment by ivancich** [comment]
> are you trying to locate individual bucket index shard objects in rados based on this index generation?
> 
> there's already a `bucket layout` command that dumps the entire layout as json, which gives you a much more complete view of that structure (including index type, reshard status, bilogs for multisite, etc)

Yeah, this stems from a tool I created to help me investigate restoring lost indices more efficiently. Rather than sequence through an old buggy version and whatnot, my tool figures out the bucket index objects and removes the entries in their omaps. To generate the bucket index objects, I need to know the bucket's id, number of shards, and generation, which with this mod I can get from `bucket stats`.

I hadn't been aware of the `bucket layout` sub-command. I see it can give me number of shards and generation, but not the id.

**Do you object to the `bucket stats` subcommand including the generation?**

I have to admit `bucket stats` is evolved into a misnomer given all the non-stats info it gives about a bucket. I don't know if we should rethink things further.

**Comment by cbodley** [comment]
> I have to admit `bucket stats` is evolved into a misnomer given all the non-stats info it gives about a bucket.

my thoughts exactly :)

> Do you object to the `bucket stats` subcommand including the generation?

nope. i've approved this, as it's consistent with the current usage 👍

**Pull request merged**
