### PR TITLE
mgr/dashboard: chartjs and ng2-charts version upgrade

### PR DESCRIPTION
**Pull request by Pegonzal**
Chartjs version upgrade to 4.4.0
ng2-charts version upgrade to 4.1.1

All graphs within the dashboard were affected in some way or another, but the functionality and appareance should remain the same after the upgrade

Fixes: https://tracker.ceph.com/issues/63924

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Review by nizamial09 — COMMENTED** [review]
Thanks @Pegonzal this is a lot of work here and kudos to you for stepping up and taking care of it.

I see some issues still in some charts.
The tooltips are still not working in the cephfs graphs. (I am hovering over a datapoint btw in the picture)
image

and even though the tooltip is now visible in sparkline charts, the tooltip doesn't show the value.
image

**Comment by Pegonzal** [comment]
> Thanks @Pegonzal this is a lot of work here and kudos to you for stepping up and taking care of it.
> 
> I see some issues still in some charts. The tooltips are still not working in the cephfs graphs. (I am hovering over a datapoint btw in the picture) 
> 
> and even though the tooltip is now visible in sparkline charts, the tooltip doesn't show the value. 

Both things should be fixed now @nizamial09! Thanks for pointing this out

**Comment by nizamial09** [comment]
thanks @Pegonzal overall looks good to me. but in the osds page, we are showing too many datapoints for the read/write bytes. was it like that before or did something changed? 
image

**Comment by Pegonzal** [comment]
> thanks @Pegonzal overall looks good to me. but in the osds page, we are showing too many datapoints for the read/write bytes. was it like that before or did something changed? 

> 
> 

Hey @nizamial09, this has not changed with the update, so it is like this

**Review by nizamial09 — APPROVED** [review]
once the test passes let's merge it!

**Comment by nizamial09** [comment]
jenkins test make check

**Comment by cloudbehl** [comment]
jenkins test make check

**Review by aaSharma14 — APPROVED** [review]

**Pull request merged**
