### PR TITLE
pybind/mgr/balancer: two more fixes

### PR DESCRIPTION
**Pull request by xiexingguo**

### CODE REVIEW

**Comment by xiexingguo** [comment]
@liewegas Yet another balancer-fix against **ZeroDivisionError**

**Comment by tchaikov** [comment]
http://pulpito.ceph.com/kchai-2018-03-09_06:49:31-rados-wip-kefu-testing-2018-03-09-1307-distro-basic-mira/

**Comment by xiexingguo** [comment]
@tchaikov Thanks!

**Comment by tchaikov** [comment]
@xiexingguo i guess your fixes for balancer also apply to luminous. do you think it's worthwhile to backport them?

**Comment by xiexingguo** [comment]
> @xiexingguo i guess your fixes for balancer also apply to luminous. do you think it's worthwhile to backport them?

@tchaikov I did backport them. See https://github.com/ceph/ceph/pull/20359 (because these new fixes relies on that PR too) :joy:

**Pull request merged**
