### PR TITLE
jewel: rbd-mirror: improve split-brain detection logic

### PR DESCRIPTION
**Pull request by dillaman**
http://tracker.ceph.com/issues/17065

### CODE REVIEW

**Comment by dachary** [comment]
jenkins test this please (the logs are gone)

**Comment by dachary** [comment]
@dillaman could you please shortly explain in the commit message of eb21a9d why it happened and why it had to be resolved via a new commit instead of cherry-picking an existing one ?

**Comment by dillaman** [comment]
@dachary updated the commit message

**Comment by dachary** [comment]
@dillaman closing because it is now part of https://github.com/ceph/ceph/pull/11433

**Pull request closed without merging**
