### PR TITLE
cmake: add WITH_ROCKSDB_WAL_COMPRESSION option for rocksdb wal compre…

### PR DESCRIPTION
**Pull request by yanghonggang**
…ssion

- switch rocksdb to 7.X.Y
- ./do_cmake.sh -DWITH_MGR_DASHBOARD_FRONTEND=OFF -DCMAKE_BUILD_TYPE=RelWithDebInfo -DWITH_ROCKSDB_WAL_COMPRESSION=ON
- CEPH_NUM_MON=1 CEPH_NUM_OSD=1 CEPH_NUM_MDS=0 CEPH_NUM_MGR=1  CEPH_NUM_RGW=0 ../src/vstart.sh  -X -l -b --without-dashboard -n -o bluestore_rocksdb_options_annex="wal_compression=kZSTD"

check if wal compression is enabled:

grep "Options.wal_compression" out/osd.0.log
2022-11-21T19:06:43.160+0800 7f25cb856700  4 rocksdb:             Options.wal_compression: 7

Signed-off-by: Yang Honggang <yanghonggang_yewu@cmss.chinamobile.com>
Signed-off-by: Wang Xu <wangxu_yewu@cmss.chinamobile.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [x] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by markhpc** [comment]
@yanghonggang thank you for the PR!  Do you have any test results or other benefits you are seeing with this PR?  I think we need to be careful here because compression may not be universally beneficial.

**Comment by yanghonggang** [comment]
# test summary
* for 4k case, wal compression can bring significant performance improvement
* for 4m case, wal compression has no significant difference

| case                                   |  rados bench BW(MB/s) |  hdd avg util
|---                                       | ---                                    |--- 
| 4K  wal compression on   | 6.59365                           | 94.44%
| 4K wal compression off    | 12.136                              | 81.96% 
| 4M  wal compression on   | 94.0137                           | 99.27%
| 4M  wal compression off  | 93.994                             | 99.47%

# vstart

* sds is HDD

```text
MON=1 OSD=1 MGR=1 RGW=0 MDS=0 ../src/vstart.sh -n -X -o "bluestore_block_db_path=\"\"" -o "bluestore_block_db_size=0" -o "bluestore_block_wal_path=\"\"" -o "bluestore_block_wal_size=0" -o "bluestore_block_path=/dev/sds" -o bluestore_rocksdb_options_annex="wal_compression=kZSTD" -b
```

```text
ceph osd set noscrub
ceph osd set nodeep-scrub
ceph osd pool create test-pool 256 256
ceph osd pool set test-pool pg_autoscale_mode off
ceph daemon mon.a config set  mon_allow_pool_size_one true
```

# 4K

```text
rados write -b 4K  -t 22 3600
```

rados bench

图片

hdd util

图片


# 4M

```text
rados write -b 4M  -t 4 3600
```

rados bench

图片

hdd util

图片

**Comment by ifed01** [comment]
@yanghonggang 
<html>
<body>


4K wal compression on | 6.59365 | 94.44%
-- | -- | --
4K wal compression off | 12.136 | 81.96%


</body>
</html>

Is BW for WAL compression On mode correct? 

</body>
</html>

**Comment by ifed01** [comment]
@yanghonggang - it would be interesting to see CPU utilization during this benchmarks too..
@markhpc - generally it looks like a really good idea to enable WAL (and SST?) compression for slow disks (hdd and apparently low-end SATA SSDs). Hence we are to compensate slow disk performance with higher CPU utilization.

Whether compression makes sense for high-end NVMe drives - it worth some additional research and this apparently  depends on OSD H/W setup...

**Comment by yanghonggang** [comment]
> Is BW for WAL compression On mode correct?

sorry my mistake. the table is correct now.
and I will add avg cpu usage later.

**Comment by ifed01** [comment]
also I'm curious how compressible are the writes that 'rados bench' invokes. I presume it uses all-zero blocks which are evidently highly compressible... Having less compressible blocks might be a more valid scenario. Not sure if 'rados bench' allows to adjust that so you might want to use fio tool or something...

**Comment by markhpc** [comment]
@ifed01 @yanghonggang I agree with Igor regarding rados bench writes.  I haven't looked at the code in a little while but I suspect it's not using random data.  Agreed that we should probably test with fio as well.  Having said that, I bet for HDD it might still be a good idea when the data is semi-compressible.  For NVMe I suspect we might want to avoid it (a lot of our performance optimizations so far have revolved around reducing CPU consumption in the kv sync thread).   We may need separate defaults.

**Pull request closed without merging**
