### PR TITLE
ceph-disk: Populate mount options when running "list"

### PR DESCRIPTION
**Pull request by badone**
Also tidy up by moving duplicated code into a function

Fixes: http://tracker.ceph.com/issues/17331
Signed-off-by: Brad Hubbard <bhubbard@redhat.com>

### CODE REVIEW

**Comment by yuriw** [comment]
http://pulpito.front.sepia.ceph.com:80/yuriw-2017-04-04_19:50:05-rados-wip-yuri-testing2_2016_4_5-distro-basic-smithi/

http://pulpito.ceph.com/yuriw-2017-04-04_22:43:09-rados-wip-yuri-testing2_2016_4_5---basic-smithi/

**Comment by badone** [comment]
@dachary mind taking a look mate?

**Comment by yuriw** [comment]
@badone this one can be merged

**Comment by dachary** [comment]
@badone nicely done :-) It needs a run of the ceph-disk suite and then it's all good.

**Comment by dachary** [comment]
@yuriw would you do the honor ?

**Comment by yuriw** [comment]
@badone @dachary running tests http://pulpito.front.sepia.ceph.com:80/yuriw-2017-04-05_22:45:26-ceph-disk-wip-yuri-testing2_2016_4_5-distro-basic-vps/

**Pull request merged**
