### PR TITLE
doc: Fix typo in mount.fuse.ceph

### PR DESCRIPTION
**Pull request by joscollin**
Signed-off-by: Jos Collin <jcollin@redhat.com>

### CODE REVIEW

**Comment by batrick** [comment]
jenkins render docs

**Comment by batrick** [comment]
@joscollin Can you explain the formatting problem? It looks fine e.g. here:

http://docs.ceph.com/ceph-prs/19212/man/8/mount.fuse.ceph/

vs. your change:

http://docs.ceph.com/ceph-prs/19215/man/8/mount.fuse.ceph/

**Comment by joscollin** [comment]
@batrick ` ‘ceph.’ ` under `Description` is the only change in this PR. 

The formatting issues I communicated via IRC are already fixed in https://github.com/ceph/ceph/pull/19172 before it was merged.

There were many. One of them was: there was no table (box) under `Description` and `Additional Info`. It was just text without a new line.

Like:
```
DEVICE PATH TYPE OPTIONS id=admin /mnt/ceph fuse.ceph defaults 0 0
```

**Comment by batrick** [comment]
Jos, I'm looking at this rendering:

http://docs.ceph.com/ceph-prs/19215/man/8/mount.fuse.ceph/

The change you're making doesn't look right to me.

**Comment by joscollin** [comment]
@batrick 

I was comparing 

http://docs.ceph.com/docs/master/man/8/mount.fuse.ceph/
and 
http://docs.ceph.com/ceph-prs/19215/man/8/mount.fuse.ceph/

I think http://docs.ceph.com/ceph-prs/19215/man/8/mount.fuse.ceph/ is more readable. Please see `ceph.` prefix.

**Comment by batrick** [comment]
I think the way it looks now is readable. You can wrap the
````
``ceph.``
````

in quotes if you want to distinguish it more but I like the monospace treatment of the text.

**Comment by joscollin** [comment]
jenkins render docs

**Comment by joscollin** [comment]
@batrick Looks ok now. Please check. Thanks.

**Pull request merged**
