### PR TITLE
rbd-nbd: network block device (NBD) support for RBD 

### PR DESCRIPTION
**Pull request by wwformat**
This is rbd client in userspace (refer to rbd-nbd), as an alternative to kernel rbd client
(refer to rbd-ker). The motivation are as follows,
(1) The developement of rbd-ker is behind that of userspace librbd;
(2) The flexibility and portability (dependent on kernel version) of rbd-ker are not very good;
(3) More importantly, according to our experience on ARM64 architecture for container scenario,
there exists stability issue for rbd-ker, easily cause kernel hang or disk-utils 100%;
(4) Rely on powerful librbd, rbd-nbd enjoys extremely simple code, and easy to maintain and
make stable, and will not cause system unusable even if crashed (which we do not meet in our
test);
(5) According to our test, the performance of rbd-nbd is comparable to rbd-ker;
(6) For the container sinaro, rbd-nbd is very practical.
The usage of rbd-nbd is very simple, rbd-nbd map/unmap/list-mapped, the other functions still
leave rbd to do.

### CODE REVIEW

**Comment by wwformat** [comment]
I have try to rebase and repush multi times, and the jenkin failure with different problem.
Anyone knows how to fix it or some advise?

**Comment by dillaman** [comment]
@wwformat Try running ```make check``` locally -- it appears a test timed out.

**Comment by wwformat** [comment]
@dillaman @dachary 
>@wwformat Try running make check locally -- it appears a test timed out.

I already run './run-make-check.sh' locally, and the result seems OK like this 'make check: successful run on cc03f678cce43df1083cd0cce3aa6b70feea90a4'
Maybe the jenkins failure is false negative report?

**Comment by dachary** [comment]
@wwformat you can verify if it's a false negative by rebasing and repushing, this will trigger another run. It is possible that something in your environment is making the test pass. You could try to run-make-check.sh on a fresh virtual machine to verify it is not the case. If you have docker installed, you can also create a docker container from the ceph/src directory with:
<pre>
test/docker-test.sh --os-type centos --os-version 7 --shell
</pre>
this will give you a container and a separate source directory at the same commit your working tree is in. When you have the shell, you can ./run-make-check.sh (that's actually what the bot does). Warning: this will use ~10GB of additional disk space.

**Comment by wwformat** [comment]
OK, the failure report seems a false negative. :)

**Comment by dragonylffly** [comment]
@dillaman @jdurgin  It has passed the tests, please review

**Comment by dragonylffly** [comment]
@dillaman serveral days ago, we received notification from Github saying that our KylinStorage team has been deleted for unknown reason, we recreated it, unfortunately found that we can not use 'push -f' to update the commits under the original PR, therefore we had to start a new pull request, sorry for the inconvenience

**Comment by wwformat** [comment]
@dillaman thanks for your review.
I update the code by your comments.

**Pull request merged**
