### PR TITLE
mon: include num pgs in 'osd df' output

### PR DESCRIPTION
**Pull request by stiopaa1**
http://tracker.ceph.com/issues/11882

### CODE REVIEW

**Comment by liewegas** [comment]
The pg_by_osd was broken.. please review https://github.com/ceph/ceph/pull/4914 and rebase on top of that?

**Comment by liewegas** [comment]
size_t seems okay to me!

**Comment by dragonylffly** [comment]
I see from the definition of struct pg_pool_t, there is a field __u32 pg_num;    ///< number of pgs, so I think maybe it is better to keep consistent, while size_t may has different lengths on different architectures, anyway, it is up to @liewegas's decision :)

**Comment by stiopaa1** [comment]
@liewegas 
I'm off for holidays tomorrow, so I don't have time to look at your change, but with 3 pools, each with 8  placement groups and 3 replicas it returns:
```
ID WEIGHT  REWEIGHT SIZE   USE    AVAIL  %USE  VAR  PGs 
 0 1.00000  1.00000 96536M 55106M 36503M 57.08 1.00   7 
 1 1.00000  1.00000 96536M 55106M 36503M 57.08 1.00   7 
 2 1.00000  1.00000 96536M 55106M 36503M 57.08 1.00   7 
              TOTAL   282G   161G   106G 57.08          
```
Wouldn't we expect 24 PGs on each OSD?

**Comment by liewegas** [comment]
I've pushed an additional fix to my branch that should clear it up!

**Comment by liewegas** [comment]
@stiopaa1 Okay, the pg_by_osd code is fixed now in master.  Can you rebase?  This should let you drop the pg count calculations and just use the accessor. Thanks!

**Comment by stiopaa1** [comment]
@liewegas 
I have rebased

**Comment by liewegas** [comment]
merged manually (with the s/PGs/PGS/ nit fixed).  thanks!

**Pull request closed without merging**
