### PR TITLE
tests: rados: move cephtool.yaml to new singleton/bluestore subsuite

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/19797

### CODE REVIEW

**Comment by liewegas** [comment]
that works!

**Comment by smithfarm** [comment]
`teuthology-suite --priority 101 --suite rados --machine-type smithi --email ncutler@suse.com --ceph wip-19797 --filter="rados/singleton/{all/cephtool.yaml msgr-failures/few.yaml msgr/simple.yaml objectstore/filestore-btrfs.yaml rados.yaml}"`

**waiting for build**

**Comment by smithfarm** [comment]
Oddly, this patch doesn't make the error go away.

**Comment by smithfarm** [comment]
This is a different problem than I thought. The `rados/singleton` suite runs a matrix of objectstores: `bluestore-comp.yaml  bluestore.yaml  filestore-btrfs.yaml  filestore-xfs.yaml` - in this case, the "osd objectstore: bluestore" override introduced in cephtool.yaml was overridden by the "osd objectstore: filestore" in filestore-btrfs.yaml.

Looks to me like the cephtool.yaml needs to be split out into a bluestore-only subsuite.

**Comment by smithfarm** [comment]
`teuthology-suite --priority 101 --suite rados --machine-type smithi --email ncutler@suse.com --ceph wip-19797 --filter="rados/singleton/bluestore"`

**waiting for build**

**Comment by liewegas** [comment]
..or the test can just tolerate this particular error message (but still 
fail on other errors).

**Comment by smithfarm** [comment]
Weird, the trusty notcmalloc build keeps failing. That must be a problem in master itself.

**Pull request merged**
