### PR TITLE
jewel: core: Addition of online osd 'omap'compaction command

### PR DESCRIPTION
**Pull request by vumrao**
jewel: Addition of online osd 'omap'compaction command
http://tracker.ceph.com/issues/20675

### CODE REVIEW

**Comment by vumrao** [comment]
@Liuchang0812 could you please help in the review.

**Comment by Liuchang0812** [comment]
LGTM

**Comment by Liuchang0812** [comment]
jenkins test this please

**Comment by xiexingguo** [comment]
the error is true; does not compile:

```
osd/OSD.cc: In member function ‘bool OSD::asok_command(std::__cxx11::string, cmdmap_t&, std::__cxx11::string, std::ostream&)’:
osd/OSD.cc:1947:14: error: ‘admin_command’ was not declared in this scope
   } else if (admin_command == "compact") {
```

**Comment by Liuchang0812** [comment]
thank you @xiexingguo 

this commit https://github.com/ceph/ceph/commit/10e6d1e1844ff20c6efde84ba8ecb9e779022ff7 rename `command` to `admin_command`. need we backport this commit ?

**Comment by xiexingguo** [comment]
> this commit 10e6d1e rename command to admin_command. need we backport this commit ?

I'd suggest resolving the conflicts instead.

**Comment by vumrao** [comment]
@Liuchang0812 @xiexingguo thank you for your review and comments. I have added new commit for changing the admin_command variable to command.

**Comment by smithfarm** [comment]
@jdurgin OK to backport this feature to jewel?

@vumrao Conflicts with #17084 - will need to wait until that one goes in, and then rebase.

**Comment by jdurgin** [comment]
@smithfarm yeah, this one is a non-risky change and can be very useful, so it's fine to backport

**Comment by smithfarm** [comment]
#17084 was just merged, so you can rebase this now, thanks.

**Comment by vumrao** [comment]
thanks @smithfarm and @jdurgin

**Comment by smithfarm** [comment]
@vumrao Please squash the last commit into 77e5e18 and mention the change in the Conflicts section there. Thanks.

**Comment by vumrao** [comment]
@smithfarm thanks, I have made the changes.

**Comment by GregMeno** [comment]
@jdurgin @smithfarm Would you please let me know what we are waiting for to merge this ?

**Comment by smithfarm** [comment]
@GregMeno We are waiting for this to be tested. When I'm preparing a release, I go from the oldest PRs to the newer ones. At some point, we have to say "cut". This one came out on the other side of the cut.

**Comment by vumrao** [comment]
- ceph-devel discussion 

<vikhyat> smithfarm: hey need one help regarding this PR status https://github.com/ceph/ceph/pull/17101 
<vikhyat> smithfarm: can we merge it ?
<vikhyat> smithfarm: I checked this 10.2.10 - http://tracker.ceph.com/issues/20613 but this one does not have it 
<vikhyat> so I am not sure if this was added for testing or not
<smithfarm> vikhyat: right
<smithfarm> updated the PR
<smithfarm> you might want to take a look at the ceph-devel mailing list - we've been discussing the 10.2.10 release there over the past few weeks and nobody asked for this PR
<vikhyat> smithfarm: yep sorry we missed it 
<vikhyat> smithfarm: any chance we can add it in testing and merge it 
<vikhyat> if we are not taking it in 10.2.10 

<vikhyat> is fine for us
<smithfarm> vikhyat: the problem is, QE testing has already started
<vikhyat> :(
<smithfarm> if we add anything, QE - i.e. yuriw - has to run all the tests over again
<smithfarm> vikhyat: we can go for a faster cycle on 10.2.11, what do you think?
<smithfarm> say, 4-5 weeks instead of 8-9 weeks, with less PRs in the release
<vikhyat> smithfarm: yep let me check and will get back to you thank you smithfarm for your help :)

**Comment by tchaikov** [comment]
http://pulpito.ceph.com/kchai-2017-10-02_07:55:29-rados-wip-kefu-testing-2017-10-02-1347-jewel-distro-basic-mira/

**Comment by tchaikov** [comment]
should backport #16500 also, see http://pulpito.ceph.com/kchai-2017-10-08_04:22:44-rados-wip-kefu-testing-2017-10-02-1347-jewel-distro-basic-smithi/1713442/

**Comment by vumrao** [comment]
@tchaikov thank you Kefu. I have backported the #16500.

**Comment by tchaikov** [comment]
- http://pulpito.ceph.com/kchai-2017-11-03_05:56:44-rados-wip-jewel-backports-reloaded-distro-basic-mira/
- http://pulpito.ceph.com/kchai-2017-11-03_12:19:08-rados-wip-jewel-backports-reloaded-distro-basic-mira/
- http://pulpito.ceph.com/kchai-2017-11-03_12:20:04-rados-wip-jewel-backports-reloaded-distro-basic-mira/

the test failure is addressed by https://github.com/ceph/teuthology/pull/1123

**Pull request merged**
