### PR TITLE
nautilus: MDSMonitor: warn if a new file system is being created with an EC default data pool

### PR DESCRIPTION
**Pull request by batrick**
https://tracker.ceph.com/issues/43506

### CODE REVIEW

**Comment by batrick** [comment]
jenkins test make check

**Comment by batrick** [comment]
http://pulpito.ceph.com/?branch=wip-pdonnell-testing-20200111.045306-nautilus

INSUFFICENT_STANDBY on last test is:  https://tracker.ceph.com/issues/43514

**Comment by smithfarm** [comment]
jenkins test make check

**Comment by smithfarm** [comment]
```
167/167 Test  #51: unittest_lockdep ........................***Timeout 3600.01 sec
```

**Comment by smithfarm** [comment]
jenkins test make check

**Comment by ajarr** [comment]
needs rebase

**Comment by batrick** [comment]
Rebase was not actually necessary. See thread "Ceph Release Branch Management" on ceph-devel. I did it anyway to clean up the github commits.

**Comment by yuriw** [comment]
[wip-yuri3-testing-2020-02-09-2109-nautilus](https://trello.com/c/uOvzPFHl/821-wip-yuri3-testing-2020-02-09-2109-nautilus)

**Pull request merged**
