### PR TITLE
mgr/dashboard: OSD details: Load only one tab at a time

### PR DESCRIPTION
**Pull request by tspmelo**
Fixes: https://tracker.ceph.com/issues/45017

Signed-off-by: Tiago Melo <tmelo@suse.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by tspmelo** [comment]
jenkins test dashboard

**Comment by tspmelo** [comment]
jenkins test dashboard

**Comment by tspmelo** [comment]
@epuertat I added the DNM label because I was not liking the current implementation and was trying to see if I could extend from the directives of #34946 or find a better solution.

Looks like it... I will investigate ng-bootstrap...

**Comment by epuertat** [comment]
> @epuertat I added the DNM label because I was not liking the current implementation and was trying to see if I could extend from the directives of #34946 or find a better solution.
> 
> Looks like it... I will investigate ng-bootstrap...

Opss, didn't see the DNM. Thanks. I checked both tabset implementations for the PR that @votdev did for keeping state/URL with tabs, and the ng-bootstrap looks simpler but better solving these cases we are now fixing in the ngx-bootstrap one.

**Comment by tspmelo** [comment]
Close in favor of #35290

**Pull request closed without merging**
