### PR TITLE
luminous: rgw: list bucket can not show the object uploaded by RGWPostObj when enable bucket versioning

### PR DESCRIPTION
**Pull request by joke-lee**
https://tracker.ceph.com/issues/36423

### CODE REVIEW

**Comment by joke-lee** [comment]
hi @cbodley do you mind help review this?

**Comment by joke-lee** [comment]
hi @cbodley ,would you mind add this to qa?

**Comment by cbodley** [comment]
hi @joke-lee - the backport team does this testing in batches leading up to a point release, so i'll leave it to them

**Comment by yuriw** [comment]
[wip-yuri3-testing-2018-10-31-2012-luminous](https://trello.com/c/Rp8QwzgA/458-wip-yuri3-testing-2018-10-31-2012-luminous)

**Pull request merged**
