### PR TITLE
mimic: mgr: crashdump feature backport

### PR DESCRIPTION
**Pull request by dmick**
- [ ] References tracker ticket
- [x] Updates documentation if necessary
- [x] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by smithfarm** [comment]
@liewegas Is this something that should go into 13.2.3?

**Comment by smithfarm** [comment]
@dmick @liewegas Ping. Should this be included in a normal mimic integration testing run?

**Comment by dmick** [comment]
@smithfarm I believe so.

**Comment by smithfarm** [comment]
@dmick @liewegas We're now collecting PRs for 13.2.5 - is this ready to go?

**Comment by dmick** [comment]
as far as I know, yes

**Comment by dmick** [comment]
Did this never get merged?

**Comment by yuriw** [comment]
[wip-yuri-testing-2019-03-20-2018-mimic](https://trello.com/c/eYs8FKUW/562-wip-yuri-testing-2019-03-20-2018-mimic)

**Comment by yuriw** [comment]
[wip-yuri3-testing-2019-04-02-1623-mimic](https://trello.com/c/1KoExCxx/575-wip-yuri3-testing-2019-04-02-1623-mimic)

**Comment by yuriw** [comment]
@liewegas this passed tests and ready for merge

**Comment by sebastian-philipp** [comment]
See https://tracker.ceph.com/issues/39132

**Pull request merged**
