### PR TITLE
osd/PG: fix _finish_recovery vs repair race

### PR DESCRIPTION
**Pull request by xiexingguo**
On detecting a corrupted object, primary may automatically
repair that object by leveraging the existing recovery procedure,
which turned out to be racy with a previous unfinished _finish_recovery
callback - the problem would then be that _finish_recovery might
continue to purge some strays that we still want to pull data from.

Fix by re-checking if there are any newly added missing objects when
executing _finish_recovery.

Note that before https://github.com/ceph/ceph/pull/29756 we might
instead have to call needs_recovery to catch the race condition
since we did not evict pg from clean state when triggering an auto-repair..

Signed-off-by: xie xingguo <xie.xingguo@zte.com.cn>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`

</details>

### CODE REVIEW

**Comment by neha-ojha** [comment]
@xiexingguo This sounds very much like https://tracker.ceph.com/issues/41385. I have a reproducer for this bug, I can run this PR against it to verify it.

**Comment by xiexingguo** [comment]
> This sounds very much like https://tracker.ceph.com/issues/41385. 

yeah, I hit the same assert a couple of days ago, but sadly can not remember which one (it's a dead job)

> I have a reproducer for this bug, I can run this PR against it to verify it.

That would be much appreciated.

**Comment by neha-ojha** [comment]
The issue did not reproduce in http://pulpito.ceph.com/nojha-2019-09-03_23:38:46-rados:singleton-wip-30059-distro-basic-smithi/ so that's good!

Running a rados suite run here: http://pulpito.ceph.com/nojha-2019-09-04_14:23:27-rados-wip-30059-distro-basic-smithi/

**Comment by xiexingguo** [comment]
@neha-ojha Thanks!

**Comment by neha-ojha** [comment]
@xiexingguo https://github.com/ceph/ceph/pull/30226#issuecomment-529027122 describes another approach to fix the same issue, let me know your thoughts about it.

Your patch seems to also fix the immediate problem, but I am not sure if adding the `!is_clean()` check at the last stage of recovery in finish_recovery() might complicate things, since some clean up of recovery related information(peer_missing/info etc.) is done before we reach this point.

**Comment by xiexingguo** [comment]
@neha-ojha We could have both, they don't interfere with each other.
A pg should never purge stray until it is clean, which I think is the baseline by design:-)

**Comment by xiexingguo** [comment]
> I don't like the !is_clean() to see if the PG should be skipped. When a primary needs to repair an object it kicks off recovery even when the PG is clean.

@dzafman Not any more and it was wrong.

See https://github.com/ceph/ceph/pull/29756

**Comment by neha-ojha** [comment]
> @neha-ojha We could have both, they don't interfere with each other.
> A pg should never purge stray until it is clean, which I think is the baseline by design:-)

sounds fair!

**Pull request merged**
