### PR TITLE
mimic: common/str_map: fix trim() on empty string

### PR DESCRIPTION
**Pull request by ashishkumsingh**
https://tracker.ceph.com/issues/38587

### CODE REVIEW

**Comment by smithfarm** [comment]
mimic test make check

**Comment by smithfarm** [comment]
jenkins test make check

**Comment by yuriw** [comment]
[wip-yuri3-testing-2019-04-29-1935-mimic](https://trello.com/c/1OdZ5zIb/598-wip-yuri3-testing-2019-04-29-1935-mimic)

**Comment by yuriw** [comment]
[wip-yuri3-testing-2019-04-30-1543-mimic](https://trello.com/c/MkrC4MVX/599-wip-yuri3-testing-2019-04-30-1543-mimic)

**Pull request merged**
