### PR TITLE
cls/rgw_gc: Modifying log level of log messages related

### PR DESCRIPTION
**Pull request by pritha-srivastava**
to deferred entries.

Signed-off-by: Pritha Srivastava <prsrivas@redhat.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Review by mattbenjamin — APPROVED** [review]
lgtm

**Comment by mattbenjamin** [comment]
as agreed, let's call "total num entries" something that indicates they're urgent data elements

**Review by mattbenjamin — APPROVED** [review]
looks great

**Comment by pritha-srivastava** [comment]
jenkins test make check

**Comment by pritha-srivastava** [comment]
jenkins test api

**Pull request closed without merging**
