### PR TITLE
Mailmap updates for infernalis.

### PR DESCRIPTION
**Pull request by dupont-y**
Please review before merging. I made some choices for jenkins (now accounted for redhat) - Not sure I've done it the right way (do we need .peoplemap ?)

No new entries this time. Just fixing some problems to have a consistent output from v0.94 -> v9.2.0

### CODE REVIEW

**Comment by dachary** [comment]
Missing in mailmap:

<pre>
Burkhard.Linke &lt;Burkhard.Linke@computational.bio.uni-giessen.de> &lt;Burkhard.Linke@computational.bio.uni-giessen.de>
Ji Chen &lt;insomnia@139.com> &lt;insomnia@139.com>
</pre>

otherwise looks good :-)

**Comment by dachary** [comment]
@dupont-y could you add a comment when you have sent the emails to the authors ? We'll wait a week for their reply and then merge.

**Comment by dupont-y** [comment]
Mails are sent.

**Comment by dachary** [comment]
@dupont-y could you please rebase ?

**Comment by dupont-y** [comment]
Le 21/11/2015 18:27, Loic Dachary a écrit :
>
> @dupont-y <https://github.com/dupont-y> could you please rebase ?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/ceph/ceph/pull/6495#issuecomment-158663484>.
>
Yep.
Sorry for the delay, I was away.
I'll do this tonight.

Cheers

**Comment by dupont-y** [comment]
Rebase done. Conflict was due to Ji Chan Affiliation already corrected in another patch
I hope I didn't made mistakes in the process.

**Comment by dachary** [comment]
One minor glitch, otherwise good :-)

**Comment by dupont-y** [comment]
You really have better eyes than me :) Is this OK this time ?

**Comment by dachary** [comment]
Yeah !

**Pull request merged**
