### PR TITLE
qa/rgw: run ceph_test_cls_2pc_queue in verify suite

### PR DESCRIPTION
**Pull request by cbodley**
## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by cbodley** [comment]
@yuvalif seeing strange failures in http://pulpito.ceph.com/cbodley-2020-04-14_17:24:48-rgw-wip-cbodley-testing-distro-basic-smithi/

a number of tests are passing, but several are failing with -1

**Comment by yuvalif** [comment]
> @yuvalif seeing strange failures in http://pulpito.ceph.com/cbodley-2020-04-14_17:24:48-rgw-wip-cbodley-testing-distro-basic-smithi/
> 
> a number of tests are passing, but several are failing with -1

looking into that

**Comment by cbodley** [comment]
added cls_queue to the osd load lists to resolve that failure

**Comment by yuvalif** [comment]
> added cls_queue to the osd load lists to resolve that failure

root cause is fixed here: https://github.com/ceph/ceph/pull/34669

**Pull request merged**
