### PR TITLE
quincy: mount: fix mount failure with old kernels

### PR DESCRIPTION
**Pull request by lxbsz**
backport tracker: https://tracker.ceph.com/issues/58251

---

backport of https://github.com/ceph/ceph/pull/48873
parent tracker: https://tracker.ceph.com/issues/58018

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by dparmar18** [comment]
I can see tox failures in this PR too, log says:

```
The following tests FAILED:
	  4 - run-tox-mgr (Failed)
	 22 - run-tox-cephadm (Failed)
	254 - run-tox-qa (Failed)
	265 - run-tox-jsonnet-check (Failed)
	271 - run-tox-alerts-lint (Failed)
```

Is this expected for quincy branch? @adk3798

**Comment by adk3798** [comment]
> I can see tox failures in this PR too, log says:
> 
> ```
> The following tests FAILED:
> 	  4 - run-tox-mgr (Failed)
> 	 22 - run-tox-cephadm (Failed)
> 	254 - run-tox-qa (Failed)
> 	265 - run-tox-jsonnet-check (Failed)
> 	271 - run-tox-alerts-lint (Failed)
> ```
> 
> Is this expected for quincy branch? @adk3798

pending https://github.com/ceph/ceph/pull/49361, yes. Fallout of the tox version being upgraded on the jenkins machines

**Comment by lxbsz** [comment]
Nothing changed, just pushed wrong patches to this PR and reverted it back.

**Comment by vshankar** [comment]
jenkins test api

**Review by vshankar — APPROVED** [review]
https://tracker.ceph.com/projects/cephfs/wiki/Quincy#2023-Feb-15

**Comment by yuriw** [comment]
jenkins test api

**Comment by yuriw** [comment]
@lxbsz this is ready but needs to pass API tests

**Comment by lxbsz** [comment]
jenkins test api

**Comment by lxbsz** [comment]
> @lxbsz this is ready but needs to pass API tests

Rebased it.

**Pull request merged**
