### PR TITLE
rgw: fix drain handles error when deleting bucket with bypass-gc option

### PR DESCRIPTION
**Pull request by taodd**
Fixes: https://tracker.ceph.com/issues/40587

Signed-off-by: dongdong tao <dongdong.tao@canonical.com>

- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by taodd** [comment]
retest this please

**Comment by taodd** [comment]
retest this please

**Comment by ivancich** [comment]
No rgw/verify regressions -- see: http://pulpito.ceph.com/ivancich-2019-08-01_14:38:47-rgw-wip-eric-testing-1-distro-basic-smithi/

No rgw/(non-verify) regressions -- see: http://pulpito.ceph.com/ivancich-2019-08-01_14:38:07-rgw-wip-eric-testing-1-distro-basic-smithi/

No s3-tests regressions.

**Comment by taodd** [comment]
Hi @ivancich I'm not sure what happened, but it appears this patch wasn't applied to the main branch. 
Octopus and Quincy onwards don't have it, we are still encountering the same bug.

**Pull request merged**
