### PR TITLE
rgw: add check for ACL when create existing bucket

### PR DESCRIPTION
**Pull request by cbodley**
some cleanups for https://github.com/ceph/ceph/pull/35170:
* use composition of `operator==()`s to avoid having to encode buffers for comparison
* adds `operator!=()`s
* changes the `create_bucket()` policy argument from an optional pointer to a const reference
* moves the acl owner comparison into `operator==()`

Fixes: https://tracker.ceph.com/issues/47028

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Review by dang — APPROVED** [review]

**Comment by BryceCao** [comment]
LGTM, brevity code.

**Comment by cbodley** [comment]
i wrote an s3test case for this and it doesn't appear to work. there's extra code in `RGWCreateBucket::execute()` that handles this `-EEXIST` error and falls back to an owner comparison. i don't fully understand the retry logic in `if (need_metadata_upload() && existed)`, but that's probably related to the tempest test failures

**Comment by cbodley** [comment]
see test cases in https://github.com/ceph/s3-tests/pull/356

**Comment by cbodley** [comment]
@dang it looks like my latest commit resolved the tempest test failures in test_create_container_with_remove_metadata_key and test_create_container_with_remove_metadata_value. can you please review that one?

https://pulpito.ceph.com/cbodley-2020-09-11_14:01:23-rgw-wip-cbodley-testing-distro-basic-smithi/

**Review by dang — APPROVED** [review]

**Comment by cbodley** [comment]
still having issues with the multisite `test_bucket_create()` here. when creating a bucket on a secondary zone, it forwards the request to the master first. after that, we go on to call `RGWRados::create_bucket()`, but that returns `-EEXIST` if metadata sync raced to create the bucket instance first

**Comment by dang** [comment]
How about this:

```
diff --git a/src/rgw/rgw_sal_rados.cc b/src/rgw/rgw_sal_rados.cc
index 4902e72a84c..ba4168e7320 100644
--- a/src/rgw/rgw_sal_rados.cc
+++ b/src/rgw/rgw_sal_rados.cc
@@ -925,6 +925,7 @@ int RGWRadosStore::create_bucket(RGWUser& u, const rgw_bucket& b,
                                    pmaster_bucket, pmaster_num_shards, exclusive);
     if (ret == -EEXIST) {
       *existed = true;
+      ret = 0;
     } else if (ret != 0) {
       return ret;
     }

```

**Comment by cbodley** [comment]
thanks, that did it! https://pulpito.ceph.com/cbodley-2020-09-14_18:11:23-rgw-wip-cbodley-testing-distro-basic-smithi/

**Pull request merged**
