### PR TITLE
fix compilation on OSX/FreeBSD

### PR DESCRIPTION
**Pull request by ukernel**

### CODE REVIEW

**Comment by gregsfortytwo** [comment]
It built on my Mac, and things didn't previously. Hurray!
(I pushed a branch to the gitbuilders which includes this and may let it run through a test as well just to make sure.)

**Comment by dachary** [comment]
please ignore the bot failure, it's a false negative

**Comment by tchaikov** [comment]
@gregsfortytwo how's the build going?

@ukernel maybe we can keep using `ceph.git/wip-osx-port` or `ceph.git/port/new` in future for the osx/freebsd port? as i also have some changes for cmake on mac, which could probably be piggybacked on yours when performing test and build?

**Comment by ukernel** [comment]
@tchaikov.  OK, I will do that for later PR

**Comment by gregsfortytwo** [comment]
@tchaikov, it builds fine but I haven't tried the most recent set of patches. This branch got stuck behind some test failures I need to deal with for Infernalis; feel free to take it if you like! (Or not and I'll do it eventually.)

**Comment by tchaikov** [comment]
okay, just want to see if anything i can do to fix the build. =)

**Pull request merged**
