### PR TITLE
tools: add a tool to restore crush map after a faulty one is injected

### PR DESCRIPTION
**Pull request by tchaikov**
- add "--dump <format>" command to osdmaptool, so we are able to extract osdmap epoch using xmlstarlet
- add a command to ceph-monstore-tool to rewrite monstore
- add a script to help fix the crush map

see http://tracker.ceph.com/issues/11815

### CODE REVIEW

**Comment by dachary** [comment]
loic-bot says FAIL: http://jenkins.ceph.dachary.org/job/ceph/6032/LABELS=centos-7&&x86_64/console

**Comment by tchaikov** [comment]
thanks @dachary, i just fixed the script's path, and also added it to the dist tarball.

**Comment by tchaikov** [comment]
@jecluis could you take a quick look at this change? i 

1. packed all the changes in a proposal, and put it into a new paxos commit. but i didn't update the infected osdmap epoches as you suggested, since the paxos commit will be applied on all monitors, so the bad epoches on leader will be fixed once the proposal is accepted.
1. added a new osdmap commit, so the OSDMonitor will update its current osdmap at seeing it.

**Comment by tchaikov** [comment]
the failure was due to:
```
2015-06-24 16:42:15.427958 2b22a8bf2bc0 -1 mon.a@-1(probing).osd e3 update_from_paxos full map CRC mismatch, resetting to canonical
```

**Comment by jecluis** [comment]
Overall looks good, aside from few recent comments.  We still have to figure out in more detail the need for a new osdmap version though.

**Comment by tchaikov** [comment]
> We still have to figure out in more detail the need for a new osdmap version though.

the related comments[0] was swallowed by github 

---
[0] https://github.com/ceph/ceph/commit/abd06355dbbcd8db26af12557cb4b687e68aa463#commitcomment-11895337

**Comment by tchaikov** [comment]
@jecluis, i addressed most of your comments other than https://github.com/ceph/ceph/commit/abd06355dbbcd8db26af12557cb4b687e68aa463#commitcomment-11895337 . if i remove the `last_committed+1` osdmap, the test fails. so maybe my test is wrong? could you advise? thanks.

**Comment by tchaikov** [comment]
per the discussion tonight, we should also offer a command, with which user can extract both the full map **and** the incrementals, which can be injected to the OSD's object store. we can do it as part of #5127.

**Comment by tchaikov** [comment]
@jecluis i managed to workaround the "local" command.
>  $ help local
> ...
>   Exit Status:
>   Returns success unless an invalid option is supplied, a variable
>   assignment error occurs, or the shell is not executing a function.

so "local" is practically always happy at whatever the following `$()` subshell returns, and what we need is to put the assignment at a different line.

```
$ ./tools/ceph-monstore-update-crush.sh dev/mon.a/
IO error: lock dev/mon.a/store.db/LOCK: Resource temporarily unavailable

error accessing mon store at dev/mon.a/
```

**Comment by tchaikov** [comment]
```
FAIL: test/libradosstriper/rados-striper.sh
```
the failed test is not relevant .

**Comment by dachary** [comment]
@tchaikov could you please rebase and repush ? It's the first time this rados-striper.sh error happens and I'd like to make sure it's a transient error.

**Comment by tchaikov** [comment]
@dachary rebased and repushed.

**Comment by tchaikov** [comment]
rebased against master to resolve the merge conflicts of PendingReleaseNotes .

@jecluis ping?

**Comment by jecluis** [comment]
Let's wait for the bot to come back with a clean build and I'll merge it then ;)

**Comment by tchaikov** [comment]
cool, thanks in advance! =)

**Pull request merged**
