### PR TITLE
osd: Object level shard errors are tracked and used if no auth available

### PR DESCRIPTION
**Pull request by dzafman**

### CODE REVIEW

**Comment by dzafman** [comment]
Waiting for shaman build to do a repair_test rados test of it.

**Comment by dzafman** [comment]
Please test this again

**Comment by tchaikov** [comment]
retest this please. see #15406

**Comment by dzafman** [comment]
Running just rados_test and scrub_test passed:

http://pulpito.ceph.com/dzafman-2017-06-01_12:42:18-rados-wip-20089-distro-basic-smithi/
http://pulpito.ceph.com/dzafman-2017-06-01_13:38:50-rados-wip-20089-distro-basic-smithi/

**Pull request merged**
