### PR TITLE
qa/cephfs/overrides: ignore expected PG_DEGRADED health warning

### PR DESCRIPTION
**Pull request by ljflores**
Fixes: https://tracker.ceph.com/issues/65018

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [x] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Comment by ljflores** [comment]
I scheduled some tests here against the original branch and the new suite branch:
https://pulpito.ceph.com/lflores-2024-03-26_17:10:07-fs-wip-batrick-testing-20240320.145742-distro-default-smithi/

**Review by batrick — COMMENTED** [review]
Laura, I confess I find this deeply unsatisfying. The `fs` suite has never ignorelisted `PG_DEGRADED` except for full pool testing. Is there a reason this is now common?

**Comment by ljflores** [comment]
@batrick do you have a good run to compare with a bad run? We touched on this briefly in the RADOS bug scrub and we agreed it was an expected warning, but I can do a deeper analysis.

I was suspecting https://github.com/ceph/ceph/pull/54312 to be the difference, but some of the affected tests don't appear to use cephadm, so that may not be it.

**Comment by batrick** [comment]
> @batrick do you have a good run to compare with a bad run? We touched on this briefly in the RADOS bug scrub and we agreed it was an expected warning, but I can do a deeper analysis.
> 
> I was suspecting #54312 to be the difference, but some of the affected tests don't appear to use cephadm, so that may not be it.

It is probably #55455.

I looked at this more closely and see in the mon log:

```
2024-03-20T19:00:36.774+0000 7fa4ece00700 10 mon.a@0(leader).osd e82 update_pending_pgs  pg 2.1b just added,  up [5,2,7] p 5 acting [5,2,7] p 5 history ec=83/83 lis/c=0/0 les/c/f=0/0/0 sis=83 past_intervals ([0,0] all_participants={} intervals=[])

2024-03-20T19:01:32.915+0000 7fa4e9c00700  1 -- [v2:172.21.15.43:3300/0,v1:172.21.15.43:6789/0] <== mgr.14152 172.21.15.43:0/2091623787 1815 ==== mon_command({"prefix": "osd pg-upmap-items", "format": "json", "pgid": "2.1b", "id": [2, 4]} v 0) ==== 122+0+0 (secure 0 0 0) 0x55c27a8d7180 con 0x55c27aeda800

2024-03-20T19:01:33.787+0000 7fa4e6a00700  2 mon.a@0(leader) e3 send_reply 0x55c27b53c5a0 0x55c27abfb2c0 mon_command_ack([{"prefix": "osd pg-upmap-items", "format": "json", "pgid": "2.1b", "id": [2, 4]}]=0 set 2.1b pg_upmap_items mapping to [2->4] v87)

                "message": "pg 2.1b is activating+degraded, acting [5,4,7]"
```

AFAICT, this PG_DEGRADED warning is unavoidable when one of the replicas is swapped for another OSD. Correct? Despite understanding the overall design, I wasn't aware of this aspect. Would it not have been safer for the new replica OSD (`osd.4`) to have been added to the PG, fully replicated, then and only then swap out the old OSD (`osd.2`)? Perhaps it's not possible to have 4 OSDs in a pg in a replica 3 pool?

In any case, this leaves me with the question: do we really want to use the upmap balancer in the cephfs suites when we would need to ignore the PG_DEGRADED warnings? Or is it more valuable for the upmap to be tested somewhat poorly in the cephfs suites?

cc @rzarzynski @vshankar

**Comment by batrick** [comment]
I want to add that I do see value in the PG_DEGRADED warnings as it has caught odd behavior like:

https://tracker.ceph.com/issues/51282

I know that is currently considered uninteresting but, to me, that exemplifies the kind of aberrant behavior we **want** to know about. If we filter out this class of warnings, we will be unaware of these problems going forward. That doesn't sit well with me at all.

**Comment by ljflores** [comment]
@batrick all makes sense. Let's close this PR so it doesn't merge or anything and perhaps continue discussion in the tracker.

**Pull request closed without merging**
