### PR TITLE
mgr/balancer: Disallow 7 as {begin,end}_weekday and 2400 as {begin,end}_time

### PR DESCRIPTION
**Pull request by tcoldrick-bb**
Since PR 37941 was merged, the OSD Scrub Schedule no longer accepts 7
and 2400 as values for the weekday and time respectively, but the
balancer module in the manager still uses the old parameters. For
consistency, this commit swaps the balancer to also reject days with the
value of 7.

This change also modifies the behaviour of the
{begin,end}_{weekday,time} settings to match that in the OSD Scrub
Scheduler - As 7 is no longer permitted, setting the two values to be
equal will set the window to be always on.

Fixes: https://tracker.ceph.com/issues/49086
Signed-off-by: Tom Coldrick <tcoldrick@bloomberg.net>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [x] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Review by ljflores — COMMENTED** [review]
How does the balancer "reject" weekday values outside of 0-6 and times outside of 000-2359? I ran a couple of commands with rejected values, and they seemed to pass through okay:

`ceph config set mgr mgr/balancer/end_time 7`
`ceph config set mgr mgr/balancer/end_weekday 2400`

I see some logging based on whether a time is permitted or not, but I'm trying to understand if something else should be happening to "reject" these incorrect values.

**Comment by tcoldrick-bb** [comment]
> How does the balancer "reject" weekday values outside of 0-6 and times outside of 000-2359?

Validation works using the `min` and `max` attributes of the `Option` instances for the module options, at least for the weekday cases. The time cases didn't use this for validation already, and I've not added anything extra to do validation. I can add `min` and `max` configuration for the time cases too, but this won't be sufficient validation - since times are formatted as `HHMM`, cases where `MM >= 60` should also be discounted (possibly also values without the `HHMM` format) . From a look around the source, I can't see a "clean" way to implement this kind of custom check on a module option, but I'd be happy to implement such a check if there is a way to do so!

>  I ran a couple of commands with rejected values, and they seemed to pass through okay:
> `ceph config set mgr mgr/balancer/end_time 7` `ceph config set mgr mgr/balancer/end_weekday 2400`

The values seem to be for the wrong keys here, so the first one should pass even if there was validation on `end_time` and `begin_time`. Using 2400 instead does pass without issue with this patch at the moment though. The second command is well outside the upper bound of `6` for `end_weekday` and should be disallowed. Trying this locally (on a `vstart.sh` for me yields:

```console
$ ./bin/ceph config set mgr mgr/balancer/end_weekday 2400
<snip out stuff about developer mode>
Error EINVAL: error passing value: Value '2400' exceeds maximum 6
```

**Comment by ljflores** [comment]
> Validation works using the `min` and `max` attributes of the `Option` instances for the module options, at least for the weekday cases. The time cases didn't use this for validation already, and I've not added anything extra to do validation. I can add `min` and `max` configuration for the time cases too, but this won't be sufficient validation - since times are formatted as `HHMM`, cases where `MM >= 60` should also be discounted (possibly also values without the `HHMM` format) . From a look around the source, I can't see a "clean" way to implement this kind of custom check on a module option, but I'd be happy to implement such a check if there is a way to do so!

I see what happened; it's exactly as you said, that I had the values switched. I tried it again with the correct commands, and it worked as expected (same with begin_weekday). Apologies for this:
```
$ ./bin/ceph config set mgr mgr/balancer/end_weekday 7
*** DEVELOPER MODE: setting PATH, PYTHONPATH and LD_LIBRARY_PATH ***
2022-07-18T19:08:19.703+0000 7f90e467e700 -1 WARNING: all dangerous and experimental features are enabled.
2022-07-18T19:08:19.715+0000 7f90e467e700 -1 WARNING: all dangerous and experimental features are enabled.
Error EINVAL: error parsing value: Value '7' exceeds maximum 6
```

As for validating the times, I can see how that would be tricky. Since the behavior has always been this way, where there is no min or max enforced, I don't see a need to invent a new way to track it in the config option. I do think some logging could help though. What about using datetime.time() to check whether the time fits in the correct parameters?

A datetime object with "2400" gets rejected due to a value error, since datetime also enforces an hour value between 0 and 23. Restrictions are also in place for minutes and seconds:
```
x = datetime.time(24, 0, 0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: hour must be in 0..23
```
We could check the date this way and include a `self.log.error` message when we catch a ValueError, saying why the value was not accepted if a user is curious why their value isn't working.

**Comment by ljflores** [comment]
jenkins test make check

**Comment by ljflores** [comment]
jenkins test make check

**Comment by ljflores** [comment]
jenkins test make check

**Review by ljflores — APPROVED** [review]

**Comment by ljflores** [comment]
jenkins test make check

**Comment by ljflores** [comment]
Works as expected! Thanks @tcoldrick-bb.

```
2022-09-13T19:27:31.636+0000 7f4ad3377700  0 [balancer ERROR root] invalid time for begin_time - expected HHMM format
2022-09-13T19:27:31.636+0000 7f4ad3377700  0 [balancer ERROR root] invalid time for begin_time - invalid literal for int() with base 10: ''

```

**Comment by ljflores** [comment]
@tcoldrick-bb I added the "needs-qa" label. Your PR will now be picked up by one of the engineers to go through integration testing. If it passes tests there, the PR will be merged. If there's any problem in the tests, I'll let you know.

For now, nothing more needs to be done on your end.

**Comment by Matan-B** [comment]
Rados Approves.
http://pulpito.front.sepia.ceph.com/yuriw-2022-09-14_13:16:11-rados-wip-yuri6-testing-2022-09-13-1352-distro-default-smithi

0 Related Failures.
6 Tracked unrelated Failures.
0 Newly Tracked Failures.
1 Tracked dead Jobs.

7032119, 7032277: rook: ensure CRDs are installed first (https://tracker.ceph.com/issues/57311)
7032198: cephadm/test_dashboard_e2e.sh: Expected to find content(https://tracker.ceph.com/issues/57386)
7032199, 7032359: 'check osd count' reached maximum triess (https://tracker.ceph.com/issues/52321)
7032334: test_orch_cli test failing (https://tracker.ceph.com/issues/54029)*

Dead Jobs:
7032356: thrash-erasure-code: AssertionError: wait_for_recovery (https://tracker.ceph.com/issues/56149)

**Pull request merged**
