### PR TITLE
luminous: ceph-volume: adds raw device support to 'lvm list'

### PR DESCRIPTION
**Pull request by andrewschoen**
fixes: http://tracker.ceph.com/issues/23140

backport of #20620

### CODE REVIEW

**Comment by andrewschoen** [comment]
jenkins test ceph-volume tox

**Comment by andrewschoen** [comment]
jenkins test ceph-volume all

**Comment by andrewschoen** [comment]
jenkins test ceph-volume lvm centos7-filestore-create

**Comment by andrewschoen** [comment]
jenkins test ceph-volume lvm xenial-bluestore-create

**Comment by andrewschoen** [comment]
jenkins test ceph-volume lvm xenial-bluestore-dmcrypt

**Comment by andrewschoen** [comment]
jenkins test ceph-volume lvm xenial-filestore-create

**Comment by andrewschoen** [comment]
jenkins test ceph-volume simple centos7-bluestore-dmcrypt_plain

**Comment by andrewschoen** [comment]
jenkins test ceph-volume simple centos7-filestore-dmcrypt_luks

**Comment by andrewschoen** [comment]
jenkins test ceph-volume simple xenial-bluestore-dmcrypt_luks

**Comment by andrewschoen** [comment]
jenkins test ceph-volume simple xenial-bluestore-dmcrypt_plain

**Comment by andrewschoen** [comment]
jenkins test ceph-volume simple xenial-filestore-dmcrypt_luks

**Comment by alfredodeza** [comment]
jenkins test ceph-volume all

**Comment by andrewschoen** [comment]
jenkins test ceph-volume simple xenial-bluestore-dmcrypt_luks

**Comment by andrewschoen** [comment]
jenkins test ceph-volume simple centos7-filestore-dmcrypt_luks

**Comment by andrewschoen** [comment]
jenkins test ceph-volume lvm centos7-filestore-create

**Pull request merged**
