### PR TITLE
luminous ceph-volume: introduce class hierachy for strategies

### PR DESCRIPTION
**Pull request by jan--f**
Backport of #25238

### CODE REVIEW

**Comment by jan--f** [comment]
@alfredodeza Anything blocking this?

**Comment by alfredodeza** [comment]
@jan--f we were blocked by failures related to ceph-ansible changes. For some context see the links in the description for PR https://github.com/ceph/ceph/pull/25820

This will now need a rebase so that we can test this accordingly.

**Comment by jan--f** [comment]
@alfredodeza done

**Comment by alfredodeza** [comment]
seems like the `json` import is still there, which was removed/cleaned-up already?  see https://jenkins.ceph.com/job/ceph-volume-pr/490/consoleFull#231334942c19247c4-fcb7-4c61-9a5d-7e2b9731c678

**Comment by jan--f** [comment]
@alfredodeza On master the fix was part of #25594. So either there is a backport for this PR somewhere (I can't find it) or I'll include it here.

**Comment by alfredodeza** [comment]
Can you include d127ae3e5901c6477ed44f4d50be834040c44b6f in this backport as well as on the mimic one? Seems I can't really backport pr #25594 cleanly in the current state of these branches

**Comment by jan--f** [comment]
jenkins test ceph-volume lvm all

**Pull request merged**
