### PR TITLE
qa/tasks/workunit: use ceph.git as an alternative of ceph-ci.git for cloning workunit

### PR DESCRIPTION
**Pull request by tchaikov**
if we run upgrade test, where, for example, "jewel" is not in
ceph-ci.git repo, we should check ceph.git to clone the workunits.

this fixes http://pulpito.ceph.com/kchai-2017-02-27_04:13:29-rados-wip-kefu-testing---basic-smithi/862549/

### CODE REVIEW

**Comment by tchaikov** [comment]
it's a regression introduced by #13625

**Comment by idryomov** [comment]
Ah, that's what it is for...  It wasn't mentioned in the commit that introduced -- I checked ;)

Have you tested this?  The except branch seems to use git_url and not alt_git_url?

**Comment by tchaikov** [comment]
@idryomov thanks for the review. fixed, and i am pushing this change to ceph-ci for testing it. will update the PR with the  link to the test run.

**Comment by tchaikov** [comment]
being tested at http://pulpito.ceph.com/kchai-2017-02-27_17:21:17-rados-wip-ceph-git-for-workunit-kefu---basic-mira/

**Comment by tchaikov** [comment]
```
2017-02-27T18:20:37.613 INFO:teuthology.orchestra.run.mira026:Running: 'rm -rf /home/ubuntu/cephtest/clone.client.0 && git clone git://git.ceph.com/ceph-ci.git /home/ubuntu/cephtest/clone.client.0 && cd -- /home/ubuntu/cephtest/clone.client.0 && git checkout jewel'
2017-02-27T18:20:38.137 INFO:tasks.workunit.client.0.mira026.stderr:Cloning into '/home/ubuntu/cephtest/clone.client.0'...
2017-02-27T18:21:06.629 INFO:tasks.workunit.client.0.mira026.stderr:error: pathspec 'jewel' did not match any file(s) known to git.
2017-02-27T18:21:06.631 INFO:tasks.workunit:failed to check out 'jewel' from git://git.ceph.com/ceph-ci.git; will also try in git://git.ceph.com/ceph.git
2017-02-27T18:21:06.631 INFO:teuthology.orchestra.run.mira026:Running: 'rm -rf /home/ubuntu/cephtest/clone.client.0 && git clone git://git.ceph.com/ceph.git /home/ubuntu/cephtest/clone.client.0 && cd -- /home/ubuntu/cephtest/clone.client.0 && git checkout jewel'
2017-02-27T18:21:07.053 INFO:tasks.workunit.client.0.mira026.stderr:Cloning into '/home/ubuntu/cephtest/clone.client.0'...
2017-02-27T18:25:23.889 INFO:tasks.workunit.client.0.mira026.stderr:Switched to a new branch 'jewel'
2017-02-27T18:25:23.937 INFO:tasks.workunit.client.0.mira026.stdout:Branch jewel set up to track remote branch jewel from origin.
```

**Comment by smithfarm** [comment]
Should #13625 and this PR be backported?

**Comment by tchaikov** [comment]
@smithfarm they improve the developer's user experience when testing using the tasks in qa suites. but it's not a user visible change. so i think it's just nice to backport them, but not required.

**Comment by idryomov** [comment]
Might want to hold the backporting for another week or two until we are sure there are no regressions.  People seem to be having issues in this area: http://tracker.ceph.com/issues/19188.

**Pull request merged**
