### PR TITLE
pacific: cephadm: Batch backport January (2)

### PR DESCRIPTION
**Pull request by sebastian-philipp**
Backport of #39035, #38935, #39028, #39087, #38998, #38854, #38982, #39101, #39043, #39113, #39112, #39007, #39083, #38875, #38686, #39118

### CODE REVIEW

**Review by jmolmo — APPROVED** [review]

**Review by callithea — APPROVED** [review]
Lgtm!

**Comment by yuriw** [comment]
[wip-yuri-testing-2021-01-29-0819-pacific](https://trello.com/c/v8je3FKA/1130-wip-yuri-testing-2021-01-29-0819-pacific)

**Review by neha-ojha — APPROVED** [review]
rados and rados/cephadm runs look good.

**Review by jan--f — APPROVED** [review]
:+1: from the ceph-volume side. One failed test is an intermittent network issue during the test setup.

**Pull request merged**
