### PR TITLE
src/os/bluestore/BlueStore.cc: Use static_cast<uint64_t> fix for 32bit

### PR DESCRIPTION
**Pull request by a16bitsysop**
Fixes: https://tracker.ceph.com/issues/54415

~~if ppc64 is not excluded it has an unrelated failure in the alpine CI:
https://gitlab.alpinelinux.org/a16bitsysop/aports/-/jobs/646635#L1177~~

Signed-off-by: Duncan Bellamy <dunk@denkimushi.com>

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [x] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [x] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [x] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by a16bitsysop** [comment]
Not sure what has changed, but building with apache arrow now gives the error linked  unless ppc64 exclusion is removed.

**Comment by a16bitsysop** [comment]
jenkins retest this please

**Comment by a16bitsysop** [comment]
jenkins retest this please

**Comment by a16bitsysop** [comment]
jenkins retest this please

**Comment by tchaikov** [comment]
jenkins test make check

**Comment by ifed01** [comment]
jenkins test make check

**Comment by tchaikov** [comment]
> 
> It shouldn't change anything for 64bit as `extents_bytes_left` is already `uint64_t`:
> 

agreed. just wanted to note this down, in case we find more occurrences of this failure in other jenkins make check runs.

**Review by tchaikov — APPROVED** [review]

**Comment by tchaikov** [comment]
jenkins test make check

**Comment by tchaikov** [comment]
jenkins test make check

**Comment by tchaikov** [comment]
rebased onto master HEAD, and pushed to https://shaman.ceph.com/builds/ceph/wip-pr-45185-kefu/6190f90a5d5718688465f04854c1a256b931a98f/

once it builds , will merge this change.

**Pull request merged**
