### PR TITLE
qa/distros: remove centos/rhel8 and ubuntu20.04 from supported distros

### PR DESCRIPTION
**Pull request by cbodley**
the S release will drop support for these distros, so stop testing them on main. as discussed on dev@ceph.io

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by cbodley** [comment]
note that RHEL 8 is still present in `qa/distros/supported-random-distro$/rhel_latest.yaml`. this should be removed too, but nobody has added RHEL 9 yet

**Review by batrick — APPROVED** [review]

**Comment by cbodley** [comment]
i found that several suites still have symlinks to these old distro files:
> qa/suites/fs/verify/distro/rhel_8.yaml                                         
qa/suites/fs/mixed-clients/distro/rhel_8.yaml
qa/suites/fs/workload/0-rhel_8.yaml

i'll go through and change any that aren't upgrade tests to use the {distro}_latest.yaml instead

**Comment by cbodley** [comment]
several of the upgrade suites had broken symlinks to `qa/distros/supported/*.yaml`, so i replaced those with links under `qa/distros/all/`

**Review by alimaredia — APPROVED** [review]

**Review by idryomov — COMMENTED** [review]
Not clear why `rbd` label is present, but since I got here... ;)

- What about things like `qa/distros/single-container-host.yaml` which specify:
  ```
  os_type: centos
  os_version: "8.stream"
  ```

- `qa/distros/supported-all-distro` degenerated into just Ubuntu.  Should CentOS be re-added there?

- What is the difference between `qa/distros/supported` and `qa/distros/supported-all-distro`?  If none, it would be nice to ditch one of them while at it.

**Comment by cbodley** [comment]
> * What about things like `qa/distros/single-container-host.yaml` which specify:
>   os_type: centos
>   os_version: "8.stream"

my only objective here is to stop building/testing ceph packages for these old distros. i'll leave any decisions about container host distros to folks that maintain a cephadm suite

> * What is the difference between `qa/distros/supported` and `qa/distros/supported-all-distro`?  If none, it would be nice to ditch one of them while at it.

thanks, i added a commit to replace `qa/distros/supported-all-distro` with `qa/distros/supported`

**Review by idryomov — APPROVED** [review]

**Comment by ljflores** [comment]
Rados approved: https://tracker.ceph.com/projects/rados/wiki/MAIN#httpstrellocomcPuCOnhYL1841-wip-yuri5-testing-2023-10-02-1105-old-wip-yuri5-testing-2023-09-27-0959

**Comment by ljflores** [comment]
However, @cbodley I do see some centos 8 stream jobs that were scheduled in the run: https://pulpito.ceph.com/yuriw-2023-10-02_20:49:32-rados-wip-yuri5-testing-2023-10-02-1105-distro-default-smithi/

Can you confirm whether the results here worked as intended? If so, feel free to merge.

**Comment by ljflores** [comment]
@yuriw don't merge this; let Casey respond to the above comment ^

**Comment by ljflores** [comment]
@cbodley it scheduled centos 8 stream, as opposed to centos 8 which I see you removed. I think it did work as expected.

**Comment by cbodley** [comment]
> * What about things like qa/distros/single-container-host.yaml which specify:
os_type: centos
os_version: "8.stream"

@ljflores it scheduled lots of rados/cephadm jobs using centos8 and rhel as the container host, but i chose not to touch container hosts as discussed above. i also see some rados/thrash-old-clients jobs that pulled in `qa/distros/container-hosts/centos_8.stream_container_tools.yaml`

but now that i look at those logs, i see that even the cephadm jobs are installing ceph packages. when we stop building packages for these old distros, those jobs will start to fail

**Comment by ljflores** [comment]
@cbodley I see; so does that mean this PR needs further modifications?

**Comment by cbodley** [comment]
> @cbodley I see; so does that mean this PR needs further modifications?

@ljflores i'd rather follow up on container host stuff in a separate pr. i'm willing to switch centos 8->9 in those yaml files for testing, but would need someone else to debug and fix any issues that uncovers

**Comment by yuriw** [comment]
@ljflores @cbodley can this be merged?

**Comment by cbodley** [comment]
i've opened https://github.com/ceph/ceph/pull/53901 to hopefully address the issue with container hosts

**Pull request merged**
