### PR TITLE
doc/rados/operations/pg-states: fix PG state names, part 2

### PR DESCRIPTION
**Pull request by smithfarm**
Follow-up on 7f8b40fc4664856998d204adcf092c16cbc933dd

See @jcsp review https://github.com/ceph/ceph/pull/21520#pullrequestreview-114316433

References: https://tracker.ceph.com/issues/24923
Signed-off-by: Nathan Cutler <ncutler@suse.com>

### CODE REVIEW

**Comment by smithfarm** [comment]
Too bad there's no `uber-nit` label :-)

**Comment by smithfarm** [comment]
@joscollin I think it would be good to document the `unknown` state, but I don't know exactly how to describe it. Do you?

**Comment by liewegas** [comment]
"unknown" means ceph-mgr hasn't yet received any information about the PG's state from an OSD since mgr started up.

**Comment by smithfarm** [comment]
Thanks @liewegas ! Added a commit.

**Pull request merged**
