### PR TITLE
crimson/osd: don't get recovery read lock in PGRecvery::on_local_recover()

### PR DESCRIPTION
**Pull request by xxhdx1985126**
Signed-off-by: Xuehan Xu <xxhdx1985126@gmail.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by xxhdx1985126** [comment]
jenkins test make check

**Comment by cyx1231st** [comment]
There is another messenger test still alive:
```
...
INFO  2020-12-18 04:36:44,731 [shard 0] ms - test_v2_protocol: start local TestPeer at v2:127.0.0.1:9013/0...
ERROR 2020-12-18 04:36:44,750 [shard 0] ms - FailoverTestPeer: there is another instance running at v2:127.0.0.1:9013/0
```

Need to get the log from that test to understand why.

**Comment by xxhdx1985126** [comment]
> There is another messenger test still alive:
> 
> ```
> ...
> INFO  2020-12-18 04:36:44,731 [shard 0] ms - test_v2_protocol: start local TestPeer at v2:127.0.0.1:9013/0...
> ERROR 2020-12-18 04:36:44,750 [shard 0] ms - FailoverTestPeer: there is another instance running at v2:127.0.0.1:9013/0
> ```
> 
> Need to get the log from that test to understand why.

Um... I've just rerun the test, the log might be lost...

**Comment by cyx1231st** [comment]
@xxhdx1985126 np, that log doesn't contain any useful information for debugging.

**Comment by tchaikov** [comment]
@xxhdx1985126 hi xuehan, could you please elaborate a little bit in the commit message to explain the rationale of this change?

**Comment by tchaikov** [comment]
jenkins test docs

**Comment by tchaikov** [comment]
@xxhdx1985126 i rebased your change against master.

**Comment by xxhdx1985126** [comment]
@tchaikov all done:-) please take a look again.

**Review by tchaikov — APPROVED** [review]

**Comment by tchaikov** [comment]
jenkins test docs

**Pull request merged**
