### PR TITLE
jewel: msg: set close on exec flag

### PR DESCRIPTION
**Pull request by asheplyakov**
http://tracker.ceph.com/issues/16585

### CODE REVIEW

**Comment by smithfarm** [comment]
**Note: this PR is targeting the 10.2.8 release - not to be merged until v10.2.7 tag is added!**

@tchaikov This PR was included in the rados run at http://tracker.ceph.com/issues/19538#note-4 which had the following results:

Of 227 total jobs:

* 222 passed on first try
* 3 passed on second try
* remaining 2 are problematic

(see http://tracker.ceph.com/issues/19538#note-4 for details)

Do you think this run is sufficient to merge this PR once the v10.2.7 tag has been added?

**Comment by smithfarm** [comment]
@tchaikov Regarding the failures, @jdurgin wrote at #13212: "Of the failures, the only one I think is real is the valgrind one - it's detected what looks to be a leak of a message, and of async messenger's connection." 

Log, e.g.: http://qa-proxy.ceph.com/teuthology/smithfarm-2017-04-09_20:57:12-rados-wip-jewel-backports-distro-basic-smithi/1005553/teuthology.log

Could that one be related to this PR?

**Comment by tchaikov** [comment]
@smithfarm

IMO, this run is sufficient to merge this PR once we tag 10.2.7. and i don't think this PR is related to the leaks reported by valgrind.

**Comment by smithfarm** [comment]
@tchaikov Thanks - can you click on the review, then I'll merge.

**Comment by tchaikov** [comment]
@smithfarm sorry, forgot to approve this PR!

**Pull request merged**
