### PR TITLE
[DNM] luminous: Robustly Notify Cache

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/24965
http://tracker.ceph.com/issues/24967

### CODE REVIEW

**Comment by cbodley** [comment]
ping @adamemerson

**Comment by smithfarm** [comment]
ping @adamemerson

**Comment by smithfarm** [comment]
I'm inclined to just close this one - luminous is pretty old to be backporting such features to.

**Comment by adamemerson** [comment]
I agree wholeheartedly with not backporting features.

**Pull request closed without merging**
