### PR TITLE
Xio fixes

### PR DESCRIPTION
**Pull request by roidayan**

### CODE REVIEW

**Comment by roidayan** [comment]
seems like a problem with the build environment?

```
checking for cython... no
configure: error: in `/home/jenkins-build/build/workspace/ceph-pull-requests':
configure: error: cython not found
See `config.log' for more details
Build step 'Execute shell' marked build as failure
```

**Comment by roidayan** [comment]
Hi,

any comments about this pull request?

Thanks,
Roi

**Comment by cbodley** [comment]
all 4 fixes look good to me

**Comment by mattbenjamin** [comment]
looks good to me

**Comment by roidayan** [comment]
thanks. can we get this merged then?

**Pull request merged**
