### PR TITLE
common: Remove the runtime dependency on lsb_release

### PR DESCRIPTION
**Pull request by badone**
With modern releases we should be able to make do with the call to
os_release_parse only which uses /etc/os-release which should be available on
most (all?) releases we currently support. this then allows us to remove the
runtime dependency which pulls in several other packages and would be nice to
avoid.

Fixes: http://tracker.ceph.com/issues/17425
Signed-off-by: Brad Hubbard bhubbard@redhat.com

### CODE REVIEW

**Comment by alfredodeza** [comment]
test this please

**Comment by badone** [comment]
The error seems unrelated. If it fails again will rebase this tomorrow as suggested by @alfredodeza 

Thanks mate :)

**Comment by liewegas** [comment]
:+1:

**Comment by ktdreyer** [comment]
:+1:

**Comment by yuriw** [comment]
http://pulpito.ceph.com/yuriw-2016-10-26_22:43:11-rados-wip-yuri-testing2_2016_10_27-distro-basic-smithi/

**Pull request merged**
