### PR TITLE
osd: replace mclock subop opclass w/ rep_op opclass; combine duplicated code

### PR DESCRIPTION
**Pull request by ivancich**
The OSD subops were replaced with replication ops (i.e., MSG_OSD_REPOP
and MSG_OSD_REPOPREPLY) in jewel. mClock incorrectly used them as an
op class rather than the newer replication ops. This fixes that and
places eight ops into the repop class -- MSG_OSD_REPOP,
MSG_OSD_REPOPREPLY, MSG_OSD_PG_UPDATE_LOG_MISSING,
MSG_OSD_PG_UPDATE_LOG_MISSING_REPLY, MSG_OSD_EC_WRITE,
MSG_OSD_EC_WRITE_REPLY, MSG_OSD_EC_READ, and MSG_OSD_EC_READ_REPLY.

This alo removes dupliated code related to op classes in
mClockOpClassQueue and mClockClientQueue and combines into
mClockOpClassSupport.

The three configuration options
osd_op_queue_mclock_osd_subop_{res,wgt,lim} have also been replaced
with osd_op_queue_mclock_osd_rep_op_{res,wgt,lim}.

Signed-off-by: J. Eric Ivancich <ivancich@redhat.com>

### CODE REVIEW

**Comment by ivancich** [comment]
Here are some of my runs with a rados suite tailored to choose mclock_opclass or mclock_client over wpq.

Rados suite:
http://pulpito.ceph.com/ivancich-2017-10-09_18:18:06-rados-wip-mclock-repops-bitmap-test---basic-smithi/

Re-run of failures and deaths:
http://pulpito.ceph.com/ivancich-2017-10-10_14:18:25-rados-wip-mclock-repops-bitmap-test---basic-smithi/

**Comment by tchaikov** [comment]
i am still reviewing it..

**Comment by ivancich** [comment]
@tchaikov Thanks, Kefu.

**Comment by ivancich** [comment]
Given the amount of changes due to the rebase, currently redoing my testing. Added DNM label for this process.

**Comment by ivancich** [comment]
@tchaikov I believe I've addressed all of your concerns. Please re-review.

**Comment by yuriw** [comment]
[wip-yuri3-testing-2017-10-19-1558](https://trello.com/c/HySY0rJX/183-wip-yuri3-testing-2017-10-19-1558)

**Comment by yuriw** [comment]
ready for merge

**Comment by liewegas** [comment]
hrm, needs rebase

**Pull request merged**
