### PR TITLE
Namespace buffer

### PR DESCRIPTION
**Pull request by stiopaa1**
common/buffer: changed buffer from class to namespace

Since the buffer only contained static functions it doesn't make sense
for it to be a class. Changing it to a namespace will allow
bufferlist, bufferptr and bufferhash to be forward declared.
This wasn't possible when they were nested classes.

Function declarations for
inc_total_alloc and
dec_total_alloc
were removed from the header file and changed to static, to simulate
the private access specifier, which they were under.

Moved the operators inside the buffer namespace to take advantage of
the Argument Dependent Lookup.

Moved typedefs to  buffer_fwd header file which we can include when
only the forward declarations are needed.

Since the buffer is not a class anymore all the instances of
using ceph::buffer
were removed.

Signed-off-by: Michal Jarzabek <stiopa@gmail.com>

### CODE REVIEW

**Comment by dachary** [comment]
@stiopaa1 could you please rebase and repush ? the bot failure is likely a false negative ( http://tracker.ceph.com/issues/13857 ).

**Comment by liewegas** [comment]
Nice cleanup, thanks!

**Comment by stiopaa1** [comment]
@tchaikov 
I have modified the code to include all the changes you proposed.

>@stiopaa1 i am a little bit concerned about the $(LIBCOMMON). seems we need some symbols offered by "buffer.cc" now? will this break the compatibility of existing clients linked against librados?

After adding CEPH_BUFFER_API to namespace buffer, we don't need to add linking to  $(LIBCOMMON) anymore.

**Comment by stiopaa1** [comment]
I have also found some more places where we can forward declare buffer, which I included as a new commit.

**Comment by tchaikov** [comment]
@stiopaa1 could you squash d99991f into af4b5df?

**Comment by stiopaa1** [comment]
@tchaikov 
done

**Comment by liewegas** [comment]
sorry, please rebase?

**Comment by stiopaa1** [comment]
@liewegas 
>sorry, please rebase?

done

**Comment by jdurgin** [comment]
Good news, I was wrong about this being an ABI break. Since the members of ceph are all private, it did not matter. Still needed the symlink for librados though - see #6863

**Comment by noahdesu** [comment]
:+1: thanks josh!

**Pull request merged**
