### PR TITLE
denc: support enums wider than 8 bits

### PR DESCRIPTION
**Pull request by cbodley**
the denc_traits specialization that supports enums looks like this:
```c++
struct denc_traits<
  T,
  std::enable_if_t<
    _denc::is_any_of<_denc::underlying_type_t<T>,
		     ceph_le64, ceph_le32, ceph_le16, uint8_t ...
```
however, an enum's underlying_type must be integral, so it's not possible for any of the ceph_le* types to match. for example, this:
```c++
enum class enum_class_16 : ceph_le16 {};
```
fails to compile with:
> underlying type ‘ceph_le16’ {aka ‘ceph_le\<short unsigned int\>’} of ‘enum_class_16’ must be an integral type

in order to support normal enums like this:
```c++
enum class enum_class_16 : uint16_t {};
```
we need a new denc_traits specialization that matches enums only, and maps its operations onto the traits of its underlying type. those traits themselves will convert to ceph_le\<T\> where necessary

### CODE REVIEW

**Comment by tchaikov** [comment]
http://pulpito.ceph.com/kchai-2020-03-03_13:02:55-rados-wip-kefu-testing-2020-03-03-1622-distro-basic-smithi/

**Comment by cbodley** [comment]
thanks @tchaikov!

**Comment by cbodley** [comment]
@dillaman @liewegas no encoding relies on this change yet, so i'm fine with reverting it for octopus if we don't have a fix

i can't tell yet why `int` would encode differently though. before and after this PR, i'd expect `T=int` to match these traits:
```c++
struct denc_traits<T, std::enable_if_t<!std::is_void_v<_denc::ExtType_t<T>>>>
```
because of this specialization:
```c++
template<typename T>
struct ExtType<T, std::enable_if_t<std::is_same_v<T, int32_t> ||
				   std::is_same_v<T, uint32_t>>> {
  using type = ceph_le32;
};
```

**Comment by dillaman** [comment]
It looks like the issue is that for my type `map<cls::rbd::MirrorImageStatusState, int>`, it's actually the enum that is being incorrectly encoded now. We have numerous enums that have helper `encode`/`decode` methods that encode them as `uint8_t`s, but with this PR, they are getting encoded as 4-byte integers instead of 1-byte. That is what is causing the apparent endian encoding weirdness since its reading 3 extra zero bytes from the incorrectly encoded enum.

**Comment by dillaman** [comment]
On the wire encoded `map` w/ this PR:
>  x /12xb 0x7fffe8004000
> 0x7fffe8004000:	0x01	0x00	0x00	0x00	0x00	0x00	0x00	0x00
> 0x7fffe8004008:	0x03	0x00	0x00	0x00
It should be this:
> 0x7fffe8004000:	0x01	0x00	0x00	0x00	0x00	0x03	0x00	0x00
> 0x7fffe8004008:	0x00

**Comment by cbodley** [comment]
ohh okay, those encode/decode overloads wouldn't be visible to the new denc_traits for is_enum_v

one option would be to change the underlying type of those enum definitions, ie:
```diff
-enum MirrorImageStatusState {
+enum MirrorImageStatusState : uint8_t {
```
and remove those overloads. what do you think?

**Comment by dillaman** [comment]
Safest thing to do for now is to revert this PR from Octopus. I think any true solution would need to ensure future users don't need to follow your explicit format above or it should throw a compilation error.

**Comment by liewegas** [comment]
see https://github.com/ceph/ceph/pull/33832

**Comment by cbodley** [comment]
postmortem of the regression:

`cls::rbd::MirrorImageStatusState` overloads encode/decode to cast to/from `uint8_t`:
```c++
// cls/rbd/cls_rbd_types.h
inline void encode(const MirrorImageStatusState &state, bufferlist& bl,
▸       ▸          uint64_t features=0)
{
  using ceph::encode;
  encode(static_cast<uint8_t>(state), bl);
}
```
this is being encoded in a `std::map<cls::rbd::MirrorImageStatusState, int>`. without this pull request, it was choosing this overload from encoding.h:
```c++
template<class T, class U, class Comp, class Alloc,
▸        typename t_traits, typename u_traits>
inline std::enable_if_t<!t_traits::supported ||
▸       ▸       ▸       !u_traits::supported>
  encode(const std::map<T,U,Comp,Alloc>& m, bufferlist& bl)
{ 
  __u32 n = (__u32)(m.size());
  encode(n, bl);
  for (auto p = m.begin(); p != m.end(); ++p) {
    encode(p->first, bl);
    encode(p->second, bl);
  }
}
```
`t_traits` is `denc_traits<MirrorImageStatusState>`, and denc_traits only matches 8-bit enums, so `t_traits::supported` was false. this function calls the right `encode()` overload from cls_rbd_types.h

this PR added denc_traits for all enums, so `supported` changed to true, and it instead matches these traits from denc.h:
```c++
template<typename A, typename B, typename ...Ts>
struct denc_traits<
  std::map<A, B, Ts...>,
  std::enable_if_t<denc_traits<A>::supported &&
▸       ▸          denc_traits<B>::supported>>
```
the encode() overload for these traits is instead calling `denc()` to encode `MirrorImageStatusState` as its underlying_type of `int`

**Comment by cbodley** [comment]
> I think any true solution would need to ensure future users don't need to follow your explicit format above or it should throw a compilation error.

in this case, an encode() overload is defined but didn't get called. it's difficult to turn that into a compilation error - and the PR's purpose is to _allow_ the compilation of encode()/decode() of enums without requiring custom overloads

for this to work, we'd need some way to guarantee that, for every type T, `encode(T, bl)` and `denc(T, bl)` produce the same encoding. we could potentially add dencoder-style tests for existing types, but that doesn't cover all future users

for now, i think the best we can do is move this support to encoding.h and leave denc.h unsupported. ie, adding templated overloads for encode/decode to support the general case, while overload resolution will still prefer the explicit overloads like cls::rbd::MirrorImageStatusState's. i raised a pr for that at https://github.com/ceph/ceph/pull/33854

**Pull request merged**
