### PR TITLE
mimic: mds: calculate load by checking self CPU usage

### PR DESCRIPTION
**Pull request by ukernel**
http://tracker.ceph.com/issues/26888

### CODE REVIEW

**Comment by smithfarm** [comment]
jenkins re-test this please

**Comment by smithfarm** [comment]
@batrick Please review (conflict resolution)

**Comment by yuriw** [comment]
[wip-yuri5-testing-2018-09-05-1625-mimic](https://trello.com/c/xwoIGoxK/390-wip-yuri5-testing-2018-09-05-1625-mimic)

**Comment by yuriw** [comment]
[wip-yuri5-testing-2018-09-11-2103-mimic](https://trello.com/c/WPo5t2WP/397-wip-yuri5-testing-2018-09-11-2103-mimic)

**Pull request merged**
