### PR TITLE
test/allocsim: ops scrapper arg parsing

### PR DESCRIPTION
**Pull request by pereman2**
```
fedora :: pere/scrapper-replayer/build 130 » ./bin/replayer -h
All options:

Options:
  -h [ --help ]                 produce help message
  -i arg (=input.txt)           Input file (output of op_scraper.py)
  --ceph-conf arg (=ceph.conf)  Path to ceph conf
  --io-depth arg (=64)          I/O depth
  --parser-threads arg (=16)    Number of parser threads
  --worker-threads arg (=16)    Number of I/O worker threads
  --pool arg (=test_pool)       Pool to use for I/O
```

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Review by aclamk — APPROVED** [review]

**Comment by pereman2** [comment]
jenkins test make check

**Comment by pereman2** [comment]
jenkins test make check

**Comment by ivancich** [comment]
@pereman2 : I'm getting shaman build errors as a result of this PR on ubuntu jammy default and centos 9 crimson.

For example:
```
/home/jenkins-build/build/workspace/ceph-dev-new-build/ARCH/x86_64/AVAILABLE_ARCH/x86_64/AVAILABLE_DIST/centos9/DIST/centos9/MACHINE_SIZE/gigantic/release/19.0.0-4814-gbe1388e0/rpm/el9/BUILD/ceph-19.0.0-4814-gbe1388e0/src/test/objectstore/allocsim/ops_replayer.cc:13:10: fatal error: rados/buffer_fwd.h: No such file or directory
   13 | #include <rados/buffer_fwd.h>
      |          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

**Comment by pereman2** [comment]
> @pereman2 : I'm getting shaman build errors as a result of this PR on ubuntu jammy default and centos 9 crimson.
> 
> For example:
> 
> ```
> /home/jenkins-build/build/workspace/ceph-dev-new-build/ARCH/x86_64/AVAILABLE_ARCH/x86_64/AVAILABLE_DIST/centos9/DIST/centos9/MACHINE_SIZE/gigantic/release/19.0.0-4814-gbe1388e0/rpm/el9/BUILD/ceph-19.0.0-4814-gbe1388e0/src/test/objectstore/allocsim/ops_replayer.cc:13:10: fatal error: rados/buffer_fwd.h: No such file or directory
>    13 | #include <rados/buffer_fwd.h>
>       |          ^~~~~~~~~~~~~~~~~~~~
> compilation terminated.
> ```

oh shit, fixing it rn

**Comment by pereman2** [comment]
@ivancich https://github.com/ceph/ceph/pull/58465 this should fix it

**Comment by cbodley** [comment]
@pereman2 any idea why this ops_replayer.cc isn't being built by 'make check'? ideally that would catch any compilation errors

**Comment by pereman2** [comment]
> @pereman2 any idea why this ops_replayer.cc isn't being built by 'make check'? ideally that would catch any compilation errors

no clue, must be missing something in cmake.

**Comment by pereman2** [comment]
fixed here https://github.com/ceph/ceph/pull/58462

**Pull request merged**
