### PR TITLE
squid: mgr/dashboard: fix gateways section error:”404 - Not Found RGW Daemon not found: None”

### PR DESCRIPTION
**Pull request by aaSharma14**
backport tracker: https://tracker.ceph.com/issues/68479

---

backport of https://github.com/ceph/ceph/pull/60101
parent tracker: https://tracker.ceph.com/issues/68376

this backport was staged using ceph-backport.sh version 16.0.0.6848
find the latest version at https://github.com/ceph/ceph/blob/main/src/script/ceph-backport.sh

### CODE REVIEW

**Review by afreen23 — APPROVED** [review]

**Comment by aaSharma14** [comment]
jenkins test make check

**Comment by aaSharma14** [comment]
jenkins render docs

**Comment by aaSharma14** [comment]
jenkins test docs

**Comment by aaSharma14** [comment]
jenkins test make check

**Pull request merged**
