### PR TITLE
os/bluestore: use iterator for erase() method directly

### PR DESCRIPTION
**Pull request by xiexingguo**

### CODE REVIEW

**Comment by ifed01** [comment]
Looks like there is duplicate write_onode call for _do_truncate and _do_clone_range too.

**Comment by ifed01** [comment]
I'm not completely sure if this duplication's worth fixing but I'd prefer to have ALL write_onode calls at the same level for the sake of uniformity, i.e. either at entry points (_zero, _truncate, _clone, etc) or at some underlying ones (_do_zero, _do_truncate, _do_clone_range, etc). Just IMHO though...

**Comment by xiexingguo** [comment]
@ifed01 I am with you.

Dropped that change.

**Comment by liewegas** [comment]
@ifed01 @xiaoxichen agreed on being consistent.  Probably _do_*....  in a handful of cases that will include a duplicate insert, but it's probably safer?  No strong preference though.

**Pull request merged**
