### PR TITLE
mgr: init() return when connection daemons failed && add some err info

### PR DESCRIPTION
**Pull request by renhwztetecs**
mgr: mgr::init() return when connection daemons failed 
 mgr/mgrstandby: display signal info 

Signed-off-by: huanwen ren ren.huanwen@zte.com.cn

### CODE REVIEW

**Comment by xiexingguo** [comment]
@renhwztetecs The patch fails the UT, please check.

**Comment by renhwztetecs** [comment]
retest this please

**Comment by renhwztetecs** [comment]
retest this please

**Comment by dachary** [comment]
jenkins test this please (no log)

**Pull request merged**
