### PR TITLE
docs: correct zone rm command in docs to zone delete

### PR DESCRIPTION
**Pull request by snosratiershad**
Signed-off-by: Salar Nosrati-Ershad <snosratiershad@gmail.com>

I've tested in latest ceph/daemon docker image in demo deployment and in a real cluster running Octopus version and the command `radosgw-admin zone rm` doesn't exists but there is a command `radosgw-admin zone delete`. I think it's a mistake in documentation because also `radosgw-amin zone delete` is never documented.

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [x] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by snosratiershad** [comment]
I force pushed the branch multiple times for my mistake in singing off the commit, sorry for that.

**Comment by snosratiershad** [comment]
I've missed one, added, and squashed.

**Comment by zdover23** [comment]
@djgalloway - https://readthedocs.org/projects/ceph/builds/17742208/ It looks like this is trying to interact with master instead of main. What gives?

@jdurgin  - Can you confirm the technical accuracy of the "radosgw-admin zone delete" command and the nonexistence in software of the "radosgw-admin zone rm" command? I don't want to make a change like this without a blessing ex cathedra.

**Comment by snosratiershad** [comment]
@zdover23,
just for additional comment: about "radosgw-admin zone delete" command, I've tested by my own and it works as well.

**Comment by djgalloway** [comment]
> @djgalloway - https://readthedocs.org/projects/ceph/builds/17742208/ It looks like this is trying to interact with master instead of main. What gives?
Screenshot at 2022-08-15 11-36-51

**Comment by snosratiershad** [comment]
@djgalloway, looks like it's my fault, I've used "sync fork" and looks it's just synced the master branch of ceph repository with my fork. going to merge it.

**Comment by snosratiershad** [comment]
just rebased and squashed due removing sync merge commit.

**Comment by snosratiershad** [comment]
please don't merge it, seems like I broked it, I'm going to remake changes.

**Comment by snosratiershad** [comment]
sorry for review requests, it's because my mistake in rebasing. I've tired to make dis PR again and I saw that it was fixed in main branch after syninc. so I'm going to close it.

**Pull request closed without merging**
