### PR TITLE
os/bluestore/KernelDevice: For buffer mode no need do bufferlist::rebuid

### PR DESCRIPTION
**Pull request by majianpeng**
Signed-off-by: Jianpeng Ma <jianpeng.ma@intel.com>

### CODE REVIEW

**Comment by yuyuyu101** [comment]
need rebase

**Comment by majianpeng** [comment]
@yuyuyu101  updated.

**Comment by yuyuyu101** [comment]
LGTM

**Comment by liewegas** [comment]
:+1:

**Pull request merged**
