### PR TITLE
qa/suites/rados: jewel cleanup

### PR DESCRIPTION
**Pull request by neha-ojha**
This follows https://github.com/ceph/ceph/pull/34541, where we have changed mon_osd_initial_require_min_compat_client from jewel to luminous.

Fixes: https://tracker.ceph.com/issues/45242
Signed-off-by: Neha Ojha <nojha@redhat.com>

### CODE REVIEW

**Comment by jdurgin** [comment]
can get rid of hammer from thrash-old-clients too

**Comment by neha-ojha** [comment]
> can get rid of hammer from thrash-old-clients too

done.

**Comment by yuriw** [comment]
[wip-yuri4-testing-2020-04-25-0009-master](https://trello.com/c/b1ICydf9/884-wip-yuri4-testing-2020-04-25-0009-master)

**Comment by tchaikov** [comment]
jenkins test docs

**Pull request merged**
