### PR TITLE
octopus: librbd: ensure that thread pool lock is held when processing throttled IOs

### PR DESCRIPTION
**Pull request by dillaman**
## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Review by trociny — APPROVED** [review]
LGTM

**Comment by trociny** [comment]
Passed my limited testing locally and on teuthology.

**Comment by smithfarm** [comment]
@dillaman I guess everyone knows you would not inadvertently fix a bug in octopus without ensuring that it is fixed in master. Still, in the spirit of setting a rules-following example for others and providing comfort to git history perusers who might doubt, could you add some reassuring sentence to the commit messages?

**Comment by dillaman** [comment]
> @dillaman I guess everyone knows you would not inadvertently fix a bug in octopus without ensuring that it is fixed in master. Still, in the spirit of setting a rules-following example for others and providing comfort to git history perusers who might doubt, could you add some reassuring sentence to the commit messages?

From the tracker ticket:

> Direct fix to octopus branch (all refactored in master-branch) with backport to nautilus branch.

**Comment by smithfarm** [comment]
> From the tracker ticket:
> 
> > Direct fix to octopus branch (all refactored in master-branch) with backport to nautilus branch.

Sure, but I thought the idea was to make this information available (directly) to folks perusing the git history so they don't have to go looking for it?

Do you think we should change the line in https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst#cherry-picking-rules which currently says:

"if a commit could not be cherry-picked from master, the commit message must explain why that was not possible"

to something like

"if a commit could not be cherry-picked from master, the commit message **or a tracker issue comment or a GitHub PR description or a GitHub PR comment** must explain why that was not possible"

?

**Comment by dillaman** [comment]
I definitely think that saying "the commit message must explain" is actually incorrect (a bug is a bug so why would anyone care historically looking at git logs that a specific commit was directly applied to a historical branch). Instead, I would think the goal is to ensure that when reviewing the GitHub PR there is a good rationale for why it's being directly fixed instead of cherry-picked.

**Comment by smithfarm** [comment]
I inherited this rule from Loic. I hesitate to speak for him, but I believe the rationale was that, in the past, regressions happened because bugs got fixed directly in a stable branch, but not in master. Later, when users upgraded their clusters, BOOM the bugs were back, but of course nobody initially knew why. They had to conduct a forensic investigation of the git history to find out what happened, and one way to do that is to zero in on all commits that aren't cherry-picks. But how to tell the "good" ones from the "bad"? That, I believe, is where this rule came from.

To me, it sounds like you're saying we don't need that, because we can rely on reviewers to never make a mistake? But, reviewers can and do make mistakes. For example, plenty of times I've seen reviewers overlook that the base branch of the PR they are reviewing is not master. So a direct fix getting inadvertently applied to a stable branch, and not to master, is not as unlikely as it may seem!

**Comment by smithfarm** [comment]
Anyway, I do wish we could find a set of rules that all the leads, at least, could get behind.

**Comment by yuriw** [comment]
[wip-yuri5-testing-2020-09-28-1009-octopus](https://trello.com/c/tcP64BXW/1025-wip-yuri5-testing-2020-09-28-1009-octopus)

**Pull request merged**
