### PR TITLE
doc: release notes for hammer v0.94.2 (draft)

### PR DESCRIPTION
**Pull request by theanalyst**
Draft release notes containing the current commits in hammer branch

### CODE REVIEW

**Comment by dachary** [comment]
looks good to me. I propose they are merged right now, just to be extra sure they won't be overlooked. What do you think ?

**Comment by dachary** [comment]
@theanalyst could you please rebase ?

**Comment by dachary** [comment]
@theanalyst ping ?

**Comment by theanalyst** [comment]
@dachary rebased

**Comment by dachary** [comment]
@theanalyst would you have time to update them with what was merged last week in hammer ? The only one potentially missing is https://github.com/ceph/ceph/pull/4568

**Comment by dachary** [comment]
> The only one potentially missing is #4568

This sentence is cryptic at best ;-) Let me clarify: the current hammer branch does not have #4568. If you run your script on hammer, it won't display anything related to it. But if it is merged in the next 24/48 hours, it will need to be included in the release notes. So if you work on release notes before it is merged, it may be missing from the release notes. But if you work on the release notes after it is meged, it won't be missing.

**Comment by theanalyst** [comment]
ah wouldn't they be populated in hammer-backports? ie I'll run it against that branch & copy over the diff?

**Comment by dachary** [comment]
@theanalyst at this point all but #4568 have been merged in hammer. I think you can safely run it against hammer and include #4568 to get a complete set. There may be a few commits merged into hammer that are not in hammer-backports (the old fashioned way ;-).

**Pull request merged**
