### PR TITLE
osd: more fixes for incorrectly dirtying info; resend reply for duplicated scrub-reserve req

### PR DESCRIPTION
**Pull request by xiexingguo**

### CODE REVIEW

**Comment by xiexingguo** [comment]
@liewegas More fixes

**Comment by liewegas** [comment]
How would the scrub message get lost "due to a network problem"?  The osd <-> osd message passing is lossless

**Comment by liewegas** [comment]
The rest looks right to me.  Can we just drop that one commit?

**Comment by xiexingguo** [comment]
Sure, dropped.

**Pull request merged**
