### PR TITLE
qa/suites/rados/singleton/all/thrash-eio: whitelist 'slow request'

### PR DESCRIPTION
**Pull request by liewegas**
Signed-off-by: Sage Weil <sage@redhat.com>

presumably due to https://github.com/ceph/ceph/pull/33328

### CODE REVIEW

**Comment by sseshasa** [comment]
@liewegas There are a bunch of tests within qa that whitelist 'SLOW_OPS' but not 'slow request'. Would it make sense to include 'slow request' as well to those tests to avoid seeing stray failures? I can take that up in a new PR or alternatively they could be added to this PR itself.

**Comment by liewegas** [comment]
Yeah, we should do the same everywhere.  Feel free to push to this branch or do a separate pr

**Comment by sseshasa** [comment]
> Yeah, we should do the same everywhere. Feel free to push to this branch or do a separate pr

@liewegas Sure, I have pushed those specific files that whitelist 'SLOW_OPS' but not 'slow request' to your branch.

**Comment by liewegas** [comment]
@sseshasa +1 this pr?

**Comment by sseshasa** [comment]
> @sseshasa +1 this pr?

LGTM

**Pull request merged**
