### PR TITLE
test/crimson: two fixes of unittest_seastar_echo

### PR DESCRIPTION
**Pull request by tchaikov**
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by tchaikov** [comment]
@cyx1231st could you take a look? seems the bind and listen functionality of crimson msgr has been broken for a while -- at least it is not able to talk to the v2 msgr now.

**Comment by cyx1231st** [comment]
Fixed crimson-msgr in https://github.com/cyx1231st/ceph/tree/wip-fix-echo.
But `test_alien_echo.cc` is linked with custom-built common libraries for seastar, so async-msgr still can't work now.

Maybe need to split this file to link with seastar/non-seastar libraries?

**Comment by tchaikov** [comment]
> Maybe need to split this file to link with seastar/non-seastar libraries?

this is nasty.. we cannot. because the symbols with the same name will conflict with each other. we will need to face this problem when integrating bluestore in alien world.

**Comment by tchaikov** [comment]
> so async-msgr still can't work now.

could you be more specific what is missing to enable async msgr to work?

@cyx1231st could you send a PR from your changes? probably we can continue the work based on it.

**Comment by cyx1231st** [comment]
> could you be more specific what is missing to enable async msgr to work?

I saw segment fault related to ConfigProxy when try to run async-msgr, that's why I think we need to split the async-msgr implementation and link it with non-seastar libraries.

>could you send a PR from your changes?

Done.

> do you think it makes sense to split this file to link with seastar/non-seastar libraries and have two separated executables for the 2nd use case?

I think so. Or we have to figure out how to co-exist seastar and non-seastar libraries first.

**Comment by tchaikov** [comment]
closing in favor of #26419

**Pull request closed without merging**
