### PR TITLE
mimic: c-v extend batch

### PR DESCRIPTION
**Pull request by jan--f**
This is the backport for the batch extension to support explicit device lists. Also included are a few commits that haven't been backported and were needed for clean cherry-picks.

Fixes: http://tracker.ceph.com/issues/40919

### CODE REVIEW

**Comment by jan--f** [comment]
jenkins test ceph-volume batch all

**Comment by jan--f** [comment]
jenkins test ceph-volume batch all

**Comment by jan--f** [comment]
jenkins test ceph-volume batch all

**Comment by alfredodeza** [comment]
@jan--f this doesn't have a link to a master PR because it is grouping a few commits that weren't together right?

It is OK if you want to pursue the backporting this way, but in the past we've seen that it was problematic to track what went where if backports weren't done in order. That is: every PR in master has a corresponding backport to other branches.

Again, it is OK if you want to do it this way, I am just pointing out that it might get painful to track commits back to their original PR if they are grouped.

@andrewschoen maybe you have some other thoughts on this? (my comments should not prevent this from moving forward)

**Comment by jan--f** [comment]
jenkins test ceph-volume batch all

**Comment by jan--f** [comment]
@alfredodeza yeah, sady backporting was somewhat neglected for a while and its tough to gather all backports. Trying to get to working state on this branch for now, will see how to resolve this more cleanly.

**Comment by jan--f** [comment]
hmm seeing failing tests on master too....looking into it.

**Comment by alfredodeza** [comment]
this is odd, something may have changed for the NVMe setup. The way this works is by creating a sparse file and using the NVME fabric tooling to create a device recognized by the Kernel. If you look at the output, we do even list it to check if it came up alright:

```
/dev/nvme0n1     afed1d952161a36e     Linux                                    1          16.11  GB /  16.11  GB    512   B +  0 B   3.10.0-9
```

What I think is happening here is that /dev/nvme0n1 exists but /dev/nvme1n1 does not. We create two IIRC, and I am not sure what is missing here (or if anything changed to add/remove /dev/nvme1n1)

**Comment by jan--f** [comment]
jenkins test ceph-volume batch all

**Comment by jan--f** [comment]
k, found the missing test backports. Thx for your pointers guys.

**Pull request merged**
