### PR TITLE
jewel: disable LTTng-UST in openSUSE builds

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/17082

### CODE REVIEW

**Comment by smithfarm** [comment]
test this please

**Comment by smithfarm** [comment]
test this please

**Comment by smithfarm** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;pwbkHKpg&#x2F;1870-fix-16937-disable-lttng-ust-in-opensuse-builds"> Fix #16937: disable LTTng-UST in openSUSE builds</a>

**Comment by smithfarm** [comment]
@dachary Could this be merged for 10.2.4 ?

**Comment by dachary** [comment]
It passed upgrade tests with failures that are, I think, unrelated http://tracker.ceph.com/issues/17487#note-7

**Pull request merged**
