### PR TITLE
doc/mgr/dashboard: Make feature toggle formatting consistent

### PR DESCRIPTION
**Pull request by bluikko**
Format dashboard feature toggle list consistently so
that the "nfs" toggle is formatted same way as other
toggles, without misleading formatting.

Additionally changed one letter in the same file to
improve capitalization.

Fixes: #54543
Signed-off-by: Ville Ojamo <14869000+bluikko@users.noreply.github.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [x] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [x] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Review by anthonyeleven — CHANGES_REQUESTED** [review]
Always love to see increased consistency!

LGTM, but please change the PR/commit title to

`doc/mgr/dashboard: Make feature toggle formatting consistent`

This is very much a nit; we prefer imperatives.

**Comment by bluikko** [comment]
> Always love to see increased consistency!
> 
> LGTM, but please change the PR/commit title to
> 
> `doc/mgr/dashboard: Make feature toggle formatting consistent`
> 

Done!  
Commit title & PR changed to the suggested phrase.

> This is very much a nit; we prefer imperatives.

Oh, agreed. Things like this absolutely do matter. I should have already remembered this point from the last time...

**Comment by bluikko** [comment]
While looking at this file, I wonder if the capitalization here could be improved:
```
- Its associated REST API endpoints will reject any further requests (404, Not Found Error).
```
With `Not Found Error` -> `Not Found error`.

**Comment by anthonyeleven** [comment]
> While looking at this file, I wonder if the capitalization here could be improved:
> 
> ```
> - Its associated REST API endpoints will reject any further requests (404, Not Found Error).
> ```
> 
> With `Not Found Error` -> `Not Found error`.

Hmm.  https://en.m.wikipedia.org/wiki/HTTP_404 doesn't capitalize this consistently.  That said, I would agree with your suggestion.

**Comment by anthonyeleven** [comment]
> > Always love to see increased consistency!
> > LGTM, but please change the PR/commit title to
> > `doc/mgr/dashboard: Make feature toggle formatting consistent`
> 
> Done! Commit title & PR changed to the suggested phrase.
> 
> > This is very much a nit; we prefer imperatives.
> 
> Oh, agreed. Things like this absolutely do matter. I should have already remembered this point from the last time...

Thanks - no problem.  It took me a few PRs to internalize it myself.

**Review by anthonyeleven — APPROVED** [review]

**Comment by anthonyeleven** [comment]
I've not yet merged in case you would like to change that capitalization.  Either way tag me when you're ready for me to merge.

**Comment by bluikko** [comment]
@anthonyeleven thanks for your comments.

Added a commit to change it to "Not Found error".  
Updated the PR to note this simple 1-letter change.

It could be debated that "Not Found" could be capitalized since it is the name of the error; however the same cannot be said of the word "error" which has nothing special about it. IMHO.

So either "Not Found error" or "not found error" would be more correct than the current capitalization.

**Comment by bluikko** [comment]
@anthonyeleven I had finished on this if you have time to review.

**Pull request closed without merging**
