### PR TITLE
luminous: core: Improve OSD startup time by only scanning for omap corruption once

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/21439

### CODE REVIEW

**Comment by dzafman** [comment]
The first 4 commits are also in ceph/ceph#17896

**Comment by liewegas** [comment]
rebase this?

**Comment by smithfarm** [comment]
@liewegas Rebased, thanks.

**Comment by smithfarm** [comment]
jenkins test docs

**Comment by smithfarm** [comment]
jenkins test docs

**Comment by liewegas** [comment]
jenkins test docs

**Comment by theanalyst** [comment]
Passed a teuthology run at http://tracker.ceph.com/issues/21830#note-6 and will be merged when approved

**Pull request merged**
