### PR TITLE
pacific: qa: mds removed because trimming for too long with valgrind

### PR DESCRIPTION
**Pull request by batrick**
https://tracker.ceph.com/issues/49610
https://tracker.ceph.com/issues/49563

### CODE REVIEW

**Comment by yuriw** [comment]
@batrick pls rebase

--- pr 40091 --- pulling https://github.com/batrick/ceph.git branch i49610
remote: Enumerating objects: 49, done.
remote: Counting objects: 100% (49/49), done.
remote: Total 56 (delta 49), reused 49 (delta 49), pack-reused 7
Unpacking objects: 100% (56/56), done.
From https://github.com/batrick/ceph
 * branch                  i49610     -> FETCH_HEAD
Auto-merging src/mds/MDSDaemon.cc
Auto-merging src/common/options.cc
Auto-merging qa/tasks/ceph_manager.py
Auto-merging qa/suites/fs/verify/validater/valgrind.yaml
Adding qa/suites/fs/verify/distro/ubuntu/overrides.yaml
Adding qa/suites/fs/verify/distro/ubuntu/latest.yaml
Adding qa/suites/fs/verify/distro/ubuntu/.qa
Adding qa/suites/fs/verify/distro/ubuntu/+
Adding qa/suites/fs/verify/distro/rhel_8.yaml
Adding qa/suites/fs/verify/distro/centos_8.yaml
Adding qa/suites/fs/verify/distro/.qa
Adding qa/suites/fs/verify/distro/$
CONFLICT (file/directory): There is a directory with name qa/suites/fs/verify/distro in 9beed82e1cb5f5045d9b7d28b307744d3b165c14. Adding qa/suites/fs/verify/distro as qa/suites/fs/verify/distro~HEAD
Automatic merge failed; fix conflicts and then commit the result.
Traceback (most recent call last):
  File "/root/master/src/script/build-integration-branch", line 99, in <module>
    assert not r
AssertionError

**Comment by batrick** [comment]
> @batrick pls rebase
> 
> --- pr 40091 --- pulling https://github.com/batrick/ceph.git branch i49610
> remote: Enumerating objects: 49, done.
> remote: Counting objects: 100% (49/49), done.
> remote: Total 56 (delta 49), reused 49 (delta 49), pack-reused 7
> Unpacking objects: 100% (56/56), done.
> From https://github.com/batrick/ceph
> 
>     * branch                  i49610     -> FETCH_HEAD
>       Auto-merging src/mds/MDSDaemon.cc
>       Auto-merging src/common/options.cc
>       Auto-merging qa/tasks/ceph_manager.py
>       Auto-merging qa/suites/fs/verify/validater/valgrind.yaml
>       Adding qa/suites/fs/verify/distro/ubuntu/overrides.yaml
>       Adding qa/suites/fs/verify/distro/ubuntu/latest.yaml
>       Adding qa/suites/fs/verify/distro/ubuntu/.qa
>       Adding qa/suites/fs/verify/distro/ubuntu/+
>       Adding qa/suites/fs/verify/distro/rhel_8.yaml
>       Adding qa/suites/fs/verify/distro/centos_8.yaml
>       Adding qa/suites/fs/verify/distro/.qa
>       Adding qa/suites/fs/verify/distro/$
>       CONFLICT (file/directory): There is a directory with name qa/suites/fs/verify/distro in [9beed82](https://github.com/ceph/ceph/commit/9beed82e1cb5f5045d9b7d28b307744d3b165c14). Adding qa/suites/fs/verify/distro as qa/suites/fs/verify/distro~HEAD
>       Automatic merge failed; fix conflicts and then commit the result.
>       Traceback (most recent call last):
>       File "/root/master/src/script/build-integration-branch", line 99, in 
>       assert not r
>       AssertionError

There are no conflicts now. It's conflicting with another PR you're building. Can you list them for me to look at?

**Comment by yuriw** [comment]
@batrick 

--- done. these PRs were included:
https://github.com/ceph/ceph/pull/40079 - pacific: mds: don't start purging inodes in the middle of recovery
https://github.com/ceph/ceph/pull/40080 - pacific: qa: slow metadata ops during scrubbing
https://github.com/ceph/ceph/pull/40081 - pacific: qa: racy session evicted check
https://github.com/ceph/ceph/pull/40082 - pacific: qa: rank_freeze prevents failover on some tests
https://github.com/ceph/ceph/pull/40083 - pacific: mds: define CephFS errors that replace standard errno values
https://github.com/ceph/ceph/pull/40084 - pacific: qa: run fs:verify with tcmalloc
https://github.com/ceph/ceph/pull/40085 - pacific: pybind/cephfs: DT_REG and DT_LNK values are wrong
https://github.com/ceph/ceph/pull/40086 - pacific: mon/MonCap: `fs authorize` generates unparseable cap for file system name containing '-'
https://github.com/ceph/ceph/pull/40087 - pacific: qa: ffsb workload: PG_AVAILABILITY|PG_DEGRADED warnings
https://github.com/ceph/ceph/pull/40089 - pacific: qa: file system deletion not complete because starter fs already destroyed
https://github.com/ceph/ceph/pull/40090 - pacific: snap-schedule doc
https://github.com/ceph/ceph/pull/40092 - pacific: client: allow looking up snapped inodes by inode number+snapid tuple
https://github.com/ceph/ceph/pull/40093 - pacific: nautilus: qa: "Assertion `cb_done' failed."

**Comment by batrick** [comment]
@yuriw it was conflicting with #40084. I merged them into this PR. Try rebuilding.

**Comment by yuriw** [comment]
test this please

**Comment by batrick** [comment]
retest this please

**Comment by batrick** [comment]
jenkins test make check

**Review by yuriw — APPROVED** [review]
Reviewed-by: Patrick Donnelly <pdonnell@redhat.com>

**Pull request merged**
