### PR TITLE
mgr/cephadm: clear error message when resuming upgrade

### PR DESCRIPTION
**Pull request by adk3798**
Fixes: https://tracker.ceph.com/issues/56714

Signed-off-by: Adam King <adking@redhat.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [x] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Review by phlogistonjohn — APPROVED** [review]
I had to carefully read the tracker issue to understand how adding this line fixed this issue.

This is where I usually recommend a comment, or a more detailed commit message explaining how this change fixes the problem. In this case I would prefer the latter.  I'll approve, but I'd love to see you update it with an improved commit message (or comment) if it's not too much of a hassle.

**Comment by adk3798** [comment]
> I had to carefully read the tracker issue to understand how adding this line fixed this issue.
> 
> This is where I usually recommend a comment, or a more detailed commit message explaining how this change fixes the problem. In this case I would prefer the latter. I'll approve, but I'd love to see you update it with an improved commit message (or comment) if it's not too much of a hassle.

I updated the commit message with a longer description of what we're doing here and why

**Comment by adk3798** [comment]
https://pulpito.ceph.com/adking-2022-07-30_00:56:25-orch:cephadm-wip-adk-testing-2022-07-29-1905-distro-default-smithi/

green

**Comment by adk3798** [comment]
jenkins test api

**Pull request merged**
