### PR TITLE
nautilus: doc: Improved dashboard feature overview

### PR DESCRIPTION
**Pull request by LenzGr**
Added some newly added features, improved wording.

Signed-off-by: Lenz Grimmer <lgrimmer@suse.com>
(cherry picked from commit f90c1113880d05159641b6923d6e09c489b7861a)

- [x] Updates documentation if necessary

### CODE REVIEW

**Comment by s0nea** [comment]
jenkins render docs

**Comment by votdev** [comment]
jenkins test make check

**Comment by p-na** [comment]
@votdev I wonder why need more reviews on this PR :thinking:

**Comment by votdev** [comment]
> @votdev I wonder why need more reviews on this PR thinking

At least 6 approving reviews are required to merge, currently we have 5.

**Pull request merged**
