### PR TITLE
test/dokan: Added ceph-dokan tests

### PR DESCRIPTION
**Pull request by stefan-chivu**
This PR adds the following:
- tests for ceph-dokan
- exposed ceph-dokan --win-vol-serial CLI optarg

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [x] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [x] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by vshankar** [comment]
Possibly an unrelated make check (arm64) failure. Should be good to merge.

**Comment by petrutlucian94** [comment]
jenkins test make check arm64

**Comment by petrutlucian94** [comment]
> Possibly an unrelated make check (arm64) failure. Should be good to merge.

For sure, I've noticed that the arm job is quite unstable. Those bits will only be compiled when targeting Windows.

I've triggered an arm recheck just to get that green mark :).

**Comment by stefan-chivu** [comment]
jenkins test make check arm64

**Comment by vshankar** [comment]
> For sure, I've noticed that the arm job is quite unstable. Those bits will only be compiled when targeting Windows.
> 
> I've triggered an arm recheck just to get that green mark :).

It's not a required check (arm64). Merging now...

**Review by vshankar — APPROVED** [review]

**Pull request merged**
