### PR TITLE
jewel: qa: use xfs instead of btrfs w/ filestore

### PR DESCRIPTION
**Pull request by tchaikov**
Fixes: http://tracker.ceph.com/issues/21150

### CODE REVIEW

**Comment by tchaikov** [comment]
hopefully fixes: http://tracker.ceph.com/issues/21150

see also #17847

**Comment by smithfarm** [comment]
jenkins test docs

**Comment by tchaikov** [comment]
@smithfarm and @jdurgin ping?

**Comment by smithfarm** [comment]
@tchaikov This PR was included in http://pulpito.front.sepia.ceph.com/smithfarm-2017-10-10_18:25:20-rados-wip-jewel-backports-distro-basic-smithi/ - it's somewhat less noisy, which is good, but still too noisy. If you can help analyze these failures, I would be grateful.

For a list of all PRs included see http://tracker.ceph.com/issues/21742#note-1

**Comment by tchaikov** [comment]
@smithfarm how's the base line look like? is it worse or better?

**Comment by smithfarm** [comment]
@tchaikov It looks like jewel is not included in the nightlies, so I pushed `wip-jewel-baseline` and will schedule a run.

**Comment by tchaikov** [comment]
@smithfarm thanks. in the meanwhile, i will check the test result tomorrow.

**Comment by smithfarm** [comment]
@tchaikov Here is the baseline: http://pulpito.ceph.com/smithfarm-2017-10-19_13:55:19-rados-wip-jewel-baseline-distro-basic-smithi/

**Comment by tchaikov** [comment]
@smithfarm regarding to http://pulpito.ceph.com/smithfarm-2017-10-10_18:25:20-rados-wip-jewel-backports-distro-basic-smithi/, i haven't analysed all the failures: 


- 1721826: the OSDs with capacity of over 16G are over 85% full. needs to check further
- 1721849: ceph_test_rados_api_aio --gtest_filter=LibRadosAio.RoundTripPP2. fails with -2 (-ENOENT). need to investigate further

will continue analyzing/debugging tomorrow.

**Comment by tchaikov** [comment]
rerunning the failed tests at http://pulpito.ceph.com/kchai-2017-10-31_11:11:14-rados-wip-jewel-backports-reloaded-distro-basic-mira/

**Comment by tchaikov** [comment]
retest this please.

**Comment by tchaikov** [comment]
- http://pulpito.ceph.com/kchai-2017-11-03_05:56:44-rados-wip-jewel-backports-reloaded-distro-basic-mira/
- http://pulpito.ceph.com/kchai-2017-11-03_12:19:08-rados-wip-jewel-backports-reloaded-distro-basic-mira/
- http://pulpito.ceph.com/kchai-2017-11-03_12:20:04-rados-wip-jewel-backports-reloaded-distro-basic-mira/

the test failure is addressed by https://github.com/ceph/teuthology/pull/1123

**Comment by tchaikov** [comment]
@smithfarm i merged the core PRs and a rgw PR (#18080, again, sorry, i should not have merged it!) involved in my rados test run. as they are 1) approved by PTL and/or the original author 2) passed the rados qa suite.

**Comment by smithfarm** [comment]
@tchaikov Thanks

**Pull request merged**
