### PR TITLE
[DNM] mimic: Robustly Notify Cache

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/24964
http://tracker.ceph.com/issues/24966

### CODE REVIEW

**Comment by smithfarm** [comment]
jenkins re-test this please

**Comment by smithfarm** [comment]
```
/home/jenkins-build/build/workspace/ceph-pull-requests/src/rgw/rgw_rados.cc: In member function 'int RGWRados::initialize()':
/home/jenkins-build/build/workspace/ceph-pull-requests/src/rgw/rgw_rados.cc:4715:16: error: request for member 'get_val' in '((RGWRados*)this)->RGWRados::cct->CephContext::_conf', which is of pointer type 'md_config_t*' (maybe you meant to use '->' ?)
     cct->_conf.get_val<double>("rgw_inject_notify_timeout_probability");
                ^~~~~~~
/home/jenkins-build/build/workspace/ceph-pull-requests/src/rgw/rgw_rados.cc:4715:24: error: expected primary-expression before 'double'
     cct->_conf.get_val<double>("rgw_inject_notify_timeout_probability");
                        ^~~~~~
/home/jenkins-build/build/workspace/ceph-pull-requests/src/rgw/rgw_rados.cc:4716:35: error: request for member 'get_val' in '((RGWRados*)this)->RGWRados::cct->CephContext::_conf', which is of pointer type 'md_config_t*' (maybe you meant to use '->' ?)
   max_notify_retries = cct->_conf.get_val<uint64_t>("rgw_max_notify_retries");
                                   ^~~~~~~
/home/jenkins-build/build/workspace/ceph-pull-requests/src/rgw/rgw_rados.cc:4716:51: error: expected primary-expression before '>' token
   max_notify_retries = cct->_conf.get_val<uint64_t>("rgw_max_notify_retries");
                                                   ^
/home/jenkins-build/build/workspace/ceph-pull-requests/src/rgw/rgw_rados.cc: In member function 'int RGWRados::robust_notify(const string&, ceph::bufferlist&)':
/home/jenkins-build/build/workspace/ceph-pull-requests/src/rgw/rgw_rados.cc:12620:18: error: 'using bufferlist = class ceph::buffer::list {aka class ceph::buffer::list}' has no member named 'cbegin'; did you mean 'begin'?
     auto p = rbl.cbegin();
                  ^~~~~~
                  begin
src/rgw/CMakeFiles/rgw_a.dir/build.make:1434: recipe for target 'src/rgw/CMakeFiles/rgw_a.dir/rgw_rados.cc.o' failed
```

**Comment by yuriw** [comment]
[wip-yuri4-testing-2018-09-04-1643-mimic](https://trello.com/c/0a9ZOm7W/387-wip-yuri4-testing-2018-09-04-1643-mimic)

**Comment by cbodley** [comment]
there's been more discussion on this at https://github.com/ceph/ceph/pull/23100#issuecomment-413192740, and it sounds like this can exacerbate a race to apply cache updates. please hold off merging until we have a followup fix

**Comment by cbodley** [comment]
ping @adamemerson

**Comment by smithfarm** [comment]
@adamemerson agreed to close out the luminous backport on the grounds that it's a feature and backporting features to older stable branches is, in general, something to be avoided if possible.

I'll close this now on the assumption that the same justification applies in this case as well.

**Pull request closed without merging**
