### PR TITLE
Wip luminous rgw bucketmv

### PR DESCRIPTION
**Pull request by mdw-at-linuxbox**
https://tracker.ceph.com/issues/36178

---

This is a backport of https://github.com/ceph/ceph/pull/23994 to luminous.
Also see tracker http://tracker.ceph.com/issues/35885
Commits here include,
5a72d6de0f rgw: RGWBucket::link supports tenant
b99d2a6220 Add several types to ceph-dencoder.
53246a2751 Add "--bucket-new-name" option to radosgw-admin.
bd7e930985 rgw: bucket link: Add ability to name bucket w/ different tenant.
9de55e2b79 rgw: bucket link: simplify use of get bucket info.
7f7746f02a rgw: bucket link: use data from bucket_info to rewrite bucket_endpoint.
d766d5eed2 rearrange / simplify RGWBucket::link logic - start bucket move support
be78d12b33 rgw: bucket link: base "bucket move" (tenant id only)
33b1475dd2 rgw: bucket link: "bucket move"; handle bucket names too.
61d9b1524c rgw: bucket link: "bucket move" documentation changes

Differences from the commit series for master,
ADDED 5a72d6de0f (rgw: RGWBucket::link supports tenant) is a backport of a pr against master that had not been backported, see http://tracker.ceph.com/issues/22666 https://github.com/ceph/ceph/pull/23119
REMOVED 8297f4cfc7 already existed in luminous as d2bdea8e7b (rgw: making implicit_tenants backwards compatible.) also see https://github.com/ceph/ceph/pull/22363 https://github.com/ceph/ceph/pull/22378)

Note that reviewers found some nits in the commit series against master, if those are addressed that may need to be propagated here as well.

### CODE REVIEW

**Comment by smithfarm** [comment]
@mdw-at-linuxbox I did read your PR description - I added the review just to make sure the PR doesn't get merged into luminous prematurely.

**Comment by cbodley** [comment]
@mdw-at-linuxbox some test coverage in qa/tasks/radosgw_admin.py would be a big help in validating these backports

**Comment by smithfarm** [comment]
The upstream PR got rebased in April 2019, so none of the "cherry-picked from commit ..." lines are valid anymore.

**Comment by fritchie** [comment]
Is this backport still planned for Luminous?

**Comment by mattbenjamin** [comment]
@fritchie hi, I don't know if there are plans to merge it, I'll ask in today's standup.  (Luminous is regarded as EOL upstream.)

**Comment by smithfarm** [comment]
At this extremely late point in the Luminous release cycle, the chance that we would merge a feature backport such as this would seem to be approaching zero.

If someone disagrees, feel free to reopen!

**Pull request closed without merging**
