### PR TITLE
mgr/dashboard: Spelling mistake in host-form Network address field

### PR DESCRIPTION
**Pull request by avanthakkar**
Fixes: https://tracker.ceph.com/issues/53215
Signed-off-by: Avan Thakkar <athakkar@redhat.com>

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
- Component impact
  - [x] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests
- Teuthology
  - [ ] Completed teuthology run
  - [x] No teuthology test necessary (e.g., documentation)

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Review by nizamial09 — APPROVED** [review]
I went through the form a million times before and this is the first time I am noticing this! Now that I saw this I can't unsee it. Nice catch @avanthakkar

**Comment by avanthakkar** [comment]
> I went through the form a million times before and this is the first time I am noticing this! Now that I saw this I can't unsee it. Nice catch @avanthakkar

Well I missed it too! Thanks to Sunil

**Review by epuertat — APPROVED** [review]
Usually in a bugfix you would be expected to add some unit test, but how to unit test spelling? Maybe we can introduce a spell checker (like [this](url), [this](https://www.npmjs.com/package/spellchecker-cli), [this](https://www.npmjs.com/package/hdis), or any other one you may know)?

**Review by aaSharma14 — APPROVED** [review]

**Comment by avanthakkar** [comment]
jenkins test dashboard cephadm

**Comment by avanthakkar** [comment]
> Usually in a bugfix you would be expected to add some unit test, but how to unit test spelling? Maybe we can introduce a spell checker (like [this](url), [this](https://www.npmjs.com/package/spellchecker-cli), [this](https://www.npmjs.com/package/hdis), or any other one you may know)?

Yes, I'll add a tracker for it

**Comment by avanthakkar** [comment]
> > Usually in a bugfix you would be expected to add some unit test, but how to unit test spelling? Maybe we can introduce a spell checker (like [this](url), [this](https://www.npmjs.com/package/spellchecker-cli), [this](https://www.npmjs.com/package/hdis), or any other one you may know)?
> 
> Yes, I'll add a tracker for it

Done https://tracker.ceph.com/issues/53233

**Pull request merged**
