### PR TITLE
[WIP] octopus: mgr/dashboard: allow getting fresh inventory data from the orchestrator

### PR DESCRIPTION
**Pull request by shyukri**
Dependencies:
- [ ] #37456
  - [ ] https://tracker.ceph.com/issues/47019

backport tracker: https://tracker.ceph.com/issues/47471

---

backport of https://github.com/ceph/ceph/pull/36845
parent tracker: https://tracker.ceph.com/issues/44803

this backport was staged using ceph-backport.sh version 15.1.1.389
find the latest version at https://github.com/ceph/ceph/blob/master/src/script/ceph-backport.sh

### CODE REVIEW

**Comment by bk201** [comment]
Please backport this after https://tracker.ceph.com/issues/47019 is backported..too many dependencies :(.

**Comment by votdev** [comment]
What is the status here?

**Comment by shyukri** [comment]
jenkins test make check

**Comment by shyukri** [comment]
jenkins test ceph dashboard

**Comment by shyukri** [comment]
I won't be working on this PR. Should i close it?

**Comment by bk201** [comment]
> I won't be working on this PR. Should i close it?

@shyukri I'll continue your work, please keep it open. Thanks!

**Comment by smithfarm** [comment]
@votdev Can you do this backport? I gather it was blocked by #38888 but that one has since been merged.

**Comment by votdev** [comment]
jenkins retest this please

**Comment by votdev** [comment]
jenkins retest this please

**Comment by votdev** [comment]
Superseded by https://github.com/ceph/ceph/pull/41387.

**Pull request closed without merging**
