### PR TITLE
mgr/dashboard: drop container image name and id from services list

### PR DESCRIPTION
**Pull request by avanthakkar**
Dropping Container image name and id columns from the Services list as `orch ls` no more contains that info [after this change](https://github.com/ceph/ceph/pull/40736)

Fixes: https://tracker.ceph.com/issues/50889
Signed-off-by: Avan Thakkar <athakkar@redhat.com>

Before:
revert

After:
Screenshot from 2021-05-20 04-00-54

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by avanthakkar** [comment]
As `orch ls` o/p no more provides the container image id & name should we hide those columns or just remove it completely from code? I've just hidden for now.

**Comment by pereman2** [comment]
I'm not a fan of having dead code so I would remove it tbh.

**Comment by avanthakkar** [comment]
> I'm not a fan of having dead code so I would remove it tbh.

Yes I agree with you. And anyways even if someone wants to use tohse columns it will show empty, so I guess better remove it. Thanks @pereman2 !

**Comment by avanthakkar** [comment]
jenkins test dashboard

**Review by nizamial09 — APPROVED** [review]
@avanthakkar You can add the PR or commit link where this got dropped in the description.

**Review by pereman2 — APPROVED** [review]

**Review by Waadkh7 — APPROVED** [review]

**Review by epuertat — APPROVED** [review]
Great @avanthakkar ! Let's go with this, as it needs to be fixed asap. But we should go next with this follow-up tracker: https://tracker.ceph.com/issues/50323

**Pull request merged**
