### PR TITLE
jewel: msg/simple/Pipe: error decoding addr

### PR DESCRIPTION
**Pull request by asheplyakov**
http://tracker.ceph.com/issues/18108

### CODE REVIEW

**Comment by asheplyakov** [comment]
The build failed due to flake8, however this patch does not touch any python code

**Comment by dachary** [comment]
@asheplyakov could you please rebase against jewel-next and repush ? This jewel branch is getting ready for 10.2.4 and new backports should be against jewel-next instead to be in 10.2.5. Thanks !

**Comment by dachary** [comment]
jenkins test this please (jenkins failed to verify submodules & no logs available)

**Comment by smithfarm** [comment]
@liewegas This passed a rados run at http://tracker.ceph.com/issues/17851#note-45 with some (few, unrelated) failures. OK to merge?

**Comment by smithfarm** [comment]
This passed another rados run at http://tracker.ceph.com/issues/17851#note-53

**Pull request merged**
