### PR TITLE
jewel: tests: clone workunit using the branch specified by task

### PR DESCRIPTION
**Pull request by tchaikov**
http://tracker.ceph.com/issues/19517

### CODE REVIEW

**Comment by tchaikov** [comment]
@yuriw sorry, yet another known issue, on jewel this time.

**Comment by smithfarm** [comment]
@tchaikov The first commit appears to be a cherry-pick of c1309fbef300a062138ac40eb5d3e5081b833072 but it doesn't explicitly say so in the commit message?

**Comment by smithfarm** [comment]
Jenkins retest this please

**Comment by smithfarm** [comment]
**Note: this PR is targeting the 10.2.8 release - not to be merged until v10.2.7 tag is added!**

@tchaikov This PR was included in the rados run at http://tracker.ceph.com/issues/19538#note-4 which had the following results:

Of 227 total jobs:

* 222 passed on first try
* 3 passed on second try
* remaining 2 are problematic

(see http://tracker.ceph.com/issues/19538#note-4 for details)

Do you think this run is sufficient to merge this PR once the v10.2.7 tag has been added?

**Pull request merged**
