### PR TITLE
qa/rgw: teach rgw.py to create an optional realm

### PR DESCRIPTION
**Pull request by cbodley**
some test cases may depend on having a realm present, so allow the rgw task's yaml to specify a realm, zonegroup, and zone to create

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Comment by cbodley** [comment]
the stuff in the rgw task worked, but apparently caused ceph_test_librgw_file to crash. lab outages are preventing me from finding the test results atm

**Comment by cbodley** [comment]
> the stuff in the rgw task worked, but apparently caused ceph_test_librgw_file to crash. lab outages are preventing me from finding the test results atm

ceph_test_librgw_file_nfsns is crashing consistently on shutdown when it's running in a realm, ex. http://qa-proxy.ceph.com/teuthology/cbodley-2024-03-07_22:07:59-rgw:verify-main-distro-default-smithi/7584823/teuthology.log

**Comment by cbodley** [comment]
i had enabled the realm in the rgw/verify just to test the changes to qa/tasks/rgw.py. i moved it to rgw/notifications to work around the ceph_test_librgw_file crash and the results look better:

https://pulpito.ceph.com/cbodley-2024-03-07_23:09:13-rgw:notifications-main-distro-default-smithi/

**Comment by yuvalif** [comment]
> i had enabled the realm in the rgw/verify just to test the changes to qa/tasks/rgw.py. i moved it to rgw/notifications to work around the ceph_test_librgw_file crash and the results look better:
> 
> https://pulpito.ceph.com/cbodley-2024-03-07_23:09:13-rgw:notifications-main-distro-default-smithi/

it did not ran the http + basic tests (the dead test). could you please rerun that?

**Comment by cbodley** [comment]
> it did not ran the http + basic tests (the dead test). could you please rerun that?

it did run for over 12 hours before "hit max job timeout". all of the setup succeeded, but it got stuck after running for about 20 minutes. teuthology.log stopped logging any output, but the [radosgw log](http://qa-proxy.ceph.com/teuthology/cbodley-2024-03-07_23:09:13-rgw:notifications-main-distro-default-smithi/7584828/remote/smithi078/log/rgw.ceph.client.0.log.gz) keeps going. it was around that time that it logged a bunch of curl errors like:

> ERROR: curl error: Failure when receiving data from the peer req_data->error_buf=Recv failure: Connection reset by peer
> rgw notify: WARNING: push entry: 0/122541 to endpoint: http://172.21.15.78:17442 failed. error: -5 (will retry)

rerun in https://pulpito.ceph.com/cbodley-2024-03-11_14:46:52-rgw:notifications-main-distro-default-smithi/

**Comment by cbodley** [comment]
^ rerun passed

**Review by yuvalif — APPROVED** [review]

**Pull request merged**
