### PR TITLE
mds, client: fix locking around handle_conf_change

### PR DESCRIPTION
**Pull request by jcsp**
Depends on: https://github.com/ceph/ceph/pull/7295 (commits also included in this branch)

### CODE REVIEW

**Comment by jcsp** [comment]
Tests: https://github.com/ceph/ceph-qa-suite/pull/805

**Comment by gregsfortytwo** [comment]
Please review this and the tests, @ukernel

**Comment by gregsfortytwo** [comment]
And mark them as needs-qa if they're good! :)

**Comment by ukernel** [comment]
looks good.

I found a related bug  https://github.com/ceph/ceph/pull/7343

**Comment by gregsfortytwo** [comment]
http://pulpito.ceph.com/gregf-2016-01-26_15:35:20-fs-greg-fs-testing-126---basic-mira/

**Pull request merged**
