### PR TITLE
ceph-disk: default to bluestore. remove experimental status.

### PR DESCRIPTION
**Pull request by liewegas**

### CODE REVIEW

**Comment by jdurgin** [comment]
retest this please

**Comment by jdurgin** [comment]
looks like the 'make check' tests need fixing with this

**Comment by dachary** [comment]
if that can wait until I return, I'll fix it (june 1st)

**Comment by wjwithagen** [comment]
@dachary 
Hi Loic, 
Could you make that piece of code dependant on 'not FREEBSD' ??
Because that is not there yet. Somebody offered to work on the AIO stuff, but that has not materialized yet.

**Comment by liewegas** [comment]
retest this please

**Comment by tchaikov** [comment]
this PR addresses http://pulpito.ceph.com/kchai-2017-05-30_05:52:48-upgrade-wip-mgr-stats-kefu---basic-mira/1244283/
```
2017-05-30T05:58:08.539 INFO:teuthology.orchestra.run.mira082:Running: 'sudo MALLOC_CHECK_=3 adjust-ulimits ceph-coverage /home/ubuntu/cephtest/archive/coverage ceph-osd --cluster
ceph --mkfs --mkkey -i 0 --monmap /home/ubuntu/cephtest/ceph.monmap'
2017-05-30T05:58:08.654 INFO:teuthology.orchestra.run.mira082.stderr:2017-05-30 05:58:08.651691 7fa2a358b980 -1 *** experimental feature 'bluestore' is not enabled ***
2017-05-30T05:58:08.654 INFO:teuthology.orchestra.run.mira082.stderr:This feature is marked as experimental, which means it
2017-05-30T05:58:08.655 INFO:teuthology.orchestra.run.mira082.stderr: - is untested
2017-05-30T05:58:08.655 INFO:teuthology.orchestra.run.mira082.stderr: - is unsupported
2017-05-30T05:58:08.655 INFO:teuthology.orchestra.run.mira082.stderr: - may corrupt your data
2017-05-30T05:58:08.655 INFO:teuthology.orchestra.run.mira082.stderr: - may break your cluster is an unrecoverable fashion
2017-05-30T05:58:08.655 INFO:teuthology.orchestra.run.mira082.stderr:To enable this feature, add this to your ceph.conf:
2017-05-30T05:58:08.655 INFO:teuthology.orchestra.run.mira082.stderr:  enable experimental unrecoverable data corrupting features = bluestore
2017-05-30T05:58:08.655 INFO:teuthology.orchestra.run.mira082.stderr:
2017-05-30T05:58:08.655 INFO:teuthology.orchestra.run.mira082.stderr:2017-05-30 05:58:08.651706 7fa2a358b980 -1 unable to create object store
```

**Comment by dachary** [comment]
jenkins retest this please

**Comment by dachary** [comment]
@liewegas working on it at https://github.com/ceph/ceph/pull/15437

**Pull request closed without merging**
