### PR TITLE
bash_completion: Do not auto complete obsolete and hidden cmds 

### PR DESCRIPTION
**Pull request by kotreshhr**
This patch fixes two things.

1. Do not auto complete obsolete and hidden commands
2. sub command completions often failed due to the
   use of associative arrays which does not keep the
   order. Hence used non-associative arrays.

Fixes: https://tracker.ceph.com/issues/45141
Signed-off-by: Kotresh HR <khiremat@redhat.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by kotreshhr** [comment]
@tchaikov @ajarr please take a look

**Comment by tchaikov** [comment]
> Obsolete bash completions

this is a little bit misleading. what i'd put is something like

> do not add autocomplete obsoleted commands

**Comment by kotreshhr** [comment]
> > Obsolete bash completions
> 
> this is a little bit misleading. what i'd put is something like
> 
> > do not autocomplete obsoleted commands

Done

**Comment by tchaikov** [comment]
> > > Obsolete bash completions
> > 
> > 
> > this is a little bit misleading. what i'd put is something like
> > > do not autocomplete obsoleted commands
> 
> Done

@kotreshhr this is not addressed.

**Comment by kotreshhr** [comment]
> > > > Obsolete bash completions
> > > 
> > > 
> > > this is a little bit misleading. what i'd put is something like
> > > > do not autocomplete obsoleted commands
> > 
> > 
> > Done
> 
> @kotreshhr this is not addressed.

@tchaikov Sry, my bad, had fixed only in headings. Done

**Comment by tchaikov** [comment]
jenkins test make check

**Comment by kotreshhr** [comment]
> not sure, but should we disallow auto completing deprecated commands?

I some where read that deprecated means feature is available but no support or update is provided as better alternative is available. Going by that definition, it's ok to allow auto completion. Thoughts?

**Comment by ajarr** [comment]
> > not sure, but should we disallow auto completing deprecated commands?
> 
> I some where read that deprecated means feature is available but no support or update is provided as better alternative is available. Going by that definition, it's ok to allow auto completion. Thoughts?

Yeah, per docs, " **Deprecated:** Use the ``.. deprecated::`` directive when CLI usage, a feature or a configuration setting is no longer preferred or will be discontinued."  So should deprecated commands be suggested? 

I'm OK with the current fix. I wanted to make sure you considered the 'deprecated' case as well.

**Comment by tchaikov** [comment]
- http://pulpito.ceph.com/kchai-2020-04-30_13:24:45-rados-wip-kefu-testing-2020-04-30-1835-distro-basic-smithi/
- http://pulpito.ceph.com/kchai-2020-05-01_04:25:09-rados-wip-kefu-testing-2020-04-30-1912-distro-basic-smithi/

**Pull request merged**
