### PR TITLE
mds/MDSMap: add 'fsid' set to MDSMap

### PR DESCRIPTION
**Pull request by renhwztetecs**
To track which cluster of MDSMap by the 'fsid';
add display max_mds when run "ceph mds stop"

Signed-off-by: huanwen ren <ren.huanwen@zte.com.cn>

### CODE REVIEW

**Comment by jcsp** [comment]
MDSMaps are implicitly scoped to an FSID: whenever you read one from a mon you know what mon you're talking to, so you know the FSID.  What's the use case for embedding the FSID in the MDSMap?

**Comment by renhwztetecs** [comment]
yeh
but if we use command “ceph mds dump > ***.txt” export to file，unable to identify the mdsmap belonging to the Cluster through the file.  especially in the maintenance of Multi cluster

**Comment by jcsp** [comment]
Sorry, I don't think this makes sense.  We have lots of commands, and most of them don't inline the FSID in the output.  If you have tools that require it, I would suggest running a 'status' before your other command so that the output contains the fsid for you.

**Comment by renhwztetecs** [comment]
thanks for your reviews

**Pull request closed without merging**
