### PR TITLE
docs: <orch osd spec> is no longer present

### PR DESCRIPTION
**Pull request by jschmid1**
Signed-off-by: Joshua Schmid <jschmid@suse.de>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by jschmid1** [comment]
jenkins render docs

**Comment by jschmid1** [comment]
jenkins test docs

**Comment by jschmid1** [comment]
jenkins render docs

**Comment by jschmid1** [comment]
jenkins test signed

**Comment by tchaikov** [comment]
jenkins test signed

**Comment by tchaikov** [comment]
@djgalloway 
```
[ceph-pr-commits] $ /bin/bash /tmp/jenkins6987278719877369076.sh
++ mktemp -td venv.XXXXXXXXXX
+ TEMPVENV=/tmp/venv.RO1TDTPWdu
+ VENV=/tmp/venv.RO1TDTPWdu/bin
+ cd /home/jenkins-build/build/workspace/ceph-pr-commits/ceph
+ git rev-parse --verify '2df66a26b2ffa15b3abb0c196028a7f7e327aad8^2'
b38bc14525460e0bec7829774d2385b62d6c8742
++ git diff --name-only '2df66a26b2ffa15b3abb0c196028a7f7e327aad8^1...2df66a26b2ffa15b3abb0c196028a7f7e327aad8^2'
+ files=doc/mgr/orchestrator.rst
+ echo -e 'changed files:\ndoc/mgr/orchestrator.rst'
changed files:
doc/mgr/orchestrator.rst
++ echo doc/mgr/orchestrator.rst
++ grep -v '^doc/'
++ wc -l
+ '[' 0 -gt 0 ']'
+ echo 'Only the doc/ dir changed.  No need to check for signed commits.'
Only the doc/ dir changed.  No need to check for signed commits.
+ exit 0
Recording test results
ERROR: Step ?Publish JUnit test result report? failed: Test reports were found but none of them are new. Did leafNodes run? 
For example, /home/jenkins-build/build/workspace/ceph-pr-commits/report.xml is 50 min old

[Checks API] No suitable checks publisher found.
Setting status of b38bc14525460e0bec7829774d2385b62d6c8742 to FAILURE with url https://jenkins.ceph.com/job/ceph-pr-commits/33877/ and message: 'one or more commits in this PR are not signed
 '
Using context: Signed-off-by
Finished: FAILURE
```

still broken. reverted your change manually.

**Comment by tchaikov** [comment]
jenkins test signed

**Review by asettle — APPROVED** [review]

**Review by mgfritch — APPROVED** [review]

**Pull request merged**
