### PR TITLE
.github: detect GPL license in PRs

### PR DESCRIPTION
**Pull request by epuertat**
Tested with [PR](https://github.com/epuertat/ceph/pull/2) in [fork](https://github.com/epuertat/ceph/actions/runs/11345807054/job/31553505960?pr=2):

image

It uses an [action that simply matches text in PR diff](https://github.com/JJ/github-pr-contains-action) (supports regex).

BTW, it fails in this very PR because it contains the text 😆 

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [x] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Comment by batrick** [comment]
Ah, your test fails in this PR because the test contains the string it is searching for. :laughing:

**Comment by epuertat** [comment]
> I also wonder if we should require a license header for all new files, with LGPLv2.1?

That's [one of the requirements for Gold level](https://www.bestpractices.dev/en/projects/2220?criteria_level=2#section_other) in the OpenSSF Best Practices:
> The project MUST include a license statement in each source file. This MAY be done by including the following inside a comment near the beginning of each file: [SPDX-License-Identifier: [SPDX license expression for project]](https://spdx.dev/ids/#how). [license_per_file] 

> This MAY also be done by including a statement in natural language identifying the license. The project MAY also include a stable URL pointing to the license text, or the full license text. Note that the criterion license_location requires the project license be in a standard location. See this SPDX tutorial for more information about SPDX license expressions. Note the relationship with [copyright_per_file](https://www.bestpractices.dev/en/projects/2220?criteria_level=2#copyright_per_file), whose content would typically precede the license information.

The Linux kernel community has also adopted this practice: https://lwn.net/Articles/739183/.

We could require users to provide the `SPDX-License-Identifier` in source files.

**Review by batrick — APPROVED** [review]
Let's do it!

**Comment by batrick** [comment]
@epuertat do you want to set the "Required" bit on the new test?

**Comment by epuertat** [comment]
> @epuertat do you want to set the "Required" bit on the new test?

Yup, that's the plan.

**Pull request merged**
