### PR TITLE
mon: do not try and "deactivate" the last MDS

### PR DESCRIPTION
**Pull request by jcsp**
Fixes: #10862
Signed-off-by: John Spray <john.spray@redhat.com>

### CODE REVIEW

**Comment by jcsp** [comment]
Can't usefully test this in cephtool/test.sh unfortunately, because that's run without an MDS so deactivate would always fail anyway

**Comment by liewegas** [comment]
Should we run it with an MDS?

**Comment by gregsfortytwo** [comment]
It would presumably make the "unit tests" take even longer to wait for an MDS to run through setup. :/ I think this is the first one we've had that requires an MDS running to test the monitor-side behavior of the command so maybe we should just wait until we have more of those and build them another test that runs with MDS?

**Comment by jcsp** [comment]
@gregsfortytwo Yeah -- we can add test for MDS-requiring mon commands in ceph-qa-suite later when doing http://tracker.ceph.com/issues/10792

**Pull request merged**
