### PR TITLE
quincy: pybind/mgr/pg_autoscaler: fix warn when not too few pgs

### PR DESCRIPTION
**Pull request by kamoltat**
Problem:

when `pg_num_final` is equal to `pg_num_target`
we get too many PGs warnings in ceph health while
`warn` mode in the autoscaler.

Solution:

Get rid of `else` condition and add an
`elif p['pg_num_final'] < p['pg_num_target']`
instead

Fixes: https://tracker.ceph.com/issues/61570

Backporting relevant commits from main PR:

https://github.com/ceph/ceph/pull/51923

Signed-off-by: Kamoltat <ksirivad@redhat.com> 

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Review by ljflores — APPROVED** [review]

**Comment by ljflores** [comment]
jenkins test make chck

**Comment by kamoltat** [comment]
Make check fail is unrelated, cephadm stuff:

```
        def _crush_location_checker(ctx, fsid, daemon_type, daemon_id, container, uid, gid, **kwargs):
            print(container.args)
            raise Exception(' '.join(container.args))
    
        _deploy_daemon.side_effect = _crush_location_checker
    
>       with pytest.raises(Exception, match='--set-crush-location database=a'):
E       AssertionError: Regex pattern did not match.
E        Regex: '--set-crush-location database=a'
E        Input: "Failed to extract uid/gid for path /var/lib/ceph: Failed command: /usr/bin/docker run --rm --ipc=host --stop-signal=SIGTERM --ulimit nofile=1048576 --net=host --entrypoint stat --init -e CONTAINER_IMAGE=quay.io/ceph/ceph:v17 -e NODE_NAME=braggi17.front.sepia.ceph.com -e CEPH_USE_RANDOM_NONCE=1 quay.io/ceph/ceph:v17 -c %u %g /var/lib/ceph: docker: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?.\nSee 'docker run --help'.\n"

tests/test_cephadm.py:343: AssertionError
```

**Comment by kamoltat** [comment]
jenkins test make check

**Comment by kamoltat** [comment]
jenkins test make chck

**Comment by yuriw** [comment]
jenkins test make check

**Comment by yuriw** [comment]
@kamoltat pls merge when all checks passed
ref: https://trello.com/c/vB5XcEdi

**Comment by vshankar** [comment]
@ljflores leave it for you to merge.

**Pull request merged**
