### PR TITLE
rados: Add cleanup message with time to rados bench output

### PR DESCRIPTION
**Pull request by vumrao**
rados: Add cleanup message with time to rados bench output

Fixes: http://tracker.ceph.com/issues/15704

Signed-off-by: Vikhyat Umrao <vumrao@redhat.com>

### CODE REVIEW

**Comment by vumrao** [comment]
Total time run:         40.201307
Total writes made:      1537
Write size:             8192
Object size:            8192
Bandwidth (MB/sec):     0.298692
Stddev Bandwidth:       0.134115
Max bandwidth (MB/sec): 0.53125
Min bandwidth (MB/sec): 0.0390625
Average IOPS:           38
Stddev IOPS:            17
Max IOPS:               68
Min IOPS:               5
Average Latency(s):     1.30695
Stddev Latency(s):      0.567084
Max latency(s):         3.0933
Min latency(s):         0.078425
Cleaning up (deleting benchmark objects) <------------------------- New Message 
Clean up completed and total clean up time :3.253823 <--------- New Message

**Comment by dzafman** [comment]
I think you should move all the new timing and output into ObjBencher::aio_bench().  The ObjBencher::clean_up(int num_objects...) has multiple purposes.  It can be called multiple times like when --all is used with rados cleanup.  For example, I'm constructing what I think would happen with the current code:

# rados -p test -N nspace1 bench 10 write --no-cleanup
# rados -p test -N nspace2 bench 10 write --no-cleanup
# rados -p test --all cleanup
Cleaning up (deleting benchmark objects) 
Clean up completed and total clean up time :###### 
Cleaning up (deleting benchmark objects)
Clean up completed and total clean up time :######

# rados purge test --yes-i-really-really-mean-it
Warning: using slow linear search
Cleaning up (deleting benchmark objects)
Removed ## objects
Clean up completed and total clean up time :#####

As purge isn't benchmark related but uses clean_up_slow() that code should be removed from there.

**Comment by vumrao** [comment]
@dzafman thank you for your inputs. sure I will verify it and will test and send the next patch set.

**Comment by vumrao** [comment]
@dzafman With new patch version -
~~~
$./rados -p rbd  bench 10  write -b 8192 -t 50                               
Maintaining 50 concurrent writes of 8192 bytes to objects of size 8192 for up to 10 seconds or 0 objects
Object prefix: benchmark_data_ceph.node.1_28603
  sec Cur ops   started  finished  avg MB/s  cur MB/s last lat(s)  avg lat(s)
    0       0         0         0         0         0           -           0
    1      50       119        69  0.539035  0.539062    0.855881    0.390985
    2      50       137        87   0.33982  0.140625     1.17201    0.586786
    3      50       185       135  0.351536     0.375     1.11068    0.961263
    4      50       213       163  0.318334   0.21875     1.06426     1.02393
    5      50       251       201  0.314037  0.296875     1.20374     1.12864
    6      50       308       258   0.33591  0.445312    0.817553     1.05099
    7      50       326       276  0.308011  0.140625     1.69989      1.0771
    8      50       358       308  0.300757      0.25     2.00614     1.12582
    9      50       416       366  0.317682  0.453125    0.581573      1.1286
   10      50       435       385  0.300756  0.148438     1.65013      1.1423
Total time run:         10.394796
Total writes made:      436
Write size:             8192
Object size:            8192
Bandwidth (MB/sec):     0.327688
Stddev Bandwidth:       0.145379
Max bandwidth (MB/sec): 0.539062
Min bandwidth (MB/sec): 0.140625
Average IOPS:           41
Stddev IOPS:            18
Max IOPS:               69
Min IOPS:               18
Average Latency(s):     1.1899
Stddev Latency(s):      0.579853
Max latency(s):         2.31031
Min latency(s):         0.07891
Cleaning up (deleting benchmark objects)
Removed 436 objects
Clean up completed and total clean up time :0.707817
~~~

**Comment by dzafman** [comment]
lgtm   I marked this pull request for a test run just to be sure that there aren't tests which need to be fixed because of the extra output.

**Comment by vumrao** [comment]
Thank you !

**Comment by tchaikov** [comment]
tested at http://pulpito.ceph.com/kchai-2016-06-12_09:44:10-rados-wip-kefu-testing---basic-mira/

http://pulpito.ceph.com/kchai-2016-06-12_09:44:10-rados-wip-kefu-testing---basic-mira/254583/ addressed by https://github.com/ceph/ceph-qa-suite/pull/1052

**Comment by vumrao** [comment]
@tchaikov thank you !

**Pull request merged**
