### PR TITLE
rgw: add bilog autotrim, bilog status and mdlog autotrim to radosgw-admin help info

### PR DESCRIPTION
**Pull request by zhangsw**
Signed-off-by: Zhang Shaowen <zhangshaowen@cmss.chinamobile.com>

### CODE REVIEW

**Comment by joke-lee** [comment]
jenkin test this pls

**Comment by joke-lee** [comment]
jenkins test this please

**Comment by joke-lee** [comment]
jenkins test this please

**Comment by zhangsw** [comment]
reopen

**Comment by zhangsw** [comment]
unstale me, my man

**Comment by zhangsw** [comment]
@cbodley Hi, it seems that help info is still missing in master branch, should we reopen this pr?

**Comment by cbodley** [comment]
hey @zhangsw, i had only added the `autotrim` commands as a way for multisite tests to test the incremental trimming logic that radosgw runs in the background every rgw_sync_log_trim_interval. since this stuff happens automatically, admins shouldn't _need_ to run these commands, and the incremental nature would probably confuse admins that expect the commands to trim everything. so i had decided to leave them undocumented

now that we have cls_cxx_map_remove_range() support from https://github.com/ceph/ceph/pull/15183, though, it's much more reasonable for radosgw-admin to provide commands that _do_ trim everything they can. but since we have tests that rely on the current behavior of the autotrim commands, we'd either have to rename the existing autotrim commands and update our tests, or add these new features under a different name. what do you think?

i do agree with documenting the `bilog status` command though!

**Pull request closed without merging**
