### PR TITLE
cephadm: check if file exists when passing `--apply_spec`

### PR DESCRIPTION
**Pull request by guits**
cephadm deploys the cluster, fails and does a rollback. If the passed file doesn't exist we can make the CLI fail early instead.

```

... omitted output ...

Applying ../host-spec.yaml to cluster
FileNotFoundError: [Errno 2] No such file or directory: '../host-spec.yaml'

        ***************
        Cephadm hit an issue during cluster installation. Current cluster files will be deleted automatically.
        To disable this behaviour you can pass the --no-cleanup-on-failure flag. In case of any previous
        broken installation, users must use the following command to completely delete the broken cluster:

        > cephadm rm-cluster --force --zap-osds --fsid <fsid>

        for more information please refer to https://docs.ceph.com/en/latest/cephadm/operations/#purging-a-cluster
        ***************

Deleting cluster with fsid: 6e6a2dbe-f73a-11ee-8262-98be948800fd
Traceback (most recent call last):
  File "/usr/lib64/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib64/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/tmp/tmpive4g9gs.cephadm.build/app/__main__.py", line 5615, in <module>
  File "/tmp/tmpive4g9gs.cephadm.build/app/__main__.py", line 5603, in main
  File "/tmp/tmpive4g9gs.cephadm.build/app/__main__.py", line 2693, in _rollback
  File "/tmp/tmpive4g9gs.cephadm.build/app/__main__.py", line 445, in _default_image
  File "/tmp/tmpive4g9gs.cephadm.build/app/__main__.py", line 2958, in command_bootstrap
FileNotFoundError: [Errno 2] No such file or directory: '../host-spec.yaml'
```

### CODE REVIEW

**Review by phlogistonjohn — APPROVED** [review]
Looks good to me. Nice comment!

**Review by adk3798 — APPROVED** [review]

**Comment by guits** [comment]
jenkins test api

**Comment by guits** [comment]
jenkins test make check

**Comment by guits** [comment]
jenkins test windows

**Comment by adk3798** [comment]
https://pulpito.ceph.com/adking-2024-04-30_05:42:49-orch:cephadm-wip-adk-testing-2024-04-29-2009-distro-default-smithi/

Most failures were `in cluster log` failures that are still in the process of being cleaned up.

Besides that, failures were:

- 1 instance of https://tracker.ceph.com/issues/65718 (known issue)
- 4 instances of mds_upgrade_sequence test failing (known issue)
- 1 instance of staggered upgrade with agent failing (known issue)
- some dead jobs, either reimaging issue or getting stuck before the test has actually began (seemingly on nvme-loop task) (known issue)

**Pull request merged**
