### PR TITLE
require osds are hammer v0.94.4 or later before upgrading past hammer

### PR DESCRIPTION
**Pull request by liewegas**

### CODE REVIEW

**Comment by liewegas** [comment]
see also https://github.com/ceph/ceph/pull/5687

**Comment by liewegas** [comment]
passed wip-sage-testing

**Comment by dachary** [comment]
@liewegas would you like me to write a hammer-x test that verifies this ?

**Comment by liewegas** [comment]
@dachary that would be awesome

**Comment by dachary** [comment]
building liewegas-wip-hammer-feature in the gitbuilders

**Comment by dachary** [comment]
<pre>
teuthology-openstack --throttle 2 --verbose --key-name myself --key-filename ~/Downloads/myself --suite-branch wip-13026-hammer-stop --ceph liewegas-wip-hammer-feature --suite upgrade/hammer-x/v0-94-4-stop
</pre>

**fail** http://167.114.248.72:8081/ubuntu-2015-09-11_15:37:48-upgrade:hammer-x:v0-94-4-stop-liewegas-wip-hammer-feature---basic-openstack/2/

If I read the logs correctly, the >= v0.94.4 OSD restarts despite two other OSDs being < v0.94.4. The teuthology test is at https://github.com/ceph/ceph-qa-suite/pull/560/files

**Comment by liewegas** [comment]
On Fri, 11 Sep 2015, Loic Dachary wrote:
> teuthology-openstack --throttle 2 --verbose --key-name myself --key-filename ~/Downloads/myself --suite-branch wip-13026-hammer-stop --ceph liewe
> gas-wip-hammer-feature --suite upgrade/hammer-x/v0-94-4-stop
> 
> fail http://167.114.248.72:8081/ubuntu-2015-09-11_15:37:48-upgrade:hammer-x:v0-94-4-stop-liewegas-wip-hammer-feature---basic-openstack/2/
> 
> If I read the logs correctly, the >= v0.94.4 OSD restarts despite two other OSDs being < v0.94.4. The teuthology test is at
> https://github.com/ceph/ceph-qa-suite/pull/560/files

That's okay.. you just can't upgrade to infernalis if osds are < 0.94.4...

**Comment by dachary** [comment]
> That's okay.. you just can't upgrade to infernalis if osds are < 0.94.4...

But that's what I read : the infernalis (9.0.3 +) OSD starts and joins the cluster which has an infernalis mon despite the two 0.94.3 OSDs running. Unless I'm misreading the logs ?

**Comment by dachary** [comment]
I should add a test for https://github.com/liewegas/ceph/commit/38465f0d7065c41070eab6b2326f8a1f0b8de332 though. I believe the current test only covers https://github.com/liewegas/ceph/commit/f668c6cce1b6c4ca05863e10b57507c91f28fa0f

**Comment by dachary** [comment]
Oh, I think I understand what I'm getting wrong

**Comment by dachary** [comment]
https://github.com/ceph/ceph-qa-suite/pull/560/files passes with this pull request:

<pre>
teuthology-openstack --throttle 2 --verbose --key-name myself --key-filename ~/Downloads/myself --suite-branch wip-13026-hammer-stop --ceph liewegas-wip-hammer-feature --suite upgrade/hammer-x/v0-94-4-stop
</pre>

* *pass* http://167.114.248.72:8081/ubuntu-2015-09-12_21:51:20-upgrade:hammer-x:v0-94-4-stop-liewegas-wip-hammer-feature---basic-openstack/9/

**Comment by dachary** [comment]
Not merging because it has the **wip-sage-testing** label. 
<pre>
Reviewed-by: Loic Dachary &lt;ldachary@redhat.com>
</pre>
once it's merged I'll write a test for https://github.com/ceph/ceph/pull/5687 as well.

**Comment by liewegas** [comment]
wip-sage-testing is fine, was just making sure i hadn't broken something stupid.  Merged them both.  We should manually (or automatically?) verify that this prevents what it's supposed to...

**Comment by dachary** [comment]
> We should manually (or automatically?) verify that this prevents what it's supposed to... 

Once https://github.com/ceph/ceph-qa-suite/pull/560/files is merged it will automatically verify that it does what it's supposed to for the master branch.

**Pull request merged**
