### PR TITLE
rgw: upgrade Apache Arrow submodule to 15.0.0

### PR DESCRIPTION
**Pull request by ivancich**
Upgrades Apache Arrow. Update RGW Arrow Flight code to work with Apache Arrow API changes.

Fixes: https://tracker.ceph.com/issues/64803

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [x] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Comment by ivancich** [comment]
jenkins test make check

**Comment by ivancich** [comment]
jenkins test api

**Comment by ivancich** [comment]
Ping @kalebskeithley @galsalomon66 .

**Comment by ivancich** [comment]
I was hoping I could make local changes to the submodule, but that generated a different commit hash, and that could not be fetched. I think to maintain local changes we'd have to either make it a subdirectory rather than a submodule, or temporarily create our own repo for the modified version.

There was an accidental ABI change that originated in 15.0.1 and continues to 15.0.2, and is expected to revert in 16.*. Do we need to care about that, @kalebskeithley and @galsalomon66 ?

**Comment by ivancich** [comment]
jenkins test make check

**Comment by ivancich** [comment]
jenkins test api

**Comment by ivancich** [comment]
So this isn't building because Arrow apparently wants xsimd version >= 8.1.0. Need to figure out how best to resolve that.

**Comment by galsalomon66** [comment]
> I was hoping I could make local changes to the submodule, but that generated a different commit hash, and that could not be fetched. I think to maintain local changes we'd have to either make it a subdirectory rather than a submodule, or temporarily create our own repo for the modified version.
> 
> There was an accidental ABI change that originated in 15.0.1 and continues to 15.0.2, and is expected to revert in 16.*. Do we need to care about that, @kalebskeithley and @galsalomon66 ?

i did a limited test(standalone application) against 15.0.2, so .. I can not tell something about this ABI change.
do you know what is broken? can we use a different version (15.0.0)?

**Comment by cbodley** [comment]
> So this isn't building because Arrow apparently wants xsimd version >= 8.1.0. Need to figure out how best to resolve that.

i see that epel9 has [xsimd-devel-9.0.1](https://packages.fedoraproject.org/pkgs/xsimd/xsimd-devel/epel-9.html) but ubuntu jammy (22.04LTS) is on [libxsimd-dev 7.6.0](https://packages.ubuntu.com/jammy/libxsimd-dev). ubuntu 23.04 has [8.1.0](https://packages.ubuntu.com/lunar/libxsimd-dev) but we'd probably need to add a submodule as long as we support jammy

**Comment by badone** [comment]
Fails to build on F39 as well with a cmake ERROR.

`
CMake Error at cmake_modules/ThirdpartyToolchain.cmake:307 (find_package):
By not providing "Findxsimd.cmake" in CMAKE_MODULE_PATH this project has
asked CMake to find a package configuration file provided by "xsimd", but  CMake did not find one.
`

If I install xsimd-devel manually it gets past that error and builds successfully so might need to add that package to install-deps of some other dependency list?

**Comment by ivancich** [comment]
Please note: the branch name (`ivancich:wip-upgrade-arrow+flight-15.0.2`) is now a misnomer since we're in fact upgrading to 15.0.0. But there's now way to rename a branch in a PR other than to create a new PR and lose the easy access to the discussion.

**Comment by badone** [comment]
I can confirm this now resolves the issue with building on f39, thanks @ivancich

**Comment by badone** [comment]
jenkins test make check
jenkins test api

**Comment by badone** [comment]
jenkins test make check

**Comment by badone** [comment]
jenkins test api

**Comment by ivancich** [comment]
@galsalomon66 I believe I've resolved the xsimd issue. It's now not building due to arrow changes forcing s3select changes. Are you ready with the minimal patch or commit off of main that would make s3select compatible with Arrow 15.0.0, so we can add it to this PR and get it merged?

**Comment by ivancich** [comment]
So it looks like this will pass CI tests as I added a commit to the s3tests submodule and then pulled in the updated submodule.

**Comment by ivancich** [comment]
Passed teuthology:
* https://pulpito.ceph.com/ivancich-2024-05-08_17:44:36-rgw-wip-upgrade-arrow-15-distro-default-smithi/
* https://pulpito.ceph.com/ivancich-2024-05-08_17:44:56-rgw-wip-upgrade-arrow-15-distro-default-smithi/

**Comment by ivancich** [comment]
jenkins test make check

**Comment by cbodley** [comment]
> Unmodified Submodules
> please include 'arrow submodule' in your commit message, if this change is intentional.

**Comment by mattbenjamin** [comment]
yay!

**Comment by Svelar** [comment]
Should this be backported to squid?

**Comment by cbodley** [comment]
> Should this be backported to squid?

we weren't planning to backport. is there a need for it?

**Comment by Svelar** [comment]
> we weren't planning to backport. is there a need for it?

https://github.com/apache/arrow/pull/13902
From v10.0.0, RISC-V architecture are suppoerted.

**Comment by ThomasLamprecht** [comment]
> > Should this be backported to squid?
> 
> we weren't planning to backport. is there a need for it?

@cbodley The old arrow version fails compilation with upcoming Debian 13 "Trixie"'s libabseil version, as the old arrow version is using C++11 while Trixie's abseil lib is requiring at least C++17. This might be fixed otherwise, e.g., I did not look into how bad it would be to compile the old arrow version as C++17, but updating arrow would reduce some tech debt and fix it too.

As Ceph Squid is currently the most recent stable release it would be great to have this fixed in one way or another.
FWIW, I could try to prepare a backport if that's preferred and nobody jumps on this, as I should soon™ be finished with evaluating such a backport locally anyway.

Edit: forgot to mention: Debian currently does not have ~a libabseil~ an apache arrow package in its repositories, so one cannot simply turn on the `WITH_SYSTEM_ARROW` flag and that's why the built-in version matters a bit more there.

**Comment by cbodley** [comment]
> As Ceph Squid is currently the most recent stable release it would be great to have this fixed in one way or another. FWIW, I could try to prepare a backport if that's preferred and nobody jumps on this, as I should soon™ be finished with evaluating such a backport locally anyway.

great, no objection to backporting

> Edit: forgot to mention: Debian currently does not have a libabseil package in it's repositories, so one cannot simply turn on the `WITH_SYSTEM_ARROW` flag and that's why the built-in version matters a bit more there.

thanks. it would be nice to address this, because it would allow Ceph to drop this submodule entirely (`WITH_SYSTEM_ARROW` was made the default for rpm builds a couple years ago in https://github.com/ceph/ceph/pull/46535)

**Comment by ThomasLamprecht** [comment]
alright, so I'll try to prepare this. Should I do a single tracking issue and PR for all backports that are required to get Ceph Squid to build on Debian Trixie, or do you prefer to have these split up and submitted separately?

A bit more context: As of now I backported the Apache Arrow upgrade (https://github.com/ceph/ceph/pull/56585), using newer python APIs in mgr (https://github.com/ceph/ceph/pull/58199) that would bump the minimum required Python version to 3.9 though.

And finally there is the removal of the Python distutils package with Python 3.12 as per [PEP 632], which was partially addressed in https://github.com/ceph/ceph/pull/59888 and that has even been partially backported for other reasons, the commit ffcc157a694 ("pybind/mgr: replace imports of distutils.util") is still missing and if one searches the code base on the current main branch one still finds quite a few uses of distutils inside various Python files (e.g. src/pybind/rbd/setup.py), so not sure yet if that part is actually fully addressed already.

But anyhow, that's now derailing the topic of this PR rather a bit much (sorry), but I'd be still thankful for a hint for my question about split PR or not.

[PEP 632]: https://peps.python.org/pep-0632/

**Comment by cbodley** [comment]
> alright, so I'll try to prepare this. Should I do a single tracking issue and PR for all backports that are required to get Ceph Squid to build on Debian Trixie, or do you prefer to have these split up and submitted separately?

i won't be able to help with review/testing of the python stuff, so i'd prefer a separate backport for arrow changes

**Pull request merged**
