### PR TITLE
qa/suites: add test exercising workunits/mon/auth_caps.sh

### PR DESCRIPTION
**Pull request by tchaikov**

### CODE REVIEW

**Comment by tchaikov** [comment]
per discussion with @jecluis, will make this a part of "make check". as it's just a smoke test.

**Comment by tchaikov** [comment]
@jecluis ping?

**Comment by jecluis** [comment]
jenkins retest this please

**Comment by tchaikov** [comment]
- http://pulpito.ceph.com/kchai-2017-07-05_03:23:34-rados-wip-kefu-testing-distro-basic-mira/
- http://pulpito.ceph.com/kchai-2017-07-04_08:30:19-rados-wip-kefu-testing-distro-basic-mira/

**Pull request merged**
