### PR TITLE
rpm: add missing % in %dir directive

### PR DESCRIPTION
**Pull request by smithfarm**
de6c8250a6d91403e6d334aeb901bf9720ba40eb added an explicit %dir directive for
a new directory added to the ceph-common package, but -- due to a typo --
neglected to include the "%". As a result, RPM builds started to fail with:

    Processing files: ceph-common-17.0.0-2787.gde6c8250.el8.x86_64
    error: File must begin with "/": {_libdir}/ceph/denc/

    RPM build errors:
        File must begin with "/": {_libdir}/ceph/denc/

Fixes: de6c8250a6d91403e6d334aeb901bf9720ba40eb
Signed-off-by: Nathan Cutler <ncutler@suse.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by smithfarm** [comment]
https://shaman.ceph.com/builds/ceph/wip-denc-fix-follow-on/9ca3c0e05ba5f404a4fa0e3ea13bd6c12a855826/

**Comment by smithfarm** [comment]
https://shaman.ceph.com/builds/ceph/wip-denc-fix-follow-on/4abbf3fe311f12f5fe4cda51982bd04b8f5019d6/

**Review by tchaikov — APPROVED** [review]

**Comment by smithfarm** [comment]
```
The following tests FAILED:
	 21 - run-rbd-unit-tests-1.sh (Failed)
```

**Comment by smithfarm** [comment]
jenkins test make check

**Comment by liewegas** [comment]
https://shaman.ceph.com/builds/ceph/wip-sage3-testing-2021-04-05-1538/e8115d4c08152ab84561cd829add9246a9c90222/default/264299/

**Pull request merged**
