### PR TITLE
rbd: wait for all io complete when bench is interrupted

### PR DESCRIPTION
**Pull request by trociny**
Signed-off-by: Mykola Golub <mgolub@suse.com>

- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by trociny** [comment]
@dillaman I noticed this problem when running (and interrupting) `rbd bench` like this:
```
rbd bench --io-type write --io-size 4K --io-total 10M test --rbd_qos_iops_limit 100
```
because although `rbd bench` does flush before closing the image, the flush ignores requests in the throttler queue. Although it was definitely the `rbd bench` bug that it was not waiting for all io completed, don't we need also fix `flush` request to wait for requests in the throttler to complete (probably make `flush` request not bypass the throttler)?

**Comment by dillaman** [comment]
> flush ignores requests in the throttler queue

We could move the ```AioCompletion::start_op``` call to ```ImageRequestWQ::start_in_flight_io``` and drop the individual calls throughput.

**Comment by trociny** [comment]
> We could move the `AioCompletion::start_op` call to `ImageRequestWQ::start_in_flight_io` and drop the individual calls throughput.

Thanks, I will try this.

**Comment by dillaman** [comment]
@trociny I am going to merge this into the nautilus branch to fix the potential bug before 14.2.2's release. We can eventually backport the better fix to nautilus when ready in a later point-release.

**Comment by trociny** [comment]
@dillaman Sure, I think it is ready for merge if it looks ok to you.

Do you mean by "the better fix" a fix for the flush issue which is planned to be addressed  #26931? I think it is a different issue that is why I created a separate PR for it.

**Comment by dillaman** [comment]
> Do you mean by "the better fix" a fix for the flush issue which is planned to be addressed #26931?

Yes. The ```rbd``` changes wouldn't technically be needed if there wasn't an issue w/ the flush (which I agree is a larger issue and I have flagged for backport to nautilus as well).

**Comment by trociny** [comment]
@dillaman the rbd changes would still be needed for `IO_TYPE_READ`.

**Comment by dillaman** [comment]
@trociny We don't track reads vs writes separately (due to laziness), so flush actually pushes out reads as well right now.

**Comment by trociny** [comment]
@dillaman Yes, but `rbd` does not call flush for `IO_TYPE_READ` case, so it would still need to be changed at least to call `image.flush()` unconditionally.

**Pull request merged**
