### PR TITLE
librbd: correct race conditions discovered during unit testing

### PR DESCRIPTION
**Pull request by dillaman**

### CODE REVIEW

**Comment by dachary** [comment]
@dillaman it's great these false negative reveal actual bugs :-) Thanks for dealing with it quickly !

**Comment by dillaman** [comment]
@dachary Indeed -- thx for triaging.

**Comment by dachary** [comment]
@dillaman I'm excited because it's the last false negative I know about. Once it's gone we will see an endless stream of clean make check runs. /me being over enthusiastic

**Comment by dillaman** [comment]
@dachary You are setting us up for failure with your high expectations :stuck_out_tongue:

**Comment by dachary** [comment]
we'll boldly fail where noone has failed before !

**Pull request merged**
