### PR TITLE
build/ops: rpm: rip out rcceph script

### PR DESCRIPTION
**Pull request by smithfarm**
"rcceph" is a SysVinit-style command-line interface for stopping, starting,
enabling, etc. all ceph-osd and ceph-mon systemd units on a machine, in one go.

Since the same functionality is provided by ceph-{osd,mon}.target, the script
is obsolete. It is also unmaintained. Judging from the absence of recent
mentions of the script online, I guess it is no longer used.

Leaving dead code in the tree can cause confusion, especially when the code is
packaged and shipped to customers. Therefore I propose to rip it out.

Signed-off-by: Nathan Cutler <ncutler@suse.com>

### CODE REVIEW

**Comment by smithfarm** [comment]
@b-ranto Right - DEB doesn't ship it. Another reason to drop it. . .

**Comment by tchaikov** [comment]
i think we need to at least send a mail to ceph-user to collect more opinions from end user. and then add a note in PendingReleaseNotes. as it's a user facing feature.

**Comment by smithfarm** [comment]
@tchaikov Started thread on ceph-users ML and added PendingReleaseNotes entry.

**Comment by tchaikov** [comment]
need rebase.

**Comment by smithfarm** [comment]
@tchaikov Thanks; rebased.

**Comment by tchaikov** [comment]
http://pulpito.ceph.com/kchai-2018-01-17_13:29:17-rados-wip-kefu-testing-2018-01-17-0950-distro-basic-mira/

**Pull request merged**
