### PR TITLE
os/bluestore: remove useless function submit

### PR DESCRIPTION
**Pull request by mychoxin**
Signed-off-by: mychoxin <mychoxin@gmail.com>

### CODE REVIEW

**Comment by mychoxin** [comment]
@joscollin

**Comment by liupan1111** [comment]
https://github.com/ceph/ceph/pull/17524 

something related to submit is under discussion, let's hold on this PR until 17524 get conclusion.

**Comment by joscollin** [comment]
@liupan1111 ok, I will put this as DNM then. 

@mychoxin Please ping me when it is ready for review.

**Comment by joscollin** [comment]
Test Result:

- http://pulpito.front.sepia.ceph.com/jcollin-2017-09-09_13:06:53-rados-wip-jcollin-testing_09-09-2017-distro-basic-smithi/
- http://pulpito.front.sepia.ceph.com/compare/?branch=wip-jcollin-testing_09-09-2017&suite=rados

**Pull request merged**
