### PR TITLE
reef: mgr/telemetry: add leaderboard description and documentation

### PR DESCRIPTION
**Pull request by yaarith**
backport tracker: https://tracker.ceph.com/issues/59390

---------

backport of https://github.com/ceph/ceph/pull/50699
parent tracker: https://tracker.ceph.com/issues/59389

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [x] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [x] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Review by anthonyeleven — APPROVED** [review]

**Comment by yaarith** [comment]
ceph API tests failures:
```
Using legacy 'setup.py install' for coverage, since package 'wheel' is not installed.
Installing collected packages: coverage
  Running setup.py install for coverage: started
  Running setup.py install for coverage: finished with status 'done'
Successfully installed coverage-4.5.2
Cannot find device "ceph-brx"
2023-04-10 19:03:15,045.045 INFO:__main__:Creating cluster with 1 MDS daemons
2023-04-10 19:03:15,045.045 INFO:__main__:
tearing down the cluster...
unable to get monitor info from DNS SRV with service name: ceph-mon
2023-04-10T19:03:22.307+0000 7fcdf9b54640 -1 failed for service _ceph-mon._tcp
2023-04-10T19:03:22.307+0000 7fcdf9b54640 -1 monclient: get_monmap_and_config cannot identify monitors to contact
[errno 2] RADOS object not found (error connecting to the cluster)
rm: cannot remove '/var/run/ceph': Permission denied
2023-04-10 19:03:23,513.513 ERROR:__main__:stop.sh failed: Command failed with status 1: '../src/stop.sh'
2023-04-10 19:03:23,514.514 INFO:__main__:
ceph cluster torn down
2023-04-10 19:03:23,517.517 INFO:__main__:
running vstart.sh now...
Build step 'Execute shell' marked build as failure
[PostBuildScript] - [INFO] Executing post build scripts.
[PostBuildScript] - [INFO] Build does not have any of the results [ABORTED]. Did not execute build step #0.
Archiving artifacts
[Checks API] No suitable checks publisher found.
Setting status of bf5862dc86e96cf086f9c692bcaaf3db2cdcc7a5 to FAILURE with url https://jenkins.ceph.com/job/ceph-api/53749/ and message: 'ceph API tests failed
 '
Using context: ceph API tests
Finished: FAILURE
```

**Review by ljflores — APPROVED** [review]

**Comment by ljflores** [comment]
Testing will be completed for this soon.

**Comment by ljflores** [comment]
Rados suite review: https://tracker.ceph.com/projects/rados/wiki/REEF#httpstrellocomcSQrPoAfN1757-wip-yuri6-testing-2023-05-19-1351-reef

**Comment by zdover23** [comment]
https://github.com/ceph/ceph/pull/51679 - a follow-up to this PR. https://github.com/ceph/ceph/pull/51679 standardizes the presentation of the CLI commands and puts some of the sentences in the format we use elsewhere in the documentation.

**Pull request merged**
