### PR TITLE
mgr/dashboard: update translations for pacific

### PR DESCRIPTION
**Pull request by s0nea**
Note: it's not a backport because the change is not intended to land in master. It's pacific related only.

Signed-off-by: Tatjana Dehler <tdehler@suse.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by votdev** [comment]
jenkins test dashboard

**Comment by votdev** [comment]
jenkins test dashboard

**Review by votdev — APPROVED** [review]
LGTM

**Comment by nizamial09** [comment]
jenkins test dashboard

**Review by nizamial09 — APPROVED** [review]

**Review by epuertat — APPROVED** [review]
LGTM! Thanks a lot @s0nea !

**Pull request merged**
