### PR TITLE
ceph-disk: Always set user/group when running ceph-osd

### PR DESCRIPTION
**Pull request by branto1**
Currently, we are running ceph-osd daemons from ceph-disk without
supplying it with the setuser/group arguments. This causes issues
because we are accessing files that are owned by ceph user with root
which is not explicitely allowed in SELinux scenario.

Simply pass the setuser/group arguments to all the occurrences of
ceph-osd call to fix this.

Fixes: #14870
Signed-off-by: Boris Ranto <branto@redhat.com>

### CODE REVIEW

**Comment by branto1** [comment]
@vasukulkarni: Could you please test that this patch (branch) makes the dac_override denials disappear?

**Comment by vasukulkarni** [comment]
@branto1 sure, will run the selinux suite, atm i am getting error will look at in few minutes http://fpaste.org/329517/64398741/raw/

**Comment by vasukulkarni** [comment]
@branto1 they are still failing for dac_override http://pulpito.ceph.com/vasu-2016-02-25_19:29:42-selinux-wip-selinux-update---basic-multi/

**Comment by branto1** [comment]
Hmm, ok, I've played with this a bit more and I was able to hit this on my test system (even ceph-mon is vulnerable to this, not just ceph-osd). The issue is not critical as in it won't stop ceph daemons from functioning (not even in enforcing mode). It will just stop them from reading a config file like

`/var/lib/ceph/mon/ceph-node1/config`

If I read the code correctly, this file is accessed in global_pre_init function while we drop the privileges afterwards in the global_init function.

I'll need to dig deeper to see if we can avoid this somehow -- i.e. check that the setuser/setgroup bits do not actually need the config file read before we can drop the privileges, etc.

**Comment by branto1** [comment]
@vasukulkarni: I've pushed some more patches, here. This PR should also fix bug #14871 and back-port the SELinux policy update for radosgw (bug #14902).

Could you please retest once the gitbuilders finish building the new packages?

**Comment by liewegas** [comment]
Hmm, in 4dfe0a8a4b958aab154ee14729c8444fbcb4b798 I deliberately did this after the config was read, but I'm not sure why now.  The main problem with doing it before the daemon was launched at all (via systemd) was that ceph-osd-prestart.sh needed to be root.  And in the radosgw case  we defer until even later until civetweb has bound to, say, port 80, and then drop privs.

Can we instead change the selinux policy to allow root to read these configs?

**Comment by vasukulkarni** [comment]
@branto1 still seen http://pulpito.ceph.com/vasu-2016-02-26_09:22:17-selinux-wip-selinux-update---basic-multi/29279/

**Comment by branto1** [comment]
@liewegas: Yeah, that would be the easiest solution and it is usually ok for programs that do setuid/setgid to have dac_override in their policy. I'll update the PR.

**Comment by liewegas** [comment]
can this be rebased and target master please?

**Comment by branto1** [comment]
@liewegas I can rebase it on top of master but we should definitely back-port this to jewel as well.

**Comment by liewegas** [comment]
not to worry, master will be part of jewel

**Comment by branto1** [comment]
OK, closing this one.

**Pull request closed without merging**
