### PR TITLE
isa-l: update isa-l to v2.18

### PR DESCRIPTION
**Pull request by ganeshmaharaj**
This upgrade brings
-  Complete rewrite of DEFLATE optimizations resulting in 5X better
   throughput and compression ratios comapred to  zlib, lz4, lzo and 2X
   better decompression performance when compared to zlib.
-  AVX512 improvements to multi-buffer versions of MD5, SHA-1 and SHA-256
   cryptographic hashing functions resulting in 3X better in performance
   compared to the AVX2 generation.

This update has the potential to improve bluestore compression
and dedup performance.

Signed-off-by: Ganesh Mahalingam <ganesh.mahalingam@intel.com>
Signed-off-by: Tushar Gohad <tushar.gohad@intel.com>

### CODE REVIEW

**Comment by liewegas** [comment]
<prE>
/home/jenkins-build/build/workspace/ceph-pull-requests/src/compressor/zlib/ZlibCompressor.cc:19:37: fatal error: isa-l/include/igzip_lib.h: No such file or directory
</pre>

**Comment by liewegas** [comment]
retest this please

**Comment by liewegas** [comment]
Thanks!

**Comment by liewegas** [comment]
http://pulpito.ceph.com/sage-2017-06-30_18:42:09-rados-wip-sage-testing-distro-basic-smithi/

test looks ok

**Comment by ganeshmaharaj** [comment]
@liewegas please find the comparison numbers between the current version of ISA-L (2.16) and the proposed one (2.18) [here](https://docs.google.com/spreadsheets/d/1i0ShCM2mH090gOYVDsXWqpoSN_dTRAl0x7NwaIjTE4M/edit?usp=sharing).

**Comment by tchaikov** [comment]
retest this please.

**Comment by ganeshmaharaj** [comment]
@liewegas @tchaikov Updated the patch to include the perf numbers in the commit message against a non-permanent google doc. The data provided is the bluestore compression time as provided by bluestore when tested with objectstore fio plugin.

**Comment by ganeshmaharaj** [comment]
Not sure if this is a thing of concern, but thought i will bring it to your notice. Any existing old ceph repos that folks use will run into the below error if they just do 'git submodule update --recursive' after this change has been merged.

`ganeshma|Illidan|/data/odisk/ceph/ceph >>> git submodule update --recursive 
error: Server does not allow request for unadvertised object e1a337433a340bc0974ed0f04301bdaca374af6
Fetched in submodule path 'src/isa-l', but it did not contain e1a337433a340bc0974ed0f04301bdaca374af6. Direct fetching of that commit failed.
`
This I believe is due to the fact that no branch is tracking the SHA-1 of the tag v2.18.0. The way i could fix it was with the below commands from my ceph repo top_dir

`cd src/isa-l/
git fetch origin --tags
cd ../../
git submodule update --recursive
`
If it is not an issue, updating the master branch in https://github.com/ceph/isa-l to the commit tagged v2.18.0 should eliminate this error msg.

**Comment by liewegas** [comment]
fixed!

**Comment by ganeshmaharaj** [comment]
Thanks a lot @liewegas

**Pull request merged**
