### PR TITLE
mds: Reorganize class members in Locker header

### PR DESCRIPTION
**Pull request by varshar16**
Fixes: https://tracker.ceph.com/issues/41665
Signed-off-by: Varsha Rao <varao@redhat.com>

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`

</details>

### CODE REVIEW

**Comment by varshar16** [comment]
> ```
> In file included from /home/jcollin/ceph-review/ceph/src/mds/Locker.cc:19:
> /home/jcollin/ceph-review/ceph/src/mds/Locker.h: In constructor ‘Locker::Locker(MDSRank*, MDCache*)’:
> /home/jcollin/ceph-review/ceph/src/mds/Locker.h:260:12: warning: ‘Locker::mdcache’ will be initialized after [-Wreorder]
>    MDCache *mdcache;
>             ^~~~~~~
> /home/jcollin/ceph-review/ceph/src/mds/Locker.h:244:18: warning:   ‘elist<CInode*> Locker::need_snapflush_inodes’ [-Wreorder]
>    elist<CInode*> need_snapflush_inodes;
>                   ^~~~~~~~~~~~~~~~~~~~~
> /home/jcollin/ceph-review/ceph/src/mds/Locker.cc:88:1: warning:   when initialized here [-Wreorder]
>  Locker::Locker(MDSRank *m, MDCache *c) :
>  ^~~~~~
> ```

I have fixed the error. Please review again.

**Comment by joscollin** [comment]
Can you cleanup those headers in Locker.cc? Many of them are already included in Locker.h. Most of those standard library headers in Locker.h are available from types.h too.

**Comment by varshar16** [comment]
> Can you cleanup those headers in Locker.cc? Many of them are already included in Locker.h. Most of those standard library headers in Locker.h are available from types.h too.

Yes, I have removed them in new commit.

**Comment by varshar16** [comment]
jenkins test make check arm64

**Pull request merged**
