### PR TITLE
mgr/StandbyPyModules: Increase the daemon for loadconfig

### PR DESCRIPTION
**Pull request by renhwztetecs**
Increased timing access to config-key information, through the A thread

Signed-off-by: huanwen ren <ren.huanwen@zte.com.cn>

### CODE REVIEW

**Comment by xiexingguo** [comment]
This patch is very welcome. Otherwise we have to restart mgr to force the reload of any changed configuration.   
@jcsp @liewegas  What do you think?

**Comment by liewegas** [comment]
This seems okay as a stopgap, but I think what we really want is a subscription for the config-key state so that the mgr gets a notification when there is a change and can refresh then.  There's some cleanup needed for that first (mainly, convert config-key to a regular PaxosService).  Or we might want to do something a bit more drastic and combine it with ConfigManager.

**Comment by jcsp** [comment]
@liewegas Rubab is working on getting the mgr module config options into ConfigManager on top of your branch -- getting all the config in one place seems like the way to go.

This patch is going to send tens of commands to the mons every five seconds, which seems like a really heavy thing to do.  Modules can already individually support live-updating of their settings if they expose CLI operations for it, so fleshing out those is probably a better stop gap than doing this.

**Comment by liewegas** [comment]
Yeah, sounds good!

**Pull request closed without merging**
