### PR TITLE
mon: fix slow op warning on mon, improve slow op warnings

### PR DESCRIPTION
**Pull request by liewegas**
Fixes http://tracker.ceph.com/issues/23769

### CODE REVIEW

**Comment by batrick** [comment]
@jdurgin issues like 23769 make me nervous about global whitelisting SLOW_OPS. Perhaps we should distinguish slow ops and "stuck" ops somehow.

**Comment by jdurgin** [comment]
@batrick that's a good idea. a higher threshold for detecting bugs like that makes sense

**Comment by batrick** [comment]
Great catch! Thanks Sage.

**Comment by liewegas** [comment]
@batrick i think with this we should revert the blanket SLOW_OPS whitelist in teuthology.  IMO we should do that explicitly on runs doing thrashing or stressy/heavy workloads or whatever.

**Comment by liewegas** [comment]
http://pulpito.ceph.com/sage-2018-05-02_22:22:16-rados-wip-sage3-testing-2018-05-02-1448-distro-basic-smithi/

- valgrind failure is http://tracker.ceph.com/issues/23980
- scrub error is old bug http://tracker.ceph.com/issues/22656
- infra noise

**Comment by batrick** [comment]
@liewegas https://github.com/ceph/teuthology/pull/1172

**Pull request merged**
