### PR TITLE
nautilus: mds: send scrub status to ceph-mgr only when scrub is running

### PR DESCRIPTION
**Pull request by smithfarm**
backport trackers:

* https://tracker.ceph.com/issues/46480
* https://tracker.ceph.com/issues/46589

---

backport of

* https://github.com/ceph/ceph/pull/34861
* https://github.com/ceph/ceph/pull/36091

parent trackers:

* https://tracker.ceph.com/issues/45349
* https://tracker.ceph.com/issues/46495

this backport was staged using ceph-backport.sh version 15.1.1.389
find the latest version at https://github.com/ceph/ceph/blob/master/src/script/ceph-backport.sh

---

To Do:

- [x] #36091 merged into master
- [x] #36091 cherry-picked into this PR
- [x] https://github.com/ceph/ceph/pull/36047 merged into octopus
- [x] https://github.com/ceph/ceph/pull/36047 published in an octopus release (15.2.8)
- [x] fix bakes in octopus for some time
- [x] rebase
- [x] remove DNM
- [x] clear for integration testing

### CODE REVIEW

**Comment by smithfarm** [comment]
#36047 has been merged, but still not (yet) published in an octopus release

Keeping DNM in place

**Comment by smithfarm** [comment]
#36047 was published in octopus 15.2.8

removing DNM

**Comment by ajarr** [comment]
@yuriw this backport has ceph-mgr changes. I think we need to run the rados qa suites as done in the master PR, 
https://github.com/ceph/ceph/pull/36091#issuecomment-658809284

@tchaikov can you please confirm the nautilus qa suites (besides the fs suite) Yuri needs to run to test the backport of https://github.com/ceph/ceph/pull/36091 included in this PR? Thanks!

**Comment by yuriw** [comment]
will test with core PRs

**Comment by yuriw** [comment]
test this please

**Comment by yuriw** [comment]
test this please

**Comment by yuriw** [comment]
test this please

**Comment by yuriw** [comment]
jenkins test make check

**Review by ajarr — APPROVED** [review]

**Pull request merged**
