### PR TITLE
[DNM] jewel: core: osdc/Objecter: If osd full, it should pause read op which w/ rwordered flag

### PR DESCRIPTION
**Pull request by shinobu-x**
http://tracker.ceph.com/issues/19140

MERGE TOGETHER WITH #13885

### CODE REVIEW

**Comment by shinobu-x** [comment]
test this please

**Comment by liupan1111** [comment]
@shinobu-x @majianpeng Could you talk more about this flag CEPH_OSD_FLAG_RWORDERED?  what does it work for? why we pause read op with this flag? Thanks.

**Comment by shinobu-x** [comment]
@liupan1111 This commit is intended for backporting request copied from:

> http://tracker.ceph.com/issues/19139

@smithfarm mentioned in his last comment in above

> Combine jewel backport with #19133 in a single PR.

Looking at that, there is other commits in:

> https://github.com/ceph/ceph/pull/13759

Commits in that PR seem to be something which we've missed.

@smithfarm Would you be able to confirm above my deduction?
I'm asking because I'm not 100% sure...

**Comment by smithfarm** [comment]
The additional commits are in #13885 - I just added that one to the integration branch. Since there are no conflicts and both PRs are in the same integration branch, there's no need to combine them into a single PR.

**Comment by smithfarm** [comment]
closing in favor of #14427

**Pull request closed without merging**
