### PR TITLE
nautilus: qa: migrate to python3

### PR DESCRIPTION
**Pull request by tchaikov**
## Checklist
- [x] run rados qa suite:
  - http://pulpito.ceph.com/kchai-2020-04-27_03:57:16-rados-nautilus-distro-basic-smithi/
  - http://pulpito.ceph.com/kchai-2020-04-29_04:57:09-rados-nautilus-distro-basic-smithi/
  - http://pulpito.ceph.com/kchai-2020-04-30_01:57:21-rados-nautilus-distro-basic-smithi/
  - http://pulpito.ceph.com/kchai-2020-04-30_08:58:21-rados-nautilus-distro-basic-smithi/
  - http://pulpito.ceph.com/kchai-2020-05-01_05:19:14-rados-nautilus-distro-basic-smithi/
  - failure are either fixed by 72d4469e9a692d00984b67ccf5ec1805e68297b9 or not related to py3 change.
- [x] run rgw qa suite
  - http://pulpito.ceph.com/kchai-2020-05-03_09:26:35-rgw-nautilus-distro-basic-smithi/
  - http://pulpito.ceph.com/kchai-2020-05-22_10:51:17-rgw-nautilus-distro-basic-smithi/
  - http://pulpito.ceph.com/kchai-2020-06-02_09:51:52-rgw-nautilus-distro-basic-smithi/
  - failures are tracked by https://tracker.ceph.com/issues/45056
- [x] run rbd qa suite
  - http://pulpito.ceph.com/kchai-2020-05-01_06:20:43-rbd-nautilus-distro-basic-smithi
  - http://pulpito.ceph.com/kchai-2020-05-01_09:02:15-rbd-nautilus-distro-basic-smithi/
  - openstack tests were removed in 34d334139f4d7d5e8fcb5ee01200ce745b0b6204
- [x] run cephfs qa suite:
  - http://pulpito.ceph.com/kchai-2020-04-27_04:18:02-fs-nautilus-distro-basic-smithi/
  - http://pulpito.ceph.com/kchai-2020-04-29_02:58:33-fs-nautilus-distro-basic-smithi/
  - http://pulpito.ceph.com/kchai-2020-04-29_06:41:28-fs-nautilus-distro-basic-smithi/
  - http://pulpito.ceph.com/kchai-2020-04-29_08:32:47-fs-nautilus-distro-basic-smithi/
  - http://pulpito.ceph.com/kchai-2020-04-30_01:55:07-fs-nautilus-distro-basic-smithi/
  - http://pulpito.ceph.com/kchai-2020-04-30_08:59:13-fs-nautilus-distro-basic-smithi/
  - http://pulpito.ceph.com/kchai-2020-05-01_05:19:45-fs-nautilus-distro-basic-smithi/
  - http://pulpito.ceph.com/kchai-2020-05-21_04:17:30-fs-nautilus-distro-basic-smithi/
  - http://pulpito.ceph.com/kchai-2020-05-21_08:08:39-fs-nautilus-distro-basic-smithi/
  - http://pulpito.ceph.com/kchai-2020-05-22_09:50:02-fs-nautilus-distro-basic-smithi/
  - http://pulpito.ceph.com/kchai-2020-06-03_11:57:14-fs-nautilus-distro-basic-smithi/5115916/
- [x] run smoke qa suite: 
  - http://pulpito.ceph.com/kchai-2020-04-27_03:13:51-smoke-nautilus-distro-basic-smithi/
  - http://pulpito.ceph.com/kchai-2020-04-27_06:06:13-smoke-nautilus-distro-basic-smithi/
- [x] py3 tests pass on master, see #34264
- [x] backport #34264
- [x] backport #34471
---

Fixes: https://tracker.ceph.com/issues/42398

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by tchaikov** [comment]
jenkins test make check

**Comment by tchaikov** [comment]
the test failure also exists in the nautilus branch without these changes. see https://github.com/ceph/ceph/pull/34236

**Comment by tchaikov** [comment]
- http://pulpito.ceph.com/kchai-2020-03-28_02:15:06-rados-nautilus-kefu2-testing-2020-03-27-2234-distro-basic-smithi/
- http://pulpito.ceph.com/kchai-2020-03-28_05:53:06-rgw-nautilus-kefu2-testing-2020-03-27-2234-distro-basic-smithi/
- http://pulpito.ceph.com/kchai-2020-03-28_05:57:39-fs-nautilus-kefu2-testing-2020-03-27-2234-distro-basic-smithi/
- http://pulpito.ceph.com/kchai-2020-03-28_05:58:21-rbd-nautilus-kefu2-testing-2020-03-27-2234-distro-basic-smithi/
- http://pulpito.ceph.com/kchai-2020-03-28_06:47:46-rados-nautilus-kefu2-testing-2020-03-28-1208-distro-basic-smithi/
- http://pulpito.ceph.com/kchai-2020-03-28_09:22:33-rbd-nautilus-kefu2-testing-2020-03-28-1555-distro-basic-smithi/
- http://pulpito.ceph.com/kchai-2020-03-28_09:23:03-rgw-nautilus-kefu2-testing-2020-03-28-1555-distro-basic-smithi/
- http://pulpito.ceph.com/kchai-2020-03-28_09:26:23-rados-nautilus-kefu2-testing-2020-03-28-1555-distro-basic-smithi/
- http://pulpito.ceph.com/kchai-2020-03-28_10:18:54-rgw-nautilus-kefu2-testing-2020-03-28-1555-distro-basic-smithi/
- http://pulpito.ceph.com/kchai-2020-03-28_10:21:26-rados-nautilus-kefu2-testing-2020-03-28-1555-distro-basic-smithi/
- http://pulpito.ceph.com/kchai-2020-03-28_10:48:38-rbd-nautilus-kefu2-testing-2020-03-28-1555-distro-basic-smithi/
- http://pulpito.ceph.com/kchai-2020-03-28_11:23:30-rados-nautilus-kefu2-testing-2020-03-28-1555-distro-basic-smithi/
- http://pulpito.ceph.com/kchai-2020-03-28_11:24:38-rbd-nautilus-kefu2-testing-2020-03-28-1555-distro-basic-smithi/

at the end, none of the failures is related to this change.

**Comment by kshtsk** [comment]
http://51.68.86.123:8081/runner-2020-03-30_13:31:05-smoke-nautilus-distro-basic-ovh/

**Comment by kshtsk** [comment]
```
2020-03-30T13:45:53.463 INFO:tasks.ceph_client:Setting up client nodes...
2020-03-30T13:45:53.465 ERROR:teuthology.contextutil:Saw exception from nested tasks
Traceback (most recent call last):
  File "/home/worker/src/teuthology_master/teuthology/contextutil.py", line 32, in nested
    vars.append(enter())
  File "/usr/lib64/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/home/worker/src/github.com_ceph_ceph_PR#34171/qa/tasks/ceph.py", line 830, in cluster
    cclient.create_keyring(ctx, cluster_name)
  File "/home/worker/src/github.com_ceph_ceph_PR#34171/qa/tasks/ceph_client.py", line 19, in create_keyring
    for remote, roles_for_host in clients.remotes.iteritems():
AttributeError: 'dict' object has no attribute 'iteritems'
```

**Comment by kshtsk** [comment]
@tchaikov it is run on recent py3 teuthology ^

**Comment by tchaikov** [comment]
@kshtsk thank you! could you rerun the tests?

**Comment by cbodley** [comment]
the rgw suite has some failures that look related:
```
global name 'chance_test_min_size' is not defined
global name 'split_user' is not defined
```

**Comment by tchaikov** [comment]
@cbodley thanks for looking into the test results. these issues have been fixed.

**Comment by kshtsk** [comment]
@tchaikov 
```
2020-03-30T17:23:35.851 INFO:tasks.workunit.client.0.target-py3-043.stderr:fatal: reference is not a tree: a88a277341e7515c183d918be3402ae5880161ba
2020-03-30T17:23:35.851 DEBUG:teuthology.orchestra.run:got remote process result: 128
2020-03-30T17:23:35.853 ERROR:teuthology.run_tasks:Saw exception from tasks.
Traceback (most recent call last):
  File "/home/worker/src/teuthology_master/teuthology/run_tasks.py", line 86, in run_tasks
    manager = run_one_task(taskname, ctx=ctx, config=config)
  File "/home/worker/src/teuthology_master/teuthology/run_tasks.py", line 65, in run_one_task
    return task(**kwargs)
  File "/home/worker/src/github.com_ceph_ceph_PR#34171/qa/tasks/workunit.py", line 138, in task
    cleanup=cleanup)
  File "/home/worker/src/github.com_ceph_ceph_PR#34171/qa/tasks/workunit.py", line 288, in _spawn_on_all_clients
    timeout=timeout)
  File "/home/worker/src/teuthology_master/teuthology/parallel.py", line 87, in __exit__
    for result in self:
  File "/home/worker/src/teuthology_master/teuthology/parallel.py", line 101, in __next__
    resurrect_traceback(result)
  File "/home/worker/src/teuthology_master/teuthology/parallel.py", line 37, in resurrect_traceback
    reraise(*exc_info)
  File "/home/worker/src/teuthology_master/virtualenv/lib/python3.6/site-packages/six.py", line 703, in reraise
    raise value
  File "/home/worker/src/teuthology_master/teuthology/parallel.py", line 24, in capture_traceback
    return func(*args, **kwargs)
  File "/home/worker/src/github.com_ceph_ceph_PR#34171/qa/tasks/workunit.py", line 335, in _run_tests
    args=refspec.clone(git_url, clonedir))
  File "/home/worker/src/teuthology_master/teuthology/orchestra/remote.py", line 201, in run
    r = self._runner(client=self.ssh, name=self.shortname, **kwargs)
  File "/home/worker/src/teuthology_master/teuthology/orchestra/run.py", line 473, in run
    r.wait()
  File "/home/worker/src/teuthology_master/teuthology/orchestra/run.py", line 162, in wait
    self._raise_for_status()
  File "/home/worker/src/teuthology_master/teuthology/orchestra/run.py", line 184, in _raise_for_status
    node=self.hostname, label=self.label
teuthology.exceptions.CommandFailedError: Command failed on target-py3-043 with status 128: 'rm -rf /home/ubuntu/cephtest/clone.client.0 && git clone https://github.com/ceph/ceph.git /home/ubuntu/cephtest/clone.client.0 && cd /home/ubuntu/cephtest/clone.client.0 && git checkout a88a277341e7515c183d918be3402ae5880161ba'
```
Not sure it is related http://51.68.86.123/teuthology/runner-2020-03-30_17:06:38-smoke-nautilus-distro-basic-ovh/38/teuthology.log

**Comment by tchaikov** [comment]
```
  suite_repo: https://github.com/ceph/ceph.git
  suite_sha1: a88a277341e7515c183d918be3402ae5880161ba
```

and i cannot find this sha1 in this repo. so i don't think it's related.

**Comment by kshtsk** [comment]
> ```
>   suite_repo: https://github.com/ceph/ceph.git
>   suite_sha1: a88a277341e7515c183d918be3402ae5880161ba
> ```
> 
> and i cannot find this sha1 in this repo. so i don't think it's related.

@tchaikov Of course it is missing, because it is in another branch, looks like it is a bug in `workunit`, it does not respect `suite-branch` while trying to clone the code :-(

**Comment by kshtsk** [comment]
```2020-04-01T19:50:50.377 INFO:teuthology.orchestra.run.target-py3-047:> CEPH_CLIENT_ID=0 adjust-ulimits ceph-coverage /home/ubuntu/cephtest/archive/coverage ceph_test_rados --no-omap --ec-pool --max-ops 400000 --objects 1024 --max-in-flight 64 --size 4000000 --min-stride-size 400000.0 --max-stride-size 800000.0 --max-seconds 600 --op read 100 --op write 0.0 --op delete 50 --op snap_create 50 --op snap_remove 50 --op rollback 50 --op setattr 25 --op rmattr 25 --op copy_from 50 --op append 50.0 --op write_excl 0.0 --op append_excl 50.0 --pool unique_pool_0
2020-04-01T19:50:50.389 ERROR:teuthology:Uncaught exception (Hub)
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 766, in gevent._greenlet.Greenlet.run
  File "/home/worker/src/github.com_tchaikov_ceph_nautilus-py3/qa/tasks/rados.py", line 260, in thread
    run.wait(tests.itervalues())
AttributeError: 'dict' object has no attribute 'itervalues'
2020-04-01T19:50:50.391 ERROR:teuthology.run_tasks:Manager failed: rados
Traceback (most recent call last):
  File "/home/worker/src/teuthology_master/teuthology/run_tasks.py", line 159, in run_tasks
    suppress = manager.__exit__(*exc_info)
  File "/usr/lib64/python3.6/contextlib.py", line 88, in __exit__
    next(self.gen)
  File "/home/worker/src/github.com_tchaikov_ceph_nautilus-py3/qa/tasks/rados.py", line 272, in task
    running.get()
  File "src/gevent/greenlet.py", line 709, in gevent._greenlet.Greenlet.get
  File "src/gevent/greenlet.py", line 317, in gevent._greenlet.Greenlet._raise_exception
  File "/home/worker/src/teuthology_master/virtualenv/lib/python3.6/site-packages/gevent/_compat.py", line 47, in reraise
    raise value.with_traceback(tb)
  File "src/gevent/greenlet.py", line 766, in gevent._greenlet.Greenlet.run
  File "/home/worker/src/github.com_tchaikov_ceph_nautilus-py3/qa/tasks/rados.py", line 260, in thread
    run.wait(tests.itervalues())
AttributeError: 'dict' object has no attribute 'itervalues'```

**Comment by kshtsk** [comment]
```2020-04-01T19:23:05.799 INFO:tasks.thrashosds.thrasher:choose_action: min_in 4 min_out 0 min_live 2 min_dead 0
2020-04-01T19:23:05.806 INFO:tasks.thrashosds.thrasher:Traceback (most recent call last):
  File "/home/worker/src/github.com_tchaikov_ceph_nautilus-py3/qa/tasks/ceph_manager.py", line 884, in wrapper
    return func(self)
  File "/home/worker/src/github.com_tchaikov_ceph_nautilus-py3/qa/tasks/ceph_manager.py", line 1014, in do_thrash
    self.choose_action()()
  File "/home/worker/src/github.com_tchaikov_ceph_nautilus-py3/qa/tasks/ceph_manager.py", line 648, in grow_pool
    pool = self.ceph_manager.get_pool()
  File "/home/worker/src/github.com_tchaikov_ceph_nautilus-py3/qa/tasks/ceph_manager.py", line 1699, in get_pool
    return random.choice(self.pools.keys())
  File "/home/worker/src/teuthology_master/virtualenv/lib64/python3.6/random.py", line 261, in choice
    return seq[i]
TypeError: 'dict_keys' object does not support indexing
```

**Comment by tchaikov** [comment]
> 2020-04-01T19:50:50.389 ERROR:teuthology:Uncaught exception (Hub)
> Traceback (most recent call last):
>   File "src/gevent/greenlet.py", line 766, in gevent._greenlet.Greenlet.run
>   File "/home/worker/src/github.com_tchaikov_ceph_nautilus-py3/qa/tasks/rados.py", line 260, in thread
>     run.wait(tests.itervalues())
> AttributeError: 'dict' object has no attribute 'itervalues'
> 2020-04-01T19:50:50.391 ERROR:teuthology.run_tasks:Manager failed: rados
> Traceback (most recent call last):
>   File "/home/worker/src/teuthology_master/teuthology/run_tasks.py", line 159, in run_tasks
>     suppress = manager.__exit__(*exc_info)
>   File "/usr/lib64/python3.6/contextlib.py", line 88, in __exit__
>     next(self.gen)
>   File "/home/worker/src/github.com_tchaikov_ceph_nautilus-py3/qa/tasks/rados.py", line 272, in task
>     running.get()
>   File "src/gevent/greenlet.py", line 709, in gevent._greenlet.Greenlet.get
>   File "src/gevent/greenlet.py", line 317, in gevent._greenlet.Greenlet._raise_exception
>   File "/home/worker/src/teuthology_master/virtualenv/lib/python3.6/site-packages/gevent/_compat.py", line 47, in reraise
>     raise value.with_traceback(tb)
>   File "src/gevent/greenlet.py", line 766, in gevent._greenlet.Greenlet.run
>   File "/home/worker/src/github.com_tchaikov_ceph_nautilus-py3/qa/tasks/rados.py", line 260, in thread
>     run.wait(tests.itervalues())
> AttributeError: 'dict' object has no attribute 'itervalues'```

thanks, dd8bacdb131db74411a07d2952182c7218472769 backported.

**Comment by tchaikov** [comment]
> 2020-04-01T19:23:05.806 INFO:tasks.thrashosds.thrasher:Traceback (most recent call last):
>   File "/home/worker/src/github.com_tchaikov_ceph_nautilus-py3/qa/tasks/ceph_manager.py", line 884, in wrapper
>     return func(self)
>   File "/home/worker/src/github.com_tchaikov_ceph_nautilus-py3/qa/tasks/ceph_manager.py", line 1014, in do_thrash
>     self.choose_action()()
>   File "/home/worker/src/github.com_tchaikov_ceph_nautilus-py3/qa/tasks/ceph_manager.py", line 648, in grow_pool
>     pool = self.ceph_manager.get_pool()
>   File "/home/worker/src/github.com_tchaikov_ceph_nautilus-py3/qa/tasks/ceph_manager.py", line 1699, in get_pool
>     return random.choice(self.pools.keys())
>   File "/home/worker/src/teuthology_master/virtualenv/lib64/python3.6/random.py", line 261, in choice
>     return seq[i]
> TypeError: 'dict_keys' object does not support indexing



> 2020-04-01T19:23:05.806 INFO:tasks.thrashosds.thrasher:Traceback (most recent call last):
>   File "/home/worker/src/github.com_tchaikov_ceph_nautilus-py3/qa/tasks/ceph_manager.py", line 884, in wrapper
>     return func(self)
>   File "/home/worker/src/github.com_tchaikov_ceph_nautilus-py3/qa/tasks/ceph_manager.py", line 1014, in do_thrash
>     self.choose_action()()
>   File "/home/worker/src/github.com_tchaikov_ceph_nautilus-py3/qa/tasks/ceph_manager.py", line 648, in grow_pool
>     pool = self.ceph_manager.get_pool()
>   File "/home/worker/src/github.com_tchaikov_ceph_nautilus-py3/qa/tasks/ceph_manager.py", line 1699, in get_pool
>     return random.choice(self.pools.keys())
>   File "/home/worker/src/teuthology_master/virtualenv/lib64/python3.6/random.py", line 261, in choice
>     return seq[i]
> TypeError: 'dict_keys' object does not support indexing

fixed in #34264, and backported as well.

**Comment by tchaikov** [comment]
- [ ] rados
  - http://pulpito.ceph.com/kchai-2020-04-23_12:39:31-rados:basic-nautilus-distro-basic-smithi/

**Comment by kshtsk** [comment]
http://51.68.93.158:8081/runner-2020-04-23_13:36:42-smoke-nautilus-distro-basic-ovh/

**Comment by kshtsk** [comment]
http://51.68.93.158:8081/runner-2020-04-23_13:38:22-smoke-nautilus-distro-basic-ovh/
http://51.68.93.158/teuthology/runner-2020-04-23_13:38:22-smoke-nautilus-distro-basic-ovh/44/teuthology.log
```
2020-04-23T21:43:35.441 ERROR:teuthology:Uncaught exception (Hub)
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 766, in gevent._greenlet.Greenlet.run
  File "/home/worker/src/github.com_tchaikov_ceph_nautilus-py3/qa/tasks/rados.py", line 260, in thread
    run.wait(tests.itervalues())
AttributeError: 'dict' object has no attribute 'itervalues'
2020-04-23T21:43:35.443 ERROR:teuthology.run_tasks:Manager failed: rados
Traceback (most recent call last):
  File "/home/worker/src/teuthology_master/teuthology/run_tasks.py", line 167, in run_tasks
    suppress = manager.__exit__(*exc_info)
  File "/usr/lib64/python3.6/contextlib.py", line 88, in __exit__
    next(self.gen)
  File "/home/worker/src/github.com_tchaikov_ceph_nautilus-py3/qa/tasks/rados.py", line 272, in task
    running.get()
  File "src/gevent/greenlet.py", line 709, in gevent._greenlet.Greenlet.get
  File "src/gevent/greenlet.py", line 317, in gevent._greenlet.Greenlet._raise_exception
  File "/home/worker/src/teuthology_master/virtualenv/lib/python3.6/site-packages/gevent/_compat.py", line 47, in reraise
    raise value.with_traceback(tb)
  File "src/gevent/greenlet.py", line 766, in gevent._greenlet.Greenlet.run
  File "/home/worker/src/github.com_tchaikov_ceph_nautilus-py3/qa/tasks/rados.py", line 260, in thread
    run.wait(tests.itervalues())
AttributeError: 'dict' object has no attribute 'itervalues'
```

**Comment by kshtsk** [comment]
this is more interesting:
http://51.68.93.158/teuthology/runner-2020-04-23_13:38:22-smoke-nautilus-distro-basic-ovh/54/teuthology.log
```
2020-04-23T22:12:49.432 ERROR:teuthology.contextutil:Saw exception from nested tasks
Traceback (most recent call last):
  File "/home/worker/src/teuthology_master/teuthology/contextutil.py", line 32, in nested
    vars.append(enter())
  File "/usr/lib64/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/home/worker/src/github.com_tchaikov_ceph_nautilus-py3/qa/tasks/swift.py", line 92, in create_users
    '--access', 'full',
  File "/home/worker/src/teuthology_master/teuthology/orchestra/cluster.py", line 64, in run
    return [remote.run(**kwargs) for remote in remotes]
  File "/home/worker/src/teuthology_master/teuthology/orchestra/cluster.py", line 64, in <listcomp>
    return [remote.run(**kwargs) for remote in remotes]
  File "/home/worker/src/teuthology_master/teuthology/orchestra/remote.py", line 203, in run
    r = self._runner(client=self.ssh, name=self.shortname, **kwargs)
  File "/home/worker/src/teuthology_master/teuthology/orchestra/run.py", line 467, in run
    cwd=cwd)
  File "/home/worker/src/teuthology_master/teuthology/orchestra/run.py", line 67, in __init__
    self.command = quote(args)
  File "/home/worker/src/teuthology_master/teuthology/orchestra/run.py", line 258, in quote
    return ' '.join(_quote(args))
  File "/home/worker/src/teuthology_master/teuthology/orchestra/run.py", line 256, in _quote
    yield pipes.quote(a)
  File "/usr/lib64/python3.6/shlex.py", line 314, in quote
    if _find_unsafe(s) is None:
TypeError: cannot use a string pattern on a bytes-like object
```

**Comment by kshtsk** [comment]
looks like sage removed swift test in master and we didn't fix it for py3, but nautilus still has it.

**Comment by tchaikov** [comment]
jenkins test make check

**Comment by tchaikov** [comment]
> Since elements of _stopping_ and _actives_ are not used an only length is use, I would suggest to refactor them be already a numbers:
> 
> ```
> stopping_ranks = sum(1 for _ in ranks if "up:stopping" == _['state'])
> active_ranks = sum(1 for _ in ranks if "up:active" == _['state'] 
>                                     and "laggy_since" not in _)
> ```

thanks @kyr i updated the PR targeting master at #34857 , and re-did the cherry-pick.

**Comment by tchaikov** [comment]
jenkins test make check

**Comment by tchaikov** [comment]
```
//home/jenkins-build/build/workspace/ceph-pull-requests/qa/standalone/ceph-helpers.sh:1060: get_config:  ceph --format json daemon /tmp/ceph-asok.28717/ceph-mon.a.asok config get mon_host
/home/jenkins-build/build/workspace/ceph-pull-requests/src/test/mgr/mgr-dashboard-smoke.sh:40: TEST_dashboard:  timeout 30 ceph mon stat
/home/jenkins-build/build/workspace/ceph-pull-requests/src/test/mgr/mgr-dashboard-smoke.sh:40: TEST_dashboard:  return 1
```

**Comment by tchaikov** [comment]
jenkins test make check

**Comment by kshtsk** [comment]
I've run smoke tests again on openstacks for centos - passed.
Ran smoke for teuthology py2, one failure at the moment, related ntpd or chrony, not sure it is related:
http://51.91.146.166:8081/runner-2020-05-22_10:14:07-smoke-nautilus-distro-basic-ovh/

**Comment by tchaikov** [comment]
@kshtsk please checkout https://github.com/ceph/ceph/pull/34171#issue-393577699 . smoke test is known to be clean. cephfs, rbd, rgw, and rados are not.

**Comment by kshtsk** [comment]
> @kshtsk please checkout [#34171 (comment)](https://github.com/ceph/ceph/pull/34171#issue-393577699) . smoke test is known to be clean. cephfs, rbd, rgw, and rados are not.

@tchaikov yes, this is just double check, I wanted to make sure it is still passing in open stack environment. Kicked another run on rados/basic, waiting results.

**Pull request merged**
