### PR TITLE
test: Don't write to a poolid that this test might not have created

### PR DESCRIPTION
**Pull request by dzafman**

### CODE REVIEW

**Comment by dzafman** [comment]
Waiting for wip-zafman-testing2 to build so I can run the modified test to make sure it passes.

**Comment by tchaikov** [comment]
@dzafman, yes, the pool might not have been created yet, but `Objecter::_op_submit()` will retry if the pool is DNE. and it's fine to issue write op to the pool being created, i think. what issue did you run into?

**Comment by dzafman** [comment]
@tchaikov Between the 2 pool creates another test created a pool, so that the second pool is NOT poolid (first pool) + 1.  That poolid belongs to another tests pool and the write createe object "foo" in the other test's pool.  The other test was testing enumerate and the extra object caused the test to fail.

**Comment by tchaikov** [comment]
@dzafman, i see. so this test is a little bit fragile that we could be writing to another pool created by another test but in the same cluster. in that case, we fail to test the racing. but we cannot use `rados_ioctx_create()`, because the pool is not yet created when we try to look up the  pool by its name.

**Pull request merged**
