### PR TITLE
pacific: mds: "cluster [WRN] Scrub error on inode 0x1000000039d (/client.0/tmp/blogbench-1.0/src/blogtest_in) see mds.a log and `damage ls` output for details"

### PR DESCRIPTION
**Pull request by batrick**
https://tracker.ceph.com/issues/50253

### CODE REVIEW

**Comment by batrick** [comment]
jenkins test api

**Comment by batrick** [comment]
jenkins test docs

**Comment by batrick** [comment]
jenkins test docs

**Comment by batrick** [comment]
jenkins test api

**Comment by batrick** [comment]
jenkins test make check

**Comment by batrick** [comment]
`Reviewed-by: Patrick Donnelly <pdonnell@redhat.com>`

**Review by yuriw — APPROVED** [review]
Reviewed-by: Patrick Donnelly <pdonnell@redhat.com>

**Pull request merged**
