### PR TITLE
DNM: hammer: rgw: the swift key remains after removing a subuser

### PR DESCRIPTION
**Pull request by dachary**
http://tracker.ceph.com/issues/14328

### CODE REVIEW

**Comment by dachary** [comment]
@yehudasa does this backport look good to merge ? It passed a run of the hammer rgw suite ( see http://tracker.ceph.com/issues/13356#note-36 ) except two occurrences of a known subuser bug ( http://tracker.ceph.com/issues/14375).

**Comment by dachary** [comment]
DNM until http://tracker.ceph.com/issues/14375 is clarified

**Comment by smithfarm** [comment]
@dachary http://tracker.ceph.com/issues/14375 was resolved by #7301 - does that need to be backported to hammer along with this?

**Comment by oritwas** [comment]
@smithfarm , yes it should also be backported

**Comment by smithfarm** [comment]
@dachary #9961 opened, so I guess we could revisit whether this still needs to be DNM

**Comment by oritwas** [comment]
@smithfarm , this backport can be merged.
did it pass a teuthology run?

**Comment by smithfarm** [comment]
@oritwas No, it was not included in the integration branch because it was marked DNM.

**Comment by oritwas** [comment]
This breaks http://tracker.ceph.com/issues/14375, created a new pr #10718
that contains both cherry picks of both patches

**Pull request closed without merging**
