### PR TITLE
luminous: mds: create health warning if we detect metadata (journal) writes are slow

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/25046

### CODE REVIEW

**Comment by smithfarm** [comment]
test this please

**Comment by smithfarm** [comment]
```
[ 26%] Building CXX object src/client/CMakeFiles/client.dir/Client.cc.o
In file included from /home/jenkins-build/build/workspace/ceph-pull-requests/src/mds/SimpleLock.h:22:0,
                 from /home/jenkins-build/build/workspace/ceph-pull-requests/src/mds/CDentry.h:32,
                 from /home/jenkins-build/build/workspace/ceph-pull-requests/src/mds/CInode.h:35,
                 from /home/jenkins-build/build/workspace/ceph-pull-requests/src/messages/MMDSCacheRejoin.h:24,
                 from /home/jenkins-build/build/workspace/ceph-pull-requests/src/msg/Message.cc:130:
/home/jenkins-build/build/workspace/ceph-pull-requests/src/mds/MDSContext.h:100:16: error: ‘spinlock’ in namespace ‘ceph’ does not name a type
   static ceph::spinlock ctx_list_lock;
                ^
src/CMakeFiles/common-objs.dir/build.make:1359: recipe for target 'src/CMakeFiles/common-objs.dir/msg/Message.cc.o' failed
make[3]: *** [src/CMakeFiles/common-objs.dir/msg/Message.cc.o] Error 1
make[3]: *** Waiting for unfinished jobs....
[ 26%] Building CXX object src/client/CMakeFiles/client.dir/Dentry.cc.o
[ 26%] Building CXX object src/client/CMakeFiles/client.dir/Fh.cc.o
CMakeFiles/Makefile2:918: recipe for target 'src/CMakeFiles/common-objs.dir/all' failed
make[2]: *** [src/CMakeFiles/common-objs.dir/all] Error 2
make[2]: *** Waiting for unfinished jobs....
[ 26%] Building CXX object src/client/CMakeFiles/client.dir/Inode.cc.o
In file included from /home/jenkins-build/build/workspace/ceph-pull-requests/src/mds/SimpleLock.h:22:0,
                 from /home/jenkins-build/build/workspace/ceph-pull-requests/src/mds/CDentry.h:32,
                 from /home/jenkins-build/build/workspace/ceph-pull-requests/src/mds/CInode.h:35,
                 from /home/jenkins-build/build/workspace/ceph-pull-requests/src/mds/LogSegment.h:22,
                 from /home/jenkins-build/build/workspace/ceph-pull-requests/src/mds/MDLog.h:47,
                 from /home/jenkins-build/build/workspace/ceph-pull-requests/src/mds/Beacon.cc:24:
/home/jenkins-build/build/workspace/ceph-pull-requests/src/mds/MDSContext.h:100:16: error: ‘spinlock’ in namespace ‘ceph’ does not name a type
   static ceph::spinlock ctx_list_lock;
                ^
/home/jenkins-build/build/workspace/ceph-pull-requests/src/mds/Beacon.cc: In member function ‘void Beacon::notify_health(const MDSRank*)’:
/home/jenkins-build/build/workspace/ceph-pull-requests/src/mds/Beacon.cc:473:34: error: ‘g_conf’ cannot be used as a function
     auto complaint_time = g_conf()->osd_op_complaint_time;
                                  ^
src/mds/CMakeFiles/mds.dir/build.make:134: recipe for target 'src/mds/CMakeFiles/mds.dir/Beacon.cc.o' failed
make[3]: *** [src/mds/CMakeFiles/mds.dir/Beacon.cc.o] Error 1
```

**Comment by smithfarm** [comment]
@batrick Any pointers for me on https://github.com/ceph/ceph/pull/23775#issuecomment-420415700

?

**Comment by batrick** [comment]
@smithfarm sorry for the confusion!! Zheng took over the backport. See https://github.com/ceph/ceph/pull/24171

**Comment by smithfarm** [comment]
closing

**Pull request closed without merging**
