### PR TITLE
common/syncfs: fall back to sync(2) if syncfs(2) not available

### PR DESCRIPTION
**Pull request by tchaikov**
Fixes: #12512, http://tracker.ceph.com/issues/12512
Signed-off-by: Kefu Chai <kchai@redhat.com>

### CODE REVIEW

**Comment by yuyuyu101** [comment]
COOL!

**Comment by tchaikov** [comment]
@dachary i am not sure this fix is the right way to fix this issue. because the valgrind keeps printing out error messages when we are using unsupported syscall. which is a little bit annoying. but as the new kernels always support this syncfs() sys call. so it might be okay.

what do you think?

also i ran rados suites with this patch at http://149.202.175.39:8081, most of the tests passed, and lots of them failed, but i think they are not related  .

**Comment by liewegas** [comment]
I'm less worrieda bout the warnings since syncfs(2) has been around for so long.  This patch definitely is an improvement though since we should fall back to sync(2).  I'm surprised we weren't doing it before?

**Comment by dachary** [comment]
@tchaikov the patch looks good to me. Could you just point to a specific job that was failing before this patch and now passes ? http://149.202.175.39:8081 has a lot, I'm not sure which one I should look at. The valgrind messages can probably be suppressed to avoid the noise, but that does not need to be with this patch, IMHO.

**Comment by tchaikov** [comment]
> I'm surprised we weren't doing it before?

@liewegas we do test for this feature in `GenericFileStoreBackend::detect_features()`, but just prints the test result with ` dout(0)` without keeping it around. when `GenericFileStoreBackend::syncfs()` is called, we simply trust the macro defined in the building environment.

@dachary  sorry, i forgot to put the test result here:

before this change
---
http://149.202.175.39:8081/ubuntu-2015-07-29_04:25:24-rados-master---basic-openstack/5/


after this change
---
http://149.202.175.39:8081/ubuntu-2015-07-30_02:52:03-rados-wip-12512---basic-openstack/58/

**Comment by dachary** [comment]
Thanks for the links, looks great :-)

<pre>
Reviewed-by: Loic Dachary &lt;ldachary@redhat.com>
</pre>

**Pull request merged**
