### PR TITLE
doc: fix the format of peering.rst

### PR DESCRIPTION
**Pull request by wonzhq**
Fix one of the number in the item list, and also the indention of items
1 to 9.

Signed-off-by: Zhiqiang Wang <zhiqiang.wang@intel.com>

### CODE REVIEW

**Comment by dachary** [comment]
A false negative, once again because an osd fails to come up.

**Comment by wonzhq** [comment]
@tchaikov yep, using `1` or `a` for the 1st one, and `#` for the remaining would be a good idea.

**Comment by tchaikov** [comment]
compiled in local env. the doc renders great!

i am taking the liberty of merging it. as the build bot does not build docs.

**Comment by wonzhq** [comment]
@tchaikov btw, how do you compile the doc? I tried 'make html' in the doc subdir. But it says there is nothing to do. Should I install the `sphinx` package?

**Comment by tchaikov** [comment]
@wonzhq http://ceph.com/docs/master/start/documenting-ceph/#build-the-source .

the Makefile under the `doc` directory only serves for including the .rst files the tarball.

> Should I install the `sphinx` package?

and per http://ceph.com/docs/master/start/documenting-ceph/#build-the-source-first-time , yes =)

**Comment by wonzhq** [comment]
@tchaikov got it, thx!

**Pull request merged**
