### PR TITLE
luminous: backport various fixes to mgr/influx module

### PR DESCRIPTION
**Pull request by wido**
We have a lot of fixes in master for the mgr/influx module, but these were never backported to Luminous.

The current Influx module is rather crippled and has many problems. Would be great if these fixes would make it into 12.2.6

### CODE REVIEW

**Comment by theanalyst** [comment]
@wido is there a tracker issue tracking this in master or for luminous?

**Comment by wido** [comment]
@theanalyst No, there isn't one. I found out yesterday that many of these fixes weren't backported to Luminous.

Shall I create a generic issue and link this PR there?

**Comment by theanalyst** [comment]
@wido if there was no tracker for the master pr then no need to create an issue as such, but the workflow should be that all backport commits are cherry-picked from master using a git cherry-pick -x so that they can be traced back. An issue makes it easier to track this process, but okay without ti. 
Can you redo this pr with a cherry-pick -x of the master commits so that we know the commit source

**Comment by wido** [comment]
Clear! Done that @theanalyst 

Used '-x' with the cherry-pick

**Comment by theanalyst** [comment]
thanks

**Comment by yuriw** [comment]
[wip-yuri-testing-2018-06-08-1529-luminous](https://trello.com/c/XYvW5z42/324-wip-yuri-testing-2018-06-08-1529-luminous)

**Comment by theanalyst** [comment]
jenkins test this please

**Pull request merged**
