### PR TITLE
os/bluestore: fix additional errors during missed shared blob repair.

### PR DESCRIPTION
**Pull request by ifed01**
Fixes: https://tracker.ceph.com/issues/51762
 Signed-off-by: Igor Fedotov <ifedotov@suse.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by tchaikov** [comment]
jenkins test make check

**Comment by tchaikov** [comment]
- https://pulpito.ceph.com/kchai-2021-07-24_05:22:39-rados-wip-kefu-testing-2021-07-24-1158-distro-basic-smithi/
- https://pulpito.ceph.com/kchai-2021-07-24_10:59:41-rados-wip-kefu-testing-2021-07-24-1507-distro-basic-smithi/

**Review by aclamk — APPROVED** [review]
Good fix!
@ifed01 Do you have an idea for simple test that checks if we properly recovered statfs sizes?

**Comment by ifed01** [comment]
> Good fix!
> @ifed01 Do you have an idea for simple test that checks if we properly recovered statfs sizes?

@aclamk - IMO the added BluestoreBrokenNoSharedBlobRepairTest should do that - final fsck verifies whether statfs is correct.
Am I missing something in you question?

**Pull request merged**
