### PR TITLE
[RFC] ceph-volume: DriveGroups in ceph-volume

### PR DESCRIPTION
**Pull request by jschmid1**
This pullrequest is supposed to be a reference implementation of the DriveGroup concept in ceph-volume.

ceph-volume would be a well suited place to host the logic since all the needed data comes from ceph-volume's inventory function `Devices().devices`

We can also re-use the `Batch()` module to apply DriveGroups to the cluster.

<details><summary>ceph-volume drivegroups show/apply <path_to_drivegroups.yml></summary>

```
data1:/ceph-volume # ceph-volume drivegroups show ceph_volume/drivegroups/example.yaml
--> Processing DriveGroup <default>
--> Initializing filter <all> with value <True>
#TODO Implement a common interface for module<->module calls

Total OSDs: 8

  Type            Path                                                    LV Size         % of device
----------------------------------------------------------------------------------------------------
  [data]          /dev/vda                                                19.00 GB        100.0%
----------------------------------------------------------------------------------------------------
  [data]          /dev/vdb                                                19.00 GB        100.0%
----------------------------------------------------------------------------------------------------
  [data]          /dev/vdc                                                19.00 GB        100.0%
----------------------------------------------------------------------------------------------------
  [data]          /dev/vdd                                                19.00 GB        100.0%
----------------------------------------------------------------------------------------------------
  [data]          /dev/vde                                                19.00 GB        100.0%
----------------------------------------------------------------------------------------------------
  [data]          /dev/vdf                                                19.00 GB        100.0%
----------------------------------------------------------------------------------------------------
  [data]          /dev/vdg                                                9.00 GB         100.0%
----------------------------------------------------------------------------------------------------
  [data]          /dev/vdh                                                9.00 GB         100.0%


```

</details>

<details><summary>drivegroups.yaml</summary>

``` yaml
default:
  target: 'fnmatch_target'
  data_devices:
    all: true
```

</details>

This is the most basic DriveGroup possible. The current specification allows to describe all kinds of drives and drive combinations. Please find the spec here:

<details><summary>DriveGroup Specification</summary>

``` yaml
drive_group_default_name:
  target: *
  data_devices:
    device_spec: arg 
  db_devices:
    device_spec: arg
  wal_devices:
    device_spec: arg
  block_wal_size: '5G' (optional)
  block_db_size: '5G' (optional)
  osds_per_device: 1 # number of osd daemons per device. To fully utilize nvme devices multiple osds are required.  # not implemented
  format: bluestore/filestore (defaults to bluestore)
  encrypted: True/False (defaults to False)
  db_slots: 5 (optional)
  wal_slots: 1 (optional)

```
</details>

`device_spec` is a placeholder for drive matchers like `model`, `vendor`, `size` and `rotational`.
Please see the [  DriveGroups wiki on the DeepSea github page](https://github.com/SUSE/DeepSea/wiki/Drive-Groups) for a more detailed description (and examples)

--------------------

There is a incomplete implementation for DriveGroups in https://github.com/ceph/ceph/blob/2ea3df19679adcdc4834e2c0ea6d748b40fdfd2d/src/pybind/mgr/orchestrator.py#L552

which is arguably the right place for the specification, but not for the selection/filtering logic.

-----------------
Unittests are in the pipeline and will be added once we reached consensus.
Obviously this PR is not well rounded and contains issues. It will be overhauled after a later stage.

Signed-off-by: Joshua Schmid <jschmid@suse.de>

~- [ ] References tracker ticket~
~- [ ] Updates documentation if necessary~
~- [ ] Includes tests for new functionality or reproducer for bug~

### CODE REVIEW

**Comment by sebastian-philipp** [comment]
Would be nice to have a bit of documentation of how to use it. Something to look at and see how it would work

**Comment by alfredodeza** [comment]
I'm going to be opposed to this kind of logic being pushed into ceph-volume because a higher-level configuration-management tool can do this with ease. In the past, the argument has been that if it doesn't live in ceph-volume then "every tool needs to implement the same logic". And _to me_ that is a reasonable approach because otherwise it makes ceph-volume an incredibly complex tool that is no longer concentrating in producing an OSD.

This is the same reason I was thoroughly opposed to have functionality that listed devices or reported on devices from the OS. Since now that functionality lives in there, it starts to feel more natural to force ceph-volume into doing other things beyond that.

I welcome other reviewers to give their feedback, but I am going to be -1 on these types of proposals.

**Comment by sebastian-philipp** [comment]
@alfredodeza Let's look for a moment at the orchestrator stacks

orchestrator

Somewhere we need to make system calls out of Drive Groups. And we need the c-v inventory for that. 

Rook doesn't expose the full c-v inventory right now, so it must be in that layer or below. If Rook is supposed to do the conversion, it will be implemented differently, as they're using Go. And I'd rather have one implementation instead of two. 

The only other alternative would be a wrapper executable around c-v that calls, but that would be silly :smile: 

Implementing the conversion on the orchestrator module level also doesn't work, as it would require a very low level interface that Rook is not going to provide

**Comment by jmolmo** [comment]
I think that @alfredodeza is right. Probably including the "selection" logic into c-v introduces in this tool more complexity and probably it will cause a "mix" of functionality  in a mid-long term.
In the other hand, as @sebastian-philippsays says, we need a common point to be used by all the orchestrators. Is important to have the osd's selection logic outside the orchestrators

What about a new tool specialized in just to process the selection?  

Maybe is good to remember one of the principles of Unix philosophy:
"Make each program do one thing well. To do a new job, build a fresh rather than complicate old programs by adding new "features"."

This has several advantages and probably is more flexible that the current approach. ( 

1. Leave c-v with only one mission, return the storage devices inventory and create osd's. Good to limit the scope of the tool. This will preserve integrity, simplicity and maintenance of the tool. 

2. We have a new a simple specific tool to make the selection, with different possibilities:

Respect functionality:
- return a list of c-v commands to create the osd's. This can be interestiin not only for orchestrators, also for other future tools.
- directly apply the commands to create the osd's

Respect implementation:
- we isolate this functionality from c-v because it has inherently a higher logic level.
- More simple, more easy to maintain... and what is more important more easy to test.
- we preserve and take care of c-v protecting  current and future functionality.

**Comment by tserong** [comment]
I agree with @sebastian-philipp. This functionality is needed by all the orchestrators, and if each one implements it separately, we're implementing the same thing four times over. The right place for it to live is a level below the orchestrators. As for whether it goes in ceph-volume or a separate tool, looking at the implementation, this seems clean and contained, and to my mind doesn't make ceph-volume especially more complicated. I also tend to think that keeping it inside ceph-volume makes for easier maintenance and testing.

**Comment by sebastian-philipp** [comment]
Also an external tool would also be tightly coupled to the CLI of ceph-volume.

**Comment by jschmid1** [comment]
I'm not completely opposed of a separate tool for this, but I've to say that the argument of 'this logically doesn't belong to ceph-volume' doesn't really strike me as valid.

ceph-volume is about creating OSDs and reading the host's devices. Creating the devices however is a manual process which shouldn't be the case for such a complicated task. So one could argue that DriveGroups are a missing feature for OSD (auto)creation.


> Respect implementation:
> * More simple, more easy to maintain... and what is more important more easy to test.

I don't think that's the case. There are quite a few utility functions that makes it very easy to test code.
Implementing a new tool would require us to basically c/p those things.

> * we preserve and take care of c-v protecting current and future functionality.

Technically we're not changing c-v functionality, we're just using existing functionality.

**Comment by liewegas** [comment]
I confess haven't been following this discussion for a while :(.  The last time I looked, though, I though we were moving toward a model where the orchestrators would pass-through, unmolested, the c-v inventory.  IIUC, that would also allow the logic to live above all of the orchestrators in mgr/orchestrator, right?  That may or may not be the best idea, but I just want to make sure I'm following the discussion.  Is the only "blocker" that rook is generating it's own simpler and abbreviated inventory?  Because this seems easy to fix...

**Comment by sebastian-philipp** [comment]
> orchestrators would pass-through, unmolested, the c-v inventory. IIUC, that would also allow the logic to live above all of the orchestrators in mgr/orchestrator, right?

Not for Rook! Rook does not provide an API for specifying the exact c-v command like arguments. Instead, Rook is continue to go towards providing an API similar to Drive Groups. So moving that logic to create c-v from above the external orchestrator to below the external orchestrator allows us to share the code between the orchestrators. 

From my point of view, this is actually the right direction for Rook. 

Where the code actually lives (in the c-v code base or in the python-ceph-common library) doesn't really matter in this context here.

> That may or may not be the best idea, but I just want to make sure I'm following the discussion. Is the only "blocker" that rook is generating it's own simpler and abbreviated inventory? Because this seems easy to fix...

Turns out that Rook's behavior to provide an API similar to Drive Group is no surprise at all. Completely idependently, the DeepSea team came up with the same solution. 

So, if Rook would at some point provide a way to directly pass through Drive Groups to c-v, it can just rely on c-v do to the right thing. Which would be cool eventually, as it could be a way to remove some complexity out of Rook.

**Comment by liewegas** [comment]
I guess the question is whether the orchestrators want to implement a DriveGroup concept at all.  If they limit themselves to acting as a pass-through, we could do it once in mgr and pass inventory and c-v incantations through and reduce our total work, right?

What about the ssh orch, for instance... does this mean that it is going to need to have a DG concept?

I'm thinking about a conversation with @leseb last year at mountpoint about adding a set of mgr/orchestrator commands to handle uniform provisioning of devices across sets of nodes, where you want to do high-level filters like which model drive to use, and also have some verification that the nodes are uniform sets.  That sort of thing would ultimately be surfaced in the CLI and dashboard, but I'm not sure if independent per-node DriveGroups makes that easier or harder.  Maybe it doesn't matter..

**Comment by jschmid1** [comment]
> I guess the question is whether the orchestrators want to implement a DriveGroup concept at all. If they limit themselves to acting as a pass-through, we could do it once in mgr and pass inventory and c-v incantations through and reduce our total work, right?
> 
> What about the ssh orch, for instance... does this mean that it is going to need to have a DG concept?

Mh, I think ultimately the DriveGroup**Distribution** needs to live one level above ceph-volume (mgr,orch,?).

> 
> I'm thinking about a conversation with @leseb last year at mountpoint about adding a set of mgr/orchestrator commands to handle uniform provisioning of devices across sets of nodes, where you want to do high-level filters like which model drive to use, and also have some verification that the nodes are uniform sets. That sort of thing would ultimately be surfaced in the CLI and dashboard, but I'm not sure if independent per-node DriveGroups makes that easier or harder. Maybe it doesn't matter..

Having an independent DriveGroup per host isn't really something. What we're missing is some sort of a 'host pool' concept which we can match against from a higher-level tool like the orchestrator. We should still possible to pass a localized DriveGroup to ceph-volume, meaning that this PR is the ground work.

Example:

``` yaml
default_drive_group:
  target: 'host[1,2,3]' # <- for this to work we need to have drivegroups one level above ceph-volume
  data_devices:
    all: True
another_drive_group:
  target: 'host[4,5,6]'
  data_devices:
    size: 4T
```

Wherever we'd put the logic for distributing the _local_ DriveGroup it need to resolve the `target` to a 'host pool' sort of thing.

**Comment by jan--f** [comment]
> I confess haven't been following this discussion for a while :(. The last time I looked, though, I though we were moving toward a model where the orchestrators would pass-through, unmolested, the c-v inventory. IIUC, that would also allow the logic to live above all of the orchestrators in mgr/orchestrator, right? 

That was the initial concept yes. Since then we implemented this in DeepSea and it turns out DriveGroups are quite handy for specifying OSD layouts. While this code could live in higher layers (as it currently does in deepsea) but there is no technical argument for not offering this interface in c-v imho. It will still reduce code duplication in the various users of c-v.

As @jschmid1 pointed out above, the concept is not tied to single hosts. One DriveGroup spec can very well deploy a whole cluster. Only an additional layer of which host can/should get one DriveGroup can not be handled by c-v.

**Comment by sebastian-philipp** [comment]
A great example of this is https://github.com/rook/rook/pull/3213 : Rook already has some form of Drive Group. Having one standard already used by the orchestrator and DeepSea would benefit everyone.

**Comment by liewegas** [comment]
Can you speak to what DriveGroups will mean for the ssh orch?

**Comment by jschmid1** [comment]
> Can you speak to what DriveGroups will mean for the ssh orch?

Well, since the ssh orch will most likely also use ceph-volume I'd go ahead and say that it greatly simplifies the OSD deployment.

Of course people are not forced to use DriveGroups if they feel intimidated or just want to do things manually for whatever reason.

**Comment by sebastian-philipp** [comment]
> Of course people are not forced to use DriveGroups if they feel intimidated or just want to do things manually for whatever reason.

Well, actually the orchestrator API mandates Drive Groups. So, for the drive group intricacies, adding this to c-v will make the SSH orchestrator a pass-through.

**Comment by sebastian-philipp** [comment]
unstale

**Comment by sebastian-philipp** [comment]
Another reason would be: With this PR, there is an opportunity that everyone uses the same drive groups, making the dashboard implementation simpler

**Comment by bk201** [comment]
Maybe a bit off-topic. If we have the following hardware setup:
    
```
two nodes and their free devices:
node1: 2 HDDs, 1 SSD
node2: 2 HDDs, 0 SSD
```

What happen if we submit the following DriveGroupSpec to orchestrator backend like DeepSea and the dg is passed through to ceph-volume with this PR?

```
drive_group_default_name:
  target: *
  data_devices:
    rotational: 1
  db_devices:
    rotational: 0
```

node2 has no free SSD to be allocated as db device, should the operation fail? Or the operation still succeed with node1 has 1 SSD shared but node2 has none? 

Dashboard needs to allow user previewing the outcome of DriveGroup submission. If the operation will fail, the logic in Dashboard should not allow user click the submit button at all. But if the operation is succeeded with best effort, Dashboard needs to provide correct preview for every host.

**Comment by sebastian-philipp** [comment]
> Maybe a bit off-topic.

Really? If we want to have a sane Dashbaord implementation, we have to make sure, edge cases are handled equally in all backend. Ansible, DeepSea, SSH, Rook. Otherwise we're opening the path to insanity here.

**Comment by sebastian-philipp** [comment]
let me rework this to add this algorithm to python-common

**Comment by sebastian-philipp** [comment]
See #31021 for moving this to python-common. Do we want to keep this open? E.g. later make use of python-common

**Comment by jschmid1** [comment]
> See #31021 for moving this to python-common. Do we want to keep this open? E.g. later make use of python-common

Ahm, I think we can close this and re-open a PR with the needed bits later.

**Pull request closed without merging**
