### PR TITLE
cmake: do not always add py3 to TOX_ENVS

### PR DESCRIPTION
**Pull request by tchaikov**
## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by tchaikov** [comment]
jenkins test make check

**Comment by tchaikov** [comment]
jenkins test make check

**Review by epuertat — APPROVED** [review]
Looks good to me @tchaikov !

On the setup-virtualenv, and totally off-topic, while working on the Jenkins pipelines, I've been thinking on trying (a vendor neutral?) Docker image as a build environment. By only rebuilding that Docker image when deps are modified (`ceph.spec.in, debian/control, **/*requirements*.txt, ...`) we could speed up deps installation, save network resources, have a 'universal' and reproducible build environment (which would also increase the hit rate in the ccache and make the case for a distributed ccache, like sccache or xcache)...

**Comment by tchaikov** [comment]
changelog

- removed the commits of
  - pybind/mgr/dashboard: s/pytest<4/pytest/
  - pybind/mgr/dashboard: bump flake8 to 3.8.4
  - tools/setup-virtualenv.sh: pass --use-feature=2020-resolver to pip

otherwise `run-tox-mgr-dashboard` fails. i will collect these removed commits in another PR.

**Review by epuertat — COMMENTED** [review]
> changelog
> 
> * removed the commits of
>   
>   * pybind/mgr/dashboard: s/pytest<4/pytest/
>   * pybind/mgr/dashboard: bump flake8 to 3.8.4
>   * tools/setup-virtualenv.sh: pass --use-feature=2020-resolver to pip
> 
> otherwise `run-tox-mgr-dashboard` fails. i will collect these removed commits in another PR.

@tchaikov when I saw the `make check` failures I remembered why I pinned pytest 🙈

**Comment by tchaikov** [comment]
@epuertat now i understand. the failures looked unrelated to the pytest change though. but somehow they are ! =(

**Comment by epuertat** [comment]
Yeah, as pytest does lots of automagic stuff, it's not a straightfoward thing to resolve.

**Pull request merged**
