### PR TITLE
mon: remove unused variable

### PR DESCRIPTION
**Pull request by jmunhoz**
Fixes: http://tracker.ceph.com/issues/15292

Signed-off-by: Javier M. Mellid <jmunhoz@igalia.com>

### CODE REVIEW

**Comment by jecluis** [comment]
this look okay to me. You'll want to change your 'Fixes:' tag from the URL to just the ticket number though. As in `Fixes: #15292`.

**Comment by tchaikov** [comment]
@jecluis see https://github.com/ceph/ceph/pull/8312 we are start using the URL now.

**Comment by gregsfortytwo** [comment]
Well that test build went badly. Asking around if something is busted, since the gitbuilder make check bots look good.

**Comment by jecluis** [comment]
@tchaikov just read an email about that. TIL. Thanks.

**Pull request merged**
