### PR TITLE
qa/workunits/rados: pull librados files from "main" instead of "master"

### PR DESCRIPTION
**Pull request by ljflores**
Fixes: https://tracker.ceph.com/issues/57122
Signed-off-by: Laura Flores <lflores@redhat.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by ljflores** [comment]
Testing the fix here on a main test branch that recently experienced this failure:
http://pulpito.front.sepia.ceph.com/lflores-2022-08-16_18:14:56-rados:singleton-nomsgr-wip-yuri4-testing-2022-08-15-0951-distro-default-smithi/

`./teuthology/virtualenv/bin/teuthology-suite -v --suite-repo https://github.com/ljflores/ceph.git -c wip-yuri4-testing-2022-08-15-0951 -m smithi -s rados/singleton-nomsgr --suite-branch wip-librados-fix --filter-all "librados_hello_world" -p 70`

**Comment by kamoltat** [comment]
jenkins test make check arm64

**Comment by kamoltat** [comment]
Are there any documented issues or trackers that this PR is trying to resolve? Or is this something you noticed without hitting any problems yet.

**Comment by ljflores** [comment]
One of the tests (ubuntu), we're still hitting this in the teuthology log:
```
2022-08-16T18:33:06.123 INFO:tasks.workunit.client.0.smithi153.stderr:+ ./hello_world_cpp -c /etc/ceph/ceph.conf
2022-08-16T18:33:06.136 INFO:tasks.workunit.client.0.smithi153.stdout:we just set up a rados cluster object
2022-08-16T18:33:06.138 INFO:tasks.workunit.client.0.smithi153.stdout:we just parsed our config options
2022-08-16T18:33:06.146 INFO:tasks.workunit.client.0.smithi153.stderr:free(): invalid pointer
2022-08-16T18:33:06.349 INFO:tasks.workunit.client.0.smithi153.stderr:/home/ubuntu/cephtest/clone.client.0/qa/workunits/rados/test_librados_build.sh: line 65: 16604 Aborted                 (core dumped) ./$b -c /etc/ceph/ceph.conf
2022-08-16T18:33:06.350 INFO:tasks.workunit.client.0.smithi153.stderr:+ cleanup
2022-08-16T18:33:06.350 INFO:tasks.workunit.client.0.smithi153.stderr:+ for f in $BINARIES$SOURCES
2022-08-16T18:33:06.351 INFO:tasks.workunit.client.0.smithi153.stderr:+ rm -f /home/ubuntu/cephtest/mnt.0/client.0/tmp/hello_world_c
2022-08-16T18:33:06.352 INFO:tasks.workunit.client.0.smithi153.stderr:+ for f in $BINARIES$SOURCES
2022-08-16T18:33:06.353 INFO:tasks.workunit.client.0.smithi153.stderr:+ rm -f /home/ubuntu/cephtest/mnt.0/client.0/tmp/hello_world_cpp
2022-08-16T18:33:06.353 INFO:tasks.workunit.client.0.smithi153.stderr:+ for f in $BINARIES$SOURCES
2022-08-16T18:33:06.354 INFO:tasks.workunit.client.0.smithi153.stderr:+ rm -f /home/ubuntu/cephtest/mnt.0/client.0/tmp/hello_radosstriper_cpp
2022-08-16T18:33:06.354 INFO:tasks.workunit.client.0.smithi153.stderr:+ for f in $BINARIES$SOURCES
2022-08-16T18:33:06.354 INFO:tasks.workunit.client.0.smithi153.stderr:+ rm -f /home/ubuntu/cephtest/mnt.0/client.0/tmp/hello_radosstriper.cc
2022-08-16T18:33:06.357 DEBUG:teuthology.orchestra.run:got remote process result: 134
2022-08-16T18:33:06.358 INFO:tasks.workunit.client.0.smithi153.stderr:+ for f in $BINARIES$SOURCES
2022-08-16T18:33:06.358 INFO:tasks.workunit.client.0.smithi153.stderr:+ rm -f /home/ubuntu/cephtest/mnt.0/client.0/tmp/hello_world_c.c
2022-08-16T18:33:06.358 INFO:tasks.workunit.client.0.smithi153.stderr:+ for f in $BINARIES$SOURCES
2022-08-16T18:33:06.358 INFO:tasks.workunit.client.0.smithi153.stderr:+ rm -f /home/ubuntu/cephtest/mnt.0/client.0/tmp/hello_world.cc
2022-08-16T18:33:06.359 INFO:tasks.workunit.client.0.smithi153.stderr:+ for f in $BINARIES$SOURCES
2022-08-16T18:33:06.359 INFO:tasks.workunit.client.0.smithi153.stderr:+ rm -f /home/ubuntu/cephtest/mnt.0/client.0/tmp/Makefile
2022-08-16T18:33:06.359 INFO:tasks.workunit:Stopping ['rados/test_librados_build.sh'] on client.0...
```

gdb shows:
```
# gdb hello_world_cpp /teuthology/lflores-2022-08-16_18:14:56-rados:singleton-nomsgr-wip-yuri4-testing-2022-08-15-0951-distro-default-smithi/6975743/remote/smithi153/coredump/1660674786.16604.core
GNU gdb (Ubuntu 9.2-0ubuntu1~20.04.1) 9.2
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from hello_world_cpp...

warning: exec file is newer than core file.
[New LWP 16609]
[New LWP 16604]
[New LWP 16605]
[New LWP 16606]
[New LWP 16607]
[New LWP 16608]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `./hello_world_cpp -c /etc/ceph/ceph.conf'.
Program terminated with signal SIGABRT, Aborted.
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
[Current thread is 1 (Thread 0x7f67251d3700 (LWP 16609))]
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007f672a072859 in __GI_abort () at abort.c:79
#2  0x00007f672a0dd26e in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7f672a207298 "%s\n") at ../sysdeps/posix/libc_fatal.c:155
#3  0x00007f672a0e52fc in malloc_printerr (str=str@entry=0x7f672a2054c1 "free(): invalid pointer") at malloc.c:5347
#4  0x00007f672a0e6b2c in _int_free (av=<optimized out>, p=<optimized out>, have_lock=0) at malloc.c:4173
#5  0x00007f672a3198ca in std::locale::_Impl::~_Impl() () from /lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00007f672a319b17 in std::locale::~locale() () from /lib/x86_64-linux-gnu/libstdc++.so.6
#7  0x00007f672a4be848 in StackStringStream<4096ul>::~StackStringStream() () from /lib/libradosstriper.so.1
#8  0x00007f672967d2b9 in CachedStackStringStream::Cache::~Cache() () from /usr/lib/ceph/libceph-common.so.2
#9  0x00007f672a0972bf in __GI___call_tls_dtors () at cxa_thread_atexit_impl.c:155
#10 0x00007f67292d9617 in start_thread (arg=<optimized out>) at pthread_create.c:485
#11 0x00007f672a16f133 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

Somehow, there is a pointer getting misused. This could have to do with the recent c++20 changes.

**Comment by ljflores** [comment]
jenkins retest this please

**Comment by ljflores** [comment]
> One of the tests (ubuntu), we're still hitting this in the teuthology log:
> 
> ```
> 2022-08-16T18:33:06.123 INFO:tasks.workunit.client.0.smithi153.stderr:+ ./hello_world_cpp -c /etc/ceph/ceph.conf
> 2022-08-16T18:33:06.136 INFO:tasks.workunit.client.0.smithi153.stdout:we just set up a rados cluster object
> 2022-08-16T18:33:06.138 INFO:tasks.workunit.client.0.smithi153.stdout:we just parsed our config options
> 2022-08-16T18:33:06.146 INFO:tasks.workunit.client.0.smithi153.stderr:free(): invalid pointer
> 2022-08-16T18:33:06.349 INFO:tasks.workunit.client.0.smithi153.stderr:/home/ubuntu/cephtest/clone.client.0/qa/workunits/rados/test_librados_build.sh: line 65: 16604 Aborted                 (core dumped) ./$b -c /etc/ceph/ceph.conf
> 2022-08-16T18:33:06.350 INFO:tasks.workunit.client.0.smithi153.stderr:+ cleanup
> 2022-08-16T18:33:06.350 INFO:tasks.workunit.client.0.smithi153.stderr:+ for f in $BINARIES$SOURCES
> 2022-08-16T18:33:06.351 INFO:tasks.workunit.client.0.smithi153.stderr:+ rm -f /home/ubuntu/cephtest/mnt.0/client.0/tmp/hello_world_c
> 2022-08-16T18:33:06.352 INFO:tasks.workunit.client.0.smithi153.stderr:+ for f in $BINARIES$SOURCES
> 2022-08-16T18:33:06.353 INFO:tasks.workunit.client.0.smithi153.stderr:+ rm -f /home/ubuntu/cephtest/mnt.0/client.0/tmp/hello_world_cpp
> 2022-08-16T18:33:06.353 INFO:tasks.workunit.client.0.smithi153.stderr:+ for f in $BINARIES$SOURCES
> 2022-08-16T18:33:06.354 INFO:tasks.workunit.client.0.smithi153.stderr:+ rm -f /home/ubuntu/cephtest/mnt.0/client.0/tmp/hello_radosstriper_cpp
> 2022-08-16T18:33:06.354 INFO:tasks.workunit.client.0.smithi153.stderr:+ for f in $BINARIES$SOURCES
> 2022-08-16T18:33:06.354 INFO:tasks.workunit.client.0.smithi153.stderr:+ rm -f /home/ubuntu/cephtest/mnt.0/client.0/tmp/hello_radosstriper.cc
> 2022-08-16T18:33:06.357 DEBUG:teuthology.orchestra.run:got remote process result: 134
> 2022-08-16T18:33:06.358 INFO:tasks.workunit.client.0.smithi153.stderr:+ for f in $BINARIES$SOURCES
> 2022-08-16T18:33:06.358 INFO:tasks.workunit.client.0.smithi153.stderr:+ rm -f /home/ubuntu/cephtest/mnt.0/client.0/tmp/hello_world_c.c
> 2022-08-16T18:33:06.358 INFO:tasks.workunit.client.0.smithi153.stderr:+ for f in $BINARIES$SOURCES
> 2022-08-16T18:33:06.358 INFO:tasks.workunit.client.0.smithi153.stderr:+ rm -f /home/ubuntu/cephtest/mnt.0/client.0/tmp/hello_world.cc
> 2022-08-16T18:33:06.359 INFO:tasks.workunit.client.0.smithi153.stderr:+ for f in $BINARIES$SOURCES
> 2022-08-16T18:33:06.359 INFO:tasks.workunit.client.0.smithi153.stderr:+ rm -f /home/ubuntu/cephtest/mnt.0/client.0/tmp/Makefile
> 2022-08-16T18:33:06.359 INFO:tasks.workunit:Stopping ['rados/test_librados_build.sh'] on client.0...
> ```
> 
> gdb shows:
> 
> ```
> # gdb hello_world_cpp /teuthology/lflores-2022-08-16_18:14:56-rados:singleton-nomsgr-wip-yuri4-testing-2022-08-15-0951-distro-default-smithi/6975743/remote/smithi153/coredump/1660674786.16604.core
> GNU gdb (Ubuntu 9.2-0ubuntu1~20.04.1) 9.2
> Copyright (C) 2020 Free Software Foundation, Inc.
> License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
> This is free software: you are free to change and redistribute it.
> There is NO WARRANTY, to the extent permitted by law.
> Type "show copying" and "show warranty" for details.
> This GDB was configured as "x86_64-linux-gnu".
> Type "show configuration" for configuration details.
> For bug reporting instructions, please see:
> <http://www.gnu.org/software/gdb/bugs/>.
> Find the GDB manual and other documentation resources online at:
>     <http://www.gnu.org/software/gdb/documentation/>.
> 
> For help, type "help".
> Type "apropos word" to search for commands related to "word"...
> Reading symbols from hello_world_cpp...
> 
> warning: exec file is newer than core file.
> [New LWP 16609]
> [New LWP 16604]
> [New LWP 16605]
> [New LWP 16606]
> [New LWP 16607]
> [New LWP 16608]
> [Thread debugging using libthread_db enabled]
> Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
> Core was generated by `./hello_world_cpp -c /etc/ceph/ceph.conf'.
> Program terminated with signal SIGABRT, Aborted.
> #0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
> 50	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
> [Current thread is 1 (Thread 0x7f67251d3700 (LWP 16609))]
> (gdb) bt
> #0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
> #1  0x00007f672a072859 in __GI_abort () at abort.c:79
> #2  0x00007f672a0dd26e in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7f672a207298 "%s\n") at ../sysdeps/posix/libc_fatal.c:155
> #3  0x00007f672a0e52fc in malloc_printerr (str=str@entry=0x7f672a2054c1 "free(): invalid pointer") at malloc.c:5347
> #4  0x00007f672a0e6b2c in _int_free (av=<optimized out>, p=<optimized out>, have_lock=0) at malloc.c:4173
> #5  0x00007f672a3198ca in std::locale::_Impl::~_Impl() () from /lib/x86_64-linux-gnu/libstdc++.so.6
> #6  0x00007f672a319b17 in std::locale::~locale() () from /lib/x86_64-linux-gnu/libstdc++.so.6
> #7  0x00007f672a4be848 in StackStringStream<4096ul>::~StackStringStream() () from /lib/libradosstriper.so.1
> #8  0x00007f672967d2b9 in CachedStackStringStream::Cache::~Cache() () from /usr/lib/ceph/libceph-common.so.2
> #9  0x00007f672a0972bf in __GI___call_tls_dtors () at cxa_thread_atexit_impl.c:155
> #10 0x00007f67292d9617 in start_thread (arg=<optimized out>) at pthread_create.c:485
> #11 0x00007f672a16f133 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
> ```
> 
> Somehow, there is a pointer getting misused. This could have to do with the recent c++20 changes.

gdb also reveals:
```
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007fb242eba859 in __GI_abort () at abort.c:79
#2  0x00007fb242f2526e in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7fb24304f298 "%s\n") at ../sysdeps/posix/libc_fatal.c:155
#3  0x00007fb242f2d2fc in malloc_printerr (str=str@entry=0x7fb24304d4c1 "free(): invalid pointer") at malloc.c:5347
#4  0x00007fb242f2eb2c in _int_free (av=<optimized out>, p=<optimized out>, have_lock=0) at malloc.c:4173
#5  0x00007fb2431618ca in char* std::string::_S_construct<char const*>(char const*, char const*, std::allocator<char> const&, std::forward_iterator_tag) () from /lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00007fb23e01a908 in ?? ()
#7  0x00007fb242e3d610 in ?? () from /usr/lib/ceph/libceph-common.so.2
#8  0x00007fb243161b17 in std::string::replace(unsigned long, unsigned long, char const*, unsigned long) () from /lib/x86_64-linux-gnu/libstdc++.so.6
#9  0x0000000000000000 in ?? ()
```

@rzarzynski any ideas on how we can resolve this?

**Comment by Matan-B** [comment]
The error seem to arise from `hello_world_c.c` (the log may show otherwise since it is running in the background)
Might get triggered here: 
https://github.com/ceph/ceph/blob/main/examples/librados/hello_world_c.c#L180

**Comment by Matan-B** [comment]
Tested a hypothesis I had, run each test separately (`hello_world_c` and `hello_world_cpp`) and no failure occurred. 
hello_world_cpp: http://pulpito.front.sepia.ceph.com/matan-2022-08-18_09:22:44-rados:singleton-nomsgr-main-distro-default-smithi/
hello_world_c: http://pulpito.front.sepia.ceph.com/matan-2022-08-18_09:25:10-rados:singleton-nomsgr-main-distro-default-smithi/

**Comment by ljflores** [comment]
Ahh, interesting observation @Matan-B!

**Comment by ljflores** [comment]
It certainly is weird; the "invalid pointer" error only happens on ubuntu.

Rhel and CentOS (pass):
- http://pulpito.front.sepia.ceph.com/lflores-2022-08-18_16:52:05-rados:singleton-nomsgr-main-distro-default-smithi/

Ubuntu 20.04 (fail):
- http://pulpito.front.sepia.ceph.com/lflores-2022-08-18_17:06:17-rados:singleton-nomsgr-main-distro-default-smithi/

**Comment by ronen-fr** [comment]
@ljflores, @Matan-B : take a look at https://github.com/ceph/ceph/pull/46891#issuecomment-1214316401

It was always a dist-specific issue...

**Comment by ljflores** [comment]
Same test passes on quincy, when run on ubuntu:
- http://pulpito.front.sepia.ceph.com/lflores-2022-08-18_18:42:02-rados:singleton-nomsgr-quincy-distro-default-smithi/

The difference I'm seeing is that on main, we're installing `libradospp-dev`:
```
2022-08-18T17:18:08.601 INFO:tasks.workunit.client.0.smithi078.stderr:++ source /etc/os-release
2022-08-18T17:18:08.602 INFO:tasks.workunit.client.0.smithi078.stderr:+++ NAME=Ubuntu
2022-08-18T17:18:08.616 INFO:tasks.workunit.client.0.smithi078.stderr:+++ VERSION='20.04.4 LTS (Focal Fossa)'
2022-08-18T17:18:08.617 INFO:tasks.workunit.client.0.smithi078.stderr:+++ ID=ubuntu
2022-08-18T17:18:08.617 INFO:tasks.workunit.client.0.smithi078.stderr:+++ ID_LIKE=debian
2022-08-18T17:18:08.618 INFO:tasks.workunit.client.0.smithi078.stderr:+++ PRETTY_NAME='Ubuntu 20.04.4 LTS'
2022-08-18T17:18:08.618 INFO:tasks.workunit.client.0.smithi078.stderr:+++ VERSION_ID=20.04
2022-08-18T17:18:08.618 INFO:tasks.workunit.client.0.smithi078.stderr:+++ HOME_URL=https://www.ubuntu.com/
2022-08-18T17:18:08.618 INFO:tasks.workunit.client.0.smithi078.stderr:+++ SUPPORT_URL=https://help.ubuntu.com/
2022-08-18T17:18:08.619 INFO:tasks.workunit.client.0.smithi078.stderr:+++ BUG_REPORT_URL=https://bugs.launchpad.net/ubuntu/
2022-08-18T17:18:08.619 INFO:tasks.workunit.client.0.smithi078.stderr:+++ PRIVACY_POLICY_URL=https://www.ubuntu.com/legal/terms-and-policies/privacy-policy
2022-08-18T17:18:08.619 INFO:tasks.workunit.client.0.smithi078.stderr:+++ VERSION_CODENAME=focal
2022-08-18T17:18:08.619 INFO:tasks.workunit.client.0.smithi078.stderr:+++ UBUNTU_CODENAME=focal
2022-08-18T17:18:08.619 INFO:tasks.workunit.client.0.smithi078.stderr:++ echo ubuntu
2022-08-18T17:18:08.620 INFO:tasks.workunit.client.0.smithi078.stderr:+ sudo env DEBIAN_FRONTEND=noninteractive apt-get install -y libradospp-dev
2022-08-18T17:18:08.661 INFO:tasks.workunit.client.0.smithi078.stdout:Reading package lists...
2022-08-18T17:18:08.821 INFO:tasks.workunit.client.0.smithi078.stdout:Building dependency tree...
2022-08-18T17:18:08.822 INFO:tasks.workunit.client.0.smithi078.stdout:Reading state information...
2022-08-18T17:18:08.960 INFO:tasks.workunit.client.0.smithi078.stdout:libradospp-dev is already the newest version (17.0.0-14348-g370d960f-1focal).
```

While on quincy, we're installing `librados-dev`:
```
2022-08-18T18:54:15.785 INFO:tasks.workunit.client.0.smithi182.stderr:++ source /etc/os-release
2022-08-18T18:54:15.785 INFO:tasks.workunit.client.0.smithi182.stderr:+++ NAME=Ubuntu
2022-08-18T18:54:15.786 INFO:tasks.workunit.client.0.smithi182.stderr:+++ VERSION='20.04.4 LTS (Focal Fossa)'
2022-08-18T18:54:15.786 INFO:tasks.workunit.client.0.smithi182.stderr:+++ ID=ubuntu
2022-08-18T18:54:15.787 INFO:tasks.workunit.client.0.smithi182.stderr:+++ ID_LIKE=debian
2022-08-18T18:54:15.787 INFO:tasks.workunit.client.0.smithi182.stderr:+++ PRETTY_NAME='Ubuntu 20.04.4 LTS'
2022-08-18T18:54:15.788 INFO:tasks.workunit.client.0.smithi182.stderr:+++ VERSION_ID=20.04
2022-08-18T18:54:15.788 INFO:tasks.workunit.client.0.smithi182.stderr:+++ HOME_URL=https://www.ubuntu.com/
2022-08-18T18:54:15.789 INFO:tasks.workunit.client.0.smithi182.stderr:+++ SUPPORT_URL=https://help.ubuntu.com/
2022-08-18T18:54:15.789 INFO:tasks.workunit.client.0.smithi182.stderr:+++ BUG_REPORT_URL=https://bugs.launchpad.net/ubuntu/
2022-08-18T18:54:15.790 INFO:tasks.workunit.client.0.smithi182.stderr:+++ PRIVACY_POLICY_URL=https://www.ubuntu.com/legal/terms-and-policies/privacy-policy
2022-08-18T18:54:15.790 INFO:tasks.workunit.client.0.smithi182.stderr:+++ VERSION_CODENAME=focal
2022-08-18T18:54:15.791 INFO:tasks.workunit.client.0.smithi182.stderr:+++ UBUNTU_CODENAME=focal
2022-08-18T18:54:15.791 INFO:tasks.workunit.client.0.smithi182.stderr:++ echo ubuntu
2022-08-18T18:54:15.791 INFO:tasks.workunit.client.0.smithi182.stderr:+ sudo env DEBIAN_FRONTEND=noninteractive apt-get install -y librados-dev
2022-08-18T18:54:15.848 INFO:tasks.workunit.client.0.smithi182.stdout:Reading package lists...
2022-08-18T18:54:16.026 INFO:tasks.workunit.client.0.smithi182.stdout:Building dependency tree...
2022-08-18T18:54:16.028 INFO:tasks.workunit.client.0.smithi182.stdout:Reading state information...
2022-08-18T18:54:16.171 INFO:tasks.workunit.client.0.smithi182.stdout:librados-dev is already the newest version (17.2.3-482-g687c45bd-1focal).
```

**Comment by ljflores** [comment]
Wow, I've looked into this for hours today and got nowhere except that I think this is a dependency issue. Here are some things I know for sure:
1. The failure is "free: invalid pointer()" when the `librados/hello_world.cc` binary is run (`./hello_world_cpp -c /etc/ceph/ceph.conf`)
2. This fails only on main, and only on ubuntu (quincy is working fine)
3. Nothing has changed code-wise in `librados/hello_world.cc` between main and quincy

It would help if we could reproduce it locally, but when I tried running the test locally, it did not like parsing my vstart ceph.conf file. If anyone is able to reproduce locally, let me know.

One thing we could do in the meantime is merge this PR to address https://tracker.ceph.com/issues/57122, which will at least fix centos and rhel tests. And then address the "free: invalid pointer()" issue separately.

@Matan-B what do you think?

**Comment by Matan-B** [comment]
> 3. Nothing has changed code-wise in `librados/hello_world.cc` between main and quincy

Related changes can also be found in the librados implementation (e.g `librados_cxx.cc`, `RadosClient.cc`). With similar issues such as e465cfc62ae0f982edb60291c67f4d76a71efd15.

> It would help if we could reproduce it locally, but when I tried running the test locally, it did not like parsing my vstart ceph.conf file. If anyone is able to reproduce locally, let me know.

I tried reproducing locally but no errors for me. (Ping me if you need help with the vstart parsing)

> One thing we could do in the meantime is merge this PR to address https://tracker.ceph.com/issues/57122, which will at least fix centos and rhel tests. And then address the "free: invalid pointer()" issue separately.

Since the `free(): invalid pointer` issue is not related to this this change, I agree that we can address this issue separately.

**Review by ronen-fr — APPROVED** [review]
LGTM. We should follow on that unrelated test failure, though.

**Comment by ronen-fr** [comment]
jenkins retest this please

**Comment by ljflores** [comment]
jenkins test api

**Comment by ljflores** [comment]
jenkins test make check

**Comment by ljflores** [comment]
jenkins test make check arm64

**Comment by Matan-B** [comment]
jenkins test make check arm64

**Comment by Matan-B** [comment]
jenkins test make check

**Comment by ljflores** [comment]
There was an instance of `free() invalid pointer` recorded on a different librados test (see https://tracker.ceph.com/issues/57163#note-2), so we can safely say that is an entirely separate issue. I will move forward with merging this PR so we can focus on fixing that separately.

**Pull request merged**
