### PR TITLE
ceph_volume_client.py: python 3.8 compatibility

### PR DESCRIPTION
**Pull request by dvanders**
Installing 15.2.1 on Ubuntu 20.04 yields this warning:
```
Setting up python3-cephfs (15.2.1-0ubuntu1) ...
/usr/lib/python3/dist-packages/ceph_volume_client.py:358: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  group_id = group_id if group_id is not 'None' else None
/usr/lib/python3/dist-packages/ceph_volume_client.py:381: SyntaxWarning: "is" with a literal. Did you mean "=="?
  readonly = True if access_level is 'r' else False
/usr/lib/python3/dist-packages/ceph_volume_client.py:1102: SyntaxWarning: "is" with a literal. Did you mean "=="?
  unwanted_access_level = 'r' if want_access_level is 'rw' else 'rw'
```
Make the suggested changes.

Signed-off-by: Dan van der Ster <daniel.vanderster@cern.ch>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by dvanders** [comment]
@batrick https://tracker.ceph.com/issues/46414

**Comment by dvanders** [comment]
sorry -- i have no clue how to resolve that change req

**Comment by smithfarm** [comment]
@dvanders The tl;dr is:

1. `git commit --amend`, editor opens
2. insert the `Fixes: ...` line, save-and-exit from editor
3. `git push --force` to update the PR

**Comment by dvanders** [comment]
This whole PR has been obsoleted by 3ce9a89a5a1a2d7fa3d57c597b781a6aece7cbb5
Closing.

**Comment by dvanders** [comment]
@smithfarm I updated https://tracker.ceph.com/issues/46414 linking to the PR which was already merged to master.
I suppose the backport is still required.

**Comment by batrick** [comment]
@dvanders I set it up to backport. Thanks!

**Comment by smithfarm** [comment]
> @smithfarm I updated https://tracker.ceph.com/issues/46414 linking to the PR which was already merged to master.
> I suppose the backport is still required.

@dvanders I'm confused.  https://tracker.ceph.com/issues/46414 does not link to this PR. It links to https://github.com/ceph/ceph/pull/34974 - is that related somehow?

**Pull request closed without merging**
