### PR TITLE
rados: prevent ShardedOpWQ suicide_grace drop when waiting for work.

### PR DESCRIPTION
**Pull request by hillpd**
The Sharded OpWQ will opportunistically wait for more work when
processing an empty queue. While waiting, the default work queue
heartbeat timeout and suicide_grace values are modified. The
`threadpool_default_timeout` grace is applied and suicide_grace is
disabled. If this op hangs, the heartbeat watchdog will not trigger an
OSD suicide recovery.

The default work queue values for grace and suicide_grace are re-applied
after finding work. This keeps the heartbeat timeouts consistent with
the values applied on _process() entry.

Fixes: https://tracker.ceph.com/issues/45076
Signed-off-by: Dan Hill <daniel.hill@canonical.com>

## Checklist
- [x] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by hillpd** [comment]
The missing suicide recovery was observed on Luminous 12.2.11. The environment was consistently hitting a known authentication race condition (issue#37778) due to repeated OSD service restarts on a node exhibiting MCEs from a faulty DIMM. 

The auth race condition would stall pg operations. In some cases, the hung ops would persist for hours without suicide recovery, but report hb timeouts.

Arrived at this fix by code inspection. The suicide_grace value is dropped in all versions since 12.2.11.

I have not identified a reliable reproducer.

**Comment by yuriw** [comment]
[wip-yuri7-testing-2020-04-22-1640-master](https://trello.com/c/9Z6XfbyH/878-wip-yuri7-testing-2020-04-22-1640-master)

**Comment by yuriw** [comment]
[wip-yuri-testing-2020-04-24-1941-master](https://trello.com/c/GFVGvIbx/883-wip-yuri-testing-2020-04-24-1941-master)

**Comment by badone** [comment]
Test run failed, see https://trello.com/c/GFVGvIbx/883-wip-yuri-testing-2020-04-24-1941-master#comment-5eaa251a65d46e61fddf3a3f

**Comment by hillpd** [comment]
@badone I'm unable to view that trello board. My trello username matches github, if you want to grant access.

**Comment by tchaikov** [comment]
http://pulpito.ceph.com/yuriw-2020-04-25_15:45:45-rados-wip-yuri-testing-2020-04-24-1941-master-distro-basic-smithi/

**Comment by badone** [comment]
@hillpd never mind, we've established the failure is not related.

**Pull request merged**
