### PR TITLE
os/bluestore: proper handling for csum enable/disable settings

### PR DESCRIPTION
**Pull request by ifed01**
There is no need to read 'csum aligned' chunks when reading with csum verification disabled. Hence we can tune read performance.

Signed-off-by: Igor Fedotov <ifedotov@mirantis.com>

### CODE REVIEW

**Comment by liewegas** [comment]
lgtm

**Comment by liewegas** [comment]
Hmm, I wonder if it makes sense to have a different option for this (verify csum on read)?  That way you can separately disable all the csum checks on read, which might be useful/interesting anyway.

**Comment by markhpc** [comment]
@liewegas Would you want the hypothetical option as a separate PR? (IE are we good to go on this one?)

**Comment by ifed01** [comment]
@liewegas I think that's a nice option with a very little use..

**Pull request merged**
