### PR TITLE
pacific: packaging: require ceph-common for immutable object cache daemon

### PR DESCRIPTION
**Pull request by idryomov**
backport tracker: https://tracker.ceph.com/issues/50231

---

backport of https://github.com/ceph/ceph/pull/40641
parent tracker: https://tracker.ceph.com/issues/50207

### CODE REVIEW

**Comment by idryomov** [comment]
jenkins please make check

**Comment by idryomov** [comment]
jenkins test make check

**Comment by idryomov** [comment]
jenkins test make check

**Review by gregsfortytwo — APPROVED** [review]
LGTM

**Comment by idryomov** [comment]
https://pulpito.ceph.com/dis-2021-04-13_08:11:34-rbd-wip-require-ceph-common-for-ioc-pacific-distro-basic-smithi/

**Pull request merged**
