### PR TITLE
pacific: mgr/cephadm: Add snmp-gateway service support

### PR DESCRIPTION
**Pull request by sebastian-philipp**
Backport of #43901, #44341

### CODE REVIEW

**Comment by pcuzner** [comment]
As I mentioned during the original PR, the 'cleanup' changes have been a backward step for the CLI UX.

The original PR provided this with a -h;
```
orch apply snmp-gateway <snmp_version:V2c|V3> <destination> [<port:int>] [<engine_id>] [<auth_protocol:MD5|SHA>]      Add a Prometheus to SNMP gateway service (cephadm only)
 [<privacy_protocol:DES|AES>] [<placement>] [--unmanaged] [--dry-run] [--format {plain|json|json-pretty|yaml}] [--no- 
 overwrite] 
```
And now you see this
```
orch apply snmp-gateway V2c|V3 <destination> [<port:int>] [<engine_id>] [MD5|SHA] [DES|AES] [<placement>] [--         Add a Prometheus to SNMP gateway service (cephadm only)
 unmanaged] [--dry-run] [--format {plain|json|json-pretty|yaml}] [--no-overwrite]
```
This makes the CLI harder to use, since you no longer see the parameter names that can be used

**Comment by sebastian-philipp** [comment]
> The original PR provided this with a -h;
> 
> ```
> orch apply snmp-gateway <snmp_version:V2c|V3> <destination> [<port:int>] [<engine_id>] [<auth_protocol:MD5|SHA>]      Add a Prometheus to SNMP gateway service (cephadm only)
>  [<privacy_protocol:DES|AES>] [<placement>] [--unmanaged] [--dry-run] [--format {plain|json|json-pretty|yaml}] [--no- 
>  overwrite] 
> ```
> 
> The parameters accepted are shown in the help.
> 
> And now you see this
> 
> ```
> orch apply snmp-gateway V2c|V3 <destination> [<port:int>] [<engine_id>] [MD5|SHA] [DES|AES] [<placement>] [--         Add a Prometheus to SNMP gateway service (cephadm only)
>  unmanaged] [--dry-run] [--format {plain|json|json-pretty|yaml}] [--no-overwrite]
> ```
> 
> snmp_version, auth_protocol and privacy_protocol are missing!
> 
> This makes the CLI harder to use, since you no longer see the parameter names that can be used.
> 
> Also, if you set them positionally I see this;
> 
> ```
> [ceph: root@pacific-1 ~]# ceph orch apply snmp-gateway V3 --destination 192.168.122.1:162 --engine_id 8000C5A32011223344 SHA AES -i ./snmp_auth_priv.yml                                                                                   
> Error EINVAL: engine_id must be a string containing 10-64 hex characters. Its length must be divisible by 2
> ```
> 
> ...but adding in --privacy_protocol AES still works
> 
> What's the cause of this 'regression'?

Maybe this is due how the help is generated by pacific instead of master????

**Comment by pcuzner** [comment]
@sebastian-philipp Hmmm - so it's a 'feature' of Pacific :) I don't have an approve 'button', but if this is the case it lgtm!

**Review by adk3798 — APPROVED** [review]

**Comment by sebastian-philipp** [comment]
jenkins test make check

**Comment by sebastian-philipp** [comment]
https://pulpito.ceph.com/swagner-2022-01-17_13:39:37-rados:cephadm-wip-swagner2-testing-2022-01-17-1019-pacific-distro-default-smithi/

* cgroups
* dashboard error
* infra issues

**Comment by sebastian-philipp** [comment]
build failed with
```
  WARNING: Built wheel for xmlsec is invalid: xmlsec has an invalid wheel, could not read 'xmlsec-1.3.12.dist-info/WHEEL' file: BadZipFile('Truncated file header')
Failed to build xmlsec
ERROR: Could not build wheels for xmlsec, which is required to install pyproject.toml-based projects
  Building wheel for xmlsec (pyproject.toml): finished with status 'done'
  Created wheel for xmlsec: filename=xmlsec-1.3.12-cp38-cp38-linux_x86_64.whl size=199791 sha256=faef8db469c4fc018e1b1c600059bb929775b1292e6d0ae522dffece9e0110fb
  Stored in directory: /home/jenkins-build/build/workspace/ceph-pull-requests/install-deps-cache/pip/wheels/2c/99/a3/98bcb24586c778eb35e23e30af30fbf1c34a0a9ed85e18576a
Successfully built xmlsec
Installing collected packages: more-itertools, pytz, pycparser, jaraco.functools, wrapt, tomli, tempora, pyflakes, pycodestyle, pluggy, mccabe, lxml, lazy-object-proxy, iniconfig, coverage, cffi, attrs, xmlsec, wcwidth, urllib3, repoze.lru, pyyaml, pytest, portend, isort, isodate, idna, flake8, docutils, defusedxml, cryptography, cheroot, chardet, certifi, astroid, rstcheck, Routes, requests, python3-saml, pytest-instafail, pytest-cov, pyopenssl, pylint, PyJWT, pyfakefs, prettytable, flake8-colors, CherryPy, ceph, bcrypt, autopep8
make[3]: *** [src/pybind/mgr/dashboard/CMakeFiles/mgr-dashboard-py3-venv.dir/build.make:61: mgr-dashboard-py3-virtualenv/bin/activate] Error 1
```

**Comment by sebastian-philipp** [comment]
jenkins test make check

**Comment by sebastian-philipp** [comment]
jenkins test make check

**Comment by sebastian-philipp** [comment]
```
cephadm/module.py:481:1: W191 indentation contains tabs
cephadm/module.py:481:1: E101 indentation contains mixed spaces and tabs
cephadm/module.py:481:4: E131 continuation line unaligned for hanging indent
cephadm/module.py:2670:1: W191 indentation contains tabs
cephadm/module.py:2670:1: E101 indentation contains mixed spaces and tabs
cephadm/module.py:2670:1: W293 blank line contains whitespace
orchestrator/_interface.py:652:1: W191 indentation contains tabs
orchestrator/_interface.py:652:1: E101 indentation contains mixed spaces and tabs
orchestrator/_interface.py:652:1: W293 blank line contains whitespace
```

**Comment by sebastian-philipp** [comment]
changelog:

* rebased (fixed conflict in python-common/ceph/tests/test_service_spec.py)
* fixed flake8 errors

**Pull request merged**
