### PR TITLE
squid: mds: check relevant caps for fs include root_squash

### PR DESCRIPTION
**Pull request by batrick**
backport tracker: https://tracker.ceph.com/issues/65853

---

backport of https://github.com/ceph/ceph/pull/57192
parent tracker: https://tracker.ceph.com/issues/65733

this backport was staged using ceph-backport.sh version 16.0.0.6848
find the latest version at https://github.com/ceph/ceph/blob/main/src/script/ceph-backport.sh

### CODE REVIEW

**Review by anthonyeleven — APPROVED** [review]

**Comment by batrick** [comment]
jenkins test make check

**Comment by batrick** [comment]
This PR is under test in [https://tracker.ceph.com/issues/66101](https://tracker.ceph.com/issues/66101).

**Comment by batrick** [comment]
jenkins test api

**Review by batrick — COMMENTED** [review]
https://tracker.ceph.com/issues/66101#note-1

**Comment by batrick** [comment]
Tests in this PR ran successfully in /teuthology/pdonnell-2024-05-20_15:44:59-fs-wip-pdonnell-testing-20240517.203521-squid-debug-distro-default-smithi/7715650/teuthology.log

ultimate failure was for other reasons.

**Comment by batrick** [comment]
Ready to merge when jenkins tests pass.

**Pull request merged**
