### PR TITLE
ceph-volume: add explicit test variant to functional tests

### PR DESCRIPTION
**Pull request by jan--f**
Also run those tests in py2 explicitly.
This will fix failing (or rather missing) nightly tests.

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by dsavineau** [comment]
@jan--f since luminous is EOL, does it still make sense to have nightly tests for this release ?

**Comment by jan--f** [comment]
> @jan--f since luminous is EOL, does it still make sense to have nightly tests for this release ?

I'd be happy to drop them! For some reason I thought RH still has a release based on luminous. If that's not the case I'll close this and drop the nightly runs.

**Comment by dsavineau** [comment]
> I'd be happy to drop them! For some reason I thought RH still has a release based on luminous. If that's not the case I'll close this and drop the nightly runs.

You're right, there's still RHCS 3 which is based on luminous but I don't think it worths having nightly tests because we shouldn't have any new content on the luminous branch upstream.

@andrewschoen what's your thoughts on this ?

**Comment by guits** [comment]
> > I'd be happy to drop them! For some reason I thought RH still has a release based on luminous. If that's not the case I'll close this and drop the nightly runs.
> 
> You're right, there's still RHCS 3 which is based on luminous but I don't think it worths having nightly tests because we shouldn't have any new content on the luminous branch upstream.
> 
> @andrewschoen what's your thoughts on this ?

+1

**Comment by jan--f** [comment]
Sounds good, thanks guys!

**Pull request closed without merging**
