### PR TITLE
URL for Ceph Object Store is pointing to radosgw instead of rados

### PR DESCRIPTION
**Pull request by nigwil**
two character change to fix link.

### CODE REVIEW

**Comment by yehudasa** [comment]
@nigwil I'm pretty sure that's on purpose

**Comment by nigwil** [comment]
I don't agree, the landing page lists Ceph Object Store, Ceph Block Device and Ceph Filesystem, the links at the bottom should go to those major subsystems, so "See Ceph Object Store" should go to RADOS. Within the RADOS subsystem it would then be ok to link to RADOSgw as a client-option.

**Comment by yehudasa** [comment]
This is not the intention of this page. While rados is an object store, so is the rados gateway. Here on the page, under Ceph Object Store we have the following items:
```
RESTful Interface
S3- and Swift-compliant APIs
S3-style subdomains
Unified S3/Swift namespace
User management
Usage tracking
Striped objects
Cloud solution integration
Multi-site deployment
Multi-site replication
```
All of these are rgw features, not rados features. Also, radosgw is not a subset of rados, it's built on top of rados, the same as rbd and cephfs are built on top of rados.

**Comment by nigwil** [comment]
I concede that the list you highlight is for RADOSgw, but the landing (top-level) page for the documentation is to guide users to the major subsystems. RADOSgw is a unidirectional dependency of RADOS (you can have RADOS without RADOSgw, but not the other way around). If RADOSgw needs to be obvious on the landing-page (rather than placed under RADOS) then it would be simpler to have a new item list such as this:

CEPH STORAGE CLUSTER    CEPH OBJECT STORE GATEWAY  CEPH BLOCK DEVICE  CEPH FILESYSTEM
...list of features...

It remains counter-intuitive to me that RADOS is simply linked in the TOC at left and not obviously linked in the body.

**Pull request closed without merging**
