### PR TITLE
ceph.spec.in: ceph-common subpackage def needs tweaking for SUSE/openSUSE

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/12308

### CODE REVIEW

**Comment by theanalyst** [comment]
@ktdreyer / @smithfarm this has passed the first run of integration tests for hammer backports tracked at http://tracker.ceph.com/issues/11990 Do you think it is ready to merge

**Comment by smithfarm** [comment]
Let Ken make the final decision on this one. IMO it can be merged provided we also backport #4970.

**Comment by dachary** [comment]
@ktdreyer ping ?

**Comment by ktdreyer** [comment]
Apologies for the delay. I see now argparse will be covered separately in http://tracker.ceph.com/issues/12269 . So this PR is good to go.

**Pull request merged**
