### PR TITLE
pacific: tool/bluestore-tool: introduce repair_omap_upgrade command

### PR DESCRIPTION
**Pull request by ifed01**
This allows to recover OMAPs broken due to
https://tracker.ceph.com/issues/53062

This command applied to OSD would fix OMAP keys and hopefully brings OSD
and other daemons back to working state.

I'm still uncertain whether we need this in the mainstream code base but it looks like some users might need that urgently to recover their clusters. Hence sharing this patch to permit custom build creation if needed. For the same reason provided as a Pacific patch only.
Definitely this should be used with with an extreme care in custom builds as  it bypasses all the regular QA procedures...

Signed-off-by: Igor Fedotov <igor.fedotov@croit.io>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by neha-ojha** [comment]
@ifed01 have any of the affected clusters tried this out?

**Comment by ifed01** [comment]
> @ifed01 have any of the affected clusters tried this out?

not yet, just shared this PR/patch to one of them..

**Comment by imobilis** [comment]
Hello, just to report that I had a cluster impacted by the omap upgrade issue, and after running the new experimental command I've been able to bring up the services and access the data.

I applied the patch over the 16.2.6 tag codebase, if that helps.

Thanks folks!

**Comment by aclamk** [comment]
@ifed01 

My replication procedure is:
- deploy cluster with 'bluestore_debug_legacy_omap = true'
- set some omaps
- restart OSD with bluestore_fsck_quick_fix_on_mount = true
Do you have anything better ?


I do not like fixing by "findfirst()".
I made a table of possible conversions below.
Shouldn't we exactly require specific bytes to match and apply exact cuts?
It is still not 100% certain, but would be better.


For example byte[0x14]=='.' and byte[0x1d]=='-' and bytes[0xc..0x13]==bytes[0x15..0x1c] means that we have case 3) => delete.

Table of corrupted conversion:
```
   00000000000000001111111111111111               000000000000000011111111111111112222222222
   0123456789abcdef0123456789abcdef	          0123456789abcdef0123456789abcdef0123456789
   
   HEAD new, is ok
1) nnnnnnnn-hhhhh                   BULK->PG      ppppppppkkkknnnnnnnn-hhhhh
2) ppppppppnnnnnnnn-hhhhh           POOL->PG      ppppppppkkkknnnnnnnn-hhhhh
   
   HEAD converted incorrectly, delete:
3) nnnnnnnn-hhhhh                   BULK->PG      ppppppppkkkknnnnnnnn.nnnnnnnn-hhhhh
4) ppppppppnnnnnnnn-hhhhh           POOL->PG      ppppppppkkkknnnnnnnn.ppppppppnnnnnnnn-hhhhh
   
   KEYS converted incorrectly, must convert:
5) nnnnnnnn.kkkkk                   BULK->PG      ppppppppkkkknnnnnnnn.nnnnnnnn.kkkkk
6) ppppppppnnnnnnnn.kkkkk           POOL->PG      ppppppppkkkknnnnnnnn.ppppppppnnnnnnnn.kkkkk

```

**Comment by ifed01** [comment]
> @ifed01
> 
> My replication procedure is:
> 
> * deploy cluster with 'bluestore_debug_legacy_omap = true'
> * set some omaps
> * restart OSD with bluestore_fsck_quick_fix_on_mount = true
>   Do you have anything better ?
> 
not really, I was doing pretty the same.
Additionally I applied some manual (unpublished) modifications for this debug mode to create store in PER_POOL format and tried that as well.

**Comment by ifed01** [comment]
>    HEAD converted incorrectly, delete:
> 3) nnnnnnnn-hhhhh                   BULK->PG      ppppppppkkkknnnnnnnn.nnnnnnnn-hhhhh
> 4) ppppppppnnnnnnnn-hhhhh           POOL->PG      ppppppppkkkknnnnnnnn.ppppppppnnnnnnnn-hhhhh
>    
And I can't read that example. Here is the real output for DB keys after broken upgrade:
case a) BULK->PG
p       %00%00%00%00%00%00%00%0b%00%00%00%00%00%00%00%00%00%00%00%01-
p       %00%00%00%00%00%00%00%0b%00%00%00%00%00%00%00%00%00%00%00%01.%00%00%00%00%00%00%00%01-
p       %00%00%00%00%00%00%00%0b%00%00%00%00%00%00%00%00%00%00%00%01.%00%00%00%00%00%00%00%01.key1
p       %00%00%00%00%00%00%00%0b%00%00%00%00%00%00%00%00%00%00%00%01~

case B) PER_POOL->PG
p       %00%00%00%00%00%00%00%0b%00%00%00%00%00%00%00%00%00%00%00%01-
p       %00%00%00%00%00%00%00%0b%00%00%00%00%00%00%00%00%00%00%00%01.%00%00%00%00%00%00%00%0b%00%00%00%00%00%00%00%01-
p       %00%00%00%00%00%00%00%0b%00%00%00%00%00%00%00%00%00%00%00%01.%00%00%00%00%00%00%00%0b%00%00%00%00%00%00%00%01.key1
p       %00%00%00%00%00%00%00%0b%00%00%00%00%00%00%00%00%00%00%00%01~

So in both cases one can see a duplicate header record (with tailing '-') and corrupted regular key.
The the following pattern matching alg is applied:
1) Search for the first '.' and following '-'.
2) Search for the second '.' if '-' wasn't found at 1)
3) Compare last 8 bytes (nid) before each found delimiter and skip the record if they don't match.
  Well, there is probably a bug here - user keys containing '-' would be false positive for '-' lookup and skipped due to unmatching nids. Perhaps we should do the second '.' lookup first and proceed with '-' lookup if not found only
4) Remove original record
5) insert new one if that's a user key (two '.' found).

4)

**Comment by aclamk** [comment]
This is my BULK -> PG broken upgrade.

```
M	%00%00%00%00%00%00%04%03~
M	%00%00%00%00%00%00%04%85-
M	%00%00%00%00%00%00%04%85.a
M	%00%00%00%00%00%00%04%85.b
M	%00%00%00%00%00%00%04%85~
M	%00%00%00%00%00%00%04%86.c
M	%00%00%00%00%00%00%04%86.d
M	%00%00%00%00%00%00%04%86~

p	%00%00%00%00%00%00%00%00%c1%a3%fcn%00%00%00%00%00%00%04%03~
p	%00%00%00%00%00%00%00%02J~hx%00%00%00%00%00%00%04%85-
p	%00%00%00%00%00%00%00%02J~hx%00%00%00%00%00%00%04%85.%00%00%00%00%00%00%04%85-
p	%00%00%00%00%00%00%00%02J~hx%00%00%00%00%00%00%04%85.%00%00%00%00%00%00%04%85.a
p	%00%00%00%00%00%00%00%02J~hx%00%00%00%00%00%00%04%85.%00%00%00%00%00%00%04%85.b
p	%00%00%00%00%00%00%00%02J~hx%00%00%00%00%00%00%04%85~
p	%00%00%00%00%00%00%00%02s%0e%9f%e6%00%00%00%00%00%00%04%86.%00%00%00%00%00%00%04%86.c
p	%00%00%00%00%00%00%00%02s%0e%9f%e6%00%00%00%00%00%00%04%86.%00%00%00%00%00%00%04%86.d
p	%00%00%00%00%00%00%00%02s%0e%9f%e6%00%00%00%00%00%00%04%86~
```

**Comment by ifed01** [comment]
> This is my BULK -> PG broken upgrade.
> 
> ```
> M	%00%00%00%00%00%00%04%03~
> M	%00%00%00%00%00%00%04%85-
> M	%00%00%00%00%00%00%04%85.a
> M	%00%00%00%00%00%00%04%85.b
> M	%00%00%00%00%00%00%04%85~
> M	%00%00%00%00%00%00%04%86.c
> M	%00%00%00%00%00%00%04%86.d
> M	%00%00%00%00%00%00%04%86~
> 
> p	%00%00%00%00%00%00%00%00%c1%a3%fcn%00%00%00%00%00%00%04%03~
> p	%00%00%00%00%00%00%00%02J~hx%00%00%00%00%00%00%04%85-
> p	%00%00%00%00%00%00%00%02J~hx%00%00%00%00%00%00%04%85.%00%00%00%00%00%00%04%85-
> p	%00%00%00%00%00%00%00%02J~hx%00%00%00%00%00%00%04%85.%00%00%00%00%00%00%04%85.a
> p	%00%00%00%00%00%00%00%02J~hx%00%00%00%00%00%00%04%85.%00%00%00%00%00%00%04%85.b
> p	%00%00%00%00%00%00%00%02J~hx%00%00%00%00%00%00%04%85~
> p	%00%00%00%00%00%00%00%02s%0e%9f%e6%00%00%00%00%00%00%04%86.%00%00%00%00%00%00%04%86.c
> p	%00%00%00%00%00%00%00%02s%0e%9f%e6%00%00%00%00%00%00%04%86.%00%00%00%00%00%00%04%86.d
> p	%00%00%00%00%00%00%00%02s%0e%9f%e6%00%00%00%00%00%00%04%86~
> ```

So it doesn't recovered properly, does it?

**Comment by ifed01** [comment]
@aclamk - well, looks like you're right - the matching algorithm should be fixed. 
Just seen records like that which escape the recovery:
p	%00%00%00%00%00%00%00%0ex%00%00%00%00%00%00%00%00%00%0a..%00%00%00%00%00%00%0a.._infover
p	%00%00%00%00%00%00%00%0e.%00%00%00%00%00%00%00%00%00%09%b8.%00%00%00%00%00%00%09%b8._infover
p	%00%00%00%00%00%00%00%0e%26%00%00%00%00%00%00%00%00%00%0a-.%00%00%00%00%00%00%0a-._infover

**Comment by aclamk** [comment]
And same, but for POOL -> PG broken upgrade.

In both cases, I just created examples for myself to compare.
It has nothing to do with repair algorithms - I wanted myself to have full picture.
```
m	%00%00%00%00%00%00%00%00%00%00%00%00%00%00%04%03~
m	%00%00%00%00%00%00%00%02%00%00%00%00%00%00%05q-
m	%00%00%00%00%00%00%00%02%00%00%00%00%00%00%05q.a
m	%00%00%00%00%00%00%00%02%00%00%00%00%00%00%05q.b
m	%00%00%00%00%00%00%00%02%00%00%00%00%00%00%05q~
m	%00%00%00%00%00%00%00%02%00%00%00%00%00%00%05%ba.c
m	%00%00%00%00%00%00%00%02%00%00%00%00%00%00%05%ba.d
m	%00%00%00%00%00%00%00%02%00%00%00%00%00%00%05%ba~

p	%00%00%00%00%00%00%00%00%c1%a3%fcn%00%00%00%00%00%00%04%03~
p	%00%00%00%00%00%00%00%02J~hx%00%00%00%00%00%00%05q-
p	%00%00%00%00%00%00%00%02J~hx%00%00%00%00%00%00%05q.%00%00%00%00%00%00%00%02%00%00%00%00%00%00%05q-
p	%00%00%00%00%00%00%00%02J~hx%00%00%00%00%00%00%05q.%00%00%00%00%00%00%00%02%00%00%00%00%00%00%05q.a
p	%00%00%00%00%00%00%00%02J~hx%00%00%00%00%00%00%05q.%00%00%00%00%00%00%00%02%00%00%00%00%00%00%05q.b
p	%00%00%00%00%00%00%00%02J~hx%00%00%00%00%00%00%05q~
p	%00%00%00%00%00%00%00%02s%0e%9f%e6%00%00%00%00%00%00%05%ba.%00%00%00%00%00%00%00%02%00%00%00%00%00%00%05%ba.c
p	%00%00%00%00%00%00%00%02s%0e%9f%e6%00%00%00%00%00%00%05%ba.%00%00%00%00%00%00%00%02%00%00%00%00%00%00%05%ba.d
p	%00%00%00%00%00%00%00%02s%0e%9f%e6%00%00%00%00%00%00%05%ba~
```

**Comment by aclamk** [comment]
@ifed01 
Side note: this one is useful now for me:
https://github.com/ceph/ceph/pull/43865

**Comment by aclamk** [comment]
@ifed01 
Previously, I posted broken table. Here it is fixed.

```
   00000000000000001111111111111111               000000000000000011111111111111112222222222
   0123456789abcdef0123456789abcdef	          0123456789abcdef0123456789abcdef0123456789

   ORIGINAL                                       AFTER FAILED CONVERSION
   
   HEAD new, is ok
1) nnnnnnnn-                        BULK->PG      pppppppphhhhnnnnnnnn-
2) ppppppppnnnnnnnn-                POOL->PG      pppppppphhhhnnnnnnnn-
   
   HEAD converted incorrectly, delete:
3) nnnnnnnn-                        BULK->PG      pppppppphhhhnnnnnnnn.nnnnnnnn-
4) ppppppppnnnnnnnn-                POOL->PG      pppppppphhhhnnnnnnnn.ppppppppnnnnnnnn-
   
   KEYS converted incorrectly, must convert:
5) nnnnnnnn.kkkkk                   BULK->PG      pppppppphhhhnnnnnnnn.nnnnnnnn.kkkkk
6) ppppppppnnnnnnnn.kkkkk           POOL->PG      pppppppphhhhnnnnnnnn.ppppppppnnnnnnnn.kkkkk

Legend:
n - nid
h - hash
p - pool
k - key
```

**Comment by ifed01** [comment]
@aclamk - here is an improved pattern matching implementation along with a set of test cases to verify it. 
A bit simpler (and a bit less universal) competitor for #43869

**Comment by tmolitor-stud-tu** [comment]
this new pull request doesn't apply cleanly to the v16.2.6 tag anymore

**Comment by ifed01** [comment]
> this new pull request doesn't apply cleanly to the v16.2.6 tag anymore
you might use the following commits only:
git cherry-pick 716bc62f43febd46ec381b49eec7c1638040f28a abe0237fe13005f7f00567dafe3d802b216be3e0 2ba66726233596ab48d1f50f563aed7a2b3aa4ed

**Comment by tmolitor-stud-tu** [comment]
@ifed01 yes, I already did so, but others might not figure this out.

**Comment by tmolitor-stud-tu** [comment]
The new repair command seemed to work.
I repaired all osds and started them.
But one of my rbd disks was missing from `rbd du`. (including a error message about failing to open an image).
I figured I'd restart all osd servers and then the missing rbd disk popped up but another one was missing.
After waiting a bit the missing one popped up, too,  and the error message from `rbd du` vanished.

But: one osd did not come up after the reboot and the dir `/var/lib/ceph/osd/ceph-0` of this osd now is empty. I don't know if that is another rare bug of ceph 16.2.6 or something done by the code in this PR, but I just wanted to let you know.

**Pull request closed without merging**
