### PR TITLE
rgw: fix build failure, reference member correctly

### PR DESCRIPTION
**Pull request by theanalyst**
fixing referring to a non pointer member via -> operator
Signed-off-by: Abhishek Lekshmanan <abhishek@suse.com>

### CODE REVIEW

**Comment by dachary** [comment]
<pre>
Reviewed-by: Loic Dachary &lt;ldachary@redhat.com>
</pre>

as soon as the bot confirms it compiles

**Comment by xiexingguo** [comment]
@theanalyst @dachary I opened https://github.com/ceph/ceph/pull/8394 for the same problem and has already done compiling, though there are other ut errors...

**Comment by xiexingguo** [comment]
And https://github.com/ceph/ceph/pull/8396 is a dup too...

**Comment by theanalyst** [comment]
@xiexingguo mea culpa, thanks! closing this then

**Comment by xiexingguo** [comment]
@theanalyst Never mind and your guys are really nice.

**Pull request closed without merging**
