### PR TITLE
ceph,pybind/mgr: a few py3 fixes

### PR DESCRIPTION
**Pull request by liewegas**
- 'ceph wahtever -o -' now works
- mgr modules sort (most) json output keys

### CODE REVIEW

**Comment by liewegas** [comment]
retest this please

**Comment by ajarr** [comment]
@liewegas does this need to be backported to nautilus?

**Comment by liewegas** [comment]
I don't think so... nautilus is python 2.  And the key sorting is mostly cosmetic (and to keep the tests from failing.. but i haven't seen failures on nautilus)

**Comment by sebastian-philipp** [comment]
Well, nautilus on suse is already py3. so. I'd say yes!

**Pull request merged**
