### PR TITLE
jewel: rgw: Custom data header support

### PR DESCRIPTION
**Pull request by prallabh**
Fixes: http://tracker.ceph.com/issues/19844
Signed-off-by: Pavan Rallabhandi <PRallabhandi@walmartlabs.com>

### CODE REVIEW

**Comment by prallabh** [comment]
@mattbenjamin can you please help review, since you had an RH equivalent patch, thanks!

**Comment by prallabh** [comment]
CC: @smithfarm @yehudasa

**Comment by smithfarm** [comment]
@prallabh Is there a reason why this wasn't cherry-picked from master?

**Comment by prallabh** [comment]
It's not a direct patch from master, like we don't have `RGWObjEnt` present in master unlike here.

**Comment by prallabh** [comment]
@smithfarm can you please check now, I've cherry picked from master, thanks!

**Comment by smithfarm** [comment]
Thanks, @prallabh, the commit message looks good now. I'll include this in the next integration run.

**Comment by smithfarm** [comment]
Merge conflict. @prallabh please rebase.

**Comment by prallabh** [comment]
@smithfarm done

**Comment by smithfarm** [comment]
jenkins build docs

**Comment by smithfarm** [comment]
jenkins test docs

**Comment by smithfarm** [comment]
@mattbenjamin This passed an rgw suite at http://tracker.ceph.com/issues/20613#note-43

Please review.

**Pull request merged**
