### PR TITLE
jewel: osdc/Objecter: prevent double-invocation of linger op callback

### PR DESCRIPTION
**Pull request by pdvian**
http://tracker.ceph.com/issues/23905

### CODE REVIEW

**Comment by pdvian** [comment]
Wrongly pushed other backport PR. Correcting it now.

**Comment by smithfarm** [comment]
i.e. cherry-pick the 3 commits from https://github.com/ceph/ceph/pull/21831 - right, @tchaikov ?

**Comment by tchaikov** [comment]
@smithfarm i mean, we should also backport #21831 along with this commit, and i did so in #22188. so i re-added the jewel-batch-1 label.

**Comment by tchaikov** [comment]
@yuriw @theanalyst can we include this change in the next test batch?

**Comment by yuriw** [comment]
[wip-yuri4-testing-2018-06-12-2037-jewel](https://trello.com/c/tzHUzvPd/327-wip-yuri4-testing-2018-06-12-2037-jewel)

**Pull request merged**
