### PR TITLE
luminous: qa/suites/fs: use bigger cinder volumes

### PR DESCRIPTION
**Pull request by vshankar**
https://tracker.ceph.com/issues/24759

### CODE REVIEW

**Comment by smithfarm** [comment]
jenkins test docs

**Comment by yuriw** [comment]
[wip-yuri5-testing-2018-12-12-1653-luminous](https://trello.com/c/oXzdX0yM/487-wip-yuri5-testing-2018-12-12-1653-luminous)

**Comment by yuriw** [comment]
[wip-yuri4-testing-2018-12-19-1658-luminous](https://trello.com/c/XKKZA4vr/494-wip-yuri4-testing-2018-12-19-1658-luminous)

**Comment by vshankar** [comment]
Reviewed-by: Venky Shankar <vshankar@redhat.com>

**Pull request merged**
