### PR TITLE
os/bluestore: adding some sensors to detect and log slow ops

### PR DESCRIPTION
**Pull request by ifed01**
Doing that at both BlueStore and KernelDevice levels.

Signed-off-by: Igor Fedotov <ifedotov@suse.com>

- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by ifed01** [comment]
please ignore the first commit for now

**Comment by xiexingguo** [comment]
Aah, this feature is useful and I like it!

**Comment by liewegas** [comment]
This generally looks fine.  I'm just a bit nervous about any performance impact from adding this instrumentation, esp in the block layer.  I think I'm off by a few orders of magnitude before it's significant?

**Comment by ifed01** [comment]
> This generally looks fine. I'm just a bit nervous about any performance impact from adding this instrumentation, esp in the block layer. I think I'm off by a few orders of magnitude before it's significant?

@liewegas - please note that generally performance overhead includes just additional 'if' statement to verify if operation has been lasted too long. And then log it. Under normal circumstances logging overhead isn't present.
Moreover for block layer I bound aio long execution tracking to existing 'bdev_debug_aio' infra. Which prevents it from execution by default. Reads are tracked only but again generally performance overhead includes just op duration measurement.

**Comment by liewegas** [comment]
retest this please

**Comment by liewegas** [comment]
retest this please

**Pull request merged**
