### PR TITLE
tasks/ceph: get rid of iteritems for python3

### PR DESCRIPTION
**Pull request by kshtsk**
For python3 compatibility use items() instead of iteritems().

Signed-off-by: Kyr Shatskyy <kyrylo.shatskyy@suse.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`

</details>

### CODE REVIEW

**Comment by batrick** [comment]
retest this please

**Comment by kshtsk** [comment]
jenkins test docs

**Comment by tchaikov** [comment]
- http://pulpito.ceph.com/kchai-2019-10-09_15:12:02-rados-wip-kefu-testing-2019-10-09-1243-distro-basic-smithi/
- http://pulpito.ceph.com/kchai-2019-10-14_06:20:56-rados-wip-kefu-testing-2019-10-14-1111-distro-basic-smithi/

failures tracked by 

- https://tracker.ceph.com/issues/42301
- https://tracker.ceph.com/issues/40026

**Comment by djgalloway** [comment]
@kshtsk Can you take a look at my last comment in https://tracker.ceph.com/issues/42313#note-11 and confirm or deny my suspicion please?

**Pull request merged**
