### PR TITLE
quincy: rgw: fix consistency bug with OLH objects

### PR DESCRIPTION
**Pull request by cfsnyder**
backport tracker: https://tracker.ceph.com/issues/62066

---

backport of https://github.com/ceph/ceph/pull/51700
parent tracker: https://tracker.ceph.com/issues/61359

this backport was staged using ceph-backport.sh version 16.0.0.6848
find the latest version at https://github.com/ceph/ceph/blob/main/src/script/ceph-backport.sh

### CODE REVIEW

**Comment by cfsnyder** [comment]
jenkins test make check

**Comment by yuriw** [comment]
@cfsnyder @cbodley [pls merge at will
ref: https://trello.com/c/UFKABPAT

**Review by cbodley — APPROVED** [review]

**Comment by cbodley** [comment]
jenkins test api

**Comment by cbodley** [comment]
jenkins test make check

**Comment by cbodley** [comment]
@cfsnyder the 'make check' failure is caused by your changes to test_rgw_reshard.py:
```
flake8: commands[0] /home/jenkins-build/build/workspace/ceph-pull-requests/qa> flake8 --select=F,E9 --exclude=venv,.tox
./workunits/rgw/test_rgw_reshard.py:3:1: F401 'errno' imported but unused
flake8: exit 1 (2.16 seconds) /home/jenkins-build/build/workspace/ceph-pull-requests/qa> flake8 --select=F,E9 --exclude=venv,.tox pid=556335
flake8: FAIL ✖ in 12.58 seconds
```

**Comment by cfsnyder** [comment]
pushed a fix for the flake8 lint

**Pull request merged**
