### PR TITLE
mgr/dashboard: Add a few type annotations

### PR DESCRIPTION
**Pull request by sebastian-philipp**
Using pytest-annotate

Signed-off-by: Sebastian Wagner <sewagner@redhat.com>

Howto:

* https://github.com/kensho-technologies/pytest-annotate
* https://github.com/dropbox/pyannotate

```diff
diff --git a/src/pybind/mgr/dashboard/tox.ini b/src/pybind/mgr/dashboard/tox.ini
index 1cda4c45ac..d1d0958662 100644
--- a/src/pybind/mgr/dashboard/tox.ini
+++ b/src/pybind/mgr/dashboard/tox.ini
@@ -21,6 +21,8 @@ addopts =
 deps =
     -rrequirements.txt
     -cconstraints.txt
+    pytest-annotate
+    pyannotate
 
 [base-test]
 deps =
@@ -45,7 +47,7 @@ setenv =
     UNITTEST = true
     WEBTEST_INTERACTIVE = false
 commands =
-    pytest {posargs}
+    pytest     --annotate-output=./annotations.json  {posargs}
 
 [testenv:run]
 basepython=python3
```
* `tox -e py3`
* `pyannotate --py3 -w --type-info ./annotations.json $(find * -name '*.py')`

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by avanthakkar** [comment]
@epuertat Maybe this can be an alternative wht we were trying to do here https://github.com/ceph/ceph/pull/39893 for run-time type checking?

**Comment by epuertat** [comment]
> @epuertat Maybe this can be an alternative wht we were trying to do here #39893 for run-time type checking?

Looks an interesting way to populate type hints @avanthakkar , but I don't see how it may enforce runtime typing 🤔

**Review by avanthakkar — APPROVED** [review]

**Review by alfonsomthd — CHANGES_REQUESTED** [review]
@sebastian-philipp Can you create a tracker issue?

**Comment by tchaikov** [comment]
> @sebastian-philipp Can you create a tracker issue?

@alfonsomthd why do we need a tracker issue for a change like this? i mean, it is not a bug fix or part of a critical feature which should be backported.

**Comment by tchaikov** [comment]
- https://pulpito.ceph.com/kchai-2021-07-17_04:37:01-rados-wip-kefu-testing-2021-07-17-1006-distro-basic-smithi/
- https://pulpito.ceph.com/kchai-2021-07-17_15:53:41-rados-wip-kefu-testing-2021-07-17-1518-distro-basic-smithi/

one of the failures is tracked by:

- https://tracker.ceph.com/issues/50245

the e2e failures are not related.

**Comment by alfonsomthd** [comment]
> > @sebastian-philipp Can you create a tracker issue?
> 
> @alfonsomthd why do we need a tracker issue for a change like this? i mean, it is not a bug fix or part of a critical feature which should be backported.

@tchaikov As there are still features/bugfixes to be backported to pacific I prefer to backport this in order to avoid backport conflicts in the future.
@epuertat  @sebastian-philipp What is the backporting criteria here?

**Comment by sebastian-philipp** [comment]
> > > @sebastian-philipp Can you create a tracker issue?
> > 
> > 
> > @alfonsomthd why do we need a tracker issue for a change like this? i mean, it is not a bug fix or part of a critical feature which should be backported.
> 
> @tchaikov As there are still features/bugfixes to be backported to pacific I prefer to backport this in order to avoid backport conflicts in the future.
> @epuertat @sebastian-philipp What is the backporting criteria here?

I wouldn't care to backport this.

**Pull request closed without merging**
