### PR TITLE
mgr/orchestrator: ServiceSpec: convert type annotations to py3

### PR DESCRIPTION
**Pull request by sebastian-philipp**
(just to make sure, doc is on Python 3)

Signed-off-by: Sebastian Wagner <sebastian.wagner@suse.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by sebastian-philipp** [comment]
Turns out:
```
WARNING: autodoc: failed to import method 'Orchestrator.get_feature_set' from module 'orchestrator'; the following exception was raised:
Traceback (most recent call last):
  File "/home/jenkins-build/build/workspace/ceph-pr-docs/build-doc/virtualenv/lib/python3.5/site-packages/sphinx/ext/autodoc/importer.py", line 32, in import_module
    return importlib.import_module(modname)
  File "/home/jenkins-build/build/workspace/ceph-pr-docs/build-doc/virtualenv/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 661, in exec_module
  File "<frozen importlib._bootstrap_external>", line 767, in get_code
  File "<frozen importlib._bootstrap_external>", line 727, in source_to_code
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/jenkins-build/build/workspace/ceph-pr-docs/src/pybind/mgr/orchestrator.py", line 1352
    self.placement: PlacementSpec = PlacementSpec() if placement is None else placement
                  ^
SyntaxError: invalid syntax
```

That syntax was added in Python 3.6: https://docs.python.org/3/whatsnew/3.6.html#whatsnew36-pep526

And that's a bummer, as this is required to use typed data classes, which would remove tons of boilerplate.

**Comment by liewegas** [comment]
the doc builder is probably old?

**Comment by sebastian-philipp** [comment]
I remember we've had a discussion about which python versions we'd like to support. Though, I can't find it in the clt pad.

**Comment by tchaikov** [comment]
> I remember we've had a discussion about which python versions we'd like to support. Though, I can't find it in the clt pad. 3.5 might be still required?

@sebastian-philipp please don't retreat to python3.5 just because we are using xenial node for building docs. i am trying to fix this with https://github.com/ceph/ceph-build/pull/1502

**Comment by sebastian-philipp** [comment]
Awesome! Big thanks @tchaikov !

**Comment by sebastian-philipp** [comment]
rebased

**Comment by sebastian-philipp** [comment]
qa passed

**Comment by tchaikov** [comment]
> Turns out, Python 3.6 adds support for variable type
> annotations. As we still need to support 3.5, we're
> limited to function signatures.
> 

@sebastian-philipp does the commit message still apply?

**Comment by sebastian-philipp** [comment]
in general, this PR is kind of  pointless. We don't need this change right now.

**Pull request closed without merging**
