### PR TITLE
Wip mpu reupload

### PR DESCRIPTION
**Pull request by mattbenjamin**
## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by mattbenjamin** [comment]
un-stahl

**Comment by cbodley** [comment]
hi @mattbenjamin, folks from Akamai/Linode joined today's refactoring call to discuss this issue. they'd like to help wherever they can, whether it's design/implementation/testing

would you be willing to type up a quick summary of your design here, and the potential next steps?

do you know if we have s3test cases that can exercise this stuff reliably? if not, maybe they could start writing some?

cc @yima77

**Comment by mattbenjamin** [comment]
> hi @mattbenjamin, folks from Akamai/Linode joined today's refactoring call to discuss this issue. they'd like to help wherever they can, whether it's design/implementation/testing
> 
> would you be willing to type up a quick summary of your design here, and the potential next steps?
> 
> do you know if we have s3test cases that can exercise this stuff reliably? if not, maybe they could start writing some?
> 
> cc @yima77

Sure, @cbodley

**Comment by mattbenjamin** [comment]
@cbodley I've asked Josh to add yima77 (Yixin) to the Ceph org

**Comment by mattbenjamin** [comment]
@yuvalif this pr is now layered on https://github.com/ceph/ceph/pull/48767, so in fact is just the top 3 commits

**Comment by cbodley** [comment]
@mattbenjamin now that the header reorg PR merged, what's the next step here?

**Comment by cbodley** [comment]
merged in https://github.com/ceph/ceph/pull/49709 🎉

**Pull request closed without merging**
