### PR TITLE
pacific: test: fix TierFlushDuringFlush to wait until dedup_tier is set on bas…

### PR DESCRIPTION
**Pull request by myoungwon**
backport tracker: https://tracker.ceph.com/issues/56099, https://tracker.ceph.com/issues/56656

---

backport of https://github.com/ceph/ceph/pull/45035, https://github.com/ceph/ceph/pull/46866
parent tracker: https://tracker.ceph.com/issues/53855, https://tracker.ceph.com/issues/53294

Signed-off-by: Myoungwon Oh <myoungwon.oh@samsung.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Review by ljflores — APPROVED** [review]

**Review by ljflores — CHANGES_REQUESTED** [review]
@myoungwon please have a look. This was caught on a test branch that contains your fix.

/a/yuriw-2022-07-05_17:38:43-rados-wip-yuri4-testing-2022-07-05-0719-pacific-distro-default-smithi/6915020
```
2022-07-06T02:26:55.749 INFO:tasks.ceph.osd.5.smithi191.stderr:2022-07-06T02:26:55.748+0000 7f83aa443700 -1 osd.5 399 get_health_metrics reporting 15 slow ops, oldest is osd_op(client.4785.0:7419 214.f 214:f5e1fadd:test-rados-api-smithi191-104463-84::foo:head [tier-flush] snapc 0=[] RETRY=1 ondisk+retry+read+ignore_cache+known_if_redirected e398)
2022-07-06T02:26:56.777 INFO:tasks.ceph.osd.5.smithi191.stderr:2022-07-06T02:26:56.763+0000 7f83aa443700 -1 osd.5 399 get_health_metrics reporting 15 slow ops, oldest is osd_op(client.4785.0:7419 214.f 214:f5e1fadd:test-rados-api-smithi191-104463-84::foo:head [tier-flush] snapc 0=[] RETRY=1 ondisk+retry+read+ignore_cache+known_if_redirected e398)
2022-07-06T02:26:57.748 INFO:tasks.ceph.osd.5.smithi191.stderr:2022-07-06T02:26:57.747+0000 7f83aa443700 -1 osd.5 399 get_health_metrics reporting 15 slow ops, oldest is osd_op(client.4785.0:7419 214.f 214:f5e1fadd:test-rados-api-smithi191-104463-84::foo:head [tier-flush] snapc 0=[] RETRY=1 ondisk+retry+read+ignore_cache+known_if_redirected e398)
2022-07-06T02:26:58.757 INFO:tasks.workunit.client.0.smithi191.stderr:++ cleanup
2022-07-06T02:26:58.757 INFO:tasks.workunit.client.0.smithi191.stderr:++ pkill -P 104256
2022-07-06T02:26:58.780 DEBUG:teuthology.orchestra.run:got remote process result: 124
2022-07-06T02:26:58.781 INFO:tasks.workunit.client.0.smithi191.stderr:/home/ubuntu/cephtest/clone.client.0/qa/workunits/rados/test.sh: line 10: 104457 Terminated              bash -o pipefail -exc "ceph_test_rados_$f $color 2>&1 | tee ceph_test_rados_$ff.log | sed \"s/^/$r: /\""
2022-07-06T02:26:58.782 INFO:tasks.workunit.client.0.smithi191.stderr:++ true
2022-07-06T02:26:58.783 INFO:tasks.workunit.client.0.smithi191.stdout:              api_tier_pp: [       OK ] LibRadosTwoPoolsPP.CacheP
2022-07-06T02:26:58.783 INFO:tasks.workunit:Stopping ['rados/test.sh'] on client.0...
2022-07-06T02:26:58.785 DEBUG:teuthology.orchestra.run.smithi191:> sudo rm -rf -- /home/ubuntu/cephtest/workunits.list.client.0 /home/ubuntu/cephtest/clone.client.0
2022-07-06T02:26:58.797 INFO:tasks.ceph.osd.5.smithi191.stderr:2022-07-06T02:26:58.796+0000 7f83aa443700 -1 osd.5 399 get_health_metrics reporting 15 slow ops, oldest is osd_op(client.4785.0:7419 214.f 214:f5e1fadd:test-rados-api-smithi191-104463-84::foo:head [tier-flush] snapc 0=[] RETRY=1 ondisk+retry+read+ignore_cache+known_if_redirected e398)
2022-07-06T02:26:59.053 ERROR:teuthology.run_tasks:Saw exception from tasks.
```

This tracker is fixing an issue with `LibRadosTwoPoolsPP.TierFlushDuringFlush`, but I see that this one caught on `LibRadosTwoPoolsPP.CachePin`. We have been treating the failures on `TierFlushDuringFlush` and `CachePin` as the same, but I wonder if these are two separate issues (see https://tracker.ceph.com/issues/53855 for both examples).

All in all, we should make sure that this PR is truly fixing the issue before we move forward with the backport.

**Comment by ljflores** [comment]
> @ljflores I observed the same issue as this before, then fixed it by #46866. It seems that #46866 needs to pass QA first, then it should be backport to pacific and quincy.

I see, thanks @myoungwon. I have approved #46866 and tagged it for `needs-qa`.

**Review by ljflores — APPROVED** [review]

**Comment by ljflores** [comment]
#46866 still needs a pacific backport. Then this one and the pacific backport for #46866 can be tested together.

**Comment by myoungwon** [comment]
@ljflores I added a commit regarding https://github.com/ceph/ceph/pull/46866 here because it causes a conflict without this PR. Is that OK?

**Comment by ljflores** [comment]
@myoungwon Yes this is okay. I meant for those to backports to be tested together, and adding the commit here fulfills that. Thanks!

**Comment by kamoltat** [comment]
Rados Approved!

[Pulpito :: Results Dashboard](https://pulpito.ceph.com/yuriw-2022-08-04_11:58:29-rados-wip-yuri3-testing-2022-08-03-0828-pacific-distro-default-smithi/)

0 Related Failures:
17 Tracked Failures:

2 jobs with [Bug #53501: Exception when running 'rook' task. - Orchestrator - Ceph](https://tracker.ceph.com/issues/53501)
1 job with [Bug #53939: ceph-nfs-upgrade, pacific: Upgrade Paused due to UPGRADE_REDEPLOY_DAEMON: Upgrading daemon osd.0 on host smithi103 failed - Orchestrator - Ceph](https://tracker.ceph.com/issues/53939)
3 jobs with [Bug #55443: "SELinux denials found.." in rados run - Infrastructure - Ceph](https://tracker.ceph.com/issues/55443)
1 job with [Bug #45318: Health check failed: 2/6 mons down, quorum b,a,c,e (MON_DOWN)" in cluster log running tasks/mon_clock_no_skews.yaml - RADOS - Ceph](https://tracker.ceph.com/issues/45318)
2 jobs with [Bug #52321: qa/tasks/rook times out: 'check osd count' reached maximum tries (90) after waiting for 900 seconds - Orchestrator - Ceph](https://tracker.ceph.com/issues/52321)
1 job with [Bug #54071: rados/cephadm/osds: Invalid command: missing required parameter hostname(<string>) - Orchestrator - Ceph](https://tracker.ceph.com/issues/54071)
1 job with [Bug #52124: Invalid read of size 8 in handle_recovery_delete() - RADOS - Ceph](https://tracker.ceph.com/issues/52124)
1 job with [Bug #56573: test_cephadm.sh: KeyError: 'TYPE' - Orchestrator - Ceph](https://tracker.ceph.com/issues/56573)

0 Newly Tracked Failures:
0 Dead Jobs

**Pull request merged**
