### PR TITLE
osd: pg primary write

### PR DESCRIPTION
**Pull request by bigwhite37**
The main purpose of this pr is to let the pg can reply the client's writing while not all osds have committed so that the availability of ceph can be improved. To implement this, I add a configuration item named "osd_pool_default_primary_write_size" which is used to control when to reply client until the number of osds have committed for writing. 

Up to now, osd_pool_default_primary_write_size only works for replicated pool.

Signed-off-by: Zhenyi Shu shuzy5@chinaunicom.cn

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by tchaikov** [comment]
i think this is a weak consistency model proposed by some community contributor before.

**Comment by athanatos** [comment]
I don't think this is a good idea.  The high level behaviour would look like randomly lost writes and other strange anomalies in situations where cluster configuration changes.

**Comment by neha-ojha** [comment]
I agree with @athanatos. FWIW, asynchronous recovery has already improved the availability of PGs when the cluster is in a degraded state.

**Comment by wuxingyi** [comment]
@athanatos  if this patch passed all the teuthology test cases, can it be considered as safe? I think this patch can improve pg availblility a lot.
@neha-ojha, asynchronous recovery can't solve the problem when an osd died silently, and other osds can only detect it through heartbeat mechanism, this means quit a long time(30s by default?).

**Comment by athanatos** [comment]
@wuxingyi This genuinely won't work in a lot of common cases -- clients would see completed writes disappear with certain failure or unavailability patterns.  I think you should focus on looking into techniques which would improve failure detection.

**Pull request closed without merging**
