### PR TITLE
osd,objecter: add pool EIO flag; make client return EIO when it is set

### PR DESCRIPTION
**Pull request by liewegas**
- new CLI commands to set/unset the pool EIO flag
- osd will reply with EIO if the client is old, drop op if client is new
- objecter will reply immediately with EIO

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by tchaikov** [comment]
@liewegas hi Sage, i am curious why we need to poison a pool by returning EIO unconditionally? could you shed some lights on the use case of this change?

**Comment by liewegas** [comment]
> @liewegas hi Sage, i am curious why we need to poison a pool by returning EIO unconditionally? could you shed some lights on the use case of this change?

The motivation is replica-1 pools.  At some point we need to make the pool (RBD probably) return EIO.  The librados timeouts aren't sufficient (implementation is wonky, there is no sourc eof truth for whether the device is failed or not, etc.).  This lets us separate the mechanism (pool is "failed" and returns EIO or isn't) from the policy (could be any number of policies for when we decide to declare a replica-1 pool offline).

See https://pad.ceph.com/p/pool_eio_flag

**Review by athanatos — APPROVED** [review]
Nice and simple!

**Comment by athanatos** [comment]
I'd vote for SUPPORTSPOOLEIO over POOLEIOOK fwiw.

**Comment by jdurgin** [comment]
Seems nice and simple like we discussed. Do we want to document this, or leave it as a hidden feature? It will make clients that don't support it hang, which may not be desirable (requires a higher layer to verify all clients are new enough).

**Review by neha-ojha — APPROVED** [review]

**Review by jdurgin — APPROVED** [review]
agreed, not worth a feature bit. We haven't added any new ones in quincy so far!

**Comment by liewegas** [comment]
jenkins test make check

**Pull request merged**
