### PR TITLE
os/bluestore/BlueFS: Rebuild memcopy for bufferlist::page_aligned_app…

### PR DESCRIPTION
**Pull request by majianpeng**
…ender

BlueFS use bufferlist::page_aligned_appender to make data aligned
w/ memory. But bufferlist::rebuild_aligned_size_and_memory don't handle
this case. For example:
```c++
buffer::list(len=4096,
  buffer::ptr(90112~2018 0x55f4de51e000 in raw 0x55f4de508000 len 1048576 nref 7),
  buffer::ptr(92130~2078 0x55f4de51e7e2 in raw 0x55f4de508000 len 1048576 nref 7)
)
```
After bufferlist::rebuild_aligned_size_and_memory()
```c++
buffer::list(
len=4096, buffer::ptr(0~4096 0x55f4de6de000 in raw 0x55f4de6de000 len 4096 nref 1)
)
```
Using bufferlist::append(ptr, offset, len) function to make all continue
prt merge.

Signed-off-by: Jianpeng Ma <jianpeng.ma@intel.com>

### CODE REVIEW

**Comment by xiexingguo** [comment]
retest this please

**Comment by liewegas** [comment]
I think the bug here is that page_aligned_appender isn't working as designed.  It is expecting an append that is part of the tail buffer to simply adjust that tail buffer.

**Comment by majianpeng** [comment]
I don't think so. So append there is no problem. For example:
append(0, 3K)--> tail(0,3k)
append(0,1k)---> tail + append
tail && append are continue. But rebuild_aligned_size_and_memory can't handle this case.

**Comment by liewegas** [comment]
https://github.com/ceph/ceph/pull/15767 tests out okay..

**Comment by liewegas** [comment]
I'm not following where rebuild_aligned_size_and_memory enters the picture.  Where did you see that fragmented buffer above?

**Comment by liewegas** [comment]
Oh.. is it because the _flush() method is called, transfering the tail ptr to the other bufferlist, and the contiguous appender continues adding bits to the writer buffer?

**Comment by majianpeng** [comment]
rados -p rbd put intel /tmp/test ; test size is 4K.

**Comment by majianpeng** [comment]
Yes.

**Comment by liewegas** [comment]
Ok I see now! Can you introduce a new method, claim_append_piecewise() (or similar) that does this instead of duplicating the loop multiple times?

**Comment by liewegas** [comment]
Good catch!

**Comment by majianpeng** [comment]
Ok. I'll do it.

**Comment by liewegas** [comment]
Can you also add a test (similar to the one in #15767... maybe cherry-pick that commit into this pr too) showing that it merges them?

**Comment by majianpeng** [comment]
OK.

**Comment by majianpeng** [comment]
update by your comments
a)add new function claim_append_piecewise; and related test case
b)cherry-pick your #15767

**Comment by liewegas** [comment]
http://pulpito.ceph.com/sage-2017-06-20_17:41:31-rados-wip-sage-testing-distro-basic-smithi/

**Pull request merged**
