### PR TITLE
qa/tests: Removed s3tests !

### PR DESCRIPTION
**Pull request by yuriw**
Fixes: https://tracker.ceph.com/issues/42802
Signed-off-by: Yuri Weinstein <yweinste@redhat.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by yuriw** [comment]
testing http://pulpito.front.sepia.ceph.com:80/yuriw-2019-11-14_16:48:47-upgrade:mimic-p2p:mimic-p2p-parallel-wip-yuri-mimic_13.2.7_RC2-distro-basic-smithi/

**Comment by cbodley** [comment]
instead of trying not to run s3tests against the prior point release, lets just run against the `ceph-luminous` branch of s3tests. those test cases should pass for both point releases

so the only change to this .yaml would be:
```diff
--- a/qa/suites/upgrade/mimic-p2p/mimic-p2p-parallel/point-to-point-upgrade.yaml
+++ b/qa/suites/upgrade/mimic-p2p/mimic-p2p-parallel/point-to-point-upgrade.yaml
@@ -171,7 +171,7 @@ workload_mimic:
      - print: "**** done rgw workload_mimic"
      - s3tests:
          client.0:
-           force-branch: ceph-mimic
+           force-branch: ceph-luminous
            rgw_server: client.0
            scan_for_encryption_keys: false
      - print: "**** done s3tests workload_mimic"
```

**Comment by yuriw** [comment]
trying with `force-branch: ceph-luminous` http://pulpito.front.sepia.ceph.com:80/yuriw-2019-11-14_17:15:58-upgrade:mimic-p2p:mimic-p2p-parallel-wip-yuri-mimic_13.2.7_RC2-distro-basic-smithi/

**Comment by yuriw** [comment]
removed 3tests http://pulpito.front.sepia.ceph.com:80/yuriw-2019-11-14_20:25:04-upgrade:mimic-p2p:mimic-p2p-parallel-wip-yuri-mimic_13.2.7_RC2-distro-basic-smithi/

**Pull request merged**
