### PR TITLE
mds: reduce memory usage of open file table prefetch

### PR DESCRIPTION
**Pull request by ukernel**
- Add an option that disables dirfrags prefetch. Dirfrags prefetch is the main cause of memory usage issue.
- Also modify client to encode inode's parent/d_name in cap_reconnect_t ,  which can eliminate the bad effect of disabling dirfrags prefetch.

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by batrick** [comment]
jenkins test dashboard backend

**Comment by batrick** [comment]
jenkins test dashboard backend

**Comment by ukernel** [comment]
jenkins retest this please

**Comment by batrick** [comment]
jenkins test api

**Comment by batrick** [comment]
jenkins test api

**Comment by batrick** [comment]
jenkins test api

**Comment by batrick** [comment]
https://pulpito.ceph.com/pdonnell-2020-08-29_19:47:16-fs-wip-pdonnell-testing-20200829.172552-distro-basic-smithi/

Failures unrelated.

**Pull request merged**
