### PR TITLE
rgw: use the compatibilty function for pthread_setname

### PR DESCRIPTION
**Pull request by wjwithagen**
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by tchaikov** [comment]
retest this please

**Comment by ivancich** [comment]
Pulpito results:
http://pulpito.ceph.com/ivancich-2019-04-23_19:53:03-rgw-wip-eric-testing-1-distro-basic-smithi/
http://pulpito.ceph.com/ivancich-2019-04-23_19:52:23-rgw-wip-eric-testing-1-distro-basic-smithi/

**Comment by ivancich** [comment]
@wjwithagen There's no tracker associated with this. Did you want any backports?

**Comment by wjwithagen** [comment]
@ivancich 
As far as I can tell is the code/PR that is corrected by this PR not backported.
Until that happens this PR also does not need to be backported.

**Pull request merged**
