### PR TITLE
mgr/dashboard: rbd: add @AuthRequired to snapshots controller

### PR DESCRIPTION
**Pull request by rjfd**
Signed-off-by: Ricardo Dias <rdias@suse.com>

### CODE REVIEW

**Comment by ricardoasmarques** [comment]
Well, this PR is my main argument to defend that authentication should be required by default, and we should disable it explicitly when we don't want it...

**Comment by LenzGr** [comment]
I tend to agree with @ricardoasmarques here. I'd assume that the majority of the REST API endpoints requires authentication by default and we should rather think about making it possible to add an exception to the rule, if necessary.

**Comment by rjfd** [comment]
@ricardoasmarques @LenzGr created http://tracker.ceph.com/issues/23796 to keep track of that.

**Comment by rjfd** [comment]
QA dashboard test cases run successfully although the tests were marked as failed due to an unrelated failure: http://pulpito.ceph.com/rdias-2018-04-19_15:33:17-rados:mgr-wip-rdias-testing-distro-basic-smithi/

**Comment by rjfd** [comment]
jenkins retest this please

**Pull request merged**
