### PR TITLE
DNM qa: update deb package list

### PR DESCRIPTION
**Pull request by jdurgin**
Include all debs explicitly, so that installing a downgrade from the distro
(e.g. 10.2.0 on xenial) works.

Related: http://tracker.ceph.com/issues/17960

### CODE REVIEW

**Comment by liewegas** [comment]
@jdurgin @dmick ping?

**Comment by dmick** [comment]
yeah, I haven't untangled this.

**Comment by dmick** [comment]
...but I'm happy if it works, and happy if @jdurgin is

**Comment by jdurgin** [comment]
it doesn't fully address the problem - it needs further untangling to handle e.g. hammer on xenial

**Comment by gregsfortytwo** [comment]
Given that this is DNM and I'd assume any issues with builds have been resolved in the last 18 months, I'm closing this PR. :)

**Pull request closed without merging**
