### PR TITLE
nautilus: common: Fix assertion when disabling and re-enabling clog_to_monitors

### PR DESCRIPTION
**Pull request by gerald-yang**
backport tracker: https://tracker.ceph.com/issues/49640

backport of #38997
parent tracker: https://tracker.ceph.com/issues/48946

Tested on centos7

### CODE REVIEW

**Review by neha-ojha — COMMENTED** [review]
@gerald-yang could you please use "cherry-pick -x" to reference the original commits? details in https://docs.ceph.com/en/latest/dev/development-workflow/#publishing-point-releases-and-backporting. Alternatively, you can use https://github.com/ceph/ceph/blob/master/src/script/ceph-backport.sh

**Comment by gerald-yang** [comment]
@neha-ojha
thanks for the advise, I've modified the PR to use "cherry-pick -x"
I also built the source with do_cmake.sh and make, and ran tests with vstart.sh/vstop.sh, it's all correct
I'm not sure why it shows "make check failed", is there anything I missed?

**Comment by neha-ojha** [comment]
> @neha-ojha
> thanks for the advise, I've modified the PR to use "cherry-pick -x"
> I also built the source with do_cmake.sh and make, and ran tests with vstart.sh/vstop.sh, it's all correct
> I'm not sure why it shows "make check failed", is there anything I missed?

Thanks for updating the commits. The "make check" failure in TestOSDScrub.scrub_time_permit is unrelated to your PR and has been seen in other PRs too, like https://jenkins.ceph.com/job/ceph-pull-requests/72747/consoleFull#15810503667dc3600c-28d8-42e2-9653-291a0c275fdf

**Comment by neha-ojha** [comment]
jenkins test make check

**Comment by gerald-yang** [comment]
got it, thanks

**Comment by smithfarm** [comment]
jenkins test make check

**Comment by yuriw** [comment]
@gerald-yang pls sign this PR
@neha-ojha this passed tests and can be merged if all is resolved.

**Comment by smithfarm** [comment]
jenkins test signed

**Comment by smithfarm** [comment]
@neha-ojha All required Jenkins tests have passed. Ready for review/merge.

**Comment by yuriw** [comment]
@smithfarm API tests still failed

**Comment by smithfarm** [comment]
> @smithfarm API tests still failed

Not required in nautilus.

**Review by neha-ojha — APPROVED** [review]

**Pull request merged**
