### PR TITLE
msg/async/ProtocolV2: take care of features when replacing the socket

### PR DESCRIPTION
**Pull request by idryomov**

### CODE REVIEW

**Comment by idryomov** [comment]
-s rados/singleton-nomsgr --filter 'all/health-warnings rados' -N 20:
https://pulpito.ceph.com/dis-2020-06-28_18:37:38-rados:singleton-nomsgr-wip-msgr21-fix-reuse-rebuildci-distro-basic-smithi/

-s rados --subset 1/3333 --filter-out cephadm:
https://pulpito.ceph.com/dis-2020-06-28_18:43:20-rados-wip-msgr21-fix-reuse-rebuildci-distro-basic-smithi/

**Comment by idryomov** [comment]
-s rados/singleton-nomsgr --filter 'all/health-warnings rados' -N 20 / 200:
https://pulpito.ceph.com/dis-2020-06-28_18:37:38-rados:singleton-nomsgr-wip-msgr21-fix-reuse-rebuildci-distro-basic-smithi/
https://pulpito.ceph.com/dis-2020-06-29_08:50:54-rados:singleton-nomsgr-wip-msgr21-fix-reuse-rebuildci-distro-basic-smithi/

-s rados --filter-out cephadm --subset 1/3333:
https://pulpito.ceph.com/dis-2020-06-28_18:43:20-rados-wip-msgr21-fix-reuse-rebuildci-distro-basic-smithi/

**Comment by idryomov** [comment]
@dillaman This is not an up/downgrade issue, or at least I don't think so.  The scenario here is two peers connecting to each other at the same time.  To handle this race, one of the peers determines the winning connection and closes the losing one.  The issue is that the winning connection can be behind in terms of the phase of the connection (i.e. how far it got), so some state must be carried over from the losing connection.  If one of the peers is restarted, both connections would get closed.

**Comment by neha-ojha** [comment]
> -s rados/singleton-nomsgr --filter 'all/health-warnings rados' -N 20 / 200:
> https://pulpito.ceph.com/dis-2020-06-28_18:37:38-rados:singleton-nomsgr-wip-msgr21-fix-reuse-rebuildci-distro-basic-smithi/
> https://pulpito.ceph.com/dis-2020-06-29_08:50:54-rados:singleton-nomsgr-wip-msgr21-fix-reuse-rebuildci-distro-basic-smithi/
> 
> -s rados --filter-out cephadm --subset 1/3333:
> https://pulpito.ceph.com/dis-2020-06-28_18:43:20-rados-wip-msgr21-fix-reuse-rebuildci-distro-basic-smithi/

@idryomov I don't see any related failures in rados. I think we also want to run this through rgw, fs and upgrade suites, fyi @cbodley @batrick

**Comment by neha-ojha** [comment]
> > -s rados/singleton-nomsgr --filter 'all/health-warnings rados' -N 20 / 200:
> > https://pulpito.ceph.com/dis-2020-06-28_18:37:38-rados:singleton-nomsgr-wip-msgr21-fix-reuse-rebuildci-distro-basic-smithi/
> > https://pulpito.ceph.com/dis-2020-06-29_08:50:54-rados:singleton-nomsgr-wip-msgr21-fix-reuse-rebuildci-distro-basic-smithi/
> > -s rados --filter-out cephadm --subset 1/3333:
> > https://pulpito.ceph.com/dis-2020-06-28_18:43:20-rados-wip-msgr21-fix-reuse-rebuildci-distro-basic-smithi/
> 
> @idryomov I don't see any related failures in rados. I think we also want to run this through rgw, fs and upgrade suites, fyi @cbodley @batrick

no related failures in upgrade: https://pulpito.ceph.com/nojha-2020-06-29_20:23:12-upgrade-wip-msgr21-fix-reuse-rebuildci-distro-basic-smithi/

**Comment by sebastian-philipp** [comment]
https://pulpito.ceph.com/swagner-2020-07-01_09:26:21-rados:cephadm-wip-swagner-testing-2020-07-01-0956-distro-basic-smithi/

**Comment by sebastian-philipp** [comment]
got a strange SELinux error: https://tracker.ceph.com/issues/46300 in my run. any idea if this is related to this PR?

**Comment by idryomov** [comment]
> got a strange SELinux error https://tracker.ceph.com/issues/46300 in my run testing this PR. any idea if this is related to this PR?

```
type=AVC msg=audit(1593601294.109:4683): avc:  denied  { module_request } for
pid=18957 comm="ksmtuned" kmod="binfmt-464c" scontext=system_u:system_r:ksmtuned_t:s0
tcontext=system_u:system_r:kernel_t:s0 tclass=system permissive=1
```

From a cursory look, it appears that ksmtuned triggered auto-load of binfmt-464c kernel module, which would suggest an unrecognized ELF binary or some weird interaction between ksmtuned and the rest of the system?    Definitely not related.

**Pull request merged**
