### PR TITLE
osd: wakeup all threads of shard rather than one thread.

### PR DESCRIPTION
**Pull request by majianpeng**
## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by majianpeng** [comment]
In one OSD ceph cluster(NVME as backend, cluster has 256 PG),  i tested 4K RR/RW.


IOPS(K) | QD | threads_per_shard_ssd=2(default) | threads_per_shard_ssd=1
-- | -- | -- | --
4K RR | 1 | 33.7 | 31.9
4K RR | 4 | 54.3 | 81.8
4K RR | 16 | 54.9 | 101
4K RR | 32 | 55.9 | 104
4K W | 1 | 20.9 | 19
4K W | 4 | 50.1 | 47.2
4K W | 16 | 57.9 | 56.1
4K W | 32 | 58.8 | 56.7

For 4K RW, performance only little drop. But for 4K RR, it only 53% on QD=16/32.
And in theory, thread_per_shard=1 only mean we add more object OSDShard.

**Comment by majianpeng** [comment]
@markhpc  please review.

**Comment by markhpc** [comment]
Hrm, I seem to recall there are some circumstances where we want a second thread per shard.  I don't remember why off the top of my head though. I've done some tests like this as well in the past but don't recall seeing that kind of drop in the 2 threads case.  Let me see if I can find any of the data I collected.  Instead of dropping the number of threads per shard we might want to dig into the threading code here and fix the real issue.

**Comment by majianpeng** [comment]
@markhpc   i asked why need two thead perf shard to sage. He said in teuthology some test cases need this.

**Comment by majianpeng** [comment]
@markhpc . I set up a 4 NVME(P4510  1TB) ceph cluster (all in one: fio and osd in the same machine, pg=900). 

runtime=1800s | QD | 8_2(IOPS(k)) | 16_1(IOPS(K))
-- | -- | -- | --
  | 4 | 137 | 134
  | 16 | 165 | 251
  | 32 | 165 | 271
  | 64 | 166 | 271

**Comment by XinzeChi** [comment]
> @markhpc . I set up a 4 NVME(P4510 1TB) ceph cluster (all in one: fio and osd in the same machine, pg=900).
> 
> runtime=1800s	QD	8_2(IOPS(k))	16_1(IOPS(K))
>  	4	137	134
>  	16	165	251
>  	32	165	271
>  	64	166	271

@majianpeng randread or readwrite?

**Comment by majianpeng** [comment]
randread

**Comment by majianpeng** [comment]
In one storage node(4NVME) and one client env(10G): for 4K Randread(runtime=1800):

QD | 8_2(IOPS(k)) | 16_1(IOPS(K))
-- | -- | --
4 | 143 | 135
16 | 186 | 264
32 | 191 | 263
64 | 189 | 265

It also show thread_per_shard_ssd=1 is better than thread_per_shard=2.

**Comment by markhpc** [comment]
We spoke about this a bit at the last performance meeting.  I think one of the issues is how much parallelism we get during recovery operations.  I think that's what I remembered when I last looked into this.

@majianpeng could I trouble you to run a wallclock profiler and see if we are stuck in lock contention in the 8x2 case?

**Comment by majianpeng** [comment]
@markhpc . 
a)I'll do wallclock profile. 
b) My tests is compare shard=8/thread_per_shard=2 vs shard=16/thread_per_shard=1 which make have the same threads. 
c) As for mixed read/write, i didn't test, but from my firstly result, it indeed hurt  4k RW.  what's the reason?

**Comment by majianpeng** [comment]
@markhpc .  For wallclock, it can't download: https://github.com/pathscale/libunwind.git.

**Comment by majianpeng** [comment]
@markhpc   I found the root reason: this because commit 28cad5b80af(introduced by myself).
I used the following patch:
diff --git a/src/osd/OSD.cc b/src/osd/OSD.cc
index 133ebb984b..23e918a73c 100644
--- a/src/osd/OSD.cc
+++ b/src/osd/OSD.cc
@@ -10728,7 +10728,7 @@ void OSD::ShardedOpWQ::_enqueue(OpSchedulerItem&& item) {
 
   if (empty) {
     std::lock_guard l{sdata->sdata_wait_lock};
-    sdata->sdata_cond.notify_one();
+    sdata->sdata_cond.notify_all();
   }
 }

w/ 4NVME, runtime=1800s.

QD | 8_2(IOPS(k)) | 16_1(IOPS(K)) | 8_2(apply patch)
-- | -- | -- | --
32 | 191 | 263 | 263.5

The results looks no different. I guess, commit 28cad5b80af only wake up one thread if two thread in wait state.

**Comment by majianpeng** [comment]
@markhpc  please review.

**Comment by majianpeng** [comment]
@markhpc . ping

**Comment by markhpc** [comment]
@majianpeng I will try to look later today, thanks!

**Comment by tchaikov** [comment]
- http://pulpito.ceph.com/kchai-2020-04-30_13:24:45-rados-wip-kefu-testing-2020-04-30-1835-distro-basic-smithi/
- http://pulpito.ceph.com/kchai-2020-05-01_04:25:09-rados-wip-kefu-testing-2020-04-30-1912-distro-basic-smithi/

**Pull request merged**
