### PR TITLE
pacific: isa-l: incorporate fix for aarch64 text relocation

### PR DESCRIPTION
**Pull request by rosinL**
Fixes: https://tracker.ceph.com/issues/48681
Fixes: https://tracker.ceph.com/issues/50384

Signed-off-by: luo rixin <luorixin@huawei.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by rosinL** [comment]
@rzarzynski  this a backport pr to pacific, to fix ceph-mon init failed on aarch64, please help to review.

**Comment by rosinL** [comment]
@rzarzynski this a backport pr to pacific, to fix ceph-mon init failed on aarch64, please help to review.

**Comment by rosinL** [comment]
@rzarzynski this a backport pr to pacific, to fix ceph-mon init failed on aarch64, please help to review.

**Comment by rzarzynski** [comment]
@rosinL: between `806b55ee578efd8158962b90121a4568eb1ecb66` and `bee5180a1517f8b5e70b02fcd66790c623536c5d` there is a lot of unrelated commits, which – as this is for `pacific` – makes a bit nervous. I'm not saying _no_ but I want to know alternatives. What do you think about bringing the fix on top of `806b55ee578efd8158962b90121a4568eb1ecb66`? We already have `ceph/isa-l.git` fork.

**Comment by rosinL** [comment]
@rzarzynski: `ceph/isa-l.git` is just forked from `intel/isa-l.git`, 
> bringing the fix on top of 806b55ee578efd8158962b90121a4568eb1ecb66

It is ok for this case.  But, if the upstream `intel/isa-l.git`  have fixed some bugs or fulfilled some features or optimizations we need, we need to cherry pick all of this and get a huge amount of work.
So, I think it is a better choice that keep `ceph/isa-l` just following the upstream

**Comment by rosinL** [comment]
@rzarzynski Hi, it has been suspended for a long time.  If we just cherry pick `bee5180a1517f8b5e70b02fcd66790c623536c5d ` to `806b55ee578efd8158962b90121a4568eb1ecb66`, would you help to create a new branch (for pacific only) base  from https://github.com/ceph/isa-l/tree/806b55ee578efd8158962b90121a4568eb1ecb66, and I will do the left work. Thank you.

**Comment by k0ste** [comment]
Closed #53463 in favor to this PR

**Comment by ljflores** [comment]
@rosinL @rzarzynski @k0ste If this is a must for 16.2.15, please add it to https://github.com/ceph/ceph/milestone/17 since Pacific is going EOL.

**Comment by rzarzynski** [comment]
I'm happy to resurrect this backport but under assumption of taking only pin-pointed changes -- extra features, optimizations etc. seems too much for an old, stable release.

**Comment by rosinL** [comment]
For pin-pointed changes, we need another isl-a branch to patch the fix. Would you  create the isl-a branch, or is there other options? @rzarzynski

**Comment by rosinL** [comment]
OK, I will update the pr after you create the branch

**Comment by rzarzynski** [comment]
@rosinL: at the moment created the `pacific` branch in my **fork** –  https://github.com/rzarzynski/isa-l/tree/pacific. Let's use this as the starting point.
In the meantime I will look for somebody with `w+` rights to the `ceph/isa-l.git` repo.

**Comment by rzarzynski** [comment]
@rosinL: https://github.com/ceph/isa-l/tree/pacific is ready :-).

**Comment by rosinL** [comment]
@rzarzynski  please merge the PR https://github.com/ceph/isa-l/pull/3, after the merge, I will upadte this PR to `ceph/isa-l:pacific `branch

**Comment by rzarzynski** [comment]
`9c242d38321847acf04e9ccfc394ebf4506b239e` is merged.

**Review by rzarzynski — APPROVED** [review]
Looks good!

```
commit 4b36e413c9ac28b4757b297779470693b699aeae (origin/pacific)
Merge: 806b55e 9c242d3
Author: Radoslaw Zarzynski <radoslaw.zarzynski@gmail.com>
Date:   Thu Jan 11 10:31:23 2024 +0100

    Merge pull request #3 from rosinL/pacific
    
    erasure_code: Fix text relocation on aarch64
    
    Reviewed-by: Radoslaw Zarzynski <rzarzyns@redhat.com>

commit 9c242d38321847acf04e9ccfc394ebf4506b239e
Author: luo rixin <luorixin@huawei.com>
Date:   Fri Jan 8 16:16:02 2021 +0800

    erasure_code: Fix text relocation on aarch64
    
    Here is the bug report on ceph. https://tracker.ceph.com/issues/48681
    
    Change-Id: Ie1c60a71f28c1a169c8899a621be9bb455f5e244
    Signed-off-by: luo rixin <luorixin@huawei.com>
    (cherry picked from commit bee5180a1517f8b5e70b02fcd66790c623536c5d)

commit 806b55ee578efd8158962b90121a4568eb1ecb66 (HEAD -> pacific, rzarzynski/pacific, rzarzynski/master)
Author: Greg Tucker <greg.b.tucker@intel.com>
Date:   Wed Feb 26 17:40:37 2020 -0700

    build: Bump revision to 2.29
    
    Change-Id: I78cfa77864f3fd77c3b63199bc18fd1782fe3dc2
    Signed-off-by: Greg Tucker <greg.b.tucker@intel.com>
```

**Review by pereman2 — APPROVED** [review]
Rados approved: https://tracker.ceph.com/projects/rados/wiki/MAIN#httpstrellocomcYriUU51p1929-wip-yuri2-testing-2024-01-18-1314-pacific-old-wip-yuri2-testing-2024-01-12-1128-pacific

**Pull request merged**
