### PR TITLE
common/options: correct the description of rgw_enable_lc_threads option

### PR DESCRIPTION
**Pull request by excellentkf**
Signed-off-by: excellentkf <likefei@cmss.chinamobile.com>

### CODE REVIEW

**Comment by excellentkf** [comment]
hi @oritwas , @mattbenjamin do you mind take a review? thanks

**Comment by excellentkf** [comment]
hi,@cbodley do you mind take a review? thanks

**Comment by cbodley** [comment]
jenkins test make check

**Comment by excellentkf** [comment]
jenkins test this please

**Pull request merged**
