### PR TITLE
nautilus: mgr/dashboard: Use serial RGW Admin OPS API calls

### PR DESCRIPTION
**Pull request by callithea**
backport tracker: https://tracker.ceph.com/issues/40056

---

backport of https://github.com/ceph/ceph/pull/28223
parent tracker: https://tracker.ceph.com/issues/40015

this backport was staged using ceph-backport.sh version 15.0.0.6950
find the latest version at https://github.com/ceph/ceph/blob/master/src/script/ceph-backport.sh

### CODE REVIEW

**Comment by callithea** [comment]
jenkins test dashboard

**Comment by callithea** [comment]
- QA run [WIP]: http://pulpito.ceph.com/laura-2019-12-04_13:59:42-rados:dashboard-wip-laura-testing-dashboard-nautilus-batch-5-distro-basic-smithi/

**Comment by smithfarm** [comment]
@callithea If it passed your tests, can it be merged? Or does it need to be included in a full rados run?

**Comment by callithea** [comment]
> @callithea If it passed your tests, can it be merged? Or does it need to be included in a full rados run?

@smithfarm It can be merged - just thought another approval would be nice.

**Pull request merged**
