### PR TITLE
rgw: Swift API: response for PUT on /container does not contain the mandatory Content-Length header when FCGI is used

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/12039

### CODE REVIEW

**Comment by dachary** [comment]
DNM because the bot did not pass yet.
@smithfarm could you please rebase & repush to trigger the bot ?

**Comment by smithfarm** [comment]
@dachary This has passed first round of integration testing as detailed in http://tracker.ceph.com/issues/11644

**Comment by dachary** [comment]
For the record the integration round in question is http://tracker.ceph.com/issues/11644#teuthology-run-commitb2aaddd3a06ac13c46df659e1f2b3119f5675802-firefly-backports-july-2015

**Comment by smithfarm** [comment]
@yehudasa This commit has passed integration tests (see the previous comment by @dachary) -- is it OK to merge? I'm asking you because you merged the master commit that this is a backport of: https://github.com/ceph/ceph/pull/3863

**Comment by yehudasa** [comment]
@smithfarm yes

**Pull request merged**
