### PR TITLE
DNM: hammer: SIGABRT in TrackedOp::dump() via dump_ops_in_flight()

### PR DESCRIPTION
**Pull request by dzafman**
Backport of fix for http://tracker.ceph.com/issues/8885

Pulled in related changes to minimize conflicts.

### CODE REVIEW

**Comment by dzafman** [comment]
I don't think the failures relate to this change:

http://pulpito.ceph.com/dzafman-2016-07-12_16:03:42-rados:thrash-wip-zafman-testing-hammer---basic-smithi/

**Comment by smithfarm** [comment]
@dzafman Is it possible that f0b87552285c77ce3de2e82ecd17ffae8e19b196 is triggering http://tracker.ceph.com/issues/13281 ?

And will cherry-picking a965378e3af1e36b1d741dfe7cfd339816366b49 into this PR fix it?

**Comment by smithfarm** [comment]
Here is the hammer-backports job where the bug was triggered: http://pulpito.ceph.com/smithfarm-2016-07-20_00:22:41-rados-hammer-backports---basic-smithi/324356/

**Comment by dzafman** [comment]
@smithfarm I added a cherry-pick (https://github.com/ceph/ceph/pull/10255/commits/a9df1560389b8f8f6fc2226e76d83f061cb29d7d) of https://github.com/ceph/ceph/commit/a965378e3af1e36b1d741dfe7cfd339816366b49 to this branch since it is needed with https://github.com/ceph/ceph/commit/f0b87552285c77ce3de2e82ecd17ffae8e19b196.

**Comment by smithfarm** [comment]
Thanks, I'll schedule another rados run.

**Comment by dzafman** [comment]
The only issue I'm seeing with this backport is in testing runs using https://github.com/ceph/ceph-qa-suite/pull/1081.  These are the tests that pass in master that test this change.  The crashes are python core dumps which I don't know why that would happen.

**Comment by smithfarm** [comment]
@liewegas This PR is in the latest round of hammer-backports integration tests, which passed a rados run (the only failures are a valgrind false positive that has since been fixed by https://github.com/ceph/teuthology/pull/915 and http://tracker.ceph.com/issues/15139 which is an infrastructure issue with two of the tests) - for details, see: http://tracker.ceph.com/issues/15895#note-18

Note that this run did not include https://github.com/ceph/ceph-qa-suite/pull/1081

Do you think this PR is OK to merge?

**Comment by dzafman** [comment]
@liewegas  It is unfortunate that there is an issue with ceph/ceph-qa-suite#1081 which is the testing for this backport.  For some reason in hammer a core is generated when trying to injectargs to osd.*.

**Comment by smithfarm** [comment]
@liewegas This is another hammer PR we wanted you to look at.

**Comment by liewegas** [comment]
I defer to @dzafman on this one as he's familiar with the changes.  It might be useful to do a diff with master on the files to see what things haven't been backported (since we know that master is stable).

**Comment by smithfarm** [comment]
marked DNM pending release of 0.94.8, then I will remove the DNM

**Comment by dzafman** [comment]
Testing passes now using ceph/ceph-qa-suite#1081

http://pulpito.ceph.com/dzafman-2016-08-17_18:37:51-rados:thrash-wip-zafman-testing-hammer-distro-basic-smithi/

**Comment by dzafman** [comment]
Retest after change to ceph-qa-suite change passed.  One failure was in Ansible.

http://pulpito.ceph.com/dzafman-2016-08-18_22:32:36-rados:thrash-wip-zafman-testing-hammer-distro-basic-smithi/

Ready for review and merge.

**Comment by athanatos** [comment]
This is a lot of changes, does this failure happen often and is there an easy workaround?

**Comment by athanatos** [comment]
Also, we're holding off on this until after the next point release, right?

**Comment by smithfarm** [comment]
@athanatos That was my plan. As of today, 0.94.8 has all but passed QE validation.

**Comment by smithfarm** [comment]
@dzafman Can you rebase this?

**Comment by dzafman** [comment]
@smithfarm Rebased.   I didn't build it but we'll see if it passes Jenkins.

**Comment by smithfarm** [comment]
Note, needs to be tested with ceph/ceph-qa-suite#1081

**Comment by smithfarm** [comment]
@dzafman Do you see anything in this PR that might cause the following new bug that is currently plaguing the hammer-backports integration testing?

* http://tracker.ceph.com/issues/17955

**Comment by dzafman** [comment]
@smithfarm Both failures are an out of space condition.  This is feature not a bug!  Was out of space handling one of the backports?

 client.4423.objecter  FULL, paused modify 0x2d05890 tid 0

**Comment by smithfarm** [comment]
@dzafman Yes: https://github.com/ceph/ceph/pull/10871

We can move discussion to the tracker.

**Comment by smithfarm** [comment]
@dzafman @athanatos This backport passed a rados suite at http://tracker.ceph.com/issues/17151#note-7 (note that it was run with `--suite-branch wip-16225`) with failures that I believe have been addressed (except for http://tracker.ceph.com/issues/15139 which is caused by the build system no longer providing dumpling-era packages).

I have rebuilt the integration branch to include the two fixes and scheduled a new run at http://tracker.ceph.com/issues/17151#note-14

Do you think it's OK to merge provided the second run succeeds?

**Comment by dzafman** [comment]
@dzafman @athanatos Seem ok to me.

**Comment by smithfarm** [comment]
A 5x run to assert that a failure from https://github.com/ceph/ceph/pull/10255#issuecomment-241138225 is not reproducible:

`./virtualenv/bin/teuthology-suite --priority 101 --suite rados --suite-branch wip-16225 --email ncutler@suse.cz --ceph hammer-backports --machine-type smithi --filter 'thrash/{0-size-min-size-overrides/2-size-2-min-size.yaml 1-pg-log-overrides/short_pg_log.yaml clusters/{fixed-2.yaml openstack.yaml} fs/xfs.yaml msgr-failures/few.yaml thrashers/mapgap.yaml workloads/cache.yaml}' -N 5`

**running** http://pulpito.front.sepia.ceph.com:80/smithfarm-2016-11-20_23:24:11-rados-hammer-backports---basic-smithi/

**Comment by smithfarm** [comment]
Second rados run succeeded: http://tracker.ceph.com/issues/17151#note-14

**Comment by smithfarm** [comment]
Third rados run here: http://pulpito.front.sepia.ceph.com/smithfarm-2016-11-21_11:52:41-rados-hammer-backports---basic-smithi/

**Comment by athanatos** [comment]
Are we sure this is the minimal set of changes that fixes the bug and that the resulting files in hammer pretty much match what is well tested in master? @dzafman

**Comment by dzafman** [comment]
@athanatos These changes bring TrackedOp.{cc,h} in line with master.  
Some of these changes are to fix bugs seen when testing with ceph/ceph-qa-suite#1081

But I did notice that the cherry-pick of d9616d6795acfd65a52a8b7e60f22ad0d9668ffa may have caused http://tracker.ceph.com/issues/14804 which was fixed by ceph/ceph#7690 .

**Comment by dzafman** [comment]
@athanatos I removed the cherry-pick of d9616d6795acfd65a52a8b7e60f22ad0d9668ffa.  If we want it to have that code we need to cherry-pick these in this order:

d9616d6795acfd65a52a8b7e60f22ad0d9668ffa
b2bfd6cc0ba697414a0abca1bb8a1074abb08993
52c04b81a699b0d193cd19263ca5f02fcef46664

**Comment by athanatos** [comment]
@dzafman For the moment, go ahead and make this PR the simplest possible fix for the SIGABRT problem.

**Comment by dzafman** [comment]
@athanatos I removed the 1 commit that was reversed by b2bfd6cc.  Hammer already has a corresponding implementation to that master commit.

**Comment by dzafman** [comment]
retest this please

**Comment by dzafman** [comment]
@smithfarm @athanatos I added DNM to pull request description.  Because I'm going to exclude the feature that you can turn op tracking on/off dynamically, if it can be done cleanly.

**Comment by smithfarm** [comment]
@dzafman OK. That gives me an excuse to do some runs with plain `--suite-branch hammer` instead of `--suite-branch wip-16225`, which is probably a good idea anyway.

**Comment by dzafman** [comment]
@smithfarm I have a new pull request ceph/ceph#12121 (a stripped down version of this one) that requires testing with --suite-branch wip-16225-min    Sam may have me removing another commit from that one.

**Comment by dzafman** [comment]
Superseded by ceph/ceph#12121

**Pull request closed without merging**
