### PR TITLE
luminous: mds: add "drop cache" command

### PR DESCRIPTION
**Pull request by vshankar**
http://tracker.ceph.com/issues/36281
http://tracker.ceph.com/issues/36695

### CODE REVIEW

**Comment by batrick** [comment]
Yes, this needs backported.

**Comment by vshankar** [comment]
latest update includes backport of https://github.com/ceph/ceph/pull/24555 minus commit 4e87709256a662de1fa48db6429404c234a21454

**Comment by smithfarm** [comment]
Jenkins re-test this please

**Comment by ukernel** [comment]
LGTM

**Comment by smithfarm** [comment]
@ukernel Did you mean to approve the PR?

**Comment by yuriw** [comment]
[wip-yuri5-testing-2018-12-12-1653-luminous](https://trello.com/c/oXzdX0yM/487-wip-yuri5-testing-2018-12-12-1653-luminous)

**Comment by yuriw** [comment]
[wip-yuri4-testing-2018-12-19-1658-luminous](https://trello.com/c/XKKZA4vr/494-wip-yuri4-testing-2018-12-19-1658-luminous)

**Comment by vshankar** [comment]
Reviewed-by: Venky Shankar vshankar@redhat.com

**Pull request merged**
