### PR TITLE
pacific: common: fix FTBFS due to dout & need_dynamic on GCC-12

### PR DESCRIPTION
**Pull request by pponnuvel**
backport tracker: https://tracker.ceph.com/issues/54276

---

backport of https://github.com/ceph/ceph/pull/44670
parent tracker: https://tracker.ceph.com/issues/53896

this backport was staged using ceph-backport.sh version 16.0.0.6848
find the latest version at https://github.com/ceph/ceph/blob/master/src/script/ceph-backport.sh

### CODE REVIEW

**Comment by pponnuvel** [comment]
jenkins retest this please

**Comment by pponnuvel** [comment]
jenkins retest this please

**Comment by pponnuvel** [comment]
jenkins retest this please

**Review by rzarzynski — APPROVED** [review]

**Comment by pponnuvel** [comment]
Superseded by https://github.com/ceph/ceph/pull/45373

**Pull request closed without merging**
