### PR TITLE
cmake: use python2 by default

### PR DESCRIPTION
**Pull request by tchaikov**
and s/PYTHON_EXECUTABLE/Python_EXECUTABLE/

it's a regression introduced by 5e2bd7fc4dd6d137cf67336d568da5b0d568efca

Signed-off-by: Kefu Chai <kchai@redhat.com>

- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by alimaredia** [comment]
@tchaikov in `FindCython.cmake` the module is running `${Python${PYTHON_VERSION}_EXECUTABLE} -m cython --version` which ends up as `/usr/bin/python3.8 -m cython --version` on Fedora 30. 

This command exits with status 1 with the error of `Could not find cython3: /usr/bin/python3.8: No module named cython`. 

On Fedora 30, running `/usr/bin/python3 -m cython --version` is successful. So is running `usr/bin/python3.7 -m cython --version`. 

Is there any way to get rid of the `.8` in `3.8`, or just the decimal version, and make it part of this commit?

**Comment by tchaikov** [comment]
@alimaredia instead of reusing the existing commit, i added another commit to address your issue. i don't think we should remove the minor version from the command line for detecting the existence of cython. couple reasons:

1. if user specifies version 3.y.z, we should adhere to the specified version instead of try to be smart and use "python3" , which could point to "python3.w.x". this is against user's will.
2. if we find the greatest python3 installed in the system is python3.y.z, and we decide to use it. but it turns out cython is available for python3, so we use python3 for detecting cython. but we will fail later. because we will use python3.y.z to cythonize the `.pyx` source code and for building the python bindings, and we will hit the wall again.

i think, the right route is to allow user to specify the *exact* version he/she wants. in your case, as python3.7 is the "official" python version, you should use something like

```
cmake -DWITH_PYTHON3=3.7 -DWITH_PYTHON2=OFF -DMGR_PYTHON_VERSION=3.7 ..
```

after applying this fix.

**Comment by tchaikov** [comment]
retest this please.

**Comment by tchaikov** [comment]
retest this please.

**Comment by alimaredia** [comment]
@tchaikov I ran into the problem when I was running `do_cmake.sh`. Can you think of any changes that need to be made to that script to make sure the problem I'm hitting doesn't occur repeatedly?

**Comment by tchaikov** [comment]
@alimaredia my last comment was only one step away from the fix. and here comes the fix.

**Comment by tchaikov** [comment]
@cbodley @alimaredia could you please help re-review this PR?

**Comment by tchaikov** [comment]
https://shaman.ceph.com/builds/ceph/wip-kefu-testing-2019-07-24-1127/e9d1acfdfe361999b065d06cc272839034bbb09c/

**Comment by liewegas** [comment]
With this change, my build/bin/ceph has ``#/usr/bin/python`` instead of ``#/usr/bin/python3``, which fails with
```
*** DEVELOPER MODE: setting PATH, PYTHONPATH and LD_LIBRARY_PATH ***
Traceback (most recent call last):
  File "bin/ceph", line 140, in <module>
    import rados
ImportError: No module named rados
```
on my fedora 29 box.  But do_cmake.sh should still be asking cmake for py3...

**Comment by alimaredia** [comment]
@liewegas the issue I mentioned happens on Fedora 30 with the most recent version of python enabled. Maybe it would be better to default back to python3 and anyone with 3.8 on their distro will just have to use python2?

**Comment by liewegas** [comment]
Does that mean going from fc29 -> fc30 will fix my problem?  I'm happy to do that if it'll fix this

**Comment by tchaikov** [comment]
@liewegas have you tried to remove `CMakeCache.txt` under your build directory? and are you using `do_cmake.sh`?

upgrading to f30 won't help, i think. see 

https://github.com/ceph/ceph/blob/f7376c0754ec700a0063bf14d0293cf31ad77798/do_cmake.sh#L14-L15

**Comment by liewegas** [comment]
I deleted ``build`` entirely and re-ran ``do_cmake.sh``

**Comment by tchaikov** [comment]
@liewegas i am not able to reproduce your issue

```
kefu@00f2db5bea52:/var/ssd/ceph-fedora-29-kefu/build$ cat /etc/redhat-release
Fedora release 29 (Twenty Nine)
kefu@00f2db5bea52:/var/ssd/ceph-fedora-29-kefu$ ./do_cmake.sh
..
+ case "$ID" in
+ '[' 29 -ge 29 ']'
+ PYBUILD=3.7
+ [[ 3.7 =~ ^3(\..*)?$ ]]
+ ARGS=' -DWITH_PYTHON2=OFF -DWITH_PYTHON3=3.7 -DMGR_PYTHON_VERSION=3.7'
...
-- Found PythonInterp: /usr/bin/python (found version "2.7.15")
...
kefu@00f2db5bea52:/var/ssd/ceph-fedora-29-kefu$ head build/bin/ceph -n1
#!/usr/bin/python3.7
```

**Pull request merged**
