### PR TITLE
luminous: ceph_volume_client: remove ceph mds calls in favor of ceph fs calls

### PR DESCRIPTION
**Pull request by jan--f**
https://tracker.ceph.com/issues/40182

### CODE REVIEW

**Comment by batrick** [comment]
Yes, let's do cherry-picks like a regular backport:

https://tracker.ceph.com/issues/40182#note-3

**Comment by smithfarm** [comment]
Echoing @batrick 's sentiment - I, too, would prefer cherry-picks if feasible.

Of course, cherry-picking should not be indiscriminate (commits that do wholesale refactoring need careful consideration, for example) but if there is a reasonably discrete set of commits in master that addresses the issue(s), that's typically the way to go.

**Comment by smithfarm** [comment]
(I continue to try to get backporters and backport reviewers to adhere to a policy of requiring that all non-cherry-picked commits to stable branches contain a sentence in the commit message explaining why the commit is not cherry-picked from master.)

**Comment by jan--f** [comment]
ping @batrick @smithfarm

**Comment by yuriw** [comment]
[wip-yuri4-testing-2019-06-13-1541-luminous](https://trello.com/c/1kU7OZL0/640-wip-yuri4-testing-2019-06-13-1541-luminous)

**Pull request merged**
