### PR TITLE
os/bluestore: fix a few memory utilization leaks and wasters

### PR DESCRIPTION
**Pull request by liewegas**

### CODE REVIEW

**Comment by ifed01** [comment]
retest this please

**Comment by ifed01** [comment]
LGTM

**Comment by markhpc** [comment]
I tested this last night.  It dramatically improves things, though I haven't yet convinced myself that we've found everything yet.  Assuming this is passing objectstore tests I'd merge it ASAP and we can keep working on any remaining stuff.

**Comment by ifed01** [comment]
+1 to Mark, I saw dignificant performance and memory use improvements as well.

**Pull request merged**
