### PR TITLE
rgw: retry CORS put/delete operations on ECANCELLED

### PR DESCRIPTION
**Pull request by adamemerson**
I must have missed these two.

### CODE REVIEW

**Comment by adamemerson** [comment]
@cbodley Give this a review if you would, it's just the fix for CORS mentioned before.

**Comment by adamemerson** [comment]
jenkins rebuild docs, please

**Comment by adamemerson** [comment]
jekins, retest docs please.

**Comment by mattbenjamin** [comment]
http://pulpito.ceph.com/mbenjamin-2017-12-21_23:57:52-rgw-wip-rgw-cors-19601---basic-smithi/

**Pull request merged**
