### PR TITLE
build/ops: add uuid-runtime to debian/control

### PR DESCRIPTION
**Pull request by dachary**
uuid-runtime was incorrectly removed by
62bfc7a1ab1587e81ed3bff0ddfbb1aa69d1c299, restore it.

http://tracker.ceph.com/issues/12734 Fixes: #12734

Signed-off-by: Loic Dachary <ldachary@redhat.com>

### CODE REVIEW

**Comment by dachary** [comment]
manually verifying this is enough to get macke check to work again on ubuntu 14.04

**Comment by cbodley** [comment]
this looks correct, yeah. boost doesn't provide an alternative to uuidgen

Reviewed-by: Casey Bodley <cbodley@redhat.com>

**Comment by tchaikov** [comment]
:+1:

**Comment by liewegas** [comment]
:+1:

**Comment by dachary** [comment]
make check passed on Ubuntu 14.04

**Pull request merged**
