### PR TITLE
pybind/rbd: fix metadata functions error handling

### PR DESCRIPTION
**Pull request by trociny**
Fixes: http://tracker.ceph.com/issues/22306
Signed-off-by: Mykola Golub <to.my.trociny@gmail.com>

### CODE REVIEW

**Comment by trociny** [comment]
I looks a bit unfortunate that for non-existent key we throw 'ImageNotFound' exception. I would prefer a new one like 'NotFound'.

@dillaman Do you think it makes sense to improve this?

**Comment by socketpair** [comment]
1. I consider standard KeyError.
2. It will be perfect if you change api to standard dict-like api, i.e. (pseudocode)
```
stub = object()
def metadata_get(key, default=stub):
    ret = rbd_metadata_get(self.image, _key, value, &size)
    if ret == 0:
        return value
    if ret != ENOENT:
        raise SomeError(err=ret)
    if default is stub:
        raise KeyError
    return default
```

**Comment by dillaman** [comment]
@trociny Yeah, ```ImageNotFound``` is definitely not an ideal exception.

**Comment by trociny** [comment]
I have updated metadata_get/remove to raise KeyError on ENOENT, as @socketpair suggested. Not sure about adding `default=stub` param to `metadata_get` method. @dillaman do you like this idea?

**Comment by trociny** [comment]
@dillaman, @socketpair updated

**Comment by trociny** [comment]
@dillaman
> I wouldn't worry about adding a default optional

Ah, sorry, I might have misunderstood you.

**Comment by trociny** [comment]
@dillaman reverted back to the approved version

**Pull request merged**
