### PR TITLE
mimic: mgr/dashboard: Fix various RGW issues

### PR DESCRIPTION
**Pull request by votdev**
* Fix handling of tenanted users
* Better exception handling if RGW backend is not available
* RGW user/bucket "max. size" should be hidden when "user/bucket quota" is not enabled
* Fix bug in loading user quota.

Fixes: https://tracker.ceph.com/issues/38800

partial manual backport of 61995970916cb11f66c3800bcf869755f8dae32c
partial manual backport of e6f130d47023c24f8a9c742f145abd34d7320cd8
partial manual backport of 945e790cab57785e1bc2dbf708d5ddafec618aba
partial manual backport of a98bca6a2f161140f78f34cfa5f5ebec07af2f82
partial manual backport of 975736aba546adb09ce4f38a1ae061621f7240cd

This fix is not cherry-picked because the code was completely re-worked for Nautilus (codebase is too far apart).

Signed-off-by: Volker Theile <vtheile@suse.com>

- [x] References tracker ticket
- [ ] Updates documentation if necessary
- [x] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by smithfarm** [comment]
@votdev Can you edit the commit message (using `git commit --amend`) so it explains why this fix cannot be implemented as a cherry-pick from `master` or `nautilus`?

One option is to:

1. find out which commit fixed the issue in master
2. append to commit message: `partial manual backport of $SHA1`
3. preferably also explain why the master commit cannot be cherry-picked in its entirety

**Comment by votdev** [comment]
@tspmelo This is the fix for the errors you were facing yesterday while testing an RGW issue in Mimic.

**Comment by tspmelo** [comment]
Found a problem, but I'm not sure if caused by this PR or if another commit should be cherry-picked to fix this problem.
The RGW user form is ignoring the value of the quota.

1. Edit a RGW user
2. Pick an user quota size
3. Save user
4. Edit the same user
5. It will show `Unlimited size` active

**Comment by votdev** [comment]
> Found a problem, but I'm not sure if caused by this PR or if another commit should be cherry-picked to fix this problem.
> The RGW user form is ignoring the value of the quota.
> 
>     1. Edit a RGW user
> 
>     2. Pick an user quota size
> 
>     3. Save user
> 
>     4. Edit the same user
> 
>     5. It will show `Unlimited size` active

Fixed by partial manual backport of 975736aba546adb09ce4f38a1ae061621f7240cd.

**Comment by yuriw** [comment]
[wip-yuri4-testing-2019-07-23-1633-mimic](https://trello.com/c/G8TDc8rz/672-wip-yuri4-testing-2019-07-23-1633-mimic)

**Pull request merged**
