### PR TITLE
doc/cephfs: clarify the 'not production ready' warning

### PR DESCRIPTION
**Pull request by liewegas**
Continue to run into people who see this and run away (occasionally to
less robust solutions) without understanding why.

Signed-off-by: Sage Weil <sage@redhat.com>

### CODE REVIEW

**Comment by jcsp** [comment]
I'm happy with this but let's give @gregsfortytwo a chance to comment before merging

**Comment by gregsfortytwo** [comment]
Mmm, that might be a little too weak. Do we have anything about not using multiple MDSes in the docs?

**Comment by jcsp** [comment]
I was thinking about adding a "cephfs for early adopters" landing page that outlines the single-mds/no-snapshots config, with prominent notes on how to report bugs, good idea?

**Comment by gregsfortytwo** [comment]
Well I'd certainly like something that emphasizes the ways in which it is
more likely to work. ;)
We cover the no-snapshot thing pretty well now since it's disabled, but
nothing limits you to 1 MDS. Perhaps we should put that limit in as well
(before we release Hammer?).

**Comment by gregsfortytwo** [comment]
@jcsp did you want to write about that?

**Comment by jcsp** [comment]
@gregsfortytwo I've put something up here: https://github.com/ceph/ceph/pull/3699

**Pull request closed without merging**
