### PR TITLE
build/ops: debian package not generating in a minimal pbuilder environment

### PR DESCRIPTION
**Pull request by darkweaver87**
Signed-off-by: Rémi BUISSON remi.buisson@cdiscount.com

In a minimal pbuilder environment the 10.2.2 version is not building because of missing package unzip.

Rémi

### CODE REVIEW

**Comment by smithfarm** [comment]
This just adds `unzip` to the list of build dependencies. LGTM.

`Reviewed-by: Nathan Cutler <ncutler@suse.com>`

**Comment by smithfarm** [comment]
pushed to gitbuilders as `wip-Cdiscount`

@darkweaver87 Thanks for contributing to Ceph!

Tip: before making your change, create a work-in-progress ("wip") branch by doing:

```
git checkout -b wip-foo-bar-blatz
```

And create your PR from that wip branch. You *can* create a PR from your local master branch, as you did here, but that limits you to having just one open PR at a time.

**Comment by smithfarm** [comment]
passes gitbuilders!

**Comment by smithfarm** [comment]
reminder to self: remove `wip-Cdiscount` branch when this is merged

**Comment by tchaikov** [comment]
@darkweaver87  in which step does pbuilder fail? and could you prefix the title of your commit message with "debian/control: " instead?

**Comment by ktdreyer** [comment]
Agreed with @tchaikov it would be nice to know the exact cause of the failure here.

**Comment by darkweaver87** [comment]
Hello,

Sorry for late answer. The building process was failing while trying to link with librados which was not generated because of missing unzip.
The error message wasn't very clear and I had to diff a working environment with a failing one.
Do you need the full log file ?

Rémi

**Comment by tchaikov** [comment]
@darkweaver87 i am not sure how unzip could be help linker to link librados. yes, could you pastebin or upload the full log file somehwere? thanks!

**Comment by dachary** [comment]
jenkins test this please (jenkins hung)

**Comment by tchaikov** [comment]
we are using pbuilder in our CI infrastructure, see https://github.com/ceph/ceph-build/blob/master/ceph-dev-build/build/setup_pbuilder, so i think this problem should have been addressed. please reopen it if you think otherwise.

**Pull request closed without merging**
