### PR TITLE
nautilus: os/bluestore: call fault_range prior to looking for blob to reuse

### PR DESCRIPTION
**Pull request by ifed01**
https://tracker.ceph.com/issues/39256

### CODE REVIEW

**Comment by smithfarm** [comment]
```
[ 97%] Building CXX object src/rgw/CMakeFiles/radosgw.dir/rgw_main.cc.o
/usr/bin/ld: warning: libboost_context.so.1.67.0, needed by //opt/ceph/lib/x86_64-linux-gnu/libboost_coroutine.so.1.67.0, not found (try using -rpath or -rpath-link)
//opt/ceph/lib/x86_64-linux-gnu/libboost_coroutine.so.1.67.0: undefined reference to `jump_fcontext'
//opt/ceph/lib/x86_64-linux-gnu/libboost_coroutine.so.1.67.0: undefined reference to `make_fcontext'
collect2: error: ld returned 1 exit status

Link Error: RGW library not found
```

@cbodley @tchaikov I wonder if this build failure is due to http://tracker.ceph.com/issues/39981 ?

**Comment by smithfarm** [comment]
jenkins re-test this please

**Comment by ifed01** [comment]
jenkins retest this please

**Comment by ifed01** [comment]
jenkins retest this please

**Comment by yuriw** [comment]
[wip-yuri4-testing-2019-05-30-2109-nautilus](https://trello.com/c/gp7jSQKF/626-wip-yuri4-testing-2019-05-30-2109-nautilus)

**Pull request merged**
