### PR TITLE
luminous: mon,osd: limit MOSDMap messages by size as well as map count

### PR DESCRIPTION
**Pull request by tchaikov**
http://tracker.ceph.com/issues/38276

### CODE REVIEW

**Comment by tchaikov** [comment]
cc @pdvian

**Comment by smithfarm** [comment]
@tchaikov This is a backport of https://github.com/ceph/ceph/pull/26340 ?

In https://tracker.ceph.com/issues/38040#note-3 Sage wrote that

* https://github.com/ceph/ceph/pull/26413
* https://github.com/ceph/ceph/pull/26448

are needed as well?

**Comment by tchaikov** [comment]
> @tchaikov This is a backport of #26340 ?
> 

yes.

> In https://tracker.ceph.com/issues/38040#note-3 Sage wrote that
> 
> * #26413
> * #26448
> 
> are needed as well?

i don't think so. the two PRs above do not address http://tracker.ceph.com/issues/38040 .

if we want to backport the fix of http://tracker.ceph.com/issues/38282 and http://tracker.ceph.com/issues/38330, we might want to update the corresponding tickets accordingly.

**Comment by tchaikov** [comment]
@smithfarm let's defer to Sage to verify this.

**Comment by smithfarm** [comment]
@tchaikov Since Sage marked those other tickets "Resolved" and listed all three PRs in issue http://tracker.ceph.com/issues/38040 when he marked it for backport, to me that's a pretty strong indication that he intended all three issues to be backported at once in a single PR. 

IMO the best course of action would be to cherry-pick the remaining commits into this PR, but of course @liewegas has the final word here.

**Comment by liewegas** [comment]
Yeah, we can test+merge this separately, but we should still backport the other two PRs too and not mark the original issue as fully resolved/backported until then

**Comment by yuriw** [comment]
[wip-yuri2-testing-2019-06-24-2019-luminous](https://trello.com/c/Uz0JspUX/651-wip-yuri2-testing-2019-06-24-2019-luminous)

**Comment by smithfarm** [comment]
@tchaikov I'm trying to do the mimic backport of this fix, and I noticed in the first commit message of this PR:

```
Conflicts:
	src/common/config_values.h: the changes in this file is applied
to src/common/config.h instead.
```

but I don't see any changes to `src/common/config.h` anywhere here?

**Pull request merged**
