### PR TITLE
luminous: mds: don't delay processing completed requests in replay queue

### PR DESCRIPTION
**Pull request by pdvian**
http://tracker.ceph.com/issues/22237

### CODE REVIEW

**Comment by pdvian** [comment]
@ukernel @smithfarm

**Comment by ukernel** [comment]
should wait until https://github.com/ceph/ceph/pull/18871 get merged

**Comment by smithfarm** [comment]
@pdvian This is ready to be re-cherry-picked.

**Comment by pdvian** [comment]
@smithfarm ack. will re-cherry-pick this PR.

**Comment by pdvian** [comment]
@ukernel @smithfarm @tchaikov kindly review this PR.

**Comment by yuriw** [comment]
[wip-yuri-testing-2018-02-04-1734-luminous](https://trello.com/c/SeYBrPx3/255-wip-yuri-testing-2018-02-04-1734-luminous)

**Comment by yuriw** [comment]
[wip-yuri3-testing-2018-02-05-2032-luminous](https://trello.com/c/j0BpLYdX/257-wip-yuri3-testing-2018-02-05-2032-luminous)

**Pull request merged**
