### PR TITLE
mimic: doc: enable Read the Docs

### PR DESCRIPTION
**Pull request by tchaikov**
## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by tchaikov** [comment]
https://docs.ceph.com/en/wip-mimic-doc/

**Comment by zdover23** [comment]
jenkins test make check

**Comment by zdover23** [comment]
From the log:

```
The following tests FAILED:
	  7 - run-tox-ceph-disk (Failed)
	  8 - run-tox-ceph-detect-init (Failed)

```

That's a bummer.

**Comment by tchaikov** [comment]
the test failures are not related to this change. and mimic is EOL already.

**Review by neha-ojha — APPROVED** [review]

**Pull request merged**
