### PR TITLE
ceph.spec.in: build with gcc-toolset-11

### PR DESCRIPTION
**Pull request by tchaikov**
as a followup of 610c0d51110e139237a412f9c07d11378d503bee

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [x] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by tchaikov** [comment]
being tested at https://shaman.ceph.com/builds/ceph/wip-pr-47427-kefu-3/3af67a3284a38271cc6e484fe20d9a2306029c05/

**Comment by tchaikov** [comment]
jenkins test make check

**Comment by tchaikov** [comment]
being built at https://shaman.ceph.com/builds/ceph/wip-pr-47427-kefu-13/

**Review by cbodley — APPROVED** [review]

**Comment by djgalloway** [comment]
```
	install -d debian/.debhelper/generated/python3-cephfs-dbg
dh_install: warning: Cannot find (any matches for) "usr/lib/python3*/site-packages/ceph_argparse.py" (tried in ., debian/tmp)

dh_install: warning: python3-ceph-argparse missing files: usr/lib/python3*/site-packages/ceph_argparse.py
dh_install: warning: Cannot find (any matches for) "usr/lib/python3*/site-packages/ceph_daemon.py" (tried in ., debian/tmp)

dh_install: warning: python3-ceph-argparse missing files: usr/lib/python3*/site-packages/ceph_daemon.py
dh_install: error: missing files, aborting
	install -d debian/.debhelper/generated/python3-ceph-argparse
	install -d debian/.debhelper/generated/python3-ceph-common
	install -d debian/.debhelper/generated/libcephfs-java
	install -d debian/.debhelper/generated/libcephfs-jni
	install -d debian/.debhelper/generated/rados-objclass-dev
	install -d debian/.debhelper/generated/cephfs-shell
	install -d debian/.debhelper/generated/cephfs-top
	install -d debian/.debhelper/generated/ceph-grafana-dashboards
	install -d debian/.debhelper/generated/ceph-prometheus-alerts
make: *** [debian/rules:61: binary] Error 25
dpkg-buildpackage: error: fakeroot debian/rules binary subprocess returned exit status 2
```

This looks familiar...

**Comment by tchaikov** [comment]
@djgalloway should be fixed by #47459 .

**Comment by djgalloway** [comment]
I see `RPM: error: line 157: Unknown tag: %enable_devtoolset11` on CentOS9.

https://jenkins.ceph.com/job/ceph-dev-build/ARCH=x86_64,AVAILABLE_ARCH=x86_64,AVAILABLE_DIST=centos9,DIST=centos9,MACHINE_SIZE=gigantic/50185/console

**Pull request merged**
