### PR TITLE
doc: fix email

### PR DESCRIPTION
**Pull request by epuertat**
## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [x] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [x] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Review by jmolmo — APPROVED** [review]

**Review by batrick — APPROVED** [review]

**Comment by epuertat** [comment]
Thank you, folks!

**Comment by zdover23** [comment]
https://github.com/ceph/ceph/pull/60233 - Squid backport
https://github.com/ceph/ceph/pull/60234 - Reef backport
https://github.com/ceph/ceph/pull/60235 - Quincy backport

**Comment by epuertat** [comment]
> #60233 - Squid backport #60234 - Reef backport #60235 - Quincy backport

Do we have to backport these things? 🤔 wouldn't it make sense to have version-less docs for topics like that are not attached to Ceph releases?

**Comment by anthonyeleven** [comment]
I think that would be a management nightmare.  Zac has a script for docs backports and I've upgraded my rubber stamp to the turbo model ;)

**Comment by epuertat** [comment]
Don't you think that some docs should probably lie outside the `ceph/ceph` repo, as their scope goes beyond a single repo (Governance, Ceph Foundation, Security, Code of Conduct, ...) and affect the whole Ceph ecosystem (e.g.: `ceph-nvmeof`, `ceph-csi`, `go-ceph`, ...).

I don't see much benefit from having them versioned by release, but it forces us to keep them in sync with `main`...

**Comment by zdover23** [comment]
> Don't you think that some docs should probably lie outside the `ceph/ceph` repo, as their scope goes beyond a single repo (Governance, Ceph Foundation, Security, Code of Conduct, ...) and affect the whole Ceph ecosystem (e.g.: `ceph-nvmeof`, `ceph-csi`, `go-ceph`, ...).
> 
> I don't see much benefit from having them versioned by release, but it forces us to keep them in sync with `main`...

@epuertat, I'm willing to discuss that, but the system that we have right now is the one that I'm familiar with and I don't want to learn a new system until the items that are already on my agenda are taken care of. Every three months, I read every pull request that has been made on the Ceph project as a part of the preparation of Ceph Quarterly. During that time, I make sure to backport anything that fell through the cracks. So far, this has been a workable system and I don't think there's any need to fix it.

Eventually, we can have a repository somewhere else that contains information that is not tied to a particular release. But that raises questions that I don't know the answers to. For example, would that information be served on docs.ceph.com? If so, how would it be integrated with the current workflow, which pulls from ceph/ceph to docs.ceph.com? I do know how to make sure that content appears on docs.ceph.com in each of the release branches in the system that we have in place now. I want to stick with it.

If you're going to be at Cephalocon, I would be willing to discuss this in detail with you. I suspect that the particulars of this conversation would make it better suited to an in-person meeting.

**Comment by epuertat** [comment]
@zdover23 unfortunately I won't be at Cephalocon. Budget constraints :/

I didn't want to add more overhead to you. On the contrary: I was just wondering if generating 4 copies (original + 3 backports) of the same info is efficient, and if something would work better here. 

I just checked how other FOSS projects are doing this. Most have their core/technical docs versioned together with their code, but everything else (Beginners Guide, Dev Guide, Governance, Community-related), as separate versionless repos (e.g.: https://github.com/kubernetes/community, https://github.com/python/steering-council, https://github.com/python/peps, https://github.com/python/devguide, https://github.com/jenkins-infra/jenkins.io/) or Wikis (e.g.: https://wiki.python.org/moin/, https://wiki.mozilla.org/Governance) and published to separate websites (peps.python.org, devguide.python.org).

Based on that, I'd have core/technical Ceph docs at docs.ceph.com and everything that's not release dependant (Governance, Dev Processes, etc) at separate repos (e.g.: https://github.com/ceph/community, https://github.com/ceph/dev_guide) and websites (community.ceph.com, dev_guide.ceph.com), or they could be even Wikis, if we find that the PR + CI process puts a lot of overhead.

**Comment by epuertat** [comment]
@zdover23 the proposal @idryomov suggested today is good enough. If we can have part of the docs outside of the version-dependant index, that solves it.

For anything more collaborative, for example in the Dashboard we're using [Github wiki to collect a list of best practices](https://github.com/ceph/ceph/wiki/Teams-%E2%80%90-Ceph-Dashboard-%E2%80%90-Best-Practices/).

**Pull request merged**
