### PR TITLE
reef: os/bluestore: report min_alloc_size through "ceph osd metadata"

### PR DESCRIPTION
**Pull request by ifed01**
backport of https://github.com/ceph/ceph/pull/49958

backport tracker: https://tracker.ceph.com/issues/59011
parent tracker: https://tracker.ceph.com/issues/58421

Signed-off-by: Igor Fedotov [igor.fedotov@croit.io](mailto:igor.fedotov@croit.io)

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [x] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Review by anthonyeleven — APPROVED** [review]
Lgtm, be sure to do the checklist ;)

**Review by anthonyeleven — APPROVED** [review]

**Comment by ifed01** [comment]
> Lgtm, be sure to do the checklist ;)

which one?

**Comment by anthonyeleven** [comment]
> > Lgtm, be sure to do the checklist ;)
> 
> which one?

The one in the PR description that's causing the commit check to fail.

**Comment by ifed01** [comment]
> > > Lgtm, be sure to do the checklist ;)
> > 
> > 
> > which one?
> 
> The one in the PR description that's causing the commit check to fail.

ah.. OK, done.

**Comment by ljflores** [comment]
jenkins test api

**Comment by ljflores** [comment]
Rados approved: https://tracker.ceph.com/projects/rados/wiki/REEF#httpstrellocomcVwWMUkId1794-wip-yuri11-testing-2023-06-27-0812-reef

**Comment by anthonyeleven** [comment]
yay! 🥇

**Pull request merged**
