### PR TITLE
qa/tasks/ceph_deploy: gatherkeys before mgr deploy

### PR DESCRIPTION
**Pull request by liewegas**
Otherwise we may be missing the bootstrap-mgr key.

Signed-off-by: Sage Weil <sage@redhat.com>

### CODE REVIEW

**Comment by liewegas** [comment]
http://pulpito.ceph.com/sage-2017-08-24_13:53:33-ceph-deploy-master-distro-basic-vps/
better!

**Comment by vasukulkarni** [comment]
thanks @liewegas

**Comment by vasukulkarni** [comment]
jenkins do not test: qa task change

**Comment by vasukulkarni** [comment]
jenkins do not test

**Comment by vasukulkarni** [comment]
@alfredodeza "jenkins do not test" does't seem to work!

**Comment by vasukulkarni** [comment]
jenkins test this please

**Comment by alfredodeza** [comment]
@vasukulkarni I thought this needed to go in the subject or title of the PR

**Pull request merged**
