### PR TITLE
tests: no need for python-flask at build time

### PR DESCRIPTION
**Pull request by dachary**
http://tracker.ceph.com/issues/10845 Refs: #10845

Signed-off-by: Loic Dachary <ldachary@redhat.com>

### CODE REVIEW

**Comment by ktdreyer** [comment]
Looking at the commit where python-flask was added to the RPM's BuildRequires, 6a45b8ed041514816d09b2808d2d390eadbd0dd9 , it sounds like this was to require all "the dependencies" in order to have `make check` succeed. However, the RPM build process itself does not run `make check`, or even have a `%check` section. I must be missing something.

@dachary , is this change here because `make check` itself does not require python-flask? And the thing that I'm missing is that other tooling (like `install-deps.sh`) installs the BuildRequires and runs `make check`, independent of the RPM?

The ceph.spec file in [Fedora downstream](http://pkgs.fedoraproject.org/cgit/ceph.git) never had `Buildrequires: python-flask`, so there's certainly no build dependency outside of `make check`.

**Comment by dachary** [comment]
@ktdreyer Andrew Bartlett copied over a number of dependencies just to make sure he was not missing anything instead of adding packages in reaction to a failed dependency when running the tests. The test in question is ceph-disk and I'm positive it does not need python-flask. 

The general idea is that make check can rely on BuildRequires to install what it needs. That has a few important advantages a) install-deps.sh is all someone needs to build + make check, b) gitbuilders can rely on install-deps.sh if they need to make check (the tarbal gitbuilder should although they currently don't and there is a ticket open for that).

**Comment by dachary** [comment]
@ktdreyer this change is because make check does not require python-flask indeed and that it is not available on some RPM based distribution which makes it a problem not worth solving.

**Comment by ktdreyer** [comment]
Thanks @dachary - I was curious why it was added in the first place. LGTM, will merge in a moment.

**Comment by ktdreyer** [comment]
Looks like this needs a trivial rebase in order to fast-forward merge onto the tip of the hammer branch (currently 890f5b6bd43bc32983b21baba60ee5e6e3b6e491)

**Comment by dachary** [comment]
@ktdreyer rebased & repushed

**Comment by dachary** [comment]
@ktdreyer are you using the github web interface to merge ? Or command line ?

**Comment by ktdreyer** [comment]
I used the command-line to merge it, so the commit shows up as "kdreyer@redhat.com"

**Comment by ktdreyer** [comment]
I see I copied & pasted the wrong ID number in my merge commit (https://github.com/ceph/ceph/commit/1914b90a8a47ba36cc12cac7825f62557f67bba7), so it's pointing at the wrong PR. Whoops. One day I'll get this right, I swear.

I will resist the urge to force push anything :)

**Comment by dachary** [comment]
@ktdreyer :-) only a bot guarding the gates could consistently do the right thing.

**Comment by ktdreyer** [comment]
@dachary - yep, that is what we need.

**Pull request merged**
