### PR TITLE
quincy: cmake: add submodule for Apache Arrow at v6.0.1

### PR DESCRIPTION
**Pull request by cbodley**
quincy backport of https://github.com/ceph/ceph/pull/44696

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by cbodley** [comment]
jenkins test make check

**Comment by cbodley** [comment]
jenkins teste api

**Comment by cbodley** [comment]
jenkins test api

**Comment by cbodley** [comment]
jenkins test make check

**Comment by cbodley** [comment]
jenkins test api

**Comment by cbodley** [comment]
jenkins test windows

**Comment by cbodley** [comment]
note that i opened https://github.com/ceph/ceph/pull/45696 to address a regression with local cmake builds. but all of our CI builds are doing the right thing, so that won't be a blocker for quincy or the merge of this PR. you can follow discussion in the "rgw: arrow packaging status for quincy" thread on the dev list

**Review by idryomov — APPROVED** [review]

**Review by yuriw — APPROVED** [review]

**Pull request merged**
