### PR TITLE
os: fix return code if unable to sync

### PR DESCRIPTION
**Pull request by xiexingguo**
Shall return a negative error code instead.

Fixes: #14187
Signed-off-by: xie xingguo <xie.xingguo@zte.com.cn>

### CODE REVIEW

**Comment by xiexingguo** [comment]
@dzafman Dear david, I would appreciate it if you come back and have a look at this. Thanks.

**Comment by liewegas** [comment]
please rebase?

**Comment by xiexingguo** [comment]
@liewegas Rebased and some more small fixes, please review.

**Comment by liewegas** [comment]
lgtm!

**Pull request merged**
