### PR TITLE
rgw: some fix for es sync

### PR DESCRIPTION
**Pull request by tianshan**

### CODE REVIEW

**Comment by tianshan** [comment]
@yehudasa  done, and replaced another two compare with starts_with

**Comment by yuriw** [comment]
see

--- pr 21622 --- pulling https://github.com/tianshan/ceph.git branch misc_es_fix
remote: Counting objects: 10, done.
remote: Total 10 (delta 8), reused 8 (delta 8), pack-reused 2
Unpacking objects: 100% (10/10), done.
From https://github.com/tianshan/ceph
 * branch            misc_es_fix -> FETCH_HEAD
Auto-merging src/rgw/rgw_sync_module_es.cc
CONFLICT (file/directory): There is a directory with name src/dmclock in 5e3abb30417e3e9a07736380fbf66292d3c7f9a9. Adding src/dmclock as src/dmclock~HEAD
Adding qa/suites/rbd/mirror/cluster
Adding qa/suites/rbd/mirror/base
Adding qa/suites/ceph-deploy/basic/distros/ubuntu_latest.yaml
Adding qa/suites/ceph-deploy/basic/distros/centos_latest.yaml
Adding qa/suites/ceph-deploy/basic/distros/.qa
Automatic merge failed; fix conflicts and then commit the result.
Traceback (most recent call last):
  File "/home/yuriw/wip_master/src/script/build-integration-branch", line 62, in <module>
    assert not r
AssertionError

**Comment by tianshan** [comment]
@yuriw  rebased to latest master

**Comment by mattbenjamin** [comment]
unstale me my man

**Comment by yuriw** [comment]
[wip-yuri4-testing-2018-11-15-2120](https://trello.com/c/rED6z2kY/473-wip-yuri4-testing-2018-11-15-2120)

**Comment by yuriw** [comment]
@tianshan pls rebase

**Comment by tianshan** [comment]
@yuriw done

**Comment by cbodley** [comment]
http://pulpito.ceph.com/cbodley-2018-12-06_14:35:32-rgw-wip-cbodley-testing-distro-basic-smithi

**Pull request merged**
