### PR TITLE
mgr/volumes/fs/operations/versions: fix various flake8 issues

### PR DESCRIPTION
**Pull request by Crossbears**
Fixes: https://tracker.ceph.com/issues/51402
Signed-off-by: Jingya Su <jingyasu@my.yorku.ca>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by Crossbears** [comment]
I run this on my terminal and shows as below:
zoey@zoey-VirtualBox:~/ceph$ flake8 --ignore=W503 src/pybind/mgr/volumes/fs/operations/versions/subvolume_base.py
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flake8/checker.py", line 426, in run_check
    self.processor.keyword_arguments_for(
  File "/usr/lib/python3/dist-packages/flake8/processor.py", line 241, in keyword_arguments_for
    arguments[param] = getattr(self, param)
AttributeError: 'FileProcessor' object has no attribute 'indent_size'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/flake8", line 11, in <module>
    load_entry_point('flake8==3.7.9', 'console_scripts', 'flake8')()
  File "/usr/lib/python3/dist-packages/flake8/main/cli.py", line 18, in main
    app.run(argv)
  File "/usr/lib/python3/dist-packages/flake8/main/application.py", line 393, in run
    self._run(argv)
  File "/usr/lib/python3/dist-packages/flake8/main/application.py", line 381, in _run
    self.run_checks()
  File "/usr/lib/python3/dist-packages/flake8/main/application.py", line 300, in run_checks
    self.file_checker_manager.run()
  File "/usr/lib/python3/dist-packages/flake8/checker.py", line 331, in run
    self.run_serial()
  File "/usr/lib/python3/dist-packages/flake8/checker.py", line 315, in run_serial
    checker.run_checks()
  File "/usr/lib/python3/dist-packages/flake8/checker.py", line 597, in run_checks
    self.process_tokens()
  File "/usr/lib/python3/dist-packages/flake8/checker.py", line 587, in process_tokens
    self.handle_newline(token_type)
  File "/usr/lib/python3/dist-packages/flake8/checker.py", line 614, in handle_newline
    self.run_logical_checks()
  File "/usr/lib/python3/dist-packages/flake8/checker.py", line 521, in run_logical_checks
    results = self.run_check(plugin, logical_line=logical_line) or ()
  File "/usr/lib/python3/dist-packages/flake8/checker.py", line 431, in run_check
    raise exceptions.PluginRequestedUnknownParameters(
flake8.exceptions.PluginRequestedUnknownParameters: "pycodestyle" requested unknown parameters causing 'FileProcessor' object has no attribute 'indent_size'

**Comment by Crossbears** [comment]
zoey@zoey-VirtualBox:~$ sudo apt-get remove  flake8
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer required:
  chromium-codecs-ffmpeg-extra gstreamer1.0-vaapi
  libgstreamer-plugins-bad1.0-0 libllvm11 libva-wayland2 pyflakes pyflakes3
  python-pkg-resources python-pyflakes python3-catkin python3-flake8
  python3-mccabe python3-pycodestyle python3-pyflakes
Use 'sudo apt autoremove' to remove them.
The following packages will be REMOVED:
  flake8
0 upgraded, 0 newly installed, 1 to remove and 66 not upgraded.
After this operation, 34.8 kB disk space will be freed.
Do you want to continue? [Y/n] y
(Reading database ... 283708 files and directories currently installed.)
Removing flake8 (3.7.9-2) ...
Processing triggers for man-db (2.9.1-1) ...
zoey@zoey-VirtualBox:~$ sudo apt-get remove --auto-remove flake8
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package 'flake8' is not installed, so not removed
The following packages will be REMOVED:
  chromium-codecs-ffmpeg-extra gstreamer1.0-vaapi
  libgstreamer-plugins-bad1.0-0 libllvm11 libva-wayland2 pyflakes pyflakes3
  python-pkg-resources python-pyflakes python3-catkin python3-flake8
  python3-mccabe python3-pycodestyle python3-pyflakes
0 upgraded, 0 newly installed, 14 to remove and 66 not upgraded.
After this operation, 87.2 MB disk space will be freed.
Do you want to continue? [Y/n] y
(Reading database ... 283701 files and directories currently installed.)
Removing chromium-codecs-ffmpeg-extra (1:85.0.4183.83-0ubuntu0.20.04.2) ...
Removing gstreamer1.0-vaapi:amd64 (1.16.2-2) ...
Removing libgstreamer-plugins-bad1.0-0:amd64 (1.16.2-2.1ubuntu1) ...
Removing libllvm11:amd64 (1:11.0.0-2~ubuntu20.04.1) ...
Removing libva-wayland2:amd64 (2.7.0-2) ...
Removing pyflakes (2.1.1-2) ...
Removing pyflakes3 (2.1.1-2) ...
Removing python-pyflakes (2.1.1-2) ...
Removing python-pkg-resources (44.0.0-2) ...
Removing python3-catkin (0.8.0-1ubuntu2) ...
Removing python3-flake8 (3.7.9-2) ...
Removing python3-mccabe (0.6.1-3) ...
Removing python3-pycodestyle (2.5.0-2) ...
Removing python3-pyflakes (2.1.1-2) ...
Processing triggers for man-db (2.9.1-1) ...
Processing triggers for libc-bin (2.31-0ubuntu9.2) ...
zoey@zoey-VirtualBox:~$ sudo apt-get purge flake8
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package 'flake8' is not installed, so not removed
0 upgraded, 0 newly installed, 0 to remove and 66 not upgraded.
zoey@zoey-VirtualBox:~$ sudo apt-get install flake8
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  pyflakes pyflakes3 python-pkg-resources python-pyflakes python3-flake8
  python3-mccabe python3-pycodestyle python3-pyflakes
Suggested packages:
  python-setuptools
The following NEW packages will be installed:
  flake8 pyflakes pyflakes3 python-pkg-resources python-pyflakes
  python3-flake8 python3-mccabe python3-pycodestyle python3-pyflakes
0 upgraded, 9 newly installed, 0 to remove and 66 not upgraded.
Need to get 336 kB of archives.
After this operation, 1,737 kB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 http://ca.archive.ubuntu.com/ubuntu focal/universe amd64 python3-mccabe all 0.6.1-3 [8,488 B]
Get:2 http://ca.archive.ubuntu.com/ubuntu focal/universe amd64 python3-pyflakes all 2.1.1-2 [48.6 kB]
Get:3 http://ca.archive.ubuntu.com/ubuntu focal/universe amd64 python3-pycodestyle all 2.5.0-2 [36.7 kB]
Get:4 http://ca.archive.ubuntu.com/ubuntu focal/universe amd64 python3-flake8 all 3.7.9-2 [51.8 kB]
Get:5 http://ca.archive.ubuntu.com/ubuntu focal/universe amd64 flake8 all 3.7.9-2 [6,016 B]
Get:6 http://ca.archive.ubuntu.com/ubuntu focal/universe amd64 python-pkg-resources all 44.0.0-2 [129 kB]
Get:7 http://ca.archive.ubuntu.com/ubuntu focal/universe amd64 python-pyflakes all 2.1.1-2 [48.5 kB]
Get:8 http://ca.archive.ubuntu.com/ubuntu focal/universe amd64 pyflakes all 2.1.1-2 [3,304 B]
Get:9 http://ca.archive.ubuntu.com/ubuntu focal/universe amd64 pyflakes3 all 2.1.1-2 [3,340 B]
Fetched 336 kB in 0s (722 kB/s) 
Selecting previously unselected package python3-mccabe.
(Reading database ... 283470 files and directories currently installed.)
Preparing to unpack .../0-python3-mccabe_0.6.1-3_all.deb ...
Unpacking python3-mccabe (0.6.1-3) ...
Selecting previously unselected package python3-pyflakes.
Preparing to unpack .../1-python3-pyflakes_2.1.1-2_all.deb ...
Unpacking python3-pyflakes (2.1.1-2) ...
Selecting previously unselected package python3-pycodestyle.
Preparing to unpack .../2-python3-pycodestyle_2.5.0-2_all.deb ...
Unpacking python3-pycodestyle (2.5.0-2) ...
Selecting previously unselected package python3-flake8.
Preparing to unpack .../3-python3-flake8_3.7.9-2_all.deb ...
Unpacking python3-flake8 (3.7.9-2) ...
Selecting previously unselected package flake8.
Preparing to unpack .../4-flake8_3.7.9-2_all.deb ...
Unpacking flake8 (3.7.9-2) ...
Selecting previously unselected package python-pkg-resources.
Preparing to unpack .../5-python-pkg-resources_44.0.0-2_all.deb ...
Unpacking python-pkg-resources (44.0.0-2) ...
Selecting previously unselected package python-pyflakes.
Preparing to unpack .../6-python-pyflakes_2.1.1-2_all.deb ...
Unpacking python-pyflakes (2.1.1-2) ...
Selecting previously unselected package pyflakes.
Preparing to unpack .../7-pyflakes_2.1.1-2_all.deb ...
Unpacking pyflakes (2.1.1-2) ...
Selecting previously unselected package pyflakes3.
Preparing to unpack .../8-pyflakes3_2.1.1-2_all.deb ...
Unpacking pyflakes3 (2.1.1-2) ...
Setting up python-pkg-resources (44.0.0-2) ...
Setting up python3-pyflakes (2.1.1-2) ...
Setting up python3-pycodestyle (2.5.0-2) ...
Setting up python3-mccabe (0.6.1-3) ...
Setting up python-pyflakes (2.1.1-2) ...
Setting up pyflakes3 (2.1.1-2) ...
Setting up pyflakes (2.1.1-2) ...
Setting up python3-flake8 (3.7.9-2) ...
Setting up flake8 (3.7.9-2) ...
Processing triggers for man-db (2.9.1-1) ...
zoey@zoey-VirtualBox:~$ cd ceph
zoey@zoey-VirtualBox:~/ceph$ flake8 --ignore=W503 src/pybind/mgr/volumes/fs/operations/versions/subvolume_base.py
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flake8/checker.py", line 426, in run_check
    self.processor.keyword_arguments_for(
  File "/usr/lib/python3/dist-packages/flake8/processor.py", line 241, in keyword_arguments_for
    arguments[param] = getattr(self, param)
AttributeError: 'FileProcessor' object has no attribute 'indent_size'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/flake8", line 11, in <module>
    load_entry_point('flake8==3.7.9', 'console_scripts', 'flake8')()
  File "/usr/lib/python3/dist-packages/flake8/main/cli.py", line 18, in main
    app.run(argv)
  File "/usr/lib/python3/dist-packages/flake8/main/application.py", line 393, in run
    self._run(argv)
  File "/usr/lib/python3/dist-packages/flake8/main/application.py", line 381, in _run
    self.run_checks()
  File "/usr/lib/python3/dist-packages/flake8/main/application.py", line 300, in run_checks
    self.file_checker_manager.run()
  File "/usr/lib/python3/dist-packages/flake8/checker.py", line 331, in run
    self.run_serial()
  File "/usr/lib/python3/dist-packages/flake8/checker.py", line 315, in run_serial
    checker.run_checks()
  File "/usr/lib/python3/dist-packages/flake8/checker.py", line 597, in run_checks
    self.process_tokens()
  File "/usr/lib/python3/dist-packages/flake8/checker.py", line 587, in process_tokens
    self.handle_newline(token_type)
  File "/usr/lib/python3/dist-packages/flake8/checker.py", line 614, in handle_newline
    self.run_logical_checks()
  File "/usr/lib/python3/dist-packages/flake8/checker.py", line 521, in run_logical_checks
    results = self.run_check(plugin, logical_line=logical_line) or ()
  File "/usr/lib/python3/dist-packages/flake8/checker.py", line 431, in run_check
    raise exceptions.PluginRequestedUnknownParameters(
flake8.exceptions.PluginRequestedUnknownParameters: "pycodestyle" requested unknown parameters causing 'FileProcessor' object has no attribute 'indent_size'
zoey@zoey-VirtualBox:~/ceph$ pycodestyle --version
2.7.0
zoey@zoey-VirtualBox:~/ceph$ pycodestyle hel[
hel[:1:1: E902 FileNotFoundError: [Errno 2] No such file or directory: 'hel['
zoey@zoey-VirtualBox:~/ceph$ pycodestyle help
help:1:1: E902 FileNotFoundError: [Errno 2] No such file or directory: 'help'
zoey@zoey-VirtualBox:~/ceph$ python-pycodestyle 2.6.0-3
python-pycodestyle: command not found
zoey@zoey-VirtualBox:~/ceph$ pip install 'pycodestyle<2.7.0,>=2.6.0'
Collecting pycodestyle<2.7.0,>=2.6.0
  Downloading pycodestyle-2.6.0-py2.py3-none-any.whl (41 kB)
     |████████████████████████████████| 41 kB 615 kB/s 
ERROR: autopep8 1.5.7 has requirement pycodestyle>=2.7.0, but you'll have pycodestyle 2.6.0 which is incompatible.
Installing collected packages: pycodestyle
  Attempting uninstall: pycodestyle
    Found existing installation: pycodestyle 2.7.0
    Uninstalling pycodestyle-2.7.0:
      Successfully uninstalled pycodestyle-2.7.0
Successfully installed pycodestyle-2.6.0
zoey@zoey-VirtualBox:~/ceph$ flake8 --ignore=W503 src/pybind/mgr/volumes/fs/operations/versions/subvolume_base.py
zoey@zoey-VirtualBox:~/ceph$ cd src/pybind/mgr/volumes/fs/operations/versions/
zoey@zoey-VirtualBox:~/ceph/src/pybind/mgr/volumes/fs/operations/versions$ flake8 --ignore=W503
./__init__.py:18:1: E302 expected 2 blank lines, found 1
./__init__.py:29:101: E501 line too long (104 > 100 characters)
./__init__.py:47:101: E501 line too long (103 > 100 characters)
./__init__.py:61:101: E501 line too long (147 > 100 characters)
./__init__.py:74:101: E501 line too long (116 > 100 characters)
./__init__.py:86:9: F841 local variable 'oe' is assigned to but never used
./__init__.py:98:101: E501 line too long (123 > 100 characters)
./__init__.py:102:101: E501 line too long (101 > 100 characters)
./__init__.py:105:101: E501 line too long (102 > 100 characters)
./__init__.py:108:1: E305 expected 2 blank lines after class or function definition, found 1
./op_sm.py:8:1: E302 expected 2 blank lines, found 1
./op_sm.py:21:1: E302 expected 2 blank lines, found 1
./op_sm.py:22:26: E261 at least two spaces before inline comment
./op_sm.py:46:21: E222 multiple spaces after operator
./op_sm.py:50:101: E501 line too long (114 > 100 characters)
./op_sm.py:64:101: E501 line too long (155 > 100 characters)
./op_sm.py:68:1: E305 expected 2 blank lines after class or function definition, found 1
./op_sm.py:72:48: E203 whitespace before ':'
./op_sm.py:76:52: E203 whitespace before ':'
./op_sm.py:81:48: E203 whitespace before ':'
./op_sm.py:85:51: E203 whitespace before ':'
./op_sm.py:89:53: E203 whitespace before ':'
./op_sm.py:93:51: E203 whitespace before ':'
./op_sm.py:97:53: E203 whitespace before ':'
./op_sm.py:101:50: E203 whitespace before ':'
./op_sm.py:105:52: E203 whitespace before ':'
./op_sm.py:109:52: E203 whitespace before ':'
./op_sm.py:113:52: E203 whitespace before ':'
./auth_metadata.py:192:101: E501 line too long (103 > 100 characters)
./subvolume_v1.py:20:101: E501 line too long (108 > 100 characters)
./subvolume_v1.py:31:1: E302 expected 2 blank lines, found 1
./subvolume_v1.py:38:101: E501 line too long (108 > 100 characters)
./subvolume_v1.py:42:101: E501 line too long (116 > 100 characters)
./subvolume_v1.py:43:101: E501 line too long (114 > 100 characters)
./subvolume_v1.py:56:101: E501 line too long (108 > 100 characters)
./subvolume_v1.py:57:9: F841 local variable 'me' is assigned to but never used
./subvolume_v1.py:62:101: E501 line too long (117 > 100 characters)
./subvolume_v1.py:66:101: E501 line too long (105 > 100 characters)
./subvolume_v1.py:70:9: F841 local variable 'e' is assigned to but never used
./subvolume_v1.py:91:9: F841 local variable 'oe' is assigned to but never used
./subvolume_v1.py:146:9: F841 local variable 'oe' is assigned to but never used
./subvolume_v1.py:167:101: E501 line too long (105 > 100 characters)
./subvolume_v1.py:207:101: E501 line too long (106 > 100 characters)
./subvolume_v1.py:214:101: E501 line too long (125 > 100 characters)
./subvolume_v1.py:219:101: E501 line too long (109 > 100 characters)
./subvolume_v1.py:233:101: E501 line too long (110 > 100 characters)
./subvolume_v1.py:236:101: E501 line too long (110 > 100 characters)
./subvolume_v1.py:237:101: E501 line too long (114 > 100 characters)
./subvolume_v1.py:345:101: E501 line too long (102 > 100 characters)
./subvolume_v1.py:348:32: E203 whitespace before ':'
./subvolume_v1.py:358:101: E501 line too long (116 > 100 characters)
./subvolume_v1.py:424:101: E501 line too long (103 > 100 characters)
./subvolume_v1.py:445:101: E501 line too long (103 > 100 characters)
./subvolume_v1.py:454:17: E126 continuation line over-indented for hanging indent
./subvolume_v1.py:459:101: E501 line too long (106 > 100 characters)
./subvolume_v1.py:461:17: E126 continuation line over-indented for hanging indent
./subvolume_v1.py:461:101: E501 line too long (101 > 100 characters)
./subvolume_v1.py:480:101: E501 line too long (102 > 100 characters)
./subvolume_v1.py:484:26: E128 continuation line under-indented for visual indent
./subvolume_v1.py:485:21: E122 continuation line missing indentation or outdented
./subvolume_v1.py:486:17: E122 continuation line missing indentation or outdented
./subvolume_v1.py:493:26: E128 continuation line under-indented for visual indent
./subvolume_v1.py:494:21: E122 continuation line missing indentation or outdented
./subvolume_v1.py:495:17: E122 continuation line missing indentation or outdented
./subvolume_v1.py:520:101: E501 line too long (104 > 100 characters)
./subvolume_v1.py:524:26: E128 continuation line under-indented for visual indent
./subvolume_v1.py:525:21: E122 continuation line missing indentation or outdented
./subvolume_v1.py:526:17: E122 continuation line missing indentation or outdented
./subvolume_v1.py:530:101: E501 line too long (103 > 100 characters)
./subvolume_v1.py:541:101: E501 line too long (103 > 100 characters)
./subvolume_v1.py:555:101: E501 line too long (103 > 100 characters)
./subvolume_v1.py:565:27: E126 continuation line over-indented for hanging indent
./subvolume_v1.py:565:101: E501 line too long (107 > 100 characters)
./subvolume_v1.py:579:23: E261 at least two spaces before inline comment
./subvolume_v1.py:620:101: E501 line too long (102 > 100 characters)
./subvolume_v1.py:633:23: E124 closing bracket does not match visual indentation
./subvolume_v1.py:640:27: E203 whitespace before ':'
./subvolume_v1.py:642:27: E203 whitespace before ':'
./subvolume_v1.py:652:9: F841 local variable 'me' is assigned to but never used
./subvolume_v1.py:658:101: E501 line too long (118 > 100 characters)
./subvolume_v1.py:661:20: E203 whitespace before ':'
./subvolume_v1.py:663:101: E501 line too long (102 > 100 characters)
./subvolume_v1.py:669:101: E501 line too long (117 > 100 characters)
./subvolume_v1.py:681:101: E501 line too long (137 > 100 characters)
./subvolume_v1.py:683:101: E501 line too long (108 > 100 characters)
./subvolume_v1.py:703:101: E501 line too long (108 > 100 characters)
./subvolume_v1.py:715:101: E501 line too long (102 > 100 characters)
./subvolume_v1.py:726:39: E231 missing whitespace after ':'
./subvolume_v1.py:726:65: E231 missing whitespace after ':'
./subvolume_v1.py:727:38: E231 missing whitespace after ':'
./metadata_manager.py:22:1: E302 expected 2 blank lines, found 1
./metadata_manager.py:25:25: E221 multiple spaces before operator
./metadata_manager.py:26:25: E221 multiple spaces before operator
./metadata_manager.py:27:26: E221 multiple spaces before operator
./metadata_manager.py:54:101: E501 line too long (113 > 100 characters)
./metadata_manager.py:95:85: E203 whitespace before ':'
./metadata_manager.py:96:85: E203 whitespace before ':'
./metadata_manager.py:97:85: E203 whitespace before ':'
./metadata_manager.py:98:85: E203 whitespace before ':'
./metadata_manager.py:99:13: E124 closing bracket does not match visual indentation
./metadata_manager.py:106:9: E722 do not use bare 'except'
./metadata_manager.py:111:101: E501 line too long (101 > 100 characters)
./metadata_manager.py:119:101: E501 line too long (101 > 100 characters)
./metadata_manager.py:124:101: E501 line too long (101 > 100 characters)
./metadata_manager.py:125:16: E231 missing whitespace after ','
./metadata_manager.py:133:101: E501 line too long (101 > 100 characters)
./metadata_manager.py:135:101: E501 line too long (110 > 100 characters)
./metadata_manager.py:143:101: E501 line too long (101 > 100 characters)
./subvolume_v2.py:13:1: F401 '..template.SubvolumeTemplate' imported but unused
./subvolume_v2.py:20:1: E302 expected 2 blank lines, found 1
./subvolume_v2.py:25:101: E501 line too long (110 > 100 characters)
./subvolume_v2.py:26:101: E501 line too long (103 > 100 characters)
./subvolume_v2.py:31:101: E501 line too long (117 > 100 characters)
./subvolume_v2.py:33:101: E501 line too long (119 > 100 characters)
./subvolume_v2.py:35:101: E501 line too long (118 > 100 characters)
./subvolume_v2.py:37:101: E501 line too long (120 > 100 characters)
./subvolume_v2.py:61:101: E501 line too long (122 > 100 characters)
./subvolume_v2.py:98:101: E501 line too long (104 > 100 characters)
./subvolume_v2.py:102:9: F841 local variable 'e' is assigned to but never used
./subvolume_v2.py:127:101: E501 line too long (108 > 100 characters)
./subvolume_v2.py:134:101: E501 line too long (102 > 100 characters)
./subvolume_v2.py:154:101: E501 line too long (107 > 100 characters)
./subvolume_v2.py:156:101: E501 line too long (107 > 100 characters)
./subvolume_v2.py:162:9: F841 local variable 'oe' is assigned to but never used
./subvolume_v2.py:192:101: E501 line too long (101 > 100 characters)
./subvolume_v2.py:210:9: F841 local variable 'oe' is assigned to but never used
./subvolume_v2.py:237:101: E501 line too long (109 > 100 characters)
./subvolume_v2.py:291:101: E501 line too long (106 > 100 characters)
./subvolume_v2.py:300:101: E501 line too long (125 > 100 characters)
./subvolume_v2.py:304:101: E501 line too long (109 > 100 characters)
./subvolume_v2.py:305:101: E501 line too long (121 > 100 characters)
./subvolume_v2.py:308:101: E501 line too long (109 > 100 characters)
./subvolume_v2.py:309:101: E501 line too long (109 > 100 characters)
./subvolume_v2.py:322:101: E501 line too long (110 > 100 characters)
./subvolume_v2.py:325:101: E501 line too long (110 > 100 characters)
./subvolume_v2.py:326:101: E501 line too long (114 > 100 characters)
./subvolume_v2.py:347:101: E501 line too long (101 > 100 characters)
./subvolume_v2.py:356:101: E501 line too long (112 > 100 characters)
./subvolume_v2.py:360:101: E501 line too long (123 > 100 characters)
./subvolume_v2.py:364:101: E501 line too long (105 > 100 characters)
./subvolume_v2.py:369:101: E501 line too long (128 > 100 characters)
./subvolume_v2.py:372:101: E501 line too long (101 > 100 characters)
./subvolume_v2.py:378:101: E501 line too long (121 > 100 characters)
./subvolume_v2.py:385:101: E501 line too long (149 > 100 characters)
./subvolume_v2.py:386:101: E501 line too long (133 > 100 characters)
6     E122 continuation line missing indentation or outdented
2     E124 closing bracket does not match visual indentation
3     E126 continuation line over-indented for hanging indent
3     E128 continuation line under-indented for visual indent
19    E203 whitespace before ':'
3     E221 multiple spaces before operator
1     E222 multiple spaces after operator
4     E231 missing whitespace after ','
2     E261 at least two spaces before inline comment
6     E302 expected 2 blank lines, found 1
2     E305 expected 2 blank lines after class or function definition, found 1
83    E501 line too long (104 > 100 characters)
1     E722 do not use bare 'except'
1     F401 '..template.SubvolumeTemplate' imported but unused
9     F841 local variable 'oe' is assigned to but never used
zoey@zoey-VirtualBox:~/ceph/src/pybind/mgr/volumes/fs/operations/versions$ flake8 --ignore=W503 subvolume_base.py
zoey@zoey-VirtualBox:~/ceph/src/pybind/mgr/volumes/fs/operations/versions$ flake8 --ignore=W503 /home/zoey/ceph/src/pybind/mgr/volumes/fs/operations/versions/subvolume_base.py
zoey@zoey-VirtualBox:~/ceph/src/pybind/mgr/volumes/fs/operations/versions$ flake8 --ignore=W503 /subvolume_base.py
zoey@zoey-VirtualBox:~/ceph/src/pybind/mgr/volumes/fs/operations/versions$ flake8 --ignore=W503 subvolume_v2.py
subvolume_v2.py:13:1: F401 '..template.SubvolumeTemplate' imported but unused
subvolume_v2.py:20:1: E302 expected 2 blank lines, found 1
subvolume_v2.py:25:101: E501 line too long (110 > 100 characters)
subvolume_v2.py:26:101: E501 line too long (103 > 100 characters)
subvolume_v2.py:31:101: E501 line too long (117 > 100 characters)
subvolume_v2.py:33:101: E501 line too long (119 > 100 characters)
subvolume_v2.py:35:101: E501 line too long (118 > 100 characters)
subvolume_v2.py:37:101: E501 line too long (120 > 100 characters)
subvolume_v2.py:61:101: E501 line too long (122 > 100 characters)
subvolume_v2.py:98:101: E501 line too long (104 > 100 characters)
subvolume_v2.py:102:9: F841 local variable 'e' is assigned to but never used
subvolume_v2.py:127:101: E501 line too long (108 > 100 characters)
subvolume_v2.py:134:101: E501 line too long (102 > 100 characters)
subvolume_v2.py:154:101: E501 line too long (107 > 100 characters)
subvolume_v2.py:156:101: E501 line too long (107 > 100 characters)
subvolume_v2.py:162:9: F841 local variable 'oe' is assigned to but never used
subvolume_v2.py:192:101: E501 line too long (101 > 100 characters)
subvolume_v2.py:210:9: F841 local variable 'oe' is assigned to but never used
subvolume_v2.py:237:101: E501 line too long (109 > 100 characters)
subvolume_v2.py:291:101: E501 line too long (106 > 100 characters)
subvolume_v2.py:300:101: E501 line too long (125 > 100 characters)
subvolume_v2.py:304:101: E501 line too long (109 > 100 characters)
subvolume_v2.py:305:101: E501 line too long (121 > 100 characters)
subvolume_v2.py:308:101: E501 line too long (109 > 100 characters)
subvolume_v2.py:309:101: E501 line too long (109 > 100 characters)
subvolume_v2.py:322:101: E501 line too long (110 > 100 characters)
subvolume_v2.py:325:101: E501 line too long (110 > 100 characters)
subvolume_v2.py:326:101: E501 line too long (114 > 100 characters)
subvolume_v2.py:347:101: E501 line too long (101 > 100 characters)
subvolume_v2.py:356:101: E501 line too long (112 > 100 characters)
subvolume_v2.py:360:101: E501 line too long (123 > 100 characters)
subvolume_v2.py:364:101: E501 line too long (105 > 100 characters)
subvolume_v2.py:369:101: E501 line too long (128 > 100 characters)
subvolume_v2.py:372:101: E501 line too long (101 > 100 characters)
subvolume_v2.py:378:101: E501 line too long (121 > 100 characters)
subvolume_v2.py:385:101: E501 line too long (149 > 100 characters)
subvolume_v2.py:386:101: E501 line too long (133 > 100 characters)
1     E302 expected 2 blank lines, found 1
32    E501 line too long (110 > 100 characters)
1     F401 '..template.SubvolumeTemplate' imported but unused
3     F841 local variable 'e' is assigned to but never used
zoey@zoey-VirtualBox:~/ceph/src/pybind/mgr/volumes/fs/operations/versions$ 



**After I reinstall the flake8, it still shows the same error. Then I found out it is because the version of pycodestyle has some incompatible issues. So I downgraded it and flake8 works.
But flake8 --ignore=W503 subvolume_base.py didn't show anything. In case it's still the flake8's problem, I run the other file and worked. So I think it is because there is simply no output for subvolume_base.py.**

**Review by varshar16 — APPROVED** [review]
Thank you for following up on the review comments, looks good!
Please feel free to pick other flake8 issues, it will be help you in improving git skills and get acquainted  with ceph review process.

**Review by batrick — APPROVED** [review]

**Comment by batrick** [comment]
https://tracker.ceph.com/projects/cephfs/wiki/Master#2021-October-26

**Pull request merged**
