### PR TITLE
rgw: radosgw-admin support user policy

### PR DESCRIPTION
**Pull request by joke-lee**
Signed-off-by: yuliyang <yuliyang@cmss.chinamobile.com>
hi @pritha-srivastava @cbodley , would you mind take a review? thanks

```

# set user policy
radosgw-admin user-policy put --uid yly3 --policy-name xxxx --policy-doc=\{\"Version\":\"2012-10-17\",\"Statement\":\[\{\"Sid\":\"VisualEditor0\",\"Effect\":\"Allow\",\"Action\":\"s3:PutObject\",\"Resource\":\"arn:aws:s3:::yly2\/*\"\}\]\}

# list user policy
radosgw-admin user-policy list --uid yly3
{
    "PolicyNames": [
        "xxxx"
    ]
}

# get user policy
radosgw-admin user-policy get --uid yly3 --policy-name xxxx
{
    "UserName": "yly3",
    "PolicyName": "xxxx",
    "PolicyDocument": "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Sid\":\"VisualEditor0\",\"Effect\":\"Allow\",\"Action\":\"s3:PutObject\",\"Resource\":\"arn:aws:s3:::yly2/*\"}]}"
}

# delete user policy
radosgw-admin user-policy delete --uid yly3 --policy-name xxxx
radosgw-admin user-policy list --uid yly3
{
    "PolicyNames": []
}
```

### CODE REVIEW

**Comment by joke-lee** [comment]
retest this please.

**Comment by joke-lee** [comment]
retest this please.

**Comment by pritha-srivastava** [comment]
A lot of code is duplicated between rgw_rest_user_policy.cc and rgw_admin.cc for User Policies. Can you make code common between them? Something similar to REST APIs and radosgw admin ops for Roles.

**Comment by cbodley** [comment]
> A lot of code is duplicated between rgw_rest_user_policy.cc and rgw_admin.cc for User Policies. Can you make code common between them? Something similar to REST APIs and radosgw admin ops for Roles.

@joke-lee can you please follow up on this feedback?

**Pull request closed without merging**
