### PR TITLE
rgw: do initialization in init_processing() for range copy

### PR DESCRIPTION
**Pull request by cfanz**
Currently, rgw has some strange behavior when do range copy with tenant enabled. This is because associated structures are not initialized before use. We can move the copy source logic in get_params() to init_processing() to fix that.

Fixes: https://tracker.ceph.com/issues/42825
Signed-off-by: cfanz <songxinying@sensetime.com>

### CODE REVIEW

**Comment by cbodley** [comment]
thanks @cfanz, could you please add a s3test case that covers this? it should have a tenanted user

**Comment by cfanz** [comment]
> thanks @cfanz, could you please add a s3test case that covers this? it should have a tenanted user

I've added the test case, could you help to review this? Thanks ~

**Comment by dang** [comment]
This has a build failure due to ongoing zipper work:
/home/dang/src/ceph/master/newclean/ceph/src/rgw/rgw_op.cc: In member function ‘virtual int RGWPutObj::init_processing()’:
/home/dang/src/ceph/master/newclean/ceph/src/rgw/rgw_op.cc:3499:42: error: ‘class rgw::sal::RGWUser’ has no member named ‘user_id’; did you mean ‘get_id’?
       copy_source_tenant_name = s->user->user_id.tenant;
                                          ^~~~~~~
                                          get_id

So it needs a rebase.

**Comment by cfanz** [comment]
Sorry for the delayed response. I have done the rebase. Codes in this [commit](https://github.com/ceph/ceph/pull/32487/commits/139495052ae3c87458ccd428f27657465a589201) are also copied to this pr.

**Comment by cfanz** [comment]
## Check list
- [x] rebase and update codes from [32487](https://github.com/ceph/ceph/pull/32487/commits/139495052ae3c87458ccd428f27657465a589201) and [32298](https://github.com/ceph/ceph/pull/32298)
- [x] local build check
- [x] run test with [s3-test](https://github.com/ceph/s3-tests/pull/328)(case:  test_multipart_copy_small_with_tenant)

**Comment by cfanz** [comment]
Hi, @dang , this has been marked stale, is there anything I can do to promote it?

**Comment by tchaikov** [comment]
@cfanz needs rebase

**Comment by cfanz** [comment]
> @cfanz needs rebase

Rebased. Hope you can help to review this, thanks. @tchaikov

**Comment by ivancich** [comment]
Teuthology results -- no regressions noted:
* http://pulpito.ceph.com/ivancich-2020-09-02_13:40:42-rgw-wip-eric-testing-2-distro-basic-smithi/
* http://pulpito.ceph.com/ivancich-2020-09-02_13:41:02-rgw-wip-eric-testing-2-distro-basic-smithi/

**Comment by ivancich** [comment]
@cfanz @dang No backports are listed in the tracker. If backports are appropriate please update this tracker, list the appropriate backports, and change the status to Pending Backport.

**Comment by epuertat** [comment]
@cfanz, this PR broke ceph-api tests (it was merged without api tests passing). Tracked in https://tracker.ceph.com/issues/47306 (CC: @LenzGr @callithea ). Please, address this issue asap, as it's blocking all subsequent PRs and masking any other issues.

**Comment by ivancich** [comment]
@cfanz -- it's not clear that this PR is the one that broke things. Investigation is taking place at https://github.com/ceph/ceph/pull/36996#issuecomment-687320937 .

**Pull request merged**
