### PR TITLE
Re-submitting rdma_local and the atomic variable change to Xio.

### PR DESCRIPTION
**Pull request by vsjulu**
Isolate the frequently accessed atomic variable 'connected' on a separate cache line
Return error (from xio bind method) if the cluster/public ip is not provided for each OSD separately and remove rdma local from xio bind method. This applies to XIO/RDMA messenger only. This change avoids any problems created by using rdma_local in the conf file while trying to use different IP addresses for different OSDs.

src/msg/xio/XioConnection.h

src/msg/xio/XioMessenger.cc

Signed-off-by: Subramanyam Varanasi s.varanasi@ssi.samsung.com

### CODE REVIEW

**Comment by mattbenjamin** [comment]
ok, ack.  we agreed to discard this rdma-local logic altogether

**Comment by mattbenjamin** [comment]
(looks good to me)

**Comment by tchaikov** [comment]
@vsjulu you might need to revise your commit messages and split and squash some of the commits.

**Comment by vsjulu** [comment]
@tchaikov 
1. Reg the pad for atomic variable connected- it is needed because we want to avoid any other data being a part of the cache line where this variable is present. This avoids any performance penalties when two different variables present in the same cache line are accessed by different threads.
2. Will make the changes to the error messages for the rdma local change. 
3. Will separate the two changes and submit separate pull requests and will merge the rdma changes.

**Comment by tchaikov** [comment]
> Reg the pad for atomic variable connected- it is needed because we want to avoid any other data being a part of the cache line where this variable is present. This avoids any performance penalties when two different variables present in the same cache line are accessed by different threads.

thanks for the explanation. i understand now. as an alternative approach, can we 
change `entity_inst_t peer;` to `entity_inst_t peer __attribute__((__aligned__(64)));` so it is also 64bit aligned, so we can make sure it is in another cache line? i am just trying avoid calculating the padding manually (i.e. magic number) and avoid adding a field never gets referenced (compiler or static checking tool will complain).

**Comment by tchaikov** [comment]
>  Will separate the two changes and submit separate pull requests and will merge the rdma changes.

two commits would suffice.

**Comment by vsjulu** [comment]
Close this one to submit a new request with XIO Changes alone - decided to split not only the commits but also the pull requests. A separate request will be submitted for the atomic connected change.

**Comment by vsjulu** [comment]
Close this one to submit a new request with XIO Changes alone - decided to split not only the commits but also the pull requests. A separate request will be submitted for the atomic connected change.

**Comment by vsjulu** [comment]
@tchaikov moving  atomic connected to the top and padding after it saves us some trouble - because we are not sure what would  follow after atomic connected. This way iti s explicit - we can add that in the comment over there.  So, in another commit, I would be changing it to 

  atomic_t connected __attribute__((align(64)));
 char pad_after[56]; 
XioConnection::type xio_conn_type;
XioPortal *portal;

This way it does not matter what field is added - else we have to make sure that if any other field is added in between it has to be again aligned.

**Pull request closed without merging**
