### PR TITLE
mimic: tools: Add clear-data-digest command to objectstore tool

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/37749

### CODE REVIEW

**Comment by smithfarm** [comment]
```
/home/jenkins-build/build/workspace/ceph-pull-requests/src/tools/ceph_objectstore_tool.cc: In function 'int clear_data_digest(ObjectStore*, coll_t, ghobject_t&)':
/home/jenkins-build/build/workspace/ceph-pull-requests/src/tools/ceph_objectstore_tool.cc:2671:18: error: 'using bufferlist = class ceph::buffer::list' {aka 'class ceph::buffer::list'} has no member named 'cbegin'; did you mean 'begin'?
   auto bp = attr.cbegin();
                  ^~~~~~
                  begin
```

**Comment by yuriw** [comment]
[wip-yuri4-testing-2019-07-23-1633-mimic](https://trello.com/c/G8TDc8rz/672-wip-yuri4-testing-2019-07-23-1633-mimic)

**Comment by smithfarm** [comment]
@dzafman I'm not sure if @yuriw runs that suite. I can try to run it, though.

**Comment by smithfarm** [comment]
@dzafman I ran it on the tip of mimic (which now includes this PR) and it passed.

**Pull request merged**
