### PR TITLE
osd/PGBackend: fix collection_list shadow return value

### PR DESCRIPTION
**Pull request by yuyuyu101**
Signed-off-by: Haomai Wang haomai@xsky.com

### CODE REVIEW

**Comment by yuyuyu101** [comment]
It will cause recovering data corrupt when collection_list return errno.

**Comment by tchaikov** [comment]
@yuyuyu101 could you file a tracker ticket for this issue? it applies to hammer and jewel also, i think.

**Comment by tchaikov** [comment]
lgtm.

**Comment by yuyuyu101** [comment]
http://tracker.ceph.com/issues/17713

**Comment by hjwsm1989** [comment]
nice catch!

**Comment by tchaikov** [comment]
@yuyuyu101 could you add a line like "Fixes: http://tracker.ceph.com/issues/17713" in your commit message?

**Comment by yuriw** [comment]
http://pulpito.ceph.com/yuriw-2016-10-26_22:43:11-rados-wip-yuri-testing2_2016_10_27-distro-basic-smithi/

**Pull request merged**
