### PR TITLE
test: Fix race with osd restart and doing a scrub

### PR DESCRIPTION
**Pull request by dzafman**
Fixes: https://tracker.ceph.com/issues/43150

Signed-off-by: David Zafman <dzafman@redhat.com>

## Checklist
- [x] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by dzafman** [comment]
Testing passed:
http://pulpito.ceph.com/dzafman-2019-12-06_10:03:39-rados-master-distro-basic-smithi/
1 failure fixed
http://pulpito.ceph.com/dzafman-2019-12-06_19:57:28-rados-master-distro-basic-smithi/

**Comment by dzafman** [comment]
@liewegas approved 8d3cfc6bc5d979c7398e3561c26a71116079d371 when it was part of ceph/ceph#32089 and got moved here.

**Comment by yuriw** [comment]
@dzafman do we need it on nautilus ?

**Comment by dzafman** [comment]
@yuriw This is test code fixes.  It could go into Nautilus if there are failures with "we got a bad state machine event" OSD crashes.

**Pull request merged**
