### PR TITLE
mgr/dashboard: fix tasks.mgr.dashboard.test_rgw suite

### PR DESCRIPTION
**Pull request by alfonsomthd**
Fixes: https://tracker.ceph.com/issues/44201
Signed-off-by: Alfonso Martínez <almartin@redhat.com>

## Checklist
- [x] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by alfonsomthd** [comment]
jenkins test dashboard backend

**Comment by callithea** [comment]
New dashboard backend API error:
```
Error EPERM: Test failed: Remote method threw exception: Traceback (most recent call last):
  File "/home/jenkins-build/build/workspace/ceph-dashboard-pr-backend/src/pybind/mgr/orchestrator/module.py", line 871, in self_test
    self._set_backend('')
  File "/home/jenkins-build/build/workspace/ceph-dashboard-pr-backend/src/pybind/mgr/orchestrator/_interface.py", line 144, in wrapper
    return func(*args, **kwargs)
TypeError: _set_backend() missing 1 required positional argument: 'module_name'

2020-02-20 11:37:19,260.260 INFO:__main__:test_orchestrator (tasks.mgr.test_module_selftest.TestModuleSelftest) ... ERROR
2020-02-20 11:37:19,260.260 INFO:__main__:Running ['./bin/ceph', 'log', 'Ended test tasks.mgr.test_module_selftest.TestModuleSelftest.test_orchestrator']
2020-02-20 11:37:20,633.633 INFO:__main__:Stopped test: test_orchestrator (tasks.mgr.test_module_selftest.TestModuleSelftest) in 26.642435s
2020-02-20 11:37:20,634.634 INFO:__main__:
2020-02-20 11:37:20,634.634 INFO:__main__:======================================================================
2020-02-20 11:37:20,634.634 INFO:__main__:ERROR: test_orchestrator (tasks.mgr.test_module_selftest.TestModuleSelftest)
2020-02-20 11:37:20,635.635 INFO:__main__:----------------------------------------------------------------------
2020-02-20 11:37:20,635.635 INFO:__main__:Traceback (most recent call last):
2020-02-20 11:37:20,635.635 INFO:__main__:  File "/home/jenkins-build/build/workspace/ceph-dashboard-pr-backend/qa/tasks/mgr/test_module_selftest.py", line 83, in test_orchestrator
2020-02-20 11:37:20,635.635 INFO:__main__:    self._selftest_plugin("orchestrator")
2020-02-20 11:37:20,636.636 INFO:__main__:  File "/home/jenkins-build/build/workspace/ceph-dashboard-pr-backend/qa/tasks/mgr/test_module_selftest.py", line 35, in _selftest_plugin
2020-02-20 11:37:20,636.636 INFO:__main__:    "mgr", "self-test", "module", module_name)
2020-02-20 11:37:20,636.636 INFO:__main__:  File "../qa/tasks/vstart_runner.py", line 942, in raw_cluster_cmd
2020-02-20 11:37:20,637.637 INFO:__main__:    proc = self.controller.run([os.path.join(BIN_PREFIX, "ceph")] + list(args), **kwargs)
2020-02-20 11:37:20,637.637 INFO:__main__:  File "../qa/tasks/vstart_runner.py", line 390, in run
2020-02-20 11:37:20,637.637 INFO:__main__:    proc.wait()
2020-02-20 11:37:20,637.637 INFO:__main__:  File "../qa/tasks/vstart_runner.py", line 190, in wait
2020-02-20 11:37:20,638.638 INFO:__main__:    raise CommandFailedError(self.args, self.exitstatus)
2020-02-20 11:37:20,638.638 INFO:__main__:CommandFailedError: Command failed with status 1: ['./bin/ceph', 'mgr', 'self-test', 'module', 'orchestrator']
2020-02-20 11:37:20,638.638 INFO:__main__:
2020-02-20 11:37:20,638.638 INFO:__main__:----------------------------------------------------------------------
2020-02-20 11:37:20,639.639 INFO:__main__:Ran 252 tests in 3167.112s
2020-02-20 11:37:20,639.639 INFO:__main__:
2020-02-20 11:37:20,639.639 INFO:__main__:FAILED (errors=1)
2020-02-20 11:37:20,639.639 INFO:__main__:
2020-02-20 11:37:20,640.640 INFO:__main__:======================================================================
2020-02-20 11:37:20,640.640 INFO:__main__:ERROR: test_orchestrator (tasks.mgr.test_module_selftest.TestModuleSelftest)
2020-02-20 11:37:20,640.640 INFO:__main__:----------------------------------------------------------------------
2020-02-20 11:37:20,640.640 INFO:__main__:Traceback (most recent call last):
2020-02-20 11:37:20,640.640 INFO:__main__:  File "/home/jenkins-build/build/workspace/ceph-dashboard-pr-backend/qa/tasks/mgr/test_module_selftest.py", line 83, in test_orchestrator
2020-02-20 11:37:20,640.640 INFO:__main__:    self._selftest_plugin("orchestrator")
2020-02-20 11:37:20,641.641 INFO:__main__:  File "/home/jenkins-build/build/workspace/ceph-dashboard-pr-backend/qa/tasks/mgr/test_module_selftest.py", line 35, in _selftest_plugin
2020-02-20 11:37:20,641.641 INFO:__main__:    "mgr", "self-test", "module", module_name)
2020-02-20 11:37:20,641.641 INFO:__main__:  File "../qa/tasks/vstart_runner.py", line 942, in raw_cluster_cmd
2020-02-20 11:37:20,641.641 INFO:__main__:    proc = self.controller.run([os.path.join(BIN_PREFIX, "ceph")] + list(args), **kwargs)
2020-02-20 11:37:20,641.641 INFO:__main__:  File "../qa/tasks/vstart_runner.py", line 390, in run
2020-02-20 11:37:20,641.641 INFO:__main__:    proc.wait()
2020-02-20 11:37:20,641.641 INFO:__main__:  File "../qa/tasks/vstart_runner.py", line 190, in wait
2020-02-20 11:37:20,642.642 INFO:__main__:    raise CommandFailedError(self.args, self.exitstatus)
2020-02-20 11:37:20,642.642 INFO:__main__:CommandFailedError: Command failed with status 1: ['./bin/ceph', 'mgr', 'self-test', 'module', 'orchestrator']
```

**Comment by alfonsomthd** [comment]
> @sebastian-philipp @bk201 maybe you could help out here?

@liewegas This PR from @sebastian-philipp 
https://github.com/ceph/ceph/pull/33432
seems to solve the orchestrator error detected by @callithea

**Comment by sebastian-philipp** [comment]
Yes. `TypeError: _set_backend() missing 1 required positional argument: 'module_name'` is fixed by #33432

**Comment by callithea** [comment]
> Yes. `TypeError: _set_backend() missing 1 required positional argument: 'module_name'` is fixed by #33432

Thanks! I'll include #33432 in my QA run

**Pull request merged**
