### PR TITLE
Replace placeholder with 'gateway'

### PR DESCRIPTION
**Pull request by gravitystorm**
This section is where all the placeholders are replaced by example text, this one had been missed out.

### CODE REVIEW

**Comment by dachary** [comment]
@gravitystorm ping ?

**Comment by dachary** [comment]
@gravitystorm re-ping ?

**Comment by gravitystorm** [comment]
@dachary sorry for the delay - I've updated the pull request and followed the contributing guide a bit more closely! Let me know if any further changes are needed.

**Comment by dachary** [comment]
thanks !

**Pull request merged**
