### PR TITLE
mailmap updates

### PR DESCRIPTION
**Pull request by theanalyst**
Mailmap updates for v0.93 release

### CODE REVIEW

**Comment by theanalyst** [comment]
@dachary done with the changes. Didn't expect this many mailmap updates :)

**Comment by dachary** [comment]
:+1: looks ready to send mails to the authors. A lot of updates indeed :-)

**Comment by dachary** [comment]
@theanalyst did you get replies to the mails sent to the authors ?

**Comment by theanalyst** [comment]
@dachary a few updates from mails, I'll be pushing them

**Comment by dachary** [comment]
There is one more to add
<pre>
    22	      1 Billy Olsen <billy.olsen@canonical.com>
</pre>
which shows when I **bash credits.sh tags/v0.92..ceph/hammer** on your branch. Otherwise all good !

**Comment by theanalyst** [comment]
Yeah when I updated mailmap & orgmap I made a mistake in mapping.. fixing
this

**Comment by theanalyst** [comment]
@dachary c1fce65b0268128fcd888ea5d44d190e1b18d63e should fix that

**Pull request merged**
