### PR TITLE
LTTng-UST tracing should be dynamically enabled

### PR DESCRIPTION
**Pull request by dillaman**
Currently, LTTng-UST tracepoint providers are statically linked into librbd, librados, and ceph-osd.  This forces LTTng-UST tracing to be enabled from startup.  This change separates the tracepoint providers into standalone dynamic libraries that are loaded based upon new tracing config options.

### CODE REVIEW

**Comment by smithfarm** [comment]
@dillaman I'm supposed to be working on this issue http://tracker.ceph.com/issues/13350 - do you see any relation to this PR or is it orthogonal?

**Comment by dillaman** [comment]
@smithfarm If this were to be merged into Infernalis, I would expect that those teuthology errors to disappear just because LTTng-UST won't be running during the tests by default.

**Comment by liewegas** [comment]
awesome.. please target infernalis

**Comment by dillaman** [comment]
Replaced by new infernalis PR #6249

**Pull request closed without merging**
