### PR TITLE
mgr/dashboard: Update copyright from 2016 to 2017

### PR DESCRIPTION
**Pull request by yaozongyou**
Signed-off-by: Yao Zongyou <yaozongyou@vip.qq.com>

### CODE REVIEW

**Comment by yaozongyou** [comment]
retest this please

**Comment by jcsp** [comment]
It probably doesn't matter much, but I believe copyright notices are supposed to show either the year of first publication, or a range of dates.  So if we're updating this, it would be "2016-2017".

**Comment by tchaikov** [comment]
i concur with John. see https://stackoverflow.com/questions/2390230/do-copyright-dates-need-to-be-updated

**Comment by yaozongyou** [comment]
Got it, thanks~

**Pull request closed without merging**
