### PR TITLE
librados:  For C-API, expose LIBRADOS_OPERATION_FULL_FORCE flag

### PR DESCRIPTION
**Pull request by majianpeng**
Make librados c-api can use LIBRADOS_OPERATION_FULL_FORCE. This maily
for delete op.

Signed-off-by: Jianpeng Ma jianpeng.ma@intel.com

### CODE REVIEW

**Comment by dzafman** [comment]
Related to #9087 which fixes the handling of this flag.

**Comment by dachary** [comment]
jenkins test this please (no logs)

**Comment by dachary** [comment]
@dzafman looks good to me. What do you say ?

**Comment by dzafman** [comment]
@dachary Looks good.  Too bad there isn't a test case (there is one for FULL_TRY).  Also, the rados command doesn't include an option to pass FULL_TRY and now FULL_FORCE.   Add a tracker?

**Comment by tchaikov** [comment]
http://pulpito.ceph.com/kchai-2016-11-25_08:09:33-rados-wip-kefu-testing2---basic-mira/

**Pull request merged**
