### PR TITLE
cmake: pass RULE_LAUNCHER_* to cython

### PR DESCRIPTION
**Pull request by tchaikov**
* pass the environment variables using `env` to pass environment
  varibles with space(s) in them to the COMMAND in add_custom_target.
  otherwise, cmake will try to quote the space with "\". this breaks the
  generated command line.
* add a comment for ccache to note that we do not expect ccache to speed
  up linking. we use it as the linker's launcher to workaround
  https://bugs.python.org/issue8027. to be specific,
  distutils.UnixCCompiler.link overwrites the first linker CLI's arg
  using the the first C++ compiler's CLI arg, if "env" is not used to
  launch the linker. this breaks the cythonization of our pybind APIs.

Signed-off-by: Kefu Chai <kchai@redhat.com>

### CODE REVIEW

**Comment by robbat2** [comment]
@tchaikov  See https://github.com/ceph/ceph/pull/8461#issuecomment-208034584 your patch doesn't effect ccache C++ linking.

**Comment by tchaikov** [comment]
build passed at http://gitbuilder.sepia.ceph.com/gitbuilder-ceph-tarball-trusty-amd64-basic/log.cgi?log=fc81bec888eba3be488c34508d4ae3521372b175

**Comment by jdurgin** [comment]
lgtm

**Comment by tchaikov** [comment]
@liewegas @athanatos can we include this change in jewel?

**Pull request merged**
