### PR TITLE
hammer: mon: send updated monmap to its subscribers

### PR DESCRIPTION
**Pull request by tchaikov**
http://tracker.ceph.com/issues/17678

### CODE REVIEW

**Comment by tchaikov** [comment]
will remove [DNM] once the master PR is merged.

**Comment by smithfarm** [comment]
@tchaikov Could you rebase please?

**Comment by smithfarm** [comment]
oops, this PR was not linked with the hammer backport in the tracker, so I re-did it in #11928

**Comment by smithfarm** [comment]
@tchaikov Please rebase.

**Comment by tchaikov** [comment]
@smithfarm done.

**Comment by smithfarm** [comment]
@gregsfortytwo This backport passed a rados suite at http://tracker.ceph.com/issues/17151#note-7 with failures that I believe have been addressed (except for http://tracker.ceph.com/issues/15139 which is caused by the build system no longer providing dumpling-era packages).

I have rebuilt the integration branch to include the two fixes and scheduled a new run at http://tracker.ceph.com/issues/17151#note-14

Do you think it's OK to merge provided the second run succeeds?

**Comment by smithfarm** [comment]
Second run succeeded; third run here: http://pulpito.front.sepia.ceph.com/smithfarm-2016-11-21_11:52:41-rados-hammer-backports---basic-smithi/

**Comment by smithfarm** [comment]
@gregsfortytwo @athanatos This passed another rados run, see http://tracker.ceph.com/issues/17151#note-23

Do you think it can be merged?

**Comment by athanatos** [comment]
I'm ok with this if @tchaikov is.

**Comment by tchaikov** [comment]
lgtm, i vote for myself!

**Pull request merged**
