### PR TITLE
rgw: fix api response in case of get and delete object tagging apis

### PR DESCRIPTION
**Pull request by selvakumaar5496**
Signed-off-by: Selvakumar <selva.k.nambi@seagate.com>

Problem:
GetObjectTagging and DeleteObjectTagging API does not return 'NoSuchKey' error for a non-existent object in a bucket with Motr as backend

Resolution:
Made some changes beyond SAL layer.
Tested the changes with plain ceph too and did not see any impact on the behaviour.

Results:
```
# aws --endpoint=$endpoint s3api get-object-tagging --bucket test-buckets41 --key test-key-02
An error occurred (NoSuchKey) when calling the GetObjectTagging operation: Unknown

# aws --endpoint=$endpoint s3api delete-object-tagging --bucket test-buckets41 --key test-key-02
An error occurred (NoSuchKey) when calling the DeleteObjectTagging operation: Unknown
```

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/master/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by selvakumaar5496** [comment]
@dang, @mattbenjamin can you guys take a look at this please?

**Comment by sjain09** [comment]
@selvakumaar5496 , Please update the proper problem statement and the solution in the description along with the test results for better understanding of the issue.

Also update the summary as below:
"rgw: fix api response in case of get and delete object tagging apis"

**Review by dang — APPROVED** [review]

**Comment by dang** [comment]
jenkins run make check

**Comment by dang** [comment]
jenkins test api

**Comment by cbodley** [comment]
this is causing a couple s3test failures in [qa](https://pulpito.ceph.com/cbodley-2022-06-24_20:01:25-rgw-wip-cbodley-testing-distro-default-smithi/). ex. [teuthology.log](http://qa-proxy.ceph.com/teuthology/cbodley-2022-06-24_20:01:25-rgw-wip-cbodley-testing-distro-default-smithi/6898094/teuthology.log):
```
2022-06-24T20:35:41.505 INFO:teuthology.orchestra.run.smithi074.stderr:======================================================================
2022-06-24T20:35:41.506 INFO:teuthology.orchestra.run.smithi074.stderr:FAIL: s3tests_boto3.functional.test_s3.test_put_delete_tags
2022-06-24T20:35:41.507 INFO:teuthology.orchestra.run.smithi074.stderr:----------------------------------------------------------------------
2022-06-24T20:35:41.507 INFO:teuthology.orchestra.run.smithi074.stderr:Traceback (most recent call last):
2022-06-24T20:35:41.508 INFO:teuthology.orchestra.run.smithi074.stderr:  File "/home/ubuntu/cephtest/s3-tests-client.0/virtualenv/lib/python3.8/site-packages/nose/case.py", line 198, in runTest
2022-06-24T20:35:41.508 INFO:teuthology.orchestra.run.smithi074.stderr:    self.test(*self.arg)
2022-06-24T20:35:41.509 INFO:teuthology.orchestra.run.smithi074.stderr:  File "/home/ubuntu/cephtest/s3-tests-client.0/s3tests_boto3/functional/test_s3.py", line 12081, in test_put_delete_tags
2022-06-24T20:35:41.509 INFO:teuthology.orchestra.run.smithi074.stderr:    eq(response['ResponseMetadata']['HTTPStatusCode'], 204)
2022-06-24T20:35:41.510 INFO:teuthology.orchestra.run.smithi074.stderr:AssertionError: 200 != 204
2022-06-24T20:35:41.510 INFO:teuthology.orchestra.run.smithi074.stderr:-------------------- >> begin captured logging << --------------------
```
and
```
2022-06-24T20:35:41.705 INFO:teuthology.orchestra.run.smithi074.stderr:======================================================================
2022-06-24T20:35:41.706 INFO:teuthology.orchestra.run.smithi074.stderr:FAIL: s3tests_boto3.functional.test_s3.test_delete_tags_obj_public
2022-06-24T20:35:41.706 INFO:teuthology.orchestra.run.smithi074.stderr:----------------------------------------------------------------------
2022-06-24T20:35:41.707 INFO:teuthology.orchestra.run.smithi074.stderr:Traceback (most recent call last):
2022-06-24T20:35:41.707 INFO:teuthology.orchestra.run.smithi074.stderr:  File "/home/ubuntu/cephtest/s3-tests-client.0/virtualenv/lib/python3.8/site-packages/nose/case.py", line 198, in runTest
2022-06-24T20:35:41.707 INFO:teuthology.orchestra.run.smithi074.stderr:    self.test(*self.arg)
2022-06-24T20:35:41.708 INFO:teuthology.orchestra.run.smithi074.stderr:  File "/home/ubuntu/cephtest/s3-tests-client.0/s3tests_boto3/functional/test_s3.py", line 12285, in test_delete_tags_obj_public
2022-06-24T20:35:41.708 INFO:teuthology.orchestra.run.smithi074.stderr:    eq(response['ResponseMetadata']['HTTPStatusCode'], 204)
2022-06-24T20:35:41.709 INFO:teuthology.orchestra.run.smithi074.stderr:AssertionError: 200 != 204
2022-06-24T20:35:41.709 INFO:teuthology.orchestra.run.smithi074.stderr:-------------------- >> begin captured logging << --------------------
```

**Comment by selvakumaar5496** [comment]
@cbodley Updated the PR and now both the test cases works fine

**Comment by alimaredia** [comment]
jenkins test api

**Comment by selvakumaar5496** [comment]
@alimaredia @cbodley @dang I see all checks are passed now.. Could you please merge this?

**Comment by cdeshmukh** [comment]
thanks @dang for reviewing & approval.
@cbodley or @alimaredia can you please review too.

And then someone merge please

**Comment by selvakumaar5496** [comment]
@cbodley A gentle remainder. Are we good to merge this ?

**Comment by alimaredia** [comment]
Latest teuthology run: https://pulpito.ceph.com/amaredia-2022-07-14_18:48:02-rgw-wip-rgw-object-api-tagging-fix-distro-default-smithi/

**Pull request merged**
