### PR TITLE
cephadm/apply_spec: use pyyaml for yaml parsing

### PR DESCRIPTION
**Pull request by tnyeanderson**
**THIS IS CURRENTLY A WORK IN PROGRESS, TO BE REBASED ON COMPLETION. CREATING THIS PR TO TRACK THE ISSUE AND TO RUN JENKINS TESTS**

See my comment [here](https://github.com/ceph/ceph/pull/49854#issuecomment-1445448752) for an explanation and example. At the moment, YAML is being parsed with homegrown adhoc functions which are extremely prone to bugs as they are not parsing according to the YAML spec. They also increase code complexity needlessly.

This is solved by importing the `pyyaml` library, already used by the orchestrator, to perform the parsing in cephadm. This simplifies the code significantly and allows for all the edge cases and formats provided by the YAML spec.

Please note that this makes the work done in #49854 unnecessary and rips the bandaid off rather than applying another.

**Let me know if there are procedures for adding this dependency that I am unaware of. I am still learning the ceph codebase!**

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [x] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [x] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by tnyeanderson** [comment]
This is dependent on the cephadm refactor to enable third-party libraries. See more info [here](https://github.com/ceph/ceph/pull/49854#issuecomment-1446707153).

**Comment by tnyeanderson** [comment]
Has the above refactor been completed yet to allow dependencies?

**Comment by phlogistonjohn** [comment]
Hi there, I wanted to let you know that PR #52492 has been merged. This PR adds support for Jinja2 templates and the basic infrastructure to support dependencies in cephadm.

There are a few items that I think you should be aware of:
* The file `src/cephadm/requirements.txt` _will not_ be used by cephadm build. It's not a merge conflict so I wanted to call this out.
* The file `src/cephadm/zipapp-reqs.txt` will be used to set up the tests running under tox _only_
* Two lists of requirements near the top of `src/cephadm/build.py` are used to determine what dependencies are bundled into a cephadm build. This is a workaround due to limitations in old versions of python and pip that ceph builds with.
* There's a new suite of tests for verifying that the cephadm zipapp build works. Run `(cd src/cephadm && tox -e test_build)` to execute them. The tests require `podman`. They must be run manually at this time, they're not automatically run in CI.

As the author of the jinja2 PR, I'm happy to try and help you with any questions you may have here regarding adding pyyaml support.

**Comment by tnyeanderson** [comment]
>Two lists of requirements near the top of src/cephadm/build.py are used to determine what dependencies are bundled into a cephadm build. This is a workaround due to limitations in old versions of python and pip that ceph builds with.

I see the two lists `PY_REQUIREMENTS` and `PY36_REQUIREMENTS`. I think I understand the `PY36_REQUIREMENTS` (for python 3.6 and above I assume), but what python versions should be considered for `PY_REQUIREMENTS`?

I have not run the new test suite yet, but obviously these dependencies need to be fixed first. Thanks for your help!

**Comment by phlogistonjohn** [comment]
Apologies if this was something you wanted to do, but I have implemented pyyaml in the cephadm zipapp in this PR: https://github.com/ceph/ceph/pull/54889
My coworker needed it and it was somewhat complex to resolve and so I took it upon myself just to get it done.

**Comment by tnyeanderson** [comment]
No worries, I'm happy as long as it gets done :)

**Pull request closed without merging**
