### PR TITLE
memstore: fix the build on i386

### PR DESCRIPTION
**Pull request by tchaikov**
on i386, uint64 is `unsigned long long`, while size_t is `unsigned int`.
std::min(uint64, size_t) can not be resolved.

Signed-off-by: Kefu Chai <kchai@redhat.com>

### CODE REVIEW

**Comment by tchaikov** [comment]
```
..../ceph-erasure-code-corpus/v0.92-988/non-regression.sh:54: shec_variants ceph_erasure_code --debug-osd 20 --plugin_exists shec
..../ceph-erasure-code-corpus/v0.92-988/non-regression.sh:54: shec_variants sed -e 's/.*load: *//'
.../ceph-erasure-code-corpus/v0.92-988/non-regression.sh:54: shec_variants eval variant=load 'dlopen(/usr/local/lib/ceph/erasure-code/libec_shec.so):' /usr/local/lib/ceph/erasure-code/libec_shec.so: cannot open shared object file: No such file or directory
../ceph-erasure-code-corpus/v0.92-988/non-regression.sh: eval: line 54: syntax error near unexpected token `('
../ceph-erasure-code-corpus/v0.92-988/non-regression.sh: eval: line 54: `variant=load dlopen(/usr/local/lib/ceph/erasure-code/libec_shec.so): /usr/local/lib/ceph/erasure-code/libec_shec.so: cannot open shared object file: No such file or directory'
```

**Comment by dachary** [comment]
@tchaikov it looks like the shec plugin did not build. I don't think it has i386 specific build instructions though, that's weird.

**Comment by dachary** [comment]
@t-miyamae it looks like we're having issues with the shec plugin on i386, does that ring a bell ?

**Comment by dachary** [comment]
@t-miyamae nevermind, it's unrelated, sorry for the noise. @tchaikov this is http://tracker.ceph.com/issues/12933

**Comment by dachary** [comment]
https://github.com/ceph/ceph/pull/5794 fixes the shec / jerasure variant problem.

**Comment by dachary** [comment]
Now that #5794 is merged in the infernalis branch, maybe this fix should go to the infernalis branch as well.

**Comment by dachary** [comment]
<pre>
Reviewed-by: Loic Dachary &lt;ldachary@redhat.com>
</pre>

**Comment by tchaikov** [comment]
@dachary shall i create a pull request against infernalis for this fix also?

**Comment by dachary** [comment]
@tchaikov I'm not sure how it's done right now. I think @liewegas  does cherry-pick of master pull requests that are marked infernalis. Wild guess on my part ;-)

**Pull request merged**
