### PR TITLE
mimic: osd: process_copy_chunk remove obc ref before pg unlock

### PR DESCRIPTION
**Pull request by pdvian**
http://tracker.ceph.com/issues/38972

### CODE REVIEW

**Comment by tchaikov** [comment]
```
[  FAILED  ] 3 tests, listed below:
[  FAILED  ] TestAllocatorLevel01.test_4G_alloc_bug
[  FAILED  ] TestAllocatorLevel01.test_4G_alloc_bug2
[  FAILED  ] TestAllocatorLevel01.test_4G_alloc_bug3
...
The following tests FAILED:
	129 - unittest_fastbmap_allocator (Failed)
```

retest this please.

**Comment by tchaikov** [comment]
retest this please.

**Comment by smithfarm** [comment]
@tchaikov Same failures on re-run.

**Comment by smithfarm** [comment]
Ah, same failures are seen in another mimic backport PR: https://github.com/ceph/ceph/pull/27588

Looks like a regression in mimic.

**Comment by smithfarm** [comment]
jenkins re-test this please

**Comment by yuriw** [comment]
[wip-yuri2-testing-2019-04-29-1936-mimic](https://trello.com/c/dXehT7mH/597-wip-yuri2-testing-2019-04-29-1936-mimic)

**Pull request merged**
