### PR TITLE
luminous:  platform.linux_distribution() is deprecated; stop using it

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/39277

### CODE REVIEW

**Comment by smithfarm** [comment]
This has baked in mimic for quite some time now.

**Comment by yuriw** [comment]
[wip-yuri5-testing-2019-09-30-1944-luminous](https://trello.com/c/oisaBLUN/700-wip-yuri5-testing-2019-09-30-1944-luminous)

**Comment by smithfarm** [comment]
```
The following tests FAILED:
	  3 - test_objectstore_memstore.sh (Timeout)
```

**Comment by smithfarm** [comment]
jenkins test make check

**Pull request merged**
