### PR TITLE
mimic: rpm: missing dependency on python34-ceph-argparse from python34-cephfs (and others?)

### PR DESCRIPTION
**Pull request by pdvian**
http://tracker.ceph.com/issues/37613

### CODE REVIEW

**Comment by yuriw** [comment]
[wip-yuri2-testing-2019-01-29-1704-mimic](https://trello.com/c/e3TKSDYU/523-wip-yuri2-testing-2019-01-29-1704-mimic)

**Comment by smithfarm** [comment]
So, as I understand it, this fix is not needed in mimic.

**Comment by batrick** [comment]
I believe not having this fix causes this failure: /ceph/teuthology-archive/yuriw-2019-02-15_13:59:21-fs-wip-yuri3-testing-2019-02-13-0003-mimic-distro-basic-smithi/3594823/teuthology.log

**Comment by pdvian** [comment]
@batrick does this PR needs fix for installing unmet deps ? or should we first get fix for 38154 and then cherry pick fix ?

**Comment by smithfarm** [comment]
closing in favor of https://github.com/ceph/ceph/pull/27949

**Pull request closed without merging**
