### PR TITLE
corrected some confusing numbers

### PR DESCRIPTION
**Pull request by RobertJansen1**
Signed-off-by: Robert Jansen <r.jansen@fairbanks.nl>

### CODE REVIEW

**Comment by dachary** [comment]
Interestingly it ends up backwards : the title should be on top and the signed-off-by should be last. Note that the SIgned-off-by: should be like
<pre>
Name Lastname &lt;mail@address.org> 
</pre>

**Comment by RobertJansen1** [comment]
that was my mistake. is it OK now? if not i am happy to do it again

**Comment by dachary** [comment]
@RobertJansen1 the commit itself still needs update : https://github.com/RobertJansen1/ceph/commit/00d26643810aa2589034d1939f5de04b8970767a . It's interesting to see how inflexible the github web interface can be ;-)

**Comment by RobertJansen1** [comment]
lets try that again thanks for the patience

**Comment by dachary** [comment]
thanks for your persistence :-)

**Pull request closed without merging**
