### PR TITLE
jewel: rgw: rgw_file: fix missing unlock in unlink

### PR DESCRIPTION
**Pull request by mattbenjamin**
http://tracker.ceph.com/issues/19525

### CODE REVIEW

**Comment by smithfarm** [comment]
```
rgw/rgw_file.cc: In member function 'int rgw::RGWLibFS::unlink(rgw::RGWFileHandle*, const char*, uint32_t)':
rgw/rgw_file.cc:262:14: error: 'class rgw::RGWFileHandle' has no member named 'has_children'
  if (rgw_fh->has_children()) {
              ^
make[3]: *** [rgw/librgw_la-rgw_file.lo] Error 1
```

**Comment by smithfarm** [comment]
Marking DNM on the assumption the build failure is reproducible. (The DNM is there to keep this PR out of the jewel integration branch - once it's fixed, please remove the DNM.)

**Comment by mattbenjamin** [comment]
@smithfarm ow!

**Comment by smithfarm** [comment]
@mattbenjamin Conflict resolution description?

**Comment by mattbenjamin** [comment]
@smithfarm don't follow;  what this revealed was a missing commit

**Comment by smithfarm** [comment]
@mattbenjamin Got it, thanks for the clarification.

**Comment by ktdreyer** [comment]
Who can review and approve this PR?

**Comment by smithfarm** [comment]
@ktdreyer This PR is included in the 10.2.8 integration testing which is currently ongoing at http://tracker.ceph.com/issues/19538

I haven't gotten a clean rgw run yet, though (WIP).

**Comment by smithfarm** [comment]
@mattbenjamin This passed an rgw suite at http://tracker.ceph.com/issues/19538#note-24

Please review/approve if you agree it can be merged.

**Comment by smithfarm** [comment]
Note: somehow, something got merged to jewel recently that caused a regression. Bisect is ongoing at http://tracker.ceph.com/issues/19538#note-30

Merging to jewel is suspended pending the result of that bisect.

**Comment by smithfarm** [comment]
@mattbenjamin @yehudasa This passed an rgw suite at http://tracker.ceph.com/issues/19538#note-24

The regression in `upgrade/hammer-x` has been bisected down to a PR completely unrelated to this one, so I'm back to merging jewel PRs.

Please review.

**Comment by smithfarm** [comment]
The rgw_file backports tend to conflict with eachother, so ganging them all up in a single PR - #14653

**Pull request closed without merging**
