### PR TITLE
mon: expose require_jewel_osds flag to user

### PR DESCRIPTION
**Pull request by xiexingguo**

### CODE REVIEW

**Comment by xiexingguo** [comment]
@liewegas Could you help to review this? Thanks.

**Comment by liewegas** [comment]
Hmm, I'm actually not quite sure why this explicit OSDMap flag is there.  @athanatos ?

**Comment by liewegas** [comment]
Hmm, fo rhammer, there was the bitwise sort flag introduced at the same time.  And an individual osd couldn't downgrade.  We didn't have (or quite need) a cluster-wide flag to prevent downgrade.

**Comment by athanatos** [comment]
I think there were features which once used prevent pre-jewel osds from working.  I think users cannot be allowed to cancel that flag.

**Comment by xiexingguo** [comment]
change set:
- add "require_jewel_osds" to white list, so user can access it by the "ceph osd set *" command family(which is previously invisible to user)
- update relevant test cases

@liewegas @athanatos  Please check again, thanks.

**Comment by xiexingguo** [comment]
retest this please

**Comment by athanatos** [comment]
Doesn't it get automatically set once a jewel required feature is used?  I'm not clear on what the use case is.

**Comment by xiexingguo** [comment]
> Doesn't it get automatically set once a jewel required feature is used?

For newly created cluster it will be. 
But it seems we also try to allow user to set this flag manually at https://github.com/ceph/ceph/blob/master/src/mon/OSDMonitor.cc#L6265, perhaps for upgrade from a pre-jewel cluster?  The problem is that we don't add this flag into white list,  so it is actually not invisible to user.

**Comment by athanatos** [comment]
@xiexingguo I get it now.  Yeah, this version makes sense.

**Pull request merged**
