### PR TITLE
Merge octopus into master

### PR DESCRIPTION
**Pull request by liewegas**

### CODE REVIEW

**Comment by toabctl** [comment]
Isn't it supposed to be the other way arround? Backport stuff from master to octopus?

**Comment by liewegas** [comment]
> Isn't it supposed to be the other way arround? Backport stuff from master to octopus?

As soon as we tag 15.2.0 we will switch to the normal backport process.  For now, it is easier to test + merge fixes once into octopus and periodically merge those into master.

**Comment by toabctl** [comment]
> As soon as we tag 15.2.0 we will switch to the normal backport process. For now, it is easier to test + merge fixes once into octopus and periodically merge those into master.

@liewegas  Why do we have the octopus branch then? Seems like an indicator that we branched to early.

**Comment by liewegas** [comment]
> > As soon as we tag 15.2.0 we will switch to the normal backport process. For now, it is easier to test + merge fixes once into octopus and periodically merge those into master.
> 
> @liewegas Why do we have the octopus branch then? Seems like an indicator that we branched to early.

It unblocks development for post-octopus work.

**Comment by toabctl** [comment]
> It unblocks development for post-octopus work.

hm. that could be just handled in wip- branches. doesn't make sense to me. but thanks for the explanation.

**Pull request merged**
