### PR TITLE
librbd: avoid blocking AIO API methods

### PR DESCRIPTION
**Pull request by dillaman**

### CODE REVIEW

**Comment by jdurgin** [comment]
The behavior makes very little sense, and I see no users depending on it (only librbd users of aio_read that I can find are qemu, tests, and benchmarking tools, which just check for non-negative return code). I'd say get rid of it, but since someone could potentially actually be using it somewhere add a note to PendingReleaseNotes

**Comment by jdurgin** [comment]
None of the librbd bindings in other languages include aio, so it should be safe for higher-level users too.

**Comment by dachary** [comment]
please ignore the bot failure (network problem)

**Comment by jdurgin** [comment]
Looks good. Have you tested with fio's rbd backend or something else capable of doing lots of aio to see if the default single thread is a bottleneck?

Should probably add something like that to ceph-qa-suite too, with >1 rbd op thread coverage as well.

**Comment by yuyuyu101** [comment]
Hmm, I'm not sure how much concurrency can improve via WorkQueue, I'm concerned about the potential latency increasement for normal workload(low iodepth)? Because WorkQueue always has a significant context switch cost.

**Comment by yuyuyu101** [comment]
OOPS, I found the corresponding bug tracker, looks like decoupling front-end with back-end is a good option to solve it.

I'm willing to performance this change with potential degraded.

**Comment by jdurgin** [comment]
Thanks Haomai, that'd be great

**Comment by yuyuyu101** [comment]
@jdurgin @dillaman 
image

I write a simple librbd mock patch to let all write op immediately completed when _send_op. So it could let we focus on librbd itself and make difference enhanced.

The result looks reasonable and obvious!

**Comment by yuyuyu101** [comment]
@jdurgin 
Hi Josh, I'm not sure whether we could bear the huge performance degraded for low iodepth? It may not good for latency-sensitive applicatoin?

**Comment by jdurgin** [comment]
@yuyuyu101 The added latency certainly isn't good, but I think we can improve it. I don't see a way to prevent blocking that wouldn't add some latency to low iodepth cases, without a very large restructuring though.

**Comment by dillaman** [comment]
@yuyuyu101 I ran a similar test where I instantly completed read/write requests within ```AioRead::send``` and ```AbstractWrite::send```, rbd cache disabled, and with 1 iodepth:

fio results w/ no WorkQueue (higher submission latencies, lower completion latencies):
```
  read : io=78859MB, bw=269178KB/s, iops=67294, runt=299992msec
    slat (usec): min=2, max=3004, avg= 6.59, stdev= 4.98
    clat (usec): min=0, max=1078, avg= 0.22, stdev= 0.89
     lat (usec): min=2, max=3006, avg= 6.81, stdev= 5.11
```

fio results w/ WorkQueue (lower submission latencies, higher completion latencies):
```
  read : io=79408MB, bw=271052KB/s, iops=67762, runt=299992msec
    slat (usec): min=0, max=473, avg= 0.30, stdev= 0.90
    clat (usec): min=4, max=3093, avg= 6.49, stdev= 4.67
     lat (usec): min=5, max=3093, avg= 6.80, stdev= 4.81
```

**Comment by yuyuyu101** [comment]
@dillaman interesting! Do you remember update commits which may related to performance?

I would try again if get the same result. It would be great if we can achieve win-win :+1:

**Pull request merged**
