### PR TITLE
nautilus: mgr: force purge normal ceph entities from service map

### PR DESCRIPTION
**Pull request by Vicente-Cheng**
backport tracker: https://tracker.ceph.com/issues/45050

---

backport of https://github.com/ceph/ceph/pull/34281
parent tracker: https://tracker.ceph.com/issues/44677

this backport was staged using ceph-backport.sh version 15.1.1.389
find the latest version at https://github.com/ceph/ceph/blob/master/src/script/ceph-backport.sh

### CODE REVIEW

**Comment by smithfarm** [comment]
@Vicente-Cheng Please rebase?

**Comment by Vicente-Cheng** [comment]
@smithfarm rebased!

**Comment by smithfarm** [comment]
```
1 tests failed out of 168 Total Test time (real) = 970.42 sec
The following tests FAILED: 5 - run-tox-mgr-dashboard (Failed)
```

Ruled a PASS

**Comment by yuriw** [comment]
[wip-yuri-testing-2020-04-22-1449-nautilus](https://trello.com/c/6cC3210z/876-wip-yuri-testing-2020-04-22-1449-nautilus)

**Comment by neha-ojha** [comment]
We need to maintain the same labels in backport PRs in order for them to be run through correct teuthology suites.

**Comment by yuriw** [comment]
@Vicente-Cheng @smithfarm see @neha-ojha commnt ^

**Comment by smithfarm** [comment]
@yuriw @neha-ojha ACK. Will try to do better with the labelling.

**Comment by jdurgin** [comment]
perhaps the backport script could copy labels other than needs-*?

**Comment by Vicente-Cheng** [comment]
Sorry for the late reply.
I check the backport script and it looks like that has the argument to make some labels.
Maybe we could use that to make the right label with backport pr for run correct teuthology suites? @smithfarm @yuriw

**Comment by smithfarm** [comment]
@Vicente-Cheng Yes, the backport script needs to be patched so it takes labels (but only certain ones) from the master PR instead of what it is currently doing.

**Comment by yuriw** [comment]
[wip-yuri5-testing-2020-04-27-1505-nautilus](https://trello.com/c/nmjAmDhf/885-wip-yuri5-testing-2020-04-27-1505-nautilus)

**Comment by gregsfortytwo** [comment]
I don't think I actually reviewed this code in master but looks like a clean cherry-pick and it's a needed bugfix so 👍

**Comment by smithfarm** [comment]
@gregsfortytwo I asked you for a review of this PR because IIRC you merged this code into master: see #34281.

Thanks for reviewing it.

**Comment by yuriw** [comment]
[wip-yuri2-testing-2020-05-01-1612-nautilus](https://trello.com/c/MGXH8eti/893-wip-yuri2-testing-2020-05-01-1612-nautilus)

**Comment by ajarr** [comment]
@yuriw , this is good to merge

**Comment by smithfarm** [comment]
jenkins test make check

**Comment by Vicente-Cheng** [comment]
Hi @smithfarm,

If I want to help to patch backport script for a better label when backport.
The thing that I need to patch is:
 - found the right label from master pr then tag it with backport pr? Only one label could be tagged?

**Pull request merged**
