### PR TITLE
RGW|BN : fix for persistent topic changing endpoint\endpointargs

### PR DESCRIPTION
**Pull request by AliMasarweh**
Previously endpoint and endpoint_args where held in the each entry of the persistent queue,
this meant that when the topic updates its endpoint/endpoint_args ,entries wouldn't got this update,
to fix this issue, we store the endpoint and the endpoint_args in the header of the queue (urgent_data)

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [x] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Comment by cbodley** [comment]
> Previously endpoint and endpoint_args where held in the each entry of the persistent queue,
> this meant that when the topic updates its endpoint/endpoint_args ,entries wouldn't got this update,
> to fix this issue, we store the endpoint and the endpoint_args in the header of the queue (urgent_data)

why can't rgw::notify::Manager consult the topic metadata for the current endpoint info?

**Comment by yuvalif** [comment]
regarding the tests change:
* can you please split to a different commit, so we can apply on either of the approaches to fix the caching?
* can you please keep both http and kafka versions (no need for amqp)?
* please also add kafka flavor to `test_persistent_ps_s3_data_path_v2_migration` this is also failing with similar symptoms (see: https://tracker.ceph.com/issues/65463)

**Comment by AliMasarweh** [comment]
@yuvalif, since https://github.com/ceph/ceph/pull/57537 was merged,
we no longer need the fix for **rgw_notify** and **cls_2pc_queue**,
should merge just the changes to the tests?

**Comment by yuvalif** [comment]
> @yuvalif, since #57537 was merged, we no longer need the fix for **rgw_notify** and **cls_2pc_queue**, should merge just the changes to the tests?

yes, please split the test changes to another PR.
still think we should discuss both approches in the "RGW refactoring meeting"

**Comment by AliMasarweh** [comment]
https://github.com/ceph/ceph/pull/58408

**Comment by yuvalif** [comment]
> > @yuvalif, since #57537 was merged, we no longer need the fix for **rgw_notify** and **cls_2pc_queue**, should merge just the changes to the tests?
> 
> yes, please split the test changes to another PR. still think we should discuss both approches in the "RGW refactoring meeting"

refactoring meeting summary:
* the approach in this PR breaks the "generality" of the 2pc queue, as it adds topic information into its head - in theory the 2pc queue could be used for information other than topics and notifications
*  it may be possible to fetch the tenant information for pre-squid queues from the notification information itself. so that if we get to this case: https://github.com/ceph/ceph/pull/57537/files#diff-e05836df60adf79bd9d629146b894bcd2ac828ea23a63c324e87b20cf7650d72R381
we can try and parse the entries payload and see if we can get the tenant name from there

**Pull request closed without merging**
