### PR TITLE
doc/rbd: readability and spelling

### PR DESCRIPTION
**Pull request by anthonyeleven**
doc/rbd: readability and spelling

Signed-off-by: Anthony D'Atri <anthony.datri@gmail.com>

### CODE REVIEW

**Comment by anthonyeleven** [comment]
jenkins test docs
jenkins test signed

**Comment by anthonyeleven** [comment]
@zdover23 I'm at a loss wrt the sign-off test is failing.
Or why the commit is reported as not belonging to any branch

**Comment by anthonyeleven** [comment]
jenkins test docs
jenkins test signed

**Comment by anthonyeleven** [comment]
jenkins test docs

**Comment by anthonyeleven** [comment]
jenkins test docs

**Comment by anthonyeleven** [comment]
@zdover23 Ready to go

**Review by zdover23 — APPROVED** [review]
LGTM. Good catch, especially, changing "infinite" to "vast" in the phrase "infinite scalability".

**Pull request merged**
