### PR TITLE
doc: reformat SubmittingPatches with more rst syntax

### PR DESCRIPTION
**Pull request by tchaikov**
* group some paragraphs into sections, so we can link to them via its
  html anchor.
* remove unrelated contents.
* add cross-refs.

Signed-off-by: Kefu Chai <kchai@redhat.com>

### CODE REVIEW

**Comment by tchaikov** [comment]
@smithfarm do you mind taking a look?

**Comment by smithfarm** [comment]
@tchaikov In general, I think SubmittingPatches.rst could be clearer about which patches can be submitted via email and which should (must?) be submitted via GitHub PR.

The "PREPARING AND SENDING PATCHES" heading could be changed to "PREPARING AND SUBMITTING PATCHES".

The structure of this section is odd:

1. Github pull request
2. Patch submission via ceph-devel@vger.kernel.org
3. Describe your changes. <- please drop the "." at the end
4. Separate your changes. <- please drop the "." at the end
5. Style check your changes.  <- please drop the "." at the end
6. No MIME, no links, no compression, no attachments.  Just plain text.

This last section ("6. No MIME, no links, no compression, no attachments.  Just plain text.") applies to kernel patches only and should be integrated into section 2. Patch submission via ceph-devel@vger.kernel.org - do you agree?

Also, perhaps we could reverse the order of sections 1. and 2. and rename them slightly:

1. Patch submission via ceph-devel@vger.kernel.org (for kernel patches only)
2. Github pull request (all other patches)

**Comment by tchaikov** [comment]
@smithfarm thanks for your review. the intention of this PR is mainly enabling us to link the related sections from PR reviews. i will update it tmr to address your comments.

**Comment by smithfarm** [comment]
@tchaikov Sounds good. I can make another PR for the changes you didn't intend to make in this one :-)

**Comment by tchaikov** [comment]
@smithfarm i just added a commit to remove the ending period. will leave other changes to you =)

**Comment by tchaikov** [comment]
for posterities, https://www.kernel.org/doc/Documentation/SubmittingPatches is "Documentation/SubmittingPatches from the Linux kernel".

**Comment by tchaikov** [comment]
https://www.kernel.org/doc/Documentation/SubmittingPatches is the "Documentation/SubmittingPatches from the Linux kernel".

**Pull request merged**
