### PR TITLE
mgr/ssh: reenable node labels

### PR DESCRIPTION
**Pull request by liewegas**
- fix label add/remove
- allow lables to be specified as part of 'host add'

### CODE REVIEW

**Comment by sebastian-philipp** [comment]
This is going to conflict with https://github.com/ceph/ceph/pull/32003/files#diff-c6bffa6367d17a355cf435c0aaaed88a which does the same thing

**Comment by liewegas** [comment]
> This is going to conflict with https://github.com/ceph/ceph/pull/32003/files#diff-c6bffa6367d17a355cf435c0aaaed88a which does the same thing

Oops!  Let's drop this then?

**Comment by sebastian-philipp** [comment]
> > This is going to conflict with https://github.com/ceph/ceph/pull/32003/files#diff-c6bffa6367d17a355cf435c0aaaed88a which does the same thing
> 
> Oops! Let's drop this then?

Having this as a separate PR looks good to me.  But this was the reason I haven't done this yet.

**Comment by jschmid1** [comment]
We can merge this now and I'll rebase my PR

**Comment by liewegas** [comment]
@jschmid1 want to just pull these (or whatever equivalent) into your pr?

**Comment by jschmid1** [comment]
I'll incorporate these patches into the next patches for labels and label querying

**Pull request closed without merging**
