### PR TITLE
luminous: mgr: add units to performance counters

### PR DESCRIPTION
**Pull request by epuertat**
Fixes: http://tracker.ceph.com/issues/25117

Signed-off-by: Rubab Syed<rubab.syed21@gmail.com>
(cherry picked from commit 8fb421070473ea212302f790f7da8e8939011d35)
Signed-off-by: Ernesto Puerta <epuertat@redhat.com>
    
Conflicts:
- src/messages/MMgrReport.h: keep current namespace operator (::)
- src/mon/Monitor.cc: keep metrics later removed in Mimic
- src/pybind/mgr/dashboard/module.py: add perf_counters* methods
- src/pybind/mgr/mgr_module.py: add _unit_to_str() method while keeping _perfvalue_to_value()

### CODE REVIEW

**Comment by smithfarm** [comment]
@epuertat So there were no cherry-pick conflicts?

**Comment by smithfarm** [comment]
In this case, then, the commit message should look like this:

```
mgr: add units to performance counters

Signed-off-by: Rubab Syed<rubab.syed21@gmail.com>
(cherry picked from 8fb421070473ea212302f790f7da8e8939011d35)

Conflicts:
        src/messages/MMgrReport.h
        src/mon/Monitor.cc
        src/pybind/mgr/dashboard/module.py
        src/pybind/mgr/mgr_module.py
```

**Comment by smithfarm** [comment]
@epuertat Soon this will be described in SubmittingPatches-backports.rst - for now see the draft in https://github.com/ceph/ceph/pull/22876

**Comment by epuertat** [comment]
Thanks for the tip, @smithfarm. I'll do so. How do you retain conflict info in the commit message? Just by uncommenting it before saving or there is some flag to keep it?

**Comment by smithfarm** [comment]
@epuertat AFAIK there is no flag, so I always just manually uncomment the lines. (Earlier versions of git did not comment them out - sigh.) If you find a flag to change this behavior, please let me know!

**Comment by epuertat** [comment]
@smithfarm, If I find it, sure I'll tell you ;-)

BTW I forced the push for amending the commit message. Is there any way to avoid triggering another full build and check?

Updated with:
```
Conflicts:
	src/messages/MMgrReport.h
	src/mon/Monitor.cc
	src/pybind/mgr/dashboard/module.py
	src/pybind/mgr/mgr_module.py

- All conflicts were trivial to solve. For src/messages/MMgrReport.h
  prepending '::' to encode() method was required for keeping
  the syntax followed in Luminous.
```

**Comment by smithfarm** [comment]
@epuertat Please now fix the part *above* the Conflicts section so it looks like this:

```
mgr: add units to performance counters

Signed-off-by: Rubab Syed<rubab.syed21@gmail.com>
(cherry picked from 8fb421070473ea212302f790f7da8e8939011d35)
```

Thanks. And no, all the Jenkins tests are triggered for every force-push. But don't let that stop you :-)

**Comment by jcsp** [comment]
Weirdly, I'm getting a 404 on http://tracker.ceph.com/issues/25122

**Comment by epuertat** [comment]
Teuthology run ongoing: [`teuthology-suite -v -m mira -c wip-epuertat-testing-2018-07-27-1053 -s rados:mgr --suite-branch luminous --priority 101 --suite-repo git://git.ceph.com/ceph.git --subset $(expr $RANDOM % 75)/75`](http://pulpito.ceph.com/epuertat-2018-07-30_09:04:07-rados:mgr-wip-epuertat-testing-2018-07-27-1053-distro-basic-mira/)

**Comment by smithfarm** [comment]
@epuertat Good that you are doing your own testing on this PR. Once you think it's ready, let us know and we'll queue it for integration testing.

**Comment by epuertat** [comment]
Above run caught the following issue: prometheus module relied (even in master on the method deprecated here,`_perf_value_to_value()`). Fix #21749 from @b-ranto  brings that method back, tunes it for time related perf-counters and fix an existing bug. Hence I'll backport this commit 056bc08d51306f4e4d031d1e3ff68ad7312c55d8 as well.

**Comment by b-ranto** [comment]
@epurtat The original commit 8fb421070473ea212302f790f7da8e8939011d35 that this is a back-port of did not remove the `_perfvalue_to_value()` method. It simply added the `_unit_to_str()` method to the mgr_module. I am not sure why that part got here. Anyway, the patch from me that you mentioned is (and has been) luminous for quite a while.

**Comment by epuertat** [comment]
@b-ranto you're completely right. I wrongly solved conflicts by removing the `_perfvalue_to_value` method. I'll ammend that and remove any reference to that last commit in order not to mess others with my comment. Thank you so much.

**Comment by epuertat** [comment]
@b-ranto I have to re-amend my amendment: original commit (8fb421070473ea212302f790f7da8e8939011d35) did replace `_perfvalue_to_value` with `_unit_to_str` (see https://github.com/ceph/ceph/blob/8fb421070473ea212302f790f7da8e8939011d35/src/pybind/mgr/mgr_module.py), and yours restored that method (https://github.com/ceph/ceph/commit/056bc08d51306f4e4d031d1e3ff68ad7312c55d8).

**Comment by b-ranto** [comment]
@epuertat I guess the mergetool can be confused by some of the patches being forward-ported from mimic to master. IIRC, my patch went into mimic at the time we were about to split the mimic branch so it could be related to that.

**Comment by epuertat** [comment]
This is a run of `rados:mgr` [after](http://pulpito.ceph.com/epuertat-2018-08-01_12:30:39-rados:mgr-wip-epuertat-testing-2018-07-27-1053-distro-basic-smithi/) and [before (only `rados:mgr/tasks/module_selftest.yaml`)](http://pulpito.ceph.com/epuertat-2018-08-01_14:59:01-rados:mgr:tasks:module_selftest.yaml-wip-epuertat-testing-2018-07-27-1053-distro-basic-smithi/) this PR changes. The only flapping failure in this suite is `rados:mgr/tasks/module_selftest.yaml` and happend both before & after.

**Comment by epuertat** [comment]
@smithfarm Please, could you run this through an integration suite?

@jcsp @b-ranto, I think I still need a review for this. Could you please have a look at it?

Thanks!

**Comment by jcsp** [comment]
The test run http://pulpito.ceph.com/epuertat-2018-08-01_14:59:01-rados:mgr:tasks:module_selftest.yaml-wip-epuertat-testing-2018-07-27-1053-distro-basic-smithi/  is failing because the configuration doesn't have a "roles" element, so it's asserting out on not having any mons -- probably something strange about how it was scheduled.

**Comment by yuriw** [comment]
[wip-yuri-testing-2018-08-14-1457-luminous](https://trello.com/c/0AIfErtO/373-wip-yuri-testing-2018-08-14-1457-luminous)

**Pull request merged**
