### PR TITLE
rbd: fix snapshot unprotect hang

### PR DESCRIPTION
**Pull request by dragonylffly**
Currently, when do snapshot unprotect, it will query all the other pools to check if there are some clones dependent on this snapshot. If for some reason, for example, pg inactive, the rbd_children object in some pool could not be accessed, the unprotect operation will hang. That is not elegant, since the snapshot could not be unprotected, and as a result, the volume could not be deleted, even the snapshot is independent on the inaccessible pool. This patch adds an option to allow skip querying other pools when unprotecting snapshot

### CODE REVIEW

**Comment by dragonylffly** [comment]
@dillaman this option leaves a chance for the operator to unprotect, and delete a volume per user's request, assurancing the data integrity by own

**Comment by dillaman** [comment]
@dragonylffly That's fine if you want this in a private, custom build of Ceph. However, for the general case, we have enough troubles with folks deleting pools and then complaining that we don't make it hard enough to prevent data loss. Additionally, clone v2 fixes this restriction and you probably should just fix a broken cluster instead of trying to work around it.

**Comment by tchaikov** [comment]
retest this please

**Comment by dragonylffly** [comment]
@dillaman in function int PrimaryLogPG::_delete_oid() (Line 7612, src/osd/PrimaryLogPG.cc, https://github.com/ceph/ceph/blob/master/src/osd/PrimaryLogPG.cc#L7631), as the comments shown "in luminous or later, we can't delete the head if there are clones. we trust the caller passing no_whiteout has already verified they don't exist", I think the idea is similar

**Pull request closed without merging**
