### PR TITLE
seastar: pickup change to fix cgroups V2 support

### PR DESCRIPTION
**Pull request by tchaikov**
Signed-off-by: Kefu Chai <kchai@redhat.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by tchaikov** [comment]
@liu-chunmei hopefully this change also addresses the cpuset issue you are facing. but i checked the changes between ceph/ceph-octopus-19.06.0-414-g77b23a18 and ceph/ceph-octopus-19.06.0-441-gaabb9058. nothing stands out.

**Comment by tchaikov** [comment]
i am dropping the commit of https://github.com/ceph/seastar/commit/4e0de1eabd764aff75a2780c1d3843323de21440 from our seastar branch. as i think we don't need to live with xenial 16.04 anymore.


@rzarzynski is https://github.com/ceph/seastar/commit/77b23a18613d2e7f09f749aa10061dd3ee3e6032 still needed if we can drop the support of ubuntu xenial?

**Comment by ronen-fr** [comment]
> @liu-chunmei hopefully this change also addresses the cpuset issue you are facing. but i checked the changes between ceph/ceph-octopus-19.06.0-414-g77b23a18 and ceph/ceph-octopus-19.06.0-441-gaabb9058. nothing stands out.

I don't think it would. I noticed what I think is the problem @liu-chunmei talked about - with and without the change. The problem seems to be in reactor.cc, in its handling of the intersection of the "smp" values and the cpu-sets.

**Comment by tchaikov** [comment]
jenkins test crimson perf

**Comment by tchaikov** [comment]
```
08:53:08 - DEBUG    - cbt      - Nodes : incerta08.front.sepia.ceph.com
08:53:08 - DEBUG    - cbt      - Nodes : incerta08.front.sepia.ceph.com
08:53:08 - DEBUG    - cbt      - Nodes : incerta08.front.sepia.ceph.com
08:53:08 - INFO     - cbt      - prefill/incerta08.front.sepia.ceph.com/0: bandwidth: (or (greater) (near 0.05)):: 11.4071/11.3657  => accepted
08:53:08 - INFO     - cbt      - prefill/incerta08.front.sepia.ceph.com/0: iops_avg: (or (greater) (near 0.05)):: 2920.0/2909.0  => accepted
08:53:08 - INFO     - cbt      - prefill/incerta08.front.sepia.ceph.com/0: iops_stddev: (or (less) (near 0.50)):: 186.765/155.773  => accepted
08:53:08 - INFO     - cbt      - prefill/incerta08.front.sepia.ceph.com/0: latency_avg: (or (less) (near 0.05)):: 0.00531259/0.00548196  => accepted
08:53:08 - INFO     - cbt      - prefill/incerta08.front.sepia.ceph.com/1: bandwidth: (or (greater) (near 0.05)):: 11.2421/11.4451  => accepted
08:53:08 - INFO     - cbt      - prefill/incerta08.front.sepia.ceph.com/1: iops_avg: (or (greater) (near 0.05)):: 2877.0/2929.0  => accepted
08:53:08 - INFO     - cbt      - prefill/incerta08.front.sepia.ceph.com/1: iops_stddev: (or (less) (near 0.50)):: 185.831/141.454  => accepted
08:53:08 - INFO     - cbt      - prefill/incerta08.front.sepia.ceph.com/1: latency_avg: (or (less) (near 0.05)):: 0.00545249/0.00545976  => accepted
08:53:08 - WARNING  - cbt      - rand/incerta08.front.sepia.ceph.com/0: bandwidth: (or (greater) (near 0.05)):: 48.9987/52.1024  => rejected
08:53:08 - WARNING  - cbt      - rand/incerta08.front.sepia.ceph.com/0: iops_avg: (or (greater) (near 0.05)):: 12543.0/13338.0  => rejected
08:53:08 - WARNING  - cbt      - rand/incerta08.front.sepia.ceph.com/0: iops_stddev: (or (less) (near 0.50)):: 1218.09/171.61  => rejected
08:53:08 - WARNING  - cbt      - rand/incerta08.front.sepia.ceph.com/0: latency_avg: (or (less) (near 0.05)):: 0.00126881/0.00119255  => rejected
08:53:08 - WARNING  - cbt      - rand/incerta08.front.sepia.ceph.com/1: bandwidth: (or (greater) (near 0.05)):: 49.2696/52.2923  => rejected
08:53:08 - WARNING  - cbt      - rand/incerta08.front.sepia.ceph.com/1: iops_avg: (or (greater) (near 0.05)):: 12613.0/13386.0  => rejected
08:53:08 - WARNING  - cbt      - rand/incerta08.front.sepia.ceph.com/1: iops_stddev: (or (less) (near 0.50)):: 1276.7/145.208  => rejected
08:53:08 - WARNING  - cbt      - rand/incerta08.front.sepia.ceph.com/1: latency_avg: (or (less) (near 0.05)):: 0.00126235/0.00118778  => rejected
08:53:08 - WARNING  - cbt      - 8 tests failed out of 16
```

**Comment by tchaikov** [comment]
jenkins test crimson perf

**Comment by tchaikov** [comment]
```
11:46:05 - INFO     - cbt      - prefill/incerta08.front.sepia.ceph.com/0: bandwidth: (or (greater) (near 0.05)):: 12.5102/11.8404  => accepted
11:46:05 - INFO     - cbt      - prefill/incerta08.front.sepia.ceph.com/0: iops_avg: (or (greater) (near 0.05)):: 3202.0/3031.0  => accepted
11:46:05 - INFO     - cbt      - prefill/incerta08.front.sepia.ceph.com/0: iops_stddev: (or (less) (near 0.50)):: 145.717/226.959  => accepted
11:46:05 - INFO     - cbt      - prefill/incerta08.front.sepia.ceph.com/0: latency_avg: (or (less) (near 0.05)):: 0.00497846/0.00520713  => accepted
11:46:05 - INFO     - cbt      - prefill/incerta08.front.sepia.ceph.com/1: bandwidth: (or (greater) (near 0.05)):: 12.5198/11.9132  => accepted
11:46:05 - INFO     - cbt      - prefill/incerta08.front.sepia.ceph.com/1: iops_avg: (or (greater) (near 0.05)):: 3205.0/3049.0  => accepted
11:46:05 - INFO     - cbt      - prefill/incerta08.front.sepia.ceph.com/1: iops_stddev: (or (less) (near 0.50)):: 171.607/248.87  => accepted
11:46:05 - INFO     - cbt      - prefill/incerta08.front.sepia.ceph.com/1: latency_avg: (or (less) (near 0.05)):: 0.00497036/0.00516124  => accepted
11:46:05 - WARNING  - cbt      - rand/incerta08.front.sepia.ceph.com/0: bandwidth: (or (greater) (near 0.05)):: 49.8875/52.7597  => rejected
11:46:05 - WARNING  - cbt      - rand/incerta08.front.sepia.ceph.com/0: iops_avg: (or (greater) (near 0.05)):: 12771.0/13506.0  => rejected
11:46:05 - WARNING  - cbt      - rand/incerta08.front.sepia.ceph.com/0: iops_stddev: (or (less) (near 0.50)):: 1186.53/170.039  => rejected
11:46:05 - WARNING  - cbt      - rand/incerta08.front.sepia.ceph.com/0: latency_avg: (or (less) (near 0.05)):: 0.00124509/0.00117755  => rejected
11:46:05 - WARNING  - cbt      - rand/incerta08.front.sepia.ceph.com/1: bandwidth: (or (greater) (near 0.05)):: 49.8939/52.9471  => rejected
11:46:05 - WARNING  - cbt      - rand/incerta08.front.sepia.ceph.com/1: iops_avg: (or (greater) (near 0.05)):: 12772.0/13554.0  => rejected
11:46:05 - WARNING  - cbt      - rand/incerta08.front.sepia.ceph.com/1: iops_stddev: (or (less) (near 0.50)):: 1161.97/180.928  => rejected
11:46:05 - WARNING  - cbt      - rand/incerta08.front.sepia.ceph.com/1: latency_avg: (or (less) (near 0.05)):: 0.00124367/0.00117339  => rejected
11:46:05 - WARNING  - cbt      - 8 tests failed out of 16
```

**Comment by tchaikov** [comment]
jenkins test crimson perf

**Comment by tchaikov** [comment]
```
12:37:33 - INFO     - cbt      - prefill/incerta08.front.sepia.ceph.com/0: bandwidth: (or (greater) (near 0.05)):: 18.0071/11.3671  => accepted
12:37:33 - INFO     - cbt      - prefill/incerta08.front.sepia.ceph.com/0: iops_avg: (or (greater) (near 0.05)):: 4609.0/2909.0  => accepted
12:37:33 - WARNING  - cbt      - prefill/incerta08.front.sepia.ceph.com/0: iops_stddev: (or (less) (near 0.50)):: 711.123/199.5  => rejected
12:37:33 - INFO     - cbt      - prefill/incerta08.front.sepia.ceph.com/0: latency_avg: (or (less) (near 0.05)):: 0.00339095/0.00549227  => accepted
12:37:33 - INFO     - cbt      - prefill/incerta08.front.sepia.ceph.com/1: bandwidth: (or (greater) (near 0.05)):: 18.0611/11.3108  => accepted
12:37:33 - INFO     - cbt      - prefill/incerta08.front.sepia.ceph.com/1: iops_avg: (or (greater) (near 0.05)):: 4623.0/2895.0  => accepted
12:37:33 - WARNING  - cbt      - prefill/incerta08.front.sepia.ceph.com/1: iops_stddev: (or (less) (near 0.50)):: 706.43/235.663  => rejected
12:37:33 - INFO     - cbt      - prefill/incerta08.front.sepia.ceph.com/1: latency_avg: (or (less) (near 0.05)):: 0.0033694/0.00552454  => accepted
12:37:33 - INFO     - cbt      - rand/incerta08.front.sepia.ceph.com/0: bandwidth: (or (greater) (near 0.05)):: 59.5567/51.5479  => accepted
12:37:33 - INFO     - cbt      - rand/incerta08.front.sepia.ceph.com/0: iops_avg: (or (greater) (near 0.05)):: 15246.0/13196.0  => accepted
12:37:33 - INFO     - cbt      - rand/incerta08.front.sepia.ceph.com/0: iops_stddev: (or (less) (near 0.50)):: 1368.99/950.7  => accepted
12:37:33 - INFO     - cbt      - rand/incerta08.front.sepia.ceph.com/0: latency_avg: (or (less) (near 0.05)):: 0.00104143/0.00120616  => accepted
12:37:33 - INFO     - cbt      - rand/incerta08.front.sepia.ceph.com/1: bandwidth: (or (greater) (near 0.05)):: 60.1372/51.5212  => accepted
12:37:33 - INFO     - cbt      - rand/incerta08.front.sepia.ceph.com/1: iops_avg: (or (greater) (near 0.05)):: 15395.0/13189.0  => accepted
12:37:33 - WARNING  - cbt      - rand/incerta08.front.sepia.ceph.com/1: iops_stddev: (or (less) (near 0.50)):: 1375.74/914.902  => rejected
12:37:33 - INFO     - cbt      - rand/incerta08.front.sepia.ceph.com/1: latency_avg: (or (less) (near 0.05)):: 0.00103217/0.00120517  => accepted
12:37:33 - WARNING  - cbt      - 3 tests failed out of 16
```

**Pull request merged**
