### PR TITLE
rgw: drop "realm remove" in radosgw-admin

### PR DESCRIPTION
**Pull request by shashalu**
Signed-off-by: Shasha Lu <lu.shasha@eisoo.com>

### CODE REVIEW

**Comment by shashalu** [comment]
jenkins retest this please

**Comment by joscollin** [comment]
retest this please

**Comment by shashalu** [comment]
ping @joscollin

**Comment by yuriw** [comment]
[wip-yuri-testing-2017-10-15-1718](https://trello.com/c/64UDQGrx/179-wip-yuri-testing-2017-10-15-1718)

**Pull request merged**
