### PR TITLE
ceph-volume-zfs: add the inventory command

### PR DESCRIPTION
**Pull request by wjwithagen**
```
usage: ceph-volume zfs inventory [-h] [--format {plain,json,json-pretty}]
                                 [path]

Generate an inventory of available devices

positional arguments:
  path                  Report on specific disk

optional arguments:
  -h, --help            show this help message and exit
  --format {plain,json,json-pretty}
                        Output format
```

Which genrates:
```
wjw@zfstest.digiware.nl> ceph-volume zfs inventory

/dev/Device Path      Size             rotates Model name
/dev/ada0             232.89 GB        True    ST3250318AS
/dev/ada1             232.89 GB        True    ST3250318AS
/dev/ada2             223.57 GB        False   INTEL SSDSC2BB240G6
/dev/ada3             37.27 GB         False   Corsair CSSD-F40GB2

```

or:
```
wjw@zfstest.digiware.nl> ceph-volume zfs inventory --format json-pretty ada3
[
    {
        "abspath": "/dev/ada3",
        "available": true,
        "path": "/dev/ada3",
        "reject_reasons": [],
        "sys_api": {
            "descr": "Corsair CSSD-F40GB2",
            "fwheads": "16",
            "fwsectors": "63",
            "geomname": "ada3",
            "ident": "111465010000101800EC",
            "lunid": "5000000000000236",
            "mediasize": "40018599936 ",
            "mode": "r2w2e6",
            "name": "ada3",
            "rotationrate": "0",
            "sectorsize": "512",
            "stripeoffset": "0",
            "stripesize": "4096"
        }
    }
]
```

Fixes: https://tracker.ceph.com/issues/42498
Signed-off-by: Willem Jan Withagen <wjw@digiware.nl>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`

</details>

### CODE REVIEW

**Comment by wjwithagen** [comment]
@tchaikov @alfredodeza 
I've taken the comments in #24569, and used that to implement the inventory command.
It also holds dummies for prepare and zap.

And I'll use this PR to continue further ceph-volume code. The older prepare PR will be closed.

**Comment by sebastian-philipp** [comment]
Hm, this is going to be unusable by the orchestrator (including showing the inventory in the dashboard), as everyone else will only use `ceph-volume inventory`. I'd be :+1: to add this to the existing `ceph-volume inventory` command.

**Comment by wjwithagen** [comment]
@sebastian-philipp 
Good suggestion, but I'll do that in 2 passed.
First get this in, then I'll check if I can get it into the top-level with much ado.
ATM, the orchestrator has little to orchestrate on FreeBSD

**Comment by sebastian-philipp** [comment]
> ATM, the orchestrator has little to orchestrate on FreeBSD

Sadly true. At least you'd get dashbaord support out of the box, if we get there eventually.

**Comment by wjwithagen** [comment]
@jan--f 
Oke, I'll create a tracker for this, and put Mimic and Nautilus on the backports.
Probably over the weekend.

**Comment by wjwithagen** [comment]
@jan--f 
https://tracker.ceph.com/issues/42498

**Comment by smithfarm** [comment]
@wjwithagen @jan--f This doesn't cherry-pick cleanly to mimic. I guess some earlier commits are missing:

```
Unmerged paths:
  (use "git add/rm <file>..." as appropriate to mark resolution)

        deleted by us:   src/ceph-volume/plugin/zfs/ceph_volume_zfs/__init__.py
        deleted by us:   src/ceph-volume/plugin/zfs/ceph_volume_zfs/devices/zfs/__init__.py
        deleted by us:   src/ceph-volume/plugin/zfs/ceph_volume_zfs/devices/zfs/main.py
        added by them:   src/ceph-volume/plugin/zfs/ceph_volume_zfs/zfs.py
        deleted by us:   src/ceph-volume/plugin/zfs/setup.py
```

**Comment by wjwithagen** [comment]
@smithfarm 
I see that there is no initial commits of of ceph-volume-zfs to mimic, 
Guess they did not get backported to from nautilus to mimic.
But mimic has ceph-disk to do the lifting

**Pull request merged**
