### PR TITLE
BlueStore: fix fsck and blockdevice read-relevant issue

### PR DESCRIPTION
**Pull request by xiexingguo**

### CODE REVIEW

**Comment by xiexingguo** [comment]
@liewegas   :-)

**Comment by xiexingguo** [comment]
@liewegas  All fixed as you suggested. Have a nice day:-)

**Comment by xiexingguo** [comment]
@liewegas  Sir,  you are looking at an obsolete version...

**Comment by liewegas** [comment]
Aha, yep, looks good now.  Thanks!

**Comment by xiexingguo** [comment]
@liewegas I think  that http://qa-proxy.ceph.com/teuthology/sage-2016-01-30_10:00:33-rados-wip-sage-testing2---basic-mira/52074/teuthology.log has nothing to do with this issue, it is caused by https://github.com/ceph/ceph/pull/7435

**Comment by xiexingguo** [comment]
Sorry, I mean this one: http://pulpito.ceph.com/sage-2016-01-30_10:00:33-rados-wip-sage-testing2---basic-mira/52041/

**Comment by liewegas** [comment]
os/bluestore/BlueStore.h: In function 'BlueStore::EnodeSet::~EnodeSet()' thread 7f898e2d7340 time 2016-02-01 15:33:55.930237
os/bluestore/BlueStore.h: 107: FAILED assert(uset.empty())
 ceph version 10.0.2-1518-g7d5a88e (7d5a88e2ba1a7bfd6a12ad04bb147d086ea20f28)
 1: (ceph::__ceph_assert_fail(char const*, char const*, int, char const*)+0x82) [0x7f898de8a752]
 2: (BlueStore::Collection::~Collection()+0x27a) [0x7f898db8d50a]
 3: (RefCountedObject::put()+0x46) [0x7f898db1b286]
 4: (()+0x280ab2) [0x7f898db32ab2]
 5: (std::_Hashtable<coll_t, std::pair<coll_t const, boost::intrusive_ptr<BlueStore::Collection> >, std::allocator<std::pair<coll_t const, boost::intrusive_ptr<BlueStore::Collection> > >, std::__detail::_Select1st, std::equal_to<coll_t>, std::hash<coll_t>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true> >::clear()+0x20) [0x7f898db8dc60]
 6: (BlueStore::fsck()+0x4e64) [0x7f898db78444]
 7: (BlueStore::umount()+0x83a) [0x7f898db7f28a]
 8: (StoreTest_SimpleRemount_Test::TestBody()+0x396) [0x7f898dadd686]
 9: (void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*)+0x65) [0x7f898de4fb78]
 10: (void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*)+0x4b) [0x7f898de4ae72]
 11: (testing::Test::Run()+0xd4) [0x7f898de31a58]
 12: (testing::TestInfo::Run()+0x104) [0x7f898de3225e]
 13: (testing::TestCase::Run()+0x107) [0x7f898de32937]
 14: (testing::internal::UnitTestImpl::RunAllTests()+0x2c3) [0x7f898de39485]
 15: (bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*)+0x65) [0x7f898de50f8a]

from

rm -rf c store_test_temp_dir && make ceph_test_objectstore && CEPH_ARGS="--log-file c --debug-bluestore 20 --no-log-to-stderr" ./ceph_test_objectstore --gtest_filter=ObjectStore/StoreTest.SimpleRemount/2

**Pull request merged**
