### PR TITLE
[bluestore] Improve deferred write decision

### PR DESCRIPTION
**Pull request by aclamk**
This PR addresses problem of BlueStore being very bad at following `bluestore_prefer_deferred_size` configurable.
Now one can reasonable expect that:
- IO smaller then bluestore_prefer_deferred_size will go through deferred mechanizm,
- IO greater then bluestore_prefer_deferred_size will go directly to device.

Exception is that chunk-unaligned writes are always deferred, regardless of settings.

There is unit tests for
- when write is to empty part of an object (into empty object, or into hole in object)

The case when write is over data already in object still has previous deferred logic.

========================================================
This work should not be a final work on deferred decision mechanism.
Comprehensive solution should work in the following way:
1) in do_write_data estimate how much we cannot defer (when operating on non-mutable blobs)
2) estimate cost of deferring vs non-deferring
3) perform one consistent operation for all data
Inputs to consider into decision:
1) if target blob is spread over multiple extents, reusing its extents causes HDD seeks
2) if we have some data that requires regular write, there is little cost in merging it with data that otherwise qualifies for deferred
3) if we have unaligned write, and we need to read data from HDD (not cache!) then issuing regular write right away induces no HDD seek cost

This solves https://tracker.ceph.com/issues/56488
This is alternative solution to #47241

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [x] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Review by markhpc — APPROVED** [review]
Adam and I looked over this code together today.  A couple of nits for additional comments to describe the logic, but overall I thought the changes made sense.  The only concern I have is whether or not the removal of the has_chunk2defer logic from https://github.com/ceph/ceph/pull/42725 may have unintended consequences.  It appears we added it in the first place to sort of thread the needle on making deferred writes less aggressive while still trying to detect chunks that should be deferred.  To be honest I'm having trouble following the reasoning in #42725 for how that logic was supposed to work though and find Adam's solution easier to process (but acknowledging that we will assume that the allocator is giving us contiguous ranges when making the decision regarding whether to defer).

Approving this, but would definitely like @ifed01 to take a look over it too, especially with regards to the has_chunk2defer removal.

**Comment by ljflores** [comment]
@aclamk @ifed01 I see a teuthology failure that may be related. Can you please take a look?

http://pulpito.front.sepia.ceph.com/yuriw-2022-10-19_18:35:19-rados-wip-yuri10-testing-2022-10-19-0810-distro-default-smithi/7075000/
```
2022-10-20T04:30:58.735 INFO:teuthology.orchestra.run.smithi027.stderr:available_objects: 984 in_flight_objects: 16 total objects: 1000 in_flight 16
2022-10-20T04:31:04.733 INFO:teuthology.orchestra.run.smithi027.stderr:Op 1000
2022-10-20T04:31:04.733 INFO:teuthology.orchestra.run.smithi027.stderr:available_objects: 1003 in_flight_objects: 0 total objects: 1003 in_flight 0
2022-10-20T04:31:09.784 INFO:teuthology.orchestra.run.smithi027.stderr:Op 2000
2022-10-20T04:31:09.785 INFO:teuthology.orchestra.run.smithi027.stderr:available_objects: 1005 in_flight_objects: 0 total objects: 1005 in_flight 0
2022-10-20T04:31:20.528 INFO:teuthology.orchestra.run.smithi027.stderr:Op 3000
2022-10-20T04:31:20.536 INFO:teuthology.orchestra.run.smithi027.stderr:available_objects: 999 in_flight_objects: 0 total objects: 999 in_flight 0
2022-10-20T04:31:39.280 INFO:teuthology.orchestra.run.smithi027.stderr:Op 4000
2022-10-20T04:31:39.300 INFO:teuthology.orchestra.run.smithi027.stderr:available_objects: 995 in_flight_objects: 0 total objects: 995 in_flight 0
2022-10-20T04:31:51.895 INFO:teuthology.orchestra.run.smithi027.stderr:Op 5000
2022-10-20T04:31:51.974 INFO:teuthology.orchestra.run.smithi027.stderr:available_objects: 996 in_flight_objects: 0 total objects: 996 in_flight 0
2022-10-20T04:32:02.930 INFO:teuthology.orchestra.run.smithi027.stderr:Op 6000
2022-10-20T04:32:02.930 INFO:teuthology.orchestra.run.smithi027.stderr:available_objects: 983 in_flight_objects: 0 total objects: 983 in_flight 0
2022-10-20T04:32:11.187 INFO:teuthology.orchestra.run.smithi027.stderr:Op 7000
2022-10-20T04:32:11.252 INFO:teuthology.orchestra.run.smithi027.stderr:available_objects: 983 in_flight_objects: 0 total objects: 983 in_flight 0
2022-10-20T04:32:59.214 INFO:teuthology.orchestra.run.smithi027.stderr:Op 8000
2022-10-20T04:32:59.215 INFO:teuthology.orchestra.run.smithi027.stderr:available_objects: 983 in_flight_objects: 2 total objects: 985 in_flight 2
2022-10-20T04:33:25.973 INFO:teuthology.orchestra.run.smithi027.stderr:Op 9000
2022-10-20T04:33:25.999 INFO:teuthology.orchestra.run.smithi027.stderr:available_objects: 997 in_flight_objects: 0 total objects: 997 in_flight 0
2022-10-20T04:34:07.999 INFO:teuthology.orchestra.run.smithi027.stdout:==> rm -r bluestore.test_temp_dir
2022-10-20T04:34:08.014 INFO:teuthology.orchestra.run.smithi027.stdout:[       OK ] ObjectStore/StoreTestSpecificAUSize.SyntheticMatrixNoCsum/2 (2790772 ms)
2022-10-20T04:34:08.015 INFO:teuthology.orchestra.run.smithi027.stdout:[ RUN      ] ObjectStore/StoreTestSpecificAUSize.SyntheticMatrixPreferDeferred/2
2022-10-20T04:34:11.518 INFO:teuthology.orchestra.run.smithi027.stdout:---------------------- 1 / 8 ----------------------
2022-10-20T04:34:11.518 INFO:teuthology.orchestra.run.smithi027.stdout:  bluestore_min_alloc_size = 4096
2022-10-20T04:34:11.518 INFO:teuthology.orchestra.run.smithi027.stdout:  max_write = 65536
2022-10-20T04:34:11.519 INFO:teuthology.orchestra.run.smithi027.stdout:  max_size = 1048576
2022-10-20T04:34:11.519 INFO:teuthology.orchestra.run.smithi027.stdout:  alignment = 512
2022-10-20T04:34:11.519 INFO:teuthology.orchestra.run.smithi027.stdout:  bluestore_max_blob_size = 262144
2022-10-20T04:34:11.519 INFO:teuthology.orchestra.run.smithi027.stdout:  bluestore_compression_mode = force
2022-10-20T04:34:11.520 INFO:teuthology.orchestra.run.smithi027.stdout:  bluestore_prefer_deferred_size = 32768
2022-10-20T04:34:11.520 INFO:teuthology.orchestra.run.smithi027.stderr:seeding object 0
2022-10-20T04:34:11.740 INFO:teuthology.orchestra.run.smithi027.stderr:seeding object 500
2022-10-20T04:34:11.991 INFO:teuthology.orchestra.run.smithi027.stderr:Op 0
2022-10-20T04:34:11.992 INFO:teuthology.orchestra.run.smithi027.stderr:available_objects: 1000 in_flight_objects: 0 total objects: 1000 in_flight 0
2022-10-20T04:34:14.911 INFO:teuthology.orchestra.run.smithi027.stderr:Op 1000
2022-10-20T04:34:14.923 INFO:teuthology.orchestra.run.smithi027.stderr:available_objects: 976 in_flight_objects: 0 total objects: 976 in_flight 0
2022-10-20T14:58:23.404 DEBUG:teuthology.exit:Got signal 15; running 1 handler...
2022-10-20T14:58:23.456 DEBUG:teuthology.task.console_log:Killing console logger for smithi027
2022-10-20T14:58:23.460 DEBUG:teuthology.exit:Finished running handlers
```

**Comment by ljflores** [comment]
@aclamk @ifed01 I apologize, I put the wrong teuthology link. The comment above now has the correct link.

**Comment by ormandj** [comment]
@aclamk @ifed01 @markhpc Where does this stand?

**Comment by ljflores** [comment]
@ormandj this PR is still in testing. @ifed01 @aclamk @markhpc I was suspicious of the job above, and wanted to schedule some reruns. Now that centos 8 builds are working again, I will do just that.

**Comment by aclamk** [comment]
@ljflores No problems on objectstore tests:
https://pulpito.ceph.com/akupczyk-2022-11-22_10:27:44-rados-wip-aclamk-fix-deferred-distro-default-smithi/

**Comment by ifed01** [comment]
@aclamk - overall this looks fine. But I think your solution lacks handling for a case when "too-long-for-deferring" write (length >= prefer_deferred_size) is actually fragmented and lands to a disk as a series of small physical extents - where all (or some) of them are short enough for deferring.. That's what my initial faulty implementation attempted to do and what my new implementation from https://github.com/ceph/ceph/pull/47241 is hopefully supports. Hence the additional complexity and the need for deferred write tests' updates.
Generally I'd prefer to keep that additional option but given the period this issue is on hold let's go ahead with your patch if you think the above concern isn't that important.

**Review by ifed01 — APPROVED** [review]

**Comment by ljflores** [comment]
Rados suite review:

@aclamk @ifed01 FYI I created this tracker (https://tracker.ceph.com/issues/58099) for the deferred test that we saw a failure for earlier. Adam deemed it unrelated after rerunning the test multiple times.

http://pulpito.front.sepia.ceph.com/?branch=wip-yuri10-testing-2022-10-19-0810
http://pulpito.front.sepia.ceph.com/?branch=wip-yuri10-testing-2022-11-22-1711

Failures:
    1. https://tracker.ceph.com/issues/52321
    2. https://tracker.ceph.com/issues/58096 -- new tracker; unrelated to PR in this test batch
    3. https://tracker.ceph.com/issues/57311
    4. https://tracker.ceph.com/issues/58097 -- new tracker; unrelated to PR in this test batch
    5. https://tracker.ceph.com/issues/58098 -- new tracker; unrelated to PR in this test batch
    6. https://tracker.ceph.com/issues/57731
    7. https://tracker.ceph.com/issues/57546
    8. https://tracker.ceph.com/issues/52129
    9. https://tracker.ceph.com/issues/57754
    10. https://tracker.ceph.com/issues/57755
    11. https://tracker.ceph.com/issues/58099 -- new tracker; flagged, but ultimately deemed unrelated by PR author

Details:
    1. qa/tasks/rook times out: 'check osd count' reached maximum tries (90) after waiting for 900 seconds - Ceph - Orchestrator
    2. test_cluster_set_reset_user_config: NFS mount fails due to missing ceph directory - Ceph - Orchestrator
    3. rook: ensure CRDs are installed first - Ceph - Orchestrator
    4. qa/workunits/post-file.sh: Connection reset by peer - Ceph - RADOS
    5. qa/workunits/rados/test_crash.sh: workunit checks for crashes too early - Ceph - RADOS
    6. Problem: package container-selinux conflicts with udica < 0.2.6-1 provided by udica-0.2.4-1 - Infrastructure
    7. rados/thrash-erasure-code: wait_for_recovery timeout due to "active+clean+remapped+laggy" pgs - Ceph - RADOS
    8. LibRadosWatchNotify.AioWatchDelete failed - Ceph - RADOS
    9. test_envlibrados_for_rocksdb.sh: update-alternatives: error: alternative path /usr/bin/gcc-11 doesn't exist - Infrastructure
    10. task/test_orch_cli: test_cephfs_mirror times out - Ceph - Orchestrator
    11. ObjectStore/StoreTestSpecificAUSize.SyntheticMatrixPreferDeferred/2 fails - Ceph - Bluestore

**Pull request merged**
