### PR TITLE
jewel: ceph-disk: workaround gperftool hang

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/16104

### CODE REVIEW

**Comment by athanatos** [comment]
@ldachary Is this good to merge?

**Comment by Abhishekvrshny** [comment]
test this please

**Comment by dachary** [comment]
test this please (bluefs mount crash)

**Comment by dachary** [comment]
@athanatos this is good to merge as soon as it passes an integration run.

**Comment by athanatos** [comment]
This is failing a make check check.

**Comment by athanatos** [comment]
sjust@teuthology:/a/samuelj-2016-06-08_21:51:40-rados-wip-sam-jewel-testing-distro-basic-smithi

**Pull request merged**
