### PR TITLE
osd: rename osd_delete_sleep to osd_pg_delete_sleep

### PR DESCRIPTION
**Pull request by YiteGu**
osd_delete_sleep is actually controlling the sleep time when deleting pg, osd_pg_delete_sleep makes it easier for people to understand this configuration.

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [x] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [x] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Comment by YiteGu** [comment]
jenkins test api

**Review by neha-ojha — COMMENTED** [review]
Given that `osd_delete_sleep` should no longer be useful with mclock, I am not sure we should making this change now. On a side note, this might be disruptive for existing WPQ clusters using the setting - will need to release note this.

**Comment by YiteGu** [comment]
> Given that `osd_delete_sleep` should no longer be useful with mclock, I am not sure we should making this change now. On a side note, this might be disruptive for existing WPQ clusters using the setting - will need to release note this.

I could not find where mclock disable `osd_delete_sleep` in source code. :)

**Comment by sseshasa** [comment]
> I could not find where mclock disable `osd_delete_sleep` in source code. :)

@YiteGu This is disabled in `OSD::maybe_override_sleep_options_for_qos()` by setting the sleep options to '0'.

**Comment by YiteGu** [comment]
> > I could not find where mclock disable `osd_delete_sleep` in source code. :)
> 
> @YiteGu This is disabled in `OSD::maybe_override_sleep_options_for_qos()` by setting the sleep options to '0'.

thx, I got it. BTW, do we need to consider controlling the pg concurrency num when deleting pool? similar to  osd_max_backfills.

**Pull request closed without merging**
