### PR TITLE
librbd: metadata_set API operation should not change global config setting

### PR DESCRIPTION
**Pull request by trociny**
Fixes: http://tracker.ceph.com/issues/18465
Signed-off-by: Mykola Golub <mgolub@mirantis.com>

### CODE REVIEW

**Comment by dillaman** [comment]
retest this please

**Comment by smithfarm** [comment]
@trociny This was flagged for backport to jewel, but the code it is touching in src/librbd/Operations.cc does not appear to exist in jewel.

**Comment by dillaman** [comment]
@smithfarm You can re-assign the tracker ticket to me and I'll manually port the logic changes over to jewel

**Comment by trociny** [comment]
@smithfarm @dillaman I can also do this

**Comment by smithfarm** [comment]
@trociny Any time you want to help with RBD backports, just go to http://tracker.ceph.com/projects/ceph/issues?query_id=96 and take any that are in status "Need More Info"

**Pull request merged**
