### PR TITLE
jewel: rgw: allow system users to read SLO parts

### PR DESCRIPTION
**Pull request by cbodley**
Fixes: http://tracker.ceph.com/issues/19474

### CODE REVIEW

**Comment by smithfarm** [comment]
@cbodley This PR is implicated in a "saw valgrind issues" regression http://pulpito.ceph.com/smithfarm-2017-04-27_16:58:41-rgw-wip-jewel-backports---basic-smithi/

The other PRs are the rgw-related ones in this list: http://tracker.ceph.com/issues/19538#note-48

Could you help me analyze and identify the culprit?

**Comment by cbodley** [comment]
hi @smithfarm, those certainly look like real leaks in multisite (and the failures were all in `rgw_s3tests_multiregion.yaml`), but i'm having trouble attributing them to any of the prs in that list

i've only made it through a couple of the valgrind logs so far - i'll keep looking, and hope something sticks out

**Comment by cbodley** [comment]
@smithfarm no luck with this so far. i added a potential fix from https://github.com/ceph/ceph/pull/9950 on top of that wip-jewel-backports branch, but i can't get it through teuthology - install keeps failing because of package versions.. http://pulpito.ceph.com/cbodley-2017-05-01_09:33:28-rgw-wip-jewel-backport-leaks---basic-mira/

**Comment by smithfarm** [comment]
@cbodley Another valgrind-related failure: http://qa-proxy.ceph.com/teuthology/smithfarm-2017-05-03_10:05:41-rgw-wip-rgw-support-ragweed-jewel-distro-basic-smithi/1097741/

The wip branch in this case is `wip-rgw-support-ragweed-jewel` which is just "jewel" + #14851 

The failed test is `rgw/verify/{clusters/fixed-2.yaml frontend/civetweb.yaml fs/btrfs.yaml msgr-failures/few.yaml overrides.yaml rgw_pool_type/ec-profile.yaml tasks/rgw_s3tests_multiregion.yaml validater/valgrind.yaml}`

**Comment by cbodley** [comment]
@smithfarm now that leaks have been addressed in https://github.com/ceph/ceph/pull/15382, can we please include this in the next round of testing?

**Comment by smithfarm** [comment]
@cbodley Definitely.

**Comment by theanalyst** [comment]
@yehudasa @cbodley this passed an integration run http://tracker.ceph.com/issues/19538#note-61 do you think we're ready to merge this PR to jewel?

**Comment by cbodley** [comment]
@theanalyst yes please (and thanks for resolving the valgrind failures!)

**Comment by theanalyst** [comment]
jenkins test this please

**Comment by theanalyst** [comment]
jenkins test this please

**Pull request merged**
