### PR TITLE
Improve socket admin commands for allocator.

### PR DESCRIPTION
**Pull request by aclamk**
Uses instances interface, reduces spam in 'help' command.

### CODE REVIEW

**Comment by aclamk** [comment]
It is based on https://github.com/ceph/ceph/pull/33382.

**Comment by neha-ojha** [comment]
@aclamk do you want to revisit this?

**Comment by aclamk** [comment]
jenkins make check

**Comment by aclamk** [comment]
retest this please

**Review by ifed01 — APPROVED** [review]

**Pull request closed without merging**
