### PR TITLE
osd/ReplicatedPG: snapset is not persisted

### PR DESCRIPTION
**Pull request by wonzhq**
When the new_obs doesn't exist, and the old snapset obc does exist, we
need to update the snapdir object with the latest snapset.

Signed-off-by: Zhiqiang Wang <zhiqiang.wang@intel.com>

### CODE REVIEW

**Comment by tchaikov** [comment]
@wonzhq i am not sure if i understand this change correctly. 

- before this change
  - if the new object does not exist
    - but the new snapset exists, we won't touch the snapset. i.e. we won't
      1. attach/persist the snapset to it.
    - if the new snapset does **not** exists, we will
      1. create one
      1. attach snapset info to it
      1. update its object info's timestamp, etc.
- after this change,
  - if the new object does not exist
    - no matter if the new snapset exists or not, we will
      1. make sure there is a snap object
      1. attach snapset info to it
      1. update its timestamp, etc.

IIUC, the problem addressed by this pull request is the case where
  - we are working on the head of the object which has already a snapset on disk
  - and the object does not have head anymore.
  - so seems we are removing the head of this object, and hence are resetting `snapshot.head_exists`.
  - and we are responsible to keep the snapset context updated
this renders the old logic wrong: we should always update the snapset even it exits. am i right? BTW, how did you test your change?

**Comment by tchaikov** [comment]
and could you update the commit log with what the impact of this bug? thanks.

**Comment by tchaikov** [comment]
talked with @wonzhq over IRC:
-  we should always keep the snapshot context up-to-date no matter if ".snapshot" exists or not
- the context might be carrying some other ops. but one of them removes the head object. so not updating the snapshot attribute will leave us with an updated snapshot.
- this bug was spotted when reviewing the code. we don't have a test for it so far.

**Comment by athanatos** [comment]
Hmm, I think this is essentially correct, but inaccessible since make_writeable can only be called on exists->exists, exists->non-exists, non-exists->exists.  For us to be updating the snapset on an already existing snapdir object, make_writeable would have to be called on a write which starts with the object not existing and ends with the object not existing.

**Comment by wonzhq** [comment]
@athanatos then probably this should be an assert? But I think it is still worth to do this PR since we may use the function `finish_ctx` for some other purpose in the future.

**Comment by yehudasa** [comment]
She had to a different email addresses anonymous email is

**Comment by tchaikov** [comment]
@yehudasa i don't understand your comment, are your referencing some other pull request here?

**Comment by athanatos** [comment]
This is actually wrong, apparently.  git blame indicates that this was introduced to handle 10262.  Admittedly, this is not a very clear way to handle this case.  Reverting for now.

**Pull request merged**
