### PR TITLE
doc/dev/developer_guide: verb disagreement on "Testing: Unit Tests" page

### PR DESCRIPTION
**Pull request by anthonyeleven**
doc/dev/developer_guide: Verb disagreement on "Testing: Unit Tests" page

Various additional formatting etc. cleanup as well.

Fixes: https://tracker.ceph.com/issues/46367
Signed-off-by: Anthony D'Atri <anthony.datri@gmail.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by anthonyeleven** [comment]
jenkins test make check

**Comment by anthonyeleven** [comment]
jenkins test make check

**Comment by zdover23** [comment]
jenkins render docs

**Comment by zdover23** [comment]
@anthonyeleven You and I were editing this file at the same time. We hit a lot of the same issues. (https://github.com/ceph/ceph/pull/38187)

I'll probably consume the non-overlap in a subsequent bug and close this one, crediting you in the subsequent bug as the primary author.

**Comment by anthonyeleven** [comment]
Ack.  The tracker ticket was from 5 months ago so I'd assumed (incorrectly) that it was ripe for picking.
I think https://github.com/ceph/ceph/pull/38187 needs `Fixes: https://tracker.ceph.com/issues/46367`

**Review by zdover23 — APPROVED** [review]
It's easier to merge this one and then review my own local edit to this than it would be to push the burden to you, so I'm going to merge this now.

Thanks for this!

(LG (obviously) TM)

**Comment by anthonyeleven** [comment]
Thanks!  Don't forget closing / updating https://tracker.ceph.com/issues/46367

My goal in this odyssey was to reduce the number of open tracker tickets 8^)

**Pull request merged**
