### PR TITLE
mgr/dashboard: Drop invalid RGW client instances, improve logging

### PR DESCRIPTION
**Pull request by votdev**
* Log RGW settings for easier problem tracking.
* Drop RGW client instances that do not exist anymore. This happens when a RGW service is removed via the orchestrator. The Dashboard tries to access the RGW client using the previous settings which leads to an error which might be confusing. Without dropping the error message 'RGW REST API failed request ...' is displayed instead of the correct one 'No RGW found'. Dropping the RGW client instance will produce correct error messages the next time the backend tries to establish a new connection.

Fixes: https://tracker.ceph.com/issues/48586

Before:
after_rm_rgw

After:
Peek 2020-12-02 17-29

Signed-off-by: Volker Theile <vtheile@suse.com>

## Checklist
- [x] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by avanthakkar** [comment]
jenkins test dashboard

**Comment by avanthakkar** [comment]
jenkins test make check

**Comment by callithea** [comment]
Jenkins test api

**Review by alfonsomthd — APPROVED** [review]

**Review by avanthakkar — APPROVED** [review]

**Review by nizamial09 — APPROVED** [review]

**Comment by epuertat** [comment]
@votdev could you please create a tracker issue for this and attaching it to this PR? Thanks!

**Comment by votdev** [comment]
Adapted the commit message to include the `Fixes: xxxx` line.

**Comment by votdev** [comment]
jenkins test make check

**Pull request merged**
