### PR TITLE
qa/suites/crimson-rados: Introduce performance testing

### PR DESCRIPTION
**Pull request by Matan-B**
https://pulpito.ceph.com/matan-2023-03-26_14:55:21-crimson-rados:perf-main-distro-crimson-smithi/

### TODO:
  - [x]  `collectl` is installed manually: 6d15b26b7bb3ca7dad0facaac8b7f5e8b2ba70ac
          `collectl` is required by CBT for collecting performance stats and is currently supported only on bionic (See: 
           https://github.com/ceph/ceph/pull/34161).

  - [x]   `ssh exited with exit code 255`

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [x] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [x] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Review by athanatos — APPROVED** [review]

**Comment by Matan-B** [comment]
Run LGTM - Un-drafting.
https://pulpito.ceph.com/matan-2023-03-26_14:55:21-crimson-rados:perf-main-distro-crimson-smithi/

**Comment by Matan-B** [comment]
cbt fix was merged  https://github.com/ceph/cbt/pull/283. 
d13b4274096a0776b672acce5c1413d5d95dd124 can be removed now.

**Comment by Matan-B** [comment]
Merging based on:
https://pulpito.ceph.com/matan-2023-07-04_11:44:46-crimson-rados:perf-main-distro-crimson-smithi/

**Comment by Matan-B** [comment]
Example json output results: 
http://qa-proxy.ceph.com/teuthology/matan-2023-07-04_11:44:46-crimson-rados:perf-main-distro-crimson-smithi/7326320/remote/smithi031/cbt/results/00000000/id-5928d42f/

**Comment by Matan-B** [comment]
jenkins test api

**Comment by Matan-B** [comment]
jenkins test docs

**Comment by Matan-B** [comment]
jenkins test api

**Comment by ljflores** [comment]
jenkins test api

**Comment by Matan-B** [comment]
jenkins test api

**Comment by Matan-B** [comment]
jenkins test api

**Pull request merged**
