### PR TITLE
osdc/Objecter: possible race condition with connection reset

### PR DESCRIPTION
**Pull request by dillaman**
If the connection quickly fails before the private session reference
can be associated with the connection, the connection will remain
closed and any OSD ops against the session will remain stuck.

Fixes: http://tracker.ceph.com/issues/36183
Signed-off-by: Jason Dillaman <dillaman@redhat.com>

- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by dillaman** [comment]
retest this please

**Comment by dillaman** [comment]
retest this please

**Comment by gregsfortytwo** [comment]
This LGTM but it’s not tagged for testing or anything, are you waiting on something?

**Comment by dillaman** [comment]
@gregsfortytwo Just waiting for a review first -- I've already tested that it fixed the rbd-mirror hang [1]

[1] http://pulpito.ceph.com/jdillaman-2018-09-25_22:06:18-rbd-wip-rbd-mirror-distro-basic-smithi/

**Comment by gregsfortytwo** [comment]
Reviewed-by: Greg Farnum <gfarnum@redhat.com>

**Comment by yuriw** [comment]
[wip-yuri2-testing-2018-09-27-2235](https://trello.com/c/WlK4caCc/419-wip-yuri2-testing-2018-09-27-2235)

**Comment by yuriw** [comment]
[wip-yuri2-testing-2018-10-01-2004](https://trello.com/c/7Bjs5knI/425-wip-yuri2-testing-2018-10-01-2004)

**Pull request merged**
