### PR TITLE
ceph disk for bluestore

### PR DESCRIPTION
**Pull request by dachary**

### CODE REVIEW

**Comment by xiexingguo** [comment]
@dachary Could you do me a favor of explaining me what DNM represents?  Sorry for my poor english:-)

**Comment by theanalyst** [comment]
@xiexingguo It means Do Not Merge, it is set generally when you have some work in progress code and want to receive early feedback

**Comment by xiexingguo** [comment]
@theanalyst  :+1:  Got it. Thank you so very much.

**Comment by dachary** [comment]
<code>cw ceph-qa-suite --openrc ovh-gra1-openrc.sh --simultaneous-jobs 9 --verbose --teuthology-git-url http://github.com/dachary/teuthology --teuthology-branch openstack --ceph-qa-suite-git-url http://github.com/ceph/ceph-qa-suite --suite-branch master --ceph-git-url http://github.com/dachary/ceph --ceph wip-13942-ceph-disk --suite ceph-disk --upload</code>

* *pass* http://teuthology-logs.public.ceph.com/ubuntu-2016-01-20_14:43:43-ceph-disk-wip-13942-ceph-disk---basic-openstack/

**Comment by dachary** [comment]
<code>cw ceph-qa-suite --openrc ovh-gra1-openrc.sh --simultaneous-jobs 9 --verbose --teuthology-git-url http://github.com/dachary/teuthology --teuthology-branch openstack --ceph-qa-suite-git-url http://github.com/ceph/ceph-qa-suite --suite-branch master --ceph-git-url http://github.com/dachary/ceph --ceph wip-13942-ceph-disk --suite ceph-disk --upload</code>

* *pass*  http://teuthology-logs.public.ceph.com/ubuntu-2016-01-22_08:15:57-ceph-disk-wip-13942-ceph-disk---basic-openstack/

**Comment by dachary** [comment]
@liewegas the refactor is complete (to the extent necessary for ceph-disk prepare). It took a few iterations but I like what I have now. 

The bluestore support is a draft and I stumbled into a problem: the fsid is assumed to be a sign that --mkfs has run. I worked that around with "bluestore: do not fail on a prepared device" but it has other undesirable side effects. How should we deal with this ?

**Comment by dachary** [comment]
with a rebase on the latest master, the bluestore integration tests pass. running them one last time to be sure. Ready for your review @liewegas ;-)

**Comment by dachary** [comment]
<code>cw ceph-qa-suite --verbose --teuthology-git-url http://github.com/dachary/teuthology --teuthology-branch openstack --ceph-qa-suite-git-url http://github.com/ceph/ceph-qa-suite --suite-branch master --ceph-git-url http://github.com/dachary/ceph --ceph wip-13942-ceph-disk --suite ceph-disk --upload</code>

* **running** http://167.114.232.46:8081/ubuntu-2016-02-01_12:48:11-ceph-disk-wip-13942-ceph-disk---basic-openstack/

**Comment by liewegas** [comment]
This is awesome!  Just three comments:

- let's use the 'type' file to identify existing osds
- maybe rename the 'default' in method names to 'filestore' for clarity?  and then have a small number of sites that indicate filestore is the default (e.g., if type file isn't missing).
- I think we should get rid of the weird journal wanted/needed thing.  This was originally intended to expose the backend requirements in a generic way, but it wasn't expressive enough for bluestore, and keyvaluestore is now removed anyway.  Maybe enough to simplify away the PrepareJournal?

**Comment by dachary** [comment]
@liewegas I'll address your comments, thanks for the quick review :-). There are zillions things I'd like to simplify now but I tried to keep to the minimum. Unless you think it's important I'd rather keep the want/need for this iteration. I'm semi-worried getting rid of it will create a few additional minor issues that will add delays.

**Comment by liewegas** [comment]
Yeah, sounds good!

**Comment by dachary** [comment]
@liewegas when you suggest to use type to identify the OSD, I assume it's in the context of activate where the initial proposal was to use the "osd objectstore" configure value instead. I'll change that to use the type instead, it's indeed more sensible.

**Comment by liewegas** [comment]
Right.

For create, we should either take an explicit arg (--type bluestore or 
whatever), or use the config value, or default to filestore.

**Comment by dachary** [comment]
@liewegas I grouped the changes mainly in 0c10294 except for the s/Default/Filestore/ which was done by amending "ceph-disk: refactor prepare". It passes the ceph-disk suite as shown below.

<code>cw ceph-qa-suite --verbose --teuthology-git-url http://github.com/dachary/teuthology --teuthology-branch openstack --ceph-qa-suite-git-url http://github.com/ceph/ceph-qa-suite --suite-branch master --ceph-git-url http://github.com/dachary/ceph --ceph wip-13942-ceph-disk --suite ceph-disk --upload</code>

* **pass** http://teuthology-logs.public.ceph.com/ubuntu-2016-02-01_19:09:22-ceph-disk-wip-13942-ceph-disk---basic-openstack/

**Comment by liewegas** [comment]
One small comment on the bluestore change.  Otherwise, I think this is ready for merge!

**Comment by dachary** [comment]
@liewegas fixed at 56f0809 and tests are running.

**Comment by dachary** [comment]
Proposed merge message:

<pre>
ceph-disk: add support for bluestore 

When preparing a device or a directory, the flag --bluestore can be set to select the bluestore experimental object store. It is recommended to also set the following configuration variables: osd objectstore=bluestore, enable experimental unrecoverable data corrupting features=* and bluestore block size=(partition size in bytes). The bluestore partition is set with a type specific to bluestore and new udev rules were added to run ceph-disk activate at boot time.

By default two partitions are created for a bluestore device, in the same way a filestore is split between a data and a journal partition. The bluestore data partition is small and contains administrative information. The bluestore block partition uses the rest of the disk and contains the OSD data.

Multipath devices, dmcrypt (plain or luks) are also supported for bluestore.
</pre>

**Comment by dachary** [comment]
@liewegas tests passed

**Comment by liewegas** [comment]
Is bluestore_block_size used by ceph-disk?  I don't think it should be 
mentioned as it's really for debugging/testing purposes.  (Might even be 
best to rename it to avoid confusion.)

Otherwise, looks good.

**Comment by dachary** [comment]
Proposed merge message:

ceph-disk: add support for bluestore

When preparing a device or a directory, the flag --bluestore can be set to select the bluestore experimental object store. It is recommended to also set the following configuration variables: osd objectstore=bluestore, enable experimental unrecoverable data corrupting features=* . The bluestore partition is set with a type specific to bluestore and new udev rules were added to run ceph-disk activate at boot time.

By default two partitions are created for a bluestore device, in the same way a filestore is split between a data and a journal partition. The bluestore data partition is small and contains administrative information. The bluestore block partition uses the rest of the disk and contains the OSD data.

Multipath devices, dmcrypt (plain or luks) are also supported for bluestore.

**Comment by dachary** [comment]
<code>cw ceph-qa-suite --verbose --teuthology-git-url http://github.com/dachary/teuthology --teuthology-branch openstack --ceph-qa-suite-git-url http://github.com/ceph/ceph-qa-suite --suite-branch master --ceph-git-url http://github.com/dachary/ceph --ceph wip-13942-ceph-disk --suite ceph-disk --upload</code>

* **running**  http://teuthology-logs.public.ceph.com/...

**Comment by liewegas** [comment]
:+1:

**Comment by dachary** [comment]
@liewegas ceph-disk passes but I think it deserves a rados suite to be sure.

**Comment by liewegas** [comment]
k, i'll get it in the next round.  Thanks!

**Pull request merged**
