### PR TITLE
cmake: s/HAVE_MSGHDR/WITH_SYSTEMD/

### PR DESCRIPTION
**Pull request by tchaikov**
## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Review by wjwithagen — APPROVED** [review]
Jenkins build is back to normal : ceph-master-compile #6416

**Comment by tchaikov** [comment]
```
22 - run-rbd-unit-tests-61.sh (Timeout)
```

**Comment by tchaikov** [comment]
jenkins test make check

**Comment by tchaikov** [comment]
- https://pulpito.ceph.com/kchai-2021-04-11_12:36:03-rados-wip-kefu-testing-2021-04-11-1826-distro-basic-smithi/
- https://pulpito.ceph.com/kchai-2021-04-12_02:29:32-rados-wip-kefu-testing-2021-04-12-0057-distro-basic-smithi/
- https://pulpito.ceph.com/kchai-2021-04-12_08:01:43-rados-wip-kefu-testing-2021-04-12-1256-distro-basic-smithi/

**Pull request merged**
