### PR TITLE
osd: add max-pg-per-osd limit

### PR DESCRIPTION
**Pull request by tchaikov**
osd will refused to create new pgs, until its pg number is lower
than the max-pg-per-osd upper bound setting.

Signed-off-by: Kefu Chai <kchai@redhat.com>

### CODE REVIEW

**Comment by tchaikov** [comment]
will test it further, but ready for early review.

**Comment by tchaikov** [comment]
was #17720, see http://pad.ceph.com/p/max-pgs-per-osd for more context

**Comment by tchaikov** [comment]
nvm, i still need to figure out how to poke the peering state machine the right way.

**Comment by liewegas** [comment]
@tchaikov The nice thing about updating pg_temp is that it will kick old clients and new to resend their requests.  Which means that the OSD can simply drop the requests on the floor so they won't consume memory, and be confident the clients will resend later.

Maybe instead of MOSDPGTemp, send a MMonCommand changing pg_temp, or a new message to the mon that forces it to make a pg_temp mapping change.  It almost doesnt' matter what mapping you choose.. perhaps setting it to [] even would be consistently reversed by the mon on the next epoch, triggering a new interval.  Setting it to another OSD would also work, but relies on that OSD (whoever it is) going through some peering work and deciding to switch it to something else.. less efficient.  If [] doesn't work, maybe we can adjust OSDMonitor.cc so that it does..

**Comment by tchaikov** [comment]
@liewegas thanks for the suggestion, after two day's struggle i found i've been hitting a brick wall. and found me at the brink of giving up.

will go with "MMonCommand(pg_temp)".

**Pull request closed without merging**
