### PR TITLE
octopus: mgr/dashboard: monitoring menu entry should indicate firing alerts

### PR DESCRIPTION
**Pull request by votdev**
backport tracker: https://tracker.ceph.com/issues/45324

---

backport of https://github.com/ceph/ceph/pull/34729
parent tracker: https://tracker.ceph.com/issues/43081

this backport was staged using ceph-backport.sh version 15.1.1.389
find the latest version at https://github.com/ceph/ceph/blob/master/src/script/ceph-backport.sh

### CODE REVIEW

**Comment by votdev** [comment]
> This PR introduced a bug in the translations: [tracker.ceph.com/issues/45428](https://tracker.ceph.com/issues/45428)
> I would suggest we include #34949 in this backport.

Done

**Comment by tspmelo** [comment]
This PR needs to be merged after https://github.com/ceph/ceph/pull/34850 and the cherrypick fixed.

**Comment by smithfarm** [comment]
#34729 has 1 commit, f88fb46d680127963c0d04b797b5742ada6024b4 - this is cherry picked na octopus in this PR

#34949 has 1 commit, 897e6a352d1623a045801fabcd3ddaa34bf0e498 - this one is not yet cherry-picked, right? @votdev

**Comment by smithfarm** [comment]
adding DNM for now

**Comment by votdev** [comment]
> #34729 has 1 commit, [f88fb46](https://github.com/ceph/ceph/commit/f88fb46d680127963c0d04b797b5742ada6024b4) - this is cherry picked na octopus in this PR
> 
> #34949 has 1 commit, [897e6a3](https://github.com/ceph/ceph/commit/897e6a352d1623a045801fabcd3ddaa34bf0e498) - this one is not yet cherry-picked, right? @votdev

I've reverted the previous changes and will cherry-pick the mentioned PR again when #34850 has been merged.

**Comment by yuriw** [comment]
[wip-yuri3-testing-2020-06-01-1942-octopus](https://trello.com/c/sgEs0H7r/924-wip-yuri3-testing-2020-06-01-1942-octopus)

**Comment by yuriw** [comment]
@votdev i am not sure why dashboard tests failed
Pls merge it passed rados

**Comment by votdev** [comment]
jenkins test dashboard

**Pull request merged**
