### PR TITLE
squid: cephadm/services/ingress: fixed keepalived config bug

### PR DESCRIPTION
**Pull request by adk3798**
Backport of https://github.com/ceph/ceph/pull/57848

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Comment by adk3798** [comment]
https://pulpito.ceph.com/adking-2024-08-28_12:31:37-orch:cephadm-wip-adk4-testing-2024-08-27-1806-squid-distro-default-smithi/

Failures:
- mds_upgrade_sequence timeout, known issue
- test_monitoring_stack_basic test failing after monitoring image version were updated, known issue (fix is open in main currently)
- rw-ingress tests timing out, known issue
- there was temporarily an issue with OSD deployment due to a teuthology bug. That's why some of the tests in that run appear to have no failure reason. The rest of the failures seem to fall under that.

nothing to block merging the PRs that were in the run

**Comment by adk3798** [comment]
jenkins test make check

**Comment by adk3798** [comment]
https://pulpito.ceph.com/adking-2024-11-11_04:01:43-orch:cephadm-wip-adk4-testing-2024-11-07-1210-squid-distro-default-smithi/

Failures:

- a number of upgrade tests failed due to https://tracker.ceph.com/issues/68802 as the patch hasn't been merged in the older branches the test was trying to upgrade from (it initially bootstrap with a ci image built from the tip of the branch)
- test_cephadm task failed for the same reason as the upgrade tests
- the nvmeof test actually failed for the same reason. I don't know why that test isn't using the image from the build and I'll probably change that, but that's the failure that occurred in this run
- 1 failure due to `rados/test_pool_quota.sh` failing, not familiar with the error, but looks unrelated to PRs in the run
- test_nfs task failed with
```
024-11-11T04:36:09.006 INFO:tasks.cephfs_test_runner:Traceback (most recent call last):
2024-11-11T04:36:09.006 INFO:tasks.cephfs_test_runner:  File "/home/teuthworker/src/git.ceph.com_ceph-c_5cac643e0c2c6484aecd3c481836e0c8a5cc6b15/qa/tasks/cephfs/test_nfs.py", line 1180, in test_cephfs_export_update_at_non_dir_path
2024-11-11T04:36:09.006 INFO:tasks.cephfs_test_runner:    self.update_export(self.cluster_id, "/testfile",
2024-11-11T04:36:09.006 INFO:tasks.cephfs_test_runner:AttributeError: 'TestNFS' object has no attribute 'update_export'
```
looks like an issue with the test to me.

Probably shouldn't merge anything nvmeof, nfs or upgrade related, otherwise looks okay.

**Review by phlogistonjohn — APPROVED** [review]
looks ok for backport

**Pull request merged**
