### PR TITLE
nautilus: mgr/dashboard: Unify button/URL actions naming for i…

### PR DESCRIPTION
**Pull request by tspmelo**
https://tracker.ceph.com/issues/40045

### CODE REVIEW

**Comment by tspmelo** [comment]
jenkins test dashboard

**Comment by yuriw** [comment]
[wip-yuri2-testing-2019-08-12-1528-nautilus](https://trello.com/c/d4WrRnxL/688-wip-yuri2-testing-2019-08-12-1528-nautilus)

**Comment by yuriw** [comment]
@tspmelo @epuertat this passed tests, pls rebase and merge

**Comment by tspmelo** [comment]
jenkins test docs

**Comment by LenzGr** [comment]
> @tspmelo @epuertat this passed tests, pls rebase and merge

@yuriw It's rebased and ready to merge, but probably too late for 14.2.3? No worries if it is, this is not an urgent fix.

**Comment by callithea** [comment]
QA run was successful: http://pulpito.ceph.com/laura-2019-10-28_20:19:18-rados:mgr-wip-laura-testing-nautilus-batch-distro-basic-smithi/

**Pull request merged**
