### PR TITLE
pacific: mds,client: update the oldest_client_tid via the renew caps

### PR DESCRIPTION
**Pull request by lxbsz**
backport tracker: https://tracker.ceph.com/issues/63551

---

backport of https://github.com/ceph/ceph/pull/54259
parent tracker: https://tracker.ceph.com/issues/63364

This will also backport 4 commit from https://github.com/ceph/ceph/pull/48027.

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Comment by lxbsz** [comment]
jenkins test api

**Comment by lxbsz** [comment]
jenkins test make check

**Comment by vshankar** [comment]
With this change, the MDS would still send `cap_auths` on session open reply, but the (pacific) client would be ignoring that, right?

**Comment by vshankar** [comment]
> > With this change, the MDS would still send `cap_auths` on session open reply, but the (pacific) client would be ignoring that, right?
> 
> Yeah, it should be.

We should ensure that our test covers this (old client <-> new mds, new client <-> old mds).

**Comment by vshankar** [comment]
> > > With this change, the MDS would still send `cap_auths` on session open reply, but the (pacific) client would be ignoring that, right?
> > 
> > 
> > Yeah, it should be.
> 
> We should ensure that our test covers this (old client <-> new mds, new client <-> old mds).

Maybe add tests which upgrade the MDS w/ client being 16.2.14 and the other way around too? @lxbsz WDYT?

**Comment by lxbsz** [comment]
> > > > With this change, the MDS would still send `cap_auths` on session open reply, but the (pacific) client would be ignoring that, right?
> > > 
> > > 
> > > Yeah, it should be.
> > 
> > 
> > We should ensure that our test covers this (old client <-> new mds, new client <-> old mds).
> 
> Maybe add tests which upgrade the MDS w/ client being 16.2.14 and the other way around too? @lxbsz WDYT?

Yeah, sound reasonable.

**Comment by vshankar** [comment]
Not marking as "needs-qa" since this is required for downstream stuff and not really to be targeted for last pacific.

**Comment by vshankar** [comment]
Converted to draft so that this isn't picked up by any chance.

**Comment by vshankar** [comment]
fs/upgrade: https://pulpito.ceph.com/vshankar-2024-01-19_09:20:35-fs:upgrade-wip-vshankar-testing-pacific-020240119.072505-testing-default-smithi/

**Comment by vshankar** [comment]
> fs/upgrade: https://pulpito.ceph.com/vshankar-2024-01-19_09:20:35-fs:upgrade-wip-vshankar-testing-pacific-020240119.072505-testing-default-smithi/

@lxbsz fs:upgrade ran successfully 👍 

I'l going through the job description to validate if the cases we discussed have been covered. I'm requesting another set of eyes (you!) to have a look.

**Review by vshankar — APPROVED** [review]
https://pulpito.ceph.com/?branch=wip-vshankar-testing-pacific-020240119.072505

LGTM. @lxbsz anything to add?

**Comment by lxbsz** [comment]
> https://pulpito.ceph.com/?branch=wip-vshankar-testing-pacific-020240119.072505
> 
> LGTM. @lxbsz anything to add?

Nothing else from my side. LGTM too.

**Comment by vshankar** [comment]
Closing as per https://github.com/ceph/ceph/pull/55139#issuecomment-1896038652

**Pull request closed without merging**
