### PR TITLE
cmake: do not link ceph-dencoder against global

### PR DESCRIPTION
**Pull request by tchaikov**
it does not use any symbol from global, so no need to link it against global.

Signed-off-by: Kefu Chai <tchaikov@gmail.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [x] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by tchaikov** [comment]
jenkins test make check

**Comment by tserong** [comment]
Just doing a test build on openSUSE...

**Review by tserong — APPROVED** [review]
LGTM, and confirmed to work on openSUSE.

**Comment by vshankar** [comment]
@tchaikov Not sure why but this seems to be causing test failures
- https://pulpito.ceph.com/vshankar-2023-01-10_14:06:28-fs-main-testing-default-smithi/7132955/
- https://pulpito.ceph.com/vshankar-2023-01-10_14:06:28-fs-main-testing-default-smithi/7132996/

Where the actual failures are due to ceph-dencoder failing with
```
023-01-10T15:26:33.131 DEBUG:teuthology.orchestra.run.smithi062:> ceph-dencoder type JournalPointer import - decode dump_json
2023-01-10T15:26:33.240 INFO:teuthology.orchestra.run.smithi062.stderr:src/tcmalloc.cc:332] Attempt to free invalid pointer 0x555c1219cd10
2023-01-10T15:26:33.247 DEBUG:teuthology.orchestra.run:got remote process result: None
```

I reverted the commit in my test branch
```
commit 843255dd155b0aee5302dd6b83e4d311ae8a3a0c (HEAD -> wip-vshankar-ceph-denc-20230111-104500, ci/wip-vshankar-ceph-denc-20230111-104500)
Author: Venky Shankar <vshankar@redhat.com>
Date:   Wed Jan 11 10:45:16 2023 +0530

    Revert "cmake: do not link ceph-dencoder against global"
    
    This reverts commit ba226465b283e5ff99d9a6f32d433122949981fd.
```

and that seems to get ceph-dencoder all back again - https://pulpito.ceph.com/vshankar-2023-01-11_08:03:00-fs-wip-vshankar-ceph-denc-20230111-104500-testing-default-smithi/ (rerun of failed,dead jobs from https://pulpito.ceph.com/vshankar-2023-01-10_14:06:28-fs-main-testing-default-smithi/).

**Comment by vshankar** [comment]
@tserong https://github.com/ceph/ceph/pull/48418#issuecomment-1378478510

Would you be able to help here?

**Comment by tserong** [comment]
@vshankar apologies for the laggy reply, I've been away. TBH I'm not sure what's going on here. I didn't see anything like that when I tested ceph-dencoder on openSUSE, but IIRC I only did `src/test/encoding/check-generated.sh` - maybe there's something different going on in the FS tests (although that's just a guess). I can try to look further next week.

**Comment by vshankar** [comment]
> @vshankar apologies for the laggy reply, I've been away. TBH I'm not sure what's going on here. I didn't see anything like that when I tested ceph-dencoder on openSUSE, but IIRC I only did `src/test/encoding/check-generated.sh` - maybe there's something different going on in the FS tests (although that's just a guess). I can try to look further next week.

Sure. Should we revert this change for now since a good number of fs suite tests fail with the ceph-dencoder exception?

**Comment by tserong** [comment]
> Sure. Should we revert this change for now since a good number of fs suite tests fail with the ceph-dencoder exception?

Yeah, probably a good idea until we can figure out what's going on.

**Pull request merged**
