### PR TITLE
rgw/rgw_file: Fix the return value of read() and readlink()

### PR DESCRIPTION
**Pull request by rosinL**
Fixes: https://tracker.ceph.com/issues/49189

Signed-off-by: Dai zhiwei <daizhiwei3@huawei.com>
Signed-off-by: luo rixin <luorixin@huawei.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by rosinL** [comment]
jenkins retest this please

**Comment by rosinL** [comment]
@mattbenjamin please help to review, thanks.

**Review by mattbenjamin — APPROVED** [review]
this looks fine--could you please create a tracker issue and reference it from the commit message, to help with backports?

**Comment by rosinL** [comment]
> this looks fine--could you please create a tracker issue and reference it from the commit message, to help with backports?

Done.

**Comment by rosinL** [comment]
jenkins retest this please

**Comment by ivancich** [comment]
> > this looks fine--could you please create a tracker issue and reference it from the commit message, to help with backports?
> 
> Done.

@rosinL, I don't see a tracker (link) in the first comment. Can you add it there?

**Comment by rosinL** [comment]
> > > this looks fine--could you please create a tracker issue and reference it from the commit message, to help with backports?
> > 
> > 
> > Done.
> 
> @rosinL, I don't see a tracker (link) in the first comment. Can you add it there?



> > > this looks fine--could you please create a tracker issue and reference it from the commit message, to help with backports?
> > 
> > 
> > Done.
> 
> @rosinL, I don't see a tracker (link) in the first comment. Can you add it there?
done

**Comment by mattbenjamin** [comment]
I'd take this for as far back as Nautilus

**Pull request merged**
