### PR TITLE
osd: wrongly placed assert and some cleanups

### PR DESCRIPTION
**Pull request by xiexingguo**

### CODE REVIEW

**Comment by dachary** [comment]
<pre>
Reviewed-by: Loic Dachary &lt;ldachary@redhat.com>
</pre>

**Comment by xiexingguo** [comment]
@dachary Some more cleanups, please review.

**Comment by xiexingguo** [comment]
@XinzeChi Fixed, thank you for your reminder.

**Comment by yuyuyu101** [comment]
please squash into one commit.

**Comment by xiexingguo** [comment]
@yuyuyu101 All of them? I'd like them stay this way as it is far more clear for tracing purpose. @dachary What do you think?

**Comment by dzafman** [comment]
@xiexingguo @dachary @yuyuyu101 The 4 commits are independent changes, so looks good to me.  My 2 cents.

**Comment by dachary** [comment]
@yuyuyu101 I tend to agree with @dzafman. Did you have a specific reason in minde when you suggested the squash ?

**Comment by yuyuyu101** [comment]
I'm just fine if remaining unchanged.

**Comment by dachary** [comment]
@yuyuyu101 cool, thanks for the confirmation :-)

**Comment by dachary** [comment]
@xiexingguo once it passes a qa run, it's good to merge IMHO. 

<pre>
Reviewed-by: Loic Dachary &lt;ldachary@redhat.com>
</pre>

**Pull request merged**
