### PR TITLE
Filestore copy:using splice instead read/write for clone

### PR DESCRIPTION
**Pull request by majianpeng**

### CODE REVIEW

**Comment by majianpeng** [comment]
@dachary . How to see the test log?  Thanks!

**Comment by dachary** [comment]
@majianpeng http://jenkins.ceph.dachary.org/job/ceph/OS=ubuntu-14.04/1274/console (the console link to the left in http://jenkins.ceph.dachary.org/job/ceph/OS=ubuntu-14.04/1274/) has the full logs.

**Comment by dachary** [comment]
Note however that the test timeout and there is no convenient way to see which one timed out. I suggest you run-make-chek.sh on a ubuntu-14.04 to repeat the problem. If it does not show... it means that's a false negative and I'll have to figure out why it happens.

**Comment by yuyuyu101** [comment]
It seemed cool. But I think we can't delete origin "_sparse_copy" implementation, I think splice won't do sparse copy and sparse copy not only provide with less data copy but occur less space. It's still important even if we use splice.
I think the smarter idea is extract "copy" codes and let sparse_copy also use splice.

**Comment by yuyuyu101** [comment]
I'm not sured the current usage about splice, but I think we can't fully trust CEPH_HAVE_SPLICE micro. CEPH_HAVE_SPLICE just told that kernel support splice, but potential local filesystem may return EINVAL if it doesn't support splice according to splice(2). And if also possible we run a binary package which compiled with splice in kernel which doesn't support splice.

Of course detecting the splice feature is a easy thing in GenericFileSystemBackend I think

**Comment by majianpeng** [comment]
@yuyuyu101  updated. Have you time review this? Thanks!

**Comment by yuyuyu101** [comment]
It looks good to me for these commits. But I checked safe_splice implementation:

Why we don't increase off_out if 'splice' return less than (len-cnt), which means we need to call 'splice' again. For example, if we first call splice(3, 0, 5, NULL, 10, 0) and return 8, we will call splice(3, 0, 5, NULL, 2, 0). Is it true that we don't change off_out argument?

ssize_t safe_splice(int fd_in, loff_t *off_in, int fd_out, loff_t *off_out,
		    size_t len, unsigned int flags)
{
  size_t cnt = 0;

  while (cnt < len) {
    ssize_t r = splice(fd_in, off_in, fd_out, off_out, len - cnt, flags);
    if (r <= 0) {
      if (r == 0) {
	// EOF
	return cnt;
      }
      if (errno == EINTR)
	continue;
      return -errno;
    }
    cnt += r;
  }
  return cnt;
}

**Comment by majianpeng** [comment]
AFAK, splice will update off_in & off_out if they are not null.

**Comment by yuyuyu101** [comment]
OK, it make sense because it use pointer argument....

**Comment by majianpeng** [comment]
@tchaikov . Have you time review this ? Thanks!

**Comment by majianpeng** [comment]
@tchaikov . Sorry for later response. updated & please review again! Thanks!

**Comment by yuyuyu101** [comment]
LGTM but it need to pass qa tests

**Comment by tchaikov** [comment]
`Reviewed-by: Kefu Chai <kchai@redhat.com>` once the qa run passes.

**Pull request merged**
