### PR TITLE
cephfs-shell: add the ability to mount a named filesystem

### PR DESCRIPTION
**Pull request by jtlayton**
This PR fixes a bug that prevents cephfs-shell from working on Fedora 35, and also adds the ability for it to mount a named fs.

Fixes: https://tracker.ceph.com/issues/50235

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Review by varshar16 — CHANGES_REQUESTED** [review]
Please update the [doc](https://docs.ceph.com/en/latest/man/8/cephfs-shell/#options) and add [qa test](https://github.com/ceph/ceph/blob/master/qa/tasks/cephfs/test_cephfs_shell.py). Otherwise looks good.

**Comment by jtlayton** [comment]
Added the doc update, but I'm unclear on what sort of test you want for this. Does the test environment create more than one named cephfs such that we can test mounting an alternate fs?

**Review by lxbsz — APPROVED** [review]
It has renamed the `use_ipython` to `include_ipy`, while the default value of it still keeps `False`. So just removing it is okay.

**Comment by lxbsz** [comment]
> It has renamed the `use_ipython` to `include_ipy`, while the default value of it still keeps `False`. So just removing it is okay.

Maybe you should add the above info to the commit comment, just in case that in future if we want to set it to `True` in cephfs-shell, then we need to consider the compatibility ?

**Comment by jtlayton** [comment]
Updated the changelog per the comment from @lxbsz .

**Comment by varshar16** [comment]
> Added the doc update, but I'm unclear on what sort of test you want for this. Does the test environment create more than one named cephfs such that we can test mounting an alternate fs?

I wanted a test in which we can mount different fs. The test environment doesn't create more than one fs. Can you please create a tracker ticket for it ?

**Review by varshar16 — APPROVED** [review]

**Comment by jtlayton** [comment]
Tracker for multifs qa testing for cephfs-shell here: https://tracker.ceph.com/issues/53649

**Pull request merged**
