### PR TITLE
OSD: drop unsed parameter passed to check_osdmap_features

### PR DESCRIPTION
**Pull request by zealoussnow**
Signed-off-by: Leo Zhang <nguzcf@gmail.com>

### CODE REVIEW

**Comment by zealoussnow** [comment]
@liewegas need a review please.

**Comment by liewegas** [comment]
Hmm, if this compiled before, that means the argument isn't used, right?  Can we just drop it?

**Comment by zealoussnow** [comment]
I think we can't drop this parameter, https://github.com/ceph/ceph/blob/master/src/osd/OSD.cc#L7723 use it.

**Comment by xiexingguo** [comment]
> I think we can't drop this parameter, https://github.com/ceph/ceph/blob/master/src/osd/OSD.cc#L7723 use it.

That is not true. It is using the internal store member there instead of the parameter passed in.
Can you simply drop that as per Sage suggesting?

**Comment by zealoussnow** [comment]
@xiexingguo OK, I know your means, thank you. I've changed it.

**Comment by tchaikov** [comment]
http://pulpito.ceph.com/kchai-2017-10-24_16:44:55-rados-wip-kefu-testing-2017-10-24-2303-distro-basic-mira/

the failed tests are due to https://github.com/ceph/ceph/pull/18171

**Pull request merged**
