### PR TITLE
jewel: cephfs: Journaler may execute on_safe contexts prematurely

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/20140

### CODE REVIEW

**Comment by jcsp** [comment]
@smithfarm could you rebase this please?  Looks like a relatively simple conflict in the constructor definition.

**Comment by smithfarm** [comment]
@jcsp OK, should be good to go now.

**Comment by smithfarm** [comment]
@jcsp This passed a fs suite at http://pulpito.front.sepia.ceph.com/smithfarm-2017-06-22_11:51:56-fs-wip-jewel-backports-distro-basic-smithi/ - one job failed ("Test failure: test_remote_update_write (tasks.cephfs.test_quota.TestQuota)")

**Comment by smithfarm** [comment]
@jcsp Oops, this appears to be missing 41618d8 (the second commit in #15240)

**Comment by smithfarm** [comment]
Reverted by https://github.com/ceph/ceph/pull/16282

**Pull request merged**
