### PR TITLE
infernalis: rgw:swift use Civetweb ssl can not get right url

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/13717

### CODE REVIEW

**Comment by Abhishekvrshny** [comment]
@smithfarm Did the make-check bot somehow skipped over this PR?

**Comment by smithfarm** [comment]
@Abhishekvrshny Repushed. Hopefully bot will pick it up this time!

**Comment by dachary** [comment]
@smithfarm @Abhishekvrshny the make check bot had troubles at the time and skipped an number of pull requests.

**Comment by Abhishekvrshny** [comment]
@yehudasa this backport passed the rgw suite (http://pulpito.ceph.com/loic-2015-11-27_13:58:16-rgw-infernalis-backports---basic-multi/), do you think it can be merged ?

**Comment by Abhishekvrshny** [comment]
@yehudasa gentle reminder.

**Comment by dachary** [comment]
@yehudasa does this backport look good to merge ? It passed a run of the infernalis rgw suite ( see http://tracker.ceph.com/issues/13750#note-21 ) except one occurrence of a known bug (http://tracker.ceph.com/issues/14361).

**Comment by yehudasa** [comment]
@dachary ack

**Pull request merged**
