### PR TITLE
Revert "pybind/snap_schedule: add initial interface"

### PR DESCRIPTION
**Pull request by tchaikov**
Reverts ceph/ceph#29489

see also https://tracker.ceph.com/issues/47185

### CODE REVIEW

**Comment by tchaikov** [comment]
- https://pulpito.ceph.com/kchai-2020-08-29_04:43:21-rados-wip-kefu-testing-2020-08-29-1106-distro-basic-smithi/
- https://pulpito.ceph.com/kchai-2020-08-29_13:54:19-rados-wip-kefu-testing-2020-08-29-1945-distro-basic-smithi/
- https://pulpito.ceph.com/kchai-2020-08-31_03:26:38-rados-wip-kefu-testing-2020-08-31-0934-distro-basic-smithi/

failures tracked by

- https://tracker.ceph.com/issues/47179

**Comment by tchaikov** [comment]
@sebastian-philipp could include this PR, in case you want to run rados:cephadm tests.

**Comment by sebastian-philipp** [comment]
@tchaikov https://github.com/ceph/ceph/pull/36877

**Comment by tchaikov** [comment]
> @tchaikov #36877

thank you. closing this one.

**Pull request closed without merging**
