### PR TITLE
kraken: mon/MonClient: make get_mon_log_message() atomic

### PR DESCRIPTION
**Pull request by asheplyakov**
http://tracker.ceph.com/issues/19618

### CODE REVIEW

**Comment by smithfarm** [comment]
This passed a rados suite at http://tracker.ceph.com/issues/19009#note-37 (3 tests failed initially, but passed the second time around)

**Comment by smithfarm** [comment]
What other suites (besides rados) does this need, if any?

**Comment by tchaikov** [comment]
@smithfarm rados would suffice.

**Comment by smithfarm** [comment]
@tchaikov OK, thanks!

**Pull request merged**
