### PR TITLE
mimic: rbd-mirror: handle duplicates in image sync throttler queue

### PR DESCRIPTION
**Pull request by trociny**
Backport ticket: http://tracker.ceph.com/issues/40593

Fixes: http://tracker.ceph.com/issues/40519
Signed-off-by: Mykola Golub <mgolub@suse.com>
(cherry picked from commit 2f35ab70a59fc22c02c98e5aa80a1e6cde29a226)

- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by smithfarm** [comment]
jenkins test make check

**Comment by smithfarm** [comment]
Does not compile:

```
Scanning dependencies of target librbd
[ 78%] Building CXX object src/librbd/CMakeFiles/librbd.dir/librbd.cc.o
/home/jenkins-build/build/workspace/ceph-pull-requests/src/test/rbd_mirror/test_mock_ImageSyncThrottler.cc: In member function 'virtual void rbd::mirror::TestMockImageSyncThrottler_Duplicate_Test::TestBody()':
/home/jenkins-build/build/workspace/ceph-pull-requests/src/test/rbd_mirror/test_mock_ImageSyncThrottler.cc:117:50: error: no matching function for call to 'rbd::mirror::ImageSyncThrottler<librbd::{anonymous}::MockTestImageCtx>::ImageSyncThrottler(CephContext*&)'
   MockImageSyncThrottler throttler(g_ceph_context);
                                                  ^
In file included from /home/jenkins-build/build/workspace/ceph-pull-requests/src/test/rbd_mirror/test_mock_ImageSyncThrottler.cc:33:0:
/home/jenkins-build/build/workspace/ceph-pull-requests/src/tools/rbd_mirror/ImageSyncThrottler.cc:31:1: note: candidate: rbd::mirror::ImageSyncThrottler<ImageCtxT>::ImageSyncThrottler() [with ImageCtxT = librbd::{anonymous}::MockTestImageCtx]
 ImageSyncThrottler<I>::ImageSyncThrottler()
 ^~~~~~~~~~~~~~~~~~~~~
/home/jenkins-build/build/workspace/ceph-pull-requests/src/tools/rbd_mirror/ImageSyncThrottler.cc:31:1: note:   candidate expects 0 arguments, 1 provided
/home/jenkins-build/build/workspace/ceph-pull-requests/src/test/rbd_mirror/test_mock_ImageSyncThrottler.cc: In member function 'virtual void rbd::mirror::TestMockImageSyncThrottler_Duplicate2_Test::TestBody()':
/home/jenkins-build/build/workspace/ceph-pull-requests/src/test/rbd_mirror/test_mock_ImageSyncThrottler.cc:140:50: error: no matching function for call to 'rbd::mirror::ImageSyncThrottler<librbd::{anonymous}::MockTestImageCtx>::ImageSyncThrottler(CephContext*&)'
   MockImageSyncThrottler throttler(g_ceph_context);
                                                  ^
In file included from /home/jenkins-build/build/workspace/ceph-pull-requests/src/test/rbd_mirror/test_mock_ImageSyncThrottler.cc:33:0:
/home/jenkins-build/build/workspace/ceph-pull-requests/src/tools/rbd_mirror/ImageSyncThrottler.cc:31:1: note: candidate: rbd::mirror::ImageSyncThrottler<ImageCtxT>::ImageSyncThrottler() [with ImageCtxT = librbd::{anonymous}::MockTestImageCtx]
 ImageSyncThrottler<I>::ImageSyncThrottler()
 ^~~~~~~~~~~~~~~~~~~~~
/home/jenkins-build/build/workspace/ceph-pull-requests/src/tools/rbd_mirror/ImageSyncThrottler.cc:31:1: note:   candidate expects 0 arguments, 1 provided
make[3]: *** [src/test/rbd_mirror/CMakeFiles/unittest_rbd_mirror.dir/test_mock_ImageSyncThrottler.cc.o] Error 1
make[2]: *** [src/test/rbd_mirror/CMakeFiles/unittest_rbd_mirror.dir/all] Error 2
```

**Comment by trociny** [comment]
@smithfarm fixed. Thanks.

**Comment by yuriw** [comment]
[wip-yuri5-testing-2019-07-15-1957-mimic](https://trello.com/c/C5BiJvwF/668-wip-yuri5-testing-2019-07-15-1957-mimic)

**Pull request merged**
