### PR TITLE
osd: drop the unused ECTransaction::requires_overwrite()

### PR DESCRIPTION
**Pull request by rzarzynski**
## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by rzarzynski** [comment]
```
[1995/2686] dashboard frontend dependencies are being installed
FAILED: ../src/pybind/mgr/dashboard/frontend/node_modules /home/jenkins-build/build/workspace/ceph-pull-requests/src/pybind/mgr/dashboard/frontend/node_modules 
cd /home/jenkins-build/build/workspace/ceph-pull-requests/src/pybind/mgr/dashboard/frontend && . /home/jenkins-build/build/workspace/ceph-pull-requests/build/src/pybind/mgr/dashboard/frontend/node-env/bin/activate && CYPRESS_CACHE_FOLDER=/home/jenkins-build/build/workspace/ceph-pull-requests/build/src/pybind/mgr/dashboard/cypress NG_CLI_ANALYTICS=false npm ci -f --userconfig /home/jenkins-build/build/workspace/ceph-pull-requests/build/src/pybind/mgr/dashboard/frontend/node-env/.npmrc && deactivate
npm WARN using --force I sure hope you know what you are doing.
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@applitools/logger/-/logger-1.0.4.tgz
npm ERR! 404 
npm ERR! 404  '@applitools/logger@1.0.4' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

**Comment by yuriw** [comment]
jenkins test this pls

**Comment by yuriw** [comment]
@rzarzynski can be merged when tests passed

ref: https://trello.com/c/CcKXkHLe

**Review by athanatos — APPROVED** [review]

**Comment by ljflores** [comment]
jenkins retest this please

**Comment by ljflores** [comment]
This was rados approved https://tracker.ceph.com/projects/rados/wiki/MAIN#httpstrellocomcCcKXkHLe1789-wip-yuri3-testing-2023-06-19-1518

**Comment by yuriw** [comment]
jenkins test api

**Comment by yuriw** [comment]
jenkins test api

**Pull request merged**
