### PR TITLE
qa/suites/rados/cephadm: add ubuntu 18.04 + podman to test matrix again

### PR DESCRIPTION
**Pull request by sebastian-philipp**
Podman 3 was released and it fixed a few bugs. (in addition to creating regressions again)

reverts #39087
see also #39420 

**Blocked by https://tracker.ceph.com/issues/49293**

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Review by jmolmo — APPROVED** [review]

**Review by liewegas — APPROVED** [review]

**Comment by liewegas** [comment]
```
2021-02-17T18:06:25.251 INFO:teuthology.orchestra.run.smithi180.stdout:Setting up fuse3 (3.9.0-2) ...
2021-02-17T18:06:25.293 INFO:teuthology.orchestra.run.smithi180.stdout:
2021-02-17T18:06:25.294 INFO:teuthology.orchestra.run.smithi180.stdout:Configuration file '/etc/fuse.conf'
2021-02-17T18:06:25.294 INFO:teuthology.orchestra.run.smithi180.stdout: ==> Modified (by you or by a script) since installation.
2021-02-17T18:06:25.294 INFO:teuthology.orchestra.run.smithi180.stdout: ==> Package distributor has shipped an updated version.
2021-02-17T18:06:25.294 INFO:teuthology.orchestra.run.smithi180.stdout:   What would you like to do about it ?  Your options are:
2021-02-17T18:06:25.295 INFO:teuthology.orchestra.run.smithi180.stdout:    Y or I  : install the package maintainer's version
2021-02-17T18:06:25.295 INFO:teuthology.orchestra.run.smithi180.stdout:    N or O  : keep your currently-installed version
2021-02-17T18:06:25.295 INFO:teuthology.orchestra.run.smithi180.stdout:      D     : show the differences between the versions
2021-02-17T18:06:25.295 INFO:teuthology.orchestra.run.smithi180.stdout:      Z     : start a shell to examine the situation
2021-02-17T18:06:25.295 INFO:teuthology.orchestra.run.smithi180.stdout: The default action is to keep your current version.
2021-02-17T18:06:25.296 INFO:teuthology.orchestra.run.smithi180.stdout:*** fuse.conf (Y/I/N/O/D/Z) [default=N] ? dpkg: error processing package fuse3 (--configure):
2021-02-17T18:06:25.296 INFO:teuthology.orchestra.run.smithi180.stdout: end of file on stdin at conffile prompt
2021-02-17T18:06:25.523 INFO:teuthology.orchestra.run.smithi180.stdout:dpkg: dependency problems prevent configuration of fuse-overlayfs:
2021-02-17T18:06:25.523 INFO:teuthology.orchestra.run.smithi180.stdout: fuse-overlayfs depends on fuse3; however:
2021-02-17T18:06:25.523 INFO:teuthology.orchestra.run.smithi180.stdout:  Package fuse3 is not configured yet.
2021-02-17T18:06:25.524 INFO:teuthology.orchestra.run.smithi180.stdout:
2021-02-17T18:06:25.524 INFO:teuthology.orchestra.run.smithi180.stdout:dpkg: error processing package fuse-overlayfs (--configure):
2021-02-17T18:06:25.524 INFO:teuthology.orchestra.run.smithi180.stdout: dependency problems - leaving unconfigured
2021-02-17T18:06:25.524 INFO:teuthology.orchestra.run.smithi180.stdout:Processing triggers for libc-bin (2.31-0ubuntu9.2) ...
2021-02-17T18:06:25.525 INFO:teuthology.orchestra.run.smithi180.stderr:No apport report written because the error message indicates its a followup error from a previous failure.
2021-02-17T18:06:25.588 INFO:teuthology.orchestra.run.smithi180.stdout:Processing triggers for man-db (2.9.1-1) ...
2021-02-17T18:06:28.267 INFO:teuthology.orchestra.run.smithi180.stdout:Processing triggers for initramfs-tools (0.136ubuntu6.3) ...
2021-02-17T18:06:28.359 INFO:teuthology.orchestra.run.smithi180.stdout:update-initramfs: Generating /boot/initrd.img-5.4.0-65-generic
2021-02-17T18:06:54.410 INFO:teuthology.orchestra.run.smithi180.stdout:Errors were encountered while processing:
2021-02-17T18:06:54.411 INFO:teuthology.orchestra.run.smithi180.stdout: fuse3
2021-02-17T18:06:54.411 INFO:teuthology.orchestra.run.smithi180.stdout: fuse-overlayfs
```

**Comment by liewegas** [comment]
on 18.04:
```
2021-02-21T14:30:30.628 INFO:teuthology.orchestra.run.smithi096.stderr:Pulling container image quay.ceph.io/ceph-ci/ceph:e721c0bb9ee5413f5c9f3af30b187efc368a30a0...
2021-02-21T14:30:30.628 INFO:teuthology.orchestra.run.smithi096.stderr:Running command: /usr/bin/podman pull quay.ceph.io/ceph-ci/ceph:e721c0bb9ee5413f5c9f3af30b187efc368a30a0
2021-02-21T14:30:32.188 INFO:teuthology.orchestra.run.smithi096.stderr:/usr/bin/podman: Error: failed to mount overlay for metacopy check with "nodev,metacopy=on" options: invalid argument
2021-02-21T14:30:32.191 INFO:teuthology.orchestra.run.smithi096.stderr:Non-zero exit code 125 from /usr/bin/podman pull quay.ceph.io/ceph-ci/ceph:e721c0bb9ee5413f5c9f3af30b187efc368a30a0
2021-02-21T14:30:32.192 INFO:teuthology.orchestra.run.smithi096.stderr:/usr/bin/podman: stderr Error: failed to mount overlay for metacopy check with "nodev,metacopy=on" options: invalid argument
2021-02-21T14:30:32.204 INFO:teuthology.orchestra.run.smithi096.stderr:Traceback (most recent call last):
2021-02-21T14:30:32.204 INFO:teuthology.orchestra.run.smithi096.stderr:  File "/usr/sbin/cephadm", line 7699, in <module>
2021-02-21T14:30:32.205 INFO:teuthology.orchestra.run.smithi096.stderr:    main()
2021-02-21T14:30:32.205 INFO:teuthology.orchestra.run.smithi096.stderr:  File "/usr/sbin/cephadm", line 7688, in main
2021-02-21T14:30:32.205 INFO:teuthology.orchestra.run.smithi096.stderr:    r = ctx.func(ctx)
2021-02-21T14:30:32.205 INFO:teuthology.orchestra.run.smithi096.stderr:  File "/usr/sbin/cephadm", line 1677, in _default_image
2021-02-21T14:30:32.206 INFO:teuthology.orchestra.run.smithi096.stderr:    return func(ctx)
2021-02-21T14:30:32.206 INFO:teuthology.orchestra.run.smithi096.stderr:  File "/usr/sbin/cephadm", line 3766, in command_bootstrap
2021-02-21T14:30:32.206 INFO:teuthology.orchestra.run.smithi096.stderr:    config = prepare_bootstrap_config(ctx, fsid, addr_arg, ctx.image)
2021-02-21T14:30:32.206 INFO:teuthology.orchestra.run.smithi096.stderr:  File "/usr/sbin/cephadm", line 3655, in prepare_bootstrap_config
2021-02-21T14:30:32.208 INFO:teuthology.orchestra.run.smithi096.stderr:    _pull_image(ctx, image)
2021-02-21T14:30:32.208 INFO:teuthology.orchestra.run.smithi096.stderr:  File "/usr/sbin/cephadm", line 3116, in _pull_image
2021-02-21T14:30:32.209 INFO:teuthology.orchestra.run.smithi096.stderr:    raise RuntimeError('Failed command: %s' % cmd_str)
2021-02-21T14:30:32.209 INFO:teuthology.orchestra.run.smithi096.stderr:RuntimeError: Failed command: /usr/bin/podman pull quay.ceph.io/ceph-ci/ceph:e721c0bb9ee5413f5c9f3af30b187efc368a30a0
```
20.04 tests pass
https://pulpito.ceph.com/sage-2021-02-21_14:13:11-rados:cephadm-wip-sage-testing-2021-02-20-0943-distro-basic-smithi/

**Comment by sebastian-philipp** [comment]
18:04 is this issue: https://github.com/containers/podman/issues/9363

**Comment by sebastian-philipp** [comment]
https://pulpito.ceph.com/swagner-2021-02-22_13:51:42-rados:cephadm-wip-swagner-testing-2021-02-22-1115-distro-basic-smithi/

**Comment by sebastian-philipp** [comment]
https://pulpito.ceph.com/swagner-2021-03-02_17:23:47-rados:cephadm-wip-swagner3-testing-2021-03-02-1313-distro-basic-smithi/

failed

**Comment by sebastian-philipp** [comment]
as podman is dropping support for 18.04, I don't think there is anything we can do

**Pull request closed without merging**
