### PR TITLE
common/address_help.cc: fix the leak in entity_addr_from_url()

### PR DESCRIPTION
**Pull request by qiankunzheng**
Fixes:#14132
 Signed-off-by: Qiankun Zheng <zheng.qiankun@h3c.com>

### CODE REVIEW

**Comment by yuyuyu101** [comment]
LGTM but keep commit message title within 80 chars will be better

**Comment by tchaikov** [comment]
@qiankunzheng could you update the commit message to add an before the tracker ticket number, like:
```
Fixes: #14132
```
?
and agreed with @yuyuyu101 , could also make your title more concise, something like 
```
common/address_help.cc: fix the leak in entity_addr_from_url()
```
would be better.

**Comment by qiankunzheng** [comment]
@tchaikov 
hi,i have modified this title. please review,  thanks

**Comment by qiankunzheng** [comment]
@tchaikov 
 hi,i have modified this title. please review, thanks

**Comment by tchaikov** [comment]
lgtm, would be ideal if jenkins can also nod on this. i grep'ed the repo, `entity_addr_from_url()` is not only used by {xio,simple}_{client,server}, which are not used by any of unit test or integration test.

**Comment by qiankunzheng** [comment]
@tchaikov 
can you help me merge it into the master ? thanks

**Comment by tchaikov** [comment]
@qiankunzheng sorry for the latency, the jenkins is disabled at this moment, merging it!

**Pull request merged**
