### PR TITLE
mimic: ceph-volume: add Ceph's device id to inventory

### PR DESCRIPTION
**Pull request by sebastian-philipp**
Backport of #31072

This will benefit the orchestrator and dashboard to show a unified view of devices with SMART data

Signed-off-by: Sebastian Wagner <sebastian.wagner@suse.com>
(cherry picked from commit e70d6041c1a093ed5c2b77abe17e1ede533d9659)

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`

</details>

### CODE REVIEW

**Comment by smithfarm** [comment]
@jan--f Which mimic release is this PR targeting: 13.2.7 (imminent) or 13.2.8?

**Comment by sebastian-philipp** [comment]
8?

**Comment by jan--f** [comment]
@smithfarm whatever works for the release time I'd say. No need to show horn it into 7 if that disturbs things, but it also wouldn't hurt.

**Comment by smithfarm** [comment]
If you're reasonably confident it won't break c-v in mimic, then I see no reason not to merge it now.

**Pull request merged**
