### PR TITLE
ceph-volume: minor optimizations related to class Volumes's use

### PR DESCRIPTION
**Pull request by rishabh-d-dave**
## Checklist
- [x] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test docs`
- `jenkins render docs`

</details>

### CODE REVIEW

**Comment by rishabh-d-dave** [comment]
Please let me know if the commit title can be better.

**Comment by alfredodeza** [comment]
You might want to indicate where the optimization is going to, otherwise the two commit messages look identical.

**Comment by alfredodeza** [comment]
jenkins test ceph-volume lvm all

**Comment by rishabh-d-dave** [comment]
@jan--f Are you sure about referring the ticket? I am unsure if the ticket #37940 was talking about this exact part of the codebase, although that is what I wanted to get done.

**Comment by jan--f** [comment]
@rishabh-d-dave I think if you add the same reuse patter to `single_report` we could call https://tracker.ceph.com/issues/37490 closed actually.

**Comment by jan--f** [comment]
Ideally you could also alter the unit tests to ensure `api.Volumes()` is only called once, but I'd call that optional.

**Comment by rishabh-d-dave** [comment]
@jan--f 
I've added the test but LVs list is being created thrice out which it happens twice due to fixtures (if my investigation was correct). Since one out of thrice, the first creation of the list takes place before class `Volumes` is monkey patched, the tests looks for lists to created twice.

**Comment by rishabh-d-dave** [comment]
@jan--f @alfredodeza ping

**Comment by rishabh-d-dave** [comment]
> seems like the tox tests are seeing valid failures. Is this branch rebased recently from master?

Old but not too old. Anyways, I'll rebase agin

**Comment by rishabh-d-dave** [comment]
Ok.

**Comment by alfredodeza** [comment]
@jan--f this looks fine to me, but I'll defer to you for a final approval+merge

**Pull request merged**
