### PR TITLE
rgw: remove bucket index when delete bucket

### PR DESCRIPTION
**Pull request by zhouyuan**
Bucket index object is left there when deleteing bucket. This will
result in many zero-sized objects in the cluster, especially if
bucket index sharding feature was enabled.

This patch removes the bucket index object(s) when deleteing bucket

Signed-off-by: Yuan Zhou <yuan.zhou@intel.com>

### CODE REVIEW

**Comment by zaitcev** [comment]
I like the idea. However, I disagree with returning in case get_bucket_instance_info() fails. We should continue, in case the directory has any kind of consistency issue. The same applies to the case if op.remove fails, exposed by aio->operate.

In addition, the commit has a build-time error ('ret' is undefined). I made a note in the commit comment.

Spelling "deleteing" in the commit message has to be replaced with "deteting". Second paragraph lacks the ending period.

Patch has a good idea but needs work.

P.S. I do not have enough experience in Ceph to call strongly upon this, but the asynchronous operation appears superfluous.

**Comment by zhouyuan** [comment]
@zaitcev thanks for the review! I'm actually not very sure about the approach, since @yehudasa has one commit(72ac281d7a8b548429cedd1a186e010390b65aa1) to reserve the bucket index when removing bucket. do you happen to know the background?

**Comment by zhouyuan** [comment]
@yehudasa can you share us some background of the commit (72ac281)?

**Comment by yehudasa** [comment]
@zhouyuan the bucket index also holds the bucket index log that is needed for remote zone sync. We don't want to remove the bucket index before the remote zone has been completely synced. Any solution that removes the bucket index will also need to take account of the remote zones. As a starter you can remove it if there's no data sync happening,

**Comment by yehudasa** [comment]
@zhouyuan this still doesn't address the issue where we need to keep the bucket index around

**Comment by zhouyuan** [comment]
close this since there are lots of updates on rgw

**Pull request closed without merging**
