### PR TITLE
crimson/osd/pg: make clone object's version consistent with pglog

### PR DESCRIPTION
**Pull request by xxhdx1985126**
Right now, the head object's version is 1 less than clone object's version in the pg log; while it's exactly the other way around when it comes to the versions recorded in the object info of head/clone objects

Fixes: https://tracker.ceph.com/issues/59536

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by Matan-B** [comment]
> @Matan-B thrashing tests should pretty consistently generate this crash, probably no need for specific test.

I was curious on how @xxhdx1985126 observed this crush as I haven't encountered it before.

**Comment by Matan-B** [comment]
Once make check is up again, this PR can be merged based on:

https://pulpito.ceph.com/matan-2023-04-30_16:46:54-crimson-rados-wip-matanb-crimson-only-testing-30.4-distro-crimson-smithi/
- 13/19 passed.
- Dead jobs: 
`7258784` - infra
`7258785` - infra
- Failed, known:
`7258780` - https://tracker.ceph.com/issues/59165
`7258781` - New test (tracked #50457)
`7258792` - rbd_lock_and_fence
`7258796` - rbd_python_api_tests_old_format

**Review by rzarzynski — APPROVED** [review]

**Comment by xxhdx1985126** [comment]
> I was curious on how @xxhdx1985126 observed this crush as I haven't encountered it before.

I was testing the recovery of clone objects on top of seastore:-)

Basically, I just start multiple OSDs, write data to an rbd image, and reweight one OSD to 0.

**Comment by Matan-B** [comment]
jenkins test make check

**Comment by rzarzynski** [comment]
> Basically, I just start multiple OSDs, write data to an rbd image, and reweight one OSD to 0.

Like this idea. Tiny little step for everyday development process that could cheaply screen for many problems.

**Pull request merged**
