### PR TITLE
luminous: common: fix BoundedKeyCounter const_pointer_iterator

### PR DESCRIPTION
**Pull request by pdvian**
http://tracker.ceph.com/issues/23227

### CODE REVIEW

**Comment by smithfarm** [comment]
retest this please

**Comment by smithfarm** [comment]
@cbodley Does this need both rgw and rados suites, or is just rgw sufficient?

**Comment by cbodley** [comment]
@smithfarm rgw is plenty, thanks. this one just fixed a compile error with clang

**Comment by yuriw** [comment]
[wip-yuri3-testing-2018-04-30-2145-luminous](https://trello.com/c/AuFS1qjo/302-wip-yuri3-testing-2018-04-30-2145-luminous)

**Pull request merged**
