### PR TITLE
nautilus: cmake: define BOOST_ASIO_USE_TS_EXECUTOR_AS_DEFAULT for Boost.Asio users

### PR DESCRIPTION
**Pull request by tchaikov**
for fixing the FTBFS with boost 1.74

---

see also
https://www.boost.org/doc/libs/1_74_0/doc/html/boost_asio/std_executors.html#boost_asio.std_executors.polymorphic_i_o_executor

we could use `asio::any_io_executor` later on though for better
performance.

also, define CMP0093, so FindBoost reports Boost_VERSION in x.y.z
format. it is simpler to use `VERSION_GREATER_EQUAL` to compare its
version with 1.74 instead of its C macro version ("107000").

Signed-off-by: Kefu Chai <kchai@redhat.com>
(cherry picked from commit 3d708219092d0e89a1434c30ffc8a4999f062cc0)

Conflicts:
	CMakeLists.txt
	src/librbd/CMakeLists.txt: trivial resolutions

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by Keruspe** [comment]
FWIW, I still see an error while building rgw with boost 1.74 and this patch

```
[ 41%] Building CXX object src/rgw/CMakeFiles/rgw_common.dir/rgw_sync_module_aws.cc.o                                                                                                                                                                          
cd /var/tmp/paludis/build/sys-cluster-ceph-14.2.16/work/build/src/rgw && /usr/bin/x86_64-pc-linux-gnu-c++ -D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE -D__linux__ -I/var/tmp/paludis/build/sys-cluster-ceph-14.2.16/work/build/src/include -I/var/tmp/paludis/build/sy
s-cluster-ceph-14.2.16/work/ceph-14.2.16/src -I/usr/x86_64-pc-linux-gnu/include/nss -I/usr/x86_64-pc-linux-gnu/include/nspr -I/var/tmp/paludis/build/sys-cluster-ceph-14.2.16/work/ceph-14.2.16/src/dmclock/support/src -isystem /var/tmp/paludis/build/sys-clu
ster-ceph-14.2.16/work/build/include -isystem /var/tmp/paludis/build/sys-cluster-ceph-14.2.16/work/ceph-14.2.16/src/xxHash -isystem /var/tmp/paludis/build/sys-cluster-ceph-14.2.16/work/ceph-14.2.16/src/rapidjson/include -isystem /var/tmp/paludis/build/sys
-cluster-ceph-14.2.16/work/ceph-14.2.16/src/rgw/services -march=x86-64 -pipe -O2 -Wall -Wtype-limits -Wignored-qualifiers -Winit-self -Wpointer-arith -Werror=format-security -fno-strict-aliasing -fsigned-char -Wno-unknown-pragmas -rdynamic -march=x86-64 -
pipe -O2 -ftemplate-depth-1024 -Wnon-virtual-dtor -Wno-unknown-pragmas -Wno-ignored-qualifiers -Wstrict-null-sentinel -Woverloaded-virtual -fno-new-ttp-matching -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -fstack-protector-strong -fdiagnostics-color=auto -fno-b
uiltin-malloc -fno-builtin-calloc -fno-builtin-realloc -fno-builtin-free -fPIC   -DHAVE_CONFIG_H -D__CEPH__ -D_REENTRANT -D_THREAD_SAFE -D__STDC_FORMAT_MACROS -std=c++17 -o CMakeFiles/rgw_common.dir/rgw_sync_module_aws.cc.o -c /var/tmp/paludis/build/sys-c
luster-ceph-14.2.16/work/ceph-14.2.16/src/rgw/rgw_sync_module_aws.cc                                                                                                                                                                                           
In file included from /var/tmp/paludis/build/sys-cluster-ceph-14.2.16/work/ceph-14.2.16/src/rgw/rgw_http_client.cc:16:
/var/tmp/paludis/build/sys-cluster-ceph-14.2.16/work/ceph-14.2.16/src/common/async/completion.h: In instantiation of 'void ceph::async::detail::CompletionImpl<Executor1, Handler, T, Args>::destroy_defer(std::tuple<Args ...>&&) [with Executor1 = boost::asi
o::io_context::basic_executor_type<std::allocator<void>, 0>; Handler = boost::asio::detail::coro_handler<boost::asio::executor_binder<void (*)(), boost::asio::execution::any_executor<boost::asio::execution::context_as_t<boost::asio::execution_context&>, b
oost::asio::execution::detail::blocking::never_t<0>, boost::asio::execution::prefer_only<boost::asio::execution::detail::blocking::possibly_t<0> >, boost::asio::execution::prefer_only<boost::asio::execution::detail::outstanding_work::tracked_t<0> >, boost
::asio::execution::prefer_only<boost::asio::execution::detail::outstanding_work::untracked_t<0> >, boost::asio::execution::prefer_only<boost::asio::execution::detail::relationship::fork_t<0> >, boost::asio::execution::prefer_only<boost::asio::execution::d
etail::relationship::continuation_t<0> > > >, void>; T = void; Args = {boost::system::error_code}]':                  
/var/tmp/paludis/build/sys-cluster-ceph-14.2.16/work/ceph-14.2.16/src/common/async/completion.h:188:8:   required from here                                                                                                                                    
/var/tmp/paludis/build/sys-cluster-ceph-14.2.16/work/ceph-14.2.16/src/common/async/completion.h:194:29: error: 'boost::asio::executor_work_guard<boost::asio::execution::any_executor<boost::asio::execution::context_as_t<boost::asio::execution_context&>, bo
ost::asio::execution::detail::blocking::never_t<0>, boost::asio::execution::prefer_only<boost::asio::execution::detail::blocking::possibly_t<0> >, boost::asio::execution::prefer_only<boost::asio::execution::detail::outstanding_work::tracked_t<0> >, boost:
:asio::execution::prefer_only<boost::asio::execution::detail::outstanding_work::untracked_t<0> >, boost::asio::execution::prefer_only<boost::asio::execution::detail::relationship::fork_t<0> >, boost::asio::execution::prefer_only<boost::asio::execution::de
tail::relationship::continuation_t<0> > >, void>::executor_type' {aka 'class boost::asio::execution::any_executor<boost::asio::execution::context_as_t<boost::asio::execution_context&>, boost::asio::execution::detail::blocking::never_t<0>, boost::asio::exe
cution::prefer_only<boost::asio::execution::detail::blocking::possibly_t<0> >, boost::asio::execution::prefer_only<boost::asio::execution::detail::outstanding_work::tracked_t<0> >, boost::asio::execution::prefer_only<boost::asio::execution::detail::outsta
nding_work::untracked_t<0> >, boost::asio::execution::prefer_only<boost::asio::execution::detail::relationship::fork_t<0> >, boost::asio::execution::prefer_only<boost::asio::execution::detail::relationship::continuation_t<0> > >'} has no member named 'def
er'; did you mean 'prefer'?                                                                                                                                                                                                                                    
  194 |     w.second.get_executor().defer(std::move(f), alloc2);                                                    
      |     ~~~~~~~~~~~~~~~~~~~~~~~~^~~~~                                                                                                                                                                                                                      
      |     prefer  
```

**Comment by Keruspe** [comment]
Adding the same define as in librbd to rgw fixes the build. Could you add it too? (Or do you want me to do it? Whatever's simpler for you)

**Comment by tchaikov** [comment]
@Keruspe  thanks for testing the change! i updated the PR according to your suggestion. could you give it another try?

**Comment by Keruspe** [comment]
WFM thx

**Comment by jdurgin** [comment]
fails to build on xenial: 
```
CMake Error at src/librbd/CMakeLists.txt:1 (if):
  if given arguments:

    "Boost_VERSION" "VERSION_GREATER_EQUAL" "1.74"

  Unknown arguments specified
```

**Comment by tchaikov** [comment]
@jdurgin @yuriw fixed and repushed. also, i pushed the change to ceph-ci for testing. see https://shaman.ceph.com/builds/ceph/nautilus-38263/

**Review by cbodley — APPROVED** [review]

**Pull request merged**
