### PR TITLE
msg: async: small cleanups

### PR DESCRIPTION
**Pull request by xiexingguo**

### CODE REVIEW

**Comment by xiexingguo** [comment]
@yuyuyu101  Some nits. Thanks:-)

**Comment by yuyuyu101** [comment]
lgtm

**Comment by liewegas** [comment]
2016-03-08T15:38:06.030 INFO:teuthology.orchestra.run.smithi041.stderr: in thread 7ffa377fe700
2016-03-08T15:38:06.031 INFO:teuthology.orchestra.run.smithi041.stderr:
2016-03-08T15:38:06.031 INFO:teuthology.orchestra.run.smithi041.stderr: ceph version 10.0.4-1900-gdc9f065 (dc9f06510384e4bf0bfab69b55401cc0c60e7de4)
2016-03-08T15:38:06.031 INFO:teuthology.orchestra.run.smithi041.stderr: 1: (()+0x1c154a) [0x7ffa4aa6054a]
2016-03-08T15:38:06.031 INFO:teuthology.orchestra.run.smithi041.stderr: 2: (()+0x10340) [0x7ffa49e4f340]
2016-03-08T15:38:06.031 INFO:teuthology.orchestra.run.smithi041.stderr: 3: (WorkerPool::release_worker(EventCenter*)+0x18) [0x7ffa4abec188]
2016-03-08T15:38:06.032 INFO:teuthology.orchestra.run.smithi041.stderr: 4: (AsyncConnection::~AsyncConnection()+0x89) [0x7ffa4ac7dca9]
2016-03-08T15:38:06.032 INFO:teuthology.orchestra.run.smithi041.stderr: 5: (AsyncConnection::~AsyncConnection()+0x9) [0x7ffa4ac7dfb9]
2016-03-08T15:38:06.032 INFO:teuthology.orchestra.run.smithi041.stderr: 6: (RefCountedObject::put()+0xe7) [0x7ffa4aa2cbd7]
2016-03-08T15:38:06.032 INFO:teuthology.orchestra.run.smithi041.stderr: 7: (C_clean_handler::~C_clean_handler()+0x20) [0x7ffa4ac92d60]
2016-03-08T15:38:06.032 INFO:teuthology.orchestra.run.smithi041.stderr: 8: (EventCenter::process_events(int)+0xa35) [0x7ffa4ac1fb45]
2016-03-08T15:38:06.032 INFO:teuthology.orchestra.run.smithi041.stderr: 9: (Worker::entry()+0x1e0) [0x7ffa4abeacf0]
2016-03-08T15:38:06.033 INFO:teuthology.orchestra.run.smithi041.stderr: 10: (()+0x8182) [0x7ffa49e47182]
2016-03-08T15:38:06.033 INFO:teuthology.orchestra.run.smithi041.stderr: 11: (clone()+0x6d) [0x7ffa487b847d]

on run /a/sage-2016-03-08_12:22:24-rados-wip-sage-testing---basic-smithi/47579
http://pulpito.ceph.com/sage-2016-03-08_12:22:24-rados-wip-sage-testing---basic-smithi/47579

**Comment by yuyuyu101** [comment]
@liewegas I'm really confusing by the symbol "WorkPool::release_worker", I searched the whole project and not found the definitition.

**Comment by xiexingguo** [comment]
Agree,  I've been working hard on this error for a couple of hours and don't think it has something to do with this issue...

**Comment by yuyuyu101** [comment]
http://pulpito.ceph.com/haomai-2016-03-12_12:34:10-rados-wip-haomai-testing-distro-basic-multi/

**Comment by yuyuyu101** [comment]
assert is introduced by #7843 , I will ran a qa suite again

**Comment by xiexingguo** [comment]
@yuyuyu101 :+1:

**Pull request merged**
