### PR TITLE
common/obj_bencher.cc: make verify error fatal

### PR DESCRIPTION
**Pull request by branch-predictor**
When run without "--no-verify", all verification errors are noted,
but they are not forwarded/reported anywhere else but to cerr, which
will cause automated testing to ignore them. Make seq_read_bench and
rand_read_bench return -EIO on any verification error which will,
in turn, return it back to caller (which include test_rados_tool.sh).

Fixes: #14971
Signed-off-by: Piotr Dałek <piotr.dalek@ts.fujitsu.com>

### CODE REVIEW

**Comment by dachary** [comment]
<pre>
[  FAILED  ] Buffer.constructors (2 ms)
</pre>
is the only failure.

**Comment by dachary** [comment]
@branch-predictor could you reference the tracker issue at df001c0 ?

**Comment by wjwithagen** [comment]
@branch-predictor @dachary 
I had the same error bother me in a testrun yesterday evening in #7573 
See the last red mark of all commit. Exact the same eror for code I have not touched in a long time

**Comment by branch-predictor** [comment]
@dachary done!

**Comment by dachary** [comment]
@branch-predictor now that it's in master, it can be **git cherry-pick -x** for the infernalis/hammer backports. thanks !

**Pull request merged**
