### PR TITLE
qa/tasks/mgr/test_progress.py: fix bug in 9b4dbf0

### PR DESCRIPTION
**Pull request by kamoltat**
follow-up-fix for 9b4dbf0

basically we wanna look at the list that has inprogress events and not the list that has inprogress+complete events

Fixes: http://pulpito.ceph.com/kchai-2019-07-28_14:30:09-rados-wip-kefu2-testing-2019-07-28-1941-distro-basic-mira/4160881/

Signed-off-by: Kamoltat (Junior) Sirivadhna <ksirivad@redhat.com>

- [x] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by kamoltat** [comment]
https://github.com/ceph/ceph/pull/29368

**Comment by tchaikov** [comment]
http://pulpito.ceph.com/kchai-2019-07-30_05:20:11-rados-master-distro-basic-smithi/

**Comment by tchaikov** [comment]
```
2019-07-30T05:37:43.148 INFO:tasks.cephfs_test_runner:
2019-07-30T05:37:43.148 INFO:tasks.cephfs_test_runner:======================================================================
2019-07-30T05:37:43.148 INFO:tasks.cephfs_test_runner:ERROR: test_osd_came_back (tasks.mgr.test_progress.TestProgress)
2019-07-30T05:37:43.148 INFO:tasks.cephfs_test_runner:----------------------------------------------------------------------
2019-07-30T05:37:43.148 INFO:tasks.cephfs_test_runner:Traceback (most recent call last):
2019-07-30T05:37:43.148 INFO:tasks.cephfs_test_runner:  File "/home/teuthworker/src/github.com_kamoltat_ceph_wip-qa-tasks-mgr-test-progress-bug-fix/qa/tasks/mgr/test_progress.py", line 202, in test_osd_came_back
2019-07-30T05:37:43.149 INFO:tasks.cephfs_test_runner:    ev2 = self._simulate_back_in([0], ev1)
2019-07-30T05:37:43.149 INFO:tasks.cephfs_test_runner:  File "/home/teuthworker/src/github.com_kamoltat_ceph_wip-qa-tasks-mgr-test-progress-bug-fix/qa/tasks/mgr/test_progress.py", line 128, in _simulate_back_in
2019-07-30T05:37:43.149 INFO:tasks.cephfs_test_runner:    timeout=self.EVENT_CREATION_PERIOD)
2019-07-30T05:37:43.149 INFO:tasks.cephfs_test_runner:  File "/home/teuthworker/src/github.com_kamoltat_ceph_wip-qa-tasks-mgr-test-progress-bug-fix/qa/tasks/ceph_test_case.py", line 145, in wait_until_equal
2019-07-30T05:37:43.149 INFO:tasks.cephfs_test_runner:    elapsed, expect_val, val
2019-07-30T05:37:43.149 INFO:tasks.cephfs_test_runner:RuntimeError: Timed out after 5 seconds waiting for 1 (currently 0)
```

http://pulpito.ceph.com/kchai-2019-07-30_05:20:11-rados-master-distro-basic-smithi/4164376/

**Comment by tchaikov** [comment]
@kamoltat needs rebase

**Comment by kamoltat** [comment]
Hi all sorry I made a mistake on git :(

**Comment by tchaikov** [comment]
- http://pulpito.ceph.com/kchai-2019-08-06_05:23:57-rados-wip-kefu-testing-2019-08-06-1102-distro-basic-mira/
- http://pulpito.ceph.com/kchai-2019-08-07_07:52:55-rados-wip-kefu-testing-2019-08-06-1102-distro-basic-mira/
- http://pulpito.ceph.com/kchai-2019-08-07_23:40:20-rados-wip-kefu-testing-2019-08-06-1102-distro-basic-mira/
- http://pulpito.ceph.com/kchai-2019-08-07_23:40:20-rados-wip-kefu-testing-2019-08-06-1102-distro-basic-mira/
- http://pulpito.ceph.com/kchai-2019-08-08_11:54:56-rados-wip-kefu-testing-2019-08-08-1633-distro-basic-mira/
- http://pulpito.ceph.com/kchai-2019-08-08_11:54:56-rados-wip-kefu-testing-2019-08-08-1633-distro-basic-mira/

failures are tracked by

- https://tracker.ceph.com/issues/41176
- https://tracker.ceph.com/issues/41175

**Pull request merged**
