### PR TITLE
Wip traceless reply

### PR DESCRIPTION
**Pull request by ukernel**

### CODE REVIEW

**Comment by gregsfortytwo** [comment]
I think I see what you're doing here, but I'm not clear on why we need to. Can you address that? Behavior changes like this make me nervous. ;)

**Comment by gregsfortytwo** [comment]
@liewegas any thoughts?

**Comment by ukernel** [comment]
when the kernel client receive a traceless reply for operation that creates new inode, it re-send a lookup request to get information about inode and dentry (VFS requires this). these two operation are not atomic because other client may modify the new file or move the new file to other place.

**Comment by gregsfortytwo** [comment]
Hmm. Don't the caps prevent this from happening? For another client to have modify access to the inode it must already have been committed to disk, and the kernel client must have had caps revoked.
That is, if the kclient resends a request it must not know that the request completed, which means nobody else can view the file in question.

**Comment by ukernel** [comment]
The machine that runs MDS crashes while MDS journals 'create' operation and send unsafe reply to client. The 'create' operation is successfully journaled, but the unsafe reply gets lost. Later when MDS recovers, there is no cap/lease prevents the new file from being modified.

**Comment by ukernel** [comment]
disabling early reply can make the race happen easier

**Comment by gregsfortytwo** [comment]
Is it infeasible to simply issue create-equivalent caps on the replayed op,
rather than translating it into a different op type?

Going the other direction entirely, if we do this can the MDS ever provide
a traceless reply to clients? If not we should be able to rip out all of
that handling (realistically, prepare to rip it out, because we want to
keep working with older servers).

**Comment by ukernel** [comment]
On Wed, Feb 4, 2015 at 11:44 AM, Gregory Farnum <notifications@github.com>
wrote:

> Is it infeasible to simply issue create-equivalent caps on the replayed op,
> rather than translating it into a different op type?
>

the operation that issues create-equivalent caps basically is the same as
Server::handle_client_getattr(). Besides, there already is code that
translate CREATE request into OPEN request.


>
> Going the other direction entirely, if we do this can the MDS ever provide
> a traceless reply to clients? If not we should be able to rip out all of
> that handling (realistically, prepare to rip it out, because we want to
> keep working with older servers).


With these commits, MDS still send may traceless reply for requests that do
not create new inode. But these requests need almost no special handling.

**Comment by gregsfortytwo** [comment]
A kcephfs run that includes this:  http://pulpito.ceph.com/gregf-2015-02-09_23:56:30-kcephfs-greg-fs-testing-testing-basic-multi/
That's 1 failure on infrastructure, and a lot of passes.

And fs run: http://qa-proxy.ceph.com/teuthology/gregf-2015-02-10_16:11:29-fs-greg-fs-testing2---basic-multi/
Has a number of failures, but they're all from a known OSD issue except the filelock workunit ones, which are because the kernel FUSE version was too old. Hurray!

**Pull request merged**
