### PR TITLE
rbd/cache: fix UTs related to image cache state

### PR DESCRIPTION
**Pull request by lixiaoy1**
Signed-off-by: Li, Xiaoyan <xiaoyan.li@intel.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by lixiaoy1** [comment]
@dillaman @MahatiC Please help to review.

**Comment by lixiaoy1** [comment]
This error was introduced as it changes the default value in https://github.com/ceph/ceph/pull/37625.

**Review by MahatiC — APPROVED** [review]
`TestMockCacheReplicatedWriteLog.init_state_write` doesn't fail with WITH_RBD_RWL=ON with this PR

**Review by dillaman — APPROVED** [review]
lgtm

**Pull request merged**
