### PR TITLE
Feature: Improvements to auto repair

### PR DESCRIPTION
**Pull request by dzafman**
- [x] References tracker ticket
- [x] Updates documentation if necessary
- [x] Includes tests for new functionality or reproducer for bug
- [x] Allow auto repair for bluestore
- [x] Trigger an auto repair when regular scrub detects errors
- [x] Set new "failed_repair" PG state when repairs can't fix all errors
- [ ] ~Set "failed_repair" if primary repair triggered by a client read fails~
- [x] Add a count of number of objects that are repaired to PG stats
- [x]  Add a count of number of shards that are repaired to OSD stats

### CODE REVIEW

**Comment by dzafman** [comment]
Testing passed, nothing seems related to this feature
dzafman-2019-03-20_19:53:02-rados-wip-zafman-testing-distro-basic-smithi
3754307 status 124 ceph --cluster ceph -- tell 'mon.*' injectargs --mon_health_to_clog=false. ?????
3754349 Infrastructure 
3754351 ceph-osd -i -0 exit status 1 but no messages in log. ??????
3754443 http://tracker.ceph.com/issues/38840 snaps missing in mapper, should be: ca was r -2...repaired

**Comment by neha-ojha** [comment]
> Testing passed, nothing seems related to this feature
> dzafman-2019-03-20_19:53:02-rados-wip-zafman-testing-distro-basic-smithi
> 3754307 status 124 ceph --cluster ceph -- tell 'mon.*' injectargs --mon_health_to_clog=false. ?????
> 3754349 Infrastructure
> 3754351 ceph-osd -i -0 exit status 1 but no messages in log. ??????
> 3754443 http://tracker.ceph.com/issues/38840 snaps missing in mapper, should be: ca was r -2...repaired

3754307 fails with the following error in the upgrade test, we should create a tracker for this.
2019-03-21T09:22:09.856 INFO:tasks.ceph.mon.a.smithi060.stderr:2019-03-21 09:22:09.859 7f6f9d881ec0 -1 mon.a@-1(probing) e1 current monmap has min_mon_release 15 (luminous) which is >2 releases older than me 15 (octopus), stopping.

3754351: https://tracker.ceph.com/issues/38839

**Comment by dzafman** [comment]
> 3754307 fails with the following error in the upgrade test, we should create a tracker for this.

3754307: http://tracker.ceph.com/issues/38845

**Comment by dzafman** [comment]
Rebased on master due to separation of doc updates that apply to prior releases.

**Comment by dzafman** [comment]
@neha-ojha I have one more change.  A new commit turns on PG_STATE_REPAIR when doing a rep_repair_primary_object() due to a read error from a client request.  This should get repair counts to be updated.  I just need a test case for this and need to see if I can do the equivalent for EC.

**Comment by dzafman** [comment]
@neha-ojha Thanks.  I'm debating whether to run another rados run after the last commit.

**Comment by dzafman** [comment]
Retest passed
http://pulpito.ceph.com/dzafman-2019-03-25_19:13:04-rados-wip-zafman-testing-distro-basic-smithi/
3 msgr issues
1 infrastructure
3773482 http://tracker.ceph.com/issues/38238

**Comment by dzafman** [comment]
@neha-ojha Ready to merge

**Pull request merged**
