### PR TITLE
tests: CentOS 7.4 is now the latest

### PR DESCRIPTION
**Pull request by smithfarm**
Signed-off-by: Nathan Cutler <ncutler@suse.com>

### CODE REVIEW

**Comment by smithfarm** [comment]
Needs backport to luminous and jewel once merged.

**Comment by yuriw** [comment]
@cbodley will repoint rgw tests to use this as well

**Comment by yuriw** [comment]
needs backport to jewel and luminous

**Comment by smithfarm** [comment]
Backports:

* luminous #17779 
* jewel #17780

**Pull request merged**
