### PR TITLE
rpm,debian: Ensure all ceph-disk runtime dependencies are declared for ceph-base

### PR DESCRIPTION
**Pull request by smithfarm**
The sgdisk and parted dependencies are not used by ceph-volume, or by anything other than ceph-disk, so move them to ceph-base.

Fixes: http://tracker.ceph.com/issues/23657

### CODE REVIEW

**Comment by alfredodeza** [comment]
Just a quick note: ceph-volume doesn't use `parted`

**Comment by smithfarm** [comment]
Changelog:

* move parted as well as gdisk
* update PR description

**Comment by smithfarm** [comment]
@alfredodeza OK, updated. What is the magic incantation to trigger ceph-volume tests on this PR?

**Comment by alfredodeza** [comment]
@smithfarm you would need to push to ceph-ci so that we can get packages build for functional tests. For reporting into this PR the branch name would need to be the same name, so that packages can appear at https://shaman.ceph.com/builds/ceph/wip-23657/

**Comment by smithfarm** [comment]
@alfredodeza OK, pushed. Now waiting for packages to build at https://shaman.ceph.com/builds/ceph/wip-23657/acf6423cf6c6a47dbf59a99052a227c229d47004/

**Comment by tchaikov** [comment]
@smithfarm it's wip-kefu-testing-2018-04-12-1450 .

**Comment by alfredodeza** [comment]
now that we've changed to disallow branches on ceph.git none of the ceph-volume jobs will work, they were depending on having branches in ceph.git (not elsewhere). This will take a while to get everything wired up correctly. I will run these tests manually from Kefu's branch/packages

**Comment by tchaikov** [comment]
http://pulpito.ceph.com/kchai-2018-04-12_15:56:07-rados-wip-kefu-testing-2018-04-12-2211-distro-basic-mira/

failed tests are 

- tracked by http://tracker.ceph.com/issues/23699
- caused by #19117, #21188
- fixed by #21406

**Comment by alfredodeza** [comment]
These changes worked for me locally.

**Comment by smithfarm** [comment]
Thanks to @tchaikov and @alfredodeza for testing.

**Pull request merged**
