### PR TITLE
librbd: ImageWatcher shouldn't block the notification thread

### PR DESCRIPTION
**Pull request by dillaman**
http://tracker.ceph.com/issues/14542

### CODE REVIEW

**Comment by jdurgin** [comment]
lgtm

**Comment by dachary** [comment]
@dillaman could you please **git cherry-pick -x 5e564ea9f869b987f3ada2465edfbe5edf9f6435** (as a replacement for e9570fc) and **git cherry-pick -x 0a3822f1559ba3fe3def6a65883b9c6c7c5a33fe** (as a replacement for 4372257) ?

For the record: 

It passed a run of the infernalis rbd suite ( see http://tracker.ceph.com/issues/13750#note-18 for details ). Note that all valgrind tests in these suites fail because of an environmental problem ( http://tracker.ceph.com/issues/14664 ).

**Comment by dillaman** [comment]
@dachary Since this bug is only present on infernalis and hammer, both commits were actually directly developed on the infernalis branch, not on master (hence why it didn't have a cherry-pick).

**Comment by dachary** [comment]
@dillaman it would be helpful to include that information into the commit message itself so that a future reader does not have to dig the PR / issues to figure it out. Thanks :-)

**Pull request merged**
