### PR TITLE
kraken: rgw: multisite: segfault after changing value of rgw_data_log_num_shards

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/18548

### CODE REVIEW

**Comment by smithfarm** [comment]
@yehudasa This passed an RGW suite at http://tracker.ceph.com/issues/19009#note-8

Please review/approve if you agree it can be merged.

**Comment by smithfarm** [comment]
@yehudasa This PR passed another RGW suite at http://tracker.ceph.com/issues/19009#note-18

Waiting for review.

**Comment by oritwas** [comment]
jenkins test this please

**Comment by smithfarm** [comment]
Jenkins re-test this please

**Pull request merged**
