### PR TITLE
FileJournal: fix return code of create method

### PR DESCRIPTION
**Pull request by xiexingguo**
Shall return negative error code instead.

Fixes: #14134
Signed-off-by: xie xingguo <xie.xingguo@zte.com.cn>

### CODE REVIEW

**Comment by xiexingguo** [comment]
@dzafman Hi, david. Could you please take a look at this, which I think is quite a simple fix. Thanks.

**Comment by dzafman** [comment]
LGTM  We could call this code clean-up and leave it at that.  Was this seen my someone or just through code inspection?  I see that in the OSD's main() it won't notice the error as it should without this change.

**Comment by xiexingguo** [comment]
@dzafman Through code inspection.

**Comment by xiexingguo** [comment]
@dzafman 
It seems that the following call stack will be problematic:
main(from ceph_osd.cc)->FileStore::mkjournal()->FileJournal::create()

You may check the following code logic

  if (mkjournal) {
    common_init_finish(g_ceph_context);
    int err = store->mkjournal();
    if (err < 0) {
      derr << TEXT_RED << " ** ERROR: error creating fresh journal " << g_conf->osd_journal
	   << " for object store " << g_conf->osd_data
	   << ": " << cpp_strerror(-err) << TEXT_NORMAL << dendl;
      exit(1);
    }
    derr << "created new journal " << g_conf->osd_journal
	 << " for object store " << g_conf->osd_data << dendl;
    exit(0);
  }

As you can see, the above code logic is not able to capture a positive error code return by mkjournal().

**Pull request merged**
