### PR TITLE
mon/MDSMonitor: return zero when mds is absent for "mds fail"

### PR DESCRIPTION
**Pull request by rishabh-d-dave**
Fixes: https://tracker.ceph.com/issues/47447

Related PR: #32581.

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Review by batrick — CHANGES_REQUESTED** [review]
Why is this a new failure due to #32581? The commit should have an explanation.

**Comment by rishabh-d-dave** [comment]
@batrick @neha-ojha 
Tests with teuthology were successful - https://pulpito.ceph.com/rishabh-2020-09-15_16:27:25-rados-wip-rishabh-fix-t-47447-distro-basic-smithi/

```
2020-09-15T16:45:55.044 INFO:teuthology.orchestra.run.smithi187.stderr:2020-09-15T16:45:55.038+0000 7fbe78920700  1 -- 172.21.15.187:0/1699250608 shutdown_connections
2020-09-15T16:45:55.044 INFO:teuthology.orchestra.run.smithi187.stderr:2020-09-15T16:45:55.038+0000 7fbe78920700  1 -- 172.21.15.187:0/1699250608 wait complete.
2020-09-15T16:45:55.055 INFO:tasks.cephfs_test_runner:test_osd_cannot_recover (tasks.mgr.test_progress.TestProgress) ... ok
2020-09-15T16:45:55.056 INFO:tasks.cephfs_test_runner:Starting test: test_osd_healthy_recovery (tasks.mgr.test_progress.TestProgress)
2020-09-15T16:45:55.057 INFO:teuthology.orchestra.run.smithi187:> sudo adjust-ulimits ceph-coverage /home/ubuntu/cephtest/archive/coverage timeout 120 ceph --cluster ceph --log-early log 'Starting test tasks.mgr.test_progress.TestProgress.test_osd_healthy_recovery'
```

**Comment by rishabh-d-dave** [comment]
jenkins test api

**Review by neha-ojha — APPROVED** [review]
LGTM with https://github.com/ceph/ceph/pull/37159#pullrequestreview-488736542 addressed

**Review by batrick — CHANGES_REQUESTED** [review]
As discussed in IRC, you changed the return value of `ceph mds fail` when the gid does not exist: https://github.com/ceph/ceph/blob/ebdb8e56e55488bf2280b4da6c370936940ee554/src/mon/MDSMonitor.cc#L1457-L1460

That's the reason why it now breaks this test. The test code you're changing should remain the same.

**Review by batrick — APPROVED** [review]

**Review by neha-ojha — APPROVED** [review]

**Comment by rishabh-d-dave** [comment]
Tests were successful - https://pulpito.ceph.com/rishabh-2020-09-16_06:06:32-rados-wip-rishabh-fix-t-47447-distro-basic-smithi/

**Review by ajarr — APPROVED** [review]

**Review by tchaikov — DISMISSED** [review]
@rishabh-d-dave could you replace "src/mon" with "mon/MDSMonitor" in the title of the commit message?

**Comment by rishabh-d-dave** [comment]
> @rishabh-d-dave could you replace "src/mon" with "mon/MDSMonitor" in the title of the commit message?

Replaced.

**Comment by batrick** [comment]
jenkins test make check

**Comment by rishabh-d-dave** [comment]
@batrick make check passed.

**Pull request merged**
