### PR TITLE
kraken: cls/rbd: remove incompatible group features from partial implementation

### PR DESCRIPTION
**Pull request by dillaman**
Fixes: https://tracker.ceph.com/issues/22676
Signed-off-by: Jason Dillaman <dillaman@redhat.com>
(cherry picked from commit cadd8426b358647505e950017d9a146e6f7f6696)

Conflicts:
	src/cls/rbd/cls_rbd_types.h: trivial resolution
	src/test/cls_rbd/test_cls_rbd.cc: trivial resolution

Fixes: https://tracker.ceph.com/issues/22740

### CODE REVIEW

**Comment by yuriw** [comment]
test this please

**Comment by yuriw** [comment]
@dillaman @trociny any chance we can merge it in time for 12.2.3?

**Comment by dillaman** [comment]
@yuriw it can be merged as soon as someone on the ops team fixes the broken build system for kraken. Regardless, it won’t impact the 12.2.3 release.

**Comment by alfredodeza** [comment]
The docs are breaking with what looks like valid errors:

        'enumvalue': (cpp.CPPEnumeratorObject, 'enumerator'),
    AttributeError: 'module' object has no attribute 'CPPEnumeratorObject'

**Comment by dillaman** [comment]
@alfredodeza I don't worry too much about the PR checks, but when I pushed this change to ```ceph-ci``` the builders failed to build [1]

[1] https://shaman.ceph.com/builds/ceph/wip-22740-kraken/

**Comment by alfredodeza** [comment]
@dillaman not sure how to deal with those errors, they seem valid. I am suspecting that a PR got merged that started breaking every kraken build.

**Comment by dillaman** [comment]
@alfredodeza I think it broke around the time the Jenkin build scripts were modified to support newer toolchains.

**Comment by dillaman** [comment]
... I suspect it's related to changes like this [1] that are not whitelisting kraken from using a newer version of GCC so it's falling through to act like a mimic release.

[1] https://github.com/ceph/ceph-build/commit/5c0012b8ea7c1c12a8a02640efe0220abf0de399#diff-fca3b107e8945cd175aba5640ef7360d

**Comment by cbodley** [comment]
it looks like @tchaikov got a fix for this merged upstream with https://github.com/facebook/rocksdb/pull/1757. kraken may just need a submodule update to pull that in. if a submodule update is too intrusive, we might consider a workaround like https://github.com/ceph/ceph/pull/12560 (that one was clang-only)

**Pull request closed without merging**
