### PR TITLE
doc/start/hardware-recommendations.rst: minor tweaks

### PR DESCRIPTION
**Pull request by Amrita42**
https://tracker.ceph.com/issues/42379
Hard Disk Drive: Replaced word 'accelerate' with 'optimize'
Networks: Replaced word 'have' with 'has'
Signed-off-by: Amrita Sakthivel asakthiv@redhat.com

## Checklist
- [x] References tracker ticket
- [x] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`

</details>

### CODE REVIEW

**Comment by gregsfortytwo** [comment]
Hey @Amrita42, can you update the patch with a Signed-off-by statement? https://github.com/ceph/ceph/blob/master/SubmittingPatches.rst#id1

We may be dropping this for documentation PRs but for the moment it's a necessary process bit. :)

**Comment by Amrita42** [comment]
I am new to this :) I am not sure where I am going wrong in the signed off. I have now added my surname.

**Comment by gregsfortytwo** [comment]
Ah, you need to update the commit message itself, not the PR text. This will require amending it and then doing a force push. :)

**Comment by tchaikov** [comment]
@Amrita42 please address Greg's comment. see https://github.com/ceph/ceph/blob/master/doc/dev/developer_guide/index.rst#amending-your-pr for the detailed instructions.

**Comment by Amrita42** [comment]
Hi Kefu
As I am new to the process I am stuck on how to add the sign off from CLI.

Amrita S

She

Technical Writer

Red Hat APAC Bangalore <https://www.redhat.com/>

asakthiv@redhat.com
M: 7829776516
<https://www.redhat.com/>*The world is already full of critics so instead
let's encourage each other*

**Comment by tchaikov** [comment]
@Amrita42 welcome to Ceph! indeed, the settings in CLI is a little bit involved. please see https://github.com/ceph/ceph/blob/master/doc/start/documenting-ceph.rst for instructions on how to do this step-by-step.

**Comment by gregsfortytwo** [comment]
Thanks for the patch!

**Comment by Amrita42** [comment]
Sorry for the delay in response. Thanks for helping out and merging.

**Comment by Amrita42** [comment]
Sorry for the delay in response, thanks for helping out.

**Pull request merged**
