### PR TITLE
jewel: IPv6 Heartbeat packets are not marked with DSCP QoS - simple messenger

### PR DESCRIPTION
**Pull request by shinobu-x**
http://tracker.ceph.com/issues/18958

### CODE REVIEW

**Comment by shinobu-x** [comment]
Mmm...

**Comment by shinobu-x** [comment]
The function, ``Pipe::set_socket_options`` seems not to be closed properly.

**Comment by shinobu-x** [comment]
Now should work hopefully!

**Comment by shinobu-x** [comment]
Job done!

**Comment by shinobu-x** [comment]
Original commit, ``38c283c``, was wrong.

**Comment by shinobu-x** [comment]
Original commit ``2d6021f`` is fine but picked one is wrong...

**Comment by shinobu-x** [comment]
Git wrong magic? But now it should be more fine...

**Comment by smithfarm** [comment]
Closing in favor of #13450

**Pull request closed without merging**
