### PR TITLE
jewel: the %USED of ceph df is wrong

### PR DESCRIPTION
**Pull request by dachary**
http://tracker.ceph.com/issues/17121

### CODE REVIEW

**Comment by dachary** [comment]
test this please (jenkins general failure)

**Comment by dachary** [comment]
@yuriw does this backport look good to merge ? It passed the rados (http://tracker.ceph.com/issues/17487#note-12), upgrade/jewel-x and upgrade/hammer-x (http://tracker.ceph.com/issues/17487#note-15) suites (except for two bugs that are, I believe, unrelated)

**Comment by athanatos** [comment]
@tchaikov lgtm, this is all we need to backport for this one, right?

**Comment by tchaikov** [comment]
@athanatos and @dachary yeah!

**Pull request merged**
