### PR TITLE
qa/rgw/upgrade: stop testing upgrade from pacific

### PR DESCRIPTION
**Pull request by cbodley**
squid won't support upgrades from pacific. stop all testing against centos8 and ubuntu20

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Comment by cbodley** [comment]
removed the change that bumped quincy to ubuntu22, because i guess we only build for ubuntu20 there:
> Failed to fetch package version from https://shaman.ceph.com/api/search/?status=ready&project=ceph&flavor=default&distros=ubuntu%2F22.04%2Fx86_64&ref=quincy

**Comment by cbodley** [comment]
jenkins test api

**Comment by cbodley** [comment]
passed qa in https://pulpito.ceph.com/cbodley-2023-12-14_02:11:26-rgw-wip-cbodley-testing-distro-default-smithi/ after reruns https://pulpito.ceph.com/cbodley-2023-12-14_20:15:48-rgw-wip-cbodley-testing-distro-default-smithi/ and https://pulpito.ceph.com/cbodley-2023-12-15_01:06:56-rgw-wip-cbodley-testing-distro-default-smithi/

**Comment by cbodley** [comment]
jenkins test api

**Review by smanjara — APPROVED** [review]

**Pull request merged**
