### PR TITLE
pybind/mgr/dashboard: do not use distutils.version.StrictVersion

### PR DESCRIPTION
**Pull request by tchaikov**
replace `distutils.version.StrictVersion` with
`packaging.version.Version`.

as the former is deprecated, see https://peps.python.org/pep-0632/.
let's use `pkg_resources` instead. this change also addresses
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1010894.
we have this issue when testing with an ubuntu jammy test node.
see https://bugs.launchpad.net/ubuntu/+source/ceph/+bug/1967139

Signed-off-by: Kefu Chai <tchaikov@gmail.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by tchaikov** [comment]
this change should address the api test failures which surface recently. the symptom is like https://jenkins.ceph.com/job/ceph-api/42106/consoleFull , where `vstart.sh` was waiting for mgr dashboard module's response. but the module was just unable to load due to the weird version number of cherrypy.

**Comment by tchaikov** [comment]
@epuertat hi Ernesto, i am also adding you as a reviewer in hope to get this change reviewed and merged sooner. as it's a blocker of PR merges.

**Comment by tchaikov** [comment]
```
Err:10 https://deb.nodesource.com/node_12.x jammy Release
  404  Not Found [IP: 23.55.62.195 443]
Reading package lists...
E: The repository 'https://deb.nodesource.com/node_12.x jammy Release' does not have a Release file.
Build step 'Execute shell' marked build as failure
```

e2e tests are failing due to https://github.com/nodesource/distributions/issues/1379

**Comment by tchaikov** [comment]
e2e test failures should be addressed by https://github.com/ceph/ceph-build/pull/2047

**Review by epuertat — APPROVED** [review]
LGTM. Probably we could/should remove the cherrypy backports file, since these old versions of cherrypy are not available in modern distros.

**Comment by tchaikov** [comment]
being built at https://shaman.ceph.com/builds/ceph/wip-no-more-distutils/c4d3c4cfedac5577b1cd98b363a823f4037fadc5/

**Comment by tchaikov** [comment]
jenkins test dashboard cephadm

**Comment by tchaikov** [comment]
jenkins test dashboard

**Comment by epuertat** [comment]
The cephadm failure is a false positive, because it does run on preexisting `main` packages + PR Python code mounted in the containers:
```
Aug 08 23:56:01 ceph-node-00 ceph-mgr[11719]: mgr[py] Traceback (most recent call last):
                                                File "/usr/share/ceph/mgr/dashboard/__init__.py", line 60, in <module>
                                                  from .module import Module, StandbyModule  # noqa: F401
                                                File "/usr/share/ceph/mgr/dashboard/module.py", line 48, in <module>
                                                  from .cherrypy_backports import patch_cherrypy
                                                File "/usr/share/ceph/mgr/dashboard/cherrypy_backports.py", line 35, in <module>
                                                  from packaging.version import Version
                                              ModuleNotFoundError: No module named 'packaging'
```

**Comment by epuertat** [comment]
Regarding the shaman buils, I see 3 different failures, but the one related to this PR is [on CentOS 8 ARM](https://jenkins.ceph.com/job/ceph-dev-new-build/ARCH=arm64,AVAILABLE_ARCH=arm64,AVAILABLE_DIST=centos8,DIST=centos8,MACHINE_SIZE=gigantic/64655//consoleFull):
```
Error: 
 Problem: conflicting requests
  - nothing provides python3-packaging needed by ceph-mgr-dashboard-2:17.0.0-14106.gc4d3c4cf.el8.noarch
 ```

**Comment by tchaikov** [comment]
@epuertat hi Ernesto,  thank you for looking into the build failures.

i thought `packaging.version()` was a better choice, but it turns out this package is provided by powertools repo (see https://centos.pkgs.org/8/centos-powertools-aarch64/python3-packaging-16.8-9.el8.noarch.rpm.html) , while python-setuptools is provided by baseos repo (see https://centos.pkgs.org/8/centos-baseos-aarch64/python3-setuptools-39.2.0-6.el8.noarch.rpm.html).

to address the `othing provides python3-packaging` issue, i am switching back to ``pkg_resources.parse_version()`.

**Comment by tchaikov** [comment]
https://shaman.ceph.com/builds/ceph/wip-no-more-distutils/fa0ae0bda422a6034d4f8f310da4aa898ba34868/

**Review by epuertat — APPROVED** [review]

**Comment by tchaikov** [comment]
changelog

- added stub with type hint `types-pkg_resources` for `pkg_resources`

**Comment by tchaikov** [comment]
jenkins test api

**Comment by tchaikov** [comment]
jenkins test make check

**Comment by tchaikov** [comment]
jenkins test make check

**Pull request merged**
