### PR TITLE
dmclock: update mClockPriorityQueue with changes in subtree 

### PR DESCRIPTION
**Pull request by cbodley**
updates `common/mClockPriorityQueue.h` with the changes from https://github.com/ceph/dmclock/pull/49

### CODE REVIEW

**Comment by cbodley** [comment]
@ivancich did i do the subtree bits right?

**Comment by cbodley** [comment]
jenkins test this please

**Comment by ivancich** [comment]
To use my slightly modified rados qa suite that only allows the op queue to use mclock variations, you can, on your teuthology-suite command-line add both of:
	--suite-repo https://github.com/ivancich/ceph-fork.git
        --suite-branch eric-qa-dmclock-only

**Comment by cbodley** [comment]
jenkins rebuild docs

**Comment by cbodley** [comment]
jenkins retest docs please

**Comment by cbodley** [comment]
jenkins build doc please

**Comment by cbodley** [comment]
jenkins test docs please

**Comment by cbodley** [comment]
http://pulpito.ceph.com/cbodley-2018-03-22_18:56:30-rados-wip-dmclock-remove-by-ptr-distro-basic-smithi/

shows 3 failures that don't appear to be related

**Comment by ivancich** [comment]
@mattbenjamin The signed check fails due to the commits created by the git `subtree pull command`. Would you mind merging?

**Comment by cbodley** [comment]
^ ping @mattbenjamin

**Pull request merged**
