### PR TITLE
Wip rgw new multisite

### PR DESCRIPTION
**Pull request by oritwas**
move default zonegroup and zone into the realm

### CODE REVIEW

**Comment by yehudasa** [comment]
@oritwas the default shouldn't be part of the realm data. Pretty much need to keep the same default object that we have now, just add the realm id to its name.

**Comment by yehudasa** [comment]
@oritwas after trying this, I'm not sure that the default zone works correctly. When doing 'radosgw-admin zone get', it seems that we still try to read the generic default.zone object, and not the per-realm one. Can you verify that I'm not just missing something?

**Comment by oritwas** [comment]
@yehudasa maybe you don't have a default realm ?

**Comment by oritwas** [comment]
@yehudasa , found the issue will post a fix

**Comment by yehudasa** [comment]
@oritwas are the help.t commits on purpose in here?

**Comment by oritwas** [comment]
trying to fix the build, but I can move them to another pull request

**Pull request merged**
