### PR TITLE
rgwlc: lock_lambda overwrites ret val

### PR DESCRIPTION
**Pull request by 5cs**
`lock_lambda` captures `ret` by reference, it will overwrites
returned value of `bucket_lc_process` when `wait_backoff` is called.

Fixes: c069eb7ff09b52003fa00a5cc83b1e52370032f5.

Signed-off-by: Tongliang Deng <dengtongliang@gmail.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [x] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Review by mattbenjamin — APPROVED** [review]
ouch, yes;  that's not intended

**Comment by 5cs** [comment]
jenkins test api

**Comment by mattbenjamin** [comment]
@cbodley can you see any destructive side effect here?

**Comment by 5cs** [comment]
@mattbenjamin I think overwriting the captured `ret` is also a bug since if `wait_backoff` at https://github.com/ceph/ceph/blob/main/src/rgw/rgw_lc.cc#LL2228C1-L2228C1 successfully returned (`ret` is `0`), the checks at https://github.com/ceph/ceph/blob/main/src/rgw/rgw_lc.cc#LL2235C5-L2235C5 are affected.

**Comment by 5cs** [comment]
@mattbenjamin I think overwriting the captured `ret` is also a bug since if `wait_backoff` at https://github.com/ceph/ceph/blob/main/src/rgw/rgw_lc.cc#LL2228C1-L2228C1 successfully returned (`ret` is `0`), the checks at https://github.com/ceph/ceph/blob/main/src/rgw/rgw_lc.cc#LL2235C5-L2235C5 are affected.

**Comment by mattbenjamin** [comment]
i send qa runs

**Review by mattbenjamin — APPROVED** [review]
+1, and verified

**Comment by mattbenjamin** [comment]
(building now in shaman)

**Comment by mattbenjamin** [comment]
https://pulpito.ceph.com/mbenjamin-2023-11-20_17:19:51-rgw-fix-lambda-capture-by-ref-distro-default-smithi/

**Comment by mattbenjamin** [comment]
I scheduled another run, because the above couldn't start over a dozen jobs, and --rerun only started 3
https://pulpito.ceph.com/mbenjamin-2023-11-21_13:24:02-rgw-fix-lambda-capture-by-ref-distro-default-smithi/

**Comment by mattbenjamin** [comment]
13 jobs failed, most looked like recently expected failures--doing a rerun:
https://pulpito.ceph.com/mbenjamin-2023-11-21_19:12:46-rgw-fix-lambda-capture-by-ref-distro-default-smithi/

**Comment by ivancich** [comment]
Teuthology results -- no regressions:
* https://pulpito.ceph.com/ivancich-2023-11-21_06:04:08-rgw-wip-eric-testing-1-distro-default-smithi/
* https://pulpito.ceph.com/ivancich-2023-11-21_06:03:43-rgw-wip-eric-testing-1-distro-default-smithi/

**Comment by ivancich** [comment]
@5cs and @mattbenjamin : I've run this through QA and merged it. There is no tracker for this, so is it correct to assume no backports are needed? Thanks!

**Comment by ivancich** [comment]
nvm, I see that it says it was a very recent bug. Sorry to bother you both.

**Comment by mattbenjamin** [comment]
this applies at least as far back as reef, probably quincy

**Comment by mattbenjamin** [comment]
so we should backport--I'm sorry there's not a tracker

**Comment by mattbenjamin** [comment]
@ivancich were you able to get a clean qa run?

**Comment by ivancich** [comment]
> @ivancich were you able to get a clean qa run?

Yes, I reviewed the results in the links above and examined all failures, and none were related to this PR.

**Comment by mattbenjamin** [comment]
thanks @ivancich !

**Pull request merged**
