### PR TITLE
kraken: osd: leaked MOSDMap

### PR DESCRIPTION
**Pull request by shinobu-x**
http://tracker.ceph.com/issues/18293

### CODE REVIEW

**Comment by shinobu-x** [comment]
retest please jenkins

**Comment by shinobu-x** [comment]
test this please

**Comment by smithfarm** [comment]
Jenkins re-test this please

**Comment by smithfarm** [comment]
Jenkins re-test this please

**Comment by smithfarm** [comment]
@shinobu-x The make check failure has hopefully been fixed by #16069 - could you please rebase to pick it up?

**Comment by smithfarm** [comment]
Jenkins re-test this please

**Comment by smithfarm** [comment]
Nevermind, rebase not necessary (Jenkins merges into latest base branch before starting the test).

Jenkins re-test this please

**Comment by smithfarm** [comment]
@jdurgin This passed a rados suite at http://tracker.ceph.com/issues/19009#note-51http://tracker.ceph.com/issues/19009#note-51 with two failures that I believe are unrelated. Please review/approve the PR if you agree it can be merged.

**Pull request merged**
