### PR TITLE
ceph.spec.in: use multi-threaded xz compression and cleanups

### PR DESCRIPTION
**Pull request by tchaikov**
## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by tchaikov** [comment]
https://shaman.ceph.com/builds/ceph/wip-rpm-multi-threaded-xz/1219a8cacefeec4caa52b75b0248e641237a5393/

**Comment by tchaikov** [comment]
https://shaman.ceph.com/builds/ceph/wip-rpm-multi-threaded-xz/144bf31087e510afcc7ebd62b3f718f14f68bef9/

**Comment by djgalloway** [comment]
> https://shaman.ceph.com/builds/ceph/wip-rpm-multi-threaded-xz/144bf31087e510afcc7ebd62b3f718f14f68bef9/

If I'm reading things correctly, that cut the time down by 12 minutes!

Your build: https://jenkins.ceph.com/job/ceph-dev-new-build/ARCH=x86_64,AVAILABLE_ARCH=x86_64,AVAILABLE_DIST=centos8,DIST=centos8,MACHINE_SIZE=gigantic/51703/
42min

Different build: https://jenkins.ceph.com/job/ceph-dev-new-build/ARCH=x86_64,AVAILABLE_ARCH=x86_64,AVAILABLE_DIST=centos8,DIST=centos8,MACHINE_SIZE=gigantic/51698/
54min

**Comment by djgalloway** [comment]
The centos8,default build that failed failed because of ceph-container breakage.

**Review by djgalloway — APPROVED** [review]
@tchaikov you rock so much

**Comment by dmick** [comment]
I don't know if "consolidating flags inside macros" is really a good trend.  It seems to obfuscate the code for not much benefit. 

The compression stuff is great tho.

**Comment by tchaikov** [comment]
yeah, I gave a second thought on this as well. but I still want the rpm receipt to be written in a more "rpm way" which follows the convention instead of inventing our own approach.

**Comment by smithfarm** [comment]
I see this PR reverted the code we had in place (originally SUSE-only, but later accepted by RH) to set a reasonable value for `-j` (parallel build) based primarily on the amount of memory available. 

The reason we had that code was, in a word, the OBS. The typical OBS build worker has a large number of CPUs but not much memory. For this reason, using the number of available CPUs as the sole basis for determining build parallelism is very bad.

@ktdreyer @b-ranto Does this change work well for your RH builds? If so, I'll restore the old code for SUSE builds only.

**Comment by tchaikov** [comment]
@smithfarm i think the change you are referencing is https://github.com/ceph/ceph/pull/39506/commits/43b441f9a3bc907c17d52385251001ffcd5d3ff9 which defines a macro for calculating `_smp_ncpus_max`. so i think its behavior should be the same as before. AFAIK, the rpm builder in OBS also respect `_smp_ncpus_max`. please correct me if i am wrong.

**Comment by tchaikov** [comment]
after some digging, probably it depends. see

https://github.com/openSUSE/obs-build/blob/1c2fc98d11ef66e9fed284258cb5655701a8693a/build-recipe-spec#L84-L90

https://github.com/openSUSE/obs-build/blob/1c2fc98d11ef66e9fed284258cb5655701a8693a/build#L931-L934

so if `-jobs` is passed to `build` , `_smp_mflags` is overridden with the `-jobs` option.

**Pull request merged**
