### PR TITLE
Bucket header is enclosed by quotes

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/11873

### CODE REVIEW

**Comment by dachary** [comment]
@smithfarm could you please rebase & repush this one to trigger the bot ?

**Comment by smithfarm** [comment]
@dachary done

**Comment by smithfarm** [comment]
@wido This PR is included in the integration branch http://tracker.ceph.com/issues/11644 that just passed an rgw suite http://pulpito.ceph.com/smithfarm-2015-08-10_12:30:50-rgw-firefly-backports---basic-multi/ - do you think it's OK to merge?

**Comment by smithfarm** [comment]
@yehudasa This is a backport of https://github.com/ceph/ceph/pull/4844 - it is included in the integration branch http://tracker.ceph.com/issues/11644 that just passed an rgw suite http://pulpito.ceph.com/smithfarm-2015-08-10_12:30:50-rgw-firefly-backports---basic-multi/ - do you think it's OK to merge?

**Comment by wido** [comment]
@smithfarm Looks good to me

**Comment by dachary** [comment]
@yehudasa ping ?

**Comment by smithfarm** [comment]
Passed rados suite as well.

**Comment by smithfarm** [comment]
Agreed with @yehudasa to leave this PR open and merge it along with #5730 in the next integration round.

**Comment by smithfarm** [comment]
Closing this PR because it is causing a merge conflict when populating the integration branch. The commit in question is now included in #5730.

**Pull request closed without merging**
