### PR TITLE
pacific: mgr/cephadm: try to get FQDN for active instance

### PR DESCRIPTION
**Pull request by adk3798**
backport tracker: https://tracker.ceph.com/issues/56042

---

backport of https://github.com/ceph/ceph/pull/46285
parent tracker: https://tracker.ceph.com/issues/55674

this backport was staged using ceph-backport.sh version 16.0.0.6848
find the latest version at https://github.com/ceph/ceph/blob/master/src/script/ceph-backport.sh

### CODE REVIEW

**Comment by s0nea** [comment]
jenkins test api

**Comment by adk3798** [comment]
jenkins test api

**Comment by adk3798** [comment]
jenkins test dashboard cephadm

**Comment by adk3798** [comment]
jenkins test dashboard cephadm

**Comment by s0nea** [comment]
jenkins test dashboard cephadm

**Comment by nizamial09** [comment]
jenkins test dashboard cephadm

**Comment by nizamial09** [comment]
@s0nea @adk3798 retriggered the tests since its merged in pacific. lets see..

**Review by s0nea — APPROVED** [review]

**Pull request merged**
