### PR TITLE
mds: relax certain asserts in mdlog replay thread

### PR DESCRIPTION
**Pull request by vshankar**
Fixes: http://tracker.ceph.com/issues/57048

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Comment by vshankar** [comment]
jenkins test make check

**Review by mchangir — APPROVED** [review]
LGTM

**Comment by vshankar** [comment]
https://pulpito.ceph.com/?branch=wip-vshankar-testing-20240226.124304

**Comment by vshankar** [comment]
https://pulpito.ceph.com/vshankar-2024-02-27_04:05:06-fs-wip-vshankar-testing-20240226.124304-testing-default-smithi/

**Comment by dparmar18** [comment]
so with this if the journaler turns unreadable by the time we hit this:
https://github.com/ceph/ceph/blob/b11e6e21f7271bc622c662de6f6c148d6da5c6fb/src/mds/MDLog.cc#L1412-L1417

then this will mean we `continue` at line 1417 and this goes on until the journaler becomes readable again?

**Comment by vshankar** [comment]
> then this will mean we `continue` at line 1417 and this goes on until the journaler becomes readable again?

I don't think so - it should enter the `if (journaler->get_error())` block at the top the while loop and then the error should get handled.

**Comment by vshankar** [comment]
> > then this will mean we `continue` at line 1417 and this goes on until the journaler becomes readable again?
> 
> I don't think so - it should enter the `if (journaler->get_error())` block at the top the while loop and then the error should get handled.

EDIT: are you seeing any other case when the above is not true @dparmar18 ?

**Comment by dparmar18** [comment]
> > > then this will mean we `continue` at line 1417 and this goes on until the journaler becomes readable again?
> > 
> > 
> > I don't think so - it should enter the `if (journaler->get_error())` block at the top the while loop and then the error should get handled.
> 
> EDIT: are you seeing any other case when the above is not true @dparmar18 ?

im trying to think of a case where we're stuck in this loop forever, i.e. readable at `if (journaler->get_error())` but then turns unreadable when we try read an entry at the code block I highlighted above

**Comment by dparmar18** [comment]
@

> > > > then this will mean we `continue` at line 1417 and this goes on until the journaler becomes readable again?
> > > 
> > > 
> > > I don't think so - it should enter the `if (journaler->get_error())` block at the top the while loop and then the error should get handled.
> > 
> > 
> > EDIT: are you seeing any other case when the above is not true @dparmar18 ?
> 
> im trying to think of a case where we're stuck in this loop forever, i.e. readable at `if (journaler->get_error())` but then turns unreadable when we try read an entry at the code block I highlighted above

this seems to be almost impossible to hit, btw do you think we should log it if the read failure occured:

```
    if (!r && journaler->get_error()) {
      continue;
      dout(0) << "journaler became unreadable, retrying" << dendl;
      //maybe log to cluster log too?
      mds->clog->error() << "journaler suddenly turns unreadable";
    }
    ceph_assert(r);
```

**Comment by vshankar** [comment]
> @
> 
> > > > > then this will mean we `continue` at line 1417 and this goes on until the journaler becomes readable again?
> > > > 
> > > > 
> > > > I don't think so - it should enter the `if (journaler->get_error())` block at the top the while loop and then the error should get handled.
> > > 
> > > 
> > > EDIT: are you seeing any other case when the above is not true @dparmar18 ?
> > 
> > 
> > im trying to think of a case where we're stuck in this loop forever, i.e. readable at `if (journaler->get_error())` but then turns unreadable when we try read an entry at the code block I highlighted above
> 
> this seems to be almost impossible to hit, btw do you think we should log it if the read failure occured:
> 
> ```
>     if (!r && journaler->get_error()) {
>       continue;
>       dout(0) << "journaler became unreadable, retrying" << dendl;
>       //maybe log to cluster log too?
>       mds->clog->error() << "journaler suddenly turns unreadable";
>     }
>     ceph_assert(r);
> ```

We can rely on the log messages from the retry.

**Comment by gregsfortytwo** [comment]
An explanation in the commit message (and PR intro comment) about *why* this fixes anything would be great. It looks like it's just straight-up dropping an assert and anything that modifies those kinds of invariants should always come with the logic around why.

**Comment by vshankar** [comment]
> An explanation in the commit message (and PR intro comment) about _why_ this fixes anything would be great. It looks like it's just straight-up dropping an assert and anything that modifies those kinds of invariants should always come with the logic around why.

Sure!

**Comment by vshankar** [comment]
Commit message fixed and updated. Please check @ceph/cephfs

**Comment by vshankar** [comment]
Reruning tests with https://github.com/ceph/ceph/pull/55909 and https://github.com/ceph/ceph/pull/55908 included. See - https://pulpito.ceph.com/vshankar-2024-03-04_08:26:39-fs-wip-vshankar-testing-20240304.042522-testing-default-smithi/

**Review by dparmar18 — APPROVED** [review]

**Comment by vshankar** [comment]
https://tracker.ceph.com/projects/cephfs/wiki/Main#5th-March-2024

**Comment by vshankar** [comment]
jenkins retest this please

**Pull request merged**
