### PR TITLE
ceph-disk/tests: add testcases and fix issues in ceph-disk tests

### PR DESCRIPTION
**Pull request by JiYou**
1. Add testcase for PrepareData.set_data_partition
2. Fix issues in QA workunits in ceph-disk-no-lockbox
3. Fix issues in ceph-disk/test-main.py

Signed-off-by: You Ji <youji@ebay.com>

### CODE REVIEW

**Comment by dachary** [comment]
test this please

**Comment by JiYou** [comment]
@dachary thanks.

**Comment by dachary** [comment]
@JiYou 2ff8a472412b90333faf5b46cb8e872640414c08 is modifying a copy of the ceph-disk script that is only there to verify the behavior of the previous version. As such, if it has a bug, it cannot be fixed in the test. The current ceph-disk / tests must be modified to work around the problem.

**Comment by dachary** [comment]
@JiYou feel free to re-open when you have time to update this pull request

**Pull request closed without merging**
