### PR TITLE
mimic: qa/workunits/rbd: wait for rbd-nbd unmap to complete

### PR DESCRIPTION
**Pull request by pdvian**
http://tracker.ceph.com/issues/39674

### CODE REVIEW

**Comment by smithfarm** [comment]
rocksdb failed to compile for reasons obviously unrelated to this PR

**Comment by smithfarm** [comment]
jenkins re-test this please

**Comment by smithfarm** [comment]
jenkins test make check

**Comment by yuriw** [comment]
[wip-yuri5-testing-2019-07-15-1957-mimic](https://trello.com/c/C5BiJvwF/668-wip-yuri5-testing-2019-07-15-1957-mimic)

**Pull request merged**
