### PR TITLE
nautilus: mgr/volumes: fs subvolume resize command

### PR DESCRIPTION
**Pull request by joscollin**
Fixes: https://tracker.ceph.com/issues/42615
Fixes: https://tracker.ceph.com/issues/42790

### CODE REVIEW

**Comment by smithfarm** [comment]
@joscollin In #30054 there is a doc commit which seems to be omitted here?

**Comment by joscollin** [comment]
@smithfarm There is no `doc/cephfs/fs-volumes.rst` in nautilus. That's why the doc commit was omitted.

**Comment by joscollin** [comment]
But I think it would be nice to have a nautilus version of `fs-volumes.rst`.

**Comment by joscollin** [comment]
@smithfarm Added two more commits, which should go along.

**Comment by smithfarm** [comment]
@joscollin Cool. If and when all the required Jenkins checks are green, please add `needs-qa` and `nautilus-batch-1` labels.

**Comment by yuriw** [comment]
@joscollin needs rebase

--- pr 31332 --- pulling https://github.com/joscollin/ceph.git branch wip-41182-nautilus
remote: Enumerating objects: 26, done.
remote: Counting objects: 100% (26/26), done.
remote: Total 32 (delta 26), reused 26 (delta 26), pack-reused 6
Unpacking objects: 100% (32/32), done.
From https://github.com/joscollin/ceph
 * branch                  wip-41182-nautilus -> FETCH_HEAD
Auto-merging src/pybind/mgr/volumes/module.py
CONFLICT (content): Merge conflict in src/pybind/mgr/volumes/module.py
Auto-merging src/pybind/mgr/volumes/fs/volume.py
Auto-merging src/pybind/mgr/volumes/fs/subvolume.py
Auto-merging qa/tasks/cephfs/test_volumes.py
CONFLICT (content): Merge conflict in qa/tasks/cephfs/test_volumes.py
Automatic merge failed; fix conflicts and then commit the result.
Traceback (most recent call last):
  File "/home/yuriw/wip_master/src/script/build-integration-branch", line 67, in <module>
    assert not r
AssertionError

**Comment by batrick** [comment]
> @joscollin needs rebase
> 
> --- pr 31332 --- pulling https://github.com/joscollin/ceph.git branch wip-41182-nautilus
> remote: Enumerating objects: 26, done.
> remote: Counting objects: 100% (26/26), done.
> remote: Total 32 (delta 26), reused 26 (delta 26), pack-reused 6
> Unpacking objects: 100% (32/32), done.
> From https://github.com/joscollin/ceph
> 
>     * branch                  wip-41182-nautilus -> FETCH_HEAD
>       Auto-merging src/pybind/mgr/volumes/module.py
>       CONFLICT (content): Merge conflict in src/pybind/mgr/volumes/module.py
>       Auto-merging src/pybind/mgr/volumes/fs/volume.py
>       Auto-merging src/pybind/mgr/volumes/fs/subvolume.py
>       Auto-merging qa/tasks/cephfs/test_volumes.py
>       CONFLICT (content): Merge conflict in qa/tasks/cephfs/test_volumes.py
>       Automatic merge failed; fix conflicts and then commit the result.
>       Traceback (most recent call last):
>       File "/home/yuriw/wip_master/src/script/build-integration-branch", line 67, in 
>       assert not r
>       AssertionError

It's conflicting with another PR. No rebase until whatever it's conflicting with is merged.

**Comment by joscollin** [comment]
@batrick rebased

**Comment by yuriw** [comment]
[wip-yuri2-testing-2020-01-06-2029-nautilus](https://trello.com/c/UGkAOr4q/794-wip-yuri2-testing-2020-01-06-2029-nautilus)

**Comment by ajarr** [comment]
@yuriw please also backport the 2 doc commits in this PR that didn't make it to your testing branch

**Comment by smithfarm** [comment]
jenkins test make check

**Comment by smithfarm** [comment]
@ajarr Yuri's integration testing does not exercise anything under `doc/`.

**Pull request merged**
