### PR TITLE
test/throttle: reassign the value of 'delay' in ThrottleTest.get

### PR DESCRIPTION
**Pull request by Yan-waller**

### CODE REVIEW

**Comment by xiexingguo** [comment]
These changes look good to me except that the commit message of https://github.com/ceph/ceph/pull/8367/commits/ca8a66bc98af0fe4517370feca0eddef7824b947 is poorly formed.

**Comment by xiexingguo** [comment]
@ldachary What do you think?

**Comment by Yan-waller** [comment]
@xiexingguo thanks for reminding me and I have already modified.

**Comment by xiexingguo** [comment]
My pleasure:)

**Pull request merged**
