### PR TITLE
os/bluestore: fix permissions on StupidAllocator.cc, cleanups

### PR DESCRIPTION
**Pull request by shinobu-x**
From 774 to 664

Signed-off-by: Shinobu Kinjo shinobu@linux.com

### CODE REVIEW

**Comment by tchaikov** [comment]
@shinobu-x some nits in your commit message:

could you prefix the title of your commit message with the subcomponent your are changing instead of "FIX"? see https://github.com/ceph/ceph/blob/master/SubmittingPatches.rst#preparing-and-sending-patches, in this case, it could be "os/bluestore/StupidAllocator"

and your signed-off-by line does looks quite right, should be
```
Signed-off-by: Shinobu Kinjo <shinobu@linux.com>
```

please note the brackets around your mail address.

**Comment by shinobu-x** [comment]
@tchaikov 

Ooookey! Thank you for your advise.
I'm still learning how-to in an appropriate manner -;
Should I do PR again?

**Comment by tchaikov** [comment]
@shinobu-x you don't need to create a new PR. instead you can instead fix your commit locally, and 'git push -f' to your remote branch (wip-shinobu), and this PR will get updated automatically.

**Comment by shinobu-x** [comment]
@tchaikov thank you for your continuous advice :)

**Pull request merged**
