### PR TITLE
kstore: Implement the get_statfs() interface for RocksDBStore

### PR DESCRIPTION
**Pull request by Ted-Chang**
Implement the get_statfs() interface for RocksDBStore so that "rados df" will show how much space was available.

### CODE REVIEW

**Comment by dachary** [comment]
jenkins test this please (no logs)

**Comment by dachary** [comment]
@Ted-Chang could you please rebase and fix the Signed off by error ?

**Comment by Ted-Chang** [comment]
Will fix it later. Thanks.

**Comment by Ted-Chang** [comment]
I started a new pull request and the link is here. Please take a look at this one. Thanks.
https://github.com/ceph/ceph/pull/12392

**Pull request closed without merging**
