### PR TITLE
mimic: rgw: fail to recover index from crash mimic backport

### PR DESCRIPTION
**Pull request by ivancich**
Fixes: http://tracker.ceph.com/issues/24629

### CODE REVIEW

**Comment by smithfarm** [comment]
Ah, I found it - it's from https://github.com/ceph/ceph/pull/22937 which is still open. Let's wait until that merges before proceeding here.

**Comment by ivancich** [comment]
@smithfarm It's from a PR to master that has not yet been merged (https://github.com/ceph/ceph/pull/22937). Do I need to wait for that to merge before proceeding with this step?

**Comment by ivancich** [comment]
@smithfarm You'd already answered my question. Thanks!

**Comment by smithfarm** [comment]
@ivancich Yes, we always wait until the master PR merges before cherry-picking, because the master commits can (and often do) change via force-pushing all the way up until merge. Once it merges, then it's fair game!

**Comment by smithfarm** [comment]
DNM can be move after master PR is merged and cherry-pick SHA1 is double-checked.

**Comment by smithfarm** [comment]
@ivancich Actually, to be correct, the second commit should be re-cherry-picked after the master PR merges. Just use `git cherry-pick -x` and don't edit the commit message unless there are conflicts (assuming there won't be). Changing the original commit message is a "no-no". You can add stuff after the cherry-picked line, though.

**Comment by ivancich** [comment]
@smithfarm I redid the cherry-picks now that https://github.com/ceph/ceph/pull/22937 merged. I'm removing the DNM label so the process can continue. Thanks!

**Comment by yuriw** [comment]
[wip-yuri4-testing-2018-08-20-2118-mimic](https://trello.com/c/EK2RH5M2/379-wip-yuri4-testing-2018-08-20-2118-mimic)

**Pull request merged**
