### PR TITLE
rgw: fix error messages in RGWAccessKeyPool::modify_key()

### PR DESCRIPTION
**Pull request by joscollin**
Fixes error messages in RGWAccessKeyPool::modify_key() function.

Signed-off-by: Jos Collin <jcollin@redhat.com>

### CODE REVIEW

**Comment by joscollin** [comment]
Jenkins Retest this please

**Comment by joscollin** [comment]
Jenkins Retest this please

**Comment by joscollin** [comment]
@cbodley  Could you please review ?

**Comment by cbodley** [comment]
hi @joscollin, can you explain the motivation for these changes? the existing error messages correspond to the `--access-key` and `--subuser` arguments to radosgw-admin. i worry that your changes would make it harder to figure out why the command failed

**Comment by joscollin** [comment]
@cbodley While reviewing another PR, I saw these messages. I just thought to give more specific error messages by seeing these lines:

https://github.com/joscollin/ceph/blob/7455d03c31d0f7d15d254dcadabf2ce910c6c60a/src/rgw/rgw_user.cc#L880
https://github.com/joscollin/ceph/blob/7455d03c31d0f7d15d254dcadabf2ce910c6c60a/src/rgw/rgw_user.cc#L886

If it is displaying inappropriate error messages, I'm okay with closing this PR. Please suggest. Thanks.

**Comment by joscollin** [comment]
@cbodley ping

**Pull request closed without merging**
