### PR TITLE
msg/async/ProtocolV2: fix typo in register_lossy_clients fix

### PR DESCRIPTION
**Pull request by liewegas**
In 507d213cc453ed86ab38619590f710f33245c652 this was typoed, reversing
the condition.

Fixes: https://tracker.ceph.com/issues/42328
Signed-off-by: Sage Weil <sage@redhat.com>

### CODE REVIEW

**Comment by liewegas** [comment]
retest this please

**Comment by dillaman** [comment]
@liewegas It's still failing w/ out-of-order ops [1] on my latest test branch [2].

[1] http://qa-proxy.ceph.com/teuthology/jdillaman-2020-02-26_18:52:47-rbd-wip-jd-testing-distro-basic-smithi/4805834/teuthology.log
[2] https://github.com/ceph/ceph-ci/commit/0d29dc315bf89c1e95c2ea627f3712bc34cb341c

**Comment by liewegas** [comment]
@dillaman ok looks like I missed a condition back when introducing the policy flag.  Can you retest with the new patch?

**Comment by dillaman** [comment]
@liewegas :champagne: RBD tests are passing! :tada:

**Comment by liewegas** [comment]
> @liewegas champagne RBD tests are passing! tada

:fireworks: omg finally.  thanks for testing!!

**Pull request merged**
