### PR TITLE
qa/suites/smoke: remove packages on test completion

### PR DESCRIPTION
**Pull request by batrick**
A new teuthology PR [1] skips package cleanup by default. Use the
lightweight smoke suite to ensure that package cleanup continues to
work.

[1] https://github.com/ceph/teuthology/pull/1553

Signed-off-by: Patrick Donnelly <pdonnell@redhat.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by batrick** [comment]
https://pulpito.ceph.com/pdonnell-2020-08-26_15:43:40-smoke-master-distro-basic-smithi/

Well, it works. For some reason though we're seeing this MDS_ALL_DOWN warning for the first time: https://pulpito.ceph.com/?suite=smoke

**Comment by neha-ojha** [comment]
> https://pulpito.ceph.com/pdonnell-2020-08-26_15:43:40-smoke-master-distro-basic-smithi/
> 
> Well, it works. For some reason though we're seeing this MDS_ALL_DOWN warning for the first time: https://pulpito.ceph.com/?suite=smoke

@batrick you shouldn't see it with https://github.com/ceph/teuthology/pull/1545

**Comment by batrick** [comment]
> > https://pulpito.ceph.com/pdonnell-2020-08-26_15:43:40-smoke-master-distro-basic-smithi/
> > Well, it works. For some reason though we're seeing this MDS_ALL_DOWN warning for the first time: https://pulpito.ceph.com/?suite=smoke
> 
> @batrick you shouldn't see it with [ceph/teuthology#1545](https://github.com/ceph/teuthology/pull/1545)

Ah, that's a relief. Thanks Neha!

**Comment by batrick** [comment]
https://pulpito.ceph.com/pdonnell-2020-08-27_01:53:58-smoke-master-distro-basic-smithi/

failures unrelated. Works as advertised. @neha-ojha the MDS_DOWN failure still persists :(

**Comment by neha-ojha** [comment]
> https://pulpito.ceph.com/pdonnell-2020-08-27_01:53:58-smoke-master-distro-basic-smithi/
> 
> failures unrelated. Works as advertised. @neha-ojha the MDS_DOWN failure still persists :(

I am not seeing the changes mades in https://github.com/ceph/teuthology/pull/1545 reflect in your run. You'll want to update your local teuthology repo from where you are issuing teuthology-suite commands. I'll send a broader announcement about this.

**Pull request merged**
