### PR TITLE
submodule: bump up RapidJSON

### PR DESCRIPTION
**Pull request by tchaikov**
to include the C++20 fixes introduced recently.

Signed-off-by: Kefu Chai <tchaikov@gmail.com>

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [x] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by tchaikov** [comment]
this change is extracted out of #45133 in hope to get it reviewed and merged sooner.

**Review by cbodley — APPROVED** [review]
lgtm. rgw only has two significant uses of rapidjson:
* stuff in rgw_iam_policy.cc should be covered by `unittest_rgw_iam_policy`
* stuff in rgw_crypt/kms.cc should be covered by the rgw/crypt teuthology suite

**Review by adamemerson — APPROVED** [review]

**Comment by tchaikov** [comment]
jenkins test make check

**Comment by tchaikov** [comment]
pushed to https://shaman.ceph.com/builds/ceph/wip-rapidjson-kefu/ad5ee504801f0c5280eab30a72246639be3baa29/default/297996/, will schedule a teuthology run afterwards.

**Comment by tchaikov** [comment]
https://pulpito.ceph.com/kchai-2022-03-13_10:17:16-rgw-wip-rapidjson-kefu-distro-default-smithi/

**Comment by tchaikov** [comment]
jenkins test windows

**Comment by tchaikov** [comment]
jenkins test windows

**Pull request merged**
