### PR TITLE
os/bluestore: fix bitmap allocating failure if max_alloc_size is 0

### PR DESCRIPTION
**Pull request by xiexingguo**
If max_alloc_size is 0(means no limit), the original logic will
always hardcode need_blks to 0, which is incorrect.

Signed-off-by: xie xingguo <xie.xingguo@zte.com.cn>

### CODE REVIEW

**Comment by xiexingguo** [comment]
@chhabaramesh Ping

**Comment by xiexingguo** [comment]
2016-07-21 17:53:03.041740 7fb74658a680  1 bluestore(store_test_temp_dir) fsck finish with 0 errors
[       OK ] ObjectStore/StoreTest.TooManyBlobsTest/2 (23797 ms)
[----------] 59 tests from ObjectStore/StoreTest (2146475 ms total)

[----------] Global test environment tear-down
[==========] 59 tests from 1 test case ran. (2146475 ms total)
[  PASSED  ] 59 tests.

**Comment by xiexingguo** [comment]
retest this please

**Comment by xiexingguo** [comment]
@chhabaramesh Care to review? Thanks!

**Comment by chhabaramesh** [comment]
@xiexingguo  looks good to me.

**Comment by xiexingguo** [comment]
2016-07-26 14:50:07.705638 7fb46a83f680  1 bluestore(store_test_temp_dir) fsck finish with 0 errors
[       OK ] ObjectStore/StoreTest.TooManyBlobsTest/2 (21131 ms)
[----------] 59 tests from ObjectStore/StoreTest (2078216 ms total)

[----------] Global test environment tear-down
[==========] 59 tests from 1 test case ran. (2078216 ms total)
[  PASSED  ] 59 tests.

**Pull request merged**
