### PR TITLE
rgw: code to return error if a role is deleted with permission

### PR DESCRIPTION
**Pull request by pritha-srivastava**
policies attached to it.

The REST API implementation already has this check in place, hence this has been implemented only for radosgw-admin cli command.

Fixes: https://tracker.ceph.com/issues/67535

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Comment by cbodley** [comment]
this means the admin would have to run additional commands (`role policy list` and `role policy delete`s) before being able to delete a role

the IAM APIs generally require that all associated resources be removed before the parent resource can be removed. and we don't want to remove something that's still referenced by something else

but in this case, the policies are stored inside the role metadata, so there's no risk that the policies outlive the deleted role. i think it's worth allowing this deletion for the sake of convenience

at least, that was my reasoning for changing this behavior in https://github.com/ceph/ceph/pull/54333 (i moved the check out of `RadosRole::delete_obj()` into the rest api's `RGWDeleteRole::execute()`)

**Comment by pritha-srivastava** [comment]
I agree with the reasoning here but shouldn't we keep the behaviour of the REST API and the cli command the same?

**Comment by cbodley** [comment]
@pritha-srivastava the DeleteRole api is for users, while the radosgw-admin command is just for admins. i don't see a problem with the admin version having extra capabilities if it makes it easier to manage the cluster

**Comment by pritha-srivastava** [comment]
> @pritha-srivastava the DeleteRole api is for users, while the radosgw-admin command is just for admins. i don't see a problem with the admin version having extra capabilities if it makes it easier to manage the cluster

Ok sounds logical.

**Pull request closed without merging**
