### PR TITLE
osd: backport straw bucket fixes and all other recent crush goodness to firefly

### PR DESCRIPTION
**Pull request by liewegas**
I took a diff of this against master's crush/ dir and the only remaining differences are straw2 or cosmetic.

### CODE REVIEW

**Comment by liewegas** [comment]
@dachary care to look?  This looked good in my wip-dho rados run (modulo env noise) and on a big production cluster.

**Comment by dachary** [comment]
@liewegas sure, I'll review it tomorrow :-)

**Comment by dachary** [comment]
<pre>
$ git log --oneline ceph/firefly..ceph/wip-crush-straw-firefly -- src/crush | wc -l
21
loic@fold:~/software/ceph/ceph$ git log --grep 'cherry picked' --oneline ceph/firefly..ceph/wip-crush-straw-firefly -- src/crush | wc -l
21
</pre>
all commits are properly marked with 'cherry picked'

**Comment by dachary** [comment]
Conflicts were resolved with
<pre>
$ git log --oneline --grep 'Conflicts' ceph/firefly..ceph/wip-crush-straw-firefly -- src/crush | while read commit subject ; do echo ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ; echo $commit "$subject" ; picked_from=$(git show --no-patch --pretty=%b $commit  | perl -ne 'print if(s/.*cherry picked from commit (\w+).*/$1/)') ; diff -u --ignore-matching-lines '^[^+-]' &lt;(git show $picked_from) &lt;(git show $commit) ; done
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2e69b1d crush: pass crush_map * to various builder methods
--- /dev/fd/63	2015-02-13 14:49:37.735445195 +0100
+++ /dev/fd/62	2015-02-13 14:49:37.739445169 +0100
@@ -57,20 +61,11 @@
  	ldout(cct, 5) &lt;&lt; "adjust_item_weight_in_loc " &lt;&lt; id &lt;&lt; " diff " &lt;&lt; diff &lt;&lt; " in bucket " &lt;&lt; bid &lt;&lt; dendl;
  	adjust_item_weight(cct, bid, b->weight);
  	changed++;
-@@ -801,7 +801,7 @@ int CrushWrapper::adjust_subtree_weight(CephContext *cct, int id, int weight)
-     for (unsigned i=0; i&lt;b->size; ++i) {
-       int n = b->items[i];
-       if (n >= 0) {
--	crush_bucket_adjust_item_weight(b, n, weight);
-+	crush_bucket_adjust_item_weight(crush, b, n, weight);
-       } else {
- 	crush_bucket *sub = get_bucket(n);
- 	if (IS_ERR(sub))
 diff --git a/src/crush/CrushWrapper.h b/src/crush/CrushWrapper.h
-index 54aa2a9..97f5ccd 100644
+index 5ab6832..9893163 100644
 --- a/src/crush/CrushWrapper.h
 +++ b/src/crush/CrushWrapper.h
-@@ -815,11 +815,11 @@ private:
+@@ -798,11 +798,11 @@ private:
  
      if (!IS_ERR(parent_bucket)) {
        // zero out the bucket weight
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
d627aec crush: fix incorrect use of adjust_item_weight method
--- /dev/fd/63	2015-02-13 14:49:37.751445091 +0100
+++ /dev/fd/62	2015-02-13 14:49:37.751445091 +0100
@@ -171,17 +175,6 @@
      // get where the bucket is located
      pair&lt;string, string> bucket_location = get_immediate_parent(item);
  
-@@ -761,6 +766,10 @@ private:
-     // get the parent bucket
-     crush_bucket *parent_bucket = get_bucket(parent_id);
- 
-+    // zero out the bucket weight
-+    crush_bucket_adjust_item_weight(parent_bucket, item, 0);
-+    adjust_item_weight(cct, parent_bucket->id, parent_bucket->weight);
-+
-     if (!IS_ERR(parent_bucket)) {
-       // remove the bucket from the parent
-       crush_bucket_remove_item(parent_bucket, item);
 diff --git a/src/test/cli/crushtool/adjust-item-weight.t b/src/test/cli/crushtool/adjust-item-weight.t
 new file mode 100644
 index 0000000..16d7135
</pre>

**Comment by dachary** [comment]
The d627aec hunk was removed because it is introduced, correctly by commit  1aefda6ce0475534ae95a1a629a2cd50f26e5e29 that shows later on
<pre>
$ git log -L '/detach_bucket(CephContext/,/^  }/:CrushWrapper.h' ceph/firefly..ceph/wip-crush-straw-firefly
...
commit 1aefda6ce0475534ae95a1a629a2cd50f26e5e29
Author: Sage Weil <sage@redhat.com>
Date:   Thu Nov 13 10:59:22 2014 -0800

    crush/CrushWrapper: fix detach_bucket
    
    In commit 9850227d2f0ca2f692a154de2c14a0a08e751f08 we changed the call that
    changed the weight of all instances of item to one that explicitly
    changes it in the parent bucket, but parent_id may not be valid at the
    call site.  Move this into the conditional block to fix.
    
    Fixes: #10095
    Signed-off-by: Sage Weil <sage@redhat.com>
    (cherry picked from commit 6f8b96a9fe4793906c74a571109a457aca7ca220)

diff --git a/src/crush/CrushWrapper.h b/src/crush/CrushWrapper.h
--- a/src/crush/CrushWrapper.h
+++ b/src/crush/CrushWrapper.h
@@ -768,44 +768,48 @@
   int detach_bucket(CephContext *cct, int item){
     if (!crush)
       return (-EINVAL);
 
     if (item >= 0)
       return (-EINVAL);
 
     // check that the bucket that we want to detach exists
     assert( get_bucket(item) );
 
     // get the bucket's weight
     crush_bucket *b = get_bucket(item);
     unsigned bucket_weight = b->weight;
 
     // zero out the bucket weight
     adjust_item_weight(cct, item, 0);
 
     // get where the bucket is located
     pair<string, string> bucket_location = get_immediate_parent(item);
 
     // get the id of the parent bucket
     int parent_id = get_item_id(bucket_location.second);
 
     // get the parent bucket
     crush_bucket *parent_bucket = get_bucket(parent_id);
 
     if (!IS_ERR(parent_bucket)) {
+      // zero out the bucket weight
+      crush_bucket_adjust_item_weight(parent_bucket, item, 0);
+      adjust_item_weight(cct, parent_bucket->id, parent_bucket->weight);
+
       // remove the bucket from the parent
       crush_bucket_remove_item(parent_bucket, item);
     } else if (PTR_ERR(parent_bucket) != -ENOENT) {
       return PTR_ERR(parent_bucket);
     }
 
     // check that we're happy
     int test_weight = 0;
     map<string,string> test_location;
     test_location[ bucket_location.first ] = (bucket_location.second);
 
     bool successful_detach = !(check_item_loc(cct, item, test_location, &test_weight));
     assert(successful_detach);
     assert(test_weight == 0);
 
     return bucket_weight;
   }
</pre>

**Comment by dachary** [comment]
Regarding the changes in src/mon has http://paste2.org/_Ms1d80HN which implements **osd crush reweight-all** **osd crush set-tunable** and **osd crush get-tunable**. The only strange thing is the ability to set **hammer** tunables. It is harmless because they are the same as firefly but it may be a source of confusion ?
<pre>
+ } else if (profile == "hammer") {
+ newcrush.set_tunables_hammer();
</pre>

**Comment by dachary** [comment]
The changes in src/tools are only about crushtools.cc and osdmaptool.cc to support new features or adapt to prototype / constness changes.

**Comment by dachary** [comment]
The rest of the changes are in src/tests and one in qa/workunits/cephtool/test.sh, all of which run with make check which returned success.

git log --patch ceph/firefly..ceph/wip-crush-straw-firefly src/test : http://paste.ubuntu.com/10205422/

**Comment by dachary** [comment]
The difference between this branch and master is http://paste.ubuntu.com/10205436/

**Comment by dachary** [comment]
If the hammer tunable is preserved in firefly, the following hunk should also be backported:
<pre>
   // be helpful about it
-  if (has_firefly_tunables())
+  if (has_hammer_tunables())
+    f->dump_string("profile", "hammer");
+  else if (has_firefly_tunables())
     f->dump_string("profile", "firefly");
   else if (has_bobtail_tunables())
</pre>

**Comment by dachary** [comment]
<pre>
@@ -141,6 +142,9 @@ int crush_addition_is_unsafe(__u32 a, __u32 b)
 
 int crush_multiplication_is_unsafe(__u32  a, __u32 b)
 {
+  // prevent division by zero 
+  if (!b)
+    return 1;
   if ((((__u32)(-1)) / b) < a)
     return 1;
   else
</pre>
is probably good to have.

**Comment by dachary** [comment]
@liewegas looks good to me :-) Let me know what you decide regarding the hammer tunables and I'll add it to the next rados run for firefly backports.

**Comment by liewegas** [comment]
On Fri, 13 Feb 2015, Loic Dachary wrote:
> If the hammer tunable is preserved in firefly, the following hunk should also be backported:
> 
>    // be helpful about it
> -  if (has_firefly_tunables())
> +  if (has_hammer_tunables())
> +    f->dump_string("profile", "hammer");
> +  else if (has_firefly_tunables())
>      f->dump_string("profile", "firefly");
>    else if (has_bobtail_tunables())

There is some other stuff that the 'hammer' profile does in hammer 
(mainly, support for straw2 buckets), so we don't want that backported.

**Comment by liewegas** [comment]
thanks!  i already did a rados that looked good (except for the 
dm-0 environmental problem), so this is ready to merge.

**Comment by dachary** [comment]
> so we don't want that backported.

Ok. Reviewed-by: as soon as
<pre>
diff --git a/src/mon/MonCommands.h b/src/mon/MonCommands.h
index bd9dd2e..58e9e60 100644
--- a/src/mon/MonCommands.h
+++ b/src/mon/MonCommands.h
@@ -431,7 +431,7 @@ COMMAND("osd crush reweight " \
"change <name>'s weight to <weight> in crush map", \
"osd", "rw", "cli,rest")
COMMAND("osd crush tunables " \
- "name=profile,type=CephChoices,strings=legacy|argonaut|bobtail|firefly|optimal|default", \
+ "name=profile,type=CephChoices,strings=legacy|argonaut|bobtail|firefly|hammer|optimal|default", \
"set crush tunables values to <profile>", "osd", "rw", "cli,rest")
COMMAND("osd crush show-tunables", \
"show current crush tunables", "osd", "r", "cli,rest")
diff --git a/src/mon/OSDMonitor.cc b/src/mon/OSDMonitor.cc
index 5f54f94..3ae031e 100644
--- a/src/mon/OSDMonitor.cc
+++ b/src/mon/OSDMonitor.cc
@@ -4195,6 +4195,8 @@ bool OSDMonitor::prepare_command_impl(MMonCommand *m,
newcrush.set_tunables_bobtail();
} else if (profile == "firefly") {
newcrush.set_tunables_firefly();
+ } else if (profile == "hammer") {
+ newcrush.set_tunables_hammer();
} else if (profile == "optimal") {
newcrush.set_tunables_optimal();
} else if (profile == "default") {
</pre>
is reverted then.

**Comment by liewegas** [comment]
oh, yeah!  repushed.  the diff between the two looks ok to me, can you 
verify?

thanks!

**Comment by dachary** [comment]
git diff 256afa2970c4aa2c7f1455fd1557ad5978de0e31 b668566 looks good http://paste.ubuntu.com/10207064/

**Comment by dachary** [comment]
@liewegas please ignore the fail, I messed with the bot

**Pull request merged**
