### PR TITLE
organizationmap: modify org mail info.

### PR DESCRIPTION
**Pull request by cxwshawn**
Signed-off-by: Xiaowei Chen <chen.xiaowei@h3c.com>

### CODE REVIEW

**Comment by tchaikov** [comment]
@cxwshawn could you resolve the merge conflict and repush?

**Comment by cxwshawn** [comment]
@tchaikov resolved, please review .

**Comment by cxwshawn** [comment]
@tchaikov @theanalyst ping!

**Comment by theanalyst** [comment]
LGTM

**Pull request merged**
