### PR TITLE
rgw: AWS4 authentication minimal support

### PR DESCRIPTION
**Pull request by jmunhoz**
Amazon S3 supports Signature Version 4. This patch contains the minimal
implementation supporting AWS4 in radosgw. It implements AWS4
authentication on http methods without body content and vars not
shipping in the request query string.

Related: #10333

Signed-off-by: Javier M. Mellid <jmunhoz@igalia.com>

### CODE REVIEW

**Comment by yehudasa** [comment]
@jmunhoz any reason why you closed the pull request?

**Comment by jmunhoz** [comment]
@yehudasa I removed my remote wip-aws4 before pushing my new local and rebased wip-aws4 with all changes included and I found github closed the pull-request. I guess I will have to create a new pull request? Sorry, I was not expecting this behaviour in github.

**Comment by jmunhoz** [comment]
@yehudasa reopening the pull request.

**Comment by jmunhoz** [comment]
@yehudasa It looks I could reopen the pull request successfully. I checked all our comments are in place and the new commit taking care of your comments is available too.

**Comment by jmunhoz** [comment]
@yehudasa Apologies for messing up the PR.You can see the old comments at
https://github.com/jmunhoz/ceph/commit/96f6f6f8516f68a95bfa26da3af72209451d1753

**Comment by yehudasa** [comment]
@jmunhoz no worries

**Comment by jmunhoz** [comment]
@yehudasa pull request updated with the missing bits. whole feature uploaded.

**Comment by yehudasa** [comment]
@jmunhoz sorry for not completing review, didn't forget about it!

**Comment by jmunhoz** [comment]
@yehudasa don't worry, thanks for the update!

**Comment by yehudasa** [comment]
@jmunhoz I will try to take a closer look at it this week

**Comment by jmunhoz** [comment]
@yehudasa thanks!

**Comment by jmunhoz** [comment]
@yehudasa I will try that approach. thanks

**Comment by jmunhoz** [comment]
@yehudasa I added a new commit to validate the requests with body following one streaming approach as suggested. Now, it doesn't read the whole thing in memory to validate it. I rebased the the whole tree to keep the sources up to date too.

**Comment by jmunhoz** [comment]
@yehudasa just pushing two new patches hardening the current code while working in S3 tests.

**Comment by jmunhoz** [comment]
@yehudasa two new patches added as result of working on S3 tests. One check on x-amz-date and another one verifying the content's sha256 sum. I had to rebase against upstream/master to avoid a simple conflict with those last two patches. All working fine.

By the way, I will ask for pull request at s3-tests to start merging test cases related to AWS4.

**Comment by yehudasa** [comment]
@jmunhoz almost there. Take a look at the wip-rgw-aws4 branch that I pushed. It has multiple changes. I have two issues that I'm seeing. See my comment with regard to url_encode() for one, and the second issue is that it seems that signed requests only handled correctly with either - PUT of an object, or requests that have no body. Any other requests will fail if they're signed (e.g., bucket creation). This needs to be handled in a more global scope than the way it is handled in the object creation. Other than that looks good!

**Comment by yehudasa** [comment]
@jmunhoz this PR has some conflicts now

**Comment by jmunhoz** [comment]
@yehudasa fixed

**Pull request merged**
