### PR TITLE
rgw: Let the object stat command be shown in the usage

### PR DESCRIPTION
**Pull request by prallabh**
Fixes: http://tracker.ceph.com/issues/19013
Signed-off-by: Pavan Rallabhandi <PRallabhandi@walmartlabs.com>

### CODE REVIEW

**Comment by prallabh** [comment]
@yehudasa addressed

**Comment by cbodley** [comment]
will this need backport?

**Comment by prallabh** [comment]
@cbodley not sure if that question was for me, but I don't mind backporting once this gets merged in master.

**Comment by cbodley** [comment]
@prallabh i opened a tracker issue so we can track the backport. can you please add `Fixes: http://tracker.ceph.com/issues/19013` to your commit message?

**Comment by prallabh** [comment]
@cbodley done

**Pull request merged**
