### PR TITLE
mimic: os/bluestore: call fault_range properly prior to looking for blob to …

### PR DESCRIPTION
**Pull request by ifed01**
https://tracker.ceph.com/issues/39255

### CODE REVIEW

**Comment by xiexingguo** [comment]
retest this please

**Comment by xiexingguo** [comment]
@ifed01 


```
[       OK ] TestAllocatorLevel01.test_l2_contiguous_alignment (1 ms)
[ RUN      ] TestAllocatorLevel01.test_4G_alloc_bug
Init L2 cont aligned
/home/jenkins-build/build/workspace/ceph-pull-requests/src/test/objectstore/fastbmap_allocator_test.cc:863: Failure
      Expected: a4.size()
      Which is: 0
To be equal to: 1u
      Which is: 1
[  FAILED  ] TestAllocatorLevel01.test_4G_alloc_bug (0 ms)
[ RUN      ] TestAllocatorLevel01.test_4G_alloc_bug2
/home/jenkins-build/build/workspace/ceph-pull-requests/src/test/objectstore/fastbmap_allocator_test.cc:881: Failure
      Expected: a4.size()
      Which is: 0
To be equal to: 1u
      Which is: 1
[  FAILED  ] TestAllocatorLevel01.test_4G_alloc_bug2 (0 ms)
[ RUN      ] TestAllocatorLevel01.test_4G_alloc_bug3
Init L2 cont aligned
/home/jenkins-build/build/workspace/ceph-pull-requests/src/test/objectstore/fastbmap_allocator_test.cc:921: Failure
      Expected: a4.size()
      Which is: 0
To be equal to: 2u
      Which is: 2
[  FAILED  ] TestAllocatorLevel01.test_4G_alloc_bug3 (0 ms)
[----------] 8 tests from TestAllocatorLevel01 (6794 ms total)

[----------] Global test environment tear-down
[==========] 8 tests from 1 test case ran. (6794 ms total)
[  PASSED  ] 5 tests.
[  FAILED  ] 3 tests, listed below:
[  FAILED  ] TestAllocatorLevel01.test_4G_alloc_bug
[  FAILED  ] TestAllocatorLevel01.test_4G_alloc_bug2
[  FAILED  ] TestAllocatorLevel01.test_4G_alloc_bug3

 3 FAILED TESTS

**Comment by ifed01** [comment]
@xiexingguo - thanks for pointing out. But these failures seem to be unrelated as they're present in mimic HEAD too. Investigating...

**Comment by xiexingguo** [comment]
> But these failures seem to be unrelated as they're present in mimic HEAD too. Investigating...

I understand. I thought I might be related to the recently backported fast bitmap allocator. Hence ping you:-)

**Comment by ifed01** [comment]
@xiexingguo - allocator test failures have been fixed in https://github.com/ceph/ceph/pull/27606

**Comment by ifed01** [comment]
jenkins retest this please

**Comment by yuriw** [comment]
[wip-yuri2-testing-2019-04-29-1936-mimic](https://trello.com/c/dXehT7mH/597-wip-yuri2-testing-2019-04-29-1936-mimic)

**Pull request merged**
