### PR TITLE
doc: document CephFS Snapshot Mirroring

### PR DESCRIPTION
**Pull request by vshankar**
Signed-off-by: Venky Shankar <vshankar@redhat.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by vshankar** [comment]
@batrick this is a cut down version of the dev document. I think we can just keep this (and remove the dev doc)?

**Review by batrick — CHANGES_REQUESTED** [review]
Please link to this from the release notes (now in master).

Otherwise LGTM

**Comment by tchaikov** [comment]
```
/home/jenkins-build/build/workspace/ceph-pr-docs/doc/releases/pacific.rst:200: WARNING: undefined label: cephfs-mirroring (if the link has no caption the label must precede a section header)
generating indices...  genindex http-routingtable py-modindexdone
writing additional pages...  searchdone
```

**Comment by vshankar** [comment]
@batrick PTAL

**Review by batrick — APPROVED** [review]

**Pull request merged**
