### PR TITLE
test/run-rbd-unit-tests.sh: increase ip-local-port-range

### PR DESCRIPTION
**Pull request by tchaikov**
Signed-off-by: Kefu Chai <tchaikov@gmail.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by tchaikov** [comment]
jenkins test make check

**Comment by tchaikov** [comment]
jenkins test make check

**Comment by tchaikov** [comment]
```
+ cat netstat.out
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 127.0.0.1:45853         0.0.0.0:*               LISTEN      954108/ceph-mon     
tcp        0      0 127.0.0.1:42903         0.0.0.0:*               LISTEN      -                   
tcp        0      0 127.0.0.1:9014          0.0.0.0:*               LISTEN      962289/unittest-sea 
tcp        0      0 127.0.0.1:9012          0.0.0.0:*               LISTEN      962289/unittest-sea 
tcp        0      0 127.0.0.1:9013          0.0.0.0:*               LISTEN      962289/unittest-sea 
tcp        0      0 0.0.0.0:5666            0.0.0.0:*               LISTEN      -                   
tcp        0      0 0.0.0.0:6834            0.0.0.0:*               LISTEN      990499/ceph-osd     
tcp        0      0 0.0.0.0:6835            0.0.0.0:*               LISTEN      990499/ceph-osd     
tcp        0      0 0.0.0.0:6832            0.0.0.0:*               LISTEN      990499/ceph-osd     
tcp        0      0 0.0.0.0:6833            0.0.0.0:*               LISTEN      990499/ceph-osd     
tcp        0      0 0.0.0.0:6818            0.0.0.0:*               LISTEN      972013/ceph-osd     
tcp        0      0 0.0.0.0:6819            0.0.0.0:*               LISTEN      972013/ceph-osd     
tcp        0      0 0.0.0.0:6816            0.0.0.0:*               LISTEN      972013/ceph-osd     
tcp        0      0 0.0.0.0:6817            0.0.0.0:*               LISTEN      972013/ceph-osd     
tcp        0      0 0.0.0.0:6830            0.0.0.0:*               LISTEN      990499/ceph-osd     
tcp        0      0 0.0.0.0:6831            0.0.0.0:*               LISTEN      990499/ceph-osd     
tcp        0      0 0.0.0.0:6828            0.0.0.0:*               LISTEN      990499/ceph-osd     
tcp        0      0 0.0.0.0:6829            0.0.0.0:*               LISTEN      990499/ceph-osd     
tcp        0      0 0.0.0.0:6810            0.0.0.0:*               LISTEN      956985/ceph-mgr     
tcp        0      0 0.0.0.0:6811            0.0.0.0:*               LISTEN      956985/ceph-mgr     
tcp        0      0 0.0.0.0:6814            0.0.0.0:*               LISTEN      972013/ceph-osd     
tcp        0      0 0.0.0.0:6815            0.0.0.0:*               LISTEN      972013/ceph-osd     
tcp        0      0 0.0.0.0:6812            0.0.0.0:*               LISTEN      972013/ceph-osd     
tcp        0      0 0.0.0.0:6813            0.0.0.0:*               LISTEN      972013/ceph-osd     
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      -                   
tcp        0      0 0.0.0.0:25              0.0.0.0:*               LISTEN      -                   
tcp        0      0 127.0.0.53:53           0.0.0.0:*               LISTEN      -                   
tcp        0      0 127.0.0.1:16814         0.0.0.0:*               LISTEN      964933/unittest-sea 
tcp        0      0 127.0.0.1:16815         0.0.0.0:*               LISTEN      964933/unittest-sea 
tcp        0      0 127.0.0.1:16812         0.0.0.0:*               LISTEN      964933/unittest-sea 
tcp        0      0 127.0.0.1:16813         0.0.0.0:*               LISTEN      964933/unittest-sea 
tcp        0      0 127.0.0.1:16810         0.0.0.0:*               LISTEN      964933/unittest-sea 
tcp        0      0 127.0.0.1:16811         0.0.0.0:*               LISTEN      964933/unittest-sea 
tcp        0      0 127.0.0.1:16809         0.0.0.0:*               LISTEN      964933/unittest-sea 
tcp        0      0 127.0.0.1:16822         0.0.0.0:*               LISTEN      964933/unittest-sea 
tcp        0      0 127.0.0.1:16823         0.0.0.0:*               LISTEN      964933/unittest-sea 
tcp        0      0 127.0.0.1:16820         0.0.0.0:*               LISTEN      964933/unittest-sea 
tcp        0      0 127.0.0.1:16821         0.0.0.0:*               LISTEN      964933/unittest-sea 
tcp        0      0 127.0.0.1:16818         0.0.0.0:*               LISTEN      964933/unittest-sea 
tcp        0      0 127.0.0.1:16819         0.0.0.0:*               LISTEN      964933/unittest-sea 
tcp        0      0 127.0.0.1:16816         0.0.0.0:*               LISTEN      964933/unittest-sea 
tcp        0      0 127.0.0.1:16817         0.0.0.0:*               LISTEN      964933/unittest-sea 
tcp        0      0 127.0.0.1:16824         0.0.0.0:*               LISTEN      964933/unittest-sea 
tcp6       0      0 :::9090                 :::*                    LISTEN      -                   
tcp6       0      0 :::5666                 :::*                    LISTEN      -                   
tcp6       0      0 :::22                   :::*                    LISTEN      -                   
tcp6       0      0 :::25                   :::*                    LISTEN      -                   
tcp        0      0 127.0.0.1:16810         0.0.0.0:*               LISTEN      964933/unittest-sea 
tcp        0      0 127.0.0.1:16811         0.0.0.0:*               LISTEN      964933/unittest-sea 
tcp        0      0 127.0.0.1:16809         0.0.0.0:*               LISTEN      964933/unittest-sea 
tcp        0      0 127.0.0.1:16822         0.0.0.0:*               LISTEN      964933/unittest-sea 
tcp        0      0 127.0.0.1:16823         0.0.0.0:*               LISTEN      964933/unittest-sea 
tcp        0      0 127.0.0.1:16820         0.0.0.0:*               LISTEN      964933/unittest-sea 
tcp        0      0 127.0.0.1:16821         0.0.0.0:*               LISTEN      964933/unittest-sea 
tcp        0      0 127.0.0.1:16818         0.0.0.0:*               LISTEN      964933/unittest-sea 
tcp        0      0 127.0.0.1:16819         0.0.0.0:*               LISTEN      964933/unittest-sea 
tcp        0      0 127.0.0.1:16816         0.0.0.0:*               LISTEN      964933/unittest-sea 
tcp        0      0 127.0.0.1:16817         0.0.0.0:*               LISTEN      964933/unittest-sea 
tcp        0      0 127.0.0.1:16824         0.0.0.0:*               LISTEN      964933/unittest-sea 
tcp6       0      0 :::9090                 :::*                    LISTEN      -                   
tcp6       0      0 :::5666                 :::*                    LISTEN      -                   
tcp6       0      0 :::22                   :::*                    LISTEN      -                   
tcp6       0      0 :::25                   :::*                    LISTEN      -                   
tcp        0      0 127.0.0.1:16820         0.0.0.0:*               LISTEN      964933/unittest-sea 
tcp        0      0 127.0.0.1:16821         0.0.0.0:*               LISTEN      964933/unittest-sea 
tcp        0      0 127.0.0.1:16818         0.0.0.0:*               LISTEN      964933/unittest-sea 
tcp        0      0 127.0.0.1:16819         0.0.0.0:*               LISTEN      964933/unittest-sea 
tcp        0      0 127.0.0.1:16816         0.0.0.0:*               LISTEN      964933/unittest-sea 
tcp        0      0 127.0.0.1:16817         0.0.0.0:*               LISTEN      964933/unittest-sea 
tcp        0      0 127.0.0.1:16824         0.0.0.0:*               LISTEN      964933/unittest-sea 
tcp6       0      0 :::9090                 :::*                    LISTEN      -                   
tcp6       0      0 :::5666                 :::*                    LISTEN      -                   
tcp6       0      0 :::22                   :::*                    LISTEN      -                   
tcp6       0      0 :::25                   :::*                    LISTEN      -   
```

**Comment by tchaikov** [comment]
jenkins test make check

**Comment by tchaikov** [comment]
jenkins test make check

**Comment by tchaikov** [comment]
jenkins test make check

**Comment by tchaikov** [comment]
jenkins test make check

**Comment by tchaikov** [comment]
jenkins test make check

**Comment by tchaikov** [comment]
jenkins test make check

**Comment by tchaikov** [comment]
```
+ cat netstat.out
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 127.0.0.1:16824         0.0.0.0:*               LISTEN      3729826/unittest-se 
tcp        0      0 127.0.0.1:16818         0.0.0.0:*               LISTEN      3729826/unittest-se 
tcp        0      0 127.0.0.1:16819         0.0.0.0:*               LISTEN      3729826/unittest-se 
tcp        0      0 127.0.0.1:16816         0.0.0.0:*               LISTEN      3729826/unittest-se 
tcp        0      0 127.0.0.1:16817         0.0.0.0:*               LISTEN      3729826/unittest-se 
tcp        0      0 127.0.0.1:16822         0.0.0.0:*               LISTEN      3729826/unittest-se 
tcp        0      0 127.0.0.1:16823         0.0.0.0:*               LISTEN      3729826/unittest-se 
tcp        0      0 127.0.0.1:16820         0.0.0.0:*               LISTEN      3729826/unittest-se 
tcp        0      0 127.0.0.1:16821         0.0.0.0:*               LISTEN      3729826/unittest-se 
tcp        0      0 127.0.0.1:16810         0.0.0.0:*               LISTEN      3729826/unittest-se 
tcp        0      0 127.0.0.1:16811         0.0.0.0:*               LISTEN      3729826/unittest-se 
tcp        0      0 127.0.0.1:16809         0.0.0.0:*               LISTEN      3729826/unittest-se 
tcp        0      0 127.0.0.1:16814         0.0.0.0:*               LISTEN      3729826/unittest-se 
tcp        0      0 127.0.0.1:16815         0.0.0.0:*               LISTEN      3729826/unittest-se 
tcp        0      0 127.0.0.1:16812         0.0.0.0:*               LISTEN      3729826/unittest-se 
tcp        0      0 127.0.0.1:16813         0.0.0.0:*               LISTEN      3729826/unittest-se 
tcp        0      0 127.0.0.1:9014          0.0.0.0:*               LISTEN      3727686/unittest-se 
tcp        0      0 127.0.0.1:9012          0.0.0.0:*               LISTEN      3727686/unittest-se 
tcp        0      0 127.0.0.1:9013          0.0.0.0:*               LISTEN      3727686/unittest-se 
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      1381/sshd: /usr/sbi 
tcp        0      0 127.0.0.53:53           0.0.0.0:*               LISTEN      1140/systemd-resolv 
tcp        0      0 0.0.0.0:6849            0.0.0.0:*               LISTEN      3776828/ceph-osd    
tcp        0      0 0.0.0.0:6848            0.0.0.0:*               LISTEN      3776828/ceph-osd    
tcp        0      0 0.0.0.0:6851            0.0.0.0:*               LISTEN      3776828/ceph-osd    
tcp        0      0 0.0.0.0:6850            0.0.0.0:*               LISTEN      3776828/ceph-osd    
tcp        0      0 0.0.0.0:6813            0.0.0.0:*               LISTEN      3733900/ceph-osd    
tcp        0      0 0.0.0.0:6812            0.0.0.0:*               LISTEN      3733900/ceph-osd    
tcp        0      0 0.0.0.0:6815            0.0.0.0:*               LISTEN      3733900/ceph-osd    
tcp        0      0 0.0.0.0:6814            0.0.0.0:*               LISTEN      3733900/ceph-osd    
tcp        0      0 0.0.0.0:6811            0.0.0.0:*               LISTEN      3722952/ceph-mgr    
tcp        0      0 0.0.0.0:6810            0.0.0.0:*               LISTEN      3722952/ceph-mgr    
tcp        0      0 0.0.0.0:6817            0.0.0.0:*               LISTEN      3733900/ceph-osd    
tcp        0      0 0.0.0.0:6816            0.0.0.0:*               LISTEN      3733900/ceph-osd    
tcp        0      0 0.0.0.0:6819            0.0.0.0:*               LISTEN      3733900/ceph-osd    
tcp        0      0 0.0.0.0:6818            0.0.0.0:*               LISTEN      3733900/ceph-osd    
tcp        0      0 0.0.0.0:6829            0.0.0.0:*               LISTEN      3753988/ceph-osd    
tcp        0      0 0.0.0.0:6828            0.0.0.0:*               LISTEN      3753988/ceph-osd    
tcp        0      0 0.0.0.0:6831            0.0.0.0:*               LISTEN      3753988/ceph-osd    
tcp        0      0 0.0.0.0:6830            0.0.0.0:*               LISTEN      3753988/ceph-osd    
tcp        0      0 0.0.0.0:6833            0.0.0.0:*               LISTEN      3753988/ceph-osd    
tcp        0      0 0.0.0.0:6832            0.0.0.0:*               LISTEN      3753988/ceph-osd    
tcp        0      0 0.0.0.0:6835            0.0.0.0:*               LISTEN      3753988/ceph-osd    
tcp        0      0 0.0.0.0:6834            0.0.0.0:*               LISTEN      3753988/ceph-osd    
tcp        0      0 0.0.0.0:6845            0.0.0.0:*               LISTEN      3776828/ceph-osd    
tcp        0      0 0.0.0.0:6844            0.0.0.0:*               LISTEN      3776828/ceph-osd    
tcp        0      0 0.0.0.0:6847            0.0.0.0:*               LISTEN      3776828/ceph-osd    
tcp        1      0 0.0.0.0:6846            0.0.0.0:*               LISTEN      3776828/ceph-osd    
tcp        0      0 0.0.0.0:5666            0.0.0.0:*               LISTEN      1463/nrpe           
tcp        0      0 127.0.0.1:54185         0.0.0.0:*               LISTEN      3720251/ceph-mon    
tcp        0      0 127.0.0.1:35061         0.0.0.0:*               LISTEN      1380/containerd     
tcp6       0      0 :::22                   :::*                    LISTEN      1381/sshd: /usr/sbi 
tcp6       0      0 :::5666                 :::*                    LISTEN      1463/nrpe           
tcp6       0      0 :::9090                 :::*                    LISTEN      3901002/prometheus  
tcp        0      0 0.0.0.0:6824            0.0.0.0:*               LISTEN      3743571/ceph-osd    
tcp        0      0 0.0.0.0:6827            0.0.0.0:*               LISTEN      3743571/ceph-osd    
tcp        0      0 0.0.0.0:6826            0.0.0.0:*               LISTEN      3743571/ceph-osd    
tcp        0      0 0.0.0.0:6837            0.0.0.0:*               LISTEN      3759004/ceph-osd    
tcp        0      0 0.0.0.0:6836            0.0.0.0:*               LISTEN      3759004/ceph-osd    
tcp        0      0 0.0.0.0:6839            0.0.0.0:*               LISTEN      3759004/ceph-osd    
tcp        0      0 0.0.0.0:6838            0.0.0.0:*               LISTEN      3759004/ceph-osd    
tcp        0      0 0.0.0.0:6833            0.0.0.0:*               LISTEN      3753988/ceph-osd    
tcp        0      0 0.0.0.0:6832            0.0.0.0:*               LISTEN      3753988/ceph-osd    
tcp        0      0 0.0.0.0:6835            0.0.0.0:*               LISTEN      3753988/ceph-osd    
tcp        0      0 0.0.0.0:6834            0.0.0.0:*               LISTEN      3753988/ceph-osd    
tcp        0      0 0.0.0.0:6845            0.0.0.0:*               LISTEN      3776828/ceph-osd    
tcp        0      0 0.0.0.0:6844            0.0.0.0:*               LISTEN      3776828/ceph-osd    
tcp        0      0 0.0.0.0:6847            0.0.0.0:*               LISTEN      3776828/ceph-osd    
tcp        0      0 0.0.0.0:6846            0.0.0.0:*               LISTEN      3776828/ceph-osd    
tcp        0      0 0.0.0.0:6841            0.0.0.0:*               LISTEN      3759004/ceph-osd    
tcp        0      0 0.0.0.0:6840            0.0.0.0:*               LISTEN      3759004/ceph-osd    
tcp        0      0 0.0.0.0:6843            0.0.0.0:*               LISTEN      3759004/ceph-osd    
tcp        0      0 0.0.0.0:6842            0.0.0.0:*               LISTEN      3759004/ceph-osd    
tcp        0      0 0.0.0.0:5666            0.0.0.0:*               LISTEN      1463/nrpe           
tcp        0      0 127.0.0.1:54719         0.0.0.0:*               LISTEN      3706489/ceph-mon    
tcp        0      0 127.0.0.1:54185         0.0.0.0:*               LISTEN      3720251/ceph-mon    
tcp        0      0 127.0.0.1:35061         0.0.0.0:*               LISTEN      1380/containerd     
tcp6       0      0 :::22                   :::*                    LISTEN      1381/sshd: /usr/sbi 
tcp6       0      0 :::5666                 :::*                    LISTEN      1463/nrpe           
tcp6       0      0 :::9090                 :::*                    LISTEN      3901002/prometheus  
tcp6       0      0 :::9090                 :::*                    LISTEN      3901002/prometheus  
+ exit 1
```

**Comment by tchaikov** [comment]
jenkins test make check

**Comment by tchaikov** [comment]
jenkins test make check

**Comment by tchaikov** [comment]
jenkins test make check

**Comment by tchaikov** [comment]
jenkins test make check

**Comment by tchaikov** [comment]
the output of nestat is way too large, so i pasted it as a git: https://gist.github.com/tchaikov/b3858da3afcba00eb71394dffb5899d1

**Comment by ljflores** [comment]
@tchaikov made this Tracker to document your additional fix: https://tracker.ceph.com/issues/57491

**Review by idryomov — CHANGES_REQUESTED** [review]
I don't understand the purpose of this change.  In https://tracker.ceph.com/issues/57116, there is an attachment that shows over 28000 `TIME_WAIT` sockets to 172.21.2.2:6810.  I don't think `unittest_librbd` is involved in that in any way -- I would expect it to generate ~20 `TIME_WAIT` sockets to localhost -- so I don't see any reason to touch `run-rbd-unit-tests.sh`.

And even if this wasn't done from `run-rbd-unit-tests.sh` but in some other file, why are we attempting to increase `ip_local_port_range` instead of tracking down what is responsible for tens of thousands of locally closed sockets?

**Comment by tchaikov** [comment]
> I don't understand the purpose of this change. https://gist.github.com/tchaikov/b3858da3afcba00eb71394dffb5899d1 shows over 28000 `TIME_WAIT` sockets to 172.21.2.2:6810. I don't think `unittest_librbd` is involved in that in any way -- I would expect it to generate ~20 `TIME_WAIT` sockets to localhost -- so I don't see any reason to touch `run-rbd-unit-tests.sh`.
> 
> And even if this wasn't done from `run-rbd-unit-tests.sh` but in some other file, why are we attempting to increase `ip_local_port_range` instead of tracking down what is responsible for tens of thousands of locally closed sockets?

i created this PR in the same spirit of #47962. why? because i think i understand the issue better, and want to get the "make check" completed sooner with less number of `sleep()` calls. 

i admit that i didn't understand the root cause of "what is responsible for tens of thousands of locally closed sockets" back then, neither do i now. why did i created these PRs without understanding the root case? because i want to "workaround" this issue to alleviate the pain we are suffering in the past weeks. and because i don't have enough bandwidth working on this issue. if any of us had come up with a better fix i would not do these.

i noticed that the #48014 was created claiming 

> Fixes: https://tracker.ceph.com/issues/57116

that PR was approved and backported. that change didn't come with a root cause analysis explaining why we had this issue. and it reverted some changes proposed by the author made in #47962. again, i admit that #47962 also failed to root cause the issue. that's why i didn't claim that i fixed the issue.

i thought we reviewed the PRs with a consistent standard. the comment is confusing. 

anyway, if this change is not following our guideline or best practice. i am closing this change for good.

**Comment by tchaikov** [comment]
> @tchaikov made this Tracker to document your additional fix: https://tracker.ceph.com/issues/57491
> 
> Can you update the commit?

hi Laura, thanks. i don't intend continue working on this change or this issue anymore. so i reset the related fields in https://tracker.ceph.com/issues/57491. sorry for the noise.

**Comment by ljflores** [comment]
No worries, Kefu!

**Comment by idryomov** [comment]
Hi Kefu,

> > I don't understand the purpose of this change.
>
> [...]
>
> i created this PR in the same spirit of #47962. why? because i think i understand the issue better, and want to get the "make check" completed sooner with less number of `sleep()` calls.

This wasn't noted anywere -- neither in the PR description nor in any of the commit messages.  "want to get the "make check" completed sooner with less number of `sleep()` calls" makes the purpose of this change and its disposition (i.e. whether it is an improvement to the workaround or an actual fix) clear.  I hope you would agree that it is much more descriptive than "increase ip-local-port-range" which was all I had to go on at the time of review.

The other thing that confused me was that you added this increase just in `run-rbd-unit-tests.sh` and not in RGW test runner as well.  This led me on a false trail of assuming that you found the root cause and it turned out to be one of RBD tests.  In an attempt to reverse engineer that (false) assumption, I actually had to dig up `ip_local_port_range` documentation to make sure that I'm not misunderstanding what it does because it was quite puzzling...

> 
> i admit that i didn't understand the root cause of "what is responsible for tens of thousands of locally closed sockets" back then, neither do i now. why did i created these PRs without understanding the root case? because i want to "workaround" this issue to alleviate the pain we are suffering in the past weeks. and because i don't have enough bandwidth working on this issue. if any of us had come up with a better fix i would not do these.

I didn't see a single occurrence of this issue on runs that included both #47962 and #48014 and therefore thought that the workaround was good enough and that the pain was gone.  I didn't realize that you had another improvement to the workaround in mind.

> 
> i noticed that the #48014 was created claiming
> 
> > Fixes: https://tracker.ceph.com/issues/57116
> 
> that PR was approved and backported. that change didn't come with a root cause analysis explaining why we had this issue. and it reverted some changes proposed by the author made in #47962. again, i admit that #47962 also failed to root cause the issue. that's why i didn't claim that i fixed the issue.

The `Fixes` tag was copied from #47962.  I backported #48014 together with #47962 (for pacific, quincy had already received #47962 as an ad-hoc backport by then) under that `Fixes` tag because I didn't see a single occurrence of this issue with #47962 + #48014, but did see a couple with just #47962.

> 
> i thought we reviewed the PRs with a consistent standard. the comment is confusing.
> 
> anyway, if this change is not following our guideline or best practice. i am closing this change for good.

I think our approach to `test-failure` issues has been fairly consistent: get as reliable as possible workaround in place, then work on an actual fix as time allows.  Now that you have explained that this PR is a further improvement to the workaround, I guess the question is: is the existing #47962 + #48014 workaround good enough?  If the answer is yes, we should move to root causing and working on an actual fix.  If the answer is no, e.g. because some `make check` runs still fail on EADDRINUSE or because `make check` now takes significantly longer, I'm totally open to reconsidering this PR.

**Pull request closed without merging**
