### PR TITLE
jewel: librbd: fix refuse to release lock when cookie is the same at rewatch

### PR DESCRIPTION
**Pull request by dillaman**

### CODE REVIEW

**Comment by dillaman** [comment]
Note: since Jewel is EOLed upstream, this PR is just for backporting to downstream Ceph releases.

**Comment by smithfarm** [comment]
@dillaman Can this be closed?

**Comment by smithfarm** [comment]
(Perhaps the stale bot only works for PRs targeting master?)

**Comment by smithfarm** [comment]
> @dillaman Can this be closed?

Closing under the assumption the answer is "yes" :-)

**Comment by dillaman** [comment]
> > @dillaman Can this be closed?
> 
> Closing under the assumption the answer is "yes" :-)

Indeed it is.

**Pull request closed without merging**
