### PR TITLE
jewel: rbd-mirror: improve resiliency of stress test case

### PR DESCRIPTION
**Pull request by dillaman**
http://tracker.ceph.com/issues/17486
http://tracker.ceph.com/issues/17065
http://tracker.ceph.com/issues/17559
http://tracker.ceph.com/issues/17405
http://tracker.ceph.com/issues/17406
http://tracker.ceph.com/issues/17484
http://tracker.ceph.com/issues/17475
http://tracker.ceph.com/issues/16902
http://tracker.ceph.com/issues/17508
http://tracker.ceph.com/issues/17537
http://tracker.ceph.com/issues/17506

### CODE REVIEW

**Comment by dillaman** [comment]
@dachary first pass at http://tracker.ceph.com/issues/17416 backport -- compiling and testing now. I will remove the DNM tag (and comment about all the included backport tickets) when locally tested and redmine is back online.

**Comment by dillaman** [comment]
This PR includes the backports for the following master-branch PRs: #10378, #10703, #10155, #11153, #11090, #10445, #11104, #10484, #11185, and #11326

**Comment by dillaman** [comment]
retest this please

**Comment by dachary** [comment]
@dillaman I'll do the backport cross reference now.

**Comment by dachary** [comment]
pushed this in the jewel-backports branch and will run a rbd suite today

**Comment by dachary** [comment]
It passed the rbd suite http://tracker.ceph.com/issues/17487#note-10 (except for two failures that are unrelated http://tracker.ceph.com/issues/17590 and http://tracker.ceph.com/issues/17262)

**Pull request merged**
