### PR TITLE
doc: release notes for 11.0.2

### PR DESCRIPTION
**Pull request by theanalyst**
release notes as of 5a98a8cdef0398f915d215351d111ebac9b51638

### CODE REVIEW

**Comment by dachary** [comment]
github won't show the diff because it's too large :-) I'll download it

**Comment by theanalyst** [comment]
@dachary I made some changes to the scripts to get the pr tags since that was more reliable than the titles here, but still I would've missed some

**Comment by theanalyst** [comment]
@yehudasa @gregsfortytwo @jcsp @dillaman @liewegas 
Any significant features worth mentioning in the release notes? Got significant bluestore improvements, first release of ceph-mgr so far

**Comment by theanalyst** [comment]
@dachary @liewegas 
pushed changes to delete the commits that do not make it to the current state of 11.0.1, since the diff is too large to preview, pasting it here https://gist.github.com/theanalyst/5417b55b3e407d3887c6988a5296695b for a quick look

**Comment by theanalyst** [comment]
Added one more commit which bumps the version number to 11.0.2, and the one commit that differs from 11.0.1 and 11.0.2,

```diff
modified   doc/release-notes.rst
@@ -2,7 +2,7 @@
  Release Notes
 ===============
 
-v11.0.1 Kraken
+v11.0.2 Kraken
 ==============
 
 This development release of introduces a lot of changes and
@@ -352,6 +352,7 @@ Notable Changes
 * cmake: use PERF_LOCAL_FLAGS only if defined (`issue#17104 <http://tracker.ceph.com/issues/17104>`_, `pr#10828 <http://github.com/ceph/ceph/pull/10828>`_, Michel Normand)
 * cmake: use stock Find* modules. (`pr#10178 <http://github.com/ceph/ceph/pull/10178>`_, Kefu Chai)
 * cmake: work to get inital FreeBSD stuff (`pr#10352 <http://github.com/ceph/ceph/pull/10352>`_, Willem Jan Withagen)
+* cmake: find GIT_VER variables if there is no .git dir (`pr#11499 <http://github.com/ceph/ceph/pull/11499>`_, Ali Maredia)
 * common,bluestore: Isa-l extention for zlib compression plugin (`pr#10158 <http://github.com/ceph/ceph/pull/10158>`_, Alyona Kiseleva, Dan Mick)
 * common,bluestore: compressor/zlib: zlib wrapper fix (`pr#11079 <http://github.com/ceph/ceph/pull/11079>`_, Igor Fedotov)
 * common: auth/cephx: misc fixes (`pr#9679 <http://github.com/ceph/ceph/pull/9679>`_, xie xingguo)
```

**Comment by theanalyst** [comment]
the overall release notes is still the same one as before at https://gist.github.com/theanalyst/5417b55b3e407d3887c6988a5296695b

**Comment by dachary** [comment]
<pre>
Reviewed-by: Loic Dachary &lt;ldachary@redhat.com>
</pre>

**Comment by theanalyst** [comment]
@dachary @liewegas added release-notes from 11.0.2 to master as of 7b1293e70db51f620210332bde1f83ade15bd9d3

**Comment by dachary** [comment]
@theanalyst there is a conflict to resolve

**Comment by theanalyst** [comment]
@dachary yes, I'll rebase against master's release notes since 10.2.4 was merged

**Comment by theanalyst** [comment]
@dachary rebased, not sure whether we should keep 11.0.2 release notes around or squash everything to 11.1.0, in which case probably I need to generate 10.2.X to 11.0.0 notes

**Comment by dachary** [comment]
I don't think it really makes a difference, does it ?

**Comment by theanalyst** [comment]
Yeah I agree

**Comment by liewegas** [comment]
See related notes at https://github.com/ceph/ceph/pull/12338

**Comment by liewegas** [comment]
pls rebase on master

**Comment by theanalyst** [comment]
@liewegas rebased, but this only contains commits upto 7b1293e70db51f620210332bde1f83ade15bd9d3, once we decide the release sha1, I'll add those commits as well in the notes

**Pull request merged**
