### PR TITLE
rgw [experimental]: rework RGWClientIO in order to unify behaviour between frontends

### PR DESCRIPTION
**Pull request by rzarzynski**
This PR tries to unify behaviour between multiple radosgw's frontends. A lot of differentiated functions (like data reordering, enforcing proper _Content-Length_ HTTP header and so on) have been moved from per-frontend derivative of _RGWClientIO_ into separated filters which could be easily shared and reused.

### CODE REVIEW

**Comment by dachary** [comment]
@rzarzynski could you please rebase and repush to trigger the make check ?

**Comment by rzarzynski** [comment]
@dachary Hi Loic. Sorry for late response.
The build failure is caused by non-satisfied dependency. This PR depends on [PR #3](https://github.com/ceph/civetweb/pull/3)  for enforced HTTP connection close in ```ceph/civetweb``` submodule.

**Comment by dachary** [comment]
@rzarzynski thanks for the update :-)

**Comment by yehudasa** [comment]
@rzarzynski what's the status here? I think the code area changed a bit with the nfs stuff

**Comment by rzarzynski** [comment]
@yehudasa I'm resurrecting this PR. We will need support for chunked transfer encoding in order to pass some Tempest tests.

**Comment by mattbenjamin** [comment]
@rzarzynski is this still valid?  if so, could you rebase?

**Comment by rzarzynski** [comment]
@mattbenjamin: this PR would require a [change](https://github.com/ceph/civetweb/pull/3) to the `civetweb` submodule. The commit is necessary to stop doing data buffering on our side for the content length calculation.

**Comment by mattbenjamin** [comment]
I'm a bit worried about the use of shared_ptr with several objects storing pointers to something which I suspect can be relied on to exist for the lifetime of (e.g.) a request, without all the explicit overhead.  More generally, how would we know we need this much added indirection, and how do we measure it's cost?

**Comment by rzarzynski** [comment]
@mattbenjamin: I'm pretty sure we could switch to the static, template-based version of the decorator pattern. We already did that in the auth rework.

**Comment by mattbenjamin** [comment]
@rzarzynski that sounds attractive, yes

**Comment by rzarzynski** [comment]
Follow up: #10767.

**Pull request closed without merging**
