### PR TITLE
kraken: rgw: add apis to support ragweed suite

### PR DESCRIPTION
**Pull request by yehudasa**
http://tracker.ceph.com/issues/19809

Add missing apis to support running ragweed against kraken.
 - rest api to retrieve object layout
 - rest api to read zone config params

### CODE REVIEW

**Comment by smithfarm** [comment]
Jenkins re-test this please

**Comment by smithfarm** [comment]
Pushed `wip-rgw-support-ragweed-kraken` to Shaman

**Comment by smithfarm** [comment]
@yehudasa Please rebase to get rid of the failed Jenkins test

**Comment by tchaikov** [comment]
retest this please.

**Comment by smithfarm** [comment]
@yehudasa Ping. Please rebase to clean up the Jenkins box and get a fresh run of the tests.

**Comment by tchaikov** [comment]
retest this please.

**Comment by smithfarm** [comment]
(Rebase is the only way I know of to get rid of the red "X" next to the "default" test.)

**Comment by smithfarm** [comment]
@yehudasa Please rebase.

**Comment by yehudasa** [comment]
@smithfarm rebased

**Comment by smithfarm** [comment]
@yehudasa Thanks. Now, how many "Jenkins retest this please" will be needed to get it past "Unix Domain socket too long" ?

**Comment by tchaikov** [comment]
@smithfarm probably we should backport #14468 to address the test failure. "Unix Domain socket too long" is not the reason why "make check" fails.

**Comment by smithfarm** [comment]
@yehudasa The make check failure has hopefully been fixed by #16069 - could you please rebase to pick it up?

**Comment by smithfarm** [comment]
Nevermind, rebase not necessary (Jenkins merges into latest base branch before starting the test).

Jenkins re-test this please

**Comment by smithfarm** [comment]
@mattbenjamin @oritwas @cbodley This passed an rgw suite at http://tracker.ceph.com/issues/19009#note-49 

Please approve if you agree it can be merged.

**Pull request merged**
