### PR TITLE
rgwlc: fix compat-decoding of cls_rgw_lc_get_entry_ret

### PR DESCRIPTION
**Pull request by mattbenjamin**
Fix compat-decode of cls_rgw_lc_get_entry_ret, which had changed
earlier in 394750597.  While not initially a problem, the more
recent change to allow radosgw-admin lc process to operate on a single
bucket created a way to decode an un-upgraded structure.

Fixes: https://tracker.ceph.com/issues/53927

Reported by Jeegn Chen <jeegnchen@gmail.com>.

Signed-off-by: Matt Benjamin <mbenjamin@redhat.com>

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [x] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Review by cbodley — APPROVED** [review]

**Comment by cbodley** [comment]
the fix itself looks great, and i recognize the decoding strategy from your previous work 👍 

i'm not crazy about the test case though. it certainly looks useful to verify that you got the decoding logic right, so i'm glad you wrote it. but i don't think it's useful to merge it and run for regression testing; mainly because it's based on types that are local to the test case, rather than the types under cls/rgw, so it won't ever catch any regressions in cls/rgw

i think this test coverage belongs with ceph-dencoder and ceph-object-corpus instead, by adding the relevant lc types to `src/tools/ceph-dencoder/rgw_types.h`. each release, we take a snapshot of the current encodings of those types and store them in ceph-object-corpus, then test that our current version can decode each prior version in the corpus. had the lc types been there, we could have caught this regression when it happened

it's probably worth doing a full audit of `rgw_types.h` to find what other types are missing, but for now, can you please make sure the relevant lifecycle types are all there?

**Comment by mattbenjamin** [comment]
> the fix itself looks great, and i recognize the decoding strategy from your previous work 👍

> i think this test coverage belongs with ceph-dencoder and ceph-object-corpus instead, by adding the relevant lc types to `src/tools/ceph-dencoder/rgw_types.h`. each release, we take a snapshot of the current encodings of those types and store them in ceph-object-corpus, then test that our current version can decode each prior version in the corpus. had the lc types been there, we could have caught this regression when it happened
> 
> it's probably worth doing a full audit of `rgw_types.h` to find what other types are missing, but for now, can you please make sure the relevant lifecycle types are all there?

Ok, I agree on both points.  I've never added members to dencoder, but I can repurpose the unittest commit;  I'm at least convinced that it proves the backward-compat path actually does work, and hopefully we can merge the first commit now?

**Comment by cbodley** [comment]
sounds good

**Comment by cbodley** [comment]
for the dencoder coverage, it really just needs:
```patch
diff --git a/src/tools/ceph-dencoder/rgw_types.h b/src/tools/ceph-dencoder/rgw_types.h
index bd1443ddf13..879a1dc789d 100644
--- a/src/tools/ceph-dencoder/rgw_types.h
+++ b/src/tools/ceph-dencoder/rgw_types.h
@@ -44,6 +44,7 @@ TYPE(rgw_bucket_olh_log_entry)
 TYPE(rgw_usage_log_entry)
 
 #include "cls/rgw/cls_rgw_ops.h"
+TYPE(cls_rgw_lc_get_entry_ret)
 TYPE(rgw_cls_obj_prepare_op)
 TYPE(rgw_cls_obj_complete_op)
 TYPE(rgw_cls_list_op)
```

**Review by cbodley — APPROVED** [review]
looks great, but the second commit pulls in lots of submodule changes

**Comment by mattbenjamin** [comment]
yeah, sorry;  will push shortly

**Comment by mattbenjamin** [comment]
@cbodley the prior push didn't define all the required member macros, hopefully now...it does

**Comment by cbodley** [comment]
jenkins test api

**Comment by cbodley** [comment]
passed qa after rerun:
https://pulpito.ceph.com/cbodley-2022-02-04_00:02:10-rgw-wip-cbodley-testing-distro-default-smithi/
https://pulpito.ceph.com/cbodley-2022-02-04_16:42:47-rgw-wip-cbodley-testing-distro-default-smithi/

**Pull request merged**
