### PR TITLE
osd/OSDMap: fix apply upmap segfault

### PR DESCRIPTION
**Pull request by badone**
http://tracker.ceph.com/issues/22056

### CODE REVIEW

**Comment by jdurgin** [comment]
Ah I see @badone mentioned in the tracker he'd create a separate issue for fixing the balancer. sounds good!

**Comment by badone** [comment]
@jdurgin Yes, looking into that next.

@smithfarm @theanalyst FYI needs backport

**Comment by xiexingguo** [comment]
I think the root cause is why balancer is starting to produce bad mappings and setting the guard here will instead cover something we'll definitely want to dig into.

IIRC, I fixed one similar case in https://github.com/ceph/ceph/pull/21325 (https://github.com/ceph/ceph/pull/21325/commits/47155949856e50d03b50993423acedddd14546e2), which should have been backported into https://github.com/ceph/ceph/pull/21359.

@badone Is http://tracker.ceph.com/issues/22056 still reproducable on master or the newest luminous?

**Comment by xiexingguo** [comment]
I see the broken version is 12.2.5

```
Updated by Bryan Stillwell 3 months ago
I believe I'm seeing this problem pretty consistently on my home cluster. The ceph-mgr keeps dying with a very similar backtrace at least:

-10> 2018-05-17 15:38:15.571835 7fcc48d69700  4 mgr[balancer] Optimize plan auto_2018-05-17_21:38:15
    -9> 2018-05-17 15:38:15.571887 7fcc48d69700  4 mgr get_config get_configkey: mgr/balancer/mode
    -8> 2018-05-17 15:38:15.571903 7fcc48d69700  4 mgr get_config get_configkey: mgr/balancer/max_misplaced
    -7> 2018-05-17 15:38:15.571985 7fcc48d69700  4 mgr[balancer] Mode upmap, max misplaced 0.800000
    -6> 2018-05-17 15:38:15.572414 7fcc48d69700  4 mgr[balancer] do_upmap
    -5> 2018-05-17 15:38:15.572441 7fcc48d69700  4 mgr get_config get_configkey: mgr/balancer/upmap_max_iterations
    -4> 2018-05-17 15:38:15.572448 7fcc48d69700  4 ceph_config_get upmap_max_iterations not found
    -3> 2018-05-17 15:38:15.572454 7fcc48d69700  4 mgr get_config get_configkey: mgr/balancer/upmap_max_deviation
    -2> 2018-05-17 15:38:15.572459 7fcc48d69700  4 ceph_config_get upmap_max_deviation not found
    -1> 2018-05-17 15:38:15.572597 7fcc48d69700  4 mgr[balancer] pools ['cephfs_data_ec42', 'cephfs_metadata', 'rbd', 'cephfs_data']
     0> 2018-05-17 15:38:15.577347 7fcc48d69700 -1 ** Caught signal (Segmentation fault) *
 in thread 7fcc48d69700 thread_name:balancer
ceph version 12.2.5 (cad919881333ac92274171586c827e01f554a70a) luminous (stable)
```
Since 12.2.5 got out on Apr 24 and https://github.com/ceph/ceph/pull/21359 did not land into luminous till May 8. 

I guess 12.2.5 should miss that fixer?

**Comment by xiexingguo** [comment]
See commit message of  https://github.com/ceph/ceph/commit/47155949856e50d03b50993423acedddd14546e2

Perhaps 
http://pulpito.ceph.com/yuriw-2018-04-06_21:35:03-rados-wip-yuri2-testing-2018-04-06-1946-luminous-distro-basic-smithi/2365151/ ?

**Comment by xiexingguo** [comment]
> The guard needs to be present since these values could potentially come from sources other than the balancer.

Then instead of putting the safeguard here, wouldn't  it be more appropriate to put it to the cli in OSDMonitor?

**Comment by tchaikov** [comment]
i agree with @xiexingguo . how about performing a sanity test when user (or balancer) injects  a new `pg_upmap`? so an `-EINVAL` is returned in that case. and we can `assert()` here.

**Pull request merged**
