### PR TITLE
jewel: build/ops: need rocksdb commit 7ca731b12ce for ppc64le build

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/17092

### CODE REVIEW

**Comment by smithfarm** [comment]
@tchaikov @michelmno @dachary

**Comment by dachary** [comment]
<pre>
Reviewed-by: Loic Dachary &lt;ldachary@redhat.com>
</pre>
when http://tracker.ceph.com/issues/17092#note-4 condition is met

**Comment by smithfarm** [comment]
@dachary https://github.com/ceph/rocksdb/pull/12 has been merged, so the condition has been met.

**Comment by dachary** [comment]
@smithfarm now we need at least one run of something with this pull request, right ?

**Comment by smithfarm** [comment]
@dachary That would be prudent, yes. I just pushed `wip-17092-jewel` to gitbuilders.

**Comment by smithfarm** [comment]
**running** http://pulpito.front.sepia.ceph.com/smithfarm-2016-08-23_11:07:52-rados:singleton:all:admin-socket.yaml-wip-17092-jewel---basic-smithi/

**Comment by smithfarm** [comment]
**running** http://pulpito.front.sepia.ceph.com/smithfarm-2016-08-23_12:03:35-upgrade:jewel-x-wip-17092-jewel---basic-smithi/

**Comment by smithfarm** [comment]
@tchaikov @dachary Passes "at least one run of something" - any further testing you would like to see?

**Pull request merged**
