### PR TITLE
msg/async: add "queue_reset" argument

### PR DESCRIPTION
**Pull request by yuyuyu101**
Signed-off-by: Haomai Wang <haomai@xsky.com>

### CODE REVIEW

**Comment by yuyuyu101** [comment]
fix rebase conflicting introduced(https://github.com/ceph/ceph/pull/9781)

**Comment by xiexingguo** [comment]
How about this(so we don't have the change the default behaviour of  `stop` too much):

```c++
-  void stop(bool queue_reset) {
+  void stop(bool queue_reset = true) {
     lock.Lock();
     bool need_queue_reset = (state != STATE_CLOSED) && queue_reset;

**Comment by yuyuyu101** [comment]
... there is no much difference since it's a internal interface. if possible we should be prefer avoid default argument value

**Comment by xiexingguo** [comment]
Ok, suit yourself.

**Comment by tchaikov** [comment]
lgtm.

**Pull request merged**
