### PR TITLE
test/rgw: unit tests for RGWFetchAllMetaCR

### PR DESCRIPTION
**Pull request by cbodley**
this is an experiment to build up unit tests for rgw sync coroutines. RGWFetchAllMetaCR is a convenient place to start, because it doesn't have a deep call stack - this means the factory interface is small

note that the tests for `ReadSectionsEIO` and `ReadKeysENOENT` will deadlock without https://github.com/ceph/ceph/pull/11505

### CODE REVIEW

**Comment by cbodley** [comment]
this gets pretty good coverage for `RGWFetchAllMetaCR`. i worry that the approach won't scale well though, because we have to inject factories for all of the child crs it can possibly spawn - for something like `RGWMetaSyncCR`, this is going to get messy fast

**Comment by yehudasa** [comment]
@cbodley just a thought, but maybe instead of overriding all the different crs, we can hook into RGWCoroutinesManager::run(), or create a version of it where it only really executes RGWFetchAllMetaCR; figuring the type by the typeid().name(), and then for each child cr it has a callback that modifies what it needs to accordingly. This could scale better (if feasible).

**Comment by cbodley** [comment]
pulled the fix into a separate pr: https://github.com/ceph/ceph/pull/11586

**Comment by dachary** [comment]
needs rebase :-)

**Comment by cbodley** [comment]
closing for now

**Pull request closed without merging**
