### PR TITLE
luminous: run-make-check.sh ccache tweaks

### PR DESCRIPTION
**Pull request by VictorDenisov**
http://tracker.ceph.com/issues/24826

---

Erwan Velu implemented some nice ccache tweaks for run-make-check.sh which reportedly bring a substantial performance improvement. Anything that makes "make check" easier to run would seem like a good thing, so I proposed opening up those tweaks to all users of the script. Erwan also suggested to backport the tweaks to mimic and luminous.

- [x] References tracker ticket
- [x] Updates documentation if necessary
- [x] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by VictorDenisov** [comment]
@smithfarm done

**Comment by smithfarm** [comment]
@VictorDenisov I don't understand why the FIO commits are included here - they are not related to the ccache tweaks.

**Comment by VictorDenisov** [comment]
FIO was added after luminous, but before this change in master, so I either needed to port FIO or remove FIO from the diffs. I chose to port FIO. I can just drop it from the diffs.

**Comment by smithfarm** [comment]
@VictorDenisov Assuming there is no tracker ticket asking for the FIO feature to be backported, then I would prefer to drop it since it's unrelated to this change.

**Comment by smithfarm** [comment]
@VictorDenisov This looks OK, but the Conflicts sections belong **below** the `(cherry picked from ...)` line, not above. The idea is for the person doing the cherry-pick to leave the original commit message (everything down to the `(cherry picked from . . .)` line untouched, and whatever additional information is added, to go below that line.

No urgent need to fix it in this case - but something for your next backport :-)

**Pull request merged**
