### PR TITLE
journal overflow fixup

### PR DESCRIPTION
**Pull request by oms4suse**
Fix #14932

Improve ceph-disk error message when there is not enough space to create journal partition.

### CODE REVIEW

**Comment by dachary** [comment]
it looks good to merge after jewel. Could you please add integration tests for the Ubuntu 14.04 and CentOS 7 ? They are found in ceph/qa/workunit/ceph-disk and https://github.com/ceph/ceph-qa-suite/tree/master/suites/ceph-disk/basic

**Comment by oms4suse** [comment]
@dachary I am afraid at this moment I don’t know enough about Ceph QA and don’t have the infrastructure to run this on Ubuntu 14.04 and CentOS 7.

If you could point me to some one who can help that would be great.

**Comment by smithfarm** [comment]
@oms4suse I'd be happy to run suites on Ubuntu 14.04 and CentOS 7.2 for you in our OVH tenant.

**Comment by dachary** [comment]
@smithfarm thanks for the help :-) Could you please reassign to me once the tests are passing ?

**Comment by oms4suse** [comment]
I am currently trying to get the test suite to pass, but really don’t understand the error.

if true && echo w --jobserver-fds=3,4 -j | grep --quiet -e -j && test $u -lt $n ; then \
	echo "ulimit -u is $u which is lower than $n = $p / 2 * 1024" ; \
	echo "If running make -j$p check you will likely exceed this limit" ; \
	echo "and the tests will fail in mysterious ways." ; \
	echo "Update /etc/security/limits.conf to increase the limit" ; \
	echo "or run make CHECK_ULIMIT=false -j4 check to override this safeguard." ; \
	exit 1 ; \
fi
FAIL: src/test/run-cli-tests
make[4]: Entering directory `/h

I am now trying to get "src/test/run-cli-tests" to succeed on a local build.

**Comment by oms4suse** [comment]
OK I have made "src/test/run-cli-tests" pass on master and am now rebuilding on my branch.

**Comment by oms4suse** [comment]
I have made "src/test/run-cli-tests" pass on my branch.

Maybe I am missing some thing and this test is failing because of some environment issue.

Please can I have help as to wear to look.

**Comment by smithfarm** [comment]
> it looks good to merge after jewel. Could you please add integration tests for Ubuntu 14.04 and CentOS 7 ? They are found in ceph/qa/workunit/ceph-disk and https://github.com/ceph/ceph-qa-suite/tree/master/suites/ceph-disk/basic

I am going to be doing some ceph-disk work soon, which will include adding tests to the ceph-disk suite. I'll add these tests, too.

**Comment by liewegas** [comment]
@oms4suse ping

**Comment by liewegas** [comment]
closing this.  feel free to reopen and rebase if it's still a problem!

**Pull request closed without merging**
