### PR TITLE
qa/cephfs: improvements for name generators in test_volumes.py

### PR DESCRIPTION
**Pull request by rishabh-d-dave**
Generate a shorter, easier to remember name. Also, write a simpler,
faster & better helper method for generating unique names.

Fixes: https://tracker.ceph.com/issues/63680

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [x] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Comment by rishabh-d-dave** [comment]
https://pulpito.ceph.com/rishabh-2023-11-23_14:37:05-fs:volumes-mgr-vol-misc2-testing-default-smithi/

**Review by vshankar — APPROVED** [review]
(conditional approve)

LGTM once this change passes tests.

**Comment by rishabh-d-dave** [comment]
https://pulpito.ceph.com/rishabh-2023-11-23_14:37:05-fs:volumes-mgr-vol-misc2-testing-default-smithi
https://pulpito.ceph.com/rishabh-2023-11-24_05:41:33-fs:volumes-rishabh-mgr-vol-misc-testing-default-smithi
https://pulpito.ceph.com/rishabh-2023-11-24_07:31:48-fs:volumes-rishabh-mgr-vol-misc-testing-default-smithi

**Comment by rishabh-d-dave** [comment]
https://pulpito.ceph.com/rishabh-2023-11-24_08:24:50-fs:volumes-rishabh-mgr-vol-misc-testing-default-smithi/

**Comment by rishabh-d-dave** [comment]
https://pulpito.ceph.com/rishabh-2023-11-24_16:45:14-fs:volumes-rishabh-mgr-vol-misc-testing-default-smithi/

All tests passed.

**Comment by vshankar** [comment]
@rishabh-d-dave let's backport this, Please create a tracker and link it in the commit message.

**Comment by rishabh-d-dave** [comment]
https://pulpito.ceph.com/rishabh-2023-11-26_06:51:12-fs:volumes-rishabh-mgr-vol-misc-testing-default-smithi/
https://pulpito.ceph.com/rishabh-2023-11-28_12:42:13-fs:volumes-rishabh-mgr-vol-misc-testing-default-smithi/
https://pulpito.ceph.com/rishabh-2023-11-29_11:43:01-fs:volumes-mgr-vol-misc-2023nov3-testing-default-smithi/

**Comment by rishabh-d-dave** [comment]
https://pulpito.ceph.com/rishabh-2023-11-29_12:25:49-fs:volumes-mgr-vol-misc-2023nov3-testing-default-smithi/

Tests ran successfully.

**Comment by rishabh-d-dave** [comment]
> @rishabh-d-dave let's backport this. Please create a tracker and link it in the commit message.

Done.

**Comment by rishabh-d-dave** [comment]
https://jenkins.ceph.com/job/ceph-api/65491/

**Comment by rishabh-d-dave** [comment]
jenkins test api

**Comment by rishabh-d-dave** [comment]
https://jenkins.ceph.com/job/ceph-pull-requests/125833/

**Comment by rishabh-d-dave** [comment]
jenkins test make check

**Review by vshankar — APPROVED** [review]

**Pull request merged**
