### PR TITLE
tests: more robust tiering agent tests

### PR DESCRIPTION
**Pull request by dachary**
http://tracker.ceph.com/issues/11359

### CODE REVIEW

**Comment by liewegas** [comment]
lgtm!

**Comment by dachary** [comment]
@liewegas I searched for ceph-qa-suite jobs running these but only found
<pre>
suites/upgrade/old/mixed-mons/mixed-mons/2-cuttlefish-workload/cephtool.yaml:6:        - cephtool/test.sh
suites/upgrade/old/mixed-mons/mixed-mons/5-mixed-workload/cephtool.yaml:6:        - cephtool/test.sh
suites/upgrade/old/mixed-mons/mixed-mons/6-rest/rest.yaml:25:      - cephtool/test.sh
</pre>
which are presumably not run because old. Am I missing something ?

**Comment by liewegas** [comment]
suites/rados/singleton/all/cephtool.yaml:        - cephtool

(which runs everything in the directory)

**Comment by dachary** [comment]
@liewegas  if this light weight QA is not enough, feel free to re-add the **needs-qa**

<pre>
./virtualenv/bin/teuthology-suite --priority 101 --suite rados/singleton/all/cephtool.yaml --suite-branch master --machine-type plana,burnupi,mira --distro ubuntu --email loic@dachary.org --ceph wip-11359-tier-tests
</pre>
http://pulpito.ceph.com/loic-2015-05-15_22:26:07-rados:singleton:all:cephtool.yaml-wip-11359-tier-tests---basic-multi/894105/

**Comment by dachary** [comment]
I should have mentioned the test is running ... and it turns out it failed. I'll investigate why.

**Comment by dachary** [comment]
<pre>
2015-05-15T13:53:16.231 INFO:tasks.workunit.client.0.plana20.stderr:  test_mon_osd: 1039: ceph osd create
2015-05-15T13:53:18.337 INFO:tasks.workunit.client.0.plana20.stderr: test_mon_osd: 1039: id=5
2015-05-15T13:53:18.338 INFO:tasks.workunit.client.0.plana20.stderr: test_mon_osd: 1040: '[' 5 = 4 ']'
2015-05-15T13:53:18.338 INFO:tasks.workunit.client.0.plana20.stderr: test_mon_osd: 1: rm -fr /tmp/cephtool11153
</pre>

Running again to verify if it is a persistent error. I don't see how it could be related to the tiering agent tests.

http://pulpito.ceph.com/loic-2015-05-15_23:10:22-rados:singleton:all:cephtool.yaml-wip-11359-tier-tests---basic-multi/

**Comment by dachary** [comment]
Same error, definitely not a transient error
<pre>
2015-05-15T14:27:23.785 INFO:tasks.workunit.client.0.burnupi24.stderr:  test_mon_osd: 1039: ceph osd create
2015-05-15T14:27:25.173 INFO:tasks.workunit.client.0.burnupi24.stderr: test_mon_osd: 1039: id=5
2015-05-15T14:27:25.173 INFO:tasks.workunit.client.0.burnupi24.stderr: test_mon_osd: 1040: '[' 5 = 4 ']'
2015-05-15T14:27:25.173 INFO:tasks.workunit.client.0.burnupi24.stderr: test_mon_osd: 1: rm -fr /tmp/cephtool11799
</pre>

**Comment by dachary** [comment]
Oh well, that's http://tracker.ceph.com/issues/11618, unrelated after all ;-)

**Pull request merged**
