### PR TITLE
qa: increase fs/snaps workunit timeout to 6h

### PR DESCRIPTION
**Pull request by vshankar**
commit 4fbf4c4f58561cbcd023ba2877dcbd02c8915d65 increases the
number of tags used in snaptest-git-ceph.sh tests. This makes
the tests run longer (than default 3h) thereby timing out.

Signed-off-by: Venky Shankar <vshankar@redhat.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by lxbsz** [comment]
Hi Venky, BTW, have you seen the timeout failures in qa teuthology tests recently ?

**Comment by vshankar** [comment]
> Hi Venky, BTW, have you seen the timeout failures in qa teuthology tests recently ?

yeh - https://pulpito.ceph.com/vshankar-2022-06-19_08:22:46-fs-wip-vshankar-testing1-20220619-102531-testing-default-smithi/6886684/

the test was still running with a tag version.

**Comment by lxbsz** [comment]
> > Hi Venky, BTW, have you seen the timeout failures in qa teuthology tests recently ?
> 
> yeh - https://pulpito.ceph.com/vshankar-2022-06-19_08:22:46-fs-wip-vshankar-testing1-20220619-102531-testing-default-smithi/6886684/
> 
> the test was still running with a tag version.

Okay, sounds reasonable. LGTM.

**Review by lxbsz — APPROVED** [review]
LGTM.

For another bug [1] I am also planing to increase the test numbers, which is also not easy to be seen.

[1] https://tracker.ceph.com/issues/56011

**Comment by dparmar18** [comment]
Looks good but is there any way we can reduce the time by running tests in parallel?

**Comment by vshankar** [comment]
> Looks good but is there any way we can reduce the time by running tests in parallel?

We can, but that's not the point of this test ;)

**Comment by gregsfortytwo** [comment]
Don't we have a hard 3-hour timeout from teuthology anyway? (Or maybe it's 6 and that's where the new timeout comes from?) I'm not sure bumping up this number will do anything.

**Comment by mchangir** [comment]
> Don't we have a hard 3-hour timeout from teuthology anyway? (Or maybe it's 6 and that's where the new timeout comes from?) I'm not sure bumping up this number will do anything.

The teuthology worker has a hard timeout of 6:30 hours.

**Comment by vshankar** [comment]
ceph test windows

**Review by vshankar — COMMENTED** [review]
https://tracker.ceph.com/projects/cephfs/wiki/Main#2022-July-04

**Comment by vshankar** [comment]
> ceph test windows

oh brilliant! excuse me to for that - its a Monday morning!

**Comment by vshankar** [comment]
jenkins test windows

**Pull request merged**
