### PR TITLE
mimic: mgr/dashboard: Use human readable units on the OSD I/O graphs

### PR DESCRIPTION
**Pull request by tspmelo**
http://tracker.ceph.com/issues/26986

### CODE REVIEW

**Comment by tspmelo** [comment]
jenkins retest this please

**Comment by tspmelo** [comment]
jenkins retest this please

**Comment by tspmelo** [comment]
jenkins retest this please

**Comment by smithfarm** [comment]
jenkins re-test this please

**Comment by yuriw** [comment]
[wip-yuri2-testing-2019-04-29-1936-mimic](https://trello.com/c/dXehT7mH/597-wip-yuri2-testing-2019-04-29-1936-mimic)

**Pull request merged**
