### PR TITLE
rgw: fix not responding when receiving SIGHUP signal.

### PR DESCRIPTION
**Pull request by yaozongyou**
Fix rgw not responding occasionally when receiving SIGHUP signal.

Signed-off-by: Yao Zongyou <yaozongyou@vip.qq.com>

### CODE REVIEW

**Comment by yaozongyou** [comment]
In UserSyncThread, if stats->sync_all_users() is being executed, and at the same time, if rgw got SIGHUP signal, UserSyncThread will be stopped by pthread_cond_broadcast to signal UserSyncThread. But pthread_cond_broadcast has no effect if UserSyncThread not blocking on cond.

**Comment by yaozongyou** [comment]
Add an issue in tracker: 
http://tracker.ceph.com/issues/20937
In this issue I have posted all's thread backtrace output.

**Comment by yaozongyou** [comment]
By the way, BucketSyncThread already has checked the condition before cond wait, so BucketSyncThread has no problem:
https://github.com/ceph/ceph/pull/16854/files#diff-95097285ada57e2bc495b190cce172d7L472

**Comment by mattbenjamin** [comment]
@yaozongyou  I'm probably misunderstanding the code, but it looks like the actual change omits a wait when going_down() is true, but without the change, the loop test for going_down() would have cause the thread to exit after the wait period;  is there any exceptional condition (e.g., segv) or hang during operation that this change fixes?

**Comment by yaozongyou** [comment]
Yes, it only omits a wait. But the default value for rgw_user_quota_sync_interval is 3600 * 24 seconds, it is too long. And it blocks RGWRealmReloader::reload to complete, and during this period, rgw can not process new requests.

**Comment by mattbenjamin** [comment]
@yaozongyou ok, cool

**Comment by yuriw** [comment]
http://pulpito.ceph.com/yuriw-2017-08-08_01:46:01-rgw-wip-yuri-testing3_2017_8_8-distro-basic-smithi/

http://pulpito.ceph.com/yuriw-2017-08-08_03:54:14-rgw-wip-yuri-testing3_2017_8_8-distro-basic-smithi/

**Comment by theanalyst** [comment]
Needs a backport back to Luminous

**Pull request merged**
