### PR TITLE
cephfs: fix missing ll_get for ll_walk

### PR DESCRIPTION
**Pull request by guihecheng**
Fixs: http://tracker.ceph.com/issues/18086

Signed-off-by: Gui Hecheng <guihecheng@cmss.chinamobile.com>

### CODE REVIEW

**Comment by dachary** [comment]
jenkins test this please (eio now ignored on master)

**Comment by gregsfortytwo** [comment]
@guihecheng, what makes you think this is necessary here? Just something you saw by code inspection, or did you run into a bug?

**Comment by gregsfortytwo** [comment]
@jtlayton, I think you did some ref-counting patches recently, any thoughts? We don't use this in ceph-fuse, but it's exposed in the libcephfs bindings.

**Comment by jcsp** [comment]
This does look sensible since we're returning the raw inode pointer to the caller.  Like Greg I am curious about how the issue was exposed though.

**Comment by jcsp** [comment]
(This passes tests here http://pulpito.ceph.com/jspray-2016-11-22_10:40:59-fs-wip-jcsp-testing-20161121-distro-basic-smithi/)

**Comment by jcsp** [comment]
@gregsfortytwo @jtlayton please merge at will once you're satisfied that it makes sense to you

**Comment by guihecheng** [comment]
@gregsfortytwo @jcsp @jtlayton  Oh, actually I catch this when dealing with a bug for nfs-ganesha, which uses libcephfs.
nfs-ganesha FSAL_CEPH do an ceph_ll_walk to lookup a path for exporting(this creates a filehandle) and tries to do ceph_ll_put() upon releasing every filehandle.
If we do not first ll_get() in ceph_ll_walk, we will get a segfault in ceph_ll_put().
And I think it is reasonable to do ll_get() since we're returning the raw inode pointer to the caller as as @jcsp said.

**Comment by jcsp** [comment]
@guihecheng please can you open a ticket on tracker.ceph.com for the crash you experienced, and add a "Fixes: " line to the commit message here that references that ticket.

(Having tickets makes it simpler when we backport fixes like this and in case any users see them)

**Comment by gregsfortytwo** [comment]
test this please

**Comment by dachary** [comment]
jenkins test this please (test_objectstore_memstore.sh  timeout http://tracker.ceph.com/issues/18027)

**Comment by guihecheng** [comment]
@dachary sorry, IMHO, this commit shall not cause such problem, because it is only related to cephfs + ganesha scenario and only nfs-ganesha FSAL_CEPH uses this interface ll_walk.

**Comment by tchaikov** [comment]
@guihecheng no worries,  we are just trying to identify and fix all irrelevant "make check" failures.

**Comment by tchaikov** [comment]
```
Total Test time (real) = 3981.25 sec

The following tests FAILED:
	137 - osd-scrub-repair.sh (Timeout)
```

retest this please, jenkins.

**Comment by guihecheng** [comment]
@tchaikov oh, thanks for your help :)

**Comment by guihecheng** [comment]
@jcsp Oh, sorry for the late reply, I will do it on the tracker soon. (The tracker seems to be migrating to a new location.)

**Comment by jcsp** [comment]
@guihecheng to clarify, the "Fixes" line needs to go into the commit message (i.e. do a git commit --amend and re-push), not just the pull request description.

**Comment by guihecheng** [comment]
@jcsp yes, I have re-pushed, the fix line goes to the commit message now.

**Pull request merged**
