### PR TITLE
cleanup code when met crc error.

### PR DESCRIPTION
**Pull request by majianpeng**
This patche set mainly cleanup the code about meeting crc error when reading the whole object. At the original, if this occur, it will send the error-data to client.  Those patch will cleanup some code.

### CODE REVIEW

**Comment by majianpeng** [comment]
@tchaikov . Can you review this? Thanks!

**Comment by majianpeng** [comment]
@tchaikov . Ping

**Comment by tchaikov** [comment]
@majianpeng sorry for the latency, it's out of my radar. will review it shortly!

**Comment by tchaikov** [comment]
@majianpeng reviewed, generally looks good. just some nits. also need to resolve the conflicts.

**Comment by majianpeng** [comment]
@tchaikov . Updated and please review again. Thanks!

**Comment by majianpeng** [comment]
@tchaikov . updated and please review again. Thanks!

**Comment by tchaikov** [comment]
i think the 4a85af5 failed the test of http://pulpito.ceph.com/kchai-2015-09-12_20:16:25-rados-wip-kefu-testing---basic-multi/1053246/ and more test jobs in that batch.

**Comment by majianpeng** [comment]
@tchaikov . updated and sorry for my careless. Thanks!

**Comment by tchaikov** [comment]
@majianpeng so you decided to remove the `std::endl` change, right? and this pull request is again ready for review?

**Comment by majianpeng** [comment]
Yes,

**Pull request merged**
