### PR TITLE
doc/dev/osd_internals/manifest.rst: add information about clone snap refcounting

### PR DESCRIPTION
**Pull request by myoungwon**
Signed-off-by: Samuel Just <sjust@redhat.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by myoungwon** [comment]
jenkins test dashboard

**Comment by myoungwon** [comment]
retest this please

**Comment by myoungwon** [comment]
retest this please

**Comment by athanatos** [comment]
retest this please

**Pull request merged**
