### PR TITLE
crimson/os/seastore: add missing hints in omap tree

### PR DESCRIPTION
**Pull request by cyx1231st**
Signed-off-by: Yingxin Cheng <yingxin.cheng@intel.com>

See https://github.com/ceph/ceph/pull/43215#issuecomment-924510457

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by cyx1231st** [comment]
jenkins test signed

**Comment by cyx1231st** [comment]
Emm.. Not sure why it cannot pass the Signed-off-by check.

**Comment by athanatos** [comment]
retest this please

**Review by liu-chunmei — APPROVED** [review]

**Comment by tchaikov** [comment]
> Emm.. Not sure why it cannot pass the Signed-off-by check.

```
+ local path=/tmp/venv.0D0Gwn9bMl
+ '[' -d /tmp/venv.0D0Gwn9bMl ']'
+ command -v python3
+ virtualenv -p python3 /tmp/venv.0D0Gwn9bMl
/tmp/jenkins5609477504730019125.sh: line 106: virtualenv: command not found
```
Seems we need to use the venv python module to create the virtual venv instead of using `virtualenv` tools.

Will create a fix late today.

**Review by athanatos — APPROVED** [review]

**Comment by tchaikov** [comment]
https://github.com/ceph/ceph-build/pull/1910

**Comment by tchaikov** [comment]
jenkins test signed

**Comment by tchaikov** [comment]
jenkins test signed

**Pull request merged**
