### PR TITLE
luminous: mds: crash when failover

### PR DESCRIPTION
**Pull request by pdvian**
http://tracker.ceph.com/issues/23946

### CODE REVIEW

**Comment by pdvian** [comment]
@smithfarm @batrick Please add DNM label to this PR as we need to cherry pick PR#21769 once gets merged to master

**Comment by smithfarm** [comment]
@pdvian https://github.com/ceph/ceph/pull/21769 has been merged to master

**Comment by pdvian** [comment]
@smithfarm thank you. I will cherry-pick #21769 and will update this PR.

**Comment by pdvian** [comment]
@smithfarm @batrick @ukernel need review. I have cherry-picked #21769 to this backport PR

**Comment by smithfarm** [comment]
jenkins test docs

**Comment by ukernel** [comment]
http://pulpito.ceph.com/?branch=wip-luminous-integration-20180530

**Pull request merged**
