### PR TITLE
mon: initialize data store stats structs to avoid weird behaviors

### PR DESCRIPTION
**Pull request by jecluis**
``Signed-off-by: Joao Eduardo Luis <joao@redhat.com>``

### CODE REVIEW

**Comment by liewegas** [comment]
looks good.  can you add these structs to test/encoding/types.h so we have better test coverage?  that usually picks up these uninitialized field errors

**Comment by liewegas** [comment]
@jecluis oops, just noticed this.. probalby needs a rebase?

**Comment by jecluis** [comment]
@liewegas, opened a new PR against hammer; do you want me to rebase this one on master or should we merge into hammer instead?

**Comment by dachary** [comment]
it's now merged in master

**Pull request closed without merging**
