### PR TITLE
Revert "os/bluestore: Enable sharding by default"

### PR DESCRIPTION
**Pull request by sebastian-philipp**
This is just a changeset to attempt to get the cephadm upgrade tests running again. Let's see if this is already enough to get the tests pass. 

not intended to get merged.

Relates to https://tracker.ceph.com/issues/45335

This reverts commit aa1a116f9eef5d6fbe09d6ed99910223451431f1.

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by tchaikov** [comment]
the right fix of #34864 is still being tested.

**Comment by sebastian-philipp** [comment]
> APPROVE!

@aclamk you'll then take care of re-enabling this, as soon as you're finished with #34864 ?

**Comment by aclamk** [comment]
> > APPROVE!
> 
> @aclamk you'll then take care of re-enabling this, as soon as you're finished with #34864 ?

If this one merges, re-enabling will became part of #34864.

**Comment by sebastian-philipp** [comment]
http://pulpito.ceph.com/swagner-2020-05-11_17:25:18-rados-wip-swagner-testing-2020-05-11-1648-distro-basic-smithi/

**Pull request merged**
