### PR TITLE
Revert "test: librados startup/shutdown racer test"

### PR DESCRIPTION
**Pull request by liewegas**
This reverts commit 9b6ed03e607fe150c40f977043788efbd5116ddd.

Reverting this until we have a fix for https://tracker.ceph.com/issues/42026

Signed-off-by: Sage Weil <sage@redhat.com>

### CODE REVIEW

**Comment by batrick** [comment]
My philosophy is that persistent test failures help focus attention on fixing the underlying bug. This is why I merged the test even though no fix was available.

With that said, if it is really disruptive, please go ahead and revert.

**Comment by batrick** [comment]
Adding on: my fear is that this won't get fixed if it's not making noise. The libcephfs shutdown race test will still fail and we kinda do need that one for Ganesha (for which the test was constructed).

**Comment by liewegas** [comment]
retest this please

**Comment by liewegas** [comment]
@rzarzynski is working on it--won't get forgotten!

**Comment by tchaikov** [comment]
http://pulpito.ceph.com/kchai-2019-10-28_03:11:42-rados-wip-kefu-testing-2019-10-28-0018-distro-basic-smithi/

**Pull request merged**
