### PR TITLE
hammer: osd: remove all stale osdmaps in handle_osd_map()

### PR DESCRIPTION
**Pull request by tchaikov**
in a large cluster, there are better chances that the OSD fails to trim
the cached osdmap in a timely manner. and sometimes, it is just unable
to keep up with the incoming osdmap if skip_maps, so the osdmap cache
can keep building up to over 250GB in size. in this change

* publish_superblock() before trimming the osdmaps, so other osdmap
  consumers of OSDService.superblock won't access the osdmaps being
  removed.
* trim all stale osdmaps in batch of conf->osd_target_transaction_size
  if skip_maps is true. in my test, it happens when the osd only
  receives the osdmap from monitor occasionally because the osd happens
  to be chosen when monitor wants to share a new osdmap with a random
  osd.
* always use dedicated transaction(s) for trimming osdmaps. so even in
  the normal case where we are able to trim all stale osdmaps in a
  single batch, a separated transaction is used. we can piggy back
  the commits for removing maps, but we keep it this way for simplicity.
* use std::min() instead MIN() for type safety

Fixes: http://tracker.ceph.com/issues/13990
Signed-off-by: Kefu Chai <kchai@redhat.com>
(cherry picked from commit 369db9930887d75b498927da9c97733bff4472b6)

Conflicts:
    remove the C++11ism

### CODE REVIEW

**Comment by tchaikov** [comment]
http://tracker.ceph.com/issues/15193

**Comment by tchaikov** [comment]
should wait until all

* https://github.com/ceph/ceph/pull/8017
* https://github.com/ceph/ceph/pull/8990
* https://github.com/ceph/ceph/pull/9108

are merged.

**Comment by tchaikov** [comment]
retest this please

**Comment by tchaikov** [comment]
the test failed due to env issue
```
FAIL: test/test-ceph-helpers.sh
../test-driver: line 126: test/test-ceph-helpers.sh.trs: No space left on device
../test-driver: line 127: test/test-ceph-helpers.sh.trs: No space left on device
../test-driver: line 128: test/test-ceph-helpers.sh.trs: No space left on device
../test-driver: line 129: test/test-ceph-helpers.sh.trs: No space left on device
make[5]: *** [test/test-ceph-helpers.sh.log] Error 1
make[5]: *** Waiting for unfinished jobs....
```

**Comment by tchaikov** [comment]
retest this please.

**Comment by vumrao** [comment]
test this please.

**Comment by athanatos** [comment]
I think this is causing trouble on hammer (not sure, but this one jumps out) http://tracker.ceph.com/issues/16639

**Comment by tchaikov** [comment]
should remove 5793b13492feecad399451e3a83836722b6e9abc from this changeset.

**Comment by tchaikov** [comment]
but before removing it, i will do a final check.

**Comment by smithfarm** [comment]
@tchaikov Thanks for looking at it. There's at least one other issue in the current hammer-backports branch, which I fixed in https://github.com/ceph/ceph/pull/10227 - once you remove 5793b13 from this PR I can do another round of tests, hopefully with better results.

**Comment by tchaikov** [comment]
changelog

- dropping 5793b13 which leads to http://tracker.ceph.com/issues/16639

**Comment by smithfarm** [comment]
@athanatos This PR is in the latest round of hammer-backports integration tests, which passed a rados run (the only failures are a valgrind false positive that has since been fixed by https://github.com/ceph/teuthology/pull/915 and http://tracker.ceph.com/issues/15139 which is an infrastructure issue with two of the tests) - for details, see: http://tracker.ceph.com/issues/15895#note-18

Do you think this PR is OK to merge?

**Comment by athanatos** [comment]
If @tchaikov is ok with it, I'm ok with it.

**Comment by tchaikov** [comment]
yeah, i 👍 for my PR!

**Pull request merged**
