### PR TITLE
octopus: mgr/prometheus: Sync and backport prometheus fixes

### PR DESCRIPTION
**Pull request by b-ranto**
## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by b-ranto** [comment]
This backports https://github.com/ceph/ceph/pull/38277, health check metric and https://github.com/ceph/ceph/pull/38264 to octopus.

**Comment by b-ranto** [comment]
jenkins test make check

**Comment by smithfarm** [comment]
jenkins test make check

**Comment by b-ranto** [comment]
Added https://github.com/ceph/ceph/pull/38436/commits -- a minor (one-line) clean-up after the patch set.

**Review by tchaikov — APPROVED** [review]

**Comment by yuriw** [comment]
@b-ranto pls rebase

**Comment by smithfarm** [comment]
@b-ranto (repeat ping) Please rebase?

**Comment by b-ranto** [comment]
@smithfarm ah, sorry, missed this the first time, rebased

**Comment by yuriw** [comment]
[wip-yuri4-testing-2021-01-28-0959-octopus](https://trello.com/c/3fGwTxh0/1128-wip-yuri4-testing-2021-01-28-0959-octopus)

**Pull request merged**
