### PR TITLE
Revert "mimic: cephfs-journal-tool: enable purge_queue journal's event commands"

### PR DESCRIPTION
**Pull request by ukernel**
Reverts ceph/ceph#23818. It causes purge queue corruption

### CODE REVIEW

**Comment by batrick** [comment]
No master revert? The problem looks to be that the on-disk version wasn't bumped?

**Comment by ukernel** [comment]
master is reverted by 65ae72a1e6dc5440e02535f5b559c9a4006d1ba9

**Comment by batrick** [comment]
Three things:

1. Add signed-off-by.
2. Reference this tracker: http://tracker.ceph.com/issues/36346
3. Please also add the correct backport to this PR on top of the revert.

**Comment by batrick** [comment]
Zheng, we also need an upgrade procedure for the Mimic 13.3.3 release notes for new CephFS deployments on  13.2.2.

**Comment by smithfarm** [comment]
In addition to what @batrick wrote, I would like to see the mimic commit message reference 65ae72a1e6dc5440e02535f5b559c9a4006d1ba9 somehow - preferably by redoing it using `git cherry-pick -x`. 

If it's not possible/desirable to cherry-pick this commit directly, the commit message could say something like "In master, this revert was executed by 65ae72a1e6dc5440e02535f5b559c9a4006d1ba9".

**Comment by ukernel** [comment]
open new PR https://github.com/ceph/ceph/pull/24485

**Pull request closed without merging**
