### PR TITLE
mgr/dashboard: E2E Failure: CRUSH map page

### PR DESCRIPTION
**Pull request by avanthakkar**
This PR fixes the e2e failure for CRUSH map page > fields check > should check that title & table appears (flaky test).

Fixes: https://tracker.ceph.com/issues/49857
Signed-off-by: Avan Thakkar <athakkar@redhat.com>

## Checklist
- [x] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by epuertat** [comment]
@avanthakkar could you please add a brief comment about why this change fixes the issue?

**Comment by avanthakkar** [comment]
> @avanthakkar could you please add a brief comment about why this change fixes the issue?

Unfortunately I think the current approach will fail too. I was not 100% sure as error it showed was `cy.click() failed as element was detached from DOM`, so I thought we are not clicking the correct element(as when you click the node it's actually node-content-wrapper which gets clicked). So I thought if we make this element to be clickable instead for e2e to pass will work. But unfortunately all assumptions were wrong. On checking the html loaded on the crush-map page I saw this (and searching for `node-name` class):

https://user-images.githubusercontent.com/23611106/111525970-26b8a500-8784-11eb-8b37-a2b137ce4641.mp4

After searching for `node-name` class if I try to see it's occurence and click on that piece of code, before I can see it it vanishes (I think it's because we are subscribing to full-health every 5s in crush-map component), so the same happens when cypress tries to find and click on it it's not there it's gone, until it appears again, but the issue is before it clicks it's already gone! So I think some refactoring needs to be done in component itself.

**Comment by epuertat** [comment]
@avanthakkar did you check [this StackOverflow question](https://stackoverflow.com/questions/61123611/cypress-click-failed-because-this-element-is-detached-from-the-dom-in-iteratio)?

**Comment by avanthakkar** [comment]
> @avanthakkar did you check [this StackOverflow question](https://stackoverflow.com/questions/61123611/cypress-click-failed-because-this-element-is-detached-from-the-dom-in-iteratio)? Or [this](https://docs.cypress.io/guides/references/error-messages.html#cy-failed-because-the-element-you-are-chaining-off-of-has-become-detached-or-removed-from-the-dom)?

Yes, have looked at both, but not useful in this case. I still have to investigate more about the issue I found 

> > @avanthakkar could you please add a brief comment about why this change fixes the issue?
> 
> Unfortunately I think the current approach will fail too. I was not 100% sure as error it showed was `cy.click() failed as element was detached from DOM`, so I thought we are not clicking the correct element(as when you click the node it's actually node-content-wrapper which gets clicked). So I thought if we make this element to be clickable instead for e2e to pass will work. But unfortunately all assumptions were wrong. On checking the html loaded on the crush-map page I saw this (and searching for `node-name` class):
> Screencast.from.03-18-2021.12.44.19.AM.mp4
> 
> After searching for `node-name` class if I try to see it's occurence and click on that piece of code, before I can see it it vanishes (I think it's because we are subscribing to full-health every 5s in crush-map component), so the same happens when cypress tries to find and click on it it's not there it's gone, until it appears again, but the issue is before it clicks it's already gone! So I think some refactoring needs to be done in component itself.



> @avanthakkar did you check [this StackOverflow question](https://stackoverflow.com/questions/61123611/cypress-click-failed-because-this-element-is-detached-from-the-dom-in-iteratio)? Or [this](https://docs.cypress.io/guides/references/error-messages.html#cy-failed-because-the-element-you-are-chaining-off-of-has-become-detached-or-removed-from-the-dom)?

Yes, already have seen quite a few similar issues and also this https://github.com/cypress-io/cypress/issues/7306 , but it didn't quite help. I still have to investigate more about the issue I mentioned here 
https://github.com/ceph/ceph/pull/40176#issuecomment-801349431

**Comment by avanthakkar** [comment]
> > @avanthakkar did you check [this StackOverflow question](https://stackoverflow.com/questions/61123611/cypress-click-failed-because-this-element-is-detached-from-the-dom-in-iteratio)? Or [this](https://docs.cypress.io/guides/references/error-messages.html#cy-failed-because-the-element-you-are-chaining-off-of-has-become-detached-or-removed-from-the-dom)?
> 
> Yes, already have seen quite a few similar issues and also this [cypress-io/cypress#7306](https://github.com/cypress-io/cypress/issues/7306) , but it didn't quite help (I already tried with `cy.contains()` thing which is the most suggested solution also in stackoveflow question you mentioned, but it didn't work). I still have to investigate more about the issue I mentioned here
> [#40176 (comment)](https://github.com/ceph/ceph/pull/40176#issuecomment-801349431)

I did some more debugging and it seems like this issue came in after some refactoring was done in crush-map component here https://github.com/ceph/ceph/pull/38963. We also discussed on doing some refactoring in backend & frontend for crush-map which is tracked here https://tracker.ceph.com/issues/49236. So my proposal is to first go for this refactoring and then deal with the e2e tests (in case if we face the same e2e failure). What you think @epuertat @alfonsomthd ?

**Comment by avanthakkar** [comment]
The fix will get covered here https://github.com/ceph/ceph/pull/40311

**Comment by epuertat** [comment]
Continuing work here: https://github.com/ceph/ceph/pull/40311

**Pull request closed without merging**
