### PR TITLE
librados: fix pool alignment API overflow issue and tests

### PR DESCRIPTION
**Pull request by xiexingguo**
The original APIs may overflow and are replaced by 1f855456cae96c91a67c169d2333e333c3b59671.
Signed-off-by: xie xingguo <xie.xingguo@zte.com.cn>

### CODE REVIEW

**Comment by xiexingguo** [comment]
Dear @tchaikov, would you please review this? As you can see this is a  supplemented commit for https://github.com/ceph/ceph/pull/6489.

**Comment by jdurgin** [comment]
lgtm

**Comment by tchaikov** [comment]
lgtm.

**Comment by liewegas** [comment]
[  FAILED  ] 11 tests, listed below:
[  FAILED  ] LibRadosIo.TooBig
[  FAILED  ] LibRadosIo.ReadTimeout
[  FAILED  ] LibRadosIo.RoundTrip
[  FAILED  ] LibRadosIo.OverlappingWriteRoundTrip
[  FAILED  ] LibRadosIo.WriteFullRoundTrip
[  FAILED  ] LibRadosIo.AppendRoundTrip
[  FAILED  ] LibRadosIo.TruncTest
[  FAILED  ] LibRadosIo.RemoveTest
[  FAILED  ] LibRadosIo.XattrsRoundTrip
[  FAILED  ] LibRadosIo.RmXattr
[  FAILED  ] LibRadosIo.XattrIter

ceph_test_rados_api_io

**Comment by xiexingguo** [comment]
@liewegas  I doubt the above UT failures have something to do with this fix. Is it possible due to the unstability of the bot itself? As you can see it can't work very well recently.

**Comment by xiexingguo** [comment]
I repush it to trigger another check and pass, but the result is somewhat not as intuitive as it used to be.

**Comment by liewegas** [comment]
The failure was triggered by a teuthology run, but I also reproduced it 
locally but just running ./ceph_test_rados_api_io

**Comment by xiexingguo** [comment]
@liewegas OK, I will try to reproduce it locally and get everything done.
Wish you merry christmas and happy new year:)

**Comment by xiexingguo** [comment]
@liewegas 
I rebased this fix to the latest master and passed the examination, below is the test result:
[root@c8 src]# ./ceph_test_rados_api_io
Running main() from gmock_main.cc
[==========] Running 50 tests from 4 test cases.
[----------] Global test environment set-up.
[----------] 12 tests from LibRadosIo
[ RUN      ] LibRadosIo.SimpleWrite
[       OK ] LibRadosIo.SimpleWrite (8124 ms)
[ RUN      ] LibRadosIo.TooBig
[       OK ] LibRadosIo.TooBig (5 ms)
[ RUN      ] LibRadosIo.ReadTimeout
[       OK ] LibRadosIo.ReadTimeout (5508 ms)
[ RUN      ] LibRadosIo.RoundTrip
[       OK ] LibRadosIo.RoundTrip (701 ms)
[ RUN      ] LibRadosIo.OverlappingWriteRoundTrip
[       OK ] LibRadosIo.OverlappingWriteRoundTrip (417 ms)
[ RUN      ] LibRadosIo.WriteFullRoundTrip
[       OK ] LibRadosIo.WriteFullRoundTrip (416 ms)
[ RUN      ] LibRadosIo.AppendRoundTrip
[       OK ] LibRadosIo.AppendRoundTrip (485 ms)
[ RUN      ] LibRadosIo.TruncTest
[       OK ] LibRadosIo.TruncTest (529 ms)
[ RUN      ] LibRadosIo.RemoveTest
[       OK ] LibRadosIo.RemoveTest (393 ms)
[ RUN      ] LibRadosIo.XattrsRoundTrip
[       OK ] LibRadosIo.XattrsRoundTrip (379 ms)
[ RUN      ] LibRadosIo.RmXattr
[       OK ] LibRadosIo.RmXattr (1209 ms)
[ RUN      ] LibRadosIo.XattrIter
[       OK ] LibRadosIo.XattrIter (584 ms)
[----------] 12 tests from LibRadosIo (18750 ms total)

[----------] 14 tests from LibRadosIoPP
[ RUN      ] LibRadosIoPP.SimpleWritePP
[       OK ] LibRadosIoPP.SimpleWritePP (7207 ms)
[ RUN      ] LibRadosIoPP.ReadOpPP
[       OK ] LibRadosIoPP.ReadOpPP (334 ms)
[ RUN      ] LibRadosIoPP.SparseReadOpPP
[       OK ] LibRadosIoPP.SparseReadOpPP (275 ms)
[ RUN      ] LibRadosIoPP.RoundTripPP
[       OK ] LibRadosIoPP.RoundTripPP (275 ms)
[ RUN      ] LibRadosIoPP.RoundTripPP2
[       OK ] LibRadosIoPP.RoundTripPP2 (477 ms)
[ RUN      ] LibRadosIoPP.OverlappingWriteRoundTripPP
[       OK ] LibRadosIoPP.OverlappingWriteRoundTripPP (557 ms)
[ RUN      ] LibRadosIoPP.WriteFullRoundTripPP
[       OK ] LibRadosIoPP.WriteFullRoundTripPP (425 ms)
[ RUN      ] LibRadosIoPP.WriteFullRoundTripPP2
[       OK ] LibRadosIoPP.WriteFullRoundTripPP2 (388 ms)
[ RUN      ] LibRadosIoPP.AppendRoundTripPP
[       OK ] LibRadosIoPP.AppendRoundTripPP (572 ms)
[ RUN      ] LibRadosIoPP.TruncTestPP
[       OK ] LibRadosIoPP.TruncTestPP (454 ms)
[ RUN      ] LibRadosIoPP.RemoveTestPP
[       OK ] LibRadosIoPP.RemoveTestPP (332 ms)
[ RUN      ] LibRadosIoPP.XattrsRoundTripPP
[       OK ] LibRadosIoPP.XattrsRoundTripPP (525 ms)
[ RUN      ] LibRadosIoPP.RmXattrPP
[       OK ] LibRadosIoPP.RmXattrPP (999 ms)
[ RUN      ] LibRadosIoPP.XattrListPP
[       OK ] LibRadosIoPP.XattrListPP (560 ms)
[----------] 14 tests from LibRadosIoPP (13380 ms total)

[----------] 10 tests from LibRadosIoEC
[ RUN      ] LibRadosIoEC.SimpleWrite
[       OK ] LibRadosIoEC.SimpleWrite (8067 ms)
[ RUN      ] LibRadosIoEC.RoundTrip
[       OK ] LibRadosIoEC.RoundTrip (560 ms)
[ RUN      ] LibRadosIoEC.OverlappingWriteRoundTrip
[       OK ] LibRadosIoEC.OverlappingWriteRoundTrip (655 ms)
[ RUN      ] LibRadosIoEC.WriteFullRoundTrip
[       OK ] LibRadosIoEC.WriteFullRoundTrip (1145 ms)
[ RUN      ] LibRadosIoEC.AppendRoundTrip
[       OK ] LibRadosIoEC.AppendRoundTrip (673 ms)
[ RUN      ] LibRadosIoEC.TruncTest
[       OK ] LibRadosIoEC.TruncTest (587 ms)
[ RUN      ] LibRadosIoEC.RemoveTest
[       OK ] LibRadosIoEC.RemoveTest (980 ms)
[ RUN      ] LibRadosIoEC.XattrsRoundTrip
[       OK ] LibRadosIoEC.XattrsRoundTrip (629 ms)
[ RUN      ] LibRadosIoEC.RmXattr
[       OK ] LibRadosIoEC.RmXattr (1606 ms)
[ RUN      ] LibRadosIoEC.XattrIter
[       OK ] LibRadosIoEC.XattrIter (926 ms)
[----------] 10 tests from LibRadosIoEC (15829 ms total)

[----------] 14 tests from LibRadosIoECPP
[ RUN      ] LibRadosIoECPP.SimpleWritePP
[       OK ] LibRadosIoECPP.SimpleWritePP (6774 ms)
[ RUN      ] LibRadosIoECPP.ReadOpPP
[       OK ] LibRadosIoECPP.ReadOpPP (778 ms)
[ RUN      ] LibRadosIoECPP.SparseReadOpPP
[       OK ] LibRadosIoECPP.SparseReadOpPP (535 ms)
[ RUN      ] LibRadosIoECPP.RoundTripPP
[       OK ] LibRadosIoECPP.RoundTripPP (572 ms)
[ RUN      ] LibRadosIoECPP.RoundTripPP2
[       OK ] LibRadosIoECPP.RoundTripPP2 (724 ms)
[ RUN      ] LibRadosIoECPP.OverlappingWriteRoundTripPP
[       OK ] LibRadosIoECPP.OverlappingWriteRoundTripPP (527 ms)
[ RUN      ] LibRadosIoECPP.WriteFullRoundTripPP
[       OK ] LibRadosIoECPP.WriteFullRoundTripPP (977 ms)
[ RUN      ] LibRadosIoECPP.WriteFullRoundTripPP2
[       OK ] LibRadosIoECPP.WriteFullRoundTripPP2 (641 ms)
[ RUN      ] LibRadosIoECPP.AppendRoundTripPP
[       OK ] LibRadosIoECPP.AppendRoundTripPP (603 ms)
[ RUN      ] LibRadosIoECPP.TruncTestPP
[       OK ] LibRadosIoECPP.TruncTestPP (568 ms)
[ RUN      ] LibRadosIoECPP.RemoveTestPP
[       OK ] LibRadosIoECPP.RemoveTestPP (771 ms)
[ RUN      ] LibRadosIoECPP.XattrsRoundTripPP
[       OK ] LibRadosIoECPP.XattrsRoundTripPP (454 ms)
[ RUN      ] LibRadosIoECPP.RmXattrPP
[       OK ] LibRadosIoECPP.RmXattrPP (2255 ms)
[ RUN      ] LibRadosIoECPP.XattrListPP
[       OK ] LibRadosIoECPP.XattrListPP (715 ms)
[----------] 14 tests from LibRadosIoECPP (16894 ms total)

[----------] Global test environment tear-down
[==========] 50 tests from 4 test cases ran. (84472 ms total)
[  PASSED  ] 50 tests.


So I am a little bit confused:(.
By the way, if this fix will definitely fail the UT, how may it be possible to silent the bot and keep getting successful results?

**Comment by xiexingguo** [comment]
@liewegas Would you please add this PR for testing again since I have verified it locally? I feel like asking because your guys are really working hard on this project and for me it would be a pain to have to rebase it again:))

**Comment by xiexingguo** [comment]
@liewegas Ping~

**Comment by tchaikov** [comment]
weird enough, ceph_test_rados_api_io also passes with the changes in this pr.

**Comment by xiexingguo** [comment]
@tchaikov Thank you:-)

**Comment by tchaikov** [comment]
@xiexingguo did you fix/change anything in you latest commits?

**Comment by xiexingguo** [comment]
@tchaikov Well, I did simplify the assert logic a little bit. For example:
before:
int r = rados_ioctx_pool_requires_alignment2(ioctx, &requires);
 ASSERT_EQ(0, r);
after:
ASSERT_EQ(0, rados_ioctx_pool_requires_alignment2(ioctx, &requires));

The interim variable "r" is deprecated to achieve a more uniform style.

**Comment by xiexingguo** [comment]
@tchaikov  I am sorry for not letting your guys know about this, my fault.

**Comment by tchaikov** [comment]
cherry-picked into #7197. closing.

**Pull request closed without merging**
