### PR TITLE
qa/tasks/workunit.py: use "overrides" as the default settings of workunit

### PR DESCRIPTION
**Pull request by tchaikov**
otherwise the settings in "workunit" tasks are always overridden by the
settings in template config. so we'd better follow the way of how
"install" task updates itself with the "overrides" settings: it uses the
"overrides" as the *defaults*.

Fixes: http://tracker.ceph.com/issues/19429
Signed-off-by: Kefu Chai <kchai@redhat.com>

### CODE REVIEW

**Comment by tchaikov** [comment]
tested at http://pulpito.ceph.com/kchai-2017-04-01_16:57:29-rados-master---basic-mira/ using 
```
teuthology-suite --filter="rados/upgrade/jewel-x-singleton/{0-cluster/{openstack.yaml start.yaml} 1-jewel-install/jewel.yaml 2-partial-upgrade/firsthalf.yaml 3-thrash/default.yaml 4-workload/{rbd-cls.yaml rbd-import-export.yaml readwrite.yaml snaps-few-objects.yaml} 5-workload/{radosbench.yaml rbd_api.yaml} 6-finish-upgrade.yaml 7-luminous.yaml 8-workload/{rbd-python.yaml rgw-swift.yaml snaps-many-objects.yaml}}" \
 --suite rados --machine-type=mira \
 --ceph master --ceph-repo https://github.com/ceph/ceph.git \
 --suite-repo https://github.com/tchaikov/ceph.git --suite-branch wip-19429
```

```
$ egrep '(clone|Cloning)\ ' /a//kchai-2017-04-01_16:57:29-rados-master---basic-mira/976811/teuthology.log
2017-04-01T17:12:01.342 INFO:teuthology.orchestra.run.mira084:Running: 'rm -rf /home/ubuntu/cephtest/clone.client.0 && git clone --depth 1 --branch jewel https://github.com/tchaikov/ceph.git /home/ubuntu/cephtest/clone.client.0 && cd /home/ubuntu/cephtest/clone.client.0'
2017-04-01T17:12:01.455 INFO:tasks.workunit.client.0.mira084.stderr:Cloning into '/home/ubuntu/cephtest/clone.client.0'...
2017-04-01T17:12:20.416 INFO:teuthology.orchestra.run.mira084:Running: 'rm -rf /home/ubuntu/cephtest/clone.client.0 && git clone --depth 1 --branch jewel https://github.com/tchaikov/ceph.git /home/ubuntu/cephtest/clone.client.0 && cd /home/ubuntu/cephtest/clone.client.0'
2017-04-01T17:12:20.494 INFO:tasks.workunit.client.0.mira084.stderr:Cloning into '/home/ubuntu/cephtest/clone.client.0'...
```

**Comment by tchaikov** [comment]
@yuriw this is the fix for one of the known test failures.

**Comment by tchaikov** [comment]
@dmick @jdurgin could you take a look at your convenience?

**Comment by dillaman** [comment]
Related to issue https://github.com/ceph/teuthology/pull/1055

**Pull request merged**
