### PR TITLE
Wip 12262

### PR DESCRIPTION
**Pull request by dzafman**
Add feature 12262, fix unit test and bug fixes.

### CODE REVIEW

**Comment by dzafman** [comment]
@ldachary On my virtual build machine running test/cephtool-test-rados.sh takes only 30 seconds.  Ports 7203 and 7204 seemed to conflict with something, so I'm using 7199.  I didn't investigate those ports any further.

**Comment by dachary** [comment]
@dzafman looks fine to me :-)

**Comment by dzafman** [comment]
@jcsp I could take the last commit that adds the test to make check out if we want to get the other changes in.  That is probably what caused the loci-bot failure.

**Comment by dzafman** [comment]
Solved the mystery of ceph port use and checking for "attr" command removed.  Just waiting for Jenkins run to pass.

**Comment by dzafman** [comment]
@jcsp Ready for review and merge.

**Comment by jcsp** [comment]
Looks good, only minor comments on https://github.com/ceph/ceph/commit/9cfa88d09bed3ca5d0b4edd494d493d889df9176 , https://github.com/ceph/ceph/commit/0ca98fbc1f9c7623538de472ee86fedf8aeeed97

(I stupidly posted them on the commits instead of here on the PR)

**Comment by dzafman** [comment]
@jcsp Changes made.  You can see the 2 pre-squashed commits here: https://github.com/dzafman/ceph/commits/wip-12262

**Comment by jcsp** [comment]
:+1:

**Pull request merged**
