### PR TITLE
ceph-disk: Utility function to extract GPT GUIDs

### PR DESCRIPTION
**Pull request by chaitanyahuilgol**
Added utility function to raw read, parse, verify and extract
GPT partition guids. Useful in cases were blkid and sgdisk do
not work correctly on specific os device-type combinations (dm-multipath)
Added unit test verification code for the same.

Signed-off-by: Chaitanya Huilgol <chaitanya.huilgol@sandisk.com>

### CODE REVIEW

**Comment by dachary** [comment]
Cool :-) We need tests in qa/workunits/ceph-disk to verify it works GTP partitions created by sgdisk.

**Comment by chaitanyahuilgol** [comment]
@dachary This would need a ceph-disk option to invoke the function from outside. Planning to add a gpt-show option to ceph-disk.. let me know if you have any other ideas to do this.

**Comment by dachary** [comment]
It should be used to replace get_sgdisk_partition_info, don't you think ?

**Comment by chaitanyahuilgol** [comment]
@dachary The rawread function depends on the hw_sector_sz being available. The  #6035 pull request provides all the necessary functionality for getting to the '/sys/block/<base-dev>/queue/hw_sector_sz' from the partition device. 
However, here for multipath we get the /dev/mapper/<mpath-name-dev> and we will have to somehow map this back to the /sys/block/<base-dev>
Currently we can hardcode this to 512 bytes, but this will break on device with non 512 sector sizes. 

Also, the rawread implementation does not look at the backup part table if the primary is corrupted, do you think this is needed? what would be the right thing to do if one of the ceph osd drives has a corrupt primary GPT part table?

**Comment by dachary** [comment]
> Currently we can hardcode this to 512 bytes, but this will break on device with non 512 sector sizes. 

It looks like non 512 bytes sector sizes won't work right now anyway. Having get_hw_sector_size return 512 as a fall back when there is no easy way to get it from /sys seems good. And it's easy to improve afterwards. You can include this function in this pull request ?

> the rawread implementation does not look at the backup part table if the primary is corrupted

If a disk is presented to ceph-disk with no partition table, it means it is damaged and the sysadmin did not notice. Can you think of a scenario where that could lead to data loss ?

**Comment by dachary** [comment]
@chaitanyahuilgol could you please rebase ? The deactivate / destroy functions were added to ceph-disk recently.

**Comment by dachary** [comment]
@chaitanyahuilgol please let me know if you are willing to followup on this pull request and I'll reopen it.

**Pull request closed without merging**
