### PR TITLE
nautilus: mgr/dashboard: NFS export creation: Add more info to the validation message of the field Pseudo

### PR DESCRIPTION
**Pull request by tspmelo**
http://tracker.ceph.com/issues/39975

### CODE REVIEW

**Comment by smithfarm** [comment]
retest this please

**Comment by tspmelo** [comment]
jenkins test make check

**Comment by tspmelo** [comment]
jenkins retest this please

**Comment by yuriw** [comment]
[wip-yuri4-testing-2019-06-07-1600-nautilus](https://trello.com/c/fYD3krdU/633-wip-yuri4-testing-2019-06-07-1600-nautilus)

**Pull request merged**
