### PR TITLE
squid: mgr/dashboard: add RGW lifecycle management

### PR DESCRIPTION
**Pull request by Pegonzal**
backport tracker: https://tracker.ceph.com/issues/66785

---

backport of https://github.com/ceph/ceph/pull/57238
parent tracker: https://tracker.ceph.com/issues/50327

this backport was staged using ceph-backport.sh version 16.0.0.6848
find the latest version at https://github.com/ceph/ceph/blob/main/src/script/ceph-backport.sh

### CODE REVIEW

**Comment by Pegonzal** [comment]
jenkins test make check

**Comment by Pegonzal** [comment]
jenkins test dashboard

**Comment by Pegonzal** [comment]
jenkins test make check

**Comment by Pegonzal** [comment]
jenkins test dashboard cephadm

**Comment by cloudbehl** [comment]
jenkins test make check

**Comment by cloudbehl** [comment]
jenkins test cephadm e2e tests

**Review by avanthakkar — APPROVED** [review]

**Pull request merged**
