### PR TITLE
rbd-nbd: return quiesce hook exit code

### PR DESCRIPTION
**Pull request by trociny**
## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by trociny** [comment]
It depends on  #37012.

**Comment by dillaman** [comment]
jenkins test api

**Review by dillaman — APPROVED** [review]
lgtm

**Comment by trociny** [comment]
Rebased after #36825 is merged.

**Comment by trociny** [comment]
@dillaman I added a commit that initialize quiesce state variable. I believe it fixes the test failures you reported in #37086.

**Pull request merged**
