### PR TITLE
Remove upstart files and references

### PR DESCRIPTION
**Pull request by badone**
Signed-off-by: Brad Hubbard <bhubbard@redhat.com>

- [ ] References tracker ticket
- [x] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by tchaikov** [comment]
could you prefix the title of your commit message with the subcomponent your are changing ? see https://github.com/ceph/ceph/blob/master/SubmittingPatches.rst#3-describe-your-changes

**Comment by tchaikov** [comment]
- http://pulpito.ceph.com/kchai-2018-08-17_15:09:18-rados-wip-kefu-testing-2018-08-17-2127-distro-basic-smithi/
- http://pulpito.ceph.com/kchai-2018-08-18_16:46:03-rados-wip-kefu-testing-2018-08-18-2315-distro-basic-mira/
- http://pulpito.ceph.com/kchai-2018-08-19_13:56:54-rados-wip-kefu-testing-2018-08-19-1812-distro-basic-mira/

the failure is tracked by http://tracker.ceph.com/issues/24485

**Comment by tchaikov** [comment]
would be ideal if we can have more details on why we want to ditch upstart support in the commit message. for example, all the supported distros of nautilus have switched to systemd,

**Comment by tchaikov** [comment]
@badone looks great. could you also update `PendingReleaseNotes` accordingly?

**Comment by badone** [comment]
OK

**Comment by tchaikov** [comment]
@liewegas @javacruft 

i confirmed that in xenial upstart is deprecated. but it co-exists with systemd in xenial. which means, if our user is still using upstart in xenial and they want to upgrade to nautilus. they might want to fix the init script by themselves. am i right? or upstart comes with wrapper scripts around systemd units? or, put in other words, will we drop the support of xenial in nautilus?

**Comment by tchaikov** [comment]
quote from James

> I think its fine to drop upstart; systemd was the default for xenial; its highly unlikely anyone is running with upstart on xenial

**Pull request merged**
