### PR TITLE
codeowners: remove api team

### PR DESCRIPTION
**Pull request by epuertat**
Signed-off-by: Ernesto Puerta <epuertat@redhat.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/master/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [x] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by epuertat** [comment]
jenkins test api

**Comment by nSedrickm** [comment]
Hi @epuertat. Yay! learned something new today (codeowners). I wish to know why this change was made. Has the api team been dissolved. I see the dashboard team will fill in too

**Comment by nSedrickm** [comment]
jenkings test dashboard cephadm

**Comment by nSedrickm** [comment]
jenkins test dashboard cephadm

**Comment by epuertat** [comment]
> Hi @epuertat. Yay! learned something new today (codeowners). I wish to know why this change was made. Has the api team been dissolved. I see the dashboard team will fill in too

@nSedrickm I recently deleted the api team, because we were no longer using it.

**Comment by epuertat** [comment]
@Sarthak0702 I fixed the validation error with the @ceph/rook team by adding them to the [ceph repo](https://github.com/orgs/ceph/teams/rook/repositories). Now they should start receiving review requests on the [files owned by them](https://github.com/ceph/ceph/pull/46452/files#diff-3d36a1bf06148bc6ba1ce2ed3d19de32ea708d955fed212c0d27c536f0bd4da7R29-R31).

**Review by Sarthak0702 — APPROVED** [review]
LGTM!

**Review by nizamial09 — APPROVED** [review]

**Review by nSedrickm — APPROVED** [review]

**Pull request merged**
