### PR TITLE
pacific: revert backport of #45529

### PR DESCRIPTION
**Pull request by rzarzynski**
Technically this isn't a backport but a full revert of an already merged backport.

"Backport" ticket for the sake of tracking: https://tracker.ceph.com/issues/55989

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/master/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by xiexingguo** [comment]
@rzarzynski I don't quite understand. Does the original fix do anything wrong?

**Comment by rzarzynski** [comment]
@xiexingguo: yes, there are two problems:

1. the on-online trimming doesn't chunk dups removal in some cases,
2. the off-line trimming touches regular entries of of pg log but doesn't modify `pg_info_t` accordingly (this came over the weekend).

A new incarnation of the off-line trimming is https://github.com/ceph/ceph/pull/46631.

**Comment by xiexingguo** [comment]
@rzarzynski Thanks!



> 1. the on-online trimming doesn't chunk dups removal in some cases,

So https://tracker.ceph.com/issues/53729 remains. What's our new plan for it?

**Comment by rzarzynski** [comment]
@xiexingguo: implement a proper chunking for `dups` in `PGLog::IndexedLog::trim()`.

**Comment by wvh-github** [comment]
Is it possible to keep the code in the ceph-objectstore-tool. Part of the problem here is that fact that OSD are using too much memory when the dups aren't being trimmed. We are reverting this to make sure the OSD is not going to use too much memory during the upgrade.

I think there should at least b an offline way of trimming the dups. Then more time can be spent on making the trimming inside the OSD work well.

**Comment by pponnuvel** [comment]
@rzarzynski Are the Octopus commits (PR https://github.com/ceph/ceph/pull/46253 - already merged & likely to make it to 15.2.17) going to be reverted as well?

**Comment by wvh-github** [comment]
Sorry, i meant this one [46611](https://github.com/ceph/ceph/pull/46611)

**Comment by pponnuvel** [comment]
@wvh-github Ah, right. Thanks - that does answer.

Hopefully it makes to 15.2.17 too!

**Comment by k0ste** [comment]
@rzarzynski, still this should be reverted or not after #46631 merge?

**Comment by rzarzynski** [comment]
@k0ste: we don't need this PR as https://github.com/ceph/ceph/pull/46631 already merged these two revert commits (and added the new op to COT). Closing.

**Pull request closed without merging**
