### PR TITLE
osd: fix the comment of RecoveryState hierarchical structure

### PR DESCRIPTION
**Pull request by fengyueqiao**
osd: fix the comment of RecoveryState hierarchical structure

The Start state should be the inner state of Started.

Signed-off-by: QinWei <qw.mail@foxmail.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by ronen-fr** [comment]
Maybe also note in the comment that this fixes the hierarchy for Stray, ToDelete and siblings

**Comment by athanatos** [comment]
osd: fix the comment of RecoveryState hierarchical structure

The Start state should be the inner state of Started.

Signed-off-by: QinWei [qw.mail@foxmail.com](mailto:qw.mail@foxmail.com)

is the title of the PR.  That needs to also be the commit message.

**Comment by fengyueqiao** [comment]
I cannot find method to modify the commit message. 
Shoud I need be create new PR?

**Comment by fengyueqiao** [comment]
@ [ronen-fr](https://github.com/ronen-fr) 
All other inner states of Started are still the inner state of Started.
Beacuse the Started level is changed from second level to first level, these inner state levels are updage also.
I will modify comment  message according to the above description.

**Comment by Matan-B** [comment]
> I cannot find method to modify the commit message. Shoud I need be create new PR?

git commit --amend

**Pull request closed without merging**
