### PR TITLE
nautilus: rgw: Added caching for S3 credentials retrieved from keystone

### PR DESCRIPTION
**Pull request by smithfarm**
backport tracker: https://tracker.ceph.com/issues/50430

---

backport of https://github.com/ceph/ceph/pull/26095
parent tracker: https://tracker.ceph.com/issues/50428

this backport was staged using ceph-backport.sh version 16.0.0.6848
find the latest version at https://github.com/ceph/ceph/blob/master/src/script/ceph-backport.sh

### CODE REVIEW

**Comment by mattbenjamin** [comment]
@ofriedma did a downstream backport of this

**Comment by smithfarm** [comment]
@mattbenjamin Actually, I don't think this backport is needed. The master PR's merge commit is

    affb7d396f76273e885cfdbcd363c1882496726c
    Merge pull request #26095 from bbc/s3secretcache

And if I do `git describe` on it, I see:

```
$ gd affb7d396f76273e885cfdbcd363c1882496726c
v14.1.1-266-gaffb7d396f7
```

Doesn't that mean the master PR went in before nautilus was declared stable?

**Comment by smithfarm** [comment]
Or maybe @ofriedma intended to backport some follow-on fix(es), not the original master PR itself?

**Comment by ofriedma** [comment]
@smithfarm this commit nor the cherry pick commit exist in the nautilus branch, I think we need to backport it

**Review by ofriedma — APPROVED** [review]
lgtm

**Comment by smithfarm** [comment]
> @smithfarm this commit nor the cherry pick commit exist in the nautilus branch, I think we need to backport it

I guess you're right: 

```
$ git branch --contains f8a82240d0b177451bf958be0a671def098932a6 | grep nautilus
$
```

**Pull request merged**
