### PR TITLE
client: getattr before returning quota/layout xattrs

### PR DESCRIPTION
**Pull request by jcsp**
http://tracker.ceph.com/issues/17939

### CODE REVIEW

**Comment by jcsp** [comment]
@gregsfortytwo the actual quota enforcement doesn't seem to be broken, or at least it's no more sloppy on remote adjustments than it is normally (the bug report was about the df output rather than what happened when they tried to write things).

I've added a test case here that demonstrates reduced quotas preventing writes when they're remotely adjusted.

**Comment by gregsfortytwo** [comment]
I think I must be misunderstanding the way enforcing quotas and the virtual xattr are related to each other client-side then. I certainly thought Dan was saying they were having Manila issues with resizing volumes up, but maybe he just meant the output. Maybe run it by him?
Anyway, I'll take off my review and let somebody else check over it. :)

**Comment by jcsp** [comment]
One test failure on this, where the volume client tests try to do some IO after a client is evicted -- mount.py does an is_mounted(), which does a statfs before trying to do any IO, and that statfs is hanging because the client is evicted and can't do its getattr.

I've updated the code to skip doing the getattr in statfs if there are stale sessions - it passes now.

**Comment by jcsp** [comment]
retest this please

**Comment by jcsp** [comment]
@ukernel could you review this please?

**Pull request merged**
