### PR TITLE
Squid: mgr/dashboard: remove orch required decorator from host UI router (list)

### PR DESCRIPTION
**Pull request by nmunet**
backport tracker: https://tracker.ceph.com/issues/68128

backport of: https://github.com/ceph/ceph/pull/59823

parent tracker: https://tracker.ceph.com/issues/68101

Signed-off-by: Naman Munet <nmunet@redhat.com>
(cherry picked from commit 21454d08484cefefef7803c250d4d0511ae4415b)

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [x] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Comment by nmunet** [comment]
jenkins test make check

**Comment by nmunet** [comment]
jenkins test dashboard

**Comment by nmunet** [comment]
jenkins test dashboard cephadm

**Comment by nizamial09** [comment]
jenkins test dashboard

**Comment by nizamial09** [comment]
jenkins test dashboard cephadm

**Comment by nmunet** [comment]
jenkins test dashboard cephadm

**Comment by nmunet** [comment]
jenkins test dashboard

**Comment by Pegonzal** [comment]
Previous test failures: https://jenkins.ceph.com/job/ceph-dashboard-cephadm-e2e/12492/consoleFull#2998473994b0cfa0c-a892-49e0-a359-82544e1a192e

Main image being used for squid testing:
```
Sep 19 05:54:42 ceph-node-00 cloud-init[840]: Internal network (--cluster-network) has not been provided, OSD replication will default to the public_network
Sep 19 05:54:42 ceph-node-00 cloud-init[840]: Pulling container image quay.ceph.io/ceph-ci/ceph:main...
Sep 19 05:55:50 ceph-node-00 cloud-init[840]: Ceph version: ceph version 19.3.0-5022-gc37a00af (c37a00af2113d089d40b9d6df347fcb940efa41a) squid (dev)
```

So main only code failing the build:
```
Sep 19 05:57:19 ceph-node-00 cloud-init[840]: /usr/bin/ceph: stderr Error ENOENT: module 'cephadm' reports that it cannot run on the active manager daemon: 'mgmt-gateway' (pass --force to force enablement
```

**Review by nizamial09 — APPROVED** [review]

**Pull request merged**
