### PR TITLE
squid: qa/standalone/scrub: fix the searched-for text for snaps decode errors

### PR DESCRIPTION
**Pull request by ronen-fr**
to match the updated error log, as modified by commit ebd8283

Backport of https://github.com/ceph/ceph/pull/58931

Original tracker: https://tracker.ceph.com/issues/67228
Backport tracker: https://tracker.ceph.com/issues/67296

### CODE REVIEW

**Comment by ronen-fr** [comment]
I have verified (local testing, as this is a 'standalone test') that the backported PR solves the failure in TEST_corrupt_scrub_replicated

**Review by athanatos — APPROVED** [review]

**Comment by ronen-fr** [comment]
jenkins test api

**Comment by ronen-fr** [comment]
jenkins test make check

**Comment by ronen-fr** [comment]
jenkins test api

**Pull request merged**
