### PR TITLE
nautilus: common: FIPS: audit and switch some memset & bzero users

### PR DESCRIPTION
**Pull request by rzarzynski**
This is the backport of https://github.com/ceph/ceph/pull/31692. It has been slightly reworked because of NSS nautilus still uses and conflicts in the audit part.

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by smithfarm** [comment]
jenkins test make check

**Comment by rzarzynski** [comment]
@mattbenjamin, @mdw-at-linuxbox: does the this look fine? It would be great to merge this PR before the xmas-induced shutdown.

**Comment by yuriw** [comment]
[wip-yuri8-testing-2020-01-10-1559-nautilus](https://trello.com/c/MgY1KqS7/800-wip-yuri8-testing-2020-01-10-1559-nautilus)

**Comment by tchaikov** [comment]
jenkins test make check

**Pull request merged**
