### PR TITLE
pacific: mgr/cephadm: fix 'mgr/cephadm: spec.virtual_ip  param should be used by the ingress daemon

### PR DESCRIPTION
**Pull request by sebastian-philipp**
Backport of #44374 and https://github.com/ceph/ceph/pull/45014

### CODE REVIEW

**Comment by sebastian-philipp** [comment]
```
    @patch("cephadm.serve.CephadmServe._run_cephadm")
    def test_ingress_config(self, _run_cephadm, cephadm_module: CephadmOrchestrator):
>       _run_cephadm.side_effect = async_side_effect(('{}', '', 0))
E       NameError: name 'async_side_effect' is not defined
```

**Comment by sebastian-philipp** [comment]
changelog: fixed conflict in test_services.py

**Comment by sebastian-philipp** [comment]
https://pulpito.ceph.com/swagner-2022-01-18_15:34:53-rados:cephadm-wip-swagner2-testing-2022-01-18-1242-pacific-distro-default-smithi/

* nvme. fixed by Guillaume
* dashboard e2e

**Comment by sebastian-philipp** [comment]
changelog: fixed conflict in test_services.py

**Comment by adk3798** [comment]
http://pulpito.front.sepia.ceph.com/adking-2022-02-15_22:33:11-orch:cephadm-wip-adk2-testing-2022-02-15-1304-pacific-distro-basic-smithi/

Failures Tracked by:
https://tracker.ceph.com/issues/54304
https://tracker.ceph.com/issues/53939
https://tracker.ceph.com/issues/54273

**Review by adk3798 — APPROVED** [review]

**Pull request merged**
