### PR TITLE
luminous: mds: trim log during shutdown to clean metadata

### PR DESCRIPTION
**Pull request by pdvian**
http://tracker.ceph.com/issues/23950

### CODE REVIEW

**Comment by ukernel** [comment]
need rebase

**Comment by pdvian** [comment]
@ukernel Let me rebase and push changes again.

**Comment by pdvian** [comment]
@ukernel pls review.

**Comment by ukernel** [comment]
http://pulpito.ceph.com/?branch=wip-luminous-integration-20180530

**Pull request merged**
