### PR TITLE
crimson: s/crimson::do_until/crimson::repeat/

### PR DESCRIPTION
**Pull request by tchaikov**
## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Review by ronen-fr — APPROVED** [review]
LGTM (although I don't think adding a do_until() construct that
handles simple booleans is a bad idea. The resulting code is much shorter)

**Comment by tchaikov** [comment]
> LGTM (although I don't think adding a do_until() construct that
> handles simple booleans is a bad idea. The resulting code is much shorter)

without the name of variable, the value of it is not self-explained. one cannot tell what `return true` is for. that's the pain.

**Comment by ronen-fr** [comment]
> > LGTM (although I don't think adding a do_until() construct that
> > handles simple booleans is a bad idea. The resulting code is much shorter)
> 
> without the name of variable, the value of it is not self-explained. one cannot tell what `return true` is for. that's the pain.

That's true enough. I wasn't sure what's better, or if we want to support both.

**Comment by tchaikov** [comment]
i'd vote for "no". for the reason explained above.

**Review by rzarzynski — APPROVED** [review]

**Pull request merged**
