### PR TITLE
luminous: parent blocks are still seen after a whole-object discard

### PR DESCRIPTION
**Pull request by pdvian**
http://tracker.ceph.com/issues/23304

### CODE REVIEW

**Comment by pdvian** [comment]
@idryomov I had to pull commit-id ed147192 in this PR to add mock version of create. I was getting build failure for test/librbd/io/test_mock_ObjectRequest.cc (getting compile error as class librados::MockTestMemIoCtxImpl has no member named gmock_create).

**Comment by pdvian** [comment]
@idryomov @smithfarm need review

**Comment by smithfarm** [comment]
jenkins test docs

**Comment by yuriw** [comment]
[wip-yuri4-testing-2018-03-22-2133-luminous](https://trello.com/c/I55gvdPh/280-wip-yuri4-testing-2018-03-22-2133-luminous)

**Pull request merged**
