### PR TITLE
mon: disable health warning on misplaced objects by default

### PR DESCRIPTION
**Pull request by liewegas**
Misplaced is a pretty normal thing and shouldn't keep an operator on edge.  Don't raise health warn by default.  Add a config option to reenable the warning for legacy behavior if they operator wants it.

- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by liewegas** [comment]
@dvanders I think this also addresses part of your "It's Friday night" problem

**Comment by dvanders** [comment]
:+1:

**Comment by jecluis** [comment]
@liewegas can we squash those two commits?

**Comment by liewegas** [comment]
@jecluis I kept them separate in case we want to backport the option to an older release

**Pull request merged**
