### PR TITLE
ceph: add the right bracket to watch-channel argument in the help message

### PR DESCRIPTION
**Pull request by Liuchang0812**
@tchaikov 

Signed-off-by: Chang Liu <liuchang0812@gmail.com>

### CODE REVIEW

**Comment by tchaikov** [comment]
could you prefix the title of your commit message with the subcomponent your are changing ? see https://github.com/ceph/ceph/blob/master/SubmittingPatches.rst#3-describe-your-changes, in this case, it would be `ceph:`.

**Comment by Liuchang0812** [comment]
@tchaikov Thank you, commit message has been updated.

**Comment by tchaikov** [comment]
http://pulpito.ceph.com/kchai-2018-01-04_11:59:52-rados-wip-kefu-testing-2018-01-04-1836-distro-basic-smithi/

failures tracked by http://tracker.ceph.com/issues/22527 and http://tracker.ceph.com/issues/22596

**Comment by tchaikov** [comment]
http://pulpito.ceph.com/kchai-2018-01-04_11:59:52-rados-wip-kefu-testing-2018-01-04-1836-distro-basic-smithi/

failures tracked by http://tracker.ceph.com/issues/22527 and http://tracker.ceph.com/issues/22596

**Pull request merged**
