### PR TITLE
jewel: rgw: fix test_rgw_ldap.cc for search filter

### PR DESCRIPTION
**Pull request by Vicente-Cheng**
http://tracker.ceph.com/issues/18881

### CODE REVIEW

**Comment by Vicente-Cheng** [comment]
@smithfarm 
Hi Nathan, 
I run the cmake_check test by myself and meet some problems with test_rgw_ldap

I think jewel maybe miss this commit for ldap test.
is there any pr to fix it on 10.2.6?
could you help to review it?

thanks!

**Comment by smithfarm** [comment]
@Vicente-Cheng Please keep in mind that the migration to cmake was not complete when jewel was released. That is why jewel is still built using autotools. Have you tried `run-make-check.sh` ?

Why do you need cmake in jewel?

**Comment by Vicente-Cheng** [comment]
@smithfarm 
OK! thanks for your explanation, I through cmake is ready on jewel :p 
sorry, I will try run-make-check

I try cmake because I just want to backport some feature to jewel and it recommend cmake.
then meet some problems and try to solve it 

thanks!!

**Comment by smithfarm** [comment]
@Vicente-Cheng If @tchaikov agrees to backport these cmake patches to jewel, I am OK with it too.

**Comment by smithfarm** [comment]
Just keep in mind that jewel uses autotools so anything cmake-specific in the feature you want to backport should be fixed up so it works with autotools as well.

**Comment by tchaikov** [comment]
@smithfarm thanks for your reminder! i misremembered that jewel was cmake ready! but it's not =) we don't need to bother with cmake in jewel then !

**Comment by Vicente-Cheng** [comment]
close it because cmake is not ready on jewel

**Pull request closed without merging**
