### PR TITLE
nautilus: ceph-volume: don't use container classes in api/lvm.py

### PR DESCRIPTION
**Pull request by andrewschoen**
backport of #32493 and #36219

### CODE REVIEW

**Comment by rishabh-d-dave** [comment]
jenkins test ceph-volume tox

**Comment by pdvian** [comment]
jenkins test dashboard backend

**Comment by andrewschoen** [comment]
I've backported https://github.com/ceph/ceph/pull/36219 here as well.

**Comment by andrewschoen** [comment]
jenkins test ceph-volume tox

**Comment by andrewschoen** [comment]
jenkins test dashboard backend

**Comment by jan--f** [comment]
jenkins test dashboard backend

**Comment by andrewschoen** [comment]
jenkins test ceph-volume tox

**Comment by jan--f** [comment]
retest this please

**Comment by jan--f** [comment]
Something is off with the API tests. Maybe someone from the @ceph/dashboard team can chime in here?

**Comment by jan--f** [comment]
jenkins test make check

**Comment by andrewschoen** [comment]
jenkins test ceph-volume tox

**Comment by rishabh-d-dave** [comment]
jenkins test dashboard backend

**Comment by andrewschoen** [comment]
jenkins test ceph-volume tox

**Comment by andrewschoen** [comment]
@jan--f the tox tests are failing for me the same way in #35881. Are we perhaps missing a backport for nautilus?

**Comment by rishabh-d-dave** [comment]
Wrote a fix - https://github.com/ceph/ceph/pull/36493.

**Pull request merged**
