### PR TITLE
DNM: Fix the paths for bash completion files

### PR DESCRIPTION
**Pull request by branto1**
This is based on PR #4952 (contains the commit from that PR) but should fix few issues that the commit brought:

- provides backwards compatible definition of PKG_CHECK_VAR
- fixes double definition of bash_completiondir
- modifies ceph.spec.in to incorporate the changed locations of the bash completion files (from a brief googling it should work fine in OpenSUSE, too)

This probably still needs some changes to debian/ubuntu build scripts but I'm not familiar with those. Feel free to create a PR for this branch that fixes the locations for debian/ubuntu builds.

I've tested the patches with koji builds for f22 and epel7:

http://koji.fedoraproject.org/koji/taskinfo?taskID=10312375
http://koji.fedoraproject.org/koji/taskinfo?taskID=10313047

### CODE REVIEW

**Comment by branto1** [comment]
A bit of background: The default location of bash completion files has changed since they were introduced. The old /etc/bash_completion.d/ directory is no longer the preferred directory for these files. The default directory is defined in pkg-config bash-completion script and can be queried via PKG_CHECK_VAR autotools macro or pkg-config binary. These patches query the location from the pkg-config script and install the file where it should be located.

The changes shall also be backwards compatible -- if there is no such variable in the pkg-config script (or no such script), the files will be installed in the old location -- /etc/bash_completion.d/.

**Comment by branto1** [comment]
I've changed the commits to include sign-off-by lines and not package bash completion files as config files.

**Comment by branto1** [comment]
I've checked the git builders and this seems to build fine in rpm-based distros (and some deb-based) but it fails on some of the more recent debians -- it can't find the bash completion files in the old locations.

However, I'm not familiar with the debian build system and I don't know how to make the file lists more generic there. Does anyone have any suggestions?

**Comment by dachary** [comment]
@branto1 this needs rebasing. It would also help with review to show (with a pulpito link) that it passes the upgrade suite.

**Comment by branto1** [comment]
This is mostly DNM as of yet, there are still some debian/ubuntu changes missing to allow the conditional path there.

@javacruft: Could you help with those, please?

**Comment by branto1** [comment]
Sorry, I removed the branch by accident, reopening the PR.

**Pull request closed without merging**
