### PR TITLE
crimson/osd/osd_operations: add pipeline to LogMissingRequest to sync it

### PR DESCRIPTION
**Pull request by xxhdx1985126**
with ReplicateRequest

Fixes: https://tracker.ceph.com/issues/61943
Signed-off-by: Xuehan Xu <xuxuehan@qianxin.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by Matan-B** [comment]
This looks related to https://tracker.ceph.com/issues/61651
Although from https://gist.github.com/Matan-B/b28ae9fe2ce43efe58f8ce4555c28ead#step-1 I have from that we receive/handle the logmissing_request not in the correct order, I will check whether the pipeline added here will help to sync this case as well.

**Comment by xxhdx1985126** [comment]
> This looks related to https://tracker.ceph.com/issues/61651 Although from https://gist.github.com/Matan-B/b28ae9fe2ce43efe58f8ce4555c28ead#step-1 I have from that we receive/handle the logmissing_request not in the correct order, I will check whether the pipeline added here will help to sync this case as well.

I think they are related but not the same, in this pr's case, the `ReplicateRequest` and `LogMissingRequest` arrived at the replica osd in order but are processed out-of-order.

**Review by Matan-B — APPROVED** [review]
LGTM.
I would suggest referring #50018 in the commit message for better context.

**Comment by xxhdx1985126** [comment]
> LGTM. I would suggest referring #50018 in the commit message for better context.

Will do.

**Comment by xxhdx1985126** [comment]
jenkins test make check

**Review by athanatos — APPROVED** [review]

**Comment by xxhdx1985126** [comment]
> LGTM. I would suggest referring #50018 in the commit message for better context.

Done

**Comment by Matan-B** [comment]
https://pulpito.ceph.com/matan-2023-07-24_07:15:05-crimson-rados-wip-matanb-crimson-only-61943-distro-crimson-smithi/

**Pull request merged**
