### PR TITLE
luminous: osd: resend osd_pgtemp if it's not acked

### PR DESCRIPTION
**Pull request by tchaikov**
http://tracker.ceph.com/issues/23630

### CODE REVIEW

**Comment by tchaikov** [comment]
backport of #21310

**Comment by liewegas** [comment]
Can you do a --num 20 --filter ... run on the luminous backport (and master version too, actually) with this one test?

**Comment by tchaikov** [comment]
good idea! will do so.

**Comment by tchaikov** [comment]
being tested at http://pulpito.ceph.com/kchai-2018-04-10_16:28:14-rados-wip-23610-luminous-distro-basic-smithi/

**Comment by tchaikov** [comment]
the test failure was not related to this change.
```
    assert manager.get_num_active_clean() == pg_num
```
it failed in the first step of the test: "1. creating pool.a".

**Comment by tchaikov** [comment]
@smithfarm FWIW, #21310 has been merged.

**Comment by yuriw** [comment]
[wip-yuri-testing-2018-04-11-1557-luminous](https://trello.com/c/7wNnLkKd/293-wip-yuri-testing-2018-04-11-1557-luminous)

**Pull request merged**
