### PR TITLE
luminous: mgr/dashboard: add configuration setting browser

### PR DESCRIPTION
**Pull request by epuertat**
Source PR: #20043

Signed-off-by: Rubab Syed<rubab.syed21@gmail.com>
(cherry picked from commit 14bb815060a4d156bb5f7cc5d66e77466cba4351)
Signed-off-by: Ernesto Puerta <epuertat@redhat.com>

Conflicts:
      src/pybind/mgr/dashboard/base.html
      src/pybind/mgr/dashboard/monitors.html
      src/pybind/mgr/dashboard/osd_perf.html
      src/pybind/mgr/dashboard/rgw_detail.html

Conflict resolution:
- Keep config references while removing references to new monitor and
rgw endpoints and pages.

### CODE REVIEW

**Comment by epuertat** [comment]
[`teuthology-suite -m mira -c wip-epuertat-testing-2018-08-08-1052 -s rados:mgr`](http://pulpito.ceph.com/epuertat-2018-08-08_08:51:28-rados:mgr-wip-epuertat-testing-2018-08-08-1052-distro-basic-mira/)
**[15/16 passed]** - Failure: *Test failure: test_selftest_command_spam (tasks.mgr.test_module_selftest.TestModuleSelftest)* --> [unrelated/flappy](http://tracker.ceph.com/issues/24614)

**Comment by epuertat** [comment]
@jcsp thank you so much!

@smithfarm any chance to get this one scheduled for a QA run? If not required, could you please merge it (or tell if it's ok for me to merge)? Thanks!

**Comment by smithfarm** [comment]
@epuertat Please be patient. This PR is on track.

Note regarding integration testing. If this commit is a dependency for another PR and testing of that PR is "blocked" as a result, you can "unblock" it by cherry-picking this commit into that other PR. If you do that, be sure to mark the "other PR" DNM and note in a comment that it needs to be rebased after this PR merges.

**Comment by yuriw** [comment]
[wip-yuri2-testing-2018-08-13-1641-luminous](https://trello.com/c/AUtDMGDx/372-wip-yuri2-testing-2018-08-13-1641-luminous)

**Pull request merged**
