### PR TITLE
luminous: Fix recovery and backfill priority handling

### PR DESCRIPTION
**Pull request by dzafman**
Backport
https://github.com/ceph/ceph/pull/26213
https://github.com/ceph/ceph/pull/23904

Commits to make the backport simpler
https://github.com/ceph/ceph/commit/7816ab5a8eb0ea754a0809eb9da915a16ad39e83
https://github.com/ceph/ceph/commit/2482b4cc91579b4ef5748097f1adacaad91510b1

- [x] References tracker ticket
- [x] Updates documentation if necessary
- [x] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by smithfarm** [comment]
@dzafman You marked this "needs-review" and "needs-qa" . . . could you squash the last commit to get it past the Jenkins "signed-off-by" check?

**Comment by neha-ojha** [comment]
@dzafman is this ready to merge?

**Comment by dzafman** [comment]
@neha-ojha I added the luminous-batch-1 label so it would be picked up for integration testing.

**Comment by neha-ojha** [comment]
cool, the wip-zafman-testing tag gave me the impression that you were testing it yourself.

**Comment by dzafman** [comment]
@neha-ojha I forgot I did do this run: 
http://pulpito.ceph.com/dzafman-2019-03-06_14:12:36-rados-wip-zafman-testing-luminous-distro-basic-smithi/
2 dead and 3675540 infrastructure
3675503 3675523  http://tracker.ceph.com/issues/24613
3675583 qa/workunits/mgr/test_localpool.sh failed, don't understand this one

So we can merge if you like, I thought it was supposed to go through another process.

**Comment by neha-ojha** [comment]
These look unrelated, should be ok to merge.

**Pull request merged**
