### PR TITLE
pybind/mgr: Add ceph_module.pyi to improve type checking

### PR DESCRIPTION
**Pull request by sebastian-philipp**
`ceph_module.pyi` is an interface definition of classes that are generated within C++.
Used by mypy to do proper type checking of mgr modules.
Without this file, all classes have undefined base classes.

Now, we're also finding accesses to undefined class properties.

Secondly, this also improves the development experience when using IDEs.

**Note**: there is some obvious downside: mypy will complain, if the .pyi file is out of date. Which means, this file needs to be manually maintained.

(This PR was a part of #26769)

**Fixes**: Access to undefined member `log` of `CRUSHMap`

Signed-off-by: Sebastian Wagner <sebastian.wagner@suse.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by sebastian-philipp** [comment]
src/seastar/CMakeFiles/seastar.dir/build.make:1132: recipe for target 'src/seastar/CMakeFiles/seastar.dir/src/net/ethernet.cc.o' failed

**Comment by jschmid1** [comment]
I'm all up for increasing test coverage in general. If this thing turns out to be a huge maintenance burden we can still get rid of it.

**Comment by sebastian-philipp** [comment]
jenkins test make check

**Comment by sebastian-philipp** [comment]
> This is a great quality improvement, @sebastian-philipp! How hard would it be to fully type all methods and return types?

This wouldn't really have an impact, as all symbols here are already wrapped in Python. I'd focus on adding type annotations there instead.
 
> Should we document _somewhere_ that when extending or modifying ceph-mgr C++ API this file needs to be updated accordingly?

Yeah. just where should we document this? keep in mind `make check` will fail, if this file needs to be modified. Honestly, I don't expect anyone to read this documentation, until `make check` fails for them.

**Pull request merged**
