### PR TITLE
BlueStore: fix wrong encode/decode logic of kv

### PR DESCRIPTION
**Pull request by xiexingguo**
Fixes: #14381
Signed-off-by: xie xingguo <xie.xingguo@zte.com.cn>

### CODE REVIEW

**Comment by xiexingguo** [comment]
@liewegas It seems that the fix https://github.com/ceph/ceph/commit/635bda363071dad9f89436cab15fd52bf2678c09 reveals another  problem. I am not sure if it is the exact fix that you want and I don't verify it locally(cause I am at home:-) now) . But if it is, please let me know and I will try to verify it locally and fix the same problem in os/kstore/kv.cc

**Comment by liewegas** [comment]
can you describe the failure/bug?  we still want to cram theese values in big endian directly into the key to avoid the overhead of hex encode/decode and to keep the key strings short

**Comment by xiexingguo** [comment]
@liewegas  I write a little test for the problem which is tracked at http://tracker.ceph.com/issues/14381:
main()
{
    unsigned hash = 0;
    string key;
    
	_key_encode_u32(hash, &key);
    cout << "(len = " << key.length() << ")" << key << endl;	
	
	const char *p = key.c_str();
	cout << strlen(p) << endl;
	
	getchar();
}

And the result is:

[root@c8 test]# ./ceph
(len = 4)
0


So the problem here is if the value to be wrapped in this way, it will potentially cause the corresponding result string(if cast to a standard c-type char string) to be unexpectedly null terminated, which is a dangerous thing.

**Comment by xiexingguo** [comment]
I guess your original intention is the encode/decode efficiency but it seems not to be a good idea.

**Comment by xiexingguo** [comment]
I also write a UT test to verify the object name key transforming logic, as below:
```

TEST_F(TestObjectNameKey, SanityCheck) {

  // no key 
  {
	uint64_t hash = 0;
	uint64_t pool = 0xCDCDCDCD;
	int64_t gen = 0xefefefefef;
	shard_id_t shard_id(0xb);
    std::string name("ABC");
    ghobject_t hoid(hobject_t(object_t(name), "", 1, hash, pool, ""));
	hoid.hobj.nspace = "NSPACE";
	hoid.generation = gen;
	std::string key;
	get_object_key(hoid, &key);
	ghobject_t temp;
    ASSERT_EQ(0, get_key_object(key, &temp));
  } 

  const std::string key("KEY");
  
  // no hash 
  {
	uint64_t hash = 0;
	uint64_t pool = 0xCDCDCDCD;
	int64_t gen = 0xefefefefef;
	shard_id_t shard_id(0xb);
    std::string name("ABC");
    ghobject_t hoid(hobject_t(object_t(name), key, 1, hash, pool, ""));
	hoid.hobj.nspace = "NSPACE";
	hoid.generation = gen;
	std::string key;
	get_object_key(hoid, &key);
	ghobject_t temp;
    ASSERT_EQ(0, get_key_object(key, &temp));
  } 

  // no snap 
  {
	uint64_t hash = 0xABABABAB;
	uint64_t pool = 0xCDCDCDCD;
	int64_t gen = 0xefefefefef;
	shard_id_t shard_id(0xb);
    std::string name(".XA/B_\\C.D");
    ghobject_t hoid(hobject_t(object_t(name), key, CEPH_NOSNAP, hash, pool, ""));
	hoid.hobj.nspace = "NSPACE";
	hoid.generation = gen;
	std::string key;
	get_object_key(hoid, &key);
	ghobject_t temp;
    ASSERT_EQ(0, get_key_object(key, &temp));
  }  
 
   // no gen 
  {
	uint64_t hash = 0xABABABAB;
	uint64_t pool = 0xCDCDCDCD;
	int64_t gen = 0;
	shard_id_t shard_id(0xb);
    std::string name(".XA/B_\\C.D");
    ghobject_t hoid(hobject_t(object_t(name), key, 1, hash, pool, ""));
	hoid.hobj.nspace = "NSPACE";
	hoid.generation = gen;
	std::string key;
	get_object_key(hoid, &key);
	ghobject_t temp;
    ASSERT_EQ(0, get_key_object(key, &temp));
  } 
}

```

Below are the test results with/without the change of this PR:
___before:___
```
[root@c8 src]# ./unittest_object_name_key   
Running main() from gmock_main.cc
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from TestObjectNameKey
[ RUN      ] TestObjectNameKey.SanityCheck
  r -3
key '--'0x80000000cdcdcdcd00000000'.NSPACE!=ABC!'0x0000000000000001000000efefefefef
oid 3452816845/00000000:NSPACE/ABC/1/efefefef
  t GHMIN
unittest_object_name_key: test/os/TestObjectNameKey.cc:294: void get_object_key(const ghobject_t&, std::string*): Assertion `t == oid' failed.
Aborted (core dumped)
```
___after___
```
[root@c8 src]# ./unittest_object_name_key   
Running main() from gmock_main.cc
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from TestObjectNameKey
[ RUN      ] TestObjectNameKey.SanityCheck
[       OK ] TestObjectNameKey.SanityCheck (0 ms)
[----------] 1 test from TestObjectNameKey (0 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test case ran. (0 ms total)
[  PASSED  ] 1 test.
```

**Comment by liewegas** [comment]
yeah, the key can't be cast to a C string.  There is a 
pretty_binary_string() helper that's used when printing it to the debug 
log.  rocksdb has no problem with null characters in the key names.

**Comment by liewegas** [comment]
This encoding is deliberate for efficiency.  I fixed this just by dropping the null checks in  1590b082d5a57faae567ae45d9eb6f9cd0e3607a

**Pull request closed without merging**
