### PR TITLE
mon: dead code removal

### PR DESCRIPTION
**Pull request by PierreChaumont**
dead code removal from src/mon/OSDMonitor::should_propose

Fixes : #7314

Signed-off-by : Pierre Chaumont <pierre.chaumont31@gmail.com>

### CODE REVIEW

**Comment by theanalyst** [comment]
I'm not sure whether doc: should be the title in the commit message.. it is generally the component affected, though I don't think developer docs mention anything about commit title (that is also a worth a patch then)

**Comment by smithfarm** [comment]
maybe I'm missing something - what this has to do with documentation?

**Comment by dachary** [comment]
@smithfarm that's just a confusion in the flow of documentation related changes in the classroom ;-)

**Comment by PierreChaumont** [comment]
yeah i'm sorry :s @theanalyst is right : I've simply read the developer docs and the only thing mentionned was 'doc' for a commit title.

**Comment by theanalyst** [comment]
@PierreChaumont no problems. Welcome to ceph & thanks for contributing :)

**Comment by jecluis** [comment]
I'm trying to understand why this code is dead and I'm failing at it.  Can someone please (maybe @dachary) explain what's the rationale behind this?

**Comment by jecluis** [comment]
Also, as mentioned before, commit title is incorrect; also, said explanation as to why this code is dead should go in the commit message.

**Comment by dachary** [comment]
@jecluis I'm disapointed at myself for not including an explanation in the issue when I created it. I vaguely remember the context but it took me a while to come to this conclusion and ... I bitterly regret not writing it down :-(

**Comment by jecluis** [comment]
Unless it's obvious why this code is dead, I don't feel comfortable acking this patch.

**Comment by dachary** [comment]
@PierreChaumont it's not a low hanging fruit after all. Do you mind picking another contribution ? Thanks for your understanding.

**Comment by PierreChaumont** [comment]
@dachary all right, i hope i'll find an other one friday :D

**Pull request closed without merging**
