### PR TITLE
config_opts: drop unused opts

### PR DESCRIPTION
**Pull request by tchaikov**

### CODE REVIEW

**Comment by liewegas** [comment]
This doesn't seem quite right.  When did we lose the ability to create a mon with leveldb?

**Comment by tchaikov** [comment]
@liewegas since 42a6b0efe1a3269c8e6c10e89f92bc0f28923af2

**Comment by liewegas** [comment]
ok, i think that commit was a mistake then.. the intention was for the config option to affect mkfs only, but it looks like it hard-codes the mon keyvaluedb to leveldb.  :/

**Comment by tchaikov** [comment]
@liewegas okay, i will push a fix for it in this PR tomorrow.

**Comment by liewegas** [comment]
I think https://github.com/ceph/ceph/pull/15059 is the fix we want

**Comment by tchaikov** [comment]
@liewegas the other commit in this PR still apply, i guess. i dropped the commit removing `mon_keyvaluedb` option. could you take a look again?

**Comment by liewegas** [comment]
Oh, yeah!  Sorry-

**Comment by liewegas** [comment]
http://pulpito.ceph.com/sage-2017-05-16_22:22:40-rados-wip-sage-testing2---basic-smithi/

**Pull request merged**
