### PR TITLE
infernalis: librados (C++) linker error (undefined reference)

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/14916

### CODE REVIEW

**Comment by tchaikov** [comment]
@smithfarm i rethought about this. i'd suggest not bump the so version.

in theory, we should change "2:0:0" to "3:0:0", as we removed some of the interfaces from librados. and the produced shared object would be librados.so.3.0.0. but that would break the soname dependency of rpm packages depending on librados.
```
    failed dependencies:
	    librados.so.2  is needed by foobar-pacakge-2.11-1
```
among them, the most notably package is qemu. so as long as foobar-package is not linked against v9.1.0 or v9.2.0. it will continue to work when the librados v10.* is installed. and since hammer is the last LTS, most (if not all) distros are packaging hammer. so there is less chance that it will break. what do you think?

**Comment by smithfarm** [comment]
@tchaikov OK, so we leave the versioning unchanged in infernalis, but what about jewel?

**Comment by tchaikov** [comment]
@smithfarm we leave it unchanged in jewel also. @liewegas what do you think?

**Comment by smithfarm** [comment]
@tchaikov, @liewegas: The reason I'm asking is that I'd dearly love to drop the hard librados dependencies (`Requires:       librados2 = %{epoch}:%{version}-%{release}`) from the libradosstriper1 and librbd1 packages, but this requires that librados2 be "properly versioned" (whatever that means).

**Comment by tchaikov** [comment]
@smithfarm https://github.com/ceph/ceph/pull/7974#discussion_r55627622 does this convince you?

**Comment by smithfarm** [comment]
@tchaikov I'm OK to leave the major so version number unchanged in infernalis.

**Comment by tchaikov** [comment]
@smithfarm so you are suggesting bump up the release number?

**Comment by smithfarm** [comment]
@tchaikov I don't know. I want to drop the inter-shared-library runtime dependencies from the spec file (see the `Requires:       librados2 = %{epoch}:%{version}-%{release}` lines in libradosstriper1 and librbd1 packages) because they make it impossible for folks to have different versions of these shared libraries installed at the same time.

**Comment by dachary** [comment]
infernalis has been EOL for a few months now, there does not seem to be a need for another release, even for upgrade purposes

**Pull request closed without merging**
