### PR TITLE
hammer: [MON] Fixed calculation of %USED

### PR DESCRIPTION
**Pull request by dzafman**
Had to add RAW USED for ceph df detail in order make correction to %USED just drop in.

### CODE REVIEW

**Comment by dzafman** [comment]
Before
[~/ceph-hammer/src] (hammer)
$ ./ceph df
GLOBAL:
    SIZE     AVAIL      RAW USED     %RAW USED
    299G     74885M         226G         75.61
POOLS:
    NAME     ID     USED      %USED     MAX AVAIL     OBJECTS
    rbd      0          0         0        24883M           0
    test     1      1000M      0.33        24883M          10

After
[~/ceph-hammer/src] (wip-15635)
dzafman$ ./ceph df
GLOBAL:
    SIZE     AVAIL      RAW USED     %RAW USED
    299G     76451M         225G         75.10
POOLS:
    NAME     ID     USED      %USED     MAX AVAIL     OBJECTS
    rbd      0          0         0        24068M           0
    test     1      1000M      0.98        24068M          10

**Comment by dzafman** [comment]
make check doesn't pass

**Comment by dzafman** [comment]
I want to cherry-pick 2fb0530a5650bcdb9c89d8bdd2504a7dd1642678 here after it merges in master.

**Comment by smithfarm** [comment]
I will leave this out of the first integration testing round.

**Comment by dzafman** [comment]
@smithfarm Why are you leaving it out?

**Comment by smithfarm** [comment]
@dzafman Because you intend to "cherry-pick 2fb0530 here after it merges in master" . . . so presumably it would need testing again after that happens?

**Comment by dzafman** [comment]
@smithfarm This now has the additional commit and is ready to go.  Should we remove DNM?

**Comment by smithfarm** [comment]
@dzafman Done.

**Comment by dzafman** [comment]
The failures don't relate to these changes:

http://pulpito.ceph.com/dzafman-2016-07-12_16:03:42-rados:thrash-wip-zafman-testing-hammer---basic-smithi/

**Comment by dzafman** [comment]
Rados run passed with 1 unrelated failure: http://pulpito.ceph.com/dzafman-2016-07-21_13:18:50-rados-wip-zafman-testing-hammer---basic-smithi/

**Comment by smithfarm** [comment]
@liewegas: I had been having some trouble with the `hammer-backports` testing runs - see http://tracker.ceph.com/issues/15895 for details - so @dzafman took matters into his own hands ;-)

Do you think this hammer backport is good to merge?

**Comment by smithfarm** [comment]
@liewegas This PR is in the latest round of hammer-backports integration tests, which passed a rados run (the only failures are a valgrind false positive that has since been fixed by https://github.com/ceph/teuthology/pull/915 and http://tracker.ceph.com/issues/15139 which is an infrastructure issue with two of the tests) - for details, see: http://tracker.ceph.com/issues/15895#note-18

Do you think this PR is OK to merge?

**Comment by smithfarm** [comment]
@liewegas @athanatos This PR passed a /200 rados run on Ubuntu. None of the failures were reproducible. For details see http://tracker.ceph.com/issues/15895#note-18

Do you think it's OK to merge?

**Comment by athanatos** [comment]
I'm ok with it if @dzafman is.

**Comment by dzafman** [comment]
👍

**Pull request merged**
