### PR TITLE
cephfs pybind: added lseek() function to cephfs pybind

### PR DESCRIPTION
**Pull request by xweichu**
Signed-off-by: Xiaowei Chu (xweichu@hotmail.com)
added lseek() function to cephfs pybind

### CODE REVIEW

**Comment by xweichu** [comment]
May I know how can I fix the "Signed-off-by" issue? Thanks a lot.

**Comment by batrick** [comment]
Please also squash your commits to one.

**Comment by xweichu** [comment]
Thanks a lot. I've fixed the mentioned problems. Please check again. 
Here is the Ceph tracker issue link:
Fixes https://tracker.ceph.com/issues/39403

**Comment by batrick** [comment]
Almost there! Just need to remove the modifications to submodules. Best way to do that is:

````
git reset -p HEAD^
git commit --amend
````

**Comment by xweichu** [comment]
> Almost there! Just need to remove the modifications to submodules. Best way to do that is:
> 
> ```
> git reset -p HEAD^
> git commit --amend
> ```

Thanks a lot. You're very helpful. I appreciate that.

**Comment by batrick** [comment]
retest this please

**Pull request merged**
