### PR TITLE
ceph.in: disable ASAN if libasan is not found

### PR DESCRIPTION
**Pull request by tchaikov**
Signed-off-by: Kefu Chai <kchai@redhat.com>

- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by tchaikov** [comment]
retest this please.

**Comment by tchaikov** [comment]
retest this please

**Comment by tchaikov** [comment]
retest this please.

**Comment by tchaikov** [comment]
- http://pulpito.ceph.com/kchai-2019-05-27_10:18:11-rados-wip-kefu-testing-2019-05-27-1206-distro-basic-smithi/
- http://pulpito.ceph.com/kchai-2019-05-28_01:35:41-rados-wip-kefu-testing-2019-05-27-1206-distro-basic-mira/

failures tracked by

- http://tracker.ceph.com/issues/23947
- http://tracker.ceph.com/issues/39644

**Comment by cbodley** [comment]
i pulled up master after this merged, and i'm getting this error from vstart.sh:
```
Populating config ...
Traceback (most recent call last):
  File "/home/cbodley/ceph/build/bin/ceph", line 132, in <module>
    if asan_lib_path.endswith('NOTFOUND'):
AttributeError: 'NoneType' object has no attribute 'endswith'
```
this is on fedora 28 with python2

**Comment by tchaikov** [comment]
@cbodley #28275

**Pull request merged**
