### PR TITLE
mgr/dashboard: RGW User quota validation is not working correctly

### PR DESCRIPTION
**Pull request by votdev**
Fixes: https://tracker.ceph.com/issues/40829

Signed-off-by: Volker Theile <vtheile@suse.com>

- [x] References tracker ticket
- [ ] Updates documentation if necessary
- [x] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by votdev** [comment]
jenkins retest this please

**Comment by ricardoasmarques** [comment]
jenkins retest this please

**Comment by ricardoasmarques** [comment]
jenkins retest this please

**Comment by votdev** [comment]
jenkins test make check arm64

**Pull request merged**
