### PR TITLE
DNM: jewel: mon: "mon metadata" fails when only one monitor exists

### PR DESCRIPTION
**Pull request by Abhishekvrshny**
http://tracker.ceph.com/issues/16081

### CODE REVIEW

**Comment by dachary** [comment]
@jcsp does this backport look good to merge ? It passed the fs suite http://tracker.ceph.com/issues/16344#note-15

**Comment by jcsp** [comment]
Not sure about backporting the new modes of commands that dump all metadata at once, those aren't really bug fixes.  The bugfix parts look fine.

**Comment by dachary** [comment]
@Abhishekvrshny please remove the DNM once you did what jcsp suggested.

**Comment by dachary** [comment]
@Abhishekvrshny ping ?

**Comment by Abhishekvrshny** [comment]
@dachary This had been fixed by in https://github.com/ceph/ceph/pull/10654 :). Hence, closing this PR.

**Comment by dachary** [comment]
@Abhishekvrshny ooops, sorry for the redundancy & noise

**Pull request closed without merging**
