### PR TITLE
luminous: rgw: resolve bugs and clean up garbage collection code

### PR DESCRIPTION
**Pull request by chardan**
backport tracker: https://tracker.ceph.com/issues/38714

parent tracker: https://tracker.ceph.com/issues/38454

---

rgw: resolve bugs and clean up garbage collection code

Reviewed-by: Matt Benjamin <mbenjamin@redhat.com>
(cherry picked from commit commit f686b5add2)
Signed-off-by: Jesse Williamson <jesse.williamson@canonical.com>

Conflicts: rgw_gc.cc (resolve merge-commit)

~https://tracker.ceph.com/issues/41801~ I'll delete this one

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`

</details>

### CODE REVIEW

**Comment by chardan** [comment]
Jenkins retest this please.

**Comment by smithfarm** [comment]
@chardan This PR doesn't seem to contain any commits?

**Comment by smithfarm** [comment]
@chardan I fixed the backport tracker URL in the description and deleted the backport tracker you opened.

There is a script in master, `src/script/ceph-backport.sh`, which I would be thrilled if you would use to do this backport. Just put it somewhere in your PATH and run it:

```
ceph-backport.sh --help
```

It requires a small bit of setup (check out the documentation pointed to in the `--help`), but once this tiny hurdle is overcome it makes backporting a "cinch". Hope you like it.

**Comment by smithfarm** [comment]
@chardan Ah, there is a merge commit - instead of that, we would need a cherry-pick on top of luminous, done by `git cherry-pick -x $MASTER_SHA1`

**Comment by smithfarm** [comment]
@chardan The cherry-pick looks much better now, thanks! Two things remain before this can be cleared for integration testing:

1. the PR now contains a number of (unrelated) ceph-volume commits - need to get rid of those somehow
2. the PR did not pass "make check", which might indicate that it does not compile (unfortunately the logs are gone now, so I can't say for sure what the issue was)

**Comment by cbodley** [comment]
jenkins test make check

**Comment by cbodley** [comment]
this appears to pull in 6 unrelated commits to ceph-volume

**Comment by smithfarm** [comment]
> this appears to pull in 6 unrelated commits to ceph-volume

Right - see https://github.com/ceph/ceph/pull/30367#issuecomment-534162403

**Comment by smithfarm** [comment]
The build failure is a "wall of text" starting with:

```
In file included from /home/jenkins-build/build/workspace/ceph-pull-requests/src/include/Context.h:19:0,
                 from /home/jenkins-build/build/workspace/ceph-pull-requests/src/common/Cond.h:19,
                 from /home/jenkins-build/build/workspace/ceph-pull-requests/src/rgw/rgw_gc.h:11,
                 from /home/jenkins-build/build/workspace/ceph-pull-requests/src/rgw/rgw_gc.cc:4:
/home/jenkins-build/build/workspace/ceph-pull-requests/src/rgw/rgw_gc.cc: In member function ‘void RGWGCIOManager::handle_next_completion()’:
/home/jenkins-build/build/workspace/ceph-pull-requests/src/rgw/rgw_gc.cc:206:19: error: ‘dpp’ was not declared in this scope
         ldpp_dout(dpp, 0) << "WARNING: gc cleanup of tags on gc shard index=" <<
                   ^
/home/jenkins-build/build/workspace/ceph-pull-requests/src/common/dout.h:68:31: note: in definition of macro ‘ldpp_dout’
 #define ldpp_dout(dpp, v) if (dpp) dout_impl(dpp->get_cct(), dpp->get_subsys(), v) (*_dout << dpp->gen_prefix())
                               ^
/home/jenkins-build/build/workspace/ceph-pull-requests/src/common/dout.h:59:24: error: template argument 1 is invalid
           CephContext* >::value,  \
                        ^
/home/jenkins-build/build/workspace/ceph-pull-requests/src/common/dout.h:68:36: note: in expansion of macro ‘dout_impl’
 #define ldpp_dout(dpp, v) if (dpp) dout_impl(dpp->get_cct(), dpp->get_subsys(), v) (*_dout << dpp->gen_prefix())
                                    ^
/home/jenkins-build/build/workspace/ceph-pull-requests/src/rgw/rgw_gc.cc:206:9: note: in expansion of macro ‘ldpp_dout’
         ldpp_dout(dpp, 0) << "WARNING: gc cleanup of tags on gc shard index=" <<
         ^
```

**Comment by ivancich** [comment]
@chardan As @smithfarm pointed out (https://github.com/ceph/ceph/pull/30367#issuecomment-534162403), this PR has some unrelated commits in it. Can we get those removed?

**Comment by yuriw** [comment]
[wip-yuri5-testing-2019-11-04-2055-luminous](https://trello.com/c/YohtmFrD/744-wip-yuri5-testing-2019-11-04-2055-luminous)

**Comment by smithfarm** [comment]
I got word that there's a new version of this coming.

**Comment by smithfarm** [comment]
New version failed to materialize.

**Comment by smithfarm** [comment]
@cbodley This was included in passing rgw run https://trello.com/c/YohtmFrD/744-wip-yuri5-testing-2019-11-04-2055-luminous

OK to merge?

**Comment by chardan** [comment]
@smithfarm Ok w/ me...

**Comment by smithfarm** [comment]
The other backport PR got opened: https://github.com/ceph/ceph/pull/31664

**Pull request closed without merging**
