### PR TITLE
qa/ceph_manager: preserve newline char at EOF in keyring

### PR DESCRIPTION
**Pull request by rishabh-d-dave**
Lack of newline character at the end of keyring file makes CephFS mount
command end with error.

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [x] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Review by dparmar18 — APPROVED** [review]

**Comment by batrick** [comment]
> Lack of newline character at the end of keyring file makes CephFS mount
> command end with error.

This fix is good but it seems to me the mount command should not depend on superfluous whitespace in the keyring. Let's fix that?

**Comment by rishabh-d-dave** [comment]
> > Lack of newline character at the end of keyring file makes CephFS mount
> > command end with error.
> 
> This fix is good but it seems to me the mount command should not depend on superfluous whitespace in the keyring. Let's fix that?

Yes. I'm on it.

**Comment by rishabh-d-dave** [comment]
@ljflores Please include this one too in next QA run.

**Comment by ljflores** [comment]
Rados suite results: http://pulpito.front.sepia.ceph.com/?branch=wip-yuri7-testing-2023-04-19-1343

Failures, unrelated:
    1. https://tracker.ceph.com/issues/57755
    2. https://tracker.ceph.com/issues/58946
    3. https://tracker.ceph.com/issues/49888
    4. https://tracker.ceph.com/issues/59380
    5. https://tracker.ceph.com/issues/57754
    6. https://tracker.ceph.com/issues/55347
    7. https://tracker.ceph.com/issues/49287

Details:
    1. task/test_orch_cli: test_cephfs_mirror times out - Ceph - Orchestrator
    2. cephadm: KeyError: 'osdspec_affinity' - Ceph - Mgr - Dashboard
    3. rados/singleton: radosbench.py: teuthology.exceptions.MaxWhileTries: reached maximum tries (3650) after waiting for 21900 seconds - Ceph - RADOS
    4. rados/singleton-nomsgr: test failing from "Health check failed: 1 full osd(s) (OSD_FULL)" and "Health check failed: 1 filesystem is offline (MDS_ALL_DOWN)" - Ceph - RGW
    5. test_envlibrados_for_rocksdb.sh: update-alternatives: error: alternative path /usr/bin/gcc-11 doesn't exist - Ceph - RADOS
    6. SELinux Denials during cephadm/workunits/test_cephadm - Ceph - Orchestrator
    7. podman: setting cgroup config for procHooks process caused: Unit libpod-$hash.scope not found - Ceph - Orchestrator

**Comment by kotreshhr** [comment]
jenkins test windows

**Comment by kotreshhr** [comment]
jenkins test make check arm64

**Pull request merged**
