### PR TITLE
mgr/dashboard: Enforce password change upon first login

### PR DESCRIPTION
**Pull request by s0nea**
Fixes: https://tracker.ceph.com/issues/24655
Signed-off-by: Tatjana Dehler <tdehler@suse.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by votdev** [comment]
While playing around with this new feature i realized that if i entered the username and pwd of a user that needs to change his password upon first login it is not possible to login with another user until i entered the new password.

How to reproduce:
- Create a new user `test01` and check the `User must change password at next logon` box.
- Logout admin
- Login `test01`
The form to change the password for `test01` is displayed. Now it is not possible anymore to login as `admin`or any other user. A page reload still shows me the form to update the password for `test01`.
Because of security reason the change pwd page should not be displayed after a page reload, instead the regular login page MUST be shown.

**Comment by votdev** [comment]
IMO the current approach to implement this feature looks too difficult, many code is duplicated and the code path looks weird. Isn't it possible to implement that by using a route guard that will check whether it is possible to redirect the user to the change passform form?

**Comment by Exotelis** [comment]
> IMO the current approach to implement this feature looks too difficult, many code is duplicated and the code path looks weird. Isn't it possible to implement that feature by using a route guard that will check whether it is necessary to change the password and redirect the user to the change passform form? That will make the code much more cleaner.

If I'm not mistaken we decided once, that we don't want to display the navigation menu but stay on the login page as long as the password hasn't been updated. So just redirecting would not work in this case.

**Comment by s0nea** [comment]
@votdev 
>  many code is duplicated

I don't really see a lot of duplicated code. One thing that is indeed duplicated is the template of the ```UserPasswordLoginFormComponent```. That is because the ```UserPasswordFormComponent``` is using a card layout which looks ugly on the login page.

> the code path looks weird

Could you explain this a bit more?

> Isn't it possible to implement that feature by using a route guard that will check whether it is necessary to change the password and redirect the user to the change passform form? That will make the code much more cleaner.

In that case the change password form will be shown within the dashboard. E.g. you will see the navigation an so on. I think it's much nicer to have it on the login form in this special case.

**Comment by Exotelis** [comment]
> In that case the change password form will be shown within the dashboard. E.g. you will see the navigation an so on. I think it's much nicer to have it on the login form in this special case.

And in the case the navigation menu is visible, all menu items are disabled and cannot be clicked which could confuse the user. Therefore I'am in favor of having the change pwd functionallity on the login page

**Comment by votdev** [comment]
> > the code path looks weird
> 
> Could you explain this a bit more?

You create another form component that is displayed in the login form component. That looks weird too me. Isn't it possible to implement ALL in the login component? That would make much more easier IMO.

I will try to implement a route guard today which will not show the navigation menu. That should be easy to implement by using different layouts. I use this technique in my private project.

```
const routes: Routes = [
  { path: '', redirectTo: 'dashboard', pathMatch: 'full' },
  {
    path: '',
    component: DefaultLayoutComponent,
    children: [
      { path: 'login', component: LoginComponent },
      { path: 'standby', component: StandbyComponent },
      { path: 'shutdown', component: ShutdownComponent },
      { path: '404', component: NotFoundComponent }
    ]
  },
  {
    path: '',
    component: WorkbenchLayoutComponent,
    children: [
      {
        path: 'dashboard',
        canActivate: [AuthGuardService],
        canActivateChild: [AuthGuardService],
        loadChildren: './pages/dashboard/dashboard.module#DashboardModule',
        data: { title: gettext('Dashboard') }
      },
      {
```

**Comment by votdev** [comment]
With https://github.com/ceph/ceph/pull/32594 it should be simple now to cleanup the code of this PR a little bit.

**Comment by s0nea** [comment]
https://github.com/ceph/ceph/pull/32680 is now addressing the issue.

**Pull request closed without merging**
