### PR TITLE
os/bluestore: drop deferred_submit_lock, fix aio leak

### PR DESCRIPTION
**Pull request by liewegas**
This lock serves no purpose.  It only protects the call to the aio_submit
on the OpSequencer running batch, but we are the only caller who will do
that submission, and a new batch won't be moved into place until ours is
completed and retired (by the completion for the aio we are queueing).

More importantly, this fixes a deadlock:

- thread A submits aio, but the queue is full, and blocks
- thread B blocks taking deferred_submit_lock while holding deferred_lock
- aio completion thread blocks trying to take deferred_lock, and thus
no further aios are drained.

Fixes: http://tracker.ceph.com/issues/21171
Signed-off-by: Sage Weil <sage@redhat.com>

### CODE REVIEW

**Comment by liewegas** [comment]
I'm a bit nervous about this because previously I seemed to believe it was important to protect the aio_submit with a lock, but now I can't see why it would be needed...

**Comment by xiexingguo** [comment]
I was considering the same question earlier this morning...

**Comment by liewegas** [comment]
@markhpc is seeing a different deadlock with this applied. it looks more like more a lost aio; can't tell what is going on it.  Working on it!

**Comment by liewegas** [comment]
Found it!  Wasn't handling io_submit return value properly.

**Comment by liupan1111** [comment]
cool

**Comment by varadakari** [comment]
@yangdongsheng yeah the delay is for the retries, we retry after waiting for some more time, as we don't know the actual time it takes for io completion. Once we are out of retries anyways assert for the completion.

**Comment by liewegas** [comment]
http://pulpito.ceph.com/sage-2017-09-08_01:07:55-rados-wip-sage-testing2-2017-09-07-1650-distro-basic-smithi/

**Pull request merged**
