### PR TITLE
qa: merge kcephfs suite with fs

### PR DESCRIPTION
**Pull request by batrick**
https://pulpito.ceph.com/pdonnell-2020-10-30_02:26:51-fs-master-distro-basic-smithi/

https://pulpito.ceph.com/pdonnell-2020-10-30_21:56:12-fs-master-distro-basic-smithi/

https://pulpito.ceph.com/pdonnell-2020-11-01_04:08:33-fs-master-distro-basic-smithi/

https://pulpito.ceph.com/pdonnell-2020-11-02_02:29:29-fs:volumes-master-distro-basic-smithi/

with #37923: https://pulpito.ceph.com/pdonnell-2020-11-03_02:22:55-fs:volumes-wip-pdonnell-testing-20201102.231317-distro-basic-smithi/

https://pulpito.ceph.com/pdonnell-2020-11-03_04:01:15-fs:volumes-wip-pdonnell-testing-20201102.231317-distro-basic-smithi/

https://pulpito.ceph.com/pdonnell-2020-11-03_15:27:11-fs-wip-pdonnell-testing-20201103.040517-distro-basic-smithi/

### CODE REVIEW

**Comment by batrick** [comment]
WIP

https://pulpito.ceph.com/pdonnell-2020-10-30_02:26:51-fs-master-distro-basic-smithi/

https://pulpito.ceph.com/pdonnell-2020-10-30_21:56:12-fs-master-distro-basic-smithi/

**Comment by batrick** [comment]
jenkins test make check

**Comment by batrick** [comment]
https://pulpito.ceph.com/pdonnell-2020-11-03_23:40:35-fs-wip-pdonnell-testing-20201103.210407-distro-basic-smithi/

**Comment by batrick** [comment]
(fixed tox errors)

**Review by kotreshhr — APPROVED** [review]
Skimmed through all the patches and looks good.

**Review by ajarr — COMMENTED** [review]
LGTM. Couple of questions:

any reason for prefix `cfuse_` for yaml filenames in qa/suites/fs/thrash/tasks/2-workunit/ and qa/cephfs/tasks/

I could not follow the commit message, "qa: rename distro link to distros

This needs to become any overrides present in "mount". Otherwise kclient
distro overrides have no effect." Can you elaborate?

**Comment by batrick** [comment]
> LGTM. Couple of questions:
> 
> any reason for prefix `cfuse_` for yaml filenames in qa/suites/fs/thrash/tasks/2-workunit/ and qa/cephfs/tasks/

It's historical. I think there used to be conf overrides for the ceph-fuse client. symlinks only recently became common.

> I did not understand the purpose of the commit [c495b23](https://github.com/ceph/ceph/commit/c495b23090fcc11df0ff617db9d77b9df661ecb7) with commit message,
> "qa: rename distro link to distros
> This needs to become any overrides present in "mount". Otherwise kclient
> distro overrides have no effect."
> Can you elaborate?

The yamls are loaded in alphabetical order. The previous name of distros was `supported-random-distros$` (`s` comes after `mounts` of course). Therefore, the distro loaded from `supported-random-distros$` would override the `os_type` and `os_version` fields set by the `mount/kclient/...` yamls.

**Comment by ajarr** [comment]
> > LGTM. Couple of questions:
> > any reason for prefix `cfuse_` for yaml filenames in qa/suites/fs/thrash/tasks/2-workunit/ and qa/cephfs/tasks/
> 
> It's historical. I think there used to be conf overrides for the ceph-fuse client. symlinks only recently became common.
> 
> > I did not understand the purpose of the commit [c495b23](https://github.com/ceph/ceph/commit/c495b23090fcc11df0ff617db9d77b9df661ecb7) with commit message,
> > "qa: rename distro link to distros
> > This needs to become any overrides present in "mount". Otherwise kclient
> > distro overrides have no effect."
> > Can you elaborate?
> 
> The yamls are loaded in alphabetical order. The previous name of distros was `supported-random-distros$` (`s` comes after `mounts` of course). Therefore, the distro loaded from `supported-random-distros$` would override the `os_type` and `os_version` fields set by the `mount/kclient/...` yamls.

Got it. Thanks!

**Review by ajarr — APPROVED** [review]

**Comment by batrick** [comment]
re-run with tox fixes (which also fix an import error): https://pulpito.ceph.com/pdonnell-2020-11-04_17:39:34-fs-wip-pdonnell-testing-20201103.210407-distro-basic-smithi/

**Pull request merged**
