### PR TITLE
rgw/S3select: remove assert from csv-parser, adding updates

### PR DESCRIPTION
**Pull request by galsalomon66**
https://tracker.ceph.com/issues/63245

https://github.com/ceph/s3select/pull/151
https://github.com/ceph/s3select/pull/148
https://github.com/ceph/s3select/pull/144
https://github.com/ceph/s3select/pull/130

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [x] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Comment by galsalomon66** [comment]
https://pulpito.ceph.com/gsalomon-2024-03-02_14:41:53-rgw:verify-s3select_remove_assert_and_updates-distro-default-smithi/
2 failures (not related)

**Comment by galsalomon66** [comment]
https://pulpito.ceph.com/gsalomon-2024-03-03_05:48:46-rgw-s3select_remove_assert_and_updates-distro-default-smithi/
1 dead , 2 failures(multisite), 70 passed

**Comment by galsalomon66** [comment]
https://pulpito.ceph.com/gsalomon-2024-03-03_15:55:54-rgw-s3select_remove_assert_and_updates-distro-default-smithi/

2 failures (multisite)
71 passed

**Comment by galsalomon66** [comment]
jenkins test make check

**Comment by cbodley** [comment]
> The following tests FAILED:
	  7 - run-tox-mgr-dashboard-py3 (Failed)

**Comment by cbodley** [comment]
jenkins test make check

**Review by cbodley — APPROVED** [review]

**Comment by cbodley** [comment]
> The following tests FAILED:
	  7 - run-tox-mgr-dashboard-py3 (Failed)
	227 - unittest_rgw_amqp (Failed)

**Comment by cbodley** [comment]
jenkins test make check

**Comment by cbodley** [comment]
thanks @galsalomon66, would you please prepare the squid backport asap?

**Pull request merged**
