### PR TITLE
exporter: dual stack by default

### PR DESCRIPTION
**Pull request by hydro-b**
Fixes: https://tracker.ceph.com/issues/64095

Signed-off-by: Stefan Kooman <stefan@kooman.org>

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Comment by hydro-b** [comment]
@avanthakkar What do you think of this PR? Can you approve this if it passes the checks?

**Comment by hydro-b** [comment]
> I think afaik that's default for ipv6 address and for cephadm based deployment of exporter the value of address is set accordingly after this PR
> https://github.com/ceph/ceph/pull/52687/files

Yes, that was my thought as well. But for some reason it does not seem to work on our systems. I redeployed the ceph-exporter daemons on all nodes but they are still deployed with "--addrs=0.0.0.0" (we are running 18.2.1, that has the PR 52687). We have disabled IPv4 (`ms_bind_ipv4 false`) and enabled IPv6 (`ms_bind_ipv6 true`).

> If you wish to change config I think that could be simply done with `ceph config set` or if changing for a specific exporter daemon then `ceph daemon <daemon_name> config set exporter_addr` . Just FYI this ain't a runtime option so you'd need to restart daemons or start daemon with this desired config value

I guess you meant something like: `ceph config set ceph-exporter.mon1 exporter_addr "::"`, however, ceph-exporter (mon1 in this example) is not recognized as a valid config target.

What I want is that on IPv6 only systems I do not need to change any defaults, and it should work out of the box, i.e. listen on IPv6 ip address(es), the same as for IPv4 systems.

**Comment by hydro-b** [comment]
I managed to get it to work: adjusted `/etc/hosts` so 127.0.0.1 localhost entry would not include the hostname. After redeployment the "::" addr gets used. Note that in that case it works for both IPv4 and IPv6. This PR would make it so it will always work on IPv6 as well, even when IPv4 references in /etc/hosts exists (AFAIK it's not yet possible to disable IPv4 in linux as both stacks share code).

**Comment by Svelar** [comment]
jenkins test make check arm64

**Comment by DrumSlayers** [comment]
> I managed to get it to work: **adjusted `/etc/hosts` so 127.0.0.1 localhost entry would not include the hostname**. After redeployment the "::" addr gets used. Note that in that case it works for both IPv4 and IPv6. This PR would make it so it will always work on IPv6 as well, even when IPv4 references in /etc/hosts exists (AFAIK it's not yet possible to disable IPv4 in linux as both stacks share code).


This "fix" is still relevent on Ceph Reef v18.2.7, managed to get ceph-exporter to bind on v6 socket after removing the v4 localhost bind for the hostname in /etc/hosts (127.0.1.1 in my specific case)

This is pretty odd, not to say weird, as other ceph services are listening in v6 without issues. (Excepting for the prometheus service discovery web server, but it has been fixed on upstream)

**Pull request closed without merging**
