### PR TITLE
mgr/PyFormatter: implement dump_format_va

### PR DESCRIPTION
**Pull request by liewegas**
Signed-off-by: Sage Weil <sage@redhat.com>

### CODE REVIEW

**Comment by Liuchang0812** [comment]
@liewegas It would be better if you could add `Fixes: http://tracker.ceph.com/issues/20245` to commit message. 😄 

I was impressed with the simplicity of supporting `dump_format_va`. I have took some time to figure out how to process `ns` and `quoted` parameters.

**Comment by tchaikov** [comment]
better off fixing the `dump_float()` method, IMO

**Comment by tchaikov** [comment]
this fixes http://tracker.ceph.com/issues/20249?issue_count=412

**Comment by Liuchang0812** [comment]
yes! I prefer this one.

**Comment by tchaikov** [comment]
```
 91/173 Test   #5: cephtool-test-mon.sh ....................   Passed  270.28 sec
```

**Pull request merged**
