### PR TITLE
crimson/osd: fetch_config() before mkfs

### PR DESCRIPTION
**Pull request by tchaikov**
## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by markhpc** [comment]
Hi Kefu, I tried this out with CBT in the configuration we were looking at yesterday.  If the fsid is set in ceph.conf it works (as before) but now if the fsid is not set it behaves slightly differently.  Instead of showing the fsid warnings in the stderr log, it appears crimson-osd stalls at some point during the initial crimson-osd invocation for mkfs:

```
sudo sh -c "ulimit -n 16384 && ulimit -c unlimited && exec env -i TCMALLOC_MAX_TOTAL_THREAD_CACHE_BYTES=134217728 /usr/local/bin/crimson-osd -c /tmp/cbt/ceph/ceph.conf -i 0 --mkfs --osd-uuid 0f3a7dcc-2bcf-4c55-861c-e709b54a5425"
```

The osd debug 20 log is attached.
[crimson_fetch_config_no_fsid_debug20.stderr.txt](https://github.com/ceph/ceph/files/5849574/crimson_fetch_config_no_fsid_debug20.stderr.txt)

**Comment by tchaikov** [comment]
@markhpc  fixed and repushed.

**Comment by tchaikov** [comment]
jenkins test make check

**Review by rzarzynski — APPROVED** [review]

**Comment by rzarzynski** [comment]
jenkins test make check

```
The following tests FAILED:
	  1 - run-tox-mgr (Failed)
```

**Comment by rzarzynski** [comment]
jenkins test make check

**Comment by tchaikov** [comment]
changelog

- updated the indent of `case` statements.

**Pull request merged**
