### PR TITLE
doc/cephadm: update cephadm compatability and stability page

### PR DESCRIPTION
**Pull request by adk3798**
This page is very out of date. This commit probably doesn't cover everything there is to say about stability and compatability in cephadm, but it at least gets it noticeably closer to reality

Signed-off-by: Adam King <adking@redhat.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [x] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [x] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Review by zdover23 — APPROVED** [review]

**Comment by zdover23** [comment]
@adk3798: Do you have any objection to this commit being backported to the Pacific and Quincy branches?

**Comment by adk3798** [comment]
> @adk3798: Do you have any objection to this commit being backported to the Pacific and Quincy branches?

Quincy I definitely wanted to backport it to. Pacific I wasn't sure as some of the features listed as under development I expect to never reach there and the new table entry is only useful for quincy onward. But I don't think I'd totally object to it either.

**Comment by zdover23** [comment]
> > @adk3798: Do you have any objection to this commit being backported to the Pacific and Quincy branches?
> 
> Quincy I definitely wanted to backport it to. Pacific I wasn't sure as some of the features listed as under development I expect to never reach there and the new table entry is only useful for quincy onward. But I don't think I'd totally object to it either.

In that case, I'll backport this commit to Quincy and Pacific both.

**Comment by zdover23** [comment]
https://github.com/ceph/ceph/pull/50336 - Quincy backport
https://github.com/ceph/ceph/pull/50337 - Pacific backport

**Comment by adk3798** [comment]
> #50336 - Quincy backport #50337 - Pacific backport

@zdover23 given the reef branch off earlier today, I guess this needs to end up there as well

**Comment by zdover23** [comment]
> > #50336 - Quincy backport #50337 - Pacific backport
> 
> @zdover23 given the reef branch off earlier today, I guess this needs to end up there as well

https://github.com/ceph/ceph/pull/50338 - Reef backport

**Pull request merged**
