### PR TITLE
hammer: rbd: fix parameter check

### PR DESCRIPTION
**Pull request by YankunLi**
http://tracker.ceph.com/issues/18237

### CODE REVIEW

**Comment by dillaman** [comment]
lgtm

**Comment by smithfarm** [comment]
@YankunLi Please add `Fixes: http://tracker.ceph.com/issues/18237` right before the Signed-off-by line

**Comment by smithfarm** [comment]
This passed an RBD suite at http://tracker.ceph.com/issues/17151#note-31

**Comment by dillaman** [comment]
👍

**Pull request merged**
