### PR TITLE
[DNM] Update rgw_rest_s3.cc

### PR DESCRIPTION
**Pull request by lnsyyj**
Support aws js sdk  multipart upload

### CODE REVIEW

**Comment by lnsyyj** [comment]
why? The existence of this problem, add the xml format etag, which can be repaired.

**Comment by lnsyyj** [comment]
I am very sad
(T_T)

**Comment by tchaikov** [comment]
@lnsyyj YuJiang, because quite a few Ceph developers are in their holidays, so we are not be very responsive these couple days. so please be more patient in these quiet days. but there are problems in your pull request,

1. normally we only backport fixes to a LTS branch, instead features are added to the master branch. but you are targeting firefly here for a new feature.
1. you might want to add a "Signed-off-by:" line at the end of your commit message, see https://github.com/ceph/ceph/blob/master/SubmittingPatches#L61
1. you might need to revise your commit message, for instance, add an title for it, and have an an appropriate prefix for the title, see `git log ./rgw/rgw_rest_s3.cc` for more examples.
1. do you have a test for your change? and how do you test it?

**Comment by lnsyyj** [comment]
Sorry, this is not a code issue
Add to my code will cause problems python api md5
aws js sdk multiparts uploads you need to configure exposed etag
Add the following configuration：

Header set Access-Control-Expose-Headers "ETag"

**Comment by lnsyyj** [comment]
please  do not merge the code, there will be problems

**Comment by yehudasa** [comment]
@lnsyyj can we close this PR?

**Comment by yehudasa** [comment]
@lnsyyj I'm closing this PR now, you can reopen or open a new one if you figure out the issue.

**Comment by lnsyyj** [comment]
@yehudasa ok

**Pull request closed without merging**
