### PR TITLE
mgr/balancer: fix initial weight-set value for newly created osds

### PR DESCRIPTION
**Pull request by xiexingguo**
This is a follow-up fix for https://github.com/ceph/ceph/pull/26955,
which should make any OSD addition start with a zeroed weight-set weight.
But without this fix, the balancer won't be able to handle it properly..

Signed-off-by: xie xingguo <xie.xingguo@zte.com.cn>

- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by liewegas** [comment]
We'll need to backport this fix to nautilus, too.. want to either open a tracker or a nautilus PR?  Thanks!

**Comment by xiexingguo** [comment]
> We'll need to backport this fix to nautilus, too.. want to either open a tracker or a nautilus PR? Thanks!

https://github.com/ceph/ceph/pull/28279

**Comment by tchaikov** [comment]
- http://pulpito.ceph.com/kchai-2019-05-30_03:19:00-rados-wip-kefu-testing-2019-05-30-0110-distro-basic-smithi/
- http://pulpito.ceph.com/kchai-2019-05-30_03:19:00-rados-wip-kefu-testing-2019-05-30-0110-distro-basic-smithi/

**Comment by xiexingguo** [comment]
@tchaikov  Thanks!

**Pull request merged**
