### PR TITLE
nautilus: mgr/volumes: use py3 items iterator

### PR DESCRIPTION
**Pull request by smithfarm**
IMPORTANT NOTE: one commit from the master PR, 4e166338561b924cc73242334184d24074e036f8, was omitted because it touched code that doesn't exist in nautilus

backport tracker: https://tracker.ceph.com/issues/43137

---

backport of https://github.com/ceph/ceph/pull/31986
parent tracker: https://tracker.ceph.com/issues/43113

this backport was staged using ceph-backport.sh version 15.0.0.6950
find the latest version at https://github.com/ceph/ceph/blob/master/src/script/ceph-backport.sh

### CODE REVIEW

**Comment by yuriw** [comment]
[wip-yuri7-testing-2020-01-14-2039-nautilus](https://trello.com/c/64rDrlDV/806-wip-yuri7-testing-2020-01-14-2039-nautilus)

**Comment by ajarr** [comment]
this backport is incomplete need to cherry-pick couple of commits. I'll update.

**Comment by ajarr** [comment]
See this in Yuri's run,  wip-yuri7-testing-2020-01-14-2039-nautilus
```
======================================================================
ERROR: test_connection_expiration (tasks.cephfs.test_volumes.TestVolumes)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/teuthworker/src/git.ceph.com_ceph-c_wip-yuri7-testing-2020-01-14-2039-nautilus/qa/tasks/cephfs/test_volumes.py", line 118, in test_connection_expiration
    self.wait_until_evicted(sessions[0]['id'], timeout=90)
AttributeError: 'TestVolumes' object has no attribute 'wait_until_evicted'
```

To get around this we would need to cherry-pick commits https://github.com/ceph/ceph/pull/31986/commits/4e166338561b924cc73242334184d24074e036f8
and
https://github.com/ceph/ceph/pull/31797/commits/98e3b7efe8bc92d88f161c892ce91a7fff67052c
The latter commit is part of a bigger different PR, https://github.com/ceph/ceph/pull/31797

@batrick , can you please take a look? I think it's better if you could do this backport.

**Comment by batrick** [comment]
Think we should block this until https://tracker.ceph.com/issues/43139 or merge the backports.

**Comment by ajarr** [comment]
> Think we should block this until https://tracker.ceph.com/issues/43139 or merge the backports.

Yes. A single PR that fixes trackers 43139 and 43137 makes sense to me.

**Comment by smithfarm** [comment]
@ajarr Feel free to close any of my cephfs backport PRs, if needed, anytime (not just this one).

**Comment by ajarr** [comment]
> @ajarr Feel free to close any of my cephfs backport PRs, if needed, anytime (not just this one).

Got it.

**Pull request closed without merging**
