### PR TITLE
nautilus: bluestore/bluefs: make accounting resiliant to unlock()

### PR DESCRIPTION
**Pull request by ifed01**
backport tracker: https://tracker.ceph.com/issues/47213

---

Moved vselector.sub_usage, so sub_usage and add_usage will not cross
_flush_bdev_safely(), which contains unlock().

Fixes: https://tracker.ceph.com/issues/47213
Signed-off-by: Adam Kupczyk <akupczyk@redhat.com>
(cherry picked from commit 82fa73a411338f4bd27eb9b5863bf5b800617a67)

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by smithfarm** [comment]
```
The following tests FAILED:
	  5 - run-tox-mgr-dashboard (Failed)
```

**Comment by smithfarm** [comment]
jenkins test make check

**Comment by smithfarm** [comment]
Same failure. I think there is a good chance this failure happens on the tip of the nautilus branch, too, because I've seen it in other nautilus PRs.

**Review by aclamk — APPROVED** [review]
Looks good.

**Comment by neha-ojha** [comment]
jenkins test make check

**Review by neha-ojha — APPROVED** [review]

**Comment by smithfarm** [comment]
jenkins test api

**Comment by smithfarm** [comment]
@epuertat Whom shoud I ping to debug repeated failures of `ceph API tests` check?

**Comment by epuertat** [comment]
> @epuertat Whom shoud I ping to debug repeated failures of `ceph API tests` check?

@smithfarm Either @callithea, myself or anyone else at #ceph-dashboard IRC.

Is the failure exactly the same? [Current one](https://jenkins.ceph.com/job/ceph-api/3682/) is:
```
2020-09-23 10:28:57,731.731 INFO:__main__:----------------------------------------------------------------------
2020-09-23 10:28:57,731.731 INFO:__main__:Traceback (most recent call last):
2020-09-23 10:28:57,732.732 INFO:__main__:  File "/home/jenkins-build/build/workspace/ceph-api/qa/tasks/mgr/dashboard/helper.py", line 117, in setUpClass
2020-09-23 10:28:57,732.732 INFO:__main__:    cls._load_module("dashboard")
2020-09-23 10:28:57,732.732 INFO:__main__:  File "/home/jenkins-build/build/workspace/ceph-api/qa/tasks/mgr/mgr_test_case.py", line 144, in _load_module
2020-09-23 10:28:57,732.732 INFO:__main__:    cls.wait_until_true(has_restarted, timeout=30)
2020-09-23 10:28:57,733.733 INFO:__main__:  File "/home/jenkins-build/build/workspace/ceph-api/qa/tasks/ceph_test_case.py", line 197, in wait_until_true
2020-09-23 10:28:57,733.733 INFO:__main__:    raise TestTimeoutError("Timed out after {0}s".format(elapsed))
2020-09-23 10:28:57,733.733 INFO:__main__:tasks.ceph_test_case.TestTimeoutError: Timed out after 30s
2020-09-23 10:28:57,733.733 INFO:__main__:
2020-09-23 10:28:57,734.734 INFO:__main__:----------------------------------------------------------------------
2020-09-23 10:28:57,734.734 INFO:__main__:Ran 49 tests in 559.575s
```
I don't see any Ceph Tracker already reporting that...

**Comment by smithfarm** [comment]
jenkins test api

**Comment by smithfarm** [comment]
@epuertat Thanks. I'd prefer to ping folks right in the PRs.

**Comment by smithfarm** [comment]
@epuertat Do you see any plausible way that failure could be related to this particular set of code changes?

**Comment by epuertat** [comment]
> @epuertat Do you see any plausible way that failure could be related to this particular set of code changes?

I cannot tell. Looking at the Jenkins console, it seems there's a segfault over there (@neha-ojha could that be related):

```
2020-09-23 10:28:27.350 7ffbd8bfc700 -1 *** Caught signal (Segmentation fault) **
 in thread 7ffbd8bfc700 thread_name:msgr-worker-0

 ceph version Development (no_version) nautilus (stable)
 1: (()+0xd0a79e) [0x56519b16579e]
 2: (()+0x128a0) [0x7ffbdd5c78a0]
 3: (ProtocolV2::handle_auth_request(ceph::buffer::v14_2_0::list&)+0x440) [0x7ffbdf741ebc]
 4: (ProtocolV2::handle_frame_payload()+0x1df) [0x7ffbdf7378c7]
 5: (ProtocolV2::handle_read_frame_dispatch()+0x158) [0x7ffbdf73696c]
 6: (ProtocolV2::_handle_read_frame_epilogue_main()+0x109) [0x7ffbdf73856d]
 7: (ProtocolV2::_handle_read_frame_segment()+0x7c) [0x7ffbdf7375fa]
 8: (ProtocolV2::handle_read_frame_segment(std::unique_ptr<ceph::buffer::v14_2_0::ptr_node, ceph::buffer::v14_2_0::ptr_node::disposer>&&, int)+0x2e4) [0x7ffbdf737518]
 9: (CtRxNode<ProtocolV2>::call(ProtocolV2*) const+0x8c) [0x7ffbdf761230]
 10: (ProtocolV2::run_continuation(Ct<ProtocolV2>&)+0x5e) [0x7ffbdf72ac9c]
 11: (()+0x1770faa) [0x7ffbdf731faa]
 12: (()+0x178aa31) [0x7ffbdf74ba31]
 13: (std::function<void (char*, long)>::operator()(char*, long) const+0x61) [0x7ffbdf6ee81f]
 14: (AsyncConnection::process()+0xd3b) [0x7ffbdf6e9997]
 15: (C_handle_read::do_request(unsigned long)+0x28) [0x7ffbdf6eda30]
 16: (EventCenter::process_events(unsigned int, std::chrono::duration<unsigned long, std::ratio<1l, 1000000000l> >*)+0x678) [0x7ffbdf764abc]
 17: (()+0x17b11f6) [0x7ffbdf7721f6]
 18: (()+0x17b26c9) [0x7ffbdf7736c9]
 19: (std::function<void ()>::operator()() const+0x32) [0x7ffbdf770a4c]
 20: (void std::__invoke_impl<void, std::function<void ()>>(std::__invoke_other, std::function<void ()>&&)+0x20) [0x7ffbdf7702e9]
 21: (std::__invoke_result<std::function<void ()>>::type std::__invoke<std::function<void ()>>(std::function<void ()>&&)+0x26) [0x7ffbdf76fa76]
 22: (decltype (__invoke((_S_declval<0ul>)())) std::thread::_Invoker<std::tuple<std::function<void ()> > >::_M_invoke<0ul>(std::_Index_tuple<0ul>)+0x28) [0x7ffbdf7719ac]
 23: (std::thread::_Invoker<std::tuple<std::function<void ()> > >::operator()()+0x1d) [0x7ffbdf77197d]
 24: (std::thread::_State_impl<std::thread::_Invoker<std::tuple<std::function<void ()> > > >::_M_run()+0x1c) [0x7ffbdf77195c]
 25: (()+0xbd6df) [0x7ffbdd0e56df]
 26: (()+0x76db) [0x7ffbdd5bc6db]
 27: (clone()+0x3f) [0x7ffbdc7a2a3f]
```

**Comment by smithfarm** [comment]
@epuertat Each time the error is different. This time, it's:

```
2020-09-23 13:48:16,573.573 INFO:__main__:======================================================================
2020-09-23 13:48:16,573.573 INFO:__main__:FAIL: test_pool_create (tasks.mgr.dashboard.test_pool.PoolTest)
2020-09-23 13:48:16,574.574 INFO:__main__:----------------------------------------------------------------------
2020-09-23 13:48:16,574.574 INFO:__main__:Traceback (most recent call last):
2020-09-23 13:48:16,574.574 INFO:__main__:  File "/home/jenkins-build/build/workspace/ceph-api/qa/tasks/mgr/dashboard/test_pool.py", line 269, in test_pool_create
2020-09-23 13:48:16,574.574 INFO:__main__:    self.assertIn(conf, new_pool['configuration'])
2020-09-23 13:48:16,574.574 INFO:__main__:AssertionError: {'name': 'rbd_qos_bps_limit', 'source': 1, 'value': '2048'} not found in []
2020-09-23 13:48:16,574.574 INFO:__main__:
2020-09-23 13:48:16,575.575 INFO:__main__:----------------------------------------------------------------------
2020-09-23 13:48:16,575.575 INFO:__main__:Ran 82 tests in 1025.634s
2020-09-23 13:48:16,575.575 INFO:__main__:
2020-09-23 13:48:16,575.575 INFO:__main__:FAILED (failures=1)
2020-09-23 13:48:16,575.575 INFO:__main__:
2020-09-23 13:48:16,576.576 INFO:__main__:======================================================================
2020-09-23 13:48:16,576.576 INFO:__main__:FAIL: test_pool_create (tasks.mgr.dashboard.test_pool.PoolTest)
2020-09-23 13:48:16,576.576 INFO:__main__:----------------------------------------------------------------------
2020-09-23 13:48:16,576.576 INFO:__main__:Traceback (most recent call last):
2020-09-23 13:48:16,576.576 INFO:__main__:  File "/home/jenkins-build/build/workspace/ceph-api/qa/tasks/mgr/dashboard/test_pool.py", line 269, in test_pool_create
2020-09-23 13:48:16,576.576 INFO:__main__:    self.assertIn(conf, new_pool['configuration'])
2020-09-23 13:48:16,577.577 INFO:__main__:AssertionError: {'name': 'rbd_qos_bps_limit', 'source': 1, 'value': '2048'} not found in []
2020-09-23 13:48:16,577.577 INFO:__main__:
```

**Comment by epuertat** [comment]
@smithfarm that's a [known one](https://tracker.ceph.com/issues/46815). We're working on stabilizing those, but it's really hard to fix issues that cannot be reproduced deterministically. 

I'll retrigger this for a third time, but I think those failures are unrelated to this.

**Comment by epuertat** [comment]
jenkins test api

**Comment by yuriw** [comment]
[wip-yuri8-testing-2020-09-25-1117-nautilus](https://trello.com/c/dN77beV0/1022-wip-yuri8-testing-2020-09-25-1117-nautilus)

**Pull request merged**
