### PR TITLE
qa: run chmod with sudo in _create_mntpt() in mount.py

### PR DESCRIPTION
**Pull request by dparmar18**
self.client_remote.run(args=f'chmod 0000 {self.hostfs_mntpt}', timeout=60) leads to failures in teuthology like:

```
Command failed on smithi203 with status 1: 'chmod 0000 /home/ubuntu/cephtest/mnt.1'
```

This is fixed by adding sudo with chmod and appending omit_sudo=False arg in self.client_remote.run()

Introduced-by: https://github.com/ceph/ceph/commit/60d5d7cf9cac250905ec4cfaee0c8d508f98ed3e
Signed-off-by: Dhairya Parmar <dparmar@redhat.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [x] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by vshankar** [comment]
@dparmar18 you can add the `Introduced-by: <commit>` tag in the commit message.

**Comment by dparmar18** [comment]
> @dparmar18 you can add the `Introduced-by: <commit>` tag in the commit message.

Sure, I'll do it

**Review by rishabh-d-dave — APPROVED** [review]
Any ideas why we never saw this issue before? Probably this issue was introduced by some commit after 60d5d7cf9cac250905ec4cfaee0c8d508f98ed3e since it was not seen until recently.

**Comment by rishabh-d-dave** [comment]
@vshankar I am not sure but I think this needs to be backported so that we don't see this issue in QA run for older versions.

**Comment by vshankar** [comment]
> @vshankar I am not sure but I think this needs to be backported so that we don't see this issue in QA run for older versions.

This fixes running tests with vstart_runner. Are we sure changes in commit 60d5d7cf9cac250905ec4cfaee0c8d508f98ed3e is the issue? @dparmar18 ?

**Comment by dparmar18** [comment]
@rishabh-d-dave @vshankar This issue was never reported previously in any runs since the induction of the commit https://github.com/ceph/ceph/commit/60d5d7cf9cac250905ec4cfaee0c8d508f98ed3e. This issue occurred when I was running https://github.com/ceph/ceph/pull/48280 in teuthology where I found my yamls were mounting ceph-fuse twice and that led to almost all the failures. I feel this should not occur with correct yamls, so, now when the correct yamls have been pushed into that PR and in order to confirm this assumption I ran all the tests again and it went as expected: https://pulpito.ceph.com/dparmar-2022-10-14_11:09:18-fs:upgrade-main-distro-default-smithi/. 

Therefore I feel it's safe to say we don't need this PR.

**Comment by dparmar18** [comment]
> > @rishabh-d-dave @vshankar This issue was never reported previously in any runs since the induction of the commit [60d5d7c](https://github.com/ceph/ceph/commit/60d5d7cf9cac250905ec4cfaee0c8d508f98ed3e). This issue occurred when I was running #48280 in teuthology where I found my yamls were mounting ceph-fuse twice and that led to almost all the failures. I feel this should not occur with correct yamls, so, now when the correct yamls have been pushed into that PR and in order to confirm this assumption I ran all the tests again and it went as expected: https://pulpito.ceph.com/dparmar-2022-10-14_11:09:18-fs:upgrade-main-distro-default-smithi/.
> 
> So, the failures were a case of incorrect yamls which have now being fixed in the PR?

Yes, Correct.
> 
> and BTW, the test run has failures like
> 
> ```
> Test failure: test_newops_getvxattr (tasks.cephfs.test_newops.TestNewOps)
> ```
> 
> That's fixed in main - are you running an old build?

Yeah this branch doesn't contain Xiubo's fix but this failure occurs with nautilus cluster being used in tests. So won't this still occur until the patch is pushed in Nautilus branch?

**Pull request closed without merging**
