### PR TITLE
install-deps.sh: create virtualenv only if necessary

### PR DESCRIPTION
**Pull request by tchaikov**

### CODE REVIEW

**Comment by tchaikov** [comment]
@dachary hope this can help with speed of multiple run of install-deps.sh and it addresses @XinzeChi 's problem also.

**Comment by dachary** [comment]
@tchaikov it is a good fix. Maybe **get_pip_and_wheel** can be renamed to something else like **prepare_wheelhouse** and encapsulate the temporary wheelhouse that prevents a incomplete wheelhouse to be mistaken as one that actually has all that's needed ?

**Comment by dachary** [comment]
Ah, no, it cannot conveniently encapsulate the temporary wheelhouse. Just renaming then ;-) **populate_wheelhouse** ?

**Comment by tchaikov** [comment]
@dachary thanks loic, i added a commit to rename this function. and also fixed a spelling error in the commit message of f81f651. could you take a look again?

**Comment by tchaikov** [comment]
the build is passed: http://gitbuilder.sepia.ceph.com/gitbuilder-ceph-rpm-centos7-amd64-basic/log.cgi?log=ab254c975dd546bfe341833ee228bd9a5537c373

**Pull request merged**
