### PR TITLE
mgr/dashboard: SSO not working after REST API versioning

### PR DESCRIPTION
**Pull request by avanthakkar**
saml2: Fix versioning parameter for saml2 endpoints including minor fix for endpoints with xml=true

Fixes: https://tracker.ceph.com/issues/48362

Signed-off-by: Avan Thakkar <athakkar@redhat.com>

## Checklist
- [x] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Review by tchaikov — CHANGES_REQUESTED** [review]
the title of the commit message reads like a bug report. ideally, the title of the commit message should use the imperative mood. see also https://github.com/ceph/ceph/blob/master/SubmittingPatches.rst#3-describe-your-changes . please use `git commit --amend`  and `git push -f` for revising the commit message and its title.

**Comment by avanthakkar** [comment]
jenkins test make check

**Comment by avanthakkar** [comment]
jenkins test dashboard

**Review by epuertat — APPROVED** [review]
Awesome, @avanthakkar ! Super quick fix 👍🏼

**Comment by epuertat** [comment]
@avanthakkar Please use the imperative style for the PR and commit titles as @tchaikov suggested!

**Review by alfonsomthd — APPROVED** [review]

**Comment by tchaikov** [comment]
@avanthakkar i am not sure why you dismissed my review.  

> SSO not working after REST API versioning

still does not summarize the change you made in this PR.

**Comment by avanthakkar** [comment]
> @avanthakkar i am not sure why you dismissed my review.
> 
Sorry  I misunderstood it with PR body description instead of the title.
> > SSO not working after REST API versioning
> 
> still does not summarize the change you made in this PR.

**Pull request merged**
