### PR TITLE
qa: use a larger timeout for kernel_untar_build workunit

### PR DESCRIPTION
**Pull request by vshankar**
Fixes: http://tracker.ceph.com/issues/68855

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Comment by vshankar** [comment]
This PR is under test in [https://tracker.ceph.com/issues/68968](https://tracker.ceph.com/issues/68968).

**Comment by vshankar** [comment]
Fixed a mess-up with incorrect placement of `timeout`.

**Comment by vshankar** [comment]
jenkins make check arm64

**Comment by vshankar** [comment]
jenkins test make check arm64

**Comment by vshankar** [comment]
jenkins test submodules

**Comment by vshankar** [comment]
https://tracker.ceph.com/projects/cephfs/wiki/Main#wip-vshankar-testing-20241219063429-debug

**Comment by vshankar** [comment]
jenkins retest this please

**Comment by mchangir** [comment]
There are 2 FAILED jobs in this run which have executed the `kernel_untar_build.sh` workunit with failure reasons as below:

1. [8044466](https://pulpito.ceph.com/vshankar-2024-12-19_10:00:45-fs-wip-vshankar-testing-20241219.063429-debug-testing-default-smithi/8044466/): `error during quiesce thrashing: Error quiescing set '15031b18': 110 (ETIMEDOUT)`
2. [8044521](https://pulpito.ceph.com/vshankar-2024-12-19_10:00:45-fs-wip-vshankar-testing-20241219.063429-debug-testing-default-smithi/8044521/): `cluster [WRN] Scrub error on inode 0x1000000ecc8 (/volumes/qa/sv_1/b51d1e5d-7379-46d5-9271-da1c608fc98b/client.0/tmp/t/linux-6.5.11/include) see mds.b log and "damage ls" output for details`

The DEAD jobs haven't failed on the `kernel_untar_build.sh` workunit.
All the DEAD jobs have `hit max job timeout` while running the following jobs:
1. [8044485](https://pulpito.ceph.com/vshankar-2024-12-19_10:00:45-fs-wip-vshankar-testing-20241219.063429-debug-testing-default-smithi/8044485/): `tasks/uninlining`
2. [8044490](https://pulpito.ceph.com/vshankar-2024-12-19_10:00:45-fs-wip-vshankar-testing-20241219.063429-debug-testing-default-smithi/8044490): `1-tests/fscrypt-dbench`
3. [8044495](https://pulpito.ceph.com/vshankar-2024-12-19_10:00:45-fs-wip-vshankar-testing-20241219.063429-debug-testing-default-smithi/8044495): `tasks/xfstests-dev`
4. [8044506](https://pulpito.ceph.com/vshankar-2024-12-19_10:00:45-fs-wip-vshankar-testing-20241219.063429-debug-testing-default-smithi/8044506): `tasks/workunit/quota`

**Comment by vshankar** [comment]
> There are 2 FAILED jobs in this run which have executed the `kernel_untar_build.sh` workunit with failure reasons as below:
> 
> 1. [8044466](https://pulpito.ceph.com/vshankar-2024-12-19_10:00:45-fs-wip-vshankar-testing-20241219.063429-debug-testing-default-smithi/8044466/): `error during quiesce thrashing: Error quiescing set '15031b18': 110 (ETIMEDOUT)`
> 2. [8044521](https://pulpito.ceph.com/vshankar-2024-12-19_10:00:45-fs-wip-vshankar-testing-20241219.063429-debug-testing-default-smithi/8044521/): `cluster [WRN] Scrub error on inode 0x1000000ecc8 (/volumes/qa/sv_1/b51d1e5d-7379-46d5-9271-da1c608fc98b/client.0/tmp/t/linux-6.5.11/include) see mds.b log and "damage ls" output for details`

Yeh. These are known issues. The first one is due to slow cap recall while the other one is scrub related. IOW, these failures are unrelated to the timeout change in this PR.

> 
> The DEAD jobs haven't failed on the `kernel_untar_build.sh` workunit. All the DEAD jobs have `hit max job timeout` while running the following jobs:
> 
> 1. [8044485](https://pulpito.ceph.com/vshankar-2024-12-19_10:00:45-fs-wip-vshankar-testing-20241219.063429-debug-testing-default-smithi/8044485/): `tasks/uninlining`
> 2. [8044490](https://pulpito.ceph.com/vshankar-2024-12-19_10:00:45-fs-wip-vshankar-testing-20241219.063429-debug-testing-default-smithi/8044490): `1-tests/fscrypt-dbench`
> 3. [8044495](https://pulpito.ceph.com/vshankar-2024-12-19_10:00:45-fs-wip-vshankar-testing-20241219.063429-debug-testing-default-smithi/8044495): `tasks/xfstests-dev`
> 4. [8044506](https://pulpito.ceph.com/vshankar-2024-12-19_10:00:45-fs-wip-vshankar-testing-20241219.063429-debug-testing-default-smithi/8044506): `tasks/workunit/quota`

Yeh. I have analyzed those and they too are unrelated to this change.

**Review by mchangir — APPROVED** [review]
LGTM

**Pull request merged**
