### PR TITLE
rgw: Make sure 'target' is available before proceeding

### PR DESCRIPTION
**Pull request by badone**
Fixes: https://tracker.ceph.com/issues/47179

Signed-off-by: Brad Hubbard <bhubbard@redhat.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by badone** [comment]
Note that I've tested this resolves the tracker in the case where no 'target' argument is supplied but have not tested the situation where a 'target' argument is supplied and does, or does not, exist. I'd appreciate if someone could give me a hand with that. I have no idea why this started happening recently as none of this code seems new.

**Comment by adamemerson** [comment]
This /should/ be validated in valid validate_arg in cmdparse.cc, since the parameter is marked with req=true.

**Comment by badone** [comment]
> This /should/ be validated in valid validate_arg in cmdparse.cc, since the parameter is marked with req=true.

Seems I need to work out why it isn't then. Thanks!

**Comment by badone** [comment]
Ah, https://github.com/ceph/ceph/pull/36459 seems to have broken the validation code for these commands.

**Comment by badone** [comment]
Closing in favour of #37098

**Pull request closed without merging**
