### PR TITLE
test/libcephfs/flock.cc: fix multithread/multiprocess tests

### PR DESCRIPTION
**Pull request by ukernel**
Add synchronization point before workers execute blocking operation.
This guarantees that the main test thread not release the file lock
before workers execute the operation that supposes to block.

Fixes: #11128
Signed-off-by: Yan, Zheng <zyan@redhat.com>

### CODE REVIEW

**Comment by jcsp** [comment]
:+1: the logic makes sense to me.

Have you checked that this passes with the modification?

**Comment by ukernel** [comment]
http://pulpito.ceph.com/compare/?branch=wip-11128&suite=smoke

**Comment by jcsp** [comment]
Looks like it failed: http://qa-proxy.ceph.com/teuthology/ubuntu-2015-03-17_05:49:14-smoke-wip-11128---basic-multi/807362/teuthology.log

& is now hung

**Comment by jcsp** [comment]
...and I've killed it, as it seems unlikely the running state would have anything useful now that it advanced to the next test.

**Pull request closed without merging**
