### PR TITLE
rbd-mirror: unbreak one-way snapshot-based mirroring

### PR DESCRIPTION
**Pull request by idryomov**
Snapshot replayer needs the remote's mirror peer uuid to find its
snapshots in the remote image.  It is obtained by listing remote's
mirror peers but RemotePoolPoller::handle_mirror_peer_list() skips
tx-only (MIRROR_PEER_DIRECTION_TX) peers.  In effect only rx-tx
(MIRROR_PEER_DIRECTION_RX_TX) peers are considered for matching
and snapshot replayer always fails with "failed to retrieve mirror
peer uuid from remote pool" error.

Instead, skip rx-only (MIRROR_PEER_DIRECTION_RX) peers as we are
definitely not interested in anything having to do with mirroring
_to_ the remote cluster.

Fixes: https://tracker.ceph.com/issues/52675
Signed-off-by: Ilya Dryomov <idryomov@gmail.com>

### CODE REVIEW

**Comment by idryomov** [comment]
TODO: add a test case -- I wonder if `rbd_mirror_bootstrap.sh` would work as is with `MIRROR_POOL_MODE=image` and `MIRROR_IMAGE_MODE=journal`.

**Review by trociny — APPROVED** [review]
LGTM

**Comment by trociny** [comment]
> Need to add a test case -- I wonder if `rbd_mirror_bootstrap.sh` would work as is with `MIRROR_POOL_MODE=image` and `MIRROR_IMAGE_MODE=snapshot`.

The test "TEST: verify rx-only direction" assumes that the pool `${POOL}` is in pool mirror mode, because it does not explicitly enable mirroring after creating the image. So to make it work (for any mode) one would need to replace 
```
create_image ${CLUSTER1} ${POOL} image1
```
with
```
create_image_and_enable_mirror ${CLUSTER1} ${POOL} image1
```
Otherwise it looks like it should work.

**Comment by trociny** [comment]
I just tried locally and it worked with the modification I mentioned earlier:
```
adonis:~/ceph/ceph.ci/build% git diff                                                                                                                           
diff --git a/qa/workunits/rbd/rbd_mirror_bootstrap.sh b/qa/workunits/rbd/rbd_mirror_bootstrap.sh
index e0a096ee8a3..fb77c0d9bf8 100755
--- a/qa/workunits/rbd/rbd_mirror_bootstrap.sh
+++ b/qa/workunits/rbd/rbd_mirror_bootstrap.sh
@@ -27,7 +27,7 @@ testlog "TEST: verify rx-only direction"
 [ "$(rbd --cluster ${CLUSTER1} --pool ${POOL} mirror pool info --format xml |
        ${XMLSTARLET} sel -t -v  '//mirror/peers/peer[1]/uuid')" = "" ]
 
-create_image ${CLUSTER1} ${POOL} image1
+create_image_and_enable_mirror ${CLUSTER1} ${POOL} image1
 
 wait_for_image_replay_started ${CLUSTER2} ${POOL} image1
 write_image ${CLUSTER1} ${POOL} image1 100
diff --git a/src/tools/rbd_mirror/RemotePoolPoller.cc b/src/tools/rbd_mirror/RemotePoolPoller.cc
index 4f5994f1da6..1ff2e41fc46 100644
--- a/src/tools/rbd_mirror/RemotePoolPoller.cc
+++ b/src/tools/rbd_mirror/RemotePoolPoller.cc
@@ -183,7 +183,7 @@ void RemotePoolPoller<I>::handle_mirror_peer_list(int r) {
 
   cls::rbd::MirrorPeer* matched_peer = nullptr;
   for (auto& peer : peers) {
-    if (peer.mirror_peer_direction == cls::rbd::MIRROR_PEER_DIRECTION_TX) {
+    if (peer.mirror_peer_direction == cls::rbd::MIRROR_PEER_DIRECTION_RX) {
       continue;
     }
 
adonis:~/ceph/ceph.ci/build% RBD_MIRROR_TEMDIR=/tmp/tmp.rbd_mirror MIRROR_POOL_MODE=image MIRROR_IMAGE_MODE=snapshot ../qa/workunits/rbd/rbd_mirror_bootstrap.sh
...
+ test /tmp/tmp.rbd_mirror = /tmp/tmp.rbd_mirror
+ '[' 0 -eq 0 ']'
+ echo OK
OK
+ exit 0
```
Note, if you want to try ../qa/workunits/rbd/rbd_mirror_*.sh locally you have to add the build/bin directory to the path. And `../qa/workunits/rbd/rbd_mirror_ha.sh` is known not to work locally currently.

**Comment by idryomov** [comment]
New test case:

https://pulpito.ceph.com/dis-2021-09-24_16:19:49-rbd-wip-dis-testing-distro-basic-smithi/

The rest of rbd/mirror and rbd/mirror-thrash look good too.

**Pull request merged**
