### PR TITLE
mailmap: Jewel updates

### PR DESCRIPTION
**Pull request by theanalyst**

### CODE REVIEW

**Comment by dachary** [comment]
bash ../credits.sh tags/v10.0.0..ceph/jewel tells me 
<pre>
Number of lines added and removed, by authors
     1	 44020 Jason Dillaman <dillaman@redhat.com>
     2	 10455 Sage Weil <sweil@redhat.com>
     3	  3790 Vicente Cheng <freeze.bilsted@gmail.com>
     4	  1665 Mykola Golub <mgolub@mirantis.com>
     5	  1390 Greg Farnum <gfarnum@redhat.com>
     6	  1056 Loic Dachary <ldachary@redhat.com>
     7	   910 David Coles <dcoles@gaikai.com>
     8	   771 Rohan Mars <code@rohanmars.com>
     9	   586 John Spray <jspray@redhat.com>
    10	   449 David Zafman <dzafman@redhat.com>
    11	   381 Xinze Chi <xinze@xsky.com>
    12	   276 Xie Xingguo <xie.xingguo@zte.com.cn>
    13	   252 Piotr Dałek <piotr.dalek@ts.fujitsu.com>
    14	   249 Javier M. Mellid <jmunhoz@igalia.com>
    15	   233 MingXin Liu <mingxin.liu@kylin-cloud.com>
    16	   147 Yan, Zheng <zyan@redhat.com>
    17	   117 Radoslaw Zarzynski <rzarzynski@mirantis.com>
    18	   115 Ilya Dryomov <idryomov@redhat.com>
    19	    98 Shu, Xinxin <xinxin.shu@intel.com>
    20	    94 Joe Julian <jjulian@io.com>
    21	    92 Guang Yang <yguang@yahoo-inc.com>
    22	    88 Xiaowei Chen <chen.xiaowei@h3c.com>
    23	    68 Ma Jianpeng <jianpeng.ma@intel.com>
    24	    64 Josh Durgin <jdurgin@redhat.com>
    25	    54 Yunchuan Wen <yunchuan.wen@kylin-cloud.com>
    26	    50 Dan van der Ster <daniel.vanderster@cern.ch>
    27	    46 Jianhui Yuan <zuiwanyuan@gmail.com>
    28	    42 Nathan Cutler <ncutler@suse.com>
    29	    30 Li Wang <li.wang@kylin-cloud.com>
    30	    28 Haomai Wang <haomai@xsky.com>
    31	    26 James Page <james.page@ubuntu.com>
    32	    22 Ning Yao <yaoning@ruijie.com.cn>
    33	    18 Yuan Zhou <yuan.zhou@intel.com>
    34	    17 vasukulkarni <vasu.kulkarni@gmail.com>
    35	    16 Yehuda Sadeh <ysadehwe@redhat.com>
    36	    12 Yann Dupont <yann@objoo.org>
    37	    12 Vikhyat Umrao <vumrao@redhat.com>
    38	    11 root <rahul.1aggarwal@gmail.com>
    39	    11 brian <bjfelton@gmail.com>
    40	     9 Xiaoxi Chen <xiaoxi.chen@intel.com>
    41	     8 Jenkins <jenkins@ceph.com>
    42	     6 Kefu Chai <kchai@redhat.com>
    43	     5 Chengyuan Li <chengyli@ebay.com>
    44	     4 suckowbiz <tobias@suckow.biz>
    45	     4 Jie Wang <jie.wang@kylin-cloud.com>
    46	     3 Ren Huanwen <ren.huanwen@zte.com.cn>
    47	     3 Ji Chen <insomnia@139.com>
    48	     2 Zhi Zhang <zhangz.david@outlook.com>
    49	     2 Sangdi Xu <xu.sangdi@h3c.com>
    50	     2 Ruifeng Yang <yangruifeng.09209@h3c.com>
    51	     2 Herve Rousseau <hroussea@cern.ch>
    52	     2 Chris Holcombe <xfactor973@gmail.com>
    53	     1 Samuel Just <sjust@redhat.com>

Number of lines added and removed, by organization
     1	 58263 Red Hat <contact@redhat.com>
     2	  4573 Unaffiliated <no@organization.net>
     3	  1782 Mirantis <contact@mirantis.com>
     4	   910 David Coles <dcoles@gaikai.com>
     5	   409 XSky <contact@xsky.com>
     6	   321 Kylin Cloud <contact@kylin-cloud.com>
     7	   279 ZTE <contact@zte.com.cn>
     8	   252 Fujitsu <contact@fujitsu.com>
     9	   249 Igalia <contact@igalia.com>
    10	   193 Intel <contact@intel.com>
    11	    94 Joe Julian <jjulian@io.com>
    12	    92 Yahoo! <contact@yahoo-inc.com>
    13	    92 H3C <wentao@h3c.com>
    14	    62 Inktank <contact@inktank.com>
    15	    50 CERN <contact@cern.ch>
    16	    46 Jianhui Yuan <zuiwanyuan@gmail.com>
    17	    42 SUSE <contact@suse.com>
    18	    26 Canonical <contact@canonical.com>
    19	    22 Ruijie Networks <contact@ruijie.com.cn>
    20	    17 vasukulkarni <vasu.kulkarni@gmail.com>
    21	    11 root <rahul.1aggarwal@gmail.com>
    22	    11 brian <bjfelton@gmail.com>
    23	     5 Chengyuan Li <chengyli@ebay.com>
    24	     4 suckowbiz <tobias@suckow.biz>
    25	     3 LETV <contact@letv.com>
    26	     2 Tencent <contact@tencent.com>
    27	     2 Herve Rousseau <hroussea@cern.ch>
    28	     2 Chris Holcombe <xfactor973@gmail.com>

Commits, by authors
     1	    121 Jason Dillaman <dillaman@redhat.com>
     2	    106 Sage Weil <sweil@redhat.com>
     3	     20 Vicente Cheng <freeze.bilsted@gmail.com>
     4	     18 Mykola Golub <mgolub@mirantis.com>
     5	     13 Loic Dachary <ldachary@redhat.com>
     6	     11 John Spray <jspray@redhat.com>
     7	     11 Greg Farnum <gfarnum@redhat.com>
     8	     10 Yan, Zheng <zyan@redhat.com>
     9	     10 David Zafman <dzafman@redhat.com>
    10	      9 Xie Xingguo <xie.xingguo@zte.com.cn>
    11	      9 Rohan Mars <code@rohanmars.com>
    12	      9 Piotr Dałek <piotr.dalek@ts.fujitsu.com>
    13	      9 Ilya Dryomov <idryomov@redhat.com>
    14	      8 Josh Durgin <jdurgin@redhat.com>
    15	      7 David Coles <dcoles@gaikai.com>
    16	      6 Li Wang <li.wang@kylin-cloud.com>
    17	      5 Xinze Chi <xinze@xsky.com>
    18	      5 Radoslaw Zarzynski <rzarzynski@mirantis.com>
    19	      5 MingXin Liu <mingxin.liu@kylin-cloud.com>
    20	      5 Ma Jianpeng <jianpeng.ma@intel.com>
    21	      5 Javier M. Mellid <jmunhoz@igalia.com>
    22	      4 Yann Dupont <yann@objoo.org>
    23	      4 Haomai Wang <haomai@xsky.com>
    24	      3 Nathan Cutler <ncutler@suse.com>
    25	      3 Joe Julian <jjulian@io.com>
    26	      2 Yunchuan Wen <yunchuan.wen@kylin-cloud.com>
    27	      2 Yehuda Sadeh <ysadehwe@redhat.com>
    28	      2 Xiaowei Chen <chen.xiaowei@h3c.com>
    29	      2 Shu, Xinxin <xinxin.shu@intel.com>
    30	      2 Ning Yao <yaoning@ruijie.com.cn>
    31	      2 Ji Chen <insomnia@139.com>
    32	      2 Guang Yang <yguang@yahoo-inc.com>
    33	      2 Dan van der Ster <daniel.vanderster@cern.ch>
    34	      1 Zhi Zhang <zhangz.david@outlook.com>
    35	      1 Yuan Zhou <yuan.zhou@intel.com>
    36	      1 Xiaoxi Chen <xiaoxi.chen@intel.com>
    37	      1 Vikhyat Umrao <vumrao@redhat.com>
    38	      1 vasukulkarni <vasu.kulkarni@gmail.com>
    39	      1 suckowbiz <tobias@suckow.biz>
    40	      1 Sangdi Xu <xu.sangdi@h3c.com>
    41	      1 Samuel Just <sjust@redhat.com>
    42	      1 Ruifeng Yang <yangruifeng.09209@h3c.com>
    43	      1 root <rahul.1aggarwal@gmail.com>
    44	      1 Ren Huanwen <ren.huanwen@zte.com.cn>
    45	      1 Kefu Chai <kchai@redhat.com>
    46	      1 Jie Wang <jie.wang@kylin-cloud.com>
    47	      1 Jianhui Yuan <zuiwanyuan@gmail.com>
    48	      1 Jenkins <jenkins@ceph.com>
    49	      1 James Page <james.page@ubuntu.com>
    50	      1 Herve Rousseau <hroussea@cern.ch>
    51	      1 Chris Holcombe <xfactor973@gmail.com>
    52	      1 Chengyuan Li <chengyli@ebay.com>
    53	      1 brian <bjfelton@gmail.com>

Commits, by organizations
     1	    303 Red Hat <contact@redhat.com>
     2	     33 Unaffiliated <no@organization.net>
     3	     23 Mirantis <contact@mirantis.com>
     4	     14 Kylin Cloud <contact@kylin-cloud.com>
     5	     10 ZTE <contact@zte.com.cn>
     6	      9 XSky <contact@xsky.com>
     7	      9 Intel <contact@intel.com>
     8	      9 Fujitsu <contact@fujitsu.com>
     9	      7 David Coles <dcoles@gaikai.com>
    10	      5 Igalia <contact@igalia.com>
    11	      4 H3C <wentao@h3c.com>
    12	      3 SUSE <contact@suse.com>
    13	      3 Joe Julian <jjulian@io.com>
    14	      2 Yahoo! <contact@yahoo-inc.com>
    15	      2 Ruijie Networks <contact@ruijie.com.cn>
    16	      2 LETV <contact@letv.com>
    17	      2 Inktank <contact@inktank.com>
    18	      2 CERN <contact@cern.ch>
    19	      1 vasukulkarni <vasu.kulkarni@gmail.com>
    20	      1 Tencent <contact@tencent.com>
    21	      1 suckowbiz <tobias@suckow.biz>
    22	      1 root <rahul.1aggarwal@gmail.com>
    23	      1 Jianhui Yuan <zuiwanyuan@gmail.com>
    24	      1 Herve Rousseau <hroussea@cern.ch>
    25	      1 Chris Holcombe <xfactor973@gmail.com>
    26	      1 Chengyuan Li <chengyli@ebay.com>
    27	      1 Canonical <contact@canonical.com>
    28	      1 brian <bjfelton@gmail.com>

Reviews, by authors (one review spans multiple commits)
     1	     18 Kefu Chai <kchai@redhat.com>
     2	     17 Josh Durgin <jdurgin@redhat.com>
     3	     15 Sage Weil <sweil@redhat.com>
     4	     14 Loic Dachary <ldachary@redhat.com>
     5	      9 Jason Dillaman <dillaman@redhat.com>
     6	      8 Li Wang <li.wang@kylin-cloud.com>
     7	      6 Yehuda Sadeh <ysadehwe@redhat.com>
     8	      4 John Spray <jspray@redhat.com>
     9	      4 David Zafman <dzafman@redhat.com>
    10	      3 Samuel Just <sjust@redhat.com>
    11	      3 Joao Eduardo Luis <joao@suse.de>
    12	      3 Haomai Wang <haomai@xsky.com>
    13	      2 Piotr Dałek <piotr.dalek@ts.fujitsu.com>
    14	      2 Nathan Cutler <ncutler@suse.com>
    15	      2 Ken Dreyer <kdreyer@redhat.com>
    16	      2 Guang Yang <yguang@yahoo-inc.com>
    17	      2 Greg Farnum <gfarnum@redhat.com>
    18	      1 Yan, Zheng <zyan@redhat.com>
    19	      1 Sebastien Ponce <sebastien.ponce@cern.ch>
    20	      1 David Coles <dcoles@gaikai.com>
    21	      1 Boris Ranto <branto@redhat.com>

Reviews, by organizations (one review spans multiple commits)
     1	     96 Red Hat <contact@redhat.com>
     2	      8 Kylin Cloud <contact@kylin-cloud.com>
     3	      5 SUSE <contact@suse.com>
     4	      3 XSky <contact@xsky.com>
     5	      2 Yahoo! <contact@yahoo-inc.com>
     6	      2 Fujitsu <contact@fujitsu.com>
     7	      1 David Coles <dcoles@gaikai.com>
     8	      1 CERN <contact@cern.ch>
</pre>
Which still shows a few missing

* David Coles <dcoles@gaikai.com>
* Joe Julian <jjulian@io.com>
* Jianhui Yuan <zuiwanyuan@gmail.com>
* vasukulkarni <vasu.kulkarni@gmail.com>
* brian <bjfelton@gmail.com>
* suckowbiz <tobias@suckow.biz>
* Herve Rousseau <hroussea@cern.ch>
* Chris Holcombe <xfactor973@gmail.com>

**Comment by smithfarm** [comment]
@dachary What about "root"? (Fortunately, he wasn't too prolific this time around. . .)

**Comment by dachary** [comment]
@smithfarm he fortunately has a distinctive email : rahul.1aggarwal@gmail.com

**Comment by theanalyst** [comment]
ah I think I did the credits.sh against 10.0.0 to v9.2.0, I guess the authors that've appeared are after the 10.0.0 release

**Comment by dachary** [comment]
@theanalyst yeah :-)

**Comment by dachary** [comment]
@theanalyst I should have checked against 10.0.0, sorry about that. All good then :-) Could you please rebase ? Assuming the mails were sent to the authors 6 days ago when you submitted the pull request, it should be good to merge early this week.

**Comment by theanalyst** [comment]
sure will do a rebase

**Comment by theanalyst** [comment]
rebased

**Pull request merged**
