### PR TITLE
rbd-mirror: bootstrap needs to handle local image id collision

### PR DESCRIPTION
**Pull request by dillaman**

### CODE REVIEW

**Comment by trociny** [comment]
@dillaman see http://qa-proxy.ceph.com/teuthology/trociny-2018-05-17_15:18:40-rbd-wip-mgolub-testing-distro-basic-smithi/2544199/teuthology.log
```
2018-05-17T18:15:16.699 INFO:tasks.rbd_mirror.cluster2.client.mirror.3.smithi145.stderr:2018-05-17 18:15:16.649 7fc33affd700 -1 rbd::mirror::image_replayer::CreateImageRequest: 0x7fc29810ec90 handle_create_image: failed to create local image: (17) File exists
2018-05-17T18:15:16.700 INFO:tasks.rbd_mirror.cluster2.client.mirror.3.smithi145.stderr:2018-05-17 18:15:16.649 7fc33affd700 -1 rbd::mirror::image_replayer::BootstrapRequest: 0x7fc358206ab0 handle_create_local_image: failed to create local image: (17) File exists
2018-05-17T18:15:16.712 INFO:tasks.rbd_mirror.cluster2.client.mirror.3.smithi145.stderr:2018-05-17 18:15:16.662 7fc376720700 -1 rbd::mirror::ImageReplayer: 0x7fc358037bc0 [2/1e745b15-43a2-45dd-b861-dcd17f723d49] operator(): start failed: (17) File exists
2018-05-17T18:15:16.741 INFO:tasks.rbd_mirror.cluster2.client.mirror.3.smithi145.stderr:2018-05-17 18:15:16.691 7fc33affd700 -1 rbd::mirror::image_replayer::CreateImageRequest: 0x7fc2980147d0 handle_create_image: failed to create local image: (17) File exists
2018-05-17T18:15:16.741 INFO:tasks.rbd_mirror.cluster2.client.mirror.3.smithi145.stderr:2018-05-17 18:15:16.691 7fc33affd700 -1 rbd::mirror::image_replayer::BootstrapRequest: 0x7fc358026540 handle_create_local_image: failed to create local image: (17) File exists
2018-05-17T18:15:16.743 INFO:tasks.rbd_mirror.cluster2.client.mirror.3.smithi145.stderr:2018-05-17 18:15:16.693 7fc33affd700 -1 rbd::mirror::image_replayer::CreateImageRequest: 0x7fc29835db20 handle_create_image: failed to create local image: (17) File exists
...
```
The image create fails due to image id object already exists:
```
2018-05-17 18:15:46.703 7fc33affd700 -1 librbd::image::CreateRequest: 0x7fc298208710 handle_create_id_object: error creating RBD id object: (17) File exists
```
I thought the scenario had been: 
1) `image::CreateRequest` fails due to "image id already in-use" and leave object id
2) the following `image::CreateRequest` fails due to object id exists

But in this case I should see at least one "already in-use" message in rbd-mirror logs while grep returns nothing.

**Comment by trociny** [comment]
Ah, the 'File exists' errors were preceding with "blacklisted" errors:
```
2018-05-17T18:07:23.363 INFO:tasks.rbd_mirror.cluster2.client.mirror.2.smithi145.stderr:2018-05-17 18:07:23.339 7fa60cff9700 -1 rbd::mirror::image_replayer::CreateImageRequest: 0x7fa5742a1d40 handle_create_image: failed to create local image: (108) Cannot send after transport endpoint shutdown
```
So could it be, that it was blacklisted at the moment when creating an image, and as a result it left the id object?

Also it crashed here:
```
/BUILD/ceph-13.1.0-418-g78a0aab/src/librbd/image/CreateRequest.cc: 872: FAILED assert(r == 0)
2018-05-17T18:07:23.364 INFO:tasks.rbd_mirror.cluster2.client.mirror.2.smithi145.stderr: ceph version 13.1.0-418-g78a0aab (78a0aab70772d2ea3d5f031eb18b7ea7938b8711) nautilus (dev)
2018-05-17T18:07:23.364 INFO:tasks.rbd_mirror.cluster2.client.mirror.2.smithi145.stderr: 1: (ceph::__ceph_assert_fail(char const*, char const*, int, char const*)+0xff) [0x7fa651fc148f]
2018-05-17T18:07:23.364 INFO:tasks.rbd_mirror.cluster2.client.mirror.2.smithi145.stderr: 2: (()+0x286677) [0x7fa651fc1677]
2018-05-17T18:07:23.364 INFO:tasks.rbd_mirror.cluster2.client.mirror.2.smithi145.stderr: 3: (librbd::image::CreateRequest<librbd::ImageCtx>::remove_from_dir()+0x207) [0x55d88abe8287]
2018-05-17T18:07:23.364 INFO:tasks.rbd_mirror.cluster2.client.mirror.2.smithi145.stderr: 4: (librbd::image::CreateRequest<librbd::ImageCtx>::handle_create_image(int)+0x163) [0x55d88abe8433]
2018-05-17T18:07:23.364 INFO:tasks.rbd_mirror.cluster2.client.mirror.2.smithi145.stderr: 5: (librados::C_AioComplete::finish(int)+0x22) [0x7fa65aa277d2]
2018-05-17T18:07:23.364 INFO:tasks.rbd_mirror.cluster2.client.mirror.2.smithi145.stderr: 6: (Context::complete(int)+0x9) [0x55d88aa3f909]
2018-05-17T18:07:23.364 INFO:tasks.rbd_mirror.cluster2.client.mirror.2.smithi145.stderr: 7: (Finisher::finisher_thread_entry()+0x12e) [0x7fa651fbfa0e]
2018-05-17T18:07:23.364 INFO:tasks.rbd_mirror.cluster2.client.mirror.2.smithi145.stderr: 8: (()+0x7dd5) [0x7fa6508cfdd5]
2018-05-17T18:07:23.365 INFO:tasks.rbd_mirror.cluster2.client.mirror.2.smithi145.stderr: 9: (clone()+0x6d) [0x7fa64f38ab3d]
```

**Comment by dillaman** [comment]
@trociny I'm still investigating the flow, but in the meantime, I have appended an unrelated commit to fix the crash you witnessed.

**Comment by dillaman** [comment]
http://pulpito.ceph.com/jdillaman-2018-09-25_17:12:57-rbd-wip-rbd-mirror-distro-basic-smithi/

**Comment by dillaman** [comment]
http://pulpito.ceph.com/jdillaman-2018-09-25_22:06:18-rbd-wip-rbd-mirror-distro-basic-smithi/

**Comment by dillaman** [comment]
@trociny I picked this back up last week and have fixed the original issue (plus a few others). I tested this in combination with 24276 and 24253.

**Pull request merged**
