### PR TITLE
mimic: mgr/dashboard: Update npm packages

### PR DESCRIPTION
**Pull request by tspmelo**
Fix some npm packages vulnerabilities.

Fixes: http://tracker.ceph.com/issues/39080

`Signed-off-by: Tiago Melo <tmelo@suse.com>`

- [ ] Vulnerability fix in `karma`
- [ ] Manual test

### CODE REVIEW

**Comment by tspmelo** [comment]
jenkins retest this please

**Comment by callithea** [comment]
jenkins test dashboard

**Comment by tspmelo** [comment]
I updated the commit messages with the reference to the tracker issue.

**Comment by yuriw** [comment]
[wip-yuri2-testing-2019-04-08-2038-mimic](https://trello.com/c/78iDtIkR/584-wip-yuri2-testing-2019-04-08-2038-mimic)

**Comment by yuriw** [comment]
[wip-yuri2-testing-2019-04-09-1657-mimic](https://trello.com/c/hF3iVrdE/587-wip-yuri2-testing-2019-04-09-1657-mimic)

**Comment by yuriw** [comment]
@tspmelo this PR seem to be breaking build 
Pls take a look add add back tags when ready 

This is built only with this PR on top of mimic
https://shaman.ceph.com/builds/ceph/wip_yuriw_mimic_PR26670/

**Comment by tspmelo** [comment]
Only had a quick look at the logs yesterday, today they were already gone.
The problem was related to the version of npm, which needs to be a higher version than the one that was being used in shaman.
Strange that it is working in make check but failed in shaman.

I have updated the node version to the same we use in master, hopefully it will work now.

**Comment by callithea** [comment]
jenkins test dashboard

**Comment by tspmelo** [comment]
jenkins test dashboard

**Comment by smithfarm** [comment]
The tracker has a nice explanation of why these commits can't be cherry-picked: "We need to manually update the npm packages in mimic. It's not possible to do a backport since we don't use the same packages anymore."

However, that explanation will not be visible to anyone reading the git history and wondering why these are not cherry-picks. Could we get the explanation in the commit messages themselves, please?

**Comment by tspmelo** [comment]
@smithfarm Done.

**Comment by tspmelo** [comment]
jenkins test dashboard

**Comment by tspmelo** [comment]
jenkins test dashboard

**Comment by tchaikov** [comment]
jenkins test dashboard

**Comment by yuriw** [comment]
[wip-yuri3-testing-2019-04-29-1935-mimic](https://trello.com/c/1OdZ5zIb/598-wip-yuri3-testing-2019-04-29-1935-mimic)

**Comment by yuriw** [comment]
[wip-yuri4-testing-2019-04-30-1543-mimic](https://trello.com/c/A2lSYsdc/600-wip-yuri4-testing-2019-04-30-1543-mimic)

**Comment by yuriw** [comment]
[wip-yuri4-testing-2019-04-30-1620-mimic](https://trello.com/c/A2lSYsdc/600-wip-yuri4-testing-2019-04-30-1620-mimic)

**Comment by yuriw** [comment]
@tspmelo @smithfarm I still can't built this.
wip-yuri5-testing-2019-04-30-1634-mimic has only this PR on the top of the tip and is failing => https://shaman.ceph.com/builds/ceph/wip-yuri5-testing-2019-04-30-1634-mimic/

**Comment by tspmelo** [comment]
@yuriw sorry about this.

Last time I was not able to check the logs, since they were gone in the morning, and was not able to figure out why this was working in make check and failing in shaman.

After a look a the logs and a quick search of mimic code I found out that although I had fixed the problem in `CMakeLists.txt`, I forgot to fix it in `make-dist` script.

I have updated `make-dist` and hopefully it will work on all envs now.

**Comment by yuriw** [comment]
@tspmelo cool I will test

**Comment by yuriw** [comment]
@tspmelo looks good now!  will batch it up with other PRs and run thru suites

**Comment by yuriw** [comment]
[wip-yuri5-testing-2019-04-30-2026-mimic](https://trello.com/c/9KYPzFev/602-wip-yuri5-testing-2019-04-30-2026-mimic)

**Pull request merged**
