### PR TITLE
rpm: use %elseif whenever appropriate

### PR DESCRIPTION
**Pull request by tchaikov**
it's more symmetric this way, and easier to read.

Signed-off-by: Kefu Chai <kchai@redhat.com>

### CODE REVIEW

**Comment by smithfarm** [comment]
Note: the OBS spec file parser does not currently understand `%elseif` so this PR is blocked until I can get that fixed.

**Comment by smithfarm** [comment]
@tchaikov Where are you seeing that there is an `%elseif` in RPM? Can you point to code or documentation?

**Comment by tchaikov** [comment]
@smithfarm https://build.opensuse.org/package/view_file/devel:tools/rpmdevtools/rpmdevtools.spec?rev=4 , but it does not exist in the doc on rpm.org. is it a non-standard extension or something?

**Comment by smithfarm** [comment]
@tchaikov That's an old version of the rpmdevtools spec file. The most recent version is https://build.opensuse.org/package/view_file/devel:tools/rpmdevtools/rpmdevtools.spec?expand=1 and it does not include `%elseif`.

My colleagues are telling me that RPM does not have such a macro.

It is possible to do "%if \n %else" though (but it sure would be nice if we didn't do that . . . .)

**Comment by tchaikov** [comment]
@smithfarm thanks for confirming it. closing this PR then. sorry for the trouble.

**Pull request closed without merging**
