### PR TITLE
rgw/rest: add 'zero' rest api

### PR DESCRIPTION
**Pull request by cbodley**
when 'zero' is included in rgw_enable_apis, a /zero endpoint is added. all paths under /zero refer to a single resource that supports the following operations:

PUT requests discard the request body and update the content length
GET requests return a response body full of zeroes
HEAD requests return the current content length
DELETE requests reset the content length to 0

none of these operations require any authentication or i/o, so can be used to benchmark the http frontend in isolation

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by cbodley** [comment]
@mattbenjamin @mkogan1 this is the same idea as the "h3_zero" example from https://github.com/ceph/ceph/pull/48178, but can be used for any rgw frontend

**Review by mattbenjamin — COMMENTED** [review]
this looks really cool, amazing work minimizing this idea

**Comment by mkogan1** [comment]
@cbodley attempted to test with https://github.com/markhpc/hsbench#usage , it has a `-bp zero` switch that denotes bucket prefix, but it is adding `000000000000` to the `zero` prefix :
ex from rgw log:
`2023-03-14T16:27:33.750+0000 7fffb552b700  1 beast: 0x7fffafb1b940: 127.0.0.1 - cosbench [14/Mar/2023:16:27:33.711 +0000] "PUT /zero000000000000/stage01_000000099931 HTTP/1.1" 200 4096 - "aws-sdk-go/1.40.2 (go1.16.5; linux; amd64)" - latency=0.039000779s`
attempted to change 
```
    if (apis_map.count("zero")) {
      rest.register_resource("zero", new rgw::RESTMgr_Zero());
```
to `"zero000000000000"` but yet it doesn't seem to hook the hsbench PUTs, any advice how to debug?

**Comment by cbodley** [comment]
maybe you can add the path to the url, like `-u http://127.0.0.1:7480/zero`? then i'd expect it to issue requests under the path `/zero/hotsauce_bench000000000000/`

**Comment by cbodley** [comment]
another option is to set a `prefix` in the `rgw_frontends` config so that /zero is added to the front of every incoming request. i tried `prefix=zero` initially and wasn't able to make it work, but i'll see if i can figure that out

**Comment by cbodley** [comment]
with this radosgw configuration: `--rgw_frontends="beast port=8000 prefix=/zero" --rgw-enable-apis zero`

a curl command at the root: `curl http://localhost:8000`

results in `:zero_get executing`

**Comment by mkogan1** [comment]
> with this radosgw configuration: `--rgw_frontends="beast port=8000 prefix=/zero" --rgw-enable-apis zero`

thank you very much, works - no I/O utilization in `iostat` during test runs.

performance on reference test machine of hsbench 4KB obj PUT test:
`time nice numactl -N 1 -m 1 -- ~/go/bin/hsbench -a b2345678901234567890 -s b234567890123456789012345678901234567890 -u http://127.0.0.1:8000 -z 4K -d -1 -t $(( $(numactl -N 0 -- nproc) / 1 )) -b 1 -n 100000 -m p -bp zero -op stage01`

increased to `17797`  IO/s
`2023/03/14 18:11:00 Loop: 0, Int: TOTAL, Dur(s): 5.6, Mode: PUT, Ops: 100000, MB/s: 69.52, IO/s: 17797 ...`

from `12784`  IO/s without (backing storage being optane nvme, on slower storage device would have shown larger delta)
`2023/03/14 15:54:37 Loop: 0, Int: TOTAL, Dur(s): 7.8, Mode: PUT, Ops: 100000, MB/s: 49.94, IO/s: 12784 ...`

**Comment by markhpc** [comment]
@cbodley @mkogan1 this is awesome work guys!  Really excited to see your results!

**Comment by cbodley** [comment]
passed qa in https://pulpito.ceph.com/cbodley-2023-04-26_00:39:50-rgw-wip-cbodley2-testing-distro-default-smithi/

still needs an approval

**Comment by cbodley** [comment]
> still needs an approval

ping @mkogan1 @mattbenjamin

**Review by dang — APPROVED** [review]

**Review by mattbenjamin — APPROVED** [review]
sorry, looks great to me

**Comment by cbodley** [comment]
thanks!

**Comment by mkogan1** [comment]
@cbodley hi, thought it may interest you, there is a specific workload of an internal CU that specified single-part PUTs of 8MiB objects using specific elbencho params -
it achieves **97.9 Gbps** with the zero endpoint !!!


```
❯ radosgw ... --rgw_frontends="beast port=8000 request_timeout_ms=0 tcp_nodelay=1 prefix=/zero" --rgw-enable-apis zero ...

❯ time (nice /usr/local/bin/elbencho --s3endpoints http://localhost:8000/ --s3key b2345678901234567890 --s3secret b234567890123456789012345678901234567890 -w -t 400 -n 10 -N 25 -s 8m -b 8m --s3fastput --mkdirs mybucket1)
OPERATION   RESULT TYPE         FIRST DONE   LAST DONE
=========== ================    ==========   =========
MKBUCKETS   Elapsed time     :         4ms         4ms
            Buckets/s        :         236         236
            Buckets total    :           1           1
---
WRITE       Elapsed time     :    1m3.512s    1m8.905s
            Objects/s        :        1453        1451
            Throughput MiB/s :       11670       11610
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
            Total MiB        :      741226      800000
            Objects total    :       92338      100000
```
image

**Pull request merged**
