### PR TITLE
qa/mgr/dashboard: add extra wait to test

### PR DESCRIPTION
**Pull request by epuertat**
Fixes: https://tracker.ceph.com/issues/49344
Signed-off-by: Ernesto Puerta <epuertat@redhat.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Review by alfonsomthd — APPROVED** [review]

**Review by ideepika — APPROVED** [review]

**Comment by epuertat** [comment]
jenkins test signed

**Comment by ideepika** [comment]
jenkins retest this please

**Comment by epuertat** [comment]
jenkins test dashboard

**Review by nizamial09 — APPROVED** [review]

**Comment by nizamial09** [comment]
jenkins test dashboard

**Pull request merged**
