### PR TITLE
rgw: using get_val instead of deprecated method

### PR DESCRIPTION
**Pull request by albIN7**
Signed-off-by: Albin Antony <aantony@redhat.com>

- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by albIN7** [comment]
@adamemerson Please review

**Comment by adamemerson** [comment]
Jenkins, retest this please.

**Comment by adamemerson** [comment]
The main focus here isn't moving from one API to the other, the most important thing is focusing on addressing the variables that are hanging around long-term and not being updated when the configuration changes.

**Comment by albIN7** [comment]
jenkins retest this please

**Comment by albIN7** [comment]
> This should also remove the corresponding option from `src/common/legacy_config_opts.h`.

Updated

**Comment by albIN7** [comment]
jenkins retest this please

**Comment by albIN7** [comment]
@adamemerson I am closing this pr as I messed up this branch. I will send a new pr with my latest commits(variables using obeserver api)

**Comment by adamemerson** [comment]
For future reference, you can always reset and/or rebase and then force push.

You might want to browse through https://git-scm.com/book/en/v2 sometime

**Pull request closed without merging**
