### PR TITLE
mgr: clean up fsstatus module

### PR DESCRIPTION
**Pull request by jcsp**

### CODE REVIEW

**Comment by liewegas** [comment]
Can you add a note to the doc/release-notes.rst section enumerating new CLI commands?

**Comment by jcsp** [comment]
Updated PendingReleaseNotes, and also switched on the module by default (otherwise people were not going to be able to actually run the commands without customizing their config)

**Comment by liewegas** [comment]
We should add this to qa/workunits/cephtool/test.sh too then?

**Comment by jcsp** [comment]
Added it to the test

**Comment by tchaikov** [comment]
- http://pulpito.ceph.com/kchai-2017-06-28_07:28:49-rados-wip-kefu-testing-distro-basic-smithi/
- http://pulpito.ceph.com/kchai-2017-06-29_03:07:53-rados-wip-kefu-testing-distro-basic-smithi/

**Pull request merged**
