### PR TITLE
.github: Run cephadm tox tests when necessary

### PR DESCRIPTION
**Pull request by zmc**
This can easily be extended for our other Python components.

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [x] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by zmc** [comment]
This took a few tries to get right, but here is:
[tox tests running when a cephadm python file had changes](https://github.com/ceph/ceph/runs/6869816054?check_suite_focus=true)
[tox tests being skipped because of no cephadm python changes](https://github.com/ceph/ceph/runs/6869853456?check_suite_focus=true)

**Comment by zmc** [comment]
jenkins test make check

**Comment by adk3798** [comment]
@zmc once merged, for any PRs not modifying cephadm files, will the test still show up and say they were skipped or will they not show up at all?

**Comment by zmc** [comment]
@adk3798 I filed this to check: https://github.com/zmc/ceph/pull/1, and here's a screenshot:

Screen Shot 2022-06-21 at 17 57 39

**Comment by adk3798** [comment]
> @adk3798 I filed this to check: [zmc#1](https://github.com/zmc/ceph/pull/1), and here's a screenshot:
> 
> Screen Shot 2022-06-21 at 17 57 39

@zmc is there anyway to have it just not pop up at all if it's not needed? That's how it works for a lot of the other optional github checks (e.g. all the ceph-volume tests). Especially if we're thinking of extending this to more python modules (which there are quite a few of) we don't really want to have it list out a whole bunch of skipped checks on every PR if it's avoidable.

**Comment by zmc** [comment]
@adk3798 Sadly it looks like hiding skipped tasks isn't possible, based on [this forum post](https://github.community/t/hide-pr-checks-for-skipped-jobs/124881/7). If the UI would e.g. group jobs from the same workflow inside an expandable element, it'd be better. But I can see how we may not want this change given that lack of flexibility.

**Comment by adk3798** [comment]
> @adk3798 Sadly it looks like hiding skipped tasks isn't possible, based on [this forum post](https://github.community/t/hide-pr-checks-for-skipped-jobs/124881/7). If the UI would e.g. group jobs from the same workflow inside an expandable element, it'd be better. But I can see how we may not want this change given that lack of flexibility.

@zmc that's unfortunate. Maybe we should get some input from some other devs with who know the infra and CI better than me. I'm not really sure what the best way forward is.

**Pull request closed without merging**
