### PR TITLE
msg/async/rdma: fix rx_cq as tx_cq passing to qp attr

### PR DESCRIPTION
**Pull request by yuyuyu101**
It will cause polling incorrect work queue notification

Signed-off-by: Haomai Wang <haomai@xsky.com>

### CODE REVIEW

**Comment by yuyuyu101** [comment]
@Adirl plz give a look at this... I don't know why this stupid problem not causing problem tilll now...

**Comment by Adirl** [comment]
how did you discover this? debug?

**Comment by Adirl** [comment]
seems like we never create completion_queue tx_cq and we use rx_cq for both
in RDMADispatcher::RDMADispatcher
`    rx_cq = ib->create_comp_queue(c, rx_cc);
`
grepping the code  i couldn't find one for tx
```
grep create_comp_queue  src/msg/async/rdma/
src/msg/async/rdma/Infiniband.cc:Infiniband::CompletionQueue* Infiniband::create_comp_queue(
src/msg/async/rdma/Infiniband.h:  CompletionQueue *create_comp_queue(CephContext *c, CompletionChannel *cc=NULL);
src/msg/async/rdma/RDMAStack.h:    rx_cq = ib->create_comp_queue(c, rx_cc);

```

maybe this is allowed and hence no issue, let me check. 

@saritz, @danielbo

**Comment by Adirl** [comment]
using same cq for rx and tx is allowed

**Comment by Adirl** [comment]
allowed... as long as CQ handler is arranged to handle both TX and RX completions…

**Comment by yuyuyu101** [comment]
YES, the orignal codes are OK

**Pull request closed without merging**
