### PR TITLE
osd/PG: handle flushed event directly

### PR DESCRIPTION
**Pull request by wumingqiao**
same logic as before, but avoid queueing and thread switching

Signed-off-by: wumingqiao <wumingqiao@inspur.com>

### CODE REVIEW

**Comment by tchaikov** [comment]
per sage,

> Ok, I'd like to keep this in testing limbo for several runs.  In particular, I'd like to combine it with https://github.com/ceph/ceph/pull/18752 .  The flush evt behavior dates back to 2012 so I'm a bit paranoid :)

that's why this PR is labeled with DNM and needs-qa.

**Comment by wumingqiao** [comment]
I understand, and this pr is more or less insignificant

**Comment by tchaikov** [comment]
@wumingqiao i was simply copying the message to help other reviewers. i think the reason Sage holds your PR is not that it's insignificant, but just "Better To Be Sure Than Sorry".

**Comment by tchaikov** [comment]
- http://pulpito.ceph.com/kchai-2017-12-14_08:53:42-rados-wip-kefu-testing-2017-12-14-1157-distro-basic-mira/
- http://pulpito.ceph.com/kchai-2017-12-15_06:17:13-rados-wip-kefu-testing-2017-12-14-1157-distro-basic-mira/

**Comment by tchaikov** [comment]
- http://pulpito.ceph.com/kchai-2017-12-15_11:03:39-rados-wip-kefu-testing-2017-12-15-1528-distro-basic-mira/
- http://pulpito.ceph.com/kchai-2017-12-16_03:28:12-rados-wip-kefu-testing-2017-12-15-1528-distro-basic-mira/

**Comment by tchaikov** [comment]
- http://pulpito.ceph.com/kchai-2018-01-08_13:52:40-rados-wip-kefu-testing-2018-01-08-1914-distro-basic-mira/
- http://pulpito.ceph.com/kchai-2018-01-09_13:55:16-rados-wip-kefu-testing-2018-01-09-1600-distro-basic-mira/

**Comment by tchaikov** [comment]
@liewegas is this change good to merge?

**Comment by liewegas** [comment]
Thanks!

**Pull request merged**
