### PR TITLE
Rados notify

### PR DESCRIPTION
**Pull request by majianpeng**

### CODE REVIEW

**Comment by majianpeng** [comment]
@liewegas . Base on your pull request #3663.  rados watch & don't work. Now i fix it . (i don;t know how to remove your commit), if you have any question, only pick my commit. 
Thanks!

**Comment by majianpeng** [comment]
@liewegas . Later find this bug exist in rbd cli.

**Comment by liewegas** [comment]
I'm confused about what this is fixing.  If you hit enter you get a clean shutdown, and (on my machines at least) if you hit control-C it exits immediately without cleaning up.

**Comment by majianpeng** [comment]
I register SIGINT handle which make pause to return so it can do cleanup work like unmatch2.

**Comment by liewegas** [comment]
> I register SIGINT handle which make pause to return so it can do cleanup work like unmatch2.

Oh, I see.  I think it's *good* though that control-c exits without 
cleaning up.  It's useful for testing, and ultimately that's what this 
command is there for..

**Comment by majianpeng** [comment]
By the way, in background exec and set timeout of notify to 30sec, it don't return timeout. 
This is because Watch::remove cause. I think in this case  for notify it should return CEPH_WATCH_EVENT_DISCONNECT not CEPH_WATCH_EVENT_NOTIFY_COMPLETE.

**Comment by majianpeng** [comment]
Sorry i misunderstand the code in Notify::maybe_complete_notify:
  if (timed_out)
      reply->return_code = -ETIMEDOUT;
In this case, the return_code is zero. But i think we can set err to tell notify. But i don't know which err is correctly?  Or notify don't care this?

**Comment by liewegas** [comment]
Sorry, I don't understand.  If timed_out==true then we return ETIMEDOUT.  Can you explain how to produce the scenario in more detail? Thanks!

**Comment by majianpeng** [comment]
For notify command, 
a: if no watch, return sucess
b: if timeout, return timeout
c: in this case(client disconnect), remove the watch cause reply notify with success.
d: watch send ack to notify.
If return success, we don't know which case a/c/d? Or for notify it don't need to know?

**Comment by liewegas** [comment]
I think we don't need to know.  As long as everyone who had a valid watch (even if that is 0 people) got the notify that is success.  Or, put another way, notify success means there does not exist a client with a valid watch that didn't receive the notify.

**Pull request closed without merging**
