### PR TITLE
luminous: tests: fix transient failures in test_pidfile.sh

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/21050

### CODE REVIEW

**Comment by smithfarm** [comment]
@dzafman OK, done.

**Comment by smithfarm** [comment]
Hmmm `Test failures: 4 - test_pidfile.sh (Failed)`

**Comment by liewegas** [comment]
http://pulpito.ceph.com/sage-2017-08-23_20:25:11-rados-wip-sage-testing-luminous-20170823a-distro-basic-smithi/

**Comment by dzafman** [comment]
It failed again even with the sleep 5.  I guess we could just disable this in luminous for now.

**Comment by liewegas** [comment]
Yeah

**Pull request closed without merging**
