### PR TITLE
kraken: ceph-disk: does not support cluster names different than 'ceph'

### PR DESCRIPTION
**Pull request by shinobu-x**
http://tracker.ceph.com/issues/18973

### CODE REVIEW

**Comment by dachary** [comment]
you'll need https://github.com/ceph/ceph/pull/13566 as well, as soon as it's merged

**Comment by shinobu-x** [comment]
@dachary Please check

$ git cherry-pick -x 7f66672

`error: could not apply 7f66672... ceph-disk: dmcrypt activate must use the same cluster as prepare`

$ git status
```
# On branch wip-17821-kraken
snip
#	both modified:      src/ceph-disk/ceph_disk/main.py
```
```
<<<<<<< HEAD
        self.create_key()
=======
        if self.args.cluster_uuid is None:
            self.args.cluster_uuid = get_fsid(cluster=self.args.cluster)
        write_one_line(path, 'ceph_fsid', self.args.cluster_uuid)
        self.create_key(self.args.cluster)
>>>>>>> 7f66672...
```
$ git diff 16fc6d8 a88b267 src/ceph-disk/ceph_disk/main.py
```
snip
-        self.create_key()
+        if self.args.cluster_uuid is None:
+            self.args.cluster_uuid = get_fsid(cluster=self.args.cluster)
+        write_one_line(path, 'ceph_fsid', self.args.cluster_uuid)
+        self.create_key(self.args.cluster)
```

**Comment by dachary** [comment]
self.create_key() must not be modified at all by the patch. It is part of the context and irrelevant to this commit.

**Comment by shinobu-x** [comment]
@dachary Yeah that's perfectly my bad =) Sorry for that.

**Comment by shinobu-x** [comment]
Yay finally I'm completely clear about what the title means :) It's taken a long time..., will update.
> ceph-disk does not support cluster names different than 'ceph'

**Comment by shinobu-x** [comment]
@dachary Please check. Thank you for your patience :)
```
$ git diff --diff-filter=U
diff --cc src/ceph-disk/ceph_disk/main.py
index dc35c2f,c9f0041..0000000
--- a/src/ceph-disk/ceph_disk/main.py
+++ b/src/ceph-disk/ceph_disk/main.py
@@@ -2509,7 -2552,10 +2520,14 @@@ class Lockbox(object)
          LOG.debug('Mounting lockbox ' + str(" ".join(args)))
          command_check_call(args)
          write_one_line(path, 'osd-uuid', self.args.osd_uuid)
++<<<<<<< HEAD
+        self.create_key()
++=======
+         if self.args.cluster_uuid is None:
+             self.args.cluster_uuid = get_fsid(cluster=self.args.cluster)
+         write_one_line(path, 'ceph_fsid', self.args.cluster_uuid)
+         self.create_key(self.args.cluster)
++>>>>>>> 7f66672... ceph-disk: dmcrypt activate must use the same cluster as pr
          self.symlink_spaces(path)
          write_one_line(path, 'magic', CEPH_LOCKBOX_ONDISK_MAGIC)
          if self.device is not None:
```
```
$ git diff --diff-filter=U
diff --cc src/ceph-disk/ceph_disk/main.py
index dc35c2f,c9f0041..0000000
--- a/src/ceph-disk/ceph_disk/main.py
+++ b/src/ceph-disk/ceph_disk/main.py
@@@ -2509,7 -2552,10 +2520,10 @@@ class Lockbox(object)
          LOG.debug('Mounting lockbox ' + str(" ".join(args)))
          command_check_call(args)
          write_one_line(path, 'osd-uuid', self.args.osd_uuid)
+        self.create_key()
+         if self.args.cluster_uuid is None:
+             self.args.cluster_uuid = get_fsid(cluster=self.args.cluster)
+         write_one_line(path, 'ceph_fsid', self.args.cluster_uuid)
```

**Comment by dachary** [comment]
In your file what is right after 
```
+         write_one_line(path, 'ceph_fsid', self.args.cluster_uuid)
```

**Comment by shinobu-x** [comment]
@dachary Oh that's ``cherry-pick``! Please :)
```
@@ -2509,6 +2520,9 @@ class Lockbox(object):
         LOG.debug('Mounting lockbox ' + str(" ".join(args)))
         command_check_call(args)
         write_one_line(path, 'osd-uuid', self.args.osd_uuid)
+        if self.args.cluster_uuid is None:
+            self.args.cluster_uuid = get_fsid(cluster=self.args.cluster)
+        write_one_line(path, 'ceph_fsid', self.args.cluster_uuid)
         self.create_key()
```

**Comment by dachary** [comment]
that's better :-)

**Comment by shinobu-x** [comment]
@dachary Thanks, very very appreciated!!

**Comment by shinobu-x** [comment]
test this jenkins

**Comment by shinobu-x** [comment]
jenkins test this please

**Comment by smithfarm** [comment]
@shinobu-x This commit message is missing a description of how the conflict was resolved.

**Comment by smithfarm** [comment]
@dachary This passed a ceph-disk suite at http://tracker.ceph.com/issues/19009#note-5

OK to merge (note: the commit message is missing a description of how the conflict was resolved)?

**Pull request merged**
