### PR TITLE
mon: Forbidden copy and assignment function in monoprequest

### PR DESCRIPTION
**Pull request by songbaisen**
mon: Forbidden copy and assignment function in monoprequest

Signed-off-by:song baisen song.baisen@zte.com.cn

### CODE REVIEW

**Comment by liewegas** [comment]
The c++11 way to do this is to add '= delete' to the declaration so that you get a compile time (vs link time) error.

**Comment by songbaisen** [comment]
@liewegas  Learn it. Thank you!

**Comment by dachary** [comment]
jenkins test this please (jenkins hung)

**Comment by dachary** [comment]
please reword the commit message:
<pre>
Because the class have point as its member,we would better forbid the copy and assign if we do not want this class to do so for safe.
</pre>
is not proper English.  Also make sure you update the commit message and not the github message in the web interface.

**Comment by songbaisen** [comment]
@dachary Thank you for review.Done it.

**Pull request merged**
