### PR TITLE
qa/tasks/workunit: Backport repo fixes from master

### PR DESCRIPTION
**Pull request by zmc**
http://tracker.ceph.com/issues/19531

### CODE REVIEW

**Comment by tchaikov** [comment]
@smithfarm this PR is a superset of your #14394. as @zmc would like to have the other two commit in kraken too.

**Comment by smithfarm** [comment]
@tchaikov OK, but do the other 2 commits need to be backported to all the other named branches, too? Or is it enough to have them in kraken? See http://tracker.ceph.com/issues/19429

**Comment by tchaikov** [comment]
@smithfarm no, as a feature, they are not needed. the minimum fix to accommodate the change on teuthology is #14394. but i am fine either way.

**Comment by smithfarm** [comment]
Jenkins re-test this please

**Pull request merged**
