### PR TITLE
pybind/mgr: use memory temp_store

### PR DESCRIPTION
**Pull request by batrick**
It appears some situations require sqlite3 to open a temporary database to execute the old database dump.

Fixes: https://tracker.ceph.com/issues/57851
Signed-off-by: Patrick Donnelly <pdonnell@redhat.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by batrick** [comment]
I've tested this myself on a cluster exhibiting this problem.

**Comment by mchangir** [comment]
> I've tested this myself on a cluster exhibiting this problem.

Since this was an upgrade scenario, was the cluster cold-started after a few scheduled snapshots after the upgrade to confirm that the changes to the db are indeed getting saved and reloaded correctly on restart ?

So if the default temp_store is a file, then sqlite wouldn't know how to create a file in ceph and so this necessitates the explicit specification of **memory** temp_store. Is this analysis correct ?

**Review by vshankar — COMMENTED** [review]
LGTM

**Comment by batrick** [comment]
jenkins test windows

**Comment by batrick** [comment]
jenkins test api

**Comment by batrick** [comment]
jenkins test windows

**Comment by batrick** [comment]
@neha-ojha @ljflores can this be included in the next RADOS run, please?

**Comment by Matan-B** [comment]
https://pulpito.ceph.com/?branch=wip-yuri11-testing-2022-11-18-1506

Rados approved.
**Rados unrelated failures:**
7089770, 7095056: https://tracker.ceph.com/issues/57311 - ensure CRDs are installed first

7089814: https://tracker.ceph.com/issues/53789 - test_aio_notify to fail

7095066, 7095029: https://tracker.ceph.com/issues/58097 - drop.ceph.com is corrupted

7095031: https://tracker.ceph.com/issues/58098 - test_crash.sh

7095033, 7095064: https://tracker.ceph.com/issues/58096 - test_cluster_set_reset_user_config

7095039, 7095043: Infra: Failed to fetch http://*.archive.ubuntu.com

7095046: https://tracker.ceph.com/issues/52321 -  'check osd count' reached maximum tries

7095058: https://tracker.ceph.com/issues/57771 - cephtest bash -s' fails

**Comment by vshankar** [comment]
@yuriw Did we run this through fs suite?

**Review by vshankar — APPROVED** [review]

**Pull request merged**
