### PR TITLE
osd/scheduler: Reset ephemeral changes to mClock built-in profile

### PR DESCRIPTION
**Pull request by sseshasa**
This is a follow-up to PR: https://github.com/ceph/ceph/pull/48703. This fix also considers changes made ephemerally using either the 'daemon' or the 'tell' interfaces to override the built-in mClock QoS parameters. In such a scenario, the ephemeral changes are removed using the rm_val() method exposed by the config subsytem and logging this information.

Other changes:

1. Add a standalone test to exercise the fix.
2. Add documentation note on the outcome of the attempt to modify built-in profile defaults.
3. Modify mon caps to allow OSDs to run "config rm" command with restrictions.

Fixes: https://tracker.ceph.com/issues/61155
Signed-off-by: Sridhar Seshasayee <sseshasa@redhat.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [x] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [x] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Review by athanatos — APPROVED** [review]

**Comment by sseshasa** [comment]
jenkins test make check

**Comment by sseshasa** [comment]
jenkins test api

**Comment by ljflores** [comment]
jenkins test api

**Comment by ljflores** [comment]
Rados suite review available here: https://tracker.ceph.com/projects/rados/wiki/MAIN#httpstrellocomc1EFSeXDn1752-wip-yuri10-testing-2023-05-16-1243

**Comment by yuriw** [comment]
jenkins test api

**Comment by sseshasa** [comment]
@yuriw @ljflores I am checking if the API test failure is related to the moncap commit I introduced.

**Comment by yuriw** [comment]
@sseshasa pls merge when ready

This is tested ref: https://trello.com/c/1EFSeXDn

**Comment by sseshasa** [comment]
jenkins test api

**Comment by sseshasa** [comment]
@rishabh-d-dave Please review aed71b56be3420d5e499453280e8aee017ce2dd5 as I see that you are the main contributor of this tool. With the mon caps change in this PR, vstart_runner test as mentioned in the above commit's message was failing. I therefore made a small change in vstart_runner.py to allow override of recovery options as mclock scheduler is the default. With this change, the API test passes.

**Comment by sseshasa** [comment]
> @rishabh-d-dave Please review [aed71b5](https://github.com/ceph/ceph/commit/aed71b56be3420d5e499453280e8aee017ce2dd5) as I see that you are the main contributor of this tool. 

@rishabh-d-dave Can you please take a quick look at the above commit related to vstart_runner.py? The other commits are already reviewed. I am planning to backport this to reef and quincy and get them into downstream releases soon and therefore the urgency.

**Pull request merged**
