### PR TITLE
common: add description in PerfCounter class

### PR DESCRIPTION
**Pull request by Ved-vampir**
Signed-off-by: Kiseleva Alyona <akiselyova@mirantis.com>

### CODE REVIEW

**Comment by Ved-vampir** [comment]
Sorry, mistake in commit

**Comment by Ved-vampir** [comment]
Test didn't match new functionality. Add changes to test too.

**Comment by liewegas** [comment]
looks good!  now to document the existing counters...

**Comment by trociny** [comment]
Sorry for the late comment. Wouldn't it be better to use empty description instead of "NO_INFO_FIX" for undocumented counters? Or do we really expect all counters are fixed before it is released?

**Comment by jcsp** [comment]
I was just noticing the same thing as @trociny while rebasing #3615 onto this -- we should probably fix that NO_INFO_FIX to just use a NULL instead (don't forget to handle NULL in ::dump methods)

**Comment by Ved-vampir** [comment]
Ok, I can do it as new pull request, but what is better: NULL or ""?

**Comment by jcsp** [comment]
I'd suggest you use a NULL internally and output it as an empty string (as our Formatter classes don't have a concept of null values).

**Pull request merged**
