### PR TITLE
pacific: mgr/dashboard: The API toolbar menu entry points to the wrong URL

### PR DESCRIPTION
**Pull request by votdev**
Fixes: https://tracker.ceph.com/issues/53322

Note, this requires https://github.com/ceph/ceph/pull/44001 to get working in combination with Angular dev server.

Before:
Peek 2021-11-18 16-25

After:
Peek 2021-11-18 16-33

Signed-off-by: Volker Theile <vtheile@suse.com>

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests
- Teuthology
  - [ ] Completed teuthology run
  - [ ] No teuthology test necessary (e.g., documentation)

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by votdev** [comment]
jenkins test dashboard cephadm

**Comment by votdev** [comment]
jenkins test dashboard cephadm

**Comment by votdev** [comment]
jenkins test dashboard

**Comment by votdev** [comment]
jenkins test dashboard cephadm

**Comment by votdev** [comment]
jenkins test dashboard

**Comment by votdev** [comment]
E2E tests seem to be totally broken, but not because of this PR.
```
[0m  1) Create cluster add host page
       "before each" hook for "should verify "_no_schedule" label is added":
[0m[31m     CypressError: The following error originated from your application code, not from Cypress.

  > ResizeObserver loop limit exceeded
```

**Comment by nizamial09** [comment]
Should https://github.com/ceph/ceph/pull/44001 needs to be backported to pacific before this?

**Comment by alfonsomthd** [comment]
@votdev @epuertat @aaSharma14 What about backporting https://github.com/ceph/ceph/pull/41523 ?

**Comment by alfonsomthd** [comment]
Closed in favor of https://github.com/ceph/ceph/pull/44400

**Pull request closed without merging**
