### PR TITLE
[WIP]mgr/dashboard: Display tabs on user and role forms

### PR DESCRIPTION
**Pull request by familyuu**
fixes:http://tracker.ceph.com/issues/36402

Signed-off-by: familyuu <guodan1@lenovo.com>

### CODE REVIEW

**Comment by familyuu** [comment]
@Devp00l

**Comment by familyuu** [comment]
@Devp00l Oh, I am very sorry, I just accidentally turned off the PR. Could you reopen it?

**Comment by familyuu** [comment]
@Devp00l 
Firstly, I can fix all the problems with failed tests.
What I wonder is, however,  the mean of 'switch from user add form to role add form'.  Is your mean is clicking 'roles' tab at user add form page, then navigate directly to the role add form page? 
 IMH, "Users" and "Roles" tabs are represented two kinds of operations of user management. So all components about users should belong to the "Users" tab, and then, we can only have two tabs  totally("Users" and "Roles").
So, when you click the "Users" tab, you should see the users table firstly, and this will same to "Roles" tab. And then, you click the Add button, you can see the user add form or role add form.
However,  I think there must be some better ideas about this feature, I will happy to hear from you. 
And, as we knew, issue #36402 just need to add "Users" and "Roles" tabs on the user add form and role add form. I think what you said should be an enhancement for user management, should we add this request to the description of [http://tracker.ceph.com/issues/36402]?

**Comment by Devp00l** [comment]
@ricardoasmarques how should the tabs behave in the form?

@familyuu 
However it should look in the end, the solution will require that the input in the forms will be stored or the user will be notified if he would loose the input, before losing it.

**Comment by familyuu** [comment]
> @ricardoasmarques how should the tabs behave in the form?
> 
> @familyuu
> However it should look in the end, the solution will require that the input in the forms will be stored or the user will be notified if he would loose the input, before losing it.

I agree with you. It looks like need more design for this feature. I am waiting for more description details from you both, and then, I implement it. Thanks.
By the way, I just added an "Add role" button beside the Roles form field on the user add form page, The user can click it navigate to the role add form.

**Comment by ricardoasmarques** [comment]
Users/Roles was the first page with 2 tabs to separate 2 different lists (now we have more pages like this), and at the time it seemed like a good idea to display those tabs in the corresponding form page.

From the feedback in this PR, we can conclude that it was a bad idea.

I'm fine with closing this PR and the corresponding issue, sorry for the wasted work @familyuu.

**Comment by familyuu** [comment]
> Users/Roles was the first page with 2 tabs to separate 2 different lists (now we have more pages like this), and at the time it seemed like a good idea to display those tabs in the corresponding form page.
> 
> From the feedback in this PR, we can conclude that it was a bad idea.
> 
> I'm fine with closing this PR and the corresponding issue, sorry for the wasted work @familyuu.

It's ok,  just closed it, I have gotten a lot from this work.

**Comment by LenzGr** [comment]
@familyuu - I too want to apologize that you spent time on this and we now had to reject it. We must ensure that we close such issues in the tracker beforehand, so nobody starts working on these in vain.

**Pull request closed without merging**
