### PR TITLE
rbd:snap purge image will remove all the unprotected snaps

### PR DESCRIPTION
**Pull request by mingyuez**
1、Check whether the image has snap or not,if not,do not show any information instead of "Removing all snapshots: 100% complete...done. "
In rbd.cc,function do_purge_snaps
test fix:
An image doesn't have any snap, execute 'rbd snap purge image'
before:
Removing all snapshots: 100% complete...done. 
after:
Without any hints

2、"rbd snap purge image" will remove all the unprotected snaps of the image.
In rbd.cc,function do_purge_snaps
test fix:
An image has 3 snaps(such as a、b、c),and b is a protected snap,then execute 'rbd snap purge image’
before：
Removing all snapshots: 33% complete...failed. and image still have b、c snap.
after：
Removing all snapshots: 66% complete...failed. and image only have b snap.

Signed-off-by: mingyuez <zhao.mingyue@h3c.com>

### CODE REVIEW

**Comment by idryomov** [comment]
I don't think we want this sneaky behaviour where only unprotected snapshots are removed.  (The current behaviour where we remove *some* of the unprotected snapshots is equally bad.)  I think snap purge should either remove all snapshots or fail.

That said, being able to nuke all snapshots, even if some of them are protected, is useful.  I'm not sure what's the best course of action here, but I'd add a --purge-protected and double it with a --yes-i-really-really-mean-it, so that we end up somewhere close to this:
```
$ rbd snap purge foo
rbd: some of the snapshots are protected from removal
$ rbd snap purge foo --purge-protected
rbd: this will purge protected snapshots, potentially breaking cloned images
rbd: if that's what you want, follow up with --yes-i-really-really-mean-it
$ rbd snap purge foo --purge-protected --yes-i-really-really-mean-it
Removing all snapshots: 100% complete...done. 
```

**Comment by idryomov** [comment]
Your change by itself is good idea - removing all unprotected snapshots is better than bailing on the first protected snapshot.  I just wanted to post my thoughts on this for discussion.

**Comment by jdurgin** [comment]
Like @idryomov mentioned, I think it would be better to check whether any snapshots are protected before purging, and failing up front rather than removing a subset.

I'd rather not add a way to remove protected snapshots, at least at this level where users may accidentally use it. For development it's easy enough to rename images or recreate pools.

**Comment by mingyuez** [comment]
@idryomov, I think that since a snap has been set to protected mode, it should not be deleted.The original intention of designing 'protected' is not allowed deletion, isn't it?

**Comment by mingyuez** [comment]
@idryomov @jdurgin  
if one rbd block has a lot of snaps and parts of snaps are protected, and the purpose of users is to delete  all the snaps,  do the best to finish the removing operation also seems like resonable.

**Comment by idryomov** [comment]
@mingyuez I disagree.  I think user's intent to remove all normal snapshots and leave protected snapshots around is a pretty unlikely case.  The major use case IMO is removing all snapshots before removing an image - if rbd snap purge succeeds, rbd rm shouldn't fail with an error related to existing snapshots.  I'll leave it up to @jdurgin to decide on this.

If we chose to go with removing a subset, you'll need to update usage() and man page.

**Comment by mingyuez** [comment]
I admit that ‘return failure directly’ is indeed a relatively simple method of modification. 
@jdurgin ,which method do you prefer ?
1.'remove subset' 
2.'return failure directly without removing any snaps'
3. 'add command args for users to remove protected snaps ' as idryomov  mentioned
I really need your advice,looking forward to your reply！

**Comment by jdurgin** [comment]
@mingyuez I prefer 2 - @idryomov's reasoning makes sense to me

**Comment by mingyuez** [comment]
@jdurgin @idryomov  ok,I will follow 2 method to modify the code.Thanks for you help!

@jdurgin  if I modify code, I should create another pull request to commit new code and description?

**Comment by jdurgin** [comment]
Sure, create another pull request. BTW, it's good practice to use a specific branch that you can update for a given PR, rather than the master branch in your ceph repo. That way you could have more than one PR in flight at once.

Another procedural note, the description in the PR is useful - a longer description like that and the Signed-off-by line should go in your commit messages too, so it's easy to understand the context of the change later.

**Comment by mingyuez** [comment]
@jdurgin if use method 2,the message to users I will change to 'Removing all snapshots: 0% complete...failed. xxx(the first protected snap name) is a protected snap',do you think this message is ok?

**Comment by jdurgin** [comment]
@mingyuez yeah, sounds good

**Pull request closed without merging**
