### PR TITLE
nautilus: rgw: sync with elastic search v7

### PR DESCRIPTION
**Pull request by smithfarm**
backport tracker: https://tracker.ceph.com/issues/42182

---

backport of https://github.com/ceph/ceph/pull/29637
parent tracker: https://tracker.ceph.com/issues/41227

this backport was staged using ceph-backport.sh version 15.0.0.6270
find the latest version at https://github.com/ceph/ceph/blob/master/src/script/ceph-backport.sh

### CODE REVIEW

**Comment by smithfarm** [comment]
```
/home/jenkins-build/build/workspace/ceph-pull-requests/src/rgw/rgw_sync_module_es.cc: In member function 'virtual void RGWElasticDataSyncModule::init(RGWDataSyncEnv*, uint64_t)':
/home/jenkins-build/build/workspace/ceph-pull-requests/src/rgw/rgw_sync_module_es.cc:821:71: error: 'class RGWRados' has no member named 'getRados'; did you mean 'RGWRados'?
     RGWCoroutinesManager crs(sync_env->store->ctx(), sync_env->store->getRados()->get_cr_registry());
                                                                       ^~~~~~~~
                                                                       RGWRados
src/rgw/CMakeFiles/rgw_common.dir/build.make:651: recipe for target 'src/rgw/CMakeFiles/rgw_common.dir/rgw_sync_module_es.cc.o' failed
make[3]: *** [src/rgw/CMakeFiles/rgw_common.dir/rgw_sync_module_es.cc.o] Error 1
```

**Comment by aleksandpetrov** [comment]
Somebody, please, approve this PR!!!

**Comment by smithfarm** [comment]
@aleksandpetrov Please be patient. Assuming this PR passes integration tests, it will be merged in time for the 14.2.5 release.

**Comment by yuriw** [comment]
[wip-yuri7-testing-2019-11-12-2103-nautilus](https://trello.com/c/WyvBSbE0/757-wip-yuri7-testing-2019-11-12-2103-nautilus)

**Pull request merged**
