### PR TITLE
osdc/Objecter: handle race between calc_target and handle_osd_map

### PR DESCRIPTION
**Pull request by liewegas**
If we fail to get an existing session and have to take the exclusive lock,
we may race with an OSDMap update and end up with a stale target.  Check
for an epoch change and, if it happens, recalculate the mapping.

Fixes: http://tracker.ceph.com/issues/17942
Reported-by: wangdongxu <wangdongxu@cmss.chinamobile.com>
Reported-by: menglingkun <menglingkun@cmss.chinamobile.com>
Signed-off-by: Sage Weil <sage@redhat.com>

### CODE REVIEW

**Comment by dachary** [comment]
test this please (eio)

**Comment by dachary** [comment]
jenkins test this please (eio now ignored on master)

**Comment by liewegas** [comment]
@bruce-lz did you actually hit this race?

**Comment by dachary** [comment]
jenkins test this please (asok)

**Comment by bruce-lz** [comment]
./osd/OSDMap.h: In function 'entity_inst_t OSDMap::get_inst(int) const' thread 7fde05033700 time 2016-10-22 13:40:33.884752
./osd/OSDMap.h: 484: FAILED assert(is_up(osd))
ceph version .94.5-bcebsv4.0-14-g1e09ec0-release2.7.1_for_mobile_suyan-193 (1e09ec07ec53894d3614d3631eb0438aa1f2b451)
1: (()+0x133e7f) [0x7fde17cb7e7f]
2: (()+0x112ff7) [0x7fde17c96ff7]
3: (()+0x127fd0) [0x7fde17cabfd0]
4: (()+0x1285bc) [0x7fde17cac5bc]
5: (()+0xfcc6e) [0x7fde17c80c6e]
6: (librados::IoCtx::aio_operate(std::string const&, librados::AioCompletion*, librados::ObjectWriteOperation*, unsigned long, std::vector<unsigned long, std::allocator<unsigned long> >&)+0x18a) [0x7fde17c50e0a]
7: (()+0xc1cdf) [0x7fde1a41bcdf]
8: (()+0xc1fa8) [0x7fde1a41bfa8]
9: (()+0x103354) [0x7fde1a45d354]
10: (()+0xbec39) [0x7fde1a418c39]
11: (()+0x169ac6) [0x7fde1a4c3ac6]
12: (()+0x16b710) [0x7fde1a4c5710]
13: (()+0x7dc5) [0x7fde1cfe9dc5]
14: (clone()+0x6d) [0x7fde1529821d]
NOTE: a copy of the executable, or `objdump -rdS <executable>` is needed to interpret this.
terminate called after throwing an instance of 'ceph::FailedAssertion'

**Comment by dachary** [comment]
jenkins test this please (unittest_throttle)

**Comment by liewegas** [comment]
@bruce-lz that was with this PR?

**Comment by tchaikov** [comment]
http://pulpito.ceph.com/kchai-2016-11-22_09:44:32-rados-wip-kefu-testing---basic-mira/

**Pull request merged**
