### PR TITLE
Revert "mgr/DaemonServer: log pgmap usage to cluster log"

### PR DESCRIPTION
**Pull request by jecluis**
This partially reverts commit f64a69e5054fb319e9f717bbcb7ddd8541e01c6f.

Having clog, by default, logging on debug causes a lot of noise to
unsuspecting users.

Signed-off-by: Joao Eduardo Luis \<joao@suse.com>

### CODE REVIEW

**Comment by vumrao** [comment]
We added this message back as it was in jewel and before releases,  from the performance and cluster load troubleshooting point of view. The logline helps when we need to check client IO and recovery IOPS for RCA purpose. Can we keep it, as it really helps in RCA?

Or 

If we are removing it, would this type of information will be captured historically in Dashboard kind of tooling to do the RCA.

**Comment by LenzGr** [comment]
> If we are removing it, would this type of information will be captured historically in Dashboard kind of tooling to do the RCA.

Not in the dashboard per se, as it does not store time series data - but wouldn't this be captured by monitoring tools like Prometheus/Grafana, for example?

**Comment by jecluis** [comment]
> We added this message back as it was in jewel and before releases, from the performance and cluster load troubleshooting point of view. The logline helps when we need to check client IO and recovery IOPS for RCA purpose. Can we keep it, as it really helps in RCA?

I have no opinion, at the moment, on the level these messages should be outputted at. But I think logging by default at debug is a very bad idea.

If I had to venture a suggestion, I'd say that maybe the IO messages would require to be explicitly enabled then, because we have seen downstream users complaining about the noise these create in the cluster log. Especially logging at default, and they end up being suppressed once we raise the clog level to info.

**Comment by neha-ojha** [comment]
@liewegas @jdurgin In https://github.com/ceph/ceph/pull/26105  we brought the log message back at `debug` level and made `mon_cluster_log_file_level` default to `debug` to address downstream requirements(https://github.com/ceph/ceph/pull/28917#issuecomment-509779851), with the idea that users who don't want those stats can change `mon_cluster_log_file_level` to `info`. This PR would mean that those stats won't be logged by default - don't think that would work for downstream. Thoughts?

**Comment by jecluis** [comment]
@neha-ojha I do think that those messages can be useful; however, I still think setting clog to debug by default is not a great idea. These messages generate quite a bit of noise in clog, and I'd rather it be turned on explicitly rather than by default.

I don't even think these should be logged at debug - too likely to have other, unrelated messages, if not now then in the future, that are not necessarily for regular user consumption and will even produce more noise. Maybe adding a 'verbose' level, between 'debug' and 'info' would be a good approach: have that message being logged at verbose, default for clog being info, and make 'verbose' being opt-in.

**Comment by sebastian-philipp** [comment]
> Maybe adding a 'verbose' level, between 'debug' and 'info'

Well, in my case those pgmap messages make up about 96% of all log lines. In this case, `verbose` should be a log level higher than `debug`.

**Comment by jecluis** [comment]
@sebastian-philipp maybe I misunderstood what you meant, but wasn't that what I said in the message above?

**Comment by jecluis** [comment]
@neha-ojha @liewegas the new commits require tests for validation, but pushing for feedback.

**Comment by liewegas** [comment]
I'm not a big fan of adding a new level between info and debug.  What if we just change the default back to info upstream, and have rhcs/downstream change it to debug?

**Comment by jdurgin** [comment]
perhaps we could log pg stats and other periodic status to a separate channel - the history of e.g. pg states is quite useful for diagnosing issues, and isn't always well captured otherwise

**Comment by liewegas** [comment]
I like that idea!

**Comment by vumrao** [comment]
> perhaps we could log pg stats and other periodic status to a separate channel - the history of e.g. pg states is quite useful for diagnosing issues, and isn't always well captured otherwise

Thanks Josh. If I understand correct having a separate channel here means having a new log file something like `ceph.iops.log`(like we have `ceph.audit.log`) instead of logging them in cluster log `ceph.log`?

**Comment by jecluis** [comment]
> perhaps we could log pg stats and other periodic status to a separate channel - the history of e.g. pg states is quite useful for diagnosing issues, and isn't always well captured otherwise

Yeah, I think this is a simpler and cleaner solution. I'll take a crack at it.

**Comment by vumrao** [comment]
https://github.com/ceph/ceph/pull/29357

**Comment by danky78** [comment]
Please, fix #29357

**Pull request closed without merging**
