### PR TITLE
client: do not uninline data for read

### PR DESCRIPTION
**Pull request by lxbsz**
We don't even ask for and to be sure that we have granted the Fw
caps when reading, we shouldn't write contents to Rados.

The bug was introduced by commit a0cb52425147
(client: Read inline data path)

Fixes: https://tracker.ceph.com/issues/56553
Signed-off-by: Xiubo Li <xiubli@redhat.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Review by mchangir — APPROVED** [review]
I wish the initial committer had elaborated on the reasons about **why** the **read** path was also chosen for uninlining.

**Comment by lxbsz** [comment]
> I wish the initial committer had elaborated on the reasons about **why** the **read** path was also chosen for uninlining.

Added the author of that commit to help review this.

**Comment by lxbsz** [comment]
@dragonylffly Could you help explain it ? Did we miss something important here ?
Thanks!

**Comment by ajarr** [comment]
jenkins test windows

**Review by vshankar — APPROVED** [review]

**Review by kotreshhr — APPROVED** [review]

**Comment by vshankar** [comment]
Test running here: https://pulpito.ceph.com/vshankar-2022-09-05_05:44:13-fs-wip-vshankar-testing-20220901-100101-testing-default-smithi/

**Pull request merged**
