### PR TITLE
rocksdb: cherry-picked modification to skiplist from fb/rocksdb

### PR DESCRIPTION
**Pull request by aclamk**
Signed-off-by: Adam Kupczyk <akupczyk@redhat.com>

This speeds adds to rocksdb when memtable=skiplist is used.

### CODE REVIEW

**Comment by liewegas** [comment]
@aclamk you need to push the rocksdb commit to ceph/rocksdb (just add it to master branch?)

**Comment by aclamk** [comment]
@liewegas 
There is https://github.com/ceph/rocksdb/pull/32. I somehow feel hesitant to merge my pull request....

**Comment by liewegas** [comment]
retest this please

**Comment by tchaikov** [comment]
@aclamk since your change has landed on upstream's master branch. mine (https://github.com/facebook/rocksdb/pull/2950) just got merged. i am going to push fb/master to our fork's master branch, and stash your change (https://github.com/ceph/rocksdb/pull/32) on rocksdb in https://github.com/ceph/rocksdb/tree/skiplist-with-prefetch, in case you want to use it. and then pick up fb/master in ceph instead.

**Comment by tchaikov** [comment]
see #18262

**Comment by aclamk** [comment]
@tchaikov Of course it is OK. My change is already there.

**Comment by liewegas** [comment]
:+1:

**Pull request closed without merging**
