### PR TITLE
rgw: udpate radosgw-admin usage with bi purge

### PR DESCRIPTION
**Pull request by yaozongyou**
Signed-off-by: Yao Zongyou <yaozongyou@vip.qq.com>

### CODE REVIEW

**Comment by yaozongyou** [comment]
retest this please

**Comment by yaozongyou** [comment]
retest this please

**Comment by yaozongyou** [comment]
retest this please

**Comment by yaozongyou** [comment]
@joscollin fixed, please check.

**Comment by yuriw** [comment]
[wip-yuri4-testing-2017-10-12-1719](https://trello.com/c/nGEHKwJe/178-wip-yuri4-testing-2017-10-12-1719)

**Pull request merged**
