### PR TITLE
debian: bump compat to 9

### PR DESCRIPTION
**Pull request by tchaikov**
so dpkg-buildflags and dh_* are able to pass appropriate cflags and
ldflags to cmake. and we are safe to move to compat 9, as , as jewel's
supported debian based distro is jessie (with debhelper 9.20150101),
ubuntu trusty (with debhelper 9.20131227ubuntu1)

Fixes: http://tracker.ceph.com/issues/16744
Signed-off-by: Kefu Chai <kchai@redhat.com>

### CODE REVIEW

**Comment by tchaikov** [comment]
```
[  0%] Building CXX object src/compressor/CMakeFiles/compressor_objs.dir/AsyncCompressor.cc.o
cd /var/ceph/ceph/obj-x86_64-linux-gnu/src/compressor && /usr/bin/c++   -DCEPH_LIBDIR=\"/usr/lib\" -DCEPH_PKGLIBDIR=\"/usr/lib/ceph\" -D__linux__ -I/var/ceph/ceph/obj-x86_64-linux-
gnu/src/include -I/include -I/var/ceph/ceph/src -I/var/ceph/ceph/obj-x86_64-linux-gnu/include -I/var/ceph/ceph/src/xxHash  -g -O2 -fstack-protector-strong -Wformat -Werror=format-s
ecurity -Wdate-time -D_FORTIFY_SOURCE=2  -rdynamic -Wall -Wtype-limits -Wignored-qualifiers -Winit-self -Wpointer-arith -Werror=format-security -fno-strict-aliasing -fsigned-char -
Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=2 -fstack-protector-strong -ftemplate-depth-1024 -Wno-invalid-offsetof -Wnon-virtual-dtor -Wno-invalid-offsetof -Wstrict-null-sentinel -Wover
loaded-virtual -fdiagnostics-color=auto -I/usr/include/nss -I/usr/include/nspr -fno-builtin-malloc -fno-builtin-calloc -fno-builtin-realloc -fno-builtin-free -fPIC   -DHAVE_CONFIG_
H -D__CEPH__ -D_FILE_OFFSET_BITS=64 -D_REENTRANT -D_THREAD_SAFE -D__STDC_FORMAT_MACROS -D_GNU_SOURCE -std=c++11 -o CMakeFiles/compressor_objs.dir/AsyncCompressor.cc.o -c /var/ceph/
ceph/src/compressor/AsyncCompressor.cc
```

it works on my debian box.

**Comment by dmick** [comment]
I totally don't understand how this fixes anything.

**Comment by tchaikov** [comment]
@dmick updated the commit message and repushed.

**Comment by dmick** [comment]
I now understand and agree with the approach.  Looking into the build failure

**Comment by dmick** [comment]
I was waiting to get a clean build sorted, but...

**Pull request merged**
