### PR TITLE
osd/PG: create new PGs from activate in last_peering_reset epoch

### PR DESCRIPTION
**Pull request by liewegas**
If we create a new PG (e.g., a backfill target) in the current epoch, it
might be > last_peering_reset.  That can lead to last_peering_reset on
the replica having a higher last_peering_reset than the primary's, which
can then lead to future messages, like pg_scan during backfill, being
ignored.

Fixes: http://tracker.ceph.com/issues/24452
Signed-off-by: Sage Weil <sage@redhat.com>

### CODE REVIEW

**Comment by dzafman** [comment]
@liewegas  osd-backup-stats.sh and osd-recovery-stats.sh tests PASSED.

**Comment by gregsfortytwo** [comment]
This LGTM, but it's the second epoch/query_epoch fix PR in a couple days (see #22408); we may need to audit those...

**Comment by liewegas** [comment]
Aha! Just confirmed that's the commit that broke this.. not sure how that made it through qa.  I don't see a ticket associated with it either, so I'm not sure if they were trying to fix something or it just looked like cleanup?

**Comment by liewegas** [comment]
http://pulpito.ceph.com/sage-2018-06-08_18:52:54-rados-wip-24454-distro-basic-smithi/

**Comment by liewegas** [comment]
Okay, audited the code and MOSDPGScan and MOSDPGBackfill are teh one two messages that are checked against last_peering_reset in this way (where it's the query_epoch or min_epoch and not the latest epoch we check), but MOSDPGBackfill has the same init "bug" that MOSDPGScan did, so it doesn't cause problems.

I'm could build a branch that "fixes" MOSDPGBackfill too and test it.

Separately, all of the replica ops are only getting checked against map_epcoh and not min_epoch at all.. those could get fixed for good measure, but I'm not actually sure those really matter: those ops are only sent after peering completes, so last_peering_reset is not really relevant.. only the interval changes.  The purpose of the min_epoch is to avoid making the recipient wait for the latest source map if it doesn't matter, and that part of things already works (and is independent of the old_peering_msg/can_discard_whatever checks).  I think we could just add a comment to the code to that effect. That said, this patch should fix the problem too, but we'll want to make sure there isn't any other fallout first.

Running this through the full rados suite now.

**Comment by liewegas** [comment]
Added a commit to deal with the upgrade case: encode the map_epcoh in the query_epoch slot so that pre-nautilus OSDs will not suffer from the bug.

**Comment by liewegas** [comment]
http://pulpito.ceph.com/sage-2018-06-08_21:32:05-rados-wip-24454-distro-basic-smithi/
- the remaining recovery timeout is the upgrade test; the second patch fixes that.  rerun is be scheduled shortly
- objectstore failure is known bug
- osd-unexpected-clone bug is addressed by #22482 
- install errors are broken centos mirror
- the max pg test failure i've seen before?

**Comment by tchaikov** [comment]
the max pg test failure is addressed by #22485 .

**Pull request merged**
