### PR TITLE
nautilus: mgr/dashboard: Remove username, password fields from Manager Modules/dashboard,influx

### PR DESCRIPTION
**Pull request by aaSharma14**
backport tracker: https://tracker.ceph.com/issues/50050

---

backport of https://github.com/ceph/ceph/pull/39908
parent tracker: https://tracker.ceph.com/issues/49645

this backport was staged using ceph-backport.sh version 16.0.0.6848
find the latest version at https://github.com/ceph/ceph/blob/master/src/script/ceph-backport.sh

### CODE REVIEW

**Comment by aaSharma14** [comment]
kenkins test make check

**Comment by aaSharma14** [comment]
jenkins test make check

**Comment by aaSharma14** [comment]
jenkins test api

**Comment by aaSharma14** [comment]
jenkins test api

**Comment by aaSharma14** [comment]
jenkins test make check

**Review by alfonsomthd — APPROVED** [review]

**Comment by aaSharma14** [comment]
jenkins test make check

**Comment by tchaikov** [comment]
@aaSharma14 the nautilus test failure should be addressed by #40536.

**Comment by tchaikov** [comment]
sorry for the inconvenience. =(

**Comment by aaSharma14** [comment]
> @aaSharma14 the nautilus test failure should be addressed by #40536.

Thanks @tchaikov for letting know.

**Review by nizamial09 — APPROVED** [review]

**Comment by aaSharma14** [comment]
jenkins test make check

**Comment by aaSharma14** [comment]
jenkins test make check

**Comment by aaSharma14** [comment]
jenkins test make check

**Comment by nizamial09** [comment]
jenkins test make check

**Comment by aaSharma14** [comment]
jenkins test make check

**Comment by alfonsomthd** [comment]
@aaSharma14 make-check failed with lint error:
```
py3-lint runtests: commands[2] | pylint --rcfile=.pylintrc --jobs=5 . module.py tools.py controllers tests services exceptions.py grafana.py ci/check_grafana_uids.py
************* Module dashboard.tests.test_access_control
tests/test_access_control.py:8:0: W0611: Unused import time (unused-import)
```

**Comment by smithfarm** [comment]
@aaSharma14 Could you add a `Conflicts` section at the end of the commit message describing the manual changes you needed to make to the cherry-pick, and why?

**Comment by aaSharma14** [comment]
jenkins retest this please

**Comment by avanthakkar** [comment]
jenkins test make check

**Comment by aaSharma14** [comment]
> @aaSharma14 Could you add a `Conflicts` section at the end of the commit message describing the manual changes you needed to make to the cherry-pick, and why?

Done. Thanks

**Pull request merged**
