### PR TITLE
kraken: rgw: Custom data header support

### PR DESCRIPTION
**Pull request by prallabh**
Fixes: http://tracker.ceph.com/issues/19843
Signed-off-by: Pavan Rallabhandi <PRallabhandi@walmartlabs.com>

### CODE REVIEW

**Comment by prallabh** [comment]
CC: @yehudasa @mattbenjamin @smithfarm

**Comment by smithfarm** [comment]
@prallabh Is there a reason why this wasn't cherry-picked from master?

**Comment by smithfarm** [comment]
Just FYI, some notes on backporting commits here: http://tracker.ceph.com/projects/ceph-releases/wiki/HOWTO_backport_commits

**Comment by prallabh** [comment]
It's not a direct patch from master, like we don't have `RGWObjEnt` present in master unlike here.

**Comment by prallabh** [comment]
Ah, I wasn't aware of that notes, let me rework this as per the process, thanks!

**Comment by smithfarm** [comment]
@prallabh Thanks. In this case it looks like there is just one commit from master, so you just `git cherry-pick -x` that commit, make the necessary modifications, and describe them in the "Conflicts" section of the commit message.

**Comment by smithfarm** [comment]
There should be a brief conflict resolution description for each file that contains a conflict (`git cherry-pick -x` provides the list of files in the commit message), and you just append a brief note to each file. Like "no RGWEntObj in kraken" or whatever is appropriate.

**Comment by smithfarm** [comment]
Marking DNM pending rework.

**Comment by smithfarm** [comment]
@prallabh Please rebase to latest kraken to pick up https://github.com/ceph/ceph/pull/16069

**Comment by prallabh** [comment]
@smithfarm can you please check now, I've cherry picked from master, thanks!

**Comment by smithfarm** [comment]
@prallabh Please rebase - I just merged a bunch of PRs into kraken.

**Comment by prallabh** [comment]
@smithfarm done so, thanks.

**Comment by smithfarm** [comment]
Jenkins re-test this please

**Comment by smithfarm** [comment]
@rzarzynski @cbodley @mattbenjamin @oritwas This passed an RGW suite at http://tracker.ceph.com/issues/19009#note-78

Please review.

**Pull request merged**
