### PR TITLE
cephadm: KillMode=none in unit file

### PR DESCRIPTION
**Pull request by liewegas**
https://tracker.ceph.com/issues/43883 (hopefully)

### CODE REVIEW

**Comment by sebastian-philipp** [comment]
https://tracker.ceph.com/issues/43883 sounds a bit like https://github.com/containers/libpod/issues/3906 which should have been resolved by https://github.com/containers/libpod/pull/4493 . To me, the libpod issue sounds like as if killing containers should work in general. If not, this looks like a bug in libpod, correct? 

Maybe @mheon could shed some light here?

In any case, setting [`KillMode=none`](https://www.freedesktop.org/software/systemd/man/systemd.kill.html#KillMode=) sound like a wrong approach to me.

> If set to none, no process is killed. In this case, only the stop command will be executed on unit stop, but no process will be killed otherwise. Processes remaining alive after stop are left in their control group and the control group continues to exist after stop unless it is empty.

Doesn't this actually increase the risk of processes staying alive?

**Comment by mheon** [comment]
On the Podman side, the issue is that systemd is killing both too many processes. When a Podman container dies, on exit, it runs `podman container cleanup`, which unmounts the container, tears down the network, and (if --rm is set) removes the container. Systemd without KillMode=none will take down the cleanup process while it is still executing, potentially at an awkward point - when we're about to remove storage for the container, for example. 4493 should have relieved this by retaining the container in the database longer, so a second `podman rm` call would remove it (though this doesn't necessarily help systemd units, which are probably trying to recreate the container).

@vrothberg is more familiar with our systemd code than myself; he's been working on new features for improving our interaction with unit files.

**Comment by vrothberg** [comment]
Thanks, Matt! We recently wrote a blog about running Podman in systemd services: https://www.redhat.com/sysadmin/podman-shareable-systemd-services

**Comment by sebastian-philipp** [comment]
Thanks @mheon and @vrothberg !

**Comment by smithfarm** [comment]
@liewegas @sebastian-philipp I have been hearing rumors that this option (`KillMode`) is problematic, deprecated and will be removed from systemd.

What I hear is that `KillMode` is problematic during shutdown, which wrests control of processes away from systemd - the result being that processes that normally get killed thanks to this option (in a non-shutdown scenario) do not get killed. (That sounds like it might plausibly disrupt the shutdown process, but I'm just mechanically repeating what I heard.)

I'm trying to get something more concrete and will hopefully post an update, soon.

P.S. `KillMode` is also in `systemd/ceph-volume@.service` so we would need to drop it there, too.

**Comment by sebastian-philipp** [comment]
@smithfarm Indeed: https://tracker.ceph.com/issues/51361

**Comment by frittentheke** [comment]
> @smithfarm Indeed: https://tracker.ceph.com/issues/51361

I just saw the warning about KillMode=none for unit `ceph-volume@.service` on Reef (18.2.1) on Ubuntu 22.04 LTS (running sytemd 249). Apparently the deprecation warning was introduced with 246 already, see https://github.com/systemd/systemd/blob/8a9bf03bd7e301037e32277d58adbd2eb7ce5534/NEWS#L5887.

1. FWIW, this is a non-cephadm installation using packages (https://docs.ceph.com/en/latest/install/get-packages/#debian-packages), not containers via podman.
2. Podman did change it's systemd generator / recommendations away from `KillMode=none` a long time ago: https://github.com/containers/podman/pull/8889
3. And they additionally moved to sdnotify, see https://github.com/containers/podman/pull/10557

**Pull request merged**
