### PR TITLE
qa/tasks/mgr/dashboard/test_health: update mdsmap schema

### PR DESCRIPTION
**Pull request by bk201**
Fixes: https://tracker.ceph.com/issues/44725
Signed-off-by: Kiefer Chang <kiefer.chang@suse.com>

Example output of mdsmap:
```json
{
  "session_autoclose":300,
  "balancer":"",
  "up":{
    "mds_0":5801
  },
  "last_failure_osd_epoch":0,
  "in":[
    0
  ],
  "last_failure":0,
  "max_file_size":1099511627776,
  "explicitly_allowed_features":0,
  "damaged":[

  ],
  "tableserver":0,
  "metadata_pool":10,
  "failed":[

  ],
  "epoch":26,
  "flags":18,
  "max_mds":1,
  "compat":{
    "compat":{

    },
    "ro_compat":{

    },
    "incompat":{
      "feature_10":"snaprealm v2",
      "feature_8":"no anchor table",
      "feature_9":"file layout v2",
      "feature_2":"client writeable ranges",
      "feature_3":"default file layouts on dirs",
      "feature_1":"base v0.20",
      "feature_6":"dirfrag is stored in omap",
      "feature_4":"dir inode in separate object",
      "feature_5":"mds uses versioned encoding"
    }
  },
  "min_compat_client":"0 (unknown)",
  "data_pools":[
    11
  ],
  "info":{
    "gid_5801":{
      "export_targets":[

      ],
      "name":"a",
      "incarnation":26,
      "state_seq":2,
      "state":"up:creating",
      "gid":5801,
      "features":4540138292836696063,
      "rank":0,
      "flags":0,
      "join_fscid":-1,
      "addrs":{
        "addrvec":[
          {
            "nonce":1244288684,
            "type":"v2",
            "addr":"192.168.2.106:6834"
          },
          {
            "nonce":1244288684,
            "type":"v1",
            "addr":"192.168.2.106:6835"
          }
        ]
      },
      "addr":"192.168.2.106:6835/1244288684"
    }
  },
  "fs_name":"cephfs",
  "created":"2020-03-24T07:38:04.180041+0000",
  "standby_count_wanted":0,
  "enabled":true,
  "modified":"2020-03-24T07:38:10.973690+0000",
  "session_timeout":60,
  "stopped":[

  ],
  "ever_allowed_features":0,
  "root":0
}
```

## Checklist
- [x] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by callithea** [comment]
jenkins test dashboard backend

**Comment by callithea** [comment]
jenkins test make check

**Comment by callithea** [comment]
- [pkg build](https://shaman.ceph.com/builds/ceph/wip-laura-testing-34138-34033/) [WIP]

**Comment by bk201** [comment]
>     * [pkg build](https://shaman.ceph.com/builds/ceph/wip-laura-testing-34138-34033/)
> 
>     * [QA run](http://pulpito.ceph.com/laura-2020-03-24_14:46:48-rados:dashboard-wip-laura-testing-34138-34033-distro-basic-smithi/) [9 / 9 failed]
> 
> 
> `Test failure: test_minimal_health (tasks.mgr.dashboard.test_health.HealthTest)`

It's another attribute, will fix together.
```
!= "In `input['fs_map']['standbys'][0]`: unknown keys: set([u'export_targets', u'addr', u'incarnation', u'state', u'state_seq', u'name', u'epoch', u'gid', u'flags', u'rank', u'join_fscid', u'addrs', u'features'])"
```

**Comment by bk201** [comment]
jenkins test dashboard backend

**Comment by bk201** [comment]
jenkins test dashboard

**Comment by tchaikov** [comment]
http://pulpito.ceph.com/kchai-2020-03-25_08:14:01-rados-wip-kefu-testing-2020-03-25-1220-distro-basic-smithi/

**Pull request merged**
