### PR TITLE
mon: ensure prepare_failure() marks no_reply on op

### PR DESCRIPTION
**Pull request by jecluis**
Signed-off-by: Joao Eduardo Luis \<joao@suse.com>

- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by jecluis** [comment]
will need to be backported to luminous,mimic; not tested yet.

**Comment by liewegas** [comment]
I think this will 'fix' the case in question, but I'm still pretty sure that most of the no_reply call sites are wrong.  I think we shouldn't actually call no_reply unless we either (1) decide the message is redundant and can be dropped or (2) the change it induced has been committed.  Otherwise, we'll lose some messages.  I'm fine with this as a bandaid but I think a complete audit is required.

**Comment by tchaikov** [comment]
retest this please.

**Comment by gregsfortytwo** [comment]
retest this please

**Comment by gregsfortytwo** [comment]
https://tracker.ceph.com/issues/24531

**Comment by gregsfortytwo** [comment]
We generally don't respond directly to failure reports even when they aren't forwarded: it's simply an input that might or might not lead to the OSD being marked down, and there's no predictable speed at which that decision can be made so we don't want to keep the messages around.
If there really is a failure, losing the report because of a monitor failure or issue is fine; it will be re-reported again shortly.

**Comment by tchaikov** [comment]
- http://pulpito.ceph.com/kchai-2019-08-25_16:39:25-rados-wip-kefu-testing-2019-08-25-2138-distro-basic-mira/
- http://pulpito.ceph.com/kchai-2019-08-27_00:38:42-rados-wip-kefu-testing-2019-08-26-1528-distro-basic-mira/
- http://pulpito.ceph.com/kchai-2019-08-27_06:58:14-rados-wip-kefu-testing-2019-08-27-1029-distro-basic-mira/
- http://pulpito.ceph.com/kchai-2019-08-27_06:45:12-rgw-wip-kefu-testing-2019-08-27-1029-distro-basic-smithi/
- http://pulpito.ceph.com/kchai-2019-08-27_08:50:36-rados-wip-kefu-testing-2019-08-27-1029-distro-basic-smithi/

**Comment by simon-rock** [comment]
@jecluis 
@yuriw  
We have a issue that IO is blocked for a long time.
ceph version is 14.2.9.
```
        {
            "description": "osd_failure(failed timeout osd.0 [v2:10.58.218.13:6826/231220,v1:10.58.218.13:6829/231220] for 371086sec e2280 v2280)",
            "initiated_at": "2020-09-01 07:08:37.698258",
            "age": 136432.84009428701,
            "duration": 136432.840178755,
            "type_data": {
                "events": [
                ...
                    {
                        "time": "2020-09-01 07:08:37.698508",
                        "event": "no_reply"
                    }
                ],
                "info": {
                    "seq": 4968708,
                    "src_is_mon": false,
                    "source": "osd.9 v2:10.58.218.13:6824/231218",
                    "forwarded_to_leader": false
                }
            }
        }
```
Why make op no_reply can fix it?

**Comment by simon-rock** [comment]
@jecluis
@tchaikov 
https://tracker.ceph.com/issues/24531  
I  think we should remove reporters when we receive msg of the msg.
In fact, this op is in failure_ info_t can't be processed.

**Pull request merged**
