### PR TITLE
ceph-volume: use the Device.rotational property instead of sys_api

### PR DESCRIPTION
**Pull request by andrewschoen**
Resolves: https://bugzilla.redhat.com/show_bug.cgi?id=1666822

Follow up to #26957

### CODE REVIEW

**Comment by andrewschoen** [comment]
jenkins test ceph-volume tox

**Comment by andrewschoen** [comment]
jenkins test ceph-volume tox

**Comment by andrewschoen** [comment]
jenkins test ceph-volume tox

**Comment by andrewschoen** [comment]
jenkins test ceph-volume batch all

**Comment by michalskalski** [comment]
@andrewschoen  hello I would like to ask if your recent changes also trying to address problems with using more predictable block device names (/deb/by-*) described in these bugs https://bugzilla.redhat.com/show_bug.cgi?id=1674022 and https://tracker.ceph.com/issues/36240 ?

**Comment by alfredodeza** [comment]
@michalskalski that is correct, it would fix the bugs you've linked.

**Comment by michalskalski** [comment]
@alfredodeza thank you for confirmation.

**Pull request merged**
