### PR TITLE
osd: zeroize ceph_osd_op instance in PrimaryLogPG::do_manifest_flush().

### PR DESCRIPTION
**Pull request by rzarzynski**
Fixes: https://tracker.ceph.com/issues/45661
Signed-off-by: Radoslaw Zarzynski <rzarzyns@redhat.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by rzarzynski** [comment]
http://pulpito.ceph.com/rzarzynski_bug45661/5116784/, although failed, hasn't shown any Valgrind issues.

**Comment by tchaikov** [comment]
drop this change as #35186 replaced the change code block with
```c++
      {
	bufferlist t;
	cls_cas_chunk_create_or_get_ref_op get_call;
	get_call.source = soid;
	get_call.data = chunk_data;
	::encode(get_call, t);
	obj_op.call("cas", "chunk_create_or_get_ref", t);
      }
```

**Comment by tchaikov** [comment]
@rzarzynski shall we just close this PR? as #35186 has been merged.

**Comment by rzarzynski** [comment]
@tchaikov: yup. I will put a note into the tracker.

**Pull request closed without merging**
