### PR TITLE
squid: rgw/lifecycle-notification: Do not block lc processing for notification errors.

### PR DESCRIPTION
**Pull request by kchheda3**
backport tracker: https://tracker.ceph.com/issues/66591

---

backport of https://github.com/ceph/ceph/pull/57079
parent tracker: https://tracker.ceph.com/issues/66018

this backport was staged using ceph-backport.sh version 16.0.0.6848
find the latest version at https://github.com/ceph/ceph/blob/main/src/script/ceph-backport.sh

### CODE REVIEW

**Comment by cbodley** [comment]
thanks @kchheda3 

the jenkins check caught some compilation errors:
```
src/rgw/rgw_lc.cc:626:20: error: no member named 'get_size' in 'rgw::sal::Object'
  auto size = obj->get_size();
              ~~~~~^
src/rgw/rgw_lc.cc:914:28: error: no member named 'get_size' in 'rgw::sal::Object'
      auto size = sal_obj->get_size();
                  ~~~~~~~~~^
src/rgw/rgw_lc.cc:1432:22: error: no member named 'get_size' in 'rgw::sal::Object'
    auto size = obj->get_size();
                ~~~~~^
src/rgw/rgw_lc.cc:1448:44: error: no member named 'ObjectTransitionNonCurrent' in namespace 'rgw::notify'; did you mean 'ObjectTransitionNoncurrent'?
        event_types.push_back(rgw::notify::ObjectTransitionNonCurrent);
                              ~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~
                                           ObjectTransitionNoncurrent
src/rgw/rgw_notify_event_type.h:27:5: note: 'ObjectTransitionNoncurrent' declared here
    ObjectTransitionNoncurrent           = 0x2000,
    ^
4 errors generated.
```

**Comment by yuvalif** [comment]
```
src/rgw/rgw_lc.cc:1448:44: error: no member named 'ObjectTransitionNonCurrent' in namespace 'rgw::notify'; did you mean 'ObjectTransitionNoncurrent'?
        event_types.push_back(rgw::notify::ObjectTransitionNonCurrent);
                              ~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~
                                           ObjectTransitionNoncurrent
src/rgw/rgw_notify_event_type.h:27:5: note: 'ObjectTransitionNoncurrent' declared here
    ObjectTransitionNoncurrent           = 0x2000,
    ^
```
the above should be resolved once https://tracker.ceph.com/issues/59488 is backported

**Comment by cbodley** [comment]
probably best to include the backport of https://github.com/ceph/ceph/pull/57319 in this pr. what do you think @kchheda3?

**Comment by cbodley** [comment]
ping @kchheda3 @yuvalif @TRYTOBE8TME

**Comment by cbodley** [comment]
jenkins test make check

**Review by cbodley — APPROVED** [review]

**Comment by yuriw** [comment]
jenkins test make check

**Comment by cbodley** [comment]
jenkins test make check

**Comment by yuvalif** [comment]
jenkins test make check

**Pull request merged**
