### PR TITLE
osd: add filestore_erasurepool_write_cache_dontneed in config_opts.h

### PR DESCRIPTION
**Pull request by majianpeng**
For erasure pool, it mainly contain cool data. So add this option to make
after writing erasurepool the fs cache don't cache data.
Signed-off-by: Jianpeng Ma <jianpeng.ma@intel.com>

### CODE REVIEW

**Comment by liewegas** [comment]
I wonder if it makes sense to add a 'flags' field to pg_pool_t and define a flag there. That way this can be controlled on a per-pool basis via the mon?  I think that will be more flexible, not that much more complex, and will make it easy to add other options like this in the future...

**Comment by liewegas** [comment]
Oh, we already have a flags field.  Let's add it there? See
<pre>
  enum {
    FLAG_HASHPSPOOL = 1<<0, // hash pg seed and pool together (instead of adding)
    FLAG_FULL       = 1<<1, // pool is full
    FLAG_DEBUG_FAKE_EC_POOL = 1<<2, // require ReplicatedPG to act like an EC pg
    FLAG_INCOMPLETE_CLONES = 1<<3, // may have incomplete clones (bc we are/were an overlay)
  };
</pre>
The complex bit is the interface on teh mon to set/clear these.  I think we should probably mirror the way hashpspool is done w/ 'ceph osd pool set hashpspool true|false'.  (The other flags are internally managed and not user-facing.)

**Comment by majianpeng** [comment]
@liewegas . By your suggestion, add command by 'ceph osd pool set' which can set pool with write-with-fadvise-dontneed. Please review!

**Comment by liewegas** [comment]
Do you think that we still need the config option when the pool flag is there?  I'm more inclined to document setting the flag on cold pools (whether they are erasure coded or not) as part of the set up process but don't have super strong feelings.. what does everyone else think?

**Comment by majianpeng** [comment]
@liewegas. updated by your suggestion. Thanks very much!

**Comment by liewegas** [comment]
With @majianpeng's comment about the flags fixed I think this looks good.  The other missing piece is something in the test suite that exercises this code.

Can you add something to ceph-qa-suite.git/tasks/rados.py that will set this flag based on a bool in the yaml, and if it's not present, enable it for ec pools?  Then we can modify a couple of the test cases in ceph-qa-suite.git/suites/rados/thrash/workloads/* to set it for replicated pools and not set it for ec pools so that we get full coverage.  Please open a pull request against ceph-qa-suite.git and link to it from here so @athanatos can include it with his test run before merging.  Thanks!

**Comment by liewegas** [comment]
Reviewed-by:

**Comment by majianpeng** [comment]
@liewegas . Search test case don't find problem. In test case it only use LIBRADOS_OP_FLAG_. And find a comment error.  I'll do the related work about ceph-qa-suite.git. Thanks!

**Comment by majianpeng** [comment]
@liewegas & @athanatos  https://github.com/ceph/ceph-qa-suite/pull/296.

**Comment by liewegas** [comment]
can you rebase and squash these fixes in?

<pre>
diff --git a/src/osd/osd_types.h b/src/osd/osd_types.h
index b158056..4a018c3 100644
--- a/src/osd/osd_types.h
+++ b/src/osd/osd_types.h
@@ -870,6 +870,8 @@ struct pg_pool_t {
       return FLAG_NOPGCHANGE;
     if (name == "nosizechange")
       return FLAG_NOSIZECHANGE;
+    if (name == "write_fadvise_dontneed")
+      return FLAG_WRITE_FADVISE_DONTNEED;
     return 0;
   }
 
diff --git a/src/test/osd/RadosModel.h b/src/test/osd/RadosModel.h
index f2e944f..f9c0f9b 100644
--- a/src/test/osd/RadosModel.h
+++ b/src/test/osd/RadosModel.h
@@ -237,7 +237,7 @@ public:
     bufferlist inbl;
     r = rados.mon_command(
       "{\"prefix\": \"osd pool set\", \"pool\": \"" + pool_name +
-      "\", \"write_fadvise_dontneed\": \"" + (write_fadvise_dontneed ? "true" : "false") + "\"}",
+      "\", \"var\": \"write_fadvise_dontneed\", \"val\": \"" + (write_fadvise_dontneed ? "true" : "false") + "\"}",
       inbl, NULL, NULL);
     if (r < 0) {
       rados.shutdown();
</pre>

**Comment by majianpeng** [comment]
@liewegas . Updated & please review ! Thanks!

**Pull request merged**
