### PR TITLE
osd: force an upgrade stop at hammer

### PR DESCRIPTION
**Pull request by liewegas**
This guard against a scenario like:

 - user runs firefly or giant
 - user upgrades directly to hammer++
 - latest ceph-osd upgrades filestore
 - osd tries to join cluster and fails because it is missing various
   features
 - user cannot downgrade to hammer because data store has been upgraded to
   post-hammer format.

I'm not sure what those new features might be yet, but if we want to require
a stop at hammer (which will simplify our lives and make testing more constrained)
then we should enforce it.

One thing this doesn't do is prevent a post-hammer OSD from joining the cluster
when there are pre-hammer peers.  To do that we can gate joining on the PGMETA
feature, but we need a post-hammer feature to indicate that we should make that
requirement first.

### CODE REVIEW

**Comment by dachary** [comment]
I suspect jenkins failed because of a rebase. Rebasing and repushing will trigger it again.

**Comment by liewegas** [comment]
@athanatos This now has the osd start gating in there.. ready for review!

**Comment by liewegas** [comment]
manual tests w/ yuri confirm this is working as expected.

**Comment by liewegas** [comment]
@athanatos okay this has passed upgrade tests.  Can't remember if you actually reviewed it though!  When you have please merge.

The hammer piece is merged into the wip-12536-hammer branch, waiting on the 0.94.3.

**Comment by liewegas** [comment]
@athanatos er nevermind, still need to test firefly>hammer>x

**Comment by athanatos** [comment]
lgtm

**Comment by liewegas** [comment]
merged manually to resolve a conflict

**Pull request merged**
