### PR TITLE
[DNM] doc: fix invalid code-like section that would not render

### PR DESCRIPTION
**Pull request by alfredodeza**
Signed-off-by: Alfredo Deza <adeza@redhat.com>

### CODE REVIEW

**Comment by alfredodeza** [comment]
jenkins test docs

**Comment by alfredodeza** [comment]
jenkins test docs

**Comment by alfredodeza** [comment]
YASSSSS

**Comment by alfredodeza** [comment]
jenkins test docs

**Comment by alfredodeza** [comment]
jenkins test docs

**Comment by alfredodeza** [comment]
jenkins test docs

**Comment by alfredodeza** [comment]
jenkins test this please

**Comment by alfredodeza** [comment]
jenkins test docs

**Comment by alfredodeza** [comment]
jenkins test docs

**Comment by liewegas** [comment]
This sectoin has been rewritten

**Pull request closed without merging**
