### PR TITLE
mgr/volumes/fs/operations/group.py: add extra blank line

### PR DESCRIPTION
**Pull request by Astroakanksha24**
Fixes:https://tracker.ceph.com/issues/51393
Signed-off-by: Akanksha Chaudhari <astroakanksha24@gmail.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by varshar16** [comment]
jenkins test make check

**Comment by ideepika** [comment]
jenkins test make check

**Review by varshar16 — APPROVED** [review]
Looks good! Thank you Akansha for your contribution.

**Comment by tchaikov** [comment]
https://pulpito.ceph.com/kchai-2021-07-26_12:44:08-rados-wip-kefu-testing-2021-07-26-1839-distro-basic-smithi/

**Pull request merged**
