### PR TITLE
hammer: client: added permission check based on getgrouplist

### PR DESCRIPTION
**Pull request by ukernel**
http://tracker.ceph.com/issues/13809

### CODE REVIEW

**Comment by dachary** [comment]
@ukernel 71eea34 is not an exact cherry pick of https://github.com/ceph/ceph/commit/f04c8da5432174874ca97d11a5b2fef56f95d73d. When this is the case, there needs to be an explanation for the difference after the (cherry picked from...) line. Thanks :-)

**Comment by dachary** [comment]
Actually if I read correctly, this commit is the agreggation of two commits : 16b59c6cd68d532a47e8c0e7b1f088b41433f048 and f04c8da5432174874ca97d11a5b2fef56f95d73d

**Comment by dachary** [comment]
@ukernel thanks ! Would you be so kind as to rebase this pull request ? That will fix the (unrelated to your work) make check failure.

**Comment by dachary** [comment]
@gregsfortytwo does this backport look good to merge ? It passed a run of the hammer fs suite ( see http://tracker.ceph.com/issues/14692#note-25 for details ) except one test which does not seem to be related (http://pulpito.ceph.com/loic-2016-03-01_20:26:33-fs-hammer-backports---basic-multi/36755/).

**Comment by dachary** [comment]
@ukernel could you please rebase to get a clean make check run ?

**Comment by gregsfortytwo** [comment]
Looks fine to me @dachary

**Pull request merged**
