### PR TITLE
jewel: rgw: Have a flavor of bucket deletion in radosgw-admin to bypass garbage collection

### PR DESCRIPTION
**Pull request by dachary**
http://tracker.ceph.com/issues/16871

### CODE REVIEW

**Comment by dachary** [comment]
http://gitbuilder.sepia.ceph.com/gitbuilder-ceph-rpm-centos7-amd64-basic/log.cgi?log=0709e5e3afda45ef3c9cbff32a9f21c2139ffecd

<pre>
 CXX rgw/librgw_la-rgw_env.lo
CXX rgw/librgw_la-rgw_fcgi.lo
CXX rgw/librgw_la-rgw_formats.lo
rgw/rgw_bucket.cc: In function 'int rgw_remove_bucket_bypass_gc(RGWRados*, rgw_bucket&, int, bool)':

    error: rgw/rgw_bucket.cc:747:12: 'class RGWRados' has no member named 'get_bucket_instance_entry' 

store->get_bucket_instance_entry(bucket, entry);
^
make[3]: *** [rgw/librgw_la-rgw_bucket.lo] Error 1
make[3]: *** Waiting for unfinished jobs....
make[3]: Leaving directory `/srv/autobuild-ceph/gitbuilder.git/build/rpmbuild/BUILD/ceph-10.2.2/src'
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory `/srv/autobuild-ceph/gitbuilder.git/build/rpmbuild/BUILD/ceph-10.2.2/src'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/srv/autobuild-ceph/gitbuilder.git/build/rpmbuild/BUILD/ceph-10.2.2/src'

    make: *** [all-recursive] Error 1 

    error: Bad exit status from /var/tmp/rpm-tmp.vZoIBo (%build) 

</pre>

**Comment by mattbenjamin** [comment]
@dachary  just need:
diff --git a/src/rgw/rgw_bucket.cc b/src/rgw/rgw_bucket.cc
index b6fdc30..c7c5239 100644
--- a/src/rgw/rgw_bucket.cc
+++ b/src/rgw/rgw_bucket.cc
@@ -743,8 +743,7 @@ int rgw_remove_bucket_bypass_gc(RGWRados *store, rgw_bucket& bucket,
 
   if (!store->is_syncing_bucket_meta(bucket)) {
     RGWObjVersionTracker objv_tracker;
-    string entry;
-    store->get_bucket_instance_entry(bucket, entry);
+    string entry = bucket.get_key();
     ret = rgw_bucket_instance_remove_entry(store, entry, &objv_tracker);
     if (ret < 0) {
       lderr(store->ctx()) << "ERROR: could not remove bucket instance entry" << bucket.name << "with ret as " << ret << dendl;

**Comment by dachary** [comment]
thanks, will use that :-)

**Comment by dachary** [comment]
rebased

**Comment by dachary** [comment]
applied the patch suggested at https://github.com/ceph/ceph/pull/10661#issuecomment-250593268

**Comment by dachary** [comment]
jenkins test this please (general jenkins failure)

**Comment by dachary** [comment]
check this please

**Comment by smithfarm** [comment]
This passed an rgw suite at http://tracker.ceph.com/issues/17851#note-50 and http://tracker.ceph.com/issues/17851#note-58

**Comment by smithfarm** [comment]
```
(11:46:45 AM) smithfarm: owasserm: thanks. For jewel integration rgw, then, what it comes down to is verifying that these 6 valgrind failures are all libtcmalloc-related: http://pulpito.front.sepia.ceph.com/smithfarm-2017-01-31_12:35:14-rgw-wip-jewel-backports-distro-basic-smithi/
(11:46:58 AM) smithfarm: owasserm: I will do that now
(11:47:05 AM) owasserm: smithfarm, thanks
(11:47:33 AM) smithfarm: owasserm: and assuming they are tcmalloc related, you said I can directly merge all the rgw PRs? Or do you want me to ask you for review in the PRs first?
(11:47:53 AM) owasserm: smithfarm, yes you can merge them
(11:48:19 AM) smithfarm: ok, will merge and do at least one or two more rgw runs before passing 10.2.6 to QE
```

**Pull request merged**
