### PR TITLE
rbd-nbd: s/cpp_error/cpp_strerror/ to fix FTBFS

### PR DESCRIPTION
**Pull request by tchaikov**
the build failure was introduced by ff4dcf0

Signed-off-by: Kefu Chai <kchai@redhat.com>

### CODE REVIEW

**Comment by tchaikov** [comment]
this fixes https://jenkins.ceph.com/job/ceph-dev-build/ARCH=x86_64,AVAILABLE_ARCH=x86_64,AVAILABLE_DIST=xenial,DIST=xenial,MACHINE_SIZE=huge/6033//consoleFull.

**Comment by dillaman** [comment]
retest this please

**Comment by liupan1111** [comment]
@tchaikov thanks for this fix. But I am curious about why it passed in the jenkins test of my PR?

**Comment by tchaikov** [comment]
@liupan1111 "make check" does not build **all* packaged artifacts. so please make sure your change at least build locally.

**Pull request merged**
