### PR TITLE
Wip orit resharding hammer

### PR DESCRIPTION
**Pull request by oritwas**
Backport of offline resharding command

### CODE REVIEW

**Comment by smithfarm** [comment]
@oritwas Can you add the missing signed-off-bys? Also, are there tests for this feature (under `qa/`) that need backporting as well?

**Comment by oritwas** [comment]
@smithfarm, there no tests for this feature (all tests are manual)

**Comment by smithfarm** [comment]
@oritwas So there's no point in running an RGW suite on it?

**Comment by oritwas** [comment]
@smithfarm , you should run RGW suite as there is a lot of code change in other RGW areas

**Comment by smithfarm** [comment]
OK, rebuilt integration branch - see http://tracker.ceph.com/issues/17151#note-43 - and will run RGW suite on it

**Comment by smithfarm** [comment]
http://pulpito.ceph.com/smithfarm-2017-01-05_20:47:44-rgw-wip-hammer-backports-distro-basic-smithi/

There is at least one failure - @oritwas can you take a look?

**Comment by smithfarm** [comment]
@oritwas Nevermind, it looks like the failure was due to infrastructure noise (`Failed to download key at http://download.ceph.com/keys/autobuild.asc: Request failed: <urlopen error [Errno 101] Network is unreachable>`). I'm re-running the failed job.

**Comment by smithfarm** [comment]
@oritwas This passed an RGW suite at http://tracker.ceph.com/issues/17151#note-44 - OK to merge?

**Comment by smithfarm** [comment]
@oritwas Can you provide a short description of this feature for the hammer 0.94.10 release notes?

**Comment by oritwas** [comment]
@smithfarm , what is the procedure to do that?

**Comment by smithfarm** [comment]
@oritwas There is no procedure that I know of. You could look at the draft release notes at #13152 and add a comment there?

**Pull request merged**
