### PR TITLE
qa/tests:  added $ distro options to krbd suite

### PR DESCRIPTION
**Pull request by yuriw**
Signed-off-by: Yuri Weinstein <yweinste@redhat.com>

### CODE REVIEW

**Comment by yuriw** [comment]
http://pulpito.ceph.com/yuriw-2018-07-23_20:18:25-krbd-mimic-testing-basic-smithi/
@idryomov @dillaman  see OSes

**Comment by yuriw** [comment]
needs `mimic` backport

**Comment by yuriw** [comment]
@idryomov I suspect  `teuthology-suite -d / -D` should override `$`, we don't use `-d` often 
The idea of `$` is to run a suit on a mix of OSes without increasing amount of jobs.  Is it not OK for `krbd` ?

**Comment by idryomov** [comment]
The idea is fine, although I don't see a lot of benefit TBH.  We use -d / -D quite often when running k* suites against external kernel packages, so I need to know for sure.

**Comment by yuriw** [comment]
`$` was implemented and merged awhile ago, so if you did not notice, it's good :)

**Comment by yuriw** [comment]
@idryomov so it's been cooking for awhile, if you don't think we need `$` for `krbd` pls close this

**Comment by idryomov** [comment]
I'm still seeing intermittent centos build failures (http://tracker.ceph.com/issues/24079), which means we don't have rpm kernel packages available for every ceph-client.git commit.  On top of my other concerns, this makes `$` a no go for krbd.

**Pull request closed without merging**
