### PR TITLE
Heavy memory shuffling in rados bench

### PR DESCRIPTION
**Pull request by Abhishekvrshny**
http://tracker.ceph.com/issues/12948

### CODE REVIEW

**Comment by dachary** [comment]
@tchaikov does this backport look good to merge ? It passed a run of the hammer rados suite ( see http://tracker.ceph.com/issues/13356#note-11 and  for details ).

**Comment by tchaikov** [comment]
@Abhishekvrshny do you want to backport #5152 as well?

**Comment by dachary** [comment]
@tchaikov backporting #5152 sound like a good idea. Is there an associated issue or should we create a new one ? Do you think backporting #5152 is a pre-condition to merge this backport ?

**Comment by tchaikov** [comment]
@dachary #5152 was mentioned in http://tracker.ceph.com/issues/12946, but it was not explicitly associated with any issue. i am just concerned that the obj_bencher might report error under some conditions as put by @branch-predictor in the commit message of https://github.com/ceph/ceph/pull/5152/commits . so probably we can merge this pr and keep in mind that we'd better backport https://github.com/ceph/ceph/pull/5152 soon. what do you think?

**Comment by branch-predictor** [comment]
Actually, I made separate issue for backport of #5152 (http://tracker.ceph.com/issues/12947) and the related PR is https://github.com/ceph/ceph/pull/5812.

**Comment by tchaikov** [comment]
thanks @branch-predictor ! lgtm then.

**Pull request merged**
