### PR TITLE
ceph-disk: dmcrypt activate must use the same cluster as prepare

### PR DESCRIPTION
**Pull request by dachary**
When dmcrypt is used, the fsid cannot be retrieved from the data
partition because it is encrypted. Store the fsid in the lockbox to
enable dmcrypt activation using the same logic as regular activation.

The fsid is used to retrive the cluster name that was used during
prepare, reason why activation does not and must not have a --cluster
argument.

Fixes: http://tracker.ceph.com/issues/17821

Signed-off-by: Loic Dachary <ldachary@redhat.com>

### CODE REVIEW

**Comment by dachary** [comment]
https://shaman.ceph.com/builds/ceph/wip-17821-revert/

**Comment by dachary** [comment]
<pre>
teuthology-suite -k distro --verbose --suite ceph-disk --ceph wip-17821-revert --machine-type vps 
</pre>

**running** http://pulpito.ceph.com/loic-2017-02-22_05:31:46-ceph-disk-wip-17821-revert-distro-basic-vps

**Comment by dachary** [comment]
teuthology suite for ceph-disk passes https://github.com/ceph/ceph/pull/13573#issuecomment-281574006

**Comment by dachary** [comment]
There are no specific tests for this change. But it modifies the code path used by every dmcrypt activation and I believe that's enough coverage, via the teuthology ceph-disk suite, to prove it does the right thing.

**Comment by leseb** [comment]
@dachary @vumrao will this be in 10.2.7 by any chance?

**Comment by leseb** [comment]
+ @ktdreyer

**Comment by ktdreyer** [comment]
@leseb the backport is in progress at https://github.com/ceph/ceph/pull/13496 . It looks like Loic has requested changes of the reviewer. If this needs to get into v10.2.7, please work with @shinobu-x on that. At this point in the schedule anything for v10.2.7 must have Pulpito links to successful Teuthology runs demonstrating that the change is safe to take in.

**Pull request merged**
