### PR TITLE
Merge octopus into master

### PR DESCRIPTION
**Pull request by liewegas**

### CODE REVIEW

**Comment by callithea** [comment]
jenkins test dashboard backend

**Comment by callithea** [comment]
The backend API tests failed with:
```
2020-03-23 08:44:49,499.499 INFO:__main__:FAIL: test_minimal_health (tasks.mgr.dashboard.test_health.HealthTest)
2020-03-23 08:44:49,499.499 INFO:__main__:----------------------------------------------------------------------
2020-03-23 08:44:49,500.500 INFO:__main__:Traceback (most recent call last):
2020-03-23 08:44:49,500.500 INFO:__main__:  File "/home/jenkins-build/build/workspace/ceph-dashboard-pr-backend/qa/tasks/mgr/dashboard/test_health.py", line 88, in test_minimal_health
2020-03-23 08:44:49,500.500 INFO:__main__:    self.assertSchema(data, schema)
2020-03-23 08:44:49,500.500 INFO:__main__:  File "/home/jenkins-build/build/workspace/ceph-dashboard-pr-backend/qa/tasks/mgr/dashboard/helper.py", line 369, in assertSchema
2020-03-23 08:44:49,500.500 INFO:__main__:    self.assertEqual(data, str(e))
2020-03-23 08:44:49,500.500 INFO:__main__:AssertionError: {u'df': {u'stats': {u'total_used_raw_bytes': 8606056448, u'total_bytes': 433791664128, u'total_avail_bytes': 425185607680}}, u'osd_map': {u'osds': [{u'up': 1, u'in': 1}, {u'up': 1, u'in': 1}, {u'up': 1, u'in': 1}, [...]
```
Here's the [full log](https://jenkins.ceph.com/job/ceph-dashboard-pr-backend/663/consoleFull).

**Comment by callithea** [comment]
Triggered the dashboard end-to-end tests manually, the build [succeeded](https://jenkins.ceph.com/view/all/job/ceph-dashboard-pull-requests/3600).

**Comment by ukernel** [comment]
LGTM

**Pull request merged**
