### PR TITLE
rgw/iam: refactor OpenIDConnectProvider rest and sal APIs

### PR DESCRIPTION
**Pull request by cbodley**
these commits were part of https://github.com/ceph/ceph/pull/54333 where i go on to add account support to the rest apis

but there's a separate need to support multisite replication of oidc-provider metadata for https://tracker.ceph.com/issues/64431, so i split them because i think the sal changes will make it easier to implement the oidc RGWMetadataHandler

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Review by dang — APPROVED** [review]

**Review by pritha-srivastava — APPROVED** [review]

**Comment by cbodley** [comment]
jenkins test make check

**Comment by ivancich** [comment]
jenkins test make check

**Comment by ivancich** [comment]
jenkins test api

**Comment by cbodley** [comment]
tagged dnm since this is part of https://github.com/ceph/ceph/pull/54333 which will hopefully merge for squid. this pr can be used as a base for oidc metadata sync in the meantime

**Pull request closed without merging**
