### PR TITLE
quincy: Wip nitzan pglog ec getattr error

### PR DESCRIPTION
**Pull request by NitzanMordhai**
backport tracker: https://tracker.ceph.com/issues/58614

---

backport of https://github.com/ceph/ceph/pull/47332
parent tracker: https://tracker.ceph.com/issues/56707

this backport was staged using ceph-backport.sh version 16.0.0.6848
find the latest version at https://github.com/ceph/ceph/blob/main/src/script/ceph-backport.sh

### CODE REVIEW

**Review by neha-ojha — APPROVED** [review]

**Comment by ljflores** [comment]
Hey @NitzanMordhai, there may be a teuthology failure related to the new cls tests you included:

https://pulpito.ceph.com/yuriw-2023-03-07_15:42:49-rados-wip-yuri6-testing-2023-03-06-1200-quincy-distro-default-smithi/

/a/yuriw-2023-03-07_15:42:49-rados-wip-yuri6-testing-2023-03-06-1200-quincy-distro-default-smithi/7196124/teuthology.log
```
2023-03-07T16:13:18.027 DEBUG:teuthology.orchestra.run.smithi032:> sudo egrep '\[ERR\]|\[WRN\]|\[SEC\]' /var/log/ceph/ceph.log | egrep -v '\(MDS_ALL_DOWN\)' | egrep -v '\(MDS_UP_LESS_THAN_MAX\)' | egrep -v '\(OSD_SLOW_PING_TIME' | head -n 1
2023-03-07T16:13:18.085 INFO:teuthology.orchestra.run.smithi032.stdout:2023-03-07T16:11:00.043161+0000 mon.a (mon.0) 502 : cluster [WRN] Health check failed: 1 pool(s) do not have an application enabled (POOL_APP_NOT_ENABLED)
2023-03-07T16:13:18.085 WARNING:tasks.ceph:Found errors (ERR|WRN|SEC) in cluster log
2023-03-07T16:13:18.086 DEBUG:teuthology.orchestra.run.smithi032:> sudo egrep '\[SEC\]' /var/log/ceph/ceph.log | egrep -v '\(MDS_ALL_DOWN\)' | egrep -v '\(MDS_UP_LESS_THAN_MAX\)' | egrep -v '\(OSD_SLOW_PING_TIME' | head -n 1
2023-03-07T16:13:18.154 DEBUG:teuthology.orchestra.run.smithi032:> sudo egrep '\[ERR\]' /var/log/ceph/ceph.log | egrep -v '\(MDS_ALL_DOWN\)' | egrep -v '\(MDS_UP_LESS_THAN_MAX\)' | egrep -v '\(OSD_SLOW_PING_TIME' | head -n 1
2023-03-07T16:13:18.223 DEBUG:teuthology.orchestra.run.smithi032:> sudo egrep '\[WRN\]' /var/log/ceph/ceph.log | egrep -v '\(MDS_ALL_DOWN\)' | egrep -v '\(MDS_UP_LESS_THAN_MAX\)' | egrep -v '\(OSD_SLOW_PING_TIME' | head -n 1
2023-03-07T16:13:18.292 INFO:teuthology.orchestra.run.smithi032.stdout:2023-03-07T16:11:00.043161+0000 mon.a (mon.0) 502 : cluster [WRN] Health check failed: 1 pool(s) do not have an application enabled (POOL_APP_NOT_ENABLED)
```
/a/yuriw-2023-03-07_15:42:49-rados-wip-yuri6-testing-2023-03-06-1200-quincy-distro-default-smithi/7196124/remote/smithi032/log/ceph-mon.a.log.gz
```
2023-03-07T16:10:59.780+0000 7f5767cf5700 20 mon.a@0(leader).mgrstat health checks:
{
    "POOL_APP_NOT_ENABLED": {
        "severity": "HEALTH_WARN",
        "summary": {
            "message": "1 pool(s) do not have an application enabled",
            "count": 1
        },
        "detail": [
            {
                "message": "application not enabled on pool 'test-rados-api-smithi032-117300-8'"
            },
            {
                "message": "use 'ceph osd pool application enable <pool-name> <app-name>', where <app-name> is 'cephfs', 'rbd', 'rgw', or freeform for custom applications."
            }
        ]
    }
}
```

**Comment by NitzanMordhai** [comment]
> Hey @NitzanMordhai, there may be a teuthology failure related to the new cls tests you included:
> 
> https://pulpito.ceph.com/yuriw-2023-03-07_15:42:49-rados-wip-yuri6-testing-2023-03-06-1200-quincy-distro-default-smithi/
> 
> /a/yuriw-2023-03-07_15:42:49-rados-wip-yuri6-testing-2023-03-06-1200-quincy-distro-default-smithi/7196124/teuthology.log

I didn't notice that create_one_ec_pool_pp doesn't enable application like create_one_pool_pp doing. Fixed

**Review by ljflores — APPROVED** [review]

**Comment by ljflores** [comment]
jenkins test make check

**Comment by yuriw** [comment]
@NitzanMordhai this is ready for merge

ref: https://trello.com/c/llcQOKAa

**Comment by yuriw** [comment]
jenkins test make check

**Review by rzarzynski — APPROVED** [review]

**Pull request merged**
