### PR TITLE
pacific: doc/cephfs/add-remove-mds: added cephadm note, refined "Adding an MDS"

### PR DESCRIPTION
**Pull request by dparmar18**
Backport tracker: https://tracker.ceph.com/issues/55238
Backport of https://github.com/ceph/ceph/pull/45639

Description: 

- Add a note about using cephadm for setting up the cluster and mds(s), mention
the use of ceph orchestrator if one needs to setup mds(s) manually.
- Changed the term data point to directory in point 1 under "Adding an MDS"
section for better clarity.

Fixes: https://tracker.ceph.com/issues/54551

Signed-off-by: Dhairya Parmar <dparmar@redhat.com>

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by kotreshhr** [comment]
jenkins retest this please

**Review by kotreshhr — COMMENTED** [review]
I don't see 'cherry picked from commit ' in the commit message. Didn't you cherry-pick this from the master commit ?

We do `git cherry-pick -x <master-commit>` for backports

**Comment by dparmar18** [comment]
> I don't see 'cherry picked from commit ' in the commit message. Didn't you cherry-pick this from the master commit ?
> 
> We do `git cherry-pick -x <master-commit>` for backports

@kotreshhr, sorry I didn't add the 'cherry picked from commit <commit_sha>' in the commit message but now it's added.

**Review by kotreshhr — APPROVED** [review]

**Comment by dparmar18** [comment]
jenkins test docs

**Comment by dparmar18** [comment]
jenkins render docs

**Review by anthonyeleven — CHANGES_REQUESTED** [review]
Please capitalize Ceph in the first chunk and uppercase MDS in the second.

**Comment by dparmar18** [comment]
> Please capitalize Ceph in the first chunk and uppercase MDS in the second.

@anthonyeleven Done, do comment for any further change.

**Review by anthonyeleven — APPROVED** [review]

**Comment by anthonyeleven** [comment]
"only uses" is a bit "boldly go" but that's pre-existing and even I am not that pedantic.  At least not tonight ;)

The first check below is failing because the second commit isn't signed.  And the project likes to have commits squashed before or at merge.  If you could squash your two commits with the signed-off-by already in the first commit message, I think that would unlock the first check and this could then be merged.

**Comment by dparmar18** [comment]
> "only uses" is a bit "boldly go" but that's pre-existing and even I am not that pedantic. At least not tonight ;)
> 
> The first check below is failing because the second commit isn't signed. And the project likes to have commits squashed before or at merge. If you could squash your two commits with the signed-off-by already in the first commit message, I think that would unlock the first check and this could then be merged.



> "only uses" is a bit "boldly go" but that's pre-existing and even I am not that pedantic. At least not tonight ;)
> 
> The first check below is failing because the second commit isn't signed. And the project likes to have commits squashed before or at merge. If you could squash your two commits with the signed-off-by already in the first commit message, I think that would unlock the first check and this could then be merged.

@anthonyeleven, I'm not sure about rewording "only uses" to something else as I don't want to touch the pre-existing data. but did squash the commit, should pass now.

**Comment by anthonyeleven** [comment]
.. and now other tests are failing.  I wonder if `master` is starting to be renamed to `main`

**Comment by anthonyeleven** [comment]
Oh feh.  I just noticed that this is a backport of 45639, my mistake.  I think standard practice is to not add changes in backport PRs, so if I could timidly ask you to revert the changes I asked for, I think it'll pass again.

**Comment by anthonyeleven** [comment]
Apologies for the mixup, backports are beyond my ken and I need to read more closely.  That said, I don't think the readthedocs failure is anything you did.  There have been plans to rename `master` to `main` but I haven't been sure when that will happen, and I don't know if that's involved here.  @zdover23 any thoughts?

**Comment by dparmar18** [comment]
> Apologies for the mixup, backports are beyond my ken and I need to read more closely. That said, I don't think the readthedocs failure is anything you did. There have been plans to rename `master` to `main` but I haven't been sure when that will happen, and I don't know if that's involved here. @zdover23 any thoughts?

No issues, I can understand. readthedocs is something I'm not very sure of but yeah It wasn't triggered by me.

**Review by rishabh-d-dave — APPROVED** [review]

**Comment by anthonyeleven** [comment]
jenkins test docs

**Comment by anthonyeleven** [comment]
Digging deeper I think the `readthedocs` repository itself renamed the branch.  I'll work to address that.

**Comment by anthonyeleven** [comment]
jenkins render docs

**Comment by anthonyeleven** [comment]
jenkins test docs

**Comment by rishabh-d-dave** [comment]
@anthonyeleven That doc CI job can't be retriggered by a command. Branch needs to be re-pushed, 

@dparmar18 The doc CI job has crashed. The issue is most likely irrelevant. Can you push after running `git commit --amend --no-edit` locally?

**Comment by dparmar18** [comment]
> @anthonyeleven That doc CI job can't be retriggered by a command. Branch needs to be re-pushed,
> 
> @dparmar18 The doc CI job has crashed. The issue is most likely irrelevant. Can you push after running `git commit --amend --no-edit` locally?

@rishabh-d-dave I'll do it

**Comment by dparmar18** [comment]
> > @anthonyeleven That doc CI job can't be retriggered by a command. Branch needs to be re-pushed,
> > @dparmar18 The doc CI job has crashed. The issue is most likely irrelevant. Can you push after running `git commit --amend --no-edit` locally?
> 
> @rishabh-d-dave I'll do it

It still failed

**Comment by rishabh-d-dave** [comment]
@dparmar18 Perhaps @djgalloway meant to rebase this PR branch since it's far away from latest origin/pacific...

**Comment by anthonyeleven** [comment]
> You can ignore the `docs/readthedocs.org:ceph — Read the Docs build failed!`
> 
> It's been broken for weeks.

Aye, I've seen that with other Pacific PRs and have discussed the phenomenon with @zdover23 .  This is the first time I've seen the ability to merge anyway.

**Pull request merged**
