### PR TITLE
qa: relocate subvol creation overrides and test

### PR DESCRIPTION
**Pull request by mchangir**
To avoid test jobs list to grow beyond snap-schedule.

Fixes: https://tracker.ceph.com/issues/65829
Signed-off-by: Milind Changire <mchangir@redhat.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [x] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Review by batrick — CHANGES_REQUESTED** [review]
```
2024-05-17 01:04:14,985.985 INFO:teuthology.suite:Using random seed=6174
2024-05-17 01:04:14,986.986 INFO:teuthology.suite.run:kernel sha1: distro
2024-05-17 01:04:15,228.228 INFO:teuthology.suite.run:ceph sha1 explicitly supplied
2024-05-17 01:04:15,228.228 INFO:teuthology.suite.run:ceph sha1: 81a3c1e6c488116ab9844fe5ad8db3ce6128ccce
2024-05-17 01:04:16,423.423 INFO:teuthology.suite.run:ceph version: 19.0.0-3722.g81a3c1e6
2024-05-17 01:04:16,686.686 INFO:teuthology.suite.run:ceph branch: mds-snap_schedule-relocate-test-and-overrides-to-correct-location 6d6374ca98bd0b09a5d709e1ee6821fcffd9503e
2024-05-17 01:04:16,690.690 INFO:teuthology.repo_utils:Cloning https://github.com/mchangir/ceph.git mds-snap_schedule-relocate-test-and-overrides-to-correct-location from upstream
2024-05-17 01:04:30,399.399 INFO:teuthology.suite.run:teuthology branch: main a771c3cd04bbdbdd87e898bc8a2abe9d693c14db
Traceback (most recent call last):
  File "/cephfs/home/pdonnell/teuthology/virtualenv/bin/teuthology-suite", line 8, in <module>
    sys.exit(main())
  File "/cephfs/home/pdonnell/teuthology/scripts/suite.py", line 226, in main
    return teuthology.suite.main(args)
  File "/cephfs/home/pdonnell/teuthology/teuthology/suite/__init__.py", line 145, in main
    run.prepare_and_schedule()
  File "/cephfs/home/pdonnell/teuthology/teuthology/suite/run.py", line 438, in prepare_and_schedule
    num_jobs = self.schedule_suite()
  File "/cephfs/home/pdonnell/teuthology/teuthology/suite/run.py", line 587, in schedule_suite
    configs = build_matrix(suite_path,
  File "/cephfs/home/pdonnell/teuthology/teuthology/suite/build_matrix.py", line 62, in build_matrix
    mat, first, matlimit = _get_matrix(path, subset, no_nested_subset)
  File "/cephfs/home/pdonnell/teuthology/teuthology/suite/build_matrix.py", line 72, in _get_matrix
    mat = _build_matrix(path, no_nested_subset=no_nested_subset)
  File "/cephfs/home/pdonnell/teuthology/teuthology/suite/build_matrix.py", line 132, in _build_matrix
    submat = _build_matrix(
  File "/cephfs/home/pdonnell/teuthology/teuthology/suite/build_matrix.py", line 152, in _build_matrix
    submat = _build_matrix(
  File "/cephfs/home/pdonnell/teuthology/teuthology/suite/build_matrix.py", line 80, in _build_matrix
    raise IOError('%s does not exist (abs %s)' % (path, os.path.abspath(path)))
OSError: /cephfs/home/pdonnell/src/github.com_mchangir_ceph_mds-snap_schedule-relocate-test-and-overrides-to-correct-location/qa/suites/fs/functional/subvol_versions/create_subvol_version_v1.yaml does not exist (abs /cephfs/home/pdonnell/src/github.com_mchangir_ceph_mds-snap_schedule-relocate-test-and-overrides-to-correct-location/qa/suites/fs/functional/subvol_versions/create_subvol_version_v1.yaml)
```

checked out your commit:

```
$ ls qa/suites/fs/functional/subvol_versions/
create_subvol_version_v1.yaml  create_subvol_version_v2.yaml
```

oops?

By the way, I think you need a `%` in this new test_snap_schedule directory. Please give it a try before requesting a new a review.

**Comment by mchangir** [comment]
> ping @mchangir

sorry about the trouble
I didn't mean to ask you to test this change
I just couldn't tell what I did was correct
the teuthology tree layout never ceases to confuse me
I just needed guidance on the file layout

**Comment by mchangir** [comment]
* rebased
* converted to draft PR
* testing in progress

**Comment by mchangir** [comment]
I've executed a dry-run of the `teuthology-suite` command and there are no errors thrown. The `$` operator also does the job of randomly choosing either of the YAMLs. Also, the `%` operator has been appropriately placed in the `test_snap_schedule` dir.

**Comment by mchangir** [comment]
rebased

**Comment by mchangir** [comment]
This PR is under test in [https://tracker.ceph.com/issues/67832](https://tracker.ceph.com/issues/67832).

**Comment by mchangir** [comment]
Testing completed
[Only 6 jobs spawned](https://pulpito.ceph.com/mchangir-2024-08-30_13:43:46-fs-wip-mchangir-testing-20240830.082048-main-debug-distro-default-smithi/) as expected without any `--limit` argument.

1 failing job has no relation with the PR.

**Comment by mchangir** [comment]
jenkins test api

**Comment by mchangir** [comment]
jenkins test api

**Comment by mchangir** [comment]
@vshankar This PR is ready for merge.
As for the conflicting file issue, the file has been relocated into a subdir of the `tasks/` dir. There were no conflicts detected by git during the rebase either. The tests have already passed with the new changes seen in the yaml fragments.

**Comment by mchangir** [comment]
@batrick please take a look at https://github.com/ceph/ceph/pull/57459#issuecomment-2322012236

**Comment by mchangir** [comment]
rebased

**Review by batrick — APPROVED** [review]

**Review by rishabh-d-dave — APPROVED** [review]
LGTM.

Just a small note: This PR adds directory `test_snap_schedule` which stands out, since the convention in `qa/fs/functional/tasks` directory is to have same name as Python test file after removing prefix `test_`. Example `admin` for `test_admin.py` and `volumes` for `test_volumes.py`. 

Since this PR has already been tested, let's not delay the merge and perhaps make this change on a separate PR.

**Comment by rishabh-d-dave** [comment]
> This PR is under test in https://tracker.ceph.com/issues/67832.

Leaving link to this QA run comment here for future reference - https://github.com/ceph/ceph/pull/57459#issuecomment-2320461668

**Pull request merged**
