### PR TITLE
Move code from .h into .cc

### PR DESCRIPTION
**Pull request by amirv**
Hi,

This pull request has some cosmetic changes to the RDMA code.
It has only copy-paste stuff (Except the last small patch) to make it easy to review.

last patch fixes a warning which is actually a small bug.

Thanks,
Amir

### CODE REVIEW

**Comment by amirv** [comment]
Adding @Adirl

**Comment by Adirl** [comment]
@yuyuyu101 pls take a look 
this is preparation for RDMA-CM

**Comment by yuyuyu101** [comment]
hmm, it's ok to me.. but I don't why we need to move all tiny implementation to .cc?

**Comment by amirv** [comment]
Thanks @yuyuyu101 

I moved only multiline functions to the .cc
At least in gvim, it makes things much clearer and easy to work on this way.

**Pull request merged**
