### PR TITLE
os/bluestore: cut down the bluefs compact frequency

### PR DESCRIPTION
**Pull request by liangmingyuanneo**
In https://github.com/ceph/ceph/pull/35473,  adding compact judgement in flush and fsync of bluefs, which leading to more bluefs log compact. In fact, besides sync_metadata, one log compact daily is enough in fsync. And there is no need to call compact function in flush as a result of compact in fsync daily.

Signed-off-by: Mingyuan Liang <liangmingyuan@baidu.com>

### CODE REVIEW

**Comment by liangmingyuanneo** [comment]
ping @ifed01

**Review by aclamk — COMMENTED** [review]
1) The function `_maybe_compact_log()` still checks if compaction is needed; calling it frequently is not a big problem.
2) Compaction of BlueFS log is very quick process. It simply writes to the disk the state of BlueFS that is held in memory - it takes <1ms to execute + time for disk to actually get the data.
3) 
In high IO OSDs it is typical to have RocksDB submit a transaction every 10ms.
Usually size of disk block is 4K. This means that every time we append something to BlueFS log, 4K has to be written.
Lets compute how much disk will be necessary:
1day * 24h/1day * 60min/h * 60s/min * 1000ms/s * 4KB/10ms = (google) = 34.56 gigabytes
This is obviously too much.
It means we must relay on other event sources to invoke `_maybe_compact_log()`
The only source left is `BlueFS::sync_metadata()`, which in turn is invoked (except tools/mount/umount) only by our wrapper of RocksDB:
- Directory::Fsync()
- ReuseWritableFile()
- DeleteFile()
- RenameFile()
How certain are we that these events will happen often enough so BlueFS log will not grow too large?

**Comment by liangmingyuanneo** [comment]
> 1. The function `_maybe_compact_log()` still checks if compaction is needed; calling it frequently is not a big problem.
> 2. Compaction of BlueFS log is very quick process. It simply writes to the disk the state of BlueFS that is held in memory - it takes <1ms to execute + time for disk to actually get the data.
> 
> In high IO OSDs it is typical to have RocksDB submit a transaction every 10ms. Usually size of disk block is 4K. This means that every time we append something to BlueFS log, 4K has to be written. Lets compute how much disk will be necessary: 1day * 24h/1day * 60min/h * 60s/min * 1000ms/s * 4KB/10ms = (google) = 34.56 gigabytes This is obviously too much. It means we must relay on other event sources to invoke `_maybe_compact_log()` The only source left is `BlueFS::sync_metadata()`, which in turn is invoked (except tools/mount/umount) only by our wrapper of RocksDB:
> 
> * Directory::Fsync()
> * ReuseWritableFile()
> * DeleteFile()
> * RenameFile()
>   How certain are we that these events will happen often enough so BlueFS log will not grow too large?

**Comment by liangmingyuanneo** [comment]
> 1. The function `_maybe_compact_log()` still checks if compaction is needed; calling it frequently is not a big problem.
> 2. Compaction of BlueFS log is very quick process. It simply writes to the disk the state of BlueFS that is held in memory - it takes <1ms to execute + time for disk to actually get the data.
> 
> In high IO OSDs it is typical to have RocksDB submit a transaction every 10ms. Usually size of disk block is 4K. This means that every time we append something to BlueFS log, 4K has to be written. Lets compute how much disk will be necessary: 1day * 24h/1day * 60min/h * 60s/min * 1000ms/s * 4KB/10ms = (google) = 34.56 gigabytes This is obviously too much. It means we must relay on other event sources to invoke `_maybe_compact_log()` The only source left is `BlueFS::sync_metadata()`, which in turn is invoked (except tools/mount/umount) only by our wrapper of RocksDB:
> 
> * Directory::Fsync()
> * ReuseWritableFile()
> * DeleteFile()
> * RenameFile()
>   How certain are we that these events will happen often enough so BlueFS log will not grow too large?

Thank you for your review and reply very much. In my opinion, rocksdb will call Directory::Fsync() after SwitchMemtable(), that means sync_metadata() will be called every time a rocksdb memtable is flushed to sst file. In high IO, a 64MB memtable can be written fast, so there will not be large BlueFS log in this scene. For free cluster that no requests for long times, maybe half of a year, compact bluefs log once a day is enough to avoid large BlueFS log too.
For now, every time we flush data to disk, the function _maybe_compact_log() is called once, that costs little CPU. In other hand, in our nvme tests, compact() still be called frequently in spite of we have _maybe_compact_log(). So I think though Compaction of BlueFS log is quick process, it will be better to control its frequency without harm.

**Pull request closed without merging**
