### PR TITLE
osd: combine unstable stats with info.stats when publish stats to osd

### PR DESCRIPTION
**Pull request by LiumxNL**
fix no io stat shows in "ceph -s" output when doing read only

Signed-off-by: Mingxin Liu <mingxin@xsky.com>

### CODE REVIEW

**Comment by LiumxNL** [comment]
@tchaikov @liewegas pls review, thanks!

**Comment by liewegas** [comment]
This looks reasonable, but we may want to wait until we have stats going  to mgr instead of the mon.  I seem to remember being sloppy about this in the past, having problems, and eventually switching to  a much stricter model.. but I don't remember the details.  Can you look back in the history a bit and see if there was a specific change to only report stable stats, or has it always been that way?

**Comment by LiumxNL** [comment]
@liewegas this appear after a more stricter publish model made by commit 97c1881378483b82437fb8f20732598920b1d2e5

**Comment by yuriw** [comment]
http://pulpito.ceph.com/yuriw-2017-03-22_21:32:35-rados-wip-yuri-testing_2017_3_23-distro-basic-smithi/

**Pull request merged**
