### PR TITLE
nautilus: mgr/volumes: add CephFS subvolumes library

### PR DESCRIPTION
**Pull request by smithfarm**
https://tracker.ceph.com/issues/39934
https://tracker.ceph.com/issues/40157
https://tracker.ceph.com/issues/40158

### CODE REVIEW

**Comment by smithfarm** [comment]
An example of two backports ganged up together in a single PR...

**Comment by smithfarm** [comment]
@batrick This PR contains just two of what appear to be several follow-up commits to f37cca105d019243bea4d8d7e42bf57cea659ecc

**Comment by batrick** [comment]
> @batrick @ajarr This PR contains just two of what appear to be several follow-up commits to [f37cca1](https://github.com/ceph/ceph/commit/f37cca105d019243bea4d8d7e42bf57cea659ecc)
> 
> I'm a little concerned that I'm now applying these commits to nautilus in the wrong order, and thereby unwittingly setting us up for cherry-pick conflicts later on, should we decide more cherry-picks are needed.
> 
> In cases like this, opening tracker tickets for each and every change might be less productive than backporting the whole feature all at once after waiting for the feature to stabilize in master/octopus?

Well, I'm too blame for the split of the volume work into several PRs. There were a few reasons for that and ease of backporting was supposed to be one of them. If this is getting painful, I would suggest having @ajarr take over with a PR that incrementall applies fixes merged into master for this project.

**Comment by smithfarm** [comment]
@batrick The system we have in place for tracking backports works nicely (and was designed) for atomic bug fixes that are implemented by single master tracker + master PR. It works less nicely (and was not designed) for feature backports implemented as a series of commits to master, all of which need to be cherry-picked in a particular order if the feature is to be backported to a stable branch.

In fact, in the latter case the "system" becomes a liability, since the feature commits end up being backported in a random order and naive attempts at conflict resolution can introduce new bugs into the stable version that aren't present in master.

**Comment by batrick** [comment]
ACK, thanks Nathan

**Comment by ajarr** [comment]
I've PR https://github.com/ceph/ceph/pull/28429 that redoes this backport.

**Pull request closed without merging**
