### PR TITLE
nautilus: osd/PeeringState: transit async_recovery_targets back into acting before backfilling

### PR DESCRIPTION
**Pull request by smithfarm**
backport tracker: https://tracker.ceph.com/issues/43469

---

backport of https://github.com/ceph/ceph/pull/32202
parent tracker: https://tracker.ceph.com/issues/43311

this backport was staged using ceph-backport.sh version 15.0.0.6950
find the latest version at https://github.com/ceph/ceph/blob/master/src/script/ceph-backport.sh

### CODE REVIEW

**Comment by neha-ojha** [comment]
See https://github.com/ceph/ceph/pull/32202#issuecomment-568690135 - we should let it bake in master a little longer

**Comment by smithfarm** [comment]
@xiexingguo @neha-ojha How much is "a little longer"? Can you give me a date when this should be unblocked?

**Comment by xiexingguo** [comment]
@smithfarm It is not a critical bug and hence of low priority. I would wait a little longer, e.g., after the octopus is out, by which point it should have got enough exercises and should be safe to go.

**Comment by tchaikov** [comment]
- http://pulpito.ceph.com/kchai-2020-03-28_02:15:06-rados-nautilus-kefu2-testing-2020-03-27-2234-distro-basic-smithi/
- http://pulpito.ceph.com/kchai-2020-03-28_06:47:46-rados-nautilus-kefu2-testing-2020-03-28-1208-distro-basic-smithi/
- http://pulpito.ceph.com/kchai-2020-03-28_09:26:23-rados-nautilus-kefu2-testing-2020-03-28-1555-distro-basic-smithi/
- http://pulpito.ceph.com/kchai-2020-03-28_10:21:26-rados-nautilus-kefu2-testing-2020-03-28-1555-distro-basic-smithi/
- http://pulpito.ceph.com/kchai-2020-03-28_11:23:30-rados-nautilus-kefu2-testing-2020-03-28-1555-distro-basic-smithi/

in the end, none of the failures is related to this change.

**Pull request merged**
