### PR TITLE
kraken: mon crash on shutdown, lease_ack_timeout event

### PR DESCRIPTION
**Pull request by asheplyakov**
http://tracker.ceph.com/issues/19928

### CODE REVIEW

**Comment by asheplyakov** [comment]
jenkins retest this please

**Comment by smithfarm** [comment]
Jenkins re-test this please (logs are gone)

**Comment by smithfarm** [comment]
@asheplyakov Please rebase to get rid of the failed Jenkins test called `default`

**Comment by asheplyakov** [comment]
@smithfarm 

> Please rebase to get rid of the failed Jenkins test called default

Done

**Comment by smithfarm** [comment]
Jenkins re-test this please (logs are gone)

**Comment by smithfarm** [comment]
Jenkins re-test this please (Unix domain path too long)

**Comment by smithfarm** [comment]
@jdurgin This passed a rados suite at http://tracker.ceph.com/issues/19009#note-51http://tracker.ceph.com/issues/19009#note-51 with two failures that I believe are unrelated. Please review/approve the PR if you agree it can be merged.

**Pull request merged**
