### PR TITLE
doc/cephadm/services: Add missing ceph command to orch apply commands

### PR DESCRIPTION
**Pull request by bluikko**
In cephadm service management documentation several of the
`ceph orch` commands are missing the `ceph ` part, mostly in
`ceph orch apply` commands but not all of them.

Add `ceph ` in the front of the command to make them consistent
with all other commands.

Signed-off-by: Ville Ojamo <14869000+bluikko@users.noreply.github.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/master/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [x] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [x] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by anthonyeleven** [comment]
Nice catch.  Perhaps a search/replace gone awry?

**Review by anthonyeleven — DISMISSED** [review]

**Review by anthonyeleven — CHANGES_REQUESTED** [review]
The PR and commit messages should begin with the relative directory path, ie.

`doc/cephadm/services: ceph command missing from orch apply commands`

Please amend / push your commit and the PR message.

**Comment by bluikko** [comment]
> The PR and commit messages should begin with the relative directory path, ie.
> 
> `doc/cephadm/services: ceph command missing from orch apply commands`
> 
> Please amend / push your commit and the PR message.

Oops, how did I miss that in the Submitting Patches. Sorry.

**Comment by anthonyeleven** [comment]
I sometimes miss that myself, that's why we have a review process. I see that you updated the PR description, please amend your commit to match and force-push, I find that to be an easier workflow for WIP PRs than a succession of commits with later squashing.

**Comment by bluikko** [comment]
> I sometimes miss that myself, that's why we have a review process. I see that you updated the PR description, please amend your commit to match and force-push, I find that to be an easier workflow for WIP PRs than a succession of commits with later squashing.

Yes, it takes a while to clone the repo, will update soon.

**Comment by bluikko** [comment]
Well that was a chore. I usually use GitHub web UI for this or GitHub desktop since git proper is setup for my work. But GitHub desktop fails when it tries to clone submodule (which cannot be disabled it seems) ceph/ceph-object-corpus.

Anyways I think I got it right now.

This is not an excuse, I should have read the documentation correctly and especially the preceding section to this one: but I assume the example in https://github.com/ceph/ceph/blob/master/SubmittingPatches.rst#fixes-lines is simply `doc:` because maybe it is a more wide commit that touches several places?  
Though the referenced "man page" sounds like it could be a single file...

**Comment by anthonyeleven** [comment]
Sorry for the hassle, it does get better, I've been through it myself and I like to help others align with the standards.

You're absolutely right that the example in that document is misleading, or maybe it was written before the powers that be enacted the path convention.  Either way, I'll update that file so that it's more clear.  I've done a doc commit myself that began with `doc: fix xyz` because it touched multiple subdirectories, but those are rare and our example should show the more-general and more-common case.

The GitHub UI does make it easy to submit small doc changes, but unfortunately it also makes it easy to miss details like Signed-off-by, and can be tricky when changes need to be amended.

**Comment by bluikko** [comment]
> Sorry for the hassle, it does get better, I've been through it myself and I like to help others align with the standards.

I understand totally, I need to do this as part of my day job and I understand how important it is that the policies are followed.  
And I also feel the occasional frustration when people do not read/understand the written policies and need reminding ;)

**Review by anthonyeleven — APPROVED** [review]

**Pull request merged**
