### PR TITLE
quincy: mgr/dashboard: add server side encryption to rgw/s3 

### PR DESCRIPTION
**Pull request by aaSharma14**
backport tracker: https://tracker.ceph.com/issues/57835

---

backport of https://github.com/ceph/ceph/pull/47495
parent tracker: https://tracker.ceph.com/issues/57826

this backport was staged using ceph-backport.sh version 16.0.0.6848
find the latest version at https://github.com/ceph/ceph/blob/master/src/script/ceph-backport.sh

### CODE REVIEW

**Comment by nizamial09** [comment]
jenkins test dashboard

**Comment by nizamial09** [comment]
jenkins test dashboard cephadm

**Review by nizamial09 — APPROVED** [review]

**Comment by aaSharma14** [comment]
jenkins test dashboard cephadm

**Review by pereman2 — APPROVED** [review]

**Comment by aaSharma14** [comment]
jenkins test dashboard cephadm

**Pull request merged**
