### PR TITLE
common/log: Speed improvement for log

### PR DESCRIPTION
**Pull request by tchaikov**
@aclamk i adapted your PR of #17938 so it works with the rest part of logging system. also did some cleanup.

- rename `ThreadLocalPrebufferedStreambuf` to `CachedPrebufferedStreambuf`, shorter name, and it makes the intention more visible.
- move `ostream` out of `CachedPrebufferedStreambuf`. so it looks more reasonable: it's kind of weird at the first glance that a `streambuf` actually contains `ostream`!
- let `CachedPrebufferedStreambuf` inherit from `streambuf` instead of `basic_streambuf<>`, less type
- do not define the types for `CachedPrebufferedStreambuf`, as they are inherited from its parent class.
- drop unused methods
- use `traits_type` instead of `traits_ty`. the former is ready to use already.

### CODE REVIEW

**Comment by tchaikov** [comment]
before
---

```
[ RUN      ] Log.Speed_gather
[       OK ] Log.Speed_gather (1129 ms)
[ RUN      ] Log.Speed_nogather
[       OK ] Log.Speed_nogather (51 ms)
```

after
---
```
[ RUN      ] Log.Speed_gather
[       OK ] Log.Speed_gather (1484 ms)
[ RUN      ] Log.Speed_nogather
[       OK ] Log.Speed_nogather (58 ms)
```

**Comment by tchaikov** [comment]
@tone-zhang the "make check" consistently fails recently. do you mind taking a look at your convenience?

**Comment by tone-zhang** [comment]
@tchaikov My pleasure! I will have a look ASAP. Thanks!

**Comment by tone-zhang** [comment]
@tchaikov I validated the PR and ran "make check -j16" command in my test bed, it looks everything is OK.

**Comment by tchaikov** [comment]
@tone-zhang thanks for verifying this!

probably this failure is not very reproducible, but in our jenkins slave, it happens frequently. see

- https://jenkins.ceph.com/job/ceph-pull-requests-arm64/9416/
- https://jenkins.ceph.com/job/ceph-pull-requests-arm64/9476/
- https://jenkins.ceph.com/job/ceph-pull-requests-arm64/9473/

**Comment by tone-zhang** [comment]
@tchaikov All the above failures are in smoke.sh. I remember I have seen such error before. 
In most of cases, when it appeared, it will disappear if I run it again. Thanks!

**Comment by tchaikov** [comment]
- http://pulpito.ceph.com/kchai-2017-11-23_12:43:54-rados-wip-kefu-testing-2017-11-23-1812-distro-basic-mira/
- http://pulpito.ceph.com/kchai-2017-11-24_08:53:47-rados-wip-kefu-testing-2017-11-23-1812-distro-basic-mira/

**Comment by aclamk** [comment]
@tchaikov
>> rename ThreadLocalPrebufferedStreambuf to CachedPrebufferedStreambuf, shorter name, and it makes the intention more visible.
+1 You are probably right. Being thread-local is just a tool to reduce execution time.
>> move ostream out of CachedPrebufferedStreambuf. so it looks more reasonable: it's kind of weird at the first glance that a streambuf actually contains ostream!
I am not 100% sure about that. Sure, ostream as a member looks wierd. But lifetimes of **m_streambuf** and **m_os** are closely coupled. Hiding **ostream** inside m_streambuf enforces this requirement. 
>> let CachedPrebufferedStreambuf inherit from streambuf instead of basic_streambuf<>, less type
+1
>> do not define the types for CachedPrebufferedStreambuf, as they are inherited from its parent class.
+1
>> drop unused methods
+1
>> use traits_type instead of traits_ty. the former is ready to use already.
+1

**Comment by tchaikov** [comment]
@aclamk i reverted the second change. could you take another look?

**Comment by tchaikov** [comment]
- http://pulpito.ceph.com/kchai-2017-11-29_16:42:05-rados-wip-kefu-testing-2017-11-29-2317-distro-basic-mira/
- http://pulpito.ceph.com/kchai-2017-11-30_07:07:30-rados-wip-kefu-testing-2017-11-29-2317-distro-basic-smithi/
- http://pulpito.ceph.com/kchai-2017-12-01_02:01:54-rados-wip-kefu-testing-2017-11-29-2317-distro-basic-mira/

**Pull request merged**
