### PR TITLE
luminous: os/bluestore: fix duplicate allocations in bmap allocator

### PR DESCRIPTION
**Pull request by ifed01**
https://tracker.ceph.com/issues/40422

### CODE REVIEW

**Comment by smithfarm** [comment]
jenkins test docs

**Comment by smithfarm** [comment]
jenkins test docs

**Comment by yuriw** [comment]
[wip-yuri2-testing-2019-07-15-1956-luminous](https://trello.com/c/5QdUgJyi/667-wip-yuri2-testing-2019-07-15-1956-luminous)

**Comment by neha-ojha** [comment]
hey @ifed01, do you think backporting https://github.com/ceph/ceph/pull/28496/commits/95dcee1f75731b064bd0d33db779b02e8842d89b will be useful?

**Comment by yuriw** [comment]
(Note to self - ref: https://github.com/ceph/ceph/pull/28644#issuecomment-514359581)

**Comment by ifed01** [comment]
> hey @ifed01, do you think backporting [95dcee1](https://github.com/ceph/ceph/commit/95dcee1f75731b064bd0d33db779b02e8842d89b) will be useful?

@neha-ojha - no. This is primarily a developer's tool intended for allocator troubleshooting via log replay. So there is no need to have it in the field (and hence backport) as developers can build and use it from master branch. Against logs received from the field if needed...

**Comment by neha-ojha** [comment]
> > hey @ifed01, do you think backporting [95dcee1](https://github.com/ceph/ceph/commit/95dcee1f75731b064bd0d33db779b02e8842d89b) will be useful?
> 
> @neha-ojha - no. This is primarily a developer's tool intended for allocator troubleshooting via log replay. So there is no need to have it in the field (and hence backport) as developers can build and use it from master branch. Against logs received from the field if needed...

makes sense, thanks Igor.

**Pull request merged**
