### PR TITLE
mgr/dashboard: Consider null values as zero in grafana panels

### PR DESCRIPTION
**Pull request by aaSharma14**
After upgrading from RHCS4 to RHCS5..some of the grafana charts broke. This is because in RHCS5 we do not generate the metrics if its value is zero as a result the null value from that metric breaks the grafana charts or graphs. This PR is to fix the above mentioned issue.

Fixes: https://tracker.ceph.com/issues/63088

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Review by Pegonzal — APPROVED** [review]

**Comment by aaSharma14** [comment]
jenkins test make check

**Review by nizamial09 — APPROVED** [review]

**Comment by nizamial09** [comment]
jenkins test windows

**Comment by avanthakkar** [comment]
> After upgrading from RHCS4 to RHCS5..some of the grafana charts broke. This is because in RHCS5 we do not generate the metrics if its value is zero as a result the null value from that metric breaks the grafana charts or graphs. This PR is to fix the above mentioned issue.
> 
> Fixes: https://tracker.ceph.com/issues/63088
> ## Contribution Guidelines
> 
>     * To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).
> 
>     * If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.
> 
> 
> ## Checklist
> 
>     * Tracker (select at least one)
>       
>       * [ ]  References tracker ticket
>       * [ ]  Very recent bug; references commit where it was introduced
>       * [ ]  New feature (ticket optional)
>       * [ ]  Doc update (no ticket needed)
>       * [ ]  Code cleanup (no ticket needed)
> 
>     * Component impact
>       
>       * [ ]  Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
>       * [ ]  Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
>       * [ ]  No impact that needs to be tracked
> 
>     * Documentation (select at least one)
>       
>       * [ ]  Updates relevant documentation
>       * [ ]  No doc update is appropriate
> 
>     * Tests (select at least one)
>       
>       * [ ]  Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
>       * [ ]  Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
>       * [ ]  Includes bug reproducer
>       * [ ]  No tests
> 
> 
> Show available Jenkins commands

But does this applies to recent upstream reef versions as well? do we have any panels breaking in `main` branch ?

**Comment by aaSharma14** [comment]
> > After upgrading from RHCS4 to RHCS5..some of the grafana charts broke. This is because in RHCS5 we do not generate the metrics if its value is zero as a result the null value from that metric breaks the grafana charts or graphs. This PR is to fix the above mentioned issue.
> > Fixes: https://tracker.ceph.com/issues/63088
> > ## Contribution Guidelines
> > ```
> > * To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).
> > 
> > * If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ## Checklist
> > ```
> > * Tracker (select at least one)
> >   
> >   * [ ]  References tracker ticket
> >   * [ ]  Very recent bug; references commit where it was introduced
> >   * [ ]  New feature (ticket optional)
> >   * [ ]  Doc update (no ticket needed)
> >   * [ ]  Code cleanup (no ticket needed)
> > 
> > * Component impact
> >   
> >   * [ ]  Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
> >   * [ ]  Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
> >   * [ ]  No impact that needs to be tracked
> > 
> > * Documentation (select at least one)
> >   
> >   * [ ]  Updates relevant documentation
> >   * [ ]  No doc update is appropriate
> > 
> > * Tests (select at least one)
> >   
> >   * [ ]  Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
> >   * [ ]  Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
> >   * [ ]  Includes bug reproducer
> >   * [ ]  No tests
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Show available Jenkins commands
> 
> But does this applies to recent upstream reef versions as well? do we have any panels breaking in `main` branch ?

Am not sure, Have we changed the behavior of not generating metrics if the value is 0 in reef?

**Pull request merged**
