### PR TITLE
convert parameter type from pointer into reference

### PR DESCRIPTION
**Pull request by snakeAngel2015**
Signed-off-by: snakeAngel2015 li.jieA@h3c.com

### CODE REVIEW

**Comment by snakeAngel2015** [comment]
hi Sage,
 this commit can optimize the function's parameters . Could you see and merge it? thank you. @liewegas

**Comment by snakeAngel2015** [comment]
hi Sage,
      this commit can optimize the function's parameters . Could you review and merge it? thank you. @liewegas

**Comment by dachary** [comment]
jenkins test this please (jenkins hung)

**Comment by dachary** [comment]
I don't think it will improve performances. If you think otherwise, please provide performance benchmarks showing it does and re-open this pull request.

**Comment by tchaikov** [comment]
also we have an (undocumented) convention to use pointer as the output parameter.

**Comment by dachary** [comment]
@tchaikov you're right ! I did not notice because the comments mentionned "optimize". Sorry about that @snakeAngel2015 this is a fine pull request.

**Comment by tchaikov** [comment]
@dachary actually, i was concurring you. take `decode_str_str_map_to_bl(bufferlist::iterator& p, bufferlist *out)` as an example, the `bl` is actually an output parameter. so using the pointer to pass  bl is desired. maybe we could change the signature of this method (and its cousins) to something like
```
bufferlist decode_str_str_map_to_bl(bufferlist::iterator& p);
```
because it will very likely to be RVO, so no need to pass the output param to eliminate the overhead of default ctor and copy ctor. but that might be another story.

**Pull request closed without merging**
