### PR TITLE
doc: release-notes: draft v0.94.7 release notes

### PR DESCRIPTION
**Pull request by smithfarm**
Signed-off-by: Nathan Cutler <ncutler@suse.com>

### CODE REVIEW

**Comment by smithfarm** [comment]
First time I'm doing this - please bear with me.

**Comment by smithfarm** [comment]
@dachary Can you suggest some content for the first sentence "This Hammer point release fixes a range of bugs, most notably . . . "

**Comment by dachary** [comment]
@smithfarm you can leave it out and sage will add something if necessary.

**Comment by smithfarm** [comment]
liewegas: if 0.94.7 has been released, then I guess this can be closed?

**Comment by smithfarm** [comment]
@liewegas I see 0.94.7 has been released, so this can be closed?

**Comment by liewegas** [comment]
Oops, didn't see this. Yep! thanks

**Pull request closed without merging**
