### PR TITLE
Wip rgw amqp timeout

### PR DESCRIPTION
**Pull request by TRYTOBE8TME**
## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Review by yuvalif — APPROVED** [review]

**Comment by yuvalif** [comment]
what about the amqp unit tests. was there any change needed there?

**Comment by yuvalif** [comment]
please move out of "draft" state and run the BN teuthology tests against the branch

**Comment by TRYTOBE8TME** [comment]
Teuthology link: https://pulpito.ceph.com/kapandya-2021-09-13_05:14:50-rgw:notifications-wip-rgw-amqp-timeout-distro-basic-smithi/

**Comment by TRYTOBE8TME** [comment]
> what about the amqp unit tests. was there any change needed there?

No, I've not changed anything.

**Pull request merged**
