### PR TITLE
ceph-volume: Allow using custom-managed crypt(setup) devices

### PR DESCRIPTION
**Pull request by Fusl**

### CODE REVIEW

**Comment by jecluis** [comment]
had the contributor requesting a review on IRC today; @alfredodeza or maybe @jan--f, mind taking a look and get back to @Fusl ?

**Comment by alfredodeza** [comment]
@Fusl I am not sure this change would map correctly to the function. The docstring says:

         For example: /dev/sda would return True, but not /dev/sdc1

In this case, an encrypted `/dev/sdc1` would now return True. Maybe if you could expand better on what issue you are trying to solve here? I would recommend opening an issue in the ceph-volume tracker  (http://tracker.ceph.com/projects/ceph-volume/issues/new)

**Comment by Fusl** [comment]
@alfredodeza My Ceph cluster runs with SSDs with a partition table like this:

```
sdX1 1MB Reserved BIOS boot partition
sdX2 16GB RAID partition
sdX3 * empty partition
```

Now, it is possible to point ceph-volume lvm create at the sdX3 partition and use Ceph managed encryption keys, but sdX3 is managed by our own crypto implementation based on cryptsetup, Vault and some other things, as we don't want Ceph to manage or know about the encryption keys. In order to make ceph-volume create the partitions on that crypt device, this check needs to be in is_volume, not in is_partition.

We're already using this in our production environments as this was tested properly and would like to get it merged since our customers also depend on a similar feature where ceph managed crypto is a no-no for several reasons.

**Comment by Fusl** [comment]
@alfredodeza Here's one of our new Ceph nodes before and after patching the `disk.py` file. You can see how 

```
root@sg-nl-prox01:~# ceph-osd --version
ceph version 12.2.10 (fc2b1783e3727b66315cc667af9d663d30fe7ed4) luminous (stable)

root@sg-nl-prox01:~# ceph --version
ceph version 12.2.10 (fc2b1783e3727b66315cc667af9d663d30fe7ed4) luminous (stable)

root@sg-nl-prox01:~# CEPH_VOLUME_DEBUG=1 ceph-volume lvm create --data /dev/mapper/sda4 --bluestore
Running command: /usr/bin/ceph-authtool --gen-print-key
Running command: /usr/bin/ceph --cluster ceph --name client.bootstrap-osd --keyring /var/lib/ceph/bootstrap-osd/ceph.keyring -i - osd new xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
--> Was unable to complete a new OSD, will rollback changes
--> OSD will be fully purged from the cluster, because the ID was generated
Running command: ceph osd purge osd.0 --yes-i-really-mean-it
 stderr: purged osd.0
Traceback (most recent call last):
  File "/usr/sbin/ceph-volume", line 11, in <module>
    load_entry_point('ceph-volume==1.0.0', 'console_scripts', 'ceph-volume')()
  File "/usr/lib/python2.7/dist-packages/ceph_volume/main.py", line 38, in __init__
    self.main(self.argv)
  File "/usr/lib/python2.7/dist-packages/ceph_volume/decorators.py", line 59, in newfunc
    return f(*a, **kw)
  File "/usr/lib/python2.7/dist-packages/ceph_volume/main.py", line 148, in main
    terminal.dispatch(self.mapper, subcommand_args)
  File "/usr/lib/python2.7/dist-packages/ceph_volume/terminal.py", line 182, in dispatch
    instance.main()
  File "/usr/lib/python2.7/dist-packages/ceph_volume/devices/lvm/main.py", line 40, in main
    terminal.dispatch(self.mapper, self.argv)
  File "/usr/lib/python2.7/dist-packages/ceph_volume/terminal.py", line 182, in dispatch
    instance.main()
  File "/usr/lib/python2.7/dist-packages/ceph_volume/devices/lvm/create.py", line 69, in main
    self.create(args)
  File "/usr/lib/python2.7/dist-packages/ceph_volume/decorators.py", line 16, in is_root
    return func(*a, **kw)
  File "/usr/lib/python2.7/dist-packages/ceph_volume/devices/lvm/create.py", line 26, in create
    prepare_step.safe_prepare(args)
  File "/usr/lib/python2.7/dist-packages/ceph_volume/devices/lvm/prepare.py", line 219, in safe_prepare
    self.prepare()
  File "/usr/lib/python2.7/dist-packages/ceph_volume/decorators.py", line 16, in is_root
    return func(*a, **kw)
  File "/usr/lib/python2.7/dist-packages/ceph_volume/devices/lvm/prepare.py", line 299, in prepare
    block_lv = self.prepare_device(self.args.data, 'block', cluster_fsid, osd_fsid)
  File "/usr/lib/python2.7/dist-packages/ceph_volume/devices/lvm/prepare.py", line 204, in prepare_device
    raise RuntimeError(' '.join(error))
RuntimeError: Cannot use device (/dev/mapper/sda4). A vg/lv path or an existing device is needed

root@sg-nl-prox01:~# fgrep "return TYPE == 'disk'" /usr/lib/python2.7/dist-packages/ceph_volume/util/disk.py
        return TYPE == 'disk'

root@sg-nl-prox01:~# sed -i.bak "s|return TYPE == 'disk'$|return TYPE == 'disk' or TYPE == 'crypt'|" /usr/lib/python2.7/dist-packages/ceph_volume/util/disk.py | grep "return TYPE"

root@sg-nl-prox01:~# fgrep "return TYPE == 'disk'" /usr/lib/python2.7/dist-packages/ceph_volume/util/disk.py
        return TYPE == 'disk' or TYPE == 'crypt'

root@sg-nl-prox01:~# CEPH_VOLUME_DEBUG=1 ceph-volume lvm create --data /dev/mapper/sda4 --bluestore
Running command: /usr/bin/ceph-authtool --gen-print-key
Running command: /usr/bin/ceph --cluster ceph --name client.bootstrap-osd --keyring /var/lib/ceph/bootstrap-osd/ceph.keyring -i - osd new xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
Running command: vgcreate --force --yes ceph-xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx /dev/mapper/sda4
 stdout: Physical volume "/dev/mapper/sda4" successfully created.
 stdout: Volume group "ceph-xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx" successfully created
Running command: lvcreate --yes -l 100%FREE -n osd-block-xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx ceph-xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
 stdout: Logical volume "osd-block-xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx" created.
Running command: /usr/bin/ceph-authtool --gen-print-key
Running command: mount -t tmpfs tmpfs /var/lib/ceph/osd/ceph-0
--> Absolute path not found for executable: restorecon
--> Ensure $PATH environment variable contains common executable locations
Running command: chown -h ceph:ceph /dev/ceph-xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/osd-block-xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
Running command: chown -R ceph:ceph /dev/dm-14
Running command: ln -s /dev/ceph-xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/osd-block-xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx /var/lib/ceph/osd/ceph-0/block
Running command: ceph --cluster ceph --name client.bootstrap-osd --keyring /var/lib/ceph/bootstrap-osd/ceph.keyring mon getmap -o /var/lib/ceph/osd/ceph-0/activate.monmap
 stderr: got monmap epoch 1
Running command: ceph-authtool /var/lib/ceph/osd/ceph-0/keyring --create-keyring --name osd.0 --add-key xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
 stdout: creating /var/lib/ceph/osd/ceph-0/keyring
added entity osd.0 auth auth(auid = 18446744073709551615 key=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx with 0 caps)
Running command: chown -R ceph:ceph /var/lib/ceph/osd/ceph-0/keyring
Running command: chown -R ceph:ceph /var/lib/ceph/osd/ceph-0/
Running command: /usr/bin/ceph-osd --cluster ceph --osd-objectstore bluestore --mkfs -i 0 --monmap /var/lib/ceph/osd/ceph-0/activate.monmap --keyfile - --osd-data /var/lib/ceph/osd/ceph-0/ --osd-uuid xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx --setuser ceph --setgroup ceph
--> ceph-volume lvm prepare successful for: /dev/mapper/sda4
Running command: ceph-bluestore-tool --cluster=ceph prime-osd-dir --dev /dev/ceph-xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/osd-block-xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx --path /var/lib/ceph/osd/ceph-0
Running command: ln -snf /dev/ceph-xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/osd-block-xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx /var/lib/ceph/osd/ceph-0/block
Running command: chown -h ceph:ceph /var/lib/ceph/osd/ceph-0/block
Running command: chown -R ceph:ceph /dev/dm-14
Running command: chown -R ceph:ceph /var/lib/ceph/osd/ceph-0
Running command: systemctl enable ceph-volume@lvm-0-xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
 stderr: Created symlink /etc/systemd/system/multi-user.target.wants/ceph-volume@lvm-0-xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx.service → /lib/systemd/system/ceph-volume@.service.
Running command: systemctl enable --runtime ceph-osd@0
Running command: systemctl start ceph-osd@0
--> ceph-volume lvm activate successful for osd ID: 0
--> ceph-volume lvm create successful for: /dev/mapper/sda4
```

**Comment by tchaikov** [comment]
@alfredodeza is this change still relevant ?

**Comment by Fusl** [comment]
Looks like this patch isn't relevant enough for the Ceph project so we'll just keep using a dpkg postinst hook script to patch this on our own infrastructure.

**Comment by tchaikov** [comment]
@alfredodeza ping?

**Comment by alfredodeza** [comment]
I am +0 on this change, we don't have test coverage for it. @jan--f if you can take a look, I defer to you.

**Pull request closed without merging**
