### PR TITLE
mgr/cephadm: make --container-init a global option

### PR DESCRIPTION
**Pull request by jschmid1**
$subject

Signed-off-by: Joshua Schmid <jschmid@suse.de>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by smithfarm** [comment]
```
The following tests FAILED:
	 11 - run-rbd-unit-tests-127.sh (Timeout)
```

**Review by mgfritch — COMMENTED** [review]
why would container-init only matter for long running processes? what about the daemon pre/post containers?

**Comment by sebastian-philipp** [comment]
> why would container-init only matter for long running processes?

can you amend the commit message with the reason?

**Comment by jschmid1** [comment]
> why would container-init only matter for long running processes?

afaik, we're doing this mainly to be able to get coredumps. we'll most probably only need coredumps of long-running processes.

Am I missing something?

**Comment by mgfritch** [comment]
> > why would container-init only matter for long running processes?
> 
> afaik, we're doing this mainly to be able to get coredumps. we'll most probably only need coredumps of long-running processes.
> 

and also to avoid any defunct process when pid 1 doesn't respond to certain signals... which I think is be possible for many of the other commands (e.g. ceph-volume, run, adopt .. )?

**Comment by smithfarm** [comment]
Would it make sense to get rid of `--container-init` (as an option to `bootstrap` and `adopt`) altogether and just make "functioning coredumps" and "avoiding defunct child processes" the normal behavior of containerized Cech daemons?

**Comment by jschmid1** [comment]
> Would it make sense to get rid of `--container-init` (as an option to `bootstrap` and `adopt`) altogether and just make "functioning coredumps" and "avoiding defunct child processes" the normal behavior of containerized Cech daemons?

There are a couple of ways to achieve this.

1) Accept `--container-init` globally

2) Teach each subcommand that spawns a container to accept `--container-init`

3) Improve `bin/cephadm` in a way to it can decide self when to run a container with `--init` (as you suggested)

**Comment by jschmid1** [comment]
now, this excludes all commands that don't spawn a container.

also, I added support `init` for `cephadm ceph-volume`

**Comment by smithfarm** [comment]
@ceph/orchestrators pinging for review

**Comment by mgfritch** [comment]
> Would it make sense to get rid of `--container-init` (as an option to `bootstrap` and `adopt`) altogether and just make "functioning coredumps" and "avoiding defunct child processes" the normal behavior of containerized Cech daemons?

Or should we make this a global argument to the bin/cephadm script?? 

I also ran across this using the `ceph cephadm registry-login` command:
```
: error: unrecognized arguments: --container-init
```

It seems like there are many paths where this could potentially happen and attempting to define all instances from within mgr/cephadm will be tedious ..

**Comment by jschmid1** [comment]
> Or should we make this a global argument to the bin/cephadm script??

Done

**Review by tserong — COMMENTED** [review]
Looks reasonable to me. As this is now a global option, does it still need to be set in parser_adopt, parser_bootstrap and parser_deploy, or can these be removed?

**Comment by matthewoliver** [comment]
ha, just about to say the same thing. Otherwise looks good. Just spinning up a vstart cluster to confirm it's working locally for me.

**Comment by matthewoliver** [comment]
An initial vstart worked and I have the global option. So looking good. Will do better testing in the morning if you need.

**Comment by jschmid1** [comment]
> Looks reasonable to me. As this is now a global option, does it still need to be set in parser_adopt, parser_bootstrap and parser_deploy, or can these be removed?

I'd leave them for compatibility reasons. We have too many projects that need adaption when this changes.

**Review by mgfritch — APPROVED** [review]

**Review by matthewoliver — CHANGES_REQUESTED** [review]
OK so I've been playing with this in my vstart test env. If I use that patch as it is I see the the '--container-init' being passed to cephadm, but my daemon **isn't** getting to the `--init` added to the podman run command.

If I remove the other, non global, pasor options for container-init, then I do get the `--init` in my podman run command. I assume args.container_init is getting set to true in the global parser but when getting processes by the deploy_parser, and the option (not provided to the sub parser) is causing it to be set back to false.

So we _do_ need to remove the container-init from the sub parsers.

**Comment by jschmid1** [comment]
> OK so I've been playing with this in my vstart test env. If I use that patch as it is I see the the '--container-init' being passed to cephadm, but my daemon **isn't** getting to the `--init` added to the podman run command.
> 
> If I remove the other, non global, pasor options for container-init, then I do get the `--init` in my podman run command. I assume args.container_init is getting set to true in the global parser but when getting processes by the deploy_parser, and the option (not provided to the sub parser) is causing it to be set back to false.
> 
> So we _do_ need to remove the container-init from the sub parsers.

sigh.. removing

**Comment by jschmid1** [comment]
> sigh.. removing

I think it should be fine to only remove the subparser args for `deploy`. We need additional patches for Deepsea and (probably) ceph-salt if we also drop it from `adopt` and `bootstrap`.

**Comment by sebastian-philipp** [comment]
this would have fixed https://tracker.ceph.com/issues/49223

**Comment by smithfarm** [comment]
> this would have fixed https://tracker.ceph.com/issues/49223

IIRC we tried it downstream and it didn't fix it, or didn't completely fix it. But maybe I remember that wrong - some time has elapsed.

**Comment by smithfarm** [comment]
> > this would have fixed https://tracker.ceph.com/issues/49223
> 
> IIRC we tried this patchset downstream and it didn't fix it, or didn't completely fix it. But maybe I remember that wrong - some time has elapsed.

Ah, now I see this PR has all three commits, so maybe you are right. Shall we reopen the PR?

**Comment by sebastian-philipp** [comment]
it's too late by now. we have to go with backporting @mgfritch 's PR to octopus

**Comment by sebastian-philipp** [comment]
ok, that didn't worked out. sorry for the noise

**Pull request closed without merging**
