### PR TITLE
os/bluestore: fix race between remove_collection and object removals

### PR DESCRIPTION
**Pull request by ifed01**
remove_collection() might start collection listing before previous removals land to KV. And cache trimming might remove onode entry from cache before the corresponding record from collection listring is processed. Hence we get onode record and no in-mem entry to check 'exist' flag against which forces remove_collection to assert due to existing object(s).

Fixes: https://tracker.ceph.com/issues/25077

Signe-off-by: Igor Fedotov <ifedotov@suse.com>

### CODE REVIEW

**Comment by liewegas** [comment]
one nit: can you make your commit messages not word-wrap the first line (subsys: short desc)?  Thanks!

**Comment by liewegas** [comment]
also, typo in the signed-off-by line

**Comment by tchaikov** [comment]
```
2018-07-27 08:44:33.681 7fefdd03c700 -1 *** Caught signal (Aborted) **
 in thread 7fefdd03c700 thread_name:tp_osd_tp

 ceph version 14.0.0-1692-gc4c9057 (c4c905775903abed8a3009116ff8ffb95463a6f1) nautilus (dev)
 1: (()+0x11390) [0x7fefffdbc390]
 2: (pthread_cond_wait()+0xc0) [0x7fefffdb8360]
 3: (std::condition_variable::wait(std::unique_lock<std::mutex>&)+0xc) [0x557a679f3b6c]
 4: (BlueStore::Collection::flush_all_but_last()+0x74) [0x557a671cd0b4]
 5: (BlueStore::_remove_collection(BlueStore::TransContext*, coll_t const&, boost::intrusive_ptr<BlueStore::Collection>*)+0x58) [0x557a671f3ed8]
 6: (BlueStore::_txc_add_transaction(BlueStore::TransContext*, ObjectStore::Transaction*)+0xc2e) [0x557a6722b38e]
 7: (BlueStore::queue_transactions(boost::intrusive_ptr<ObjectStore::CollectionImpl>&, std::vector<ObjectStore::Transaction, std::allocator<ObjectStore::Transaction> >&, boost::intrusive_ptr<TrackedOp>, ThreadPool::TPHandle*)+0x5e7) [0x557a6722d8d7]
 8: (ObjectStore::queue_transaction(boost::intrusive_ptr<ObjectStore::CollectionImpl>&, ObjectStore::Transaction&&, boost::intrusive_ptr<TrackedOp>, ThreadPool::TPHandle*)+0x82) [0x557a66e1f6b2]
 9: (PG::_delete_some(ObjectStore::Transaction*)+0x889) [0x557a66e9cf39]
 10: (PG::RecoveryState::Deleting::react(PG::DeleteSome const&)+0x71) [0x557a66e9d521]
 11: (boost::statechart::simple_state<PG::RecoveryState::Deleting, PG::RecoveryState::ToDelete, boost::mpl::list<mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na>, (boost::statechart::history_mode)0>::react_impl(boost::statechart::event_base const&, void const*)+0x131) [0x557a66edbdb1]
 12: (boost::statechart::state_machine<PG::RecoveryState::RecoveryMachine, PG::RecoveryState::Initial, std::allocator<void>, boost::statechart::null_exception_translator>::process_event(boost::statechart::event_base const&)+0x6b) [0x557a66eb615b]
 13: (PG::do_peering_event(std::shared_ptr<PGPeeringEvent>, PG::RecoveryCtx*)+0x143) [0x557a66e9c043]
 14: (OSD::dequeue_peering_evt(OSDShard*, PG*, std::shared_ptr<PGPeeringEvent>, ThreadPool::TPHandle&)+0xcf) [0x557a66ddb47f]
 15: (OSD::dequeue_delete(OSDShard*, PG*, unsigned int, ThreadPool::TPHandle&)+0xd2) [0x557a66de71e2]
 16: (OSD::ShardedOpWQ::_process(unsigned int, ceph::heartbeat_handle_d*)+0xa3b) [0x557a66df4d3b]
 17: (ShardedThreadPool::shardedthreadpool_worker(unsigned int)+0x466) [0x557a6737e476]
:
```

/a/kchai-2018-07-27_05:17:26-rados-wip-kefu-testing-2018-07-27-1103-distro-basic-mira/2823903/remote/mira011/log/ceph-osd.4.log.gz

**Comment by ifed01** [comment]
@tchaikov, @liewegas - freeze fixed, please take a look again

**Comment by tchaikov** [comment]
```
2018-08-03T08:33:41.626 INFO:tasks.workunit.client.0.smithi170.stderr:/build/ceph-14.0.0-1876-ge3709e8/src/os/bluestore/BlueStore.h: 1753: FAILED assert(q.size() >= 1)
2018-08-03T08:33:41.627 INFO:tasks.workunit.client.0.smithi170.stderr: ceph version 14.0.0-1876-ge3709e8 (e3709e8a32e45d7c7d7589b7982d710502bf11c9) nautilus (dev)
2018-08-03T08:33:41.627 INFO:tasks.workunit.client.0.smithi170.stderr: 1: (ceph::__ceph_assert_fail(char const*, char const*, int, char const*)+0x152) [0x7f846eeb22b5]
2018-08-03T08:33:41.627 INFO:tasks.workunit.client.0.smithi170.stderr: 2: (ceph::__ceph_assertf_fail(char const*, char const*, int, char const*, char const*, ...)+0) [0x7f846eeb2437]
2018-08-03T08:33:41.627 INFO:tasks.workunit.client.0.smithi170.stderr: 3: (BlueStore::Collection::flush_all_but_last()+0xee) [0x5600c99784ce]
2018-08-03T08:33:41.627 INFO:tasks.workunit.client.0.smithi170.stderr: 4: (BlueStore::_remove_collection(BlueStore::TransContext*, coll_t const&, boost::intrusive_ptr<BlueStore::Collection>*)+0x58) [0x5600c999f898]
2018-08-03T08:33:41.627 INFO:tasks.workunit.client.0.smithi170.stderr: 5: (BlueStore::_txc_add_transaction(BlueStore::TransContext*, ObjectStore::Transaction*)+0xc6e) [0x5600c99d6b3e]
2018-08-03T08:33:41.627 INFO:tasks.workunit.client.0.smithi170.stderr: 6: (BlueStore::queue_transactions(boost::intrusive_ptr<ObjectStore::CollectionImpl>&, std::vector<ObjectStore::Transaction, std::allocator<ObjectStore::Transaction> >&
, boost::intrusive_ptr<TrackedOp>, ThreadPool::TPHandle*)+0x5e3) [0x5600c99d90d3]
2018-08-03T08:33:41.628 INFO:tasks.workunit.client.0.smithi170.stderr: 7: (ObjectStore::queue_transaction(boost::intrusive_ptr<ObjectStore::CollectionImpl>&, ObjectStore::Transaction&&, boost::intrusive_ptr<TrackedOp>, ThreadPool::TPHandl
e*)+0x80) [0x5600c952e480]
```
```
$ git br --contains ba843f7cfcb402ef502af39eba852e95be56859a
  wip-kefu-testing-2018-08-03-0109
```

/a//kchai-2018-08-03_07:35:53-rados-wip-kefu-testing-2018-08-03-0109-distro-basic-smithi/2858000/teuthology.log

**Comment by ifed01** [comment]
@tchaikov, @liewegas - looks like a bug in FuseStore. Fixed, please take a look one again.

**Comment by tchaikov** [comment]
- http://pulpito.ceph.com/kchai-2018-08-11_05:04:56-rados-wip-kefu-testing-2018-08-10-1333-distro-basic-mira/
- http://pulpito.ceph.com/kchai-2018-08-12_06:11:58-rados-wip-kefu-testing-2018-08-10-1333-distro-basic-mira/
- http://pulpito.ceph.com/kchai-2018-08-12_07:30:12-rados-wip-kefu-testing-2018-08-10-1333-distro-basic-mira/
- http://pulpito.ceph.com/kchai-2018-08-12_09:15:25-rados-wip-kefu-testing-2018-08-10-1333-distro-basic-mira/

**Pull request merged**
