### PR TITLE
common/options/global.yaml.in: increase default value of bluestore_cache_trim_max_skip_pinned

### PR DESCRIPTION
**Pull request by neha-ojha**
This option controls the rate of trimming of onodes and the earlier default of
64 has been seen to be too low for large clusters, leading to buildup of
onodes resulting in memory growth.

Increase the default value to 1000, since there are no known downsides to it.

Fixes: https://tracker.ceph.com/issues/50217
Signed-off-by: Neha Ojha <nojha@redhat.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Review by jdurgin — APPROVED** [review]

**Review by markhpc — APPROVED** [review]
Yep, I think this is a good idea overall.  The real fix is what Igor/Adam are working on, but this is the right short term solution and doesn't preclude the other work imho.

**Review by ifed01 — CHANGES_REQUESTED** [review]
Unless I missed something it looks like this parameter is of no use at the moment - we do not keep pinned entries in LRU any more and do not need to cap number of pinned entriese to traverse during trimming. Hence IMO this is a no-op modification.

**Review by aclamk — APPROVED** [review]

**Comment by aclamk** [comment]
@ifed01 True, it does nothing in master, but this is a good starting point for backports.

**Comment by neha-ojha** [comment]
> Unless I missed something it looks like this parameter is of no use at the moment - we do not keep pinned entries in LRU any more and do not need to cap number of pinned entriese to traverse during trimming. Hence IMO this is a no-op modification.

This parameter has been very useful in nautilus to deal with issues described in https://tracker.ceph.com/issues/50217. Unless we plan to get rid of this option completely in later versions, I don't see any harm in keeping the value consistent. Would you agree?

The other question is - what would be an equivalent knob in newer versions to control the rate of trimming of onode cache, if at all we need it?

**Comment by ifed01** [comment]
> > Unless I missed something it looks like this parameter is of no use at the moment - we do not keep pinned entries in LRU any more and do not need to cap number of pinned entriese to traverse during trimming. Hence IMO this is a no-op modification.
> 
> This parameter has been very useful in nautilus to deal with issues described in https://tracker.ceph.com/issues/50217. Unless we plan to get rid of this option completely in later versions, I don't see any harm in keeping the value consistent. Would you agree?
IIUC this could be helpful for pre-14.2.17 releases. After that it shouldn't be that useful due to https://github.com/ceph/ceph/pull/39720. Please correct me if I'm wrong...

But this patch is harmless indeed just wanted to let everyone know it's a no-op in Octopus+ releases. They do not use the parameter at all for now.
> 
> The other question is - what would be an equivalent knob in newer versions to control the rate of trimming of onode cache, if at all we need it?
It depends on the approach we choose to handle pinned entries. May be we could eliminate it totally - similarly as we currently have. Or may be it would have a bit different meaning (and naming)...

**Comment by neha-ojha** [comment]
> > > Unless I missed something it looks like this parameter is of no use at the moment - we do not keep pinned entries in LRU any more and do not need to cap number of pinned entriese to traverse during trimming. Hence IMO this is a no-op modification.
> > 
> > 
> > This parameter has been very useful in nautilus to deal with issues described in https://tracker.ceph.com/issues/50217. Unless we plan to get rid of this option completely in later versions, I don't see any harm in keeping the value consistent. Would you agree?
> > IIUC this could be helpful for pre-14.2.17 releases. After that it shouldn't be that useful due to #39720. Please correct me if I'm wrong...

Thanks for pointing this patch out! Since, we haven't removed this option from the bluestore code in nautilus, like we have in later releases, even after #39720, it would be good to understand how both interact - but that can happen as a separate discussion.

> 
> But this patch is harmless indeed just wanted to let everyone know it's a no-op in Octopus+ releases. They do not use the parameter at all for now.

sure

> 
> > The other question is - what would be an equivalent knob in newer versions to control the rate of trimming of onode cache, if at all we need it?
> > It depends on the approach we choose to handle pinned entries. May be we could eliminate it totally - similarly as we currently have. Or may be it would have a bit different meaning (and naming)...

**Comment by neha-ojha** [comment]
being tested at https://pulpito.ceph.com/nojha-2021-04-15_20:05:27-rados-wip-50217-distro-basic-smithi/

**Review by ifed01 — APPROVED** [review]

**Comment by neha-ojha** [comment]
> https://pulpito.ceph.com/nojha-2021-04-15_20:05:27-rados-wip-50217-distro-basic-smithi/

no related failures

**Pull request merged**
