### PR TITLE
doc/rados: line 233 typo cients -> clients 

### PR DESCRIPTION
**Pull request by xakaitetoia**
Justa a typo :P
Signed-off-by: Anastasios D Openstack Engineer <tdados@hotmail.com>

- [ ] References tracker ticket
- [x] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by cbodley** [comment]
thanks @xakaitetoia! a check failed because it's expecting to see a Signed-off-by: line in your commit message. please see https://github.com/ceph/ceph/blob/master/SubmittingPatches.rst#signing-contributions for details

**Comment by sebastian-philipp** [comment]
ping @xakaitetoia ?

**Comment by xakaitetoia** [comment]
Typo

**Comment by sebastian-philipp** [comment]
This still needs a `Signed-off-by` line

**Comment by neha-ojha** [comment]
> This still needs a `Signed-off-by` line

yup

**Comment by sebastian-philipp** [comment]
Still needs a `Signed-off-by ` :-(

**Comment by sebastian-philipp** [comment]
> Signed-off-by: Anastasios D Openstack Engineer [tdados@hotmail.com](mailto:tdados@hotmail.com)

Awesome, just add this to the commit message as described in  https://github.com/ceph/ceph/blob/master/SubmittingPatches.rst#signing-contributions

**Comment by sebastian-philipp** [comment]
No DCO. Closing.

**Pull request closed without merging**
