### PR TITLE
pacific: subscribe to config-key changes from mgr; maintain mgr-side ConfigMap

### PR DESCRIPTION
**Pull request by liewegas**
backport of #39504

@sebastian-philipp I left off these two commits because the first one had a conflict.. want to include them separately? 
- 9b5cbf40f8328060d7c6d04a474ee87d5bf03ca3
- 4d7dd0012962202532bde4fbc47554186c95b9fb

also note that when i tested this on master I adjusted the version condition in Mgr.cc to quincy from pacific, but since we are backporting this, the version merged to master says pacific too.  that means that until this is merged into pacific the upgrade tests (pacific -> master) will fail.

### CODE REVIEW

**Comment by sebastian-philipp** [comment]
> @sebastian-philipp I left off these two commits because the first one had a conflict.. want to include them separately?
> 
> * [9b5cbf4](https://github.com/ceph/ceph/commit/9b5cbf40f8328060d7c6d04a474ee87d5bf03ca3)
> * [4d7dd00](https://github.com/ceph/ceph/commit/4d7dd0012962202532bde4fbc47554186c95b9fb)
> 

sounds good.

**Comment by yuriw** [comment]
[wip-yuri7-testing-2021-02-22-0837-pacific](https://trello.com/c/ps8f45yv/1151-wip-yuri7-testing-2021-02-22-0837-pacific)

**Review by neha-ojha — APPROVED** [review]

**Comment by yuriw** [comment]
@liewegas suspect this breaking the build 
https://shaman.ceph.com/builds/ceph/wip-yuri7-testing-2021-02-22-0837-pacific/
https://jenkins.ceph.com/job/ceph-dev-new-build/ARCH=arm64,AVAILABLE_ARCH=arm64,AVAILABLE_DIST=centos8,DIST=centos8,MACHINE_SIZE=gigantic/52072//consoleFull

/home/jenkins-build/build/workspace/ceph-dev-new-build/ARCH/arm64/AVAILABLE_ARCH/arm64/AVAILABLE_DIST/centos8/DIST/centos8/MACHINE_SIZE/gigantic/release/16.1.0-338-g679e3c5b/rpm/el8/BUILD/ceph-16.1.0-338-g679e3c5b/src/mgr/ActivePyModules.cc: In member function 'PyObject* ActivePyModules::get_foreign_config(const string&, const string&)':
/home/jenkins-build/build/workspace/ceph-dev-new-build/ARCH/arm64/AVAILABLE_ARCH/arm64/AVAILABLE_DIST/centos8/DIST/centos8/MACHINE_SIZE/gigantic/release/16.1.0-338-g679e3c5b/rpm/el8/BUILD/ceph-16.1.0-338-g679e3c5b/src/mgr/ActivePyModules.cc:1060:5: error: 'without_gil_t' was not declared in this scope
     without_gil_t no_gil;
     ^~~~~~~~~~~~~

**Comment by liewegas** [comment]
@tchaikov any object to backporting 9c652fb305a3e3d1b4a752bac9bd8a85d15c7de9 as part of this?

**Comment by yuriw** [comment]
test this please

**Comment by neha-ojha** [comment]
@liewegas can you please check https://tracker.ceph.com/issues/49460, seems related and appeared multiple times in @yuriw's run https://pulpito.ceph.com/yuriw-2021-02-23_01:49:37-rados-wip-yuri7-testing-2021-02-22-1523-pacific-distro-basic-smithi/5905121/

**Comment by tchaikov** [comment]
> @tchaikov any object to backporting 9c652fb305a3e3d1b4a752bac9bd8a85d15c7de9 as part of this?

@liewegas no objections. please let me know if i can help preparing a backport including it.

**Pull request merged**
