### PR TITLE
rgw: sync tracing fixes

### PR DESCRIPTION
**Pull request by yehudasa**

### CODE REVIEW

**Comment by cbodley** [comment]
jenkins test this please

**Comment by tianshan** [comment]
maybe remove the parent ref in RGWSyncTraceNode will also fix the issue ? as I recorded in http://tracker.ceph.com/issues/22001

**Comment by cbodley** [comment]
jenkins test this please

**Comment by yehudasa** [comment]
@tianshan removing the parent will solve it, but we'll then lose the parent ref. We keep the parent ref around on purpose, so that when we dump the nodes we have a full call chain

**Comment by yuriw** [comment]
test this please

**Comment by yuriw** [comment]
[wip-yuri2-testing-2018-02-14-2134](https://trello.com/c/9ZVL9Aqx/263-wip-yuri2-testing-2018-02-14-2134)

**Pull request merged**
