### PR TITLE
librbd: fix various memory leaks

### PR DESCRIPTION
**Pull request by orozery**
This PR aims to fix all current (i.e. contained in master branch) errors that are reported by running:
`RBD_FEATURES=61 valgrind --tool=memcheck --leak-check=full ./bin/unittest_librbd`

Fixes: https://tracker.ceph.com/issues/53419

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [x] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Review by trociny — APPROVED** [review]
LGTM

Just a couple of nits, just in case you agree with some of them and want to improve.

**Comment by orozery** [comment]
@trociny thanks for the nits. made the changes.

**Comment by orozery** [comment]
jenkins test make check

**Comment by orozery** [comment]
jenkins test make check
jenkins test make check arm64

**Comment by orozery** [comment]
jenkins test make check

**Comment by orozery** [comment]
jenkins test make check arm64

**Comment by orozery** [comment]
jenkins test make check

**Comment by orozery** [comment]
jenkins test make check arm64

**Pull request merged**
