### PR TITLE
librbd: crypto performance optimization

### PR DESCRIPTION
**Pull request by orozery**
I tested librbd crypto overhead in the toughest condition I could, which is memstore OSDs.
Found that the call to `bufferlist::rebuild_aligned_size_and_memory` on `BlockCrypto` is really expensive (equals about half of the openssl crypto ops).

Good news that with the rebuild removed, the profiling shows that the openssl ops are the only dominant ops from the crypto side. i.e. no other overhead is seen.

For reference, here are the numbers I got for single-threaded 4MB-sized IOs:
Raw (non-encrypted) RBD image: 2189MB/s write, 2389MB/s read
RBD image with LUKS1: 1124MB/s write, 1240MB/s read
RBD image with LUKS2: 1322MB/s write, 2068MB/s read
(there was considerable deviation in results, I picked the best numbers per each case).

On the same machine, openssl speed gave:
aes-256-xts with 512 bytes block (LUKS1): 3642MB/s
aes-256-xts with 4096 bytes block (LUKS2): 4324MB/s

BTW I initially wanted to include in this PR also the enablement of the CryptoContextPool which I forgot to enable by default when I created the luks PR.
However, I noticed in profiling that the context pool actually can harm performance since it saves only a little for the relatively few calls to `get_context`, while adding an additional function call (which is not inlined) to the very hot `init_context` and `update_context` methods.

### CODE REVIEW

**Comment by orozery** [comment]
The profiling showing the inefficiency before this PR:

crypto-profile

**Comment by orozery** [comment]
Another BTW:
planning to compare my results to QEMU-LUKS on top of RBD.
This should be interesting. I expect significant improvement, definitely for LUKS2, but maybe also LUKS1.

**Comment by orozery** [comment]
QEMU numbers:

QEMU-LUKS:
```
root@bm01:~/qemu# ./build/qemu-io --object secret,id=sec0,data=password --image-opts file.driver=rbd,file.pool=rbd,key-secret=sec0,file.image=foo,file.conf=/root/ceph/build/ceph.conf
qemu-io> writev -P 0xfe 0 1000M
wrote 1048576000/1048576000 bytes at offset 0
1000 MiB, 1 ops; 0:00:01.75 (572.231 MiB/sec and 0.5722 ops/sec)
```

Our LUKS1 (through QEMO-IO, using a patched qemu-rbd driver):
```
root@bm01:~/qemu/build# ./qemu-io rbd:rbd/foo:conf=/root/ceph/build/ceph.conf:format=luks1 -f raw
format: luks1
qemu-io> writev -P 0xfe 0 1000M
wrote 1048576000/1048576000 bytes at offset 0
1000 MiB, 1 ops; 00.83 sec (1.175 GiB/sec and 1.2031 ops/sec)
```

LUKS2:
```
root@bm01:~/qemu/build# ./qemu-io rbd:rbd/foo:conf=/root/ceph/build/ceph.conf:format=luks2 -f raw
format: luks2
qemu-io> writev -P 0xfe 0 1000M
wrote 1048576000/1048576000 bytes at offset 0
1000 MiB, 1 ops; 00.79 sec (1.234 GiB/sec and 1.2633 ops/sec)
```

BTW QEMU with raw unencrypted rbd got 1.49GiB/s

**Comment by dillaman** [comment]
> QEMU numbers:

:open_mouth: 

Wow --- that is very unexpectedly good performance for this crypto layer. Now that I am thinking about it, it would be great to have a test that verifies that QEMU's LUKS implementation can properly read the librbd LUKS data (and vice-versa).

**Comment by orozery** [comment]
> > QEMU numbers:
> 
> 😮
> 
> Wow --- that is very unexpectedly good performance for this crypto layer. Now that I am thinking about it, it would be great to have a test that verifies that QEMU's LUKS implementation can properly read the librbd LUKS data (and vice-versa).

We have a test (luks-encryption.sh) which verifies that our implementation is compatible with cryptsetup.
Cryptsetup being the reference implementation for LUKS, I think it's enough to conclude that we match against QEMU LUKS as well.

**Review by dillaman — APPROVED** [review]
lgtm

**Comment by orozery** [comment]
tried to understand why our implementation is much faster and got the following:

First, I timed gcrypt (qemu's encryption library) performance, using:
```
	err = gcry_cipher_open(&handle, GCRY_CIPHER_AES256, GCRY_CIPHER_MODE_XTS, 0);
	err = gcry_cipher_setkey(handle, key, 32);
	for (int i = 0; i < 10000000; ++i) {
		gcry_cipher_reset(handle);
		err = gcry_cipher_setiv(handle, iv, 16);
		err = gcry_cipher_encrypt(handle, out, 512, in, 512);
	}
```
And got only 839MB/s (comparing to OpenSSL speed which gave 3642 MB/s).
I guess this should explain most of it.
BTW QEMU also supports nettle, but its performance is much much worse.

Another place where are better is the number of buffer copies along the IO path.
In QEMU-LUKS over RBD you got 2 copies: client -> qemu crypto -> rbd
Whereas in using our stack you get only a single copy: client -> rbd.

This single client->rbd copy takes about 33% of the time it takes to encrypt the same buffer using OpenSSL.

**Comment by orozery** [comment]
looks like openssl speed does not measure re-setting IV's per each block, so I implemented my own timing and got slightly lower numbers:
512 blocks: 3200 MB/s
4096 blocks: 4308 MB/s

**Comment by dillaman** [comment]
pacific backport appended to #39305

**Pull request merged**
