### PR TITLE
[RFC] osd: make replicas persist their missing sets

### PR DESCRIPTION
**Pull request by trociny**
Now when primary detects a missing object it sends a new type
message to peers to persist the object missing error.

The oid is erased from backfills_in_flight (i.e. allowing to
advance last_backfill position) only after acks from all peers
are recieved.

Signed-off-by: Mykola Golub <mgolub@suse.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by trociny** [comment]
@neha-ojha @athanatos 

This is about the issue that was discussed on CDM 2021-06-02 [1, 2].

As I understood it then, the idea is, when recording a missing oid on primary, to send also a new type message to secondaries to store (persist) this information there.

As I see a missing record is stored in the pg_log, and the primary calls `PeeringState::force_object_missing` for this. So I decided it would be a good idea to modify the primary, when it calls `force_object_missing`, to also send "force object missing" message to the secondaries, which will call `PeeringState::force_object_missing` there too.

I just checked the approach and it seems to work, though I have not tested it well at this stage. Right now I would be interested to know if this is what you had in mind or I am completely on a wrong track.

[1] https://pad.ceph.com/p/peer-missing-persistence
[2] https://www.youtube.com/watch?v=3dKjAgZb6Kk&t=295s

**Comment by neha-ojha** [comment]
> @neha-ojha @athanatos
> 
> This is about the issue that was discussed on CDM 2021-06-02 [1, 2].
> 
> As I understood it then, the idea is, when recording a missing oid on primary, to send also a new type message to secondaries to store (persist) this information there.
> 
> As I see a missing record is stored in the pg_log, and the primary calls `PeeringState::force_object_missing` for this. So I decided it would be a good idea to modify the primary, when it calls `force_object_missing`, to also send "force object missing" message to the secondaries, which will call `PeeringState::force_object_missing` there too.
> 
> I just checked the approach and it seems to work, though I have not tested it well at this stage. Right now I would be interested to know if this is what you had in mind or I am completely on a wrong track.
> 
> [1] https://pad.ceph.com/p/peer-missing-persistence [2] https://www.youtube.com/watch?v=3dKjAgZb6Kk&t=295s

sure, I'll review this next week

**Comment by trociny** [comment]
@neha-ojha ping

**Comment by neha-ojha** [comment]
> @neha-ojha ping

@trociny Apologies for the delay, this PR somehow fell through the cracks. The idea you've described in https://github.com/ceph/ceph/pull/43318#issuecomment-927801862 matches my understanding! But we'll need to do detailed code review and as discussed, this change will need careful testing. At this point, I'd say we should aim at merging this in the early R cycle, to give it good amount of baking time.

**Pull request closed without merging**
