### PR TITLE
quincy: client: do not release the global snaprealm until unmounting

### PR DESCRIPTION
**Pull request by lxbsz**
backport tracker: https://tracker.ceph.com/issues/55736

---

backport of https://github.com/ceph/ceph/pull/45114
parent tracker: https://tracker.ceph.com/issues/54362

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/master/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by yuriw** [comment]
jenkins test this please

**Review by vshankar — APPROVED** [review]

**Review by kotreshhr — APPROVED** [review]

**Comment by kotreshhr** [comment]
@lxbsz Could you check the make check failures please ?

**Comment by lxbsz** [comment]
> @lxbsz Could you check the make check failures please ?

Rebased it the latest.

**Comment by yuriw** [comment]
jenkins test this please

**Comment by lxbsz** [comment]
jenkins test api

**Comment by lxbsz** [comment]
jenkins test windows

**Comment by djgalloway** [comment]
Rebase on https://github.com/ceph/ceph/pull/47625 to resolve API failure

**Comment by kotreshhr** [comment]
> Rebase on #47625 to resolve API failure

@lxbsz  Please do the needful

**Comment by lxbsz** [comment]
> > Rebase on #47625 to resolve API failure
> 
> @lxbsz Please do the needful

Done!

**Pull request merged**
