### PR TITLE
doc: release notes for v10.2.7 Jewel

### PR DESCRIPTION
**Pull request by theanalyst**
Release notes for v10.2.7

### CODE REVIEW

**Comment by theanalyst** [comment]
Added all the merged prs to 10.2.7 (with the exception of tests), Didn't see anything mentioned in the Pending Release notes, so if we want to announce something in the changes we need to add that.

**Comment by theanalyst** [comment]
Since this was a relatively smaller release, just tagged the respective authors for review if anythign needs to be announced

**Comment by Liuchang0812** [comment]
Hi, @theanalyst 

Here is a jewel backport PR: https://github.com/ceph/ceph/pull/14236, It would be better to merge to v10.2.7.

**Comment by theanalyst** [comment]
@Liuchang0812 this may have to wait for 10.2.8, 10.2.7 is currently already handed over to QE, so it wouldn't be easy to do new merges anymore

**Comment by Liuchang0812** [comment]
@theanalyst OK! thanks

**Comment by theanalyst** [comment]
* changelog: 
fixed a typo in changelog link

**Pull request merged**
