### PR TITLE
cmake: really stop at top of source code tree

### PR DESCRIPTION
**Pull request by smithfarm**
Previously, we were recursing right up to /

Patch submitted by Tony Davies via https://tracker.ceph.com

Fixes: https://tracker.ceph.com/issues/43895
Signed-off-by: Tony Davies <anthony.t.davies@gmail.com>

### CODE REVIEW

**Comment by smithfarm** [comment]
@tonydavies57

**Comment by tchaikov** [comment]
@smithfarm could you change the Signed-off-by to something like
```
Signed-off-by: Tony Davis <anthony.t.davies@gmail.com>
```

**Comment by smithfarm** [comment]
@tchaikov Will be happy to do so if Tony says he is OK with that.

**Comment by tonydavies57** [comment]
No, I have no idea why I am being pinged on this. If I did something in error, I apologise

**Comment by smithfarm** [comment]
@tonydavies57 Sorry to trouble you. We're looking for some other Tony Davies.

**Comment by tonydavies57** [comment]
@smithfarm , no problem, there’s a lot of us around!

**Comment by tchaikov** [comment]
@smithfarm i will ping Tony over IRC to get his blessings.

**Comment by PhoenixMage** [comment]
You are looking for me, I approve

**Comment by badone** [comment]
@smithfarm Tony (PhoenixMage) is updating https://pad.ceph.com/p/reviewers Could you use that info for the signed off line please?

**Pull request merged**
