### PR TITLE
qa: test that new mounts of same fs function after old mount is evicted

### PR DESCRIPTION
**Pull request by jtlayton**
This is mostly intended for the kclient, which just got a patch to fail matching existing superblocks at mount time if the client is evicted (or is in the process of being forcibly unmounted):

https://lore.kernel.org/ceph-devel/CAOi1vP-jyg1E1eBB7NrtcmQB=2wYFXht669kgFqTsmgVeX-h4w@mail.gmail.com/T/#t

### CODE REVIEW

**Comment by jtlayton** [comment]
retest this please

**Comment by jtlayton** [comment]
jenkins test api

**Review by lxbsz — APPROVED** [review]

**Comment by batrick** [comment]
https://tracker.ceph.com/projects/cephfs/wiki/Master#2021-October-26

**Comment by batrick** [comment]
https://pulpito.ceph.com/pdonnell-2021-10-25_03:06:01-fs-wip-pdonnell-testing-20211025.000447-distro-basic-smithi/6459958/

Tested here, didn't see a run for fuse or stock rhel. Hopefully the test doesn't break on those mount types.

**Pull request merged**
