### PR TITLE
qa/suites/rados: add crimson perf test

### PR DESCRIPTION
**Pull request by tchaikov**
Signed-off-by: Kefu Chai <kchai@redhat.com>

- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by tchaikov** [comment]
still trying to build the crimson flavored ceph-osd package, so it can be tested against one of these tests

**Comment by tchaikov** [comment]
it depends on https://github.com/ceph/ceph-build/pull/1315

**Comment by tchaikov** [comment]
```
2019-06-26T14:12:05.266 INFO:teuthology.orchestra.run.smithi202.stdout: ceph : Depends: ceph-mon (= 15.0.0-2197-g324750c-1bionic) but it is not going to be installed
2019-06-26T14:12:05.266 INFO:teuthology.orchestra.run.smithi202.stdout:        Depends: ceph-osd (= 15.0.0-2197-g324750c-1bionic) but it is not going to be installed
2019-06-26T14:12:05.266 INFO:teuthology.orchestra.run.smithi202.stdout: ceph-common : Depends: python-rgw (= 15.0.0-2197-g324750c-1bionic) but it is not going to be installed
2019-06-26T14:12:05.266 INFO:teuthology.orchestra.run.smithi202.stdout:               Depends: libradosstriper1 but it is not going to be installed
2019-06-26T14:12:05.266 INFO:teuthology.orchestra.run.smithi202.stdout:               Depends: libstdc++6 (>= 9) but 8.3.0-6ubuntu1~18.04 is to be installed
2019-06-26T14:12:05.267 INFO:teuthology.orchestra.run.smithi202.stdout: ceph-fuse : Depends: libstdc++6 (>= 9) but 8.3.0-6ubuntu1~18.04 is to be installed
2019-06-26T14:12:05.267 INFO:teuthology.orchestra.run.smithi202.stdout: ceph-mds : Depends: ceph-base (= 15.0.0-2197-g324750c-1bionic) but it is not going to be installed
2019-06-26T14:12:05.267 INFO:teuthology.orchestra.run.smithi202.stdout:            Depends: libstdc++6 (>= 9) but 8.3.0-6ubuntu1~18.04 is to be installed
2019-06-26T14:12:05.267 INFO:teuthology.orchestra.run.smithi202.stdout: ceph-mgr : Depends: ceph-base (= 15.0.0-2197-g324750c-1bionic) but it is not going to be installed
2019-06-26T14:12:05.267 INFO:teuthology.orchestra.run.smithi202.stdout:            Depends: libstdc++6 (>= 9) but 8.3.0-6ubuntu1~18.04 is to be installed
2019-06-26T14:12:05.267 INFO:teuthology.orchestra.run.smithi202.stdout:            Recommends: ceph-mgr-dashboard but it is not going to be installed
2019-06-26T14:12:05.267 INFO:teuthology.orchestra.run.smithi202.stdout:            Recommends: ceph-mgr-diskprediction-local but it is not going to be installed
2019-06-26T14:12:05.268 INFO:teuthology.orchestra.run.smithi202.stdout:            Recommends: ceph-mgr-diskprediction-cloud but it is not going to be installed
2019-06-26T14:12:05.268 INFO:teuthology.orchestra.run.smithi202.stdout:            Recommends: ceph-mgr-rook but it is not going to be installed
2019-06-26T14:12:05.268 INFO:teuthology.orchestra.run.smithi202.stdout:            Recommends: ceph-mgr-ssh but it is not going to be installed
2019-06-26T14:12:05.268 INFO:teuthology.orchestra.run.smithi202.stdout: ceph-test : Depends: libradosstriper1 but it is not going to be installed
2019-06-26T14:12:05.268 INFO:teuthology.orchestra.run.smithi202.stdout:             Depends: libstdc++6 (>= 9) but 8.3.0-6ubuntu1~18.04 is to be installed
2019-06-26T14:12:05.269 INFO:teuthology.orchestra.run.smithi202.stdout: libcephfs2 : Depends: libstdc++6 (>= 9) but 8.3.0-6ubuntu1~18.04 is to be installed
2019-06-26T14:12:05.269 INFO:teuthology.orchestra.run.smithi202.stdout: librados2 : Depends: libstdc++6 (>= 9) but 8.3.0-6ubuntu1~18.04 is to be installed
2019-06-26T14:12:05.269 INFO:teuthology.orchestra.run.smithi202.stdout: librbd1 : Depends: libstdc++6 (>= 9) but 8.3.0-6ubuntu1~18.04 is to be installed
2019-06-26T14:12:05.269 INFO:teuthology.orchestra.run.smithi202.stdout: python-ceph : Depends: python-rgw (= 15.0.0-2197-g324750c-1bionic) but it is not going to be installed
2019-06-26T14:12:05.269 INFO:teuthology.orchestra.run.smithi202.stdout: radosgw : Depends: librgw2 (= 15.0.0-2197-g324750c-1bionic) but it is not going to be installed
2019-06-26T14:12:05.270 INFO:teuthology.orchestra.run.smithi202.stdout:           Depends: libstdc++6 (>= 9) but 8.3.0-6ubuntu1~18.04 is to be installed
2019-06-26T14:12:05.270 INFO:teuthology.orchestra.run.smithi202.stdout: rbd-fuse : Depends: libstdc++6 (>= 9) but 8.3.0-6ubuntu1~18.04 is to be installed
2019-06-26T14:12:05.284 INFO:teuthology.orchestra.run.smithi202.stderr:W: --force-yes is deprecated, use one of the options starting with --allow instead.
2019-06-26T14:12:05.285 INFO:teuthology.orchestra.run.smithi202.stderr:E: Unable to correct problems, you have held broken packages.
2019-06-26T14:12:05.286 DEBUG:teuthology.orchestra.run:got remote process result: 100
```

as crimson is compiled using GCC-9 offered by [ubuntu-toolchain-r  PPA](https://launchpad.net/~ubuntu-toolchain-r/+archive/ubuntu/test), we need to install the libstdc++6 runtime to address the dependency issue.

**Comment by tchaikov** [comment]
http://pulpito.ceph.com/kchai-2019-06-26_15:25:01-rados-wip-for-crimson-perf-test-distro-crimson-smithi/
```
Command crashed: 'sudo MALLOC_CHECK_=3 adjust-ulimits ceph-coverage /home/ubuntu/cephtest/archive/coverage ceph-osd --no-mon-config --cluster ceph --mkfs --mkkey -i 0 --monmap /home/ubuntu/cephtest/ceph.monmap' 
```

**Comment by tchaikov** [comment]
```
2019-06-29T10:18:44.434 INFO:tasks.ceph.osd.0.smithi088.stdout:INFO  2019-06-29 10:17:55,238 [shard 0] osd - osd.0: _preboot
2019-06-29T10:18:44.434 INFO:tasks.ceph.osd.0.smithi088.stdout:WARN  2019-06-29 10:17:55,238 [shard 0] osd - waiting for initial osdmap
2019-06-29T10:18:44.434 INFO:tasks.ceph.osd.0.smithi088.stdout:INFO  2019-06-29 10:17:55,239 [shard 0] osd - osdmap_subscribe(1)
2019-06-29T10:18:44.434 INFO:tasks.ceph.osd.0.smithi088.stdout:INFO  2019-06-29 10:17:55,239 [shard 0] osd - handle_osd_map osd_map(1..4 src has 1..4) v4
2019-06-29T10:18:44.434 INFO:tasks.ceph.osd.0.smithi088.stdout:INFO  2019-06-29 10:17:55,239 [shard 0] osd - handle_osd_map epochs [1..4], i have 0, src has [1..4]
2019-06-29T10:18:44.434 INFO:tasks.ceph.osd.0.smithi088.stdout:INFO  2019-06-29 10:17:55,239 [shard 0] osd - osd.0: committed_osd_maps(1, 4)
2019-06-29T10:18:44.434 INFO:tasks.ceph.osd.0.smithi088.stdout:INFO  2019-06-29 10:17:55,239 [shard 0] osd - osd.0: now preboot
2019-06-29T10:18:44.435 INFO:tasks.ceph.osd.0.smithi088.stdout:INFO  2019-06-29 10:17:55,239 [shard 0] osd - osd.0: _preboot
2019-06-29T10:18:44.435 INFO:tasks.ceph.osd.0.smithi088.stdout:INFO  2019-06-29 10:17:55,239 [shard 0] osd - hb_back_msgr: v2:172.21.15.88:6804/10251
2019-06-29T10:18:44.435 INFO:tasks.ceph.osd.0.smithi088.stdout:INFO  2019-06-29 10:17:55,239 [shard 0] osd - hb_front_msgr: v1:172.21.15.88:6805/10251
2019-06-29T10:18:44.435 INFO:tasks.ceph.osd.0.smithi088.stdout:INFO  2019-06-29 10:17:55,239 [shard 0] osd - cluster_msgr: v2:172.21.15.88:6801/10251
2019-06-29T10:18:44.435 INFO:tasks.ceph.osd.0.smithi088.stdout:INFO  2019-06-29 10:17:56,158 [shard 0] osd - ms_dispatch unhandled message mgrmap(e 3) v1
2019-06-29T10:18:44.435 INFO:tasks.ceph.osd.0.smithi088.stdout:INFO  2019-06-29 10:17:56,159 [shard 0] monc - get_auth_request(con=[osd.0(client) v1:172.21.15.88:6800/10251 >> v2:172.21.15.88:6802/10118], auth_method=0)
2019-06-29T10:18:44.435 INFO:tasks.ceph.osd.0.smithi088.stdout:INFO  2019-06-29 10:17:56,161 [shard 0] mgrc - handle_mgr_conf mgrconfigure(period=5, threshold=5) v3
2019-06-29T10:18:44.436 INFO:tasks.ceph.osd.0.smithi088.stdout:INFO  2019-06-29 10:17:56,161 [shard 0] osd - ms_dispatch unhandled message mgrconfigure(period=5, threshold=5) v3
2019-06-29T10:18:44.436 INFO:tasks.ceph.osd.0.smithi088.stdout:INFO  2019-06-29 10:18:04,417 [shard 0] monc - sending auth(proto 1 0 bytes epoch 0) v1
2019-06-29T10:18:44.436 INFO:tasks.ceph.osd.0.smithi088.stdout:INFO  2019-06-29 10:18:04,417 [shard 0] monc - waiting
2019-06-29T10:18:44.436 INFO:tasks.ceph.osd.0.smithi088.stdout:INFO  2019-06-29 10:18:04,417 [shard 0] monc - handle_auth_reply mon v1:172.21.15.88:6800/10251 => v1:172.21.15.88:6789/0 returns auth_reply(proto 1 0 (0) Success) v1: 0
2019-06-29T10:18:44.436 INFO:tasks.ceph.osd.0.smithi088.stdout:INFO  2019-06-29 10:18:04,417 [shard 0] osd - ms_dispatch unhandled message auth_reply(proto 1 0 (0) Success) v1
2019-06-29T10:18:44.436 INFO:tasks.ceph.osd.0.smithi088.stdout:INFO  2019-06-29 10:18:04,417 [shard 0] monc - do_auth: mon v1:172.21.15.88:6800/10251 => v1:172.21.15.88:6789/0 returns auth_reply(proto 1 0 (0) Success) v1: 0
2019-06-29T10:18:44.436 INFO:tasks.ceph.osd.0.smithi088.stdout:INFO  2019-06-29 10:18:14,420 [shard 0] monc - sending auth(proto 1 0 bytes epoch 0) v1
2019-06-29T10:18:44.436 INFO:tasks.ceph.osd.0.smithi088.stdout:INFO  2019-06-29 10:18:14,420 [shard 0] monc - waiting
2019-06-29T10:18:44.437 INFO:tasks.ceph.osd.0.smithi088.stdout:INFO  2019-06-29 10:18:14,420 [shard 0] monc - handle_auth_reply mon v1:172.21.15.88:6800/10251 => v1:172.21.15.88:6789/0 returns auth_reply(proto 1 0 (0) Success) v1: 0
2019-06-29T10:18:44.437 INFO:tasks.ceph.osd.0.smithi088.stdout:INFO  2019-06-29 10:18:14,421 [shard 0] osd - ms_dispatch unhandled message auth_reply(proto 1 0 (0) Success) v1
2019-06-29T10:18:44.437 INFO:tasks.ceph.osd.0.smithi088.stdout:INFO  2019-06-29 10:18:14,421 [shard 0] monc - do_auth: mon v1:172.21.15.88:6800/10251 => v1:172.21.15.88:6789/0 returns auth_reply(proto 1 0 (0) Success) v1: 0
2019-06-29T10:18:44.437 INFO:tasks.ceph.osd.0.smithi088.stdout:INFO  2019-06-29 10:18:24,425 [shard 0] monc - sending auth(proto 1 0 bytes epoch 0) v1
2019-06-29T10:18:44.437 INFO:tasks.ceph.osd.0.smithi088.stdout:INFO  2019-06-29 10:18:24,425 [shard 0] monc - waiting
2019-06-29T10:18:44.437 INFO:tasks.ceph.osd.0.smithi088.stdout:INFO  2019-06-29 10:18:24,425 [shard 0] monc - handle_auth_reply mon v1:172.21.15.88:6800/10251 => v1:172.21.15.88:6789/0 returns auth_reply(proto 1 0 (0) Success) v1: 0
....
```

**Comment by tchaikov** [comment]
```
2019-07-01T01:39:05.775 INFO:teuthology.orchestra.run.smithi063.stderr:01:39:05 - DEBUG    - cbt      - CheckedPopen continue_if_error=True args=pdsh -f 1 -R ssh -w ubuntu@smithi063.front.sepia.ceph.com /usr/bin/rados -c /etc/ceph/ceph.conf -v
...
2019-07-01T01:39:07.148 INFO:teuthology.orchestra.run.smithi063.stderr:01:39:07 - ERROR    - cbt      - During tests
2019-07-01T01:39:07.148 INFO:teuthology.orchestra.run.smithi063.stderr:Traceback (most recent call last):
2019-07-01T01:39:07.148 INFO:teuthology.orchestra.run.smithi063.stderr:  File "/home/ubuntu/cephtest/cbt/cbt.py", line 75, in main
2019-07-01T01:39:07.148 INFO:teuthology.orchestra.run.smithi063.stderr:    b.run()
2019-07-01T01:39:07.148 INFO:teuthology.orchestra.run.smithi063.stderr:  File "/home/ubuntu/cephtest/cbt/benchmark/radosbench.py", line 77, in run
2019-07-01T01:39:07.148 INFO:teuthology.orchestra.run.smithi063.stderr:    self._run('write', '%s/write' % self.run_dir, '%s/write' % self.out_dir)
2019-07-01T01:39:07.149 INFO:teuthology.orchestra.run.smithi063.stderr:  File "/home/ubuntu/cephtest/cbt/benchmark/radosbench.py", line 115, in _run
2019-07-01T01:39:07.149 INFO:teuthology.orchestra.run.smithi063.stderr:    raise ValueError('max_objects not supported by rados_version < 9')
2019-07-01T01:39:07.149 INFO:teuthology.orchestra.run.smithi063.stderr:ValueError: max_objects not supported by rados_version < 9
2019-07-01T01:39:07.181 DEBUG:teuthology.orchestra.run:got remote process result: 1
```

**Comment by tchaikov** [comment]
http://pulpito.ceph.com/kchai-2019-07-01_04:29:12-rados-wip-kefu2-testing-2019-07-01-0133-distro-crimson-mira/

```
/usr/bin/rados -c /etc/ceph/ceph.conf -p rados-bench-cbt bench -b 131072 60 write --concurrent-ios 4   --run-name `hostname -f`-0 --no-cleanup
```
crimson-osd crashed 
```
2019-07-01T04:53:30.053 INFO:tasks.ceph.osd.0.mira101.stdout:WARN  2019-07-01 04:53:28,040 [shard 0] ms - [osd.0(client) v1:172.21.8.118:6800/11342 >> v1:172.21.8.118:0/1345921402@46806] open fault: std::bad_alloc (std::bad_alloc)
2019-07-01T04:53:30.053 INFO:tasks.ceph.osd.0.mira101.stdout:ERROR 2019-07-01 04:53:28,044 [shard 0] ms - failed to log message: std::bad_alloc (std::bad_alloc)
2019-07-01T04:53:30.053 INFO:tasks.ceph.osd.0.mira101.stdout:WARN  2019-07-01 04:53:28,044 [shard 0] seastar - Exceptional future ignored: std::bad_alloc (std::bad_alloc), backtrace:   0xbb17a1
2019-07-01T04:53:30.053 INFO:tasks.ceph.osd.0.mira101.stdout:  0xa7187b
2019-07-01T04:53:30.053 INFO:tasks.ceph.osd.0.mira101.stdout:  0x953d6c
2019-07-01T04:53:30.054 INFO:tasks.ceph.osd.0.mira101.stdout:  0xa703b3
2019-07-01T04:53:30.054 INFO:tasks.ceph.osd.0.mira101.stdout:  0xa706ff
2019-07-01T04:53:30.054 INFO:tasks.ceph.osd.0.mira101.stdout:  0xad7e0d
2019-07-01T04:53:30.054 INFO:tasks.ceph.osd.0.mira101.stdout:  0xa4361c
2019-07-01T04:53:30.054 INFO:tasks.ceph.osd.0.mira101.stdout:  0x39a5fe
2019-07-01T04:53:30.054 INFO:tasks.ceph.osd.0.mira101.stdout:  /lib/x86_64-linux-gnu/libc.so.6+0x21b96
2019-07-01T04:53:30.054 INFO:tasks.ceph.osd.0.mira101.stdout:  0x3a9009
...
2019-07-01T04:53:30.084 INFO:tasks.ceph.osd.0.mira101.stdout:WARN  2019-07-01 04:53:28,062 [shard 0] ms - [osd.0(client) v1:172.21.8.118:6800/11342 >> v1:172.21.8.118:0/987851558@46828] open fault: std::bad_alloc (std::bad_alloc)
2019-07-01T04:53:30.084 INFO:tasks.ceph.osd.0.mira101.stdout:WARN  2019-07-01 04:53:28,062 [shard 0] seastar - Exceptional future ignored: std::bad_alloc (std::bad_alloc), backtrace:   0xbb17a1
2019-07-01T04:53:30.084 INFO:tasks.ceph.osd.0.mira101.stdout:  0xa7187b
2019-07-01T04:53:30.084 INFO:tasks.ceph.osd.0.mira101.stdout:  0x953d6c
2019-07-01T04:53:30.084 INFO:tasks.ceph.osd.0.mira101.stdout:  0xa703b3
2019-07-01T04:53:30.084 INFO:tasks.ceph.osd.0.mira101.stdout:  0xa706ff
2019-07-01T04:53:30.084 INFO:tasks.ceph.osd.0.mira101.stdout:  0xad7e0d
2019-07-01T04:53:30.085 INFO:tasks.ceph.osd.0.mira101.stdout:  0xa4361c
2019-07-01T04:53:30.085 INFO:tasks.ceph.osd.0.mira101.stdout:  0x39a5fe
2019-07-01T04:53:30.085 INFO:tasks.ceph.osd.0.mira101.stdout:  /lib/x86_64-linux-gnu/libc.so.6+0x21b96
2019-07-01T04:53:30.085 INFO:tasks.ceph.osd.0.mira101.stdout:  0x3a9009
```

**Comment by tchaikov** [comment]
http://pulpito.ceph.com/kchai-2019-07-02_07:44:20-rados-wip-kefu2-testing-2019-07-01-0133-distro-crimson-mira/

**Comment by tchaikov** [comment]
before merging this change, we still need to enable crimson flavor of master build on jenkins build job.

**Comment by cyx1231st** [comment]
I tried to use `rados bench` these days, but found that my results are not reasonable to me because:
- Stddev Bandwidth sometimes is too high.
- Performance results across tests are not stable.
- For smaller IO, the CPU usage of crimson-osd core cannot reach 100%.
- For larger IO, the CPU usage of crimson-osd core can reach 100%, but I don't know whether it is busy polling or doing IO.

If the bottleneck is at rados client side, then the result may not be reliable because we are not measuring the performance of crimson-osd. It is highly possible because `rados bench` is using a different messenger and POSIX threads.

**Comment by tchaikov** [comment]
@cyx1231st thanks for your comments. i will increase the queue-depth and add more instance of client, and try again.

**Comment by tchaikov** [comment]
@cyx1231st I think you need to use multiple rados bench clients instead. @rzarzynski and me are using two clients to exercise crimson osd.

and in this PR, i am using `concurrent_procs: 2` to start two clients. if it's not enough, we can use more of them.

**Comment by tchaikov** [comment]
https://github.com/ceph/ceph-build/pull/1334 is posted to build crimson flavor from master branch. once it's merged. this change is ready to go.

**Comment by tchaikov** [comment]
jenkins test crimson perf

**Comment by tchaikov** [comment]
jenkins test crimson perf

**Comment by tchaikov** [comment]
jenkins test crimson perf

**Comment by tchaikov** [comment]
jenkins test crimson perf

**Comment by tchaikov** [comment]
jenkins test crimson perf

**Comment by tchaikov** [comment]
jenkins test crimson perf

**Pull request closed without merging**
