### PR TITLE
reef: mds: catch damage to CDentry's first member before persisting

### PR DESCRIPTION
**Pull request by batrick**
https://tracker.ceph.com/issues/59222

### CODE REVIEW

**Comment by yuriw** [comment]
@batrick pls rebase

**Comment by batrick** [comment]
> @batrick pls rebase

@yuriw done

**Comment by kotreshhr** [comment]
jenkins test api

**Review by kotreshhr — APPROVED** [review]

**Comment by yuriw** [comment]
jenkins test api

**Comment by yuriw** [comment]
ref: https://trello.com/c/mhrFHiWI

**Pull request merged**
