### PR TITLE
crimson/osd: support multicore cyanstore

### PR DESCRIPTION
**Pull request by liu-chunmei**
## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by athanatos** [comment]
This approach basically requires all FuturizedStore implementations to be accessed by the OSD through a seastar::sharded container. This already isn't a good fit for alienstore -- which doesn't need it, and probably won't be a good fit for SeaStore -- which will need finer control over shared data structures. It may make sense for CyanStore, but I'd like you do to all of this within the CyanStore implementation without exposing the seastar::sharded<> container to the osd.

**Comment by liu-chunmei** [comment]
> This approach basically requires all FuturizedStore implementations to be accessed by the OSD through a seastar::sharded container. This already isn't a good fit for alienstore -- which doesn't need it, and probably won't be a good fit for SeaStore -- which will need finer control over shared data structures. It may make sense for CyanStore, but I'd like you do to all of this within the CyanStore implementation without exposing the seastar::sharded<> container to the osd.

@athanatos IIUC, this shard store do NOT influence alienstore, for alienstore, there is only one store instance created and each PerShardState hold this store instance reference, and no proxy for alienstore, so each pg shard core can access alienstore not through primary core.  see the third commit (only create one store instance, and mutlicore pg shards can use it )

**Comment by liu-chunmei** [comment]
@athanatos BTW, if I want to support partitions for seastore, that means each seastore instance has its own device or partition, then each of the seastore instance has its own lba tree, onode tree, collections and omap tree, all the meta data needn't be shared, then this PR should work, right? 
if we don't use partitions for seastore, and all cores share one device, that will be more complex.

**Comment by cyx1231st** [comment]
I think SeaStore is not really relavent to this PR.

> if we don't use partitions for seastore, and all cores share one device, that will be more complex.

Software-level dynamic partition is the goal for SeaStore. I think we need to find a way to manage a device from multiple cores, even for the static partition version.

**Comment by liu-chunmei** [comment]
@athanatos @cyx1231st  I hard code to give each seastore instance one dev/osd0x as its device and copy keyring to them. (I manually create these files)
with the following diff based on this PR:
I can do the test as follows and it works
MDS=0 MGR=1 OSD=1 MON=1 ../src/vstart.sh -n --without-dashboard --seastore -X --crimson-smp 3 --crimson-foreground -d
1)  ./bin/ceph osd pool create test-pool 32 32
2) ./bin/ceph osd pool set test-pool size 1 --yes-i-really-mean-it
3)  ./bin/ceph osd pool set test-pool min_size 1
4)  ./bin/rados bench -p test-pool 5 write -b 4096 --no-cleanup  (repeat 3 times)
5)  ./bin/rados bench -p test-pool 10 write -b 4096 --no-cleanup  (repeat 3 times)
6) ./bin/rados bench -p test-pool 10 seq –t 10
7) ./bin/rados bench -p test-pool 10 rand -t 10

sometimes I meet segment fault from onode tree by skipping step 4 and execute step 5 directly, but with step 4, step 5 always works, maybe there are some bugs.  

Just FYI.  

diff --git a/src/crimson/os/futurized_store.cc b/src/crimson/os/futurized_store.cc
index b9542a50c60..8326c9e90e4 100644
--- a/src/crimson/os/futurized_store.cc
+++ b/src/crimson/os/futurized_store.cc
@@ -20,12 +20,13 @@ FuturizedStore::create(const std::string& type,
     return seastar::make_ready_future<std::unique_ptr<FuturizedStore>>(
       std::make_unique<CyanStore>(data));
   } else if (type == "seastore") {
+    std::string dev = data + std::to_string(seastar::this_shard_id());
+    std::cout<<"------seastore dev = "<<dev<<std::endl;
     return crimson::os::seastore::make_seastore(
-      data, values
+      dev, values
     ).then([] (auto seastore) {
       return seastar::make_ready_future<std::unique_ptr<FuturizedStore>>(
-       std::make_unique<ShardedStoreProxy<seastore::SeaStore>>(
-         seastore.release()));
+         seastore.release());
     });
   } else {
     using crimson::os::AlienStore;
diff --git a/src/crimson/osd/shard_stores.h b/src/crimson/osd/shard_stores.h
index 701ccd9076e..16fe70ada9f 100644
--- a/src/crimson/osd/shard_stores.h
+++ b/src/crimson/osd/shard_stores.h
@@ -9,7 +9,9 @@

 static inline bool multicore_store() {
   return (crimson::common::local_conf().get_val<std::string>
-    ("osd_objectstore") == "cyanstore");
+    ("osd_objectstore") == "cyanstore" ||
+    crimson::common::local_conf().get_val<std::string>
+    ("osd_objectstore") == "seastore" );
 }

**Comment by liu-chunmei** [comment]
@athanatos  I am going to move shard features to cyanstore interface.  I plan to create a sharded class and move each cyanstore member functions used by each pg shard to that sharded class,  then when each pg shard call store member functions, will convert to that shard local to execute that function, does this what you mean?

**Comment by athanatos** [comment]
That sounds reasonable.  The external interface should remain the same (without the proxy wrapper), but internally CyanStore invokes the method on the correct seastar::sharded instance.

**Pull request closed without merging**
