### PR TITLE
pybind/mgr: tox.ini remove redundant `tox` env

### PR DESCRIPTION
**Pull request by phlogistonjohn**
Fixes: https://tracker.ceph.com/issues/57153

The envlist contained an environment named `lint`. There was no specific
customization of the lint testenv so it is essentially the same as
running the `py3` testenv.

This was probably a typo and was meant to be `pylint`. Unfortunately,
the pylint test env does not appear to work, probably because it was
never run as part of any automation. At the risk of leaving old stuff
behind I'm not removing the pylint testenv at the moment, only the
`lint` item in order to not run redundant tests.

Signed-off-by: John Mulligan <jmulligan@redhat.com>

 

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Review by tchaikov — APPROVED** [review]
thanks for the detailed commit message.

**Comment by adk3798** [comment]
jenkins test api

**Review by rkachach — APPROVED** [review]

**Comment by tchaikov** [comment]
```
=========================== short test summary info ============================
FAILED orchestrator/tests/test_orchestrator.py::test_orch_ps - AssertionError...
FAILED orchestrator/tests/test_orchestrator.py::test_orch_host_ls - Assertion...
FAILED orchestrator/tests/test_orchestrator.py::test_orch_device_ls - Asserti...
======= 3 failed, 1282 passed, 5 skipped, 9 warnings in 80.21s (0:01:20) =======
```

**Comment by tchaikov** [comment]
jenkins test make check

**Review by adk3798 — APPROVED** [review]

**Comment by adk3798** [comment]
> ```
> =========================== short test summary info ============================
> FAILED orchestrator/tests/test_orchestrator.py::test_orch_ps - AssertionError...
> FAILED orchestrator/tests/test_orchestrator.py::test_orch_host_ls - Assertion...
> FAILED orchestrator/tests/test_orchestrator.py::test_orch_device_ls - Asserti...
> ======= 3 failed, 1282 passed, 5 skipped, 9 warnings in 80.21s (0:01:20) =======
> ```

seeing these now locally in the py37 tests. Happens on just main branch as well so it isn't this PR causing it. I'll try to find a fix

**Comment by adk3798** [comment]
jenkins test make check

**Comment by adk3798** [comment]
jenkins test api

**Comment by adk3798** [comment]
jenkins test make check

**Comment by adk3798** [comment]
jenkins test api

**Comment by phlogistonjohn** [comment]
jenkins test api

**Comment by adk3798** [comment]
jenkins test api

**Pull request merged**
