### PR TITLE
msg/async/kqueue: avoid remove nonexist kqueue event

### PR DESCRIPTION
**Pull request by yuyuyu101**
Signed-off-by: Haomai Wang <haomai@xsky.com>

### CODE REVIEW

**Comment by wjwithagen** [comment]
@yuyuyu101 
Looks a lot like wat I was trying... 8D
But I'll give your version a run for its money.

**Comment by yuyuyu101** [comment]
@wjwithagen do you have ceph dev env setup scripts or guide on freebsd, like install-deps.sh. I left bsd system too long time and forget most of things. I just create a freebsd vm on digitalocean and want to test kqueue backend

**Comment by yuyuyu101** [comment]
oh sorry, I found do_freebsd.sh

**Comment by yuyuyu101** [comment]
@wjwithagen I ran ceph_test_msgr with this commit, it looks kqueue behavior correctly. Could you verify this again?

**Comment by yuyuyu101** [comment]
@wjwithagen ping?

**Comment by wjwithagen** [comment]
@yuyuyu101 
Sorry, I did not get any notice of your ping.
But I'm currently more than happy with how this works.
so LGTM

**Pull request merged**
