### PR TITLE
Objecter: fix several flaws introduced by the enumeration_objects API

### PR DESCRIPTION
**Pull request by xiexingguo**

### CODE REVIEW

**Comment by xiexingguo** [comment]
@liewegas Some simple fixes:-) that may take you only a couple of minutes.

**Comment by jcsp** [comment]
The enumerate fixes look good to me

**Comment by liewegas** [comment]
These all look good except for the race condition fix.  Can you drop that patch from this series?

Instead, I think we should call the g_conf->should_gather(...) helper so that we can avoid taking the locks and calling the _dump* methods entirely if the log level is low.  As things currently stand, we are iterating over all those maps even if nothing is logged/printed, which is a waste of CPU.  Adding the proper locking is making that even more expensive.

Thanks!

**Comment by xiexingguo** [comment]
@liewegas Dropped. Have a nice day :-)

**Pull request merged**
