### PR TITLE
systemd: no rbdmap systemd unit file

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/13678

### CODE REVIEW

**Comment by smithfarm** [comment]
@dachary This will need gitbuilder validation.

**Comment by dachary** [comment]
in http://ceph.com/gitbuilder.cgi as suse-wip-13678-infernalis

**Comment by smithfarm** [comment]
@dachary It seems to have passed the CentOS gitbuilders. The Fedora 22 failure is due to environmental noise (disk full IIRC).

**Comment by dachary** [comment]
@smithfarm could you please rebase ?

**Comment by smithfarm** [comment]
@dachary My pleasure.

**Pull request merged**
