### PR TITLE
install-deps: remove the legacy resolver flags 

### PR DESCRIPTION
**Pull request by nizamial09**
This was a workaround that was introduced long time ago. This will be
something that could be deprectaed at some point [1]. And its preventing some of the dependencies to be
downloaded or stored into the wheelhouse. Deps like jsonschema, parse,
mypy, cryptography etc.

[1] https://pip.pypa.io/en/latest/user_guide/#deprecation-timeline
Fixes: https://tracker.ceph.com/issues/62082

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by ljflores** [comment]
@nizamial09 I'm guessing this draft is to test the recent make check failure? I raised a tracker for it here: https://tracker.ceph.com/issues/62082

**Comment by nizamial09** [comment]
> @nizamial09 I'm guessing this draft is to test the recent make check failure? I raised a tracker for it here: https://tracker.ceph.com/issues/62082
> 
> Are you testing a fix here? If so, feel free to add it to the tracker.

thanks @ljflores will update the tracker.

**Comment by phlogistonjohn** [comment]
I don't know if this is helpful or not but it seems like the failures are in the `src/tools/setup-virtualenv.sh` script and that maybe a dependency changed and now it can't find the packages (honestly I find this script way under-documented). I was just looking at this script because it had a side effect due to the plan on adding dependencies to the cephadm binary in #52492. So if you want to bounce ideas off someone I'm happy to help.  Thanks!

**Comment by nizamial09** [comment]
> maybe a dependency changed and now it can't find the packages

do you think the dependency is on the ceph or something changed from pip? i can see some of the jenkins machines like irvingi for example is passing the make check but all other seems to be failing!

**Comment by phlogistonjohn** [comment]
Assuming I'm right about `src/tools/setup-virtualenv.sh` what do you think about just starting by adding a `set -x` to the top of the script so we can see exactly what command is failing?

**Comment by nizamial09** [comment]
I ended up studying how the dependencies are installed on the make-checks. Basically the `install-deps` script installs all the python dependencies and store them in the `wheelhouse` folder. So when the `tox` requires a dependency, its fetched from the `wheelhouse` folder rather than going online. But for some reason, the `jsonschema, cryptography, mypy...` deps are not getting saved to the wheelhouse folder when these `--use-feature=fast-deps --use-deprecated=legacy-resolver` flags are set. Since it was introduced as a workaround in pip20.3, which was useful upto pip 21 I think (I read that somewhere but I lost the link, maybe if I go through history I can find it again). 

So I removed this flags which resolves this issue. Not sure if its the best/right approach to the problem.

[This run](https://jenkins.ceph.com/job/ceph-pull-requests/118607/console) was successful with the `setup-venv`'s. But it got aborted when I pushed again. So maybe it'll pass again in the current run.

**Comment by ljflores** [comment]
> I ended up studying how the dependencies are installed on the make-checks. Basically the `install-deps` script installs all the python dependencies and store them in the `wheelhouse` folder. So when the `tox` requires a dependency, its fetched from the `wheelhouse` folder rather than going online. But for some reason, the `jsonschema, cryptography, mypy...` deps are not getting saved to the wheelhouse folder when these `--use-feature=fast-deps --use-deprecated=legacy-resolver` flags are set. Since it was introduced as a workaround in pip20.3, which was useful upto pip 21 I think (I read that somewhere but I lost the link, maybe if I go through history I can find it again).
> 
> So I removed this flags which resolves this issue. Not sure if its the best/right approach to the problem.
> 
> [This run](https://jenkins.ceph.com/job/ceph-pull-requests/118607/console) was successful with the `setup-venv`'s. But it got aborted when I pushed again. So maybe it'll pass again in the current run.

I found the same issue with /wheelhouse, and I was able to fix it by removing a line in install-deps.sh that updates pip. (See PR #52558). A new version of pip was released a few days ago, which is I think what caused the change.

Up to you which method you want to use, but it looks like both fix the issue.

**Review by ljflores — APPROVED** [review]
Approving, but take a look at #52558 and let me know what you think works best.

**Comment by nizamial09** [comment]
> Approving, but take a look at #52558 and let me know what you think works best.

I added my thought there! I am a bit uncertain which will work the best. I'll let others take a look at these.

**Review by idryomov — APPROVED** [review]

**Comment by idryomov** [comment]
@badone Could you please sanity check this against what lead to https://github.com/ceph/ceph/pull/43221?  If `install-deps.sh` runs into a similar issue with the "new" resolver in the future, how would we notice that it's happening in Jenkins?

Perhaps we should consider wrapping `pip install` with a timeout?

**Comment by idryomov** [comment]
> Since it was introduced as a workaround in pip20.3, which was useful upto pip 21 I think (I read that somewhere but I lost the link, maybe if I go through history I can find it again).

@nizamial09 It would be very nice to add that to the commit message.  We are removing a workaround that was in place for almost two years, having an explanation for why it's no longer needed with a link is miles better than "Not sure if this is still valid."

**Comment by nizamial09** [comment]
> > Since it was introduced as a workaround in pip20.3, which was useful upto pip 21 I think (I read that somewhere but I lost the link, maybe if I go through history I can find it again).
> 
> @nizamial09 It would be very nice to add that to the commit message. We are removing a workaround that was in place for almost two years, having an explanation for why it's no longer needed with a link is miles better than "Not sure if this is still valid."

@idryomov I couldn't find the url. But there is this [documentation](https://pip.pypa.io/en/latest/user_guide/#changes-to-the-pip-dependency-resolver-in-20-3-2020) that explains why we should be using the new dependency resolver rather than using the legacy resolver. And moreover, this looks like something that [could be deprecated](https://pip.pypa.io/en/latest/user_guide/#deprecation-timeline) when the community decides. And the more viable solution is to be more strict with our pip dependencies. 

I'll update the commit with these links.

**Comment by ljflores** [comment]
@nizamial09 want to merge this?

**Comment by nizamial09** [comment]
> @nizamial09 want to merge this?

@ljflores I think we can. Please do the honors. I am connected through phone now.

**Comment by ljflores** [comment]
@nizamial09 should be backported to Reef too.

**Comment by nizamial09** [comment]
> @nizamial09 should be backported to Reef too. It doesn't seem to cherry-pick cleanly, so take a look.

alright!

**Comment by nizamial09** [comment]
@ljflores https://github.com/ceph/ceph/pull/52562

**Comment by idryomov** [comment]
> Perhaps we should consider wrapping `pip install` with a timeout?

Noting that `--timeout 300` is already passed in `PIP_OPTS`.

**Comment by nizamial09** [comment]
> > Perhaps we should consider wrapping `pip install` with a timeout?
> 
> Noting that `--timeout 300` is already passed in `PIP_OPTS`.

I forgot about this, but thanks for confirming.

**Comment by phlogistonjohn** [comment]
Possibly related: https://github.com/pypa/pip/issues/12156
So FWIW pip developers are aware of issues with the legacy resolver in 23.2.

**Comment by nizamial09** [comment]
> Possibly related: [pypa/pip#12156](https://github.com/pypa/pip/issues/12156) So FWIW pip developers are aware of issues with the legacy resolver in 23.2.

ah good! atleast its being tracked in the community. thanks for pointing it out. @phlogistonjohn

**Pull request merged**
