### PR TITLE
erasure-code: add clay codes

### PR DESCRIPTION
**Pull request by liewegas**
Replaces #14300

### CODE REVIEW

**Comment by liewegas** [comment]
@mynaramana can you look at the second commit and confirm that ec profile makes sense?  I'm not sure what **w** means or whether the default value (8?) is fine.  Thanks!

**Comment by mynaramana** [comment]
Hi Sage,

The erasure code profile looks good. For clay codes w is set as 8. It doesnt have to be given as parameter.

Thanks!

**Comment by liewegas** [comment]
http://pulpito.ceph.com/sage-2018-09-06_19:02:31-rados:thrash-erasure-code-wip-sage3-testing-2018-09-06-1148-distro-basic-smithi ... that's just the clay code cases, and it looks good.

**Comment by tchaikov** [comment]
closing in favor of #24291

**Pull request closed without merging**
