### PR TITLE
kv/RocksDBStore: extract common code to a new function

### PR DESCRIPTION
**Pull request by liupan1111**
1) two set(...) functions have most of same code.
2) submit_transaction and submit_transaction_sync has almost same code, accept "sync" option value.

### CODE REVIEW

**Comment by liupan1111** [comment]
@liewegas  please help take a look, thanks.

**Comment by liupan1111** [comment]
retest this please

**Comment by tchaikov** [comment]
retest this please

**Comment by liupan1111** [comment]
Finished rebase, retest this please.

**Comment by liupan1111** [comment]
@tchaikov could you help test it? Thanks!

**Comment by liupan1111** [comment]
@joscollin could you help test this? Thanks!

**Comment by joscollin** [comment]
@liupan1111 
I prefer not to test a PR that I don't review. It's better if the reviewer himself test the PR. I see that @liewegas  has already added a `needs-qa` label. So it will be tested soon.

**Comment by liupan1111** [comment]
@joscollin yes, reasonable to me. Thank you all the same!

**Pull request merged**
