### PR TITLE
quincy: docs/releases: update quincy release notes tracker 55383 known issue

### PR DESCRIPTION
**Pull request by zdover23**
Signed-off-by: Vikhyat Umrao <vikhyat@redhat.com>
(cherry picked from commit d59e376b13d8bc2f3604b06d228fa371c53f32a0)
Signed-off-by: Zac Dover <zac.dover@gmail.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/master/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [x] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [x] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Review by anthonyeleven — CHANGES_REQUESTED** [review]
I'm slightly confused -- this appears to add `quincy.rst` in-toto, but the file already exists.  What am I missing?

**Comment by zdover23** [comment]
> I'm slightly confused -- this appears to add `quincy.rst` in-toto, but the file already exists. What am I missing?

`quincy.rst` exists in the `master` branch, but it doesn't exist yet in the `quincy` branch. This PR is a backport that will fix that.

Here is the current state of the `quincy` branch:

https://github.com/ceph/ceph/tree/quincy/doc/releases

(Note to the future: at the time that I posted this link, no `quincy.rst` file was present in the `/doc/releases/` directory on the `quincy` branch.)

This PR is one of a number of PRs that will backport information from `master` to the correct branches. Probably there will be hundreds of these PRs over the coming months.

There remains a bit of wiring and debugging left to do before this passes all of the CI tests, as shown in this warning message:

> checking consistency... /home/jenkins-build/build/workspace/ceph-pr-docs/doc/releases/quincy.rst: WARNING: document isn't included in any toctree

Anyway: this is a backport into a branch that doesn't yet have a `quincy.rst` file in it.

**Review by anthonyeleven — APPROVED** [review]

**Review by idryomov — CHANGES_REQUESTED** [review]
This PR is supposed to be a documentation backport but it touches a lot more than that: files in `src/librbd/cache/pwl`, `src/mon`, `src/mount`, `ceph.spec.in`, etc.  Zac, you would probably need to start over and redo the cherry-pick from scratch.

**Comment by zdover23** [comment]
> This PR is supposed to be a documentation backport but it touches a lot more than that: files in `src/librbd/cache/pwl`, `src/mon`, `src/mount`, `ceph.spec.in`, etc. Zac, you would probably need to start over and redo the cherry-pick from scratch.

I'm doing that now, Ilya.

**Pull request closed without merging**
