### PR TITLE
nautilus: mon: Log "ceph health detail" periodically in cluster log

### PR DESCRIPTION
**Pull request by neha-ojha**
backport tracker: https://tracker.ceph.com/issues/48227

---

backport of https://github.com/ceph/ceph/pull/37902
parent tracker: https://tracker.ceph.com/issues/48042

this backport was staged using ceph-backport.sh version 16.0.0.6848
find the latest version at https://github.com/ceph/ceph/blob/master/src/script/ceph-backport.sh

### CODE REVIEW

**Review by jdurgin — APPROVED** [review]

**Comment by yuriw** [comment]
@neha-ojha I can't build with this PT pls see https://jenkins.ceph.com/job/ceph-dev-new-build/ARCH=x86_64,AVAILABLE_ARCH=x86_64,AVAILABLE_DIST=centos7,DIST=centos7,MACHINE_SIZE=gigantic/48321//consoleFull

/home/jenkins-build/build/workspace/ceph-dev-new-build/ARCH/x86_64/AVAILABLE_ARCH/x86_64/AVAILABLE_DIST/centos7/DIST/centos7/MACHINE_SIZE/gigantic/release/14.2.13-58-g737b3101/rpm/el7/BUILD/ceph-14.2.13-58-g737b3101/src/mon/Monitor.cc: In member function 'void Monitor::do_health_to_clog(bool)':
/home/jenkins-build/build/workspace/ceph-dev-new-build/ARCH/x86_64/AVAILABLE_ARCH/x86_64/AVAILABLE_DIST/centos7/DIST/centos7/MACHINE_SIZE/gigantic/release/14.2.13-58-g737b3101/rpm/el7/BUILD/ceph-14.2.13-58-g737b3101/src/mon/Monitor.cc:2785:26: error: 'class HealthMonitor' has no member named 'get_health_status'; did you mean 'get_health_checks'?
     level = healthmon()->get_health_status(true, nullptr, &details);
                          ^~~~~~~~~~~~~~~~~
                          get_health_checks

**Comment by neha-ojha** [comment]
@yuriw ready for you to retest

**Comment by neha-ojha** [comment]
https://pulpito.ceph.com/yuriw-2020-11-17_21:44:35-rados-wip-yuri6-testing-2020-11-17-1134-nautilus-distro-basic-smithi/ - tests have passed, merge after 14.2.14

**Comment by yuriw** [comment]
@neha-ojha pls rebase

**Comment by yuriw** [comment]
jenkins test this please

**Comment by neha-ojha** [comment]
jenkins test make check

**Comment by yuriw** [comment]
jenkins test make check

**Comment by yuriw** [comment]
@neha-ojha this PR can be merged any time after make check passed

**Comment by badone** [comment]
Build failure is due to importlib-metadata being updated in the last couple of days and breaking the build. Fix proposed in #38296

**Comment by badone** [comment]
Please rebase.

**Comment by tchaikov** [comment]
jenkins test make check

**Pull request merged**
