### PR TITLE
doc/cephadm/administration: clarify log gathering

### PR DESCRIPTION
**Pull request by smithfarm**
This is an attempt to bring the current state of the documentation more
into line with the current state of the cephadm code.

However, when I try to grab logs from a daemon on a host other than the
one where the daemon is running, I get an empty log...

References: https://tracker.ceph.com/issues/44354
Signed-off-by: Nathan Cutler <ncutler@suse.com>

## Checklist
- [x] References tracker ticket
- [x] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by liewegas** [comment]
It would also be good to have a section about how logs go to the container log by default, but if you want traditional /var/log/ceph-style logs, you need to 
```
ceph config set global log_to_file true
ceph config set global log_to_stderr
ceph config set global mon_cluster_log_to_file true
```
etc

**Comment by smithfarm** [comment]
@liewegas I have osd.0 running on "node1". When I do the following on a different node, "admin", I get:

```
admin:~ # cephadm logs --fsid 2757319a-5a1f-11ea-8132-525400fc4b2d --name osd.0
-- Logs begin at Fri 2020-02-28 12:27:51 CET, end at Fri 2020-02-28 18:23:14 CET. --
-- No entries --
```

If I do the exact same command on "node1", I get the normal osd.0 log messages. I guess this is a bug - see https://tracker.ceph.com/issues/44354

**Comment by smithfarm** [comment]
> It would also be good to have a section about how logs go to the container log by default, but if you want traditional /var/log/ceph-style logs, you need to
> 
> ```
> ceph config set global log_to_file true
> ceph config set global log_to_stderr
> ceph config set global mon_cluster_log_to_file true
> ```
> 
> etc

And to get them from the very beginning, you'd have to put those settings into a file and pass it to `cephadm bootstrap` via the `-c` option...

**Comment by liewegas** [comment]
Perhaps a ``--use-traditional-log-files`` option to bootstrap might be useful?

**Comment by smithfarm** [comment]
> Perhaps a `--use-traditional-log-files` option to bootstrap might be useful?

Since there is just a limited number of use cases for setting non-default config options via `cephadm bootstrap -c`, sure, it might make sense to implement a special command line to `cephadm bootstrap` for each of those use cases.

In addition to `--use-traditional-log-files` I can think of:

1. `--osd-crush-chooseleaf-type` (needs to be 0 for single-node clusters)
2. `--debug-mon` for debugging the first MON as it comes up
3. `--debug-mgr` for debugging the first MGR as it comes up

**Comment by sebastian-philipp** [comment]
> @liewegas I have osd.0 running on "node1". When I do the following on a different node, "admin", I get:
> 
> ```
> admin:~ # cephadm logs --fsid 2757319a-5a1f-11ea-8132-525400fc4b2d --name osd.0
> -- Logs begin at Fri 2020-02-28 12:27:51 CET, end at Fri 2020-02-28 18:23:14 CET. --
> -- No entries --
> ```
> 
> However, if I do the exact same command on "node1", I get the normal osd.0 log messages. I guess this is a bug - see https://tracker.ceph.com/issues/44354

`cephadm` doesn't do any remote ssh calls. All it does is to give insights into the local host. there is no command to fetch the logs from remote hosts right now. I really have to explain this somewhere.

**Pull request merged**
