### PR TITLE
qa: postgresql test suite workunit

### PR DESCRIPTION
**Pull request by batrick**
This PR also adds snap schedules for fs:workload to exercise snapshots during the postgres task. That will also affect other workunits.

* https://tracker.ceph.com/issues/23724
* https://tracker.ceph.com/issues/55470

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [x] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by batrick** [comment]
Still iterating on tests to reproduce problem in https://tracker.ceph.com/issues/54546

**Comment by batrick** [comment]
jenkins test make check arm64

**Comment by batrick** [comment]
jenkins test windows

**Comment by batrick** [comment]
https://tracker.ceph.com/projects/cephfs/wiki/Main#2022-Sep-22

**Comment by batrick** [comment]
Now shows type of dentry damage (we're looking for "dentry" damage):

https://pulpito.ceph.com/pdonnell-2022-09-26_16:35:43-fs-wip-pdonnell-testing-20220923.171109-distro-default-smithi/7044452/

**Comment by batrick** [comment]
https://tracker.ceph.com/projects/cephfs/wiki/Main#2022-Sep-26

**Review by vshankar — APPROVED** [review]

**Pull request merged**
