### PR TITLE
luminous: repeated eviction of idle client until some IO happens

### PR DESCRIPTION
**Pull request by batrick**
http://tracker.ceph.com/issues/24295

### CODE REVIEW

**Comment by smithfarm** [comment]
jenkins re-test this please (logs are gone, but there was a make check failure)

**Comment by batrick** [comment]
@smithfarm should be resolved now

**Comment by yuriw** [comment]
[wip-yuri2-testing-2018-07-26-1628-luminous](https://trello.com/c/WOQfNKOf/353-wip-yuri2-testing-2018-07-26-1628-luminous)

**Comment by batrick** [comment]
`Reviewed-by: Patrick Donnelly <pdonnell@redhat.com>`

**Pull request merged**
