### PR TITLE
[WIP] octopus: mgr/dashboard: displaying deleting status in the OSD list

### PR DESCRIPTION
**Pull request by callithea**
backport tracker: https://tracker.ceph.com/issues/48380

---

backport of https://github.com/ceph/ceph/pull/35039
parent tracker: https://tracker.ceph.com/issues/45301

this backport was staged using ceph-backport.sh version 16.0.0.6848
find the latest version at https://github.com/ceph/ceph/blob/master/src/script/ceph-backport.sh

### CODE REVIEW

**Comment by callithea** [comment]
jenkins retest this please

**Comment by nizamial09** [comment]
jenkins test make check

**Comment by nizamial09** [comment]
jenkins test api

**Comment by callithea** [comment]
jenkins retest this please

**Comment by callithea** [comment]
Depends on #38888

**Comment by tchaikov** [comment]
jenkins test make check

**Comment by votdev** [comment]
jenkins retest this please

**Comment by epuertat** [comment]
@callithea @votdev this seems to be the error (missing Orchestrator related PR):

```
[build:en-US -- -- --progress=false] ERROR in app/ceph/cluster/osd/osd-list/osd-list.component.ts:25:36 - error TS2307: Cannot find module '../../../../shared/models/orchestrator.interface'.
[build:en-US -- -- --progress=false] 
[build:en-US -- -- --progress=false] 25 import { OrchestratorStatus } from '../../../../shared/models/orchestrator.interface';
[build:en-US -- -- --progress=false]                                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[build:en-US -- -- --progress=false] app/ceph/cluster/osd/osd-list/osd-list.component.ts:86:14 - error TS2304: Cannot find name 'OrchestratorFeature'.
[build:en-US -- -- --progress=false] 
[build:en-US -- -- --progress=false] 86     create: [OrchestratorFeature.OSD_CREATE],
[build:en-US -- -- --progress=false]                 ~~~~~~~~~~~~~~~~~~~
[build:en-US -- -- --progress=false] app/ceph/cluster/osd/osd-list/osd-list.component.ts:87:14 - error TS2304: Cannot find name 'OrchestratorFeature'.
[build:en-US -- -- --progress=false] 
[build:en-US -- -- --progress=false] 87     delete: [OrchestratorFeature.OSD_DELETE]
[build:en-US -- -- --progress=false]                 ~~~~~~~~~~~~~~~~~~~
[build:en-US -- -- --progress=false] app/ceph/cluster/osd/osd-list/osd-list.component.ts:376:29 - error TS2339: Property 'getTableActionDisableDesc' does not exist on type 'OrchestratorService'.
[build:en-US -- -- --progress=false] 
[build:en-US -- -- --progress=false] 376     return this.orchService.getTableActionDisableDesc(
[build:en-US -- -- --progress=false]                                 ~~~~~~~~~~~~~~~~~~~~~~~~~
[build:en-US -- -- --progress=false] 
```

**Comment by callithea** [comment]
jenkins retest this please

**Comment by epuertat** [comment]
@callithea I think the error you're getting here is due to `OrchestratorFeature` introduced by [this PR](https://github.com/ceph/ceph/pull/34918) (which was never backported to Octopus).

**Comment by callithea** [comment]
I think it makes sense to re-create the PR if necessary.

**Pull request closed without merging**
