### PR TITLE
mon: ceph osd setcrushmap: test_with_crushtool improvements

### PR DESCRIPTION
**Pull request by trociny**
This is #3774 rebased against master

### CODE REVIEW

**Comment by dachary** [comment]
@trociny could you please rebase ?

**Comment by dachary** [comment]
@trociny could you please remove the CEPH_VSTART_WRAPPER related logic ? We can rely on --injectargs crushtool to locate the crushtool binary.

**Comment by trociny** [comment]
@dachary this is what I was going to discuss before removing.

After rebase, we have your test_mon_crushmap_validation and my test_mon_crushtool, which supersedes yours, so I am going to delete test_mon_crushmap_validation.

For test_mon_crushmap_validation to work you made '--injectargs crushtool' work, though as I mentioned then I had concerns to the implementation. As '--injectargs crushtool'  is needed only for testing and I have provided a solution in test_mon_crushtool that does not require it (though more complicated) may be we use it and remove '--injectargs crushtool'  feature?

If people think that '--injectargs crushtool' should stay as is then I will remove CEPH_VSTART_WRAPPER related logic and will use --injectargs crushtool.

**Comment by trociny** [comment]
Ok. I have updated my tests to use  '--injectargs crushtool' feature.

**Comment by liewegas** [comment]
@tchaikov now that hammer is out the door should we still do this for master?  looks like a cleaner approach to me!

**Comment by tchaikov** [comment]
@trociny i am not sure that e08bccf is necessary. i removed it and the `./test/cephtool-test-mon.sh` passed in my testbed. what do you think?

**Comment by trociny** [comment]
@tchaikov without  e08bccf, by default, mons started by vstart.sh will use for testing crushtool found in standard PATH. So depending on your environment you may have different results e.g. crushtool not found or using a wrong version.

**Comment by trociny** [comment]
@tchaikov just to make it more clear,  e08bccf is not necessary for test/cephtool-test-mon.sh, because the wrapper sets path properly, it is needed if a developer runs ./ceph osd setcrushmap in src dir and wants to be sure that src/crushtool is used here.

**Comment by tchaikov** [comment]
thank you @trociny for your detailed explanation. i should have read your discussion with @dachary more carefully. i understand now. you are improving the usability of vstart. in that case, `ceph-osd` is not able to locate crushtool without a proper $PATH or the pull path to this tool. changing the $PATH is a good way, but i tend to agree with Loic that we could be more specific when pointing ceph-osd to the crushtool's path. let me make an analogy, if we want to allow a user to burn cdroms, maybe i have some options:

1. add the user to the `cdrom` group
1. add this user to sudoer file, with a line of `alice ALL=(ALL:ALL) ALL`.
1. make the cdrom device world writable.

if i were the system administrator, i would go with option 1. the same goes with this PR.

and as a developer who runs `./ceph osd setcrushmap`, maybe he/she will simply `injectargs --crushtool "${crushtool_path}" .

BTW, probably a little bit off topic: why we are exec crushtool for this? instead of using `CrushTester::test()` directly?

**Comment by trociny** [comment]
If a daemon is expected to run binaries from a dir, I think the PATH should include this directory as the first one by default. So I still think the change to add src dir in vstart.sh srcipt is correct.

Even if a developer could make './ceph osd setcrushmap' work by fixing crushtool_path with injectargs, imaging how much time she would require to figure out why './ceph osd setcrushmap' does not work and how to fix this?

Personally, I would like to have 'crushtool' configuration parameter to be set by default to the path where crushtool utility is expected to be installed (e.g. crushtool = /usr/bin/crushtool), i.e. to the absolute path, so exec does not search executing arbitrarily found binary, but run the binary installed by this package. I suppose the path should be determined during autoconfigure/make using PREFIX or something like this, but I am not so familiar with all this stuff to provide a patch. The thing is complicated by the fact that destination directory can be changed after build, e.g. by setting DESTDIR for 'make install'...

> BTW, probably a little bit off topic: why we are exec'ing crushtool for this? instead of using CrushTester::test() directly? 

See https://github.com/ceph/ceph/pull/3522.

**Comment by tchaikov** [comment]
> Even if a developer could make './ceph osd setcrushmap' work by fixing crushtool_path with injectargs, imaging how much time she would require to figure out why './ceph osd setcrushmap' does not work and how to fix this?

yes, that's would spend her a while to walk through the code and test for grep'ing the "setcrushmap", i would say. but we can hardly help her if she wants to use the pre-packaged binaries prepared by the packager or the ceph-osd installed by `make install` other than the error message of
```
Error EINVAL: Failed to parse crushmap: crushtool: exec failed: (2) No such file or directory
```

> Personally, I would like to have 'crushtool' configuration parameter to be set by default to the path where crushtool utility is expected to be installed (e.g. crushtool = /usr/bin/crushtool), i.e. to the absolute path, so exec does not search executing arbitrarily found binary, but run the binary installed by this package. I suppose the path should be determined during autoconfigure/make using PREFIX or something like this, but I am not so familiar with all this stuff to provide a patch.

yes, we could help our users (developers also, maybe) with a default path which is configured using `configure`. this probably can be achieved by

1. a `config_opts.h.in` file, and the `configure` will substitute the `@PREFIX@` with `$prefix` specified at configure time. or
1. we can also generate the `config_opts.h` in Makefile according to the `$PREFIX` passed in when `make`ing. but it would be overkill, IMHO. or
1. a `ceph.conf` shipped along with the binary. that would be ideal solution. as a side effect, that could also fix http://tracker.ceph.com/issues/11389 .

**Comment by liewegas** [comment]
I think having vstart add it to the path (for ceph-mon) is the simplest 
approach and totally sufficient.

**Pull request merged**
