### PR TITLE
RGW: remove duplicate include header files in rgw_rados.cc

### PR DESCRIPTION
**Pull request by gaosibei**
we remove the header files in  rgw_rados.cc which have already been included in rgw_rados.h

Signed-off-by: Sibei Gao <gaosb@inspur.com>

### CODE REVIEW

**Comment by gaosibei** [comment]
@ wjwithagen @mattbenjamin 
can you approve this PR?

**Comment by gaosibei** [comment]
@wjwithagen
can you take a look?

**Comment by wjwithagen** [comment]
@tchaikov 
Kefu, can you take this one in one of your QA runs?

**Comment by wjwithagen** [comment]
@tchaikov 
Not sure I can follow you, but Clang is notouriously more picky about unresolved refences.
So I would expect that a succesfull compilation and testrun would be anough shake out.

**Comment by tchaikov** [comment]
@wjwithagen it's all about implicit and explicit dependencies. for example, if `a.cc` uses `Foo` declared in `a.hh`, apparently, we should `#include "a.hh"`. because it's an explicit dependency.

 but `a.cc` also happens to `#include "b.hh"`, and `b.hh` (indirectly) includes `a.hh`. and `b.hh` is *not* an interface header file including `a.hh` . 

in this case, i don't think we should remove `#include "a.hh"` from `a.cc`.

**Comment by wjwithagen** [comment]
@tchaikov 
I see, will check.

**Comment by wjwithagen** [comment]
@tchaikov 
All three are also included in rgw_rados.h
So that would exclude all 3 deletes in you opinion?
Then we should close this PR.

**Comment by tchaikov** [comment]
i am afraid that i am in the best position to answer your question. as i am not familiar with RGW.

**Comment by wjwithagen** [comment]
@tchaikov 
Oke I'll try to find somebody else in the RGW world.
But on the other hand, your criteria are more abstract, and just of code "quality".
And the test you stipulated fails on all three include removals, thus rendering this PR void.

**Comment by wjwithagen** [comment]
@mattbenjamin 
Could you check if we can commit or close this PR?

**Comment by cbodley** [comment]
http://pulpito.ceph.com/cbodley-2018-09-18_18:33:41-rgw-wip-cbodley-testing-distro-basic-smithi/

**Pull request merged**
