### PR TITLE
ceph-detect-init: fix linux distro detection

### PR DESCRIPTION
**Pull request by dalgaaf**
The platform.linux_distribution function is deprecated and
no longer part of recent 3.x python. Replace it with the
recommended 'distro' pypi package.

This also fixes "make check' tests (run-tox-ceph-detect-init,
run-tox-ceph-disk) on recent openSUSE versions.

### CODE REVIEW

**Comment by dalgaaf** [comment]
@liewegas What would be the preferred way? Merge it into master and backport it then or pull it directly in mimic?

**Comment by alfredodeza** [comment]
I am going to be -1 on this one going straight to master. 

If we *really* wanted to add better support for distro detection for ceph-disk in say, Luminous we can just look into `/etc/os-release`, this is how ceph-deploy does it:

https://github.com/ceph/ceph-deploy/blob/master/ceph_deploy/hosts/remotes.py#L53

**Comment by alfredodeza** [comment]
@dalgaaf certainly not in mimic. ceph-disk is frozen in mimic (and has the 'deprecated' banner all over it). This would need to probably target Luminous only, but then again *if* we really think that it is worth adding that support for ceph-disk in Luminous

**Comment by liewegas** [comment]
Regardless of whether it's deprecated I think we should put the fix in the latest branch that has the code and backport from there.

**Comment by dalgaaf** [comment]
@alfredodeza it's not really adding any additional support. It fixes the existing code to work e.g. on openSUSE Tumbleweed. Here platform.linux_distribution() doesn't return anything (only: ('', '', '')) and leads to an error, it could be an bug on openSUSE but since platform.linux_distribution() is deprecated anyway in recent python3, The issues hunts me since a while, but I ignored it till now. I think we should fix it for those releases which still support it. 

Anyway isn't ceph-deploy deprecated too?

**Comment by alfredodeza** [comment]
@dalgaaf the support on ceph-deploy was done for the same reasons (python 3 deprecation/removal of linux_distribution) by SUSE. We shouldn't get this into master because we are removing ceph-disk. 

@liewegas I was under the impression that ceph-disk was frozen for mimic, so no new updates/fixes since ceph-volume had reached feature parity and could be used for all new use cases. If we want to move forward with this, then the PR should only target Mimic, and backport to Luminous, like you suggest.

I am hesitant on the dependency, I would prefer to reuse the ceph-deploy approach.

**Pull request closed without merging**
