### PR TITLE
hammer: Multipart ListPartsResult has missing quotes on ETag

### PR DESCRIPTION
**Pull request by Vicente-Cheng**
http://tracker.ceph.com/issues/15343

### CODE REVIEW

**Comment by oritwas** [comment]
This needs also #8394

**Comment by mattbenjamin** [comment]
@smithfarm is this moving towards merge (backport urgent in tracker)

**Comment by oritwas** [comment]
lgtm

**Comment by smithfarm** [comment]
@mattbenjamin It is included in the current integration testing round. Status is always available at http://tracker.ceph.com/issues/15895

**Pull request merged**
