### PR TITLE
[DNM] octopus: mgr/dashboard: Remove yargs-parser vulnerability warning

### PR DESCRIPTION
**Pull request by tspmelo**
Replaced 2 npm packages with ones that have their internal packages updated.

Fixes: https://tracker.ceph.com/issues/47972

Signed-off-by: Tiago Melo <tmelo@suse.com>

## Checklist
- [x] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by tspmelo** [comment]
I tried to use an alias for the new packages, but didn't get it working.
If anyone knows if its possible and how to do it, let me know so I don't need to change the package name in all this files.

**Comment by LenzGr** [comment]
We probably need to add a description about why this PR is against the Octopus branch directly and not handled via a backport?

**Comment by tspmelo** [comment]
@LenzGr yes, thanks for the reminder.

**Comment by tspmelo** [comment]
jenkins test dashboard

**Comment by tspmelo** [comment]
jenkins test dashboard

**Comment by votdev** [comment]
jenkins test dashboard

**Comment by tspmelo** [comment]
We need to find a better solution.

**Pull request closed without merging**
