### PR TITLE
jewel: Error EINVAL: removing mon.a at 172.21.15.16:6789/0, there will be 1 monitors

### PR DESCRIPTION
**Pull request by Abhishekvrshny**
http://tracker.ceph.com/issues/17904

### CODE REVIEW

**Comment by jecluis** [comment]
lgtm, although the commit dropping the 'goto' statements is a lot more about aesthetics than bug fixing - i don't think it causes any harm by being backported anyway.

**Comment by ktdreyer** [comment]
@theanalyst , @athanatos , should this go in before v10.2.4?

**Comment by athanatos** [comment]
I think this still needs to be tested.  @Abhishekvrshny @dachary ?

**Comment by dachary** [comment]
@athanatos @ktdreyer this is @theanalyst decision.

**Comment by theanalyst** [comment]
@dachary @athanatos did this pass through an integration run already (looks harmless to include IMO)

**Comment by dachary** [comment]
It was included in http://tracker.ceph.com/issues/17851#note-9 which had a flawless rados suite run at http://tracker.ceph.com/issues/17851#note-12 . Note however that this is the usual X/2000 designed for pre-merge verification and not the X/50 designed to validate a release.

**Comment by dachary** [comment]
@athanatos by merging in jewel-next you targeted 10.2.5. Please speak up if you wanted this pull request in 10.2.4 instead.

**Comment by athanatos** [comment]
@dachary Sorry, didn't notice.  Can you move it over?

**Comment by dachary** [comment]
@athanatos I'll do it

**Pull request merged**
