### PR TITLE
 qa: Move fs creation/removal to CephFSTestCase class 

### PR DESCRIPTION
**Pull request by kotreshhr**
There is no functional change with this patch. It's
re-org of the code.

The 'CephFSTestCase' class creates the filesystem based on
'REQUIRE_FILESYSTEM' flag in setUp. The 'TestVolume' class
which inherits 'CephFSTestCase' also has the code to create
filesystem which never gets executed. This patch removes this
redundant and dead code.

Also the 'CephFSTestCase' class doesn't cleanup the filesystem
created in setUp in the corresponding tearDown function but
instead cleans up any existing filesystems in setUp prior to
new filesystem creation. Though there is no functional impact,
cleaning it up in tearDown is neat. This patch does the same.
It also retains the filesysytem clean up code in setUp as is
which helps running the test suit on cluster with existing
filesystems.

Fixes: https://tracker.ceph.com/issues/46769
Signed-off-by: Kotresh HR <khiremat@redhat.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by kotreshhr** [comment]
Blocks on https://github.com/ceph/ceph/pull/32581 Please check https://github.com/ceph/ceph/pull/36155#discussion_r461933798

**Comment by kotreshhr** [comment]
> I think deleting FSs in `CephFSTestCase.setUp()` is an better idea since the leftover FS from testcase makes it easier to inspect and investigate in case the testcase fails.

Yes, that's a valid point. Just to note, I have not removed clean up code in setUp but also added in tearDown. I am fine removing only dead code and keep the earlier behavior. I would like to hear from others @batrick @ajarr @vshankar ?

**Comment by batrick** [comment]
> Yes, that's a valid point. Just to note, I have not removed clean up code in setUp but also added in tearDown. I am fine removing only dead code and keep the earlier behavior. I would like to hear from others @batrick @ajarr @vshankar ?

I think the issue @rishabh-d-dave is trying to raise is that if the test fails then tearDown may still be run. That makes it difficult to debug when tests fail in vstart_runner.py.

**Comment by kotreshhr** [comment]
> > Yes, that's a valid point. Just to note, I have not removed clean up code in setUp but also added in tearDown. I am fine removing only dead code and keep the earlier behavior. I would like to hear from others @batrick @ajarr @vshankar ?
> 
> I think the issue @rishabh-d-dave is trying to raise is that if the test fails then tearDown may still be run. That makes it difficult to debug when tests fail in vstart_runner.py.

Yes, I got that, wanted another opinion. I will remove the fs cleanup in tearDown for better debug-ability and retain the earlier behavior.

**Review by batrick — CHANGES_REQUESTED** [review]
Please rebase.

**Comment by batrick** [comment]
> I think deleting FSs in `CephFSTestCase.setUp()` is an better idea since the leftover FS from testcase makes it easier to inspect and investigate in case the testcase fails.

Sorry I'm going to flip-flop on my opinion. This is the rationale for `--interactive` in vstart_runner.py. I think `tearDown` should remove everything left behind. @kotreshhr please go ahead and revive your previous change.

**Comment by rishabh-d-dave** [comment]
@kotreshhr @batrick 

My memory served me right, vstart_runner.py enters the interactive shell after running the teardown (which deletes the Ceph FSs). This is undesirable from debugging's POV and, therefore, would require some more changes IMO. Below is an example (where I made the test fail by appending `assert False`to the test method) -

```
2020-09-25 22:39:26,712.712 INFO:__main__:> cephfs-shell -b /tmp/test-cephfss4ymile5
2020-09-25 22:39:27,052.052 INFO:__main__:> sudo umount /tmp/tmpfou2y01j/mnt.0
2020-09-25 22:39:27,083.083 INFO:__main__:> rmdir -- /tmp/tmpfou2y01j/mnt.0
2020-09-25 22:39:27,086.086 INFO:tasks.cephfs.filesystem:Destroying file system cephfs and related pools
2020-09-25 22:39:27,086.086 INFO:__main__:> ./bin/ceph fs fail cephfs
2020-09-25 22:39:27,947.947 INFO:__main__:> ./bin/ceph fs rm cephfs --yes-i-really-mean-it
2020-09-25 22:39:29,058.058 INFO:__main__:> ./bin/ceph osd pool rm cephfs_metadata cephfs_metadata --yes-i-really-really-mean-it
2020-09-25 22:39:30,200.200 INFO:__main__:> ./bin/ceph osd pool rm cephfs_data cephfs_data --yes-i-really-really-mean-it
2020-09-25 22:39:31,223.223 INFO:__main__:> ./bin/ceph config rm mon mon_allow_pool_delete
2020-09-25 22:39:31,587.587 INFO:__main__:> ./bin/ceph log Ended test tasks.cephfs.test_cephfs_shell.TestCD.test_cd_with_args
2020-09-25 22:39:32,311.311 INFO:__main__:Test that when cd is issued with an argument, CWD is changed ... FAIL
2020-09-25 22:39:32,311.311 ERROR:__main__:Traceback (most recent call last):
  File "/home/rishabh/repos/ceph/master/qa/tasks/cephfs/test_cephfs_shell.py", line 510, in test_cd_with_args
    assert False
AssertionError

2020-09-25 22:39:32,312.312 ERROR:__main__:Failure in test 'test_cd_with_args (tasks.cephfs.test_cephfs_shell.TestCD)
Test that when cd is issued with an argument, CWD is changed', going interactive
Ceph test interactive mode, use ctx to interact with the cluster, press control-D to exit...
>>> 
now exiting InteractiveConsole...
2020-09-25 22:40:27,784.784 INFO:__main__:Stopped test: test_cd_with_args (tasks.cephfs.test_cephfs_shell.TestCD)
Test that when cd is issued with an argument, CWD is changed in 76.630554s
2020-09-25 22:40:27,785.785 INFO:__main__:
2020-09-25 22:40:27,785.785 INFO:__main__:======================================================================
2020-09-25 22:40:27,786.786 INFO:__main__:FAIL: test_cd_with_args (tasks.cephfs.test_cephfs_shell.TestCD)
2020-09-25 22:40:27,786.786 INFO:__main__:Test that when cd is issued with an argument, CWD is changed
2020-09-25 22:40:27,786.786 INFO:__main__:----------------------------------------------------------------------
2020-09-25 22:40:27,787.787 INFO:__main__:Traceback (most recent call last):
2020-09-25 22:40:27,787.787 INFO:__main__:  File "/home/rishabh/repos/ceph/master/qa/tasks/cephfs/test_cephfs_shell.py", line 510, in test_cd_with_args
2020-09-25 22:40:27,787.787 INFO:__main__:    assert False
2020-09-25 22:40:27,787.787 INFO:__main__:AssertionError
2020-09-25 22:40:27,788.788 INFO:__main__:
2020-09-25 22:40:27,788.788 INFO:__main__:----------------------------------------------------------------------
2020-09-25 22:40:27,788.788 INFO:__main__:Ran 1 test in 76.632s

```

**Comment by batrick** [comment]
> @kotreshhr @batrick
> 
> My memory served me right, vstart_runner.py enters the interactive shell after running the teardown (which deletes the Ceph FSs). This is undesirable from debugging's POV and, therefore, would require some more changes IMO. Below is an example (where I made the test fail by appending `assert False`to the test method) -

I see. Well that stinks. For the record, the way we trigger interactive mode is by hooking this class:

https://docs.python.org/3/library/unittest.html#unittest.TestResult

But there is no method called in that class **before** `tearDown`. So it looks like we would have to build our own thing. I have an attempt here but it's unfinished: https://github.com/ceph/ceph/pull/37421

**Comment by batrick** [comment]
This is a good fix @kotreshhr and would be nice to get in soon to fix this class of failures: https://tracker.ceph.com/issues/46769#note-8

**Pull request closed without merging**
