### PR TITLE
mgr/dashboard: fix error shown when no rgw daemons are running.

### PR DESCRIPTION
**Pull request by alfonsomthd**
- Adapted code to changes introduced in: https://github.com/ceph/ceph/pull/40220
- Improved error handling.
- Increased test coverage.
- Some refactoring.
- Simplified documentation about setting default daemon host and port.

Fixes: https://tracker.ceph.com/issues/49655
Signed-off-by: Alfonso Martínez <almartin@redhat.com>

## Checklist
- [x] References tracker ticket
- [ ] Updates documentation if necessary
- [x] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Review by epuertat — APPROVED** [review]
Looks good and happy to see the coverage in the unit test section!

**Comment by avanthakkar** [comment]
jenkins test dashboard

**Review by avanthakkar — APPROVED** [review]
LGTM!

**Review by nizamial09 — APPROVED** [review]
Tested! LGTM

**Comment by liewegas** [comment]
jenkins test dashboard

**Comment by liewegas** [comment]
```
  Running:  rgw/daemons.e2e-spec.ts                                                       (14 of 22)
  Estimated: 36 seconds


  RGW daemons page
    breadcrumb and tab tests
      â should open and show breadcrumb (2538ms)
      â should show two tabs (774ms)
      â should show daemons list tab at first (674ms)
      â should show overall performance as a second tab (609ms)
    details and performance counters table tests
      1) should check that details/performance tables are visible when daemon is selected


  4 passing (4m)
  1 failing

  1) RGW daemons page
       details and performance counters table tests
         should check that details/performance tables are visible when daemon is selected:
     AssertionError: Timed out retrying: Expected to find element: `cd-table`, but never found it. Queried from element: <div.tab-content>
      at DaemonsPageHelper.getTableCell (https://irvingi07.front.sepia.ceph.com:41342/__cypress/tests?p=cypress/integration/rgw/daemons.e2e-spec.ts:391:14)
      at DaemonsPageHelper.checkTables (https://irvingi07.front.sepia.ceph.com:41342/__cypress/tests?p=cypress/integration/rgw/daemons.e2e-spec.ts:403:14)
      at Context.eval (https://irvingi07.front.sepia.ceph.com:41342/__cypress/tests?p=cypress/integration/rgw/daemons.e2e-spec.ts:359:21)
```

**Comment by alfonsomthd** [comment]
@liewegas changes introduced in https://github.com/ceph/ceph/pull/40220 have side effects on some API endpoints.

Working on it.

**Pull request merged**
