### PR TITLE
Jewel 14380

### PR DESCRIPTION
**Pull request by ukernel**

### CODE REVIEW

**Comment by jcsp** [comment]
Looks good

**Comment by gregsfortytwo** [comment]
See http://gitbuilder.sepia.ceph.com/gitbuilder-ceph-tarball-trusty-amd64-basic/log.cgi?log=9d70891a17548a0c97169785b059f916bc4e6b28 for failure in test_ceph_argparse.

**Comment by gregsfortytwo** [comment]
Okay, I'm not sure why but the output's better in this one: http://gitbuilder.sepia.ceph.com/gitbuilder-ceph-tarball-trusty-amd64-basic/log.cgi?log=acb3467d224fecf842439e6e24cd201ee258598d

**Comment by gregsfortytwo** [comment]
http://pulpito.ceph.com/gregf-2016-01-26_15:35:20-fs-greg-fs-testing-126---basic-mira/

**Pull request merged**
