### PR TITLE
run-make-check: pass -Werror when compiling C++ code and a couple cleanups

### PR DESCRIPTION
**Pull request by tchaikov**
## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by tchaikov** [comment]
jenkins test make check

**Review by rzarzynski — APPROVED** [review]

**Comment by rzarzynski** [comment]
Related: https://github.com/ceph/ceph/pull/42787.

**Comment by rzarzynski** [comment]
There is a warning on fresh `master` when building Seastar:

```
In file included from ../src/seastar/src/net/tls.cc:37:
../src/seastar/include/seastar/net/stack.hh:37:25: warning: <E2><80><98>virtual seastar::data_source seastar::net::connected_socket_impl::source(seastar::connected_socket_input_stream_config)<E2><80><99> wa
s hidden [-Woverloaded-virtual]
   37 |     virtual data_source source(connected_socket_input_stream_config csisc);
      |                         ^~~~~~
../src/seastar/src/net/tls.cc:1555:17: note:   by <E2><80><98>virtual seastar::data_source seastar::tls::tls_connected_socket_impl::source()<E2><80><99>
 1555 |     data_source source() override;
      |                 ^~~~~~
```

Fix: https://github.com/scylladb/seastar/commit/ddad9cf21aa49a51d96014ec51b918a4759fd7c6.

**Comment by tchaikov** [comment]
> There is a warning on fresh `master` when building Seastar:
> 
> ```
> In file included from ../src/seastar/src/net/tls.cc:37:
> ../src/seastar/include/seastar/net/stack.hh:37:25: warning: <E2><80><98>virtual seastar::data_source seastar::net::connected_socket_impl::source(seastar::connected_socket_input_stream_config)<E2><80><99> wa
> s hidden [-Woverloaded-virtual]
>    37 |     virtual data_source source(connected_socket_input_stream_config csisc);
>       |                         ^~~~~~
> ../src/seastar/src/net/tls.cc:1555:17: note:   by <E2><80><98>virtual seastar::data_source seastar::tls::tls_connected_socket_impl::source()<E2><80><99>
>  1555 |     data_source source() override;
>       |                 ^~~~~~
> ```
> 
> Fix: [scylladb/seastar@ddad9cf](https://github.com/scylladb/seastar/commit/ddad9cf21aa49a51d96014ec51b918a4759fd7c6).

@rzarzynski could you send this patch to seatar-dev?

**Comment by rzarzynski** [comment]
@tchaikov: sure, will upstream it.

**Review by cbodley — APPROVED** [review]

**Pull request merged**
