### PR TITLE
nautilus: New msgr2 crc and secure modes (msgr2.1)

### PR DESCRIPTION
**Pull request by idryomov**
Backport of #35078 (changes from #34927 which got merged via #35078 already in nautilus).

Moderate conflicts, all documented inline.

### CODE REVIEW

**Comment by yuriw** [comment]
[wip-yuri2-testing-2020-07-01-1702-nautilus](https://trello.com/c/QsEZp3Cg/948-wip-yuri2-testing-2020-07-01-1702-nautilus)

**Comment by idryomov** [comment]
@yuriw Please drop it for now, it suffers from the same issue as the octopus branch.  I'll add the fix from #35816 and ping you.

**Comment by idryomov** [comment]
@yuriw This is still DNM.  There is a subtle issue that I'm currently tracking down.

**Comment by yuriw** [comment]
[wip-yuri-testing-2020-07-08-1951-nautilus](https://trello.com/c/eezspgCH/953-wip-yuri-testing-2020-07-08-1951-nautilus)

**Comment by yuriw** [comment]
@idryomov we suspect this PR is failing builds
http://hastebin.com/relivoceci
@neha-ojha FYI

**Comment by idryomov** [comment]
@yuriw Correct, I haven't bothered pushing the fix for the build failure as there is a deeper issue here that is being investigated.

**Comment by idryomov** [comment]
-s rados/singleton-nomsgr --filter 'all/health-warnings rados' -N 20:

https://pulpito.ceph.com/dis-2020-07-13_14:08:26-rados:singleton-nomsgr-wip-msgr21-nautilus-distro-basic-smithi/

**Comment by idryomov** [comment]
@yuriw @neha-ojha Taking DNM off.

**Comment by idryomov** [comment]
I tracked it down to the interaction of `INTERCEPT` framework and `NetworkStack::get_worker()`.  Pulled in commit 5cf027d27e5d ("msg/async: don't forget dec(Worker::references) when met error.") from #31929.

**Comment by yuriw** [comment]
@idryomov ok testing this alone

**Comment by yuriw** [comment]
[wip-yuri4-testing-2020-07-13-1935-nautilus](https://trello.com/c/1RQihhoW/960-wip-yuri4-testing-2020-07-13-1935-nautilus)

**Comment by idryomov** [comment]
-s rados/singleton-nomsgr --filter 'all/health-warnings rados' -N 200:

https://pulpito.ceph.com/dis-2020-07-13_16:40:12-rados:singleton-nomsgr-wip-msgr21-nautilus-distro-basic-smithi/

@neha-ojha One suspicious failure, but it doesn't appear to be related to the messenger.  osd.1 couldn't come up because osd.9 kept telling it that it had died (`MOSDPing` with `YOU_DIED`).  Not sure why it never moved to a newer osdmap...

**Comment by yuriw** [comment]
@idryomov it passed tests and @neha-ojha reviewed/approved it https://trello.com/c/1RQihhoW
So pls merge is all is done here.

**Comment by neha-ojha** [comment]
> -s rados/singleton-nomsgr --filter 'all/health-warnings rados' -N 200:
> 
> https://pulpito.ceph.com/dis-2020-07-13_16:40:12-rados:singleton-nomsgr-wip-msgr21-nautilus-distro-basic-smithi/
> 
> @neha-ojha One suspicious failure, but it doesn't appear to be related to the messenger. osd.1 couldn't come up because osd.9 kept telling it that it had died (`MOSDPing` with `YOU_DIED`). Not sure why it never moved to a newer osdmap...

doesn't look related

**Comment by idryomov** [comment]
@yuriw What about upgrade tests?

**Comment by yuriw** [comment]
@idryomov @neha-ojha https://pulpito.ceph.com/yuriw-2020-07-16_15:35:27-upgrade-wip-yuri4-testing-2020-07-13-1935-nautilus-distro-basic-smithi

**Comment by yuriw** [comment]
@idryomov @neha-ojha what's next ? do we want this in next release?

**Comment by idryomov** [comment]
Yes, we do.  I was waiting for Neha to look at the upgrade runs.

Radek should review shortly.

**Comment by neha-ojha** [comment]
> Yes, we do. I was waiting for Neha to look at the upgrade runs.

There seem to be a lot of failures in the nautilus baseline upgrade run, which can mask real bugs. I'll triage those and decide whether we need to redo upgrade tests for this PR.

> 
> Radek should review shortly.

**Comment by yuriw** [comment]
[wip-yuri-testing-2020-07-27-1614-nautilus](https://trello.com/c/7kQyT5fs/977-wip-yuri-testing-2020-07-27-1614-nautilus)

**Comment by yuriw** [comment]
See more testing info https://trello.com/c/7kQyT5fs

and per @neha-ojha 
"Failures tracked in:
https://tracker.ceph.com/issues/46804 https://tracker.ceph.com/issues/43048"

**Comment by smithfarm** [comment]
I find it odd that no PendingReleaseNote was added for this... would it make sense to write one and add it to the 14.2.11 blog post and the 14.2.11 release notes in master?

(If someone comes up with such a release note, I could take care of getting it into the right places.)

**Pull request merged**
