### PR TITLE
nautilus: msg/async: perform the v2 resets in proper EventCenter

### PR DESCRIPTION
**Pull request by smithfarm**
backport trackers:

* https://tracker.ceph.com/issues/42856
* https://tracker.ceph.com/issues/43775
* https://tracker.ceph.com/issues/43832

---

backport of 

* https://github.com/ceph/ceph/pull/27094
* https://github.com/ceph/ceph/pull/30717
* https://github.com/ceph/ceph/pull/32352
* https://github.com/ceph/ceph/pull/32732

parent trackers:

* https://tracker.ceph.com/issues/42026
* https://tracker.ceph.com/issues/43070
* https://tracker.ceph.com/issues/43667

this backport was staged using ceph-backport.sh version 15.0.0.6950
find the latest version at https://github.com/ceph/ceph/blob/master/src/script/ceph-backport.sh

### CODE REVIEW

**Comment by rzarzynski** [comment]
Hi @smithfarm! My suggestion would be to backport these patches with the related fix for `local_connection` (https://tracker.ceph.com/issues/43775).

**Comment by jtlayton** [comment]
jenkins test make check

**Comment by smithfarm** [comment]
```
/home/jenkins-build/build/workspace/ceph-pull-requests/src/msg/async/AsyncMessenger.cc: In member function 'virtual int AsyncMessenger::shutdown()':
/home/jenkins-build/build/workspace/ceph-pull-requests/src/msg/async/AsyncMessenger.cc:345:21: error: 'class AsyncConnection' has no member named 'clear_priv'; did you mean 'set_priv'?
   local_connection->clear_priv();
                     ^~~~~~~~~~
                     set_priv
src/msg/CMakeFiles/common-msg-objs.dir/build.make:302: recipe for target 'src/msg/CMakeFiles/common-msg-objs.dir/async/AsyncMessenger.cc.o' failed
make[3]: *** [src/msg/CMakeFiles/common-msg-objs.dir/async/AsyncMessenger.cc.o] Error 1
```

**Comment by smithfarm** [comment]
@rzarzynski There is no `clear_priv` method in nautilus. Should I drop the commit "msg/async: use dedicated method for clearing conn's priv up" or would you rather have me try to backport whatever commit(s) added that method?

**Comment by rzarzynski** [comment]
@smithfarm: let's drop 16f152b60caf6402af6f283453abb8e361b8669c – it's a just a clean-up. In `master` all it does is:

```cpp
  void clear_priv() {
    std::lock_guard l{lock};
    priv.reset(nullptr);
  }
```

while `set_priv()`:
```cpp
  void set_priv(const RefCountedPtr& o) {
    std::lock_guard l{lock};
    priv = o;
  }
```

In `nautilus` `set_priv()` is:

```cpp
  void set_priv(const RefCountedPtr& o) {
    Mutex::Locker l(lock);
    priv = o;
  }
```

**Comment by yuriw** [comment]
[wip-yuri-testing-2020-02-08-1638-nautilus](https://trello.com/c/WGSzqecu/820-wip-yuri-testing-2020-02-08-1638-nautilus)

**Comment by yuriw** [comment]
@smithfarm suspect to cause failures  "Command failed on smithi150 with status 1: 'sudo ceph --cluster ceph osd crush tunables default'"

http://pulpito.ceph.com/yuriw-2020-02-09_16:26:19-rados-wip-yuri-testing-2020-02-08-1638-nautilus-distro-basic-smithi/

**Comment by smithfarm** [comment]
@rzarzynski With this PR in the integration branch, `sudo ceph --cluster ceph osd crush tunables default` dumps core as described by @yuriw in the previous comment. Can you take a look?

**Comment by rzarzynski** [comment]
@smithfarm: I'm on it. The trace isn't particularly helpful.
```
    "backtrace": [
        "(()+0x12890) [0x7fc66bf96890]",
        "(pthread_kill()+0x31) [0x7fc66bf932d1]",
        "(ceph::HeartbeatMap::_check(ceph::heartbeat_handle_d const*, char const*, unsigned long)+0x468) [0x555931c5abc8]",
        "(ceph::HeartbeatMap::reset_timeout(ceph::heartbeat_handle_d*, unsigned long, unsigned long)+0x8a) [0x555931c5b3aa]",
        "(ShardedThreadPool::shardedthreadpool_worker(unsigned int)+0x498) [0x555931c7c3c8]",
        "(ShardedThreadPool::WorkThreadSharded::entry()+0x10) [0x555931c7f630]",
        "(()+0x76db) [0x7fc66bf8b6db]",
        "(clone()+0x3f) [0x7fc66ad2b88f]"
    ]
```
```cpp
  was = h->suicide_timeout;
  if (was && was < now) {
    ldout(m_cct, 1) << who << " '" << h->name << "'"
                    << " had suicide timed out after " << h->suicide_grace << dendl;
    pthread_kill(h->thread_id, SIGABRT);
    sleep(1);
    ceph_abort_msg("hit suicide timeout");
  }
```
It was a suicide which in turn could have a root cause of messenger:

**Comment by rzarzynski** [comment]
@smithfarm, @yuriw: I've reverted 57b0bad, built new packages [on top of the Yuri's branch](https://github.com/ceph/ceph-ci/commits/wip-rzarzynski-wip-yuri-testing-2020-02-08-1638-nautilus) and [scheduled first failing job 32 times](http://pulpito.ceph.com/rzarzynski_pr32922/) – all these entries are green.

**Comment by smithfarm** [comment]
closing in favor of https://github.com/ceph/ceph/pull/33714

**Pull request closed without merging**
