### PR TITLE
mgr/dashboard: rgw multisite topology view shows blank table for multisite entities

### PR DESCRIPTION
**Pull request by aaSharma14**
Toplology view in multi-site dashboard displaying blank table regarding realm, zonegroup and zones in chrome browser

Fixes: https://tracker.ceph.com/issues/62677

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Review by nizamial09 — APPROVED** [review]

**Review by Pegonzal — COMMENTED** [review]
Is the scroller something we actually want in the multisite page? I feel like we are not taking advantage of the space we actually have here and adding a scroller without real need.

image


I think we could add a condition to activate/deactivate the scroller in the `cd-table-key-value` component and deactivate for this use case.

Another option could be to have different `css` classes with different heights and select the one most appropiate for the use case, depending on the available space for the table

**Comment by nizamial09** [comment]
> the table to overflow the page dimensions in some cases

@aaSharma14: isn't there a scroll-bar dedicated to the page rather than the details section?

**Comment by aaSharma14** [comment]
> > the table to overflow the page dimensions in some cases
> 
> @aaSharma14: isn't there a scroll-bar dedicated to the page rather than the details section?

The page is scrollable as well..for this to work we probably need to remove the bottom padding of the page

**Comment by nizamial09** [comment]
since this a quick bug fix, i am okay with as it is

**Review by Pegonzal — APPROVED** [review]

**Pull request merged**
