### PR TITLE
rgw: fix bucket_index::cancel , bs is wild pointer

### PR DESCRIPTION
**Pull request by Guokexin**
failed to get BucketShard object, bs is wild pointer.

Signed-off-by: kexin <kexin@xsky.com>

### CODE REVIEW

**Comment by joscollin** [comment]
Test Result:

- http://pulpito.front.sepia.ceph.com/jcollin-2017-09-12_03:55:26-rgw-wip-jcollin-testing_09-12-2017-distro-basic-smithi/
- http://pulpito.front.sepia.ceph.com/compare/?branch=wip-jcollin-testing_09-12-2017&suite=rgw

**Comment by yuriw** [comment]
@Guokexin pls rebase
--- pr 17587 --- pulling https://github.com/Guokexin/ceph.git branch fix_bucket_index_cancel_crash
remote: Counting objects: 5, done.
remote: Total 5 (delta 4), reused 4 (delta 4), pack-reused 1
Unpacking objects: 100% (5/5), done.
From https://github.com/Guokexin/ceph
 * branch            fix_bucket_index_cancel_crash -> FETCH_HEAD
Auto-merging src/rgw/rgw_rados.cc
CONFLICT (file/directory): There is a directory with name src/dmclock in 5d10ef6ece1ee7547aca6b7869c590d65d1ba200. Adding src/dmclock as src/dmclock~HEAD
Adding qa/suites/rgw/verify/frontend
Adding qa/suites/rgw/tempest/frontend
Adding qa/suites/rgw/multisite/frontend
Adding qa/suites/rbd/mirror/cluster
Adding qa/suites/rbd/mirror/base
Adding qa/suites/ceph-deploy/basic/distros/ubuntu_latest.yaml
Adding qa/suites/ceph-deploy/basic/distros/centos_latest.yaml
Adding qa/suites/ceph-deploy/basic/distros/.qa
warning: inexact rename detection was skipped due to too many files.
warning: you may want to set your merge.renamelimit variable to at least 1947 and retry the command.
Automatic merge failed; fix conflicts and then commit the result.
Traceback (most recent call last):
  File "/home/yuriw/wip_master/src/script/build-integration-branch", line 62, in <module>
    assert not r
AssertionError

**Comment by mattbenjamin** [comment]
@joscollin please rebase

**Comment by yuriw** [comment]
@Guokexin sill conflicts 

--- pr 17587 --- pulling https://github.com/Guokexin/ceph.git branch fix_bucket_index_cancel_crash
remote: Enumerating objects: 4, done.
remote: Counting objects: 100% (4/4), done.
remote: Total 5 (delta 4), reused 4 (delta 4), pack-reused 1
Unpacking objects: 100% (5/5), done.
From https://github.com/Guokexin/ceph
 * branch            fix_bucket_index_cancel_crash -> FETCH_HEAD
Auto-merging src/rgw/rgw_rados.cc
CONFLICT (file/directory): There is a directory with name src/dmclock in 5d10ef6ece1ee7547aca6b7869c590d65d1ba200. Adding src/dmclock as src/dmclock~HEAD
Adding qa/suites/rgw/verify/frontend
Adding qa/suites/rgw/tempest/frontend
Adding qa/suites/rgw/multisite/frontend
Adding qa/suites/rbd/mirror/cluster
Adding qa/suites/rbd/mirror/base
Adding qa/suites/multimds/thrash/mount
Adding qa/suites/multimds/basic/mount
warning: inexact rename detection was skipped due to too many files.
warning: you may want to set your merge.renamelimit variable to at least 2755 and retry the command.
Automatic merge failed; fix conflicts and then commit the result.
Traceback (most recent call last):
  File "/home/yuriw/wip_master/src/script/build-integration-branch", line 62, in <module>
    assert not r
AssertionError

**Pull request closed without merging**
