### PR TITLE
pacific: os/bluestore: cumulative bluefs backport

### PR DESCRIPTION
**Pull request by ifed01**
This includes:
- os/bluestore: BlueFS fine grain locking
(https://github.com/ceph/ceph/pull/43794)
- os/bluestore/bluefs: Fix improper vselector tracking in _flush_special()
https://github.com/ceph/ceph/pull/44955
- os/bluestore: enable 4K allocation unit for BlueFS
 https://github.com/ceph/ceph/pull/48854
- os/bluestore/bluefs: Fix sync compaction
https://github.com/ceph/ceph/pull/44913/commits/4fd98ce0359d6c3a36f08a3d87a78c3f0b65018d

Signed-off-by: Igor Fedotov <igor.fedotov@croit.io>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by ifed01** [comment]
jenkins test make check

**Comment by ifed01** [comment]
jenkins test make check

**Comment by aclamk** [comment]
`options/global.yaml.in` dragged in by mistake.

**Comment by ifed01** [comment]
> `options/global.yaml.in` dragged in by mistake.

Fixed

**Review by aclamk — APPROVED** [review]
I was thinking that the use of UPDATE_INC op in BlueFS will be a blocker for this backport.
I completely forgot that we already merged https://github.com/ceph/ceph/pull/48915, which I believe was a mistake - we broke downgrading in the same version line.

But since it is already done, I think we can extent Pacific logic with this cumulative set of features.

**Comment by aclamk** [comment]
jenkins test api

**Comment by YiteGu** [comment]
> I was thinking that the use of UPDATE_INC op in BlueFS will be a blocker for this backport. I completely forgot that we already merged #48915, which I believe was a mistake - we broke downgrading in the same version line.
> 
> But since it is already done, I think we can extent Pacific logic with this cumulative set of features.

Yes, we released #48915, but didn't seem to tell the user that can not downgrading. I only found out after the upgrade was completed.

**Comment by YiteGu** [comment]
Hi, @ifed01 Why do we need bluefs_failed_shared_alloc_cooldown? Isn't it good for bluefs to directly use 4k alloc units?

**Comment by ifed01** [comment]
> Hi, @ifed01 Why do we need bluefs_failed_shared_alloc_cooldown? Isn't it good for bluefs to directly use 4k alloc units?

Using 4K chunks is potentially less effective in terms of metadata size - file allocation map will generally contain more entries which takes more RAM and might impact the performance. Hence we still trying to use large chunks if possible and rollback to them if this failed at some point

**Comment by YiteGu** [comment]
> > Hi, @ifed01 Why do we need bluefs_failed_shared_alloc_cooldown? Isn't it good for bluefs to directly use 4k alloc units?
> 
> Using 4K chunks is potentially less effective in terms of metadata size - file allocation map will generally contain more entries which takes more RAM and might impact the performance. Hence we still trying to use large chunks if possible and rollback to them if this failed at some point

thanks, I got it.

**Review by YiteGu — APPROVED** [review]

**Comment by ljflores** [comment]
Rados approved: https://tracker.ceph.com/projects/rados/wiki/PACIFIC#httpstrellocomcTw3vOIOj1819-wip-yuri2-testing-2023-08-08-0755-pacific

**Pull request merged**
