### PR TITLE
pybind/cephfs: add special values for not reading conffile

### PR DESCRIPTION
**Pull request by tchaikov**
Signed-off-by: Kefu Chai <kchai@redhat.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by tchaikov** [comment]
jenkins test docs

**Comment by tchaikov** [comment]
@batrick could you take a quick look? if this change is not relevant i will close it.

**Comment by rishabh-d-dave** [comment]
@tchaikov I am reassigning the related tracker ticket (https://tracker.ceph.com/issues/44415) to you.

**Comment by tchaikov** [comment]
@rishabh-d-dave updated the commit message. and i reset the backport field of the tracker ticket you created. there is no need to backport a cleanup.

**Comment by tchaikov** [comment]
jenkins test dashboard backend

**Comment by jdurgin** [comment]
the same logic is in rados.pyx - may want to make the same change there

**Comment by tchaikov** [comment]
> the same logic is in rados.pyx - may want to make the same change there

@jdurgin thanks for your review. updated accordingly.

**Comment by tchaikov** [comment]
jenkins test make check

**Comment by tchaikov** [comment]
@batrick fixed and repushed.

**Comment by tchaikov** [comment]
jenkins retest this please.

**Comment by tchaikov** [comment]
- https://pulpito.ceph.com/kchai-2020-07-06_04:02:43-rados-wip-kefu-testing-2020-07-06-1016-distro-basic-smithi/
- https://pulpito.ceph.com/kchai-2020-07-06_11:39:50-rados-wip-kefu-testing-2020-07-06-1016-distro-basic-smithi/

**Comment by tchaikov** [comment]
@batrick i think the issue you pointed out has been fixed. would you mind reviewing again?

**Pull request merged**
