### PR TITLE
kv/RocksDBStore: Configure compact-on-deletion for all CFs

### PR DESCRIPTION
**Pull request by baergj**
update_column_family_options() is called only for non-default CFs, whereas load_rocksdb_options() sets options for all CFs, including default. This isn't really a problem for new installs, where the default CF isn't used for very much, but for upgrades where resharding has not yet happened, the bulk of rocksdb data is still in the default CF and so it's important that it also gets compact-on-deletion configured, if desired.

Fixes: https://tracker.ceph.com/issues/64511

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Comment by baergj** [comment]
Before changes:
```
2024-02-20T21:48:35.805+0000 7f7938faa200  4 rocksdb: [column_family.cc:552] --------------- Options for column family [default]:
2024-02-20T21:48:35.805+0000 7f7938faa200  4 rocksdb:                   Options.table_properties_collectors:
```

After:
```
2024-02-20T21:44:13.097+0000 7f325fcc7200  4 rocksdb: [column_family.cc:552] --------------- Options for column family [default]:
2024-02-20T21:44:13.097+0000 7f325fcc7200  4 rocksdb:                   Options.table_properties_collectors: CompactOnDeletionCollector;
```

**Comment by baergj** [comment]
jenkins test make check

**Comment by markhpc** [comment]
@baergj It's been a little while since I've looked at how column families have options set.  Just to be sure, did you verify it's still working properly for the non-default column families?

**Comment by baergj** [comment]
@markhpc Yup! Here's the full output for the after case:
```
2024-02-20T21:44:25.902+0000 7f325fcc7200  4 rocksdb: [column_family.cc:552] --------------- Options for column family [default]:
2024-02-20T21:44:25.902+0000 7f325fcc7200  4 rocksdb:                   Options.table_properties_collectors: CompactOnDeletionCollector;
2024-02-20T21:44:25.902+0000 7f325fcc7200  4 rocksdb: [column_family.cc:552] --------------- Options for column family [m-0]:
2024-02-20T21:44:25.902+0000 7f325fcc7200  4 rocksdb:                   Options.table_properties_collectors: CompactOnDeletionCollector;
2024-02-20T21:44:25.902+0000 7f325fcc7200  4 rocksdb: [column_family.cc:552] --------------- Options for column family [m-1]:
2024-02-20T21:44:25.902+0000 7f325fcc7200  4 rocksdb:                   Options.table_properties_collectors: CompactOnDeletionCollector;
2024-02-20T21:44:25.902+0000 7f325fcc7200  4 rocksdb: [column_family.cc:552] --------------- Options for column family [m-2]:
2024-02-20T21:44:25.902+0000 7f325fcc7200  4 rocksdb:                   Options.table_properties_collectors: CompactOnDeletionCollector;
2024-02-20T21:44:25.902+0000 7f325fcc7200  4 rocksdb: [column_family.cc:552] --------------- Options for column family [p-0]:
2024-02-20T21:44:25.902+0000 7f325fcc7200  4 rocksdb:                   Options.table_properties_collectors: CompactOnDeletionCollector;
2024-02-20T21:44:25.902+0000 7f325fcc7200  4 rocksdb: [column_family.cc:552] --------------- Options for column family [p-1]:
2024-02-20T21:44:25.902+0000 7f325fcc7200  4 rocksdb:                   Options.table_properties_collectors: CompactOnDeletionCollector;
2024-02-20T21:44:25.902+0000 7f325fcc7200  4 rocksdb: [column_family.cc:552] --------------- Options for column family [p-2]:
2024-02-20T21:44:25.902+0000 7f325fcc7200  4 rocksdb:                   Options.table_properties_collectors: CompactOnDeletionCollector;
2024-02-20T21:44:25.902+0000 7f325fcc7200  4 rocksdb: [column_family.cc:552] --------------- Options for column family [O-0]:
2024-02-20T21:44:25.902+0000 7f325fcc7200  4 rocksdb:                   Options.table_properties_collectors: CompactOnDeletionCollector;
2024-02-20T21:44:25.902+0000 7f325fcc7200  4 rocksdb: [column_family.cc:552] --------------- Options for column family [O-1]:
2024-02-20T21:44:25.902+0000 7f325fcc7200  4 rocksdb:                   Options.table_properties_collectors: CompactOnDeletionCollector;
2024-02-20T21:44:25.902+0000 7f325fcc7200  4 rocksdb: [column_family.cc:552] --------------- Options for column family [O-2]:
2024-02-20T21:44:25.902+0000 7f325fcc7200  4 rocksdb:                   Options.table_properties_collectors: CompactOnDeletionCollector;
```

**Review by markhpc — APPROVED** [review]
LGTM!

**Review by ifed01 — APPROVED** [review]
Good catch!

**Comment by amathuria** [comment]
Rados approved: https://tracker.ceph.com/projects/rados/wiki/MAIN#httpstrackercephcomissues64995

**Pull request merged**
