### PR TITLE
rgw/notifications: support v4 auth for topics and notifications

### PR DESCRIPTION
**Pull request by yuvalif**
Fixes: https://tracker.ceph.com/issues/50039

Signed-off-by: Yuval Lifshitz <ylifshit@redhat.com>

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Review by mattbenjamin — APPROVED** [review]
is this all that was needed to address this issue?  this certainly looks fine

**Comment by yuvalif** [comment]
> is this all that was needed to address this issue? this certainly looks fine

i specified v4 auth for s3 and sns (according to: https://docs.aws.amazon.com/AmazonS3/latest/userguide/UsingAWSSDK.html#specify-signature-version):

```
aws configure set default.s3.signature_version s3v4
aws configure set default.sns.signature_version s3v4
aws configure set default.s3api.signature_version s3v4
```

and verified that the topic and notification commands work.

**Review by pritha-srivastava — APPROVED** [review]

**Comment by cbodley** [comment]
@mattbenjamin this looks similar to the downstream issue of v4 auth against admin APIs. we don't define `RGW_OP_` values for the admin APIs, but can add them for v4 support

**Comment by mattbenjamin** [comment]
> 
> 
> @mattbenjamin this looks similar to the downstream issue of v4 auth against admin APIs. we don't define `RGW_OP_` values for the admin APIs, but can add them for v4 support

makes sense, thanks @cbodley

**Comment by yuvalif** [comment]
teuthology:
http://pulpito.front.sepia.ceph.com/yuvalif-2021-07-01_13:46:17-rgw:notifications-wip-yuval-testing3-distro-basic-smithi/

**Pull request merged**
