### PR TITLE
mon: add cache tier IO rate in the 'osd pool stats' command

### PR DESCRIPTION
**Pull request by wonzhq**
This additionally shows the flush/evict bandwidth and promote IOPS in the output of the 'osd pool stats' command.

### CODE REVIEW

**Comment by liewegas** [comment]
a few cosmetic quibbles, otherwise this looks great!

i wonder if we should roll up all cache tier activity and include it in ceph -s alongside recovery and client io?  that seems worthwhile to me as it is another major source of io in the cluster...

**Comment by wonzhq** [comment]
Yep, let's add it in the 'ceph -s' as well.

**Comment by wonzhq** [comment]
@liewegas updated, pls take another look.

**Comment by fiskn** [comment]
Would it be possible to add another flag in the ceph -s view to indicate if any cache tier PG's are doing low/high speed flushing. This would be very useful to see as it would allow you to make sure that you are not constantly hitting the high threshold and tune if needed.

eg:-
3 PG's are flushing at the high threshold

**Comment by liewegas** [comment]
I think there are two main options for showing flushing mode (low/high):

 1. we could add a PG_STATE_* flag so that the pgs show up in the pg state counts
 2. we could add pg stat fields

Is there anything information that'd be useful here beyond just the mode?

**Comment by fiskn** [comment]
Not that I can think of at the moment, it should hopefully enable a user to make an informed decision if the thresholds need adjusting or the cache tier needs to be expanded to match their workloads.

**Comment by fiskn** [comment]
Thinking about it some more, also having it flag when a cache PG reaches 100% and starts forced flushing would also be very useful.

**Pull request merged**
