### PR TITLE
luminous: rgw: fail to recover index from crash luminous backport

### PR DESCRIPTION
**Pull request by ivancich**
Fixes: http://tracker.ceph.com/issues/24628

### CODE REVIEW

**Comment by ivancich** [comment]
@smithfarm As with https://github.com/ceph/ceph/pull/23118 we'll wait for the master merge, update commit hashes if necessary, and remove DNM.

**Comment by smithfarm** [comment]
@ivancich If the master commit hash changes, would need to re-do the cherry-pick. In geneal it's easier to wait for the master PR to merge, but I do appreciate the backporting effort.

**Comment by ivancich** [comment]
@smithfarm So now that these commits merged with master, I reapplied the cherry-picks all over again. So I'm removing DNM, so this can move forward. Thanks for the help.

**Comment by yuriw** [comment]
[wip-yuri2-testing-2018-08-03-1639-luminous](https://trello.com/c/dW8go611/365-wip-yuri2-testing-2018-08-03-1639-luminous)

**Comment by mattbenjamin** [comment]
@yuriw this one is good for merge

**Pull request merged**
