### PR TITLE
squid: librbd/crypto: fix issue when live-migrating from encrypted export

### PR DESCRIPTION
**Pull request by idryomov**
backport tracker: https://tracker.ceph.com/issues/67441

---

backport of https://github.com/ceph/ceph/pull/58882 and https://github.com/ceph/ceph/pull/44366
parent tracker: https://tracker.ceph.com/issues/53674

### CODE REVIEW

**Comment by idryomov** [comment]
jenkins test make check

**Comment by idryomov** [comment]
jenkins test make check

**Comment by idryomov** [comment]
jenkins test make check

**Comment by idryomov** [comment]
jenkins test make check

**Review by ajarr — APPROVED** [review]

**Pull request merged**
