### PR TITLE
LifeCycle feature

### PR DESCRIPTION
**Pull request by chenji-kael**
As same as amazon S3 interface,"PUT Bucket lifecycle" and
"DELETE Bucket lifecycle" have been implemented,
"GET Bucket lifecycle" not realized yet as S3cmd has not
realize it also.
The feature`s main point is to remove expire file per day.
As ceph does not have a tier concept, so files transfer
from hot layer to cold layer is also not supported.

lifecycle config file format:
<LifecycleConfiguration>
    <Rule>
        <ID>sample-rule</ID>
        <Prefix></Prefix>
        <Status>enable</Status>
        <Expiration>
           <Days>1</Days>
        </Expiration>
    </Rule>
</LifecycleConfiguration>

Signed-off-by: Ji Chen <insomnia@139.com>

### CODE REVIEW

**Comment by yehudasa** [comment]
@chenji-kael this is very interesting, looks like a good start. I do see it needs some cleanups, and we'll need to take a closer look at it to make sure it conforms to what we had in mind when thinking about this feature. Assigining it to @dang to take a closer look.

**Comment by chenji-kael** [comment]
@yehudasa ping

**Comment by yehudasa** [comment]
@chenji-kael there are a few problems that I see. It still does it using the bucket name, not the bucket instance which is problematic. I also think that modifying the bucket metadata is problematic because it's racy (can race with another change to the bucket metadata). I still think we need to keep the list of bucket instances that need to be scanned in a separate sharded omap. Each gateway will try to grab a lease on a shard, then process it. This way multiple gateways can coordinate the work.

**Comment by chenji-kael** [comment]
@yehudasa  OK,I will get it fix soon

**Comment by chenji-kael** [comment]
@yehudasa ping
Hi, I have changed a lot, Now save lc bucket list in shard object. Please check it, thanks

**Comment by chenji-kael** [comment]
@yehudasa ping

**Comment by yehudasa** [comment]
@chenji-kael haven't forgotten you. Will try to get it reviewed soon. Thanks!

**Comment by dang** [comment]
@chenji-kael 
Can you rebase on master?  You can probably resolve conflicts faster than I can.

**Comment by chenji-kael** [comment]
@dang hi,rebase has been done

**Comment by dachary** [comment]
@chenji-kael please ignore the bot failure, it is a false negative (see http://tracker.ceph.com/issues/13997 for more information). You can re-schedule a job by rebasing your branch and repushing.

**Comment by dang** [comment]
@chenji-kael The call to get_bucket_info() needs to be updated for tenants from commit f7ca00a6e97b82787becbc15d7e7143e96b3e96d this is causing me build failures.

I suspect this will need a new argument, but I'm not sure.

Also, can you add your new files to src/CMakeList.txt?

**Comment by chenji-kael** [comment]
@dang sorry for have not noticed tenant has been merged, now it works fine, please check it, thanks

**Comment by yehudasa** [comment]
@chenji-kael @dang I reverted the merge off github for now. There still are some issues that I think will need to be fixed. Note that I pushed some fixes to wip-rgw-lifecycle, but we'll need to do some more work before we can merge it.

**Comment by chenji-kael** [comment]
@yehudasa @dang Glad to hear that, I will do more test, Thanks guys!

**Pull request merged**
