### PR TITLE
ceph-disk: s/ceph_osd_mkfs/command_check_call/

### PR DESCRIPTION
**Pull request by shangzhong**
Fixes: http://tracker.ceph.com/issues/20685
Signed-off-by: Zhu Shangzhong <zhu.shangzhong@zte.com.cn>

### CODE REVIEW

**Comment by shangzhong** [comment]
jenkins test this please

**Comment by shangzhong** [comment]
Jenkins retest this please

**Comment by shangzhong** [comment]
Jenkins retest this please

**Comment by scienceluo** [comment]
@shangzhong Maybe you should update your Signed-off-by info to:

Signed-off-by: Zhu Shangzhong <zhu.shangzhong@zte.com.cn>

**Comment by shangzhong** [comment]
@scienceluo Thanks. It's OK now.

**Comment by shangzhong** [comment]
Jenkins retest this please

**Comment by tchaikov** [comment]
http://pulpito.ceph.com/kchai-2017-07-24_17:50:25-ceph-disk-wip-kefu-testing-distro-basic-vps/

**Pull request merged**
