### PR TITLE
mgr/dashboard：delete image fail on dashboard while it has some protected snapshots

### PR DESCRIPTION
**Pull request by tengjie5**
Fixes:  https://tracker.ceph.com/issues/62047
Signed-off-by: teng jie tengjie5@asiainfo.com

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by tengjie5** [comment]
@aaSharma14  @nizamial09  hi，would you please review the PR ?thanks.

**Comment by aaSharma14** [comment]
> @aaSharma14 @nizamial09 hi，would you please review the PR ?thanks.

Hi @tengjie5 , Thanks for the contribution, will check it out

**Comment by Pegonzal** [comment]
Hi @tengjie5!

I was checking this PR, and I was trying to reproduce the issue as you stated in tracker but I wasn't able to do so.
Could you attach some logs of the error? It'd be great to see what's going on, 

regarding the fix, looks good to me, but may be a 1 second sleep might be too much of a wait?

**Comment by tengjie5** [comment]
@Pegonzal  hi, Maybe your hosts have better performance,I suggest creating more snapshots to reproduce the issue. 
The dashboard only reported an error log： “Failed to delete RBD 'pool/image' RBD 'pool/image' is busy.”
About the duration of sleep，completing the operation often takes more than one second.

**Pull request closed without merging**
