### PR TITLE
jewel: rgw: curl* reuse and for debian, use openssl not gnutls. (jewel)

### PR DESCRIPTION
**Pull request by mdw-at-linuxbox**
3 commits here; two are important, one is a minor build fix
0853bb0203  rgw: reuse CURL* for keystone.
e550dfbba9 build/link against curl w/ openssl not nss or gnutls. (debian)
b114d317ce Fix tag handling for ceph_versioning.

0853bb0203  rgw: reuse CURL* for keystone.
   actual code change - queue to store recently used CURL*, thread to delete idle CURL*.
e550dfbba9 build/link against curl w/ openssl not nss or gnutls. (debian)
  this is just a configuration change; it's debian/ubuntu specific.  centos doesn't have such a package (yet); I will do something for that too but almost certainly separately.
In order to build this I also wanted this fix,...
b114d317ce Fix tag handling for ceph_versioning.

This is all for jewel; I'll post something shortly for master as well.

### CODE REVIEW

**Comment by ktdreyer** [comment]
`git tag` has a "match" option. Wherever that runs, it should be matching against `v*` tags only

**Comment by smithfarm** [comment]
Maybe a little background is in order. A former dev lead (Sam Just) gave us the following principles for reviewing backport PRs:

Each backport PR (or backport tracker issue) should state:

1. what bug is fixed
2. why this fix is the minimal way to do it
3. why does this need to be fixed in <release>

For more info, see: http://tracker.ceph.com/projects/ceph-releases/wiki/HOWTO_review_backport_PRs

N.B. there is a difference between releases that are early in their lifecycle, like luminous, and those that are mature, like jewel. As the release gets more advanced in age, we tend to get more and more serious about enforcing this.

**Comment by mattbenjamin** [comment]
@smithfarm the changes are definitely defensible;  I'm happy to take them only to our downstream if that's upstream's preference--discussion can happen here and in our standup meetings.

**Comment by smithfarm** [comment]
@mattbenjamin To be clear, I'm only objecting to this change: b114d317ce826d6361a8b0900bb343fb2f0af4fc

(We made it to 10.2.10 without touching this, and it's not related to rgw . . . why take the risk?)

**Comment by smithfarm** [comment]
Don't get me wrong, here, please - I was bitten by the same issue in our downstream. I would have welcomed the fix early in the jewel release cycle (though not as part of an rgw PR).

**Comment by smithfarm** [comment]
So, https://github.com/ceph/ceph/pull/20635 has been merged. @mdw-at-linuxbox Could you redo this PR using `git cherry-pick -x` from the master PR?

**Comment by smithfarm** [comment]
Also note that @theanalyst included this in his luminous backport PR here: https://github.com/ceph/ceph/pull/20722

Maybe the jewel backport could be done in a similar fashion (i.e. together with other related PRs, instead of separately). It's always easier that way, because it prevents merge conflicts when preparing the integration branch.

**Comment by theanalyst** [comment]
I included these changes in https://github.com/ceph/ceph/pull/20749 + my openssl locking fixes in master + the fix in radosgw-admin init

**Comment by smithfarm** [comment]
jenkins re-test this please

**Comment by smithfarm** [comment]
timeout in unittest_throttle

jenkins re-test this please

**Comment by smithfarm** [comment]
Closing in favor of #20749

**Pull request closed without merging**
