### PR TITLE
librados: fix message dropping and race condition in RadosClient::monitor_log()

### PR DESCRIPTION
**Pull request by rzarzynski**
I would like to propose two changes:

1) Fix for the problem described in the issue [#5639](http://tracker.ceph.com/issues/5639).
2) Introducing synchronization between _librados::RadosClient::monitor_log()_ and _librados::RadosClient::handle_log()_ because there could be race condition while updating the pair of pointer to user callback and its argument. I'm afraid the operation in not atomic.

### CODE REVIEW

**Comment by liewegas** [comment]
Reviewed-by:

Both of these look correct.  Thanks!  I seem to remember thinking this was complex to fix when that bug was opened.. I think the client/mon session state has improved since then.

**Comment by liewegas** [comment]
One other fix that may be appropriate here: although there is only one user for this interface and it doesn't care, in general it is a bad idea to do the callback while holding an intenral lock, as it means you can't call back into the interface.  The callbacks could be put on the Finisher thread by defining a C_DoLogCb context that makes the function call(s) in another thread context.  Or it may be simpler just to add a comment in librados.h noting that the log callback does not allow blocking or calling back into librados.

**Comment by rzarzynski** [comment]
Thanks for the review. I was surprised too. :-)

There is another thing that could be improved. In _RadosClient.cc_, around line 820th, small block of code utilizes tabs instead of spaces for indentation. It would be nice to have the indentation style consistent across a file, I think. Is it acceptable (in this particular case as well as in the general) to rectify such things in a separate commit with appropriate description (like “code reformatting only”) and under restriction that the reformatting must be performed on fragments really close to the real changes (to minimize chance of affecting other PRs awaiting merge)?

**Comment by liewegas** [comment]
Yep, go for it!  There should be a mdoeline at the top of every file that 
makes emacs and vi not do this but some old source files are wonky.  Just 
keep it in a separate commit.

s

**Comment by liewegas** [comment]
manual merge

**Pull request closed without merging**
