### PR TITLE
ceph-volume fix filestore OSD creation after mon-config changes

### PR DESCRIPTION
**Pull request by alfredodeza**
Fixes http://tracker.ceph.com/issues/23260

### CODE REVIEW

**Comment by alfredodeza** [comment]
jenkins test ceph-volume lvm all

**Comment by alfredodeza** [comment]
The issues here where only for filestore and lvm, so just those tests are important. `ceph-volume simple` is unaffected since those OSDs are setup by ceph-disk

**Comment by alfredodeza** [comment]
jenkins test ceph-volume lvm all

**Comment by alfredodeza** [comment]
We couldn't make this pass at all until we pulled in the latest master and rebased. This is now consistently passing all of our functional tests and it is ready to be reviewed/merged

**Comment by alfredodeza** [comment]
@liewegas this will not need to get backported because the mon-config changes aren't going into Luminous right?

**Comment by liewegas** [comment]
@alfredodeza correct!

**Pull request merged**
