### PR TITLE
radosgw-admin: supplement help documents with 'bilog autotrim'

### PR DESCRIPTION
**Pull request by Huber-ming**
Signed-off-by: Huber-ming <zhangsm01@inspur.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by Huber-ming** [comment]
jenkins test make check

**Comment by Huber-ming** [comment]
jenkins test make check

**Review by dang — APPROVED** [review]

**Comment by dang** [comment]
jenkins test make check

**Comment by Huber-ming** [comment]
> jenkins test make check

what's wrong? why rbd test error?

**Comment by Huber-ming** [comment]
jenkins test make check

**Comment by Huber-ming** [comment]
@dang merge?

**Pull request merged**
