### PR TITLE
mgr/deepsea: use ceph_volume output in get_inventory()

### PR DESCRIPTION
**Pull request by tserong**
DeepSea is being updated to use ceph_volume internally (see https://github.com/SUSE/DeepSea/pull/1517 and https://github.com/jschmid1/DeepSea/pull/6). Once this is done, the mgr_orch.get_inventory runner will just be returning the raw ceph_volume output, so this PR updates the DeepSea mgr module to match. There's also a couple of small cleanup commits. We probably don't want to merge this until the DS PR is in though.

### CODE REVIEW

**Comment by sebastian-philipp** [comment]
@tserong we need to merge it to nautilus, if we need it for nautilus

**Comment by tserong** [comment]
@sebastian-philipp https://github.com/SUSE/DeepSea/pull/1517 was merged, so this is good to go (I re-tested this just now against the latest deepsea master)

**Comment by tserong** [comment]
Rebased on latest master

**Comment by sebastian-philipp** [comment]
Fixes http://tracker.ceph.com/issues/39082

**Pull request merged**
