### PR TITLE
WIP: osd/osd_types: get rid of awkward [de]encoding of new pg_missing_item

### PR DESCRIPTION
**Pull request by xiexingguo**
There is already a flags field which we can make use of.
Also if 'decode' failed to read the new clean_regions field off
the disk, then we should still be able to fall back to the traditional
way. 'mark_fully_dirty' ensures that happen.

Signed-off-by: xie xingguo <xie.xingguo@zte.com.cn>

- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by xiexingguo** [comment]
@jdurgin @neha-ojha

**Comment by xiexingguo** [comment]
I know the make check failure is true, but I'd like to get some feedback first before moving on.
Also there are some bug-fixes that depends on this change, that's why this pr is marked as WIP.

**Comment by jdurgin** [comment]
I like the idea, haven't looked closely at correctness yet

**Comment by xiexingguo** [comment]
There are some scrub errors with this change.
Closing for now.

**Comment by xiexingguo** [comment]
@jdurgin it's probably because of https://github.com/ceph/ceph/pull/29717. I'll retest this with that fix.

**Pull request closed without merging**
