### PR TITLE
luminous: MDSMonitor: missing osdmon writeable check

### PR DESCRIPTION
**Pull request by pdvian**
http://tracker.ceph.com/issues/37989

### CODE REVIEW

**Comment by smithfarm** [comment]
@callithea @LenzGr Any idea why we're running "ceph dashboard tests" on luminous?

**Comment by smithfarm** [comment]
jenkins retest this please

**Comment by smithfarm** [comment]
@callithea Yeah, it's odd. AFAICT there is no dashboard in luminous so luminous should probably be excluded even if a "dashboard" label gets added to a luminous PR by accident?

**Comment by callithea** [comment]
@smithfarm yeah, indeed.
There are some pending dashboard backport PRs - so in that case it might makes sense to run the dashboard tests there.
I'll keep an eye on the Jenkins job and will try to find a solution for the trigger behavior of the job - sorry for the inconvenience @smithfarm @batrick!

**Comment by yuriw** [comment]
[wip-yuri4-testing-2019-02-22-1534-luminous](https://trello.com/c/SqBDMx2n/546-wip-yuri4-testing-2019-02-22-1534-luminous)

**Comment by yuriw** [comment]
test this pls

**Pull request merged**
