### PR TITLE
octopus: tools/rbd: expand where option rbd_default_map_options can be set

### PR DESCRIPTION
**Pull request by ideepika**
backport tracker: https://tracker.ceph.com/issues/54323

---

backport of https://github.com/ceph/ceph/pull/44904
parent tracker: https://tracker.ceph.com/issues/52850

this backport was staged using ceph-backport.sh version 16.0.0.6848
find the latest version at https://github.com/ceph/ceph/blob/master/src/script/ceph-backport.sh

### CODE REVIEW

**Review by idryomov — CHANGES_REQUESTED** [review]
This is in conflict with https://github.com/ceph/ceph/pull/45001.  Let's wait for it to merge and then rebase this PR.

**Comment by ljflores** [comment]
http://pulpito.front.sepia.ceph.com/?branch=wip-yuri5-testing-2022-02-28-0839-octopus

All green on the rados suite, except for one dead job that was the result of an infrastructure issue.

**Comment by ljflores** [comment]
jenkins test make check

**Comment by ljflores** [comment]
@ideepika @idryomov I added the "DNM" tag for extra security; remove when ready to merge.

**Review by chrisphoffman — CHANGES_REQUESTED** [review]
The conflicting PR has been merged, @ideepika please merge and rebase at your convenience.

**Comment by ideepika** [comment]
updated.

**Review by idryomov — CHANGES_REQUESTED** [review]
This is wrong still.  Please redo the cherry picks from scratch instead of attempting to rebase.

**Comment by ljflores** [comment]
jenkins test make check

**Comment by ljflores** [comment]
@chrisphoffman you might have to re-approve this for it to merge, if it looks okay to you.

**Pull request merged**
