### PR TITLE
osd: avoid dead lock when shutdown() in handle_osd_map()

### PR DESCRIPTION
**Pull request by xiexingguo**
OSD deadlocked during handle_osd_map and need to shutdown.
Fixes: #13004
Signed-off-by: xie.xingguo@zte.com.cn

### CODE REVIEW

**Comment by tchaikov** [comment]
@xiexingguo you might need to revise the title of your commit message

> Fix #13004 : OSD deadlock

something like this would be more specific:

> osd: avoid dead lock when shutdown() in handle_osd_map()

**Comment by xiexingguo** [comment]
@tchaikov 
Dear tchaikov :+1: 
 I have rename the variable and rewrote the comment as your suggusted. Could you check it again please?

**Comment by tchaikov** [comment]
@xiexingguo  could you squash your commits into a single one? and update the title of your commit message. please note that the commit message of d89d923 is not changed yet. what you changed is the pull request's title.

and i'd suggest to use `BOOST_SCOPE_EXIT_END` to consolidate the cleanup. we can put it right after where we mess up with the lock. so the readability is better, imo. what do you think?

**Comment by xiexingguo** [comment]
@tchaikov  I am still trying hart to get familiar with GitShell and do some testing with BOOST_SCOPE_EXIT, I'll come back soon, thank you for your patience

**Comment by xiexingguo** [comment]
Hi, @tchaikov 

I have tried to do cleanup with BOOST_SCOPE_EXIT, and the final solution is something like this::
int OSD::shutdown()
{
  if (!service.prepare_to_stop())
    return 0; // already shutting down

  bool is_osd_locked = osd_lock.is_locked_by_me();
  Mutex *osd_lockp = &osd_lock; 
  BOOST_SCOPE_EXIT((is_osd_locked) (osd_lockp)) {
    if (!is_osd_locked) {
        osd_lockp->Unlock();
    } else {
        osd_lockp->Lock();
    }
  } BOOST_SCOPE_EXIT_END    

  if (!is_osd_locked)
    osd_lock.Lock();
  if (is_stopping()) {
    return 0;
  }
  derr << "shutdown" << dendl;

**Comment by tchaikov** [comment]
@xiexingguo i reviewed the original code, seems we do not always do the cleanup when exiting the method, see https://github.com/ceph/ceph/blob/master/src/osd/OSD.cc#L2430 . so we'd better not `osd_lockp->Unlock()` when returning from this method. although we can still have
```c++
BOOST_SCOPE_EXIT((is_osd_locked) (&osd_lock)) {
  if (!is_osd_locked) {
    osd_lockp->Lock();
  }
}
```
at where we check for the ownership of the lock at the beginning of this method, i think it could be overkill, because, if we don't expect an exception being thrown in `shutdown()`, we have only a single exit of this method in this case. and i think, the beauty of `BOOST_SCOPE_EXIT` is its ability to do the cleanup nicely when one is likely to leave a scope in **several** different paths.

so maybe we should keep your original solution as it is. sorry for my immature suggestions =(

fwiw, you can capture a variable using reference `git grep BOOST_SCOPE_EXIT` for some examples in the ceph git. to be specific, 
```c++
BOOST_SCOPE_EXIT((is_osd_locked) (&osd_lock)) {
```

**Comment by tchaikov** [comment]
btw, you are reverting your changes? you did it on purpose?

**Comment by xiexingguo** [comment]
Dear @tchaikov

I did all those reverts on purpose and I will try to get all these commits well with a final commit.
But I have to do this when I come back to home this evening.  Thank you for your patience and all your 
wonderful suggestions.

Have a nice day.

**Comment by xiexingguo** [comment]
Dear @tchaikov 
I have recommitted my code just now.
But there are seems to be more and more commits and I am fully frustrated by the gitshell.
I am still not sure if it is right :((

**Comment by tchaikov** [comment]
@xiexingguo i use `git` but not gitshell. presumably, you should have the vanilla git installed right? if yes, you can squash them into a single one, using `git rebase -i 689d923~1`. and mark the squashed commits using `f` as prompted.

**Comment by xiexingguo** [comment]
@tchaikov 
It is done. Thank you for your kindness.

**Comment by tchaikov** [comment]
@xiexingguo #5870 might be a better fix, if `handle_osd_map()` is the only caller which tries to `shutdown()` when holding the lock. what do you think?

**Comment by tchaikov** [comment]
@xiexingguo i am closing your pull request, as #5870 is a simpler one, probably more restrictive, but good enough. let me know if you think otherwise.

**Comment by xiexingguo** [comment]
@tchaikov 
It is up to you ...

**Pull request closed without merging**
