### PR TITLE
Coverity and SCA fixes

### PR DESCRIPTION
**Pull request by dalgaaf**
Coverity:
- CID 1242020
- CID 1242018
- CID 1260395
- CID 1256099
- CID 1256100
- CID 1238902
- CID 1128404/1128405/1219644-1219646
- CID 1219471
- CID 743419

SCA fixes like:
- unsigned can't be less than zero
- remove unused variable
- reduce scope of variables
- init variables in constructor
- fix error about self init
- prefer ++operator for non-primitive iterators
- prefer !empty() over size() for emptiness check

Misc:
- fix -Wsign-compare
- fix -Wmaybe-uninitialized
- small fixes for configure.ac to solve unknown commands warnings.

### CODE REVIEW

**Comment by liewegas** [comment]
The rest look good!

**Comment by liewegas** [comment]
I think this needs a rebase either way as github is complaining it won't merge.  Thanks!

**Comment by dalgaaf** [comment]
Incorporated comments and rebased on latest master

**Comment by dachary** [comment]
@dalgaaf I can't reproduce the crash locally either but I'm convinced there is a problem. The last time this test program failed it was difficult to figure out also and IIRC it was dependent on the compilation options or something. I tried with valgrind but got nothing different from what master shows.

**Comment by dachary** [comment]
trying to reproduce the problem at https://github.com/ceph/ceph/pull/3314

**Comment by dachary** [comment]
@dalgaaf false negative it seems, can't reproduce the crash.

**Comment by liewegas** [comment]
Reviewed-by:

**Pull request merged**
