### PR TITLE
nautilus: mgr/dashboard: Admin resource not honored

### PR DESCRIPTION
**Pull request by LenzGr**
http://tracker.ceph.com/issues/39467

### CODE REVIEW

**Comment by smithfarm** [comment]
jenkins test make check

**Comment by yuriw** [comment]
[wip-yuri2-testing-2019-05-16-1555-nautilus](https://trello.com/c/VvCEDimT/616-wip-yuri2-testing-2019-05-16-1555-nautilus)

**Comment by smithfarm** [comment]
jenkins re-test this please

**Comment by smithfarm** [comment]
"make check" failure is tracked by http://tracker.ceph.com/issues/39986

**Comment by smithfarm** [comment]
jenkins re-test this please

**Comment by smithfarm** [comment]
jenkins re-test this please

**Pull request merged**
