### PR TITLE
osd: support filestore fstrim in ssd cluster

### PR DESCRIPTION
**Pull request by XinzeChi**
Signed-off-by: Xinze Chi <xmdxcxz@gmail.com>

### CODE REVIEW

**Comment by majianpeng** [comment]
Does it effect performance, especially there are much write ops? 
For xfs, when delete a file, the fs don't do trim? or maybe the metadata don't do trim?
like repair/scrub, we can call by cli or can set the exec time.

**Comment by XinzeChi** [comment]
@majianpeng, what about do fstrim like https://github.com/ceph/ceph/pull/3318?

**Comment by XinzeChi** [comment]
Add comand "ceph osd fstrim osd.xxx"

**Comment by XinzeChi** [comment]
Add comand "ceph osd fstrim osd.xxx"

**Comment by XinzeChi** [comment]
Add command "ceph osd fstrim osd.xxx"

**Comment by XinzeChi** [comment]
@liewegas , please review.  Thanks.

**Comment by yuyuyu101** [comment]
I want to know what's the difference between mount with "-o discard" and manual fstrim? It's absolutely overlap or not?

**Comment by XinzeChi** [comment]
@yuyuyu101 , see http://xfs.org/index.php/FITRIM/discard

1. Realtime discard
This mode issues discard requests automatically as files are removed from the filesystem. No other command or process is required.
There can be a severe performance penalty for enabling realtime discard. (4)
Realtime discard is selected by adding the filesystem option discard while mounting.
This can be done by the following examples:
placing discard in your /etc/fstab for the filesystem: /dev/sda1 /mountpoint xfs defaults,discard 0 1
mount options: mount -o discard /dev/sda1 /mountpoint
2. Batch Mode
This mode requires user intervention. This intervention is in the form of the command fstrim. It has been included in util-linux-ng since about Nov 26, 2010.
Usage example: fstrim /mountpoint

**Comment by XinzeChi** [comment]
@yuyuyu101 , see https://wiki.archlinux.org/index.php/Solid_State_Drives#Apply_TRIM_via_cron.

**Comment by xiaoxichen** [comment]
The most case that use SSD and had tons of delete op should be the cache tiering scenarios.

First, why don't just use crontab?

And also , I am kind of curious about the real performance tradeoff here( in some out-of-date ssd),
1. RT Trime -> SSD can know which block is invalid realtime-> better wear-leveling and better GC efficiency -> MAYBE better SSD performance,  but will hurt delete performance.

2. Batch trim -> .SSD can mark block invalid only when it has been rewritten-> less efficient GC -> MAYBE less SSD performance, but better delete performance.

Another argue here is that if you use moderate enterprise level SSD(s3700/s3500/p3700/p3500), or some good commercial level SSD(Intel 530/730),  thanks to the large over-povisioning, trim or not make little difference in performance, never trim it should also be fine.

**Comment by liewegas** [comment]
this seems like a bad idea to me.  fstrim is generally not cheap and certaily not something that shoudl happen every ~30s

**Comment by liewegas** [comment]
happy to be proven wrong, but i think we shoudl demonstrate an improvement (on a full/aged fs) before doing somethign like this

**Pull request closed without merging**
