### PR TITLE
rbd-mirror: improved mirror image status readability

### PR DESCRIPTION
**Pull request by caisan**
Impoved journal-based mirror image status readability, change
from bytes per second to B, KB, or MB per second.

Signed-off-by: Alex <alex@easystack.cn>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by caisan** [comment]
@dillaman please review it. thx.

**Comment by dillaman** [comment]
It's JSON output so I really don't want to have it in human-readable suffixes. Instead, the place to improve readability would be the place where it's output for human consumption (i.e. `rbd`).

**Comment by caisan** [comment]
@dillaman hi,  you mean this is not design for human consumption ? 

> It's JSON output so I really don't want to have it in human-readable suffixes. Instead, the place to improve readability would be the place where it's output for human consumption (i.e. `rbd`).

In `rbd mirror status ` command ? what difference does it make ?

**Comment by dillaman** [comment]
If you want to have pretty output, the proper place to handle that would be where it's actually output. That means that the "rbd mirror pool/image status" commands should attempt to decode the JSON and nicely format it.

**Pull request closed without merging**
