### PR TITLE
luminous: backport beast frontend and boost 1.66 update

### PR DESCRIPTION
**Pull request by cbodley**
http://tracker.ceph.com/issues/22621
http://tracker.ceph.com/issues/22622
http://tracker.ceph.com/issues/22623

building radosgw with boost 1.66 required a lot of extra backports related to the beast frontend, see tracker for details

Fixes: http://tracker.ceph.com/issues/22621

### CODE REVIEW

**Comment by smithfarm** [comment]
test this please (logs gone)

**Comment by cbodley** [comment]
the jenkins failure is a real one affecting gcc5, tracked in this boost bug: https://svn.boost.org/trac10/ticket/13368
```
In file included from build/boost/include/boost/asio/impl/write.hpp:25:0,
                 from build/boost/include/boost/asio/write.hpp:927,
                 from build/boost/include/boost/asio/buffered_write_stream.hpp:29,
                 from build/boost/include/boost/asio/buffered_stream.hpp:22,
                 from build/boost/include/boost/asio.hpp:41,
                 from src/common/Graylog.h:7,
                 from src/common/LogClient.cc:20:
build/boost/include/boost/asio/detail/consuming_buffers.hpp: In member function ‘boost::asio::detail::consuming_buffers<Buffer, Buffers, Buffer_Iterator>::prepared_buffers_type boost::asio::detail::consuming_buffers<Buffer, Buffers, Buffer_Iterator>::prepare(std::size_t)’:
build/boost/include/boost/asio/detail/consuming_buffers.hpp:105:50: error: parse error in template argument list
     while (next != end && max_size > 0 && result.count < result.max_buffers)
                                                  ^
```

i've added a workaround commit that uses more specific #includes to avoid pulling in the broken header (details in commit message)

**Comment by yuriw** [comment]
[rgw => wip-yuri4-testing-2018-01-25-1744-luminous](https://trello.com/c/qvWoKh2O/243-rgw-wip-yuri4-testing-2018-01-25-1744-luminous)

**Comment by yuriw** [comment]
ready for merge
@tchaikov @b-ranto @theanalyst pls approve

**Pull request merged**
