### PR TITLE
rbd-ggate: small fixes and improvements

### PR DESCRIPTION
**Pull request by trociny**

### CODE REVIEW

**Comment by wjwithagen** [comment]
Running it thru FreeBSD-jenkins

**Comment by trociny** [comment]
Updated: support is added for different output formats for `list` command. Though it might require additional tweaking after discussing the format for `rbd-nbd list-mapped` command in #19704.

**Comment by wjwithagen** [comment]
@trociny 
Let me know if you want another FreeBSD-jenkins run.

**Comment by wjwithagen** [comment]
@trociny 
It lloks like this patch is cont compatible with #19711?
But could be cause I did not include the last 2 commits.

**Comment by trociny** [comment]
@wjwithagen It will probably require resolving some conflicts if you want to test this together with  #19711. I will resolve this after one of this is merged to the master.

Right now I don't think there is a need for FreeBSD-jenkins run. I would like to discuss with @dillaman  the formatted output structure first, so it will probably be updated. I guess this will happen the next year though )

**Pull request merged**
