### PR TITLE
mgr/dashboard/api: increase API health timeout

### PR DESCRIPTION
**Pull request by epuertat**
Fixes: https://tracker.ceph.com/issues/46601
Signed-off-by: Ernesto Puerta <epuertat@redhat.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by callithea** [comment]
jenkins test dashboard backend

**Comment by callithea** [comment]
First run passed, but I'd like to re-trigger the job a few times to see if we will still see timeouts..

**Comment by epuertat** [comment]
@callithea this would only fix PRs with error `RuntimeError: Timed out after 20s`, which represent ~25% of all API failures.

**Comment by callithea** [comment]
> @callithea this would only fix PRs with error `RuntimeError: Timed out after 20s`, which represent ~25% of all API failures.

@epuertat okay, thanks for the clarification!

**Comment by callithea** [comment]
jenkins test dashboard backend

**Comment by bk201** [comment]
jenkins test dashboard

**Comment by callithea** [comment]
jenkins test dashboard

**Comment by callithea** [comment]
- [pkg build](https://shaman.ceph.com/builds/ceph/wip-laura-testing-36157/) [WIP]
- QA run [PENDING]

**Pull request merged**
