### PR TITLE
common/options: refactors to set the properties in a more structured way

### PR DESCRIPTION
**Pull request by tchaikov**

### CODE REVIEW

**Comment by tchaikov** [comment]
```
//home/jenkins-build/build/workspace/ceph-pull-requests/src/test/mon/mkfs.sh:72: kill_daemons:  find mkfs -name pidfile
find: ‘mkfs’: No such file or directory
/home/jenkins-build/build/workspace/ceph-pull-requests/src/test/mon/mkfs.sh:38: teardown:  rm -fr mkfs
/home/jenkins-build/build/workspace/ceph-pull-requests/src/test/mon/mkfs.sh:33: setup:  mkdir mkfs
/home/jenkins-build/build/workspace/ceph-pull-requests/src/test/mon/mkfs.sh:183: run:  idempotent
/home/jenkins-build/build/workspace/ceph-pull-requests/src/test/mon/mkfs.sh:169: idempotent:  mon_mkfs --auth-supported=none
//home/jenkins-build/build/workspace/ceph-pull-requests/src/test/mon/mkfs.sh:42: mon_mkfs:  uuidgen
/home/jenkins-build/build/workspace/ceph-pull-requests/src/test/mon/mkfs.sh:42: mon_mkfs:  local fsid=31fcb974-214b-41f0-84c1-6755d3208d09
/home/jenkins-build/build/workspace/ceph-pull-requests/src/test/mon/mkfs.sh:45: mon_mkfs:  ceph-mon --id a --fsid 31fcb974-214b-41f0-84c1-6755d3208d09 --erasure-code-dir=/home/jenkins-build/build/workspace/ceph-pull-requests/build/lib --mkfs --mon-data=mkfs/a --mon-initial-members=a --mon-host=127.0.0.1:7110 --auth-supported=none
/home/jenkins-build/build/workspace/ceph-pull-requests/src/test/mon/mkfs.sh:170: idempotent:  mon_mkfs --auth-supported=none
/home/jenkins-build/build/workspace/ceph-pull-requests/src/test/mon/mkfs.sh:170: idempotent:  tee mkfs/makedir.log
//home/jenkins-build/build/workspace/ceph-pull-requests/src/test/mon/mkfs.sh:42: mon_mkfs:  uuidgen
/home/jenkins-build/build/workspace/ceph-pull-requests/src/test/mon/mkfs.sh:42: mon_mkfs:  local fsid=85d2ad38-0789-4c14-a3b2-bf04ebe982e9
/home/jenkins-build/build/workspace/ceph-pull-requests/src/test/mon/mkfs.sh:45: mon_mkfs:  ceph-mon --id a --fsid 85d2ad38-0789-4c14-a3b2-bf04ebe982e9 --erasure-code-dir=/home/jenkins-build/build/workspace/ceph-pull-requests/build/lib --mkfs --mon-data=mkfs/a --mon-initial-members=a --mon-host=127.0.0.1:7110 --auth-supported=none
/home/jenkins-build/build/workspace/ceph-pull-requests/src/test/mon/mkfs.sh:171: idempotent:  grep ''\''mkfs/a'\'' already exists' mkfs/makedir.log
/home/jenkins-build/build/workspace/ceph-pull-requests/src/test/mon/mkfs.sh:171: idempotent:  return 1
/home/jenkins-build/build/workspace/ceph-pull-requests/src/test/mon/mkfs.sh:183: run:  return 1
```

test this please

**Comment by tchaikov** [comment]
retest this please

**Comment by jcsp** [comment]
Hmm, generally I wouldn't care about such a small memory overhead, but I guess since we embed one of these objects in our clients, it is worthwhile.

**Comment by tchaikov** [comment]
- http://pulpito.ceph.com/kchai-2017-07-27_04:52:14-rados-wip-kefu-testing-distro-basic-mira/
- http://pulpito.ceph.com/kchai-2017-07-28_02:24:35-rados-wip-kefu-testing-distro-basic-mira/

**Pull request merged**
