### PR TITLE
quincy: qa/standalone/osd/divergent-prior.sh: Divergent test 3 with pg_autoscale_mode on pick divergent osd

### PR DESCRIPTION
**Pull request by NitzanMordhai**
backport tracker: https://tracker.ceph.com/issues/62252

---

backport of https://github.com/ceph/ceph/pull/51909
parent tracker: https://tracker.ceph.com/issues/56034

this backport was staged using ceph-backport.sh version 16.0.0.6848
find the latest version at https://github.com/ceph/ceph/blob/main/src/script/ceph-backport.sh

### CODE REVIEW

**Comment by NitzanMordhai** [comment]
jenkins retest this please

**Comment by NitzanMordhai** [comment]
jenkins retest this please

**Review by kamoltat — APPROVED** [review]
LGTM

**Comment by NitzanMordhai** [comment]
Rados suite review: https://tracker.ceph.com/projects/rados/wiki/QUINCY#httpstrellocomcEoKQClMJ1839-wip-yuri6-testing-2023-09-27-0938-quincy

All tests passed

**Pull request merged**
