### PR TITLE
mgr/dashboard: Show error messages in password change form

### PR DESCRIPTION
**Pull request by ishanrai05**
fixes: https://tracker.ceph.com/issues/47048

Signed-off-by: Ishan Rai <ishanrai05@gmail.com>

## Checklist
- [x] References tracker ticket
- [x] Updates documentation if necessary
- [x] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by ishanrai05** [comment]
Before
before-1

After
after-1

**Comment by alfonsomthd** [comment]
@ishanrai05 Do you have a tracker issue for this?

**Comment by ishanrai05** [comment]
@alfonsomthd No.

**Comment by nizamial09** [comment]
> Before
> before-1
> 
> After
> after-1

Instead of adding the message "The old and new passwords must be different" to both field, it could be just given to either one of the field. WDYT? @ishanrai05

**Review by tspmelo — CHANGES_REQUESTED** [review]
I can't reproduce this in master.
I notice the PR is based on a 2 week old commit, maybe this as been fixed in the meanwhile.
Could you try master again?

**Comment by ishanrai05** [comment]
@tspmelo Yes, I can't reproduce it now. looks like another PR fixed it. Closing.

**Pull request closed without merging**
