### PR TITLE
os/bluestore: fix spillover alert

### PR DESCRIPTION
**Pull request by ifed01**
Fixes: https://tracker.ceph.com/issues/58440

Signerd-off-by: Igor Fedotov <igor.fedotov@croit.io>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [x] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by ifed01** [comment]
jenkins test make check

**Comment by ifed01** [comment]
jenkins test api

**Comment by ifed01** [comment]
jenkins test make check

**Comment by ifed01** [comment]
jenkins make check

**Comment by ifed01** [comment]
jenkins test api

**Comment by ifed01** [comment]
jenkins test make check

**Comment by ljflores** [comment]
Rados suite review:
https://pulpito.ceph.com/?branch=wip-yuri11-testing-2023-03-28-0950
https://pulpito.ceph.com/?branch=wip-yuri11-testing-2023-03-31-1108

Failures, unrelated:
    1. https://tracker.ceph.com/issues/58585
    2. https://tracker.ceph.com/issues/58946
    3. https://tracker.ceph.com/issues/58265
    4. https://tracker.ceph.com/issues/59271
    5. https://tracker.ceph.com/issues/59057
    6. https://tracker.ceph.com/issues/59333
    7. https://tracker.ceph.com/issues/59334
    8. https://tracker.ceph.com/issues/59335

Details:
    1. rook: failed to pull kubelet image - Ceph - Orchestrator
    2. cephadm: KeyError: 'osdspec_affinity' - Ceph - Orchestrator
    3. TestClsRbd.group_snap_list_max_read failure during upgrade/parallel tests - Ceph - RBD
    4. mon: FAILED ceph_assert(osdmon()->is_writeable()) - Ceph - RADOS
    5. rados/test_envlibrados_for_rocksdb.sh: No rule to make target 'rocksdb_env_librados_test' on centos 8 - Ceph - RADOS
    6. PgScrubber: timeout on reserving replicas - Ceph - RADOS
    7. test_pool_create_with_quotas: Timed out after 60s and 0 retries - Ceph - Mgr - Dashboard
    8. Found coredumps on smithi related to sqlite3 - Ceph - Cephsqlite

**Pull request merged**
