### PR TITLE
installation error on ubuntu 14 corrected  

### PR DESCRIPTION
**Pull request by delco225**

### CODE REVIEW

**Comment by dachary** [comment]
Could you please squash the commits into one ? Also I'm not sure I understand what error you had in the first place ;-)

**Comment by delco225** [comment]
I have just help user to install libtool automatically 
http://paste2.org/I0Hp4aWn for more comprehension

**Comment by dachary** [comment]
@delco225 helping with dependencies installation is what install-deps.sh is supposed to do. This is why autogen.sh does not install anything.

**Comment by dachary** [comment]
@delco225 could you please remove the commits and only keep the last one ? git rebase -i and simply remove the lines with the commits you don't want. After you've done that, you should just keep the line with LC_ALL in the last commit, the other modifications are not necessary.

**Comment by dachary** [comment]
@delco225 you still have more than one commit. Also please change the commit message with "Signed-off-by:" instead of "signed-off-by" (note the upper case letter and the : at the end).

**Comment by delco225** [comment]
ah yes

**Comment by delco225** [comment]
done it left only one commit for installation error please send me a message and i will close the bug report if merged

**Comment by dachary** [comment]
@delco225 much better :-) Could you please change this last commit to not add the diff at https://github.com/ceph/ceph/pull/3466/files#diff-47a21b3706c13e08943e223c12323aa1R17 and not change the whitespace at https://github.com/ceph/ceph/pull/3466/files#diff-47a21b3706c13e08943e223c12323aa1R20 ? You can do that by editing the file, then git add, then git commit --amend, then git push --force

**Comment by delco225** [comment]
i have delete the lines

**Comment by delco225** [comment]
done

**Comment by dachary** [comment]
@delco225 This is good :-) Could you please change the commit message with "Signed-off-by:" instead of "signed-off-by" (note the upper case letter and the : at the end). And while you're at it, it would be better (but it's not wrong) to have a space before the # in the line you added.

**Comment by dachary** [comment]
@delco225 and add an empty line after the title of the commit

**Comment by dachary** [comment]
@delco225 it looks like the bug fix is gone and all that's left are spaces :-)

**Comment by delco225** [comment]
added last commit

**Comment by dachary** [comment]
the message of the last commit is good. Now you have to squash the three commits into one. You can do that with git rebase -i and replace pick with squash on the first two commits.

**Comment by delco225** [comment]
done I have manage with git rebase -i

**Comment by dachary** [comment]
You're almost there ! The last thing is to add some newlines in the commit message. Something like
<pre>
bug: error when installing ceph dependencies with install-deps.sh

The parsing is sensitive to i18n and will fail if, for instance, it is set to French. 
Workaround the problem by always setting the language to C so the script 
can safely assume all output will be in english.

http://tracker.ceph.comm/issues/10596 Fixes: #10596

Signed-off-by: Ahoussi Armand &lt;ahoussi.say@telecom-bretagne.eu>
</pre>
would be perfect. Note that I've added a : at the end of the Signed-off-by, removed the \ at the end of the title, added a newline after the URL of the bug and added a Fixes: #10596 so that redmine knows it is related to this issue (it will not parse the URL itself, unfortunately). I also added an explanation about why the but showed so that a future reader knows what it was about.

**Pull request merged**
