### PR TITLE
qa/tests: added pg log settings to mimic-x

### PR DESCRIPTION
**Pull request by yuriw**
Fixes: https://github.com/ceph/ceph/pull/24308
Signed-off-by: Yuri Weinstein <yweinste@redhat.com>

- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by yuriw** [comment]
http://pulpito.ceph.com/yuriw-2018-11-06_17:35:17-upgrade:mimic-x-master-distro-basic-smithi

**Comment by yuriw** [comment]
DNM per @jdurgin till this is fixed http://tracker.ceph.com/issues/36686

**Comment by yuriw** [comment]
related bug http://tracker.ceph.com/issues/36758

**Comment by neha-ojha** [comment]
closing this in favor of https://github.com/ceph/ceph/pull/25816/commits/45af678d3d36eb24b6c51961794f74cc5ac225b9 which has been merged with https://github.com/ceph/ceph/pull/25816

**Pull request closed without merging**
