### PR TITLE
doc: Tidy up description wording and spelling

### PR DESCRIPTION
**Pull request by anthonyeleven**
doc: Tidied up cloud sync module description paragraph wording and spelling.
Signed-off-by: Anthony D'Atri <anthony.datri@gmail.com>

### CODE REVIEW

**Comment by djgalloway** [comment]
jenkins test make check

**Comment by anthonyeleven** [comment]
@jcsp @yehudasa This has been pending since June and was just marked stale.  It shows a conflict now as well, a result I think of several commits that have been merged since this PR was entered.  Looking at the history of the file those commits seem to be congruent with my changes.

The `make check` above also failed, I suspect for reasons unrelated to the PR itself.

Would you be able to resolve the conflict in favor of my paragraph and merge this?

Thanks!

**Comment by anthonyeleven** [comment]
The `make check` failed again with what *looks* to me like an error not related to the PR itself.  Is this a known thing?

**Comment by anthonyeleven** [comment]
jenkins test make check

**Comment by jcsp** [comment]
The only thing stopping me clicking merge is that there's a merge commit here -- @anthonyeleven , please could you rebase this branch on master, so that there's just a single commit.

This really shouldn't have been ignored for so long -- I'm not sure what's going on with pull requests under the rgw label :-/

**Comment by anthonyeleven** [comment]
Curious.  I suspect that crept in due to a combo of using the UI and CLI along the way, which is valuable, it teaches us to stick with only or or the other.

I think this should now finally be in a state where you can merge.

I'll use lessons learned for my next doc PR.

**Pull request merged**
