### PR TITLE
mgr/cephadm: ok-to-stop for mgr

### PR DESCRIPTION
**Pull request by Daniel-Pivonka**
implements ok-to-stop for mgr

depends on #38854

Signed-off-by: Daniel-Pivonka <dpivonka@redhat.com>

### CODE REVIEW

**Comment by sebastian-philipp** [comment]
https://pulpito.ceph.com/swagner-2021-01-18_11:41:36-rados:cephadm-wip-swagner-testing-2021-01-15-1448-distro-basic-smithi/

Failures

https://tracker.ceph.com/issues/48894
https://tracker.ceph.com/issues/48715
https://tracker.ceph.com/issues/48142

**Comment by sebastian-philipp** [comment]
run-tox-mgr failed

**Comment by Daniel-Pivonka** [comment]
make check will still fail because of changes need from #38854 but tox passed locally with that commit cherry-picked

**Review by sebastian-philipp — CHANGES_REQUESTED** [review]
This PR makes test/test_upgrade.py take 120.4 seconds instead of 0.4 seconds:

```
LANG=C ../../script/run_tox.sh --tox-envs=mypy,py3 mgr -- cephadm/tests/test_upgrade.py
Requirement already satisfied: tox in /home/sebastian/Repos/ceph/build/mgr/lib/python3.6/site-packages (3.14.3)
Requirement already satisfied: virtualenv>=16.0.0 in /home/sebastian/Repos/ceph/build/mgr/lib/python3.6/site-packages (from tox) (16.7.9)
Requirement already satisfied: filelock<4,>=3.0.0 in /home/sebastian/Repos/ceph/build/mgr/lib/python3.6/site-packages (from tox) (3.0.12)
Requirement already satisfied: pluggy<1,>=0.12.0 in /home/sebastian/Repos/ceph/build/mgr/lib/python3.6/site-packages (from tox) (0.13.1)
Requirement already satisfied: packaging>=14 in /home/sebastian/Repos/ceph/build/mgr/lib/python3.6/site-packages (from tox) (20.0)
Requirement already satisfied: toml>=0.9.4 in /home/sebastian/Repos/ceph/build/mgr/lib/python3.6/site-packages (from tox) (0.10.0)
Requirement already satisfied: six<2,>=1.0.0 in /home/sebastian/Repos/ceph/build/mgr/lib/python3.6/site-packages (from tox) (1.13.0)
Requirement already satisfied: importlib-metadata<2,>=0.12; python_version < "3.8" in /home/sebastian/Repos/ceph/build/mgr/lib/python3.6/site-packages (from tox) (1.3.0)
Requirement already satisfied: py<2,>=1.4.17 in /home/sebastian/Repos/ceph/build/mgr/lib/python3.6/site-packages (from tox) (1.8.1)
Requirement already satisfied: pyparsing>=2.0.2 in /home/sebastian/Repos/ceph/build/mgr/lib/python3.6/site-packages (from packaging>=14->tox) (2.4.6)
Requirement already satisfied: zipp>=0.5 in /home/sebastian/Repos/ceph/build/mgr/lib/python3.6/site-packages (from importlib-metadata<2,>=0.12; python_version < "3.8"->tox) (0.6.0)
Requirement already satisfied: more-itertools in /home/sebastian/Repos/ceph/build/mgr/lib/python3.6/site-packages (from zipp>=0.5->importlib-metadata<2,>=0.12; python_version < "3.8"->tox) (8.0.2)
WARNING: You are using pip version 19.3.1; however, version 21.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
mypy installed: DEPRECATION: --find-links option in pip freeze is deprecated. pip 21.2 will remove support for this functionality. You can find discussion regarding this at https://github.com/pypa/pip/issues/9069.,-f /home/sebastian/Repos/ceph/src/pybind/mgr/wheelhouse,apipkg==1.5,attrs==20.3.0,cachetools==4.2.0,-e git+git@github.com:sebastian-philipp/ceph.git@625f380cac993d53d11fbefc078dc25d0b665ff0#egg=ceph&subdirectory=src/python-common,certifi==2020.12.5,cffi==1.14.4,chardet==4.0.0,coverage==5.3.1,cryptography==3.3.1,Cython==0.29.21,execnet==1.7.1,google-auth==1.24.0,idna==2.10,importlib-metadata==3.3.0,iniconfig==1.1.1,Jinja2==2.11.2,kubernetes==12.0.1,MarkupSafe==1.1.1,mypy==0.790,mypy-extensions==0.4.3,oauthlib==3.1.0,packaging==20.8,pluggy==0.13.1,prettytable==2.0.0,py==1.10.0,pyasn1==0.4.8,pyasn1-modules==0.2.8,pycparser==2.20,pyfakefs==4.3.3,pyOpenSSL==20.0.1,pyparsing==2.4.7,pytest==6.2.1,pytest-cov==2.7.1,python-dateutil==2.8.1,PyYAML==5.3.1,remoto==1.2.0,requests==2.25.1,requests-mock==1.8.0,requests-oauthlib==1.3.0,rsa==4.6,six==1.15.0,toml==0.10.2,typed-ast==1.4.2,typing-extensions==3.7.4.3,urllib3==1.26.2,wcwidth==0.2.5,websocket-client==0.57.0,zipp==3.4.0
mypy run-test-pre: PYTHONHASHSEED='2247337815'
mypy run-test: commands[0] | mypy --config-file=../../mypy.ini -m cephadm -m dashboard -m devicehealth -m mds_autoscaler -m mgr_module -m mgr_util -m mirroring -m orchestrator -m progress -m prometheus -m rook -m snap_schedule -m stats -m test_orchestrator -m volumes -m zabbix
Success: no issues found in 16 source files
py3 installed: -f /home/sebastian/Repos/ceph/src/pybind/mgr/wheelhouse,apipkg==1.5,attrs==20.2.0,cachetools==4.1.1,-e git+git@github.com:sebastian-philipp/ceph.git@625f380cac993d53d11fbefc078dc25d0b665ff0#egg=ceph&subdirectory=src/python-common,certifi==2020.6.20,cffi==1.14.2,chardet==3.0.4,coverage==5.2.1,cryptography==3.1,Cython==0.29.21,execnet==1.7.1,google-auth==1.21.1,idna==2.10,importlib-metadata==1.7.0,iniconfig==1.0.1,Jinja2==2.11.2,kubernetes==11.0.0,MarkupSafe==1.1.1,more-itertools==8.5.0,oauthlib==3.1.0,packaging==20.4,pluggy==0.13.1,prettytable==0.7.2,py==1.9.0,pyasn1==0.4.8,pyasn1-modules==0.2.8,pycparser==2.20,pyfakefs==4.1.0,pyOpenSSL==19.1.0,pyparsing==2.4.7,pytest==6.0.1,pytest-cov==2.7.1,python-dateutil==2.8.1,PyYAML==5.3.1,remoto==1.2.0,requests==2.24.0,requests-mock==1.8.0,requests-oauthlib==1.3.0,rsa==4.6,six==1.15.0,toml==0.10.1,urllib3==1.25.10,websocket-client==0.57.0,zipp==3.1.0
py3 run-test-pre: PYTHONHASHSEED='2247337815'
py3 run-test: commands[0] | pytest --doctest-modules cephadm/tests/test_upgrade.py
========================================================================================================================================================= test session starts ==========================================================================================================================================================
platform linux -- Python 3.6.9, pytest-6.0.1, py-1.9.0, pluggy-0.13.1
cachedir: .tox/py3/.pytest_cache
rootdir: /home/sebastian/Repos/ceph/src/pybind/mgr
plugins: requests-mock-1.8.0, pyfakefs-4.1.0, cov-2.7.1
collected 4 items                                                                                                                                                                                                                                                                                                                      

cephadm/tests/test_upgrade.py ....                                                                                                                                                                                                                                                                                               [100%]

==================================================================================================================================================== 4 passed in 120.44s (0:02:00) =====================================================================================================================================================
_______________________________________________________________________________________________________________________________________________________________ summary ________________________________________________________________________________________________________________________________________________________________
  mypy: commands succeeded
  py3: commands succeeded
  congratulations :)
```

**Comment by Daniel-Pivonka** [comment]
test/test_upgrade.py took +120 seconds because of the 4 tries that sleep(15) in _wait_for_ok_to_stop https://github.com/ceph/ceph/blob/master/src/pybind/mgr/cephadm/upgrade.py#L212
2 test, 4 tries each, 15 second 2x4x15=120secs
this test runs with 1 host and 1 mgr and is not a valid config to do an upgrade, you are required to have a standby mgr. https://github.com/ceph/ceph/blob/master/src/pybind/mgr/cephadm/upgrade.py#L523
so ive modified the test to have 2 hosts and 2 mgrs.

**Review by sebastian-philipp — APPROVED** [review]

**Comment by tchaikov** [comment]
- https://pulpito.ceph.com/kchai-2021-02-05_14:59:08-rados-wip-kefu-testing-2021-02-05-1809-distro-basic-smithi/
- https://pulpito.ceph.com/kchai-2021-02-06_12:11:31-rados-wip-kefu-testing-2021-02-06-1838-distro-basic-smithi/
- https://pulpito.ceph.com/kchai-2021-02-07_14:19:29-rados-wip-kefu-testing-2021-02-07-2019-distro-basic-smithi/

reran the failed tests on master

- https://pulpito.ceph.com/kchai-2021-02-08_02:14:21-rados-wip-kefu2-testing-2021-02-08-0023-distro-basic-smithi/

e2e failures tracked by

- https://tracker.ceph.com/issues/49205

**Pull request merged**
