### PR TITLE
Luminous multi osds per device support

### PR DESCRIPTION
**Pull request by jiribroulik**
Ability to manage size and partition numbers for Osds on single device.
Nice to have for Osds on SSDs for performance.

### CODE REVIEW

**Comment by alfredodeza** [comment]
I am inclined to say we aren't going to add any new features to ceph-disk, and that ceph-volume is perfectly capable on supporting multiple osds on a same device in Luminous.

So I am -1 on this, @tchaikov do you have any input here?

**Comment by jiribroulik** [comment]
So how is it supported in Luminous please?

Traceback (most recent call last):
  File "/usr/sbin/ceph-disk", line 9, in <module>
    load_entry_point('ceph-disk==1.0.0', 'console_scripts', 'ceph-disk')()
  File "/usr/lib/python2.7/dist-packages/ceph_disk/main.py", line 5736, in run
    main(sys.argv[1:])
  File "/usr/lib/python2.7/dist-packages/ceph_disk/main.py", line 5674, in main
    args.func(args)
  File "/usr/lib/python2.7/dist-packages/ceph_disk/main.py", line 2093, in main
    Prepare.factory(args).prepare()
  File "/usr/lib/python2.7/dist-packages/ceph_disk/main.py", line 2082, in prepare
    self._prepare()
  File "/usr/lib/python2.7/dist-packages/ceph_disk/main.py", line 2163, in _prepare
    self.data.prepare(*to_prepare_list)
  File "/usr/lib/python2.7/dist-packages/ceph_disk/main.py", line 2937, in prepare
    self.prepare_device(*to_prepare_list)
  File "/usr/lib/python2.7/dist-packages/ceph_disk/main.py", line 3110, in prepare_device
    super(PrepareBluestoreData, self).prepare_device(*to_prepare_list)
  File "/usr/lib/python2.7/dist-packages/ceph_disk/main.py", line 2999, in prepare_device
    self.sanity_checks()
  File "/usr/lib/python2.7/dist-packages/ceph_disk/main.py", line 2962, in sanity_checks
    check_partitions=not self.args.dmcrypt)
  File "/usr/lib/python2.7/dist-packages/ceph_disk/main.py", line 966, in verify_not_in_use
    raise Error('Device is mounted', partition)
ceph_disk.main.Error: Error: Device is mounted: /dev/vdf1
root@osd0:~#

**Comment by alfredodeza** [comment]
This is supported in Luminous with `ceph-volume`. You are trying with `ceph-disk`, which doesn't support multiple OSDs on the same device.

With `ceph-volume` you would need to get that NVMe on a volume group and then carve out as many logical volumes as you want to create OSDs from

**Comment by jiribroulik** [comment]
@alfredodeza Thank you, ceph-volume does not support encrypted osds at Luminous release, right?
It will be supported in next release by ceph-volume maybe?

**Comment by alfredodeza** [comment]
@jiribroulik dmcrypt support in ceph-volume just got merged into master, this means it will be ready for the Mimic release, not Luminous.

**Comment by tchaikov** [comment]
i concur with @alfredodeza , we don't want to add new features to ceph-disk . only bug fixes are accepted for it, as it's being deprecated.

**Pull request closed without merging**
