### PR TITLE
rgw/s3select : fix crash by exception

### PR DESCRIPTION
**Pull request by galsalomon66**
https://github.com/ceph/s3select/pull/141
https://github.com/ceph/s3select/pull/142

include resolution for 
https://bugzilla.redhat.com/show_bug.cgi?id=2245145
https://bugzilla.redhat.com/show_bug.cgi?id=2245575
https://bugzilla.redhat.com/show_bug.cgi?id=2246150
https://bugzilla.redhat.com/show_bug.cgi?id=2248866
https://bugzilla.redhat.com/show_bug.cgi?id=2248862
https://bugzilla.redhat.com/show_bug.cgi?id=2248157

it also resolves 
missing check-type in trim operator
wrong parsing rule for is-null/is-not-null 

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [x] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by galsalomon66** [comment]
http://pulpito.front.sepia.ceph.com/gsalomon-2023-11-02_05:57:59-rgw:verify-exception_cause_crash-distro-default-smithi/
all green

**Comment by galsalomon66** [comment]
https://pulpito.ceph.com/gsalomon-2023-11-05_04:01:15-rgw:verify-exception_cause_crash-distro-default-smithi/
all green

**Comment by cbodley** [comment]
> [googletest] ceph_test_librbd failed. Error: Command returned non-zero code(1): "cmd /c 'C:\ceph\ceph_test_librbd.exe --gtest_output=xml:C:\workspace\test_results\out\ceph_test_librbd\ceph_test_librbd_results.xml  >> C:\workspace\test_results\out\ceph_test_librbd\ceph_test_librbd_results.log 2>&1'".

**Comment by cbodley** [comment]
thanks @galsalomon66. please squash the commits before merging

**Comment by galsalomon66** [comment]
https://pulpito.ceph.com/gsalomon-2023-11-06_16:45:54-rgw:verify-exception_cause_crash-distro-default-smithi/
3 dead
the rest are green

**Comment by galsalomon66** [comment]
https://pulpito.ceph.com/gsalomon-2023-11-07_06:41:11-rgw-exception_cause_crash-distro-default-smithi/
64 passed 
6 failed

investigating

**Comment by cbodley** [comment]
multisite failures are expected
`bucket_notification/test_bn.py -v -a kafka_test` https://tracker.ceph.com/issues/62136
valgrind leak https://tracker.ceph.com/issues/63445
kmip python-dev https://tracker.ceph.com/issues/58523

the s3test failures in http://qa-proxy.ceph.com/teuthology/gsalomon-2023-11-07_06:41:11-rgw-exception_cause_crash-distro-default-smithi/7450611/teuthology.log are new:
```
2023-11-07T11:07:41.048 INFO:teuthology.orchestra.run.smithi134.stdout:=========================== short test summary info ============================
2023-11-07T11:07:41.048 INFO:teuthology.orchestra.run.smithi134.stdout:FAILED s3tests_boto3/functional/test_s3select.py::test_progress_expressions
2023-11-07T11:07:41.048 INFO:teuthology.orchestra.run.smithi134.stdout:ERROR s3tests_boto3/functional/test_s3select.py::test_progress_expressions - ...
2023-11-07T11:07:41.049 INFO:teuthology.orchestra.run.smithi134.stdout:ERROR s3tests_boto3/functional/test_s3select.py::test_output_serial_expressions
```

**Comment by galsalomon66** [comment]
http://qa-proxy.ceph.com/teuthology/gsalomon-2023-11-07_06:41:11-rgw-exception_cause_crash-distro-default-smithi/7450611/teuthology.log

contain a crash with s3select-stack

**Comment by galsalomon66** [comment]
https://pulpito.ceph.com/gsalomon-2023-11-09_05:41:08-rgw-exception_cause_crash-distro-default-smithi/
3 failures not related to s3select changes 


(commit-sha1 = https://github.com/ceph/ceph/pull/54298/commits/a25478793b20020a67b3ceb133f2365db0145a7b)

**Pull request closed without merging**
