### PR TITLE
common: OpTracker age histogram calculation is not correct

### PR DESCRIPTION
**Pull request by wonzhq**
While the TrackedOps in each sharded list are ordered, there are no
order among different shared lists. Looping the sharded list one by one
won't be able to get the right histogram.

Signed-off-by: Zhiqiang Wang <zhiqiang.wang@intel.com>

### CODE REVIEW

**Comment by wonzhq** [comment]
@tchaikov do you have time to take a look at this one? I'm wondering if I could also include this one in the teuthology run together with my others.

**Comment by dachary** [comment]
@wonzhq do you have access to a teuthology cluster ?

**Comment by wonzhq** [comment]
@dachary yes, we have a local teuthology cluster. And I can also access sepia.

**Comment by tchaikov** [comment]
@wonzhq will review it shortly. it fell off the cracks =(

**Comment by tchaikov** [comment]
@wonzhq the fix makes sense to me. the only concern is that the size of `all_ms` could be large when something goes wrong, probably an alternative is to 

1. update `calc_bits_of(int t)` as following to avoid the tight loop:
```c
    return x ? (sizeof(x) * 8 - __builtin_clz(x)) : 0;
```
2. have a `std::map<bin,count> m`. and replace `all_ms.insert(ms);` with `m[calc_bits_of(ms)]++;` and dump it to `pow2_hist_t` after collecting the ops in all shards.

**Comment by wonzhq** [comment]
@tchaikov thanks for taking a look!

> update calc_bits_of(int t) as following to avoid the tight loop

I'd like to leave this to someone else since I'm not quite clear which one performs better and if it is worth doing this.

> have a std::map<bin,count> m. and replace all_ms.insert(ms); with m[calc_bits_of(ms)]++; and dump it to pow2_hist_t after collecting the ops in all shards.

Good idea! But why not do `h->add(ms)` directly?

**Comment by tchaikov** [comment]
> Good idea! But why not do `h->add(ms)` directly?

i just don't like the overhead of 
```c++
_expand_to(bin + 1);
///
_contract();
```
calls. but yeah, i'd admit that's a sign of premature optimisation. as this function is called every 6 seconds.

**Comment by tchaikov** [comment]
> I'd like to leave this to someone else since I'm not quite clear which one performs better and if it is worth doing this.

yeah, makes sense to me. i will do some benchmark on my side.

**Comment by wonzhq** [comment]
> i just don't like the overhead of
```
> _expand_to(bin + 1);
> ///
> _contract();
```

> calls. but yeah, i'd admit that's a sign of premature optimisation. as this function is called every 6 seconds.

Since we loops from the oldest to the newest, most likely we just need to expand/contract the vector only once, which is the same as `set_bin`.

**Comment by tchaikov** [comment]
agreed, they will be just no-ops.

**Comment by wonzhq** [comment]
@tchaikov i've updated this PR, please take another look, thanks!

**Comment by wonzhq** [comment]
Looks like after updating the commit message, @tchaikov 's comment is gone. I'm pasting his previous comment below:

> this changes the behaviour of get_age_ms_histogram(), it put all ops which was initiated before 2^30 ms into a single bin. and now it it put them into (2^(n-1), 2^n] buckets. i'm okay with it. but could you put a note in the commit message?

> @gregsfortytwo , are you good with this change?

**Comment by gregsfortytwo** [comment]
I don't know how the histogram bits work. @athanatos is back beginning of next week, ask him. ;)

**Pull request merged**
