### PR TITLE
cephadm: merge `--config-and-keyring` and `--config-json` args

### PR DESCRIPTION
**Pull request by mgfritch**
Both args can be passed via `cephadm deploy` and both read JSON from stdin.

Signed-off-by: Michael Fritch <mfritch@suse.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by liewegas** [comment]
retest this please

**Comment by liewegas** [comment]
when upgrading crash,
```
2020-03-11T13:56:59.135+0000 7f1110167700  0 [cephadm ERROR root] cephadm exited with an error code: 1, stderr:ERROR: no keyring provided
Traceback (most recent call last):
  File "/usr/share/ceph/mgr/cephadm/module.py", line 1498, in _run_cephadm
    code, '\n'.join(err)))
RuntimeError: cephadm exited with an error code: 1, stderr:ERROR: no keyring provided
2020-03-11T13:56:59.135+0000 7f1110167700 -1 log_channel(cephadm) log [ERR] : cephadm exited with an error code: 1, stderr:ERROR: no keyring provided
Traceback (most recent call last):
  File "/usr/share/ceph/mgr/cephadm/module.py", line 1498, in _run_cephadm
    code, '\n'.join(err)))
RuntimeError: cephadm exited with an error code: 1, stderr:ERROR: no keyring provided
2020-03-11T13:56:59.135+0000 7f1110167700 -1 log_channel(cluster) log [ERR] : Unhandled exception from module 'cephadm' while running on mgr.x: cephadm exited with an error code: 1, stderr:ERROR: no keyring provided
2020-03-11T13:56:59.135+0000 7f1110167700 -1 cephadm.serve:
2020-03-11T13:56:59.135+0000 7f1110167700 -1 Traceback (most recent call last):
  File "/usr/share/ceph/mgr/cephadm/module.py", line 1086, in serve
    self._do_upgrade()
  File "/usr/share/ceph/mgr/cephadm/module.py", line 864, in _do_upgrade
    'redeploy'
  File "/usr/share/ceph/mgr/cephadm/module.py", line 1783, in _daemon_action
    return self._create_daemon(daemon_type, daemon_id, host)
  File "/usr/share/ceph/mgr/cephadm/module.py", line 2128, in _create_daemon
    stdin=json.dumps(cephadm_config))
  File "/usr/share/ceph/mgr/cephadm/module.py", line 1498, in _run_cephadm
    code, '\n'.join(err)))
RuntimeError: cephadm exited with an error code: 1, stderr:ERROR: no keyring provided
```
see running cluster on smithi160 and 174 to debug..

**Comment by mgfritch** [comment]
redeploy for the crash keyring should use `client.crash.<name>` instead of `crash.<name>`

```
2020-03-11T13:56:59.806+0000 7f831799e700  7 mon.b@2(peon).log v251 update_from_paxos applying incremental log 251 2020-03-11T13:56:58.882338+0000 mon.a (mon.0) 141 : audit [INF] from='mgr.64103 172.21.15.160:0/2071080989' entity='mgr.x' cmd=[{"prefix": "auth get", "entity": "crash.smithi160"}]: dispatch
```

**Comment by mgfritch** [comment]
jenkins test make check

**Comment by liewegas** [comment]
How is the package mode broken?

**Comment by sebastian-philipp** [comment]
> How is the package mode broken?

in the package mode, we can no longer be sure, that we have an exact version match between the mgr container and cephadm on the remote host.

**Comment by liewegas** [comment]
Ah, right. Once we release I think we need to be really careful about breaking changes, but until then I think we want to squeeze these in!

**Pull request merged**
