### PR TITLE
nautilus: tests: test_librados_build.sh: grab from nautilus branch in nautilus

### PR DESCRIPTION
**Pull request by smithfarm**
Fixes: f18903a66c86695d4ad5e8b99756c03f00fcd025
Fixes: https://tracker.ceph.com/issues/42782
Signed-off-by: Nathan Cutler <ncutler@suse.com>

### CODE REVIEW

**Comment by smithfarm** [comment]
It looks to me like https://github.com/ceph/ceph/pull/31045 should be backported to nautilus (and possible all the way back to luminous) as well, since it's a follow-on fix for #12607 which was merged for the luminous release?

```
$ git describe 25c9910
v11.1.0-6586-g25c9910503
```

**Comment by tchaikov** [comment]
i think #31045 is more of a cleanup. so probably there is no need to backport it?

**Comment by smithfarm** [comment]
If we don't need to backport it, so much the better.

**Comment by smithfarm** [comment]
@neha-ojha I don't currently have a checklist of things that have to be done for each major release. I'll think about where best to maintain such a list, and I'll make sure this is included.

**Comment by tchaikov** [comment]
probably an alternative is 
```diff
diff --git a/examples/librados/Makefile b/examples/librados/Makefile
index fd61cb9980..97e5e7d368 100644
--- a/examples/librados/Makefile
+++ b/examples/librados/Makefile
@@ -6,7 +6,7 @@ CXX_INC?=$(LOCAL_LIBRADOS_INC)
 CXX_CC=$(CXX) $(CXX_FLAGS) $(CXX_INC) $(LOCAL_LIBRADOS)

 CC?=gcc
-CC_FLAGS=-Wno-unused-parameter -Wall -Wextra -Werror -g
+CC_FLAGS=-Wno-unused-parameter -Wall -Wextra -g
 CC_INC=$(LOCAL_LIBRADOS_INC)
 CC_LIBS?=-lrados
 CC_CC=$(CC) $(CC_FLAGS) $(CC_INC) $(LOCAL_LIBRADOS)
```

**Comment by yuriw** [comment]
[wip-yuri8-testing-2019-11-16-2138-nautilus](https://trello.com/c/2l18BM3z/765-wip-yuri8-testing-2019-11-16-2138-nautilus)

**Comment by tchaikov** [comment]
i propose #31693

**Pull request merged**
