### PR TITLE
mgr/nfs: handle subprocess exceptions

### PR DESCRIPTION
**Pull request by mgfritch**
Fixes: https://tracker.ceph.com/issues/53096
Signed-off-by: Michael Fritch <mfritch@suse.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by liewegas** [comment]
I was just about to move this code into mgr_module.py: https://github.com/ceph/ceph/pull/43655/commits/dd2de9a8800b75b78e9f0c96c98bf510905a693e

I'll incorporate this fix there?

**Comment by liewegas** [comment]
updated version here: https://github.com/ceph/ceph/pull/43655/commits/fe02b3f98df731a7e6dd2bc830cceb5e9ac53785

**Comment by mgfritch** [comment]
> I was just about to move this code into mgr_module.py: [dd2de9a](https://github.com/ceph/ceph/commit/dd2de9a8800b75b78e9f0c96c98bf510905a693e)
> 
> I'll incorporate this fix there?

yeah a common place for this logic would be good

**Review by liewegas — APPROVED** [review]

**Comment by liewegas** [comment]
jenkins test make check arm64

**Comment by tchaikov** [comment]
jenkins test make check arm64

**Comment by tchaikov** [comment]
```
[ RUN      ] Queue.SpawnAsyncRequest
../src/test/rgw/test_rgw_dmclock_scheduler.cc:425: Failure
Value of: context.stopped()
  Actual: false
Expected: true
[  FAILED  ] Queue.SpawnAsyncRequest (2 ms)
[----------] 8 tests from Queue (12 ms total)

[----------] Global test environment tear-down
[==========] 8 tests from 1 test suite ran. (12 ms total)
[  PASSED  ] 7 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] Queue.SpawnAsyncRequest
```

it seems that https://tracker.ceph.com/issues/42788 surfaced again.

**Comment by liewegas** [comment]
https://pulpito.ceph.com/sage-2021-10-30_01:41:34-orch:cephadm-wip-sage4-testing-2021-10-29-1941-distro-basic-smithi/

**Pull request merged**
