### PR TITLE
Enable extern plugins load to compressor

### PR DESCRIPTION
**Pull request by Ved-vampir**
Based on https://github.com/ceph/ceph/pull/6696, common plugins infrastructure.

### CODE REVIEW

**Comment by liewegas** [comment]
There is a PR or patch floating around here somewhere with a generic plugin loading framework... which I swore I just saw referenced in teh last couple weeks but I can't find now :(.  The original PR was https://github.com/ceph/ceph/pull/6150 but I suspect it needs some cleanup.  Can we please get this infrastructure in first, and then base any new plugin loaders off of that?  Thanks!

**Comment by Ved-vampir** [comment]
It would be better, if I separate common infrastructure and compression at all, I think? I create pull (https://github.com/ceph/ceph/pull/6696) request with common plugin data and update this using it.

**Comment by varadakari** [comment]
@liewegas i am working fixing the PR #6150, but facing some issues with the build order of the files compiled resulting in failure for ceph_ver.h. Any help would be much appreciated, will rebase #6150 with latest master.

**Comment by dachary** [comment]
@Ved-vampir the bot failure is due to a temporary network outage. It will pass if submitted again. Sorry for the inconvenience.

**Comment by Ved-vampir** [comment]
Any feedback here?

**Comment by liewegas** [comment]
It looks right to me!

**Comment by liewegas** [comment]
make[2]: *** No rule to make target `copy-example', needed by `test/compressor/test_compression_plugin.cc'. Stop.


from http://gitbuilder.sepia.ceph.com/gitbuilder-ceph-deb-trusty-amd64-basic/log.cgi?log=b474d798296671ea665d0fe6f41a13d1e7a5d1bf

**Comment by Ved-vampir** [comment]
I have fixed make dist error at Friday, please, review, than you'll have some time.

**Comment by liewegas** [comment]
test/compressor/compressor_plugin_example.cc:21:32: fatal error: compressor_example.h: No such file or directory

need to include the header in the noinst_HEADERS list in Makefile.am

**Comment by liewegas** [comment]
rebase please?

**Comment by liewegas** [comment]
RPM build errors:
Installed (but unpackaged) file(s) found:
/usr/lib64/ceph/compressor/libceph_example.so
/usr/lib64/ceph/compressor/libceph_example.so.0
/usr/lib64/ceph/compressor/libceph_example.so.0.0.0
/usr/lib64/ceph/compressor/libceph_snappy.so
/usr/lib64/ceph/compressor/libceph_snappy.so.2
/usr/lib64/ceph/compressor/libceph_snappy.so.2.0.0

**Comment by liewegas** [comment]
debs build fine tho.  almost there!

**Comment by liewegas** [comment]
pushed wip-sage-testing3 branch to check build

**Comment by liewegas** [comment]
22099ee3410372dbb775ee6ca4238a429fde9ffa has a typo

**Comment by liewegas** [comment]
merged manually!

**Comment by Ved-vampir** [comment]
@liewegas Thanks a lot!

**Pull request closed without merging**
