### PR TITLE
osd: default osd_objectstore=bluestore

### PR DESCRIPTION
**Pull request by liewegas**
- change the default
- fix standaloen and other tests

This replaces #24642 

Fixes: http://tracker.ceph.com/issues/36494

### CODE REVIEW

**Comment by liewegas** [comment]
@vumrao @neha-ojha @jdurgin we could alternatively adjust the standalone tests to mount via fuse and fiddle that way, but this is easier and probably okay?

**Comment by jdurgin** [comment]
seems like much of the EIO testing would need to be different for bluestore, since it's detecting problems during reads. seems fine to keep these versions of the tests for filestore

**Comment by vumrao** [comment]
Thank you, Josh and Sage, for your feedback.

**Comment by liewegas** [comment]
@vumrao this replaces your PR since it was fixing some of those patches.  squashed all the test changes into one commit.

**Comment by vumrao** [comment]
@liewegas Thank you Sage.

**Comment by wjwithagen** [comment]
@liewegas 
Right, guessing that this is why my jenkins runs are crashing since this morning. Bluestore on FreeBSD has not yet have all its issue ironed out.

**Comment by wjwithagen** [comment]
@liewegas 
Yup, `#ifdef`-ing it, gets jenkins oke again. I'll keep this in my local jenkins until bluestore really works.

**Pull request merged**
