### PR TITLE
jewel: ceph-disk: ceph-disk@.service races with ceph-osd@.service

### PR DESCRIPTION
**Pull request by dachary**
http://tracker.ceph.com/issues/18007
http://tracker.ceph.com/issues/18009

### CODE REVIEW

**Comment by dachary** [comment]
jenkins test this please (changing base)

**Comment by dachary** [comment]
DNM because the backport is incomplete, it misses https://github.com/ceph/ceph/pull/12241

**Comment by dachary** [comment]
check this please

**Comment by wido** [comment]
I would really like to see this one merged and backported in to Jewel 10.2.6. This issue is hitting multiple users I know of.

**Comment by smithfarm** [comment]
@dachary This PR was included in this [1] integration branch which already passed a ceph-disk suite at [2].

[1] http://tracker.ceph.com/issues/17851#note-17
[2] http://tracker.ceph.com/issues/17851#note-18

OK to merge?

**Pull request merged**
