### PR TITLE
nautilus: mgr/dashboard: Adapt iSCSI overview page to make use of ceph-iscsi

### PR DESCRIPTION
**Pull request by ricardoasmarques**
https://tracker.ceph.com/issues/39122

### CODE REVIEW

**Comment by callithea** [comment]
jenkins test dashboard

**Comment by callithea** [comment]
jenkins test dashboard

**Comment by ricardoasmarques** [comment]
jenkins test dashboard

**Comment by yuriw** [comment]
[wip-yuri5-testing-2019-04-12-1916-nautilus](https://trello.com/c/tRDDEFxc/592-wip-yuri5-testing-2019-04-12-1916-nautilus)

**Pull request merged**
