### PR TITLE
librbd: expose internal plugin API to plugin libraries

### PR DESCRIPTION
**Pull request by dillaman**
## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Review by trociny — APPROVED** [review]
LGTM

**Review by trociny — APPROVED** [review]

**Comment by trociny** [comment]
@dillaman Now `qemu_on_immutable_object_cache_and_thrash` test starts reporting failure [1]:
```
2020-08-27T09:28:58.115 INFO:teuthology.orchestra.run.smithi099:> qemu-img convert -f qcow2 -O raw /home/ubuntu/cephtest/qemu/base.client.0.qcow2 rbd:rbd/client.0.0
2020-08-27T09:28:58.183 INFO:teuthology.orchestra.run.smithi099.stderr:qemu-img: Could not open 'rbd:rbd/client.0.0': error reading header from client.0.0: Function not implemented
```
In the client log:
```
2020-08-27T09:28:58.180+0000 7f9dd4efa700 -1 load failed dlopen(): "/usr/lib64/ceph/librbd/libceph_librbd_parent_cache.so: undefined symbol: _ZN4ceph6buffer7v15_2_04list17always_empty_bptrE" or "/usr/lib64/ceph/libceph_librbd_parent_cache.so: cannot open shared object file: No such file or directory"
2020-08-27T09:28:58.180+0000 7f9dd4efa700 -1 librbd::PluginRegistry: 0x558d0cb09200 init: failed to load plugin: parent_cache
2020-08-27T09:28:58.180+0000 7f9dd4efa700 -1 librbd::image::OpenRequest: failed to initialize plugin registry: (38) Function not implemented
2020-08-27T09:28:58.180+0000 7f9dd4efa700 -1 librbd::ImageState: 0x558d0cb09100 failed to open image: (38) Function not implemented
```

[1] http://qa-proxy.ceph.com/teuthology/trociny-2020-08-27_08:23:31-rbd-wip-mgolub-testing-distro-basic-smithi/5379730/teuthology.log

**Comment by dillaman** [comment]
Odd -- I'll take a look. Hopefully it's as simple as just linking against librados

**Comment by dillaman** [comment]
> Odd -- I'll take a look. Hopefully it's as simple as just linking against librados

Yup, that seems to have been the issue.

**Comment by trociny** [comment]
@dillaman I suppose it is going to be backported to octopus. I will update the tracker ticket accordingly.

**Comment by smithfarm** [comment]
> @dillaman I suppose it is going to be backported to octopus. I will update the tracker ticket accordingly.

@trociny Which tracker ticket is that?

**Comment by trociny** [comment]
@smithfarm I mean the tracker ticket for this PR [1]. It had the "Backport" field empty. I set it to octopus.

Just cherry-picking into #36860 would work too.

[1] https://tracker.ceph.com/issues/46916

**Comment by dillaman** [comment]
I don't think Octopus has the librbd plugin system -- it was added only to the master branch [1]. 


[1] https://tracker.ceph.com/issues/45137

**Comment by trociny** [comment]
Ah, indeed. I forgot about it. Sorry.

**Pull request merged**
