### PR TITLE
client: flush the caps release in filesystem sync

### PR DESCRIPTION
**Pull request by lxbsz**
Fixes: https://tracker.ceph.com/issues/67221

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Review by vshankar — CHANGES_REQUESTED** [review]
Please explain the commit message regarding the idea behind the change.

**Comment by dparmar18** [comment]
were there any problems uncovered due this @lxbsz ?

**Comment by dparmar18** [comment]
In tracker you mentioned "Though the tick thread will do this but some times the tick could be stuck.", is it due to the thread entering sleep here?:
https://github.com/ceph/ceph/blob/2fa0e43b7e714df9811f87cbc5bf862ac503483c/src/client/Client.cc#L7119-L7121

So maybe when the thread is sleeping, we're at a situation where the cap flush is needed but can't until the thread wakes up, but this should just be a slight delay i guess, shouldn't be that critical. What are other scenarios?

**Comment by lxbsz** [comment]
> In tracker you mentioned "Though the tick thread will do this but some times the tick could be stuck.", is it due to the thread entering sleep here?:
> 
> https://github.com/ceph/ceph/blob/2fa0e43b7e714df9811f87cbc5bf862ac503483c/src/client/Client.cc#L7119-L7121
> 
> So maybe when the thread is sleeping, we're at a situation where the cap flush is needed but can't until the thread wakes up, but this should just be a slight delay i guess, shouldn't be that critical. What are other scenarios?

Not sure, before I hit several times the tick thread was blocked for a long time, maybe over load or something else.

Here for this we just want to explicitly expose one method to flush the cap release manually to get rid of the cap revoke stuck bugs as we hit in https://tracker.ceph.com/issues/57244 many times before.

**Comment by lxbsz** [comment]
> were there any problems uncovered due this @lxbsz ?

We have figured out there has a race between caps revoke and the cap release in kclient. Just want to expose one way to flush the cap releases manually to get rid of the bug.

**Comment by dparmar18** [comment]
> > were there any problems uncovered due this @lxbsz ?
> 
> We have figured out there has a race between caps revoke and the cap release in kclient. Just want to expose one way to flush the cap releases manually to get rid of the bug.

So this is a temporary fix?

**Comment by vshankar** [comment]
This PR is under test in [https://tracker.ceph.com/issues/67368](https://tracker.ceph.com/issues/67368).

**Comment by lxbsz** [comment]
> > > were there any problems uncovered due this @lxbsz ?
> > 
> > 
> > We have figured out there has a race between caps revoke and the cap release in kclient. Just want to expose one way to flush the cap releases manually to get rid of the bug.
> 
> So this is a temporary fix?

No, the caps releases also the metadata should be flushed when syncing the whole filesystem.

**Comment by lxbsz** [comment]
jenkins test api

**Comment by lxbsz** [comment]
jenkins test make check

**Review by dparmar18 — APPROVED** [review]
LGTM, we need a mechanism to flush cap releases manually and till now we had none. Other thing is `Client::sync_fs` does flush the metadata logs at `Client::flush_mdlog_sync` but never did we flush the cap releases. This is adding the missing bit to the function.

**Review by vshankar — APPROVED** [review]
https://tracker.ceph.com/projects/cephfs/wiki/Main#wip-vshankar-testing-20240806162829-debug

**Comment by vshankar** [comment]
jenkins test make check

**Comment by vshankar** [comment]
jenkins test api

**Comment by vshankar** [comment]
jenkins retest this please

**Comment by vshankar** [comment]
rebased and pushed for getting jenkins tests to pass.

**Pull request merged**
