### PR TITLE
src/rgw: DPP addition 2

### PR DESCRIPTION
**Pull request by TRYTOBE8TME**
## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by alimaredia** [comment]
@TRYTOBE8TMEis this PR (minus the last commit) supposed to be mostly low hanging DPP's? 

I see in the commit for `rgw_coroutine.cc` you changed ~8 `ldout/lderr`'s total but when I look through that file via `grep -R "ldout" src/rgw/rgw_coroutine.cc | wc -l`on master I see 14 of them. Did you already hit the others for that file in the other PR?

**Comment by alimaredia** [comment]
jenkins test make check

**Comment by TRYTOBE8TME** [comment]
jenkins test make check

**Comment by alimaredia** [comment]
@And any update here?

**Comment by TRYTOBE8TME** [comment]
this is stuck because I see failures [here](https://shaman.ceph.com/builds/ceph/wip-rgw-dpp-1/00258451ab4df17966d83b98eb58d268a1bb75c1/)
It would be great if @cbodley or anyone else can help me out figure out the reason of this?

**Comment by dang** [comment]
The logs in that build have been deleted.  Can you run a new build, and link the failures?

**Comment by TRYTOBE8TME** [comment]
> The logs in that build have been deleted. Can you run a new build, and link the failures?

https://shaman.ceph.com/builds/ceph/wip-rgw-dpp-1/c0fb2fc55f200bb32de1a1d4d19db2fd114aacdc/

**Pull request closed without merging**
