### PR TITLE
cephadm: capadd and privileged are mutex with podman >= 2.0

### PR DESCRIPTION
**Pull request by jschmid1**
Signed-off-by: Joshua Schmid <jschmid@suse.de>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Review by sebastian-philipp — APPROVED** [review]

**Comment by jschmid1** [comment]
test results: https://pulpito.ceph.com/jschmid-2020-09-16_10:44:07-rados:cephadm-wip-jschmid1-testing-2020-09-16-1013-distro-basic-smithi/

Test failure: test_cluster_set_reset_user_config (tasks.cephfs.test_nfs.TestNFS):

status: known
identified by: https://github.com/ceph/ceph/pull/37122#issuecomment-692099983

Test failure cluster [ERR] Health check failed: 1 filesystem is offline (MDS_ALL_DOWN)" in cluster log

status: unkown

**Review by Devp00l — APPROVED** [review]

**Review by mgfritch — APPROVED** [review]

**Comment by mgfritch** [comment]
jenkins make check

**Comment by mgfritch** [comment]
jenkins test make check

**Comment by mgfritch** [comment]
retest this please

**Comment by mgfritch** [comment]
Green:
https://pulpito.ceph.com/mgfritch-2020-09-21_20:24:35-rados:cephadm-wip-mgfritch-testing-2020-09-21-1034-distro-basic-smithi/

Failure:
https://tracker.ceph.com/issues/47591

**Pull request merged**
