### PR TITLE
doc: add a link to ceph-deploy document

### PR DESCRIPTION
**Pull request by tchaikov**
## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by tchaikov** [comment]
jenkins test signed

**Comment by tchaikov** [comment]
jenkins test signed

**Comment by zdover23** [comment]
1. The docs build-check is failing in github, but when I check out this branch locally and build it, it builds with no problem. So something's up.

2. I'm not crazy about the word "quickly" in the phrase "for quickly deploying", but I don't think it should slow down the merge of this PR into master.

3. Whatever's going on with the docs build-check, though, might be a showstopper. What's up with that?

**Review by zdover23 — CHANGES_REQUESTED** [review]
I've left a comment in the Conversation tab regarding potential changes. The upshot is: I can build this with no problem locally, so I don't know why the docs build-check is failing here. As long as that's judged to be no problem, LGTM.

**Review by neha-ojha — APPROVED** [review]

**Review by jdurgin — APPROVED** [review]

**Pull request merged**
