### PR TITLE
[DNM] nautilus: install-deps.sh: Use dnf for rhel/centos 8

### PR DESCRIPTION
**Pull request by badone**
Backport of #31144 (not merged yet)

parent tracker: https://tracker.ceph.com/issues/42504

### CODE REVIEW

**Comment by badone** [comment]
> cherry-pick needs to be from a PR that is in master - I guess the master PR is still open...

Hmmm... sounds fair. We wait then.

**Comment by badone** [comment]
I've now created a tracker for this issue at https://tracker.ceph.com/issues/42504

**Comment by smithfarm** [comment]
@badone Would you mind if we closed this in favor of the standard backporting workflow?

**Comment by badone** [comment]
@smithfarm Sure, no problem. Perhaps you could take a look at https://github.com/ceph/ceph/pull/31144 then?

**Pull request closed without merging**
