### PR TITLE
rbd-mirror: force-promoted image will remain R/O until rbd-mirror daemon restarted

### PR DESCRIPTION
**Pull request by dillaman**

### CODE REVIEW

**Comment by dillaman** [comment]
There is an unrelated memory corruption within rbd-mirror on master -- need to fix that first before testing and merging this PR

**Comment by trociny** [comment]
@dillaman Does #11104 fix the memory corruption issue you mention here and [DNM] prefix can be removed?

**Comment by dillaman** [comment]
@trociny Yes, so far so good.

**Comment by trociny** [comment]
@dillaman "force promote" functional test passes locally for me but regularly fails on teuthology:

http://pulpito.ceph.com/trociny-2016-09-17_15:04:54-rbd-wip-mgolub-testing---basic-smithi/
http://pulpito.ceph.com/trociny-2016-09-17_15:04:37-rbd-wip-mgolub-testing---basic-mira/
http://pulpito.ceph.com/trociny-2016-09-17_15:04:21-rbd-wip-mgolub-testing---basic-vps/
http://pulpito.ceph.com/trociny-2016-09-17_15:04:04-rbd-wip-mgolub-testing---basic-vps/

Note, I rose debugging level for rbd-mirror daemon in the qa-suite config, so you might find useful data in cluster1-client.mirror.*.log files.

It looks I don't see image replayer handle_promoted handler being fired on tethology.

**Comment by dillaman** [comment]
@trociny Looks like journal::JournalMetadata::allocate_tag doesn't send out an update notification, so a forced promotion on an idle image wouldn't never be detected.

**Comment by dillaman** [comment]
@trociny repushed

**Comment by trociny** [comment]
@dillaman Could you please rebase?

**Comment by dillaman** [comment]
@trociny rebase pushed

**Comment by trociny** [comment]
lgtm

**Pull request merged**
