### PR TITLE
mgr/cephadm: fix and improve osd draining

### PR DESCRIPTION
**Pull request by liewegas**
- when purging and osd, the osd was removed from teh osdmap *before* teh daemon was removed, resulting in the daemon not getting cleaned up.
- when purging, we should set the crush weight to 0 instead of marking the osd out (fixes https://tracker.ceph.com/issues/49339)
- clean up the log output (chattiness and formatting)

### CODE REVIEW

**Review by sebastian-philipp — APPROVED** [review]

**Comment by sebastian-philipp** [comment]
https://pulpito.ceph.com/swagner-2021-02-22_13:51:42-rados:cephadm-wip-swagner-testing-2021-02-22-1115-distro-basic-smithi/

**Comment by sebastian-philipp** [comment]
oops. this broke the upgrade test:

```
 [INF] from='mgr.14646 172.21.15.120:0/2476104201' entity='mgr.x' cmd=[{"prefix":"config-key set","key":"mgr/cephadm/osd_remove_queue","val":"[]"}]: dispatch
audit [INF] from='mgr.14646 172.21.15.120:0/2476104201' entity='mgr.x' cmd='[{"prefix":"config-key set","key":"mgr/cephadm/osd_remove_queue","val":"[]"}]': finished
audit [INF] from='mgr.14646 172.21.15.120:0/2476104201' entity='mgr.x' cmd=[{"prefix":"config-key set","key":"mgr/cephadm/osd_remove_queue","val":"[]"}]: dispatch
audit [INF] from='mgr.14646 172.21.15.120:0/2476104201' entity='mgr.x' cmd='[{"prefix":"config-key set","key":"mgr/cephadm/osd_remove_queue","val":"[]"}]': finished
audit [INF] from='mgr.14646 172.21.15.120:0/2476104201' entity='mgr.x' cmd=[{"prefix":"config-key set","key":"mgr/cephadm/osd_remove_queue","val":"[]"}]: dispatch
audit [INF] from='mgr.14646 172.21.15.120:0/2476104201' entity='mgr.x' cmd='[{"prefix":"config-key set","key":"mgr/cephadm/osd_remove_queue","val":"[]"}]': finished
audit [INF] from='mgr.14646 172.21.15.120:0/2476104201' entity='mgr.x' cmd=[{"prefix":"config-key set","key":"mgr/cephadm/osd_remove_queue","val":"[]"}]: dispatch
audit [INF] from='mgr.14646 172.21.15.120:0/2476104201' entity='mgr.x' cmd='[{"prefix":"config-key set","key":"mgr/cephadm/osd_remove_queue","val":"[]"}]': finished
audit [INF] from='mgr.14646 172.21.15.120:0/2476104201' entity='mgr.x' cmd=[{"prefix":"config-key set","key":"mgr/cephadm/osd_remove_queue","val":"[]"}]: dispatch
audit [INF] from='mgr.14646 172.21.15.120:0/2476104201' entity='mgr.x' cmd='[{"prefix":"config-key set","key":"mgr/cephadm/osd_remove_queue","val":"[]"}]': finished
audit [INF] from='mgr.14646 172.21.15.120:0/2476104201' entity='mgr.x' cmd=[{"prefix":"config-key set","key":"mgr/cephadm/osd_remove_queue","val":"[]"}]: dispatch
audit [INF] from='mgr.14646 172.21.15.120:0/2476104201' entity='mgr.x' cmd='[{"prefix":"config-key set","key":"mgr/cephadm/osd_remove_queue","val":"[]"}]': finished
audit [INF] from='mgr.14646 172.21.15.120:0/2476104201' entity='mgr.x' cmd=[{"prefix":"config-key set","key":"mgr/cephadm/osd_remove_queue","val":"[]"}]: dispatch
audit [INF] from='mgr.14646 172.21.15.120:0/2476104201' entity='mgr.x' cmd='[{"prefix":"config-key set","key":"mgr/cephadm/osd_remove_queue","val":"[]"}]': finished
audit [INF] from='mgr.14646 172.21.15.120:0/2476104201' entity='mgr.x' cmd=[{"prefix":"config-key set","key":"mgr/cephadm/osd_remove_queue","val":"[]"}]: dispatch
audit [INF] from='mgr.14646 172.21.15.120:0/2476104201' entity='mgr.x' cmd='[{"prefix":"config-key set","key":"mgr/cephadm/osd_remove_queue","val":"[]"}]': finished
audit [INF] from='mgr.14646 172.21.15.120:0/2476104201' entity='mgr.x' cmd=[{"prefix":"config-key set","key":"mgr/cephadm/osd_remove_queue","val":"[]"}]: dispatch
audit [INF] from='mgr.14646 172.21.15.120:0/2476104201' entity='mgr.x' cmd='[{"prefix":"config-key set","key":"mgr/cephadm/osd_remove_queue","val":"[]"}]': finished
audit [INF] from='mgr.14646 172.21.15.120:0/2476104201' entity='mgr.x' cmd=[{"prefix":"config-key set","key":"mgr/cephadm/osd_remove_queue","val":"[]"}]: dispatch
audit [INF] from='mgr.14646 172.21.15.120:0/2476104201' entity='mgr.x' cmd='[{"prefix":"config-key set","key":"mgr/cephadm/osd_remove_queue","val":"[]"}]': finished
audit [INF] from='mgr.14646 172.21.15.120:0/2476104201' entity='mgr.x' cmd=[{"prefix":"config-key set","key":"mgr/cephadm/osd_remove_queue","val":"[]"}]: dispatch
audit [INF] from='mgr.14646 172.21.15.120:0/2476104201' entity='mgr.x' cmd='[{"prefix":"config-key set","key":"mgr/cephadm/osd_remove_queue","val":"[]"}]': finished
audit [INF] from='mgr.14646 172.21.15.120:0/2476104201' entity='mgr.x' cmd=[{"prefix":"config-key set","key":"mgr/cephadm/osd_remove_queue","val":"[]"}]: dispatch
audit [INF] from='mgr.14646 172.21.15.120:0/2476104201' entity='mgr.x' cmd='[{"prefix":"config-key set","key":"mgr/cephadm/osd_remove_queue","val":"[]"}]': finished
audit [INF] from='mgr.14646 172.21.15.120:0/2476104201' entity='mgr.x' cmd=[{"prefix":"config-key set","key":"mgr/cephadm/osd_remove_queue","val":"[]"}]: dispatch
audit [INF] from='mgr.14646 172.21.15.120:0/2476104201' entity='mgr.x' cmd='[{"prefix":"config-key set","key":"mgr/cephadm/osd_remove_queue","val":"[]"}]': finished
audit [INF] from='mgr.14646 172.21.15.120:0/2476104201' entity='mgr.x' cmd=[{"prefix":"config-key set","key":"mgr/cephadm/osd_remove_queue","val":"[]"}]: dispatch
audit [INF] from='mgr.14646 172.21.15.120:0/2476104201' entity='mgr.x' cmd='[{"prefix":"config-key set","key":"mgr/cephadm/osd_remove_queue","val":"[]"}]': finished
audit [INF] from='mgr.14646 172.21.15.120:0/2476104201' entity='mgr.x' cmd=[{"prefix":"config-key set","key":"mgr/cephadm/osd_remove_queue","val":"[]"}]: dispatch
audit [INF] from='mgr.14646 172.21.15.120:0/2476104201' entity='mgr.x' cmd='[{"prefix":"config-key set","key":"mgr/cephadm/osd_remove_queue","val":"[]"}]': finished
```
https://pulpito.ceph.com/swagner-2021-02-22_13:54:50-rados:cephadm-wip-swagner4-testing-2021-02-22-1119-distro-basic-smithi/

**Comment by liewegas** [comment]
> 1.15.120:0/2476104201' entity='mgr.x' cmd='[{"prefix":"config-key set","key":"mgr/cephadm/osd_remove_queue","val":"[]"}]': finished
> audit [INF] from='mgr.14646 172.21.15.120:0/2476104201' entity='mgr.x' cmd=[{"prefix":"config-key set","key":"mgr/cephadm/osd_remove_queue","val":"[]"}]: dispatch
> audit [INF] from='mgr.14646 172.2

I don't think this is related to my pull request.  The process_removal_queue() method is called at the top of the serve loop and it unconditionally saves the list.

**Comment by strenuous-life** [comment]
@sebastian-philipp @liewegas Whether this pr will backport to octopus. In the issue  #49339, the backport is described as 'pacific,octopush'.

**Comment by sebastian-philipp** [comment]
do you want to do the backport? That's mainly a `git cherry-pick -x` for all the commits here

**Pull request merged**
