### PR TITLE
Makefile-env.am: set a default for CEPH_BUILD_VIRTUALENV (part 2)

### PR DESCRIPTION
**Pull request by dachary**
The new default must be taken into account by make check scripts
otherwise they fail.

Signed-off-by: Loic Dachary <loic@dachary.org>

### CODE REVIEW

**Comment by dachary** [comment]
pushed in gitbuilders under the branch wip-virtualenv-jewel

**Comment by liewegas** [comment]
failed the centos7 builds...

**Comment by dachary** [comment]
The failure is unrelated
<pre>
 RPM build errors:
Installed (but unpackaged) file(s) found:
/etc/cron.hourly/subman.pyc
/etc/cron.hourly/subman.pyo 
</pre>
I'll fix it in another pull request.

**Comment by dmick** [comment]
I guess this fixes "running the make check scripts outside of make check" (the addition of the default) as well as "running make check inside make check" (adding the extra slash)?  Either way, this all looks right to me, and sorry I didn't see it as assigned to me for five days.  Pings always welcome if it looks like I'm ignoring something

**Comment by dachary** [comment]
@dmick it was a long week-end, I would have pinged you about it today ;-)

**Pull request merged**
