### PR TITLE
luminous: build/ops: Allow multi instances of "make tests" on the same machine

### PR DESCRIPTION
**Pull request by tchaikov**
http://tracker.ceph.com/issues/38073

### CODE REVIEW

**Comment by smithfarm** [comment]
Marking DNM until master PR https://github.com/ceph/ceph/pull/26091 is merged...

**Comment by tchaikov** [comment]
retest this please

**Comment by wjwithagen** [comment]
@tchaikov 
not sure if you can access this, but:
http://cephdev.digiware.nl:8180/jenkins/job/ceph-luminous/164/console

**Comment by wjwithagen** [comment]
@tchaikov 
Rebooting the Jenkins VM and reverting this PR gets testing oke again. But then still in the sequential second run for failed parallel tests. Going to reboot and test it with the PR again

**Comment by tchaikov** [comment]
@wjwithagen thanks for testing. i think the test failure of `smoke.sh` should be fixed by the latest change. we were using `ceph-disk` back in luminous. and `ceph-disk` is installed into `/tmp` before this change, so in the latest change `ceph-helper.sh` is updated accordingly.

**Comment by wjwithagen** [comment]
@tchaikov 
Right, with patch same problem again.
But I think I have the clue in the report generated bij `smoke.sh`, now if only why are we in `HEALTH_ERR` and does `smoke.sh` care?
```
report 3661488570
{
    "cluster_fingerprint": "5219997e-2bf5-41df-836a-e915e833a95a",
    "version": "Development",
    "commit": "no_version",
    "timestamp": "2019-01-31 12:33:26.540841",
    "tag": "",
    "health": {
        "checks": {
            "OSD_OUT_OF_ORDER_FULL": {
                "severity": "HEALTH_ERR",
                "summary": {
                    "message": "full ratio(s) out of order"
                },
                "detail": [
                    {
                        "message": "osd_failsafe_full_ratio (0.97) < full_ratio (0.99), increased"
                    }
                ]
            },
            "PG_AVAILABILITY": {
                "severity": "HEALTH_WARN",
                "summary": {
                    "message": "Reduced data availability: 4 pgs inactive"
                },
                "detail": [
                    {
                        "message": "pg 1.0 is stuck inactive for 357.577023, current state unknown, last acting []"
                    },
                    {
                        "message": "pg 1.1 is stuck inactive for 357.577023, current state unknown, last acting []"
                    },
                    {
                        "message": "pg 1.2 is stuck inactive for 357.577023, current state unknown, last acting []"
                    },
                    {
                        "message": "pg 1.3 is stuck inactive for 357.577023, current state unknown, last acting []"
                    }
                ]
            }
        },
        "status": "HEALTH_ERR",
        "summary": [
            {
                "severity": "HEALTH_WARN",
                "summary": "'ceph health' JSON format has changed in luminous. If you see this your monitoring system is scraping the wrong fields. Disable this with 'mon health preluminous compat warning = false'"
            }
        ],
        "overall_status": "HEALTH_ERR",
        "detail": [
            "'ceph health' JSON format has changed in luminous. If you see this your monitoring system is scraping the wrong fields. Disable this with 'mon health preluminous compat warning = false'"
        ]
    },
```

**Comment by wjwithagen** [comment]
@tchaikov 
`ceph-disk` does not exist when the virtualenv is moved. So I guess that it is not in the `$PATH`
```
/home/jenkins/workspace/ceph-luminous/src/test/smoke.sh:30: TEST_minimal:  run_osd td/smoke 0
/home/jenkins/workspace/ceph-luminous/qa/standalone/ceph-helpers.sh:603: run_osd:  local dir=td/smoke
/home/jenkins/workspace/ceph-luminous/qa/standalone/ceph-helpers.sh:604: run_osd:  shift
/home/jenkins/workspace/ceph-luminous/qa/standalone/ceph-helpers.sh:605: run_osd:  local id=0
/home/jenkins/workspace/ceph-luminous/qa/standalone/ceph-helpers.sh:606: run_osd:  shift
/home/jenkins/workspace/ceph-luminous/qa/standalone/ceph-helpers.sh:607: run_osd:  local osd_data=td/smoke/0
/home/jenkins/workspace/ceph-luminous/qa/standalone/ceph-helpers.sh:609: run_osd:  local ceph_disk_args
/home/jenkins/workspace/ceph-luminous/qa/standalone/ceph-helpers.sh:610: run_osd:  ceph_disk_args+=' --statedir=td/smoke'
/home/jenkins/workspace/ceph-luminous/qa/standalone/ceph-helpers.sh:611: run_osd:  ceph_disk_args+=' --sysconfdir=td/smoke'
/home/jenkins/workspace/ceph-luminous/qa/standalone/ceph-helpers.sh:612: run_osd:  ceph_disk_args+=' --prepend-to-path='
/home/jenkins/workspace/ceph-luminous/qa/standalone/ceph-helpers.sh:614: run_osd:  mkdir -p td/smoke/0
/home/jenkins/workspace/ceph-luminous/qa/standalone/ceph-helpers.sh:615: run_osd:  ceph-disk --statedir=td/smoke --sysconfdir=td/smoke --prepend-to-path= prepare --filestore td/smoke/0
/home/jenkins/workspace/ceph-luminous/qa/standalone/ceph-helpers.sh: line 615: ceph-disk: command not found
/home/jenkins/workspace/ceph-luminous/qa/standalone/ceph-helpers.sh:616: run_osd:  return 1
/home/jenkins/workspace/ceph-luminous/src/test/smoke.sh:31: TEST_minimal:  run_osd td/smoke 1
```

**Comment by wjwithagen** [comment]
@tchaikov 
The other worrying part is that the script still continues although thre are serious errors...

**Comment by wjwithagen** [comment]
@tchaikov 
Waiting for a slot to run `luminous` test in.

**Comment by wjwithagen** [comment]
@tchaikov 
Right, now it passed

**Comment by tchaikov** [comment]
@theanalyst can we unlock luminous? as 12.2.11 has been released?

**Comment by theanalyst** [comment]
@tchaikov unlocked, sorry was travelling this weekend and forgot to do it soon after release.

**Pull request merged**
