### PR TITLE
qa/suites/rados/perf/ceph.yaml: remove rgw

### PR DESCRIPTION
**Pull request by neha-ojha**
This is no longer required because we removed cosbench workloads in
fd350fd0150a2d4072f055658c20314a435a19ba. This is also required to prevent
failures like the following or any other changes that break the rgw task:

```
2021-08-06T20:13:25.812 INFO:teuthology.orchestra.run.smithi060.stderr:curl: (7) Failed to connect to smithi060.front.sepia.ceph.com port 80: Connection refused
2021-08-06T20:15:33.813 ERROR:teuthology.contextutil:Saw exception from nested tasks
Traceback (most recent call last):
  File "/home/teuthworker/src/git.ceph.com_git_teuthology_04c2febe7099917d97a71271f17abb5710030132/teuthology/contextutil.py", line 31, in nested
    vars.append(enter())
  File "/usr/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/home/teuthworker/src/github.com_ceph_ceph-c_3c0f8c8164075af7aac4d1f2805d3f4580709461/qa/tasks/rgw.py", line 191, in start_rgw
    wait_for_radosgw(url, remote)
  File "/home/teuthworker/src/github.com_ceph_ceph-c_3c0f8c8164075af7aac4d1f2805d3f4580709461/qa/tasks/util/rgw.py", line 94, in wait_for_radosgw
    assert exit_status == 0
AssertionError
```

Signed-off-by: Neha Ojha <nojha@redhat.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by neha-ojha** [comment]
Before: https://pulpito.ceph.com/yuriw-2021-08-06_16:31:19-rados-wip-yuri-master-8.6.21-distro-basic-smithi/ (all the rados/perf tests failed)

After: https://pulpito.ceph.com/nojha-2021-08-09_14:40:15-rados:perf-wip-yuri-master-8.6.21-distro-basic-smithi/

**Comment by neha-ojha** [comment]
jenkins test make check

**Review by sseshasa — COMMENTED** [review]
Considering that  qa/suites/perf-basic/workloads/cosbench_64K_write.yaml too was removed in fd350fd0150a2d4072f055658c20314a435a19ba, shouldn't a similar change be made in qa/suites/perf-basic/ceph.yaml?

**Review by sseshasa — APPROVED** [review]
Apart from the comment I made earlier, the changes look good.

**Comment by neha-ojha** [comment]
> Considering that qa/suites/perf-basic/workloads/cosbench_64K_write.yaml too was removed in [fd350fd](https://github.com/ceph/ceph/commit/fd350fd0150a2d4072f055658c20314a435a19ba), shouldn't a similar change be made in qa/suites/perf-basic/ceph.yaml?

good point, added another commit to address this

**Comment by neha-ojha** [comment]
> Before: https://pulpito.ceph.com/yuriw-2021-08-06_16:31:19-rados-wip-yuri-master-8.6.21-distro-basic-smithi/ (all the rados/perf tests failed)
> 
> After: https://pulpito.ceph.com/nojha-2021-08-09_14:40:15-rados:perf-wip-yuri-master-8.6.21-distro-basic-smithi/

perf-basic tests: https://pulpito.ceph.com/nojha-2021-08-09_17:35:00-perf-basic-wip-yuri-master-8.6.21-distro-basic-smithi/

**Pull request merged**
