### PR TITLE
nautilus: mds: "apply configuration changes through MDSRank" and "recall caps from quiescent sessions" and "drive cap recall while dropping cache"

### PR DESCRIPTION
**Pull request by smithfarm**
backport trackers:

* https://tracker.ceph.com/issues/41865
* https://tracker.ceph.com/issues/41899
* https://tracker.ceph.com/issues/42339

---

backport of:

* https://github.com/ceph/ceph/pull/27199 (5 commits)
* https://github.com/ceph/ceph/pull/28702 (13 commits)
* https://github.com/ceph/ceph/pull/28951 (2 commits)
* https://github.com/ceph/ceph/pull/30389 (1 commit)

GRAND TOTAL: 21 commits

parent trackers:

* https://tracker.ceph.com/issues/22446
* https://tracker.ceph.com/issues/40694
* https://tracker.ceph.com/issues/41835

### CODE REVIEW

**Comment by smithfarm** [comment]
@batrick I think I got both related fixes in a single PR now.

**Comment by batrick** [comment]
@smithfarm looks like this is missing 12 commits from #28702

**Comment by smithfarm** [comment]
```
/home/jenkins-build/build/workspace/ceph-pull-requests/src/mds/MDSRank.cc: In member function 'void C_Drop_Cache::recall_client_state()':
/home/jenkins-build/build/workspace/ceph-pull-requests/src/mds/MDSRank.cc:331:67: error: 'TRIM' is not a member of 'Server::RecallFlags'
     auto flags = Server::RecallFlags::STEADY|Server::RecallFlags::TRIM;
                                                                   ^~~~
src/mds/CMakeFiles/mds.dir/build.make:110: recipe for target 'src/mds/CMakeFiles/mds.dir/MDSRank.cc.o' failed
make[3]: *** [src/mds/CMakeFiles/mds.dir/MDSRank.cc.o] Error 1
```

**Comment by smithfarm** [comment]
@batrick Hm, yeah. Cherry-picked all the commits, plus some others to enable everything to go in without conflicts. Updated the PR description. Hope you like it now :-)

**Comment by batrick** [comment]
> @batrick Hm, yeah. Cherry-picked all the commits, plus some others to enable everything to go in without conflicts. Updated the PR description. Hope you like it now :-)

Okay with me. Thanks @smithfarm

**Comment by yuriw** [comment]
@smithfarm needs rebease

--- pr 30761 --- pulling https://github.com/smithfarm/ceph.git branch wip-41899-nautilus
remote: Enumerating objects: 118, done.
remote: Counting objects: 100% (118/118), done.
remote: Total 139 (delta 118), reused 118 (delta 118), pack-reused 21
Receiving objects: 100% (139/139), 19.79 KiB | 6.60 MiB/s, done.
Resolving deltas: 100% (118/118), completed with 37 local objects.
From https://github.com/smithfarm/ceph
 * branch                  wip-41899-nautilus -> FETCH_HEAD
Auto-merging src/mds/locks.c
Auto-merging src/mds/MDSRank.h
Auto-merging src/mds/MDSRank.cc
CONFLICT (content): Merge conflict in src/mds/MDSRank.cc
Auto-merging src/mds/MDSDaemon.cc
Auto-merging src/include/rados.h
Auto-merging src/common/options.cc
Auto-merging src/client/Client.cc
Automatic merge failed; fix conflicts and then commit the result.
Traceback (most recent call last):
  File "/home/yuriw/wip_master/src/script/build-integration-branch", line 67, in <module>
    assert not r
AssertionError

**Comment by yuriw** [comment]
[wip-yuri-testing-2020-01-06-2017-nautilus](https://trello.com/c/v6sgaU6D/793-wip-yuri-testing-2020-01-06-2017-nautilus)

**Pull request merged**
