### PR TITLE
rgw/rgw_resolve: fallback to res_query when res_nquery not implemented

### PR DESCRIPTION
**Pull request by dx9**
The only thing I like about this is it's a quick solution.

Don't hate the player hate the game.

### CODE REVIEW

**Comment by dx9** [comment]
hey @yehudasa, thanks for looking at this! My understanding is the musl libc implementation is stateless.

**Comment by yehudasa** [comment]
@dx9 we should handle the general case, not just a specific implementation.

**Comment by dx9** [comment]
@yehudasa Couldn't the general case be if res_nquery is defined use it otherwise assume res_query is safe. This approach is appealing because figuring out when locking is required is not super obvious and the effect of locking may not be ideal. Would putting a lock around the network hit(s) be an issue? 

Looking at this again I'm missing a res_init(), which is a noop in musl libc.

**Comment by yehudasa** [comment]
@dx9 the general case for res_query use is to guard it with a lock. Having a lock there is suboptimal, but since the api is considered not thread safe (see: http://man7.org/linux/man-pages/man3/resolver.3.html), that's what we should be doing. You can add a special handling for musl libc to not use a lock. In most we'll just end up using res_nquery, so there's no issue there.

**Comment by dx9** [comment]
@yehudasa sounds good. I'll add a flag for thread safe implementations and default to locking if it is not specified.

**Comment by liewegas** [comment]
@yehudasa ping

**Pull request merged**
