### PR TITLE
jewel: journal: do not prematurely flag object recorder as closed

### PR DESCRIPTION
**Pull request by dillaman**
http://tracker.ceph.com/issues/17616

### CODE REVIEW

**Comment by dachary** [comment]
jenkins test this please (cephtool failure)

**Comment by dachary** [comment]
@dillaman did you include this in a rbd suite run by any chance ? Or are you confident it can be merged as it is ?

**Comment by dillaman** [comment]
@dachary I don't think it has been included in a run so it should be before merged -- even though I am confident.

**Comment by dachary** [comment]
running in gitbuilders as wip-pr-11634

**Comment by dachary** [comment]
<pre>
teuthology-suite --priority 101 --suite rbd  --subset $(expr $RANDOM % 5)/5 --suite-branch jewel --email loic@dachary.org --ceph wip-pr-11634 --machine-type smithi
</pre>

* **running** http://pulpito.ceph.com/loic-2016-10-27_09:17:10-rbd-wip-pr-11634---basic-smithi/

**Comment by dillaman** [comment]
@dachary Results look fine -- rbd-nbd fsx tests will timeout at 12 hrs due to missing fix.

**Pull request merged**
