### PR TITLE
qa/workunits/rbd: fix permission issue when removing mirror peer

### PR DESCRIPTION
**Pull request by dillaman**
Fixes: https://tracker.ceph.com/issues/48032
Signed-off-by: Jason Dillaman <dillaman@redhat.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Review by trociny — APPROVED** [review]
LGTM

**Comment by trociny** [comment]
jenkins test make check

**Comment by trociny** [comment]
@dillaman just wondering, what was the purpose in `remove_peer_config_key` from api/Mirror.cc to ignore `-EPERM` [1]? In this case as I understand `-EACCES` was returned, so it was not for cases like this?

[1] https://github.com/ceph/ceph/blob/master/src/librbd/api/Mirror.cc#L112

**Comment by dillaman** [comment]
> @dillaman just wondering, what was the purpose in `remove_peer_config_key` from api/Mirror.cc to ignore `-EPERM` [1]? In this case as I understand `-EACCES` was returned, so it was not for cases like this?

I can't remember, it might have just been an oversight -- but I don't think we would want to silently ignore failures to clean up the metadata if it exists.

**Pull request merged**
