### PR TITLE
qa/suites/rados: minor fixes

### PR DESCRIPTION
**Pull request by neha-ojha**
Fixes the following failures:

- http://pulpito.ceph.com/nojha-2018-05-23_15:55:12-rados-wip-double-reservation2-2018-05-22-distro-basic-smithi/2578414/

- http://pulpito.ceph.com/nojha-2018-05-23_15:55:12-rados-wip-double-reservation2-2018-05-22-distro-basic-smithi/2578362/

Signed-off-by: Neha Ojha <nojha@redhat.com>

### CODE REVIEW

**Comment by dzafman** [comment]
@neha-ojha Recently a test run job with cephtool passed without (SMALLER_PGP_NUM).  Did you see this?

See http://pulpito.ceph.com/dzafman-2018-05-22_18:09:50-rados-wip-zafman-test-fixes-distro-basic-smithi/2570596

**Comment by dzafman** [comment]
@neha-ojha Oh, I see your run.  Strange that I didn't have that issue before.

**Comment by neha-ojha** [comment]
@dzafman I hit this issue a couple of times in my runs.

**Comment by neha-ojha** [comment]
Tests running here: http://pulpito.ceph.com/nojha-2018-05-24_18:21:37-rados-master-distro-basic-smithi/

**Comment by neha-ojha** [comment]
1 job failed, and the failure looks unrelated:
http://pulpito.ceph.com/nojha-2018-05-24_18:21:37-rados-master-distro-basic-smithi/2581044/

This should be ready to merge.

**Pull request merged**
