### PR TITLE
msg/async: avoid lossy connection sending ack message

### PR DESCRIPTION
**Pull request by yuyuyu101**
Signed-off-by: Haomai Wang <haomai@xsky.com>

### CODE REVIEW

**Comment by yuyuyu101** [comment]
@liewegas sorry, we must rebuild testing branch since previous codes:
          if (policy.lossy) {
             ack_left.inc();
             need_dispatch_writer = true;
           }

It's totally wrong. I updated this commit!

**Comment by yuriw** [comment]
test this plese

**Comment by tchaikov** [comment]
@yuyuyu101 could you rebase against the latest master and try again, the failure was fixed in fec59e80ef2c1330296d748e2fee124ca652d4b2

**Comment by yuyuyu101** [comment]
hmm, from the log I don't think it's related to this pr... maybe I need to figure out when this test failed

**Comment by tchaikov** [comment]
after reverted this change, the test passes. maybe this change reveals another issue?

**Comment by yuyuyu101** [comment]
I can't reproduce this error locally. Could you run it again ?

**Comment by yuriw** [comment]
Trying to rebuild and test again

**Comment by yuriw** [comment]
http://pulpito.ceph.com/yuriw-2017-03-10_01:14:50-rados-wip-yuri-testing_2017_3_11-distro-basic-smithi/

http://pulpito.ceph.com/yuriw-2017-03-10_16:32:02-rados-wip-yuri-testing_2017_3_11---basic-smithi/

**Comment by liewegas** [comment]
@tchaikov ?

**Comment by tchaikov** [comment]
ahh, we were testing the buggy commit 
```diff
commit 854c3713651a036342865a4f0c87e88f5cb75d05
Author: Haomai Wang <haomai@xsky.com>
Date:   Wed Mar 1 00:16:55 2017 +0800

    msg/async: avoid lossy connection sending ack message

    Signed-off-by: Haomai Wang <haomai@xsky.com>

diff --git a/src/msg/async/AsyncConnection.cc b/src/msg/async/AsyncConnection.cc
index 0dc74d3..c8db137 100644
--- a/src/msg/async/AsyncConnection.cc
+++ b/src/msg/async/AsyncConnection.cc
@@ -768,8 +768,10 @@ void AsyncConnection::process()
                                     << message->get_seq() << " " << message
                                    << " " << *message << dendl;

-          ack_left.inc();
-          need_dispatch_writer = true;
+          if (policy.lossy) {
+            ack_left.inc();
+            need_dispatch_writer = true;
+          }
           state = STATE_OPEN;

           logger->inc(l_msgr_recv_messages);
```

with the updated change, the test passes.

**Pull request merged**
