### PR TITLE
osd/OSD.cc: shutdown after flipping certain times

### PR DESCRIPTION
**Pull request by xiaoxichen**
OSD stauts may flipping due to some hardware/network issue.
Although we tried our best to self healthing but still in some case
the OSD is still flipping and require admin to operate.

This patch try another approach that shutdown the OSD after certain
times of reboot(flipping), thus speed up the convergence of cluster.

Signed-off-by: Xiaoxi Chen <xiaoxi.chen@intel.com>

### CODE REVIEW

**Comment by xiaoxichen** [comment]
reopen #6615 as automatically shutdown by branch deleted

**Comment by liewegas** [comment]
A few cosmetic issue, otherwise this looks good!  Thanks-

**Comment by xiaoxichen** [comment]
@liewegas ,done with the cosmetic issue:)

**Comment by liewegas** [comment]
Sorry, one last request: can you construct a simple test for this?  One that runs during 'make check' is probably simplest (see test/*/*.sh).  I would start an osd, mark it down explicitly 6 times (ceph osd down N), and verify that it comes back up 5 times and then doesn't on the 6th time.  Thanks!

**Comment by xiaoxichen** [comment]
@liewegas ,sorry for the late reply, test added:)

**Pull request merged**
