### PR TITLE
mimic: rgw: resolve bugs and clean up garbage collection code

### PR DESCRIPTION
**Pull request by cbodley**
backport tracker https://tracker.ceph.com/issues/38713

### CODE REVIEW

**Comment by cbodley** [comment]
jenkins test make check

**Comment by ivancich** [comment]
@cbodley thanks for backporting this!

**Comment by yuriw** [comment]
[wip-yuri-testing-2019-05-02-2259-mimic](https://trello.com/c/j1rN3QVx/604-wip-yuri-testing-2019-05-02-2259-mimic)

**Comment by smithfarm** [comment]
Apparently, this backport also includes https://github.com/ceph/ceph/pull/26545 so I'm adding http://tracker.ceph.com/issues/38753

**Pull request merged**
