### PR TITLE
doc/start: remove journal info from hardware recs

### PR DESCRIPTION
**Pull request by zdover23**
This PR removes mentions of journaling from the hardware
recommendations.

Journaling was a FileStore-related practice. BlueStore is
the default backend for Ceph OSDs and has been since
Luminous. The documentation should reflect that.

Signed-off-by: Zac Dover <zac.dover@gmail.com>

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [x] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [x] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by zdover23** [comment]
jenkins test docs

**Comment by djgalloway** [comment]
jenkins test docs

**Comment by zdover23** [comment]
jenkins test docs

**Comment by zdover23** [comment]
jenkins retest this

**Comment by zdover23** [comment]
jenkins render docs

**Comment by ljflores** [comment]
This `render docs` failure appears to be happening across PRs:
```
python setup.py egg_info
```

**Comment by zdover23** [comment]
> This `render docs` failure appears to be happening across PRs:
> 
> ```
> Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-6zl6um2e-build/
> ```

I fixed this by rebasing this commit on ed2ad24a4ba3ad3f8103926bfea2466b9eb61222, per dgalloway's instructions on irc.

The docs-related tests work after making that rebase. However, the arm64 make check still takes hours and may never complete.

**Review by djgalloway — APPROVED** [review]

**Comment by djgalloway** [comment]
> The docs-related tests work after making that rebase. However, the arm64 make check still takes hours and may never complete.

Sorry about that.  [Let's save you some time](https://github.com/ceph/ceph-build/pull/1939).

**Review by dvanders — APPROVED** [review]
I think this is fine.

More generally we need to review this entire doc, because it reads like it was written a decade ago, and misses pertinent recommendations related to BlueStore (hdd/mixed/ssd/nvme, in particular)

**Comment by zdover23** [comment]
> I think this is fine.
> 
> More generally we need to review this entire doc, because it reads like it was written a decade ago, and misses pertinent recommendations related to BlueStore (hdd/mixed/ssd/nvme, in particular)

I agree. The rewriting of the Hardware Recommendations page is on my list of things to do in 2022.

Unless I am struck by meteor or I undergo a sudden health-related collapse, we will discuss this in the future.

**Pull request merged**
