### PR TITLE
Squid: mgr/dashboard: unable to edit pipe config for bucket level policy of bucket

### PR DESCRIPTION
**Pull request by nmunet**
backport tracker:  https://tracker.ceph.com/issues/68520

backport of: #60147

parent tracker: https://tracker.ceph.com/issues/68387

https://github.com/user-attachments/assets/cb11f29e-cdae-4b9c-aacf-02c1b5441e0c

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [x] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [x] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Comment by nmunet** [comment]
jenkins test dashboard

**Comment by nmunet** [comment]
jenkins test dashboard cephadm

**Comment by nmunet** [comment]
jenkins test dashboard cephadm

**Review by nizamial09 — APPROVED** [review]

**Comment by nmunet** [comment]
cephadm tests failure seems unrelated to this PR:
```
[should stop a daemon.Services page should stop a daemon](https://jenkins.ceph.com/job/ceph-dashboard-cephadm-e2e/12857/testReport/junit/(root)/should%20stop%20a%20daemon/Services_page_should_stop_a_daemon/)
[should create a nfs-export with RGW backend.nfsExport page Create, edit and delete should create a nfs-export with RGW backend](https://jenkins.ceph.com/job/ceph-dashboard-cephadm-e2e/12857/testReport/junit/(root)/should%20create%20a%20nfs-export%20with%20RGW%20backend/nfsExport_page_Create__edit_and_delete_should_create_a_nfs_export_with_RGW_backend/)
[should show Clients.nfsExport page Create, edit and delete should show Clients](https://jenkins.ceph.com/job/ceph-dashboard-cephadm-e2e/12857/testReport/junit/(root)/should%20show%20Clients/nfsExport_page_Create__edit_and_delete_should_show_Clients/)
[should edit an export.nfsExport page Create, edit and delete should edit an export](https://jenkins.ceph.com/job/ceph-dashboard-cephadm-e2e/12857/testReport/junit/(root)/should%20edit%20an%20export/nfsExport_page_Create__edit_and_delete_should_edit_an_export/)
[should delete exports and bucket.nfsExport page Create, edit and delete should delete exports and bucket](https://jenkins.ceph.com/job/ceph-dashboard-cephadm-e2e/12857/testReport/junit/(root)/should%20delete%20exports%20and%20bucket/nfsExport_page_Create__edit_and_delete_should_delete_exports_and_bucket/)
[should check if rgw daemon is running on all hosts.Host Page should check if rgw daemon is running on all hosts](https://jenkins.ceph.com/job/ceph-dashboard-cephadm-e2e/12857/testReport/junit/(root)/should%20check%20if%20rgw%20daemon%20is%20running%20on%20all%20hosts/Host_Page_should_check_if_rgw_daemon_is_running_on_all_hosts/)
[should force maintenance and exit.Host Page should force maintenance and exit](https://jenkins.ceph.com/job/ceph-dashboard-cephadm-e2e/12857/testReport/junit/(root)/should%20force%20maintenance%20and%20exit/Host_Page_should_force_maintenance_and_exit/)
[should check if mon daemon is running on all hosts.when cluster creation is completed Hosts page should check if mon daemon is running on all hosts](https://jenkins.ceph.com/job/ceph-dashboard-cephadm-e2e/12857/testReport/junit/(root)/should%20check%20if%20mon%20daemon%20is%20running%20on%20all%20hosts/when_cluster_creation_is_completed_Hosts_page_should_check_if_mon_daemon_is_running_on_all_hosts/)
``` 

Dashboard tests failure seems unrelated to this PR:
```
[should create image.Images page create, edit & delete image test should create image](https://jenkins.ceph.com/job/ceph-dashboard-pull-requests/16621/testReport/junit/(root)/should%20create%20image/Images_page_create__edit___delete_image_test_should_create_image/)
[should edit image.Images page create, edit & delete image test should edit image](https://jenkins.ceph.com/job/ceph-dashboard-pull-requests/16621/testReport/junit/(root)/should%20edit%20image/Images_page_create__edit___delete_image_test_should_edit_image/)
[should delete image.Images page create, edit & delete image test should delete image](https://jenkins.ceph.com/job/ceph-dashboard-pull-requests/16621/testReport/junit/(root)/should%20delete%20image/Images_page_create__edit___delete_image_test_should_delete_image/)
["before all" hook for "should move the image to the trash".Images page move to trash, restore and purge image tests "before all" hook for "should move the image to the trash"](https://jenkins.ceph.com/job/ceph-dashboard-pull-requests/16621/testReport/junit/(root)/%22before%20all%22%20hook%20for%20%22should%20move%20the%20image%20to%20the%20trash%22/Images_page_move_to_trash__restore_and_purge_image_tests__before_all__hook_for__should_move_the_image_to_the_trash_/)
["after all" hook for "should move the image to the trash".Images page move to trash, restore and purge image tests "after all" hook for "should move the image to the trash"](https://jenkins.ceph.com/job/ceph-dashboard-pull-requests/16621/testReport/junit/(root)/%22after%20all%22%20hook%20for%20%22should%20move%20the%20image%20to%20the%20trash%22/Images_page_move_to_trash__restore_and_purge_image_tests__after_all__hook_for__should_move_the_image_to_the_trash_/)
[should create pool and check audit logs reacted.Logs page audit logs respond to pool creation and deletion test should create pool and check audit logs reacted](https://jenkins.ceph.com/job/ceph-dashboard-pull-requests/16621/testReport/junit/(root)/should%20create%20pool%20and%20check%20audit%20logs%20reacted/Logs_page_audit_logs_respond_to_pool_creation_and_deletion_test_should_create_pool_and_check_audit_logs_reacted/)
[should delete pool and check audit logs reacted.Logs page audit logs respond to pool creation and deletion test should delete pool and check audit logs reacted](https://jenkins.ceph.com/job/ceph-dashboard-pull-requests/16621/testReport/junit/(root)/should%20delete%20pool%20and%20check%20audit%20logs%20reacted/Logs_page_audit_logs_respond_to_pool_creation_and_deletion_test_should_delete_pool_and_check_audit_logs_reacted/)
["before all" hook for "should open notification sidebar".Notification page "before all" hook for "should open notification sidebar"](https://jenkins.ceph.com/job/ceph-dashboard-pull-requests/16621/testReport/junit/(root)/%22before%20all%22%20hook%20for%20%22should%20open%20notification%20sidebar%22/Notification_page__before_all__hook_for__should_open_notification_sidebar_/)
["after all" hook for "should open notification sidebar".Notification page "after all" hook for "should open notification sidebar"](https://jenkins.ceph.com/job/ceph-dashboard-pull-requests/16621/testReport/junit/(root)/%22after%20all%22%20hook%20for%20%22should%20open%20notification%20sidebar%22/Notification_page__after_all__hook_for__should_open_notification_sidebar_/)
```

**Pull request merged**
