### PR TITLE
[DNM] rpm: drop support for unsupported distros

### PR DESCRIPTION
**Pull request by smithfarm**
Fixes: http://tracker.ceph.com/issues/13445
Fixes: http://tracker.ceph.com/issues/15486

### CODE REVIEW

**Comment by smithfarm** [comment]
Note: this breaks `ceph-common` for older distros.

**Comment by smithfarm** [comment]
Passes gitbuilder.

**Comment by liewegas** [comment]
We can do this post-infernalis.

Also, although we aren't building ceph.com packages on old distros, in theory you could if you go and install the right compiler toolchain yourself.  Removing this cruft is nice but it means any backporter will also have to futz around with the spec file too...  we may want to wait a bit longer?

**Comment by ktdreyer** [comment]
I'm ok with merging this before infernalis, or after. Either way works for me

**Comment by smithfarm** [comment]
@liewegas has a point. Though upstream will not be testing infernalis against older distros, somebody out there might be interested in doing so on their own, and this PR would make life difficult for them.

So, the question becomes: retarget against master and merge now, or close the PR and reopen it post-jewel?

**Comment by liewegas** [comment]
As much as I would love to remove this cruft, I think we should carry it for a bit longer.

Let's see how the no-el6 support pans out for infernalis. If nobody cares, we could merge this before jewel.  If people end up doing these builds downstream we can carry this stuff a bit longer.

**Comment by smithfarm** [comment]
@ktdreyer This will need rebased, but I think it does some of what you are asking for in http://tracker.ceph.com/issues/15486

**Comment by ktdreyer** [comment]
Great point @smithfarm , this would make a good starting point.

**Pull request closed without merging**
