### PR TITLE
rgw: handle old clients with transfer-encoding: chunked.

### PR DESCRIPTION
**Pull request by mkogan1**
s3 clients *should* provide an x-amz-decoded-content-length field when they use transport-encoding: chunked.  Some clients do not. With swift we already allow chunked uploads that do not specify the
content length in advance.   This commit adds similar support
for s3.  Known client affected by this: boto2.

Fixes: https://tracker.ceph.com/issues/45789
Resolves: rhbz#2152801

Signed-off-by: Marcus Watts <mwatts@redhat.com>

= = = = =   8<   = = = = =

Additional details from the BZ:
Description of problem:

- Cu is getting error 411, missing content length error for  PutObject operations for clients accessing via aws-sdk
Cu confirmed following implementation details:

```
library is '@aws-sdk/client-s3' with the version 3.54.0
they use it in javascript (node)
specific request type is PutObject with a stream, the content I can't give but it happens for any file from their testing, but please try various of object sizes.
The exact error is: "MissigContentLength: UnknownError"
```

Cu script:

```
import fs from 'fs';
import { Readable } from 'stream';

import { S3, PutObjectCommandInput, PutObjectCommandOutput } from '@aws-sdk/client-s3';
import { SdkStream } from '@aws-sdk/types';

const file = fs.createReadStream('/file/path')


const s3client = new S3({
	region: 's3Region',
	tls: true,
	forcePathStyle: true
	credentials: {
		accessKeyId: 'access key',
		secretAccessKey: 'secret key'
	},
	endpoint: 'endpoint'
});


const params: PutObjectCommandInput = {
	Bucket: bucket,
	Key: key,
	Body: file
};

const upload: PutObjectCommandOutput = await s3client.putObject(params, {});

return upload;
```

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [x] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by cbodley** [comment]
if there's a reproducer for this, can we please turn it into a s3test case? if boto2 is required, we still have some boto2 tests under s3tests/

**Comment by mkogan1** [comment]
> if there's a reproducer for this, can we please turn it into a s3test case? if boto2 is required, we still have some boto2 tests under s3tests/

@cbodley added s3test PR: https://github.com/ceph/s3-tests/pull/501

**Comment by mkogan1** [comment]
jenkins test make check

**Review by cbodley — APPROVED** [review]

**Comment by cbodley** [comment]
we'll need to make sure this gets run against a suite-branch that modifies `qa/rgw/s3tests-branch.yaml` to point at your `mkogan1:wip-chunked-trans-enc` s3test branch

**Comment by mkogan1** [comment]
jenkins test api

**Comment by mkogan1** [comment]
@ivancich sorry, currently it will fail _wip-eric-testing-1_
https://github.com/ceph/java_s3tests/blob/81319fea9d8be9b8083723dd74ee59ff94f0351e/src/test/java/ObjectTest.java#L472
because there are test changes, working on testing per instructions in https://github.com/ceph/ceph/pull/50235#issuecomment-1458275023 above

**Review by mattbenjamin — COMMENTED** [review]
marcus says sounds plausible, he will review

**Comment by mkogan1** [comment]
added java_s3test PR: https://github.com/ceph/java_s3tests/pull/13

**Comment by ivancich** [comment]
In my QA branch all my rgw/verify jobs fail due to this:

```
2023-03-20T03:40:41.347 INFO:teuthology.orchestra.run.smithi033.stdout:suite > Object tests > ObjectTest.testObjectCreateBadContentlengthNegative FAILED
2023-03-20T03:40:41.348 INFO:teuthology.orchestra.run.smithi033.stdout:    java.lang.AssertionError at ObjectTest.java:472
```

Of the 4 PRs on the branch, this seems the most likely to involve this. I'm verifying.

**Comment by cbodley** [comment]
thanks @ivancich. this was expected, yeah:

> @ivancich sorry, currently it will fail _wip-eric-testing-1_ https://github.com/ceph/java_s3tests/blob/81319fea9d8be9b8083723dd74ee59ff94f0351e/src/test/java/ObjectTest.java#L472 because there are test changes, working on testing per instructions in [#50235 (comment)](https://github.com/ceph/ceph/pull/50235#issuecomment-1458275023) above

**Comment by ivancich** [comment]
> thanks @ivancich. this was expected, yeah:
> 
> > @ivancich sorry, currently it will fail _wip-eric-testing-1_ https://github.com/ceph/java_s3tests/blob/81319fea9d8be9b8083723dd74ee59ff94f0351e/src/test/java/ObjectTest.java#L472 because there are test changes, working on testing per instructions in [#50235 (comment)](https://github.com/ceph/ceph/pull/50235#issuecomment-1458275023) above

Sorry, I missed that comment directed at me above. How would you like me to handle QA then -- pull this PR out of the QA run or count this as a pass?

**Comment by mkogan1** [comment]
> > thanks @ivancich. this was expected, yeah:
> > > @ivancich sorry, currently it will fail _wip-eric-testing-1_ https://github.com/ceph/java_s3tests/blob/81319fea9d8be9b8083723dd74ee59ff94f0351e/src/test/java/ObjectTest.java#L472 because there are test changes, working on testing per instructions in [#50235 (comment)](https://github.com/ceph/ceph/pull/50235#issuecomment-1458275023) above
> 
> Sorry, I missed that comment directed at me above. How would you like me to handle QA then -- pull this PR out of the QA run or count this as a pass?

following this https://github.com/ceph/java_s3tests/pull/14 merging it should be OK to test again and it should pass now

**Comment by mkogan1** [comment]
@cbodley 
this PR passed teuthology `rgw:verify` suite & `--limit 10` and a suite-repo&branch 
with the explicit additional s3test for this scenario from: https://github.com/ceph/s3-tests/pull/501

https://pulpito.ceph.com/mkogan-2023-03-21_13:51:47-rgw:verify-wip-chuncked-put-i04-distro-default-smithi/ -->
http://qa-proxy.ceph.com/teuthology/mkogan-2023-03-21_13:51:47-rgw:verify-wip-chuncked-put-i04-distro-default-smithi/7215297/teuthology.log : `test_object_write_with_chunked_transfer_encoding PASSED [ 36%]`
```
2023-03-21T14:25:08.794 INFO:teuthology.orchestra.run.smithi149.stdout:s3tests_boto3/functional/test_s3.py::test_object_write_with_chunked_transfer_encoding PASSED [ 36%]   
```
is `rgw:verify` suite & `--limit 10` enough or should I submit full `rgw:verify` or `rgw`?


@ivancich
sorry if you already submitted your teuthology runs, the s3tests with not failed because of this PR after ceph/java_s3tests#14 but without https://github.com/ceph/s3-tests/pull/501 (which has not merged yet) they also do not verify this PR correctness

**Comment by mkogan1** [comment]
jenkins test windows

**Comment by mkogan1** [comment]
jenkins test make check arm64

**Comment by cbodley** [comment]
> is `rgw:verify` suite & `--limit 10` enough or should I submit full `rgw:verify` or `rgw`?

please run the whole rgw suite. we run s3tests in other subsuites like rgw/multifs, rgw/sts, rgw/crypt, etc

**Comment by mkogan1** [comment]
jenkins test make check arm64

**Comment by mdw-at-linuxbox** [comment]
Looks fine - only thing I can see is do you really still want to call this "rgw/civetweb"?

**Review by mdw-at-linuxbox — APPROVED** [review]
Looks fine (other than calling it a "civetweb" change)

**Comment by mkogan1** [comment]
> Looks fine - only thing I can see is do you really still want to call this "rgw/civetweb"?

thank you, changed the PR title, preferred to leave the commit title to keep track all the way back when searching the commit history of various old release branches by commit tile

**Comment by mkogan1** [comment]
jenkins test make check arm64

**Comment by mkogan1** [comment]
queued full _rgw_ suite tueuthology run, 
https://pulpito.ceph.com/mkogan-2023-03-21_16:00:08-rgw-wip-chuncked-put-i04-distro-default-smithi/

**Comment by ivancich** [comment]
QA run:
* https://pulpito.ceph.com/ivancich-2023-03-23_02:25:39-rgw-wip-eric-testing-1-distro-default-smithi/
* https://pulpito.ceph.com/ivancich-2023-03-23_02:26:05-rgw-wip-eric-testing-1-distro-default-smithi/

**Comment by cbodley** [comment]
> I think we should wait until this passes the rgw upgrade suite.

we're waiting on Mark's results, which are running against the new test case in https://github.com/ceph/s3-tests/pull/501

**Comment by ivancich** [comment]
> > I think we should wait until this passes the rgw upgrade suite.
> 
> we're waiting on Mark's results, which are running against the new test case in [ceph/s3-tests#501](https://github.com/ceph/s3-tests/pull/501)

OK, then I'll pull this off of my QA run and won't merge.

**Comment by mkogan1** [comment]
@cbodley @ivancich ACK
a full `rgw` suite run with the new `test_object_write_with_chunked_transfer_encoding` test (https://github.com/ceph/s3-tests/pull/501)
has completed successfully below, none of the failures is related to the new test
https://pulpito.ceph.com/mkogan-2023-03-21_16:00:08-rgw-wip-chuncked-put-i04-distro-default-smithi/
for representative example: http://qa-proxy.ceph.com/teuthology/mkogan-2023-03-21_16:00:08-rgw-wip-chuncked-put-i04-distro-default-smithi/7215423/teuthology.log :
`2023-03-24T11:02:22.344 INFO:teuthology.orchestra.run.smithi026.stdout:s3tests_boto3/functional/test_s3.py::test_object_write_with_chunked_transfer_encoding PASSED [ 36%]`

**Comment by mkogan1** [comment]
> @cbodley @ivancich ACK a full `rgw` suite run with the new `test_object_write_with_chunked_transfer_encoding` test ([ceph/s3-tests#501](https://github.com/ceph/s3-tests/pull/501)) has completed successfully below, none of the failures is related to the new test https://pulpito.ceph.com/mkogan-2023-03-21_16:00:08-rgw-wip-chuncked-put-i04-distro-default-smithi/ for representative example: http://qa-proxy.ceph.com/teuthology/mkogan-2023-03-21_16:00:08-rgw-wip-chuncked-put-i04-distro-default-smithi/7215423/teuthology.log : `2023-03-24T11:02:22.344 INFO:teuthology.orchestra.run.smithi026.stdout:s3tests_boto3/functional/test_s3.py::test_object_write_with_chunked_transfer_encoding PASSED [ 36%]`

@cbodley may please ask to take another look when there's time, any additional tests?

**Pull request merged**
