### PR TITLE
jewel: cls/rgw: list_plain_entries() stops before bi_log entries

### PR DESCRIPTION
**Pull request by asheplyakov**
http://tracker.ceph.com/issues/20014

### CODE REVIEW

**Comment by asheplyakov** [comment]
Cloning into 'src/gmock'...
fatal: unable to access 'https://github.com/ceph/gmock.git/': Failed to connect to github.com port 443: Connection timed out
fatal: clone of 'https://github.com/ceph/gmock.git' into submodule path 'src/gmock' failed

**Comment by asheplyakov** [comment]
jenkins retest this please

**Comment by asheplyakov** [comment]
jenkins retest this please

**Comment by smithfarm** [comment]
@yehudasa @oritwas @cbodley This passed a rgw suite http://pulpito.front.sepia.ceph.com/smithfarm-2017-06-22_11:53:25-rgw-wip-jewel-backports-distro-basic-smithi/ with a relatively massive failure - 16 jobs failed, all in the same way: "SWIFT_TEST_CONFIG_FILE=/home/ubuntu/cephtest/archive/testswift.client.0.conf /home/ubuntu/cephtest/swift/virtualenv/bin/nosetests -w /home/ubuntu/cephtest/swift/test/functional -v -a '!fails_on_rgw'"

Any idea how to fix this? It also caused this one failure in the rados suite: http://pulpito.front.sepia.ceph.com/smithfarm-2017-06-22_11:36:26-rados-wip-jewel-backports-distro-basic-smithi/1316336/

**Comment by smithfarm** [comment]
@yehudasa @cbodley @oritwas This passed another RGW suite at http://tracker.ceph.com/issues/19538#note-70

This time, there was only one failure (in a test with the Apache frontend, no less), because I included https://github.com/ceph/ceph/pull/15870 in the integration branch and ran with `--teuthology-branch wip-20392` to simulate a testing environment in which `swift.py` has been moved to the ceph repo, and fixed to clone the `ceph-jewel` branch of ceph/swift.git.

I also re-ran the one test failure and it did not reproduce, so I believe this is ready to merge. Please give a positive review if you agree. Thanks!

**Pull request merged**
