### PR TITLE
DNM: common: fix up "ceph releases"

### PR DESCRIPTION
**Pull request by gregsfortytwo**
Users are being confused because they still see "luminous" after upgrading to mimic. Fix that!

### CODE REVIEW

**Comment by gregsfortytwo** [comment]
I'm unsure — are these SERVER_* features actually the ones we want to rely on, or should we be looking at something else?
If these work, perhaps we can do something automatic instead of needing to remember to patch this function.

(I did two commits to allow for easier backporting!)

**Comment by gregsfortytwo** [comment]
Yeah, that makes some sense. My concern is that users get really unhappy when they run a full upgrade and don't see the latest release that they just upgraded to for eg their OSDs.

The kernel client is always going to be weird and messy with these sorts of things since it's a separate implementation which depends on the actual feature bits rather than a global set. I'm not sure what to do there...

**Comment by liewegas** [comment]
I suggest we modify set-require-min-compat-client to not take anything > 
luminous, and error out with a message that there have been no 
client protocol changes since luminous.

This will hopefully help encourage users to think of client compatibility 
as a separate thing from the upgrade of the cluster itself.

**Comment by gregsfortytwo** [comment]
Closing this for now until someone develops a smarter approach.

**Pull request closed without merging**
