### PR TITLE
Fixes: #11106 

### PR DESCRIPTION
**Pull request by Cedricdelcroix**
Fixes: #11106
doc: change "It starts mon, osd and/or mds" to "It starts rgw, mon, osd and/or mds"
Signed-off-by: CedricDelcroix delcroix.cedric62@gmail.com

### CODE REVIEW

**Comment by dachary** [comment]
You should copy / paste the following in the commit message with **git commit --amend** 
<pre>
doc: change "It starts mon, osd and/or mds" to "It starts rgw, mon, osd and/or mds"

Fixes: #11106
Signed-off-by: CedricDelcroix &lt;delcroix.cedric62@gmail.com>
</pre>

**Comment by Cedricdelcroix** [comment]
@dachary I've update my commit message

**Comment by ldachary** [comment]
@Cedricdelcroix you now have 3 commits instead of one. You need to **git rebase -i HEAD~3** and remove the commits you do not need. And then **git push --force**

**Comment by dachary** [comment]
abandonned by @Cedricdelcroix

**Pull request closed without merging**
