### PR TITLE
hammer: mon: OSDMonitor: Missing nearfull flag set

### PR DESCRIPTION
**Pull request by aiicore**
http://tracker.ceph.com/issues/17403

Signed-off-by: Igor Podoski igor.podoski@ts.fujitsu.com
(cherry picked from commit 754887b575795ef96cda095f7f0d8c898e20f00f)

### CODE REVIEW

**Comment by smithfarm** [comment]
@aiicore Could you rebase please?

**Comment by smithfarm** [comment]
@aiicore github has a new button which, I found, adds an unwanted merge commit to the wip branch. Could you remove that in the rebase, please. Sorry for the inconvenience.

**Comment by smithfarm** [comment]
Changing to DNM (and replaced by https://github.com/ceph/ceph/pull/12027 ) until we can get the merge commit removed. Sorry for this trouble!

**Comment by aiicore** [comment]
@smithfarm done

**Comment by smithfarm** [comment]
@aiicore Thanks

**Comment by smithfarm** [comment]
@liewegas This backport passed a rados suite at http://tracker.ceph.com/issues/17151#note-7 with failures that I believe have been addressed (except for http://tracker.ceph.com/issues/15139 which is caused by the build system no longer providing dumpling-era packages).

I have rebuilt the integration branch to include the two fixes and scheduled a new run at http://tracker.ceph.com/issues/17151#note-14

Do you think it's OK to merge provided the second run succeeds?

**Comment by smithfarm** [comment]
Second run succeeded; third run here: http://pulpito.front.sepia.ceph.com/smithfarm-2016-11-21_11:52:41-rados-hammer-backports---basic-smithi/

**Comment by liewegas** [comment]
:+1:

**Pull request merged**
