### PR TITLE
rgw: compression uses optional::emplace instead of in-place factories

### PR DESCRIPTION
**Pull request by rzarzynski**

### CODE REVIEW

**Comment by cbodley** [comment]
jenkins test this please

**Comment by dachary** [comment]
jenkins test this please (tox bug, now fixed in master)

**Comment by mattbenjamin** [comment]
lgtm--jenkins must approve

**Comment by mattbenjamin** [comment]
@rzarzynski could you rebase, please?

**Comment by rzarzynski** [comment]
@mattbenjamin: rebased.

**Pull request merged**
