### PR TITLE
  common: add nested-name-specifier ThreadPool before WorkQueueVal

### PR DESCRIPTION
**Pull request by hjwsm1989**
Fixes: #12459

  Signed-off-by: huangjun <hjwsm1989@gmail.com>

### CODE REVIEW

**Comment by hjwsm1989** [comment]
@tchaikov could you have time to review this?

**Comment by tchaikov** [comment]
i posted my question on tracker

> what compiler are you using, and may i have its version? i am not able to reproduce your problem, though.

**Comment by hjwsm1989** [comment]
hi, kefu
gcc version 4.4.7 20120313 (Red Hat 4.4.7-4) (GCC)

**Comment by tchaikov** [comment]
thanks, i think i can reproduce it at http://gitbuilder.sepia.ceph.com/gitbuilder-ceph-rpm-centos6-5-amd64-basic/log.cgi?log=11e313e5ccf54eca340056d3ae5bf57630fd44e6 .

**Comment by tchaikov** [comment]
i pushed it to `wip-5338`, so your change can be confirmed by the gitbuilder. once gitbuilder is happy, this pull request is considered good to merge.

**Comment by tchaikov** [comment]
confirmed at http://gitbuilder.sepia.ceph.com/gitbuilder-ceph-rpm-centos6-5-amd64-basic/#origin/wip-5338 .

**Comment by hjwsm1989** [comment]
thanks

**Pull request merged**
