### PR TITLE
time: Make ceph_time clocks work under BSD

### PR DESCRIPTION
**Pull request by adamemerson**
Signed-off-by: Adam C. Emerson <aemerson@redhat.com>

### CODE REVIEW

**Comment by trociny** [comment]
It still does not build on FreeBSD due to CLOCK_REALTIME_COARSE being used in  ceph_time.cc:

 common/ceph_time.cc:52:21: error: use of undeclared identifier 'CLOCK_REALTIME_COARSE'
      clock_gettime(CLOCK_REALTIME_COARSE, &ts);

In #7170 I used a little different approach: https://github.com/ceph/ceph/commit/fa05220501c323fb8ce025142181efdf9190a1f7

**Comment by wjwithagen** [comment]
On 31-1-2016 09:28, Mykola Golub wrote:
> It still does not build on FreeBSD due to CLOCK_REALTIME_COARSE being
> used in ceph_time.cc:
> 
> common/ceph_time.cc:52:21: error: use of undeclared identifier
> 'CLOCK_REALTIME_COARSE'
> clock_gettime(CLOCK_REALTIME_COARSE, &ts);
> 
> In #7170 <https://github.com/ceph/ceph/pull/7170> I used a little
> different approach: fa05220
> <https://github.com/ceph/ceph/commit/fa05220501c323fb8ce025142181efdf9190a1f7>

Hi Mykola,

I sort of prefer the approach where it is made more explicit, and put at
the place where it is actually used.

If you prefer you way of porting, then perhaps src/include/compat.h
would be a more applicable place?

--WjW

**Comment by trociny** [comment]
I am fine with any approach. I just was pointing to yet another possible, which still is not perfect as it might be confusing. I suppose, a better solution would be to define in ceph_time.h a wrapper function ceph_clock_gettime() and constants CEPH_CLOCK_REALTIME..., so the changes are localized. But again I am fine with any fix.

**Comment by adamemerson** [comment]
I have a fix in https://github.com/adamemerson/ceph/commit/5477424ee769392eaf0c8c13b1ab379b307e328f

If it works for people I'll send another pull request.

**Comment by adamemerson** [comment]
Wrong commit. I'll just link to the branch

https://github.com/adamemerson/ceph/commits/wip-bsd-time-second-try

**Comment by wjwithagen** [comment]
On 1-2-2016 16:47, Adam C. Emerson wrote:
> Wrong commit. I'll just link to the branch
> 
> https://github.com/adamemerson/ceph/commits/wip-bsd-time-second-try
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ceph/ceph/pull/7340#issuecomment-178034469>.
> 

In my work last night I added the "std" workaround to this blob of code
as well. Removing clock_gettime calls here will very likely compile for
BSD without trouble. And it also mitigate the danger of having lots of
places where the conditonal clocktype selection is #ifdef-ed.

--WjW

**Comment by adamemerson** [comment]
All right, I now have pull request https://github.com/ceph/ceph/pull/7466 submitted that should take care of this.

**Pull request merged**
