### PR TITLE
osd: fix omap digest compare when scrub

### PR DESCRIPTION
**Pull request by XinzeChi**
Fixes: http://tracker.ceph.com/issues/16000
Signed-off-by: Xinze Chi <xinze@xsky.com>

### CODE REVIEW

**Comment by XinzeChi** [comment]
@tchaikov , please review . Thanks.

**Comment by tchaikov** [comment]
lgtm

**Comment by dzafman** [comment]
This is related to a Hammer only commit.

**Comment by tchaikov** [comment]
@dzafman if we look at the change closer the fix also applies to master.

**Comment by dzafman** [comment]
@tchaikov I think @athanatos was talking about limiting the reliance on FLAG_OMAP, for simplicity.

**Comment by dzafman** [comment]
@tchaikov See #9638

**Pull request closed without merging**
