### PR TITLE
cmake: set empty RPATH for some test executables

### PR DESCRIPTION
**Pull request by smithfarm**
Fixes: https://tracker.ceph.com/issues/41524
Signed-off-by: Nathan Cutler <ncutler@suse.com>

### CODE REVIEW

**Comment by smithfarm** [comment]
https://shaman.ceph.com/builds/ceph/wip-41524/da82cd4cc1035e02f6b5ccb7acc27b49f6e531ec/

**Comment by smithfarm** [comment]
```
110/180 Test #104: check-generated.sh ......................***Failed   54.86 sec 
...
176/180 Test #105: readable.sh .............................***Failed  418.03 sec 
...
```

**Comment by tchaikov** [comment]
@smithfarm it's a known issue. and has been fixed.

retest this please.

**Comment by smithfarm** [comment]
```
99% tests passed, 1 tests failed out of 180

Total Test time (real) = 3622.95 sec

The following tests FAILED:
	 56 - unittest_lockdep (Timeout)
```

**Comment by smithfarm** [comment]
jenkins test make check

**Comment by tchaikov** [comment]
@smithfarm i think #30028 could a better fix if it works. i am testing it.

**Comment by smithfarm** [comment]
> @smithfarm i think #30028 could a better fix if it works. i am testing it.

I agree. Your fix looks much better :-)

**Comment by smithfarm** [comment]
@tchaikov Looks like we still need `INSTALL_RPATH ""` because I got FTBFS on openSUSE Tumbleweed even with #30028 applied.

Rebased this fix and testing it now.

**Comment by smithfarm** [comment]
https://shaman.ceph.com/builds/ceph/wip-41524/51a1c621718e65a7062af7dcf12949bdd79a26d1/

**Comment by smithfarm** [comment]
With this patch, the Tumbleweed build in OBS passes: https://build.opensuse.org/package/show/filesystems:ceph:master:upstream/ceph

**Pull request merged**
