### PR TITLE
osd/PrimaryLogPG: make_writeable nit fixes

### PR DESCRIPTION
**Pull request by Matan-B**
Few minor fixes around `make_writeable()` (no behavior changes).
* `_make_clone()`: replace ~`obc`~ with `clone_obc` to improve readability (As discussed).
* use `find_if_not` instead of iterating thorough `snapc.snaps` twice.

Signed-off-by: Matan Breizman <mbreizma@redhat.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [x] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by ronen-fr** [comment]
LGTM.
We should probably implement a "Ceph-global" copy_until() template.

**Review by ronen-fr — APPROVED** [review]

**Review by athanatos — APPROVED** [review]

**Comment by athanatos** [comment]
Needs to go through the test suite.

**Comment by Matan-B** [comment]
jenkins test make check arm64

**Comment by NitzanMordhai** [comment]
https://pulpito.ceph.com/yuriw-2022-07-09_14:48:58-rados-wip-yuri6-testing-2022-07-07-1429-distro-default-smithi/

Failures, unrelated:
6921591 - https://tracker.ceph.com/issues/52321
6921593 - https://tracker.ceph.com/issues/52321
6921594 - https://tracker.ceph.com/issues/55789
6921595 - https://tracker.ceph.com/issues/52321
6921596 - https://tracker.ceph.com/issues/52321
6921597 - https://tracker.ceph.com/issues/55789

Details:
6921591\6921593\6921595\6921596 - qa/tasks/rook times out: 'check osd count' reached maximum tries (90) after waiting for 900 seconds - Ceph - Rook
6921594\6921597 -  cls_rgw.index_suggest_complete assert failuer during test

**Pull request merged**
