### PR TITLE
Revert "qa/tasks/cephfs: don't create a new CephManager if there is o…

### PR DESCRIPTION
**Pull request by mchangir**
…ne in the context"

This reverts commit 329edd3c56baff81cb76c5008ac2eaf7c110f9e1. This is temporary revert to unblock snap-scheule testing in teuthology.

See also: https://tracker.ceph.com/issues/66009

Fixes: https://tracker.ceph.com/issues/66763
Signedo-off-by: Milind Changire <mchangir@redhat.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Comment by vshankar** [comment]
jenkins test api

**Comment by vshankar** [comment]
I propose that we take this change in till @mchangir works out the details in https://github.com/ceph/ceph/pull/58158

**Review by batrick — COMMENTED** [review]
Everything about this points to some issue in the finishers used for modules. Perhaps the finisher is "stuck" doing something. For the original issue debug logs, it seemed that the finisher was waiting and then was never awoken.

It may be this PR somehow avoids a race but I think there needs to be more debugging for the finishers added to determine the cause. We simply don't have information about what the finisher is doing. I'd like to see:

* what the queue depth is at the time we push the context onto the queue
* whether the finisher is currently running
* **which Finisher** (pointer) is assigned to the module (currently it's really damn troublesome to figure this out).

**Comment by mchangir** [comment]
> Everything about this points to some issue in the finishers used for modules. Perhaps the finisher is "stuck" doing something. For the original issue debug logs, it seemed that the finisher was waiting and then was never awoken.
> 
> It may be this PR somehow avoids a race but I think there needs to be more debugging for the finishers added to determine the cause. We simply don't have information about what the finisher is doing. I'd like to see:
> 
> * what the queue depth is at the time we push the context onto the queue
> * whether the finisher is currently running
> * **which Finisher** (pointer) is assigned to the module (currently it's really damn troublesome to figure this out).

fyi - the PR for the actual problem is here: https://github.com/ceph/ceph/pull/58547

**Comment by vshankar** [comment]
> > Everything about this points to some issue in the finishers used for modules. Perhaps the finisher is "stuck" doing something. For the original issue debug logs, it seemed that the finisher was waiting and then was never awoken.
> > It may be this PR somehow avoids a race but I think there needs to be more debugging for the finishers added to determine the cause. We simply don't have information about what the finisher is doing. I'd like to see:
> > 
> > * what the queue depth is at the time we push the context onto the queue
> > * whether the finisher is currently running
> > * **which Finisher** (pointer) is assigned to the module (currently it's really damn troublesome to figure this out).
> 
> fyi - the PR for the actual problem is here: #58547

Closing this change in favour of that PR.

**Pull request closed without merging**
