### PR TITLE
mgr/dashboard: behave when pwdUpdateRequired key is missing

### PR DESCRIPTION
**Pull request by liewegas**
Fixes: https://tracker.ceph.com/issues/44271
Signed-off-by: Sage Weil <sage@redhat.com>

### CODE REVIEW

**Comment by callithea** [comment]
jenkins test dashboard backend

**Comment by votdev** [comment]
Does this belong to https://tracker.ceph.com/issues/44256? This PR will make it working, but will not fix the origin problem. I'm asking myself why these two fields do not exist. Older user databases will be migrated and new users will already have these fields with default values. How can we reproduce this?

**Comment by p-se** [comment]
> Does this belong to https://tracker.ceph.com/issues/44256? This PR will make it working, but will not fix the origin problem. I'm asking myself why these two fields do not exist. Older user databases will be migrated and new users will already have these fields with default values. How can we reproduce this?

I had a similar thought. Maybe the migration isn't working correctly? Anyway, this fixes the problem for now, but maybe someone should look into it once more.

**Comment by liewegas** [comment]
> > Does this belong to https://tracker.ceph.com/issues/44256? This PR will make it working, but will not fix the origin problem. I'm asking myself why these two fields do not exist. Older user databases will be migrated and new users will already have these fields with default values. How can we reproduce this?
> 
> I had a similar thought. Maybe the migration isn't working correctly? Anyway, this fixes the problem for now, but maybe someone should look into it once more.

This cluster was upgraded from master a few days before this change merged. I'm guessing the migration only triggers when upgrading from nautilus?

**Comment by votdev** [comment]
> > > Does this belong to [tracker.ceph.com/issues/44256](https://tracker.ceph.com/issues/44256)? This PR will make it working, but will not fix the origin problem. I'm asking myself why these two fields do not exist. Older user databases will be migrated and new users will already have these fields with default values. How can we reproduce this?
> > 
> > 
> > I had a similar thought. Maybe the migration isn't working correctly? Anyway, this fixes the problem for now, but maybe someone should look into it once more.
> 
> This cluster was upgraded from master a few days before this change merged. I'm guessing the migration only triggers when upgrading from nautilus?

Everytime the user database is loaded from the key/value store it is checked whether it is necessary to migrate it.

We have some unit tests to ensure migration works, so i'm wondering what happened here.

* [v0 -> v2](https://github.com/ceph/ceph/blob/master/src/pybind/mgr/dashboard/tests/test_access_control.py#L785)
* [v1 -> v2](https://github.com/ceph/ceph/blob/master/src/pybind/mgr/dashboard/tests/test_access_control.py#L676)
* [Test v2 is loaded correct](https://github.com/ceph/ceph/blob/master/src/pybind/mgr/dashboard/tests/test_access_control.py#L729)

**Comment by votdev** [comment]
I think i have it now. The database was created before https://github.com/ceph/ceph/pull/32680 was merged. This PR introduces the field `pwdUpdateRequired` which is missing in the already existing v2 database.

I think we can close this PR because this scenario should not happen in production. Beside that, we do not support migration between development versions.

**Comment by p-se** [comment]
> I think i have it now. The database was created before #32680 was merged. This PR introduces the field `pwdUpdateRequired` which is missing in the v2 database of your [test](https://tracker.ceph.com/issues/44271).
> 
> ```
> ceph_store_get accessdb_v2 found: {"users": {"admin": {"username": "admin", "password": "$2b$12$Ykme3yWivo/WJfNAAYgE3eI6VCouYtpJFpIv0sanBow8jwTwB7Uoy", "roles": ["administrator"], "name": null, "email": null, "lastUpdate": 1580415055, "enabled": true, "pwdExpirationDate" 
> : null}}, "roles": {}, "version": 2}
> ```
> 
> I think we can close this PR because this scenario should not happen in production. Beside that, the Dashboard does not support migrations within the same Ceph version.

I thinks there's value in having this PR merged for long running clusters that run on versions from master. The solution is simple and prevents them from unnecessary failures.

**Pull request merged**
