### PR TITLE
mgr/dashboard: NFS pages shows 'Page not found'

### PR DESCRIPTION
**Pull request by votdev**
If no orchestrator is configured, the NFS page in the Dashboard shows 'Page not found'.

Fixes: https://tracker.ceph.com/issues/53813

Old behaviour:
Bildschirmfoto vom 2022-01-10 11-29-28

Bildschirmfoto von 2022-01-10 11-27-00

New (expected) behaviour:
Bildschirmfoto vom 2022-01-10 11-27-50

Signed-off-by: Volker Theile <vtheile@suse.com>

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [x] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [x] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by votdev** [comment]
jenkins retest this please

**Comment by s0nea** [comment]
jenkins retest this please

**Comment by votdev** [comment]
jenkins test dashboard

**Comment by s0nea** [comment]
jenkins test dashboard

**Comment by nizamial09** [comment]
jenkins test dashboard

**Review by nizamial09 — APPROVED** [review]
LGTM! Although from a UI perspective, just `No orchestrator is configured (try ceph.....). Please consult documentation......` message would have been great instead of the lengthy traceback.

**Review by s0nea — APPROVED** [review]

**Review by alfonsomthd — APPROVED** [review]

**Comment by votdev** [comment]
> LGTM! Although from a UI perspective, just `No orchestrator is configured (try ceph.....). Please consult documentation......` message would have been great instead of the lengthy traceback.

I fully agree with you, but IMO the root of the problem is located in the NFS mgr module at the time when the exception is thrown. This should be fixed, but this is not part of this PR.

**Comment by nizamial09** [comment]
> This should be evaluated and fixed, but this is not part of this PR.

Agreed!

**Review by callithea — APPROVED** [review]

**Pull request merged**
