### PR TITLE
luminous: ceph-volume: Require lvm2, move to osd package

### PR DESCRIPTION
**Pull request by pdvian**
http://tracker.ceph.com/issues/22701

### CODE REVIEW

**Comment by alfredodeza** [comment]
@smithfarm not sure if you need me to do anything here, changes look OK.

**Comment by smithfarm** [comment]
@alfredodeza Oh, never mind, this is not a ceph-volume patch. It's a spec file patch.

**Comment by smithfarm** [comment]
Closing in favor of #20215

**Comment by smithfarm** [comment]
@pdvian Instead of resolving the conflict manually, the better course of action here was to cherry-pick d1f2df37dd0 first.

**Pull request closed without merging**
