### PR TITLE
test/rgw/notification: verify network access to http server

### PR DESCRIPTION
**Pull request by yuvalif**
## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [x] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [x] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Review by AliMasarweh — APPROVED** [review]
LGTM

**Comment by AliMasarweh** [comment]
I think you missed these:
https://github.com/ceph/ceph/pull/57748/files#diff-83b1d2148e5a0483255b9af5f707fec576625a16c04aca191578d555ca336443R3694

https://github.com/ceph/ceph/pull/57748/files#diff-83b1d2148e5a0483255b9af5f707fec576625a16c04aca191578d555ca336443R3707

Did you left these because they are endpoint agnostic?
https://github.com/ceph/ceph/pull/57748/files#diff-83b1d2148e5a0483255b9af5f707fec576625a16c04aca191578d555ca336443R3786

https://github.com/ceph/ceph/pull/57748/files#diff-83b1d2148e5a0483255b9af5f707fec576625a16c04aca191578d555ca336443R3707

**Review by AliMasarweh — APPROVED** [review]
Other than the above comments, LGTM

**Comment by yuvalif** [comment]
> I think you missed these: https://github.com/ceph/ceph/pull/57748/files#diff-83b1d2148e5a0483255b9af5f707fec576625a16c04aca191578d555ca336443R3694
> 
> https://github.com/ceph/ceph/pull/57748/files#diff-83b1d2148e5a0483255b9af5f707fec576625a16c04aca191578d555ca336443R3707
> 
> Did you left these because they are endpoint agnostic? https://github.com/ceph/ceph/pull/57748/files#diff-83b1d2148e5a0483255b9af5f707fec576625a16c04aca191578d555ca336443R3786
> 
> https://github.com/ceph/ceph/pull/57748/files#diff-83b1d2148e5a0483255b9af5f707fec576625a16c04aca191578d555ca336443R3707



> I think you missed these: https://github.com/ceph/ceph/pull/57748/files#diff-83b1d2148e5a0483255b9af5f707fec576625a16c04aca191578d555ca336443R3694
> 
> https://github.com/ceph/ceph/pull/57748/files#diff-83b1d2148e5a0483255b9af5f707fec576625a16c04aca191578d555ca336443R3707
> 
> Did you left these because they are endpoint agnostic? https://github.com/ceph/ceph/pull/57748/files#diff-83b1d2148e5a0483255b9af5f707fec576625a16c04aca191578d555ca336443R3786
> 
> https://github.com/ceph/ceph/pull/57748/files#diff-83b1d2148e5a0483255b9af5f707fec576625a16c04aca191578d555ca336443R3707



> I think you missed these: https://github.com/ceph/ceph/pull/57748/files#diff-83b1d2148e5a0483255b9af5f707fec576625a16c04aca191578d555ca336443R3694
> 
> https://github.com/ceph/ceph/pull/57748/files#diff-83b1d2148e5a0483255b9af5f707fec576625a16c04aca191578d555ca336443R3707
> 
> Did you left these because they are endpoint agnostic? https://github.com/ceph/ceph/pull/57748/files#diff-83b1d2148e5a0483255b9af5f707fec576625a16c04aca191578d555ca336443R3786
> 
> https://github.com/ceph/ceph/pull/57748/files#diff-83b1d2148e5a0483255b9af5f707fec576625a16c04aca191578d555ca336443R3707

can you please add the line numbers? the links juts point to the file diff

**Comment by yuvalif** [comment]
> I think you missed these: https://github.com/ceph/ceph/pull/57748/files#diff-83b1d2148e5a0483255b9af5f707fec576625a16c04aca191578d555ca336443R3694
> 
> https://github.com/ceph/ceph/pull/57748/files#diff-83b1d2148e5a0483255b9af5f707fec576625a16c04aca191578d555ca336443R3707
> 
> Did you left these because they are endpoint agnostic? https://github.com/ceph/ceph/pull/57748/files#diff-83b1d2148e5a0483255b9af5f707fec576625a16c04aca191578d555ca336443R3786
> 
> https://github.com/ceph/ceph/pull/57748/files#diff-83b1d2148e5a0483255b9af5f707fec576625a16c04aca191578d555ca336443R3707



> I think you missed these: https://github.com/ceph/ceph/pull/57748/files#diff-83b1d2148e5a0483255b9af5f707fec576625a16c04aca191578d555ca336443R3694
> 
> https://github.com/ceph/ceph/pull/57748/files#diff-83b1d2148e5a0483255b9af5f707fec576625a16c04aca191578d555ca336443R3707
> 
> Did you left these because they are endpoint agnostic? https://github.com/ceph/ceph/pull/57748/files#diff-83b1d2148e5a0483255b9af5f707fec576625a16c04aca191578d555ca336443R3786
> 
> https://github.com/ceph/ceph/pull/57748/files#diff-83b1d2148e5a0483255b9af5f707fec576625a16c04aca191578d555ca336443R3707



> I think you missed these: https://github.com/ceph/ceph/pull/57748/files#diff-83b1d2148e5a0483255b9af5f707fec576625a16c04aca191578d555ca336443R3694
> 
> https://github.com/ceph/ceph/pull/57748/files#diff-83b1d2148e5a0483255b9af5f707fec576625a16c04aca191578d555ca336443R3707
> 

i did not see failures in these tests. we can try and add it there if we see failures so we can verify if the failure is a test issue

> Did you left these because they are endpoint agnostic? https://github.com/ceph/ceph/pull/57748/files#diff-83b1d2148e5a0483255b9af5f707fec576625a16c04aca191578d555ca336443R3786
> 
> https://github.com/ceph/ceph/pull/57748/files#diff-83b1d2148e5a0483255b9af5f707fec576625a16c04aca191578d555ca336443R3707

yes, this checks only the http server

**Comment by yuvalif** [comment]
teuthology is passing for http:
http://pulpito.front.sepia.ceph.com/yuvalif-2024-05-28_13:49:24-rgw:notifications-wip-yuval-test-http-distro-default-smithi/
http://pulpito.front.sepia.ceph.com/yuvalif-2024-05-28_15:16:23-rgw:notifications-wip-yuval-test-http-distro-default-smithi/

**Pull request merged**
