### PR TITLE
rbd: refactor cli command handling

### PR DESCRIPTION
**Pull request by dillaman**
In preparation for new RBD features such as RBD mirroring that will required numerous new CLI commands, the current monolithic rbd utility has been refactored to simplify its future maintenance.

* commands are self-registering with the cli command / argument processor
* help is dynamically generated for a given command via ```rbd help <command name>```

### CODE REVIEW

**Comment by jdurgin** [comment]
getting a regex error trying to use anything with an image name:

``` 9: (std::__throw_regex_error(std::regex_constants::error_type)+0x35) [0x7fb63c108375]
 10: (std::__detail::_Compiler<char const*, std::regex_traits<char> >::_M_bracket_expression()+0xc6) [0x7fb642c185d6]
 11: (std::__detail::_Compiler<char const*, std::regex_traits<char> >::_M_atom()+0x5a) [0x7fb642c1880a]
 12: (std::__detail::_Compiler<char const*, std::regex_traits<char> >::_M_term()+0x2a) [0x7fb642c1904a]
 13: (std::__detail::_Compiler<char const*, std::regex_traits<char> >::_M_alternative()+0xe) [0x7fb642c190ee]
 14: (std::__detail::_Compiler<char const*, std::regex_traits<char> >::_M_disjunction()+0x24) [0x7fb642c19264]
 15: (std::__detail::_Compiler<char const*, std::regex_traits<char> >::_M_atom()+0x4d3) [0x7fb642c18c83]
 16: (std::__detail::_Compiler<char const*, std::regex_traits<char> >::_M_term()+0x2a) [0x7fb642c1904a]
 17: (std::__detail::_Compiler<char const*, std::regex_traits<char> >::_M_alternative()+0xe) [0x7fb642c190ee]
 18: (std::__detail::_Compiler<char const*, std::regex_traits<char> >::_M_alternative()+0x57) [0x7fb642c19137]
 19: (std::__detail::_Compiler<char const*, std::regex_traits<char> >::_M_alternative()+0x57) [0x7fb642c19137]
 20: (std::__detail::_Compiler<char const*, std::regex_traits<char> >::_M_disjunction()+0x24) [0x7fb642c19264]
 21: (std::__detail::_Compiler<char const*, std::regex_traits<char> >::_M_atom()+0x4d3) [0x7fb642c18c83]
 22: (std::__detail::_Compiler<char const*, std::regex_traits<char> >::_M_term()+0x2a) [0x7fb642c1904a]
 23: (std::__detail::_Compiler<char const*, std::regex_traits<char> >::_M_alternative()+0xe) [0x7fb642c190ee]
 24: (std::__detail::_Compiler<char const*, std::regex_traits<char> >::_M_alternative()+0x57) [0x7fb642c19137]
 25: (std::__detail::_Compiler<char const*, std::regex_traits<char> >::_M_disjunction()+0x24) [0x7fb642c19264]
 26: (std::__detail::_Compiler<char const*, std::regex_traits<char> >::_Compiler(char const* const&, char const* const&, std::regex_traits<char>&, unsigned int)+0x242) [0x7fb642c195e2]
 27: (std::shared_ptr<std::__detail::_Automaton> std::__detail::__compile<char const*, std::regex_traits<char> >(char const* const&, char const* const&, std::regex_traits<char>&, unsigned int)+0x28) [0x7fb642c19998]
 28: (rbd::utils::extract_spec(std::string const&, std::string*, std::string*, std::string*)+0x65) [0x7fb642c13ff5]
```

**Comment by jdurgin** [comment]
Things like rbd ls --debug-ms 1 now interpret the 1 as an unknown positional arg. Using --debug-ms=1 works around this, but it'd be nice to preserve the old behavior if possible.

**Comment by dillaman** [comment]
@jdurgin Good catch -- I had to put special logic in the command spec processing to handle all the possible unknown arguments.  I just didn't extend it to the actual command execution.  Might just be easier to throw all the config options into a hidden options_descriptions so that we can throw when we see things we don't expect.

**Comment by dillaman** [comment]
@jdurgin What version of GCC do you have that gave you the reg-ex issue?

**Comment by jdurgin** [comment]
gcc 4.8.3 on fedora 20

**Comment by dillaman** [comment]
@jdurgin There's your problem -- fc20 is EOL :stuck_out_tongue_winking_eye:

**Comment by jdurgin** [comment]
try pushing to the gitbuilders with a 'rbd info foo' added to make check - 4.8.3 is just behind the 4.8.4 on trusty. there is boost::regex if the std one isn't fully supported on current platforms

**Comment by dillaman** [comment]
@jdurgin Appears that it isn't supported on GCC 4.8.x (it was just a placeholder) -- first implemented in 4.9.x (https://gcc.gnu.org/bugzilla/show_bug.cgi?id=53631)

**Comment by dillaman** [comment]
@dachary Interesting bot failure

**Comment by dachary** [comment]
@dillaman indeed. First time I see it. I'll keep it in mind. It looks like a transient network failure.

**Comment by jdurgin** [comment]
a couple more minor differences from ceph option parsing: - and _ are interchangeable for generic ceph options (--debug_ms 1 doesn't work with this patchset), and '--' ignores options after it, so e.g. rbd ls -- --blah works on a pool called '--blah'

**Comment by dillaman** [comment]
@jdurgin update pushed

**Comment by dillaman** [comment]
I return the command help only when the error code is -EINVAL -- it's unfortunate that it's used in cased where it wasn't an invalid argument error.  I guess I can have the parse errors return (positive) EINVAL to differentiate from odd librbd -EINVAL errors.

**Comment by jdurgin** [comment]
A few global short options don't work anymore (K, k, m are relevant for rbd) - from md_config_t::parse_argv()

```
rbd -k /dev/null ls
rbd: unrecognised option '-k'
```

**Comment by dillaman** [comment]
@jdurgin Rebased and added support for the new 'snap rename' command

**Comment by jdurgin** [comment]
Can you add the changed input of --image-features to PendingReleaseNotes? Looks like the last thing using it in the tests is the fio task: http://pulpito.ceph.com/joshd-2015-11-05_12:59:22-rbd-wip-rbd-testing---basic-multi/

I'm not sure if the crash during 'rbd rm' in http://pulpito.ceph.com/joshd-2015-11-05_12:59:22-rbd-wip-rbd-testing---basic-multi/1139277/ is related to this pr.

**Comment by jdurgin** [comment]
The rbd rm crash seems unrelated - caused by the perf_start() movement, it fails when perfcounters aren't initialized when flush() is called, e.g. when opening an image whose header has been deleted.

**Comment by dillaman** [comment]
@jdurgin PendingReleaseNotes updated and I've opened a new ticket for updating the teuthology test

**Comment by jdurgin** [comment]
The implementation still uses --image-features, just with text names - the singular no longer works

**Comment by jdurgin** [comment]
looks like rbd-default-format isn't applying correctly:

```
./rbd create -s 10 --image-features layering --rbd-default-format 2 test
rbd: the argument for option '--features' is invalid
```

**Comment by dillaman** [comment]
@jdurgin Corrected typo on '--image-feature' and fixed odd handling of multitoken support when positional elements are in-use.

**Pull request merged**
