### PR TITLE
[DNM] discussion: async recovery

### PR DESCRIPTION
**Pull request by Aran85**
Signed-off-by: Zengran Zhang <zhzr@sangfor.com>

### CODE REVIEW

**Comment by Aran85** [comment]
@gregsfortytwo hi Gregory, i removed the restrictions and took some qa test with only rw on replica pool ...without finding any problem... 
i add a verify function into `rados load-gen`, it generate random data then write(95%) , meanwhile generate read(5%)  to verify data correctness(i could post the verify code if need to).  a simple failure script performed which will random up/down osds.
I'll appreciate it very much if you can give some guidance.

**Comment by Aran85** [comment]
close but hoping for discussion

**Comment by gregsfortytwo** [comment]
I think you're trying to implement the option to not wait for recovery on objects which are degraded with this code?

But the way you're bypassing a bunch of the async recovery machinery is confusing me. Can you include some documentation about the change, and the algorithm you're trying to implement (with explanation for why it works)?

(Also, feel free to leave PRs open even if you don't want them merged. The "Do Not Merge" tag should for that; you can also attach RFC "Request For Comment".)

**Comment by Aran85** [comment]
> I think you're trying to implement the option to not wait for recovery on objects which are degraded with this code?

yes..

> But the way you're bypassing a bunch of the async recovery machinery is confusing me. 

i think i should take an explanation on the change,  the `writable_with_acting` will calculate the number of shards who *do not missing* the object within the op.  if the number is greater than pool.min_size,we bypassing the op.Meanwhile the `is_degraded_or_backfilling_object` will not  check wether  the object is missing on any shard(degraded) any more . so when `generate_subop` for `issue_op`, we ship the pglog only to the shards who are missing the object(like backfilling does).

my original intention is removing the restrictions to see what problem will happen, but now i puzzled..

**Comment by gregsfortytwo** [comment]
Yeah, having a ```writable_with_acting``` function makes sense. I'm just not sure why the changes to ```is_degraded_or_backfilling_object``` are present — are you trying to remove async recovery entirely? I think there's a lot more to it than those bits.
And while I haven't examined it, I'm pretty sure we'll need to check in a lot more places than just ```do_op``` to handle this new "degraded but still writeable" state.

**Comment by Aran85** [comment]
yes, there must be a certain complexity so the restriction was added, and i wonder request the original 

> I'm just not sure why the changes to is_degraded_or_backfilling_object are present

just let it bypass the writable op...

> are you trying to remove async recovery entirely?

yes, remove the async recovery feature which merged to upstream.

**Comment by Aran85** [comment]
if op unwritable_with_acting, we would put the op into *waiting_for_writable_object(not impl yet)* queue, So when PG goto another active interval, we should check the waiting_for_writable_object queue, if any op could satisfy  *writable_with_acting*,we would requeue_ops...

**Comment by Aran85** [comment]
the main change of this means that we will allow  logs with empty opt  mixed in recent logs, so there will be 3 kind of procs maybe need to change.
1) the new op log append with empty opt, in this case, we need check the missing object according to this op and need to update missing according new version. 
2) append empty opt logs when merge_log extending local head to auth's head, maybe this dont need change? 
3)  rewind an empty opt log, this circumstance need be specially handled,but maybe not too hard.

any thought would be appreciated! @gregsfortytwo @liewegas

**Comment by Aran85** [comment]
@liewegas would you give some guidelines please?

**Comment by liewegas** [comment]
My high-level concern here is that I think this is roughly what @athanatos tried to do several years back: allow writes to degraded objects by only writing to the non-degraded replicas/peers.  I wish I could find the email/explanation of why it didn't work but I can't seem to find it.  Several months of effort simply didn't pan out.

My best recollection is that it led to either unfound or stuck peering PGs, and the reason was that an interval of OSDs [1,2,3] is normally/currently a promise that any write in that interval was captured by all of [1,2,3].  But since a degraded write might only go to 1,2 and not to 3 (because it was degraded going into the interval), we would get a PG event with a new version in that interval but if 1+2 failed and only 3 survived then the object would be lost.  The conclusion was that we should do what the current async recovery does: move the incomplete OSD (3) out of the acting set and treat it like a backfill peer, so that peering understood that only [1,2] captured all writes in that interval.  This is exactly what the new async recovery feature does.

**Comment by liewegas** [comment]
I thought he was just looking at doing the writes to already-degraded objects (to reduce the latency hit you get on any recently-touched 4MB RBD objects).  IIRC all peers still go the PG log items too.  But my memory is fuzzy and I can't find any written record of it... :(

**Comment by Aran85** [comment]
image

**Comment by Aran85** [comment]
when mid osd perform peering at last, E' will be an unfound object, does this be acceptable or expected? @gregsfortytwo

**Comment by Aran85** [comment]
i think this is an unacceptable circumstance.. the modify of E' is only update on osd.X, but not commit on osd.N & osd.M . so osd.X mark object E be unfound  is ok, but when osd.N or osd.M up again, they will think E' is the right version, so remove object E locally, waiting recover E'...

**Comment by Aran85** [comment]
on replica pool, my thought is maybe we could make the "degrade modify"  report its version to monitor before reply client, this means we could judge an op that wether it had acked to client..
when do peering, primary could make decision acording to the monitor's recording:
+  if  degraded modify had acked to client
      a. if a degraded modify could find any participant shard, 
            then we could accept the op
      b. if a degraded modify could _NOT_ find any participant shard, 
            then we should go incomplete
+  if degrade modify had not acked to client
       we just choose a newer version as committed

this will change much present logic, and extra overhead is  frequent communication with monitor. but maybe this also better than wait recovery..

**Comment by liewegas** [comment]
I'm not following this description:
"the modify of E' is only update on osd.X, but not commit on osd.N & osd.M"
ok..
" . so osd.X mark object E be unfound is ok"
if osd.X has a newer version (call it E'), why would it be unfound?
", but when osd.N or osd.M up again, they will think E' is the right version, so remove object E locally, waiting recover E'..."
If E' is newer, then it is the right version, and they should remove E and recovery E'.

**Comment by Aran85** [comment]
sorry for not descripe clearly.

if osd.N & osd.M down, the osd.X has version E' but did not have object E'.

present logic is that osd.X  will think E' is the right version,so go peering and active with missing E'.

i think the key problem is : 
  if osd.N or osd.M boot again, but they do not have object E' also, this means the object E' is loss. but osd.X may already go active and accept new operation.

So i think osd.X should  be able check the version E' wether had commited on osd.N or osd.M, if yes ,ok we go active, if not, we should rewind to E. .

**Comment by Aran85** [comment]
or we could  persist the op journal on osd.X,  so if osd.N or osd.M did not apply the E' op, they could replay the E' journal to rollforward?

**Comment by liewegas** [comment]
"So i think osd.X should be able check the version E' wether had commited on osd.N or osd.M before active, if yes ,ok we go active, if not, we should rewind to E. ."

The problem is that a rewind in this case is throwing away a write that we told the client we committed. 

Are you familar with the lost_unfound functions?  When you get an unfound object you have 2 choices: delete the object (forget that we know we should have a newer version) or revert (revert to the older version we do have, even though we know we are throwing out a newer committed update).

"or we could persist the op journal on osd.X, so if osd.N or osd.M did not apply the E' op, they could replay the E' journal to rollforward?"

Something like this might work, but only for a subset of operations (blind writes that do not depend on prior state of the object).  I'm not sure it's worth the complexity.

**Comment by Aran85** [comment]
> The problem is that a rewind in this case is throwing away a write that we told the client we committed.

"the rewind" i mean rewind a divergent log if we could check the op had not acked to client

**Comment by Aran85** [comment]
if op of E' did not committed on osd.N & osd.M, and committed on osd.X but only with pglog, i think on this circumstance, osd.X should rewind the op of E'. but how to distinguish this case need extra mechanism..

**Comment by liewegas** [comment]
Oh, I think I'm understanding what you're getting... the interval acting is [X] and [N,M] are async recovery targets?

**Comment by Aran85** [comment]
i want to kown if there is a new approach to replace the existing async recovery feature. :D

**Comment by gregsfortytwo** [comment]
I'm not sure I'm following this discussion, but the drawings aren't really plausible scenarios since they seem to indicate we're committing an object when it's durable on a single OSD? That should only be allowed if min_size is set to 1, in which case indeed loss of OSDs is going to mean peering starts failing and admins will have to mark stuff as lost quite often...

**Comment by Aran85** [comment]
@gregsfortytwo  sorry for not take an accurate description.. this is not the circumstance when min_size is set to 1, it's just because we will chose the newest last_update when find_best_info..

**Comment by Aran85** [comment]
the new approach would track the degraded modify, the code is incomplete, i want to kown wether it is worth to go forward..
core change:
* pg_missing_item add 2 member: 
     a.  set<pg_shard_t> holders;
     b.  map<eversion_t, set<pg_shard_t>> prior_holders;
  the first used to indicate current locate, prior_holders used when rewinding..

* pg_missing_set add 2 member:
  a. map<set<pg_shard_t>, weak_ptr<set<pg_shard_t>>> degraded_sets;
  b. map<hobject_t, shared_ptr<set<pg_shard_t>>> degraded_objects;
  local degraded modify will add to local missing_set  

  * the recover logic(not implement):
  after primary queried missing from replicas, primary will have local missing and peer missing, so it could check wether all degrad modify object is reocverable, if not we could go incomplete.

 hoping for your comment about the core change, thanks so much! @liewegas @gregsfortytwo

**Comment by liewegas** [comment]
I think the above sounds like it could be implemented, but it also sounds complex.  And I'm still concerned that we can get into a state where we are reverting to a prior version even though the write for the new version was acked to the client.

Here is a different proposal... please let me know if it makes sense to you.  For EC pools, we maintain a rollback object after every write that allows us to revert to the previous version of the object.  We keep these around to ensure we can get all EC shards on the same version (such that they can decode) even though they may fail in positions in a sequence of updates.

We could consider doing the same thing for replicated pools.  There is some overhead in bluestore for this metadata, so we'd probably want to quantify that before committing (or, actually, make this an optional behavior), but it would have the nice benefit that the ec and replicated recovery behavior would be more consistent.  Then we'd use the rollforward/can_rollback_to machinery to get all the replicas into a consistent state.

**Comment by liewegas** [comment]
@Aran85 I'm still worried I'm not fully understanding the case you're trying to address.  Can we maybe plan to discuss this on IRC (#ceph-devel) sometime this week?  I can be online as early as 1130 UTC if we plan ahead

**Comment by Aran85** [comment]
> And I'm still concerned that we can get into a state where we are reverting to a prior version even though the write for the new version was acked to the client
my thought is this does not relate to revert etc, and i want to explain more..

> the reason was that an interval of OSDs [1,2,3] is normally/currently a promise that any write in that interval was captured by all of [1,2,3]
i think this will cause misjudgement if we allow degraded  modify because it break this rule. so the basic problem is we can't  predicate an object if it is recoverable throught acting set.
let's say replicated pool w/ prev acting is [1,2,3], and osd.3 is missing object X.if modifying on object X meet failure,and acting become[3]. let's say again osd.3 had the modify w/ pglog , now there may be 3 state:
  a. modify committed on osd.1 and osd.2, and acked to client.
  b. modify  comitted on  osd.1 or osd.2 or both, and  did not acked to client.
  c.  modify didnot committed on ether osd.1 or osd.2 , and therefor did not acked to client.
right now osd.3 can't say which state had really happened, and if it revert to a prior version, on state.a circumstance, this is just the bad thing you concerned..but if it accept the new version, on state.c circumstance, the mistake is also unepected, because nobody persist the data of the new version, so i think the right behavior here is waiting osd.1 and osd.2 boot up instead of revert or go forward..

on ec pool ,the problem exist as well, let say prev acting is [1,2,3,4,5,6], and osd.3 is missing object X, if modifying on object X meet failure and acting become [1,2,3,4]. there is no difference with replicated pool case above, becase we have no ideal about osd.5 and osd.6, the new modify may be incomplete or had acked to client..

make sense now?  :D

**Comment by Aran85** [comment]
IRC maybe need some colleague to help...

**Comment by Aran85** [comment]
Never used IRC, I mistook it for a voice chat.. lol

**Comment by liewegas** [comment]
On Tue, 31 Jul 2018, Aran85 wrote:
> > the reason was that an interval of OSDs [1,2,3] is normally/currently a promise that any write in that interval was captured by all of [1,2,3]
> 
> i think this will cause misjudgement if we allow degraded  modify because it break this rule. so the basic problem is we can't  predicate an object if it is recoverable throught acting set.
> let's say replicated pool w/ prev acting is [1,2,3], and osd.3 is missing object X.if modifying on object X meet failure,and acting become[3]. let's say again osd.3 had the modify w/ pglog , now there may be 3 state:
>   a. modify committed on osd.1 and osd.2, and acked to client.
>   b. modify  comitted on  osd.1 or osd.2 or both, and  did not acked to client.
>   c.  modify didnot committed on ether osd.1 or osd.2 , and therefor did not acked to client.
> right now osd.3 can't say which state had really happened, and if it revert to a prior version, on state.a circumstance, this is just the bad thing you concerned..but if it accept the new version, on state.c circumstance, the mistake is also unepected, because nobody persist the data of the new version, so i think the right behavior here is waiting osd.1 and osd.2 boot up instead of revert or go forward..

Restating the sequence of events a bit more explicitly:

- acting is [1,2,3], object foo v1 is missing on osd.3
- write to foo (v2) is applied to osd.1 and osd.2 but not to osd.3.  osd.3 gets the pg log entry though.  (this is a hypothetical change: the OSD doesn't do this today!!)
- osd.1 and osd.2 fail, acting is [3]
- osd.3 see foo v2 should exist via its pglog but it doesn't have it, foo is unfound

The above is exactly why we *don't* implement writes to degraded objects: it mean that we frequently would end up with unfound objects.

To be clear, we can reach the same state with a different (more rare) sequence:

- acting is [1,2]
- write foo (v2) to osd.1 and osd.2
- osd.3 starts up, acting becomes [1,2,3]
- pg peers, osd.3 how has pglog entry for foo v2, but has not recovered the object yet
- osd.1 and osd.2 fail, acting is [3]
- osd.3 see foo v2 should exist via its pglog but it doesn't have it, foo is unfound

However, this sequence happens much less often than the first (hypothetical) sequence, which is why Sam's original 'async recovery' approach (which implemented writes to the non-degraded members of acting) was abandoned.

The current async recovery instead would result in a sequence like this:

- acting is [1,2,3], object foo v1 is missing on osd.3
- osd.3 is selected as an async target
- acting is [1,2], osd.3 is async target
- write to foo (v2) is applied to osd.1 and osd.2 but not to osd.3.
- osd.1 and osd.2 fail, acting is [3]
- osd.3 refuses to peer until osd.1 or osd.2 comes up because of the [1,2] past interval

...which is, I think, exactly what you are suggesting: that we wait for those osds to come up to decide whether to roll forward/back.  The mechanics for that are just a slightly different: osd.3 in the [3] interval doesn't [1,2] have a specific update they may have made; it is waiting to learn about all writes in that interval.

**Comment by Aran85** [comment]
👍 what a clear description! 

one thing i think current async recovery is not so good is  the async target calculate manner and only fewer osd(s) been choosen as async target. usually temporary failures are concentrated, so maybe each shard has some missing item..

**Comment by Aran85** [comment]
sorry.. the a bit more detail :
the `choose_async_recovery_{replicated | ec}` function choose the num entries which fall behind auth shard approximately, 
> approx_entries = auth_version - candidate_version;
then use the approxmate cost compare with an option value(osd_async_recovery_min_pg_log_entries=100) to choose candidates. so..
[1]. the approxmate cost  is not base on really recovery cost, awfully circumstance is object with huge omap entries..
[2]. the default value of osd_async_recovery_min_pg_log_entries is arbitrary..
[3]. the num of async target is restricted to le than (size - min_size).

on particular circumstance like upgrade osd one by one, each shard of each pg may have some fall behind entries, then the reason [3] will be an upper bound limit, consider the especial case, ec 8:3 or 4:2 pool..

**Comment by liewegas** [comment]
I think for [1], we can address that later when we have the partial recovery metadata in the log entries (e.g., which extent(s) in the object were modified) to estimate the recovery cost.  Unfortunately we don't have a way to estimate the omap size currently.

For [3], I'm not sure about the min_size and size relationship to the async targets.. @neha-ojha ?

I'm going to close this PR since I don't think the code is directly relevant to our discussion any more :).  Perhaps we should move this conversation to the ceph-devel email list?

**Pull request closed without merging**
