### PR TITLE
pybind/mgr: ceph fs status raise AttributeError

### PR DESCRIPTION
**Pull request by zy751713126**
Signed-off-by: Zheng Yin <zhengyin@cmss.chinamobile.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by zy751713126** [comment]
steps:
1、../src/vstart.sh -d -x -n -f
2、[root@cephdev build]# ./bin/ceph -s
  cluster:
    id:     92244509-c97e-4be7-935a-e2f54ba46605
    health: HEALTH_OK

  services:
    mon: 3 daemons, quorum a,b,c (age 38s)
    mgr: x(active, since 32s)
    mds: a:1 {0=a=up:active} 2 up:standby
    osd: 3 osds: 3 up (since 18s), 3 in (since 18s)

  task status:
    scrub status:
        mds.a: idle

  data:
    pools:   2 pools, 16 pgs
    objects: 22 objects, 2.2 KiB
    usage:   141 GiB used, 39 GiB / 180 GiB avail
    pgs:     16 active+clean

  io:
    client:   1.8 KiB/s wr, 0 op/s rd, 6 op/s wr

3、[root@cephdev build]# ./bin/ceph fs status
Error EINVAL: Traceback (most recent call last):
  File "/data/ceph/src/pybind/mgr/mgr_module.py", line 975, in _handle_command
    return self.handle_command(inbuf, cmd)
  File "/data/ceph/src/pybind/mgr/status/module.py", line 251, in handle_command
    return self.handle_fs_status(cmd)
  File "/data/ceph/src/pybind/mgr/status/module.py", line 176, in handle_fs_status
    mds_versions[metadata.get('ceph_version', "unknown")].append(standby['name'])
AttributeError: 'NoneType' object has no attribute 'get'

after fixing:
[root@cephdev build]# ./bin/ceph fs status

a - 0 clients
=
+------+--------+-----+---------------+-------+-------+
| Rank | State  | MDS |    Activity   |  dns  |  inos |
+------+--------+-----+---------------+-------+-------+
|  0   | active |  a  | Reqs:    0 /s |   10  |   13  |
+------+--------+-----+---------------+-------+-------+
+---------------+----------+-------+-------+
|      Pool     |   type   |  used | avail |
+---------------+----------+-------+-------+
| cephfs.a.meta | metadata | 2286  | 12.3G |
| cephfs.a.data |   data   |    0  | 12.3G |
+---------------+----------+-------+-------+
+-------------+
| Standby MDS |
+-------------+
|      b      |
|      c      |
+-------------+
MDS version: ceph version v15.0.0-6814-g8338739 (83387399ffd277f1eeca407385d343a0cbb29513) octopus (dev)

**Comment by batrick** [comment]
This is addressed by #31400. Thanks for the contribution though!

**Comment by zy751713126** [comment]
Hi @batrick ,  I think it is better to judge the metadata，Maybe in some cases，metadata is None，it will raise AttributeError.

**Comment by batrick** [comment]
It should be an error that the mgr has no metadata for a daemon in the MDSMap. We need to fix the MDS registering with the mgr as standby (#31400).

**Pull request closed without merging**
