### PR TITLE
Added ceph_flock() to libcephfs.

### PR DESCRIPTION
**Pull request by xroche**
As discussed in the [*flock() on libcephfs ?* thread](http://permalink.gmane.org/gmane.comp.file-systems.ceph.devel/23135) on *ceph-devel*, here is a ceph_flock for libcephfs.

### CODE REVIEW

**Comment by dachary** [comment]
@xroche it would be nice to have a unit test for that. I don't know where CephFS unit tests are though.

**Comment by xroche** [comment]
@dachary : seems to have some tests in src/test/libcephfs - I'll add one for locking (it won't be exhaustive, because it will lack cross-machine locking, but this is probably a bit more difficult to do that in an unit test)

**Comment by ukernel** [comment]
tests that open two connection should be good enough

**Comment by xroche** [comment]
**One thought while writing some unit tests**: the current Client::flock() implementation is... locking client_lock. It means that while waiting for a file lock, the entire process library is locked, and other threads will be blocked. I see no obvious way to solve this issue, except by using the LOCK_NB flag and use an exponential backoff poll.

**Comment by gregsfortytwo** [comment]
I think you're mis-reading the op flow. If you look at Client::make_request() you'll see it waits on a Cond variable until the reply comes in; this unlocks client_lock. :)

**Comment by xroche** [comment]
Darn, you're right, should have read more carefully :)

```c++
    // wait for signal
    ldout(cct, 20) << "awaiting reply|forward|kick on " << &caller_cond << dendl;
    request->kick = false;
    while (!request->reply &&         // reply
           request->resend_mds < 0 && // forward
           !request->kick)
      caller_cond.Wait(client_lock);
    request->caller_cond = NULL;
```

**Comment by dachary** [comment]
please ignore the last bot failure : false negative http://tracker.ceph.com/issues/10833

**Comment by ukernel** [comment]
looks good.

**Comment by noahdesu** [comment]
:+1:

**Comment by gregsfortytwo** [comment]
Please do any final review and merge this when you get back if you're happy.

**Pull request merged**
