### PR TITLE
Add openstack requirements to smoke suite

### PR DESCRIPTION
**Pull request by zmc**
Signed-off-by: Zack Cerza <zack@redhat.com>

### CODE REVIEW

**Comment by yuriw** [comment]
@zmc did you try running it ?

**Comment by zmc** [comment]
@yuriw Just scheduled http://pulpito.ceph.com/zack-2017-01-12_15:49:01-smoke-master---basic-ovh/

**Comment by zmc** [comment]
Hrm. Jobs are failing because of:
```
2017-01-12T23:06:20.502 INFO:teuthology.orchestra.run.ovh005.stderr:mount.ceph: unrecognized mount option "norequire_active_mds", passing to kernel.
2017-01-12T23:06:20.506 INFO:teuthology.orchestra.run.ovh005.stdout:parsing options: name=0,secretfile=/home/ubuntu/cephtest/ceph.data/client.0.secret,norequire_active_mds
2017-01-12T23:06:20.509 INFO:teuthology.orchestra.run.ovh005.stdout:mount error 22 = Invalid argument
```

I don't think this could be related to these changes, but I can't be sure...

**Comment by tmuthamizhan** [comment]
Zack, we need to bump the monitors to 3, instead of 2.

**Comment by zmc** [comment]
@tmuthamizhan where?

**Comment by tmuthamizhan** [comment]
http://qa-proxy.ceph.com/teuthology/zack-2017-01-12_15:49:01-smoke-master---basic-ovh/713392/teuthology.log
- this test yaml has only 2 mons. and the problem also seems to be that it
is unable to find ceph packages.

**Comment by zmc** [comment]
@tmuthamizhan ah, you're right. I'm not sure which remote to add it to. I'm really just trying to get the openstack files in here.

**Comment by tmuthamizhan** [comment]
it should go in here -
https://github.com/ceph/ceph/blob/master/qa/suites/smoke/systemd/tasks/systemd.yaml

like this:
roles:
- [mon.a, osd.0]
- [osd.1, osd.2]
- [mds.a, osd.3]
- [mon.b, mon.c, client.0]

**Comment by vasukulkarni** [comment]
3rd monitor is not required for this test, its tests only systemd part, Also tamil you can't overload mds or mon on same node for ceph-deploy tests.

**Comment by tmuthamizhan** [comment]
@vasu, i have not had any issues with overloading mons/mds for ceph-deploy
tests in the past.

**Comment by vasukulkarni** [comment]
@tmuthamizhan it has no effect in the code,  the roles are internally modified for that test.

**Comment by tmuthamizhan** [comment]
@zackc, you are right. the errors appear to be something with mount and not
your change.

2017-01-12T23:06:20.502
INFO:teuthology.orchestra.run.ovh005.stderr:mount.ceph: unrecognized
mount option "norequire_active_mds", passing to
kernel.2017-01-12T23:06:20.506
INFO:teuthology.orchestra.run.ovh005.stdout:parsing options:
name=0,secretfile=/home/ubuntu/cephtest/ceph.data/client.0.secret,norequire_active_mds2017-01-12T23:06:20.509
INFO:teuthology.orchestra.run.ovh005.stdout:mount error 22 = Invalid
argument

**Comment by ZackC** [comment]
@tmuthamizhan - I think you tagged the wrong person.  I haven't been involved in this project.  Hope it goes well though!

**Pull request merged**
