### PR TITLE
quincy: pybind/mgr: disable sqlite3/python autocommit

### PR DESCRIPTION
**Pull request by batrick**
backport tracker: https://tracker.ceph.com/issues/65736

---

backport of https://github.com/ceph/ceph/pull/56997
parent tracker: https://tracker.ceph.com/issues/65494

this backport was staged using ceph-backport.sh version 16.0.0.6848
find the latest version at https://github.com/ceph/ceph/blob/main/src/script/ceph-backport.sh

### CODE REVIEW

**Comment by batrick** [comment]
jenkins test api

**Comment by ljflores** [comment]
@epuertat can you review this and decide if it should go in quincy? If so, add the "needs-qa" label. If it is a blocker, additionally change the milestone to "v17.2.8".

**Comment by epuertat** [comment]
@ljflores I can't say, as I'm not familiar with the core of this PR. I just helped @batrick with an API test failure in the original PR.

**Comment by batrick** [comment]
> @epuertat can you review this and decide if it should go in quincy? If so, add the "needs-qa" label. If it is a blocker, additionally change the milestone to "v17.2.8".

It should go in v17.2.8. The bug can leave the sqlite3 database in a state the mgr doesn't know how to recover from.

**Review by phlogistonjohn — APPROVED** [review]
python bits (and teuthology bits) look ok for backport.
c++ bits are over my head :-)

**Comment by ljflores** [comment]
Rados approved: https://tracker.ceph.com/projects/rados/wiki/QUINCY#httpstrackercephcomissues67719

**Comment by hswong3i** [comment]
My [ceph-ceph-17.2.8](https://build.opensuse.org/package/show/home:alvistack/ceph-ceph-17.2.8) OBS packaging for Ubuntu 24.04 is broken with following error message:
```
root@ais3ua9thiem-1:~# ceph -s
  cluster:
    id:     8ef45e11-f70c-5cb6-8c83-b631cde550af
    health: HEALTH_ERR
            Module 'devicehealth' has failed: cannot start a transaction within a transaction
            1 mgr modules have recently crashed
 
  services:
    mon: 2 daemons, quorum ais3ua9thiem-2,ais3ua9thiem-1 (age 12m)
    mgr: ais3ua9thiem-1(active, since 4m)
    mds: 1/1 daemons up
    osd: 1 osds: 1 up (since 12m), 1 in (since 71m)
 
  data:
    volumes: 1/1 healthy
    pools:   4 pools, 145 pgs
    objects: 23 objects, 26 KiB
    usage:   300 MiB used, 9.7 GiB / 10 GiB avail
    pgs:     145 active+clean
```
```
root@ais3ua9thiem-1:~# tail -f -n 500 /var/log/ceph/ceph-mgr.ais3ua9thiem-1.log
2024-11-19T06:04:53.965+0000 74652c0006c0 -1 Traceback (most recent call last):
  File "/usr/share/ceph/mgr/mgr_module.py", line 513, in check
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/ceph/mgr/devicehealth/module.py", line 364, in _do_serve
    if self.db_ready() and self.enable_monitoring:
       ^^^^^^^^^^^^^^^
  File "/usr/share/ceph/mgr/mgr_module.py", line 1282, in db_ready
    return self.db is not None
           ^^^^^^^
  File "/usr/share/ceph/mgr/mgr_module.py", line 1294, in db
    self._db = self.open_db()
               ^^^^^^^^^^^^^^
  File "/usr/share/ceph/mgr/mgr_module.py", line 1275, in open_db
    self.configure_db(db)
  File "/usr/share/ceph/mgr/mgr_module.py", line 1249, in configure_db
    self.load_schema(db)
  File "/usr/share/ceph/mgr/mgr_module.py", line 1228, in load_schema
    db.execute('BEGIN;')
sqlite3.OperationalError: cannot start a transaction within a transaction

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/ceph/mgr/devicehealth/module.py", line 408, in serve
    self._do_serve()
  File "/usr/share/ceph/mgr/mgr_module.py", line 521, in check
    self.open_db();
    ^^^^^^^^^^^^^^
  File "/usr/share/ceph/mgr/mgr_module.py", line 1275, in open_db
    self.configure_db(db)
  File "/usr/share/ceph/mgr/mgr_module.py", line 1249, in configure_db
    self.load_schema(db)
  File "/usr/share/ceph/mgr/mgr_module.py", line 1228, in load_schema
    db.execute('BEGIN;')
sqlite3.OperationalError: cannot start a transaction within a transaction
```

Once partly rollback with https://github.com/alvistack/ceph-ceph/blob/5ecb79fdfc03f2050b7472f86f4b1335132d6e27/debian/patches/0027-57199-revert-wip-65736-quincy.patch and recompile the packages, now error gone and running normally:
```
root@ais3ua9thiem-1:~# ceph -s
  cluster:
    id:     8ef45e11-f70c-5cb6-8c83-b631cde550af
    health: HEALTH_ERR
            Module 'devicehealth' has failed: cannot start a transaction within a transaction
            1 mgr modules have recently crashed
 
  services:
    mon: 2 daemons, quorum ais3ua9thiem-2,ais3ua9thiem-1 (age 12m)
    mgr: ais3ua9thiem-1(active, since 4m)
    mds: 1/1 daemons up
    osd: 1 osds: 1 up (since 12m), 1 in (since 71m)
 
  data:
    volumes: 1/1 healthy
    pools:   4 pools, 145 pgs
    objects: 23 objects, 26 KiB
    usage:   300 MiB used, 9.7 GiB / 10 GiB avail
    pgs:     145 active+clean
```

**Comment by batrick** [comment]
> My [ceph-ceph-17.2.8](https://build.opensuse.org/package/show/home:alvistack/ceph-ceph-17.2.8) OBS packaging for Ubuntu 24.04 is broken with following error message:
> 
> ```
> root@ais3ua9thiem-1:~# ceph -s
>   cluster:
>     id:     8ef45e11-f70c-5cb6-8c83-b631cde550af
>     health: HEALTH_ERR
>             Module 'devicehealth' has failed: cannot start a transaction within a transaction
>             1 mgr modules have recently crashed
>  
>   services:
>     mon: 2 daemons, quorum ais3ua9thiem-2,ais3ua9thiem-1 (age 12m)
>     mgr: ais3ua9thiem-1(active, since 4m)
>     mds: 1/1 daemons up
>     osd: 1 osds: 1 up (since 12m), 1 in (since 71m)
>  
>   data:
>     volumes: 1/1 healthy
>     pools:   4 pools, 145 pgs
>     objects: 23 objects, 26 KiB
>     usage:   300 MiB used, 9.7 GiB / 10 GiB avail
>     pgs:     145 active+clean
> ```
> 
> ```
> root@ais3ua9thiem-1:~# tail -f -n 500 /var/log/ceph/ceph-mgr.ais3ua9thiem-1.log
> 2024-11-19T06:04:53.965+0000 74652c0006c0 -1 Traceback (most recent call last):
>   File "/usr/share/ceph/mgr/mgr_module.py", line 513, in check
>     return func(self, *args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/share/ceph/mgr/devicehealth/module.py", line 364, in _do_serve
>     if self.db_ready() and self.enable_monitoring:
>        ^^^^^^^^^^^^^^^
>   File "/usr/share/ceph/mgr/mgr_module.py", line 1282, in db_ready
>     return self.db is not None
>            ^^^^^^^
>   File "/usr/share/ceph/mgr/mgr_module.py", line 1294, in db
>     self._db = self.open_db()
>                ^^^^^^^^^^^^^^
>   File "/usr/share/ceph/mgr/mgr_module.py", line 1275, in open_db
>     self.configure_db(db)
>   File "/usr/share/ceph/mgr/mgr_module.py", line 1249, in configure_db
>     self.load_schema(db)
>   File "/usr/share/ceph/mgr/mgr_module.py", line 1228, in load_schema
>     db.execute('BEGIN;')
> sqlite3.OperationalError: cannot start a transaction within a transaction
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/share/ceph/mgr/devicehealth/module.py", line 408, in serve
>     self._do_serve()
>   File "/usr/share/ceph/mgr/mgr_module.py", line 521, in check
>     self.open_db();
>     ^^^^^^^^^^^^^^
>   File "/usr/share/ceph/mgr/mgr_module.py", line 1275, in open_db
>     self.configure_db(db)
>   File "/usr/share/ceph/mgr/mgr_module.py", line 1249, in configure_db
>     self.load_schema(db)
>   File "/usr/share/ceph/mgr/mgr_module.py", line 1228, in load_schema
>     db.execute('BEGIN;')
> sqlite3.OperationalError: cannot start a transaction within a transaction
> ```
> 
> Once partly rollback with https://github.com/alvistack/ceph-ceph/blob/5ecb79fdfc03f2050b7472f86f4b1335132d6e27/debian/patches/0027-57199-revert-wip-65736-quincy.patch and recompile the packages, now error gone and running normally:
> 
> ```
> root@ais3ua9thiem-1:~# ceph -s
>   cluster:
>     id:     8ef45e11-f70c-5cb6-8c83-b631cde550af
>     health: HEALTH_ERR
>             Module 'devicehealth' has failed: cannot start a transaction within a transaction
>             1 mgr modules have recently crashed
>  
>   services:
>     mon: 2 daemons, quorum ais3ua9thiem-2,ais3ua9thiem-1 (age 12m)
>     mgr: ais3ua9thiem-1(active, since 4m)
>     mds: 1/1 daemons up
>     osd: 1 osds: 1 up (since 12m), 1 in (since 71m)
>  
>   data:
>     volumes: 1/1 healthy
>     pools:   4 pools, 145 pgs
>     objects: 23 objects, 26 KiB
>     usage:   300 MiB used, 9.7 GiB / 10 GiB avail
>     pgs:     145 active+clean
> ```

this one is weird. My current theory is this is a quirk to an older version of sqlite3 I don't understand, specifically with how the database connection is opened (`isolation_level`). Any idea?

**Comment by hswong3i** [comment]
> this one is weird. My current theory is this is a quirk to an older version of sqlite3 I don't understand, specifically with how the database connection is opened (`isolation_level`). Any idea?

I don't really think so, because I didn't patch the sqlite3 package but just using the official Ubuntu [sqlite3 (3.45.1-1ubuntu2)](24.04 https://packages.ubuntu.com/noble/sqlite3), which shouldn't be too old :-(

P.S. Still, once this PR partly reverted, bug gone immediately :-(

**Comment by batrick** [comment]
Thanks to you both. I have opened https://tracker.ceph.com/issues/69912

**Pull request merged**
