### PR TITLE
jewel: rgw: log name instead of id for SystemMetaObj on failure

### PR DESCRIPTION
**Pull request by wido**
http://tracker.ceph.com/issues/18340

@theanalyst: Could you review this one?

### CODE REVIEW

**Comment by theanalyst** [comment]
lgtm

**Comment by smithfarm** [comment]
@wido Could you re-do the cherry-picks with "git cherry-pick -x" and include conflict resolution description?

(Also, we typically do not add additional signed-off-by line to cherry-picks but it's certainly OK if you want to append one at end of the commit message. The part above the "cherry-picked from" line should be just the original commit message without any changes. Sorry if any of this seems unnecessarily bureaucratic!)

**Comment by wido** [comment]
@smithfarm Done (I think)!

**Comment by wido** [comment]
Is this one ready to merge?

**Comment by smithfarm** [comment]
@yehudasa @oritwas This backport was included in the rgw run described at http://tracker.ceph.com/issues/17851#note-33 which was afflicted by valgrind issues. Can you take a look? Suggestions for how to address the valgrind-related test failures would be most welcome.

**Comment by smithfarm** [comment]
This passed RGW runs at http://tracker.ceph.com/issues/17851#note-50 and http://tracker.ceph.com/issues/17851#note-58

**Pull request merged**
