### PR TITLE
[qa/ceph-deploy]:  run create mgr nodes as well

### PR DESCRIPTION
**Pull request by vasukulkarni**
Due to https://github.com/ceph/ceph/pull/16023, the mgr are no longer started alongside monitor nodes.

Testing at: http://pulpito.ceph.com/vasu-2017-07-07_15:53:08-ceph-deploy-master-distro-basic-vps/

Signed-off-by: Vasu Kulkarni <vasu@redhat.com>

### CODE REVIEW

**Comment by vasukulkarni** [comment]
the tests are working, it failed due to the workunit issue which i believe needs update: .workunit.client.0.vpm141.stderr:rbd: error opening default pool 'rbd' 

I will try to add that commit here.

**Comment by liewegas** [comment]
ah, yeah, test should just get an exec line that does 'ceph osd pool create rbd 8' or whatever.

**Comment by vasukulkarni** [comment]
http://pulpito.ceph.com/vasu-2017-07-07_16:27:33-ceph-deploy-master-distro-basic-vps/, the one trusty failure with dmcrypt is unrelated, we didnt have trusty working for long time after mgr changes. there is a other trusty run without dmcrypt is passing now.

**Comment by vasukulkarni** [comment]
retest this please

**Pull request merged**
