### PR TITLE
common: WeightedPriorityQueue Re-Add Round Robin for Classes

### PR DESCRIPTION
**Pull request by rldleblanc**
In some corner cases the WPQ without round robin dequeue of classes caused starvation of other classes. This adds the round robin dequeue of classes back in as intrusive containers.

Signed-off-by: Robert LeBlanc <robert.leblanc@endurance.com>

### CODE REVIEW

**Comment by theanalyst** [comment]
This makes the master builds green again with boost 1.60.0

**Comment by theanalyst** [comment]
Can we get this in before we cut a release to address the failures with boost 1.60

**Comment by kmroz** [comment]
+1 @theanalyst

**Comment by tchaikov** [comment]
@rldleblanc lgtm. did you perform a performance test against this chanceset as you did in #6781 ?

**Comment by rldleblanc** [comment]
@tchaikov I did some tests on a previous version of this code (I pulled it out thinking it might be ok with the round robin between the clients). I had to clean it up a little for this pull request. In that test, I only did the SSDs because the spindles were already maxed out in the STL version. I did have about ~15% decrease in enqueue/dequeue times and 6.41% improvement on 4K SSD and 10.57% increase on SSD 4M.

Today is my last day at Endurance so I won't be able to do any more testing as I won't have access to the gear.

**Comment by theanalyst** [comment]
@tchaikov @liewegas could we get this in one of Jewel RCs, it helps avoid build failures in distros that ship boost 1.60+

**Comment by kmroz** [comment]
@liewegas - Awesome, thanks for adding this. Will make our lives a bit simpler :)
@theanalyst - Thanks for following up.

**Comment by athanatos** [comment]
lgtm

**Pull request merged**
