### PR TITLE
rgw: fix request exception between keepalive and 100-continue

### PR DESCRIPTION
**Pull request by sonetto-lmz**
For a request with a "Expect: 100-continue" header, when an error occurred in rgw before sending a "100 Continue", it will directly return bad response. Because of the the keepalive logic, it will cause the next request exception.

### CODE REVIEW

**Comment by sonetto-lmz** [comment]
like https://tracker.ceph.com/issues/58286，after trying to upload an object of a wrong acl type to a S3-Bucket via PutObject (which returns a 400 Bad Request with error code InvalidArgument as expected) any subsequent request on the same HTTP connection fails.

Although that fix [rgw/beast: fix interaction between keepalive and 100-continue · ceph/ceph@4358cf2 (github.com)](https://github.com/ceph/ceph/commit/4358cf2a6a60d780791322f17cb216addd8ddae6) has been fixed, it does not work for this type

**Comment by sonetto-lmz** [comment]
The test case as follows： 

import s3conn
s3client = s3conn.connect_boto3()
try:
    resp = s3client.put_object(Bucket='test1',Key='string9',Body='asphalts',ACL="privateabc")
except:
    pass
resp = s3client.put_object(Bucket='test1',Key='string111111',Body='asphalts')
    print(resp)

the first request returns a 400 Bad Request with error code InvalidArgument as expected，but the next request returns An error occurred (400) when calling the PutObject operation: Bad Request。

But the rgw log is not the same as follows：
2023-03-27T12:01:53.524+0200 7f7479e8b700  1 ====== starting new request req=0x7f73c2d1c730 =====
2023-03-27T12:01:53.525+0200 7f7479e8b700  1 req 1602985843211682982 0.001000000s op->ERRORHANDLER: err_no=-22 new_err_no=-22
2023-03-27T12:01:53.525+0200 7f7479e8b700  1 ====== req done req=0x7f73c2d1c730 op status=0 http_status=400 latency=0.001000000s ======
2023-03-27T12:01:53.525+0200 7f7479e8b700  1 beast: 0x7f73c2d1c730: 127.0.0.1 - test1 [27/Mar/2023:12:01:53.524 +0200] "PUT /test1/string9 HTTP/1.1" 400 218 - "Boto3/1.17.112 Python/2.7.18 Windows/10 Botocore/1.20.112" - latency=0.001000000s
2023-03-27T12:01:53.537+0200 7f747a68c700  1 ====== starting new request req=0x7f73c2d1c730 =====
2023-03-27T12:01:53.549+0200 7f746de73700  1 ====== req done req=0x7f73c2d1c730 op status=0 http_status=200 latency=0.012000000s ======
2023-03-27T12:01:53.549+0200 7f746de73700  1 beast: 0x7f73c2d1c730: 127.0.0.1 - test1 [27/Mar/2023:12:01:53.537 +0200] "PUT /test1/string111111 HTTP/1.1" 200 8 - "Boto3/1.17.112 Python/2.7.18 Windows/10 Botocore/1.20.112" - latency=0.012000000s

**Comment by sonetto-lmz** [comment]
image

**Comment by sonetto-lmz** [comment]
@cbodley Can you review it for me? thanks

**Comment by cbodley** [comment]
> but the next request returns An error occurred (400) when calling the PutObject operation: Bad Request

@sonetto-lmz running that [s3test case](https://github.com/ceph/s3-tests/pull/504), i'm not seeing a 400 response to that second request. instead, it doesn't look like boto is receiving the full response after it gets the `100 Continue` and sends its request body.. wireshark and the radosgw log both show that the `200 OK` response was sent right after the `100 Continue`, but the boto log shows it hanging for 10+ seconds here before ctrl-c:
```
2023-03-31 17:55:01,121 botocore.endpoint [DEBUG] Sending http request: <AWSPreparedRequest stream_output=False, method=PUT, url=http://localhost:8000/yournamehere-rutu9kcnzy3erp4g-1/key, headers={'User-Agent': b'Boto3/1.24.96 Python/3.11.2 Linux/6.2.8-200.fc37.x86_64 Botocore/1.27.96', 'Content-MD5': b'ar6QJzAXjXZxYCOvCzIC3w==', 'Expect': b'100-continue', 'X-Amz-Date': b'20230331T215501Z', 'X-Amz-Content-SHA256': b'ccecafa07528a4891f609a632f8354daba061d4d41b0467c9d1de8ec24188ac3', 'Authorization': b'AWS4-HMAC-SHA256 Credential=0555b35654ad1656d804/20230331/us-east-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-date, Signature=2de3b1671b904cb9fdf2938fadef3541b4f33129baafc98f8f2bb2dadbd3b1d0', 'amz-sdk-invocation-id': b'906615e6-9239-486c-bbbb-b36afd6ab9e7', 'amz-sdk-request': b'attempt=1', 'Content-Length': '1024'}>
2023-03-31 17:55:01,121 botocore.awsrequest [DEBUG] Waiting for 100 Continue response.
2023-03-31 17:55:01,122 botocore.awsrequest [DEBUG] 100 Continue response seen, now sending request body.
^CERROR: got KeyboardInterrupt signal
2023-03-31 17:55:14,671 botocore.hooks [DEBUG] Event choose-service-name: calling handler <function handle_service_name_alias at 0x7fe2596a1620>
```
if i don't stop it with ctrl-c, boto eventually closes the connection, sends a retry, and succeeds

**Comment by sonetto-lmz** [comment]
> if i don't stop it with ctrl-c, boto eventually closes the connection, sends a retry, and succeeds

@cbodley Because the boto3 itself has a retry function, the whole request process is shown below：
（1）the first request  returns 400
（2）due to the 100 continue, the second request return 400 （bad request）firstly. But infact, the response  for the second request was not returned，leading to Read timeout on endpoint URL
（3）Retry the request，returns 200. The request is reconnected after the disconnection.

```
DEBUG:botocore.awsrequest:Waiting for 100 Continue response.
DEBUG:botocore.awsrequest:Received a non 100 Continue response from the server, NOT sending request body.
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "PUT /test1/string9 HTTP/1.1" 400 218

DEBUG:botocore.awsrequest:Waiting for 100 Continue response.
DEBUG:botocore.awsrequest:100 Continue response seen, now sending request body.
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "PUT /test1/string111111 HTTP/1.1" 400 None

DEBUG:botocore.hooks:Event needs-retry.s3.PutObject: calling handler <botocore.retryhandler.RetryHandler object at 0x7f1b3a944470>
DEBUG:botocore.retryhandler:retry needed, retryable exception caught: Read timeout on endpoint URL: "http://127.0.0.1:8000/test1/string111111"

DEBUG:botocore.awsrequest:Waiting for 100 Continue response.
DEBUG:botocore.awsrequest:100 Continue response seen, now sending request body.
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "PUT /test1/string111111 HTTP/1.1" 200 0
```

**Comment by sonetto-lmz** [comment]
wireshark shows it 
image

**Comment by cbodley** [comment]
> （2）due to the 100 continue, the second request return 400 （bad request）firstly.

i'm not seeing this in wireshark. line 8 captures the 400 response to first request. lines 11 and 13 capture the successful responses to the second request

it's clear that boto is getting that response from line 11, because it prints `100 Continue response seen, now sending request body`. after enabling urllib3 logging, i saw this error message:
```
2023-04-05 12:27:45,447 botocore.awsrequest [DEBUG] Waiting for 100 Continue response.
2023-04-05 12:27:45,448 botocore.awsrequest [DEBUG] 100 Continue response seen, now sending request body.
2023-04-05 12:27:45,455 urllib3.connectionpool [DEBUG] http://localhost:8000 "PUT /yournamehere-mwslk39silws5294-1/key HTTP/1.1" 400 None
2023-04-05 12:27:45,456 urllib3.connectionpool [WARNING] Failed to parse headers (url=http://localhost:8000/yournamehere-mwslk39silws5294-1/key): [MissingHeaderBodySeparatorDefect()], unparsed data: 'HTTP/1.1 200 OK\r\nContent-Length: 0\r\nETag: "6abe902730178d76716023af0b3202df"\r\nAccept-Ranges: bytes\r\nx-amz-request-id: tx000008c70413b89d6a94b-00642da181-1041-default\r\nServer: Ceph Object Gateway (reef)\r\nDate: Wed, 05 Apr 2023 16:27:45 GMT\r\nConnection: Keep-Alive\r\n\r\n'
Traceback (most recent call last):
  File "/home/cbodley/s3-tests/.tox/py/lib/python3.11/site-packages/urllib3/connectionpool.py", line 469, in _make_request
    assert_header_parsing(httplib_response.msg)
  File "/home/cbodley/s3-tests/.tox/py/lib/python3.11/site-packages/urllib3/util/response.py", line 91, in assert_header_parsing
    raise HeaderParsingError(defects=defects, unparsed_data=unparsed_data)
urllib3.exceptions.HeaderParsingError: [MissingHeaderBodySeparatorDefect()], unparsed data: 'HTTP/1.1 200 OK\r\nContent-Length: 0\r\nETag: "6abe902730178d76716023af0b3202df"\r\nAccept-Ranges: bytes\r\nx-amz-request-id: tx000008c70413b89d6a94b-00642da181-1041-default\r\nServer: Ceph Object Gateway (reef)\r\nDate: Wed, 05 Apr 2023 16:27:45 GMT\r\nConnection: Keep-Alive\r\n\r\n'
^CERROR: got KeyboardInterrupt signal
```
that's why boto is logging it as a 400 response and hanging. it looks like this issue is tracked in https://github.com/boto/botocore/issues/1863

do you see anything wrong with radosgw's responses here? if not, i don't think radosgw should close the connection as a workaround for this client bug

**Comment by sonetto-lmz** [comment]
the line 10 is not a normal request，it includes two hypertext transfer protocol. By the java sdk,  the request is normal, so it may   
 be the client bug.
image

**Comment by sonetto-lmz** [comment]
A server that responds with a final status code before reading the entire request content SHOULD indicate whether it intends to close the connection (e.g., see [Section 9.6](https://www.rfc-editor.org/rfc/rfc9112#section-9.6) of [[HTTP/1.1](https://www.rfc-editor.org/rfc/rfc9110.html#HTTP11)]) or continue reading the request content.

**Pull request closed without merging**
