### PR TITLE
cephadm: set --ulimit nofiles with Docker

### PR DESCRIPTION
**Pull request by mnasiadka**
cephadm is setting LimitNOFILE in systemd units, but it doesn't get picked up by Docker.

Fixes: https://tracker.ceph.com/issues/58855

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [X] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [X] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by rkachach** [comment]
The referenced tracker states that:

`Ceph deployed on EL9 is behaving weird with timeouts to any commands after deploying a couple of services (mons, mgrs and a couple of OSDs).`

Are you sure that these timeouts are strictly related to the `nofile` ulimit configuration?

**Comment by rkachach** [comment]
> > The referenced tracker states that:
> > `Ceph deployed on EL9 is behaving weird with timeouts to any commands after deploying a couple of services (mons, mgrs and a couple of OSDs).`
> > Are you sure that these timeouts are strictly related to the `nofile` ulimit configuration?
> 
> Yes, had to do the same for rabbitmq case in OpenStack deployment (see [rabbitmq/rabbitmq-server#5673](https://github.com/rabbitmq/rabbitmq-server/discussions/5673)) - after applying --ulimit - the cluster deploys fine and works fine. Without that - on my test nodes that have limited amount of memory - any ceph commands time out after a couple of minutes after the deployment.

But `nofile` affects the number of open files, not memory! (just to make sure it's what you are trying to increase). That's said the change LGTM as it just applies the same configuration used by cephadm (in the systemd unit configuration).

**Comment by mnasiadka** [comment]
> > > The referenced tracker states that:
> > > `Ceph deployed on EL9 is behaving weird with timeouts to any commands after deploying a couple of services (mons, mgrs and a couple of OSDs).`
> > > Are you sure that these timeouts are strictly related to the `nofile` ulimit configuration?
> > 
> > 
> > Yes, had to do the same for rabbitmq case in OpenStack deployment (see [rabbitmq/rabbitmq-server#5673](https://github.com/rabbitmq/rabbitmq-server/discussions/5673)) - after applying --ulimit - the cluster deploys fine and works fine. Without that - on my test nodes that have limited amount of memory - any ceph commands time out after a couple of minutes after the deployment.
> 
> But `nofile` affects the number of open files, not memory! (just to make sure it's what you are trying to increase). That's said the change LGTM as it just applies the same configuration for Docker used by cephadm (in the systemd unit configuration).

Not trying to increase anything, just writing what is the effect - if that's not set (and the default on RHEL9/Rocky Linux 9/CentOS Stream 9 is around 1 bilion) - ceph is not behaving correctly (maybe it's worth a different bug).

**Comment by mnasiadka** [comment]
Updated tests

**Comment by mnasiadka** [comment]
jenkins retest this please

**Comment by adk3798** [comment]
https://pulpito.ceph.com/adking-2023-03-06_16:09:09-orch:cephadm-wip-adk-testing-2023-03-04-1231-distro-default-smithi/

Failed/dead jobs reruns: https://pulpito.ceph.com/adking-2023-03-06_21:04:02-orch:cephadm-wip-adk-testing-2023-03-04-1231-distro-default-smithi/

After reruns, 6 failed, 2 dead jobs:

- 2 dead jobs were teuthology/infra issues (`Could not get lock /var/lib/dpkg/lock-frontend`, `SSH connection to smithi038 was lost`)
- 1 job failed installing a kernel `[Errno 2] No such file or directory: '/var/cache/dnf/CentOS-BaseOS-7c3d8b2bb640713c/packages/kernel-4.18.0-448.el8.x86_64.rpm'` unrelated to our tests
- 2 instances of https://tracker.ceph.com/issues/58535
- 3 jobs failed due to changes made to `ceph nfs cluster create` command in another PR in the run

Overall, should only block merging for PRs related to nfs

**Review by adk3798 — APPROVED** [review]

**Pull request merged**
