### PR TITLE
luminous: tests: ceph-deploy: create the rbd pool right after install

### PR DESCRIPTION
**Pull request by vasukulkarni**
rbd pool should exist for many rbd tests to work properly, create
the pool right after install is successful.

Signed-off-by: Vasu Kulkarni <vasu@redhat.com>

### CODE REVIEW

**Comment by vasukulkarni** [comment]
@yuriw @smithfarm, sorry, I was wrong in the email thread about this commit already in luminous, some of the failures are due to this missing commit.

**Comment by tchaikov** [comment]
@vasukulkarni could you reference some failures here? a link to a test on pulpito would suffice.

**Comment by vasukulkarni** [comment]
@tchaikov any ceph-admin workunits in this run id: http://pulpito.ceph.com/teuthology-2018-04-21_05:55:02-ceph-deploy-luminous-distro-basic-mira/2424738/

**Comment by tchaikov** [comment]
@vasukulkarni you are referencing a test which includes 71e0922cfad8a05a0642aff1e6fc24024743446f , and the failure was 
```
2018-04-21T10:56:06.270 INFO:tasks.workunit.client.0.mira112.stderr:pool 'rbd' already exists
```

i don't think moving this creating logic into qa/tasks/ceph_deploy.py would help in this case.

**Comment by vasukulkarni** [comment]
@tchaikov this is inline with what we do with ceph.py https://github.com/ceph/ceph/blob/master/qa/tasks/ceph.py#L344-L355 and also its a cherry-pick so anything I would rather fix in master and cherry-pick here rather than direct commit to luminous.

for the ceph-admin failure the workunit is failing with non zero exit code and afaik it is due to that last command it ran(rbd pool create in this case), I can run some tests on this branch to have some proof. Also, I dont like the ceph-admin worunit in general, so I will probably remove that since we have good coverage from other workunits but that will first go to master.

**Comment by vasukulkarni** [comment]
@tchaikov there is something else broken for ceph-disk/bluestore and I think you are right the failure is not due to double create of rbd pool but we still need this backport here 

for the ceph-disk/blustore issue i have filed:
http://tracker.ceph.com/issues/23911

**Comment by alfredodeza** [comment]
@vasukulkarni I don't think what you just linked is a problem in bluestore, it is complaining about seeing a different FSID, which would imply that the disk wasn't cleaned up properly for the test.

**Comment by yuriw** [comment]
@theanalyst can you pls add tracking issue and merge?

@vasukulkarni FYI

**Comment by vasukulkarni** [comment]
thanks!

**Pull request merged**
