### PR TITLE
nautilus: ceph-volume: use the Device.rotational property instead of sys_api 

### PR DESCRIPTION
**Pull request by andrewschoen**
backport of #28060

### CODE REVIEW

**Comment by andrewschoen** [comment]
jenkins test ceph-volume tox

**Comment by andrewschoen** [comment]
jenkins test ceph-volume lvm all

**Comment by andrewschoen** [comment]
jenkins test ceph-volume batch all

**Comment by jarrpa** [comment]
@andrewschoen @alfredodeza Any chance we could push this along somehow, either by retriggering CI or explicitly asking for more reviews?

**Comment by liewegas** [comment]
retest this please

**Comment by liewegas** [comment]
jenkins test ceph-volume batch all

**Comment by liewegas** [comment]
jenkins test ceph-volume lvm all

**Comment by leseb** [comment]
@liewegas Will this make it in time for `14.2.2`?

**Comment by andrewschoen** [comment]
The CI failures so far are all jenkins related.

**Comment by liewegas** [comment]
can a ceph-volume person hit the merge button?

**Pull request merged**
