### PR TITLE
mgr/dashboard: fix API tests: Invalid URL: None/api/auth

### PR DESCRIPTION
**Pull request by alfonsomthd**
Fixes: https://tracker.ceph.com/issues/47052
Signed-off-by: Alfonso Martínez <almartin@redhat.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Review by s0nea — APPROVED** [review]
LGTM

**Review by callithea — APPROVED** [review]

**Comment by callithea** [comment]
- [pkg build](https://shaman.ceph.com/builds/ceph/wip-laura-testing-36736/) [WIP]
- QA run [PENDING]

**Comment by avanthakkar** [comment]
jenkins test dashboard

**Review by epuertat — APPROVED** [review]

**Comment by callithea** [comment]
Latest QA run:
- [pkg build](https://shaman.ceph.com/builds/ceph/wip-laura-testing-36736-2/)
- [QA run](https://pulpito.ceph.com/laura-2020-08-27_09:55:47-rados:dashboard-wip-laura-testing-36736-2-distro-basic-smithi/) [WIP]

**Pull request merged**
