### PR TITLE
Leftover of previous mailmap not merged.

### PR DESCRIPTION
**Pull request by dupont-y**
Leftover of the previous merge request for (mailmap update for 10.2.0 - #8659)
Mails were sent, but I didn't reacted fast enough,  pull request is not mergeable anymore.

This batch should be OK. 
removed initial sorting, & 2 other patch already adressed.
[edit] : only initial sorting is removed.

### CODE REVIEW

**Comment by dupont-y** [comment]
OK. Really, the last 2 patch were mergeable after all.
The file should be sorted once again, but won't do this time - It's probably asking for trouble.
I'll do it once this part is merged.

**Comment by theanalyst** [comment]
lgtm... we can do the sorting as a seperate patch after this one is in? @dupont-y agree?

**Comment by dupont-y** [comment]
Yep.
In fact I'm also preparing 11.0.1 mailmap updates (My fault, I forgot to rotate the wiki :) ). 

Will do sorting as a separate step.

I'd like to see this first step merged, So I could push a part of the update for 11.0.1

**Comment by theanalyst** [comment]
sure makes sense, lgtm

**Comment by dupont-y** [comment]
Le 19/05/16 09:10, Loic Dachary a écrit :
>
> Merged #9182 <https://github.com/ceph/ceph/pull/9182>.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub 
> <https://github.com/ceph/ceph/pull/9182#event-665404396>
>
Thanks. Just pushed mailmap update for 11.0.1 now.
Cheers,

**Comment by dupont-y** [comment]
#9208 is the 2nd round of updates.

**Pull request merged**
