### PR TITLE
cmake: make rgw_common a static library

### PR DESCRIPTION
**Pull request by tchaikov**
## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by tchaikov** [comment]
https://pulpito.ceph.com/kchai-2021-07-25_06:46:11-rados-wip-kefu-testing-2021-07-25-1126-distro-basic-smithi/

**Comment by cbodley** [comment]
@tchaikov it looks like we updated our cmake version to 3.16, and support for `target_link_libaries()` on object libraries was added in 3.12: https://cmake.org/cmake/help/latest/command/target_link_libraries.html#linking-object-libraries

if we can use that, is it still desirable to make `rgw_common` to a static library?

**Comment by tchaikov** [comment]
@cbodley thank you for point me for that document. didn't know that `target_link_libaries()` could also link libraries to object libraries. but i think it *might* be still desirable to use static library. i am not sure how to ensure that the library linked to `rgw_common` get the linkages of `rgw_common` without making them `PUBLIC` of `rgw_common`. even if they could have been `PRIVATE`. IMHO, it's always a good idea to make the linkage dependencies explicit and traceable with minimal efforts.

but if you feel strong on this, i will s/STATIC/OBJECT/ in the commit of "cmake: make rgw_common a static library". and make necessary changes accordingly.

**Review by cbodley — APPROVED** [review]

**Comment by cbodley** [comment]
@tchaikov good points about public vs. private, i'm convinced. i scheduled an rgw suite against your branch at https://pulpito.ceph.com/cbodley-2021-07-27_15:24:05-rgw-wip-kefu-testing-2021-07-25-1126-distro-basic-smithi

**Pull request merged**
