### PR TITLE
doc: Fixed the picture on page http://ceph.com/docs/master/cephfs/

### PR DESCRIPTION
**Pull request by Arshanes**
Fixes: #9174

Signed-off-by Valentin Thomas <valentin.arshanes.thomas@gmail.com>

### CODE REVIEW

**Comment by dachary** [comment]
https://raw.githubusercontent.com/Arshanes/ceph/8385391beb4e53c3644d386b526aa3cff64e4dc9/doc/cephfs/index.rst shows space differences. Could you please make sure you're only using spaces and no tabs ? That's the easiest way to ensure it's properly formatted. Otherwise looks great :-)

**Comment by Arshanes** [comment]
I removed the unexpected tabs. I didn't saw those 3 remaining. It's ok now. :)

**Comment by dachary** [comment]
looks great :-) Could you please squash the two commits into one ?

**Comment by Arshanes** [comment]
Commits are squashed. :)

**Pull request merged**
