### PR TITLE
mds: improve handling of layout bugs

### PR DESCRIPTION
**Pull request by jcsp**
This is a list of stuff that I noticed while investigating https://github.com/ceph/ceph/pull/8455 on the lab cluster.

### CODE REVIEW

**Comment by liewegas** [comment]
Reviewed-by:

**Comment by gregsfortytwo** [comment]
Did you run this code anywhere?

**Comment by jcsp** [comment]
Only locally so far.  It has one new big of test to go with it (which passes) https://github.com/ceph/ceph-qa-suite/pull/936

**Comment by liewegas** [comment]
http://pulpito.ceph.com/sage-2016-04-07_08:34:50-fs-wip-sage-testing---basic-smithi/

**Comment by gregsfortytwo** [comment]
Between http://pulpito.ceph.com/gregf-2016-04-11_16:48:12-fs-greg-fs-testing-411---basic-mira/ and http://pulpito.ceph.com/gregf-2016-04-11_22:01:18-fs-greg-fs-testing-411---basic-mira/, we're in good shape.

**Pull request merged**
