### PR TITLE
luminous: mds: don't check gid when none specified in auth caps

### PR DESCRIPTION
**Pull request by shinobu-x**
http://tracker.ceph.com/issues/22074

### CODE REVIEW

**Comment by shinobu-x** [comment]
test this

**Comment by shinobu-x** [comment]
test this pls

**Comment by shinobu-x** [comment]
test please

**Comment by shinobu-x** [comment]
test this please

**Comment by yuriw** [comment]
[cephfs => wip-yuri3-testing-2018-01-24-1514-luminous](https://trello.com/c/QWO1XUPz/241-cephfs-wip-yuri3-testing-2018-01-24-1514-luminous)

**Pull request merged**
