### PR TITLE
mgr/dashboard: Update formatting of e2e test files

### PR DESCRIPTION
**Pull request by adk3798**
Fixes: https://tracker.ceph.com/issues/40789

Signed-off-by: Adam King <adking@redhat.com>
Signed-off-by: Rafael Quintero <rquinter@redhat.com>

### CODE REVIEW

**Comment by adk3798** [comment]
jenkins test dashboard

**Comment by rafaelquint** [comment]
jenkins test dashboard

**Comment by adk3798** [comment]
jenkins test dashboard

**Comment by adk3798** [comment]
jenkins test dashboard

**Comment by adk3798** [comment]
I'm not sure how to make jenkins run the dashboard tests. If somebody else knows how can you do so when you see this?

Thanks

**Comment by tspmelo** [comment]
jenkins test dashboard

**Comment by tspmelo** [comment]
jenkins test dashboard

**Comment by tspmelo** [comment]
Jenkins seems to have problems with the PR titles.
@callithea Could it be a problem with the length of the title?

**Comment by callithea** [comment]
> Jenkins seems to have problems with the PR titles.
> @callithea Could it be a problem with the length of the title?

@tspmelo yeah, sometimes it's related to the title, but so far I could not figure out what exactly is causing this.

**Comment by ricardoasmarques** [comment]
@adk3798 now that https://github.com/ceph/ceph/pull/28928 has been merged, please rebase and update accordingly. Thanks.

**Comment by adk3798** [comment]
Updated to match changes made in #28928 . Haven't handled the merge conflicts or squashed commits yet but I will do that if the tests pass.

**Comment by adk3798** [comment]
jenkins test make

**Comment by adk3798** [comment]
jenkins test make check

**Comment by adk3798** [comment]
jenkins test dashboard

**Comment by tspmelo** [comment]
Please always resolve conflicts and run the tests locally before pushing or triggering jenkins.

**Comment by adk3798** [comment]
It looks like changes were made to the buckets e2e elsewhere that are causing a merge conflict. I'll try to fix that

**Comment by adk3798** [comment]
Made a mistake rebasing. Trying to fix now

**Pull request merged**
