### PR TITLE
quincy: build: Silence deprecation warnings from OpenSSL 3

### PR DESCRIPTION
**Pull request by idryomov**
Backport https://github.com/ceph/ceph/pull/46330 to quincy to unbreak `make check`:
```
FAILED: src/crimson/CMakeFiles/crimson.dir/__/auth/AuthSessionHandler.cc.o 
/usr/bin/ccache /usr/bin/clang++-14 -DBOOST_ASIO_DISABLE_CONCEPTS -DBOOST_ASIO_DISABLE_THREAD_KEYWORD_EXTENSION -DBOOST_ASIO_USE_TS_EXECUTOR_AS_DEFAULT -DHAVE_CONFIG_H -DSEASTAR_API_LEVEL=6 -DSEASTAR_DEBUG -DSEASTAR_DEBUG_SHARED_PTR -DSEASTAR_DEFAULT_ALLOCATOR -DSEASTAR_SCHEDULING_GROUPS_COUNT=16 -DSEASTAR_SHUFFLE_TASK_QUEUE -DSEASTAR_TYPE_ERASE_MORE -DWITH_SEASTAR=1 -D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE -D_REENTRANT -D_THREAD_SAFE -D__CEPH__ -D__STDC_FORMAT_MACROS -D__linux__ -I/home/jenkins-build/build/workspace/ceph-pull-requests/build/src/include -I/home/jenkins-build/build/workspace/ceph-pull-requests/src -I/home/jenkins-build/build/workspace/ceph-pull-requests/src/seastar/include -I/home/jenkins-build/build/workspace/ceph-pull-requests/build/src/seastar/gen/include -isystem /home/jenkins-build/build/workspace/ceph-pull-requests/build/boost/include -isystem /home/jenkins-build/build/workspace/ceph-pull-requests/build/include -isystem /home/jenkins-build/build/workspace/ceph-pull-requests/src/xxHash -isystem /home/jenkins-build/build/workspace/ceph-pull-requests/src/rapidjson/include -Werror -g -fPIC -Wall -fno-strict-aliasing -fsigned-char -Wtype-limits -Wignored-qualifiers -Wpointer-arith -Werror=format-security -Winit-self -Wno-unknown-pragmas -Wnon-virtual-dtor -Wno-ignored-qualifiers -ftemplate-depth-1024 -Wpessimizing-move -Wredundant-move -Wno-inconsistent-missing-override -Wno-mismatched-tags -Wno-unused-private-field -Wno-address-of-packed-member -Wno-unused-function -Wno-unused-local-typedef -Wno-varargs -Wno-gnu-designator -Wno-missing-braces -Wno-parentheses -Wno-deprecated-register -DCEPH_DEBUG_MUTEX -D_GLIBCXX_ASSERTIONS -fdiagnostics-color=auto -fno-builtin-malloc -fno-builtin-calloc -fno-builtin-realloc -fno-builtin-free -ftemplate-backtrace-limit=0 -Wno-non-virtual-dtor -std=gnu++17 -U_FORTIFY_SOURCE -DSEASTAR_SSTRING -Wno-error=unused-result "-Wno-error=#warnings" -fstack-clash-protection -fsanitize=address -fsanitize=undefined -fno-sanitize=vptr -std=c++17 -MD -MT src/crimson/CMakeFiles/crimson.dir/__/auth/AuthSessionHandler.cc.o -MF src/crimson/CMakeFiles/crimson.dir/__/auth/AuthSessionHandler.cc.o.d -o src/crimson/CMakeFiles/crimson.dir/__/auth/AuthSessionHandler.cc.o -c /home/jenkins-build/build/workspace/ceph-pull-requests/src/auth/AuthSessionHandler.cc
In file included from /home/jenkins-build/build/workspace/ceph-pull-requests/src/auth/AuthSessionHandler.cc:23:
/home/jenkins-build/build/workspace/ceph-pull-requests/src/common/ceph_crypto.h:135:19: error: 'HMAC_CTX_new' is deprecated [-Werror,-Wdeprecated-declarations]
      : mpContext(HMAC_CTX_new()) {
                  ^
/usr/include/openssl/hmac.h:33:1: note: 'HMAC_CTX_new' has been explicitly marked deprecated here
OSSL_DEPRECATEDIN_3_0 HMAC_CTX *HMAC_CTX_new(void);
^
/usr/include/openssl/macros.h:182:49: note: expanded from macro 'OSSL_DEPRECATEDIN_3_0'
#   define OSSL_DEPRECATEDIN_3_0                OSSL_DEPRECATED(3.0)
                                                ^
/usr/include/openssl/macros.h:62:52: note: expanded from macro 'OSSL_DEPRECATED'
#     define OSSL_DEPRECATED(since) __attribute__((deprecated))
                                                   ^
In file included from /home/jenkins-build/build/workspace/ceph-pull-requests/src/auth/AuthSessionHandler.cc:23:
/home/jenkins-build/build/workspace/ceph-pull-requests/src/common/ceph_crypto.h:136:22: error: 'HMAC_Init_ex' is deprecated [-Werror,-Wdeprecated-declarations]
      const auto r = HMAC_Init_ex(mpContext, key, length, type, nullptr);
                     ^
/usr/include/openssl/hmac.h:43:1: note: 'HMAC_Init_ex' has been explicitly marked deprecated here
OSSL_DEPRECATEDIN_3_0 int HMAC_Init_ex(HMAC_CTX *ctx, const void *key, int len,
^
/usr/include/openssl/macros.h:182:49: note: expanded from macro 'OSSL_DEPRECATEDIN_3_0'
#   define OSSL_DEPRECATEDIN_3_0                OSSL_DEPRECATED(3.0)
                                                ^
/usr/include/openssl/macros.h:62:52: note: expanded from macro 'OSSL_DEPRECATED'
#     define OSSL_DEPRECATED(since) __attribute__((deprecated))
                                                   ^
In file included from /home/jenkins-build/build/workspace/ceph-pull-requests/src/auth/AuthSessionHandler.cc:23:
/home/jenkins-build/build/workspace/ceph-pull-requests/src/common/ceph_crypto.h:142:7: error: 'HMAC_CTX_free' is deprecated [-Werror,-Wdeprecated-declarations]
      HMAC_CTX_free(mpContext);
      ^
/usr/include/openssl/hmac.h:35:1: note: 'HMAC_CTX_free' has been explicitly marked deprecated here
OSSL_DEPRECATEDIN_3_0 void HMAC_CTX_free(HMAC_CTX *ctx);
^
/usr/include/openssl/macros.h:182:49: note: expanded from macro 'OSSL_DEPRECATEDIN_3_0'
#   define OSSL_DEPRECATEDIN_3_0                OSSL_DEPRECATED(3.0)
                                                ^
/usr/include/openssl/macros.h:62:52: note: expanded from macro 'OSSL_DEPRECATED'
#     define OSSL_DEPRECATED(since) __attribute__((deprecated))
                                                   ^
In file included from /home/jenkins-build/build/workspace/ceph-pull-requests/src/auth/AuthSessionHandler.cc:23:
/home/jenkins-build/build/workspace/ceph-pull-requests/src/common/ceph_crypto.h:146:35: error: 'HMAC_CTX_get_md' is deprecated [-Werror,-Wdeprecated-declarations]
      const EVP_MD * const type = HMAC_CTX_get_md(mpContext);
                                  ^
/usr/include/openssl/hmac.h:51:1: note: 'HMAC_CTX_get_md' has been explicitly marked deprecated here
OSSL_DEPRECATEDIN_3_0 const EVP_MD *HMAC_CTX_get_md(const HMAC_CTX *ctx);
^
/usr/include/openssl/macros.h:182:49: note: expanded from macro 'OSSL_DEPRECATEDIN_3_0'
#   define OSSL_DEPRECATEDIN_3_0                OSSL_DEPRECATED(3.0)
                                                ^
/usr/include/openssl/macros.h:62:52: note: expanded from macro 'OSSL_DEPRECATED'
#     define OSSL_DEPRECATED(since) __attribute__((deprecated))
                                                   ^
In file included from /home/jenkins-build/build/workspace/ceph-pull-requests/src/auth/AuthSessionHandler.cc:23:
/home/jenkins-build/build/workspace/ceph-pull-requests/src/common/ceph_crypto.h:147:22: error: 'HMAC_Init_ex' is deprecated [-Werror,-Wdeprecated-declarations]
      const auto r = HMAC_Init_ex(mpContext, nullptr, 0, type, nullptr);
                     ^
/usr/include/openssl/hmac.h:43:1: note: 'HMAC_Init_ex' has been explicitly marked deprecated here
OSSL_DEPRECATEDIN_3_0 int HMAC_Init_ex(HMAC_CTX *ctx, const void *key, int len,
^
/usr/include/openssl/macros.h:182:49: note: expanded from macro 'OSSL_DEPRECATEDIN_3_0'
#   define OSSL_DEPRECATEDIN_3_0                OSSL_DEPRECATED(3.0)
                                                ^
/usr/include/openssl/macros.h:62:52: note: expanded from macro 'OSSL_DEPRECATED'
#     define OSSL_DEPRECATED(since) __attribute__((deprecated))
                                                   ^
In file included from /home/jenkins-build/build/workspace/ceph-pull-requests/src/auth/AuthSessionHandler.cc:23:
/home/jenkins-build/build/workspace/ceph-pull-requests/src/common/ceph_crypto.h:154:24: error: 'HMAC_Update' is deprecated [-Werror,-Wdeprecated-declarations]
        const auto r = HMAC_Update(mpContext, input, length);
                       ^
/usr/include/openssl/hmac.h:45:1: note: 'HMAC_Update' has been explicitly marked deprecated here
OSSL_DEPRECATEDIN_3_0 int HMAC_Update(HMAC_CTX *ctx, const unsigned char *data,
^
/usr/include/openssl/macros.h:182:49: note: expanded from macro 'OSSL_DEPRECATEDIN_3_0'
#   define OSSL_DEPRECATEDIN_3_0                OSSL_DEPRECATED(3.0)
                                                ^
/usr/include/openssl/macros.h:62:52: note: expanded from macro 'OSSL_DEPRECATED'
#     define OSSL_DEPRECATED(since) __attribute__((deprecated))
                                                   ^
In file included from /home/jenkins-build/build/workspace/ceph-pull-requests/src/auth/AuthSessionHandler.cc:23:
/home/jenkins-build/build/workspace/ceph-pull-requests/src/common/ceph_crypto.h:162:22: error: 'HMAC_Final' is deprecated [-Werror,-Wdeprecated-declarations]
      const auto r = HMAC_Final(mpContext, digest, &s);
                     ^
/usr/include/openssl/hmac.h:47:1: note: 'HMAC_Final' has been explicitly marked deprecated here
OSSL_DEPRECATEDIN_3_0 int HMAC_Final(HMAC_CTX *ctx, unsigned char *md,
^
/usr/include/openssl/macros.h:182:49: note: expanded from macro 'OSSL_DEPRECATEDIN_3_0'
#   define OSSL_DEPRECATEDIN_3_0                OSSL_DEPRECATED(3.0)
                                                ^
/usr/include/openssl/macros.h:62:52: note: expanded from macro 'OSSL_DEPRECATED'
#     define OSSL_DEPRECATED(since) __attribute__((deprecated))
                                                   ^
7 errors generated.
```

### CODE REVIEW

**Comment by idryomov** [comment]
Apparently, there is more:
```
[419/2580] Building CXX object src/crimson/os/seastore/CMakeFiles/crimson-seastore.dir/transaction.cc.o
FAILED: src/crimson/os/seastore/CMakeFiles/crimson-seastore.dir/transaction.cc.o 
/usr/bin/ccache /usr/bin/clang++-14 -DBOOST_ASIO_DISABLE_CONCEPTS -DBOOST_ASIO_DISABLE_THREAD_KEYWORD_EXTENSION -DBOOST_ASIO_USE_TS_EXECUTOR_AS_DEFAULT -DHAVE_CONFIG_H -DSEASTAR_API_LEVEL=6 -DSEASTAR_DEBUG -DSEASTAR_DEBUG_SHARED_PTR -DSEASTAR_DEFAULT_ALLOCATOR -DSEASTAR_SCHEDULING_GROUPS_COUNT=16 -DSEASTAR_SHUFFLE_TASK_QUEUE -DSEASTAR_TYPE_ERASE_MORE -DWITH_SEASTAR=1 -D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE -D_REENTRANT -D_THREAD_SAFE -D__CEPH__ -D__STDC_FORMAT_MACROS -D__linux__ -I/home/jenkins-build/build/workspace/ceph-pull-requests/build/src/include -I/home/jenkins-build/build/workspace/ceph-pull-requests/src -I/home/jenkins-build/build/workspace/ceph-pull-requests/src/seastar/include -I/home/jenkins-build/build/workspace/ceph-pull-requests/build/src/seastar/gen/include -isystem /home/jenkins-build/build/workspace/ceph-pull-requests/build/boost/include -isystem /home/jenkins-build/build/workspace/ceph-pull-requests/build/include -isystem /home/jenkins-build/build/workspace/ceph-pull-requests/src/xxHash -isystem /home/jenkins-build/build/workspace/ceph-pull-requests/src/rapidjson/include -Werror -g -fPIC -Wall -fno-strict-aliasing -fsigned-char -Wtype-limits -Wignored-qualifiers -Wpointer-arith -Werror=format-security -Winit-self -Wno-unknown-pragmas -Wnon-virtual-dtor -Wno-ignored-qualifiers -ftemplate-depth-1024 -Wpessimizing-move -Wredundant-move -Wno-inconsistent-missing-override -Wno-mismatched-tags -Wno-unused-private-field -Wno-address-of-packed-member -Wno-unused-function -Wno-unused-local-typedef -Wno-varargs -Wno-gnu-designator -Wno-missing-braces -Wno-parentheses -Wno-deprecated-register -DCEPH_DEBUG_MUTEX -D_GLIBCXX_ASSERTIONS -fdiagnostics-color=auto -fno-builtin-malloc -fno-builtin-calloc -fno-builtin-realloc -fno-builtin-free -ftemplate-backtrace-limit=0 -Wno-non-virtual-dtor -std=gnu++17 -U_FORTIFY_SOURCE -DSEASTAR_SSTRING -Wno-error=unused-result "-Wno-error=#warnings" -fstack-clash-protection -fsanitize=address -fsanitize=undefined -fno-sanitize=vptr -std=c++17 -MD -MT src/crimson/os/seastore/CMakeFiles/crimson-seastore.dir/transaction.cc.o -MF src/crimson/os/seastore/CMakeFiles/crimson-seastore.dir/transaction.cc.o.d -o src/crimson/os/seastore/CMakeFiles/crimson-seastore.dir/transaction.cc.o -c /home/jenkins-build/build/workspace/ceph-pull-requests/src/crimson/os/seastore/transaction.cc
In file included from /home/jenkins-build/build/workspace/ceph-pull-requests/src/crimson/os/seastore/transaction.cc:1:
/home/jenkins-build/build/workspace/ceph-pull-requests/src/crimson/os/seastore/transaction.h:44:7: error: 'operator""_format' is deprecated [-Werror,-Wdeprecated-declarations]
      SUBTRACET(seastore_tm, "Found offset {} in write_set: {}", *this, addr, *iter);
      ^
/home/jenkins-build/build/workspace/ceph-pull-requests/src/crimson/os/seastore/logging.h:49:34: note: expanded from macro 'SUBTRACET'
#define SUBTRACET(subname_, ...) SUBLOGT(subname_, seastar::log_level::trace, __VA_ARGS__)
                                 ^
/home/jenkins-build/build/workspace/ceph-pull-requests/src/crimson/os/seastore/logging.h:42:45: note: expanded from macro 'SUBLOGT'
  _LOG<level_>(LOGGER(subname_), "{}({}): " MSG ## _format(FNAME, (void*)&t_ , ##__VA_ARGS__))
                                            ^
<scratch space>:36:35: note: expanded from here
"Found offset {} in write_set: {}"_format
                                  ^
/usr/include/fmt/format.h:3043:1: note: 'operator""_format' has been explicitly marked deprecated here
FMT_DEPRECATED constexpr auto operator"" _format(const char* s, size_t n)
^
/usr/include/fmt/core.h:224:30: note: expanded from macro 'FMT_DEPRECATED'
#    define FMT_DEPRECATED [[deprecated]]
```
cc @rzarzynski @cyx1231st ^^

**Comment by cyx1231st** [comment]
found https://github.com/ceph/ceph/pull/45085

**Review by tchaikov — APPROVED** [review]

**Comment by tchaikov** [comment]
> found #45085

#47603

**Comment by idryomov** [comment]
> > found #45085
> 
> #47603

Pulled in these commits to try and advance "make check"...

**Comment by tchaikov** [comment]
@idryomov i added yet another commit to #47603.

**Comment by tchaikov** [comment]
@idryomov and .. yet another commit! (and i am calling it a night, have a nice $local_time)

**Comment by idryomov** [comment]
jenkins test make check

**Comment by idryomov** [comment]
jenkins test make check

**Comment by idryomov** [comment]
jenkins test make check

**Comment by tchaikov** [comment]
@idryomov the "ceph API test" failure should be fixed by #47602. i collected these fixes in #47616

**Comment by tchaikov** [comment]
https://shaman.ceph.com/builds/ceph/wip-pr-47616-kefu/2975e912f90a207510336c262eca1991e4ec009b/

**Comment by tchaikov** [comment]
https://pulpito.ceph.com/kchai-2022-08-16_07:51:11-rados-quincy-pr-47616-kefu-1-distro-default-smithi/

**Comment by idryomov** [comment]
Unbreaking "make check" here also included backports of #45085, #45198, #45513 and #47568.

**Pull request merged**
