### PR TITLE
Wip write path optimization

### PR DESCRIPTION
**Pull request by somnathr**
Pull request for FileStore write path optimization.

### CODE REVIEW

**Comment by somnathr** [comment]
Sure, will refactor the commits accordingly.

**Comment by somnathr** [comment]
Sage,
I have refactored the commits, please have a look now.

**Comment by liewegas** [comment]
The throttle and (broken out) o_dsync patches look like they're basically ready to go.  I think the do_fast_sync one can be refactored to be much clearer/cleaner, though!

**Comment by athanatos** [comment]
We need to make sure not to merge this until we have done at least power cycle testing.

**Comment by athanatos** [comment]
I spoke to Xinxin and he indicated that they tested this in their lab and got the osd to crash by restarting the osd daemon with entries in the journal.

**Comment by liewegas** [comment]
@somnathr One other thought on the throttling part of this (which is really independen to of the fsync change and should be borken into a separate PR): can we capture the throttle logic into a class?  Probably with a simple interface like DynamicThrottle::calc_wait_time(int cur_percentage_full)?  I suspect we'll want to use this same logic in newstore based on the rocksdb wal log partition utilization (when it is on it's own extra-fast device).

**Comment by somnathr** [comment]
@athanatos Hmm..I am doing that and unable to reproduce. One point though, the sync method can't be changed during restart. They need to do mkfs and recreate the osds fresh to change to the fast sync.

**Comment by somnathr** [comment]
@liewegas Sure, I will comeup with something , that make sense.

**Comment by liewegas** [comment]
will be resubmitted as separate pr's for the throtlte, o_dsync, and fast sync

**Pull request closed without merging**
