### PR TITLE
Add udev rule to set readahead on mapped rbd's

### PR DESCRIPTION
**Pull request by fiskn**
Set to 128kb by default, so no change from current behaviour

### CODE REVIEW

**Comment by wido** [comment]
Thanks!

I think it should go in the udev directory right? Afterwards in debian/rules add it to the proper packages. Same goes for the RPM spec file.

**Comment by idryomov** [comment]
Can you add a comment to the rule file, clarifying that this is just a placeholder and doesn't change the kernel default?

**Comment by fiskn** [comment]
As suggest by @wido closing this PR and moving this into the already packaged /usr/lib/udev/50-rbd.rules

**Comment by fiskn** [comment]
@wido Could you just check this new commit before I do another PR

https://github.com/fiskn/ceph/commit/f4febec9788e5b02bf0fc12f0fd2a193d6e8619e

**Comment by wido** [comment]
@fiskn Thanks! However, if you check the current src directory, there is already a file.

Just check src/udev in the source.

You can squash all the commits and force push. No need for a new PR.

**Comment by fiskn** [comment]
@wido, sorry I don't understand, the udev folder was in the root of the repository and I don't see anything in the src folder relating to udev.

Ok, will do that

**Comment by wido** [comment]
Looks good now! Kan you use git rebase to squash all the commits into on? Since you are only changing one file.

Then do a git force push and you should be good.

**Comment by dillaman** [comment]
lgtm

**Comment by dillaman** [comment]
@fiskn Can you run "git commit --amend -s" to add a signed-off-by line to your commit?

**Comment by idryomov** [comment]
I suggested the explanatory comment, but I now think the rule itself needs to be commented out so that we can actually change the kernel default some day and also to save an unnecessary step on map (rbd map CLI waits for udev).
```
# This is a placeholder, uncomment and edit as necessary
#KERNEL== ...
```

**Comment by dillaman** [comment]
@fiskn ping

**Comment by idryomov** [comment]
@fiskn Could you please add a space between # and This and change commit title to "udev: add krbd readahead placeholder" and I'll merge?

**Pull request merged**
