### PR TITLE
pybind: set language_level for cythonize explicitly

### PR DESCRIPTION
**Pull request by tchaikov**
Compiling rbd.pyx because it changed.
[1/1] Cythonizing rbd.pyx
/usr/lib/python2.7/dist-packages/Cython/Compiler/Main.py:367:
FutureWarning: Cython directive 'language_level' not set, using 2 for
now (Py2). This will change in a later re
lease! File: /var/ssd/ceph/src/pybind/rbd/rbd.pyx
  tree = Parsing.p_module(s, pxd, full_module_name)

this warning is raised by cython 0.29.2

Signed-off-by: Kefu Chai <kchai@redhat.com>

- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by tchaikov** [comment]
see also https://cython.readthedocs.io/en/latest/src/userguide/source_files_and_compilation.html#cythonize-arguments

**Comment by tchaikov** [comment]
```
dpkg: error: dpkg frontend is locked by another process
```

retest this please.

**Comment by liewegas** [comment]
```
04a185c/build/lib/cython_modules/lib.2/rados.so
[ 96%] Built target cython_rados
Scanning dependencies of target cython3_rados

Error compiling Cython file:
------------------------------------------------------------
...
        metadata_dict = '\0'.join(chain.from_iterable(metadata.items()))
        metadata_dict += '\0'
        cdef:
            char *_service = service
            char *_daemon = daemon
            char *_metadata = metadata_dict
                                          ^
------------------------------------------------------------

rados.pyx:1521:43: Unicode objects only support coercion to Py_UNICODE*.

Error compiling Cython file:
------------------------------------------------------------
...
    @requires(('metadata', dict))
    def service_daemon_update(self, status):
        status_dict = '\0'.join(chain.from_iterable(status.items()))
        status_dict += '\0'
        cdef:
            char *_status = status_dict
                                      ^
------------------------------------------------------------

rados.pyx:1533:39: Unicode objects only support coercion to Py_UNICODE*.
Compiling rados.pyx because it changed.
[1/1] Cythonizing rados.pyx
Traceback (most recent call last):
  File "/home/jenkins-build/build/workspace/ceph-dev-new-build/ARCH/x86_64/AVAILABLE_ARCH/x86_64/AVAILABLE_DIST/centos7/DIST/centos7/MACHINE_SIZE/huge/release/14.0.1-3962-g04a185c/rpm/el7/BUILD/ceph-14.0.1-3962-g04a185c/src/pybind/rados/setup.py", line 204, in <module>
    build_dir=os.environ.get("CYTHON_BUILD_DIR", None)
  File "/usr/lib64/python3.4/site-packages/Cython/Build/Dependencies.py", line 877, in cythonize
    cythonize_one(*args)
  File "/usr/lib64/python3.4/site-packages/Cython/Build/Dependencies.py", line 997, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: rados.pyx
make[2]: *** [src/pybind/rados3/CMakeFiles/cython3_rados] Error 1
make[1]: *** [src/pybind/rados3/CMakeFiles/cython3_rados.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```
https://jenkins.ceph.com/job/ceph-dev-new-build/ARCH=x86_64,AVAILABLE_ARCH=x86_64,AVAILABLE_DIST=centos7,DIST=centos7,MACHINE_SIZE=huge/18079//consoleFull

**Comment by tchaikov** [comment]
https://shaman.ceph.com/builds/ceph/wip-set-cython-language-level/c36d0f1a7de4668eb81075e4a94846cf81fc30cd/default/143774/

**Comment by dillaman** [comment]
This PR appears to break Python3 on F29:

> $ ceph health
> Traceback (most recent call last):
>   File "/home/jdillaman/ceph/build/bin/ceph", line 135, in <module>
>     import rados
>   File "rados.pyx", line 329, in init rados
> AttributeError: 'str' object has no attribute 'decode'

Reverting the PR fixes the issue for me.

**Comment by liewegas** [comment]
should we revert in master?

**Comment by dillaman** [comment]
Perhaps it's just me? Did this PR go through a teuthology run? If it's not just me, I'd vote for revert (especially if it's going to be breaking teuthology tests) or fix ASAP before for the RC.

**Comment by neha-ojha** [comment]
revert https://github.com/ceph/ceph/pull/26602

**Pull request merged**
