### PR TITLE
rgw: Externalize Keystone secret key cache TTL

### PR DESCRIPTION
**Pull request by rafaelweingartner**
The Keystone secret key TTL is hardcoded to 300 seconds (5 minutes).
For some use cases, the TTL could be increased, and as a consequence, the number of requests to Keystone is reduced.

Therefore, we propose to externalize this configuration to an option that provides this flexibility to operators. The default is maintained as 300 seconds (5 minutes).

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [x] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [x] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by rafaelweingartner** [comment]
Hello guys, 
Are we missing something for this one to move on?

**Comment by mattbenjamin** [comment]
> Hello guys, Are we missing something for this one to move on?

it needs a review

**Comment by mdw-at-linuxbox** [comment]
This is a fine change, although I think the win will be modest.

Things this change needs:
1/ more doc -- there's a bunch of stuff under doc/radosgw  describing how to configuration various subsystems, and there should be mention of this somewhere in that, perhaps keystone.rst

2/ would be nice to see teuthology tests for this.  Not sure what the options are on this, because waiting even 5 minutes for a token to expire would be awkward.

**Comment by rafaelweingartner** [comment]
Can we reopen this PR. I have just rebased it.

**Comment by rafaelweingartner** [comment]
I have created a new PR as this one could not be re-opened: https://github.com/ceph/ceph/pull/63271

**Pull request closed without merging**
