### PR TITLE
mirroring/MIRRORS: add cn.ceph.com

### PR DESCRIPTION
**Pull request by hjadb**
1. Country: CN
2. Site Name: Alibaba Cloud
3. Mirror Name: mirrors.aliyun.com
4. Categories: http(http://mirrors.aliyun.com/ceph/), https (https://mirrors.aliyun.com/ceph/).
5. Bandwidth: 10000
6. Internet2: No
7. Email: ali-yum@alibaba-inc.com

### CODE REVIEW

**Review by tchaikov — COMMENTED** [review]
why rename this file?

**Comment by hjadb** [comment]
> could you prefix the title of your commit message with the subcomponent your are changing ? see https://github.com/ceph/ceph/blob/master/SubmittingPatches.rst#3-describe-your-changes. in this case, it would be "mirrors".

Is that so?

**Comment by tchaikov** [comment]
> > could you prefix the title of your commit message with the subcomponent your are changing ? see https://github.com/ceph/ceph/blob/master/SubmittingPatches.rst#3-describe-your-changes. in this case, it would be "mirrors".
> 
> 
> 
> Is that so?
> 
> 
> 
> 

not quite. please update the *commit message* also. And could you please reply another comment ?

**Comment by hjadb** [comment]
> why rename this file?

It may have been inadvertently changed. I'm very sorry for causing you some trouble. I don't understand what you said not quite. Please tell me what to do now. Thank you very much.

**Pull request closed without merging**
