### PR TITLE
qa/suites/fs: use bigger cinder volumes

### PR DESCRIPTION
**Pull request by liewegas**
http://tracker.ceph.com/issues/24238

### CODE REVIEW

**Comment by liewegas** [comment]
updated

**Comment by batrick** [comment]
http://pulpito.ceph.com/pdonnell-2018-05-25_04:13:22-fs-mimic-testing-basic-ovh/

@liewegas I may not get around to merging this tomorrow and I'll be on PTO next week. Please merge if the testing looks good to you.

**Comment by batrick** [comment]
actually might need more disk than that since we're running so many services on each node with logging, maybe 100GB?

**Comment by batrick** [comment]
http://pulpito.ceph.com/pdonnell-2018-06-29_21:12:39-fs-wip-pdonnell-pr22165-distro-basic-ovh/

**Comment by batrick** [comment]
Mimic test works now: http://pulpito.ceph.com/pdonnell-2018-07-03_03:40:38-fs-wip-pdonnell-pr22165-mimic-distro-basic-ovh/

**Pull request merged**
