### PR TITLE
rgw: fix BUG#16355

### PR DESCRIPTION
**Pull request by linuxhunter**
fix the BUG#16355 with tenant information on rgw.

### CODE REVIEW

**Comment by mattbenjamin** [comment]
@zaitcev could you scan this?

**Comment by theanalyst** [comment]
I think pin fragmenting should be a separate pr

**Comment by zaitcev** [comment]
I see a couple of issues with the new code.

- It keeps the double-conversion that was mistakenly done in the original code. I think a cleaner approach would be to pass the key to get_existing_bucket_entry() as it's done currently, but rename that argument from bucket_name to bucket_key or such. Then remove the call to get_key_by_bucket_name from the body of get_existing_bucket_entry.

- It adds additional field to serialized structures without any regard for compatibility. I have to wonder if that structure was used by RGW itself. I don't think I could be quite this careless. Actually I left Yehuda's additions intact, but I remember that he was careful with tacking the new fields at the tail and added ifs for structure versions.

**Comment by linuxhunter** [comment]
Hi zaitcev, 
    I had fix the issue 1 by commit 7637d7d2abf6b4edf0fe03f9004bc633e54a0f64, please check it again.

Thanks.

**Comment by zaitcev** [comment]
The double-conversion part now looks good, but what about the incompatible serialization?

**Comment by linuxhunter** [comment]
Hi zaitcev,
    I had try to fix the incompatible serialization on struct cls_user_bucket by commit d45259f, please check it again. 

Thanks.

**Comment by zaitcev** [comment]
My objections were addressed. We still need @yehudasa to take a look, but seems okay. One remaining question - is this the last place that needs fixes? I did not realize the code outside of src/rgw/ would be affected.

Acked-by: Pete Zaitcev <zaitcev@redhat.com>

**Comment by linuxhunter** [comment]
Hi zaitcev, 
    This is the last place that needs to fix for bug#16355.

**Comment by linuxhunter** [comment]
Hi zaitcev,
    Does @yehudasa take a look? What's suggestions?

**Comment by linuxhunter** [comment]
create a new pull request #9938 to replace this which delete the codes unrelated to the bug.

**Pull request closed without merging**
