### PR TITLE
osd: fix full pool side-effects bug

### PR DESCRIPTION
**Pull request by liewegas**

### CODE REVIEW

**Comment by liewegas** [comment]
https://github.com/ceph/ceph-qa-suite/pull/574

**Comment by jdurgin** [comment]
I think we should be dropping the request with no reply since clients resend based on the pool full flag now - this should have been part of 67de12bf9b67c29bf613e831f4146ff9809e42f7

**Comment by liewegas** [comment]
Oh, hmm.. i reproduced on master but not hammer.  It seems like this 
should fix the issue, and hte check in prepare_transaction isn't needed 
at all?

Although.. there  is another open bug that we don't allow rados delete 
when at quota.  So maybe this check is better than the one in handle_op?

**Comment by liewegas** [comment]
Eh, this fix is incomplete.

**Pull request closed without merging**
