### PR TITLE
doc: Introduce the term MON at http://ceph.com/docs/master/rados/

### PR DESCRIPTION
**Pull request by Nairolf21**
http://tracker.ceph.com/issues/10203 Fixes:#10203

Signed-off by : Florian Coste <fcoste21@gmail.com>

### CODE REVIEW

**Comment by dachary** [comment]
Could you please change to 
<pre>
Signed-off by : Florian Coste &lt;fcoste21@gmail.com>
</pre>
note the <> around the mail address :-)

**Comment by Nairolf21** [comment]
I've changed this ;)

**Comment by dachary** [comment]
@Nairolf21 could you please repush the changed commit ?

**Comment by Nairolf21** [comment]
It's okay, I've repushed the commit.

**Comment by dachary** [comment]
Sorry to be picky, but ... could you please update the Signed-off-by to be 
<pre>
Signed-off-by: Florian Coste <fcoste21@gmail.com>
</pre>
Note the **-** between off and by and there is no space before the : Thanks for your patience !

**Comment by Nairolf21** [comment]
Sorry... 
Is it okay, now ?

**Comment by dachary** [comment]
@Nairolf21 there still is a space before the : :-)

**Comment by Nairolf21** [comment]
It should be okay.

**Pull request merged**
