### PR TITLE
os/bluestore: If using sync_wal_apply, no need start wal_tp thread.

### PR DESCRIPTION
**Pull request by majianpeng**
Signed-off-by: Jianpeng Ma <jianpeng.ma@intel.com>

### CODE REVIEW

**Comment by majianpeng** [comment]
@liewegas . hope your comments!

**Comment by liewegas** [comment]
Did you verify the ThreadPool behaves when passed 0 threads?

**Comment by majianpeng** [comment]
@liewegas . For 0 threads, nothing can do. In the end it  killed by suicide timed out.

I try to implement dynamic change wal_apply mode(sync/async). But this will change the order. So i add 	a7a43a5 which don't support change wal_apply mode in running state.

**Comment by liewegas** [comment]
This patch set looks right to me.   Can you rebsae on current master please?

**Pull request merged**
