### PR TITLE
octopus: rgw: add "rgw-orphan-list" tool and "radosgw-admin bucket radoslist ..."

### PR DESCRIPTION
**Pull request by smithfarm**
backport trackers:

* https://tracker.ceph.com/issues/45489
* https://tracker.ceph.com/issues/45487

---

backport of

* https://github.com/ceph/ceph/pull/34148
* https://github.com/ceph/ceph/pull/34086
* https://github.com/ceph/ceph/pull/35009
* https://github.com/ceph/ceph/pull/35245

parent trackers:

* https://tracker.ceph.com/issues/44733
* https://tracker.ceph.com/issues/44734
* https://tracker.ceph.com/issues/45510
* https://tracker.ceph.com/issues/45713

this backport was staged using ceph-backport.sh version 15.1.1.389
find the latest version at https://github.com/ceph/ceph/blob/master/src/script/ceph-backport.sh

### CODE REVIEW

**Comment by smithfarm** [comment]
@ivancich @cbodley Since this is deprecating something in a stable release, would it be prudent to add a `PendingReleaseNote`?

**Comment by ivancich** [comment]
> @ivancich @cbodley Since this is deprecating something in a stable release, would it be prudent to add a `PendingReleaseNote`?

I think that makes sense, @smithfarm.

**Comment by smithfarm** [comment]
> > @ivancich @cbodley Since this is deprecating something in a stable release, would it be prudent to add a `PendingReleaseNote`?
> 
> I think that makes sense, @smithfarm.

Can you write that release note? I'll be happy to add it as a commit here in the PR.

It would make sense to write the release note in the form of a PR targeting master, so the note gets into the pacific release notes as well.

**Comment by smithfarm** [comment]
converted to draft pending `PendingReleaseNote` commit

**Comment by ivancich** [comment]
> converted to draft pending `PendingReleaseNote` commit

Here it is, @smithfarm :

- https://github.com/ceph/ceph/pull/35009
- https://tracker.ceph.com/issues/45510

**Comment by smithfarm** [comment]
Thanks, @ivancich - once that's merged, I'll cherry-pick it into this PR and remove the "draft" status.

**Comment by cbodley** [comment]
@ivancich there was a test_rgw_orphan_list.sh failure in http://pulpito.ceph.com/yuriw-2020-05-19_22:30:41-rgw-wip-yuri5-testing-2020-05-19-2028-octopus-distro-basic-smithi/, can you please take a look?

**Comment by ivancich** [comment]
> @ivancich there was a test_rgw_orphan_list.sh failure in http://pulpito.ceph.com/yuriw-2020-05-19_22:30:41-rgw-wip-yuri5-testing-2020-05-19-2028-octopus-distro-basic-smithi/, can you please take a look?

@cbodley, @smithfarm I believe the issue is that when this CentOS 8 machine was provisioned, it did not produce the fully qualified domain name when `hostname --fqdn` was issued. You can see that in this line here from the teuthology log:

2020-05-20T03:53:03.121 INFO:tasks.workunit.client.0.smithi097.stderr:+ ST_AUTH=http://smithi097:80/auth/v1.0

This issue seems to happen sometimes but not others. I've submitted a sepia tracker for it:

https://tracker.ceph.com/issues/45571

**Comment by ivancich** [comment]
@cbodley, @smithfarm : my sepia tracker (https://tracker.ceph.com/issues/45571) has not been touched yet. How do you think we should handle this? I don't think that it's worth holding up this backport for them to fix that issue. I'm open to work-arounds as well.

**Comment by smithfarm** [comment]
@ivancich You suggested to cherry-pick https://github.com/ceph/ceph/pull/35245 into the nautilus backport (once it's merged). Shouldn't we cherry-pick it into this PR, too?

**Comment by smithfarm** [comment]
#35245 cherry-picked

**Comment by ivancich** [comment]
@smithfarm Thanks for cherry-picking it!

**Comment by yuriw** [comment]
[wip-yuri8-testing-2020-05-28-2043-octopus](https://trello.com/c/PXNU6jIm/919-wip-yuri8-testing-2020-05-28-2043-octopus)

**Pull request merged**
