### PR TITLE
osd/PeeringState: do not trim pg log past last_update_ondisk

### PR DESCRIPTION
**Pull request by xiexingguo**
Trimming past last_update_ondisk would be really bad, e.g.,
a new interval change would cancel&redo a previous op, and if
we trim past last_update_ondisk, there could be potential
object inconsistencies as log merging won't necessarily be able
to find all divergent entries later (we lost track of the unfinished
op that should really be reverted).

Fixes: https://tracker.ceph.com/issues/44532
Signed-off-by: xie xingguo <xie.xingguo@zte.com.cn>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by athanatos** [comment]
I think this is right.

Larger question: why don't the short_pg_log.yaml tests blow this up, like, every time?

Seems to be due to 3 factors:
1) teuthology tests tend to have low outstanding write counts
2) pg splits dilute the writes among more pgs
3) biggest one: short_pg_log.yaml adjusts osd_min_pg_log_entries to 2 (good) but not osd_pg_log_trim_min which defaults to 100.  Thus, even on those tests we're only rarely vulnerable.

I'm going to do a quick run with that rectified (can you add osd_pg_log_trim_min=0 to qa/overrides/short_pg_log.yaml as another commit in this PR?)

**Comment by xiexingguo** [comment]
> 3\. biggest one: short_pg_log.yaml adjusts osd_min_pg_log_entries to 2 (good) but not osd_pg_log_trim_min which defaults to 100.

yeah, good catch!



> I'm going to do a quick run with that rectified (can you add osd_pg_log_trim_min=0 to qa/overrides/short_pg_log.yaml as another commit in this PR?)

@athanatos Added!

**Comment by xiexingguo** [comment]
Aah, I see you last two qa runs are both green.

Instead of running the short_pg_log script, maybe we can instead re-run the original test case that expose the bug multiple times?

```
rados/singleton/{all/osd-recovery.yaml msgr-failures/few.yaml msgr/async-v1only.yaml
    objectstore/bluestore-bitmap.yaml rados.yaml supported-random-distro$/{rhel_latest.yaml}}
```

It looks like to me the suspicious trigger might be related to 
```
https://github.com/ceph/ceph/blob/master/qa/suites/rados/singleton/all/osd-recovery.yaml#L29
https://github.com/ceph/ceph/blob/master/qa/suites/rados/singleton/all/osd-recovery.yaml#L30 
```

I think we should put the osd_pg_log_trim_min=0 exerciser here too.

**Comment by xiexingguo** [comment]
Aah, I see you last two qa runs (with/without the fixer) are both green.

Instead of running the short_pg_log script, maybe we can re-run the original test case that expose the bug multiple times?

```
rados/singleton/{all/osd-recovery.yaml msgr-failures/few.yaml msgr/async-v1only.yaml
    objectstore/bluestore-bitmap.yaml rados.yaml supported-random-distro$/{rhel_latest.yaml}}
```

It looks like to me the suspicious trigger might be related to 

https://github.com/ceph/ceph/blob/master/qa/suites/rados/singleton/all/osd-recovery.yaml#L29
https://github.com/ceph/ceph/blob/master/qa/suites/rados/singleton/all/osd-recovery.yaml#L30 


I think we should put the osd_pg_log_trim_min=0 exerciser here too.

**Comment by athanatos** [comment]
@xiexingguo https://github.com/athanatos/ceph/tree/sjust/wip-44532 has two extra patches adding an assert and a higher concurrency rados bench test to trigger this bug.

**Comment by xiexingguo** [comment]
Pulled the reproducer down!

@athanatos Thanks, Sam. Great job!

**Comment by xiexingguo** [comment]
@athanatos Shall we target this one to Octopus? I think this one is of low priority.

**Comment by athanatos** [comment]
@xiexingguo Yep, I think it needs to go back to nautilus and perhaps one more as well.

**Comment by xiexingguo** [comment]
@athanatos Updated. Mind approving too?

**Comment by tchaikov** [comment]
http://pulpito.ceph.com/kchai-2020-03-24_03:31:20-rados-wip-kefu-testing-2020-03-23-2313-distro-basic-smithi/

**Pull request merged**
