### PR TITLE
client: use deep-copy when setting permission during make_request

### PR DESCRIPTION
**Pull request by Mer1997**
We need MetaRequest's perms.gids keeps longer than syscal if mds reboot. 
When mds reboot we need to rebuild MClientRequest with MetaRequest.

Fixes: https://tracker.ceph.com/issues/59514
Signed-off-by: Mer Xuanyi [xuanyi.meng@xtaotech.com](mailto:xuanyi.meng@xtaotech.com)

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by Mer1997** [comment]
jenkins test make check arm64

**Comment by vshankar** [comment]
@Mer1997 Curious if you ran into an client side issue that prompted this change?

**Comment by Mer1997** [comment]
> @Mer1997 Curious if you ran into an client side issue that prompted this change?

Not really 😂, it's detected by address sanitizer.

**Review by vshankar — APPROVED** [review]
LGTM

**Comment by vshankar** [comment]
@Mer1997 Please change commit message to "client: use deep-copy when setting permission during make_request".

**Comment by Mer1997** [comment]
jenkins test make check arm64

**Comment by vshankar** [comment]
jenkins test make check arm64

**Comment by Mer1997** [comment]
jenkins test make check

**Comment by Mer1997** [comment]
jenkins test make check arm64

**Comment by lxbsz** [comment]
> We need MetaRequest's perms.gids keeps longer than syscal if mds reboot. When mds reboot we need to rebuild MClientRequest with MetaRequest.
> 
> Fixes: https://tracker.ceph.com/issues/59514 

LGTM.

BTW, could you update the commit comment by add the above `Fixes: ....` ? Which will be easier to track the issue in future ?



> Signed-off-by: Mer Xuanyi [xuanyi.meng@xtaotech.com](mailto:xuanyi.meng@xtaotech.com)

**Comment by Mer1997** [comment]
jenkins test make check arm64

**Comment by Mer1997** [comment]
jenkins test make check arm64

**Comment by Mer1997** [comment]
jenkins test make check arm64

**Comment by Mer1997** [comment]
jenkins test make check

**Comment by Mer1997** [comment]
jenkins test make check

**Comment by Mer1997** [comment]
jenkins test make check

**Comment by Mer1997** [comment]
jenkins test make check

**Comment by Mer1997** [comment]
jenkins test make check

**Comment by Mer1997** [comment]
jenkins test make check

**Comment by Mer1997** [comment]
jenkins test make check

**Comment by Mer1997** [comment]
jenkins test make check

**Comment by Mer1997** [comment]
jenkins test make check

**Comment by Mer1997** [comment]
jenkins test make check

**Review by lxbsz — APPROVED** [review]
LGTM.

**Comment by vshankar** [comment]
fs suite run: https://pulpito.ceph.com/vshankar-2023-05-08_02:52:50-fs-wip-vshankar-testing-20230507.032515-testing-default-smithi/

**Comment by vshankar** [comment]
https://pulpito.ceph.com/vshankar-2023-05-09_07:29:33-fs-wip-vshankar-testing-20230509.054005-testing-default-smithi/

(after removing a problematic PR)

**Comment by vshankar** [comment]
https://tracker.ceph.com/projects/cephfs/wiki/Main#11-May-2023

**Pull request merged**
