### PR TITLE
doc: remove mentions about mon_osd_min_down_reports

### PR DESCRIPTION
**Pull request by baruza**
Signed-off-by: Bara Ancincova (bara@redhat.com)

http://tracker.ceph.com/issues/19016

### CODE REVIEW

**Comment by tchaikov** [comment]
@baruza could you revise the commit message so it looks like
```
doc: remove mentions about mon_osd_min_down_reports

Fixes: http://tracker.ceph.com/issues/19016
Signed-off-by: Bara Ancincova <bara@redhat.com>
```
and repush?

**Comment by tchaikov** [comment]
```
ceph_test_objectstore: /home/jenkins-build/build/workspace/ceph-pull-requests/src/test/objectstore/store_test.cc:3209: virtual void SyntheticWorkloadState::C_SyntheticOnReadable::finish(int): Assertion `bl_eq(state->contents[hoid].data, r2)' failed.
*** Caught signal (Aborted) **
 in thread 7f4efb0ed700 thread_name:fn_anonymous
 ceph version 12.0.0-609-g0774c94 (0774c9475e15f99f02994a23e9afac6503d80d79)
 1: (()+0x46df27) [0x7f4f09347f27]
 2: (()+0x10330) [0x7f4efffc7330]
 3: (gsignal()+0x37) [0x7f4efe605c37]
 4: (abort()+0x148) [0x7f4efe609028]
 5: (()+0x2fbf6) [0x7f4efe5febf6]
 6: (()+0x2fca2) [0x7f4efe5feca2]
 7: (SyntheticWorkloadState::C_SyntheticOnReadable::finish(int)+0x367) [0x7f4f09125e77]
 8: (Context::complete(int)+0x9) [0x7f4f09101ea9]
 9: (Finisher::finisher_thread_entry()+0x1de) [0x7f4f0047c9fe]
 10: (()+0x8184) [0x7f4efffbf184]
 11: (clone()+0x6d) [0x7f4efe6c937d]
2017-02-21 12:01:22.565997 7f4efb0ed700 -1 *** Caught signal (Aborted) **
 in thread 7f4efb0ed700 thread_name:fn_anonymous
```

**Comment by baruza** [comment]
Hi @tchaikov, done :) I'll make sure to follow the conventions for commit messages next time.

**Comment by tchaikov** [comment]
@baruza next time, you could push to your own remote repo for creating PR from there. the ceph/ceph repo is used for releasing and master only now.

**Comment by baruza** [comment]
@tchaikov, ok so the preferred way is to fork the master repo? I thought it is sufficient to work in a topic branches. Nevermind, will work in my own fork next time :)

**Comment by tchaikov** [comment]
@baruza it's a good practice to work in a topic branch, and you branch name "wip-19016-remove-mon_osd_min_down_reports" is very descriptive, which is good. what i'd recommend is to create a branch in your own repo next time.

**Pull request merged**
