### PR TITLE
client: fix setting empty default ACL

### PR DESCRIPTION
**Pull request by ukernel**
'cp -a ...' may call setxattr(..., "system.posix_acl_default",
"\2\0\0", 4, 0). The ACL xattr only include ACL header. Client
should remove ACL in this case.

Signed-off-by: Yan, Zheng <zyan@redhat.com>

### CODE REVIEW

**Comment by jcsp** [comment]
:+1: Reviewed-by

**Comment by jcsp** [comment]
@ukernel is this covered by any tests or is there one we should add?

**Comment by jcsp** [comment]
(this is good to go once it has a test)

**Comment by ErwanAliasr1** [comment]
I submit the job again and it passed but didn't update the github status : https://jenkins.ceph.com/job/ceph-pull-requests/6521/console

**Pull request merged**
