### PR TITLE
luminous: mds: MDBalancer::try_rebalance() may stop prematurely

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/32084

### CODE REVIEW

**Comment by yuriw** [comment]
[wip-yuri2-testing-2018-09-13-1634-luminous](https://trello.com/c/kzbWeNmq/403-wip-yuri2-testing-2018-09-13-1634-luminous)

**Comment by batrick** [comment]
Needs rebase

**Comment by batrick** [comment]
Needs rebase. Testing passed.

**Comment by yuriw** [comment]
@smithfarm pls merged after rebase

**Pull request merged**
