### PR TITLE
quincy: mon,auth,cephadm: support auth key rotation

### PR DESCRIPTION
**Pull request by rzarzynski**
This is the quincy backport of the PR https://github.com/ceph/ceph/pull/43655.

Backport ticket: https://tracker.ceph.com/issues/57541.

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Review by adk3798 — APPROVED** [review]

**Review by anthonyeleven — APPROVED** [review]

**Comment by adk3798** [comment]
https://pulpito.ceph.com/adking-2022-12-07_15:13:51-orch:cephadm-wip-adk3-testing-2022-12-05-1317-quincy-distro-default-smithi/

- 2 failures in test_cephad task due to a master -> main change not having been backported yet (backport is now open but was not
- 1 odd failure where test_nfs timed out, seemingly because of an issue with deployment of an mds service
```
2022-12-07T00:00:14.679 INFO:journalctl@ceph.mgr.a.smithi055.stdout:Dec 07 00:00:14 smithi055 conmon[119979]: 2022-12-07T00:00:14.397+0000 7fe452257700 -1 log_channel(cephadm) log [ERR] : Failed to apply mds.a spec MDSSpec.from_json(yaml.safe_load('''service_type: mds
2022-12-07T00:00:14.679 INFO:journalctl@ceph.mgr.a.smithi055.stdout:Dec 07 00:00:14 smithi055 conmon[119979]: service_id: a
2022-12-07T00:00:14.680 INFO:journalctl@ceph.mgr.a.smithi055.stdout:Dec 07 00:00:14 smithi055 conmon[119979]: service_name: mds.a
2022-12-07T00:00:14.680 INFO:journalctl@ceph.mgr.a.smithi055.stdout:Dec 07 00:00:14 smithi055 conmon[119979]: placement:
2022-12-07T00:00:14.680 INFO:journalctl@ceph.mgr.a.smithi055.stdout:Dec 07 00:00:14 smithi055 conmon[119979]:   count: 2
2022-12-07T00:00:14.680 INFO:journalctl@ceph.mgr.a.smithi055.stdout:Dec 07 00:00:14 smithi055 conmon[119979]: ''')): cephadm exited with an error code: 1, stderr: ERROR: Daemon not found: mds.a.smithi055.ystyid. See `cephadm ls`
2022-12-07T00:00:14.681 INFO:journalctl@ceph.mgr.a.smithi055.stdout:Dec 07 00:00:14 smithi055 conmon[119979]: Traceback (most recent call last):
2022-12-07T00:00:14.681 INFO:journalctl@ceph.mgr.a.smithi055.stdout:Dec 07 00:00:14 smithi055 conmon[119979]:   File "/usr/share/ceph/mgr/cephadm/serve.py", line 508, in _apply_all_services
2022-12-07T00:00:14.681 INFO:journalctl@ceph.mgr.a.smithi055.stdout:Dec 07 00:00:14 smithi055 conmon[119979]:     if self._apply_service(spec):
2022-12-07T00:00:14.681 INFO:journalctl@ceph.mgr.a.smithi055.stdout:Dec 07 00:00:14 smithi055 conmon[119979]:   File "/usr/share/ceph/mgr/cephadm/serve.py", line 837, in _apply_service
2022-12-07T00:00:14.682 INFO:journalctl@ceph.mgr.a.smithi055.stdout:Dec 07 00:00:14 smithi055 conmon[119979]:     self._remove_daemon(d.name(), d.hostname)
2022-12-07T00:00:14.682 INFO:journalctl@ceph.mgr.a.smithi055.stdout:Dec 07 00:00:14 smithi055 conmon[119979]:   File "/usr/share/ceph/mgr/cephadm/serve.py", line 1245, in _remove_daemon
2022-12-07T00:00:14.682 INFO:journalctl@ceph.mgr.a.smithi055.stdout:Dec 07 00:00:14 smithi055 conmon[119979]:     host, name, 'rm-daemon', args))
2022-12-07T00:00:14.683 INFO:journalctl@ceph.mgr.a.smithi055.stdout:Dec 07 00:00:14 smithi055 conmon[119979]:   File "/usr/share/ceph/mgr/cephadm/module.py", line 605, in wait_async
2022-12-07T00:00:14.683 INFO:journalctl@ceph.mgr.a.smithi055.stdout:Dec 07 00:00:14 smithi055 conmon[119979]:     return self.event_loop.get_result(coro)
2022-12-07T00:00:14.683 INFO:journalctl@ceph.mgr.a.smithi055.stdout:Dec 07 00:00:14 smithi055 conmon[119979]:   File "/usr/share/ceph/mgr/cephadm/ssh.py", line 48, in get_result
2022-12-07T00:00:14.683 INFO:journalctl@ceph.mgr.a.smithi055.stdout:Dec 07 00:00:14 smithi055 conmon[119979]:     return asyncio.run_coroutine_threadsafe(coro, self._loop).result()
2022-12-07T00:00:14.684 INFO:journalctl@ceph.mgr.a.smithi055.stdout:Dec 07 00:00:14 smithi055 conmon[119979]:   File "/lib64/python3.6/concurrent/futures/_base.py", line 432, in result
2022-12-07T00:00:14.684 INFO:journalctl@ceph.mgr.a.smithi055.stdout:Dec 07 00:00:14 smithi055 conmon[119979]:     return self.__get_result()
2022-12-07T00:00:14.684 INFO:journalctl@ceph.mgr.a.smithi055.stdout:Dec 07 00:00:14 smithi055 conmon[119979]:   File "/lib64/python3.6/concurrent/futures/_base.py", line 384, in __get_result
2022-12-07T00:00:14.684 INFO:journalctl@ceph.mgr.a.smithi055.stdout:Dec 07 00:00:14 smithi055 conmon[119979]:     raise self._exception
2022-12-07T00:00:14.685 INFO:journalctl@ceph.mgr.a.smithi055.stdout:Dec 07 00:00:14 smithi055 conmon[119979]:   File "/usr/share/ceph/mgr/cephadm/serve.py", line 1391, in _run_cephadm
2022-12-07T00:00:14.685 INFO:journalctl@ceph.mgr.a.smithi055.stdout:Dec 07 00:00:14 smithi055 conmon[119979]:     f'cephadm exited with an error code: {code}, stderr: {err}')
2022-12-07T00:00:14.685 INFO:journalctl@ceph.mgr.a.smithi055.stdout:Dec 07 00:00:14 smithi055 conmon[119979]: orchestrator._interface.OrchestratorError: cephadm exited with an error code: 1, stderr: ERROR: Daemon not found: mds.a.smithi055.ystyid. See `cephadm ls`
```
issue was not reproducible, other two test_nfs tests in the run + 5 reruns of the exact test that failed all passed (https://pulpito.ceph.com/adking-2022-12-07_15:13:51-orch:cephadm-wip-adk3-testing-2022-12-05-1317-quincy-distro-default-smithi/). 

Overall, nothing here that should block merging I think. First two are expected and last failure looks unrelated to PRs in the run (and obviously doesn't happen in most runs). Will watch in case I see it again.

**Comment by adk3798** [comment]
jenkins retest this please

**Comment by adk3798** [comment]
@yuriw can you include this PR next time you do a RADOS run on quincy? The orch run looked good, so just needs RADOS now. Thanks.

**Comment by ljflores** [comment]
Rados suite review: https://pulpito.ceph.com/?branch=wip-yuri7-testing-2023-01-30-1510-quincy

Failures, unrelated:
    1. https://tracker.ceph.com/issues/58585
    2. https://tracker.ceph.com/issues/58146
    3. https://tracker.ceph.com/issues/58560
    4. https://tracker.ceph.com/issues/58265

Details:
    1. rook: failed to pull kubelet image - Ceph - Orchestrator
    2. test_cephadm.sh: Error: Error initializing source docker://quay.ceph.io/ceph-ci/ceph:master - Ceph - Orchestrator
    3. test_envlibrados_for_rocksdb.sh failed to subscrib repo - Ceph
    4. TestClsRbd.group_snap_list_max_read failure during upgrade/parallel tests - Ceph - RBD

**Pull request merged**
