### PR TITLE
os/FileJournal: Fix journal write fail, align for direct io

### PR DESCRIPTION
**Pull request by liewegas**
http://tracker.ceph.com/issues/12945

when config journal_zero_on_create true, osd mkfs will fail when zeroing journal.
journal open with O_DIRECT, buf should align with blocksize.

Backport: giant, firefly, dumpling
Signed-off-by: Xie Rui <875016668@qq.com>
Reviewed-by: Sage Weil <sage@redhat.com>
(cherry picked from commit 80473f63853593e53d72f17c098152caf17f5e9e)

Firefly backport: http://tracker.ceph.com/issues/12945
(giant and dumpling are EOL)

### CODE REVIEW

**Comment by dachary** [comment]
What is the corresponding issue ? There does not seem to be a matching pull request.

**Comment by smithfarm** [comment]
@dachary: http://tracker.ceph.com/issues/12945

**Comment by dachary** [comment]
@smithfarm reading the comment helps... sorry for the noise ;-)

**Comment by smithfarm** [comment]
@dachary Actually, I created the issue and added it to the comment :-)

**Comment by dmick** [comment]
@dachary, is this ready to go?

**Comment by dachary** [comment]
@dmick @smithfarm knows how much testing it saw.

**Comment by smithfarm** [comment]
@dmick I would not say it is ready yet. It was in the last round of firefly integration tests. The rados suite results are here: http://tracker.ceph.com/issues/11644#note-102

I am scheduling suites for a new round, now.

**Comment by smithfarm** [comment]
New rados suite: http://tracker.ceph.com/issues/11644#note-110

**Pull request merged**
