### PR TITLE
jewel: rbd: Enabling mirroring for a pool with clones may fail

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/19228
http://tracker.ceph.com/issues/19808

### CODE REVIEW

**Comment by smithfarm** [comment]
@dillaman I ran this PR and a couple other RBD jewel PRs [1] through an RBD suite at http://tracker.ceph.com/issues/19538#note-47 and was suprised to see 8 failures, all of them appearing to be a failed TestLibRBD.Mirror test. Can you help debug?

[1] http://tracker.ceph.com/issues/19538#note-38

**Comment by dillaman** [comment]
@smithfarm Revert 83bae8bb from wip-jewel-backports for now -- the TestLibRBD.Mirror test cases uses a hard-coded image name

**Comment by smithfarm** [comment]
* cherry pick 8f72e74 into this PR
* add http://tracker.ceph.com/issues/19808 to the PR description here
* edit description of http://tracker.ceph.com/issues/19808 so it points to this PR
* close #15462

**Comment by amitkumar50** [comment]
@smithfarm Nathan Sorry to say But if you can limit Title for future PRs to be inside 50 characters?
https://github.com/ceph/ceph/blob/master/SubmittingPatches.rst#title-of-pull-requests-and-title-of-commits

**Comment by smithfarm** [comment]
The following three rbd-related PRs were included in a recent jewel integration branch. An rbd suite was run on said branch, and it failed rather spectacularly: http://pulpito.front.sepia.ceph.com/smithfarm-2017-08-21_20:07:45-rbd-wip-jewel-backports-distro-basic-smithi/

Pushed `wip-19228-jewel` to ceph-ci with intent tol run an rbd suite on this single PR.

**Comment by smithfarm** [comment]
@dillaman @trociny This passed an rbd suite at http://tracker.ceph.com/issues/20613#note-12

**Pull request merged**
