### PR TITLE
os/bluestore: Set new compression blob size to 64K

### PR DESCRIPTION
**Pull request by aclamk**
Based on compression test results (no detailed methodology report yet, data pre-processed in:
https://docs.google.com/spreadsheets/d/1zIlu1aZFodgmZOJm7VboJBbteoERVtJtx8AY1KzKmQE )
I would like to propose change of compression blob size to 64K.

Graphs show evolution of cluster. X-axis is 8 steps of testing. 
Test is 4-64k random read/write that spans 600MB dataset of 150k objects each 4MB.

It shows significant reduction in space used:
used_space

And still has reasonable impact on performance:
write_iops
read_iops

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by ifed01** [comment]
@aclamk - were your benchmarks run against flash of spinner drives?

**Comment by ifed01** [comment]
and it looks like the graphs lack the results for the original min blob size = 8K

**Comment by markhpc** [comment]
I'm open either way. I'll trust @ifed01's judgment more than my own on this one!

**Comment by tchaikov** [comment]
- https://pulpito.ceph.com/kchai-2021-03-06_09:19:54-rados-wip-kefu-testing-2021-03-06-1553-distro-basic-smithi/
- https://pulpito.ceph.com/kchai-2021-03-07_12:30:50-rados-wip-kefu-testing-2021-03-07-1842-distro-basic-smithi/


failures tracked by

- https://tracker.ceph.com/issues/49638
- https://tracker.ceph.com/issues/49484

**Review by markhpc — APPROVED** [review]
Talked to Josh about this, looks very reasonable to me.

**Review by ifed01 — APPROVED** [review]

**Comment by sseshasa** [comment]
Teuthology Test Results:

 http://pulpito.front.sepia.ceph.com/yuriw-2021-12-07_16:02:55-rados-wip-yuri11-testing-2021-12-06-1619-distro-default-smithi/

**Unrelated Failures:**

1. 16/22 jobs related to mds_upgrade_sequence failed with the  errors:
    Predominant Failure reason:
    Command failed on smithi001 with status 32: 'sudo nsenter --net=/var/run/netns/ceph-ns--home-ubuntu-cephtest-mnt.0 adjust-ulimits ceph-coverage /home/ubuntu/cephtest/archive/coverage /bin/mount -t ceph :/ /home/ubuntu/cephtest/mnt.0 -v -o norequire_active_mds,conf=/etc/ceph/ceph.conf,norbytes,name=0,mds_namespace=cephfs,nofallback'

    Existing tracker: https://tracker.ceph.com/issues/53487

2. http://pulpito.front.sepia.ceph.com/yuriw-2021-12-07_16:02:55-rados-wip-yuri11-testing-2021-12-06-1619-distro-default-smithi/6550482
   http://pulpito.front.sepia.ceph.com/yuriw-2021-12-07_16:02:55-rados-wip-yuri11-testing-2021-12-06-1619-distro-default-smithi/6550909
    Command failed (workunit test cephadm/test_dashboard_e2e.sh) on smithi101 with status 1
    New tracker created: https://tracker.ceph.com/issues/53499

3. http://pulpito.front.sepia.ceph.com/yuriw-2021-12-07_16:02:55-rados-wip-yuri11-testing-2021-12-06-1619-distro-default-smithi/6550484
    [Errno 2] Cannot find file on the remote 'ubuntu@smithi027.front.sepia.ceph.com': 'rook/cluster/examples/kubernetes/ceph/operator.yaml' 
    New tracker created: https://tracker.ceph.com/issues/53501

4. http://pulpito.front.sepia.ceph.com/yuriw-2021-12-07_16:02:55-rados-wip-yuri11-testing-2021-12-06-1619-distro-default-smithi/6550873
    Valgrind error during handle_recovery_delete()
    Existing tracker: https://tracker.ceph.com/issues/52124


5. http://pulpito.front.sepia.ceph.com/yuriw-2021-12-07_16:02:55-rados-wip-yuri11-testing-2021-12-06-1619-distro-default-smithi/6550960
    ceph_abort_msg("block checksum mismatch: stored = 632344828, computed = 928675071  in db/000047.sst offset 264241 size 3745")
    Existing tracker: https://tracker.ceph.com/issues/47453

**Pull request merged**
