### PR TITLE
run-make: do not pass '-DWITH_FMT_VERSION' to cmake

### PR DESCRIPTION
**Pull request by Svelar**
Clean up this opt because 'WITH_FMT_VERSION' is removed from src/CMakeLists.txt in #54216 
See: https://github.com/adamemerson/ceph/blob/686dd3d838b6de6bf1101f0b61f729426b0bccad/src/CMakeLists.txt

Fixes: https://tracker.ceph.com/issues/65067

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Comment by rosinL** [comment]
nit, should `s/_DWITH_FMT_VERSION/-DWITH_FMT_VERSION/` in commit log

**Comment by Svelar** [comment]
> nit, should `s/_DWITH_FMT_VERSION/-DWITH_FMT_VERSION/` in commit log

Fixed

**Comment by rosinL** [comment]
lgtm

**Review by rosinL — APPROVED** [review]

**Comment by dmick** [comment]
@adamemerson please have a look

**Review by tchaikov — COMMENTED** [review]
> run-make: clean up '-DWITH_FMT_VERSION'

could you please make the title more explicit, like

> run-make: do not pass '-DWITH_FMT_VERSION' to cmake

and the body of commit message asks reviewer to guess what you intend to do

```
> This opt should be removed because of #https://github.com/ceph/ceph/pull/54216/files#:~:text=option(WITH_SYSTEM_FMT%20%22build,endif()

Fixes: https://tracker.ceph.com/issues/65067
Signed-off-by: Rongqi Sun <sunrongqi@huawei.com>
```

by referencing a URL. please reference a git sha1, or a file in the repo when possible. and put the rationales **in** the commit message. developer's time is precious, unless necessary, i don't want to fire up a browser with javescript enabled, and wait for it, when checking a commit message.

**Comment by Svelar** [comment]
> > run-make: clean up '-DWITH_FMT_VERSION'
> 
> could you please make the title more explicit, like
> 
> > run-make: do not pass '-DWITH_FMT_VERSION' to cmake
> 
> and the body of commit message asks reviewer to guess what you intend to do
> 
> ```
> > This opt should be removed because of #https://github.com/ceph/ceph/pull/54216/files#:~:text=option(WITH_SYSTEM_FMT%20%22build,endif()
> 
> Fixes: https://tracker.ceph.com/issues/65067
> Signed-off-by: Rongqi Sun <sunrongqi@huawei.com>
> ```
> 
> by referencing a URL. please reference a git sha1, or a file in the repo when possible. and put the rationales **in** the commit message. developer's time is precious, unless necessary, i don't want to fire up a browser with javescript enabled, and wait for it, when checking a commit message.

Sorry for the inconvenience. Thanks for pointing this out. Would make PR more explicit and accessible in the future.

**Review by adamemerson — APPROVED** [review]
Looks good to me.

**Pull request merged**
