### PR TITLE
luminous: mon,osd: fix "pg ls {forced_backfill, backfilling}"

### PR DESCRIPTION
**Pull request by tchaikov**
http://tracker.ceph.com/issues/21609

also backport of #18235

### CODE REVIEW

**Comment by tchaikov** [comment]
probably we should backport #18235 as well.

**Comment by liewegas** [comment]
The state rename commit is also in https://github.com/ceph/ceph/pull/18025, which will hopefully merge shortly.

**Comment by tchaikov** [comment]
cool, will remove it from this PR.

**Comment by liewegas** [comment]
http://pulpito.ceph.com/sage-2017-10-17_15:09:41-rados-wip-sage-testing-2017-10-16-2116-distro-basic-smithi/

**Pull request merged**
