### PR TITLE
jewel: osd: Add config option to disable new scrubs during recovery

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/17866

### CODE REVIEW

**Comment by dachary** [comment]
<pre>
  CXX      osd/libosd_a-OpRequest.o
osd/OSD.cc: In member function ‘void OSD::sched_scrub()’:
osd/OSD.cc:6439:61: error: ‘class OSDService’ has no member named ‘is_recovery_active’
       if (!cct->_conf->osd_scrub_during_recovery && service.is_recovery_active()) {
                                                             ^
osd/OSD.cc: At global scope:
osd/OSD.cc:8405:37: error: no ‘bool OSDService::is_recovery_active()’ member function declared in class ‘OSDService’
 bool OSDService::is_recovery_active()
</pre>

**Comment by smithfarm** [comment]
@dachary Thanks for pointing that out. Jenkins is gnawing at my second try now.

**Comment by smithfarm** [comment]
[(PR#11944) osd: Add config option to disable new scrubs during recovery](https://trello.com/c/tzjNDZdu/2173-pr-11944-osd-add-config-option-to-disable-new-scrubs-during-recovery)

**Comment by dachary** [comment]
jenkins test this please (flake8 error now fixed in jewel-next)

**Comment by dachary** [comment]
@liewegas does this backport look good to merge ? It passed the rados (http://tracker.ceph.com/issues/17851#note-12) suite. It also passed the upgrade/jewel-x and upgrade/hammer-x (http://tracker.ceph.com/issues/17851#note-15) suites. Note that it won't be included in 10.2.4, reason why it targets jewel-next.

**Pull request merged**
