### PR TITLE
hammer: mon: MonmapMonitor should return success when MON will be removed

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/17905

### CODE REVIEW

**Comment by smithfarm** [comment]
@jecluis Please review. I did not cherry-pick the second commit - the one removing the goto statements - because the hammer code does not seem to have goto statements.

**Comment by jecluis** [comment]
@smithfarm lgtm

and the second commit isn't required as part of the bugfix.

**Comment by smithfarm** [comment]
@liewegas This backport passed a rados suite at http://tracker.ceph.com/issues/17151#note-7 with failures that I believe have been addressed (except for http://tracker.ceph.com/issues/15139 which is caused by the build system no longer providing dumpling-era packages).

I have rebuilt the integration branch to include the two fixes and scheduled a new run at http://tracker.ceph.com/issues/17151#note-14

Do you think it's OK to merge provided the second run succeeds?

**Comment by smithfarm** [comment]
Second run succeeded; third run here: http://pulpito.front.sepia.ceph.com/smithfarm-2016-11-21_11:52:41-rados-hammer-backports---basic-smithi/

**Pull request merged**
