### PR TITLE
rgw: fix versioned bucket data sync fail when upload is busy

### PR DESCRIPTION
**Pull request by dongbula**
http://tracker.ceph.com/issues/18208

In multisite cluster, upload an file to master zone two times in a short time, you will find the first version sync to slave zone failed, this fix it.

### CODE REVIEW

**Comment by idealguo** [comment]
Signed-off-by and tracker

**Comment by cbodley** [comment]
@dongbula thanks for taking this on. i added a test for it at https://github.com/ceph/ceph/pull/12474, and verified that your fix works as intended

i do still see an issue with this fix though. the `squash_map` is important here because these sync entries are processed in parallel. so if there's an `OP_WRITE` entry followed by `OP_DEL` on the same object, we can't guarantee that the `OP_WRITE` will sync before the `OP_DEL` - if the order gets switched, then this zone would up with that object still existing, while it didn't in the source zone

so we use the `squash_map` to make sure that we only apply the most recent entry for any given object. but by ignoring the `squash_map` for versioned entries, we wouldn't know to squash a `LINK_OLH` entry followed by an `UNLINK_INSTANCE` on the same object instance, and we could end up in the same situation

i think the ideal solution would involve extending the `squash_map` key to include the object instance along with the object name, so we can track each version separately. something like this:
```diff
-  map<string, pair<real_time, RGWModifyOp> > squash_map;
+  map<pair<string, string>, pair<real_time, RGWModifyOp> > squash_map;
```
then below:
```diff
-        auto& squash_entry = squash_map[e.object];
+        auto& squash_entry = squash_map[make_pair(e.object, e.instance)];
         if (squash_entry.first == e.timestamp &&
-            e.op == CLS_RGW_OP_DEL) {
+            (e.op == CLS_RGW_OP_DEL || e.op == CLS_RGW_OP_UNLINK_INSTANCE)) {
           squash_entry.second = e.op;
         } else if (squash_entry.first < e.timestamp) {
           squash_entry = make_pair<>(e.timestamp, e.op);
         }
```
does that make sense?

**Comment by dongbula** [comment]
@cbodley Hi,
I understand the idea that 

> use the squash_map to make sure that we only apply the most recent entry for any given object

, but I still feel puzzled about these code:
```
       if (squash_entry.first == e.timestamp &&
              e.op == CLS_RGW_OP_DEL) {
            squash_entry.second = e.op;
         }
```
Is it means that `OP_WRITE `  and  `OP_DEL`  entry may have same timestamp?

Considering that the instances of `OP_WRITE ` are usually different(they are just like different write in non-versioned situation), so I modify the code  to make the squash_map just work in non-versioned situation. That is my original idea.

**Comment by cbodley** [comment]
> Is it means that OP_WRITE and OP_DEL entry may have same timestamp?

good point - these are high-resolution timestamps, so that shouldn't be possible (right @yehudasa?). it should also be safe to assume that the bilog entries are already ordered by timestamp, so we could probably replace that whole block with:
```diff
-        auto& squash_entry = squash_map[e.object];
+        auto& squash_entry = squash_map[make_pair(e.object, e.instance)];
-        if (squash_entry.first == e.timestamp &&
-            e.op == CLS_RGW_OP_DEL) {
-          squash_entry.second = e.op;
-        } else if (squash_entry.first < e.timestamp) {
-          squash_entry = make_pair<>(e.timestamp, e.op);
-        }
+        squash_entry = make_pair(e.timestamp, e.op);
```

> I modify the code to make the squash_map just work in non-versioned bucket. That is my original idea, maybe it's not enough.

we still need to squash entries for versioned buckets, or we'll run into ordering problems between `LINK_OLH` and `UNLINK_INSTANCE`. the `squash_map` is what prevents them from running in parallel

(http://tracker.ceph.com/issues/15542 has a bit more about the bug that was fixed by adding the `squash_map`)

**Comment by yehudasa** [comment]
@cbodley iirc for OP_DEL we're storing the removed object's mtime, not when it was removed

**Comment by cbodley** [comment]
@yehudasa maybe you're thinking about the `obj_tombstone_cache` in `RGWRados`? these are the timestamps in `rgw_bi_log_entry` that we're using for the `squash_map` to resolve the create/delete races in bucket sync that @theanalyst had found. we're discussing whether this check is necessary:
```c++
         if (squash_entry.first == e.timestamp &&
              e.op == CLS_RGW_OP_DEL) {
            squash_entry.second = e.op;
         }
```
 the timestamps were converted to from `utime_t` to `ceph::real_time`, so it's possible that sync is reading old entries that were encoded with 1-second resolution - so the timestamps could compare equal. but my point is that the bilog is ordered, so i think that the `squash_map` should always take the most recent entry

**Comment by cbodley** [comment]
@dongbula i updated the test in https://github.com/ceph/ceph/pull/12474 to exercise this squash logic. you can run it from your cmake build directory with:
`$ nosetests --nocapture ../src/test/rgw/test_multi.py:test_versioned_object_incremental_sync`

**Comment by yehudasa** [comment]
@cbodley no, I'm really talking about bucket index log (also verified it now). The timestamp entries that we keep for the delete operations are the object's mtime. Note that although bilog is ordered, entries can arrive out of order as you might have multiple rgws feeding into it, so need to check timestamps.

**Comment by yehudasa** [comment]
@cbodley ahrm.. ah, reading the cls/rgw code again, committed operations will be written to the bi log in order. That been said, I think we should still check timestamp, bugs may happen.

**Comment by cbodley** [comment]
@yehudasa okay, thanks! so it looks like the first diff i posted, that also checks for `OP_UNLINK_INSTANCE` in that comparison, would be the way to go

**Comment by dongbula** [comment]
@cbodley 
Well, squashing entries seems to be necessary whether bucket is versioned or not, the code shoule be like those in your first comment. But, I still have a question about:
`the timestamps were converted to from utime_t to ceph::real_time, so it's possible that sync is reading old entries that were encoded with 1-second resolution - so the timestamps could compare equal.`
That encoded with 1-second resolution, not 1-nanosecond? Two operations always have different timestamps if the timestamps is gained by nanoseconds. Isn't it?

thanks!

**Comment by cbodley** [comment]
> When the entry will be encoded with 1-second resolution?

the type of this timestamp was changed for jewel i think? so any entries that were written before that upgrade would be decoded in seconds

> I modify the code to do squash for all entries, and replace CLS_RGW_OP_DEL with CLS_RGW_OP_LINK_OLH to make versioned upload sync normally. I think that is necessary.

looks good, except i'm not sure why you took the `OP_DEL` part out of that comparison?

**Comment by dongbula** [comment]
@cbodley ah, i see, the comparison for OP_DEL is for compatibility with old entries. I will add that.

**Comment by cbodley** [comment]
some extra notes from testing..

uploading an object to a versioned bucket results in two bilog entries with the same timestamp, `OP_ADD` and `OP_LINK_OLH`. so in this case, the `squash_map` needs to overwrite the `OP_ADD` with `OP_LINK_OLH`

deleting an object instance results in `OP_UNLINK_INSTANCE` and `OP_DEL`, both with a matching timestamp (but different from the `ADD`/`LINK_OLH`). so the existing logic for `if (squash_entry.first == e.timestamp && e.op == CLS_RGW_OP_DEL)` covers this case

in both cases, when timestamps match, we want to apply the latest bilog entry. even in non-versioned buckets with low-resolution timestamps, if there are entries for `OP_ADD`, `OP_DEL`, `OP_ADD`, we want to apply the last `OP_ADD`. i think that something like this would work best:
```diff
-        auto& squash_entry = squash_map[e.object];
+        auto& squash_entry = squash_map[make_pair(e.object, e.instance)];
-        if (squash_entry.first == e.timestamp &&
-            e.op == CLS_RGW_OP_DEL) {
-          squash_entry.second = e.op;
-        } else if (squash_entry.first < e.timestamp) {
+        if (squash_entry.first <= e.timestamp) {
           squash_entry = make_pair<>(e.timestamp, e.op);
         }
```

**Comment by dongbula** [comment]
good, that's concise. I noticed that：

> Note that although bilog is ordered, entries can arrive out of order as you might have multiple rgws feeding into it, so need to check timestamps.

When OP_ADD and OP_DEL own same timestamp which are encoded with 1-second resolution, is it safety to assume that the OP_DEL  is behind OP_ADD in entry?

**Comment by cbodley** [comment]
> Is it safety to assume that the OP_DEL is behind OP_ADD in entry when OP_ADD and OP_DEL own same timestamp which are encoded with 1-second resolution?

if the DEL entry comes later in the log, yes

**Comment by cbodley** [comment]
looks good to me 👍 it's passing test_multi.py, including the new `test_versioned_object_incremental_sync` from https://github.com/ceph/ceph/pull/12474

could you please squash this into a single commit so we can merge?

**Comment by dongbula** [comment]
ok, I have squashed the commits

**Comment by cbodley** [comment]
@dongbula thank you. could you add the line `Fixes: http://tracker.ceph.com/issues/18208` please?

**Comment by dongbula** [comment]
okey, have added it

**Pull request merged**
