### PR TITLE
quincy: ceph-dencoder: Add erasure_code to denc-mod-osd's target_link_libraries

### PR DESCRIPTION
**Pull request by tserong**
backport tracker: https://tracker.ceph.com/issues/57391

---

backport of https://github.com/ceph/ceph/pull/47919
parent tracker: https://tracker.ceph.com/issues/57390

this backport was staged using ceph-backport.sh version 16.0.0.6848
find the latest version at https://github.com/ceph/ceph/blob/main/src/script/ceph-backport.sh

### CODE REVIEW

**Comment by tserong** [comment]
Note: this also needs https://github.com/ceph/ceph/pull/47982 - will cherry pick here once that's merged into main.

**Comment by tserong** [comment]
I've grabbed #47982 which was necessary and also #48418 because that came out of the same discussion and I thought it made sense to keep 'em all together.

**Comment by tserong** [comment]
jenkins test make check

**Comment by tserong** [comment]
jenkins test make check

**Comment by tserong** [comment]
Rebased

**Review by tchaikov — APPROVED** [review]

**Comment by tserong** [comment]
jenkins test make check

**Comment by tserong** [comment]
Tested manually on openSUSE.

**Comment by tserong** [comment]
Tagging DNM because @vshankar reported problems with the last commit (see https://github.com/ceph/ceph/pull/49842)

**Comment by tserong** [comment]
Dropped "cmake: do not link ceph-dencoder against global" (see #49842)

**Comment by tserong** [comment]
@yuriw I see you've got this labelled wip-yuri7-testing, but I've just dropped one commit (see previous comments). My apologies if that messes up your testing.

**Comment by ljflores** [comment]
jenkins test make check

**Comment by ljflores** [comment]
jenkins test api

**Comment by ljflores** [comment]
Rados suite review: https://pulpito.ceph.com/?branch=wip-yuri7-testing-2023-01-30-1510-quincy

Failures, unrelated:
    1. https://tracker.ceph.com/issues/58585
    2. https://tracker.ceph.com/issues/58146
    3. https://tracker.ceph.com/issues/58560
    4. https://tracker.ceph.com/issues/58265

Details:
    1. rook: failed to pull kubelet image - Ceph - Orchestrator
    2. test_cephadm.sh: Error: Error initializing source docker://quay.ceph.io/ceph-ci/ceph:master - Ceph - Orchestrator
    3. test_envlibrados_for_rocksdb.sh failed to subscrib repo - Ceph
    4. TestClsRbd.group_snap_list_max_read failure during upgrade/parallel tests - Ceph - RBD

**Comment by yuriw** [comment]
jenkins test this please

**Comment by ljflores** [comment]
Rados suite review: https://pulpito.ceph.com/?branch=wip-yuri2-testing-2023-02-09-0842-quincy

Failures, unrelated:
    1. https://tracker.ceph.com/issues/58146
    2. https://tracker.ceph.com/issues/58585

Details:
    1. test_cephadm.sh: Error: Error initializing source docker://quay.ceph.io/ceph-ci/ceph:master - Ceph - Orchestrator
    2. rook: failed to pull kubelet image - Ceph - Orchestrator

**Pull request merged**
