### PR TITLE
[DNM] jewel: librados: libradosstriper: Avoid assertion if object size is ZERO 

### PR DESCRIPTION
**Pull request by shinobu-x**
Do not try to stripe any pieces of ZERO size object

Fixes: http://tracker.ceph.com/issues/14609

Signed-off-by: Shinobu Kinjo <shinobu@redhat.com>

### CODE REVIEW

**Comment by tchaikov** [comment]
@shinobu-x you might want to squash these commits into a single one. and also explain why this commit is targeting jewel but not master in the commit message.

**Comment by shinobu-x** [comment]
@tchaikov 

Sorry that's my bad. I just tagged jewel since reporter used codebases based on jewel. By the way should I just "git merge --squash <my branch>"?

**Comment by smithfarm** [comment]
Is this bug already fixed in master?

**Comment by smithfarm** [comment]
Marking DNM pending clarification of targeting, staging, etc.

**Comment by shinobu-x** [comment]
@smithfarm 

Looks like fixed in master. How should I proceed with code cleanup a bit more? I've been also thinking of including exception handling. 

Please advice.

**Comment by shinobu-x** [comment]
@smithfarm 

Looks like fixed in master. But I've not been finding when it happened. What should I do from here?

**Comment by smithfarm** [comment]
@shinobu-x There is a policy that we try as hard as we can to backport fixes from master by cherry-picking. So, you would find the relevant commits in master and then `git cherry-pick -x`. There is some documentation on the backporting process here: http://tracker.ceph.com/projects/ceph-releases/wiki/HOWTO_backport_commits

Anything new (like the exception handling you mentioned) should be implemented in master first, and only then backported if it fixes a real bug in jewel that is causing (or could potentially cause) trouble for users.

You might also read https://github.com/ceph/ceph/blob/master/SubmittingPatches.rst

**Comment by shinobu-x** [comment]
@smithfarm 

Thank you very much for your really really great help :) will follow you!

**Pull request closed without merging**
