### PR TITLE
tools: set the release of backport issues

### PR DESCRIPTION
**Pull request by dachary**
Signed-off-by: Loic Dachary <ldachary@redhat.com>

### CODE REVIEW

**Comment by dachary** [comment]
@Abhishekvrshny @theanalyst would you have time to take a look ? I made too many mistakes doing that manually :-)

**Comment by smithfarm** [comment]
@dachary I keep having this recurring thought that we should have a separate github repo for backport-related stuff.

**Comment by dachary** [comment]
@smithfarm earlier this year I started http://workbench.dachary.org/dachary/ceph-workbench for that purpose. Then I realized it was too early and it turns out we developed methods that work, without any software. But now seems a good time to collect the snippets we have into the ceph-workbench cli.

**Comment by smithfarm** [comment]
@dachary Yes, the methods do work without any software, but I think all of us have converted one or more of the code snippets into scripts that we maintain locally. I, too, think it's time to formalize these scripts, make them parse configuration files, and have them in a git repo. You're ceph-workbench repo looks perfect for this purpose - I was not aware of it till now.

**Comment by dachary** [comment]
replaced by http://ceph-workbench.dachary.org/root/ceph-workbench/merge_requests/8

**Pull request closed without merging**
