### PR TITLE
mon,mgr: ceph logs shouldn't display dmcrypt keys

### PR DESCRIPTION
**Pull request by badone**
Fixes: http://tracker.ceph.com/issues/20790

Signed-off-by: Brad Hubbard <bhubbard@redhat.com>

### CODE REVIEW

**Comment by jdurgin** [comment]
lgtm, @tchaikov are there any other places or commands we should be masking with this?

**Comment by tchaikov** [comment]
i will take a look early tomorrow.

**Comment by liewegas** [comment]
see http://tracker.ceph.com/issues/20790?next_issue_id=20580&prev_issue_id=20800#note-3

**Comment by tchaikov** [comment]
@badone so we don't need this change in luminous and above anymore, right? in other words, we just need it in jewel. as kraken will be EOL once luminous is released.

**Comment by badone** [comment]
@tchaikov We don't need this PR at all (I'm closing it). All we apparently need is a change to ceph-disk so it uses the '-i' flag, and only in jewel specifically, and I'm working on a PR for that now.

**Comment by smithfarm** [comment]
> All we apparently need is a change to ceph-disk so it uses the '-i' flag, and only in jewel specifically

@badone Can you open a tracker issue so we can track the backport?

**Pull request closed without merging**
