### PR TITLE
mgr/dashboard: Replace vonage-status-panel with native grafana stat panel

### PR DESCRIPTION
**Pull request by aaSharma14**
Before:
Screenshot from 2022-11-08 10-37-06

After:
Screenshot from 2022-11-21 15-17-20

Fixes: https://tracker.ceph.com/issues/58295
Signed-off-by: Aashish Sharma<aasharma@redhat.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [x] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Review by pereman2 — CHANGES_REQUESTED** [review]
Great job Aasshish thanks for helping here :). 

I believe the alignment should be addressed as it is looking too out of place and different in each label. 

Active and standy should have the number below as the previous stat panels, furthermore, could it help aligning to center both labels and values maybe?

**Review by epuertat — COMMENTED** [review]
Looks reall nice. BTW I thought that this panel was also generated from a jsonnet/grafonnet file... Not the case?

**Comment by aaSharma14** [comment]
> Looks reall nice. BTW I thought that this panel was also generated from a jsonnet/grafonnet file... Not the case?

Thanks @epuertat , ceph-cluster.json is the only dashboard json file for which we didn't create a jsonnet file.

**Comment by aaSharma14** [comment]
> Great job Aasshish thanks for helping here :).
> 
> I believe the alignment should be addressed as it is looking too out of place and different in each label.
> 
> Active and standy should have the number below as the previous stat panels, furthermore, could it help aligning to center both labels and values maybe?

Thanks @pereman2 , I have modified the panels a bit with added bg color as well, couldn't find the properties to set the alignment though, anyways it looks a little better to me than before.

**Review by avanthakkar — APPROVED** [review]

**Comment by aaSharma14** [comment]
jenkins retest this please

**Review by nizamial09 — APPROVED** [review]

**Review by pereman2 — APPROVED** [review]

**Pull request merged**
