### PR TITLE
librbd: journal: improvements and fixes

### PR DESCRIPTION
**Pull request by trociny**

### CODE REVIEW

**Comment by trociny** [comment]
This is based on https://github.com/ceph/ceph/pull/5807 with additional patches.

**Comment by trociny** [comment]
I have some issue I would like to discuss:

1) When 'rbd snap create' command is run for an image with a journal that has uncommitted events, snapshot creation does not wait until all events are replied (see qa/workunits/rbd/journal.sh:test_rbd_journal, where I had to do 'rbd snap create' in loop to make sure all events are replayed). Furthermore, it may lead to a crush, when m_journal_replay is destroying on image close while it is still replaying. The patch 4e32088 fixes the crush for me. Still I think we need to make 'rbd snap create' wait for journal replay. I could work on this, I just wander if it is only snapshot creation should be fixed, or do we need a more generic solution?

2) I have added a bunch of configuration and rbd command line options to tweak journal settings, but I am not sure I choose good names.

a) Some config options have long names (rbd_journal_object_flush_*). To be consistent, rbd command option names have similar naming (--journal-object-flush-*), but the option names are long enough to make trouble for boost::program_options to render properly help message. It looks like below:
```
zhuzha:~/ceph/ceph.trociny/src% ./rbd help create
usage: rbd create [--pool <pool>] [--image <image>] 
                  [--image-format <image-format>] [--new-format] 
                  [--order <order>] [--image-feature <image-feature>] 
                  [--image-shared] [--stripe-unit <stripe-unit>] 
                  [--stripe-count <stripe-count>] 
                  [--journal-splay-width <journal-splay-width>] 
                  [--journal-commit-age <journal-commit-age>] 
                  [--journal-object-pool <journal-object-pool>] 
                  [--journal-object-size <journal-object-size>] 
                  
                  
                  
                  
                  
                  [--journal-object-flush-interval <journal-object-flush-interval>] 
                  [--journal-object-flush-bytes <journal-object-flush-bytes>] 
                  
                  
                  
                  
                  
                  
                  
                  
                  [--journal-object-flush-age <journal-object-flush-age>] --size <size> 
                  <image-spec> 
...
```
It is fixed by using a shorter names but I am not sure what better names to choose. I would like to keep consistency between config option names and command line option names.

b) I have added rbd_journal_order config option, but --journal-object-size command line option (the order is calculated from the size specified). object-size looks more user friendly and from this point of view fits better for command line option, on the other hand for configuration option it would be good to have a precise parameter. But this breaks consistency between config and command line
options and may lead to user confusion. What do you think?

**Comment by jdurgin** [comment]
1) Generally any sort of write (resize, set metadata, change features...) should wait for journal replay, or we'll have inconsistent results (e.g. setting rbd_cache_size, then replaying a different rbd_cache_size over it). I'm not sure if @dillaman handled this in later branches yet.

2) a) The config options can always be specified on the cli as generic args, e.g. --rbd-journal-object-flush-interval. It seems like the main one people would want to change on the cli would be --journal-pool (object isn't needed in the name for this one either). Maybe hide the rest from the usage, and add a note to refer to the man page for the full listing of journal-related options?

b) go with object size, no need for object order. There's a pr for adding it to 'rbd create' so it'll be consistent soon - #5676 .

**Comment by dillaman** [comment]
There is a TODO comment in the master branch about creating a new request coordinator for such a purpose (similar to the new AioImageRequestWQ ability to block writes during journal replay).  I wrote a rough draft of this class a few months ago.

I do think it would be a good idea to block all snap creates until all previous IO events are *committed* to the journal since snapshots are R/O and there is no going back if a replay is required. Feel free to tackle this addition if you have the bandwidth.

As an aside, I actually skipped journaling of metadata since (1) they aren't critical, and (2) I can easily see how different data centers would have the need for different config overrides for an image.

**Comment by trociny** [comment]
@jdurgin @dillaman  Thank you for the comments.

I will check how specifying config options via command line works and it will be definitely  a better solution it it works.

Also, I will work on 'block snap util all IO events are committed'.

**Comment by trociny** [comment]
Considering the idea of using config options in cli instead of adding additional options (e.g. --rbd-journal-object-flush-interval instead of adding --journal-object-flush-interval), it would change the behavior I wanted to achieve initially: if an option is specified via command line (for CLI, or in rbd_create(..., opts) for API) this value is stored in the image metadata and will not be lost if journal is disabled and then re-enabled. I considered this as a useful feature, still needing discussion.

Now, if we pass these options as config options via cli, they are not stored in metadata, and are lost when the journal is disabled.

Do you think storing options in metadata is useful? If you don't I will just proceed with using config options, otherwise I will think about other solution.

**Comment by dillaman** [comment]
@trociny I wouldn't automatically store those in the metadata -- if you want to keep a config setting persistently, use the provided tooling to store the config value in the metadata.

**Comment by jdurgin** [comment]
@trociny I think it's fine to lose the metadata when you disable the journal - recreating the journal may want to use different settings anyway, and it could get confusing if your image has some stored defaults that you didn't want to use. Better to keep setting the metadata as an explicit step imo.

**Comment by jdurgin** [comment]
@dillaman good point about not wanting to replicate metadata. esp. if it could contain mirroring settings, which would not make sense in different sites.

**Comment by trociny** [comment]
I have update the patches:

- only the following journaling options remain: 
  --journal-pool
  --journal-object-size
  --journal-splay-width 6
- metadata are not stored

**Comment by jdurgin** [comment]
looks good in general, I'm curious about the linking issue for reset. Putting these journal manipulations directly in the cli (as opposed to behind a librbd api) make separating the rbd cli from depending on exactly the librbd/librados version compiled more difficult. They're currently intertwined anyway, so I don't think it's really an issue, but I'm curious on @dillaman's thoughts

**Comment by dillaman** [comment]
@jdurgin I actually already gave a thumbs-up to directly link since, as you said, librbd and the rbd CLI are already tightly intertwined.  At some point it might be good to expose, but if CephFS ever migrates to this journal, it would perhaps make more sense to upgrade the journal to its own stand-alone API. Definitely in the short term it helps to direct our focus elsewhere instead of building a potentially large-ish API before we have users for it.

**Comment by trociny** [comment]
Rebased after addressing some Josh's comments: 
- s/journal_object_pool/journal_pool/
- get_metadata: out params should be pointers
- get_pool_journal_names: remove unused argument

I have still not addressed comments about adding  --yes-i-really-really-mean-it for reset, and checking if the journal is empty before importing, because after thinking more about it I am not so sure now it is really a good idea:
- we don't use --yes-i-really-really-mean-it for other rbd dangerous operations like remove image, and I am not sure it is particularly useful.
- allowing import only on empty journal limits a bit the import functionality, I could imagine (rather exotic though) cases where it could be useful to allow import to non-empty journal. May be add `--force` option?

I agree that we could create a separate tool for recovery operations (reset/import/export). Actually I added them to rbd only because it was in initial Jason's design. I will create a separate too if you change your mind.

But right now I am more concerned with the issue which I was trying to address with f5a37b7. I needed this fiix to make e.g. TestJournalReplay.EntryPosition works. But the fix does not look correct, because now TestLibRBD.ZeroLengthWrite fails due to FAILED assert(m_events.empty()). I still don't have an idea about a proper fix.

Also, may be instead of creating a PR that contain a bunch of patches it would be better if I separated it in several PRs to ease the review and merging?

**Comment by trociny** [comment]
It turned out that after "journaling for maintenance operations" branch was merged to master I have not been observing the issue with the snap_create not waiting for uncommitted events to replay, that I described earlier.

I have updated my test in journal.sh.

**Comment by trociny** [comment]
I have yet another issue I would like to discuss.

In TestJournalReplay I have added a method  get_journal_commit_position. It is used to check how the client position is updated reading journal metadata, and is called after closing the journal. But ictx->journal->close() is not synchronous, it queues journal deletion (in Journal::destroy_journaler()) and returns. As a result I am observing a race: sometime get_journal_commit_position returns not updated position yet.

To ensure that this this the case, I used this patch:

```
--- a/src/librbd/Journal.cc
+++ b/src/librbd/Journal.cc
@@ -26,11 +26,14 @@ const std::string CLIENT_DESCRIPTION = "master image";
 
 struct C_DestroyJournaler : public Context {
   ::journal::Journaler *journaler;
+  Context *on_safe;
 
-  C_DestroyJournaler(::journal::Journaler *_journaler) : journaler(_journaler) {
+  C_DestroyJournaler(::journal::Journaler *journaler, Context *on_safe)
+    : journaler(journaler), on_safe(on_safe) {
   }
   virtual void finish(int r) {
     delete journaler;
+    on_safe->complete(r);
   }
 }; 
 
@@ -483,10 +487,15 @@ void Journal::destroy_journaler() {
   }
 
   m_close_pending = false;
-  m_image_ctx.op_work_queue->queue(new C_DestroyJournaler(m_journaler), 0);
+  C_SaferCond cond;
+  m_image_ctx.op_work_queue->queue(new C_DestroyJournaler(m_journaler, &cond), 0);
   m_journaler = NULL;
 
   transition_state(STATE_UNINITIALIZED);
+  int r = cond.wait();
+  if (r != 0) {
+    lderr(cct) << "destroy_journaler: " << cpp_strerror(r) << dendl;
+  }
 }

```
It fixes the issue to me.

What do you think is a proper way to fix this? I thought about adding 'boool sync' argument to close() function, and wait for destroy journaler if it is set.

**Comment by dillaman** [comment]
@trociny How about adding an optional ```Context *``` to ```Journal::close``` which the ```C_DestroyJournaler``` would complete if not null?

**Comment by trociny** [comment]
@dillaman I will do. Thanks.

**Comment by dillaman** [comment]
@trociny FYI -- that async destruction was a dirty workaround to the fact that image refresh is synchronous instead of async, which results in the thread pool getting deadlocked.  I've started a (large) effort to convert image refresh to a new async state machine, but it's still a large work-in-progress.

**Comment by trociny** [comment]
Rebased after the following changes:

- Remove the patches 16e14c4 and 92749ee.
- Add 0f90779 to fix the close issue in tests.
- Use std::move() to avoid heap allocation.

Issues that are still observed:

- TestJournalReplay.EntryPosition still fails due to commit position is not properly updated after aio_flush (@dillaman: waiting for your fix?).
- FAILED assert(m_events.empty()) are still sometime observed (both on my branch and master):
```
zhuzha:~/ceph/ceph.trociny/src% RBD_FEATURES=109 ./unittest_librbd  --gtest_filter=TestLibRBD.ExclusiveLockTransition
Note: Google Test filter = TestLibRBD.ExclusiveLockTransition
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from TestLibRBD
seed 30564
[ RUN      ] TestLibRBD.ExclusiveLockTransition
using new format!
librbd/Journal.cc: In function 'void librbd::Journal::handle_lock_updated(librbd::ImageWatcher::LockUpdateState)' thread 7f2fba7fc700 time 2015-12-03 10:57:29.916683
librbd/Journal.cc: 639: FAILED assert(m_events.empty())
 ceph version 9.2.0-1268-g39ba840 (39ba840fce370820c7a35d0e0086b72b3a0a435d)
 1: (ceph::__ceph_assert_fail(char const*, char const*, int, char const*)+0x82) [0x7f2fe473c8f2]
 2: (librbd::Journal::handle_lock_updated(librbd::ImageWatcher::LockUpdateState)+0x373) [0x7f2fe460c173]
 3: (librbd::ImageWatcher::notify_listeners_updated_lock(librbd::ImageWatcher::LockUpdateState)+0x179) [0x7f2fe45d68a9]
 4: (librbd::ImageWatcher::release_lock()+0x254) [0x7f2fe45dbe04]
 5: (librbd::ImageWatcher::notify_release_lock()+0x53) [0x7f2fe45dc313]
 6: (FunctionContext::finish(int)+0x2a) [0x7f2fe44a51ba]
 7: (Context::complete(int)+0x9) [0x7f2fe44a01b9]
 8: (Context::complete(int)+0x9) [0x7f2fe44a01b9]
 9: (Finisher::finisher_thread_entry()+0x21e) [0x7f2fe471b8be]
 10: (()+0x80a4) [0x7f2fe3a580a4]
 11: (clone()+0x6d) [0x7f2fe25d804d]
 NOTE: a copy of the executable, or `objdump -rdS <executable>` is needed to interpret this.
terminate called after throwing an instance of 'ceph::FailedAssertion'
zsh: abort      RBD_FEATURES=109 ./unittest_librbd 
```
Thought it is a little harder to trigger (I need to run the test several time to fail).

**Comment by dachary** [comment]
@trociny @dillaman this is the third occurrence of what seems to be a new false negative tracked at http://tracker.ceph.com/issues/13969

**Comment by dachary** [comment]
@trociny 
<pre>
[  FAILED  ] 1 test, listed below:
[  FAILED  ] TestJournalReplay.EntryPosition
</pre>
looks like it could be real ? If you think it's a false negative, could you add a note about it ? 

Thanks :-)

**Comment by trociny** [comment]
@dachary sorry for this noise with loic-bot failures. It was expected, see my note above. This PR is still in RFC stage.

**Comment by dachary** [comment]
@trociny not a problem, thanks for the update :-)

**Comment by jdurgin** [comment]
@trociny Good point about the lack of safety options for other destructive rbd cli commands. The cli and config changes look good. Do you want to make a separate pr for the bug fixes that are still being sorted so we can merge the journal config stuff?

**Comment by trociny** [comment]
Rebased after removing 0f90779, 6dc2e48, and fd91a92.

I am going to create a separate PR for the 0f90779 and 6dc2e48.

I am not sure about the last fd91a92: I needed it previously, but now it is not triggered. @dillaman can I just drop it or may be it is still a good idea, or does it need improvements (you were talking about ignored possible error from flush())?

**Comment by dillaman** [comment]
@trociny I would drop it since I think if it is needed, it's just covering up a problem that should be fixed elsewhere.

**Pull request merged**
