### PR TITLE
nautilus: monitoring: update Grafana dashboards

### PR DESCRIPTION
**Pull request by jan--f**
http://tracker.ceph.com/issues/39932
http://tracker.ceph.com/issues/40006

### CODE REVIEW

**Comment by callithea** [comment]
jenkins test dashboard

**Comment by callithea** [comment]
jenkins test dashboard

**Comment by callithea** [comment]
jenkins test dashboard

**Comment by callithea** [comment]
jenkins test make check

**Comment by callithea** [comment]
jenkins test make check arm64

**Comment by yuriw** [comment]
[wip-yuri2-testing-2019-05-16-1555-nautilus](https://trello.com/c/VvCEDimT/616-wip-yuri2-testing-2019-05-16-1555-nautilus)

**Comment by LenzGr** [comment]
Adding the "DNM" label for now: please note that this PR changes the UUIDs of some Grafana dashboards, which breaks embedding them into the Ceph Dashboard. See http://tracker.ceph.com/issues/39971 for the corresponding issue. A PR for master is under review here: #28169 - once this one has been merged, it may make sense to cherry-pick it into this backport PR.

**Comment by hoerup** [comment]
@LenzGr  #28169 has been merged now  and there's a backport issue on tracker http://tracker.ceph.com/issues/40006

**Comment by LenzGr** [comment]
@jan--f would you mind cherry picking #28169 into this PR so it will resolve http://tracker.ceph.com/issues/40006 as well?

**Comment by jan--f** [comment]
@LenzGr done

**Comment by LenzGr** [comment]
jenkins test make check

**Comment by yuriw** [comment]
@jan--f @LenzGr this passed tests.  pls merge at will, I am hesitant as see ceph dashboard tests failed

**Comment by epuertat** [comment]
jenkins test dashboard

**Comment by epuertat** [comment]
Jenkins "dashboard tests" console failure (looks like someone confused "rpm" with "yum"?):
```
+ sudo rpm -i -y google-chrome-stable_current_x86_64.rpm
rpm: -y: unknown option
Build step 'Execute shell' marked build as failure
```

**Pull request merged**
