### PR TITLE
mimic: rgw: fix RGWDeleteMultiObj::verify_permission

### PR DESCRIPTION
**Pull request by IrekFasikhov**
Solving a problem when deleting multiple objects 

Fixes: https://tracker.ceph.com/issues/38722
Signed-off-by: Irek Fasikhov <malmyzh@gmail.com>

### CODE REVIEW

**Comment by mattbenjamin** [comment]
@IrekFasikhov if you haven't already,could you create a tracker ticket for this and link it?

**Comment by IrekFasikhov** [comment]
@majianpeng https://tracker.ceph.com/issues/38722

**Comment by mattbenjamin** [comment]
@IrekFasikhov woot;  in addition, please edit the commit message to have

Fixes: https://tracker.ceph.com/issues/38722

in the body?

**Comment by IrekFasikhov** [comment]
> @IrekFasikhov woot; in addition, please edit the commit message to have
> 
> Fixes: https://tracker.ceph.com/issues/38722
> 
> in the body?

done :)

**Comment by IrekFasikhov** [comment]
> @IrekFasikhov woot; in addition, please edit the commit message to have
> 
> Fixes: https://tracker.ceph.com/issues/38722
> 
> in the body?

**Comment by mattbenjamin** [comment]
um, what?  "At least 6 approving reviews are required by reviewers with write access."

**Comment by mattbenjamin** [comment]
@IrekFasikhov oops -- I apologize for this, I didn't notice you sent this PR against mimic;  If it applies (which I assume), you should do this against MASTER, then put luminous,mimic (nautilus) in the backports field in the tracker issue;  the backports team will then handle the backport to mimic in due course

**Comment by smithfarm** [comment]
The backport will be done by the backporting team after the master PR has merged.

**Pull request closed without merging**
