### PR TITLE
luminous: librbd: add missing shutdown states to managed lock helper

### PR DESCRIPTION
**Pull request by dillaman**
http://tracker.ceph.com/issues/38508

### CODE REVIEW

**Comment by trociny** [comment]
@dillaman I tried this PR on teuthology [1] (as it looked suspicious to me) and observed crashes (see e.g. [2]):
```
2019-05-17 11:05:29.295479 7fcb1ddd77c0  0 ceph version 12.2.12-15-g6c4e2ae (6c4e2aefcbfd5e8a69cf0743e35e583208c54bce) luminous (stable), process rbd-mirror, pid 12043
2019-05-17 11:05:29.300765 7fcb1ddd77c0  1 mgrc service_daemon_register rbd-mirror.mirror metadata {arch=x86_64,ceph_version=ceph version 12.2.12-15-g6c4e2ae (6c4e2aefcbfd5e8a69cf0743e35e583208c54bce) luminous (stable),cpu=Intel(R) Xeon(R) CPU E5-1620 v3 @ 3.50GHz,distro=ubuntu,distro_description=Ubuntu 18.04 LTS,distro_version=18.04,hostname=smithi038,instance_id=4126,kernel_description=#54-Ubuntu SMP Mon May 6 18:46:08 UTC 2019,kernel_version=4.15.0-50-generic,mem_swap_kb=2097148,mem_total_kb=32830548,os=Linux}
2019-05-17 11:06:29.404287 7fcb0a7fc700 -1 /build/ceph-12.2.12-15-g6c4e2ae/src/common/CondVar.h: In function 'int Cond::Signal()' thread 7fcb0a7fc700 time 2019-05-17 11:06:29.403077
/build/ceph-12.2.12-15-g6c4e2ae/src/common/CondVar.h: 86: FAILED assert(waiter_mutex == __null || waiter_mutex->is_locked())

 ceph version 12.2.12-15-g6c4e2ae (6c4e2aefcbfd5e8a69cf0743e35e583208c54bce) luminous (stable)
 1: (ceph::__ceph_assert_fail(char const*, char const*, int, char const*)+0xf5) [0x7fcb14e1be25]
 2: (rbd::mirror::PoolReplayer::handle_init_remote_pool_watcher(int, Context*)+0x482) [0x55891057abc2]
 3: (FunctionContext::finish(int)+0x2c) [0x558910582f3c]
 4: (Context::complete(int)+0x9) [0x558910581d09]
 5: (ThreadPool::worker(ThreadPool::WorkThread*)+0xceb) [0x7fcb14e227fb]
 6: (ThreadPool::WorkThread::entry()+0x10) [0x7fcb14e24b70]
 7: (()+0x76db) [0x7fcb149456db]
 8: (clone()+0x3f) [0x7fcb13cbc88f]
 NOTE: a copy of the executable, or `objdump -rdS <executable>` is needed to interpret this.
```
[1] http://pulpito.ceph.com/trociny-2019-05-17_10:48:25-rbd-wip-mgolub-testing-luminous-distro-basic-smithi/
[2] http://qa-proxy.ceph.com/teuthology/trociny-2019-05-17_10:48:25-rbd-wip-mgolub-testing-luminous-distro-basic-smithi/3962987/teuthology.log

**Comment by dillaman** [comment]
Whoops -- thanks. I re-acquired the lock prior to invoking the condition now.

**Comment by smithfarm** [comment]
@dillaman Please check that the PR passed all the mandatory Jenkins tests before adding the magic label :-) Thanks.

**Comment by smithfarm** [comment]
jenkins re-test this please

**Comment by dillaman** [comment]
> @dillaman Please check that the PR passed all the mandatory Jenkins tests before adding the magic label :-) Thanks.

Eh, it wasn't failing due to this PR so it shouldn't have blocked any teuthology testing.

**Comment by yuriw** [comment]
[wip-yuri3-testing-2019-07-10-1613-luminous](https://trello.com/c/jcT6CVxq/662-wip-yuri3-testing-2019-07-10-1613-luminous)

**Pull request merged**
