### PR TITLE
mgr/cephadm: OSDs belongs always to one service

### PR DESCRIPTION
**Pull request by jmolmo**
Avoid to have OSDs daemons created with <orch daemon add> being shown as simulated services.

This makes consistent the management of OSDs ( OSDs will always belong to one service ).

The use of "orch daemon add osd hots:devices" creates OSDs daemons not linked with any service. The "orch ls" command simulate the service, creating a "osd.None" each time a osd daemons without service was found.

For users this is very confusing, because they think that that "osd.None" is a service, and try to use it as a service, finding unexpected behavior when you try to manage the service. For example. If you try to remove the service with "orch rm" and error appears telling that the service does not exist.

This modification, apart of fixing this blurred situation, will allow us to launch OSD removals automatically when the service is deleted. (new PR coming soon)

Fixes: https://tracker.ceph.com/issues/49755

Signed-off-by: Juan Miguel Olmo Martínez <jolmomar@redhat.com>

## Checklist
- [x] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by liewegas** [comment]
I'm a bit confused by what this: what service do the osds show under instead of ``osd.None``?  Or do they not show up at all?

Note that one of the earlier challenges here was that we didn't know how to link an OSD to the drivegroup/service that originally created it.  Now that the unit.meta has the service_name, we have one way to link those back together.  (Except that the service could be deleted or modified and the osd unit.meta would still reference the old service name.)

**Comment by jmolmo** [comment]
@liewegas : 
The service shown (orch ls) for osds created with "orch daemon add osd"  is [build](https://github.com/ceph/ceph/blob/ba5611283561114c66c302feaeacc85e0b1b6da6/src/pybind/mgr/cephadm/module.py#L1582) each time we invoke the "ls" command.

The result is a  non real service ([not present in the spec store]) that is presented like a service:

```
[ceph: root@cephLab2-node-00 /]# ceph orch daemon add osd cephLab2-node-00:/dev/vdc
Created osd(s) 4 on host 'cephLab2-node-00'

[ceph: root@cephLab2-node-00 /]# ceph orch ls --refresh
NAME                       RUNNING  REFRESHED   AGE  PLACEMENT    IMAGE NAME                                                                                          IMAGE ID      
....
osd.None                       1/0  0s ago      -    <unmanaged>  docker.io/ceph/daemon-base@sha256:8a9d01990f2601ea3111d84a18ba84a9043275cde1e48956a74b5a12e5e850b3  5c2a636e05b4  


[ceph: root@cephLab2-node-00 /]# ceph orch rm osd.None
Failed to remove service. <osd.None> was not found.

[ceph: root@cephLab2-node-00 /]# ceph orch ls osd --format yaml
service_type: osd
service_id: None
service_name: osd.None
placement:
  hosts:
  - cephLab2-node-00
spec:
  filter_logic: AND
  objectstore: bluestore
status:
  container_image_id: 5c2a636e05b4186feac98972e3f12d384ef4db25d7a0bd3d39477fb27a03a6a9
  container_image_name: docker.io/ceph/daemon-base@sha256:8a9d01990f2601ea3111d84a18ba84a9043275cde1e48956a74b5a12e5e850b3
  last_refresh: '2021-03-12T07:41:47.304697Z'
  running: 1
  size: 0
---
service_type: osd
service_id: all-available-devices
....
```

Respect the question  "how to link an OSD to the drivegroup/service that originally created it." .. you are right, now we have "service_name" in the "DaemonDescription" and this allow us to link services and daemons.
This is what I am going to use to delete the osds when the user delete a OSD service. 

Now the user only can delete OSD services created using drivegroup spec. ( or "all-available-devices") .. but not with "daemon add osd".  This modification fixes that.
Now if the user delete the OSD service .. it remains in status "deleting" until the user has deleted manually all the individual OSDs affected by the service ( this is not documented in any place). 
Next step is automate also the OSD deletion when the user deletes the service, but for that we need all the OSDs belong to one service.

**Comment by sebastian-philipp** [comment]
> Now if the user delete the OSD service .. it remains in status "deleting" until the user has deleted manually all the individual OSDs affected by the service ( this is not documented in any place).

Fixed in #40061

> Next step is automate also the OSD deletion when the user deletes the service, but for that we need all the OSDs belong to one service.

I think that is too scary!

**Comment by liewegas** [comment]
Two thoughts here:

- If we do this, and someone adds a bunch of OSDs "manually", we'll end up with a (long!) list of osd.NNNNNN service specs in the ``ceph orch ls`` output.  Do we really want that?  It seems messy. And I think it is pretty reasonable/common for users to be creating OSDs on an 'ad hoc' basis (e.g., I just replaced this failed drive... go create an OSD with that specific device on that specific host).
- This doesn't address the case of existing OSDs that predate this change; those will still appear in the ``osd.None`` (or similar).

I wonder if instead we should create something like osd.None that is a bit more graceful, like ``osd.unmanaged``.  This would be a "magic" service that would appear and collect all OSDs that don't belong to another service.

Then, separately, we make sure that the service_name is populated/plumbed down to unit.meta so that OSDs provisioned through a new spec/drivegroup are correctly associated with that service spec.  And then, if for some reason that spec is removed from the cluster, those OSDs would move over to the ``osd.unmanaged``...

WDYT?

**Comment by jmolmo** [comment]
Closed in favor of:
https://github.com/ceph/ceph/pull/40414

**Pull request closed without merging**
