### PR TITLE
osd/scrub: do not start scrubbing if the PG is snap-trimming

### PR DESCRIPTION
**Pull request by ronen-fr**
Both 'snap-trim' and 'snaptrim-wait' PG states will now prevent
scrub from starting.

Fixes: https://tracker.ceph.com/issues/49525

Signed-off-by: Ronen Friedman <rfriedma@redhat.com>

### CODE REVIEW

**Comment by ljflores** [comment]
jenkins test api

**Review by ljflores — APPROVED** [review]
Is this issue already tracked in https://tracker.ceph.com/issues/49525? Otherwise, LGTM

**Review by athanatos — APPROVED** [review]

**Comment by ronen-fr** [comment]
"Is this issue already tracked in https://tracker.ceph.com/issues/49525? Otherwise, LGTM"
@ljflores - yes, it is. Thanks.

**Comment by ronen-fr** [comment]
@neha-ojha - candidate for Quincy backport?

**Comment by neha-ojha** [comment]
> @neha-ojha - candidate for Quincy backport?

yes, https://tracker.ceph.com/issues/49525 was reported a more than a year ago, worth checking if pacific also needs the fix

**Comment by ronen-fr** [comment]
> > @neha-ojha - candidate for Quincy backport?
> 
> yes, https://tracker.ceph.com/issues/49525 was reported a more than a year ago, worth checking if pacific also needs the fix

The problem surely exists in Pacific. Actually - as far as I checked, the same omission exists in the original scrub code.

**Comment by ronen-fr** [comment]
Merging based on http://pulpito.front.sepia.ceph.com/yuriw-2022-06-01_23:19:00-rados-wip-yuri8-testing-2022-06-01-1114-distro-default-smithi.
No related issues.
Will follow with detailed list.

**Comment by rzarzynski** [comment]
Looks the quincy backport is: https://github.com/ceph/ceph/pull/46498.

**Pull request merged**
