### PR TITLE
unittest-seastar-socket: tolerate connection_reset in test_unexpected_down

### PR DESCRIPTION
**Pull request by athanatos**
Related: https://tracker.ceph.com/issues/64457

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Review by cbodley — APPROVED** [review]

**Comment by cbodley** [comment]
> The following tests FAILED:
	240 - unittest-seastar-socket (Subprocess aborted)

> INFO  2024-02-16 01:45:50,302 [shard 0:main] test - test_unexpected_down()...
INFO  2024-02-16 01:45:50,332 [shard 1:main] test - dispatch_sockets(): accepted at shard 1
ERROR 2024-02-16 01:45:50,406 [shard 0:main] test - test_unexpected_down(): client get error std::system_error (error system:104, recv: Connection reset by peer)
ERROR 2024-02-16 01:45:50,407 [shard 0:main] none - /home/jenkins-build/build/workspace/ceph-pull-requests/src/test/crimson/test_socket.cc:453 : In function 'auto (anonymous namespace)::test_unexpected_down(bool)::(anonymous class)::operator()(crimson::net::Socket *)::(anonymous class)::operator()(const std::system_error &) const', ceph_assert(%s)
e.code() == error::read_eof
Aborting on shard 0.

**Review by liu-chunmei — APPROVED** [review]

**Comment by athanatos** [comment]
jenkins test make check

**Comment by athanatos** [comment]
@liu-chunmei I pushed a commit tolerating connection_reset -- can you take another look?

**Comment by athanatos** [comment]
jenkins test make check

**Comment by athanatos** [comment]
make check apparently failed due to npm failing to pull a dependency, rerunning.

**Review by Matan-B — APPROVED** [review]

**Comment by cyx1231st** [comment]
> It seems like 'Connection reset by peer' is a valid error for the write side if the read side happens to force_close first, which seems possible for that test. Does that sound right to you?

@athanatos Reasonable to me.

I implemented this test to confirm the possible exceptions when the crimson messenger uses seastar sockets, might need to revisit the messenger code to make sure the added exception is handled correctly.

**Pull request merged**
