### PR TITLE
cmake: set CMAKE_BUILD_TYPE only if .git exists

### PR DESCRIPTION
**Pull request by tchaikov**
distros intend to fine tune the CFLAGS and CXXFLAGS by themselves, see

- https://git.alpinelinux.org/abuild/tree/abuild.conf
- https://wiki.archlinux.org/title/CMake_package_guidelines#CMake_undesired_behaviors
- https://github.com/Debian/debhelper/blob/5d1bb29841043d8e47ebbdd043e6cd086cad508e/lib/Debian/Debhelper/Buildsystem/cmake.pm#L16

so instead of setting a CMAKE_BUILD_TYPE when building from a
dist tarball, let's just leave it empty.

Signed-off-by: Kefu Chai <kchai@redhat.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by tchaikov** [comment]
```
self = <cherrypy.process.wspbus.Bus object at 0x7fd62efb17c0>, channel = 'start'
args = (), kwargs = {}
exc = OSError("No socket could be created -- (('127.0.0.1', 54583): [Errno 98] Address already in use)")
output = [None, None]
raw_items = <generator object Bus.publish.<locals>.<genexpr> at 0x7fd62941d040>
items = [(50, <cherrypy._cpchecker.Checker object at 0x7fd62eeeee20>), (50, <bound method RequestCounter.start of <cherrypy.li...object at 0x7fd62abf62b0>>), (75, <bound method Server.start of <cherrypy._cpserver.Server object at 0x7fd62ef425b0>>)]
priority = 75
listener = <bound method Server.start of <cherrypy._cpserver.Server object at 0x7fd62ef425b0>>
```

**Comment by tchaikov** [comment]
jenkins test make check

**Comment by tchaikov** [comment]
- https://pulpito.ceph.com/kchai-2021-07-01_14:09:56-rados-wip-kefu-testing-2021-07-01-1912-distro-basic-smithi/
- https://pulpito.ceph.com/kchai-2021-07-02_03:53:50-rados-wip-kefu-testing-2021-07-02-0958-distro-basic-smithi/
- https://pulpito.ceph.com/kchai-2021-07-02_12:31:26-rados-wip-kefu-testing-2021-07-02-1417-distro-basic-smithi/

failures are not related to this changeset.

**Comment by tchaikov** [comment]
@markhpc @batrick @jdurgin @neha-ojha ping?

**Review by batrick — APPROVED** [review]

**Pull request merged**
