### PR TITLE
librbd: remove last synchronous librados calls from open/close state machine

### PR DESCRIPTION
**Pull request by dillaman**
Switched to the newly added aio_watch/aio_unwatch/aio_watch_flush librados API.  Now the librbd aio_open/aio_close methods are fully asynchronous.

### CODE REVIEW

**Comment by dillaman** [comment]
Depends on PR #7824

**Comment by jdurgin** [comment]
lgtm

**Comment by jdurgin** [comment]
Crash when blacklisted: http://qa-proxy.ceph.com/teuthology/joshd-2016-02-29_22:13:37-rbd-wip-josh-testing---basic-vps/35784/teuthology.log

**Comment by jdurgin** [comment]
not sure exactly which patch, but valgrind detected an issue with fsx: http://qa-proxy.ceph.com/teuthology/joshd-2016-02-29_22:23:19-rbd-wip-josh-testing---basic-mira/35793/remote/mira078/log/valgrind/

**Comment by dillaman** [comment]
Fixed the blacklist assert failure.  The valgrind issue is on master already -- I will look into it (race condition in librados linger ops populating the object version within the AioCompletion after the completion has already been destroyed).

**Comment by dillaman** [comment]
aio_notify race condition covered in PR #7864

**Pull request merged**
