### PR TITLE
jewel: rgw: segfaults after running radosgw-admin data sync init

### PR DESCRIPTION
**Pull request by oritwas**
http://tracker.ceph.com/issues/22182

### CODE REVIEW

**Comment by shinobu-x** [comment]
@oritwas can you follow the following guide?

http://tracker.ceph.com/projects/ceph-releases/wiki/HOWTO_backport_commits

**Comment by cbodley** [comment]
@shinobu-x is there anything missing other than a link to the tracker issue? http://tracker.ceph.com/issues/22182

**Comment by shinobu-x** [comment]
@cbodley commit title of this PR needs to be:
> jewel: rgw segfaults after running radosgw-admin data sync init

**Comment by smithfarm** [comment]
The commits look like they were cherry-picked properly. The PR title can be "anything" - just keep in mind that the PR title determines how the fix appears in the release notes.

**Comment by smithfarm** [comment]
Integration testing: http://tracker.ceph.com/issues/21742#note-11

Will post a summary to the PR when the testing is complete.

**Comment by smithfarm** [comment]
This PR passed two RGW runs at http://tracker.ceph.com/issues/21742#note-11

It will be merged soon, unless there any objections.

**Pull request merged**
