### PR TITLE
tools/rados/rados.cc: fix rados rm --force-full blocking problem

### PR DESCRIPTION
**Pull request by yanghonggang**
Fixes: https://tracker.ceph.com/issues/36177
Signed-off-by: Yang Honggang <yanghonggang@umcloud.com>

### CODE REVIEW

**Comment by gregsfortytwo** [comment]
Hmm, it seems like FULL_TRY shouldn't be necessary for this to work; do we have a conditional somewhere that checks FULL_TRY and not FULL_FORCE?

**Comment by gregsfortytwo** [comment]
Hmm, it seems like FULL_TRY shouldn't be necessary for this to work; do we have a conditional somewhere that checks FULL_TRY and not FULL_FORCE?

(Also: jenkins retest this please)

**Comment by xiexingguo** [comment]
> Hmm, it seems like FULL_TRY shouldn't be necessary for this to work; do we have a conditional somewhere that checks FULL_TRY and not FULL_FORCE?

https://github.com/ceph/ceph/blob/master/src/osd/PrimaryLogPG.cc#L2052
Seems we use FULL_TRY for unconditionally removals, even if we are failsafe_full

**Comment by gregsfortytwo** [comment]
Can we fix that as well @yanghonggang so this doesn't bite future devs as well?

**Comment by xiexingguo** [comment]
> Can we fix that as well @yanghonggang so this doesn't bite future devs as well?

@gregsfortytwo I don't think so. See https://github.com/ceph/ceph/pull/17177 for the details.

**Pull request merged**
