### PR TITLE
mgr/cephadm: host _no_schedule label prevents placing daemons on a host

### PR DESCRIPTION
**Pull request by liewegas**
This will both prevent new daemons and lead to removal of old (non-OSD) daemons.

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by liewegas** [comment]
jenkins test docs

**Review by mgfritch — APPROVED** [review]
This works, but I do wonder if a simple bool flag in the host inventory would be preferable over adding a host label with special meaning

**Comment by liewegas** [comment]
jenkins test docs

**Review by adk3798 — APPROVED** [review]

**Review by jmolmo — APPROVED** [review]

**Comment by liewegas** [comment]
jenkins test docs

**Comment by liewegas** [comment]
jenkins test docs

**Pull request merged**
