### PR TITLE
mimic: rpm: should change ceph-mgr package depency from py-bcrypt to python2-bcrypt

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/27212

### CODE REVIEW

**Comment by yuriw** [comment]
[wip-yuri-testing-2018-09-02-2228-mimic](https://trello.com/c/NY950iNm/384-wip-yuri-testing-2018-09-02-2228-mimic)

**Comment by yuriw** [comment]
@smithfarm this is ready for merge after review is completed .

**Comment by sebastian-philipp** [comment]
See #23648. Looks innocent to me.

**Comment by smithfarm** [comment]
@sebastian-philipp Thanks. Can you approve so we can merge the PR?

**Pull request merged**
