### PR TITLE
rgw: add support for Swift's ContainerTempUrls

### PR DESCRIPTION
**Pull request by rzarzynski**

### CODE REVIEW

**Comment by rzarzynski** [comment]
jenkins retest this please (`Makefile failed to find target `tests'`)

**Comment by rzarzynski** [comment]
Tempest hasn't found any regression here.

**Comment by rzarzynski** [comment]
Jenkins retest this please (`ERROR: Error fetching remote repo 'origin'`)

**Comment by rzarzynski** [comment]
jenkins retest this please (no log)

**Comment by mattbenjamin** [comment]
@rzarzynski seems still useful?

**Pull request closed without merging**
