### PR TITLE
mgr: do the shutdown in the right order

### PR DESCRIPTION
**Pull request by tchaikov**
Fixes: http://tracker.ceph.com/issues/19813

### CODE REVIEW

**Comment by liewegas** [comment]
I think the addresses the case where Mgr::init deadlocks with MgrStandby::shutdown, but it doesn't address teh more general/common case of MgrStandby::handle_mgr_map() doing a synchronous active_mgr->shutdown() (and blocking the dispatch thread) while Mgr::init() is still running and waiting for messages from the mon.

I think the options are

1. make Mgr init etc state-driven so that it doesn't block and we can kill it at any time.
2. give Mgr its own messenger and dispatch thread
3. make MgrStandby have needs_stop, need_start etc states and make Mgr shutdown also asynchronous.

?

**Comment by tchaikov** [comment]
the state-driven approach looks more a better way to fix these racing issues. i think we can have this fix, and in the meanwhile, pull together a fix to make mgr state-driven.

**Comment by liewegas** [comment]
Okay, that works for me.  Have you run this through the qa suite yet?  I think that is probably the test of whether it'll be a viable interim solution

**Comment by tchaikov** [comment]
@liewegas will include it in my next test batch.

**Comment by tchaikov** [comment]
- http://pulpito.ceph.com/kchai-2017-05-06_17:11:36-rados-wip-kefu-testing---basic-mira/
- http://pulpito.ceph.com/kchai-2017-05-09_10:05:25-rados-wip-kefu-testing---basic-mira/

**Comment by tchaikov** [comment]
@liewegas the PR passed the rados qa run, can we merge it?

**Comment by tchaikov** [comment]
will keep http://tracker.ceph.com/issues/19813 open until we have a complete solution.

**Pull request merged**
