### PR TITLE
mon: unregister command on shutdown

### PR DESCRIPTION
**Pull request by renhwztetecs**
unregister command on shutdown
include: "quorum enter" && "quorum exit"

Signed-off-by: huanwen ren <ren.huanwen@zte.com.cn>

### CODE REVIEW

**Comment by xiexingguo** [comment]
So hard working you are:-)

**Comment by songbaisen** [comment]
It is really work hard.

**Comment by jecluis** [comment]
@renhwztetecs changes look fine.

Let me nit pick the commit message though. It would be great if you could adjust it to be a bit more comprehensible. Instead of `mon:lack of unregister of object in shutdown()`, something like `mon: Monitor: unregister command on shutdown` would be perfect.

**Comment by renhwztetecs** [comment]
@jecluis
hmm,before the description is more redundant, I change it
Thanks a lot for your advice

**Comment by liewegas** [comment]
More nit picking: 

- there is always a space after a colon
- mon: Monitor: is redundant... just "mon: unregister command on shutdown" is sufficient

**Comment by renhwztetecs** [comment]
@liewegas after you remind, I noticed the colon need a space

**Pull request merged**
