### PR TITLE
luminous: rgw: add list user admin OP API

### PR DESCRIPTION
**Pull request by k0ste**
tracker: https://tracker.ceph.com/issues/37073
backport of: #25073

### CODE REVIEW

**Comment by yuriw** [comment]
[wip-yuri2-testing-2019-11-18-1527-luminous](https://trello.com/c/mroVe20D/767-wip-yuri2-testing-2019-11-18-1527-luminous)

**Comment by smithfarm** [comment]
@k0ste For the next backport, could you use the Conflicts section that git provides (all you have to do is uncomment it before accepting the commit message)? It looks like this:

```
Conflicts:
        src/rgw/rgw_user.h
```

To this, you can append your comments.

**Comment by k0ste** [comment]
Of course, I just forgot to uncomment this line.

**Comment by smithfarm** [comment]
At some point in the future, there will be a Jenkins check for this... until then it's not a big deal.

**Pull request merged**
