### PR TITLE
rgw/sal: get_notification() takes optional_yield

### PR DESCRIPTION
**Pull request by cbodley**
not all calls use `s->yield`, so pass in the `optional_yield` argument separately

Fixes: https://tracker.ceph.com/issues/58231

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by cbodley** [comment]
cc @cfsnyder

**Review by dang — APPROVED** [review]

**Comment by yuvalif** [comment]
can we unify the use of `optional_yield`?
is there a rule when to pass as argument and when to take from `req_state`

**Comment by cbodley** [comment]
> can we unify the use of `optional_yield`? is there a rule when to pass as argument and when to take from `req_state`

i'd say use s->yield in RGWOp logic, unless the op spawns other coroutines like RGWDeleteMultiObj. otherwise pass optional_yield

**Comment by yuvalif** [comment]
> > can we unify the use of `optional_yield`? is there a rule when to pass as argument and when to take from `req_state`
> 
> i'd say use s->yield in RGWOp logic, unless the op spawns other coroutines like RGWDeleteMultiObj. otherwise pass optional_yield

but how would the devloper know if it is safe to use `s->yield`or if it going to crash?

**Comment by cbodley** [comment]
> but how would the devloper know if it is safe to use `s->yield`or if it going to crash?

`s->yield` represents the request coroutine spawned by the beast frontend. think of that like a thread of execution. if you're running inside of that coroutine, it's safe to yield on it

**Comment by cbodley** [comment]
> but inside the notification code i have no idea if it is safe or not

that's why this PR stops using it there

> maybe we should set s->yield to nullopt if we use the req_state in another coroutine?

i had put it in `req_state` as a convenience for `RGWOp`s, but it looks like @alimaredia has already threaded this `optional_yield` argument through most of the `RGWHandler`/`RGWOp` calls under `process_request()`. we should probably get rid of `s->yield` entirely by passing the yield context everywhere else it needs to go

**Review by yuvalif — APPROVED** [review]

**Comment by cbodley** [comment]
jenkins test make check

**Comment by cbodley** [comment]
passed qa in https://pulpito.ceph.com/cbodley-2022-12-20_15:43:17-rgw-wip-cbodley-testing-distro-default-smithi/

**Pull request merged**
