### PR TITLE
mon/monitor: some clean up

### PR DESCRIPTION
**Pull request by renhwztetecs**
some clean up

Signed-off-by: huanwen ren <ren.huanwen@zte.com.cn>

### CODE REVIEW

**Comment by renhwztetecs** [comment]
@xiexingguo 
oh! yes
thanks

**Comment by tchaikov** [comment]
lgtm with a nit,

**Comment by jecluis** [comment]
I don't think it's such a great idea removing the 'get_leader_supported_commands()' function. Albeit being unused, it does gives an hint as to how it ought to be used; and it's still a getter that may be used in the future. I don't see a compelling argument besides "not being used at the moment" to get rid of it.

Also, please make sure your commit messages have a space following the colon. I know this is a rather annoying nit, but for the sake of consistency with other commits in the tree, instead of `mon:Monitor:whatever` use `mon: Monitor: whatever`.

**Comment by renhwztetecs** [comment]
@tchaikov 
thank you for your review
Taking into account https://github.com/ceph/ceph/pull/7520/files#diff-d4e1ba36dd08617ea271ab2be3dbcb5bL1612 does not use "MMonProbe *r", the definition of the global "MMonProbe *r" to https://github.com/renhwsky/ceph/commit/2f5c9830ec058ddc75de9dd400e0f6990e79dd9b#diff-d4e1ba36dd08617ea271ab2be3dbcb5bR1628 is better
I have changed it

**Comment by renhwztetecs** [comment]
@jecluis 
thank you for your review
Delete function is not used in order to simplify the code, easy to use and learn,
For the possible use of functional interface, can be used in real time to add more good? I'm not sure if this is true!

**Comment by liewegas** [comment]
passed rados test.  @jecluis ok with removing that helper?  or leave it?

**Comment by jecluis** [comment]
@liewegas yeah, let's remove it. lgtm.

**Pull request merged**
