### PR TITLE
src/test: Test case for bilog trim across reshard event

### PR DESCRIPTION
**Pull request by TRYTOBE8TME**
Resharding a bucket and then performing the bilog trim

Signed-off-by: Kalpesh Pandya <kapandya@redhat.com>

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by cbodley** [comment]
thanks, this is a good start

i don't think this test should worry about cold vs. hot buckets, since the original bilog trim test covers that stuff. so you can just use a single bucket, and ignore the extra options like --rgw-sync-log-trim-max-buckets and --rgw-sync-log-trim-min-cold-buckets

each time a bucket is resharded, we create a new bilog. so this test will have to list these logs separately: `radosgw-admin bilog list --gen=0` will show the object uploads before reshard, and `--gen=1` will show entries after reshard

trim also has new logic to delete the old log generations entirely, so i'd like to verify that part too. i think that will require `radosgw-admin metadata get` on the bucket instance metadata, and inspecting its array of layout.logs

cc @adamemerson

**Comment by cbodley** [comment]
> i think that will require `radosgw-admin metadata get` on the bucket instance metadata, and inspecting its array of layout.logs

i added a new `radosgw-admin bucket layout --bucket=name` command in https://github.com/ceph/ceph/pull/44947 to simplify this part

**Comment by TRYTOBE8TME** [comment]
> trim also has new logic to delete the old log generations entirely, so i'd like to verify that part too. i think that will require `radosgw-admin metadata get` on the bucket instance metadata, and inspecting its array of layout.logs

@cbodley Can you please elaborate this part or maybe can give a hint on how this can be done?

**Comment by cbodley** [comment]
hey @TRYTOBE8TME, i'd start by creating a bucket with some objects in it, then playing around with `radosgw-admin bucket layout`, and see how it changes after you run `radosgw-admin bucket reshard`. each time you reshard, you should see an extra entry in the `logs`, until you hit the maximum number of logs at 4

then, once the other zone is all caught up with sync, you can run `radosgw-admin bilog autotrim` and see how that changes the output of `radosgw-admin bucket layout`. each time `bilog autotrim` runs, you should see one *less* entry the list of `logs`, until there's only one entry left

this is exactly what we want to write a test for; for example, do 2 reshards and verify that `bucket layout` shows 3 logs. then do a bucket checkpoint to wait for sync to catch up. then `bilog autotrim` and verify that `bucket layout` removes 1 of the logs, then that another `bilog autotrim` removes another. finally, verify that `bilog autotrim` doesn't remove the last log

**Comment by adamemerson** [comment]
@TRYTOBE8TME Before you get on to anything else, can you rebase this?

**Comment by TRYTOBE8TME** [comment]
> @TRYTOBE8TME Before you get on to anything else, can you rebase this?

@adamemerson sorry, I've created a new alias PR for this #45053

**Pull request closed without merging**
