### PR TITLE
reef: qa: switch to use the merge fragment for fscrypt

### PR DESCRIPTION
**Pull request by lxbsz**
backport tracker: https://tracker.ceph.com/issues/64655

---

backport of https://github.com/ceph/ceph/pull/50728
parent tracker: https://tracker.ceph.com/issues/59195

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Comment by lxbsz** [comment]
jenkins retest this please

**Comment by leonid-s-usov** [comment]
jenkins test make check

**Comment by leonid-s-usov** [comment]
jenkins test windows

**Comment by leonid-s-usov** [comment]
jenkins test make check

**Review by joscollin — CHANGES_REQUESTED** [review]
We have a failure in `test_fscrypt_dummy_encryption_with_quick_group`
https://pulpito.ceph.com/leonidus-2024-06-16_14:19:11-fs-wip-lusov-testing-20240616.100042-reef-distro-default-smithi/7758502/

@lxbsz Please check?

**Comment by lxbsz** [comment]
> We have a failure in `test_fscrypt_dummy_encryption_with_quick_group` https://pulpito.ceph.com/leonidus-2024-06-16_14:19:11-fs-wip-lusov-testing-20240616.100042-reef-distro-default-smithi/7758502/
> 
> @lxbsz Please check?

@joscollin These 6 failures are not related to this change. They are known and new bugs, I will work on it separately.

**Review by joscollin — APPROVED** [review]
Failures are unrelated

**Review by joscollin — CHANGES_REQUESTED** [review]
@lxbsz This can't be merged because of `make check` failure. Could you please rebase this?

**Comment by joscollin** [comment]
jenkins test api

**Comment by lxbsz** [comment]
jenkins test api

**Review by joscollin — APPROVED** [review]

**Pull request merged**
