### PR TITLE
luminous: debian: correct ceph-common relationship with older radosgw package

### PR DESCRIPTION
**Pull request by mcv21**
https://tracker.ceph.com/issues/37274

### CODE REVIEW

**Comment by mcv21** [comment]
(the docs test looks to have failed due to a network error...)

**Comment by tchaikov** [comment]
@mcv21 Matthew, thanks for fixing the broken debian packaging. normally, if a bug exists in both LTS branches and master, we intend to

1. create a ticket at http://tracker.ceph.com , mark the "Backport:" field of tracker with the impacted branches.
1. fix it in master, then
1. change the status of the tracker to "Pending Backport", and then
1. backport the fix to the impacted branches by cherry-picking the fix to these branches

**Comment by mcv21** [comment]
The adjacent PR #24996 fixes it in master (this is just a cherry-pick of that); it's not really office hours right now, so do you want to make the tracker ticket? Otherwise I'll do so tomorrow.

**Comment by tchaikov** [comment]
@mcv21 by "cherry-pick" , i mean `git cherry-pick -x`. so we can connect the fix in LTS branches to the one in master. and to avoid to extra efforts (for example, the sha1 of the commit changes if you update the commit targeting master), you might want to wait until the PR targeting master is merged.

yeah, it'd be great if you could help on it.

**Comment by mcv21** [comment]
OK (I did cherry-pick, but missed the -x). As you suggest, I'll wait to re-do the cherry-pick until #24996 is merged. I've opened https://tracker.ceph.com/issues/36741 (and linked that from the other PR).

**Comment by mcv21** [comment]
[the docs build failure is some bit of Jenkins having a network issue...]
```
 Caused by: hudson.plugins.git.GitException: Command "git fetch --tags --progress https://github.com/ceph/ceph +refs/pull/*:refs/remotes/origin/pr/*" returned status code 128:
stdout: 
stderr: error: RPC failed; curl 18 transfer closed with outstanding read data remaining
fatal: The remote end hung up unexpectedly
```

**Comment by mcv21** [comment]
@tchaikov The original PR has been merged (thanks :) ), so I have now re-done this PR with a `git cherry-pick -x` of that commit.

**Comment by tchaikov** [comment]
jenkins, retest this please.

**Comment by mcv21** [comment]
PR text updated to reflect new tracker issue made for the luminous backport
[do you want me to open a PR with the relevant Mimic cherry-pick too?]

**Comment by tchaikov** [comment]
@mcv21 then you'd need to create a backport tracker ticket for mimic first. @smithfarm kindly created the one for luminous.

**Comment by smithfarm** [comment]
@tchaikov @mvc21 mimic backport tracker issue is https://tracker.ceph.com/issues/37273

**Comment by smithfarm** [comment]
@mcv21 You are not required to do the cherry-picking to mimic - the tracker is open, someone will pick it up.

**Comment by mcv21** [comment]
@smithfarm thanks, I figured I'd do it while I was thinking about it - https://github.com/ceph/ceph/pull/25115

**Comment by mcv21** [comment]
@yuriw I'm not sure what I should understand by your comment, but I can't see that trello card.

**Comment by tchaikov** [comment]
@mcv21 i think it's a note for Yuri himself. but probably you can consider it as a message that your change is now included in his test batch, and the test branch is named wip-yuri-testing-2019-01-07-1727-luminous . if you are really curious, you can search the tests against this branch at pulpito, see http://pulpito.ceph.com/?branch=wip-yuri-testing-2019-01-07-1727-luminous

**Comment by mcv21** [comment]
@tchaikov thanks for satisfying my curiosity :)

**Pull request merged**
