### PR TITLE
pacific: librbd/cache/pwl: persistant cache backports 

### PR DESCRIPTION
**Pull request by ideepika**
<google-sheets-html-origin><style type="text/css"></style>

parent tracker | backport tracker | status
-- | -- | --
https://tracker.ceph.com/issues/50560 | https://tracker.ceph.com/issues/50609 | https://github.com/ceph/ceph/pull/41068
https://tracker.ceph.com/issues/50589 | https://tracker.ceph.com/issues/50615 | https://github.com/ceph/ceph/pull/41093
https://tracker.ceph.com/issues/50669 | https://tracker.ceph.com/issues/50856 | https://github.com/ceph/ceph/pull/41354
https://tracker.ceph.com/issues/50670 | https://tracker.ceph.com/issues/52310 | https://github.com/ceph/ceph/pull/41968
https://tracker.ceph.com/issues/50675 | TBA |  
https://tracker.ceph.com/issues/49819 | needs fix |  
https://tracker.ceph.com/issues/49876 | needs fix |  
https://tracker.ceph.com/issues/51438 | needs fix |  
https://tracker.ceph.com/issues/50832 | https://tracker.ceph.com/issues/51670 | https://github.com/ceph/ceph/pull/41490
https://tracker.ceph.com/issues/50951 | https://tracker.ceph.com/issues/51669 | https://github.com/ceph/ceph/pull/42145
https://tracker.ceph.com/issues/50734 | needs fix |  
https://tracker.ceph.com/issues/51418 | https://tracker.ceph.com/issues/52092 | https://github.com/ceph/ceph/pull/42149
https://tracker.ceph.com/issues/52090 | https://tracker.ceph.com/issues/52111 | https://github.com/ceph/ceph/pull/42581
https://tracker.ceph.com/issues/52236 | https://tracker.ceph.com/issues/52281 | https://github.com/ceph/ceph/pull/42580
https://tracker.ceph.com/issues/52323 | https://tracker.ceph.com/issues/52422 | https://github.com/ceph/ceph/pull/42843
https://tracker.ceph.com/issues/52341 | https://tracker.ceph.com/issues/52569 | https://github.com/ceph/ceph/pull/42883
https://tracker.ceph.com/issues/49879 | https://tracker.ceph.com/issues/50576 | had some issues not backported yet
https://tracker.ceph.com/issues/52465 | https://tracker.ceph.com/issues/52536 | https://github.com/ceph/ceph/pull/43006
https://tracker.ceph.com/issues/52400 | https://tracker.ceph.com/issues/52570 | https://github.com/ceph/ceph/pull/42984
https://tracker.ceph.com/issues/51438 | https://tracker.ceph.com/issues/52584 | https://github.com/ceph/ceph/pull/43038 needs investigation, tests are actually disabled
https://tracker.ceph.com/issues/52579 | https://tracker.ceph.com/issues/52585 | https://github.com/ceph/ceph/pull/42555
https://tracker.ceph.com/issues/52852 | https://tracker.ceph.com/issues/52882 | https://github.com/ceph/ceph/pull/43182
https://tracker.ceph.com/issues/52511 | https://tracker.ceph.com/issues/53114 | https://github.com/ceph/ceph/pull/43127
other cherry-picks |   |  
https://tracker.ceph.com/issues/53116 | https://tracker.ceph.com/issues/53118 | https://github.com/ceph/ceph/pull/40718
https://tracker.ceph.com/issues/50670 | https://tracker.ceph.com/issues/52310 | https://github.com/ceph/ceph/pull/41968
https://tracker.ceph.com/issues/52852 | https://tracker.ceph.com/issues/52882 | https://github.com/ceph/ceph/pull/43182
https://tracker.ceph.com/issues/49879 | https://tracker.ceph.com/issues/50576 | https://github.com/ceph/ceph/pull/40493
52235, 52566 |   | https://github.com/ceph/ceph/pull/42950/
https://tracker.ceph.com/issues/52599 | https://tracker.ceph.com/issues/53141 | https://github.com/ceph/ceph/pull/43461
listed but not in PR |   |  
https://tracker.ceph.com/issues/51419 | https://tracker.ceph.com/issues/51605 | https://github.com/ceph/ceph/pull/42112
  | build stuff | https://github.com/ceph/ceph/pull/41022/
  | build stuff | https://github.com/ceph/ceph/pull/40493
  |   | https://github.com/ceph/ceph/pull/40866

### CODE REVIEW

**Comment by ideepika** [comment]
cc @CongMinYin

**Comment by ideepika** [comment]
@trociny looks ready for review
https://pulpito.ceph.com/ideepika-2021-11-08_13:37:50-rbd-wip-ssd-cache-testing-backports-pacific-distro-basic-smithi/

**Review by trociny — APPROVED** [review]

**Comment by trociny** [comment]
> https://pulpito.ceph.com/ideepika-2021-11-08_13:37:50-rbd-wip-ssd-cache-testing-backports-pacific-distro-basic-smithi/

Interesting "v1 cli_generic" failures. I don't see how they could be related though. Do we observe the same on master?

**Comment by ideepika** [comment]
> > https://pulpito.ceph.com/ideepika-2021-11-08_13:37:50-rbd-wip-ssd-cache-testing-backports-pacific-distro-basic-smithi/
> 
> Interesting "v1 cli_generic" failures. I don't see how they could be related though. Do we observe the same on master?

yep on master as well as pacific: https://pulpito.ceph.com/teuthology-2021-10-25_02:01:03-rbd-master-distro-default-gibba/

**Comment by ideepika** [comment]
rerun: https://pulpito.ceph.com/ideepika-2021-11-09_20:00:16-rbd-wip-deepika-testing-pacific-distro-basic-smithi/

**Pull request merged**
