### PR TITLE
quincy: qa/orch: drop centos 8 and rhel 8.6 for orch suite tests

### PR DESCRIPTION
**Pull request by adk3798**
We don't build those distros for quincy any more. These changes are required to schedule an orch/cephadm run on quincy branch currently. Includes backport of https://github.com/ceph/ceph/pull/58290 and a commit from https://github.com/ceph/ceph/pull/53901

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Review by ljflores — APPROVED** [review]
I added a commit to address the quincy-p2p tests in the upgrade suite.

Otherwise, LGTM. I checked by scheduling an orch and upgrade suite in teuthology with --dry-run (this option errors out if any of the jobs reference packages we don't build anymore)

**Comment by adk3798** [comment]
just added https://github.com/ceph/ceph/pull/58290 to this backport as we need it for all the centos 9 jobs that use the nvme loop task to pass (e.g. https://pulpito.ceph.com/adking-2024-07-23_21:34:47-orch:cephadm-wip-adk5-testing-2024-07-23-1249-quincy-distro-default-smithi/7815112)

**Comment by adk3798** [comment]
also added https://github.com/ceph/ceph/commit/97efa97c2c72dba32774d0f105ae90462b93ac4e to this PR as it's needed for one of the iscsi tests to pass

**Comment by adk3798** [comment]
https://pulpito.ceph.com/adking-2024-07-24_12:36:52-orch:cephadm-wip-adk5-testing-2024-07-23-1249-quincy-distro-default-smithi/

run of iscsi tests after additional patch was added: https://pulpito.ceph.com/adking-2024-07-25_11:07:08-orch:cephadm-wip-adk5-testing-2024-07-23-1249-quincy-distro-default-smithi/

Not counting the failed iscsi test that passed with the additional patch, failures were:

- 1 `test_non_existent_cluster ` failure, known issue, just missing a backport to update the test
- All other failures were test_cephadm, test_cephadm_repos, or mds_upgrade_sequence. All failed trying to pull packages that did not exist. This is mostly fallout of the move to centos 9. These tests are trying to do things like pull pacific packages for centos 9, or main branch builds on ubuntu focal, which don't exist. Unfortunate, but not worth blocking merging PRs in the run. The issues are more so with the tests than the ceph build itself.

**Comment by adk3798** [comment]
jenkins test make check

**Comment by ljflores** [comment]
@adk3798 I wanted to bring a few issues to your attention from the teuthology run:

* I filed https://tracker.ceph.com/issues/67561 for several jobs that failed when trying to pull pacific containers. I see you already ack'ed that on the QA tracker, but I wanted to bring it to your attention since ideally this should be addressed before merging the PR.

* I also saw a new dashboard failure concerning nodejs.
Found in this job: /a/yuriw-2024-08-01_19:59:16-rados-wip-yuri5-testing-2024-08-01-0821-quincy-distro-default-smithi/7830663
This was actually already fixed in earlier releases when we made the switch to centos 9 stream. See https://github.com/ceph/ceph/pull/53901#issuecomment-1904767173 for an explanation.
We need to backport this commit, which can be included in your PR before it gets merged: https://github.com/ceph/ceph/pull/53901/commits/a602e5f0e0e48c40fd728ae382502826ca354828

**Comment by adk3798** [comment]
jenkins test make check

**Comment by adk3798** [comment]
jenkins test api

**Comment by adk3798** [comment]
orch/cephadm run with most recent patches here: https://pulpito.ceph.com/adking-2024-08-27_21:46:04-orch:cephadm-wip-adk5-testing-2024-08-27-0932-quincy-distro-default-smithi/

upgrade suite with most recent patches here: https://pulpito.ceph.com/adking-2024-08-27_21:50:25-upgrade-wip-adk5-testing-2024-08-27-0932-quincy-distro-default-smithi/

**Comment by yuriw** [comment]
jenkins test make check

**Pull request merged**
