### PR TITLE
os/bluestore: use db->rm_range_keys to delete range of keys

### PR DESCRIPTION
**Pull request by lixiaoy1**
As Key Value DB provides the rm_range_keys interface to remove
some range of keys, BlueStore should use the interface. DB can
provide more efficient ways.

Signed-off-by: Xiaoyan Li <xiaoyan.li@intel.com>

### CODE REVIEW

**Comment by xiexingguo** [comment]
I am pretty sure this will conflict with https://github.com/ceph/ceph/pull/18224 hence need a rebase as soon as that one gets in.
Drop the `need_qa` label for now.

**Comment by xiexingguo** [comment]
The change itself looks good

**Comment by xiexingguo** [comment]
@lixiaoy1 Need rebase (FYI:  it is https://github.com/ceph/ceph/pull/18224 which causes conflicts)

**Comment by lixiaoy1** [comment]
Thanks for the review, it is rebased.

**Comment by tchaikov** [comment]
@lixiaoy1 
could you prefix the title of your commit message with the subcomponent your are changing ? see https://github.com/ceph/ceph/blob/master/SubmittingPatches.rst#3-describe-your-changes, 

also, your "Signed-off-by" line does not look right. instead of 
```
Signed-off-by: Xiaoyan Li xiaoyan.li@intel.com
```
it should be
```
Signed-off-by: Xiaoyan Li <xiaoyan.li@intel.com>
```

**Comment by lixiaoy1** [comment]
@tchaikov Thank you for the review. The commit message is updated.

**Comment by tchaikov** [comment]
- http://pulpito.ceph.com/kchai-2017-10-17_02:10:23-rados-wip-kefu-testing-2017-10-16-2315-distro-basic-smithi/
- http://pulpito.ceph.com/kchai-2017-10-16_14:55:45-rados-wip-kefu-testing-2017-10-16-1746-distro-basic-smithi/

**Pull request merged**
