### PR TITLE
qa: fix cephfs-mirror unwinding and 'fs volume create/rm' order

### PR DESCRIPTION
**Pull request by joscollin**
Fixes: https://tracker.ceph.com/issues/61182

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [x] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by joscollin** [comment]
jenkins test windows

**Comment by vshankar** [comment]
@joscollin changes look fine. Could you share the 30 run iteration test run?

**Comment by joscollin** [comment]
> @joscollin changes look fine. Could you share the 30 run iteration test run?

I'm scheduling a new iteration test run. Will share that once finished.

**Comment by joscollin** [comment]
> @joscollin changes look fine. Could you share the 30 run iteration test run?

@vshankar 
http://pulpito.front.sepia.ceph.com/jcollin-2023-07-25_07:28:18-fs:mirror-ha-wip-B61182-cephfs-mirror-qa-distro-default-smithi/

**Review by vshankar — APPROVED** [review]

**Comment by vshankar** [comment]
@joscollin I think the commits can be squashed. Also, please update the commit message to explain the change. Otherwise LGTM.

**Comment by joscollin** [comment]
> @joscollin I think the commits can be squashed. Also, please update the commit message to explain the change. Otherwise LGTM.

Done.

**Review by vshankar — APPROVED** [review]

**Comment by joscollin** [comment]
jenkins test make check

**Comment by joscollin** [comment]
jenkins test api

**Comment by joscollin** [comment]
rebased

**Comment by joscollin** [comment]
jenkins test make check arm64

**Comment by joscollin** [comment]
jenkins test make check

**Pull request merged**
