### PR TITLE
doc: always load resources via HTTPS

### PR DESCRIPTION
**Pull request by tchaikov**
## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test docs`
- `jenkins render docs`

</details>

### CODE REVIEW

**Comment by tchaikov** [comment]
jenkins render docs

**Comment by tchaikov** [comment]
jenkins render docs

**Comment by tchaikov** [comment]
jenkins render docs

**Comment by tspmelo** [comment]
Please include the following 2 changes in this PR:
https://github.com/ceph/ceph/pull/29531/files#diff-2602a37e85b8976dfc2505da56885bfeR2
https://github.com/ceph/ceph/pull/29531/files#diff-f5a6e650769018ef3fc0e0d6f6e21bffR16

**Comment by tchaikov** [comment]
jenkins render docs

**Comment by tchaikov** [comment]
jenkins render docs

**Comment by tchaikov** [comment]
i am closing this issue for now. as it depends on https://tracker.ceph.com/issues/41160

**Comment by tchaikov** [comment]
jenkins render docs

**Pull request merged**
