### PR TITLE
osd: misc cleanups 

### PR DESCRIPTION
**Pull request by Songweibin**
Signed-off-by: songweibin song.weibin@zte.com.cn

### CODE REVIEW

**Comment by xiexingguo** [comment]
Please drop the last change, which has already been addressed by https://github.com/ceph/ceph/pull/17423

**Comment by Songweibin** [comment]
@xiexingguo Updated, thanks for your remind.

**Comment by Songweibin** [comment]
Jenkins retest this please

**Comment by tchaikov** [comment]
- http://pulpito.ceph.com/kchai-2017-09-04_18:32:24-rados-wip-kefu-testing-2017-09-05-0030-distro-basic-smithi/
- http://pulpito.ceph.com/kchai-2017-09-05_04:17:28-rados-wip-kefu-testing-2017-09-05-0030-distro-basic-smithi/

**Pull request merged**
