### PR TITLE
qa/rgw: renamed ssl task to openssl_keys

### PR DESCRIPTION
**Pull request by rjfd**
The ssl task located in a python file called `ssl.py` will generate
python module loading conflicts with the `ssl` system module, when
running QA tests using vstart_runner.py.

```
Traceback (most recent call last):
  File "vstart_runner.py", line 45, in <module>
    from teuthology.orchestra.run import Raw, quote
  File "/tmp/tmp.2q6u5iqppn/teuthology/teuthology/__init__.py", line 19, in <module>
    subprocess=False,
  File "/tmp/tmp.2q6u5iqppn/venv/lib/python2.7/site-packages/gevent/monkey.py", line 621, in patch_all
    patch_ssl()
  File "/tmp/tmp.2q6u5iqppn/venv/lib/python2.7/site-packages/gevent/monkey.py", line 463, in patch_ssl
    patch_module('ssl')
  File "/tmp/tmp.2q6u5iqppn/venv/lib/python2.7/site-packages/gevent/monkey.py", line 152, in patch_module
    gevent_module = getattr(__import__('gevent.' + name), name)
  File "/tmp/tmp.2q6u5iqppn/venv/lib/python2.7/site-packages/gevent/ssl.py", line 20, in <module>
    from gevent import _ssl2 as _source # pragma: no cover
  File "/tmp/tmp.2q6u5iqppn/venv/lib/python2.7/site-packages/gevent/_ssl2.py", line 16, in <module>
    _ssl = __ssl__._ssl
AttributeError: 'module' object has no attribute '_ssl'
```

Signed-off-by: Ricardo Dias <rdias@suse.com>

### CODE REVIEW

**Comment by sebastian-philipp** [comment]
This fixes vstart_runner.py. Without this PR, I'm getting:

```Traceback (most recent call last):
  File "../qa/tasks/vstart_runner.py", line 45, in <module>
    from teuthology.orchestra.run import Raw, quote
  File "/tmp/tmp.JMxJMZvBFT/teuthology/teuthology/__init__.py", line 19, in <module>
    subprocess=False,
  File "/tmp/tmp.JMxJMZvBFT/venv/local/lib/python2.7/site-packages/gevent/monkey.py", line 621, in patch_all
    patch_ssl()
  File "/tmp/tmp.JMxJMZvBFT/venv/local/lib/python2.7/site-packages/gevent/monkey.py", line 463, in patch_ssl
    patch_module('ssl')
  File "/tmp/tmp.JMxJMZvBFT/venv/local/lib/python2.7/site-packages/gevent/monkey.py", line 152, in patch_module
    gevent_module = getattr(__import__('gevent.' + name), name)
  File "/tmp/tmp.JMxJMZvBFT/venv/local/lib/python2.7/site-packages/gevent/ssl.py", line 20, in <module>
    from gevent import _ssl2 as _source # pragma: no cover
  File "/tmp/tmp.JMxJMZvBFT/venv/local/lib/python2.7/site-packages/gevent/_ssl2.py", line 16, in <module>
    _ssl = __ssl__._ssl
AttributeError: 'module' object has no attribute '_ssl'
```

**Comment by cbodley** [comment]
maybe `openssl_keys` or something? i'm not familiar with the term `sslayer`

**Comment by rjfd** [comment]
@cbodley I'm fine with `openssl_keys`, will change that.

**Comment by rjfd** [comment]
@cbodley pushed renaming to `openssl_keys`

**Comment by rjfd** [comment]
@cbodley this issue is blocking dashboard backend developers from running the QA tests locally, are we still missing something, or can we merge the PR?

**Pull request merged**
