### PR TITLE
luminous: mgr/balancer: blame if upmap won't actually work

### PR DESCRIPTION
**Pull request by k0ste**
http://tracker.ceph.com/issues/38781

### CODE REVIEW

**Comment by k0ste** [comment]
@xiexingguo

**Comment by smithfarm** [comment]
@liewegas @jan--f Is this something good (and not too risky) to have in luminous?

**Comment by xiexingguo** [comment]
I think it should be good to go.
- it does not change anything that is material
- it only matters when you manually enable balancer up-map mode, which should not be a concern for the upgrade case?

**Comment by xiexingguo** [comment]
> Out of interest, whats the reasoning for EPERM here?

I copied it from https://github.com/ceph/ceph/blob/master/src/mon/OSDMonitor.cc#L10948 :-)

`#define EPERM            1      /* Operation not permitted */`

but it also sounds good to me.

**Comment by k0ste** [comment]
v12.2.13?

**Comment by yuriw** [comment]
[wip-yuri2-testing-2019-07-15-1956-luminous](https://trello.com/c/5QdUgJyi/667-wip-yuri2-testing-2019-07-15-1956-luminous)

**Comment by dzafman** [comment]
@yuriw This breaks lots of tests because at least d-require-luminous/at-mkfs-balancer-upmap.yaml requires adding "ceph osd set-require-min-compat-client luminous" just like the change in master to d-balancer/upmap.yaml

**Comment by smithfarm** [comment]
@yuriw Did you really intend to re-queue this for another run?

**Comment by yuriw** [comment]
(Note to self - ref: https://github.com/ceph/ceph/pull/28644#issuecomment-514359581)

**Comment by k0ste** [comment]
> @k0ste
> Pls see @dzafman 's comments

Done.

**Comment by yuriw** [comment]
[wip-yuri3-testing-2019-07-25-2227-luminous](https://trello.com/c/7h1LQO8C/677-wip-yuri3-testing-2019-07-25-2227-luminous)

**Pull request merged**
