### PR TITLE
octopus: mgr/volumes: Add interface to get subvolume metadata

### PR DESCRIPTION
**Pull request by kotreshhr**
The following interface is added

"ceph fs subvolume info <vol_name> <sub_name> [<group_name>]"

The output is in json format with following fields

1. atime: access time of subvolume path in the format "YYYY-MM-DD HH:MM:SS"
2. mtime: modification time of subvolume path in the format "YYYY-MM-DD HH:MM:SS"
3. ctime: change time of subvolume path in the format "YYYY-MM-DD HH:MM:SS"
4. uid: uid of subvolume path
5. gid: gid of subvolume path
6. mode: mode of subvolume path
7. mon_addrs: list of monitor addresses
8. bytes_pcent: quota used in percentage if quota is set, else displays "undefined"
9. bytes_quota: quota size in bytes if quota is set, else displays "infinite"
10. bytes_used: current used size of the subvolume in bytes
11. created_at: time of creation of subvolume in the format "YYYY-MM-DD HH:MM:SS"
12. data_pool: data pool the subvolume belongs to
13. path: absolute path of a subvolume
14. type: subvolume type indicating whether it's clone or subvolume

Fixes: https://tracker.ceph.com/issues/45180
Signed-off-by: Kotresh HR <khiremat@redhat.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by kotreshhr** [comment]
@ajarr please take a look

**Comment by ajarr** [comment]
> the commit message is missing a `(cherry picked from commit yxz)` message. did you use git cherry-pick -x ?

you should @kotreshhr use `git cherry-pick -x <original-commit>` as @sebastian-philipp says

**Comment by kotreshhr** [comment]
> > the commit message is missing a `(cherry picked from commit yxz)` message. did you use git cherry-pick -x ?
> 
> @kotreshhr use `git cherry-pick -x <original-commit>` as @sebastian-philipp says
> 
> And no need to edit the `Fixes` label to match the octopus tracker ticket. Leave the original tracket ticket as is.

@ajarr @sebastian-philipp I had not cherry-picked from original commit. Done. But it was not a clean apply. I had to resolve the minor conflicts as commit a44de38b61d598fb0512ea48da0de4179d39b804 was not backported. Is that required ?

**Comment by ajarr** [comment]
@kotreshhr if you resolved conflict you need to mention the conflict
as done here
https://github.com/ceph/ceph/commit/20b7bb685c5ea74c

**Comment by kotreshhr** [comment]
> @kotreshhr if you resolved conflict you need to mention the conflict
> as done here
> [20b7bb6](https://github.com/ceph/ceph/commit/20b7bb685c5ea74c)

Done

**Comment by ajarr** [comment]
The tests passed http://pulpito.ceph.com/yuriw-2020-05-05_20:58:56-fs-wip-yuri-testing-2020-05-05-1439-distro-basic-smithi/5026455/
Failure is unrelated.

**Pull request merged**
