### PR TITLE
quincy: Consider setting "bulk" autoscale pool flag when automatically creating a data pool for CephFS

### PR DESCRIPTION
**Pull request by leonid-s-usov**
Fixes (backport): https://tracker.ceph.com/issues/62373

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Review by joscollin — APPROVED** [review]

**Comment by leonid-s-usov** [comment]
jenkins test make check

**Comment by leonid-s-usov** [comment]
jenkins test make check

**Review by mchangir — APPROVED** [review]
https://pulpito.ceph.com/vshankar-2023-09-29_10:09:00-fs-wip-vshankar-testing-quincy-20230929.071619-testing-default-smithi/

**Comment by mchangir** [comment]
jenkins test api

**Pull request merged**
