### PR TITLE
API cleanup for libcephfs interfaces

### PR DESCRIPTION
**Pull request by jtlayton**
Just a couple of patches to do some cleanup of the statx-based APIs. The main thing we need to ensure is that no callers are setting flags that we don't currently recognize, as that would prevent us from being able to add new flags in the future.

I tried to run tests over the weekend but a bunch died, so I'm rerunning them now:

http://pulpito.ceph.com/jlayton-2016-11-21_14:46:06-fs-wip-jlayton-libcephfs---basic-mira/

Still, this patchset is pretty trivial, so I'll be surprised if it breaks anything.

### CODE REVIEW

**Comment by jtlayton** [comment]
Oh, and I should reference this tracker bug:

http://tracker.ceph.com/issues/17911

**Comment by gregsfortytwo** [comment]
The code looks good but you should include "Fixes: http://tracker.ceph.com/issues/17911" in the second patch commit message, and at least one of those dead jobs is a libcephfs one so we should figure out what's going on there (we've had much more successful runs very recently).

**Comment by jtlayton** [comment]
Sigh... added the Fixes line and repushed, and then the build failed for some reason. Looks like:

        Start  14: run-tox-ceph-disk                                            
  7/156 Test  #10: test_objectstore_memstore.sh ............***Failed   15.48 sec

I'm guessing this is another unrelated bug, but if you guys want to sanity check that, then I'd appreciate it.

**Comment by tchaikov** [comment]
the objectstore test failure is tracked at http://tracker.ceph.com/issues/17743 .

**Pull request merged**
