### PR TITLE
[DNM] jewel: librbd: interlock image refresh and exclusive lock operations

### PR DESCRIPTION
**Pull request by dillaman**
http://tracker.ceph.com/issues/17134

### CODE REVIEW

**Comment by dachary** [comment]
for the record the build error should be fixed by a backport merged today

**Comment by dillaman** [comment]
@dachary rebased against latest jewel-next branch

**Comment by dachary** [comment]
@trociny could you please open a pull requestion against jewel-next with the rbd_mirror_stress.sh commits you cherry-picked ? It may even make sense for @dillaman to include those fixes in this pull request so that it can pass the tests.

**Comment by trociny** [comment]
@dachary #12159

It contains some additional commit I didn't use when running teuthology, so I am testing that PR now.

**Comment by smithfarm** [comment]
@dillaman I can't figure out why, but for some reason this PR was not picked up by the integration branch generation script until today, and it appears to conflict with #12890 

One option would be to test+merge one first, then the other. Another would be for you to integration one of the PRs into the other. Any preference?

**Comment by dillaman** [comment]
@smithfarm I'll just merge this one into #12890

**Comment by dillaman** [comment]
@smithfarm Actually -- it looks like this PR is already contained in the other Pr

**Comment by dillaman** [comment]
Merged via alternative PR

**Pull request closed without merging**
