### PR TITLE
rgw/s3select: bug fixes per QE recent defects

### PR DESCRIPTION
**Pull request by galsalomon66**
- https://github.com/ceph/s3select/pull/140
- https://github.com/ceph/s3select/pull/141
- https://github.com/ceph/s3select/pull/142
- https://github.com/ceph/s3select/pull/143
- https://github.com/ceph/s3select/pull/145
- https://github.com/ceph/s3select/pull/146
- https://github.com/ceph/s3select/pull/147

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [x] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Comment by galsalomon66** [comment]
https://pulpito.ceph.com/gsalomon-2024-01-18_05:33:36-rgw:verify-s3select_fixes_QE_bugs-distro-default-smithi/

all 8 had passed successfully

**Comment by cbodley** [comment]
> Unmodified Submodules — Approval needed: modified submodules found
> please include 's3select submodule' in your commit message, if this change is intentional.

**Comment by galsalomon66** [comment]
https://pulpito.ceph.com/gsalomon-2024-01-18_10:43:24-rgw:verify-s3select_fixes_QE_bugs-distro-default-smithi/
1 failure 
19 had with success

**Comment by galsalomon66** [comment]
https://pulpito.ceph.com/gsalomon-2024-01-19_11:25:24-rgw-s3select_fixes_QE_bugs-distro-default-smithi/
3 failures
68 had passed with success

**Comment by galsalomon66** [comment]
jenkins test submodules

**Review by cbodley — APPROVED** [review]

**Comment by galsalomon66** [comment]
https://pulpito.ceph.com/gsalomon-2024-01-22_14:50:50-rgw:verify-s3select_fixes_QE_bugs-distro-default-smithi/
1 failure :: not related to changes
23 success

**Pull request merged**
