### PR TITLE
reef: mgr/nfs: disallow non-existent paths when creating export

### PR DESCRIPTION
**Pull request by dparmar18**
Backport tracker: https://tracker.ceph.com/issues/59251, https://tracker.ceph.com/issues/59248 and https://tracker.ceph.com/issues/59245
Backport of https://github.com/ceph/ceph/pull/49460
Parent tracker: https://tracker.ceph.com/issues/58228, https://tracker.ceph.com/issues/58744 and https://tracker.ceph.com/issues/58758

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [x] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by vshankar** [comment]
> @vshankar this one needs commits from #51005 (after merged into main) before moving ahead right?

yes.

**Comment by ljflores** [comment]
jenkins test api make check

**Comment by ljflores** [comment]
jenkins test api

**Comment by ljflores** [comment]
jenkins test make check

**Comment by ljflores** [comment]
Rados suite review: https://pulpito.ceph.com/?branch=wip-yuri6-testing-2023-04-26-1247-reef

Failures, unrelated:
    1. https://tracker.ceph.com/issues/59049
    2. https://tracker.ceph.com/issues/59057
    3. https://tracker.ceph.com/issues/59142
    4. https://tracker.ceph.com/issues/58797

Details:
    1. WaitReplicas::react(const DigestUpdate&): Unexpected DigestUpdate event - Ceph - RADOS
    2. rados/test_envlibrados_for_rocksdb.sh: No rule to make target 'rocksdb_env_librados_test' on centos 8 - Ceph - RADOS
    3. mgr/dashboard: fix e2e for dashboard v3 - Ceph - Mgr - Dashboard
    4. scrub/osd-scrub-dump.sh: TEST_recover_unexpected fails from "ERROR: Unexpectedly low amount of scrub reservations seen during test" - Ceph - RADOS

**Review by kotreshhr — APPROVED** [review]

**Pull request merged**
