### PR TITLE
nautilus: cephfs: client: wake up the front pos waiter

### PR DESCRIPTION
**Pull request by lxbsz**
backport tracker: https://tracker.ceph.com/issues/49519

---

backport of https://github.com/ceph/ceph/pull/39574
parent tracker: https://tracker.ceph.com/issues/49379

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by lxbsz** [comment]
jenkins retest this please

**Comment by tchaikov** [comment]
test failure due to the missing fix in the current "nautilus" branch. should be fixed once we restore it from "nautilus-saved".

**Comment by lxbsz** [comment]
> test failure due to the missing fix in the current "nautilus" branch. should be fixed once we restore it from "nautilus-saved".

Okay, get it. Thanks.

**Comment by tchaikov** [comment]
jenkins test api

**Comment by smithfarm** [comment]
make check failure is:

```
CMake Error at /usr/lib/x86_64-linux-gnu/cmake/Boost-1.71.0/BoostConfig.cmake:117 (find_package):
  Found package configuration file:

    /usr/lib/x86_64-linux-gnu/cmake/boost_python-1.71.0/boost_python-config.cmake

  but it set boost_python_FOUND to FALSE so package "boost_python" is
  considered to be NOT FOUND.  Reason given by package:

  No suitable build variant has been found.

  The following variants have been tried and rejected:

  * libboost_python38.so.1.71.0 (3.8, Boost_PYTHON_VERSION=2.7)

  * libboost_python38.a (3.8, Boost_PYTHON_VERSION=2.7)

Call Stack (most recent call first):
  /usr/lib/x86_64-linux-gnu/cmake/Boost-1.71.0/BoostConfig.cmake:182 (boost_find_component)
  cmake/modules/FindBoost.cmake:443 (find_package)
  CMakeLists.txt:677 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/jenkins-build/build/workspace/ceph-pull-requests/build/CMakeFiles/CMakeOutput.log".
See also "/home/jenkins-build/build/workspace/ceph-pull-requests/build/CMakeFiles/CMakeError.log".
+ exit 1
```

**Review by smithfarm — DISMISSED** [review]
@lxbsz Did you use `git cherry-pick -x` ? (The reason I ask is your `(cherry picked from commit ...)` line appears to have a short SHA1 hash.)

If not, would you mind redoing it? Or at least replace the short SHA1 with the complete one.

Also, if this is anything but a clean cherry-pick from master, then there should be a "Conflicts" section. You can read more about that here:

* https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst#cherry-picking-rules
* https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst#conflict-resolution

**Comment by lxbsz** [comment]
> @lxbsz Did you use `git cherry-pick -x` ? (The reason I ask is your `(cherry picked from commit ...)` line appears to have a short SHA1 hash.)
> 

No.

> If not, would you mind redoing it? Or at least replace the short SHA1 with the complete one.
> 

Sure, will do it.

> Also, if this is anything but a clean cherry-pick from master, then there should be a "Conflicts" section. You can read more about that here:
> 
> * https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst#cherry-picking-rules
> * https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst#conflict-resolution

Sure, will check it.
Thanks

**Comment by lxbsz** [comment]
> make check failure is:
> 
> ```
> CMake Error at /usr/lib/x86_64-linux-gnu/cmake/Boost-1.71.0/BoostConfig.cmake:117 (find_package):
>   Found package configuration file:
> 
>     /usr/lib/x86_64-linux-gnu/cmake/boost_python-1.71.0/boost_python-config.cmake
> 
>   but it set boost_python_FOUND to FALSE so package "boost_python" is
>   considered to be NOT FOUND.  Reason given by package:
> 
>   No suitable build variant has been found.
> 
>   The following variants have been tried and rejected:
> 
>   * libboost_python38.so.1.71.0 (3.8, Boost_PYTHON_VERSION=2.7)
> 
>   * libboost_python38.a (3.8, Boost_PYTHON_VERSION=2.7)
> 
> Call Stack (most recent call first):
>   /usr/lib/x86_64-linux-gnu/cmake/Boost-1.71.0/BoostConfig.cmake:182 (boost_find_component)
>   cmake/modules/FindBoost.cmake:443 (find_package)
>   CMakeLists.txt:677 (find_package)
> 
> 
> -- Configuring incomplete, errors occurred!
> See also "/home/jenkins-build/build/workspace/ceph-pull-requests/build/CMakeFiles/CMakeOutput.log".
> See also "/home/jenkins-build/build/workspace/ceph-pull-requests/build/CMakeFiles/CMakeError.log".
> + exit 1
> ```

BTW, does this PR will affect this errors above ?

**Comment by lxbsz** [comment]
jenkins retest this please

**Comment by lxbsz** [comment]
> Also, if this is anything but a clean cherry-pick from master, then there should be a "Conflicts" section. You can read more about that here:
> 

There is no any Conflict for the cherry-pick.

**Comment by smithfarm** [comment]
> > Also, if this is anything but a clean cherry-pick from master, then there should be a "Conflicts" section. You can read more about that here:
> 
> There is no any Conflict for the cherry-pick.

And no manual change is required to get it to compile?

**Comment by lxbsz** [comment]
> > > Also, if this is anything but a clean cherry-pick from master, then there should be a "Conflicts" section. You can read more about that here:
> > 
> > 
> > There is no any Conflict for the cherry-pick.
> 
> And no manual change is required to get it to compile?
> 
Yeah, there has, will add this to the conflicits section. 

> When I tried to compile the cherry-pick without any modifications, I got:
> 
> ```
> /home/jenkins-build/build/workspace/ceph-pull-requests/src/client/Client.cc: In member function 'void Client::unlock_fh_pos(Fh*)':
> /home/jenkins-build/build/workspace/ceph-pull-requests/src/client/Client.cc:9065:11: error: 'class Cond' has no member named 'notify_one'
>  9065 |     cond->notify_one();
>       |           ^~~~~~~~~~
> ```
> 
> So whatever modification is required, would need to be mentioned in a Conflicts section or split out into a separate commit.

Sure.


> > > Also, if this is anything but a clean cherry-pick from master, then there should be a "Conflicts" section. You can read more about that here:
> > 
> > 
> > There is no any Conflict for the cherry-pick.
> 
> And no manual change is required to get it to compile?
> 
> When I tried to compile the cherry-pick without any modifications, I got:
> 
> ```
> /home/jenkins-build/build/workspace/ceph-pull-requests/src/client/Client.cc: In member function 'void Client::unlock_fh_pos(Fh*)':
> /home/jenkins-build/build/workspace/ceph-pull-requests/src/client/Client.cc:9065:11: error: 'class Cond' has no member named 'notify_one'
>  9065 |     cond->notify_one();
>       |           ^~~~~~~~~~
> ```
> 
> So whatever modification is required, would need to be mentioned in a Conflicts section or split out into a separate commit.

Okay, get it.
Done.

**Comment by smithfarm** [comment]
@lxbsz Thanks!

**Comment by smithfarm** [comment]
jenkins test make check

**Comment by smithfarm** [comment]
@tchaikov @djgalloway Do you guys know why "make check" keeps failing in this PR? To me, it looks like the machine running the test does not have Python 2 installed at all. Yet the way nautilus make check is run, Python 2 is needed for it to succeed?

**Comment by djgalloway** [comment]
> @tchaikov @djgalloway Do you guys know why "make check" keeps failing in this PR? To me, it looks like the machine running the test does not have Python 2 installed at all. Yet the way nautilus make check is run, Python 2 is needed for it to succeed?

Sorry, I don't.  I usually rely on Kefu for boost-related errors.

**Comment by smithfarm** [comment]
jenkins test make check

**Comment by smithfarm** [comment]
@djgalloway Thanks. The failure is gone, now.

**Comment by yuriw** [comment]
Per @ajarr "Not sure we can merge PR 40865 since PR 41394 introduced a lot of failures in fs suite."

**Review by ajarr — APPROVED** [review]

**Comment by ajarr** [comment]
@yuriw please merge this PR

**Pull request merged**
