### PR TITLE
[DNM] libcephfs: fscrypt support

### PR DESCRIPTION
**Pull request by yehudasa**
This implements fscrypt support in libcephfs, and the cephfs userspace client that is interoperable with the cephfs kernel client (see: https://lwn.net/Articles/889912/).

Note that this is still in heavy development.

Currently implemented:
- Key management infrastructure
- Can use [a modified] fscrypt utility [1] with fuse mounted filesystem
- Supports "lock", and "unlock", as well as other required operations
- Listing encrypted directories
- Encrypted files read
- Encrypted files write
- libcephfs control API

TODO:
- ~~Currently cannot select encryption types (uses defaults)~~
- ~~Add libcephfs API to control crypto keys~~
- ~~Long file names support~~
- ~~Cleanly deal with the read caps needed when writing data~~
- read-modify race detection when writing files
- ~~symlinks implementation~~
- ~~snapshots~~
- ~~async API~~
- restrict certain operations to only happen when directory is unlocked (e.g., read file, create snapshots, etc.)
- Probably more filesystem operations coverage (e.g., where there are multiple implementations of different functionalities, etc.)
- testing

We currently only support the default encryption types that the fscrypt control tool sets. The code does handle selection of encryption types dynamically, and gracefully handles the case where it cannot support an encryption type. Since the fscrypt tool does not make it easy to set encryption types, and since libopenssl does not support every type/mode out of the box, we should consider in the future which encryption types we want to support, however this is beyond the scope of this PR.

[1] fscrypt utility is modified due to use of ioctls that are not well formed (a problem with fuse), see https://github.com/yehudasa/fscrypt/tree/wip-ceph-fuse

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by lxbsz** [comment]
@yehudasa Please enable the qa test cases at the same time and make sure all the test pass before we merging it.

**Comment by yehudasa** [comment]
@gregsfortytwo is there a new PR that replaces this one?

**Comment by gregsfortytwo** [comment]
> @gregsfortytwo is there a new PR that replaces this one?

I know @chrisphoffman has been doing work on top of this at https://github.com/chrisphoffman/ceph/commits/wip-fscrypt/, but I don't think we have another PR for it?

**Comment by chrisphoffman** [comment]
> > @gregsfortytwo is there a new PR that replaces this one?
> 
> I know @chrisphoffman has been doing work on top of this at https://github.com/chrisphoffman/ceph/commits/wip-fscrypt/, but I don't think we have another PR for it?

That branch isn't ready for PR yet, the plan is to create one soon.

**Pull request closed without merging**
