### PR TITLE
cephadm: do not hard code samba debuglevel 6

### PR DESCRIPTION
**Pull request by phlogistonjohn**
Remove the line hard-coding the samba debuglevel to 6. It is a leftover from testing the early versions of the containers on ceph.

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [x] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [x] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), <s>opened tracker ticket</s> nah
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Review by adk3798 — APPROVED** [review]

**Review by anoopcs9 — APPROVED** [review]
lgtm, thanks for leaving the log level at default for now 😊

**Comment by adk3798** [comment]
https://pulpito.ceph.com/adking-2024-07-23_15:55:03-orch:cephadm-wip-adk-testing-2024-07-19-0851-distro-default-smithi/

Failures:

- staggered upgrade mismatch between `ceph orch ps` and `ceph versions`, known issue
- thrash and rgw-ingress tests timing out, known issue
- mds_upgrade_sequence failure, known issue
- cephadm task test was actually related to a specific PR in the run

Nothing to block merging for all PRs except the one causing the cephadm task failure (not this PR if you see this comment)

**Comment by adk3798** [comment]
jenkins test make check

**Comment by adk3798** [comment]
@phlogistonjohn it looks like the make check failure is actually related to the PR
```
=================================== FAILURES ===================================
__________________________ test_deploy_smb_container ___________________________

cephadm_fs = <pyfakefs.fake_filesystem.FakeFilesystem object at 0x7f311ed608b0>
funkypatch = <tests.fixtures.FunkyPatcher object at 0x7f311ef9ff40>

    def test_deploy_smb_container(cephadm_fs, funkypatch):
        mocks = _common_patches(funkypatch)
        fsid = 'b01dbeef-701d-9abe-0000-e1e5a47004a7'
        with with_cephadm_ctx([]) as ctx:
            ctx.container_engine = mock_podman()
            ctx.fsid = fsid
            ctx.name = 'smb.b01s'
            ctx.image = 'quay.io/essembee/samba-server:latest'
            ctx.reconfig = False
            ctx.config_blobs = {
                'cluster_id': 'smb1',
                'config_uri': 'http://localhost:9876/smb.json',
                'config': 'SAMPLE',
                'keyring': 'SOMETHING',
            }
            _cephadm._common_deploy(ctx)
    
        basedir = pathlib.Path(f'/var/lib/ceph/{fsid}/smb.b01s')
        assert basedir.is_dir()
        with open(basedir / 'unit.run') as f:
            runfile_lines = f.read().splitlines()
        assert 'podman' in runfile_lines[-1]
>       assert runfile_lines[-1].endswith('quay.io/essembee/samba-server:latest --samba-debug-level=6 run smbd')
E       AssertionError: assert False
E        +  where False = <built-in method endswith of str object at 0x555ef31c9370>('quay.io/essembee/samba-server:latest --samba-debug-level=6 run smbd')
E        +    where <built-in method endswith of str object at 0x555ef31c9370> = '/usr/bin/podman run --rm --ipc=shareable --stop-signal=SIGTERM --init --name ceph-b01dbeef-701d-9abe-0000-e1e5a47004a...01dbeef-701d-9abe-0000-e1e5a47004a7/smb.b01s/keyring:/etc/ceph/keyring:z quay.io/essembee/samba-server:latest run smbd'.endswith
```

**Review by anoopcs9 — APPROVED** [review]
😆

**Comment by anoopcs9** [comment]
jenkins test dashboard cephadm

**Pull request merged**
