### PR TITLE
osd: Reverse order of op_has_sufficient_caps and do_pg_op

### PR DESCRIPTION
**Pull request by badone**
Fixes: http://tracker.ceph.com/issues/19790

Signed-off-by: Brad Hubbard <bhubbard@redhat.com>

### CODE REVIEW

**Comment by liewegas** [comment]
retest this please

**Comment by gregsfortytwo** [comment]
@badone, how did you validate this works? When I skimmed through it I wasn't sure it would behave well since PG ops aren't targeted at a particular object.
Or maybe that all just behaves correctly and means listing is only allowed by users with full read permissions on the pool?

**Comment by badone** [comment]
@gregsfortytwo in hammer op_has_sufficient_caps was called at the top of ReplicatedPG::do_request. In 818d790f7d424520bc96c651571f2c86e94caf1e it was moved to ReplicatedPG::do_op but placed after do_pg_op for reasons I can't fathom. I validated the fix against the original reported tracker issue and also ran testing (unit and CI). I will mark this PR DNM and look into adding additional testing to check for this regression and correct auth caps validation.

**Comment by gregsfortytwo** [comment]
That sounds to me like enough to get on with for now, then! :)

**Comment by gregsfortytwo** [comment]
@badone I'm satisfied with this given the testing you say you've already done. Did this need to wait on anything else?

**Comment by badone** [comment]
@gregsfortytwo I was going to add a test specifically for this case but got sidetracked. Could you give me another workday or two?

**Comment by badone** [comment]
@gregsfortytwo mind taking a look now?

**Comment by badone** [comment]
@liewegas added a test so I hope the approval stands?

**Comment by liewegas** [comment]
yep lgtm!

**Comment by gregsfortytwo** [comment]
Reviewed-by: Greg Farnum <gfarnum@redhat.com>

**Comment by liewegas** [comment]
http://pulpito.ceph.com/sage-2017-06-21_22:08:07-rados-wip-sage-testing-distro-basic-smithi/

**Pull request merged**
