### PR TITLE
rgw: add mon command admin ops.

### PR DESCRIPTION
**Pull request by yaozongyou**
Add mon command admin ops. Using this API, a command can be sent to the monitor, executed and the response is sent back.

Signed-off-by: Yao Zongyou <yaozongyou@vip.qq.com>

### CODE REVIEW

**Comment by liewegas** [comment]
@jdurgin @mattbenjamin does this make sense?

@yaozongyou do you have a motivating use case here?

**Comment by yaozongyou** [comment]
Yes! This API is dramatically useful. Ceph dashboard, cluster monitor and other things can be 
implemented via this API. 
I know the same feature can be made using librados api. But http + restful api is more friendly.

**Comment by liewegas** [comment]
If we add a restful management API we expect it to look more like this: 
https://github.com/ceph/ceph/pull/14457

**Comment by mattbenjamin** [comment]
@sage concur;  RGW bug scrub concurs

**Comment by yehudasa** [comment]
@yaozongyou @liewegas yeah, I think going via ceph manager would be the better route

**Comment by yaozongyou** [comment]
ok, thanks.

**Pull request closed without merging**
