### PR TITLE
reef: qa: use centos9 for fs:upgrade

### PR DESCRIPTION
**Pull request by vshankar**
backport tracker: https://tracker.ceph.com/issues/66518

---

backport of https://github.com/ceph/ceph/pull/57991
parent tracker: https://tracker.ceph.com/issues/65580

this backport was staged using ceph-backport.sh version 16.0.0.6848
find the latest version at https://github.com/ceph/ceph/blob/main/src/script/ceph-backport.sh

### CODE REVIEW

**Comment by vshankar** [comment]
cc @batrick @yuriw

**Comment by vshankar** [comment]
@yuriw testing this out right now. Will update when its ready for merge.

**Review by anthonyeleven — APPROVED** [review]

**Comment by batrick** [comment]
> fs:upgrade run: https://pulpito.ceph.com/vshankar-2024-06-28_11:04:25-fs:upgrade-wip-yuri5-testing-2024-06-20-1013-reef-testing-default-smithi/
> 
> The remaining problems are tests that rely on starting upgrades from pacific release - those still require centos8. Even if we override those with centos8, the upgrade would fail due to lack for centos8 packages for reef. So, we would need to stop testing upgrades from pacific. cc @batrick

Leave them failing for now until we decide how we want to address.

**Review by batrick — APPROVED** [review]

**Review by joscollin — APPROVED** [review]
Could this be merged today?

**Comment by vshankar** [comment]
> Could this be merged today?

Ofcourse - pretty soon actually :)

**Pull request merged**
