### PR TITLE
jewel: ceph_volume_client: fix recovery from partial auth update 

### PR DESCRIPTION
**Pull request by ajarr**
Fixes http://tracker.ceph.com/issues/17705

and adds tests in tasks/cephfs/test_volume_clients.py

### CODE REVIEW

**Comment by ajarr** [comment]
test the PR with https://github.com/ceph/ceph-qa-suite/pull/1221

**Comment by dachary** [comment]
@ajarr could you link to the test results here please ?

**Comment by dachary** [comment]
jenkins test this please

**Comment by dachary** [comment]
pushed to gitbuilders as wip-17705-jewel so that it can be tested with the required ceph-qa-suite modifications https://github.com/ceph/ceph-qa-suite/pull/1221/files

**Comment by dachary** [comment]
jenkins test this please (jenkins general failure)

**Comment by dachary** [comment]
jenkins test this please (general jenkins failure)

**Comment by dachary** [comment]
@ajarr you can now run a fs suite using wip-17705-jewel and https://github.com/ceph/ceph-qa-suite/pull/1221 . Please let me know if you need help doing that.

**Comment by jcsp** [comment]
Running here http://pulpito.ceph.com/jspray-2016-11-17_18:46:55-fs-wip-17705-jewel-distro-basic-smithi

**Comment by dachary** [comment]
@ajarr in the context of backports DNM means that it will not be merged in the integration branch. I set that for this pull request because it needs its own run of QA with the corresponding ceph-qa-suite branch.

**Comment by smithfarm** [comment]
Analysis of test failures from @jscp 's run:

Test [557275](http://pulpito.ceph.com/jspray-2016-11-17_18:46:55-fs-wip-17705-jewel-distro-basic-smithi/557275/) - assert(0) in common/lockdep.cc just like http://tracker.ceph.com/issues/17447

Test [557280](http://pulpito.ceph.com/jspray-2016-11-17_18:46:55-fs-wip-17705-jewel-distro-basic-smithi/557280/):

```
2016-11-17T21:37:30.227 INFO:tasks.workunit.client.0.smithi087.stdout:test/libcephfs/flock.cc:466: Failure
2016-11-17T21:37:30.227 INFO:tasks.workunit.client.0.smithi087.stdout:Value of: sem_timedwait(&s.sem[1%2], abstime(ts, waitSlowMs))
2016-11-17T21:37:30.228 INFO:tasks.workunit.client.0.smithi087.stdout:  Actual: -1
2016-11-17T21:37:30.228 INFO:tasks.workunit.client.0.smithi087.stdout:Expected: 0
2016-11-17T21:37:30.228 INFO:tasks.workunit.client.0.smithi087.stdout:[  FAILED  ] LibCephFS.InterProcessLocking (5023 ms)
```

Test [557281](http://pulpito.ceph.com/jspray-2016-11-17_18:46:55-fs-wip-17705-jewel-distro-basic-smithi/557281/): 29 failures in libcephfs-java/test.sh - Java makes my eyes glaze over, but maybe due to this:

```
2016-11-17T21:33:58.439 INFO:tasks.workunit.client.0.smithi002.stdout:.Loading libcephfs-jni from default path: /usr/lib/jni:/usr/lib64
2016-11-17T21:33:58.440 INFO:tasks.workunit.client.0.smithi002.stdout:Loading libcephfs-jni: /usr/lib64/libcephfs_jni.so
2016-11-17T21:33:58.440 INFO:tasks.workunit.client.0.smithi002.stdout:Loading libcephfs-jni: /usr/lib/jni/libcephfs_jni.so
2016-11-17T21:33:58.441 INFO:tasks.workunit.client.0.smithi002.stdout:Loading libcephfs-jni: Failure!
2016-11-17T21:33:58.527 INFO:tasks.workunit.client.0.smithi002.stdout:E.EEE.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E
```

Test [557316](http://pulpito.ceph.com/jspray-2016-11-17_18:46:55-fs-wip-17705-jewel-distro-basic-smithi/557316/) and test [557321](http://pulpito.ceph.com/jspray-2016-11-17_18:46:55-fs-wip-17705-jewel-distro-basic-smithi/557321/) are similar to [557280](http://pulpito.ceph.com/jspray-2016-11-17_18:46:55-fs-wip-17705-jewel-distro-basic-smithi/557280/)

Test [557322](http://pulpito.ceph.com/jspray-2016-11-17_18:46:55-fs-wip-17705-jewel-distro-basic-smithi/557322/) is similar to [557281](http://pulpito.ceph.com/jspray-2016-11-17_18:46:55-fs-wip-17705-jewel-distro-basic-smithi/557281/)

**Comment by smithfarm** [comment]
Re-running the 6 failed jobs:

```./virtualenv/bin/teuthology-suite --priority 101 --machine-type smithi --email ncutler@suse.cz --ceph wip-17705-jewel --suite-branch wip-17705-jewel --suite fs --filter "$filter"```

**running** http://pulpito.ceph.com:80/smithfarm-2016-11-24_20:19:25-fs-wip-17705-jewel---basic-smithi/

**Comment by smithfarm** [comment]
@jcsp Does my analysis of your run (see preceding two comments) help any?

**Comment by jcsp** [comment]
@smithfarm yes, those failure are all ignoreable

**Comment by ajarr** [comment]
@smithfarm @dachary can this PR be merged?

**Comment by smithfarm** [comment]
@ajarr The tests in https://github.com/ceph/ceph-qa-suite/pull/1221 need to be moved into this PR.

**Comment by smithfarm** [comment]
@ajarr Ping

**Comment by ajarr** [comment]
@smithfarm done. missed your comment. sorry about the delay.

**Comment by jcsp** [comment]
Tested here: http://pulpito.ceph.com/jspray-2017-01-24_21:53:01-fs-wip-jcsp-backports-20170124-distro-basic-smithi/

**Pull request merged**
