### PR TITLE
doc: Jewel v10.2.8 release notes

### PR DESCRIPTION
**Pull request by smithfarm**
Finally . . .

### CODE REVIEW

**Comment by smithfarm** [comment]
Dropped bombshell in form of the second commit.

**Comment by smithfarm** [comment]
We should wait for @ukernel and/or @jcsp to review before merging this.

**Comment by smithfarm** [comment]
test this please

**Comment by smithfarm** [comment]
test this please

**Comment by tchaikov** [comment]
@smithfarm it's a known issue that the master's "make check" fails, see #16317.

**Comment by smithfarm** [comment]
@tchaikov ACK, thanks.

**Comment by smithfarm** [comment]
If someone with higher github privileges is inclined to merge this now (without waiting for Jenkins make check), they could do so.

**Pull request merged**
