### PR TITLE
nautilus: rgw: list objects version 2

### PR DESCRIPTION
**Pull request by theanalyst**
backport trackers:

* https://tracker.ceph.com/issues/41408
* https://tracker.ceph.com/issues/42280

---

backport of:

* https://github.com/ceph/ceph/pull/28102
* https://github.com/ceph/ceph/pull/28988

parent trackers:

* https://tracker.ceph.com/issues/23908
* https://tracker.ceph.com/issues/40728

### CODE REVIEW

**Comment by cbodley** [comment]
we'll want to fix the indentation issues (https://github.com/ceph/ceph/pull/28830) before taking it to nautilus

**Comment by smithfarm** [comment]
> we'll want to fix the indentation issues (#28830) before taking it to nautilus

Looks like #28830 has been merged. The corresponding backport tracker is https://tracker.ceph.com/issues/41904 - would it make sense to do that one right here in this PR?

**Comment by smithfarm** [comment]
@cbodley Have another look?

**Comment by theanalyst** [comment]
also includes https://github.com/ceph/ceph/pull/28988

**Comment by mattbenjamin** [comment]
@theanalyst superb, thanks for this effort!

**Comment by smithfarm** [comment]
This one was marked for backport to nautilus:

https://github.com/ceph/ceph/pull/28988

but AFAICT it's not necessary to cherry-pick it into this PR.

**Comment by theanalyst** [comment]
> This one was marked for backport to nautilus:
> 
> #28988
> 
> but AFAICT it's not necessary to cherry-pick it into this PR.

I think the second whitespace change actually overwrote that part and it is included, but an explicit cherry-pick or mentioning this in the tracker & commit wouldn't hurt

**Comment by yuriw** [comment]
[wip-yuri3-testing-2019-11-08-1221-nautilus](https://trello.com/c/GKBiDkwL/752-wip-yuri3-testing-2019-11-08-1221-nautilus)

**Comment by smithfarm** [comment]
Note: this introduced a regression https://tracker.ceph.com/issues/42881 with possible security implications (program returns random data from function) - #31678 is needed to fix the regression.

**Comment by cbodley** [comment]
thank you @smithfarm!

**Pull request merged**
