### PR TITLE
qa/tasks/cephfs: fix shell command errors

### PR DESCRIPTION
**Pull request by lxbsz**
Fixes: https://tracker.ceph.com/issues/44571
Signed-off-by: Xiubo Li <xiubli@redhat.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by tchaikov** [comment]
@lxbsz i rebased your change onto octopus. as currently, the bug fixes should go to octopus, and octopus will merge back into master, before we cut v15.2.0 branch. as the py3 change, the rebased change won't be cherry-picked cleanly by then, we will have to do the cherry-pick manually...

**Comment by lxbsz** [comment]
> @lxbsz i rebased your change onto octopus. as currently, the bug fixes should go to octopus, and octopus will merge back into master, before we cut v15.2.0 branch. because of the py3 change, the rebased change won't be cherry-picked cleanly by then, we will have to do the cherry-pick manually...

Okay, got it.
Thanks.

**Comment by tchaikov** [comment]
rerunning the fuse test w/o this change at http://pulpito.ceph.com/kchai-2020-03-21_04:14:30-fs:verify-wip-kefu-testing-2020-03-20-1836-distro-basic-smithi/

**Comment by lxbsz** [comment]
@tchaikov 
Update it by switching the remote.sh() to remote.run().
Thanks.

**Comment by lxbsz** [comment]
http://pulpito.ceph.com/xiubli-2020-04-09_13:05:46-fs:basic_functional:-wip-lxb-sh-2020-04-09-1714-distro-basic-smithi/

**Comment by lxbsz** [comment]
Will close it, it has been fixed by another previous commit:

```
commit 2cc0ee709c36eabe03311a00b72295da468bccf4
Author: Rishabh Dave <ridave@gmail.com>
Date:   Fri Mar 13 07:03:50 2020 +0000

    qa/vstart_runner: update vstart_runner.LocalRemote.sh
    
    Commit 9f6c764f10f replaces remote.run calls by remote.sh without
    updating the definition of vstart_runner.LocalRemote.sh which breaks the
    cephfs tests when executed locally.
    
    Fixes: https://tracker.ceph.com/issues/44579
    Signed-off-by: Rishabh Dave <ridave@redhat.com>

```

**Pull request closed without merging**
