### PR TITLE
mutex: avoid trylock unless instrumentation is enabled

### PR DESCRIPTION
**Pull request by liewegas**
Testing showed the trylock was very expensive; avoid it unless
mutex instrumentaiton is actually enabled at runtime.

### CODE REVIEW

**Comment by athanatos** [comment]
lgtm

**Comment by branch-predictor** [comment]
Great!

**Comment by branch-predictor** [comment]
This decreases time spent in Mutex::Lock() by around 3ns (around 10%).

**Comment by v-sinha** [comment]
Tested this change successfully on our lab machines. I do realize this has already been merged into ceph:master :-).

**Pull request merged**
