### PR TITLE
[DNM] jewel: common osd: Improve scrub analysis, list-inconsistent-obj output and osd-scrub-repair test

### PR DESCRIPTION
**Pull request by dzafman**
Backport pull request #11449 from dzafman/wip-scrub-prep
Backport pull request #9613 from dzafman/wip-16064
Backport pull request ceph/ceph-qa-suite#1274 from (ceph-qa-suite dzafman/wip-16064)

Fixes: http://tracker.ceph.com/issues/18116

### CODE REVIEW

**Comment by dzafman** [comment]
Retest this please (ceph-disk/run-tox.sh failed)

**Comment by dachary** [comment]
@dzafman retargeted to jewel-next, could you please rebase & repush against it ?

jenkins test this please

**Comment by dachary** [comment]
jenkins test this please (jenkins agent failure)

**Comment by athanatos** [comment]
@dzafman This seems way to complicated for a backport.

**Comment by dzafman** [comment]
@dachary Rebased

@athanatos  The rebase removed 2 extraneous commits due to a switch to jewel-next.

This is a very clean backport of 10 commits from 1 pull request.  And the only commit from a pull which was to prepare for the main one originally.  The only conflicts were in a makefile change and object_info output which doesn't include "alloc_hint" in Jewel.

The meat of all this is in 6fa5f5a which merged without conflict.

**Comment by dachary** [comment]
@dzafman thanks. Changed the title to match the title of the backport issue.

**Comment by dachary** [comment]
marking DNM because it conflicts with another pull request

**Comment by dzafman** [comment]
No longer conflicts with ceph/ceph#12088

**Comment by dzafman** [comment]
Need to add backport of ceph/ceph-qa-suite#1274 to this pull request to cover testing changes which use to be in its own repo.

**Comment by smithfarm** [comment]
Marking DNM because it conflicts with #13047 and is waiting for another commit to be cherry-picked.

**Comment by dzafman** [comment]
Merged with ceph/ceph#13146

**Pull request closed without merging**
