### PR TITLE
nautilus: rgw: check object locks in multi-object delete

### PR DESCRIPTION
**Pull request by mattbenjamin**
Backport tracker: https://tracker.ceph.com/issues/48423

Backport of: https://github.com/ceph/ceph/pull/37933 (6 commits; this backport PR has only 5 commits because "the submitter of the original PR had to do a rebase due to changes in the RGW source--there's no corresponding action to be taken in the backport")

Parent tracker: https://tracker.ceph.com/issues/47586

### CODE REVIEW

**Comment by trociny** [comment]
@mattbenjamin I don't see "Conflicts" description in the commit message logs. I thought it was mandatory (and actually quite useful).

**Comment by smithfarm** [comment]
```
The following tests FAILED:
	 58 - unittest_lockdep (Timeout)
```

**Comment by smithfarm** [comment]
@mattbenjamin Please add the missing Conflicts blocks. Also, though I understand there is a temptation to modify the original commit messages (e.g. to replace the tracker URL to the backport tracker URL), doing so is actually violates this rule:

```
the commit message generated by git cherry-pick -x must not be modified, except to add a "Conflicts" section below the "cherry picked from commit ..." line added by git
```

https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst#cherry-picking-rules

**Comment by smithfarm** [comment]
One final comment: the original PR https://github.com/ceph/ceph/pull/37933 has 6 commits, this one only 5. 

@mattbenjamin Was the sixth commit omitted intentionally? If so, could you add a brief explanation for that to the PR description?

**Comment by mattbenjamin** [comment]
> 
> 
> ```
> The following tests FAILED:
> 	 58 - unittest_lockdep (Timeout)
> ```

clearly not related to this change, not sure what can usefully be done

**Comment by mattbenjamin** [comment]
> 
> 
> One final comment: the original PR #37933 has 6 commits, this one only 5.
> 
> @mattbenjamin Was the sixth commit omitted intentionally? If so, could you add a brief explanation for that to the PR description?

ok, it's quite obvious though--the submitter of the original PR had to do a rebase due to changes in the RGW source--there's no corresponding action to be taken in the backport

**Comment by mattbenjamin** [comment]
> 
> 
> @mattbenjamin Please add the missing Conflicts blocks. Also, though I understand there is a temptation to modify the original commit messages (e.g. to replace the tracker URL to the backport tracker URL), doing so actually violates this rule:
> 
> ```
> the commit message generated by git cherry-pick -x must not be modified, except to add 
> a "Conflicts" section below the "cherry picked from commit ..." line added by git
> ```
> 
> https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst#cherry-picking-rules

this is wasteful, to be honest;  it was easier in this case to apply the changes by hand;  of course, I can fake it so it appears to be a git merge--again, in my opinion a better process would accommodate that

**Comment by smithfarm** [comment]
jenkins test make check

**Comment by smithfarm** [comment]
> clearly not related to this change, not sure what can usefully be done
> let's see if it repeats

Typically, it doesn't, but since the Jenkins log disappears after a very short time I tend to post a summary of it to the PRs. That way, one can still see what the failure was even if the logs are gone.

**Review by cbodley — APPROVED** [review]

**Pull request merged**
