### PR TITLE
GCC13 Fixes

### PR DESCRIPTION
**Pull request by adamemerson**
Fix compilation failures due to not including `<cstdint>` and ambiguity between `std::format_to` and `fmt::format_to`.

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [x] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Review by idryomov — APPROVED** [review]

**Comment by cbodley** [comment]
> please include 'rocksdb submodule' in your commit message, if this change is intentional.

submodule changes don't require approval, they just need to be documented in the commit message. also note @tserong's existing work in https://github.com/ceph/rocksdb/pull/44 and https://github.com/ceph/ceph/pull/50438

**Comment by adamemerson** [comment]
jenkins test make check

**Comment by tchaikov** [comment]
@adamemerson hi Adam, you might want to update the rockdb submodule to a commit which includes https://github.com/ceph/rocksdb/pull/44 instead of your https://github.com/ceph/rocksdb/pull/45 . or, better off waiting until https://github.com/ceph/ceph/pull/51737 lands.

**Comment by adamemerson** [comment]
Closing in favor of #51737 .

**Pull request closed without merging**
