### PR TITLE
jewel: core: Objecter::C_ObjectOperation_sparse_read throws/catches exceptions on -ENOENT

### PR DESCRIPTION
**Pull request by shinobu-x**
http://tracker.ceph.com/issues/21923

### CODE REVIEW

**Comment by shinobu-x** [comment]
test this please

**Comment by smithfarm** [comment]
retest this please

**Comment by smithfarm** [comment]
jenkins test docs

**Comment by smithfarm** [comment]
This PR passed a rados integration run at http://tracker.ceph.com/issues/21742#note-14 with two bugs reproducing:

    http://tracker.ceph.com/issues/23006
    http://tracker.ceph.com/issues/23007

@dillaman Do you think it's ready to merge? Or does it need an rbd run?

**Comment by dillaman** [comment]
@smithfarm I would recommend a small RBD run

**Comment by smithfarm** [comment]
This PR passed another rados run at http://tracker.ceph.com/issues/21742#note-15

Still waiting for an rbd run.

**Comment by smithfarm** [comment]
Passed an rbd run at http://tracker.ceph.com/issues/21742#note-19

**Pull request merged**
