### PR TITLE
octopus:qa/tasks/mgr/test_progress: fix wait_until_equal

### PR DESCRIPTION
**Pull request by kamoltat**
Octopus ceph_test_case doesn't have period arg
so remove that in wait_until_equal. Also increase
time to wait for complete events by using RECOVERY_PERIOD
instead of EVENT_CREATION_PERIOD

Not needed in masters because only octopus and nautilus
doesn't have a period argument in qa/tasks/mgr/test_progress.py
wait_until_equals() function

Fixes: https://tracker.ceph.com/issues/48824

Signed-off-by: Kamoltat <ksirivad@redhat.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Review by jdurgin — APPROVED** [review]

**Comment by kamoltat** [comment]
https://pulpito.ceph.com/ksirivad-2021-02-10_07:46:43-rados:mgr-wip-octupus-del-period-arg-distro-basic-smithi/

**Comment by kamoltat** [comment]
@jdurgin I scheduled 9 jobs `task/progress` that passed successfully. Let me know if I should schedule more jobs

**Comment by jdurgin** [comment]
That amount of testing is fine since this is purely a change in the progress tests. I just wanted to verify this change is not needed in master, is that correct?

**Comment by tchaikov** [comment]
@kamoltat  could you note down the reason why this change does not apply to master in the commit message?

**Comment by kamoltat** [comment]
> That amount of testing is fine since this is purely a change in the progress tests. I just wanted to verify this change is not needed in master, is that correct?

@jdurgin yes so basically it is not needed in masters because only octopus and nautilus doesn't have a `period` argument in 
`qa/tasks/mgr/test_progress.py` wait_until_equals()

**Comment by kamoltat** [comment]
> @kamoltat could you note down the reason why this change does not apply to master in the commit message?

@tchaikov sure thing

**Review by jdurgin — APPROVED** [review]

**Comment by ideepika** [comment]
@kamoltat seems related :
```
2021-03-12T01:41:14.893 INFO:tasks.cephfs_test_runner:======================================================================
2021-03-12T01:41:14.893 INFO:tasks.cephfs_test_runner:ERROR: test_osd_cannot_recover (tasks.mgr.test_progress.TestProgress)
2021-03-12T01:41:14.893 INFO:tasks.cephfs_test_runner:----------------------------------------------------------------------
2021-03-12T01:41:14.894 INFO:tasks.cephfs_test_runner:Traceback (most recent call last):
2021-03-12T01:41:14.894 INFO:tasks.cephfs_test_runner:  File "/home/teuthworker/src/github.com_ceph_ceph-c_dbb79e0547db3abf076b9bc9b6ad97ede0519a0e/qa/tasks/mgr/test_progress.py", line 352, in test_osd_cannot_recover
2021-03-12T01:41:14.895 INFO:tasks.cephfs_test_runner:    self._osd_in_out_completed_events_count('out'),
2021-03-12T01:41:14.895 INFO:tasks.cephfs_test_runner:AttributeError: 'TestProgress' object has no attribute '_osd_in_out_completed_events_count'
2021-03-12T01:41:14.896 INFO:tasks.cephfs_test_runner:
2021-03-12T01:41:14.896 INFO:tasks.cephfs_test_runner:----------------------------------------------------------------------
2021-03-12T01:41:14.896 INFO:tasks.cephfs_test_runner:Ran 2 tests in 157.386s
2021-03-12T01:41:14.897 INFO:tasks.cephfs_test_runner:
2021-03-12T01:41:14.897 INFO:tasks.cephfs_test_runner:FAILED (errors=1)
2021-03-12T01:41:14.897 INFO:tasks.cephfs_test_runner:
2021-03-12T01:41:14.897 INFO:tasks.cephfs_test_runner:======================================================================
2021-03-12T01:41:14.898 INFO:tasks.cephfs_test_runner:ERROR: test_osd_cannot_recover (tasks.mgr.test_progress.TestProgress)
2021-03-12T01:41:14.898 INFO:tasks.cephfs_test_runner:----------------------------------------------------------------------
2021-03-12T01:41:14.899 INFO:tasks.cephfs_test_runner:Traceback (most recent call last):
2021-03-12T01:41:14.899 INFO:tasks.cephfs_test_runner:  File "/home/teuthworker/src/github.com_ceph_ceph-c_dbb79e0547db3abf076b9bc9b6ad97ede0519a0e/qa/tasks/mgr/test_progress.py", line 352, in test_osd_cannot_recover
2021-03-12T01:41:14.899 INFO:tasks.cephfs_test_runner:    self._osd_in_out_completed_events_count('out'),
2021-03-12T01:41:14.899 INFO:tasks.cephfs_test_runner:AttributeError: 'TestProgress' object has no attribute '_osd_in_out_completed_events_count'
```
can you take a look: /ceph/teuthology-archive/yuriw-2021-03-09_20:27:38-rados-wip-yuri2-testing-2021-03-09-1006-octopus-distro-basic-smithi/5950994/teuthology.log

**Comment by neha-ojha** [comment]
@kamoltat @ideepika I decided to dig into this since the progress module tests have been consistently failing in octopus.

The problem is that https://github.com/ceph/ceph/pull/39289/files#diff-068949e3f54d53acccfd66139a1b7c90ec7f3b4c65254ffa677fb72b1270a774R354 was an incomplete backport. It used `_osd_in_out_completed_events_count` without including the function itself, which got added in https://github.com/ceph/ceph/pull/37327 (not backported). 

I have no idea how tests passed for https://github.com/ceph/ceph/pull/39289, probably they did not. Let's please fix this.

**Review by neha-ojha — CHANGES_REQUESTED** [review]
until https://github.com/ceph/ceph/pull/39360#issuecomment-801243593 is fixed

**Comment by kamoltat** [comment]
@neha-ojha I see will get it on it right away. Thank you.

**Review by jdurgin — APPROVED** [review]
Since it was included in this run, https://github.com/ceph/ceph/pull/40225#issuecomment-804508453 looks good!

**Review by neha-ojha — APPROVED** [review]
👍

**Pull request merged**
