### PR TITLE
added listobjects v2

### PR DESCRIPTION
**Pull request by albIN7**
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by albIN7** [comment]
@mattbenjamin @cbodley @alimaredia

**Comment by albIN7** [comment]
Need some modifications

**Comment by mattbenjamin** [comment]
thanks, @albIN7 !
the upstream tracker for this feature seems to be http://tracker.ceph.com/issues/37801 make sujre
"Fixes: http://tracker.ceph.com/issues/37801" appears in the commit message when you resend this

**Comment by albIN7** [comment]
Thanks @mattbenjamin
I will follow the instructions.

**Pull request closed without merging**
