### PR TITLE
rgw: sysobj service cleanup

### PR DESCRIPTION
**Pull request by cbodley**
this simplifies the sysobj service, and removes `RGWSysObjectCtx` entirely

`RGWSysObjectCtx` is an analog of `RGWObjectCtx`, which caches a map of object state protected by a mutex

however, `RGWSysObjectCtx` only interacts with the sysobj `stat()` API ~~which appears to be completely unused~~. the sysobj service has a cache layer already, so extra caching at this level isn't useful

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by cbodley** [comment]
added another commit to simplify `rgw_get_system_obj()`, which removes the last caller of `stat()`

**Review by adamemerson — APPROVED** [review]
I approve of this commit.

**Comment by cbodley** [comment]
jenkins test make check

**Comment by cbodley** [comment]
passed qa in https://pulpito.ceph.com/cbodley-2022-07-18_15:12:20-rgw-wip-cbodley-testing-distro-default-smithi/ (valgrind issues tracked in https://tracker.ceph.com/issues/56500)

**Pull request merged**
