### PR TITLE
Detect NFS availability without mgr crash

### PR DESCRIPTION
**Pull request by samuelallan72**
Ceph Dashboard needs to check availability of the NFS service
for the NFS tab.
However, the existing method caused the nfs mgr module to crash,
as ceph dashboard called `cluster_ls`,
which crashed if the orchestrator was not available.

Resolve the issue with two things:

1. Avoid crashing the module if orchestrator is not available.
The `cluster_ls` function now returns an empty list if no orchestrator.

2. Add a function to check if NFS is available.  This should be separate
from the `cluster_ls`, as we should avoid overloading the `cluster_ls`
function.  This way, we have a new function that can provide information
about whether the NFS + Orchestrator is available or not.

Fixes: https://tracker.ceph.com/issues/56246

Fixes: https://bugs.launchpad.net/charm-ceph-dashboard/+bug/2039955

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Comment by avanthakkar** [comment]
jenkins retest this please

**Comment by sabaini** [comment]
jenkins retest this please

**Comment by cloudbehl** [comment]
jenkins retest this please

**Comment by pponnuvel** [comment]
The errors seem unrelated. Can you please rebase to see if tests work? @samuelengineer

**Comment by pponnuvel** [comment]
This is probably the same issue as https://tracker.ceph.com/issues/59438

Telemetry bot has opened several issues for the same.

**Comment by pponnuvel** [comment]
@samuelallan72 FYI - This has been fixed in https://github.com/ceph/ceph/pull/56876.

**Pull request closed without merging**
