### PR TITLE
mimic: tests: ceph-admin-commands.sh workunit does not log what it's doing

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/37153

### CODE REVIEW

**Comment by smithfarm** [comment]
@yuriw This needs a ceph-ansible and/or ceph-deploy run.

**Comment by yuriw** [comment]
@badone FYI

**Comment by yuriw** [comment]
[wip-yuri2-testing-2018-11-19-1655-mimic](https://trello.com/c/evmSyETG/476-wip-yuri2-testing-2018-11-19-1655-mimic)

**Comment by yuriw** [comment]
@smithfarm sorry I forgot extra suites, will run after on @badone 's wip

**Comment by yuriw** [comment]
CEPH_QA_MAIL="ceph-qa@lists.ceph.com"; MACHINE_NAME=smithi; CEPH_BRANCH=mimic
MACHINE_NAME=ovh; teuthology-suite -v --ceph-repo https://github.com/ceph/ceph.git --suite-repo https://github.com/badone/ceph.git  -c $CEPH_BRANCH -m $MACHINE_NAME -s ceph-ansible -k distro -p 70 -e $CEPH_QA_MAIL --suite-branch wip-mimic-ceph_ansible-specify-branch-stable-3.2 --dry-run -n 15

http://pulpito.front.sepia.ceph.com:80/yuriw-2018-11-20_17:39:39-ceph-ansible-mimic-distro-basic-ovh/

**Comment by smithfarm** [comment]
@yuriw Which extra suites? This workunit is only used by ceph-ansible and ceph-deploy.

**Comment by yuriw** [comment]
@smithfarm see ceph-ansible run ^

**Pull request merged**
