### PR TITLE
squid: test/neorados: remove depreciated RemoteReads cls test

### PR DESCRIPTION
**Pull request by ljflores**
backport tracker: https://tracker.ceph.com/issues/66463

---

backport of https://github.com/ceph/ceph/pull/57486
parent tracker: https://tracker.ceph.com/issues/66019

this backport was staged using ceph-backport.sh version 16.0.0.6848
find the latest version at https://github.com/ceph/ceph/blob/main/src/script/ceph-backport.sh

### CODE REVIEW

**Comment by ljflores** [comment]
Built packages here: https://shaman.ceph.com/builds/ceph/wip-lflores-testing-2024-06-19-1556-squid/

**Comment by ljflores** [comment]
jenkins test make check

**Comment by ljflores** [comment]
jenkins test make check

**Comment by ljflores** [comment]
> Built packages here: https://shaman.ceph.com/builds/ceph/wip-lflores-testing-2024-06-19-1556-squid/
> 
> Tests scheduled here: https://pulpito.ceph.com/lflores-2024-06-20_17:24:28-orch:cephadm:with-work-wip-lflores-testing-2024-06-19-1556-squid-distro-default-smithi/

Failures are unrelated cluster warnings, tracked by:
- https://tracker.ceph.com/issues/64872

**Comment by ljflores** [comment]
Depends on https://github.com/ceph/ceph/pull/57819 merging first.

**Comment by ljflores** [comment]
https://github.com/ceph/ceph/pull/57819 merged, so this needs to be backported.

**Review by neha-ojha — APPROVED** [review]

**Comment by ljflores** [comment]
> > Built packages here: https://shaman.ceph.com/builds/ceph/wip-lflores-testing-2024-06-19-1556-squid/
> > Tests scheduled here: https://pulpito.ceph.com/lflores-2024-06-20_17:24:28-orch:cephadm:with-work-wip-lflores-testing-2024-06-19-1556-squid-distro-default-smithi/
> 
> Failures are unrelated cluster warnings, tracked by:
> 
> * https://tracker.ceph.com/issues/64872

Teuthology tests passed, so merging.

**Pull request merged**
