### PR TITLE
Batch backport for nvme listener, namesapces and regression fix

### PR DESCRIPTION
**Pull request by afreen23**
Original PR:
https://github.com/ceph/ceph/pull/58648/
https://github.com/ceph/ceph/pull/58636

Backport Tracker:
https://tracker.ceph.com/issues/67004
https://tracker.ceph.com/issues/67017
https://tracker.ceph.com/issues/67031

Backport Summary:
https://github.com/ceph/ceph/pull/58667/commits/a17ad6721a5b4344c08dd52204cf9ba0961d06c0 : no conflicts, clean cherrypick

https://github.com/ceph/ceph/pull/58667/commits/aeccd480f0fd1f9b929800d7608630ea83062dc9 : conflicts mentioned

https://github.com/ceph/ceph/pull/58667/commits/4ef160bdcfe68e9067f50bdabc66b2784065037f: conflicts mentioned

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [x] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [x] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Comment by afreen23** [comment]
jenkins test dashboard cephadm

**Comment by afreen23** [comment]
jenkins test make check

**Review by avanthakkar — APPROVED** [review]

**Comment by afreen23** [comment]
tests failing due to:
```

Error: src/app/shared/datatable/table/table.component.ts:78:1 - error TS1185: Merge conflict marker encountered.

78 <<<<<<< HEAD
   ~~~~~~~


Error: src/app/shared/datatable/table/table.component.ts:79:1 - error TS1185: Merge conflict marker encountered.

79 =======
   ~~~~~~~
```
Fixed them now, with recent push.

**Comment by nizamial09** [comment]
jenkins test make check

**Comment by nizamial09** [comment]
jenkins test api

**Comment by afreen23** [comment]
jenkins test dashboard

**Comment by afreen23** [comment]
jenkins test dashboard

**Comment by afreen23** [comment]
jenkins test dashboard

**Comment by afreen23** [comment]
cephadm test failure issues:

```
stop-signal=SIGTERM --net=host --entrypoint /usr/bin/ceph --init -e CONTAINER_IMAGE=quay.ceph.io/ceph-ci/ceph:main -e NODE_NAME=ceph-node-00 -v /var/log/ceph/8dd0daae-45af-11ef-a684-525400e10eb0:/var/log/ceph:z -v /tmp/ceph-tmp9h779njf:/etc/ceph/ceph.client.admin.keyring:z -v /tmp/ceph-tmp8pi845pb:/etc/ceph/ceph.conf:z quay.ceph.io/ceph-ci/ceph:main mgr module enable cephadm: Error ENOENT: module 'cephadm' reports that it cannot run on the active manager daemon: 'mgmt-gateway' (pass --force to force enablement)
Jul 19 09:17:50 ceph-node-00 cloud-init[831]:         ***************
Jul 19 09:17:50 ceph-node-00 cloud-init[831]:         Cephadm hit an issue during cluster installation. Current cluster files will be deleted automatically.
Jul 19 09:17:50 ceph-node-00 cloud-init[831]:         To disable this behaviour you can pass the --no-cleanup-on-failure flag. In case of any previous
Jul 19 09:17:50 ceph-node-00 cloud-init[831]:         broken installation, users must use the following command to completely delete the broken cluster:
Jul 19 09:17:50 ceph-node-00 cloud-init[831]:         > cephadm rm-cluster --force --zap-osds --fsid <fsid>
Jul 19 09:17:50 ceph-node-00 cloud-init[831]:         for more information please refer to https://docs.ceph.com/en/latest/cephadm/operations/#purging-a-cluster
Jul 19 09:17:50 ceph-node-00 cloud-init[831]:         ***************
Jul 19 09:17:50 ceph-node-00 cloud-init[831]: Deleting cluster with fsid: 8dd0daae-45af-11ef-a684-525400e10eb0
Jul 19 09:17:52 ceph-node-00 cloud-init[831]: Traceback (most recent call last):
Jul 19 09:17:52 ceph-node-00 cloud-init[831]:   File "/usr/lib64/python3.10/runpy.py", line 196, in _run_module_as_main
```

**Pull request merged**
