### PR TITLE
hammer: Scrub error: 0/1 pinned

### PR DESCRIPTION
**Pull request by Vicente-Cheng**
http://tracker.ceph.com/issues/16149

### CODE REVIEW

**Comment by jdurgin** [comment]
This will need to adjusted for hammer - it doesn't compile as-is:

```osd/ReplicatedPG.cc: In member function 'int ReplicatedPG::_delete_oid(ReplicatedPG::OpContext*, bool)':
osd/ReplicatedPG.cc:5233:10: error: 'struct object_info_t' has no member named 'is_cache_pinned'
   if (oi.is_cache_pinned()) {
          ^
osd/ReplicatedPG.cc:5234:22: error: 'struct object_stat_sum_t' has no member named 'num_objects_pinned'
     ctx->delta_stats.num_objects_pinned--;
                      ^```

**Comment by smithfarm** [comment]
Hm, should http://tracker.ceph.com/issues/16149 be reopened, then?

**Comment by jdurgin** [comment]
I think this may not be needed for hammer, since pinned objects aren't part of the pg stats.

**Comment by Vicente-Cheng** [comment]
@liewegas @smithfarm 
I am sorry for that, I know it comes complie error and want to fixed this backport pr tonight.
sorry about sage merge and revert.

and thanks for @jdurgin 's reminder, so now it still need to backport to hammer?

btw, next time I meet the similar problem (mean complie with error and need some time to fix it)
how do I hand on backport pr?

thanks!!

**Comment by smithfarm** [comment]
@Vicente-Cheng If you don't want it to be merged, edit the PR title and prefix it with "DNM" (stands for "Do Not Merge")

AFAIK the backport tracker issue http://tracker.ceph.com/issues/16149 has been rejected and the hammer backport is not needed.

**Comment by Vicente-Cheng** [comment]
@smithfarm 

OK! I will do that next time I need.
and very thanks for your tips : )

**Pull request merged**
