### PR TITLE
mimic: rgw: default quota not set in radosgw for Openstack users

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/36223

### CODE REVIEW

**Comment by smithfarm** [comment]
Jenkins re-test this please

**Comment by smithfarm** [comment]
```
/home/jenkins-build/build/workspace/ceph-pull-requests/src/rgw/rgw_quota.cc: In function 'void rgw_apply_default_bucket_quota(RGWQuotaInfo&, const md_config_t&)':
/home/jenkins-build/build/workspace/ceph-pull-requests/src/rgw/rgw_quota.cc:1011:11: error: base operand of '->' has non-pointer type 'const md_config_t'
   if (conf->rgw_bucket_default_quota_max_objects >= 0) {
           ^~
/home/jenkins-build/build/workspace/ceph-pull-requests/src/rgw/rgw_quota.cc:1012:29: error: base operand of '->' has non-pointer type 'const md_config_t'
     quota.max_objects = conf->rgw_bucket_default_quota_max_objects;
                             ^~
/home/jenkins-build/build/workspace/ceph-pull-requests/src/rgw/rgw_quota.cc:1015:11: error: base operand of '->' has non-pointer type 'const md_config_t'
   if (conf->rgw_bucket_default_quota_max_size >= 0) {
           ^~
/home/jenkins-build/build/workspace/ceph-pull-requests/src/rgw/rgw_quota.cc:1016:26: error: base operand of '->' has non-pointer type 'const md_config_t'
     quota.max_size = conf->rgw_bucket_default_quota_max_size;
                          ^~
/home/jenkins-build/build/workspace/ceph-pull-requests/src/rgw/rgw_quota.cc: In function 'void rgw_apply_default_user_quota(RGWQuotaInfo&, const md_config_t&)':
/home/jenkins-build/build/workspace/ceph-pull-requests/src/rgw/rgw_quota.cc:1023:11: error: base operand of '->' has non-pointer type 'const md_config_t'
   if (conf->rgw_user_default_quota_max_objects >= 0) {
           ^~
/home/jenkins-build/build/workspace/ceph-pull-requests/src/rgw/rgw_quota.cc:1024:29: error: base operand of '->' has non-pointer type 'const md_config_t'
     quota.max_objects = conf->rgw_user_default_quota_max_objects;
                             ^~
/home/jenkins-build/build/workspace/ceph-pull-requests/src/rgw/rgw_quota.cc:1027:11: error: base operand of '->' has non-pointer type 'const md_config_t'
   if (conf->rgw_user_default_quota_max_size >= 0) {
           ^~
/home/jenkins-build/build/workspace/ceph-pull-requests/src/rgw/rgw_quota.cc:1028:26: error: base operand of '->' has non-pointer type 'const md_config_t'
     quota.max_size = conf->rgw_user_default_quota_max_size;
                          ^~
src/rgw/CMakeFiles/rgw_a.dir/build.make:1410: recipe for target 'src/rgw/CMakeFiles/rgw_a.dir/rgw_quota.cc.o' failed
```

**Comment by cbodley** [comment]
looks good, thanks @smithfarm!

**Comment by yuriw** [comment]
[wip-yuri2-testing-2018-11-19-1655-mimic](https://trello.com/c/evmSyETG/476-wip-yuri2-testing-2018-11-19-1655-mimic)

**Pull request merged**
