### PR TITLE
librbd: look for mirror peers in default namespace

### PR DESCRIPTION
**Pull request by trociny**
(when creating primary mirror snapshot)

Signed-off-by: Mykola Golub <mgolub@suse.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by trociny** [comment]
@dillaman We configure peers only in the default namespace, so this is where we should look for them.

I also noticed that in `api::Mirror::image_status_summary` we get the list of peers from the current namespace. But this probably is supposed to work because it seems the peers will be autogenerated here by mirror ping.

**Comment by dillaman** [comment]
> I also noticed that in `api::Mirror::image_status_summary` we get the list of peers from the current namespace. But this probably is supposed to work because it seems the peers will be autogenerated here by mirror ping.

Correct -- but this did remind me to open a tracker ticket to ensure that those non-default namespace peers are removed when removing the matching peer from the default namespace.

**Comment by dillaman** [comment]
... does need fixes to the unit tests, though

**Comment by tchaikov** [comment]
jenkins test make check

**Comment by trociny** [comment]
> ... does need fixes to the unit tests, though

@dillaman fixed, probably a bit hackish. If you know a better way....

**Comment by dillaman** [comment]
[1] shows an example of handling the `librados::IoCtx::dup` call 

[1] https://github.com/ceph/ceph/blob/master/src/test/librbd/image/test_mock_ValidatePoolRequest.cc#L45

**Comment by trociny** [comment]
@dillaman thank you. Updated

**Pull request merged**
