### PR TITLE
luminous: os/bluestore: fix collection_list ordering

### PR DESCRIPTION
**Pull request by trociny**
backport tracker: https://tracker.ceph.com/issues/47364

---

backport of https://github.com/ceph/ceph/pull/36230
parent tracker: https://tracker.ceph.com/issues/43174

this backport was staged using ceph-backport.sh version 15.1.1.389
find the latest version at https://github.com/ceph/ceph/blob/master/src/script/ceph-backport.sh

### CODE REVIEW

**Comment by smithfarm** [comment]
I know luminous is EOL, but there are still big clusters out there running luminous and this would help them to migrate from filestore to bluestore in preparation for upgrading.

**Review by neha-ojha — APPROVED** [review]

**Review by ifed01 — APPROVED** [review]

**Comment by trociny** [comment]
Pushed an additional commit, which is a backport of #37999.

**Comment by smithfarm** [comment]
@trociny @ifed01 @tchaikov I'd like to merge this now. Can you think of any reason why not?

**Comment by trociny** [comment]
no objections from my side

**Comment by ifed01** [comment]
+1 to proceed

**Pull request merged**
