### PR TITLE
cmake: fix "WITH_STATIC_LIBSTDCXX"

### PR DESCRIPTION
**Pull request by tchaikov**
- do not link libkv with ALLOC_LIBS, it turns out that if we link
tcmalloc *before* -static-libstdc++ -static-libgcc, libstdc++ and gcc
libs will show up in `ldd` output
- add `-static-libstdc++ -static-libgcc` to CMAKE_SHARED_LINKER_FLAGS
and CMAKE_EXE_LINKER_FLAGS instead of adding them to all shared
libraries and executable. simpler this way.

Signed-off-by: Kefu Chai <kchai@redhat.com>

### CODE REVIEW

**Comment by liewegas** [comment]
My test run accumulated multiple instances of a few new failures...
```
2018-07-11T21:19:05.762 INFO:tasks.ceph.osd.6.smithi093.stderr:*** Caught signal (Aborted) **
2018-07-11T21:19:05.762 INFO:tasks.ceph.osd.6.smithi093.stderr: in thread 7f888ed66700 thread_name:tp_osd_tp
2018-07-11T21:19:05.771 INFO:tasks.ceph.osd.6.smithi093.stderr: ceph version 14.0.0-1254-g3bbd1db (3bbd1db9eda6a2f474e1040c1ffececd4b9b4b64) nautilus (dev)
2018-07-11T21:19:05.771 INFO:tasks.ceph.osd.6.smithi093.stderr: 1: (()+0x11390) [0x7f88bacfd390]
2018-07-11T21:19:05.771 INFO:tasks.ceph.osd.6.smithi093.stderr: 2: (gsignal()+0x38) [0x7f88b9e0a428]
2018-07-11T21:19:05.772 INFO:tasks.ceph.osd.6.smithi093.stderr: 3: (abort()+0x16a) [0x7f88b9e0c02a]
2018-07-11T21:19:05.772 INFO:tasks.ceph.osd.6.smithi093.stderr: 4: (()+0x156cbe) [0x7f88a5206cbe]
2018-07-11T21:19:05.772 INFO:tasks.ceph.osd.6.smithi093.stderr: 5: (__gxx_personality_v0()+0xe1) [0x7f88a5163ac1]
2018-07-11T21:19:05.772 INFO:tasks.ceph.osd.6.smithi093.stderr: 6: (()+0x11ed7e3) [0x55b7b10e27e3]
2018-07-11T21:19:05.772 INFO:tasks.ceph.osd.6.smithi093.stderr: 7: (()+0x11edfff) [0x55b7b10e2fff]
2018-07-11T21:19:05.772 INFO:tasks.ceph.osd.6.smithi093.stderr: 8: (__cxa_throw()+0x37) [0x55b7b103d197]
2018-07-11T21:19:05.773 INFO:tasks.ceph.osd.6.smithi093.stderr: 9: (ceph::buffer::list::iterator_impl<true>::copy(unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)+0xdf) [0x55b7b0a17e4f]
2018-07-11T21:19:05.773 INFO:tasks.ceph.osd.6.smithi093.stderr: 10: (()+0x9e0ab) [0x7f88a514e0ab]
2018-07-11T21:19:05.773 INFO:tasks.ceph.osd.6.smithi093.stderr: 11: (()+0x7931e) [0x7f88a512931e]
2018-07-11T21:19:05.773 INFO:tasks.ceph.osd.6.smithi093.stderr: 12: (ClassHandler::ClassMethod::exec(void*, ceph::buffer::list&, ceph::buffer::list&)+0x34) [0x55b7b0525744]
2018-07-11T21:19:05.773 INFO:tasks.ceph.osd.6.smithi093.stderr: 13: (PrimaryLogPG::do_osd_ops(PrimaryLogPG::OpContext*, std::vector<OSDOp, std::allocator<OSDOp> >&)+0x114a) [0x55b7b0636dda]
2018-07-11T21:19:05.773 INFO:tasks.ceph.osd.6.smithi093.stderr: 14: (PrimaryLogPG::prepare_transaction(PrimaryLogPG::OpContext*)+0x9f) [0x55b7b0647d4f]
2018-07-11T21:19:05.774 INFO:tasks.ceph.osd.6.smithi093.stderr: 15: (PrimaryLogPG::execute_ctx(PrimaryLogPG::OpContext*)+0x38b) [0x55b7b064854b]
2018-07-11T21:19:05.774 INFO:tasks.ceph.osd.6.smithi093.stderr: 16: (PrimaryLogPG::do_op(boost::intrusive_ptr<OpRequest>&)+0x3644) [0x55b7b064cf74]
2018-07-11T21:19:05.774 INFO:tasks.ceph.osd.6.smithi093.stderr: 17: (PrimaryLogPG::do_request(boost::intrusive_ptr<OpRequest>&, ThreadPool::TPHandle&)+0xcd0) [0x55b7b0651190]
```
this is calling into cls_numops.  maybe a linking or ABI issue?
/a/sage-2018-07-11_16:15:31-rados-wip-sage4-testing-2018-07-11-0934-distro-basic-smithi/2768885

also, some other failures, but i think they're side-effects of the above.

**Comment by tchaikov** [comment]
```
 ceph version 14.0.0-1105-g0a176a0 (0a176a027c429794cce4a456779fe871bc51a7fc) nautilus (dev)
 1: (()+0x11390) [0x7f30692b0390]
 2: (gsignal()+0x38) [0x7f30685c1428]
 3: (abort()+0x16a) [0x7f30685c302a]
 4: (__gnu_cxx::__verbose_terminate_handler()+0x135) [0x14c5195]
 5: (__cxxabiv1::__terminate(void (*)())+0x6) [0x7f30545637a6]
 6: (()+0x1408c9) [0x7f30545638c9]
 7: (__gxx_personality_v0()+0x328) [0x7f30544d6d08]
 8: (__libunwind_Unwind_RaiseException()+0x1ef) [0x7f306af31a9f]
 9: (__cxa_throw()+0x37) [0x14b8917]
 10: (ceph::buffer::list::iterator_impl<true>::copy(unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)+0xdf) [0xe78aaf]
 11: (()+0x9e0ab) [0x7f30544c10ab]
 12: (()+0x7931e) [0x7f305449c31e]
 13: (ClassHandler::ClassMethod::exec(void*, ceph::buffer::list&, ceph::buffer::list&)+0x34) [0x98ac64]
 14: (PrimaryLogPG::do_osd_ops(PrimaryLogPG::OpContext*, std::vector<OSDOp, std::allocator<OSDOp> >&)+0x114a) [0xa9c62a]
 15: (PrimaryLogPG::prepare_transaction(PrimaryLogPG::OpContext*)+0x9f) [0xaad59f]
 16: (PrimaryLogPG::execute_ctx(PrimaryLogPG::OpContext*)+0x38b) [0xaadd9b]
 17: (PrimaryLogPG::do_op(boost::intrusive_ptr<OpRequest>&)+0x3644) [0xab27c4]
 18: (PrimaryLogPG::do_request(boost::intrusive_ptr<OpRequest>&, ThreadPool::TPHandle&)+0xcd0) [0xab69e0]
 19: (OSD::dequeue_op(boost::intrusive_ptr<PG>, boost::intrusive_ptr<OpRequest>, ThreadPool::TPHandle&)+0x1b7) [0x90fb17]
 20: (PGOpItem::run(OSD*, OSDShard*, boost::intrusive_ptr<PG>&, ThreadPool::TPHandle&)+0x62) [0xb8aa92]
 21: (OSD::ShardedOpWQ::_process(unsigned int, ceph::heartbeat_handle_d*)+0x590) [0x931d50]
 22: (ShardedThreadPool::shardedthreadpool_worker(unsigned int)+0x46e) [0xeb401e]
 23: (ShardedThreadPool::WorkThreadSharded::entry()+0x10) [0xeb63f0]
 24: (()+0x76ba) [0x7f30692a66ba]
 25: (clone()+0x6d) [0x7f306869341d]
 26: [(nil)]
```

/a/kchai-2018-07-12_15:09:12-rados-wip-kefu-cmake-link-static-libstdc++-distro-basic-mira/2771695

**Comment by tchaikov** [comment]
i am able to reproduce this issue with `bin/unittest_libcephfs_config`:


```
#0  0x00007ffff73c9428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
#1  0x00007ffff73cb02a in __GI_abort () at abort.c:89
#2  0x000000000051ecf5 in __gnu_cxx::__verbose_terminate_handler() ()
#3  0x000000000051be76 in __cxxabiv1::__terminate(void (*)()) ()
#4  0x00000000005ad3f9 in __cxa_call_terminate ()
#5  0x000000000051d6a8 in __gxx_personality_v0 ()
#6  0x00007fffec7a6c1e in __libunwind_Unwind_Resume () from /usr/lib/x86_64-linux-gnu/libunwind.so.8
#7  0x00007fffee61b806 in boost::conversion::detail::throw_bad_cast<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, unsigned long> ()
    at /var/ceph/ceph-ubuntu-16.04-kefu/build/boost/include/boost/lexical_cast/bad_lexical_cast.hpp:92
#8  0x00007fffee61b311 in boost::lexical_cast<unsigned long, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > (arg=...)
    at /var/ceph/ceph-ubuntu-16.04-kefu/build/boost/include/boost/lexical_cast.hpp:42
#9  0x00007fffee61a5f0 in librbd::rbd_features_from_string (orig_value=..., err=0x7ffffffe4a30) at /var/ceph/ceph-ubuntu-16.04-kefu/src/librbd/Features.cc:63
#10 0x00007fffee4b5497 in <lambda(std::__cxx11::string*, std::__cxx11::string*)>::operator()(std::__cxx11::string *, std::__cxx11::string *) const (__closure=0x7ffff7efb8d0,
    value=0x7fffffff0840, error_message=0x7fffffff0860) at /var/ceph/ceph-ubuntu-16.04-kefu/src/common/options.cc:6324
#11 0x00007fffee4c6230 in std::_Function_handler<int(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*), get_rbd_options()::<lambda(std::__cxx11::string*, std::__cxx11::string*)> >::_M_invoke(const std::_Any_data &, <unknown type in /var/ceph/ceph-ubuntu-16.04-kefu/build/lib/libceph-common.so.0, CU 0x2c8271c, DIE 0x2d93e84>, <unknown type in /var/ceph/ceph-ubuntu-16.04-kefu/build/lib/libceph-common.so.0, CU 0x2c8271c, DIE 0x2d93e93>) (__functor=..., __args#0=<unknown type in /var/ceph/ceph-ubuntu-16.04-kefu/build/lib/libceph-common.so.0, CU 0x2c8271c, DIE 0x2d93e84>,
    __args#1=<unknown type in /var/ceph/ceph-ubuntu-16.04-kefu/build/lib/libceph-common.so.0, CU 0x2c8271c, DIE 0x2d93e93>) at /usr/include/c++/7/bits/std_function.h:302
#12 0x00007fffee4c8cf7 in std::function<int (std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*)>::operator()(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*) const (this=0x7ffff7efb8d0, __args#0=0x7fffffff0840, __args#1=0x7fffffff0860) at /usr/include/c++/7/bits/std_function.h:706
#13 0x00007fffee466f36 in Option::pre_validate (this=0x7ffff7efb740, new_value=0x7fffffff0840, err=0x7fffffff0860) at /var/ceph/ceph-ubuntu-16.04-kefu/src/common/options.cc:81
#14 0x00007fffee51dd60 in ceph::internal::md_config_impl<(ceph::internal::LockPolicy)1>::md_config_impl (this=0x849970, values=..., is_daemon=false)
    at /var/ceph/ceph-ubuntu-16.04-kefu/src/common/config.cc:197
#15 0x00007fffee43ca9b in std::make_unique<ceph::internal::md_config_impl<(ceph::internal::LockPolicy)1>, ConfigValues&, bool&> (__args#0=..., __args#1=@0x7fffffffe4a4: false)
    at /usr/include/c++/7/bits/unique_ptr.h:825
#16 0x00007fffee43a61b in ConfigProxy::ConfigProxy (this=0x861ab8, is_daemon=false) at /var/ceph/ceph-ubuntu-16.04-kefu/src/common/config_proxy.h:20
```

**Comment by tchaikov** [comment]
http://pulpito.ceph.com/kchai-2018-07-29_15:20:14-rados-wip-static-libstdcxx-kefu-distro-basic-smithi/

**Comment by tchaikov** [comment]
http://pulpito.ceph.com/kchai-2018-07-30_23:45:11-rados-wip-kefu-testing-2018-07-30-2341-distro-basic-mira/

**Pull request merged**
