### PR TITLE
nautilus: mgr/dashboard: add debug mode, and accept expected exception when SSL handshaking

### PR DESCRIPTION
**Pull request by epuertat**
backport trackers:

* https://tracker.ceph.com/issues/42294
* https://tracker.ceph.com/issues/42557
* https://tracker.ceph.com/issues/43054

---

backport of:

* https://github.com/ceph/ceph/pull/30522
* https://github.com/ceph/ceph/pull/31014 (required for the following to apply)
* https://github.com/ceph/ceph/pull/31266
* https://github.com/ceph/ceph/pull/31431
* https://github.com/ceph/ceph/pull/31190

parent trackers:

* https://tracker.ceph.com/issues/38378
* https://tracker.ceph.com/issues/41990
* https://tracker.ceph.com/issues/42565
* https://tracker.ceph.com/issues/42708

### CODE REVIEW

**Comment by epuertat** [comment]
jenkins test dashboard

**Comment by smithfarm** [comment]
@epuertat Feel free to combine several related backports into a single PR. For example, you might consider doing the cherry-pick of #31014 right here in this PR.

**Comment by epuertat** [comment]
> @epuertat Feel free to combine several related backports into a single PR. For example, you might consider doing the cherry-pick of #31014 right here in this PR.

Thanks a lot, @smithfarm! I'll do that.

**Comment by smithfarm** [comment]
jenkins test make check

**Comment by epuertat** [comment]
jenkins test dashboard

**Comment by epuertat** [comment]
QA in progress:
- [Package builds](https://shaman.ceph.com/builds/ceph/wip-epuertat-testing-2019-11-12-1147/)
- Teuthology

**Comment by tchaikov** [comment]
@epuertat could you include #31431 in this changset?

**Comment by epuertat** [comment]
> @epuertat could you include #31431 in this changset?

Sure, @tchaikov! I'll pass the QA for the packages already built, and another one only for OpenSUSE 15.1, which is the only distro using Cherrypy > 9.

**Comment by tchaikov** [comment]
@epuertat to address the FTBFS failure on opensuse, probably you could backport #28809 .

**Comment by epuertat** [comment]
> @epuertat to address the FTBFS failure on opensuse, probably you could backport #28809 .

Tried it, but the cherry-pick is not clean, as in nautilus `RGWHandler_REST_Bucket_S3::get_obj_op` does not return `RGWListBucket_ObjStore_S3v2`, so the code change resulting from the merge conflict is trivial.

**Comment by epuertat** [comment]
QA tried again (last one got stuck):
- [Packages](https://shaman.ceph.com/builds/ceph/wip-epuertat-testing-2019-11-13-2103/)
- Teuthology

**Comment by epuertat** [comment]
4th try :see_no_evil: :
- [Packages](https://shaman.ceph.com/builds/ceph/wip-epuertat-testing-2019-11-14-1730/)
- Teuthology

**Comment by epuertat** [comment]
Packages failed again for OpenSUSE. Backporting fix in https://github.com/ceph/ceph/pull/31678.

**Comment by epuertat** [comment]
Blocked by https://github.com/ceph/ceph/pull/31678

**Comment by epuertat** [comment]
- [Packages](https://shaman.ceph.com/builds/ceph/wip-epuertat-testing-2019-11-18-1029/): 4/6 (failed: CentOS:8 and Ubuntun:bionic+crimson)
- [QA](http://pulpito.ceph.com/epuertat-2019-11-18_12:48:49-rados:dashboard-wip-epuertat-testing-2019-11-18-1029-distro-basic-smithi/) (ongoing)

**Comment by epuertat** [comment]
TODO:
- Add backporting of https://github.com/ceph/ceph/pull/31720

**Comment by epuertat** [comment]
[Packages](https://shaman.ceph.com/builds/ceph/wip-epuertat-testing-2019-11-28-1351/) ongoing.

**Comment by callithea** [comment]
- QA run [WIP]: http://pulpito.ceph.com/laura-2020-01-27_16:19:37-rados:dashboard-wip-laura-testing-nautilus-batch-8-distro-basic-mira/

**Comment by callithea** [comment]
@yuriw, @smithfarm : Should we wait for a rados QA run or could we merge this PR?

**Comment by callithea** [comment]
jenkins test dashboard backend

**Comment by callithea** [comment]
- [rados/mgr](http://pulpito.ceph.com/laura-2020-02-04_17:10:38-rados:mgr-wip-laura-testing-dashboard-nautilus-batch-8-distro-basic-smithi/) QA run [WIP]
- [rados/dashboard](http://pulpito.ceph.com/laura-2020-02-04_17:10:06-rados:dashboard-wip-laura-testing-dashboard-nautilus-batch-8-distro-basic-smithi/) QA run [WIP]

**Comment by callithea** [comment]
jenkins test make check

**Pull request merged**
