### PR TITLE
mgr/dashboard: pin xmlsec to 1.3.13

### PR DESCRIPTION
**Pull request by nizamial09**
Also has: [qa/vstart_runner: increase timeout for vstart.sh command](https://github.com/ceph/ceph/pull/56974/commits/5a8a9df401663ca48b0031104d00ea0e4b636165) which fixes Fixes: https://tracker.ceph.com/issues/65565

xmlsec is an inner dependency used by python3-saml. A [newer release ](https://pypi.org/project/xmlsec/#history)of it broke the import.
https://github.com/xmlsec/python-xmlsec/issues/314

Fixes the `run-tox-mgr-dashboard-py3` failure in [make check](https://jenkins.ceph.com/job/ceph-pull-requests/133500/consoleFull#-1011227698e840cee4-f4a4-4183-81dd-42855615f2c1)
```
__init__.py:60: in <module>
    from .module import Module, StandbyModule  # noqa: F401
module.py:36: in <module>
    from .services.sso import SSO_COMMANDS, handle_sso_command
services/sso.py:20: in <module>
    from onelogin.saml2.settings import OneLogin_Saml2_Settings as Saml2Settings
.tox/py3/lib/python3.10/site-packages/onelogin/saml2/settings.py:18: in <module>
    from onelogin.saml2.metadata import OneLogin_Saml2_Metadata
.tox/py3/lib/python3.10/site-packages/onelogin/saml2/metadata.py:15: in <module>
    from onelogin.saml2.utils import OneLogin_Saml2_Utils
.tox/py3/lib/python3.10/site-packages/onelogin/saml2/utils.py:23: in <module>
    import xmlsec
E   xmlsec.Error: (100, 'lxml & xmlsec libxml2 library version mismatch')
```

Fixes: https://tracker.ceph.com/issues/65571

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Comment by nizamial09** [comment]
**NOTE**: I am intending this as a temporary fix. When a proper fix from xmlsec has been released, I might revert this change since I don't want to pin an inner dependency in our project.

**Review by tchaikov — APPROVED** [review]
lgtm.

**Comment by nizamial09** [comment]
jenkins test dashboard cephadm

**Comment by nizamial09** [comment]
jenkins test api

**Comment by nizamial09** [comment]
jenkins test windows

**Comment by rishabh-d-dave** [comment]
@nizamial09 Is the fix on this PR related to the failure here - https://jenkins.ceph.com/job/ceph-pull-requests/133510/consoleFull#-1417082282e2f9bd1b-f570-4eac-a6c0-0080730e3135

**Comment by rishabh-d-dave** [comment]
@nizamial09 The Ceph API test failure (https://jenkins.ceph.com/job/ceph-api/72608/consoleFull#1610380190c212b007-e891-4176-9ee7-2f60eca393b7) can be fixed with following patch - 

```
diff --git a/qa/tasks/vstart_runner.py b/qa/tasks/vstart_runner.py
index 3ef987f4d7c..c2098f9abaa 100644
--- a/qa/tasks/vstart_runner.py
+++ b/qa/tasks/vstart_runner.py
@@ -1399,7 +1399,7 @@ def exec_test():
         log.info('\nrunning vstart.sh now...')
         # usually, i get vstart.sh running completely in less than 100
         # seconds.
-        remote.run(args=args, env=vstart_env, timeout=(5 * 60))
+        remote.run(args=args, env=vstart_env)
         log.info('\nvstart.sh finished running')
 
         # Wait for OSD to come up so that subsequent injectargs etc will
```

For CephFS, 180 seconds is enough. But I've set it to 300 seconds on latest main. Since it's not enough for Ceph API tests sometimes (some Ceph API tests are passing and some are failing), I recommend, instead of removing  `timeout`, setting it to a more reasonable number.

**Comment by nizamial09** [comment]
> @nizamial09 Is the fix on this PR related to the failure here - https://jenkins.ceph.com/job/ceph-pull-requests/133510/consoleFull#-1417082282e2f9bd1b-f570-4eac-a6c0-0080730e3135? I see this issue on other PRs too.

yup, this address that failure.
```
 40/293 Test   #7: run-tox-mgr-dashboard-py3 .................   Passed  298.19 sec
 ```
 its passing in the PR but make check is failing on unrelated issue.

> etting it to a more reasonable number.
> 
> **EDIT: PR for above patch - #56977, feel free to cherry-pick the commit here.**

@rishabh-d-dave Thank you, I'll cherry-pick that here so both gets fixed in one go

**Comment by cbodley** [comment]
thanks @nizamial09, i'm seeing these failures on squid PRs too. can you please make sure there's a tracker issue for backport(s)?

**Comment by nizamial09** [comment]
> thanks @nizamial09, i'm seeing these failures on squid PRs too. can you please make sure there's a tracker issue for backport(s)?

opened the tracker and attached to the commit

**Comment by nizamial09** [comment]
[unrelated failure](https://jenkins.ceph.com/job/ceph-pull-requests/133544/consoleFull#1351773342e840cee4-f4a4-4183-81dd-42855615f2c1) but its the second time i am seeing this
```
293/293 Test #261: unittest-seastore .........................***Timeout 7200.34 sec
WARNING: debug mode. Not for benchmarking or production
```

**Comment by nizamial09** [comment]
jenkins test make check

**Comment by nizamial09** [comment]
dashboard cephadm e2e can be ignored. Its unrelated cypress failure.

**Comment by rishabh-d-dave** [comment]
@nizamial09 Let's merge this PR?

**Comment by nizamial09** [comment]
@rishabh-d-dave does your fix need squid backport?

**Comment by rishabh-d-dave** [comment]
> @rishabh-d-dave does your fix need squid backport?

@cbodley mentioned that we need Squid backport [here](https://github.com/ceph/ceph/pull/56974#issuecomment-2063847204) but the patch that brought this issue to surface wasn't backported to Squid - https://github.com/ceph/ceph/blob/squid/qa/tasks/vstart_runner.py#L1396. Without that patch, `timeout` parameter has no effect. So Squid backports hitting same issue is weird.

Is vstart_runner.py from main being used for Squid backport's CI jobs? In this case we don't need backporting.

**Comment by rishabh-d-dave** [comment]
> > @rishabh-d-dave does your fix need squid backport?
> 
> @cbodley mentioned that we need Squid backport [here](https://github.com/ceph/ceph/pull/56974#issuecomment-2063847204) but the patch that brought this issue to surface wasn't backported to Squid - https://github.com/ceph/ceph/blob/squid/qa/tasks/vstart_runner.py#L1396. Without that patch, `timeout` parameter has no effect. So Squid backports hitting same issue is weird.
> 
> Is vstart_runner.py from main being used for Squid backport's CI jobs? In this case we don't need backporting.

@nizamial09 ping

**Pull request merged**
