### PR TITLE
rgw: fix rgw.none statistics

### PR DESCRIPTION
**Pull request by ivancich**
Only unaccount for objects being removed if they exist.

Also, clean up some formatting.

Signed-off-by: J. Eric Ivancich <ivancich@redhat.com>

Fixes: https://tracker.ceph.com/issues/51560

### CODE REVIEW

**Comment by cbodley** [comment]
@ivancich because the bucket stats are managed internally by cls_rgw for each index shard, i think an approach similar to ceph_test_cls_rgw (which only tests the cls_rgw_client api against a single rados object) is the easiest way to get test coverage for stats. in https://github.com/ceph/ceph/pull/43843 i started on a new test that throws a bunch of random create/delete operations at the index, and tracks the expected bucket stats in memory for comparison

**Review by cbodley — APPROVED** [review]

**Comment by cbodley** [comment]
i updated https://github.com/ceph/ceph/pull/43843 to model multipart uploads, and was a) able to reproduce these negative rgw.none stats from canceled multiparts, and b) verify that this pr resolved the issue

**Comment by ivancich** [comment]
> i updated #43843 to model multipart uploads, and was a) able to reproduce these negative rgw.none stats from canceled multiparts, and b) verify that this pr resolved the issue

That is awesome, @cbodley !

**Comment by cbodley** [comment]
passed qa https://pulpito.ceph.com/cbodley-2021-11-12_16:45:53-rgw-wip-cbodley-testing-distro-basic-smithi/

**Pull request merged**
