### PR TITLE
ceph-volume: remove container classes from api/lvm.py

### PR DESCRIPTION
**Pull request by rishabh-d-dave**
* removes container classes (i.e. ``PVolumes``, ``VolumeGroups`` and ``Volumes`` in ``api/lvm.py``) and related calls and exceptions
* removes functions ``get_api_pvs()``, ``get_api_vgs()`` and ``get_api_lvs()`` and related tests
* rearranges ``api/lvm.py``

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by rishabh-d-dave** [comment]
jenkins test ceph-volume tox

**Comment by rishabh-d-dave** [comment]
jenkins test ceph-volume all

**Comment by rishabh-d-dave** [comment]
@jan--f Both unit and func tests passed.

**Comment by tchaikov** [comment]
because 172.21.1.46+slave-ubuntu11 disk out of space, "ceph dashboard backend API tests" failed

**Comment by jan--f** [comment]
retest this please

**Comment by rishabh-d-dave** [comment]
jenkins test ceph-volume tox

**Comment by rishabh-d-dave** [comment]
jenkins test ceph-volume all

**Comment by rishabh-d-dave** [comment]
Most batch tests failed with `ModuleNotFoundError: No module named 'yaml'` and tox failed with `py27: InvocationError`. Retriggering tests...

**Comment by jan--f** [comment]
> Most batch tests failed with `ModuleNotFoundError: No module named 'yaml'` and tox failed with `py27: InvocationError`. Retriggering tests...

Should be fixed by #36372

**Comment by rishabh-d-dave** [comment]
@jan--f Except for tox tests, all tests passed. Waiting for your PR to get merged, thank you for letting me know!

**Comment by rishabh-d-dave** [comment]
jenkins test ceph-volume all

**Comment by rishabh-d-dave** [comment]
jenkins test ceph-volume tox

**Comment by rishabh-d-dave** [comment]
jenkins test ceph-volume tox

**Comment by rishabh-d-dave** [comment]
Rebased, the branch in on latest commit of master now.

**Comment by rishabh-d-dave** [comment]
jenkins test ceph-volume all

**Comment by rishabh-d-dave** [comment]
@jan--f All tests passed.

**Comment by rishabh-d-dave** [comment]
jenkins test ceph-volume tox

**Comment by jan--f** [comment]
I think we can ignore the tox failure. Its flake8 choking on unrelated code due to it using python2. I'll look into how we can force flake8 to use python3. Opened https://tracker.ceph.com/issues/46897 to track this.

**Comment by jan--f** [comment]
@rishabh-d-dave I assume you will take care of the backports for this.

**Pull request merged**
