### PR TITLE
rgw: DPP addition 5

### PR DESCRIPTION
**Pull request by TRYTOBE8TME**
## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by TRYTOBE8TME** [comment]
jenkins test make check

**Comment by TRYTOBE8TME** [comment]
jenkins test make check

**Comment by TRYTOBE8TME** [comment]
Teuthology link: https://pulpito.ceph.com/kapandya-2021-07-01_15:12:46-rgw-wip-rgw-dpp-4-distro-basic-smithi/

**Comment by TRYTOBE8TME** [comment]
Latest run: https://pulpito.ceph.com/kapandya-2021-07-20_19:01:27-rgw-wip-rgw-dpp-4-distro-basic-smithi/

**Comment by TRYTOBE8TME** [comment]
@cbodley are the failures from [this](https://pulpito.ceph.com/kapandya-2021-07-20_19:01:27-rgw-wip-rgw-dpp-4-distro-basic-smithi/) run all known?

**Review by alimaredia — APPROVED** [review]

**Comment by TRYTOBE8TME** [comment]
jenkins test api

**Comment by TRYTOBE8TME** [comment]
Teuthology run (after removing the bad commit): https://pulpito.ceph.com/kapandya-2021-08-20_08:50:24-rgw-wip-rgw-dpp-4-distro-basic-smithi/

**Pull request merged**
