### PR TITLE
rgw_file: NFSv3 should not check open state in rgw_rename()

### PR DESCRIPTION
**Pull request by cmgitdream**
Signed-off-by: Min Chen <chenmin@xsky.com>

### CODE REVIEW

**Comment by cmgitdream** [comment]
@mattbenjamin

**Comment by mattbenjamin** [comment]
@cmgitdream will this behave correctly when NFSv3 i/o is in progress?

**Comment by cmgitdream** [comment]
@mattbenjamin I noticed RFC1813 for NFSv3 has no open/close operation,
so file is opened in rgw file fs when it is created, but will not be closed.
so when rename file, it is rejected as file is opened

**Comment by mattbenjamin** [comment]
@cmgitdream got it;  the intent is, since NFSv3 has no open/close operation, the stateless-open flag causes an open to be simulated;  then, when no write i/o has been seen for the i/o timeout period, a close() is performed internally

**Comment by mattbenjamin** [comment]
@cmgitdream do you have any new thoughts on this PR?  to be fair, in POSIX, open state doesn't block rename()--which leads to silly rename--i/o in progress continues, but the result is discarded when all opens that originated before the rename are returned;  I think my idea was, for RGW, we could forego that complexity;  we also don't allow multiple write opens--is that a problem?

**Comment by cmgitdream** [comment]
@mattbenjamin oh, rgw file can not handle rename when opening file,  because rename changes inode number. I agree with you not change rename logic, just keep simple

**Comment by cmgitdream** [comment]
@mattbenjamin can we use a new desgin just keep inode number not changed after rename, 
eg, use database to record file / s3 object mapping

**Comment by mattbenjamin** [comment]
@cmgitdream well, question 1 first:  does rgw_read() need a new timer or periodic checks?  ans:  Not minimally, insofar as once for v4, opens will be followed by close and for v3, the existing timer will bound the lifetime of any write open (10s unless extended by subsequent writes);

In the larger picture, do we want to strengthen posix consistency guarantees for RGW NFS in general, the the point of reifying inode allocation in a central database;  ans:  I think the current model has a lot to recommend it, given the semantic choices RGW currently has made on the semantics of the underlying data stream, and I have certainly some affection for the property of the current design that it avoids the i/o and consistency cost we'd otherwise pay for maintaining an arbitrary namespace of inodes;  There's support within RGW to allow more flexible data streams by policy--such data streams would make it more plausible to try to keep inodes stable;  but could there not genuinely be room for a filesystem which doesn't assume posix semantics here?  For example, it seems like we have little use for helping clients use renamed or deleted streams as scratch space--they can use local filesystems (or overlay filesystems?) for that;  It seems like the big issue is impact on consumers of the renamed files;  Can you imagine a world in which we intentionally sacrifice that for namespace scalability?  That's kind of the space where I've wanted this filesystem to play, up to this point.

**Comment by cmgitdream** [comment]
@mattbenjamin 
for rename desgin, i got it.

do you intend to implement RGW NFS random write & partial write, 
we can use 4k as write unit, pad zero at both head and tail for data less than 4k unit.
for 4M hole whose offset is multiple of 4M, just create an empty rados object.

when reading file, use sparse read when s3 /nfs read file with holes

besides, we can implement truncate as well.

**Comment by cmgitdream** [comment]
@mattbenjamin I think open state timer is more suitable for manage open state,
it is repsonsible for open, read, write, rename, delete in NFSv3

when opening file, add event to open timer,  and extend event expire time when read/write data

**Comment by mattbenjamin** [comment]
@cmgitdream closing per discussion

**Pull request closed without merging**
