### PR TITLE
rbd-mirror: improve status to show additional snapshot details

### PR DESCRIPTION
**Pull request by pkalever**
$ rbd mirror --cluster=site-b image status pool1/test_image
```
test_image:                                                                                                                                                                                                                               
  global_id:   5750c75e-84d1-478b-a086-64c896455abb                                                                                                                                                                                       
  state:       up+replaying                                                                                                                                                                                                               
  description: replaying, {"bytes_per_second":0.0,"bytes_per_snapshot":0.0,"local_snapshot_timestamp":1668063305,"remote_snapshot_timestamp":1668063305,"replay_state":"idle"}                                                            
  service:     admin on localhost.localdomain                                                                                                                                                                                             
  last_update: 2022-11-10 18:44:53                                                                                                                                                                                                        
  peer_sites:                                                                                                                                                                                                                             
    name: 43f2e3d2-8e58-4c4f-8f2a-c205f3627c1c                                                                                                                                                                                            
    state: up+stopped                                                                                                                                                                                                                     
    description: local image is primary                                                                                                                                                                                                   
    last_update: 2022-11-10 18:44:51                                                                                                                                                                                                      
  snapshots:                                                                                                                                                                                                                              
  SNAPID  NAME                                                                                           SIZE    TIMESTAMP                 DETAILS                                                                                        
    ┆ 25  .mirror.non_primary.5750c75e-84d1-478b-a086-64c896455abb.e879fca5-1f08-4711-bdbb-a07c43ac017c  10 MiB  Thu Nov 10 12:25:10 2022  (non-primary peer_uuids:[] 02cabf51-e87e-419f-b767-6c7727db2bd8:23 copied)                     
                                                                                                                                                                                                                                          
```
$ rbd mirror --cluster=site-b image status pool1/test_image --format=json --pretty-format
```
{                                                                                                                                                                                                                                         
    "name": "test_image",                                                                                                                                                                                                                 
    "global_id": "5750c75e-84d1-478b-a086-64c896455abb",                                                                                                                                                                                  
    "state": "up+replaying",                                                                                                                                                                                                              
    "description": "replaying, {\"bytes_per_second\":0.0,\"bytes_per_snapshot\":0.0,\"local_snapshot_timestamp\":1668063305,\"remote_snapshot_timestamp\":1668063305,\"replay_state\":\"idle\"}",                                         
    "daemon_service": {                                                                                                                                                                                                                   
    ┆   "service_id": "4133",                                                                                                                                                                                                             
    ┆   "instance_id": "4135",                                                                                                                                                                                                            
    ┆   "daemon_id": "admin",                                                                                                                                                                                                             
    ┆   "hostname": "localhost.localdomain"                                                                                                                                                                                               
    },                                                                                                                                                                                                                                    
    "last_update": "2022-11-10 18:50:53",                                                                                                                                                                                                 
    "peer_sites": [                                                                                                                                                                                                                       
    ┆   {                                                                                                                                                                                                                                 
    ┆   ┆   "site_name": "43f2e3d2-8e58-4c4f-8f2a-c205f3627c1c",                                                                                                                                                                          
    ┆   ┆   "mirror_uuids": "02cabf51-e87e-419f-b767-6c7727db2bd8",                                                                                                                                                                       
    ┆   ┆   "state": "up+stopped",                                                                                                                                                                                                        
    ┆   ┆   "description": "local image is primary",                                                                                                                                                                                      
    ┆   ┆   "last_update": "2022-11-10 18:51:06"                                                                                                                                                                                          
    ┆   }                                                                                                                                                                                                                                 
    ],                                                                                                                                                                                                                                    
    "snapshots": [                                                                                                                                                                                                                        
    ┆   {                                                                                                                                                                                                                                 
    ┆   ┆   "id": 25,                                                                                                                                                                                                                     
    ┆   ┆   "name": ".mirror.non_primary.5750c75e-84d1-478b-a086-64c896455abb.e879fca5-1f08-4711-bdbb-a07c43ac017c",                                                                                                                      
    ┆   ┆   "size": "10 MiB",                                                                                                                                                                                                             
    ┆   ┆   "timestamp": "Thu Nov 10 12:25:10 2022",                                                                                                                                                                                      
    ┆   ┆   "details": {                                                                                                                                                                                                                  
    ┆   ┆   ┆   "state": "non-primary",                                                                                                                                                                                                   
    ┆   ┆   ┆   "mirror_peer_uuids": [],                                                                                                                                                                                                  
    ┆   ┆   ┆   "complete": true,                                                                                                                                                                                                         
    ┆   ┆   ┆   "primary_mirror_uuid": "02cabf51-e87e-419f-b767-6c7727db2bd8",                                                                                                                                                            
    ┆   ┆   ┆   "primary_snap_id": 23,                                                                                                                                                                                                    
    ┆   ┆   ┆   "last_copied_object_number": 3                                                                                                                                                                                            
    ┆   ┆   }                                                                                                                                                                                                                             
        }                                                                                                                                                                                                                                 
    ]                                                                                                                                                                                                                                     
}                                                                                                                                                                                                                                         
```

Signed-off-by: Prasanna Kumar Kalever \<prasanna.kalever@redhat.com\>


## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [x] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Review by idryomov — COMMENTED** [review]
> $ rbd mirror image snapshot ls pool1/test_image --format json --pretty-format
> 
> ```
> SNAPID  NAME                                                                                       SIZE
>    133  .mirror.primary.4779442d-ac5b-4c19-8abc-b5324dced42b.d19c3e96-9fcc-4f42-9192-fd6d85e0ef72  10 MiB
>    137  .mirror.primary.4779442d-ac5b-4c19-8abc-b5324dced42b.038921bd-5966-48da-91b0-41067e6c32c0  10 MiB
>    140  .mirror.primary.4779442d-ac5b-4c19-8abc-b5324dced42b.18a527ea-31e2-4401-acd4-7bd401822da1  10 MiB
> ```

I'm not sure I follow the use case here.  Mirror snapshots can be listed with `rbd snap ls --all` and a similarly constrained (when compared to `rbd snap ls --all`) output is available as part of `rbd mirror image status`.

**Comment by pkalever** [comment]
> I'm not sure I follow the use case here. Mirror snapshots can be listed with `rbd snap ls --all` and a similarly constrained (when compared to `rbd snap ls --all`) output is available as part of `rbd mirror image status`.

@idryomov 
I tried below and got a failure, should we be fixing it?
```
$ rbd --cluster=site-a snap ls pool1/test_image --namespace=mirror
rbd: namespace 'mirror' does not exist.
```
I was not aware of `--all`, thanks!

BTW, since we have a way to create a mirror snapshot with `rbd mirror snapshot create`, IMHO it also makes sense to have a `list` something like:

```
$ rbd mirror image snapshot create pool1/test_image
$ rbd mirror image snapshot ls pool1/test_image
```
Thoughts?

cc: @chrisphoffman @trociny

**Comment by trociny** [comment]
Although `rbd mirror image snapshot ls` indeed is not necessary as the info may be provided by other ways, still I think I like the idea to have it. It looks useful enough to me and would be more intuitive for users. Though I don't have a strong opinion here.

**Comment by idryomov** [comment]
> > I'm not sure I follow the use case here. Mirror snapshots can be listed with `rbd snap ls --all` and a similarly constrained (when compared to `rbd snap ls --all`) output is available as part of `rbd mirror image status`.
> 
> @idryomov I tried below and got a failure, should we be fixing it?
> 
> ```
> $ rbd --cluster=site-a snap ls pool1/test_image --namespace=mirror
> rbd: namespace 'mirror' does not exist.
> ```

No, `--namespace` refers to RADOS namespaces -- see `rbd namespace create`, `rbd namespace ls`, etc commands.

> 
> I was not aware of `--all`, thanks!
> 
> BTW, since we have a way to create a mirror snapshot with `rbd mirror snapshot create`, IMHO it also makes sense to have a `list` something like:

We don't have `rbd mirror snapshot create`, the command is `rbd mirror image snapshot`.

**Comment by idryomov** [comment]
> Although `rbd mirror image snapshot ls` indeed is not necessary as the info may be provided by other ways, still I think I like the idea to have it. It looks useful enough to me and would be more intuitive for users. Though I don't have a strong opinion here.

The list of mirror snapshots *by itself* doesn't seem like it would be particularly useful to an average user.  Additional context is needed because they wouldn't know that the most recent snapshot being primary means that the image is primary, for example.  I think that was the idea behind including the list of mirror snapshots in `rbd mirror image status` output where (some of) that context is available.  I'd rather improve `rbd mirror image status` in that regard than introduce yet another way to list mirror snapshots.

One such improvement might be to make it list all mirror snapshots instead of just primary mirror snapshots.  Another might be to list more metadata with each snapshot, e.g. include the creation timestamp.

**Review by chrisphoffman — COMMENTED** [review]
It seems redundant having two commands do the same thing.
Such as:
```
    mirror image snapshot             Create RBD mirroring image snapshot.
    mirror image snapshot create      Create RBD mirroring image snapshot.
```
That being said, backwards compatibility is needed and the original one shouldn't be removed. In my opinion, this should be added to something such as `rbd mirror image status`

**Review by idryomov — CHANGES_REQUESTED** [review]
I typed up six or seven comments on various redundancies and inconsistencies in both table and structured outputs before realizing that `rbd snap ls --all` doesn't suffer from any them.  Why not just copy what `rbd snap ls --all` does as previously discussed -- make the output exactly the same, just with non-mirror snapshots omitted?

The only useful tweak I can immediately think of is we can drop `PROTECTED` column here since mirror snapshots can't be protected with `rbd snap protect`.

**Review by chrisphoffman — COMMENTED** [review]
I like the table format. The table format with column labels make reading information easier.

**Comment by pkalever** [comment]
> I typed up six or seven comments on various redundancies and inconsistencies in both table and structured outputs before realizing that `rbd snap ls --all` doesn't suffer from any them. Why not just copy what `rbd snap ls --all` does as previously discussed -- make the output exactly the same, just with non-mirror snapshots omitted?
> 
> The only useful tweak I can immediately think of is we can drop `PROTECTED` column here since mirror snapshots can't be protected with `rbd snap protect`.

@idryomov 

output with ` mirror image status `:
```
SNAPID  NAME                                                                                       SIZE    PRIMARY  DEMOTED  TIMESTAMP                 PEER-UUID
          11  .mirror.primary.219c35d2-4d77-465b-a326-242218a7e869.7d453188-695a-416a-ba71-006aae028893  10 MiB  true     false    Thu Nov  3 16:30:07 2022  41408e34-f709-4742-9d4c-2b9c09963934
          12  .mirror.primary.219c35d2-4d77-465b-a326-242218a7e869.f561768c-d86e-40e9-827c-8af45c974474  10 MiB  true     false    Thu Nov  3 16:30:08 2022  41408e34-f709-4742-9d4c-2b9c09963934
          14  .mirror.primary.219c35d2-4d77-465b-a326-242218a7e869.c7242a60-15f8-48ed-ab81-91e4b147695e  10 MiB  true     false    Thu Nov  3 16:30:09 2022  41408e34-f709-4742-9d4c-2b9c09963934
          17  .mirror.primary.219c35d2-4d77-465b-a326-242218a7e869.ddc76295-3418-4e6a-9907-c4dc03ecabfe  10 MiB  true     false    Thu Nov  3 16:30:11 2022  41408e34-f709-4742-9d4c-2b9c09963934
          20  .mirror.primary.219c35d2-4d77-465b-a326-242218a7e869.d918917b-4c31-40b4-9ea4-5008f1913cda  10 MiB  true     false    Thu Nov  3 16:30:14 2022  41408e34-f709-4742-9d4c-2b9c09963934
```

And the `rbd snap ls --all` output looks like this:
```
SNAPID  NAME   SIZE    PROTECTED  TIMESTAMP                 NAMESPACE
    14  snap1  10 MiB             Wed Nov  9 21:03:15 2022  user     
    15  snap2  10 MiB             Wed Nov  9 21:03:18 2022  user     
```
The only extra fields are PRIMARY|DEMOTED|PEER-UUID, are you saying we don't need this information? not sure if I missed something!

We are showing information under PRIMARY because now we enabled non-primary too.
NOTE: DEMOTED and PEER-UUID in the output were part of the current code, not something that's getting added with this PR.

I thought, having additional details like PRIMARY status instead of NAMESPACE and PROTECTED might be useful, and those were the only diff as compared to `rbd snap ls --all`.

Let me know your thoughts, please. Thanks!

**Comment by trociny** [comment]
I would use json/xml format for full information. For the plain format it is more important to have it readable, so any attempts to "compress" it, like combining  PRIMARY|DEMOTED columns to one (e.g. the column could contain just "P" "D" letters) would look good to me.

Also thinking, may be we should avoid snapshot names in the plain text output. The names do not look like very useful to me, and one could get them in other format output if needed.

**Comment by idryomov** [comment]
> And the `rbd snap ls --all` output looks like this:
> 
> ```
> SNAPID  NAME   SIZE    PROTECTED  TIMESTAMP                 NAMESPACE
>     14  snap1  10 MiB             Wed Nov  9 21:03:15 2022  user     
>     15  snap2  10 MiB             Wed Nov  9 21:03:18 2022  user     
> ```

These are user snapshots whereas we are talking about mirror snapshots.  `rbd snap ls --all` would show them as follows:
```
SNAPID  NAME                                                                                       SIZE     PROTECTED  TIMESTAMP                 NAMESPACE
945729  .mirror.primary.75d57599-4dad-4a36-8f54-15a1baa01a94.00e6a6da-53da-4886-b524-4264195b6f5c  149 GiB             Tue Aug 30 10:30:03 2022  mirror (primary peer_uuids:[609fd734-7dfb-4d8e-addc-9cc3636ab1e6])
945856  .mirror.primary.75d57599-4dad-4a36-8f54-15a1baa01a94.637ca956-a705-4252-99db-d2de94cb5ef5  149 GiB             Tue Aug 30 10:34:10 2022  mirror (demoted peer_uuids:[609fd734-7dfb-4d8e-addc-9cc3636ab1e6])
```

... along with other (user, trash, etc) snapshots if they are present.  What I'm suggesting is to make `rbd mirror image status` output _just_ mirror snapshots exactly like they are output by `rbd snap ls --all` except for PROTECTED column which is useless since mirror snapshots can't be protected.

> 
> The only extra fields are PRIMARY|DEMOTED|PEER-UUID, are you saying we don't need this information? not sure if I missed something!

This information is contained in NAMESPACE column.  Here is the output I initially had in mind:

```
test_image:
  global_id:   219c35d2-4d77-465b-a326-242218a7e869
  state:       up+stopped
  description: local image is primary
  service:     admin on localhost.localdomain
  last_update: 2022-11-03 16:30:09
  peer_sites:
    name: site-b
    state: up+replaying
    description: replaying, {"bytes_per_second":0.0,"bytes_per_snapshot":0.0,"local_snapshot_timestamp":1667473113,"remote_snapshot_timestamp":1667473203,"replay_state":"syncing","syncing_percent":100,"syncing_snapshot_timestamp":1667
03}
    last_update: 2022-11-03 16:30:04
SNAPID  NAME                                                                                       SIZE     TIMESTAMP                 NAMESPACE
945729  .mirror.primary.75d57599-4dad-4a36-8f54-15a1baa01a94.00e6a6da-53da-4886-b524-4264195b6f5c  149 GiB  Tue Aug 30 10:30:03 2022  mirror (primary peer_uuids:[609fd734-7dfb-4d8e-addc-9cc3636ab1e6])
945856  .mirror.primary.75d57599-4dad-4a36-8f54-15a1baa01a94.637ca956-a705-4252-99db-d2de94cb5ef5  149 GiB  Tue Aug 30 10:34:10 2022  mirror (demoted peer_uuids:[609fd734-7dfb-4d8e-addc-9cc3636ab1e6])
```

**Comment by idryomov** [comment]
> I would use json/xml format for full information. For the plain format it is more important to have it readable, so any attempts to "compress" it, like combining PRIMARY|DEMOTED columns to one (e.g. the column could contain just "P" "D" letters) would look good to me.

Do you see a problem with how mirror snapshots are formatted by `rbd snap ls --all`?  That seems very readable to me and since it's already out there, we can just reuse it.  The user would get the output that they are (presumably) already used to with the benefit that non-mirror snapshots would be filtered out automatically.

> 
> Also thinking, may be we should avoid snapshot names in the plain text output. The names do not look like very useful to me, and one could get them in other format output if needed.

I disagree.  Without names matching up mirror snapshots from primary and secondary cluster is pretty hard -- it's what you typically grep for.  `rbd mirror image status` output tends to be one of the first things that users share when they are having an issue and it better contain names ;)

**Comment by trociny** [comment]
> Do you see a problem with how mirror snapshots are formatted by rbd snap ls --all?

I don't see a problem with it :-)

> I disagree. Without names matching up mirror snapshots from primary and secondary cluster is pretty hard -- it's what you typically grep for.

You could display the needed information in some shorter form. If you just need to know if a snapshot from primary or secondary cluster it is not necessary to display almost 100 character snapshot name. And again, the full information could be obtain from json output, and using `jq` instead of grep.

Actually, I don't care much. What I was trying to say was that if there were two ways to display the same information (in plane text mode) I would vote for the way that used less space on the screen.

I think in the past we just did not think much about how to output data. It is not necessary we need to think now (in this PR), but I just wanted to mention it.

E.g. timestamps could use much less space if some other format is used.

Just as a good example for me is `ls -l` or `top` commands output where a lot of useful information is "compressed" in a rather short line.

**Comment by idryomov** [comment]
> You could display the needed information in some shorter form. If you just need to know if a snapshot from primary or secondary cluster it is not necessary to display almost 100 character snapshot name. And again, the full information could be obtain from json output, and using `jq` instead of grep.

True, but the user submitting a tracker ticket wouldn't know to use `--format json`.

> 
> Actually, I don't care much. What I was trying to say was that if there were two ways to display the same information (in plane text mode) I would vote for the way that used less space on the screen.
> 
> I think in the past we just did not think much about how to output data. It is not necessary we need to think now (in this PR), but I just wanted to mention it.
> 
> E.g. timestamps could use much less space if some other format is used.

Yeah, you hit the nail there.  I feel like we have never really strived towards `ls -l`-style output, not just in RBD but also in Ceph in general.  A good(?) example of that is `ceph pg dump` output which is going to uglily wrap no matter how wide one's terminal is or what font size is used.  So for now I would vote for just replicating `rbd snap ls --all` output so that we are at least consistent ;)

**Comment by idryomov** [comment]
> > You could display the needed information in some shorter form. If you just need to know if a snapshot from primary or secondary cluster it is not necessary to display almost 100 character snapshot name. And again, the full information could be obtain from json output, and using `jq` instead of grep.
> 
> True, but the user submitting a tracker ticket wouldn't know to use `--format json`.
> 
> > Actually, I don't care much. What I was trying to say was that if there were two ways to display the same information (in plane text mode) I would vote for the way that used less space on the screen.
> > I think in the past we just did not think much about how to output data. It is not necessary we need to think now (in this PR), but I just wanted to mention it.
> > E.g. timestamps could use much less space if some other format is used.
> 
> Yeah, you hit the nail there. I feel like we have never really strived towards `ls -l`-style output, not just in RBD but also in Ceph in general. A good(?) example of that is `ceph pg dump` output which is going to uglily wrap no matter how wide one's terminal is or what font size is used. So for now I'm voting for just replicating `rbd snap ls --all` output so that we are at least consistent ;)

**Comment by pkalever** [comment]
@idryomov could you please provide your review on this PR?

**Pull request closed without merging**
