### PR TITLE
kickoff v17 quincy

### PR DESCRIPTION
**Pull request by liewegas**

### CODE REVIEW

**Comment by tchaikov** [comment]
@liewegas the run-cli-tests failure should be addressed by #39042.

**Comment by tchaikov** [comment]
jenkins test make check

**Review by sebastian-philipp — APPROVED** [review]
looks reasonable. (Haven't reviewed  OSDMonitor.cc )

**Comment by liewegas** [comment]
retest this please

**Review by jdurgin — APPROVED** [review]
looks good assuming the suite works

**Review by neha-ojha — APPROVED** [review]

**Pull request merged**
