### PR TITLE
rgw: decrement qlen/qactive perf counters on error

### PR DESCRIPTION
**Pull request by mkogan1**
like for example
```
2024-08-21T16:01:59.146+0000 7fffe6348640  0 ERROR: client_io->complete_request() returned Broken pipe
```

Fixes: https://tracker.ceph.com/issues/48358

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Comment by mkogan1** [comment]
executing the reproducer:
```
nice numactl -N 1 -m 1 -- rclone -P copy s3:b04b-000000000000 s3:bkt --transfers=256 --stats-one-line --stats=1s
```

before the fix in this PR, would result in:
```
❯ watch -cd "ls -b ./out/radosgw*asok | xargs -i sh -c 'echo \"F={}\" ; sudo ./bin/ceph --admin-daemon {} perf dump 2>/dev/null | jq -C '\''.rgw.qactive'\'' '"
F=./out/radosgw.8000.asok
177
```

after the fix in this PR:
```
❯ watch -cd "ls -b ./out/radosgw*asok | xargs -i sh -c 'echo \"F={}\" ; sudo ./bin/ceph --admin-daemon {} perf dump 2>/dev/null | jq -C '\''.rgw.qactive'\'' '"
F=./out/radosgw.8000.asok
0
```

**Review by cbodley — APPROVED** [review]

**Comment by mkogan1** [comment]
Note re: https://tracker.ceph.com/issues/48358#note-6

the exception occurs in:
https://github.com/ceph/ceph/blob/64f5bff3791df7656457f2462cf8b6aeb824549f/src/rgw/rgw_process.cc#L435-L440

and not as stated in the tracker: 
https://github.com/ceph/ceph/blob/64f5bff3791df7656457f2462cf8b6aeb824549f/src/rgw/rgw_rest.cc#L644-L648

**Comment by mkogan1** [comment]
jenkins test api

**Comment by mkogan1** [comment]
teuthology results:
https://pulpito.ceph.com/mkogan-2024-08-24_13:27:09-rgw-wip-qlen_qactive--i03-distro-default-smithi/

**Pull request merged**
