### PR TITLE
mgr/dashboard: Fix RBD Image latency issue

### PR DESCRIPTION
**Pull request by epuertat**
By means of caching and lazy loading this change reduces the time
required for calculating metadata for collections of RBD Images.

Overall, this change introduces the following:
- REST API queries now support: server-side pagination, sorting (yet ascending only) and
field selection (filtering/searching is still pending).
- New Attribute and Resource classes for easily creating proxy objects (DTO, thanks @alfonsomthd for pointing this out) for RESTful representations of back-end entities (decoupling REST API from Ceph back-end data model).
- Improved TTL caching (thread-safe).
- Calculation of resource attributes now segregated and
performed on demand and lazily.

Fixes: http://tracker.ceph.com/issues/39140
Signed-off-by: Ernesto Puerta <epuertat@redhat.com>

- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by epuertat** [comment]
please jenkins tell stale bot to stop calling this PR stale. please PR don't listen to stale bot.

**Comment by epuertat** [comment]
stay away, stalebot!

**Comment by epuertat** [comment]
Bad boy, **stalebot**! Drop it!

**Comment by Devp00l** [comment]
@epuertat You have conflicts in some files, you need to rebase.

**Comment by epuertat** [comment]
> @epuertat You have conflicts in some files, you need to rebase.

Thanks for the reminder @Devp00l ! Yes, rather than a simple rebase, this needs a full rewrite :worried:

**Comment by epuertat** [comment]
@stalebot, stay home!

**Comment by nizamial09** [comment]
Looks like a war going on between stalebot and @epuertat

**Comment by epuertat** [comment]
> Looks like a war going on between stalebot and @epuertat

🙈 it is indeed!

**Comment by epuertat** [comment]
Closing in favor of https://github.com/ceph/ceph/pull/39344

**Pull request closed without merging**
