### PR TITLE
rgw: rgw_rados drop deprecated global var

### PR DESCRIPTION
**Pull request by mikulely**

### CODE REVIEW

**Comment by mikulely** [comment]
jenkins retest this please

**Comment by mikulely** [comment]
jenkins retest this please

**Comment by mikulely** [comment]
@tchaikov unrelated test case failed, plz take a look: 

```
99% tests passed, 1 tests failed out of 171

Total Test time (real) = 2008.29 sec

The following tests FAILED:
	148 - osd-scrub-repair.sh (Failed)
```

Thx.

**Comment by mikulely** [comment]
@tchaikov @cbodley  Jenkins passed after rebase master.

**Comment by cbodley** [comment]
passed rgw suite: http://pulpito.ceph.com/cbodley-2017-05-10_19:55:34-rgw-wip-cbodley-testing---basic-mira/

**Pull request merged**
