### PR TITLE
mon: mgr/osd beacon timeout under high mon_command load

### PR DESCRIPTION
**Pull request by maydaycc**
When mons handle a large amount of mon_commands, osdbeacon|mgrbeacon sent to peon mon
will wait for a long time with many forward(log) messages in leader mon's dispatch queue.
We should give forward(osdbeacon)|forward(mgrbeacon) high priority since they have
queued up in peon mon's dispatch queue with normal priority.

Fixes: https://tracker.ceph.com/issues/54617
Signed-off-by: wencong wan wanwc@chinatelecom.cn

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by maydaycc** [comment]
@sseshasa please have a look

**Review by tchaikov — APPROVED** [review]

**Review by sseshasa — APPROVED** [review]

**Comment by ljflores** [comment]
http://pulpito.front.sepia.ceph.com/yuriw-2022-03-22_00:42:53-rados-wip-yuri7-testing-2022-03-21-1529-distro-default-smithi/

Failures, unrelated:
    https://tracker.ceph.com/issues/53680
    https://tracker.ceph.com/issues/52320
    https://tracker.ceph.com/issues/52657

**Comment by ljflores** [comment]
jenkins test api

**Comment by ljflores** [comment]
jenkins test make check arm64

**Comment by yuriw** [comment]
jenkins test api

**Comment by yuriw** [comment]
jenkins test api

**Comment by ljflores** [comment]
jenkins retest this please

**Comment by ljflores** [comment]
jenkins test api

**Comment by ljflores** [comment]
jenkins test make check arm64

**Comment by neha-ojha** [comment]
Adding DNM, since there is more discussion required based on https://github.com/ceph/ceph/pull/45521#issuecomment-1075118761

**Comment by rzarzynski** [comment]
@sseshasa: would find some time to take a look on that?

**Comment by sseshasa** [comment]
> @tchaikov @sseshasa I found that the MLog messages generated by mon have high priority, even if we changed the forward(osdbeacon|mgrbeacon) messages' priority, they still need to queue up with many forward(log) messages, can we give these MLog messages normal priority?

@maydaycc I checked the history for LogMonitor and couldn't find a specific reason for the MLog messages being allocated the high priority. @neha-ojha do you know? The MLog constructor doesn't assign the priority but goes with the msgr allocated priority of CEPH_MSG_PRIO_HIGH during mon bring-up. Unless there's a specific reason for the high priority, we could allocate the default priority for the LogMonitor messages to CEPH_MSG_PRIO_DEFAULT.

**Comment by sseshasa** [comment]
> @maydaycc I checked the history for LogMonitor and couldn't find a specific reason for the MLog messages being allocated the high priority. @neha-ojha do you know? The MLog constructor doesn't assign the priority but goes with the msgr allocated priority of CEPH_MSG_PRIO_HIGH during mon bring-up. Unless there's a specific reason for the high priority, we could allocate the default priority for the LogMonitor messages to CEPH_MSG_PRIO_DEFAULT.

@neha-ojha @tchaikov Can you please take a look at the latest change and based on my comments above suggest if lowering the priority of MLog messages is the right way forward? Thanks!

**Comment by maydaycc** [comment]
@neha-ojha @tchaikov Would you please take a look at this problem?

**Comment by tchaikov** [comment]
> When mons handle a large amount of mon_commands

i'd like to understand the root cause of the "large amount of mon_commands" first. if they are MLog, then we should stop sending them in large bulk.

**Comment by maydaycc** [comment]
> > When mons handle a large amount of mon_commands
> 
> i'd like to understand the root cause of the "large amount of mon_commands" first. if they are MLog, then we should stop sending them in large bulk.

nova、cinder、ceph-exporter、mgr prometheus，we encountered this problem after expanding the openstack and ceph cluster. Our Ceph cluster have 5000+ osd ,version is 14.2.8，openstack cluster have 600+ compute node.

**Comment by maydaycc** [comment]
> > When mons handle a large amount of mon_commands
> 
> i'd like to understand the root cause of the "large amount of mon_commands" first. if they are MLog, then we should stop sending them in large bulk.

mlog mlog mlog

**Pull request closed without merging**
