### PR TITLE
mimic: ceph_detect_init: Add support for ALT Linux

### PR DESCRIPTION
**Pull request by mrandybu**
Support Alt Linux distribution added.

Signed-off-by: Andrey Bychkov <mrdrew@altlinux.org>

### CODE REVIEW

**Comment by mrandybu** [comment]
@smithfarm ping

**Comment by smithfarm** [comment]
@yuriw Could you please run a `ceph-disk` suite on this one?

**Comment by yuriw** [comment]
[wip-yuri3-testing-2019-04-29-1935-mimic](https://trello.com/c/1OdZ5zIb/598-wip-yuri3-testing-2019-04-29-1935-mimic)

**Comment by yuriw** [comment]
[wip-yuri3-testing-2019-04-30-1543-mimic](https://trello.com/c/MkrC4MVX/599-wip-yuri3-testing-2019-04-30-1543-mimic)

**Comment by yuriw** [comment]
passed rados and ready for merge
@smithfarm

**Comment by smithfarm** [comment]
> passed rados and ready for merge

@yuriw Please run a **ceph-disk** suite on this. Rados is nice, but this one needs ceph-disk.

**Comment by yuriw** [comment]
[wip-yuri-testing-2019-07-08-2007-mimic](https://trello.com/c/QAzBp49o/659-wip-yuri-testing-2019-07-08-2007-mimic)

**Comment by yuriw** [comment]
@smithfarm pls approve and merge it's passed tests

**Comment by yuriw** [comment]
[wip-yuri4-testing-2019-07-23-1633-mimic](https://trello.com/c/G8TDc8rz/672-wip-yuri4-testing-2019-07-23-1633-mimic)

**Comment by smithfarm** [comment]
@yuriw Can you point me to the ceph-disk run (not rados) where this PR is included?

**Pull request merged**
