### PR TITLE
rgw: check object storage_class when check_disk_state

### PR DESCRIPTION
**Pull request by Huber-ming**
fix: https://tracker.ceph.com/issues/55618

Signed-off-by: Huber-ming <zhangsm01@inspur.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/master/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by Huber-ming** [comment]
jenkins test windows

**Comment by Huber-ming** [comment]
@cbodley why windows tests allways  failed?

**Comment by Huber-ming** [comment]
jenkins test windows

**Comment by cbodley** [comment]
> @cbodley why windows tests allways failed?

dunno, maybe a networking issue. but don't worry about it, it's not required for merge

**Review by cbodley — APPROVED** [review]

**Comment by Huber-ming** [comment]
jenkins retest this please

**Comment by Huber-ming** [comment]
@djgalloway new commit merge to main? not master?

**Comment by cbodley** [comment]
@Huber-ming that's right, we've switched to `main` as the development branch

**Comment by cbodley** [comment]
pass qa with rerun:
https://pulpito.ceph.com/cbodley-2022-06-07_20:15:13-rgw-wip-cbodley-testing-distro-default-smithi/
https://pulpito.ceph.com/cbodley-2022-06-08_13:53:34-rgw-wip-cbodley-testing-distro-default-smithi/

**Pull request merged**
