### PR TITLE
hammer: tools: fix race condition in seq/rand bench (part 2)

### PR DESCRIPTION
**Pull request by asheplyakov**
http://tracker.ceph.com/issues/14873

### CODE REVIEW

**Comment by dachary** [comment]
@asheplyakov could you please explain in detail in the commit message why and how https://github.com/ceph/ceph/commit/a619b621b0a7c670eeaf163d9e2b742d13c9f517 creates a problem ?

**Comment by asheplyakov** [comment]
@dachary does it look good enough now?

**Comment by dachary** [comment]
The message helps a lot. Your patch is correct, IMHO. The first hunk (moving the Lock()) is also correct but belongs to another backport (for https://github.com/ceph/ceph/commit/0c8faf7c9982c564002771c3a41362a833ace9bb), for the sake of clarity, could you please either cherry-pick -x this commit or not include the hunk ?

The commit message of your fix should read something like the
following (note that the title of the commit is the same as the
original commit, which will presumably help when retracing this
problem down the line):

hammer: tools: fix race condition in seq/rand bench (part 2)

Commit c2c6d02591519dfd15ddcb397ac440322a964deb which is intended to
cherry-pick 9bcf5f065c4ed4b10d8f98961d1f99493bcdc9b8 incorrectly resolved
a conflict by adding code where it should have been removed. The incorrect
conflict resolution can been displayed with

   commit=c2c6d02591519dfd15ddcb397ac440322a964deb
   picked_from=9bcf5f065c4ed4b10d8f98961d1f99493bcdc9b8
   diff -u --ignore-matching-lines '^[^+-]' <(git show $picked_from) <(git show $commit)

--- /dev/fd/63    2016-03-03 14:09:51.354329129 +0700
+++ /dev/fd/62    2016-03-03 14:09:51.358329122 +0700
@@ -76,20 +79,18 @@
      ++data.in_flight;
 -    if (!no_verify) {
 -      snprintf(data.object_contents, data.object_size, "I'm the %16dth object!", current_index);
--      lock.Unlock();
+       lock.Unlock();
 -      if (memcmp(data.object_contents, cur_contents->c_str(), data.object_size) != 0) {
 -        cerr << name[slot] << " is not correct!" << std::endl;
 -        ++errors;
 -      }
--    } else {
--        lock.Unlock();
--    }
--
-+    lock.Unlock();
-     name[slot] = newName;
-   }
- 
-@@ -789,11 +791,14 @@ int ObjBencher::rand_read_bench(int seconds_to_run, int num_objects, int concurr
++    if (memcmp(data.object_contents, cur_contents->c_str(), data.object_size) != 0) {
++      cerr << name[slot] << " is not correct!" << std::endl;
++      ++errors;
+     } else {
+       lock.Unlock();
+     }
+@@ -776,11 +785,14 @@ int ObjBencher::rand_read_bench(int seconds_to_run, int num_objects, int concurr
        }
        lc.cond.Wait(lock);
      }

http://tracker.ceph.com/issues/14873 Fixes: #14873

**Comment by asheplyakov** [comment]
@dachary I've tried cherry-picking  0c8faf7, however it had some non-trivial merge conflicts. Resolving them is not that difficult, however there are more subtle differences. For instance,
https://github.com/ceph/ceph/blob/hammer/src/common/obj_bencher.cc#L162

> int object_size = op_size;

I think fixing the sloppy comparison [1] is less error prone than cherry-picking the above patch and figuring out subtle code changes between hammer and master. 

[1] that is,
- memcmp(data.object_contents, cur_contents->c_str(), data.object_size) != 0
+ (cur_contents->length() != data.object_size) || (memcmp(data.object_contents, cur_contents->c_str(), data.object_size) != 0)

Also the problem solved by 0c8faf7 can be easily worked around, and there's no way to solve #14873 (other than patching and rebuilding the tools). Therefore I propose to merge this PR as is, and fix the comparison by a different patch. What do you think?

**Comment by branch-predictor** [comment]
@asheplyakov I agree. The issue with seq bench was caused by cherry-pick that went wrong, causing extra code to be left out where it shouldn't be, and I haven't noticed that when I issued original backport PR. Your patch fixes this issue.
@dachary I agree too, but I think backporting 0c8faf7, considering the amount of changes, is not worth it. @asheplyakov patch gets the job done.
Another thing we can do, is to issue *another* PR just for the lock thing, since this is all we need right now from 0c8faf7. What do you think?

**Comment by dachary** [comment]
@asheplyakov @branch-predictor I think issuing  another PR just for the lock thing from 0c8faf7 is indeed the right thing to do. It could be cherry-picked -x 0c8faf7 and trimmed down just to the lock, with a clear explanation as to why that was done this way in the Conflict section of the commit message. Since it does not seem relevant to backport the rest of the 0c8faf7 commit, I think it's ok to explain that it will never be in hammer.

**Comment by asheplyakov** [comment]
@dachary @branch-predictor I've submitted a new PR which moves the lock to the right place: #7896 , skipped the corresponding hunk from this patch, and updated the commit message.

**Comment by branch-predictor** [comment]
LGTM

**Pull request merged**
