### PR TITLE
jewel: RHEL 7.3 Selinux denials at OSD start

### PR DESCRIPTION
**Pull request by shinobu-x**
http://tracker.ceph.com/issues/21053

### CODE REVIEW

**Comment by shinobu-x** [comment]
test this please

**Comment by shinobu-x** [comment]
test this please

**Comment by smithfarm** [comment]
test this please

**Comment by smithfarm** [comment]
This PR passed a rados integration run at http://tracker.ceph.com/issues/21742#note-14 with two bugs reproducing:

    http://tracker.ceph.com/issues/23006
    http://tracker.ceph.com/issues/23007

Since neither of the bugs is SElinux-related, I'll merge this now.

**Comment by smithfarm** [comment]
On second though, @b-ranto please take a look and merge if it looks OK.

**Pull request merged**
