### PR TITLE
rgw: filter shoud't have tags when dm_expiration=ture

### PR DESCRIPTION
**Pull request by Huber-ming**
When specifying the ExpiredObjectDeleteMarker Lifecycle(dm_expiration=ture) action, the rule cannot specify a tag-based filter. look at: [https://docs.aws.amazon.com/AmazonS3/latest/dev/lifecycle-configuration-examples.html#lifecycle-config-conceptual-ex7](https://docs.aws.amazon.com/AmazonS3/latest/dev/lifecycle-configuration-examples.html#lifecycle-config-conceptual-ex7)  second **Node**

```
s3cmd setlifecycle encry1 s3://shengming
```
where bucket name with _shengming_ ,  xml in _encry1_ :
```
<?xml version="1.0"?>
<LifecycleConfiguration>
  <Rule>
    <ID>rule1</ID>
    <Filter>
	<And>
            <Tag>
               <Key>key1</Key>
               <Value>value1</Value>
            </Tag>
            <Tag>
               <Key>key2</Key>
               <Value>value2</Value>
            </Tag>
          </And>
    </Filter>
    <Status>Enabled</Status>
    <Expiration>
           <ExpiredObjectDeleteMarker>true</ExpiredObjectDeleteMarker>
    </Expiration>
  </Rule>
</LifecycleConfiguration>
```
**Before modification：**
```
rados -p cn-north-3a.rgw.meta -N root getxattr .bucket.meta.shengming:c2f69fa0-94f3-4e1b-bd00-496dd14c8714.28600632.1 user.rgw.lc -> lc
./ceph-14.2.8/build/bin/ceph-dencoder type RGWLifecycleConfiguration import lc decode dump_json

{
    _prefix_map element_
    "rule_map": [
        {
            "id": "rule1",
            "rule": {
                "id": "rule1",
                "prefix": "",
                "status": "Enabled",
                "expiration": {},
                "noncur_expiration": {},
                "mp_expiration": {},
                "filter": {
                    "prefix": "",
                    "obj_tags": {
                        "tag_map": {
                            "key": "key1",
                            "value": "value1"
                        },
                        "tag_map": {
                            "key": "key2",
                            "value": "value2"
                        }
                    }
                },
                "dm_expiration": true
            }
        }
    ]
}

```
**After modification**
```
s3cmd setlifecycle encry1 s3://shengming
ERROR: S3 error: 400 (InvalidArgument)
```
Signed-off-by: Shengming Zhang <zhangsm01@inspur.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by mattbenjamin** [comment]
Hi @Huber-ming, where does the supplied reference specify that tags are not permitted in dm-expiration rules?  Is this instead something that you confirmed AWS does not accept in your own testing?

**Comment by Huber-ming** [comment]
> Hi @Huber-ming, where does the supplied reference specify that tags are not permitted in dm-expiration rules? Is this instead something that you confirmed AWS does not accept in your own testing?

@mattbenjamin The **Note** above title **Example 8: Lifecycle configuration to abort multipart uploads** specify that tags are not permitted in dm-expiration rules, the  **Note** above title **How Amazon S3 calculates how long an object has been noncurrent** in https://docs.aws.amazon.com/AmazonS3/latest/dev/intro-lifecycle-rules.html aslo specify this rule restriction.

**Comment by Huber-ming** [comment]
jenkins test signed

**Comment by Huber-ming** [comment]
@mattbenjamin

**Pull request closed without merging**
