### PR TITLE
qa/suites/rados: move thrash-old-clients under cephadm

### PR DESCRIPTION
**Pull request by neha-ojha**
Since it uses cephadm, at the moment it makes sense to run it as a part of
rados/cephadm. This gives better test coverage for developers and has exposed
bugs such as https://tracker.ceph.com/issues/45421 and
https://tracker.ceph.com/issues/47709. We can always restructure this later.

Signed-off-by: Neha Ojha <nojha@redhat.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by neha-ojha** [comment]
Testing it here: https://pulpito.ceph.com/nojha-2020-09-30_19:37:06-rados:cephadm-master-distro-basic-smithi/

**Comment by neha-ojha** [comment]
> i'd suggest avoid repeating the tests in rados suite.

makes sense, done!

**Review by tchaikov — APPROVED** [review]

**Comment by neha-ojha** [comment]
https://pulpito.ceph.com/nojha-2020-10-02_16:28:59-rados:cephadm-master-distro-basic-smithi/

**Comment by neha-ojha** [comment]
@ceph/orchestrators any objections?

**Comment by sebastian-philipp** [comment]
one issue though: this suite drawfs the rest of the cephadm suite. I need a way to somehow filter this properly and only schedule 10  runs from this suite or so.

**Pull request merged**
