### PR TITLE
jewel: Decode errors on backtrace will crash MDS

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/18462

### CODE REVIEW

**Comment by jcsp** [comment]
The test in this one had a dependency on this earlier test commit:
```
commit 5f77f09b019b607b84e6a8f89ce19065383ca108
Author: John Spray <john.spray@redhat.com>
Date:   Thu Oct 20 11:49:08 2016 +0100

    tasks/cephfs: add TestForwardScrub.test_backtrace_repair
    
    Signed-off-by: John Spray <john.spray@redhat.com>
```

That was part of the PR to add backtrace repairs during forward scrub, which is not a bugfix so I'd skip backporting it.  I think the thing to do here is to copy-paste the _write_data_xattr function from that PR into a separate commit in this PR.

**Comment by smithfarm** [comment]
@jcsp Done, but I guess it doesnt warrant a separate commit - better would be to squash the commit into the qa/tasks cherry-pick and write a note about it in Conflicts:, do you agree?

**Comment by smithfarm** [comment]
@jcsp Oh, now I see you specifically said you wanted a separate commit. So, here it is.

**Comment by jcsp** [comment]
Tested here: http://pulpito.ceph.com/jspray-2017-01-24_21:53:01-fs-wip-jcsp-backports-20170124-distro-basic-smithi/

**Pull request merged**
