### PR TITLE
rgw: multisite bucket index trace points

### PR DESCRIPTION
**Pull request by zenomri**
This PR comes to add trace points of multisite bucket index sync

As part of the PutObj Op, we want to trace the syncing of the bucket index changes, and add the other zone syncing as a sub trace of the original upload operation into the primary zone
this changes also add the OSD spans of the object write in the secondary zone, using the changes done in #47457 (commits squashed into b23ba6a873d6fdfd91e7e5361effadbde3c993ce)

Example of how the trace looks like in Jaeger GUI:

image

image

some basic information that we can see there – how long it took the secondary zone to start the sync, object and bucket name, and host_id of the rgw
## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [x] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by yuvalif** [comment]
@zenomri can you please specify which of the commits here are new and not part of https://github.com/ceph/ceph/pull/47457 ?

**Comment by zenomri** [comment]
> @zenomri can you please specify which of the commits here are new and not part of #47457 ?

b23ba6a873d6fdfd91e7e5361effadbde3c993ce
i squashed the other PR commits into this one.

**Comment by yuvalif** [comment]
this PR is waiting on https://github.com/ceph/ceph/pull/52114

**Comment by yuvalif** [comment]
closing in favor of: https://github.com/ceph/ceph/pull/52707
note that the above does not include 
* end2end tracing, which is done here: https://github.com/ceph/ceph/pull/52114
* other fixes are done in: 
  *  https://github.com/ceph/ceph/pull/52392
  * https://github.com/ceph/ceph/pull/52393

**Pull request closed without merging**
