### PR TITLE
luminous: rbd-nbd can deadlock in logging thread

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/23913

### CODE REVIEW

**Comment by yuriw** [comment]
[wip-yuri3-testing-2018-04-30-2145-luminous](https://trello.com/c/AuFS1qjo/302-wip-yuri3-testing-2018-04-30-2145-luminous)

**Comment by yuriw** [comment]
[wip-yuri-testing-2018-05-08-1950-luminous](https://trello.com/c/jzXuWwpp/309-wip-yuri-testing-2018-05-08-1950-luminous)

**Comment by dillaman** [comment]
Since this will now include changes to common code, it should be run through rados, rgw, cephfs, rbd suites

**Comment by dillaman** [comment]
@yuriw  ... this PR is still not ready for testing

**Comment by smithfarm** [comment]
@dillaman Done, thanks.

**Comment by yuriw** [comment]
@smithfarm @dillaman pls review test results https://trello.com/c/FMIU468q (see below if inaccessible)

some failures related to mirror issues we had.

http://pulpito.ceph.com/yuriw-2018-05-11_21:43:30-rados-wip-yuri-testing-2018-05-11-1522-luminous-distro-basic-smithi

http://pulpito.ceph.com/yuriw-2018-05-11_21:47:23-rbd-wip-yuri-testing-2018-05-11-1522-luminous-distro-basic-smithi

http://pulpito.ceph.com/yuriw-2018-05-11_21:48:38-rgw-wip-yuri-testing-2018-05-11-1522-luminous-distro-basic-smithi

http://pulpito.ceph.com/yuriw-2018-05-11_21:50:45-fs-wip-yuri-testing-2018-05-11-1522-luminous-distro-basic-smithi

http://pulpito.ceph.com/yuriw-2018-05-11_21:52:25-kcephfs-wip-yuri-testing-2018-05-11-1522-luminous-testing-basic-smithi

**Comment by yuriw** [comment]
https://trello.com/c/FMIU468q

**Pull request merged**
