### PR TITLE
mgr/dashboard: add support for NFSv3 exports

### PR DESCRIPTION
**Pull request by avanthakkar**
By default now we have enabled support for both v3,v4 protocols for NFS exports
Screenshot from 2024-03-08 16-19-54

[Screencast from 2024-03-12 14-31-17.webm](https://github.com/ceph/ceph/assets/23611106/ed8761a7-5615-4e10-8cea-c34db2741633)

Fixes: https://tracker.ceph.com/issues/64812
Signed-off-by: Avan Thakkar <athakkar@redhat.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [x] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [x] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Comment by avanthakkar** [comment]
jenkins test make check

**Comment by avanthakkar** [comment]
jenkins test api

**Comment by cloudbehl** [comment]
@avanthakkar can you attach recording to it and show how it works when you unselect both of them. Also what happen when you start with v3 and then edit and change it to v4?

**Comment by avanthakkar** [comment]
> @avanthakkar can you attach recording to it and show how it works when you unselect both of them. Also what happen when you start with v3 and then edit and change it to v4?

I've attached screencast in PR description

**Comment by avanthakkar** [comment]
jenkins test dashboard

**Comment by afreen23** [comment]
Hey @avanthakkar , I have tested this out.

And following working fine:
- by default always nfsv3 and nfsv4 enabled
- disabling both does not allow to proceed
- I was able to edit the export if its created from cli (tried with cephfs export)
- I was able to create export for both rgw and cephfs

What I was unable to do:
- choosing only nfsv3 for any storage backend gives me error 
image
image


let me know if I missed anything, thanks !

**Comment by avanthakkar** [comment]
> Hey @avanthakkar , I have tested this out.
> 
> And following working fine:
> 
>     * by default always nfsv3 and nfsv4 enabled
> 
>     * disabling both does not allow to proceed
> 
>     * I was able to edit the export if its created from cli (tried with cephfs export)
> 
>     * I was able to create export for both rgw and cephfs
> 
> 
> What I was unable to do:
> 
>     * choosing only nfsv3 for any storage backend gives me error
>       image
>       image
> 
> 
> let me know if I missed anything, thanks !

Thank you for testing!  It seems that selecting   only  nfsv3 was a issue, I added a fix for it. Basically pseudo path was dependent only on v4 field so it caused the issue. You can do testing again, it shouldn't be reproducible anymore.

**Comment by cloudbehl** [comment]
jenkins test dashboard

**Comment by cloudbehl** [comment]
jenkins test api

**Comment by avanthakkar** [comment]
jenkins test api

**Comment by avanthakkar** [comment]
jenkins test dashboard

**Comment by afreen23** [comment]
> Thank you for testing! It seems that selecting only nfsv3 was a issue, I added a fix for it. Basically pseudo path was dependent only on v4 field so it caused the issue. You can do testing again, it shouldn't be reproducible anymore.

Indeed, this works fine:

* by default always nfsv3 and nfsv4 enabled

* disabling both does not allow to proceed

* I was able to edit the export if its created from cli (tried with cephfs export)

* I was able to create export for both rgw and cephfs from UI- both nfs v3 and nfs v4 working fine

**Review by afreen23 — APPROVED** [review]

**Review by cloudbehl — APPROVED** [review]

**Pull request merged**
