### PR TITLE
debian: build against libSSL1.0 since civetweb needs it

### PR DESCRIPTION
**Pull request by mcv21**
The version of civetweb in Luminous is incompatible with libSSL1.1,
which is the default libSSL in e.g. Ubuntu Bionic. This means that if
you build ceph on Bionic, you get a civetweb that links against
libssl1.1 that then fails to run, producing logs like

2019-02-01 14:09:45.651071 7f3dd9065000  0 civetweb: 0x564bbd31cf40: load_dll: libcrypto.so.1.1: cannot find CRYPTO_num_locks

It's fixed in newer civetwebs, but for Luminous the answer is to
specify build-dependency on libssl1.0; we also then have to build
against libcurl4-gnutls-dev since libcurl4-openssl-dev depends on
libssl1.1-dev.

Fixes: https://tracker.ceph.com/issues/20696
Signed-off-by: Matthew Vernon <mv3@sanger.ac.uk>

- [X] References tracker ticket
- [x] Updates documentation if necessary

### CODE REVIEW

**Comment by mcv21** [comment]
The build failure log suggests to me this is a problem in Jenkins, nothing to do with my PR:
https://jenkins.ceph.com/job/ceph-pull-requests/523/console

**Comment by tchaikov** [comment]
retest this please

**Comment by tchaikov** [comment]
retest this please

**Comment by mcv21** [comment]
retest this please

**Comment by mcv21** [comment]
I worked out the issue - on Xenial, there isn't libssl1.0-dev, instead that's libssl-dev (which on Bionic is libssl1.1), so we needed a versioned alternative to use libssl-dev where that's a 1.0 version, and then libssl1.0-dev once libssl-dev is 1.1

**Comment by cbodley** [comment]
pointing out https://github.com/ceph/ceph/pull/20635, where @mdw-at-linuxbox mentions "significant performance hits" with gnutls

**Comment by mcv21** [comment]
@cbodley the alternative is no TLS at all with Luminous/Bionic, unfortunately. We're using this on our test cluster ATM (production will move there in due course).

**Comment by mcv21** [comment]
Ah, actually, I can do better -  by making the libcurl4 a dependency with alternatives, then (at least on the boxes I tried it on here), you get libcurl4-openssl-dev on Xenial and libcurl4-gnutls-dev only on Bionic (where it's necessary because libcurl4-openssl-dev is compiled against libssl1.1 and so incompatible).

**Comment by mcv21** [comment]
retest this please

**Comment by mcv21** [comment]
@cbodley @mdw-at-linuxbox does this address your concerns?

**Comment by mdw-at-linuxbox** [comment]
Getting it to not go to decidedly worse behavior on xenial is certainly an improvement.  I suppose going from not building at all on bionic to building badly is an improvement.  Still.  ew.

I know several people who will definitely be sad to see bionic not working as well as xenial.

**Comment by mcv21** [comment]
@mdw-at-linuxbox working at all on Bionic (for Luminous) is an improvement, though?

**Comment by cbodley** [comment]
@mcv21 we're actually pulling up the luminous civetweb (see https://github.com/ceph/ceph/pull/27982) to match what's in mimic. will that resolve the issue?

**Comment by mcv21** [comment]
@cbodley That'd be grand!
[I didn't attempt that myself, because I figured it'd be too invasive for a stable release]

**Comment by cbodley** [comment]
@mcv21 https://github.com/ceph/ceph/pull/27982 merged to luminous, do you think this can be closed?

**Comment by mcv21** [comment]
Yes, thanks :-)

**Pull request closed without merging**
