### PR TITLE
Fixed typos

### PR DESCRIPTION
**Pull request by suckowbiz**
I just used this file as basis for another work and came across the typos which are fixed now.

### CODE REVIEW

**Comment by dachary** [comment]
Nice catch :-) Could you please format your commit message like so:
<pre>
doc: fix message typos in systemd

Signed-off-by: Name Surname &lt;mail@address.com>
</pre>

**Comment by suckowbiz** [comment]
doc: fix message typos in systemd

Signed-off-by: Tobias Suckow <tobias@suckow.biz>

**Comment by suckowbiz** [comment]
How can I do this?

Loic Dachary <notifications@github.com> schrieb am Mo., 23. Nov. 2015 um
13:26 Uhr:

> Nice catch :-) Could you please format your commit message like so:
>
> doc: fix message typos in systemd
>
> Signed-off-by: Name Surname <mail@address.com>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ceph/ceph/pull/6679#issuecomment-158918865>.
>
-- 
Freundliche Grüße
Tobias Suckow

**Comment by dachary** [comment]
You need to use git commit --amend to modify the commit message and then git push --force to replace the existing commit.

**Comment by suckowbiz** [comment]
I applied this but do not see any change.

**Comment by suckowbiz** [comment]
Applied :).

**Comment by dachary** [comment]
Yeah !

**Pull request merged**
