### PR TITLE
rgw: aws4 subdomain calling bugfix

### PR DESCRIPTION
**Pull request by jmunhoz**
Fixes: http://tracker.ceph.com/issues/15369

Signed-off-by: Javier M. Mellid <jmunhoz@igalia.com>

### CODE REVIEW

**Comment by robbat2** [comment]
@jmunhoz:
Fix confirmed, thanks! Please merge.

**Comment by robbat2** [comment]
Oh, one quick thought, throw in a comment line that describes what the request_uri_aws4 field does (specifically that it shouldn't be mangled as it's used for hashing).

**Comment by liewegas** [comment]
fwiw http://pulpito.ceph.com/sage-2016-04-06_06:37:14-rgw-wip-sage-testing---basic-smithi/

**Comment by jmunhoz** [comment]
@robbat2 comment added.

**Pull request merged**
