### PR TITLE
mds: fix CDir::merge() for mds_debug_auth_pins

### PR DESCRIPTION
**Pull request by ukernel**
Fixes: http://tracker.ceph.com/issues/19946
Signed-off-by: "Yan, Zheng" <zyan@redhat.com>

### CODE REVIEW

**Comment by fullerdj** [comment]
In finish_old_fragment, we assert that STATE_STICKY is set (it is normally set in CInode::add_dirfrag). Should we remove the assertion or set it in CDir::split?

**Comment by fullerdj** [comment]
On the merge side, CDir::merge calls close_dirfrag, which is unhappy having the extra ref added by prepare_new_fragment.

**Comment by ukernel** [comment]
CDir::finish_old_fragment does not assert STATE_STICKY. depends on STATE_STICKY is set, it assert dirfrag's ref is 0 or 1.

**Comment by fullerdj** [comment]
I see what you mean, thanks.

**Comment by fullerdj** [comment]
@jcsp this looks good to me, can we merge it?

**Pull request merged**
