### PR TITLE
mgr/dashboard: Hide table action input field if limit=0

### PR DESCRIPTION
**Pull request by votdev**
Fixes: https://tracker.ceph.com/issues/46901

Signed-off-by: Volker Theile <vtheile@suse.com>

## Checklist
- [x] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by avanthakkar** [comment]
jenkins test dashboard

**Comment by callithea** [comment]
jenkins test dashboard

**Comment by tspmelo** [comment]
the value of the `limit` is only configured when creating the table, so it will never change based on the user behavior.
We already remove other buttons if that feature is not enabled for that table, so we should do the same here.

**Comment by epuertat** [comment]
ok, thanks @tspmelo !

**Pull request merged**
