### PR TITLE
mgr/Zabbix: Various fixes to Zabbix module

### PR DESCRIPTION
**Pull request by wido**
This pull request contains multiple improvements and fixes for the Zabbix Manager Module:

- Use fsid of Ceph to identify with Zabbix
- Configuration improvements of the module to make it run more smoothly
- Logging fixes

### CODE REVIEW

**Comment by wido** [comment]
The reason I added 'bugfix' as a label is that without this fix the Zabbix module doesn't start after setting zabbix_host and restarting the manager.

**Comment by wido** [comment]
@liewegas Ah I see, you mean where I dropped the RuntimeErrors. I can add those back easily.

Just need to know what the convention is.

**Comment by jcsp** [comment]
The PR with the error handling is https://github.com/ceph/ceph/pull/19235

It introduces a behaviour where exceptions from serve() or __init__() cause a health check to fail + get reported.  However, it also prevents the module running until the mgr restarts, so it's mean for fatal/unexpected errors.

Modules are also able to raise their own health checks with MgrModule.set_health_checks, so maybe that's the right thing to do for runtime-fixable conditions like a bad configuration option?

**Comment by wido** [comment]
@jcsp: Ok, I didn't know that. I'll take a look at those instead of logging a error.

**Comment by jcsp** [comment]
The set_health_checks bits are already in master, so I think it would be neat to try using those to raise a friendly health message to tell the user to set their zabbix config when it's missing/invalid.

For anything really fatal, just raise the exception and it'll be handled more gracefully when #19235 merges.

**Comment by wido** [comment]
@jcsp I've brought back the RunTimeError exceptions again.

How does it look now?

**Comment by jcsp** [comment]
We may want to revisit the runtimeerrors in the future, but clearly it's not a regression for this PR so :+1:

**Comment by wido** [comment]
I see that the docs fail to build, but that's due to a 404 during the test itself.

**Comment by wido** [comment]
I pushed again to trigger the checks. They succeeded now.

**Comment by tchaikov** [comment]
- http://pulpito.ceph.com/kchai-2017-12-23_05:58:55-rados-wip-kefu-testing-2017-12-23-1241-distro-basic-mira/
- http://pulpito.ceph.com/kchai-2017-12-24_02:41:14-rados-wip-kefu-testing-2017-12-23-1241-distro-basic-mira/

**Pull request merged**
