### PR TITLE
build/ops: add missing libcap-ng-dev build dependency

### PR DESCRIPTION
**Pull request by smithfarm**
Fixes: https://tracker.ceph.com/issues/42032
Signed-off-by: Nathan Cutler <ncutler@suse.com>

### CODE REVIEW

**Comment by smithfarm** [comment]
@ivancich Do you know which PR/commit introduced this new build dependency, and which cmake options trigger the need for it?

**Comment by tchaikov** [comment]
i think eae01275134ea550367a09e6adb084ffc9f4bd46 is able to address the failure.

**Comment by smithfarm** [comment]
@tchaikov Thanks!

**Comment by smithfarm** [comment]
Ah, I see the issue now. It's a bug in https://github.com/ceph/ceph/commit/eae01275134ea550367a09e6adb084ffc9f4bd46

**Comment by smithfarm** [comment]
nope, not

**Pull request closed without merging**
