### PR TITLE
qa/tests: added nautilus clients to the mix

### PR DESCRIPTION
**Pull request by yuriw**
Signed-off-by: Yuri Weinstein <yweinste@redhat.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test docs`
- `jenkins render docs`

</details>

### CODE REVIEW

**Comment by yuriw** [comment]
@batrick fixed some of you comments, probably not all

**Comment by yuriw** [comment]
just trying http://pulpito.front.sepia.ceph.com:80/yuriw-2019-08-09_16:25:52-fs:upgrade:featureful_client-master-distro-basic-smithi/

**Comment by batrick** [comment]
changes look sane to me

**Comment by yuriw** [comment]
@batrick I am letting you merge it if you feel it's ok, or we can test/modify more

**Comment by batrick** [comment]
I will do more testing.

**Comment by batrick** [comment]
http://pulpito.ceph.com/pdonnell-2019-09-11_16:54:51-fs:upgrade-master-distro-basic-smithi/
http://pulpito.ceph.com/pdonnell-2019-09-11_05:53:25-fs:upgrade-wip-pdonnell-testing-20190910.213701-distro-basic-smithi/

**Comment by yuriw** [comment]
rebased and trying again
http://pulpito.front.sepia.ceph.com:80/yuriw-2019-10-21_19:51:06-fs:upgrade:featureful_client-master-distro-basic-smithi/

**Pull request closed without merging**
