### PR TITLE
mon/MonMap: fix unconditional failure for init_with_hosts

### PR DESCRIPTION
**Pull request by batrick**
Fixes: https://tracker.ceph.com/issues/47951
Signed-off-by: Patrick Donnelly <pdonnell@redhat.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by tchaikov** [comment]
@batrick could you drop the ceph-object-corpus change from this PR?

**Comment by batrick** [comment]
Oops, thanks @tchaikov .

**Review by tchaikov — APPROVED** [review]

**Comment by wido** [comment]
This fixes: https://github.com/ceph/ceph/commit/2f075704073ff80f94c70cf79516028d2754ae4f

**Review by dillaman — APPROVED** [review]
lgtm -- can we get a quick unit test to resolve `ceph.io` (or something) by hostname to prevent this from getting broken in the future?

**Comment by wido** [comment]
> lgtm -- can we get a quick unit test to resolve `ceph.io` (or something) by hostname to prevent this from getting broken in the future?

That would be great. I know many clusters out there using Round Robin DNS entries for Monitor discovery.

**Review by wido — APPROVED** [review]

**Review by neha-ojha — APPROVED** [review]

**Comment by batrick** [comment]
I'm working on adding a test.

**Comment by batrick** [comment]
> lgtm -- can we get a quick unit test to resolve `ceph.io` (or something) by hostname to prevent this from getting broken in the future?

Done!

**Comment by batrick** [comment]
@rjfd I added to your MonMap.cc tests but found out they weren't actually getting built or run. I fixed some compiler errors but the tests SIGSEGV during `SetUp`. You might want to have another look at those after this gets merged?

**Comment by batrick** [comment]
````
        Start 139: unittest_mon_monmap
        Start 140: unittest_mon_pgmap
        Start 141: unittest_mon_montypes
        Start 142: unittest_mon_election
119/209 Test #126: unittest_erasure_code_shec ................   Passed    6.61 sec
120/209 Test #141: unittest_mon_montypes .....................   Passed    0.81 sec
121/209 Test #140: unittest_mon_pgmap ........................   Passed    1.22 sec
122/209 Test #139: unittest_mon_monmap .......................   Passed    1.52 sec
123/209 Test #133: unittest_journal ..........................   Passed    5.91 sec
````

**Comment by tchaikov** [comment]
- https://pulpito.ceph.com/kchai-2020-10-23_10:21:03-rados-wip-kefu-testing-2020-10-23-1631-distro-basic-smithi/
- https://pulpito.ceph.com/kchai-2020-10-24_10:41:09-rados-wip-kefu-testing-2020-10-24-1306-distro-basic-smithi/
- https://pulpito.ceph.com/kchai-2020-10-24_16:10:41-rados-wip-kefu-testing-2020-10-24-1306-distro-basic-smithi/

failures tracked by

- https://tracker.ceph.com/issues/46323

**Comment by smithfarm** [comment]
@batrick Is the nautilus backport of this fix something we should fast-track?

**Comment by batrick** [comment]
> @batrick Is the nautilus backport of this fix something we should fast-track?

Yes, I think so.

**Comment by batrick** [comment]
https://pulpito.ceph.com/?branch=wip-pdonnell-testing-20201024.032205

failures unrelated.

**Comment by smithfarm** [comment]
@batrick Nautilus backport is up

**Pull request merged**
