### PR TITLE
hammer: man: document listwatchers cmd in rados manpage

### PR DESCRIPTION
**Pull request by dachary**
http://tracker.ceph.com/issues/14441

### CODE REVIEW

**Comment by ktdreyer** [comment]
Thank you! Do you want to change the in-tree nroff source as well? The patch I'm using in RH Ceph Storage downstream is
```
diff --git a/man/rados.8 b/man/rados.8
index 94b67c9..e9f2d03 100644
--- a/man/rados.8
+++ b/man/rados.8
@@ -132,6 +132,9 @@ Write object name to the cluster with contents from infile.
 .B \fBrm\fP \fIname\fP
 Remove object name.
 .TP
+.B \fBlistwatchers\fP \fIname\fP
+List the watchers of object name.
+.TP
 .B \fBls\fP \fIoutfile\fP
 List objects in given pool and write to outfile.
 .TP
```

**Comment by tchaikov** [comment]
@dachary thanks for backporting this change, and i agree with @ktdreyer , unlike jewel, we still put the rendered man page in the git repo in hammer.

**Comment by dachary** [comment]
@ktdreyer would you be so kind as to open a pull request with the backport you have ? It will make it easier later on. And if you have backports stashed that resolve other pending backports, by all means ;-)

**Comment by tchaikov** [comment]
i created a pull request to include @ktdreyer's backport and the upstream change at #7434.

**Comment by ktdreyer** [comment]
Thanks @dachary and @tchaikov !

**Pull request closed without merging**
