### PR TITLE
os/filestore: print out the error if do_read_entry() fails

### PR DESCRIPTION
**Pull request by tchaikov**
Signed-off-by: Kefu Chai <kchai@redhat.com>

### CODE REVIEW

**Comment by tchaikov** [comment]
@shinobu-x

**Comment by shinobu-x** [comment]
@tchaikov

**Comment by yuriw** [comment]
[wip-yuri2-testing-2017-10-18-1626](https://trello.com/c/Umf2zVud/181-wip-yuri2-testing-2017-10-18-1626)

**Comment by tchaikov** [comment]
- http://pulpito.ceph.com/kchai-2017-10-19_01:36:34-rados-wip-kefu-testing-2017-10-18-2318-distro-basic-mira/
- http://pulpito.ceph.com/kchai-2017-10-18_16:55:07-rados-wip-kefu-testing-2017-10-18-2318-distro-basic-smithi/

**Pull request merged**
