### PR TITLE
test/osd/safe-to-destroy.sh: Add checks for the test

### PR DESCRIPTION
**Pull request by NitzanMordhai**
The test script is not detecting the build env vars and not checking 
return code from start osds\mon\mgr.

This will add those checks to prevent false results from the test.

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Comment by athanatos** [comment]
How does this specifically address the linked bug?  Is there an environment variable that causes it to wait correctly?

**Comment by NitzanMordhai** [comment]
> How does this specifically address the linked bug? Is there an environment variable that causes it to wait correctly?

@athanatos from the log that was sent in the tracker:
`cat build/Testing/Temporary/LastTest.log
  /bzy-dev/slicer-src/qa/standalone/ceph-helpers.sh:688: run_osd:  return 1
  /bzy-dev/slicer-src/src/test/osd/safe-to-destroy.sh:35: TEST_safe_to_destroy:  echo 'ceph status======11111'
  ceph status======11111`

we can see that at least one of the osd didn't start, we also just got the first status, before the flush_pg_stats.
i asked in the tracker to get also full log, that PR also add return 1 to fail the test if one of the osd\mon\mgr didn't started

**Comment by athanatos** [comment]
@NitzanMordhai Ok, so the || return 1 would cause the test to fail sooner in the event that there's an error in those calls.  How does  ```source $(dirname $0)/../detect-build-env-vars.sh``` factor in?

The bug states that adding a sleep 60 solves the problem.  That suggests that the root cause of that bug report isn't that the osd failed to start, but rather that it started slowly.  It's still not obvious to me how this PR solves that problem.

**Comment by NitzanMordhai** [comment]
> @NitzanMordhai Ok, so the || return 1 would cause the test to fail sooner in the event that there's an error in those calls. How does `source $(dirname $0)/../detect-build-env-vars.sh` factor in?

@athanatos that is the reason i added the note in the bug: https://tracker.ceph.com/issues/64657#note-4
without the full logs, we won't be able to identify why the osd started slowly. just another clarification here: "ceph status======11111" will check the status after creating 4 osds, we return 1 after the osd didn't start after timeout of 300 seconds.
i think that my PR headline is making that confusion that build env vars will fix the error.

**Comment by NitzanMordhai** [comment]
@athanatos looks like the user changed the codebase and removed the wait_for_osd, https://tracker.ceph.com/issues/64657#note-5 so that PR is just to handle errors in that test

**Comment by athanatos** [comment]
Ok, if this doesn't fix that bug (since it apparently doesn't need to be fixed), remove the Fixes: line from both the commit message and the PR description.

**Review by athanatos — APPROVED** [review]
LGTM once the Fixes: lines are removed (as long as the test passes)

**Comment by NitzanMordhai** [comment]
> Ok, if this doesn't fix that bug (since it apparently doesn't need to be fixed), remove the Fixes: line from both the commit message and the PR description.

done, thanks for reviewing it and the comments

**Comment by NitzanMordhai** [comment]
jenkins test make check

**Comment by ljflores** [comment]
Rados approved: https://tracker.ceph.com/projects/rados/wiki/MAIN#httpstrackercephcomissues65126

**Pull request merged**
