### PR TITLE
qa/workunits/rbd: switch rbd-mirror workunits to bash

### PR DESCRIPTION
**Pull request by idryomov**
By making use of here strings in commit ea3a567f7f03 ("qa/workunits: make wait_for_status_in_pool_dir() reentrant") we grew a dependency on bash.

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [x] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Comment by idryomov** [comment]
A follow-up for https://github.com/ceph/ceph/pull/54802, backport is to be appended to https://github.com/ceph/ceph/pull/55763, https://github.com/ceph/ceph/pull/55762 and https://github.com/ceph/ceph/pull/55761.

**Review by trociny — APPROVED** [review]

**Comment by idryomov** [comment]
jenkins test make check

**Review by ajarr — APPROVED** [review]

**Comment by ajarr** [comment]
> A follow-up for #54802, backport is to be appended to #55763, #55762 and #55761.

So the plan is that once this fix is merged in main, we want to append this commit to  #55763, #55762 and #55761.

#55763 has been tested. Should we hold off on merging it? Append this commit to that PR, and then request Yuri to redo the testing?

Looks like #55762 is being tested right now. Similarly, should we request Yuri to redo the testing after we append the commit to that PR?

**Comment by idryomov** [comment]
> #55763 has been tested. Should we hold off on merging it? Append this commit to that PR, and then request Yuri to redo the testing?

I'm waiting to hear from @yuriw, but it seems like #55763 hasn't actually been tested.  Something went wrong with the process and only RADOS suite appears to have been run on it and some other quincy PRs that Yuri blessed for merging earlier today.

**Comment by idryomov** [comment]
... so I'd say go ahead and append this fixup to all three backport PRs.

**Pull request merged**
