### PR TITLE
 luminous: osd: "sudo cp /var/lib/ceph/osd/ceph-0/fsid ..." fails

### PR DESCRIPTION
**Pull request by shinobu-x**
http://tracker.ceph.com/issues/22509

### CODE REVIEW

**Comment by yuriw** [comment]
@theanalyst pls add it to our queue as it fails some runs

**Comment by yuriw** [comment]
@shinobu-x @liewegas Is it core?

**Comment by liewegas** [comment]
core, and/or ceph-disk/ceph-volume

**Comment by smithfarm** [comment]
jenkins test docs please

**Comment by yuriw** [comment]
[wip-yuri2-testing-2018-01-29-1733-luminous](https://trello.com/c/Hi2l9Gd8/246-wip-yuri2-testing-2018-01-29-1733-luminous)

**Pull request merged**
