### PR TITLE
octopus: cmake: define BOOST_ASIO_USE_TS_EXECUTOR_AS_DEFAULT globaly

### PR DESCRIPTION
**Pull request by tchaikov**
these changes are backported because i am observing the same FTBFS we saw on the pacific branch. but only once, after rerunning the "make check", the build completed.

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Review by idryomov — COMMENTED** [review]
It would be nice to state the reason for backporting.  I don't think octopus build got similarly broken, or did it?

**Comment by tchaikov** [comment]
@idryomov hi IIya, thanks for your review. i only saw once occurrence of the FTBFS, but it was cured by rerolling the dice. that's why i backported the change.

**Comment by idryomov** [comment]
Has anyone tracked down the root cause?  @neha-ojha mentioned that (some of?) the builders got upgraded, but no specifics.

**Comment by tchaikov** [comment]
@idryomov i will, if this problem surfaces again. but presumably, the root cause might be related to the prebuild boost packages. `install-deps.sh` *should* uninstall the prebuilt packages if their version is different from the required one.

https://github.com/ceph/ceph/blob/1976598f645ad1935a5e428219713b8856796d83/install-deps.sh#L156-L168

but probably, it failed to do so sometimes.

**Review by jdurgin — APPROVED** [review]

**Review by cbodley — APPROVED** [review]

**Comment by tchaikov** [comment]
- https://pulpito.ceph.com/kchai-2021-04-12_02:35:25-rados-wip-kefu-octopus-testing-2021-04-11-2349-distro-basic-gibba/
- https://pulpito.ceph.com/kchai-2021-04-12_13:55:39-rados-wip-kefu-octopus-testing-2021-04-11-2349-distro-basic-smithi/

i think most of cephadm test failures are caused by https://tracker.ceph.com/issues/49293

**Pull request merged**
