### PR TITLE
pacific: cmake: re-enable TCMalloc and allocator related cleanups

### PR DESCRIPTION
**Pull request by pponnuvel**
backport tracker: https://tracker.ceph.com/issues/55541

---

backport of https://github.com/ceph/ceph/pull/46103
parent tracker: https://tracker.ceph.com/issues/55519

this backport was staged using ceph-backport.sh version 16.0.0.6848
find the latest version at https://github.com/ceph/ceph/blob/main/src/script/ceph-backport.sh

### CODE REVIEW

**Comment by pponnuvel** [comment]
jenkins test api

**Comment by pponnuvel** [comment]
@tchaikov Can you please take a look at this? I am hoping to get this into the possibly-last Pacific point release.

**Comment by pponnuvel** [comment]
Ping.

Can this be looked at again?

**Review by ljflores — DISMISSED** [review]

**Review by ljflores — COMMENTED** [review]
@pponnuvel I built this patch and it is causing a build problem:

https://jenkins.ceph.com/job/ceph-dev-new-build/ARCH=x86_64,AVAILABLE_ARCH=x86_64,AVAILABLE_DIST=bionic,DIST=bionic,MACHINE_SIZE=gigantic/75706/consoleFull#3154186727641bc0b-bacc-4481-8290-0cf28df0ce68
```
-- Found LZ4: /usr/lib/x86_64-linux-gnu/liblz4.so (found suitable version "1.7.1", minimum required is "1.7") 
CMake Error at /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find gperftools: Found unsuitable version "2.5", but required is
  at least "2.6.2" (found /usr/include)
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:376 (_FPHSA_FAILURE_MESSAGE)
  cmake/modules/Findgperftools.cmake:52 (find_package_handle_standard_args)
  CMakeLists.txt:346 (find_package)
```

PTAL when you can. As Pacific is going EOL soon, we maybe should not include this.

**Comment by pponnuvel** [comment]
@ljflores The gperftools version on Ubuntu/Bionic is 2.5, so obviously this fails to meet the minimum required version.
Looking at this requirment, this was introduced to be able to use `aligned_alloc` (https://github.com/ceph/ceph/pull/28093). So removing this requirement (gperftools >= 2.6.2) isn't straightforward.

Not using tcmalloc at all on Bionic defeats the purpose of this backport as the intention was to link with tcmalloc for performance reasons.

I originally proposed this backport in light of https://bugs.launchpad.net/ubuntu/+source/ceph/+bug/2016845.
However, we have since linked with tcmalloc in our (Ubuntu's) Pacific release anyway. Needing gperftools >= 2.6.2 wasn't 
an issue for us since we don't ship Pacific on Ubuntu/Bionic.

So I agree this isn't a critical issue for us in Ubuntu and can be closed since Pacific is going EOL anyway.
Besides the reason for this backport is a performance, not any bug critical for functionality. Hence I am OK to close this PR as you suggested.

Perhaps it's time to drop Ubuntu/Bionic (18.04) from https://docs.ceph.com/en/quincy/start/os-recommendations/#platforms so that Ubuntu/Bionic (18.04) need not be tested/built going forward. But that's a different discussion.

**Pull request closed without merging**
