### PR TITLE
jewel: cephfs: normalize file open flags internally used by cephfs

### PR DESCRIPTION
**Pull request by jan--f**
http://tracker.ceph.com/issues/19846

### CODE REVIEW

**Comment by smithfarm** [comment]
@jan--f: Please move the commit resolution down below the "(cherry-picked from . . .)" line.

**Comment by batrick** [comment]
I may have found a bug in the original code. Please delay merging this.

**Comment by batrick** [comment]
http://tracker.ceph.com/issues/19896

**Comment by batrick** [comment]
False alarm, please proceed.

**Comment by jcsp** [comment]
@jan--f could you cherry pick the https://github.com/ceph/ceph/pull/15018 test fix into this PR please?

**Comment by smithfarm** [comment]
Jenkins re-test this please

**Comment by smithfarm** [comment]
@jcsp This passed a fs suite at http://pulpito.front.sepia.ceph.com/smithfarm-2017-06-22_11:51:56-fs-wip-jewel-backports-distro-basic-smithi/ - one job failed ("Test failure: test_remote_update_write (tasks.cephfs.test_quota.TestQuota)")

**Pull request merged**
