### PR TITLE
quincy: pybind/mgr: fixup after upgrading tox versions

### PR DESCRIPTION
**Pull request by adk3798**
We upgraded the tox version on the Jenkins machines and some changes are needed in order for make check to pass now.

Backport of #49322, #49321, partially #49359 (included some unnecessary things I've removed here and will revert in main later)

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by adk3798** [comment]
api test failed with
```
/tmp/tmp.kdEuveZDqZ/venv/lib/python3.10/site-packages/requests/__init__.py:102: RequestsDependencyWarning: urllib3 (1.26.13) or chardet (5.1.0)/charset_normalizer (2.0.12) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({})/charset_normalizer ({}) doesn't match a supported "
Cannot find device "ceph-brx"
2022-12-09 18:49:08,761.761 INFO:__main__:Creating cluster with 1 MDS daemons
2022-12-09 18:49:08,761.761 INFO:__main__:
tearing down the cluster...
rm: cannot remove '/var/run/ceph': Permission denied
Using guessed paths /home/jenkins-build/build/workspace/ceph-api/build/lib/ ['/home/jenkins-build/build/workspace/ceph-api/qa', '/home/jenkins-build/build/workspace/ceph-api/build/lib/cython_modules/lib.3', '/home/jenkins-build/build/workspace/ceph-api/src/pybind']
Traceback (most recent call last):
  File "/home/jenkins-build/build/workspace/ceph-api/build/../qa/tasks/vstart_runner.py", line 1527, in <module>
    exec_test()
  File "/home/jenkins-build/build/workspace/ceph-api/build/../qa/tasks/vstart_runner.py", line 1362, in exec_test
    teardown_cluster()
  File "/home/jenkins-build/build/workspace/ceph-api/build/../qa/tasks/vstart_runner.py", line 1094, in teardown_cluster
    remote.run(args=[os.path.join(SRC_PREFIX, "stop.sh")], timeout=60)
  File "/home/jenkins-build/build/workspace/ceph-api/build/../qa/tasks/vstart_runner.py", line 410, in run
    return self._do_run(**kwargs)
  File "/home/jenkins-build/build/workspace/ceph-api/build/../qa/tasks/vstart_runner.py", line 480, in _do_run
    proc.wait()
  File "/home/jenkins-build/build/workspace/ceph-api/build/../qa/tasks/vstart_runner.py", line 221, in wait
    raise CommandFailedError(self.args, self.exitstatus)
teuthology.exceptions.CommandFailedError: Command failed with status 1: ['../src/stop.sh']
find: ‘/home/jenkins-build/build/workspace/ceph-api/build/out’: No such file or directory
```
not sure if related yet. Going to rerun.

**Comment by adk3798** [comment]
jenkins test api

**Comment by adk3798** [comment]
> tried dropping the commits that drop the py3 and py37 testing as was done on the pacific backport. Will see if it causes failures here or not.

forgot the py37 commit had the mypy parsing fixes. Definitely need that. Looks like removing py3 testing from qa tox is also necessary due to tests failing with
```
>   from IPy import IP
E   ModuleNotFoundError: No module named 'IPy'

tasks/cephfs/mount.py:12: ModuleNotFoundError
```

**Comment by ljflores** [comment]
jenkins test dashboard

**Comment by ljflores** [comment]
jenkins test dashboard cephadm e2e

**Comment by ljflores** [comment]
jenkins test dashboard cephadm e2e

**Comment by ljflores** [comment]
@nizamial09 @avanthakkar can either of you take a look at the dashboard aspects of this PR? The dashboard tests are failing, but I'm not sure if it's related.

We need this PR to unblock Quincy PRs.

**Comment by avanthakkar** [comment]
> @nizamial09 @avanthakkar can either of you take a look at the dashboard aspects of this PR? The dashboard tests are failing, but I'm not sure if it's related.
> 
> We need this PR to unblock Quincy PRs.

These failures doesn't seem related, some similar failures in master branch too. The fix for this failing tests is WIP, will try to raise a PR ASAP.

**Review by nizamial09 — APPROVED** [review]

**Comment by nizamial09** [comment]
As @avanthakkar said the dashboard failures are unrelated, let's go with this one and unblock the quincy branch. We can take care of the dashboard e2e in a separate PR.

**Comment by ljflores** [comment]
Thanks @nizamial09 @avanthakkar and @adk3798 !!

**Pull request merged**
