### PR TITLE
common/LogEntry: Reintroduce human readable log level for clog messages

### PR DESCRIPTION
**Pull request by pdvian**
In {fmt} v9, fmt::formatter<> is not getting defined automatically for
the clog_type with operator<<, we need to define it explictly.
Allow fmt::formatter<> to print clog prio using {fmt}.

Fixes: https://tracker.ceph.com/issues/58436

Signed-off-by: Prashant D <pdhange@redhat.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by pdvian** [comment]
@tchaikov Would it be wise to implement our own struct fmt::formatter<clog_type> instead of providing a formatter inherited from ostream_formatter here ?

**Comment by tchaikov** [comment]
@pdvian hi Prashant, I think it depends on if we still use operator<< to print this type. Please note, if we have both of them if the tree is compiled with fmtlib< 9.0.

**Comment by pdvian** [comment]
> @pdvian hi Prashant, I think it depends on if we are still using operator<< to print this type. Please note, if we have both of them if the tree is compiled with fmtlib< 9.0. Personally, I'd avoid replicate the formatting logic in two places unless one of the implementations is very readable/ simple.

Thanks. It makes sense.

**Comment by pdvian** [comment]
@tchaikov Hi Kefu, Can you review this PR please ?

**Comment by pdvian** [comment]
Re-opening this PR as we are encountering this issue in teuthology test runs. e.g https://pulpito.ceph.com/yuriw-2024-01-10_19:18:18-rados-wip-pdhange-testing-distro-default-smithi/7512554/

**Comment by pdvian** [comment]
Re-opening this PR as we are encountering this issue in teuthology test runs.

**Comment by pdvian** [comment]
Re-opening this PR as we are encountering this issue in teuthology tests. e.g https://pulpito.ceph.com/yuriw-2024-01-10_19:18:18-rados-wip-pdhange-testing-distro-default-smithi/7512554/

**Comment by pdvian** [comment]
@rzarzynski @NitzanMordhai Kindly review this PR.

**Comment by sseshasa** [comment]
Hi @pdvian, Another PR: https://github.com/ceph/ceph/pull/55455 was recently raised and reviewed to fix this. PTAL.

**Review by NitzanMordhai — APPROVED** [review]
LGTM

**Review by rzarzynski — APPROVED** [review]

**Comment by pdvian** [comment]
> Hi @pdvian, Another PR: #55455 was recently raised and reviewed to fix this. PTAL.

Thanks Sridhar. Your PR looks good to me. I am fine to close this PR in favor of your PR.

@rzarzynski @NitzanMordhai Sridhar has another PR #55455 ready to merge for the same issue. Should we go ahead with str helper function instead of defining formatter for clog_type ?

**Comment by sseshasa** [comment]
> Thanks Sridhar. Your PR looks good to me. I am fine to close this PR in favor of your PR.
> 
> @rzarzynski @NitzanMordhai Sridhar has another PR #55455 ready to merge for the same issue. Should we go ahead with str helper function instead of defining formatter for clog_type ?

@pdvian @rzarzynski Can both the fixes co-exist? This is only if there's a possibility that fmt version can be lower than `90000`. Otherwise, I am fine with whatever you think is the best fix.

**Comment by ronen-fr** [comment]
@sseshasa , @rzarzynski , @tchaikov 
> @pdvian @rzarzynski Can both the fixes co-exist? This is only if there's a possibility that fmt version can be lower than `90000`. Otherwise, I am fine with whatever you think is the best fix.

Aren't we are passed this point in Squid?

**Comment by pdvian** [comment]
> > Thanks Sridhar. Your PR looks good to me. I am fine to close this PR in favor of your PR.
> > @rzarzynski @NitzanMordhai Sridhar has another PR #55455 ready to merge for the same issue. Should we go ahead with str helper function instead of defining formatter for clog_type ?
> 
> @pdvian @rzarzynski Can both the fixes co-exist? This is only if there's a possibility that fmt version can be lower than `90000`. Otherwise, I am fine with whatever you think is the best fix.

Yes, both fixes can co-exist. @rzarzynski What do you think ?

**Comment by pdvian** [comment]
> @sseshasa , @rzarzynski , @tchaikov
> 
> > @pdvian @rzarzynski Can both the fixes co-exist? This is only if there's a possibility that fmt version can be lower than `90000`. Otherwise, I am fine with whatever you think is the best fix.
> 
> Aren't we are passed this point in Squid?

The fmt submodule in ceph repo is having FMT_VERSION 90100 so we need to define fmt::formatter for clog_type explicitly.

**Comment by sseshasa** [comment]
**Teuthology test result**

https://pulpito.ceph.com/yuriw-2024-03-08_16:20:46-rados-wip-yuri4-testing-2024-03-05-0854-distro-default-smithi/.

There are no related failures. For the full report please see: https://tracker.ceph.com/projects/rados/wiki/MAIN#httpstrellocomcQFtoIRXE1971-wip-yuri4-testing-2024-03-05-0854

This is RADOS approved.

**Review by sseshasa — APPROVED** [review]
LGTM

**Pull request merged**
