### PR TITLE
osd: Don't evict even when preemption has restarted with smaller chunk

### PR DESCRIPTION
**Pull request by dzafman**
Fixes: https://tracker.ceph.com/issues/24045

Work in progress

### CODE REVIEW

**Comment by dzafman** [comment]
Test:
http://pulpito.ceph.com/dzafman-2018-05-08_16:32:58-rados:thrash-wip-24045-distro-basic-smithi
http://pulpito.ceph.com/dzafman-2018-05-08_15:32:10-rados:thrash-wip-24045-distro-basic-smithi

1 unrelated failure and 6 dead jobs, no core files

**Comment by tchaikov** [comment]
http://pulpito.ceph.com/kchai-2018-05-10_02:52:31-rados-wip-24045-on-kefu-distro-basic-mira/ also looks good.

**Comment by dzafman** [comment]
@tchaikov The 5 jobs you ran strangely didn't include the exact one that failed with this problem.

rados/thrash run 438 passed, 1 dead infrastructure and 1 still running:
http://pulpito.ceph.com/dzafman-2018-05-09_17:22:39-rados:thrash-wip-24045-distro-basic-smithi/

**Comment by dzafman** [comment]
I probably fixed the eviction race, but there is still a promote race which my assert caught.

```
0> 2018-05-10 17:56:17.756 7f5d54bc3700 -1 /build/ceph-13.1.0-77-g01c000f/src/osd/PG.cc: In function 'bool PG::write_blocked_by_scrub(const hobject_t&)' thread 7f5d54bc3700 time 2018-05-10 17:56:17.759108
/build/ceph-13.1.0-77-g01c000f/src/osd/PG.cc: 5222: FAILED assert(!soid.is_snap())

 ceph version 13.1.0-77-g01c000f (01c000f54599cab91e8e2524fd1f533f759603a8) mimic (dev)
 1: (ceph::__ceph_assert_fail(char const*, char const*, int, char const*)+0x102) [0x7f5d78e54202]
 2: (()+0x2e43c7) [0x7f5d78e543c7]
 3: (PG::write_blocked_by_scrub(hobject_t const&)+0x85) [0x55c627a382d5]
 4: (PrimaryLogPG::promote_object(std::shared_ptr<ObjectContext>, hobject_t const&, object_locator_t const&, boost::intrusive_ptr<OpRequest>, std::shared_ptr<ObjectContext>*)+0x93) [0x55c627b1d3d3]
 5: (PrimaryLogPG::maybe_handle_cache_detail(boost::intrusive_ptr<OpRequest>, bool, std::shared_ptr<ObjectContext>, int, hobject_t, bool, bool, std::shared_ptr<ObjectContext>*)+0xd9e) [0x55c627b1ef7e]
 6: (PrimaryLogPG::_rollback_to(PrimaryLogPG::OpContext*, ceph_osd_op&)+0x23a) [0x55c627b3b56a]
 7: (PrimaryLogPG::do_osd_ops(PrimaryLogPG::OpContext*, std::vector<OSDOp, std::allocator<OSDOp> >&)+0x3351) [0x55c627b44ee1]
 8: (PrimaryLogPG::prepare_transaction(PrimaryLogPG::OpContext*)+0x9f) [0x55c627b5365f]
 9: (PrimaryLogPG::execute_ctx(PrimaryLogPG::OpContext*)+0x38b) [0x55c627b53e5b]
 10: (PrimaryLogPG::do_op(boost::intrusive_ptr<OpRequest>&)+0x361c) [0x55c627b5885c]
 11: (PrimaryLogPG::do_request(boost::intrusive_ptr<OpRequest>&, ThreadPool::TPHandle&)+0xcc3) [0x55c627b5ca73]
 12: (OSD::dequeue_op(boost::intrusive_ptr<PG>, boost::intrusive_ptr<OpRequest>, ThreadPool::TPHandle&)+0x1b8) [0x55c6279b70c8]
 13: (PGOpItem::run(OSD*, OSDShard*, boost::intrusive_ptr<PG>&, ThreadPool::TPHandle&)+0x62) [0x55c627c2fd72]
 14: (OSD::ShardedOpWQ::_process(unsigned int, ceph::heartbeat_handle_d*)+0x590) [0x55c6279d6820]
 15: (ShardedThreadPool::shardedthreadpool_worker(unsigned int)+0x46e) [0x7f5d78e5913e]
 16: (ShardedThreadPool::WorkThreadSharded::entry()+0x10) [0x7f5d78e5b1c0]
 17: (()+0x76ba) [0x7f5d778fd6ba]
 18: (clone()+0x6d) [0x7f5d7712641d]
```

**Comment by dzafman** [comment]
@liewegas  Now that I think about this, I think this must be a latent defect.  In the past it was always possible that if a snapshot happen to be in the scrub window and scrub_can_preempt == false it would  block the write.  The last commit just made it much easier to block the write at least for snapshots.

```
2018-05-11 06:15:08.990 7f9e4131e700 20 osd.0 op_wq(3) _process 3.3 to_process <> waiting <> waiting_peering {}
2018-05-11 06:15:08.990 7f9e4131e700 20 osd.0 op_wq(3) _process OpQueueItem(3.3 PGOpItem(op=osd_op(client.4428.0:2987 3.3 3:cd983545:::smithi16216178-470:head [rollback 30] snapc 34=[34,33,30,2d] ondisk+write+known_if_redirected e89) v8) prio 63 cost 0 e89) queued
2018-05-11 06:15:08.990 7f9e4131e700 20 osd.0 op_wq(3) _process 3.3 to_process <OpQueueItem(3.3 PGOpItem(op=osd_op(client.4428.0:2987 3.3 3:cd983545:::smithi16216178-470:head [rollback 30] snapc 34=[34,33,30,2d] ondisk+write+known_if_redirected e89) v8) prio 63 cost 0 e89)> waiting <> waiting_peering {}
2018-05-11 06:15:08.990 7f9e4131e700 20 osd.0 op_wq(3) _process OpQueueItem(3.3 PGOpItem(op=osd_op(client.4428.0:2987 3.3 3:cd983545:::smithi16216178-470:head [rollback 30] snapc 34=[34,33,30,2d] ondisk+write+known_if_redirected e89) v8) prio 63 cost 0 e89) pg 0x55cf11ad2000
2018-05-11 06:15:08.990 7f9e4131e700 10 osd.0 89 dequeue_op 0x55cf14bad880 prio 63 cost 0 latency 0.044058 osd_op(client.4428.0:2987 3.3 3:cd983545:::smithi16216178-470:head [rollback 30] snapc 34=[34,33,30,2d] ondisk+write+known_if_redirected e89) v8 pg pg[3.3( v 89'337 (0'0,89'337] local-lis/les=59/60 n=47 ec=20/20 lis/c 59/59 les/c/f 60/60/0 59/59/59) [0,6] r=0 lpr=59 luod=89'336 crt=89'337 lcod 89'334 mlcod 89'334 active+clean ps=[16~1,1c~1,26~1,2e~1]]
2018-05-11 06:15:08.990 7f9e4131e700 10 osd.0 pg_epoch: 89 pg[3.3( v 89'337 (0'0,89'337] local-lis/les=59/60 n=47 ec=20/20 lis/c 59/59 les/c/f 60/60/0 59/59/59) [0,6] r=0 lpr=59 luod=89'336 crt=89'337 lcod 89'334 mlcod 89'334 active+clean ps=[16~1,1c~1,26~1,2e~1]] _handle_message: 0x55cf14bad880
2018-05-11 06:15:08.990 7f9e4131e700 20 osd.0 pg_epoch: 89 pg[3.3( v 89'337 (0'0,89'337] local-lis/les=59/60 n=47 ec=20/20 lis/c 59/59 les/c/f 60/60/0 59/59/59) [0,6] r=0 lpr=59 luod=89'336 crt=89'337 lcod 89'334 mlcod 89'334 active+clean ps=[16~1,1c~1,26~1,2e~1]] do_op: op osd_op(client.4428.0:2987 3.3 3:cd983545:::smithi16216178-470:head [rollback 30] snapc 34=[34,33,30,2d] ondisk+write+known_if_redirected e89) v8
2018-05-11 06:15:08.990 7f9e4131e700 20 osd.0 pg_epoch: 89 pg[3.3( v 89'337 (0'0,89'337] local-lis/les=59/60 n=47 ec=20/20 lis/c 59/59 les/c/f 60/60/0 59/59/59) [0,6] r=0 lpr=59 luod=89'336 crt=89'337 lcod 89'334 mlcod 89'334 active+clean ps=[16~1,1c~1,26~1,2e~1]] op_has_sufficient_caps session=0x55cf1344ef00 pool=3 (cache ) owner=0 pool_app_metadata={} need_read_cap=0 need_write_cap=1 classes=[] -> yes
2018-05-11 06:15:08.990 7f9e4131e700 10 osd.0 pg_epoch: 89 pg[3.3( v 89'337 (0'0,89'337] local-lis/les=59/60 n=47 ec=20/20 lis/c 59/59 les/c/f 60/60/0 59/59/59) [0,6] r=0 lpr=59 luod=89'336 crt=89'337 lcod 89'334 mlcod 89'334 active+clean ps=[16~1,1c~1,26~1,2e~1]] do_op osd_op(client.4428.0:2987 3.3 3:cd983545:::smithi16216178-470:head [rollback 30] snapc 34=[34,33,30,2d] ondisk+write+known_if_redirected e89) v8 may_write -> write-ordered flags ondisk+write+known_if_redirected
2018-05-11 06:15:08.990 7f9e4131e700 10 osd.0 pg_epoch: 89 pg[3.3( v 89'337 (0'0,89'337] local-lis/les=59/60 n=47 ec=20/20 lis/c 59/59 les/c/f 60/60/0 59/59/59) [0,6] r=0 lpr=59 luod=89'336 crt=89'337 lcod 89'334 mlcod 89'334 active+clean ps=[16~1,1c~1,26~1,2e~1]] get_object_context: found obc in cache: 0x55cf161a8100
2018-05-11 06:15:08.990 7f9e4131e700 10 osd.0 pg_epoch: 89 pg[3.3( v 89'337 (0'0,89'337] local-lis/les=59/60 n=47 ec=20/20 lis/c 59/59 les/c/f 60/60/0 59/59/59) [0,6] r=0 lpr=59 luod=89'336 crt=89'337 lcod 89'334 mlcod 89'334 active+clean ps=[16~1,1c~1,26~1,2e~1]] get_object_context: 0x55cf161a8100 3:cd983545:::smithi16216178-470:head rwstate(write n=1 w=0) oi: 3:cd983545:::smithi16216178-470:head(89'337 osd.0.0:511 s 3882483 uv 656 alloc_hint [0 0 0]) exists: 1 ssc: 0x55cf11bb6c60 snapset: 34=[34,33,30,2d]:{34=[34,33,30,2d]}
2018-05-11 06:15:08.990 7f9e4131e700 10 osd.0 pg_epoch: 89 pg[3.3( v 89'337 (0'0,89'337] local-lis/les=59/60 n=47 ec=20/20 lis/c 59/59 les/c/f 60/60/0 59/59/59) [0,6] r=0 lpr=59 luod=89'336 crt=89'337 lcod 89'334 mlcod 89'334 active+clean ps=[16~1,1c~1,26~1,2e~1]] find_object_context 3:cd983545:::smithi16216178-470:head @head oi=3:cd983545:::smithi16216178-470:head(89'337 osd.0.0:511 s 3882483 uv 656 alloc_hint [0 0 0])
2018-05-11 06:15:08.990 7f9e4131e700 10 osd.0 pg_epoch: 89 pg[3.3( v 89'337 (0'0,89'337] local-lis/les=59/60 n=47 ec=20/20 lis/c 59/59 les/c/f 60/60/0 59/59/59) [0,6] r=0 lpr=59 luod=89'336 crt=89'337 lcod 89'334 mlcod 89'334 active+clean ps=[16~1,1c~1,26~1,2e~1]] agent_choose_mode flush_mode: idle evict_mode: idle num_objects: 47 num_bytes: 132907531 num_objects_dirty: 25 num_objects_omap: 0 num_dirty: 25 num_user_objects: 47 num_user_bytes: 132921631 num_overhead_bytes: 14100 pool.info.target_max_bytes: 0 pool.info.target_max_objects: 250
2018-05-11 06:15:08.990 7f9e4131e700 20 osd.0 pg_epoch: 89 pg[3.3( v 89'337 (0'0,89'337] local-lis/les=59/60 n=47 ec=20/20 lis/c 59/59 les/c/f 60/60/0 59/59/59) [0,6] r=0 lpr=59 luod=89'336 crt=89'337 lcod 89'334 mlcod 89'334 active+clean ps=[16~1,1c~1,26~1,2e~1]] agent_choose_mode dirty 0.403225 full 0.758064
2018-05-11 06:15:08.990 7f9e4131e700 25 osd.0 pg_epoch: 89 pg[3.3( v 89'337 (0'0,89'337] local-lis/les=59/60 n=47 ec=20/20 lis/c 59/59 les/c/f 60/60/0 59/59/59) [0,6] r=0 lpr=59 luod=89'336 crt=89'337 lcod 89'334 mlcod 89'334 active+clean ps=[16~1,1c~1,26~1,2e~1]] maybe_handle_cache_detail 3:cd983545:::smithi16216178-470:head(89'337 osd.0.0:511 s 3882483 uv 656 alloc_hint [0 0 0]) exists missing_oid MIN must_promote 0 in_hit_set 1
2018-05-11 06:15:08.990 7f9e4131e700 25 osd.0 pg_epoch: 89 pg[3.3( v 89'337 (0'0,89'337] local-lis/les=59/60 n=47 ec=20/20 lis/c 59/59 les/c/f 60/60/0 59/59/59) [0,6] r=0 lpr=59 luod=89'336 crt=89'337 lcod 89'334 mlcod 89'334 active+clean ps=[16~1,1c~1,26~1,2e~1]] do_op oi 3:cd983545:::smithi16216178-470:head(89'337 osd.0.0:511 s 3882483 uv 656 alloc_hint [0 0 0])
2018-05-11 06:15:08.990 7f9e4131e700 20 osd.0 pg_epoch: 89 pg[3.3( v 89'337 (0'0,89'337] local-lis/les=59/60 n=47 ec=20/20 lis/c 59/59 les/c/f 60/60/0 59/59/59) [0,6] r=0 lpr=59 luod=89'336 crt=89'337 lcod 89'334 mlcod 89'334 active+clean ps=[16~1,1c~1,26~1,2e~1]] do_op obc obc(3:cd983545:::smithi16216178-470:head rwstate(write n=2 w=0))
2018-05-11 06:15:08.990 7f9e4131e700 10 osd.0 pg_epoch: 89 pg[3.3( v 89'337 (0'0,89'337] local-lis/les=59/60 n=47 ec=20/20 lis/c 59/59 les/c/f 60/60/0 59/59/59) [0,6] r=0 lpr=59 luod=89'336 crt=89'337 lcod 89'334 mlcod 89'334 active+clean ps=[16~1,1c~1,26~1,2e~1]] execute_ctx 0x55cf1169a800
2018-05-11 06:15:08.990 7f9e4131e700 10 osd.0 pg_epoch: 89 pg[3.3( v 89'337 (0'0,89'337] local-lis/les=59/60 n=47 ec=20/20 lis/c 59/59 les/c/f 60/60/0 59/59/59) [0,6] r=0 lpr=59 luod=89'336 crt=89'337 lcod 89'334 mlcod 89'334 active+clean ps=[16~1,1c~1,26~1,2e~1]] execute_ctx 3:cd983545:::smithi16216178-470:head [rollback 30] ov 89'337 av 89'338 snapc 34=[34,33,30,2d] snapset 34=[34,33,30,2d]:{34=[34,33,30,2d]}
2018-05-11 06:15:08.990 7f9e4131e700 10 osd.0 pg_epoch: 89 pg[3.3( v 89'337 (0'0,89'337] local-lis/les=59/60 n=47 ec=20/20 lis/c 59/59 les/c/f 60/60/0 59/59/59) [0,6] r=0 lpr=59 luod=89'336 crt=89'337 lcod 89'334 mlcod 89'334 active+clean ps=[16~1,1c~1,26~1,2e~1]] do_osd_op 3:cd983545:::smithi16216178-470:head [rollback 30]
2018-05-11 06:15:08.990 7f9e4131e700 10 osd.0 pg_epoch: 89 pg[3.3( v 89'337 (0'0,89'337] local-lis/les=59/60 n=47 ec=20/20 lis/c 59/59 les/c/f 60/60/0 59/59/59) [0,6] r=0 lpr=59 luod=89'336 crt=89'337 lcod 89'334 mlcod 89'334 active+clean ps=[16~1,1c~1,26~1,2e~1]] do_osd_op  rollback 30
2018-05-11 06:15:08.990 7f9e4131e700 10 osd.0 pg_epoch: 89 pg[3.3( v 89'337 (0'0,89'337] local-lis/les=59/60 n=47 ec=20/20 lis/c 59/59 les/c/f 60/60/0 59/59/59) [0,6] r=0 lpr=59 luod=89'336 crt=89'337 lcod 89'334 mlcod 89'334 active+clean ps=[16~1,1c~1,26~1,2e~1]] _rollback_to 3:cd983545:::smithi16216178-470:head snapid 30
2018-05-11 06:15:08.990 7f9e4131e700 10 osd.0 pg_epoch: 89 pg[3.3( v 89'337 (0'0,89'337] local-lis/les=59/60 n=47 ec=20/20 lis/c 59/59 les/c/f 60/60/0 59/59/59) [0,6] r=0 lpr=59 luod=89'336 crt=89'337 lcod 89'334 mlcod 89'334 active+clean ps=[16~1,1c~1,26~1,2e~1]] find_object_context 3:cd983545:::smithi16216178-470:30 @30 snapset 34=[34,33,30,2d]:{34=[34,33,30,2d]}
2018-05-11 06:15:08.990 7f9e4131e700 10 osd.0 pg_epoch: 89 pg[3.3( v 89'337 (0'0,89'337] local-lis/les=59/60 n=47 ec=20/20 lis/c 59/59 les/c/f 60/60/0 59/59/59) [0,6] r=0 lpr=59 luod=89'336 crt=89'337 lcod 89'334 mlcod 89'334 active+clean ps=[16~1,1c~1,26~1,2e~1]] get_object_context: obc NOT found in cache: 3:cd983545:::smithi16216178-470:34
2018-05-11 06:15:08.990 7f9e4131e700 15 bluestore(/var/lib/ceph/osd/ceph-0) getattr 3.3_head #3:cd983545:::smithi16216178-470:34# _
2018-05-11 06:15:08.990 7f9e4131e700 20 bluestore(/var/lib/ceph/osd/ceph-0).collection(3.3_head 0x55cf11a80400) get_onode oid #3:cd983545:::smithi16216178-470:34# key 0x7f8000000000000003cd9835'E!smithi16216178-470!='0x0000000000000034ffffffffffffffff'o'
2018-05-11 06:15:08.990 7f9e4131e700 20 bluestore(/var/lib/ceph/osd/ceph-0).collection(3.3_head 0x55cf11a80400)  r -2 v.len 0
2018-05-11 06:15:08.990 7f9e4131e700 10 bluestore(/var/lib/ceph/osd/ceph-0) getattr 3.3_head #3:cd983545:::smithi16216178-470:34# _ = -2
2018-05-11 06:15:08.990 7f9e4131e700 10 osd.0 pg_epoch: 89 pg[3.3( v 89'337 (0'0,89'337] local-lis/les=59/60 n=47 ec=20/20 lis/c 59/59 les/c/f 60/60/0 59/59/59) [0,6] r=0 lpr=59 luod=89'336 crt=89'337 lcod 89'334 mlcod 89'334 active+clean ps=[16~1,1c~1,26~1,2e~1]] get_object_context: no obc for soid 3:cd983545:::smithi16216178-470:34 and !can_create
2018-05-11 06:15:08.990 7f9e4131e700 20 osd.0 pg_epoch: 89 pg[3.3( v 89'337 (0'0,89'337] local-lis/les=59/60 n=47 ec=20/20 lis/c 59/59 les/c/f 60/60/0 59/59/59) [0,6] r=0 lpr=59 luod=89'336 crt=89'337 lcod 89'334 mlcod 89'334 active+clean ps=[16~1,1c~1,26~1,2e~1]] find_object_context missing clone 3:cd983545:::smithi16216178-470:34
2018-05-11 06:15:08.990 7f9e4131e700 25 osd.0 pg_epoch: 89 pg[3.3( v 89'337 (0'0,89'337] local-lis/les=59/60 n=47 ec=20/20 lis/c 59/59 les/c/f 60/60/0 59/59/59) [0,6] r=0 lpr=59 luod=89'336 crt=89'337 lcod 89'334 mlcod 89'334 active+clean ps=[16~1,1c~1,26~1,2e~1]] maybe_handle_cache_detail (no obc) missing_oid 3:cd983545:::smithi16216178-470:34 must_promote 1 in_hit_set 0
2018-05-11 06:15:08.990 7f9e4131e700 10 osd.0 pg_epoch: 89 pg[3.3( v 89'337 (0'0,89'337] local-lis/les=59/60 n=47 ec=20/20 lis/c 59/59 les/c/f 60/60/0 59/59/59) [0,6] r=0 lpr=59 luod=89'336 crt=89'337 lcod 89'334 mlcod 89'334 active+clean ps=[16~1,1c~1,26~1,2e~1]] write_blocked_by_scrub 3:cd983545:::smithi16216178-470:34 snapshot can't preempt
2018-05-11 06:15:08.990 7f9e4131e700 10 osd.0 pg_epoch: 89 pg[3.3( v 89'337 (0'0,89'337] local-lis/les=59/60 n=47 ec=20/20 lis/c 59/59 les/c/f 60/60/0 59/59/59) [0,6] r=0 lpr=59 luod=89'336 crt=89'337 lcod 89'334 mlcod 89'334 active+clean ps=[16~1,1c~1,26~1,2e~1]] promote_object 3:cd983545:::smithi16216178-470:34 blocked by scrub
2018-05-11 06:15:08.990 7f9e4131e700 10 osd.0 pg_epoch: 89 pg[3.3( v 89'337 (0'0,89'337] local-lis/les=59/60 n=47 ec=20/20 lis/c 59/59 les/c/f 60/60/0 59/59/59) [0,6] r=0 lpr=59 luod=89'336 crt=89'337 lcod 89'334 mlcod 89'334 active+clean ps=[16~1,1c~1,26~1,2e~1]] promote_object 3:cd983545:::smithi16216178-470:34 placing op in waiting_for_scrub
2018-05-11 06:15:08.994 7f9e4131e700 -1 /build/ceph-13.1.0-78-gaa906b7/src/osd/PrimaryLogPG.cc: In function 'int PrimaryLogPG::_rollback_to(PrimaryLogPG::OpContext*, ceph_osd_op&)' thread 7f9e4131e700 time 2018-05-11 06:15:08.996450
/build/ceph-13.1.0-78-gaa906b7/src/osd/PrimaryLogPG.cc: 7762: FAILED assert(promote_obc)

 ceph version 13.1.0-78-gaa906b7 (aa906b73d8d2c8f927e3d0fbb2041c948a4d54ff) mimic (dev)
 1: (ceph::__ceph_assert_fail(char const*, char const*, int, char const*)+0x102) [0x7f9e69cb7202]
 2: (()+0x2e43c7) [0x7f9e69cb73c7]
 3: (PrimaryLogPG::_rollback_to(PrimaryLogPG::OpContext*, ceph_osd_op&)+0xefb) [0x55cf0d85748b]
 4: (PrimaryLogPG::do_osd_ops(PrimaryLogPG::OpContext*, std::vector<OSDOp, std::allocator<OSDOp> >&)+0x3351) [0x55cf0d860141]
 5: (PrimaryLogPG::prepare_transaction(PrimaryLogPG::OpContext*)+0x9f) [0x55cf0d86e8bf]
 6: (PrimaryLogPG::execute_ctx(PrimaryLogPG::OpContext*)+0x38b) [0x55cf0d86f0bb]
 7: (PrimaryLogPG::do_op(boost::intrusive_ptr<OpRequest>&)+0x361c) [0x55cf0d873abc]
 8: (PrimaryLogPG::do_request(boost::intrusive_ptr<OpRequest>&, ThreadPool::TPHandle&)+0xcc3) [0x55cf0d877cd3]
 9: (OSD::dequeue_op(boost::intrusive_ptr<PG>, boost::intrusive_ptr<OpRequest>, ThreadPool::TPHandle&)+0x1b8) [0x55cf0d6d2148]
 10: (PGOpItem::run(OSD*, OSDShard*, boost::intrusive_ptr<PG>&, ThreadPool::TPHandle&)+0x62) [0x55cf0d94afd2]
 11: (OSD::ShardedOpWQ::_process(unsigned int, ceph::heartbeat_handle_d*)+0x590) [0x55cf0d6f18a0]
 12: (ShardedThreadPool::shardedthreadpool_worker(unsigned int)+0x46e) [0x7f9e69cbc13e]
 13: (ShardedThreadPool::WorkThreadSharded::entry()+0x10) [0x7f9e69cbe1c0]
 14: (()+0x76ba) [0x7f9e687606ba]
 15: (clone()+0x6d) [0x7f9e67f8941d]
```

**Comment by dzafman** [comment]
@liewegas Thinking about this some more, we have a case where there are many snapshots causing multiple chunks to be processed before we get to the head object.  In that case a delete of a snapshot in an earlier chunk would be in cleaned_meta_map .  This isn't about the chunk getting smaller, but rather about making any changes before the head object is reached.  That is why the changes to write_blocked_by_scrub() to use range_intersects_scrub().  The end result is that we don't allow any changes to any snapshots until the entire range to head isn't part of the largest scrub region in progress.

**Comment by dzafman** [comment]
PASSED failing test X 20:
http://pulpito.ceph.com/dzafman-2018-05-14_10:50:57-rados:thrash-wip-24045-on-kefu-distro-basic-smithi/

Re-running wip-zafman-tesitng rados/thrash suite.

**Comment by dzafman** [comment]
@liewegas I will immediately cherry-pick this to mimic once it passes the rados/thrash run.

**Comment by liewegas** [comment]
Something like (untested):
<pre>
diff --git a/src/osd/PG.cc b/src/osd/PG.cc
index 738919e8fb..d1fb1397dd 100644
--- a/src/osd/PG.cc
+++ b/src/osd/PG.cc
@@ -4566,6 +4566,7 @@ int PG::build_scrub_map_chunk(
   _repair_oinfo_oid(map);
   if (!is_primary()) {
     ScrubMap for_meta_scrub;
+    scrubber.cleaned_meta_map.clear_from(start);
     scrubber.cleaned_meta_map.insert(map);
     scrubber.clean_meta_map(for_meta_scrub);
     _scan_snaps(for_meta_scrub);
@@ -5248,6 +5249,7 @@ void PG::scrub_compare_maps()
   dout(10) << __func__ << " has maps, analyzing" << dendl;
 
   // construct authoritative scrub map for type specific scrubbing
+  scrubber.cleaend_meta_map.clear_from(scrubber.start);
   scrubber.cleaned_meta_map.insert(scrubber.primary_scrubmap);
   map<hobject_t,
       pair<boost::optional<uint32_t>,
diff --git a/src/osd/osd_types.h b/src/osd/osd_types.h
index 2455b94c93..4fe40c3c2f 100644
--- a/src/osd/osd_types.h
+++ b/src/osd/osd_types.h
@@ -4967,6 +4967,9 @@ struct ScrubMap {
   bool has_large_omap_object_errors:1;
 
   void merge_incr(const ScrubMap &l);
+  void clear_from(const hobject_t& start) {
+    objects.erase(objects.lower_bound(start), objects.end());
+  }
   void insert(const ScrubMap &r) {
     objects.insert(r.objects.begin(), r.objects.end());
   }
</pre>

**Comment by dzafman** [comment]
@liewegas I don't think your change to fix clean_meta_map.

1. Eviction is avoided for a scrub window intersecting with snapshot to head.
1. _max_end_ is added to keep scrub window the same even when preemption reduces chunk size
1. __scan_snaps()_ only fixes snapshots missing from _snapset_ (extra items in _snapset_ ignored)
1. Racing promote looks like a missing snapshot which_scrub_snapshot_metadata()_ ignores already

**Comment by dzafman** [comment]
@liewegas This version that passed original test x 20, only required the original commit with 1 bug correction AND removal of the `assert(!soid.is_snap());` in _write_blocked_by_scrub()_.

**Comment by dzafman** [comment]
@liewegas Ready for final review and merge.  Should I cherry-pick to mimic?

Passed:
http://pulpito.ceph.com/dzafman-2018-05-16_09:57:45-rados:thrash-wip-zafman-testing-distro-basic-smithi/
2539708 http://tracker.ceph.com/issues/24148
2539898 http://tracker.ceph.com/issues/24076

http://pulpito.ceph.com/dzafman-2018-05-16_10:04:16-rados:thrash-wip-24045-on-kefu-distro-basic-smithi/

**Pull request merged**
