### PR TITLE
mgr/dashboard: replace deprecated table panel in grafana with a newer table panel

### PR DESCRIPTION
**Pull request by aaSharma14**
Since the grafana table panel is deprectaed in the latest grafana versions, the existing panels should be replaced with the newer table panel

Before:

Screenshot from 2024-03-28 10-26-08

After:

Screenshot from 2024-04-02 11-49-57

Before:

Screenshot from 2024-04-02 11-37-47

After:

Screenshot from 2024-04-02 12-19-40

Before:

Screenshot from 2024-03-28 10-27-36

After:

Screenshot from 2024-04-02 12-20-21

Before:

Screenshot from 2024-03-28 10-27-59

After:

Screenshot from 2024-03-28 14-38-13

Fixes: https://tracker.ceph.com/issues/65174

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Review by nizamial09 — APPROVED** [review]
apart from the dropdown in this chart, everything looks good to me. thanks

Screenshot from 2024-03-27 14-59-19

**Comment by cloudbehl** [comment]
should go after this: https://github.com/ceph/ceph/pull/56509

**Comment by cloudbehl** [comment]
can you record a demo and point which one are you replace  and screenshot of comparison

**Comment by nizamial09** [comment]
> should go after this: #56509

the PR you pasted here is the same PR.

**Comment by nizamial09** [comment]
```
jsonnet-lint: exit 1 (0.75 seconds) /home/jenkins-build/build/workspace/ceph-pull-requests/monitoring/ceph-mixin> ./lint-jsonnet.sh --test pid=1860617
  jsonnet-lint: FAIL code 1 (11.04=setup[10.29]+cmd[0.75] seconds)
  evaluation failed :( (11.71 seconds)
```

**Comment by cloudbehl** [comment]
Hey @aaSharma14 In pool overview table.

Top slow ops per host -> Before and After is not matching, the instance value is changed with time.

type -> Type and values is Replica:3(in my cluster and yours says replicated) or Erasure coded 2+2/4+2

image

Highest Write latencies: We can put 0.00 rather than NaN

Read and write latencies needs to be sorted by latency,  its not visible in screenshot I hope its working.

**Comment by aaSharma14** [comment]
> Hey @aaSharma14 In pool overview table.
> 
> Top slow ops per host -> Before and After is not matching, the instance value is changed with time.
> 
> type -> Type and values is Replica:3(in my cluster and yours says replicated) or Erasure coded 2+2/4+2
> 
> image
> 
> Highest Write latencies: We can put 0.00 rather than NaN
> 
> Read and write latencies needs to be sorted by latency, its not visible in screenshot I hope its working.

Thanks @cloudbehl , Updated the PR

**Comment by aaSharma14** [comment]
jenkins test dashboard cephadm

**Review by cloudbehl — APPROVED** [review]

**Comment by aaSharma14** [comment]
jenkins test dashboard cephadm

**Comment by aaSharma14** [comment]
jenkins test dashboard cephadm

**Pull request merged**
