### PR TITLE
rgw: fix spelling of eTag in S3 message structure

### PR DESCRIPTION
**Pull request by tschoonj**
An S3 object event contains its eTag, currently spelled as 'etag' in the message structure, which does not correspond to the documentation example (https://docs.ceph.com/en/latest/radosgw/notifications/#events), or what is used by AWS (https://docs.aws.amazon.com/AmazonS3/latest/userguide/notification-content-structure.html).

Fixes bug https://tracker.ceph.com/issues/50115

Signed-off-by: Tom Schoonjans <Tom.Schoonjans@rfi.ac.uk>

## Checklist
- [x] References tracker ticket
- [x] Updates documentation if necessary
- [x] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by tschoonj** [comment]
@yuvalif the unit tests (make check and run-s3tests.sh) appear to succeed locally, so I don't think that there is currently a test being run for this key in the message structure at all. Any suggestions as to where it should go in?

Thanks!

**Comment by yuvalif** [comment]
> @yuvalif the unit tests (make check and run-s3tests.sh) appear to succeed locally, so I don't think that there is currently a test being run for this key in the message structure at all. Any suggestions as to where it should go in?
> 
> Thanks!

we recently added "bucket_notification" tests. you can run them locally against a vstart cluster. more details are here:
https://github.com/ceph/ceph/tree/master/src/test/rgw/bucket_notification
currently these tests are covering only Kafka and HTTP endpoints, and there is no coverage for eTags.

it would be great if you can add an eTag test in: https://github.com/ceph/ceph/blob/master/src/test/rgw/bucket_notification/test_bn.py
test can validate the correct field name in JSON, and also the eTag value.

if you don't want to bother with Kafka setup and install, you can use an HTTP endpoint for this test. and run just this tests using:
```
BNTESTS_CONF=bntests.conf python -m nose -s /path/to/ceph/src/test/rgw/bucket_notification/test_bn.py:name_of_specific_test
```

**Review by yuvalif — CHANGES_REQUESTED** [review]
- [ ] please add test
- [ ] please mention the change in release notes (as this is changing the public API): https://github.com/ceph/ceph/blob/master/PendingReleaseNotes

**Comment by tschoonj** [comment]
I just tried one of the examples but didn't get very far 😢 

I spun up a Kafka server and then ran:

```
$ ../src/vstart.sh -n -d -l
... lots of output
$ source venv/bin/activate
(venv) $ export BNTESTS_CONF=bntests.conf 
(venv) $ nosetests -s ../src/test/rgw/bucket_notification/test_bn.py:test_ps_s3_notification_push_kafka_on_master
E
======================================================================
ERROR: test pushing kafka s3 notification on master
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/awf63395/github/ceph/build/venv/lib/python3.6/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/awf63395/github/ceph/src/test/rgw/bucket_notification/test_bn.py", line 1006, in test_ps_s3_notification_push_kafka_on_master
    bucket = conn.create_bucket(bucket_name)
  File "/home/awf63395/github/ceph/build/venv/lib/python3.6/site-packages/boto/s3/connection.py", line 619, in create_bucket
    data=data)
  File "/home/awf63395/github/ceph/build/venv/lib/python3.6/site-packages/boto/s3/connection.py", line 671, in make_request
    retry_handler=retry_handler
  File "/home/awf63395/github/ceph/build/venv/lib/python3.6/site-packages/boto/connection.py", line 1071, in make_request
    retry_handler=retry_handler)
  File "/home/awf63395/github/ceph/build/venv/lib/python3.6/site-packages/boto/connection.py", line 1030, in _mexe
    raise ex
  File "/home/awf63395/github/ceph/build/venv/lib/python3.6/site-packages/boto/connection.py", line 943, in _mexe
    request.body, request.headers)
  File "/usr/lib/python3.6/http/client.py", line 1281, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1327, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1276, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1042, in _send_output
    self.send(msg)
  File "/usr/lib/python3.6/http/client.py", line 980, in send
    self.connect()
  File "/usr/lib/python3.6/http/client.py", line 952, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/lib/python3.6/socket.py", line 724, in create_connection
    raise err
  File "/usr/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
-------------------- >> begin captured logging << --------------------
boto: DEBUG: Using access key provided by client.
boto: DEBUG: Using secret key provided by client.
boto: DEBUG: path=/yfcysx-1/
boto: DEBUG: auth_path=/yfcysx-1/
boto: DEBUG: Method: PUT
boto: DEBUG: Path: /yfcysx-1/
boto: DEBUG: Data: 
boto: DEBUG: Headers: {}
boto: DEBUG: Host: localhost:8000
boto: DEBUG: Port: 8000
boto: DEBUG: Params: {}
boto: DEBUG: establishing HTTP connection: kwargs={'timeout': 70, 'port': 8000}
boto: DEBUG: Token: None
boto: DEBUG: StringToSign:
PUT


Sat, 10 Apr 2021 06:33:02 GMT
/yfcysx-1/
boto: DEBUG: Signature:
AWS 0555b35654ad1656d804:C6c3t1pSPioMe0RBAQxwPyOHC+8=
boto: DEBUG: Final headers: {'User-Agent': 'Boto/2.49.0 Python/3.6.9 Linux/4.15.0-135-generic', 'Date': 'Sat, 10 Apr 2021 06:33:02 GMT', 'Authorization': 'AWS 0555b35654ad1656d804:C6c3t1pSPioMe0RBAQxwPyOHC+8=', 'Content-Length': '0'}
boto: DEBUG: encountered ConnectionRefusedError exception, reconnecting
boto: DEBUG: establishing HTTP connection: kwargs={'timeout': 70, 'port': 8000}
boto: DEBUG: Token: None
boto: DEBUG: StringToSign:
PUT


Sat, 10 Apr 2021 06:33:02 GMT
/yfcysx-1/
boto: DEBUG: Signature:
AWS 0555b35654ad1656d804:C6c3t1pSPioMe0RBAQxwPyOHC+8=
boto: DEBUG: Final headers: {'User-Agent': 'Boto/2.49.0 Python/3.6.9 Linux/4.15.0-135-generic', 'Date': 'Sat, 10 Apr 2021 06:33:02 GMT', 'Authorization': 'AWS 0555b35654ad1656d804:C6c3t1pSPioMe0RBAQxwPyOHC+8=', 'Content-Length': '0'}
boto: DEBUG: encountered ConnectionRefusedError exception, reconnecting
boto: DEBUG: establishing HTTP connection: kwargs={'timeout': 70, 'port': 8000}
boto: DEBUG: Token: None
boto: DEBUG: StringToSign:
PUT


Sat, 10 Apr 2021 06:33:02 GMT
/yfcysx-1/
boto: DEBUG: Signature:
AWS 0555b35654ad1656d804:C6c3t1pSPioMe0RBAQxwPyOHC+8=
boto: DEBUG: Final headers: {'User-Agent': 'Boto/2.49.0 Python/3.6.9 Linux/4.15.0-135-generic', 'Date': 'Sat, 10 Apr 2021 06:33:02 GMT', 'Authorization': 'AWS 0555b35654ad1656d804:C6c3t1pSPioMe0RBAQxwPyOHC+8=', 'Content-Length': '0'}
boto: DEBUG: encountered ConnectionRefusedError exception, reconnecting
boto: DEBUG: establishing HTTP connection: kwargs={'timeout': 70, 'port': 8000}
boto: DEBUG: Token: None
boto: DEBUG: StringToSign:
PUT


Sat, 10 Apr 2021 06:33:02 GMT
/yfcysx-1/
boto: DEBUG: Signature:
AWS 0555b35654ad1656d804:C6c3t1pSPioMe0RBAQxwPyOHC+8=
boto: DEBUG: Final headers: {'User-Agent': 'Boto/2.49.0 Python/3.6.9 Linux/4.15.0-135-generic', 'Date': 'Sat, 10 Apr 2021 06:33:02 GMT', 'Authorization': 'AWS 0555b35654ad1656d804:C6c3t1pSPioMe0RBAQxwPyOHC+8=', 'Content-Length': '0'}
boto: DEBUG: encountered ConnectionRefusedError exception, reconnecting
boto: DEBUG: establishing HTTP connection: kwargs={'timeout': 70, 'port': 8000}
boto: DEBUG: Token: None
boto: DEBUG: StringToSign:
PUT


Sat, 10 Apr 2021 06:33:02 GMT
/yfcysx-1/
boto: DEBUG: Signature:
AWS 0555b35654ad1656d804:C6c3t1pSPioMe0RBAQxwPyOHC+8=
boto: DEBUG: Final headers: {'User-Agent': 'Boto/2.49.0 Python/3.6.9 Linux/4.15.0-135-generic', 'Date': 'Sat, 10 Apr 2021 06:33:02 GMT', 'Authorization': 'AWS 0555b35654ad1656d804:C6c3t1pSPioMe0RBAQxwPyOHC+8=', 'Content-Length': '0'}
boto: DEBUG: encountered ConnectionRefusedError exception, reconnecting
boto: DEBUG: establishing HTTP connection: kwargs={'timeout': 70, 'port': 8000}
boto: DEBUG: Token: None
boto: DEBUG: StringToSign:
PUT


Sat, 10 Apr 2021 06:33:02 GMT
/yfcysx-1/
boto: DEBUG: Signature:
AWS 0555b35654ad1656d804:C6c3t1pSPioMe0RBAQxwPyOHC+8=
boto: DEBUG: Final headers: {'User-Agent': 'Boto/2.49.0 Python/3.6.9 Linux/4.15.0-135-generic', 'Date': 'Sat, 10 Apr 2021 06:33:02 GMT', 'Authorization': 'AWS 0555b35654ad1656d804:C6c3t1pSPioMe0RBAQxwPyOHC+8=', 'Content-Length': '0'}
boto: DEBUG: encountered ConnectionRefusedError exception, reconnecting
boto: DEBUG: establishing HTTP connection: kwargs={'timeout': 70, 'port': 8000}
boto: DEBUG: Token: None
boto: DEBUG: StringToSign:
PUT


Sat, 10 Apr 2021 06:33:02 GMT
/yfcysx-1/
boto: DEBUG: Signature:
AWS 0555b35654ad1656d804:C6c3t1pSPioMe0RBAQxwPyOHC+8=
boto: DEBUG: Final headers: {'User-Agent': 'Boto/2.49.0 Python/3.6.9 Linux/4.15.0-135-generic', 'Date': 'Sat, 10 Apr 2021 06:33:02 GMT', 'Authorization': 'AWS 0555b35654ad1656d804:C6c3t1pSPioMe0RBAQxwPyOHC+8=', 'Content-Length': '0'}
boto: DEBUG: encountered ConnectionRefusedError exception, reconnecting
boto: DEBUG: establishing HTTP connection: kwargs={'timeout': 70, 'port': 8000}
--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
Ran 1 test in 58.423s

FAILED (errors=1)
```

Any thoughts on what is going wrong here?

**Comment by yuvalif** [comment]
the above looks like an RGW crash. this is probably why the client gets "[Errno 111] Connection refused"
most likely, unrelated to the fix here. recently we have seen RGW crashes especially when running in ubuntu.

**Comment by tschoonj** [comment]
Have the problems on ubuntu been resolved? I don't have access to a suitable CentOS VM right now...

**Comment by yuvalif** [comment]
> Have the problems on ubuntu been resolved? I don't have access to a suitable CentOS VM right now...

@cbodley was the ubuntu crash solved?

**Comment by cbodley** [comment]
> 
> 
> > Have the problems on ubuntu been resolved? I don't have access to a suitable CentOS VM right now...
> 
> @cbodley was the ubuntu crash solved?

yes

**Comment by tschoonj** [comment]
Thanks, I will try and revisit this soon.

**Comment by tschoonj** [comment]
I tried again just now after rebasing against origin/master and ran into the same `ConnectionRefusedError`. I tried going through the logs to figure out what went wrong but there's just too much output for me to go through.

Any advice?

**Comment by yuvalif** [comment]
> I tried again just now after rebasing against origin/master and ran into the same `ConnectionRefusedError`. I tried going through the logs to figure out what went wrong but there's just too much output for me to go through.
> 
> Any advice?

could you share the logs?
if this is because of an RGW crash, it should be simple to see the backtrace in the radosgw log

**Comment by tschoonj** [comment]
There is no such file.

In out I see:

```
client.admin.2611.log   client.admin.31320.log  mds.a.heartbeat  mon.b.heartbeat
client.admin.30764.log  client.admin.31344.log  mds.a.log        mon.b.log
client.admin.30810.log  client.admin.31377.log  mds.a.pid        mon.b.pid
client.admin.30840.log  client.admin.31414.log  mds.b.heartbeat  mon.c.heartbeat
client.admin.30867.log  client.admin.32677.log  mds.b.log        mon.c.log
client.admin.30893.log  client.admin.5697.log   mds.b.pid        mon.c.pid
client.admin.30925.log  client.admin.5752.log   mds.c.heartbeat  osd.0.heartbeat
client.admin.30969.log  client.admin.5815.log   mds.c.log        osd.0.log
client.admin.31020.log  client.admin.5881.log   mds.c.pid        osd.0.pid
client.admin.31064.log  client.admin.5907.log   mgr.x.heartbeat  osd.1.heartbeat
client.admin.31105.log  client.admin.5951.log   mgr.x.log        osd.1.log
client.admin.31145.log  client.admin.5980.log   mgr.x.pid        osd.1.pid
client.admin.31242.log  cluster.mon.a.log       mon.a.heartbeat  osd.2.heartbeat
client.admin.31266.log  cluster.mon.b.log       mon.a.log        osd.2.log
client.admin.31292.log  cluster.mon.c.log       mon.a.pid        osd.2.pid
```

Weird

**Comment by yuvalif** [comment]
> There is no such file.
> 
> In out I see:
> 
> ```
> client.admin.2611.log   client.admin.31320.log  mds.a.heartbeat  mon.b.heartbeat
> client.admin.30764.log  client.admin.31344.log  mds.a.log        mon.b.log
> client.admin.30810.log  client.admin.31377.log  mds.a.pid        mon.b.pid
> client.admin.30840.log  client.admin.31414.log  mds.b.heartbeat  mon.c.heartbeat
> client.admin.30867.log  client.admin.32677.log  mds.b.log        mon.c.log
> client.admin.30893.log  client.admin.5697.log   mds.b.pid        mon.c.pid
> client.admin.30925.log  client.admin.5752.log   mds.c.heartbeat  osd.0.heartbeat
> client.admin.30969.log  client.admin.5815.log   mds.c.log        osd.0.log
> client.admin.31020.log  client.admin.5881.log   mds.c.pid        osd.0.pid
> client.admin.31064.log  client.admin.5907.log   mgr.x.heartbeat  osd.1.heartbeat
> client.admin.31105.log  client.admin.5951.log   mgr.x.log        osd.1.log
> client.admin.31145.log  client.admin.5980.log   mgr.x.pid        osd.1.pid
> client.admin.31242.log  cluster.mon.a.log       mon.a.heartbeat  osd.2.heartbeat
> client.admin.31266.log  cluster.mon.b.log       mon.a.log        osd.2.log
> client.admin.31292.log  cluster.mon.c.log       mon.a.pid        osd.2.pid
> ```
> 
> Weird

maybe vstart is not running RGW?
i usually use `MON=1 OSD=1 RGW=1 MGR=0 MDS=0 ../src/vstart.sh -n -d`

**Comment by tschoonj** [comment]
got it working now thanks!

**Comment by tschoonj** [comment]
I updated the commit with modified unit tests that will ensure that the eTag returned by boto3 is equal to its counterpart in the event message as well as the eTag that we calculated ourselves.

If you're happy with this, I will gladly go through the docs updates...

**Review by yuvalif — APPROVED** [review]

**Comment by yuvalif** [comment]
> I updated the commit with modified unit tests that will ensure that the eTag returned by boto3 is equal to its counterpart in the event message as well as the eTag that we calculated ourselves.
> 
> If you're happy with this, I will gladly go through the docs updates...

docs are actually correct. the only thing to update are the "PendingReleaseNotes".

**Comment by tschoonj** [comment]
Are you ok with the release note I added?

**Comment by yuvalif** [comment]
> Are you ok with the release note I added?

yes, this is great.
thanks @tschoonj for this fix!

**Comment by tschoonj** [comment]
No problem, but this is not the only case where RGW deviates from AWS in the message format structure. As I stated in the original [bug report](https://tracker.ceph.com/issues/50115), there is also a difference in the value of the `eventName` key...

Shall I open a separate ticket for that?

**Comment by yuvalif** [comment]
> No problem, but this is not the only case where RGW deviates from AWS in the message format structure. As I stated in the original [bug report](https://tracker.ceph.com/issues/50115), there is also a difference in the value of the `eventName` key...
> 
> Shall I open a separate ticket for that?

i replied inside the tracker. 
i don't see how the AWS doc: https://docs.aws.amazon.com/AmazonS3/latest/userguide/notification-content-structure.html
is different than ours: https://docs.ceph.com/en/latest/radosgw/notifications/#events

**Comment by yuvalif** [comment]
@tschoonj   we can keep the same ticket, and just add another commit to this PR (less test overhead...)

**Comment by tschoonj** [comment]
This patch appears to do the trick... Hope this is not too naive.

**Comment by yuvalif** [comment]
> @tschoonj we can keep the same ticket, and just add another commit to this PR (less test overhead...)

it works :-) but, IMO, a bit too cryptic.
maybe a `to_event_string()` function that does exactly the same?

**Review by yuvalif — APPROVED** [review]

**Comment by yuvalif** [comment]
teuthology passing: http://pulpito.front.sepia.ceph.com/yuvalif-2021-05-09_15:02:23-rgw:notifications-wip-yuval-etag-spelling-distro-basic-smithi/

**Comment by tschoonj** [comment]
Ready for a merge?

**Comment by yuvalif** [comment]
> Ready for a merge?

yes. thank for the fix!

**Pull request merged**
