### PR TITLE
rgw: set user quota which is less than user's current usage should fail.

### PR DESCRIPTION
**Pull request by zhangsw**
Before setting user's quota, we should check whether his usage has exceeded the new quota. 

Signed-off-by: Zhang Shaowen <zhangshaowen@cmss.chinamobile.com>

### CODE REVIEW

**Comment by zhangsw** [comment]
@cbodley How about we add a parameter , something like '--force',  in setting user's quota? If we don't check the quota,  applications those calculate the cost according to the user's quota may need more work.

**Comment by dang** [comment]
If an option is added, I'd prefer it to default to succeeding, not default to failing.  I'm not aware of any quota tools that fail if the user is over the new quota, so apps need to handle this already, correct?

**Comment by zhangsw** [comment]
@dang Yeah, make it default to succeeding is a better choice.

**Comment by cbodley** [comment]
@zhangsw keep in mind that a quota check here isn't atomic - that user could be in the middle of an upload that would put them over this new quota. so there's little difference between a check here, and an external check based on the output of `radosgw-admin user stats`, for example. for that reason, i don't think it's worth adding extra complexity to the code for setting quotas

**Comment by yehudasa** [comment]
closing for now

**Pull request closed without merging**
