### PR TITLE
nautilus: mgr: use ipv4 default when ipv6 was disabled

### PR DESCRIPTION
**Pull request by pdvian**
http://tracker.ceph.com/issues/40273

### CODE REVIEW

**Comment by votdev** [comment]
For backports you need to cherry pick the changes from the origin PR, in this case https://github.com/ceph/ceph/commit/748c294508980613595a8edf547521582c820051, otherwise @smithfarm won't be happy.

**Comment by smithfarm** [comment]
@votdev Not sure why you're suggesting to cherry-pick the merge commit? 

This backport PR looks fine to me.

**Comment by votdev** [comment]
> @votdev Not sure why you're suggesting to cherry-pick the merge commit?
> 
> This backport PR looks fine to me.

Uahh, sorry, it should be 38e7083301f4d5e419f4c7c1fb596d529d3ab83c

**Comment by yuriw** [comment]
[wip-yuri4-testing-2019-07-24-2314-nautilus](https://trello.com/c/QnlxiPxf/675-wip-yuri4-testing-2019-07-24-2314-nautilus)

**Pull request merged**
