### PR TITLE
osd/PG.cc: fix error in retrieving the last rw interval

### PR DESCRIPTION
**Pull request by 363921219**
Signed-off-by: Jie Wang <jie.wang@kylin-cloud.com>

### CODE REVIEW

**Comment by dragonylffly** [comment]
@athanatos please take a look

**Comment by athanatos** [comment]
I think this is correct (though I'm also pretty sure that whole bit of logic is no longer necessary).  It needs to go through a test run though.  Also, it seems to have failed the build.

**Comment by athanatos** [comment]
retest this please

**Comment by liewegas** [comment]
this is rewritten by https://github.com/ceph/ceph/pull/14444

**Pull request closed without merging**
