### PR TITLE
DNM: EC async "fast read" patchset for hammer (EC read latency improvements)

### PR DESCRIPTION
**Pull request by tsg-**
Backport EC "fast read" patches from master:

131214dc ec: add support for fast read on PGBackend/ECBackend async read

5eb2a77d mon: add a new pool setting to configure fast read for EC pool

54090f18 mon: add a configuration for default fast read setting

### CODE REVIEW

**Comment by dachary** [comment]
@tsg- since this is about backporting a feature, would you mind starting a thread on ceph-devel to get opinions from the people involved ? Backporting a feature sometime happens but it is rare and there must be a strong incentive to do so.

**Comment by athanatos** [comment]
We do not have tests in ceph-qa-suite branch in *master* for this feature yet.  I'm closing this PR until we have tests.  I just created a wip-fast-read ceph-qa-suite branch with it added to one of the ec yamls.  Once our testing is adequate and has been running for a while, we'll consider backporting.

**Comment by tsg-** [comment]
@athanatos, backporting Yahoo's test suite https://github.com/ceph/ceph-qa-suite/pull/503 to hammer should be a good start.  Unless you are already looking at this, I will get this going and add tests as I see fit.

**Comment by brynmathias** [comment]
@athanatos is there any update on the additon of tests for this patch?

There are a group of us using ceph hammer that aren't ready to upgrade to infernarlis, but would benifit greatly from this PR.

We might be able to offer some testing time as well.

**Pull request closed without merging**
