### PR TITLE
pacific: mgr/cephadm: update monitoring stack versions 

### PR DESCRIPTION
**Pull request by aaSharma14**
backport tracker: https://tracker.ceph.com/issues/55366

---

backport of https://github.com/ceph/ceph/pull/45187
backport of https://github.com/ceph/ceph/pull/45739
backport of https://github.com/ceph/ceph/pull/45578
backport of https://github.com/ceph/ceph/pull/45793
parent tracker: https://tracker.ceph.com/issues/54311

this backport was staged using ceph-backport.sh version 16.0.0.6848
find the latest version at https://github.com/ceph/ceph/blob/master/src/script/ceph-backport.sh

### CODE REVIEW

**Comment by aaSharma14** [comment]
jenkins test make check

**Comment by aaSharma14** [comment]
jenkins test api

**Comment by epuertat** [comment]
jenkins test dashboard

**Review by epuertat — APPROVED** [review]
LGTM! Thanks @aaSharma14 !

**Comment by epuertat** [comment]
BTW @aaSharma14 Pacific doesn't contain all the grafonnet work, right? I think you should backport that or the Grafana dashboards conveyed by the 8.3.5 Grafana image don't match Pacific codebase's. Alternatively you could generate a pacific-only Grafana (8.3.5-pacific?) image with the Grafana dashboards from the Pacific tree.

**Comment by avanthakkar** [comment]
jenkins test dashboard

**Review by avanthakkar — APPROVED** [review]

**Comment by aaSharma14** [comment]
jenkins test dashboard

**Pull request merged**
