### PR TITLE
Update libkmip to pull in some portability changes.

### PR DESCRIPTION
**Pull request by mdw-at-linuxbox**
This is just a submodule change.  It will pull in old changes for centos (not sure they matter), plus some new changes for darwin.

This should be tested against pykmip using teuthology before committing.

### CODE REVIEW

**Comment by leonid-s-usov** [comment]
I confirm that this branch solves issues addressed by https://github.com/ceph/libkmip/pull/1

**Comment by mdw-at-linuxbox** [comment]
For the two checks that failed:
"modified submodule" -- apparently my commit message ought to have contained "libkmip submodule".
"make check failed" - not obviously related to libkmip, perhaps environment?  So far as I know, any possible cure should not belong in this PR.

I've pushed out a copy of this to ceph-ci, as "mdw-libkmip-update-1".  If it built, it should be ready to run through teuthology.  Only the s3/kms/kmip (pykmip) part needs testing.

**Comment by leonid-s-usov** [comment]
Hi, any updates on this PR? what's holding it?

**Comment by leonid-s-usov** [comment]
Hi @mdw-at-linuxbox, this commit is one of the last things holding the dependent https://github.com/ceph/ceph/pull/52629. Do you think this can be merged soon?

**Comment by cbodley** [comment]
> For the two checks that failed: "modified submodule" -- apparently my commit message ought to have contained "libkmip submodule". "make check failed" - not obviously related to libkmip, perhaps environment? So far as I know, any possible cure should not belong in this PR.
> 
> I've pushed out a copy of this to ceph-ci, as "mdw-libkmip-update-1". If it built, it should be ready to run through teuthology. Only the s3/kms/kmip (pykmip) part needs testing.

@mdw-at-linuxbox can you please follow up on this stuff?

i recently disabled kmip testing in teuthology with https://github.com/ceph/ceph/pull/54840, so i'm willing to merge without a teuthology run as long as checks pass and shaman builds succeed

**Review by cbodley — APPROVED** [review]

**Comment by cbodley** [comment]
https://shaman.ceph.com/builds/ceph/wip-master-update-kmip-1/ builds green

**Comment by mattbenjamin** [comment]
I experienced problems with my git checkout trying to update the libkmip submodule;  I couldn't figure out the problem, I manually repaired .git and src/libkmip, fwiw

**Comment by leonid-s-usov** [comment]
> I manually repaired .git and src/libkmip

what was the problem?

**Comment by mattbenjamin** [comment]
I couldn't figure out @leonid-s-usov ;  I tried various things, that submodule would not update to the new base, but I wasn't making any headway.  In the end, I overlayed both the .git/modules/src/libkmip and src/libkmip paths with the ones in ceph/main

**Comment by leonid-s-usov** [comment]
did you notice what the paths were before you fixed them?

**Pull request merged**
