### PR TITLE
luminous: rgw: make HTTP dechunking compatible with Amazon S3

### PR DESCRIPTION
**Pull request by shinobu-x**
http://tracker.ceph.com/issues/22401

### CODE REVIEW

**Comment by shinobu-x** [comment]
test this please

**Comment by yuriw** [comment]
[rgw => wip-yuri4-testing-2018-01-25-1744-luminous](https://trello.com/c/qvWoKh2O/243-rgw-wip-yuri4-testing-2018-01-25-1744-luminous)

**Comment by smithfarm** [comment]
@theanalyst @oritwas @cbodley @yehudasa This moves the civetweb submodule SHA1 for luminous - are we sure that's OK?

**Comment by yuriw** [comment]
test this please

**Pull request merged**
