### PR TITLE
cmake: specify distutils build path explicitly

### PR DESCRIPTION
**Pull request by tchaikov**
so we don't need to replicate the logic in distutils/command/build.py
at different places.

Signed-off-by: Kefu Chai <kchai@redhat.com>

### CODE REVIEW

**Comment by tchaikov** [comment]
@wjwithagen this addresses the distutils build path issue also.

**Comment by wjwithagen** [comment]
@tchaikov 
Looks like it would do.
ATM got other things to tend to, but perhaps I can give it a testrun tonight.

**Comment by tchaikov** [comment]
@wjwithagen thanks in advance!

**Comment by alimaredia** [comment]
@mdw-at-linuxbox what do you think about this?

**Comment by wjwithagen** [comment]
@tchaikov 
Is there an easy way to get a diff or something I can run thru patch?
Otherwise I need to start editing 6 files manually

**Comment by tchaikov** [comment]
@wjwithagen

what you do you mean by get a diff? you mean get a patch of this PR, for example? if that's the case, you can using following command to create a local branch named "wip-10568" has the change in this PR.
```bash
git fetch -f origin pull/10568/head:wip-10568
```

**Comment by wjwithagen** [comment]
lgtm

**Comment by tchaikov** [comment]
@alimaredia @mdw-at-linuxbox if no objections i will merge this PR.

**Comment by tchaikov** [comment]
rebased against master and resolved conflicts.

**Pull request merged**
