### PR TITLE
osd: misc osd fixes

### PR DESCRIPTION
**Pull request by wonzhq**

### CODE REVIEW

**Comment by wonzhq** [comment]
I can't see what is wrong in the log file of 'run-make-check.sh'. Can someone point out to me?

**Comment by tchaikov** [comment]
@wonzhq  maybe it timed out? run-make-check.sh should `make dist` before it returns.

the log file was truncated. so i can hardly tell which test suite took the most time, but very likely the last one.
```
run: 46: return 1
main: 120: code=1
main: 122: teardown testdir/test-erasure-code
```

**Comment by dachary** [comment]
@tchaikov is right @wonzhq the tests timed out, the last line of the output is:
<pre>
abort by timeout after 1h
</pre>
the log is too large to be displayed and I suggest you try to run **make -j4 check** locally (assuming you have a 4 core CPU it will speed up tests) and see for yourself which test hangs.

**Comment by liewegas** [comment]
the other patches look right to me, but we'll need to fix make check and then test carefully (esp the new assert).

**Comment by wonzhq** [comment]
Thanks @tchaikov @dachary @liewegas 
I'll run the make check locally.

**Comment by wonzhq** [comment]
Looks like the assertion "repop->nref == 1" in remove_repop is causing the trouble. I haven't found why the assertion fails yet. I've removed that commit from this PR, and it should be ok now.

**Comment by liewegas** [comment]
Looks good, thanks. Let us know when you figure out what is triggering that assert as it sounds suspicious

**Comment by wonzhq** [comment]
@liewegas The "repop->nref == 1" assertion failure may be caused by the SnapTrimmer. When doing trimming objects, it creates some repops and put it in the set 'repops'. After the replication is applied and committed, they are not removed from the 'repops' set. Instead, they are removed from the 'repops' set in the next trimming or reset. This may cause the assertion failure.

**Comment by wonzhq** [comment]
Does it make sense to remove the snap trimming repop from the 'repops' set of SnapTrimmer when it is applied and committed?

**Comment by athanatos** [comment]
I'd probably just remove the assert.  The interface does not require that the user not be holding another reference to the repop.

**Comment by wonzhq** [comment]
> I'd probably just remove the assert. The interface does not require that the user not be holding another reference to the repop.

This is ok to me. I just thought it would be better to reclaim the repop after done its work, instead of waiting for the next trimming or reset.

**Comment by liewegas** [comment]
manual merge to hammer

**Pull request closed without merging**
