### PR TITLE
kraken: rgw: fix use of marker in List::list_objects()

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/19047

### CODE REVIEW

**Comment by smithfarm** [comment]
```
ceph_test_objectstore: /home/jenkins-build/build/workspace/ceph-pull-requests/src/test/objectstore/store_test.cc:3147: virtual void SyntheticWorkloadState::C_SyntheticOnReadable::finish(int): Assertion `bl_eq(state->contents[hoid].data, r2)' failed.
```

Some kind of fix is missing.

**Comment by tchaikov** [comment]
this is also a known issue. the tracker is not accessible at this moment. will update you with the ticket id later on.

**Comment by smithfarm** [comment]
@tchaikov http://tracker.ceph.com/issues/18027 I presume

**Comment by smithfarm** [comment]
Jenkins re-test this please

**Comment by tchaikov** [comment]
@smithfarm yeah, which points to http://tracker.ceph.com/issues/17743

**Comment by smithfarm** [comment]
```
119/156 Test #126: unittest_bit_alloc ......................***Exception: Other  0.80 sec
2017-07-03 14:00:31.709242 7f3cb5a95080 -1 did not load config file, using default settings.
[==========] Running 6 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 6 tests from BitAllocator
[ RUN      ] BitAllocator.test_bmap_iter
[       OK ] BitAllocator.test_bmap_iter (1 ms)
[ RUN      ] BitAllocator.test_bmap_entry
[       OK ] BitAllocator.test_bmap_entry (0 ms)
[ RUN      ] BitAllocator.test_zone_alloc
0
1
[       OK ] BitAllocator.test_zone_alloc (10 ms)
[ RUN      ] BitAllocator.test_bmap_alloc
[       OK ] BitAllocator.test_bmap_alloc (41 ms)
[ RUN      ] BitAllocator.test_bmap_alloc2
[       OK ] BitAllocator.test_bmap_alloc2 (1 ms)
[ RUN      ] BitAllocator.test_bmap_alloc_concurrent
Spawning 16 threads for parallel test. Mode Cont = 0.....
Starting thread 0Starting thread 1Starting thread 2Starting thread 3Starting thread 4Starting thread 5Starting thread 6Starting thread 7Starting thread 8Starting thread 9Starting thread 10Starting thread 11Starting thread 12Starting thread 13Starting thread 14Starting thread 15Spawning 16 threads for parallel test. Mode Cont = 1.....
Starting thread 16Starting thread 17Starting thread 18Starting thread 19Starting thread 20Starting thread 21Starting thread 22Starting thread 23Starting thread 24Starting thread 25Starting thread 26Starting thread 27Starting thread 28Starting thread 29Starting thread 30Starting thread 31/home/jenkins-build/build/workspace/ceph-pull-requests/src/os/bluestore/BitAllocator.cc: In function 'void BitAllocator::free_blocks_dis(int64_t, ExtentList*)' thread 7f3cb09cc700 time 2017-07-03 14:00:31.975749
/home/jenkins-build/build/workspace/ceph-pull-requests/src/os/bluestore/BitAllocator.cc: 1504: FAILED assert(get_used_blocks() >= 0)
 ceph version 11.2.0-383-g4ba36fb (4ba36fba4b341799c0c260bfe76f091d639b81e3)
 1: (ceph::__ceph_assert_fail(char const*, char const*, int, char const*)+0x79) [0x55a0eb9a5989]
 2: (()+0x142c74) [0x55a0eb98fc74]
 3: (do_work_dis(BitAllocator*)+0x12f) [0x55a0eb9616bf]
 4: (worker(void*)+0x34) [0x55a0eb961904]
 5: (()+0x76ba) [0x7f3cb56716ba]
 6: (clone()+0x6d) [0x7f3cb3ce93dd]
 NOTE: a copy of the executable, or `objdump -rdS <executable>` is needed to interpret this.
2017-07-03 14:00:32.006505 7f3cb09cc700 -1 /home/jenkins-build/build/workspace/ceph-pull-requests/src/os/bluestore/BitAllocator.cc: In function 'void BitAllocator::free_blocks_dis(int64_t, ExtentList*)' thread 7f3cb09cc700 time 2017-07-03 14:00:31.975749
/home/jenkins-build/build/workspace/ceph-pull-requests/src/os/bluestore/BitAllocator.cc: 1504: FAILED assert(get_used_blocks() >= 0)

 ceph version 11.2.0-383-g4ba36fb (4ba36fba4b341799c0c260bfe76f091d639b81e3)
 1: (ceph::__ceph_assert_fail(char const*, char const*, int, char const*)+0x79) [0x55a0eb9a5989]
 2: (()+0x142c74) [0x55a0eb98fc74]
 3: (do_work_dis(BitAllocator*)+0x12f) [0x55a0eb9616bf]
 4: (worker(void*)+0x34) [0x55a0eb961904]
 5: (()+0x76ba) [0x7f3cb56716ba]
 6: (clone()+0x6d) [0x7f3cb3ce93dd]
 NOTE: a copy of the executable, or `objdump -rdS <executable>` is needed to interpret this.

--- begin dump of recent events ---
   -16> 2017-07-03 14:00:31.708888 7f3cb5a95080  5 asok(0x55a0f4ad8000) register_command perfcounters_dump hook 0x55a0f4aa4050
   -15> 2017-07-03 14:00:31.708913 7f3cb5a95080  5 asok(0x55a0f4ad8000) register_command 1 hook 0x55a0f4aa4050
   -14> 2017-07-03 14:00:31.708917 7f3cb5a95080  5 asok(0x55a0f4ad8000) register_command perf dump hook 0x55a0f4aa4050
   -13> 2017-07-03 14:00:31.708922 7f3cb5a95080  5 asok(0x55a0f4ad8000) register_command perfcounters_schema hook 0x55a0f4aa4050
   -12> 2017-07-03 14:00:31.708956 7f3cb5a95080  5 asok(0x55a0f4ad8000) register_command 2 hook 0x55a0f4aa4050
   -11> 2017-07-03 14:00:31.708968 7f3cb5a95080  5 asok(0x55a0f4ad8000) register_command perf schema hook 0x55a0f4aa4050
   -10> 2017-07-03 14:00:31.708972 7f3cb5a95080  5 asok(0x55a0f4ad8000) register_command perf reset hook 0x55a0f4aa4050
    -9> 2017-07-03 14:00:31.708976 7f3cb5a95080  5 asok(0x55a0f4ad8000) register_command config show hook 0x55a0f4aa4050
    -8> 2017-07-03 14:00:31.708983 7f3cb5a95080  5 asok(0x55a0f4ad8000) register_command config set hook 0x55a0f4aa4050
    -7> 2017-07-03 14:00:31.708987 7f3cb5a95080  5 asok(0x55a0f4ad8000) register_command config get hook 0x55a0f4aa4050
    -6> 2017-07-03 14:00:31.708992 7f3cb5a95080  5 asok(0x55a0f4ad8000) register_command config diff hook 0x55a0f4aa4050
    -5> 2017-07-03 14:00:31.708999 7f3cb5a95080  5 asok(0x55a0f4ad8000) register_command log flush hook 0x55a0f4aa4050
    -4> 2017-07-03 14:00:31.709002 7f3cb5a95080  5 asok(0x55a0f4ad8000) register_command log dump hook 0x55a0f4aa4050
    -3> 2017-07-03 14:00:31.709005 7f3cb5a95080  5 asok(0x55a0f4ad8000) register_command log reopen hook 0x55a0f4aa4050
    -2> 2017-07-03 14:00:31.709017 7f3cb5a95080  5 asok(0x55a0f4ad8000) register_command dump_mempools hook 0x55a0f4aac428
    -1> 2017-07-03 14:00:31.709242 7f3cb5a95080 -1 did not load config file, using default settings.
```

**Comment by smithfarm** [comment]
Jenkins re-test this please

**Comment by smithfarm** [comment]
@yehudasa @mattbenjamin @oritwas @cbodley @rzarzynski This PR passed an rgw suite at http://tracker.ceph.com/issues/19009#note-60 and, provided there are no objections, I'll merge it as soon as it gets a positive review from one of you.

**Pull request merged**
