### PR TITLE
rgw: allow enforcing of maximum requested in listing when possible

### PR DESCRIPTION
**Pull request by ivancich**
Some Swift clients assume that the number of items requested in a bucket listing will be returned if possible. This allows the underlying code to enfore that behavior, so Swift can get that behavior, but S3 does not have to.

Tracker: https://tracker.ceph.com/issues/44554

### CODE REVIEW

**Comment by matthewoliver** [comment]
Yeah the swift API and therefore clients I've seen expect up to the max container listing limit of a single req (10 000, but configurable), clients should see this value from the /info call.
If < max is returned, it's assumed we have it all, if == max, then there could be more, so client paginate.

Obivously there is also prefix, marker, end_marker, and reverse which changes potential output, but still that's up to the client to use and understand. (ie, prefix for psudo containers, or marker/end_marker to paginate by some bounds).

**Comment by ivancich** [comment]
@matthewoliver Thank you for weighing in.

I wish this API documentation were more clear:  [Swift API documentation](https://docs.openstack.org/api-ref/object-store/?expanded=show-container-details-and-list-objects-detail#show-container-details-and-list-objects)

**Comment by matthewoliver** [comment]
Let me see what I can do re: Swift api on the Swift side :)

**Comment by ivancich** [comment]
@mattbenjamin This now has both commits.

**Comment by cbodley** [comment]
> Yeah the swift API and therefore clients I've seen expect up to the max container listing limit of a single req (10 000, but configurable), clients should see this value from the /info call.

we advertise this value of `RGW_LIST_BUCKETS_LIMIT_MAX=10000` in the swift /info api here:
```c++
void RGWInfo_ObjStore_SWIFT::list_swift_data(Formatter& formatter,
                                              const ConfigProxy& config,
                                              RGWRados& store)
{ 
  formatter.open_object_section("swift");
  formatter.dump_int("max_file_size", config->rgw_max_put_size);
  formatter.dump_int("container_listing_limit", RGW_LIST_BUCKETS_LIMIT_MAX);
```
i think we should return the value of `rgw_max_listing_results` here, and use that value for `RGWListBucket_ObjStore_SWIFT::default_max` as well. then we don't need to change the semantics of `parse_value_and_bound()`, which is used elsewhere

**Comment by ivancich** [comment]
> we advertise this value of `RGW_LIST_BUCKETS_LIMIT_MAX=10000` in the swift /info api here:
> 
> ```c++
> void RGWInfo_ObjStore_SWIFT::list_swift_data(Formatter& formatter,
>                                               const ConfigProxy& config,
>                                               RGWRados& store)
> { 
>   formatter.open_object_section("swift");
>   formatter.dump_int("max_file_size", config->rgw_max_put_size);
>   formatter.dump_int("container_listing_limit", RGW_LIST_BUCKETS_LIMIT_MAX);
> ```
> 
> i think we should return the value of `rgw_max_listing_results` here, and use that value for `RGWListBucket_ObjStore_SWIFT::default_max` as well. then we don't need to change the semantics of `parse_value_and_bound()`, which is used elsewhere

The challenge is that rgw_max_listing_results is set to 1000, which works well for S3. However, the swift api specifies that 10,000 objects are returned when that many can be returned (see: https://docs.openstack.org/api-ref/object-store/?expanded=show-container-details-and-list-objects-detail). I think technically we'd be OK as long as we "advertise" that value, but that might be problematic with users.

But ... clients might assume that without configuration changes they'll get 10,000 back.

And ... how would we configure an RGW installation with both s3 and swift users, such that s3 users get 1,000 and swift users get 10,000 entries?

**Comment by ivancich** [comment]
QA Results:
http://pulpito.ceph.com/ivancich-2020-05-08_18:24:50-rgw-wip-eric-testing-distro-basic-smithi/
http://pulpito.ceph.com/ivancich-2020-05-08_18:25:10-rgw-wip-eric-testing-distro-basic-smithi/

Any failures  are from other sources and do not represent regressions.

**Comment by ivancich** [comment]
jenkins test make check

**Comment by ivancich** [comment]
@cbodley : did I address your concerns adequately in https://github.com/ceph/ceph/pull/33864#issuecomment-626013578 ? If not, can we talk in order to move this PR forward?

**Comment by smithfarm** [comment]
jenkins test make check

**Pull request closed without merging**
