### PR TITLE
mon/LogMonitor, MgrStat: Report logm and mgrstat committed version

### PR DESCRIPTION
**Pull request by pdvian**
Only way to get the first and last committed version for logm and
mgrstat is through the monstore db dump. Reporting first and last
committed version for logm and mgrstat in ceph report will help in
debugging monstore is too big issues.

Signed-off-by: Prashant D <pdhange@redhat.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/master/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [x] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Review by ljflores — APPROVED** [review]
Works as expected on a vstart cluster.
```
[lflores@folio01 build]$ ./bin/ceph report
{
    "cluster_fingerprint": "44f404d9-480a-4c9b-ac3f-d46c1da1e9ae",
    "version": "17.0.0-12482-ga91be6fb581",
    "commit": "a91be6fb581c01db75cf19d636aacdab44fef960",
    "timestamp": "2022-05-25T18:52:04.692160+0000",
    "tag": "",
    "health": {
        "status": "HEALTH_OK",
        "checks": {},
        "mutes": []
    },

...

    "mgrstat_first_committed": 1,
    "mgrstat_last_committed": 148,
    "logm_first_committed": 1,
    "logm_last_committed": 271,
    "paxos": {
        "first_committed": 1,
        "last_committed": 572,
        "last_pn": 200,
        "accepted_pn": 200
    }
}
report 2050060982
```

**Comment by sseshasa** [comment]
**Teuthology Test Result:**

http://pulpito.front.sepia.ceph.com/yuriw-2022-06-13_16:36:31-rados-wip-yuri7-testing-2022-06-13-0706-distro-default-smithi/
Found no related Failures

**Comment by ljflores** [comment]
http://pulpito.front.sepia.ceph.com/yuriw-2022-06-13_16:36:31-rados-wip-yuri7-testing-2022-06-13-0706-distro-default-smithi/

Failures, unrelated:
    1. https://tracker.ceph.com/issues/55986
    2. https://tracker.ceph.com/issues/52321
    3. https://tracker.ceph.com/issues/52124
    4. https://tracker.ceph.com/issues/52316
    5. https://tracker.ceph.com/issues/55322
    6. https://tracker.ceph.com/issues/55741
    7. https://tracker.ceph.com/issues/56034 --> new Tracker; unrelated to the PRs in this run.

Details:
    1. cephadm: Test failure: test_cluster_set_reset_user_config (tasks.cephfs.test_nfs.TestNFS) - Ceph - Orchestrator
    2. qa/tasks/rook times out: 'check osd count' reached maximum tries (90) after waiting for 900 seconds - Ceph - Orchestrator
    3. Invalid read of size 8 in handle_recovery_delete() - Ceph - RADOS
    4. qa/tasks/mon_thrash.py: _do_thrash AssertionError len(s['quorum']) == len(mons) - Ceph - RADOS
    5. test-restful.sh: mon metadata unable to be retrieved - Ceph - Mgr
    6. cephadm/test_dashboard_e2e.sh: Unable to find element `cd-modal .custom-control-label` when testing on orchestrator/01-hosts.e2e-spec.ts - Ceph - Mgr - Dashboard
    7. qa/standalone/osd/divergent-priors.sh fails in test TEST_divergent_3() - Ceph - RADOS

**Comment by yuriw** [comment]
jenkins test this please

**Comment by ljflores** [comment]
jenkins test make check

**Comment by ljflores** [comment]
jenkins test make check arm64

**Comment by ljflores** [comment]
jenkins test make check arm64

**Pull request merged**
