### PR TITLE
OSD: drop parameter t from merge_log()

### PR DESCRIPTION
**Pull request by xiexingguo**
which is not necessary.

Signed-off-by: xie xingguo <xie.xingguo@zte.com.cn>

### CODE REVIEW

**Comment by gregsfortytwo** [comment]
Can you fix the build error? I assume it's just a test which also passes in the old Parma.

**Comment by xiexingguo** [comment]
Sure. Repushed, let's wait and see.

**Comment by shinobu-x** [comment]
@athanatos Would you be able to review this PR?

**Comment by gregsfortytwo** [comment]
Needs to get run through somebody's test suite but looks good. :)

**Comment by yuriw** [comment]
http://pulpito.ceph.com/yuriw-2017-03-18_00:03:11-rados-wip-yuri-testing2_2017_3_18-distro-basic-smithi/

http://pulpito.ceph.com/yuriw-2017-03-18_15:53:35-rados-wip-yuri-testing2_2017_3_18---basic-smithi/

100% tests passed, 0 tests failed out of 163

**Pull request merged**
