### PR TITLE
RGW - Don't create empty obj in webdir

### PR DESCRIPTION
**Pull request by dang**
Zipper objects shouldn't be empty, but should instead be null.  Fix this
case where parsing wasn't checking for empty object name, and the
website code that uses it.

Fixes: https://tracker.ceph.com/issues/48049

Signed-off-by: Daniel Gryniewicz <dang@redhat.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Review by cbodley — APPROVED** [review]

**Comment by dang** [comment]
Teuthology passes: 
https://pulpito.ceph.com/dang-2020-11-12_10:25:06-rgw-wip-dang-webdir-empty-object-distro-basic-smithi/

**Comment by dang** [comment]
jenkins test make check

**Comment by cbodley** [comment]
@dang there seem to be some unrelated commits in this branch

**Review by cbodley — APPROVED** [review]

**Comment by cbodley** [comment]
jenkins test make check

**Pull request merged**
