### PR TITLE
cephadm: podman inspect: image field was called `ImageID`

### PR DESCRIPTION
**Pull request by sebastian-philipp**
cephadm: podman inspect: image field was called `ImageID`

See https://github.com/containers/libpod/pull/4195

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by tchaikov** [comment]
```
2020-01-14T13:45:58.124 INFO:teuthology.orchestra.run.smithi154.stderr:INFO:cephadm:Pulling latest quay.io/ceph-ci/ceph:14f3faf4468b8c47b33d0b6da91a917d2e032c60 container...
2020-01-14T13:45:59.772 INFO:teuthology.orchestra.run.smithi154.stderr:INFO:cephadm:Non-zero exit code 125 from /bin/podman pull quay.io/ceph-ci/ceph:14f3faf4468b8c47b33d0b6da91a917d2e032c60
2020-01-14T13:45:59.773 INFO:teuthology.orchestra.run.smithi154.stderr:INFO:cephadm:/bin/podman:stderr Trying to pull quay.io/ceph-ci/ceph:14f3faf4468b8c47b33d0b6da91a917d2e032c60...time="2020-01-14T13:45:59Z" level=error msg="Error pulling image ref //quay.io/ceph-ci/cep
h:14f3faf4468b8c47b33d0b6da91a917d2e032c60: Error initializing source docker://quay.io/ceph-ci/ceph:14f3faf4468b8c47b33d0b6da91a917d2e032c60: Error reading manifest 14f3faf4468b8c47b33d0b6da91a917d2e032c60 in quay.io/ceph-ci/ceph: manifest unknown: manifest unknown"
2020-01-14T13:45:59.773 INFO:teuthology.orchestra.run.smithi154.stderr:INFO:cephadm:/bin/podman:stderr Failed
2020-01-14T13:45:59.773 INFO:teuthology.orchestra.run.smithi154.stderr:INFO:cephadm:/bin/podman:stderr Error: error pulling image "quay.io/ceph-ci/ceph:14f3faf4468b8c47b33d0b6da91a917d2e032c60": unable to pull quay.io/ceph-ci/ceph:14f3faf4468b8c47b33d0b6da91a917d2e032c60:
 unable to pull image: Error initializing source docker://quay.io/ceph-ci/ceph:14f3faf4468b8c47b33d0b6da91a917d2e032c60: Error reading manifest 14f3faf4468b8c47b33d0b6da91a917d2e032c60 in quay.io/ceph-ci/ceph: manifest unknown: manifest unknown
2020-01-14T13:45:59.776 INFO:teuthology.orchestra.run.smithi154.stderr:Traceback (most recent call last):
2020-01-14T13:45:59.776 INFO:teuthology.orchestra.run.smithi154.stderr:  File "/home/ubuntu/cephtest/cephadm", line 2695, in <module>
2020-01-14T13:45:59.776 INFO:teuthology.orchestra.run.smithi154.stderr:    r = args.func()
2020-01-14T13:45:59.776 INFO:teuthology.orchestra.run.smithi154.stderr:  File "/home/ubuntu/cephtest/cephadm", line 1508, in command_bootstrap
2020-01-14T13:45:59.776 INFO:teuthology.orchestra.run.smithi154.stderr:    call_throws([container_path, 'pull', args.image])
2020-01-14T13:45:59.777 INFO:teuthology.orchestra.run.smithi154.stderr:  File "/home/ubuntu/cephtest/cephadm", line 462, in call_throws
2020-01-14T13:45:59.777 INFO:teuthology.orchestra.run.smithi154.stderr:    raise RuntimeError('Failed command: %s' % ' '.join(command))
2020-01-14T13:45:59.777 INFO:teuthology.orchestra.run.smithi154.stderr:RuntimeError: Failed command: /bin/podman pull quay.io/ceph-ci/ceph:14f3faf4468b8c47b33d0b6da91a917d2e032c60
2020-01-14T13:45:59.798 DEBUG:teuthology.orchestra.run:got remote process result: 1
```


http://pulpito.ceph.com/kchai-2020-01-14_13:07:57-rados-wip-kefu-testing-2020-01-14-1719-distro-basic-smithi/

not sure if it's related.

**Comment by sebastian-philipp** [comment]
> podman pull

should not be affected by my PR. Nevertheless, seems we have an issue with the pushed imaged to quay.io. cc @dmick @liewegas

**Comment by sebastian-philipp** [comment]
- [ ] http://pulpito.ceph.com/swagner-2020-01-20_14:55:57-rados-wip-swagner-testing-distro-basic-smithi/ (still in progress)

**Comment by sebastian-philipp** [comment]
```
Traceback (most recent call last):
  File "/tmp/tmp.v5oGIl53or/cephadm", line 2823, in <module>
    r = args.func()
  File "/tmp/tmp.v5oGIl53or/cephadm", line 2129, in command_ls
    legacy_dir=args.legacy_dir)
  File "/tmp/tmp.v5oGIl53or/cephadm", line 2197, in list_daemons
    if 'podman' in container_path and get_podman_version() < [1, 6, 2]:
  File "/tmp/tmp.v5oGIl53or/cephadm", line 604, in get_podman_version
    return list(map(int, version_str.split('.')))
ValueError: invalid literal for int() with base 10: '2-stable2'
```

**Comment by liewegas** [comment]
retest this please

**Comment by liewegas** [comment]
tests pass http://pulpito.ceph.com/sage-2020-01-23_15:28:05-rados-wip-sage-testing-2020-01-22-2146-distro-basic-smithi/

**Comment by sebastian-philipp** [comment]
> Couple of suggestions:
> 
> [sebastian-philipp/ceph@cephadm-fix-ls-podman-inspect...mgfritch:cephadm-fix-ls-podman-inspect-gotemp](https://github.com/sebastian-philipp/ceph/compare/cephadm-fix-ls-podman-inspect...mgfritch:cephadm-fix-ls-podman-inspect-gotemp)
> 
> 1. Using a GoTemplate instead of parsing stdout is simpler and probably more reliable

Thanks! Didn't knew that `podman version --format '{{.Version}}'` exist. That would have been obliviously a better choice.

> 2. Generally, I think `cephadm ls` should succeed, even if there is a failure to query an single attribute.
> 
> Worst case would look as follows:
> 
> ```
>     {
>         "style": "cephadm:v1",
>         "name": "mgr.kiqjft",
>         "fsid": "c027e61c-3d28-11ea-bb8a-525400fdaffd",
>         "enabled": true,
>         "state": "running",
>         "container_id": null,
>         "container_image_name": null,
>         "container_image_id": null,
>         "version": null
>     }
> ```
Yeah we had that already. Returning just the name is about as buggy as simply giving up.

**Pull request merged**
