### PR TITLE
common/TrackedOp: fix osd reboot optracker coredump

### PR DESCRIPTION
**Pull request by zhouyh-orcadt**
common/TrackedOp: fix osd reboot optracker coredump

Signed-off-by: zhouyh-orcadt <yaohui.zhou@orcadt.com>
https://tracker.ceph.com/issues/44715 

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by sebastian-philipp** [comment]
The DCO is still missing in the commit message. You run this to fix this:

```
git commit --amend -s 
git push -f
```

**Comment by neha-ojha** [comment]
@zhouyh-orcadt We've already fixed the osd shutdown issue, see https://tracker.ceph.com/issues/42347#note-8. Just curious if you observed this is on the osd or on the mon?

**Comment by zhouyh-orcadt** [comment]
> @zhouyh-orcadt We've already fixed the osd shutdown issue, see https://tracker.ceph.com/issues/42347#note-8. Just curious if you observed this is on the osd or on the mon?

The problem I encountered was the coredump of osd service stop.
But I noticed that the osd and mon services are all related to the processing of OpTracker. When they are destructing, they all judge whether the sub-list of sharded_in_flight_list is empty. If it is not empty, you need to release the elements in the sub-list.

**Comment by neha-ojha** [comment]
@sebastian-philipp I am unable to find a reproducer for the issue this PR is fixing, see https://tracker.ceph.com/issues/44715#note-13. Are you still seeing it?

**Comment by sebastian-philipp** [comment]
let me come back to you when I create the next cephadm backport PR

**Comment by tchaikov** [comment]
- http://pulpito.ceph.com/kchai-2020-06-02_10:41:24-rados-wip-kefu-testing-2020-06-02-1412-distro-basic-smithi/
- http://pulpito.ceph.com/kchai-2020-06-03_13:01:39-rados-wip-kefu-testing-2020-06-02-1412-1-distro-basic-smithi/

the failures are not related.

**Comment by tchaikov** [comment]
@jdurgin good to merge?

**Comment by sebastian-philipp** [comment]
ok I haven't seen the crash in latest octopus!

**Comment by neha-ojha** [comment]
> @jdurgin good to merge?

@tchaikov see https://github.com/ceph/ceph/pull/34624#issuecomment-631089923, we should reproduce the original bug before merging this fix.

**Comment by tchaikov** [comment]
@neha-ojha i am adding DNM then.

**Comment by neha-ojha** [comment]
I think we should revisit this PR, given the reports coming from telemetry https://tracker.ceph.com/issues/44715#note-17

**Pull request merged**
