### PR TITLE
mgr/dashboard: Update locale en to en-US to match transifex

### PR DESCRIPTION
**Pull request by Exotelis**
This pr should sync the transifex source language with the dashboard.
This pr will also update the translations on master.

Signed-off-by: Sebastian Krah <exotelis@mailbox.org>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by s0nea** [comment]
jenkins test make check

**Comment by callithea** [comment]
jenkins test dashboard

**Review by epuertat — CHANGES_REQUESTED** [review]
Thanks @Exotelis! Code-wise looks good to me, but I have a couple of comments:
* could you plz create a tracker and link it here?
* would this need to be backported to octopus/nautilus?

**Review by epuertat — APPROVED** [review]
As discussed with @Exotelis, i18n PRs don't go with tracker issues linked, and they're not meant for backporting. So I'm ok with this then!

**Review by callithea — APPROVED** [review]
Lgtm

**Pull request merged**
