### PR TITLE
OPT_INT option interprets 3221225472 as -1073741824, and crashes in Throttle::Throttle()

### PR DESCRIPTION
**Pull request by theanalyst**
http://tracker.ceph.com/issues/11738

### CODE REVIEW

**Comment by dachary** [comment]
@theanalyst if I'm not mistaken the issue in the pull request description should be http://tracker.ceph.com/issues/11738 instead of http://tracker.ceph.com/issues/11484

**Comment by theanalyst** [comment]
@dachary Both the descriptions look the same to me.. though I guess it should have been #4994 's title

**Comment by dachary** [comment]
I mean https://github.com/ceph/ceph/pull/4889#issue-85878829 should be http://tracker.ceph.com/issues/11738  right ?

**Comment by theanalyst** [comment]
Yes.. sorry.. updated

**Comment by theanalyst** [comment]
@athanatos / @tchaikov this has passed the first round of integration tests for hammer backports at http://tracker.ceph.com/issues/11990#rados Do you think it is ready to merge

**Comment by tchaikov** [comment]
:+1:

**Pull request merged**
