### PR TITLE
doc: Modify the description of "RADOS GATEWAY S3 API COMPLIANCE" on the website

### PR DESCRIPTION
**Pull request by ybwang0211**
doc: Modify the description of "RADOS GATEWAY S3 API COMPLIANCE" on the website

There are a lot of errors in the description of "RADOS GATEWAY S3 API COMPLI
ANCE" on the website, for example, "GET Bucket" is misplaced, and now "GET Bucke
t location" is already supported. In this commit, I mainly revised the content o
f "OPERATIONS ON BUCKETS".

Fixes: http://tracker.ceph.com/issues/45506
Signed-off-by: wangyingbin <wangyingbin@inspur.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by ybwang0211** [comment]
Excuse me, I deleted the previous commit and reopened it as required, please check it.

**Comment by ybwang0211** [comment]
Excuse me, please check if my commit meets the requirements? @tchaikov

**Comment by tchaikov** [comment]
@ybwang0211 could you reference the close PR? what you mean by "requirements". if what you mean is the "build check" of doc, then, yes, the doc can be rendered by sphinx w/o issues now.

**Comment by ybwang0211** [comment]
> @ybwang0211 could you reference the closed PR? what you mean by "requirements". if what you mean is the "build check" of doc, then, yes, the doc can be rendered by sphinx w/o issues now.

About the last commits, when I squashed them into a single one, I closed them by accident,Sorry. So I submitted this again, the content is exactly the same as the last commits.
and how to render the doc by sphinx w/o issues?

**Comment by tchaikov** [comment]
@ybwang0211 i mean, i don't have any concern regarding the formatting now.

**Comment by ybwang0211** [comment]
> @ybwang0211 i mean, i don't have any concern regarding the formatting now.

So, what should I do now?
(And this is my first time working on GitHub, so I'm not familiar with the operation. Thank you for your guidance.)

**Comment by ybwang0211** [comment]
Please check my commit！

**Review by anthonyeleven — CHANGES_REQUESTED** [review]
I'll have to defer to @tchaikov , @mattbenjamin , @cbodley et all re the actual content, but please do modify the commit and PR messages to conform to our preferred format, something like:

`doc/dev/radosgw: Modify code links for RGW S3 API compliance`

Apologies that this PR fell through the cracks.  Our tagging and documentation PR review processes are better now, and we're circling back to existing PRs.

**Pull request closed without merging**
