### PR TITLE
doc/rados/operations: Fix off-by-one erors in control.rst

### PR DESCRIPTION
**Pull request by tobydarling**
doc/rados/operations: Fix off-by-one errors in control.rst

The description of the commands was after the commands themselves, not before

Signed-off-by: tobydarling <anothercoffee@gmail.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [x] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [x] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Comment by anthonyeleven** [comment]
Nice catch!  Thanks for contributing.

I can merge after a couple of tweaks:

* Commits and the PR description must have be signed-off-by
* Commit and PR titles should be like "doc/rados/operations: Fix off-by-one erors in control.rst"


https://docs.ceph.com/en/quincy/start/documenting-ceph/#commit-the-change

**Comment by tobydarling** [comment]
Sorry, gonna expose my novice git status here, I'm not sure how to fix the signed-off-by in the PR. It looks to be set in the commit. I think I've fixed the titles.

**Comment by anthonyeleven** [comment]
In the UI you click the `...` dropdown menu next to `tobydarling commented 13 hours ago edited` and edit in the signed-off-by.

The commit has that, but the commit message should match the PR message.

I would do that by running `git commit --amend` in my local checkout and editing the message, then `git push -f` it up.

**Comment by tobydarling** [comment]
Thanks for the pointer, I'm still not certain I've got this right, but I've pushed again

**Comment by anthonyeleven** [comment]
jenkins retest this please

**Comment by anthonyeleven** [comment]
Looks good to me now, just need to get the tests to pass before I can merge.

The nitpicking may seem well nitpicky but it quickly becomes second nature.  I'm in the habit of using `git commit -sm` to sign everything.

**Comment by anthonyeleven** [comment]
jenkins retest this please

**Comment by anthonyeleven** [comment]
@zdover23 I fear that Jenkins is broken

**Comment by anthonyeleven** [comment]
jenkins retest this please

**Review by anthonyeleven — APPROVED** [review]

**Comment by zdover23** [comment]
> @zdover23 I fear that Jenkins is broken

@anthonyeleven and to posterity: This has been followed up on as much as it possibly can be at 18:27 UTC on a Saturday. I will update this conversation when I know what can be done to address the 403 error and the seemingly out-of-date version of Sphinx.

**Comment by anthonyeleven** [comment]
jenkins retest this please

**Comment by zdover23** [comment]
https://github.com/ceph/ceph/pull/55231 - Reef backport
https://github.com/ceph/ceph/pull/55232 - Quincy backport

**Pull request merged**
