### PR TITLE
nautilus: mgr: drop session with Ceph daemon when not ready 

### PR DESCRIPTION
**Pull request by smithfarm**
backport tracker: https://tracker.ceph.com/issues/43046

---

backport of https://github.com/ceph/ceph/pull/31899
parent tracker: https://tracker.ceph.com/issues/43037

this backport was staged using ceph-backport.sh version 15.0.0.6950
find the latest version at https://github.com/ceph/ceph/blob/master/src/script/ceph-backport.sh

### CODE REVIEW

**Comment by yuriw** [comment]
[wip-yuri-testing-2019-12-09-1618-nautilus](https://trello.com/c/MSxcU6h6/775-wip-yuri-testing-2019-12-09-1618-nautilus)

**Comment by yuriw** [comment]
[wip-yuri4-testing-2019-12-16-2243-nautilus](https://trello.com/c/DLDDntxo/782-wip-yuri4-testing-2019-12-16-2243-nautilus)

**Comment by yuriw** [comment]
[wip-yuri4-testing-2019-12-20-1958-nautilus](https://trello.com/c/uuj2DM6o/787-wip-yuri4-testing-2019-12-20-1958-nautilus)

**Comment by yuriw** [comment]
@smithfarm we see unusually high number of failed jobs compared to other runs an.  d suspect it caused by this PR, pls advice 
https://trello.com/c/uuj2DM6o

**Comment by yuriw** [comment]
@smithfarm ping

**Comment by yuriw** [comment]
@smithfarm @neha-ojha reran and still to many failed 
http://pulpito.ceph.com/yuriw-2020-01-13_23:58:22-rados-wip-yuri4-testing-2020-01-13-2017-nautilus-distro-basic-smithi

pls see why

**Comment by smithfarm** [comment]
@yuriw Presumably there is one or more qa/test PRs/commits that need to be cherry-picked as well?

**Comment by smithfarm** [comment]
somehow I didn't see https://github.com/ceph/ceph/pull/31905 - sorry!

**Pull request closed without merging**
