### PR TITLE
client: don't choose dirfrag when opendir

### PR DESCRIPTION
**Pull request by ukernel**
When the directory is fragmented, choosing dirfrag makes dir_result_t::offset
non-zero. This results missing '.' and '..' in readdir result.

Signed-off-by: Yan, Zheng <zyan@redhat.com>

### CODE REVIEW

**Comment by gregsfortytwo** [comment]
Hmm, this doesn't seem to fix the bug LibCephFS.DirLs failure that I presume prompted it. We're still off by one:

>2015-11-24T16:55:13.929 INFO:tasks.workunit.client.0.plana52.stdout:[ RUN      ] LibCephFS.DirLs
2015-11-24T16:55:25.651 INFO:teuthology.orchestra.run.plana04:Running: 'sudo logrotate /etc/logrotate.d/ceph-test.conf'
2015-11-24T16:55:25.655 INFO:teuthology.orchestra.run.plana52:Running: 'sudo logrotate /etc/logrotate.d/ceph-test.conf'
2015-11-24T16:55:55.698 INFO:teuthology.orchestra.run.plana04:Running: 'sudo logrotate /etc/logrotate.d/ceph-test.conf'
2015-11-24T16:55:55.702 INFO:teuthology.orchestra.run.plana52:Running: 'sudo logrotate /etc/logrotate.d/ceph-test.conf'
2015-11-24T16:56:12.715 INFO:tasks.workunit.client.0.plana52.stdout:rand: 3397
2015-11-24T16:56:12.715 INFO:tasks.workunit.client.0.plana52.stdout:test/libcephfs/test.cc:304: Failure
2015-11-24T16:56:12.715 INFO:tasks.workunit.client.0.plana52.stdout:Value of: entries[i].first
2015-11-24T16:56:12.715 INFO:tasks.workunit.client.0.plana52.stdout:  Actual: "dirf1001"
2015-11-24T16:56:12.715 INFO:tasks.workunit.client.0.plana52.stdout:Expected: result->d_name
2015-11-24T16:56:12.715 INFO:tasks.workunit.client.0.plana52.stdout:Which is: "dirf1000"
2015-11-24T16:56:12.716 INFO:tasks.workunit.client.0.plana52.stdout:[  FAILED  ] LibCephFS.DirLs (58786 ms)

http://pulpito.ceph.com/ubuntu-2015-11-24_12:55:44-fs-greg-fs-verify---basic-multi/1158585

**Comment by ukernel** [comment]
On Thu, Nov 26, 2015 at 5:54 AM, Gregory Farnum <notifications@github.com>
wrote:

> Hmm, this doesn't seem to fix the bug LibCephFS.DirLs failure that I
> presume prompted it. We're still off by one:
>
> 2015-11-24T16:55:13.929 INFO:tasks.workunit.client.0.plana52.stdout:[ RUN
> ] LibCephFS.DirLs
> 2015-11-24T16:55:25.651 INFO:teuthology.orchestra.run.plana04:Running:
> 'sudo logrotate /etc/logrotate.d/ceph-test.conf'
> 2015-11-24T16:55:25.655 INFO:teuthology.orchestra.run.plana52:Running:
> 'sudo logrotate /etc/logrotate.d/ceph-test.conf'
> 2015-11-24T16:55:55.698 INFO:teuthology.orchestra.run.plana04:Running:
> 'sudo logrotate /etc/logrotate.d/ceph-test.conf'
> 2015-11-24T16:55:55.702 INFO:teuthology.orchestra.run.plana52:Running:
> 'sudo logrotate /etc/logrotate.d/ceph-test.conf'
> 2015-11-24T16:56:12.715 INFO:tasks.workunit.client.0.plana52.stdout:rand:
> 3397
> 2015-11-24T16:56:12.715
> INFO:tasks.workunit.client.0.plana52.stdout:test/libcephfs/test.cc:304:
> Failure
> 2015-11-24T16:56:12.715 INFO:tasks.workunit.client.0.plana52.stdout:Value
> of: entries[i].first
> 2015-11-24T16:56:12.715 INFO:tasks.workunit.client.0.plana52.stdout:
> Actual: "dirf1001"
> 2015-11-24T16:56:12.715
> INFO:tasks.workunit.client.0.plana52.stdout:Expected: result->d_name
> 2015-11-24T16:56:12.715 INFO:tasks.workunit.client.0.plana52.stdout:Which
> is: "dirf1000"
> 2015-11-24T16:56:12.716 INFO:tasks.workunit.client.0.plana52.stdout:[
> FAILED ] LibCephFS.DirLs (58786 ms)
>
>
> http://pulpito.ceph.com/ubuntu-2015-11-24_12:55:44-fs-greg-fs-verify---basic-multi/1158585
>
>
this is issue of test case. MDS fragments the dirfrag in the middle test,
so the order of entries change.

**Comment by gregsfortytwo** [comment]
note to self: actually should merge this to Jewel branch if possible

**Comment by gregsfortytwo** [comment]
Hurray, this passed a test branch in master: http://pulpito.ceph.com/gregf-2016-01-05_23:12:08-fs-greg-test-readdir-fix---basic-mira/ The two valgrind failures are an OSD crashing on shutdown (bug 14212), and the dead one is some kind of infrastructure issue.
The LibCephFS.DirLs tests have been reliably failing without this patch (and the unit test fix) so this should give us pretty good confidence.

Merged to the jewel branch as of 088b8c2c881c8561b9bc96934e04d030e8de9255; that will get merged to master shortly.

**Pull request closed without merging**
