### PR TITLE
nautilus: pybind/ceph_volume_client: Update the 'volumes' key to 'subvolumes' in auth-metadata file 

### PR DESCRIPTION
**Pull request by kotreshhr**
-----------------------------
backport tracker: https://tracker.ceph.com/issues/49447

backport of https://github.com/ceph/ceph/pull/39480
parent tracker: https://tracker.ceph.com/issues/49294

------------------------------
backport tracker: https://tracker.ceph.com/issues/49430

backport of https://github.com/ceph/ceph/pull/39572
parent tracker: https://tracker.ceph.com/issues/49374

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by kotreshhr** [comment]
Teuthology Results:

http://pulpito.front.sepia.ceph.com/khiremat-2021-02-24_10:57:06-fs-wip-khiremat-39658-cvc-vol-subvol-nautilus-distro-basic-smithi/

**Comment by ajarr** [comment]
> Teuthology Results:
> 
> http://pulpito.front.sepia.ceph.com/khiremat-2021-02-24_10:57:06-fs-wip-khiremat-39658-cvc-vol-subvol-nautilus-distro-basic-smithi/

I don't see volume_client job run here

**Comment by kotreshhr** [comment]
> > Teuthology Results:
> > http://pulpito.front.sepia.ceph.com/khiremat-2021-02-24_10:57:06-fs-wip-khiremat-39658-cvc-vol-subvol-nautilus-distro-basic-smithi/
> 
> I don't see volume_client job run here

The filter should have been 'volume' instead of 'volumes'. I will re-schedule and attach the results.

**Comment by kotreshhr** [comment]
> > > Teuthology Results:
> > > http://pulpito.front.sepia.ceph.com/khiremat-2021-02-24_10:57:06-fs-wip-khiremat-39658-cvc-vol-subvol-nautilus-distro-basic-smithi/
> > 
> > 
> > I don't see volume_client job run here
> 
> The filter should have been 'volume' instead of 'volumes'. I will re-schedule and attach the results.

http://pulpito.front.sepia.ceph.com/khiremat-2021-02-24_13:50:10-fs-wip-khiremat-39658-cvc-vol-subvol-nautilus-distro-basic-smithi/

**Comment by ajarr** [comment]
@kotreshhr sorry, missed this earlier. But show we cherry-pick this a48ebec0cfc38ba9d218518f9380badc5a23a963
I saw that one of your commits had a conflict as this was not cherry-picked

**Comment by kotreshhr** [comment]
jenkins test api

**Comment by kotreshhr** [comment]
jenkins test api

**Comment by kotreshhr** [comment]
> @kotreshhr I saw that one of your commits had a conflict as this was not cherry-picked. Sorry, missed this earlier. We want to cherry-pick this [a48ebec](https://github.com/ceph/ceph/commit/a48ebec0cfc38ba9d218518f9380badc5a23a963) for py3 fix.

Done.

Teuthology Results:

http://pulpito.front.sepia.ceph.com/khiremat-2021-02-25_08:55:18-fs-wip-khiremat-39658-cvc-vol-subvol-nautilus-1-distro-basic-smithi/

**Review by ajarr — APPROVED** [review]

**Pull request merged**
