### PR TITLE
erasure code: shec performance optimization and bugfix

### PR DESCRIPTION
**Pull request by t-miyamae**
Optimize shec's cpu utilization by intel sse4 and fix some bugs.

This pull request is continuation of #4132.
Hope these commits will be backported to a hammer point release in the near future.

Signed-off-by: Takanori Nakao <nakao.takanori@jp.fujitsu.com>
Signed-off-by: Shotaro Kawaguchi <kawaguchi.s@jp.fujitsu.com>
Signed-off-by: Takeshi Miyamae <miyamae.takeshi@jp.fujitsu.com>

### CODE REVIEW

**Comment by t-miyamae** [comment]
@dachary We added the patch for our teuthology problem.

**Comment by dachary** [comment]
@t-miyamae https://github.com/t-miyamae/ceph/commit/243f0d005b88380c35100806a758ea372e9750f8 is a very significant change. Could you explain what it does ? What was the problem and how did you solve it ? Also please do not include pull requests in the series ( I see 5d1ab8a ).

Thanks !

**Comment by t-miyamae** [comment]
@dachary We assumed that (1) want_to_read and available_chunks does not share osds and (2) osds that are not included in want_to_read are always included in available_chunks. But we found that those were misunderstanding when we investigated a problem in running teuthology. Especially, as reconsidering of (2) meant changing conditions of calculating minimum chunks, that made us revise existent shec's logic significantly.

**Comment by dachary** [comment]
@t-miyamae thanks for the explanation. I'll close this optimization pull request until the logic is fixed. I assume you will open a different pull request with the fix.

**Comment by t-miyamae** [comment]
@dachary We are sorry that the situation has got confused. Do you mean fixing the logic should precede #4689 ?

**Comment by dachary** [comment]
@t-miyamae yes. This pull request (https://github.com/ceph/ceph/pull/4689) requires testing with teuthology ( see https://github.com/ceph/ceph/pull/4132#issuecomment-103178917 ). It is therefore better to a) fix the logic, b) run the teuthology tests to confirm, c) optimize, d) run the teuthology tests to confirm there is no regression. Does that make sense or am I misunderstanding something ?

**Comment by t-miyamae** [comment]
@dachary You are right. We will accept your opinion.

**Comment by t-miyamae** [comment]
@dachary May I confirm your intent about commit order? We totally agree that SIMD optimization(6224b08) should be preceded by fixing main logic. But how about merging shec.cc(a21dacf)? Since we hope we can implement the fixing logic on the base without shec.cc, may we commit a21dacf at first in the same pull request as the fixing logic?

**Comment by dachary** [comment]
@t-miyamae yes, the refactor a21dacf would make sense in the context of the pull request fixing the logic.

**Comment by t-miyamae** [comment]
@dachary Thank you for your understanding! :)

**Pull request closed without merging**
