### PR TITLE
qa/workunits/rados/test_envlibrados_for_rocksdb: install newer cmake

### PR DESCRIPTION
**Pull request by tchaikov**
rocksdb needs CMake 3.5.1 since
https://github.com/facebook/rocksdb/pull/5662

Signed-off-by: Kefu Chai <kchai@redhat.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test docs`
- `jenkins render docs`

</details>

### CODE REVIEW

**Comment by tchaikov** [comment]
we also need https://github.com/facebook/rocksdb/pull/5687

**Comment by neha-ojha** [comment]
@tchaikov I believe this addressing https://tracker.ceph.com/issues/41253?

**Comment by tchaikov** [comment]
@neha-ojha yes.

http://pulpito.ceph.com/kchai-2019-08-17_00:17:24-rados-wip-kefu-testing-2019-08-16-2103-distro-basic-mira/

**Comment by tchaikov** [comment]
http://pulpito.ceph.com/kchai-2019-08-17_15:55:17-rados-wip-kefu-testing-2019-08-16-2103-distro-basic-smithi/

**Comment by neha-ojha** [comment]
> http://pulpito.ceph.com/kchai-2019-08-17_15:55:17-rados-wip-kefu-testing-2019-08-16-2103-distro-basic-smithi/

seems to be failing with something else

**Comment by tchaikov** [comment]
http://pulpito.ceph.com/kchai-2019-08-17_17:32:39-rados-wip-kefu-testing-2019-08-16-2103-distro-basic-smithi/

@neha-ojha this one passed.

**Comment by tchaikov** [comment]
retest this please.

**Pull request merged**
