### PR TITLE
log: Log.cc: Assign LOG_DEBUG priority to syslog calls

### PR DESCRIPTION
**Pull request by badone**
http://tracker.ceph.com/issues/14138

### CODE REVIEW

**Comment by badone** [comment]
http://tracker.ceph.com/issues/14138

**Comment by dachary** [comment]
@badone could you please **git cherry-pick -x 8e93f3f** for the same reason ?

**Comment by badone** [comment]
@dachary done for both, sorry, still getting the hang of all this :)

**Comment by dachary** [comment]
@liewegas does this backport look good to merge ? It passed a run of the hammer rados suite ( see http://tracker.ceph.com/issues/13356#note-34 for details ) and the upgrade/hammer suite ( see http://tracker.ceph.com/issues/13356#note-37 for details ).

**Pull request merged**
