### PR TITLE
Revert "Merge PR #35697 into master"

### PR DESCRIPTION
**Pull request by batrick**
This reverts commit c27bf1ced2c6e3dea32f4c109267e09c4f0b8e47, reversing
changes made to 4a73fd2251e6790e115e382f1bab844d5c1e1531.

The PR broke packaging. It will be reposted.

Signed-off-by: Patrick Donnelly <pdonnell@redhat.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by tchaikov** [comment]
@batrick we can have the packaging fixed without reverting the changes first, if this does not take a long time. in the meanwhile, we can include this PR for building packages.

**Review by badone — APPROVED** [review]

**Comment by batrick** [comment]
> @batrick we can have the packaging fixed without reverting the changes first, if this does not take a long time. in the meanwhile, we can include this PR for building packages.

That's okay with me. I've let @vshankar know about this issue.

**Comment by vshankar** [comment]
> @batrick we can have the packaging fixed without reverting the changes first, if this does not take a long time. in the meanwhile, we can include this PR for building packages.

I'll push a PR soon...

**Comment by batrick** [comment]
Closed in favor of #36939

**Pull request closed without merging**
