### PR TITLE
tests: remove pubsub tests from multisite

### PR DESCRIPTION
**Pull request by yuvalif**
Fixes: https://tracker.ceph.com/issues/56572

Signed-off-by: Yuval Lifshitz <ylifshit@redhat.com>

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [x] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Review by cbodley — APPROVED** [review]

**Review by TRYTOBE8TME — COMMENTED** [review]
So, is this a part of only fix or have we deprecated pubsub tests?

**Comment by yuvalif** [comment]
> So, is this a part of only fix or have we deprecated pubsub tests?

the tests are currently failing (something is broken with pubsub), so there is no point in keeping them unless we plan on fixing pubsub (which we don't, as we plan on deprecating the feature)

**Comment by yuvalif** [comment]
jenkins test make check

**Review by TRYTOBE8TME — APPROVED** [review]

**Comment by yuvalif** [comment]
lua is crashing during multisite teuthology tests: http://qa-proxy.ceph.com/teuthology/yuvalif-2022-09-13_07:01:40-rgw:multisite-wip-yuval-fix-56572-distro-default-smithi/7030426/teuthology.log

submitted: https://tracker.ceph.com/issues/57518

**Comment by yuvalif** [comment]
teuthology: http://pulpito.front.sepia.ceph.com/yuvalif-2022-09-14_19:06:06-rgw:multisite-wip-yuval-fix-56572-distro-default-smithi/

crashes seen, similar to: https://tracker.ceph.com/issues/57400

this test: http://qa-proxy.ceph.com/teuthology/yuvalif-2022-09-14_19:06:06-rgw:multisite-wip-yuval-fix-56572-distro-default-smithi/7033150/teuthology.log

has 8 failures. in the following tests, sync status failed after the crash:
* `test_resharded_bucket_incremental_sync_oldest_after_data_sync_init`
* `test_resharded_bucket_incremental_sync_latest_after_data_sync_init`
* `test_bucket_incremental_sync_after_data_sync_init` 
* `test_resharded_bucket_full_sync_after_data_sync_init`
* `test_bucket_full_sync_after_data_sync_init`
following tests failed before the crash appear in the log, but probably also due to the crash:
* `test_zap_init_bucket_sync_run`
* `test_bucket_sync_run_basic_incremental`
following is a know failure: `test_version_suspended_incremental_sync`

**Pull request merged**
