### PR TITLE
mgr/smb: Make appropriate changes to global and share specific options

### PR DESCRIPTION
**Pull request by anoopcs9**
To better match Windows ACLs include `acl_xattr` VFS module alongside `ceph` with specific options meaningful for containers. In addition to that we remove explicit configuration for the minimum supported protocol version so as to live with the default.

See man [vfs_acl_xattr(8)](https://www.samba.org/samba/docs/current/man-html/vfs_acl_xattr.8.html) and man [smb.conf(5)](https://www.samba.org/samba/docs/current/man-html/smb.conf.5.html) for more details.

### CODE REVIEW

**Comment by anoopcs9** [comment]
@phlogistonjohn let me know your thoughts.

**Review by phlogistonjohn — COMMENTED** [review]
I really want to ensure ceph's smb support doesn't enable SMB1. At some point samba team was going to disable smb1 by default, has this already happened for the samba in the images we're using? If so I think your change is fine... if not we can explicitly choose the lowest SMB2_XX for now.

The reason I don't want to support smb1 is that smb1, if not already disabled, is on it's way out and I don't want anyone trying out early versions of our stack to get the wrong impression of behavior or performance that is smb1 related. I also would prefer explicit bug reports from folks who have smb1 only clients so we can assess the frequency of these requests vs have some clients quietly work one day and then not after upgrades.

**Comment by anoopcs9** [comment]
> I really want to ensure ceph's smb support doesn't enable SMB1. At some point samba team was going to disable smb1 by default, has this already happened for the samba in the images we're using?

From earlier [v4.11.0](https://www.samba.org/samba/history/samba-4.11.0.html) release notes:
```
SMB1 is disabled by default
---------------------------
The defaults of 'client min protocol' and 'server min protocol' have been changed to SMB2_02.
This means clients without support for SMB2 or SMB3 are no longer able to connect to smbd (by default).
SMB1 is officially deprecated and might be removed step by step in the following years.
```

> If so I think your change is fine... if not we can explicitly choose the lowest SMB2_XX for now.

So we are safe in this regard.

**Comment by phlogistonjohn** [comment]
Thanks for looking into it.

**Review by phlogistonjohn — APPROVED** [review]

**Comment by phlogistonjohn** [comment]
@adk3798 can you please add this to a future tuethology run? Thanks.

**Comment by anoopcs9** [comment]
jenkins test make check

**Comment by anoopcs9** [comment]
jenkins test dashboard cephadm

**Comment by adk3798** [comment]
jenkins test make check

**Comment by adk3798** [comment]
https://pulpito.ceph.com/adking-2024-07-23_15:55:03-orch:cephadm-wip-adk-testing-2024-07-19-0851-distro-default-smithi/

Failures:

- staggered upgrade mismatch between `ceph orch ps` and `ceph versions`, known issue
- thrash and rgw-ingress tests timing out, known issue
- mds_upgrade_sequence failure, known issue
- cephadm task test was actually related to a specific PR in the run

Nothing to block merging for all PRs except the one causing the cephadm task failure (not this PR if you see this comment)

**Pull request merged**
