### PR TITLE
reef: RGW - Swift retarget needs bucket set on object

### PR DESCRIPTION
**Pull request by prazumovsky**
Fixes: https://tracker.ceph.com/issues/63684

---

backport of https://github.com/ceph/ceph/pull/46719
parent tracker: https://tracker.ceph.com/issues/56029

When a bucket list is retargeted to an object get, then the object may not yet have it's bucket set.  Ensure the bucket is set on the object.

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Comment by cbodley** [comment]
blocked by https://github.com/ceph/ceph/pull/56003. will need to 'cherry-pick -x' once that merges

**Comment by prazumovsky** [comment]
`make check` failed - is it something serious or could be just re-run? Same failure I see on squid backport.

**Comment by cbodley** [comment]
> The following tests FAILED:
	  7 - run-tox-mgr-dashboard-py3 (Failed)

apologies, the checks are very flaky lately. we'll just keep running them until they pass. it won't prevent testing in the meantime

**Comment by cbodley** [comment]
jenkins test make check

**Comment by prazumovsky** [comment]
Hello again, I see all checks are passed, are we ok to merge this fix?

**Review by cbodley — APPROVED** [review]

**Pull request merged**
