### PR TITLE
mgr/volumes: avoid returning -ESHUTDOWN back to cli

### PR DESCRIPTION
**Pull request by vshankar**
I think mgr/volumes is acting a bit fancy by checking if the ceph-mgr daemon and plugins are under termination, thereby returning -ESHUTDOWN to cli commands. This seems unnecessary. None of the other mgr plugins do anything like this.

Handling of commands when the ceph-mgr is under termination is possibly handled in one of the upper layers.

Fixes: http://tracker.ceph.com/issues/58651
Signed-off-by: Venky Shankar <vshankar@redhat.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Review by dparmar18 — APPROVED** [review]
LGTM

**Review by batrick — COMMENTED** [review]
> Handling of commands when the ceph-mgr is under termination is possibly handled in one of the upper layers.

If that's true, what prompted this change? :thinking:

If this is just cleanup then, lgtm.

**Comment by vshankar** [comment]
> > Handling of commands when the ceph-mgr is under termination is possibly handled in one of the upper layers.
> 
> If that's true, what prompted this change? :thinking:

Not sure, but it might depend on the return value of the command. None of the other mgr plugins seem to specially handle the termination case.

> 
> If this is just cleanup then, lgtm.

**Review by rishabh-d-dave — APPROVED** [review]

**Comment by vshankar** [comment]
jenkins test api

**Comment by vshankar** [comment]
jenkins test make check

**Comment by vshankar** [comment]
https://tracker.ceph.com/projects/cephfs/wiki/Main#09-Mar-2023

**Comment by vshankar** [comment]
jenkins test api

**Pull request merged**
