### PR TITLE
kraken: osd: calc_clone_subsets misuses try_read_lock vs missing 

### PR DESCRIPTION
**Pull request by shinobu-x**
http://tracker.ceph.com/issues/18723

### CODE REVIEW

**Comment by shinobu-x** [comment]
Reset commits pushed by mistake =)
Old one: https://github.com/ceph/ceph/pull/13499

**Comment by shinobu-x** [comment]
jenkins test this please

**Comment by shinobu-x** [comment]
jenkins test this please

**Comment by shinobu-x** [comment]
Magic!

**Comment by shinobu-x** [comment]
Ain't no magic!!

**Comment by shinobu-x** [comment]
test jenkins please

**Comment by tchaikov** [comment]
@shinobu-x could you mark the backported PRs with the targeted milestone when you prepare them next time?

**Comment by smithfarm** [comment]
@shinobu-x You cherry-picked the 2 commits in the wrong order.

Closing this PR in favor of #14616

**Pull request closed without merging**
