### PR TITLE
rgw: lifecycle thread shouldn't process the bucket which has been deleted

### PR DESCRIPTION
**Pull request by zhangsw**
Fixes: http://tracker.ceph.com/issues/20285

Signed-off-by: Zhang Shaowen <zhangshaowen@cmss.chinamobile.com>

### CODE REVIEW

**Comment by cbodley** [comment]
passed rgw suite: http://pulpito.ceph.com/cbodley-2017-06-19_13:44:54-rgw-wip-cbodley-testing-distro-basic-mira/

**Comment by cbodley** [comment]
@zhangsw @dang should this one be backported to kraken? jewel?

**Comment by zhangsw** [comment]
@cbodley I think it should be backported to kraken.

**Comment by cbodley** [comment]
@zhangsw thanks, i updated http://tracker.ceph.com/issues/20285 accordingly

**Pull request merged**
