### PR TITLE
mgr/dashboard: Add metric relative to osd blocklist

### PR DESCRIPTION
**Pull request by aaSharma14**
It would be good to have a metric with number of clients "blocklisted" of command: "ceph osd blocklist ls". The reason to have this is metric is have an alert when this number raise up.

Fixes: https://tracker.ceph.com/issues/58083
Signed-off-by: Aashish Sharma <aasharma@redhat.com>

Screenshot from 2022-11-25 11-40-35

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Review by avanthakkar — COMMENTED** [review]
@aaSharma14 The alert if count changes is yet to be added?

**Comment by aaSharma14** [comment]
jenkins test make check

**Review by pereman2 — APPROVED** [review]

**Review by avanthakkar — APPROVED** [review]
LGTM!

**Comment by avanthakkar** [comment]
> @aaSharma14 The alert if count changes is yet to be added?

And can you create maybe tracker for adding any alerts related to this metric.

**Comment by avanthakkar** [comment]
jenkins retest this please

**Comment by Pegonzal** [comment]
jenkins test make check

**Comment by aaSharma14** [comment]
jenkins retest this please

**Comment by aaSharma14** [comment]
jenkins retest this please

**Comment by aaSharma14** [comment]
jenkins test dashboard

**Comment by aaSharma14** [comment]
jenkins test dashboard cephadm

**Comment by aaSharma14** [comment]
jenkins test make check arm64

**Comment by aaSharma14** [comment]
jenkins test windows

**Pull request merged**
