### PR TITLE
mgr/cephadm: fixing yaml parsing during bootstrap

### PR DESCRIPTION
**Pull request by rkachach**
Fixes YAML parsing during bootstrap. Code was not handling `---` YAML seperator (sed to separate multiple docs) correctly, as consequence, any objects containing `---` (such priv/pub keys) was considered as the start of a new object.

**Note:** Added some UT arround presence of `---` in YAML doc and also fields such as priv/pub key where multiple `-` characters are present (original issue was caused by not handling correctly these scenarios).

Fixes: https://tracker.ceph.com/issues/55555
Signed-off-by: Redouane Kachach <rkachach@redhat.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/master/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [x] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [x] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Review by adk3798 — APPROVED** [review]

**Comment by adk3798** [comment]
@rkachach Can we maybe also add either a unit test checking that a yaml doc that was not parsed correctly before this change now is, or a teuthology test that applies a spec at bootstrap that did not work before this change?

**Comment by rkachach** [comment]
> @rkachach Can we maybe also add either a unit test checking that a yaml doc that was not parsed correctly before this change now is, or a teuthology test that applies a spec at bootstrap that did not work before this change?

I added a new UT that should cover several cases of `---` presence as part of field or when used as doc separator.

**Comment by adk3798** [comment]
jenkins test make check

**Comment by adk3798** [comment]
jenkins test dashboard cephadm

**Comment by adk3798** [comment]
https://pulpito.ceph.com/adking-2022-05-17_04:26:54-orch:cephadm-wip-adk-testing-2022-05-16-2012-distro-basic-smithi/

green

**Pull request merged**
