### PR TITLE
ReplicatedPG: object_info_t's version < replica's need, add to missing too.

### PR DESCRIPTION
**Pull request by cxwshawn**
Fixes #13111

Signed-off-by: Xiaowei Chen <chen.xiaowei@h3c.com>

### CODE REVIEW

**Comment by yangruifeng** [comment]
should we also check it when read_log?

**Comment by cxwshawn** [comment]
@athanatos please help check !

**Comment by cxwshawn** [comment]
@liewegas @athanatos  please help check !

**Comment by athanatos** [comment]
This code path also needs a test in ceph-qa-suite.

**Comment by cxwshawn** [comment]
@athanatos I really don't know how to write test about this code path, since we need to unpin the hard drive, and another problem is I cannot join in the #ceph-devel, and I still don't know the reason.

**Comment by tchaikov** [comment]
@cxwshawn let me know if you can use some help on writing a test in ceph-qa-suite or performing test using teuthology.

**Comment by cxwshawn** [comment]
@tchaikov yeah, I still cannot use teuthology since we can only use proxy to access internet, so building  teuthology env cost too much ~~~ do u have an existing webpage that can test my case easily ?

**Comment by tchaikov** [comment]
@cxwshawn , probably you can start with writing a test in ceph-qa-suite? and i will surely help review and test it in the sepia lab?

**Comment by cxwshawn** [comment]
@tchaikov can u give me an account since we really have a big team, and others may use again  ?

**Comment by tchaikov** [comment]
@cxwshawn to access the community lab, you need to be able to openvpn and ssh to an external server. not sure your limited internet access allows you guys to do this?  i will find you a link to the process.

**Comment by tchaikov** [comment]
@cxwshawn see http://ceph.github.io/sepia/adding_users/

**Comment by liewegas** [comment]
@cxwshawn ping

**Comment by cxwshawn** [comment]
@liewegas @tchaikov ah, I am so sorry since this job priority being low in my job list, but this case is really not easy to trigger, writing test case becomes really big problem, I will try my best to consider how to finish this.

**Comment by athanatos** [comment]
@cxwshawn I'm still not really sure this is correct.  I really think we need a test case in order to merge it.  Can we talk about how to build such a case?

**Comment by liewegas** [comment]
Closing this pull request since it appears to be abandoned.  If you it is not abandoned, and you are still interested in championing this change, please address any review comments so far and reopen the pull request.

**Pull request closed without merging**
