### PR TITLE
nautilus: rgw: tooling to locate rgw objects with missing rados components

### PR DESCRIPTION
**Pull request by ivancich**
backport tracker: https://tracker.ceph.com/issues/49187

---

backport of https://github.com/ceph/ceph/pull/39176
parent tracker: https://tracker.ceph.com/issues/49063

this backport was staged using ceph-backport.sh version 16.0.0.6848
find the latest version at https://github.com/ceph/ceph/blob/master/src/script/ceph-backport.sh

### CODE REVIEW

**Comment by ivancich** [comment]
jenkins test make check

**Review by linuxkidd — APPROVED** [review]

**Comment by smithfarm** [comment]
@ivancich @cbodley Does this need a PendingReleaseNote?

**Comment by ivancich** [comment]
> @ivancich @cbodley Does this need a PendingReleaseNote?

Given that this has merged on master, pacific, and octopus, what would you recommend, @smithfarm? Another PR to add a PendingReleaseNote?

**Comment by smithfarm** [comment]
> Given that this has merged on master, pacific, and octopus, what would you recommend, @smithfarm? Another PR to add a PendingReleaseNote?

Whatever you guys think is best for our users :-)

**Comment by smithfarm** [comment]
jenkins test make check

**Comment by smithfarm** [comment]
```
make[3]: *** [src/test/rgw/CMakeFiles/unittest_rgw_dmclock_scheduler.dir/build.make:63: src/test/rgw/CMakeFiles/unittest_rgw_dmclock_scheduler.dir/test_rgw_dmclock_scheduler.cc.o] Error 1
```

**Comment by smithfarm** [comment]
jenkins test make check

**Pull request merged**
