### PR TITLE
jewel: rgw: dont log EBUSY errors in 'sync error list'

### PR DESCRIPTION
**Pull request by pdvian**
http://tracker.ceph.com/issues/22582

### CODE REVIEW

**Comment by taodd** [comment]
retest this please

**Comment by smithfarm** [comment]
Duplicate backport PR is open at https://github.com/ceph/ceph/pull/19638

**Comment by smithfarm** [comment]
@mattbenjamin @cbodley Can you review? A duplicate backport PR is open at #19638 but needs revision, whereas this one already passed make check.

**Comment by smithfarm** [comment]
Integration testing: http://tracker.ceph.com/issues/21742#note-11

Will post a summary to the PR when the testing is complete.

**Comment by smithfarm** [comment]
@mattbenjamin @cbodley This PR passed two RGW runs at http://tracker.ceph.com/issues/21742#note-11

Do you think it's ready to merge?

**Pull request merged**
