### PR TITLE
qa/suites/rados: Cancel injectfull to allow cleanup

### PR DESCRIPTION
**Pull request by badone**
IO is frozen when the injectfull command is sent as part of the test which causes the cleanup to hang so we need to clear it.

Fixes: https://tracker.ceph.com/issues/59380

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Comment by cbodley** [comment]
from https://jenkins.ceph.com/job/ceph-api/76404/
> dashboard.exceptions.DashboardException: Orchestrator is unavailable

**Comment by cbodley** [comment]
jenkins test api

**Comment by cbodley** [comment]
from https://jenkins.ceph.com/job/ceph-pull-requests/137451/
> The following tests FAILED:
	 32 - run-rbd-unit-tests-61.sh (Failed)

**Comment by cbodley** [comment]
jenkins test make check

**Comment by kamoltat** [comment]
FYI Came across this PR while scrubbing the main suite tracker issues:

Should we approve and move it to QA soon @cbodley?

**Comment by cbodley** [comment]
you might still add the `needs-qa` label to get tests going in the meantime?

**Review by neha-ojha — APPROVED** [review]

**Comment by neha-ojha** [comment]
@badone I am reading https://tracker.ceph.com/issues/59380#note-52, have you already tested this PR? adding needs-qa just in case it needs a larger run

**Comment by badone** [comment]
> @badone I am reading https://tracker.ceph.com/issues/59380#note-52, have you already tested this PR? adding needs-qa just in case it needs a larger run

Hi @neha-ojha , I have tested it with a standalone run using a modified orig.config.yaml file and it appears to work just fine. I leave it up to you whether it needs wider testing before merging.

**Comment by badone** [comment]
jenkins test api

**Comment by ljflores** [comment]
Rados approved: https://tracker.ceph.com/projects/rados/wiki/MAIN#httpstrackercephcomissues66706

**Pull request merged**
