### PR TITLE
objecter: resend linger ops on split

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/11699

### CODE REVIEW

**Comment by smithfarm** [comment]
ready for integration testing

**Comment by dachary** [comment]
Sam is the ultimate authority on splitting pg and he also authored the original patch.

**Comment by dachary** [comment]
@athanatos this backport passed a rados suite ( http://pulpito.ceph.com/loic-2015-07-09_21:09:04-rados-firefly-backports---basic-multi ), do you think it can be merged in firefly ?

**Comment by jdurgin** [comment]
Looks like a good backport to me. I authored the original 2nd patch.

**Pull request merged**
