### PR TITLE
librbd: remove inclusion of endian.h

### PR DESCRIPTION
**Pull request by wjwithagen**
The file is not available on FreeBSD.

fixes: https://github.com/ceph/ceph/pull/38862

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by wjwithagen** [comment]
Removing the DNM, since this compiles oke in Linux Jenkins env.
So endian.h is definitely not needed to include

**Comment by dillaman** [comment]
jenkins make test

**Comment by dillaman** [comment]
jenkins test make check

**Review by dillaman — APPROVED** [review]
lgtm

**Pull request merged**
