### PR TITLE
jewel: cephfs: Journaler may execute on_safe contexts prematurely

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/20536

### CODE REVIEW

**Comment by smithfarm** [comment]
@jcsp This completes what was started by #15468 - I hope it's not a problem that 10.2.8 contains only the first half of the fix.

**Comment by jcsp** [comment]
Hmm, I can't remember how bad the issue was that needed the followup commit: @ukernel ?

**Comment by ukernel** [comment]
it's better to also cherry pick 146383a21b932048030982f1c44d39781879ab41.

**Comment by ukernel** [comment]
The whole series fix an issue in purge queue. we haven't back-ported purge queue to jewel. So another option is reverting #15468

**Comment by smithfarm** [comment]
@ukernel @jcsp So this should be considered a blocker for 10.2.8? In other words, we need to quickly do a 10.2.9 to clean this up?

**Comment by ukernel** [comment]
the bug can cause damaged mds. it should be blocker for 10.2.8.

**Comment by smithfarm** [comment]
Since we tend towards not backporting features, and the purge queue sounds like a feature, I propose the following course of action:

* revert #15468 -> see https://github.com/ceph/ceph/pull/16282
* close this PR
* change status of related backport trackers http://tracker.ceph.com/issues/20140 and http://tracker.ceph.com/issues/20536 to "Rejected"
* remove jewel from Backports field in http://tracker.ceph.com/issues/20055
* write a release note
* cut a 10.2.9 release with just PR#16282 in it

Alternatively, we could cherry-pick 146383a21b932048030982f1c44d39781879ab41 into this PR, merge it, and cut a 10.2.9 with this PR?

**Comment by smithfarm** [comment]
http://tracker.ceph.com/issues/20536 was rejected

**Pull request closed without merging**
