### PR TITLE
mimic: krbd: avoid udev netlink socket overrun and retry on transient errors from udev_enumerate_scan_devices()

### PR DESCRIPTION
**Pull request by idryomov**
Analogous to https://github.com/ceph/ceph/pull/31075:

backport trackers:

* https://tracker.ceph.com/issues/42426
* https://tracker.ceph.com/issues/42526
* https://tracker.ceph.com/issues/42644

---

backport of

* https://github.com/ceph/ceph/pull/30965
* https://github.com/ceph/ceph/pull/31023
* https://github.com/ceph/ceph/pull/31057

parent trackers:

* https://tracker.ceph.com/issues/41036
* https://tracker.ceph.com/issues/41404
* https://tracker.ceph.com/issues/42523

### CODE REVIEW

**Comment by yuriw** [comment]
[wip-yuri4-testing-2019-11-04-2107-mimic](https://trello.com/c/v6wZSzAW/745-wip-yuri4-testing-2019-11-04-2107-mimic)

**Comment by smithfarm** [comment]
Thanks, @idryomov

**Comment by smithfarm** [comment]
Sorry, @yuriw - I broke the `rbd` suite in mimic. Just merged the fix #31424 so it should work again now.

**Comment by idryomov** [comment]
Note that this should be tested with krbd suite, not rbd.

**Comment by smithfarm** [comment]
OK, I made a new "krbd" label.

**Pull request merged**
