### PR TITLE
octopus: cephadm batch backport September (1)

### PR DESCRIPTION
**Pull request by sebastian-philipp**
Backport of #36765, #36738, #36757, #36793, #36509, #36794, #36571, #36315, #36817, #36330, #36752, #36797, #36799, #36818, #36841, #36816, #36572, #36848, #36792, #36753, #36849, #36858, #36815, #36676, #36905, #36800, #36873, #36943, #36911, #36894

---

commit 2b05cf53e836234fb94f6694662e309074bb071f
Conflicts:
        src/pybind/mgr/dashboard/tools.py
        src/python-common/ceph/deployment/service_spec.py

commit 6d252bba431fb292d87613626fb32ece88b001aa
Conflicts:
        qa/tasks/cephadm.py

### CODE REVIEW

**Comment by sebastian-philipp** [comment]
This PR acutally breaks iscsi, cause of #36800

**Comment by sebastian-philipp** [comment]
> This PR acutally breaks iscsi, cause of #36800

removed this PR from this batch

**Comment by sebastian-philipp** [comment]
ceph/ceph-container#1706

**Comment by sebastian-philipp** [comment]
removed #36894 from the batch

**Comment by sebastian-philipp** [comment]
green: https://pulpito.ceph.com/swagner-2020-09-09_08:14:41-rados:cephadm-wip-swagner2-testing-2020-09-08-1104-distro-basic-smithi/

**Review by jschmid1 — APPROVED** [review]

**Comment by sebastian-philipp** [comment]
still green: https://pulpito.ceph.com/swagner-2020-09-10_12:02:16-rados:cephadm-wip-swagner2-testing-2020-09-10-1101-octopus-distro-basic-smithi/

**Review by Devp00l — APPROVED** [review]

**Comment by jschmid1** [comment]
waiting for 15.2.5

**Pull request merged**
