### PR TITLE
rbd: misc fixes

### PR DESCRIPTION
**Pull request by wonzhq**

### CODE REVIEW

**Comment by wonzhq** [comment]
The failure of run-make-check.sh is weird. It fails at test/os/TestLFNIndex.cc. However the changes in this PR don't touch that part of the code. Look at the failure itself, it complains a just successfully created file can't be copied, saying that it doesn't exist. Anything wrong with the server running the script?

**Comment by liewegas** [comment]
@athanatos, that sounds a bit like the bug you fixed a while back in 
shared_cache... I think introduced with the new ObjectContext caching?

**Comment by XinzeChi** [comment]
@wonzhq , I think the fails at test/os/TestLFNIndex.cc is not caused by your patch. My patch is also return fail because of test/os/TestLFNIndex.cc. You can repush your code directly.

I think the test case in test/os/TestLFNIndex.cc would run fail sometimes.

**Comment by wonzhq** [comment]
Thanks, @XinzeChi . I've already pushed the right code :)

**Comment by jdurgin** [comment]
Thanks! Nice finds!

**Pull request merged**
