### PR TITLE
client: eliminate duplicate lookups wherever possible

### PR DESCRIPTION
**Pull request by gardran**
## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [x] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Comment by mchangir** [comment]
@vshankar 
Tested *kernel untar build* for non-optimized and optimized version of the client. The seed used for both the jobs was the same, i.e. both the jobs had exactly the same YAML fragments.

[Job without optimization](https://pulpito.ceph.com/mchangir-2024-07-18_12:49:30-fs:workload-main-distro-default-smithi/) 28:25 minutes
2024-07-18T13:39:27.482 INFO:tasks.workunit.client.0.smithi019.stderr:+ tar xJf ../linux.tar.xz
...
2024-07-18T13:57:52.152 INFO:tasks.workunit.client.0.smithi019.stdout:removed directory 'linux-6.5.11'

[Job with optimization](https://pulpito.ceph.com/mchangir-2024-07-18_16:02:30-fs:workload-wip-mchangir-testing-wip-gardran-kill-count-debug-distro-default-smithi/) 18:43 minutes
2024-07-18T16:38:54.147 INFO:tasks.workunit.client.0.smithi003.stderr:+ tar xJf ../linux.tar.xz
...
2024-07-18T16:57:37.868 INFO:tasks.workunit.client.0.smithi003.stdout:removed directory 'linux-6.5.11'

**Review by vshankar — COMMENTED** [review]
Seems reasonable. Thx @gardran

**Comment by gardran** [comment]
@vshankar @mchangir - curious what happened with Milind's report comparing performance for optimized vs. non-optimized versions? It's not here any more :(

**Comment by vshankar** [comment]
> @vshankar @mchangir - curious what happened with Milind's report comparing performance for optimized vs. non-optimized versions? It's not here any more :(

Oh, I wasn't aware that @mchangir is running performance benchmarks with this change.

**Comment by mchangir** [comment]
> @vshankar @mchangir - curious what happened with Milind's report comparing performance for optimized vs. non-optimized versions? It's not here any more :(

I had miscalculated the timmings. Sorry about that.

**Comment by vshankar** [comment]
This PR is under test in [https://tracker.ceph.com/issues/67252](https://tracker.ceph.com/issues/67252).

**Review by vshankar — APPROVED** [review]
https://tracker.ceph.com/projects/cephfs/wiki/Main#wip-vshankar-testing-20240731064922-debug

**Pull request merged**
