### PR TITLE
doc: release notes for v0.94.3

### PR DESCRIPTION
**Pull request by theanalyst**
WIP doc for the current hammer backport

### CODE REVIEW

**Comment by dachary** [comment]
https://github.com/theanalyst/ceph/blob/doc/v0.94.3-release/doc/release-notes.rst#v0943-hammer-draft even has accented letters right. Yeah :-)

**Comment by dachary** [comment]
<pre>
Reviewed-by: Loic Dachary &lt;ldachary@redhat.com>
</pre>

**Comment by dachary** [comment]
Does the WIP mean I should not merge right now ? Or can I ?

**Comment by theanalyst** [comment]
marked primarily as wip because of the additional comment introduced this time.. if that looks okay its ready to merge.

**Pull request merged**
