### PR TITLE
octopus: rbd-mirror: improved replication statistics

### PR DESCRIPTION
**Pull request by smithfarm**
backport trackers:

* https://tracker.ceph.com/issues/45036
* https://tracker.ceph.com/issues/45047
* https://tracker.ceph.com/issues/45223
* https://tracker.ceph.com/issues/45277
* https://tracker.ceph.com/issues/45278

---

backport of:

* https://github.com/ceph/ceph/pull/34408
* https://github.com/ceph/ceph/pull/34496
* https://github.com/ceph/ceph/pull/34615
* https://github.com/ceph/ceph/pull/34697
* https://github.com/ceph/ceph/pull/34753

parent trackers:

* https://tracker.ceph.com/issues/44105
* https://tracker.ceph.com/issues/44596
* https://tracker.ceph.com/issues/44727
* https://tracker.ceph.com/issues/44938
* https://tracker.ceph.com/issues/45072

this backport was staged using ceph-backport.sh version 15.1.1.389
find the latest version at https://github.com/ceph/ceph/blob/master/src/script/ceph-backport.sh

### CODE REVIEW

**Comment by smithfarm** [comment]
@dillaman Please take another look?

**Comment by dillaman** [comment]
lgtm -- thx

**Comment by smithfarm** [comment]
@dillaman @trociny Added two more backport issues to this PR. Assuming this is still OK...

**Comment by yuriw** [comment]
[wip-yuri2-testing-2020-04-29-1652-octopus](https://trello.com/c/jT0MqqDt/890-wip-yuri2-testing-2020-04-29-1652-octopus)

**Pull request merged**
