### PR TITLE
Revert "cmake: do not link ceph-dencoder against global"

### PR DESCRIPTION
**Pull request by vshankar**
Reverts ceph/ceph#48418

### CODE REVIEW

**Comment by vshankar** [comment]
doh -- GH revert does not add signed-off-by tag :/

**Review by tserong — APPROVED** [review]
I've done a test build on openSUSE and it doesn't cause any trouble for me, so I'm cool. The one thing I'd suggest is adding a note to the commit message about _why_ this is being reverted (perhaps mention the "Attempt to free invalid pointer" error you noted in https://github.com/ceph/ceph/pull/48418#issuecomment-1378478510).

Also, I'm not sure if @tchaikov is around ATM, but if he is, I'd be interested to see if he has a view on why you're seeing that error, because I'm still not sure what's going on :-/

**Comment by vshankar** [comment]
> I've done a test build on openSUSE and it doesn't cause any trouble for me, so I'm cool. The one thing I'd suggest is adding a note to the commit message about _why_ this is being reverted (perhaps mention the "Attempt to free invalid pointer" error you noted in [#48418 (comment)](https://github.com/ceph/ceph/pull/48418#issuecomment-1378478510)).

Sure. I created this commit via GH revert and that adds minimal info. I'll do the needful.

> 
> Also, I'm not sure if @tchaikov is around ATM, but if he is, I'd be interested to see if he has a view on why you're seeing that error, because I'm still not sure what's going on :-/

I would have liked to debug this but I have a BIG backlog of cephfs related changes that are pending testing and merging due to lab issues we had in the past :/

BTW, I am running this through fs suite with other PRs - will report if I do not see the tcmalloc exception.

**Comment by vshankar** [comment]
@tserong fs suite run - https://pulpito.ceph.com/vshankar-2023-01-25_07:57:32-fs-wip-vshankar-testing-20230125.055346-testing-default-smithi/

No ceph-dencoder failures. Failures are known issues - https://tracker.ceph.com/projects/cephfs/wiki/Main#25-Jan-2023

**Comment by vshankar** [comment]
@tserong Updated with commit description and tracker link.

**Comment by tserong** [comment]
@vshankar LGTM!

**Comment by vshankar** [comment]
@tserong Doesn't require backport to p/q I think?

**Comment by tserong** [comment]
@vshankar, nope, the original commit was never backported to pacific. I do have #48028 open for Quincy to fix a couple other things, and I had pulled the original commit in there, but I have now dropped it from that PR.

**Comment by vshankar** [comment]
> @vshankar, nope, the original commit was never backported to pacific. I do have #48028 open for quincy to fix a couple other things, and I had pulled the original commit in there, but I have now dropped it from that PR.

Thx!

**Comment by vshankar** [comment]
> @vshankar can https://tracker.ceph.com/issues/58219 be marked Resolved?

Oh, this is similar to another test failure I fixed - https://github.com/ceph/ceph/pull/52754

Can be marked resolved.

**Pull request merged**
