### PR TITLE
cephadm: Remove duplicated process args in promtail and loki(

### PR DESCRIPTION
**Pull request by hookak**
- ~Add bind mount for journald in promtail container(`/var/log/journal`)~
  - ~scraping log of prometheus, loki, etc in journald~
- Remove duplicated process args in promtail and loki(`--confing.file=config.file`)
- Add `--config.expand-env` for in promtail for using host env

It would be nice to be able to add [process args]/[container args] to the service spec file.
Currently, only [container args] seems to be supported in [custom container service](https://docs.ceph.com/en/quincy/cephadm/services/custom-container/).
Monitoring services require additional arguments.(https://tracker.ceph.com/issues/54308)
What do you guys think?

Signed-off-by: jinhong.kim <jinhong.kim0@navercorp.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [x] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by hookak** [comment]
@adk3798 Could you review this?

**Comment by adk3798** [comment]
> * Add bind mount for journald in promtail container(`/var/log/journal`)
>   
>   * scraping log of prometheus, loki, etc in journald
> * Remove Duplicated process args in promtail and loki(`--confing.file=config.file`)
> * Add `--config.expand-env` for in promtail for using host env
> 
> It would be nice to be able to add [process args]/[container args] to the service spec file. Currently, only [container args] seems to be supported in [custom container service](https://docs.ceph.com/en/quincy/cephadm/services/custom-container/). Monitoring services require additional arguments.(https://tracker.ceph.com/issues/54308) What do you guys think?
> 

While there is no support currently for daemon/process args, we do have universal support for container args, even outside of Custom Container service https://docs.ceph.com/en/quincy/cephadm/services/#extra-container-arguments

I'd be okay with adding support for misc. daemon/process args in the same way we support misc. container args (I imagine the patch would be very similar to https://github.com/ceph/ceph/pull/44459/commits/d030c0f8fb5f091866b9b2b0efc66ca18e40494c) it's just not something I've had a chance to look at just yet.

> Signed-off-by: jinhong.kim [jinhong.kim0@navercorp.com](mailto:jinhong.kim0@navercorp.com)
>

**Review by adk3798 — APPROVED** [review]

**Comment by adk3798** [comment]
jenkins test make check

**Comment by adk3798** [comment]
https://pulpito.ceph.com/adking-2022-08-13_23:54:41-orch:cephadm-wip-adk-testing-2022-08-13-1551-distro-default-smithi/

1 known failure - https://tracker.ceph.com/issues/49287

**Comment by adk3798** [comment]
jenkins test make check

**Comment by adk3798** [comment]
jenkins test dashboard cephadm

**Comment by adk3798** [comment]
jenkins test make check

**Comment by adk3798** [comment]
jenkins test make check

**Comment by adk3798** [comment]
jenkins test make check

**Comment by adk3798** [comment]
jenkins test make check

**Comment by hookak** [comment]
Thanks for your comment @adk3798 
I didn't know service spec already support container args.
So, I delete additional bind mount code in this commit. It seems right to define this in the spec file.

**Comment by nizamial09** [comment]
> @aaSharma14 @nizamial09 do either of you want to take a look at this?

@adk3798 for me it looks okay!

**Pull request merged**
