### PR TITLE
monitoring: add 2 nvmeof alerts to prometheus_alerts.yaml

### PR DESCRIPTION
**Pull request by VallariAg**
This PR adds two alerts:
1. `NVMeoFMissingListener`: Raised if a subsystem doesn't have a listener for each gateway.
2. `NVMeoFZeroListenerSubsystem`: Raised if a subsystem has 0 listeners.

Output (alert example): https://github.com/ceph/ceph-nvmeof/issues/565#issuecomment-2468729003
Fixes: https://github.com/ceph/ceph-nvmeof/issues/565

(Test Build: https://shaman.ceph.com/builds/ceph/wip-nvmeof-listeners-prometheus-alerts-debug-centos9-only/56bd5dd029bda9c0824c9723140a22d1bf3491ad/default/415096/)

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [x] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Comment by aaSharma14** [comment]
Thanks @VallariAg for the PR. 
Any new alerts that need to be added, should be first added in the `prometheus_alerts.libsonnet` file. You can learn about this more here - https://github.com/ceph/ceph/blob/main/monitoring/ceph-mixin/README.md. Also there is a `test_alerts.yml` file where we have the tests related to the alerts, it would be great if we can have tests added for these newly added alerts as well.

**Comment by VallariAg** [comment]
@aaSharma14 thank you for sharing the guide! I have updated the PR. I verified the content generated by ` tox -e alerts-fix` is same as what I added manually in prometheus_alerts.yml. Hope the PR looks better now. 

While running unit tests, I noticed a failure and reported it here https://tracker.ceph.com/issues/68777.

**Review by aaSharma14 — APPROVED** [review]
LGTM! Thanks @VallariAg

**Comment by caroav** [comment]
I think this description is not accurate? 

> NVMeoFListenersUnbalancedCount: trigger if all listeners are not created for each gateway in a subsystem

Should be -  trigger if number of listeners are not equal for each gateway in a subsystem ?

**Comment by VallariAg** [comment]
@caroav I have updated the description of the PR. Thank you!

**Comment by VallariAg** [comment]
jenkins test windows

**Pull request merged**
