### PR TITLE
uuid: use boost::random:random_device

### PR DESCRIPTION
**Pull request by liewegas**
The boost mt code uses uninitialized memory for extra randomness,
which is a bad idea in general but more importantly makes valgrind
unhappy.  Use /dev/urandom instead.

Unfortunately this introduces a link time dependency.. meh!

Fixes: #12736
Signed-off-by: Sage Weil <sage@redhat.com>

### CODE REVIEW

**Comment by liewegas** [comment]
@tchaikov you're right, this did require a ceph.spec and debian/control change.. updated!

**Comment by tchaikov** [comment]
:+!:

**Comment by tchaikov** [comment]
let's see if the valgrind is happy or not.

**Comment by smithfarm** [comment]
@liewegas Is backporting this to hammer an option? This is causing quite some rgw failures in the hammer integration runs.

**Comment by liewegas** [comment]
I'm fine with a backport!

**Pull request merged**
