### PR TITLE
doc: fix typos

### PR DESCRIPTION
**Pull request by wxypro**
Signed-off-by: wangxinyu <wangxinyu@inspur.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by wxypro** [comment]
jenkins test make check

**Review by tchaikov — APPROVED** [review]

**Comment by tchaikov** [comment]
@wxypro could you please squash these two commits into a single one?

**Review by batrick — CHANGES_REQUESTED** [review]
squash commits please

**Comment by wxypro** [comment]
> squash commits please

@batrick already squashed two commits into a single one.

**Review by batrick — APPROVED** [review]

**Pull request merged**
