### PR TITLE
fix a few minor compilation warnings

### PR DESCRIPTION
**Pull request by dachary**
Signed-off-by: Loic Dachary <ldachary@redhat.com>

### CODE REVIEW

**Comment by dachary** [comment]
http://ceph.com/gitbuilder.cgi wip-warnings branch is green for all tarbal builders

**Comment by dachary** [comment]
@tchaikov updated with 0xffffffffu :-)

**Comment by tchaikov** [comment]
looks good in general.

**Comment by dachary** [comment]
running on gitbuilders again

**Pull request merged**
