### PR TITLE
warn when QAT switches to software [de]compression

### PR DESCRIPTION
**Pull request by mkogan1**
Fixes: https://tracker.ceph.com/issues/67631

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Comment by mkogan1** [comment]
example RGW log output when _vstarted_ with when `-o qat_compressor_enabled=true --rgw_compression zlib -o debug_compressor=20` on a machine that does not have a QAT HW or the QAT HW is miss-configured:

```
tail -F ./out/radosgw.8001.log
...
2024-08-20T11:32:15.889+0000 7fffe81e8640 20 QatAccel: QAT decompress                                                                                                                      
2024-08-20T11:32:15.900+0000 7fffe81e8640  1 QatAccel: QAT decompress NOT OK - Using SW: No QAT HW detected                                                                                
2024-08-20T11:32:15.900+0000 7fffe81e8640 20 QatAccel: QAT decompress                                                                                                                      
2024-08-20T11:32:15.909+0000 7fffe81e8640  1 QatAccel: QAT decompress NOT OK - Using SW: No QAT HW detected                                                                                
2024-08-20T11:32:15.909+0000 7fffe81e8640 20 QatAccel: QAT decompress                                                                                                                      
2024-08-20T11:32:15.911+0000 7fffe81e8640  1 QatAccel: QAT decompress NOT OK - Using SW: No QAT HW detected                                                                                
2024-08-20T11:32:15.911+0000 7fffe81e8640  1 ====== req done req=0x7fffbc18f720 op status=0 http_status=200 latency=72.068588257s ======                                                   
2024-08-20T11:32:15.912+0000 7fffe81e8640  1 beast: 0x7fffbc18f720: 127.0.0.1 - cosbench [20/Aug/2024:11:31:03.842 +0000] "GET /bkt/objMP01 HTTP/1.1" 200 11350376448 - - - latency=72.0685
```

**Review by cbodley — APPROVED** [review]
this will be very spammy in the logs, but i guess that's the point 👍

**Comment by cbodley** [comment]
cc @hualongfeng

**Comment by cbodley** [comment]
is there any troubleshooting advice we can add to these error messages? other than 'disable qat_compressor_enabled'?

**Comment by hualongfeng** [comment]
Hi @cbodley  when QAT switches to software [de]compression, there are the following situations: 
1. There is no qat device, in this case you can only disable qat_compressor_enabled; 
2. If the qat device exists, the qat service may not be working properly. In this case, you need to confirm the qat service status; ensure that the qat service is in the active state, and then restart the process using qat. 
3. The current request has exceeded qat's processing capacity, and the excess requests will be transferred to software. In this case, the number of qat instances needs to be increased. The third situation has not been encountered yet, I still need to confirm it.

**Comment by mkogan1** [comment]
@hualongfeng thank you, re:
> qat instances needs to be increased

does it referees increasing the `POLICY=` in
```
sudo vim /etc/sysconfig/qat
ServicesEnabled=dc
POLICY=8
```
or change something in `/etc/4xxx_dev*.conf` ?

**Comment by hualongfeng** [comment]
> @hualongfeng thank you, re:
> 
> > qat instances needs to be increased
> 
> does it referees increasing the `POLICY=` in
> 
> ```
> sudo vim /etc/sysconfig/qat
> ServicesEnabled=dc
> POLICY=8
> ```
> 
> or change something in `/etc/4xxx_dev*.conf` ?

Yes, increasing the `POLICY=` in `/etc/sysconfig/qat` for intree(using qatlib), or increasing the `NumberDcInstances` in `/etc/4xxx_dev*.conf` for out-of-tree driver.

**Comment by mkogan1** [comment]
shaman build submitted:
https://shaman.ceph.com/builds/ceph/wip-qat-logs--i01/

**Pull request merged**
