### PR TITLE
build/ops: rpm: move _epoch_prefix below Epoch definition

### PR DESCRIPTION
**Pull request by smithfarm**
Fix breakage caused by #15286

### CODE REVIEW

**Comment by smithfarm** [comment]
https://shaman.ceph.com/builds/ceph/wip-cond-epoch-2/

**Comment by smithfarm** [comment]
I hope we can find a way to make this work . . .

**Comment by liewegas** [comment]
http://pulpito.ceph.com/sage-2017-06-01_21:44:07-rados-wip-sage-testing---basic-smithi/

better!

**Comment by smithfarm** [comment]
Thanks @liewegas !!!

**Pull request merged**
