### PR TITLE
Test:bencher wrong test margin casuses writes over object_size

### PR DESCRIPTION
**Pull request by jack-changtao**
Signed-off-by: Tao Chang <changtao@hihuron.com>

### CODE REVIEW

**Comment by tchaikov** [comment]
@jack-changtao the change looks good to me. but the Signed-off line does not look right:
```
Signed-off-by:changtao changtao@hihuron.com
```
you might want to change it to
```
Signed-off-by: Chang Tao <changtao@hihuron.com>
```

if "Chang" you first name.

**Comment by jack-changtao** [comment]
@tchaikov 
I changed the comment!  I don't know how to  change the commit message. Thanks

**Comment by tchaikov** [comment]
@jack-changtao use 
```git commit --amend```
to edit your commit message. and
```git push -f``` to update your remote repo

and you need a space after the colon:
```
Signed-off-by: Tao Chang <changtao@hihuron.com>
```

**Comment by jack-changtao** [comment]
@tchaikov
Thanks very much!

**Pull request merged**
