### PR TITLE
rgw: shouldn't return content-type: application/xml if content length is 0

### PR DESCRIPTION
**Pull request by Abhishekvrshny**
http://tracker.ceph.com/issues/12632
http://tracker.ceph.com/issues/12634

### CODE REVIEW

**Comment by dachary** [comment]
You **cherry-pick -x** a commit that was already **cherry-pick -x** : you now have two **cherry-picked from** lines in the commit message. You should have just cherry-pick (without the **-x**).

**Comment by Abhishekvrshny** [comment]
Shall I raise a fresh pull request then with just **cherry-pick** ?

**Comment by dachary** [comment]
@Abhishekvrshny you just need to **git reset --hard ceph/hammer** your branch, **git cherry-pick** and then **git push --force** and it will override the commits that are currently in this pull request. No need to open another pull request.

**Comment by Abhishekvrshny** [comment]
@dachary : done. Hope it is fine now.

**Comment by dachary** [comment]
@Abhishekvrshny perfect :-)

**Comment by yehudasa** [comment]
@dachary should we set milestone hammer for this PR?

**Comment by dachary** [comment]
@yehudasa yes, my bad, thanks !

**Comment by dachary** [comment]
It is a subset of #5482

**Pull request closed without merging**
