### PR TITLE
rgw: fix crash in system_obj_set_attrs when got SIGHUP

### PR DESCRIPTION
**Pull request by fangyuxiangGL**

### CODE REVIEW

**Comment by fangyuxiangGL** [comment]
@cbodley 

http://tracker.ceph.com/issues/20866

My analysis:
RGWDataSyncProcessorThread is stopped prior to RGWAsyncRadosProcessor in RGWRados::finalize, which caused RGWSimpleRadosWriteAttrsCR released before RGWAsyncPutSystemObjAttrs finished.

**Comment by joscollin** [comment]
Jenkins retest this please

**Comment by fangyuxiangGL** [comment]
Jenkins retest this please

**Comment by fangyuxiangGL** [comment]
@cbodley 

Could you have a loot at this? thanks

**Comment by cbodley** [comment]
thanks @fangyuxiangGL. i think this approach is going to lead to cyclical references. in this case where `caller` appears to be `RGWSimpleRadosWriteAttrsCR`:

* `RGWSimpleRadosWriteAttrsCR` holds a reference to `RGWAsyncPutSystemObjAttrs *req`
* the `RGWAsyncPutSystemObjAttrs` parent class `RGWAsyncRadosRequest` holds a reference to `RGWAioCompletionNotifier *notifier`
* `RGWAioCompletionNotifier` now holds a reference to the `RGWSimpleRadosWriteAttrsCR`

this will prevent both from being released

i think we need to allow the `RGWAsyncRadosRequest` and `RGWCoroutine` to have distinct lifetimes. from that perspective, the real issue in this case is that `RGWAsyncPutSystemObjAttrs` has a `*attrs` member that points at memory owned by `RGWSimpleRadosWriteAttrsCR`

to fix this specific case, `RGWAsyncPutSystemObjAttrs` should own that map of `attrs` - and `RGWSimpleRadosWriteAttrsCR::send_request()` should use `std::move(attrs)` to transfer ownership to the `RGWAsyncPutSystemObjAttrs` constructor

it also looks like we have similar issues with most of the coroutines in `rgw_cr_rados.h` and their AsyncRadosRequest counterparts

does that make sense? can you try to fix all of these?

**Comment by fangyuxiangGL** [comment]
@cbodley thanks for your remind.

I think the reference relation is below:
`RGWSimpleRadosWriteAttrsCR ` hold a reference to `RGWAsyncPutSystemObjAttrs`
Parent class `RGWAsyncRadosRequest` of `RGWAsyncPutSystemObjAttrs` hold a reference to `RGWSimpleRadosWriteAttrsCR`
`RGWAsyncPutSystemObjAttrs` hold a reference to 'RGWAioCompletionNotifier'

And seems that the reference break process is as below:
step1. `RGWAsyncPutSystemObjAttrs` call `notifier->cb()` in `send_request()` when the related rados io complete, and the cr-stack of `RGWSimpleRadosWriteAttrsCR` will be add to complete queue in `notifier->cb()`, then `RGWAioCompletionNotifier` self released in the `notifier->cb()` and `notifier ` is set to `notifier = nullptr;`
step2. Coroutine `RGWSimpleRadosWriteAttrsCR` is called, and then call `request_cleanup()` in `RGWSimpleCoroutine::call_cleanup`, which call `RGWAsyncRadosRequest::finish()` and then call `put()`, so `RGWSimpleRadosWriteAttrsCR` release `RGWAsyncRadosRequest` when it complete
step3. `RGWAsyncRadosRequest` put the reference of `RGWSimpleRadosWriteAttrsCR` in its deconstructor

**Comment by fangyuxiangGL** [comment]
Hi @cbodley 

BTW, could you tell me the main purpose of PR #8765? It seems that `RGWRealmNotify::Reload` is very dangerous operation and SIGHUP is periodically called by logrotate to zip logs. `RGWRealmNotify::Reload` stop the frontend and call RGWRados::finalize, which is very dangerous. e.g. [](http://tracker.ceph.com/issues/20686), this issue and other issues. Is is more sense that don't do `RGWRealmNotify::Reload` together with `g_ceph_context->reopen_logs()`?

**Comment by fangyuxiangGL** [comment]
@cbodley 

the key of this issue is that `RGWDataSyncProcessorThread `is stopped prior to `RGWAsyncRadosProcessor` in `RGWRados::finalize`, which couse `RGWCoroutinesManager::run` break the loop for `going_down` is True. Then call `stack->put();` for all the `RGWCoroutinesStack`.

Normally this issue will not appear, for `RGWAsyncPutSystemObjAttrs` is always released prior to `RGWSimpleRadosWriteAttrsCR`

**Comment by cbodley** [comment]
> And seems that the reference break process is as below: ...

okay, thanks for the explanation. i think you're right that the reference cycle will be broken before AsyncRadosProcessor shuts down. if that's the case, i prefer your simpler fix

i was trying to test this with test_multi.py, but i'm hitting some unrelated segfaults on master. have you been able to run this under valgrind?

**Comment by cbodley** [comment]
> It seems that RGWRealmNotify::Reload is a very dangerous operation and SIGHUP is periodically called by logrotate to zip logs usually.

yeah, we wanted to be able to signal the gateway to reload its multisite configuration. we decided to piggy-back on SIGHUP, but in hindsight this seems like a bad choice. i wouldn't mind reverting that - want to open a pr for that?

**Comment by fangyuxiangGL** [comment]
> yeah, we wanted to be able to signal the gateway to reload its multisite configuration. we decided to piggy-back on SIGHUP, but in hindsight this seems like a bad choice. i wouldn't mind reverting that - want to open a pr for that?

Yes, I will open a pr to revert it with your response for the initial purpose.

> i was trying to test this with test_multi.py, but i'm hitting some unrelated segfaults on master. have you been able to run this under valgrind?

I will try to run this under valgrind, but frankly speaking, I am not familiar with valgrind in ceph, could you give me some guideline and method to analyse it?

Things will be handled next day, now it's a bit late, thanks.

**Comment by cbodley** [comment]
> I am not familiar with valgrind in ceph, could you give me some guideline and method to analyse it?

you basically just have to put `valgrind --tool=memcheck` before the radosgw command line. to run test_multi.py under valgrind, i use this diff for `src/mrgw.sh`:
```patch
diff --git a/src/mrgw.sh b/src/mrgw.sh
index c5770ca..299de97 100755
--- a/src/mrgw.sh
+++ b/src/mrgw.sh
@@ -27,4 +27,4 @@ logfile=$run_root/out/radosgw.${port}.log
 
 $vstart_path/mstop.sh $name radosgw $port
 
-$vstart_path/mrun $name radosgw --rgw-frontends="civetweb port=$port" --pid-file=$pidfile --admin-socket=$asokfile "$@" --log-file=$logfile
+valgrind --tool=memcheck --leak-check=full $ceph_bin/radosgw -c $run_root/ceph.conf --rgw-frontends="civetweb port=$port" --pid-file=$pidfile --admin-socket=$asokfile "$@" --log-file=$logfile
```

**Comment by theanalyst** [comment]
Any updates on this, @cbodley  @fangyuxiangGL

**Comment by TaveMyliuX** [comment]
Luminous 12.2.2 on centos7 ,all rgw will hung by  timed out  after logroute:

heartbeat_map is_healthy 'RGWAsyncRadosProcessor::m_tp thread 0x7f77def34700' had timed out after 600

**Comment by fangyuxiangGL** [comment]
@TaveMyliuX 

you can try Luminious 12.2.3 as #16807 is backported in it.

**Pull request closed without merging**
