### PR TITLE
OSD:lock PG when get_pg_or_queue_for_pg method successfully returns a PG

### PR DESCRIPTION
**Pull request by xiexingguo**
Otherwise caller may race with other PG users, especially with PG removal.
Fixes:#13968
Signed-off-by: xie xingguo <xie.xingguo@zte.com.cn>

### CODE REVIEW

**Comment by xiexingguo** [comment]
Dear @dachary Is build 9787(see above) a false negative? Sorry for interrupting but I am not very sure about this.

**Comment by dachary** [comment]
@xiexingguo this indeed looks like a (new) false negative. I filed a bug at http://tracker.ceph.com/issues/13969. You can repush to run again :-)

**Comment by xiexingguo** [comment]
Dear @tchaikov, glad you are back. Could you please review this for me? Thanks :)))

**Comment by tchaikov** [comment]
@xiexingguo i will review it tomorrow. sorry for the latency =(

**Comment by xiexingguo** [comment]
Dear @tchaikov,  would you please take a look at this one too? Thank you so very much

**Comment by xiexingguo** [comment]
Closed. Refer to http://tracker.ceph.com/issues/13968 for detailed information.

**Pull request closed without merging**
