### PR TITLE
RocksDBStore: filterpolicy is not deleted when RocksDBStore destructs

### PR DESCRIPTION
**Pull request by wonzhq**
Signed-off-by: Zhiqiang Wang <zhiqiang.wang@intel.com>

### CODE REVIEW

**Comment by yuyuyu101** [comment]
Good catch! But I think we need to add "delete block_cache" too.

**Comment by wonzhq** [comment]
Maybe we don't need to delete block_cache. What rocksdb::NewLRUCache returns is a smart pointer.

**Comment by yuyuyu101** [comment]
yeah, I missed. It's good to me

**Comment by wonzhq** [comment]
Thx.

**Comment by liewegas** [comment]
we could probably update the rocksdb submodule itself to the latest release too?

**Pull request merged**
