### PR TITLE
rgw/rgw_admin: Checking the legality of the parameters

### PR DESCRIPTION
**Pull request by qiankunzheng**
There is no messages When some parameters are invalid. so the Program should be added the function which checks parameters, if the parameters are invalid, the program will give some messages.

Fixes: #13018
Signed-off-by: Qiankun Zheng <zheng.qiankun@h3c.com>

### CODE REVIEW

**Comment by dachary** [comment]
please ignore the bot failure, it's a false negative

**Comment by qiankunzheng** [comment]
@yehudasa 
hi,  when can be reviewed this fix ? thank you very much

**Comment by qiankunzheng** [comment]
@yehudasa 
hi, the bug has been fixed, can you review it  when you aren't too busy ? thank you very much

**Comment by yehudasa** [comment]
@qiankunzheng it looks good to me. Not sure why the build bot didn't kick in though (@dachary ?)

**Comment by qiankunzheng** [comment]
@yehudasa  
hi, This fix has been compiled successfully by the build bot, when can be reviewed this fix ? Many thanks.

**Comment by qiankunzheng** [comment]
@yehudasa 
hi, What do you need me to do about this fix? Many thanks.

**Comment by qiankunzheng** [comment]
@yehudasa 
hi, the bug has been fixed, when can this fix be reviewed and merged?  thank you very much

**Comment by qiankunzheng** [comment]
@yehudasa 
hi, when can be reviewed this fix ? thank you very much

**Pull request merged**
