### PR TITLE
mgr/dashboard: Fix type hinting

### PR DESCRIPTION
**Pull request by votdev**
Signed-off-by: Volker Theile <vtheile@suse.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by sebastian-philipp** [comment]
```diff
diff --git a/src/pybind/mgr/tox.ini b/src/pybind/mgr/tox.ini
index 23b0573220..5e79eb4127 100644
--- a/src/pybind/mgr/tox.ini
+++ b/src/pybind/mgr/tox.ini
@@ -14,6 +14,7 @@ deps =
     mypy
 commands = mypy --config-file=../../mypy.ini \
            cephadm/module.py \
+           dashboard/module.py \
            mgr_module.py \
            mgr_util.py \
            orchestrator/__init__.py \
```

Please :smile: . This would eliminate future breakages when using the orchestrator interface.

**Comment by votdev** [comment]
> ```diff
> diff --git a/src/pybind/mgr/tox.ini b/src/pybind/mgr/tox.ini
> index 23b0573220..5e79eb4127 100644
> --- a/src/pybind/mgr/tox.ini
> +++ b/src/pybind/mgr/tox.ini
> @@ -14,6 +14,7 @@ deps =
>      mypy
>  commands = mypy --config-file=../../mypy.ini \
>             cephadm/module.py \
> +           dashboard/module.py \
>             mgr_module.py \
>             mgr_util.py \
>             orchestrator/__init__.py \
> ```
> 
> Please smile . This would eliminate future breakages when using the orchestrator interface.

We should do that in a different PR because your suggestion needs much more rework than adding this simple line.
```
ress/module.py rook/module.py osd_support/module.py test_orchestrator/module.py
dashboard/plugins/__init__.py:7: note: In module imported here,
dashboard/module.py:55: note: ... from here:
dashboard/plugins/pluggy.py: note: In member "__init__" of class "_HookRelay":
dashboard/plugins/pluggy.py:78: error: Need type annotation for '_registry'
dashboard/plugins/feature_toggles.py:10: note: In module imported here,
dashboard/module.py:56: note: ... from here:
dashboard/plugins/ttl_cache.py: note: In function "ttl_cache":
dashboard/plugins/ttl_cache.py:19: error: Need type annotation for 'cache'
dashboard/services/rgw_client.py:10: note: In module imported here,
dashboard/controllers/rgw.py:15: note: ... from here,
dashboard/plugins/feature_toggles.py:17: note: ... from here,
dashboard/module.py:56: note: ... from here:
dashboard/awsauth.py: note: In member "get_signature" of class "S3Auth":
dashboard/awsauth.py:93: error: Incompatible types in assignment (expression has type "str", variable has type "bytes")
dashboard/module.py:30: note: In module imported here:
dashboard/cherrypy_backports.py: note: In member "uuid4" of class "LazyUUID4":
dashboard/cherrypy_backports.py:177: error: Cannot determine type of '_uuid4'
dashboard/controllers/rbd.py:20: note: In module imported here,
dashboard/plugins/feature_toggles.py:12: note: ... from here,
dashboard/module.py:56: note: ... from here:
dashboard/services/rbd.py:82: error: Type signature has too few arguments
dashboard/services/rbd.py: note: In member "list" of class "RbdConfiguration":
dashboard/services/rbd.py:97: error: Bracketed expression "[...]" is not valid as a type
dashboard/services/rbd.py:97: note: Did you mean "List[...]"?
dashboard/__init__.py:35: error: Module 'tests' has no attribute 'mock'
dashboard/controllers/iscsi.py:15: note: In module imported here,
dashboard/plugins/feature_toggles.py:15: note: ... from here,
dashboard/module.py:56: note: ... from here:
dashboard/rest_client.py:27: error: Name 'SSLError' already defined (possibly by an import)
dashboard/plugins/__init__.py:74: note: In module imported here,
dashboard/module.py:55: note: ... from here:
dashboard/plugins/interfaces.py: note: In class "CanMgr":
dashboard/plugins/interfaces.py:9: error: Cannot determine type of 'mgr'
dashboard/plugins/debug.py:9: note: In module imported here,
dashboard/module.py:56: note: ... from here:
dashboard/plugins/plugin.py: note: In member "get_options" of class "SimplePlugin":
dashboard/plugins/plugin.py:20: error: "SimplePlugin" has no attribute "OPTIONS"
dashboard/plugins/plugin.py:24: error: INTERNAL ERROR -- Please try using mypy master on Github:
https://mypy.rtfd.io/en/latest/common_issues.html#using-a-development-mypy-build
If this issue continues with mypy master, please report a bug at https://github.com/python/mypy/issues
version: 0.761
dashboard/plugins/plugin.py:24: : note: please use --show-traceback to print a traceback when reporting a bug
ERROR: InvocationError for command /ceph/src/pybind/mgr/.tox/mypy/bin/mypy --config-file=../../mypy.ini cephadm/module.py dashboard/module.py mgr_module.py mgr_util.py orchestrator/__init__.py progress/module.py rook/module.py osd_support/module.py test_orchestrator/module.py (exited with code 2)
```

**Comment by sebastian-philipp** [comment]
I know, I've had the same experience a few weeks back. 

btw 

```
dashboard/plugins/plugin.py:24: error: INTERNAL ERROR -- Please try using mypy master on Github:
https://mypy.rtfd.io/en/latest/common_issues.html#using-a-development-mypy-build
```
is caused by https://github.com/python/mypy/issues/7806

**Comment by votdev** [comment]
Argghh, deleted the wrong branch. Doesn't matter, #33454 is a replacement.

**Pull request closed without merging**
