### PR TITLE
bluestore/allocator: Ageing test for bluestore allocators.

### PR DESCRIPTION
**Pull request by aclamk**
Tests performance and fragmentation for data accumulation
and storage capacity extension scenario.
In addition, special test was added to evaluate fragmentation after all space was freed.

### CODE REVIEW

**Comment by ErwanAliasr1** [comment]
PR https://github.com/ceph/ceph/pull/22571 is about introducing gtest-parallel.
Can you check if your code will be able to use it ? If so that would be a great speedup.

**Comment by liewegas** [comment]
@aclamk ping?

**Comment by liewegas** [comment]
@aclamk can we resurrect this as a unit test?  i don't think we want to lose this.  (also, i don't remember what the results of this work were with the new vs old allocator...)

**Comment by aclamk** [comment]
jenking test this please

**Comment by liewegas** [comment]
nit: s/ageing/aging/.  otherwise LGTM!

**Comment by aclamk** [comment]
"s/ageing/aging". Thanks.

**Comment by tchaikov** [comment]
merging w/o running this PR through rados qa suite. as the change does not touch production code paths. and is already exercised by "make check" run.

**Pull request merged**
