### PR TITLE
mon/Monitor.cc: exit function if !osdmon()->is_writeable() 

### PR DESCRIPTION
**Pull request by kamoltat**
Problem:

In the function `maybe_go_degraded_stretch_mode()`
when `osdmon` is not writeable we shouldn't go into
`trigger_degraded_stretch_mode` because we will
crash at `ceph_assert(osdmon()->is_writeable())`.
The current code does not exit `maybe_go_degraded_stretch_mode()`
when we are waiting for `osdmon` to be writeable, therefore,
we crash.

Solution:

Exit the function by returning nothing after going into
`wait_for_writeable_ctx`, since at that point we would have
queued the context and all we have to do is wait for finish
context to execute `maybe_go_degraded_stretch_mode` again.

Also, added a bit of logging so that user is aware
when `osdmon` and `monmon` are not writeable.

We fix other parts of the monitor code that are missing
the return after `wait_for_writeable_ctx` and `wait_for_readable_ctx`
as well.

Fixes: https://tracker.ceph.com/issues/59271

Signed-off-by: Kamoltat <ksirivad@redhat.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [x] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by kamoltat** [comment]
jenkins test api

**Comment by kamoltat** [comment]
jenkins test api

**Comment by kamoltat** [comment]
jenkins test make check arm64

**Review by gregsfortytwo — CHANGES_REQUESTED** [review]
So, while preparing for my Cephalocon talk, I discovered another missing return statement following an is_writeable/is_readable() check that isn't in this PR.

@kamoltat, I think we've found enough of these now to warrant a full audit — have you done one of those? If not, can you? I don't think it'll take that long but we definitely need to go over them all and squash this category of issue.

**Review by batrick — APPROVED** [review]
Good find!

**Comment by kamoltat** [comment]
> 

Hi @gregsfortytwo just did the audit like you asked for the Monitor part and yep just added all the missing `return` statement to other places that needed them. Let me know if I'm missing anything!

**Comment by kamoltat** [comment]
Tested the latest change with 120/120 passing jobs.

https://pulpito.ceph.com/ksirivad-2023-04-18_20:07:58-rados:standalone-wip-ksirivad-iswriteable-distro-default-smithi/

**Review by gregsfortytwo — APPROVED** [review]
Excellent, thanks!

**Comment by kamoltat** [comment]
OP_COLLECT

**Comment by kamoltat** [comment]
jenkins test windows

**Comment by kamoltat** [comment]
NOTE: since this PR fixes an issue that was discovered through a standalone test that was added to main: https://github.com/ceph/ceph/pull/47340

When back-porting it is best to combine this PR with https://github.com/ceph/ceph/pull/47340 into 1 backport.

**Comment by kamoltat** [comment]
No related failures.

Analysed both:

http://pulpito.front.sepia.ceph.com/lflores-2023-05-03_18:20:26-rados-wip-yuri-testing-2023-04-19-1343-distro-default-smithi/

[Pulpito :: Results Dashboard](https://pulpito.ceph.com/yuriw-2023-04-20_14:47:35-rados-wip-yuri-testing-2023-04-19-1343-distro-default-smithi)

Known Failures:

[Bug #59196: ceph_test_lazy_omap_stats segfault while waiting for active+clean - RADOS - Ceph](https://tracker.ceph.com/issues/59196#change-233794) ceph_test_lazy_omap_stats segfault while waiting for active+clean

[Bug #57386: cephadm/test_dashboard_e2e.sh: Expected to find content: '/^foo$/' within the selector: 'cd-modal .badge' but never did - Dashboard - Ceph](https://tracker.ceph.com/issues/57386) cephadm/test_dashboard_[e2e.sh](http://e2e.sh/)

[Bug #59057: rados/test_envlibrados_for_rocksdb.sh: No rule to make target 'rocksdb_env_librados_test' on centos 8 - RADOS - Ceph](https://tracker.ceph.com/issues/59057) rados/test_envlibrados_for_[rocksdb.sh](http://rocksdb.sh/): No rule to make target 'rocksdb_env_librados_test' on centos 8

[Bug #58585: rook: failed to pull kubelet image - Orchestrator - Ceph](https://tracker.ceph.com/issues/58585#change-230643) rook: failed to pull kubelet image

[Bug #58224: cephadm/test_repos.sh: urllib.error.HTTPError: HTTP Error 504: Gateway Timeout - Orchestrator - Ceph](https://tracker.ceph.com/issues/58224) cephadm/test_repos.sh: urllib.error.HTTPError: HTTP Error 504: Gateway Timeout

Packaging Issues - Command failed on smithi114 with status 1: 'sudo yum install -y kernel'

Packing Issues - Command failed on smithi184 with status 1: 'sudo yum -y install cephfs-java'

Import Module Issues - No module named 'tasks <module>'

Known Deadjobs:

[Bug #59380: rados/singleton-nomsgr: test failing from "Health check failed: 1 full osd(s) (OSD_FULL)" and "Health check failed: 1 filesystem is offline (MDS_ALL_DOWN)" - rgw - Ceph](https://tracker.ceph.com/issues/59380#change-234607) - rados/singleton-nomsgr: test failing from "Health check failed: 1 full osd(s) (OSD_FULL)" and "Health check failed: 1 filesystem is offline (MDS_ALL_DOWN)"

Error reimaging machines: reached maximum tries (60) after waiting for 900 seconds

centos8 ansible error: Failed to download metadata for repo 'CentOS-PowerTools': Yum repo downloading error

**Pull request merged**
