### PR TITLE
luminous: rgw: bucket policy evaluation logical error

### PR DESCRIPTION
**Pull request by adamemerson**
http://tracker.ceph.com/issues/22602

### CODE REVIEW

**Comment by shinobu-x** [comment]
@adamemerson can you follow:

> http://tracker.ceph.com/projects/ceph-releases/wiki/HOWTO_backport_commits

**Comment by adamemerson** [comment]
Jenkins, retest this please.

**Comment by smithfarm** [comment]
@adamemerson Thanks for the backport (again)! The workflow for backport PRs is different than for PRs targeting master. Whereas in master the idea is to get a positive review first, and then proceed with testing, for backports this is reversed: first the backport PR undergoes integration testing (we gang them up for this), and then it is reviewed. It can be reviewed by anyone, but the only reviews that "count" are ones from either the component lead or from the person who merged the corresponding master PR that is being cherry-picked.

(It would be great if someone helped with testing rgw backports PRs. . . like I said, they can be ganged up and tested in batches.)

**Comment by yuriw** [comment]
[wip-yuri4-testing-2018-01-16-2200](https://trello.com/c/tXbuDRQm/230-wip-yuri4-testing-2018-01-16-2200)

**Comment by yuriw** [comment]
@adamemerson @smithfarm @theanalyst @cbodley ready for merge

**Pull request merged**
