### PR TITLE
Librbd cache iohint

### PR DESCRIPTION
**Pull request by majianpeng**
make librbd cache handle nocache fadvise flags.

### CODE REVIEW

**Comment by majianpeng** [comment]
@liewegas . Find two question:
A)for read, avoid later lose bh for rx & hit, we call touch_bh. In fact, in there we should use bh->get() to instead. Because bh split/merge, it difficult using bh->get() 
B)For write, if bh->is_rx() and we can modify bh with new data. If message use crc when send. There is chance that partly write data cause crc error. Is it correct?

**Comment by majianpeng** [comment]
@liewegas . ping

**Comment by majianpeng** [comment]
Read code again, i found there is no change parity write case Message CRC error. This is because in librbd::aio_write, it copy data from use-buffer into librbd buffer.  In Message, the crc buffer isn't those new data buffer. Is it correctly?

**Comment by liewegas** [comment]
rebase?

**Comment by majianpeng** [comment]
rebase and remove 2 patches because dillaman already done and merged in master. Please review again. Thanks!

**Pull request merged**
