### PR TITLE
octopus: cephadm: Various properties like 'last_refresh' do not contain timezone

### PR DESCRIPTION
**Pull request by votdev**
Fixes: https://tracker.ceph.com/issues/48068

Signed-off-by: Volker Theile <vtheile@suse.com>
(cherry picked from commit 3fe715201c8c07cf4ea86b590f9682422eeccf33)

## Checklist
- [x] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by votdev** [comment]
jenkins test make check

**Comment by votdev** [comment]
jenkins test make check

**Comment by votdev** [comment]
jenkins test make check

**Comment by votdev** [comment]
jenkins test make check

**Comment by sebastian-philipp** [comment]
https://pulpito.ceph.com/swagner-2021-01-28_09:49:52-rados:cephadm-wip-swagner4-testing-2021-01-27-1348-octopus-distro-basic-smithi/

* https://tracker.ceph.com/issues/48142
* https://github.com/containers/podman/issues/9096

**Review by sebastian-philipp — APPROVED** [review]

**Pull request merged**
