### PR TITLE
osd/OSD.cc : drop write if pool is full

### PR DESCRIPTION
**Pull request by xinxinsh**
Signed-off-by: xinxin shu <xinxin.shu@intel.com>

### CODE REVIEW

**Comment by gregsfortytwo** [comment]
Don't we handle this case elsewhere? Or do we handle a full cluster but not full pools? I'm just confused about what this is for and why it wouldn't include some client-side handling and/or config options.

**Comment by xinxinsh** [comment]
what do you mean "full cluster", do you mean osd full ?

2015-06-17 16:59 GMT+08:00 Gregory Farnum <notifications@github.com>:

**Comment by gregsfortytwo** [comment]
Yeah, the FULL flag in the OSDMap, which is set when one of the OSDs
exceeds the full threshold.

**Comment by xinxinsh** [comment]
@gregsfortytwo   check of FULL flag in the OSDMap (https://github.com/ceph/ceph/blob/master/src/osd/OSD.cc#L8055) is just before this , so if cluster is full cluster but not full pools,  handle_op function will directly return at https://github.com/ceph/ceph/blob/master/src/osd/OSD.cc#L8061

**Comment by jdurgin** [comment]
@gregsfortytwo this is about pool quotas. Writes in this condition are already rejected in ReplicatedPG.cc here: https://github.com/ceph/ceph/blob/b7abc398c03fa20a95e3081a2c09f11abc2cadf4/src/osd/ReplicatedPG.cc#L2323

I think @xinxinsh was looking at this in the context of http://tracker.ceph.com/issues/12018
I'll put more references to how I think this should work there.

Returning -ENOSPC up through the rbd layer is one of the problems.

**Pull request closed without merging**
