### PR TITLE
os/bluestore: ensure fsck repair transactions succeed

### PR DESCRIPTION
**Pull request by TheJJ**
I found this while investigating https://tracker.ceph.com/issues/50017.

## Checklist
- [x] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by tchaikov** [comment]
failure tracked by https://tracker.ceph.com/issues/50028

**Comment by tchaikov** [comment]
jenkins test make check

**Comment by tchaikov** [comment]
@ifed01 hi Igor, could you kindly take a look?

**Comment by tchaikov** [comment]
- https://pulpito.ceph.com/kchai-2021-03-27_12:17:59-rados-wip-kefu-testing-2021-03-27-1545-distro-basic-gibba/
- https://pulpito.ceph.com/kchai-2021-03-28_03:01:25-rados-wip-kefu-testing-2021-03-27-1545-distro-basic-smithi/

failures

- https://tracker.ceph.com/issues/49344
- https://tracker.ceph.com/issues/49260
- https://tracker.ceph.com/issues/49633

**Review by ifed01 — COMMENTED** [review]
In general LGTM but I'd prefer not to have acting calls as a parameters to ceph_assert. 
Hence suggest something like
auto b = db->dubmit_transaction_sync(...) == 0;
ceph_assert(b);

**Review by ifed01 — APPROVED** [review]

**Comment by tchaikov** [comment]
- https://pulpito.ceph.com/kchai-2021-04-02_15:50:13-rados-wip-kefu-testing-2021-04-02-1506-distro-basic-gibba/
- https://pulpito.ceph.com/kchai-2021-04-03_11:44:43-rados-wip-kefu-testing-2021-04-03-1318-distro-basic-smithi/

**Comment by TheJJ** [comment]
nice! shall we backport it since i encountered this on octopus?

**Pull request merged**
