### PR TITLE
rgw: drop dead flush_read_list declaration

### PR DESCRIPTION
**Pull request by mikulely**
## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test docs`
- `jenkins render docs`

</details>

### CODE REVIEW

**Comment by tchaikov** [comment]
@mikulely i think this change is still relevant. why did you close it?

**Comment by cbodley** [comment]
make check failing on `VERSION='16.04.6 LTS (Xenial Xerus)'`. it reports `CXX_STANDARD: 11` and has lots of warnings/errors:
```
[ 79%] Building CXX object src/rgw/CMakeFiles/rgw_a.dir/rgw_loadgen.cc.o
In file included from /home/jenkins-build/build/workspace/ceph-pull-requests/src/rgw/rgw_dmclock_scheduler.h:18,
                 from /home/jenkins-build/build/workspace/ceph-pull-requests/src/rgw/rgw_dmclock_sync_scheduler.h:18,
                 from /home/jenkins-build/build/workspace/ceph-pull-requests/src/test/rgw/test_rgw_dmclock_scheduler.cc:17:
/home/jenkins-build/build/workspace/ceph-pull-requests/src/common/ceph_time.h:504:16: warning: variable templates only available with -std=c++14 or -std=gnu++14
 constexpr bool converts_to_timespec_v = converts_to_timespec<Clock>::value;
```

**Comment by tchaikov** [comment]
@cbodley the FTBFS is supposed to be fixed by #29291

**Comment by tchaikov** [comment]
retest this please.

**Pull request merged**
