### PR TITLE
pacific: mgr: various fixes for mgr scalability

### PR DESCRIPTION
**Pull request by neha-ojha**
Backports:

- https://github.com/ceph/ceph/pull/44073
- https://github.com/ceph/ceph/pull/44208
- https://github.com/ceph/ceph/pull/44155
- https://github.com/ceph/ceph/pull/44162 

These fixes were identified to help with mgr scalability during Pawsey scale testing.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Review by adk3798 — APPROVED** [review]

**Comment by neha-ojha** [comment]
Changelog

- Rebased to resolve minor conflict in src/pybind/mgr/progress/module.py

**Comment by vumrao** [comment]
@vumrao

**Comment by neha-ojha** [comment]
jenkins test make check

**Review by pereman2 — APPROVED** [review]

**Comment by neha-ojha** [comment]
Changelog

- Add 288b80b7f5f0f48e0f691bf2b252e0d356cc5b34 to address failures like http://pulpito.front.sepia.ceph.com/yuriw-2022-02-10_23:42:14-rados-wip-yuri10-testing-2022-02-09-1352-pacific-distro-default-smithi/6675148/

```
2022-02-06T07:27:13.493+0000 7f5efede2700 10 ceph_option_get osd_pool_default_size found: 2
2022-02-06T07:27:13.493+0000 7f5efede2700  0 [devicehealth WARNING root] Not enough OSDs yet to create monitoring pool
...
2022-02-06T08:00:08.609+0000 7f2a6c782700  0 [dashboard ERROR exception] Dashboard Exception
Traceback (most recent call last):
  File "/usr/share/ceph/mgr/dashboard/services/exception.py", line 71, in handle_rados_error
    yield
  File "/usr/share/ceph/mgr/dashboard/services/exception.py", line 46, in dashboard_exception_handler
    return handler(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/cherrypy/_cpdispatch.py", line 54, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/usr/share/ceph/mgr/dashboard/controllers/_base_controller.py", line 258, in inner
    ret = func(*args, **kwargs)
  File "/usr/share/ceph/mgr/dashboard/controllers/_rest_controller.py", line 191, in wrapper
    return func(*vpath, **params)
  File "/usr/share/ceph/mgr/dashboard/controllers/pool.py", line 284, in configuration
    return RbdConfiguration(pool_name).list()
  File "/usr/share/ceph/mgr/dashboard/services/rbd.py", line 146, in list
    ioctx = mgr.rados.open_ioctx(self._pool_name)
  File "rados.pyx", line 982, in rados.Rados.open_ioctx
rados.ObjectNotFound: [errno 2] RADOS object not found (error opening pool 'device_health_metrics')
```

**Comment by neha-ojha** [comment]
jenkins test make check

**Comment by neha-ojha** [comment]
jenkins retest this please

**Comment by neha-ojha** [comment]
Dropping https://github.com/ceph/ceph/pull/44207 due to lot of conflicts now

Test runs+reruns - https://pulpito.ceph.com/?branch=wip-mgr-fixes-pacific-gil

@adk3798 can you please review the cephadm failures in the last rerun https://pulpito.ceph.com/nojha-2022-02-18_01:15:24-rados-wip-mgr-fixes-pacific-gil-distro-basic-smithi/ to see if you find anything related, otherwise looks good

**Comment by adk3798** [comment]
> Dropping #44207 due to lot of conflicts now
> 
> Test runs+reruns - https://pulpito.ceph.com/?branch=wip-mgr-fixes-pacific-gil
> 
> @adk3798 can you please review the cephadm failures in the last rerun https://pulpito.ceph.com/nojha-2022-02-18_01:15:24-rados-wip-mgr-fixes-pacific-gil-distro-basic-smithi/ to see if you find anything related, otherwise looks good

Almost all errors fall under one of these which happens independent of this PR
https://tracker.ceph.com/issues/53939
https://tracker.ceph.com/issues/54304
https://tracker.ceph.com/issues/54071
https://tracker.ceph.com/issues/54273

I've never seen that rm-zap-flag failure before where the osd never comes up after attempted replacement but I don't think this PR is causing it. More likely it's just an unlikely failure that happened to pop up here imo.

**Comment by neha-ojha** [comment]
jenkins test dashboard

**Comment by neha-ojha** [comment]
@ceph/dashboard can someone please help me understand if the dashboard test failure is related or not?

**Comment by nizamial09** [comment]
> @ceph/dashboard can someone please help me understand if the dashboard test failure is related or not?

Looked unrelated. So I triggered again and it failed due to a flaky test. So I would say its good to go.

**Review by nizamial09 — APPROVED** [review]

**Pull request merged**
