### PR TITLE
[DNM] ceph-disk: support osd new

### PR DESCRIPTION
**Pull request by tchaikov**
for testing the proposed change on top of #15432

### CODE REVIEW

**Comment by GregMeno** [comment]
This seems to be missing docs describing the usage of osd new. Would you please add them?

**Comment by tchaikov** [comment]
@GregMeno "ceph osd new" is documented by ceph's manpage, see http://docs.ceph.com/docs/master/man/8/ceph/, search for "ceph osd new" in that web page.

**Comment by tchaikov** [comment]
whitelisting the health warnings addresses the failures in http://pulpito.ceph.com/kchai-2017-07-14_16:33:13-ceph-disk-master-distro-basic-vps/

**Comment by tchaikov** [comment]
closed as #15432 has the proposed change already.

**Pull request closed without merging**
