### PR TITLE
common,mds,mgr,mon,osd: store event only if it's added

### PR DESCRIPTION
**Pull request by tchaikov**
otherwise
* we will try to cancel it even it's never been added
* we will keep a dangling pointer around. which is, well,
  scaring.
* static analyzer will yell at us:
  Memory - illegal accesses  (USE_AFTER_FREE)

Signed-off-by: Kefu Chai <kchai@redhat.com>

### CODE REVIEW

**Comment by tchaikov** [comment]
retest this please.

**Comment by tchaikov** [comment]
retest this please.

**Comment by liewegas** [comment]
This seems right.  I'm scared about the number of call sites that have to change, though, and that we'll introduce something subtle.  :(

**Comment by dillaman** [comment]
Hold this PR for mimic?

**Comment by tchaikov** [comment]
http://pulpito.ceph.com/kchai-2017-07-13_18:13:10-rados-wip-kefu-testing-distro-basic-smithi/
failed tests are either tracker or fixed already

- new: http://tracker.ceph.com/issues/20625
- new: http://tracker.ceph.com/issues/20624 
- fixed already: http://tracker.ceph.com/issues/20208

**Comment by tchaikov** [comment]
i am fine either way. the fix mostly addresses the possible crashes after timer is shutdown, and this only happens when the daemon is being brought down.

**Comment by liewegas** [comment]
@jdurgin what do you think?

**Comment by jdurgin** [comment]
Unless this is causing a bunch of noise in the tests, I'd prefer postponing to mimic

**Comment by tchaikov** [comment]
okay, so far no noises is observed in tests caused by the problem mentioned above. let's hold this PR for mimic!

**Comment by tchaikov** [comment]
@jdurgin @dillaman could you take a look at this PR again? as luminous has been forked, it's relatively safe to have this change in master now.

**Comment by tchaikov** [comment]
http://pulpito.ceph.com/kchai-2017-08-20_09:42:12-rados-wip-kefu-testing-distro-basic-mira/

**Pull request merged**
