### PR TITLE
An empty bucket or OSD is not an error

### PR DESCRIPTION
**Pull request by badone**
Fixes: https://tracker.ceph.com/issues/48884

## Checklist
- [x] References tracker ticket
- [ ] Updates documentation if necessary
- [x] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by badone** [comment]
Changing the test here to be more robust.

**Comment by badone** [comment]
@jdurgin How about this?

**Review by jdurgin — APPROVED** [review]
That json-handling in c++ turned out much nicer than I expected!

**Comment by badone** [comment]
> That json-handling in c++ turned out much nicer than I expected!

Yeah, quite happy with the result. Thanks!

**Comment by ideepika** [comment]
http://pulpito.front.sepia.ceph.com/ideepika-2021-01-22_07:01:14-rados-wip-deepika-testing-master-2021-01-22-0047-distro-basic-smithi/
rerun: http://pulpito.front.sepia.ceph.com/ideepika-2021-01-25_12:19:15-rados-wip-deepika-testing-2021-01-25-1527-distro-basic-smithi/
failure not related and tracked by:
https://tracker.ceph.com/issues/48981
https://tracker.ceph.com/issues/48982

**Comment by ideepika** [comment]
http://pulpito.front.sepia.ceph.com/ideepika-2021-01-22_07:01:14-rados-wip-deepika-testing-master-2021-01-22-0047-distro-basic-smithi/
rerun: http://pulpito.front.sepia.ceph.com/ideepika-2021-01-25_12:19:15-rados-wip-deepika-testing-2021-01-25-1527-distro-basic-smithi/
failure not related and tracked by:
https://tracker.ceph.com/issues/48981
https://tracker.ceph.com/issues/48982

**Pull request merged**
