### PR TITLE
rgw: qa: add a scheduler task

### PR DESCRIPTION
**Pull request by theanalyst**
Signed-off-by: Abhishek Lekshmanan <abhishek@suse.com>

- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by tchaikov** [comment]
retest this please

**Comment by theanalyst** [comment]
I have a first run that failed, as I can't find the admin socket, http://qa-proxy.ceph.com/teuthology/abhi-2019-04-09_11:40:22-rgw-master-distro-basic-smithi/3827826/teuthology.log

I have set the admin socket in the client overrides, but that doesn't seem to have actually been used there

**Comment by theanalyst** [comment]
sort of had the tests actually running and passing (and failing to remove dir. in the end because of sudo) http://pulpito.ceph.com/abhi-2019-04-09_15:42:52-rgw-master-distro-basic-smithi/, I'll now try to not use a repo and bring the tests in the ceph tree itself

**Comment by theanalyst** [comment]
have a passing test http://qa-proxy.ceph.com/teuthology/abhi-2019-04-10_16:28:26-rgw-master-distro-basic-smithi/3831079/teuthology.log

will clean up the branch and open it for review soon

**Comment by theanalyst** [comment]
Have an initial version that just simply tests the throttler by keeping rgw_max_concurrent_requests to 100 and validating that we are hitting a req_denied that the client sees and what perf throttle counter reports. (Can extend a couple of more throttler cases to ensure that we've hit the throttle with config set  as well as the current form will pass if there was no throttle)

**Comment by theanalyst** [comment]
jenkins test this please

**Comment by theanalyst** [comment]
the make check python3-cython failures seem to be present in other PRs as well

**Pull request closed without merging**
