### PR TITLE
auth, crypto: optimize encrypt/decrypt and signature check

### PR DESCRIPTION
**Pull request by liewegas**

### CODE REVIEW

**Comment by liewegas** [comment]
still buggy

**Comment by markhpc** [comment]
Segfaults on ceph health :)

**Comment by liewegas** [comment]
passed my test run

**Comment by liewegas** [comment]
@athanatos how do you feel about this one?

**Comment by athanatos** [comment]
it's probably ok if we merge today

**Comment by liewegas** [comment]
repushed.  fixed

- footer flag
- added return codes to simplify things a bit
- made nss stuff private

**Comment by liewegas** [comment]
https://github.com/ceph/ceph/pull/3896

**Pull request closed without merging**
