### PR TITLE
common, crimson: reuse the interpreter of Option::TYPE_BOOL

### PR DESCRIPTION
**Pull request by rzarzynski**
## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by tchaikov** [comment]
- https://pulpito.ceph.com/kchai-2020-06-25_14:36:27-rados-wip-kefu-testing-2020-06-25-1815-distro-basic-smithi/
- https://pulpito.ceph.com/kchai-2020-06-27_03:47:06-rados-wip-kefu-testing-2020-06-26-1211-distro-basic-smithi/
- https://pulpito.ceph.com/kchai-2020-06-27_07:37:00-rados-wip-kefu-testing-2020-06-27-1407-distro-basic-smithi/

failures tracked by

- https://tracker.ceph.com/issues/46054
- https://tracker.ceph.com/issues/45721
- https://tracker.ceph.com/issues/44595

**Comment by tchaikov** [comment]
```
Traceback (most recent call last):
  File "/home/jenkins-build/build/workspace/ceph-perf-classic/cbt/compare.py", line 69, in <module>
    main()
  File "/home/jenkins-build/build/workspace/ceph-perf-classic/cbt/compare.py", line 51, in main
    results.extend(current.evaluate(baseline))
  File "/home/jenkins-build/build/workspace/ceph-perf-classic/cbt/benchmark/benchmark.py", line 100, in evaluate
    compare_results = self._compare_client_results(client_run, self_analyzer, baseline_analyzer)
  File "/home/jenkins-build/build/workspace/ceph-perf-classic/cbt/benchmark/benchmark.py", line 66, in _compare_client_results
    self_analyzer_res[name] = self_getter()
  File "/home/jenkins-build/build/workspace/ceph-perf-classic/cbt/benchmark/radosbench.py", line 269, in get_cpu_cycles_per_op
    num_cpu_cycles = self.get_cpu_cycles()
  File "/home/jenkins-build/build/workspace/ceph-perf-classic/cbt/benchmark/radosbench.py", line 266, in get_cpu_cycles
    return monitoring.get_cpu_cycles(self.out_dir)
  File "/home/jenkins-build/build/workspace/ceph-perf-classic/cbt/monitoring.py", line 158, in get_cpu_cycles
    return monitoring_profile.get_cpu_cycles(out_dir) # if it is, then return the number of cycle
  File "/home/jenkins-build/build/workspace/ceph-perf-classic/cbt/monitoring.py", line 97, in get_cpu_cycles
    cpu_cycles = ((re.search(r'(.*) cycles(.*?) .*', perf_output_file.read(), re.M|re.I)).group(1)).strip()
AttributeError: 'NoneType' object has no attribute 'group'
```

**Comment by tchaikov** [comment]
@AmnonHanuhov could you help take a look at this failure?

**Comment by AmnonHanuhov** [comment]
> @AmnonHanuhov could you help take a look at this failure?

Yes, I will take a look at it first thing tomorrow morning

**Comment by AmnonHanuhov** [comment]
> ```
> Traceback (most recent call last):
>   File "/home/jenkins-build/build/workspace/ceph-perf-classic/cbt/compare.py", line 69, in <module>
>     main()
>   File "/home/jenkins-build/build/workspace/ceph-perf-classic/cbt/compare.py", line 51, in main
>     results.extend(current.evaluate(baseline))
>   File "/home/jenkins-build/build/workspace/ceph-perf-classic/cbt/benchmark/benchmark.py", line 100, in evaluate
>     compare_results = self._compare_client_results(client_run, self_analyzer, baseline_analyzer)
>   File "/home/jenkins-build/build/workspace/ceph-perf-classic/cbt/benchmark/benchmark.py", line 66, in _compare_client_results
>     self_analyzer_res[name] = self_getter()
>   File "/home/jenkins-build/build/workspace/ceph-perf-classic/cbt/benchmark/radosbench.py", line 269, in get_cpu_cycles_per_op
>     num_cpu_cycles = self.get_cpu_cycles()
>   File "/home/jenkins-build/build/workspace/ceph-perf-classic/cbt/benchmark/radosbench.py", line 266, in get_cpu_cycles
>     return monitoring.get_cpu_cycles(self.out_dir)
>   File "/home/jenkins-build/build/workspace/ceph-perf-classic/cbt/monitoring.py", line 158, in get_cpu_cycles
>     return monitoring_profile.get_cpu_cycles(out_dir) # if it is, then return the number of cycle
>   File "/home/jenkins-build/build/workspace/ceph-perf-classic/cbt/monitoring.py", line 97, in get_cpu_cycles
>     cpu_cycles = ((re.search(r'(.*) cycles(.*?) .*', perf_output_file.read(), re.M|re.I)).group(1)).strip()
> AttributeError: 'NoneType' object has no attribute 'group'
> ```

How can I recreate this on my machine?

**Pull request merged**
