### PR TITLE
luminous: prometheus module 500 if 'deep' in pg states

### PR DESCRIPTION
**Pull request by shinobu-x**
http://tracker.ceph.com/issues/22238

### CODE REVIEW

**Comment by smithfarm** [comment]
Note: I tried it and both commits should cherry-pick cleanly into this branch.

**Comment by pewpewp3w** [comment]
Also there is same problem with "activating" state

**Comment by jan--f** [comment]
@pewpewp3w right. I took the PG States from the docs mentioned #18890. Not the best idea it seems, I'll find a better source. In any case that would be a separate issue.

**Comment by jcsp** [comment]
Closing in favour of https://github.com/ceph/ceph/pull/19929

**Pull request closed without merging**
