### PR TITLE
luminous: rgw: S3 v4 auth fails when query string contains  

### PR DESCRIPTION
**Pull request by theanalyst**
http://tracker.ceph.com/issues/21043

### CODE REVIEW

**Comment by theanalyst** [comment]
jenkins test this please

**Comment by theanalyst** [comment]
jenkins test this please

**Comment by smithfarm** [comment]
Jenkins re-test this please

**Comment by theanalyst** [comment]
strange that the other luminous backport passed then

**Comment by theanalyst** [comment]
enkins re-test this please (the test_pidfile.sh failed)

**Comment by theanalyst** [comment]
jenkins retest this please

**Comment by smithfarm** [comment]
Sounds like we need to backport @dzafman 's test_pidfile.sh fixes as a matter of urgency.

**Comment by smithfarm** [comment]
See https://github.com/ceph/ceph/pull/17161

**Comment by theanalyst** [comment]
@smithfarm yes, agree

**Pull request merged**
