### PR TITLE
pacific: run-make-check.sh: enable RBD persistent caches

### PR DESCRIPTION
**Pull request by idryomov**
backport tracker: https://tracker.ceph.com/issues/55392

---

backport of https://github.com/ceph/ceph/pull/45872 and https://github.com/ceph/ceph/pull/46600
parent tracker: https://tracker.ceph.com/issues/55285

### CODE REVIEW

**Comment by idryomov** [comment]
jenkins test make check

**Comment by idryomov** [comment]
jenkins test make check

**Review by ideepika — APPROVED** [review]

**Comment by ideepika** [comment]
failure looks unrelated:
```
[ 48%] Building CXX object src/crimson/CMakeFiles/crimson-common.dir/__/crush/CrushTester.cc.o
make[3]: *** [src/pybind/mgr/dashboard/CMakeFiles/mgr-dashboard-openapi-venv.dir/build.make:61: mgr-dashboard-openapi-virtualenv/bin/activate] Error 1
make[3]: *** Deleting file 'mgr-dashboard-openapi-virtualenv/bin/activate'
make[2]: *** [CMakeFiles/Makefile2:9177: src/pybind/mgr/dashboard/CMakeFiles/mgr-dashboard-openapi-venv.dir/all] Error 2
make[2]: *** Waiting for unfinished jobs....
```

**Comment by ideepika** [comment]
jenkins test make check

**Comment by idryomov** [comment]
@epuertat Please take a look at the `mgr-dashboard-openapi-virtualenv/bin/activate] Error 1` failure.

**Comment by epuertat** [comment]
> @epuertat Please take a look at the `mgr-dashboard-openapi-virtualenv/bin/activate] Error 1` failure.

Hi @idryomov the failure seems to do with the `xmlsec` package cached during the install-deps.sh stage:

```
ERROR: Wheel 'xmlsec' located at /home/jenkins-build/build/workspace/ceph-pull-requests/install-deps-cache/pip/wheels/2c/99/a3/98bcb24586c778eb35e23e30af30fbf1c34a0a9ed85e18576a/xmlsec-1.3.12-cp38-cp38-linux_x86_64.whl is invalid.
  Created wheel for xmlsec: filename=xmlsec-1.3.12-cp38-cp38-linux_x86_64.whl size=199776 sha256=ed630da54f06f25182232eb7bfe871c453b5d2ec95e29d54702812ec752061dc
  Stored in directory: /home/jenkins-build/build/workspace/ceph-pull-requests/install-deps-cache/pip/wheels/2c/99/a3/98bcb24586c778eb35e23e30af30fbf1c34a0a9ed85e18576a
```

However, I'm checking failures at other pacific builds (or any branch builds at all) and I don't see this reproduced.... Maybe it's a cleanup issue? @djgalloway anything specific to this irvingi03 machine?

**Comment by epuertat** [comment]
jenkins test make check

**Comment by idryomov** [comment]
jenkins test make check

**Comment by djgalloway** [comment]
jenkins test make check

**Comment by idryomov** [comment]
The build is failing in one the pmem libraries, it looks like:
```
uuid.c:56:35: error: argument 1 of type 'const char *' declared as a pointer [-Werror=array-parameter=]
   56 | util_uuid_from_string(const char *uuid, struct uuid *ud)
      |                       ~~~~~~~~~~~~^~~~
In file included from uuid.c:11:
uuid.h:39:38: note: previously declared as an array 'const char[37]'
   39 | int util_uuid_from_string(const char uuid[POOL_HDR_UUID_STR_LEN],
      |                           ~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~
```
I rebased just in case but it didn't help.

**Comment by idryomov** [comment]
https://github.com/pmem/pmdk/commit/57a7e50be71e2677a5cb1a84b5f462d40182dee8

**Comment by ljflores** [comment]
Rados suite review for documentation:

http://pulpito.front.sepia.ceph.com/yuriw-2022-06-07_19:48:58-rados-wip-yuri6-testing-2022-06-07-0955-pacific-distro-default-smithi/

Failures, unrelated:
    1. https://tracker.ceph.com/issues/53939
    2. https://tracker.ceph.com/issues/53827
    3. https://tracker.ceph.com/issues/54071
    4. https://tracker.ceph.com/issues/54992
    5. https://tracker.ceph.com/issues/49525
    6. https://tracker.ceph.com/issues/55741
    7. https://tracker.ceph.com/issues/52321
    8. https://tracker.ceph.com/issues/50222
    9. https://tracker.ceph.com/issues/53501
    10. https://tracker.ceph.com/issues/56028 --> opened a new Tracker for this; it is unrelated to the PRs that were tested in this run.

Details:
    1. ceph-nfs-upgrade, pacific: Upgrade Paused due to UPGRADE_REDEPLOY_DAEMON: Upgrading daemon osd.0 on host smithi103 failed - Ceph - Orchestrator
    2. cephadm exited with error code when creating osd: Input/Output error. Faulty NVME? - Ceph - Orchestrator
    3. rados/cephadm/osds: Invalid command: missing required parameter hostname(<string>) - Ceph - Orchestrator
    4. cannot stat '/etc/containers/registries.conf': No such file or directory - Ceph - Orchstrator
    5. found snap mapper error on pg 3.2s1 oid 3:4abe9991:::smithi10121515-14:e4 snaps missing in mapper, should be: dc was r -2...repaired - Ceph - RADOS (pending Pacific backport)
    6. cephadm/test_dashboard_e2e.sh: Unable to find element `cd-modal .custom-control-label` when testing on orchestrator/01-hosts.e2e-spec.ts - Ceph - Mgr - Dashboard
    7. qa/tasks/rook times out: 'check osd count' reached maximum tries (90) after waiting for 900 seconds - Ceph - Orchestrator
    8. osd: 5.2s0 deep-scrub : stat mismatch - Ceph - RADOS
    9. Exception when running 'rook' task. - Ceph - Orchestrator
    10. thrash_cache_writeback_proxy_none: FAILED ceph_assert(version == old_value.version) in src/test/osd/RadosModel.h - Ceph - RADOS

**Pull request merged**
