### PR TITLE
test/store_test: get rid off assert_death.

### PR DESCRIPTION
**Pull request by ifed01**
Looks like death assertions aren't 100% reliable and might cause deadlock sometimes.
Hence getting rid of them and enabling optional sending exception from *Store::queue_transaction()

Fixes: https://tracker.ceph.com/issues/61193

Signed-off-by: Igor Fedotov <igor.fedotov@croit.io>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by ifed01** [comment]
jenkins test api

**Review by pereman2 — APPROVED** [review]

**Review by aclamk — APPROVED** [review]

**Comment by yuriw** [comment]
@ifed01 I suspect this PR broke the build:

https://jenkins.ceph.com/job/ceph-dev-new-build/ARCH=x86_64,AVAILABLE_ARCH=x86_64,AVAILABLE_DIST=centos8,DIST=centos8,MACHINE_SIZE=gigantic/75654//consoleFull

build/ARCH/x86_64/AVAILABLE_ARCH/x86_64/AVAILABLE_DIST/centos8/DIST/centos8/MACHINE_SIZE/gigantic/release/19.0.0-625-g42d98088/rpm/el8/BUILD/ceph-19.0.0-625-g42d98088/src/os/bluestore/BlueStore.cc: In member function ‘void BlueStore::Blob::finish_write(uint64_t)’:
/home/jenkins-build/build/workspace/ceph-dev-new-build/ARCH/x86_64/AVAILABLE_ARCH/x86_64/AVAILABLE_DIST/centos8/DIST/centos8/MACHINE_SIZE/gigantic/release/19.0.0-625-g42d98088/rpm/el8/BUILD/ceph-19.0.0-625-g42d98088/src/os/bluestore/BlueStore.cc:2935:22: error: ‘coll’ was not declared in this scope; did you mean ‘cosl’?
 2935 | #define dout_context coll->store->cct
      |                      ^~~~

**Comment by yuriw** [comment]
maybe this https://github.com/ceph/ceph/pull/53565

**Comment by NitzanMordhai** [comment]
Rados approved: https://tracker.ceph.com/projects/rados/wiki/MAIN#httpstrellocomc6oYH6qSe1924-wip-yuri3-testing-2024-01-10-0735-old-wip-yuri3-testing-2024-01-09-1342

**Pull request merged**
