### PR TITLE
sysctl.d: set kernel.pid_max=4194304

### PR DESCRIPTION
**Pull request by ddiss**
For CONFIG_BASE_FULL Linux kernels, the maximum number of proc/thread
IDs is set to 32768 by default. This default limit can be quite easily
hit during recovery on nodes with high OSD counts.
To avoid hitting the pid_max default limit, attempt to configure it to
4194304, which corresponds to the maximum limit possible on 64-bit
CONFIG_BASE_FULL kernels.

Fixes: http://tracker.ceph.com/issues/21929

Signed-off-by: David Disseldorp <ddiss@suse.de>

### CODE REVIEW

**Comment by ddiss** [comment]
This was raised and submitted separately following discussion in https://github.com/ceph/ceph/pull/17894

**Comment by ddiss** [comment]
ping, is there anything blocking the merge here?

**Comment by smithfarm** [comment]
@tchaikov @theanalyst @yuriw Could you include this in your next rados run?

**Comment by tchaikov** [comment]
@smithfarm @ddiss is it possible to conditionize this on 32bit arch and 64bit arch? or use a .in file for creating the `90-ceph-osd.conf` for different archs? if we apply this setting on a x86 box, it will complain

> error: "Invalid argument" setting key "kernel.pid_max"

**Comment by ddiss** [comment]
It doesn't look like conditions can be nested in the sysctl file itself. I'll go with the .in file approach. It probably makes sense to move it out of src/ too - should I nest it under systemd/ in the top level?

**Comment by ddiss** [comment]
> should I nest it under systemd/ in the top level?

etc/sysctl/90-ceph-osd.conf.in looks like a better option.

**Comment by tchaikov** [comment]
http://pulpito.ceph.com/kchai-2017-11-14_08:08:02-rados-wip-kefu-testing-2017-11-14-1048-distro-basic-mira/

**Comment by ddiss** [comment]
This new version moves 90-ceph-osd.conf under etc/sysctl/ , and adds conditional 64-bit logic, as requested by @tchaikov .
The generated 90-ceph-osd.conf  file is placed in the source directory, rather than the cmake build directory, to avoid extra packaging changes. If a CMAKE_INSTALL_SYSCTLDIR variable were available, then it'd probably be worth adding the install logic to etc/sysctl/CMakeLists.txt .

**Comment by tchaikov** [comment]
- http://pulpito.ceph.com/kchai-2017-11-18_15:01:48-rados-wip-kefu-testing-2017-11-18-2124-distro-basic-mira/
- http://pulpito.ceph.com/kchai-2017-11-20_05:45:10-rados-wip-kefu-testing-2017-11-18-2124-distro-basic-mira/
- http://pulpito.ceph.com/kchai-2017-11-20_06:28:09-rados-wip-kefu-testing-2017-11-18-2124-distro-basic-mira/

**Pull request merged**
