### PR TITLE
crush: optimal is hammer

### PR DESCRIPTION
**Pull request by liewegas**
http://tracker.ceph.com/issues/16490

Signed-off-by: Sage Weil <sage@redhat.com>
(cherry picked from commit 07dbd9326a7b76f7ab41c397ecedbaf4d477d95e)

### CODE REVIEW

**Comment by smithfarm** [comment]
Changelog:
* added backport tracker URL to PR description

**Comment by smithfarm** [comment]
@liewegas This PR is in the latest round of hammer-backports integration tests, which passed a rados run (the only failures are a valgrind false positive that has since been fixed by https://github.com/ceph/teuthology/pull/915 and http://tracker.ceph.com/issues/15139 which is an infrastructure issue with two of the tests) - for details, see: http://tracker.ceph.com/issues/15895#note-18

OK to merge?

**Comment by athanatos** [comment]
@liewegas Do we actually want to change this so late in the hammer life cycle?

**Comment by ktdreyer** [comment]
@liewegas , @athanatos , should we take this change or not?

**Comment by athanatos** [comment]
@ktdreyer @liewegas will be back next week.  I don't want to merge it until we hear from him.

**Comment by ktdreyer** [comment]
Discussed with Sam and Sage today in Core standup. Sam and Sage agreed we won't be pulling this into Hammer, closing.

**Pull request closed without merging**
