### PR TITLE
*: s/virtualenv/python -m venv/

### PR DESCRIPTION
**Pull request by tchaikov**
for less build deps and for preparing for the el9 build. as el8 does not package `python3-virtualenv`.

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by tchaikov** [comment]
jenkins test docs

**Comment by tchaikov** [comment]
this change depends on 

- [ ] https://github.com/ceph/ceph-cm-ansible/pull/643
- [ ] https://github.com/ceph/ceph-build/pull/1888

**Comment by tchaikov** [comment]
jenkins test docs

**Comment by tchaikov** [comment]
jenkins test docs

**Comment by tchaikov** [comment]
jenkins test docs

**Comment by tchaikov** [comment]
jenkins test dashboard

**Comment by tchaikov** [comment]
jenkins test make check arm64

**Review by sebastian-philipp — APPROVED** [review]

**Comment by tchaikov** [comment]
- https://pulpito.ceph.com/kchai-2021-08-04_05:19:17-rados-wip-kefu-testing-2021-08-04-1022-distro-basic-smithi/
- https://pulpito.ceph.com/kchai-2021-08-04_10:33:19-rados-wip-kefu-testing-2021-08-04-1022-distro-basic-smithi/

**Comment by ktdreyer** [comment]
Tracking Pacific backport in https://tracker.ceph.com/issues/52472

**Pull request merged**
