### PR TITLE
squid: mgr/cephadm:  update default NVMEoF container image version

### PR DESCRIPTION
**Pull request by adk3798**
backport tracker: https://tracker.ceph.com/issues/65958

---

backport of https://github.com/ceph/ceph/pull/57182
parent tracker: https://tracker.ceph.com/issues/65718

this backport was staged using ceph-backport.sh version 16.0.0.6848
find the latest version at https://github.com/ceph/ceph/blob/main/src/script/ceph-backport.sh

### CODE REVIEW

**Review by idryomov — APPROVED** [review]
Note: `rbd:nvmeof` suite would still fail, but with a different error (further into the test):
> 2024-05-16T09:15:10.367 INFO:tasks.workunit.client.2.smithi100.stdout:Failure creating subsystem nqn.2016-06.io.spdk:cnode1: HA must be enabled for subsystems

(This is from today's run on main: https://pulpito.ceph.com/dis-2024-05-16_08:07:49-rbd-wip-dis-testing-distro-default-smithi/7708811)

**Comment by adk3798** [comment]
> Note: `rbd:nvmeof` suite would still fail, but with a different error (further into the test):
> 
> > 2024-05-16T09:15:10.367 INFO:tasks.workunit.client.2.smithi100.stdout:Failure creating subsystem nqn.2016-06.io.spdk:cnode1: HA must be enabled for subsystems
> 
> (This is from today's run on main: https://pulpito.ceph.com/dis-2024-05-16_08:07:49-rbd-wip-dis-testing-distro-default-smithi/7708811)

Alright, would you like me to ping you to review the results of that run when it happens before we merge this?

**Comment by adk3798** [comment]
@idryomov this patch worked for the nvmeof test in the orch suite, but the test in the rbd suite is doing a `ceph config set mgr mgr/cephadm/container_image_nvmeof quay.io/ceph/nvmeof:latest` which nullifies the effect of this change https://pulpito.ceph.com/adking-2024-05-21_13:52:35-rbd-wip-adk4-testing-2024-05-17-0821-squid-distro-default-smithi/7718636/. Do we want to adjust the test, or should we request an update of the `latest` tag for the nvmeof image from the nvmeof team?

**Comment by idryomov** [comment]
> Do we want to adjust the test, or should we request an update of the `latest` tag for the nvmeof image from the nvmeof team?

The latter, but this is pending discussion with Aviv's team.  @barakda indicated in https://github.com/ceph/ceph/pull/57522#issuecomment-2122147481 that `latest` not getting updated automatically is intended.  I think that needs to change -- we shouldn't be requesting anything and it should be done automatically.  Having latest point at 1.0.0 when e.g. 1.2.5 is available and used is not only weird, but also breaks the idea of CI.

**Comment by adk3798** [comment]
https://pulpito.ceph.com/adking-2024-06-18_03:54:30-orch:cephadm-wip-adk4-testing-2024-06-17-1401-squid-distro-default-smithi/

failures were

- 18 `in cluster log` type failures, known issue, still being cleaned up
- 7 failures in mds_upgrade_sequence, known issue
- 1 staggered upgrade with agent on failure, known issue
- 1 random failure installing a kernel
```
2024-06-18T09:28:10.210 INFO:teuthology.orchestra.run.smithi172.stdout:Transaction check succeeded.
2024-06-18T09:28:10.210 INFO:teuthology.orchestra.run.smithi172.stdout:Running transaction test
2024-06-18T09:28:10.733 INFO:teuthology.orchestra.run.smithi172.stderr:Error: Cannot open file /var/cache/dnf/baseos-044cae74d71fe9ea/packages/kernel-modules-5.14.0-460.el9.x86_64.rpm: [Errno 2] No such file or directory: '/var/cache/dnf/baseos-044cae74d71fe9ea/packages/kernel-modules-5.14.0-460.el9.x86_64.rpm'
2024-06-18T09:28:10.733 INFO:teuthology.orchestra.run.smithi172.stderr:TypeError: an integer is required (got type NoneType)
2024-06-18T09:28:10.733 INFO:teuthology.orchestra.run.smithi172.stderr:FATAL ERROR: python callback ??? failed, aborting!
2024-06-18T09:28:10.827 DEBUG:teuthology.orchestra.run:got remote process result: 1
```
unrelated to anything we're testing in the run.

Overall, nothing to block merging PRs in the run

**Comment by adk3798** [comment]
jenkins test make check

**Comment by adk3798** [comment]
jenkins test api

**Pull request merged**
