### PR TITLE
doc: fix broken link in erasure-code.rst

### PR DESCRIPTION
**Pull request by minshenglin**
Fixes: http://tracker.ceph.com/issues/19972
Signed-off-by: MinSheng Lin <minsheng.l@inwinstack.com>

### CODE REVIEW

**Comment by Liuchang0812** [comment]
maybe we should create a test case since we support sphinx link-check already.

**Comment by tchaikov** [comment]
@Liuchang0812  that would need network access. i am not 100% sure it's always available in the test environment. is it possible to disable it by default assuming we have that test?

**Comment by Liuchang0812** [comment]
@tchaikov dirty but works solution: we create a test script that it check the network at first, then execute `link-check` if network is ok, else skip this test.

**Comment by tchaikov** [comment]
i'd prefer adding an option which is `OFF` by default in CMake script, and enable it in our jenkins "make check" make run, and add the "link-check" test only if it's `ON`.

**Comment by Liuchang0812** [comment]
it's a better solution. i create a issue to track this problem http://tracker.ceph.com/issues/19973

**Pull request merged**
