### PR TITLE
quincy: rgw/sts: modify max_session_duration using update role REST API/ radosgw-admin command.

### PR DESCRIPTION
**Pull request by pritha-srivastava**
backport tracker: https://tracker.ceph.com/issues/57509

---

backport of https://github.com/ceph/ceph/pull/46378
parent tracker: https://tracker.ceph.com/issues/55751

this backport was staged using ceph-backport.sh version 16.0.0.6848
find the latest version at https://github.com/ceph/ceph/blob/master/src/script/ceph-backport.sh

### CODE REVIEW

**Review by mattbenjamin — APPROVED** [review]
lgtm!

**Review by anthonyeleven — APPROVED** [review]
docs lgtm, not that this is very docky

**Comment by yuriw** [comment]
note for self: this PR could not be merged with others cleanly

**Comment by yuriw** [comment]
@pritha-srivastava pls rebase

**Pull request merged**
