### PR TITLE
jewel: cephfs: osdc/Filer: truncate large file party by party

### PR DESCRIPTION
**Pull request by Vicente-Cheng**
http://tracker.ceph.com/issues/20025

### CODE REVIEW

**Comment by smithfarm** [comment]
Jenkins re-test this please

**Comment by smithfarm** [comment]
@Vicente-Cheng Hi, could you please compare your version of this backport with @ukernel 's version at https://github.com/ukernel/ceph/tree/wip-20026-jewel (they should be exactly the same)

**Comment by ukernel** [comment]
@Vicente-Cheng, the onack handling in your code does not seem correct. no one uses the onack callback, please just remove it.

**Comment by Vicente-Cheng** [comment]
@ukernel, OK, I will remove it and check `onack` callback again (I though it still use, so I remain it...)

@smithfarm, Sure, I will check it with https://github.com/ukernel/ceph/tree/wip-20026-jewel this branch again and update this pr

thanks for your reminder

**Comment by Vicente-Cheng** [comment]
@smithfarm, 
Hi Nathan, I rebase and update this pr.
Compare with the https://github.com/ukernel/ceph/tree/wip-20026-jewel, I change something that @ukernel suggest remove unuse onack, I think that looks like the same with his branch...

maybe you could review it again : )
thanks!!

**Comment by smithfarm** [comment]
@Vicente-Cheng Thanks. I will include this in the next jewel integration branch.

**Comment by smithfarm** [comment]
@ukernel This passed an fs suite at http://tracker.ceph.com/issues/20613#note-7 with two occurrences of the following transient failure: http://tracker.ceph.com/issues/16881

Please review.

**Comment by batrick** [comment]
That failure is known to be racy/transient. I'm okay with merging this after @ukernel approves.

**Pull request merged**
