### PR TITLE
pacific: qa: run e2e test on centos only

### PR DESCRIPTION
**Pull request by ljflores**
Backport of https://github.com/ceph/ceph/pull/42158

Fixes: https://tracker.ceph.com/issues/54992

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [x] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by ljflores** [comment]
@tchaikov pacific dashboard tests have been failing when run on ubuntu, and I noticed that we removed support for ubuntu in releases >= quincy.

This is the commit that seems to take care of it, but do you know if this is sufficient, or if something more/different needs to be backported?

**Comment by ljflores** [comment]
I scheduled some tests here:
http://pulpito.front.sepia.ceph.com/lflores-2022-12-08_21:33:17-rados:dashboard-pacific-distro-default-smithi/

**Comment by tchaikov** [comment]
> @tchaikov pacific dashboard tests have been failing when run on ubuntu, and I noticed that we removed support for ubuntu in releases >= quincy.
> 
> This is the commit that seems to take care of it, but do you know if this is sufficient, or if something more/different needs to be backported?

@ljflores hi Laura, sorry i don't have enough bandwidth looking into this issue so i cannot provide an answer to your inquiries.

**Comment by ljflores** [comment]
@tchaikov no worries!

@ceph/dashboard can you please take a look?

**Comment by nizamial09** [comment]
> pacific dashboard tests have been failing when run on ubuntu, and I noticed that we removed support for ubuntu in releases >= quincy.

@ljflores do you mean to say releases <=quincy? if that's the case i am okay with it..

**Review by nizamial09 — APPROVED** [review]

**Comment by ljflores** [comment]
As this has already been tested on teuthology (http://pulpito.front.sepia.ceph.com/lflores-2022-12-08_21:33:17-rados:dashboard-pacific-distro-default-smithi/) I will merge this.

**Pull request merged**
