### PR TITLE
doc/cephfs/mds-config-ref: render options using confval directive 

### PR DESCRIPTION
**Pull request by tchaikov**
## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by tchaikov** [comment]
it will be a time-consuming endeavor to migrate all mds options to `.. confval::` directive, so i will do this piecemeal.

**Comment by tchaikov** [comment]
jenkins test make check

**Comment by tchaikov** [comment]
jenkins test make check

**Review by sseshasa — APPROVED** [review]
For document doc/dev/osd_internals/mclock_wpq_cmp_study.rst, the note under 
section "Establish Baseline Client Throughput (IOPS)" talks about overriding the bluestore
throttle options. Reference may be added to these as well.

The changes look good for the mclock related documentation. Thanks!

**Review by sseshasa — COMMENTED** [review]
s/opeations/operations on line 435 in doc/dev/osd_internals/mclock_wpq_cmp_study.rst.

**Comment by tchaikov** [comment]
@sseshasa updated and repushed.

**Comment by tchaikov** [comment]
jenkins test make check

**Review by batrick — APPROVED** [review]
\o/

**Pull request merged**
