### PR TITLE
os/DBObjectMap:move iterator to first record of object

### PR DESCRIPTION
**Pull request by xinxinsh**
iter->valid is always false if we do not initialize the iterator with init(), seek_to_first will initialize this iterator

Signed-off-by: xinxin shu <xinxin.shu@intel.com>

### CODE REVIEW

**Comment by tchaikov** [comment]
@xinxinsh could you prefix your the title of your commit message with something like "os/DBObjectMap: "?

also would be great if you can also elaborate the intention of this change in addition to what you changed in this pull request? for example, if it's a bug fix, what the problem is, and how it addresses the problem? if it's performance enhancement, what is the impact of this change?

thanks. =)

**Comment by xinxinsh** [comment]
@tchaikov , updated

**Comment by varadakari** [comment]
Looks good to me

**Comment by tchaikov** [comment]
thanks @xinxinsh, could you also add a simple test in `test/objectstore/store_test.cc` to cover this fix? it's a good chance to improve the `StoreTest.OMapTest`, i guess.

**Comment by xinxinsh** [comment]
@tchaikov , updated

**Comment by tchaikov** [comment]
tested at http://pulpito.ceph.com/ubuntu-2015-06-12_21:23:04-rados-wip-kefu-testing---basic-multi/, the failed one is not relevant, and it passed in a second run at http://pulpito.ceph.com/ubuntu-2015-06-14_06:07:33-rados-wip-kefu-testing---basic-multi/933027/. the failed test was tracked at http://tracker.ceph.com/issues/12013 .

**Comment by tchaikov** [comment]
good to merge, but @xinxinsh , could you prefix your the title of your commit messages with the area you touched, e.g. "os/DBObjectMap: "? i see you've updated the issue title in the github, thanks =)

**Comment by xinxinsh** [comment]
@tchaikov , updated

**Comment by tchaikov** [comment]
@xinxinsh just a side note, you might want to name your branch with a better name next time, wip-fix is way too general =)

**Pull request merged**
