### PR TITLE
crimson/seastore: add ObjectDataHandler readv

### PR DESCRIPTION
**Pull request by liu-chunmei**
move do_for_each interval_set<uint64_t>& m from seastore::readv
to ObjectDataHandler::readv.
otherwise seastar has Exceptioanl future for std::bad_alloc

Signed-off-by: chunmei-liu <chunmei.liu@intel.com>

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by athanatos** [comment]
This seems like it duplicates fiemap and read.  What specifically was causing the bad_alloc?

**Comment by liu-chunmei** [comment]
@athanatos with the original seastore::readv, I got 2022-02-23T18:41:02.840 INFO:tasks.ceph.osd.1.real301.stderr:WARN  2022-02-23 18:47:28,151 [shard 0] seastar - Exceptional future ignored: std::bad_alloc (std::bad_alloc), backtrace: 0x60b2521 0x60b0d35 0x60b18c2 0x60b2139 0x5db42c7 0x5db43a7 0x3c29388 0x3c24ed5 0x3de118a 0x3e0bda8 0x5e254aa 0x5e2617d 0x5e272c3 0x5e26540 0x5d8816f 0x5d877e8 0x3ca8717 /lib/x86_64-linux-gnu/libc.so.6+0x270b2 0x3c1be6d
2022-02-23T18:41:02.841 INFO:tasks.ceph.osd.1.real301.stderr:   seastar::continuation<seastar::internal::promise_base_with_type<void>, crimson::osd::ShardServices::start_operation<crimson::osd::ClientRequest, crimson::osd::OSD&, seastar::shared_ptr<crimson::net::Connection>&, boost::intrusive_ptr<_mosdop::MOSDOp<std::vector<OSDOp, std::allocator<OSDOp> > > > >(crimson::osd::OSD&, seastar::shared_ptr<crimson::net::Connection>&, boost::intrusive_ptr<_mosdop::MOSDOp<std::vector<OSDOp, std::allocator<OSDOp> > > >&&)::{lambda()#1}, seastar::future<void>::then_impl_nrvo<{lambda()#1}, seastar::future>({lambda()#1}&&)::{lambda(seastar::internal::promise_base_with_type<void>&&, {lambda()#1}&, seastar::future_state<seastar::internal::monostate>&&)#1}, void>

with the back trace, I got: 
backtrace:[Backtrace #0]
void seastar::backtrace<seastar::current_backtrace_tasklocal()::{lambda(seastar::frame)#1}>(seastar::current_backtrace_tasklocal()::{lambda(seastar::frame)#1}&&) at ./obj-x86_64-linux-gnu/src/seastar/./src/seastar/include/seastar/util/backtrace.hh:59
seastar::current_backtrace_tasklocal() at ./obj-x86_64-linux-gnu/src/seastar/./src/seastar/src/util/backtrace.cc:86
seastar::current_tasktrace() at ./obj-x86_64-linux-gnu/src/seastar/./src/seastar/src/util/backtrace.cc:137
seastar::current_backtrace() at ./obj-x86_64-linux-gnu/src/seastar/./src/seastar/src/util/backtrace.cc:170
seastar::report_failed_future(std::__exception_ptr::exception_ptr const&) at ./obj-x86_64-linux-gnu/src/seastar/./src/seastar/src/core/future.cc:210
seastar::report_failed_future(seastar::future_state_base const&) at ./obj-x86_64-linux-gnu/src/seastar/./src/seastar/src/core/future.cc:214
void seastar::internal::promise_base::set_exception_impl<seastar::future_state_base>(seastar::future_state_base&&) at ./obj-x86_64-linux-gnu/src/crimson/osd/./src/seastar/include/seastar/core/future.hh:851
seastar::internal::promise_base::set_exception(seastar::future_state_base&&) at ./obj-x86_64-linux-gnu/src/crimson/osd/./src/seastar/include/seastar/core/future.hh:856
seastar::future<void>::then_impl_nrvo<crimson::osd::ShardServices::start_operation<crimson::osd::ClientRequest, crimson::osd::OSD&, seastar::shared_ptr<crimson::net::Connection>&, boost::intrusive_ptr<_mosdop::MOSDOp<std::vector<OSDOp, std::allocator<OSDOp> > > > >(crimson::osd::OSD&, seastar::shared_ptr<crimson::net::Connection>&, boost::intrusive_ptr<_mosdop::MOSDOp<std::vector<OSDOp, std::allocator<OSDOp> > > >&&)::{lambda()#1}, seastar::future<void> >(crimson::osd::ShardServices::start_operation<crimson::osd::ClientRequest, crimson::osd::OSD&, seastar::shared_ptr<crimson::net::Connection>&, boost::intrusive_ptr<_mosdop::MOSDOp<std::vector<OSDOp, std::allocator<OSDOp> > > > >(crimson::osd::OSD&, seastar::shared_ptr<crimson::net::Connection>&, boost::intrusive_ptr<_mosdop::MOSDOp<std::vector<OSDOp, std::allocator<OSDOp> > > >&&)::{lambda()#1}&&)::{lambda(seastar::internal::promise_base_with_type<void>&&, {lambda()#1}&, seastar::future_state<auto:1&&::monostate>&&)#1}::operator()(seastar::internal::promise_base_with_type<void>, seastar::internal::promise_base_with_type<void>&&, seastar::future_state<crimson::osd::ShardServices::start_operation<crimson::osd::ClientRequest, crimson::osd::OSD&, seastar::shared_ptr<crimson::net::Connection>&, boost::intrusive_ptr<_mosdop::MOSDOp<std::vector<OSDOp, std::allocator<OSDOp> > > > >(crimson::osd::OSD&, seastar::shared_ptr<crimson::net::Connection>&, boost::intrusive_ptr<_mosdop::MOSDOp<std::vector<OSDOp, std::allocator<OSDOp> > > >&&)::{lambda()#1}&&::monostate>) const at ./obj-x86_64-linux-gnu/src/crimson/osd/./src/seastar/include/seastar/core/future.hh:1573
seastar::continuation<seastar::internal::promise_base_with_type<void>, crimson::osd::ShardServices::start_operation<crimson::osd::ClientRequest, crimson::osd::OSD&, seastar::shared_ptr<crimson::net::Connection>&, boost::intrusive_ptr<_mosdop::MOSDOp<std::vector<OSDOp, std::allocator<OSDOp> > > > >(crimson::osd::OSD&, seastar::shared_ptr<crimson::net::Connection>&, boost::intrusive_ptr<_mosdop::MOSDOp<std::vector<OSDOp, std::allocator<OSDOp> > > >&&)::{lambda()#1}, seastar::future<void>::then_impl_nrvo<{lambda()#1}, seastar::future>({lambda()#1}&&)::{lambda(seastar::internal::promise_base_with_type<void>&&, {lambda()#1}&, seastar::future_state<seastar::internal::monostate>&&)#1}, void>::run_and_dispose() at ./obj-x86_64-linux-gnu/src/crimson/osd/./src/seastar/include/seastar/core/future.hh:767
seastar::reactor::run_tasks(seastar::reactor::task_queue&) at ./obj-x86_64-linux-gnu/src/seastar/./src/seastar/src/core/reactor.cc:2354
seastar::reactor::run_some_tasks() at ./obj-x86_64-linux-gnu/src/seastar/./src/seastar/src/core/reactor.cc:2763
seastar::reactor::do_run() at ./obj-x86_64-linux-gnu/src/seastar/./src/seastar/src/core/reactor.cc:2932
seastar::reactor::run() at ./obj-x86_64-linux-gnu/src/seastar/./src/seastar/src/core/reactor.cc:2815
seastar::app_template::run_deprecated(int, char**, std::function<void ()>&&) at ./obj-x86_64-linux-gnu/src/seastar/./src/seastar/src/core/app-template.cc:265
seastar::app_template::run(int, char**, std::function<seastar::future<int> ()>&&) at ./obj-x86_64-linux-gnu/src/seastar/./src/seastar/src/core/app-template.cc:156
main at ./obj-x86_64-linux-gnu/src/crimson/osd/./src/crimson/osd/main.cc:237
__libc_start_main at /build/glibc-eX1tMB/glibc-2.31/csu/../csu/libc-start.c:308
_start at ??:?

**Comment by athanatos** [comment]
What workload/sequence of commands triggers that crash?

**Comment by liu-chunmei** [comment]
> What workload/sequence of commands triggers that crash?

teuthology test: qa/suite/crimson-rados/basic/tasks/readwrite.yaml.  any fixed-1.yaml or fixed-2.yaml cluster.

**Comment by athanatos** [comment]
I think the invalid memory access is due to the oid param being passed to SeaStore::readv.  PGBackend::sparse_read passes ghobject_t{os.oi.soid}, which means that the lifetime of oid in SeaStore::readv won't necessarily last until the future finally resolves.  You can fix that by adding the oid param to the first seastar::do_with call:

```
 SeaStore::read_errorator::future<ceph::bufferlist> SeaStore::readv(
   CollectionRef ch,
-  const ghobject_t& oid,
+  const ghobject_t& _oid,
   interval_set<uint64_t>& m,
   uint32_t op_flags)
 {
   return seastar::do_with(
+    _oid,
     ceph::bufferlist{},
-    [=, &oid, &m](auto &ret) {
+    [=, &m](auto &oid, auto &ret) {
     return crimson::do_for_each(
       m,
       [=, &oid, &ret](auto &p) {
```

**Comment by athanatos** [comment]
I think readwrite.yaml runs ceph_test_rados.  Running the same command against a vstart cluster with seastore would probably reproduce the crash.  Do you have a link to a run with the crash?

**Comment by liu-chunmei** [comment]
> I think readwrite.yaml runs ceph_test_rados. Running the same command against a vstart cluster with seastore would probably reproduce the crash. Do you have a link to a run with the crash?

no, I will run your recommended modification to verify by teuthology environment.

**Comment by liu-chunmei** [comment]
@athanatos  with the modification, I got: 
2022-03-01T11:56:58.683 INFO:tasks.ceph.osd.2.real300.stderr:WARN  2022-03-01 12:03:30,767 [shard 0] seastar - Exceptional future ignored: std::runtime_error (op 'undirty' not supported), backtrace: 0x60250ef 0x6023903 0x6024490 0x6024d07 0x5d26f67 0x5d27047 0x3bb5388 0x3bb0ed5 0x3d6d2e6 0x3d97f04 0x5d9814a 0x5d98e1d 0x5d99f63 0x5d991e0 0x5cfae0f 0x5cfa488 0x3c34871 /lib/x86_64-linux-gnu/libc.so.6+0x270b2 0x3ba7e6d
2022-03-01T11:56:58.684 INFO:tasks.ceph.osd.2.real300.stderr:   --------
2022-03-01T11:56:58.684 INFO:tasks.ceph.osd.2.real300.stderr:   seastar::continuation<seastar::internal::promise_base_with_type<void>, crimson::osd::ShardServices::start_operation<crimson::osd::ClientRequest, crimson::osd::OSD&, seastar::shared_ptr<crimson::net::Connection>&, boost::intrusive_ptr<_mosdop::MOSDOp<std::vector<OSDOp, std::allocator<OSDOp> > > > >(crimson::osd::OSD&, seastar::shared_ptr<crimson::net::Connection>&, boost::intrusive_ptr<_mosdop::MOSDOp<std::vector<OSDOp, std::allocator<OSDOp> > > >&&)::{lambda()#1}, seastar::future<void>::then_impl_nrvo<{lambda()#1}, seastar::future>({lambda()#1}&&)::{lambda(seastar::internal::promise_base_with_type<void>&&, {lambda()#1}&, seastar::future_state<seastar::internal::monostate>&&)#1}, void>
2022-03-01T11:56:58.684 INFO:tasks.ceph.osd.2.real300.stderr:DEBUG 2022-03-01 12:03:30,767 [shard 0] osd - client_request(id=8, detail=m=[osd_op(client.4218.0:2 13.8 13:13abc3e7:test-rados-api-teuth-41-9011-2::foo:head {undirty} snapc 0={} ondisk+write+known_if_redirected+supports_pool_eio e15) v8]): destroying
2022-03-01T11:56:58.684 INFO:tasks.ceph.osd.2.real300.stderr:WARN  2022-03-01 12:03:30,767 [shard 0] seastar - Exceptional future ignored: std::runtime_error (op 'undirty' not supported), backtrace: 0x60250ef 0x6023903 0x6024490 0x6024d07 0x5d26f67 0x5d27093 0x3bb0e49 0x3c0250d 0x3c2a457 0x3c2bc45 0x3d97eab 0x3d97f17 0x5d9814a 0x5d98e1d 0x5d99f63 0x5d991e0 0x5cfae0f 0x5cfa488 0x3c34871 /lib/x86_64-linux-gnu/libc.so.6+0x270b2 0x3ba7e6d
2022-03-01T11:56:58.684 INFO:tasks.ceph.osd.2.real300.stderr:   --------
2022-03-01T11:56:58.684 INFO:tasks.ceph.osd.2.real300.stderr:   seastar::continuation_base<void>

**Comment by athanatos** [comment]
@liu-chunmei undirty is related to tiering, you'll probably need to modify that yaml to remove tiering operations since they aren't supported in crimson yet (and should probably be a very low priority).

**Comment by liu-chunmei** [comment]
> @liu-chunmei undirty is related to tiering, you'll probably need to modify that yaml to remove tiering operations since they aren't supported in crimson yet (and should probably be a very low priority).

Sam, sorry I made a mistake, that is rados_api_test, I forgot to modify it.  I am retesting readwrite now.

**Comment by liu-chunmei** [comment]
@athanatos  passed the test,  a new PR at: #45204

**Pull request closed without merging**
