### PR TITLE
ceph upstart script rbdmap.conf incorrectly processes parameters

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/13342

### CODE REVIEW

**Comment by Abhishekvrshny** [comment]
@smithfarm @dachary This does not apply cleanly on infernalis due to the changes that have gone into src/init-rbdmap through https://github.com/ceph/ceph/pull/6363 . Marking it DNM as of now.

**Comment by smithfarm** [comment]
@Abhishekvrshny Rebased and repushed. Thanks!

**Comment by Abhishekvrshny** [comment]
@liewegas this backport passed the rbd suite (http://tracker.ceph.com/issues/13750#note-10), do you think it can be merged ?

**Comment by liewegas** [comment]
:+1:

**Pull request merged**
