### PR TITLE
quincy: cephadm: use importlib.metadata for querying ceph_iscsi's version

### PR DESCRIPTION
**Pull request by zdover23**
to prepare for a change to use importlib, then fallback to pkg_resources. as the former is only available in Python 3.8, while the latter is deprecated.

NOTE: This is a backport to the Quincy branch of the commits in https://github.com/ceph/ceph/pull/57685/commits. Those commits are:
   1. be1a8c2c43e97f91bd26554ba9dadc71c499865d
   2. cbd4bede7f258823462f27cb15d86e13eb52c359 The alteration to the "def get_version(ctx, container_id):" function introduced by be1a8c is not in the same file in the main branch as in the Quincy branch, which makes a backport using cherry-picks impossible.

Refs https://tracker.ceph.com/issues/66201

(cherry picked from commit be1a8c2c43e97f91bd26554ba9dadc71c499865d)

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [x] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [x] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Comment by idryomov** [comment]
Pushed a mechanical backport (no testing!) to Zac's branch at his request.

**Comment by idryomov** [comment]
> which makes a backport using cherry-picks impossible.

It's always possible if you are willing to resolve conflicts after each cherry pick ;)  For larger series it can get burdensome, but in general it's preferred -- that way commits in the backport PR correspond 1:1 to commits in the original PR and conflict resolution can be retraced easily.

**Comment by idryomov** [comment]
jenkins test make check

**Comment by idryomov** [comment]
jenkins test make check

**Review by adk3798 — APPROVED** [review]

**Pull request merged**
