### PR TITLE
osd: remove Message::trace empty check.

### PR DESCRIPTION
**Pull request by majianpeng**
Message::trace never empty. So no need check empty check.

Signed-off-by: Jianpeng Ma <jianpeng.ma@intel.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by majianpeng** [comment]
@cbodley . This introduced by your commit :a39b8c466e8fe22936b7195ab88b45da274f2a1. So please review.

**Comment by cbodley** [comment]
> Message::trace never empty. So no need check empty check.

are you sure? the initialization of `m->trace` is conditional in `Message::decode_trace()`:
```c++
  if (info.trace_id) {
    trace.init(get_type_name().data(), endpoint, &info, true);
    trace.event("decoded trace");
  } else if (create || (msgr->get_myname().is_osd() &&
                        msgr->cct->_conf->osd_blkin_trace_all)) {
    // create a trace even if we didn't get one on the wire
    trace.init(get_type_name().data(), endpoint);
    trace.event("created trace");
  }
```
the idea is that we should only initialize the trace (and spend cpu cycles to trace events) if the remote messenger associated a trace with its message. we really shouldn't be enabling this tracing anywhere by default because there's a performance cost

**Comment by majianpeng** [comment]
@cbodley .  trace.init() and m->trace is equal? I don't think so.

**Comment by cbodley** [comment]
looking at class Trace in src/blkin/blkin-lib/ztracer.hpp:
```c++
  // return true if the Trace has been initialized
  bool valid() const { return info.trace_id != 0; }
  operator bool() const { return valid(); }
```
and the default constructor:
```c++
  // default constructor zero-initializes blkin_trace valid()
  // will return false on a default-constructed Trace until
  // init()
  Trace()
  {
    // zero-initialize so valid() returns false
    name = NULL;
    info.trace_id = 0;
```
are you seeing different behavior in testing?

**Comment by majianpeng** [comment]
@cbodley . Thanks for your explanation.  In fact  i omit the operator bool(). You are right.

**Comment by cbodley** [comment]
@majianpeng gotcha, no problem

**Pull request closed without merging**
