### PR TITLE
jewel: rgw: leak from RGWMetaSyncShardCR::incremental_sync

### PR DESCRIPTION
**Pull request by asheplyakov**
http://tracker.ceph.com/issues/18563

### CODE REVIEW

**Comment by cbodley** [comment]
oops. the build failure is due to jewel using the system boost, while master/kraken are bundling a more recent version:
```
rgw/rgw_sync.cc:2064:16: error: no matching function for call to 'boost::intrusive_ptr<RGWMetadataLogInfoCompletion>::reset(RGWMetadataLogInfoCompletion*, const bool&)'
```
I've pushed a copy of this branch to https://github.com/cbodley/ceph/commits/wip-18563, and added the commit https://github.com/cbodley/ceph/commit/e1a183a68a6f12775af748c9079ff82a7fbc1279 to fix it. Can you please cherry-pick that into this pr?

**Comment by asheplyakov** [comment]
@cbodley: I've folded e1a183a into the last commit in this PR (6634da4726dbff996ca8e510a66c6eed6ab4ee02). cherry-picking would leave a broken commit which is not nice for bisection, etc

**Comment by cbodley** [comment]
thanks!

**Comment by asheplyakov** [comment]
The PRs necessary for this one (and conflicting with it) have been merged. I've dropped a copy of #10661, and rebased on latest jewel.

**Comment by asheplyakov** [comment]
jenkins retest this please

**Comment by dachary** [comment]
@yehudasa does this backport look good to merge ? It passed the rgw suite at http://tracker.ceph.com/issues/17851#note-66.

**Comment by dachary** [comment]
@yehudasa does this backport look good to merge ? It passed the rgw suite at http://tracker.ceph.com/issues/17851#note-75.

**Comment by yehudasa** [comment]
@cbodley do you think this one is ready?

**Comment by cbodley** [comment]
@dachary @yehudasa yes

**Pull request merged**
