### PR TITLE
rgw: fix user.rgw.user-policy attr remove by assume_role or modify user info

### PR DESCRIPTION
**Pull request by joke-lee**
fix https://tracker.ceph.com/issues/48761

Signed-off-by: yuliyang_yewu <yuliyang_yewu@cmss.chinamobile.com>

```
when put user policy on user yly by the follow boto3 script

import boto3
import botocore
botocore.session.Session().set_debug_logger()
access_key = 'admin'
secret_key = 'admin'
config_dict = { 'signature_version' : 's3', 'connect_timeout': 30000, 'read_timeout': 30000}
configuration = boto3.session.Config(**config_dict)

client = boto3.client('iam',
aws_access_key_id=access_key,
aws_secret_access_key=secret_key,
endpoint_url='http://127.0.0.1:8000',
region_name='',
use_ssl = False,
config = configuration,
)

policy = '''{
  "Version": "2012-10-17",
  "Statement": [{
    "Effect": "Allow",
    "Action": "sts:GetSessionToken",
    "Resource": "*"
  }]
}'''

response = client.put_user_policy(
    UserName='yly',
    PolicyName='yly-sts',
    PolicyDocument= policy
)


./bin/rados -p default.rgw.meta listxattr yly --namespace users.uid -c ceph.conf
ceph.objclass.version
user.rgw.user-policy <= we have new attr here

but when we modify user info by

./bin/radosgw-admin user modify --uid=yly --max-buckets=200 -c ceph.conf

the user.rgw.user-policy attr will be removed

and if we assume_role, the user.rgw.user-policy attr will be remove too

./bin/radosgw-admin role create --role-name role1 --path / --assume-role-policy-doc \{\"Version\":\"2012-10-17\",\"Statement\":\[\{\"Effect\":\"Allow\",\"Principal\":\{\"AWS\":\[\"arn:aws:iam:::user/yly\"\]\},\"Action\":\[\"sts:AssumeRole\"\]\}\]\}

./bin/radosgw-admin role-policy put --role-name=role1 --policy-name=Policy1 --policy-doc=\{\"Version\":\"2012-10-17\",\"Statement\":\[\{\"Effect\":\"Allow\",\"Action\":\[\"s3:*\"\],\"Resource\":\"arn:aws:s3:::test1\"\}\]\}


import boto3
import botocore
botocore.session.Session().set_debug_logger()
access_key = 'yly'
secret_key = 'yly'
config_dict = { 'signature_version' : 's3', 'connect_timeout': 30000, 'read_timeout': 30000}
configuration = boto3.session.Config(**config_dict)

client = boto3.client('sts',
aws_access_key_id=access_key,
aws_secret_access_key=secret_key,
endpoint_url='http://127.0.0.1',
region_name='',
use_ssl = False,
config = configuration,
)

response = client.assume_role(
RoleArn='arn:aws:iam:::role/role1',
RoleSessionName='my-session-1',
DurationSeconds=3600,
)

after call assume_role, the user.rgw.user-policy will be remove and user can not call get_session_token which we defined in put_user_policy

```

### CODE REVIEW

**Comment by joke-lee** [comment]
hi @pritha-srivastava , would you mind help to review this pr :)

**Comment by joke-lee** [comment]
hi @cbodley do you mind help review this?

**Comment by pritha-srivastava** [comment]
looks good to me - can use newer std::optional for pattrs

**Review by cbodley — APPROVED** [review]
looks good, lets confirm with testing

**Comment by cbodley** [comment]
we still want this fix, but it will need a rebase

**Comment by joke-lee** [comment]
@cbodley rebase done

**Comment by ivancich** [comment]
This appears to be failing QA:

2023-03-21T17:46:31.129 INFO:teuthology.orchestra.run.smithi120.stdout:FAILED s3tests_boto3/functional/test_iam.py::test_get_user_policy_from_multiple_policies
2023-03-21T17:46:31.129 INFO:teuthology.orchestra.run.smithi120.stdout:FAILED s3tests_boto3/functional/test_iam.py::test_delete_user_policy_from_multiple_policies
2023-03-21T17:46:31.129 INFO:teuthology.orchestra.run.smithi120.stdout:FAILED s3tests_boto3/functional/test_iam.py::test_verify_conflicting_user_policies
2023-03-21T17:46:31.129 INFO:teuthology.orchestra.run.smithi120.stdout:FAILED s3tests_boto3/functional/test_s3.py::test_bucket_acl_grant_userid_read
2023-03-21T17:46:31.129 INFO:teuthology.orchestra.run.smithi120.stdout:FAILED s3tests_boto3/functional/test_s3.py::test_bucket_acl_grant_userid_readacp
2023-03-21T17:46:31.129 INFO:teuthology.orchestra.run.smithi120.stdout:FAILED s3tests_boto3/functional/test_s3.py::test_bucket_acl_grant_userid_write
2023-03-21T17:46:31.130 INFO:teuthology.orchestra.run.smithi120.stdout:FAILED s3tests_boto3/functional/test_s3.py::test_bucket_acl_grant_userid_writeacp
2023-03-21T17:46:31.130 INFO:teuthology.orchestra.run.smithi120.stdout:FAILED s3tests_boto3/functional/test_s3.py::test_access_bucket_private_object_private
2023-03-21T17:46:31.130 INFO:teuthology.orchestra.run.smithi120.stdout:FAILED s3tests_boto3/functional/test_s3.py::test_access_bucket_private_objectv2_private
2023-03-21T17:46:31.130 INFO:teuthology.orchestra.run.smithi120.stdout:FAILED s3tests_boto3/functional/test_s3.py::test_access_bucket_private_object_publicread
2023-03-21T17:46:31.130 INFO:teuthology.orchestra.run.smithi120.stdout:FAILED s3tests_boto3/functional/test_s3.py::test_access_bucket_private_objectv2_publicread
2023-03-21T17:46:31.130 INFO:teuthology.orchestra.run.smithi120.stdout:FAILED s3tests_boto3/functional/test_s3.py::test_access_bucket_private_object_publicreadwrite
2023-03-21T17:46:31.130 INFO:teuthology.orchestra.run.smithi120.stdout:FAILED s3tests_boto3/functional/test_s3.py::test_access_bucket_private_objectv2_publicreadwrite
2023-03-21T17:46:31.131 INFO:teuthology.orchestra.run.smithi120.stdout:FAILED s3tests_boto3/functional/test_s3.py::test_access_bucket_publicread_object_private
2023-03-21T17:46:31.131 INFO:teuthology.orchestra.run.smithi120.stdout:FAILED s3tests_boto3/functional/test_s3.py::test_access_bucket_publicread_object_publicread
2023-03-21T17:46:31.131 INFO:teuthology.orchestra.run.smithi120.stdout:FAILED s3tests_boto3/functional/test_s3.py::test_access_bucket_publicread_object_publicreadwrite
2023-03-21T17:46:31.131 INFO:teuthology.orchestra.run.smithi120.stdout:FAILED s3tests_boto3/functional/test_s3.py::test_access_bucket_publicreadwrite_object_private
2023-03-21T17:46:31.131 INFO:teuthology.orchestra.run.smithi120.stdout:FAILED s3tests_boto3/functional/test_s3.py::test_access_bucket_publicreadwrite_object_publicread
2023-03-21T17:46:31.131 INFO:teuthology.orchestra.run.smithi120.stdout:FAILED s3tests_boto3/functional/test_s3.py::test_access_bucket_publicreadwrite_object_publicreadwrite
2023-03-21T17:46:31.131 INFO:teuthology.orchestra.run.smithi120.stdout:FAILED s3tests_boto3/functional/test_s3.py::test_object_copy_not_owned_bucket
2023-03-21T17:46:31.132 INFO:teuthology.orchestra.run.smithi120.stdout:FAILED s3tests_boto3/functional/test_s3.py::test_bucket_policy_get_obj_existing_tag
2023-03-21T17:46:31.132 INFO:teuthology.orchestra.run.smithi120.stdout:FAILED s3tests_boto3/functional/test_s3.py::test_bucket_policy_get_obj_tagging_existing_tag
2023-03-21T17:46:31.132 INFO:teuthology.orchestra.run.smithi120.stdout:FAILED s3tests_boto3/functional/test_s3.py::test_bucket_policy_put_obj_tagging_existing_tag
2023-03-21T17:46:31.132 INFO:teuthology.orchestra.run.smithi120.stdout:FAILED s3tests_boto3/functional/test_s3.py::test_bucket_policy_put_obj_copy_source
2023-03-21T17:46:31.132 INFO:teuthology.orchestra.run.smithi120.stdout:FAILED s3tests_boto3/functional/test_s3.py::test_bucket_policy_put_obj_copy_source_meta
2023-03-21T17:46:31.132 INFO:teuthology.orchestra.run.smithi120.stdout:FAILED s3tests_boto3/functional/test_s3.py::test_bucket_policy_get_obj_acl_existing_tag
2023-03-21T17:46:31.132 INFO:teuthology.orchestra.run.smithi120.stdout:FAILED s3tests_boto3/functional/test_s3.py::test_ignore_public_acls - Asserti...

**Pull request closed without merging**
