### PR TITLE
octopus: revert of #46253, add tools: ceph-objectstore-tool is able to trim solely pg log dups' entries

### PR DESCRIPTION
**Pull request by rzarzynski**
Revert of https://github.com/ceph/ceph/pull/46253 and includes https://github.com/ceph/ceph/pull/46630/commits/a2190f901abf2fed20c65e59f53b38c10545cb5a

Technically this isn't a backport but a full revert of an already merged backport.

"Backport" ticket for the sake of tracking: https://tracker.ceph.com/issues/55990

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/master/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by rzarzynski** [comment]
There is a FTBFS due an undetected merge conflict in the COT commit. Replacing with the pacific's version.

**Comment by yuriw** [comment]
@rzarzynski This PR seems like breaking the build:

https://jenkins.ceph.com/job/ceph-dev-new-build/ARCH=x86_64,AVAILABLE_ARCH=x86_64,AVAILABLE_DIST=centos7,DIST=centos7,MACHINE_SIZE=gigantic/63787//consoleFull

`/home/jenkins-build/build/workspace/ceph-dev-new-build/ARCH/x86_64/AVAILABLE_ARCH/x86_64/AVAILABLE_DIST/centos7/DIST/centos7/MACHINE_SIZE/gigantic/release/15.2.16-324-g22f047e9/rpm/el7/BUILD/ceph-15.2.16-324-g22f047e9/src/tools/ceph_objectstore_tool.cc: In function ‘int main(int, char**)’:
/home/jenkins-build/build/workspace/ceph-dev-new-build/ARCH/x86_64/AVAILABLE_ARCH/x86_64/AVAILABLE_DIST/centos7/DIST/centos7/MACHINE_SIZE/gigantic/release/15.2.16-324-g22f047e9/rpm/el7/BUILD/ceph-15.2.16-324-g22f047e9/src/tools/ceph_objectstore_tool.cc:4445:36: error: request for member ‘get’ in ‘fs’, which is of pointer type ‘ObjectStore*’ (maybe you meant to use ‘->’ ?)
       ret = do_trim_pg_log_dups(fs.get(), coll, info, pgid,`

**Comment by rzarzynski** [comment]
@yuriw:

```
/home/jenkins-build/build/workspace/ceph-dev-new-build/ARCH/x86_64/AVAILABLE_ARCH/x86_64/AVAILABLE_DIST/centos7/DIST/centos7/MACHINE_SIZE/gigantic/release/15.2.16-324-g22f047e9/rpm/el7/BUILD/ceph-15.2.16-324-g22f047e9/src/tools/ceph_objectstore_tool.cc:4445:36: error: request for member ‘get’ in ‘fs’, which is of pointer type ‘ObjectStore*’ (maybe you meant to use ‘->’ ?)
       ret = do_trim_pg_log_dups(fs.get(), coll, info, pgid,
```

Please use the updated version pushed this morning (commit ID https://github.com/ceph/ceph/pull/46611/commits/263e0fa6b3e6e1d6e7b382923a1d586d9d1ffa1b).

**Comment by rzarzynski** [comment]
jenkins test api

**Pull request merged**
