### PR TITLE
luminous: Deleting a pool with active notify linger ops can result in seg fault

### PR DESCRIPTION
**Pull request by pdvian**
http://tracker.ceph.com/issues/24059

### CODE REVIEW

**Comment by pdvian** [comment]
@dillaman @tchaikov Need review. I have cherry-picked PR #21831 for this backport, do I suppose to cherry-pick commit-id 0b8bd36b3d3bbf1e1a2c849adf0be3c6d19174ce only here ?

**Comment by tchaikov** [comment]
@pdvian thanks for backporting this fix! i think 0b8bd36b3d3bbf1e1a2c849adf0be3c6d19174ce is important in this fix, so we do need to have it here also.

**Comment by yuriw** [comment]
[wip-yuri-testing-2018-06-08-1529-luminous](https://trello.com/c/XYvW5z42/324-wip-yuri-testing-2018-06-08-1529-luminous)

**Comment by yuriw** [comment]
[wip-yuri-testing-2018-06-08-1529-luminous](https://trello.com/c/XYvW5z42/324-wip-yuri-testing-2018-06-08-1529-luminous)

**Comment by yuriw** [comment]
[wip-yuri2-testing-2018-06-08-1529-luminous](https://trello.com/c/n2OD92F0/325-wip-yuri2-testing-2018-06-08-1529-luminous)

**Pull request merged**
