### PR TITLE
os/KeyValueDB: reduce malloc/free/string copy count

### PR DESCRIPTION
**Pull request by branch-predictor**
In RocksDB, LevelDB and Kinetic wrapper code, there is unnecessary
string copying. In particular, split_key makes an extra copy of string
(as a basis for extracted key and/or value), which can be easily omitted.
Also, checking for iterator validity generates std::pair with prefix
and key and checks prefix with the one from pair, wasting memory for
key.

Signed-off-by: Piotr Dałek <piotr.dalek@ts.fujitsu.com>

### CODE REVIEW

**Comment by liewegas** [comment]
The first two patches look good.  I think we need to audit all of the api users to make sure dropping valid from next is possible, though...

**Comment by branch-predictor** [comment]
True. I'll make separate PR for this. First two patches make the most of the performance gain anyway.

**Comment by branch-predictor** [comment]
Last patch is moved to https://github.com/ceph/ceph/pull/6304

**Comment by liewegas** [comment]
see wip-kv branch.. we'll integrate test and merge from there

**Pull request closed without merging**
