### PR TITLE
ceph-volume: don't use MultiLogger in find_executable_on_host()

### PR DESCRIPTION
**Pull request by guits**
This generates a lot of unnecessary messages on the terminal.

Fixes: https://tracker.ceph.com/issues/53934

Signed-off-by: Guillaume Abrioux <gabrioux@redhat.com>

### CODE REVIEW

**Comment by guits** [comment]
jenkins test ceph-volume all

**Comment by guits** [comment]
jenkins test ceph-volume all

**Comment by guits** [comment]
jenkins test ceph-volume tox

**Comment by guits** [comment]
jenkins test ceph-volume batch centos8-filestore-single_type

**Review by yuriw — APPROVED** [review]

**Comment by guits** [comment]
jenkins test make check

**Comment by guits** [comment]
jenkins test doc

**Comment by guits** [comment]
jenkins test ceph-volume all

**Comment by guits** [comment]
jenkins test ceph-volume batch centos8-bluestore-single_type

**Comment by guits** [comment]
jenkins test ceph make check

**Comment by guits** [comment]
jenkins test make check

**Comment by guits** [comment]
jenkins test make check

**Comment by guits** [comment]
jenkins test ceph-volume tox

**Comment by guits** [comment]
jenkins test make check

**Comment by guits** [comment]
jenkins test ceph-volume tox

**Comment by guits** [comment]
jenkins test ceph-volume all

**Comment by guits** [comment]
jenkins test ceph-volume lvm centos8-bluestore-dmcrypt

**Comment by guits** [comment]
jenkins test ceph-volume batch centos8-bluestore-single_type_dmcrypt

**Pull request merged**
