### PR TITLE
nautilus:  mds: change how mds revoke stale caps

### PR DESCRIPTION
**Pull request by ukernel**
https://tracker.ceph.com/issues/40326

- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by yuriw** [comment]
@ukernel seems conflicting :

--- pr 28583 --- pulling https://github.com/ukernel/ceph.git branch nautilus-40326
remote: Enumerating objects: 31, done.
remote: Counting objects: 100% (31/31), done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 31 (delta 28), reused 28 (delta 28), pack-reused 0
Unpacking objects: 100% (31/31), done.
From https://github.com/ukernel/ceph
 * branch            nautilus-40326 -> FETCH_HEAD
Auto-merging src/mds/Server.cc
Auto-merging src/mds/Locker.h
Auto-merging src/mds/Locker.cc
CONFLICT (content): Merge conflict in src/mds/Locker.cc
Auto-merging src/common/options.cc
Automatic merge failed; fix conflicts and then commit the result.
Traceback (most recent call last):
  File "/home/yuriw/wip_master/src/script/build-integration-branch", line 62, in <module>
    assert not r
AssertionError

**Comment by yuriw** [comment]
[wip-yuri-testing-2019-06-17-2042-nautilus](https://trello.com/c/4seSG4a2/646-wip-yuri-testing-2019-06-17-2042-nautilus)

**Comment by batrick** [comment]
marking DNM until Zheng verifies a test failure is unrelated

**Comment by batrick** [comment]
Zheng verified this PR causes /ceph/teuthology-archive/yuriw-2019-06-18_03:14:43-fs-wip-yuri-testing-2019-06-18-0112-nautilus-distro-basic-smithi/4044919/teuthology.log

Delay merging this until a fix is ready.

**Comment by batrick** [comment]
needs rebased too

**Comment by smithfarm** [comment]
Re-queuing for integration testing on the assumption this is fixed. Correct, @ukernel?

**Comment by ukernel** [comment]
yes, it's fixed

**Comment by yuriw** [comment]
[wip-yuri-testing-2019-07-30-1543-nautilus](https://trello.com/c/bRHqvLN7/678-wip-yuri-testing-2019-07-30-1543-nautilus)

**Pull request merged**
