### PR TITLE
mgr/dashboard: Fix env vars of `run-tox.sh`

### PR DESCRIPTION
**Pull request by p-na**
Fixes: http://tracker.ceph.com/issues/38798

Signed-off-by: Patrick Nawracay <pnawracay@suse.com>

- [x] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by sebastian-philipp** [comment]
what does this fix? Does it make sense to have this in nautilus?

**Comment by p-na** [comment]
`$CEPH_BUILD_DIR` is used for `$MGR_DASHBOARD_VIRTUALENV` before it's ensured that `$CEPH_BUILD_DIR` is defined. There's no known problem yet.

**Comment by tchaikov** [comment]
retest this please.

**Comment by sebastian-philipp** [comment]
then I'd lean towards merging this into `nautilus` branch.

**Pull request merged**
