### PR TITLE
jewel: filestore: can get stuck in an unbounded loop during scrub

### PR DESCRIPTION
**Pull request by dachary**
http://tracker.ceph.com/issues/17915

### CODE REVIEW

**Comment by dachary** [comment]
jenkins test this please (jenkins was stuck)

**Comment by theanalyst** [comment]
@dachary can you retarget this  to jewel, as we need this also for 10.2.4

**Comment by theanalyst** [comment]
@liewegas ok to merge?

**Comment by liewegas** [comment]
yep!

**Comment by athanatos** [comment]
retest this

**Comment by athanatos** [comment]
jenkins retest this

**Comment by athanatos** [comment]
retest this please

**Comment by dachary** [comment]
@athanatos the error is expected and is fixed in jewel-next. It is environmental.
<pre>
# TOTAL: 141
# PASS:  140
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: ceph-disk/run-tox.sh
==========================
...
ERROR:   flake8: commands failed
  py27: commands succeeded
</pre>

**Pull request merged**
