### PR TITLE
mgr/dashboard: Add 'Dirs' and 'Caps' for filesystems details

### PR DESCRIPTION
**Pull request by ghyer**
## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by votdev** [comment]
Could you please describe your PR in the upper description box? Does your PR reference a tracker issue?

**Comment by ghyer** [comment]
@votdev 
2020-08-03 13-12-50 的屏幕截图
'Dirs' and 'Caps' column were added.

**Comment by s0nea** [comment]
jenkins test make check

**Comment by s0nea** [comment]
I created an issue to reflect the PR in the tracker: https://tracker.ceph.com/issues/47728 . Feel free to change/enhance it.

@ghyer could you please add the tracker URL to your commit message (`Fixes: https://tracker.ceph.com/issues/47728`) like it's done e.g. here: https://github.com/ceph/ceph/commit/c427901252cdf27c89a076de75011b0d25f35799 ?

**Review by s0nea — APPROVED** [review]
LGTM

**Comment by s0nea** [comment]
`make check` is failing because there is an issue with the linting of `src/app/ceph/cephfs/cephfs-detail/cephfs-detail.component.ts`:

```
[lint:html    ] 
[lint:html    ] [htmllint] found 0 errors out of 156 files
[lint:html    ] All files pass linting
[lint:prettier] src/app/ceph/cephfs/cephfs-detail/cephfs-detail.component.ts
[lint:tslint  ] Linting "ceph-dashboard"...
[lint:tslint  ] All files pass linting.

Try running 'npm run fix' to fix some linting errors. Some errors might need a manual fix.
```

Could you please run `npm run fix` to fix it and commit the changes?

**Comment by s0nea** [comment]
jenkins test dashboard

**Review by bk201 — APPROVED** [review]

**Comment by callithea** [comment]
- [pkg build](https://shaman.ceph.com/builds/ceph/wip-laura-testing-36385/) [WIP]
- QA run [PENDING]

**Review by callithea — APPROVED** [review]
lgtm

**Comment by epuertat** [comment]
Thank you very much @ghyer for your contribution here! Please let us know if you want to take an active part on Ceph Dashboard development!

**Pull request merged**
