### PR TITLE
os/bluestore: Make Onode::put/get resiliant to split_cache

### PR DESCRIPTION
**Pull request by aclamk**
In
  OnodeCacheShard* ocs = c->get_onode_cache();
  std::lock_guard l(ocs->lock);
while waiting for lock, split_cache might have changed OnodeCacheShard.
This will result in adding Onode to improper OnodeCacheShard.

This might fix: https://tracker.ceph.com/issues/49818.

Signed-off-by: Adam Kupczyk <akupczyk@redhat.com>

## Checklist
- [x] References tracker ticket
- [x] Updates documentation if necessary

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Review by jdurgin — APPROVED** [review]
good catch!

**Review by ifed01 — COMMENTED** [review]
This looks good to me but it makes a little sense without proper locking in split_cache. @aclamk - could you please cherry-pick that stuff from https://github.com/ceph/ceph/pull/40237/commits/98894fae75949968fc37847f76457230461838cb
After additional investigation it looks to me that the whole https://github.com/ceph/ceph/pull/40237 hardly fits your fix (as the  intention in my PR is to avoid the dependency from CacheShard::lock). Hence I suggest to make a minimal meaningful PR from both your patch and the first commit of my fix and proceed with testing and using in Pacific, Hopefully this would at least make the probability of the bug popup much less.
Meanwhile I'm going to extend my patch and go ahead with cleaning up lock usage around caches but I doubt it makes sense to have as an urgent fix for Pacific - it's going to be rather heavy.

**Review by ifed01 — APPROVED** [review]

**Comment by aclamk** [comment]
@ifed01 Wow, that was quick.

**Comment by neha-ojha** [comment]
Full rados run queued - https://pulpito.ceph.com/nojha-2021-03-23_23:04:33-rados-wip-40323-2-distro-basic-gibba/
@aclamk this is where I am running your reproducer https://pulpito.ceph.com/nojha-2021-03-24_14:14:01-rados-wip-40323-2-distro-basic-gibba/

**Comment by neha-ojha** [comment]
> Full rados run queued - https://pulpito.ceph.com/nojha-2021-03-23_23:04:33-rados-wip-40323-2-distro-basic-gibba/

Did another run https://pulpito.ceph.com/nojha-2021-03-25_17:31:39-rados-wip-40323-2-distro-basic-smithi/ - no related failures.

> @aclamk this is where I am running your reproducer https://pulpito.ceph.com/nojha-2021-03-24_14:14:01-rados-wip-40323-2-distro-basic-gibba/ 

no related failures

**Pull request merged**
