### PR TITLE
docs: correct add system user to the master zone command

### PR DESCRIPTION
**Pull request by snosratiershad**
Signed-off-by: Salar Nosrati-Ershad <snosratiershad@gmail.com>

In progress of following the documentation to implement ceph multisite, I' tried the suggested command: `radosgw-admin zone modify --rgw-zone=us-east --access-key={access-key} --secret={secret}` and got following error:
```
failed to init zone: (2) No such file or directory
```
after a double check I realized that the `us-east` value should be defined as a zone in RGW. so think it's better to replace the command with something like that:
`radosgw-admin zone modify --rgw-zone={zone-name} --access-key={access-key} --secret={secret}`

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [x] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by snosratiershad** [comment]
please don't merge it, seems like I broked it, I'm going to remake changes.

**Comment by snosratiershad** [comment]
I've fixed it, so sorry for requested reviews. it's because my mistake in rebasing it first.

**Review by zdover23 — APPROVED** [review]
This is a sensible change, and I approve it.

Note to future me: The prompts in this file (doc/radosgw/multisite.rst) are selectable and the commands of which they are a part are improperly marked up.

**Comment by zdover23** [comment]
https://github.com/ceph/ceph/pull/48655 - Quincy backport
https://github.com/ceph/ceph/pull/48656 - Pacific backport

**Pull request merged**
