### PR TITLE
osd/PG: use emplace() to construct new element in-place

### PR DESCRIPTION
**Pull request by Aran85**
Signed-off-by: Zengran Zhang <zhangzengran@sangfor.com.cn>

- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by Aran85** [comment]
test this please

**Comment by Aran85** [comment]
retest this please

**Comment by tchaikov** [comment]
@Aran85 could you elaborate a little bit why we need to replace `push_back()` and `insert()` calls with `emplace()` and `emplace_back()` in the commit message? and probably you could revise the title of the commit message so it is more specific, something like

> osd/pg: use emplace() to construct new element in-place
>
> replace emplace() and emplace_back() with insert() and push_back() calls to construct the new element in-place and avoid the overhead of move constructor calls

**Comment by Aran85** [comment]
amend the commit message only.

**Pull request merged**
