### PR TITLE
ceph-volume: allow ceph-volume use for 'vstart'-ed cluster

### PR DESCRIPTION
**Pull request by ifed01**
--osd-root and --bstrap-keyring command options have been added for that.

Signed-off-by: Igor Fedotov <ifedotov@suse.com>

- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by alfredodeza** [comment]
One of the design decisions made for ceph-volume was to not implement "drop an OSD anywhere" like ceph-disk did in directories. This caused tremendous pain when users started consuming this as a standard feature and was not working correctly in the larger scope of a cluster that expects files and directories in well-known paths.

I think that the idea of consuming ceph-volume in vstart is a good one, but I wouldn't try to bend ceph-volume to accommodate for this type of deployment.

I am -1 on this PR

As a side note, when I initially investigated why vstart couldn't use ceph-volume, it was brought up that requiring sudo was a no-go. Super user permissions are a must for ceph-volume since LVM requires it.

**Comment by ifed01** [comment]
@alfredodeza - thank you for the comments. Not sure I got the last note though, could you elaborate, please.
Additionally - do you think if it makes sense to enable production deployment scheme for vstart? Certainly as an option.

**Comment by alfredodeza** [comment]
@ifed01 I think it would be *great* to have vstart.sh use standard paths (if that is what you mean by production deployment scheme).  The super user comment came up in a discussion about ceph-volume in vstart.sh, and it was mentioned that developers dislike using super user permissions because nothing else required that in vstart.sh

Again, I am 100% behind the idea of consuming ceph-volume everwhere, the more usage the better!

**Comment by ifed01** [comment]
@alfredodeza - yeah, that's what I mean indeed. 
Got your point about superuser usage.
Thanks again!

**Comment by liewegas** [comment]
My $0.02: maybe instead of trying to kludge ceph-volume to use vstart's wonky paths, we should instead build a post-vstart tool that builds a minimal container image from the local build artifacts and lets you run your dev cluster in a container.

**Pull request closed without merging**
