### PR TITLE
radosgw-admin zone deletion uses zone delete

### PR DESCRIPTION
**Pull request by Ejdesgaard**
doc/radosgw/multisite.rst: zone rm does not work on pacific, zone delete works

### CODE REVIEW

**Review by cbodley — APPROVED** [review]

**Comment by ljflores** [comment]
Hey @Ejdesgaard, looks like your commits need a "Signed-off-by" signature: https://github.com/ceph/ceph/blob/master/SubmittingPatches.rst#developer-s-certificate-of-origin-1-1

**Comment by Ejdesgaard** [comment]
> Hey @Ejdesgaard, looks like your commits need a "Signed-off-by" signature: https://github.com/ceph/ceph/blob/master/SubmittingPatches.rst#developer-s-certificate-of-origin-1-1

I have setup git on my computer to sign-off all commits, moving forward, but I can't figure out how I can amend the 2 commits such that they get signed.
Do I need to drop the commits and make the changes again and commit them signed, or is there a way for me to sign the existing commits ?

**Comment by anthonyeleven** [comment]
I am far from a git expert, but what I’ve done in the past to resolve this :guilty: has been `git commit -amend` followed by a force push.

**Comment by Ejdesgaard** [comment]
> I am far from a git expert, but what I’ve done in the past to resolve this :guilty: has been `git commit -amend` followed by a force push.

I can only get `git commit --amend` to work on HEAD and I need to do it on 2 commits that are far from the current HEAD
Is there a way to specify a commit id to --amend ?

**Comment by anthonyeleven** [comment]
Maybe squash them and edit the commit message as part of the process? It’s common for git projects to prefer PRs to have a single commit anyway.

**Comment by ljflores** [comment]
@Ejdesgaard try this set of commands:

- `git log`
- `git rebase -i <SHA of the commit right before your two commits>`
- Change `pick` to `edit` in front of the two commits
- `git commit --amend` (this edits the first commit)
- Make your edits and save the commit
- `git rebase --continue` (this moves to the second commit)
- `git commit --amend` (edits the second commit)
- Make your edits and save the commit
- `git rebase --continue` (completes the rebase of both commits)

If done successfully, you should see a message something like `Successfully rebased and updated refs/heads/master.`.

- Run `git log` and make sure that the commits are how you want them.
- `git push -f <ceph repository> <branch name>` (you have to force-push the branch now since you changed the log history)

As you are making your edits, I noticed that in addition to adding a "Signed-off-by" line, you also should prefix your commits with the directory the changes belong to, in your case `doc/radosgw`. See this document for more details: https://github.com/ceph/ceph/blob/master/SubmittingPatches.rst (it explains how you should sign off your commits and title them).

**Comment by Ejdesgaard** [comment]
@ljflores 
That solved it :D
I also merged the commits into 1 commit and found another instance of zone rm that had to be amended.

I have also tried to find out when it was changed and with `git checkout [v16.2.7|v15.2.7|v14.2.7] it seems rm was replaced with delete between v14 and v15.

**Comment by Ejdesgaard** [comment]
Do I need to do any modifications in order to get this merged and back-ported ?

**Comment by ljflores** [comment]
> @ljflores That solved it :D I also merged the commits into 1 commit and found another instance of zone rm that had to be amended.
> 
> I have also tried to find out when it was changed and with `git checkout [v16.2.7|v15.2.7|v14.2.7]` and for each of them `git blame src/rgw/rgw_admin.cc |grep OPT::ZONE_DELETE` it seems rm was replaced with delete between v14 and v15.

@Ejdesgaard just need re-approval from @cbodley or another RGW person based on your new changes. Once there's a final approval, it will be okay to merge.

**Review by cbodley — APPROVED** [review]

**Comment by cbodley** [comment]
if this needs backporting, is there a corresponding tracker issue for this?

**Comment by Ejdesgaard** [comment]
> if this needs backporting, is there a corresponding tracker issue for this?

I'm afraid not...
I'm not sure what the workflow for this is.

I would be happy to give it a go if you can point me at some documentation on how to do it :)

**Comment by cbodley** [comment]
> I would be happy to give it a go if you can point me at some documentation on how to do it :)

@Ejdesgaard no worries, i opened https://tracker.ceph.com/issues/55434 against pacific/quincy. thanks!

@ljflores thanks for the review

**Pull request merged**
