### PR TITLE
quincy: pybind/rbd: expose CLONE_FORMAT and FLATTEN image options

### PR DESCRIPTION
**Pull request by idryomov**
backport tracker: https://tracker.ceph.com/issues/65815

---

backport of https://github.com/ceph/ceph/pull/57212
parent tracker: https://tracker.ceph.com/issues/65624

### CODE REVIEW

**Review by ajarr — APPROVED** [review]

**Comment by idryomov** [comment]
@cbodley It looks like you have changed the milestone on this PR, was that intended?

**Comment by cbodley** [comment]
> @cbodley It looks like you have changed the milestone on this PR, was that intended?

what the heck? i vaguely remember changing the milestone for a rgw pr, but i wouldn't have touched other components

**Comment by idryomov** [comment]
> what the heck? i vaguely remember changing the milestone for a rgw pr, but i wouldn't have touched other components

One possibility is `ceph-backport.sh` script.  If you use it, it has your GitHub token...

**Comment by cbodley** [comment]
> One possibility is `ceph-backport.sh` script. If you use it, it has your GitHub token...

i did prepare https://github.com/ceph/ceph/pull/57899 on jun 5, so that tracks

**Comment by idryomov** [comment]
> @cbodley It looks like you have changed the milestone on this PR, was that intended?

Undone based on https://github.com/ceph/ceph/pull/57764#issuecomment-2214274488

**Pull request merged**
