### PR TITLE
mgr/dashboard: upgrade grafana pie-chart and vonage-status-panel versions

### PR DESCRIPTION
**Pull request by aaSharma14**
upgrade grafana pie-chart and vonage-status-panel versions

Fixes:https://tracker.ceph.com/issues/55195
Signed-off-by: Aashish Sharma <aasharma@redhat.com>

To test the changes I installed the upgraded versions of piechart-panel and vonage status panel manually inside the grafana container using ceph-dev env and it worked
Before:-
Screenshot from 2022-04-06 17-19-18

After:-
Screenshot from 2022-04-06 17-19-36
Screenshot from 2022-04-06 17-26-25

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by epuertat** [comment]
jenkins test api

**Comment by epuertat** [comment]
jenkins test dashboard

**Comment by aaSharma14** [comment]
jenkins test dashboard

**Comment by epuertat** [comment]
@MrFreezeex can you please check this. @aaSharma14 shared these screenshots that show that both plugins work with Grafana 8.3.5. If you're ok with this, can you please review & approve this PR? Thanks!

**Review by epuertat — APPROVED** [review]

**Review by MrFreezeex — APPROVED** [review]
I'm really surprised that some patches created two years ago of the plugins help with the grafana upgrade to a recent version (did those panels ever work at all?).

Anyway something that work is better than nothing!

**Comment by epuertat** [comment]
* Grafana image build launched: https://jenkins.ceph.com/view/all/job/ceph-grafana-trigger/10/
* That should generate a new 8.3.5 image: https://quay.io/repository/ceph/ceph-grafana?tab=tags

**Comment by s0nea** [comment]
> I'm really surprised that some patches created two years ago of the plugins help with the grafana upgrade to a recent version (did those panels ever work at all?).

@MrFreezeex as far as I can tell the issue is cause by the Grafana version upgrade (https://github.com/ceph/ceph/commit/c306778889c1c65fa7a5d8fd525c5cd3da7f2b78): https://github.com/Vonage/Grafana_Status_panel/issues/189

**Pull request merged**
