### PR TITLE
msg/async/AsyncMessenger: make sure all connection cleanup handler finished

### PR DESCRIPTION
**Pull request by yuyuyu101**
Signed-off-by: Haomai Wang <haomai@xsky.com>

### CODE REVIEW

**Comment by tchaikov** [comment]
lgtm.

**Comment by tchaikov** [comment]
could you add a `Fixes:` line in the commit message?

**Comment by yuyuyu101** [comment]
done

**Comment by yuyuyu101** [comment]
replace by #10090

**Pull request closed without merging**
