### PR TITLE
rgw: multipart copy-part remove '/' for s3 java sdk request header.

### PR DESCRIPTION
**Pull request by donglinpeng**
Fixes: http://tracker.ceph.com/issues/20075

Signed-off-by: donglinpeng@cmss.chinamobile.com

### CODE REVIEW

**Comment by smithfarm** [comment]
Is this intended as a fix for http://tracker.ceph.com/issues/20075 ? If so, can you add a line `Fixes: http://tracker.ceph.com/issues/20075` right before the Signed-off-by line. Thanks; that will help with tracking!

**Comment by donglinpeng** [comment]
@smithfarm Done.  Could you help to review ? Thanks a lot.

**Comment by smithfarm** [comment]
@donglinpeng I don't see any change in the commit message. Did you force-push?

**Comment by donglinpeng** [comment]
@smithfarm I resubmit commit message by force-push.  Thanks a lot.

**Comment by donglinpeng** [comment]
@mattbenjamin Hi, this pull request is intended to fix  http://tracker.ceph.com/issues/20075, could you please help to review ,thank u very much.

**Comment by mattbenjamin** [comment]
http://pulpito.ceph.com/mbenjamin-2017-06-06_22:05:23-rgw-wip-donglingpeng-copypart---basic-smithi/

**Comment by mattbenjamin** [comment]
retest this please

**Comment by mdw-at-linuxbox** [comment]
I had a brief look at this.  It's in fact correct for x-amz-copy-source to start with a leading '/'.  The aws documentation shows this exact syntax in several examples (in my copy pg.385, s3-api.pdf).  Since copy_source is a C string, the commit is doing a fine job of skipping the leading '/'.

**Comment by mmgaggle** [comment]
This fix works in my environment.

**Pull request merged**
