### PR TITLE
osd/PG.cc: 3837: FAILED assert(0 == "Running incompatible OSD")

### PR DESCRIPTION
**Pull request by dzafman**
http://tracker.ceph.com/issues/14292

### CODE REVIEW

**Comment by yuriw** [comment]
@dzafman You don't want me review this PR, do you?

**Comment by yuriw** [comment]
@dachary FYI

**Comment by dzafman** [comment]
@dachary I wasn't sure if these need to be expedited, so I assigned to Yuri.  It consists of 2 straight cherry-picks.  I didn't backport a bunch of mostly code clean-up that was went in together with these 2 changes, so that is the only risk.

**Comment by dachary** [comment]
@dzafman it will be in the next batch of tests.

**Pull request merged**
