### PR TITLE
octopus: qa: Enable debug_client for mgr tests

### PR DESCRIPTION
**Pull request by badone**
Signed-off-by: Brad Hubbard <bhubbard@redhat.com>
(cherry picked from commit 926e06caf5c1262ab1268126d1d775897ff87471)

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by smithfarm** [comment]
jenkins test docs

**Comment by smithfarm** [comment]
The `Docs: build check` is inexplicably failing with:

```
+ sudo apt-get update -o Acquire::Languages=none -o Acquire::Translation=none
Hit:1 http://security.ubuntu.com/ubuntu bionic-security InRelease
Hit:2 http://nova.clouds.archive.ubuntu.com/ubuntu bionic InRelease
Hit:3 http://nova.clouds.archive.ubuntu.com/ubuntu bionic-updates InRelease
Hit:4 http://nova.clouds.archive.ubuntu.com/ubuntu bionic-backports InRelease
Ign:5 https://chacra.ceph.com/r/libboost/master/7aba8a1882670522ee1d1ee1bba0ea170b292dec/ubuntu/bionic/flavors/default bionic InRelease
Hit:6 https://chacra.ceph.com/r/libboost/master/7aba8a1882670522ee1d1ee1bba0ea170b292dec/ubuntu/bionic/flavors/default bionic Release
Ign:7 https://chacra.ceph.com/r/libboost/master/7aba8a1882670522ee1d1ee1bba0ea170b292dec/ubuntu/bionic/flavors/default bionic Release.gpg
Reading package lists...
+ sudo apt-get install -y gcc python3-dev python3-pip python3-virtualenv libxml2-dev libxslt-dev doxygen graphviz ant ditaa cython3
E: dpkg was interrupted, you must manually run 'sudo dpkg --configure -a' to correct the problem. 
```

Maybe it would be fixed by manually doing on the Jenkins machine what the error message says must be done?

**Comment by tchaikov** [comment]
jenkins test docs

**Comment by yuriw** [comment]
[wip-yuri-testing-2020-09-28-1007-octopus](https://trello.com/c/6BigWI59/1024-wip-yuri-testing-2020-09-28-1007-octopus)

**Review by yuriw — APPROVED** [review]

**Pull request merged**
