### PR TITLE
nvmeof: Add mount for log location

### PR DESCRIPTION
**Pull request by roysahar**
## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Comment by phlogistonjohn** [comment]
I'm curious if you considered letting the nvmeof processes log to the journal instead of logging to files - and thus needing log rotation?  I generally consider it better for containerized processes not to log to files but I don't insist on it. :-)

**Comment by roysahar** [comment]
> I'm curious if you considered letting the nvmeof processes log to the journal instead of logging to files - and thus needing log rotation? I generally consider it better for containerized processes not to log to files but I don't insist on it. :-)

Hi, we already logging to journal, the purpose here to keep logs after the daemon exits and also keeping logs over longer period of timeline.

**Comment by caroav** [comment]
@phlogistonjohn @adk3798 I think we need this PR, because currently with the journal way, we don't have any logs remaining after the node reboots for example. The log files are in addition to the journal and not instead of. 
I see that other services (OSD for example) is also logging to file. I know that they're using the "log_to_file" flag, but this is something that we didn't find a way to do in the nvmeof GW which is a python service. 
If there are no major concerns here, and if no once has a better idea, can we get this PR approved? thanks.

**Comment by phlogistonjohn** [comment]
> @phlogistonjohn @adk3798 I think we need this PR, because currently with the journal way, we don't have any logs remaining after the node reboots for example. 

Yikes, that is very concerning to me. Could you share with me the commands you are using and steps to reproduce?

> The log files are in addition to the journal and not instead of. I see that other services (OSD for example) is also logging to file. I know that they're using the "log_to_file" flag, but this is something that we didn't find a way to do in the nvmeof GW which is a python service. If there are no major concerns here, and if no once has a better idea, can we get this PR approved? thanks.

Yeah, we can look into it. One thing to watch out for with  shared log dir is that the service could collide with another if the log file names are "static" and the serivice can be colocated on the same node. I don't know if nvmeof service can be colocated or not though.  Let me know if colocation should not be supported or if you know that the file logging can handle colocation.

**Comment by caroav** [comment]
>  I don't know if nvmeof service can be colocated or not though. Let me know if colocation should not be supported or if you know that the file logging can handle colocation.

@phlogistonjohn the nvmeof GW is indeed collocated on ceph node. The file names that we give the logs are different than the files names of other ceph services, so I don't understand what is the concern. The path to the log file is /var/log/ceph/<fsid>/... 

> Could you share with me the commands you are using and steps to reproduce?
you can simply deploy an nvmeof GW (ceph orch apply) and then while the container is up and running you can use 
`  journalctl -u $(systemctl list-units | grep nvmeof.mypool | awk '{print $1}') ` to see the logs. But when you take the service down, e.g. 
1. ceph orch ps. 
2. ceph orch daemon stop <nvmeof daemon name>

then we don't have the logs in `  journalctl -u $(systemctl list-units | grep nvmeof.mypool | awk '{print $1}') ` 
we can run '`  journalctl -u $(systemctl list-units | grep nvmeof.mypool | awk '{print $**2**}') ` and see the logs, but that is also not available after a while, or after a node reboot.

**Comment by caroav** [comment]
@oritwas @adk3798 @phlogistonjohn - how do you suggest to proceed? IMHO we need to get this merged.

**Comment by adk3798** [comment]
jenkins retest this please

**Review by adk3798 — APPROVED** [review]
at the least, this didn't cause any regressions when I did a test run, and seems to work as intended.

**Comment by phlogistonjohn** [comment]
If @adk3798 wants to merge I won't object. I still prefer to fix this centrally but I don't have the time to dig into it deeply enough to come up with a single solution.  Originally, I had hoped that the `--boot` option to journalctl would solve this but on most of the machines I looked at they only had one boot entry.  I *was* able to find older entries (pre-reboot) in /var/log/messages on centos (9s) but don't know if that configuration will work for all cases/distros.

**Review by caroav — APPROVED** [review]

**Comment by adk3798** [comment]
jenkins test api

**Pull request merged**
