### PR TITLE
mimic: librados application's symbol could conflict with the libceph-common

### PR DESCRIPTION
**Pull request by pdvian**
http://tracker.ceph.com/issues/26839

### CODE REVIEW

**Comment by smithfarm** [comment]
@tchaikov Please review (conflict resolution)

**Comment by yuriw** [comment]
[wip-yuri5-testing-2018-08-20-2118-mimic](https://trello.com/c/19sTEq0s/380-wip-yuri5-testing-2018-08-20-2118-mimic)

**Comment by yuriw** [comment]
@pdvian @smithfarm @tchaikov this broke the build, pls fix and add tags back.

**Comment by smithfarm** [comment]
@pdvian Please rebase

**Comment by smithfarm** [comment]
@pdvian Ping. Please rebase.

**Comment by smithfarm** [comment]
closing in favor of https://github.com/ceph/ceph/pull/24708

**Pull request closed without merging**
