### PR TITLE
kstore: batch small fixes

### PR DESCRIPTION
**Pull request by xiexingguo**

### CODE REVIEW

**Comment by xiexingguo** [comment]
@liewegas Some relevant fixes have been merged by https://github.com/ceph/ceph/pull/7095.
But I found some more here and an escaped one that also exsits in bluestore https://github.com/xiexingguo/ceph/commit/9e77dfd32259cd2577fc358d67d8eb078678034b

**Comment by liewegas** [comment]
thanks!  can you put the new bluestore fix in another PR (or add it to this one)?

**Comment by xiexingguo** [comment]
@liewegas My pleasure and sorry for  the late responding.
I see you have done fetching this pull request for testing. Do I still need to create another PR to get it involved?

**Comment by liewegas** [comment]
you mentioned an additional bluestore bug... if that's not already in the 
other PRs can you open a new one for that?  thanks!

**Comment by xiexingguo** [comment]
LOL :-)  That's not ture. It is the same one (https://github.com/xiexingguo/ceph/commit/9e77dfd32259cd2577fc358d67d8eb078678034b) as I mentioned above and I have already appended it to https://github.com/ceph/ceph/pull/7122. Have a nice day, sir.

**Comment by liewegas** [comment]
hehe, ok, sounds good then--they're both in the current batch for testing  
:)

**Pull request merged**
