### PR TITLE
os/bluestore: perf counters

### PR DESCRIPTION
**Pull request by majianpeng**

### CODE REVIEW

**Comment by liewegas** [comment]
Can we rename the penal writes wal_rmw_op ?

**Comment by majianpeng** [comment]
On write make cause 2 read. So i think wal_rmw_op isn't correctly. At first i named it wal_rmw_read_op. How about this?

**Comment by liewegas** [comment]
perfect, thanks!

**Comment by liewegas** [comment]
rebase please?

**Comment by liewegas** [comment]
@majianpeng can you rebase this on current master?  A bunch of this code has changed.  Thanks!

**Comment by liewegas** [comment]
Can you rebase this on master and drop the other unrelated commits?

**Comment by liewegas** [comment]
The last 4 commits look good, except the last one seems to remove the write_read_penalty lines you just added.

**Comment by majianpeng** [comment]
@liewegas  update.

**Pull request merged**
