### PR TITLE
jewel: rgw: add cors header rule check in cors option request

### PR DESCRIPTION
**Pull request by shinobu-x**
http://tracker.ceph.com/issues/22188

### CODE REVIEW

**Comment by shinobu-x** [comment]
test this please

**Comment by shinobu-x** [comment]
test this please

**Comment by joke-lee** [comment]
test this please

**Comment by smithfarm** [comment]
This passed a rados run at http://tracker.ceph.com/issues/21742#note-15

Still waiting for an rgw run.

**Comment by smithfarm** [comment]
This passed two rgw runs at http://tracker.ceph.com/issues/21742#note-17

**Pull request merged**
