### PR TITLE
Wip osx port

### PR DESCRIPTION
**Pull request by ukernel**

### CODE REVIEW

**Comment by tchaikov** [comment]
@ukernel lgtm 
how did you manage to fix
```
In file included from test/librados/test.cc:19:
In file included from ../src/gmock/gtest/include/gtest/gtest.h:58:
In file included from ../src/gmock/gtest/include/gtest/internal/gtest-internal.h:40:
../src/gmock/gtest/include/gtest/internal/gtest-port.h:594:13: fatal error: 'tr1/tuple' file not found
#   include <tr1/tuple>  // NOLINT
            ^
```
? as clang claims to be gcc 4.*

```
$ clang++ -dM -E -x c /dev/null| grep GNUC
#define __GNUC_MINOR__ 2
#define __GNUC_PATCHLEVEL__ 1
#define __GNUC_STDC_INLINE__ 1
#define __GNUC__ 4
```

and the gtest we are using tests the inclusion of `std::tuple` using
```
# elif defined(__GNUC__) && (GTEST_GCC_VER_ >= 40302)
```
 ?

probably we can sync up the gtest and gmock with the upstream at https://github.com/google/googletest ? seems it is now able check the `std::tuple` in better way, see https://github.com/google/googletest/blob/master/googletest/include/gtest/internal/gtest-port.h#L370 . but i understand it would be a much larger change.

**Comment by tchaikov** [comment]
and needs rebase.

**Comment by wjwithagen** [comment]
On 6-2-2016 18:21, Kefu Chai wrote:
> @ukernel <https://github.com/ukernel> lgtm
> how did you manage to fix
> 
> |In file included from test/librados/test.cc:19: In file included from
> ../src/gmock/gtest/include/gtest/gtest.h:58: In file included from
> ../src/gmock/gtest/include/gtest/internal/gtest-internal.h:40:
> ../src/gmock/gtest/include/gtest/internal/gtest-port.h:594:13: fatal
> error: 'tr1/tuple' file not found # include <tr1/tuple> // NOLINT ^ |
> 
> ? as clang claims to be gcc 4.*
> 
> |$ clang++ -dM -E -x c /dev/null| grep GNUC #define __GNUC_MINOR__ 2
> #define __GNUC_PATCHLEVEL__ 1 #define __GNUC_STDC_INLINE__ 1 #define
> __GNUC__ 4 |
> 
> and the gtest we are using tests the inclusion of |std::tuple| using
> 
> |# elif defined(__GNUC__) && (GTEST_GCC_VER_ >= 40302) |
> 
> ?
> 
> probably we can sync up the gtest and gmock with the upstream at
> https://github.com/google/googletest ? seems it is now able check the
> |std::tuple| in better way, see
> https://github.com/google/googletest/blob/master/googletest/include/gtest/internal/gtest-port.h#L370
> . but i understand it would be a much larger change.

What I actually did for the FreeBSD port is run the patch in the ports
tree over it, after installation. Not the easiest thing to do, but with
the current version in Ceph it just(tm) works.

Since you are talking about OSX, there are also a lot more ifdefs for
DARWIN in there.

As far as I can tell the patch that is in the FreeBSD-ports tree is not
just upstreamed/accepted in the google version.

--WjW


--WjW

**Comment by ukernel** [comment]
Sorry, I don't fix that. This RP only fix build without debug

**Comment by tchaikov** [comment]
@ukernel ping?

**Comment by wjwithagen** [comment]
Not sure that this has anything to do with debug?
If you want to pass all the tests under FreeBSD you need to patch gmock/gtest.
Now it could be that you do not care to run the tests under Darwin...
That is your choice...

**Comment by tchaikov** [comment]
> If you want to pass all the tests under FreeBSD you need to patch gmock/gtest.

yeah. maybe we should leave it as it is at this moment.

**Comment by trociny** [comment]
@ukernel I am recalling you had a patch for FreeBSD error code translation. What is its fate? It would be really nice to have it merged.

**Comment by wjwithagen** [comment]
On 22-3-2016 05:10, Kefu Chai wrote:
>     If you want to pass all the tests under FreeBSD you need to patch
>     gmock/gtest.
> 
> yeah. maybe we should leave it as it is at this moment.

I actually take the "rough" path:

- have autoconfig/autobuild install the git-archive
- path the result with the patchfile in the FreeBSD ports
  Which at the moment runs without any problems.

And once the FreeBSD portmanager get the gtest people to accept his
changes. If ever that happens, I/we will want to remove this part of the
FreeBSD test processing. It is not all that complex atm., just one line
in: do_freebsd.sh:
( cd src/gmock/gtest; patch <
/usr/ports/devel/googletest/files/patch-bsd-defines )

And it does make compilation under FreeBSD/Clang a much happier process.

--WjW

**Comment by athanatos** [comment]
@gregsfortytwo Does this look worthwhile?

**Comment by wjwithagen** [comment]
As far as I can se are quite a few of the fixes already in...
certainly the time stuff, bluestore with aio
So a rebase or cleanup would help

**Comment by gregsfortytwo** [comment]
I'm always a fan of ports and OS X compatibility, but I haven't managed to test this or anything. :(

(On the other hand, I've had it sitting at the bottom of my email inbox list since it was created, too...)

**Pull request closed without merging**
