### PR TITLE
hammer: mon: return size_t from MonitorDBStore::Transaction::size()

### PR DESCRIPTION
**Pull request by tchaikov**
Fixes: http://tracker.ceph.com/issues/14217
Signed-off-by: Kefu Chai kchai@redhat.com
(cherry picked from commit 3971274b342b00d76c2e19211becdc3ee81cf1c1)

### CODE REVIEW

**Comment by tchaikov** [comment]
the ceph-monstore-tool will OOM without this commit when trying to add **lots** of commits.

**Comment by ktdreyer** [comment]
:+1: thanks Kefu

**Comment by tchaikov** [comment]
@dachary can we include this change in hammer?

**Comment by jazeltq** [comment]
@tchaikov hello, could you please explain more about why ceph-monstore-tool will not oom if there return a size_t? Or point out the code of line? Thanks a lot.....

**Comment by dachary** [comment]
@tchaikov I think it's relevant, yes.

**Comment by tchaikov** [comment]
@jazeltq, ceph_monstore_tool.cc:504.

**Comment by jecluis** [comment]
LGTM - regardless of OOM'ing or not, this function should not have been returning a 'bool' anyway ;)

**Comment by smithfarm** [comment]
@tchaikov This backport passed a rados suite at http://tracker.ceph.com/issues/17151#note-7 with failures that I believe have been addressed (except for http://tracker.ceph.com/issues/15139 which is caused by the build system no longer providing dumpling-era packages).

I have rebuilt the integration branch to include the two fixes and scheduled a new run at http://tracker.ceph.com/issues/17151#note-14

Do you think it's OK to merge provided the second run succeeds?

**Comment by smithfarm** [comment]
@tchaikov Also, please rebase.

**Comment by smithfarm** [comment]
Second run succeeded; third run here: http://pulpito.front.sepia.ceph.com/smithfarm-2016-11-21_11:52:41-rados-hammer-backports---basic-smithi/

**Comment by tchaikov** [comment]
@smithfarm lgtm.

**Comment by smithfarm** [comment]
@tchaikov Is this really related to http://tracker.ceph.com/issues/14217 ? It is marked already fixed and backported to hammer long ago.

**Pull request merged**
