### PR TITLE
nautilus: mgr/k8sevents: Initial ceph -> k8s events integration

### PR DESCRIPTION
**Pull request by sebastian-philipp**
Backport tracker:

* https://tracker.ceph.com/issues/41720

Backport of:

* https://github.com/ceph/ceph/pull/29520
* https://github.com/ceph/ceph/pull/28986
* https://github.com/ceph/ceph/pull/30482

### CODE REVIEW

**Comment by sebastian-philipp** [comment]
DNM, because we have a bug in master that should be pulled into this one:

https://tracker.ceph.com/issues/41737

**Comment by b-ranto** [comment]
Any progress, here? The bug was already fixed in master but it is still pending a back-port.

**Comment by sebastian-philipp** [comment]
updated.

**Comment by mykaul** [comment]
@sebastian-philipp - who else should review this?

**Comment by smithfarm** [comment]
Backporting proposal:

Could we keep this feature backport PR open for awhile longer? As various k8s-related PRs get merged into master, they can be cherry-picked into this PR. When the 14.2.5 release starts getting close, we can merge this PR and open another one for 14.2.6. Also, no backport trackers are needed since this is only getting backported to nautilus and no farther.

Does that sound reasonable?

**Comment by tchaikov** [comment]
@smithfarm why did you remove the nautilus-batch-1  label from this PR? does this mean that it failed to squeeze into the last test batch?

**Comment by smithfarm** [comment]
@tchaikov I removed it because

1. we are not testing nautilus PRs at the moment, and
2. I'm waiting for feedback on https://github.com/ceph/ceph/pull/30215#issuecomment-546316131

**Comment by tchaikov** [comment]
probably it's off-topic. just trying to understand how we use this label. because i see there are other nautilus PRs still have "nautilus-batch-1" label. what does that mean?

**Comment by smithfarm** [comment]
It means the PR has passed all the mandatory Jenkins tests and has no open change requests or other questions in need of clarification, and is therefore clear for inclusion in the next regular integration run.

**Comment by tchaikov** [comment]
thanks @smithfarm , i see. so this PR is actually pending on the your question.

**Comment by smithfarm** [comment]
Yes, that is my proposal based on my perception that this feature is still under active development.

**Comment by sebastian-philipp** [comment]
> Backporting proposal:
> 
> Could we keep this feature backport PR open for awhile longer? 

Actually, I'd like to get this merged in soonish. I don't think it will make much sense to wait longer.

**Comment by smithfarm** [comment]
@yuriw Can you include this in an upcoming integration run?

**Comment by yuriw** [comment]
[wip-yuri8-testing-2019-11-13-2038-nautilus](https://trello.com/c/B3GlsAUj/761-wip-yuri8-testing-2019-11-13-2038-nautilus)

**Pull request merged**
