### PR TITLE
pacific: cephadm: November batch 2 

### PR DESCRIPTION
**Pull request by sebastian-philipp**
Backport of #43827, #43894, #42906, #43095, #43929, #43969, #43873, #43888, #44092, #44080, #44075, #44079, #44011, #42378, #44100, #44118, #44140

### CODE REVIEW

**Review by adk3798 — APPROVED** [review]
bits from me look good

**Comment by sebastian-philipp** [comment]
```
2022-01-04T15:06:21.969 INFO:teuthology.orchestra.run.smithi001.stderr:Error EINVAL: Traceback (most recent call last):
2022-01-04T15:06:21.970 INFO:teuthology.orchestra.run.smithi001.stderr:  File "/usr/share/ceph/mgr/mgr_module.py", line 1384, in _handle_command
2022-01-04T15:06:21.970 INFO:teuthology.orchestra.run.smithi001.stderr:    return self.handle_command(inbuf, cmd)
2022-01-04T15:06:21.970 INFO:teuthology.orchestra.run.smithi001.stderr:  File "/usr/share/ceph/mgr/orchestrator/_interface.py", line 168, in handle_command
2022-01-04T15:06:21.970 INFO:teuthology.orchestra.run.smithi001.stderr:    return dispatch[cmd['prefix']].call(self, cmd, inbuf)
2022-01-04T15:06:21.971 INFO:teuthology.orchestra.run.smithi001.stderr:  File "/usr/share/ceph/mgr/mgr_module.py", line 397, in call
2022-01-04T15:06:21.971 INFO:teuthology.orchestra.run.smithi001.stderr:    return self.func(mgr, **kwargs)
2022-01-04T15:06:21.971 INFO:teuthology.orchestra.run.smithi001.stderr:  File "/usr/share/ceph/mgr/orchestrator/_interface.py", line 107, in <lambda>
2022-01-04T15:06:21.971 INFO:teuthology.orchestra.run.smithi001.stderr:    wrapper_copy = lambda *l_args, **l_kwargs: wrapper(*l_args, **l_kwargs)  # noqa: E731
2022-01-04T15:06:21.972 INFO:teuthology.orchestra.run.smithi001.stderr:  File "/usr/share/ceph/mgr/orchestrator/_interface.py", line 96, in wrapper
2022-01-04T15:06:21.972 INFO:teuthology.orchestra.run.smithi001.stderr:    return func(*args, **kwargs)
2022-01-04T15:06:21.972 INFO:teuthology.orchestra.run.smithi001.stderr:  File "/usr/share/ceph/mgr/orchestrator/module.py", line 774, in _daemon_add_osd
2022-01-04T15:06:21.972 INFO:teuthology.orchestra.run.smithi001.stderr:    raise_if_exception(completion)
2022-01-04T15:06:21.972 INFO:teuthology.orchestra.run.smithi001.stderr:  File "/usr/share/ceph/mgr/orchestrator/_interface.py", line 225, in raise_if_exception
2022-01-04T15:06:21.973 INFO:teuthology.orchestra.run.smithi001.stderr:    raise e
2022-01-04T15:06:21.973 INFO:teuthology.orchestra.run.smithi001.stderr:RuntimeError: cephadm exited with an error code: 1, stderr:Inferring config /var/lib/ceph/610b3a2a-6d6f-11ec-8c31-001a4aab830c/mon.a/config
2022-01-04T15:06:21.973 INFO:teuthology.orchestra.run.smithi001.stderr:Non-zero exit code 2 from /usr/bin/docker run --rm --ipc=host --stop-signal=SIGTERM --net=host --entrypoint /usr/sbin/ceph-volume --privile>
2022-01-04T15:06:21.973 INFO:teuthology.orchestra.run.smithi001.stderr:/usr/bin/docker: stderr  stderr: lsblk: vg_nvme/lv_4: not a block device
2022-01-04T15:06:21.974 INFO:teuthology.orchestra.run.smithi001.stderr:/usr/bin/docker: stderr  stderr: blkid: error: vg_nvme/lv_4: No such file or directory
2022-01-04T15:06:21.974 INFO:teuthology.orchestra.run.smithi001.stderr:/usr/bin/docker: stderr  stderr: Unknown device, --name=, --path=, or absolute path in /dev/ or /sys expected.
2022-01-04T15:06:21.974 INFO:teuthology.orchestra.run.smithi001.stderr:/usr/bin/docker: stderr usage: ceph-volume lvm batch [-h] [--db-devices [DB_DEVICES [DB_DEVICES ...]]]
2022-01-04T15:06:21.974 INFO:teuthology.orchestra.run.smithi001.stderr:/usr/bin/docker: stderr                              [--wal-devices [WAL_DEVICES [WAL_DEVICES ...]]]
2022-01-04T15:06:21.974 INFO:teuthology.orchestra.run.smithi001.stderr:/usr/bin/docker: stderr                              [--journal-devices [JOURNAL_DEVICES [JOURNAL_DEVICES ...]]]
2022-01-04T15:06:21.975 INFO:teuthology.orchestra.run.smithi001.stderr:/usr/bin/docker: stderr                              [--auto] [--no-auto] [--bluestore] [--filestore]
2022-01-04T15:06:21.975 INFO:teuthology.orchestra.run.smithi001.stderr:/usr/bin/docker: stderr                              [--report] [--yes]
2022-01-04T15:06:21.975 INFO:teuthology.orchestra.run.smithi001.stderr:/usr/bin/docker: stderr                              [--format {json,json-pretty,pretty}] [--dmcrypt]
2022-01-04T15:06:21.975 INFO:teuthology.orchestra.run.smithi001.stderr:/usr/bin/docker: stderr                              [--crush-device-class CRUSH_DEVICE_CLASS]
2022-01-04T15:06:21.976 INFO:teuthology.orchestra.run.smithi001.stderr:/usr/bin/docker: stderr                              [--no-systemd]
2022-01-04T15:06:21.976 INFO:teuthology.orchestra.run.smithi001.stderr:/usr/bin/docker: stderr                              [--osds-per-device OSDS_PER_DEVICE]
2022-01-04T15:06:21.976 INFO:teuthology.orchestra.run.smithi001.stderr:/usr/bin/docker: stderr                              [--data-slots DATA_SLOTS]
2022-01-04T15:06:21.976 INFO:teuthology.orchestra.run.smithi001.stderr:/usr/bin/docker: stderr                              [--block-db-size BLOCK_DB_SIZE]
2022-01-04T15:06:21.976 INFO:teuthology.orchestra.run.smithi001.stderr:/usr/bin/docker: stderr                              [--block-db-slots BLOCK_DB_SLOTS]
2022-01-04T15:06:21.977 INFO:teuthology.orchestra.run.smithi001.stderr:/usr/bin/docker: stderr                              [--block-wal-size BLOCK_WAL_SIZE]
2022-01-04T15:06:21.977 INFO:teuthology.orchestra.run.smithi001.stderr:/usr/bin/docker: stderr                              [--block-wal-slots BLOCK_WAL_SLOTS]
2022-01-04T15:06:21.977 INFO:teuthology.orchestra.run.smithi001.stderr:/usr/bin/docker: stderr                              [--journal-size JOURNAL_SIZE]
2022-01-04T15:06:21.977 INFO:teuthology.orchestra.run.smithi001.stderr:/usr/bin/docker: stderr                              [--journal-slots JOURNAL_SLOTS] [--prepare]
2022-01-04T15:06:21.978 INFO:teuthology.orchestra.run.smithi001.stderr:/usr/bin/docker: stderr                              [--osd-ids [OSD_IDS [OSD_IDS ...]]]
2022-01-04T15:06:21.978 INFO:teuthology.orchestra.run.smithi001.stderr:/usr/bin/docker: stderr                              [DEVICES [DEVICES ...]]
```
* `rados:cephadm/with-work/{0-distro/ubuntu_18.04 fixed-2 mode/root mon_election/connectivity msgr/async start tasks/rados_python}`
* https://pulpito.ceph.com/swagner-2022-01-04_14:18:33-rados:cephadm-wip-swagner2-testing-2022-01-03-1502-pacific-distro-default-smithi/6594463

**Comment by sebastian-philipp** [comment]
depends on #44505

**Comment by sebastian-philipp** [comment]
test make check

**Comment by sebastian-philipp** [comment]
jenkins test make check

**Comment by sebastian-philipp** [comment]
jenkins test make check

**Comment by sebastian-philipp** [comment]
jenkins test make check

**Comment by sebastian-philipp** [comment]
jenkins test make check

**Pull request merged**
