### PR TITLE
messenger,client,compressor: migrate atomic_t to std::atomic

### PR DESCRIPTION
**Pull request by chardan**
refer-to: https://github.com/ceph/ceph/pull/14655

### CODE REVIEW

**Comment by chardan** [comment]
@ceph-jenkins retest

**Comment by chardan** [comment]
@ceph-jenkins jenkins test this please

**Comment by liewegas** [comment]
/home/sage/src/ceph2/src/osdc/Objecter.h: In member function ‘Objecter::Op* Objecter::prepare_cmpext_op(const object_t&, const object_locator_t&, uint64_t, ceph::bufferlist&, snapid_t, int, Context*, version_t*, ObjectOperation*, int)’:
/home/sage/src/ceph2/src/osdc/Objecter.h:2392:60: error: ‘struct std::atomic<unsigned int>’ has no member named ‘read’; did you mean ‘load’?
     Op *o = new Op(oid, oloc, ops, flags | global_op_flags.read() |

**Comment by chardan** [comment]
Jenkins re-test this please

**Comment by chardan** [comment]
Jenkins, re-test this please.

**Comment by tchaikov** [comment]
retest this please.

**Comment by chardan** [comment]
Jenkins, retest this please.

**Comment by tchaikov** [comment]
@chardan please rebase against master, 0ccebc5c9b5bf819bab1c7f45976d10f7facbbfc introduced a change that you need to fix. that's why you have
```
/home/jenkins-build/build/workspace/ceph-pull-requests/src/osdc/Objecter.h: In member function ‘Objecter::Op* Objecter::prepare_cmpext_op(const object_t&, const object_locator_t&, uint64_t, ceph::bufferlist&, snapid_t, int, Context*, version_t*, ObjectOperation*, int)’:
/home/jenkins-build/build/workspace/ceph-pull-requests/src/osdc/Objecter.h:2395:60: error: ‘struct std::atomic<long int>’ has no member named ‘read’
     Op *o = new Op(oid, oloc, ops, flags | global_op_flags.read() |
                                                            ^
```

**Comment by tchaikov** [comment]
the build still fails.

**Comment by chardan** [comment]
Jenkins retest this please.

**Comment by chardan** [comment]
Jenkins retest this please

**Comment by chardan** [comment]
Jenkins retest this please

**Comment by liewegas** [comment]
build issue:
<pre>
[ 82%] Building CXX object src/test/librbd/CMakeFiles/unittest_librbd.dir/test_Groups.cc.o
In file included from /home/jenkins-build/build/workspace/ceph-pull-requests/src/include/Context.h:19:0,
                 from /home/jenkins-build/build/workspace/ceph-pull-requests/src/journal/Journaler.h:9,
                 from /home/jenkins-build/build/workspace/ceph-pull-requests/src/test/journal/test_Journaler.cc:4:
/home/jenkins-build/build/workspace/ceph-pull-requests/src/common/RefCountedObj.h: In member function ‘const RefCountedObject* RefCountedObject::get() const’:
/home/jenkins-build/build/workspace/ceph-pull-requests/src/common/dout.h:81:12: error: base operand of ‘->’ is not a pointer
   _ASSERT_H->_log->submit_entry(_dout_e);  \
            ^
/home/jenkins-build/build/workspace/ceph-pull-requests/src/common/dout.h:85:15: note: in expansion of macro ‘dendl_impl’
 #define dendl dendl_impl
               ^
/home/jenkins-build/build/workspace/ceph-pull-requests/src/common/RefCountedObj.h:39:12: note: in expansion of macro ‘dendl’
         << dendl;
            ^
/home/jenkins-build/build/workspace/ceph-pull-requests/src/common/dout.h:62:18: warning: unused variable ‘_dout_cct’ [-Wunused-variable]
     CephContext *_dout_cct = cct;     \
                  ^
/home/jenkins-build/build/workspace/ceph-pull-requests/src/common/dout.h:65:32: note: in expansion of macro ‘dout_impl’
 #define lsubdout(cct, sub, v)  dout_impl(cct, ceph_subsys_##sub, v) dout_prefix
                                ^
/home/jenkins-build/build/workspace/ceph-pull-requests/src/common/RefCountedObj.h:37:7: note: in expansion of macro ‘lsubdout’
       lsubdout(cct, refs, 1) << "RefCountedObject::get " << this << " "
</pre>

**Comment by chardan** [comment]
Jenkins retest this please.

**Comment by chardan** [comment]
Hopefully this is finally starting to get a bit less tangled.

**Pull request merged**
