### PR TITLE
hammer: Wip 13039 15315

### PR DESCRIPTION
**Pull request by dzafman**
http://tracker.ceph.com/issues/15315

This branch is really on top of wip-10794-hammer which is pull #7917

### CODE REVIEW

**Comment by dzafman** [comment]
I'm assuming this is really only going to merge the 2 new commits and NOT the first 2 that are already in hammer.

**Comment by dachary** [comment]
@dzafman you could rebase to make that better. It's not a blocker but looks cleaner ;-)

**Comment by dzafman** [comment]
@dachary done!

**Comment by smithfarm** [comment]
Changelog:
* added tracker URL to PR description

**Comment by dzafman** [comment]
Rados run passed with 1 unrelated failure: http://pulpito.ceph.com/dzafman-2016-07-21_13:18:50-rados-wip-zafman-testing-hammer---basic-smithi/

**Comment by smithfarm** [comment]
@liewegas: I had been having some trouble with the `hammer-backports` testing runs - see http://tracker.ceph.com/issues/15895 for details - so @dzafman took matters into his own hands ;-)

Do you think this hammer backport is good to merge?

**Comment by smithfarm** [comment]
@liewegas This PR is in the latest round of hammer-backports integration tests, which passed a rados run (the only failures are a valgrind false positive that has since been fixed by https://github.com/ceph/teuthology/pull/915 and http://tracker.ceph.com/issues/15139 which is an infrastructure issue with two of the tests) - for details, see: http://tracker.ceph.com/issues/15895#note-18

Do you think this PR is OK to merge?

**Comment by smithfarm** [comment]
@liewegas @athanatos @dzafman This PR passed a /200 rados run on Ubuntu. None of the failures were reproducible. For details see http://tracker.ceph.com/issues/15895#note-18

Do you think it's OK to merge?

**Comment by athanatos** [comment]
lgtm if @dzafman is happy

**Comment by dzafman** [comment]
👍

**Pull request merged**
