### PR TITLE
mgr/dashboard: create cephfs snapshot clone

### PR DESCRIPTION
**Pull request by nizamial09**
Fixes: https://tracker.ceph.com/issues/64175

https://github.com/ceph/ceph/assets/71764184/28783a30-a476-457f-891c-36f1555b2e48

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Review by Pegonzal — COMMENTED** [review]
Thanks @nizamial09 looks good,  just a couple things from side though:

- You can click on the clone button even when no snapshot is selected, leading to an error.

- Are we not planning on adding the abiltiy to specify a pool layout?
- And a way to set the maxmimum number of concurrent clones?

**Comment by nizamial09** [comment]
> * You can click on the clone button even when no snapshot is selected, leading to an error.

nice catch, fixed it.


> * Are we not planning on adding the abiltiy to specify a pool layout?

we need to. but that needs to be done not just for the snapshot but for the whole cephfs i guess. Probably we can do it in a single go for all the areas?



> * And a way to set the maxmimum number of concurrent clones?

Technically we can do that still from the UI if we go to configuration page. But we need to find a way to expose them in the cephfs page. I am not sure clone creation form is the best area for it since this deals with a setting that has more scope. I am open for ideas!

**Comment by nizamial09** [comment]
I am also renaming the `Remove Snapshot` button to `Delete Snapshot`

**Comment by cloudbehl** [comment]
> I am also renaming the `Remove Snapshot` button to `Delete Snapshot`

I would say we do it once for all in cephfs.

**Comment by nizamial09** [comment]
> I would say we do it once for all in cephfs.

I'll need to adapt e2es and maybe unit tests as well which might increase the scope and i am afraid if it could delay this PR. That's why I was hesitant.

**Review by cloudbehl — APPROVED** [review]
LGTM.

**Review by Pegonzal — APPROVED** [review]

**Pull request merged**
