### PR TITLE
octopus: qa/tasks/{ceph,ceph_manager}: drop py2 support

### PR DESCRIPTION
**Pull request by ideepika**
Partial backport of https://github.com/ceph/ceph/pull/35817 to Octopus

fixes failures seen in: https://pulpito.ceph.com/?branch=wip-yuri8-testing-2020-10-26-0758-octopus, needed for https://github.com/ceph/ceph/pull/37690/ backport

````
File "/home/teuthworker/src/github.com_ceph_ceph-c_wip-yuri8-testing-2020-10-26-0758-octopus/qa/tasks/ceph.py", line 161, in invoke_logrotate
    stderr=StringIO()
NameError: name 'StringIO' is not defined
2020-10-26T22:58:41.460 INFO:teuthology.orchestra.run.smithi063:> adjust-ulimits ceph-coverage /home/ubuntu/cephtest/archive/coverage ceph --cluster ceph osd dump --format=json
```

### CODE REVIEW

**Comment by smithfarm** [comment]
@ideepika We generally prefer cherry-picks from master over "original research" (commits targeting a stable branch directly). This change was made in master by a7f18e46b911d9047ebb3ac0f9de4d4c2e59c704 ...

So I'm missing: which issue is this fixing? and why can't it be fixed by cherry-picking that commit from master?

**Comment by ideepika** [comment]
should fix missing import for https://github.com/ceph/ceph/pull/37441/files#diff-e6e4facbefde6d6b52e1a4e14cb3e7b031fce71e0e0d5c347c6e37ad09a8ca3cR183 for octopus

> @ideepika We generally prefer cherry-picks from master over "original research" (commits targeting a stable branch directly). This change was made in master by [a7f18e4](https://github.com/ceph/ceph/commit/a7f18e46b911d9047ebb3ac0f9de4d4c2e59c704) ...
> 
> So I'm missing: which issue is this fixing? and why can't it be fixed by cherry-picking that commit from master?

tests were failing for https://pulpito.ceph.com/?branch=wip-yuri8-testing-2020-10-26-0758-octopus, so I added a quick fix, sorry I missed to check on master. I will close this PR and use https://github.com/ceph/ceph/commit/a7f18e46b911d9047ebb3ac0f9de4d4c2e59c704 backport instead, that would be ideal. Thanks!

**Comment by smithfarm** [comment]
I see that a7f18e4 applies cleanly to octopus.

**Comment by smithfarm** [comment]
@ideepika You wouldn't necessarily need to close this PR. You could simply reset the wip branch to octopus and then do `git cherry-pick -x a7f18e4` and force-push.

**Comment by ideepika** [comment]
> I see that [a7f18e4](https://github.com/ceph/ceph/commit/a7f18e46b911d9047ebb3ac0f9de4d4c2e59c704) applies cleanly to octopus.

awesome!!

**Comment by ideepika** [comment]
> @ideepika You wouldn't necessarily need to close this PR. You could simply reset the wip branch to octopus and then do `git cherry-pick -x a7f18e4` and force-push.

sounds great! on it!

**Comment by ideepika** [comment]
@smithfarm thanks! should I create a tracker for it?

**Comment by smithfarm** [comment]
Thanks, @ideepika - I'll leave it to @tchaikov and @kshtsk to review. This patch is part of a large set of patches - I'm not sure how/if/when they plan to backport this work into octopus.

**Comment by smithfarm** [comment]
> @smithfarm thanks! should I create a tracker for it?

No, I don't think a tracker is necessary, but - here again - I defer to @tchaikov and @kshtsk.

**Comment by ideepika** [comment]
> Thanks, @ideepika - I'll leave it to @tchaikov and @kshtsk to review. This patch is part of a large set of patches - I'm not sure how/if/when they plan to backport this work into octopus.

yes, i agree! Let's wait for review.

**Review by yuriw — APPROVED** [review]

**Comment by yuriw** [comment]
[wip-yuri8-testing-2020-10-26-0758-octopus](https://trello.com/c/q40cBqQc/1045-wip-yuri8-testing-2020-10-26-0758-octopus)

**Comment by tchaikov** [comment]
> should fix missing import for https://github.com/ceph/ceph/pull/37441/files#diff-e6e4facbefde6d6b52e1a4e14cb3e7b031fce71e0e0d5c347c6e37ad09a8ca3cR183 for octopus
> 


just to be clear, the root cause of the failure is not that a7f18e4 is "missing" in octopus. the reason is that #37690 depends on a7f18e4.

> This patch is part of a large set of patches - I'm not sure how/if/when they plan to backport this work into octopus.

i have no plan to backport the cleanup change to octopus. i think a7f18e4 alone would suffice to fix the failure introduced by #37690 .

**Review by smithfarm — APPROVED** [review]
If @tchaikov thinks it's OK, then that's enough for me :-)

**Review by tchaikov — APPROVED** [review]

**Review by kshtsk — APPROVED** [review]
Same for me.

**Pull request merged**
