### PR TITLE
mgr/dashboard: Add a sheet to display the supplementary informationen to a datatable item

### PR DESCRIPTION
**Pull request by Exotelis**
As mentioned in the stand up, this will be a draft pull request.

The idea behind this pr was to move the supplementary information, of a datatable item, from below the datatable to a side sheet. This seemed very trivial for me and except one issue it was. The user should be able to close the dialog by clicking on a button. You can test the current implementation at the pools page. 

So selecting a pool will open the side sheet. In the top right corner the user will find the button to close the dialog and removing the selection. And here it becomes tricky. We don't have a single selection instance where we can clear the selection but we have at least three or more. Let me explain:

The pool list creates an instance of the [CdTableSelection](https://github.com/ceph/ceph/blob/master/src/pybind/mgr/dashboard/frontend/src/app/ceph/pool/pool-list/pool-list.component.ts#L52) and also the [CdTable](https://github.com/ceph/ceph/blob/master/src/pybind/mgr/dashboard/frontend/src/app/shared/datatable/table/table.component.ts#L146). This means we already have two independent object of the CdTableSelection and to make it even more complicated we also clone the object in the [CdTable](https://github.com/ceph/ceph/blob/master/src/pybind/mgr/dashboard/frontend/src/app/shared/datatable/table/table.component.ts#L484). The Problem with the clone is that it is just a shallow-copy, that means that the attribute `selected ` will always point to the same reference as the original object. I created a [code snippet](https://codepen.io/Exotelis/pen/JjoPopo) that demonstrates the problem. This can also cause strange behaviour.

In my first implementation I realised, that it is not enough to update the CdTableSelection in the PoolDetails component. And this make sense, because there is no event fired that informs the parent component (PoolList) that the selection changed. What I did was adding an event and it worked, well at least for 5 seconds because then the selection got updated from another component (CdTable) and the sheet was active again. 

In the current implementation I also bind the table to the cd-pool-list where I can also update the selection object of the table when the close button is clicked.

```javascript
closeSheet() {
    this.selection.clear(); // Clear local selection
    this.table.selection.clear(); // Clear selection in table
}
```

Now it's working. I guess I'd also have to add the event again to update the pool-list, because when closing the panel it takes a while until the footer of the datatable is updated where `1 selected / x total` is printed.

But I'm not a fan of my own implementation. I still don't like the fact to have multiple selection object. Using a service might be an idea but I'd like to ask you if you have any other and maybe better ideas.

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by ricardoasmarques** [comment]
My first impression is that it should be safe to remove the `clone` from [CdTable](https://github.com/ceph/ceph/blob/master/src/pybind/mgr/dashboard/frontend/src/app/shared/datatable/table/table.component.ts#L484), which should fix your issue.

**Comment by ricardoasmarques** [comment]
Let me share my initial impressions when looking into this for the first time, so we can discuss them.

Screenshot from 2019-12-02 11-06-34

1) Now that we have a "dedicated page/sheet" for details, maybe we should consider moving `Edit` and other actions related to the selected item to the "Details page" (instead of having them in the table behind). 

2) What about closing "Details page" when the user clicks outside of the "Details page" (instead of forcing the user to always use the "X" button in the top right corner)?

3) I wonder if "Details page" should overlap the menu (I was expecting that menu is always visible).

**Comment by Exotelis** [comment]
@ricardoasmarques

1. I have no opinion on that point yet

2.  The idea was that the sheet can also be closed by pressing the ESC key. I already implemented this and it's working. Clicking outside might also be an idea but when the user selects another item, then the panel should be updated instead.

3. That can be changed fairly easy... It shouldn't be a problem anyway, when we move the menu to the left side. 

4. I like the idea

**Comment by callithea** [comment]
FYI: As discussed in the backlog grooming meeting today, it would be great to have a demo of this implementation in one of our stand-up meetings to gather feedback/ideas.

**Comment by Exotelis** [comment]
We discussed these feature an decided to implement it differently. I'm going to close this pr in favor of https://github.com/ceph/ceph/pull/32747

**Pull request closed without merging**
