### PR TITLE
doc/cephfs: don't recommend ceph-ansible

### PR DESCRIPTION
**Pull request by bluikko**
Stop recommending ceph-ansible and change
it to cephadm instead in add-remove-mds.

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [x] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [x] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by anthonyeleven** [comment]
The desire to include Rook is understandable, but why remove `ceph-ansible`?

**Comment by bluikko** [comment]
> The desire to include Rook is understandable, but why remove `ceph-ansible`?

Excuse me, Rook was there already. I only changed `ceph-ansible` to `cephadm` because I thought `ceph-ansible` is no longer recommended as it is deprecated? Has it risen from the dead?

In the beginning of the page it talks about `cephadm` but then in the next section only about Rook & `ceph-ansible`.

**Comment by anthonyeleven** [comment]
Re ceph-ansible, I think there are nuances with respect to what "recommended" means, including who one asks ;)

**Comment by bluikko** [comment]
I can understand that -- I thought the "official" line is that `cephadm` is the one these days. I'll close this then, sorry for wasting your time.

**Comment by anthonyeleven** [comment]
Not at all, this is what review is for.  Don't hesitate to keep us on our toes.

**Pull request closed without merging**
