### PR TITLE
octopus: qa/distros: Remove stale kubic distros

### PR DESCRIPTION
**Pull request by sebastian-philipp**
Cause they're broken

Signed-off-by: Sebastian Wagner <sewagner@redhat.com>
(cherry picked from commit 65e2cc084073ea7e05ecbc06f5773617676708ff)

Conflicts:
	qa/distros/podman/rhel_8.3_kubic_stable.yaml
	qa/distros/podman/ubuntu_18.04_kubic_stable.yaml
	qa/distros/podman/ubuntu_20.04_kubic_stable.yaml
	qa/distros/podman/ubuntu_20.04_kubic_testing.yaml

Fixes: https://tracker.ceph.com/issues/53106

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Review by ideepika — DISMISSED** [review]
thanks @sebastian-philipp !

**Comment by ideepika** [comment]
```
❯ tree | grep "podman"
│   │   │   │   ├── centos_8.2_container_tools_3.0.yaml -> .qa/distros/podman/centos_8.2_container_tools_3.0.yaml
│   │       │   ├── ubuntu_20.04_kubic_stable.yaml -> .qa/distros/podman/ubuntu_20.04_kubic_stable.yaml
│   │       │   └── ubuntu_20.04_kubic_testing.yaml -> .qa/distros/podman/ubuntu_20.04_kubic_testing.yaml
```

**Comment by sebastian-philipp** [comment]
> ```
> ❯ tree | grep "podman"
> │   │   │   │   ├── centos_8.2_container_tools_3.0.yaml -> .qa/distros/podman/centos_8.2_container_tools_3.0.yaml
> │   │       │   ├── ubuntu_20.04_kubic_stable.yaml -> .qa/distros/podman/ubuntu_20.04_kubic_stable.yaml
> │   │       │   └── ubuntu_20.04_kubic_testing.yaml -> .qa/distros/podman/ubuntu_20.04_kubic_testing.yaml
> ```

fixed!

**Review by ideepika — APPROVED** [review]
lgtm thanks!

**Review by adk3798 — APPROVED** [review]

**Pull request merged**
