### PR TITLE
luminous: os/bluestore: cache autotuning and memory limit

### PR DESCRIPTION
**Pull request by jdurgin**
This is a backport of:

https://github.com/ceph/ceph/pull/22009
https://github.com/ceph/ceph/pull/22838
https://github.com/ceph/ceph/pull/22970

These make bluestore much simpler to configure, since users no longer need to worry about bluestore's cache size or internal details of what is allocated where.

Instead, the osd_memory_target tunable is all that is needed. Since bluestore cannot use the kernel's page cache, the default osd memory target is 4GB. This has no effect on filestore.

### CODE REVIEW

**Comment by jdurgin** [comment]
This passed a rados suite here: http://pulpito.ceph.com/joshd-2018-09-12_06:44:56-rados-wip-luminous-cache-autotune-distro-basic-smithi/

**Comment by yuriw** [comment]
[wip-yuri4-testing-2018-09-15-1645-luminous](https://trello.com/c/ixvfj7WY/405-wip-yuri4-testing-2018-09-15-1645-luminous)

**Comment by yuriw** [comment]
@liewegas @markhpc Pls approve, it passed tests

**Comment by yuriw** [comment]
@smithfarm @theanalyst FYI backport

**Comment by smithfarm** [comment]
The mimic backport @liewegas asked for was done by @jdurgin in https://github.com/ceph/ceph/pull/25283

Thanks, @jdurgin

**Pull request merged**
