### PR TITLE
rgw:  regard layout as a subresource.

### PR DESCRIPTION
**Pull request by yaozongyou**
Regard ?layout as a subresource and append it to string_to_sign on authentication.

Signed-off-by: Yao Zongyou <yaozongyou@vip.qq.com>

### CODE REVIEW

**Comment by yaozongyou** [comment]
2768583dc486109e49d209243675b99fdd39e92c this commit is related.

**Comment by yehudasa** [comment]
@yaozongyou what's the motivation behind this? generic client libraries aren't using 'layout' as a signed subresource

**Comment by yaozongyou** [comment]
@yehudasa yes, only users who have the system capacity can call this API,  Generally, client libraries have no this demand or capacity. But it is better to keep consistent on signing. Getting object's layout is different from getting object content, so the layout is a subresource. By the way, this API is greatly useful, internally, we use this API to get object's each part size on multipart uploading, download the object, calculate each part's md5, and at last, calculate the etag, and compare it with object's etag to check the object is not corrupted.

**Comment by amitkumar50** [comment]
@yaozongyou Please note title should be withing 50 characters.
https://github.com/ceph/ceph/blob/master/SubmittingPatches.rst#title-of-pull-requests-and-title-of-commits

**Comment by yaozongyou** [comment]
@amitkumar50 the title has been changed, thanks.

**Pull request closed without merging**
