### PR TITLE
octopus: mgr/rbd_support: store global schedule without localized prefix

### PR DESCRIPTION
**Pull request by smithfarm**
backport tracker: https://tracker.ceph.com/issues/48086

---

backport of https://github.com/ceph/ceph/pull/37864
parent tracker: https://tracker.ceph.com/issues/48020

this backport was staged using ceph-backport.sh version 15.1.1.389
find the latest version at https://github.com/ceph/ceph/blob/master/src/script/ceph-backport.sh

### CODE REVIEW

**Comment by smithfarm** [comment]
jenkins test docs

**Comment by smithfarm** [comment]
jenkins test api

**Comment by smithfarm** [comment]
jenkins test make check

**Review by dillaman — APPROVED** [review]
:+1:

**Review by trociny — APPROVED** [review]

**Comment by yuriw** [comment]
[wip-yuri7-testing-2020-12-14-0841-octopus](https://trello.com/c/WBLPidv7/1086-wip-yuri7-testing-2020-12-14-0841-octopus)

**Pull request merged**
