### PR TITLE
rgw: support safe base64 encode and decode

### PR DESCRIPTION
**Pull request by DHB-liuhong**
optimize base64 encode/decode,using safe base64 codec

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by DHB-liuhong** [comment]
jenkins test api

**Comment by DHB-liuhong** [comment]
jenkins test pull_request

**Comment by DHB-liuhong** [comment]
jenkins test make check (arm64)

**Comment by DHB-liuhong** [comment]
@yuvalif Can you review it for me? thanks

**Comment by DHB-liuhong** [comment]
@mattbenjamin Can you review it for me? thanks

**Comment by cbodley** [comment]
@DHB-liuhong can you please describe the bug you're trying to fix here? i assume this is about making base64-encoded strings safe for use in URLs; but where does this happen?

**Comment by mattbenjamin** [comment]
from what I can see that's what it is, but could use a reference and some kind of unit test?

**Comment by mattbenjamin** [comment]
also, if we need to filter specific characters, should that not be conditional?

**Pull request closed without merging**
