### PR TITLE
rgw: tagging field support nested search

### PR DESCRIPTION
**Pull request by tianshan**
add mapping for tagging field

fixes: http://tracker.ceph.com/issues/23882

Signed-off-by: Tianshan Qu <tianshan@xsky.com>

### CODE REVIEW

**Comment by tianshan** [comment]
I think custom type use "key" is better instead of "name" , if so, I will just modify dump_custom

**Comment by theanalyst** [comment]
I guess text/string still makes sense here, keyword expects exact matches, not sure whether that is strictly necessary for tagging (may be for tagging keys?)

**Comment by tianshan** [comment]
@theanalyst  no, without nested type, we can not match one tag key from the tagging group

**Comment by theanalyst** [comment]
nested type is ok; was just debating on keyword type, but looks good as is.

**Comment by ZVampirEM77** [comment]
@theanalyst  ping

**Comment by ZVampirEM77** [comment]
I think  the accuracy of metadata searching will be improved if we modify the tagging field to nested type.

**Pull request closed without merging**
