### PR TITLE
pacific: mgr/nfs: nfs-rgw batch backport

### PR DESCRIPTION
**Pull request by sebastian-philipp**
Backport of #41510, #41509, #41964, #41574, #42278, #42073, #42406, #42463, #42627, #42680, #42691, #42682, #42759

conflicts:
```
git log -n 150 | grep -A 2 -B 20 Conflicts
commit 0bbcbea0395835022188f29b7b113aa3aae31781
Author: Varsha Rao <varao@redhat.com>
Date:   Wed Aug 4 16:05:47 2021 +0530

    src/vstart: create rgw export for nfs
    
    Fixes: https://tracker.ceph.com/issues/51800
    Signed-off-by: Varsha Rao <varao@redhat.com>
    (cherry picked from commit 8a77e017fd2110ec9d7fbc0a33de0fb85f14cbca)
    
    Conflicts:
            src/vstart.sh
--
commit 7a93aff09e782783d0068af96ad1e3bfea263501
Author: Sage Weil <sweil@redhat.com>
Date:   Fri Jul 2 12:39:29 2021 -0400

    mgr/nfs: change nfs pool to .nfs
    
    This is a new pool that we can migrate all past NFS configuration to,
    simplifying the migration process (and also allowing us to pick a
    .-prefixed name).
    
    Signed-off-by: Sage Weil <sage@newdream.net>
    (cherry picked from commit 82e939d89c3b6e2ce6faad9a5315c5372fef341d)
    
    Conflicts:
            src/pybind/mgr/rook/rook_cluster.py
--
commit 6532c9e6f5a1fb47cfe9c31e5abc079f3d23de42
Author: Sage Weil <sweil@redhat.com>
Date:   Mon Jun 28 14:44:27 2021 -0400

    mgr/rook: used fixed pool + ns
    
    Signed-off-by: Sage Weil <sage@newdream.net>
    (cherry picked from commit d799f9b5bdf39b2c3226cd160ac5f470951eea67)
    
    Conflicts:
            src/pybind/mgr/rook/rook_cluster.py
--
commit 3a15d5d04878649d8c20f44a9db687b6ec11cd4f
Author: Varsha Rao <varao@redhat.com>
Date:   Mon Jul 12 13:01:49 2021 +0530

    doc/mgr/nfs: update about RGW exports
    
    This patch just moves the RGW exports created using nfs module to mgr/nfs
    document. The RGW requirements will be updated in a different PR.
    
    Signed-off-by: Varsha Rao <varao@redhat.com>
    (cherry picked from commit 387369373cba9f569b5fd84e64fffb0fe8de6821)
    
    Conflicts:
            doc/mgr/nfs.rst
--
commit 3aaa55008eb728837537c58b744f4da11938118b
Author: Varsha Rao <varao@redhat.com>
Date:   Mon Jul 12 12:38:36 2021 +0530

    doc/cephfs/nfs: update about nfs module
    
    Signed-off-by: Varsha Rao <varao@redhat.com>
    (cherry picked from commit 65489e8d3e7f40f19e1df5ed6871d7116e4a5023)
    
    Conflicts:
        doc/cephfs/nfs.rst

commit d67e1fbc896de53700dee19d5b7e8c1ebc0a8c74
Author: Varsha Rao <varao@redhat.com>
Date:   Tue Jun 29 19:09:44 2021 +0530

    doc/mgr/nfs: update nfs links
    
    Signed-off-by: Varsha Rao <varao@redhat.com>
    (cherry picked from commit ce7fef695b82d798ed38728ccc032990b1ad9dd9)
    
    Conflicts:
            .github/labeler.yml
            doc/releases/pacific.rst
--
commit cd1cd61cc261d9e8da82328df53e07cdcf4a66e5
Author: Sebastian Wagner <sewagner@redhat.com>
Date:   Wed Jun 2 16:04:21 2021 +0200

    mgr/nfs: flake8
    
    Signed-off-by: Sebastian Wagner <sewagner@redhat.com>
    (cherry picked from commit a24e912099851a7c77d453afa84154858233e7d8)
    
    Conflicts:
            src/pybind/mgr/tox.ini

commit 57734623d97660b668577c6f80338d4323bd4ef2
Author: Sebastian Wagner <sewagner@redhat.com>
Date:   Wed Jun 2 15:55:02 2021 +0200

    mgr/nfs: Add type checking
    
    Also introduce RawBlock class
    
    Fixes: https://tracker.ceph.com/issues/50816
    Signed-off-by: Sebastian Wagner <sewagner@redhat.com>
    (cherry picked from commit 42d01c5ed3da749d2af6d3debffd3e117d18856f)
    
    Conflicts:
            src/mypy.ini

--
commit 51c4ac85824efdecebb629ee48a86828cb0acc35
Author: Sage Weil <sweil@redhat.com>
Date:   Wed May 26 13:44:04 2021 -0400

    vstart.sh: enable nfs module
    
    Signed-off-by: Sage Weil <sage@newdream.net>
    (cherry picked from commit 9b9c5bc7a4bebec2b03b7ff4367b8964f02614ae)
    
    Conflicts:
            src/vstart.sh
--
commit 9ff011457f8ce29f0b230a5ddc9f8867e5d4f7d0
Author: Ramana Raja <rraja@redhat.com>
Date:   Mon Jun 21 22:47:55 2021 -0400

    doc/cephfs/nfs: update recommendation for versions
    
    ... of Ceph and NFS-Ganesha packages.
    
    Signed-off-by: Ramana Raja <rraja@redhat.com>
    (cherry picked from commit e031a5969120c43adc5b20ca004e6540dffd1579)
    
    Conflicts:
            doc/cephfs/nfs.rst
--
commit b0411b5377ebbcab155518842957e53afa632eae
Author: Sage Weil <sweil@redhat.com>
Date:   Tue May 25 10:53:01 2021 -0400

    doc/_ext/ceph_commands: handle non-positional args in docs
    
    Signed-off-by: Sage Weil <sage@newdream.net>
    (cherry picked from commit 295a5f282710efa7c3815faaa3919f1018d04066)
    
    Conflicts:
            doc/_ext/ceph_commands.py
--
commit 29999e289680ec98c0786711f8c33b30cd5a9f6e
Author: Sage Weil <sweil@redhat.com>
Date:   Mon May 24 16:03:33 2021 -0500

    doc/cephfs/nfs: remove documented limitation
    
    At the time NFS support was added, this limitation applied.
    However, in
     https://github.com/nfs-ganesha/nfs-ganesha/commit/b3d97f8157a131f55d848ff57e46af91b746b944
    and
     https://github.com/nfs-ganesha/nfs-ganesha/commit/1cfe7e2df96f9785367ba94d41559140f584a875
    we added support for multiple filesystems and started mixing
    the fscid into the filehandle.
    
    Signed-off-by: Sage Weil <sage@newdream.net>
    (cherry picked from commit a534f7be3601a18cd7e26af67031f2dfe3fead7b)
    
    Conflicts:
            doc/cephfs/nfs.rst
```

### CODE REVIEW

**Comment by liewegas** [comment]
```
In file included from /home/jenkins-build/build/workspace/ceph-pull-requests/src/msg/msg_types.h:22,
                 from /home/jenkins-build/build/workspace/ceph-pull-requests/src/common/ceph_context.h:36,
                 from /home/jenkins-build/build/workspace/ceph-pull-requests/src/common/dout.h:29,
                 from /home/jenkins-build/build/workspace/ceph-pull-requests/src/common/debug.h:18,
                 from /home/jenkins-build/build/workspace/ceph-pull-requests/src/common/cmdparse.cc:18:
/home/jenkins-build/build/workspace/ceph-pull-requests/src/common/cmdparse.cc: In function 'void ceph::common::dump_cmd_to_json(ceph::Formatter*, uint64_t, const string&)':
/home/jenkins-build/build/workspace/ceph-pull-requests/src/include/ceph_features.h:36:11: error: 'CEPH_FEATUREMASK_SERVER_QUINCY' was not declared in this scope; did you mean 'CEPH_FEATUREMASK_SERVER_MIMIC'?
   36 |  (((x) & (CEPH_FEATUREMASK_##name)) == (CEPH_FEATUREMASK_##name))
      |           ^~~~~~~~~~~~~~~~~
/home/jenkins-build/build/workspace/ceph-pull-requests/src/common/cmdparse.cc:183:7: note: in expansion of macro 'HAVE_FEATURE'
  183 |  if (!HAVE_FEATURE(features, SERVER_QUINCY)) {
      |       ^~~~~~~~~~~~
/home/jenkins-build/build/workspace/ceph-pull-requests/src/include/ceph_features.h:36:11: error: 'CEPH_FEATUREMASK_SERVER_QUINCY' was not declared in this scope; did you mean 'CEPH_FEATUREMASK_SERVER_MIMIC'?
   36 |  (((x) & (CEPH_FEATUREMASK_##name)) == (CEPH_FEATUREMASK_##name))
      |           ^~~~~~~~~~~~~~~~~
/home/jenkins-build/build/workspace/ceph-pull-requests/src/common/cmdparse.cc:187:34: note: in expansion of macro 'HAVE_FEATURE'
  187 |       } else if (key == "req" && HAVE_FEATURE(features, SERVER_QUINCY)) {
      |                                  ^~~~~~~~~~~~
```

**Comment by varshar16** [comment]
@sebastian-philipp https://github.com/ceph/ceph/pull/42682 is already backported

**Comment by sebastian-philipp** [comment]
> ```
> In file included from /home/jenkins-build/build/workspace/ceph-pull-requests/src/msg/msg_types.h:22,
>                  from /home/jenkins-build/build/workspace/ceph-pull-requests/src/common/ceph_context.h:36,
>                  from /home/jenkins-build/build/workspace/ceph-pull-requests/src/common/dout.h:29,
>                  from /home/jenkins-build/build/workspace/ceph-pull-requests/src/common/debug.h:18,
>                  from /home/jenkins-build/build/workspace/ceph-pull-requests/src/common/cmdparse.cc:18:
> /home/jenkins-build/build/workspace/ceph-pull-requests/src/common/cmdparse.cc: In function 'void ceph::common::dump_cmd_to_json(ceph::Formatter*, uint64_t, const string&)':
> /home/jenkins-build/build/workspace/ceph-pull-requests/src/include/ceph_features.h:36:11: error: 'CEPH_FEATUREMASK_SERVER_QUINCY' was not declared in this scope; did you mean 'CEPH_FEATUREMASK_SERVER_MIMIC'?
>    36 |  (((x) & (CEPH_FEATUREMASK_##name)) == (CEPH_FEATUREMASK_##name))
>       |           ^~~~~~~~~~~~~~~~~
> /home/jenkins-build/build/workspace/ceph-pull-requests/src/common/cmdparse.cc:183:7: note: in expansion of macro 'HAVE_FEATURE'
>   183 |  if (!HAVE_FEATURE(features, SERVER_QUINCY)) {
>       |       ^~~~~~~~~~~~
> /home/jenkins-build/build/workspace/ceph-pull-requests/src/include/ceph_features.h:36:11: error: 'CEPH_FEATUREMASK_SERVER_QUINCY' was not declared in this scope; did you mean 'CEPH_FEATUREMASK_SERVER_MIMIC'?
>    36 |  (((x) & (CEPH_FEATUREMASK_##name)) == (CEPH_FEATUREMASK_##name))
>       |           ^~~~~~~~~~~~~~~~~
> /home/jenkins-build/build/workspace/ceph-pull-requests/src/common/cmdparse.cc:187:34: note: in expansion of macro 'HAVE_FEATURE'
>   187 |       } else if (key == "req" && HAVE_FEATURE(features, SERVER_QUINCY)) {
>       |                                  ^~~~~~~~~~~~
> ```

@liewegas , It's going to be a bit up to you how to handle those cli changes in pacific.

**Comment by liewegas** [comment]
> @liewegas , It's going to be a bit up to you how to handle those cli changes in pacific.

I think we need to leave off this series of patches for positional args; they aren't safe to backport to a stable series.  I suspect you included them to avoid conflicts around the function signatures?  I think we need to just deal with those conflicts one by one :(.. hopefully not too painful!

**Comment by sebastian-philipp** [comment]
changelog:
  * removed positional arguments
  * fixed merge conflict in PendingReleaseNotes
  * removed automated mgr/prometheus activation

**Comment by sebastian-philipp** [comment]
* https://pulpito.ceph.com/swagner-2021-09-20_15:03:24-rados:cephadm-wip-swagner2-testing-2021-09-20-1012-pacific-distro-basic-smithi/
* https://pulpito.ceph.com/swagner-2021-09-20_16:06:50-rados:cephadm-wip-swagner2-testing-2021-09-20-1012-pacific-distro-basic-smithi/ (ongoing)

**Review by liewegas — APPROVED** [review]

**Pull request merged**
