### PR TITLE
cleanup: Replacing MIN,MAX with std::min,std::max

### PR DESCRIPTION
**Pull request by amitkumar50**
Signed-off-by: Amit Kumar <amitkuma@redhat.com>

### CODE REVIEW

**Comment by amitkumar50** [comment]
@liewegas Can you please review?

**Comment by liewegas** [comment]
Looks good, but needs rebase. Also, can you verify it doesn't generate new warnings?

**Comment by amitkumar50** [comment]
@liewegas Will do that ..

**Comment by amitkumar50** [comment]
It does not generates new warning, would be resolving merge conflicts

**Comment by amitkumar50** [comment]
@liewegas Can you plz review?

**Comment by amitkumar50** [comment]
@liewegas ping

**Comment by tchaikov** [comment]
- http://pulpito.ceph.com/kchai-2017-11-29_16:42:05-rados-wip-kefu-testing-2017-11-29-2317-distro-basic-mira/
- http://pulpito.ceph.com/kchai-2017-11-30_07:07:30-rados-wip-kefu-testing-2017-11-29-2317-distro-basic-smithi/
- http://pulpito.ceph.com/kchai-2017-12-01_02:01:54-rados-wip-kefu-testing-2017-11-29-2317-distro-basic-mira/

**Pull request merged**
