### PR TITLE
mon: add "node ls [mon|osd|mds]" command

### PR DESCRIPTION
**Pull request by tchaikov**
* this command print all node names

Fixes: #10904
Signed-off-by: Kefu Chai <kchai@redhat.com>

### CODE REVIEW

**Comment by jcsp** [comment]
Was the intention really to print the service IDs for mons and MDSs?  From the ticket I would have expected to see hostnames or FQDNs.  We don't currently have those in the mons, but it would by fine IMHO to add an equivalent of the "osd metadata" mechanism for the MDSs and mons.

**Comment by tchaikov** [comment]
@jcsp i talked with @alfredodeza about this ticket couple times, and this is where we converge on. yes, as we don't have hostname or FQDN in monmap, mdsmap or osdmap/crush, the hostname would be desirable. but that's not alfredo is after, i think.

**Comment by gregsfortytwo** [comment]
These aren't listing nodes, these are listing daemons that might be involved with the system. The command name should match what it does, not what Alfredo wished it did. ;)

**Comment by alfredodeza** [comment]
It seems there is still confusion here about the ticket :(

The problem is to be able to understand what all nodes are, and maybe (if possible) list the nodes by OSD/MDS/MON 

http://tracker.ceph.com/issues/10904

Service IDs will not work. Again, refer to the specifics of the ticket, and let me know if the wording needs to change.

I agree with @jcsp assessment of how to resolve situations where we don't have a FQDN

**Comment by tchaikov** [comment]
@alfredodeza i thought we agreed on having the `name` as the output of this command. and what you wanted was in the output of three commands you listed in the ticket. and your intention was to avoid the grep and awk. as we the `osd tree`, `mon dump` and `mds dump` commands do not offer hostname or FQDN, and you also nodded on what fields we needed last night, that's the result of discussion with us: see http://tracker.ceph.com/issues/10904#note-8. hence this PR.

if we are going to have something like "osd metadata", probably we need to add a metadata field in `MMonJoin` message, and probably add another `PaxosServiceMessage` for mds, i guess. and store them into mon's storage using `MDSMonitor` and `MonMapMonitor`. that would need more discussion and work, i think.

let me know your call.

**Comment by tchaikov** [comment]
just talked with sam, so we are going to follow @jcsp 's idea of implementing the "{mds,mon} metadata". and the `MMDSBeacon` is the message for MDS to carry the metadata.

**Comment by liewegas** [comment]
:+1:

**Pull request closed without merging**
