### PR TITLE
qa/cephfs: mark file system joinable for fs rename tests before unmou…

### PR DESCRIPTION
**Pull request by vshankar**
…nting clients

Fixes: http://tracker.ceph.com/issues/66088

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Comment by vshankar** [comment]
@rishabh-d-dave https://tracker.ceph.com/issues/66088#note-3

**Review by rishabh-d-dave — APPROVED** [review]
Looks good.

**Review by rishabh-d-dave — CHANGES_REQUESTED** [review]
`self.skipTest()` needs to be deleted from this test. It's not visible in this patch but without removing this test will be skipped.

**Comment by vshankar** [comment]
> `self.skipTest()` needs to be deleted from this test. It's not visible in this patch but without removing this test will be skipped.

good catch!

**Review by rishabh-d-dave — APPROVED** [review]

**Comment by vshankar** [comment]
@rishabh-d-dave If you don't mind I'll pull in commits from https://github.com/ceph/ceph/pull/57624 into this change?

**Comment by rishabh-d-dave** [comment]
> @rishabh-d-dave If you don't mind I'll pull in commits from #57624 into this change?

@vshankar Cool.

**Review by rishabh-d-dave — APPROVED** [review]

**Comment by vshankar** [comment]
@rishabh-d-dave thx. I also adjusted the commit message a bit :)

**Comment by vshankar** [comment]
This PR is under test in [https://tracker.ceph.com/issues/66327](https://tracker.ceph.com/issues/66327).

**Comment by vshankar** [comment]
This PR is under test in [https://tracker.ceph.com/issues/66522](https://tracker.ceph.com/issues/66522).

**Comment by vshankar** [comment]
https://tracker.ceph.com/projects/cephfs/wiki/Main#wip-vshankar-testing-20240617094253-debug

(https://tracker.ceph.com/issues/66522)

**Comment by vshankar** [comment]
jenkins retest this please

**Pull request merged**
