### PR TITLE
tools/rados: add touch2 command to change object modification time

### PR DESCRIPTION
**Pull request by yaozongyou**
Signed-off-by: Yao Zongyou <yaozongyou@vip.qq.com>

### CODE REVIEW

**Comment by yaozongyou** [comment]
jenkins retest this please

**Comment by gregsfortytwo** [comment]
Why would you ever need mtimes that precise in a RADOS cluster?

**Comment by yaozongyou** [comment]
@gregsfortytwo currently only used for test~~for example, for testing rgw lifecycle, we may change object's mtime in head_obj and change the object's mtime in bucket index (the time in head_obj and bucket index should keep consistent. The time in bucket index is in high precision). And then runing `radosgw-admin lc process` to test if object lifecycled upon configuration.

**Comment by gregsfortytwo** [comment]
Well I don't love it, but I guess that's a good reason.

As this is going into a public-facing tool it needs tests validating behavior before we can merge, though!

**Pull request closed without merging**
