### PR TITLE
squid: mds/quiesce: prevent an overflow of the wait duration

### PR DESCRIPTION
**Pull request by batrick**
backport tracker: https://tracker.ceph.com/issues/65289

---

backport of https://github.com/ceph/ceph/pull/56542
parent tracker: https://tracker.ceph.com/issues/65276

this backport was staged using ceph-backport.sh version 16.0.0.6848
find the latest version at https://github.com/ceph/ceph/blob/main/src/script/ceph-backport.sh

### CODE REVIEW

**Comment by batrick** [comment]
jenkins test make check

**Comment by leonid-s-usov** [comment]
@batrick the failed test should have been addressed by a backport of #56245, which is missing.

**Comment by leonid-s-usov** [comment]
It appears I haven't pushed it: 

```
Counting objects: 100% (281/281), done.
* 8fba6b5d3f0 - (3 weeks ago) mds/quiesce-db: always clear the db if a membership is lost - Leonid Usov (HEAD -> bp/quiesce-db/squid, ci/wip-lusov-qdb-squid)
* aba3c1d240c - (4 weeks ago) mds/quiesce-db: keep the db thread alive until shutdown - Leonid Usov (origin/wip-lusov-qdb-squid)
```

I'll reopen the tracker and push the missing commit separately

**Comment by leonid-s-usov** [comment]
https://github.com/ceph/ceph/pull/56695

**Comment by batrick** [comment]
jenkins test make check

**Comment by leonid-s-usov** [comment]
jenkins test make check

**Comment by leonid-s-usov** [comment]
jenkins test make check

**Review by leonid-s-usov — APPROVED** [review]

**Pull request merged**
