### PR TITLE
mgr/dashboard:Cancel button leads to the previous page in browser history 

### PR DESCRIPTION
**Pull request by Seremba**
This commit changes the behavior of the Cancel button from relying on browser history to rely on the
router hierarchy.

Fixes: https://tracker.ceph.com/issues/39121
Signed-off-by: Seremba Patrick <pserembae@gmail.com>

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [x] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [x] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [x] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by Seremba** [comment]
Hi @epuertat , @ljflores I request for your review of this PR. Thanks a lot.

**Comment by epuertat** [comment]
@Seremba have you manually tested this? In what pages? I tested in the Pools - Image - Create modal, and it broke:
```
polyfills.js:214 Uncaught TypeError: Cannot read properties of null (reading 'previousNavigation')
    at new BackButtonComponent (main.js:29964:69)
    at NodeInjectorFactory.BackButtonComponent_Factory [as factory] (main.js:29975:77)
    at getNodeInjectable (vendor.js:17994:44)
    at instantiateAllDirectives (vendor.js:24731:27)
    at createDirectivesInstances (vendor.js:24080:5)
    at Module.ɵɵelementStart (vendor.js:29333:9)
    at FormButtonPanelComponent_Template (main.js:31412:69)
    at executeTemplate (vendor.js:24051:9)
    at renderView (vendor.js:23854:13)
    at renderComponent (vendor.js:25135:5)
```

**Comment by Seremba** [comment]
sorry about that, let me test it again manually. Though it was working well on my PC

**Comment by Seremba** [comment]
Hi @epuertat , I have made a few changes to the PR. I have tested  manually when it is working properly and also the jest tests  for it were all okay. I kindly seek your review on it. Thanks a lot.

**Comment by Seremba** [comment]
Hi @epuertat, and @ljflores any code review on this PR?

**Pull request closed without merging**
