### PR TITLE
docs/start: fix min. hardware rec. typo

### PR DESCRIPTION
**Pull request by zdover23**
The minimum hardware recommendations said that we
recommended a minimum of "24GB+ per daemon".

I changed this to read "2-4GB+ per daemon".

Reddit actually caught this one:
https://www.reddit.com/r/ceph/comments/q14ey2/cephs_mon_minimum_requirements/

Signed-off-by: Zac Dover <zac.dover@gmail.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Review by jdurgin — APPROVED** [review]
looks good, just remove the extra space to make the table parse correctly

**Comment by zdover23** [comment]
> looks good, just remove the extra space to make the table parse correctly

I've removed that extra space. Good catch.

Unrelated, but worth bringing up: When I build the docs locally, I see this:
md5sum: WARNING: 1 computed checksum did NOT match

What's up with that?

**Review by jdurgin — APPROVED** [review]

**Comment by jdurgin** [comment]
> Unrelated, but worth bringing up: When I build the docs locally, I see this: md5sum: WARNING: 1 computed checksum did NOT match
> 
> What's up with that?

I'm not sure, is it causing any issues?

**Comment by zdover23** [comment]
> > Unrelated, but worth bringing up: When I build the docs locally, I see this: md5sum: WARNING: 1 computed checksum did NOT match
> > What's up with that?
> 
> I'm not sure, is it causing any issues?

It seems to build fine. It's just an example of a confusing error message.

**Comment by tchaikov** [comment]
> > looks good, just remove the extra space to make the table parse correctly
> 
> I've removed that extra space. Good catch.
> 
> Unrelated, but worth bringing up: When I build the docs locally, I see this: md5sum: WARNING: 1 computed checksum did NOT match
> 
> What's up with that?

i think it's just that the imported python libraries changed since last run. if you rerun the `build-doc` script, the warning should disappear.

if this warning keeps showing up. i will try to fix it.

**Comment by zdover23** [comment]
> > > looks good, just remove the extra space to make the table parse correctly
> > 
> > 
> > I've removed that extra space. Good catch.
> > Unrelated, but worth bringing up: When I build the docs locally, I see this: md5sum: WARNING: 1 computed checksum did NOT match
> > What's up with that?
> 
> i think it's just that the imported python libraries changed since last run. if you rerun the `build-doc` script, the warning should disappear.

This happened exactly as foretold. Truly, you are oracular.

> if this warning keeps showing up. i will try to fix it.

**Comment by anthonyeleven** [comment]
Wish I'd seen this PR sooner.

cf [https://github.com/ceph/ceph/pull/37587]
The 24GB figure was deliberate on my part, a result of having seen the RAM that ceph-mon and especially ceph-mgr consume in real life.

**Pull request merged**
