### PR TITLE
mds: regular file inode flags are not replicated by the policylock

### PR DESCRIPTION
**Pull request by batrick**
## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
- Component impact
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [x] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Comment by batrick** [comment]
This PR is under test in [wip-pdonnell-testing-20240417.020632-debug](wip-pdonnell-testing-20240417.020632-debug.

**Comment by batrick** [comment]
This PR is under test in [https://tracker.ceph.com/issues/65528](https://tracker.ceph.com/issues/65528.

**Comment by batrick** [comment]
This PR is under test in [https://tracker.ceph.com/issues/65529](https://tracker.ceph.com/issues/65529).

**Comment by batrick** [comment]
This PR is under test in [https://tracker.ceph.com/issues/65530](https://tracker.ceph.com/issues/65530).

**Comment by batrick** [comment]
jenkins test make check

**Comment by batrick** [comment]
jenkins test windows

**Comment by batrick** [comment]
This PR is under test in [https://tracker.ceph.com/issues/65562](https://tracker.ceph.com/issues/65562).

**Comment by batrick** [comment]
jenkins test make check

**Comment by batrick** [comment]
jenkins test windows

**Comment by batrick** [comment]
jenkins test make check

**Review by leonid-s-usov — CHANGES_REQUESTED** [review]
73253f360c3a24ad7101d32a0434f91176a88f9d is now in conflict with https://github.com/ceph/ceph/pull/57020, and it appears that here the fix wasn't correct. We want to go for the `xlock_finish` for local xlock, rather than silently put it as it's done here.

**Comment by batrick** [comment]
> [73253f3](https://github.com/ceph/ceph/commit/73253f360c3a24ad7101d32a0434f91176a88f9d) is now in conflict with #57020, and it appears that here the fix wasn't correct. We want to go for the `xlock_finish` for local xlock, rather than silently put it as it's done here.

ack, thanks. I'll remove from this PR.

**Comment by batrick** [comment]
https://tracker.ceph.com/projects/cephfs/wiki/Main#2024-04-20

**Comment by batrick** [comment]
needs rerun as the commit noted above has been removed

**Review by leonid-s-usov — APPROVED** [review]
You should run it with https://github.com/ceph/ceph/pull/57020 included to avoid the said crash

**Comment by batrick** [comment]
This PR is under test in [https://tracker.ceph.com/issues/65661](https://tracker.ceph.com/issues/65661).

**Comment by batrick** [comment]
This PR is under test in [https://tracker.ceph.com/issues/65694](https://tracker.ceph.com/issues/65694).

**Comment by batrick** [comment]
https://tracker.ceph.com/issues/65694#note-2

**Pull request merged**
