### PR TITLE
jewel: [librados_test_stub] cls_cxx_map_get_XYZ methods don't return correct value

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/19610

### CODE REVIEW

**Comment by smithfarm** [comment]
@dillaman This passed a rados run at http://tracker.ceph.com/issues/19538#note-39

What other testing does it need?

**Comment by smithfarm** [comment]
@dillaman - this one was done: http://tracker.ceph.com/issues/19538#note-47

Is that enough, or should I wait until the next round?

**Comment by dillaman** [comment]
@smithfarm All set if it was included in a rbd suite run

**Comment by smithfarm** [comment]
@dillaman It was included, but the run had those 8 TestLibRBD.Mirror failures which might be covering up a different failure caused by this PR.

**Comment by dillaman** [comment]
@smithfarm Understood -- I think it's near zero risk and acceptable to merge

**Pull request merged**
