### PR TITLE
jewel: rgw: add suport for Swift-at-root dependent features of Swift API 

### PR DESCRIPTION
**Pull request by rzarzynski**
http://tracker.ceph.com/issues/17208
http://tracker.ceph.com/issues/18526

This is the Jewel backport of PR #10280. Currently under testing.

CC: @dachary, @yehudasa.

### CODE REVIEW

**Comment by dachary** [comment]
jenkins test this please (no log)

**Comment by dachary** [comment]
jenkins test this please (jenkins failure)

**Comment by rzarzynski** [comment]
Removed the _DNM_ tag after testing. s3-tests nor Tempest haven't found any regression in comparison to the `jewel` branch. Tempest confirmed the `/info` and friends are operational. Following testcases pass after the changes:
```
tempest.api.object_storage.test_account_services.AccountTest.test_list_extensions
tempest.api.object_storage.test_crossdomain.CrossdomainTest.test_get_crossdomain_policy
tempest.api.object_storage.test_healthcheck.HealthcheckTest.test_get_healthcheck
```
Additionally, [the issue 17961](http://tracker.ceph.com/issues/17961) in `jewel` has been discovered during the verification of this backport. The bug is definitely unrelated -- it appears on the `jewel` branch as well.

CC: @dachary, @yehudasa, @cbodley, @pritha-srivastava.

**Comment by cbodley** [comment]
@rzarzynski please make sure that your backport commits include the line `(cherry picked from commit XXX)` so we can associate them with their commits on master (`cherry-pick -x` includes this for you)

**Comment by rzarzynski** [comment]
@cbodley: Thanks for pointing this out! Updated the commit messages. Absolutely no other changes.

**Comment by dachary** [comment]
jenkins test this please

**Comment by dachary** [comment]
@rzarzynski there are conflicts in  	6031bfd which comes from the master commit https://github.com/ceph/ceph/commit/277079da3c57f61221254f266b698ab3962ef87c . The master commit must not contain Conflicts, but it is merged so we can't do anything about it. For this backport and to avoid confusion could you remove the "Conflicts" ? Unless there actually was a conflict when cherry-picking in which case it would have to be explained in the same way you explained the previous conflicts.

**Comment by rzarzynski** [comment]
@dachary: I just pushed https://github.com/ceph/ceph/pull/11497/commits/22eca660b47288e9c29be758b851366367a1ec1 with the `Conflicts` part removed. Also doubled checked it was only an artifact from `master` -- the commit applies cleanly on top of https://github.com/ceph/ceph/pull/11497/commits/5b89e7b896ecb53801441ebfb1f9ffdd3c990093.

There are absolutely no other changes than the modification of the commit message.

**Comment by dachary** [comment]
@rzarzynski excellent, thanks !

**Comment by dachary** [comment]
test this please

**Comment by smithfarm** [comment]
This passed rgw runs at http://tracker.ceph.com/issues/17851#note-50 and http://tracker.ceph.com/issues/17851#note-58

**Comment by smithfarm** [comment]
```
(11:46:45 AM) smithfarm: owasserm: thanks. For jewel integration rgw, then, what it comes down to is verifying that these 6 valgrind failures are all libtcmalloc-related: http://pulpito.front.sepia.ceph.com/smithfarm-2017-01-31_12:35:14-rgw-wip-jewel-backports-distro-basic-smithi/
(11:46:58 AM) smithfarm: owasserm: I will do that now
(11:47:05 AM) owasserm: smithfarm, thanks
(11:47:33 AM) smithfarm: owasserm: and assuming they are tcmalloc related, you said I can directly merge all the rgw PRs? Or do you want me to ask you for review in the PRs first?
(11:47:53 AM) owasserm: smithfarm, yes you can merge them
(11:48:19 AM) smithfarm: ok, will merge and do at least one or two more rgw runs before passing 10.2.6 to QE
```

**Pull request merged**
