### PR TITLE
octopus: build/ops: ceph.spec: fix mgr diskprediction_local dependency

### PR DESCRIPTION
**Pull request by shyukri**
backport tracker: https://tracker.ceph.com/issues/47097

---

backport of https://github.com/ceph/ceph/pull/35648
parent tracker: https://tracker.ceph.com/issues/44948

this backport was staged using ceph-backport.sh version 15.1.1.389
find the latest version at https://github.com/ceph/ceph/blob/master/src/script/ceph-backport.sh

### CODE REVIEW

**Review by LenzGr — APPROVED** [review]
LGTM!

**Review by tchaikov — APPROVED** [review]

**Comment by yuriw** [comment]
[wip-yuri5-testing-2020-09-29-0919-octopus](https://trello.com/c/kGYaCHPv/1026-wip-yuri5-testing-2020-09-29-0919-octopus)

**Comment by yuriw** [comment]
[wip-yuri7-testing-2020-10-04-0852-octopus](https://trello.com/c/tLpholMk/1031-wip-yuri7-testing-2020-10-04-0852-octopus)

**Comment by ideepika** [comment]
the package not available for centos, please DNM

**Review by tchaikov — CHANGES_REQUESTED** [review]
@shyukri could you include #35767 in this PR?

**Review by tchaikov — APPROVED** [review]

**Review by smithfarm — CHANGES_REQUESTED** [review]
Needs cherry-pick of https://github.com/ceph/ceph/pull/37801 (but not before that PR is merged)

**Comment by smithfarm** [comment]
let's try this one again

**Pull request closed without merging**
