### PR TITLE
rgw: put bucket policy panics RGW process

### PR DESCRIPTION
**Pull request by qrGitHub**
Fixes: http://tracker.ceph.com/issues/22541
Signed-off-by: Bingyin Zhang <zhangbingyin@cloudin.cn>

### CODE REVIEW

**Comment by qrGitHub** [comment]
Hi @joscollin, would you help to review this? Thanks.

**Comment by yuriw** [comment]
[wip-yuri-testing-2018-01-05-1727](https://trello.com/c/x53HxhYO/220-wip-yuri-testing-2018-01-05-1727)

**Comment by qrGitHub** [comment]
Hi @cbodley, is the test result private? I registered an account "qrCeph" in Trello, but still cannot see the test link.

**Comment by mattbenjamin** [comment]
@qrGitHub that Trello just tracks what Yuri has batched;  he'll merge if/when there's a successful result.

**Comment by qrGitHub** [comment]
@mattbenjamin ok, thanks.

**Comment by joscollin** [comment]
@qrGitHub 
http://pulpito.ceph.com/yuriw-2018-01-05_20:36:27-rgw-wip-yuri-testing-2018-01-05-1727-distro-basic-smithi/

**Comment by qrGitHub** [comment]
Thank you @joscollin

**Pull request merged**
