### PR TITLE
mgr/volumes/fs/operations/versions : fixing flake8 issues

### PR DESCRIPTION
**Pull request by Mithu22**
## Checklist
- [x] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

Fixes:  https://tracker.ceph.com/issues/51382
Signed-off-by: Maithreyi Rajagopalan <maithreyi220288@gmail.com>

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by ljflores** [comment]
@Mithu22 make sure to include a "Signed-off-by: FirstName LastName <email.gmail.com>" message in your commit. Also, I'd recommend moving the tracker url from the commit title to the comment, i.e. "Fixes: <tracker url>".

**Comment by Mithu22** [comment]
> @Mithu22 make sure to include a "Signed-off-by: FirstName LastName <email.gmail.com>" message in your commit. Also, I'd recommend moving the tracker url from the commit title to the comment, i.e. "Fixes: ".

Made amends!

**Review by varshar16 — CHANGES_REQUESTED** [review]
Please change the commit title to  and add the following to commit message:
```
Fixes: https://tracker.ceph.com/issues/51382
Signed-off-by: Maithreyi Rajagopalan maithreyi220288@gmail.com
```

Kindly drop changes to `src/pybind/mgr/volumes/fs/operations/versions/subvolume_attrs.py`. It is resolved by https://github.com/ceph/ceph/pull/43398. 

Otherwise the changes look good.

**Comment by Mithu22** [comment]
> Please change the commit title to `mgr/volumes/fs/operations/versions : fixing flake8 issues` and add the following to commit message:
> 
> ```
> Fixes: https://tracker.ceph.com/issues/51382
> Signed-off-by: Maithreyi Rajagopalan maithreyi220288@gmail.com
> ```
> 
> Kindly drop changes to `src/pybind/mgr/volumes/fs/operations/versions/subvolume_attrs.py`. It is resolved by #43398.
> 
> Otherwise the changes look good.

@varshar16 I have addressed these.

**Review by varshar16 — CHANGES_REQUESTED** [review]
The commit message still needs to be fixed. You can use `git commit --amend` to fix it. Please see https://github.com/ceph/ceph/blob/master/SubmittingPatches.rst

**Comment by Mithu22** [comment]
> The commit message still needs to be fixed. You can use `git commit --amend` to fix it. Please see https://github.com/ceph/ceph/blob/master/SubmittingPatches.rst

yeah i amended and pushed again!

**Comment by joscollin** [comment]
The first line of the commit message is still `Fixes: https://tracker.ceph.com/issues/51382`, which makes the commit heading. The correct format of the commit message is shown here https://github.com/ceph/ceph/blob/master/SubmittingPatches.rst#fixes-lines.

**Comment by ideepika** [comment]
@Mithu22 do you need any help?

**Pull request closed without merging**
