### PR TITLE
Mon:  delete 'auth print_key' command

### PR DESCRIPTION
**Pull request by HongweiBi**
'auth print-key' and 'auth print_key' are the same, so we delete one of the two.

Signed-off-by: Hongwei Bi <hwbi2008@gmail.com>

### CODE REVIEW

**Comment by dachary** [comment]
@HongweiBi I think we want to keep both for backward compatibility purposes. There may be scripts using **print_key** and such a change would force them to be updated. What do you think ?

**Comment by HongweiBi** [comment]
Thank you for your explanation. Other similar commands that you see  are  "osd crush rule list" and "osd crush rule ls", and so on. 
 I am considering this issue form the coming point of view. If we now get rid of these issues, there would be no ones in the future. This is my thought, thank you!

**Comment by dachary** [comment]
@HongweiBi say there is a script using **print_key** on a hammer cluster. The administrator of the hammer cluster decides to upgrade to infernalis. Then the script will stop working and the author of the script will have to fix it. I think that's what we want to avoid by keeping **print_key** around. Do you see my point ?

**Comment by HongweiBi** [comment]
OK, I see what you’re saying.

**Comment by dachary** [comment]
@HongweiBi I'll let you close this pull request unless you think there is more to it.

**Comment by HongweiBi** [comment]
closed already.

**Pull request closed without merging**
