### PR TITLE
ceph-volume: Pacific backports

### PR DESCRIPTION
**Pull request by guits**
batch of ceph-volume PRs:
https://github.com/ceph/ceph/pull/47169
https://github.com/ceph/ceph/pull/46893
https://github.com/ceph/ceph/pull/47170
https://github.com/ceph/ceph/pull/47361
https://github.com/ceph/ceph/pull/46375
https://github.com/ceph/ceph/pull/46992

### CODE REVIEW

**Comment by guits** [comment]
jenkins test ceph-volume tox

**Comment by guits** [comment]
jenkins test ceph-volume tox

**Comment by guits** [comment]
jenkins test ceph-volume tox

**Review by adk3798 — APPROVED** [review]

**Comment by guits** [comment]
jenkins test ceph-volume tox

**Comment by guits** [comment]
jenkins test ceph-volume tox

**Comment by guits** [comment]
jenkins test make check

**Comment by guits** [comment]
jenkins test api

**Comment by guits** [comment]
jenkins test make check

**Comment by guits** [comment]
jenkins test make check

**Comment by guits** [comment]
jenkins test ceph-volume tox

**Comment by guits** [comment]
https://pulpito.ceph.com/gabrioux-2022-08-03_18:01:01-orch:cephadm-wip-guits-testing-2022-08-03-1554-pacific-distro-default-smithi/
https://pulpito.ceph.com/gabrioux-2022-08-04_05:28:09-orch:cephadm-wip-guits-testing-2022-08-03-1554-pacific-distro-default-smithi/
https://pulpito.ceph.com/gabrioux-2022-08-04_06:49:43-orch:cephadm-wip-guits-testing-2022-08-03-1554-pacific-distro-default-smithi/

**Comment by guits** [comment]
jenkins test make check

**Comment by guits** [comment]
jenkins test api

**Comment by guits** [comment]
jenkins test ceph-volume tox

**Comment by guits** [comment]
jenkins test make check

**Comment by guits** [comment]
the 3 failures seen in teuthology tests are known issues for pacific

**Pull request merged**
