### PR TITLE
pacific: mgr/telemetry: check if 'ident' channel is active; identify dashboard telemetry test

### PR DESCRIPTION
**Pull request by liewegas**
backports of #39429 and #39538

### CODE REVIEW

**Comment by yaarith** [comment]
perf-test is still running (started 2d 20h ago), and readthedocs check has the error "This build was terminated due to inactivity.".  Should we rerun these checks?

**Comment by liewegas** [comment]
retest this please

**Comment by yaarith** [comment]
```
The following tests FAILED:
	 10 - run-rbd-unit-tests-61.sh (Failed)
```

also, seems like perf-test wasn't restarted (still says it started 2 days ago).

**Comment by jdurgin** [comment]
don't worry about the perf test, it's not enforcing and wouldn't be impacted by this change. For the make check failure, I don't see it in the tracker yet - can you add a ticket with the crash? It's probably a race condition in the rbd unit tests.

**Comment by yaarith** [comment]
@jdurgin: thanks!
https://tracker.ceph.com/issues/49558

**Comment by liewegas** [comment]
jenkins test make check

**Pull request merged**
