### PR TITLE
ceph-monstore-tool: use a large enough paxos/{first,last}_committed

### PR DESCRIPTION
**Pull request by tchaikov**
set monitor/cluster_fingerprint for the newly created monstore,
otherwise, the leader will create a new paxos proposal and there is
chance that the quorum will accept it.

when the quorum is recovering, the leader will collect the paxos
transactions from peons. if the quorum accept the proposal for setting
the fingerprint, the peon will update the monitor with the paxos
transaction with a newer "last_committed" than the one created using
update_paxos() in ceph_monstore_tool.cc. the latter "last_committed" is
always 0.

so, to avoid this extra paxos proposal obsoleting the "rebuilding" paxos
transaction, we set "monitor/cluster_fingerprint" when rebuilding the
monstore.

Fixes: http://tracker.ceph.com/issues/38219
Signed-off-by: Kefu Chai <kchai@redhat.com>

- [x] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by neha-ojha** [comment]
retest this please

**Comment by tchaikov** [comment]
http://pulpito.ceph.com/kchai-2019-04-09_16:42:22-rados-wip-38219-distro-basic-smithi/

**Comment by tchaikov** [comment]
http://pulpito.ceph.com/kchai-2019-04-11_12:48:09-rados-wip-38219-distro-basic-mira/

**Comment by tchaikov** [comment]
the tests still fail like a hell..

**Comment by jdurgin** [comment]
unstale

**Comment by ideepika** [comment]
jenkins test make check

**Comment by ideepika** [comment]
@tchaikov would it be possible to get this PR in nautilus seeing this issue pops up every few months in teuthology: https://tracker.ceph.com/issues/38219

**Comment by ideepika** [comment]
jenkins test make check

**Comment by ideepika** [comment]
jenkins test make check arm64

**Comment by ideepika** [comment]
jenkins retest this please

**Comment by tchaikov** [comment]
@ideepika will revisit this pr by the end of this week.

**Comment by tchaikov** [comment]
changelog

- rebased against master

**Comment by tchaikov** [comment]
being tested at https://pulpito.ceph.com/kchai-2021-06-10_04:50:42-rados:singleton-wip-38219-kefu-distro-basic-smithi/

**Comment by ideepika** [comment]
> @ideepika will revisit this pr by the end of this week.

@tchaikov sure thanks, checked with Josh, it might be okay to skip backport to nautilus.

**Comment by tchaikov** [comment]
https://pulpito.ceph.com/kchai-2021-06-10_15:05:32-rados:singleton-wip-38219-kefu-distro-basic-smithi/

**Comment by tchaikov** [comment]
changelog

- use bash lexer to render bash code in `doc/rados/troubleshooting`
- add a couple cleanups using the `make_scope_guard()` helper
- tolerate the `EACCES` in the 5-second window after the quorum is formed

@neha-ojha could you take another look?

**Comment by neha-ojha** [comment]
> changelog
> 
> * use bash lexer to render bash code in `doc/rados/troubleshooting`
> * add a couple cleanups using the `make_scope_guard()` helper
> * tolerate the `EACCES` in the 5-second window after the quorum is formed
> 
> @neha-ojha could you take another look?

@tchaikov sure, will take a look at it tomorrow

**Review by neha-ojha — COMMENTED** [review]
@tchaikov a couple of questions 1. do you understand why https://tracker.ceph.com/issues/38219 is not seen in releases after nautilus? 2. how far should we backport this patch? overall, this change makes sense to me

**Comment by tchaikov** [comment]
> @tchaikov a couple of questions 
> 1. do you understand why https://tracker.ceph.com/issues/38219 is not seen in releases after nautilus? 

@neha-ojha , thank you for reviewing the changes. yes, the frequency of the failures is much lower in recent releases. but it still surfaces occasionally. i checked `mon/Monitor.cc`, seems there are no changes after nautilus in the "fingerprint" related logic. so i am not able to explain why it's less reproducible after nautilus =( 

> 2. how far should we backport this patch? overall, this change makes sense to me

as far as possible, i'd say. even back to nautilus.

**Pull request merged**
