### PR TITLE
mgr: enable pg_autoscale by default on new clusters

### PR DESCRIPTION
**Pull request by liewegas**
Alternatively, we could put pg_autoscaler in the always_on modules for octopus... not sure which is better?

### CODE REVIEW

**Comment by liewegas** [comment]
@neha-ojha @jdurgin The issue with this approach is that upgraded clusters will still need to ``ceph mgr module enable pg_autoscaler``.  OTOH, it also means you can turn it all off easily (vs setting ``pg_autoscale_mode=off`` on every pool).  WDYT?

**Comment by neha-ojha** [comment]
> @neha-ojha @jdurgin The issue with this approach is that upgraded clusters will still need to `ceph mgr module enable pg_autoscaler`. OTOH, it also means you can turn it all off easily (vs setting `pg_autoscale_mode=off` on every pool). WDYT?

this approach sounds reasonable to me

**Comment by liewegas** [comment]
> sounds like a good approach to me too. I guess we're waiting for luminous clients to be old enough to turn on the balancer by default?

There's no issue with clients.  It's just a question of whether we think it's stable and want it on all the time.

**Comment by jdurgin** [comment]
On 7/16/19 9:39 AM, Sage Weil wrote:
>     sounds like a good approach to me too. I guess we're waiting for
>     luminous clients to be old enough to turn on the balancer by default?
> 
> There's no issue with clients. It's just a question of whether we think 
> it's stable and want it on all the time.

I thought you'd wanted to wait until we could enable upmap mode by 
default, requiring luminous clients

**Comment by liewegas** [comment]
Ah--two different things.  The upmap mode is for the balancer.  That module is already always_on, although you still have to ``ceph balancer on`` to turn it on.  This PR is about the pg_autoscaler, which has dependencies with clients.

**Pull request closed without merging**
