### PR TITLE
nautilus: mgr/pg_autoscaler: default to pg_num[_min] = 32

### PR DESCRIPTION
**Pull request by smithfarm**
backport tracker: https://tracker.ceph.com/issues/43819

---

NOTE: follow-on backport for https://github.com/ceph/ceph/pull/32069#issuecomment-577275657

---

backport of https://github.com/ceph/ceph/pull/32788
parent tracker: https://tracker.ceph.com/issues/43757

this backport was staged using ceph-backport.sh version 15.0.0.6950
find the latest version at https://github.com/ceph/ceph/blob/master/src/script/ceph-backport.sh

### CODE REVIEW

**Comment by smithfarm** [comment]
@neha-ojha I have a note that this fixes an incomplete backport that found its way into 14.2.5 - can you confirm/deny?

**Comment by neha-ojha** [comment]
> @neha-ojha I have a note that this fixes an incomplete backport that got merged prematurely - can you confirm/deny?
> 
> UPDATE: Ah, yes, here it is -> [#32069 (comment)](https://github.com/ceph/ceph/pull/32069#issuecomment-577275657)

@smithfarm It is not a matter of incomplete backport. The previous PR(https://github.com/ceph/ceph/pull/32069) becomes irrelevant with this one. This is further increasing the value of the same config.

**Comment by alfonsomthd** [comment]
jenkins test dashboard backend

**Comment by alfonsomthd** [comment]
jenkins test dashboard

**Comment by alfonsomthd** [comment]
jenkins test dashboard

**Comment by callithea** [comment]
The dashboard backend API tests failed with:
```
2020-01-29 09:28:08,571.571 INFO:__main__:ERROR: setUpClass (tasks.mgr.dashboard.test_rbd_mirroring.RbdMirroringTest)
2020-01-29 09:28:08,571.571 INFO:__main__:----------------------------------------------------------------------
2020-01-29 09:28:08,571.571 INFO:__main__:Traceback (most recent call last):
2020-01-29 09:28:08,571.571 INFO:__main__:  File "/home/jenkins-build/build/workspace/ceph-dashboard-pr-backend/qa/tasks/mgr/dashboard/test_rbd_mirroring.py", line 69, in setUpClass
2020-01-29 09:28:08,571.571 INFO:__main__:    super(RbdMirroringTest, cls).setUpClass()
2020-01-29 09:28:08,571.571 INFO:__main__:  File "/home/jenkins-build/build/workspace/ceph-dashboard-pr-backend/qa/tasks/mgr/dashboard/helper.py", line 115, in setUpClass
2020-01-29 09:28:08,571.571 INFO:__main__:    cls._base_uri = cls._get_uri("dashboard").rstrip('/')
2020-01-29 09:28:08,571.571 INFO:__main__:  File "/home/jenkins-build/build/workspace/ceph-dashboard-pr-backend/qa/tasks/mgr/mgr_test_case.py", line 158, in _get_uri
2020-01-29 09:28:08,571.571 INFO:__main__:    cls.wait_until_true(lambda: _get_or_none() is not None, 30)
2020-01-29 09:28:08,571.571 INFO:__main__:  File "/home/jenkins-build/build/workspace/ceph-dashboard-pr-backend/qa/tasks/ceph_test_case.py", line 164, in wait_until_true
2020-01-29 09:28:08,571.571 INFO:__main__:    raise RuntimeError("Timed out after {0}s".format(elapsed))
2020-01-29 09:28:08,572.572 INFO:__main__:RuntimeError: Timed out after 30s
2020-01-29 09:28:08,572.572 INFO:__main__:
2020-01-29 09:28:08,572.572 INFO:__main__:----------------------------------------------------------------------
2020-01-29 09:28:08,572.572 INFO:__main__:Ran 121 tests in 1189.048s
2020-01-29 09:28:08,572.572 INFO:__main__:
2020-01-29 09:28:08,572.572 INFO:__main__:FAILED (errors=1)
2020-01-29 09:28:08,572.572 INFO:__main__:
2020-01-29 09:28:08,572.572 INFO:__main__:======================================================================
2020-01-29 09:28:08,572.572 INFO:__main__:ERROR: setUpClass (tasks.mgr.dashboard.test_rbd_mirroring.RbdMirroringTest)
2020-01-29 09:28:08,572.572 INFO:__main__:----------------------------------------------------------------------
2020-01-29 09:28:08,572.572 INFO:__main__:Traceback (most recent call last):
2020-01-29 09:28:08,572.572 INFO:__main__:  File "/home/jenkins-build/build/workspace/ceph-dashboard-pr-backend/qa/tasks/mgr/dashboard/test_rbd_mirroring.py", line 69, in setUpClass
2020-01-29 09:28:08,572.572 INFO:__main__:    super(RbdMirroringTest, cls).setUpClass()
2020-01-29 09:28:08,572.572 INFO:__main__:  File "/home/jenkins-build/build/workspace/ceph-dashboard-pr-backend/qa/tasks/mgr/dashboard/helper.py", line 115, in setUpClass
2020-01-29 09:28:08,573.573 INFO:__main__:    cls._base_uri = cls._get_uri("dashboard").rstrip('/')
2020-01-29 09:28:08,573.573 INFO:__main__:  File "/home/jenkins-build/build/workspace/ceph-dashboard-pr-backend/qa/tasks/mgr/mgr_test_case.py", line 158, in _get_uri
2020-01-29 09:28:08,573.573 INFO:__main__:    cls.wait_until_true(lambda: _get_or_none() is not None, 30)
2020-01-29 09:28:08,573.573 INFO:__main__:  File "/home/jenkins-build/build/workspace/ceph-dashboard-pr-backend/qa/tasks/ceph_test_case.py", line 164, in wait_until_true
2020-01-29 09:28:08,573.573 INFO:__main__:    raise RuntimeError("Timed out after {0}s".format(elapsed))
2020-01-29 09:28:08,573.573 INFO:__main__:RuntimeError: Timed out after 30s
```

**Comment by callithea** [comment]
jenkins test dashboard backend

**Comment by yuriw** [comment]
[wip-yuri-testing-2020-02-08-1638-nautilus](https://trello.com/c/WGSzqecu/820-wip-yuri-testing-2020-02-08-1638-nautilus)

**Pull request merged**
