### PR TITLE
cephadm: change loki/promtail default image tags

### PR DESCRIPTION
**Pull request by guits**
This commit changes the default images for both loki and promtail
containers.
Also, to allow this update we need to update the configuration of loki
in order to add a new storage schema configuration:

```
    - from: 2024-05-03
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h
```

This is because 3.0.0 uses new structured metadata.

See [1][2].

[1] https://grafana.com/docs/loki/latest/operations/storage/schema/
[2] https://grafana.com/docs/loki/latest/get-started/labels/structured-metadata/#when-to-use-structured-metadata

Fixes: https://tracker.ceph.com/issues/65784

Signed-off-by: Guillaume Abrioux <gabrioux@ibm.com>

### CODE REVIEW

**Comment by guits** [comment]
@aaSharma14 FYI

**Comment by guits** [comment]
Hey @aaSharma14 ,

I took a look at this, 3.0.0 uses new schema v13 with new structured metadata, it implies migrating from BoltDB with v11 schema to tsdb with v13 schema.
Correct me if I'm wrong but I think it means we would have to take care of backward compatibility by adding a new `schema_config` block.

We currently have:

```yaml
schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h
```

We would need to add something like following:

```yaml
schema_config:
  configs:
    - from: 20YY-MM-DD
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h
```

Another option is starting loki with `-validation.allow-structured-metadata=false` parameter, which is what I've done in this PR.

@aaSharma14 Let me know which approach would be best.

**Comment by guits** [comment]
jenkins test make check

**Comment by guits** [comment]
@adk3798 @aaSharma14 🙂

**Review by aaSharma14 — APPROVED** [review]

**Comment by guits** [comment]
https://pulpito.ceph.com/gabrioux-2024-05-14_05:57:55-orch:cephadm-wip-guits-testing-2024-05-13-1110-distro-default-smithi/

**Pull request merged**
