### PR TITLE
[DNM]BlueFS: Wip bluefs log compact

### PR DESCRIPTION
**Pull request by varadakari**
This patch contains sync and async bluefs log compaction and unit test cases to verify them. 
Will split them to multiple commits if the approach is okay and correct.

Signed-off-by: Sage Weil <sage@redhat.com>
Signed-off-by: Varada Kari <varada.kari@sandisk.com>

### CODE REVIEW

**Comment by varadakari** [comment]
Added few more commits and it passes make check except ceph-disk.

99% tests passed, 2 tests failed out of 145

Total Test time (real) = 2509.05 sec
The following tests FAILED:
         13 - run-tox-ceph-disk (Failed)
         14 - run-tox-ceph-detect-init (Failed)


ceph_test_objectstore is in progress.

**Comment by varadakari** [comment]
2016-07-27 15:46:56.963018 7f7a79336680  1 bluestore(store_test_temp_dir) fsck finish with 0 errors
[       OK ] ObjectStore/StoreTest.TooManyBlobsTest/2 (57769 ms)
[----------] 59 tests from ObjectStore/StoreTest (5161446 ms total)

[----------] Global test environment tear-down
[==========] 59 tests from 1 test case ran. (5161447 ms total)
[  PASSED  ] 59 tests.
2016-07-27 15:46:56.996000 7f7a79336680  0 lockdep stop

Passed all tests in ceph_test_objectstore

**Comment by varadakari** [comment]
Make test also completed sucessfully

**Comment by liewegas** [comment]
I fixed several small things and rebased.  See https://github.com/ceph/ceph/pull/10717

**Pull request closed without merging**
