### PR TITLE
ceph-backports: add redmine ticket's JSON to debug output

### PR DESCRIPTION
**Pull request by rishabh-d-dave**
## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [x] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Comment by rishabh-d-dave** [comment]
```
diff --git a/src/script/ceph-backport.sh b/src/script/ceph-backport.sh
index 4854edff8b3..877bb37df57 100755
--- a/src/script/ceph-backport.sh
+++ b/src/script/ceph-backport.sh
@@ -1580,7 +1580,7 @@ else
 fi

 debug "Looking up release/milestone of $redmine_url"
-milestone="$(echo "$remote_api_output" | jq -r '.issue.custom_fields[0].value')"
+milestone="$(echo "$remote_api_output" | jq -r '.issue.custom_fields[1].value')"
 if [ "$milestone" ] ; then
     debug "Release/milestone: $milestone"
 else
 ```

**Comment by batrick** [comment]
> This patch will be deleted in next push (due to rebase) -
> 
> ```
> diff --git a/src/script/ceph-backport.sh b/src/script/ceph-backport.sh
> index 4854edff8b3..877bb37df57 100755
> --- a/src/script/ceph-backport.sh
> +++ b/src/script/ceph-backport.sh
> @@ -1580,7 +1580,7 @@ else
>  fi
> 
>  debug "Looking up release/milestone of $redmine_url"
> -milestone="$(echo "$remote_api_output" | jq -r '.issue.custom_fields[0].value')"
> +milestone="$(echo "$remote_api_output" | jq -r '.issue.custom_fields[1].value')"
>  if [ "$milestone" ] ; then
>      debug "Release/milestone: $milestone"
>  else
> ```

What is this PR doing then?

Please see: https://github.com/ceph/ceph/commit/67956d065d322d497ba1d4a39ed6b7c8b7f963be

**Comment by rishabh-d-dave** [comment]
> > This patch will be deleted in next push (due to rebase) -
> > ```
> > diff --git a/src/script/ceph-backport.sh b/src/script/ceph-backport.sh
> > index 4854edff8b3..877bb37df57 100755
> > --- a/src/script/ceph-backport.sh
> > +++ b/src/script/ceph-backport.sh
> > @@ -1580,7 +1580,7 @@ else
> >  fi
> > 
> >  debug "Looking up release/milestone of $redmine_url"
> > -milestone="$(echo "$remote_api_output" | jq -r '.issue.custom_fields[0].value')"
> > +milestone="$(echo "$remote_api_output" | jq -r '.issue.custom_fields[1].value')"
> >  if [ "$milestone" ] ; then
> >      debug "Release/milestone: $milestone"
> >  else
> > ```
> 
> What is this PR doing then?
> 
> Please see: [67956d0](https://github.com/ceph/ceph/commit/67956d065d322d497ba1d4a39ed6b7c8b7f963be)

I did. That's why I was fine with deletion of that patch due to rebase.

I've kept this PR open because there's one more patch on this PR that adds redmine ticket's JSON in debug logs. I found it very useful while debugging and writing the fix that was originally presented here. IMO, it would be helpful in future if merge this patch.

**Comment by rishabh-d-dave** [comment]
@batrick 
> > This patch will be deleted in next push (due to rebase) -
> 
> What is this PR doing then?
> 
> Please see: [67956d0](https://github.com/ceph/ceph/commit/67956d065d322d497ba1d4a39ed6b7c8b7f963be)

I did. That's why I was fine with deletion of that patch due to rebase.

I've kept this PR open because there's one more patch on this PR that adds redmine ticket's JSON in debug logs. I found it very useful while debugging and writing the fix that was originally presented here. IMO, it would be helpful in future if merge this patch.

**Review by batrick — APPROVED** [review]

**Comment by batrick** [comment]
jenkins test make check

**Comment by batrick** [comment]
jenkins test make check arm64

**Comment by rishabh-d-dave** [comment]
@batrick All CI jobs passed.

**Pull request merged**
