### PR TITLE
nautilus: ceph-volume/zfs: add the inventory command

### PR DESCRIPTION
**Pull request by smithfarm**
backport tracker: https://tracker.ceph.com/issues/42537

---

backport of https://github.com/ceph/ceph/pull/30995
parent tracker: https://tracker.ceph.com/issues/42498

this backport was staged using ceph-backport.sh version 15.0.0.6270
find the latest version at https://github.com/ceph/ceph/blob/master/src/script/ceph-backport.sh

### CODE REVIEW

**Comment by jan--f** [comment]
jenkins test make check

**Comment by jan--f** [comment]
jenkins test make check

**Comment by smithfarm** [comment]
@jan--f Can you trigger the c-v tests on this?

**Comment by jan--f** [comment]
jenkins test ceph-volume tox

**Pull request merged**
