### PR TITLE
ajdust mstart and mstop script to run with cmake build

### PR DESCRIPTION
**Pull request by oritwas**
Signed-off-by: Orit Wasserman <owasserm@redhat.com>

### CODE REVIEW

**Comment by yehudasa** [comment]
@oritwas what if we need to run everything from a different directory (not from the build directory). Maybe we should add some variable to allow specifying where the build directory is?

**Comment by liewegas** [comment]
@oritwas ping

**Comment by yehudasa** [comment]
@cbodley can you take a look at this one, see if it works for you?

**Comment by cbodley** [comment]
@yehudasa I've been running with this patch locally since @oritwas first pushed it :+1:

**Pull request merged**
