### PR TITLE
nautilus: pybind: volume_client handle purge of directory names encoded in utf-8

### PR DESCRIPTION
**Pull request by josecastroleon**
https://tracker.ceph.com/issues/45997

### CODE REVIEW

**Comment by smithfarm** [comment]
@josecastroleon We don't open backport PRs until the master PR (https://github.com/ceph/ceph/pull/35571 in this case, right?) is merged. And the backport should be done according to the cherry-picking rules [1] (tl;dr - `git cherry-pick -x` from commits that are in master).

Feel free to reopen this (or just open a new one using the backport script) once you have grokked the above ;-)

[1] https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst

**Comment by batrick** [comment]
@smithfarm @tchaikov requested the PR author retarget this to nautilus as we don't want the change in master.

https://github.com/ceph/ceph/pull/35571#discussion_r471233281

**Comment by batrick** [comment]
@josecastroleon sorry this got lost.

**Comment by smithfarm** [comment]
jenkins test make check

**Comment by tchaikov** [comment]
> @josecastroleon We don't open backport PRs until the master PR (#35571 in this case, right?) is merged. And the backport should be done according to the cherry-picking rules [1] (tl;dr - `git cherry-pick -x` from commits that are in master).
> 
> Feel free to reopen this (or just open a new one using the backport script) once you have grokked the above ;-)
> 
> [1] https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst

yes,  this change should target nautilus. as master is now python3 only.

@josecastroleon could you explain the reason why this change is not cherry-picked from master in the commit message, as this change is an exception ? something like

> this change is not cherry-picked from master, because master has dropped python2 support. and this change is to print the path of "unicode" type in python2

**Comment by ajarr** [comment]
@yuriw I've fixed the bug in this PR. Please include this PR in your next round of nautilus testing.

**Comment by batrick** [comment]
jenkins test api

**Review by ajarr — APPROVED** [review]
@yuriw, this PR is good to be merged.

**Comment by ajarr** [comment]
jenkins test make check

**Pull request merged**
