### PR TITLE
mimic: mgr/crash: fix python3 invalid syntax problems

### PR DESCRIPTION
**Pull request by liewegas**
Signed-off-by: Ricardo Dias <rdias@suse.com>
(cherry picked from commit bcf0f4df2db8b51c58e5ca4d411d05e2a4d081ab)

### CODE REVIEW

**Comment by smithfarm** [comment]
jenkins test docs

**Comment by smithfarm** [comment]
jenkins test docs

**Comment by yuriw** [comment]
[wip-yuri6-testing-2019-07-23-2000-mimic](https://trello.com/c/PkgNbUWw/673-wip-yuri6-testing-2019-07-23-2000-mimic)

**Comment by smithfarm** [comment]
jenkins test docs

**Pull request merged**
