### PR TITLE
mimic: qa: Fix issues in vstart runner

### PR DESCRIPTION
**Pull request by votdev**
Add missing timeout parameter to LocalRemote::run() and LocalCephManager::admin_socket() method

Fixes: https://tracker.ceph.com/issues/40054

cherry picked from commit 00e3022710dc49f72005ef2e34efea10f279bfb3
partial manual backport of 8620c4caf55d3ee6424a8f83ab3f3934a705be5f (partly because the origin patch contains changes that i was not affected from and i don't know if they are needed in Mimic and do not break something).

Signed-off-by: Volker Theile <vtheile@suse.com>

- [x] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by smithfarm** [comment]
@votdev Can you edit the commit message (using `git commit --amend`) so it explains why this backport cannot be implemented as a cherry-pick from `master` or `nautilus`?

**Comment by smithfarm** [comment]
One option is to:

1. find out which commit fixed the issue in master
2. append to commit message: `partial manual backport of $SHA1`

**Comment by smithfarm** [comment]
jenkins test make check

**Comment by smithfarm** [comment]
@votdev I'm confused by the commit message now. It says: 

```
cherry picked from commit 00e3022
partial manual backport of 8620c4c
```

Is this commit a cherry-pick of 00e3022 or a partial manual backport of 8620c4c, or both?

**Comment by votdev** [comment]
> @votdev I'm confused by the commit message now. It says:
> 
> ```
> cherry picked from commit 00e3022
> partial manual backport of 8620c4c
> ```
> 
> Is this commit a cherry-pick of [00e3022](https://github.com/ceph/ceph/commit/00e3022710dc49f72005ef2e34efea10f279bfb3) or a partial manual backport of [8620c4c](https://github.com/ceph/ceph/commit/8620c4caf55d3ee6424a8f83ab3f3934a705be5f), or both?

It's both.

**Comment by votdev** [comment]
This PR is needed by https://github.com/ceph/ceph/pull/28210, so please review to be able to process the mentioned PR.

**Comment by yuriw** [comment]
[wip-yuri2-testing-2019-07-11-1516-mimic](https://trello.com/c/DNupOYCk/664-wip-yuri2-testing-2019-07-11-1516-mimic)

**Pull request merged**
