### PR TITLE
crushtool: process commands in a sensible order

### PR DESCRIPTION
**Pull request by liewegas**

### CODE REVIEW

**Comment by liewegas** [comment]
i keep stumbling over this while working with the buggy straw code and tunable.  the way the current tool processes things is super nonintuitive.

**Comment by liewegas** [comment]
passed my wip-sage-testing run, just need an ack.. perhaps from @dachary?

**Comment by dachary** [comment]
The code in https://github.com/ceph/ceph/commit/04812b8c5220be822aa8022059f5f59e34385ef2 was moved and not modified. The **test** part is placed before the **output** instead of after. The **mutate** part that was intermingled with the **display** part is placed before instead. The **input** part is left as is.

**Comment by dachary** [comment]
I would like to keep https://github.com/ceph/ceph/commit/5a3514f74f3f8c7aabde94025ee4a309221049e4 despite the pollution because it helps when using the tool manually. I don't feel strongly about it though and I'm not opposed to removing it.

**Comment by dachary** [comment]
> I would like to keep 5a3514f despite the pollution because it helps when using the tool manually. I don't feel strongly about it though and I'm not opposed to removing it.

Nevermind, adding --tree does the same, got it.

**Comment by dachary** [comment]
The code at https://github.com/ceph/ceph/commit/5a3514f74f3f8c7aabde94025ee4a309221049e4 can probably be removed instead of if(0). You inspired me to re-organize the help in the same way and I find it more readable: https://github.com/ceph/ceph/pull/3778

:+1:

**Comment by liewegas** [comment]
dropped the if (0) bit

**Pull request merged**
