### PR TITLE
[DNM] mgr/nfs: disallow non-existent paths when creating export

### PR DESCRIPTION
**Pull request by vshankar**
Fixes: https://tracker.ceph.com/issues/58228

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by vshankar** [comment]
@dparmar18 looks like this is going fine. You probably know if make check is bound to fail early on?

**Comment by dparmar18** [comment]
I had tried it earlier but didnt work i.e. `super().__init__(mgr)` instead instantiating `CephfsClient`

**Comment by dparmar18** [comment]
ran this locally:

```
branch 'wip-58228-dry-run' set up to track 'vshankar/wip-58228-dry-run'.
Switched to a new branch 'wip-58228-dry-run'
dparmar:mgr$ ../../script/run_tox.sh --tox-envs=py3 mgr
Requirement already satisfied: tox in /home/dparmar/CephRepo1/ceph/build/mgr/lib/python3.10/site-packages (4.4.7)
Requirement already satisfied: pluggy>=1 in /home/dparmar/CephRepo1/ceph/build/mgr/lib/python3.10/site-packages (from tox) (1.0.0)
Requirement already satisfied: colorama>=0.4.6 in /home/dparmar/CephRepo1/ceph/build/mgr/lib/python3.10/site-packages (from tox) (0.4.6)
Requirement already satisfied: platformdirs>=2.6.2 in /home/dparmar/CephRepo1/ceph/build/mgr/lib/python3.10/site-packages (from tox) (3.1.1)
Requirement already satisfied: pyproject-api>=1.5 in /home/dparmar/CephRepo1/ceph/build/mgr/lib/python3.10/site-packages (from tox) (1.5.1)
Requirement already satisfied: virtualenv>=20.17.1 in /home/dparmar/CephRepo1/ceph/build/mgr/lib/python3.10/site-packages (from tox) (20.21.0)
Requirement already satisfied: cachetools>=5.3 in /home/dparmar/CephRepo1/ceph/build/mgr/lib/python3.10/site-packages (from tox) (5.3.0)
Requirement already satisfied: tomli>=2.0.1 in /home/dparmar/CephRepo1/ceph/build/mgr/lib/python3.10/site-packages (from tox) (2.0.1)
Requirement already satisfied: packaging>=23 in /home/dparmar/CephRepo1/ceph/build/mgr/lib/python3.10/site-packages (from tox) (23.0)
Requirement already satisfied: chardet>=5.1 in /home/dparmar/CephRepo1/ceph/build/mgr/lib/python3.10/site-packages (from tox) (5.1.0)
Requirement already satisfied: filelock>=3.9 in /home/dparmar/CephRepo1/ceph/build/mgr/lib/python3.10/site-packages (from tox) (3.10.0)
Requirement already satisfied: distlib<1,>=0.3.6 in /home/dparmar/CephRepo1/ceph/build/mgr/lib/python3.10/site-packages (from virtualenv>=20.17.1->tox) (0.3.6)
py3: commands[0]> pytest --doctest-modules
==================================================================== test session starts =====================================================================
platform linux -- Python 3.10.6, pytest-7.2.2, pluggy-1.0.0
cachedir: .tox/py3/.pytest_cache
rootdir: /home/dparmar/CephRepo1/ceph/src/pybind/mgr, configfile: tox.ini
plugins: pyfakefs-5.1.0, requests-mock-1.10.0, cov-2.7.1
collected 1322 items                                                                                                                                         

mgr_module.py .                                                                                                                                        [  0%]
mgr_util.py ......                                                                                                                                     [  0%]
cephadm/upgrade.py .                                                                                                                                   [  0%]
cephadm/tests/test_autotune.py ....                                                                                                                    [  0%]
cephadm/tests/test_cephadm.py .......................................................................................................................  [  9%]
cephadm/tests/test_completion.py ............                                                                                                          [ 10%]
cephadm/tests/test_configchecks.py .......................                                                                                             [ 12%]
cephadm/tests/test_facts.py ..                                                                                                                         [ 12%]
cephadm/tests/test_migration.py ........                                                                                                               [ 13%]
cephadm/tests/test_osd_removal.py ..................................................                                                                   [ 17%]
cephadm/tests/test_scheduling.py ..................................................................................................................... [ 25%]
...................................................................................................................................................... [ 37%]
...................................................................................................................................................... [ 48%]
...................................................................................................................................................... [ 59%]
...................................................................................................................................................... [ 71%]
....................................................                                                                                                   [ 75%]
cephadm/tests/test_service_discovery.py ......                                                                                                         [ 75%]
cephadm/tests/test_services.py ..................................                                                                                      [ 78%]
cephadm/tests/test_spec.py .........................................                                                                                   [ 81%]
cephadm/tests/test_ssh.py .s                                                                                                                           [ 81%]
cephadm/tests/test_template.py .                                                                                                                       [ 81%]
cephadm/tests/test_tuned_profiles.py ....                                                                                                              [ 81%]
cephadm/tests/test_upgrade.py .............................                                                                                            [ 84%]
cli_api/tests/test_cli_api.py .....                                                                                                                    [ 84%]
diskprediction_local/predictor.py .                                                                                                                    [ 84%]
insights/tests/test_health.py .........                                                                                                                [ 85%]
mds_autoscaler/tests/test_autoscaler.py .                                                                                                              [ 85%]
nfs/tests/test_nfs.py .......................F............                                                                                             [ 88%]
orchestrator/_interface.py ss.ss.                                                                                                                      [ 88%]
orchestrator/module.py .                                                                                                                               [ 88%]
orchestrator/tests/test_orchestrator.py ...........                                                                                                    [ 89%]
pg_autoscaler/tests/test_cal_final_pg_target.py .......                                                                                                [ 89%]
pg_autoscaler/tests/test_cal_ratio.py ..                                                                                                               [ 90%]
pg_autoscaler/tests/test_overlapping_roots.py ..                                                                                                       [ 90%]
progress/test_progress.py ..                                                                                                                           [ 90%]
prometheus/module.py .                                                                                                                                 [ 90%]
prometheus/test_module.py ......                                                                                                                       [ 90%]
rook/tests/test_placement.py ....                                                                                                                      [ 91%]
snap_schedule/tests/fs/test_schedule.py ..............................................                                                                 [ 94%]
snap_schedule/tests/fs/test_schedule_client.py ..                                                                                                      [ 94%]
telemetry/tests/test_telemetry.py ...                                                                                                                  [ 95%]
tests/test_mgr_util.py ......                                                                                                                          [ 95%]
tests/test_object_format.py .....................................................                                                                      [ 99%]
tests/test_tls.py ......                                                                                                                               [100%]

========================================================================== FAILURES ==========================================================================
_____________________________________________________________ TestNFS.test_create_export_cephfs ______________________________________________________________

self = <mgr_util.CephfsConnectionPool object at 0x7fef2c920730>, fs_name = 'myfs'

    def get_fs_handle(self, fs_name: str) -> "cephfs.LibCephFS":
        with self.lock:
            try:
                min_shared = 0
                shared_connection = None
                connections = self.connections.setdefault(fs_name, [])
>               logger.debug(f'[get] volume: ({fs_name}) connection: ({connections})')
E               TypeError: <lambda>() missing 2 required positional arguments: 'x' and 'y'

mgr_util.py:226: TypeError

During handling of the above exception, another exception occurred:

self = <nfs.export.ExportMgr object at 0x7fef2c9206d0>, addr = ['192.168.1.0/8']
kwargs = {'access_type': 'none', 'clients': [{'access_type': 'rw', 'addresses': ['192.168.1.0/8'], 'squash': 'root'}], 'cluster_id': 'foo', 'fs_name': 'myfs', ...}
clients = [{'access_type': 'rw', 'addresses': ['192.168.1.0/8'], 'squash': 'root'}], fsal_type = 'cephfs'

    def create_export(self, addr: Optional[List[str]] = None, **kwargs: Any) -> Dict[str, Any]:
        self._validate_cluster_id(kwargs['cluster_id'])
        # if addr(s) are provided, construct client list and adjust outer block
        clients = []
        if addr:
            clients = [{
                'addresses': addr,
                'access_type': 'ro' if kwargs['read_only'] else 'rw',
                'squash': kwargs['squash'],
            }]
            kwargs['squash'] = 'none'
        kwargs['clients'] = clients
    
        if clients:
            kwargs['access_type'] = "none"
        elif kwargs['read_only']:
            kwargs['access_type'] = "RO"
        else:
            kwargs['access_type'] = "RW"
    
        if kwargs['cluster_id'] not in self.exports:
            self.exports[kwargs['cluster_id']] = []
    
        try:
            fsal_type = kwargs.pop('fsal_type')
            if fsal_type == 'cephfs':
>               return self.create_cephfs_export(**kwargs)

nfs/export.py:406: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <nfs.export.ExportMgr object at 0x7fef2c9206d0>, fs_name = 'myfs', cluster_id = 'foo', pseudo_path = '/cephfs2', read_only = False, path = '/'
squash = 'none', access_type = 'none', clients = [{'access_type': 'rw', 'addresses': ['192.168.1.0/8'], 'squash': 'root'}], sectype = None

    def create_cephfs_export(self,
                             fs_name: str,
                             cluster_id: str,
                             pseudo_path: str,
                             read_only: bool,
                             path: str,
                             squash: str,
                             access_type: str,
                             clients: list = [],
                             sectype: Optional[List[str]] = None) -> Dict[str, Any]:
    
>       with open_filesystem(self, fs_name) as fs_handle:

nfs/export.py:667: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <contextlib._GeneratorContextManager object at 0x7fef0c40a5c0>

    def __enter__(self):
        # do not keep args and kwds alive unnecessarily
        # they are only needed for recreation, which is not possible anymore
        del self.args, self.kwds, self.func
        try:
>           return next(self.gen)

/home/dparmar/.pyenv/versions/3.10.6/lib/python3.10/contextlib.py:135: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

fsc = <nfs.export.ExportMgr object at 0x7fef2c9206d0>, fs_name = 'myfs'

    @contextlib.contextmanager
    def open_filesystem(fsc: CephfsClient, fs_name: str) -> Generator["cephfs.LibCephFS", None, None]:
        """
        Open a volume with shared access.
        This API is to be used as a context manager.
    
        :param fsc: cephfs client instance
        :param fs_name: fs name
        :return: yields a fs handle (ceph filesystem handle)
        """
>       fs_handle = fsc.connection_pool.get_fs_handle(fs_name)

mgr_util.py:346: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <mgr_util.CephfsConnectionPool object at 0x7fef2c920730>, fs_name = 'myfs'

    def get_fs_handle(self, fs_name: str) -> "cephfs.LibCephFS":
        with self.lock:
            try:
                min_shared = 0
                shared_connection = None
                connections = self.connections.setdefault(fs_name, [])
                logger.debug(f'[get] volume: ({fs_name}) connection: ({connections})')
                if connections:
                    min_shared = connections[0].ops_in_progress
                    shared_connection = connections[0]
                for connection in list(connections):
                    logger.debug(f'[get] connection: {connection} usage: {connection.ops_in_progress}')
                    if connection.ops_in_progress == 0:
                        if connection.is_connection_valid():
                            logger.debug(f'[get] connection ({connection}) can be reused')
                            return connection.get_fs_handle()
                        else:
                            # filesystem id changed beneath us (or the filesystem does not exist).
                            # this is possible if the filesystem got removed (and recreated with
                            # same name) via "ceph fs rm/new" mon command.
                            logger.warning(f'[get] filesystem id changed for volume ({fs_name}), disconnecting ({connection})')
                            # note -- this will mutate @connections too
                            self._del_connection(fs_name, connection)
                    else:
                        if connection.ops_in_progress < min_shared:
                            min_shared = connection.ops_in_progress
                            shared_connection = connection
                # when we end up here, there are no "free" connections. so either spin up a new
                # one or share it.
                if len(connections) < CephfsConnectionPool.MAX_CONCURRENT_CONNECTIONS:
                    logger.debug('[get] spawning new connection since no connection is unused and we still have room for more')
                    connection = CephfsConnectionPool.Connection(self.mgr, fs_name)
                    connection.connect()
                    self.connections[fs_name].append(connection)
                    return connection.get_fs_handle()
                else:
                    assert shared_connection is not None
                    logger.debug(f'[get] using shared connection ({shared_connection})')
                    return shared_connection.get_fs_handle()
>           except cephfs.Error as e:
E           TypeError: catching classes that do not inherit from BaseException is not allowed

mgr_util.py:259: TypeError

The above exception was the direct cause of the following exception:

self = <nfs.tests.test_nfs.TestNFS object at 0x7fef30bc03d0>

    def test_create_export_cephfs(self):
>       self._do_mock_test(self._do_test_create_export_cephfs)

nfs/tests/test_nfs.py:1039: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
nfs/tests/test_nfs.py:395: in _do_mock_test
    func(*args)
nfs/tests/test_nfs.py:1048: in _do_test_create_export_cephfs
    r = conf.create_export(
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <nfs.export.ExportMgr object at 0x7fef2c9206d0>, addr = ['192.168.1.0/8']
kwargs = {'access_type': 'none', 'clients': [{'access_type': 'rw', 'addresses': ['192.168.1.0/8'], 'squash': 'root'}], 'cluster_id': 'foo', 'fs_name': 'myfs', ...}
clients = [{'access_type': 'rw', 'addresses': ['192.168.1.0/8'], 'squash': 'root'}], fsal_type = 'cephfs'

    def create_export(self, addr: Optional[List[str]] = None, **kwargs: Any) -> Dict[str, Any]:
        self._validate_cluster_id(kwargs['cluster_id'])
        # if addr(s) are provided, construct client list and adjust outer block
        clients = []
        if addr:
            clients = [{
                'addresses': addr,
                'access_type': 'ro' if kwargs['read_only'] else 'rw',
                'squash': kwargs['squash'],
            }]
            kwargs['squash'] = 'none'
        kwargs['clients'] = clients
    
        if clients:
            kwargs['access_type'] = "none"
        elif kwargs['read_only']:
            kwargs['access_type'] = "RO"
        else:
            kwargs['access_type'] = "RW"
    
        if kwargs['cluster_id'] not in self.exports:
            self.exports[kwargs['cluster_id']] = []
    
        try:
            fsal_type = kwargs.pop('fsal_type')
            if fsal_type == 'cephfs':
                return self.create_cephfs_export(**kwargs)
            if fsal_type == 'rgw':
                return self.create_rgw_export(**kwargs)
            raise NotImplementedError()
        except Exception as e:
            log.exception(
                f"Failed to create {kwargs['pseudo_path']} export for {kwargs['cluster_id']}")
>           raise ErrorResponse.wrap(e)
E           object_format.ErrorResponse: catching classes that do not inherit from BaseException is not allowed

nfs/export.py:413: ErrorResponse
--------------------------------------------------------------------- Captured log call ----------------------------------------------------------------------
DEBUG    tests:mgr_module.py:1616 mon_command: 'config get' -> 0 in 0.000s
DEBUG    tests:mgr_module.py:1616 mon_command: 'config get' -> 0 in 0.000s
DEBUG    tests:mgr_module.py:1616 mon_command: 'config get' -> 0 in 0.000s
DEBUG    tests:mgr_module.py:1616 mon_command: 'config get' -> 0 in 0.000s
DEBUG    nfs.export:export.py:374 checking for 'foo' in known nfs clusters: {'foo'}
INFO     nfs.export:export.py:201 Begin export parsing
DEBUG    nfs.export:export.py:304 read export configuration from rados object .nfs/foo/export-1
DEBUG    nfs.export:export.py:304 read export configuration from rados object .nfs/foo/export-2
INFO     nfs.export:export.py:206 Exports parsed successfully dict_items([('foo', [<nfs.ganesha_conf.Export object at 0x7fef2c9211e0>, <nfs.ganesha_conf.Export object at 0x7fef2c13da80>])])
DEBUG    nfs.export:export.py:374 checking for 'foo' in known nfs clusters: {'foo'}
ERROR    nfs.export:export.py:411 Failed to create /cephfs2 export for foo
Traceback (most recent call last):
  File "/home/dparmar/CephRepo1/ceph/src/pybind/mgr/mgr_util.py", line 226, in get_fs_handle
    logger.debug(f'[get] volume: ({fs_name}) connection: ({connections})')
TypeError: <lambda>() missing 2 required positional arguments: 'x' and 'y'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dparmar/CephRepo1/ceph/src/pybind/mgr/nfs/export.py", line 406, in create_export
    return self.create_cephfs_export(**kwargs)
  File "/home/dparmar/CephRepo1/ceph/src/pybind/mgr/nfs/export.py", line 667, in create_cephfs_export
    with open_filesystem(self, fs_name) as fs_handle:
  File "/home/dparmar/.pyenv/versions/3.10.6/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/home/dparmar/CephRepo1/ceph/src/pybind/mgr/mgr_util.py", line 346, in open_filesystem
    fs_handle = fsc.connection_pool.get_fs_handle(fs_name)
  File "/home/dparmar/CephRepo1/ceph/src/pybind/mgr/mgr_util.py", line 259, in get_fs_handle
    except cephfs.Error as e:
TypeError: catching classes that do not inherit from BaseException is not allowed
====================================================================== warnings summary ======================================================================
.tox/py3/lib/python3.10/site-packages/pkg_resources/__init__.py:2804
  /home/dparmar/CephRepo1/ceph/src/pybind/mgr/.tox/py3/lib/python3.10/site-packages/pkg_resources/__init__.py:2804: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('google')`.
  Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
    declare_namespace(pkg)

.tox/py3/lib/python3.10/site-packages/pkg_resources/__init__.py:2804
  /home/dparmar/CephRepo1/ceph/src/pybind/mgr/.tox/py3/lib/python3.10/site-packages/pkg_resources/__init__.py:2804: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('zc')`.
  Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
    declare_namespace(pkg)

.tox/py3/lib/python3.10/site-packages/asyncssh/crypto/cipher.py:29
  /home/dparmar/CephRepo1/ceph/src/pybind/mgr/.tox/py3/lib/python3.10/site-packages/asyncssh/crypto/cipher.py:29: CryptographyDeprecationWarning: Blowfish has been deprecated
    from cryptography.hazmat.primitives.ciphers.algorithms import Blowfish, CAST5

.tox/py3/lib/python3.10/site-packages/asyncssh/crypto/cipher.py:29
  /home/dparmar/CephRepo1/ceph/src/pybind/mgr/.tox/py3/lib/python3.10/site-packages/asyncssh/crypto/cipher.py:29: CryptographyDeprecationWarning: CAST5 has been deprecated
    from cryptography.hazmat.primitives.ciphers.algorithms import Blowfish, CAST5

.tox/py3/lib/python3.10/site-packages/asyncssh/crypto/cipher.py:30
  /home/dparmar/CephRepo1/ceph/src/pybind/mgr/.tox/py3/lib/python3.10/site-packages/asyncssh/crypto/cipher.py:30: CryptographyDeprecationWarning: SEED has been deprecated
    from cryptography.hazmat.primitives.ciphers.algorithms import SEED, TripleDES

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
================================================================== short test summary info ===================================================================
FAILED nfs/tests/test_nfs.py::TestNFS::test_create_export_cephfs - object_format.ErrorResponse: catching classes that do not inherit from BaseException is not allowed
=================================================== 1 failed, 1316 passed, 5 skipped, 5 warnings in 58.47s ===================================================
task exception: <lambda>() missing 2 required positional arguments: 'x' and 'y'
Exception in thread Thread-3388:
Traceback (most recent call last):
  File "/home/dparmar/.pyenv/versions/3.10.6/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/home/dparmar/CephRepo1/ceph/src/pybind/mgr/mgr_util.py", line 81, in run
    self.function(*self.args, **self.kwargs)
  File "/home/dparmar/CephRepo1/ceph/src/pybind/mgr/mgr_util.py", line 212, in cleanup_connections
    logger.debug(f'fs_name ({fs_name}) connections ({connections})')
TypeError: <lambda>() missing 2 required positional arguments: 'x' and 'y'
^CROOT: [35544] KeyboardInterrupt - teardown started
Exception ignored in: <module 'threading' from '/home/dparmar/.pyenv/versions/3.10.6/lib/python3.10/threading.py'>
Traceback (most recent call last):
  File "/home/dparmar/.pyenv/versions/3.10.6/lib/python3.10/threading.py", line 1567, in _shutdown
ROOT: interrupt tox environment: py3
ROOT: requested interrupt of 35550 from 35544, activate in 0.00
ROOT: send signal SIGINT(2) to 35550 from 35544 with timeout 0.30
    lock.acquire()
KeyboardInterrupt: 
Exception ignored in atexit callback: <function shutdown at 0x7fef5da00dc0>
Traceback (most recent call last):
  File "/home/dparmar/.pyenv/versions/3.10.6/lib/python3.10/logging/__init__.py", line 2183, in shutdown
    h.close()
  File "/home/dparmar/.pyenv/versions/3.10.6/lib/python3.10/logging/__init__.py", line 998, in close
    _acquireLock()
  File "/home/dparmar/.pyenv/versions/3.10.6/lib/python3.10/logging/__init__.py", line 219, in _acquireLock
    def _acquireLock():
KeyboardInterrupt: 
ROOT: send signal SIGTERM(15) to 35550 from 35544 with timeout 0.20
py3: exit -15 (107.72 seconds) /home/dparmar/CephRepo1/ceph/src/pybind/mgr> pytest --doctest-modules pid=35550
ROOT: interrupt finished with success
  py3: FAIL code -15 (107.76=setup[0.04]+cmd[107.72] seconds)
  evaluation failed :( (107.87 seconds)
dparmar:mgr$ 
```

The test failure is because fs is not monkey patched but thats not an issue, but it still halted and required manual interruption, you can see the exact same traceback

**Comment by dparmar18** [comment]
make check also seems to be stuck https://jenkins.ceph.com/job/ceph-pull-requests/112569/console, running close to 2 hrs, it would timeout at 3hr

**Comment by vshankar** [comment]
Thx for running the locally. The nfs unit tests create an instance of ExportMgr. Other unit tests (mgr modules) do not does anything like that.

**Comment by vshankar** [comment]
I think we'll have to mock CephfsClient to get this work. An alternate approach would be to not instantiate CephfsClient in ExportMgr.

**Comment by dparmar18** [comment]
> I think we'll have to mock CephfsClient to get this work. An alternate approach would be to not instantiate CephfsClient in ExportMgr.

I thought of not instantiating it and instead call it in a helper but that would mean having new CephfsClient instance at every cephfs export creation

**Comment by vshankar** [comment]
@dparmar18 no wonder the file path check wasn't done in mgr/nfs ;P

**Comment by vshankar** [comment]
@dparmar18 Could you share your changes for mocking CephfsClient?

**Comment by dparmar18** [comment]
> @dparmar18 Could you share your changes for mocking CephfsClient?

https://github.com/ceph/ceph/pull/49460/commits/88f1a59a58b6c7226dbc5d4795f16ee6b6177c40

**Comment by dparmar18** [comment]
im thinking if somehow we can mock `nfs_mod = Module('nfs', '', '')` then it would solve all the issues

**Pull request closed without merging**
