### PR TITLE
luminous: mgr/dashboard_v2: #1 - Initial submission of a web-based management UI (replacement for the existing dashboard)

### PR DESCRIPTION
**Pull request by epuertat**
Source-PR: #20103
Fixes: http://tracker.ceph.com/issues/24788
Fixes: http://tracker.ceph.com/issues/34318

**Conflict-solving summary:**
-  `ceph.spec.in`:
    - Add make-check distro-conditional Python `BuildRequires`: CherryPy, tox, coverage and bcrypt.
    - Add ceph-mgr package Python `Requires`: bcrypt
- `install-deps.sh`: Add `ensure_min_npm_version` method
- `qa/tasks/mgr/mgr_test_case.py`: Pick `setUpClass` method from remote
- `qa/tasks/mgr/test_prometheus.py`: Delete
- `src/pybind/CMakeLists.txt`: Add `add_subdirectory(mgr)`
- `src/vstart.sh`: Bring `DASH_V2_URLS` and dashboard_v2 config setting.

**Ad-hoc additions**:
- Remove `--use-wheel` from dashboard `CMakeLists.txt` (#21159): required for `make check`.
- Disable `RBD_FEATURE_OPERATIONS`.
- Update node to 6.0.0 (as a dependency failed).
- Disable tslint error in password-button component.

**Note for reviewers**:
Given the size of this review, in order to ease the review process, please just focus on the manually merged files:
- [ceph.spec.in](https://github.com/ceph/ceph/pull/23271/files#diff-ca40628478ff1274b73dcd40c384e7f0)
- [debian/rules](https://github.com/ceph/ceph/pull/23271/files#diff-d2b2229a977ef7e99780f2207c29b503)
- [install-deps.sh](https://github.com/ceph/ceph/pull/23271/files#diff-47a21b3706c13e08943e223c12323aa1)
- [src/vstart.sh](https://github.com/ceph/ceph/pull/23271/files#diff-7b2752174570bb104c55d6bce2c9ab5b)

**Changes required for this PR**:
- #23479: mgr/dashboard: add configuration setting browser

### CODE REVIEW

**Comment by epuertat** [comment]
[`epuertat-2018-08-08_13:49:45-rados:mgr-wip-epuertat-testing-dashboard_v2-PR23271-distro-basic-mira`](http://pulpito.ceph.com/epuertat-2018-08-08_13:49:45-rados:mgr-wip-epuertat-testing-dashboard_v2-PR23271-distro-basic-mira/)
**Passed**: 16/20 (4 failed ones seem to be a flappy dashboard test)

**ongoing**: [`epuertat-2018-08-09_09:49:49-rados-wip-epuertat-testing-dashboard_v2-PR23271-distro-basic-smithi`](http://pulpito.ceph.com/epuertat-2018-08-09_09:49:49-rados-wip-epuertat-testing-dashboard_v2-PR23271-distro-basic-smithi/) [[reference run in original PR](http://pulpito.ceph.com/rdias-2018-03-01_14:49:11-rados-wip-mgr-dashboard_v2-distro-basic-smithi/): 199/205]

**Comment by epuertat** [comment]
Thank you very much @ricardoasmarques for doing the vstart testing. I blindly relied on the automated testing without checking the current coverage. My bad! This error is due to a commit I initially merged in luminous (https://github.com/ceph/ceph/pull/23235) but had soon to revert, as it caused ceph-mgr to crash. I'll amend this by adding a new commit to this PR, so rados handle is looked up in the derived class, and not in the parent one, as it happens in master.

**Comment by epuertat** [comment]
Thanks @ricardoasmarques. Just fixed the error: dashboard_v2 uses `logger` instead of `log`. I've also moved also the lazy `import rados` from the rados property to the top of the module (following the same approach as in master), as I don't want to introduce different behaviours between Luminous' dashboard_v2 vs. master's.

I'll now run QA rados:mgr suite again.

**Comment by epuertat** [comment]
jenkins rebuild docs

**Comment by epuertat** [comment]
jenkins test docs

**Comment by tchaikov** [comment]
@epuertat the change looks sane in general. only one concern, `WITH_MGR_DASHBOARD_V2_FRONTEND` is OFF in both `ceph.spec.in` and `debian/rules`. if dashboard is always disabled. how is the end user using the pre-built packages prepared by us supposed to use this feature?

**Comment by LenzGr** [comment]
>  if dashboard is always disabled. how is the end user using the pre-built packages prepared by us supposed to use this feature?

The Dashboard frontend code is usually built when the source tarball is created. Therefore there is no need to repeat that process during the packaging of the RPM and DEB packages, the previously built frontend assets are simply copied from the tarball into the packages.

**Pull request closed without merging**
