### PR TITLE
qa: add basic Ceph on Windows integration test

### PR DESCRIPTION
**Pull request by ionutbalutoiu**
Due to lack of Windows support in the Teuthology, the test case adopts
the following workaround:

* Deploy baremetal machine with `ubuntu_latest.yaml` and
  configure it with libvirt KVM.
* Create a libvirt VM and provision it with Windows Server 2019, using
  the official ISO from Microsoft.
* Configure SSH in the Windows VM, and run the tests remotely via SSH.

The implementation of the test case consists of workunit scripts.

`qa/workunits/windows/test_rbd_wnbd.py` is the main Python script
to test Ceph on Windows basic functionality. This is executed in the
libvirt VM configured with Windows Server 2019.

Co-authored-by: Lucian Petrut <lpetrut@cloudbasesolutions.com>
Co-authored-by: Daniel Vincze <dvincze@cloudbasesolutions.com>

Signed-off-by: Ionut Balutoiu <ibalutoiu@cloudbasesolutions.com>

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [x] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [x] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by ionutbalutoiu** [comment]
jenkins test make check

**Comment by ionutbalutoiu** [comment]
jenkins test api

**Comment by ionutbalutoiu** [comment]
jenkins test make check

**Review by zmc — COMMENTED** [review]
This is a very nice approach; if we end up supporting Windows properly in teuthology, it should be easy to convert it to a task, if desired. The python code looks great. I am unqualified to review PowerShell, otherwise I'd add an approval.

**Comment by ionutbalutoiu** [comment]
> This is a very nice approach; if we end up supporting Windows properly in teuthology, it should be easy to convert it to a task, if desired. The python code looks great.

Thank-you, Zack! That was exactly my idea: Implement the workaround as nicely as possible, and allow the Python code to be easily ported to a Teuthology task, once the Windows support is properly added to Ceph Teuthology.

> I am unqualified to review PowerShell, otherwise I'd add an approval.

I am really confident in the PowerShell there, but it would be ideal if somebody else can take a look at it.

**Comment by ionutbalutoiu** [comment]
Also, this is my wip branch running the code from this pull request:
http://pulpito.front.sepia.ceph.com/?branch=wip-ionutbalutoiu-windows-tests

The last run is using exactly the code from here.

**Comment by djgalloway** [comment]
I don't know anyone qualified to review PowerShell but nothing jumps out at me.  I'm fine merging this as-is.

**Review by djgalloway — APPROVED** [review]

**Pull request merged**
