### PR TITLE
doc/SubmittingPatches.rst: use Google style guide for doc patches

### PR DESCRIPTION
**Pull request by smithfarm**
Signed-off-by: Nathan Cutler <ncutler@suse.com>

### CODE REVIEW

**Comment by smithfarm** [comment]
Style violation: https://developers.google.com/style/tone#politeness-and-use-of-please

**Comment by liewegas** [comment]
Uh oh!  https://www.theatlantic.com/science/archive/2018/05/two-spaces-after-a-period/559304/

Is the two spaces thing part of the style guide?  That recent research paper, if I recall, concluded 2 spaces is better (for a monospaced font).

**Comment by smithfarm** [comment]
@liewegas I love the last three paragraphs of that article you linked to! 

Yes, the single-space is part of the style guide: https://developers.google.com/style/sentence-spacing

Read on for some opinionated verbiage on this topic.

I used to be a two-spacer, having been taught to type that way when I was young.

I agree with the article's thesis that quite a few folks (millions?) have gotten so used to it that it "seems" right to them, just like writing left to write seems "right", as opposed to writing right to left, or down to up.

In my professional career as a translator I was forced to abandon this idea, since I was asked to submit copy with single-space between sentences and after colons within a sentence. When I was first asked to do this, I was indignant and thought the people asking me to single-space were wrong. I embarked on a search for style guides calling for double-space, and came up empty-handed.

I gave up long ago, but when I examined reputable publications looking for evidence of double-space I never could find any. My conclusion was/is that they simply don't put two hard spaces in.

So, over time, I came to view the two-space "rule" as spurious and without merit and I no longer consider it "right", and I scoff at the ridiculous study referred to in that article!

**Comment by smithfarm** [comment]
@liewegas Regardless of the above, I'll will drop the double- to single-space change from this PR if you prefer.

**Comment by smithfarm** [comment]
(What I would give to have been a fly on the wall at Google when they were debating https://developers.google.com/style/sentence-spacing !)

**Comment by liewegas** [comment]
This is probably not the hill I should die on.  :)

(Long live the two-space rule!)

**Pull request merged**
