### PR TITLE
jewel: librbd: possible deadlock if cluster connection closed after image

### PR DESCRIPTION
**Pull request by xiaoxichen**
http://tracker.ceph.com/issues/17265

### CODE REVIEW

**Comment by xiaoxichen** [comment]
@dillaman , would you mind mark the ticket as urgent so this  can squeeze into 10.2.3？

**Comment by ktdreyer** [comment]
Missed v10.2.3, here comes v10.2.4

**Comment by dillaman** [comment]
Need to ensure that 2f4d4868 is included in any build this PR land in

**Comment by dachary** [comment]
replaced by https://github.com/ceph/ceph/pull/11466

**Pull request closed without merging**
