### PR TITLE
Messenger: Fix incorrect connect_seq increase when enabling reset_check

### PR DESCRIPTION
**Pull request by yuyuyu101**
two monitor node(A,B) connected with lossless_peer_reuse policy,
1. lots of messages has been transmitted....
2. markdown A
3. restart A
4. network error injected and A failed to build a *session* with B
5. because of policy and in_queue() == true, we will reconnect in "writer()"
6. connect_seq++ and try to reconnect
7. because of connect_seq != 0, B can't detect remote reset and in_seq(a large value) will be exchange and cause A crashed(Pipe.cc:1154)

The drop line is added(https://github.com/ceph/ceph/commit/0fc47e267b6f8dcd4511d887d5ad37d460374c25#diff-500cebf3665775f2e77db1ff88255b9bR1553).

### CODE REVIEW

**Comment by gregsfortytwo** [comment]
This looks good to me but I haven't been following the messenger testing stuff too well.

**Comment by gregsfortytwo** [comment]
@yuyuyu101 Can you tag the Pipe fix for backport to hammer,firefly,dumpling? :)
(At least, I think for dumpling.)

**Comment by yuyuyu101** [comment]
@gregsfortytwo Done

**Comment by liewegas** [comment]
@yuyuyu101 I'm not sure what you mean by

So later we added codes to catch
"(existing->state == STATE_OPEN || existing->state == STATE_STANDBY)"
before asserting.

which does is that referring to?  Thanks!

**Comment by yuyuyu101** [comment]
The commit(0fc47e2#diff-500cebf3665775f2e77db1ff88255b9bR1553) at that time want to make sure existing->state == STATE_CONNECTING when replacing and connect_seq == existing->connect_seq. So it want to increase connect_seq for initiator and try to avoid  connect_seq == existing->connect_seq.

But later we found it still exists problem then added codes(https://github.com/ceph/ceph/blob/master/src/msg/simple/Pipe.cc#L537) and want to catch existing->state == STATE_OPEN and STATE_STANDBY.

So the previous commit which we drop here is useless.

**Pull request merged**
