### PR TITLE
qa: Wip install ansible jewel

### PR DESCRIPTION
**Pull request by tmuthamizhan**

### CODE REVIEW

**Comment by tmuthamizhan** [comment]
@yuriw pls review

**Comment by tchaikov** [comment]
@tmuthamizhan could you remove the merge commit, and also could you prefix the title of your commit message with the subcomponent your are changing ? see https://github.com/ceph/ceph/blob/master/SubmittingPatches.rst#3-describe-your-changes, in your case, it could be "qa: ".

**Comment by tmuthamizhan** [comment]
@tchaikov done, does it look ok now?

**Comment by yuriw** [comment]
@tmuthamizhan @tchaikov we can merge is tests passed

**Comment by tmuthamizhan** [comment]
@yuriw running tests, will let you know once they pass

**Comment by liewegas** [comment]
we probably don't need this any more?

**Comment by yuriw** [comment]
yeah too old

**Comment by gregsfortytwo** [comment]
Based on comments from last December, I am closing this PR.

**Pull request closed without merging**
