### PR TITLE
nautilus: mgr/dashboard: Silence Alertmanager alerts

### PR DESCRIPTION
**Pull request by Devp00l**
http://tracker.ceph.com/issues/40699

### CODE REVIEW

**Comment by Devp00l** [comment]
Tested it on a fresh build - worked fine :)

**Comment by votdev** [comment]
Please summarize all commits in the PR comment.

**Comment by smithfarm** [comment]
@votdev This is a backport of https://github.com/ceph/ceph/pull/27277, where I see there is a nice PR description.

**Comment by Devp00l** [comment]
@votdev I documented merge conflicts in the commit see https://github.com/ceph/ceph/pull/28968/commits/0a453abb48778a3015de50a679574826ab719bac for details.

**Comment by Devp00l** [comment]
jenkins test dashboard

**Comment by Devp00l** [comment]
jenkins test dashboard

**Comment by tspmelo** [comment]
jenkins test dashboard

**Comment by smithfarm** [comment]
needs-rebase

**Comment by smithfarm** [comment]
I guess this needs to pass the 'ceph dashboard tests' Jenkins test, first?

**Comment by smithfarm** [comment]
In all likelihood, this will need to be rebased once again after https://github.com/ceph/ceph/pull/28938 merges.

**Comment by Devp00l** [comment]
jenkins test dashboard

**Comment by yuriw** [comment]
[wip-yuri5-testing-2019-07-31-1625-nautilus](https://trello.com/c/BG4V781x/681-wip-yuri5-testing-2019-07-31-1625-nautilus)

**Pull request merged**
