### PR TITLE
squid: ceph-volume: do source devices zapping if they're detached.

### PR DESCRIPTION
**Pull request by guits**
backport tracker: https://tracker.ceph.com/issues/66448

---

backport of https://github.com/ceph/ceph/pull/57807
parent tracker: https://tracker.ceph.com/issues/66315

this backport was staged using ceph-backport.sh version 16.0.0.6848
find the latest version at https://github.com/ceph/ceph/blob/main/src/script/ceph-backport.sh

### CODE REVIEW

**Comment by guits** [comment]
jenkins test ceph-volume tox

**Review by asm0deuz — APPROVED** [review]
LGTM

**Comment by guits** [comment]
jenkins test make check

**Comment by guits** [comment]
jenkins test make check

**Comment by guits** [comment]
https://pulpito.ceph.com/gabrioux-2024-08-01_10:46:13-orch:cephadm-wip-guits-testing-5-2024-08-01-0751-squid-distro-default-smithi/

**Comment by guits** [comment]
https://pulpito.ceph.com/gabrioux-2024-08-01_13:04:14-orch:cephadm-wip-guits-testing-5-2024-08-01-0751-squid-distro-default-smithi/

**Comment by guits** [comment]
jenkins test make check

**Pull request merged**
