### PR TITLE
jewel: rgw: rgw_file: FHCache residence check should be exhaustive

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/19143

### CODE REVIEW

**Comment by mattbenjamin** [comment]
@ktdreyer @smithfarm the proximate cause of this build failure is lack of

commit ef330f385d3407af5f470b5093145f59cc4dcc79
Author: Matt Benjamin <mbenjamin@redhat.com>
Date:   Fri Feb 10 17:14:16 2017 -0500

    rgw_file: add pretty-print for RGWFileHandle

**Comment by mattbenjamin** [comment]
@ktdreyer I apologize, I don't see the on master a merge commit/PR which contains;  XXX depends on (should follow) #13084

**Comment by smithfarm** [comment]
@mattbenjamin This backport seems non-trivial; can you take it?

**Comment by mattbenjamin** [comment]
@smithfarm sure, can do--thank you for your effort so far!

**Pull request closed without merging**
