### PR TITLE
jewel: rbd bench-write: seg fault when --io-size is larger than image size 

### PR DESCRIPTION
**Pull request by dachary**
http://tracker.ceph.com/issues/17059

### CODE REVIEW

**Comment by dachary** [comment]
@dillaman the https://github.com/ceph/ceph/pull/9066 pull request was backported to avoid conflict (rename BenchWrite.cc into Bench.cc). It introduces a new feature but it looks like it is acceptable for a backport. What do you think ?

**Comment by dillaman** [comment]
@dachary I'd like to avoid backporting new features (outside the feature gaps in rbd-mirror daemon).

**Comment by dillaman** [comment]
@dachary Alternative PR: #10796

**Comment by dachary** [comment]
Thanks for the alternate backport, much appreciated :-)

**Pull request closed without merging**
