### PR TITLE
rbd: don't allow --allow-shrink when growing image

### PR DESCRIPTION
**Pull request by bniver**
Fixes: http://tracker.ceph.com/issues/15991
Signed-off-by: Brett Niver <bniver@redhat.com>

### CODE REVIEW

**Comment by idryomov** [comment]
IMO this is unnecessary.  This is essentially a force flag and I can't think of any standard command that would error out if force is specified but isn't used.  That goes for our "--yes-i-really[-really]-mean-it" too.

**Comment by bniver** [comment]
@idryomov  - that's fine.   I would assume that if we decide this is extraneous, then the tracker item would be marked "not a bug"?

**Comment by idryomov** [comment]
Redmine's speak for "not a bug" is Rejected.  That's just me though, let's see what @jdurgin and @dillaman think first.

**Comment by bniver** [comment]
Why is it necessary at all?  If new size is smaller, then shrink, right?

**Comment by dillaman** [comment]
@bniver It's required on shrink for the same reason "--yes-i-really-really-mean-it" is there for pool deletions.  If a user accidentally shrinks an image (typo, wrong image, etc), they probably just corrupted the image's file system if they didn't properly shrink everything inside the VM.

**Comment by jdurgin** [comment]
I agree with @idryomov, accepting a force flag like this when it does nothing seems fine, and avoids breaking scripts that would e.g. always pass the option.

**Comment by bniver** [comment]
ok, want me to mark the issue rejected?

**Comment by jdurgin** [comment]
sure, go ahead

**Pull request closed without merging**
