### PR TITLE
mon: monmap created is 0.000000 use ceph-deploy installed

### PR DESCRIPTION
**Pull request by dwj192**
Fixed: #14130
Signed-off-by: Weijun Duan <duanweijun@h3c.com>

### CODE REVIEW

**Comment by jecluis** [comment]
Nice catch, but I don't think this is the correct fix.

After a brief investigation of the code, I think the fix should go into `MonMap::build_initial()`. Most likely just before the last `return 0` statement of the function, and should mimic the monmaptool; e.g.:

``
created = ceph_clock_now(g_ceph_context);
last_changed = created;
``
or something similar. I'd have to test it to make sure though.

**Comment by dwj192** [comment]
@jecluis 
Had modify, please check it, thanks!

**Comment by jecluis** [comment]
@dwj192 Looks okay, but needs testing. Please add a unit test to make sure this works now and to avoid regressions in the future. Thanks!

**Comment by dwj192** [comment]
@jecluis  It's my maiden unit test for ceph, is it correct? please advise...

**Comment by liewegas** [comment]
Can you rebase please?  Test looks good to me!  I assume 'make check' passes for you?

**Comment by liewegas** [comment]
rebase please?

**Comment by dwj192** [comment]
@liewegas 
sorry, Operational errors，change to https://github.com/ceph/ceph/pull/7459

**Pull request closed without merging**
