### PR TITLE
quincy: mgr/nfs: Don't crash ceph-mgr if NFS clusters are unavailable.

### PR DESCRIPTION
**Pull request by pponnuvel**
backport trackers: 
https://tracker.ceph.com/issues/66700
https://tracker.ceph.com/issues/67195

---

backport of https://github.com/ceph/ceph/pull/56876 and https://github.com/ceph/ceph/pull/58535

parent trackers: 
https://tracker.ceph.com/issues/56246
https://tracker.ceph.com/issues/66800

this backport was staged using ceph-backport.sh version 16.0.0.6848
find the latest version at https://github.com/ceph/ceph/blob/main/src/script/ceph-backport.sh

### CODE REVIEW

**Comment by phlogistonjohn** [comment]
Hi, please see https://tracker.ceph.com/issues/66800 . if you backport this this will start breaking our CI even more. I think the fix needs to be reworked in order not to break setups without orchestration enabled.

**Comment by pponnuvel** [comment]
@phlogistonjohn Thanks for notifying me. I am checking 66800. Is the description noted in 66800 a good test case? I am not sure how to run the CI tests myself.

**Comment by phlogistonjohn** [comment]
You should not need to run the go-ceph ci. Just mimic what it does. It manually sets up the .nfs pool and namespace and config stub.

https://github.com/ceph/go-ceph/blob/1046b034a1f618f67acd3c6523482917e27c7113/common/admin/nfs/export_test.go#L74-L83

Then in one of the failing tests the system fails because it doesn't think the "cluster" exists.
https://github.com/ceph/go-ceph/blob/1046b034a1f618f67acd3c6523482917e27c7113/common/admin/nfs/export_test.go#L133-L138

Do note that Rook setups up a manual nfs pool and Ceph-CSI uses the library we provide. There's a good chance that this change will also break the Ceph-CSI/Rook combo.

**Comment by pponnuvel** [comment]
With https://github.com/ceph/ceph/pull/58535 merged, do you see any issue with this backport? If not, I'll cherry pick https://github.com/ceph/ceph/pull/58535 into this and propose again.

**Comment by pponnuvel** [comment]
@phlogistonjohn With https://github.com/ceph/ceph/pull/58535 merged, do you see any issue with this backport? If not, I'll cherry pick https://github.com/ceph/ceph/pull/58535 into this and propose again.

**Comment by phlogistonjohn** [comment]
sounds like a plan.

**Comment by pponnuvel** [comment]
jenkins test make check

**Comment by anoopcs9** [comment]
I see that you have included the changes from #58535 as part of the current PR. But shouldn't we create quincy backport bug for the upstream tracker https://tracker.ceph.com/issues/66800 and correspondingly reference it here?

**Comment by pponnuvel** [comment]
> I see that you have included the changes from #58535 as part of the current PR. But shouldn't we create quincy backport bug for the upstream tracker https://tracker.ceph.com/issues/66800 and correspondingly reference it here?

done

**Comment by pponnuvel** [comment]
@phlogistonjohn 

I've cherry-picked #58535 and proposed the backports:
https://github.com/ceph/ceph/pull/58283
https://github.com/ceph/ceph/pull/58284
https://github.com/ceph/ceph/pull/58285

Would you be able to review and merged or notify the right people to do review & merge? Thanks.

**Comment by phlogistonjohn** [comment]
I'll review and I'd also like @anoopcs9 to review, then I'll ask @adk3798 to review and/or merge after Anoop and I take a look.

**Comment by pponnuvel** [comment]
jenkins retest make check

**Comment by pponnuvel** [comment]
jenkins test make check

**Comment by pponnuvel** [comment]
Thanks @anoopcs9 for the reviewing the patches. Please take a look at this one too.

**Review by anoopcs9 — APPROVED** [review]
lgtm, thanks.

**Review by phlogistonjohn — APPROVED** [review]
looks ok for backport.
I think I had started a review nearly two days ago, but nearly got lost among the other tabs.

**Comment by phlogistonjohn** [comment]
@adk3798 can we include this in an teuthology orch run of quincy backports?

**Comment by pponnuvel** [comment]
@adk3798 @yuriw Thanks for QA and merging it in Quincy. 

Can you please do the same for Reef  (PR: https://github.com/ceph/ceph/pull/58283) & Squid (PR: https://github.com/ceph/ceph/pull/58285) backports and include in their next point releases?

**Pull request merged**
