### PR TITLE
src/doc: fix class names in exports.txt

### PR DESCRIPTION
**Pull request by jcsp**
Signed-off-by: John Spray <john.spray@redhat.com>

### CODE REVIEW

**Comment by dachary** [comment]
jenkins test this please (eio/osd-crush.sh failures)

**Comment by liewegas** [comment]
This is probably a good time to move this to ../doc/dev/ and rst

**Comment by gregsfortytwo** [comment]
Text changes look good to me, but there's @liewegas's note.

**Comment by jcsp** [comment]
@gregsfortytwo @liewegas updated to move the file too.  There isn't that much left in this dir so it shouldn't be hard to wholesale move the remaining mds bits over at some point soon.

**Pull request merged**
