### PR TITLE
PendingReleaseNotes: add orchestrator

### PR DESCRIPTION
**Pull request by sebastian-philipp**
Signed-off-by: Sebastian Wagner <sebastian.wagner@suse.com>

- [ ] References tracker ticket.
- [x] Updates documentation if necessary

### CODE REVIEW

**Comment by tchaikov** [comment]
jenkins render docs

**Comment by sebastian-philipp** [comment]
Is the PendingReleaseNotes file hooked into the sphinx documentation somewhere?

**Comment by tchaikov** [comment]
@sebastian-philipp no. i didn't give it a thought before asking jenkins to render the doc..

**Comment by sebastian-philipp** [comment]
Although, adding that to the sphinx build would ensure proper RST formatting. That would need to be conditionally added for developer builds only, though.

**Comment by liewegas** [comment]
incorporated into https://github.com/ceph/ceph/pull/26598

**Pull request closed without merging**
