### PR TITLE
mgr/cephadm: Add extra-ceph-conf

### PR DESCRIPTION
**Pull request by sebastian-philipp**
Due to limitations of `config generate-minimal-conf`, (see #36884) 
we need to provide a way for users to modify the
ceph.conf for the daemons.

This now provides a way to append config to
the daemons config. Like. e.g. `cluster_network`.

Signed-off-by: Sebastian Wagner <sebastian.wagner@suse.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by sebastian-philipp** [comment]
green: https://pulpito.ceph.com/swagner-2020-08-31_14:42:04-rados:cephadm-wip-swagner-testing-2020-08-31-1131-distro-basic-smithi/

**Comment by theanalyst** [comment]
LGTM

**Review by jschmid1 — APPROVED** [review]
it's a pity that we have to do it that way, but I also don't see another way without introducing huge changes.

**Comment by jschmid1** [comment]
test results: https://pulpito.ceph.com/jschmid-2020-09-16_10:44:07-rados:cephadm-wip-jschmid1-testing-2020-09-16-1013-distro-basic-smithi/

Test failure: test_cluster_set_reset_user_config (tasks.cephfs.test_nfs.TestNFS):

status: known
identified by: https://github.com/ceph/ceph/pull/37122#issuecomment-692099983

Test failure cluster [ERR] Health check failed: 1 filesystem is offline (MDS_ALL_DOWN)" in cluster log

status: unkown

**Comment by jschmid1** [comment]
Test failures are not related to this PR

**Pull request merged**
