### PR TITLE
crimson/osd: add minimal state machine for PG peering

### PR DESCRIPTION
**Pull request by tchaikov**
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by athanatos** [comment]
Is this an effort to break https://github.com/ceph/ceph/pull/26697/commits into smaller pieces?

**Comment by athanatos** [comment]
I'd like to observe that the state machine/osd interface employed here broadly mirrors the existing machinery.  The user (osd) gives the recovery state machine a logical event and a means for propagating side effects asyncronously.  The state machine itself really only gets to do two things:
1) update local in-memory state (which it may assume exclusive access to)
2) schedule side effects (writes, messages) via the recovery::Ctx concept.
Notably, it does not do reads afaict -- all of the relevant state is in memory.  I've been reading through the existing state machine logic in PG.h, and I'm fairly confident I can extract the RecoveryState and related PG methods and reuse it directly crimson.  To be clear, it wouldn't actually include the logic for *doing* something like a backfill or a scrub, but it would have all of the logic required for bouncing peering messages around and updating the info/info.history structures.

**Comment by xiexingguo** [comment]
@athanatos Welcome back!

**Comment by tchaikov** [comment]
yes, this is a subset of #26697. i am trying to break it down to smaller PRs so they are easier to review and hopefully can be merged sooner.

**Comment by tchaikov** [comment]
> it does not do reads afaict 

yeah, the state machine does nott return `future<>`. actually, we could do async op in the statemachine with proper guarding with `seastar::gate`.

> I'm fairly confident I can extract the RecoveryState and related PG methods and reuse it directly crimson

agreed. the reason i am extracting a subset of it into "src/crimson" is to avoid worrying about the unnecessary dependencies. these dependencies fall into different categories:

- unsupported operations related states, like recovery, backfill, scrub.
- some machinery/operations that i am not sure if they apply to crimson-osd, like `publish_stats_to_osd()`. at the very beginning, i even wanted to send the "side-effects" (pg_notify) right in statemachine, without using the the RecoveryContext. as it seems that we don't benefit from batching the notifications -- context are not supposed to be shared across different PGs, so only a couple outgoing messages will be stashed into the context. but i found that the messages like `MOSDPGInfo` is *designed* to hold multiple notifications. so i think probably i should hold this change back until we have a prototype.
- ldout(), actually, i want to kill cct in crimson-osd.

> it's not likely we could come up with an implementation of those IO paths that would be both optimal for crimson and tolerable for classic

no. but i think in the long run, we can indeed "futurize" the state machine.

**Comment by athanatos** [comment]
I'm working on a solution for the logging thing now.  I think the answer is to adapt any code we want to share to have essentially crimson-style logging and create an adapter to make classic osd ok with that.  Hopefully I'll have something on this tomorrow.

I'm not as worried about the recovery/backfill/scrub parts.  We can hack something up to short circuit it (like have crimson just pretend to complete the operation immediately).

As far as futurizing the state machine, I think I'm saying that it already is.  It doesn't perform any blocking IO that isn't already represented using the transaction attached to the RecoveryCtx.  The challenge then is pretty much refactoring to clean up the RecoveryState->PG calls (things like proc_replica_log etc) so that crimson can slot right in.  Most of that will be a matter of moving some of the peering state down into RecoveryState and cleaning up the users.

I've got a branch with RecoveryState yanked into out of PG into its own class, I'm working on cleaning up the RecoveryState->PG calls.  Once that's done (assuming it winds up being pretty clean), we should be able to wire it under the event handle calls in crimson.  Some events will trigger behavior that doesn't exist yet, but that's ok.  Mainly, it should be sufficient to make the peering message sequences work right.

I need to go through it in a bit more detail, but this patch series strikes me as being about right.

**Comment by tchaikov** [comment]
@athanatos does it make sense to get the commits before "crimson/osd: add minimal PG recovery FSM " reviewed and merged first ?

**Comment by athanatos** [comment]
LGTM.  I'd be fine with either merging the PG bits or not -- I can adjust as needed when I get to it either way.

**Comment by tchaikov** [comment]
changelog

- use `std::move()` when appropriate.
- rename `compare_set()` to `compare_n_set()`
- rebase onto master.

**Pull request merged**
