### PR TITLE
octopus: mgr/dashboard: Use secure cookies to store JWT Token

### PR DESCRIPTION
**Pull request by avanthakkar**
backport tracker: https://tracker.ceph.com/issues/48739

---

backport of https://github.com/ceph/ceph/pull/38259
parent tracker: https://tracker.ceph.com/issues/44591

this backport was staged using ceph-backport.sh version 16.0.0.6848
find the latest version at https://github.com/ceph/ceph/blob/master/src/script/ceph-backport.sh

### CODE REVIEW

**Comment by callithea** [comment]
Hi @avanthakkar there seems to be a make check failure related to this PR:
```
dashboard/controllers/__init__.py: note: In function "validate_ceph_type":
dashboard/controllers/__init__.py:977: error: Name 'ArgumentFormat' is not defined
dashboard/controllers/__init__.py:978: error: Name 'DashboardException' is not defined
Found 2 errors in 1 file (checked 10 source files)
```

**Comment by avanthakkar** [comment]
> Hi @avanthakkar there seems to be a make check failure related to this PR:
> 
> ```
> dashboard/controllers/__init__.py: note: In function "validate_ceph_type":
> dashboard/controllers/__init__.py:977: error: Name 'ArgumentFormat' is not defined
> dashboard/controllers/__init__.py:978: error: Name 'DashboardException' is not defined
> Found 2 errors in 1 file (checked 10 source files)
> ```

Yes! Forgot to push a change. Just did it.

**Comment by avanthakkar** [comment]
jenkins test dashboard

**Comment by avanthakkar** [comment]
jenkins test make check

**Comment by avanthakkar** [comment]
jenkins test make check

**Comment by avanthakkar** [comment]
jenkins test dashboard

**Comment by aaSharma14** [comment]
jenkins test make check

**Comment by avanthakkar** [comment]
jenkins test dashboard

**Comment by avanthakkar** [comment]
jenkins test dashboard

**Review by callithea — APPROVED** [review]
Lgtm, thank you!

**Comment by avanthakkar** [comment]
jenkins test dashboard

**Comment by aaSharma14** [comment]
jenkins test dashboard

**Comment by aaSharma14** [comment]
jenkins test dashboard

**Review by alfonsomthd — APPROVED** [review]

**Pull request merged**
