### PR TITLE
rgw: add OPT_BUCKET_SYNC_RUN to gc_ops_list, so that

### PR DESCRIPTION
**Pull request by pritha-srivastava**
gc is initialised and send_chain does not crash.

Also deleting objects inline in case gc is uninitialised.

Signed-off-by: Pritha Srivastava <prsrivas@redhat.com>

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by mattbenjamin** [comment]
should file a tracker, I think @pritha-srivastava

**Review by adamemerson — APPROVED** [review]

**Comment by pritha-srivastava** [comment]
> should file a tracker, I think @pritha-srivastava

@mattbenjamin : i have updated the pr with a tracker.

@mattbenjamin @adamemerson : apart from bucket sync run command, is there a need to review other radosgw-admin commands as well, although i have added a check that if gc is null then the objects can be deleted inline.

**Review by cbodley — APPROVED** [review]

**Comment by pritha-srivastava** [comment]
teuthology run results here: https://pulpito.ceph.com/prsrivas-2022-02-28_10:41:38-rgw-wip-rgw-bucket-sync-run-distro-default-smithi/

The failures do not look related to this PR.

**Comment by cbodley** [comment]
the only failure i don't recognize is this one from http://qa-proxy.ceph.com/teuthology/prsrivas-2022-02-28_10:41:38-rgw-wip-rgw-bucket-sync-run-distro-default-smithi/6710931/teuthology.log:
> Command failed on smithi027 with status 1: 'cd /home/ubuntu/cephtest/s3-tests-java && /opt/gradle/gradle/bin/gradle clean test --rerun-tasks --no-build-cache --tests ObjectTest'
```
suite > Object tests > ObjectTest.testUploadFileList STARTED

suite > Object tests > ObjectTest.testUploadFileList FAILED
    com.amazonaws.services.s3.model.AmazonS3Exception

----------------------------------------------------------------------
|  Results: FAILURE (72 tests, 71 successes, 1 failures, 0 skipped)  |
----------------------------------------------------------------------
```

i scheduled a rerun at https://pulpito.ceph.com/cbodley-2022-02-28_19:57:53-rgw-wip-rgw-bucket-sync-run-distro-default-smithi to see if it goes away

**Comment by cbodley** [comment]
ok, it did go away 👍

**Comment by mattbenjamin** [comment]
quick question @cbodley @pritha-srivastava -- this covers just the BUCKET_SYNC_RUN command.  Is the same thing needed for DATA_SYNC_RUN as well?  (sorry for not asking earlier)

**Comment by cbodley** [comment]
yeah i missed that too, `DATA_SYNC_RUN` could trigger the same deletes as `BUCKET_SYNC_RUN`

**Comment by pritha-srivastava** [comment]
> yeah i missed that too, `DATA_SYNC_RUN` could trigger the same deletes as `BUCKET_SYNC_RUN`

@cbodley, @adamemerson , @mattbenjamin : Also I had asked earlier, if there are other commands that need to be added to the gc ops list (apart from bucket sync run and data sync run)

**Pull request merged**
