### PR TITLE
mgr/dashboard: Switched from png icons to svg icons

### PR DESCRIPTION
**Pull request by SchoolGuy**
As in the reference tracker says it is better in my eyes to use SVG as PNGs in the web. Thus I created together with @Exotelis a small component which enables us to reuse and style our icon and icon variants.

## Checklist
- [x] References tracker ticket: https://tracker.ceph.com/issues/47111
- [ ] Updates documentation if necessary
- [x] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Review by epuertat — CHANGES_REQUESTED** [review]
Neat approah, @SchoolGuy ! I too prefer vector graphics, rather than raster ones.

I see that this PR embeds SVG code into an HTML template. While this is [technically valid](https://angular.io/guide/svg-in-templates), I think it has a negative impact on dashboard code maintainability and performance:
* people and especially that subclass of people that we know as designers usually don't read (SVG) pictures, they simply open those in an image editor. By mixing SVG code with Angular directives, we are making impossible to open this SVG in any image editor.
* by embedding graphics into templates, we are creating a bigger bundle. Potential bandwidth savings derived from this approach are overrun by the benefits of separate static assets (mainly caching and parallel download).

Isn't it possible to achieve a similar behaviour with CSS transform?

BTW, could you please post some pictures of the before&after this change?

Thanks!

**Comment by SchoolGuy** [comment]
@epuertat I agree with you that what we (Sebastian and me) are doing is uncommon. If you take a close look at the template you will see that these vector graphics are never intended to be opened in something like Inkscape. We stripped all metadata of it to not give the svgs any "manipulation" by the various vector graphic programs. Thus a designer shall never open these vector files. I recieved the originals from Sebastian, who himself received them from Mike Perez. Designing these logos and integrating them into Ceph are two different things in my eyes.

Also a downside of having static assets and then using some kind of image manipulation is that we lose many advantages of SVG. My source of information is this paragraph on [svgontheweb.com](https://svgontheweb.com/#implementation). Also we are trying to work "around" the intuitive way of handling SVGs on the web.

Regarding the caching: Apparently we can make the caching work with some hacky JS since I found this article - https://css-tricks.com/inline-svg-cached/ - but I don't like adding this kind of complexity.

Regarding the parallel download: I don't have any arguments, especially in the notifications this could be something which is useful.

On the other hand if we manipulate the SVGs we need an own stylesheet because then the SVG is in its own DOM which means this new stylesheet also needs to be loaded (yes that is probably cached but still). If we manipulate the SVG via its own stylesheet the designer can't open the SVG [directly again](https://blueprints.launchpad.net/inkscape/+spec/external-css) since it is hardwired to our running Ceph. If we manipulate the SVG via JS to circumvent that topic then we need to wait until the SVG is loaded and then execute JS which increases the bundle size again thus our SVG is size wise SVG + JS for manipulation which will most likely be more then our template + component TS size. The more similar icons we have the more efficient Sebastian and my approach gets in my eyes.

Since we currently have two different variants of our Icon in my eyes both of our arguments are micro optimizations which won't make a measurable difference at all. We are taking in the end about currently 11.7 KiB + 239B + 196B (Sebstian and my approach) vs 9.5 KiB + 6 KiB + some TS/SCSS for styling (your approach with caching and parallel download).

But since my web experience is very limited compared to yours I will talk to Sebastian if we can somehow find the best our of both worlds. Screenshots will also come tomorrow.

**Comment by tspmelo** [comment]
Can't remember exactly what was the last solution proposed in today's standup, but I think it differed from the following:

https://github.com/tspmelo/ceph/commit/0afcb42b22098e8158c1d1651c736abcee915011
1. By extracting the text from the svg, it reduces modifications on the svg and its easier to show/hide.
We just need to find a way to keep it the same size as the logo or vice versa.
2. Using the css `mask` option, we can easily change the color of the logo via css
3. In my example I'm using `hover` to test the color change, in the final solution the color would be associated with a fixed class
4. We should also find out the correct font to apply on the logo text.

**Comment by SchoolGuy** [comment]
Okay after researching this for another hour:

- Dynamical loading of templates in Angular is not possible without messing with Angular internals deeply. Angular enforces the One Component, One Template approach.
- Using `<object>` or `` is not an option as we need an external stylesheet which needs to be manually put into every svg after dropping it in the resource folder. This stylesheet will not be simple since it needs to be page sensitive.
- Having Subcomponents is cluttering the component tree and requires Angular to take care of more logic (which we don't need to code but it is there).
- Using @tspmelo 's approach is not an option since we don't have a font for the Ceph letters in the logo.

Thus since all options are not optimal and ours proposal was discarded I decide to close this PR. We need to wait until either Inkscape has External Stylesheet support (for easy editing of the svg) or we need to be willing to maintain a solution similar to Sebastian and my proposal.

**Comment by epuertat** [comment]
> Thus since all options are not optimal and ours proposal was discarded I decide to close this PR. We need to wait until either Inkscape has External Stylesheet support (for easy editing of the svg) or we need to be willing to maintain a solution similar to Sebastian and my proposal.

@SchoolGuy I don't think the proposal was discarded, just was the implementation debated:
* To me, moving from PNG to SVG sounds like a nice move, same as cleaning-up the SVG code. Thanks for that!
* However, I find too it complicate to embed a mix of SVG code with Angular directives just [for replacing 2 PNG images](https://xkcd.com/974/) (and believe it's speaking someone that always feels tempted to implement a 'generic solution that will fix this but also the issues to come'). 

If we still want to come up with a different presentation of the Ceph logo based on size, we can still use simpler approaches like  [responsive images](https://css-tricks.com/responsive-images-css/) and media queries (SVG also support inline CSS media queries).

**Comment by SchoolGuy** [comment]
@epuertat Yes I know that the switch to SVG itself was not discarded but rather Sebastian and my implementation.

The reason why someone does want to go with SVG is in my eyes because it is easy to manipulate. If we use responsive images we again have to look at the SVG in the text editor, remove clutter and write our styles directly into the SVG (which was a negative point on the daily since we are expecting this to be done by a designer also each logo replacement needs to be done with care as the styles are in it). If we go for responsive images we lose the point why an svg is so cool since we are handling it like a raster graphics image.

Also I found Sebastian and my solution very straigtforward: Take the paths of an SVG - drop them into the `*ngSwitch` - define a name for the new variant - use our component and say `variant="something"` - done. Styling is done via a stylesheet in the component which uses the icon with two classes and an id.

**Comment by LenzGr** [comment]
> The reason why someone does want to go with SVG is in my eyes because it is easy to manipulate.

I'm not so sure about this. IMHO, switching from PNGs to SVGs already has merit, if the same image is required in different resolutions. In that case, multiple bitmaps could be replaced with a single SVG file, saving up some space and reducing complexity a bit (and hoping that the browser does a better job in rendering an SVG in the requested resolution on the fly)

**Pull request closed without merging**
