### PR TITLE
rados bench improvements

### PR DESCRIPTION
**Pull request by liewegas**
- make formatting less fragile
- do lots of smaller writes to each object (either block writes or omap)

### CODE REVIEW

**Comment by markhpc** [comment]
--max-objects may not be working:

rados -p cbt-librbdfio bench 100000000 write -b 0 --max-objects 4000000 --no-cleanup

GLOBAL:
    SIZE       AVAIL     RAW USED     %RAW USED 
    14606G     3263G       11342G         77.66 
POOLS:
    NAME              ID     USED     %USED     MAX AVAIL     OBJECTS   
    rbd               0         0         0         3263G             0 
    cbt-librbdfio     1         0         0         3263G     888719266

**Comment by tchaikov** [comment]
@markhpc tested with

```
$ ./src/rados -p test-pool bench 1000000 write -b 0 --max-objects 40000 --no-cleanup
...
$ ./ceph df
GLOBAL:
    SIZE     AVAIL      RAW USED     %RAW USED
    664G     92752M         573G         86.36
POOLS:
    NAME                ID     USED     %USED     MAX AVAIL     OBJECTS
    rbd                 0        24         0        30618M        4002
    cephfs_data         1         0         0        30618M           0
    cephfs_metadata     2      4416         0        30618M          54
    test-pool           5        24         0        30618M       40002
```

**Comment by tchaikov** [comment]
reviewed, and i think the way to do the ceiling is not quite right.

**Comment by tchaikov** [comment]
lgtm

**Comment by yuyuyu101** [comment]
After merging this PR, rados bench will meet buffer::end_of_buffer exception, I'm not sure the detail problem, just a reminder ...

**Comment by tchaikov** [comment]
the reason of end_of_buffer exception could due to the incompatibility of the new metadata format see
https://github.com/liewegas/ceph/commit/0b369e1aff14d17536566d62a60def418be37963#diff-77d6052552f1e1330c1d4fbf33702764R347 , you might need to nuke the existing metadata, and start a new run from scratch.

**Comment by liewegas** [comment]
what rados bench arguments lead to a crash?  i haven't seen it..

**Comment by liewegas** [comment]
oh, right.  i didn't bother making it compatible since I assumed people 
didn't leave the data sitting around.. but that may not be true.  it's 
easy enough to make it backward compatible, though, just be rearranging 
the fields.

https://github.com/ceph/ceph/pull/7402

**Pull request merged**
