### PR TITLE
enhance osd io-latency and -size statistics tool

### PR DESCRIPTION
**Pull request by scoopex**
- add colors to the output to ease interpretation
- add possibility to specify one ore more sockets
- aggregate statistics over multiple sockets
- prevent stacktrace if tool is interrupted by SIGINT
- add possibility to specify the number of data collection
  seconds between loops

Auswahl_103

### CODE REVIEW

**Comment by tchaikov** [comment]
retest this please.

**Comment by scoopex** [comment]
> retest this please.
Retested this successfully in my production environment. 
I'm sorry - what's wrong?

**Comment by tchaikov** [comment]
@scoopex sorry for the confusion. "retest this please" is a trigger phrase for jenkins. see https://github.com/ceph/ceph-build/blob/3b798ffe1b5b5482697196d096a47409456e8451/teuthology-pull-requests/config/definitions/teuthology-pull-requests.yml#L47 .

i wanted to rerun the "make check" tests to make sure that its failure does not block you.

**Comment by scoopex** [comment]
Done :-)

**Comment by tchaikov** [comment]
unstable this please.

**Comment by scoopex** [comment]
> unstable this please.

resynced with upstream.

**Comment by tchaikov** [comment]
@scoopex i force-pushed to you repo to

- remove the merge commit
- revise the title a little bit to add a prefix and change it from "enhance osd io-latency and -size statistics tool" to "enhance this tool". and put the details in the body of the commit message. hope this is fine by you.

**Comment by scoopex** [comment]
Created a new pull request, see https://github.com/ceph/ceph/pull/30881

**Pull request closed without merging**
