### PR TITLE
nautilus: cephfs: ceph_volume_client: d_name needs to be converted to string before using

### PR DESCRIPTION
**Pull request by batrick**
http://tracker.ceph.com/issues/40324

### CODE REVIEW

**Comment by yuriw** [comment]
[wip-yuri-testing-2019-06-17-2042-nautilus](https://trello.com/c/4seSG4a2/646-wip-yuri-testing-2019-06-17-2042-nautilus)

**Comment by batrick** [comment]
`Reviewed-by: Patrick Donnelly <pdonnell@redhat.com>`

**Comment by smithfarm** [comment]
Re-queuing now that 14.2.2 is out.

**Comment by yuriw** [comment]
[wip-yuri-testing-2019-07-30-1543-nautilus](https://trello.com/c/bRHqvLN7/678-wip-yuri-testing-2019-07-30-1543-nautilus)

**Pull request merged**
