### PR TITLE
rgw: fix miss handle curl error return

### PR DESCRIPTION
**Pull request by tianshan**
if meet tcp packet loss, curl return will be result=18(CURLE_PARTIAL_FILE)
and http_status=200, so sync will continue and cause content miss match.

Signed-off-by: Tianshan Qu <tianshan@xsky.com>

- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by tianshan** [comment]
@cbodley @xiaoxichen maybe this is the root cause of https://tracker.ceph.com/issues/39992

**Comment by xiaoxichen** [comment]
I think it is possible with (result = CURLE_PARTIAL_FILE and http_code = 200) however in previous code it also result an EAGAIN, isnt it?

**Comment by tianshan** [comment]
@xiaoxichen  the http_status is the http_code, so it will not return EAGAIN

**Comment by xiaoxichen** [comment]
```
static inline int rgw_http_error_to_errno(int http_err)
{
  if (http_err >= 200 && http_err <= 299)
    return 0;
```

```
int status = rgw_http_error_to_errno(http_status);
```
status == 0 for your case where http_status = 200;
and 
result = CURLE_PARTIAL_FILE 

why it will not go to EAGAIN?

**Comment by tianshan** [comment]
the condition here needs http_status == 0, but we got http_status = 200, so it will not return EAGAIN, and the status is 0, so the next finish_request will also not return error

**Comment by xiaoxichen** [comment]
sigh...I read your new code...yes you are right.

**Comment by cbodley** [comment]
thanks @tianshan! i wrote a test case for this and pushed it to https://github.com/cbodley/ceph/commits/wip-rgw-http-err, could you please include that commit https://github.com/cbodley/ceph/commit/cfb452bd9e31997c7a6d8850de6c8d6c9f0e9c2c in this pr?

without your fix applied, the test fails with:
```
[ RUN      ] HTTPManager.ReadTruncated
/home/cbodley/ceph/src/test/rgw/test_http_manager.cc:47: Failure
Expected equality of these values:
  -11
  RGWHTTP::process(&client, null_yield)
    Which is: 0
[  FAILED  ] HTTPManager.ReadTruncated (0 ms)
```

with your fix, it passes with a warning:
```
[ RUN      ] HTTPManager.ReadTruncated
[       OK ] HTTPManager.ReadTruncated (1 ms)
2019-06-03T11:58:21.063-0400 7f4b6f2e1700  0 ERROR: curl error: Failure when receiving data from the peer, maybe network unstable
```

**Comment by tianshan** [comment]
@cbodley done. and removed the if condition around dout in my commit, since status == 0 mostly means http_status = 200

**Comment by cbodley** [comment]
passed qa http://pulpito.ceph.com/cbodley-2019-06-03_20:43:11-rgw-wip-cbodley-testing-distro-basic-smithi/

**Pull request merged**
