### PR TITLE
luminous: mds: fix mds damaged due to unexpected journal length

### PR DESCRIPTION
**Pull request by pdvian**
http://tracker.ceph.com/issues/36200

### CODE REVIEW

**Comment by yuriw** [comment]
[wip-yuri4-testing-2018-10-05-2015-luminous](https://trello.com/c/IsbxOeA6/438-wip-yuri4-testing-2018-10-05-2015-luminous)

**Comment by batrick** [comment]
Waiting on some QA runs before merging this.

**Comment by batrick** [comment]
Note to self:

/ceph/teuthology-archive/yuriw-2018-10-05_22:16:45-fs-wip-yuri4-testing-2018-10-05-2015-luminous-distro-basic-smithi/3105500/teuthology.log

**Comment by smithfarm** [comment]
@batrick You reassigned http://tracker.ceph.com/issues/36200 to yourself - did you mean to close this PR when you did that?

**Comment by batrick** [comment]
@smithfarm maybe? I don't know why I marked this stale as it looks okay to me. Maybe I meant to do it for a different backport and got the issues mixed up. I'll re-assign 36200.

**Comment by batrick** [comment]
@smithfarm maybe? I don't know why I marked this stale as it looks okay to me. Maybe I meant to do it for a different backport and got the issues mixed up. I'll re-assign 36200.

**Comment by yuriw** [comment]
[wip-yuri5-testing-2018-12-12-1653-luminous](https://trello.com/c/oXzdX0yM/487-wip-yuri5-testing-2018-12-12-1653-luminous)

**Comment by yuriw** [comment]
[wip-yuri4-testing-2018-12-19-1658-luminous](https://trello.com/c/XKKZA4vr/494-wip-yuri4-testing-2018-12-19-1658-luminous)

**Pull request merged**
