### PR TITLE
kraken: librbd: corrected resize RPC message backwards compatibility

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/19659

### CODE REVIEW

**Comment by smithfarm** [comment]
@dillaman The failure persists even though this PR is included:

* http://tracker.ceph.com/issues/19009#note-30
* http://qa-proxy.ceph.com/teuthology/smithfarm-2017-04-19_04:06:05-upgrade:client-upgrade-wip-kraken-backports-distro-basic-vps/1042954/teuthology.log

**Comment by smithfarm** [comment]
But it's a different mode of failure than before:

```
2017-04-19T05:28:29.537 INFO:tasks.workunit.client.0.vpm021.stderr:+ python /home/ubuntu/cephtest/clone.client.0/qa/workunits/rbd/../../../src/test/librbd/test_notify.py master
2017-04-19T05:28:34.655 INFO:tasks.workunit.client.1.vpm063.stdout:starting slave
2017-04-19T05:28:34.655 INFO:tasks.workunit.client.1.vpm063.stdout:detected master
2017-04-19T05:28:34.655 INFO:tasks.workunit.client.1.vpm063.stdout:rename
2017-04-19T05:28:34.655 INFO:tasks.workunit.client.1.vpm063.stdout:flatten
2017-04-19T05:28:34.656 INFO:tasks.workunit.client.1.vpm063.stdout:resize
2017-04-19T05:28:34.656 INFO:tasks.workunit.client.1.vpm063.stdout:create_snap
2017-04-19T05:28:34.656 INFO:tasks.workunit.client.1.vpm063.stdout:protect_snap
2017-04-19T05:28:34.656 INFO:tasks.workunit.client.1.vpm063.stdout:unprotect_snap
2017-04-19T05:28:34.656 INFO:tasks.workunit.client.1.vpm063.stdout:rename_snap
2017-04-19T05:28:34.656 INFO:tasks.workunit.client.1.vpm063.stdout:remove_snap
2017-04-19T05:28:34.656 INFO:tasks.workunit.client.1.vpm063.stdout:rebuild object map
2017-04-19T05:28:34.656 INFO:tasks.workunit.client.1.vpm063.stderr:Traceback (most recent call last):
2017-04-19T05:28:34.656 INFO:tasks.workunit.client.1.vpm063.stderr:  File "/home/ubuntu/cephtest/clone.client.1/qa/workunits/rbd/../../../src/test/librbd/test_notify.py", line 170, in <module>
2017-04-19T05:28:34.656 INFO:tasks.workunit.client.1.vpm063.stderr:    main()
2017-04-19T05:28:34.657 INFO:tasks.workunit.client.1.vpm063.stderr:  File "/home/ubuntu/cephtest/clone.client.1/qa/workunits/rbd/../../../src/test/librbd/test_notify.py", line 166, in main
2017-04-19T05:28:34.657 INFO:tasks.workunit.client.1.vpm063.stderr:    slave(ioctx)
2017-04-19T05:28:34.657 INFO:tasks.workunit.client.1.vpm063.stderr:  File "/home/ubuntu/cephtest/clone.client.1/qa/workunits/rbd/../../../src/test/librbd/test_notify.py", line 141, in slave
2017-04-19T05:28:34.658 INFO:tasks.workunit.client.1.vpm063.stderr:    False)
2017-04-19T05:28:34.658 INFO:tasks.workunit.client.1.vpm063.stderr:  File "rbd.pyx", line 1474, in rbd.Image.update_features (/build/ceph-11.2.0-359-gf2fdbbe/obj-x86_64-linux-gnu/src/pybind/rbd/pyrex/rbd.c:13173)
2017-04-19T05:28:34.658 INFO:tasks.workunit.client.1.vpm063.stderr:rbd.InvalidArgument: error updating features for image test_notify_clone2
```

**Comment by smithfarm** [comment]
@dillaman I populated a new version of `wip-kraken-backports` including this PR, and re-ran the `upgrade/client-upgrade` suite. The two jobs that were failing before were "hammer-client-x" and "jewel-client-x". Of these, the former is fixed but the latter is showing the new failure mentioned above (I ran both jobs 5 times each to be certain).

See http://tracker.ceph.com/issues/19009#note-32 for the pulpito URLs.

Thanks for helping with this.

**Comment by dillaman** [comment]
@smithfarm Yeah -- different issue where the upgrade test overrides the default features for jewel which results in this failure. Tracker via http://tracker.ceph.com/issues/19692

**Pull request merged**
