### PR TITLE
config-ref: add a note on current scheduler settings.

### PR DESCRIPTION
**Pull request by theanalyst**
Adding a note on configuirables for max concurrent requests and the rest of
experimental options for tuning dmclock scheduler

Signed-off-by: Abhishek Lekshmanan <abhishek@suse.com>

- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by theanalyst** [comment]
still undecided whether this deserves a page of its own.

**Comment by ivancich** [comment]
@cbodley, @theanalyst In fact, there are some detailed QoS docs. I think the link would be `../../rados/configuration/osd-config-ref#qos-based-on-mclock`, although please check to make sure I got it all right.

**Comment by cbodley** [comment]
> still undecided whether this deserves a page of its own.

eventually yeah, when we have more configuration steps and tuning advice - but this is a good start!

**Comment by theanalyst** [comment]
added a cross-ref. 

jenkins render docs

**Comment by theanalyst** [comment]
jenkins render docs

**Comment by theanalyst** [comment]
jenkins build docs

**Comment by theanalyst** [comment]
jenkins render docs

**Comment by ivancich** [comment]
docs look good!

**Comment by cbodley** [comment]
render looks good. can merge once jenkins is happy

**Pull request merged**
