### PR TITLE
os/bluestore: _do_remove: dirty shard individually as each blob is unshared

### PR DESCRIPTION
**Pull request by liewegas**
Fixes: http://tracker.ceph.com/issues/20849

### CODE REVIEW

**Comment by liewegas** [comment]
I'm a bit nervous about this fix because it means we dirty slightly less, and there might be misuses of dirty_range that relied on that sloppiness elsewhere in the code.  I'd rather give it lots of testing before backport to luminous...

**Comment by xiexingguo** [comment]
@liewegas  I doubt this is the right fix. `fault_range` and `dirty_range ` shares the same logic of seeking shards. If `dirty_range` complains that some shard is missing(not loaded), then perhaps it is because `fault_range` did a bad thing? (or simply because `fault_range` dirties less than we expect it is supposed to do?)

**Comment by liewegas** [comment]
It's not directly related to fault_range here.  We are looking at a different object and checking whether the blob happens to be loaded.  If so, we unshare it and include it in the range.. but it only needs to be enough to ensure we write the shard for the blob we unshared.

Hmm, I think there is still a bug here, though.  You could have two shards in memory, say 0~0x80000 and 0x100000~0x80000, and unshare a blob in each of those, and end up with a range that covers the gap (0x80000~0x80000) which isn't loaded?

I think we should actually call dirty_range for each blob we unshare for exactly the range that it covers (or a subset of it--just enough to ensure we dirty the shard).

**Comment by xiexingguo** [comment]
> It's not directly related to fault_range here. We are looking at a different object and checking whether the blob happens to be loaded. If so, we unshare it and include it in the range.. but it only needs to be enough to ensure we write the shard for the blob we unshared.

Sorry, I didn't read the  original tracker carefully(it happens during BlueStore::_do_remove).



> Hmm, I think there is still a bug here, though. You could have two shards in memory, say 00x80000 and 0x1000000x80000, and unshare a blob in each of those, and end up with a range that covers the gap (0x80000~0x80000) which isn't loaded?

Exactly.



> I think we should actually call dirty_range for each blob we unshare for exactly the range that it covers (or a subset of it--just enough to ensure we dirty the shard).

Sounds reasonable.

**Comment by liewegas** [comment]
@xiexingguo updated!

**Comment by xiexingguo** [comment]
@liewegas  The change itself looks fine, but I get another question here:

```
  ghobject_t nogen = o->oid;
  nogen.generation = ghobject_t::NO_GEN;
  OnodeRef h = c->onode_map.lookup(nogen);

  if (!h || !h->exists) {
    return 0;
  }

  dout(20) << __func__ << " checking for unshareable blobs on " << h
	   << " " << h->oid << dendl;
  map<SharedBlob*,bluestore_extent_ref_map_t> expect;
  for (auto& e : h->extent_map.extent_map) {
```
I see we are directly looking up the head object from the cache and supposing its extent map is fully loaded(spanned) here. Is this always true? What if we fail?

**Comment by liewegas** [comment]
The loaded/unloaded state is a bit constrained at the moment.  We never trim extents from the map--we can only throw out the whole onode.  So shards are only loaded. Or loaded ones can be split or merged.  So if the extent is there its shard is loaded.

The blob might be a spanning a blob.  I don't think that matters, though (except we don't actually need to dirty the shard in that case).

**Comment by liewegas** [comment]
retest this please

**Comment by liewegas** [comment]
http://pulpito.ceph.com/sage-2017-08-06_16:51:13-rados-wip-sage-testing2-20170806a-distro-basic-smithi/

I don't think the ceph_test_objectstore failure is related, but I want to be sure first before merging this.

**Comment by xiexingguo** [comment]
> The loaded/unloaded state is a bit constrained at the moment. We never trim extents from the map--we can only throw out the whole onode. So shards are only loaded. Or loaded ones can be split or merged. So if the extent is there its shard is loaded.

@liewegas That's true. Thanks for the detailed explanation.
But lemme make myself a bit more clear here:

By rechecking the original logic of BlueStore::_do_remove:
(1) suppose we are currently deleting a gen object;
(2) we want to check if there is any shared blobs that we might be unable to unshare in the corresponding head object now. And if there is, mark it as unshared in the head object too.

Here comes my concern:
We are calling `c->onode_map.lookup(nogen);` instead of `c->get_onode(nogen, false); `here,
which means we check whether the head object has already been loaded into memory or not.
But what if it is not? Shouldn't we instead load the head object from disk and continue the
above check?

**Comment by xiexingguo** [comment]
> I don't think the ceph_test_objectstore failure is related,

Me neither :P

**Comment by liewegas** [comment]
I chose to be opportunistic.. if the nogen object is already in cache, unshare the blobs.  If not, don't slow things down by loading any new metadata.

I'm not sure that's the best choice but it seems reasonable.  Hard to tell whether to trade a metadata read now with paying the cost of loaded and then deleting the shared blob in the future (when the blob is eventually freed).  This optimization is really targeting EC pools that are cloning the overwritten range and then deleting it moments later, so for that case at least it will basically always be there.

**Comment by liewegas** [comment]
Yeah that csum crash trigger on two runs, one with this and one without this. Merging!

**Comment by xiexingguo** [comment]
Got it. Fine with me. @liewegas  Thanks for the explanation!

**Comment by liewegas** [comment]
/a/joshd-2017-08-04_06:16:52-rados-wip-20904-distro-basic-smithi/1482581 has the logs that led to diagnosis

**Pull request merged**
