### PR TITLE
mon/OSDMonitor: make pool app options configurable

### PR DESCRIPTION
**Pull request by xiexingguo**
To give user more flexible choices...

Signed-off-by: xie xingguo <xie.xingguo@zte.com.cn>

### CODE REVIEW

**Comment by xiexingguo** [comment]
retest this please

**Comment by dillaman** [comment]
@xiexingguo Keeping those values fixed was a conscience decision [1][2]

[1] http://pad.ceph.com/p/pool-metadata
[2] https://github.com/ceph/ceph/pull/15763/files#diff-0a5db46a44ae9900e226289a810f10e8R88

**Comment by xiexingguo** [comment]
> Keeping those values fixed was a conscience decision

I definitely understand the risk of inflating the osdmap size by abusing these options, but making these configurable instead of hardcoded could be useful...

E.g., we intend to leverage the pool application to store several large kvs(up to 1K) from higher layers,
but these hardcoded constraints will prevent us from doing this. 

In the above case we don't inflate the osdmap too much, and there are other user cases such as:

```
1024(kvs) * 16 (bytes per ky)
256 * 64
16 * 1KB
4 * 4KB 
...
```

IMHO, we should give more flexible choices to user otherwise this feature is going to have very limited value...

**Comment by dillaman** [comment]
I'll let a member of the core RADOS team decide -- from my point of view, it's already been decided upon.

**Comment by gregsfortytwo** [comment]
Sorry, we don't want you storing 1KB (or more) of data here. :) I'd recommend the configure-key interface on the monitor; it's designed for stuff like that...

**Comment by xiexingguo** [comment]
> I'd recommend the configure-key interface on the monitor; it's designed for stuff like that...

Ah, I'd love to give a try. What is that, then?

**Comment by gregsfortytwo** [comment]
you can invoke it via the CLI or programmatically: "ceph config-key {set|get|ls|dump}" etc

**Comment by xiexingguo** [comment]
> you can invoke it via the CLI or programmatically: "ceph config-key {set|get|ls|dump}" etc

Thanks, Greg. This works beautifully!

**Pull request closed without merging**
