### PR TITLE
quincy: common/admin_socket: add a command to raise a signal

### PR DESCRIPTION
**Pull request by leonid-s-usov**
Backport ticket: https://tracker.ceph.com/issues/63362
Original ticket: https://tracker.ceph.com/issues/63362
Original PR: https://github.com/ceph/ceph/pull/53689

---

The new command "raise <signal> [--after X]" accepts signals in the forms: '9', '-9', 'kill', '-KILL'
When --after is specified, the program will fork to wait for the timeout

The forked instance will bail out if it detects that the parent PID has changed which would indicate that the original parent has terminated.

Forking an instance allows to schedule delivery of signals even if the original process is suspended, e.g.:
```
  ceph tell mds.a raise CONT --after 10
  ceph tell mds.a raise STOP
```

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by leonid-s-usov** [comment]
jenkins test api

**Comment by vshankar** [comment]
@leonid-s-usov just confirming - this backport has fixes from https://github.com/ceph/ceph/pull/54451, yes?

**Comment by leonid-s-usov** [comment]
> @leonid-s-usov just confirming - this backport has fixes from #54451, yes?

That is correct. It's actually the other way around: #54451 has been created to apply the changes that were implemented in these backports

**Comment by lxbsz** [comment]
This PR is under test in [https://tracker.ceph.com/issues/67315](https://tracker.ceph.com/issues/67315).

**Review by rzarzynski — APPROVED** [review]

**Comment by amathuria** [comment]
Rados approved - https://tracker.ceph.com/projects/rados/wiki/QUINCY#httpstrackercephcomissues68435

**Pull request merged**
