### PR TITLE
doc: Update manual deployment

### PR DESCRIPTION
**Pull request by jharbott**
Fixes: http://tracker.ceph.com/issues/20309
Signed-off-by: Jens Rosenboom <j.rosenboom@x-ion.de>

### CODE REVIEW

**Comment by liewegas** [comment]
sorry i missed this earlier!  needs rebase?

**Comment by alfredodeza** [comment]
jenkins test docs

**Comment by tchaikov** [comment]
@jharbott ping?

**Comment by jharbott** [comment]
Sorry this got dropped from my radar, rebased version upcoming

**Pull request merged**
