### PR TITLE
reef: qa: ignore container checkpoint/restore related selinux denials for centos9

### PR DESCRIPTION
**Pull request by vshankar**
backport tracker: https://tracker.ceph.com/issues/64756

---

backport of https://github.com/ceph/ceph/pull/55908
parent tracker: https://tracker.ceph.com/issues/64616

this backport was staged using ceph-backport.sh version 16.0.0.6848
find the latest version at https://github.com/ceph/ceph/blob/main/src/script/ceph-backport.sh

### CODE REVIEW

**Comment by leonid-s-usov** [comment]
jenkins test make check

**Comment by leonid-s-usov** [comment]
jenkins test make check

**Comment by leonid-s-usov** [comment]
jenkins test make check

**Comment by joscollin** [comment]
jenkins test make check

**Comment by joscollin** [comment]
Tested in https://tracker.ceph.com/issues/66511

**Review by joscollin — APPROVED** [review]

**Comment by cbodley** [comment]
these commits were cherry-picked to reef-release to resolve conflicts with https://github.com/ceph/ceph/pull/57932

**Pull request merged**
