### PR TITLE
cephadm: update shared folder python packages dir

### PR DESCRIPTION
**Pull request by nizamial09**
after centos9 our python version is 3.9 so shouldn't we use the python3.9 path instead of python3.6?

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Comment by nizamial09** [comment]
Seen more instances in 
https://github.com/ceph/ceph/blob/main/qa/run-standalone.sh#L21
https://github.com/ceph/ceph/blob/main/src/ceph-volume/ceph_volume/tests/functional/playbooks/deploy.yml#L111

But wanted @guits and @tchaikov 's opinion before doing that.

**Comment by nizamial09** [comment]
https://tracker.ceph.com/issues/66903

**Review by phlogistonjohn — APPROVED** [review]
I think this is fine. One thing to note is that cephadm can run on a wide variety of distros and python versions so a single python version can never be "right". However, for the one of our most widely used distros for development this is a good update and no worse than before.

**Review by adk3798 — APPROVED** [review]

**Comment by nizamial09** [comment]
@adk3798 shall we merge this?

**Comment by adk3798** [comment]
https://pulpito.ceph.com/adking-2024-07-23_15:55:03-orch:cephadm-wip-adk-testing-2024-07-19-0851-distro-default-smithi/

Failures:

- staggered upgrade mismatch between `ceph orch ps` and `ceph versions`, known issue
- thrash and rgw-ingress tests timing out, known issue
- mds_upgrade_sequence failure, known issue
- cephadm task test was actually related to a specific PR in the run

Nothing to block merging for all PRs except the one causing the cephadm task failure (not this PR if you see this comment)

**Comment by afreen23** [comment]
@nizamial09  should we backport this to squid ?
I can see we have similar errors due this in bootstrapping cephadm cc @rkachach 
https://jenkins.ceph.com/job/ceph-dashboard-cephadm-e2e/12339/consoleFull#-845242084b0cfa0c-a892-49e0-a359-82544e1a192e

Thanks

**Comment by adk3798** [comment]
> @nizamial09 should we backport this to squid ? I can see we have similar errors due this in bootstrapping cephadm cc @rkachach https://jenkins.ceph.com/job/ceph-dashboard-cephadm-e2e/12339/consoleFull#-845242084b0cfa0c-a892-49e0-a359-82544e1a192e
> 
> Thanks

in theory this needs to be backported everywhere where we'll be using centos 9 as the container image base. I know that is the case for squid and also the most recent reef release. I'm unsure when it comes to quincy what the plan is as there was some pushback on the move from centos 8 -> 9 with the most recent reef release.

**Comment by nizamial09** [comment]
thanks @adk3798 and @afreen23. opened the backports for squid and reef for now. in reef there was a minor conflict because of the in-existence of cephadmlib, but addressed those.

**Comment by rkachach** [comment]
> @nizamial09 should we backport this to squid ? I can see we have similar errors due this in bootstrapping cephadm cc @rkachach https://jenkins.ceph.com/job/ceph-dashboard-cephadm-e2e/12339/consoleFull#-845242084b0cfa0c-a892-49e0-a359-82544e1a192e
> 
> Thanks

@afreen23 we clarified in slack the reason behind the error. At this moment the `mgmt-gatewa` feature is only on main so you shouldn't see any related error in squid branch :+1:

**Pull request merged**
