### PR TITLE
msg/async: crash in the case STATE_OPEN_MESSAGE_READ_DATA

### PR DESCRIPTION
**Pull request by shenhang**
Fixes: http://tracker.ceph.com/issues/37431
Signed-off-by: Shen Hang <harryshen18@gmail.com>

- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by shenhang** [comment]
@smithfarm @rjfd @ukernel @tchaikov 
pls have a look here.

**Comment by rjfd** [comment]
@shenhang @tchaikov I found this related PR #24466 where @tchaikov  states that this problem only occurs in versions prior to luminous. @tchaikov has this changed?

**Comment by shenhang** [comment]
@rjfd @tchaikov @ukernel @smithfarm . how about adding a function advance(unisigned int) in common/buffer.cc.
   void buffer::list::iterator::advance(unsigned int o)
  {
    buffer::list::iterator_impl<false>::advance(o);
  }
  template<bool is_const>
  void buffer::list::iterator_impl<is_const>::advance(unsigned int o)
  {
    //cout << this << " advance " << o << " from " << off << " (p_off " << p_off << " in " << p->length() << ")" << std::endl;
    const unsigned max_adv = std::numeric_limits<int>::max();
    assert(o <= max_adv - p_off);
    assert(o <= max_adv - off);
    if (o > 0) {
      p_off += o;
      while (p_off > 0) {
        if (p == ls->end())
          throw end_of_buffer();
        if (p_off >= p->length()) {
          // skip this buffer
          p_off -= p->length();
          p++;
        } else {
          // somewhere in this buffer!
          break;
        }
      }
      off += o;
    }
    return;
  }

**Comment by tchaikov** [comment]
@rjfd no. this hasn't changed. the fix of http://tracker.ceph.com/issues/16164 is 60af83c80910070d8fb10ac7a4f6f24d49521c1b , and all branches after jewel contain it
```
$ git br --contains 60af83c80910070d8fb10ac7a4f6f24d49521c1b|grep -v wip
  luminous
* master
  mimic
  nautilus
```

the PR (https://github.com/ceph/ceph/pull/24466) connected with http://tracker.ceph.com/issues/36340 merely adds an `assert()`.

@shenhang i'd suggest you retry with branch with 60af83c80910070d8fb10ac7a4f6f24d49521c1b to see if it fixes your issue.

**Comment by shenhang** [comment]
> @rjfd no. this hasn't changed. the fix of http://tracker.ceph.com/issues/16164 is [60af83c](https://github.com/ceph/ceph/commit/60af83c80910070d8fb10ac7a4f6f24d49521c1b) , and all branches after jewel contain it
> 
> ```
> $ git br --contains 60af83c80910070d8fb10ac7a4f6f24d49521c1b|grep -v wip
>   luminous
> * master
>   mimic
>   nautilus
> ```
> the PR (#24466) connected with http://tracker.ceph.com/issues/36340 merely adds an `assert()`.
> 
> @shenhang i'd suggest you retry with branch with [60af83c](https://github.com/ceph/ceph/commit/60af83c80910070d8fb10ac7a4f6f24d49521c1b) to see if it fixes your issue.

 The related issue was found on luminous, which contains this commit.

**Comment by tchaikov** [comment]
> how about adding a function advance(unisigned int) in common/buffer.cc.

@shenhang i think it's a bug in libcephfs, and we should not cover it in this way.

**Comment by shenhang** [comment]
> > how about adding a function advance(unisigned int) in common/buffer.cc.
> 
> @shenhang i think it's a bug in libcephfs, and we should not cover it in this way.

I think this should be corrected on both side. For server side, It is no doubt Ceph is targeted for production use, so it is necessary for mds to enhance its self-robustness to adjust to all kinds of client released before. On the other hand, I really don't think it is proper to change type without overflow check. :)

**Comment by gregsfortytwo** [comment]
Hmm, I'm confused. Is the invocation of ```advance()``` really the part where it goes wrong? We have several other ```unsigned``` variables involved prior to that. If there's an integer overflow it looks like other stuff must have broken prior to us calling ```advance()```, just perhaps not in a way that causes a crash.

That said, this general issue does seem like something we need to fix — we don't want a malicious client to be able to crash Ceph daemons just by connecting and claiming to have a very large message that needs to be prepared!

**Pull request closed without merging**
