### PR TITLE
qa: check immutable object cache content

### PR DESCRIPTION
**Pull request by CongMinYin**
Fixes: qa test cannot correctly detect that immutable object cache is not working

Signed-off-by: Yin Congmin <congmin.yin@intel.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by CongMinYin** [comment]
Hi @dillaman , immutable object cache still  doesn't work now. The problem that I reported two weeks ago that the plug-in could not load the cache correctly was not actually completely resolved, but QA cann't detected. Because the ceph and qa didn't  report an error, but the cache actually does not work properly. There is no data in the cache directory. This PR detects whether there is data in the cache directory after qa test. If not, the cache does not work properly.
There are two situations that QA test cann't detected at present:
1. Parent cache is skipped when the daemon is not started (similar to thrash)
2. Parent cache started, but date can't be cached.

bug link：https://tracker.ceph.com/issues/46916
fix pr link: https://github.com/ceph/ceph/pull/36802

**Review by dillaman — APPROVED** [review]
lgtm -- but if the cache is still broken right now won't this test just fail?

**Comment by CongMinYin** [comment]
> lgtm -- but if the cache is still broken right now won't this test just fail?

The current test will not fail. If this PR is applied, it will fail because there is no data in the cache directory.

**Comment by dillaman** [comment]
> The current test will not fail. If this PR is applied, it will fail because there is no data in the cache directory.

Yes, I understand that part. I am asking if the cache is actually working right now (i.e. will this change to the test find files in the cache after it has run) or will it fail because the cache is not working?

**Comment by CongMinYin** [comment]
> > The current test will not fail. If this PR is applied, it will fail because there is no data in the cache directory.
> 
> Yes, I understand that part. I am asking if the cache is actually working right now (i.e. will this change to the test find files in the cache after it has run) or will it fail because the cache is not working?

After the end of the test to find out whether the cache file exists. It is in finally part and just before cleanning.

**Comment by dillaman** [comment]
The test is currently failing:

http://qa-proxy.ceph.com/teuthology/jdillaman-2020-09-17_15:06:37-rbd-wip-jd-testing-2-distro-basic-smithi/5443948/teuthology.log

**Comment by CongMinYin** [comment]
> The test is currently failing:
> 
> http://qa-proxy.ceph.com/teuthology/jdillaman-2020-09-17_15:06:37-rbd-wip-jd-testing-2-distro-basic-smithi/5443948/teuthology.log

The test should fail because the current cache is doesn't work. The previous problem that plugin failed to load the parent cache has not been solved completely(https://tracker.ceph.com/issues/46916), just no error reported. The parent cache does not work in my manual test(no cache data). This command of PR is just to detect this situation. Could  you please take a look: can the plugin load parent cache? Or are the hook related codes incorrectly modified, causing the parent cache to fail to get the request?

**Comment by dillaman** [comment]
The test failed because the cache directory was never created. I think the teuthology task needs to actually create the directory prior to starting the test.

**Comment by CongMinYin** [comment]
> The test failed because the cache directory was never created. I think the teuthology task needs to actually create the directory prior to starting the test.

sorry, 

> The test failed because the cache directory was never created. I think the teuthology task needs to actually create the directory prior to starting the test.

Sorry, it's just that I didn't use Raw() when passing the command, and it turned into a pure character. Now it is OK.  

In addition, when creating an image, the parameter  "--thick provision" must be added (previously it seems unnecessary), which led me to think that cache does not work. I'm very sorry.

**Comment by dillaman** [comment]
jenkins test api

**Comment by dillaman** [comment]
@ceph/dashboard FYI -- RGW API test is failing

**Comment by dillaman** [comment]
jenkins test api

**Pull request merged**
