### PR TITLE
os/bluestore: use single allocator for shared bluestore/bluefs device

### PR DESCRIPTION
**Pull request by ifed01**
Smoke benchmarking results can be found at:
https://docs.google.com/spreadsheets/d/1RulvKovOM1V8X1GwLryzpJWVbxihXAI0WObhjh_PgPI/edit?usp=sharing
In short - no substantial difference in performance has been observed.

Signed-off-by: Igor Fedotov <ifedotov@suse.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`

</details>

### CODE REVIEW

**Comment by liewegas** [comment]
Overall this looks good.. love to see so much code removed!  Let's see how this does in qa

**Comment by ifed01** [comment]
jenkins retest this please

**Comment by liewegas** [comment]
http://pulpito.ceph.com/sage-2019-10-10_19:32:04-rados-wip-sage3-testing-2019-10-10-0958-distro-basic-smithi/

**Comment by ifed01** [comment]
@liewegas - I've fixed relevant failures in StupidAllocator, please rerun QA.

**Comment by tchaikov** [comment]
- http://pulpito.ceph.com/kchai-2019-10-17_15:27:09-rados-wip-kefu-testing-2019-10-15-1130-distro-basic-mira/
- http://pulpito.ceph.com/kchai-2019-10-15_09:41:56-rados-wip-kefu-testing-2019-10-15-1130-distro-basic-mira/

@ifed01 i found that you updated this PR after i picked up your change in my test batch. shall we rerun the qa suite?

**Comment by ifed01** [comment]
> * http://pulpito.ceph.com/kchai-2019-10-17_15:27:09-rados-wip-kefu-testing-2019-10-15-1130-distro-basic-mira/
> * http://pulpito.ceph.com/kchai-2019-10-15_09:41:56-rados-wip-kefu-testing-2019-10-15-1130-distro-basic-mira/
> 
> @ifed01 i found that you updated this PR after i picked up your change in my test batch. shall we rerun the qa suite?

@tchaikov - yes, please rerun

**Comment by tchaikov** [comment]
- http://pulpito.ceph.com/kchai-2019-10-18_15:55:07-rados-wip-kefu-testing-2019-10-18-1835-distro-basic-mira/
- http://pulpito.ceph.com/kchai-2019-10-20_02:57:03-rados-wip-kefu-testing-2019-10-18-1835-distro-basic-mira/
- http://pulpito.ceph.com/kchai-2019-10-20_12:50:42-rados-wip-kefu-testing-2019-10-18-1835-distro-basic-mira/

librbd failures tracked by https://tracker.ceph.com/issues/42384

**Comment by tchaikov** [comment]
@liewegas ping?

**Comment by markhpc** [comment]
@ifed01 We still need to quantify where this isn't playing well with a 4K min alloc size right?

**Comment by ifed01** [comment]
> @ifed01 We still need to quantify where this isn't playing well with a 4K min alloc size right? (Based on update in standup this morning?)

@markhpc - right. There are some performance gaps when both single allocator and 4K alloc unit are used together, see last two columns here:
https://docs.google.com/spreadsheets/d/1xXbheoGwgyaLBc389TFo1vUyz9LjshI83_bW8zBYWl8/edit?usp=sharing

These results are a bit out of date? I've partially improved these numbers but doing sharding inside bitmap allocator but some perf regression is still there in some scenarios...

**Comment by liewegas** [comment]
```
teuthology:4455660  10:17 PM $ tail -n 1 teuthology.log 
2019-10-30T14:45:28.678 INFO:teuthology.orchestra.run.smithi155.stdout:[ RUN      ] ObjectStore/StoreTest.ColSplitTest0/2
teuthology:4455660  10:17 PM $ date
Wed Oct 30 22:17:43 UTC 2019
```

**Comment by liewegas** [comment]
```
  -507> 2019-10-30T15:34:51.477+0000 7fb5f96f9700 -1 bluestore(/var/lib/ceph/osd/ceph-8) _verify_csum bad crc32c/0x1000 checksum at blob offset 0x0, got 0xf5ef4c77, expected 0xcdf86c77, device location [0x510000~1000], logical extent 0x3a~1000, object #-1:46e858f0:::pg_num_history:head#
  -506> 2019-10-30T15:34:51.477+0000 7fb5f96f9700 -1 bluestore(/var/lib/ceph/osd/ceph-8) _verify_csum bad crc32c/0x1000 checksum at blob offset 0x0, got 0xf5ef4c77, expected 0xcdf86c77, device location [0x510000~1000], logical extent 0x3a~1000, object #-1:46e858f0:::pg_num_history:head#
  -505> 2019-10-30T15:34:51.478+0000 7fb5f96f9700 -1 bluestore(/var/lib/ceph/osd/ceph-8) _verify_csum bad crc32c/0x1000 checksum at blob offset 0x0, got 0xf5ef4c77, expected 0xcdf86c77, device location [0x510000~1000], logical extent 0x3a~1000, object #-1:46e858f0:::pg_num_history:head#
```
on another test.. maybe not related though?  captured log at /a/sage-2019-10-30_13:15:04-rados-wip-sage-testing-2019-10-29-2112-distro-basic-smithi/4455702/ceph-osd.8.log

**Comment by ifed01** [comment]
@liewegas - does the presence of https://tracker.ceph.com/issues/42712 mean that your comment above about failing ColSplitTest0/2 is irrelevant?

**Comment by liewegas** [comment]
> @liewegas - does the presence of https://tracker.ceph.com/issues/42712 mean that your comment above about failing ColSplitTest0/2 is irrelevant?

Yeah, just hit this on a run without this PR.

**Comment by liewegas** [comment]
http://pulpito.ceph.com/sage-2019-11-30_15:43:29-rados-wip-sage3-testing-2019-11-22-1124-distro-basic-smithi/

There's an issue here somewhere... 11 dead jobs.  i don't see a stack trace, so there's a hang or something.

**Comment by xiexingguo** [comment]
@ifed01 Can you rebase?

**Comment by huangwei04** [comment]
@ifed01 hi, I want to test the effect of this commit, can you complete it, please？

**Comment by ifed01** [comment]
@xiexingguo, @huangwei04 - rebased and ready for QA

**Comment by tchaikov** [comment]
- https://pulpito.ceph.com/kchai-2020-08-02_10:33:38-rados-wip-kefu-testing-2020-08-02-1650-distro-basic-smithi/
- https://pulpito.ceph.com/kchai-2020-08-03_03:37:05-rados-wip-kefu-testing-2020-08-03-0931-distro-basic-smithi/

**Pull request merged**
