### PR TITLE
crimson/os/seastore: return future when no element error tolerated

### PR DESCRIPTION
**Pull request by rosinL**
OP_REMOVE etc ops will tolerate absent onode, we need return
ready future to chain the continuation, otherwise it will cause
a segmentation fault.

Signed-off-by: luo rixin <luorixin@huawei.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [x] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by rosinL** [comment]
jenkins retest this please

**Comment by cyx1231st** [comment]
Is this also a potential segmentation fault code?

https://github.com/ceph/ceph/blob/8cb32e9c502ea98ab2754318e155b9ce0d99cbe1/src/crimson/os/seastore/transaction_manager.cc#L624-L626

**Review by cyx1231st — APPROVED** [review]

**Comment by rosinL** [comment]
> Is this also a potential segmentation fault code?
> 
> https://github.com/ceph/ceph/blob/8cb32e9c502ea98ab2754318e155b9ce0d99cbe1/src/crimson/os/seastore/transaction_manager.cc#L624-L626

yes, I think there is.

**Comment by cyx1231st** [comment]
jenkins test api

**Pull request merged**
