### PR TITLE
pacific: cephadm: specify addr on bootstrap's host add

### PR DESCRIPTION
**Pull request by jecluis**
Signed-off-by: Joao Eduardo Luis \<joao@suse.com>
(cherry picked from commit df13888255e47ad2c66fa8da11f0e9e4ef624071)

### CODE REVIEW

**Review by mgfritch — APPROVED** [review]

**Comment by liewegas** [comment]
jenkins test make check

**Comment by liewegas** [comment]
```
	210 - unittest-seastore-cache (Failed)
	213 - unittest-staged-fltree (Failed)
```

**Comment by liewegas** [comment]
170/214 Test #210: unittest-seastore-cache ...................***Failed    1.25 sec
WARNING: debug mode. Not for benchmarking or production
ERROR 2021-04-02 15:05:22,123 [shard 0] seastar - Could not setup Async I/O: Resource temporarily unavailable. The most common cause is not enough request capacity in /proc/sys/fs/aio-max-nr. Try increasing that number or reducing the amount of logical CPUs available for your applicationERROR 2021-04-02 15:05:22,123 [shard 44] seastar - Could not setup Async I/O: Resource temporarily unavailable. The most common cause is not enough request capacity in /proc/sys/fs/aio-max-nr. Try increasing that number or reducing the amount of logical CPUs available for your application

**Comment by liewegas** [comment]
jenkins test make check

**Comment by liewegas** [comment]
jenkins test make check

**Pull request merged**
