### PR TITLE
rgw: fix rados bucket merge and store attrs

### PR DESCRIPTION
**Pull request by lightmelodies**
The original code pass `new_attrs` as argument, which will overwrite existing attrs. (e.g. set bucket ratelimit will break all bucket policy and acl settings)

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [x] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Review by dang — APPROVED** [review]

**Comment by mattbenjamin** [comment]
this seems potentially very significant @adamemerson @cbodley ?

**Comment by cbodley** [comment]
this failed qa by causing some s3test failures (`test_set_cors`, `test_set_bucket_tagging`, `test_delete_bucket_encryption_kms`). in each case, it appears that the bucket operations to delete the policy failed to remove the corresponding xattr (`delete_bucket_cors()`, `delete_bucket_tagging()`, `delete_bucket_encryption()`), so the policy was still visible afterwards

see logs in http://qa-proxy.ceph.com/teuthology/cbodley-2023-09-18_21:11:42-rgw-wip-cbodley-testing-distro-default-smithi/7397756/teuthology.log

**Comment by lightmelodies** [comment]
> this failed qa by causing some s3test failures (`test_set_cors`, `test_set_bucket_tagging`, `test_delete_bucket_encryption_kms`). in each case, it appears that the bucket operations to delete the policy failed to remove the corresponding xattr (`delete_bucket_cors()`, `delete_bucket_tagging()`, `delete_bucket_encryption()`), so the policy was still visible afterwards
> 
> see logs in http://qa-proxy.ceph.com/teuthology/cbodley-2023-09-18_21:11:42-rgw-wip-cbodley-testing-distro-default-smithi/7397756/teuthology.log

Indeed, these `delete*` functions mistakenly use `merge_and_store_attrs` and behave correctly due to the bug.

https://github.com/ceph/ceph/blob/e068b2aabd46f935333603625de762e9b1be3d2b/src/rgw/rgw_op.cc#L1242-L1262

**Comment by lightmelodies** [comment]
Set bucket ratelimit should be the only affected case now(which we encountered in our production cluster), other op constructs new_attr with  s->bucket->get_attrs() and get right result coincidentally. Anyway, the current merge behavior is wrong. I'll make a full check later.

**Comment by smanjara** [comment]
unstale

**Comment by lightmelodies** [comment]
I'm doubting whether `merge_and_store_attrs` is useful since it can not handle key deletion. In all cases except rate limit we just copy the old attrs, modify and `mistakenly` merged it. Why not directly operating on reference returned by `bucket->get_attrs()`?

**Pull request closed without merging**
