### PR TITLE
mimic: common: (mon) command sanitization accepts floats when Int type is defined resulting in exception fault in ceph-mon

### PR DESCRIPTION
**Pull request by pdvian**
http://tracker.ceph.com/issues/26918

### CODE REVIEW

**Comment by pdvian** [comment]
@liewegas Need review.

**Comment by smithfarm** [comment]
Note to reviewer: conflict resolution

**Comment by neha-ojha** [comment]
https://github.com/ceph/ceph/pull/23557 has been merged, we can proceed with the backport.

**Comment by yuriw** [comment]
[wip-yuri3-testing-2018-10-02-1639-mimic](https://trello.com/c/aDL8Gcgu/427-wip-yuri3-testing-2018-10-02-1639-mimic)

**Comment by smithfarm** [comment]
@theanalyst @yuriw I thought the idea here was to cherry-pick all the commits from https://github.com/ceph/ceph/pull/23557 into this PR.

**Comment by liewegas** [comment]
I'm okay with the partial backport.. the second round of commits were cleaning up the approach but i think the minimal backport is a bit less risky

**Comment by smithfarm** [comment]
Thanks for the clarification, @liewegas 

@yuriw It sounds like this can be merged if it passed the integration test run you cited above in comment https://github.com/ceph/ceph/pull/23644#issuecomment-426345263 ?

**Comment by neha-ojha** [comment]
http://pulpito.ceph.com/yuriw-2018-10-02_20:14:35-rados-wip-yuri3-testing-2018-10-02-1639-mimic-distro-basic-smithi/
http://pulpito.front.sepia.ceph.com/yuriw-2018-10-04_03:45:35-rados-wip-yuri3-testing-2018-10-02-1639-mimic-distro-basic-smithi/

The above runs of this PR saw failures like
`2018-10-03T13:19:02.979 INFO:tasks.ceph.mon.b.smithi075.stderr:2018-10-03 13:19:02.986 7f8bb1658700 -1 bad boost::get: key val is not type std::string` in http://pulpito.ceph.com/yuriw-2018-10-02_20:14:35-rados-wip-yuri3-testing-2018-10-02-1639-mimic-distro-basic-smithi/3094983/.

Could these be related?

**Comment by liewegas** [comment]
definitely

**Comment by smithfarm** [comment]
Failed integration tests. Back to the drawing board.

**Pull request closed without merging**
