### PR TITLE
client: bypass objectcacher for direct IO

### PR DESCRIPTION
**Pull request by ukernel**
Fixes: #13569
Signed-off-by: Yan, Zheng <zyan@redhat.com>

### CODE REVIEW

**Comment by gregsfortytwo** [comment]
@ukernel, this looks good to me but we need a test exercising it and demonstrating that it works.

**Comment by gregsfortytwo** [comment]
Between http://pulpito.ceph.com/gregf-2016-01-12_23:23:33-fs-greg-fs-testing-1-12-1---basic-mira/ and http://pulpito.ceph.com/gregf-2016-01-13_16:11:43-fs-greg-fs-testing-1-12-2---basic-mira/ I think we're in good shape here.

**Comment by Sebastiaan-Alvarez-Rodriguez** [comment]
Hi there,

Thanks a lot for implementing support for direct I/O!
I tried to enable direct I/O by executing:
```bash
sudo ceph-fuse /mnt/cephfs -o direct_io
```
Too bad, it does not work:
```
ceph-fuse[460920]: starting ceph client2021-06-11T07:01:21.520-0600 7fd13ae80080 -1 init, newargv = 0x562c81a9e910 newargc=11

fuse: unknown option `direct_io'
ceph-fuse[460920]: fuse failed to start
2021-06-11T07:01:21.536-0600 7fd13ae80080 -1 fuse_lowlevel_new failed
```
I guess this makes sense, because *"The '-o direct_io' mount option is only supported on the high level
interface, and only for backward compatibility."* [[1](http://fuse.996288.n3.nabble.com/fuse-devel-How-do-I-force-direct-io-tp2700p2701.html)].
Could you provide information on how to enable direct I/O when mounting `CephFS`?

Sidenotes:
 1. Mounting CephFS works fine when not trying to enablde direct I/O from the CLI.
 2. `ceph-fuse -V` returns `FUSE library version: 2.9.9`.
 
Places I searched before asking:
 1. https://docs.ceph.com/en/latest/cephfs/mount-using-fuse/
 2. https://docs.ceph.com/en/latest/man/8/ceph-fuse/
 3. https://docs.ceph.com/en/latest/man/8/mount.ceph/
 4. https://docs.ceph.com/en/latest/man/8/mount.fuse.ceph/
 5. http://fuse.996288.n3.nabble.com/fuse-devel-How-do-I-force-direct-io-td2700.html
 6. The Ceph source code: https://github.com/ceph/ceph/blob/8273a96198cc7fc488135649369229fbf69bd860/src/client/fuse_ll.cc#L657-L658 Sadly, I could not find out how to trigger that bit of code.

Any pointers/help/ideas would be greatly appreciated!

**Comment by tchaikov** [comment]
https://github.com/ceph/ceph/blob/8273a96198cc7fc488135649369229fbf69bd860/src/client/fuse_ll.cc#L652-L661

@Sebastiaan-Alvarez-Rodriguez i am far from an expert of cephfs, but by inspecting the code, i think the way to trigger it would be to add
```ini
fuse_disable_pagecache = true
```
to ceph.conf.

also, i am afraid that commenting on a merged PR might not be the most efficient way to ask for help -- you might want to drop a message to the mailing list.

**Comment by Sebastiaan-Alvarez-Rodriguez** [comment]
Hey there,
thanks for your quick reply!
After setting this option in `/etc/ceph/ceph.conf` on every client node, CephFS becomes [40-50]% slower. So, it works, excellent.

For other issues, I'll use the mailng list.
Have a nice day!

**Pull request merged**
