### PR TITLE
ceph-create-keys: deprecate, print warning

### PR DESCRIPTION
**Pull request by liewegas**
We'll remove this post-mimic, I guess?

Merge this with/after https://github.com/ceph/ceph/pull/21236

### CODE REVIEW

**Comment by liewegas** [comment]
Hi @alfredodeza, the mons now (on their own) do all the key generation that ceph-create-keys used to do, so on that level this tool is obsolete.  But there are 2 other things:

1. This would wait for a quorum, so a caller might have some timing dependency when running this?
2. This would also write the bootstrap keys out to /var/lib/ceph/ on the local host.  The mons obviously don't do that automatically.

Do you mind checking whether there is an opportunity to remove the dependency on this in ceph-ansible?

**Comment by alfredodeza** [comment]
There is currently one place in ceph-ansible where this happens, and it is only done when deploying monitors (on monitor hosts only I believe).

If I understand #21236 correctly, then we wouldn't have a problem here. @leseb @guits you guys might be interested in taking a look!

**Comment by leseb** [comment]
@liewegas when you say:

> This would also write the bootstrap keys out to /var/lib/ceph/ on the local host. The mons obviously don't do that automatically.

Let me know if I understood that correctly. Once the mons are in quorum, the keys will be created and written on `/var/lib/ceph/` (bootstrap keys). What about the admin key? Is it also created and put in `/etc/ceph/`?

I guess ceph-ansible will have to watch and wait for these keys to be created after the mon service starts.

Thanks!

**Comment by liewegas** [comment]
No.. the mon will generate the keys but they'll just exist in the mon's internal db.  ceph-create-keys would also write them to the local host... so that's the change we need to deal with in ceph-ansible and ceph-deploy (and whatever else).  e.g., replacing it with calls to 'ceph auth get ...' or whatever for the specific keys ansible wants/needs.

This doesn't have to happen for mimic; ceph-create-keys will contnue to behave as before (it will just be fetching rather then creating keys), but it would be nice to sort this out so that the script can be removed in the future (or perhaps replaced by something simpler).

**Comment by leseb** [comment]
Alright so we just need to:

* stop calling the script `ceph-create-keys`
 * add a bunch of tasks `ceph auth get-create`

Thanks!

**Comment by leseb** [comment]
@liewegas one more thing, does that mean we should use the initial mon key `mon.` to fetch the key in the first place? We don't have the admin key so we can't do `ceph auth get-or-create` :).

Thanks!

**Comment by liewegas** [comment]
Yeah, use mon. to get client.admin.

It's also possible to pre-create client.admin and feed it to the initial mons, but I think it's easier to maintain if we extract it after mons form quorum.

**Comment by smithfarm** [comment]
@liewegas Rebase?

**Comment by jdurgin** [comment]
Is this ready to go now that we're post-mimic?

**Comment by liewegas** [comment]
I can't decide.  Even tho the mon now creates the keys, this script also writes out the keys to the local host's /etc/ceph/ceph.client.admin.keyring and /var/lib/ceph/boostrap-*.  I suspect all of the ansible/salt/etc tooling relies on that.  If we remove it we'll need to patch each of those to (1) not run this and (2) run ceph auth export whatever to get the keys they want.  I think I'm fine with that, but I'd like confirmation from @leseb and others that it's okay?

**Comment by smithfarm** [comment]
@liewegas afaict Salt/DeepSea will not use ceph-create-keys to deploy/manage Nautilus clusters.

@jschmid1 @tserong Correct?

**Comment by leseb** [comment]
@liewegas @jdurgin we haven't had the time to start this yet. So the procedure we will be to use the `mon.` key and `ceph -n mon. -k /var/lib/ceph/mon/ceph-mon0/keyring  auth get client.admin -o client.admin`  all the keys right?
Thanks!

**Comment by liewegas** [comment]
@leseb right

**Comment by tserong** [comment]
> @liewegas afaict Salt/DeepSea will not use ceph-create-keys to deploy/manage Nautilus clusters.
> 
> @jschmid1 @tserong Correct?

Yep. AFAIK DeepSea actually never used ceph-create-keys.

**Comment by smithfarm** [comment]
jenkins re-test this please

**Comment by tchaikov** [comment]
http://pulpito.ceph.com/kchai-2018-12-06_14:36:33-rados-wip-kefu2-testing-2018-12-06-1345-distro-basic-smithi/

the leak is tracked by http://tracker.ceph.com/issues/20491

**Comment by liewegas** [comment]
The problem is that I suspect some (many?) tools still use this as a way to get the admin and bootstrap keys on the current node.  If we merge then, we'll force them to fix things for nautilus.

I'm good with just, but I want to make sure everyone is on board with that plan!  Looks like ceph-ansible already made the change.

**Comment by liewegas** [comment]
rebased.

**Comment by smithfarm** [comment]
@liewegas Given that ceph-ansible and DeepSea are safe, what other tools out there might be at risk?

**Comment by smithfarm** [comment]
Maybe add a PendingReleaseNote ?

**Comment by liewegas** [comment]
puppet maybe?  good to hear that deepsea is ready to go.  @dvanders fyi!

**Comment by liewegas** [comment]
Updated the release not to call out the writing of local keys.

**Comment by dvanders** [comment]
Thx for the ping. We don't use ceph-create-keys so we'll only need to update our cluster bootstrap procedure.

**Pull request merged**
