### PR TITLE
cmake: add common-options-objs as a dependency of common-msg-objs, rados_snap_set_diff_obj and krbd

### PR DESCRIPTION
**Pull request by peeweep**
This PR fixes two compilation issues with `common-options-objs`, found on Gentoo.

1. https://bugs.gentoo.org/866449
  `src/msg/Messenger.h:723:30: error: ‘class ConfigValues’ has no member named ‘ms_die_on_unhandled_msg’`

2. https://bugs.gentoo.org/868891
  `global_legacy_options.h: No such file or directory`
```
                 from /var/tmp/portage/sys-cluster/ceph-17.2.5-r1/work/ceph-17.2.5/src/librados/snap_set_diff.cc:7:
/var/tmp/portage/sys-cluster/ceph-17.2.5-r1/work/ceph-17.2.5/src/common/options/legacy_config_opts.h:1:10: fatal error: global_legacy_options.h: No such file or directory

                 from /var/tmp/portage/sys-cluster/ceph-17.2.5-r1/work/ceph-17.2.5/src/krbd.cc:44:
/var/tmp/portage/sys-cluster/ceph-17.2.5-r1/work/ceph-17.2.5/src/common/options/legacy_config_opts.h:1:10: fatal error: global_legacy_options.h: No such file or directory
```

Add common-options-objs as a dependency of common-msg-objs, rados_snap_set_diff_obj and krbd to fix them.

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [x] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by peeweep** [comment]
Should I use `target_link_libraries(rados_snap_set_diff_obj $<TARGET_OBJECTS:common-options-objs>)` better in [80e4222](https://github.com/ceph/ceph/pull/49517/commits/80e422234acb1f8ffcbe8ee3898cb00f889466a3) ?
I've tried both target_link_libraries and add_dependencies, and the effect is the same.

**Comment by peeweep** [comment]
The error reported by `make check` and `ceph windows tests` does not seem to be introduced by my modification, I just added some dependencies.

make check error:
```
bluestore(td/smoke/1/block) _read_bdev_label failed to open td/smoke/1/block: (2) No such file or directory
bluestore(td/smoke/1/block) _read_bdev_label failed to open td/smoke/1/block: (2) No such file or directory
bluestore(td/smoke/1/block) _read_bdev_label failed to open td/smoke/1/block: (2) No such file or directory
```

**Comment by rzarzynski** [comment]
jenkins retest this please

**Comment by rzarzynski** [comment]
(Please also note Gentoo isn't a supported platform)

**Comment by thesamesam** [comment]
> (Please also note Gentoo isn't a supported platform)

We know, but I feel like this isn't a very constructive comment when we've provided a PR to fix it. This isn't a Gentoo-exclusive bug or anything. I've been happy to provide patches whenever I hit issues involving Ceph, as have the other Gentoo folks who touch Ceph.

**Comment by peeweep** [comment]
make check (arm64) failed and needs to be retriggered.

**Pull request closed without merging**
