### PR TITLE
rgw/s3select : crash upon parsing stage 

### PR DESCRIPTION
**Pull request by galsalomon66**
upon Parquet-flow there are 2 calls to parse-query (not correct)
upon failure of AST creation, the second call caused a crash.
 
the engine has safety against multiple calls, but it is not working correctly upon failure during AST creation.

-- the multiple calls should remove
-- the engine should overcome a failed AST creation

s3select : https://github.com/ceph/s3select/pull/160
s3select : https://github.com/ceph/s3select/pull/161

BZ https://bugzilla.redhat.com/show_bug.cgi?id=2290775

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [x] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Comment by galsalomon66** [comment]
https://pulpito.ceph.com/gsalomon-2024-06-13_06:43:30-rgw:verify-fix_crash_upon_parsing-distro-default-smithi/

**Comment by galsalomon66** [comment]
https://pulpito.ceph.com/gsalomon-2024-06-20_04:14:51-rgw:verify-fix_crash_upon_parsing-distro-default-smithi/

the `valgrind error: MismatchedFree operator delete[](void*, unsigned long) MonClient::get_monmap_and_config()` not related to changes.

https://tracker.ceph.com/issues/66336#change-265969

**Comment by galsalomon66** [comment]
https://pulpito.ceph.com/gsalomon-2024-06-20_13:38:11-rgw:verify-fix_crash_upon_parsing-distro-default-smithi/
TODO : check results

**Comment by galsalomon66** [comment]
https://pulpito.ceph.com/gsalomon-2024-06-24_05:00:59-rgw:verify-fix_crash_upon_parsing-distro-default-smithi/

TODO: check results

**Comment by galsalomon66** [comment]
https://pulpito.ceph.com/gsalomon-2024-07-13_13:13:26-rgw:verify-fix_crash_upon_parsing-distro-default-smithi/
one failure on non-related valgrind issue

**Comment by galsalomon66** [comment]
https://pulpito.ceph.com/gsalomon-2024-08-04_03:53:05-rgw:verify-fix_crash_upon_parsing-distro-default-smithi/
all green(6)

**Comment by galsalomon66** [comment]
https://pulpito.ceph.com/gsalomon-2024-08-04_22:45:04-rgw:verify-fix_crash_upon_parsing-distro-default-smithi/
valgrind issue

**Comment by galsalomon66** [comment]
https://pulpito.ceph.com/gsalomon-2024-08-23_07:48:35-rgw:verify-fix_crash_upon_parsing-distro-default-smithi/
2 dead. the rest are green. 
no valgrind report.

**Comment by galsalomon66** [comment]
https://pulpito.ceph.com/gsalomon-2024-08-23_13:03:18-rgw-fix_crash_upon_parsing-distro-default-smithi/

**Comment by galsalomon66** [comment]
jenkins test make check

**Comment by galsalomon66** [comment]
jenkins test api

**Comment by cbodley** [comment]
can you please squash the submodule commits?

**Comment by galsalomon66** [comment]
jenkins test make check

**Comment by galsalomon66** [comment]
jenkins test make check

**Comment by galsalomon66** [comment]
jenkins test api

**Comment by galsalomon66** [comment]
jenkins test make check

**Comment by mkogan1** [comment]
jenkins test api

**Comment by adamemerson** [comment]
jenkins test make check

**Comment by galsalomon66** [comment]
this PR is closed, its recent teuthology runs keep failing with failures unrelated to PR changes.

https://github.com/ceph/ceph/pull/60322 replace it

**Pull request closed without merging**
