### PR TITLE
RFC: common: define config options

### PR DESCRIPTION
**Pull request by liewegas**
- options.c is C to allow C-style struct initialization.  There is no good C++ syntax that lets you label the fields.
- there's a trivial-ish .c file to generate a header fragment. The idea is that cmake would run this and swap in teh header if and only if it has changed from before, so that only type changes or additions will trigger a recompile.
- md_config_t will get updated to include that fragment, and it's constructure will populate the default values by parsing them from teh strings.  this adds validation on startup (yay).
- differing defaults for daemons vs non-daemons will be specified in the options.c so that we don't have to hack around it in common_init like we do now.  (daemons with specific default changes will continue to pass in their own default values.)
- lots of chnages to config.cc to follow to enforce min/max/enum, allowed config level, dump config schema, etc.

Thoughts?  It is very slow going actually populating options.c.  If we can agree on the approach and get some of the infrastructure in place maybe we can divvy up the work across subsystems...

### CODE REVIEW

**Comment by tchaikov** [comment]
> options.c is C to allow C-style struct initialization. There is no good C++ syntax that lets you label the fields.

how about https://gist.github.com/tchaikov/a4c159b5ebf814ab47900bff1eee641b ?

**Comment by tchaikov** [comment]
with a `boost::variant`, i imagine, for example, we could use the user-defined literals to present the timeout/duration in a more expressive and type-safe way. C++11 does not offer literals for time duration, but i think we can extend it by defining our own. and define a ratio or percentage option using the notation like "66_percent". very cool, isn't it? =D

**Comment by liewegas** [comment]
The boost::variant looks like it'll work, but I can't tell if it actually makes the situation better.  In all cases we need to parse values from strings, so populating C strings in a struct isn't limiting us in any case.  The lists (see_also, tags) could be explicit vectors or sets, I guess, but it's actually more typing to write that out (.add_tag("foo").add_tag("bar") or .add_tags({"foo","bar"}) vs just .tags = "foo bar", ...  Unless there's a real advantage I'm leaning toward the trivial syntax.

Either way, I'll need help with the CMake piece that runs the helper to generate the header fragment at build time before doing the dependency calculation on the (maybe but hopefully not) modified header...

**Comment by tchaikov** [comment]
the C++ syntax will prove itself when we add min/max/enum support. for example, we can define a self-contained `BoundedOption` type. and its ctor will accept the "name", lower/upper bound. the `set_value()` can `assert()` at seeing a wrong value.

i will take care of the CMake change if necessary.

**Comment by liewegas** [comment]
I got as far as the options.cc in the top patch.  boost::variant doesn't like the int, though.. i'm not sure what is ambiguous?

Anyway I'm still unsure whether this is any better than the C struct definitions...

**Comment by tchaikov** [comment]
i will continue working on this tomorrow.

**Comment by mattbenjamin** [comment]
++boost?

**Comment by adamemerson** [comment]
I like the boost variant since at some point I'd like to get rid of all the floating point second counts in the config struct and replace them with actual time values. That way we don't have to keep grabbing stuff out of floating point and whatnot when using it.

**Comment by liewegas** [comment]
Note that C variant doesn't make float vs timepoint change any easier or harder; we'll still be able to parse to/from a string.

**Comment by tchaikov** [comment]
@liewegas i rebased your PR on master and fixed the build, see #15534

**Comment by jcsp** [comment]
Disorganised thoughts:

- The basic/advanced distinction mixes two concepts: how easy to understand an option is, and how reasonable/expected it is for someone to modify it.  For example, the log path is clearly a very simple thing, but probably not something a lot of people would want to change.  The "advanced" tuning options are probably more likely to be changed (... He claimed with no evidence whatsoever).  The "dev vs. not dev" distinction is the really important one: I'm not sure how I would use "basic", because things like log paths really wouldn't be the first options I showed to users anyway.
- Thinking of e.g. the MDS, the real options I'd want to expose first to users would be things like the client eviction timeout, standby_for_rank, standby_replay.  They don't really have much in common with other "basic" things like the service infrastructure paths.  Then again, maybe I'm just hung up on the word basic.  In practice a UI could show the basic stuff but filter out the boring bits if they're properly tagged as being related to logging/service configuration.
- I would separate out the "consumed by" concept from the freeform tags.  For the freeform tags, we talked about having a "performance" flag, I like that.  Maybe another one would be something like "service" that configured things like asok and pidfile locations (what I like to call the boring options).  Others would be "network", "logging".

I think we're going through contortions to expose the config settings as C++ variables rather than just as a map of variants.  Clearly having the native config settings makes it simple and efficient to consume them, but here's another idea to get the efficiency -- what if we had a "bind" class that consumers would use to grab a local copy of the variable, and subscribe for updates to changes of the variable's value.

For example, MDLog currently reads out of g_conf->mds_log_events_per_segment frequently.  It would get a config_binder<int> evs_per_segment("mds_log_events_per_segment") member, that would go get the value from g_conf on construction, and then MDLog code would read of its local evs_per_segment.  By default the config_binder would just get its value updated in place if it changed in the global config object, but there could be a specialized config_observer<type>("option", this); for use on md_config_obs_t, so that the global config object would know which config observers needed calling for which options (rather than the duplicated list in get_tracked_conf_keys that we currently have).

The downside to that kind of thing is that we wouldn't be checking at compile time that the subscribed-to option really existed, but perhaps we need to get used to that when looking forward to storing config in a central KV store on the mons rather than loading it locally on each daemon.

**Pull request closed without merging**
