### PR TITLE
mimic: mds: introduce cephfs' own feature bits

### PR DESCRIPTION
**Pull request by ukernel**
http://tracker.ceph.com/issues/24914

Backport of #21885

### CODE REVIEW

**Comment by batrick** [comment]
@ukernel now that 3d39e1089b04df761babb63464bfbca4f89d747d is merged via #22835, this should run through QA without issue. Rebase shouldn't be necessary.

**Comment by smithfarm** [comment]
@batrick Can you approve this PR?

**Comment by yuriw** [comment]
[wip-yuri3-testing-2018-08-20-2118-mimic](https://trello.com/c/hWHRSkCU/378-wip-yuri3-testing-2018-08-20-2118-mimic)

**Comment by yuriw** [comment]
[wip-yuri5-testing-2018-09-12-1937-mimic](https://trello.com/c/hdresXy8/401-wip-yuri5-testing-2018-09-12-1937-mimic)

**Pull request merged**
