### PR TITLE
doc/rados/troubleshooting: description of upgrade procedure - stopping/starting OSDs

### PR DESCRIPTION
**Pull request by anthonyeleven**
doc/rados/troubleshooting: description of upgrade procedure - stopping/starting OSDs

Updated legacy Upstart commands to the ``systemd`` new world order.  Added a brief note about other init systems.

Fixes: https://tracker.ceph.com/issues/14730
Signed-off-by: Anthony D'Atri <anthony.datri@gmail.com>

## Checklist
- [x] References tracker ticket
- [x] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by anthonyeleven** [comment]
jenkins test api

**Review by zdover23 — APPROVED** [review]
LGTM. Proceeding with merge.

**Comment by zdover23** [comment]
@anthonyeleven There's a single conflict around line 239. If you need help resolving it, let me know and we'll set a time to go through it.

**Comment by anthonyeleven** [comment]
Odd, not sure how that happened.  Will chalk it up to having 21 local branches in play.  I _think_ I've properly resolved.

**Review by zdover23 — APPROVED** [review]
LGTM. Proceeding with merge.

**Comment by zdover23** [comment]
@anthonyeleven Can you squash these two commits into a single commit?

**Comment by anthonyeleven** [comment]
> @anthonyeleven Can you squash these two commits into a single commit?

My local branch history is messed up, I will abandon this PR and enter a new one to do so.

**Comment by zdover23** [comment]
oh no! It can probably be fixed!

**Comment by zdover23** [comment]
All you've got to do is this:

1. $ git fetch ceph
2. $ git checkout master
3. $ git reset --hard ceph/master
4. $ git push origin master
5. $ git checkout docs-14730
6. $ git rebase -i master
7. replace "pick" with "squash" on either of the commits listed.
8. $ git push -f

That's it. (I mean, that's eight steps, so maybe "that's it" seems glib. But that's it.)

**Comment by anthonyeleven** [comment]
@zdover23 The rebase shows a great many unrelated commits, and not my second one at all.  When I try a whole new fork from a fresh clone/fetch, I get a commit from an unrelated PR.

I think I need to wait until we merge

https://github.com/ceph/ceph/pull/38091
https://github.com/ceph/ceph/pull/38079
https://github.com/ceph/ceph/pull/38088
https://github.com/ceph/ceph/pull/38143

then I'll tear down my fork and local checkout and start fresh.

**Comment by zdover23** [comment]
> @zdover23 The rebase shows a great many unrelated commits, and not my second one at all. When I try a whole new fork from a fresh clone/fetch, I get a commit from an unrelated PR.
> 
> I think I need to wait until we merge
> 
> #38091
> #38079
> #38088
> #38143
> 
> then I'll tear down my fork and local checkout and start fresh.

Aw man. It'll probably take a few hours for all these checks to make it through the pipes, so I'll probably fit a nap in between the present and the time that these get merged. Continually checking to see if the pipes have somehow become unclogged is a bummer.

**Pull request merged**
