### PR TITLE
pacific: qa: "AttributeError: 'NoneType' object has no attribute 'mon_manager'"

### PR DESCRIPTION
**Pull request by batrick**
https://tracker.ceph.com/issues/50015

### CODE REVIEW

**Comment by batrick** [comment]
jenkins test make check

**Comment by batrick** [comment]
https://tracker.ceph.com/projects/cephfs/wiki/Pacific#2021-Apr-07-Integration-Branch

`Reviewed-by: Patrick Donnelly <pdonnell@redhat.com>`

**Review by yuriw — APPROVED** [review]
Reviewed-by: Patrick Donnelly <pdonnell@redhat.com>

**Comment by yuriw** [comment]
test this please

**Comment by neha-ojha** [comment]
jenkins test make check

**Pull request merged**
