### PR TITLE
jewel: tests: ceph-disk must ignore debug monc

### PR DESCRIPTION
**Pull request by dachary**
http://tracker.ceph.com/issues/17609

### CODE REVIEW

**Comment by liewegas** [comment]
:+1:

**Comment by liewegas** [comment]
reverted the debug monc = 1, fwiw.  this is probably a good idea anyway tho

**Comment by dachary** [comment]
test this please

**Comment by dachary** [comment]
test this please

**Comment by dachary** [comment]
Passed the ceph-disk suite http://tracker.ceph.com/issues/17487#note-23

**Pull request merged**
