### PR TITLE
nautilus: mds: display scrub status in ceph status

### PR DESCRIPTION
**Pull request by vshankar**
http://tracker.ceph.com/issues/41508
http://tracker.ceph.com/issues/42168
http://tracker.ceph.com/issues/42325
http://tracker.ceph.com/issues/42569
http://tracker.ceph.com/issues/42713
http://tracker.ceph.com/issues/44520

### CODE REVIEW

**Comment by smithfarm** [comment]
jenkins test make check

**Comment by smithfarm** [comment]
@vshankar Would it make sense to do https://tracker.ceph.com/issues/42325 right here in this PR?

**Comment by yuriw** [comment]
[wip-yuri7-testing-2019-11-13-1707-nautilus](https://trello.com/c/bfPMBPx6/759-wip-yuri7-testing-2019-11-13-1707-nautilus)

**Comment by batrick** [comment]
@yuriw please drop from your testing.

**Comment by batrick** [comment]
and https://tracker.ceph.com/issues/43035

**Comment by batrick** [comment]
Note, #32600 also has https://github.com/ceph/ceph/pull/31231/commits/9dc07d80967287051eab3245e58d029157d3e1da

**Comment by vshankar** [comment]
@batrick please take a look. btw, seems that tracker https://tracker.ceph.com/issues/42835 had an incorrect blocker tracker set. I've removed that and created a backport tracker ticket.

**Comment by vshankar** [comment]
fixed and updated

**Comment by gregsfortytwo** [comment]
Running tests at
http://pulpito.front.sepia.ceph.com:80/gregf-2020-03-13_20:56:54-fs-wip-greg-testing-nautilus-313-distro-basic-smithi/
http://pulpito.front.sepia.ceph.com:80/gregf-2020-03-13_21:00:59-multimds:basic-wip-greg-testing-nautilus-313-distro-basic-smithi/

Once those run let's merge if they look good.

**Comment by smithfarm** [comment]
@gregsfortytwo @vshankar I was looking at this, and https://tracker.ceph.com/issues/42738 seems to be missing? 

https://tracker.ceph.com/issues/42835 (which is backported in this PR) is supposedly a follow-on fix for https://tracker.ceph.com/issues/42738 so I was expected it to be included.

**Comment by smithfarm** [comment]
Also please note that `PendingReleaseNotes` now no longer contains any old release notes relating to already released versions of nautilus, so the release note for this PR can just be appended at the end of the file.

**Comment by gregsfortytwo** [comment]
@vshankar the test run had a failure in test_scrub_pause_and_resume (tasks.cephfs.test_scrub_checks.TestScrubControls)

**Comment by vshankar** [comment]
> @vshankar the test run had a failure in test_scrub_pause_and_resume (tasks.cephfs.test_scrub_checks.TestScrubControls)

checking

**Comment by vshankar** [comment]
> @gregsfortytwo @vshankar I was looking at this, and https://tracker.ceph.com/issues/42738 seems to be missing?
> 
> https://tracker.ceph.com/issues/42835 (which is backported in this PR) is supposedly a follow-on fix for https://tracker.ceph.com/issues/42738 so I was expected it to be included.

I updated tracker https://tracker.ceph.com/issues/42835 -- the two trackers are not related.

**Comment by vshankar** [comment]
> @vshankar the test run had a failure in test_scrub_pause_and_resume (tasks.cephfs.test_scrub_checks.TestScrubControls)

The issue is seen in master too: http://pulpito.ceph.com/vshankar-2020-03-16_10:45:29-fs-master-testing-basic-smithi/

I'll raise a tracker ticket to track that.

@gregsfortytwo -- if the backport looks ok (apart from the above issue), should we just merge it? I'll rebase and push...

**Comment by gregsfortytwo** [comment]
> > @vshankar the test run had a failure in test_scrub_pause_and_resume (tasks.cephfs.test_scrub_checks.TestScrubControls)
> 
> The issue is seen in master too: http://pulpito.ceph.com/vshankar-2020-03-16_10:45:29-fs-master-testing-basic-smithi/
> 
> I'll raise a tracker ticket to track that.
> 
> @gregsfortytwo -- if the backport looks ok (apart from the above issue), should we just merge it? I'll rebase and push...

Have you diagnosed the issue? Let's work out what it is first...

**Comment by vshankar** [comment]
> Have you diagnosed the issue? Let's work out what it is first...

sure -- should have something by tomorrow.

**Comment by vshankar** [comment]
> Have you diagnosed the issue? Let's work out what it is first...

https://tracker.ceph.com/issues/44638 -- fix will be up soon.

**Comment by yuriw** [comment]
@vshankar pls rebase

**Pull request merged**
