### PR TITLE
librbd: not return the migration source as the parent

### PR DESCRIPTION
**Pull request by Songweibin**
```
[swb@ ~/ceph/ceph-dev/build]$ rbd migration prepare img1 img2
[swb@ ~/ceph/ceph-dev/build]$ rbd ls -l
NAME  SIZE   PARENT    FMT PROT LOCK
img2  10 MiB rbd/img1@   2
```

Signed-off-by: songweibin <song.weibin@zte.com.cn>

- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by Songweibin** [comment]
@dillaman  Fixed as your suggestion, please take a look. Thx.

**Comment by dillaman** [comment]
@Songweibin This actually exposes a bigger problem. When we are migrating, ```ImageCtx::parent_md``` stores the migration source details and overwrites any potential parent. That means that if your migration destination image really does have a parent, you won't know about it until after the migration has completed.

Therefore, I think the real solution is to remove all the places in librbd that directly read the parent data from ```ImageCtx::parent_md``` and instead force them to use an accessor. Then ```librbd::image::RefreshRequest``` can store the real parent info into the image ctx for use by the API getter.

**Comment by Songweibin** [comment]
@dillaman  I'm not sure I got your idea about using an accessor, I can think of two ways:
(1) add a new API in ImageCtx, E.g.:
```
+  int ImageCtx::get_parent_info(snap_t in_snap_id,
+                                ParentImageInfo *parent_info)
+  {
+    ceph_assert(snap_lock.is_locked());
+    ceph_assert(parent_lock.is_locked());
+    if (in_snap_id == CEPH_NOSNAP) {
+      int r = cls_client::get_parent(&md_ctx, header_oid, CEPH_NOSNAP,
+                                     &parent_info->spec,
+                                     &parent_info->overlap);
+      if (r < 0) {
+        return r;
+      }
+      return 0;
+    }
+    const SnapInfo *info = get_snap_info(in_snap_id);
+    if (info) {
+      *parent_info = info->parent;
+      return 0;
+    }
+    return -ENOENT;
+  }
```
(2) add a new member variable in ImageCtx.h, E.g: `ParentImageInfo parent_md2;`
And store the real parent info into `parent_md2` at librbd::image::RefreshRequest.

**Comment by dillaman** [comment]
@Songweibin I was suggesting something similar to option (1) where we change the librbd code from directly touching ```ImageCtx::parent_md```. Instead, it would populate the provided ```ParentImageInfo``` struct with the contents of ```ImageCtx::migration_info``` if a migration is in-progress, or ```ImageCtx::parent_md``` if ```snap_id == CEPH_NOSNAP```, otherwise the contents from the snapshot. Additionally, ```RefreshRequest``` wouldn't overwrite the contents of ```ImageCtx::parent_md``` w/ the migration data.

**Pull request closed without merging**
