### PR TITLE
ceph-volume: fix lvm activate --all --no-systemd

### PR DESCRIPTION
**Pull request by dsavineau**
When using a system without systemd then the `lvm activate --all --no-systemd`
subcommand still calls systemd.
We already allow users to activate a single OSD without systemd so there's
no reason to not do the same with --all (because activate_all calls activate).

Fixes: https://tracker.ceph.com/issues/25070

Signed-off-by: Dimitri Savineau <dsavinea@redhat.com>

## Checklist
- [x] References tracker ticket
- [ ] Updates documentation if necessary
- [x] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by dsavineau** [comment]
jenkins test ceph-volume tox

**Comment by dsavineau** [comment]
jenkins test ceph-volume all

**Comment by dsavineau** [comment]
jenkins test ceph-volume lvm centos8-bluestore-create

**Comment by dsavineau** [comment]
jenkins test ceph-volume lvm centos8-bluestore-create

**Comment by dsavineau** [comment]
jenkins test ceph-volume lvm centos8-bluestore-create

**Comment by dsavineau** [comment]
jenkins test ceph-volume lvm centos8-bluestore-create

**Comment by dsavineau** [comment]
jenkins test ceph-volume lvm centos8-bluestore-create

**Review by guits — APPROVED** [review]

**Comment by guits** [comment]
jenkins test ceph-volume lvm centos8-bluestore-create

**Pull request merged**
