### PR TITLE
pacific: qa: enable kclient test for newop test

### PR DESCRIPTION
**Pull request by lxbsz**
backport tracker: https://tracker.ceph.com/issues/59198

---

backport of https://github.com/ceph/ceph/pull/48183 and https://github.com/ceph/ceph/pull/48280
parent tracker: https://tracker.ceph.com/issues/57591 and https://tracker.ceph.com/issues/53573

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by yuriw** [comment]
@lxbsz I suspect this PR breaks `tautology-siute`

OSError: /home/yuriw/src/github.com_ceph_ceph-c_wip-yuri2-testing-2023-04-11-1244-pacific/qa/suites/fs/upgrade/upgraded_client/tasks/2-workload/stress_tests/1-tests/blogbench.yaml does not exist (abs /home/yuriw/src/github.com_ceph_ceph-c_wip-yuri2-testing-2023-04-11-1244-pacific/qa/suites/fs/upgrade/upgraded_client/tasks/2-workload/stress_tests/1-tests/blogbench.yaml)

ref: https://trello.com/c/TABfdBDZ

**Review by kotreshhr — APPROVED** [review]

**Comment by vshankar** [comment]
> @lxbsz I suspect this PR breaks `tautology-siute`
> 
> OSError: /home/yuriw/src/github.com_ceph_ceph-c_wip-yuri2-testing-2023-04-11-1244-pacific/qa/suites/fs/upgrade/upgraded_client/tasks/2-workload/stress_tests/1-tests/blogbench.yaml does not exist (abs /home/yuriw/src/github.com_ceph_ceph-c_wip-yuri2-testing-2023-04-11-1244-pacific/qa/suites/fs/upgrade/upgraded_client/tasks/2-workload/stress_tests/1-tests/blogbench.yaml)
> 
> ref: https://trello.com/c/TABfdBDZ

@lxbsz ping ^^

**Comment by lxbsz** [comment]
> > @lxbsz I suspect this PR breaks `tautology-siute`
> > OSError: /home/yuriw/src/github.com_ceph_ceph-c_wip-yuri2-testing-2023-04-11-1244-pacific/qa/suites/fs/upgrade/upgraded_client/tasks/2-workload/stress_tests/1-tests/blogbench.yaml does not exist (abs /home/yuriw/src/github.com_ceph_ceph-c_wip-yuri2-testing-2023-04-11-1244-pacific/qa/suites/fs/upgrade/upgraded_client/tasks/2-workload/stress_tests/1-tests/blogbench.yaml)
> > ref: https://trello.com/c/TABfdBDZ
> 
> @lxbsz ping ^^

Sorry, missed this. Let me have a look.

**Comment by lxbsz** [comment]
Fixed it by removing:

```
lrwxrwxrwx. 1 xiubli xiubli 61 Aug 21 10:21 blogbench.yaml -> .qa/suites/fs/workload/tasks/5-workunit/suites/blogbench.yaml
lrwxrwxrwx. 1 xiubli xiubli 58 Aug 21 10:21 dbench.yaml -> .qa/suites/fs/workload/tasks/5-workunit/suites/dbench.yaml
lrwxrwxrwx. 1 xiubli xiubli 60 Aug 21 10:21 fsstress.yaml -> .qa/suites/fs/workload/tasks/5-workunit/suites/fsstress.yaml
lrwxrwxrwx. 1 xiubli xiubli 58 Aug 21 10:21 iozone.yaml -> .qa/suites/fs/workload/tasks/5-workunit/suites/iozone.yaml
lrwxrwxrwx. 1 xiubli xiubli 63 Aug 21 10:21 kernel_untar_build.yaml -> .qa/suites/fs/workload/tasks/5-workunit/kernel_untar_build.yaml
```

And adding:

```
lrwxrwxrwx. 1 xiubli xiubli 59 Aug 21 10:23 blogbench.yaml -> .qa/suites/fs/workload/tasks/workunit/suites/blogbench.yaml
lrwxrwxrwx. 1 xiubli xiubli 56 Aug 21 10:23 dbench.yaml -> .qa/suites/fs/workload/tasks/workunit/suites/dbench.yaml
lrwxrwxrwx. 1 xiubli xiubli 58 Aug 21 10:23 fsstress.yaml -> .qa/suites/fs/workload/tasks/workunit/suites/fsstress.yaml
lrwxrwxrwx. 1 xiubli xiubli 56 Aug 21 10:23 iozone.yaml -> .qa/suites/fs/workload/tasks/workunit/suites/iozone.yaml
lrwxrwxrwx. 1 xiubli xiubli 61 Aug 21 10:24 kernel_untar_build.yaml -> .qa/suites/fs/workload/tasks/workunit/kernel_untar_build.yaml
```

**Comment by vshankar** [comment]
Not critical for last pacific release.

**Pull request closed without merging**
