### PR TITLE
osd: For write a non-exist erasure object don't offset > 0.

### PR DESCRIPTION
**Pull request by dachary**
http://tracker.ceph.com/issues/11507

### CODE REVIEW

**Comment by dachary** [comment]
@majianpeng I've added a test that demonstrate the problem and created an issue for backporting at http://tracker.ceph.com/issues/11507. Nice catch !

**Comment by tchaikov** [comment]
the build failure is irrelevant, triggering another build.

**Comment by dachary** [comment]
@majianpeng does that look right to you ?

**Comment by majianpeng** [comment]
@dachary . Looks good to me. Thanks

**Pull request merged**
