### PR TITLE
cephadm: show contextual message when port is in use

### PR DESCRIPTION
**Pull request by mgfritch**
- OSError raised during a failed bind did not include exception cause
- Log warning for other potental failure cases (e.g. EADDRNOTAVAIL, etc)

Signed-off-by: Michael Fritch <mfritch@suse.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by mgfritch** [comment]
Exception cause was missing from error message when port is already in use.

Old behavior:
```
# cephadm bootstrap --mon-ip 127.0.0.1
INFO:root:Cluster fsid: 89a43a54-3275-11ea-93b1-8cdcd44b8f38
INFO:cephadm:Verifying IP 127.0.0.1 port 3300 is not in use...
ERROR: Unable to bind to IP 127.0.0.1 port 3300:
```

New behavior:
```
# cephadm bootstrap --mon-ip 127.0.0.1
INFO:root:Cluster fsid: 6ab3a8f0-3275-11ea-877f-8cdcd44b8f38
INFO:cephadm:Verifying IP 127.0.0.1 port 3300 ...
WARNING:cephadm:Cannot bind to IP 127.0.0.1 port 3300: [Errno 98] Address already in use
ERROR: Cannot bind to IP 127.0.0.1 port 3300: [Errno 98] Address already in use
```

**Comment by mgfritch** [comment]
Also added warning log line for other `errno` instances for easier debugging.

Such as attempting to bind to a non-existent IP address:
```
# cephadm bootstrap --mon-ip 192.168.0.1
INFO:root:Cluster fsid: 65e4bd32-325c-11ea-84a2-8cdcd44b8f38
INFO:cephadm:Verifying IP 192.168.0.1 port 3300 ...
WARNING:cephadm:Cannot bind to IP 192.168.0.1 port 3300: [Errno 99] Cannot assign requested address
INFO:cephadm:Verifying IP 192.168.0.1 port 6789 ...
WARNING:cephadm:Cannot bind to IP 192.168.0.1 port 6789: [Errno 99] Cannot assign requested address
INFO:cephadm:Pulling latest ceph/daemon-base:latest-master-devel container...
INFO:cephadm:Extracting ceph user uid/gid from container image...
INFO:cephadm:Creating initial keys...
INFO:cephadm:Creating initial monmap...
INFO:cephadm:Creating mon...
INFO:cephadm:Waiting for mon to start...
INFO:cephadm:Non-zero exit code 1 from /usr/bin/podman run --rm --net=host -e CONTAINER_IMAGE=ceph/daemon-base:latest-master-devel -e NODE_NAME=foobar -v /tmp/ceph-tmpAaN64I:/etc/ceph/ceph.conf:z -v /var/lib/ceph/65e4bd32-325c-11ea-84a2-8cdcd44b8f38/mon.foobar:/var/lib/ceph/mon/ceph-foobar:z -v /tmp/ceph-tmpaIhRZ7:/etc/ceph/ceph.client.admin.keyring:z --entrypoint /usr/bin/ceph ceph/daemon-base:latest-master-devel status
INFO:cephadm:/usr/bin/ceph:stderr [errno 110] RADOS timed out (error connecting to the cluster)
INFO:cephadm:mon is still not available yet, waiting...
```

**Comment by mgfritch** [comment]
retest this please

**Comment by sebastian-philipp** [comment]
http://pulpito.ceph.com/swagner-2020-01-13_10:20:46-rados-wip-swagner-testing-distro-basic-smithi/ failed with

```
2020-01-13T10:52:26.760 INFO:teuthology.orchestra.run.smithi132.stderr:Error ENOENT: No inventory found for host: smithi132
```

**Comment by mgfritch** [comment]
> http://pulpito.ceph.com/swagner-2020-01-13_10:20:46-rados-wip-swagner-testing-distro-basic-smithi/ failed with
> 
> ```
> 2020-01-13T10:52:26.760 INFO:teuthology.orchestra.run.smithi132.stderr:Error ENOENT: No inventory found for host: smithi132
> ```
> 

Unsure about this ..


> and http://qa-proxy.ceph.com/teuthology/swagner-2020-01-13_10:20:46-rados-wip-swagner-testing-distro-basic-smithi/4664538/teuthology.log
> 
> ```
> 2020-01-13T10:51:07.241 INFO:tasks.workunit.client.0.smithi177.stderr:WARNING:cephadm:Cannot bind to IP 127.0.0.1 port 3300: [Errno 98] Address already in use
> 2020-01-13T10:51:07.242 INFO:tasks.workunit.client.0.smithi177.stderr:ERROR: Cannot bind to IP 127.0.0.1 port 3300: [Errno 98] Address already in use
> 2020-01-13T10:51:07.246 INFO:tasks.workunit.client.0.smithi177.stderr:+ rm -rf /tmp/tmp.dA4mh43WiG
> 2020-01-13T10:51:07.254 INFO:tasks.workunit.client.0.smithi177.stderr:+ rm -rf /tmp/tmp.LkluVZnnbH
> 2020-01-13T10:51:07.255 DEBUG:teuthology.orchestra.run:got remote process result: 1
> ```

This is caused when the TCP session between mgr -> mon is disconnected during `cephadm rm-cluster` leaving the mon socket in a `TIME_WAIT`.

**Comment by liewegas** [comment]
> > and http://qa-proxy.ceph.com/teuthology/swagner-2020-01-13_10:20:46-rados-wip-swagner-testing-distro-basic-smithi/4664538/teuthology.log
> > ```
> > 2020-01-13T10:51:07.241 INFO:tasks.workunit.client.0.smithi177.stderr:WARNING:cephadm:Cannot bind to IP 127.0.0.1 port 3300: [Errno 98] Address already in use
> > 2020-01-13T10:51:07.242 INFO:tasks.workunit.client.0.smithi177.stderr:ERROR: Cannot bind to IP 127.0.0.1 port 3300: [Errno 98] Address already in use
> > 2020-01-13T10:51:07.246 INFO:tasks.workunit.client.0.smithi177.stderr:+ rm -rf /tmp/tmp.dA4mh43WiG
> > 2020-01-13T10:51:07.254 INFO:tasks.workunit.client.0.smithi177.stderr:+ rm -rf /tmp/tmp.LkluVZnnbH
> > 2020-01-13T10:51:07.255 DEBUG:teuthology.orchestra.run:got remote process result: 1
> > ```
> 
> This is caused when the TCP session between mgr -> mon is disconnected during `cephadm rm-cluster` leaving the mon socket in a TCP `TIME_WAIT`

I think it was actually the 'exit 0', such that after the first time around with a previous python version the cluster wasn't torn down.

**Comment by mgfritch** [comment]
> > > and http://qa-proxy.ceph.com/teuthology/swagner-2020-01-13_10:20:46-rados-wip-swagner-testing-distro-basic-smithi/4664538/teuthology.log
> > > ```
> > > 2020-01-13T10:51:07.241 INFO:tasks.workunit.client.0.smithi177.stderr:WARNING:cephadm:Cannot bind to IP 127.0.0.1 port 3300: [Errno 98] Address already in use
> > > 2020-01-13T10:51:07.242 INFO:tasks.workunit.client.0.smithi177.stderr:ERROR: Cannot bind to IP 127.0.0.1 port 3300: [Errno 98] Address already in use
> > > 2020-01-13T10:51:07.246 INFO:tasks.workunit.client.0.smithi177.stderr:+ rm -rf /tmp/tmp.dA4mh43WiG
> > > 2020-01-13T10:51:07.254 INFO:tasks.workunit.client.0.smithi177.stderr:+ rm -rf /tmp/tmp.LkluVZnnbH
> > > 2020-01-13T10:51:07.255 DEBUG:teuthology.orchestra.run:got remote process result: 1
> > > ```
> > 
> > 
> > This is caused when the TCP session between mgr -> mon is disconnected during `cephadm rm-cluster` leaving the mon socket in a TCP `TIME_WAIT`
> 
> I think it was actually the 'exit 0', such that after the first time around with a previous python version the cluster wasn't torn down.

That was my initial thought too, but the `rm-cluster` near the start of the test should have handled that.

It's fairly easy to reproduce by running `bootstrap`, `rm-cluster` and `bootstrap` again with a few min  ...

```
# ../src/cephadm/cephadm bootstrap --mon-ip 127.0.0.1 --fsid 00000000-0000-0000-0000-0000deadbeef --allow-overwrite
<snip>

# ../src/cephadm/cephadm rm-cluster --force --fsid 00000000-0000-0000-0000-0000deadbeef

# ../src/cephadm/cephadm bootstrap --mon-ip 127.0.0.1 --fsid 00000000-0000-0000-0000-0000deadbeef --allow-overwrite
INFO:root:Cluster fsid: 00000000-0000-0000-0000-0000deadbeef
INFO:cephadm:Verifying IP 127.0.0.1 port 3300 ...
WARNING:cephadm:Cannot bind to IP 127.0.0.1 port 3300: [Errno 98] Address already in use
ERROR: Cannot bind to IP 127.0.0.1 port 3300: [Errno 98] Address already in use

#  ss -apn | grep 3300
tcp               TIME-WAIT              0                   0                                                                                        127.0.0.1:3300                                           127.0.0.1:39120



```

**Pull request merged**
