### PR TITLE
doc/releases/nautilus: fix release notes (crash->device)

### PR DESCRIPTION
**Pull request by liewegas**
Fix pending note for octopus too

Signed-off-by: Sage Weil <sage@redhat.com>

### CODE REVIEW

**Comment by theanalyst** [comment]
updated the blog with this as well https://ceph.io/releases/v14-2-5-nautilus-released/

**Comment by liewegas** [comment]
retest this please

**Comment by smithfarm** [comment]
@liewegas Would it be easier on the reader if the two telemetry release notes were combined into a single one, for example like so?

```
The telemetry MGR module now reports more information.

* a new "device" channel, enabled by default, will report anonymized hard disk and SSD health metrics to telemetry.ceph.com in order to build and improve device failure prediction algorithms.
* information about CephFS file systems, including:
  + how many MDS daemons (in total and per file system)
  + which features are (or have been) enabled
  + how many data pools
  + approximate file system age (year + month of creation)
  + how many files, bytes, and snapshots
  + how much metadata is being cached
* other miscellaneous information:
  + which Ceph release the monitors are running
  + whether msgr v1 or v2 addresses are used for the monitors
  + whether IPv4 or IPv6 addresses are used for the monitors
  + whether RADOS cache tiering is enabled (and which mode)
  + whether pools are replicated or erasure coded, and which erasure code profile plugin and parameters are in use
  + how many hosts are in the cluster, and how many hosts have each type of daemon
  + whether a separate OSD cluster network is being used
  + how many RBD pools and images are in the cluster, and how many pools have RBD mirroring enabled
  + how many RGW daemons, zones, and zonegroups are present; which RGW frontends are in use
  + aggregate stats about the CRUSH map, like which algorithms are used, how big buckets are, how many rules are defined, and what tunables are in use

If you had telemetry enabled before 14.2.5, you will need to re-opt-in with:

    ceph telemetry on

If you are not comfortable sharing device metrics, you can disable that channel first before re-opting-in:

    ceph config set mgr mgr/telemetry/channel_device false
    ceph telemetry on

You can view exactly what information will be reported first with:
If you would rather not report the 
    ceph telemetry show        # see everything
    ceph telemetry show device # just the device info
    ceph telemetry show basic  # basic cluster info
```

**Comment by liewegas** [comment]
Yeah probably!

**Pull request merged**
