### PR TITLE
luminous: rgw: Random 500 errors in Swift PutObject (needs cache fixes)

### PR DESCRIPTION
**Pull request by adamemerson**
http://tracker.ceph.com/issues/22574
http://tracker.ceph.com/issues/22588

Backport of fixes for http://tracker.ceph.com/issues/22517

### CODE REVIEW

**Comment by cbodley** [comment]
@adamemerson this appears to be missing some of the commits from https://github.com/ceph/ceph/pull/19581, was that intentional? i think we'd be better off including everything so future backports are less likely to conflict

**Comment by mattbenjamin** [comment]
@adamemerson @cbodley my intent here was that this PR would have all applicable commits from the corresponding series I created for Jewel (and downstreamed)

**Comment by adamemerson** [comment]
I left out the commit using deque and the commit fixing deque, since it seemed pointless to add a commit breaking something and another commit fixing it to the same PR. We can put both back in if you like.

(Also Nathan Cutler did a backport yesterday, too, that has both in them.)

**Comment by mattbenjamin** [comment]
@adamemerson no, sorry, I didn't mean take the deque changes.  I meant follow the backport that I did for Jewel, and what we downstreamed (insofar as it applies);  our backports should take precedence in this case

**Comment by smithfarm** [comment]
@adamemerson Can you please cherry-pick https://github.com/ceph/ceph/commit/a6a1b664d313a54ad9d2f64b859296b1352b1ce4 into this PR? Then I can close mine.

Also, it would be great if backport PRs were mentioned in the tracker ticket - http://tracker.ceph.com/issues/22410 in this case. If I had known about this PR I would not have attempted the backport.

**Comment by smithfarm** [comment]
@adamemerson You mentioned a jewel backport PR? Can you post that in  http://tracker.ceph.com/issues/22410 as well, assuming it exists? That way, nobody will undertake duplicate work.

**Comment by adamemerson** [comment]
My original PR is about to merge and if I add something we'll have to put it through testing again. I will get started on a backport for this fix right now, though!

**Comment by smithfarm** [comment]
> my intent here was that this PR would have all applicable commits from the corresponding series I created for Jewel (and downstreamed)

@mattbenjamin Do you happen to know the PR for the Jewel series? I'd like to add it to the tracker.

**Comment by smithfarm** [comment]
@adamemerson Thanks! http://tracker.ceph.com/issues/22583 is the backport tracker - I assigned it to you.

**Comment by smithfarm** [comment]
The tracker side is complicated because (afaict) there are two root issues that the master PR fixes and both were marked for backport:

* http://tracker.ceph.com/issues/21560
* http://tracker.ceph.com/issues/22517

(Please correct me if I'm wrong on this!)

**Comment by yuriw** [comment]
[wip-yuri4-testing-2018-01-16-2200](https://trello.com/c/tXbuDRQm/230-wip-yuri4-testing-2018-01-16-2200)

**Pull request merged**
