### PR TITLE
Purge range 2

### PR DESCRIPTION
**Pull request by liwenpeng19**
There is PurgeRange.oncommit NULL error, which caused program crash
fixes:https://tracker.ceph.com/issues/43493
Singed-off-by : liwenpeng liwenpeng@inspur.com

### CODE REVIEW

**Comment by batrick** [comment]
Note: replaces #32472.

**Comment by batrick** [comment]
@liwenpeng19 sorry this is still not right. Try this:

````
git checkout purge_range_2
git reset --hard a7d273cef73caf6d98b34732b25f2581cc927043
git diff a7d273cef73caf6d98b34732b25f2581cc927043...6aab6196a9d04070cd3c15b853afadcc68f4a7d4 | git apply
git commit -s
````

**Comment by tchaikov** [comment]
@liwenpeng19 ping?

**Comment by batrick** [comment]
Replaced by #38012

**Pull request closed without merging**
