### PR TITLE
common/blkdev, ceph-volume: improve get_device_id

### PR DESCRIPTION
**Pull request by liewegas**
Sigh... the Areca controllers in the mira machines have weird results.

Also, my desktop doesn't have ID_SERIAL_SHORT, just ID_SERIAL.  So, let's try a few different things!

### CODE REVIEW

**Comment by ErwanAliasr1** [comment]
That situation will be present on many versions of controllers. Why not having some sample udev output and test them in a TDD fashion so we can add more cases later while checking we don't break the format ?

**Comment by ErwanAliasr1** [comment]
looks like there is some. oups.

**Comment by ErwanAliasr1** [comment]
I have a couple of some devices from various hardware to offer : http://pastebin.test.redhat.com/679978

**Comment by leseb** [comment]
Looks like we need the output with `--property` instead to remove the first field, based on https://github.com/ceph/ceph/blob/master/src/ceph-volume/ceph_volume/util/disk.py#L226-L227

**Comment by alfredodeza** [comment]
Seems like there is some room to still get this incorrectly for some manufacturers. Are we fine by being correct in a bunch of cases and be uncertain about the rest?

**Comment by liewegas** [comment]
I agree.  I don't think we really have a choice, though!  It's either this, or we give up and use the WWID, which is just some hex gibberish.

I think this will work for the vast majority of cases, and we can whittle away at the outliers over time.

**Comment by alfredodeza** [comment]
jenkins test ceph-volume tox

**Comment by alfredodeza** [comment]
The lack of tests for this is killing us :( These changes just broke everything in master for ceph-volume:

    [root@osd0 vagrant]# CEPH_VOLUME_DEBUG=1 ceph-volume lvm batch --bluestore --report /dev/sdb
    usage: ceph-volume lvm batch [-h] [--bluestore] [--filestore] [--report]
                                 [--yes] [--format {json,pretty}] [--dmcrypt]
                                 [--crush-device-class CRUSH_DEVICE_CLASS]
                                 [--no-systemd]
                                 [--osds-per-device OSDS_PER_DEVICE]
                                 [--block-db-size BLOCK_DB_SIZE]
                                 [--journal-size JOURNAL_SIZE] [--prepare]
     ceph-volume lvm batch: error: argument DEVICES: invalid <ceph_volume.util.arg_validators.ValidDevice object at 0x7f68072497d0> value: '/dev/sdb'


The error is eaten up by argparse:


    >>> from ceph_volume.util import device
    >>> device.Device('/dev/sdb')
     Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/usr/lib/python2.7/site-packages/ceph_volume/util/device.py", line 92, in __init__
        self.device_id = self._get_device_id()
      File "/usr/lib/python2.7/site-packages/ceph_volume/util/device.py", line 198, in _get_device_id
        dev_id = '_'.join(p['ID_MODEL'], p['ID_SERIAL_SHORT'])
    TypeError: join() takes exactly one argument (2 given)

**Comment by LenzGr** [comment]
> These changes just broke everything in master for ceph-volume

Looks like @sebastian-philipp has just submitted #25469 to fix this.

**Comment by alfredodeza** [comment]
@liewegas just want to confirm that we shouldn't backport the C++ changes for this right? (similar to https://github.com/ceph/ceph/pull/25201 )

**Comment by liewegas** [comment]
> @liewegas just want to confirm that we shouldn't backport the C++ changes for this right? (similar to #25201 )

Correct!

**Pull request merged**
