### PR TITLE
rgw/notification: set correct type to "post" and "copy" notifications

### PR DESCRIPTION
**Pull request by yuvalif**
~added 2 commits to the PR so that tests would pass, however, they address completely different issues.~

@dang could you please help review this commit: 00789848391c0a46d4cdca126f08c69fbe76a508
~@tschoonj could you please help review this commit: bc6e38ffff8c5f7cd002fc55ae661d210cd7e671~
~@TRYTOBE8TME this PR include merging the changes between these 2 PR:~
~* https://github.com/ceph/ceph/pull/39139~
~* https://github.com/ceph/ceph/pull/39392~
---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Review by tschoonj — APPROVED** [review]
Looks good. I had to do the same thing to get it working but didn't want to commit it in at the time.

**Comment by yuvalif** [comment]
jenkins test make check

**Review by dang — APPROVED** [review]
LGTM

**Review by TRYTOBE8TME — APPROVED** [review]

**Comment by yuvalif** [comment]
split the PR to include only the fix to: https://tracker.ceph.com/issues/49799
@tschoonj and @TRYTOBE8TME I aplogize, but will create a new PR for the test fixes (merging the bucket notification work with the amqp ssl tests).

for this, teuthology is passing: http://pulpito.front.sepia.ceph.com/yuvalif-2021-04-06_11:39:10-rgw:multisite-wip-yuval-fix-49799-distro-basic-gibba/ (except one dead test)

**Comment by yuvalif** [comment]
jenkins test make check

**Pull request merged**
