### PR TITLE
rgw:when creating a user and the -- uid does not exist, the error message is unreasonable

### PR DESCRIPTION
**Pull request by ybwang0211**
rgw:when creating a user and the -- uid does not exist, the error message is unreasonable

When creating a user, when --uid is empty, the error message is "user.init failed: (13) Permission denied", but a more reasonable prompt should be "ERROR: --uid required"

Signed-off-by: wangyingbin <ybwang0211@163.com>

Fix: https://tracker.ceph.com/issues/53431

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Review by dang — COMMENTED** [review]
First off, this needs to be submitted against master, not against nautilus.  However, I'm not convinced this is the correct solution.  The problem is that RGWUserAdminOpState initializes it's user to ANON instead of empty.  This means that if you pass subuser and not user, it won't use the subuser, or indeed pass any of the user.empty() checks.  It's been this way forever, however, so I'm not entirely sure what's the best way to fix it.  If the empty checks work properly, then you can just pass access_key instead of UID (like the actual check in the like above indicates) and it would work.

I suspect the best solution is just to change the user_id.empty() checks in RGWUser::init() to check if the ID is anonymous.  @cbodley what do you think?

**Comment by cbodley** [comment]
> The problem is that RGWUserAdminOpState initializes it's user to ANON instead of empty.

any idea why it does that? the anonymous user shouldn't actually exist, so why would admin commands ever operate on it?

**Comment by cbodley** [comment]
> I suspect the best solution is just to change the user_id.empty() checks in RGWUser::init() to check if the ID is anonymous.

i tend to agree that this approach is the least likely to break other commands

**Comment by dang** [comment]
> > The problem is that RGWUserAdminOpState initializes it's user to ANON instead of empty.
> 
> any idea why it does that? the anonymous user shouldn't actually exist, so why would admin commands ever operate on it?

It appears to have "always" been this way (at least for 8 years)

**Comment by ybwang0211** [comment]
您好，这里是王迎彬的邮箱，已经收到您的邮件，谢谢。

**Pull request closed without merging**
