### PR TITLE
pacific: rgw: use tenant id from the uri on anonymous access

### PR DESCRIPTION
**Pull request by mdw-at-linuxbox**
[
This is a backport to pacific of this PR: https://github.com/ceph/ceph/pull/38319
]

When anonymous tries access public bucket, it gets 404,
because rgw doesn't check tenant correctly.

Fixes: https://tracker.ceph.com/issues/48001 https://tracker.ceph.com/issues/48382
Signed-off-by: Rafał Wądołowski <rwadolowski@cloudferro.com>
(cherry picked from commit 9a911f0cb5f7f4511274cf44d23b74c96f1a3863)

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests
- Teuthology
  - [ ] Completed teuthology run
  - [ ] No teuthology test necessary (e.g., documentation)

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Review by dang — APPROVED** [review]

**Comment by cbodley** [comment]
(DNM until the master PR merges)

**Comment by cbodley** [comment]
note that https://github.com/ceph/ceph/pull/38319 has failed qa

**Comment by frittentheke** [comment]
> note that #38319 has failed qa

I believe that has been resolved. Would be great to have this issue fixed for Quincy and Pacific as well.

**Comment by cbodley** [comment]
merged better fix in https://github.com/ceph/ceph/pull/47341, thanks @mdw-at-linuxbox!

**Pull request closed without merging**
