### PR TITLE
DNM: Fix libcephfs_jni

### PR DESCRIPTION
**Pull request by qiuyi21**
1. Fix redefined warning during compiling

2. Can get inode by CephMount.stat

### CODE REVIEW

**Comment by tchaikov** [comment]
@qiuyi21 could you file a ticket on tracker and target your change to master instead? if you believe that this change should be backported to jewel, you can update the "Backport" field of the ticket.

also could you prefix the title of your commit message with the subcomponent your are changing ? see https://github.com/ceph/ceph/blob/master/SubmittingPatches.rst#3-describe-your-changes. and 
could you add a "`Signed-off-by`" line at the end of your commit message? "git commit -s" will do the trick for you. see https://github.com/ceph/ceph/blob/master/SubmittingPatches.rst#1-sign-your-work

**Comment by dachary** [comment]
jenkins test this please (change base to jewel-next)

**Comment by dachary** [comment]
@qiuyi21 ping ?

**Comment by tchaikov** [comment]
i am closing this PR, please reopen it once you want to continue working on it.

**Pull request closed without merging**
