### PR TITLE
nautilus: mon/OSDMonitor: Use generic priority cache tuner for mon caches

### PR DESCRIPTION
**Pull request by sseshasa**
Use priority cache manager to tune inc, full and rocksdb caches.
This PR pulls in all the necessary commits from the master related
to priority cache manager[1] and related changes. The changes
introduced in src/OSDMonitor.* uses the priority cache manager
interfaces to tune the incremental, full and rocksdb caches.

[1] The priority cache manager is under src/common/PriorityCache.*

Fixes: https://tracker.ceph.com/issues/41238
Signed-off-by: Sridhar Seshasayee <sseshasa@redhat.com>

## Checklist
- [x] References tracker ticket
- [x] Updates documentation if necessary
- [x] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by sseshasa** [comment]
retest this please

**Comment by smithfarm** [comment]
Thanks, @sseshasa - is there a reason why the wip branch is on ceph/ceph.git instead of in your fork?

**Comment by sseshasa** [comment]
> Thanks, @sseshasa - is there a reason why the wip branch is on ceph/ceph.git instead of in your fork?

I have so far based my branches on ceph/ceph.git. I can change over to creating a clone of my
fork if that is the recommended way.

I followed the instructions as mentioned here,
https://tracker.ceph.com/projects/ceph-releases/wiki/HOWTO_backport_commits

I created the branch using `git checkout -b wip-41238-nautilus origin/nautilus`. If the branching is not proper, I can redo this PR again. Please let me know.

**Comment by sseshasa** [comment]
> One more thing - for your next backport, could you please limit your edits of the commit message to the part _after_ the `(cherry picked from . . .)` line?
> 
> Rationale: The accepted backporting protocol of the Ceph project is: "in the cherry-pick commit message, preserve the master commit message exactly as it is. Any additional information can be added after the `(cherry picked from . . .)` line."

Sure, henceforth I will adhere to the above instructions.

**Comment by smithfarm** [comment]
@seshasa Pretty much everyone uses their own fork. In the past, when the number of core developers was much smaller, they used ceph/ceph.git but there were problems with huge numbers of dead branches building up there, and IIRC Sage eventually cleaned it all up and asked that folks use their own forks for PRs.

But I don't think you need to re-do this PR ;-)

**Comment by smithfarm** [comment]
@sseshasa Also, thanks for following https://tracker.ceph.com/projects/ceph-releases/wiki/HOWTO_backport_commits - I will update that to clarify this point. The idea is not to use the remote repo called `origin` but rather to use the one that corresponds to your fork, whatever the name might be.

**Comment by sseshasa** [comment]
@markhpc @jdurgin @tchaikov @trociny Request your review for this backport when you get time. Thanks!

**Comment by smithfarm** [comment]
@sseshasa Also, would it make sense to do https://tracker.ceph.com/issues/41810 right here in this PR?

**Comment by sseshasa** [comment]
> @sseshasa Also, would it make sense to do https://tracker.ceph.com/issues/41810 right here in this PR?

@smithfarm since there's no functional dependency between this and https://tracker.ceph.com/issues/41810, it would be better to backport them separately. Also, this backport PR takes higher priority than the other (41810).

**Comment by smithfarm** [comment]
@sseshasa You don't have to test this PR. It's already flagged for integration testing as part of 14.2.5 preparation. @yuriw tests the backport PRs in batches to save test lab resources.

**Comment by sseshasa** [comment]
> @sseshasa You don't have to test this PR. It's already flagged for integration testing as part of 14.2.5 preparation. @yuriw tests the backport PRs in batches to save test lab resources.

@smithfarm Sure, I won't run the suites. I will run some tests on a locked machine (mira).

**Comment by neha-ojha** [comment]
> @sseshasa You don't have to test this PR. It's already flagged for integration testing as part of 14.2.5 preparation. @yuriw tests the backport PRs in batches to save test lab resources.

@yuriw This PR is a priority for us, can you please include it in your next N batch?

**Comment by yuriw** [comment]
[wip-yuri8-testing-2019-11-08-2045-nautilus](https://trello.com/c/1zza4G7A/754-wip-yuri8-testing-2019-11-08-2045-nautilus)

**Pull request merged**
