### PR TITLE
rgw: use separate http_manager for read_sync_status

### PR DESCRIPTION
**Pull request by shashalu**
concurrent users of read_sync_status() use different cr managers, when get_resource must
use http_manager related to the cr manager.

Signed-off-by: Shasha Lu <lu.shasha@eisoo.com>

### CODE REVIEW

**Comment by shashalu** [comment]
@cbodley 
Hi, could you review this for me, thx

**Comment by cbodley** [comment]
@shashalu did this result in a crash?

**Comment by shashalu** [comment]
@cbodley 
It won't crash. But when use radosgw-admin to init data sync, RGWCoroutinesManager::run will stuck after the first 100(RGW_ASYNC_OPS_MGR_WINDOW) RGWReadRemoteDataLogShardInfo requests sent.
The completion_mgr of RGWCoroutinesManager can't not get the completed req, because those reqs was sent by other http_manager.

**Comment by cbodley** [comment]
hi @shashalu, we'd like to backport this fix to jewel and kraken, so i opened a ticket at http://tracker.ceph.com/issues/19236. can you please add this to your commit message?
```
Fixes: http://tracker.ceph.com/issues/19236
```

**Comment by shashalu** [comment]
@cbodley  ok, already updated.

**Comment by cbodley** [comment]
thank you!

**Pull request merged**
