### PR TITLE
doc/cephfs: add note about CephFS extended attributes and getfattr

### PR DESCRIPTION
**Pull request by zdover23**
Supersedes https://github.com/ceph/ceph/pull/50060

Add a note on the fact that CephFS extended attributes are not printed by "getfattr /some/cephfs/dir/ -d -m -" even when the CephFS directory has some extended attributes set on it.

https://lists.ceph.io/hyperkitty/list/ceph-users@ceph.io/thread/6ENI42ZMHTTP2OONBRD7FDP7LQBC4P2E/

Primary Author: Rishabh Dave <ridave@redhat.com>
Co-author: Anthony D'Atri <anthony.datri@gmail.com>
Signed-off-by: Zac Dover <zac.dover@proton.me>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [x] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [x] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Review by anthonyeleven — APPROVED** [review]

**Review by anthonyeleven — APPROVED** [review]
lgtm, I love formatting so I'd backtick the system call.

**Comment by zdover23** [comment]
> lgtm, I love formatting so I'd backtick the system call.

Yeah, let's do that. (I've just done it.)

**Review by rishabh-d-dave — APPROVED** [review]
Looks better.

**Comment by rishabh-d-dave** [comment]
By the way, why did we close #50060? I would've incorporated your changes (I couldn't right away because I am located in a different time zone).

**Comment by zdover23** [comment]
> By the way, why did we close #50060? I would've incorporated your changes (I couldn't right away because I am located in a different time zone).

@rishabh-d-dave: I meant no offense. It was a good change that was failing the docs build because of a bad indent, and it was something that I could get into the docs sooner rather than later without having to trouble you to tinker with .rst formatting. If I've thrown off your metrics, I'll give you one of my changes. If you'd prefer that I leave these things alone so that you can tidy them up yourself in the future, I will, with apologizes for this overstep.

**Comment by zdover23** [comment]
https://github.com/ceph/ceph/pull/50068 - Quincy backport
https://github.com/ceph/ceph/pull/50069 - Pacific backport

**Comment by rishabh-d-dave** [comment]
@zdover23 

> > By the way, why did we close #50060? I would've incorporated your changes (I couldn't right away because I am located in a different time zone).
> 
> @rishabh-d-dave: I meant no offense. 

None taken. I was curious because this was very unusual.

> It was a good change that was failing the docs build because of a bad indent, and it was something that I could get into the docs sooner rather than later without having to trouble you to tinker with .rst formatting. If I've thrown off your metrics, I'll give you one of my changes. If you'd prefer that I leave these things alone so that you can tidy them up yourself in the future, I will, with apologizes for this overstep.

I like writing docs and I don't mind writing/editing RST files.  Don't worry about metrics, it's nothing major so I don't mind. And no need for apologies too. Feel free to do this next if the PR needs to be merged super-urgently and I can't get it done in time. Otherwise, I like going through the review process, it brings opportunities to learn new things  :)

**Pull request merged**
