### PR TITLE
ceph_volume_client: evict client also based on mount path

### PR DESCRIPTION
**Pull request by ajarr**
Evict clients based on not just their auth ID, but also based on the
volume path mounted. This is needed for the Manila use-case, where
the clients using an auth ID are denied further access to a share.

Fixes: http://tracker.ceph.com/issues/15045

Signed-off-by: Ramana Raja <rraja@redhat.com>

### CODE REVIEW

**Comment by gregsfortytwo** [comment]
Can you describe how you tested this? :)

**Comment by ajarr** [comment]
Tested by https://github.com/ceph/ceph-qa-suite/pull/968

**Comment by gregsfortytwo** [comment]
@jcsp, your review

**Comment by gregsfortytwo** [comment]
Do you guys want a manila or similar label in github? I'm trying to decide if that's too fine-grained, but it's a project with sort of its own timelines so I'm thinking maybe it's good.

**Pull request merged**
