### PR TITLE
octopus:ImportError: cannot import name 'environmentfilter' from 'jinja2'

### PR DESCRIPTION
**Pull request by RaminNietzsche**
Date:      Sun Apr 10 15:16925 2022 +0430

On branch fix_jinja2_version
Changes to be committed:
	modified:   admin/doc-requirements.txt

Signed-off-by: Ramin Najarbashi <ramin.najarbashi@gmail.com>

## Checklist
- Component impact
  - [X] No impact that needs to be tracked
- Documentation
  - [X] No doc update is appropriate
- Tests
  - [X] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by RaminNietzsche** [comment]
Merged with https://github.com/ceph/ceph/pull/45838

**Review by idryomov — CHANGES_REQUESTED** [review]
We do backports by cherry picking changes from the master branch with `git cherry-pick -x` so that the original commit hash is recorded in the changelog.  E.g. for `admin/doc-read-the-docs.txt` change, you would need to do `git cherry-pick -x 6a1dd3a8a2f3dc9fe8615d402c9041273516ff89`.

I don't see the `Jinja2 < 3.1` change is master though.  Is master not affected, if so why?

**Comment by ideepika** [comment]
> We do backports by cherry picking changes from the master branch with `git cherry-pick -x` so that the original commit hash is recorded in the changelog. E.g. for `admin/doc-read-the-docs.txt` change, you would need to do `git cherry-pick -x 6a1dd3a8a2f3dc9fe8615d402c9041273516ff89`.
> 
> I don't see the `Jinja2 < 3.1` change is master though. Is master not affected, if so why?

@idryomov perhaps we need octopus backport for https://tracker.ceph.com/issues/55294 https://github.com/ceph/ceph/pull/45881#issuecomment-1097184438  or if we do not want to update sphnix version then pinning Jinja version might help.

**Comment by idryomov** [comment]
FWIW @ljflores is looking into bumping the sphinx version in https://github.com/ceph/ceph/pull/45972.

**Comment by ljflores** [comment]
@RaminNietzsche this might be a more straight-forward solution for the readthedocs failure: #46219. The Docs build failure has already been fixed by bumping the Sphinx version.

**Pull request closed without merging**
