### PR TITLE
docs/start: fixes typo in hardware recommendation docs

### PR DESCRIPTION
**Pull request by sebastian-schmid**
## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [x] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [x] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Review by ljflores — COMMENTED** [review]
Hi @sebastian-schmid, the change looks good, but your commit should be amended to align with Ceph project conventions:

1. Modify the title of your commit to be prefixed by the component you are modifying, in your case "docs/start". I would also make title more descriptive like your PR title: `docs/start: fixes typo in hardware recommendation docs`. See https://github.com/ceph/ceph/blob/master/SubmittingPatches.rst#commit-title for more details.
2. Sign off with your name and email, like so: `Signed-off-by: Random J Developer <random@developer.example.org>`. See https://github.com/ceph/ceph/blob/master/SubmittingPatches.rst#developer-s-certificate-of-origin-1-1 for more details.

**Comment by sebastian-schmid** [comment]
Thank you @ljflores for guiding me through my first ceph contribution.

In the same file there is a headline "OSDs (ceph-osd)" which has no content, I am not sure if this is intended, but doesn't make sense in my eyes. What do you think?

If this is obsolete should I include this in this pull request or should I open another one for that?

**Comment by ljflores** [comment]
> Thank you @ljflores for guiding me through my first ceph contribution.
> 
> In the same file there is a headline "OSDs (ceph-osd)" which has no content, I am not sure if this is intended, but doesn't make sense in my eyes. What do you think?
> 
> If this is obsolete should I include this in this pull request or should I open another one for that?

@sebastian-schmid the commit looks great now! And thanks for bringing that other part to our attention. I just took a look, and it seems that portion of the documentation was removed here https://github.com/ceph/ceph/commit/3305a0732403ba7fe58fe6248868b7711bbccc72. I'll ping @markhpc here since he was the author of that commit; he might have some ideas.

**Comment by ljflores** [comment]
Hey @sebastian-schmid, I checked with @markhpc, and it looks like the info that was originally under that header is covered under the Memory section now. So it can be removed. I would put this removal and your typo fix all in the same commit.

**Comment by sebastian-schmid** [comment]
@ljflores the one commit now includes both changes

**Review by ljflores — APPROVED** [review]
Thanks @sebastian-schmid! Looks great.

**Comment by zdover23** [comment]
Though this PR is merged, it's a good place to call attention to the February 2022 Hardware Recommendations rewrite project.

In the first week of Feburary, the Hardware Recommendations page will be updated for 2022. The last time that these hardware recommendations were made, Barack Obama was the president of the United States. So it's time for these to be updated.

Anyone who wants to join the conversation about this can do so here:

https://pad.ceph.com/p/docs_hardware_recs_rewrite_overview_2021_dec

**Comment by zdover23** [comment]
https://github.com/ceph/ceph/pull/48392 - Pacific backport

**Comment by zdover23** [comment]
This change was present already in the Quincy branch on 07 Oct 2022.

**Pull request merged**
