### PR TITLE
tools/rados: Fix extra NL in getxattr

### PR DESCRIPTION
**Pull request by aclamk**
Recent code refactor caused extra "std::endl" output.
Detected by teuthology:
https://pulpito.ceph.com/akupczyk-2024-08-02_13:56:25-rados-aclamk-testing-phoebe-2024-08-01-1249-distro-default-smithi/7832308/

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [x] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Review by ronen-fr — APPROVED** [review]

**Review by rzarzynski — APPROVED** [review]

**Review by vshankar — APPROVED** [review]

**Comment by vshankar** [comment]
Just FYI - https://tracker.ceph.com/issues/67336

**Comment by vshankar** [comment]
This PR is under test in [https://tracker.ceph.com/issues/67368](https://tracker.ceph.com/issues/67368).

**Review by rishabh-d-dave — APPROVED** [review]
@aclamk IMO, it'll be nice to add `introduced-by` tag in commit and have tracker ticket for this so that this commit can also be backported. The commit that introduced this issue has been backported to Squid and will be to Reef. See: https://tracker.ceph.com/issues/66286.

**Review by vshankar — APPROVED** [review]
https://tracker.ceph.com/projects/cephfs/wiki/Main#wip-vshankar-testing-20240806162829-debug

**Comment by vshankar** [comment]
Doh, I didn't notice @ljflores adding testing tag and merged the change as it passed fs suite tests.

@ljflores If you notice that tests still fail in other suites, feel free to revert this.merge.

**Comment by NitzanMordhai** [comment]
Rados approved: https://tracker.ceph.com/projects/rados/wiki/MAIN#httpstrackercephcomissues67523

**Pull request merged**
