### PR TITLE
reef: qa: add support/qa for cephfs-shell on CentOS 9 / RHEL9

### PR DESCRIPTION
**Pull request by batrick**
Supersedes https://github.com/ceph/ceph/pull/54865

Fixes: https://tracker.ceph.com/issues/63782
Original-issue: https://tracker.ceph.com/issues/43393
Original-PR: https://github.com/ceph/ceph/pull/54726

### CODE REVIEW

**Comment by batrick** [comment]
This PR is under test in [https://tracker.ceph.com/issues/65699](https://tracker.ceph.com/issues/65699).

**Comment by batrick** [comment]
I can't seem to get a reef build to complete. I get errors like:

```
make: *** [Makefile:146: all] Error 2
error: Bad exit status from /var/tmp/rpm-tmp.DbJqR0 (%build)


RPM build errors:
    Macro expanded in comment on line 2638: %{_mandir}/man8/ceph-node-proxy.8*

    Bad exit status from /var/tmp/rpm-tmp.DbJqR0 (%build)
```

but  I cannot immediately tell why.

**Comment by batrick** [comment]
This PR is under test in [https://tracker.ceph.com/issues/66212](https://tracker.ceph.com/issues/66212).

**Comment by batrick** [comment]
https://tracker.ceph.com/issues/66212#note-1

This is ready for general QA.

**Comment by joscollin** [comment]
Tested in https://tracker.ceph.com/issues/66510

**Review by joscollin — APPROVED** [review]

**Pull request merged**
