### PR TITLE
rgw: fix zone did't update realm_id when added to zonegroup

### PR DESCRIPTION
**Pull request by tianshan**
Fixes: http://tracker.ceph.com/issues/17995
Signed-off-by: Tianshan Qu <tianshan@xsky.com>

### CODE REVIEW

**Comment by tianshan** [comment]
ping @yehudasa , is this looks fine?

**Comment by yehudasa** [comment]
@tianshan at first glance it makes sense, @oritwas will review it closer. Thanks!

**Comment by oritwas** [comment]
jenkins test this please

**Comment by yuriw** [comment]
ready for merge http://pulpito.ceph.com/yuriw-2017-07-13_21:26:32-rgw-wip-yuri-testing3_2017_7_14-distro-basic-smithi/

**Pull request merged**
