### PR TITLE
pacific: mgr/dashboard: crushmap tree doesn't display crush type other than root

### PR DESCRIPTION
**Pull request by avanthakkar**
backport tracker: https://tracker.ceph.com/issues/51343

---

backport of https://github.com/ceph/ceph/pull/41758
parent tracker: https://tracker.ceph.com/issues/50971

this backport was staged using ceph-backport.sh version 16.0.0.6848
find the latest version at https://github.com/ceph/ceph/blob/master/src/script/ceph-backport.sh

### CODE REVIEW

**Comment by avanthakkar** [comment]
jenkins test make check

**Comment by avanthakkar** [comment]
jenkins test api

**Comment by avanthakkar** [comment]
jenkins test api

**Comment by avanthakkar** [comment]
jenkins test dashboard

**Review by alfonsomthd — APPROVED** [review]

**Review by epuertat — APPROVED** [review]

**Pull request merged**
