### PR TITLE
mimic: mds: reset heartbeat map at potential time-consuming places

### PR DESCRIPTION
**Pull request by ukernel**
https://tracker.ceph.com/issues/26886

### CODE REVIEW

**Comment by smithfarm** [comment]
jenkins re-test this please

**Comment by smithfarm** [comment]
@batrick Please review (conflict resolution)

**Comment by smithfarm** [comment]
```
In file included from /home/jenkins-build/build/workspace/ceph-pull-requests/src/mds/Beacon.cc:25:0:
/home/jenkins-build/build/workspace/ceph-pull-requests/src/mds/MDSRank.h:308:30: error: 'MDSInternalContextBase::vec' has not been declared
     void queue_waiters_front(MDSInternalContextBase::vec& ls) {
                              ^~~~~~~~~~~~~~~~~~~~~~
/home/jenkins-build/build/workspace/ceph-pull-requests/src/mds/MDSRank.h: In member function 'void MDSRank::queue_waiters_front(int&)':
/home/jenkins-build/build/workspace/ceph-pull-requests/src/mds/MDSRank.h:309:55: error: no matching function for call to 'std::__cxx11::list<MDSInternalContextBase*>::splice(std::__cxx11::list<MDSInternalContextBase*>::iterator, int&)'
       finished_queue.splice(finished_queue.begin(), ls);
                                                       ^
In file included from /usr/include/c++/7/list:63:0,
                 from /home/jenkins-build/build/workspace/ceph-pull-requests/src/include/buffer.h:43,
                 from /home/jenkins-build/build/workspace/ceph-pull-requests/src/include/encoding.h:38,
                 from /home/jenkins-build/build/workspace/ceph-pull-requests/src/include/uuid.h:8,
                 from /home/jenkins-build/build/workspace/ceph-pull-requests/src/include/types.h:21,
                 from /home/jenkins-build/build/workspace/ceph-pull-requests/src/msg/msg_types.h:21,
                 from /home/jenkins-build/build/workspace/ceph-pull-requests/src/common/entity_name.h:20,
                 from /home/jenkins-build/build/workspace/ceph-pull-requests/src/common/config.h:21,
                 from /home/jenkins-build/build/workspace/ceph-pull-requests/src/common/dout.h:22,
                 from /home/jenkins-build/build/workspace/ceph-pull-requests/src/mds/Beacon.cc:16:
/usr/include/c++/7/bits/stl_list.h:1424:7: note: candidate: void std::__cxx11::list<_Tp, _Alloc>::splice(std::__cxx11::list<_Tp, _Alloc>::const_iterator, std::__cxx11::list<_Tp, _Alloc>&&) [with _Tp = MDSInternalContextBase*; _Alloc = std::allocator<MDSInternalContextBase*>; std::__cxx11::list<_Tp, _Alloc>::const_iterator = std::_List_const_iterator<MDSInternalContextBase*>]
       splice(const_iterator __position, list&& __x) noexcept
       ^~~~~~
/usr/include/c++/7/bits/stl_list.h:1424:7: note:   no known conversion for argument 2 from 'int' to 'std::__cxx11::list<MDSInternalContextBase*>&&'
...
...
...
```

**Comment by smithfarm** [comment]
@ukernel @batrick I updated the PR description to reflect that this PR resolves two backport issues. Please double-check that this is correct.

**Comment by yuriw** [comment]
[wip-yuri4-testing-2018-10-15-0002-mimic](https://trello.com/c/hEUw3v8h/440-wip-yuri4-testing-2018-10-15-0002-mimic)

**Pull request merged**
