### PR TITLE
nautilus: mgr/prometheus: assign a value to osd_dev_node when obj_store is not filestore or bluestore

### PR DESCRIPTION
**Pull request by jan--f**
backport tracker: https://tracker.ceph.com/issues/42766

---

backport of https://github.com/ceph/ceph/pull/30534
parent tracker: https://tracker.ceph.com/issues/42017

this backport was staged using ceph-backport.sh version 15.0.0.6814
find the latest version at https://github.com/ceph/ceph/blob/master/src/script/ceph-backport.sh

### CODE REVIEW

**Comment by jan--f** [comment]
Yeah my bad...commits should have be squashed before merging to master...apologies.

**Comment by yuriw** [comment]
[wip-yuri3-testing-2020-01-08-2028-nautilus](https://trello.com/c/5X40EXaX/796-wip-yuri3-testing-2020-01-08-2028-nautilus)

**Comment by yuriw** [comment]
[wip-yuri3-testing-2020-01-08-2028-nautilus](https://trello.com/c/5X40EXaX/796-wip-yuri3-testing-2020-01-08-2028-nautilus)

**Comment by tchaikov** [comment]
jenkins test make check

**Pull request merged**
