### PR TITLE
implement snapshot rename

### PR DESCRIPTION
**Pull request by xinxinsh**

### CODE REVIEW

**Comment by dillaman** [comment]
Can you also add the new feature to the librbd Python bindings?

**Comment by xinxinsh** [comment]
@dillaman ， updated, pls help review

**Comment by xinxinsh** [comment]
@dillaman , updated, pls help review

**Comment by xinxinsh** [comment]
@dillaman , thanks for review, updated

**Comment by dillaman** [comment]
LGTM -- we need to wait for the master branch to open for new features before merging.

Note to self: need to update #5735 to support this new feature

**Pull request merged**
