### PR TITLE
Backport of pull request 3634 to hammer : Added --striper option to rados command line

### PR DESCRIPTION
**Pull request by sponce**
Although libradosstriper has been introduced in giant, there has been no way to use it from the command line via the rados command. This is now available via --striper flag.

### CODE REVIEW

**Comment by dachary** [comment]
@sponce I think this will not be in hammer because we are past feature freeze. I'll let @liewegas decide because I tend to be too rigid ;-) Either way the original patch https://github.com/ceph/ceph/pull/3634 needs minimal testing before it can merged.

**Comment by sponce** [comment]
I'm working on the testing. I'm almost there, but it took me some time to understand how you write these bash tests.
Concerning the release. I know I'm late, but it's not a problem to skip that for the first hammer. It can be merged into the next hammer release.

**Comment by dachary** [comment]
@sponce my understanding is that after a release is published only bug fixes are allowed. Each "point release" (i.e. v0.80.1, v0.80.2 etc.) is supposed to be only about fixing bugs. New features are committed to master and will be in the next stable release.

**Comment by sponce** [comment]
Closed and replaced by pull request #3653 as this one was not based on the right branch (master rather than hammer).

**Comment by sponce** [comment]
@dachary : if you could assign #3653 to @liewegas as you did for this one so that he can judge whether to include it in (a future) hammer ?
I had done the same clicking mistake as for the other pull request here : it was based on master rather than hammer, so I had to replace it.

**Pull request closed without merging**
