### PR TITLE
msg: take another few steps toward addrvec-based interfaces

### PR DESCRIPTION
**Pull request by liewegas**
- connect_to instead of get_connection
- send_to instead of send_message
- avoid entity_inst_t where we can

There's another pile of patches that takes this the rest of the way, but it's not really mergeable until the messenger changes are ready (msgr2 addrs aren't passed across the messenger to the peer, which breaks mon quorum).

### CODE REVIEW

**Comment by rjfd** [comment]
The changes look good but I have one doubt. Since the `connect_to` and `send_to` now receives a list of addresses, who decides, and how, which address to use (currently the legacy one is chosen)?

**Comment by liewegas** [comment]
The idea is it is the client's option.  Generally it will be a deterministic choice based on what is supported.  e.g., msgr2 is also preferred if both ends support it.  If there are ipv4 and v6 choices, it would be less deterministic, but i think making dual stack work is a secondary priority.

**Comment by tchaikov** [comment]
retest this please.

**Comment by liewegas** [comment]
retest this please

**Pull request merged**
