### PR TITLE
 [DNM] kraken: kernel client feature mismatch on latest master test runs

### PR DESCRIPTION
**Pull request by shinobu-x**
http://tracker.ceph.com/issues/18842

### CODE REVIEW

**Comment by shinobu-x** [comment]
Old one:
https://github.com/ceph/ceph/pull/13486

**Comment by idryomov** [comment]
This won't apply once #13485 is merged.  I'm not sure how @smithfarm usually handles these, you'll either need to wait until #13485 is merged and rebase or cherry-pick ab558bbf2956 into wip-18644-kraken.

**Comment by smithfarm** [comment]
@shinobu-x Please:

* cherry-pick ab558bb into wip-18644-kraken (#13485) and `git push` to update the PR (#13485)
* add http://tracker.ceph.com/issues/18842 to the PR description (#13485)
* close this PR (#13593)

Thanks!

**Comment by shinobu-x** [comment]
@smithfarm Thank you for your message. I will follow you.

**Pull request closed without merging**
