### PR TITLE
ceph-detect-init helper and associated tests

### PR DESCRIPTION
**Pull request by dachary**
this also lays out the foundations for integrating the existing python code into make check and allow running tox without network access

### CODE REVIEW

**Comment by dachary** [comment]
Integration tests pass
<pre>
src/ceph-detect-init$ tox -e integration
============================= test session starts ==============================
platform linux2 -- Python 2.7.6 -- py-1.4.26 -- pytest-2.7.0 -- /home/loic/software/ceph/ceph/src/ceph-detect-init/.tox/integration/bin/python2
rootdir: /home/loic/software/ceph/ceph/src/ceph-detect-init, inifile: 
collected 12 items 

integration/test_main.py::TestCephDetectInit::test_centos_6 PASSED
integration/test_main.py::TestCephDetectInit::test_centos_7 PASSED
integration/test_main.py::TestCephDetectInit::test_debian_jessie PASSED
integration/test_main.py::TestCephDetectInit::test_debian_sid PASSED
integration/test_main.py::TestCephDetectInit::test_debian_squeeze PASSED
integration/test_main.py::TestCephDetectInit::test_debian_wheezy PASSED
integration/test_main.py::TestCephDetectInit::test_fedora_21 PASSED
integration/test_main.py::TestCephDetectInit::test_opensuse_13_1 PASSED
integration/test_main.py::TestCephDetectInit::test_opensuse_13_2 PASSED
integration/test_main.py::TestCephDetectInit::test_ubuntu_12_04 PASSED
integration/test_main.py::TestCephDetectInit::test_ubuntu_14_04 PASSED
integration/test_main.py::TestCephDetectInit::test_ubuntu_15_04 PASSED

========================= 12 passed in 111.22 seconds ==========================
___________________________________ summary ____________________________________
  integration: commands succeeded
  congratulations :)
</pre>

**Comment by dachary** [comment]
@thanks for your review :-)

**Comment by dachary** [comment]
http://ceph.com/gitbuilder.cgi passes (branch wip-init-system-detection)

**Comment by dachary** [comment]
@ktdreyer I would very much like your input on the packaging side of this series: https://github.com/dachary/ceph/commit/b4a441a0ed78bb8d744332ed708304e7467312f4

**Comment by dachary** [comment]
@liewegas this is osynge ceph-detect-init with integration tests and unit tests. I turned out to be significant work for a simple change, reason why this kind of code was untested so far: the test infrastructure was missing. I believe these tests can be re-used or mimicked to significantly improve the tests of other python scripts included in the ceph source directory.

**Comment by liewegas** [comment]
:+1:

**Comment by trhoden** [comment]
Sorry, I should have seen this one and commented earlier.

I question the reason for --use_rhceph in ceph-detect-init.  I see that a lot of the code is borrowed from ceph-deploy, so that is probably the origin for this, but ceph-deploy is taking different code paths in the relevant cases. 

For choosing the init system, are we actually going to treat CentOS and RHEL + RH ceph packages differently?  I wouldn't think so -- Whether you are running upstream packages or Red Hat packages on RHEL, we are going to use the same init system.

Am I wrong?

**Comment by dachary** [comment]
@trhoden the code is an exact copy of the current ceph-deploy code, only with a few unrelevant variables stripped of. I copy / pasted use_rhceph under the idea that I was refactoring a sub directory into ceph. And it would have be quite difficult to change the behavior simultaneously. It's worth at least a mailing list thread (I mean the use_rhceph thing), don't you think ?

**Pull request merged**
