### PR TITLE
rgw: beast frontend no longer experimental

### PR DESCRIPTION
**Pull request by cbodley**

### CODE REVIEW

**Comment by cbodley** [comment]
jenkins test make check

**Comment by theanalyst** [comment]
jenkins test this please

**Comment by cbodley** [comment]
jenkins test make check

**Comment by cbodley** [comment]
rebased - hopefully the run-tox-mgr-dashboard failures go away. also removed the `enable experimental unrecoverable data corrupting features` override in the qa suite

**Comment by cbodley** [comment]
lots of run-tox-mgr-dashboard failures from make check. @mattbenjamin, would you consider merging with your override?

**Comment by rjfd** [comment]
@cbodley a fix for the dashboard unit tests was merged last night, you may trigger the jenkins checks again.

**Comment by tspmelo** [comment]
jenkins retest this please

**Comment by cbodley** [comment]
rebased

**Pull request merged**
