### PR TITLE
luminous: bucket resharding fixes

### PR DESCRIPTION
**Pull request by theanalyst**
Fixes for the following tracker issues:
http://tracker.ceph.com/issues/36688
http://tracker.ceph.com/issues/37446
https://tracker.ceph.com/issues/37555

The first one adds renewable locks as the backport already staged in
https://github.com/ceph/ceph/pull/24898; the second one is the admin fixes built
atop of this so amalgamating as one pr to reduce merge conflicts

### CODE REVIEW

**Comment by theanalyst** [comment]
@ivancich I've added the reshard cleanup pr as well to this one to avoid merge conflicts and testing these as a batch while dealing wit h the 3 reshard patches. The merge conflicts were only due to rgw rados refactor moving a few functions around.

**Comment by ivancich** [comment]
@theanalyst, @smithfarm Thank you Abhishek. A bunch of PRs did focus on the same areas of code, so I imagine this is very helpful and will speed the backport.

**Comment by yuriw** [comment]
[wip-yuri3-testing-2018-12-10-1632-luminous](https://trello.com/c/3zsD2Wxj/485-wip-yuri3-testing-2018-12-10-1632-luminous)

**Comment by cbodley** [comment]
@ivancich this passed qa, could you please review?

**Pull request merged**
