### PR TITLE
src/msg/async/net_handler.cc: Fix compilation

### PR DESCRIPTION
**Pull request by carletes**
On a Cray system I'm working on, it seems that `SO_PRIORITY` is defined, but `IPTOS_CLASS_CS6` is not. Without this patch, compilation fails at line 150:

```
r = ::setsockopt(sd, SOL_SOCKET, SO_PRIORITY, &prio, sizeof(prio));
```

beacuse the variable `r` is not defined (originally it is defined inside the `#ifdef IPTOS_CLASS_CS6` block).

Fixes: https://tracker.ceph.com/issues/42821

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by tchaikov** [comment]
@carletes Carlos, could you add a "`Signed-off-by`" line at the end of your commit message? "git commit -s" will do the trick for you. see https://github.com/ceph/ceph/blob/master/SubmittingPatches.rst#1-sign-your-work

**Comment by carletes** [comment]
Thanks for your prompt reply, @tchaikov! I've just signed it off, and tidied up the description (since it was such a simple change, I did it originally with the GitHub UI, and did not find the chance to do it properly online).

Any chance of having this backported to the current stable branch, by the way?

**Comment by tchaikov** [comment]
> Any chance of having this backported to the current stable branch, by the way?

yup. you could

1. file a tracker ticket on https://tracker.ceph.com, and 
1. mark the ticket with "Backport: <stable-branch>[,<stable-branch>...]". 
1. then connect this fix with it by adding a "Fixes: <url-to-ticket>" line right before your "Signed-off-by" line. 
1. update the tracker ticket.

 see 4e8d745c594db18b4119ddf83047014917f437da for an example. lemme know if i could help.

**Comment by carletes** [comment]
Done! Thanks again for your help on this, @tchaikov

**Comment by tchaikov** [comment]
https://shaman.ceph.com/builds/ceph/wip-kefu-testing-2019-11-17-0135/70968846f95926b5f8ae4f251788ce3818969018/

**Comment by carletes** [comment]
Thanks for your help with this, @tchaikov!

**Pull request merged**
