### PR TITLE
build: minor build script cleanups

### PR DESCRIPTION
**Pull request by phlogistonjohn**
This work is a few small clean ups of some of the build scripts - this is preparatory work that leads up to running more of the build and tests in (OCI/docker) containers.

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [x] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Review by epuertat — APPROVED** [review]
LGTM!

**Review by tchaikov — APPROVED** [review]

**Comment by tchaikov** [comment]
jenkins test make check

**Comment by phlogistonjohn** [comment]
jenkins test make check

**Comment by phlogistonjohn** [comment]
jenkins test make check

**Comment by phlogistonjohn** [comment]
After a few unlucky breaks 'make check' is passing.

**Comment by adk3798** [comment]
jenkins test api

**Comment by adk3798** [comment]
jenkins test api

**Comment by adk3798** [comment]
builds succeeded (https://shaman.ceph.com/builds/ceph/wip-adk2-testing-2022-10-14-1027/45575eee1e4eb905e9a32c9aa1d5f6f2b03f2ef9/) except the centos 8 arm bulld, but that also fails on main currently (https://shaman.ceph.com/builds/ceph/main/3313f1c8944c210bab87f3544b312cf20629cded/) so not relevant to this PR

**Comment by adk3798** [comment]
jenkins test api

**Comment by tchaikov** [comment]
jenkins test api

**Comment by phlogistonjohn** [comment]
jenkins test api

**Comment by phlogistonjohn** [comment]
I don't see any reason why these changes should impact the ceph api tests, but they have failed consistently. I'm rebasing to see if I was unlucky with the state of the tree when I first made my patches. This is a bit of a shot in the dark, though.

**Comment by phlogistonjohn** [comment]
'make check' and 'ceph API tests' are now both passing!

**Pull request merged**
