### PR TITLE
nautilus: dashboard: orchestrator mgr modules assert failure on iscsi service request

### PR DESCRIPTION
**Pull request by sebastian-philipp**
http://tracker.ceph.com/issues/40037

### CODE REVIEW

**Comment by yuriw** [comment]
[wip-yuri3-testing-2019-06-14-1440-nautilus](https://trello.com/c/217ldlvH/642-wip-yuri3-testing-2019-06-14-1440-nautilus)

**Comment by smithfarm** [comment]
jenkins test docs

**Comment by smithfarm** [comment]
once again we got "nautilus-batch-1" added before the PR passed mandatory checks... :-( :-( :-(

**Comment by yuriw** [comment]
[wip-yuri3-testing-2019-06-17-1508-nautilus](https://trello.com/c/1nC2eLGN/645-wip-yuri3-testing-2019-06-17-1508-nautilus)

**Comment by smithfarm** [comment]
@sebastian-philipp The process for adding "nautilus-batch-1" is simple:

1. ensure that all mandatory Jenkins checks are green (issue "retest this please", etc. comments as needed)
2. add "nautilus-batch-1" label
3. do not add the label before completing step 1

That's really all there is to it.

**Comment by sebastian-philipp** [comment]
jenkins test make check

**Comment by yuriw** [comment]
@sebastian-philipp @ricardoasmarques this passed tests, pls approve and merge, or I will, thx

**Pull request merged**
