### PR TITLE
nautilus: rgw: ordered bucket listing code clean-up

### PR DESCRIPTION
**Pull request by ivancich**
rgw: ordered bucket listing code clean-up

As a result of an earlier bug-fix, the code for ordered bucket listing is now more complex than it needs to be. This reverts that fix and applies a cleaner one.

This change is not applicable to octopus or later because the ordered bucket listing code underwent a significant change in between. Specifically much of the delimiter filtering logic was moved to cls/osd code.

Fixes: https://tracker.ceph.com/issues/47487

Signed-off-by: J. Eric Ivancich <ivancich@redhat.com>

### CODE REVIEW

**Review by cbodley — APPROVED** [review]

**Comment by cbodley** [comment]
jenkins test make check

**Comment by smithfarm** [comment]
@ivancich It would be nice if the commit message could include some (even very brief) verbiage explaining why the fix is applicable only to nautilus and cannot be backported from master or octopus.

**Comment by ivancich** [comment]
@smithfarm I just want to make certain you want that documentation in the two commit messages. Normally I don't reference specific releases in commit messages. I will update the PR message.

**Comment by smithfarm** [comment]
> @smithfarm I just want to make certain you want that documentation in the two commit messages. Normally I don't reference specific releases in commit messages. I will update the PR message.

The PR message is for now, but the commit messages are for posterity. So, yes, I do mean to put the explanation in the commit message itself. According to https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst#cherry-picking-rules one of the cherry-picking rules is:

"if a commit could not be cherry-picked from master, the **commit message** must explain why that was not possible."

(emphasis added)

So, you would not necessarily have to mention a specific branch (other than "master"). My recommended formulation is "This commit cannot be cherry-picked from master because . . ."

This case is discussed further in https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst#notes-on-the-cherry-picking-rules if you're interested.

**Comment by yuriw** [comment]
[wip-yuri3-testing-2020-09-18-1321-nautilus](https://trello.com/c/zv4Nz8SW/1015-wip-yuri3-testing-2020-09-18-1321-nautilus)

**Pull request merged**
