### PR TITLE
changes to address FTBFS on fc30

### PR DESCRIPTION
**Pull request by tchaikov**
in C++17, the base class subobject itself is an element of the
aggregation. by calling `get_size_visitor<T>{}`, we are using
aggregation-initialization of the derived class of
`boost::static_visitor` which defines its ctor and dtor as protected
member methods. and for aggregation-initialization, the base class
subobjects are treated exactly the same as member variables. so, we are
calling the protected member methods of `boost::static_visitor` via
`get_size_visitor<T>{}`. one way to do this, is to explicitly define the
ctor of `get_size_visitor`. or avoid using aggregation-initialization.

as list initialization is encouraged under most circumstances, for
instance,

- it does not allow narrowing.
- it is not ambiguous in the sense that it cannot be parsed as a
function declaration.

so, in this change, an empty constructor is added.

Signed-off-by: Kefu Chai <kchai@redhat.com>

- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by tchaikov** [comment]
this change should address the FTBFS with GCC-9 or Clang trunk. for a minimal reproducer, see https://godbolt.org/z/PTqaJA

**Comment by kalebskeithley** [comment]
This fixes that error. (Now there are others.)

**Comment by tchaikov** [comment]
@kalebskeithley thanks for testing the change. i am hunting them down.

**Comment by tchaikov** [comment]
@kalebskeithley could you give it another try?

**Comment by kalebskeithley** [comment]
I only took the common/config and the dmclock_server.h changes. With those it builds in koji for Fedora/Rawhide — x86_64 at least (scratch build). Hopefully the other arches don't bite me.
Thanks for the quick fixes.

**Comment by tchaikov** [comment]
https://shaman.ceph.com/builds/ceph/wip-26301/9d24e3d82bc3e8ced3e3f59123a07473b100cd0a/

**Pull request merged**
