### PR TITLE
qa/tasks: jewel backport -  ceph-deploy use of dev option

### PR DESCRIPTION
**Pull request by vasukulkarni**
Fixes http://tracker.ceph.com/issues/18736 for jewel

### CODE REVIEW

**Comment by yuriw** [comment]
@vasukulkarni did they pass?

**Comment by vasukulkarni** [comment]
will paste the link here in a min

**Comment by vasukulkarni** [comment]
http://pulpito.ceph.com/vasu-2017-01-25_17:18:25-ceph-deploy-jewel---basic-vps/

**Comment by vasukulkarni** [comment]
http://pulpito.ceph.com/vasu-2017-01-26_21:22:46-ceph-deploy-jewel---basic-vps/

**Comment by vasukulkarni** [comment]
we  need d7e1b949a4a6a51bb28505f5c5e5b97a23faab2b for hammer as well

**Comment by smithfarm** [comment]
Thanks, will be included in next integration round, for which we'll schedule a ceph-deploy run.

**Comment by smithfarm** [comment]
@vasukulkarni Could you squash the commits together and add `Fixes: http://tracker.ceph.com/issues/18736`

**Comment by smithfarm** [comment]
@vasukulkarni If you could prepare a hammer version of the PR, too, that would be great.

**Comment by smithfarm** [comment]
If the second commit is unrelated to the failure in 18736, it could be moved into a separate PR?

**Comment by vasukulkarni** [comment]
@smithfarm for the jewel both commits are required, for hammer we need only one, I will get the pr out for hammer

**Comment by smithfarm** [comment]
@vasukulkarni Thanks. Please think about how you could add a `Fixes` line somehow.

**Comment by smithfarm** [comment]
@vasukulkarni http://tracker.ceph.com/issues/18737 is the hammer backport tracker issue.

**Comment by vasukulkarni** [comment]
@smithfarm @yuriw I pushed the Fixes in first commit where it makes sense, For the hammer run, i recall that package split caused issues before and I see the same now as well and we recommended folks to use older version of ceph-deploy for hammer.

**Comment by smithfarm** [comment]
Ah yes, now I remember.

**Comment by smithfarm** [comment]
@vasukulkarni Looks good, thanks.

Regarding hammer, it looks like the `ceph-deploy` task supports branch, but not tag. If you made a branch for the old ceph-deploy version, you could modify `qa/suites/ceph-deploy/ceph-deploy/basic/tasks/ceph-deploy_hello_world.yaml` to use that branch and then the suite might pass?

**Pull request merged**
