### PR TITLE
mgr/dashboard: get rgw daemon zonegroup name from mgr

### PR DESCRIPTION
**Pull request by alfonsomthd**
Fixes: https://tracker.ceph.com/issues/47676
Signed-off-by: Alfonso Martínez <almartin@redhat.com>

Related to: https://github.com/rook/rook/issues/6210

## Checklist
- [x] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by alfonsomthd** [comment]
jenkins test api

**Comment by alfonsomthd** [comment]
jenkins test api

**Review by epuertat — APPROVED** [review]

**Review by avanthakkar — APPROVED** [review]
Nice improvement. Also, reduced a lot of code which was used just to get the zonegroup_name!

**Comment by alfonsomthd** [comment]
jenkins test signed

**Comment by alfonsomthd** [comment]
@LenzGr Rebased.

**Comment by callithea** [comment]
jenkins test signed

**Comment by callithea** [comment]
jenkins test signed

**Comment by callithea** [comment]
jenkins test signed

**Comment by tchaikov** [comment]
jenkins test signed

**Comment by tchaikov** [comment]
jenkins test signed

**Comment by tchaikov** [comment]
jenkins test signed

**Comment by callithea** [comment]
- [New pkg build](https://shaman.ceph.com/builds/ceph/wip-laura-testing-36449-37064-37375-37449/)
- [QA run](https://pulpito.ceph.com/laura-2020-10-08_09:25:00-rados:dashboard-wip-laura-testing-36449-37064-37375-37449-distro-basic-smithi/)

**Review by callithea — APPROVED** [review]

**Pull request merged**
