### PR TITLE
rgw: don't write bucket_header when it is not changed in bucket_link/unlink

### PR DESCRIPTION
**Pull request by shashalu**
Signed-off-by: Shasha Lu <lu.shasha@eisoo.com>

### CODE REVIEW

**Comment by ZVampirEM77** [comment]
@shashalu Have you passed the compiling in your local env? I can not find the definition of "header" in 

`if (op.log_op && !header.syncstopped) {`

and I compile it in my local env,  the result is
`/home/enming/new_ceph/ceph/src/cls/rgw/cls_rgw.cc: In function ‘int rgw_bucket_link_olh(cls_method_context_t, ceph::bufferlist*, ceph::bufferlist*)’:
/home/enming/new_ceph/ceph/src/cls/rgw/cls_rgw.cc:1518:21: error: ‘header’ was not declared in this scope
   if (op.log_op && !header.syncstopped) {
                     ^
/home/enming/new_ceph/ceph/src/cls/rgw/cls_rgw.cc:1519:34: error: redeclaration of ‘rgw_bucket_dir_header header’
     struct rgw_bucket_dir_header header;
                                  ^
/home/enming/new_ceph/ceph/src/cls/rgw/cls_rgw.cc:1518:21: error: ‘<typeprefixerror>header’ previously declared here
   if (op.log_op && !header.syncstopped) {
                     ^
/home/enming/new_ceph/ceph/src/cls/rgw/cls_rgw.cc: In function ‘int rgw_bucket_unlink_instance(cls_method_context_t, ceph::bufferlist*, ceph::bufferlist*)’:
/home/enming/new_ceph/ceph/src/cls/rgw/cls_rgw.cc:1676:21: error: ‘header’ was not declared in this scope
   if (op.log_op && !header.syncstopped) {
                     ^
/home/enming/new_ceph/ceph/src/cls/rgw/cls_rgw.cc:1677:34: error: redeclaration of ‘rgw_bucket_dir_header header’
     struct rgw_bucket_dir_header header;
                                  ^
/home/enming/new_ceph/ceph/src/cls/rgw/cls_rgw.cc:1676:21: error: ‘<typeprefixerror>header’ previously declared here
   if (op.log_op && !header.syncstopped) {
                     ^
make[3]: *** [src/cls/CMakeFiles/cls_rgw.dir/rgw/cls_rgw.cc.o] Error 1
make[3]: *** Waiting for unfinished jobs....`

**Comment by ZVampirEM77** [comment]
My local branch is the newest master branch
`git log

commit b133a6d95a08a4fc89508f439adf4518da16cb33
Author: lu.shasha <lu.shasha@eisoo.com>
Date:   Wed Aug 30 11:41:12 2017 +0800

    rgw: don't read/write bucket_header when bucket_header is not changed in bucket_link/unlink

    Signed-off-by: Shasha Lu <lu.shasha@eisoo.com>

commit 5923e77917cbc14ae90a0f2f6a7064f2aca25892
Merge: fb795f5 fee7666
Author: Haomai Wang <haomaiwang@gmail.com>
Date:   Wed Aug 30 22:19:12 2017 -0700

    Merge pull request #17145 from optimistyzy/822_bl

    os/bluestore/NVMEDevice: change write_bl to bl

    Reviewed-by: Haomai Wang <haomai@xsky.com>

commit fee7666efcb3e25fcfcb09ba39a1115970a41ebd
Author: Ziye Yang <optimistyzy@gmail.com>
Date:   Tue Aug 22 20:56:30 2017 +0800

    NVMEDevice: change write_bl to bl

    With this patch, both read and write can use this field in
    task.

    Signed-off-by: Ziye Yang <optimistyzy@gmail.com>
    Signed-off-by: Pan Liu <wanjun.lp@alibaba-inc.com>

commit fb795f556a4259b2f1d944121b532109d4d8cc47
Merge: dab3522 b5c2782
Author: Sage Weil <sage@newdream.net>
Date:   Wed Aug 30 21:53:36 2017 -0500

    Merge pull request #17382 from liewegas/wip-integration

    src/script/build-integration-branch

    Reviewed-by: Kefu Chai <kchai@redhat.com>

commit b5c27826158f699960fcf887e901545c359ad68c
...`

**Comment by shashalu** [comment]
@ZVampirEM77  sorry, I have made a mistake. Already revised.

**Comment by ZVampirEM77** [comment]
LGTM

**Comment by shashalu** [comment]
@cbodley Please take a look, thx

**Pull request merged**
