### PR TITLE
nautilus: mgr/dashboard: Handle always-on Ceph Manager modules correctly

### PR DESCRIPTION
**Pull request by alfonsomthd**
backport tracker: https://tracker.ceph.com/issues/42809

---

backport of https://github.com/ceph/ceph/pull/30142
parent tracker: https://tracker.ceph.com/issues/41648

this backport was staged using ceph-backport.sh version 15.0.0.6950
find the latest version at https://github.com/ceph/ceph/blob/master/src/script/ceph-backport.sh

Also cherry-picked (as they are to be merged together):

mgr/dashboard: test_mgr_module QA test has not been adapted to latest controller changes

 Fixes: https://tracker.ceph.com/issues/41993

Signed-off-by: Volker Theile <vtheile@suse.com>
cherry picked from commit 59a7bb209d0283493040665518082cc2fc80ee55)

### CODE REVIEW

**Comment by callithea** [comment]
jenkins test dashboard backend

**Comment by callithea** [comment]
The dashboard backend API tests failed with:
```2019-11-21 15:28:15,349.349 INFO:tasks.mgr.mgr_test_case:Found dashboard at https://ceph-builders:7789/ (daemon y/4717)
2019-11-21 15:28:15,352.352 INFO:tasks.mgr.test_dashboard:Originally running manager 'y' at https://ceph-builders:7789/
2019-11-21 15:28:15,352.352 INFO:__main__:Running ['./bin/ceph', 'mgr', 'fail', u'y']
2019-11-21 15:28:16,699.699 INFO:__main__:Running ['./bin/ceph', 'status', '--format=json-pretty']
2019-11-21 15:28:17,896.896 INFO:__main__:Running ['./bin/ceph', 'status', '--format=json-pretty']
2019-11-21 15:28:19,117.117 INFO:__main__:Running ['./bin/ceph', 'status', '--format=json-pretty']
2019-11-21 15:28:20,145.145 INFO:tasks.mgr.mgr_test_case:Found dashboard at https://ceph-builders:7790/ (daemon x/4723)
2019-11-21 15:28:20,147.147 INFO:tasks.mgr.test_dashboard:After failover running manager 'x' at https://ceph-builders:7790/
2019-11-21 15:28:20,159.159 INFO:__main__:test_standby_disable_redirect (tasks.mgr.test_dashboard.TestDashboard) ... ERROR
2019-11-21 15:28:20,159.159 INFO:__main__:Running ['./bin/ceph', 'config', 'set', 'mgr', 'mgr/dashboard/standby_behaviour', 'redirect']
2019-11-21 15:28:21,222.222 INFO:__main__:Running ['./bin/ceph', 'config', 'set', 'mgr', 'mgr/dashboard/standby_error_status_code', '500']
2019-11-21 15:28:22,051.051 INFO:__main__:Stopped test: test_standby_disable_redirect (tasks.mgr.test_dashboard.TestDashboard) in 26.194175s
2019-11-21 15:28:22,053.053 INFO:__main__:
2019-11-21 15:28:22,053.053 INFO:__main__:======================================================================
2019-11-21 15:28:22,053.053 INFO:__main__:ERROR: test_standby_disable_redirect (tasks.mgr.test_dashboard.TestDashboard)
2019-11-21 15:28:22,054.054 INFO:__main__:----------------------------------------------------------------------
2019-11-21 15:28:22,054.054 INFO:__main__:Traceback (most recent call last):
2019-11-21 15:28:22,054.054 INFO:__main__:  File "/home/jenkins-build/build/workspace/ceph-dashboard-pr-backend/qa/tasks/mgr/test_dashboard.py", line 82, in test_standby_disable_redirect
2019-11-21 15:28:22,054.054 INFO:__main__:    r = requests.get(original_uri, allow_redirects=False, verify=False)
2019-11-21 15:28:22,054.054 INFO:__main__:  File "/tmp/tmp.bsmgyPzb8E/venv/lib/python2.7/site-packages/requests/api.py", line 75, in get
2019-11-21 15:28:22,055.055 INFO:__main__:    return request('get', url, params=params, **kwargs)
2019-11-21 15:28:22,055.055 INFO:__main__:  File "/tmp/tmp.bsmgyPzb8E/venv/lib/python2.7/site-packages/requests/api.py", line 60, in request
2019-11-21 15:28:22,055.055 INFO:__main__:    return session.request(method=method, url=url, **kwargs)
2019-11-21 15:28:22,055.055 INFO:__main__:  File "/tmp/tmp.bsmgyPzb8E/venv/lib/python2.7/site-packages/requests/sessions.py", line 524, in request
2019-11-21 15:28:22,055.055 INFO:__main__:    resp = self.send(prep, **send_kwargs)
2019-11-21 15:28:22,056.056 INFO:__main__:  File "/tmp/tmp.bsmgyPzb8E/venv/lib/python2.7/site-packages/requests/sessions.py", line 637, in send
2019-11-21 15:28:22,056.056 INFO:__main__:    r = adapter.send(request, **kwargs)
2019-11-21 15:28:22,056.056 INFO:__main__:  File "/tmp/tmp.bsmgyPzb8E/venv/lib/python2.7/site-packages/requests/adapters.py", line 516, in send
2019-11-21 15:28:22,056.056 INFO:__main__:    raise ConnectionError(e, request=request)
2019-11-21 15:28:22,056.056 INFO:__main__:ConnectionError: HTTPSConnectionPool(host='ceph-builders', port=7789): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fba5afe1d10>: Failed to establish a new connection: [Errno 111] Connection refused',))
2019-11-21 15:28:22,057.057 INFO:__main__:
2019-11-21 15:28:22,057.057 INFO:__main__:----------------------------------------------------------------------
2019-11-21 15:28:22,057.057 INFO:__main__:Ran 2 tests in 88.907s
2019-11-21 15:28:22,058.058 INFO:__main__:
2019-11-21 15:28:22,058.058 INFO:__main__:FAILED (errors=1)
2019-11-21 15:28:22,058.058 INFO:__main__:
2019-11-21 15:28:22,058.058 INFO:__main__:======================================================================
2019-11-21 15:28:22,059.059 INFO:__main__:ERROR: test_standby_disable_redirect (tasks.mgr.test_dashboard.TestDashboard)
2019-11-21 15:28:22,059.059 INFO:__main__:----------------------------------------------------------------------
2019-11-21 15:28:22,059.059 INFO:__main__:Traceback (most recent call last):
2019-11-21 15:28:22,059.059 INFO:__main__:  File "/home/jenkins-build/build/workspace/ceph-dashboard-pr-backend/qa/tasks/mgr/test_dashboard.py", line 82, in test_standby_disable_redirect
2019-11-21 15:28:22,060.060 INFO:__main__:    r = requests.get(original_uri, allow_redirects=False, verify=False)
2019-11-21 15:28:22,060.060 INFO:__main__:  File "/tmp/tmp.bsmgyPzb8E/venv/lib/python2.7/site-packages/requests/api.py", line 75, in get
2019-11-21 15:28:22,060.060 INFO:__main__:    return request('get', url, params=params, **kwargs)
2019-11-21 15:28:22,060.060 INFO:__main__:  File "/tmp/tmp.bsmgyPzb8E/venv/lib/python2.7/site-packages/requests/api.py", line 60, in request
2019-11-21 15:28:22,060.060 INFO:__main__:    return session.request(method=method, url=url, **kwargs)
2019-11-21 15:28:22,061.061 INFO:__main__:  File "/tmp/tmp.bsmgyPzb8E/venv/lib/python2.7/site-packages/requests/sessions.py", line 524, in request
2019-11-21 15:28:22,061.061 INFO:__main__:    resp = self.send(prep, **send_kwargs)
2019-11-21 15:28:22,061.061 INFO:__main__:  File "/tmp/tmp.bsmgyPzb8E/venv/lib/python2.7/site-packages/requests/sessions.py", line 637, in send
2019-11-21 15:28:22,061.061 INFO:__main__:    r = adapter.send(request, **kwargs)
2019-11-21 15:28:22,062.062 INFO:__main__:  File "/tmp/tmp.bsmgyPzb8E/venv/lib/python2.7/site-packages/requests/adapters.py", line 516, in send
2019-11-21 15:28:22,063.063 INFO:__main__:    raise ConnectionError(e, request=request)
2019-11-21 15:28:22,063.063 INFO:__main__:ConnectionError: HTTPSConnectionPool(host='ceph-builders', port=7789): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fba5afe1d10>: Failed to establish a new connection: [Errno 111] Connection refused',))```

**Comment by alfonsomthd** [comment]
jenkins test dashboard backend

**Comment by alfonsomthd** [comment]
jenkins test dashboard backend

**Comment by callithea** [comment]
- QA run [WIP]: http://pulpito.ceph.com/laura-2019-12-04_13:59:42-rados:dashboard-wip-laura-testing-dashboard-nautilus-batch-5-distro-basic-smithi/

**Comment by yuriw** [comment]
[wip-yuri8-testing-2020-01-13-2057-nautilus](https://trello.com/c/ZAl5Zb8O/804-wip-yuri8-testing-2020-01-13-2057-nautilus)

**Comment by yuriw** [comment]
retest this please

**Comment by tchaikov** [comment]
jenkins test make check

**Comment by callithea** [comment]
jenkins test make check

**Pull request merged**
