### PR TITLE
rgw: raise log level of eacces for reshard list

### PR DESCRIPTION
**Pull request by kmroz**
Fixes http://tracker.ceph.com/issues/20289

Signed-off-by: Karol Mroz <kmroz@suse.de>

### CODE REVIEW

**Comment by kmroz** [comment]
@oritwas - Could you take a look please?  The idea is to make access issues (per the ticket) not flood the rgw log.

**Comment by smithfarm** [comment]
Jenkins re-test this please

**Comment by cbodley** [comment]
do we really want to hide these errors from the user? how would they know to fix their pool permissions otherwise?

**Comment by oritwas** [comment]
@kmroz , I agree with @cbodley

**Comment by kmroz** [comment]
@oritwas / @cbodley - We were thinking in a slightly different direction with the severity of the log message, but you're right, having the user fix the permission error would be the right solution.  Thanks for the review.

**Comment by cbodley** [comment]
@kmroz what do you think about leaving log level at 0, but providing a more concise error message for `EACCESS`? something like:

> ERROR: user client.rgw.0 denied access to pool default.rgw.log:reshard. you can view these permissions with 'ceph auth get client.rgw.0', and modify them with 'ceph auth cap' (see 'User Management' in the rados documentation)

**Comment by kmroz** [comment]
@cbodley - Yes, I'm sure we'd make an admin or two happy with that one.  I am afk for a few days (vacation).  @theanalyst gets into the office sooner, so I will see about dumping, err, sharing this with him ;)

Thanks.

**Pull request closed without merging**
