### PR TITLE
qa/clusters/fixed-[23]: 4 osds per node, not 3

### PR DESCRIPTION
**Pull request by liewegas**
Smithi have 4 nvme partitions available for use.

Signed-off-by: Sage Weil <sage@redhat.com>

### CODE REVIEW

**Comment by vasukulkarni** [comment]
@liewegas this will fail on mira nodes and i think vps also has 3 drives, but have to check.

**Comment by vasukulkarni** [comment]
Actually mira nodes have till sdh, probably the vps is also configurable

**Comment by liewegas** [comment]
Do you mind tracking that down?  I think going from 3->4 will improve the quality of the tseting

**Comment by vasukulkarni** [comment]
@liewegas sure i will update here.

**Comment by vasukulkarni** [comment]
vps current default is 3, but should be increased from 3 to 4 here, https://github.com/ceph/teuthology/blob/master/teuthology/provision/downburst.py#L172 , probably reduce the disks-size which is currently 200gb or it could still work with mira's. @djgalloway ?

**Comment by vasukulkarni** [comment]
trying on vps with 4 osd's wip-branch: http://pulpito.ceph.com/vasu-2017-08-03_21:35:41-rados:basic-master-distro-basic-vps/ 

and mira: http://pulpito.ceph.com/vasu-2017-08-03_21:36:44-rados:basic-master-distro-basic-mira/

**Comment by vasukulkarni** [comment]
Looks good,  need this for vps: https://github.com/ceph/teuthology/pull/1099

**Pull request merged**
