### PR TITLE
jewel: Jewel: segfault in ObjectCacher::FlusherThread

### PR DESCRIPTION
**Pull request by dachary**
http://tracker.ceph.com/issues/17131

### CODE REVIEW

**Comment by singler** [comment]
hey,

I noticed that this is still not merged to jewel. Is there a reason for that?

**Comment by dachary** [comment]
It's being tested and it takes time, no other reason ;-)

**Comment by dachary** [comment]
@gregsfortytwo does this backport look good to merge ? It passed the rados (http://tracker.ceph.com/issues/17487#note-12), upgrade/jewel-x and upgrade/hammer-x (http://tracker.ceph.com/issues/17487#note-15) suites (except for two bugs that are, I believe, unrelated)

**Comment by gregsfortytwo** [comment]
Looks good @dachary.

**Pull request merged**
