### PR TITLE
jewel: ceph-disk flake8 test fails on very old, and very new, versions of flake8

### PR DESCRIPTION
**Pull request by shinobu-x**
http://tracker.ceph.com/issues/22236

### CODE REVIEW

**Comment by shinobu-x** [comment]
test this please

**Comment by shinobu-x** [comment]
test this please

**Comment by shinobu-x** [comment]
test this please

**Comment by shinobu-x** [comment]
test this please

**Comment by smithfarm** [comment]
I seem to have clobbered this with https://github.com/ceph/ceph/pull/19153 - very sorry!!

**Pull request closed without merging**
