### PR TITLE
nautilus: mon: Warn when too many reads are repaired on an OSD

### PR DESCRIPTION
**Pull request by dzafman**
https://tracker.ceph.com/issues/46096

---

My version of #35686 with alternative to mute functionality not present in Naultius.

## Checklist
- [x] References tracker ticket
- [x] Updates documentation if necessary
- [x] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by dzafman** [comment]
@neha-ojha Should we document the clear_shards_repaired tell command or just add something to the release notes.

**Comment by neha-ojha** [comment]
> @neha-ojha Should we document the clear_shards_repaired tell command or just add something to the release notes.

@dzafman Let's do both, it is important to make this visible to users.

**Comment by dzafman** [comment]
@neha-ojha I added Doc and PendingReleaseNotes changes

**Comment by dzafman** [comment]
@neha-ojha I adjust the doc to use re-enable.  Also, because the warning test is > mon_osd_warn_num_repaired I fix the docs to say to use the tell command to set the value to equal to mon_osd_warn_num_repaired.  In addition, I added a notice that this command will be replaced in future release my health mute/unmute.

**Comment by dzafman** [comment]
@neha-ojha What are the Ceph API tests?   I can't retest just that test.

**Pull request merged**
