### PR TITLE
common,test,cmake: various changes to re-enable build on osx

### PR DESCRIPTION
**Pull request by tchaikov**

### CODE REVIEW

**Comment by wjwithagen** [comment]
@tchaikov 
Can't really test ATM since there is an older Clang problem I have not yet been able to fix....
But from observation it looks oke.

**Comment by wjwithagen** [comment]
@tchaikov 
I've got a normal build env again, so I'll run this thru FreeBSD-jenkins

**Comment by tchaikov** [comment]
@wjwithagen thanks for testing!

**Comment by tchaikov** [comment]
- http://pulpito.ceph.com/kchai-2017-11-13_07:26:34-rados-wip-kefu-testing-2017-11-13-1300-distro-basic-mira/
- http://pulpito.ceph.com/kchai-2017-11-14_05:25:42-rados-wip-kefu-testing-2017-11-14-1048-distro-basic-mira/

**Pull request merged**
