### PR TITLE
mgr/volumes: drop unused variable vol_name

### PR DESCRIPTION
**Pull request by jschmid1**
Signed-off-by: Joshua Schmid <jschmid@suse.de>

### CODE REVIEW

**Comment by joscollin** [comment]
@jschmid1 Can you make this change, so that I could include this in my QA run?

**Comment by jschmid1** [comment]
> @jschmid1 Can you make this change, so that I could include this in my QA run?

will do

**Comment by joscollin** [comment]
http://pulpito.front.sepia.ceph.com/jcollin-2019-11-21_22:40:05-fs-mds_removal_ssh_unused_var_static_typing_testing-distro-basic-smithi/

**Comment by joscollin** [comment]
Tests passed:
http://pulpito.front.sepia.ceph.com/jcollin-2019-11-22_05:40:26-fs-mds_removal_ssh_unused_var_testing-distro-basic-smithi/

**Comment by joscollin** [comment]
```
2019-11-22T06:28:18.577 INFO:tasks.cephfs_test_runner:test_subvolume_group_ls (tasks.cephfs.test_volumes.TestVolumes) ... ok

2019-11-22T06:29:12.103 INFO:tasks.cephfs_test_runner:test_subvolume_group_ls_for_nonexistent_volume (tasks.cephfs.test_volumes.TestVolumes) ... ok
```

**Pull request merged**
