### PR TITLE
qa: drop XMLSTARLET variable, use xmlstarlet directly

### PR DESCRIPTION
**Pull request by idryomov**
The variable was added in commit 9b6b7c35d03f ("Handle differently-named xmlstarlet binary for *suse") but this compatibility business is long outdated:

  Mon Oct 13 08:52:37 UTC 2014 - toms@opensuse.org

  - SPEC file changes
    - Added link from /usr/bin/xml to /usr/bin/xmlstarlet as other distributions do the same
    - Did the same for the manpage

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [x] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Comment by idryomov** [comment]
Affected RBD workunits:

https://pulpito.ceph.com/dis-2024-08-25_11:30:18-rbd-wip-dis-testing-distro-default-smithi/
https://pulpito.ceph.com/dis-2024-08-25_11:31:18-rbd-wip-dis-testing-distro-default-smithi/
https://pulpito.ceph.com/dis-2024-08-25_11:35:42-rbd-wip-dis-testing-distro-default-smithi/
https://pulpito.ceph.com/dis-2024-08-25_11:36:50-rbd-wip-dis-testing-distro-default-smithi/
https://pulpito.ceph.com/dis-2024-08-25_11:37:57-rbd-wip-dis-testing-distro-default-smithi/
https://pulpito.ceph.com/dis-2024-08-25_11:40:55-rbd-wip-dis-testing-distro-default-smithi/

**Review by ajarr — APPROVED** [review]
Quite a few RBD workunit files sourced `ceph-helpers.sh` for only the `XMLSTARLET` variable?

**Comment by ajarr** [comment]
> Affected RBD workunits:
> 
> https://pulpito.ceph.com/dis-2024-08-25_11:30:18-rbd-wip-dis-testing-distro-default-smithi/ https://pulpito.ceph.com/dis-2024-08-25_11:31:18-rbd-wip-dis-testing-distro-default-smithi/ https://pulpito.ceph.com/dis-2024-08-25_11:35:42-rbd-wip-dis-testing-distro-default-smithi/ https://pulpito.ceph.com/dis-2024-08-25_11:36:50-rbd-wip-dis-testing-distro-default-smithi/ https://pulpito.ceph.com/dis-2024-08-25_11:37:57-rbd-wip-dis-testing-distro-default-smithi/ https://pulpito.ceph.com/dis-2024-08-25_11:40:55-rbd-wip-dis-testing-distro-default-smithi/

rbd-ggate.sh is tested by the `make-check` job?

I couldn't find the core workunit that runs  `crush-classes.sh`.

**Comment by idryomov** [comment]
> rbd-ggate.sh is tested by the `make-check` job?

No.  It's a FreeBSD-specific thing and it's not covered by CI.

> 
> I couldn't find the core workunit that runs `crush-classes.sh`.

I didn't run `crush-classes.sh` either, but note that `ceph-helpers.sh` is still imported there, so the risk of something breaking should be near zero.

**Pull request merged**
