### PR TITLE
octopus: osd: optimize PG removal (part1)

### PR DESCRIPTION
**Pull request by ifed01**
This is the first set of patches intended to improve user experience while doing pool/PG removal.
Includes previous position reuse for collection listing, trimming removed object from bluestore cache (which speeds-up final collection reaping) plus some means to gather statistics on the removal process.

Fixes: https://tracker.ceph.com/issues/48480

Signed-off-by: Igor Fedotov ifedotov@suse.com

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Review by neha-ojha — APPROVED** [review]

**Review by tchaikov — APPROVED** [review]

**Review by aclamk — APPROVED** [review]

**Comment by gravitystorm** [comment]
What are the next steps to get this merged? Is there anything we can do to help?

**Comment by tchaikov** [comment]
@gravitystorm the next step is to run it against the rados qa suite. we do this in batch in general. I just added the octopus-batch-1 label in hope that some of us can pick it up in the next batch.

**Comment by yuriw** [comment]
[wip-yuri2-testing-2021-01-04-0837-octopus](https://trello.com/c/Fk0Aj3z8/1096-wip-yuri2-testing-2021-01-04-0837-octopus)

**Comment by ideepika** [comment]
hey @ifed01 @gravitystorm observed test failure: https://tracker.ceph.com/issues/48764 can you verify if it's related to this change or not

**Pull request merged**
