### PR TITLE
pybind/mgr/mirroring: drop mon_host from peer_list

### PR DESCRIPTION
**Pull request by joscollin**
Drop mon_host from peer_list to make it similar to rbd_mirror peer_list.

Fixes: https://tracker.ceph.com/issues/63614

### CODE REVIEW

**Comment by joscollin** [comment]
@rishabh-d-dave Please do an `fs:mirror` suite run for this PR. Thanks.

**Review by vshankar — APPROVED** [review]

**Comment by vshankar** [comment]
fs+smoke suite - https://pulpito.ceph.com/?branch=wip-vshankar-testing-20231206.125818

**Comment by vshankar** [comment]
@joscollin Test test_cephfs_mirror_peer_bootstrap checks for `mon_host`. That bit need to be fixed.

**Review by vshankar — CHANGES_REQUESTED** [review]
@joscollin PTAL

**Review by vshankar — APPROVED** [review]

**Comment by vshankar** [comment]
https://pulpito.ceph.com/?branch=wip-vshankar-testing-20240103.072409-1

**Comment by vshankar** [comment]
jenkins test windows

**Review by vshankar — APPROVED** [review]
https://tracker.ceph.com/projects/cephfs/wiki/Main#17th-Jan-2024

**Pull request merged**
