### PR TITLE
[RFC]msg: remove rx_buffers_version of Connection.

### PR DESCRIPTION
**Pull request by majianpeng**

### CODE REVIEW

**Comment by tchaikov** [comment]
retest this please

**Comment by yuyuyu101** [comment]
hmm, I forget why I not remove these lines before.....

**Comment by majianpeng** [comment]
@liewegas . Have you time to review this PR? Thanks!

**Comment by liewegas** [comment]
This makes me nervous because I don't understand or remember what the _version was being used for.  What was it protecting against, and (why) do we get away with not having it in AsyncMessenger?

**Comment by majianpeng** [comment]
For rx_version in Msg: No commit log mentioned this. post_rx_buffer only called in Objecter::_send_op. No way keep tid but change outbl for resent(abnormal reason).

I add #38db747 to make post_rx_buffer enable when op enable timeout.

**Comment by liewegas** [comment]
"Note that this still doesn't cover the op_cancel() paths, but none of those
users provide static buffers to read into."

Can you document that in the header file so we don't forget the limitation?

**Comment by majianpeng** [comment]
@liewegas . update by your suggestion.

**Comment by liewegas** [comment]
@majianpeng did you forget to push updated commits?

**Comment by majianpeng** [comment]
@liewegas . It's my fault. Now it's ok.

**Comment by majianpeng** [comment]
@liewegas .ping

**Comment by liewegas** [comment]
Oops, sorry for letting this go stale.  Can you rebase?

**Comment by liewegas** [comment]
needs rebase

**Comment by majianpeng** [comment]
@liewegas . Sorry later to response.  in the rebased problem, i met a strange gcc bug cause me took long time to review code and still can't fix currently.  But lucky, it passed in this environment. please review . Thanks!

**Pull request closed without merging**
