### PR TITLE
test: correct librbd errors discovered with unoptimized cmake build

### PR DESCRIPTION
**Pull request by dillaman**

### CODE REVIEW

**Comment by jdurgin** [comment]
lgtm, surprised unittest_bufferlist doesn't catch this

**Comment by tchaikov** [comment]
@jdurgin my bad, the equity operators of `list::{const_}iterator` is broken. we still need a friend `operator==` and friend `operator=!`. will add them and their tests accordingly after this change is merged.

**Comment by jdurgin** [comment]
thanks @tchaikov

**Comment by tchaikov** [comment]
test added at https://github.com/ceph/ceph/pull/7974

**Pull request merged**
