### PR TITLE
librados: add FULL_TRY flag; EDQUOT != ENOSPC

### PR DESCRIPTION
**Pull request by liewegas**

### CODE REVIEW

**Comment by jdurgin** [comment]
pybind/rados.py could use the new flag too, otherwise lgtm

**Comment by jdurgin** [comment]
the description of what the flag does should probably go in librados.h too

**Comment by gregsfortytwo** [comment]
Hmm, blocking instead of returning ENOSPC or similar is breaking one of our cephfs tests as well. We need a good way to ask for those sorts of returns on every op, preferably in the kernel but definitely in userspace (via the objecter)...

**Comment by liewegas** [comment]
@gregsfortytwo which libcephfs test?  There's a librados flag to ask for that behavior.  Hopefully we can get away with making the behavior dependent on a feature bit.. although we can do that if we need to (probably use an existing bit as a proxy).

**Comment by liewegas** [comment]
nearly passed wip-sage-testing.. i forgot ot whitelist 'reached quota', see https://github.com/ceph/ceph-qa-suite/pull/595

**Comment by liewegas** [comment]
@jdurgin documented.  I don't see any of the other operation flags in rados.py, though, so I'm not sure how best to add that.  Leaving out for now

**Pull request merged**
