### PR TITLE
luminous: backport and other test fixes for osd-scrub-repair.sh

### PR DESCRIPTION
**Pull request by dzafman**
http://tracker.ceph.com/issues/36393

---

Test fixes that are luminous specific

### CODE REVIEW

**Comment by dzafman** [comment]
run-standalone.sh all tests passed "ALL 39 TESTS PASSED"

**Comment by neha-ojha** [comment]
@smithfarm this PR has fixes specific to luminous, is there anything else we need to take care of before merging?

**Comment by smithfarm** [comment]
@neha-ojha The luminous-only commit messages look fine. The main thing is that the commit message should declare that the commit is luminous-only and either explain, or make it obvious, why it is not a cherry-pick.

The PR description did not mention the backport tracker issue - fixed.

The master tracker issue was not in Pending Backport state - fixed.

**Comment by smithfarm** [comment]
Also, the backport tracker issues were not in the backport tracker at all. It looks like they were created via manual copying, since the master issue was not in Pending Backport state.

A much less error-prone, and far faster and easier, way to create the backport tracker issues is to:

1. wait for the master PR to be merged
2. change the tracker state to "Pending Backport"
3. run src/script/backport-create-issue $ISSUE_NUMBER (where ISSUE_NUMBER is the master tracker issue whose state is "Pending Backport")

Hope this helps someone!

**Comment by yuriw** [comment]
[wip-yuri5-testing-2018-10-19-1535-luminous](https://trello.com/c/D2nF3EqQ/446-wip-yuri5-testing-2018-10-19-1535-luminous)

**Pull request merged**
