### PR TITLE
osd/PGPool::update: optimize with std::vector for intersection results

### PR DESCRIPTION
**Pull request by zmedico**
Use array_interval_set (based on std::vector) to store intersection
results, since it performs better than interval_set (based on std::map)
for all operations that this variable is involved in.

The following benchmark program shows a 20% increase in performance:
```c++
#include <iostream>
#include <chrono>
#include "include/interval_set.h"
#include "include/array_interval_set.hpp"

#define NANOSECONDS(d) \
    std::chrono::duration_cast<std::chrono::nanoseconds>(d).count()

typedef uint64_t snapid_t;
typedef std::chrono::steady_clock::duration duration;

template<class IntersectionSet>
duration PGPool_update(const interval_set<snapid_t> &rs) {
  std::chrono::steady_clock::time_point start, end;
  interval_set<snapid_t> newly_removed_snaps, cached_removed_snaps;

  // initialize state
  cached_removed_snaps = rs;

  // start timed simulation
  start = std::chrono::steady_clock::now();

  {
    newly_removed_snaps = cached_removed_snaps;
    IntersectionSet intersection;
    intersection.intersection_of(newly_removed_snaps, cached_removed_snaps);

    assert(intersection == cached_removed_snaps);
    cached_removed_snaps.swap(newly_removed_snaps);
    newly_removed_snaps = cached_removed_snaps;
    newly_removed_snaps.subtract(intersection);
  }

  // end timed simulation
  end = std::chrono::steady_clock::now();

  return end - start;
}

int main(int argc, char *argv[])
{
  assert(argc == 3);
  const int sample_count = std::stoi(argv[1]);
  const int interval_count = std::stoi(argv[2]);
  const int interval_distance = 4;
  const int interval_size = 2;
  const int max_offset = interval_count * interval_distance;
  interval_set<snapid_t> removed_snaps;

  for (int i = 0; i < max_offset; i += interval_distance)
    removed_snaps.insert(i, interval_size);

  duration old_delta(0), new_delta(0);

  for (int i = 0; i < sample_count; ++i) {
    old_delta += PGPool_update<interval_set<snapid_t>>(removed_snaps);
    new_delta += PGPool_update<array_interval_set<snapid_t>>(removed_snaps);
  }

  float ratio = float(NANOSECONDS(new_delta)) / NANOSECONDS(old_delta);

  std::cout << ratio << std::endl;
}
```

### CODE REVIEW

**Comment by branch-predictor** [comment]
This looks like a lot of extra code for a relatively small performance increase. I'll benchmark it for our use  cases and let you know what I found out.

**Comment by zmedico** [comment]
The following benchmark shows that there is actually no overall performance improvement. The costs of comparing the vector to the map, and copying from the vector to the map, outweigh the performance gained during the copy to vector and intersection operations.
```c++
#include <iostream>
#include <chrono>
#include "include/interval_set.h"
#include "include/array_interval_set.hpp"

typedef uint64_t snapid_t;

std::chrono::steady_clock::duration PGPool_update_old(const interval_set<snapid_t> &rs) {
  std::chrono::steady_clock::time_point start, end;
  interval_set<snapid_t> newly_removed_snaps, cached_removed_snaps;

  // initialize state
  cached_removed_snaps = rs;

  // start timed simulation
  start = std::chrono::steady_clock::now();

  {
    newly_removed_snaps = cached_removed_snaps;
    interval_set<snapid_t> intersection;
    intersection.intersection_of(newly_removed_snaps, cached_removed_snaps);

    assert(intersection == cached_removed_snaps);
    cached_removed_snaps.swap(newly_removed_snaps);
    newly_removed_snaps = cached_removed_snaps;
    newly_removed_snaps.subtract(intersection);
  }

  // end timed simulation
  end = std::chrono::steady_clock::now();

  return start - end;
}

std::chrono::steady_clock::duration PGPool_update_new(const interval_set<snapid_t> &rs) {
  std::chrono::steady_clock::time_point start, end;
  interval_set<snapid_t> newly_removed_snaps, cached_removed_snaps;

  // initialize state
  cached_removed_snaps = rs;

  // start timed simulation
  start = std::chrono::steady_clock::now();

  {
    array_interval_set<snapid_t> removed_snaps, intersection;
    removed_snaps.reserve(cached_removed_snaps.num_intervals() << 1);
    removed_snaps = cached_removed_snaps;
    intersection.intersection_of(removed_snaps, cached_removed_snaps);

    assert(intersection == cached_removed_snaps);
    cached_removed_snaps = removed_snaps;
    newly_removed_snaps = cached_removed_snaps;
    newly_removed_snaps.subtract(intersection);
  }

  // end timed simulation
  end = std::chrono::steady_clock::now();

  return start - end;
}

int main(int argc, char *argv[])
{
  assert(argc == 3);
  const int sample_count = std::stoi(argv[1]);
  const int interval_count = std::stoi(argv[2]);
  const int interval_distance = 4;
  const int interval_size = 2;
  const int max_offset = interval_count * interval_distance;
  interval_set<snapid_t> removed_snaps;

  for (int i = 0; i < max_offset; i += interval_distance)
    removed_snaps.insert(i, interval_size);

  std::chrono::steady_clock::duration old_delta(0), new_delta(0);

  for (int i = 0; i < sample_count; ++i) {
    old_delta += PGPool_update_old(removed_snaps);
    new_delta += PGPool_update_new(removed_snaps);
  }

  float ratio = float(std::chrono::duration_cast<std::chrono::nanoseconds>(new_delta).count())
    / std::chrono::duration_cast<std::chrono::nanoseconds>(old_delta).count();

  std::cout << ratio << std::endl;
}
```

**Comment by zmedico** [comment]
The benchmark is showing a 20% performance increase if I use array_interval_set just for the intersection variable alone, so I'll update the patch accordingly.

**Comment by zmedico** [comment]
See https://github.com/ceph/ceph/pull/17820 for a simpler approach that uses the inverval_set subset_of method to replace expensive  intersection_of and operator== calls.

**Comment by zmedico** [comment]
The benchmark for https://github.com/ceph/ceph/pull/17820 is showing superior performance. Maybe array_interval_set it useful for something else though.

**Comment by zmedico** [comment]
Closing in favor of https://github.com/ceph/ceph/pull/17820.

**Pull request closed without merging**
