### PR TITLE
quincy: mgr/dashboard: backport of all accessibility changes

### PR DESCRIPTION
**Pull request by nizamial09**
backport tracker: https://tracker.ceph.com/issues/58429

---

backport of https://github.com/ceph/ceph/pull/46510, https://github.com/ceph/ceph/pull/48137, https://github.com/ceph/ceph/pull/48002,https://github.com/ceph/ceph/pull/47857, https://github.com/ceph/ceph/pull/47510, https://github.com/ceph/ceph/pull/47250, https://github.com/ceph/ceph/pull/47249, https://github.com/ceph/ceph/pull/47054, https://github.com/ceph/ceph/pull/46972, https://github.com/ceph/ceph/pull/46958, https://github.com/ceph/ceph/pull/46757, https://github.com/ceph/ceph/pull/46757, https://github.com/ceph/ceph/pull/46723, https://github.com/ceph/ceph/pull/46510
parent tracker: https://tracker.ceph.com/issues/55820

this backport was staged using ceph-backport.sh version 16.0.0.6848
find the latest version at https://github.com/ceph/ceph/blob/main/src/script/ceph-backport.sh

### CODE REVIEW

**Review by anthonyeleven — APPROVED** [review]

**Comment by nSedrickm** [comment]
jenkins test dashboard cephadm

**Comment by nSedrickm** [comment]
jenkins test dashboard

**Comment by nSedrickm** [comment]
jenkins test windows

**Comment by nSedrickm** [comment]
jenkins test dashboard

**Comment by nSedrickm** [comment]
jenkins test dashboard cephadm

**Comment by nSedrickm** [comment]
jenkins test dashboard

**Comment by nSedrickm** [comment]
Thanks @nizamial09 this is a lot of work!

**Review by nSedrickm — COMMENTED** [review]
We are missing one PR #47249 which solves the issues for tabs

Screenshot from 2023-02-03 12-05-50

**Comment by nizamial09** [comment]
> We are missing one PR #47249 which solves the issues for tabs

Thanks for catching that, updated it. @nSedrickm

**Review by nSedrickm — APPROVED** [review]
Thanks @nizamial09, LGTM!

**Pull request merged**
