### PR TITLE
client: put MetaSession map container

### PR DESCRIPTION
**Pull request by batrick**
Simplifies memory management and reduces fragmentation.

### CODE REVIEW

**Comment by ukernel** [comment]
should we remove the line "delete s;" in _close_mds_session

**Comment by batrick** [comment]
Yes, that's probably what was causing the failures in QA. I had not looked at the core dumps yet. Thanks Zheng.

**Comment by batrick** [comment]
`Reviewed-by: Patrick Donnelly <pdonnell@redhat.com>`

**Comment by batrick** [comment]
This passed testing. Zheng, can you add your review?

**Pull request merged**
