### PR TITLE
(DNM) uuid: use boost uuid

### PR DESCRIPTION
**Pull request by dotnwat**

### CODE REVIEW

**Comment by benh57** [comment]
Sad to see this was never implemented considering its one of the only blockers for windows (mingw32) support.

**Comment by liewegas** [comment]
@benh57 If it's useful, please resurrect the patch!  I thought this was largely cosmetic.  If there's a good reason to switch let's do it.

**Comment by benh57** [comment]
Yes, my comment was based off the (very, very old) thread about libuuid not working on mingw32, which blocked the windows port -- switching to Boost allows librados more easily compile on windows. (within mingw32)

I'm not sure if this is still the case -- perhaps Noah knows?)

**Comment by dmick** [comment]
I *think* we have bits to change to boost::uuid in .. another port repo.  Let me dig a bit.

**Comment by dmick** [comment]
https://github.com/droneware/ceph/commits/librados-aix-port contains it among a lot of other stuff, and not in super-clean commits yet, but it's findable.

**Comment by noahdesu** [comment]
@benh57 i'm not sure about windows. i was interested in using it for freebsd/osx. using boost should make that easier too, iirc.

**Pull request closed without merging**
