### PR TITLE
jewel: rgw: bucket resharding

### PR DESCRIPTION
**Pull request by robbat2**
Backported from master; original 19 commits.

Fixes: http://tracker.ceph.com/issues/17756

### CODE REVIEW

**Comment by robbat2** [comment]
i have one issue, that this seems to destroy buckets :-(

**Comment by robbat2** [comment]
My first pass testing missed a commit when I was building the local copy, that was in this PR; hence it acted broken for a bit; but with the full PR, it does work.

**Comment by dachary** [comment]
@yehudasa does this backport look good to merge ? It passed the rgw suite at http://tracker.ceph.com/issues/17851#note-66.

**Comment by yehudasa** [comment]
@dachary lgtm

**Pull request merged**
