### PR TITLE
rgw: extend SIGHUP handler for realm reconfiguration

### PR DESCRIPTION
**Pull request by cbodley**
Adds a signal handler to trigger RGWRealmReloader to shut down and recreate RGWRados to reload the realm configuration and restart multisite sync.

### CODE REVIEW

**Comment by yehudasa** [comment]
@cbodley I think SIGUSR2 is used internally in valgrind, so maybe we'd want to hook this with SIGHUP instead? tie it into the generic ceph configuration reloader somehow

**Comment by cbodley** [comment]
It looks like we could install a different handler for SIGHUP, which calls both `RGWRealmReloader::handle_notify()` and `g_ceph_context->reopen_logs()`. I'll give that a try.

**Comment by theanalyst** [comment]
is it also possible to hook the `ceph tell` or  `injectargs` into RGW somehow?

**Comment by yehudasa** [comment]
@theanalyst no, you cannot use ceph tell or injectargs with client ceph apps.

**Comment by cbodley** [comment]
@yehudasa updated to piggy-pack realm reconfiguration on SIGHUP. the default `sighup_handler()` only calls `g_ceph_context->reopen_logs()` though.. was the goal to extend this to reload ceph.conf too? i wasn't able to find any examples of other daemons doing this, and i don't think there's a thread-safe way to do it (the config observers look like a step in this direction, but they haven't been fully adopted)

**Comment by yehudasa** [comment]
@cbodley eventually we'd probably want to be able to update all config via sighup, but this is fine for now I think.

**Pull request merged**
