### PR TITLE
nautilus: mgr/volumes: Add interface to get subvolume metadata

### PR DESCRIPTION
**Pull request by kotreshhr**
The following interface is added

"ceph fs subvolume info <vol_name> <sub_name> [<group_name>]"

The output is in json format with following fields

1. atime: access time of subvolume path in the format "YYYY-MM-DD HH:MM:SS"
2. mtime: modification time of subvolume path in the format "YYYY-MM-DD HH:MM:SS"
3. ctime: change time of subvolume path in the format "YYYY-MM-DD HH:MM:SS"
4. uid: uid of subvolume path
5. gid: gid of subvolume path
6. mode: mode of subvolume path
7. mon_addrs: list of monitor addresses
8. bytes_pcent: quota used in percentage if quota is set, else displays "undefined"
9. bytes_quota: quota size in bytes if quota is set, else displays "infinite"
10. bytes_used: current used size of the subvolume in bytes
11. created_at: time of creation of subvolume in the format "YYYY-MM-DD HH:MM:SS"
12. data_pool: data pool the subvolume belongs to
13. path: absolute path of a subvolume
14. type: subvolume type indicating whether it's clone or subvolume

Fixes: https://tracker.ceph.com/issues/45181
Signed-off-by: Kotresh HR <khiremat@redhat.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by kotreshhr** [comment]
@ajarr please take a look

**Comment by kotreshhr** [comment]
> See [#34681 (comment)](https://github.com/ceph/ceph/pull/34681#issuecomment-618422071)

same as [#34681 (comment reply)](https://github.com/ceph/ceph/pull/34681#issuecomment-618851542)

**Comment by ajarr** [comment]
https://github.com/ceph/ceph/pull/34681#issuecomment-618886198

**Comment by kotreshhr** [comment]
> [#34681 (comment)](https://github.com/ceph/ceph/pull/34681#issuecomment-618886198)

Done

**Comment by yuriw** [comment]
[wip-yuri3-testing-2020-05-06-1934-nautilus](https://trello.com/c/MdP7ZRct/899-wip-yuri3-testing-2020-05-06-1934-nautilus)

**Pull request merged**
