### PR TITLE
Revert "tools/cephfs/top/CMakeList.txt: check the minimum compatible python version for cephfs-top"

### PR DESCRIPTION
**Pull request by vshankar**
Reverts ceph/ceph#50089

### CODE REVIEW

**Comment by vshankar** [comment]
Packages building now - https://shaman.ceph.com/builds/ceph/wip-revert-50089/

**Review by joscollin — APPROVED** [review]

**Comment by vshankar** [comment]
jenkins test windows

**Comment by vshankar** [comment]
> Packages building now - https://shaman.ceph.com/builds/ceph/wip-revert-50089/

Build are fine - @dmick @joscollin @ljflores

**Comment by joscollin** [comment]
> > Packages building now - https://shaman.ceph.com/builds/ceph/wip-revert-50089/
> 
> Builds are fine - @dmick @joscollin @ljflores

Please merge this. Let's discuss the cephfs-top version check.

**Review by ljflores — COMMENTED** [review]
LGTM

**Pull request merged**
