### PR TITLE
Fix non-bluestore builds post-81e4560781c

### PR DESCRIPTION
**Pull request by asomers**
Signed-off-by: Alan Somers <asomers@gmail.com>

### CODE REVIEW

**Comment by asomers** [comment]
@Liuchang0812 could you review please?

**Comment by Liuchang0812** [comment]
thank you. would you mind updating your title and commit message to "os/bluestore: fix non-bluestore builds ......."?

this looks good to me, BTW, we should not show bluestore-kv option if we could not build bluestore.

**Comment by tchaikov** [comment]
could you prefix the title of your commit message with the subcomponent your are changing ? see https://github.com/ceph/ceph/blob/master/SubmittingPatches.rst#3-describe-your-changes

also, it'd be better if you could remove the tab in "Signed-off-by" line in your commit message.

**Comment by tchaikov** [comment]
@asomers @Liuchang0812 @wjwithagen i created a cleanup patch at #18221 in hope to fix the build on FreeBSD and the who-cares-the leak issue. could you help take a look?

**Comment by tchaikov** [comment]
closing in favor of #18221

**Pull request closed without merging**
