### PR TITLE
mgr/orch: remove a bunch of duplicated code

### PR DESCRIPTION
**Pull request by sebastian-philipp**
## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Review by mgfritch — APPROVED** [review]
:+1:

**Review by varshar16 — APPROVED** [review]

**Comment by sebastian-philipp** [comment]
jenkins test make check

**Comment by sebastian-philipp** [comment]
```
    from .module import Module, StandbyModule  # noqa: F401
module.py:27: in <module>
    from .services.exception import dashboard_exception_handler
services/exception.py:11: in <module>
    from orchestrator import OrchestratorError
../orchestrator/__init__.py:3: in <module>
    from .module import OrchestratorCli
../orchestrator/module.py:187: in <module>
    metaclass=CLICommandMeta):
../orchestrator/module.py:1070: in OrchestratorCli
    def _apply_misc(self, specs: Sequence[GenericSpec], dry_run: bool, format: Format) -> HandleCommandResult:
E   NameError: name 'GenericSpec' is not defined
```

```
ImportError while loading conftest '/home/jenkins-build/build/workspace/ceph-pull-requests/src/pybind/mgr/cephadm/tests/conftest.py'.
cephadm/__init__.py:1: in <module>
    from .module import CephadmOrchestrator
cephadm/module.py:29: in <module>
    from cephadm.serve import CephadmServe
cephadm/serve.py:21: in <module>
    import orchestrator
orchestrator/__init__.py:3: in <module>
    from .module import OrchestratorCli
orchestrator/module.py:187: in <module>
    metaclass=CLICommandMeta):
orchestrator/module.py:1070: in OrchestratorCli
    def _apply_misc(self, specs: Sequence[GenericSpec], dry_run: bool, format: Format) -> HandleCommandResult:
E   NameError: name 'GenericSpec' is not defined
```

```
orchestrator/__init__.py:3: note: In module imported here:
orchestrator/module.py: note: In member "_apply_misc" of class "OrchestratorCli":
orchestrator/module.py:1070: error: Name 'GenericSpec' is not defined
Found 1 error in 1 file (checked 23 source files)
ERROR: InvocationError for command /home/jenkins-build/build/workspace/ceph-pull-requests/src/pybind/mgr/.tox/mypy/bin/mypy --config-file=../../mypy.ini -m alerts -m balancer -m cephadm -m crash -m dashboard -m devicehealth -m hello -m iostat -m mds_autoscaler -m mgr_module -m mgr_util -m mirroring -m orchestrator -m progress -m prometheus -m rook -m snap_schedule -m stats -m status -m telemetry -m test_orchestrator -m volumes -m zabbix (exited with code 1)
flake8 create: /home/jenkins-build/build/workspace/ceph-pull-requests/src/pybind/mgr/.tox/flake8
flake8 installdeps: flake8
flake8 installed: DEPRECATION: --find-links option in pip freeze is deprecated. pip 21.2 will remove support for this functionality. You can find discussion regarding this at https://github.com/pypa/pip/issues/9069.,-f /home/jenkins-build/build/workspace/ceph-pull-requests/src/pybind/mgr/wheelhouse,flake8==3.8.4,importlib-metadata==3.4.0,mccabe==0.6.1,pycodestyle==2.6.0,pyflakes==2.2.0,typing-extensions==3.7.4.3,zipp==3.4.0
flake8 run-test-pre: PYTHONHASHSEED='594923299'
flake8 run-test: commands[0] | flake8 --config=tox.ini cephadm orchestrator
orchestrator/module.py:1070:43: F821 undefined name 'GenericSpec'
1     F821 undefined name 'GenericSpec'
```

**Comment by sebastian-philipp** [comment]
jenkins test make check

**Comment by sebastian-philipp** [comment]
https://pulpito.ceph.com/swagner-2021-02-17_14:01:13-rados:cephadm-wip-swagner-testing-2021-02-16-1806-distro-basic-smithi/

**Pull request merged**
