### PR TITLE
cephadm: Avoid crash on AppArmor profile names with space

### PR DESCRIPTION
**Pull request by smarsching**
Fixes: http://tracker.ceph.com/issues/66073

`cephadm shell` (and possibly other sub-commands) would crash when
there was an AppArmor profile that contained a space character in its
name. This happened due to the code parsing
`/sys/kernel/security/apparmor/profiles` only expecting a single space
character per line.

This commit fixes this issue by splitting the line on the last space
character instead of splitting it on each one.

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [X] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [X] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [X] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [X] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Review by phlogistonjohn — COMMENTED** [review]
Change looks OK but ideally we'd have some sort of test to avoid regressions, probably a unit test. Unfortunately, the host_facts stuff is a bit monolithic so I don't know how difficult it would be.  Have you looked into adding a unit test?  If not, could I bother you to do so but spend no more than a week at most on it. If you respond that you looked into it and it was too hard to write I'd happily approve anyway. I just don't want to miss the opporunity to have a test if it's not a big burden. Thanks!

**Comment by smarsching** [comment]
@phlogistonjohn I considered writing a unit test, but due to there being no unit tests for `HostFacts` at all, this would be a major task:

Testing `_fetch_apparmor` on its own would be reasonably simple: I would just have to mock-patch `os.path.exists` and `read_file`. However, there is no way to test `_fetch_apparmor` directly, because it is defined inside the `kernel_security` method, so the lowest level which the unit test could target is that method.

This is already a lot harder, because `read_file` and now has to be patched in way so that it returns different results for different arguments (as it is used multiple times in the functions called by `kernel_security`). In addition to that `call` would have to be mocked in order to make the `_fetch_selinux` function work.

But the work does not stop there: As `read_file` is a method, we need an instance of `HostFacts` to test it, so we have to mock-patch even more code in order to make the constructor work correctly regardless of the environment.

It certainly is possible to do this, but quite frankly I do not have the time to do all that work.

The best thing that I can offer is making `_fetch_apparmor` a module-level function, so that it can be tested on its own. Do you think that this makes sense?

I discarded this idea because I wanted to keep the change for the bugfix minimal, in particular considering that I think it should be backported to Reef, and for a simple one-line fix this is much more reasonable than for a refactoring of the `HostFacts` logic.

**Comment by smarsching** [comment]
A quick update: In the meantime, I found that this problem also affects Ubuntu 24.04 Server, not just the Desktop version. 

And unfortunately, it cannot simply be fixed by replacing the `cephadm` executable in the host system with a patched version, because `cephadm` is also used internally, and in this case the version from the Docker image is used.

For example, this happens when running `ceph health detail`:

```
[WRN] CEPHADM_REFRESH_FAILED: failed to probe daemons or devices
    host XXXXXXXX `cephadm gather-facts` failed: cephadm exited with an error code: 1, stderr: Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/var/lib/ceph/ea2b2af0-1879-11ef-a6b1-0cc47a841bc8/cephadm.2b9d7d139a9cb40289f2358faf49a109fc297c0a258bde893227c262c30bca8d/__main__.py", line 10700, in <module>
  File "/var/lib/ceph/ea2b2af0-1879-11ef-a6b1-0cc47a841bc8/cephadm.2b9d7d139a9cb40289f2358faf49a109fc297c0a258bde893227c262c30bca8d/__main__.py", line 10688, in main
  File "/var/lib/ceph/ea2b2af0-1879-11ef-a6b1-0cc47a841bc8/cephadm.2b9d7d139a9cb40289f2358faf49a109fc297c0a258bde893227c262c30bca8d/__main__.py", line 9772, in command_gather_facts
  File "/var/lib/ceph/ea2b2af0-1879-11ef-a6b1-0cc47a841bc8/cephadm.2b9d7d139a9cb40289f2358faf49a109fc297c0a258bde893227c262c30bca8d/__main__.py", line 9762, in dump
  File "/var/lib/ceph/ea2b2af0-1879-11ef-a6b1-0cc47a841bc8/cephadm.2b9d7d139a9cb40289f2358faf49a109fc297c0a258bde893227c262c30bca8d/__main__.py", line 9677, in kernel_security
  File "/var/lib/ceph/ea2b2af0-1879-11ef-a6b1-0cc47a841bc8/cephadm.2b9d7d139a9cb40289f2358faf49a109fc297c0a258bde893227c262c30bca8d/__main__.py", line 9658, in _fetch_apparmor
ValueError: too many values to unpack (expected 2)
```

**Comment by phlogistonjohn** [comment]
Hi there. I wanted to let you know that yesterday I filed PR #57955 in response to https://tracker.ceph.com/issues/66389 because I saw that issue yesterday afternoon while I was waiting for something else to complete. I had forgotten about this PR and it did not occur to me at the time to check if that issue was a duplicate.

I hope you understand, but I think we ought to go forward with #57955 because it includes unit tests as well as cleans up the code. I do think that this patch ought to fix the problem but it does continue to leave an unused variable in the code ("item").  I've had project maintainers rewrite contributions I've submitted before so I sympathize if you were hoping to have a change you created become part of the project. As such, I'd like you give you an `Original-version-by` trailer credit in my commit in PR #57955. Sound OK?

Thanks to @adk3798 for pointing out the duplicate work.

**Comment by smarsching** [comment]
@phlogistonjohn Sure, that’s fine by me. The important thing is that this issue gets fixed, and a patch that includes tests is certainly better than a patch that does not.

**Comment by adk3798** [comment]
Closing in favor of https://github.com/ceph/ceph/pull/57955 as per https://github.com/ceph/ceph/pull/57527#issuecomment-2160809397 and https://github.com/ceph/ceph/pull/57527#issuecomment-2161190071

**Pull request closed without merging**
