### PR TITLE
DNM: jewel: rbd-mirror: gracefully handle being blacklisted

### PR DESCRIPTION
**Pull request by dillaman**
http://tracker.ceph.com/issues/16658

### CODE REVIEW

**Comment by dillaman** [comment]
retest this please

**Comment by dachary** [comment]
conflicts with https://github.com/ceph/ceph/pull/10678

**Comment by dillaman** [comment]
@dachary rebased

**Comment by dachary** [comment]
Hey jenkins, test this please.

**Comment by dachary** [comment]
Conflict with https://github.com/ceph/ceph/pull/10684, wait for it to be merged

**Comment by dachary** [comment]
Hey jenkins, test this please. (bluefs crash)

**Comment by dachary** [comment]
Included in https://github.com/ceph/ceph/pull/10684

**Pull request closed without merging**
