### PR TITLE
qa/tasks: backport rbd_fio fixes to jewel

### PR DESCRIPTION
**Pull request by idryomov**
http://tracker.ceph.com/issues/13512

### CODE REVIEW

**Comment by idryomov** [comment]
Test run: http://pulpito.front.sepia.ceph.com/dis-2017-01-25_15:29:05-krbd-jewel-testing-basic-mira/.
All rbd devices unmapped as expected.

**Comment by smithfarm** [comment]
@dachary Do you think @idryomov 's test run is sufficient to merge this PR?

**Comment by smithfarm** [comment]
`suite_sha1: 61e1b0caddfbc3721cd9fa2de5b90b2f65740f79 `

**Comment by smithfarm** [comment]
@dillaman This PR was tested by @idryomov as per the above comments. OK to merge?

**Pull request merged**
