### PR TITLE
test/common/unittest_blkdev: delete unused test file

### PR DESCRIPTION
**Pull request by zealoussnow**
Signed-off-by: Leo Zhang <nguzcf@gmail.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by zealoussnow** [comment]
When I use `git checkout -b master origin/master` on Windows, got error as following:

```
# git checkout -b master
error: invalid path src/test/common/test_blkdev_sys_block/sys/dev/block/8:0
error: invalid path src/test/common/test_blkdev_sys_block/sys/dev/block/9:0
```

and I use `git grep -n "test_blkdev_sys_block"` on src/test, no code use it, so I delete it.

**Comment by zealoussnow** [comment]
@asomers need a review please.

**Comment by tchaikov** [comment]
i think it's used by `unittest_blkdev`.

**Comment by asomers** [comment]
Yeah.  It's been a long time since I've worked on this, but as tchaikov said, I think those files are used by the test.  Have you run the tests on Linux?

**Comment by zealoussnow** [comment]
@asomers Sorry, I don't run the tests on Linux, how can I do these tests now?

**Comment by zealoussnow** [comment]
@asomers  I only run `unittest_blkdev` on Linux

```
# export CEPH_ROOT="/home/leo/ceph-build"
# ./unittest_blkdev
Running main() from gmock_main.cc
[==========] Running 4 tests from 2 test suites.
[----------] Global test environment set-up.
[----------] 3 tests from BlockDevTest
[ RUN      ] BlockDevTest.device_model
[       OK ] BlockDevTest.device_model (0 ms)
[ RUN      ] BlockDevTest.discard
[       OK ] BlockDevTest.discard (0 ms)
[ RUN      ] BlockDevTest.is_rotational
[       OK ] BlockDevTest.is_rotational (0 ms)
[----------] 3 tests from BlockDevTest (1 ms total)

[----------] 1 test from blkdev
[ RUN      ] blkdev._decode_model_enc
 'WDC\x20WDS200T2B0A-00SM50\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20' -> 'WDC_WDS200T2B0A-00SM50'
[       OK ] blkdev._decode_model_enc (0 ms)
[----------] 1 test from blkdev (0 ms total)

[----------] Global test environment tear-down
[==========] 4 tests from 2 test suites ran. (1 ms total)
[  PASSED  ] 4 tests.
```

**Comment by tchaikov** [comment]
@zealoussnow i think you might want to amend the commit message. IMHO, the test-and-it-works is not the best way to document a change or to prove the correctness of a change. i think, the reason this change is correct is that the only place where `sysfsdir()` is used is `BlkDev::get_string_property()`, in which, we only use `/sys/block/` for looking up a given block device by its name, and we don't use `/sys/dev/` by looking up a device by the major id and minor id of that device.

**Comment by zealoussnow** [comment]
@tchaikov OK

**Pull request merged**
