### PR TITLE
cmake: only build/link necessary boost libs 

### PR DESCRIPTION
**Pull request by tchaikov**

### CODE REVIEW

**Comment by smithfarm** [comment]
@tchaikov The last commit in this PR is quite similar to https://github.com/ceph/ceph/pull/15225/commits/8e4900d04d85d1a4d5344eef8d189d87de28fab2 and this PR and #15225 seem to be working toward the same goal. Shall we merge them?

**Comment by tchaikov** [comment]
@smithfarm i have no objection merging them. i wanted to improve it before doing so.

**Comment by tchaikov** [comment]
closing in favor of #15225

**Comment by tchaikov** [comment]
cherry-pick a commit in this PR and put it into #15347

**Comment by smithfarm** [comment]
> i wanted to improve it before doing so.

And I appreciate that!

**Comment by tchaikov** [comment]
anyway, if you feel like to use some help, let me know.

**Comment by smithfarm** [comment]
I *always* need help :-)

**Comment by tchaikov** [comment]
@smithfarm https://github.com/smithfarm/ceph/pull/1

**Pull request closed without merging**
