### PR TITLE
mgr/prometheus: add type annotations 

### PR DESCRIPTION
**Pull request by tchaikov**
## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by tchaikov** [comment]
hello @sebastian-philipp @p-se do you mind taking a look at this change?

**Review by sebastian-philipp — APPROVED** [review]
lgtm

**Review by p-se — APPROVED** [review]
lgtm

**Comment by tchaikov** [comment]
- https://pulpito.ceph.com/kchai-2021-03-06_09:19:54-rados-wip-kefu-testing-2021-03-06-1553-distro-basic-smithi/
- https://pulpito.ceph.com/kchai-2021-03-07_12:30:50-rados-wip-kefu-testing-2021-03-07-1842-distro-basic-smithi/


failures tracked by

- https://tracker.ceph.com/issues/49638
- https://tracker.ceph.com/issues/49484

**Pull request merged**
