### PR TITLE
erasure-code: mark the shec plugin as experimental

### PR DESCRIPTION
**Pull request by dachary**

### CODE REVIEW

**Comment by dachary** [comment]
@t-miyamae the general idea of this pull request is that ceph users do not have the same stability expectations for the shec plugin than they have for the jerasure plugin. Would you have time to review it ?

**Comment by liewegas** [comment]
looks good to me!  const string would be nicer but this isn't a hot path so it doesn't matter much

**Comment by dachary** [comment]
@tchaikov changed the constness of the string. @liewegas thanks for the review :-)

**Comment by t-miyamae** [comment]
I'm sorry for reviewing so late. There seems to be no problems, although I couldn't test the codes in my environment.
By the way, from what events could the mark of experimental feature be released in general? Are there any standards for that?

**Comment by dachary** [comment]
> I'm sorry for reviewing so late. There seems to be no problems, although I couldn't test the codes in my environment.

No worries, there was no urgency for that review and having too many reviews

> By the way, from what events could the mark of experimental feature be released in general? Are there any standards for that?

I'm not sure what you mean ? Maybe it's more convenient to discuss this on the ceph-devel mailing list.

**Pull request merged**
