### PR TITLE
DNM: pg_interval_t::check_new_interval - for ec pool, should not rely on min_size to determine if the PG was active at the interval

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/12488

### CODE REVIEW

**Comment by smithfarm** [comment]
repushed so I can take a look at the build failure

**Comment by smithfarm** [comment]
@dachary Here is the backport of https://github.com/ceph/ceph/pull/1865 . . . Four out of the five commits applied cleanly. See 30420a5 for my resolution of the one that didn't.

**Comment by smithfarm** [comment]
@dachary Please review. If you think the backport of #1865 is OK, I will proceed to backport #5093 on top of it.

**Comment by dachary** [comment]
Why are ccd44a0 and 0a23263 necessary exactly ? The same modification must be in a commit somewhere. How come this commit is not part of this series ? Can we maybe add it to the series instead of introducing two new commits ? I'm concerned that it hides a larger problem.

**Comment by dachary** [comment]
@smithfarm assigning to myself as a reviewer

**Comment by smithfarm** [comment]
@dachary Updated commit message as requested.

**Comment by smithfarm** [comment]
ready for integration tests

**Comment by dachary** [comment]
@athanatos  does this backport look good to merge ? It passed a run of the firefly rados suite ( see http://tracker.ceph.com/issues/11644#note-110 ).

**Comment by dachary** [comment]
I'm not sure if the tests cover this case. The backport could probably be simpler if 150092a was adapted to firefly and no other commit was backported (except maybe 2a23072). I fear it is too complicated although it seems to work and I'm worried we may miss something.

**Comment by smithfarm** [comment]
@dachary As far as I'm concerned, you're welcome to re-do the PR in the way you just described.

**Comment by athanatos** [comment]
I would prefer that the PR be done the way Loic indicated.

**Pull request closed without merging**
