### PR TITLE
mimic:  rgw: handle S3 version 2 pre-signed urls with meta-data

### PR DESCRIPTION
**Pull request by ashishkumsingh**
http://tracker.ceph.com/issues/37558

### CODE REVIEW

**Comment by mattbenjamin** [comment]
@ashishkumsingh are you doing Luminous, as well?

**Comment by ashishkumsingh** [comment]
> @ashishkumsingh are you doing Luminous, as well?
@mattbenjamin yes, that is in progress.

**Comment by ashishkumsingh** [comment]
> @ashishkumsingh are you doing Luminous, as well?

@mattbenjamin yes, that is in progress.

**Comment by yuriw** [comment]
[wip-yuri4-testing-2019-01-18-1556-mimic](https://trello.com/c/JXYqBvOa/516-wip-yuri4-testing-2019-01-18-1556-mimic)

**Pull request merged**
