### PR TITLE
luminous: qa: malformed job

### PR DESCRIPTION
**Pull request by batrick**
backport tracker: https://tracker.ceph.com/issues/42678
possibly a backport of https://github.com/ceph/ceph/pull/29431
parent tracker: https://tracker.ceph.com/issues/41031

---

original PR body:

luminous backport of https://tracker.ceph.com/issues/41031
 don't have a tracker ticket generated yet...

---

updated using ceph-backport.sh version 15.0.0.6950

### CODE REVIEW

**Comment by batrick** [comment]
Fixes http://pulpito.ceph.com/yuriw-2019-11-05_00:14:00-fs-wip-yuri5-testing-2019-11-04-2055-luminous-testing-basic-smithi/4473505/

**Comment by batrick** [comment]
ping @yuriw

**Comment by smithfarm** [comment]
> don't have a tracker ticket generated yet...

You can generate the backport tracker tickets by running:

```
backport-create-issue [PARENT_ISSUE_NUMBER]
```

This is (only very) slightly painful in that one must have the dependencies installed for the script to run properly - personally, I use a virtualenv for this.

**Comment by yuriw** [comment]
[wip-yuri5-testing-2019-11-15-1531-luminous](https://trello.com/c/YlSLupiJ/763-wip-yuri5-testing-2019-11-15-1531-luminous)

**Pull request merged**
