### PR TITLE
cmake: support Node.js and npm registry mirror

### PR DESCRIPTION
**Pull request by tchaikov**
## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by tchaikov** [comment]
tested using
```sh
NODE_MIRROR=https://npm.taobao.org/mirrors/node NPM_REGISTRY=https://registry.npm.taobao.org cmake ..
```

**Comment by tchaikov** [comment]
jenkins test docs

**Review by badone — APPROVED** [review]
Looks OK to me.

**Review by tspmelo — APPROVED** [review]
works using ceph-dev-docker.

**Comment by epuertat** [comment]
Got late, sorry! I was going to suggest using the provided environment variables instead (`npm_node_registry` for npm, `PIP_INDEX_URL` for pip...). No big deal as this works anyway.

**Comment by tchaikov** [comment]
@epuertat where are these two environmental variable defined or exposed?

**Comment by epuertat** [comment]
@tchaikov those are env. variables from each of these tools. By injecting those via env. vars in the CI (Jenkins, Docker or whatever) you can control where these tool feed from. I get that their naming is not homogeneous, but at least those env. vars exist. Nevertheless, nothing really serious.

**Comment by tchaikov** [comment]
@epuertat you mean they are consumed by these tools automatically? in other words, we can just partially revert these changes? so user can just use
```sh
export npm_node_registry=<REGISTRY_URL>
```
when running, for instance `make` ?

**Comment by epuertat** [comment]
@tchaikov I guess so, based on their docs... However, as we are using virtualenvs and probably calling scripts, I'm not so sure that these external env. variables would become available to the internal instances of `npm`/`pip`/... Don't worry, this is perfectly ok!

**Comment by tchaikov** [comment]
@epuertat, i see. i am not familiar with this area. yeah, if any of us with savvy of npm would like to improve it, i'd like to review  the PR.

**Comment by epuertat** [comment]
@tchaikov sure! I don't know what is the context of this, but I was thinking of local PIP/Node registry caches for speeding up and saving networking resources during [the Jenkins `make check` pipeline](https://jenkins.ceph.com/job/ceph-multibranch-pipeline/job/PR-37425/).

**Comment by tchaikov** [comment]
i think a shared cache which persists across `make check` runs would serve this purpose better.

**Pull request merged**
