### PR TITLE
buffer: avoid changing bufferlist ABI by removing new _mempool field

### PR DESCRIPTION
**Pull request by liewegas**
This also improves the buffer allocation to avoid jumping between
multiple mempools.

### CODE REVIEW

**Comment by tchaikov** [comment]
better off marking with `Fixes: http://tracker.ceph.com/issues/21573`.

**Comment by yuriw** [comment]
we need to run client upgrades for this 
teuthology-suite -v -c $CEPH_BRANCH  -n 7 -m $MACHINE_NAME -s upgrade/client-upgrade-hammer -k distro -e $CEPH_QA_EMAIL --suite-branch hammer

teuthology-suite -v -c $CEPH_BRANCH  -n 7 -m $MACHINE_NAME -s upgrade/client-upgrade-jewel -k distro -e $CEPH_QA_EMAIL --suite-branch jewel

teuthology-suite -v -c $CEPH_BRANCH  -n 7 -m $MACHINE_NAME -s upgrade/client-upgrade-kraken -k distro -e $CEPH_QA_EMAIL --suite-branch kraken

**Comment by yuriw** [comment]
trying on `wip-kefu-testing-2017-10-20-1713`

http://pulpito.ceph.com/yuriw-2017-10-20_15:24:35-upgrade:client-upgrade-kraken-wip-kefu-testing-2017-10-20-1713-distro-basic-smithi/
http://pulpito.ceph.com/yuriw-2017-10-20_15:24:09-upgrade:client-upgrade-jewel-wip-kefu-testing-2017-10-20-1713-distro-basic-smithi/
http://pulpito.ceph.com/yuriw-2017-10-20_15:23:11-upgrade:client-upgrade-hammer-wip-kefu-testing-2017-10-20-1713-distro-basic-smithi/

**Comment by yuriw** [comment]
runs of vps failed, maybe related to @kchiu PR?

http://pulpito.ceph.com/yuriw-2017-10-20_15:28:38-upgrade:client-upgrade-hammer-wip-kefu-testing-2017-10-20-1713-distro-basic-vps/
http://pulpito.ceph.com/yuriw-2017-10-20_15:27:17-upgrade:client-upgrade-kraken-wip-kefu-testing-2017-10-20-1713-distro-basic-vps/
http://pulpito.ceph.com/yuriw-2017-10-20_15:27:44-upgrade:client-upgrade-jewel-wip-kefu-testing-2017-10-20-1713-distro-basic-vps/

@djgalloway looked and found no dependency and no disk problems FYI

**Comment by yuriw** [comment]
@tchaikov there were lots of nodes left in `stale un-nukable` stale that I re-imaged, not sure if it's related just FYI.  @zmc suggested it could be because tests used `exclude_packages in upgrade_workload`

See copy from IRC chat

`(03:01:11 PM) yuriw: we have like a zillion of un-nukable nodes https://pastebin.com/mbRPtmDj
(03:01:21 PM) yuriw: dgalloway ^
(03:02:26 PM) yuriw: and error snippet https://pastebin.com/BcETLKqy
(03:03:03 PM) yuriw: zackc ^
(03:06:01 PM) zackc: wow.
(03:06:07 PM) zackc: that is "apt autoremove" failing
(03:06:24 PM) yuriw: did we do anything ?
(03:07:04 PM) zackc: isolating one host: https://pastebin.com/HZ8588RS
(03:08:50 PM) zackc: how is this even possible https://pastebin.com/RAzM8Wbv
(03:10:28 PM) zackc: ooh! i finally get to see some green http://pulpito.ceph.com/zack-2017-10-20_20:59:14-cephmetrics-master-distro-basic-vps/
(03:10:34 PM) zackc: (i knew centos would fail)
(03:10:51 PM) dmick: it's not easy seeing green
(03:11:13 PM) zackc: !haiku add_use sevens it's not easy seeing green
(03:11:38 PM) zackc: 😩
(03:13:08 PM) zackc: smithi062 last ran http://pulpito.ceph.com/yuriw-2017-10-20_15:24:09-upgrade:client-upgrade-jewel-wip-kefu-testing-2017-10-20-1713-distro-basic-smithi/1754023/
(03:13:29 PM) zackc: which has a whole lot of package-related sadness
(03:13:51 PM) zackc: like:
(03:13:58 PM) zackc: 2017-10-20T19:21:42.200 INFO:teuthology.orchestra.run.smithi062.stderr:dpkg: error processing archive /var/cache/apt/archives/ceph-osd_13.0.0-2201-g6cc0b41-1trusty_amd64.deb (--unpack):
(03:13:58 PM) zackc: 2017-10-20T19:21:42.200 INFO:teuthology.orchestra.run.smithi062.stderr: trying to overwrite '/usr/bin/ceph-osdomap-tool', which is also in package ceph-test 10.2.10-14-gcbaddae-1trusty
(03:14:43 PM) zackc: possibly due to the exclude_packages in upgrade_workload ?
(03:20:35 PM) yuriw: maybe we saw some issues with david in the am and it what corrupted nodes?
(03:21:09 PM) yuriw: sage this ^ on kefu's 'buffer' pr 
(03:36:48 PM) yuriw: zackc: you think I should reimage them ?
(03:43:23 PM) zackc: yeah i think that's the only option at this point
(03:43:51 PM) yuriw: ok btw they were other runs as well 
(03:43:55 PM) yuriw: will start 
(03:44:09 PM) yuriw: *** Friday Friday !!!
(04:17:10 PM) yuriw: all done 
(04:17:44 PM) yuriw: running nuke/stale`

**Comment by yuriw** [comment]
I also unsure if the way I ran then (on `luminous`) is valid at all!

**Comment by tchaikov** [comment]
- http://pulpito.ceph.com/kchai-2017-10-20_15:10:22-rados-wip-kefu-testing-2017-10-20-1713-distro-basic-mira/
- http://pulpito.ceph.com/kchai-2017-10-21_00:57:41-rados-wip-kefu-testing-2017-10-20-1713-distro-basic-mira/

**Comment by tchaikov** [comment]
@yuriw i think you did it right. the fix for the upgrade test is #18474

**Comment by tchaikov** [comment]
@yuriw see https://github.com/ceph/ceph/pull/18474#issuecomment-338632296, i am testing the jewel-x upgrade suite using the ceph/ceph:jewel branch.

**Pull request merged**
