### PR TITLE
mgr/smb: accept public_addrs on cli when creating cluster

### PR DESCRIPTION
**Pull request by spuiuk**
We can set the public ip address to set for the cluster using the declarative method by providing the information in the resource description. The corresponding functionality is not available with the imperative method of creating the smb cluster.

This patch adds this functionality by allowing the user the option of providing the a public address on the command line when creating the smb cluster.

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [x] New feature (ticket optional)
  - [x] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [x] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [x] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Review by phlogistonjohn — COMMENTED** [review]
generally looks OK. ping me when it's out of draft for final review

**Comment by spuiuk** [comment]
To test, I create a smb cluster and share with the following commands
```
ceph smb cluster create mysmb2 user --define_user_pass test1%x --clustering default --public_addrs "192.168.145.31/24"
ceph smb share create mysmb2 mysmb2-root mycephfs "/" --subvolume=smbshares
```
I finally tested the samba share using smbclient
```
smbclient -U test1%x //mycephfs11/mysmb2-root/
```

I was also able to exec into the container and confirm that the public ip address was setup as expected.

**Review by phlogistonjohn — APPROVED** [review]
lgtm

**Comment by phlogistonjohn** [comment]
I won't demand it for this PR. But it would be nice to follow this up with a teuthology test that works similarly to the existing test with the declaritive form but using these new cli params.

**Comment by spuiuk** [comment]
Had an error with check-black. Pushed a new version with the fix proposed by black.

**Comment by phlogistonjohn** [comment]
jenkins test make check

**Comment by phlogistonjohn** [comment]
@avanthakkar is going to look at adding a teuthology test after this PR as a follow up task

**Review by avanthakkar — APPROVED** [review]
LGTM! 
I was just wondering if it makes sense to add validation for `public_addrs`?

**Comment by phlogistonjohn** [comment]
@adk3798 please include in a test run at your earliest convenience. Thanks!

**Comment by avanthakkar** [comment]
> @adk3798 please include in a test run at your earliest convenience. Thanks!

I can trigger orch run for now

**Comment by avanthakkar** [comment]
shaman build is stuck from more than 8 hrs now :neutral_face: 
https://shaman.ceph.com/builds/ceph/wip-athakkar-testing-2024-10-08-1203/

**Comment by phlogistonjohn** [comment]
There have been sepia lab disruptions for hours. See #sepia channel in ceph slack for details.
These infra issues may have impacted your build.

**Comment by phlogistonjohn** [comment]
https://pulpito.ceph.com/phlogistonjohn-2024-10-13_22:59:47-orch:cephadm-wip-phlogistonjohn-testing-1-2024-10-13-1520-distro-default-smithi/

All smb tests in this run failed:
* Many failed due to CEPHADM_FAILED_DAEMON
* Some failed to execute smbclient
* Some failed to run `ceph orch ls -f json` while waiting for service(s) to start

I reproduced the CEPHADM_FAILED_DAEMON error locally using this build and it appears to be caused by PR #60251 .
```
[root@ceph0 ~]# ceph health  detail
Inferring fsid 844919f4-8a35-11ef-9252-525400220000
Inferring config /var/lib/ceph/844919f4-8a35-11ef-9252-525400220000/mon.ceph0/config
HEALTH_WARN 1 failed cephadm daemon(s)
[WRN] CEPHADM_FAILED_DAEMON: 1 failed cephadm daemon(s)
    daemon smb.cluster1.ceph0.lgdeld on ceph0 is in unknown state
```

I'm going to assume that cephadm is more sensitive than I thought to the status value being returned and is the cause of the other errors. Will rebuild and re-run the tests without PR #60251 .

**Comment by phlogistonjohn** [comment]
https://pulpito.ceph.com/phlogistonjohn-2024-10-15_11:51:33-orch:cephadm-wip-phlogistonjohn-testing-1-2024-10-14-1026-distro-default-smithi/
Failures include:
* random teuthology infra problems (importing tasks module)
* stray ctdb daemons
I consider the latter a "success" as the test passes before these are checked and this stray daemons check is a well known issue

I consider this run an overall success and I think the PR can be merged.

**Pull request merged**
