### PR TITLE
mgr/cephadm: do not use sudo for root user

### PR DESCRIPTION
**Pull request by rkachach**
Do not use sudo for root user since it's not needed and it may break in systems where root is not included in `/etc/sudoers`.

Fixes: https://tracker.ceph.com/issues/55641
Signed-off-by: Redouane Kachach <rkachach@redhat.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/master/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [x] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Review by adk3798 — APPROVED** [review]

**Comment by adk3798** [comment]
https://pulpito.ceph.com/adking-2022-05-18_00:20:23-orch:cephadm-wip-adk-testing-2022-05-17-1753-distro-basic-smithi/

1 failure in new staggered upgrade test, caused by staggered upgrade PR in this run. Unrelated to changes in this PR.

**Comment by bluikko** [comment]
I thought that this works since this fixed my issues on EL8, but on RHEL9 host there is again an issue that looks like `sudo` not allowed by the root user:
```
Sep 01 14:59:35 host.example.com sudo[42449]:     root : user NOT in sudoers ; PWD=/root ; USER=root ; COMMAND=/usr/bin/true
Sep 01 14:59:35 host.example.com sshd[42448]: Received disconnect from 192.0.2.1 port 37166:11: Disconnected by application
Sep 01 14:59:35 host.example.com sshd[42448]: Disconnected from user root 192.0.2.1 port 37166
Sep 01 14:59:35 host.example.com ceph-mgr[38560]: [cephadm ERROR orchestrator._interface] Unable to reach remote host host.example.com. Process exited with non-zero exit status 1
                                                 Traceback (most recent call last):
                                                   File "/usr/share/ceph/mgr/cephadm/ssh.py", line 143, in _execute_command
                                                     r = await conn.run('sudo true', check=True, timeout=5)
                                                   File "/lib/python3.6/site-packages/asyncssh/connection.py", line 3637, in run
                                                     return await process.wait(check, timeout)
                                                   File "/lib/python3.6/site-packages/asyncssh/process.py", line 1257, in wait
                                                     self.returncode, stdout_data, stderr_data)
                                                 asyncssh.process.ProcessError: Process exited with non-zero exit status 1

                                                 During handling of the above exception, another exception occurred:

                                                 Traceback (most recent call last):
                                                   File "/usr/share/ceph/mgr/orchestrator/_interface.py", line 125, in wrapper
                                                     return OrchResult(f(*args, **kwargs))
                                                   File "/usr/share/ceph/mgr/cephadm/module.py", line 2565, in apply
                                                     results.append(self._apply(spec))
                                                   File "/usr/share/ceph/mgr/cephadm/module.py", line 2429, in _apply
                                                     return self._add_host(cast(HostSpec, spec))
                                                   File "/usr/share/ceph/mgr/cephadm/module.py", line 1404, in _add_host
                                                     ip_addr = self._check_valid_addr(spec.hostname, spec.addr)
                                                   File "/usr/share/ceph/mgr/cephadm/module.py", line 1385, in _check_valid_addr
                                                     error_ok=True, no_fsid=True))
                                                   File "/usr/share/ceph/mgr/cephadm/module.py", line 590, in wait_async
                                                     return self.event_loop.get_result(coro)
                                                   File "/usr/share/ceph/mgr/cephadm/ssh.py", line 48, in get_result
                                                     return asyncio.run_coroutine_threadsafe(coro, self._loop).result()
                                                   File "/lib64/python3.6/concurrent/futures/_base.py", line 432, in result
                                                     return self.__get_result()
                                                   File "/lib64/python3.6/concurrent/futures/_base.py", line 384, in __get_result
                                                     raise self._exception
                                                   File "/usr/share/ceph/mgr/cephadm/serve.py", line 1317, in _run_cephadm
                                                     python = await self.mgr.ssh._check_execute_command(host, cmd, addr=addr)
                                                   File "/usr/share/ceph/mgr/cephadm/ssh.py", line 183, in _check_execute_command
                                                     out, err, code = await self._execute_command(host, cmd, stdin, addr)
                                                   File "/usr/share/ceph/mgr/cephadm/ssh.py", line 151, in _execute_command
                                                     raise OrchestratorError(f'Unable to reach remote host {host}. {str(e)}')
                                                 orchestrator._interface.OrchestratorError: Unable to reach remote host host.example.com. Process exited with non-zero exit status 1
```

Not sure if I should open an issue in the bug tracker for this...  
The `ssh.py` seems to have this patch in `/usr/share/ceph/mgr/cephadm/ssh.py`.

**Comment by adk3798** [comment]
@bluikko 
https://tracker.ceph.com/issues/57369 
https://github.com/ceph/ceph/pull/47898

**Comment by bluikko** [comment]
@adk3798 I see so it is a known issue. Thanks for pointing that out.

**Pull request merged**
