### PR TITLE
Fix racey test by setting noout flag (tracker 17757)

### PR DESCRIPTION
**Pull request by dzafman**
Want to see what Jenkins does with this showing ceph pg dump pgs in the log.

### CODE REVIEW

**Comment by dzafman** [comment]
jenkins test this please

**Comment by dzafman** [comment]
Passed Jenkins once, updated sign-off so we'll see if it passes again.

**Comment by dachary** [comment]
@dzafman do you want me to run into a loop to verify it always works ?

**Comment by dzafman** [comment]
@dachary It seemed to reproduce every time on Jenkins and never on my build machine.  So I don't think it is necessary, but go ahead if you prefer.

**Pull request merged**
