### PR TITLE
seastar: update seastar submodule

### PR DESCRIPTION
**Pull request by tchaikov**
to pick up recent fixes in file io

Signed-off-by: Kefu Chai <kchai@redhat.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by tchaikov** [comment]
api test failed due to
```
+ timeout 2h ./src/script/run-make.sh --cmake-args '-DWITH_TESTS=OFF -DENABLE_GIT_VERSION=OFF'
E: dpkg was interrupted, you must manually run 'sudo dpkg --configure -a' to correct the problem. 
```

just fixed as instructed manually.

**Comment by tchaikov** [comment]
jenkins test docs

**Comment by tchaikov** [comment]
jenkins test api

**Review by athanatos — APPROVED** [review]

**Comment by tchaikov** [comment]
run-tox-mgr-dashboard  test failure tracked by https://tracker.ceph.com/issues/48506.

**Pull request merged**
