### PR TITLE
mimic: mds: crash when dumping ops in flight

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/26982

### CODE REVIEW

**Comment by ukernel** [comment]
MFoo:const_ref  does not exists. Need to use boost::intrusive_ptr<MFoo>. See https://github.com/ceph/ceph/pull/23677

**Comment by smithfarm** [comment]
@ukernel Thanks!

Closing in favor of https://github.com/ceph/ceph/pull/23677

**Comment by smithfarm** [comment]
I see now that #23677 is targeting luminous. I will update this PR (targeting mimic) to use boost::intrusive_ptr as suggested by @ukernel, using #23677 as a model.

**Comment by smithfarm** [comment]
```
/home/jenkins-build/build/workspace/ceph-pull-requests/src/mds/Mutation.cc:330:6: error: prototype for 'void MDRequestImpl::reset_slave_request(MMDSSlaveRequest*)' does not match any in class 'MDRequestImpl'
 void MDRequestImpl::reset_slave_request(MMDSSlaveRequest *req)
      ^~~~~~~~~~~~~
In file included from /home/jenkins-build/build/workspace/ceph-pull-requests/src/mds/Mutation.cc:15:0:
/home/jenkins-build/build/workspace/ceph-pull-requests/src/mds/Mutation.h:351:8: error: candidate is: void MDRequestImpl::reset_slave_request(const MMDSSlaveRequest*)
   void reset_slave_request(const MMDSSlaveRequest *req=nullptr);
        ^~~~~~~~~~~~~~~~~~~
src/mds/CMakeFiles/mds.dir/build.make:254: recipe for target 'src/mds/CMakeFiles/mds.dir/Mutation.cc.o' failed
```

**Comment by smithfarm** [comment]
@batrick @ukernel Please re-review (and thanks again to @ukernel for guidance)

**Comment by smithfarm** [comment]
@batrick Thanks for the LGTM, can you also approve?

**Comment by yuriw** [comment]
[wip-yuri5-testing-2018-09-05-1625-mimic](https://trello.com/c/xwoIGoxK/390-wip-yuri5-testing-2018-09-05-1625-mimic)

**Comment by yuriw** [comment]
[wip-yuri5-testing-2018-09-11-2103-mimic](https://trello.com/c/WPo5t2WP/397-wip-yuri5-testing-2018-09-11-2103-mimic)

**Pull request merged**
