### PR TITLE
librbd: remove invalid object map flag when object map is disabled

### PR DESCRIPTION
**Pull request by xinxinsh**
Fixes: #16706
Signed-off-by: xinxin shu <shuxinxin@chinac.com>

### CODE REVIEW

**Comment by dillaman** [comment]
lgtm

**Comment by dillaman** [comment]
Minor: can you change your commit message's "Fixes" line to be the URL to the tracker ticket instead of the number?

**Comment by dillaman** [comment]
... also, the tracker ticket is #16076

**Comment by xinxinsh** [comment]
@dillaman updated

**Pull request merged**
