### PR TITLE
rgw: TempAUTH implementation of Swift API does support implicit tenancy now

### PR DESCRIPTION
**Pull request by rzarzynski**

### CODE REVIEW

**Comment by mattbenjamin** [comment]
@rzarzynski is this dead?

**Comment by tchaikov** [comment]
@rzarzynski ping?

**Comment by cbodley** [comment]
@mdw-at-linuxbox can you tell how this interacts with your implicit tenant changes that merged recently in https://github.com/ceph/ceph/pull/28813?

**Comment by cbodley** [comment]
marked DNM, needs a rebase, and hasn't had any movement. feel free to rebase and reopen

**Pull request closed without merging**
