### PR TITLE
pybind/mgr/rbd_support: use image ids to detect duplicate tasks

### PR DESCRIPTION
**Pull request by dillaman**
This helps to to avoid the case where new tasks were not being scheduled
when an image name was re-used after having a task created under the
same name.

Fixes: https://tracker.ceph.com/issues/41032
Signed-off-by: Jason Dillaman <dillaman@redhat.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test docs`
- `jenkins render docs`

</details>

### CODE REVIEW

**Comment by tchaikov** [comment]
retest this please.

**Comment by tchaikov** [comment]
retest this please.

**Comment by trociny** [comment]
@dillaman It started to fail in teouthology when a ceph command is resent [1]:
```
2019-08-05T19:28:34.282 INFO:tasks.workunit.client.0.smithi135.stderr:++ ceph rbd task add flatten rbd_tasks/ns1/74287fdf-185e-48a7-8b58-52eb54c1a327
2019-08-05T19:28:34.282 INFO:tasks.workunit.client.0.smithi135.stderr:++ jq --raw-output .id
2019-08-05T19:28:34.676 INFO:tasks.ceph.mgr.x.smithi135.stderr:2019-08-05T19:28:34.678+0000 7fb336161700 -1 mgr.server reply reply (2) No such file or directory [errno 2] RBD image not found (Image rbd_tasks/ns1/74287fdf-185e-48a7-8b58-52eb54c1a327 does not have a parent)
2019-08-05T19:28:34.683 INFO:tasks.workunit.client.0.smithi135.stderr:Second attempt of previously successful command failed with ENOENT: [errno 2] RBD image not found (Image rbd_tasks/ns1/74287fdf-185e-48a7-8b58-52eb54c1a327 does not have a parent)
2019-08-05T19:28:34.684 INFO:tasks.workunit.client.0.smithi135.stderr:[errno 2] RBD image not found (Image rbd_tasks/ns1/74287fdf-185e-48a7-8b58-52eb54c1a327 does not have a parent)
```
[1] http://pulpito.ceph.com/trociny-2019-08-05_19:09:47-rbd-wip-mgolub-testing-distro-basic-smithi/

**Comment by dillaman** [comment]
@trociny Sorry about that -- the `queue_flatten` method wasn't using the pre-built `refs` dict when adding the task, so it was missing the image id.

**Pull request merged**
