### PR TITLE
qa/tasks/cephfs/mount: switch to StringIO to fix TypeErrors

### PR DESCRIPTION
**Pull request by lxbsz**
Signed-off-by: Xiubo Li <xiubli@redhat.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by lxbsz** [comment]
The build succeed: https://shaman.ceph.com/builds/ceph/vstart_runner/

**Comment by lxbsz** [comment]
Need the qa test under Py3 and David is trying to reboot the teuthology node.

**Comment by bk201** [comment]
jenkins test dashboard backend

**Comment by alfonsomthd** [comment]
jenkins test dashboard backend

**Comment by callithea** [comment]
- [pkg build](https://shaman.ceph.com/builds/ceph/wip-laura-testing-34680-34685/519eb48f4250ccb1940bf55b14fa290f240071e8/)
- rados/dashboard [QA run](http://pulpito.ceph.com/laura-2020-04-23_12:52:47-rados:dashboard-wip-laura-testing-34680-34685-distro-basic-smithi/) [WIP]

**Comment by lxbsz** [comment]
> * [pkg build](https://shaman.ceph.com/builds/ceph/wip-laura-testing-34680-34685/519eb48f4250ccb1940bf55b14fa290f240071e8/)
> * `rados/dashboard` [QA run](http://pulpito.ceph.com/laura-2020-04-23_12:52:47-rados:dashboard-wip-laura-testing-34680-34685-distro-basic-smithi/) [9/9 passed]
> 
> Edit: please let me know if I should run this PR with any other additional suite, since I'm just testing this changes along with the other two mentioned PRs and the suite is not sufficient for this PR.

I have run the fs basic test suite http://pulpito.ceph.com/xiubli-2020-04-23_23:39:53-fs:basic_functional-wip-fs-misc-2020-04-24-0625-distro-basic-smithi/.

All test cases relating to this PR are passed. And 2/60 failures are another chmod permission issue.

**Comment by lxbsz** [comment]
A small fix by adding another BytesIO() --> StringIO() changing. And the integration test please see https://github.com/ceph/ceph/pull/34685#issuecomment-618743494.

**Pull request merged**
