### PR TITLE
nautilus: tests: cephfs: fix malformed qa suite config

### PR DESCRIPTION
**Pull request by smithfarm**
backport tracker: https://tracker.ceph.com/issues/41276

---

backport of https://github.com/ceph/ceph/pull/29431
parent tracker: https://tracker.ceph.com/issues/41031

this backport was staged using https://github.com/ceph/ceph/blob/master/src/script/ceph-backport.sh

### CODE REVIEW

**Comment by smithfarm** [comment]
jenkins test make check

**Comment by yuriw** [comment]
[wip-yuri6-testing-2019-10-01-1605-nautilus](https://trello.com/c/5DZ906lA/701-wip-yuri6-testing-2019-10-01-1605-nautilus)

**Comment by smithfarm** [comment]
Did not pass "make check" yet - DNM!

**Comment by smithfarm** [comment]
jenkins test make check

**Pull request merged**
