### PR TITLE
s3select: update s3select submodule

### PR DESCRIPTION
**Pull request by galsalomon66**
Signed-off-by: gal salomon <gal.salomon@gmail.com>

## Checklist
- [ ] References tracker ticket
- [x] Updates documentation if necessary
- [x] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by galsalomon66** [comment]
jenkins test make check

**Comment by galsalomon66** [comment]
jenkins test signed

**Comment by galsalomon66** [comment]
jenkins test signed

**Comment by galsalomon66** [comment]
jenkins test signed

**Comment by galsalomon66** [comment]
jenkins test signed

**Comment by cbodley** [comment]
@galsalomon66 can you please revert the commit from https://github.com/ceph/ceph/pull/35910 as part of this pull request? then we can test the two together

**Comment by cbodley** [comment]
you can also add `Fixes: https://tracker.ceph.com/issues/46257` to the commit message for the submodule change

**Pull request closed without merging**
