### PR TITLE
osd: Fix Memory leak: final_extent

### PR DESCRIPTION
**Pull request by joscollin**
Signed-off-by: Jos Collin <jcollin@redhat.com>

### CODE REVIEW

**Comment by joscollin** [comment]
retest this please

**Comment by joscollin** [comment]
retest this please

**Comment by joscollin** [comment]
retest this please

**Comment by badone** [comment]
@joscollin Could you either resolve this or close it please mate?

**Comment by badone** [comment]
I'll pick this up in another PR

**Comment by badone** [comment]
Turns out the original code does not leak.

**Pull request closed without merging**
