### PR TITLE
rgw: remove bucket API returns NoSuchKey than NoSuchBucket

### PR DESCRIPTION
**Pull request by satoru-takeuchi**
Remove bucket API returns NoSuchKey but NoSuchBucket is appropriate in this case.

Code path:
RGWRadosStore::get_bucket  # returns -ENOENT as is. Should convert this to -ERR_NO_SUCH_BUCKET
-> RGWRadosBucket::get_bucket_info
-> RGWBucketCtl::read_bucket_info
-> RGWBucketCtl::read_bucket_entrypoint_info
-> RGWSI_Bucket_SObj::read_bucket_entrypoint_info
-> RGWSI_MetaBackend_SObj::get_entry
-> rgw_get_system_obj
-> RGWSI_SysObj::Obj::ROp::stat
-> RGWSI_SysObj_Core::stat # return -ENOENT here.

[1]: https://docs.ceph.com/en/pacific/radosgw/adminops/#remove-bucket

Fixes: https://tracker.ceph.com/issues/53731

Signed-off-by: Satoru Takeuchi <satoru.takeuchi@gmail.com>

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Review by leseb — APPROVED** [review]
Thanks for addressing this, I encountered this while testing in go-ceph https://github.com/ceph/go-ceph/blob/0e3ed2982fed0628efab22238ad91e7be9b39dd9/rgw/admin/bucket_test.go#L54-L55 and found it very confusing.

**Comment by cbodley** [comment]
i think this change is too far down the call stack, so effects a lot of other operations that already handle NO_SUCH_BUCKET correctly. please just modify the error path in `RGWOp_Bucket_Remove::execute()` after it calls `store->get_bucket()`

**Comment by satoru-takeuchi** [comment]
Test passed. Could someone merge this?

**Review by cbodley — APPROVED** [review]

**Comment by satoru-takeuchi** [comment]
@cbodley 

> please just modify the error path in RGWOp_Bucket_Remove::execute() after it calls store->get_bucket()

I was concerned that this fix might be wrong. Both `read_bucket_entrypoint_info()` and `read_bucket_instance_info()` may return -ENOENT. It's OK to convert -ENOENT to -ERR_NO_SUCH_BUCKET in the former case but I doubt that it might be inappropriate in the latter case. In other words, shouldn't we distinguish the missing bucket entry point and the missing bucket instance info?

**Comment by cbodley** [comment]
hi @satoru-takeuchi

if a bucket exists, we'd expect both the entrypoint and the instance to exist. RGWOp_Bucket_Remove shouldn't do anything special here, it should behave the same way other s3/swift ops do - they just translate ENOENT errors from store->get_bucket() into ERR_NO_SUCH_BUCKET

**Comment by satoru-takeuchi** [comment]
@cbodley Thank you!

**Comment by cbodley** [comment]
passed qa in https://pulpito.ceph.com/cbodley-2022-01-18_13:20:34-rgw-wip-cbodley-testing-distro-default-smithi/ with rerun https://pulpito.ceph.com/cbodley-2022-01-18_16:36:14-rgw-master-distro-default-smithi/

**Pull request merged**
