### PR TITLE
luminous: config: drop config::lock when invoking config observer

### PR DESCRIPTION
**Pull request by vshankar**
http://tracker.ceph.com/issues/37762

### CODE REVIEW

**Comment by batrick** [comment]
retest this please

**Comment by yuriw** [comment]
[wip-yuri2-testing-2019-01-08-1817-luminous](https://trello.com/c/hxKrCdTL/503-wip-yuri2-testing-2019-01-08-1817-luminous)

**Comment by batrick** [comment]
I'd like @liewegas to sign off on this backport since it required a lot of changes from what's in master.

**Comment by yuriw** [comment]
@liewegas leaving this for you to merge

**Comment by yuriw** [comment]
[wip-yuri2-testing-2019-01-15-1617-luminous](https://trello.com/c/qiqhsb6d/511-wip-yuri2-testing-2019-01-15-1617-luminous)

**Pull request merged**
