### PR TITLE
cmake: add dpdk::dpdk if dpdk is built or found

### PR DESCRIPTION
**Pull request by tchaikov**
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by tchaikov** [comment]
adding "bug fix" label, because cmake fails to configure if `WITH_SEASTAR` is enabled and user has libdpdk-dev installed.

**Comment by tchaikov** [comment]
@liu-chunmei could you help test this change?

**Comment by liu-chunmei** [comment]
still has error:
CMake Error at cmake/modules/BuildDPDK.cmake:42 (target_compile_options):
  Cannot specify compile options for imported target "dpdk::cflags".
Call Stack (most recent call first):
  cmake/modules/BuildDPDK.cmake:98 (do_build_dpdk)
  cmake/modules/BuildSPDK.cmake:4 (build_dpdk)
  CMakeLists.txt:255 (build_spdk)


CMake Error at cmake/modules/BuildDPDK.cmake:122 (target_link_libraries):
  Cannot specify link libraries for target "dpdk::dpdk" which is not built by
  this project.
Call Stack (most recent call first):
  cmake/modules/BuildSPDK.cmake:4 (build_dpdk)
  CMakeLists.txt:255 (build_spdk)


-- Configuring incomplete, errors occurred!

**Comment by tchaikov** [comment]
@liu-chunmei it's fixed in the latest change.

**Comment by smithfarm** [comment]
@tchaikov Triggering a build of this PR in OBS now...

**Comment by smithfarm** [comment]
jenkins re-test this please (unrelated run-rbd-unit-tests.sh failure)

**Comment by liu-chunmei** [comment]
@tchaikov -DWITH_SEASTAR=ON build works, but -DWITH_DPDK=ON has build error. 
In file included from /home/chunmei/ceph-seastar/ceph/src/msg/async/dpdk/DPDKStack.h:24:0,
                 from /home/chunmei/ceph-seastar/ceph/src/msg/async/Stack.cc:27:
/home/chunmei/ceph-seastar/ceph/src/msg/async/dpdk/dpdk_rte.h:27:10: fatal error: rte_config.h: No such file or directory
 #include <rte_config.h>
          ^~~~~~~~~~~~~~
compilation terminated.

**Comment by liu-chunmei** [comment]
@tchaikov  -DWITH_SEASTAR=ON build success, but unittest_seastar_echo  failed. as follows:
ceph/src/seastar/src/core/reactor.cc:542: seastar::reactor::reactor(unsigned int): Assertion `r >= 0' failed.
Aborting on shard 64.
Backtrace:
  0x00000000005f4cca
  0x0000000000582258
  0x0000000000582313
  0x00000000005823e5
  /lib/x86_64-linux-gnu/libpthread.so.0+0x000000000001138f
  /lib/x86_64-linux-gnu/libc.so.6+0x0000000000035427
  /lib/x86_64-linux-gnu/libc.so.6+0x0000000000037029
  /lib/x86_64-linux-gnu/libc.so.6+0x000000000002dbd6
  /lib/x86_64-linux-gnu/libc.so.6+0x000000000002dc81
  0x00000000005ebc4f
  0x00000000005ebd7d
  0x00000000005ebfa2
  0x000000000057acbd
  /lib/x86_64-linux-gnu/libpthread.so.0+0x00000000000076b9
  /lib/x86_64-linux-gnu/libc.so.6+0x000000000010741c

**Comment by tchaikov** [comment]
yeah, that’s a know issue. i will fix it in a follow-up PR.
Le sam. 18 août 2018 à 03:12, Liu-Chunmei <notifications@github.com> a
écrit :

**Comment by tchaikov** [comment]
@liu-chunmei can we continue the discussion on unittest_seastar_echo on ceph–devel? i want to learn more about it. thanks!

**Comment by tchaikov** [comment]
https://shaman.ceph.com/builds/ceph/wip-kefu-testing-2018-08-17-2127/22b5c586465691d0e918d8ca84374c5296838687/

**Comment by tchaikov** [comment]
https://shaman.ceph.com/builds/ceph/wip-kefu-testing-2018-08-17-2127/22b5c586465691d0e918d8ca84374c5296838687/

as `-DWITH_DPDK=ON` failure is not a regression introduced by this change, and this option is not enabled by default. i am merging as it is.

**Comment by tchaikov** [comment]
@liu-chunmei for `-DWITH_DPDK=ON`, see #23650 . but i don't think the dpdk backend is being maintained anymore.

**Pull request merged**
