### PR TITLE
mds: miscellaneous multimds fixes

### PR DESCRIPTION
**Pull request by ukernel**

### CODE REVIEW

**Comment by jcsp** [comment]
Looks like there are a couple of new commits here, so will re-test.

**Comment by jcsp** [comment]
@ukernel please can you put any followups in a separate PR so that I can get this one tested and merged

**Comment by ukernel** [comment]
which commits are not tested, I can remove them

**Comment by jcsp** [comment]
It's the last three commits

**Comment by ukernel** [comment]
new commits removed

**Pull request merged**
