### PR TITLE
 nautilus: mgr/dashboard: Manager modules and Alerts menu E2E breadcrumb tests

### PR DESCRIPTION
**Pull request by s0nea**
http://tracker.ceph.com/issues/38870

### CODE REVIEW

**Comment by callithea** [comment]
jenkins test dashboard

**Comment by tchaikov** [comment]
jenkins test dashboard

**Comment by tchaikov** [comment]
jenkins test dashboard

**Comment by tchaikov** [comment]
jenkins test dashboard

**Comment by tchaikov** [comment]
jenkins test dashboard

**Comment by tchaikov** [comment]
jenkins test dashboard

**Comment by tchaikov** [comment]
jenkins test dashboard

**Comment by tchaikov** [comment]
jenkins test dashboard

**Comment by tchaikov** [comment]
jenkins test dashboard

**Comment by tchaikov** [comment]
jenkins test dashboard

**Comment by nathan-weinberg** [comment]
LGTM

**Comment by yuriw** [comment]
[wip-yuri-testing-2019-04-15-1624-nautilus](https://trello.com/c/rlSGWgFv/593-wip-yuri-testing-2019-04-15-1624-nautilus)

**Pull request merged**
