### PR TITLE
move onode->exists = true into assign_node.

### PR DESCRIPTION
**Pull request by majianpeng**
a)avoid repeatedly set if object exist
b)remove code simple

### CODE REVIEW

**Comment by xiexingguo** [comment]
Is kstore still relevant...? Actually it is almost dead...

**Comment by majianpeng** [comment]
I'm not sure this. By search i found the same problem in  kstore.  So i modify BTW.

**Comment by tchaikov** [comment]
@majianpeng did you close this PR by accident?

**Comment by majianpeng** [comment]
@tchaikov . Yes, i'll recreate a PR ASAP.

**Comment by tchaikov** [comment]
thanks!

**Pull request closed without merging**
