### PR TITLE
pacific: pybind/mgr/volumes: deadlock on async job hangs finisher thread

### PR DESCRIPTION
**Pull request by batrick**
https://tracker.ceph.com/issues/50127

### CODE REVIEW

**Comment by batrick** [comment]
https://tracker.ceph.com/projects/cephfs/wiki/Pacific#2021-Apr-07-Integration-Branch

`Reviewed-by: Patrick Donnelly <pdonnell@redhat.com>`

**Review by yuriw — APPROVED** [review]
Reviewed-by: Patrick Donnelly <pdonnell@redhat.com>

**Comment by yuriw** [comment]
test this please

**Comment by yuriw** [comment]
test this please

**Comment by neha-ojha** [comment]
jenkins test make check

**Comment by yuriw** [comment]
jenkins test make check

**Comment by yuriw** [comment]
From IRC chat:
(10:34:04 AM) batrick: yuriw: it's a genuine tox error: https://github.com/ceph/ceph/pull/40630#issuecomment-816137349
(10:34:08 AM) batrick: but i don't know how to fix it
(10:34:18 AM) batrick: from my googling it appears mypy or whatever is broken

This PR passed tests  an can be merged after it passes `make check`

**Comment by tchaikov** [comment]
> @tchaikov do you see how to resolve this properly?
> 
> ```
> mgr_util.py: note: In function "lock_timeout_log":
> mgr_util.py:92: error: Yield value expected
> ```

@batrick might want to backport #40579. i took the liberty and backported on behalf of you.

**Comment by batrick** [comment]
@tchaikov oh I missed you followup fix; thanks!

**Comment by batrick** [comment]
jenkins test docs

**Comment by batrick** [comment]
jenkins test api

**Comment by batrick** [comment]
jenkins test api

**Comment by batrick** [comment]
jenkins test api

**Pull request merged**
