### PR TITLE
mon/OSDMonitor.cc: Add current numbers of objects and bytes

### PR DESCRIPTION
**Pull request by shinobu-x**
The purpose of this PR is that sysadmins know current numbers of objects
and bytes when they run `osd pool get-quota`.

Signed-off-by: Shinobu Kinjo <shinobu@redhat.com>

### CODE REVIEW

**Comment by liewegas** [comment]
Can you include the same information in the structured json dump too?

**Comment by shinobu-x** [comment]
@liewegas Please check when you get a chance.

**Comment by gregsfortytwo** [comment]
This looks fine but needs a simple rebase if anybody can do that.

**Comment by jecluis** [comment]
fixed the conflicts, will pull this into my testing branch

**Comment by neha-ojha** [comment]
retest this please

**Pull request merged**
