### PR TITLE
mon/LogMonitor: proposed fix for bug #14366 , lock update_log_channel().

### PR DESCRIPTION
**Pull request by sahithi-rv**
Signed-off-by: Sahithi R V <sahithi.rv1@gmail.com>

### CODE REVIEW

**Comment by sahithi-rv** [comment]
The main idea was to add mutual exclusion to shared variables( channels.log* maps). 
These changes make execution of the functions common/str_map: get_conf_str_map_helper() and mon/LogMonitor: channels.expand_channel_meta() sequential. 
This patch did not pass some tests. How do I fix that and make it better?

**Comment by sahithi-rv** [comment]
Let me share my idea.
1) I was using a lock per map so that the execution of this function would not be sequential.
2) I used trylock instead of lock, because I do not want a thread to wait for a lock to be released(spin) rather the thread should execute the next if statement.(hoping that this will lead to more concurrency)
3)I called the unlock function within the trylock so that only the one holding the lock can release it.

**Comment by branch-predictor** [comment]
@sahithi-rv Ok, so you need one mutex in LogMonitor class and use it to Lock and Unlock before and after each section. Why you don't want it proceed sequentially?
You should use Lock() or switch from Mutexes to spinlocks. TryLock() is used in code that wants to do something else (presumably something useful) while waiting for lock to be released instead of waiting.

**Comment by jecluis** [comment]
I haven't thought about this in depth yet, but off the top of my head I would agree would @branch-predictor.

I'm guessing you'd only need a single Mutex in LogMonitor (say, `Mutex conf_lock`), and then having a `Mutex::Locker l(conf_lock);` first thing in `LogMonitor::handle_conf_change()`. That ought to avoid a concurrent threads doing conflicting stuff in `LogMonitor::handle_conf_change()` by serializing all conf updates on the LogMonitor itself.

**Comment by jecluis** [comment]
Oh, in case you're not familiar with how `Mutex::Locker` works, it basically grabs a reference on the mutex on instanciation and will release it at end of scope. This means you don't need either an explicit `Lock()` nor an explicit `Unlock()`.

**Pull request closed without merging**
