### PR TITLE
ceph.spec.in: SUSE/openSUSE builds need libbz2-devel

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/11629 Fixes: #11629

Signed-off-by: Nathan Cutler <ncutler@suse.cz>

### CODE REVIEW

**Comment by ktdreyer** [comment]
LGTM. I always wondered why we conditionalized that bit for non-SUSE. Now I understand - it's because the bzip2 package name is different.

**Comment by ktdreyer** [comment]
Looking a bit closer at this... what do you think about just un-inverting the conditional here?

Like change `%if ! 0%{defined suse_version}` to `%if 0%{defined suse_version} ...`

I think that's going to make the code clearer now that we *do* have something for SUSE.

**Comment by smithfarm** [comment]
Agreed and done.

**Comment by ktdreyer** [comment]
Cool, thank you! merging

**Pull request merged**
