### PR TITLE
hammer: librbd: possible QEMU deadlock after creating image snapshots

### PR DESCRIPTION
**Pull request by dillaman**
http://tracker.ceph.com/issues/15033

### CODE REVIEW

**Comment by dachary** [comment]
@dillaman is the double *cherry-pick -x on  	621e3ae* intentional ?

**Comment by dillaman** [comment]
@dachary Just guessing since this was a month ago, but I'd think was cherry-picked from the infernalis branch just so that it applied cleanly (thus it picked up the chain).

**Comment by dachary** [comment]
@dillaman that's fine :-)

**Comment by dachary** [comment]
Passed http://tracker.ceph.com/issues/14692#note-49

**Pull request merged**
