### PR TITLE
Adding build requires

### PR DESCRIPTION
**Pull request by ErwanAliasr1**
This PR is about adding two build requires issue I faced while building inside a FC23 chroot.

Cheers,

### CODE REVIEW

**Comment by liewegas** [comment]
What was btrfs-progs needed for?

**Comment by wjwithagen** [comment]
@liewegas @ErwanAliasr1 btrfs tests are used in the teardown routines of several scripts including vstart.sh but if btrfs is not there, these scripts will fail miserably.
In my wip I've made them dependant on `uname` = FreeBSD, mainly because stat does not have the requested fields. But perhaps a better test (or extra) would be `which btrfs > /dev/null 2>&1` which does not depend on OS or distro.

Unless running btrfs on these ditros is a wanted testing issue, but then I'd expect btrfs to be setup accordingly. And before install-deps is executed.

**Comment by ErwanAliasr1** [comment]
Just added the missing sign off

**Comment by ErwanAliasr1** [comment]
Updated commit message to include the /usr/lib/rpm/redhat/redhat-hardened-cc1 trace.
That will make the commit more explicit.

Rebasing btw.

**Comment by liewegas** [comment]
@branto1 does teh redhat-rpm-config change make sense?

**Comment by branto1** [comment]
The `redhat-rpm-config` is a dependency of `rpm-build` package that actually builds the rpms (at least on f23 and rhel-7). I'm not sure how @ErwanAliasr1 managed to hit that error while building the package from src.rpm but that really should not happen.

As for the `redhat-hardened-cc1` binary, that comes from the `_hardened_build` macro which should be on by default in f23 [1]. The macro itself is part of the `redhat-rpm-config` package so that makes it even more weird an issue.

Adding the package itself as the build depedency won't break anything on redhat distros (but it might on SUSE distros -- @smithfarm ?) but I really don't see a scenario where that package wouldn't be installed and the packages were being built.

[1] https://bugzilla.redhat.com/show_bug.cgi?id=1192183

**Comment by ErwanAliasr1** [comment]
@branto1 I hit this issue with a manual build, not by building the spec file. A simple configure + make.

But as we do use the spec file to install the build deps during the dev. cycle, the spec file have to be up to date.

I rebased & repushed with the required changes.

**Comment by branto1** [comment]
@ErwanAliasr1: Hmm, ok, manual build. I suppose that could probably make it hittable. LGTM, then.

**Comment by ErwanAliasr1** [comment]
@branto1 To be more precise : ./configure --with-librocksdb-static --with-debug --with-radosgw

**Comment by smithfarm** [comment]
AFAICT these are "make check" dependencies, so they are needed only if tests are run as part of the build. So we should put another conditional around them: `%if %{with tests}`

**Comment by ErwanAliasr1** [comment]
@smithfarm Very true. Fixed on the spec file, rebased & pushed.

I don't see anything similar on the debian packaging.

**Comment by ErwanAliasr1** [comment]
Just updated and I didn't took the suse case .... Their package name is pretty weird "btrfsprogs" (with no dash). 

Added the suse case inside the test case you asked me.

Enjoy,

**Comment by ErwanAliasr1** [comment]
@smithfarm Updated the file spec as you suggested.

At some point I would propose having a %if <distro> with all the buildrequires instead of having the a specific %if for each sub package like cython, lttng, boost etc... That's make the spec very verbose at my taste.

Anyway, done & rebased.

**Comment by ErwanAliasr1** [comment]
@smithfarm Ok ... let's hope this version is better ... this section isn't that simple to read :(

**Comment by ErwanAliasr1** [comment]
Rebased against latest modifications of the spec file

**Comment by ErwanAliasr1** [comment]
Little ping to @liewegas and @ldachary not to forget that one ;)

**Comment by ErwanAliasr1** [comment]
@smithfarm Done.

**Comment by smithfarm** [comment]
@ErwanAliasr1 After you fix that last little nit, I will push the branch to the gitbuilders.

**Comment by ErwanAliasr1** [comment]
@smithfarm I pushed with all the fixes you requested. Should be good.

**Comment by smithfarm** [comment]
Pushed to gitbuilders as `wip-evelu-spec` . . . you can follow on http://ceph.com/gitbuilder.cgi

**Comment by ErwanAliasr1** [comment]
@smithfarm I'm not sure to understand the output I get on this url.

**Comment by smithfarm** [comment]
@ErwanAliasr1 Yellow background means it passed, red means it failed. This one passed all the gitbuilders except the broken ones :-)

@ktdreyer This one looks good to me.

`Reviewed-by: Nathan Cutler <ncutler@suse.com>`

**Comment by ktdreyer** [comment]
Thanks LGTM

**Comment by ErwanAliasr1** [comment]
Thx for the merge.

**Comment by ErwanAliasr1** [comment]
@smithfarm This statement "So we should put another conditional around them: %if %{with tests}" triggers a side effect I didn't analyze before the merge.

The buildrequires is inside the with_tests and as we are using a  "%bcond_with tests", yum-builddep doesn't see it. As a result, install-deps.sh doesn't install btrfs-progs :(

I have a workaround on that by injecting a temporary "%global with_tests 1" in the spec file before calling yum-builddep.

@ldachary is more on the line to remove the conditional if around that buildrequires.

What's your opinion guys ?

**Comment by smithfarm** [comment]
@ErwanAliasr1 I agree with @dachary - let's remove the `%if %{with tests}` conditional around the btrfs buildrequires. 

I opened http://tracker.ceph.com/issues/15042 to track this issue. @ErwanAliasr1 Please open a PR and include a line that says "Fixes: #15042" in the commit message.

**Comment by ErwanAliasr1** [comment]
@smithfarm done by https://github.com/ceph/ceph/pull/8016

**Pull request merged**
