### PR TITLE
qa/tasks/mds_thrash: s/random.sample/random.choice/

### PR DESCRIPTION
**Pull request by tchaikov**
in python3, range() returns an instance of `range` which cannot be
accumulated using `+` operator. so, in this change, a list comprehension
is used instead. also, `random.sample()` is replaced with
`random.choice()`. the latter is a better alternative, if the number of
samples is 1.

Signed-off-by: Kefu Chai <kchai@redhat.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by tchaikov** [comment]
the backport of this change should address the failure of http://pulpito.ceph.com/kchai-2020-05-21_08:08:39-fs-nautilus-distro-basic-smithi/5076101/

**Comment by batrick** [comment]
dup of #35109

**Comment by tchaikov** [comment]
@batrick thanks, i completely forgot #35109 when working on this fix. can we include it as a refactory instead?

**Comment by batrick** [comment]
sure!

**Pull request merged**
