### PR TITLE
hammer: rgw: backport rgwx-copy-if-newer for radosgw-agent

### PR DESCRIPTION
**Pull request by cbodley**
Fixes: http://tracker.ceph.com/issues/16262

### CODE REVIEW

**Comment by oritwas** [comment]
lgtm
@cbodley, did it pass a teuthology run?

**Comment by cbodley** [comment]
> @cbodley, did it pass a teuthology run?

oops, missed this comment. it hasn't been through teuthology. which suite should i run?

**Comment by smithfarm** [comment]
This PR was included in the last round of hammer integration testing. The RGW suite was run and the following 4 failures are reproducible: http://pulpito.ceph.com/smithfarm-2016-07-08_12:39:54-rgw-hammer-backports---basic-smithi/

All of the failures are http://tracker.ceph.com/issues/16638

**Comment by smithfarm** [comment]
I would appreciate help debugging/fixing that one.

**Comment by oritwas** [comment]
@smithfarm, this seems to be a build issue.
valgrind complains on tcmalloc but this run is notcmalloc 
see also http://tracker.ceph.com/issues/15117

**Comment by smithfarm** [comment]
@oritwas This PR passed an rgw suite with some valgrind-related failures that appear harmless - see http://tracker.ceph.com/issues/15895#note-19 

Do you think this PR is ready to merge?

**Comment by smithfarm** [comment]
Ceph is not compiled against tcmalloc, but boost is - and that appears to be the source of the problem. So far the consensus seems to be that the valgrind warnings are spurious.

**Comment by oritwas** [comment]
lgtm

**Pull request merged**
