### PR TITLE
osd/OSD: bump up current version; conditionally encoding manifest into oi

### PR DESCRIPTION
**Pull request by xiexingguo**

### CODE REVIEW

**Comment by xiexingguo** [comment]
retest this please

**Comment by liewegas** [comment]
Maybe combine these into one commit?  Otherwise it's unclear what the change is for.

**Comment by liewegas** [comment]
otherwise lgtm!

**Comment by xiexingguo** [comment]
> Maybe combine these into one commit?

sure:-)

**Comment by liewegas** [comment]
http://pulpito.ceph.com/sage-2017-06-15_16:44:51-rados-wip-sage-testing-distro-basic-smithi/

**Pull request merged**
