### PR TITLE
doc: reorganize CephFS landing page and ToC

### PR DESCRIPTION
**Pull request by batrick**
## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by batrick** [comment]
jenkins render docs

**Comment by batrick** [comment]
jenkins render docs

**Comment by batrick** [comment]
jenkins render docs

**Comment by liewegas** [comment]
Just a note that https://docs.ceph.com/ceph-prs/32038/cephfs/add-remove-mds/#adding-an-mds is out of date.. (2) isn't needed and (4) should be ``ceph-mds@foo``

**Comment by batrick** [comment]
> Just a note that https://docs.ceph.com/ceph-prs/32038/cephfs/add-remove-mds/#adding-an-mds is out of date.. (2) isn't needed and (4) should be `ceph-mds@foo`

https://tracker.ceph.com/issues/43162

**Comment by batrick** [comment]
jenkins render docs

**Pull request merged**
