### PR TITLE
qa/rgw: hadoop-s3a suite targets centos_latest

### PR DESCRIPTION
**Pull request by cbodley**
instead of having two separate tasks, add v27.yaml and v28.yaml with overrides for hadoop_version

add symlink to centos_latest.yaml instead of setting os_type/os_version manually

### CODE REVIEW

**Comment by cbodley** [comment]
test pending: http://pulpito.ceph.com/cbodley-2017-09-18_13:31:33-rgw:hadoop-s3a-master-distro-basic-mira/

**Comment by vasukulkarni** [comment]
Makes sense +1, but you will have to pull commits from here as well for the tests to pass due to recent ansible changes https://github.com/ceph/ceph/pull/17757 , I think one of us will have to rebase changes on top or we could include all in on pr.

**Comment by yuriw** [comment]
@cbodley needs backport to jewel and luminous

**Comment by cbodley** [comment]
@yuriw this hadoop-s3a suite did not exist in jewel

**Comment by smithfarm** [comment]
luminous backport: https://github.com/ceph/ceph/pull/17816

**Pull request merged**
