### PR TITLE
octopus: New msgr2 crc and secure modes (msgr2.1)

### PR DESCRIPTION
**Pull request by idryomov**
Backport of #35078 and #35816 (changes from #34927 which got merged via #35078 already in octopus).

Two minor conflicts, documented inline.

### CODE REVIEW

**Comment by yuriw** [comment]
[wip-yuri-testing-2020-06-23-1929-octopus](https://trello.com/c/wFBenVww/944-wip-yuri-testing-2020-06-23-1929-octopus)

**Comment by yuriw** [comment]
[wip-yuri4-testing-2020-06-25-1924-octopus](https://trello.com/c/xv2oCiv0/947-wip-yuri4-testing-2020-06-25-1924-octopus)

**Comment by neha-ojha** [comment]
Marking DNM until https://tracker.ceph.com/issues/46180 is fixed.

**Comment by idryomov** [comment]
Pushed the fix for https://tracker.ceph.com/issues/46180 (#35816).

-s rados/singleton-nomsgr --filter 'all/health-warnings rados' -N 20 / 200:

https://pulpito.ceph.com/dis-2020-07-02_20:12:12-rados:singleton-nomsgr-wip-msgr21-octopus-distro-basic-smithi/
https://pulpito.ceph.com/dis-2020-07-02_21:12:10-rados:singleton-nomsgr-wip-msgr21-octopus-distro-basic-smithi/

**Comment by idryomov** [comment]
@neha-ojha @yuriw Taking DNM off.

**Comment by yuriw** [comment]
[wip-yuri7-testing-2020-07-06-1754-octopus](https://trello.com/c/VGUTyb8R/952-wip-yuri7-testing-2020-07-06-1754-octopus)

**Pull request merged**
