### PR TITLE
common/ipaddr: Allow binding on lo

### PR DESCRIPTION
**Pull request by thomasgoirand**
Commmit 5cf0fa872231f4eaf8ce6565a04ed675ba5b689b, solves the issue that
the osd can't restart after seting a virtual local loopback IP. However,
this commit also prevents a bgp-to-the-host over unumbered Ipv6
local-link is setup, where OSD typically are bound to the lo interface.

To solve this, this single char patch simply checks against "lo:" to
match only virtual interfaces instead of anything that starts with "lo".

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by tchaikov** [comment]
@thomasgoirand hi Thomas, looks great, just revised your commit message a little bit:

- add a "Fixes" line, so this change is connected with https://tracker.ceph.com/issues/48893
- add a "Signed-off-by" line, as required by https://github.com/ceph/ceph/blob/master/SubmittingPatches.rst#sign-your-work
- add a prefix in the title of the commit message, as required by https://github.com/ceph/ceph/blob/master/SubmittingPatches.rst#3-describe-your-changes

**Review by tchaikov — APPROVED** [review]

**Comment by tchaikov** [comment]
jenkins test api

**Comment by neha-ojha** [comment]
jenkins test api

**Comment by neha-ojha** [comment]
jenkins test api

**Comment by neha-ojha** [comment]
https://pulpito.ceph.com/yuriw-2021-01-15_19:06:33-rados-wip-yuri8-testing-master-2021-01-15-0935-distro-basic-smithi/ - no related failures

**Pull request merged**
