### PR TITLE
Wip writepath optimization work

### PR DESCRIPTION
**Pull request by somnathr**
Hi,
This the new pull request of write path optimization work after incorporating all the comments.

Thanks & Regards
Somnath

### CODE REVIEW

**Comment by joehandzik** [comment]
Hey @somnathr, @jcsp has messaged me a few times about an issue he's running into with the blkid calls too (http://tracker.ceph.com/issues/13512). Just lending our voices to the "create a separate PR" request from @liewegas, very much appreciate you getting your change out into the world while I work to just remove blkid entirely before drop-dead on Jewel. Honestly, it might be helpful to spin off multiple separate PRs by cherrypicking each individual commit into a separate branch.

**Comment by xinxinsh** [comment]
@somnathr , i tested this PR on my Full SSD setup, but if i enable filestore_odsync_write， filestore_do_fast_sync, filestore_do_force_sync and journal_dynamic_throttle, some osds are killed by out-of-memory error , it seems that new patch consume much more memory, FYI, i run 4-hosts cluster,    every host gets 64 GB memory, and runs 8 osd daemons

**Comment by somnathr** [comment]
@xinxinsh Do you have the following commit (First one in this PR)?
https://github.com/somnathr/ceph/commit/4aa4bf2d32d8977c9217f5f402252d377514834a

Without that , you will be hitting this if you don't restrict number of journal writes.

**Comment by xinxinsh** [comment]
@somnathr , yes,  i fetch all 5 commits to my local repository

**Comment by somnathr** [comment]
@xinxinsh hmm..How long you ran the tests ?
if you don't mind , could you please try with my following branch directly ?

https://github.com/somnathr/ceph/tree/wip-writepath-optimization-work

I specifically tested this behavior and found no memory pile up issues. I did 1 hour test.

BTW, did you see any performance improvement during the run ?

**Comment by xinxinsh** [comment]
@somnathr , thanks, i will have a try

**Comment by somnathr** [comment]
@xinxinsh Thanks, I should have mentioned in this PR as I mentioned in the original PR that we still need to control number of journal write with journal_max_write_entries. The delete patch is definitely helping to reduce memory piling up but if we make journal to unleash boundlessly , eventually memory may creep up.

**Comment by somnathr** [comment]
@liewegas You can close this, related pull requests for write path optimization are ..

https://github.com/ceph/ceph/pull/7271
https://github.com/ceph/ceph/pull/7303
https://github.com/ceph/ceph/pull/7278
https://github.com/ceph/ceph/pull/6743

**Pull request closed without merging**
