### PR TITLE
osd: adding 'reef' to pending_require_osd_release

### PR DESCRIPTION
**Pull request by PhilippHufnagl**
It appears adding 'reef' to pending_require_osd_release has been forgotten. This PR adds it

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Review by sseshasa — COMMENTED** [review]
@PhilippHufnagl The changes LGTM. If possible, can you please raise a Ceph tracker for this and associate it with this PR? Please link the tracker to the PR in the commit message at the bottom by adding the "Fixes: https://tracker.ceph.com/issues/####" line. This would help in backporting the fix to upstream Reef since that's where the fix is required and would be tested.

**Review by rzarzynski — APPROVED** [review]

**Comment by rzarzynski** [comment]
@PhilippHufnagl: thanks for bringing this! Would you mind creating a ticket on the tracker and putting the `Fixes` tag to the commit description? We'll want to backport the fix to the `reef` branch as well.

**Comment by PhilippHufnagl** [comment]
I currently can not open a Ticket because I do not have a Ceph bug tracker account. I created one which is now waiting for approval. Ill check back later

**Comment by PhilippHufnagl** [comment]
Hello

I added a bug now to the bug tracker Fixes https://tracker.ceph.com/issues/63779
I can't figure out how to edit the commit message. Is this possible in Github or do I have to rebase?

**Pull request closed without merging**
