### PR TITLE
rgw/admin: don't search all realms in try_to_resolve_local_entities()

### PR DESCRIPTION
**Pull request by cbodley**
we read the `RGWZoneParams`, so can use its `realm_id` to read its realm directly

cleanup related to https://github.com/ceph/ceph/pull/42122

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by cbodley** [comment]
jenkins test make check

**Comment by cbodley** [comment]
passed [qa](https://pulpito.ceph.com/cbodley-2022-08-24_22:54:44-rgw-wip-cbodley-testing-distro-default-smithi/) with [rerun](https://pulpito.ceph.com/cbodley-2022-08-25_13:25:55-rgw-wip-cbodley-testing-distro-default-smithi/)

**Comment by cbodley** [comment]
jenkins test make check

**Comment by cbodley** [comment]
jenkins test api

**Comment by yehudasa** [comment]
@cbodley can we be sure that the realm field is always updated / correct?

**Pull request closed without merging**
