### PR TITLE
jewel: doc: clarify status of jewel PendingReleaseNotes

### PR DESCRIPTION
**Pull request by smithfarm**
Status as of 10.2.8 release

Signed-off-by: Nathan Cutler <ncutler@suse.com>

### CODE REVIEW

**Comment by liewegas** [comment]
Any reason not to move these into release-notes.rst?

**Comment by liewegas** [comment]
oh i see, this is jewel branch.

**Comment by smithfarm** [comment]
@liewegas So, this PR is just so I can ask you if it's OK, in light of https://github.com/ceph/ceph/pull/16274, to completely wipe this file in Jewel. In other words I'd replace the current commit with one that zeroes out this file.

**Comment by liewegas** [comment]
yeah, kill it!

**Comment by smithfarm** [comment]
@liewegas I zeroed it by adding a second commit. The first one adds some clarifications which might be useful.

**Pull request merged**
