### PR TITLE
rgwlc: fix backoff retries counter

### PR DESCRIPTION
**Pull request by 5cs**
SimpleBackoff from c069eb7ff09b52003fa00a5cc83b1e52370032f5 has
`retries` counter which should be incremented before setting new
`sleep_ms`, otherwise we always have 0 `sleep_ms`.

Signed-off-by: Tongliang Deng <dengtongliang@gmail.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [x] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Review by dang — APPROVED** [review]

**Comment by cbodley** [comment]
jenkins test api

**Comment by cbodley** [comment]
jenkins test make check

**Comment by mattbenjamin** [comment]
the claim in the commit message that "we always have 0 sleep_ms" is not true, through.  We have it once, on the first iteration through the loop, do we not?

**Comment by 5cs** [comment]
> the claim in the commit message that "we always have 0 sleep_ms" is not true, though. We have it (edit) only once, on the first iteration through the loop, do we not?

In the first iteration, the value of `retries` is 0 when updating `sleep_ms = std::chrono::milliseconds(sleep_ms*2*retries)`, which result into `sleep_ms` collapsed to 0, finally sleep_ms is always 0 in the rest iterations.

>  I think I felt the first wait would be too long with the calling parameters I initially picked, and allowed the no-op call, iirc. It's only one no-op, so long as max_retries is provided > 1.

Yes, a no-op call is useful since the lock will be released very quickly in common cases. A fix reflecting this purpose can be
```c++
  std::this_thread::sleep_for(sleep_ms*retries);
  sleep_ms = std::chrono::milliseconds(sleep_ms*2);
  ++retries;
```

**Comment by mattbenjamin** [comment]
you're right, obviously. 
but maybe what I should have done is not stored the intermediate values of sleep_ms at all, e.g.:
std::this_thread::sleep_for(sleep_ms * 2 * retries++);

**Comment by 5cs** [comment]
> you're right, obviously. but maybe what I should have done is not stored the intermediate values of sleep_ms at all, e.g.: std::this_thread::sleep_for(sleep_ms * 2 * retries++); (i.e., without the other lines)

@mattbenjamin PTAL

**Comment by ivancich** [comment]
QA run -- no regressions:
- https://pulpito.ceph.com/ivancich-2022-07-16_18:44:05-rgw-wip-eric-testing-1-distro-default-smithi/
- https://pulpito.ceph.com/ivancich-2022-07-16_18:43:39-rgw-wip-eric-testing-1-distro-default-smithi/

**Pull request merged**
