### PR TITLE
common: /usr/lib64/ceph/libceph-common.so.0 isn't CET enabled

### PR DESCRIPTION
**Pull request by kalebskeithley**
see https://bugzilla.redhat.com/show_bug.cgi?id=1809799

https://tracker.ceph.com/issues/44403

Fedora 33/rawhide requires that all shlibs be CET enabled with
IBT and SHSTK where applicable.

common/crc32c_intel_fast_asm.s and common/crc32c_intel_fast_zero_asm.s
are apparently (or obviously) derived from [1] which has the necessary
changes; and which is the model for the changes to these two files.

Also updating yasm-wrapper to add the appropriate note.gnu.property NOTE
section as required.

Presumably the requirement to be CET enabled will apply to RHEL9 too
some day, when it becomes a thing. CET enablement seems to be driven by
Intel, so I am sure there will be pressure from other Linux distributions
to be CET enabled as well, although I haven't seen any evidence of it yet.

FWIW this change has been included as a patch in the f33/rawhide builds of
ceph-15.y.z since 20200309. (I.e. ceph-15.1.0)

[1] https://github.com/intel/isa-l/blob/master/crc/crc32_iscsi_00.asm

Signed-off-by: Kaleb S. KEITHLEY <kkeithle@redhat.com>

## Checklist
- [x] References tracker ticket
- [x] Updates documentation if necessary
- [x] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by tchaikov** [comment]
please create a tracker ticket for tracking the backport process of this change.

**Comment by kalebskeithley** [comment]
jenkins test dashboard backend

**Comment by kalebskeithley** [comment]
jenkins test dashboard backend

**Comment by kalebskeithley** [comment]
jenkins test make check

**Comment by kalebskeithley** [comment]
jenkins test dashboard backend

**Comment by kalebskeithley** [comment]
jenkins test dashboard backend

**Comment by kalebskeithley** [comment]
@tchaikov subject in the commit was updated

**Comment by kalebskeithley** [comment]
I have made the requested changes to the commit message (prefix changed to "common". The make build test and associated unit tests which cover change this have passed. Two runs of teuthology rados tests (500 tests) have mainly passed (480+ passes.)  What else needs to be done to merge this? @tchaikov I'd like to eventually stop carrying this patch in the fedora builds. Thanks

**Comment by tchaikov** [comment]
> I have made the requested changes to the commit message (prefix changed to "common".

not all requested changes was made, see

> the title of the commit message reads like a bug report. ideally, the title of the commit message should use the imperative mood. see also https://github.com/ceph/ceph/blob/master/SubmittingPatches.rst#3-describe-your-changes . please use `git commit --amend` and `git push -f` for revising the commit message and its title.
> 

> The make build test and associated unit tests which cover change this have passed. Two runs of teuthology rados tests (500 tests) have mainly passed (480+ passes.) 

could you paste the link to them?

> What else needs to be done to merge this? @tchaikov I'd like to eventually stop carrying this patch in the fedora builds. Thanks

i think you need to get an approval and make sure it's tested (links needed).

**Comment by kalebskeithley** [comment]
http://pulpito.front.sepia.ceph.com/kkeithle-2020-08-11_14:03:42-rados-wip-kkeithle-cet-distro-basic-smithi/

http://pulpito.front.sepia.ceph.com/kkeithle-2020-08-17_21:22:48-rados-wip-kkeithle-cet-distro-basic-smithi/

I changed the prefix to common. How about you just tell me what you want the title to be? I have no time for figuring out this kind of grammar imperative mood nonsense. This is not my $dayjob.

@tchaikov @mattbenjamin

**Comment by smithfarm** [comment]
@kalebskeithley Ah, imperative mood. In this case, you would change:

"common: /usr/lib64/ceph/libceph-common.so.0 isn't CET enabled"

to

"common: enable CET on /usr/lib64/ceph/libceph-common.so.0"

Make sense?

**Pull request closed without merging**
