### PR TITLE
mds: remove boost::pool usage and use tcmalloc directly

### PR DESCRIPTION
**Pull request by david-z**
Fixes: http://tracker.ceph.com/issues/18425

Signed-off-by: Zhi Zhang <zhangz.david@outlook.com>

### CODE REVIEW

**Comment by david-z** [comment]
@jcsp Could you pls take a look? Thanks.

**Comment by jcsp** [comment]
Can you talk about why this is useful and what performance differences you saw?

**Comment by jcsp** [comment]
Oh, never mind I see that there is an explanation in the tracker ticket

**Comment by jcsp** [comment]
Hmm, so I don't want to merge this without working out how it intersects with the possible switch to using mempools (src/common/mempool.cc) in the MDS (cc @liewegas)

**Comment by liewegas** [comment]
The switch to mempool will probably mean dropping boost::pool here anyway (unless we want to add special boost::pool support to the mempool infrastructure).  The only reason not to do that is concern about performance and memory utiliztion.  It wouldn't surprise me if tcmalloc does just as well on the performance side.  I would do some testing to make sure the overall memory footprint doesn't expand, though--that's the original problem we were trying to fix, and ~7 years ago or wahtever it was significant.  The allocator has probably come a long way since then, but we need to check.

**Comment by liewegas** [comment]
And assuming it's fine with tcmalloc, I would rip out boost::pool entirely.. don't bother with an #ifdef.

**Comment by david-z** [comment]
@LiuHongdong thanks for testing this change on different tcmalloc version. I only tested it on gperftools-2.1 before.

Currently I haven't figured out how this crash is related to tcmalloc or boost::pool. It looks more like a logic bug to me. Anyway, I will try to reproduce this crash by using gperftools-2.4.

BTW, can you give me more information?
1. Is this crash reproduced constantly with gperftools-2.4?
2. Which ceph version are you using?

**Comment by david-z** [comment]
@LiuHongdong This crash doesn't seem to be related with TCMALLOC. I think it might be the new version of TCMALLOC which has some new memory reclaim mechanism or similar stuff, that could expose this crash more easily and obviously.

The root cause is that in StrayManager::_purge_stray_logged, inode will delete itself firstly, 
`in->mdcache->remove_inode(in);`
then it tries to drop dentry via this deleted inode.  
`in->mdcache->touch_dentry_bottom(dn);`

I have create a new PR to track and fix this crash, pls check it here https://github.com/ceph/ceph/pull/13347

I also tested the new fix with some test cases and they are all passed.

1. boost::pool with TCMALLOC 4.2.6
2. only TCMALLOC 4.2.6
3. boost::pool with TCMALLOC 4.1.2
4. only TCMALLOC 4.1.2

**Comment by jcsp** [comment]
@david-z if you would still like to work on this, please could you rebase this code on master, and update it to simply remove the boost::pool usage instead of ifdeffing it.

**Comment by david-z** [comment]
@jcsp Sorry for the late reply. I will work on this, but let me test it on our real env more. I will update the change soon.

**Comment by david-z** [comment]
@jcsp Changes had been made and tests had been ran for few days on our real env. So far so good. Pls help to review the change.

BTW, I see the jenkins build failed but it is not related to this change. Could you pls help to check? Thanks.
```
/home/jenkins-build/build/workspace/ceph-pull-requests/src/test/osd/osd-scrub-repair.sh:2214: corrupt_scrub_erasure:  test no = yes
/home/jenkins-build/build/workspace/ceph-pull-requests/src/test/osd/osd-scrub-repair.sh:2214: corrupt_scrub_erasure:  return 1
/home/jenkins-build/build/workspace/ceph-pull-requests/src/test/osd/osd-scrub-repair.sh:45: run:  return 1
...
166/167 Test #146: osd-scrub-repair.sh .....................***Failed  906.08 sec
```

**Comment by jcsp** [comment]
retest this please (jenkins)

**Pull request merged**
