### PR TITLE
Fix keyvaluestore fails ceph_test_objectstore

### PR DESCRIPTION
**Pull request by yuyuyu101**
Fix #12798

### CODE REVIEW

**Comment by tchaikov** [comment]
tested using 
```
./ceph_test_objectstore --gtest_filter='ObjectStore/StoreTest.BigRGWObjectName/2
./ceph_test_objectstore --gtest_filter='ObjectStore/StoreTest.SimpleAttrTest/2
```

they asserted/failed without these commits.

lgtm other than a nit to see if we can simplify the code a little bit.

**Comment by yuyuyu101** [comment]
@tchaikov thanks! It should be fixed!

**Comment by tchaikov** [comment]
per sage's comment at http://tracker.ceph.com/issues/12798 , the tests which failed were disabled. but i can hardly find any trace of "disabled tests" other than the ones i tested this afternoon, see https://github.com/ceph/ceph/pull/5713#issuecomment-136100478 . @yuyuyu101 am i missing anything?

**Comment by yuyuyu101** [comment]
I guess @liewegas means disable it in ceph qa suite?

**Comment by tchaikov** [comment]
not likely.
```
$ git rev-parse origin/master
cfce56fafe62e08e4ef16f3eff17d395a246207b
$ git rev-parse HEAD
cfce56fafe62e08e4ef16f3eff17d395a246207b
$ git grep ceph_test_objectstore
suites/rados/objectstore/objectstore.yaml:      - mkdir $TESTDIR/ostest && cd $TESTDIR/ostest && ceph_test_objectstore
```

probably @liewegas can shed some light on it?

**Comment by liewegas** [comment]
keyvaluestore just needs to be added back to the list in test/objectstore/store_test.cc

**Pull request merged**
