### PR TITLE
osd: fix: slow scheduling when item_cost is large

### PR DESCRIPTION
**Pull request by jrchyang**
osd/scheduler/mClockScheduler: Take the maximum value of item_cost and osd_bandwidth_cost_per_io to solve the problem of slow scheduling when item_cost is large

We use the iops and bandwidth tested by
`ceph tell osd.0 bench 10737418240 204800 204800 100`
to verify the QoS function. iops was 400 and bandwidth was 80MiB/s.
When osd_mclock_scheduler_client_lim is set to 1,
the sequential write bandwidth is only half of the capacity.
Therefore, we believe that it should not unconditionally increase
osd_bandwidth_cost_per_io for each IO, but take the maximum of the two.

Fixes: https://tracker.ceph.com/issues/62812
Signed-off-by: Jrchyang Yu <yuzhiqiang_yewu@cmss.chinamobile.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by jrchyang** [comment]
# test info

## ceph version

reef v18.2.0

## OSD iops and bandwidth

```Shell
ceph tell osd.0 cache drop

# our client IO size is 200K
ceph tell osd.0 bench 10737418240 204800 204800 100
{
    "bytes_written": 10737418240,
    "blocksize": 204800,
    "elapsed_sec": 130.958958,
    "bytes_per_sec": 81990712.23520273,
    "iops": 400.34527458595085
}
```

The disk capacity settings are as follows:

- osd_mclock_iops_capacity_threshold_hdd = 400
- osd_mclock_max_capacity_iops_hdd = 400
- osd_mclock_max_sequential_bandwidth_hdd = 78643200

## client profile settings

```Shell
# first round
"osd_mclock_scheduler_client_lim": "0.000000",
"osd_mclock_scheduler_client_res": "0.200000",
"osd_mclock_scheduler_client_wgt": "1",

# second round
"osd_mclock_scheduler_client_lim": "1.000000",
"osd_mclock_scheduler_client_res": "0.200000",
"osd_mclock_scheduler_client_wgt": "1",

# third round
"osd_mclock_scheduler_client_lim": "0.600000",
"osd_mclock_scheduler_client_res": "0.200000",
"osd_mclock_scheduler_client_wgt": "1",

# fourth round
"osd_mclock_scheduler_client_lim": "0.300000",
"osd_mclock_scheduler_client_res": "0.200000",
"osd_mclock_scheduler_client_wgt": "1",
```

## test result

image2023-9-11_17-49-37

## questions

- We think the scheduling effect should be the same when lim is equal to 0 and 1, but the actual difference is nearly double
- issue: https://tracker.ceph.com/issues/62812

**Comment by sseshasa** [comment]
@jrchyang I posted the below comment in the associated tracker as well.
Thanks for the detailed explanation of the tests in the associated tracker.

The osd_bandwidth_cost_per_io is currently calculated using the IOPS capacity at 4 KiB
block size. This represents the base cost per IO. For progressively larger IO sizes, the
idea is that the cost should be increased appropriately. This is the reason for adding
the item cost to the base cost_per_io parameter in calc_scaled_cost(). But this approach
as you have noted results in lower than expected IOPS for an item whose cost is lower
than the cost_per_io parameter.

Therefore, your approach to pass  the greater of cost_per_io and item cost for the
tag calculation seems good to me.

@athanatos Please provide your thoughts too on this proposed change.

**Comment by athanatos** [comment]
Seems reasonable!

**Comment by jianwei1216** [comment]
From the test results,
When osd_mclock_scheduler_client_lim = [0, 1],
Whether it’s bandwidth or IOPS,
The test results before adding PR are half smaller than the test results after adding PR.

LGTM

**Review by sseshasa — APPROVED** [review]
LGTM.

**Comment by jianwei1216** [comment]
Can make check(arm) still be tested normally?

**Comment by sseshasa** [comment]
> Can make check(arm) still be tested normally?

The arm check is currently not mandatory for merging PRs. However, this has to go through CI tests for which the "needs-qa"  tag is  added.

**Comment by sseshasa** [comment]
jenkins test make check arm64

**Comment by jrchyang** [comment]
@sseshasa This appears to be a dependency error, the Clang version is below 12. Console output as follows:

```Shell
-- Performing Test COMPILER_SUPPORTS_REDUNDANT_MOVE - Success
CMake Error at src/CMakeLists.txt:146 (message):
  C++20 support requires a minimum Clang version of 12.


-- Configuring incomplete, errors occurred!
See also "/home/jenkins-build/build/workspace/ceph-pull-requests-arm64/build/CMakeFiles/CMakeOutput.log".
See also "/home/jenkins-build/build/workspace/ceph-pull-requests-arm64/build/CMakeFiles/CMakeError.log".
+ exit 1
Build step 'Execute shell' marked build as failure
[Checks API] No suitable checks publisher found.
Setting status of 65ebf2d6f1b41c93ee2e170437780846d20f5480 to FAILURE with url https://jenkins.ceph.com/job/ceph-pull-requests-arm64/46086/ and message: 'make check failed
 '
Using context: make check (arm64)
Finished: FAILURE
```

**Comment by ljflores** [comment]
> @sseshasa This appears to be a dependency error, the Clang version is below 12. Console output as follows:
> 
> ```shell
> -- Performing Test COMPILER_SUPPORTS_REDUNDANT_MOVE - Success
> CMake Error at src/CMakeLists.txt:146 (message):
>   C++20 support requires a minimum Clang version of 12.
> 
> 
> -- Configuring incomplete, errors occurred!
> See also "/home/jenkins-build/build/workspace/ceph-pull-requests-arm64/build/CMakeFiles/CMakeOutput.log".
> See also "/home/jenkins-build/build/workspace/ceph-pull-requests-arm64/build/CMakeFiles/CMakeError.log".
> + exit 1
> Build step 'Execute shell' marked build as failure
> [Checks API] No suitable checks publisher found.
> Setting status of 65ebf2d6f1b41c93ee2e170437780846d20f5480 to FAILURE with url https://jenkins.ceph.com/job/ceph-pull-requests-arm64/46086/ and message: 'make check failed
>  '
> Using context: make check (arm64)
> Finished: FAILURE
> ```

@jrchyang that test has been failing for awhile; it's unrelated to your changes.

**Pull request merged**
