### PR TITLE
rocksdb: sync with upstream

### PR DESCRIPTION
**Pull request by tchaikov**
http://tracker.ceph.com/issues/20529

### CODE REVIEW

**Comment by liewegas** [comment]
This is fine in principle, but @ifed01 previously saw a regression when moving to a newer rocksdb master, so we'll need to check that there isn't a negative performance impact!

**Comment by Liuchang0812** [comment]
jenkins test this please

**Comment by dmick** [comment]
Build error on arm64 looks real, needs to be resolved before merge

**Comment by tchaikov** [comment]
@dmick fixed and repushed.

**Comment by tchaikov** [comment]
changelog

- sync with the latest master to pick up https://github.com/facebook/rocksdb/pull/2807
- and drop SSE4.2 specific settings in cmake script

**Comment by tchaikov** [comment]
- http://pulpito.ceph.com/kchai-2017-09-08_07:40:35-rados-wip-kefu-testing-2017-09-08-1043-distro-basic-mira/
- http://pulpito.ceph.com/kchai-2017-09-08_18:05:34-rados-wip-kefu-testing-2017-09-08-1043-distro-basic-mira/

**Comment by tchaikov** [comment]
changelog

- updated the commit message to link it to http://tracker.ceph.com/issues/20529
- sync with latest fb/rocksdb, since it includes some optimizations since last commit.

**Comment by markhpc** [comment]
I tested master last night with this before and after applying this PR and have not been able to reproduce any significant performance regressions due to the new version of RocksDB.  I believe we should go ahead and merge it.

**Comment by liewegas** [comment]
Awesome, thanks mark!

**Comment by liewegas** [comment]
@tchaikov looks like the rocksdb repo branch needs to get pushed first (just update the master branch?)

**Comment by liewegas** [comment]
retest this please

**Comment by tchaikov** [comment]
retest this please.

**Comment by tchaikov** [comment]
@liewegas pushed.

**Pull request merged**
