### PR TITLE
Clarify abbreviation that I was not aware of

### PR DESCRIPTION
**Pull request by CodingSpiderFox**
Other people might not know this abbreviation too when diving into storage topics for the first time

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by athanatos** [comment]
Reasonable clarification.  Can you add a Signed-off-by and fix the line wrapping?

**Comment by CodingSpiderFox** [comment]
Signoff added.
Can't see what's wrong with the line wrapping.

**Comment by athanatos** [comment]
The lines in that file appear wrapped to a shorter length than your modified line, can you rewrap that paragraph?

**Comment by CodingSpiderFox** [comment]
image

I can't see a problem here

**Comment by athanatos** [comment]
I meant in the actual .rst file, it's just a code formatting thing.

**Comment by athanatos** [comment]
Eh, not important I guess.

**Comment by athanatos** [comment]
Oh, I didn't notice the commit message.  Please switch the first line to something like

doc: clarify WAL abbreviation in bluestore-config-ref.rst

**Comment by athanatos** [comment]
Oh, I made a mistake.  Please reopen this PR against master, this shouldn't have been merged to mimc.

**Comment by athanatos** [comment]
@CodingSpiderFox I'm sorry, I should have noticed immediately, but this PR shouldn't have been targeted at mimic -- I'll have to revert it.

Please reopen against master and ping me on the new one.  Sorry for the inconvenience.

**Pull request merged**
