### PR TITLE
crimson: audit and correct epoch captured by IOInterruptCondition

### PR DESCRIPTION
**Pull request by athanatos**
<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Comment by athanatos** [comment]
crimson-rados/thrash --limit 10 sjust-2024-07-06_06:23:37-crimson-rados:thrash-wip-sjust-crimson-testing-2024-07-05-distro-default-smithi: one notable failure, looks good otherwise
- 7789460 FuturizedCollection crash during load_pogs, https://tracker.ceph.com/issues/66294

Full crimson-rados run pending (can't access pulpito for link right now)

**Comment by athanatos** [comment]
jenkins test make check

**Comment by athanatos** [comment]
https://tracker.ceph.com/issues/66827

**Review by Matan-B — APPROVED** [review]

**Comment by Matan-B** [comment]
jenkins test api

**Comment by Matan-B** [comment]
rescheduled: https://pulpito.ceph.com/matan-2024-07-11_09:18:39-crimson-rados-wip-sjust-crimson-testing-2024-07-05-distro-crimson-smithi/

**Comment by athanatos** [comment]
Bug in InternalClientRequest, @Matan-B good catch!

**Comment by athanatos** [comment]
Repushed with fix.

**Review by Matan-B — APPROVED** [review]

**Comment by Matan-B** [comment]
jenkins test make check

**Comment by Matan-B** [comment]
jenkins test api

**Comment by Matan-B** [comment]
jenkins test api

**Pull request merged**
