### PR TITLE
jewel: auth: ceph auth add does not sanity-check caps

### PR DESCRIPTION
**Pull request by tchaikov**
http://tracker.ceph.com/issues/23673

### CODE REVIEW

**Comment by smithfarm** [comment]
Thanks, @tchaikov

**Comment by smithfarm** [comment]
Note: the predecessor PR #21363 was approved by @liewegas

**Comment by yuriw** [comment]
[wip-yuri-testing-2018-05-23-1940-jewel](https://trello.com/c/Dux006Uz/318-wip-yuri-testing-2018-05-23-1940-jewel)

**Comment by jdurgin** [comment]
looks like this needs to update the rest api test:

http://pulpito.ceph.com/yuriw-2018-05-23_21:57:10-rados-wip-yuri-testing-2018-05-23-1940-jewel-distro-basic-smithi/2578891/

```
2018-05-24T16:00:03.576 INFO:tasks.workunit:Running workunits matching rest/test.py on client.0...
2018-05-24T16:00:03.577 INFO:tasks.workunit:Running workunit rest/test.py...
2018-05-24T16:00:03.577 INFO:teuthology.orchestra.run.smithi078:Running (workunit test rest/test.py): 'mkdir -p -- /home/ubuntu/cephtest/mnt.0/client.0/tmp && cd -- /home/ubuntu/cephtest/mnt.0/client.0/tmp && CEPH_CLI_TEST_DUP_COMMAND=1 
CEPH_REF=wip-yuri-testing-2018-05-23-1940-jewel TESTDIR="/home/ubuntu/cephtest" CEPH_ARGS="--cluster ceph" CEPH_ID="0" PATH=$PATH:/usr/sbin CEPH_BASE=/home/ubuntu/cephtest/clone.client.0 adjust-ulimits ceph-coverage /home/ubuntu/cephtest
/archive/coverage timeout 3h /home/ubuntu/cephtest/clone.client.0/qa/workunits/rest/test.py'
2018-05-24T16:00:03.771 INFO:tasks.rest_api.client.rest0.smithi078.stderr:127.0.0.1 - - [24/May/2018 16:00:03] "GET /api/v0.1/auth/export HTTP/1.1" 200 -
2018-05-24T16:00:03.778 INFO:tasks.rest_api.client.rest0.smithi078.stderr:127.0.0.1 - - [24/May/2018 16:00:03] "GET /api/v0.1/auth/export.json HTTP/1.1" 200 -
2018-05-24T16:00:03.784 INFO:tasks.rest_api.client.rest0.smithi078.stderr:127.0.0.1 - - [24/May/2018 16:00:03] "GET /api/v0.1/auth/export.xml HTTP/1.1" 200 -
2018-05-24T16:00:03.813 INFO:tasks.rest_api.client.rest0.smithi078.stderr:127.0.0.1 - - [24/May/2018 16:00:03] "GET /api/v0.1/auth/export HTTP/1.1" 200 -
2018-05-24T16:00:03.819 INFO:tasks.rest_api.client.rest0.smithi078.stderr:127.0.0.1 - - [24/May/2018 16:00:03] "GET /api/v0.1/auth/export HTTP/1.1" 200 -
2018-05-24T16:00:03.833 INFO:tasks.rest_api.client.rest0.smithi078.stderr:127.0.0.1 - - [24/May/2018 16:00:03] "PUT /api/v0.1/auth/add?entity=client.xx&caps=mon&caps=allow&caps=osd&caps=allow+* HTTP/1.1" 400 -
2018-05-24T16:00:03.834 INFO:tasks.workunit.client.0.smithi078.stderr:FAILURE: url  http://localhost:5000/api/v0.1/auth/add?entity=client.xx&caps=mon&caps=allow&caps=osd&caps=allow+*
2018-05-24T16:00:03.835 INFO:tasks.workunit.client.0.smithi078.stderr:expected 200, got 400
2018-05-24T16:00:03.835 INFO:tasks.workunit.client.0.smithi078.stderr:Response content:  {"status": "Error: moncap parse failed, stopped at 'allow' of 'allow'\n (-22)", "output": []}
2018-05-24T16:00:03.835 INFO:tasks.workunit.client.0.smithi078.stderr:Headers:  {'Date': 'Thu, 24 May 2018 16:00:03 GMT', 'Content-Length': '93', 'Content-Type': 'text/html; charset=utf-8', 'Server': 'Werkzeug/0.10.4 Python/2.7.12'}
2018-05-24T16:00:03.835 INFO:tasks.workunit.client.0.smithi078.stdout:GET auth/export: plain 200
2018-05-24T16:00:03.835 INFO:tasks.workunit.client.0.smithi078.stdout:GET auth/export.json: json 200
2018-05-24T16:00:03.835 INFO:tasks.workunit.client.0.smithi078.stdout:GET auth/export.xml: xml 200
2018-05-24T16:00:03.836 INFO:tasks.workunit.client.0.smithi078.stdout:GET auth/export: json 200
2018-05-24T16:00:03.836 INFO:tasks.workunit.client.0.smithi078.stdout:GET auth/export: xml 200
2018-05-24T16:00:03.836 INFO:tasks.workunit.client.0.smithi078.stdout:PUT auth/add?entity=client.xx&caps=mon&caps=allow&caps=osd&caps=allow+*: json 400

```

**Comment by tchaikov** [comment]
@yuriw @jdurgin @smithfarm updated.

**Comment by yuriw** [comment]
[wip-yuri4-testing-2018-06-12-2037-jewel](https://trello.com/c/tzHUzvPd/327-wip-yuri4-testing-2018-06-12-2037-jewel)

**Comment by tchaikov** [comment]
@smithfarm #24906

**Pull request merged**
