### PR TITLE
crimson/os/seastore/segment_cleaner: parallel live extents retrieval

### PR DESCRIPTION
**Pull request by xxhdx1985126**
This is for gc perf improvement. The result is shown in the following graphs: with "parallel live extents retrieval", cpu time spent on polling drops from about 19% to below 2.5%, and the crimson-seastore's throughput also show visible improvement.

**Sequential live extents retrieval:**
image

**Parallel live extents retrieval:**
image

Crimson-Seastore throughput:
image

Signed-off-by: Xuehan Xu <xxhdx1985126@gmail.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/master/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by xxhdx1985126** [comment]
@athanatos Hi, sam, about the commit `crimson/os/seastore/transaction: allow trying to insert duplicated extents to transacstions' read_set`, I'm not very sure whether it's appropriate actually. Should we implement some kind of placeholder to put into transactions' read_set, which is replaced with the actual extents later, and make concurrent extents retrieval to wait on that placeholder? Is it worth it? What do you think? Thanks:-)

**Comment by athanatos** [comment]
As we discussed earlier, I think the key here is to ensure that Transaction::add_to_read_set gets called atomically with Transaction::get_extent.  Cache::get_extent should be changed accordingly.  Additionally, any extents we get back from Transaction::get_extent need to have wait_io() called prior to returning since it's now possible that the read hasn't yet completed.

**Comment by xxhdx1985126** [comment]
@athanatos I think this pr is good to go, please take a look again, thanks:-)

**Review by athanatos — APPROVED** [review]

**Comment by cyx1231st** [comment]
@athanatos @xxhdx1985126 Sorry for the late reply, I think there might be a loophole that leaks the pending extents, specifically, from the synchronous method `update_extent_from_transaction()`:
https://github.com/ceph/ceph/blob/97f5519c10f7d4ceb19d5fd8ca8245b47e6d0181/src/crimson/os/seastore/cache.h#L841-L863
So the `updated` extent might be still not ready for rewrite:
https://github.com/ceph/ceph/blob/97f5519c10f7d4ceb19d5fd8ca8245b47e6d0181/src/crimson/os/seastore/transaction_manager.cc#L505

But I'm still not sure if it is still correct simply by changing `update_extent_from_transaction()` to an asynchronous version with `wait_io()`.

**Comment by xxhdx1985126** [comment]
> So the `updated` extent might be still not ready for rewrite:

Is this an issue that came up in a test? It looks to me that, when the gc reaches the point of 'update_extent_from_transaction', the extent to be rewritten should already be in the transaction's read_set

**Comment by cyx1231st** [comment]
> Is this an issue that came up in a test? 
No, I just think that part of logic looks incorrect.

**Comment by xxhdx1985126** [comment]
I think the code of `Cache::update_extent_from_transaction()` needs some clean up.

**Pull request merged**
