### PR TITLE
qa/tests - added tag 12.2.5. to the mix and removed -x path as unneeded

### PR DESCRIPTION
**Pull request by yuriw**
Signed-off-by: Yuri Weinstein <yweinste@redhat.com>

### CODE REVIEW

**Comment by yuriw** [comment]
Note: this suite has to run against `luminous` branch now as `-x` was removed.  I think for future releases we will need to keep all point releases included to make sure good testing coverage.  ATM I kept `12.2.2.` => `12.2.5` => `luminous' latest

**Comment by yuriw** [comment]
http://pulpito.ceph.com/yuriw-2018-06-08_19:28:10-upgrade:luminous-p2p-luminous-distro-basic-smithi/

**Comment by batrick** [comment]
@yuriw yes.

**Comment by yuriw** [comment]
@batrick and `POOL_APP_NOT_ENABLED` ?

**Comment by yuriw** [comment]
So far I whitelisted:
    - FS_DEGRADED
    - POOL_APP_NOT_ENABLED
    - CACHE_POOL_NO_HIT_SET
    - POOL_FULL

http://pulpito.ceph.com/yuriw-2018-06-11_22:41:36-upgrade:luminous-p2p-luminous-distro-basic-smithi/

@batrick @tchaikov @jdurgin any clues?

**Comment by tchaikov** [comment]
@yuriw i checked the log of mon.a of http://pulpito.ceph.com/yuriw-2018-06-11_22:41:36-upgrade:luminous-p2p-luminous-distro-basic-smithi/2655431/

```
$ zgrep -E -o 'pg_num [0-9]+ pgp_num [0-9]+'  /a//yuriw-2018-06-11_22:41:36-upgrade:luminous-p2p-luminous-distro-basic-smithi/2655431/remote/*/log/ceph-mon.a.log.gz| sort|uniq
pg_num 11 pgp_num 8
pg_num 4 pgp_num 4
pg_num 64 pgp_num 64
pg_num 6 pgp_num 6
pg_num 8 pgp_num 8
```

but failed to find the case where "pg_num > pgp_num".

**Comment by yuriw** [comment]
@tchaikov real issue or test problem ?

**Comment by jdurgin** [comment]
@yuriw that's due to a test setting it that way intentionally - can whitelist SMALLER_PG

**Comment by yuriw** [comment]
added `SMALLER_PG`
http://pulpito.front.sepia.ceph.com:80/yuriw-2018-06-19_22:57:29-upgrade:luminous-p2p-luminous-distro-basic-smithi/

**Comment by yuriw** [comment]
added `pool\(s\) full`
http://pulpito.front.sepia.ceph.com:80/yuriw-2018-06-20_16:50:01-upgrade:luminous-p2p-luminous-distro-basic-smithi/

**Comment by yuriw** [comment]
and `OSD_DOWN`
http://pulpito.front.sepia.ceph.com:80/yuriw-2018-06-20_19:32:16-upgrade:luminous-p2p-luminous-distro-basic-smithi/

**Comment by yuriw** [comment]
added `missing hit_sets`

http://pulpito.front.sepia.ceph.com:80/yuriw-2018-06-20_22:20:59-upgrade:luminous-p2p-luminous-distro-basic-smithi/

**Comment by yuriw** [comment]
Merged this https://github.com/ceph/ceph/pull/22666 after mergeing
https://github.com/ceph/ceph/pull/22666

**Pull request merged**
