### PR TITLE
spdk: update submodule to more recent upstream

### PR DESCRIPTION
**Pull request by smithfarm**
This commit fast-forwards the SPDK submodule to upstream commit
93bd60e0de6b161567182d965239735bf467e85c to enable the py3-only build.
(Without said commit, SPDK configure script fails to find the python
interpreter in py3-only environment.)

Signed-off-by: Nathan Cutler <ncutler@suse.com>

### CODE REVIEW

**Comment by smithfarm** [comment]
@yuyuyu101 @liu-chunmei Does this look OK to you?

**Comment by smithfarm** [comment]
This PR passed a rados run here: http://pulpito.ceph.com/smithfarm-2018-01-24_19:46:55-rados-wip-smithfarm-testing-distro-basic-smithi/

197 of 202 tests passed.

Failed tests:

* "2018-01-25 02:00:26.400626 osd.5 osd.5 172.21.15.77:6810/36898 23 : cluster [ERR] 3.0 scrub stat mismatch, got 48/48 objects, 5/5 clones, 23/23 dirty, 0/0 omap, 0/0 pinned, 1/1 hit_set_archive, 7/7 whiteouts, 112856156/114189825 bytes, 249/249 hit_set_archive bytes." in cluster log 
* "2018-01-25 01:54:14.602444 mgr.z client.4375 172.21.15.193:0/3577525578 1 : cluster [ERR] Unhandled exception from module 'prometheus' while running on mgr.z: error(98, 'Address already in use')" in cluster log
* "2018-01-25 01:40:33.702645 mon.f mon.0 172.21.15.94:6789/0 118 : cluster [WRN] Health check failed: 1 slow ops, oldest one blocked for 33 sec (SLOW_OPS)" in cluster log

Two tests are still running.

**Comment by tchaikov** [comment]
@yuyuyu101 i am merging this PR to unblock @smithfarm . if you believe that we should not pick up this version of SPDK, please feel free to ping me.

**Comment by smithfarm** [comment]
@tchaikov Thanks

**Pull request merged**
