### PR TITLE
ceph-disk: Accept bcache devices as data disks

### PR DESCRIPTION
**Pull request by sabaini**
Fixes: http://tracker.ceph.com/issues/13278
Signed-off-by: Peter Sabaini <peter@sabaini.at>

### CODE REVIEW

**Comment by ErwanAliasr1** [comment]
Would be nice to get a topic like "ceph-disk: Accept bcache devices as data disks"

**Comment by sabaini** [comment]
Sure, like this?

**Comment by ErwanAliasr1** [comment]
Thanks

**Comment by tchaikov** [comment]
@sabaini ideally you might want to update the title of your commit message with the prefix suggested by @ErwanAliasr1 , "git amend" and "git push -f".

**Comment by tchaikov** [comment]
@dachary mind taking a look?

**Comment by dachary** [comment]
@sabaini this assumes that bcache devices always are partitions, right ?

**Comment by dachary** [comment]
Hey jenkins, test this please !

**Comment by sabaini** [comment]
@dachary Correct, the individual /dev/bcacheN devices are always partitions

**Comment by smithfarm** [comment]
Do we know why this feature was merged to jewel when it is not present in master?

**Comment by sabaini** [comment]
This might just be a mistake on my part. I'd be happy to do a PR against master

**Comment by smithfarm** [comment]
@sabaini If it's really missing in master (I haven't checked), that means it dies when jewel goes EOL. So a PR against master might be a good idea.

**Comment by hansbogert** [comment]
@smithfarm maybe it should be EOL, because since kernel 4.10, bcache devices can definitely have partitions.
I had to monkey patch `/usr/lib/python2.7/dist-packages/ceph_disk/main.py` on machines, to  get expected behavior during deploy.

Expected behavior being: bcache devices being automatically mounted and activated by Ceph, without resorting to a manual fstab config, and a hardcoded ceph.conf which holds a mapping  journals to data (bcache) disks.

**Comment by smithfarm** [comment]
Sorry, I didn't realize this was merged in July 2016 (I was thinking 2017).

**Pull request merged**
