### PR TITLE
doc: document the mds_autoscaler mgr plugin

### PR DESCRIPTION
**Pull request by mchangir**
Documentation for the MDS Autoscaler mgr module.

Fixes: https://tracker.ceph.com/issues/46884
Signed-off-by: Milind Changire <mchangir@redhat.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Review by batrick — CHANGES_REQUESTED** [review]
Please [title your commits according to the conventions of this project](https://github.com/ceph/ceph/blob/master/SubmittingPatches.rst#commit-title). In particular, please use the imperative mood and summarize the change. This is required for your PR to be merged.

See [this article](https://help.github.com/en/articles/changing-a-commit-message) on GitHub on how to amend commits and update your pull request.

**Comment by mchangir** [comment]
> Please [title your commits according to the conventions of this project](https://github.com/ceph/ceph/blob/master/SubmittingPatches.rst#commit-title). In particular, please use the imperative mood and summarize the change. This is required for your PR to be merged.
> 
> See [this article](https://help.github.com/en/articles/changing-a-commit-message) on GitHub on how to amend commits and update your pull request.

@batrick 
I've updated the document text as well as the commit message.
Please review and let me know if it fits the purpose.

**Comment by batrick** [comment]
> > Please [title your commits according to the conventions of this project](https://github.com/ceph/ceph/blob/master/SubmittingPatches.rst#commit-title). In particular, please use the imperative mood and summarize the change. This is required for your PR to be merged.
> > See [this article](https://help.github.com/en/articles/changing-a-commit-message) on GitHub on how to amend commits and update your pull request.
> 
> @batrick
> I've updated the document text as well as the commit message.
> Please review and let me know if it fits the purpose.

You can keep "doc: ". I was referring to the style of your commit title. It should be in the imperative mood and summarize the change:

`doc: document the mds_autoscaler mgr plugin`

**Comment by mchangir** [comment]
> > > Please [title your commits according to the conventions of this project](https://github.com/ceph/ceph/blob/master/SubmittingPatches.rst#commit-title). In particular, please use the imperative mood and summarize the change. This is required for your PR to be merged.
> > > See [this article](https://help.github.com/en/articles/changing-a-commit-message) on GitHub on how to amend commits and update your pull request.
> > 
> > 
> > @batrick
> > I've updated the document text as well as the commit message.
> > Please review and let me know if it fits the purpose.
> 
> You can keep "doc: ". I was referring to the style of your commit title. It should be in the imperative mood and summarize the change:
> 
> `doc: document the mds_autoscaler mgr plugin`

done

**Review by batrick — APPROVED** [review]

**Pull request merged**
