### PR TITLE
rpm: no @TARBALL_BASENAME@ on SUSE, add appropriate conditionals

### PR DESCRIPTION
**Pull request by smithfarm**
Signed-off-by: Nathan Cutler <ncutler@suse.com>

### CODE REVIEW

**Comment by smithfarm** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;fEr00X5M&#x2F;1989-rpm-no-tarball-basename-on-suse-add-appropriate-conditionals"> rpm: no @TARBALL_BASENAME@ on SUSE, add appropriate conditionals</a>

**Comment by smithfarm** [comment]
@ktdreyer Feel like helping SUSE out? ;-)

**Comment by ktdreyer** [comment]
`@TARBALL_BASENAME@` is not a RHEL-specific thing, it's more like a Ceph-specific thing, like the `@VERSION@` or `@RPM_RELEASE@` macros we use there. Is there another way to solve this for SUSE?

**Comment by smithfarm** [comment]
It's solvable via downstream patches, of course, but I was hoping to get rid of those.

AFAICT those tokens - @VERSION@ @RPM_RELEASE@ @TARBALL_BASENAME@ - are used by the gitbuilders and the Jenkins build infrastructure, neither of which produce packages for SUSE.

But maybe that will change someday. Closing, then.

**Comment by ktdreyer** [comment]
Yes, hopefully we will change that (and have Jenkins build for SUSE!)

**Pull request closed without merging**
