### PR TITLE
ceph-fuse: add to selinux profile

### PR DESCRIPTION
**Pull request by batrick**
Fixes: http://tracker.ceph.com/issues/36103

Signed-off-by: Patrick Donnelly <pdonnell@redhat.com>

### CODE REVIEW

**Comment by batrick** [comment]
Not sure if this will work as `ceph-fuse` needs access to some `/dev/fuse*` device. I'll run it through QA to see...

**Comment by b-ranto** [comment]
lgtm, let's see what the test run discovers.

**Comment by batrick** [comment]
http://pulpito.ceph.com/?branch=wip-pdonnell-testing-20180924.230702

Various failures are unrelated. Didn't see any selinux denials. @b-ranto please approve if you think this is good to merge.

**Comment by vasukulkarni** [comment]
unless we test this with ceph-deploy or ceph-ansible, the policy is not in affect and runs as unconfined.

**Pull request merged**
