### PR TITLE
mon/MDSMonitor: fix gid/rank/state parsing

### PR DESCRIPTION
**Pull request by jcsp**
Signed-off-by: John Spray <john.spray@redhat.com>

### CODE REVIEW

**Comment by jcsp** [comment]
This is an alternative fix for https://github.com/ceph/ceph/pull/3506

**Comment by hjwsm1989** [comment]
yeah,it's more flexiable.

**Comment by dmick** [comment]
Definitely like this better from an elegance standpoint; when I did this first I was overwhelmed by the number and variety of types there were and terrified of the amount of specialization and compile time/linktime bloat.  That terror may well mostly be fear of the unknown, but the choice was conscious for that reason.  Am I worrying about nothing?

**Comment by jcsp** [comment]
If we were adding hundreds of types then perhaps, but I think as long as we're only adding definitions for types that are actually used as cmd arguments we won't cause bloat.

**Pull request merged**
