### PR TITLE
librbd: potential race between discard and writeback

### PR DESCRIPTION
**Pull request by dillaman**

### CODE REVIEW

**Comment by smithfarm** [comment]
```
Test   #1: run-rbd-unit-tests.sh ...................***Failed  147.49 sec
```

**Comment by batrick** [comment]
retest this please

**Comment by dillaman** [comment]
@smithfarm Thanks -- I saw the failure and have been trying to repeat a failure locally (since the ```make check``` jenkins builders now "conveniently" drop the end of the test run output).

**Comment by trociny** [comment]
@dillaman see [1] for "src/osdc/ObjectCacher.cc: 605: FAILED assert(bh->waitfor_read.empty())"

[1] http://pulpito.ceph.com/trociny-2018-04-05_10:40:08-rbd-wip-mgolub-testing-distro-basic-smithi/

**Comment by dillaman** [comment]
@trociny Thanks -- I repeated it locally by running under a CPU restricted cgroup. The readahead logic is racing w/ the IO.

**Comment by trociny** [comment]
@ceph-jenkins retest this please

**Comment by dillaman** [comment]
retest this please

**Comment by dillaman** [comment]
@trociny Yuri hit the same issue here [1] w/ the master branch.

[1] http://qa-proxy.ceph.com/teuthology/yuriw-2018-04-05_21:02:08-rbd-wip-yuriw-master-4.5.18-distro-basic-smithi/2358072/teuthology.log

**Comment by dillaman** [comment]
@trociny Thanks -- I suspect ```ObjectCacherObjectDispatch``` is not respecting the ```OBJECT_DISCARD_FLAG_SKIP_PARTIAL``` flag. I'm tracking it here [1].

[1] http://tracker.ceph.com/issues/23597

**Comment by trociny** [comment]
@dillaman Today I retested with different option combinations. It also fails when `skip_partial_discard` is disabled. It stops fails only when `rbd cache = false`, other options from the list above looks unimportant. So it is probably not related to `OBJECT_DISCARD_FLAG_SKIP_PARTIAL` flag.

**Comment by dillaman** [comment]
@trociny It was related to my attempt to avoid initializing the ```ObjectCacher``` for every image in a clone chain. Once ```ObjectCacher``` receives an ```-ENOENT``` it will mark the whole object as missing so it can create odd edge conditions.

**Pull request merged**
