### PR TITLE
nautilus: rgw: multisite log trimming only checks peers that sync from us

### PR DESCRIPTION
**Pull request by ashishkumsingh**
https://tracker.ceph.com/issues/39417

### CODE REVIEW

**Comment by cbodley** [comment]
there's a related bug in http://tracker.ceph.com/issues/39487 that i'd like to include in these backports. can we please hold off on that until https://github.com/ceph/ceph/pull/27794 merges?

**Comment by yuriw** [comment]
[wip-yuri6-testing-2019-05-28-1952-nautilus](https://trello.com/c/tlYhp5P4/619-wip-yuri6-testing-2019-05-28-1952-nautilus)

**Comment by smithfarm** [comment]
> there's a related bug in http://tracker.ceph.com/issues/39487 that i'd like to include in these backports.
> can we please hold off on that until #27794 merges?

Oops, @cbodley It looks like we didn't hold off. #27794 is still open. What now?

(Next time, maybe add DNM tag?)

**Comment by cbodley** [comment]
thanks @smithfarm. i'm working to get a review on the followup fix. this pr doesn't introduce a new bug, it just doesn't completely fix the issue. so it's okay if we do a release that doesn't include the latter, but i'll try to get it ready

**Pull request merged**
