### PR TITLE
cmake, debian: strip "-Wl,-Bsymbolic-functions" from LDFLAGS and cleanups

### PR DESCRIPTION
**Pull request by tchaikov**
- [x] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by tchaikov** [comment]
```
 ceph version 14.0.0-1980-g55b9305 (55b9305fea77cda0f3118c17d0e522988f02b0a8) nautilus (dev)
 1: (()+0x11390) [0x7f602b219390]
 2: (gsignal()+0x38) [0x7f602a52a428]
 3: (abort()+0x16a) [0x7f602a52c02a]
 4: (()+0x15497e) [0x7f6014d5a97e]
 5: (__gxx_personality_v0()+0xe1) [0x7f6014cb7781]
 6: ceph-osd() [0x15cdb43]
 7: ceph-osd() [0x15ce35f]
 8: (__cxa_throw()+0x37) [0x15284c7]
 9: (ceph::buffer::list::iterator_impl<true>::copy(unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)+0xdf) [0x10
b4b0f]
 10: (()+0x9c2cb) [0x7f6014ca22cb]
 11: (()+0x7867e) [0x7f6014c7e67e]
 12: (ClassHandler::ClassMethod::exec(void*, ceph::buffer::list&, ceph::buffer::list&)+0x34) [0x9c6be4]
 13: (PrimaryLogPG::do_osd_ops(PrimaryLogPG::OpContext*, std::vector<OSDOp, std::allocator<OSDOp> >&)+0x1166) [0xada536]
 14: (PrimaryLogPG::prepare_transaction(PrimaryLogPG::OpContext*)+0x9f) [0xaeb59f]
 15: (PrimaryLogPG::execute_ctx(PrimaryLogPG::OpContext*)+0x37f) [0xaebdaf]
 16: (PrimaryLogPG::do_op(boost::intrusive_ptr<OpRequest>&)+0x3667) [0xaf0807]
 17: (PrimaryLogPG::do_request(boost::intrusive_ptr<OpRequest>&, ThreadPool::TPHandle&)+0xcf2) [0xaf4a92]
 18: (OSD::dequeue_op(boost::intrusive_ptr<PG>, boost::intrusive_ptr<OpRequest>, ThreadPool::TPHandle&)+0x1b3) [0x93ff13]
 19: (PGOpItem::run(OSD*, OSDShard*, boost::intrusive_ptr<PG>&, ThreadPool::TPHandle&)+0x62) [0xbcd142]
 20: (OSD::ShardedOpWQ::_process(unsigned int, ceph::heartbeat_handle_d*)+0x53c) [0x96e23c]
 21: (ShardedThreadPool::shardedthreadpool_worker(unsigned int)+0x466) [0xf09b96]
 22: (ShardedThreadPool::WorkThreadSharded::entry()+0x10) [0xf0b710]
```
/a/sage-2018-08-05_20:41:16-rados-wip-sage2-testing-2018-08-05-1417-distro-basic-smithi/2869145

**Comment by tchaikov** [comment]
http://pulpito.ceph.com/kchai-2018-08-06_04:34:40-rados-wip-strip-debian-ldflags-distro-basic-smithi/

**Comment by tchaikov** [comment]
changelog

- remove `Buildgperftools.cmake`, it's not used anymore
- revert the rocksdb submodule change.

**Comment by tchaikov** [comment]
- http://pulpito.ceph.com/kchai-2018-08-05_01:51:41-rados-wip-kefu-testing-2018-08-05-0015-distro-basic-mira/
- http://pulpito.ceph.com/kchai-2018-08-06_10:41:52-rados-wip-kefu-testing-2018-08-05-0015-distro-basic-smithi/
- http://pulpito.ceph.com/kchai-2018-08-06_13:50:47-rados-wip-kefu2-testing-2018-08-06-2008-distro-basic-smithi/

**Comment by liewegas** [comment]
seems to work for me!

**Pull request merged**
