### PR TITLE
init-radosgw: check in /var/lib/ceph/radosgw ; unify w/ sysv version

### PR DESCRIPTION
**Pull request by liewegas**

### CODE REVIEW

**Comment by liewegas** [comment]
manually tested this on wheezy and centos7 without problems.

(except that wheezy doesn't recognized the git.ceph.com cert and i had to hack ceph-deploy to pass --no-check-certificate for install to work.)

**Comment by liewegas** [comment]
@ktdreyer can you take a look?  killing two birds here, making radosgw script look in /var/lib/ceph/radosgw (so that it works with teh ceph-deploy rgw create) and finally merging the two radosgw init scripts into one.

**Comment by ktdreyer** [comment]
This makes me happy and it looks good. I haven't tested it out, though

**Comment by trhoden** [comment]
@liewegas This is looking good to me.  I'd like to pull it down and test it on a couple of EL machines first, though.

The main piece I don't really grok is the part where it's checking if $host != $hostname.  the $host var in this case seems to come from the ceph.conf file, but I thought in the "new style" of rgw daemons, there isn't an entry for the rgw daemons in the .conf file at all.  So what does `ceph-conf -n $name host` return in that case?

**Comment by trhoden** [comment]
@liewegas this seems to work on CentOS6.  I can get RGW to start now! Going to check CentOS7 next.

I see the following output when doing "service ceph-radosgw start"

```
[root@cent661 init.d]# service ceph-radosgw start
libust[7622/7622]: Warning: HOME environment variable not set. Disabling LTTng-UST per-user tracing. (in setup_local_apps() at lttng-ust-comm.c:305)
Starting client.rgw.cent661...
/usr/bin/dirname: extra operand `-n'
Try `/usr/bin/dirname --help' for more information.
```

Not sure if these can safely be ignored or not.

I ran with /bin/sh -x, and the first one comes from:
```
++ /usr/bin/radosgw -n client.rgw.cent661 --show-config-value log_file
libust[7520/7520]: Warning: HOME environment variable not set. Disabling LTTng-UST per-user tracing. (in setup_local_apps() at lttng-ust-comm.c:305)
```

The second one comes from:
```
+ case $1 in
+ user=root
+ shift
+ '[' '/usr/bin/radosgw -n client.rgw.cent661' '!=' '/usr/bin/radosgw -n client.rgw.cent661' ']'
+ '[' -z '' ']'
+ base='radosgw -n client.rgw.cent661'
+ __pids_var_run 'radosgw -n client.rgw.cent661' ''
+ local 'base=radosgw -n client.rgw.cent661'
+ local 'pid_file=/var/run/radosgw -n client.rgw.cent661.pid'
++ /usr/bin/dirname /var/run/radosgw -n client.rgw.cent661.pid
/usr/bin/dirname: extra operand `-n'
Try `/usr/bin/dirname --help' for more information.
```

**Comment by trhoden** [comment]
@liewegas Also, just to confirm -- the ceph-radosgw init script does *not* accept daemon names, correct?  It looks like it will just automatically start/stop any daemons int he config file (in sections of client.radosgw), or daemons defined in /var/lib/ceph/radosgw.

I'm going to remove the passing of the daemon name to the service call in ceph-deploy.

**Comment by trhoden** [comment]
Works on CentOS7!  No weird output from that one, either.

I used all my queued up fixes on ceph-deploy with it, and it all went smooth.  Just found one more fix I need to do with ceph-deploy (ceph-deploy still tries to chkconfig/systemctl enable ceph instead of ceph-radosgw).

**Comment by liewegas** [comment]
@trhoden yeah, it doesn't (currently) take a daemon name.

**Comment by trhoden** [comment]
Ack, I missed that this was assigned to me (I don't think I have a filter that catches that).  I think this is ready to merge, but now it needs a rebase.  Sorry @liewegas, can you rebase?

**Comment by liewegas** [comment]
rebased!

**Comment by trhoden** [comment]
LGTM. Merging...

**Comment by ktdreyer** [comment]
So we have to cherry-pick this to `next`, right?

**Comment by trhoden** [comment]
Not sure about ``next``, but it should also be a backport for Hammer, right?  Sorry, I do so little with Ceph I'm not sure how to indicate that.  Not sure if it is here or if in Tracker (and I don't think there is a ticket open for this).

**Comment by ktdreyer** [comment]
Sage occasionally merges the `next` branch into the `master` branch, but it doesn't go the other way round. So if we want something in the "next" release of Ceph, we have to get it into both `next` and `master`. Otherwise this might not land in Infernalis; it will be in the release _after_ that one. Sage, do I have that right?

**Comment by liewegas** [comment]
On Thu, 14 May 2015, Ken Dreyer wrote:
> Sage occasionally merges the next branch into the master branch, but it doesn't go the other way round. So if we want something in the "next"
> release of Ceph, we have to get it into both next and master. Otherwise this might not land in Infernalis; it will be in the release after that
> one. Sage, do I have that right?

For each dev release we reset next to current master, and we're on #2 of 
5-7 for infernalis, so anything in master will definitely make it.  
There'll be lost of 'feature freeze!' noise before there is danger of 
missing it...

**Comment by ktdreyer** [comment]
Oh ok, great. I wasn't sure whether next gets reset during each dev release, or whether it only happens after each named release.

**Pull request merged**
