### PR TITLE
common/compressor: update the interfaces and data structures

### PR DESCRIPTION
**Pull request by liumiaomiaoIntel**
Since the QAT device is updated from 1.7 to 2.0 generation[1], the interfaces and data structures of QATzip library has also changed. Relevant interfaces and data structures need to be updated to make it compatible with the latest QATzip library, allowing compression with QAT.

[1] https://www.intel.com/content/www/us/en/developer/topic-technology/open/quick-assist-technology/overview.html

Signed-off-by: Liu Miaomiao <miaomiao.liu@intel.com>

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by hualongfeng** [comment]
jenkins test Pull Request Checklist / Verify (pull_request)

**Comment by liumiaomiaoIntel** [comment]
jenkins retest this please

**Comment by hualongfeng** [comment]
Hi @majianpeng  Please review this PR. In this PR, we also disable the `busy_polling` at the same time.

**Comment by liumiaomiaoIntel** [comment]
jenkins retest this please

**Pull request closed without merging**
