### PR TITLE
luminous: osd: allow recovery preemption

### PR DESCRIPTION
**Pull request by liewegas**

### CODE REVIEW

**Comment by liewegas** [comment]
do not backport until we fix http://tracker.ceph.com/issues/21613

**Comment by liewegas** [comment]
http://pulpito.ceph.com/sage-2017-10-06_01:12:40-rados-wip-sage-testing2-2017-10-05-1735-distro-basic-smithi/

**Comment by liewegas** [comment]
@gregsfortytwo this is everything except the final patch that adds the CANCEL verb.  The second to last one that adds the cancel TrivialEvent is not terribly useful but it helps clarify the code a bit and keeps us as close to master as possible.

**Comment by gregsfortytwo** [comment]
Is there any point to *not* backporting the final verb-changing patch? That'll keep us closer still to master ;)
Oh, it's conditioned on VERSION_MIMIC and giving it its own feature bit would be tedious...okay.

Anyway, I'm fine backporting these patches and I verified this PR has all the patches from #17839 and #18070; were there some backport conflicts you wanted me to check on it @liewegas?

**Comment by liewegas** [comment]
The only conflict was from the PG_STATE_BACKFILL -> PG_STATE_BACKFILLING rename vs code in PGMap.cc that was removed in master, so I think we're good to go!  Thanks!

**Pull request merged**
