### PR TITLE
src/valgrind.supp: Adding know leaks unrelated to ceph

### PR DESCRIPTION
**Pull request by NitzanMordhai**
During teuthology test we can hit few valgrind errors that stop the tests, one of them is Rocksdb version info and the other one is dl-init.
Adding them to the valgrind suppression file.

Fixes: https://tracker.ceph.com/issues/52136
       https://tracker.ceph.com/issues/57751
       https://tracker.ceph.com/issues/53575
Signed-off-by: Nitzan Mordechai <nmordec@redhat.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Review by ljflores — APPROVED** [review]
We can perhaps run some of the tests recorded in the Trackers ~ 20-30 times, and if everything looks good, merge!

**Comment by ljflores** [comment]
@NitzanMordhai perhaps another related tracker? https://tracker.ceph.com/issues/55809

**Comment by NitzanMordhai** [comment]
> @NitzanMordhai perhaps another related tracker? https://tracker.ceph.com/issues/55809

That one looks like a monitor leaking memory, need to fix that one

**Comment by NitzanMordhai** [comment]
Ran 50 jobs: http://pulpito.front.sepia.ceph.com/nmordech-2022-11-28_07:46:50-rados:verify-wip-nitzan-valgrind-supp-adding-rocksdb-dl-init-distro-default-smithi/

Not related failure:
7093112 - failed in Alarm for ceph_test_rados_api_aio
7093113 - Segmentation fault      (core dumped) ceph_test_rados_api_watch_notify_pp
7093117 - api_watch_notify_pp:   watches.size()

**Comment by ljflores** [comment]
Rados suite review:

https://pulpito.ceph.com/?branch=wip-yuri-testing-2022-12-06-1204
https://pulpito.ceph.com/?branch=wip-yuri-testing-2022-12-12-1136

Failures, unrelated:
    1. https://tracker.ceph.com/issues/58096
    2. https://tracker.ceph.com/issues/52321
    3. https://tracker.ceph.com/issues/58173
    4. https://tracker.ceph.com/issues/52129
    5. https://tracker.ceph.com/issues/58097
    6. https://tracker.ceph.com/issues/57546
    7. https://tracker.ceph.com/issues/58098
    8. https://tracker.ceph.com/issues/57731
    9. https://tracker.ceph.com/issues/55606
    10. https://tracker.ceph.com/issues/58256
    11. https://tracker.ceph.com/issues/58258

Details:
    1. test_cluster_set_reset_user_config: NFS mount fails due to missing ceph directory - Ceph - Orchestrator
    2. qa/tasks/rook times out: 'check osd count' reached maximum tries (90) after waiting for 900 seconds - Ceph - Orchestrator
    3. api_aio_pp: failure on LibRadosAio.SimplePoolEIOFlag and LibRadosAio.PoolEIOFlag - Ceph - RADOS
    4. LibRadosWatchNotify.AioWatchDelete failed - Ceph - RADOS
    5. qa/workunits/post-file.sh: kex_exchange_identification: read: Connection reset by peer - Ceph - RADOS
    6. rook: ensure CRDs are installed first - Ceph - Orchestrator
    7. qa/workunits/rados/test_crash.sh: crashes are never posted - Ceph - RADOS
    8. Problem: package container-selinux conflicts with udica < 0.2.6-1 provided by udica-0.2.4-1 - Infrastructure
    9. [ERR] Unhandled exception from module ''devicehealth'' while running on mgr.y: unknown - Ceph - CephSqlite
    10. ObjectStore/StoreTestSpecificAUSize.SpilloverTest/2: Expected: (logger->get(l_bluefs_slow_used_bytes)) >= (16 * 1024 * 1024), actual: 0 vs 16777216 - Ceph - Bluestore
    11. rook: kubelet fails from connection refused - Ceph - Orchestrator

**Pull request merged**
