### PR TITLE
nautilus: qa/tasks: add remaining tests for fs volume

### PR DESCRIPTION
**Pull request by joscollin**
backport tracker: https://tracker.ceph.com/issues/43338
possibly a backport of https://github.com/ceph/ceph/pull/31884
parent tracker: https://tracker.ceph.com/issues/42872

---

original PR body:

Fixes: https://tracker.ceph.com/issues/43338

---

updated using ceph-backport.sh version 15.0.0.6950

### CODE REVIEW

**Comment by smithfarm** [comment]
```
172/172 Test  #51: unittest_lockdep ........................***Timeout 3600.01 sec
```

**Comment by smithfarm** [comment]
jenkins test make check

**Comment by joscollin** [comment]
@batrick @smithfarm We may have to cherry-pick this also: https://github.com/ceph/ceph/pull/32459/commits/67e43f466826f121d7649da33954b5b6a5454101

**Comment by smithfarm** [comment]
@joscollin Is 67e43f4 in master, though? If not, we probably should not cherry-pick it.

Also, you could have left this PR open - all the extra commits will go away once 14.2.6 is released.

**Comment by joscollin** [comment]
@smithfarm I would let the backport team take https://tracker.ceph.com/issues/43338, as I don't have time to bother about it's correctness.

**Pull request closed without merging**
