### PR TITLE
mon/ConfigMonitor: make 'num' of 'config reset' optional; allow target version 0

### PR DESCRIPTION
**Pull request by xiexingguo**
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by xiexingguo** [comment]
@liewegas Can you look?

**Comment by xiexingguo** [comment]
Failure is caused by the duplicate commands ENV from the CLI as "ceph config reset" is not idempotent.

http://pulpito.ceph.com/xxg-2019-03-25_04:20:10-rados-wip-config-mon-core-distro-basic-smithi/

**Comment by liewegas** [comment]
Hrm, if the command isn't idempotent, it might not be a good idea to make this change at all.

**Comment by xiexingguo** [comment]
> Hrm, if the command isn't idempotent, it might not be a good idea to make this change at all.

@liewegas  Fine with me. The meaning part is about the ceph_assert fix and 'ceph config reset 0' anyway.  See https://github.com/ceph/ceph/pull/27155

**Pull request merged**
