### PR TITLE
dpdk: remove redundant dpdk source folder

### PR DESCRIPTION
**Pull request by liu-chunmei**
remove redundant dpdk source folder, this one is not maintained since last Nov.2016,
the other one is located in src/spdk/dpdk, which is alwasy maintained and used by spdk.
so remove this src/dpdk folder, we only need maintain one copy.

Signed-off-by: chunmei <chunmei.liu@intel.com>

### CODE REVIEW

**Comment by tchaikov** [comment]
see also #16997

**Comment by tchaikov** [comment]
https://shaman.ceph.com/builds/ceph/wip-kefu-testing-2017-11-04-1010/

**Comment by liupan1111** [comment]
@liu-chunmei @tchaikov are you sure we could just remove it? Indeed, this dpdk is used by async messenger part, remove it directly may cause compile error when you enable dpdk for async menssenger. In another, the dpdk under spdk/ is not a complete dpdk version, you could find it:
https://github.com/spdk/dpdk/commit/98eca0c61fb03916641b205b71374d94de77f18d#diff-4874d9295f6345b44eb0651ae5aad90d
https://github.com/spdk/dpdk/commit/193a6860dfd84ddad2a72c567480e0dd959724d4#diff-4874d9295f6345b44eb0651ae5aad90d

So @liu-chunmei do you really try async messenger dpdk flow?

**Comment by liu-chunmei** [comment]
@liupan1111 I just test the async/dpdk part  and is going to fix the build and function bug based on spdk/dpdk, anyway if code redundant and not maintained, I think we should remove it.

**Comment by tchaikov** [comment]
the follow-up PR by @liu-chunmei is posted at #18927

**Pull request merged**
