### PR TITLE
octopus: rocksdb: Update to ceph-octopus-v5.8-1436

### PR DESCRIPTION
**Pull request by badone**
We require
https://github.com/facebook/rocksdb/commit/debc4ef18b2e61581ca81dc7fc997b085eb015d9
to build rocksdb_env_librados_test since the bufferlist::copy() method
was removed in c724369

Master was upgraded to v6.8.1 to achieve this but that would be too
potentially risky for a release branch.

Signed-off-by: Brad Hubbard <bhubbard@redhat.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by badone** [comment]
This is part of the resolution to https://tracker.ceph.com/issues/44981

**Comment by smithfarm** [comment]
jenkins test make check

**Comment by badone** [comment]
I can't reproduce the run-rbd-unit-tests-109 failure locally. @dillaman would you mind taking a look?

**Comment by dillaman** [comment]
We see occasional failures w/ no available logs from Jenkins from time-to-time

**Comment by dillaman** [comment]
jenkins test make check

**Comment by yuriw** [comment]
[wip-yuri3-testing-2020-06-01-1942-octopus](https://trello.com/c/sgEs0H7r/924-wip-yuri3-testing-2020-06-01-1942-octopus)

**Pull request merged**
