### PR TITLE
Scrub bug fix

### PR DESCRIPTION
**Pull request by majianpeng**

### CODE REVIEW

**Comment by majianpeng** [comment]
@athanatos . Have you time review this? Thanks!

**Comment by tchaikov** [comment]
looks good to me.

**Comment by tchaikov** [comment]
looks good to me.

**Comment by athanatos** [comment]
This one conflicts with another patch I'm testing, I'll get to it later.

**Comment by athanatos** [comment]
Oops, no it doesn't.

**Comment by majianpeng** [comment]
@athanatos , What's mean ? Could you explain in detail? Thanks!

**Pull request merged**
