### PR TITLE
fix docker-test.sh for CentOS 7

### PR DESCRIPTION
**Pull request by dachary**

### CODE REVIEW

**Comment by dachary** [comment]
@tchaikov would you have time for this pull request ? We need it to reactivate the make check bot on CentOS 7.

**Comment by dachary** [comment]
@tchaikov I rebased and repushed with an updated comment that has a link to the suite for clarity : https://github.com/ceph/ceph-qa-suite/tree/master/suites/ceph-disk

**Comment by tchaikov** [comment]
tested. and lgtm

**Comment by dachary** [comment]
@tchaikov thanks :-)

**Pull request merged**
