### PR TITLE
nautilus: common: Clang requires a default constructor, but it can be empty

### PR DESCRIPTION
**Pull request by dillaman**
http://tracker.ceph.com/issues/39573

### CODE REVIEW

**Comment by dillaman** [comment]
retest this please

**Comment by smithfarm** [comment]
`131/171 Test   #4: smoke.sh ................................***Failed  329.15 sec`

**Comment by dillaman** [comment]
Unrelated

**Comment by dillaman** [comment]
retest this please

**Comment by dillaman** [comment]
retest this please

**Comment by smithfarm** [comment]
This time it's the dashboard unit tests that are failing:

```
121/171 Test #127: mgr-dashboard-smoke.sh ..................***Failed  166.84 sec
Enivronment Variables Already Set
stty: standard input: Inappropriate ioctl for device
[test log follows]
```

@ricardoasmarques Can you take a look?

**Comment by smithfarm** [comment]
(please note that the same failure is happening on other nautilus PRs - e.g. https://github.com/ceph/ceph/pull/28064 - so it's not related to the content of this PR; it's an issue with the testing environment)

**Comment by ricardoasmarques** [comment]
jenkins test make check

**Comment by smithfarm** [comment]
@ricardoasmarques It will eventually succeed if we keep re-triggering it, yes. But it sure would be nice if it could be analyzed and the root cause found and fixed.

**Comment by ricardoasmarques** [comment]
@smithfarm I don't think this is dashboard related, I've seen the same error on other PRs, different script.

For instance, on https://github.com/ceph/ceph/pull/28191:

```
125/171 Test   #4: smoke.sh ................................***Failed  259.41 sec
stty: standard input: Inappropriate ioctl for device
```

**Comment by smithfarm** [comment]
This time, the failure is `./do_cmake.sh: 9: ./do_cmake.sh: source: not found` - I have a fix for this open at https://github.com/ceph/ceph/pull/28181

**Comment by smithfarm** [comment]
jenkins re-test this please

**Comment by yuriw** [comment]
[wip-yuri3-testing-2019-06-14-1440-nautilus](https://trello.com/c/217ldlvH/642-wip-yuri3-testing-2019-06-14-1440-nautilus)

**Pull request merged**
