### PR TITLE
cmake: librbd cleanup

### PR DESCRIPTION
**Pull request by tchaikov**

### CODE REVIEW

**Comment by dillaman** [comment]
lgtm

**Comment by dillaman** [comment]
Not sure if this is related, but going to pull this PR from my branch and attempt a rebuild:
http://gitbuilder.sepia.ceph.com/gitbuilder-ceph-deb-jessie-amd64-basic/log.cgi?log=d1a162e6c065b105eb386657751b9a15e62b6ef7

**Comment by tchaikov** [comment]
```
cd "/srv/autobuild-ceph/gitbuilder.git/build/out~/ceph-11.0.2-1391-gd1a162e/src/pybind/rbd" && env CC=" /usr/bin/cc" CXX=" /usr/bin/c++" LDSHARED=" /usr/bin/cc -shared" OPT="-DNDEBUG -g -fwrapv -O2 -Wall" LDFLAGS=-L/srv/autobuild-ceph/gitbuilder.git/build/out~/ceph-11.0.2-1391-gd1a162e/obj-x86_64-linux-gnu/lib CYTHON_BUILD_DIR=/srv/autobuild-ceph/gitbuilder.git/build/out~/ceph-11.0.2-1391-gd1a162e/obj-x86_64-linux-gnu/src/pybind/rbd3 CEPH_LIBDIR=/srv/autobuild-ceph/gitbuilder.git/build/out~/ceph-11.0.2-1391-gd1a162e/obj-x86_64-linux-gnu/lib CFLAGS="-iquote/srv/autobuild-ceph/gitbuilder.git/build/out~/ceph-11.0.2-1391-gd1a162e/src/include" /usr/bin/python3 /srv/autobuild-ceph/gitbuilder.git/build/out~/ceph-11.0.2-1391-gd1a162e/src/pybind/rbd/setup.py build --verbose --build-base /srv/autobuild-ceph/gitbuilder.git/build/out~/ceph-11.0.2-1391-gd1a162e/obj-x86_64-linux-gnu/lib/cython_modules --build-platlib /srv/autobuild-ceph/gitbuilder.git/build/out~/ceph-11.0.2-1391-gd1a162e/obj-x86_64-linux-gnu/lib/cython_modules/lib.3
/srv/autobuild-ceph/gitbuilder.git/build/out~/ceph-11.0.2-1391-gd1a162e/obj-x86_64-linux-gnu/lib/librbd.so: undefined reference to `ceph_str_hash_linux(char const*, unsigned int)'
/srv/autobuild-ceph/gitbuilder.git/build/out~/ceph-11.0.2-1391-gd1a162e/obj-x86_64-linux-gnu/lib/librbd.so: undefined reference to `ceph::time_detail::real_clock::now(CephContext const*)'
error: collect2: ld returned 1 exit status
Error: Link RBD library not found
src/pybind/rbd3/CMakeFiles/cython3_rbd.dir/build.make:52: recipe for target 'src/pybind/rbd3/CMakeFiles/cython3_rbd' failed
make[4]: *** [src/pybind/rbd3/CMakeFiles/cython3_rbd] Error 1
```

**Comment by tchaikov** [comment]
fixed and re-pushed to ceph/ceph:wip-cmake.

**Pull request merged**
