### PR TITLE
Rgw keystone v3

### PR DESCRIPTION
**Pull request by lperiquito**
We've improved the current rgw to support authv3 using keystone.

Rather than introduce a factory and inheritance of the keystone token structure, the token now accommodates both formats and the parser populates the relevant structure dependent on the version of the API and then normalises it to the v3 layout, which uses project rather than tenant. 

As for documentation there are new options in ceph.conf

rgw keystone api version = \[ 2.0 / 3 \] ( default = 2.0 )

For admin authentication without a token, the following is required

rgw keystone admin domain = acme.org
rgw keystone admin project = project_name

### CODE REVIEW

**Comment by yehudasa** [comment]
@lperiquito I commented on the original PR here: https://github.com/ocadotechnology/ceph/commit/459a0e7e64cbb15fbff1cd87d5ad2e06044c746e#commitcomment-13947564
Note that it'll be easier for me to review changes if you don't squash your incremental changes following the review, and keep working on the same pull request.

**Comment by jmlowe** [comment]
If I read this correctly the default value for all of the domain settings is "", to match the behavior of the rest of openstack it should probably be "default".

**Comment by MartinHoustonOccado** [comment]
It seems that the structure of the code around rgw_keystone has bee re factored quite significantly since the branch where the v3 was developed was split several months ago. The structure of the KeystoneToken object is quite different and a direct merge with current head looks messy. Could someone familiar with the way the code has been re-factored assist please? The current head code has no reference to protocol version within the object in it yet so unless this is automagic (i.e. the work has been done) we will still need to get this merged to allow Keystone V3 support.

**Comment by yehudasa** [comment]
@MartinHoustonOccado take a look at PR #7539

**Comment by yehudasa** [comment]
keystone v3 (based on this PR, and another one) merged here: https://github.com/ceph/ceph/pull/7719

**Pull request closed without merging**
