### PR TITLE
hammer: rgw: user quota may not adjust on bucket removal

### PR DESCRIPTION
**Pull request by Vicente-Cheng**
http://tracker.ceph.com/issues/15023

### CODE REVIEW

**Comment by dachary** [comment]
<pre>
 CXX      rgw/librgw_la-rgw_tools.lo
rgw/rgw_bucket.cc: In function 'int rgw_remove_bucket(RGWRados*, const string&, rgw_bucket&, bool)':
rgw/rgw_bucket.cc:436:50: error: 'struct rgw_bucket' has no member named 'tenant'
   ret = rgw_bucket_sync_user_stats(store, bucket.tenant, bucket.name);
                                                  ^
</pre>

**Comment by dachary** [comment]
https://github.com/ceph/ceph/pull/8113/commits/5c5f206fa409b9857aad835bfc2c523dabc0c57a changes the order of delete_bucket and rgw_bucket_sync_user_stats which the original commit did not https://github.com/ceph/ceph/commit/06507992e3fad837c4667f467d59fc026a2ca0e8. Is there a reason for that ?

**Comment by Vicente-Cheng** [comment]
@dachary thanks for reminder. Already corrected

**Comment by dachary** [comment]
@Vicente-Cheng http://tracker.ceph.com/issues/15023#note-5 shows the conflict resolution was done in a minimal way and matches the conflict resolution comment. :+1:

**Pull request merged**
