### PR TITLE
librbd: fix regression in object map diff request

### PR DESCRIPTION
**Pull request by trociny**
(when testing for fast-diff feature enabled)

Fix: https://tracker.ceph.com/issues/48412
Signed-off-by: Mykola Golub <mgolub@suse.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by trociny** [comment]
@dillaman Making fast-diff work revealed an issue with deep copy. Now deep copy tests fail when copying to an image with different object size. 

I think the problem is in ImageCopyRequest.cc  [1]. In `send_next_object_copy` as an object number we use destination image object number, but when deciding if we can skip to copy this object based on fast-diff results, we use is as an src object number.

The fix could be to map `ono` (the destination object number) to the src object(s) and test `m_object_diff_state` against this (these) object(s). I am going to try this.

[1] https://github.com/ceph/ceph/blob/master/src/librbd/deep_copy/ImageCopyRequest.cc#L163
[2] https://github.com/ceph/ceph/blob/master/src/librbd/deep_copy/ImageCopyRequest.cc#L150

**Review by dillaman — APPROVED** [review]
great catch -- lgtm

**Comment by dillaman** [comment]
jenkins test make check

**Comment by dillaman** [comment]
jenkins test make check

**Comment by dillaman** [comment]
jenkins test make check

**Comment by dillaman** [comment]
unrelated unit test failure [1]:

```
[ RUN      ] TestLibRBD.ConcurentOperations
using new format!
/home/jenkins-build/build/workspace/ceph-pull-requests/src/common/mutex_debug.h: In function 'void ceph::mutex_debug_detail::mutex_debug_impl<<anonymous> >::_post_lock() [with bool Recursive = false]' thread 7fe9b9b0f700 time 2020-12-03T15:05:20.141264+0000
/home/jenkins-build/build/workspace/ceph-pull-requests/src/common/mutex_debug.h: 153: FAILED ceph_assert(nlock == 0)
 ceph version Development (no_version) pacific (dev)
 1: (ceph::__ceph_assert_fail(char const*, char const*, int, char const*)+0x19d) [0x7fe9d5a9f173]
 2: /home/jenkins-build/build/workspace/ceph-pull-requests/build/lib/libceph-common.so.2(+0x163f3f5) [0x7fe9d5a9f3f5]
 3: (ceph::mutex_debug_detail::mutex_debug_impl<false>::_post_lock()+0x24) [0x56112bc939cc]
 4: (ceph::mutex_debug_detail::mutex_debug_impl<false>::try_lock(bool)+0x54) [0x56112bc938c2]
 5: (ceph::mutex_debug_detail::mutex_debug_impl<false>::lock(bool)+0x4a) [0x56112bc79c0e]
 6: (std::lock_guard<ceph::mutex_debug_detail::mutex_debug_impl<false> >::lock_guard(ceph::mutex_debug_detail::mutex_debug_impl<false>&)+0x2f) [0x56112bc75d9f]
 7: (librbd::TaskFinisher<librbd::ImageWatcher<librbd::ImageCtx>::Task>::complete(librbd::ImageWatcher<librbd::ImageCtx>::Task const&)+0x3f) [0x56112d2c87bb]
 8: (librbd::TaskFinisher<librbd::ImageWatcher<librbd::ImageCtx>::Task>::C_Task::finish(int)+0x2a) [0x56112d2c84ce]
 9: (Context::complete(int)+0x27) [0x56112bc63f3d]
 10: (Finisher::finisher_thread_entry()+0x39d) [0x7fe9d59fe6b7]
 11: (Finisher::FinisherThread::entry()+0x1c) [0x56112d292ca0]
 12: (Thread::entry_wrapper()+0x83) [0x7fe9d5a60031]
 13: (Thread::_entry_func(void*)+0x18) [0x7fe9d5a5ffa4]
 14: /lib/x86_64-linux-gnu/libpthread.so.0(+0x76db) [0x7fe9df2cc6db]
 15: clone()
/home/jenkins-build/build/workspace/ceph-pull-requests/src/test/run-rbd-unit-tests.sh: line 20: 24074 Aborted                 (core dumped) RBD_FEATURES=$i unittest_librbd
```

[1] https://jenkins.ceph.com/job/ceph-pull-requests/65014/

**Comment by dillaman** [comment]
jenkins test make check

**Comment by dillaman** [comment]
Hmm -- `TestLibRBD.ConcurentOperations` is now just timing out

**Comment by trociny** [comment]
> Hmm -- TestLibRBD.ConcurentOperations is now just timing out

looking at it

**Comment by dillaman** [comment]
jenkins test make check

**Pull request merged**
