### PR TITLE
quincy: mgr/dashboard: rbd-mirror batch backport

### PR DESCRIPTION
**Pull request by pereman2**
backport tracker: https://tracker.ceph.com/issues/55753, https://tracker.ceph.com/issues/55920, https://tracker.ceph.com/issues/56032

---

backport of #46249, #46263, #46433, #46512, #46639, #46527, #46733, https://github.com/ceph/ceph/pull/46407
parent tracker: https://tracker.ceph.com/issues/55645, https://tracker.ceph.com/issues/55648, https://tracker.ceph.com/issues/42109

this backport was staged using ceph-backport.sh version 16.0.0.6848
find the latest version at https://github.com/ceph/ceph/blob/master/src/script/ceph-backport.sh

### CODE REVIEW

**Comment by pereman2** [comment]
jenkins test make check

**Comment by pereman2** [comment]
jenkins test dashboard cephadm

**Comment by pereman2** [comment]
jenkins test api

**Comment by pereman2** [comment]
jenkins retest this please

**Comment by nizamial09** [comment]
jenkins retest this please

**Comment by nizamial09** [comment]
jenkins retest this please

**Comment by nizamial09** [comment]
accidental click on the close button :)

**Comment by pereman2** [comment]
jenkins retest this please

**Review by nizamial09 — APPROVED** [review]

**Review by aaSharma14 — APPROVED** [review]

**Pull request merged**
