### PR TITLE
udev: remove 60-ceph-partuuid-workaround-rules

### PR DESCRIPTION
**Pull request by liewegas**
These were added to get /dev/disk/by-partuuid/ symlinks to work on
wheezy.  They are no longer needed for the supported distros (el7+,
jessie+, trusty+), and they apparently break dm by opening devices they
should not.

Signed-off-by: Sage Weil <sage@redhat.com>

### CODE REVIEW

**Comment by smithfarm** [comment]
Please add `Fixes: http://tracker.ceph.com/issues/15516` to the commit description.

**Comment by dachary** [comment]
<pre>
Reviewed-by: Loic Dachary &lt;ldachary@redhat.com>
</pre>

**Comment by oms4suse** [comment]
This codes is currently packaged in SUSE.

Please give me at least a day to build this for SUSE. as it will take me some time to test this for side effects.

**Comment by oms4suse** [comment]
Seems to cause no issues for my salt install on SUSE, or the crowbar install.

**Comment by smithfarm** [comment]
Yay! I love getting rid of old cruft.

```
Reviewed-by: Nathan Cutler <ncutler@suse.com>
```

**Pull request merged**
