### PR TITLE
common/buffer.cc: cleanup

### PR DESCRIPTION
**Pull request by stiopaa1**
Signed-off-by: Michal Jarzabek <stiopa@gmail.com>

### CODE REVIEW

**Comment by dachary** [comment]
@stiopaa1 the problem with such cleanups is that it makes backporing or comparing files more difficult, which is a lot more annoying that the aesthetic of the code. I hope you understand the rationale.

**Comment by stiopaa1** [comment]
How do you improve the quality of the code then?

**Comment by dachary** [comment]
@stiopaa1 whenever the code changes for other reasons (fixing a bug, adding a feature), we take the opportunity to improve style. It improves slowly and steadily ;-)

**Comment by stiopaa1** [comment]
What if I changed particular part of code in every version we are backporting to? Would that be acceptable?

**Comment by dachary** [comment]
That's the idea, yes. Would you mind closing this pull request ? It will be kept in the history and can conveniently be referenced to later for cleanup purposes.

**Pull request closed without merging**
