### PR TITLE
crimson: seastar modification for alien store

### PR DESCRIPTION
**Pull request by liu-chunmei**
let alien puller works when smp = 1
let release build use seastar default allocator for alien store

Signed-off-by: chunmei-liu <chunmei.liu@intel.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by liu-chunmei** [comment]
@tchaikov  I can't create seastar PR for ceph, could you please manually merger this seastar patch for alien store, otherwise alien store will can't work. 

commit a80492cb79b90b9cfd8204f5fdfd0d4dedeb2281 (HEAD -> seastar_for_alien_store)
Author: chunmei-liu <chunmei.liu@intel.com>
Date:   Thu Mar 5 14:35:31 2020 -0800

    crimson:for alien store

    let alien store puller works when smp=1
    let release version work with seastar default allocator.

    Signed-off-by: chunmei-liu <chunmei.liu@intel.com>

diff --git a/CMakeLists.txt b/CMakeLists.txt
index c84a66f5..e7c9f464 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -901,6 +901,14 @@ if ((CMAKE_BUILD_TYPE STREQUAL "Dev") OR (CMAKE_BUILD_TYPE STREQUAL "Debug"))
       SEASTAR_TYPE_ERASE_MORE)
 endif ()

+if (WITH_BLUESTORE)
+  if (CMAKE_BUILD_TYPE STREQUAL "RelWithDebInfo")
+    target_compile_definitions (seastar
+      PUBLIC
+        SEASTAR_DEFAULT_ALLOCATOR)
+  endif ()
+endif ()
+
 target_compile_definitions (seastar
   PRIVATE ${Seastar_PRIVATE_COMPILE_DEFINITIONS})

diff --git a/src/core/reactor.cc b/src/core/reactor.cc
index 554bf83f..5e6441c2 100644
--- a/src/core/reactor.cc
+++ b/src/core/reactor.cc
@@ -2557,9 +2557,7 @@ int reactor::run() {
     // 5. kernel submission: for I/O, will submit what was generated from last step.
     // 6. reap kernel events completion: some of the submissions from last step may return immediately.
     //                                   For example if we are dealing with poll() on a fd that has events.
-    if (smp::count > 1) {
-        smp_poller = poller(std::make_unique<smp_pollfn>(*this));
-    }
+    smp_poller = poller(std::make_unique<smp_pollfn>(*this));

     poller reap_kernel_completions_poller(std::make_unique<reap_kernel_completions_pollfn>(*this));
     poller io_queue_submission_poller(std::make_unique<io_queue_submission_pollfn>(*this));

**Comment by tchaikov** [comment]
regarding to https://github.com/ceph/ceph/pull/31041#issuecomment-593606911, i don't think we are talking about a "special case". if you are reluctant to do this. i will send the patch instead. to fork seastar would be the last resort.

**Comment by liu-chunmei** [comment]
> regarding to #31041 (comment), i don't think we are talking about a "special case". if you are reluctant to do this. i will send the patch instead. to fork seastar would be the last resort.

@tchaikov seastar has allocator solution for alien world. but not merged in. do you think we need adopt it or just use default allocator? 
https://github.com/elazarl/seastar/tree/alien-allocator

I will find a way to initialize alien puller when smp =1.

**Comment by tchaikov** [comment]
> > regarding to #31041 (comment), i don't think we are talking about a "special case". if you are reluctant to do this. i will send the patch instead. to fork seastar would be the last resort.
> 
> @tchaikov seastar has allocator solution for alien world. but not merged in. do you think we need adopt it or just use default allocator?
> https://github.com/elazarl/seastar/tree/alien-allocator

this is a different story. i thought we were discussing the smp=1 issue. regarding to the libc allocator versus seastar lockless allocator issue, IMHO, it's of lower priority. we just need to keep in mind that, if we want to have better performance when using alienized bluestore, we have the option to continue working on the alien-allocator branch. but at this moment, i think seastore and crimson are more important.

> 
> already has a patch for smp=1 start alien poller, see below discussion, I am asking if they will merge it.
> https://groups.google.com/forum/#!searchin/seastar-dev/alien$20poller%7Csort:date/seastar-dev/J8urU7q4mI0/ulMkVApYEQAJ

thanks!

**Pull request closed without merging**
