### PR TITLE
test: check daemon is alive or not agagin when sleep 60s

### PR DESCRIPTION
**Pull request by XinzeChi**
@dachary , I think this code does not follow your means.

Signed-off-by: Xinze Chi <xmdxcxz@gmail.com>

### CODE REVIEW

**Comment by dachary** [comment]
@XinzeChi could you explain the reason for this change ? I must be missing something :-)

**Comment by XinzeChi** [comment]
@dachary, your comment about this code:
#  0 1 1 1 2 3 5 5 5 10 10 20 60
#
# This sequence is designed to not require a sleep time (0) if the
# machine is fast enough and the daemon terminates in a fraction of a
# second. The increasing sleep numbers should give plenty of time for
# the daemon to die even on the slowest running machine. If a daemon
# takes more than two minutes to stop (the sum of all sleep times),

But after sleep 60s, you do not check the daemon again.

**Comment by dachary** [comment]
Oh! you're absolutely right, nice catch :-) For clarity could you set 
<pre>
0 0 1 1 1 2 3 5 5 5 10 10 20 60
</pre>
that is the 0 at the beginning, and move the sleep from the end of the for loop to the beginning of the for loop ?

**Comment by tchaikov** [comment]
@XinzeChi i think the first `0` is for the fast machine which is able to shut the daemon down in a jiffy. so i think @dachary 's comment is accurate.

**Comment by XinzeChi** [comment]
@dachary , kefu's comment is what I mean.

**Comment by dachary** [comment]
@XinzeChi the last minute is not wasted if the sleep is moved at the beginning of the for loop and the zero is at the start of the list. When maintaining the code **0 0 1 1 1 2 3 5 5 5 10 10 20 60** looks (and is indeed) straightforward to understand. If we have **0 1 1 1 2 3 5 5 5 10 10 20 60 0** (which would work without changing where the sleep is in the loop), it will look quite mysterious to the code reader who will ask her/himself : "hum, what's that last 0 about ?".

**Comment by XinzeChi** [comment]
@dachary , repush code, Please review.

**Comment by tchaikov** [comment]
:+1:

**Pull request merged**
