### PR TITLE
ceph-volume: add some flexibility to bytes_to_extents

### PR DESCRIPTION
**Pull request by jan--f**
For batch we want to report the projected sizes before creating any LVM
structures, we use the device size for that. This means we pass this
projected size to lvm/api.py::create_lv. This could result in situations
where we request more extents for the new LV than are actually
available, as LVM takes up some available space on the block device
(plus alignment).
We fix this by adjusting the extent count downwards if its less than 1% off the
requested value.

Fixes: https://tracker.ceph.com/issues/47758

Signed-off-by: Jan Fajerski <jfajerski@suse.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by jan--f** [comment]
jenkins test ceph-volume all

**Comment by jan--f** [comment]
jenkins test ceph-volume tox

**Comment by jan--f** [comment]
jenkins test ceph-volume all

**Comment by jan--f** [comment]
jenkins test ceph-volume tox

**Comment by jan--f** [comment]
jenkins test ceph-volume all

**Comment by jan--f** [comment]
jenkins test ceph-volume tox

**Comment by kmhughes** [comment]
I really need this to be able to use the SSDs in my cluster. Any thoughts on when this will be released, if ever?

**Comment by jan--f** [comment]
> I really need this to be able to use the SSDs in my cluster. Any thoughts on when this will be released, if ever?

Yes, we need at least a review on this though. @jmolmo @guits @rishabh-d-dave ?

**Comment by lordzkin** [comment]
I have used the same fixes in my setup here where I pass through physical
spinning disks in oVirt to the virtual machines in order to have the OSDs
virtualized.  Thanks for putting in the work Jan.

**Comment by jan--f** [comment]
> > I really need this to be able to use the SSDs in my cluster. Any thoughts on when this will be released, if ever?
> 
> Yes, we need at least a review on this though. @jmolmo @guits @rishabh-d-dave ?

ping again. I no one willing to review this?

**Comment by kmhughes** [comment]
Yes, could we please get a review on this!

**Review by jmolmo — APPROVED** [review]

**Comment by jmolmo** [comment]
> ing to review this?

**Comment by kmhughes** [comment]
Awesome! Thanks for the approval! Time to get some SSDs in my cluster!

**Comment by DWSR** [comment]
@jan--f looks like this is failing some tests

**Comment by jan--f** [comment]
> @jan--f looks like this is failing some tests

That's just an intermittent infrastructure issue.

**Pull request merged**
