### PR TITLE
mon/PGMap: remove or narrow columns 'pg ls' output

### PR DESCRIPTION
**Pull request by liewegas**
I think the removals are uncontroversial.

I'm not sure about the duplicate PRI columns, though.  Perhaps we don't need up_primary at all?

### CODE REVIEW

**Comment by jcsp** [comment]
Having two "PRI" columns with the same name is a bit weird, I wonder if we could remove the need for those columns at all with a convention that the OSDs in the UP and ACTING columns always have the primary first, if they don't already?

**Comment by liewegas** [comment]
It's normally true for replicated PGs, but not for EC ones.

The operator<< in the OSD debug code print something like "[1,2,3]p2" (for ec pool soly)... we could use the same syntax here and stick it in the up/acting columns?  It's a bit less clean but more compact.

**Comment by jcsp** [comment]
Since this output is already pretty low level stuff, that compact form should be a good fit.

If we have two columns with the same name there is a risk it might bug me forever :-D

**Comment by liewegas** [comment]
retest this please

**Comment by liewegas** [comment]
@jcsp ping

**Comment by liewegas** [comment]
http://pulpito.ceph.com/sage-2018-04-17_04:17:03-rados-wip-sage3-testing-2018-04-16-2028-distro-basic-smithi/

**Pull request merged**
