### PR TITLE
rgw: DPP addition 4

### PR DESCRIPTION
**Pull request by TRYTOBE8TME**
## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by TRYTOBE8TME** [comment]
jenkins test docs

**Comment by TRYTOBE8TME** [comment]
jenkins render docs

**Comment by alimaredia** [comment]
@TRYTOBE8TME any update on this?

**Comment by TRYTOBE8TME** [comment]
There were many failures on master due which I'm waiting just to ensure that nothing conflicting from this branch goes in.
@alimaredia would it be a correct time to schedule a run now?

**Comment by TRYTOBE8TME** [comment]
Teuthology run: https://pulpito.ceph.com/kapandya-2021-09-23_16:02:07-rgw-wip-rgw-dpp-3-distro-basic-smithi/

**Comment by alimaredia** [comment]
jenkins retest

**Comment by TRYTOBE8TME** [comment]
jenkins retest

**Comment by TRYTOBE8TME** [comment]
jenkins retest this please

**Review by alimaredia — APPROVED** [review]

**Pull request merged**
