### PR TITLE
common,osdc: remove atomic_t completely

### PR DESCRIPTION
**Pull request by tchaikov**

### CODE REVIEW

**Comment by tchaikov** [comment]
@chardan guess it's the final nail in the coffin of `atomic_t` in ceph.

**Comment by joscollin** [comment]
@tchaikov 
/home/jenkins-build/build/workspace/ceph-pull-requests/src/journal/JournalRecorder.h:8:28: fatal error: include/atomic.h: No such file or directory

**Comment by tchaikov** [comment]
@joscollin fixed in latest version.

**Comment by chardan** [comment]
Whew!! :-)

**Comment by liewegas** [comment]
http://pulpito.ceph.com/sage-2017-06-08_20:27:41-rados-wip-sage-testing2-distro-basic-smithi/

**Pull request merged**
