### PR TITLE
pacific: ceph.spec.in: add support for openEuler OS

### PR DESCRIPTION
**Pull request by liuqinfei**
Currently, as the openEuler OS has been used by more and more people. Users expect Ceph to support the compilation on the openEuler.

Signed-off-by: liuqinfei <liuqinfei5@hisilicon.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by jianwei1216** [comment]
Can openEuler support the ceph main branch now? @liuqinfei

**Comment by kevinzs2048** [comment]
Some info about opeEuler, here is the link: https://www.openeuler.org/en/, hope that can help.

OpenEuler is now a very active and popular operation system community. It is based on RPM and all the packages are built from source. openEuler now attracted a lot of end users and developers, especially in China. Actually some companies are already has some trial deployment cluster for Ceph on openEuler. 

The openEuler LTS version is 22.03. openEuler has an SDS-sig, in this sig we've co-work together with many companies to promote the RPM release, including Ceph, Lustre, DAOS, etc. Besides, there are some validation for Ceph + Openstack deployment validation. So from the variety of the Ceph upstream, it's better to support openEuler build in the master branch.

**Comment by kevinzs2048** [comment]
And any questions, problems and concerns about this topic are welcome. Thanks!

**Comment by liuqinfei** [comment]
> Can openEuler support the ceph main branch now? @liuqinfei

The openEuler has support ceph16.2.7 on openEuler22.03LTS. The main difference is support openEuler in the spec. You can find that in the 'file changed'.
I have checked the spec file on ceph main branch and see some new changes. So i just submit the pull request to the pacific branch.

**Comment by fantastic2085** [comment]
openEuler OS is used a lot, so Ceph is necessary to run on it

**Comment by Svelar** [comment]
openEuler is widely applied nowadays, look forward to support it soon.

**Comment by idryomov** [comment]
> > Can openEuler support the ceph main branch now? @liuqinfei
> 
> The openEuler has support ceph16.2.7 on openEuler22.03LTS. The main difference is support openEuler in the spec. You can find that in the 'file changed'. I have checked the spec file on ceph main branch and see some new changes. So i just submit the pull request to the pacific branch.

The usual process for most changes is for the PR to be submitted against main branch first.  Then, after it lands, backport PRs are opened against stable branches (currently pacific and quincy are active) with a reference to the original PR.  This is followed even if the backport is not a straight cherry-pick -- the general rule is that a corresponding change must be in main to avoid regressions.

**Comment by liuqinfei** [comment]
> > > Can openEuler support the ceph main branch now? @liuqinfei
> > 
> > 
> > The openEuler has support ceph16.2.7 on openEuler22.03LTS. The main difference is support openEuler in the spec. You can find that in the 'file changed'. I have checked the spec file on ceph main branch and see some new changes. So i just submit the pull request to the pacific branch.
> 
> The usual process for most changes is for the PR to be submitted against main branch first. Then, after it lands, backport PRs are opened against stable branches (currently pacific and quincy are active) with a reference to the original PR. This is followed even if the backport is not a straight cherry-pick -- the general rule is that a corresponding change must be in main to avoid regressions.

ok, i will update a new pull request to main branch later.

**Comment by liuqinfei** [comment]
> > > Can openEuler support the ceph main branch now? @liuqinfei
> > 
> > 
> > The openEuler has support ceph16.2.7 on openEuler22.03LTS. The main difference is support openEuler in the spec. You can find that in the 'file changed'. I have checked the spec file on ceph main branch and see some new changes. So i just submit the pull request to the pacific branch.
> 
> The usual process for most changes is for the PR to be submitted against main branch first. Then, after it lands, backport PRs are opened against stable branches (currently pacific and quincy are active) with a reference to the original PR. This is followed even if the backport is not a straight cherry-pick -- the general rule is that a corresponding change must be in main to avoid regressions.

I have submitted a new PR against the main branch. Please review. Thank you. [PR 50301](https://github.com/ceph/ceph/pull/50301)

**Pull request closed without merging**
