### PR TITLE
osd: Fix compilation warnings for PR https://github.com/ceph/ceph/pull/55198

### PR DESCRIPTION
**Pull request by JoshSalomon**
Fix compilation warnings for PR https://github.com/ceph/ceph/pull/55198

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [x] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Comment by JoshSalomon** [comment]
@cbodley - I don't see any warnings now (but I didn't see them before either) - does this PR complete without warning?
@ljflores - Can you build it in a container with Casey's environment?

**Review by ljflores — COMMENTED** [review]
Hey @JoshSalomon, I still see one warning on the branch:
```
[80/136] Building CXX object src/CMakeFiles/common-objs.dir/osd/OSDMap.cc.o
/root/ceph/src/osd/OSDMap.cc: In member function ‘int OSDMap::calc_rbs_size_optimal(ceph::common::CephContext*, OSDMap&, int64_t, const pg_pool_t*, read_balance_info_t&) const’:
/root/ceph/src/osd/OSDMap.cc:6589:22: warning: comparison of integer expressions of different signedness: ‘int’ and ‘long unsigned int’ [-Wsign-compare]
 6589 |   for (int i = 0 ; i < num_osds ; i++) {
      |                    ~~^~~~~~~~~~
```

Steps to reproduce:
- `podman pull fedora:39`
- `podman run -it fedora:39`
- Clone ceph repository and install dependencies as usual
- In build directory, `ninja osd`

**Comment by cbodley** [comment]
> Steps to reproduce:

all of the shaman builds in https://shaman.ceph.com/builds/ceph/wip-lflores-testing-2024-01-29-0542/ showed these warnings if you're having trouble reproducing them locally

**Comment by ljflores** [comment]
> > Steps to reproduce:
> 
> all of the shaman builds in https://shaman.ceph.com/builds/ceph/wip-lflores-testing-2024-01-29-0542/ showed these warnings if you're having trouble reproducing them locally

Yeah, I did your env first, but I was also able to reproduce this on my centos 8 stream setup.

**Comment by JoshSalomon** [comment]
@ljflores 
I could not build the project in a container, the install_deps crashed on my laptop - I fixed the problem and it did not produce errors on my compile, but I am working with clang and not with GCC.
Can you verify that no warning exist as a result of the read balancer PR?

**Review by ljflores — APPROVED** [review]

**Comment by ljflores** [comment]
I don't see any more warnings. Let's send it to QA

**Pull request merged**
