### PR TITLE
ceph-osd-prestart.sh: check existence of OSD data directory

### PR DESCRIPTION
**Pull request by smithfarm**
Fixes: http://tracker.ceph.com/issues/17091
Signed-off-by: Nathan Cutler <ncutler@suse.com>

### CODE REVIEW

**Comment by smithfarm** [comment]
@ddiss Care to review?

**Comment by ddiss** [comment]
LGTM :+1:

**Comment by b-ranto** [comment]
lgtm as well.

**Comment by ktdreyer** [comment]
Thank you!

**Pull request merged**
