### PR TITLE
os/bluestore: assign nid for newly created onode

### PR DESCRIPTION
**Pull request by xiexingguo**

### CODE REVIEW

**Comment by xiexingguo** [comment]
It seems these failure noises from iBot are true...
```
=====================================
   ceph 10.0.2: src/test-suite.log
=====================================

# TOTAL: 134
# PASS:  133
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: test/mon/mon-created-time.sh
==================================

../test-driver: line 95: ./test/mon/mon-created-time.sh: Permission denied  
```

**Comment by xiexingguo** [comment]
Dear @ldachary  , do you mind checking the above failure? Thanks:)

**Comment by xiexingguo** [comment]
Append more fixes.

**Comment by tchaikov** [comment]
@xiexingguo @dachary the test failure is addressed by #7538.

**Comment by xiexingguo** [comment]
@tchaikov  :+1:  Thanks for ack and wish you Happy New Year:)

**Pull request merged**
