### PR TITLE
Fix unicode encoding for non-ASCII characters in title and author names

### PR DESCRIPTION
**Pull request by Abhishekvrshny**
Signed-off-by: Abhishek Varshney <abhishek.varshney@flipkart.com>
Reviewed-by: Loic Dachary <loic@dachary.org>

### CODE REVIEW

**Comment by dachary** [comment]
@Abhishekvrshny would you mind contributing this to https://github.com/dachary/ceph/tree/wip-release-notes ? I'll merge it right away and it will be part of https://github.com/ceph/ceph/pull/7689

**Comment by Abhishekvrshny** [comment]
@dachary Here you go: https://github.com/dachary/ceph/pull/7 .

**Comment by dachary** [comment]
@Abhishekvrshny thanks !

**Comment by dachary** [comment]
part of https://github.com/ceph/ceph/pull/7689 now

**Pull request closed without merging**
