### PR TITLE
osd/ReplicatedPG: for getattr_maybe_cache, it never return -EEXIST.

### PR DESCRIPTION
**Pull request by majianpeng**
Signed-off-by: Jianpeng Ma <jianpeng.ma@intel.com>

### CODE REVIEW

**Comment by majianpeng** [comment]
@ukernel .  Have you time to review those patches? Thanks!

**Comment by majianpeng** [comment]
@ukernel . Ping.

**Comment by majianpeng** [comment]
@ukernel . Ping!

**Comment by majianpeng** [comment]
@jcsp. Have you time to review this? Thanks!

**Comment by majianpeng** [comment]
@liewegas . Have you time to review this? Thanks very much!

**Comment by liewegas** [comment]
@majianpeng sorry for the slow reply--we're focusing on stabilizing infernalis.  adding this to my list

**Comment by majianpeng** [comment]
@ukernel . updated and please review again.  Other question: why keep create operation in cephfs client? What's the mean of talk w/ old osd? Thanks!

**Comment by liewegas** [comment]
@ukernel is this ready for needs-qa?

**Pull request merged**
