### PR TITLE
qa/rgw: combine swift, s3tests, ragweed into single verify task

### PR DESCRIPTION
**Pull request by cbodley**
these tests don't need to be split across the job matrix the same way that we split features like frontend, ssl, objectstore, etc. by combining them, we can still test the whole matrix of features, but with only 1/3 of the total jobs

### CODE REVIEW

**Comment by vasukulkarni** [comment]
Really nice to see the matrix reduced!

**Comment by cbodley** [comment]
reduces the current rgw suite from 377 to 249 jobs

**Comment by yuriw** [comment]
[wip-yuri3-testing-2018-03-06-2056](https://trello.com/c/gkIitMRd/272-wip-yuri3-testing-2018-03-06-2056)

**Comment by cbodley** [comment]
@yuriw sorry, it looks like this pr was causing a lot of failures. i pushed an update and have a test started at http://pulpito.ceph.com/cbodley-2018-03-07_14:23:13-rgw-wip-cbodley-testing-distro-basic-smithi/

**Comment by yuriw** [comment]
[wip-yuri3-testing-2018-03-07-1524](https://trello.com/c/gkIitMRd/272-wip-yuri3-testing-2018-03-07-1524)

**Comment by vasukulkarni** [comment]
we could just test this standalone with small subset and merge this fast, @cbodley if the single test has passed as I see in your logs we can merge this, there is nothing more to do than that right?

**Pull request merged**
