### PR TITLE
check for nosetests in configure

### PR DESCRIPTION
**Pull request by dalgaaf**
'make check' needs nosetests (python-nose) for some of the checks. Added a check to configure to make sure the package is installed.

Fixed also some links in documentation related to CentOS ftp server links.

### CODE REVIEW

**Comment by tchaikov** [comment]
@dalgaaf , i just learnt from @alfredodeza that we don't want to add more dependencies to configure stage. because the state where jenkins.ceph.com creates the dist tarball might not have the required tools, among other things nosetest or sphinx-build. so, probably, you want to reconsider the change to configure.ac?

i am also adding a "--with-man-pages" to configure in order to loose the requirement for sphinx-build. see #4544

**Comment by dalgaaf** [comment]
@tchaikov: to be honest this is strange plan. What is the purpose of a CI tool if it doesn't test the complete build/package. If the CI system doesn't have the tools to build the basic dist tarball, then add the missing packages. 

The nosetest package is needed to run make check successfully. Otherwise you have failing tests and to disable tests based on the installed packages in the system makes also no sense since then the checks are incomplete and the dist tarball is not ready for testing.

**Comment by tchaikov** [comment]
@dalgaaf agreed. and we should use install-deps.sh to ready the CI system for `configure`.

so the only thing i'd suggest for this pull request is not to add nosetest to the list of `documenting-ceph.rst` . what do you think?

**Comment by dachary** [comment]
@dalgaaf the proper way of dealing with python dependencies is by adding them in a requirements.txt file along with a tox.ini file that will be run via make check. You can see how it is done in https://github.com/ceph/ceph/tree/master/src/ceph-detect-init for instance. https://github.com/ceph/ceph/blob/master/install-deps.sh will install the dependencies and install-deps.sh is also used by CI. 
Of course it would be better to add proper packages to BuildRequires but ... finding the python packages that exactly match the content of the requirements.txt files, recursively, not only is a lot of redundant manual taks. It also is a blocker because many such packages do not exist on the operating systems supported by Ceph and on which we want to run tests.

Although I prefer py.test, I don't have strong feelings against nose, as long as it is run from tox.

**Comment by dachary** [comment]
@dalgaaf I'm with @tchaikov on not including in ``documenting-ceph.rst``.

**Comment by dachary** [comment]
(removing myself because I don't have the bandwidth to followup in the next week, feel free to ping me in two weeks if you need)

**Comment by dachary** [comment]
@dalgaaf feel free to re-open when you have time to address the comments

**Pull request closed without merging**
