### PR TITLE
src/CMakeLists.txt: remove unneeded libraries from ceph-dencoder target

### PR DESCRIPTION
**Pull request by wjwithagen**

### CODE REVIEW

**Comment by tchaikov** [comment]
test this please.

**Comment by wjwithagen** [comment]
@tchaikov 
On the FreeBSD end it works perfectly.
On my CentOS box it compiles with problem
Running in Jenkins in ran into trouble during tests.

I guess you've obviously fixed something.
But I think it deserves a bit more hammering in theuthology?

**Comment by tchaikov** [comment]
@wjwithagen jenkins passed. it ran into some irrelevant issue, i believe.

**Comment by tchaikov** [comment]
retest this please. (try again to see if it's reproducible)

**Comment by tchaikov** [comment]
@wjwithagen  needs rebase.

**Comment by wjwithagen** [comment]
please retest this

**Comment by tchaikov** [comment]
@wjwithagen could you update the commit message? it now reads "fix rebase".

**Comment by wjwithagen** [comment]
@tchaikov 
This is a general commit, good for all architectures

**Comment by tchaikov** [comment]
all unit tests (check-generated.sh,readable.sh) involving ceph-dencoder passed.

**Pull request merged**
