### PR TITLE
remove librdmacm from dependencies, README.xio

### PR DESCRIPTION
**Pull request by gregsfortytwo**
This was only needed for XioMessenger and that is gone now.

Signed-off-by: Greg Farnum <gfarnum@redhat.com>

### CODE REVIEW

**Comment by gregsfortytwo** [comment]
As this is a package/build bug, creating this PR is kicking off the testing for it...

**Comment by gregsfortytwo** [comment]
Never mind, we use this for the AsyncMessenger's RDMA mode too, and that's still in tree.

**Comment by cbodley** [comment]
README.xio can still go!

**Comment by gregsfortytwo** [comment]
> README.xio can still go!

This is actually done; looks like a PR merged cleaning that up in the meantime.

**Pull request closed without merging**
