### PR TITLE
nautilus: mount.ceph: remove arbitrary limit on size of name= option

### PR DESCRIPTION
**Pull request by smithfarm**
backport tracker: https://tracker.ceph.com/issues/43770

---

backport of https://github.com/ceph/ceph/pull/32706
parent tracker: https://tracker.ceph.com/issues/43649

this backport was staged using ceph-backport.sh version 15.0.0.6950
find the latest version at https://github.com/ceph/ceph/blob/master/src/script/ceph-backport.sh

### CODE REVIEW

**Comment by smithfarm** [comment]
@luis-henrix JFYI

**Comment by rwagoner** [comment]
I wanted to provide feedback that this patch does fix the issue I had with k8s mounting volumes after I upgraded from 14.2.4 to 14.2.6. I tested by building a set of rpms off 14.2.6 with only this patch added. Is this backport going to be included in 14.2.7?

**Comment by batrick** [comment]
@yuriw @theanalyst @liewegas @jdurgin 

This is needed for 14.2.7. There are rumors of a hotfix release. Can we get this included?

**Comment by jtlayton** [comment]
Sadly, it looks like this didn't make 14.2.7. Hopefully, we can get this in for .8.

**Comment by yuriw** [comment]
[wip-yuri8-testing-2020-02-10-2143-nautilus](https://trello.com/c/baL1B6OC/823-wip-yuri8-testing-2020-02-10-2143-nautilus)

**Pull request merged**
