### PR TITLE
cmake: remove WITH_MDS option

### PR DESCRIPTION
**Pull request by alimaredia**
Signed-off-by: Ali Maredia <amaredia@redhat.com>

This patch can merge as long as there's agreement that the WITH_MDS option can go away.

### CODE REVIEW

**Comment by liewegas** [comment]
@ktdreyer ?

**Comment by ktdreyer** [comment]
:+1: for simplicity

**Comment by liewegas** [comment]
:+1: from me too!

**Comment by ivancich** [comment]
Might a better approach had been to use the WITH_CEPHFS to control building and testing of the mds library and the ceph-mds program? With this merge it's now possible to build without the ceph filesystem and the mds will nonetheless be built.

**Comment by alimaredia** [comment]
@liewegas @tchaikov @jcsp @gregsfortytwo  have any thoughts on what @ivancich mentioned?

**Comment by gregsfortytwo** [comment]
I'm not really aware of either of those build options, so nothing detailed.

In general, building the MDS without the filesystem is weird. But you might want to be able to build the clients without building the MDS, if for instance porting/qualifying clients on weird platforms but not going through the effort of the full server. In which case maybe rename WITH_CEPHFS to WITH_CEPHFS and use WITH_CEPHFS for the full stack?
Or not. I don't have strong feelings about it.

**Pull request merged**
