### PR TITLE
rpm: add fmt-devel as build deps

### PR DESCRIPTION
**Pull request by tchaikov**
## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by tchaikov** [comment]
jenkins test make check

**Comment by tchaikov** [comment]
jenkins test make check

**Comment by tchaikov** [comment]
@jdurgin @neha-ojha ping?

**Comment by tchaikov** [comment]
https://pulpito.ceph.com/kchai-2020-09-26_01:51:27-rados-wip-kefu-testing-2020-09-25-2324-distro-basic-smithi/

**Comment by tchaikov** [comment]
- https://pulpito.ceph.com/kchai-2020-09-26_11:23:24-rados-wip-kefu-testing-2020-09-25-2324-distro-basic-smithi/
- https://pulpito.ceph.com/kchai-2020-09-27_03:11:59-rados-wip-kefu-testing-2020-09-25-2324-distro-basic-smithi/
- https://pulpito.ceph.com/kchai-2020-09-27_14:40:39-rados-wip-kefu-testing-2020-09-25-2325-distro-basic-smithi

**Review by neha-ojha — APPROVED** [review]

**Comment by tchaikov** [comment]
jenkins test docs

**Pull request merged**
