### PR TITLE
ceph.spec.in: SUSE/openSUSE builds need libbz2-devel

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/11629

### CODE REVIEW

**Comment by dachary** [comment]
@smithfarm please ignore the bot false negative, it will be fixed by #5208

**Comment by dachary** [comment]
@smithfarm the fix was merged, could you please rebase & repush to trigger the bot once more ?

**Comment by smithfarm** [comment]
@dachary It failed osd-scrub-repair.sh - the log output of that test is huge, but I found for example:

```
2015-07-13 01:05:29.632663 2b040c6391c0 -1 journal FileJournal::_open: disabling aio for non-block journal.  Use journal_force_aio to force use of aio anyway
2015-07-13 01:05:29.765775 2b040c6391c0 -1 journal FileJournal::_open: disabling aio for non-block journal.  Use journal_force_aio to force use of aio anyway
2015-07-13 01:05:29.770750 2b040c6391c0 -1 filestore(testdir/osd-scrub-repair/0) could not find 23c2fcde/osd_superblock/0//-1 in index: (2) No such file or directory
2015-07-13 01:05:29.865831 2b040c6391c0 -1 created object store testdir/osd-scrub-repair/0 journal testdir/osd-scrub-repair/0/journal for osd.0 fsid 11541aaa-9291-46a9-9360-a7c0b948c996
2015-07-13 01:05:29.865880 2b040c6391c0 -1 auth: error reading file: testdir/osd-scrub-repair/0/keyring: can't open testdir/osd-scrub-repair/0/keyring: (2) No such file or directory
2015-07-13 01:05:29.865963 2b040c6391c0 -1 created new key in keyring testdir/osd-scrub-repair/0/keyring
```

**Comment by dachary** [comment]
@smithfarm please ignore, this is a false negative and the cause has been fixed in master but not backported to hammer.

**Comment by dachary** [comment]
Pass http://tracker.ceph.com/issues/12701#ceph-deploy http://tracker.ceph.com/issues/12701#upgrade (there are job failures but they are unrelated to packaging)

**Pull request merged**
