### PR TITLE
squid: mgr/dashboard: nvmeof api batch fixes

### PR DESCRIPTION
**Pull request by nizamial09**
backport tracker: https://tracker.ceph.com/issues/64515, https://tracker.ceph.com/issues/64775, https://tracker.ceph.com/issues/65100

---

backport of https://github.com/ceph/ceph/pull/55535, #55804, https://github.com/ceph/ceph/pull/56164/
parent tracker: https://tracker.ceph.com/issues/64384, https://tracker.ceph.com/issues/64714, https://tracker.ceph.com/issues/64890

this backport was staged using ceph-backport.sh version 16.0.0.6848
find the latest version at https://github.com/ceph/ceph/blob/main/src/script/ceph-backport.sh

### CODE REVIEW

**Comment by nizamial09** [comment]
jenkins test api

**Comment by nizamial09** [comment]
jenkins test api

**Comment by nizamial09** [comment]
jenkins test api

**Comment by nizamial09** [comment]
jenkins test api

**Comment by nizamial09** [comment]
jenkins test windows

**Comment by nizamial09** [comment]
jenkins test make check

**Comment by nizamial09** [comment]
jenkins test api

**Comment by nizamial09** [comment]
jenkins test make check

**Comment by epuertat** [comment]
Ceph Dashboard Cephadm e2e failure:

> [Test Result](https://jenkins.ceph.com/job/ceph-dashboard-cephadm-e2e/10177/testReport/) (8 failures / +8)
> [RGW Daemon Overall Performance (example #2).Grafana panels RGW Daemon Overall Performance (example #2)](https://jenkins.ceph.com/job/ceph-dashboard-cephadm-e2e/10177/testReport/junit/(root)/RGW%20Daemon%20Overall%20Performance%20(example%20_2)/Grafana_panels_RGW_Daemon_Overall_Performance__example__2_/)
> [RGW Daemon Overall Performance (example #3).Grafana panels RGW Daemon Overall Performance (example #3)](https://jenkins.ceph.com/job/ceph-dashboard-cephadm-e2e/10177/testReport/junit/(root)/RGW%20Daemon%20Overall%20Performance%20(example%20_3)/Grafana_panels_RGW_Daemon_Overall_Performance__example__3_/)
> [RGW Daemon Overall Performance (example #4).Grafana panels RGW Daemon Overall Performance (example #4)](https://jenkins.ceph.com/job/ceph-dashboard-cephadm-e2e/10177/testReport/junit/(root)/RGW%20Daemon%20Overall%20Performance%20(example%20_4)/Grafana_panels_RGW_Daemon_Overall_Performance__example__4_/)
> [RGW Daemon Overall Performance (example #5).Grafana panels RGW Daemon Overall Performance (example #5)](https://jenkins.ceph.com/job/ceph-dashboard-cephadm-e2e/10177/testReport/junit/(root)/RGW%20Daemon%20Overall%20Performance%20(example%20_5)/Grafana_panels_RGW_Daemon_Overall_Performance__example__5_/)
> [RGW Daemon Overall Performance (example #6).Grafana panels RGW Daemon Overall Performance (example #6)](https://jenkins.ceph.com/job/ceph-dashboard-cephadm-e2e/10177/testReport/junit/(root)/RGW%20Daemon%20Overall%20Performance%20(example%20_6)/Grafana_panels_RGW_Daemon_Overall_Performance__example__6_/)
> [RGW per Daemon Performance (example #1).Grafana panels RGW per Daemon Performance (example #1)](https://jenkins.ceph.com/job/ceph-dashboard-cephadm-e2e/10177/testReport/junit/(root)/RGW%20per%20Daemon%20Performance%20(example%20_1)/Grafana_panels_RGW_per_Daemon_Performance__example__1_/)
> [RGW per Daemon Performance (example #3).Grafana panels RGW per Daemon Performance (example #3)](https://jenkins.ceph.com/job/ceph-dashboard-cephadm-e2e/10177/testReport/junit/(root)/RGW%20per%20Daemon%20Performance%20(example%20_3)/Grafana_panels_RGW_per_Daemon_Performance__example__3_/)
> [RGW per Daemon Performance (example #5).Grafana panels RGW per Daemon Performance (example #5)](https://jenkins.ceph.com/job/ceph-dashboard-cephadm-e2e/10177/testReport/junit/(root)/RGW%20per%20Daemon%20Performance%20(example%20_5)/Grafana_panels_RGW_per_Daemon_Performance__example__5_/)

**Pull request merged**
