### PR TITLE
smb: have create cluster and create share commands only create

### PR DESCRIPTION
**Pull request by phlogistonjohn**
Depends on #57180

Prior to this change the create commands could be used counter to the term 'create' as a create-or-update command. IMO this violates the principle of least surprise so make them create-only.

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [x] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [x] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Review by adk3798 — APPROVED** [review]
Final 4 commits (only new ones for this PR afaict) LGTM

**Comment by adk3798** [comment]
https://pulpito.ceph.com/adking-2024-06-12_15:11:26-orch:cephadm-wip-adk-testing-2024-06-12-0810-distro-default-smithi/

Failures were

- `in cluster log` stuff
- mds_upgrade_sequence
- staggered upgrade with the agent on
- rados_api_tests cleanup failure
- some failures installing kernel stuff pre-test

did some rerun of the SMB tests as well, that all passed https://pulpito.ceph.com/adking-2024-06-13_15:04:10-orch:cephadm-wip-adk-testing-2024-06-12-0810-distro-default-smithi/

**Comment by phlogistonjohn** [comment]
WRT to make check failing, it was some `crushtool` test. Likely not related to my changes. Will re-run make check (again).

**Comment by phlogistonjohn** [comment]
jenkins test make check

**Comment by phlogistonjohn** [comment]
Now we can wait for a million years for a result.

**Comment by adk3798** [comment]
`unittest_deferred` failed this time in make check

**Comment by adk3798** [comment]
jenkins test make check

**Comment by avanthakkar** [comment]
jenkins test make check arm64

**Review by avanthakkar — APPROVED** [review]
LGTM code-wise!

**Pull request merged**
