### PR TITLE
monitoring: Use instance for PG States panel in grafana

### PR DESCRIPTION
**Pull request by juztas**
Signed-off-by: Justas Balcas <juztas@gmail.com>

### CODE REVIEW

**Comment by callithea** [comment]
Hi @juztas, thanks for your contribution!
Could you please add this line:`Signed-off-by: Justas Balcas <juztas@gmail.com>` to the commit message and also add the prefix `monitoring:` to the commit message title?

**Comment by callithea** [comment]
Hi @juztas, do you still plan to work on this?

**Comment by avanthakkar** [comment]
jenkins retest this please

**Comment by avanthakkar** [comment]
jenkins retest this please

**Comment by alfonsomthd** [comment]
> Hi @juztas, do you still plan to work on this?

@juztas ping.

**Comment by epuertat** [comment]
@p-se do you think we should we try to recover this?

**Comment by juztas** [comment]
Hi, Yes, I will look into it this week. I have seen more issues than just use an instance for pg.

**Comment by juztas** [comment]
Closing because of new pull request: https://github.com/ceph/ceph/pull/41047

**Pull request closed without merging**
