### PR TITLE
mon: OSDMonitor: do not assume a session exists in send_incremental()

### PR DESCRIPTION
**Pull request by jecluis**
http://tracker.ceph.com/issues/14236

### CODE REVIEW

**Comment by dachary** [comment]
@jecluis it would be useful to explain in the commit message in what respect the regression was hammer specific, to justify why this commit is necessary and why there is no commit in master to be backported to fix the issue.

**Comment by jecluis** [comment]
@dachary done. Also, while figuring out a proper commit message I noticed that these patches may have introduced yet another potential bug -- or, maybe, the bug is actually in `OSDMonitor::process_failures()` because it doesn't check whether each message still has a session --, but I'll take a better look into this tomorrow. In the mean time, @tchaikov please take a look and let me know what you think.

**Comment by dachary** [comment]
@jecluis crystal clear now, thanks ! A typo : s/intrudu/introdu/

**Comment by tchaikov** [comment]
@jecluis sorry for the bug. yes, the fix makes sense to me. we should send the oldest osdmap we have even if the `MonSession` was dropped before `send_incremental()`, otherwise we will fall to the branch building the incrementals not available anymore, and hence run into a brick wall.

**Pull request merged**
