### PR TITLE
hammer: tests: test_librbd_fsx: invalidate before discard in krbd mode

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/18795

### CODE REVIEW

**Comment by smithfarm** [comment]
Pushed wip branch to Shaman, will test with: `teuthology-suite --priority 101 --suite krbd --ceph wip-18795-hammer --machine-type smithi -k distro --filter="krbd/rbd-nomount/{clusters/fixed-3.yaml conf.yaml fs/btrfs.yaml install/ceph.yaml msgr-failures/few.yaml tasks/rbd_kfsx.yaml}" qa/distros/all/ubuntu_14.04.yaml`

**Comment by smithfarm** [comment]
@idryomov The test now fails with:

```
2017-02-02T13:28:25.451 INFO:tasks.rbd_fsx:starting rbd_fsx...
2017-02-02T13:28:25.451 INFO:teuthology.orchestra.run.smithi160:Running: 'sudo adjust-ulimits ceph-coverage /home/ubuntu/cephtest/archive/coverage ceph_test_librbd_fsx -d -W -R -p 100 -P /home/ubuntu/cephtest/archive -r 512 -w 512 -t 512 -h 512 -l 250000000 -S 0 -N 10000 -K -U pool_client.0 image_client.0'
2017-02-02T13:28:25.480 INFO:teuthology.orchestra.run.smithi160.stdout:mapped writes DISABLED
2017-02-02T13:28:25.480 INFO:teuthology.orchestra.run.smithi160.stdout:mapped reads DISABLED
2017-02-02T13:28:25.480 INFO:teuthology.orchestra.run.smithi160.stdout:Seed set to 2105
2017-02-02T13:28:25.480 INFO:teuthology.orchestra.run.smithi160.stdout:krbd mode enabled
2017-02-02T13:28:31.173 INFO:teuthology.orchestra.run.smithi160.stdout:skipping zero size read
2017-02-02T13:28:31.174 INFO:teuthology.orchestra.run.smithi160.stdout:skipping zero size read
2017-02-02T13:28:31.174 INFO:teuthology.orchestra.run.smithi160.stdout:truncating to largest ever: 0x2656600
2017-02-02T13:28:31.174 INFO:teuthology.orchestra.run.smithi160.stdout:6 trunc	from 0x0 to 0x2656600
2017-02-02T13:28:31.185 INFO:teuthology.orchestra.run.smithi160.stdout:7 read	0x13b000 thru	0x1463a7	(0xb3a8 bytes)
2017-02-02T13:28:31.189 INFO:teuthology.orchestra.run.smithi160.stdout:truncating to largest ever: 0x70e9a00
2017-02-02T13:28:31.200 INFO:teuthology.orchestra.run.smithi160.stdout:8 trunc	from 0x2656600 to 0x70e9a00
2017-02-02T13:28:31.234 INFO:teuthology.orchestra.run.smithi160.stdout:9 write	0xc766600 thru	0xc770ca9	(0xa6aa bytes)
2017-02-02T13:28:31.234 INFO:teuthology.orchestra.run.smithi160.stdout:truncating to largest ever: 0xa2e7800
2017-02-02T13:28:31.240 INFO:teuthology.orchestra.run.smithi160.stdout:14 trunc	from 0xc770e00 to 0xa2e7800
2017-02-02T13:28:31.262 INFO:teuthology.orchestra.run.smithi160.stdout:15 read	0x1a0fc00 thru	0x1a1de27	(0xe228 bytes)
2017-02-02T13:28:31.262 INFO:teuthology.orchestra.run.smithi160.stdout:16 punch	from 0x674800 to 0x681e00, (0xd600 bytes)
2017-02-02T13:28:31.262 INFO:teuthology.orchestra.run.smithi160.stdout:BLKDISCARD(6768640, 54784) failed
2017-02-02T13:28:31.262 INFO:teuthology.orchestra.run.smithi160.stdout:do_punch_hole: ops->discard: Operation not supported
2017-02-02T13:28:31.262 INFO:teuthology.orchestra.run.smithi160.stdout:LOG DUMP (16 total operations):
2017-02-02T13:28:31.263 INFO:teuthology.orchestra.run.smithi160.stdout:1(  1 mod 256): SKIPPED (no operation)
2017-02-02T13:28:31.263 INFO:teuthology.orchestra.run.smithi160.stdout:2(  2 mod 256): SKIPPED (no operation)
2017-02-02T13:28:31.263 INFO:teuthology.orchestra.run.smithi160.stdout:3(  3 mod 256): SKIPPED (no operation)
2017-02-02T13:28:31.263 INFO:teuthology.orchestra.run.smithi160.stdout:4(  4 mod 256): SKIPPED (no operation)
2017-02-02T13:28:31.263 INFO:teuthology.orchestra.run.smithi160.stdout:5(  5 mod 256): SKIPPED (no operation)
2017-02-02T13:28:31.263 INFO:teuthology.orchestra.run.smithi160.stdout:6(  6 mod 256): TRUNCATE UP	from 0x0 to 0x2656600
2017-02-02T13:28:31.263 INFO:teuthology.orchestra.run.smithi160.stdout:7(  7 mod 256): READ     0x13b000 thru 0x1463a7	(0xb3a8 bytes)
2017-02-02T13:28:31.263 INFO:teuthology.orchestra.run.smithi160.stdout:8(  8 mod 256): TRUNCATE UP	from 0x2656600 to 0x70e9a00
2017-02-02T13:28:31.263 INFO:teuthology.orchestra.run.smithi160.stdout:9(  9 mod 256): WRITE    0xc766600 thru 0xc770ca9	(0xa6aa bytes) HOLE
2017-02-02T13:28:31.263 INFO:teuthology.orchestra.run.smithi160.stdout:10( 10 mod 256): SKIPPED (no operation)
2017-02-02T13:28:31.264 INFO:teuthology.orchestra.run.smithi160.stdout:11( 11 mod 256): SKIPPED (no operation)
2017-02-02T13:28:31.264 INFO:teuthology.orchestra.run.smithi160.stdout:12( 12 mod 256): SKIPPED (no operation)
2017-02-02T13:28:31.264 INFO:teuthology.orchestra.run.smithi160.stdout:13( 13 mod 256): SKIPPED (no operation)
2017-02-02T13:28:31.264 INFO:teuthology.orchestra.run.smithi160.stdout:14( 14 mod 256): TRUNCATE DOWN	from 0xc770e00 to 0xa2e7800
2017-02-02T13:28:31.264 INFO:teuthology.orchestra.run.smithi160.stdout:15( 15 mod 256): READ     0x1a0fc00 thru 0x1a1de27	(0xe228 bytes)
2017-02-02T13:28:31.264 INFO:teuthology.orchestra.run.smithi160.stdout:16( 16 mod 256): PUNCH    0x674800 thru 0x681dff	(0xd600 bytes)
2017-02-02T13:28:31.351 INFO:teuthology.orchestra.run.smithi160.stdout:Correct content saved for comparison
2017-02-02T13:28:31.352 INFO:teuthology.orchestra.run.smithi160.stdout:(maybe hexdump "image_client.0" vs "image_client.0.fsxgood")
2017-02-02T13:28:34.362 ERROR:teuthology.parallel:Exception in parallel execution
Traceback (most recent call last):
  File "/home/teuthworker/src/git.ceph.com_git_teuthology_master/teuthology/parallel.py", line 83, in __exit__
    for result in self:
  File "/home/teuthworker/src/git.ceph.com_git_teuthology_master/teuthology/parallel.py", line 101, in next
    resurrect_traceback(result)
  File "/home/teuthworker/src/git.ceph.com_git_teuthology_master/teuthology/parallel.py", line 19, in capture_traceback
    return func(*args, **kwargs)
  File "/home/teuthworker/src/git.ceph.com_ceph-c_wip-18795-hammer/qa/tasks/rbd_fsx.py", line 82, in _run_one_client
    remote.run(args=args)
  File "/home/teuthworker/src/git.ceph.com_git_teuthology_master/teuthology/orchestra/remote.py", line 192, in run
    r = self._runner(client=self.ssh, name=self.shortname, **kwargs)
  File "/home/teuthworker/src/git.ceph.com_git_teuthology_master/teuthology/orchestra/run.py", line 403, in run
    r.wait()
  File "/home/teuthworker/src/git.ceph.com_git_teuthology_master/teuthology/orchestra/run.py", line 166, in wait
    label=self.label)
CommandFailedError: Command failed on smithi160 with status 161: 'sudo adjust-ulimits ceph-coverage /home/ubuntu/cephtest/archive/coverage ceph_test_librbd_fsx -d -W -R -p 100 -P /home/ubuntu/cephtest/archive -r 512 -w 512 -t 512 -h 512 -l 250000000 -S 0 -N 10000 -K -U pool_client.0 image_client.0'
```

**Comment by smithfarm** [comment]
I guess this is the root cause? `do_punch_hole: ops->discard: Operation not supported`

**Comment by idryomov** [comment]
@smithfarm Need to use -k testing.  trusty distro kernel (3.13.*) doesn't support discard.

**Comment by smithfarm** [comment]
Re-testing with `teuthology-suite --priority 101 --suite krbd --ceph wip-18795-hammer --machine-type smithi -k testing --email ncutler@suse.com --filter="krbd/rbd-nomount/{clusters/fixed-3.yaml conf.yaml fs/btrfs.yaml install/ceph.yaml msgr-failures/few.yaml tasks/rbd_kfsx.yaml}" qa/distros/all/ubuntu_14.04.yaml`

**running** http://pulpito.ceph.com:80/smithfarm-2017-02-02_14:04:03-krbd-wip-18795-hammer-testing-basic-smithi/

**Comment by smithfarm** [comment]
Hammer is EOL.

**Pull request closed without merging**
