### PR TITLE
osd: renamed the new vector name in OSDMap::build_simple_crush_map_from_conf

### PR DESCRIPTION
**Pull request by joscollin**
Renamed the new vector name in OSDMap::build_simple_crush_map_from_conf, to avoid confusing
it with the sections vector outside the for loop and which is iterating.

Signed-off-by: Jos Collin <jcollin@redhat.com>

### CODE REVIEW

**Comment by liewegas** [comment]
can you rebase to get rid of the merge commits please?

**Comment by joscollin** [comment]
@liewegas Done.

**Comment by yuriw** [comment]
@joscollin @liewegas pls resolve conflicts

[yuriw@smithi148 build]$ git pull https://github.com/joscollin/ceph.git wip-cleanup-osdmap-sections
remote: Counting objects: 5, done.
remote: Total 5 (delta 4), reused 4 (delta 4), pack-reused 1
Unpacking objects: 100% (5/5), done.
From https://github.com/joscollin/ceph
 * branch            wip-cleanup-osdmap-sections -> FETCH_HEAD
Auto-merging src/osd/OSDMap.cc
CONFLICT (content): Merge conflict in src/osd/OSDMap.cc
Automatic merge failed; fix conflicts and then commit the result.

**Comment by joscollin** [comment]
@liewegas @yuriw : Resolved the merge conflicts. Please review and merge now.

**Pull request merged**
