### PR TITLE
use remote write file

### PR DESCRIPTION
**Pull request by kshtsk**
## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by batrick** [comment]
````
flake8 run-test: commands[0] | flake8 --select=F,E9 --exclude=venv,.tox
./tasks/ragweed.py:215:13: F841 local variable 'conf' is assigned to but never used
./tasks/ragweed.py:218:71: F821 undefined name 'data'
./tasks/s3tests.py:248:13: F841 local variable 'conf' is assigned to but never used
./tasks/s3tests.py:251:71: F821 undefined name 'data'
````

**Comment by kshtsk** [comment]
The tests should be run with `-t refs/pull/1538/merge` options.

**Comment by tchaikov** [comment]
@kshtsk could you run this change with, for instance, rados suites?

**Comment by kshtsk** [comment]
> @kshtsk could you run this change with, for instance, rados suites?

yes I will

**Comment by kshtsk** [comment]
jenkins retest this please

**Comment by kshtsk** [comment]
@tchaikov I've run _rados:cephadm_ with limit 2:
```
teuthology-suite --ceph-repo https://github.com/ceph/ceph --suite rados:cephadm --suite-branch wip-remote-write-file --suite-repo https://github.com/kshtsk/ceph -t refs/pull/1538/merge -v --limit 2 -m smithi --priority 66 --sha1 42f47baab639209ee8af40ce0f158d32f108a74f
```
https://pulpito.ceph.com/kyr-2020-08-05_13:22:39-rados:cephadm-master-distro-basic-smithi/

Do we need run this whole suite? Do we need to run another suites from _rados_? Since there changes related to other suites, do we need to run some more?

**Comment by kshtsk** [comment]
Does anyone has a clue why the make check test failed? No sure it is related to the PR.

**Comment by kshtsk** [comment]
https://pulpito.ceph.com/kyr-2020-08-05_14:25:07-fs:basic_functional-master-distro-basic-smithi/

Status | Job ID | Links | Duration | Description | Nodes
-- | -- | -- | -- | -- | --
pass | 5288967 |   | 0:18:11 | fs:basic_functional/{begin clusters/1-mds-4-client-coloc  conf/{client mds mon osd} mount/fuse objectstore/bluestore-ec-root  overrides/{frag_enable no_client_pidfile whitelist_health  whitelist_wrongly_marked_down} supported-random-distros$/{rhel_8}  tasks/sessionmap/{sessionmap}} | 2
pass | 5288968 |   | 0:17:34 | fs:basic_functional/{begin clusters/1-mds-4-client-coloc  conf/{client mds mon osd} mount/fuse objectstore/bluestore-bitmap  overrides/{frag_enable no_client_pidfile whitelist_health  whitelist_wrongly_marked_down} supported-random-distros$/{rhel_8}  tasks/sessionmap/{sessionmap}} | 2

**Comment by kshtsk** [comment]
Full suite for rados:cephadm

https://pulpito.ceph.com/kyr-2020-08-05_13:51:26-rados:cephadm-master-distro-basic-smithi/

**Comment by kshtsk** [comment]
cephfs-shell
```
teuthology-suite --ceph-repo https://github.com/ceph/ceph --suite fs:basic_functional --suite-branch wip-remote-write-file --suite-repo https://github.com/kshtsk/ceph -t refs/pull/1538/merge -v -m smithi --priority 66 --sha1 42f47baab639209ee8af40ce0f158d32f108a74f --filter-all cephfs-shell
```
https://pulpito.ceph.com/kyr-2020-08-05_16:08:46-fs:basic_functional-master-distro-basic-smithi/

**Comment by kshtsk** [comment]
jenkins test docs

**Comment by kshtsk** [comment]
cephfs-shell test passed

```teuthology-suite --ceph-repo https://github.com/ceph/ceph --suite fs:basic_functional --suite-branch wip-remote-write-file --suite-repo https://github.com/kshtsk/ceph -t refs/pull/1538/merge -v -m smithi --priority 66 --sha1 42f47baab639209ee8af40ce0f158d32f108a74f --filter-all cephfs-shell```

https://pulpito.ceph.com/kyr-2020-08-06_09:38:11-fs:basic_functional-master-distro-basic-smithi/

Status | Job ID | Links | Duration | Description | Nodes
-- | -- | -- | -- | -- | --
pass | 5291819 |   | 2020-08-06 09:38:17 | 2020-08-06 09:39:03 | 2020-08-06 10:17:02 | 0:37:59 | 0:30:54 | 0:07:05 | smithi | refs/pull/1538/merge | ubuntu | 18.04 | 2
pass | 5291820 |   | 2020-08-06 09:38:17 | 2020-08-06 09:39:05 | 2020-08-06 10:21:05 | 0:42:00 | 0:30:04 | 0:11:56 | smithi | refs/pull/1538/merge | ubuntu | 18.04 | 2

**Comment by tchaikov** [comment]
jenkins test docs

**Comment by kshtsk** [comment]
The rbd_fio passed too:

```
teuthology-suite --ceph-repo https://github.com/ceph/ceph --suite krbd:rbd --suite-branch wip-remote-write-file --suite-repo https://github.com/kshtsk/ceph -t refs/pull/1538/merge -v -m smithi --priority 66 --sha1 42f47baab639209ee8af40ce0f158d32f108a74f --filter-all rbd_fio -k testing
```

https://pulpito.ceph.com/kyr-2020-08-06_10:35:32-krbd:rbd-master-testing-basic-smithi/

Status | Job ID | Links | Duration | Description | Nodes
-- | -- | -- | -- | -- | --
pass | 5291924 |   | 0:47:37 | krbd:rbd/{bluestore-bitmap clusters/fixed-3 conf msgr-failures/few tasks/rbd_fio} | 3
pass | 5291925 |   | 0:42:35 | krbd:rbd/{bluestore-bitmap clusters/fixed-3 conf msgr-failures/many tasks/rbd_fio} | 3

**Comment by kshtsk** [comment]
The s3tests java rgw:verify passed:
https://pulpito.ceph.com/kyr-2020-08-06_11:52:55-rgw:verify-master-distro-basic-smithi/

Status | Job ID | Duration | Description | Nodes
-- | -- | -- | -- | --
pass | 5292561 | 0:28:15 | rgw:verify/{centos_latest clusters/fixed-2 frontend/beast  msgr-failures/few objectstore/bluestore-bitmap overrides proto/http  rgw_pool_type/ec-profile sharding$/{single}  striping$/{stripe-greater-than-chunk} tasks/{0-install cls ragweed  reshard s3tests-java s3tests} validater/lockdep} | 2
pass | 5292562 | 0:29:08 | rgw:verify/{centos_latest clusters/fixed-2 frontend/civetweb  msgr-failures/few objectstore/filestore-xfs overrides proto/https  rgw_pool_type/ec sharding$/{default}  striping$/{stripe-greater-than-chunk} tasks/{0-install cls ragweed  reshard s3tests-java s3tests} validater/valgrind} | 2

**Comment by kshtsk** [comment]
jenkins test make check

**Comment by kshtsk** [comment]
retest this please

**Review by batrick — APPROVED** [review]

**Comment by batrick** [comment]
@kshtsk can we remove the "[WIP]"?

**Review by batrick — DISMISSED** [review]
https://pulpito.ceph.com/pdonnell-2020-09-03_22:39:43-fs-wip-pdonnell-testing-20200903.202918-distro-basic-smithi/

**Comment by kshtsk** [comment]
> https://pulpito.ceph.com/pdonnell-2020-09-03_22:39:43-fs-wip-pdonnell-testing-20200903.202918-distro-basic-smithi/

this run is scheduled against wrong teuthology branch, corresponding teuthology PR 1538
I will remove WIP after the teuthology PR merged, however I found some strange bug, with remote read_file, I can not reproduce it in local environment yet, investigating...

**Comment by kshtsk** [comment]
For example:
https://pulpito.ceph.com/kyr-2020-09-03_22:20:09-fs:basic_functional-master-distro-basic-smithi/

The read_file reads extra binary data:
```
2020-09-03T22:32:33.049 INFO:teuthology.orchestra.run.smithi060.stdout:[mgr.y]
2020-09-03T22:32:33.050 INFO:teuthology.orchestra.run.smithi060.stdout:	key = AQDiblFfykUxJxAAUUGVs7VXwL7fseBUSBIppw==
2020-09-03T22:32:33.050 INFO:teuthology.orchestra.run.smithi060.stdout:�����������������aT������a�����������������ï¿½<����������������������ï¿½ï¿½<���������������bT������b�����������������ï¿½ï¿½����������������������ï¿½ï¿½ï¿½���������������cT������c�����������������ï¿½ï¿½����������������������ï¿½ï¿½ï¿½������������������a���b���c�[mds.a]
2020-09-03T22:32:33.050 INFO:teuthology.orchestra.run.smithi060.stdout:	key = AQDiblFf0UL7LBAAbKnwfywXpR3CtJCCdcYhqQ==
```
However earlier in the log it says it read exact amount of data:
```
2020-09-03T22:32:32.286 INFO:tasks.ceph:Reading keys from all nodes...
2020-09-03T22:32:32.287 INFO:teuthology.orchestra.run.smithi060:> set -ex
2020-09-03T22:32:32.287 INFO:teuthology.orchestra.run.smithi060:> sudo dd if=/var/lib/ceph/mgr/ceph-y/keyring of=/dev/stdout
2020-09-03T22:32:32.292 INFO:teuthology.orchestra.run.smithi060.stderr:+ sudo dd if=/var/lib/ceph/mgr/ceph-y/keyring of=/dev/stdout
2020-09-03T22:32:32.300 INFO:teuthology.orchestra.run.smithi060.stdout:[mgr.y]
2020-09-03T22:32:32.301 INFO:teuthology.orchestra.run.smithi060.stdout:	key = AQDiblFfykUxJxAAUUGVs7VXwL7fseBUSBIppw==
2020-09-03T22:32:32.301 INFO:teuthology.orchestra.run.smithi060.stderr:0+1 records in
2020-09-03T22:32:32.301 INFO:teuthology.orchestra.run.smithi060.stderr:0+1 records out
2020-09-03T22:32:32.301 INFO:teuthology.orchestra.run.smithi060.stderr:56 bytes copied, 0.000184217 s, 304 kB/s
```
Interesting that earlier those tests was passing... and the teuthology PR did not change significantly.

**Comment by kshtsk** [comment]
well... I figured it out

**Comment by kshtsk** [comment]
After fixing the default value for stdout in remote.read_file() ceph/teuthology#1538, it is passing again:

https://pulpito.ceph.com/kyr-2020-09-04_12:37:25-rados:cephadm-master-distro-basic-smithi/

**Comment by kshtsk** [comment]
Just a reminder test should be run with `-t refs/pull/1538/merge` till the teuthology pull request merged.

**Review by tchaikov — APPROVED** [review]

**Comment by tchaikov** [comment]
@batrick does @kshtsk 's reply address your concern?

**Comment by kshtsk** [comment]
The latest results fails:
https://pulpito.ceph.com/kyr-2020-09-04_15:21:01-rados:cephadm-master-distro-basic-smithi/

I don't know if this is legal failure?

**Comment by kshtsk** [comment]
Looks like cephadm experiencing problems, it cannot find a /etc/containers/registries.conf file on remote hosts.

**Comment by batrick** [comment]
> @batrick does @kshtsk 's reply address your concern?

Yes, I'll try that.

**Comment by kshtsk** [comment]
Okay, seems like the code relies on IOError generated by remote.get_file which is replaced with remote.run, need another fix for that.

**Comment by kshtsk** [comment]
Added corresponding patch to ceph/teuthology#1556 addressing the issue.

**Comment by batrick** [comment]
@kshtsk https://github.com/ceph/teuthology/pull/1538 is merged so we should be using `-t refs/pull/1556/merge` now?

**Comment by batrick** [comment]
> @kshtsk [ceph/teuthology#1538](https://github.com/ceph/teuthology/pull/1538) is merged so we should be using `-t refs/pull/1556/merge` now?

https://pulpito.ceph.com/?branch=wip-pdonnell-testing-20200904.221904

with `-t refs/pull/1556/merge`

**Comment by batrick** [comment]
Interesting, a lot of the failures we also saw here https://github.com/ceph/teuthology/pull/1554#issuecomment-684059482 . I don't have an explanation, do you @kshtsk ?

**Comment by batrick** [comment]
Testing again without `-t`.

**Comment by kshtsk** [comment]
I've run this again: https://pulpito.ceph.com/kyr-2020-09-04_19:58:27-rados:cephadm-master-distro-basic-smithi/
So many failures.

**Comment by kshtsk** [comment]
> Interesting, a lot of the failures we also saw here [ceph/teuthology#1554 (comment)](https://github.com/ceph/teuthology/pull/1554#issuecomment-684059482) . I don't have an explanation, do you @kshtsk ?

No, I have not yet, for me it all fails on ansbile step.

**Comment by kshtsk** [comment]
@batrick seems like workers are conflicting each other while bootstrapping teuthology.

**Review by batrick — COMMENTED** [review]
Getting this failure now:

````
2020-09-05T06:30:01.070 INFO:teuthology.orchestra.run.smithi075:> rm -f -- /home/ubuntu/.ssh/id_rsa
2020-09-05T06:30:01.112 INFO:teuthology.orchestra.run.smithi075:> touch /home/ubuntu/.ssh/id_rsa && chmod 500 -- /home/ubuntu/.ssh/id_rsa
2020-09-05T06:30:01.162 INFO:teuthology.orchestra.run.smithi075:> set -ex
2020-09-05T06:30:01.162 INFO:teuthology.orchestra.run.smithi075:> dd of=/home/ubuntu/.ssh/id_rsa conv=notrunc oflag=append
2020-09-05T06:30:01.210 INFO:teuthology.orchestra.run.smithi075.stderr:+ dd of=/home/ubuntu/.ssh/id_rsa conv=notrunc oflag=append
2020-09-05T06:30:01.214 INFO:teuthology.orchestra.run.smithi075.stderr:dd: failed to open '/home/ubuntu/.ssh/id_rsa': Permission denied
2020-09-05T06:30:01.214 DEBUG:teuthology.orchestra.run:got remote process result: 1
2020-09-05T06:30:01.215 ERROR:teuthology.contextutil:Saw exception from nested tasks
Traceback (most recent call last):
  File "/home/teuthworker/src/git.ceph.com_git_teuthology_master/teuthology/contextutil.py", line 31, in nested
    vars.append(enter())
  File "/usr/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/home/teuthworker/src/git.ceph.com_git_teuthology_master/teuthology/task/ssh_keys.py", line 157, in push_keys_to_host
    misc.create_file(remote, priv_key_file, priv_key_data, str(500))
  File "/home/teuthworker/src/git.ceph.com_git_teuthology_master/teuthology/misc.py", line 698, in create_file
    append_lines_to_file(remote, path, data, sudo)
  File "/home/teuthworker/src/git.ceph.com_git_teuthology_master/teuthology/misc.py", line 660, in append_lines_to_file
    remote.write_file(path, lines, append=True, sudo=sudo)
  File "/home/teuthworker/src/git.ceph.com_git_teuthology_master/teuthology/orchestra/remote.py", line 578, in write_file
    self.run(args=args, stdin=data)
  File "/home/teuthworker/src/git.ceph.com_git_teuthology_master/teuthology/orchestra/remote.py", line 213, in run
    r = self._runner(client=self.ssh, name=self.shortname, **kwargs)
  File "/home/teuthworker/src/git.ceph.com_git_teuthology_master/teuthology/orchestra/run.py", line 446, in run
    r.wait()
  File "/home/teuthworker/src/git.ceph.com_git_teuthology_master/teuthology/orchestra/run.py", line 160, in wait
    self._raise_for_status()
  File "/home/teuthworker/src/git.ceph.com_git_teuthology_master/teuthology/orchestra/run.py", line 182, in _raise_for_status
    node=self.hostname, label=self.label
teuthology.exceptions.CommandFailedError: Command failed on smithi075 with status 1: 'set -ex\ndd of=/home/ubuntu/.ssh/id_rsa conv=notrunc oflag=append'
````

Looks related?

**Comment by batrick** [comment]
Kefu pointed me at https://github.com/ceph/teuthology/pull/1557 . Thanks for fixing it!

**Comment by tchaikov** [comment]
- https://pulpito.ceph.com/kchai-2020-09-08_12:29:35-rados-wip-kefu-testing-2020-09-08-0934-distro-basic-smithi/
- https://pulpito.ceph.com/kchai-2020-09-10_01:44:12-rados-wip-kefu-testing-2020-09-08-0934-distro-basic-smithi/

failures tracked by 

- https://tracker.ceph.com/issues/47306
- https://tracker.ceph.com/issues/47179
- https://tracker.ceph.com/issues/46886

**Comment by tchaikov** [comment]
- https://pulpito.ceph.com/kchai-2020-09-10_16:44:13-rados-wip-kefu-testing-2020-09-10-1633-distro-basic-smithi
- https://pulpito.ceph.com/kchai-2020-09-11_02:31:36-rados-wip-kefu-testing-2020-09-10-1633-distro-basic-smithi/
- https://pulpito.ceph.com/kchai-2020-09-11_06:48:10-rados-wip-kefu-testing-2020-09-10-1634-distro-basic-smithi/

**Pull request merged**
