### PR TITLE
Yd for loicd

### PR DESCRIPTION
**Pull request by dupont-y**
Hi,
I need thoses 2 corrections for using install-deps.sh on fresh debian Jessie.

Quite sure the parsing "|" patch is needed for other debian version, less sure for zlib1g dependancy for rocksdb.

### CODE REVIEW

**Comment by dachary** [comment]
zlib1g-dev exists on:
* http://packages.ubuntu.com/precise/zlib1g-dev
* http://packages.ubuntu.com/trusty/zlib1g-dev

**Comment by dachary** [comment]
It is already installed on all gitbuilders, presumably because it already is an indirect dependency
<pre>
$ for target in gitbuilder-ceph-deb-trusty-amd64-notcmalloc gitbuilder-ceph-deb-trusty-amd64-basic gitbuilder-ceph-deb-precise-amd64-notcmalloc gitbuilder-ceph-deb-precise-amd64-basic ; do ssh $target dpkg -l zlib1g-dev ; done
Warning: Permanently added 'gitbuilder-ceph-deb-trusty-amd64-notcmalloc,10.214.139.123' (ECDSA) to the list of known hosts.
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                                   Version                                    Architecture Description
+++-======================================-==========================================-============-===============================================================================
ii  zlib1g-dev:amd64                       1:1.2.8.dfsg-1ubuntu1                      amd64        compression library - development
Warning: Permanently added 'gitbuilder-ceph-deb-trusty-amd64-basic,10.214.139.77' (ECDSA) to the list of known hosts.
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                                   Version                                    Architecture Description
+++-======================================-==========================================-============-===============================================================================
ii  zlib1g-dev:amd64                       1:1.2.8.dfsg-1ubuntu1                      amd64        compression library - development
Warning: Permanently added 'gitbuilder-ceph-deb-precise-amd64-notcmalloc,10.214.139.18' (ECDSA) to the list of known hosts.
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                              Version                                             Description
+++-=================================-===================================================-==============================================================================
ii  zlib1g-dev                        1:1.2.3.4.dfsg-3ubuntu4                             compression library - development
Warning: Permanently added 'gitbuilder-ceph-deb-precise-amd64-basic,10.214.139.2' (ECDSA) to the list of known hosts.
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                              Version                                             Description
+++-=================================-===================================================-==============================================================================
ii  zlib1g-dev                        1:1.2.3.4.dfsg-3ubuntu4                             compression library - development
</pre>

**Comment by dupont-y** [comment]
| parsing is necessary  because of this patch :

 https://github.com/ceph/ceph/commit/6a45b8ed041514816d09b2808d2d390eadbd0dd9#diff-d837a1c17de0268bcea321239ddbed47

**Comment by dachary** [comment]
zlib1g-dev is installed on jessie, indirectly. If it's missing on your machine, the problem is elsewhere. Moved the | fix to https://github.com/ceph/ceph/pull/3882 for your review.

**Comment by dupont-y** [comment]
Really not sure zlib1g-dev is installed by default on jessie ! It's a -dev package and at least on my docker instances, it's not the case. Anyway I'll double check on jessie & other debian versions.

**Pull request closed without merging**
