### PR TITLE
rbd-mirror: FAILED assert(!m_status_watcher)

### PR DESCRIPTION
**Pull request by trociny**
Fixes: http://tracker.ceph.com/issues/16245
Signed-off-by: Mykola Golub <mgolub@mirantis.com>

### CODE REVIEW

**Comment by trociny** [comment]
@dillaman Observed this when running rbd_mirror_stress.sh, on "TEST: create many images".

**Comment by dillaman** [comment]
lgtm

**Comment by dillaman** [comment]
Fails pretty consistently now when running rbd_mirror.sh (although I am not sure why) -- 3 out of 3 tries and passed 2 out of two once reverted:
> ceph --admin-daemon /tmp/tmp.rbd_mirror/rbd-mirror.cluster1_daemon.cluster1.asok rbd mirror flush mirror/test2
> Invalid command:  unused arguments: ['mirror/test2']
> rbd mirror flush :  flush rbd mirror

**Comment by dillaman** [comment]
... looks like a race condition in rbd_mirror.sh although still not sure why it occurs more often with this change.

**Pull request merged**
