### PR TITLE
jewel: rgw: multisite: log_meta on secondary zone causes continuous loop of metadata sync

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/20292
http://tracker.ceph.com/issues/20530

### CODE REVIEW

**Comment by mattbenjamin** [comment]
@amitkumar50 isn't it just prepending "jewel: "?  The folks adding this are either core members of the backport team or maintainers coordinating with them.  I'd focus attention elsewhere to improve quality, as I think this is basically a best practice--or certainly a good one.

**Comment by smithfarm** [comment]
Yeah, the "jewel: " prefix on the PR title makes it immediately obvious that the PR is targeting a stable branch. This is useful when perusing lists of PRs in the github GUI, for example.

**Comment by amitkumar50** [comment]
@mattbenjamin Hey matt my point was not prepending 'jewel'. My point was why PR heading text is way bigger than 72 characters also?

**Comment by yehudasa** [comment]
@smithfarm why is the filestore commit needed here?

**Comment by smithfarm** [comment]
@yehudasa The filestore commit was part of https://github.com/ceph/ceph/pull/15777/commits so it was just cherry-picked along with the other commits in that PR. It looks like a "cleanup" type commit so I'll drop it.

**Comment by smithfarm** [comment]
This passed an rgw suite at http://tracker.ceph.com/issues/20613#note-63

**Pull request merged**
