### PR TITLE
qa/tasks/cephadm: Make hostname change idempotent

### PR DESCRIPTION
**Pull request by zmc**
Inside a container, we may already have a short hostname - and also lack
the privileges to change it.

Signed-off-by: Zack Cerza <zack@redhat.com>

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [x] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by zmc** [comment]
This PR depends on https://github.com/ceph/teuthology/pull/1711

**Comment by zmc** [comment]
https://github.com/ceph/teuthology/pull/1711 is merged

**Review by jdurgin — APPROVED** [review]

**Comment by zmc** [comment]
testing here https://pulpito.ceph.com/zack-2022-03-10_20:07:11-smoke-master-distro-default-smithi/

**Comment by zmc** [comment]
Tested here: https://pulpito.ceph.com/zack-2022-03-11_01:40:50-orch:cephadm:smoke-master-distro-default-smithi/

**Pull request merged**
