### PR TITLE
DNM: nautilus: osd: Fix the way that auto repair triggers after regular scrub

### PR DESCRIPTION
**Pull request by dzafman**

### CODE REVIEW

**Comment by dzafman** [comment]
TESTING PASSED
http://pulpito.ceph.com/dzafman-2019-05-31_08:12:10-rados-wip-zafman-testing-nautilus-distro-basic-smithi/
3 valgrind
1 infrastructure

**Comment by dzafman** [comment]
jenkins retest make check

**Comment by djgalloway** [comment]
jenkins test make check

**Comment by djgalloway** [comment]
I installed this on the Sepia LRC and the warnings went away FWIW.

**Comment by dzafman** [comment]
This must wait for ceph/ceph#28334 to merge in case any changes to master occur.

**Pull request closed without merging**
