### PR TITLE
doc: update doc for with new pool settings

### PR DESCRIPTION
**Pull request by guangyy**
The code change of both parameters have been merged, update the doc accordingly.

Signed-off-by: Guang Yang yguang@yahoo-inc.com

### CODE REVIEW

**Comment by guangyy** [comment]
@tchaikov , you are right, let me update the section.

**Comment by guangyy** [comment]
Rebased to resolve the conflicts. Hi @tchaikov , could you please help to review? Thanks!

**Comment by guangyy** [comment]
@tchaikov , yeah I agree, will update accordingly. Thanks.

**Comment by guangyy** [comment]
@tchaikov , had another looks, it seems for others settings (including cache_min_evict_age), the description of the GET section is just a copy-paste of SET section. Did I miss anything?

**Comment by guangyy** [comment]
@tchaikov , right.. my bad (I realized that yesterday as well when I was trying to rebase).

In order to keep things consistent, I may add another commit to make all *description* at GET section to point to SET section, not just fast_read?

**Comment by dachary** [comment]
<pre>
Reviewed-by: Loic Dachary &lt;ldachary@redhat.com>
</pre>

after a rebase

**Comment by tchaikov** [comment]
> In order to keep things consistent, I may add another commit to make all description at GET section to point to SET section, not just fast_read?

that sounds good =)

**Comment by guangyy** [comment]
@tchaikov , updated with in-doc reference for all pool setting stuff, please help check. Thanks!

**Comment by dachary** [comment]
@guangyy please ignore the false negative from the bot, it has been fixed yesterday and should no longer bother you :-) http://tracker.ceph.com/issues/13176

**Comment by guangyy** [comment]
@dachary , thanks for looking into it.

**Pull request merged**
