### PR TITLE
test/test-erasure-code: spin off EIO tests to avoid lingering OSD processes after tests finishes

### PR DESCRIPTION
**Pull request by tchaikov**
Fixes: #11693 http://tracker.ceph.com/issues/11693
Signed-off-by: Kefu Chai <kchai@redhat.com>

### CODE REVIEW

**Comment by XinzeChi** [comment]
:+1:

**Comment by dachary** [comment]
let's do it in a more robust way : setup + inject + verify crash + teardown. Once for shard id 0 and once for shard id 1. That will be way more robust.

**Comment by tchaikov** [comment]
@dachary thanks for your review.  i addressed your comments in the latest change.

**Comment by tchaikov** [comment]
```
FAIL: ./src/test/erasure-code/test-erasure-eio.sh.log
../test-driver: line 95: ./test/erasure-code/test-erasure-eio.sh: Permission denied
+ test 1 = 124
+ success=false
+ false
```

still looking at this problem.

**Comment by dachary** [comment]
minor typos, otherwise much better
<pre>
Reviewed-by: Loic Dachary &lt;ldachary@redhat.com>
</pre>

**Comment by tchaikov** [comment]
@dachary, thanks for your review. i updated the pull request to address your comments. in addition, i also changed the existing test in `test_get_config()`, so it checks the overrided config passed in using command line, i think that was the original intention of the argument "--osd_pool_default_size", and it will make it a better test.

**Comment by dachary** [comment]
looks good !

**Pull request merged**
