### PR TITLE
squid: tracer/osd/librados/build/rgw: rgw and osd end2end tracing using open…

### PR DESCRIPTION
**Pull request by rzarzynski**
…telemetry

* build: add opentelemetry to cmake system crimson targets that uses Message.cc/h are built before opentelemetry (o-tel), so we need to build o-tel eralier so we also add the library to the include path earlier this shoud work for WITH_JAEGER flag both the ON/OFF cases, and for librados where the compilation flag is ignored

* msg/tracer: add o-tel trace to Messages with decode/encode function in tracer.h some files that uses Message.cc/h just need the encode/decode functions  and not all others functions. some crimson targets does not link with ceph_context (common) which is required for tracer.cc file. so we just need to include that functions

* librados: Add opentelemtry trace param for aio_operate and operate methods in order to propagate the trace info I added the otel-trace as an extra param. in some places, there already was a blkin trace info, and since it is not used in other places we can safely change it to o-tel trace info. this will be done in another commit, so the cleanup of blkin trace will be in a dedicated commit

* osd: use the o-tel trace of the msg as a parent span of the osd trace if there is a valid span in the msg, we will add this op to the request trace, otherwise it will start a new trace for the OSD op

* rgw: pass put obj trace info to librados in order to make it possible, I saved the trace info inside the sal::Object, so we can use it later when writing the object to rados it could be used also later for read ops.
note the trace field of req_state is initalized only in rgw_process, so it's also required in librgw request flow

* prevent breaking channges to kSize. make sure that changes between components built with different versions of OTEL do not break message compatibility

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Comment by rzarzynski** [comment]
This is the squid backport of https://github.com/ceph/ceph/pull/55625.

**Comment by rzarzynski** [comment]
Known make check failure:

```
The following tests FAILED:
	240 - unittest-seastar-socket (Subprocess aborted)
```

**Comment by rzarzynski** [comment]
jenkins test make check

**Comment by rzarzynski** [comment]
Linking the orignal: 52114.

**Comment by cbodley** [comment]
@rzarzynski i really appreciate your help pushing this one through ❤️ 

i'm tracking an rgw regression from this pr on main in https://tracker.ceph.com/issues/64543. we'll need the fix from https://github.com/ceph/ceph/pull/55722 to get a clean rgw run for squid

**Comment by cbodley** [comment]
jenkins test api

**Review by cbodley — APPROVED** [review]

**Comment by cbodley** [comment]
@rzarzynski @ljflores does this need a rados suite run too?

**Comment by rzarzynski** [comment]
@cbodley: yes, I would prefer to not skip the workflow.

ping @yuriw, @ljflores.

**Comment by cbodley** [comment]
@yuriw please make sure this one gets a rados suite (see https://tracker.ceph.com/issues/64973#note-14)

**Comment by ljflores** [comment]
Rados approved: https://tracker.ceph.com/projects/rados/wiki/SQUID#httpstrackercephcomissues64973

**Pull request merged**
