### PR TITLE
deps: increase the node version to 16

### PR DESCRIPTION
**Pull request by nizamial09**
With node 14, the angular 13 is going into some issues with node-gyp.
```
prebuild-install || node-gyp rebuild

prebuild-install WARN install No prebuilt binaries found (target=14.20.0 runtime=node arch=x64 libc= platform=linux)
make: Entering directory '/home/jenkins-build/build/workspace/ceph-dashboard-cephadm-e2e/src/pybind/mgr/dashboard/frontend/node_modules/tree-sitter/build'
  CC(target) Release/obj.target/tree_sitter/vendor/tree-sitter/lib/src/lib.o
  AR(target) Release/obj.target/tree_sitter.a
  COPY Release/tree_sitter.a
  CXX(target) Release/obj.target/tree_sitter_runtime_binding/src/binding.o
```
and in some other environments its like `cb() never called` and stops
the whole `npm ci` process.

After some research, looks like updating node is the way to stop this.

With node16, ` npm 7 will block installations if an upstream dependency
conflict is present that cannot be automatically resolved.` https://github.blog/2021-02-02-npm-7-is-now-generally-available/#peer-dependencies, which is fixed by passing `legacy-peer-deps` in the `.npmrc`

Fixes: https://tracker.ceph.com/issues/62107

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by ktdreyer** [comment]
The commit message says "what", but not "why" - could you elaborate?

**Comment by nizamial09** [comment]
> The commit message says "what", but not "why" - could you elaborate?

done

**Comment by nizamial09** [comment]
to remove the `legacy-peer-deps` warning in `npm ci` the npm dependencies needs to be updated. https://tracker.ceph.com/issues/62108

**Review by avanthakkar — APPROVED** [review]
LGTM!

**Review by aaSharma14 — APPROVED** [review]

**Pull request merged**
