### PR TITLE
osd: note down the number of missing clones

### PR DESCRIPTION
**Pull request by tchaikov**
Signed-off-by: Kefu Chai <kchai@redhat.com>

### CODE REVIEW

**Comment by tchaikov** [comment]
@dzafman , would you please take a look at this? thanks.

**Comment by dzafman** [comment]
Test case test/osd/osd-scrub-snaps.sh needs err_strings[6] to specify 2 missing clones instead of 1 as follows:

err_strings[6]="log_channel[(]cluster[)] log [[]INF[]] : scrub [0-9]*[.]0 [0-9]*/666934a3/obj5/head 2 missing clone[(]s[)]"

**Comment by dzafman** [comment]
Commit comment could say "Caused by: 2e0bb0ae9498fd9a0c49f1b81bf0c86f7a7cac42"

**Comment by dzafman** [comment]
:+1: after it passes Jenkins

**Pull request merged**
