### PR TITLE
client,mds: Drop execute permission bits

### PR DESCRIPTION
**Pull request by joscollin**
Drop execute permission bits of Client.cc and CDir.cc. Seeing this for a while, so created the PR.

### CODE REVIEW

**Comment by joscollin** [comment]
retest this please

**Review by batrick — APPROVED** [review]

**Comment by joscollin** [comment]
jenkins test make check

**Comment by batrick** [comment]
jenkins test api

**Comment by joscollin** [comment]
jenkins test api

**Pull request merged**
