### PR TITLE
common, auth: use boost::spirit to parse ceph.conf, escape quotes in exported auths

### PR DESCRIPTION
**Pull request by tchaikov**
Fixes: http://tracker.ceph.com/issues/22227

### CODE REVIEW

**Comment by tchaikov** [comment]
@badone indeed. seems i broke `ceph-authtool`. lemme look into it.

**Comment by tchaikov** [comment]
@badone it turns out we pass `/dev/null` as the path of `ceph.conf` and expect that the parser return an empty `ConfFile`.  i updated the sanity check to handle this case by ignoring non-regular file.

also, as a bonus,  i updated the `ConfUtils.{h,cc}` to reimplement the trim helpers using boost::algorithm library.

**Comment by neha-ojha** [comment]
retest this please

**Comment by badone** [comment]
> Tests that failed:  ceph-conf

May not be quite there yet @tchaikov

**Comment by tchaikov** [comment]
retest this please

**Comment by tchaikov** [comment]
@badone i think it's should ready for another round of review.

**Comment by tchaikov** [comment]
http://pulpito.ceph.com/kchai-2019-06-20_05:33:07-rados-wip-kefu-testing-2019-06-20-1103-distro-basic-smithi/

the valgrind failures are caused by #27834

**Comment by tchaikov** [comment]
fixed the commit message and repushed.

@neha-ojha i will send a follow-up PR to update `doc/rados/configuration/ceph-conf.rst` to document the the changes.

**Pull request merged**
