### PR TITLE
pybind/ceph_daemon: add type annotations

### PR DESCRIPTION
**Pull request by tchaikov**
## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Review by sebastian-philipp — APPROVED** [review]
Is there a call to mypy that verifies this? https://github.com/ceph/ceph/blob/master/src/pybind/tox.ini is pretty much empty

**Comment by tchaikov** [comment]
@sebastian-philipp will add it to tox.ini in a follow-up change. was scrubbing my local repo just now. just realized there was something i haven't pushed to github yet.

**Comment by tchaikov** [comment]
- https://pulpito.ceph.com/kchai-2021-05-25_04:17:20-rados-wip-kefu-testing-2021-05-25-1039-distro-basic-smithi/
- https://pulpito.ceph.com/kchai-2021-05-25_14:42:43-rados-wip-kefu-testing-2021-05-25-2008-distro-basic-smithi/

failure tracked by

- https://tracker.ceph.com/issues/45423

**Comment by tchaikov** [comment]
@sebastian-philipp #41704

**Pull request merged**
