### PR TITLE
cmake: use gtest-parallel to speedup unittests

### PR DESCRIPTION
**Pull request by tchaikov**

### CODE REVIEW

**Comment by tchaikov** [comment]
retest this please.

**Comment by ErwanAliasr1** [comment]
This PR seems to have dpdk issues. Does it need a rebase ?

**Comment by ErwanAliasr1** [comment]
A new test got integrated recently and I didn't saw it when I was preparing my PR.

128/157 Test #128: unittest_alloc_bench ....................   Passed  969.92 sec

This test is seriously long and running it with gtest-parallel works perfectly with a significant improve in running time.

erwan@mr-meeseeks:~/ceph/build (evelu-parallel)$ ../src/test/gtest-parallel/gtest-parallel bin/unittest_alloc_bench
[10/10] Allocator/AllocTest.test_alloc_bench_10_300/0 (510613 ms) 

The running time is nearly divided by two saving 400 secs (6m30).

The required change is 
- src/test/objectstore/CMakeLists.txt:  add_ceph_unittest(unittest_alloc_bench)
+ src/test/objectstore/CMakeLists.txt:  add_ceph_unittest(unittest_alloc_bench parallel)

**Comment by ErwanAliasr1** [comment]
@tchaikov I had a quick discussion with @ifed01 and it appear that running unittest_alloc_bench in every make check is perfectly useless as it only try to estimate a performance.
There is no reason of consuming so much time in our CI with it.

So can you update the commit to remove it instead of adding the parallel thing in it ?
I'm sorry to ask you doing my work but I can't edit the commit anymore :(

**Comment by tchaikov** [comment]
@ErwanAliasr1 probably you can also pull this PR into your branch and create a new PR? i didn't intend to hijack your PR, just wanted to add some changes on top of yours.

**Comment by ErwanAliasr1** [comment]
Closing in favor of #22577 to get the latest patches.

**Pull request closed without merging**
