### PR TITLE
qa/distros: Don't let focal sleep

### PR DESCRIPTION
**Pull request by badone**
Seems we may have chosen a workstation fog image for ubuntu focal 20.04 that is going to sleep during teuthology tests resulting in an apparent 'hang' scenario. This PR disables all system sleep/suspend/hibernation on that distro.

This is a quick hack to get us by until we can organise a new image/config.

Fixes: https://tracker.ceph.com/issues/49152

Signed-off-by: Brad Hubbard <bhubbard@redhat.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by badone** [comment]
jenkins test make check

**Comment by jdurgin** [comment]
@djgalloway could we disable this in the focal image?

**Review by sebastian-philipp — APPROVED** [review]

**Comment by djgalloway** [comment]
> @djgalloway could we disable this in the focal image?

Yes, this should not go in the ceph repo.  I will create a PR in ceph-cm-ansible.

**Comment by badone** [comment]
Closed in favour of https://github.com/ceph/ceph-cm-ansible/pull/606

**Pull request closed without merging**
