### PR TITLE
Messenger: Fix bad crc when different header crc config set

### PR DESCRIPTION
**Pull request by yuyuyu101**
If initiator disable header crc and receiver enable header crc, we need to check message whether header' crc is trusted(!= 0);

### CODE REVIEW

**Comment by liewegas** [comment]
a crc of 0 is valid (altho only a 1/2^32 probabilty).

Is this covering the case where crc is disabled after the connection is established?  Do we care about that case?

**Comment by yuyuyu101** [comment]
@liewegas Yes, this should cover the case even if setting crc config inflight.

Because ceph_msg_header doesn't contain "flags" field to extend header crc flag, so we use "0" to decide whether to enable/disable it.

Do you think we only need to use "flags" in ceph_msg_connect like "CEPH_MSG_CONNECT_LOSSY" and exchange crc settings when shakehand instead of this way?

I just remember we could do this in connect/accept process, maybe that should be better

**Comment by liewegas** [comment]
I'm not sure how useful/interesting it is to enable/disable crcs while 
running (especially header ones) since the only good reason i've seen for 
doing so it RDMA having strong checksums already, and that doesn't change 
at runtime.  do we really need to do anything here?

**Comment by yuyuyu101** [comment]
Hmm, sorry, I got your meaning still now. I stucked into the exception and still recall that this broken case isn't a normal way.

Close this.

**Pull request closed without merging**
