### PR TITLE
mgr/dashboard: Cluster Creation Add multiple hosts at once

### PR DESCRIPTION
**Pull request by aaSharma14**
Add multiple hosts at once in cluster creation wizard

Fixes: https://tracker.ceph.com/issues/52759
Signed-off-by: Aashish Sharma <aasharma@redhat.com>

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by aaSharma14** [comment]
This PR is a follow-up of https://github.com/ceph/ceph/pull/43283

**Comment by avanthakkar** [comment]
jenkins test api

**Comment by avanthakkar** [comment]
jenkins test make check arm64

**Comment by nizamial09** [comment]
`npm ci` fails and therefore frontend dists are not made. And that causes cephadm jobs to fail too.
```
✔ Browser application bundle generation complete.

Error: src/app/ceph/cluster/hosts/host-form/host-form.component.html:24:19 - error NG5002: Cannot mark an element as translatable inside of a translatable section. Please remove the nested i18n marker.

24                   <li i18n>a comma-separated list of hostnames <samp>(e.g.: example-01,example-02,example-03)</samp>,</li>
                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  src/app/ceph/cluster/hosts/host-form/host-form.component.ts:19:16
    19   templateUrl: './host-form.component.html',
                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    Error occurs in the template of component HostFormComponent.



npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ceph-dashboard@0.0.0 build: `npm run env_build && ng build --configuration=$npm_package_config_locale "--prod"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ceph-dashboard@0.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/jenkins-build/.npm/_logs/2021-10-21T17_18_43_401Z-debug.log
```

**Pull request merged**
