### PR TITLE
pybind: Avoid type error in crush rule (str, not an int)

### PR DESCRIPTION
**Pull request by tchaikov**
this pull request succeeds #3139. for more context, please see the discussions in #3139.

* Make crush_rule parameter an int in create_pool

Signed-off-by: Jeff Epstein <jeff.epstein@commerceguys.com>
Signed-off-by: Kefu Chai <kchai@redhat.com>

### CODE REVIEW

**Comment by tchaikov** [comment]
@alfredodeza ping?

**Comment by alfredodeza** [comment]
@tchaikov I am not sure I can provide proper feedback on this since I am not sure about these changes and mostly anything pybind related

**Comment by tchaikov** [comment]
@alfredodeza oh, i see, thanks anyway =)

**Comment by liewegas** [comment]
@jdurgin ?

**Pull request merged**
