### PR TITLE
deb,rpm: Sphinx 3.0 is now required to build the docs

### PR DESCRIPTION
**Pull request by smithfarm**
Fixes: https://tracker.ceph.com/issues/47628
Signed-off-by: Nathan Cutler <ncutler@suse.com>

### CODE REVIEW

**Comment by tchaikov** [comment]
might want to backport #33888 as well.

**Review by tchaikov — CHANGES_REQUESTED** [review]
there is no need to use sphinx3 in our packaging. please note, rpm/debian packaging does not build https://docs.ceph.com . rpm/debian packaging only build the manpages, whose `conf.py` is located at https://github.com/ceph/ceph/blob/master/man/conf.py, which does not use sphinx-autodoc-typehints at all.

**Comment by smithfarm** [comment]
@tchaikov Sure, I was only trying to fix the failing `Docs: build check` issue in octopus which was apparently caused by the missing backport of #33888

**Comment by smithfarm** [comment]
@tchaikov I assigned https://tracker.ceph.com/issues/47628 to you. Please review the Backport field.

**Comment by tchaikov** [comment]
> @tchaikov Sure, I was only trying to fix the failing `Docs: build check` issue in octopus which was apparently caused by the missing backport of #33888

i was assigned as a reviewer  hence the comment.

**Pull request closed without merging**
