### PR TITLE
cls: new force-promotion flag for class methods

### PR DESCRIPTION
**Pull request by dillaman**
Class methods that use the cls_get_request_origin should not be
proxied to a base tier -- otherwise the origin will reflect the
cache tier instead of the client.

Fixes: #13380

Signed-off-by: Jason Dillaman <dillaman@redhat.com>

### CODE REVIEW

**Comment by dillaman** [comment]
Verified rbd/cli/{base/install.yaml cachepool/small.yaml clusters/fixed-1.yaml features/object_map.yaml fs/btrfs.yaml msgr-failures/few.yaml workloads/rbd_cli_copy.yaml} test case now passes

**Comment by jdurgin** [comment]
It seems like making Message::get_orig_source_inst() actually have the original source instance would be more generally useful. It seems like this could cause scheduling problems for forwarded requests otherwise.

**Comment by dillaman** [comment]
I thought about adding the client data -- but since the proxy ops are just forwarding the standard op, the message payload would need to be expanded to include the originator. Then I thought it might introduce a (minor) security hole since at that point, anybody could craft a message saying that they were anybody (without adding additional logic to stop bad actors). 

In the long term, I think forwarding the origin fits in nicely with a future capability to forward / act-on-the-behalf-of clients.

**Comment by athanatos** [comment]
Passed tests

**Pull request merged**
