### PR TITLE
radosgw-admin: add missing 'zonegroup remove'

### PR DESCRIPTION
**Pull request by cbodley**
'zone delete' is currently the only way to remove a zone from a zonegroup, but it can only be run on that zone's local cluster. 'zonegroup remove' is needed to remove a zone from its zonegroup, a) from another cluster, or b) without deleting the zone itself.

### CODE REVIEW

**Comment by yehudasa** [comment]
@cbodley lgtm, maybe add a test for it?

**Comment by cbodley** [comment]
@yehudasa would you recommend testing this with test/rgw/test_multi.py? or ceph-qa-suite?

**Comment by yehudasa** [comment]
@cbodley test_mutli.py probably. We'll need to get it integrated with teuthology eventually.

**Comment by cbodley** [comment]
updated with test_zonegroup_remove() in test_multi.py

**Pull request merged**
