### PR TITLE
qa/rgw/upgrade: add reef as a starting release

### PR DESCRIPTION
**Pull request by cbodley**
start testing upgrades from reef

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by cbodley** [comment]
i guess this is blocked on https://github.com/ceph/ceph/pull/53191 to update the ceph version to squid/19:

> 2023-10-12T00:46:57.726 INFO:teuthology.task.install:Ceph deb upgrade from 18.2.0-640-g1a1059b0-1jammy to 18.0.0-6685-g139f9d15-1jammy
2023-10-12T00:46:57.727 ERROR:teuthology.run_tasks:Saw exception from tasks.
Traceback (most recent call last):
  File "/home/teuthworker/src/git.ceph.com_teuthology_8cdab074dcca9a68965bc5a50e9c30b691949723/teuthology/run_tasks.py", line 109, in run_tasks
    manager.__enter__()
  File "/usr/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/home/teuthworker/src/git.ceph.com_teuthology_8cdab074dcca9a68965bc5a50e9c30b691949723/teuthology/task/install/__init__.py", line 405, in upgrade
    upgrade_common(ctx, config, upgrade_old_style)
  File "/home/teuthworker/src/git.ceph.com_teuthology_8cdab074dcca9a68965bc5a50e9c30b691949723/teuthology/task/install/__init__.py", line 344, in upgrade_common
    raise RuntimeError(
RuntimeError: An attempt to upgrade from a higher version to a lower one will always fail. Hint: check tags in the target git branch.

from http://qa-proxy.ceph.com/teuthology/cbodley-2023-10-11_17:53:41-rgw-main-distro-default-smithi/7422112/teuthology.log

**Comment by cbodley** [comment]
> i guess this is blocked on #53191 to update the ceph version to squid/19

rebased now that it's hopefully unblocked

**Comment by cbodley** [comment]
reef upgrade jobs succeeded in https://pulpito.ceph.com/cbodley-2024-01-04_14:48:31-rgw-wip-cbodley-testing-distro-default-smithi/

**Comment by cbodley** [comment]
ping @ceph/rgw, this passed qa and just needs an approval

**Review by smanjara — APPROVED** [review]

**Pull request merged**
