### PR TITLE
librbd: rbd ack cleanup

### PR DESCRIPTION
**Pull request by runsisi**
since #12607 has killed the distinction between onack and onsafe, we can do a little bit cleanup now

Signed-off-by: runsisi <runsisi@zte.com.cn>

### CODE REVIEW

**Comment by runsisi** [comment]
@dillaman @trociny please take a look, thanks!

**Comment by dillaman** [comment]
@runsisi I would just squash the four commits down to a single commit since it doesn't compile after the first one.

**Comment by runsisi** [comment]
@dillaman updated, thanks.

**Comment by dillaman** [comment]
retest this please

**Comment by dillaman** [comment]
retest this please

**Pull request merged**
