### PR TITLE
tools/osdmaptool: fix possible segfaults when there are down osds

### PR DESCRIPTION
**Pull request by trociny**
Signed-off-by: Mykola Golub <mykola.golub@clyso.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Review by neha-ojha — APPROVED** [review]

**Comment by ljflores** [comment]
jenkins retest this please

**Comment by ljflores** [comment]
http://pulpito.front.sepia.ceph.com/yuriw-2022-01-15_05:47:18-rados-wip-yuri8-testing-2022-01-14-1551-distro-default-smithi/
http://pulpito.front.sepia.ceph.com/yuriw-2022-01-17_17:14:22-rados-wip-yuri8-testing-2022-01-14-1551-distro-default-smithi/

Failures, unrelated:
    https://tracker.ceph.com/issues/45721
    https://tracker.ceph.com/issues/50280
    https://tracker.ceph.com/issues/53827
    https://tracker.ceph.com/issues/51076
    https://tracker.ceph.com/issues/53807
    https://tracker.ceph.com/issues/53842

Details:
    Bug_#45721: CommandFailedError: Command failed (workunit test rados/test_python.sh) FAIL: test_rados.TestWatchNotify.test
    Bug_#50280: cephadm: RuntimeError: uid/gid not found - Ceph
    Bug_#53827: cephadm exited with error code when creating osd. - Ceph - Orchestrator
    Bug_#51076: "wait_for_recovery: failed before timeout expired" during thrashosd test with EC backend.
    Bug_#53807: Dead jobs in rados/cephadm/smoke-roleless{...} - Ceph - Orchestrator
    Bug_#53842: cephadm/mds_upgrade_sequence: KeyError: 'en***'

**Comment by yuriw** [comment]
jenkins test make check

**Comment by yuriw** [comment]
jenkins test make check

**Comment by ljflores** [comment]
jenkins test make check arm64

**Comment by yuriw** [comment]
jenkins test make check

**Comment by yuriw** [comment]
jenkins test make check

**Comment by yuriw** [comment]
@trociny @ljflores 
This can be merged but can't pass `make check`

**Comment by ljflores** [comment]
> @trociny @ljflores This can be merged but can't pass `make check`

Thx @yuriw, it seems like there might be several widespread make check failures going on right now. Since this passed the teuthology requirements, I think it can still be merged but I'll double-check on that.

**Comment by ljflores** [comment]
jenkins test make check

**Comment by ljflores** [comment]
@yuriw some updates: The failure is unrelated, but let's hold off on merging this since the problem is so widespread. Neha and Radek are working on a solution to fix it here: #44675

**Comment by ljflores** [comment]
jenkins test make check

**Pull request merged**
