### PR TITLE
 doc: adds a way to allow users set_contents_from_filename for rgw

### PR DESCRIPTION
**Pull request by Kalkulus1**
Just added a way to allow users set_contents_from_filename.

### CODE REVIEW

**Comment by ideepika** [comment]
@Kalkulus1  can you amend the commit and do a git force push fixing cppcheck errors? also can you prefix the commit with component name:

```
 doc: adds a way to allow users set_contents_from_filename for rgw
```
 please also add a signed off by using -s during `git commit` stage or while writing git commit message, Thanks! 
please read: https://github.com/ceph/ceph/blob/master/SubmittingPatches.rst#describe-your-changes

**Comment by Kalkulus1** [comment]
> @Kalkulus1 can you amend the commit and do a git force push fixing cppcheck errors? also can you prefix the commit with component name:
> 
> ```
>  doc: adds a way to allow users set_contents_from_filename for rgw
> ```
> 
> please also add a signed off by using -s during `git commit` stage or while writing git commit message, Thanks!
> please read: https://github.com/ceph/ceph/blob/master/SubmittingPatches.rst#describe-your-ch

**Comment by Kalkulus1** [comment]
Sure working on it

**Comment by Kalkulus1** [comment]
doc: adds a way to allow users set_contents_from_filename for rgw

**Comment by Kalkulus1** [comment]
doc: adds a way to allow users set_contents_from_filename for rgw

**Review by Kalkulus1 — COMMENTED** [review]
doc: adds a way to allow users set_contents_from_filename for rgw

**Comment by ideepika** [comment]
@Kalkulus1 can you squash the two commits into one and use `git commit --amend --signoff` on the final commit. Also please fix cppCheck errors

**Comment by Kalkulus1** [comment]
> @Kalkulus1 can you squash the two commits into one and use `git commit --amend --signoff` on the final commit. Also please fix cppCheck errors

All right I will do that

**Comment by Kalkulus1** [comment]
@ideepika, I really don't know what I am doing wrong. Can you guide me?

**Comment by ideepika** [comment]
@Kalkulus1 can you fix cppCheck comments mentioned here: https://github.com/ceph/ceph/pull/42880/files
steps I would have followed:
0. from local repository clone(please google this if not familiar) checkout your pr branch
1. remove the merge commit using `git reset --hard 5007367` this will delete all commits after this commit
2. fix cppCheck comments mentioned here: https://github.com/ceph/ceph/pull/42880/files []
3. stage relevant changes using `git add -p`
4. add fixed changed to commit 5007367 using `git commit --amend` 
5. force push changes pr branch `git push fork-repo -f` 

HTH

**Comment by Kalkulus1** [comment]
> @Kalkulus1 can you fix cppCheck comments mentioned here: https://github.com/ceph/ceph/pull/42880/files
> steps I would have followed:
> 0. from local repository clone(please google this if not familiar) checkout your pr branch
> 
> 1. remove the merge commit using `git reset --hard 5007367` this will delete all commits after this commit
> 2. fix cppCheck comments mentioned here: https://github.com/ceph/ceph/pull/42880/files []
> 3. stage relevant changes using `git add -p`
> 4. add fixed changed to commit [5007367](https://github.com/ceph/ceph/commit/5007367c1455080fa55fcb7734619c9e63948beb) using `git commit --amend`
> 5. force push changes pr branch `git push fork-repo -f`
> 
> HTH

@ideepika Thank you. It worked and one failed again. This section: Signed-off-by — one or more commits in this PR are not signed

**Comment by Kalkulus1** [comment]
@ideepika worked now. I didn't signed-off my first commit.

**Review by cbodley — APPROVED** [review]
looks fine, but i tend to think we should just link to boto docs instead of maintaining these examples. especially when this doc still uses the old version of boto

**Comment by Kalkulus1** [comment]
> looks fine, but i tend to think we should just link to boto docs instead of maintaining these examples. especially when this doc still uses the old version of boto

I would love to contribute to the boto3 version if you are going to change it.

**Comment by mattbenjamin** [comment]
> 
> 
> looks fine, but i tend to think we should just link to boto docs instead of maintaining these examples. especially when this doc still uses the old version of boto

I certainly found the local examples helpful when learning RGW--I'd argue for keeping them, just clarifying maybe that they are not exhaustive?

**Comment by Kalkulus1** [comment]
@ideepika when will it be closed?

**Comment by ideepika** [comment]
@cbodley @mattbenjamin can we merge this?

**Comment by cbodley** [comment]
thanks @Kalkulus1. are you interested in adding boto3 examples too?

**Comment by Kalkulus1** [comment]
> thanks @Kalkulus1. are you interested in adding boto3 examples too?

Yes, I am very interested. I have good codes to share for that as well.

**Comment by cbodley** [comment]
great. we could either reuse this `python.rst` file, with different sections for boto2 and boto3, or have two them in two separate .rst files. i'll let you decide how to manage that

**Comment by Kalkulus1** [comment]
I think we should have them in two separate .rst files. It will make it easier for me/people to navigate on the docs page. Let me know your thought on this as well

**Comment by cbodley** [comment]
i agree, that should help avoid mistakes from people accidentally copy/pasting examples from the wrong section

**Comment by Kalkulus1** [comment]
Yes. So what's the plan to start the files?

**Comment by cbodley** [comment]
open a PR to add a new file for boto3 and update the index to point to it

**Comment by Kalkulus1** [comment]
Great. How do I point the index to the new file?

**Comment by cbodley** [comment]
that would be this part of the s3.rst: https://github.com/ceph/ceph/blob/master/doc/radosgw/s3.rst#api

```diff
    PHP <s3/php>
-   Python <s3/python>
+   Python (boto2) <s3/python>
+   Python (boto3) <s3/python_boto3>
    Ruby <s3/ruby>
```

**Comment by Kalkulus1** [comment]
Awesome. Thank you so much. Will work on it soon.

**Pull request merged**
