### PR TITLE
quincy: cephfs: add command "ceph fs swap"

### PR DESCRIPTION
**Pull request by rishabh-d-dave**
backport tracker: https://tracker.ceph.com/issues/63835

---

backport of https://github.com/ceph/ceph/pull/50212 but skips https://github.com/ceph/ceph/pull/50212/commits/03df86b7c54325fd577bacec6a1f4c6441117e72 because this trivial change would need more vstart_runner commits.
parent tracker: https://tracker.ceph.com/issues/58129

Also backports because these commits were pre-requisite to backport PR #50212 - https://github.com/ceph/ceph/pull/50882, https://github.com/ceph/ceph/pull/50665, https://github.com/ceph/ceph/pull/50498, https://github.com/ceph/ceph/pull/50497, https://github.com/ceph/ceph/pull/46168, https://github.com/ceph/ceph/pull/46994, https://github.com/ceph/ceph/pull/46993, https://github.com/ceph/ceph/pull/46991

this backport was staged using ceph-backport.sh version 16.0.0.6848
find the latest version at https://github.com/ceph/ceph/blob/master/src/script/ceph-backport.sh

### CODE REVIEW

**Comment by vshankar** [comment]
@rishabh-d-dave please rebase.

**Comment by rishabh-d-dave** [comment]
jenkins test api

**Comment by rishabh-d-dave** [comment]
jenkins test make check

**Comment by rishabh-d-dave** [comment]
Make check job failed - https://jenkins.ceph.com/job/ceph-pull-requests/132786/consoleFull#13711791732a811ea2-3e7b-466b-84b4-d13df7e35809. Copying from its console output - 

```
/home/jenkins-build/build/workspace/ceph-pull-requests/src/mon/FSCommands.cc:1299:40: error: use of undeclared identifier 'CEPH_MDSMAP_REFUSE_CLIENT_SESSION'
    if (!fs1p->get_mds_map().test_flag(CEPH_MDSMAP_REFUSE_CLIENT_SESSION) ||
                                       ^
/home/jenkins-build/build/workspace/ceph-pull-requests/src/mon/FSCommands.cc:1300:33: error: use of undeclared identifier 'CEPH_MDSMAP_REFUSE_CLIENT_SESSION'
        !fs2p->get_mds_map().test_flag(CEPH_MDSMAP_REFUSE_CLIENT_SESSION)) {
                                       ^
/home/jenkins-build/build/workspace/ceph-pull-requests/src/mon/FSCommands.cc:1301:42: error: use of undeclared identifier 'CEPH_MDSMAP_REFUSE_CLIENT_SESSION'
      if (!fs1p->get_mds_map().test_flag(CEPH_MDSMAP_REFUSE_CLIENT_SESSION) &&
                                         ^
/home/jenkins-build/build/workspace/ceph-pull-requests/src/mon/FSCommands.cc:1302:41: error: use of undeclared identifier 'CEPH_MDSMAP_REFUSE_CLIENT_SESSION'
          fs2p->get_mds_map().test_flag(CEPH_MDSMAP_REFUSE_CLIENT_SESSION)) {
                                        ^
/home/jenkins-build/build/workspace/ceph-pull-requests/src/mon/FSCommands.cc:1308:41: error: use of undeclared identifier 'CEPH_MDSMAP_REFUSE_CLIENT_SESSION'
          fs1p->get_mds_map().test_flag(CEPH_MDSMAP_REFUSE_CLIENT_SESSION) &&
                                        ^
/home/jenkins-build/build/workspace/ceph-pull-requests/src/mon/FSCommands.cc:1309:35: error: use of undeclared identifier 'CEPH_MDSMAP_REFUSE_CLIENT_SESSION'
          !fs2p->get_mds_map().test_flag(CEPH_MDSMAP_REFUSE_CLIENT_SESSION)) {
                                         ^
/home/jenkins-build/build/workspace/ceph-pull-requests/src/mon/FSCommands.cc:1315:42: error: use of undeclared identifier 'CEPH_MDSMAP_REFUSE_CLIENT_SESSION'
          !fs1p->get_mds_map().test_flag(CEPH_MDSMAP_REFUSE_CLIENT_SESSION) &&
                                         ^
/home/jenkins-build/build/workspace/ceph-pull-requests/src/mon/FSCommands.cc:1316:35: error: use of undeclared identifier 'CEPH_MDSMAP_REFUSE_CLIENT_SESSION'
          !fs2p->get_mds_map().test_flag(CEPH_MDSMAP_REFUSE_CLIENT_SESSION)) {
                                         ^
8 errors generated.
```

So, after 23 additional commits, now this backport needs another feature to be backported - https://github.com/ceph/ceph/pull/48720.

**Comment by rishabh-d-dave** [comment]
I spent some time with rebase, there are plenty conflicts in it that will take some time. Postponing that until we know whether this PR should be closed or should progress towards merge.

**Comment by vshankar** [comment]
> @vshankar
> 
> Make check job failed - https://jenkins.ceph.com/job/ceph-pull-requests/132786/consoleFull#13711791732a811ea2-3e7b-466b-84b4-d13df7e35809. Copying from its console output -
> 
> ```
> /home/jenkins-build/build/workspace/ceph-pull-requests/src/mon/FSCommands.cc:1299:40: error: use of undeclared identifier 'CEPH_MDSMAP_REFUSE_CLIENT_SESSION'
>     if (!fs1p->get_mds_map().test_flag(CEPH_MDSMAP_REFUSE_CLIENT_SESSION) ||
>                                        ^
> /home/jenkins-build/build/workspace/ceph-pull-requests/src/mon/FSCommands.cc:1300:33: error: use of undeclared identifier 'CEPH_MDSMAP_REFUSE_CLIENT_SESSION'
>         !fs2p->get_mds_map().test_flag(CEPH_MDSMAP_REFUSE_CLIENT_SESSION)) {
>                                        ^
> /home/jenkins-build/build/workspace/ceph-pull-requests/src/mon/FSCommands.cc:1301:42: error: use of undeclared identifier 'CEPH_MDSMAP_REFUSE_CLIENT_SESSION'
>       if (!fs1p->get_mds_map().test_flag(CEPH_MDSMAP_REFUSE_CLIENT_SESSION) &&
>                                          ^
> /home/jenkins-build/build/workspace/ceph-pull-requests/src/mon/FSCommands.cc:1302:41: error: use of undeclared identifier 'CEPH_MDSMAP_REFUSE_CLIENT_SESSION'
>           fs2p->get_mds_map().test_flag(CEPH_MDSMAP_REFUSE_CLIENT_SESSION)) {
>                                         ^
> /home/jenkins-build/build/workspace/ceph-pull-requests/src/mon/FSCommands.cc:1308:41: error: use of undeclared identifier 'CEPH_MDSMAP_REFUSE_CLIENT_SESSION'
>           fs1p->get_mds_map().test_flag(CEPH_MDSMAP_REFUSE_CLIENT_SESSION) &&
>                                         ^
> /home/jenkins-build/build/workspace/ceph-pull-requests/src/mon/FSCommands.cc:1309:35: error: use of undeclared identifier 'CEPH_MDSMAP_REFUSE_CLIENT_SESSION'
>           !fs2p->get_mds_map().test_flag(CEPH_MDSMAP_REFUSE_CLIENT_SESSION)) {
>                                          ^
> /home/jenkins-build/build/workspace/ceph-pull-requests/src/mon/FSCommands.cc:1315:42: error: use of undeclared identifier 'CEPH_MDSMAP_REFUSE_CLIENT_SESSION'
>           !fs1p->get_mds_map().test_flag(CEPH_MDSMAP_REFUSE_CLIENT_SESSION) &&
>                                          ^
> /home/jenkins-build/build/workspace/ceph-pull-requests/src/mon/FSCommands.cc:1316:35: error: use of undeclared identifier 'CEPH_MDSMAP_REFUSE_CLIENT_SESSION'
>           !fs2p->get_mds_map().test_flag(CEPH_MDSMAP_REFUSE_CLIENT_SESSION)) {
>                                          ^
> 8 errors generated.
> ```
> 
> So, after 23 additional commits, now this backport needs another feature to be backported - #48720.

The tracker for https://github.com/ceph/ceph/pull/48720 does not mention why its not a candidate for backporting but I presume this was discussed (somewhere) and a conclusion was made. So, we'll have to adjust this backport accordingly.

What's more worrying in the sheer number of dependent commits in this backport. Why did we ended up creating some many dependencies? We should try to limit that in the future.

**Comment by rishabh-d-dave** [comment]
> > @vshankar
> > So, after 23 additional commits, now this backport needs another feature to be backported - #48720.
> 
> The tracker for #48720 does not mention why its not a candidate for backporting but I presume this was discussed (somewhere) and a conclusion was made. So, we'll have to adjust this backport accordingly.
> 
> What's more worrying in the sheer number of dependent commits in this backport. Why did we ended up creating some many dependencies? We should try to limit that in the future.

We didn't create them deliberately. QA changes from original PR depended on lots of QA changes from last couple of years which were naturally absent in Quincy. To backport QA changes from original PR, backporting lots of those improvements/bug-fixes was necessary.

**Comment by rishabh-d-dave** [comment]
> The tracker for #48720 does not mention why its not a candidate for backporting but I presume this was discussed (somewhere) and a conclusion was made. So, we'll have to adjust this backport accordingly.
> 

You asked me to backport "fs swap" PR to quincy and reef for a BZ (I've sent a message on G-chat for more details about this). Reef backport has been merged, Quincy backport is left.

> What's more worrying in the sheer number of dependent commits in this backport. Why did we ended up creating some many dependencies? We should try to limit that in the future.

We didn't create them deliberately. QA changes from original PR depended on lots of QA changes from last couple of years which were naturally absent in Quincy. To backport QA changes from original PR, backporting lots of those improvements/bug-fixes was necessary.

**Comment by vshankar** [comment]
> > The tracker for #48720 does not mention why its not a candidate for backporting but I presume this was discussed (somewhere) and a conclusion was made. So, we'll have to adjust this backport accordingly.
> 
> You asked me to backport "fs swap" PR to quincy and reef for a BZ (I've sent a message on G-chat for more details about this). Reef backport has been merged, Quincy backport is left.

I know that. My question was regarding the tracker https://tracker.ceph.com/issues/57090 failing to mention about why backport isn't required.

> 
> > What's more worrying in the sheer number of dependent commits in this backport. Why did we ended up creating some many dependencies? We should try to limit that in the future.
> 
> We didn't create them deliberately. QA changes from original PR depended on lots of QA changes from last couple of years which were naturally absent in Quincy.

Those QA changes weren't backported to quincy then I believe.

**Comment by rishabh-d-dave** [comment]
Had a chat with Venky and Greg about this. It's fine to close this backport PR since it depends on another feature despite of 23 commits that've been added to it besides the original 9.

**Pull request closed without merging**
