### PR TITLE
quincy: librados: aio operate functions can set mtimes

### PR DESCRIPTION
**Pull request by cbodley**
backport tracker: https://tracker.ceph.com/issues/61731

---

backport of https://github.com/ceph/ceph/pull/51681
parent tracker: https://tracker.ceph.com/issues/61349

this backport was staged using ceph-backport.sh version 16.0.0.6848
find the latest version at https://github.com/ceph/ceph/blob/main/src/script/ceph-backport.sh

### CODE REVIEW

**Review by ljflores — APPROVED** [review]

**Comment by yuriw** [comment]
@cbodley I can't build branch with this PR and suspect this PR

Pls see https://jenkins.ceph.com/job/ceph-dev-new-build/ARCH=x86_64,AVAILABLE_ARCH=x86_64,AVAILABLE_DIST=centos8,DIST=centos8,MACHINE_SIZE=gigantic/70756//consoleFull


[ 63%] Building CXX object src/test/librados/CMakeFiles/ceph_test_rados_api_aio.dir/aio.cc.o
In file included from /home/jenkins-build/build/workspace/ceph-dev-new-build/ARCH/x86_64/AVAILABLE_ARCH/x86_64/AVAILABLE_DIST/centos8/DIST/centos8/MACHINE_SIZE/gigantic/release/17.2.6-729-ga19861cc/rpm/el8/BUILD/ceph-17.2.6-729-ga19861cc/src/googletest/googletest/include/gtest/gtest.h:387,
                 from /home/jenkins-build/build/workspace/ceph-dev-new-build/ARCH/x86_64/AVAILABLE_ARCH/x86_64/AVAILABLE_DIST/centos8/DIST/centos8/MACHINE_SIZE/gigantic/release/17.2.6-729-ga19861cc/rpm/el8/BUILD/ceph-17.2.6-729-ga19861cc/src/test/librados/aio.cc:17:
/home/jenkins-build/build/workspace/ceph-dev-new-build/ARCH/x86_64/AVAILABLE_ARCH/x86_64/AVAILABLE_DIST/centos8/DIST/centos8/MACHINE_SIZE/gigantic/release/17.2.6-729-ga19861cc/rpm/el8/BUILD/ceph-17.2.6-729-ga19861cc/src/test/librados/aio.cc: In member function ‘virtual void LibRadosAio_OperateMtime_Test::TestBody()’:
/home/jenkins-build/build/workspace/ceph-dev-new-build/ARCH/x86_64/AVAILABLE_ARCH/x86_64/AVAILABLE_DIST/centos8/DIST/centos8/MACHINE_SIZE/gigantic/release/17.2.6-729-ga19861cc/rpm/el8/BUILD/ceph-17.2.6-729-ga19861cc/src/test/librados/aio.cc:802:18: error: ‘rados_stat2’ was not declared in this scope; did you mean ‘rados_stat’?
  802 |     ASSERT_EQ(0, rados_stat2(test_data.m_ioctx, "foo", &size, &mtime));
      |                  ^~~~~~~~~~~
/home/jenkins-build/build/workspace/ceph-dev-new-build/ARCH/x86_64/AVAILABLE_ARCH/x86_64/AVAILABLE_DIST/centos8/DIST/centos8/MACHINE_SIZE/gigantic/release/17.2.6-729-ga19861cc/rpm/el8/BUILD/ceph-17.2.6-729-ga19861cc/src/test/librados/aio.cc: In member function ‘virtual void LibRadosAio_Operate2Mtime_Test::TestBody()’:
/home/jenkins-build/build/workspace/ceph-dev-new-build/ARCH/x86_64/AVAILABLE_ARCH/x86_64/AVAILABLE_DIST/centos8/DIST/centos8/MACHINE_SIZE/gigantic/release/17.2.6-729-ga19861cc/rpm/el8/BUILD/ceph-17.2.6-729-ga19861cc/src/test/librados/aio.cc:833:18: error: ‘rados_stat2’ was not declared in this scope; did you mean ‘rados_stat’?
  833 |     ASSERT_EQ(0, rados_stat2(test_data.m_ioctx, "foo", &size, &mtime));
      |                  ^~~~~~~~~~~
make[2]: *** [src/test/librados/CMakeFiles/ceph_test_rados_api_aio.dir/build.make:76: src/test/librados/CMakeFiles/ceph_test_rados_api_aio.dir/aio.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:14879: src/test/librados/CMakeFiles/ceph_test_rados_api_aio.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

**Comment by cbodley** [comment]
> @cbodley I can't build branch with this PR and suspect this PR

okay, looking

**Comment by cbodley** [comment]
> error: ‘rados_stat2’ was not declared in this scope; did you mean ‘rados_stat’?

ok, i see that `rados_stat2()` was added to the C API in https://github.com/ceph/ceph/pull/46823 after quincy, and wasn't backported

my original PR https://github.com/ceph/ceph/pull/51681 added `rados_aio_write_op_operate2()` to the C API, and its unit test relies on `rados_stat2()` to read back the high-resolution timestamp. that new function was not required to fix the bug in https://tracker.ceph.com/issues/61349, though, so i'll remove that commit from the backport along with its problematic test case. i'll do the same for the pacific backport

cc @rzarzynski @idryomov

**Comment by cbodley** [comment]
updated, conflicts are documented in the final commit

**Comment by ljflores** [comment]
Rados suite review: https://tracker.ceph.com/projects/rados/wiki/QUINCY#httpstrellocomciQLrAz6r1791-wip-yuri6-testing-2023-06-22-1005-quincy-old-wip-yuri6-testing-2023-06-22-0827-quincy

**Comment by yuriw** [comment]
jenkins test make check

**Review by idryomov — APPROVED** [review]

**Pull request merged**
