### PR TITLE
objectcacher: fix object read result overwritten

### PR DESCRIPTION
**Pull request by xiexingguo**

### CODE REVIEW

**Comment by xiexingguo** [comment]
@dillaman And this one. Thanks again:-)

**Comment by dillaman** [comment]
@xiexingguo Do you have an example of how this is an issue?

**Comment by xiexingguo** [comment]
@liewegas Maybe we can receive some useful advice from you once you are available.

**Comment by liewegas** [comment]
Are those 2 methods unused?

**Comment by xiexingguo** [comment]
@liewegas They seem like to be. But I will drop this change if you'd like they to stay this way.

**Comment by jdurgin** [comment]
In practice errors should never reach this level - we could get rid of the whole bh-error concept and log an error if it occurs in bh_write_commit()

**Pull request closed without merging**
