### PR TITLE
pacific: Warning Cleanup and Clang Compile Fix

### PR DESCRIPTION
**Pull request by singuliere**
backport tracker: https://tracker.ceph.com/issues/50240

---

backport of https://github.com/ceph/ceph/pull/40632
parent tracker: https://tracker.ceph.com/issues/50148

this backport was staged using ceph-backport.sh version 16.0.0.6848
find the latest version at https://github.com/ceph/ceph/blob/master/src/script/ceph-backport.sh

### CODE REVIEW

**Comment by singuliere** [comment]
```
[ 72%] Building CXX object src/librbd/CMakeFiles/rbd_internal.dir/mirror/ImageStateUpdateRequest.cc.o
/home/jenkins-build/build/workspace/ceph-pull-requests/src/librbd/managed_lock/BreakRequest.cc: In member function 'void librbd::managed_lock::BreakRequest<ImageCtxT>::send_blocklist()':
/home/jenkins-build/build/workspace/ceph-pull-requests/src/librbd/managed_lock/BreakRequest.cc:155:35: error: cannot convert 'std::string' {aka 'std::__cxx11::basic_string<char>'} to 'const char*'
  155 |   if (!locker_addr.parse(m_locker.address)) {
      |                          ~~~~~~~~~^~~~~~~
      |                                   |
      |                                   std::string {aka std::__cxx11::basic_string<char>}
In file included from /home/jenkins-build/build/workspace/ceph-pull-requests/src/librbd/managed_lock/BreakRequest.h:10,
                 from /home/jenkins-build/build/workspace/ceph-pull-requests/src/librbd/managed_lock/BreakRequest.cc:4:
/home/jenkins-build/build/workspace/ceph-pull-requests/src/msg/msg_types.h:441:26: note:   initializing argument 1 of 'bool entity_addr_t::parse(const char*, const char**, int)'
  441 |   bool parse(const char *s, const char **end = 0, int type=0);
      |              ~~~~~~~~~~~~^
make[3]: *** [src/librbd/CMakeFiles/rbd_internal.dir/build.make:1480: src/librbd/CMakeFiles/rbd_internal.dir/managed_lock/BreakRequest.cc.o] Error 1
make[3]: *** Waiting for unfinished jobs....
```

**Comment by singuliere** [comment]
jenkins test this please

**Comment by singuliere** [comment]
jenkins test this please

**Review by idryomov — APPROVED** [review]

**Review by tchaikov — APPROVED** [review]

**Comment by yuriw** [comment]
https://pulpito.ceph.com/yuriw-2021-07-01_22:17:44-rgw-wip-yuri-testing-2021-07-01-1059-pacific-distro-basic-smithi/
https://pulpito.ceph.com/yuriw-2021-07-02_14:46:34-rgw-wip-yuri-testing-2021-07-01-1059-pacific-distro-basic-smithi/

**Pull request merged**
