### PR TITLE
jewel: the option 'rbd_cache_writethrough_until_flush=true' dosn't work

### PR DESCRIPTION
**Pull request by trociny**
http://tracker.ceph.com/issues/17080
http://tracker.ceph.com/issues/16869
http://tracker.ceph.com/issues/17088
http://tracker.ceph.com/issues/16903

### CODE REVIEW

**Comment by trociny** [comment]
I ended up with the following chain of cherry-picks to resolve conflicts:

# 5498123 Merge pull request #10762 from dillaman/wip-16654
# Backport ticket: http://tracker.ceph.com/issues/17080
2d9840a librbd: cache was not switching to writeback after first flush

# 57b69b9 Merge pull request #10462 from dillaman/wip-16478
# Backport ticket: http://tracker.ceph.com/issues/16903
4a256f5 test: unit test cases for disabling librbd journal by policy
2e5076e librbd: utilize factory methods to create AioObjectRequest objects
840a473 librbd: convert AioObjectRequest/AioObjectRead classes to templates
65b336f librbd: move read callback helpers to narrowest scope
a945c2c librbd: convert AioImageRequest derived classes to templates
f1e3919 librbd: removed namespace indentation from legacy classes
405142c librbd: do not record journal events if append is disabled by policy
f453554 librbd: remove unused journal replay canceled callback
f7eeacd librbd: optionally support disabling journal appends via policy

# 2066ad8 Merge pull request #9539 from cxwshawn/wip-tc9-fix
# No tracker ticket, still look like no hurt to backport
2185a62 librbd: optimize header file dependency & modify related file.
88afa40 librbd: optimize operation header file dependency
59397e2 librbd: optimize journal header file dependency
aee1559 librbd: optimize image_watcher header file dependency
461958e librbd: optimize image header file dependency
01282eb librbd: optimize exclusive_lock  header file dependency
1a22769 librbd: optimize object-map header file dependency

# 1fe0566 Merge pull request #10060 from trociny/wip-16386
# Backport ticket: http://tracker.ceph.com/issues/16869
9717417 test: fix librbd tests for rbd_skip_partial_discard (Conflicts: src/rocksdb)
dc41731 librbd: discard hangs when 'rbd_skip_partial_discard' is enabled

# 89e5d1c Merge pull request #9535 from xinxinsh/wip-bug
# No tracker ticket, still looks good to backport, anyway
a540738 librbd: object_may_exist always return true when you write an empty object

## 1d4384c Merge pull request #10332 from dillaman/wip-16689
## Backport ticket: http://tracker.ceph.com/issues/16867 -- already merged!
#e5b4188 librbd: optimize away unnecessary object map updates
#b7a4db2 rbd-replay: decode and replay discard IO operations

# 77ec14a Merge pull request #10432 from dillaman/wip-16708
# Original ticket: http://tracker.ceph.com/issues/16708
# pending backport (no backport ticket yet)
6064f23 librbd: ensure that AIO ops are started prior to request
3df7213 librbd: helper method for creating and starting AioCompletions

**Comment by trociny** [comment]
I tested this locally -- no issues detected. Also, was running this on teuthology:
```
teuthology-suite --suite rbd --ceph wip-mgolub-testing --owner mgolub --email mgolub@mirantis.com --machine-type vps --suite-branch jewel --filter-out qemu
```
The results are here:
http://pulpito.ceph.com/trociny-2016-08-20_15:51:06-rbd-wip-mgolub-testing---basic-vps/
There were 7 dead jobs, which are looks like some environment issue, and 10 failed jobs.

Most of failed jobs are due to valgrind errors, which is a known issue, one rbd_mirror_stress.sh failure (currently it is known to may fail), one was TestJournalReplay.Rename failure:

http://qa-proxy.ceph.com/teuthology/trociny-2016-08-20_15:51:06-rbd-wip-mgolub-testing---basic-vps/376109/teuthology.log

This last one was believed to be fixed, but it looks like it is still observable:

http://tracker.ceph.com/issues/16019

Summarizing, the test results look ok to me.

**Comment by knandya** [comment]
@dachary : Is this PR going to be part of 10.2.3 release?

**Comment by dachary** [comment]
@knandya yes !

**Comment by knandya** [comment]
@dachary : Thanks!. Same with https://github.com/ceph/ceph/pull/10565 too?

**Comment by dachary** [comment]
@knandya you can find a complete list of the issues fixed in 10.2.3 at http://tracker.ceph.com/versions/518

**Pull request merged**
