### PR TITLE
[WIP]mgr/dashboard: monitoring: replace Grafana JSON with code-based generators

### PR DESCRIPTION
**Pull request by aaSharma14**
This PR intends to add grafanalib library to generate grafana JSON files through python files

Fixes: https://tracker.ceph.com/issues/45184
Signed-off-by: Aashish Sharma <aasharma@redhat.com>

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Review by epuertat — CHANGES_REQUESTED** [review]
Nice to see this one happening! Please let's demo this ASAP so everyone can see what's this about.

My comments:
* We should version both the source .py file and the generated .json. We can follow the same approach taken for the openapi.yaml (we generate it from the `controllers/*.py` data and if there's any difference between the generated and the versioned file, the CI fails).
* Having the json files would be great to compare the differences between those.
* I still see a lot boilerplate and mysterious stuff ("Prometheus admin.virt1.home.fajerski.name:9090"?). Are we using Annotations?
* Styles, colors (`"#3F6833"`) and repeated patterns should be moved a separate file. What have you used for formatting the python files? Looks good but a bit sparse. Perhaps a more compact styling would also help to reduce the sense that we still have to review a 1,000's lines file.

**Comment by p-se** [comment]
Basically I agree with @epuertat, but I'd like to explicitly mention how important I think it is to
- have the JSON files created and versioned alongside the Python files to create them, so that we'll be able to directly download them for various purposes, if not solely for comparison. Strictly technically speaking that would not be necessary, but if we didn't do it, even more changes in this PR would be required.
  
  - Not having the JSON files created would mean that they'd need to be built alongside Ceph, so that they could be packaged.
  - Container creation might needed to be adapted

  But if we'd keep them, it would immediately be possible to see what has changed in the JSON files when PRs are created. Even the possibility to easily spot how many files are affected by a change in the Python source (that affects several files) would be great.

- have CI extended to ensure the Grafana JSON dashboard files are always up-to-update with the source.

Other than that, I've looked at what the PR does and it is interesting to have Grafana dashboards created automatically as there doesn't seem to be a simple way to validate Grafana dashboards and I assume being able to generate them gives us a certain confidence that they are valid and will work. However,
- the library is not created by Grafana folks. But has been maintained for several years up to this day!
- it seems that some functionality is missing here and there, as it is requested to be added to the library in Github. Among them being
  - several new (beta) panels (when the issues have been created, they were still in beta state. That suggests they'll be added in a timely fashion)
  - all other issues about the addition of new panels which are not in beta anymore seem to have been added to the next milestone
  - fillGradient, a seemingly less important feature, but it was introduced in Grafana 6.x. However, since it has been reported missing, a PR has been created to fix that: https://github.com/weaveworks/grafanalib/issues/379
  
**My general impression is that newly added functionality in Grafana reaches the library in a timely fashion.** All the issues I found which were about existing functionality in Grafana, which haven't reached the library yet, have at least been added to the next milestone of the library or a PR has already been created.

The only question left about compatiblity seems to be if it covers the two plugins we use in our dashboards:
- vonage-status-panel (haven't found a reference to it)
- grafana-piechart-panel ([seems](https://github.com/weaveworks/grafanalib/blob/e58492dca61e50c2dd868c8d121d5e13b48a87b2/grafanalib/core.py#L91) to be covered)

If only the functionality for one of those two plugins would need to be added, it might still be worth it.

Then it, as I said, gives a certain level of confidence that the generate dashboards will work, but that does not necessarily means  we shouldn't think about having them validated in Grafana itself. But I guess the greater benefit of generating dashboards will be the possibility to unify settings and extract repeated patterns. I'm not sure how effective that'll be but my silent hope is that we'll be able to reduce the size of the dashboards significantly.

I'm looking forward to seeing progress on this PR!

**Comment by epuertat** [comment]
> Other than that, I've looked at what the PR does and it is interesting to have Grafana dashboards created automatically as there doesn't seem to be a simple way to validate Grafana dashboards and I assume being able to generate them gives us a certain confidence that they are valid and will work. However,
> 
> the library is not created by Grafana folks. But has been maintained for several years up to this day!

@p-se I also mentioned exploring the jsonnet approach: [Grafonnet](https://github.com/grafana/grafonnet-lib), which is officially backed by Grafana. @aaSharma14 have you investigated about it?

**Comment by aaSharma14** [comment]
> Basically I agree with @epuertat, but I'd like to explicitly mention how important I think it is to
> 
>     * have the JSON files created and versioned alongside the Python files to create them, so that we'll be able to directly download them for various purposes, if not solely for comparison. Strictly technically speaking that would not be necessary, but if we didn't do it, even more changes in this PR would be required.
>       
>       * Not having the JSON files created would mean that they'd need to be built alongside Ceph, so that they could be packaged.
>       * Container creation might needed to be adapted
>       
>       But if we'd keep them, it would immediately be possible to see what has changed in the JSON files when PRs are created. Even the possibility to easily spot how many files are affected by a change in the Python source (that affects several files) would be great.
> 
>     * have CI extended to ensure the Grafana JSON dashboard files are always up-to-update with the source.
> 
> 
> Other than that, I've looked at what the PR does and it is interesting to have Grafana dashboards created automatically as there doesn't seem to be a simple way to validate Grafana dashboards and I assume being able to generate them gives us a certain confidence that they are valid and will work. However,
> 
>     * the library is not created by Grafana folks. But has been maintained for several years up to this day!
> 
>     * it seems that some functionality is missing here and there, as it is requested to be added to the library in Github. Among them being
>       
>       * several new (beta) panels (when the issues have been created, they were still in beta state. That suggests they'll be added in a timely fashion)
>       * all other issues about the addition of new panels which are not in beta anymore seem to have been added to the next milestone
>       * fillGradient, a seemingly less important feature, but it was introduced in Grafana 6.x. However, since it has been reported missing, a PR has been created to fix that: [Add support for fillGradient weaveworks/grafanalib#379](https://github.com/weaveworks/grafanalib/issues/379)
> 
> 
> **My general impression is that newly added functionality in Grafana reaches the library in a timely fashion.** All the issues I found which were about existing functionality in Grafana, which haven't reached the library yet, have at least been added to the next milestone of the library or a PR has already been created.
> 
> The only question left about compatiblity seems to be if it covers the two plugins we use in our dashboards:
> 
>     * vonage-status-panel (haven't found a reference to it)
> 
>     * grafana-piechart-panel ([seems](https://github.com/weaveworks/grafanalib/blob/e58492dca61e50c2dd868c8d121d5e13b48a87b2/grafanalib/core.py#L91) to be covered)
> 
> 
> If only the functionality for one of those two plugins would need to be added, it might still be worth it.
> 
> Then it, as I said, gives a certain level of confidence that the generate dashboards will work, but that does not necessarily means we shouldn't think about having them validated in Grafana itself. But I guess the greater benefit of generating dashboards will be the possibility to unify settings and extract repeated patterns. I'm not sure how effective that'll be but my silent hope is that we'll be able to reduce the size of the dashboards significantly.
> 
> I'm looking forward to seeing progress on this PR!

Thank you @p-se for the detailed review. I agree with your thoughts. As @epuertat mentioned, the alternative could be [Grafonnet](https://grafana.github.io/grafonnet-lib/). It is maintained by grafana and as far as i know covers your concerns as well. I have started exploring it and will come up with a PR soon.

**Comment by aaSharma14** [comment]
> > Other than that, I've looked at what the PR does and it is interesting to have Grafana dashboards created automatically as there doesn't seem to be a simple way to validate Grafana dashboards and I assume being able to generate them gives us a certain confidence that they are valid and will work. However,
> > the library is not created by Grafana folks. But has been maintained for several years up to this day!
> 
> @p-se I also mentioned exploring the jsonnet approach: [Grafonnet](https://github.com/grafana/grafonnet-lib), which is officially backed by Grafana. @aaSharma14 have you investigated about it?

Yes, I have started exploring Grafonnet as well. It seems to be much similar to grafanalib but It is maintained by Grafana people and covers almost all the functionality. I will come up with a PR soon using Grafonnet.

**Comment by epuertat** [comment]
Closing in favor of https://github.com/ceph/ceph/pull/42194

**Pull request closed without merging**
