### PR TITLE
mgr/dashboard: added recovery throghput graph, improve promqls, and fixes

### PR DESCRIPTION
**Pull request by Pegonzal**
This PR covers the following:

> Adds Recovery Throughput graph
> Remade the promQLs to dynamically change the $interval
> Adjusted inventory's card horizontal bars to be responsive
> Switched IPS/OPS to keep consistency between graphs colors for Read and Write

Signed-off-by: Pedro Gonzalez Gomez <pegonzal@redhat.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [x] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Review by nizamial09 — APPROVED** [review]
LGTM!

Just a question, how often does the chart refreshes? every 5 seconds?

**Comment by nizamial09** [comment]
and I noticed that this PR wasn't on top of the latest changes in feature branch?

**Comment by Pegonzal** [comment]
> LGTM!
> 
> Just a question, how often does the chart refreshes? every 5 seconds?

Thanks @nizamial09 !

The prometheus data get fetched every 30s and the charts updates when new data is fetched, so each 30s the charts are updated

**Comment by Pegonzal** [comment]
> and I noticed that this PR wasn't on top of the latest changes in feature branch?

I'm pretty sure it is on top of the latest changes, could you check it again just in case?

**Comment by Pegonzal** [comment]
> Can you attach some screenshots demonstrating the difference of approaches?

Do you mean in the difference between the new queries and the old ones?
If that's the case the biggest difference is that by adjusting the $interval dynamically we get more data points which was an issue before becuase you could miss some data when there actually was. So that gets fixed.
And with this change as well for the shorter time frames (5,15min...) the charts will look less spiky

**Comment by pereman2** [comment]
> > Can you attach some screenshots demonstrating the difference of approaches?
> 
> Do you mean in the difference between the new queries and the old ones? If that's the case the biggest difference is that by adjusting the $interval dynamically we get more data points which was an issue before becuase you could miss some data when there actually was. So that gets fixed. And with this change as well for the shorter time frames (5,15min...) the charts will look less spiky

Yeah exactly that difference

**Pull request merged**
