### PR TITLE
mgr: Diskprediction cloud activate when config changes

### PR DESCRIPTION
**Pull request by hsiang41**
Trigger diskprediction cloud action when receive notify configuration changed.

Signed-off-by: Rick Chen <rick.chen@prophetstor.com>

- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by hsiang41** [comment]
@liewegas Dear Sir: I need your review and approve.

**Comment by tchaikov** [comment]
retest this please.

**Comment by hsiang41** [comment]
retest this please.

**Comment by hsiang41** [comment]
retest this please.

**Comment by hsiang41** [comment]
retest this please.

**Comment by tchaikov** [comment]
- http://pulpito.ceph.com/kchai-2018-11-22_06:59:02-rados-wip-kefu2-testing-2018-11-22-1132-distro-basic-mira/
- http://pulpito.ceph.com/kchai-2018-11-25_10:39:02-rados-wip-kefu2-testing-2018-11-22-1635-distro-basic-smithi/
- http://pulpito.ceph.com/kchai-2018-11-26_08:14:00-rados-wip-kefu2-testing-2018-11-25-2246-distro-basic-smithi/

**Comment by hsiang41** [comment]
@tchaikov Thanks.

**Pull request merged**
