### PR TITLE
rgw: swift: bugfix: https://tracker.ceph.com/issues/37765

### PR DESCRIPTION
**Pull request by greenx**
The meaning is as follows:
iterate_slo_parts() set end offset equal to the size of the segment,
but  RGWRados::iterate_obj args wait offset not size.

Signed-off-by: Andrey Groshev an.groshev@tensor.ru

### CODE REVIEW

**Comment by greenx** [comment]
@batrick 
Maybe someone call to speed up the process? Or useless?

**Comment by mattbenjamin** [comment]
@greenx will review, thanks for your patience

**Comment by greenx** [comment]
@mattbenjamin Is there no 5 minutes to look at 13 lines of code?  If you don't understand swift api, ask me, I will explain.

**Comment by cbodley** [comment]
jenkins test make check

**Comment by greenx** [comment]
@cbodley , There is some kind of mistake in the jenkins
https://jenkins.ceph.com/job/ceph-pull-requests/1111/consoleText

**Comment by cbodley** [comment]
jenkins test make check

**Comment by cbodley** [comment]
passed qa in http://pulpito.ceph.com/cbodley-2019-05-30_18:03:29-rgw-wip-cbodley-testing-distro-basic-smithi/

**Comment by mattbenjamin** [comment]
unstale

**Pull request merged**
