### PR TITLE
mgr/dashboard: Making the edges of not rounded button rounded

### PR DESCRIPTION
**Pull request by nizamial09**
**BEFORE**
not-round-button

**AFTER**
rounded

Fixes: https://tracker.ceph.com/issues/48563
Signed-off-by: Nizamudeen A <nia@redhat.com>

## Checklist
- [x] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Review by epuertat — APPROVED** [review]
👍🏼

**Comment by epuertat** [comment]
This fixes the "Cluster -> Config action button" too?

**Comment by avanthakkar** [comment]
jenkins test api

**Review by avanthakkar — APPROVED** [review]
LGTM!

**Comment by nizamial09** [comment]
> This fixes the "Cluster -> Config action button" too?

Yup @epuertat

**Comment by nizamial09** [comment]
jenkins test api

**Review by s0nea — APPROVED** [review]

**Review by aaSharma14 — APPROVED** [review]

**Review by callithea — APPROVED** [review]

**Pull request merged**
