### PR TITLE
osd: fix unordered read bug (for chunked object)

### PR DESCRIPTION
**Pull request by myoungwon**
The current implementation for chunked object only supports
proxy_read(if offset is within range) and write(local write)
In this case, a read request can be handled before a write request.
This commit prevents unordered read processing because
proxy_read() will be executed if the chunk is missing state.
If chunked object has been overwritten, its state will not be missing.

Fixes: http://tracker.ceph.com/issues/22369
Signed-off-by: Myoungwon Oh <omwmw@sk.com>

### CODE REVIEW

**Comment by myoungwon** [comment]
retest this please

**Comment by tchaikov** [comment]
- http://pulpito.ceph.com/kchai-2017-12-14_08:53:42-rados-wip-kefu-testing-2017-12-14-1157-distro-basic-mira/
- http://pulpito.ceph.com/kchai-2017-12-15_06:17:13-rados-wip-kefu-testing-2017-12-14-1157-distro-basic-mira/

**Comment by tchaikov** [comment]
@myoungwon i'd suggest contributor comment on the PR to explain what change he/she made if the PR is updated *after* it's reviewed/approved. otherwise we can hardly tell if the test is valid or not.

**Comment by myoungwon** [comment]
@tchaikov Sorry, The main purpose of updated commit is to make a chunk MISSING state when ChunkReadOp test is executed. Since stat and write op make a chunk CLEAN state (through promote_object), this causes local read (not chunk_proxy_read).

If flush() is implemented (https://github.com/ceph/ceph/pull/19294), combination test (promote , flush, write and read ...) will be added. 
Current implementation mainly implements chunk_proxy_read() and promote_object() for chunks.

Do you need more explanation?

**Comment by tchaikov** [comment]
@myoungwon i have not reviewed this change, so it's up to the reviewer. i just wanted to understand if it's safe to merge. because @liewegas has approved your change. but it's risky to merge as it is without confirming with you.

**Pull request merged**
