### PR TITLE
rgw/admin: 'data sync status' formats binary error repo entries

### PR DESCRIPTION
**Pull request by cbodley**
the error repo keys were converted to a binary format for resharding support, so they could encode the optional generation number. the `data sync status` command now uses `rgw::error_repo::decode_key()` to parse these and format them correctly

Fixes: https://tracker.ceph.com/issues/59174

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by cbodley** [comment]
without the fix:
```
    "recovering_buckets": [
        "<80>\u0001\u0001Z\u0000\u0000\u0000\n\nG\u0000\u0000\u0000\u0006\u0000\u0000\u0000testbucket\u0000\u0000\u0000\u00000\u0000\u0000\u0000f48cfc12-b34a-4ba8-a849-10785cc33c8a.4190.1\u0000\u0000\u0000\u0000\u0000<FF><FF><FF><FF>\u0002\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" 
    ]
```
and with:
```
    "recovering_buckets": [                                                                                                                                   
        "testbucket:f48cfc12-b34a-4ba8-a849-10785cc33c8a.4190.1:2[0]"                                                                                         
    ],
```

**Comment by mattbenjamin** [comment]
this is showing up in output from downstream users on rhcs-5.3, obviously;  I would like to create bzs for downstream backports, would that be problematic?

**Review by mattbenjamin — APPROVED** [review]
lgtm

**Comment by cbodley** [comment]
passed qa after reruns; see https://github.com/ceph/ceph/pull/50648#issuecomment-1492355714 for details

**Pull request merged**
