### PR TITLE
luminous: crush/CrushWrapper: ensure crush_choose_arg_map.size == max_buckets

### PR DESCRIPTION
**Pull request by pdvian**
http://tracker.ceph.com/issues/38719

### CODE REVIEW

**Comment by yuriw** [comment]
[wip-yuri3-testing-2019-03-28-1550-luminous](https://trello.com/c/Pmz5A7di/569-wip-yuri3-testing-2019-03-28-1550-luminous)

**Comment by neha-ojha** [comment]
```
2019-03-29T02:11:45.255 INFO:tasks.workunit.client.0.smithi203.stderr:+ ceph osd crush add-bucket r1 rack root=default
2019-03-29T02:11:45.367 INFO:tasks.workunit.client.0.smithi203.stderr:2019-03-29 02:11:45.375466 7f7fa6321700 -1 WARNING: all dangerous and experimental features are enabled.
2019-03-29T02:11:45.393 INFO:tasks.workunit.client.0.smithi203.stderr:2019-03-29 02:11:45.401422 7f7fa6321700 -1 WARNING: all dangerous and experimental features are enabled.
2019-03-29T02:11:45.519 INFO:tasks.workunit.client.0.smithi203.stderr:Invalid command: unused arguments: [u'root=default']
2019-03-29T02:11:45.519 INFO:tasks.workunit.client.0.smithi203.stderr:osd crush add-bucket <name> <type> :  add no-parent (probably root) crush bucket <name> of type <type>
2019-03-29T02:11:45.519 INFO:tasks.workunit.client.0.smithi203.stderr:Error EINVAL: invalid command
2019-03-29T02:11:45.531 DEBUG:teuthology.orchestra.run:got remote process result: 22
2019-03-29T02:11:45.532 INFO:tasks.workunit:Stopping ['mon/pool_ops.sh', 'mon/crush_ops.sh', 'mon/osd.sh', 'mon/caps.sh'] on client.0...
2019-03-29T02:11:45.532 INFO:teuthology.orchestra.run.smithi203:Running:
2019-03-29T02:11:45.532 INFO:teuthology.orchestra.run.smithi203:> sudo rm -rf -- /home/ubuntu/cephtest/workunits.list.client.0 /home/ubuntu/cephtest/clone.client.0
2019-03-29T02:11:45.677 ERROR:teuthology.run_tasks:Saw exception from tasks.
```
mon/crush_ops.sh is failing with this error in http://pulpito.ceph.com/yuriw-2019-03-28_20:45:53-rados-wip-yuri3-testing-2019-03-28-1550-luminous-distro-basic-smithi/3781809/

**Comment by yuriw** [comment]
@pdvian @neha-ojha pls add `needs-qa`  `luminous-batch-1` when done

**Comment by liewegas** [comment]
updated the workunit, ready to retest

**Comment by yuriw** [comment]
[wip-yuri2-testing-2019-06-07-2039-luminous](https://trello.com/c/jPJYEz25/634-wip-yuri2-testing-2019-06-07-2039-luminous)

**Pull request merged**
