### PR TITLE
qa: switch to curl for qemu-xfstests

### PR DESCRIPTION
**Pull request by idryomov**
A follow-up for https://github.com/ceph/ceph/pull/49534.  This got missed because a custom branch needed to be passed during testing for other purposes.

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [x] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Review by chrisphoffman — APPROVED** [review]

**Review by anthonyeleven — APPROVED** [review]

**Comment by ktdreyer** [comment]
Dunno if it matters but `wget` will follow HTTP redirects, whereas with curl you'll need the `-L` flag.

**Comment by idryomov** [comment]
jenkins test api

**Comment by idryomov** [comment]
> Dunno if it matters but `wget` will follow HTTP redirects, whereas with curl you'll need the `-L` flag.

In this case it seems to not matter -- it's working as is:
```
+ cd /tmp/cephtest
+ curl -O 'https://git.ceph.com/?p=ceph.git;a=blob_plain;f=qa/run_xfstests-obsolete.sh'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 12288    0 12288    0     0  65898      0 --:--:-- --:--:-- --:--:-- 67889
+ [[ -s run_xfstests-obsolete.sh ]]
+ chmod +x run_xfstests-obsolete.sh
```

**Comment by idryomov** [comment]
jenkins test api

**Comment by idryomov** [comment]
https://pulpito.ceph.com/dis-2022-12-22_15:37:58-rbd-wip-dis-testing-distro-default-smithi/

**Pull request merged**
