### PR TITLE
rgw: check going_down() when lifecycle processing

### PR DESCRIPTION
**Pull request by yaozongyou**
Signed-off-by: Yao Zongyou <yaozongyou@vip.qq.com>

### CODE REVIEW

**Comment by cbodley** [comment]
jenkins test this please

**Comment by yuriw** [comment]
[wip-yuri2-testing-2017-11-09-2112](https://trello.com/c/3eoOIo2T/199-wip-yuri2-testing-2017-11-09-2112)

**Comment by smithfarm** [comment]
@cbodley You marked http://tracker.ceph.com/issues/22099 for backport to both luminous and jewel. Luminous should be fine, but I don't see the lifecycle code in jewel . . . am I missing something?

**Comment by dang** [comment]
Correct, lifecycle isn't in jewel

**Comment by cbodley** [comment]
@smithfarm oops, i wasn't paying attention there - sorry! i removed jewel from the backport tags

**Pull request merged**
