### PR TITLE
quincy: rgw: first batch of quincy backports

### PR DESCRIPTION
**Pull request by cbodley**
includes the following prs:

https://github.com/ceph/ceph/pull/44078  meta sync retries
https://github.com/ceph/ceph/pull/44413  remove bucket admin api
https://github.com/ceph/ceph/pull/44581  dbstore logging
https://github.com/ceph/ceph/pull/40011  datalog notify interval
https://github.com/ceph/ceph/pull/44617  swift bulk upload
https://github.com/ceph/ceph/pull/33934  delete full sync index

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Review by dang — APPROVED** [review]

**Comment by cbodley** [comment]
jenkins test api

**Comment by cbodley** [comment]
jenkins test api

**Comment by yuriw** [comment]
jenkins test api

**Comment by yuriw** [comment]
jenkins test api

**Comment by cbodley** [comment]
the 'ceph API tests' don't seem to be triggering at all on quincy PRs

**Comment by epuertat** [comment]
jenkins test api

**Comment by yuriw** [comment]
jenkins test api

**Comment by yuriw** [comment]
jenkins test api

**Pull request merged**
