### PR TITLE
doc/mgr: Fix msgr2 TCP port in a couple of examples

### PR DESCRIPTION
**Pull request by anthonyeleven**
doc/mgr: Fix msgr2 TCP port in a couple of examples.

Signed-off-by: Anthony D'Atri <anthony.datri@gmail.com>
Fixes: https://tracker.ceph.com/issues/47976

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by anthonyeleven** [comment]
@zdover23 this is ready to go.  Please feel free to assign https://tracker.ceph.com/issues/47976 to me and mark it completed upon your acceptance and merging of this PR.

**Comment by anthonyeleven** [comment]
jenkins test api

**Comment by anthonyeleven** [comment]
jenkins test api

**Comment by anthonyeleven** [comment]
jenkins test api

**Review by zdover23 — APPROVED** [review]
LGTM. Proceeding with merge.

**Pull request merged**
