### PR TITLE
doc: Modified a note section in rbd-snapshot doc.

### PR DESCRIPTION
**Pull request by nilamdyuti**
Elaborates the note section a bit more as to why stopping I/O before
taking a snapshot is recommended and how to do it.

### CODE REVIEW

**Comment by nilamdyuti** [comment]
@jdurgin Made the suggested changes. Let me know if they look good to you.

**Comment by dachary** [comment]
@nilamdyuti could you please make it so there is only one commit in this pull request ?

**Comment by jdurgin** [comment]
@nilamdyuti wording looks good to me, thanks!

**Comment by nilamdyuti** [comment]
@dachary I mistakenly deleted the branch. I recreated the branch but the changes weren't restored. So, I have made the same changes in a separate branch and created a new pull request. See: https://github.com/ceph/ceph/pull/6908

Can you please merge that pull request?

**Pull request closed without merging**
