### PR TITLE
quincy: cephfs-top: display average read/write/metadata latency

### PR DESCRIPTION
**Pull request by neesingh-rh**
backport tracker: https://tracker.ceph.com/issues/57440

---

backport of https://github.com/ceph/ceph/pull/41397
parent tracker: https://tracker.ceph.com/issues/48619

this backport was staged using ceph-backport.sh version 16.0.0.6848
find the latest version at https://github.com/ceph/ceph/blob/master/src/script/ceph-backport.sh

### CODE REVIEW

**Review by anthonyeleven — APPROVED** [review]
Docs Lgtm

**Review by vshankar — APPROVED** [review]

**Comment by vshankar** [comment]
jenkins test make check

**Comment by ljflores** [comment]
Rados suite review: https://pulpito.ceph.com/?branch=wip-yuri6-testing-2022-09-06-1353-quincy

Failures, unrelated:
    1. https://tracker.ceph.com/issues/57165 -- pending Quincy backport
    2. https://tracker.ceph.com/issues/57290 -- pending Quincy backport
    3. https://tracker.ceph.com/issues/57269
    4. https://tracker.ceph.com/issues/49287
    5. https://tracker.ceph.com/issues/56951

Details:
    1. expected valgrind issues and found none - Ceph - RADOS
    2. orch/cephadm: task/test_cephadm failure due to: ERROR: A cluster with the same fsid '00000000-0000-0000-0000-0000deadbeef' already exists. - Ceph - Orchestrator
    3. rook: unable to read URL "https://docs.projectcalico.org/manifests/tigera-operator.yaml" - Ceph - Orchestrator
    4. podman: setting cgroup config for procHooks process caused: Unit libpod-$hash.scope not found - Ceph - Orchestrator
    5. rook/smoke: Updating cephclusters/rook-ceph is forbidden - Ceph - Orchestrator

**Comment by ljflores** [comment]
jenkins test make check

**Comment by vshankar** [comment]
jenkins test make check

**Review by vshankar — APPROVED** [review]

**Pull request merged**
