### PR TITLE
qa/tasks/ceph: update_archive_setting() only if ctx.archive is valid

### PR DESCRIPTION
**Pull request by tchaikov**
## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by tchaikov** [comment]
jenkins test make check

**Comment by tchaikov** [comment]
jenkins test make check

**Comment by ideepika** [comment]
@tchaikov I saw similar failure with respect to jobs using  qa/tasks/cephadm.py; I created changes based on your PR: https://github.com/ceph/ceph/pull/38009

**Comment by tchaikov** [comment]
jenkins test api

**Comment by tchaikov** [comment]
- https://pulpito.ceph.com/kchai-2020-11-14_09:04:49-rados-wip-kefu-testing-2020-11-14-1525-distro-basic-smithi/
- https://pulpito.ceph.com/kchai-2020-11-15_03:36:16-rados-wip-kefu-testing-2020-11-14-1526-distro-basic-smithi/
- https://pulpito.ceph.com/kchai-2020-11-15_12:08:30-rados-wip-kefu-testing-2020-11-14-1526-distro-basic-smithi/
- https://pulpito.ceph.com/kchai-2020-11-15_16:16:56-rados-wip-kefu-testing-2020-11-14-1526-distro-basic-smithi/

failures tracked by

- https://tracker.ceph.com/issues/48220
- https://tracker.ceph.com/issues/48030

**Review by jdurgin — APPROVED** [review]

**Review by neha-ojha — APPROVED** [review]

**Pull request merged**
