### PR TITLE
doc/rados: erasure-code-lrc corrections

### PR DESCRIPTION
**Pull request by anthonyeleven**
doc/rados: erasure-code-lrc corrections

- Clarified / corrected jerasure recovery characterization cf. https://library.eecs.utk.edu/storage/125phpw0xFqAut-cs-07-603.pdf
- Capitalization
- Word choice:  OSDs are discrete / cardinal, so "fewer" instead of  "less"
- Reworked a few phrases to be less stilted

Signed-off-by: Anthony D'Atri <anthony.datri@gmail.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by anthonyeleven** [comment]
jenkins test make check
jenkins test api

**Comment by anthonyeleven** [comment]
jenkins test make check

**Comment by anthonyeleven** [comment]
jenkins test api

**Review by zdover23 — APPROVED** [review]
LGTM

**Comment by anthonyeleven** [comment]
@zdover23 can you merge or does someone else handle that?

**Pull request merged**
