### PR TITLE
mimic: rbd-mirror: optionally support active/active replication

### PR DESCRIPTION
**Pull request by dillaman**

### CODE REVIEW

**Comment by dillaman** [comment]
http://pulpito.ceph.com/jdillaman-2018-05-20_08:17:31-rbd-wip-jd-testing-distro-basic-smithi/

**Comment by trociny** [comment]
@dillaman, the teuthology result contains one rbd_mirror_fsx_compare.sh failure. It failed waiting snapshot creation propagated to slave, because the replay was in error state in that time due to this error:
```
2018-05-20 12:44:45.338 7fd88d7fa700 -1 librbd::SnapshotUnprotectRequest: cannot unprotect: at least 1 child(ren) [108323436314] in pool 'mirror'
2018-05-20 12:44:45.338 7fd88d7fa700 -1 librbd::SnapshotUnprotectRequest: encountered error: (16) Device or resource busy
2018-05-20 12:44:45.338 7fd88d7fa700 -1 librbd::SnapshotUnprotectRequest: 0x7fd7ec1a10b0 should_complete_error: ret_val=-16
2018-05-20 12:44:45.338 7fd88d7fa700 -1 librbd::SnapshotUnprotectRequest: 0x7fd7ec1a10b0 should_complete_error: ret_val=-16
2018-05-20 12:44:45.338 7fd88d7fa700 -1 librbd::deep_copy::SnapshotCopyRequest: 0x7fd7ec13fc20 handle_snap_unprotect: failed to unprotect snapshot 'snap': (16) Device or resource busy
2018-05-20 12:44:45.338 7fd88d7fa700 -1 librbd::DeepCopyRequest: 0x7fd7ec575020 handle_copy_snapshots: failed to copy snapshot metadata: (16) Device or resource busy
2018-05-20 12:44:45.338 7fd88d7fa700 10 rbd::mirror::ImageSync: 0x7fd7b410fb20 handle_copy_image: r=-16
2018-05-20 12:44:45.338 7fd88d7fa700 -1 rbd::mirror::ImageSync: 0x7fd7b410fb20 handle_copy_image: failed to copy image: (16) Device or resource busy
```

Do you think we still may proceed and merge this to mimic?

**Comment by luoguanzzz** [comment]
`rbd snap unprotect rbd1/lgrbd2@lgrbd2.snap
2019-11-14 10:31:46.409 7f07f8ff9700 -1 librbd::SnapshotUnprotectRequest: cannot unprotect: at least 1 child(ren) [25a4e6b8b4567] in pool 'rbd1'
2019-11-14 10:31:46.412 7f07f8ff9700 -1 librbd::SnapshotUnprotectRequest: encountered error: (16) Device or resource busy
2019-11-14 10:31:46.412 7f07f8ff9700 -1 librbd::SnapshotUnprotectRequest: 0x563503d4c380 should_complete_error: ret_val=-16
2019-11-14 10:31:46.419 7f07f8ff9700 -1 librbd::SnapshotUnprotectRequest: 0x563503d4c380 should_complete_error: ret_val=-16
rbd: unprotecting snap failed: (16) Device or resource busy
` 
What caused this error

**Comment by luoguanzzz** [comment]
`[root@ceph-mon-node1 lgrbd0]# rbd snap unprotect rbd1/lgrbd2@lgrbd2.snap
2019-11-14 10:31:46.409 7f07f8ff9700 -1 librbd::SnapshotUnprotectRequest: cannot unprotect: at least 1 child(ren) [25a4e6b8b4567] in pool 'rbd1'
2019-11-14 10:31:46.412 7f07f8ff9700 -1 librbd::SnapshotUnprotectRequest: encountered error: (16) Device or resource busy
2019-11-14 10:31:46.412 7f07f8ff9700 -1 librbd::SnapshotUnprotectRequest: 0x563503d4c380 should_complete_error: ret_val=-16
2019-11-14 10:31:46.419 7f07f8ff9700 -1 librbd::SnapshotUnprotectRequest: 0x563503d4c380 should_complete_error: ret_val=-16
rbd: unprotecting snap failed: (16) Device or resource busy
`

What caused this error

**Comment by luoguanzzz** [comment]
What caused this error?

> [root@ceph-mon-node1 lgrbd0]# rbd snap unprotect rbd1/lgrbd2@lgrbd2.snap
2019-11-14 10:31:46.409 7f07f8ff9700 -1 librbd::SnapshotUnprotectRequest: cannot unprotect: at least 1 child(ren) [25a4e6b8b4567] in pool 'rbd1'
2019-11-14 10:31:46.412 7f07f8ff9700 -1 librbd::SnapshotUnprotectRequest: encountered error: (16) Device or resource busy
2019-11-14 10:31:46.412 7f07f8ff9700 -1 librbd::SnapshotUnprotectRequest: 0x563503d4c380 should_complete_error: ret_val=-16
2019-11-14 10:31:46.419 7f07f8ff9700 -1 librbd::SnapshotUnprotectRequest: 0x563503d4c380 should_complete_error: ret_val=-16
rbd: unprotecting snap failed: (16) Device or resource busy

**Pull request merged**
