### PR TITLE
mgr/dashboard: fix UI modal issues

### PR DESCRIPTION
**Pull request by nizamial09**
- Fix bs-modal getting hidden behind navbar
- Reuse the project name for tab title
- Readonly user shows an empty space in the administration dropdown
- Physical Disks Identify modal not opening up
   - add e2e in cephadm to make sure the modal always comes up
- Primary action doesn't need to be displayed for the read-only user

Fixes: https://tracker.ceph.com/issues/67547

**BEFORE**
Screenshot from 2024-09-09 16-43-18
Screenshot from 2024-09-09 16-43-42

**AFTER**

Screenshot from 2024-09-09 16-50-15
Screenshot from 2024-09-09 16-49-37

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Comment by nizamial09** [comment]
one more major difference is that the tab title shows `Ceph Dashboard` instead of `Ceph` from now on: 
image

**Review by afreen23 — APPROVED** [review]

**Review by cloudbehl — APPROVED** [review]
LGTM

**Comment by afreen23** [comment]
jenkins test api

**Comment by afreen23** [comment]
jenkins retest this please

**Comment by afreen23** [comment]
breadcrumb unit tests failing:

```
 ● BreadcrumbsComponent › should display no breadcrumbs in page title when navigating to dashboard

    expect(received).toEqual(expected) // deep equality

    Expected: "Ceph"
    Received: "Ceph Dashboard"

      143 |     });
      144 |     tick();
    > 145 |     expect(titleService.getTitle()).toEqual('Ceph');
          |                                     ^
      146 |   }));
      147 |
      148 |   it('should display no breadcrumbs in page title when a page is not found', fakeAsync(() => {

      at src/app/core/navigation/breadcrumbs/breadcrumbs.component.spec.ts:145:37
      at fakeAsyncFn (node_modules/zone.js/bundles/zone-testing-bundle.umd.js:5637:34)
      at _ZoneDelegate.Object.<anonymous>._ZoneDelegate.invoke (node_modules/zone.js/bundles/zone-testing-bundle.umd.js:409:30)
      at ProxyZoneSpec.Object.<anonymous>.ProxyZoneSpec.onInvoke (node_modules/zone.js/bundles/zone-testing-bundle.umd.js:3830:43)
      at _ZoneDelegate.Object.<anonymous>._ZoneDelegate.invoke (node_modules/zone.js/bundles/zone-testing-bundle.umd.js:408:56)
      at Zone.Object.<anonymous>.Zone.run (node_modules/zone.js/bundles/zone-testing-bundle.umd.js:169:47)
      at Object.wrappedFunc (node_modules/zone.js/bundles/zone-testing-bundle.umd.js:4330:34)

  ● BreadcrumbsComponent › should display no breadcrumbs in page title when a page is not found

    expect(received).toEqual(expected) // deep equality

    Expected: "Ceph"
    Received: "Ceph Dashboard"

      151 |     });
      152 |     tick();
    > 153 |     expect(titleService.getTitle()).toEqual('Ceph');
          |                                     ^
      154 |   }));
      155 |
      156 |   it('should display 2 breadcrumbs in page title when navigating to hosts', fakeAsync(() => {

      at src/app/core/navigation/breadcrumbs/breadcrumbs.component.spec.ts:153:37
 ```

**Comment by afreen23** [comment]
dashboard test failures:
```
[Test Result](https://jenkins.ceph.com/job/ceph-dashboard-pull-requests/16212/testReport/) (12 failures / +3)
[should move the image to the trash.Images page move to trash, restore and purge image tests should move the image to the trash](https://jenkins.ceph.com/job/ceph-dashboard-pull-requests/16212/testReport/junit/(root)/should%20move%20the%20image%20to%20the%20trash/Images_page_move_to_trash__restore_and_purge_image_tests_should_move_the_image_to_the_trash/)
[should restore image to images table.Images page move to trash, restore and purge image tests should restore image to images table](https://jenkins.ceph.com/job/ceph-dashboard-pull-requests/16212/testReport/junit/(root)/should%20restore%20image%20to%20images%20table/Images_page_move_to_trash__restore_and_purge_image_tests_should_restore_image_to_images_table/)
[should purge trash in images trash tab.Images page move to trash, restore and purge image tests should purge trash in images trash tab](https://jenkins.ceph.com/job/ceph-dashboard-pull-requests/16212/testReport/junit/(root)/should%20purge%20trash%20in%20images%20trash%20tab/Images_page_move_to_trash__restore_and_purge_image_tests_should_purge_trash_in_images_trash_tab/)
["after all" hook for "should purge trash in images trash tab".Images page move to trash, restore and purge image tests "after all" hook for "should purge trash in images trash tab"](https://jenkins.ceph.com/job/ceph-dashboard-pull-requests/16212/testReport/junit/(root)/%22after%20all%22%20hook%20for%20%22should%20purge%20trash%20in%20images%20trash%20tab%22/Images_page_move_to_trash__restore_and_purge_image_tests__after_all__hook_for__should_purge_trash_in_images_trash_tab_/)
[Create a CephFS Subvolume Snapshot Clone.CephFS Snapshot Management Create a CephFS Subvolume Snapshot Clone](https://jenkins.ceph.com/job/ceph-dashboard-pull-requests/16212/testReport/junit/(root)/Create%20a%20CephFS%20Subvolume%20Snapshot%20Clone/CephFS_Snapshot_Management_Create_a_CephFS_Subvolume_Snapshot_Clone/)
[should switch to the second cluster and back to hub.Muti-cluster management page should switch to the second cluster and back to hub](https://jenkins.ceph.com/job/ceph-dashboard-pull-requests/16212/testReport/junit/(root)/should%20switch%20to%20the%20second%20cluster%20and%20back%20to%20hub/Muti_cluster_management_page_should_switch_to_the_second_cluster_and_back_to_hub/)
[should reconnect the second cluster.Muti-cluster management page should reconnect the second cluster](https://jenkins.ceph.com/job/ceph-dashboard-pull-requests/16212/testReport/junit/(root)/should%20reconnect%20the%20second%20cluster/Muti_cluster_management_page_should_reconnect_the_second_cluster/)
[should edit the second cluster.Muti-cluster management page should edit the second cluster](https://jenkins.ceph.com/job/ceph-dashboard-pull-requests/16212/testReport/junit/(root)/should%20edit%20the%20second%20cluster/Muti_cluster_management_page_should_edit_the_second_cluster/)
[should disconnect the second cluster.Muti-cluster management page should disconnect the second cluster](https://jenkins.ceph.com/job/ceph-dashboard-pull-requests/16212/testReport/junit/(root)/should%20disconnect%20the%20second%20cluster/Muti_cluster_management_page_should_disconnect_the_second_cluster/)
```

Cephadm test failures:

```
[Test Result](https://jenkins.ceph.com/job/ceph-dashboard-cephadm-e2e/12325/testReport/) (3 failures / +3)
[Add and remove labels on host (example #1).Cluster expansion host addition Add and remove labels on host (example #1)](https://jenkins.ceph.com/job/ceph-dashboard-cephadm-e2e/12325/testReport/junit/(root)/Add%20and%20remove%20labels%20on%20host%20(example%20_1)/Cluster_expansion_host_addition_Add_and_remove_labels_on_host__example__1_/)
[should create ingress as unmanaged.Services page should create ingress as unmanaged](https://jenkins.ceph.com/job/ceph-dashboard-cephadm-e2e/12325/testReport/junit/(root)/should%20create%20ingress%20as%20unmanaged/Services_page_should_create_ingress_as_unmanaged/)
[should edit a service.Create cluster create services page when Orchestrator is available should edit a service](https://jenkins.ceph.com/job/ceph-dashboard-cephadm-e2e/12325/testReport/junit/(root)/should%20edit%20a%20service/Create_cluster_create_services_page_when_Orchestrator_is_available_should_edit_a_service/)
```

**Comment by ivoalmeida** [comment]
jenkins test make check

**Comment by nizamial09** [comment]
> breadcrumb unit tests failing:

fixed

**Pull request merged**
