### PR TITLE
common: fix parse_env nullptr deref

### PR DESCRIPTION
**Pull request by batrick**
Fixes: https://tracker.ceph.com/issues/39599
Signed-off-by: Patrick Donnelly <pdonnell@redhat.com>

- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by liewegas** [comment]
Is there a test case in make check for this?

**Comment by batrick** [comment]
No. Where would you suggest we put it?

**Comment by tchaikov** [comment]
@batrick how about `src/test/common/test_config.cc` ?

**Comment by tchaikov** [comment]
retest this please.

**Comment by batrick** [comment]
@tchaikov @liewegas done!

**Comment by liewegas** [comment]
```
   $ ceph-conf -n osd.0 --show-config-value log_file -c /dev/null
   /var/log/ceph/ceph-osd.0.log
   $ CEPH_ARGS="--fsid 96a3abe6-7552-4635-a79b-f3c096ff8b95" ceph-conf -n osd.0 --show-config-value fsid -c /dev/null
-  96a3abe6-7552-4635-a79b-f3c096ff8b95
+  00000000-0000-0000-0000-000000000000
```
looks like this breaks uuid parsing?

**Comment by batrick** [comment]
> ```
>    $ ceph-conf -n osd.0 --show-config-value log_file -c /dev/null
>    /var/log/ceph/ceph-osd.0.log
>    $ CEPH_ARGS="--fsid 96a3abe6-7552-4635-a79b-f3c096ff8b95" ceph-conf -n osd.0 --show-config-value fsid -c /dev/null
> -  96a3abe6-7552-4635-a79b-f3c096ff8b95
> +  00000000-0000-0000-0000-000000000000
> ```
> 
> looks like this breaks uuid parsing?

Whoops! Okay I think I've fixed it.

**Comment by tchaikov** [comment]
retest this please.

**Comment by tchaikov** [comment]
```
/usr/bin/ld: warning: libboost_context.so.1.67.0, needed by //opt/ceph/lib/x86_64-linux-gnu/libboost_coroutine.so.1.67.0, not found (try using -rpath or -rpath-link)
//opt/ceph/lib/x86_64-linux-gnu/libboost_coroutine.so.1.67.0: undefined reference to `jump_fcontext'
//opt/ceph/lib/x86_64-linux-gnu/libboost_coroutine.so.1.67.0: undefined reference to `make_fcontext'
collect2: error: ld returned 1 exit status

Link Error: RGW library not found
src/pybind/rgw/CMakeFiles/cython_rgw.dir/build.make:57: recipe for target 'src/pybind/rgw/CMakeFiles/cython_rgw' failed
make[3]: *** [src/pybind/rgw/CMakeFiles/cython_rgw] Error 1
CMakeFiles/Makefile2:5456: recipe for target 'src/pybind/rgw/CMakeFiles/cython_rgw.dir/all' failed
```

**Comment by batrick** [comment]
@tchaikov that looks unrelated, yes? I rebased in the small hope it goes away.

**Comment by tchaikov** [comment]
@batrick no, it's actually an occurrence of http://tracker.ceph.com/issues/39995

retest this please.

**Comment by tchaikov** [comment]
- http://pulpito.ceph.com/kchai-2019-05-27_10:18:11-rados-wip-kefu-testing-2019-05-27-1206-distro-basic-smithi/
- http://pulpito.ceph.com/kchai-2019-05-28_01:35:41-rados-wip-kefu-testing-2019-05-27-1206-distro-basic-mira/

failures tracked by

- http://tracker.ceph.com/issues/23947
- http://tracker.ceph.com/issues/39644

**Comment by leseb** [comment]
Can we get this in 14.2.2? Thanks!

**Comment by liewegas** [comment]
see https://github.com/ceph/ceph/pull/28382

**Pull request merged**
