### PR TITLE
qa/tasks/swift: add support for the "force-branch" configurable.

### PR DESCRIPTION
**Pull request by rzarzynski**
http://tracker.ceph.com/issues/20547

Usage example:
```
tasks:
...
- swift:
    client.0:
      ...
      force-branch: ceph-jewel
```

CC: @cbodley, @smithfarm, @yuriw.

### CODE REVIEW

**Comment by rzarzynski** [comment]
It seems the switch is operational:
```
2017-07-07T18:11:07.653 INFO:tasks.swift:Downloading swift...
2017-07-07T18:11:07.653 INFO:teuthology.orchestra.run.mira063:Running: 'git clone -b ceph-jewel git://git.ceph.com/swift.git /home/ubuntu/cephtest/swift'
2017-07-07T18:11:07.687 INFO:teuthology.orchestra.run.mira063.stderr:Cloning into '/home/ubuntu/cephtest/swift'...
```

I'm removing the DNM mark.

**Comment by rzarzynski** [comment]
jenkins retest this please

**Comment by smithfarm** [comment]
@rzarzynski Could you add a commit to this PR, adding a `force-branch: ceph-jewel` to https://github.com/ceph/ceph/blob/master/qa/suites/rados/upgrade/jewel-x-singleton/8-workload/rgw-swift.yaml#L8-L10 ?

**Comment by smithfarm** [comment]
With `Fixes: http://tracker.ceph.com/issues/20368` in the commit message ;-)

**Comment by smithfarm** [comment]
The test would then be something like this: `teuthology-suite -k distro --machine-type smithi --priority 101 --ceph-repo https://github.com/ceph/ceph --ceph master --suite-repo https://github.com/rzarzynski/ceph --suite-branch wip-rgw-qa-swift-force-branch --suite rados --filter="upgrade/jewel-x-singleton/{0-cluster/{openstack.yaml start.yaml} 1-jewel-install/jewel.yaml 2-partial-upgrade/firsthalf.yaml 3-thrash/default.yaml 4-workload/{rbd-cls.yaml rbd-import-export.yaml readwrite.yaml snaps-few-objects.yaml} 5-workload/{radosbench.yaml rbd_api.yaml} 6-finish-upgrade.yaml 7-luminous.yaml 8-workload/{rbd-python.yaml rgw-swift.yaml snaps-many-objects.yaml}}"`

**Comment by cbodley** [comment]
> @rzarzynski Could you add a commit to this PR, adding a force-branch: ceph-jewel to https://github.com/ceph/ceph/blob/master/qa/suites/rados/upgrade/jewel-x-singleton/8-workload/rgw-swift.yaml#L8-L10 ?

i don't think that part is needed. `8-workload/rgw-swift.yaml` runs after the upgrade, so it should target the master branch of swift tests. @liewegas noticed that the `client.0` node wasn't being upgraded though (which is why that upgrade test was failing), and is testing a fix in https://github.com/ceph/ceph/pull/16222

**Comment by smithfarm** [comment]
ok

**Comment by rzarzynski** [comment]
@smithfarm: added. Thanks.

**Comment by liewegas** [comment]
is this still needed?

**Comment by smithfarm** [comment]
@liewegas Here's my perspective on your question:

The problem this PR is adressing is divergence in `ceph/swift.git` between stable releases. Typically, when this divergence appears, a `ceph-$RELEASE` (e.g. "ceph-jewel") branch is added to the swift repo and, on the ceph side, the swift.py task is modified to clone that branch specifically (hard-coded). Since we now have swift.py in the ceph repo and the ceph repo has separate branches for each stable release, this system of hard-coding the branch name is straightforward and IMO works fine.

If we wanted to get rid of the hard-coding, we could merge this and then modify all the yaml that calls swift so it specifies the branch, but this is just replacing one type of hard-coding with another, and maintaining the branch name in multiple yaml files will be more difficult than maintaining it in one place (swift.py).

**Comment by liewegas** [comment]
ok, sounds good to me!

**Pull request closed without merging**
