### PR TITLE
nautilus: switch to boost 1.72

### PR DESCRIPTION
**Pull request by tchaikov**
## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by mykaul** [comment]
How do we know RGW (and other areas using Boost) did not regress in performance?

**Comment by tchaikov** [comment]
@mykaul i think a more profound question is: how can we ensure that a change does not introduce significant performance regression?

@markhpc i think we discussed about this before. do we have any plan to implement a machinery to identify performance regression in our CI?

**Comment by tchaikov** [comment]
@neha-ojha i rebuilt libboost 1.72 with python2.6 which is shipped by bionic. so the nautilus build on bionic should be fixed now. if the slave happens to have an existing precompiled libboost 1.72 installed, i will have to reinstall them manually. as currently, in install-deps.sh, we don't install a package if it's already installed unless "force" passed to `install_pkg_on_ubuntu()`.

**Comment by yuriw** [comment]
[wip-yuri-testing-2020-01-14-2058-nautilus](https://trello.com/c/j3EAERXf/807-wip-yuri-testing-2020-01-14-2058-nautilus)

**Comment by smithfarm** [comment]
jenkins test make check

**Comment by smithfarm** [comment]
@yuriw If "make check" succeeds here, then merging this PR will fix the build failure that we just started to see in the other nautilus PRs.

**Comment by tchaikov** [comment]
jenkins test make check

**Comment by smithfarm** [comment]
@tchaikov Thanks for fixing the build! Just out of curiosity, what was causing it to fail?

**Comment by tchaikov** [comment]
@smithfarm Hi Nathan, there were two issues. the first one was https://github.com/ceph/ceph/pull/32441#issuecomment-572499171. but after i rebuilt libboost with python2 support and uploaded the prebuilt packages. i realized that the fix for https://github.com/boostorg/coroutine/issues/46 was missing in the libboost package, and the workaround of ea64c4909ffeae10e5d8e0a23604030e8849f803 was not backported to nautilus. so i figured the best fix would be patch libboost with the fix of https://github.com/boostorg/coroutine/commit/436e1dbe6fcd31523d261d18ad011392f1d6fbbc . so we don't need to backport ea64c4909ffeae10e5d8e0a23604030e8849f803. but as i put in https://github.com/ceph/ceph/pull/32441#issuecomment-572499171, install-deps.sh does not install libboost-dev again if it's already installed. so i manually re-installed this updated package on all trusty nodes this afternoon.

**Comment by smithfarm** [comment]
@tchaikov Thanks for the explanation.

**Comment by yuriw** [comment]
[wip-yuri8-testing-2020-01-21-1924-nautilus](https://trello.com/c/G7q9EcIw/811-wip-yuri8-testing-2020-01-21-1924-nautilus)

**Comment by yuriw** [comment]
@tchaikov this seems to be breaking build
https://shaman.ceph.com/builds/ceph/wip-yuri8-testing-2020-01-21-1924-nautilus/

**Comment by yuriw** [comment]
@tchaikov no love https://shaman.ceph.com/builds/ceph/wip-yuri8-testing-2020-01-23-1557-nautilus/

**Comment by wjwithagen** [comment]
Sort of a weird error in at least 2 different OSes:
```
src/test/mon/test_mon_memory_target.cc: In function 'int main(int, char**)':
[ 1037s] /home/abuild/rpmbuild/BUILD/ceph-14.2.6-340-g83a5a14/src/test/mon/test_mon_memory_target.cc:66:16: error: 'sqrt' was not declared in this scope
[ 1037s]    auto stdev = sqrt(sump / results.size());
```
And `cmath` is included in master, but not in nautilus. 
So I guess that the problem is with that.
`9acfb351a39 (Su Yue             2019-09-10 15:30:57 +0800  2) #include <cmath>`

And I guess that this is a missing backport: #30284

**Comment by tchaikov** [comment]
thanks @wjwithagen ! the fix for sqrt build failure is backport at #32815

@yuriw could you include it in your test batch?

**Comment by yuriw** [comment]
@tchaikov included #32815 and rebuilding

**Comment by cbodley** [comment]
> How do we know RGW (and other areas using Boost) did not regress in performance?

@mykaul we have been tracking API changes in boost related to our use of asio and beast. we did identify one breaking change in 1.70 that would have added extra allocations, and addressed that early on in https://github.com/ceph/ceph/pull/27730. separately, beast has been adding new features in these releases, and we'll need one in particular ([tcp_stream](https://www.boost.org/doc/libs/1_70_0/libs/beast/doc/html/beast/ref/boost__beast__tcp_stream.html)) for connection timeouts, and that will target nautilus as well

that said, we do rely on ongoing workload testing to catch performance regressions in practice

**Comment by tchaikov** [comment]
for posterities and archaeologists, #31289 is the backport for #27730 of nautilus.

**Pull request merged**
