### PR TITLE
octopus: rgw: cls/rgw/cls_rgw.cc: fix multiple lastest version problem

### PR DESCRIPTION
**Pull request by orztt**
backport tracker: https://tracker.ceph.com/issues/48239

backport of #37733 
parent tracker: https://tracker.ceph.com/issues/47919

Signed-off-by: Ruan Zitao <ruanzitao@kuaishou.com>
Signed-off-by: Yang Honggang <yanghonggang@kuaishou.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Review by smithfarm — DISMISSED** [review]
This backport has two issues:

1. It was opened before the corresponding master PR has been merged.
2. The commit message has no "(cherry picked from commit ...)" line, indicating it was not done using git cherry-pick -x.

Both of these issues are discussed in more detail at https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst (improvement suggestions welcome!)

Thank you in advance for considering this change request.

**Comment by orztt** [comment]
jenkins test api

**Comment by orztt** [comment]
jenkins test make check

**Comment by orztt** [comment]
```text
==================================== ERRORS ====================================
____________________ ERROR collecting tests/test_health.py _____________________
ImportError while importing test module '/home/jenkins-build/build/workspace/ceph-pull-requests/src/pybind/mgr/insights/tests/test_health.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python3.6/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_health.py:3: in <module>
    from ..health import *
health.py:2: in <module>
    import six
E   ModuleNotFoundError: No module named 'six'
=========================== short test summary info ============================
ERROR tests/test_health.py
!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
=============================== 1 error in 0.16s ===============================
ERROR: InvocationError for command /home/jenkins-build/build/workspace/ceph-pull-requests/build/insights/py3/bin/py.test tests/ (exited with code 2)
___________________________________ summary ____________________________________
```
@smithfarm  jenkins test make check failed, the error doesn't seem to have anything to do with my changes. How can i fix this error?  Thanks very much!

**Comment by smithfarm** [comment]
> jenkins test make check failed, the error doesn't seem to have anything to do with my changes. How can i fix this error?

Correct: the error is not related to your changes, so you are not expected to fix it.

**Comment by smithfarm** [comment]
jenkins test make check

**Review by cbodley — APPROVED** [review]

**Pull request merged**
