### PR TITLE
mgr/dashboard: fix frontend deps' vulnerabilities

### PR DESCRIPTION
**Pull request by alfonsomthd**
- Add github action: Dashboard Frontend security audit: 1st job: run npm audit.
- Remove npm-force-resolutions: no resolution needed anymore and this is modifying package-lock.json every time it is run (striping last empty line).
- Add .npmrc: save exact version by default; do not launch audit report when installing.

Fixes: https://tracker.ceph.com/issues/48005
Signed-off-by: Alfonso Martínez <almartin@redhat.com>

AFTER:
```
$ npm audit --prod
                                                                                
                       === npm audit security report ===                        
                                                                                
found 0 vulnerabilities
```

BEFORE:
Screenshot from 2021-11-30 10-19-59

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [x] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by pereman2** [comment]
jenkins test dashboard cephadm

**Comment by pereman2** [comment]
jenkins test make check arm64

**Review by pereman2 — APPROVED** [review]

**Review by Waadkh7 — APPROVED** [review]

**Comment by alfonsomthd** [comment]
jenkins test api

**Comment by alfonsomthd** [comment]
jenkins test dashboard

**Comment by alfonsomthd** [comment]
jenkins test dashboard cephadm

**Comment by alfonsomthd** [comment]
jenkins test make check arm64

**Pull request merged**
