### PR TITLE
mgr/dashboard: rm warning/error threshold for cpu usage

### PR DESCRIPTION
**Pull request by nizamial09**
for multi-core cpu's the value can be more than 100% so it doesn't make sense to show warning/error when the usage is at or more than 100%. hence removing it

Fixes: https://tracker.ceph.com/issues/58838

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Review by ivoalmeida — APPROVED** [review]

**Review by afreen23 — COMMENTED** [review]
Hey, Although this fixes the confusing thresholds issue but  I see some more concerns:

- even if we remove the thresholds, the bar chart will still display as full as its more than 100% and that might look weird from user expereince perspective

- also, since the values are coming from cephadm -> podman , hence we can fix it there to provide a normalized value out of 100 in case of multicores.

- for UXD point , it makes sense to know CPU percentage out of 100 by getting from backend  or get more data and show stats per core or show a normalized-calculated value(out of 100)

Let me know wdyt ?
Thanks

**Comment by nizamial09** [comment]
> * even if we remove the thresholds, the bar chart will still display as full as its more than 100% and that might look weird from user expereince perspective

agreed! this just fix one part of the problem where consuming more than 100% of CPU is indicated as an error but realistically it is not. And I personally don't want to add more conditions that hides/show the usage bar if usage is above 100. And with the current behavior we really can't say what will be the max value.


> * also, since the values are coming from cephadm -> podman , hence we can fix it there to provide a normalized value out of 100 in case of multicores.

We can check with @adk3798 for this on how cephadm does this. If it can be normalized from cephadm, then we rely on it to provide that. Let us know your thoughts, @adk3798.

**Review by aaSharma14 — APPROVED** [review]

**Comment by adk3798** [comment]
> > * even if we remove the thresholds, the bar chart will still display as full as its more than 100% and that might look weird from user expereince perspective
> 
> agreed! this just fix one part of the problem where consuming more than 100% of CPU is indicated as an error but realistically it is not. And I personally don't want to add more conditions that hides/show the usage bar if usage is above 100. And with the current behavior we really can't say what will be the max value.
> 
> > * also, since the values are coming from cephadm -> podman , hence we can fix it there to provide a normalized value out of 100 in case of multicores.
> 
> We can check with @adk3798 for this on how cephadm does this. If it can be normalized from cephadm, then we rely on it to provide that. Let us know your thoughts, @adk3798.

spoke with Nizam a  bit about this offline. From the cephadm side we're going to start with trying to provide the number of cores per CPU in the output of whatever dashboard is getting this info from. Then that number of cores can be used to adjust what the threshold should be. The reason being I prefer to be able to display the over 100% numbers in what cephadm reports generally as it's closer to what you'd expect from a tool like `top` so it's what I think users would expect as well.

**Comment by nizamial09** [comment]
> The reason being I prefer to be able to display the over 100% numbers in what cephadm reports generally as it's closer to what you'd expect from a tool like `top` so it's what I think users would expect as well.

thank you @adk3798, that makes sense.

@afreen23 i am merging this based on the above comment.

**Pull request merged**
