### PR TITLE
jewel: rbd-mirror: reduce memory footprint during journal replay

### PR DESCRIPTION
**Pull request by dillaman**
http://tracker.ceph.com/issues/16512
http://tracker.ceph.com/issues/16796
http://tracker.ceph.com/issues/16658
http://tracker.ceph.com/issues/16747
http://tracker.ceph.com/issues/17066
http://tracker.ceph.com/issues/16904

### CODE REVIEW

**Comment by dillaman** [comment]
retest this please

**Comment by dillaman** [comment]
(unittest_bluefs seg fault causing test failure)

**Comment by dachary** [comment]
hey jenkins, test this please (unittest_bluefs seg fault causing test failure)

**Comment by dachary** [comment]
@dillaman could you please rebase ? https://github.com/ceph/ceph/pull/10678 has been merged, hence the conflicts.

**Comment by dillaman** [comment]
@dachary rebased

**Comment by dachary** [comment]
@dillaman thanks ! There is an actual compilation problem though:
<pre>
CXX      test/rbd_mirror/image_sync/unittest_rbd_mirror-test_mock_SyncPointPruneRequest.o
test/rbd_mirror/image_sync/test_mock_ImageCopyRequest.cc:632:7: error: redefinition of ‘class rbd::mirror::image_sync::TestMockImageSyncImageCopyRequest_EmptySnapSeqs_Test’
 TEST_F(TestMockImageSyncImageCopyRequest, EmptySnapSeqs) {
       ^
test/rbd_mirror/image_sync/test_mock_ImageCopyRequest.cc:610:7: error: previous definition of ‘class 
</pre>

**Comment by dachary** [comment]
Testing in progress at http://tracker.ceph.com/issues/16904#note-5

**Comment by dachary** [comment]
@dillaman it passed a rbd suite run modulo (I think ;-) known false negatives http://tracker.ceph.com/issues/16904#note-5. Good to merge ?

**Comment by dillaman** [comment]
:+1:

**Pull request merged**
