### PR TITLE
pybind: set language_level for cythonize explicitly

### PR DESCRIPTION
**Pull request by tchaikov**
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by tchaikov** [comment]
https://shaman.ceph.com/builds/ceph/wip-26607/6cb23f9ce6b3848a7fd93d135acc143f2ae7cba1/

**Comment by dillaman** [comment]
@tchaikov Since we are most likely going to be dropping python2 for the octopus release, perhaps we can punt on this until nautilus is out?

**Comment by tchaikov** [comment]
sure, i just don't like the warning messages spit from cython.

**Comment by tchaikov** [comment]
@neha-ojha ping?

**Comment by tchaikov** [comment]
http://pulpito.ceph.com/kchai-2019-03-21_02:00:24-rados-wip-kefu-testing-2019-03-21-0010-distro-basic-mira/

**Comment by tchaikov** [comment]
will hardwire the `language_level` to "3" once we drop the support of python2.

**Pull request merged**
