### PR TITLE
luminous: rgw: policy fix for nonexistent objects

### PR DESCRIPTION
**Pull request by davebiffuk**
https://tracker.ceph.com/issues/39272

---

rgw: backport of #27309 - policy fix for nonexistent objects

This is the patch from #27309, backported to Luminous.

Fixes: https://tracker.ceph.com/issues/39272
Signed-off-by: Dave Holland <dh3@sanger.ac.uk>

- [x] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by sebastian-philipp** [comment]
looks like you haven't done a `git cherry-pick -x`. Could you please cherry-pick the original commit instead?

**Comment by davebiffuk** [comment]
Hi,

As I understand it (I'm not a git expert) this can't be cherry-picked, because the patch in pr27309 doesn't apply cleanly on Luminous - `bucket_policy.verify_permission` has slightly different arguments. So this isn't a straight application of the original commit, but a slightly different patch.

Would it be acceptable instead if I include the "cherry picked from ..." text that would have been included in the commit message?

Thanks,
Dave

**Comment by sebastian-philipp** [comment]
> Hi,
> 
> As I understand it (I'm not a git expert) this can't be cherry-picked, because the patch in pr27309 doesn't apply cleanly on Luminous - `bucket_policy.verify_permission` has slightly different arguments. So this isn't a straight application of the original commit, but a slightly different patch.
> 
> Would it be acceptable instead if I include the "cherry picked from ..." text that would have been included in the commit message?
> 
> Thanks,
> Dave

Well, you can `cherry-pick -x` and then resolve the conflicts. Additionally, please uncomment the `conflicts` section in the commit message. see http://tracker.ceph.com/projects/ceph-releases/wiki/HOWTO_backport_commits

**Comment by davebiffuk** [comment]
Thanks for your patience while I try to get this into shape! I believe I've done the cherry-pick as you asked.

**Comment by smithfarm** [comment]
@davebiffuk The commit message is not quite right. We have a "best practice" that says, when cherry-picking, do not edit the original commit message. The cherry-picked commit message can be divided into three parts:

(1) the part before the `(cherry picked from . . .)` line
(2) the `(cherry picked from . . .)` line itself
(3) the part after the `(cherry picked from . . .)` line

(1) is expected to be an exact copy of the original commit message (generated automatically by git - the idea is to not touch this part at all)
(2) also generated by git - not to be modified at all
(3) this part should include the Conflicts section if there were any cherry-pick conflicts or if any other manual changes were made.

If you think it's warranted, (3) can also include any other information you deem to add, such as your `Signed-off-by` line etc. But this is optional.

**Comment by smithfarm** [comment]
make check is shown as "Pending - running" but in reality it succeeded 17 hours ago.

**Comment by davebiffuk** [comment]
@smithfarm Thanks for the pointers. Forgive my inexperience - I wasn't trying to take Pritha's credit, just record my name for future "blame" (or otherwise). But I guess git records that? I believe I've got the commit message correct now.

**Comment by smithfarm** [comment]
@davebiffuk Commit message looks good now - thanks. You can add your `Signed-off-by` line in the bottom section, at your discretion. But you're right: git and github already record that information and most backporters omit it.

**Comment by yuriw** [comment]
[wip-yuri5-testing-2019-10-08-2016-luminous](https://trello.com/c/2sPmnyf7/713-wip-yuri5-testing-2019-10-08-2016-luminous)

**Pull request merged**
