### PR TITLE
nautilus: rgw_file: advance_mtime() should consider namespace expiration

### PR DESCRIPTION
**Pull request by pdvian**
https://tracker.ceph.com/issues/40627

### CODE REVIEW

**Comment by mattbenjamin** [comment]
https://github.com/ceph/ceph/pull/29560

**Comment by yuriw** [comment]
[wip-yuri2-testing-2019-08-15-2024-nautilus](https://trello.com/c/MlbcFeDD/691-wip-yuri2-testing-2019-08-15-2024-nautilus)

**Comment by yuriw** [comment]
@cbodley can this be merged?Reviewed-by: Casey Bodley <cbodley@redhat.com>

**Comment by smithfarm** [comment]
@cbodley @theanalyst @yuriw @mattbenjamin Do I understand correctly that:

* this PR introduces a regression into nautilus
* that regression was supposed to be addressed by including #29560 -  https://tracker.ceph.com/issues/41173 - in this PR, but that didn't happen

If I am right about the above, what does that mean for 14.2.3?

**Comment by cbodley** [comment]
@smithfarm that's correct, my intent was to block merging of this pr. i would very much like to include https://github.com/ceph/ceph/pull/29801 in 14.2.3

**Pull request merged**
