### PR TITLE
qa: reduce debug log levels for bluestore

### PR DESCRIPTION
**Pull request by dillaman**
## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by dillaman** [comment]
https://pulpito.ceph.com/?suite=rbd

**Comment by idryomov** [comment]
https://pulpito.ceph.com/dis-2021-03-03_20:46:12-krbd-master-testing-basic-gibba/

**Review by idryomov — COMMENTED** [review]
+1 from krbd perspective -- OSDs have become too chatty in pacific and master, long running xfstests jobs are regularly running 1T root disk out of space with logs.

**Review by jdurgin — APPROVED** [review]

**Review by neha-ojha — APPROVED** [review]

**Comment by dillaman** [comment]
Note: the changes are helpful but the OSDs are still extremely slow:

```
# rbd perf image iotop
 >WRITES OPS    READS OPS  WRITE BYTES   READ BYTES    WRITE LAT     READ LAT IMAGE                                                                                                                                  
        62/s         83/s    1.2 MiB/s    186 KiB/s     18.84 ms     14.25 ms client.0.1-clone
```

On my development machine, the test completes in <20 minutes (instead of timing out after 3 hours) and my latencies are <1ms or my throughput >200MiB/s. I am going to retest locally w/ bluestore at "1/20".

**Comment by dillaman** [comment]
Looks like RBD `xfstests` really need the default bluestore/bluefs/etc log levels instead of `1/20` because it slows IO down way too much even though it's all in-memory. The only alternative would be to bump up the `timeout 3h` for the QEMU task, but that seems to be the opposite of what we would want to do in the lab since machines will be busy for longer. 

This run [1] was with the "debug XYZ = ABC"' statements removed from the objectstore YAMLs and everything passes (one failed on unmount because I was tailing the test log). I also tried another run where I also decreased the OSD debug log level but that didn't seem to matter as much (and I'd rather keep the OSD logs for debugging). 

[1] https://pulpito.ceph.com/jdillaman-2021-03-04_15:59:49-rbd-wip-jd-testing-distro-basic-smithi/

**Comment by neha-ojha** [comment]
https://pulpito.ceph.com/nojha-2021-03-04_20:06:17-rados-master-distro-basic-gibba/ - rados tests look good

**Comment by batrick** [comment]
https://pulpito.ceph.com/pdonnell-2021-03-05_06:25:39-fs-wip-pdonnell-testing-20210305.032405-distro-basic-smithi/

Failures are:
- https://tracker.ceph.com/issues/48203 (stock kernel update required)
- https://tracker.ceph.com/issues/49240
- https://tracker.ceph.com/issues/48805
- https://tracker.ceph.com/issues/48773
- https://tracker.ceph.com/issues/45434
- https://tracker.ceph.com/issues/47723 (stock kernel update required?)
- https://tracker.ceph.com/issues/49605


Passes cephfs qa.

**Comment by tchaikov** [comment]
- https://pulpito.ceph.com/kchai-2021-03-06_09:19:54-rados-wip-kefu-testing-2021-03-06-1553-distro-basic-smithi/
- https://pulpito.ceph.com/kchai-2021-03-07_12:30:50-rados-wip-kefu-testing-2021-03-07-1842-distro-basic-smithi/


failures tracked by

- https://tracker.ceph.com/issues/49638
- https://tracker.ceph.com/issues/49484

but 

- https://pulpito.ceph.com/kchai-2021-03-07_12:30:50-rados-wip-kefu-testing-2021-03-07-1842-distro-basic-smithi/5944406/
- https://pulpito.ceph.com/kchai-2021-03-07_12:30:50-rados-wip-kefu-testing-2021-03-07-1842-distro-basic-smithi/5944411/

are suspicious. as thrash-erasure-code-big suites are changed in this changeset. and the same tests passed with master, see https://pulpito.ceph.com/kchai-2021-03-07_15:03:51-rados-master-distro-basic-smithi/

i need to rerun these two tests only with this change on top of master later on.

**Comment by tchaikov** [comment]
i am not able to reproduce this issue when rerunning these failed tests:

- https://pulpito.ceph.com/kchai-2021-03-08_09:55:28-rados-wip-kefu-testing-2021-03-08-0012-distro-basic-smithi/
- https://pulpito.ceph.com/kchai-2021-03-08_04:39:47-rados:thrash-erasure-code-big-wip-kefu-testing-2021-03-08-0012-distro-basic-smithi/

**Pull request merged**
