### PR TITLE
rbd: include RADOS namespace in krbd symlinks

### PR DESCRIPTION
**Pull request by idryomov**

### CODE REVIEW

**Review by dillaman — APPROVED** [review]
lgtm

**Comment by TheJJ** [comment]
The rbdnamer-script is easy to adapt, the tricky part is the `rbdmap`, which can't handle the updated `/dev` paths. I suggest to rewrite `rbdmap` in python :)

**Comment by TheJJ** [comment]
And while we're at it, we could include the `fsid` in the `/dev` symlink path to support connections to multiple clusters with images named the same.

**Comment by idryomov** [comment]
> The rbdnamer-script is easy to adapt, the tricky part is the `rbdmap`, which can't handle the updated `/dev` paths. I suggest to rewrite `rbdmap` in python :)

I actually tested that yesterday, it worked for me:

```
$ cat /etc/ceph/rbdmap 
# RbdDevice		Parameters
#poolname/imagename	id=client,keyring=/etc/ceph/ceph.client.keyring
rbd/myimage
rbd/mynamespace/myimage
$ rbd showmapped 
$ sudo systemctl start rbdmap
$ rbd showmapped 
id  pool  namespace    image    snap  device   
0   rbd                myimage  -     /dev/rbd0
1   rbd   mynamespace  myimage  -     /dev/rbd1
$ sudo systemctl stop rbdmap
$ rbd showmapped
```

```
Sep 08 19:46:07 systemd[1]: Starting Map RBD devices...
Sep 08 19:46:07 rbdmap[10373]: Mapping 'rbd/myimage'
Sep 08 19:46:08 rbdmap[10409]: Mapped 'rbd/myimage' to '/dev/rbd0'
Sep 08 19:46:08 rbdmap[10411]: Mapping 'rbd/mynamespace/myimage'
Sep 08 19:46:08 rbdmap[10444]: Mapped 'rbd/mynamespace/myimage' to '/dev/rbd1'
Sep 08 19:46:08 systemd[1]: Started Map RBD devices.
Sep 08 19:46:13 systemd[1]: Stopping Map RBD devices...
Sep 08 19:46:13 rbdmap[10466]: Unmapping '/dev/rbd0'
Sep 08 19:46:14 rbdmap[10475]: Unmapped '/dev/rbd0'
Sep 08 19:46:14 rbdmap[10481]: Unmapping '/dev/rbd1'
Sep 08 19:46:14 rbdmap[10490]: Unmapped '/dev/rbd1'
Sep 08 19:46:14 systemd[1]: Stopped Map RBD devices.
```

**Comment by idryomov** [comment]
> And while we're at it, we could include the `fsid` in the `/dev` symlink path to support connections to multiple clusters with images named the same.

Yes, there is a ticket for that, but it's not as easy as it sounds.  Namespaces is a relatively new feature -- as long as it's not used, the symlink remains the same.  If we suddenly start including the cluster fsid, it would break everybody's scripts.

One option is to leave the current symlink as is (i.e. accept that it gets overwritten if an image with the same spec gets mapped) and create a separate symlink with the cluster fsid alongside.  Not sure how much it matters though, as I suspect very few people would ever run into this.

**Comment by TheJJ** [comment]
I see, yes you're right. My adjustments to the rbdnamer were different - it always included a namespace. It was right after the nautilus release when I tried to fix this, but I probably messed up something.

With the fsid - yes, that's a problem. But this pull alone is a great improvement, thank you!

**Comment by idryomov** [comment]
https://pulpito.ceph.com/dis-2020-09-09_21:16:02-krbd-wip-krbd-namespace-symlinks-testing-basic-smithi/
https://pulpito.ceph.com/dis-2020-09-09_22:35:49-krbd-wip-krbd-namespace-symlinks-testing-basic-smithi/

**Pull request merged**
