### PR TITLE
selinux: Update policy for radosgw

### PR DESCRIPTION
**Pull request by branto1**
The current SELinux policy does not cover radosgw daemon. This patch
introduces the SELinux support for radosgw daemon (civetweb only).

Signed-off-by: Boris Ranto <branto@redhat.com>

### CODE REVIEW

**Comment by branto1** [comment]
Initial teuthology tests look ok.

**Comment by dachary** [comment]
@branto1 could you please add the URL to the teuthology job that succeeded ?

**Comment by branto1** [comment]
@dachary: Sure, I did not say succeed, though. There are just no SELinux failures in the run (i.e. the failures are not caused by this patch):

http://pulpito.ceph.redhat.com/teuthology-2015-08-10_17:28:07-rgw-wip-selinux-radosgw-distro-basic-magna/

**Comment by branto1** [comment]
Can we get this merged? This is a fairly minor/simple policy update.

**Comment by mbroz** [comment]
LGTM, I think we should this merge now so the policy is tested together for all daemons...

**Comment by dachary** [comment]
please ignore the bot failure, it's a false negative

**Pull request merged**
