### PR TITLE
common/bl, *: deprecate bufferlist::claim() and switch to rvalue-taking operator=()

### PR DESCRIPTION
**Pull request by rzarzynski**
## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by rzarzynski** [comment]
> What about `claim_append()`?  The set of files to patch would be pretty much the same, I suspect.  Probably makes sense to do both in a single PR.

`claim_append()` will be deprecated as well. It has more occurrences. WIP.

> Probably makes sense to do both in a single PR.

The intention is to make the review process easier by not mixing components. Somebody involved in, let's say, RGW doesn't need to worry about e.g. monitor. After we could squash.

**Comment by tchaikov** [comment]
- https://pulpito.ceph.com/kchai-2020-06-25_14:36:27-rados-wip-kefu-testing-2020-06-25-1815-distro-basic-smithi/
- https://pulpito.ceph.com/kchai-2020-06-27_03:47:06-rados-wip-kefu-testing-2020-06-26-1211-distro-basic-smithi/
- https://pulpito.ceph.com/kchai-2020-06-27_07:37:00-rados-wip-kefu-testing-2020-06-27-1407-distro-basic-smithi/

failures tracked by

- https://tracker.ceph.com/issues/46054
- https://tracker.ceph.com/issues/45721
- https://tracker.ceph.com/issues/44595

**Comment by tchaikov** [comment]
@rzarzynski please feel free to merge this PR once it's ready.

**Comment by rzarzynski** [comment]
@idryomov, @tchaikov: squashed! No difference apart that.

**Pull request merged**
