### PR TITLE
rgw & msgr fixes from 15.2.1 

### PR DESCRIPTION
**Pull request by theanalyst**
These were on nautilus/octopus but not on master

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by idryomov** [comment]
Huh, I could have sworn I saw them on master -- and indicated so in more than one conversation.  Must have confused with the octopus branch that I had checked out for a while because of unrelated backport work, sorry!

**Comment by theanalyst** [comment]
> Huh, I could have sworn I saw them on master -- and indicated so in more than one conversation. Must have confused with the octopus branch that I had checked out for a while because of unrelated backport work, sorry!

Yes, I also assumed they were still in the octopus -> master merge cycle, and forgot an explicit cherry-pick to master

**Comment by idryomov** [comment]
@neha-ojha, @tchaikov This is tagged with messenger, so probably went under your radar.  Could you please pull it into your integration branches?

**Comment by neha-ojha** [comment]
> @neha-ojha, @tchaikov This is tagged with messenger, so probably went under your radar. Could you please pull it into your integration branches?

sure, added the core label as well. The rados suite has a lot of noise right now, we'll test this once those clear up.

**Comment by tchaikov** [comment]
- http://pulpito.ceph.com/kchai-2020-05-27_23:43:53-rados-wip-kefu-testing-2020-05-27-2242-distro-basic-smithi/
- http://pulpito.ceph.com/kchai-2020-05-28_06:49:15-rados-wip-kefu-testing-2020-05-27-2242-distro-basic-smithi/

failed tests are tracked by

- https://tracker.ceph.com/issues/45661
- https://tracker.ceph.com/issues/45734
- https://tracker.ceph.com/issues/44595
- https://tracker.ceph.com/issues/45343
- https://tracker.ceph.com/issues/45660

**Comment by tchaikov** [comment]
@cbodley Casey, could you include this changset in your next batch?

**Comment by neha-ojha** [comment]
> @neha-ojha Ping, do we need another RADOS run here?

don't think so, I am not seeing any changes since @tchaikov tested it 

> 
> @cbodley What is the status on your end? Do you want to get this through rgw suite or are you OK with us merging?

**Comment by idryomov** [comment]
@neha-ojha Sorry, I'm not clear -- do you expect changes to this PR or are you OK with the results of Kefu's run?

**Pull request merged**
