### PR TITLE
dmclock: pick up fix to replace uint

### PR DESCRIPTION
**Pull request by tchaikov**
`uint` is not available in musl. so this change should address the FTBFS
on distros, like Alpine and Gentoo Linux, which uses musl-libc.

Signed-off-by: Kefu Chai <kchai@redhat.com>

- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by tchaikov** [comment]
the change on dmclock side was pushed to ceph repo as `wip-uint` branch. will update this PR to point the merge commit, once https://github.com/ceph/dmclock/pull/72 is merged.

**Comment by ivancich** [comment]
Rather than do this in two steps, I'm going to recommend we close this in favor of https://github.com/ceph/ceph/pull/28846 .

The dmclock library just merged the associated commit, so we can pull dmclock from there.

**Comment by ivancich** [comment]
I leave the ultimate decision as to which way to go to @tchaikov .

**Comment by tchaikov** [comment]
@ivancich i am good either way. actually, the reason i wanted to this in 2 steps in hope to get this PR reviewed sooner before https://github.com/ceph/dmclock/pull/72 was merged. and i pointed this PR to the updated dmclock commit after that. so this PR and #28846 are literally identical.

but i prefer this PR over #28846. because it states the reason of the change in the commit message.

**Comment by tchaikov** [comment]
- http://pulpito.ceph.com/kchai-2019-07-04_12:44:28-rados-wip-kefu-testing-2019-07-04-1747-distro-basic-smithi/
- http://pulpito.ceph.com/kchai-2019-07-05_01:50:15-rados-wip-kefu-testing-2019-07-05-0137-distro-basic-smithi/

**Pull request merged**
