### PR TITLE
Quincy: osd/scrub: verify SnapMapper consistency

### PR DESCRIPTION
**Pull request by ronen-fr**
Whenever the scrubber accesses the SnapMapper for the snaps of a specific
clone, the mapper will now verify that the snaps have the required
mapping DB entries (the 'SNA_' keys).

A manual back-port of https://github.com/ceph/ceph/pull/47388
backport tracker: https://tracker.ceph.com/issues/59537

Signed-off-by: Ronen Friedman [rfriedma@redhat.com](mailto:rfriedma@redhat.com)

### CODE REVIEW

**Comment by ronen-fr** [comment]
Draft, as no Teuthology tests yet.

**Comment by athanatos** [comment]
@ronen-fr "manual back-port" -- does that mean there were conflicts you needed to address?

**Comment by athanatos** [comment]
I also don't see cherry-pick tags like ```(cherry picked from commit ...)```

**Comment by ronen-fr** [comment]
@athanatos 
> @ronen-fr "manual back-port" -- does that mean there were conflicts you needed to address?

(I mentioned this in the Core meeting) I had two false starts trying to cherry-pick the original commits. The two main issues I've encountered: (1) the refactoring of the scrub backend that happened in between (and changed the files where the relevant functions are placed), and (2) compilation issues caused by the updated compilation environment. The two together required so many manual changes, that I considered the result less safe than what I finally did here: copying the relevant changes from the original PR, into the (not the same) files in Quincy.

(Two false starts and not one, as in the 1'st I simply backported the PR and manually moved the changes to the pre-factored files, and in the 2'nd - tried to backport the backend refactoring as a first step, then this PR).

**Comment by ronen-fr** [comment]
Closing in favor of https://github.com/ceph/ceph/pull/52256

**Pull request closed without merging**
