### PR TITLE
ECBackend: For first read, it can meet the situation which can't read.

### PR DESCRIPTION
**Pull request by majianpeng**
Signed-off-by: Jianpeng Ma <jianpeng.ma@intel.com>

### CODE REVIEW

**Comment by tchaikov** [comment]
@majianpeng  looks good to me. but could be great if you can update the commit log with more details.

**Comment by majianpeng** [comment]
@tchaikov . Updated. Thanks your suggestion. In test/ceph-helper.sh, there is test-case about pg repair. But don't consider this situation. Before https://github.com/majianpeng/ceph/commit/b5c7787a84c272b2aa88be3d4edc5e37cc4fe653 merge, the recovery will endless.

**Comment by tchaikov** [comment]
@majianpeng thank you. i am looking at #4269 .

**Comment by tchaikov** [comment]
@majianpeng could you add a test case in tethology for this fix?

**Comment by majianpeng** [comment]
@tchaikov . 8f30db85219a6c57cb2fc03f4049a3f57446ca55 can cover this case.

**Comment by tchaikov** [comment]
sorry, @majianpeng i don't get you. if 8f30db8 covers this case. it will fail the build bot since this pull request has not been merged. am i missing something?

**Comment by majianpeng** [comment]
@tchaikov . Because the d51806f5b330d5f112281fbb95ea6addf994324e, now for this case(unrecovery object) don't be there. So although https://github.com/ceph/ceph/commit/8f30db85219a6c57cb2fc03f4049a3f57446ca55 can cover this case, but the bug don't occur. I think we remove the path which can call this.

**Comment by tchaikov** [comment]
@majianpeng sorry for the latency. IIUC, https://github.com/majianpeng/ceph/commit/b16b080332616f12852c15cd27e022a83ed86319 will prevent us from moving forward if the object is not recoverable. and hence this will not likely happen.

**Comment by tchaikov** [comment]
`Reviewed-by: Kefu Chai <kchai@redhat.com>` after the qa run.

**Comment by athanatos** [comment]
The reason for this is that we won't hit this case at all on the first operation, only when initiating subsequent ones.  The way in which this can happen is if one of the shards we are reading from is not in the up/acting sets and goes down.  I think the assert is correct as it.

**Comment by athanatos** [comment]
The test you mentioned probably does not cover this case if it has been passing up to now.

**Comment by athanatos** [comment]
Closing, if I'm wrong, reopen!

**Pull request closed without merging**
