### PR TITLE
admin/build-doc: svg peering diagram instead of graphviz

### PR DESCRIPTION
**Pull request by tchaikov**
Signed-off-by: Mark Nelson <mnelson@redhat.com>

### CODE REVIEW

**Comment by tchaikov** [comment]
jenkins render docs

**Comment by tchaikov** [comment]
dup with #20366

**Comment by dmick** [comment]
How do you even find this in the TOC these days?

**Comment by tchaikov** [comment]
@dmick well, the TOC is now sitting at http://docs.ceph.com/ceph-prs/20366/dev/index-old/ , while the index-old is not reachable from the frontpage anymore, see b6f9a9b2b1a17e2cb73fd90b5d66599f38c32d71 .

@smithfarm is there anyway we can improve this? i think the "internals" doc is also a valuable source for developers?

**Pull request closed without merging**
