### PR TITLE
inline_memory: optimized mem_is_zero for aarch64 by neon intrinsic

### PR DESCRIPTION
**Pull request by Svelar**
The Neon instruction can be used to optimize mem_is_Zero. The Neon instruction can load 128-bit data. Most ARM CPU architectures have 2 LD loading channels. Therefore, two 128-bit data can be loaded at the same time, which is good for block data.

We did a set of performance tests with different sizes compare TSV110 with default implementation, it shows about 50% improvement.

loop: 1,000,000
used time:

|size    |    default      |     neon|
| ------ | ------ | ------ |
|1024    |    0.091       |     0.044|
|2048    |    0.177       |     0.092|
|4096    |    0.348       |     0.175|
|8192    |    0.689       |     0.345|
|65536   |    5.471       |     2.746|

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [x] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [x] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Comment by Svelar** [comment]
jenkins test make check

**Review by markhpc — COMMENTED** [review]
Very nice!  I don't have any ARM hardware in the upstream lab to test this on, but at least we can make sure it builds.  One question:  When you say "Most ARM CPU architectures have 2 LD loading channels.", will the ones that don't have 2 LD loading channels work properly with the elif conditional here?

**Comment by Svelar** [comment]
> Very nice! I don't have any ARM hardware in the upstream lab to test this on, but at least we can make sure it builds. One question: When you say "Most ARM CPU architectures have 2 LD loading channels.", will the ones that don't have 2 LD loading channels work properly with the elif conditional here?

Thanks Mark! I would say that almost all new ARM machines have at least 2 LD channels(even 4 or more). But if the machine had less than 2 channels, the program would still work fine with this condition. Cuz I don't have such server, but in theory, nothing would be affected but performance. Overall it would not get worse result even the machine only has one LD channel. BTW, could it be tested on the ARM machine which ran 'arm make check' now?

**Review by athanatos — APPROVED** [review]
Seems reasonable to me.

**Comment by Svelar** [comment]
https://pulpito.ceph.com/svelar-2024-01-03_06:20:29-rados-wip-svelar-testing-1-2024-01-03-0329-distro-default-smithi/

3 Failed, 1 Dead caused by infra issues. Seems like reasonable to merge from the runs.

**Pull request merged**
