### PR TITLE
rgw: enforce Content-Type in Swift responses.

### PR DESCRIPTION
**Pull request by rzarzynski**

### CODE REVIEW

**Comment by rzarzynski** [comment]
@yehudasa only commit message has been altered (added ```Fixes```, improved the description).

**Comment by yehudasa** [comment]
@rzarzynski also, can you reopen this pull request against the 'next' branch?

**Comment by rzarzynski** [comment]
@yehudasa no problem, but I'm not sure how the exact procedure does look like. Should I create a new branch starting from ```next```, cherry pick the commit and then send a new PR?

**Comment by rzarzynski** [comment]
@yehudasa created PR #5089 for the ```next``` branch.

**Pull request closed without merging**
