### PR TITLE
osd: copy the RecoveryCtx::handle for when creating RecoveryCtx instance from another one

### PR DESCRIPTION
**Pull request by guangyy**
Fixes: 12523
Signed-off-by: Guang Yang <yguang@yahoo-inc.com>

### CODE REVIEW

**Comment by hjwsm1989** [comment]
nice catch!

**Comment by liewegas** [comment]
Reviewed-by:

**Comment by guangyy** [comment]
After applying this patch, we have brought the cluster back to healthy :)

**Comment by tchaikov** [comment]
LGTM.

**Pull request merged**
