### PR TITLE
DNM: jewel: rgw: cannot limit users to not create buckets

### PR DESCRIPTION
**Pull request by Abhishekvrshny**
http://tracker.ceph.com/issues/16163

### CODE REVIEW

**Comment by dang** [comment]
This looks reasonable in general, but what does zero mean now?  It used to mean "unset".  Now, there's a bool for that, and <0 is checked for denied, but what if the user sets it to zero?

**Comment by Abhishekvrshny** [comment]
test this please

**Comment by prallabh** [comment]
@dang I see that it means 'no limit' per comment here http://tracker.ceph.com/issues/14534#note-2

**Comment by dachary** [comment]
@Abhishekvrshny could you please edit the commit message to reflect how the conflict was resolved ?

**Comment by dachary** [comment]
It passed the rgw suite http://tracker.ceph.com/issues/16344#note-6 (except for one failure which I believe to be unrelated).

**Comment by yehudasa** [comment]
@dachary lgtm, merge at will

**Comment by dachary** [comment]
Replaced with https://github.com/ceph/ceph/pull/10655

**Pull request closed without merging**
