### PR TITLE
ceph.in: Minor python3 specific changes

### PR DESCRIPTION
**Pull request by saru95**

### CODE REVIEW

**Comment by saru95** [comment]
@tchaikov fixed the spaces in this . opened a new PR because I messed up the old one .

**Comment by tchaikov** [comment]
lgtm

**Comment by theanalyst** [comment]
@saru95 nit, there are two signed-off-by lines in commit, could you make it just one

**Comment by saru95** [comment]
Oh ! my bad ! Corrected @theanalyst

**Comment by jdurgin** [comment]
looks good, thanks!

**Comment by tchaikov** [comment]
tested at http://pulpito.ceph.com/kchai-2016-03-11_19:18:43-rados-wip-kefu-testing---basic-smithi/ , failed tests are known issues and not related to the tested changes:

- http://tracker.ceph.com/issues/15077
- http://tracker.ceph.com/issues/15047
- http://tracker.ceph.com/issues/15106
- http://tracker.ceph.com/issues/15113

**Comment by saru95** [comment]
working on it !

**Comment by tchaikov** [comment]
@saru95 what do you mean exactly? the issues above are all being taken care of.

**Comment by saru95** [comment]
@tchaikov there are some tests that fail when you run `make check` from within src .

**Pull request merged**
