### PR TITLE
luminous: client: fix bug of cap release no respond to unchanged revoke

### PR DESCRIPTION
**Pull request by cmgitdream**
in some sutitaion, mds need client reply caps to eval mds lock machine to 
next stable state, so client should send cap even if received old caps on op CEPH_CAP_OP_REVOKE

Signed-off-by: Min Chen <chenmin@sangfor.com.cn>

### CODE REVIEW

**Comment by cmgitdream** [comment]
@ukernel

**Comment by batrick** [comment]
Why is this patch not against master?

**Comment by cmgitdream** [comment]
@batrick we just reproduce it on luminous, and not sure this affects on master,
may backport to master later

**Comment by batrick** [comment]
Sorry that's not how we do things. Anything backported to Luminous must first go into master unless the issue only exists in Luminous.

That's not the case here.

**Comment by cmgitdream** [comment]
@batrick , ok

**Comment by batrick** [comment]
@cmgitdream we're grateful for your contribution. I encourage you to submit an issue to the Ceph issue tracker describing the problem. Then submit a PR against master. We will work on getting the fix into Luminous as soon as the master PR is merged.

**Pull request closed without merging**
