### PR TITLE
mds: delay MMDSCacheRejoin::OP_WEAK until rejoin

### PR DESCRIPTION
**Pull request by batrick**
Fixes: http://tracker.ceph.com/issues/21777

Signed-off-by: Patrick Donnelly <pdonnell@redhat.com>

### CODE REVIEW

**Comment by batrick** [comment]
@ukernel I think this is a reasonable fix. I considered dropping the message too but I don't think the sender handles that case properly unless the mds eventually fails (handle_mds_failure).

If you think a different approach is better, please go ahead and write up a new PR so we can close this ticket ASAP.

**Comment by ukernel** [comment]
I checked log of crashed mds, it got cache rejoin message in reconnect state. I have no idea how this can happen. It's better to wait for the bug to happen again, instead of hiding it.

**Comment by batrick** [comment]
From what I can tell, one way for this to happen is for two standbys to take over failed ranks. First MDS to reach rejoin will send `MMDSCacheRejoin::OP_WEAK` to the other MDS which is not in rejoin yet.

**Comment by batrick** [comment]
I'm writing a test to confirm now...

**Comment by ukernel** [comment]
On Fri, Oct 13, 2017 at 10:22 AM, Patrick Donnelly
<notifications@github.com> wrote:
>
> From what I can tell, one way for this to happen is for two standbys to take over failed ranks. First MDS to reach rejoin will send MMDSCacheRejoin::OP_WEAK to the other MDS which is not in rejoin yet.


It shouldn't happen, check MDSMap::is_rejoining()

**Comment by batrick** [comment]
Right, I didn't know about `MDSMap::is_rejoining`. I wasn't able to reproduce this and I agree the scenario which prompted this PR shouldn't happen so I'll close this.

**Comment by batrick** [comment]
@ukernel looking at this again after working on #21577, I think it makes sense that an up:starting MDS would cause `MDSMap::is_rejoining` to wrongly return true?

**Comment by LiuHongdong** [comment]
@unkernel @batrick    I have a situation: 
1 When mdsA in rejoin_join_start, and waitting for processing caps
2 During of the waitting, mdsB is restart
3 When mdsA process_caps is complete, and waiting  for mdsB resolve
4 mdsA handle_resolve mdsB, and send pending rejoins to mdsB
5 mdsB is resolve or reconnect state, and then crush.

**Comment by LiuHongdong** [comment]
@ukernel @batrick I have a situation: 
1 When mdsA in rejoin_join_start, and waitting for processing caps
2 During of the waitting, mdsB is restart
3 When mdsA process_caps is complete, and waiting  for mdsB resolve
4 mdsA handle_resolve mdsB, and send pending rejoins to mdsB
5 mdsB is resolve or reconnect state, and then crush.

**Pull request closed without merging**
