### PR TITLE
os: misc bug fix for fiemap

### PR DESCRIPTION
**Pull request by mslovy**
fix issue http://tracker.ceph.com/issues/14055
misc bug fix for fiemap
add test case for fiemap

Reported-by: YiQiang Chen cyqsign@163.com
Signed-off-by: Ning Yao <zay11022@gmail.com>

### CODE REVIEW

**Comment by liewegas** [comment]
Do you mind rebasing this on liewegas/ceph.git wip-bluestore?  Also, please add a test case to test/objectstore/store_test.cc that reproduces the case?

Thanks!

**Comment by mslovy** [comment]
@liewegas the memstore fiemap semantics  is different with others so that we need different test code for different backend? Any guided

**Comment by mslovy** [comment]
rebase on liewegas/ceph.git wip-bluestore

**Comment by liewegas** [comment]
MemStore is different because it always returns the whole range?  I would 
make the test assert that the returned range is a superset of what has 
been written and a subset of [0,object_size].

FWIW it looks like if offset is > object_size it puts an offset=0 entry in 
the result map, which seems wrong...

**Comment by mslovy** [comment]
If offset >= object_size, it will return immediately with uninitialized bufferlist, which lead to a decode exception.
https://github.com/ceph/ceph/blob/master/src/os/newstore/NewStore.cc#L1377

rewrite the test case and add more general test case(e.g. the out of boundary case for offset > object_size). Any other cases needed, for example, offset != 0 and length == 0. But I don't think we will call fiemap() with length == 0 except that offset == length == 0.

**Comment by liewegas** [comment]
Please rebase on master?  ALso, I tried to merge these manually and it made all of the backends fail on the new fiemap test... please run ceph_test_objectstore --gtest_filter=*Fiemap* to verify it passes.  Thanks!

**Comment by mslovy** [comment]
@liewegas , cannot pass the compilation after rebase as linking error with rockdbs, undefined reference, in bluestore?  Any configurations need to set for bluestore?

**Comment by liewegas** [comment]
try cd rocksdb ; make clean ; cd ..

**Comment by mslovy** [comment]
@liewegas , different backend gives different result for test case (offset == length == 0). Like FileStore backend, {0,0} will be returned. However, for bluestore, it resets length = o->onode.size() so return the whole ranges.  And so if client request a fiemap data with op.extent.offset == op.extent.length == 0, what kinds of the results is expected?  nothing with {0,0} or whole ranges?

**Comment by liewegas** [comment]
Hmm, i wonder if we should assert if the caller asks for an offset past eof?  Presumably no caller actually does that?

Let's standardize all of the implementations so that they behave the same for these corner cases, and add store_test.cc tests.  So, make the others match the FileStore behavior when len == 0...

**Comment by mslovy** [comment]
@liewegas , Hmm, So use assertion to make sure len!=0.  And for offset > object.size(),  I would like to deal with it what the filesystem(like, ext4 or xfs) do. treat it as a out of boundary case and just return nothing. 
Another issue may relate to overlay and fragment in bluestore. When disable overlay, based on current strategy, it is the same as memstore since stupid allocator always allocate fixed length (like 64k) one time and onode_t cannot tell which content is sparse in this 64k yet . So I would skip this issue currentlly. 
Please review, thx.

**Comment by yuyuyu101** [comment]
@liewegas 
sage should do something similar before, not sure exists overlap here.

**Comment by mslovy** [comment]
@yuyuyu101  Yeah, I think you mention https://github.com/ceph/ceph/pull/7267 and e29ca1cfd7292d117be4d5234287ff995e0a7032 in https://github.com/ceph/ceph/pull/7130. So I would like to close this PR now.

**Pull request closed without merging**
