### PR TITLE
cephadm/services/ingress: configure security user in keepalived template

### PR DESCRIPTION
**Pull request by thegreenbear**
It is cleaner to enable script security and define a script user for keepalived.

When keepalived start the following messages are logged:
```
Fri Apr  5 09:24:18 2024: Starting Keepalived v2.2.4 (08/21,2021)
Fri Apr  5 09:24:18 2024: Running on Linux 5.15.0-91-generic #101-Ubuntu SMP Tue Nov 14 13:30:08 UTC 2023 (built for Linux 5.14.0)
Fri Apr  5 09:24:18 2024: Command line: '/usr/sbin/keepalived' '-n' '-l' '-f' '/etc/keepalived/keepalived.conf'
Fri Apr  5 09:24:18 2024: Configuration file /etc/keepalived/keepalived.conf
Fri Apr  5 09:24:18 2024: NOTICE: setting config option max_auto_priority should result in better keepalived performance
Fri Apr  5 09:24:18 2024: Starting VRRP child process, pid=4
Fri Apr  5 09:24:18 2024: WARNING - default user 'keepalived_script' for script execution does not exist - please create.
Fri Apr  5 09:24:18 2024: Startup complete
Fri Apr  5 09:24:18 2024: SECURITY VIOLATION - scripts are being executed but script_security not enabled.
[...]
```
Setting appropriately the script security will remove the WARNING and the scrary SECURITY VIOLATION.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [x] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

### CODE REVIEW

**Comment by thegreenbear** [comment]
Should I open a bug in the tracker?

**Review by phlogistonjohn — APPROVED** [review]
Looks ok to me, after reading up on these options in the docs.

**Comment by phlogistonjohn** [comment]
> Should I open a bug in the tracker?

If you would like the change backported, you should.

**Review by phlogistonjohn — COMMENTED** [review]
I was a bit too quick to approve, you need to update the unit tests to match your changes to the template so that the CI tests pass.

**Comment by thegreenbear** [comment]
> I was a bit too quick to approve, you need to update the unit tests to match your changes to the template so that the CI tests pass.

Will do soon.

**Review by adk3798 — APPROVED** [review]

**Comment by thegreenbear** [comment]
There's two checks still failing but I do not think they are related to my change.

**Comment by adk3798** [comment]
https://pulpito.ceph.com/adking-2024-06-10_15:49:42-orch:cephadm-wip-adk-testing-2024-06-10-0759-distro-default-smithi/

failures consisted of

- 18 `in cluster log` type failures, still being cleaned up and a known issue
- 3 failures in the cleanup of rados_api_tests, don't know the tracker number but this is a known issue
- 2 failures in mds_upgrade_sequence, known issue
- 1 failure with staggered upgrade while agent is active, known issue
- lots of dead jobs due to `Error reimaging machines: Failed to power on smithiXXX`, general lab/teuthology issue unrelated to the PRs in the run

Nothing to block merging for most PRs in the run

**Pull request merged**
