### PR TITLE
osd/osd_types: fix pg_pool_t encoding for hammer

### PR DESCRIPTION
**Pull request by liewegas**
If we are missing the hammer feature, we will also be missing the
luminous feature, but we should still encode like hammer.

Analogous fix to e28e0c617af8825ae92cced5d87cc4f403709e48

Signed-off-by: Sage Weil <sage@redhat.com>

### CODE REVIEW

**Comment by tchaikov** [comment]
should be backported to luminous.

**Comment by liewegas** [comment]
https://github.com/ceph/ceph/pull/21283

**Comment by idryomov** [comment]
@liewegas 
```
/home/jenkins-build/build/workspace/ceph-pull-requests/src/osd/OSDMap.cc: In member function 'int OSDMap::Incremental::propagate_snaps_to_tiers(CephContext*, const OSDMap&)':
/home/jenkins-build/build/workspace/ceph-pull-requests/src/osd/OSDMap.cc:237:31: error: 'FLAG_SELFMANAGED_SNAPS' was not declared in this scope
  tier->flags |= base.flags & (FLAG_SELFMANAGED_SNAPS|
                               ^~~~~~~~~~~~~~~~~~~~~~
/home/jenkins-build/build/workspace/ceph-pull-requests/src/osd/OSDMap.cc:238:10: error: 'FLAG_POOL_SNAPS' was not declared in this scope
          FLAG_POOL_SNAPS);
          ^~~~~~~~~~~~~~~
```

**Comment by idryomov** [comment]
Otherwise looks good.  The kernel client isn't affected because `OSD_POOLRESEND`, `NEW_OSDOP_ENCODING` and `SERVER_LUMINOUS` were implemented together in 4.13.  Older kernels actually get v14.

**Pull request merged**
