### PR TITLE
log: Log.cc: Assign LOG_DEBUG priority to syslog calls

### PR DESCRIPTION
**Pull request by badone**
Fixes: #13993
Signed-off-by: Brad Hubbard <bhubbard@redhat.com>

### CODE REVIEW

**Comment by badone** [comment]
I know there was a new release of gperftools recently. Has this broken the build or was it something I did (can't think what)?

**Comment by dachary** [comment]
@badone please ignore the bot failure, it is a false negative (see http://tracker.ceph.com/issues/13997 for more information). You can re-schedule a job by rebasing your branch and repushing.

**Comment by liewegas** [comment]
lgtm

**Comment by liewegas** [comment]
@badone please rebase

**Comment by badone** [comment]
@sage done

**Pull request merged**
