### PR TITLE
nautilus: tools/rados: add support for binary object names in the rados CLI

### PR DESCRIPTION
**Pull request by rzarzynski**
A backport of PR #39328. Strictly speaking it's a new feature. However, this feature is necessary to clean a cluster after of a bug-induced problems.

Related-backport: #39324.
Related-`master`: https://github.com/ceph/ceph/pull/39322.

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by smithfarm** [comment]
@tchaikov I noticed you added both `needs-qa` and `nautilus-batch-1` here. The idea is to only do that when all required Jenkins checks have passed.

**Comment by tchaikov** [comment]
jenkins test make check

**Comment by tchaikov** [comment]
jenkins test api

**Comment by tchaikov** [comment]
@smithfarm sorry and thanks, Nathan. will try to ensure that the tests pass before adding those labels in future.

**Review by ivancich — APPROVED** [review]

**Pull request merged**
