### PR TITLE
Wip compressor

### PR DESCRIPTION
**Pull request by yuyuyu101**
Compressor: Add compressor infrastructure for ceph

AsyncCompressor is a stucture which implement the nonblock compress method, callers could compress this and then get the resulted data later. Of course, callers could directly wait for the compressor completed.
    
Compression algorithm usually uses lots of helper data to speed compress, so here AsyncCompressor uses dedicated threads to help cache-affinity. Second, We want to make compression parallel with normal io logic. For example, any component receive data may not need to care the actual data and need to do some things with metadata. We could let metadata process parallel with data compression.

### CODE REVIEW

**Comment by joehandzik** [comment]
Awesome! Was Snappy your first choice, or I did I help motivate that? :)

**Comment by liewegas** [comment]
This looks very reasonable to me!

I'm not sure I see the value in the affinity (pinning compression/decompression to a core) since the data its operating on located who knows where in the system, and we're never going to be compressing and decompressing the same buffers in the same process (right?).

**Comment by yuyuyu101** [comment]
Hmm, I think it's fine that we dont bind thread to cores

**Comment by yuyuyu101** [comment]
@liewegas Do we merge this PR or make #3490 append?

**Pull request merged**
