### PR TITLE
denc cleanups and other fixes

### PR DESCRIPTION
**Pull request by adamemerson**
Recent changes have broken compilation under Clang. Fix that.

Clean up a bit while we're at it.

### CODE REVIEW

**Comment by wjwithagen** [comment]
@adamemerson 
Thanx, I'll give it a ru in FreeBSD-jenkins.

**Comment by tchaikov** [comment]
@adamemerson thanks for the fix and cleanups! love them!

**Comment by wjwithagen** [comment]
@adamemerson @tchaikov 
Some commit broke the denc code again on Clang.
See http://cephdev.digiware.nl:8180/jenkins/job/ceph-master/1672/console
There a a number of problems, but the first hit is:
```
n file included from /home/jenkins/workspace/ceph-master/src/common/SloppyCRCMap.cc:4:
In file included from /home/jenkins/workspace/ceph-master/src/common/SloppyCRCMap.h:7:
In file included from /home/jenkins/workspace/ceph-master/src/include/encoding.h:37:
/home/jenkins/workspace/ceph-master/src/include/denc.h:1528:3: error: no matching function for call to 'bound_encode'
  traits::bound_encode(o, len);
  ^~~~~~~~~~~~~~~~~~~~
/home/jenkins/workspace/ceph-master/src/common/SloppyCRCMap.cc:145:3: note: in instantiation of function template specialization 'ceph::encode<std::__1::map<unsigned long, unsigned int, std::__1::less<unsigned long>, std::__1::allocator<std::__1::pair<const unsigned long, unsigned int> > >, denc_traits<std::__1::map<unsigned long, unsigned int, std::__1::less<unsigned long>, std::__1::allocator<std::__1::pair<const unsigned long, unsigned int> > >, void> >' requested here
  encode(crc_map, bl);
  ^
/home/jenkins/workspace/ceph-master/src/include/denc.h:863:5: note: candidate template ignored: substitution failure [with U = std::__1::pair<unsigned long, unsigned int>]: non-type template argument evaluates to 16, which cannot be narrowed to type 'bool'
    bound_encode(const container& s, size_t& p, uint64_t f = 0) {
    ^
/home/jenkins/workspace/ceph-master/src/include/denc.h:1530:3: error: no matching function for call to 'encode'
  traits::encode(o, a);
  ^~~~~~~~~~~~~~
/home/jenkins/workspace/ceph-master/src/include/denc.h:890:5: note: candidate template ignored: substitution failure [with U = std::__1::pair<unsigned long, unsigned int>]: non-type template argument evaluates to 16, which cannot be narrowed to type 'bool'
    encode(const container& s, buffer::list::contiguous_appender& p,
    ^
2 errors generated.
gmake[2]: *** [src/CMakeFiles/common-objs.dir/build.make:1096: src/CMakeFiles/common-objs.dir/common/SloppyCRCMap.cc.o] Error 1
```

**Comment by wjwithagen** [comment]
@adamemerson @tchaikov 
Probably due to the same reason as to why there are now merge-conflicts in this PR.

**Comment by adamemerson** [comment]
All right. Rebased. Compiles under Clang for me.

**Comment by wjwithagen** [comment]
@adamemerson 
And we're back to building oke... Thanx

**Comment by adamemerson** [comment]
@tchaikov How is this coming with regard to QA? We need to merge it in if we're going to point people to CLang just to unbreak it.

**Comment by tchaikov** [comment]
@adamemerson i understand. sorry for the latecny. i was rerunning some of the failed test to analyzing the failures.

**Comment by tchaikov** [comment]
- http://pulpito.ceph.com/kchai-2018-01-11_05:03:22-rados-wip-kefu-testing-2018-01-11-1036-distro-basic-smithi/
- http://pulpito.ceph.com/kchai-2018-01-14_09:26:29-rados-wip-kefu-testing-2018-01-11-1036-distro-basic-mira/

failed tests are tracked by 

- http://tracker.ceph.com/issues/20236
- http://tracker.ceph.com/issues/22527
- http://tracker.ceph.com/issues/22668

**Comment by adamemerson** [comment]
@tchaikov Thank you! And thank you for doing a good job tracking all the test failures and opening bugs for them.

**Pull request merged**
