### PR TITLE
tests: allow docker-test.sh to run under root

### PR DESCRIPTION
**Pull request by dachary**

### CODE REVIEW

**Comment by smithfarm** [comment]
@dachary: The machine I was testing this on suddenly went AWOL (Absent With Out Leave - a military acronym). Will keep you posted.

**Comment by dachary** [comment]
@smithfarm ack, no rush ;-)

**Comment by dachary** [comment]
@smithfarm ping ?

**Comment by smithfarm** [comment]
@dachary: http://tracker.ceph.com/issues/13355 updated.

**Comment by dachary** [comment]
@smithfarm updated the documentation: it was indeed misleading.

**Comment by smithfarm** [comment]
LGTM

**Pull request merged**
