### PR TITLE
mimic: mgr/dashboard: fix lint error caused by codelyzer update

### PR DESCRIPTION
**Pull request by tspmelo**
fixes: https://tracker.ceph.com/issues/24663

Signed-off-by: Tiago Melo <tmelo@suse.com>
(cherry picked from commit 4e7f4cbd3fa1d89420a3521888ca7583fd7284fb)

### CODE REVIEW

**Comment by tspmelo** [comment]
Should I also include #22712 in this PR? or create another backport after it has been merged?

**Comment by tspmelo** [comment]
Updated the commit message with the link to the issue.

**Comment by votdev** [comment]
jenkins retest this please

**Comment by LenzGr** [comment]
retest this please

**Comment by smithfarm** [comment]
@tspmelo Thanks for the backport. Over the years I have found myself in the unfortunate position of being the one who posts pedantic comments to PRs regarding backporting processes and workflows.

That said, you did almost everything right on this backport! You cherry-picked a commit from master using `git cherry-pick -x` and you opened a backport tracker issue.

Just a small nit. When running `git cherry-pick -x` please do not change the commit message at all, except to append a "Conflicts" section at the bottom, and that only if there were conflicts you had to resolve manually.

The cherry-picking process is described in detail here [1] but you probably don't need to study it ;-)

[1] http://tracker.ceph.com/projects/ceph-releases/wiki/HOWTO_backport_commits

**Comment by tspmelo** [comment]
@smithfarm thanks for the info.

**Pull request merged**
