### PR TITLE
hammer: mon: Enable Pg_prime By Default

### PR DESCRIPTION
**Pull request by rldleblanc**
http://tracker.ceph.com/issues/14948

The pg_temp mapping helps reduce the memory of an OSD when it is restarted.

Signed-off-by: Robert LeBlanc <robert.leblanc@endurance.com>

### CODE REVIEW

**Comment by dachary** [comment]
@rldleblanc do you confirm that there was no conflict resolution on any of the commits in this pull request ?

**Comment by rldleblanc** [comment]
Yes, it was a clean cherry-pick with no conflicts.

**Comment by dachary** [comment]
@rldleblanc very cool. I created issues to track the backport (administrative sugar, nothing important really). It will be part of the next integration branch.

**Comment by dachary** [comment]
@liewegas does this backport look good to merge ? It passed the hammer upgrade suite ( http://tracker.ceph.com/issues/14692#note-52 ) and the rados suite http://tracker.ceph.com/issues/14692#note-51).

**Comment by liewegas** [comment]
We should discuss this in standup before backporting.

**Comment by liewegas** [comment]
After some discussion we've decide this shouldn't be backported to hammer.  At least not yet.

**Pull request closed without merging**
