### PR TITLE
os/bluefs: assert for file not existing. #19086

### PR DESCRIPTION
**Pull request by JiYou**
Fixes: http://tracker.ceph.com/issues/19086

Signed-off-by: You Ji <youji@ebay.com>

### CODE REVIEW

**Comment by shinobu-x** [comment]
Have you checked what the Callers of this method actually do before calling it?

**Comment by liewegas** [comment]
It's fine for path to refer to the block device directly and not be a symlink.  I'm not sure I understand what this is trying to fix...

**Comment by shinobu-x** [comment]
@JiYou Please describe problem description in your PR message.
And also what would be fixed with this PR.

**Comment by xiaoxichen** [comment]
It doesnt looks right to me. If direct path like  "/dev/sdb" is given, as it is NOT a link , readlink will return EINVAL, assert on this case is clearly wrong.

**Comment by JiYou** [comment]
@xiaoxichen you're right after adding more testing code for it.

**Pull request closed without merging**
