### PR TITLE
mds: optimize purge queue expire pos update

### PR DESCRIPTION
**Pull request by ukernel**
Fixes: http://tracker.ceph.com/issues/23755
Signed-off-by: "Yan, Zheng" <zyan@redhat.com>

### CODE REVIEW

**Comment by batrick** [comment]
Two test failures that look to be caused by this PR:

http://pulpito.ceph.com/pdonnell-2018-04-17_23:06:40-kcephfs-wip-pdonnell-testing-20180417.214135-testing-basic-smithi/2410138/

http://pulpito.ceph.com/pdonnell-2018-04-17_23:06:40-kcephfs-wip-pdonnell-testing-20180417.214135-testing-basic-smithi/2410166/

**Comment by ukernel** [comment]
2018-04-18T15:23:20.752 INFO:tasks.workunit.client.0.smithi097.stderr:+ cephfs-journal-tool event get --type=UPDATE --path=/ --inode=0 --frag=0x100 summary

2018-04-18T15:23:20.809 INFO:tasks.workunit.client.0.smithi097.stderr:Error (2018-04-18 15:23:20.807 7f517ffb3b80 -1 Invalid inode '0x100': The option value '0x100' contains invalid digits

does not seem to be related to this PR

**Comment by ukernel** [comment]
the bug that caused failure was introduced by
https://github.com/ceph/ceph/pull/19117/commits/143c776ba30f42df85f2d83184f179fee2104063

**Comment by batrick** [comment]
Thanks for tracking that down @ukernel .

**Pull request merged**
