### PR TITLE
cli: retry when the mon is not configured

### PR DESCRIPTION
**Pull request by dachary**
The mon may return on error if a command is sent to it while it is
still in configuring state.

Fixes: http://tracker.ceph.com/issues/16477

Signed-off-by: Loic Dachary <loic@dachary.org>

### CODE REVIEW

**Comment by smithfarm** [comment]
@dachary Does this break "make check"? The failures look Python-related.

**Comment by dachary** [comment]
yeah, I'm on it :-)

**Comment by dachary** [comment]
<pre>
kill_daemoexit_code=0
/home/jenkins-build/build/workspace/ceph-pull-requests/qa/workunits/ceph-helpers.sh:180: kill_daemobreak
/home/jenkins-build/build/workspace/ceph-pull-requests/qa/workunits/ceph-helpers.sh:185: kill_daemoreturn 0
/home/jenkins-build/build/workspace/ceph-pull-requests/qa/workunits/ceph-helpers.sh:217: test_kill_ceph --connect-timeout 60 status
2016-09-16 07:33:08.474956 7f6870d4a700  0 monclient(hunting): authenticate timed out after 300
2016-09-16 07:33:08.474990 7f6870d4a700  0 librados: client.admin authentication error (110) Connection timed out


99% tests passed, 1 tests failed out of 148

Total Test time (real) = 3600.05 sec

The following tests FAILED:
	  1 - test-ceph-helpers.sh (Timeout)
Errors while running CTest
Build step 'Execute shell' marked build as failure
[PostBuildScript] - Execution post build scripts.
[ceph-pull-requests] $ /bin/sh -xe /tmp/hudson2372350190255667354.sh
</pre>

Not the same error but occurs in the same area. Jenkins test this please, want to make sure it always happens.

**Comment by dachary** [comment]
test this please (previous run was successfull, trying again to assert it consistently succeeds)

**Pull request merged**
