### PR TITLE
reef: qa: fix incorrectly using the wait_for_health() helper

### PR DESCRIPTION
**Pull request by lxbsz**
backport tracker: https://tracker.ceph.com/issues/63339

---

backport of https://github.com/ceph/ceph/pull/49844 and https://github.com/ceph/ceph/pull/49766
parent tracker: https://tracker.ceph.com/issues/57985

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by dparmar18** [comment]
Reef is still fresh, I think we should keep this param and maybe backport https://github.com/ceph/ceph/pull/49844 which introduced this new param? What do you think?

**Comment by lxbsz** [comment]
> Reef is still fresh, I think we should keep this param and maybe backport #49844 which introduced this new param? What do you think?

Yeah, this is also okay to me.

**Comment by vshankar** [comment]
@lxbsz Shouldn't we add all 3 commits from https://github.com/ceph/ceph/pull/50785/commits

**Comment by lxbsz** [comment]
> @lxbsz Shouldn't we add all 3 commits from https://github.com/ceph/ceph/pull/50785/commits

Okay, I just referred https://github.com/ceph/ceph/pull/49844 only. Missed https://github.com/ceph/ceph/pull/49766.

I will update it.

**Comment by vshankar** [comment]
> > @lxbsz Shouldn't we add all 3 commits from https://github.com/ceph/ceph/pull/50785/commits
> 
> Okay, I just referred #49844 only. Missed #49766.
> 
> I will update it.

The qa changes would have been fine if the backport to other release wasn't done.

**Comment by vshankar** [comment]
@lxbsz Could you update the Fixes tag to the reef backport for https://tracker.ceph.com/issues/57985 ?

**Comment by lxbsz** [comment]
> @lxbsz Could you update the Fixes tag to the reef backport for https://tracker.ceph.com/issues/57985 ?

Done, please check.

**Review by vshankar — APPROVED** [review]

**Pull request merged**
