### PR TITLE
mon: fix 'sortbitwise' warning on jewel

### PR DESCRIPTION
**Pull request by liewegas**
Backports from master.

### CODE REVIEW

**Comment by smithfarm** [comment]
@theanalyst LGTM - we can merge this after it passes a rados suite.

**Comment by theanalyst** [comment]
rados run http://pulpito.ceph.com/abhi-2017-05-22_19:04:05-rados-wip-jewel-backports-mon-sortbitwise-distro-basic-smithi/

details at http://tracker.ceph.com/issues/19538#note-59

**Comment by theanalyst** [comment]
@liewegas @jdurgin the 2 failures seem to occur even after a 3rd retry, is this something known?

**Comment by liewegas** [comment]
they're fine.  both failed with
<pre>
2017-05-24T00:58:25.481 DEBUG:teuthology.misc:Ceph health: HEALTH_WARN no legacy OSD present but 'sortbitwise' flag is not set
2017-05-24T00:58:32.482 INFO:teuthology.orchestra.run.smithi180:Running: 'adjust-ulimits ceph-coverage /home/ubuntu/cephtest/archive/coverage ceph --cluster ceph health'
2017-05-24T00:58:32.620 INFO:teuthology.misc.health.smithi180.stdout:HEALTH_WARN no legacy OSD present but 'sortbitwise' flag is not set
2017-05-24T00:58:32.620 DEBUG:teuthology.misc:Ceph health: HEALTH_WARN no legacy OSD present but 'sortbitwise' flag is not set
2017-05-24T00:58:39.621 INFO:teuthology.orchestra.run.smithi180:Running: 'adjust-ulimits ceph-coverage /home/ubuntu/cephtest/archive/coverage ceph --cluster ceph health'
2017-05-24T00:58:39.764 INFO:teuthology.misc.health.smithi180.stdout:HEALTH_WARN no legacy OSD present but 'sortbitwise' flag is not set
2017-05-24T00:58:39.764 DEBUG:teuthology.misc:Ceph health: HEALTH_WARN no legacy OSD present but 'sortbitwise' flag is not set
2017-05-24T00:58:46.766 INFO:teuthology.orchestra.run.smithi180:Running: 'adjust-ulimits ceph-coverage /home/ubuntu/cephtest/archive/coverage ceph --cluster ceph health'
</pre>
the tests just need to be modified to 'ceph osd set sortbitwise' during/after the upgrade.

**Comment by liewegas** [comment]
added a patch to do that!

**Comment by smithfarm** [comment]
Jenkins re-test this please

**Pull request merged**
