### PR TITLE
seastar: pick up change adding ioctl and fcntl support

### PR DESCRIPTION
**Pull request by tchaikov**
prepare for the better support of ZNS.

Signed-off-by: Kefu Chai <kchai@redhat.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by tchaikov** [comment]
the upstream seastar does not build fix pending on review at https://groups.google.com/g/seastar-dev/c/3HHrinjOH88/m/wD-C7iNYBQAJ

**Comment by tchaikov** [comment]
```
/tmp/typ-mqNvUJzTq /tmp/typ-nzMe3lWw1 differ: char 166, line 1
**** rgw_log_entry test 2 binary reencode check failed ****
   ceph-dencoder type rgw_log_entry select_test 2 encode export /tmp/typ-mqNvUJzTq
   ceph-dencoder type rgw_log_entry select_test 2 encode decode encode export /tmp/typ-nzMe3lWw1
   cmp /tmp/typ-mqNvUJzTq /tmp/typ-nzMe3lWw1
```

**Comment by tchaikov** [comment]
jenkins test make check

**Review by rzarzynski — APPROVED** [review]

**Comment by rzarzynski** [comment]
Oops, looks `ceph/seastar.git` missed the new commit:

```
[rzarzynski@o06 seastar]$ git fetch origin
[rzarzynski@o06 seastar]$ git checkout 4559a985d2c2a851d0567a0bb08e91d965530087
fatal: reference is not a tree: 4559a985d2c2a851d0567a0bb08e91d965530087
```

**Comment by tchaikov** [comment]
> Oops, it looks `ceph/seastar.git` missed the new commit:
> 
> ```
> [rzarzynski@o06 seastar]$ git fetch origin
> [rzarzynski@o06 seastar]$ git checkout 4559a985d2c2a851d0567a0bb08e91d965530087
> fatal: reference is not a tree: 4559a985d2c2a851d0567a0bb08e91d965530087
> ```
> 
> As we're running with vanilla seastar, the alternative is to change the submobule's URL to point directly to the upstream.

should be sync'ed now.

**Comment by tchaikov** [comment]
jenkins test make check

**Pull request merged**
