### PR TITLE
pybind/mgr: fix format for rbd-mirror prometheus metrics

### PR DESCRIPTION
**Pull request by trociny**
Fixes: https://tracker.ceph.com/issues/39977
Signed-off-by: Mykola Golub <mgolub@suse.com>

- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by tchaikov** [comment]
retest this please.

**Comment by sebastian-philipp** [comment]
is there any test covering this fix?

**Comment by trociny** [comment]
> is there any test covering this fix?

No, there is not. It seems we don't have any tests for prometheus counters, where I could add tests for this specific case.

**Comment by dillaman** [comment]
retest this please

**Comment by b-ranto** [comment]
I have a couple of comments/suggestions, here:
 - the actual reason why these metrics cannot be imported by the prometheus server is in the `/` sign that the rbd-mirror metrics contain, we should definitely fix the prometheus module to sanitize this character when dealing with metric names; we already have a function for this in `Metric.str_expfmt.promethize`
 - the next question is if we want to change the perf counter name and move `pool` and `image` to the labels for the counters; this could cause some incosistencies between the various ways you can interact with perf counters
- if we are only going to change this for the `prometheus` module, the `Metric.str_expfmt` method that does the final formatting might be a better place for the patch as that is the place where we deal with the specifics of the prometheus syntax

**Comment by trociny** [comment]
>     * the actual reason why these metrics cannot be imported by the prometheus server is in the `/` sign that the rbd-mirror metrics contain, we should definitely fix the prometheus module to sanitize this character when dealing with metric names; we already have a function for this in `Metric.str_expfmt.promethize`

Added a commit for this. Thanks.

>     * the next question is if we want to change the perf counter name and move `pool` and `image` to the labels for the counters; this could cause some incosistencies between the various ways you can interact with perf counters

With labes you can build nice queries in prometheus. The fact that all this info is packed in a perf counter name is rather a limitation of the perfcounters, I would rather we do not extend it to prometheus counters, just for the sake of consistency in counters names, which is already not consistent (due to `promethize`) and not clear how it is useful.

>     * if we are only going to change this for the `prometheus` module, the `Metric.str_expfmt` method that does the final formatting might be a better place for the patch as that is the place where we deal with the specifics of the prometheus syntax

I think potentially other modules will need the similar thing. For example, the influx module, which uses tags. Currently the influx module does not support rbd-mirror counters. It is rather easy to add though and I hope someone will do this in future. I did not do this just because I don't have any experience with influx and would not be able to test it.

**Comment by b-ranto** [comment]
> I think potentially other modules will need the similar thing. For example, the influx module, which uses tags. Currently the influx module does not support rbd-mirror counters. It is rather easy to add though and I hope someone will do this in future. I did not do this just because I don't have any experience with influx and would not be able to test it.

Yeah, I was not necessarily talking about the `_perfpath_to_path_labels` function. That can stay where it is right now for use by other modules. I was talking more about the use of that function in `Metric.str_expfmt` instead of the `collect` method. You could just call the function on line 145 (calling it first and then the `promethize` function) and then you could just modify the `labelvalues`/`labelnames` in the `for`starting on line 154. It does feel more robust to me having handled this in a single place, not multiple places.

**Comment by trociny** [comment]
@b-ranto I am not very happy with moving `_perfpath_to_path_labels` into `Metric.str_expfmt`. I see your reasons, but in my opinion it would obfuscate the code. When I call `Metric(..., name, ..., labels)` it would be counter intuitive to me that the metric eventually may have more labels than I specified, depending on the name.

But if you insisted...

**Comment by b-ranto** [comment]
@trociny We already do a couple of transformations there that can make things counter-intuitive like changing the metric names. Basically, the function was designed to deal with the specifics of representing the internal objects as lines in the prometheus exporter output but let's see what others think about it.

@jan--f Any opinion on the matter?

Just to be clear: I am not suggesting we should move the `_perfpath_to_path_labels` function there. All I am saying is that we should call it from there. It can still be defined in the `mgr_module.py` file.

**Comment by trociny** [comment]
Updated according to Jason's suggestion.

**Comment by liewegas** [comment]
retest this please

**Pull request merged**
