### PR TITLE
mgr/orch: fix `orch apply iscsi`

### PR DESCRIPTION
**Pull request by mgfritch**
Adds missing orch cli:
`$ ceph orch apply iscsi --pool <pool>`

Also fixes invocation error during apply:
```
Error ENOENT: ServiceSpec: __init__() missing 1 required positional argument: 'service_id
```

Fixes: https://tracker.ceph.com/issues/45249
Signed-off-by: Michael Fritch <mfritch@suse.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by bk201** [comment]
- `ceph orch apply -i <spec>` works.
- `ceph orch apply iscsi` doesn't' support `spec` parameters. (Related: https://github.com/ceph/ceph/pull/34722)
- This PR removes the `fqdn_enabled` parameter: https://github.com/ceph/ceph/pull/34723/

One of these PRs need to be merged first for others to rebase.

**Comment by mgfritch** [comment]
> * `ceph orch apply -i <spec>` works.
:+1:


> * `ceph orch apply iscsi` doesn't' support `spec` parameters. (Related: #34722)

But, this mostly equivalent to the above? Do we want to support both variations (Related: #34843)?
```
$ ceph orch apply iscsi <pool> -i <spec>
--and--
$ ceph orch apply -i <spec>
```



> * This PR removes the `fqdn_enabled` parameter: #34723
> 
Let's merge this one first and rebase the others.

**Comment by mgfritch** [comment]
rebased and updated to remove the `fqdn_enabled` parameter #34723

**Comment by mgfritch** [comment]
http://pulpito.ceph.com/mgfritch-2020-05-05_02:07:06-rados-wip-mgfritch-testing-2020-05-04-1622-distro-basic-smithi/

**Comment by sebastian-philipp** [comment]
http://pulpito.ceph.com/swagner-2020-05-04_13:28:01-rados-wip-swagner-testing-2020-05-04-1211-distro-basic-smithi/

https://tracker.ceph.com/issues/45335

**Pull request merged**
