### PR TITLE
nautilus: mgr/dashboard: Disabling the form inputs for the read_only modals

### PR DESCRIPTION
**Pull request by nizamial09-zz**
backport tracker: https://tracker.ceph.com/issues/47538

## Checklist
- [x] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by smithfarm** [comment]
@nizamial09 When I tried this cherry pick, I got a conflict in 

    src/pybind/mgr/dashboard/frontend/src/app/shared/directives/directives.module.ts

Was that the case for you as well?

**Comment by smithfarm** [comment]
I noticed the octopus backport of this fix also has a conflict.

Would it make sense to backport to octopus, first, and from there to nautilus?

**Comment by nizamial09** [comment]
> I noticed the octopus backport of this fix also has a conflict.
> 
> Would it make sense to backport to octopus, first, and from there to nautilus?

The result would be entirely the same I guess. I'll update the conflicts section in the commit message and push it in.

**Comment by nizamial09** [comment]
@smithfarm Updated the commit message. PTAL, thanks

**Comment by smithfarm** [comment]
@nizamial09 Thanks!

**Review by alfonsomthd — APPROVED** [review]

**Pull request merged**
