### PR TITLE
osd/scrub: remove detection & handling of reservation timeouts from the code

### PR DESCRIPTION
**Pull request by ronen-fr**
as no timeout can be set for reserver-based (queued) reservation requests.
    
Fixes: https://tracker.ceph.com/issues/65044

### CODE REVIEW

**Review by athanatos — APPROVED** [review]

**Comment by yuriw** [comment]
@ronen-fr pls rebase

**Comment by ronen-fr** [comment]
> @ronen-fr pls rebase

(Back from PTO... )
Done!

**Comment by ronen-fr** [comment]
jenkins retest this please

**Comment by ronen-fr** [comment]
I will be merging based on my tests and the Teuthology tests performed on the backport

**Comment by ronen-fr** [comment]
jenkins test windows

**Comment by ronen-fr** [comment]
jenkins test windows

**Comment by ronen-fr** [comment]
jenkins test api

**Comment by yuriw** [comment]
This PR is under test in [https://tracker.ceph.com/issues/65797](https://tracker.ceph.com/issues/65797).

**Pull request merged**
