### PR TITLE
quincy: mgr/vol: handle case where clone index entry goes missing

### PR DESCRIPTION
**Pull request by rishabh-d-dave**
backport tracker: https://tracker.ceph.com/issues/66929

---

backport of https://github.com/ceph/ceph/pull/58101
parent tracker: https://tracker.ceph.com/issues/66560

this backport was staged using ceph-backport.sh version 16.0.0.6848
find the latest version at https://github.com/ceph/ceph/blob/main/src/script/ceph-backport.sh

### CODE REVIEW

**Comment by rishabh-d-dave** [comment]
jenkins test make check

**Comment by rishabh-d-dave** [comment]
jenkins test api

**Comment by rishabh-d-dave** [comment]
jenkins test make check

**Comment by rishabh-d-dave** [comment]
@lxbsz IMO this is ready for QA run

**Comment by lxbsz** [comment]
This PR is under test in [https://tracker.ceph.com/issues/67315](https://tracker.ceph.com/issues/67315).

**Review by rishabh-d-dave — COMMENTED** [review]
QA run was successful - https://tracker.ceph.com/projects/cephfs/wiki/Quincy#19-aug-2024

**Comment by rishabh-d-dave** [comment]
@lxbz Please merge this PR, I can't merge it since this PR is from me.

**Review by lxbsz — APPROVED** [review]

**Pull request merged**
