### PR TITLE
DNM: osd: Transaction::op_bl is not safe to use directly in encode

### PR DESCRIPTION
**Pull request by yuandong1222**
the op_bl may changes during append operation,
so it is not safe to use directly in encode.
we use additional bufferlist & rebuild action to avoid this problem

Change-Id: Ic9fa85a963d49dd4fee5b8f5f704a6690f1c1a52
Signed-off-by: Dong Yuan <yuandong1222@gmail.com>

### CODE REVIEW

**Comment by yuandong1222** [comment]
Updated

**Comment by yuandong1222** [comment]
Call robot

**Comment by dachary** [comment]
@yuandong1222 the bot will run automatically each time you push a new version of your code ;-)

**Comment by yuandong1222** [comment]
That 's great!

Thanks:-)

On 20 January 2015 at 16:17, Loic Dachary <notifications@github.com> wrote:

> @yuandong1222 <https://github.com/yuandong1222> the bot will run
> automatically each time you push a new version of your code ;-)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ceph/ceph/pull/3413#issuecomment-70618792>.
>



-- 
Dong Yuan
Email:yuandong1222@gmail.com

**Comment by liewegas** [comment]
this looks right to me

**Comment by athanatos** [comment]
Don't create pull requests based on or targeted at wip-sam-testing.  I force-push that branch several times a day.

**Comment by yuandong1222** [comment]
I see.

While I can't find a appropriate branch to fix these bugs, who can tell me?

On 21 January 2015 at 05:17, Samuel Just <notifications@github.com> wrote:

> Don't create pull requests based on or targeted at wip-sam-testing. I
> force-push that branch several times a day.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ceph/ceph/pull/3413#issuecomment-70735231>.
>



-- 
Dong Yuan
Email:yuandong1222@gmail.com

**Comment by liewegas** [comment]
looks like a bunch of other commits got mixed in here?

in any case, with just the two original patches, i'm seeing a rados api test failure:

<pre>
[ RUN      ] LibRadosMisc.CloneRange
test/librados/misc.cc:492: Failure
Value of: rados_read(ioctx, "dst", buf2, sizeof(buf2), 0)
  Actual: 0
Expected: (int)sizeof(buf2)
Which is: 128
[  FAILED  ] LibRadosMisc.CloneRange (61 ms)
</pre>
(ceph_test_rados_api_misc)

**Comment by yuandong1222** [comment]
I am sorry I don't what you are talking about.

What branch do you use? And is these a make check result?

I tested the patches on wip-sam-testing branch and make check passed. Maybe
I am used the wrong branch?

On 22 January 2015 at 05:50, Sage Weil <notifications@github.com> wrote:

> looks like a bunch of other commits got mixed in here?
>
> in any case, with just the two original patches, i'm seeing a rados api
> test failure:
>
> [ RUN      ] LibRadosMisc.CloneRange
> test/librados/misc.cc:492: Failure
> Value of: rados_read(ioctx, "dst", buf2, sizeof(buf2), 0)
>   Actual: 0
> Expected: (int)sizeof(buf2)
> Which is: 128
> [  FAILED  ] LibRadosMisc.CloneRange (61 ms)
>
> (ceph_test_rados_api_misc)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ceph/ceph/pull/3413#issuecomment-70928817>.
>



-- 
Dong Yuan
Email:yuandong1222@gmail.com

**Comment by tchaikov** [comment]
@yuandong1222 you might want to apply your patches to the master branch. and it would be better if  your PR only involves your own changes: bd5e305 and 9ae2986, but not involves the one(s) from sam. i applied your patches against 6f44f7a, and reran the `ceph_test_rados_api_misc` test mentioned by sage, 

```
$ ./ceph_test_rados_api_misc --gtest_filter='*CloneRange*'
Note: Google Test filter = *CloneRange*
[==========] Running 2 tests from 2 test cases.
[----------] Global test environment set-up.
[----------] 1 test from LibRadosMisc
[ RUN      ] LibRadosMisc.CloneRange
test/librados/misc.cc:494: Failure
Value of: rados_read(ioctx, "dst", buf2, sizeof(buf2), 0)
  Actual: 0
Expected: (int)sizeof(buf2)
Which is: 128
[  FAILED  ] LibRadosMisc.CloneRange (3555 ms)
[----------] 1 test from LibRadosMisc (3555 ms total)

[----------] 1 test from LibRadosMiscPP
[ RUN      ] LibRadosMiscPP.CloneRangePP
test/librados/misc.cc:482: Failure
Value of: (size_t)ioctx.read("bar", bl2, sizeof(buf), 0)
  Actual: 0
Expected: sizeof(buf)
Which is: 64
[  FAILED  ] LibRadosMiscPP.CloneRangePP (3322 ms)
[----------] 1 test from LibRadosMiscPP (3322 ms total)

[----------] Global test environment tear-down
[==========] 2 tests from 2 test cases ran. (9439 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 2 tests, listed below:
[  FAILED  ] LibRadosMisc.CloneRange
[  FAILED  ] LibRadosMiscPP.CloneRangePP
```

**Comment by yuandong1222** [comment]
I am sorry, but these two patches is based on my last RP
https://github.com/ceph/ceph/pull/2991 which is closed and Sage said he
will manually merge. This is also metioned by
https://github.com/ceph/ceph/pull/3188.

Should I push the whole RP again?

On 22 January 2015 at 10:49, Kefu Chai <notifications@github.com> wrote:

> @yuandong1222 <https://github.com/yuandong1222> you might want to apply
> your patches to the master branch. and it would be better if your PR only
> involves your own changes: bd5e305
> <https://github.com/ceph/ceph/commit/bd5e30596fe8c3617d7ec2a45b82299b8d44ee8c>
> and 9ae2986
> <https://github.com/ceph/ceph/commit/9ae2986fbfefb628971b0b81db341bbd62b33a03>,
> but not involves the one(s) from sam. i applied your patches against
> 6f44f7a
> <https://github.com/ceph/ceph/commit/6f44f7a0a9847e419ce2783164633efa71218380>,
> and reran the ceph_test_rados_api_misc test mentioned by sage,
>
> $ ./ceph_test_rados_api_misc --gtest_filter='*CloneRange*'
> Note: Google Test filter = *CloneRange*
> [==========] Running 2 tests from 2 test cases.
> [----------] Global test environment set-up.
> [----------] 1 test from LibRadosMisc
> [ RUN      ] LibRadosMisc.CloneRange
> test/librados/misc.cc:494: Failure
> Value of: rados_read(ioctx, "dst", buf2, sizeof(buf2), 0)
>   Actual: 0
> Expected: (int)sizeof(buf2)
> Which is: 128
> [  FAILED  ] LibRadosMisc.CloneRange (3555 ms)
> [----------] 1 test from LibRadosMisc (3555 ms total)
>
> [----------] 1 test from LibRadosMiscPP
> [ RUN      ] LibRadosMiscPP.CloneRangePP
> test/librados/misc.cc:482: Failure
> Value of: (size_t)ioctx.read("bar", bl2, sizeof(buf), 0)
>   Actual: 0
> Expected: sizeof(buf)
> Which is: 64
> [  FAILED  ] LibRadosMiscPP.CloneRangePP (3322 ms)
> [----------] 1 test from LibRadosMiscPP (3322 ms total)
>
> [----------] Global test environment tear-down
> [==========] 2 tests from 2 test cases ran. (9439 ms total)
> [  PASSED  ] 0 tests.
> [  FAILED  ] 2 tests, listed below:
> [  FAILED  ] LibRadosMisc.CloneRange
> [  FAILED  ] LibRadosMiscPP.CloneRangePP
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ceph/ceph/pull/3413#issuecomment-70963476>.
>



-- 
Dong Yuan
Email:yuandong1222@gmail.com

**Comment by yuandong1222** [comment]
Oh, the PR has already merged to master, I missed that.

I will repush my patches to the master.

Thanks.

On 22 January 2015 at 11:54, Dong Yuan <yuandong1222@gmail.com> wrote:

> I am sorry, but these two patches is based on my last RP
> https://github.com/ceph/ceph/pull/2991 which is closed and Sage said he
> will manually merge. This is also metioned by
> https://github.com/ceph/ceph/pull/3188.
>
> Should I push the whole RP again?
>
> On 22 January 2015 at 10:49, Kefu Chai <notifications@github.com> wrote:
>
>> @yuandong1222 <https://github.com/yuandong1222> you might want to apply
>> your patches to the master branch. and it would be better if your PR only
>> involves your own changes: bd5e305
>> <https://github.com/ceph/ceph/commit/bd5e30596fe8c3617d7ec2a45b82299b8d44ee8c>
>> and 9ae2986
>> <https://github.com/ceph/ceph/commit/9ae2986fbfefb628971b0b81db341bbd62b33a03>,
>> but not involves the one(s) from sam. i applied your patches against
>> 6f44f7a
>> <https://github.com/ceph/ceph/commit/6f44f7a0a9847e419ce2783164633efa71218380>,
>> and reran the ceph_test_rados_api_misc test mentioned by sage,
>>
>> $ ./ceph_test_rados_api_misc --gtest_filter='*CloneRange*'
>> Note: Google Test filter = *CloneRange*
>> [==========] Running 2 tests from 2 test cases.
>> [----------] Global test environment set-up.
>> [----------] 1 test from LibRadosMisc
>> [ RUN      ] LibRadosMisc.CloneRange
>> test/librados/misc.cc:494: Failure
>> Value of: rados_read(ioctx, "dst", buf2, sizeof(buf2), 0)
>>   Actual: 0
>> Expected: (int)sizeof(buf2)
>> Which is: 128
>> [  FAILED  ] LibRadosMisc.CloneRange (3555 ms)
>> [----------] 1 test from LibRadosMisc (3555 ms total)
>>
>> [----------] 1 test from LibRadosMiscPP
>> [ RUN      ] LibRadosMiscPP.CloneRangePP
>> test/librados/misc.cc:482: Failure
>> Value of: (size_t)ioctx.read("bar", bl2, sizeof(buf), 0)
>>   Actual: 0
>> Expected: sizeof(buf)
>> Which is: 64
>> [  FAILED  ] LibRadosMiscPP.CloneRangePP (3322 ms)
>> [----------] 1 test from LibRadosMiscPP (3322 ms total)
>>
>> [----------] Global test environment tear-down
>> [==========] 2 tests from 2 test cases ran. (9439 ms total)
>> [  PASSED  ] 0 tests.
>> [  FAILED  ] 2 tests, listed below:
>> [  FAILED  ] LibRadosMisc.CloneRange
>> [  FAILED  ] LibRadosMiscPP.CloneRangePP
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/ceph/ceph/pull/3413#issuecomment-70963476>.
>>
>
>
>
> --
> Dong Yuan
> Email:yuandong1222@gmail.com
>



-- 
Dong Yuan
Email:yuandong1222@gmail.com

**Comment by yuandong1222** [comment]
I will repush to master.

**Comment by tchaikov** [comment]
@yuandong1222 did you close this issue by accident?

**Comment by yuandong1222** [comment]
I will push a new request to master later.

On Thursday, 22 January 2015, Kefu Chai <notifications@github.com> wrote:

> @yuandong1222 <https://github.com/yuandong1222> did you close this issue
> by accident?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ceph/ceph/pull/3413#issuecomment-70970406>.
>


-- 
Dong Yuan
Email:yuandong1222@gmail.com

**Comment by tchaikov** [comment]
@yuandong1222 as you might know, you can also reuse this pull request by force push to your branch of `yuandong1222:wip-sam-testing-bug-fix` , so we can have the full history of the discussion, and review comments, etc.

**Comment by yuandong1222** [comment]
I am sorry, and I will follow the rule in the future.

Thanks for your notice. :-)

On 22 January 2015 at 16:17, Kefu Chai <notifications@github.com> wrote:

> @yuandong1222 <https://github.com/yuandong1222> as you might know, you
> can also reuse this pull request by force push to your branch of
> yuandong1222:wip-sam-testing-bug-fix , so we can have the full history of
> the discussion, and review comments, etc.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ceph/ceph/pull/3413#issuecomment-70985511>.
>



-- 
Dong Yuan
Email:yuandong1222@gmail.com

**Pull request closed without merging**
