### PR TITLE
Cleanup:  call ceph_clock_now added clock_offset defined in ceph.conf

### PR DESCRIPTION
**Pull request by XinzeChi**
@yuyuyu101 , @dachary, Do you think it is a bug? we should add the clock_offset in ceph.conf.

I grep all the ceph code, there are so many place use ceph_clock_now(NULL).

Signed-off-by: Xinze Chi <xmdxcxz@gmail.com>

### CODE REVIEW

**Comment by XinzeChi** [comment]
Such as rgw, client, rados, monitor only use ceph_clock_now(NULL).

**Comment by dachary** [comment]
I did not know about clock_offset. Is it used for debugging or somewhere else ? I feel that the code should be left untouched because it may change the behavior of existing daemons in unexpected ways if the ceph.conf turns out to have a clock_offset. But I'm ignorant of the rationale of this flag therefore it's best to ask someone else ;-)

**Comment by XinzeChi** [comment]
@liewages, please give some advice about this patch. Thanks.

**Comment by liewegas** [comment]
i have never used (and have never seen used) the clock_offset field.  i think we either need to audit all calls to make sure they pass cct (is this patch comprehensive?) or we just remove the option (which i'm not sure i fully trust anyway)..

**Comment by XinzeChi** [comment]
@liewegas,  i think all calls used clock_offset or all calls not used clock_offset is ok.  If you make a decision, i will do cleanup.

**Comment by XinzeChi** [comment]
Maybe using the clock_offset is more  reasonaable. Because user may use it doing something we donot know.

**Comment by dachary** [comment]
@XinzeChi it is worth discussing on ceph-devel. I'm closing this pull request for now but please feel free to re-open it if you think differently.

**Pull request closed without merging**
