### PR TITLE
doc/radosgw/admin: the option '--purge-keys' not purge all keys associated to the uid but only purge the key spedified by '--access-key'

### PR DESCRIPTION
**Pull request by weiqiaomiao**
Signed-off-by: weiqiaomiao wei.qiaomiao@zte.com.cn

### CODE REVIEW

**Comment by theanalyst** [comment]
@weiqiaomiao could you also add an example for using purge keys to purge a single key alone?

**Comment by weiqiaomiao** [comment]
@theanalyst  ok, I add it

**Comment by weiqiaomiao** [comment]
retest this please

**Comment by yehudasa** [comment]
@weiqiaomiao  @theanalyst I think that the bug here is that purge_keys is not working as expected.

**Comment by theanalyst** [comment]
@yehudasa @weiqiaomiao agreed

**Comment by weiqiaomiao** [comment]
This bug was fixed in  commit [e7b7e1a](https://github.com/ceph/ceph/commit/e7b7e1afc7a81c3f97976f7442fbdc5118b532b5) ，so in jewel(and later) version there is no need to specify '--purge-data' to clean all keys because of the remove subuser opt will purge all associate keys by default, but the bug is still in hammer(and older) version ,  I think this bug have little effect so we need not to backport it to hammer and we can only add the tips in doc . What do you think?

**Comment by liewegas** [comment]
It's probably safe to drop this now? If not please reopen!

**Pull request closed without merging**
