### PR TITLE
pybind/rados: keep byte representation if decode fails

### PR DESCRIPTION
**Pull request by batrick**
## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [x] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [x] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by phlogistonjohn** [comment]
> Mixing types sucks for the library user but it's better than making iteration impossible.

Agreed. Would it possibly be a better API to add a keyword argument to OmapIterator? Something like `bytes_keys=False`? That way the caller can control what types will be returned and they'll be consistent across an iteraton?

**Comment by batrick** [comment]
> > Mixing types sucks for the library user but it's better than making iteration impossible.
> 
> Agreed. Would it possibly be a better API to add a keyword argument to OmapIterator? Something like `bytes_keys=False`? That way the caller can control what types will be returned and they'll be consistent across an iteraton?

Thanks @phlogistonjohn. I took a slightly different approach. Please take a look.

**Review by vshankar — COMMENTED** [review]
LGTM

**Review by dparmar18 — APPROVED** [review]
LGTM

**Comment by batrick** [comment]
jenkins test make check arm64

**Comment by batrick** [comment]
https://tracker.ceph.com/projects/cephfs/wiki/Main#24-May-2023

**Review by athanatos — APPROVED** [review]
LGTM

**Comment by batrick** [comment]
jenkins test make check arm64

**Comment by phlogistonjohn** [comment]
> > > Mixing types sucks for the library user but it's better than making iteration impossible.
> > 
> > 
> > Agreed. Would it possibly be a better API to add a keyword argument to OmapIterator? Something like `bytes_keys=False`? That way the caller can control what types will be returned and they'll be consistent across an iteraton?
> 
> Thanks @phlogistonjohn. I took a slightly different approach. Please take a look.

Sorry for the slow reply.  Implementation looks good to me.  I'm not well-verssed in this module enough to tell off the top of my head if `__cinit__` was part of the public api. I'm assuming it's not so we should be good supporting existing code.

**Review by phlogistonjohn — APPROVED** [review]

**Comment by ljflores** [comment]
Hey @batrick, I found a related failure:

/a/yuriw-2023-05-30_21:40:46-rados-wip-yuri10-testing-2023-05-30-1244-distro-default-smithi/7291042
/a/yuriw-2023-05-31_16:12:15-rados-wip-yuri10-testing-2023-05-30-1244-distro-default-smithi/7292098
```
2023-05-31T10:08:00.753 INFO:tasks.workunit.client.0.smithi005.stderr:======================================================================
2023-05-31T10:08:00.753 INFO:tasks.workunit.client.0.smithi005.stderr:ERROR: test_rados.TestIoctx.test_get_omap_vals_by_keys
2023-05-31T10:08:00.753 INFO:tasks.workunit.client.0.smithi005.stderr:----------------------------------------------------------------------
2023-05-31T10:08:00.753 INFO:tasks.workunit.client.0.smithi005.stderr:Traceback (most recent call last):
2023-05-31T10:08:00.753 INFO:tasks.workunit.client.0.smithi005.stderr:  File "/usr/lib/python3.6/site-packages/nose/case.py", line 197, in runTest
2023-05-31T10:08:00.753 INFO:tasks.workunit.client.0.smithi005.stderr:    self.test(*self.arg)
2023-05-31T10:08:00.754 INFO:tasks.workunit.client.0.smithi005.stderr:  File "/home/ubuntu/cephtest/clone.client.0/src/test/pybind/test_rados.py", line 546, in test_get_omap_vals_by_keys
2023-05-31T10:08:00.754 INFO:tasks.workunit.client.0.smithi005.stderr:    eq(list(iter), [("3", b"ccc"), ("4", b"\x04\x04\x04\x04"), (b"\xff", b"5")])
2023-05-31T10:08:00.754 INFO:tasks.workunit.client.0.smithi005.stderr:  File "rados.pyx", line 1400, in rados.OmapIterator.__next__
2023-05-31T10:08:00.754 INFO:tasks.workunit.client.0.smithi005.stderr:UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte
```

Trello ref: https://trello.com/c/Zbp7w1yE/1770-wip-yuri10-testing-2023-05-30-1244

**Comment by batrick** [comment]
https://pulpito.ceph.com/pdonnell-2023-06-08_01:57:47-rados:basic-wip-pdonnell-testing-20230607.202642-distro-default-smithi/

**Comment by batrick** [comment]
jenkins test make check

**Comment by batrick** [comment]
@ljflores thanks, I fixed the issue and posted a QA run.

**Comment by ljflores** [comment]
Rados suite review: https://tracker.ceph.com/projects/rados/wiki/MAIN#httpstrellocomcCcKXkHLe1789-wip-yuri3-testing-2023-06-19-1518

**Pull request merged**
