### PR TITLE
workunits/rgw: semicolon terminates perl statements

### PR DESCRIPTION
**Pull request by mattbenjamin**
Fixes a lexical error in one line of code added in
90e9307ab0a52da260bc1ebb50329cd8ff942eb9, removing the dependency
on lsb_release, on 8/16/2021.

Fixes: https://tracker.ceph.com/issues/52613

Signed-off-by: Matt Benjamin <mbenjamin@redhat.com>
(cherry picked from commit 221fdb858be083a981697cdb59c19f0659be3f1d)

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by yuriw** [comment]
@mattbenjamin pls close https://github.com/ceph/ceph/pull/43165

**Comment by yuriw** [comment]
https://pulpito.ceph.com/yuriw-2021-09-14_23:03:47-rgw-wip-yuri5-testing-2021-09-14-1441-pacific-distro-basic-smithi

**Review by yuriw — APPROVED** [review]
@mattbenjamin see aT the test results, I suspect the failures were masked before this fix

let me know if you want to merge it and I will unlock the repo

**Comment by mattbenjamin** [comment]
@yuriw seems like we -must- merge this one, I'm reviewing the other failures in our downstream standup

**Comment by mattbenjamin** [comment]
@cbodley has rulings on the outstanding test failures :)

**Pull request merged**
