### PR TITLE
octopus: Batch backport May (2)

### PR DESCRIPTION
**Pull request by sebastian-philipp**
Backport of #34745, #34658, #34814, #34778, #34703, #34773, #34856, #34898, #34887, #34820, #34891, #34909, #34843, #34903, #34922, #34950, #34932, #34961, #34926, #34938, #34977, #34945, #34888, #35022, #35030, #34944, #34668, #34981, #35013, #35092, #35083, #35084, #35068, #35071, #34900, #35101, #34980, #35125, #35088, #35087, #35114

Note, this PR excludes

* #34436
* #35010

as they are not part of the cephadm codebase

### CODE REVIEW

**Comment by sebastian-philipp** [comment]
http://pulpito.front.sepia.ceph.com:80/swagner-2020-05-27_13:53:08-rados:cephadm-wip-swagner2-testing-2020-05-27-1207-distro-basic-smithi/

**Comment by kshtsk** [comment]
I'm curious what is the benefit of making such long names `sebastian-philipp:octopus-backport-34745-34658-34814-34778-34703-34773-34856-34898-34887-34820-34891-3490`

**Comment by sebastian-philipp** [comment]
> I'm curious what is the benefit of making such long names `sebastian-philipp:octopus-backport-34745-34658-34814-34778-34703-34773-34856-34898-34887-34820-34891-3490`

not really. but 

https://github.com/sebastian-philipp/backport-cephadm-pr/blob/df011e30a6fde37c5074d8de6871af7ee31a0a17/simple-backport-pr.py#L264-L265

was easy to do.

**Comment by sebastian-philipp** [comment]
QA: http://pulpito.ceph.com/swagner-2020-06-02_09:44:23-rados:cephadm-wip-swagner2-testing-2020-06-02-0945-octopus-distro-basic-smithi/

**Comment by gekios** [comment]
Test run looks good apart from one test that seems to have randomly failed to add the ppa repo. 

`Command failed on smithi150 with status 1: "sudo TESTDIR=/home/ubuntu/cephtest bash -c 'sudo add-apt-repository -y ppa:projectatomic/ppa'"`

**Comment by sebastian-philipp** [comment]
success http://pulpito.ceph.com/swagner-2020-06-02_09:44:23-rados:cephadm-wip-swagner2-testing-2020-06-02-0945-octopus-distro-basic-smithi/

**Pull request merged**
