### PR TITLE
jewel: core: two instances of omap_digest mismatch

### PR DESCRIPTION
**Pull request by dzafman**
http://tracker.ceph.com/issues/19404

Fix the code that can corrupt an omap and check and repair existing corruption at start-up
Simplify omap rm_keys() at the expense of omap clone() performance
Add omap rename() which can be used in place of clone() in some cases
Add dump-headers and repair to ceph-osdomap-tool for diagnostics and testing

### CODE REVIEW

**Comment by smithfarm** [comment]
This pased an upgrade/hammer-x suite at http://tracker.ceph.com/issues/19538#note-35 and an upgrade/client-upgrade suite at http://tracker.ceph.com/issues/19538#note-36

Rados suite was scheduled and is still pending.

**Comment by smithfarm** [comment]
Rados run results here: http://pulpito.ceph.com/smithfarm-2017-04-20_08:48:32-rados-wip-jewel-backports-distro-basic-smithi/

Re-running the 4 failed jobs here: http://pulpito.ceph.com:80/smithfarm-2017-04-21_05:45:14-rados-wip-jewel-backports-distro-basic-smithi/

**Comment by smithfarm** [comment]
@dzafman @tchaikov I analyzed the two failures in detail; they are:

* http://tracker.ceph.com/issues/16239 (known bug)
* http://tracker.ceph.com/issues/19737 (new bug)

They already happened in the previous rados run which did not include this PR, so they are unrelated to this PR. Still, I'd be grateful if you helped me to fix them.

**Comment by smithfarm** [comment]
This conflicts with #14701 - I suggest we get that one in first, and then rebase this one.

**Comment by dzafman** [comment]
@smithfarm Had #14701 already merged then bce7e20aa0dc04f2cdd0cc7fb6ad182625837b88 wouldn't have conflicted.  To try and avoid unfixing a conflict manually, we should try out removing bce7e20aa0dc04f2cdd0cc7fb6ad182625837b88 and then cherry-pick 5fb2b2d13953979e5da9f571ab8c4b0b510b8368 again, first.

**Comment by dzafman** [comment]
So actually we should try this to see if it all falls into place:

1. merge #14701 
2. Remove bce7e20aa0dc04f2cdd0cc7fb6ad182625837b88
3. rebase branch ( maybe no conflicts)
4. cherry-pick 5fb2b2d13953979e5da9f571ab8c4b0b510b8368 (maybe no conflicts)

**Comment by smithfarm** [comment]
@dzafman Unfortunately, #14710 does not currently pass make check.

**Comment by smithfarm** [comment]
@dzafman Could you change the PR description to something more descriptive, like "jewel: core: ..." 

That will help with the release notes generation process.

**Comment by smithfarm** [comment]
@dzafman #14701 was just merged. Can you please proceed with steps 2-4 from https://github.com/ceph/ceph/pull/14204#issuecomment-296403724

**Comment by dzafman** [comment]
@smithfarm Updated description, rebased and fix 1 commit that no longer conflicts.

**Comment by dzafman** [comment]
@jdurgin I assume I shouldn't review my own backport.

**Comment by smithfarm** [comment]
@jdurgin This passed a rados run at http://tracker.ceph.com/issues/19538#note-49

Please review.

**Pull request merged**
