### PR TITLE
rbd: check value of config override when setting image-meta

### PR DESCRIPTION
**Pull request by zhuangzeqiang**
Fixes: http://tracker.ceph.com/issues/15522

Signed-off-by: zhuangzeqiang <zhuang.zeqiang@h3c.com>

### CODE REVIEW

**Comment by zhuangzeqiang** [comment]
@dillaman thanks for your explanation，is that ok？

**Comment by dillaman** [comment]
lgtm

**Comment by yuriw** [comment]
test run http://pulpito.ceph.com/yuriw-2016-05-26_19:14:40-rbd-wip-yuri-testing2-distro-basic-smithi/

**Comment by tchaikov** [comment]
@zhuangzeqiang if you were not posting this PR from the future, could you fix your localtime? your commit's timestamp is "Sat Oct 7 16:52:07 2017 +0800". and thanks to the way how github shows the commits you will be always the first one in https://github.com/ceph/ceph/commits/master until we have a newer commit.

**Comment by zhuangzeqiang** [comment]
@tchaikov Very embarrassed for that, and what should i do to fix it?

**Comment by tchaikov** [comment]
@zhuangzeqiang no. we can hardly fix this without rewriting the git history after your commit. but guess it's always good to have a correct time, no? =)

**Pull request merged**
