### PR TITLE
quincy -- sse s3 changes

### PR DESCRIPTION
**Pull request by mdw-at-linuxbox**
sse s3 changes backported to quincy.

No special magic here -- patches applied without issue.  Builds on fc35, not otherwise tested.  Will need corresponding changes to test suites to pass teuthology.

There might still be a build of this at ceph-ci -- look for "mdw-qmk-2"

### CODE REVIEW

**Comment by cbodley** [comment]
> is it a problem that these commits were not taken via "git cherry-pick -x"? (downstream, I can just edit the commit messages...)

@mattbenjamin i don't see any commits here that are missing the "cherry picked from commit" line, everything looks ok to me

**Comment by mattbenjamin** [comment]
> > is it a problem that these commits were not taken via "git cherry-pick -x"? (downstream, I can just edit the commit messages...)
> 
> @mattbenjamin i don't see any commits here that are missing the "cherry picked from commit" line, everything looks ok to me

thanks, @cbodley !

**Comment by cbodley** [comment]
@mdw-at-linuxbox can you please include the commit from https://github.com/ceph/ceph/pull/46232?

**Comment by cbodley** [comment]
> @mdw-at-linuxbox can you please include the commit from #46232?

ping

**Comment by cbodley** [comment]
passed qa in https://pulpito.ceph.com/cbodley-2022-08-02_18:55:58-rgw-pr-46467-distro-default-smithi/

**Review by cbodley — APPROVED** [review]

**Comment by cbodley** [comment]
i also added sse-s3 test cases to ceph-quincy branches of s3tests and java-s3tests

**Comment by mattbenjamin** [comment]
Great work @mdw-at-linuxbox @cbodley -- thanks for helping this get to Quincy!

**Pull request merged**
