### PR TITLE
rgw: support x-amz-tagging-directive for CopyObj

### PR DESCRIPTION
**Pull request by Rjerk**
Signed-off-by: Liu Lan <liulan_yewu@cmss.chinamobile.com>

https://docs.aws.amazon.com/AmazonS3/latest/API/API_CopyObject.html#API_CopyObject_RequestSyntax

> x-amz-tagging-directive
> Specifies whether the object tag-set are copied from the source object or replaced with tag-set provided in the request.
> Valid Values: COPY | REPLACE

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by Rjerk** [comment]
jenkins test make check

**Comment by Rjerk** [comment]
jenkins retest this please

**Comment by Rjerk** [comment]
jenkins retest this please

**Comment by mattbenjamin** [comment]
@Rjerk is it possible to create s3-test cases for these?

**Comment by Rjerk** [comment]
> @Rjerk is it possible to create s3-test cases for these?

https://github.com/ceph/s3-tests/pull/369

**Comment by Rjerk** [comment]
rebase is done, any pieces of advice?

**Pull request closed without merging**
