### PR TITLE
powerdns: flask disable JSONIFY_PRETTYPRINT_REGULAR

### PR DESCRIPTION
**Pull request by lxbsz**
The request.is_xhr property was deprecated since Werkzeug 0.13 and
removed in Werkzeug 1.0.0.

Signed-off-by: Xiubo Li <xiubli@redhat.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by tchaikov** [comment]
could you prefix the title of your commit message with the subcomponent your are changing ? see https://github.com/ceph/ceph/blob/master/SubmittingPatches.rst#3-describe-your-changes

**Comment by lxbsz** [comment]
> could you prefix the title of your commit message with the subcomponent your are changing ? see https://github.com/ceph/ceph/blob/master/SubmittingPatches.rst#3-describe-your-changes

Done, thanks!

**Review by idryomov — APPROVED** [review]
> return json.dumps(response, indent=1) + "\n"

In addition to flask dropping `JSONIFY_PRETTYPRINT_REGULAR` anyway, this appears to do its own formatting, so LGTM!

**Review by tchaikov — APPROVED** [review]

**Comment by tchaikov** [comment]
@lxbsz Xiubo, i just noticed a test failure like
```
2022-09-03T06:33:39.712 INFO:tasks.cram.a_gateway.0.smithi074.stdout: Create the first gateway
2022-09-03T06:33:39.712 INFO:tasks.cram.a_gateway.0.smithi074.stdout: ========================
2022-09-03T06:33:39.712 INFO:tasks.cram.a_gateway.0.smithi074.stdout:   $ HOST=`python3 -c "import socket; print(socket.getfqdn())"`
2022-09-03T06:33:39.712 INFO:tasks.cram.a_gateway.0.smithi074.stdout:   > IP=`hostname -i | awk '{print $1}'`
2022-09-03T06:33:39.713 INFO:tasks.cram.a_gateway.0.smithi074.stdout:   > sudo curl --user admin:admin -d ip_address=$IP -X PUT http://127.0.0.1:5000/api/gateway/iqn.2003-01.com.redhat.iscsi-gw:ceph-gw/$HOST -s
2022-09-03T06:33:39.713 INFO:tasks.cram.a_gateway.0.smithi074.stdout:-  {
2022-09-03T06:33:39.713 INFO:tasks.cram.a_gateway.0.smithi074.stdout:-    "message": "Gateway creation successful"
2022-09-03T06:33:39.713 INFO:tasks.cram.a_gateway.0.smithi074.stdout:-  }
2022-09-03T06:33:39.714 INFO:tasks.cram.a_gateway.0.smithi074.stdout:+  {"message":"Gateway creation successful"}
```

at https://pulpito.ceph.com/kchai-2022-09-03_01:50:21-rados-wip-pacific-update-fio-kefu-8-distro-default-smithi/7009273/

is this a regression introduced by https://github.com/ceph/ceph-iscsi/pull/263 . if yes, could you help update the test accordingly?

**Comment by lxbsz** [comment]
> @lxbsz Xiubo, i just noticed a test failure like
> 
> ```
> 2022-09-03T06:33:39.712 INFO:tasks.cram.a_gateway.0.smithi074.stdout: Create the first gateway
> 2022-09-03T06:33:39.712 INFO:tasks.cram.a_gateway.0.smithi074.stdout: ========================
> 2022-09-03T06:33:39.712 INFO:tasks.cram.a_gateway.0.smithi074.stdout:   $ HOST=`python3 -c "import socket; print(socket.getfqdn())"`
> 2022-09-03T06:33:39.712 INFO:tasks.cram.a_gateway.0.smithi074.stdout:   > IP=`hostname -i | awk '{print $1}'`
> 2022-09-03T06:33:39.713 INFO:tasks.cram.a_gateway.0.smithi074.stdout:   > sudo curl --user admin:admin -d ip_address=$IP -X PUT http://127.0.0.1:5000/api/gateway/iqn.2003-01.com.redhat.iscsi-gw:ceph-gw/$HOST -s
> 2022-09-03T06:33:39.713 INFO:tasks.cram.a_gateway.0.smithi074.stdout:-  {
> 2022-09-03T06:33:39.713 INFO:tasks.cram.a_gateway.0.smithi074.stdout:-    "message": "Gateway creation successful"
> 2022-09-03T06:33:39.713 INFO:tasks.cram.a_gateway.0.smithi074.stdout:-  }
> 2022-09-03T06:33:39.714 INFO:tasks.cram.a_gateway.0.smithi074.stdout:+  {"message":"Gateway creation successful"}
> ```
> 
> at https://pulpito.ceph.com/kchai-2022-09-03_01:50:21-rados-wip-pacific-update-fio-kefu-8-distro-default-smithi/7009273/
> 
> ~is this a regression introduced by [ceph/ceph-iscsi#263](https://github.com/ceph/ceph-iscsi/pull/263) ? if yes, could you help update the test accordingly?~ oh, we already have #47920. thank you @idryomov !

Yeah, Ilya has already fixed it.

**Comment by ktdreyer** [comment]
Flask shipped 1.0 in 2018, and that removed the reference to `is_xhr` https://github.com/pallets/flask/pull/2193

What version of Flask are you using? What is your OS?

**Comment by lxbsz** [comment]
> Flask shipped 1.0 in 2018, and that removed the reference to `is_xhr` [pallets/flask#2193](https://github.com/pallets/flask/pull/2193)
> 
> What version of Flask are you using? What is your OS?

This was first seen in the ceph-iscsi https://github.com/ceph/ceph-iscsi/pull/263, which was reported by one cu.

**Comment by ktdreyer** [comment]
> This was first seen in the ceph-iscsi https://github.com/ceph/ceph-iscsi/pull/263, which was reported by one cu.

Thanks.

I don't think this is an issue on modern distros. We could probably close it.

**Comment by ktdreyer** [comment]
This cu was using powerdns?

**Comment by lxbsz** [comment]
> This cu was using powerdns?

Long time for this. I couldn't get which BZ now.  I am okay to close it for now and when needed let's reopen it.

Thanks!

**Pull request closed without merging**
