### PR TITLE
doc: clarify WAL in bluestore-config-ref.rst

### PR DESCRIPTION
**Pull request by CodingSpiderFox**
Signed-off-by: CodingSpiderFox <codingspiderfox@gmail.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by CodingSpiderFox** [comment]
@athanatos here is the new PR :)

**Comment by tchaikov** [comment]
@CodingSpiderFox is "CodingSpiderFox" you real name? if not, could you use your real name for signing your contribution? see https://github.com/ceph/ceph/blob/master/SubmittingPatches.rst#developer-s-certificate-of-origin-1-1

**Comment by CodingSpiderFox** [comment]
I'd like to keep a bit of privacy online.
Would firstname and first letter of last name be OK?

**Comment by tchaikov** [comment]
@CodingSpiderFox i discussed this with the team, we think it's okay.

**Pull request merged**
