### PR TITLE
msg/simple: use my addr when setting sock priority

### PR DESCRIPTION
**Pull request by tchaikov**
Fixes: http://tracker.ceph.com/issues/19801

### CODE REVIEW

**Comment by tchaikov** [comment]
retest this please.

**Comment by yuyuyu101** [comment]
async commit isn't a fix, right?

**Comment by tchaikov** [comment]
@yuyuyu101 no, it's not. i am not tagging it as a fix either.

**Comment by tchaikov** [comment]
http://pulpito.ceph.com/kchai-2017-04-30_13:25:30-rados-wip-kefu-testing---basic-smithi/

**Pull request merged**
