### PR TITLE
mgr/cephadm: allow config for an nfs `container_image`

### PR DESCRIPTION
**Pull request by mgfritch**
For example, to apply a custom container image for all nfs services:

```
ceph config set client.nfs container_image <container_image>
```

Signed-off-by: Michael Fritch <mfritch@suse.com>

**Depends on**

- [x] #34406

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by sebastian-philipp** [comment]
please make sure, this doesn't break upgrades.

**Comment by sebastian-philipp** [comment]
afaik, you can already set a specific image using the mon store, right?

**Comment by mgfritch** [comment]
> afaik, you can already set a specific image using the mon store, right?

Only for core ceph services, this PR extends the same logic to work with nfs. An alternate solution might be to pass the container image via the service spec?

**Comment by liewegas** [comment]
I think this approach is flawed because normal clusters will have a [global] level container_image setting pointing to ceph/ceph, and we don't want that image used for nfs.  Right now things work only because mgr/cephadm doesn't specify an image and the cephadm script has a type-specific default.  If we make this change then you have to keep a [client.nfs] container_image in the config store.

**Comment by liewegas** [comment]
Probably better to have a ganesha_container_image setting?

**Comment by mgfritch** [comment]
the type specific defaults exist for the monitoring stack, but nfs-ganesha is currently packaged with the `ceph/ceph` container .. 

`ganesha_container_image` would avoid mistakes around the global setting .. or maybe it would make sense to split these by daemon type: `mgr/cephadm/nfs/container_image` or similar ?

**Comment by sebastian-philipp** [comment]
somehow, I don't really like `ganesha_container_image`. Then, what's next? `grafana_contaienr_image`? `prometheus_container_image`? `node-exporter_contaienr_image`?

**Comment by sebastian-philipp** [comment]
> I think this approach is flawed because normal clusters will have a [global] level container_image setting pointing to ceph/ceph, and we don't want that image used for nfs. Right now things work only because mgr/cephadm doesn't specify an image and the cephadm script has a type-specific default. If we make this change then you have to keep a [client.nfs] container_image in the config store.

after rethinking this, NFS uses (and will use) the **same** `ceph/ceph` image as the rest of the ceph daemons. Which means, we should be safe here. Right? 

(We need to rethink this for the monitoring containers, but NFS should be safe)

**Comment by liewegas** [comment]
> > I think this approach is flawed because normal clusters will have a [global] level container_image setting pointing to ceph/ceph, and we don't want that image used for nfs. Right now things work only because mgr/cephadm doesn't specify an image and the cephadm script has a type-specific default. If we make this change then you have to keep a [client.nfs] container_image in the config store.
> 
> after rethinking this, NFS uses (and will use) the **same** `ceph/ceph` image as the rest of the ceph daemons. Which means, we should be safe here. Right?
> 
> (We need to rethink this for the monitoring containers, but NFS should be safe)

Oh, right.  Yeah.

I currently lean toward ``mgr/cephadm/${type}_container_image`` for the others, just because it feels awkward to try to map things like node-exporter or prometheus to client.something so that we can make container_image apply in that dimension.  It happens to work for ``client.nfs.*`` but not so much for the others.

Also, I'm thinking that we might want to expand ``ceph upgrade start --ceph-version <x.y.z>`` to include ``--prometheus-version x`` and so on so that we can upgrade the other daemons?  Or we have a given version of ceph pin itself to a particular verson of the prometheus etc.. not really sure.  Either way, at some point in the not-too-distant future we'll want to be able to upgrade those too.

**Comment by sebastian-philipp** [comment]
QA run failed: upgrade test failed, due to a missing `octopus` tag:

http://qa-proxy.ceph.com/teuthology/swagner-2020-04-02_14:10:58-rados-wip-swagner2-testing-2020-04-02-1049-distro-basic-smithi/4917791/teuthology.log

@dmick Any idea?

**Comment by dmick** [comment]
Now I see the context for the question in IRC.  I don't know how upgrade tests work, but it seems wrong for them to be using the "upgrade from" branch as something from the CI namespace; wouldn't you want to be testing from actual released branches?  Maybe this is some crossover pain from when the released branch moves from cephci.git to ceph.git, and maybe teuthology searched download.ceph.com first, didn't find it, so tried (hopelessly) to find it in shaman?

**Pull request merged**
