### PR TITLE
mgr/dashboard: Introduce layout components

### PR DESCRIPTION
**Pull request by votdev**
This PR will simplify the code of the app component in that way that it introduces layout components. Depending on the route a specific layout is choosen. Currently there are two layouts:

- Workbench
- Blank

The blank layout, which does not show any navigation controls, is used for the error, login and logout pages.

The 403 and 404 pages have a `Back` button that will redirect to `/login`. The Angular router will redirect to `/dashboard` if logged in.

Bildschirmfoto vom 2020-01-17 11-22-28

Bildschirmfoto vom 2020-01-17 11-22-46

Bildschirmfoto vom 2020-01-10 14-14-25

The workbench layout shows the navigation controls and is mainly used for all pages that are used to configure Ceph.

Fixes: https://tracker.ceph.com/issues/43565

Signed-off-by: Volker Theile <vtheile@suse.com>

## Checklist
- [x] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by votdev** [comment]
> LGTM, but the tracker link is missing in the PR description and your commit message.

Need to create one first :-)

**Comment by votdev** [comment]
> lgtm, but there is a new error that happens when you go from the `WorkbenchLayoutComponent` to the `BlankLayoutComponent`.
> Just login and logout and you will see the error.
> 
> ```
> Uncaught Error: ViewDestroyedError: Attempt to use a destroyed view: detectChanges
>     at viewDestroyedError (core.js:28818)
> ```

Strange, can not reproduce this with Chrome 79.0.3945.117 and Firefox 72.0.1.

Peek 2020-01-14 10-40

**Comment by votdev** [comment]
jenkins test make check

**Comment by votdev** [comment]
jenkins test make check

**Comment by votdev** [comment]
jenkins test make check arm64

**Comment by tspmelo** [comment]
@votdev The problem seems to happen only when using a non production build or using `ng serve`, could not reproduce it with a prod build.

**Comment by votdev** [comment]
> @votdev The problem seems to happen only when using a non production build or using `ng serve`, could not reproduce it with a prod build.

Fixed

**Comment by Exotelis** [comment]
LGTM with one exception. 

- If you land on the 404 or 403 we should display at least one link to get back to any page :-) Seems to be a dead end currently

**Comment by votdev** [comment]
> LGTM with one exception.
> 
> If you land on the 404 or 403 we should display at least one link to get back to any page :-) Seems to be a dead end currently. Or wouldn't it be better to keep the navigation displayed in this two cases?

I think we should not display the navigation for both pages because there are surely situations where it shouldn't and can't be displayed, e.g. when user is logged out and tries to reach an invalid URL (currently this IS the situation which is not good IMO).

**Comment by Exotelis** [comment]
> > LGTM with one exception.
> > If you land on the 404 or 403 we should display at least one link to get back to any page :-) Seems to be a dead end currently. Or wouldn't it be better to keep the navigation displayed in this two cases?
> 
> I think we should not display the navigation for both pages because there are surely situations where it shouldn't and can't be displayed, e.g. when user is logged out and tries to reach an invalid URL (currently this IS the situation which is not good IMO).
> 
> But the question is what is the URL for the back button? Should we use /dashboard? The router will take care to redirect to the correct page in case of problems, e.g. if user is logged out router will redirect to login page.

A redirect to the dashboard sounds good. As you mentioned the user will be redirected to the login page if he is not logged in :-) 
Thanks for your changes

**Comment by votdev** [comment]
jenkins test make check arm64

**Pull request merged**
