### PR TITLE
python-common: move pytest integration from setup.py to tox.ini

### PR DESCRIPTION
**Pull request by sebastian-philipp**
I for one prefer to have this integration in the setup.py instead of making the tox.ini more complex. I don't think we're gaining so much readability here.

thoughts?

Signed-off-by: Sebastian Wagner <sebastian.wagner@suse.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`

</details>

### CODE REVIEW

**Comment by sebastian-philipp** [comment]
> LGTM.
> 
> @sebastian-philipp could you rebase against master?

this is kind of low on my prio list, as it doesn't really fix anything urgently.

**Comment by sebastian-philipp** [comment]
This might actually now fix a bug:

```
5: Installed /nvm/src/ceph3/src/python-common/.eggs/toml-0.10.0-py3.7.egg
5: Traceback (most recent call last):
5:   File "setup.py", line 62, in <module>
5:     'Programming Language :: Python :: 3.6',
5:   File "/home/sage/src/ceph3/src/python-common/.tox/py3/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
5:     return distutils.core.setup(**attrs)
5:   File "/usr/lib64/python3.7/distutils/core.py", line 148, in setup
5:     dist.run_commands()
5:   File "/usr/lib64/python3.7/distutils/dist.py", line 966, in run_commands
5:     self.run_command(cmd)
5:   File "/usr/lib64/python3.7/distutils/dist.py", line 985, in run_command
5:     cmd_obj.run()
5:   File "/home/sage/src/ceph3/src/python-common/.tox/py3/lib/python3.7/site-packages/setuptools/command/test.py", line 225, in run
5:     installed_dists = self.install_dists(self.distribution)
5:   File "/home/sage/src/ceph3/src/python-common/.tox/py3/lib/python3.7/site-packages/setuptools/command/test.py", line 209, in install_dists
5:     tr_d = dist.fetch_build_eggs(dist.tests_require or [])
5:   File "/home/sage/src/ceph3/src/python-common/.tox/py3/lib/python3.7/site-packages/setuptools/dist.py", line 720, in fetch_build_eggs
5:     replace_conflicting=True,
5:   File "/home/sage/src/ceph3/src/python-common/.tox/py3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 791, in resolve
5:     raise VersionConflict(dist, req).with_context(dependent_req)
5: pkg_resources.ContextualVersionConflict: (importlib-metadata 1.1.0 (/nvm/src/ceph3/src/python-common/.eggs/importlib_metadata-1.1.0-py3.7.egg), Requirement.parse('importlib-metadata<1,>=0.12'), {'tox'})
5: ERROR: InvocationError for command /home/sage/src/ceph3/src/python-common/.tox/py3/bin/python setup.py test '--addopts=--mypy --mypy-ignore-missing-imports' (exited with code 1)
```

**Comment by sebastian-philipp** [comment]
> > LGTM.
> > @sebastian-philipp could you rebase against master?
> 
> this is kind of low on my prio list, as it doesn't really fix anything urgently.

done.

**Comment by tchaikov** [comment]
```
ERROR: Double requirement given: pytest>=2.1.3 (from -r requirements-test-3.txt (line 3)) (already in pytest<5,>=2.1.3 (from -r requirements-test-2.txt (line 1)), name='pytest')
```

**Comment by liewegas** [comment]
This fixes my local make check test ``ctest -R run-tox-python-common``

**Comment by tchaikov** [comment]
i am trying to address the failure in #31943

**Comment by tchaikov** [comment]
#31943 does address the issue. @liewegas @sebastian-philipp could you help review that PR instead?

**Pull request closed without merging**
