### PR TITLE
test/TestPGLog: fix the FTBFS

### PR DESCRIPTION
**Pull request by tchaikov**
the new pure virtual method was introduced by e7edf2.

Signed-off-by: Kefu Chai <kchai@redhat.com>

### CODE REVIEW

**Comment by dachary** [comment]
<pre>
Reviewed-by: Loic Dachary &lt;ldachary@redhat.com>
</pre>

after make check is happy with it.

**Comment by dachary** [comment]
<pre>
void PGLogTest::LogHandler::try_stash(const pg_log_entry_t&, version_t)’ marked override, but does not override
     void try_stash(
</pre>

**Comment by tchaikov** [comment]
d'oh, forgot to commit the latest changes.

**Comment by jdurgin** [comment]
Added http://tracker.ceph.com/issues/14930 before I saw this

**Comment by tchaikov** [comment]
changelog:

* sync'ed with the local repo, (forgot to commit the latest change in local tree)
* add the "Fixed" line to link this change with http://tracker.ceph.com/issues/14930

**Pull request merged**
