### PR TITLE
Merge pull request #2 from stiwari/fix_1

### PR DESCRIPTION
**Pull request by stiwari**
Updated : Documentation Fixes for http://tracker.ceph.com/issues/19879

### CODE REVIEW

**Comment by gregsfortytwo** [comment]
I'm not quite sure if this was meant to exist, but it's just a merge commit. :)

**Comment by stiwari** [comment]
i want to make an update to the change I made in the .rst file and not able to do so.

**Comment by stiwari** [comment]
I updated the code in my local repo, commited, pushed, and then created a new pull request

**Comment by stiwari** [comment]
Sorry, if I am messing up :-(

**Comment by stiwari** [comment]
I made an update, to my previous change, in the ceph/doc/man/8/ceph-osd.rst
file, and re-submitted the pull request.

Maybe I did it the wrong way? Sorry, if I am messing up. :-(

-Sameer

**Comment by gregsfortytwo** [comment]
I'm not sure how you went wrong (perhaps you didn't actually commit the change? That happens sometimes to me if I don't add a file and forget the "-a" flag I most often use), but you definitely didn't include any changes in this PR. There's just a merge from your fix_1 branch (which I merged at https://github.com/ceph/ceph/pull/15606) into your master branch, which you are here attempting to push into the main ceph.git master. Since the ceph.git master branch already includes that fix_1, there's no change.

**Pull request closed without merging**
