### PR TITLE
qa/suites/upgrade/pacific-x/rgw-multisite: fix install version

### PR DESCRIPTION
**Pull request by neha-ojha**
Before:

2021-04-22T06:20:58.260 INFO:teuthology.task.install:Ceph rpm upgrade from
16.2.1-103.gb54cefd0.el8 to 16.2.1-103.gb54cefd0

After:

2021-04-22T21:08:16.565 INFO:teuthology.task.install:Ceph rpm upgrade from
16.2.1-105.g540c2494.el8 to 17.0.0-3515.ga5b16446

Fixes: https://tracker.ceph.com/issues/50388
Signed-off-by: Neha Ojha <nojha@redhat.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by neha-ojha** [comment]
Testing it here: https://pulpito.ceph.com/nojha-2021-04-22_20:42:41-rados:upgrade:pacific-x:rgw-multisite-master-distro-basic-smithi/

**Comment by neha-ojha** [comment]
> Testing it here: https://pulpito.ceph.com/nojha-2021-04-22_20:42:41-rados:upgrade:pacific-x:rgw-multisite-master-distro-basic-smithi/

The upgrade went fine but rgw-multisite-tests are continuing to run...

```
2021-04-22T21:02:33.418 INFO:teuthology.task.install:Ceph rpm upgrade from 16.2.1-105.g540c2494.el8 to 17.0.0-3515.ga5b16446
...
2021-04-22T21:03:46.189 INFO:teuthology.task.install:The correct ceph version 17.0.0-3515.ga5b16446 is installed.
```

**Comment by neha-ojha** [comment]
> > Testing it here: https://pulpito.ceph.com/nojha-2021-04-22_20:42:41-rados:upgrade:pacific-x:rgw-multisite-master-distro-basic-smithi/
> 
> The upgrade went fine but rgw-multisite-tests are continuing to run...
> 
> ```
> 2021-04-22T21:02:33.418 INFO:teuthology.task.install:Ceph rpm upgrade from 16.2.1-105.g540c2494.el8 to 17.0.0-3515.ga5b16446
> ...
> 2021-04-22T21:03:46.189 INFO:teuthology.task.install:The correct ceph version 17.0.0-3515.ga5b16446 is installed.
> ```

Failed with https://tracker.ceph.com/issues/49955, I think? @cbodley can you please confirm

**Comment by neha-ojha** [comment]
jenkins test make check

**Review by tchaikov — APPROVED** [review]

**Review by yuriw — APPROVED** [review]

**Review by cbodley — APPROVED** [review]
looks fine, thanks. i really didn't intend for these to run in the rados suite. is there a better place to put them?

**Comment by neha-ojha** [comment]
> looks fine, thanks. i really didn't intend for these to run in the rados suite. is there a better place to put them?

That's because we symlink upgrade/pacific-x within rados/upgrade, but going forward we will symlink subdirectories https://github.com/ceph/ceph/pull/41006

**Pull request merged**
