### PR TITLE
rgw/multisite: metadata polling event based on unmodified mdlog_marker

### PR DESCRIPTION
**Pull request by smanjara**
In order to sleep between metadata log polling events, we check if the mdlog_marker is not modified by comparing
mdlog_marker and max_marker. but max_marker is exposed to changes from RGWReadMDLogEntriesCR, and if there is a race coming from mdlog trimming which could render max_marker empty, then its comparison with mdlog polling can be incorrect. To fix this, we now save the previous mdlog marker and compare with the updated mdlog marker.

https://tracker.ceph.com/issues/61743

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by smanjara** [comment]
@mkogan1 @cbodley I have replaced https://github.com/ceph/ceph/pull/52400 with this one.

**Comment by smanjara** [comment]
@cbodley do you have any review comments? we want to take this downstream.

**Review by cbodley — APPROVED** [review]

**Comment by coder-hugo** [comment]
Any news on this? We had to recreate one of our zones and since then this bug is killing our master zone. To fix this I had to build the rados gateway on my own with this patch.

**Comment by smanjara** [comment]
> Any news on this? We had to recreate one of our zones and since then this bug is killing our master zone. To fix this I had to build the rados gateway on my own with this patch.

the pr was meant to address excessive polling, but we weren't sure if it was very helpful. thanks for testing.

**Comment by smanjara** [comment]
@cbodley should we merge this? I see that you have approved and Mark has run some load testing on it in #52400

**Comment by mattbenjamin** [comment]
sounds like it helped this site

**Comment by cbodley** [comment]
> @cbodley should we merge this? I see that you have approved and Mark has run some load testing on it in #52400

it has my approval. if you're satisfied with the testing it's seen, feel free to merge

**Comment by coder-hugo** [comment]
Any chance to get this into `reef` or `squid`? Since this bug is killing our master zone I need to package `ceph` myself for every new release as the fix is currently only available in the `main` branch.

**Pull request merged**
