### PR TITLE
rgw/qa: fix for teuthology failure related to role metadata sync

### PR DESCRIPTION
**Pull request by pritha-srivastava**
in case of pub sub zone.

fixes: https://tracker.ceph.com/issues/56175

Signed-off-by: Pritha Srivastava <prsrivas@redhat.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [x] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by pritha-srivastava** [comment]
Runs locally fine for both num_ps_zones = 0 and num_ps_zones = 1.

**Review by cbodley — APPROVED** [review]

**Comment by pritha-srivastava** [comment]
teuthology run: https://pulpito.ceph.com/prsrivas-2022-06-29_09:42:15-rgw:multisite-wip-rgw-sts-teuthology-failure-distro-default-smithi/ - both jobs are dead, have scheduled a re-run here: https://pulpito.ceph.com/prsrivas-2022-06-29_12:09:13-rgw:multisite-wip-rgw-sts-teuthology-failure-distro-default-smithi/

**Comment by pritha-srivastava** [comment]
@cbodley : https://pulpito.ceph.com/prsrivas-2022-06-30_08:21:00-rgw:multisite-wip-rgw-sts-teuthology-failure-distro-default-smithi/ is successful for test_role_sync test. There are other test faillures but test_role_sync has passed.

**Comment by cbodley** [comment]
thanks @pritha-srivastava!

**Pull request merged**
