### PR TITLE
qa: reorg podman distro files; disable centos/rhel podman tests for now

### PR DESCRIPTION
**Pull request by liewegas**
- do not use distro podman on centos/rhel because 2.2.1 is broken
- reorganize the distro files with kubic repos
- consistently use podman distro files for cephadm tests

### CODE REVIEW

**Comment by liewegas** [comment]
jenkins test make check

**Comment by liewegas** [comment]
jenkins test make check

**Review by sebastian-philipp — APPROVED** [review]

**Comment by liewegas** [comment]
jenkins test make check

**Comment by liewegas** [comment]
https://pulpito.ceph.com/sage-2021-03-04_23:44:35-upgrade:octopus-x:stress-split-wip-sage-testing-2021-03-04-1435-distro-basic-gibba/
https://pulpito.ceph.com/sage-2021-03-04_21:20:56-upgrade:octopus-x:parallel-wip-sage-testing-2021-03-04-1435-distro-basic-gibba/
https://pulpito.ceph.com/sage-2021-03-04_21:20:22-rados:cephadm:upgrade-wip-sage-testing-2021-03-04-1435-distro-basic-gibba/#

**Comment by tchaikov** [comment]
@liewegas this introduced a regression. see https://tracker.ceph.com/issues/49638.

**Comment by liewegas** [comment]
> @liewegas this introduced a regression. see https://tracker.ceph.com/issues/49638.

Yeah :(.  I think it is simplest to just live with this one until we fix the tests to run on centos again.. which hopefully is just a matter of setting up the right repos?  Whatever is needed to avoid the toxic podman v2.2.1

**Pull request merged**
