### PR TITLE
tests: verify erasure code read / write after remapping

### PR DESCRIPTION
**Pull request by dachary**
http://tracker.ceph.com/issues/11667

### CODE REVIEW

**Comment by dachary** [comment]
repushed and rebased

**Comment by dachary** [comment]
@tchaikov thanks for volunteering for review :-) I rebased and repushed to get a fresh make check run.

**Comment by tchaikov** [comment]
tested. and looks good with a minor suggestion

`Reviewed-by: Kefu Chai <kchai@redhat.com>`.

**Comment by dachary** [comment]
@tchaikov repushed with your changes: much better :-)

**Pull request merged**
