### PR TITLE
pacific: qa: switch to https protocol for repos' server

### PR DESCRIPTION
**Pull request by lxbsz**
backport tracker: https://tracker.ceph.com/issues/58293

---

backport of https://github.com/ceph/ceph/pull/49021 and two commits of https://github.com/ceph/ceph/pull/48628
parent tracker: https://tracker.ceph.com/issues/58290 and https://tracker.ceph.com/issues/58133

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Review by vshankar — CHANGES_REQUESTED** [review]
```
flake8: install_deps /home/jenkins-build/build/workspace/ceph-pull-requests/qa> python -I -m pip install flake8
flake8: commands[0] /home/jenkins-build/build/workspace/ceph-pull-requests/qa> flake8 --select=F,E9 --exclude=venv,.tox
./tasks/cephfs/xfstests_dev.py:40:9: F401 'teuthology.orchestra.run' imported but unused
flake8: exit 1 (4.50 seconds) /home/jenkins-build/build/workspace/ceph-pull-requests/qa> flake8 --select=F,E9 --exclude=venv,.tox pid=105597
  py3: OK (0.32 seconds)
  flake8: FAIL code 1 (12.76=setup[8.27]+cmd[4.50] seconds)
  evaluation failed :( (13.30 seconds)
```

**Comment by lxbsz** [comment]
> ```
> flake8: install_deps /home/jenkins-build/build/workspace/ceph-pull-requests/qa> python -I -m pip install flake8
> flake8: commands[0] /home/jenkins-build/build/workspace/ceph-pull-requests/qa> flake8 --select=F,E9 --exclude=venv,.tox
> ./tasks/cephfs/xfstests_dev.py:40:9: F401 'teuthology.orchestra.run' imported but unused
> flake8: exit 1 (4.50 seconds) /home/jenkins-build/build/workspace/ceph-pull-requests/qa> flake8 --select=F,E9 --exclude=venv,.tox pid=105597
>   py3: OK (0.32 seconds)
>   flake8: FAIL code 1 (12.76=setup[8.27]+cmd[4.50] seconds)
>   evaluation failed :( (13.30 seconds)
> ```

Fixed it. Thanks.

**Review by idryomov — APPROVED** [review]

**Comment by idryomov** [comment]
(The affected RBD jobs likely still won't pass but that is a separate issue.)

**Review by badone — APPROVED** [review]

**Comment by badone** [comment]
@vshankar Can you mark your changes resolved so I can get this merged please?

**Review by vshankar — APPROVED** [review]

**Comment by yuriw** [comment]
@lxbsz pls rebase this

@badone I checked with @vshankar and it's safe to merge

If it were merged I'd take in for 16.2.11.

Thx

**Comment by badone** [comment]
Since this is a special situation I have resolved the conflict via the github interface and will merge the commit once the tests have completed.

**Comment by tchaikov** [comment]
hi Brad, sorry if i delayed the merging. just wanted to make sure the git history is more linear. i will merge this change by the end of the day if it has been merged by then.

**Comment by tchaikov** [comment]
jenkins test api

**Comment by yuriw** [comment]
jenkins test api

**Comment by yuriw** [comment]
all passed @tchaikov

**Comment by badone** [comment]
> hi Brad, sorry if i delayed the merging. just wanted to make sure the git history is more linear. i will merge this change by the end of the day if it has been merged by then.

Unfortunately, the way  you have it now would revert part of https://github.com/ceph/ceph/pull/49543 which was the conflict I fixed yesterday so this still can't be merged. Check https://github.com/ceph/ceph/compare/5b6ccb14d5d643b0898b7388bd9820fea889b1b3..2d3be8fc32c021ad80afe499c0aef4f4fe754089

**Comment by tchaikov** [comment]
> > hi Brad, sorry if i delayed the merging. just wanted to make sure the git history is more linear. i will merge this change by the end of the day if it has been merged by then.
> 
> Unfortunately, the way you have it now would revert part of #49543 which was the conflict I fixed yesterday so this still can't be merged. Check https://github.com/ceph/ceph/compare/5b6ccb14d5d643b0898b7388bd9820fea889b1b3..2d3be8fc32c021ad80afe499c0aef4f4fe754089

@badone hi Brad, the covert letter of this PR does not mention #49543 at all. neither did your commit message. i think that's why i didn't include the reverted part.

also, if we intend to backport a change, i'd suggest to be explicit. so i cherry-picked the change you put in the link in the form of a cherry-pick. hopefully that'd restore your fix yesterday.

**Comment by lxbsz** [comment]
Rebased it.

**Comment by badone** [comment]
> @badone hi Brad, the cover letter of this PR does not mention #49543 at all. neither did your commit message. i think that's why i didn't include the reverted part.
> 

Hi Kefu,

This PR predates #49543 so that's why it doesn't mention it and that's why it created a conflict. The web interface for resolving conflicts does not allow you to edit the commit message AFAICT so I probably wouldn't use it again. Nevertheless the conflict resolution I provided reflected what we want the codebase to look like after this PR is merged for whatever that's worth. I won't argue the toss with you any more because you are usually right but I just can't see how this time around. Thanks for the help.

**Comment by badone** [comment]
jenkins test api

**Comment by idryomov** [comment]
> Nevertheless the conflict resolution I provided reflected what we want the codebase to look like after this PR is merged for whatever that's worth.

I can confirm that the current conflict resolution wrt. https://github.com/ceph/ceph/pull/49543 is correct.  We shouldn't be touching `qa/run_xfstests-obsolete.sh` here because the required changes to that script got backported ahead of this PR.

**Comment by idryomov** [comment]
> I can confirm that the current conflict resolution wrt. #49543 is correct. We shouldn't be touching `qa/run_xfstests-obsolete.sh` here because the required changes to that script got backported ahead of this PR.

That said, it's done rather backwards...  The right way to do it would have been to drop `qa/run_xfstests-obsolete.sh` hunk from the first commit.  Then you the fourth commit wouldn't have been needed (as it's already cherry-picked to pacific in https://github.com/ceph/ceph/pull/49543).

As it is, this PR first undoes part of the change that is already in pacific (in the first commit) and then re-introduces that change (in the forth commit, which has nothing to do with the two PRs that are getting backported here according to the description).

**Comment by lxbsz** [comment]
> > I can confirm that the current conflict resolution wrt. #49543 is correct. We shouldn't be touching `qa/run_xfstests-obsolete.sh` here because the required changes to that script got backported ahead of this PR.
> 
> That said, it's done rather backwards... The right way to do it would have been to drop `qa/run_xfstests-obsolete.sh` hunk from the first commit. Then the fourth commit wouldn't have been needed -- it's already cherry-picked to pacific in #49543.
> 
> As it is, this PR first undoes part of the change that is already in pacific (in the first commit) and then re-introduces that change (in the forth commit, which has nothing to do with the two PRs that are getting backported here according to the description).

Sounds good and done.

**Comment by lxbsz** [comment]
jenkins test make check

**Comment by lxbsz** [comment]
jenkins test api

**Comment by lxbsz** [comment]
jenkins test api

**Comment by lxbsz** [comment]
jenkins test api

**Comment by yuriw** [comment]
jenkins test api

**Pull request merged**
