### PR TITLE
cephadm: introduce flake8 and flake8-quotes

### PR DESCRIPTION
**Pull request by mgfritch**
* Add flake8 as a linter for bin/cephadm
* Add flake8-quotes to standardize on a `'` chars

Replaces: https://github.com/ceph/ceph/pull/39576

Signed-off-by: Michael Fritch mfritch@suse.com

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by sebastian-philipp** [comment]
you have a chmod on cephadm in this PR

**Comment by mgfritch** [comment]
> you have a chmod on cephadm in this PR

ooops! thanks for catching. looks like this was actually introduce by #39576

**Comment by mgfritch** [comment]
jenkins test make check

**Review by jmolmo — APPROVED** [review]
LGTM. Thanks Michael!!!

**Comment by mgfritch** [comment]
https://pulpito.ceph.com/mgfritch-2021-03-02_23:06:05-rados:cephadm-wip-mgfritch-testing-2021-03-02-1408-distro-basic-smithi/

**Comment by mgfritch** [comment]
https://pulpito.ceph.com/mgfritch-2021-03-02_23:06:05-rados:cephadm-wip-mgfritch-testing-2021-03-02-1408-distro-basic-smithi/

Failures:
https://tracker.ceph.com/issues/49590

**Pull request merged**
