### PR TITLE
obj_bencher rados cli: rados bench producing wrong values when different blocksize used in writes and reads

### PR DESCRIPTION
**Pull request by dmitryya**
Propose fix for tracker.ceph.com/issues/10163

### CODE REVIEW

**Comment by dachary** [comment]
@dmitryya nice catch :-) The documentation for -b is actually incorrect: it is used to specify the block size for get / put operations also. Can you fix the documentation as well ? Otherwise looks great. I would even go as far as to rename the aio_bench argument op_size into object_size to reflect the reality of how it is used, but that's up to you.

**Comment by dachary** [comment]
@dmitryya could you please rebase ?

**Comment by dmitryya** [comment]
@dachary done

**Comment by dachary** [comment]
@dmitryya one last detail: the Signed-off-by: is missing from cce82bf. When updated it's good to merge :-)

**Comment by dmitryya** [comment]
@dachary oh, sorry. updated

**Pull request merged**
