### PR TITLE
qa: add fiemap and seek_hole to rados thrashers

### PR DESCRIPTION
**Pull request by branch-predictor**
Let them break stuff or prove that these things actually work.

Signed-off-by: Piotr Dałek <piotr.dalek@corp.ovh.com>

### CODE REVIEW

**Comment by liewegas** [comment]
<pre>
2017-08-31T18:53:27.162 INFO:tasks.ceph.osd.6.smithi110.stderr:/build/ceph-13.0.0-265-g782a632/src/os/filestore/FileStore.cc: In function 'int FileStore::_do_copy_range(int, int, uint64_t, uint64_t, uint64_t, bool)' thread 7f839c7a9700 time 2017-08-31 18:53:27.087689
2017-08-31T18:53:27.163 INFO:tasks.ceph.osd.6.smithi110.stderr:/build/ceph-13.0.0-265-g782a632/src/os/filestore/FileStore.cc: 3888: FAILED assert(replaying || pos == end)
2017-08-31T18:53:27.163 INFO:tasks.ceph.osd.6.smithi110.stderr:2017-08-31 18:53:27.087682 7f839c7a9700 -1 filestore(/var/lib/ceph/osd/ceph-6) _do_copy_range(3859): got short read result at 1769472 of fd 190 len 3445501
2017-08-31T18:53:27.163 INFO:tasks.ceph.osd.6.smithi110.stderr: ceph version 13.0.0-265-g782a632 (782a6325f47c23cc439b86e14f74eeb1572e56bc) mimic (dev)
2017-08-31T18:53:27.163 INFO:tasks.ceph.osd.6.smithi110.stderr: 1: (ceph::__ceph_assert_fail(char const*, char const*, int, char const*)+0x102) [0xb907732662]
2017-08-31T18:53:27.163 INFO:tasks.ceph.osd.6.smithi110.stderr: 2: (FileStore::_do_copy_range(int, int, unsigned long, unsigned long, unsigned long, bool)+0x913) [0xb9074a9113]
2017-08-31T18:53:27.163 INFO:tasks.ceph.osd.6.smithi110.stderr: 3: (FileStore::_do_sparse_copy_range(int, int, unsigned long, unsigned long, unsigned long)+0x479) [0xb9074cbd39]
2017-08-31T18:53:27.163 INFO:tasks.ceph.osd.6.smithi110.stderr: 4: (FileStore::_do_clone_range(int, int, unsigned long, unsigned long, unsigned long)+0x287) [0xb9074a8777]
2017-08-31T18:53:27.163 INFO:tasks.ceph.osd.6.smithi110.stderr: 5: (FileStore::_clone_range(coll_t const&, ghobject_t const&, coll_t const&, ghobject_t const&, unsigned long, unsigned long, unsigned long, SequencerPosition const&)+0x3c5) [0xb9074d7085]
2017-08-31T18:53:27.163 INFO:tasks.ceph.osd.6.smithi110.stderr: 6: (FileStore::_do_transaction(ObjectStore::Transaction&, unsigned long, int, ThreadPool::TPHandle*)+0x37e6) [0xb9074e1666]
2017-08-31T18:53:27.164 INFO:tasks.ceph.osd.6.smithi110.stderr: 7: (FileStore::_do_transactions(std::vector<ObjectStore::Transaction, std::allocator<ObjectStore::Transaction> >&, unsigned long, ThreadPool::TPHandle*)+0x3b) [0xb9074e480b]
2017-08-31T18:53:27.164 INFO:tasks.ceph.osd.6.smithi110.stderr: 8: (FileStore::_do_op(FileStore::OpSequencer*, ThreadPool::TPHandle&)+0x671) [0xb9074e4eb1]
2017-08-31T18:53:27.164 INFO:tasks.ceph.osd.6.smithi110.stderr: 9: (ThreadPool::worker(ThreadPool::WorkThread*)+0xdb9) [0xb907739569]
2017-08-31T18:53:27.164 INFO:tasks.ceph.osd.6.smithi110.stderr: 10: (ThreadPool::WorkThread::entry()+0x10) [0xb90773a670]
2017-08-31T18:53:27.164 INFO:tasks.ceph.osd.6.smithi110.stderr: 11: (()+0x770a) [0x7f83b12e470a]
2017-08-31T18:53:27.164 INFO:tasks.ceph.osd.6.smithi110.stderr: 12: (clone()+0x6d) [0x7f83b035b82d]
</pre>
with           filestore_seek_data_hole: true

/a/sage-2017-08-31_16:29:40-rados-wip-sage-testing2-2017-08-31-0908-distro-basic-smithi/1584003

**Comment by liewegas** [comment]
@branch-predictor ping

**Comment by branch-predictor** [comment]
@liewegas maybe it's worth marking ```filestore seek map hole``` experimental until a fix is in place? It has been broken all the time...

**Comment by branch-predictor** [comment]
Closing, probably not worth fixing - I'll come up with some other PR that marks these options experimental.

**Pull request closed without merging**
