### PR TITLE
doc/cephadm/services: Update monitoring.rst to add additional templates

### PR DESCRIPTION
**Pull request by AlexonOliveiraRH**
doc/cephadm/services: Update monitoring.rst to add additional templates

The current documentation lacks a lot of other available templates as the source code here: https://github.com/ceph/ceph/tree/main/src/pybind/mgr/cephadm/templates/services
    
v2 - This updated commit fixes the j2 extensions I left in the previous one wrongly.
v3 - This updated commit changes the title as per PR's comment orientation

Signed-off-by: Alexon Oliveira <alolivei@redhat.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [x] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [x] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Comment by AlexonOliveiraRH** [comment]
@anthonyeleven closed PR 60585 and opened this one. Can you check it, please?

**Comment by anthonyeleven** [comment]
Didn't need to close, coulda edited in place.

**Review by anthonyeleven — APPROVED** [review]

**Comment by AlexonOliveiraRH** [comment]
> Didn't need to close, coulda edited in place.

I preferred to close that because I realized I didn't follow all the community steps for the contribution. This new PR is according to the community guidelines.

**Comment by anthonyeleven** [comment]
Please review https://docs.ceph.com/en/octopus/start/documenting-ceph/

The automated checks won't let this be merged unless you amend the commit message to include signed-off-by

**Comment by anthonyeleven** [comment]
Fair enough, but those can all be updated in-situ.  The PR message is easily edited via the web interface, so is the checklist.

**Comment by AlexonOliveiraRH** [comment]
> Fair enough, but those can all be updated in-situ. The PR message is easily edited via the web interface, so is the checklist.

Sure, for this on I'll do it like that. In fact, I'm checking now the commits because it's complaining about not being signed-off, but I can't find it. Both commits are signed-off.

**Comment by AlexonOliveiraRH** [comment]
`ceph dashboard cephadm e2e tests — ceph dashboard cephadm e2e tests failed`:

https://jenkins.ceph.com/job/ceph-dashboard-cephadm-e2e/13061/console

Som weird errors with the pipeline, not my commit's fault:

```
Nov 01 21:45:02 ceph-node-00 cloud-init[868]: /usr/bin/ceph: stderr Error EINVAL: unrecognized config option 'mgr/dashboard/ssl_server_port'
Nov 01 21:45:02 ceph-node-00 cloud-init[868]: RuntimeError: Failed command: /usr/bin/podman run --rm --ipc=host --stop-signal=SIGTERM --net=host --entrypoint /usr/bin/ceph --init -e CONTAINER_IMAGE=quay.ceph.io/ceph-ci/ceph:main -e NODE_NAME=ceph-node-00 -v /var/log/ceph/3f9c3002-989a-11ef-a84a-525400e2ff05:/var/log/ceph:z -v /tmp/ceph-tmp2g4yu4zl:/etc/ceph/ceph.client.admin.keyring:z -v /tmp/ceph-tmp1gsrpd5r:/etc/ceph/ceph.conf:z quay.ceph.io/ceph-ci/ceph:main config set mgr mgr/dashboard/ssl_server_port 8443: Error EINVAL: unrecognized config option 'mgr/dashboard/ssl_server_port'
Nov 01 21:45:03 ceph-node-00 cloud-init[868]:         ***************
Nov 01 21:45:03 ceph-node-00 cloud-init[868]:         Cephadm hit an issue during cluster installation. Current cluster files will be deleted automatically.
Nov 01 21:45:03 ceph-node-00 cloud-init[868]:         To disable this behaviour you can pass the --no-cleanup-on-failure flag. In case of any previous
Nov 01 21:45:03 ceph-node-00 cloud-init[868]:         broken installation, users must use the following command to completely delete the broken cluster:
Nov 01 21:45:03 ceph-node-00 cloud-init[868]:         > cephadm rm-cluster --force --zap-osds --fsid <fsid>
Nov 01 21:45:03 ceph-node-00 cloud-init[868]:         for more information please refer to https://docs.ceph.com/en/latest/cephadm/operations/#purging-a-cluster
Nov 01 21:45:03 ceph-node-00 cloud-init[868]:         ***************
Nov 01 21:45:03 ceph-node-00 cloud-init[868]: Deleting cluster with fsid: 3f9c3002-989a-11ef-a84a-525400e2ff05
Nov 01 21:45:05 ceph-node-00 cloud-init[868]: Traceback (most recent call last):
Nov 01 21:45:05 ceph-node-00 cloud-init[868]:   File "/usr/lib64/python3.10/runpy.py", line 196, in _run_module_as_main
Nov 01 21:45:05 ceph-node-00 cloud-init[868]:     return _run_code(code, main_globals, None,
Nov 01 21:45:05 ceph-node-00 cloud-init[868]:   File "/usr/lib64/python3.10/runpy.py", line 86, in _run_code
Nov 01 21:45:05 ceph-node-00 cloud-init[868]:     exec(code, run_globals)
Nov 01 21:45:05 ceph-node-00 cloud-init[868]:   File "/tmp/tmp7cvvn711.cephadm.build/app/__main__.py", line 5644, in <module>
Nov 01 21:45:05 ceph-node-00 cloud-init[868]:   File "/tmp/tmp7cvvn711.cephadm.build/app/__main__.py", line 5632, in main
Nov 01 21:45:05 ceph-node-00 cloud-init[868]:   File "/tmp/tmp7cvvn711.cephadm.build/app/__main__.py", line 2673, in _rollback
Nov 01 21:45:05 ceph-node-00 cloud-init[868]:   File "/tmp/tmp7cvvn711.cephadm.build/app/__main__.py", line 453, in _default_image
Nov 01 21:45:05 ceph-node-00 cloud-init[868]:   File "/tmp/tmp7cvvn711.cephadm.build/app/__main__.py", line 2939, in command_bootstrap
Nov 01 21:45:05 ceph-node-00 cloud-init[868]:   File "/tmp/tmp7cvvn711.cephadm.build/app/__main__.py", line 2437, in prepare_dashboard
Nov 01 21:45:05 ceph-node-00 cloud-init[868]:   File "/tmp/tmp7cvvn711.cephadm.build/app/__main__.py", line 2852, in cli
Nov 01 21:45:05 ceph-node-00 cloud-init[868]:   File "/tmp/tmp7cvvn711.cephadm.build/app/cephadmlib/container_types.py", line 430, in run
Nov 01 21:45:05 ceph-node-00 cloud-init[868]:   File "/tmp/tmp7cvvn711.cephadm.build/app/cephadmlib/call_wrappers.py", line 307, in call_throws
Nov 01 21:45:05 ceph-node-00 cloud-init[868]: RuntimeError: Failed command: /usr/bin/podman run --rm --ipc=host --stop-signal=SIGTERM --net=host --entrypoint /usr/bin/ceph --init -e CONTAINER_IMAGE=quay.ceph.io/ceph-ci/ceph:main -e NODE_NAME=ceph-node-00 -v /var/log/ceph/3f9c3002-989a-11ef-a84a-525400e2ff05:/var/log/ceph:z -v /tmp/ceph-tmp2g4yu4zl:/etc/ceph/ceph.client.admin.keyring:z -v /tmp/ceph-tmp1gsrpd5r:/etc/ceph/ceph.conf:z quay.ceph.io/ceph-ci/ceph:main config set mgr mgr/dashboard/ssl_server_port 8443: Error EINVAL: unrecognized config option 'mgr/dashboard/ssl_server_port'
```

**Comment by AlexonOliveiraRH** [comment]
@anthonyeleven anything else pending to get this approved and merged?

**Comment by anthonyeleven** [comment]
Let's trigger tests again to see if the dashboard check completes, it's weird that the Details link doesn't work as I write.

**Comment by anthonyeleven** [comment]
jenkins retest this please

**Comment by AlexonOliveiraRH** [comment]
> Let's trigger tests again to see if the dashboard check completes, it's weird that the Details link doesn't work as I write.

Now it's failing here: https://jenkins.ceph.com/job/ceph-api/85200/console

**Comment by anthonyeleven** [comment]
The test infra unfortunately can be brittle.  I'll retry later.

**Comment by AlexonOliveiraRH** [comment]
> The test infra unfortunately can be brittle. I'll retry later.

Okey dokey, I can do it too.

**Comment by anthonyeleven** [comment]
jenkins retest this please

**Comment by anthonyeleven** [comment]
Best to allow some time between triggers, as bombarding the test infra with retests can be part of the precipitate, vs being part of the solution.

**Comment by anthonyeleven** [comment]
In theory one can trigger specific tests -- expand the `Show available Jenkins commands` section to see how.

**Comment by AlexonOliveiraRH** [comment]
> Best to allow some time between triggers, as bombarding the test infra with retests can be part of the precipitate, vs being part of the solution.

ACK

**Comment by AlexonOliveiraRH** [comment]
> ceph dashboard cephadm e2e tests

Got it. Let me try the `ceph dashboard cephadm e2e tests` which is the one always failing.

**Comment by AlexonOliveiraRH** [comment]
jenkins test dashboard cephadm

**Comment by AlexonOliveiraRH** [comment]
It's always failing in the same steps:

```
Caused by: hudson.plugins.git.GitException: Error performing git command: git init /home/jenkins-build/build/workspace/ceph-dashboard-cephadm-e2e
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2864)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2768)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2763)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommand(CliGitAPIImpl.java:2052)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$5.execute(CliGitAPIImpl.java:1077)
	... 12 more
Caused by: java.io.IOException: Cannot run program "git" (in directory "/home/jenkins-build/build/workspace/ceph-dashboard-cephadm-e2e"): error=0, Failed to exec spawn helper: pid: 3567049, exit value: 1
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1143)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
	at hudson.Proc$LocalProc.<init>(Proc.java:252)
	at hudson.Proc$LocalProc.<init>(Proc.java:221)
	at hudson.Launcher$LocalLauncher.launch(Launcher.java:994)
	at hudson.Launcher$ProcStarter.start(Launcher.java:506)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2841)
	... 16 more
Caused by: java.io.IOException: error=0, Failed to exec spawn helper: pid: 3567049, exit value: 1
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:314)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:244)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1110)
	... 22 more
ERROR: Error cloning remote repo 'origin'
Retrying after 10 seconds
The recommended git tool is: git
No credentials specified
Wiping out workspace first.
Cloning the remote Git repository
Using shallow clone with depth 1
Cloning repository https://github.com/ceph/ceph.git
 > git init /home/jenkins-build/build/workspace/ceph-dashboard-cephadm-e2e # timeout=10
ERROR: Error cloning remote repo 'origin'
[...]
ERROR: Error cloning remote repo 'origin'
Archiving artifacts
Recording test results
ERROR: Step ‘Publish JUnit test result report’ failed: No test report files were found. Configuration error?
[PostBuildScript] - [INFO] Executing post build scripts.
[ceph-dashboard-cephadm-e2e] $ /bin/sh -xe /tmp/jenkins10152442899890940875.sh
FATAL: command execution failed
java.io.IOException: error=0, Failed to exec spawn helper: pid: 3567057, exit value: 1
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:314)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:244)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1110)
Also:   hudson.remoting.Channel$CallSiteStackTrace: Remote call to JNLP4-connect connection from 8.43.84.3/8.43.84.3:38282
		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1923)
		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:384)
		at hudson.remoting.Channel.call(Channel.java:1112)
		at hudson.Launcher$RemoteLauncher.launch(Launcher.java:1121)
		at hudson.Launcher$2.launch(Launcher.java:942)
		at hudson.Launcher$ProcStarter.start(Launcher.java:506)
		at hudson.tasks.CommandInterpreter.perform(CommandInterpreter.java:144)
		at hudson.tasks.CommandInterpreter.perform(CommandInterpreter.java:92)
		at PluginClassLoader for postbuildscript//org.jenkinsci.plugins.postbuildscript.processor.Processor.processBuildSteps(Processor.java:178)
		at PluginClassLoader for postbuildscript//org.jenkinsci.plugins.postbuildscript.processor.Processor.processScripts(Processor.java:90)
		at PluginClassLoader for postbuildscript//org.jenkinsci.plugins.postbuildscript.processor.Processor.process(Processor.java:78)
		at PluginClassLoader for postbuildscript//org.jenkinsci.plugins.postbuildscript.processor.Processor.process(Processor.java:72)
		at PluginClassLoader for postbuildscript//org.jenkinsci.plugins.postbuildscript.PostBuildScript.perform(PostBuildScript.java:76)
		at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
		at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:818)
		at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:767)
		at hudson.model.Build$BuildExecution.post2(Build.java:179)
		at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:711)
		at hudson.model.Run.execute(Run.java:1854)
		at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:44)
		at hudson.model.ResourceController.execute(ResourceController.java:101)
		at hudson.model.Executor.run(Executor.java:445)
Caused: java.io.IOException: Cannot run program "/bin/sh" (in directory "/home/jenkins-build/build/workspace/ceph-dashboard-cephadm-e2e"): error=0, Failed to exec spawn helper: pid: 3567057, exit value: 1
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1143)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
	at hudson.Proc$LocalProc.<init>(Proc.java:252)
	at hudson.Proc$LocalProc.<init>(Proc.java:221)
	at hudson.Launcher$LocalLauncher.launch(Launcher.java:994)
	at hudson.Launcher$ProcStarter.start(Launcher.java:506)
	at hudson.Launcher$RemoteLaunchCallable.call(Launcher.java:1395)
	at hudson.Launcher$RemoteLaunchCallable.call(Launcher.java:1337)
	at hudson.remoting.UserRequest.perform(UserRequest.java:211)
	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
	at hudson.remoting.Request$2.run(Request.java:377)
	at hudson.remoting.InterceptingExecutorService.lambda$wrap$0(InterceptingExecutorService.java:78)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at hudson.remoting.Engine$1.lambda$newThread$0(Engine.java:125)
	at java.base/java.lang.Thread.run(Thread.java:840)
Build step 'Execute scripts' marked build as failure
Setting status of aee484425f7bcff0f18188032f99e14caed227cb to FAILURE with url https://jenkins.ceph.com/job/ceph-dashboard-cephadm-e2e/13219/ and message: 'ceph dashboard cephadm e2e tests failed
 '
Using context: ceph dashboard cephadm e2e tests
Finished: FAILURE
```

**Comment by anthonyeleven** [comment]
Aye.  In this case it passed the other checks and as a doc-only PR I think we're okay to merge as the dashboard e2e test is not related.

**Pull request merged**
