### PR TITLE
 rgw: fix list op raced with put op maybe cause index delete

### PR DESCRIPTION
**Pull request by tianshan**
Fixes: http://tracker.ceph.com/issues/24744

Signed-off-by: Tianshan Qu <tianshan@xsky.com>

- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by tianshan** [comment]
@ivancich the left work from https://github.com/ceph/ceph/pull/22798

**Comment by ivancich** [comment]
refresh this

**Comment by IlsooByun** [comment]
Why do you check pending_map inside of the class method which is executed in a OSD. Would it be a problem to check before sending suggestions in the check_disk_state method in rgw_rados.cc?

**Comment by IlsooByun** [comment]
Is there any possibility that put op completes for the time between dispatch and arrival of suggestion request? If so, I think there is still a chance to race between list_op and put_op.

**Comment by theanalyst** [comment]
tests are broken after https://github.com/ceph/ceph/pull/15183, please rebase on current master

**Comment by tianshan** [comment]
@theanalyst  rebase done

**Comment by tianshan** [comment]
> Why do you check pending_map inside of the class method which is executed in a OSD. Would it be a problem to check before sending suggestions in the check_disk_state method in rgw_rados.cc?

Sorry for late reply.  Check in rgw_rados will have consistency issue. The pending state may change by other process after read from osd.

> Is there any possibility that put op completes for the time between dispatch and arrival of suggestion request? If so, I think there is still a chance to race between list_op and put_op.

Put the check in OSD is just ensure no middle state, since OSD process op one by one.

**Comment by tianshan** [comment]
@IlsooByun sorry for late reply.
> Why do you check pending_map inside of the class method which is executed in a OSD. Would it be a problem to check before sending suggestions in the check_disk_state method in rgw_rados.cc?

Check in rgw_rados will have consistency issue. The pending state may change by other process after read from osd.

> Is there any possibility that put op completes for the time between dispatch and arrival of suggestion request? If so, I think there is still a chance to race between list_op and put_op.

Put the check in OSD is just ensure no middle state, since OSD process op one by one.

**Comment by ivancich** [comment]
jenkins test make check

**Comment by ivancich** [comment]
I copied this commit to a different PR so I could add a fix for a changing API.

Now at: https://github.com/ceph/ceph/pull/41978

**Pull request closed without merging**
