### PR TITLE
nautilus: restful: Query nodes_by_id for items

### PR DESCRIPTION
**Pull request by b-ranto**
This is a nautilus back-port of https://github.com/ceph/ceph/pull/31153.

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`

</details>

### CODE REVIEW

**Comment by b-ranto** [comment]
jenkins test make check

**Comment by badone** [comment]
Backport tracker, https://tracker.ceph.com/issues/42574

**Comment by b-ranto** [comment]
We should probably merge this too now that mimic and luminous back-ports were merged.

**Comment by badone** [comment]
@b-ranto still needs QA

**Comment by yuriw** [comment]
[wip-yuri8-testing-2019-11-16-2138-nautilus](https://trello.com/c/2l18BM3z/765-wip-yuri8-testing-2019-11-16-2138-nautilus)

**Pull request merged**
