### PR TITLE
test: fix ceph_test_cls_hello test

### PR DESCRIPTION
**Pull request by tchaikov**
add the missing stub for cls_register_cxx_filter() call

Signed-off-by: Kefu Chai <kchai@redhat.com>

### CODE REVIEW

**Comment by liewegas** [comment]
it would be awesome if a make check test compiled the example code

**Comment by tchaikov** [comment]
this also fixes
```
unittest_librbd --gtest_filter=TestMockObjectWatcher.Success
```

**Comment by tchaikov** [comment]
@dillaman would you please take a look? quite a few jenkins test failures are caused by this problem, i believe.

**Comment by tchaikov** [comment]
the test failures are unrelated.

**Comment by tchaikov** [comment]
rebased against master.

**Comment by dillaman** [comment]
lgtm -- in regards to test failures, do you have an example? I haven't seen any failures (expect unittest_log on any rbd PRs).

**Comment by tchaikov** [comment]
@dillaman sorry, it was 5 days ago, and i recall that's how i noticed this issue. and i can hardly find any example now. next time, i will note it down in the comment so we can check later.

**Pull request merged**
