### PR TITLE
OSD:cleanup a judgment in PG.cc

### PR DESCRIPTION
**Pull request by HeyoQiang**
It looks tedious, and I would like to modify it to be more concise.

Signed-off-by: Yongqiang He <he.yongqiang@h3c.com>

### CODE REVIEW

**Comment by cxwshawn** [comment]
@HeyoQiang two unrelated commits, otherwise lgtm .

**Comment by HeyoQiang** [comment]
@cxwshawn  I have done it. Thanks!

**Comment by tchaikov** [comment]
@HeyoQiang could you elaborate a little bit in your commit message why we should change this piece of code?

**Comment by HeyoQiang** [comment]
@tchaikov It looks tedious, and I would like to modify it to be more concise.

**Comment by tchaikov** [comment]
@HeyoQiang i mean, other developers could have more context about your change if you could put it into your *commit message* if your change is merged.

imho, i think it's okay either way: with/without your refactory. it consolidates the condition statements at the expense of increasing the nesting level of the if blocks.

**Comment by HeyoQiang** [comment]
@tchaikov I have changed the commit message. Thanks！

**Comment by HeyoQiang** [comment]
@tchaikov I just changed it to conform our  regular tendency，and it does not affect the expansion.

**Comment by dzafman** [comment]
I wouldn't merge this change since the improvement is so slight.  If this code were being modified for other reasons, that is when someone might do this.

**Comment by tchaikov** [comment]
@HeyoQiang i tend to agree with @dzafman. closing it.

**Pull request closed without merging**
