### PR TITLE
rgw: fix delete tags failed for latest version object

### PR DESCRIPTION
**Pull request by Rjerk**
Signed-off-by: Liu Lan <liulan_yewu@cmss.chinamobile.com>

failed to delete the latest version object's tags in versioning enabled bucket.

```
# tags are not removed without specifying version
client.delete_object_tagging(Bucket=bucket_name, Key=key)

# success
client.delete_object_tagging(Bucket=bucket_name, Key=key, VersionId=version)
```

Also add these to [s3-tests](https://github.com/ceph/s3-tests/pull/372).

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by dang** [comment]
Could you explain why we have to get the attributes before we set them?  The set is just doing a remove of specific attributes, the attrs we got are never used anywhere in the callchain, I don't think.

**Comment by Rjerk** [comment]
I intend to get the object's instance instead of attrs before setting it. @dang

**Comment by Rjerk** [comment]
jenkins test api

**Comment by Rjerk** [comment]
jenkins retest this please

**Comment by Rjerk** [comment]
jenkins retest this please

**Review by dang — APPROVED** [review]
Okay, this works, but we'll have to find a better way to get the instance for an object.

**Comment by Rjerk** [comment]
rebase is done, any pieces of advice?

**Pull request closed without merging**
