### PR TITLE
common: Various optimizations

### PR DESCRIPTION
**Pull request by MaxKellermann**
common-specific parts of https://github.com/ceph/ceph/pull/60175 (split upon @batrick's request)

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [X] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [X] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [X] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [X] No tests

### CODE REVIEW

**Review by batrick — APPROVED** [review]

**Comment by batrick** [comment]
```
/home/jenkins-build/build/workspace/ceph-pull-requests/src/common/config.cc:136:7: error: no matching constructor for initialization of 'Option'
      Option(name, Option::TYPE_STR, Option::LEVEL_ADVANCED));
      ^      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by MaxKellermann** [comment]
Whoops, sorry, this happened when I moved the patch over to the "main" branch (same with the build failure in the other PR). I guess I forgot to build "main" after the move. (We're using Reef, so I develop and test everything on that branch and only move it over for upstream submission.)

**Review by batrick — APPROVED** [review]

**Comment by batrick** [comment]
This PR is under test in [https://tracker.ceph.com/issues/68629](https://tracker.ceph.com/issues/68629).

**Comment by batrick** [comment]
https://tracker.ceph.com/issues/68629#note-1

**Pull request merged**
