### PR TITLE
pacific: mgr: Add one finisher thread per module

### PR DESCRIPTION
**Pull request by kotreshhr**
backport tracker: https://tracker.ceph.com/issues/59417

---
Added following dependent qa commits from main branch:
   1. 8114bdd964d5a442802ed120c851ff8028bc6baa
   2. d8ec1bd8e65542d2fb8ccf6103ce3b2768d1551b
   
backport of https://github.com/ceph/ceph/pull/47893
parent tracker: https://tracker.ceph.com/issues/51177

this backport was staged using ceph-backport.sh version 16.0.0.6848
find the latest version at https://github.com/ceph/ceph/blob/main/src/script/ceph-backport.sh

### CODE REVIEW

**Review by badone — APPROVED** [review]
I don't see why this shouldn't go into pacific since it's gone in the other releases without issue so far.

**Comment by ljflores** [comment]
Hey @kotreshhr, there was a related failure:
/a/yuriw-2023-07-19_14:33:14-rados-wip-yuri11-testing-2023-07-18-0927-pacific-distro-default-smithi/7343716
```
2023-07-19T20:24:01.465 INFO:tasks.workunit.client.0.smithi062.stderr:+ ceph telemetry diff
...
2023-07-19T20:24:01.794 INFO:tasks.workunit.client.0.smithi062.stderr:no valid command found; 7 closest matches:
2023-07-19T20:24:01.794 INFO:tasks.workunit.client.0.smithi062.stderr:telemetry status
2023-07-19T20:24:01.794 INFO:tasks.workunit.client.0.smithi062.stderr:telemetry send [ceph|device...] [<license>]
2023-07-19T20:24:01.794 INFO:tasks.workunit.client.0.smithi062.stderr:telemetry show [<channels>...]
2023-07-19T20:24:01.794 INFO:tasks.workunit.client.0.smithi062.stderr:telemetry show-device
2023-07-19T20:24:01.794 INFO:tasks.workunit.client.0.smithi062.stderr:telemetry show-all
2023-07-19T20:24:01.795 INFO:tasks.workunit.client.0.smithi062.stderr:telemetry on [<license>]
2023-07-19T20:24:01.795 INFO:tasks.workunit.client.0.smithi062.stderr:telemetry off
2023-07-19T20:24:01.795 INFO:tasks.workunit.client.0.smithi062.stderr:Error EINVAL: invalid command
2023-07-19T20:24:01.796 DEBUG:teuthology.orchestra.run:got remote process result: 22
2023-07-19T20:24:01.797 INFO:tasks.workunit:Stopping ['mgr/test_per_module_finisher.sh'] on client.0...
```

It's because there's no `telemetry diff` command in pacific.

**Comment by ljflores** [comment]
Please re-add the needs-qa label when you want it tested again.

**Comment by kotreshhr** [comment]
> Please re-add the needs-qa label when you want it tested again.

Fixed and added needs-qa label.

**Comment by batrick** [comment]
https://tracker.ceph.com/projects/cephfs/wiki/Pacific#2023-August-31

Need to schedule a `rados` run as well.

**Comment by batrick** [comment]
@yuriw kindly scheduled his usual `rados` run for this PR:

https://pulpito.ceph.com/yuriw-2023-09-01_19:14:47-rados-wip-batrick-testing-20230831.124848-pacific-distro-default-smithi/

@ljflores please have a look when it completes.

**Review by vshankar — APPROVED** [review]

**Comment by ljflores** [comment]
Rados approved: https://tracker.ceph.com/projects/rados/wiki/PACIFIC#Individual-testing-for-httpsgithubcomcephcephpull51045

LGTM @batrick !

**Comment by batrick** [comment]
> Rados approved: https://tracker.ceph.com/projects/rados/wiki/PACIFIC#Individual-testing-for-httpsgithubcomcephcephpull51045
> 
> LGTM @batrick !

TY!

**Pull request merged**
