### PR TITLE
doc/release-notes: final infernalis notes

### PR DESCRIPTION
**Pull request by liewegas**
Signed-off-by: Sage Weil <sage@redhat.com>

### CODE REVIEW

**Comment by smithfarm** [comment]
`Reviewed-by: Nathan Cutler <ncutler@suse.com>`

**Comment by smithfarm** [comment]
@liewegas If you'd like, you can merge this as-is and I will open a PR with the fixes.

**Comment by liewegas** [comment]
> @liewegas If you'd like, you can merge this as-is and I will open a PR with the fixes.

I'd rather not merge until the release is cut.  Can you do a PR with teh 
fixups against my branch?

thanks!

**Comment by smithfarm** [comment]
@liewegas Sorry, I have been severely distracted lately.

**Comment by liewegas** [comment]
no worries, thanks for the edits (and congrats on the release!)

**Pull request closed without merging**
