### PR TITLE
nautilus: rbd: librbd: ensure that thread pool lock is held when processing throttled IOs

### PR DESCRIPTION
**Pull request by smithfarm**
backport tracker: https://tracker.ceph.com/issues/48040

---

backport of https://github.com/ceph/ceph/pull/37116
parent tracker: https://tracker.ceph.com/issues/47371

this backport was staged using ceph-backport.sh version 15.1.1.389
find the latest version at https://github.com/ceph/ceph/blob/master/src/script/ceph-backport.sh

### CODE REVIEW

**Review by dillaman — APPROVED** [review]
:+1:

**Comment by smithfarm** [comment]
jenkins test make check

**Comment by smithfarm** [comment]
```
In file included from /home/jenkins-build/build/workspace/ceph-pull-requests/src/test/librbd/io/test_mock_ImageRequestWQ.cc:147:
/home/jenkins-build/build/workspace/ceph-pull-requests/src/librbd/io/ImageRequestWQ.cc: In instantiation of 'void librbd::io::ImageRequestWQ< <template-parameter-1-1> >::handle_throttle_ready(int, librbd::io::ImageDispatchSpec<ImageCtxT>*, uint64_t) [with ImageCtxT = librbd::{anonymous}::MockTestImageCtx; uint64_t = long unsigned int]':
/home/jenkins-build/build/workspace/ceph-pull-requests/src/librbd/io/ImageRequestWQ.cc:768:8:   required from 'bool librbd::io::ImageRequestWQ< <template-parameter-1-1> >::needs_throttle(librbd::io::ImageDispatchSpec<ImageCtxT>*) [with ImageCtxT = librbd::{anonymous}::MockTestImageCtx]'
/home/jenkins-build/build/workspace/ceph-pull-requests/src/librbd/io/ImageRequestWQ.cc:788:7:   required from 'void* librbd::io::ImageRequestWQ< <template-parameter-1-1> >::_void_dequeue() [with ImageCtxT = librbd::{anonymous}::MockTestImageCtx]'
/home/jenkins-build/build/workspace/ceph-pull-requests/src/librbd/io/ImageRequestWQ.cc:779:7:   required from here
/home/jenkins-build/build/workspace/ceph-pull-requests/src/librbd/io/ImageRequestWQ.cc:742:24: error: cannot convert 'std::lock_guard<Mutex>' to 'testing::internal::Function<void(const std::lock_guard<ceph::mutex_debug_detail::mutex_debug_impl<false> >&)>::Argument1' {aka 'const std::lock_guard<ceph::mutex_debug_detail::mutex_debug_impl<false> >&'}
  742 |     this->requeue_back(pool_locker, item);
      |                        ^~~~~~~~~~~
      |                        |
      |                        std::lock_guard<Mutex>
In file included from /home/jenkins-build/build/workspace/ceph-pull-requests/src/googletest/googlemock/include/gmock/gmock.h:61,
                 from /home/jenkins-build/build/workspace/ceph-pull-requests/src/test/librbd/mock/MockContextWQ.h:7,
                 from /home/jenkins-build/build/workspace/ceph-pull-requests/src/test/librbd/mock/MockImageCtx.h:8,
                 from /home/jenkins-build/build/workspace/ceph-pull-requests/src/test/librbd/test_mock_fixture.h:8,
                 from /home/jenkins-build/build/workspace/ceph-pull-requests/src/test/librbd/io/test_mock_ImageRequestWQ.cc:4:
/home/jenkins-build/build/workspace/ceph-pull-requests/src/googletest/googlemock/include/gmock/gmock-generated-function-mockers.h:396:38: note:   initializing argument 1 of 'testing::internal::Function<void()>::Result ThreadPool::PointerWQ<librbd::io::ImageDispatchSpec<librbd::{anonymous}::MockTestImageCtx> >::requeue_back(testing::internal::Function<void(const std::lock_guard<ceph::mutex_debug_detail::mutex_debug_impl<false> >&)>::Argument1, testing::internal::Function<void(const std::lock_guard<ceph::mutex_debug_detail::mutex_debug_impl<false> >&, librbd::io::ImageDispatchSpec<librbd::{anonymous}::MockTestImageCtx>*)>::Argument2)'
  396 |       GMOCK_ARG_(tn, 1, __VA_ARGS__) gmock_a1, \
      |                                      ^
/home/jenkins-build/build/workspace/ceph-pull-requests/src/googletest/googlemock/include/gmock/gmock-generated-function-mockers.h:396:38: note: in definition of macro 'GMOCK_METHOD2_'
  396 |       GMOCK_ARG_(tn, 1, __VA_ARGS__) gmock_a1, \
      |                                      ^~~~~~~~
/home/jenkins-build/build/workspace/ceph-pull-requests/src/test/librbd/io/test_mock_ImageRequestWQ.cc:109:3: note: in expansion of macro 'MOCK_METHOD2'
  109 |   MOCK_METHOD2(requeue_back, void(const std::lock_guard<ceph::mutex>&,
      |   ^~~~~~~~~~~~
In file included from /home/jenkins-build/build/workspace/ceph-pull-requests/src/test/librbd/io/test_mock_ImageRequestWQ.cc:147:
/home/jenkins-build/build/workspace/ceph-pull-requests/src/librbd/io/ImageRequestWQ.cc:744:5: error: no matching function for call to 'librbd::io::ImageRequestWQ<librbd::{anonymous}::MockTestImageCtx>::signal(std::lock_guard<Mutex>&)'
  744 |     this->signal(pool_locker);
      |     ^~~~
In file included from /home/jenkins-build/build/workspace/ceph-pull-requests/src/googletest/googlemock/include/gmock/gmock.h:61,
                 from /home/jenkins-build/build/workspace/ceph-pull-requests/src/test/librbd/mock/MockContextWQ.h:7,
                 from /home/jenkins-build/build/workspace/ceph-pull-requests/src/test/librbd/mock/MockImageCtx.h:8,
                 from /home/jenkins-build/build/workspace/ceph-pull-requests/src/test/librbd/test_mock_fixture.h:8,
                 from /home/jenkins-build/build/workspace/ceph-pull-requests/src/test/librbd/io/test_mock_ImageRequestWQ.cc:4:
/home/jenkins-build/build/workspace/ceph-pull-requests/src/test/librbd/io/test_mock_ImageRequestWQ.cc:103:16: note: candidate: 'testing::internal::Function<void()>::Result ThreadPool::PointerWQ<librbd::io::ImageDispatchSpec<librbd::{anonymous}::MockTestImageCtx> >::signal()'
  103 |   MOCK_METHOD0(signal, void());
      |                ^~~~~~
/home/jenkins-build/build/workspace/ceph-pull-requests/src/googletest/googlemock/include/gmock/gmock-generated-function-mockers.h:357:37: note: in definition of macro 'GMOCK_METHOD0_'
  357 |   GMOCK_RESULT_(tn, __VA_ARGS__) ct Method( \
      |                                     ^~~~~~
/home/jenkins-build/build/workspace/ceph-pull-requests/src/test/librbd/io/test_mock_ImageRequestWQ.cc:103:3: note: in expansion of macro 'MOCK_METHOD0'
  103 |   MOCK_METHOD0(signal, void());
      |   ^~~~~~~~~~~~
/home/jenkins-build/build/workspace/ceph-pull-requests/src/test/librbd/io/test_mock_ImageRequestWQ.cc:103:16: note:   candidate expects 0 arguments, 1 provided
  103 |   MOCK_METHOD0(signal, void());
      |                ^~~~~~
/home/jenkins-build/build/workspace/ceph-pull-requests/src/googletest/googlemock/include/gmock/gmock-generated-function-mockers.h:357:37: note: in definition of macro 'GMOCK_METHOD0_'
  357 |   GMOCK_RESULT_(tn, __VA_ARGS__) ct Method( \
      |                                     ^~~~~~
/home/jenkins-build/build/workspace/ceph-pull-requests/src/test/librbd/io/test_mock_ImageRequestWQ.cc:103:3: note: in expansion of macro 'MOCK_METHOD0'
  103 |   MOCK_METHOD0(signal, void());
      |   ^~~~~~~~~~~~
/home/jenkins-build/build/workspace/ceph-pull-requests/src/test/librbd/io/test_mock_ImageRequestWQ.cc:104:16: note: candidate: 'testing::internal::Function<void()>::Result ThreadPool::PointerWQ<librbd::io::ImageDispatchSpec<librbd::{anonymous}::MockTestImageCtx> >::signal(testing::internal::Function<void(const std::lock_guard<ceph::mutex_debug_detail::mutex_debug_impl<false> >&)>::Argument1)'
  104 |   MOCK_METHOD1(signal, void(const std::lock_guard<ceph::mutex>&));
      |                ^~~~~~
/home/jenkins-build/build/workspace/ceph-pull-requests/src/googletest/googlemock/include/gmock/gmock-generated-function-mockers.h:376:37: note: in definition of macro 'GMOCK_METHOD1_'
  376 |   GMOCK_RESULT_(tn, __VA_ARGS__) ct Method( \
      |                                     ^~~~~~
/home/jenkins-build/build/workspace/ceph-pull-requests/src/test/librbd/io/test_mock_ImageRequestWQ.cc:104:3: note: in expansion of macro 'MOCK_METHOD1'
  104 |   MOCK_METHOD1(signal, void(const std::lock_guard<ceph::mutex>&));
      |   ^~~~~~~~~~~~
/home/jenkins-build/build/workspace/ceph-pull-requests/src/googletest/googlemock/include/gmock/gmock-generated-function-mockers.h:377:38: note:   no known conversion for argument 1 from 'std::lock_guard<Mutex>' to 'testing::internal::Function<void(const std::lock_guard<ceph::mutex_debug_detail::mutex_debug_impl<false> >&)>::Argument1' {aka 'const std::lock_guard<ceph::mutex_debug_detail::mutex_debug_impl<false> >&'}
  377 |       GMOCK_ARG_(tn, 1, __VA_ARGS__) gmock_a1) constness { \
      |                                      ^
/home/jenkins-build/build/workspace/ceph-pull-requests/src/googletest/googlemock/include/gmock/gmock-generated-function-mockers.h:377:38: note: in definition of macro 'GMOCK_METHOD1_'
  377 |       GMOCK_ARG_(tn, 1, __VA_ARGS__) gmock_a1) constness { \
      |                                      ^~~~~~~~
/home/jenkins-build/build/workspace/ceph-pull-requests/src/test/librbd/io/test_mock_ImageRequestWQ.cc:104:3: note: in expansion of macro 'MOCK_METHOD1'
  104 |   MOCK_METHOD1(signal, void(const std::lock_guard<ceph::mutex>&));
      |   ^~~~~~~~~~~~
src/test/librbd/CMakeFiles/unittest_librbd.dir/build.make:806: recipe for target 'src/test/librbd/CMakeFiles/unittest_librbd.dir/io/test_mock_ImageRequestWQ.cc.o' failed
make[3]: *** [src/test/librbd/CMakeFiles/unittest_librbd.dir/io/test_mock_ImageRequestWQ.cc.o] Error 1
```

**Comment by smithfarm** [comment]
@dillaman Something more is needed (see the previous comment), but what?

**Comment by dillaman** [comment]
@smithfarm Looks like in Octopus, commit 792d6c53fedc695199cc18916347c1b545fe42c2 did a global replace of `Mutex` to `ceph::mutex`, so to fix this for Nautilus, we just need to do that in `test_mock_ImageRequestWQ.cc` since the `get_pool_lock()` method is returning a `Mutex` instead of a `ceph::mutex`

**Comment by smithfarm** [comment]
@dillaman Right on!

**Pull request merged**
