### PR TITLE
jewel: Session::check_access() is buggy

### PR DESCRIPTION
**Pull request by xiaoxichen**
http://tracker.ceph.com/issues/16515

### CODE REVIEW

**Comment by dachary** [comment]
@xiaoxichen I'm setting milestone jewel since this is targeting jewel really. If that's a mistake please let me know.

**Comment by dachary** [comment]
Hey jenkins, test this please !

**Comment by dachary** [comment]
@gregsfortytwo does this backport look good to merge ? It passed the fs suite http://tracker.ceph.com/issues/16344#note-21 (except for unrelated valgrind failures and one transient failure that is, I believe, unrelated ).

**Comment by gregsfortytwo** [comment]
Yep, looks good to me @dachary!

**Pull request merged**
