### PR TITLE
luminous: ceph_volume_client: perform snapshot operations in

### PR DESCRIPTION
**Pull request by batrick**
http://tracker.ceph.com/issues/21514

### CODE REVIEW

**Comment by batrick** [comment]
Delaying until after 12.2.1.

**Comment by theanalyst** [comment]
This passed a teuthology run at http://tracker.ceph.com/issues/21830#FS and will be merged when approved

**Comment by ajarr** [comment]
@batrick, I'm unable to approve this change. It's a simple fix, and has been in review for a while. Can you please move this along?

**Comment by batrick** [comment]
Ramana, you can also just a comment and my script will pick up your review (but I realize that won't help with the "Review Required" github barrier)

`Reviewed-by: Ramana ...`

**Pull request merged**
