### PR TITLE
nautilus: mgr/devicehealth: do not scrape mon devices

### PR DESCRIPTION
**Pull request by liewegas**
Disable this feature for nautilus because the tell mechanism for mons is
not reliable.  It works in master (octopus), so only disable this in
the nautilus branch.

This (hopefully!) avoids problems with a hanging mgr that seem to occur
right when devicehealth is trying to scrape mon devices.

Signed-off-by: Sage Weil <sage@redhat.com>

### CODE REVIEW

**Comment by liewegas** [comment]
User Oliver Freyermuth on ceph-users has confirmed this fixes the problem for his cluster.

**Comment by neha-ojha** [comment]
> User Oliver Freyermuth on ceph-users has confirmed this fixes the problem for his cluster.

linking the discussion https://www.spinics.net/lists/ceph-users/msg56484.html

**Comment by smithfarm** [comment]
jenkins test make check

**Comment by smithfarm** [comment]
This appears to break one of the unit tests:

```
106/172 Test   #5: run-tox-mgr-dashboard ...................***Failed  148.54 sec
```

**Pull request merged**
