### PR TITLE
rgw/multisite: error repo coroutines store raw_obj by value

### PR DESCRIPTION
**Pull request by cbodley**
RGWErrorRepoWriteCR/RGWErrorRepoRemoveCR need to copy their rgw_raw_obj arguments to extend the lifetimes until send_request() is called

potential regression from https://github.com/ceph/ceph/pull/50359

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Review by smanjara — APPROVED** [review]

**Comment by cbodley** [comment]
passed qa in https://pulpito.ceph.com/cbodley-2023-12-14_02:11:26-rgw-wip-cbodley-testing-distro-default-smithi/ after reruns https://pulpito.ceph.com/cbodley-2023-12-14_20:15:48-rgw-wip-cbodley-testing-distro-default-smithi/ and https://pulpito.ceph.com/cbodley-2023-12-15_01:06:56-rgw-wip-cbodley-testing-distro-default-smithi/

the multisite jobs had crashes, but they looked like the earlier ones from https://tracker.ceph.com/issues/63378

**Comment by cbodley** [comment]
jenkins test make check

**Comment by smanjara** [comment]
> passed qa in https://pulpito.ceph.com/cbodley-2023-12-14_02:11:26-rgw-wip-cbodley-testing-distro-default-smithi/ after reruns https://pulpito.ceph.com/cbodley-2023-12-14_20:15:48-rgw-wip-cbodley-testing-distro-default-smithi/ and https://pulpito.ceph.com/cbodley-2023-12-15_01:06:56-rgw-wip-cbodley-testing-distro-default-smithi/
> 
> the multisite jobs had crashes, but they looked like the earlier ones from https://tracker.ceph.com/issues/63378

thanks. will look

**Comment by cbodley** [comment]
jenkins test make check

**Pull request merged**
