### PR TITLE
quincy: mgr/telemetry: add Rook data

### PR DESCRIPTION
**Pull request by yaarith**
backport tracker: https://tracker.ceph.com/issues/55816

---------

backport of https://github.com/ceph/ceph/pull/46483
parent tracker: https://tracker.ceph.com/issues/55740

### CODE REVIEW

**Review by ljflores — APPROVED** [review]
I'm seeing the make check error on other Quincy PRs. This is likely due to the "master" --> "main" change that David is currently handling.

```
 error: pathspec 'master' did not match any file(s) known to git
```

**Comment by yaarith** [comment]
jenkins test make check

**Comment by ljflores** [comment]
Rados suite results:

http://pulpito.front.sepia.ceph.com/yuriw-2022-06-01_23:21:01-rados-wip-yuri3-testing-2022-06-01-1035-quincy-distro-default-smithi/
http://pulpito.front.sepia.ceph.com/yuriw-2022-06-02_14:59:52-rados-wip-yuri3-testing-2022-06-01-1035-quincy-distro-default-smithi/

Job 6859508 failed due to a "Health check failed: Reduced data availability: 1 pg peering (PG_AVAILABILITY)" message in the cluster log. I am still checking to see where this is tracked, but in any case, it is not related to this PR.

All other failures, unrelated, are tracked by:
    1. https://tracker.ceph.com/issues/52321
    2. https://tracker.ceph.com/issues/55741
    3. https://tracker.ceph.com/issues/55838 --> opened a new Tracker for this; it is unrelated to the PR tested in this run.

Details:
    1. qa/tasks/rook times out: 'check osd count' reached maximum tries (90) after waiting for 900 seconds - Ceph - Orchestrator - Ceph - Orchestrator
    2. cephadm/test_dashboard_e2e.sh: Unable to find element `cd-modal .custom-control-label` when testing on orchestrator/01-hosts.e2e-spec.ts - Ceph - Mgr - Dashboard
    3. cephadm/osds: Exception with "test -s /home/ubuntu/cephtest/cephadm && test $(stat -c%s /home/ubuntu/cephtest/cephadm) -gt 1000 && chmod +x /home/ubuntu/cephtest/cephadm" - Ceph - Orchestrator

**Comment by ljflores** [comment]
Let's hold off on merging this until the main PR has been merged.

**Comment by ljflores** [comment]
The main PR has been rados approved. As soon as it merges, we can merge this one!

**Pull request merged**
