### PR TITLE
kraken: rgw: rgw_file: FHCache residence check should be exhaustive

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/19144
http://tracker.ceph.com/issues/19723
http://tracker.ceph.com/issues/20195

### CODE REVIEW

**Comment by smithfarm** [comment]
Jenkins retest this please (logs gone)

**Comment by smithfarm** [comment]
```
In file included from /home/jenkins-build/build/workspace/ceph-pull-requests/src/rgw/rgw_os_lib.cc:8:0:
/home/jenkins-build/build/workspace/ceph-pull-requests/src/rgw/rgw_file.h: In member function ‘rgw::LookupFHResult rgw::RGWLibFS::lookup_fh(const rgw::fh_key&, uint32_t)’:
/home/jenkins-build/build/workspace/ceph-pull-requests/src/rgw/rgw_file.h:897:20: error: cannot bind ‘std::basic_ostream<char>’ lvalue to ‘std::basic_ostream<char>&&’
        << __func__ << " 1 " << *fh
                    ^
In file included from /usr/include/c++/4.8/iterator:64:0,
                 from /home/jenkins-build/build/workspace/ceph-pull-requests/build/boost/include/boost/utility/string_ref.hpp:26,
                 from /home/jenkins-build/build/workspace/ceph-pull-requests/src/rgw/rgw_rest.h:9,
                 from /home/jenkins-build/build/workspace/ceph-pull-requests/src/rgw/rgw_os_lib.cc:4:
/usr/include/c++/4.8/ostream:602:5: error:   initializing argument 1 of ‘std::basic_ostream<_CharT, _Traits>& std::operator<<(std::basic_ostream<_CharT, _Traits>&&, const _Tp&) [with _CharT = char; _Traits = std::char_traits<char>; _Tp = rgw::RGWFileHandle]’
     operator<<(basic_ostream<_CharT, _Traits>&& __os, const _Tp& __x)
     ^
In file included from /home/jenkins-build/build/workspace/ceph-pull-requests/src/rgw/rgw_os_lib.cc:8:0:
/home/jenkins-build/build/workspace/ceph-pull-requests/src/rgw/rgw_file.h: In member function ‘rgw::LookupFHResult rgw::RGWLibFS::lookup_fh(rgw::RGWFileHandle*, const char*, uint32_t)’:
/home/jenkins-build/build/workspace/ceph-pull-requests/src/rgw/rgw_file.h:980:20: error: cannot bind ‘std::basic_ostream<char>’ lvalue to ‘std::basic_ostream<char>&&’
        << __func__ << " 2 " << *fh
                    ^
In file included from /usr/include/c++/4.8/iterator:64:0,
                 from /home/jenkins-build/build/workspace/ceph-pull-requests/build/boost/include/boost/utility/string_ref.hpp:26,
                 from /home/jenkins-build/build/workspace/ceph-pull-requests/src/rgw/rgw_rest.h:9,
                 from /home/jenkins-build/build/workspace/ceph-pull-requests/src/rgw/rgw_os_lib.cc:4:
/usr/include/c++/4.8/ostream:602:5: error:   initializing argument 1 of ‘std::basic_ostream<_CharT, _Traits>& std::operator<<(std::basic_ostream<_CharT, _Traits>&&, const _Tp&) [with _CharT = char; _Traits = std::char_traits<char>; _Tp = rgw::RGWFileHandle]’
     operator<<(basic_ostream<_CharT, _Traits>&& __os, const _Tp& __x)
     ^
[ 83%] Building CXX object src/rgw/CMakeFiles/rgw_a.dir/rgw_process.cc.o
make[3]: *** [src/rgw/CMakeFiles/rgw_a.dir/rgw_os_lib.cc.o] Error 1
```

@mattbenjamin: Whelp!

**Comment by mattbenjamin** [comment]
@will test build...

**Comment by mattbenjamin** [comment]
@smithfarm the handle print requires having merged 1d6c72fe9a59561fb8f33889895b6708342b2856

**Comment by smithfarm** [comment]
@mattbenjamin Thanks!

**Comment by mattbenjamin** [comment]
@smithfarm sorry, we're not missing 1d6c72fe, but need to understand the conflict (want to ensure that correct handle lifecycle commits all land)

**Comment by smithfarm** [comment]
@mattbenjamin No, not 1d6c72f (which is a jewel backport), but I did cherry-pick ef330f3 into this PR which will hopefully resolve the build issue.

**Comment by smithfarm** [comment]
oh, now I see the conflict. I'll re-do that commit as well.

**Comment by mattbenjamin** [comment]
@smithfarm basically kraken should I think get backports of all commits that reached jewel after kraken branched;  kraken seems to be missing at least the following:
70ef7d45e0abf2661bd4e23161d4e70cf5178079
2e66c7a7cc763c5c0d6f5db04855f60f2b2ceed3

**Comment by smithfarm** [comment]
@mattbenjamin First, I redid the cherry-picks, so the conflict is gone. Second, I tried cherry-picking 70ef7d4 and 2e66c7a on top of this PR and neither cherry-picks cleanly.

**Comment by mattbenjamin** [comment]
@smithfarm I did search those on a jewel branch, I'll re-run on master;  however, I do know that LIBRGW_FILE_VER_EXTRA (src/include/rados/rgw_file.h) is incorrect on Kraken

**Comment by mattbenjamin** [comment]
@smithfarm proposed conflict resolutions on:
   git@github.com:linuxbox2/ceph.git smithfarm-wip-19144-kraken
(ignore top commit)

**Comment by smithfarm** [comment]
@mattbenjamin OK, integrated those fixes, updated trackers etc.

**Comment by smithfarm** [comment]
Jenkins re-test this please

**Comment by smithfarm** [comment]
@mattbenjamin In the end I merged this PR into #13871. The two commits that had conflicts (which you resolved) no longer conflicted when I cherry-picked them on top of the commits already in that PR.

**Comment by mattbenjamin** [comment]
ok, cool

**Pull request closed without merging**
