### PR TITLE
tests: osd-scrub-repair.sh abort if add_something fails

### PR DESCRIPTION
**Pull request by dachary**
If the script keeps going after this function fails, it will be non
trivial to find the root cause of the problem.

Signed-off-by: Loic Dachary <loic@dachary.org>

### CODE REVIEW

**Comment by dachary** [comment]
I ran into this while looking into http://tracker.ceph.com/issues/18018 : I don't think it helps osd-scrub-repair.sh itself in any way. It just makes it a little easier to debug.

**Comment by dachary** [comment]
jenkins test this please (osd-crush.sh http://tracker.ceph.com/issues/18022)

**Comment by tchaikov** [comment]
```
Error ENOSPC: failed to add rule 256 because (28) No space left on device
```

**Comment by dachary** [comment]
@tchaikov unfortunately this is expected and not the root cause of the error. Thanks for taking a look though :-)

<pre>
/home/jenkins-build/build/workspace/ceph-pull-requests/src/test/mon/osd-crush.sh:203: TEST_add_ruleceph osd crush rule create-simple test_rule_nospace host1 osd firstn
/home/jenkins-build/build/workspace/ceph-pull-requests/src/test/mon/osd-crush.sh:203: TEST_add_rulegrep 'Error ENOSPC'
Error ENOSPC: failed to add rule 256 because (28) No space left on device
ceph-mon: mon.noname-a 127.0.0.1:7104/0 is local, renaming to mon.a
ceph-mon: set fsid to 545eeeef-59ac-4bf4-b99a-921cf3046813
ceph-mon: created monfs at td/osd-crush/a for mon.a
/home/jenkins-build/build/workspace/ceph-pull-requests/src/test/mon/osd-crush.sh:34: run:  teardown td/osd-crush
</pre>

**Comment by tchaikov** [comment]
oh, right!

**Comment by dachary** [comment]
jenkins test this please (test_objectstore_memstore.sh http://tracker.ceph.com/issues/18027)

**Pull request merged**
