### PR TITLE
jewel: qa: use xfs instead of btrfs w/ filestore

### PR DESCRIPTION
**Pull request by batrick**
Backport of work from 6369120d63ba8077f0f5bb8b4280ee72ce269568.

Fixes: http://tracker.ceph.com/issues/21481

Signed-off-by: Patrick Donnelly <pdonnell@redhat.com>

### CODE REVIEW

**Comment by smithfarm** [comment]
IIRC there was a discussion awhile back whether or not to drop BTRFS testing/support in Jewel and the idea of dropping it got some pushback from the community at the time. Perhaps that's why these tests are still there.

This PR is more limited in scope - not dropping it entirely, but just in the fs suite.

**Comment by tchaikov** [comment]
http://pulpito.ceph.com/kchai-2017-10-02_07:55:29-rados-wip-kefu-testing-2017-10-02-1347-jewel-distro-basic-mira/

**Comment by tchaikov** [comment]
http://pulpito.ceph.com/kchai-2017-10-02_07:55:29-rados-wip-kefu-testing-2017-10-02-1347-jewel-distro-basic-mira/

**Comment by tchaikov** [comment]
clone_range fails with errno 95 while testing with btrfs backend, see http://tracker.ceph.com/issues/21150. i'd suggest drop btrfs tests in rados suite as well. change posted at #18165

**Comment by tchaikov** [comment]
- http://pulpito.ceph.com/kchai-2017-11-03_05:56:44-rados-wip-jewel-backports-reloaded-distro-basic-mira/
- http://pulpito.ceph.com/kchai-2017-11-03_12:19:08-rados-wip-jewel-backports-reloaded-distro-basic-mira/
- http://pulpito.ceph.com/kchai-2017-11-03_12:20:04-rados-wip-jewel-backports-reloaded-distro-basic-mira/

the test failure is addressed by https://github.com/ceph/teuthology/pull/1123

**Pull request merged**
