### PR TITLE
nautilus: krbd: avoid udev netlink socket overrun and retry on transient errors from udev_enumerate_scan_devices()

### PR DESCRIPTION
**Pull request by smithfarm**
backport trackers: 

* https://tracker.ceph.com/issues/42427
* https://tracker.ceph.com/issues/42524
* https://tracker.ceph.com/issues/42645

---

backport of

* https://github.com/ceph/ceph/pull/30965
* https://github.com/ceph/ceph/pull/31023
* https://github.com/ceph/ceph/pull/31057

parent trackers:

* https://tracker.ceph.com/issues/41036
* https://tracker.ceph.com/issues/41404
* https://tracker.ceph.com/issues/42523

### CODE REVIEW

**Comment by smithfarm** [comment]
I seem to remember that this backport could be profitably combined with a different, but related, backport... can anyone confirm or deny that?

**Comment by idryomov** [comment]
@smithfarm It could be combined with the backport of https://github.com/ceph/ceph/pull/31023, but that's not merged yet (another libudev misbehaviour has popped out, I'm investigating...)

**Comment by smithfarm** [comment]
jenkins test docs

**Comment by smithfarm** [comment]
Cherry-picked #31023 into this PR. @idryomov @dillaman Please re-review?

**Comment by idryomov** [comment]
@smithfarm Please cherry-pick https://github.com/ceph/ceph/pull/31057 in front of everything else in this PR.  I added comments on the tracker and linked the respective issues, but it's a bit scattered...

**Comment by smithfarm** [comment]
@idryomov OK, done. After the force-push, GitHub is not showing the commits in the right order. Here's the real order:

```
$ git log --oneline --no-decorate --reverse 98cb958fc1^..HEAD
98cb958fc1 common/thread: Fix race condition in make_named_thread
3012b35364 krbd: get rid of poll() timeout
7e66b7e33e krbd: separate event reaping from event processing
3817245256 krbd: reap all available events before polling again
924e18f468 krbd: avoid udev netlink socket overrun
29ee92a151 krbd: increase udev netlink socket receive buffer to 2M
c7968c30a4 qa: add script to test udev event reaping
8e15daef1e krbd: retry on transient errors from udev_enumerate_scan_devices()
3a6fa88e61 krbd: retry on an empty list from udev_enumerate_scan_devices()
2ad3e0f2e3 qa: add script to stress udev_enumerate_scan_devices()
```

**Comment by smithfarm** [comment]
@idryomov Hm, and I see that #31057 has non-trivial conflicts when cherry-picked to mimic (and presumably luminous as well). Looks like it conflicts with some post-mimic refactoring.

**Comment by idryomov** [comment]
Yeah, I'll probably need to do mimic and luminous myself.  I'll try to open the PRs today.

**Comment by idryomov** [comment]
@smithfarm I noticed you removed nautilus-batch-1 and needs-qa labels.  The series looks good, please re-add them if needed.

**Comment by yuriw** [comment]
[wip-yuri8-testing-2019-11-08-2045-nautilus](https://trello.com/c/1zza4G7A/754-wip-yuri8-testing-2019-11-08-2045-nautilus)

**Pull request merged**
