### PR TITLE
rgw: perfcounters: add gc retire counter

### PR DESCRIPTION
**Pull request by mattbenjamin**
To avoid spam, counter updates are batched with the corresponding log
trim chunks.

Fixes: https://tracker.ceph.com/issues/38251

Signed-off-by: Matt Benjamin <mbenjamin@redhat.com>

- [x] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by mattbenjamin** [comment]
@ivancich does this look ok?

**Comment by ivancich** [comment]
@ivancich Yep, it looks good.

**Comment by mattbenjamin** [comment]
http://pulpito.ceph.com/mbenjamin-2019-03-15_13:52:11-rgw-wip-matt-testing-2-distro-basic-smithi/

**Comment by mattbenjamin** [comment]
previous job fragged, now it's
http://pulpito.ceph.com/mbenjamin-2019-03-15_14:31:36-rgw-wip-matt-testing-2-distro-basic-smithi/

**Comment by ivancich** [comment]
@mattbenjamin 

My teuthology QA run found an issue.

Here's the log:
http://qa-proxy.ceph.com/teuthology/ivancich-2019-03-29_06:51:35-rgw-wip-eric-testing-1-distro-basic-smithi/3783785/teuthology.log

And here's the stack trace from the log:
2019-03-29T08:06:05.718 INFO:teuthology.orchestra.run.smithi138.stderr: ceph version 14.2.0-640-g421f9b6 (421f9b604473fb8d392bc103de95ea3d388683db) octopus (dev)
2019-03-29T08:06:05.718 INFO:teuthology.orchestra.run.smithi138.stderr: 1: (()+0x11390) [0x7ff362b14390]
2019-03-29T08:06:05.719 INFO:teuthology.orchestra.run.smithi138.stderr: 2: (PerfCounters::inc(int, unsigned long)+0) [0x7ff3631b09a0]
2019-03-29T08:06:05.719 INFO:teuthology.orchestra.run.smithi138.stderr: 3: (RGWGCIOManager::flush_remove_tags(int, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&)+0x970) [0x976980]
2019-03-29T08:06:05.719 INFO:teuthology.orchestra.run.smithi138.stderr: 4: (RGWGC::process(bool)+0x425) [0x974765]
2019-03-29T08:06:05.719 INFO:teuthology.orchestra.run.smithi138.stderr: 5: (main()+0x1a0fa) [0x56b9fa]
2019-03-29T08:06:05.719 INFO:teuthology.orchestra.run.smithi138.stderr: 6: (__libc_start_main()+0xf0) [0x7ff36141d830]
2019-03-29T08:06:05.719 INFO:teuthology.orchestra.run.smithi138.stderr: 7: (_start()+0x29) [0x59cef9]

**Comment by cbodley** [comment]
passed qa in http://pulpito.front.sepia.ceph.com/cbodley-2019-06-19_19:30:04-rgw-wip-cbodley-testing-distro-basic-smithi/. s3test failures tracked in http://tracker.ceph.com/issues/40416, and valgrind warnings in ceph-mon are from https://github.com/ceph/ceph/pull/27834

**Pull request merged**
