### PR TITLE
osd: optimize pg peering latency when add new osd that need backfill

### PR DESCRIPTION
**Pull request by jianwei1216**
https://tracker.ceph.com/issues/52884
first description : https://github.com/ceph/ceph/pull/43482

```
    osd: optimize pg peering latency when add new osd that need backfill
    
    set last_backfill to MIN when creating pg
    
    This happens when the newly created(caused by adding or deleting osd)
    pg has its pglog (head, tail) that is empty pglog(0,0),
    but it still continuous with the authoritative log(0, 3000),
    In this case, we use backfill instead of recovery.
    
    If the authoritative log (6000,9000), that is, tail > 3000,
    then the newly created pg (0,0) will naturally go directly to the backfill path,
    because there is no intersection between the two.
    
    If the osd is offline for a short time,
    the pg on it will still be continuous with the authoritative log.
    In this case, the recovery path will still be taken, not backfill.
    
    There are 2 benefits
    1. Backfill has lower latency than recovery in processing pglog during peering
    2. When choose_acting, the backfill osd will not be considered,
       when osd is continuously added/deleted, the number of acting changes can be reduced.
    
    Fix : https://tracker.ceph.com/issues/52884
    
    Signed-off-by: Jianwei Zhang <jianwei1216@qq.com>
```

### CODE REVIEW

**Comment by jianwei1216** [comment]
add @neha-ojha @tchaikov

**Comment by athanatos** [comment]
I would want this to be, at the least, a config option.  I'm not sure I'm sold on this in general, though.

**Comment by rzarzynski** [comment]
```
The following tests FAILED:
	 33 - run-rbd-unit-tests-109.sh (Failed)
	 34 - run-rbd-unit-tests-127.sh (Failed)
	 36 - smoke.sh (Timeout)
	192 - safe-to-destroy.sh (Failed)
Errors while running CTest
```

**Comment by rzarzynski** [comment]
jenkins retest this please

**Comment by jianwei1216** [comment]
> I would want this to be, at the least, a config option. I'm not sure I'm sold on this in general, though.

This happens when the newly created(caused by adding or deleting osd)  pg has its pglog (head, tail) still continuous with the authoritative log, but it is indeed an empty log

**Comment by athanatos** [comment]
One observation is that this only seems to matter for a pg that is so new that it hasn't seen 3000 updates yet.  I'm not sure it's worth adding complexity to address such a narrow case.

**Comment by jianwei1216** [comment]
> One observation is that this only seems to matter for a pg that is so new that it hasn't seen 3000 updates yet. I'm not sure it's worth adding complexity to address such a narrow case.

My idea is that the newly created pg should go backfill, pglog(0,3000), in the case of osdmap changes, choose_acting will also select this empty pg as a member of acting, which is for the replica pool , the impact is not large, but for the ec pool, the impact will be relatively large, please refer to https://tracker.ceph.com/issues/55668

**Comment by jianwei1216** [comment]
> One observation is that this only seems to matter for a pg that is so new that it hasn't seen 3000 updates yet. I'm not sure it's worth adding complexity to address such a narrow case.

Should have pg(osd) with complete data as a member of acting even in the case of pglog(0,3000).
This is my original intention.

**Comment by athanatos** [comment]
Again, though, once a pool has seen enough writes that the pgs will have seen 3000 updates, this change has no effect.  I'm really not sure it's worth adding complexity for this.

**Comment by jianwei1216** [comment]
> Again, though, once a pool has seen enough writes that the pgs will have seen 3000 updates, this change has no effect. I'm really not sure it's worth adding complexity for this.

This may depend on the scale of the cluster. If the scale of the cluster is relatively large, it may take some time for all PGs in a storage pool to write 3000 pglogs, and the abnormal time window will increase accordingly, and the probability of problems will also increase.

**Comment by athanatos** [comment]
The only problem I think you've pointed out is a difference in latency.  Someone else my disagree with me, but I don't think it's worth the additional complexity.

**Pull request closed without merging**
