### PR TITLE
mgr/dashboard: Return task also if run synchronously

### PR DESCRIPTION
**Pull request by sebastian-philipp**
Returned JSON is a subset for finished tasks of
`mgr.dashboard.tools.TaskManager#list_serializable`

**It only makes sense to merge this PR, if it actually helps the frontend!**

Signed-off-by: Sebastian Wagner <sebastian.wagner@suse.com>

### CODE REVIEW

**Comment by ricardoasmarques** [comment]
This PR implements what was discussed, and I was part of that discussion, but after thinking about this topic one more time, I'm afraid this can compromise us in the future if we want to become a public REST API for ceph.

Therefore, I think that RBD synchronous creation should return the created RBD, instead of returning the Task. This should be enough for the frontend.

**Comment by sebastian-philipp** [comment]
@ricardoasmarques , We can still return the created object. See https://github.com/ceph/ceph/pull/21814/files#diff-3095fd00dfad68aeeccd8ad3fe6d3356R329

Also, this makes the JSON returned by these endpoints more predictable and coherent.

**Comment by ricardoasmarques** [comment]
@sebastian-philipp but still it might be a good idea to stick with the REST "standard", and just return the `value`.

I'm defending this because I think that all synchronous calls should be treated in the same way, regardless of whether they are a `task` or not.

My strongest argument here is that the problem we are trying to solve in this PR, will continue to exist in endpoints that are not `tasks`, that's why I'm proposing a solution that works for both `task` and `not task` endpoints.

**Comment by sebastian-philipp** [comment]
let's keep it open, till PR of the other solution is open

**Comment by LenzGr** [comment]
Closing per today's conversation

**Pull request closed without merging**
