### PR TITLE
mimic: common: fix missing include boost/noncopyable.hpp

### PR DESCRIPTION
**Pull request by wjwithagen**
http://tracker.ceph.com/issues/38179

### CODE REVIEW

**Comment by smithfarm** [comment]
@wjwithagen @tchaikov Before opening a PR with a cherry-pick to a stable branch, would it be possible to first:

1. create a tracker mentioning the PR number of the master fix, fill out Backport field
2. set that tracker's status to "Pending Backport"

Beyond that the backporting team will take care of it. If you really want to do the cherry-pick yourself, the next steps would be:

3. run `src/script/backport-create-issue [TRACKER_NUMBER]` to create the backport tracker issues
4. assign the backport tracker to yourself
5. open PR with cherry-pick
6. put the full URL of the PR in the backport tracker description
7. put the full URL of the backport tracker in the PR description

**Comment by yuriw** [comment]
[wip-yuri5-testing-2019-02-05-1730-mimic](https://trello.com/c/3UT78K8S/531-wip-yuri5-testing-2019-02-05-1730-mimic)

**Comment by wjwithagen** [comment]
@smithfarm 
Thanx for pointing this out.
I'll put this in my notes. Sure make my work for this a lot easier.
Can I also do this for just a small commit of a larger PR?

**Comment by smithfarm** [comment]
> Can I also do this for just a small commit of a larger PR?

@wjwithagen Absolutely! In that case don't fill out "Pull Request ID" field, but just specify the SHA1 of the commit in the tracker description.

**Comment by wjwithagen** [comment]
@smithfarm 

Right, but in this case the whole PR turns out to be only 1 commit to several  files.
And I need only once change, and there that part has moved form `src/CMakeLists.txt` to `src/mgr/CMakeLists.txt` (see last file in #2351)
So I guessing that is going to be a dedicated commit to mimic?

**Comment by smithfarm** [comment]
@wjwithagen That's a special case. . . Can you still open the tracker and specify in the description exactly what you need? If you do it now, I'll create the backport issue for you and you can then do the manual partial cherry-pick yourself. OK?

**Comment by smithfarm** [comment]
In the commit description you can write: "This is a manual partial cherry-pick of [SHA1]"

**Comment by wjwithagen** [comment]
@smithfarm 
Tracker: http://tracker.ceph.com/issues/38213

**Comment by tchaikov** [comment]
@wjwithagen in future, i'd suggest use one's own repo for topic branch instead of using ceph/ceph for hosting them.

**Comment by wjwithagen** [comment]
@tchaikov 
I think you have to be more explicit, since your question makes no sense to me...
As you know I'd like to accomodate where ever I can.
So I will do this, IF I know what you are asking me to do.

**Comment by tchaikov** [comment]
@wjwithagen i suggest push to your changes to your own repo, namely https://github.com/wjwithagen/ceph/ , and create PR from there instead of pushing to https://github.com/ceph/ceph/ .

**Comment by wjwithagen** [comment]
@tchaikov 
I see, Thanx for pointing that out. I wasn't aware that I did this.
Other backports were along the lines you describe.
And I will try to take better care next time.

**Pull request merged**
