### PR TITLE
luminous: rbd-mirror: handle duplicates in image sync throttler queue

### PR DESCRIPTION
**Pull request by trociny**
Backport ticket: http://tracker.ceph.com/issues/40592

### CODE REVIEW

**Comment by smithfarm** [comment]
jenkins test make check

**Comment by smithfarm** [comment]
Does not compile.

```
Scanning dependencies of target ceph-conf
[ 84%] Building CXX object src/tools/CMakeFiles/ceph-conf.dir/ceph_conf.cc.o
/home/jenkins-build/build/workspace/ceph-pull-requests/src/test/rbd_mirror/test_mock_ImageSyncThrottler.cc: In member function ‘virtual void rbd::mirror::TestMockImageSyncThrottler_Duplicate_Test::TestBody()’:
/home/jenkins-build/build/workspace/ceph-pull-requests/src/test/rbd_mirror/test_mock_ImageSyncThrottler.cc:117:50: error: no matching function for call to ‘rbd::mirror::ImageSyncThrottler<librbd::{anonymous}::MockTestImageCtx>::ImageSyncThrottler(CephContext*&)’
   MockImageSyncThrottler throttler(g_ceph_context);
                                                  ^
In file included from /home/jenkins-build/build/workspace/ceph-pull-requests/src/test/rbd_mirror/test_mock_ImageSyncThrottler.cc:33:0:
/home/jenkins-build/build/workspace/ceph-pull-requests/src/tools/rbd_mirror/ImageSyncThrottler.cc:31:1: note: candidate: rbd::mirror::ImageSyncThrottler<ImageCtxT>::ImageSyncThrottler() [with ImageCtxT = librbd::{anonymous}::MockTestImageCtx]
 ImageSyncThrottler<I>::ImageSyncThrottler()
 ^
/home/jenkins-build/build/workspace/ceph-pull-requests/src/tools/rbd_mirror/ImageSyncThrottler.cc:31:1: note:   candidate expects 0 arguments, 1 provided
/home/jenkins-build/build/workspace/ceph-pull-requests/src/test/rbd_mirror/test_mock_ImageSyncThrottler.cc: In member function ‘virtual void rbd::mirror::TestMockImageSyncThrottler_Duplicate2_Test::TestBody()’:
/home/jenkins-build/build/workspace/ceph-pull-requests/src/test/rbd_mirror/test_mock_ImageSyncThrottler.cc:140:50: error: no matching function for call to ‘rbd::mirror::ImageSyncThrottler<librbd::{anonymous}::MockTestImageCtx>::ImageSyncThrottler(CephContext*&)’
   MockImageSyncThrottler throttler(g_ceph_context);
                                                  ^
In file included from /home/jenkins-build/build/workspace/ceph-pull-requests/src/test/rbd_mirror/test_mock_ImageSyncThrottler.cc:33:0:
/home/jenkins-build/build/workspace/ceph-pull-requests/src/tools/rbd_mirror/ImageSyncThrottler.cc:31:1: note: candidate: rbd::mirror::ImageSyncThrottler<ImageCtxT>::ImageSyncThrottler() [with ImageCtxT = librbd::{anonymous}::MockTestImageCtx]
 ImageSyncThrottler<I>::ImageSyncThrottler()
 ^
/home/jenkins-build/build/workspace/ceph-pull-requests/src/tools/rbd_mirror/ImageSyncThrottler.cc:31:1: note:   candidate expects 0 arguments, 1 provided
src/test/rbd_mirror/CMakeFiles/unittest_rbd_mirror.dir/build.make:158: recipe for target 'src/test/rbd_mirror/CMakeFiles/unittest_rbd_mirror.dir/test_mock_ImageSyncThrottler.cc.o' failed
make[3]: *** [src/test/rbd_mirror/CMakeFiles/unittest_rbd_mirror.dir/test_mock_ImageSyncThrottler.cc.o] Error 1
```

**Comment by trociny** [comment]
@smithfarm fixed. Thanks.

**Comment by smithfarm** [comment]
jenkins test docs

**Comment by yuriw** [comment]
[wip-yuri5-testing-2019-09-30-1944-luminous](https://trello.com/c/oisaBLUN/700-wip-yuri5-testing-2019-09-30-1944-luminous)

**Pull request merged**
