### PR TITLE
 librbd: create+truncate for whole-object layered discards

### PR DESCRIPTION
**Pull request by idryomov**

### CODE REVIEW

**Comment by dillaman** [comment]
@idryomov Can you create a tracker ticket for this issue so that it can be backported to jewel and luminous?

**Comment by idryomov** [comment]
Created and rebased to link it from the commit.

**Comment by idryomov** [comment]
retest this please

**Comment by dillaman** [comment]
retest this please

**Comment by dillaman** [comment]
retest this please

**Comment by dillaman** [comment]
retest this please

**Comment by dillaman** [comment]
(I'm really scratching my head to figure out why the ```make check``` builders hate this PR)

**Comment by dillaman** [comment]
retest this please

**Comment by dillaman** [comment]
Merged manually

**Pull request closed without merging**
