### PR TITLE
octopus: mgr/dashboard: Display users current bucket quota usage

### PR DESCRIPTION
**Pull request by epuertat**
backport tracker: https://tracker.ceph.com/issues/46354

---

backport of https://github.com/ceph/ceph/pull/34606
parent tracker: https://tracker.ceph.com/issues/45011

this backport was staged using ceph-backport.sh version 15.1.1.389
find the latest version at https://github.com/ceph/ceph/blob/master/src/script/ceph-backport.sh

### CODE REVIEW

**Comment by epuertat** [comment]
jenkins test dashboard

**Comment by epuertat** [comment]
jenkins test dashboard

**Comment by avanthakkar** [comment]
jenkins test make check

**Comment by avanthakkar** [comment]
jenkins test dashboard backend

**Comment by callithea** [comment]
jenkins test make check

**Comment by callithea** [comment]
jenkins test dashboard backend

**Comment by avanthakkar** [comment]
jenkins test make check

**Comment by avanthakkar** [comment]
jenkins test dashboard

**Comment by avanthakkar** [comment]
jenkins test dashboard backend

**Comment by epuertat** [comment]
jenkins retest this please

**Comment by epuertat** [comment]
This backport has undone part of the changes introduced by https://github.com/ceph/ceph/pull/35766. Opened https://tracker.ceph.com/issues/46502 to fix this.

**Pull request merged**
