### PR TITLE
mgr/dashboard: Set iSCSI disk WWN and LUN number from the UI

### PR DESCRIPTION
**Pull request by ricardoasmarques**
_After https://github.com/ceph/ceph-iscsi/pull/150 (Merged)_

---

With this PR will be possible to set disk WWN and LUN number from the UI:

Screenshot from 2019-10-22 16-25-30

Screenshot from 2019-10-22 16-25-56

Fixes: https://tracker.ceph.com/issues/41749

Signed-off-by: Ricardo Marques <rimarques@suse.com>

### CODE REVIEW

**Comment by ricardoasmarques** [comment]
jenkins test dashboard

**Comment by ricardoasmarques** [comment]
jenkins test dashboard

**Comment by ricardoasmarques** [comment]
jenkins test dashboard

**Comment by epuertat** [comment]
@ricardoasmarques I'm curious: why is it necessary to merge this PR after a PR in another repo becomes merged? Does it  otherwise break something there?

I'm asking this because of the `"expected v10, found v11"` error (https://tracker.ceph.com/issues/42613) triggered by Nautilus dashboard with ceph-iscsi 3.2,  and also the later change to allow 10-11 versions. 

This basically means that the dashboard is tightly coupled with the ceph-iscsi version, and very restrictively backward/forward compatible.

If I have correctly interpreted the other PRs, that version 11 increase happened because a new endpoint param `auth` was added, but that addition, couldn't it be done seamlessly? I mean

**Comment by epuertat** [comment]
Sorry @ricardoasmarques! I was writing a comment, but later decided to discard it and accidentally closed it :pray:  :sweat_smile:

**Comment by ricardoasmarques** [comment]
jenkins test dashboard

**Pull request merged**
