### PR TITLE
qa/cephfs: don't use int() to convert string of float point number

### PR DESCRIPTION
**Pull request by ukernel**
Fixes: http://tracker.ceph.com/issues/20582
Signed-off-by: "Yan, Zheng" <zyan@redhat.com>

### CODE REVIEW

**Comment by jcsp** [comment]
The thing is, they *are* ints.  It's a bug in config.cc that's casting them to floats in the output to "config get".

**Comment by batrick** [comment]
http://tracker.ceph.com/issues/20582#note-4

**Comment by jcsp** [comment]
Oh, I'm wrong about this.  It was broken by the config.cc change, but they were always floats.  The breakage was that it started forcing the fixed number of decimal places.  Zheng's fix is correct.

**Comment by batrick** [comment]
`Reviewed-by: Patrick Donnelly <pdonnell@redhat.com>`

**Pull request merged**
