### PR TITLE
include: cleanup lru con/des

### PR DESCRIPTION
**Pull request by batrick**

### CODE REVIEW

**Comment by tchaikov** [comment]
```
/home/jenkins-build/build/workspace/ceph-pull-requests/src/test/smoke.sh:56: TEST_multimon:  timeout 8 rados -p foo bench 4 write -b 4096 --no-cleanup
/home/jenkins-build/build/workspace/ceph-pull-requests/src/test/smoke.sh:56: TEST_multimon:  return 1
/home/jenkins-build/build/workspace/ceph-pull-requests/src/test/smoke.sh:20: run:  return 1
```

**Comment by tchaikov** [comment]
jenkins test make check

**Comment by tchaikov** [comment]
- http://pulpito.ceph.com/kchai-2020-06-18_14:02:59-rados-wip-kefu-testing-2020-06-18-1920-distro-basic-smithi/
- http://pulpito.ceph.com/kchai-2020-06-19_01:27:19-rados-wip-kefu-testing-2020-06-19-0045-distro-basic-smithi/
- http://pulpito.ceph.com/kchai-2020-06-19_04:33:35-rados-wip-kefu-testing-2020-06-19-1102-distro-basic-smithi/
- http://pulpito.ceph.com/kchai-2020-06-20_03:36:44-rados-wip-kefu-testing-2020-06-20-0005-distro-basic-smithi/

cephadm tests failed due to accessing docker.io instead of via a mirror registry.

**Comment by batrick** [comment]
jenkins test dashboard backend

**Pull request merged**
