### PR TITLE
nautilus: core: include/encoding: Fix encode/decode of float types on big-endian systems

### PR DESCRIPTION
**Pull request by smithfarm**
backport tracker: https://tracker.ceph.com/issues/47350

---

backport of https://github.com/ceph/ceph/pull/36992
parent tracker: https://tracker.ceph.com/issues/47302

this backport was staged using ceph-backport.sh version 15.1.1.389
find the latest version at https://github.com/ceph/ceph/blob/master/src/script/ceph-backport.sh

### CODE REVIEW

**Comment by smithfarm** [comment]
@uweigand FYI

**Comment by smithfarm** [comment]
jenkins test make check

**Comment by smithfarm** [comment]
The dashboard tests in nautilus "make check" are unstable ATM.

**Comment by yuriw** [comment]
[wip-yuri2-testing-2020-09-08-1946-nautilus](https://trello.com/c/UDU0u8VE/1005-wip-yuri2-testing-2020-09-08-1946-nautilus)

**Comment by yuriw** [comment]
[wip-yuri2-testing-2020-09-10-0000-nautilus](https://trello.com/c/DBenW5i1/1007-wip-yuri2-testing-2020-09-10-0000-nautilus)

**Comment by neha-ojha** [comment]
jenkins test make check

**Review by tchaikov — APPROVED** [review]

**Review by ideepika — APPROVED** [review]

**Comment by yuriw** [comment]
test this please

**Comment by smithfarm** [comment]
`run-tox-mgr-dashboard` failure in a test called `IscsiTestController.test_remove_client_logged_in`

(I've seen it before... It's tracked by https://tracker.ceph.com/issues/47269 ... @callithea Do you know if anyone is working on this one? It's blocking nautilus integration testing.)

**Comment by callithea** [comment]
> make check failure is caused by a failure in `run-tox-mgr-dashboard` -- specifically, it failed in a test called `IscsiTestController.test_remove_client_logged_in`
> 
> (This one is tracked by https://tracker.ceph.com/issues/47269 ... @callithea Do you know if anyone is working on this one? It's blocking nautilus integration testing.)

Hi @smithfarm, I asked the dashboard team to look into this, thanks for the ping!

**Comment by yuriw** [comment]
@smithfarm This PR can be merged but I can't do so, it blocked :(

**Comment by yuriw** [comment]
test this please

**Comment by djgalloway** [comment]
jenkins test make check

**Comment by smithfarm** [comment]
> @smithfarm This PR can be merged but I can't do so, it blocked :(

I can't merge it, either. We have two options: (1) keep retrying until it passes, (2) wait for https://tracker.ceph.com/issues/47269 to be fixed.

**Comment by dmick** [comment]
There are other failures here; it looks like one of them is run-rbd-unit-tests-127.sh; something to do with a missing symbol in libcls:

$ echo "_Z27cls_cxx_chunk_write_and_setPviiPN4ceph6buffer7v14_2_04listEjS4_i" | c++filt
cls_cxx_chunk_write_and_set(void*, int, int, ceph::buffer::v14_2_0::list*, unsigned int, ceph::buffer::v14_2_0::list*, int)

**Comment by dmick** [comment]
The assert failure is also worth investigating

**Comment by yuriw** [comment]
[wip-yuri6-testing-2020-09-16-2222-nautilus](https://trello.com/c/jWKrFVDM/1014-wip-yuri6-testing-2020-09-16-2222-nautilus)

**Comment by smithfarm** [comment]
> There are other failures here; it looks like one of them is run-rbd-unit-tests-127.sh; something to do with a missing symbol in libcls:
> 
> $ echo "_Z27cls_cxx_chunk_write_and_setPviiPN4ceph6buffer7v14_2_04listEjS4_i" | c++filt
> cls_cxx_chunk_write_and_set(void*, int, int, ceph::buffer::v14_2_0::list*, unsigned int, ceph::buffer::v14_2_0::list*, int)

Pretty sure I've seen that one in other nautilus PRs, too: could be https://tracker.ceph.com/issues/46669 ?

**Comment by yuriw** [comment]
jenkins test make check

**Comment by smithfarm** [comment]
https://tracker.ceph.com/issues/47269 once again

**Comment by yuriw** [comment]
jenkins test make check

**Comment by yuriw** [comment]
jenkins test make check

**Comment by yuriw** [comment]
jenkins test make check

**Comment by yuriw** [comment]
test this please

**Comment by jdurgin** [comment]
jenkins test make check

**Comment by smithfarm** [comment]
@yuriw The "make check" check passed. The failed check "ceph PR - make check" can be ignored.

**Pull request merged**
