### PR TITLE
erasure-code: shec plugin feature

### PR DESCRIPTION
**Pull request by dachary**
http://tracker.ceph.com/issues/10887

### CODE REVIEW

**Comment by liewegas** [comment]
LGTM

**Comment by dachary** [comment]
http://ceph.com/gitbuilder.cgi builds wip-10887-shec to use with https://github.com/ceph/ceph-qa-suite/pull/523

**Comment by t-miyamae** [comment]
@dachary We have reviewed the source code. LGTM. Do we have to test it on a cluster?

**Comment by dachary** [comment]
@t-miyamae it would be great if you could test it on your cluster, yes :-)

**Comment by t-miyamae** [comment]
@dachary OK. We'll try it. But since we are in a summer holiday next week, we'll be able to show you the result after August 17.
By the way, I forgot to mention some trivial typos in above sentences. Should we correct them such as isa=>shec, sched=>shec?

**Comment by dachary** [comment]
@t-miyamae I fixed the typos, thanks !

**Comment by dachary** [comment]
@t-miyamae results after August 17th will be useful, sure.

**Comment by liewegas** [comment]
@dachary ping

**Comment by dachary** [comment]
http://pulpito.ceph.com/loic-2015-08-17_18:18:30-upgrade:hammer-x:stress-split-erasure-code-wip-10887-shec---basic-multi/ running

**Comment by t-miyamae** [comment]
@dachary We have finished the test on a real cluster and verified that following tests were all passed.
1. We cannot load SHEC plugins when mon is PLUGINS_V3 and all osds are PLUGINS_V2.
2. We can create SHEC pools when mon is PLUGINS_V3 and all osds are PLUGINS_V3.
3. We can create SHEC pools when mon is PLUGINS_V3, all osds are PLUGINS_V3 and we don't write magic word of experimental feature in ceph.conf.

**Comment by dachary** [comment]
@t-miyamae thanks for the manual testing. The teuthology tests fail though http://pulpito.ceph.com/loic-2015-08-17_18:18:30-upgrade:hammer-x:stress-split-erasure-code-wip-10887-shec---basic-multi/

**Comment by dachary** [comment]
Feature test running at http://pulpito.ceph.com/loic-ec-feature-plugins-v3/

**Comment by dachary** [comment]
Must run the following again on f29260a (just pushed to gitbuilders)  because the previous successful run was before the rebase 
<pre>
./virtualenv/bin/teuthology-suite --verbose --suite rados/singleton --filter=feature-plugins-v3 --suite-branch wip-10887-shec --ceph wip-10887-shec --email loic@dachary.org --machine-type vps
</pre>

**Comment by dachary** [comment]
rebased (trivial conflict with proxy write feature) and repushed

**Comment by dachary** [comment]
http://pulpito.ceph.com/loic-2015-08-21_18:47:09-rados:singleton-wip-10887-shec---basic-vps/ fails but that does not seem to be related to the change

**Comment by dachary** [comment]
I tried to use the same feature bit as another but the update logic is quite different. Changed back to a dedicated bit for this feature.

**Comment by dachary** [comment]
http://pulpito.ceph.com/loic-2015-08-21_22:44:21-rados:singleton-wip-10887-shec---basic-vps/ running

**Comment by dachary** [comment]
http://pulpito.ceph.com/loic-2015-08-22_10:13:46-rados:singleton-wip-10887-shec---basic-vps/ running

**Comment by dachary** [comment]
http://pulpito.ceph.com/loic-2015-08-22_12:37:09-upgrade:hammer-x-wip-10887-shec---basic-vps/ running

**Comment by t-miyamae** [comment]
@dachary We appreciate so much that you spent your time on this pull request for these couple of weeks.

**Comment by dachary** [comment]
@t-miyamae you're welcome :-) It is now very important to verify it does not disrupt anything and it would be great if you could run tests suites ( upgrade/hammer-x and rados ) to double check.

**Pull request merged**
