### PR TITLE
install-deps.sh: fix gcc detection and install pre-built libboost on bionic

### PR DESCRIPTION
**Pull request by tchaikov**
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by iotcg** [comment]
@tchaikov I'll verify this PR.

**Comment by iotcg** [comment]
@tchaikov  We can merge this PR. It pass below tests on ubuntu 18.04 physical host
1) git am patch successfully.
2) pass build "cd build; make"
3) pass tests "cd build; make tests"

Detail:
1. Host check
1) nstcc1@nstcloudcc1:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic

2) nstcc1@nstcloudcc1:~$ dpkg -l | grep 'ceph-libboost'
    ==> empty

3) nstcc1@nstcloudcc1:~$ grep 'libboost1.67' /etc/apt/* -rn
    ==> empty

2. verify patch
clone ceph code and apply this PR
git clone https://github.com/ceph/ceph.git
cd ceph
wget https://patch-diff.githubusercontent.com/raw/ceph/ceph/pull/25169.patch
git am 25169.patch

5) install dependents
nstcc1@nstcloudcc1:ceph$ ./install-deps.sh
    check dependents
           dpkg -l | grep 'ceph-libboost'       #all installed
    grep 'libboost1.67' /etc/apt/sources.list.d/ceph-libboost1.67.list -q    #source is wrote into this file

6) pass "make" and "make test"
nstcc1@nstcloudcc1:ceph$ ./do_cmake.sh
nstcc1@nstcloudcc1:build$ make
nstcc1@nstcloudcc1:build$ make tests

**Comment by tchaikov** [comment]
@iotcg thanks for testing and reviewing!

**Comment by iotcg** [comment]
@tchaikov welcome

**Pull request merged**
