### PR TITLE
mon/LogMonitor: Fix log last

### PR DESCRIPTION
**Pull request by pdvian**
The ceph log last command outputs all the cluster
logs generated from logm entries at DBG level,
irrespective of their log level. We must output
cluster logs generated from logm according
to the log level specified in the log last command.

Fixes: https://tracker.ceph.com/issues/57340

Signed-off-by: Prashant D <pdhange@redhat.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by pdvian** [comment]
jenkins test make check

**Review by rzarzynski — APPROVED** [review]

**Comment by rzarzynski** [comment]
jenkins test make check

**Comment by rzarzynski** [comment]
jenkins test api

**Comment by Matan-B** [comment]
Tests LGTM.

0 Related Failures.
6 Tracked unrelated Failures.
0 Newly Tracked Failures.
0 Tracked dead Jobs.

http://pulpito.front.sepia.ceph.com/yuriw-2022-09-14_20:04:05-rados-wip-yuri3-testing-2022-09-13-0928-distro-default-smithi/

Rerun of:
http://pulpito.front.sepia.ceph.com/yuriw-2022-09-13_20:42:45-rados-wip-yuri3-testing-2022-09-13-0928-distro-default-smithi/

Failures:
7033172, 7033177: rook: ensure CRDs are installed first (https://tracker.ceph.com/issues/57311)
7033173, 7033179: free(): invalid pointer (https://tracker.ceph.com/issues/57163)
7033174, 7033178: 'check osd count' reached maximum tries (https://tracker.ceph.com/issues/52321)

**Pull request merged**
