### PR TITLE
jewel: msg/simple/Pipe: avoid infinite loop in Pipe::do_recv()

### PR DESCRIPTION
**Pull request by liewegas**
http://tracker.ceph.com/issues/18155

### CODE REVIEW

**Comment by gregsfortytwo** [comment]
retest this please

**Comment by dachary** [comment]
jenkins test this please (unittest throttle)

**Comment by dachary** [comment]
@liewegas could you please rebase this against jewel-next ?

**Comment by liewegas** [comment]
replaced by https://github.com/ceph/ceph/pull/12349

**Pull request closed without merging**
