### PR TITLE
qa/mgr/test_progress: add _get_osd_in_out_events to account for osd marked in/out events

### PR DESCRIPTION
**Pull request by kamoltat**
Fixes a failing test case regarding osd coming back
after being marked out. The old test case wasn't accounting
for a specific event, therefore this resulted in the failure.
The fix basically accounts for a specific event of osd being
marked in/out.

Fixes: https://tracker.ceph.com/issues/48217

Signed-off-by: Kamoltat <ksirivad@redhat.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Review by neha-ojha — COMMENTED** [review]
can you please follow https://github.com/ceph/ceph/blob/master/SubmittingPatches.rst#fixes-lines to add the "Fixes" line and update the commit title to explain what the fix does

**Comment by kamoltat** [comment]
@neha-ojha I ran 18 tests on this and it passed successfully. Let me know if I should run more tests: https://pulpito.ceph.com/ksirivad-2020-11-17_04:43:46-rados:mgr-wip-mgr-progress-fix-48217-distro-basic-smithi/

**Comment by neha-ojha** [comment]
> @neha-ojha I ran 18 tests on this and it passed successfully. Let me know if I should run more tests: https://pulpito.ceph.com/ksirivad-2020-11-17_04:43:46-rados:mgr-wip-mgr-progress-fix-48217-distro-basic-smithi/

If there aren't any other tests exercising the progress module, then this is good.

**Review by neha-ojha — APPROVED** [review]
nit: how about changing the title to `qa/mgr/test_progress: add _get_osd_in_out_events to account for osd marked in/out events`?

**Comment by neha-ojha** [comment]
@epuertat @tchaikov does the auto labeler remove manually added labels? Seeing it in this PR.

**Comment by epuertat** [comment]
> @epuertat @tchaikov does the auto labeler remove manually added labels? Seeing it in this PR.

@neha-ojha I didn't know that. There's a [`sync-labels` option](https://github.com/marketplace/actions/labeler) that says "Whether or not to remove labels when matching files are reverted or no longer changed by the PR"... but the default value is `false`, so [it shouldn't be in effect](https://github.com/actions/labeler/blob/fa244eaba5c3a196c5312fbef1e5ff0cf5350dc5/src/main.ts#L55-L57):
```
    if (syncLabels && labelsToRemove.length) {
      await removeLabels(client, prNumber, labelsToRemove);
    }
```
In any case I saw this related issue: https://github.com/actions/labeler/issues/112

I'll try with explicitly disable the `sync-labels` option.

**Comment by tchaikov** [comment]
@kamoltat please use your own repo for creating topic branches. and also please note the title of a pull request is not the title of a commit, in future, i'd suggest use `git commit --amend` to update your commit and repush to update your change.

**Comment by smithfarm** [comment]
Just to supplement what @tchaikov said: here we have a descriptive PR title ("qa/mgr/test_progress: add _get_osd_in_out_events to account for osd marked in/out events") coupled with a bad, non-descriptive commit title ("qa/mgr/test_progress: fix bug 48217"), yet it's the commit title that enters the git history. The git history is what gets downloaded to each developer's computer and is shown in `git log`, while the github PR title only resides on github's servers and can only be seen via a web browser.

https://github.com/ceph/ceph/blob/master/SubmittingPatches.rst#descrihttps://github.com/ceph/ceph/blob/master/SubmittingPatches.rst#describe-your-changesbe-your-changes has more guidance on this subject.

**Comment by kamoltat** [comment]
@smithfarm I agree, my apologies for the bad commit title will try to improve for the next PRs/commits

**Pull request merged**
