### PR TITLE
pybind: do not import from "__future__" anymore

### PR DESCRIPTION
**Pull request by tchaikov**
## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by tchaikov** [comment]
jenkins test api

**Review by epuertat — APPROVED** [review]
Awesome! Have you used [`2to3`](https://docs.python.org/3/library/2to3.html), [`pyupgrade`](https://github.com/asottile/pyupgrade) or any similar helper? Additionally, it might be interesting to enforce from tox that these changes don't come back :D

**Review by jdurgin — APPROVED** [review]

**Comment by tchaikov** [comment]
@epuertat i was using `sed -i` and emacs =)

**Review by sebastian-philipp — APPROVED** [review]

**Comment by tchaikov** [comment]
- https://pulpito.ceph.com/kchai-2021-05-25_04:17:20-rados-wip-kefu-testing-2021-05-25-1039-distro-basic-smithi/
- https://pulpito.ceph.com/kchai-2021-05-25_14:42:43-rados-wip-kefu-testing-2021-05-25-2008-distro-basic-smithi/

failure tracked by

- https://tracker.ceph.com/issues/45423

**Pull request merged**
