### PR TITLE
doc/dev: mgr/dashboard: Visual regression tests for ceph dashboard

### PR DESCRIPTION
**Pull request by aaryanporwal**
Fixes: https://tracker.ceph.com/issues/52370
Part of: https://tracker.ceph.com/issues/47497
Documentation for PR #42328

Signed-off-by: Aaryan Porwal <aaryanporwal2233@gmail.com>

## Checklist
- [ ] References tracker ticket
- [x] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by aaryanporwal** [comment]
jenkins test dashboard

**Comment by aaryanporwal** [comment]
jenkins test dashboard

**Review by avanthakkar — APPROVED** [review]
LGTM!

**Review by pereman2 — APPROVED** [review]

**Review by nizamial09 — APPROVED** [review]

**Comment by nizamial09** [comment]
@alfonsomthd @aaryanporwal There's no tracker for this PR. I don't know if its necessary for this either.

**Comment by aaryanporwal** [comment]
> @alfonsomthd @aaryanporwal There's no tracker for this PR. I don't know if its necessary for this either.

I just created an issue on the tracker for the documentation: https://tracker.ceph.com/issues/47497
It's a subtask of: https://tracker.ceph.com/issues/47497

I've updated the commit message to add the `fixes` line as well.

**Pull request merged**
