### PR TITLE
mgr/dashboard: carbonize fs forms

### PR DESCRIPTION
**Pull request by nizamial09**
This commit also covers the nfs form

Fixes: https://tracker.ceph.com/issues/67663

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Comment by nizamial09** [comment]
jenkins test make check

**Comment by ivoalmeida** [comment]
Hi @nizamial09 

It looks good overall. Juts a few things to fix:

1. The order of the buttons is swapped on the form below. The primary action should be on the right (just 2 examples below but this needs to be fixed all over the application):
image
image


2. There's a weird space to the right of the checkbox when one clicks on the 'Hosts' form input. Plus there's an outline around the checkbox and label that I don't think should be there:
image

3. If I try to progress without filling in a required field I don't get an error message. Is this intentional?
image

4. The initial loading state of the 'Directory' field is clipped:

https://github.com/user-attachments/assets/2771fe1c-31c3-4974-80ae-62b9febbf0ca

5. When adding retention fields, the new fields are not taking up the full width of the row making they look misaligned to the field above:
image

6. The close button is focused as soon as ones opens this modal. 
image

7. The 'Hosts' field is not marked as required:
image

**Comment by ivoalmeida** [comment]
@nizamial09 is there a tracker for this?

**Comment by nizamial09** [comment]
Thank you @ivoalmeida for the review. I addressed all the comments and put the replies inline below and attached the tracker as well

> Hi @nizamial09
> 
> It looks good overall. Juts a few things to fix:
> 
> 1. The order of the buttons is swapped on the form below. The primary action should be on the right (just 2 examples below but this needs to be fixed all over the application):

Swapped them in the regular forms as well, initially i only did it for the modal-forms. I also moved the button to the right side of the form because it looked a bit weird on the left side with the primary button on the other side. I checked the carbon designs an i couldn't find anything against this.

> 2. There's a weird space to the right of the checkbox when one clicks on the 'Hosts' form input. Plus there's an outline around the checkbox and label that I don't think should be there:

Unfortunately thats the default behaviour of carbon and I did not customize it. Probably we can leave it there for now

> 3. If I try to progress without filling in a required field I don't get an error message. Is this intentional?

Fixed it

> 4. The initial loading state of the 'Directory' field is clipped:

Fixed it

> 5. When adding retention fields, the new fields are not taking up the full width of the row making they look misaligned to the field above

Fixed it too..

> 6. The close button is focused as soon as the modal is open.

Fixed it as well.

> 7. The 'Hosts' field is not marked as required:

Fixed this as well..

**Comment by nizamial09** [comment]
only thing left here now is to fix failing unit tests in one file which i am working on.. the e2es were passing for me locally. i'll wait to see whats going on in jenkins

**Comment by nizamial09** [comment]
fixed the unit test failures

**Review by ivoalmeida — COMMENTED** [review]
> > 2. There's a weird space to the right of the checkbox when one clicks on the 'Hosts' form input. Plus there's an outline around the checkbox and label that I don't think should be there:
> 
> Unfortunately thats the default behaviour of carbon and I did not customize it. Probably we can leave it there for now
> 

Hi @nizamial09 

Thanks for the improvements. Looks great.

Only nit is issue 2: The outline is indeed a carbon default but the massive padding to the left of the checkboxes is not. It is actually coming from a bootstrap's normalising stylesheet called ```_reboot.scss```. Until we fully remove bootstrap, you can fix this by adding the below reset to ```frontend/src/styles/ceph-custom/_basics.scss```:
```css
ol, ul {
  padding-left: 0;
}
```

Thanks

**Comment by nizamial09** [comment]
> > > 2. There's a weird space to the right of the checkbox when one clicks on the 'Hosts' form input. Plus there's an outline around the checkbox and label that I don't think should be there:
> > 
> > 
> > Unfortunately thats the default behaviour of carbon and I did not customize it. Probably we can leave it there for now
> 
> Hi @nizamial09
> 
> Thanks for the improvements. Looks great.
> 
> Only nit is issue 2: The outline is indeed a carbon default but the massive padding to the left of the checkboxes is not. It is actually coming from a bootstrap's normalising stylesheet called `_reboot.scss`. Until we fully remove bootstrap, you can fix this by adding the below reset to `frontend/src/styles/ceph-custom/_basics.scss`:
> 
> ```css
> ol, ul {
>   padding-left: 0;
> }
> ```
> 
> Thanks

thanks @ivoalmeida for this. updated it

**Review by ivoalmeida — APPROVED** [review]
thanks @nizamial09 

lgtm

**Comment by afreen23** [comment]
jenkins test api

**Comment by afreen23** [comment]
jenkins test api

**Comment by afreen23** [comment]
unit test failure:

```
 ● InputModalComponent › has the defined description

    expect(received).toBe(expected) // Object.is equality

    Expected: "Some description"
    Received: null

      250 |
      251 |   expectTextToBe(css: string, value: string) {
    > 252 |     expect(this.getText(css)).toBe(value);
          |                               ^
      253 |   }
      254 |
      255 |   clickElement(css: string) {

      at FixtureHelper.toBe [as expectTextToBe] (src/testing/unit-test-helper.ts:252:31)
      at src/app/shared/components/form-modal/form-modal.component.spec.ts:86:8
```

**Pull request merged**
