### PR TITLE
mgr/zabbix: encode string for Python 3 compatibility

### PR DESCRIPTION
**Pull request by smithfarm**
Fixes: https://tracker.ceph.com/issues/36318
Signed-off-by: Nathan Cutler <ncutler@suse.com>

- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by smithfarm** [comment]
My only reason for opening this is so the fix, which was proposed in the tracker, doesn't fall through the cracks. If there's a better way to implement the fix, either I can modify this PR or this PR could be replaced.

**Comment by smithfarm** [comment]
This is becoming more urgent - we have Python 3 users reporting that they are affected by this bug.

**Comment by smithfarm** [comment]
Looking elsewhere in the code I see `.encode('utf-8')` in many cases. However, according to

https://docs.python.org/3/library/stdtypes.html#str.encode

that is actually the default for Python 3. And I can only assume that `.encode()` is safe in Python 2.7 as well.

**Comment by tchaikov** [comment]
```
$ python2
Python 2.7.12 (default, Nov 12 2018, 14:36:49)
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.getdefaultencoding()
'ascii'
```

per the python2 document:

> Default encoding is the current default string encoding

probably we'd better specify `utf-8`?

**Pull request merged**
