### PR TITLE
Fix compile warning unused-result

### PR DESCRIPTION
**Pull request by yuyuyu101**
Signed-off-by: Haomai Wang <haomaiwang@gmail.com>

### CODE REVIEW

**Comment by yuyuyu101** [comment]
Fix #5621

**Comment by tchaikov** [comment]
@yuyuyu101 the build slave is offline today. so will test the fix in my local env and get back to you.

**Comment by tchaikov** [comment]
before the patch:
```
  CXX      msg/async/Event.o
msg/async/Event.cc: In member function ‘virtual void C_handle_notify::do_request(int)’:
msg/async/Event.cc:51:35: warning: ignoring return value of ‘ssize_t read(int, void*, size_t)’, declared with attribute warn_unused_result [-Wunused-result]
       read(fd_or_id, c, sizeof(c));
                                   ^
```

after the patch
```
  CXX      msg/async/Event.o

```

**Comment by yuyuyu101** [comment]
@tchaikov thanks

**Pull request merged**
