### PR TITLE
msg/async: reply a retry session message when connection is lossless

### PR DESCRIPTION
**Pull request by penglaiyxy**
Think of a cluster connection between osds. The server endpoint is rebooted.
Then Client has a op to send and will try to reconnect to the server endpoint.
After server is up, server finds the csq is not zero, and will send a reset session command,
even if the connection policy is lossless. It's better to send a retry session message with csq set to 0,
then the op in client will be kept. In some cases, the lost op will lead to inconsistent objects. We can
only find the inconsistent object after scrubbing.

Fixes: https://tracker.ceph.com/issues/42058
Signed-off-by: Xiangyang Yu <penglaiyxy@gmail.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`

</details>

### CODE REVIEW

**Comment by penglaiyxy** [comment]
@gregsfortytwo   What if the client endpoint has not received the new osdmap before the connection is reconnected ?  
In our cluster, the client osd(which is the primary osd) reconnected the server osd(which is a secondary osd) before updating the osdmap. First op is discarded because of the reset session(First op has already applied to client osd.). After the client osd updated the new osdmap and before pg peered,  a second op is send to server osd correctly(Also applied to the client osd). After the two ops are over. Client and server osds began to peer pgs. We would not find the server osd lost the first op, because the last pg log  are the same.

If I misunderstand some logical, please tell me.

**Comment by tchaikov** [comment]
```
186/186 Test  #14: test_objectstore_memstore.sh ............***Timeout 3600.12 sec
```

jenkins test make check

**Comment by penglaiyxy** [comment]
> ```
> 186/186 Test  #14: test_objectstore_memstore.sh ............***Timeout 3600.12 sec
> ```
> 
> jenkins test make check

Build step 'Execute shell' marked build as failure
[PostBuildScript] - Executing post build scripts.
[ceph-pull-requests] $ /bin/sh -xe /tmp/jenkins7870355846650710382.sh
+ sudo reboot
FATAL: Unable to delete script file /tmp/jenkins7870355846650710382.sh   ----> ？？？

Is there some problem with the jenkins test? I do not think it is related with the messenger module.

**Comment by gregsfortytwo** [comment]
> @gregsfortytwo What if the client endpoint has not received the new osdmap before the connection is reconnected ?
> In our cluster, there is no osd shutdown. There was some network problem with the client osd. The server osd update the osdmap and clean the connection with the client osd. When the network got well, the client osd(which is the primary osd) reconnected the server osd(which is a secondary osd) before updating the osdmap. First op is discarded because of the reset session(First op has already applied to client osd.). After the client osd updated the new osdmap and before pg peered, a second op is send to server osd correctly(Also applied to the client osd). After the two ops finished. Client and server osds began to peer pgs. We would not find the server osd lost the first op, because the last pg log are the same.
> 
> If I misunderstand some logical, please tell me.

Are you saying that there's corruption in this scenario?
As you've described it, I don't think this code path should even trigger: OSD connections are lossless so it will have an old Pipe to replace.

I'm not really understanding in which scenario a lossless connection could have (connect_seq > 0) and not know it's replacing a previous pipe; that shouldn't be possible except in a real reboot. In which case we definitely need to do a full reset.

**Comment by penglaiyxy** [comment]
> > @gregsfortytwo What if the client endpoint has not received the new osdmap before the connection is reconnected ?
> > In our cluster, there is no osd shutdown. There was some network problem with the client osd. The server osd update the osdmap and clean the connection with the client osd. When the network got well, the client osd(which is the primary osd) reconnected the server osd(which is a secondary osd) before updating the osdmap. First op is discarded because of the reset session(First op has already applied to client osd.). After the client osd updated the new osdmap and before pg peered, a second op is send to server osd correctly(Also applied to the client osd). After the two ops finished. Client and server osds began to peer pgs. We would not find the server osd lost the first op, because the last pg log are the same.
> > If I misunderstand some logical, please tell me.
> 
> Are you saying that there's corruption in this scenario?
> As you've described it, I don't think this code path should even trigger: OSD connections are lossless so it will have an old Pipe to replace.
> 
> I'm not really understanding in which scenario a lossless connection could have (connect_seq > 0) and not know it's replacing a previous pipe; that shouldn't be possible except in a real reboot. In which case we definitely need to do a full reset.

We found  inconsistent(scrub info inconsistent)  not corruption in this scenario.
The client osd is marked down  because of  heartbeat timeout. When the server osd found the down osd, it would mark down the connection with the client osd and clear the connection information. See  OSD::require_same_or_newer_map ->OSD::require_same_peer_instance -> AsyncConnection::mark_down. 
When the client osd later marked in  and the network got well,  the client osd began to  connect  the server osd and would discard any ops in out_q when the server osd sent a reset session msg.

**Comment by gregsfortytwo** [comment]
Okay but you’re not explaining the step from “the OSD threw out old messages” to “scrub detected an inconsistency”. I’m pretty sure these two things are not related and unless I’m misunderstanding there are a LOT of ways the patch you’ve presented here could cause other issues.

So I think it’s time to close this PR. Feel free to discuss more on the tracker ticket!

**Comment by penglaiyxy** [comment]
> Okay but you’re not explaining the step from “the OSD threw out old messages” to “scrub detected an inconsistency”. I’m pretty sure these two things are not related and unless I’m misunderstanding there are a LOT of ways the patch you’ve presented here could cause other issues.
> 
> So I think it’s time to close this PR. Feel free to discuss more on the tracker ticket!

@gregsfortytwo  Hi Greg, I have updated message in tracker, waiting for your reply.

**Comment by penglaiyxy** [comment]
@gregsfortytwo  Hi grep, I leave two messages on tracker. Waiting for your repy, thanks.
https://tracker.ceph.com/issues/42058

**Comment by penglaiyxy** [comment]
https://github.com/ceph/ceph/pull/17217

My problem can be resovled by the PR.

**Pull request closed without merging**
