### PR TITLE
Clean up endian handling

### PR DESCRIPTION
**Pull request by uweigand**
This is the second PR to address https://tracker.ceph.com/issues/41605.

This PR removes all remaining instances of the `__le16`/`__le32`/`__le64` types that were not already removed by the previous patches.  Specifically, this PR:
- changes several additional instances to `ceph_le16`/`ceph_le32`/`ceph_le64`, but in contexts where generated code is not affected (e.g. as argument to `sizeof`, or simply in a comment); and
- changes several instances to `uint16_t`/`uint32_t`/`uint64_t`, in cases where the objects in question are local and never used in contexts where byte-swapping would be required.

In addition, the PR removes the remaining (few) uses of `le16/32/64_to_cpu`.  These functions are not required when operating on `ceph_le` types (and have already been no-ops anyway).

In the end, this allows actual removal of the definitions of both the `__le16`/`__le32`/`__le64` types and the `le16/32/64_to_cpu` routines, so as to help avoid accidentally re-introducing incorrect uses of those with future code changes.

All changes in this PR should have no effect on the generated code on any platform.

(Note that once this PR is in, there is still one further PR that I'll submit for this issue, that one will make the member variable of the `ceph_le` types private to avoid accidentally bypassing the byte-swapping accessors.  Since this required some additional changes, I'll separate that out.)

### CODE REVIEW

**Comment by liewegas** [comment]
retest this please

**Comment by uweigand** [comment]
Patch updated to resolve merge conflict

**Comment by tchaikov** [comment]
- http://pulpito.ceph.com/kchai-2019-09-21_17:17:30-rados-wip-kefu-testing-2019-09-20-1944-distro-basic-mira/
- http://pulpito.ceph.com/kchai-2019-09-21_17:17:30-rados-wip-kefu-testing-2019-09-20-1944-distro-basic-mira/
- http://pulpito.ceph.com/kchai-2019-09-22_03:04:52-rados-wip-kefu-testing-2019-09-20-1945-distro-basic-mira/

failures tracked by

- https://tracker.ceph.com/issues/41744
- https://tracker.ceph.com/issues/41946

**Comment by uweigand** [comment]
> (Note that once this PR is in, there is still one further PR that I'll submit for this issue, that one will make the member variable of the ceph_le types private to avoid accidentally bypassing the byte-swapping accessors. Since this required some additional changes, I'll separate that out.)

Now submitted as https://github.com/ceph/ceph/pull/30526

Also submitted a final endian patch related to the bloom filter code: https://github.com/ceph/ceph/pull/30527

This completes all endian fixes I had in my tree.

**Pull request merged**
