### PR TITLE
qa/tests: add openstack volume info + lvs for ceph-volume

### PR DESCRIPTION
**Pull request by vasukulkarni**

### CODE REVIEW

**Comment by vasukulkarni** [comment]
Should fix couple of issues related to 'zap disk' failures we are seeing on master run, 

http://pulpito.ceph.com/vasu-2018-02-01_22:39:48-ceph-deploy-master-distro-basic-ovh/

**Comment by vasukulkarni** [comment]
I am surprised, my openstack is being overwritten by lower disk size in the run logs, thats why they failed.

"""
  openstack:
  - machine:
      cpus: 1
      disk: 10
      ram: 2000
    volumes:
      count: 2
      size: 10
"""

**Comment by djgalloway** [comment]
This isn't really something that should be up to me to approve IMO.

**Comment by yuriw** [comment]
@vasukulkarni ready for merge if it passed tests

**Comment by vasukulkarni** [comment]
http://pulpito.ceph.com/vasu-2018-03-10_03:23:21-ceph-deploy-master-distro-basic-ovh/

**Pull request merged**
