### PR TITLE
mimic: tests: upgrade/luminous-x: whitelist REQUEST_SLOW for rados_mon_thrash

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/25056

### CODE REVIEW

**Comment by smithfarm** [comment]
**running** http://pulpito.ceph.com/smithfarm-2018-07-21_18:44:33-upgrade:luminous-x-mimic-distro-basic-smithi/

**Comment by smithfarm** [comment]
@theanalyst @yuriw I believe this will fix the last remaining failures in `upgrade/luminous-x (mimic)` which would be nice to merge for 13.2.1 - doing a run to verify before merging. (Will need your approval)

**Comment by smithfarm** [comment]
Test run (see above comment for URL) **passed** with one unrelated failure -> opened http://tracker.ceph.com/issues/25076 to track

**Comment by yuriw** [comment]
@smithfarm I think we need it on `luminous` too, a?

**Comment by smithfarm** [comment]
@yuriw You mean in `upgrade/jewel-x` ? I don't know.

**Comment by smithfarm** [comment]
@yuriw This is already a backport of http://tracker.ceph.com/issues/25051 which was original marked "Backport: mimic, luminous" but I removed the luminous backport because luminous doesn't have `upgrade/luminous-x`.

AFAICR we have not seen this failure in `upgrade/jewel-x (luminous)`.

**Comment by yuriw** [comment]
I meant on `luminous' branch https://github.com/ceph/ceph/blob/luminous/qa/suites/upgrade/luminous-x/parallel/5-final-workload/rados_mon_thrash.yaml

**Comment by yuriw** [comment]
maybe not, we need to remove unused suites, confusing ...
mumbling to myself :)

**Comment by yuriw** [comment]
@smithfarm will try to remember do a clean up.

upgrade/*-client-x live on named branches, see 
https://github.com/ceph/ceph/blob/master/qa/crontab/teuthology-cronjobs

**Comment by smithfarm** [comment]
@yuriw Sorry, I must have been looking at something other than the tip of luminous. The state is different than I wrote, above.

Here's a first stab at the cleanup: https://github.com/ceph/ceph/pull/23293

**Pull request merged**
