### PR TITLE
build/ops: make package groups comply with openSUSE guidelines

### PR DESCRIPTION
**Pull request by smithfarm**
. . . and put all Group: lines in SUSE conditional blocks.

Fixes: http://tracker.ceph.com/issues/19184
Signed-off-by: Nathan Cutler <ncutler@suse.com>

### CODE REVIEW

**Comment by smithfarm** [comment]
pushed `wip-19184` to Shaman

**Comment by ktdreyer** [comment]
[Fedora's guidelines](https://fedoraproject.org/wiki/Packaging:Guidelines) say "The BuildRoot: tag, Group: tag, and %clean section SHOULD NOT be used."

Groups are defined in Fedora's comps now.

**Comment by smithfarm** [comment]
@b-ranto: The idea here is to completely eliminate the `Group:` tag for non-SUSE platforms for all RPMs. Before this patch, this was done for the main package but not for the subpackages.

**Comment by smithfarm** [comment]
Changelog:

* clarified the comments ("common" was misleading - change to "main package" and "subpackages")
* change several instances of `System/Libraries` to `System/Libraries/C and C++` for consistency

**Comment by smithfarm** [comment]
@b-ranto I went through it again and verified that this patch puts *all* `Group:` lines in SUSE conditionals.

**Comment by smithfarm** [comment]
> Isn't there any better group than System/Filesystems for the basic stuff?

The short answer to this question is "no".

**Comment by b-ranto** [comment]
You are right, it is all suse-specific. I did not notice the first conditional because it was not a part of the change.

**Comment by smithfarm** [comment]
Passes Shaman, but will wait to hear what the openSUSE:Factory reviewer has to say before merging it.

**Comment by smithfarm** [comment]
Rebased, changed `System/Libraries/C and C++` and `System/Libraries/Java` to just `System/Libraries`. Now waiting on second round of openSUSE review.

**Pull request merged**
