### PR TITLE
cephfs-journal-tool: correctly parse --dry_run argument

### PR DESCRIPTION
**Pull request by mchangir**
Correctly parse --dry_run argument and make it available to the
"recover_dentries" command.

Fixes: https://tracker.ceph.com/issues/44172
Signed-off-by: Milind Changire <mchangir@redhat.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by mchangir** [comment]
> It looks to me like the dry_run parameter only works for recover_dentries. If a user passes it to another command and expects nothing to happen in CephFS/RADOS, there's going to be a problem.
> 
> So probably we just need to fix whatever parsing Dan saw with recover_dentries and make sure it's clear the option only applies to that one command?

hmm;
Updated the PR with appropriate corrections;
@gregsfortytwo please review

**Comment by gregsfortytwo** [comment]
So if the user specifies dry-run on a command it's not implemented for, does that now return an error before it processes anything else? Or if the user specifies --dry-run after a normal command, will it run the command and then try to parse dry-run as another command and fail after having done work? What about if they specify dry-run before the recover_dentries command on the CLI?

**Comment by mchangir** [comment]
@gregsfortytwo 

> So if the user specifies dry-run on a command it's not implemented for, does that now return an error before it processes anything else?

Here's some examples where `--dry_run` is not accepted:
`$ ./bin/cephfs-journal-tool --rank a:0 event --dry-run`
`Error (2020-04-02T13:28:43.532+0530 7f05dd0bdc40 -1 main_event: Unknown argument '--dry-run'`
`(22) Invalid argument)
`

`$ ./bin/cephfs-journal-tool --rank a:0 event get --dry_run summary`
`Unknown argument: '--dry_run'`
`Error ((22) Invalid argument)
`

`$ ./bin/cephfs-journal-tool --rank a:0 event splice --dry_run list`
`Unknown argument: '--dry_run'`
`Error ((22) Invalid argument)
`


> Or if the user specifies --dry-run after a normal command, will it run the command and then try to parse dry-run as another command and fail after having done work?

`--dry_run` is acceptable only for the `recover_dentries` command; see examples above

> What about if they specify dry-run before the recover_dentries command on the CLI?

Here's what happens when `--dry_run` is mentioned before `recover_dentries` command:

`$ ./bin/cephfs-journal-tool --rank a:0 event --dry_run recover_dentries list`
`Error (2020-04-02T13:35:06.478+0530 7f9236c3ac40 -1 main_event: Unknown argument '--dry_run'`
`(22) Invalid argument)
`

Here's what happens when `--dry_run` is mentioned as the very first argument:

`$ ./bin/cephfs-journal-tool --dry_run --rank a:0 event recover_dentries summary`
`Error (2020-04-02T13:46:33.575+0530 7f1ebfbabc40 -1 main: missing mandatory "--rank" argument`
`(22) Invalid argument)`


Here's how it would really work:
`$ ./bin/cephfs-journal-tool --rank a:0 event recover_dentries --dry_run list`
`2020-04-02T13:27:26.490977+0530 0x400000 SUBTREEMAP:  ()
`

`$ ./bin/cephfs-journal-tool --rank a:0 event recover_dentries --dry_run summary`
`Events by type:`
`  SUBTREEMAP: 1`
`Errors: 0`



Here's a `recover_dentries` without `--dry_run`:
`$ ./bin/cephfs-journal-tool --rank a:0 event recover_dentries summary`
`Events by type:`
`  SUBTREEMAP: 1`
`Errors: 0`


Please note that the file-system on the vstart cluster is empty.

**Comment by gregsfortytwo** [comment]
http://pulpito.front.sepia.ceph.com/gregf-2020-04-15_20:54:50-fs-wip-greg-testing-415-1-distro-basic-smithi/ failures are https://tracker.ceph.com/issues/45133, https://tracker.ceph.com/issues/45103, and a couple rpm metadata download errors.

**Pull request merged**
