### PR TITLE
qa: fixed script to schedule rados and other suites with --subset option

### PR DESCRIPTION
**Pull request by yuriw**
changed script name
added kraken
parameterized suite name to be able to use for rados, rbd etc.

Signed-off-by: Yuri Weinstein yweinste@redhat.com

### CODE REVIEW

**Comment by yuriw** [comment]
test this please

**Comment by jdurgin** [comment]
seems fine to me - @dillaman?

**Comment by dillaman** [comment]
@yuriw Can you sign off on your commit message?

**Comment by yuriw** [comment]
@dillaman I think done, sorry

**Pull request merged**
