### PR TITLE
hammer: rados cppool omap to ec pool crashes osd

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/14718

### CODE REVIEW

**Comment by dachary** [comment]
@liewegas does this backport look good to merge ? It passed a run of the hammer rados suite ( see http://tracker.ceph.com/issues/14692#note-9 for details ). The upgrade/hammer suite also passes ( http://tracker.ceph.com/issues/14692#note-11 ) after a few tries to get rid of environmental noise.

**Comment by liewegas** [comment]
I'm not 100% certain we should backport this yet... @athanatos, can you look at https://github.com/SUSE/ceph/commit/2b4acfb1b808b98132a771cf1089063c0f7a75b5 and tell me if this seems like the right way to go?

Also, not sure we care about cppool breakage being backported.

**Comment by dachary** [comment]
@liewegas FYI in http://tracker.ceph.com/issues/14695#note-1 @athanatos suggests the backport is needed. Assigning to @athanatos for double confirmation.

**Comment by dachary** [comment]
@athanatos what do you think ?

**Comment by dachary** [comment]
It passed the hammer upgrade suite ( http://tracker.ceph.com/issues/14692#note-52 ) and the rados suite http://tracker.ceph.com/issues/14692#note-51).

**Comment by dachary** [comment]
@athanatos what do you think ?

**Comment by liewegas** [comment]
we don't like the original patch either, let's fix it better in master first.

**Pull request closed without merging**
