### PR TITLE
deb,rpm,do_cmake: switch to cmake3

### PR DESCRIPTION
**Pull request by tchaikov**
Signed-off-by: Kefu Chai <kchai@redhat.com>

### CODE REVIEW

**Comment by tchaikov** [comment]
https://shaman.ceph.com/builds/ceph/wip-cmake3/

**Comment by cbodley** [comment]
:+1: there's probably quite a bit of CMakeLists cleanup we can do now that we don't need to support 2.x

**Comment by tchaikov** [comment]
very true, i was actually working on a dummy library to mimic the behavior of the INTERFACE library for Boost::boost yesterday.

**Comment by alimaredia** [comment]
@tchaikov lgtm. Is the `cmake3` command different than the `cmake` command on rhel or is one just an alias for another?

**Comment by tchaikov** [comment]
@alimaredia the executable is named `cmake3` in the cmake3 package offered by EPEL. and it's not a symlink to `cmake`. i think EPEL repo make it so on purpose. so `cmake3` can co-exist with `cmake`.

**Comment by ktdreyer** [comment]
Requested review 14 hours ago, merged a few hours later... please wait a bit longer if you really want a review :)

**Comment by tchaikov** [comment]
@ktdreyer sorry for jumping the gun, i wanted to get your attention. and also wanted to get it merged ASAP. will wait longer next time.

**Comment by tchaikov** [comment]
[OT] @ktdreyer could you remark on https://www.spinics.net/lists/ceph-devel/msg41913.html ? i think the only fix crossed in my mind is to use `--allow-unauthenticated` .

**Comment by ktdreyer** [comment]
No prob Kefu :heart:

**Pull request merged**
