### PR TITLE
qa/tests: Changed -t from `py2` to default for `octopus`

### PR DESCRIPTION
**Pull request by yuriw**
Signed-off-by: Yuri Weinstein <yweinste@redhat.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by tchaikov** [comment]
i'd defer this review to @kshtsk. i haven't reviewed the teuthology change which introduced the auto "-t" support.

**Comment by kshtsk** [comment]
well, when I said `there is still -t py2 used for octopus` I was not scrupulous enough to mention that it is not only about octopus, we can remove any -t py2 from the schedule, can we add this to the PR or we can do that in follow up PR?

**Comment by yuriw** [comment]
@kshtsk I am open for either or.  Maybe let's merge this and  then remove `py2` from the rest ?

**Comment by yuriw** [comment]
I also removed `ceph-deploy` run on `mimic`

**Comment by kshtsk** [comment]
Added a follow up PR #35519

**Pull request merged**
