### PR TITLE
With root as default user, unable to have multiple RGW instances running

### PR DESCRIPTION
**Pull request by dachary**
http://tracker.ceph.com/issues/13227
http://tracker.ceph.com/issues/13225
http://tracker.ceph.com/issues/13343
http://tracker.ceph.com/issues/11735

### CODE REVIEW

**Comment by dachary** [comment]
@yehudasa does this backport look good to merge ? It passed a run of the hammer rgw suite ( see http://tracker.ceph.com/issues/13356#note-5 for details ).

**Comment by liewegas** [comment]
missing this commit: 9d8c115b0ab05cfc1db6670d1d367737e61fe0ea
otherwise, red hat still uses the .sysv script that doesn't actually get fixed.

@ktdreyer can you take a look?

**Comment by ktdreyer** [comment]
Agreed, https://github.com/ceph/ceph/commit/9d8c115b0ab05cfc1db6670d1d367737e61fe0ea is needed

**Comment by dachary** [comment]
in the gitbuilders, will run the ceph-deploy suite on CentOS 7 before merging to assert nothing stupid is broken

**Comment by liewegas** [comment]
cool lgtm

**Comment by dachary** [comment]
<pre>
teuthology-suite --machine-type vps --suite ceph-deploy --suite-branch hammer --ceph wip-13227-hammer --filter=centos_6 --email loic@dachary.org
</pre>

* *running* http://pulpito.ceph.com/loic-2015-10-12_23:46:42-ceph-deploy-wip-13227-hammer---basic-vps/

**Pull request merged**
