### PR TITLE
Updated Description 

### PR DESCRIPTION
**Pull request by nehaummareddy**
doc: Replaced with apt word and fixed grammatical error

Signed-off-by: Neha Ummareddy <nehaummareddy@gmail.com>

### CODE REVIEW

**Comment by dachary** [comment]
@nehaummareddy it looks like this should be fixed upstream (i.e. in the sphinx sources) ? Did you check if the same mistakes were done there ?

**Comment by nehaummareddy** [comment]
@dachary  Hey .. I am new to Open Source and  Ceph. Trying to figure out things. As far as I have understood I have checked but not very sure. I would be grateful If you could guide me further. Thanks a lot.

**Comment by dachary** [comment]
I thought this file was from https://github.com/sphinx-doc/sphinx/ (linked from http://sphinx-doc.org/develop.html ) but that is my mistake. Your fix looks good. All it needs is that you replace the commit message of 220ba48 with
<pre>
doc: Replaced with apt word and fixed grammatical error

Signed-off-by: Neha Ummareddy <nehaummareddy@gmail.com>
</pre>
I see you've correctly done that in the github web interface but it does not show in the git commit itself. In order to do that you should git rebase -i HEAD~2 and delete the line  with 44b19bb (that will get rid of this merge commit) and replace **pick** with **reword** on 220ba48. Once you save and quit the editor, it will give you a chance to update the commit message. After that you should git push --force (the --force is to rewrite the history, that is getting rid of the merge commit and rewriting the commit message)

**Comment by nehaummareddy** [comment]
Thanks a lot for your guidence. I have followed the steps you have asked me to.

**Comment by dachary** [comment]
@nehaummareddy you're almost there :-) The line starting with **doc:** must be the first line of the commit message. You can update the commit message with **git commit --amend** and when done **git push --force** again.

**Comment by nehaummareddy** [comment]
Done. Thank you so much for bearing with me and guiding me through.

**Comment by dachary** [comment]
@nehaummareddy there is one last thing: you need an empty line between the title of the commit and the signed-off-by line. Like so:
<pre>
doc: Replaced with apt word and fixed grammatical error

Signed-off-by: Neha Ummareddy &lt;nehaummareddy@gmail.com>
</pre>

**Comment by nehaummareddy** [comment]
Done.

**Comment by dachary** [comment]
@nehaummareddy and you need to git push --force also ;-)

**Comment by nehaummareddy** [comment]
yes I did. It shows everything up-to-date.

**Pull request merged**
