### PR TITLE
qa/tasks/cephadm: setup site based container registry

### PR DESCRIPTION
**Pull request by kshtsk**
Add containers registry mirror for 'docker.io' to the config
file /etc/containers/registries.conf

Since we need site based config, so each teuthology instance
could have own containers' mirror, store corresponding data
in /etc/teuthology.yaml under 'overrides/cephadm' task specific
section.

Signed-off-by: Kyr Shatskyy <kyrylo.shatskyy@suse.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by kshtsk** [comment]
@sebastian-philipp @tchaikov my question to you, what do  you expect if there is no config in found for the mirror or and image, what you guys think the test should do when using defaults values? At this moment it is just fails because image name is underfined? I can add an exception that containers_name should be declared in the config files, or just try and skip. If we want containers running out of our ceph-ci there should be some default values for image name at least in default registry, which are the correct values?

**Comment by sebastian-philipp** [comment]
Tbh I don't want anyone to run into the same issues. I'd simplify fail the task, if the registry is not set

**Comment by tchaikov** [comment]
jenkins test dashboard backend

**Comment by tchaikov** [comment]
- http://pulpito.ceph.com/kchai-2020-06-17_01:02:07-rados-wip-kefu-testing-2020-06-17-0030-distro-basic-smithi/
- http://pulpito.ceph.com/kchai-2020-06-17_08:41:50-rados-wip-kefu-testing-2020-06-17-1349-distro-basic-smithi/

test failure is tracked by https://tracker.ceph.com/issues/46046

**Pull request merged**
