### PR TITLE
blk/BlockDevice: use ceph_assertf() for assert

### PR DESCRIPTION
**Pull request by tchaikov**
also silences a warning like

src/blk/BlockDevice.cc:158:1: warning: label 'out_fail' defined but not used [-Wunused-label]
  158 | out_fail:
      | ^~~~~~~~

Signed-off-by: Kefu Chai <kchai@redhat.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by tchaikov** [comment]
cc @agayev

**Comment by agayev** [comment]
> cc @agayev

Thanks for the heads up!

**Comment by ifed01** [comment]
jenkins test make check

**Comment by tchaikov** [comment]
- https://pulpito.ceph.com/kchai-2020-07-13_15:11:10-rados-wip-kefu-testing-2020-07-13-2108-distro-basic-smithi/
- https://pulpito.ceph.com/kchai-2020-07-15_09:19:03-rados-wip-kefu-testing-2020-07-13-2108-distro-basic-smithi/

failures tracked / fixed by

- https://tracker.ceph.com/issues/46323
- #36091

**Pull request merged**
