### PR TITLE
pacific: cephadm: use quay, not docker

### PR DESCRIPTION
**Pull request by liewegas**
## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by liewegas** [comment]
retest this please

**Comment by dsavineau** [comment]
I think this needs to be updated with the changes on the monitoring container images

**Comment by liewegas** [comment]
jenkins test dashboard cephadm

**Comment by liewegas** [comment]
jenkins test dashboard cephadm

**Comment by liewegas** [comment]
jenkins test dashboard cephadm

**Comment by sebastian-philipp** [comment]
* https://pulpito.ceph.com/yuriw-2021-08-30_16:30:46-rados-wip-yuri5-testing-2021-08-30-0725-pacific-distro-basic-smithi
* http://pulpito.ceph.com/yuriw-2021-08-31_19:46:12-rados-wip-yuri5-testing-2021-08-30-0725-pacific-distro-basic-smithi/

Found unrelated issue: https://tracker.ceph.com/issues/52479

**Pull request merged**
