### PR TITLE
common: include <signal.h> in Preforker.h

### PR DESCRIPTION
**Pull request by wjwithagen**
Since it does use functions declared by signal.h

/home/jenkins/workspace/ceph-master/src/common/Preforker.h:50:5: error: use of undeclared identifier                                             'sigemptyset'
    sigemptyset(&sa.sa_mask);
    ^
/home/jenkins/workspace/ceph-master/src/common/Preforker.h:52:9: error: no matching constructor for                                             initialization of 'sigaction'
    if (sigaction(SIGHUP, &sa, nullptr) != 0) {
        ^         ~~~~~~~~~~~~~~~~~~~~
/usr/include/sys/signal.h:366:8: note: candidate constructor (the implicit copy constructor) not via                                            ble: requires 1 argument, but 3 were provided
struct sigaction {
       ^
/usr/include/sys/signal.h:366:8: note: candidate constructor (the implicit move constructor) not via                                            ble: requires 1 argument, but 3 were provided
/usr/include/sys/signal.h:366:8: note: candidate constructor (the implicit default constructor) not                                             viable: requires 0 arguments, but 3 were provided
2 errors generated.

fixes: https://github.com/ceph/ceph/pull/35844

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by smithfarm** [comment]
Note: tracker ticket may not be needed, because I have already staged the backport of #35844 to both octopus and nautilus, and the need for this fix has been mentioned in both of those PRs.

**Comment by smithfarm** [comment]
```
Test failures: 190 - unittest_rbd_mirror (Failed) 
```

**Comment by smithfarm** [comment]
jenkins test make check

**Comment by wjwithagen** [comment]
> 
> 
> Note: tracker ticket may not be needed, because I have already staged the backport of #35844 to both octopus and nautilus, and the need for this fix has been mentioned in both of those PRs.

Thanx, I had planned to look into exactly this today. But now I kan hunt for other stuff as well.

**Comment by smithfarm** [comment]
> Thanx, I had planned to look into exactly this today. But now I kan hunt for other stuff as well.

Thanks, Willem. As a follow-on fix for something that is already in the process of being backported, this one is a special case where the fix has to be included in the backport PRs of the original change that introduced the issue.

**Comment by tchaikov** [comment]
- https://pulpito.ceph.com/kchai-2020-07-21_07:32:05-rados-wip-kefu-testing-2020-07-21-0014-distro-basic-smithi/
- https://pulpito.ceph.com/kchai-2020-07-22_03:46:42-rados-wip-kefu-testing-2020-07-21-2148-distro-basic-smithi/
- https://pulpito.ceph.com/kchai-2020-07-22_06:32:16-rados-wip-kefu-testing-2020-07-22-1235-distro-basic-smithi/

**Pull request merged**
