### PR TITLE
quincy: RGW: allow user disabling presigned urls in rgw configuration

### PR DESCRIPTION
**Pull request by pr0ton11**
backport tracker: https://tracker.ceph.com/issues/65005

backport of #56044
parent tracker: https://tracker.ceph.com/issues/64797

### CODE REVIEW

**Comment by pr0ton11** [comment]
Seems like I need to remove the expired signature URL part as this has not been implemented in quincy yet? @cbodley

**Comment by cbodley** [comment]
> Seems like I need to remove the expired signature URL part as this has not been implemented in quincy yet? @cbodley

right, please remove those unrelated parts from your backport commits, and be sure to document that under Conflicts: in the commit message

**Comment by pr0ton11** [comment]
@cbodley The conflict commit has been pushed, so this can move forward

**Comment by pr0ton11** [comment]
@cbodley Sorry for pinging you, but we need this change in the next Ceph 17 minor version, as we are planning to upgrade soon

**Comment by cbodley** [comment]
the "Conflicts" commit and its commit message needs to be part of the same cherry-picked commit that introduced the conflict

> we need this change in the next Ceph 17 minor version, as we are planning to upgrade soon

it'll be a while before the backport team starts testing for the next quincy point release

**Comment by yuriw** [comment]
This PR is under test in [https://tracker.ceph.com/issues/65558](https://tracker.ceph.com/issues/65558).

**Comment by yuriw** [comment]
This PR is under test in [https://tracker.ceph.com/issues/65561](https://tracker.ceph.com/issues/65561).

**Comment by yuriw** [comment]
jenkins test api

**Comment by yuriw** [comment]
@pr0ton11 @cbodley pls approve and merge

ref: https://tracker.ceph.com/issues/65558

**Comment by yuriw** [comment]
This PR is under test in [https://tracker.ceph.com/issues/65638](https://tracker.ceph.com/issues/65638).

**Comment by pr0ton11** [comment]
> the "Conflicts" commit and its commit message needs to be part of the same cherry-picked commit that introduced the conflict
> 
> > we need this change in the next Ceph 17 minor version, as we are planning to upgrade soon
> 
> it'll be a while before the backport team starts testing for the next quincy point release

How do I get that to happen?

**Comment by yuriw** [comment]
jenkins test api

**Comment by pr0ton11** [comment]
I think this rebase should fix the issue

> @pr0ton11 the "Conflicts" commit and its commit message needs to be part of the same cherry-picked commit that introduced the conflict

I think this rebase should fix the issue

**Comment by smanjara** [comment]
jenkins test make check

**Comment by smanjara** [comment]
jenkins test make check

**Comment by yuriw** [comment]
jenkins test make check

**Review by cbodley — APPROVED** [review]

**Comment by yuriw** [comment]
jenkins test make check

**Comment by cbodley** [comment]
jenkins test make check

**Comment by pr0ton11** [comment]
Let me know on which version this could be released

**Comment by cbodley** [comment]
> Let me know on which version this could be released

thanks for the reminder, this will be in 17.2.8

**Pull request merged**
