### PR TITLE
include/types_fmt: use fmt::join() to format containers

### PR DESCRIPTION
**Pull request by tchaikov**
* use template parameter pack to represent container template argument,
  simpler this way. also, this enables us to print specialized
  classes which uses non-default template parameters.
* use fmt::join() to print container elements. see also
  https://fmt.dev/latest/api.html#_CPPv4I0EN3fmt4joinE9join_viewIN6detail10iterator_tI5RangeEEN6detail10sentinel_tI5RangeEEERR5Range11string_view

Signed-off-by: Kefu Chai <tchaikov@gmail.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [x] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by tchaikov** [comment]
it does not compile on our jenkins test node. i need to take a closer look.

**Review by ronen-fr — APPROVED** [review]
Indeed better than my PR

**Comment by ronen-fr** [comment]
@tchaikov : will re-approve after your checks, if needed. Ping me.

**Comment by tchaikov** [comment]
jenkins test make check

**Comment by tchaikov** [comment]
@ronen-fr thank you for the review and approval! could you take another look? it turns out that we need a new fmtlib to use `fmt::join()`, otherwise i'd have to teach it to consider `operator<<` when instantiating `fmt::join()`. i tried, but it turns out to be non-trivial. =(

**Comment by ronen-fr** [comment]
> @ronen-fr thank you for the review and approval! could you take another look? it turns out that we need a new fmtlib to use `fmt::join()`, otherwise i'd have to teach it to consider `operator<<` when instantiating `fmt::join()`. i tried, but it turns out to be non-trivial. =(

np. Just for my curiosity: why was there a problem with join()+'<<' in 6?

**Comment by ronen-fr** [comment]
LGTM

**Review by ronen-fr — APPROVED** [review]

**Comment by tchaikov** [comment]
> > @ronen-fr thank you for the review and approval! could you take another look? it turns out that we need a new fmtlib to use `fmt::join()`, otherwise i'd have to teach it to consider `operator<<` when instantiating `fmt::join()`. i tried, but it turns out to be non-trivial. =(
> 
> np. Just for my curiosity: why was there a problem with join()+'<<' in 6?

@ronen-fr see the commit message of b7b7ff4cce3669fba69e9468304465bacdc7b7c5. it seems i am not alone.

**Comment by tchaikov** [comment]
https://shaman.ceph.com/builds/ceph/wip-fmt-containers-kefu-2/

**Pull request merged**
