### PR TITLE
doc/start/os-recommendations: drop 4.14 kernel and reword guidance

### PR DESCRIPTION
**Pull request by idryomov**
The 4.14 LTS kernel has less than a year left in terms of maintenance, drop it.

Also, the current wording with an explicit list of kernels tends to go stale: it's missing the latest 6.1 LTS kernel.

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [x] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Review by zdover23 — APPROVED** [review]

**Comment by zdover23** [comment]
https://github.com/ceph/ceph/pull/51489 - Reef backport
https://github.com/ceph/ceph/pull/51490 - Quincy backport
https://github.com/ceph/ceph/pull/51491 - Pacific backport

**Comment by anthonyeleven** [comment]
Wish I'd seen this pre-merge, I suggest adding a note that 5.4 on KRBD clients is the minimum for reasonable RBD feature flag support.

**Comment by zdover23** [comment]
> Wish I'd seen this pre-merge, I suggest adding a note that 5.4 on KRBD clients is the minimum for reasonable RBD feature flag support.

I'll add that note and name you as a co-author and flag you as a reviewer if you give me the go-ahead right now.

**Comment by anthonyeleven** [comment]
Of course.

**Comment by anthonyeleven** [comment]
Lens^H^H^HPRcrafters ftw

**Comment by zdover23** [comment]
https://github.com/ceph/ceph/pull/51492 - followup PR

**Pull request merged**
