### PR TITLE
BUG #46369 mgr/dashboard: RBD namespace creation form gives incorrect…

### PR DESCRIPTION
**Pull request by navinbarnwal**
Fixed !!
Screenshot from 2021-04-23 14-44-55

Fixes: https://tracker.ceph.com/issues/46369
Signed-off-by: Kumar Navin Barnwal knbarnwal@gmail.com

### CODE REVIEW

**Comment by epuertat** [comment]
@navinbarnwal you need to correct some formalities, like PR and commit titles, and adding the signed-off line to the commit body as well. You can find a detailed explanation on [this guide for contributors](https://github.com/ceph/ceph/blob/master/SubmittingPatches.rst).

**Comment by navinbarnwal** [comment]
> @navinbarnwal you need to correct some formalities, like PR and commit titles, and adding the signed-off line to the commit body as well. You can find a detailed explanation on [this guide for contributors](https://github.com/ceph/ceph/blob/master/SubmittingPatches.rst).

I added the title as expected with signed-off-line to the commit body and got All 8 checks successful here #41008 . Please do have a check.
Just one question, Was it possible to send a commit again to this PR just by pushing another commit (I didn't wanted to cause trouble So I didn't try).
You can close this PR now.

**Comment by tchaikov** [comment]
> > @navinbarnwal you need to correct some formalities, like PR and commit titles, and adding the signed-off line to the commit body as well. You can find a detailed explanation on [this guide for contributors](https://github.com/ceph/ceph/blob/master/SubmittingPatches.rst).
> 
> I added the title as expected with signed-off-line to the commit body and got All 8 checks successful here #41008 . Please do have a check.
> Just one question, Was it possible to send a commit again to this PR just by pushing another commit (I didn't wanted to cause trouble So I didn't try).
> You can close this PR now.

i'd suggest avoid creating new PRs for addressing reviewers' comments. please see https://docs.ceph.com/en/latest/dev/developer_guide/basic-workflow/#amending-your-pr for more details.

**Comment by navinbarnwal** [comment]
> > > @navinbarnwal you need to correct some formalities, like PR and commit titles, and adding the signed-off line to the commit body as well. You can find a detailed explanation on [this guide for contributors](https://github.com/ceph/ceph/blob/master/SubmittingPatches.rst).
> > 
> > 
> > I added the title as expected with signed-off-line to the commit body and got All 8 checks successful here #41008 . Please do have a check.
> > Just one question, Was it possible to send a commit again to this PR just by pushing another commit (I didn't wanted to cause trouble So I didn't try).
> > You can close this PR now.
> 
> i'd suggest avoid creating new PRs for addressing reviewers' comments. please see https://docs.ceph.com/en/latest/dev/developer_guide/basic-workflow/#amending-your-pr for more details.

Thank you for the suggestion. I'll remember that next time. For now do you want me to follow that and commit to this PR or should I stick with the new one?

**Comment by tchaikov** [comment]
> Thank you for the suggestion. I'll remember that next time. For now do you want me to follow that and commit to this PR or should I stick with the new one?

i'd recommend commit to this PR to preserve the comments and the history of the changes.

**Comment by navinbarnwal** [comment]
> > Thank you for the suggestion. I'll remember that next time. For now do you want me to follow that and commit to this PR or should I stick with the new one?
> 
> i'd recommend commit to this PR to preserve the comments and the history of the changes.

Hi Kefu,
I tried to do as asked. I had trouble first time but next one would pass submission check 8/8 at 
https://github.com/ceph/ceph/pull/41001/commits/dce9c7c34927a4d937f1e40e6095aae66ea7c391

Please let me know if it's fine and Thank you for recommending me to do that.

**Comment by navinbarnwal** [comment]
> > Thank you for the suggestion. I'll remember that next time. For now do you want me to follow that and commit to this PR or should I stick with the new one?
> 
> i'd recommend commit to this PR to preserve the comments and the history of the changes.

Hi Kefu, I tried to do that. But couldn't accomplish. Please consider #41008 at present and I promise this won't happen again.

**Pull request closed without merging**
