### PR TITLE
DNM: jewel: ceph cli: Rados object in state configuring race

### PR DESCRIPTION
**Pull request by dachary**
http://tracker.ceph.com/issues/17385

### CODE REVIEW

**Comment by dachary** [comment]
test this please

**Comment by dachary** [comment]
test this please (no logs)

**Comment by dachary** [comment]
rebased

**Comment by dachary** [comment]
massive make check failure, needs to be tested manually because it ends up timeouting

**Comment by dachary** [comment]
jenkins test this please (no logs)

**Comment by smithfarm** [comment]
Jenkins retest this please (no logs)

**Comment by smithfarm** [comment]
@dachary If this causes "make test" to timeout every time, I guess we shouldn't merge it?

**Comment by dachary** [comment]
right. jenkins test this please (one last time)

**Pull request closed without merging**
