### PR TITLE
librbd: multiple cache writeback threads.

### PR DESCRIPTION
**Pull request by liyichao**
With rbd cache on, the flusher threads and tp_librbd threads are mutually exclusive by the cache lock, limiting librbd performance. According to cpu flames, most of the time is spent in LibrbdWriteback::write. By further analysis, LibrbdWriteback::write can run with cache lock unlocked and run concurrently using multiple threads.

According to one of my tests (4k randwrite), using default configuration, the iops is 22.7k(with avg latency 8.6ms, p99 latency 13.5ms), while with 4 writeback threads, the iops is 38.8k(avg/p99 latency=4.8ms/54.8ms), the improvement is 71%. In another test, 4 tp_librbd (with this pr https://github.com/ceph/ceph/pull/24483) with rbd cache off, the iops is 41.5k(avg/p99 latency=5.1ms/42.7ms), and 4 tp_librbd + 4 writeback threads the iops is 42.5k(avg/p99 latency=3.7ms/58.5ms), catching the rbd cache off case.

### CODE REVIEW

**Comment by liyichao** [comment]
#24483  has little effect when using rbd cache because tp_librbd threads are made mutually exclusive by the cache lock. This pr moves `request->send` out of the cache lock and makes it concurrent.

As to another thread pool, it may be ok to put the work back to tp_librbd, but this thread pool will be made sleep by cache lock even though there are `request->send` work in the queue, reducing throughput.

**Comment by liyichao** [comment]
> You are still moving the bulk of the work outside the lock which should still reduce the contention.

I do not quite understand this, could you please explain further?

This will improve librbd's performance significantly when rbd cache is on and multiple tp_librbd threads are used, do you mean if one wants the performance, rbd cache should be closed, so this patch is not needed?

**Comment by dillaman** [comment]
> > You are still moving the bulk of the work outside the lock which should still reduce the contention.
> 
> I do not quite understand this, could you please explain further?

If the librbd thread pool supports multiple threads and you queue up the actual write op to that thread pool, the amount of time the ```cache_lock``` the held is vastly reduced (so less contention and blocking).
 
> This will improve librbd's performance significantly when rbd cache is on and multiple tp_librbd threads are used, do you mean if one wants the performance, rbd cache should be closed, so this patch is not needed?

The librbd cache really only provides benefits for low IOPS workloads or sequential write workloads (since multiple writes can be combined into a single write op to the OSD). If you have a really high-performance cluster, I suspect you would most likely see better throughput by just disabling the cache even when compared to your changes (but worth a test).

**Comment by liyichao** [comment]
> If the librbd thread pool supports multiple threads and you queue up the actual write op to that thread pool, the amount of time the `cache_lock` the held is vastly reduced (so less contention and blocking).

You mean use tp_librbd to do the `request->send` work instead of a new thread pool? It seems ok.

> The librbd cache really only provides benefits for low IOPS workloads or sequential write workloads (since multiple writes can be combined into a single write op to the OSD). If you have a really high-performance cluster, I suspect you would most likely see better throughput by just disabling the cache even when compared to your changes (but worth a test).

I have tested. The performance of `4 tp_librbd + rbd cache off` is the nearly the same with the `4 tp_librbd + 4 tp_writeback + rbd cache on` case.

**Comment by liyichao** [comment]
@dillaman  , I have updated to use the thread pool tp_librbd, please have a look.

**Comment by dillaman** [comment]
Have you re-run your performance testing using the new approach? I'd be interested in the original vs new implementation under 1 vs 4 threads in the pool.

**Comment by liyichao** [comment]
These are numbers for 4k randwrite with 8 messenger and rbd cache on.
using tp_librbd:
* 4 tp_librbd: iops=37.2k/avg_lat=4.0ms/p99_lat=61.6ms
* 5 tp_librbd: 33.4k/avg_lat=4.4ms/p99_lat=59.0ms
* 8 tp_librbd: 33.6k/avg_lat=4.1ms/p99_lat=59.5ms

using tp_writeback:
* 1 tp_librbd + 4 tp_writeback: 38.8k/avg_lat=4.8ms/p99_lat=54.8ms
* 1 tp_librbd + 7 tp_writeback: 38.3k/avg_lat=5.0ms/p99_lat=61ms
* 4 tp_librbd + 4 tp_writeback: 40.8k/avg_lat=3.8ms/p99_lat=62.7ms

**Comment by engel75** [comment]
We do use rbd cache in our Openstack environment and we are limited to 23.000 IOPS by the cache. By disabling the cache we are able to deliver 66.000 IOPS in one VM but the latency (QD1) for write jumps from 85ys to 1.3ms. We are very interested in having the cache highiops limit improved. Will this feature exist in Nautilus?

**Comment by dillaman** [comment]
@engel75 No, this is not going to land in nautlius (expected to be released next week). Am I correct in assuming your QD1 tests involve sequential workloads (or perhaps a unrealistically large cache size to help w/ those IOPS rates)? PR #26675 is a work-in-progress to replace the cache w/ an IO scheduler (to batch sequential IO operations together just like the cache).

**Comment by dillaman** [comment]
@liyichao It would be great if you could test again after the recent addition of the default "writearound" cache policy. Below are the numbers I get on my machine. All tested w/ QD=32, 4K random writes, 4 tp_librbd threads and 8 async messenger threads, and "rbd_cache_writethrough_until_flush = false": 

* RBD cache disabled *
23.9k/avg_lat=1.3ms/p99_lat=2.9ms

* RBD writeback cache *
16.3k/avg_lat=2.0ms/p99_lat=3.1ms

* RBD writearound cache *
25.0k/avg_lat=1.3ms/p99_lat=2.4ms

**Pull request closed without merging**
