### PR TITLE
[DNM] hammer: rbd: fix coding mistake in pre-refactor rbd CLI

### PR DESCRIPTION
**Pull request by YankunLi**
http://tracker.ceph.com/issues/17671

### CODE REVIEW

**Comment by tchaikov** [comment]
could you prefix the title of your commit message with the subcomponent your are changing ? see https://github.com/ceph/ceph/blob/master/SubmittingPatches.rst#preparing-and-sending-patches, in this case, "rbd: " would suffice.

@smithfarm do we need a ticket for this issue?

**Comment by dillaman** [comment]
lgtm

**Comment by smithfarm** [comment]
@tchaikov Yes, I opened the tracker issue and linked it.

**Comment by smithfarm** [comment]
@YankunLi Could you rebase please?

**Comment by smithfarm** [comment]
@YankunLi Please also add a line `Fixes: http://tracker.ceph.com/issues/17671` to the commit message, right above the `Signed-off-by:` line. Thanks.

**Comment by YankunLi** [comment]
@smithfarm, Thinks, i have rebase this branch, and update the comment.

**Comment by smithfarm** [comment]
@YankunLi Please rebase again to get rid of the merge commit. First, `git rebase -i HEAD~2` and then, in the editor that appears, delete the line corresponding to the merge commit. Then save and exit from the editor. Then `git push -f origin fix_bug_EXPORT_DIFF1` to force-push the changes to github. Thanks!

**Comment by smithfarm** [comment]
Marking DNM (and replacing with https://github.com/ceph/ceph/pull/11948 ) until we can get the merge commit removed.

**Comment by smithfarm** [comment]
@YankunLi Please rebase again to get rid of the merge commit. First, `git rebase -i HEAD~2` and then, in the editor that appears, delete the line corresponding to the merge commit. Then save and exit from the editor. Then `git push -f origin fix_bug_EXPORT_DIFF1` to force-push the changes to github. 

Please do *not* use "git merge" because that introduces additional merge commits that are undesirable.

**Comment by smithfarm** [comment]
@YankunLi I'm closing this for now, because #11948 has already been reviewed and tested. 

Your help with backports and stable releases is most welcome. Please consider studying tutorials on "git interactive rebasing" and "git commit --amend" for modifying PRs.

**Pull request closed without merging**
