### PR TITLE
CMakeLists.txt: fix the manpage location for FreeBSD

### PR DESCRIPTION
**Pull request by wjwithagen**
Signed-off-by: Willem Jan Withagen <wjw@digiware.nl>

### CODE REVIEW

**Comment by tchaikov** [comment]
we discussed this before, see #13301

**Comment by wjwithagen** [comment]
I knew that I had discussion about this, but I thought it was at the FreeBSD end.
Your memory is way better than mine.

I guess that the resolution was to set a CMAKE var to actually fix this, then the new question becomes why my new ports tests runs are throwing a fit on the wrong location. AKA how did this setting get lost. 
Perhaps putting this in, is a more future safe sollution?

**Comment by tchaikov** [comment]
@wjwithagen i think we had reached a convergence. maybe you can reference `do_freebsd.sh` next time. if `-DCEPH_MAN_DIR=man` fails to work for you, then we need to fix it instead.

**Comment by wjwithagen** [comment]
@tchaikov 
Closed the PR.... 
Not sure why it got lost on the FreeBSD port. But it (can be)|(needs to be_ there.

**Pull request closed without merging**
