### PR TITLE
mgr/dashboard: Landing page v3

### PR DESCRIPTION
**Pull request by Pegonzal**
New landing page

tracker: https://tracker.ceph.com/issues/57861

Co-authored-by: bryanmontalvan <bmontalv@redhat.com>
Co-authored-by: Nizamudeen A <nia@redhat.com>
Signed-off-by: Pedro Gonzalez Gomez [pegonzal@redhat.com](mailto:pegonzal@redhat.com)

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [x] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [x] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by Pegonzal** [comment]
jenkins test windows

**Comment by nizamial09** [comment]
@Pegonzal as discussed earlier, let's try to squash this into one for each card.

**Comment by Pegonzal** [comment]
> @Pegonzal as discussed earlier, let's try to squash commits into one for each card.

Done! @nizamial09 , hope this works better, let me know what you think

**Comment by nizamial09** [comment]
> > @Pegonzal as discussed earlier, let's try to squash commits into one for each card.
> 
> Done! @nizamial09 , hope this works better, let me know what you think

Looks mostly good. Let's make it even more less and keep only these commits.
```
mgr/dashboard: dashboard-v3: details card
mgr/dashboard: dashboard-v3: capacity card
mgr/dashboard: dashboard-v3: status card
mgr/dashboard: dashboard-v3: inventory card
mgr/dashboard: dashboard-v3: cluster-utilization card
```

Also, I hope we have individual trackers for each of these cards. If so, let's put those trackers individually on each cards. WDYT?

**Comment by Pegonzal** [comment]
> > > @Pegonzal as discussed earlier, let's try to squash commits into one for each card.
> > 
> > 
> > Done! @nizamial09 , hope this works better, let me know what you think
> 
> Looks mostly good. Let's make it even more less and keep only these commits.
> 
> ```
> mgr/dashboard: dashboard-v3: details card
> mgr/dashboard: dashboard-v3: capacity card
> mgr/dashboard: dashboard-v3: status card
> mgr/dashboard: dashboard-v3: inventory card
> mgr/dashboard: dashboard-v3: cluster-utilization card
> ```
> 
> Also, I hope we have individual trackers for each of these cards. If so, let's put those trackers individually on each cards. WDYT?


Sure, makes sense, we can go for it, however, at the very least I guess we would need one other commit for the stuff that is not related to any of the cards in particular but are changes to the whole layout or landing page. As some of the commits left to squash, have different changes across the whole landing page it doesn't seem apppropiate to include those changes on one card specificly, do you agree?

**Comment by nizamial09** [comment]
> > > > @Pegonzal as discussed earlier, let's try to squash commits into one for each card.
> > > 
> > > 
> > > Done! @nizamial09 , hope this works better, let me know what you think
> > 
> > 
> > Looks mostly good. Let's make it even more less and keep only these commits.
> > ```
> > mgr/dashboard: dashboard-v3: details card
> > mgr/dashboard: dashboard-v3: capacity card
> > mgr/dashboard: dashboard-v3: status card
> > mgr/dashboard: dashboard-v3: inventory card
> > mgr/dashboard: dashboard-v3: cluster-utilization card
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Also, I hope we have individual trackers for each of these cards. If so, let's put those trackers individually on each cards. WDYT?
> 
> Sure, makes sense, we can go for it, however, at the very least I guess we would need one other commit for the stuff that is not related to any of the cards in particular but are changes to the whole layout or landing page. As some of the commits left to squash, have different changes across the whole landing page it doesn't seem apppropiate to include those changes on one card specificly, do you agree?

Okay makes sense. Lets keep one for the style fixes as well.

**Comment by nizamial09** [comment]
Also, don't remember to include Bryan as well as a co-author of this PR ;)

**Review by nizamial09 — APPROVED** [review]

**Pull request merged**
