### PR TITLE
cmake: update description for cmake module Findkeyutils.cmake

### PR DESCRIPTION
**Pull request by runsisi**
the original description was copy & pasted from `Findgperftools.cmake`

Signed-off-by: runsisi <runsisi@zte.com.cn>

### CODE REVIEW

**Comment by tchaikov** [comment]
```
Recording test results
FATAL: org.acegisecurity.providers.UsernamePasswordAuthenticationToken cannot be cast to org.jenkinsci.plugins.GithubAuthenticationToken
java.lang.ClassCastException: org.acegisecurity.providers.UsernamePasswordAuthenticationToken cannot be cast to org.jenkinsci.plugins.GithubAuthenticationToken
	at org.jenkinsci.plugins.GithubSecurityRealm.loadUserByUsername(GithubSecurityRealm.java:644)
```

@alfredodeza seems like a known issue https://issues.jenkins-ci.org/browse/JENKINS-25791

**Comment by alfredodeza** [comment]
test this please

**Comment by alfredodeza** [comment]
@tchaikov thanks for the ping, we are good now :)

**Comment by alimaredia** [comment]
@tchaikov this looks good to me. Did it get lost in the fray?

**Pull request merged**
