### PR TITLE
nautilus: mgr/dashboard: check embedded Grafana dashboard references

### PR DESCRIPTION
**Pull request by bk201**
backport trackers:

* https://tracker.ceph.com/issues/42947
* https://tracker.ceph.com/issues/42956

---

backport of:

* https://github.com/ceph/ceph/pull/28234
* https://github.com/ceph/ceph/pull/31750

parent trackers:

* https://tracker.ceph.com/issues/40008
* https://tracker.ceph.com/issues/42892

this backport was staged using ceph-backport.sh version 15.0.0.6950
find the latest version at https://github.com/ceph/ceph/blob/master/src/script/ceph-backport.sh

### CODE REVIEW

**Comment by bk201** [comment]
jenkins test dashboard backend

**Comment by bk201** [comment]
jenkins test dashboard

**Comment by smithfarm** [comment]
Let's not use `ready-to-merge` for nautilus PRs. Thanks.

**Comment by callithea** [comment]
- [pkg build](https://shaman.ceph.com/builds/ceph/wip-laura-testing-dashboard-nautilus-batch-6/69356e56d38be5d7ff3dd7a80bce0a9780b521ee/default/) was successful
- [rados/dashboard QA run](http://pulpito.ceph.com/laura-2020-01-06_12:44:54-rados:dashboard-wip-laura-testing-dashboard-nautilus-batch-6-distro-basic-mira/) passed

**Comment by bk201** [comment]
jenkins test dashboard

**Comment by bk201** [comment]
jenkins test make check

**Comment by bk201** [comment]
jenkins retest this please

**Comment by smithfarm** [comment]
jenkins test make check

**Comment by callithea** [comment]
make check failed with:
```> ceph-dashboard@0.0.0 test:config /home/jenkins-build/build/workspace/ceph-pull-requests/src/pybind/mgr/dashboard/frontend
> if [ ! -e 'src/unit-test-configuration.ts' ]; then cp 'src/unit-test-configuration.ts.sample' 'src/unit-test-configuration.ts'; fi

........................................................................................
  ● PoolDetailsComponent › Pool details tabset › returns pool details correctly

    HttpErrorResponse: Http failure response for api/summary: 0 Unknown Error

      82 |     });
      83 | 
    > 84 |     it('returns pool details correctly', () => {
         |     ^
      85 |       const pool = { prop1: 1, cdIsBinary: true, prop2: 2, cdExecuting: true, prop3: 3 };
      86 |       const expectedPool = { prop1: 1, prop2: 2, prop3: 3 };
      87 | 

      at new Spec (node_modules/jest-jasmine2/build/jasmine/Spec.js:116:22)
      at env.(anonymous function) (node_modules/jest-zone-patch/index.js:87:27)
      at src/app/ceph/pool/pool-details/pool-details.component.spec.ts:84:5
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invoke (node_modules/zone.js/dist/zone.js:391:26)
      at Zone.Object.<anonymous>.Zone.run (node_modules/zone.js/dist/zone.js:150:43)
      at Suite.<anonymous> (node_modules/jest-zone-patch/index.js:39:40)
      at env.(anonymous function) (node_modules/jest-zone-patch/index.js:69:27)
      at src/app/ceph/pool/pool-details/pool-details.component.spec.ts:36:3
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invoke (node_modules/zone.js/dist/zone.js:391:26)
      at Zone.Object.<anonymous>.Zone.run (node_modules/zone.js/dist/zone.js:150:43)
      at Suite.<anonymous> (node_modules/jest-zone-patch/index.js:39:40)
      at env.(anonymous function) (node_modules/jest-zone-patch/index.js:69:27)
      at Object.<anonymous> (src/app/ceph/pool/pool-details/pool-details.component.spec.ts:12:1)

............................................................................................................................

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ceph-dashboard@0.0.0 test:ci: `npm run test:config && JEST_SILENT_REPORTER_DOTS=true jest --coverage --reporters jest-silent-reporter`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ceph-dashboard@0.0.0 test:ci script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/jenkins-build/.npm/_logs/2020-01-16T11_11_57_225Z-debug.log
Linting "ceph-dashboard"...
no-use-before-declare is deprecated. Since TypeScript 2.9. Please use the built-in compiler checks instead.


All files pass linting.
Linting "ceph-dashboard-e2e"...


All files pass linting.
All files pass linting

> ceph-dashboard@0.0.0 i18n:extract /home/jenkins-build/build/workspace/ceph-pull-requests/src/pybind/mgr/dashboard/frontend
> ng xi18n --i18n-format xlf --i18n-locale en-US --output-path locale --progress=false && ngx-extractor -i 'src/**/*.ts' -f xlf -o src/locale/messages.xlf -l en-US


167/167 Test   #1: run-rbd-unit-tests.sh ...................   Passed  1128.28 sec

99% tests passed, 1 tests failed out of 167

Total Test time (real) = 1128.43 sec

The following tests FAILED:
	127 - mgr-dashboard-frontend-unittests (Failed)
```

**Comment by bk201** [comment]
> api/summary: 0 Unknown Error

This random error is tracked on https://tracker.ceph.com/issues/42929

**Comment by callithea** [comment]
jenkins test make check

**Comment by callithea** [comment]
Scheduled QA runs:
- [rados/mgr](http://pulpito.ceph.com/laura-2020-02-04_17:10:38-rados:mgr-wip-laura-testing-dashboard-nautilus-batch-8-distro-basic-smithi/) [WIP]
- [rados/dashboard](http://pulpito.ceph.com/laura-2020-02-04_17:10:06-rados:dashboard-wip-laura-testing-dashboard-nautilus-batch-8-distro-basic-smithi/)  [WIP]

**Pull request merged**
