### PR TITLE
osd/erasure-code: fix osd corruption when appending a deleted object

### PR DESCRIPTION
**Pull request by wuxingyi**
We should complain the bad offset to append to the client to avoid osd corruption.

see more details on #11573: http://tracker.ceph.com/issues/11573

### CODE REVIEW

**Comment by wuxingyi** [comment]
any ideas about the problem of "ceph-detect-init"? It seems that it has nothing to do with patch.

**Comment by dachary** [comment]
@wuxingyi I'll look into it

**Comment by dachary** [comment]
@wuxingyi could you please rebase and repush ?

**Comment by wuxingyi** [comment]
hi, @dachary , rebased and repushed.

**Comment by tchaikov** [comment]
i repeated your steps described in http://tracker.ceph.com/issues/11573, but unable to reproduce the crash on master.  my test case is attached at http://tracker.ceph.com/issues/11573.

@wuxingyi could you please add a test case for it? you might want to put it into `test/erasure-code/test-erasure-code.sh`.  thank you! =)

**Comment by wuxingyi** [comment]
hi，@tchaikov，
 I found a print error in my script http://tracker.ceph.com/issues/11573, 
    filename=`date +Y%m%d%H%M%S`
    dd if=/dev/zero of=$filename bs=64M count=1
    rados put -p TESTECPOOLDELETE $filename $filename x%x
    sleep 2 
    rados rm -p TESTECPOOLDELETE $filename
on the third line, when I mean "&", the tracker website seems to transform it to "x%x".

could you please run it again with "rados put -p TESTECPOOLDELETE $filename $filename &"?
thank you so much~

**Comment by tchaikov** [comment]
@wuxingyi sure. will do. it sounds like a race condition...

**Comment by tchaikov** [comment]
@wuxingyi, as it is marked as a dup on http://tracker.ceph.com/issues/11573, i am closing it. please feel free to reopen it if you think otherwise. thanks =)

**Comment by Jeegn-Chen** [comment]
I encounter the issue as well.
We saw the issue because 2 test scripts happened to upload the same file to a RGW with the same multipart upload ID almost at the same time. As a result, when the first script was uploading part 1, the second script tried to upload the same part as well. So the request from the second script tried to remove part 1 being uploaded by the first script. So concurrent put and rm showed up and kill the OSDs.

**Pull request closed without merging**
