### PR TITLE
global: output usage on -h, --help, or no args before contacting mons

### PR DESCRIPTION
**Pull request by liewegas**
- when there are no arguments, print a short invitation to stderr to use -h or --help and exit with an error.
- if we get -h or --help, print usage to stdout, and exit with success.
- do the above *before* making any contact with the cluster.  we should not fail to explain usage because the mons are down.
- if there is some other error with the arguments, print an error message, but do not spam the user with usage.  Try to use cerr instead of derr.

### CODE REVIEW

**Comment by alfredodeza** [comment]
This will address this very old tracker ticket http://tracker.ceph.com/issues/6242

Thank you Sage!

**Comment by liewegas** [comment]
retest this please

**Comment by liewegas** [comment]
http://pulpito.ceph.com/sage-2018-03-15_16:13:13-rados-wip-sage-testing-2018-03-15-0843-distro-basic-smithi/

**Comment by liewegas** [comment]
@jcsp ping

**Comment by batrick** [comment]
Note for posterity: http://tracker.ceph.com/issues/23624

**Pull request merged**
