### PR TITLE
FileJournal: Remove obsolete _check_disk_write_cache function

### PR DESCRIPTION
**Pull request by badone**
_check_disk_write_cache issues a warning about a bug that existed in the linux
kernel prior to version 2.6.33. This check/warning should be obsolete in master.

Signed-off-by: Brad Hubbard <bhubbard@redhat.com>

### CODE REVIEW

**Comment by jdurgin** [comment]
sounds good to remove, should get rid of the declaration too

**Comment by badone** [comment]
Thanks @jdurgin removed now :)

**Comment by badone** [comment]
I need to add to this so setting DNM for now

**Comment by badone** [comment]
Added commit to remove the dependency on hdparm/sdparm

**Comment by jdurgin** [comment]
lgtm

**Comment by tchaikov** [comment]
tested at http://pulpito.ceph.com/kchai-2016-09-19_07:07:02-rados-wip-kefu-testing---basic-mira/

failure caused by known issue  http://tracker.ceph.com/issues/17257

**Pull request merged**
