### PR TITLE
crimson/osd: implement basic reactor-utilization stats report to log

### PR DESCRIPTION
**Pull request by cyx1231st**
Signed-off-by: Yingxin Cheng <yingxin.cheng@intel.com>

As discussed with @Matan-B, it is helpful to watch critical stats (such as reactor-utilization) from logs. So there is no need to implement scripts to request/collect them during performance tests.

Disable by default.

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [x] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Review by athanatos — APPROVED** [review]

**Review by liu-chunmei — APPROVED** [review]

**Comment by Matan-B** [comment]
Cool! We can enable `crimson_osd_stat_interval` in the testing suite for sanity checks

**Comment by cyx1231st** [comment]
> We can enable crimson_osd_stat_interval in the testing suite for sanity checks

RU is useful to understand how busy a seastar application is at real time, together with CPU utilization, which should be an important indicator during performance tests/tunings.

Testing suites are built in debug mode to validate features, so I suppose RU isn't useful there.

Probably other important stats can be added for sanity checks, and we can enable it then.

**Comment by cyx1231st** [comment]
jenkins test make check

**Comment by cyx1231st** [comment]
https://pulpito.ceph.com/yingxin-2024-04-11_01:17:19-crimson-rados-ci-yingxin-crimson-osd-report-stats-distro-default-smithi/
* 7651631: seems to be a new and unrelated failure in tri-mutex, reported as https://tracker.ceph.com/issues/65451
* 7651641: https://tracker.ceph.com/issues/62162

For https://tracker.ceph.com/issues/65451, probably can be addressed by https://github.com/ceph/ceph/pull/55488/commits/3a6332fd6676da590b9ede46954b2a6a74308bd7 from https://github.com/ceph/ceph/pull/55488

Is the test result reasonable to you? @Matan-B

**Review by Matan-B — APPROVED** [review]
> https://pulpito.ceph.com/yingxin-2024-04-11_01:17:19-crimson-rados-ci-yingxin-crimson-osd-report-stats-distro-default-smithi/
> 
> * 7651631: seems to be a new and unrelated failure in tri-mutex, reported as https://tracker.ceph.com/issues/65451
> * 7651641: https://tracker.ceph.com/issues/62162
> 
> For https://tracker.ceph.com/issues/65451, probably can be addressed by [3a6332f](https://github.com/ceph/ceph/commit/3a6332fd6676da590b9ede46954b2a6a74308bd7) from #55488
> 
> Is the test result reasonable to you? @Matan-B

LGTM.  https://tracker.ceph.com/issues/65451 doesn't seem to be related to this PR.

**Pull request merged**
