### PR TITLE
doc: Fixes all "Qemu" to uppercase

### PR DESCRIPTION
**Pull request by scienceluo**
"QEMU" looks more professional

Signed-off-by: luo kexue luo.kexue@zte.com.cn

### CODE REVIEW

**Comment by tchaikov** [comment]
@scienceluo maybe we can piggyback this change with another one which, for example,  improves the doc in a more significant way ?

**Comment by tchaikov** [comment]
@scienceluo maybe we can piggyback this change with another one which, for example,  improves the doc in a more significant way ?

**Comment by xiexingguo** [comment]
@scienceluo I am with @tchaikov.

**Comment by tchaikov** [comment]
closing. let me know if you think otherwise.

**Comment by scienceluo** [comment]
@tchaikov @xiexingguo 
You mean make two commits into one?
 I didn't mean to play tricks, but the truth is I can not commit two files at web-github in one commit.
Ok,I will use cli-tool to commit
Thanks for your advices.

**Comment by scienceluo** [comment]
Ok, Thanks for your advice. @tchaikov

**Pull request closed without merging**
