### PR TITLE
[DNM] mds: miscellaneous multimds fixes 

### PR DESCRIPTION
**Pull request by ukernel**
Fixes: http://tracker.ceph.com/issues/20677
Signed-off-by: "Yan, Zheng" <zyan@redhat.com>

### CODE REVIEW

**Comment by batrick** [comment]
@ukernel Zheng, please keep issue fixes in separate PRs from your misc. fixes. Otherwise it is difficult to backport because the cherry-picker is not sure which commits belong with the issue fix.

**Comment by batrick** [comment]
@ukernel is this okay to merge?

**Comment by batrick** [comment]
I'll go ahead and run it through testing to see...

**Comment by ukernel** [comment]
Yes, it it

**Pull request merged**
