### PR TITLE
rgw: continuation token doesn't work in list object v2 request.

### PR DESCRIPTION
**Pull request by zhangsw**
Fixes: tracker.ceph.com/issues/40728

Signed-off-by: zhang Shaowen <zhangshaowen@cmss.chinamobile.com>

### CODE REVIEW

**Comment by zhangsw** [comment]
@mattbenjamin There's no test case for non-empty continuation token. I've added one. https://github.com/ceph/s3-tests/pull/291

**Comment by alimaredia** [comment]
@zhangsw @albIN7 Do you know what will happen right now if a string that is not in the list of keys in a bucket is passed in as the continuation token? I noticed we're not testing that either.

**Comment by zhangsw** [comment]
@alimaredia At present `continuation token` works just like a marker. If it'not in the list of keys in a bucket, it will return key names after specific object key. Amazon's `continuation token`  is an opaque value that Amazon S3 understands, not just an object's name. Maybe we need another PR for  `continuation token` working as same as S3.

**Comment by cbodley** [comment]
> Maybe we need another PR for continuation token working as same as S3

@zhangsw do you know of any advantage we could get from turning our continuation token into an opaque string?

**Comment by zhangsw** [comment]
@cbodley Maybe we can generate the continuation token like sts token.

**Comment by mattbenjamin** [comment]
@zhangsw this does not make sense.  the point of something being opaque is to remove the obligation of the implementation to honor a client's assumptions about the 'thing' (here token)'s internal structure;  hence this is an opportunity to make tokens that represent unique RGW states or to make it apparently arbitrary (so long as we can somehow use it as a continuation);  it IN NO WAY implies that our tokens need to be "uninterpretable" nor that they "work like Amazon's"--except in the exact sense that they function as continuations;  hence, unless otherwise noted, we are perfectly free to send our old markers as continuation tokens--and moreover, we should do so until we have some more efficient structure for them;  forcing tokens to be arbitrary byte strings would force RGW maintain (and pay the cost to maintain) an that arbitrary mapping of tokens to traversals at runtime--to what purpose?

**Pull request merged**
