### PR TITLE
rgw_file: fix misuse of make_key_name before make_fhk

### PR DESCRIPTION
**Pull request by guihecheng**
The make_fhk calls make_key_name internally.

Signed-off-by: Gui Hecheng <guihecheng@cmss.chinamobile.com>

### CODE REVIEW

**Comment by mattbenjamin** [comment]
@guihecheng does this fix an observed problem?

**Comment by guihecheng** [comment]
@mattbenjamin oh, yes, I forgot the versioned decoder, so we shall have this after it is sate to update.

**Comment by guihecheng** [comment]
@mattbenjamin This introduces 'version' for fh_key and assert is conditional, but I didn't touch lookup_fh() as commented for now, could you please explain a bit more ?

**Comment by mattbenjamin** [comment]
@guihecheng iiuc, since this change alters the computed value of fh_key, an old value could have been stored, and we'd need to update it if we detect an old stored version

**Comment by guihecheng** [comment]
@mattbenjamin yes, I agree that, old versioned 'unix-key1' attr should be updated.
So, could we just do an update right inside decode_attrs() ? it should be safe, because we call it always under rgw_fh->mtx.
If we update inside lookup_fh(), then the attr will get updated only upon a second lookup_fh(), because we need the first lookup_fh() to kick decode_attrs() to go.
Or if we do the version check in lookup_fh(),  it would be a bit expensive.

**Comment by guihecheng** [comment]
@mattbenjamin hi, I updated with my solution, it works for me together with this fix:https://github.com/ceph/ceph/pull/15679. please review this when free, thx~

**Comment by mattbenjamin** [comment]
@guihecheng this looks good;  I'll test the key upgrade case and if it works, will merge this

**Comment by mattbenjamin** [comment]
retest this please

**Comment by mattbenjamin** [comment]
retest this please

**Pull request merged**
