### PR TITLE
MDS: Make standby-replay mds avoid initiating subtree export

### PR DESCRIPTION
**Pull request by JianyuLi**
Fixes: http://tracker.ceph.com/issues/21222
Signed-off-by: "Jianyu Li" joannyli@tencent.com

### CODE REVIEW

**Comment by ukernel** [comment]
It's better to track callers of Migrator::export_empty_import. make them not call export_empty_import when mds is not active

**Comment by JianyuLi** [comment]
For the empty subtree case we could add check in trim function to avoid this issue, but it doesn't work for other scenarios as mentioned in http://tracker.ceph.com/issues/21222. So we had better add some defensive code in the underlying export_dir function.

**Comment by ukernel** [comment]
I don't find any other scenarios in http://tracker.ceph.com/issues/21222

**Comment by JianyuLi** [comment]
Maybe in the majority of normal cases, standby-replay mds would only migrate empty subtree triggered by trim, but as a robust system, it should resist any exception and abnormal operation too, e.g. some one export non-empty subtree from this standby mds to another active mds.
So add this defensive code would make system survive in any other scenario we haven't expected.

**Comment by ukernel** [comment]
I don't object to add defensive code.  I mean adding extra patch that avoids call export_dir when mds isn't active

**Comment by JianyuLi** [comment]
:), will add soon as you suggest.

**Comment by JianyuLi** [comment]
@ukernel , pls have a look.

**Comment by ukernel** [comment]
LGTM. but please cleanup the RP (rebase you branch against ceph/master locally, then git push -f)

**Comment by JianyuLi** [comment]
Done!

**Comment by JianyuLi** [comment]
@joscollin , forgot, add now.

**Comment by joscollin** [comment]
@batrick The [merge commit](https://github.com/ceph/ceph/commit/178ca58fec2d820f61724d223addac1c4fa67086) is not having `Reviewed-by`

**Comment by batrick** [comment]
https://github.com/ceph/ceph/commit/490bc0050c54c4e81c28b457af30e3dd62532961

**Pull request merged**
