### PR TITLE
mgr/dashboard: listener addr is always none

### PR DESCRIPTION
**Pull request by nizamial09**
Even if the traddr is passed from the API, it gets overriden by the None hard-coded in the code.

Fixes: https://tracker.ceph.com/issues/64714

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Review by epuertat — APPROVED** [review]
I was going to suggest a small improvement to the `__init__` method: the client works as a singleton class, and once initialized, the connection is stored... and then realized that there's no closing to the channel. Have you checked if this leads to leaking connections, or do Python _garbage-collector_ automatically dispatches those?

Then I tested it and:
```bash
curl -k "https://localhost:11000/api/nvmeof/gateway/info" ...
bash-5.1$ netstat -anp | grep 5500
tcp        0      0 192.168.240.2:32968     192.168.240.6:5500      TIME_WAIT   -                   


bash-5.1$ curl -k "https://localhost:11000/api/nvmeof/gateway/info"...
bash-5.1$ netstat -anp | grep 5500
tcp        0      0 192.168.240.2:51220     192.168.240.6:5500      TIME_WAIT   -                   
tcp        0      0 192.168.240.2:32968     192.168.240.6:5500      TIME_WAIT   -                   


bash-5.1$ curl -k "https://localhost:11000/api/nvmeof/gateway/info"...
bash-5.1$ netstat -anp | grep 5500
tcp        0      0 192.168.240.2:51220     192.168.240.6:5500      TIME_WAIT   -                   
tcp        0      0 192.168.240.2:32968     192.168.240.6:5500      TIME_WAIT   -                   


bash-5.1$ curl -k "https://localhost:11000/api/nvmeof/gateway/info"...
bash-5.1$ netstat -anp | grep 5500
tcp        0      0 192.168.240.2:51220     192.168.240.6:5500      TIME_WAIT   -                   
tcp        0      0 192.168.240.2:32968     192.168.240.6:5500      TIME_WAIT   -                   


bash-5.1$ curl -k "https://localhost:11000/api/nvmeof/gateway/info"...
bash-5.1$ netstat -anp | grep 5500
tcp        0      0 192.168.240.2:51220     192.168.240.6:5500      TIME_WAIT   -                   
tcp        0      0 192.168.240.2:32968     192.168.240.6:5500      TIME_WAIT   -                   


bash-5.1$ curl -k "https://localhost:11000/api/nvmeof/gateway/info"...
bash-5.1$ netstat -anp | grep 5500
tcp        0      0 192.168.240.2:51220     192.168.240.6:5500      TIME_WAIT   -                   
tcp        0      0 192.168.240.2:56752     192.168.240.6:5500      TIME_WAIT   -                   
tcp        0      0 192.168.240.2:32968     192.168.240.6:5500      TIME_WAIT   -                   

bash-5.1$ curl -k "https://localhost:11000/api/nvmeof/gateway/info"...
bash-5.1$ netstat -anp | grep 5500
tcp        0      0 192.168.240.2:51220     192.168.240.6:5500      TIME_WAIT   -                   
tcp        0      0 192.168.240.2:56752     192.168.240.6:5500      TIME_WAIT   -                   
tcp        0      0 192.168.240.2:32968     192.168.240.6:5500      TIME_WAIT   -                   
tcp        0      0 192.168.240.2:56756     192.168.240.6:5500      TIME_WAIT   -                   


bash-5.1$ curl -k "https://localhost:11000/api/nvmeof/gateway/info"...
bash-5.1$ netstat -anp | grep 5500
tcp        0      0 192.168.240.2:51220     192.168.240.6:5500      TIME_WAIT   -                   
tcp        0      0 192.168.240.2:56778     192.168.240.6:5500      TIME_WAIT   -                   
tcp        0      0 192.168.240.2:56752     192.168.240.6:5500      TIME_WAIT   -                   
tcp        0      0 192.168.240.2:32968     192.168.240.6:5500      TIME_WAIT   -                   
tcp        0      0 192.168.240.2:56756     192.168.240.6:5500      TIME_WAIT   -                                  
```

It's not a big issue because after a while all connections are closed:
```bash
netstat -anp | grep 5500
# None
```
However in case of connection spikes it'll open multiple parallel sockets, while gRPC is mainly used because of it's capacity to multiplex connections over the same socket.

**Comment by nizamial09** [comment]
@epuertat you are right. I haven't tested that before. I'll test this out. thanks

**Review by jmolmo — APPROVED** [review]
Tested  (Fedora 39 / python 3.12.2)

**Review by yehudasa — DISMISSED** [review]
@nizamial09 these are two completely separate changes, I think it'd be better to split into two separate PRs. FWIW the unpinning is ok.

**Comment by nizamial09** [comment]
> @nizamial09 these are two completely separate changes, I think it'd be better to split into two separate PRs. FWIW the unpinning is ok.

https://github.com/ceph/ceph/pull/55913

**Comment by nizamial09** [comment]
> the client works as a singleton class, and once initialized, the connection is stored..

i am trying to address this in a different PR https://github.com/ceph/ceph/pull/55951. I saw a concept of channel pooling in grpc which is considered a [best practice from this doc](https://grpc.io/docs/guides/performance/), so thought of trying it out

**Review by avanthakkar — APPROVED** [review]
Thanks for the fix @nizamial09 , LGTM!

**Pull request merged**
