### PR TITLE
[DNM]Wip msg compression

### PR DESCRIPTION
**Pull request by yuyuyu101**
Use AsyncCompressor to implement message compression.

1. Caller need to queue message to compressor as early as possible, so Messenger can send already compressed data directly
2. Now messenger will directly decompress data from network, and dispatch decompressed message to Dispatcher. The best way is we can delay get decompressed data as late as possible, so decompress process can be parallel fully.

### CODE REVIEW

**Comment by yuyuyu101** [comment]
@liewegas @gregsfortytwo Do you think this usage make sense?

This PR lack of users prepare compress message. If ok, recovery logic could prepare data as early as possible in PG layer instead of beginning to compress in messenger.

Then currently received message will be decompressed directly, next we need to encapsulate message's header, payload and data to avoid other components directly get these fields. So we can have a central method to do lazy decompressed data getting.

**Comment by markhpc** [comment]
Hi Haomai, I need to look at code, but I think this will be great. Especially if we could pass data compressed at a lower layer (filesystem or even hardware level) all the way through the stack.  Will try to look in more detail later!

**Comment by dachary** [comment]
@yuyuyu101 this needs rebasing

**Comment by branch-predictor** [comment]
If the (de)compressor will be fast enough, it'll help on bandwidth-restricted networks. I haven't looked at the code, but I already suggest adding possibility to disable compression on specified networks/interfaces.

**Comment by liewegas** [comment]
Does it make sense to do teh compress/decompress async?  Why not do it inline with the sending or receiving worker?

**Comment by branch-predictor** [comment]
Ideally, all parts would be (de)compressed in parallel and/or only when needed.

**Comment by branch-predictor** [comment]
On Fri, Apr 22, 2016 at 01:03:23PM -0700, Haomai Wang wrote:
> Closed #5439.

Abandoned completely or you have another idea on your mind?

-- 
Piotr Dałek
branch@predictor.org.pl
http://blog.predictor.org.pl

**Comment by yuyuyu101** [comment]
@branch-predictor I will rework it later.

**Pull request closed without merging**
