### PR TITLE
qa: convert fs:workload to use cephadm

### PR DESCRIPTION
**Pull request by batrick**

### CODE REVIEW

**Comment by batrick** [comment]
jenkins test make check

**Comment by batrick** [comment]
https://pulpito.ceph.com/pdonnell-2021-06-24_04:28:25-fs:workload-master-distro-basic-smithi/

**Comment by batrick** [comment]
https://pulpito.ceph.com/pdonnell-2021-06-24_13:24:27-fs:workload-master-distro-basic-smithi/

**Comment by batrick** [comment]
fs:workload is about 53% of the jobs in fs suite.

**Comment by batrick** [comment]
(fixed tox failure)

**Review by liewegas — APPROVED** [review]
Looks good!

You might consider also a different set of tests that do this via 'fs volume create' and put cephadm in ``roleless: true`` mode, just to ensure there is good coverage of the path most users will take.

**Comment by batrick** [comment]
> You might consider also a different set of tests that do this via 'fs volume create' and put cephadm in roleless: true mode, just to ensure there is good coverage of the path most users will take.

I'm wary of doing this because some configurations in the matrix add overrides to how cephfs is created and these would not be applied with the `fs volume create` provisioning. I think the `fs:volumes` (and `fs:cephadm`) sub-suite is testing this sufficiently.

**Comment by batrick** [comment]
> https://pulpito.ceph.com/pdonnell-2021-06-24_13:24:27-fs:workload-master-distro-basic-smithi/

I broke this run during a rebase of this branch. I'll rerun soon.

**Review by liewegas — APPROVED** [review]

**Comment by batrick** [comment]
https://pulpito.ceph.com/pdonnell-2021-06-24_17:33:20-fs:workload-wip-pdonnell-testing-20210624.153153-distro-basic-smithi/

**Comment by batrick** [comment]
Several missing package failures. Not sure why this is a problem for cephadm because we're still using the install task. Will check on this more later.

**Comment by batrick** [comment]
Latest tests: https://pulpito.ceph.com/pdonnell-2021-07-12_18:17:18-fs:workload-wip-pdonnell-testing-20210710.030422-distro-basic-smithi/

New failure: https://pulpito.ceph.com/pdonnell-2021-07-12_18:17:18-fs:workload-wip-pdonnell-testing-20210710.030422-distro-basic-smithi/6266629/

@sebastian-philipp says it's an instance of https://tracker.ceph.com/issues/49287

Further testing/merge is blocked until it is resolved.

**Comment by batrick** [comment]
https://pulpito.ceph.com/pdonnell-2021-07-23_15:30:01-fs:workload-master-distro-basic-smithi/

Still several cephadm related failures blocking merge.

**Comment by sebastian-philipp** [comment]
https://pulpito.ceph.com/pdonnell-2021-08-24_17:29:03-fs:workload-wip-pdonnell-testing-20210824.150835-distro-basic-smithi/6356265

```
bash[26804]: Error: OCI runtime error: container_linux.go:370: starting container process caused: unknown capability "CAP_BPF"
systemd[1]: ceph-783410ce-0504-11ec-8c25-001a4aab830c@mon.a.service: Control process exited, code=exited status=126
systemd[1]: ceph-783410ce-0504-11ec-8c25-001a4aab830c@mon.a.service: Failed with result 'exit-code'.
systemd[1]: Failed to start Ceph mon.a for 783410ce-0504-11ec-8c25-001a4aab830c.
```

**Comment by sebastian-philipp** [comment]
#43021

**Comment by sebastian-philipp** [comment]
> #43021

`distros/podman/rhel_8.4_container_tools_rhel8` should work for you

**Comment by batrick** [comment]
https://pulpito.ceph.com/pdonnell-2021-09-03_18:17:02-fs:workload-wip-pdonnell-testing-20210903.161618-distro-basic-smithi/

**Comment by batrick** [comment]
@sebastian-philipp any idea ^?

**Comment by sebastian-philipp** [comment]
> @sebastian-philipp any idea ^?

Let's take a breath for a moment and think about what we're doing here. Till recently, we had a dashbaord frontend job in the cephadm suite. Turned out this didn't worked at all and we had to ask the dashboard folks constantly for all testing failures. I actually want to keep the cephfs team to be able to have good base for testing cephfs. 

What do you think of having a super small subset of this test here in the orch/cephadm suite? Maybe two jobs or so and then let the cephadm team keep this subset stable?

**Comment by batrick** [comment]
> What do you think of having a super small subset of this test here in the orch/cephadm suite? Maybe two jobs or so and then let the cephadm team keep this subset stable?

It's okay with me.I'll try to get around to it when I have some time.

**Comment by batrick** [comment]
I believe this is good to merge.

cc @jtlayton @vshankar @gregsfortytwo

**Comment by batrick** [comment]
(small rebase)

**Comment by vshankar** [comment]
jenkins test make check

**Comment by batrick** [comment]
(small rebase)

**Comment by vshankar** [comment]
jenkins retest this please

**Comment by batrick** [comment]
jenkins test dashboard cephadm

**Review by vshankar — APPROVED** [review]
LGTM

**Pull request merged**
