### PR TITLE
test/encoding/readable: use [ for "test" not ((

### PR DESCRIPTION
**Pull request by tchaikov**
this also fixes following error in the ubuntu gitbuilder

error: Added files:
+ cat .git/added-files
src/0

where sh points to dash.

Signed-off-by: Kefu Chai <kchai@redhat.com>

### CODE REVIEW

**Comment by tchaikov** [comment]
@ErwanAliasr1 could you take a look?

**Comment by ErwanAliasr1** [comment]
I'm ok with the syntax but aren't we expecting to test $? instead of $# ?

**Comment by tchaikov** [comment]
iiuc, we are testing the number of pids to wait for, but not the return code of last command.

**Comment by ErwanAliasr1** [comment]
Oh ok, didn't read it like that.
+1 for me then.

**Comment by tchaikov** [comment]
build and test passed at http://gitbuilder.sepia.ceph.com/gitbuilder-ceph-tarball-trusty-amd64-basic/log.cgi?log=fc81bec888eba3be488c34508d4ae3521372b175

**Pull request merged**
