### PR TITLE
Balancer fixes without all of the calc_pg_upmaps() rewrites

### PR DESCRIPTION
**Pull request by dzafman**
## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by tchaikov** [comment]
- http://pulpito.ceph.com/kchai-2019-11-30_02:34:26-rados-wip-kefu-testing-2019-11-29-2231-distro-basic-mira/
- http://pulpito.ceph.com/kchai-2019-12-02_01:50:54-rados-wip-kefu-testing-2019-11-29-2231-distro-basic-mira/

failures tracked by:

- https://tracker.ceph.com/issues/42764
- https://tracker.ceph.com/issues/43075
- https://tracker.ceph.com/issues/43077
- https://tracker.ceph.com/issues/43078

**Comment by tchaikov** [comment]
@dzafman @jdurgin shall we backport some of these commits to nautilus (and mimic)?

**Comment by wjwithagen** [comment]
@tchaikov @dzafman @jdurgin
build on FreeBSD/Clang/stdlic++ complains.

from:
[https://en.cppreference.com/w/cpp/algorithm/random_shuffle](https://en.cppreference.com/w/cpp/algorithm/random_shuffle)
template< class RandomIt > void random_shuffle( RandomIt first, RandomIt last ); | (1) | (deprecated in C++14) (removed in C++17)


```
/home/jenkins/workspace/ceph-master/src/tools/osdmaptool.cc:437:5: error: use of undeclared identifier 'random_shuffle'
    random_shuffle (rules.begin(), rules.end());
    ^
1 error generated.
gmake[2]: *** [src/tools/CMakeFiles/osdmaptool.dir/build.make:63: src/tools/CMakeFiles/osdmaptool.dir/osdmaptool.cc.o] Error 1
gmake[2]: Leaving directory '/home/jenkins/workspace/ceph-master/build'
gmake[1]: *** [CMakeFiles/Makefile2:5960: src/tools/CMakeFiles/osdmaptool.dir/all] Error 2
```

**Comment by wjwithagen** [comment]
@tchaikov @dzafman @jdurgin
Fix for this is in: https://github.com/ceph/ceph/pull/31935

**Comment by dzafman** [comment]
@tchaikov @jdurgin I wasn't expecting this to be merged yet.

**Comment by tchaikov** [comment]
@dzafman sorry for jumping the gun! anything missing or anything i can do to fix anything?

**Pull request merged**
