### PR TITLE
ceph-disk: use /sys/dev/block/maj:min/partition to see if partition

### PR DESCRIPTION
**Pull request by trociny**
Fixes: #12706
Signed-off-by: Mykola Golub <mgolub@mirantis.com>

This is the pull request #5591 reopened against infernalis.

### CODE REVIEW

**Comment by dachary** [comment]
@trociny to save you time : there is no need to run the ceph-disk suite just yet as it will fail because of http://tracker.ceph.com/issues/12877. Once this issue is fixed, you'll be able to run https://github.com/ceph/ceph-qa-suite/tree/master/suites/ceph-disk to verify this pull request works.

**Comment by dachary** [comment]
@trociny http://tracker.ceph.com/issues/12877 is fixed, you can go ahead and test :-)

**Comment by trociny** [comment]
@dachary could you please help to interpret the teuthology test results:

http://pulpito.ceph.com/trociny-2015-09-03_23:49:42-ceph-disk-wip-12706-infernalis-trociny---basic-vps/

Particularly this failure:

http://qa-proxy.ceph.com/teuthology/trociny-2015-09-03_23:49:42-ceph-disk-wip-12706-infernalis-trociny---basic-vps/1043819/teuthology.log

Do you think it is due to my change? Output of 'ceph-disk list --format json' looks a little strange to me, though this might be because I am not familiar with multipath.

**Comment by dachary** [comment]
@trociny the Ubuntu 14.04 test is proof enough that your test does not introduce a regression.

**Pull request merged**
