### PR TITLE
rbd-nbd: fix typo in comment

### PR DESCRIPTION
**Pull request by liupan1111**

### CODE REVIEW

**Comment by liupan1111** [comment]
@trociny minor change. thanks.

**Comment by trociny** [comment]
@liupan1111 I am not sure we do intentionally changes like your first commit. We have tabs/space mix through all the code, and personally I in favour to use only one style, and prefer spaces. The funny thing is though that the file header:
```
// -*- mode:C++; tab-width:8; c-basic-offset:2; indent-tabs-mode:t -*-
```
tells that tabs should be used. And frequently I am a source of these tabs because my emacs uses this settings instead of my preferences.

Jason usually changes tabs to spaces, but only for lines where he updates the code.

If changing this just to fix the style, at the first we should officially agree that tabs is wrong (and fix the headers then). Note, changes like these add additional difficulties when e.g. researching a regression.

@dillaman what do you think?

**Comment by liupan1111** [comment]
@trociny @dillaman The current coding style of existing code makes me confused... sometimes, some code only use spaces, but some others, space and tab mix ...

But for my first commit, the issue is: no matter tab or spacing, the code should be kept in alignment, but it was not.

**Comment by dillaman** [comment]
Sadly -- the Ceph coding standard permits the mixture of tabs and spaces [1], so we aren't going to change that here. I agree w/ @trociny that the first commit is not helpful.

[1] https://github.com/ceph/ceph/blob/master/CodingStyle#L75

**Comment by liupan1111** [comment]
ok, i just removed the first commit.

**Pull request merged**
