### PR TITLE
hammer: tools: add a tool to rebuild mon store from OSD

### PR DESCRIPTION
**Pull request by tchaikov**
http://tracker.ceph.com/issues/17291
http://tracker.ceph.com/issues/17602

### CODE REVIEW

**Comment by tchaikov** [comment]
will update the x-refs of commits yet merged in master.

**Comment by tchaikov** [comment]
changelog

- fix the xrefs so they point to the corresponding commits in master

**Comment by smithfarm** [comment]
@tchaikov In all likelihood, 0.94.10 will be the last hammer release. If we include this new tool, and it has bugs, there won't be another release in which to fix those (admittedly hypothetical) bugs. If that's OK with you, then I'm in favor of inclusion since I'm sure the new tool is useful.

**Comment by tchaikov** [comment]
@smithfarm, this tool has been tested on jewel and master, so it should work well. i am okay to include it in this hammer release.

**Comment by smithfarm** [comment]
@tchaikov Can we ignore the new warning "This branch is out-of-date with the base branch" ?

**Comment by smithfarm** [comment]
@tchaikov Thanks, updated tracker and PR description.

**Comment by smithfarm** [comment]
@tchaikov This backport passed a rados suite at http://tracker.ceph.com/issues/17151#note-7 with failures that I believe have been addressed (except for http://tracker.ceph.com/issues/15139 which is caused by the build system no longer providing dumpling-era packages).

I have rebuilt the integration branch to include the two fixes and scheduled a new run at http://tracker.ceph.com/issues/17151#note-14

Do you think it's OK to merge provided the second run succeeds?

**Comment by smithfarm** [comment]
@tchaikov Also, could you provide the text of a hammer 0.94.10 release notes entry describing this new tool?

**Comment by smithfarm** [comment]
Second run succeeded; third run here: http://pulpito.front.sepia.ceph.com/smithfarm-2016-11-21_11:52:41-rados-hammer-backports---basic-smithi/

**Comment by tchaikov** [comment]
> Also, could you provide the text of a hammer 0.94.10 release notes entry describing this new tool?

@smithfarm sure thing! will do it tmr.

**Comment by tchaikov** [comment]
@smithfarm done, and rebased against master.

**Pull request merged**
