### PR TITLE
luminous: qa: fsstress workunit does not execute in parallel on same host without clobbering files

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/36152
http://tracker.ceph.com/issues/36322
http://tracker.ceph.com/issues/36277

### CODE REVIEW

**Comment by smithfarm** [comment]
@batrick de824f74dd8ac909e47335ccd53d7a085e388e41 depends on 91942df5a690809ed872f5aa8c35b56e8048e485 for the `cleanup` code in `qa/tasks/workunit.py` so the easiest way to cherry-pick it is as above. But I don't know if the snap format upgrade test is something we want to have in luminous?

**Comment by batrick** [comment]
No, we do not want the snap upgrade test in luminous. Feel free to just cherry-pick the workunit changes.

**Comment by yuriw** [comment]
[wip-yuri4-testing-2018-10-03-2104-luminous](https://trello.com/c/mCnQ3lN2/434-wip-yuri4-testing-2018-10-03-2104-luminous)

**Comment by batrick** [comment]
Needs followup fixes: http://tracker.ceph.com/issues/36165 http://tracker.ceph.com/issues/36184

Combine into one PR please.

**Comment by smithfarm** [comment]
@batrick Brought in the follow-up fixes. Ready for review?

**Comment by yuriw** [comment]
[wip-yuri4-testing-2018-10-05-2015-luminous](https://trello.com/c/IsbxOeA6/438-wip-yuri4-testing-2018-10-05-2015-luminous)

**Comment by batrick** [comment]
LGTM

**Pull request merged**
