### PR TITLE
luminous: mon, osd: fix potential collided *Up Set* after PG remapping

### PR DESCRIPTION
**Pull request by xiexingguo**
http://tracker.ceph.com/issues/23118

### CODE REVIEW

**Comment by theanalyst** [comment]
@xiexingguo can you add the ticket number and original PR this backport is from

**Comment by xiexingguo** [comment]
@theanalyst The first commit includes the original ticket number..

**Comment by yuriw** [comment]
[wip-yuri2-testing-2018-04-06-1946-luminous](https://trello.com/c/jnS4VFcV/287-wip-yuri2-testing-2018-04-06-1946-luminous)

**Comment by liewegas** [comment]
does not look good:
<pre>
2018-04-06T23:06:35.044 INFO:tasks.ceph.mgr.x.smithi118.stderr:*** Caught signal (Segmentation fault) **
2018-04-06T23:06:35.044 INFO:tasks.ceph.mgr.x.smithi118.stderr: in thread 7f84692bd700 thread_name:balancer
2018-04-06T23:06:35.045 INFO:tasks.ceph.mgr.x.smithi118.stderr: ceph version 12.2.4-372-g3ec4869 (3ec4869d8a1d6ef06aa5698b52347ce41aa0d068) luminous (stable)
2018-04-06T23:06:35.045 INFO:tasks.ceph.mgr.x.smithi118.stderr: 1: (()+0x40c194) [0x557093897194]
2018-04-06T23:06:35.045 INFO:tasks.ceph.mgr.x.smithi118.stderr: 2: (()+0x11390) [0x7f8478180390]
2018-04-06T23:06:35.045 INFO:tasks.ceph.mgr.x.smithi118.stderr: 3: (OSDMap::_apply_upmap(pg_pool_t const&, pg_t, std::vector<int, std::allocator<int> >*) const+0x1af) [0x5570939c551f]
2018-04-06T23:06:35.045 INFO:tasks.ceph.mgr.x.smithi118.stderr: 4: (OSDMap::_pg_to_up_acting_osds(pg_t const&, std::vector<int, std::allocator<int> >*, int*, std::vector<int, std::allocator<int> >*, int*, bool) const+0x257) [0x5570939c9f97]
2018-04-06T23:06:35.045 INFO:tasks.ceph.mgr.x.smithi118.stderr: 5: (OSDMap::calc_pg_upmaps(CephContext*, float, int, std::set<long, std::less<long>, std::allocator<long> > const&, OSDMap::Incremental*)+0x367) [0x5570939db527]
2018-04-06T23:06:35.045 INFO:tasks.ceph.mgr.x.smithi118.stderr: 6: (()+0x2efef8) [0x55709377aef8]
2018-04-06T23:06:35.045 INFO:tasks.ceph.mgr.x.smithi118.stderr: 7: (PyEval_EvalFrameEx()+0x8a51) [0x7f847925c971]
2018-04-06T23:06:35.046 INFO:tasks.ceph.mgr.x.smithi118.stderr: 8: (PyEval_EvalCodeEx()+0x85c) [0x7f847939205c]
2018-04-06T23:06:35.046 INFO:tasks.ceph.mgr.x.smithi118.stderr: 9: (PyEval_EvalFrameEx()+0x6ffd) [0x7f847925af1d]
2018-04-06T23:06:35.046 INFO:tasks.ceph.mgr.x.smithi118.stderr: 10: (PyEval_EvalFrameEx()+0x7124) [0x7f847925b044]
2018-04-06T23:06:35.046 INFO:tasks.ceph.mgr.x.smithi118.stderr: 11: (PyEval_EvalFrameEx()+0x7124) [0x7f847925b044]
2018-04-06T23:06:35.046 INFO:tasks.ceph.mgr.x.smithi118.stderr: 12: (PyEval_EvalCodeEx()+0x85c) [0x7f847939205c]
2018-04-06T23:06:35.046 INFO:tasks.ceph.mgr.x.smithi118.stderr: 13: (()+0x13e370) [0x7f84792e8370]
2018-04-06T23:06:35.046 INFO:tasks.ceph.mgr.x.smithi118.stderr: 14: (PyObject_Call()+0x43) [0x7f84792bb273]
2018-04-06T23:06:35.046 INFO:tasks.ceph.mgr.x.smithi118.stderr: 15: (()+0x1853ac) [0x7f847932f3ac]
2018-04-06T23:06:35.046 INFO:tasks.ceph.mgr.x.smithi118.stderr: 16: (PyObject_Call()+0x43) [0x7f84792bb273]
2018-04-06T23:06:35.046 INFO:tasks.ceph.mgr.x.smithi118.stderr: 17: (PyObject_CallMethod()+0xf4) [0x7f84792bc444]
2018-04-06T23:06:35.047 INFO:tasks.ceph.mgr.x.smithi118.stderr: 18: (PyModuleRunner::serve()+0x5c) [0x5570937780dc]
2018-04-06T23:06:35.047 INFO:tasks.ceph.mgr.x.smithi118.stderr: 19: (PyModuleRunner::PyModuleRunnerThread::entry()+0x1b8) [0x5570937788e8]
2018-04-06T23:06:35.047 INFO:tasks.ceph.mgr.x.smithi118.stderr: 20: (()+0x76ba) [0x7f84781766ba]
2018-04-06T23:06:35.047 INFO:tasks.ceph.mgr.x.smithi118.stderr: 21: (clone()+0x6d) [0x7f84771e241d]
2018-04-06T23:06:35.047 INFO:tasks.ceph.mgr.x.smithi118.stderr:2018-04-06 23:06:35.044306 7f84692bd700 -1 *** Caught signal (Segmentation fault) **
</pre>
@xiexingguo do you mind looking?
/a/yuriw-2018-04-06_21:35:03-rados-wip-yuri2-testing-2018-04-06-1946-luminous-distro-basic-smithi/2365151

**Comment by xiexingguo** [comment]
> @xiexingguo do you mind looking?

Sure, I'm on it.

**Comment by xiexingguo** [comment]
@liewegas The above test failure is not related to this change.  
See https://github.com/ceph/ceph/pull/21325

**Comment by yuriw** [comment]
[wip-yuri5-testing-2018-04-10-1643-luminous](https://trello.com/c/8zZrm1sU/292-wip-yuri5-testing-2018-04-10-1643-luminous)

**Pull request merged**
