### PR TITLE
CLS numops

### PR DESCRIPTION
**Pull request by joaquimrocha**
Hey,

This is a new and simple CLS useful for those who keep numeric values in the objects' omap and need to perform operations on them.
As an example of why this may be useful, say you have many users creating/deleting files in one go and you want to keep a count of the files in an omap entry without having to lock its object, then you can just call an *add* operation with the number of files a user is creating and it will add to whatever the omap entry's value is at that point. Currently and for simplicity, it's only performing the ops as double values but I can provide other types/ops later.

The operations provided are addition, subtraction, multiplication and division.

Hopefully you'll find this class useful enough to include it upstream.

### CODE REVIEW

**Comment by yuyuyu101** [comment]
Hmm, I think we like to add a feature or interface which should be actually useful for someone or certainly use cases. Otherwise, we may lose the control when time flowed.

**Comment by joaquimrocha** [comment]
Hi @yuyuyu101 , could you clarify what you mean? Are you saying that the feature is not useful for many users or that's not complete enough to be useful? If so, why and how would you change it?

I am implementing a quota-like system for a project that uses librados and this is extremely important as there's no faster way to quickly add/sub a number from an object. I bet there are more use-cases beyond this one where such ops are needed.

Cheers,

**Comment by jecluis** [comment]
Assigned @noahdesu. I imagine he would know who, if not himself, would be better to tackle this pull request.

**Comment by noahdesu** [comment]
Hi @joaquimrocha thanks for the PR. I really like the functionality that this object class introduces, and it's easy to see its utility in a number of use cases. I'd like to take this opportunity to discuss how object classes are handled, because I think this is a great example of the type of PR that the Ceph community will continue to see as more people become aware of and comfortable with the use of objects for metadata management.

To help tackle the common case of objects being used for metadata management, it seems that a flexible solution may easily be achievable in the form of something such as an SQLite object class. Such a `cls_sqlite` feature would subsume `cls_numops`, and generally allow the vast majority of metadata use cases to be solved on the application side with a single new upstream object class.

More generally though, there is likely always going to be a need for applications to define custom object classes, so how should the community handle object class upstream requests? In a perfect world completely general and reusable object classes would exist, but part of the beauty of object classes is their ability to be custom tailored for each application. Judging generality seems like it is going to be very hard, and so my opinion is that there needs to be a mechanism in place to handle community submitted object classes.

As it currently stands, by far the most convenient location for object classes is in the Ceph tree because 1) the object class interface is not exported, 2) bufferlist serialization is not exported, and 3) the existing build and packaging system automatically handles object class libraries bits.

So there seems to be a few options:

1. Accept every object class PR upstream in the Ceph tree similar to all the drivers in the kernel with a smart build system.
2. Construct a community Git tree that holds submitted object classes and use the Ceph packaging system to build deb/rpm
3. Provide some sort of object class SDK that simplifies object class development external to the Ceph tree.

Personally I think 1 and 3 make the most sense.

@liewegas 
@dachary 
@gregsfortytwo 
@yehudasa

**Comment by joaquimrocha** [comment]
Hi @noahdesu , thank you for your review and comments.
I see what you mean. As much as I think my cls_numops might make for a common use-case (I think of it as an extension to the numeric comparison of omap/xattrs operation) and as much as I'd like it to be added upstream, I don't think your suggested approach 1 is the best for Ceph as it could escalate to something that is not useful for many people (and more code to maintain).

The repo in approach number 2 could be used as a stage for things that can later be included in upstream Ceph. I still disagree with putting everything as it makes it difficult to see what can be considered of general interest or not.

Approach 3 may be the best option so we don't have to build object classes in Ceph's tree but I wonder, when we might have that available, which means that before that happens, I'll have to build the cls_numops inside Ceph and give the .so to be included in our production (but yeah, that's my problem).

Let's see what the other Ceph experts say.

**Comment by noahdesu** [comment]
Just to clarify, at this point there doesn't seem to be a lot of class object upstream requests. So in that regard, I think that merging this PR is a good idea. Changing things later is always possible if and when its needed. :)

**Comment by joaquimrocha** [comment]
@noahdesu , that'd be great!
By the way, my idea is that once this is merged I keep improving it or make it more general for other use-cases.

Cheers,

**Comment by gregsfortytwo** [comment]
Sorry for the delay in commenting on this. I haven't looked at the code much, but:
*) I think it's okay for us to accept all object class PRs which meet our coding and maintainability standards, at least until we start seeing many more object classes or ones which are much more complicated than this.
*) I think a simple class for doing arithmetic on a value is a useful tool to have in the box, in addition to a fairly readable example object class that wasn't written by the original upstream. ;)

I'm not sure if any of the other comments (@noahdesu?) were a Reviewed-by from anybody, but if they were I think this should get merged!
(This comment should not be taken as a Reviewed-by: statement; sorry.)

**Comment by noahdesu** [comment]
@gregsfortytwo i was pro merging in the abstract. i'll add an actual reviewed-by soon.

**Comment by joaquimrocha** [comment]
Hi @noahdesu , any update on this? It'd be great to get this merged.

**Comment by noahdesu** [comment]
@joaquimrocha sorry for the delay on this. I'll get the review done this week.

**Comment by joaquimrocha** [comment]
Hi @noahdesu , sorry for insisting on this but it'd be nice to know if it will be merged soon. Cheers.

**Comment by liewegas** [comment]
@joaquimrocha Canyou add a script in qa/workunits/cls/ that runs the functional test so that our qa runs will cover it?  (we run all scripts in that directory)

Also, can you rebase to resolve the merge conflict?

**Comment by joaquimrocha** [comment]
@liewegas . Will do! Stay tuned.

**Comment by joaquimrocha** [comment]
Hi @liewegas , finally I found the time to rebase and add the requested script. Hope everything looks fine now.

**Comment by joaquimrocha** [comment]
Any news regarding this? @liewegas , @noahdesu ? Cheers.

**Comment by liewegas** [comment]
@joaquimrocha sorry i missed this.. i'll test it in my next batch.

**Comment by joaquimrocha** [comment]
Thanks @liewegas et al!

**Pull request merged**
