### PR TITLE
mimic: Limit pg log length during recovery/backfill so that we don't run out of memory

### PR DESCRIPTION
**Pull request by neha-ojha**
Fixes: https://tracker.ceph.com/issues/24989
https://tracker.ceph.com/issues/25200
https://tracker.ceph.com/issues/25220
https://tracker.ceph.com/issues/26909
https://tracker.ceph.com/issues/35073

Signed-off-by: Neha Ojha nojha@redhat.com

### CODE REVIEW

**Comment by neha-ojha** [comment]
updated to incorporate https://tracker.ceph.com/issues/26868.
TODO: add backport tracker ticket reference

**Comment by yuriw** [comment]
[wip-yuri2-testing-2018-08-16-1638-mimic](https://trello.com/c/RNnCSi1B/375-wip-yuri2-testing-2018-08-16-1638-mimic)

**Comment by yuriw** [comment]
@jdurgin it passed tests, pls merge

**Comment by smithfarm** [comment]
@neha-ojha Does this still need to be DNM?

**Comment by neha-ojha** [comment]
@smithfarm https://github.com/ceph/ceph/pull/23211#issuecomment-412194617 applies to this PR as well. 
https://github.com/ceph/ceph/pull/23633 is the potential fix, which needs to be backported to this and the luminous version of this PR. Hence, the DNM.

**Comment by smithfarm** [comment]
@neha-ojha Thanks for the clarification!

@yuriw This will need to be re-tested after commits are added. It stays DNM until that happens.

**Comment by yuriw** [comment]
@neha-ojha PR # ?

**Comment by neha-ojha** [comment]
https://github.com/ceph/ceph/pull/23633

**Comment by neha-ojha** [comment]
@yuriw  This is ready for retesting with the rados and multimds suite.

**Comment by yuriw** [comment]
[wip-yuri3-testing-2018-09-02-2228-mimic](https://trello.com/c/JIu8MzD5/386-wip-yuri3-testing-2018-09-02-2228-mimic)

**Comment by smithfarm** [comment]
@neha-ojha Does this need https://github.com/ceph/ceph/pull/23894 as well? (not yet merged into master)

**Comment by smithfarm** [comment]
Larger question is - can this wait until 13.2.3 ?

**Comment by jdurgin** [comment]
@yuriw let's get https://github.com/ceph/ceph/pull/23894 into mimic too - it's just removing a line of debugging so I'm not worried about the master merge

**Comment by smithfarm** [comment]
> let's get #23894 into mimic too

@jdurgin @yuriw See https://github.com/ceph/ceph/pull/23951

**Pull request merged**
