### PR TITLE
mgr/orchestrator: get_hosts return `HostSpec` instead of `InventoryDevice`

### PR DESCRIPTION
**Pull request by sebastian-philipp**
This fixes a bad symmetry problem:

previsously:
```python
def add_host(host: HostSpec): ...
def get_hosts() -> List[InventoryDevice]: ...
```

now:
```python
def add_host(host: HostSpec): ...
def get_hosts() -> List[HostSpec]: ...
```

Signed-off-by: Sebastian Wagner <sebastian.wagner@suse.com>

This is a step for implementing https://tracker.ceph.com/issues/43839 .

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by sebastian-philipp** [comment]
jenkins test dashboard backend

**Comment by callithea** [comment]
jenkins test dashboard backend

**Comment by sebastian-philipp** [comment]
frontend failed with

```
Jasmine started

  Images page

    breadcrumb and tab tests
      ✓ should open and show breadcrumb (0.104 sec)
      ✓ should show four tabs (0.036 sec)
      ✓ should show text for all tabs (0.176 sec)

(node:19371) UnhandledPromiseRejectionWarning: NoSuchElementError: No element found using locator: by.cssContainingText(".select-menu-item-content", "rbd")
    at elementArrayFinder.getWebElements.then (/home/jenkins-build/build/workspace/ceph-dashboard-pull-requests/src/pybind/mgr/dashboard/frontend/node_modules/protractor/built/element.js:814:27)
    at process._tickCallback (internal/process/next_tick.js:68:7)Error: 
    at ElementArrayFinder.applyAction_ (/home/jenkins-build/build/workspace/ceph-dashboard-pull-requests/src/pybind/mgr/dashboard/frontend/node_modules/protractor/built/element.js:459:27)
    at ElementArrayFinder.(anonymous function).args [as click] (/home/jenkins-build/build/workspace/ceph-dashboard-pull-requests/src/pybind/mgr/dashboard/frontend/node_modules/protractor/built/element.js:91:29)
    at ElementFinder.(anonymous function).args [as click] (/home/jenkins-build/build/workspace/ceph-dashboard-pull-requests/src/pybind/mgr/dashboard/frontend/node_modules/protractor/built/element.js:831:22)
    at PoolPageHelper.<anonymous> (/home/jenkins-build/build/workspace/ceph-dashboard-pull-requests/src/pybind/mgr/dashboard/frontend/e2e/pools/pools.po.ts:83:92)
    at step (/home/jenkins-build/build/workspace/ceph-dashboard-pull-requests/src/pybind/mgr/dashboard/frontend/node_modules/tslib/tslib.js:136:27)
    at Object.next (/home/jenkins-build/build/workspace/ceph-dashboard-pull-requests/src/pybind/mgr/dashboard/frontend/node_modules/tslib/tslib.js:117:57)
    at /home/jenkins-build/build/workspace/ceph-dashboard-pull-requests/src/pybind/mgr/dashboard/frontend/node_modules/tslib/tslib.js:110:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/home/jenkins-build/build/workspace/ceph-dashboard-pull-requests/src/pybind/mgr/dashboard/frontend/node_modules/tslib/tslib.js:106:16)
    at /home/jenkins-build/build/workspace/ceph-dashboard-pull-requests/src/pybind/mgr/dashboard/frontend/e2e/pools/pools.po.ts:83:17
(node:19371) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:19371) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

 log: [ Entry {
    level: Level { name_: 'SEVERE', value_: 1000 },
    message:
     'https://bionic-huge--0b02bc07-01c1-4d53-a09a-11ef80958176:41538/polyfills.js 180:24 Uncaught Error: Control \'filter\' could not be found!',
    timestamp: 1581594536658,
    type: '' } ]
    create, edit & delete image test
      ✗ should create image (0.859 sec)
        - Failed: No element found using locator: by.cssContainingText("select[name=pool] option", "e2e_images_pool")
            at elementArrayFinder.getWebElements.then (/home/jenkins-build/build/workspace/ceph-dashboard-pull-requests/src/pybind/mgr/dashboard/frontend/node_modules/protractor/built/element.js:814:27)
            at process._tickCallback (internal/process/next_tick.js:68:7)Error: 
            at ElementArrayFinder.applyAction_ (/home/jenkins-build/build/workspace/ceph-dashboard-pull-requests/src/pybind/mgr/dashboard/frontend/node_modules/protractor/built/element.js:459:27)
            at ElementArrayFinder.(anonymous function).args [as click] (/home/jenkins-build/build/workspace/ceph-dashboard-pull-requests/src/pybind/mgr/dashboard/frontend/node_modules/protractor/built/element.js:91:29)
            at ElementFinder.(anonymous function).args [as click] (/home/jenkins-build/build/workspace/ceph-dashboard-pull-requests/src/pybind/mgr/dashboard/frontend/node_modules/protractor/built/element.js:831:22)
            at ImagesPageHelper.<anonymous> (/home/jenkins-build/build/workspace/ceph-dashboard-pull-requests/src/pybind/mgr/dashboard/frontend/e2e/page-helper.po.ts:159:89)
            at step (/home/jenkins-build/build/workspace/ceph-dashboard-pull-requests/src/pybind/mgr/dashboard/frontend/node_modules/tslib/tslib.js:136:27)
            at Object.next (/home/jenkins-build/build/workspace/ceph-dashboard-pull-requests/src/pybind/mgr/dashboard/frontend/node_modules/tslib/tslib.js:117:57)
            at /home/jenkins-build/build/workspace/ceph-dashboard-pull-requests/src/pybind/mgr/dashboard/frontend/node_modules/tslib/tslib.js:110:75
            at new Promise (<anonymous>)
            at Object.__awaiter (/home/jenkins-build/build/workspace/ceph-dashboard-pull-requests/src/pybind/mgr/dashboard/frontend/node_modules/tslib/tslib.js:106:16)
            at ImagesPageHelper.PageHelper.selectOption (/home/jenkins-build/build/workspace/ceph-dashboard-pull-requests/src/pybind/mgr/dashboard/frontend/e2e/page-helper.po.ts:216:24)
        From asynchronous test: 
        Error: 
            at Suite.<anonymous> (/home/jenkins-build/build/workspace/ceph-dashboard-pull-requests/src/pybind/mgr/dashboard/frontend/e2e/block/images.e2e-spec.ts:51:5)
            at apply (/home/jenkins-build/build/workspace/ceph-dashboard-pull-requests/src/pybind/mgr/dashboard/frontend/node_modules/jasmine-fail-fast/node_modules/lodash/lodash.js:476:27)
            at Env.wrapper [as describe] (/home/jenkins-build/build/workspace/ceph-dashboard-pull-requests/src/pybind/mgr/dashboard/frontend/node_modules/jasmine-fail-fast/node_modules/lodash/lodash.js:5317:16)
            at Suite.<anonymous> (/home/jenkins-build/build/workspace/ceph-dashboard-pull-requests/src/pybind/mgr/dashboard/frontend/e2e/block/images.e2e-spec.ts:38:3)
        - Expected 1 to equal 0.
            at Function.<anonymous> (/home/jenkins-build/build/workspace/ceph-dashboard-pull-requests/src/pybind/mgr/dashboard/frontend/e2e/page-helper.po.ts:40:37)
            at step (/home/jenkins-build/build/workspace/ceph-dashboard-pull-requests/src/pybind/mgr/dashboard/frontend/node_modules/tslib/tslib.js:136:27)
            at Object.next (/home/jenkins-build/build/workspace/ceph-dashboard-pull-requests/src/pybind/mgr/dashboard/frontend/node_modules/tslib/tslib.js:117:57)
            at fulfilled (/home/jenkins-build/build/workspace/ceph-dashboard-pull-requests/src/pybind/mgr/dashboard/frontend/node_modules/tslib/tslib.js:107:62)
            at process._tickCallback (internal/process/next_tick.js:68:7)

**************************************************
*                    Failures                    *
**************************************************

1) Images page create, edit & delete image test should create image
  - Failed: No element found using locator: by.cssContainingText("select[name=pool] option", "e2e_images_pool")
  - Expected 1 to equal 0.
```

**Comment by sebastian-philipp** [comment]
qa failed: 


```
2020-02-13T15:45:21.072 INFO:ceph.mon.b.smithi164.stdout:Feb 13 15:45:20 smithi164 bash[15408]: audit 2020-02-13T15:45:10.679433+0000 mgr.y (mgr.14124) 25 : audit [DBG] from='client.14150 -' entity='client.admin' cmd=[{"prefix": "orch mon update", "num": 3, "hosts": ["smithi026:[v2:172.21.15.26:3301,v1:172.21.15.26:6790]=c"], "target": ["mon-mgr", ""]}]: dispatch
2020-02-13T15:45:21.072 INFO:ceph.mon.b.smithi164.stdout:Feb 13 15:45:20 smithi164 bash[15408]: cluster 2020-02-13T15:45:11.745344+0000 mgr.y (mgr.14124) 26 : cluster [DBG] pgmap v23: 0 pgs: ; 0 B data, 0 B used, 0 B / 0 B avail
2020-02-13T15:45:21.073 INFO:ceph.mon.b.smithi164.stdout:Feb 13 15:45:20 smithi164 bash[15408]: cluster 2020-02-13T15:45:13.745714+0000 mgr.y (mgr.14124) 27 : cluster [DBG] pgmap v24: 0 pgs: ; 0 B data, 0 B used, 0 B / 0 B avail
2020-02-13T15:45:21.073 INFO:ceph.mon.b.smithi164.stdout:Feb 13 15:45:20 smithi164 bash[15408]: cluster 2020-02-13T15:45:15.746120+0000 mgr.y (mgr.14124) 28 : cluster [DBG] pgmap v25: 0 pgs: ; 0 B data, 0 B used, 0 B / 0 B avail
2020-02-13T15:45:21.073 INFO:ceph.mon.b.smithi164.stdout:Feb 13 15:45:20 smithi164 bash[15408]: cluster 2020-02-13T15:45:17.746483+0000 mgr.y (mgr.14124) 29 : cluster [DBG] pgmap v26: 0 pgs: ; 0 B data, 0 B used, 0 B / 0 B avail
2020-02-13T15:45:21.074 INFO:ceph.mon.b.smithi164.stdout:Feb 13 15:45:20 smithi164 bash[15408]: cluster 2020-02-13T15:45:19.746780+0000 mgr.y (mgr.14124) 30 : cluster [DBG] pgmap v27: 0 pgs: ; 0 B data, 0 B used, 0 B / 0 B avail
2020-02-13T15:45:21.074 INFO:ceph.mon.b.smithi164.stdout:Feb 13 15:45:20 smithi164 bash[15408]: audit 2020-02-13T15:45:19.832128+0000 mon.a (mon.0) 145 : audit [INF] from='mgr.14124 172.21.15.26:0/1' entity='mgr.y' cmd=[{"prefix":"config-key set","key":"mgr/cephadm/host.services.smithi026","val":"{\"data\": [{\"style\": \"cephadm:v1\", \"name\": \"mon.a\", \"fsid\": \"86cbc6f8-4e77-11ea-99e5-001a4aab830c\", \"enabled\": true, \"state\": \"running\", \"container_id\": \"0781c3b2f496949de5bb8c5fb64a116dfdfe94897cdbce0b709f4d50b21d2675\", \"container_image_name\": \"quay.io/ceph-ci/ceph:c2b912fee0bc367c8e1abc0f39fb11f63145818c\", \"container_image_id\": \"5e8b3de3e373adf640c0929375ff4c605730dbaac7edece69923d8e16f31c3b1\", \"version\": \"15.1.0-577-ge9b5a97\", \"last_refresh\": \"2020-02-13T15:45:19.831542\"}, {\"style\": \"cephadm:v1\", \"name\": \"mgr.y\", \"fsid\": \"86cbc6f8-4e77-11ea-99e5-001a4aab830c\", \"enabled\": true, \"state\": \"running\", \"container_id\": \"7a0472c218bd155c55f6c4a55d6165fccb7cac478d22a4a48fbb183bdc660547\", \"container_image_name\": \"quay.io/ceph-ci/ceph:c2b912fee0bc367c8e1abc0f39fb11f63145818c\", \"container_image_id\": \"5e8b3de3e373adf640c0929375ff4c605730dbaac7edece69923d8e16f31c3b1\", \"version\": \"15.1.0-577-ge9b5a97\", \"last_refresh\": \"2020-02-13T15:45:19.831568\"}, {\"style\": \"cephadm:v1\", \"name\": \"crash.smithi026\", \"fsid\": \"86cbc6f8-4e77-11ea-99e5-001a4aab830c\", \"enabled\": true, \"state\": \"running\", \"container_id\": \"3b0a1f2bce472e9230d06f2eec84f6986118076db7116945073477708f59a02a\", \"container_image_name\": \"quay.io/ceph-ci/ceph:c2b912fee0bc367c8e1abc0f39fb11f63145818c\", \"container_image_id\": \"5e8b3de3e373adf640c0929375ff4c605730dbaac7edece69923d8e16f31c3b1\", \"version\": \"15.1.0-577-ge9b5a97\", \"last_refresh\": \"2020-02-13T15:45:19.831571\"}, {\"style\": \"cephadm:v1\", \"name\": \"mon.c\", \"fsid\": \"86cbc6f8-4e77-11ea-99e5-001a4aab830c\", \"enabled\": true, \"state\": \"running\", \"container_id\": \"29567b6fd65a9c63ed0bbb1689fa11021b8ce8725b0c6ffb76979864de4ca4db\", \"container_image_name\": \"quay.io/ceph-ci/ceph:c2b912fee0bc367c8e1abc0f39fb11f63145818c\", \"container_image_id\": \"5e8b3de3e373adf640c0929375ff4c605730dbaac7edece69923d8e16f31c3b1\", \"version\": \"15.1.0-577-ge9b5a97\", \"last_refresh\": \"2020-02-13T15:45:19.831574\"}], \"last_refresh\": \"2020-02-13 15:45:19.831695\"}"}]: dispatch
2020-02-13T15:45:21.074 INFO:ceph.mon.b.smithi164.stdout:Feb 13 15:45:20 smithi164 bash[15408]: audit 2020-02-13T15:45:19.836712+0000 mon.a (mon.0) 146 : audit [INF] from='mgr.14124 172.21.15.26:0/1' entity='mgr.y' cmd='[{"prefix":"config-key set","key":"mgr/cephadm/host.services.smithi026","val":"{\"data\": [{\"style\": \"cephadm:v1\", \"name\": \"mon.a\", \"fsid\": \"86cbc6f8-4e77-11ea-99e5-001a4aab830c\", \"enabled\": true, \"state\": \"running\", \"container_id\": \"0781c3b2f496949de5bb8c5fb64a116dfdfe94897cdbce0b709f4d50b21d2675\", \"container_image_name\": \"quay.io/ceph-ci/ceph:c2b912fee0bc367c8e1abc0f39fb11f63145818c\", \"container_image_id\": \"5e8b3de3e373adf640c0929375ff4c605730dbaac7edece69923d8e16f31c3b1\", \"version\": \"15.1.0-577-ge9b5a97\", \"last_refresh\": \"2020-02-13T15:45:19.831542\"}, {\"style\": \"cephadm:v1\", \"name\": \"mgr.y\", \"fsid\": \"86cbc6f8-4e77-11ea-99e5-001a4aab830c\", \"enabled\": true, \"state\": \"running\", \"container_id\": \"7a0472c218bd155c55f6c4a55d6165fccb7cac478d22a4a48fbb183bdc660547\", \"container_image_name\": \"quay.io/ceph-ci/ceph:c2b912fee0bc367c8e1abc0f39fb11f63145818c\", \"container_image_id\": \"5e8b3de3e373adf640c0929375ff4c605730dbaac7edece69923d8e16f31c3b1\", \"version\": \"15.1.0-577-ge9b5a97\", \"last_refresh\": \"2020-02-13T15:45:19.831568\"}, {\"style\": \"cephadm:v1\", \"name\": \"crash.smithi026\", \"fsid\": \"86cbc6f8-4e77-11ea-99e5-001a4aab830c\", \"enabled\": true, \"state\": \"running\", \"container_id\": \"3b0a1f2bce472e9230d06f2eec84f6986118076db7116945073477708f59a02a\", \"container_image_name\": \"quay.io/ceph-ci/ceph:c2b912fee0bc367c8e1abc0f39fb11f63145818c\", \"container_image_id\": \"5e8b3de3e373adf640c0929375ff4c605730dbaac7edece69923d8e16f31c3b1\", \"version\": \"15.1.0-577-ge9b5a97\", \"last_refresh\": \"2020-02-13T15:45:19.831571\"}, {\"style\": \"cephadm:v1\", \"name\": \"mon.c\", \"fsid\": \"86cbc6f8-4e77-11ea-99e5-001a4aab830c\", \"enabled\": true, \"state\": \"running\", \"container_id\": \"29567b6fd65a9c63ed0bbb1689fa11021b8ce8725b0c6ffb76979864de4ca4db\", \"container_image_name\": \"quay.io/ceph-ci/ceph:c2b912fee0bc367c8e1abc0f39fb11f63145818c\", \"container_image_id\": \"5e8b3de3e373adf640c0929375ff4c605730dbaac7edece69923d8e16f31c3b1\", \"version\": \"15.1.0-577-ge9b5a97\", \"last_refresh\": \"2020-02-13T15:45:19.831574\"}], \"last_refresh\": \"2020-02-13 15:45:19.831695\"}"}]': finished
2020-02-13T15:45:21.467 INFO:teuthology.orchestra.run.smithi164:> sudo /home/ubuntu/cephtest/cephadm --image quay.io/ceph-ci/ceph:c2b912fee0bc367c8e1abc0f39fb11f63145818c shell -c /home/ubuntu/cephtest/ceph.conf -k /home/ubuntu/cephtest/ceph.keyring --fsid 86cbc6f8-4e77-11ea-99e5-001a4aab830c -- ceph orch daemon reconfig mon.b
...
2020-02-13T15:45:23.169 INFO:teuthology.orchestra.run.smithi164.stderr:no valid command found; 10 closest matches:
2020-02-13T15:45:23.169 INFO:teuthology.orchestra.run.smithi164.stderr:orch host add <host> [<addr>] [<labels>...]
2020-02-13T15:45:23.169 INFO:teuthology.orchestra.run.smithi164.stderr:orch host rm <host>
2020-02-13T15:45:23.170 INFO:teuthology.orchestra.run.smithi164.stderr:orch host ls [json|plain]
2020-02-13T15:45:23.170 INFO:teuthology.orchestra.run.smithi164.stderr:orch host label add <host> <label>
2020-02-13T15:45:23.170 INFO:teuthology.orchestra.run.smithi164.stderr:orch host label rm <host> <label>
2020-02-13T15:45:23.170 INFO:teuthology.orchestra.run.smithi164.stderr:orch device ls [<host>...] [json|plain] [--refresh]
2020-02-13T15:45:23.170 INFO:teuthology.orchestra.run.smithi164.stderr:orch service ls [<host>] [mon|mgr|osd|mds|iscsi|nfs|rgw|rbd-mirror] [<svc_id>] [json|plain] [--refresh]
2020-02-13T15:45:23.171 INFO:teuthology.orchestra.run.smithi164.stderr:orch osd create [<svc_arg>]
2020-02-13T15:45:23.171 INFO:teuthology.orchestra.run.smithi164.stderr:orch osd rm <svc_id>...
2020-02-13T15:45:23.171 INFO:teuthology.orchestra.run.smithi164.stderr:orch rbd-mirror add [<num:int>] [<hosts>...]
2020-02-13T15:45:23.171 INFO:teuthology.orchestra.run.smithi164.stderr:Error EINVAL: invalid command
```

**Comment by sebastian-philipp** [comment]
This break the upgrade task:

http://qa-proxy.ceph.com/teuthology/swagner-2020-02-21_12:47:18-rados-wip-swagner-testing-2020-02-21-1025-distro-basic-smithi/4787386/teuthology.log

**Pull request merged**
