### PR TITLE
mon: remove filestore

### PR DESCRIPTION
**Pull request by Svelar**
Because filestore is no longer supported in Reef, we should remove it from code.

This PR is about fileStore depreciation for monitor module.

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [x] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by Svelar** [comment]
jenkins test make check arm64

**Review by kamoltat — CHANGES_REQUESTED** [review]
Hi can you add the motivation (in the PR and commit) to why you are getting rid of file_store in the monitor? I have not been following file_store stuff so I'm a bit confused. Thanks!

**Comment by Svelar** [comment]
> Hi can you add the motivation (in the PR and commit) to why you are getting rid of file_store in the monitor? I have not been following file_store stuff so I'm a bit confused. Thanks!

Update, please check.

**Comment by anthonyeleven** [comment]
The deprecation of the Filestore OSD back end has been hinted for several years.  BlueStore became default in Luminous IIRC.  Beginning to remove legacy Filestore code cleans up the codebase and streamlines the path forward.

**Comment by kamoltat** [comment]
@anthonyeleven
I understand, however, after looking at commit history of the filestore code, @pdvian added a commit on Jan 2022 to address an RFE https://tracker.ceph.com/issues/49275 which adds a health warning in ceph -s, which then notifies the user to migrate from filestore to bluestore. 

Therefore, it doesn't make sense to remove this ... @pdvian what do you think?

**Comment by Svelar** [comment]
> 

From Reef, filestore should not be supported. Not only me, Guillaume and some other contributors are also removing ‘filestore’ code, you could find it easily by searching the PRs about 'filestore'. Once #50657 is merged, filestore can not be used anymore, so we should clean up other filestore code and doc ASAP.

**Review by pdvian — COMMENTED** [review]
The filestore code has already been removed by https://github.com/ceph/ceph/pull/49528 so this PR make sense to remove the filestore warning code from the mon codebase.

**Review by kamoltat — APPROVED** [review]
LGTM

**Comment by ljflores** [comment]
Rados suite review: https://tracker.ceph.com/projects/rados/wiki/MAIN#httpstrellocomc1LQJnuRh1759-wip-yuri8-testing-2023-05-23-0802

**Comment by rzarzynski** [comment]
Thanks for cleaning this up, @Svelar!

**Pull request merged**
