### PR TITLE
hammer: rgw sends omap_getvals with (u64)-1 limit

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/18218

### CODE REVIEW

**Comment by smithfarm** [comment]
@mattbenjamin @oritwas @yehudasa This PR passed an rgw suite as detailed by http://tracker.ceph.com/issues/17151#note-30

Do you think it's OK to merge?

**Comment by smithfarm** [comment]
This passed another RGW suite at http://tracker.ceph.com/issues/17151#note-35

**Comment by oritwas** [comment]
lgtm

**Comment by smithfarm** [comment]
This just passed another RGW suite, see: http://tracker.ceph.com/issues/17151#note-39

**Pull request merged**
