### PR TITLE
mon: proposed fix for bug #14366

### PR DESCRIPTION
**Pull request by sahithi-rv**

### CODE REVIEW

**Comment by liewegas** [comment]
Also, why not take the lock in handle_log_clients instead of just one of the callers?

**Comment by sahithi-rv** [comment]
@jecluis sorry, there was no need of a lock in Monitor.cc: handle_conf_change().

**Comment by sahithi-rv** [comment]
@jecluis can you check it now

**Comment by athanatos** [comment]
@sahithi-rv This no longer builds.
@jecluis @tchaikov Is this still worth exploring?

**Comment by tchaikov** [comment]
by adding a lock in `LogMonitor::update_log_channels()` does not address the issue in http://tracker.ceph.com/issues/14366. because `md_config_obs_t::handle_conf_change()` is not likely to be called by different threads at the same time. and what we want to avoid the read-while-writing case described by http://tracker.ceph.com/issues/14366#note-1.

**Pull request closed without merging**
