### PR TITLE
rgw: Return correct XML response when delete role fail.

### PR DESCRIPTION
**Pull request by xijiacun**
## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by xijiacun** [comment]
Please help to reviews the codes, thanks @tchaikov @yehudasa

**Comment by xijiacun** [comment]
Please help to review the code, thanks @cbodley 
The tracker is commited by me, and my PR is ahead.

**Comment by xijiacun** [comment]
Please help to reviews the codes, thanks @tchaikov

**Review by tchaikov — APPROVED** [review]

**Comment by tchaikov** [comment]
@xijiacun thank you for your contribution, but i think #41800 has been approved . and as @BryceCao mentioned in https://github.com/ceph/ceph/pull/41800#issuecomment-858390430, he updated the tracker ticket before you did. in general, we coordinate the work using tracker ticket, in future, if you want to work on an issue or a feature, please make sure your work is not overlapped with others.

so i am closing this PR in favor of #41800 .

**Pull request closed without merging**
