### PR TITLE
jewel: rgw: copying part without http header x-amz-copy-source-range will be mistaken for copying object

### PR DESCRIPTION
**Pull request by joke-lee**
Backport tracker: http://tracker.ceph.com/issues/22904

> https://github.com/ceph/ceph/pull/21209

Signed-off-by: yuliyang <yuliyang@cmss.chinamobile.com>

### CODE REVIEW

**Comment by joke-lee** [comment]
@smithfarm code have update

**Comment by joke-lee** [comment]
can this merge now?

**Comment by joke-lee** [comment]
can this merge now

**Comment by smithfarm** [comment]
needs an rgw suite

**Comment by smithfarm** [comment]
@mattbenjamin I noticed you did the luminous backport of this fix in combination with another fix - see #20236

That other fix was not marked for backport to jewel, but I thought I'd ask if it would make sense to do the jewel backport in the same way?

**Comment by yuriw** [comment]
[wip-yuri4-testing-2018-05-23-1713-jewel](https://trello.com/c/sEAU8Gda/317-wip-yuri4-testing-2018-05-23-1713-jewel)

**Comment by mattbenjamin** [comment]
@smithfarm sure, if it's still an open item

**Comment by theanalyst** [comment]
@mattbenjamin I kind of  dropped it since some of the policy stuff and the functions aren't part of jewel and needs a little work before backporting

**Pull request merged**
