### PR TITLE
qa/suites/fs/upgrade: change octopus installations and references

### PR DESCRIPTION
**Pull request by ajarr**
... to pacific.

Fixes: https://tracker.ceph.com/issues/53996
Signed-off-by: Ramana Raja <rraja@redhat.com>

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [x] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by ajarr** [comment]
Observed failures,
https://pulpito.ceph.com/rraja-2022-04-10_00:40:48-fs-rraja-wip-53996-distro-default-smithi/
need to investigate further

**Comment by ajarr** [comment]
> Observed failures, https://pulpito.ceph.com/rraja-2022-04-10_00:40:48-fs-rraja-wip-53996-distro-default-smithi/ need to investigate further

The tests where a quincy MDS server is expected to evict a pacific ceph-fuse client as it doesn't support "metric_collect" feature, fails. However, the pacific fuse client (unlike an octopus client) supports "metric_collect", and does not get evicted.

e.g.,  See, https://github.com/ceph/ceph/blob/master/qa/suites/fs/upgrade/featureful_client/upgraded_client/tasks/4-compat_client.yaml#L9

Is there a feature that is supported only by quincy client/server but not by pacific client? I couldn't find one at,
https://docs.ceph.com/en/latest/cephfs/administration/#required-client-features
or
https://github.com/ceph/ceph/blob/master/src/mds/cephfs_features.h#L33

**Comment by vshankar** [comment]
> Maybe it's OK not to change "featureful client" upgrade suite for now, and just change the "nofs" upgrade suite in this PR? @vshankar @batrick what do you think?

We probably want to keep testing client eviction for unsupported features. Anyway we could keep whatever is tested currently, and add o->p/p->q changes?

**Comment by ajarr** [comment]
http://pulpito.front.sepia.ceph.com/rraja-2022-05-02_21:38:13-fs-ajarr-wip-53996-1-distro-default-smithi/

**Comment by ajarr** [comment]
**featureful client** was already testing octopus to quincy upgrade and tests were passing. I had to just rename couple of files in this suite from pacific to quincy to reflect that.

I think we're good.

**Comment by ajarr** [comment]
> http://pulpito.front.sepia.ceph.com/rraja-2022-05-02_21:38:13-fs-ajarr-wip-53996-1-distro-default-smithi/

@vshankar Tests passed.

**Review by vshankar — APPROVED** [review]

**Review by vshankar — APPROVED** [review]
https://tracker.ceph.com/projects/cephfs/wiki/Master#2022-May-12

**Comment by batrick** [comment]
Good work!

**Pull request merged**
