### PR TITLE
luminous: qa: get rid of iterkeys for py3 compatibility

### PR DESCRIPTION
**Pull request by shyukri**
backport tracker: https://tracker.ceph.com/issues/42322

---

backport of https://github.com/ceph/ceph/pull/30873
parent tracker: https://tracker.ceph.com/issues/42287

this backport was staged using ceph-backport.sh version 15.0.0.6950
find the latest version at https://github.com/ceph/ceph/blob/master/src/script/ceph-backport.sh

### CODE REVIEW

**Comment by smithfarm** [comment]
@shyukri Did you grep all of `qa/` for instances of `iterkeys`?

**Comment by shyukri** [comment]
All should be changed now.

**Comment by kshtsk** [comment]
This PR is supposed to be a back port of the my commit, but it didn't have following files which are part of the new commit:
qa/tasks/keystone.py 
qa/tasks/barbican.py
qa/tasks/netem.py
qa/tasks/ragweed.py
qa/tasks/tempest.py
qa/tasks/vault.py

Can they be submitted as a separate commit?
@smithfarm is it normal approach to bring the files not related to the commit message of original commit in a back port?

**Comment by smithfarm** [comment]
> is it normal approach to bring the files not related to the commit message of original commit in a back port?

@kshtsk Yes, we want the cherry-pick to be a functional (not formalistic) equivalent of the original.

@shyukri Can you add at the bottom of the commit message a brief description of the manual changes - maybe something like:

```
- ensured that all instances of iterkeys() under qa/ in luminous are changed to keys()
```

**Comment by kshtsk** [comment]
@smithfarm @shyukri what do we wait here?

**Comment by smithfarm** [comment]
@kshtsk Queued for integration testing.

**Comment by yuriw** [comment]
[wip-yuri8-testing-2020-04-20-1406-luminous](https://trello.com/c/emNHbbw6/874-wip-yuri8-testing-2020-04-20-1406-luminous)

**Comment by shyukri** [comment]
What should we do with this PR?

**Comment by shyukri** [comment]
What should we do with this PR?

**Comment by smithfarm** [comment]
> What should we do with this PR?

luminous EOL

**Pull request closed without merging**
