### PR TITLE
doc: use console lexer for rendering command line sessions

### PR DESCRIPTION
**Pull request by tchaikov**
by default the pygements uses python lexer for rendering literal blocks,
and `#` is considered as the marker for inline comments. in this change,
the "console" lexer is specified explicitly. see
https://pygments.org/docs/lexers/#lexers-for-various-shells for more details,
in which "BashSessionLexer" is for this very use case.

Signed-off-by: Kefu Chai <kchai@redhat.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by tchaikov** [comment]
jenkins render docs

**Comment by tchaikov** [comment]
please compare

- https://docs.ceph.com/ceph-prs/32141/bootstrap/ and
- https://docs.ceph.com/docs/master/bootstrap/

**Comment by tchaikov** [comment]
cc @zdover23

**Comment by zdover23** [comment]
Roger that.

This is a better solution than using sudo in every case.

Is the lexer used as described in the link below?

https://ipython.readthedocs.io/en/stable/development/lexer.html

Thanks, tchaikov.

**Comment by tchaikov** [comment]
@zdover23 could you take a look at the commit message at https://github.com/ceph/ceph/pull/32141/commits/310d145ef57ef400e820cf138215d0b77b0019c0 ?

**Pull request merged**
