### PR TITLE
qa: test standby-replay with fs:workloads

### PR DESCRIPTION
**Pull request by batrick**

### CODE REVIEW

**Comment by tchaikov** [comment]
jenkins test make check

**Comment by tchaikov** [comment]
jenkins test make check

**Comment by tchaikov** [comment]
jenkins test api

**Comment by batrick** [comment]
ping @ceph/cephfs

**Comment by batrick** [comment]
Found a small bug: https://tracker.ceph.com/issues/50215

**Comment by batrick** [comment]
https://pulpito.ceph.com/pdonnell-2021-04-07_02:12:41-fs-wip-pdonnell-testing-20210406.213012-distro-basic-smithi/

- https://tracker.ceph.com/issues/50215
    qa: "log [ERR] : error reading sessionmap 'mds2_sessionmap'"
- https://tracker.ceph.com/issues/49466
    qa: "Command failed on gibba030 with status 1: 'set -ex\nsudo dd of=/tmp/tmp.ZEeZBasJer'"
- https://tracker.ceph.com/issues/50216
    qa: "ls: cannot access 'lost+found': No such file or directory"
- https://tracker.ceph.com/issues/48773
    qa: scrub does not complete
- https://tracker.ceph.com/issues/49845
    qa: failed umount in test_volumes
- https://tracker.ceph.com/issues/50220
    qa: dbench workload timeout
- https://tracker.ceph.com/issues/50221
    qa: snaptest-git-ceph failure in git diff
- https://tracker.ceph.com/issues/50222
    osd: 5.2s0 deep-scrub : stat mismatch
- https://tracker.ceph.com/issues/50223
    qa: "client.4737 isn't responding to mclientcaps(revoke)"
- https://tracker.ceph.com/issues/50224
    qa: test_mirroring_init_failure_with_recovery failure

will rerun with bugfix

**Comment by batrick** [comment]
https://pulpito.ceph.com/pdonnell-2021-04-08_04:31:36-fs-wip-pdonnell-testing-20210408.024225-distro-basic-smithi/
https://pulpito.ceph.com/?branch=wip-pdonnell-testing-20210408.142238 (with logic inversion / QA fix)

- https://tracker.ceph.com/issues/50246
    mds: failure replaying journal (EMetaBlob)
- https://tracker.ceph.com/issues/50250
    mds: "log [WRN] : Scrub error on inode 0x10000004506 (/client.0/tmp/clients/client3/~dmtmp/COREL) see mds.a log and `damage ls` output for details"

**Comment by batrick** [comment]
jenkins test make check

**Comment by batrick** [comment]
https://tracker.ceph.com/projects/cephfs/wiki/Master#2021-Apr-08

**Comment by batrick** [comment]
`Reviewed-by: Patrick Donnelly <pdonnell@redhat.com>`

**Pull request merged**
