### PR TITLE
crimson/osd: fix recovery related bugs

### PR DESCRIPTION
**Pull request by xxhdx1985126**
Signed-off-by: Xuehan Xu <xxhdx1985126@gmail.com>
## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Review by tchaikov — COMMENTED** [review]
@xxhdx1985126 i created https://github.com/xxhdx1985126/ceph/pull/5 on top of your change.  just two improvements

* s/<tab>/spaces
* capture from=m->from in outer continuation

also, could you please add a short explanation as the body of commit message for each of the commits in this PR?

**Comment by xxhdx1985126** [comment]
@tchaikov Done:-)

**Comment by tchaikov** [comment]
@xxhdx1985126 could you reconsider the change in https://github.com/xxhdx1985126/ceph/pull/5 ?

**Comment by xxhdx1985126** [comment]
> @xxhdx1985126 could you reconsider the change in [xxhdx1985126#5](https://github.com/xxhdx1985126/ceph/pull/5) ?

Oh, sorry, I thought you intended to merge that PR, will change it immediately

**Comment by xxhdx1985126** [comment]
@tchaikov Done:-)

**Comment by xxhdx1985126** [comment]
@tchaikov Done:-)

**Review by tchaikov — APPROVED** [review]

**Pull request merged**
