### PR TITLE
[DNM] librbd: avoid blocking AIO API methods

### PR DESCRIPTION
**Pull request by dillaman**
http://tracker.ceph.com/issues/11056

### CODE REVIEW

**Comment by dachary** [comment]
@dillaman is it still DNM ?

**Comment by jdurgin** [comment]
Still DNM - not in master yet

**Comment by dillaman** [comment]
This has diverged somewhat from the final implementation in master -- closing.

**Comment by dillaman** [comment]
Replaced by PR #4854

**Pull request closed without merging**
