### PR TITLE
blk/kernel: use open file description lock if available

### PR DESCRIPTION
**Pull request by tchaikov**
## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by tchaikov** [comment]
jenkins test make check

**Review by nh2 — APPROVED** [review]
This looks good and addresses all my concerns from https://github.com/ceph/ceph/pull/34566#issuecomment-692133157, but https://github.com/X0Ken/ceph/blob/23f8c323d2ba9133c3ef5834ae93115425c862d1/src/common/options.cc#L3998 now needs to mention that negative means unlimited, e.g.

```c++
    .set_long_description(
        "The number of times to retry on getting the block device lock. "
        "Programs such as systemd-udevd may compete with Ceph for this lock. "
        "A negative number means 'unlimited'."),
```

Independent question: Is `3` still the best default, should it be longer, or should it loop forever without configurable max retry value (perhaps logging a warning instead)? It seems sensible to me in a situation like this where we know that the lock will eventually make progress.

**Comment by tchaikov** [comment]
> This looks good and addresses all my concerns from [#34566 (comment)](https://github.com/ceph/ceph/pull/34566#issuecomment-692133157), but https://github.com/X0Ken/ceph/blob/23f8c323d2ba9133c3ef5834ae93115425c862d1/src/common/options.cc#L3998 now needs to mention that negative means unlimited, e.g.
> 
> ```c++
>     .set_long_description(
>         "The number of times to retry on getting the block device lock. "
>         "Programs such as systemd-udevd may compete with Ceph for this lock. "
>         "A negative number means 'unlimited'."),
> ```
> 

thank you. i split the wait-forever change into a separate commit, as it's not related to the OFD lock change. and incorporated your suggestion into that commit.

> Independent question: Is `3` still the best default, should it be longer, or should it loop forever without configurable max retry value (perhaps logging a warning instead)? It seems sensible to me in a situation like this where we know that the lock will eventually make progress.

i cannot tell what is the best default. but by inspecting https://github.com/systemd/systemd/blob/ee0b9e721a368742ac6fa9c3d9a33e45dc3203a2/src/shared/lockfile-util.c#L45-L72 . i think 0.3 second should be enough for `make_lock_file()` to get its job done, unless the system is _very_ busy.

and after a second thought, i don't think to loop forever is a good default. a small number for the max retry times is like

```c++
assert(systemd_should_finish_its_job_in_a_short_time)
```

where short time is, well, a magic number. if, systemd cannot finish in 0.3 second, we should be aware of this right away. as it very likely indicates a serious issue in system. a warning in log is not enough for this signal, IMHO.

**Comment by tchaikov** [comment]
- https://pulpito.ceph.com/kchai-2020-09-16_14:28:48-rados-wip-kefu-testing-2020-09-16-1741-distro-basic-smithi/
- https://pulpito.ceph.com/kchai-2020-09-17_08:46:35-rados-wip-kefu-testing-2020-09-17-1122-distro-basic-smithi/

**Review by ifed01 — APPROVED** [review]
LGTM. Just one nit - may be more straightforward processing when bdev_flock_retry is set to 0. Currently this means MAX_INT retries which isn't obvious for users...

**Comment by tchaikov** [comment]
@ifed01 i don't follow you. do you mean we should retry forever if `bdev_flock_retry` is 0? that is exactly the behavior after this change. probably i should update the long_description accordingly.

**Comment by ifed01** [comment]
> @ifed01 i don't follow you. do you mean we should retry forever if `bdev_flock_retry` is 0? that is exactly the behavior after this change. probably i should update the long_description accordingly.

Given prefix form for (++nr_tries) and initial setting nr_tries=0 it looks like the current behavior when bdev_flock_retry == 0 is to to repeat MAX_UINT times and stop. This is neither a "forever" loop nor "meaningful" behavior for such a setting.
IMO it's a bit confusing, it's better either use 0 as a major "forever" indicator (not negative value) or treat bdev_flock_retry explicitly as a RETRY counter assuming that one attempt is always performed. I.e. retry = 0 -> 1 attempt, retry = 1 -> 2 attempts, etc...

**Comment by tchaikov** [comment]
```c++
max_retry > 0 && ++nr_tries == max_retry
```
if the setting (`max_retry`) is `0`, this expression always evaluates to `false`, and the loop never ends unless `r` is 0.

but yeah, the setting is not **re**try anymore, it is actually `nr_tries`. will fix it.

**Comment by tchaikov** [comment]
@ifed01 fixed and repushed.

**Comment by tchaikov** [comment]
- https://pulpito.ceph.com/kchai-2020-09-26_11:23:24-rados-wip-kefu-testing-2020-09-25-2324-distro-basic-smithi/
- https://pulpito.ceph.com/kchai-2020-09-27_03:11:59-rados-wip-kefu-testing-2020-09-25-2324-distro-basic-smithi/
- https://pulpito.ceph.com/kchai-2020-09-27_14:40:39-rados-wip-kefu-testing-2020-09-25-2325-distro-basic-smithi

**Pull request merged**
