### PR TITLE
tools/ceph_monstore_tool: update pgmap_meta also when rebuilding store.db

### PR DESCRIPTION
**Pull request by tchaikov**
we should rebuild pgmap_meta table from the collected osdmaps

Fixes: http://tracker.ceph.com/issues/17400
Signed-off-by: Kefu Chai <kchai@redhat.com>

### CODE REVIEW

**Comment by tchaikov** [comment]
@renhwztetecs and @zphj1987 could you help test this change? thanks!

**Comment by renhwztetecs** [comment]
I will be test it later

**Comment by tchaikov** [comment]
@renhwztetecs thanks in advance!

**Comment by renhwztetecs** [comment]
@tchaikov 
nothing coredump and test pass. :+1: 
client.admin lack of caps after rebuild, 
I push PR fix it, please reviews.
https://github.com/ceph/ceph/pull/11381

**Comment by tchaikov** [comment]
@renhwztetecs i updated the doc and tool to address your concern. does it look better?

**Comment by tchaikov** [comment]
test passed at http://pulpito.ceph.com/kchai-2016-10-10_10:05:13-rados-wip-kefu-testing---basic-mira/

and qa suite updated accordingly, see  https://github.com/ceph/ceph-qa-suite/pull/1200

**Comment by renhwztetecs** [comment]
yeah!

**Comment by tchaikov** [comment]
@jecluis could you take a look?

**Comment by tchaikov** [comment]
@gregsfortytwo could you take a look also? thanks.

**Comment by gregsfortytwo** [comment]
restest this please

**Comment by gregsfortytwo** [comment]
I'm confused, did we have this function while not actually invoking it anywhere?

**Comment by tchaikov** [comment]
@gregsfortytwo  yes, i forgot to call it.

**Comment by tchaikov** [comment]
it's already tested at http://pulpito.ceph.com/kchai-2016-10-10_10:05:13-rados-wip-kefu-testing---basic-mira/, so i am merging it.

**Comment by smithfarm** [comment]
The hammer backport is non-trivial. Anyone here care to give it a try? It's http://tracker.ceph.com/issues/17602

**Comment by tchaikov** [comment]
@smithfarm it's included in #11125.

**Pull request merged**
