### PR TITLE
rgw: remove lc entry when deleting bucket

### PR DESCRIPTION
**Pull request by yaozongyou**
Signed-off-by: Yao Zongyou <yaozongyou@vip.qq.com>

### CODE REVIEW

**Comment by yaozongyou** [comment]
@cbodley may you please have a look at this?

**Comment by yaozongyou** [comment]
retest this please

**Comment by cbodley** [comment]
hi @yaozongyou, i'm not sure that it's a good idea to block DeleteBucket requests while waiting on the lifecycle lock for this. i'd rather find a way to do this in the background, like during lifecycle (or gc?) processing

**Comment by ZVampirEM77** [comment]
@cbodley @yaozongyou maybe we can add a filter in `radosgw-admin lc list` and cleanup those deleted buckets' lc entries during lifecycle~

**Comment by yaozongyou** [comment]
sorry for my mistake, the lc entry has been asynchronously removed in RGWLC::bucket_lc_post:
https://github.com/ceph/ceph/blob/master/src/rgw/rgw_lc.cc#L580

**Pull request closed without merging**
