### PR TITLE
[FOLLOWED ON #42821] mgr/dashbord: force maintenance e2e failing for host

### PR DESCRIPTION
**Pull request by avanthakkar**
Fixes: https://tracker.ceph.com/issues/51728
Signed-off-by: Avan Thakkar <athakkar@redhat.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by epuertat** [comment]
@avanthakkar can you please explain what was the issue and what have you done for fixing it? Thanks!

**Comment by epuertat** [comment]
And please add the PR number to the tracker issue. Thanks!

**Comment by nizamial09** [comment]
jenkins test dashboard

**Comment by nizamial09** [comment]
jenkins test dashboard

**Comment by avanthakkar** [comment]
jenkins test dashboard

**Review by tchaikov — CHANGES_REQUESTED** [review]
```
2021-08-03T01:10:15.114 INFO:tasks.workunit.client.0.smithi078.stdout:  1) OSDs page
2021-08-03T01:10:15.114 INFO:tasks.workunit.client.0.smithi078.stdout:       when Orchestrator is available
2021-08-03T01:10:15.114 INFO:tasks.workunit.client.0.smithi078.stdout:         should create and delete OSDs:
2021-08-03T01:10:15.115 INFO:tasks.workunit.client.0.smithi078.stdout:
2021-08-03T01:10:15.115 INFO:tasks.workunit.client.0.smithi078.stdout:      Timed out retrying
2021-08-03T01:10:15.115 INFO:tasks.workunit.client.0.smithi078.stdout:      + expected - actual
2021-08-03T01:10:15.115 INFO:tasks.workunit.client.0.smithi078.stdout:
2021-08-03T01:10:15.115 INFO:tasks.workunit.client.0.smithi078.stdout:      -3
2021-08-03T01:10:15.116 INFO:tasks.workunit.client.0.smithi078.stdout:      +6
2021-08-03T01:10:15.116 INFO:tasks.workunit.client.0.smithi078.stdout:
2021-08-03T01:10:15.116 INFO:tasks.workunit.client.0.smithi078.stdout:      at Context.eval (https://172.21.15.78:8443/__cypress/tests?p=cypress/integration/orchestrator/04-osds.e2e-spec.ts:380:61)
```

https://pulpito.ceph.com/kchai-2021-08-03_00:34:30-rados-wip-kefu-testing-2021-08-02-1223-1-distro-basic-smithi/6307972/

**Comment by epuertat** [comment]
jenkins test dashboard cephadm

**Comment by tchaikov** [comment]
```
2021-08-05T10:35:17.034 INFO:tasks.workunit.client.0.smithi082.stdout:      1) should create and delete OSDs
2021-08-05T10:35:17.191 INFO:tasks.workunit.client.0.smithi082.stdout:2021-08-05T10:35:17Z Eyes: [LOG    ] {} (): [server] eyes api: batchEnd
2021-08-05T10:35:17.191 INFO:tasks.workunit.client.0.smithi082.stdout:2021-08-05T10:35:17Z Eyes: [LOG    ] {} Object.batchEnd(): [handlers] batchEnd
2021-08-05T10:35:17.191 INFO:tasks.workunit.client.0.smithi082.stdout:2021-08-05T10:35:17Z Eyes: [LOG    ] {} (): Waiting for test results of 0 tests.
2021-08-05T10:35:18.235 INFO:tasks.workunit.client.0.smithi082.stdout:2021-08-05T10:35:18Z Eyes: [LOG    ] {} (): [server] eyes api: batchEnd
2021-08-05T10:35:18.235 INFO:tasks.workunit.client.0.smithi082.stdout:2021-08-05T10:35:18Z Eyes: [LOG    ] {} Object.batchEnd(): [handlers] batchEnd
2021-08-05T10:35:18.452 INFO:tasks.workunit.client.0.smithi082.stdout:
2021-08-05T10:35:18.453 INFO:tasks.workunit.client.0.smithi082.stdout:
2021-08-05T10:35:18.453 INFO:tasks.workunit.client.0.smithi082.stdout:  0 passing (5m)
2021-08-05T10:35:18.453 INFO:tasks.workunit.client.0.smithi082.stdout:  1 failing
2021-08-05T10:35:18.453 INFO:tasks.workunit.client.0.smithi082.stdout:
2021-08-05T10:35:18.454 INFO:tasks.workunit.client.0.smithi082.stdout:  1) OSDs page
2021-08-05T10:35:18.454 INFO:tasks.workunit.client.0.smithi082.stdout:       when Orchestrator is available
2021-08-05T10:35:18.454 INFO:tasks.workunit.client.0.smithi082.stdout:         should create and delete OSDs:
2021-08-05T10:35:18.455 INFO:tasks.workunit.client.0.smithi082.stdout:
2021-08-05T10:35:18.455 INFO:tasks.workunit.client.0.smithi082.stdout:      Timed out retrying
2021-08-05T10:35:18.455 INFO:tasks.workunit.client.0.smithi082.stdout:      + expected - actual
2021-08-05T10:35:18.455 INFO:tasks.workunit.client.0.smithi082.stdout:
2021-08-05T10:35:18.456 INFO:tasks.workunit.client.0.smithi082.stdout:      -3
2021-08-05T10:35:18.456 INFO:tasks.workunit.client.0.smithi082.stdout:      +6
2021-08-05T10:35:18.456 INFO:tasks.workunit.client.0.smithi082.stdout:
2021-08-05T10:35:18.456 INFO:tasks.workunit.client.0.smithi082.stdout:      at Context.eval (https://172.21.15.82:8443/__cypress/tests?p=cypress/integration/orchestrator/04-osds.e2e-spec.ts:380:61)
2021-08-05T10:35:18.456 INFO:tasks.workunit.client.0.smithi082.stdout:
2021-08-05T10:35:18.457 INFO:tasks.workunit.client.0.smithi082.stdout:
2021-08-05T10:35:18.457 INFO:tasks.workunit.client.0.smithi082.stdout:
2021-08-05T10:35:18.461 INFO:tasks.workunit.client.0.smithi082.stdout:
2021-08-05T10:35:18.462 INFO:tasks.workunit.client.0.smithi082.stdout:  (Results)
```

https://pulpito.ceph.com/kchai-2021-08-05_09:56:39-rados-wip-kefu-testing2-2021-08-05-1425-distro-basic-smithi/6312068/

**Comment by tchaikov** [comment]
@epuertat and @avanthakkar ping?

**Comment by avanthakkar** [comment]
> @epuertat and @avanthakkar ping?

work continued here https://github.com/ceph/ceph/pull/42821 . I think this will be closed once fix is ready in mentioned PR, right @nizamial09 ?

**Comment by nizamial09** [comment]
> > @epuertat and @avanthakkar ping?
> 
> work continued here #42821 . I think this will be closed once fix is ready in mentioned PR, right @nizamial09 ?

you are right @avanthakkar I am gonna close this in favor of  #42821

**Pull request closed without merging**
