### PR TITLE
client: flush kernel pagecache before creating snapshot

### PR DESCRIPTION
**Pull request by ukernel**
Fixes: #10436
Signed-off-by: Yan, Zheng <zyan@redhat.com>

### CODE REVIEW

**Comment by ukernel** [comment]
ceph-qa https://github.com/ceph/ceph-qa-suite/pull/812

**Comment by ukernel** [comment]
tested by running snaptest-multiple-capsnaps.sh and snaptest-snap-rm-cmp.sh manully

**Comment by gregsfortytwo** [comment]
Looks simple enough!

**Comment by gregsfortytwo** [comment]
This failed its test: http://pulpito.ceph.com/gregf-2016-02-03_09:19:17-fs-greg-fs-testing-23---basic-mira/4567/

:(

**Comment by gregsfortytwo** [comment]
@ukernel ^

**Comment by ukernel** [comment]
Updated.

Old code actually syncfs on filesystem of mount point directory. I don't think how it affected the test I ran

**Comment by ukernel** [comment]
updated. the old code actually sync filesystem of mount point directory

**Comment by gregsfortytwo** [comment]
Integration branches are still seeing failures with the snaptest-rm-cmp.sh workunit, even under this branch: http://pulpito.ceph.com/gregf-2016-02-15_19:55:22-fs-greg-fs-testing-215-1---basic-mira/10848/

**Comment by gregsfortytwo** [comment]
I'll be scheduling a test of just this branch (merged to master) once it finishes building.

**Comment by gregsfortytwo** [comment]
Results will be showing up at http://pulpito.ceph.com/gregf-2016-02-17_22:33:22-fs-greg-pr-7495---basic-mira/

**Comment by gregsfortytwo** [comment]
Hmm, it passed that last run (two valgrind errors on http://tracker.ceph.com/issues/14794, plus a package install noise). I scheduled a few more runs of the snaptests against it.

**Comment by gregsfortytwo** [comment]
http://pulpito.ceph.com/gregf-2016-02-18_06:56:00-fs-greg-pr-7495---basic-mira/15129/ :(

Still in progress: http://pulpito.ceph.com/gregf-2016-02-18_06:55:38-fs-greg-pr-7495---basic-mira/
http://pulpito.ceph.com/gregf-2016-02-18_06:55:56-fs-greg-pr-7495---basic-mira/

**Comment by ukernel** [comment]
bad md5sum for both failures is 866dc09e4986c72ad8864bd4c8839794, which is md5sum of linux-2.6.33.tar.bz2's first 32M data. This should be caused by wrong i_size .

**Comment by ukernel** [comment]
FYI: I still can't reproduce this issue locally, not sure if the new commit fixes the issue

**Comment by ukernel** [comment]
scheduled 5 runs, all passed
http://pulpito.ceph.com/ubuntu-2016-02-29_00:00:47-fs-wip-10436-testing-basic-multi
http://pulpito.ceph.com/ubuntu-2016-02-29_01:16:37-fs-wip-10436-testing-basic-mira
http://pulpito.ceph.com/ubuntu-2016-02-29_01:25:17-fs-wip-10436-testing-basic-mira
http://pulpito.ceph.com/zyan-2016-02-29_17:58:34-fs-wip-10436-testing-basic-mira
http://pulpito.ceph.com/zyan-2016-02-29_17:58:25-fs-wip-10436-testing-basic-multi

**Comment by gregsfortytwo** [comment]
@ukernel, I don't get this last commit. What sequence of events do we need to hit in order to have stale data on a snapshot? (I presume it must be a snapshot whose data is still being flushed out.) Can't we do something a little more carefully to avoid sending every snapshot getattr request as an op to the MDS? (It's very expensive!)

**Comment by gregsfortytwo** [comment]
So snaptest-multiple-capsnaps.sh failed again on an integration branch including this: http://pulpito.ceph.com/gregf-2016-03-07_23:12:27-fs-greg-fs-testing-3-7-safe---basic-mira/46126/

I didn't dig into why. :/

**Comment by ukernel** [comment]
found a bug in queue_cap_snap() code. the new commit should fix this issue.

**Comment by ukernel** [comment]
http://pulpito.ceph.com/zyan-2016-03-09_18:34:54-fs-jewel-10436---basic-vps/
http://pulpito.ceph.com/zyan-2016-03-09_18:25:12-fs-jewel-10436---basic-mira/
http://pulpito.ceph.com/zyan-2016-03-09_18:24:59-fs-jewel-10436---basic-smithi/
http://pulpito.ceph.com/zyan-2016-03-09_18:23:51-fs-jewel-10436---basic-smithi/
http://pulpito.ceph.com/zyan-2016-03-09_18:23:40-fs-jewel-10436---basic-mira/
http://pulpito.ceph.com/zyan-2016-03-09_18:11:27-fs-jewel-10436---basic-multi/

all passed

**Comment by gregsfortytwo** [comment]
Hurray!

**Pull request merged**
