### PR TITLE
mimic: osd: src/osd/OSDMap.h: 1065: FAILED assert(__null != pool)

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/38450

### CODE REVIEW

**Comment by smithfarm** [comment]
Build failure:

```
/home/jenkins-build/build/workspace/ceph-pull-requests/src/osd/OSD.cc: In member function 'bool OSD::project_pg_history(spg_t, pg_history_t&, epoch_t, const OSDMap&, const std::vector<int>&, int, const std::vector<int>&, int)':
/home/jenkins-build/build/workspace/ceph-pull-requests/src/osd/OSD.cc:4218:51: error: base operand of '->' has non-pointer type 'const OSDMap'
            << " from " << from << " to " << endmap->get_epoch()
                                                   ^~
/home/jenkins-build/build/workspace/ceph-pull-requests/src/osd/OSD.cc:4223:18: error: base operand of '->' has non-pointer type 'const OSDMap'
   for (e = endmap->get_epoch();
                  ^~
/home/jenkins-build/build/workspace/ceph-pull-requests/src/osd/OSD.cc:4258:15: error: base operand of '->' has non-pointer type 'const OSDMap'
         endmap->get_pg_num(pgid.pool()),
               ^~
/home/jenkins-build/build/workspace/ceph-pull-requests/src/osd/OSD.cc: In member function 'void OSD::handle_pg_query_nopg(const MQuery&)':
/home/jenkins-build/build/workspace/ceph-pull-requests/src/osd/OSD.cc:8612:43: error: no matching function for call to 'OSD::project_pg_history(spg_t&, pg_history_t&, const epoch_t&, OSDMapRef&, std::vector<int>&, int&, std::vector<int>&, int&)'
     up, up_primary, acting, acting_primary);
                                           ^
/home/jenkins-build/build/workspace/ceph-pull-requests/src/osd/OSD.cc:4210:6: note: candidate: bool OSD::project_pg_history(spg_t, pg_history_t&, epoch_t, const OSDMap&, const std::vector<int>&, int, const std::vector<int>&, int)
 bool OSD::project_pg_history(spg_t pgid, pg_history_t& h, epoch_t from,
      ^~~
/home/jenkins-build/build/workspace/ceph-pull-requests/src/osd/OSD.cc:4210:6: note:   no known conversion for argument 4 from 'OSDMapRef {aka std::shared_ptr<const OSDMap>}' to 'const OSDMap&'
src/osd/CMakeFiles/osd.dir/build.make:62: recipe for target 'src/osd/CMakeFiles/osd.dir/OSD.cc.o' failed
make[3]: *** [src/osd/CMakeFiles/osd.dir/OSD.cc.o] Error 1
```

**Comment by smithfarm** [comment]
@dzafman Could I trouble you to look at the build failure? It's too non-trivial for my poor brain.

**Comment by dzafman** [comment]
retest this please

**Comment by smithfarm** [comment]
build still failing; rebased

**Comment by smithfarm** [comment]
closing because the backport is non-trivial

**Pull request closed without merging**
