### PR TITLE
mds: add scrub perf counters support

### PR DESCRIPTION
**Pull request by lxbsz**
## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by lxbsz** [comment]
This PR depends on https://github.com/ceph/ceph/pull/38672 and will rebase it after https://github.com/ceph/ceph/pull/38672 merged.

**Review by batrick — APPROVED** [review]

**Comment by batrick** [comment]
please rebase

**Comment by lxbsz** [comment]
> please rebase

Done. Thanks.

**Review by batrick — APPROVED** [review]

**Comment by batrick** [comment]
https://pulpito.ceph.com/pdonnell-2021-01-08_05:07:01-fs-wip-pdonnell-testing-20210107.220115-distro-basic-smithi/

New failures are:
- https://tracker.ceph.com/issues/48811

**Pull request merged**
