### PR TITLE
octopus: osdc: add timeout configs for mons/osds

### PR DESCRIPTION
**Pull request by batrick**
https://tracker.ceph.com/issues/47942

### CODE REVIEW

**Comment by batrick** [comment]
jenkins test make check

**Comment by batrick** [comment]
jenkins test api

**Comment by batrick** [comment]
https://pulpito.ceph.com/pdonnell-2020-10-04_21:51:57-fs-wip-pdonnell-testing-20201004.051319-octopus-distro-basic-smithi/

tested with #37529. Just need to catch the expected exception.

**Comment by batrick** [comment]
https://pulpito.ceph.com/pdonnell-2020-10-06_18:17:45-fs-wip-pdonnell-testing-20201006.164704-octopus-distro-basic-smithi/

**Comment by batrick** [comment]
retest this please

**Comment by batrick** [comment]
https://pulpito.ceph.com/pdonnell-2020-10-23_20:06:48-fs-wip-pdonnell-testing-20201023.172652-octopus-distro-basic-smithi/

**Comment by batrick** [comment]
This is ready for wider testing in regular octopus QA.

**Comment by batrick** [comment]
@yuriw this needs tested with #37256.

**Comment by yuriw** [comment]
[wip-yuri3-testing-2020-10-26-1241-octopus](https://trello.com/c/IprObvVi/1049-wip-yuri3-testing-2020-10-26-1241-octopus)

**Comment by yuriw** [comment]
[wip-yuri4-testing-2020-10-27-1210-octopus](https://trello.com/c/ei09zCqO/1050-wip-yuri4-testing-2020-10-27-1210-octopus)

**Comment by yuriw** [comment]
passed rbd approved by @dillaman

**Review by yuriw — APPROVED** [review]
Reviewed-by: Patrick Donnelly <pdonnell@redhat.com>

**Pull request merged**
