### PR TITLE
luminous: osd: Prioritize user specified scrubs

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/37343

### CODE REVIEW

**Comment by dzafman** [comment]
Does _../qa/run-standalone.sh "osd-scrub-repair.sh TEST_request_scrub_priority"_ pass?

**Comment by smithfarm** [comment]
@dzafman I generally do not compile locally, so no, not yet.

**Comment by dzafman** [comment]
@smithfarm I'm building this branch to run the test.

**Comment by yuriw** [comment]
[wip-yuri3-testing-2019-01-03-1654-luminous](https://trello.com/c/vFwbW3TH/497-wip-yuri3-testing-2019-01-03-1654-luminous)

**Pull request merged**
