### PR TITLE
pybind/mgr: maximum recursion depth exceeded in comparison

### PR DESCRIPTION
**Pull request by hswong3i**
Original issue from https://github.com/python/typing_extensions/issues/10

In case typing-extensions is upgrade to 4.1.1 (https://pypi.org/project/typing-extensions/4.1.1/, the final Python 3.6
supported version), Ceph MGR will failed with pg_autoscaler as below:

    [root@cp-nightsky ~]# pip list | grep typing-extensions
    typing-extensions      4.1.1

    [root@cp-nightsky ~]# systemctl restart ceph-mgr@cp-nightsky.service

    [root@cp-nightsky ~]# journalctl -xef -u ceph-mgr@cp-nightsky.service
    May 12 06:16:39 cp-nightsky.novalocal systemd[1]: Started Ceph cluster manager daemon.
    -- Subject: Unit ceph-mgr@cp-nightsky.service has finished start-up
    -- Defined-By: systemd
    -- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
    --
    -- Unit ceph-mgr@cp-nightsky.service has finished starting up.
    --
    -- The start-up result is done.
    May 12 06:16:51 cp-nightsky.novalocal ceph-mgr[1719]: 2022-05-12T06:16:51.181+0000 7fe3eb521700 -1 log_channel(cluster) log [ERR] : Unhandled exception from module 'pg_autoscaler' while running on mgr.cp-nightsky: maximum recursion depth exceeded in comparison
    May 12 06:16:51 cp-nightsky.novalocal ceph-mgr[1719]: 2022-05-12T06:16:51.182+0000 7fe3eb521700 -1 pg_autoscaler.serve:
    May 12 06:16:51 cp-nightsky.novalocal ceph-mgr[1719]: 2022-05-12T06:16:51.182+0000 7fe3eb521700 -1 Traceback (most recent call last):
    May 12 06:16:51 cp-nightsky.novalocal ceph-mgr[1719]: File "/usr/share/ceph/mgr/pg_autoscaler/module.py", line 206, in serve
    May 12 06:16:51 cp-nightsky.novalocal ceph-mgr[1719]: self._maybe_adjust()
    May 12 06:16:51 cp-nightsky.novalocal ceph-mgr[1719]: File "/usr/share/ceph/mgr/pg_autoscaler/module.py", line 423, in _maybe_adjust
    May 12 06:16:51 cp-nightsky.novalocal ceph-mgr[1719]: ps, root_map, pool_root = self._get_pool_status(osdmap, pools)
    May 12 06:16:51 cp-nightsky.novalocal ceph-mgr[1719]: File "/usr/share/ceph/mgr/pg_autoscaler/module.py", line 325, in _get_pool_status
    May 12 06:16:51 cp-nightsky.novalocal ceph-mgr[1719]: self.log.debug('skipping empty subtree %s', cr_name)
    May 12 06:16:51 cp-nightsky.novalocal ceph-mgr[1719]: File "/lib64/python3.6/logging/__init__.py", line 1296, in debug
    May 12 06:16:51 cp-nightsky.novalocal ceph-mgr[1719]: self._log(DEBUG, msg, args, **kwargs)
    May 12 06:16:51 cp-nightsky.novalocal ceph-mgr[1719]: File "/lib64/python3.6/logging/__init__.py", line 1443, in _log
    May 12 06:16:51 cp-nightsky.novalocal ceph-mgr[1719]: exc_info, func, extra, sinfo)
    May 12 06:16:51 cp-nightsky.novalocal ceph-mgr[1719]: File "/lib64/python3.6/logging/__init__.py", line 1413, in makeRecord
    May 12 06:16:51 cp-nightsky.novalocal ceph-mgr[1719]: sinfo)
    May 12 06:16:51 cp-nightsky.novalocal ceph-mgr[1719]: File "/lib64/python3.6/logging/__init__.py", line 277, in __init__
    May 12 06:16:51 cp-nightsky.novalocal ceph-mgr[1719]: if (args and len(args) == 1 and isinstance(args[0], collections.Mapping)
    May 12 06:16:51 cp-nightsky.novalocal ceph-mgr[1719]: File "/lib64/python3.6/abc.py", line 193, in __instancecheck__
    May 12 06:16:51 cp-nightsky.novalocal ceph-mgr[1719]: return cls.__subclasscheck__(subclass)
    May 12 06:16:51 cp-nightsky.novalocal ceph-mgr[1719]: File "/lib64/python3.6/abc.py", line 228, in __subclasscheck__
    May 12 06:16:51 cp-nightsky.novalocal ceph-mgr[1719]: if issubclass(subclass, scls):
    May 12 06:16:51 cp-nightsky.novalocal ceph-mgr[1719]: File "/lib64/python3.6/abc.py", line 228, in __subclasscheck__
    May 12 06:16:51 cp-nightsky.novalocal ceph-mgr[1719]: if issubclass(subclass, scls):
    May 12 06:16:51 cp-nightsky.novalocal ceph-mgr[1719]: File "/lib64/python3.6/typing.py", line 1154, in __subclasscheck__
    May 12 06:16:51 cp-nightsky.novalocal ceph-mgr[1719]: return super().__subclasscheck__(cls)
    May 12 06:16:51 cp-nightsky.novalocal ceph-mgr[1719]: File "/lib64/python3.6/abc.py", line 228, in __subclasscheck__
    May 12 06:16:51 cp-nightsky.novalocal ceph-mgr[1719]: if issubclass(subclass, scls):
    May 12 06:16:51 cp-nightsky.novalocal ceph-mgr[1719]: File "/lib/python3.6/site-packages/typing_extensions.py", line 426, in __subclasscheck__
    May 12 06:16:51 cp-nightsky.novalocal ceph-mgr[1719]: if issubclass(subclass, scls):
    May 12 06:16:51 cp-nightsky.novalocal ceph-mgr[1719]: File "/lib/python3.6/site-packages/typing_extensions.py", line 426, in __subclasscheck__
    May 12 06:16:51 cp-nightsky.novalocal ceph-mgr[1719]: if issubclass(subclass, scls):
    May 12 06:16:51 cp-nightsky.novalocal ceph-mgr[1719]: File "/lib/python3.6/site-packages/typing_extensions.py", line 426, in __subclasscheck__
    May 12 06:16:51 cp-nightsky.novalocal ceph-mgr[1719]: if issubclass(subclass, scls):
    May 12 06:16:51 cp-nightsky.novalocal ceph-mgr[1719]: [Previous line repeated 239 more times]
    May 12 06:16:51 cp-nightsky.novalocal ceph-mgr[1719]: File "/lib/python3.6/site-packages/typing_extensions.py", line 421, in __subclasscheck__
    May 12 06:16:51 cp-nightsky.novalocal ceph-mgr[1719]: if self.__extra__ in subclass.__mro__:
    May 12 06:16:51 cp-nightsky.novalocal ceph-mgr[1719]: RecursionError: maximum recursion depth exceeded in comparison
    May 12 06:16:51 cp-nightsky.novalocal ceph-mgr[1719]: 2022-05-12T06:16:51.291+0000 7fe3de3c7700 -1 client.0 error registering admin socket command: (17) File exists
    May 12 06:16:51 cp-nightsky.novalocal ceph-mgr[1719]: 2022-05-12T06:16:51.291+0000 7fe3de3c7700 -1 client.0 error registering admin socket command: (17) File exists
    May 12 06:16:51 cp-nightsky.novalocal ceph-mgr[1719]: 2022-05-12T06:16:51.291+0000 7fe3de3c7700 -1 client.0 error registering admin socket command: (17) File exists
    May 12 06:16:51 cp-nightsky.novalocal ceph-mgr[1719]: 2022-05-12T06:16:51.291+0000 7fe3de3c7700 -1 client.0 error registering admin socket command: (17) File exists
    May 12 06:16:51 cp-nightsky.novalocal ceph-mgr[1719]: 2022-05-12T06:16:51.291+0000 7fe3de3c7700 -1 client.0 error registering admin socket command: (17) File exists

Solution provided by https://github.com/python/typing_extensions/issues/10#issuecomment-1131767191 not working:

    self.log.debug('skipping empty subtree %s', str(cr_name))

But implement with `.format` could help:

    self.log.debug("skipping empty subtree {0}".format(cr_name))

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/master/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [x] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by tchaikov** [comment]
@hswong3i hi Hoi Sing, thanks for your contribution,

the title of the commit message reads like a bug report. ideally, the title of the commit message should use the imperative mood. see also https://github.com/ceph/ceph/blob/master/SubmittingPatches.rst#3-describe-your-changes . please use `git commit --amend`  and `git push -f` for revising the commit message and its title.

could you prefix the title of your commit message with the subcomponent your are changing ? see https://github.com/ceph/ceph/blob/master/SubmittingPatches.rst#3-describe-your-changes . it should be "pybind/mgr: ".

**Comment by tchaikov** [comment]
- https://pulpito.ceph.com/kchai-2022-08-07_05:39:26-rados-wip-kefu-testing-2022-08-07-1123-distro-default-smithi/
- https://pulpito.ceph.com/kchai-2022-08-07_07:44:14-rados-wip-kefu-testing-2022-08-07-1123-distro-default-smithi/

the `sudo yum -y install ceph-radosgw` failures are tracked by https://tracker.ceph.com/issues/57051

**Comment by hswong3i** [comment]
> could you prefix the title of your commit message with the subcomponent your are changing ? see https://github.com/ceph/ceph/blob/master/SubmittingPatches.rst#3-describe-your-changes . it should be "pybind/mgr: ".

@tchaikov sorry for my delay, commit message update, rebase with main and force pushed, please kindly comment if any else missing ;-)

**Comment by tchaikov** [comment]
```
[ RUN      ] TestMockMigrationHttpClient.OpenCloseHttp
unknown file: Failure
C++ exception with description "bind: Address already in use [system:98]" thrown in SetUp().
[  FAILED  ] TestMockMigrationHttpClient.OpenCloseHttp (68 ms)
[ RUN      ] TestMockMigrationHttpClient.OpenCloseHttps
unknown file: Failure
C++ exception with description "bind: Address already in use [system:98]" thrown in SetUp().
[  FAILED  ] TestMockMigrationHttpClient.OpenCloseHttps (68 ms)
[ RUN      ] TestMockMigrationHttpClient.OpenHttpsHandshakeFail
unknown file: Failure
C++ exception with description "bind: Address already in use [system:98]" thrown in SetUp().
[  FAILED  ] TestMockMigrationHttpClient.OpenHttpsHandshakeFail (60 ms)
[ RUN      ] TestMockMigrationHttpClient.OpenInvalidUrl
unknown file: Failure
C++ exception with description "bind: Address already in use [system:98]" thrown in SetUp().
[  FAILED  ] TestMockMigrationHttpClient.OpenInvalidUrl (64 ms)
[ RUN      ] TestMockMigrationHttpClient.OpenResolveFail
unknown file: Failure
C++ exception with description "bind: Address already in use [system:98]" thrown in SetUp().
[  FAILED  ] TestMockMigrationHttpClient.OpenResolveFail (63 ms)
[ RUN      ] TestMockMigrationHttpClient.OpenConnectFail
unknown file: Failure
C++ exception with description "bind: Address already in use [system:98]" thrown in SetUp().
[  FAILED  ] TestMockMigrationHttpClient.OpenConnectFail (70 ms)
[ RUN      ] TestMockMigrationHttpClient.IssueHead
unknown file: Failure
C++ exception with description "bind: Address already in use [system:98]" thrown in SetUp().
[  FAILED  ] TestMockMigrationHttpClient.IssueHead (67 ms)
[ RUN      ] TestMockMigrationHttpClient.IssueGet
unknown file: Failure
C++ exception with description "bind: Address already in use [system:98]" thrown in SetUp().
[  FAILED  ] TestMockMigrationHttpClient.IssueGet (58 ms)
[ RUN      ] TestMockMigrationHttpClient.IssueSendFailed
unknown file: Failure
C++ exception with description "bind: Address already in use [system:98]" thrown in SetUp().
[  FAILED  ] TestMockMigrationHttpClient.IssueSendFailed (60 ms)
[ RUN      ] TestMockMigrationHttpClient.IssueReceiveFailed
unknown file: Failure
C++ exception with description "bind: Address already in use [system:98]" thrown in SetUp().
[  FAILED  ] TestMockMigrationHttpClient.IssueReceiveFailed (68 ms)
[ RUN      ] TestMockMigrationHttpClient.IssueResetFailed
unknown file: Failure
C++ exception with description "bind: Address already in use [system:98]" thrown in SetUp().
[  FAILED  ] TestMockMigrationHttpClient.IssueResetFailed (67 ms)
[ RUN      ] TestMockMigrationHttpClient.IssuePipelined
unknown file: Failure
C++ exception with description "bind: Address already in use [system:98]" thrown in SetUp().
[  FAILED  ] TestMockMigrationHttpClient.IssuePipelined (73 ms)
[ RUN      ] TestMockMigrationHttpClient.IssuePipelinedRestart
unknown file: Failure
C++ exception with description "bind: Address already in use [system:98]" thrown in SetUp().
[  FAILED  ] TestMockMigrationHttpClient.IssuePipelinedRestart (74 ms)
[ RUN      ] TestMockMigrationHttpClient.ShutdownInFlight
unknown file: Failure
C++ exception with description "bind: Address already in use [system:98]" thrown in SetUp().
[  FAILED  ] TestMockMigrationHttpClient.ShutdownInFlight (68 ms)
[ RUN      ] TestMockMigrationHttpClient.GetSize
unknown file: Failure
C++ exception with description "bind: Address already in use [system:98]" thrown in SetUp().
[  FAILED  ] TestMockMigrationHttpClient.GetSize (57 ms)
[ RUN      ] TestMockMigrationHttpClient.GetSizeError
unknown file: Failure
C++ exception with description "bind: Address already in use [system:98]" thrown in SetUp().
[  FAILED  ] TestMockMigrationHttpClient.GetSizeError (62 ms)
[ RUN      ] TestMockMigrationHttpClient.Read
unknown file: Failure
C++ exception with description "bind: Address already in use [system:98]" thrown in SetUp().
[  FAILED  ] TestMockMigrationHttpClient.Read (57 ms)
```

not related to this change. but this test failure has been occurring very often recently.

**Comment by tchaikov** [comment]
jenkins test make check

**Comment by tchaikov** [comment]
```
In file included from /home/jenkins-build/build/workspace/ceph-pull-requests/src/rgw/rgw_sal_motr.cc:29:
In file included from /usr/include/motr/motr/layout.h:28:
In file included from /usr/include/motr/motr/client.h:1875:
/usr/include/motr/cas/cas.h:38:10: fatal error: 'fop/wire.h' file not found
#include "fop/wire.h"           /* m0_fop_mod_rep */
         ^~~~~~~~~~~~
1 error generated.
```

i have to fix the prebuilt motr development package on jammy..

**Comment by tchaikov** [comment]
jenkins test make check

**Comment by tchaikov** [comment]
jenkins test api

**Comment by tchaikov** [comment]
> @tchaikov sorry for my delay, commit message update, rebase with main and force pushed, please kindly comment if any else missing ;-)

no worries. i understand lots things are going on. we just need to iron out the infra issues.

**Review by tchaikov — APPROVED** [review]

**Pull request merged**
