### PR TITLE
cls/rgw: fix rgw list-object-versions key-marker behavior to match s3

### PR DESCRIPTION
**Pull request by samakshd**
The key-marker parameter in the list-object-versions operation is inclusive in RGW, while it's exclusive in S3. This commit updates RGW's behavior to make the key-marker parameter exclusive, ensuring consistent behavior between RGW and S3.

Fixes: https://tracker.ceph.com/issues/68055

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Comment by cbodley** [comment]
thanks @samakshd. we have a lot of test cases for ListObjects and ListObjectVersions in https://github.com/ceph/s3-tests. can you please run those to make sure you haven't broken anything there? you can find instructions in the repo's README

we'll also want to add a new test case for this specific issue, since it wasn't caught before

**Comment by samakshd** [comment]
> thanks @samakshd. we have a lot of test cases for ListObjects and ListObjectVersions in https://github.com/ceph/s3-tests. can you please run those to make sure you haven't broken anything there? you can find instructions in the repo's README
> 
> we'll also want to add a new test case for this specific issue, since it wasn't caught before

Sure, will do that. Although, I see that ceph API tests is failing during CI, is that expected?

**Comment by cbodley** [comment]
> Although, I see that ceph API tests is failing during CI, is that expected?

no worries, 'ceph API tests' and 'make check' can be flaky. we'll get them green when this is ready to merge

**Comment by adamemerson** [comment]
jenkins test api

**Comment by samakshd** [comment]
Hey, I first tried running s3-tests on the main branch itself but it seems around 74 tests failed. Is that expected or it should pass all the tests? In the config file since values are set to default setting of '../src/vstart.sh'. I did not change anything there.

**Comment by samakshd** [comment]
Hi, I have executed the S3-tests on the PR branch using following way:
`$ cd build/
$ RGW=1 ../src/vstart.sh -n
$ ../qa/workunits/rgw/run-s3tests.sh`

Attaching the screenshot of result [
Screenshot 2024-10-04 at 12 23 21 PM
](url)
Screenshot 2024-10-04 at 12 23 45 PM

Please let me know if this is the expected result or not. 
Thanks.

**Comment by cbodley** [comment]
> 1 xfailed

@samakshd i don't think any should fail. can you tell which test case that was? the output should say above the DeprecationWarning stuff

**Comment by samakshd** [comment]
> > 1 xfailed
> 
> @samakshd i don't think any should fail. can you tell which test case that was? the output should say above the DeprecationWarning stuff

Here is the corresponding log

`s3tests/functional/test_s3_website.py::test_routing_generator XFAIL ([NOTRUN] yield tests were removed in pytest 4.0 - test_routing_generator will be ignored)`

**Comment by samakshd** [comment]
It's giving same error on main branch also though @cbodley

**Comment by samakshd** [comment]
Hi @cbodley, I have added the corresponding test as you asked. I have tested it by building both main and my PR branch. It is giving expected results. Please let me know if any changes are required or any other tests have to be added. Thanks.

s3-tests PR: https://github.com/ceph/s3-tests/pull/594

**Comment by samakshd** [comment]
@cbodley I have created another PR with backup branch, in case the mess I created in this one is irreversible. Extremely sorry for creating such mess, didn't know that merge or rebase is not required after each commit, I thought since the main branch would have got stale, hence thought to do that. 

Link for alt PR: https://github.com/ceph/ceph/pull/60280

Thanks.

**Comment by cbodley** [comment]
> @cbodley I have created another PR with backup branch, in case the mess I created in this one is irreversible. Extremely sorry for creating such mess, didn't know that merge or rebase is not required after each commit, I thought since the main branch would have got stale, it would be better to rebase/merge the main and then push the commit.
> 
> Link for alt PR: #60280

thanks, closing this one

**Pull request closed without merging**
