### PR TITLE
Wip 8635 -- Move scrub, snap_trim into a unified queue

### PR DESCRIPTION
**Pull request by athanatos**

### CODE REVIEW

**Comment by athanatos** [comment]
Passed a couple of rados suite subsets -- ready for review and merge.

**Comment by tchaikov** [comment]
looks good other than some minor suggestions.

**Comment by athanatos** [comment]
Actually, can't make them const since I use PGQueueuable::operator=

**Comment by athanatos** [comment]
Added an is_locked() assert to requeue_scrub, retesting.

**Pull request merged**
