### PR TITLE
rgw: drop asio/{yield,coroutine}.hpp replacements

### PR DESCRIPTION
**Pull request by tchaikov**
as we requires boost 1.61+ now, which offers them. see
http://www.boost.org/doc/libs/1_61_0/boost/asio/.

Signed-off-by: Kefu Chai <kchai@redhat.com>

### CODE REVIEW

**Comment by tchaikov** [comment]
retest this please.

**Comment by cbodley** [comment]
thanks @tchaikov, agreed that they can go. we'll need to fix up the #includes too

**Comment by tchaikov** [comment]
@cbodley sorry, i forget to "git add" them!

**Comment by tchaikov** [comment]
@cbodley fixed and repushed.

**Comment by tchaikov** [comment]
@cbodley seems the `fork` and `yield` collide with other names in boost and libc, and it takes longer than i expected to figure out why and how to fix it. will continue the adventure tomorrow.

**Comment by cbodley** [comment]
@tchaikov yeah, that's messy. there's a `<boost/asio/unyield.hpp>` you can include to `#undef` those where necessary

**Comment by tchaikov** [comment]
@cbodley fixed! we just need to include the asio headers after those who define/use `fork` or `yield`, so they don't panic at seeing these macros.

**Comment by tchaikov** [comment]
changelog

- rebased against master to resolve the conflict of `rgw_data_sync.cc`

**Comment by tchaikov** [comment]
retest this please.

**Comment by tchaikov** [comment]
@cbodley is this PR ready to merge ? i think most of failures in http://pulpito.ceph.com/cbodley-2017-06-05_13:55:57-rgw-wip-cbodley-testing-distro-basic-mira/ is not relevant to this change.

**Pull request merged**
