### PR TITLE
cleanup code for wbthrottle.

### PR DESCRIPTION
**Pull request by majianpeng**

### CODE REVIEW

**Comment by athanatos** [comment]
Added a comment, you can re-add needs-qa once it is addressed or responded to.

**Comment by liewegas** [comment]
@athanatos ping

**Comment by athanatos** [comment]
@majianpeng 

I'm adding this to wip-sam-testing.  majianpeng: you should still work on getting access to the sepia lab and learning to run tests prior to posting PRs.  I'm trying to be less of a bottleneck on this process.

**Comment by athanatos** [comment]
Also, do not name your local branches "bug-fix".  Please use descriptive branch names.  In this case, wip-wbthrrotle-signal, perhaps.

**Pull request merged**
