### PR TITLE
hammer: docs: Bucket object versions

### PR DESCRIPTION
**Pull request by odivlad**
Fixes: http://tracker.ceph.com/issues/16574

### CODE REVIEW

**Comment by dachary** [comment]
@odivlad would you please **git cherry-pick -x** the commits so that there is a reference of the master commit in the message ?

**Comment by odivlad** [comment]
@dachary, sorry about that. I've fixed it.

**Comment by smithfarm** [comment]
@oritwas Please review?

**Comment by oritwas** [comment]
lgtm

**Pull request merged**
