### PR TITLE
pacific: mgr/dashboard: Update Angular version to 12

### PR DESCRIPTION
**Pull request by alfonsomthd**
backport tracker: https://tracker.ceph.com/issues/53834
backport tracker: https://tracker.ceph.com/issues/53922

---

backport of https://github.com/ceph/ceph/pull/43404, #44578
parent tracker: https://tracker.ceph.com/issues/53049
parent tracker: https://tracker.ceph.com/issues/53843

this backport was staged using ceph-backport.sh version 16.0.0.6848
find the latest version at https://github.com/ceph/ceph/blob/master/src/script/ceph-backport.sh

### CODE REVIEW

**Comment by alfonsomthd** [comment]
jenkins test dashboard

**Comment by alfonsomthd** [comment]
jenkins test dashboard cephadm

**Review by epuertat — APPROVED** [review]

**Comment by nizamial09** [comment]
jenkins test dashboard

**Review by nizamial09 — APPROVED** [review]
LGTM! Thank you @alfonsomthd

**Review by Waadkh7 — APPROVED** [review]

**Comment by alfonsomthd** [comment]
jenkins test dashboard cephadm

**Comment by nizamial09** [comment]
QA run scheduled: http://pulpito.front.sepia.ceph.com/nizamial09-2022-01-20_13:00:56-rados:dashboard-wip-nizamial09-testing-2022-01-20-1223-pacific-distro-default-smithi/

**Pull request merged**
