### PR TITLE
[RFC] Task: Implementing MemPool Monitoring for Ceph Tests

### PR DESCRIPTION
**Pull request by NitzanMordhai**
Objective: The goal is to enhance the test framework by introducing a new subtask that monitors mempools. This subtask will periodically dump mempool data and compare it to the previous dump, generating warning messages in the Teuthology logs if the observed differences exceed the specified memory_max_diff threshold. Additionally, the subtask will perform checks on the total mempool allocation against the osd_memory_target and raise an error if the total_memory_max_diff threshold is exceeded.

Approach:

 1.   Implement the "watchmempools" subtask within the test framework.
 2.   Configure the subtask to periodically collect and analyze memory usage data from the mempools.
 3.   Compare the current mempool data with the previous dump to identify any significant differences.
 4.   Generate warning messages in the Teuthology logs if the observed differences exceed the memory_max_diff threshold.
 5.   Perform checks on the total mempool allocation against the osd_memory_target.
 6.   Raise an error if the total_memory_max_diff threshold is exceeded.
 7.   Continuously monitor the mempools until all relevant OSDs have been processed.
 8.   Log the completion of the mempool monitoring task in the Teuthology logs.

By implementing this mempool monitoring mechanism, we aim to enhance the test framework's ability to detect and report deviations in mempool usage, ensuring better control and visibility over memory utilization during Ceph tests.

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [x] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by NitzanMordhai** [comment]
jenkins test make check

**Comment by NitzanMordhai** [comment]
jenkins test make check

**Comment by NitzanMordhai** [comment]
jenkins test api

**Comment by neha-ojha** [comment]
Relevant dev list thread: https://lists.ceph.io/hyperkitty/list/dev@ceph.io/thread/SXZDCAWCB2B5IAE6CY65KGTM3PSEZ7S2/
@ra

**Comment by neha-ojha** [comment]
@NitzanMordhai can you share a link to a teuthology run you've done with this PR?

**Comment by NitzanMordhai** [comment]
@neha-ojha , here are a few runs with `watchmempool`: [link to the runs](http://pulpito.front.sepia.ceph.com/nmordech-2023-06-25_05:11:03-rados:objectstore-main-distro-default-smithi/)

In the logs, you can observe that `watchmempool` was successfully started:
`tasks.watchmempools.mempools_watch:watchmempools starting`

It collects the mempool output for each OSD, as shown in the logs:
`tasks.watchmempools.mempools_watch:watchmempools: collecting memory usage for osd.0`

During the collection, `watchmempool` compares the current memory usage with the previous interval and outputs a warning or error if the memory usage has increased by a certain percentage. For example:
`tasks.watchmempools.mempools_watch:watchmempools warning: osd.0 pool osdmap memory usage changed by 57.36% since last interval`

`watchmempool` will only terminate if the memory usage exceeds the target memory plus the specified percentage. Here's an example of such an output:
`tasks.watchmempools.mempools_watch:watchmempools: osd.0 memory usage: 3249608 target 4294967296`

**Comment by NitzanMordhai** [comment]
Rebase it, and waiting for comments.

**Pull request closed without merging**
