### PR TITLE
luminous: cmake: check bootstrap.sh instead before downloading boost

### PR DESCRIPTION
**Pull request by cbodley**
luminous backport for http://tracker.ceph.com/issues/23072

### CODE REVIEW

**Comment by cbodley** [comment]
this was causing issues for fedora builds which failed to re-fetch boost due to firewall

**Comment by smithfarm** [comment]
Do we need to roll out a quick 12.2.4 for this?

**Comment by smithfarm** [comment]
Pedantic note: the other commit from https://github.com/ceph/ceph/pull/19124 was already backported to luminous in https://github.com/ceph/ceph/pull/19721

**Comment by tchaikov** [comment]
@smithfarm yeah. would be ideal if we can have this change, as without it, our end-user will need to download boost even if they are compiling from the dist tarball released by us.

**Comment by yuriw** [comment]
[wip-yuri4-testing-2018-02-23-1643-luminous](https://trello.com/c/S6IhW1FM/268-wip-yuri4-testing-2018-02-23-1643-luminous)

**Pull request merged**
