### PR TITLE
mgr/dashboard: snapshot schedule repeat frequency validation

### PR DESCRIPTION
**Pull request by ivoalmeida**
Fixed snap schedule repeat frequency validation

Fixes: https://tracker.ceph.com/issues/64980

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [x] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

[Screencast from 2024-03-19 12-49-22.webm](https://github.com/ceph/ceph/assets/1071297/70b07b64-1180-4ca2-9bb6-e06216d716a7)

### CODE REVIEW

**Review by nizamial09 — COMMENTED** [review]
Works mostly. 

If I initially add the a path that has a frequency it shows validation error as expected. But the I removed and added a path that doesn't have any snap_schedules and the error was still there until I click the Create button (which force me to click Create twice to do the creation). 

https://github.com/ceph/ceph/assets/71764184/49be0058-84cc-4eac-ab76-8f56ebe59a93

**Comment by ivoalmeida** [comment]
> Works mostly.
> 
> If I initially add the a path that has a frequency it shows validation error as expected. But the I removed and added a path that doesn't have any snap_schedules and the error was still there until I click the Create button (which force me to click Create twice to do the creation).
> 
>  scrnli_3_22_2024_12-07-49.PM.mp4
@nizamial09 

I made a change that will trigger a new validation when the value of the directory input field changes. PTAL

**Comment by cloudbehl** [comment]
jenkins test make check

**Comment by cloudbehl** [comment]
@vshankar As we are able to create schedule with same path and same frequency from CLI, what are the usecases we are targeting and should UI allow or block this scenario?

**Comment by mchangir** [comment]
> @vshankar As we are able to create schedule with same path and same frequency from CLI, what are the usecases we are targeting and should UI allow or block this scenario?

Yes, duplicate schedules are allowed. I don't foresee any specific usecase for this. This should obviously be used with care, because if you mistakenly add a duplicate schedule and then delete it, the original schedule also gets deleted since there's no way to tell which one was the original and which one was the duplicate. So, all the schedules with the same (path, frequency) combo get deleted on a remove operation.

**Comment by cloudbehl** [comment]
Thanks @mchangir for the response. If we don't have specific usecase for now. I will disable this functionality with a validation in place. So its less confusing for a user. Thanks

**Comment by cloudbehl** [comment]
jenkins test make check

**Comment by mchangir** [comment]
@ivoalmeida I just wanted to emphasize that this issue is not just associated with subvolumes. You can add multiple schedules with the same frequency for any other dir path as well.

The TypeScript is a bit hard on my eyes. Kindly excuse me if this has already been taken care of.

**Comment by ivoalmeida** [comment]
jenkins test make check

**Review by Pegonzal — APPROVED** [review]
Since validation has been added, and no duplicate snap schedules can be created, only one is selected at a time, which fixes the issue

**Pull request merged**
