### PR TITLE
nautilus: qa/tasks/ceph_manager: increase CLI command timeout

### PR DESCRIPTION
**Pull request by liewegas**
https://tracker.ceph.com/issues/43914

### CODE REVIEW

**Comment by liewegas** [comment]
retest this please

**Comment by liewegas** [comment]
retest this please

**Comment by yuriw** [comment]
http://pulpito.front.sepia.ceph.com:80/yuriw-2020-02-27_19:20:22-upgrade:mimic-x:stress-split-nautilus-distro-basic-smithi/

**Comment by yuriw** [comment]
retest this please

**Comment by yuriw** [comment]
retest this please

**Comment by liewegas** [comment]
@neha-ojha updated to 900s

**Comment by smithfarm** [comment]
jenkins test make check

**Pull request merged**
