### PR TITLE
remove rdma_local and changes to xio connection

### PR DESCRIPTION
**Pull request by vsjulu**
1. Isolate the frequently accessed atomic variable 'connected' on a separate cache line
2.  Return error (from xio bind method) if the cluster/public ip is not provided for each OSD separately and remove rdma local from xio bind method. This applies to XIO/RDMA messenger only. This change avoids any problems created by using rdma_local in the conf file while trying to use different IP addresses for different OSDs. 

1. src/msg/xio/XioConnection.h  
2. src/msg/xio/XioMessenger.cc

### CODE REVIEW

**Comment by yuyuyu101** [comment]
need rebase with a clean pr

**Comment by mattbenjamin** [comment]
I ack both changes, but think we should at least remove the conditional code, so please explain that.  We could move to c++11 syntax later, if it's not trivial to do now.

**Comment by vsjulu** [comment]
Thanks for reviewing.  I have made the change to remove the conditional compile. It was originally just added in case people wanted it to be a config option.  Now, it will just be compiled in all cases.

**Comment by vsjulu** [comment]
Signed-off-by: Subramanyam Varanasi s.varanasi@ssi.samsung.com

**Comment by liewegas** [comment]
@vsjulu please put the Signed-off-by line in teh commit message itself (not the pull request). Also, can you git rebase on to of master to get rid of the merge commits? Thanks!

**Comment by mattbenjamin** [comment]
@vsjulu is this commit still active?

**Comment by tchaikov** [comment]
@mattbenjamin guess it's superseded by #7664.

**Comment by vsjulu** [comment]
@mattbenjamin  -  I will close this pull request. I will have to close the other one also and submit two different pull requests for the two changes.

**Comment by tchaikov** [comment]
@vsjulu sorry, i meant two commits, one for the atomic padding, the other for the rdma_local removal.

**Comment by vsjulu** [comment]
Closing this pull request as there is a new one now.

**Pull request closed without merging**
