### PR TITLE
qa/tasks/ceph_deploy: use dev option instead of dev-commit

### PR DESCRIPTION
**Pull request by vasukulkarni**
Signed-off-by: Vasu Kulkarni <vasu@redhat.com>

### CODE REVIEW

**Comment by liewegas** [comment]
@vasukulkarni What is this for?  I seem to remember the dev-commit being needed for a reason (upgrade tests maybe?) but I can't remember.

**Comment by vasukulkarni** [comment]
@liewegas sorry i should have added tracker, http://tracker.ceph.com/issues/18253 , This is for ceph-deploy suite to work with shaman and will not affect upgrade tests, 

Assigning to @alfredodeza

**Comment by vasukulkarni** [comment]
@alfredodeza http://tracker.ceph.com/issues/18294

**Comment by alfredodeza** [comment]
note that before these options where mutually exclusive. Now they aren't, because with the new system, when you specify a SHA1, you must point to the branch too because they are built tied to branches.

It isn't possible to specify just a SHA1 (which this PR addresses)

**Pull request merged**
