### PR TITLE
mgr/cephadm: use host address while updating rgw zone endpoints

### PR DESCRIPTION
**Pull request by aaSharma14**
During Import zone endpoint automatically fetches hostname instead of ip resulting in sync error. This PR is to fix this issue

Fixes: https://tracker.ceph.com/issues/68027

Signed-off-by: Aashish Sharma <aasharma@redhat.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Review by adk3798 — APPROVED** [review]

**Comment by aaSharma14** [comment]
jenkins test api

**Comment by aaSharma14** [comment]
jenkins test api

**Comment by aaSharma14** [comment]
jenkins test make check

**Comment by aaSharma14** [comment]
jenkins test make check

**Comment by aaSharma14** [comment]
@adk3798 , can we merge this if the test run looks good?

**Comment by adk3798** [comment]
> @adk3798 , can we merge this if the test run looks good?

I haven't done a run yet, sorry. I'll schedule one today.

**Comment by adk3798** [comment]
https://pulpito.ceph.com/adking-2024-09-21_16:57:11-orch:cephadm-wip-adk-testing-2024-09-21-1014-distro-default-smithi/

Failures:
- 6x mds_upgrade_sequence timeouts, known issue
- 3x SELinux denials + stray daemon warnings, known issue
- 2x rgw-ingress timeout, known issue
- test_nfs task failed due to PR in the run
- staggered upgrade with agent enabled failed, known issue
- stray daemon warning in rados_python task (not a big issue, needs an ignorelist entry)

Nothing to block merging outside of the PR causing the test_nfs task failure

**Comment by aaSharma14** [comment]
Merging this as it has approvals and the required tests are passing now.

**Pull request merged**
