### PR TITLE
common: default pg_autoscale_mode=on for new pools

### PR DESCRIPTION
**Pull request by liewegas**
take 2

### CODE REVIEW

**Comment by jtlayton** [comment]
Seems like the right thing to do.

Note that many of examples in the docs have `ceph osd pool create` specify a (seemingly magic) pg_num value. It to follow up with making the `pg_num` argument to that command be optional, and start removing those settings from the docs.

**Comment by xiexingguo** [comment]
IMHO, if we are going to default pg_autoscale_mode on for new pools, then perhaps we should allow user to create a pool without specifying pg_num...

**Comment by liewegas** [comment]
YES!  I will add patches to do that.

**Comment by liewegas** [comment]
@neha-ojha see f9c683e

**Comment by tchaikov** [comment]
@liewegas @xiexingguo this change breaks "make check". i'd suggest double check the reason why "make check" fails before approving a PR or merging it.

**Comment by xiexingguo** [comment]
@tchaikov I re-edited the branch protection rule to enforce all configured restrictions (including make check) for administrators, so it would be impossible to merge a pr if make check is failing now.

It must be someone who have temporarily disabled that option, e.g., to let an legal submodule update in, and then forgot to restore...

**Comment by wjwithagen** [comment]
@tchaikov 

`make check` probably fails in `test_ceph_argparse.py`:
```
160: FAIL: test_ceph_argparse.TestOSD.test_pool_create
160: ----------------------------------------------------------------------
160: Traceback (most recent call last):
160:   File "/usr/local/lib/python3.6/site-packages/nose/case.py", line 197, in runTest
160:     self.test(*self.arg)
160:   File "/home/jenkins/workspace/ceph-master/src/test/pybind/test_ceph_argparse.py", line 1071, in test_pool_create
160:     'poolname']))
160: AssertionError: {} != {'prefix': 'osd pool create', 'pool': 'poolname'}
160: - {}
160: + {'pool': 'poolname', 'prefix': 'osd pool create'}
160:
160: ----------------------------------------------------------------------
```

**Comment by tchaikov** [comment]
@wjwithagen should have been fixed by #30535 .

**Pull request merged**
