### PR TITLE
doc: updated multisite documentation

### PR DESCRIPTION
**Pull request by falcon78921**
- [x] References tracker ticket
- [x] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

The federated architecture link was broken on doc/install/manual-deployment (404). I didn't see any federated-config documentation in the master branch. The federated-config docs, however, exist in Jewel. When reading the Multisite docs, I noticed the content was very similar to the federated architecture.

Fixes: http://tracker.ceph.com/issues/26997

Signed-off-by: James McClune jmcclune@mcclunetechnologies.net

### CODE REVIEW

**Comment by falcon78921** [comment]
jenkins render docs

**Comment by smithfarm** [comment]
It would be nice if the `Fixes: http://tracker.ceph.com/issues/26997` line could be in one or more (all?) of the commits. Having it in the PR description is fine for those looking at the PR, but the git history is what really counts IMO.

**Comment by falcon78921** [comment]
Thanks @smithfarm. I'll fix the commits now.

**Comment by falcon78921** [comment]
@smithfarm Done :)

**Comment by falcon78921** [comment]
@cbodley I'm just following up on this pull request. If there's something I need to correct, please let me know.

**Comment by cbodley** [comment]
thanks!

**Pull request merged**
