### PR TITLE
mgr/dashboard: enforce absolute imports in UI

### PR DESCRIPTION
**Pull request by epuertat**
Fixes: https://tracker.ceph.com/issues/48213
Signed-off-by: Ernesto Puerta <epuertat@redhat.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by aaSharma14** [comment]
jenkins test make check

**Comment by aaSharma14** [comment]
jenkins test make check

**Comment by s0nea** [comment]
jenkins test make check

**Review by Devp00l — APPROVED** [review]

**Review by nizamial09 — APPROVED** [review]

**Comment by callithea** [comment]
jenkins test make check

**Comment by nizamial09** [comment]
jenkins test make check

**Comment by alfonsomthd** [comment]
jenkins test make check

**Pull request closed without merging**
