### PR TITLE
DNM: Possible crash while concurrently writing and shrinking an image

### PR DESCRIPTION
**Pull request by theanalyst**
http://tracker.ceph.com/issues/12236

### CODE REVIEW

**Comment by dachary** [comment]
@theanalyst could you please rebase & repush ? I suspect this does not actually build but the make check bot was apparently taking a nap when that was first submitted ;-)

**Comment by theanalyst** [comment]
@dachary pushed

**Comment by dachary** [comment]
@theanalyst the bot failed
<pre>
librbd/AsyncRequest.cc: In member function 'Context* librbd::AsyncRequest::create_async_callback_context()':
librbd/AsyncRequest.cc:34:43: error: 'async_complete' is not a member of 'librbd::AsyncRequest'
   return new FunctionContext(boost::bind(&AsyncRequest::async_complete, this,
                                           ^
librbd/AsyncRequest.cc:36:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
make[3]: *** [librbd/AsyncRequest.lo] Error 1
</pre>

**Comment by theanalyst** [comment]
This may require 218bc2d0f8d90c9c64408cb22e26680e88138844 which was a part of a larger pull request in master.. It is better @dillaman does this backport.. assigning to @dillaman

**Comment by dillaman** [comment]
@theanalyst I believe this one will be dependent upon http://tracker.ceph.com/issues/12384 (PR #5280) and http://tracker.ceph.com/issues/12345 (in-progress) at the minimum.

**Comment by theanalyst** [comment]
@dillaman thanks!

**Comment by dillaman** [comment]
New PR #5318 tracks merge request from new branch.

**Pull request closed without merging**
