### PR TITLE
rgw: multisite data log flag not used

### PR DESCRIPTION
**Pull request by ivancich**
A flag controlling multisite data logging passed to RGWRados::bucket_index_link_olh was ignored.

Fixes: https://tracker.ceph.com/issues/61198

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by cbodley** [comment]
> bring to Casey's attention since he introduced it in commit [b5ecc4e](https://github.com/ceph/ceph/commit/b5ecc4eaaaaa4f9950ad934a015255171abeb01e) .

thanks Eric, i've refreshed my memory on that commit. the `bool log_data_change` flag was added to control whether we write an entry to the *datalog*, not to the bilog

`bool log_data_change` was a special case for `fetch_remote_obj()`, because it's just calling `set_olh()` there without the rest of the bucket index transaction, so nothing would write its datalog entry otherwise

that `bool log_data_change` flag is currently unused, but it *should* cover the call to `add_datalog_entry()` below

**Review by cbodley — APPROVED** [review]

**Comment by ivancich** [comment]
jenkins test make check

**Comment by ivancich** [comment]
jenkins test make check

**Comment by cbodley** [comment]
passed qa after rerun https://pulpito.ceph.com/cbodley-2023-05-25_13:09:32-rgw-wip-cbodley-testing-distro-default-smithi/

**Pull request merged**
