### PR TITLE
osdc/Striper.cc fix stripe_count == 1 && stripe_unit != object_size

### PR DESCRIPTION
**Pull request by ukernel**
Fixes:11120
Signed-off-by: Yan, Zheng <zyan@redhat.com>

### CODE REVIEW

**Comment by jcsp** [comment]
I think we should reject this case in ceph_file_layout_is_valid, so that we give the user feedback that they are doing something crazy.

**Comment by ukernel** [comment]
the problem is that, when using vxattr, we can update one field at a time. Rejecting this case will make the vxattr interface very hard to use.

**Comment by liewegas** [comment]
Given that most people will be moving from/to a stripe_count of 1 i think @ukernel 's approach makes sense

**Comment by gregsfortytwo** [comment]
Hmm. I'm not comfortable doing constant online translation of the file stripes:
* What happens if an older client gets mounted with the file? (How does the current kernel client behave?)
* What happens if we want to change this behavior in the future, and a bunch of stuff is deployed with nonsensical units?

I agree we shouldn't prevent users from setting the vxattrs one at a time, which means we need to let the values be nonsensical in that intermediate stage. But I think we *can* prevent them from opening a file until its layout makes sense...try that?

**Comment by liewegas** [comment]
Hmm, verifying on open might work.  Note that you can also set multiple 
fields at teh same time by setting ceph.layout = "stripe_unit=1234 
stripe_count=345" instead of the individual fields.  It makes it a bit 
more awkard to use the interface but it does work... :/  Maybe that's 
the simplest.

**Comment by ukernel** [comment]
On Tue, Mar 31, 2015 at 7:08 AM, Gregory Farnum <notifications@github.com>
wrote:

> Hmm. I'm not comfortable doing constant online translation of the file
> stripes:
>
>    - What happens if an older client gets mounted with the file? (How
>    does the current kernel client behave?)
>    - What happens if we want to change this behavior in the future, and a
>    bunch of stuff is deployed with nonsensical units?
>
> I agree we shouldn't prevent users from setting the vxattrs one at a time,
> which means we need to let the values be nonsensical in that intermediate
> stage. But I think we *can* prevent them from opening a file until its
> layout makes sense...try that?
>
>
I don't like the allowing intermediate states and verifying on open approach.
Client can opens the file first, then use fsetaxattr() to change file's
layout.  Yes, we can make MDS not issue Frw caps to clients when file has
bogus layout. But I don't like to add check for this rare case to the
issuing caps code either. As sage said, maybe disable setting single vxattr
is the simplest approach.

Reply to this email directly or view it on GitHub
<https://github.com/ceph/ceph/pull/4211#issuecomment-87872322>.

>

**Comment by gregsfortytwo** [comment]
On Mon, Mar 30, 2015 at 6:25 PM, Yan, Zheng <notifications@github.com> wrote:
>
> On Tue, Mar 31, 2015 at 7:08 AM, Gregory Farnum <notifications@github.com>
> wrote:
>
> > Hmm. I'm not comfortable doing constant online translation of the file
> > stripes:
> >
> > - What happens if an older client gets mounted with the file? (How
> > does the current kernel client behave?)
> > - What happens if we want to change this behavior in the future, and a
> > bunch of stuff is deployed with nonsensical units?
> >
> > I agree we shouldn't prevent users from setting the vxattrs one at a time,
> > which means we need to let the values be nonsensical in that intermediate
> > stage. But I think we *can* prevent them from opening a file until its
> > layout makes sense...try that?
> >
> >
> I don't like the allowing intermediate states and verifying on open approach.
> Client can opens the file first, then use fsetaxattr() to change file's
> layout. Yes, we can make MDS not issue Frw caps to clients when file has
> bogus layout. But I don't like to add check for this rare case to the
> issuing caps code either. As sage said, maybe disable setting single vxattr
> is the simplest approach.

Yeah, only allowing the full layout setting is definitely the easiest,
although it's not my favorite either due to the oddities of entering
it (they have to be newline separated or something?).
Nor is checking for this in the cap-issuing code. Is the exposed
failure we have really restricted to only a stripe unit smaller than
the object size, and if so is it really so difficult to fix that?

**Comment by ukernel** [comment]
On Tue, Mar 31, 2015 at 12:40 PM, Gregory Farnum <notifications@github.com>
wrote:

> On Mon, Mar 30, 2015 at 6:25 PM, Yan, Zheng <notifications@github.com>
> wrote:
> >
> > On Tue, Mar 31, 2015 at 7:08 AM, Gregory Farnum <
> notifications@github.com>
> > wrote:
> >
> > > Hmm. I'm not comfortable doing constant online translation of the file
> > > stripes:
> > >
> > > - What happens if an older client gets mounted with the file? (How
> > > does the current kernel client behave?)
> > > - What happens if we want to change this behavior in the future, and a
> > > bunch of stuff is deployed with nonsensical units?
> > >
> > > I agree we shouldn't prevent users from setting the vxattrs one at a
> time,
> > > which means we need to let the values be nonsensical in that
> intermediate
> > > stage. But I think we *can* prevent them from opening a file until its
> > > layout makes sense...try that?
> > >
> > >
> > I don't like the allowing intermediate states and verifying on open
> approach.
> > Client can opens the file first, then use fsetaxattr() to change file's
> > layout. Yes, we can make MDS not issue Frw caps to clients when file has
> > bogus layout. But I don't like to add check for this rare case to the
> > issuing caps code either. As sage said, maybe disable setting single
> vxattr
> > is the simplest approach.
>
> Yeah, only allowing the full layout setting is definitely the easiest,
> although it's not my favorite either due to the oddities of entering
> it (they have to be newline separated or something?).
> Nor is checking for this in the cap-issuing code. Is the exposed
> failure we have really restricted to only a stripe unit smaller than
> the object size, and if so is it really so difficult to fix that?


difficult to fix what ? The crash is in objectcacher, we make it tolerate
this special case. but it requires more code modification.  I can't see any
benefit to do that.

**Comment by gregsfortytwo** [comment]
Never mind, I was just confused.

**Pull request merged**
