### PR TITLE
qa/rgw: add new rgw/website suite for static website tests

### PR DESCRIPTION
**Pull request by cbodley**
resurrecting https://github.com/ceph/ceph/pull/20570, which was broken when we added ssl support (we would need to generate wildcard ssl certificates to match the *.s3. and *.s3website. subdomains). i worked around this limitation by moving these static website tests into a new rgw/website suite which doesn't include https.yaml

### CODE REVIEW

**Comment by cbodley** [comment]
passed a full suite in http://pulpito.ceph.com/cbodley-2019-09-13_13:15:40-rgw-wip-cbodley-testing-distro-basic-smithi/

**Comment by cbodley** [comment]
cc @robbat2

**Comment by robbat2** [comment]
visually looks good, if it passes ship it.

**Comment by cbodley** [comment]
smoke tested in http://qa-proxy.ceph.com/teuthology/cbodley-2019-09-17_12:26:12-rgw:website-wip-rgw-dns-name-iends-with-distro-basic-smithi/4314892/teuthology.log after rebase, still passing. thanks for review!

**Pull request merged**
