### PR TITLE
ceph-volume:  increase the default CEPH_VOLUME_SYSTEMD_TRIES to 2000

### PR DESCRIPTION
**Pull request by taodd**
Fixes: https://tracker.ceph.com/issues/43187

Signed-off-by: dongdong tao <dongdong.tao@canonical.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by jan--f** [comment]
@alfredodeza The systemd unit sets a timeout of 10000s so it I agree that it is weird that other timeouts trigger earlier.
Though it might make more sense to change the systemd_tries variable in the systemd unit.

**Comment by alfredodeza** [comment]
The reason these values are environment variables is because we explicitly did not want to hard code them and allow different environments to set what they think is reasonable. I don't think we should change these values in ceph-volume at all.

**Comment by taodd** [comment]
@alfredodeza I understand user can always set this value through environment variable. 
this patch is trying to change the default value to match  CEPH_VOLUME_TIMEOUT which is already 10000 seconds. 
Below is a section of the ceph-volume's systemd file:
---
Environment=CEPH_VOLUME_TIMEOUT=10000
ExecStart=/bin/sh c 'timeout $CEPH_VOLUME_TIMEOUT /usr/sbin/ceph-volume-systemd %i'
---
Based on this, user most likely will get an assumption that ceph-volume will by default try 10000 seconds before it gives up. 
But it's not true, since ceph-volume-systemd by default will give up after 300 seconds, Hence it will make ceph-volume quit after 300 seconds.

**Comment by alfredodeza** [comment]
> @alfredodeza I understand user can always set this value through environment variable.
> this patch is trying to change the default value to match CEPH_VOLUME_TIMEOUT which is already 10000 seconds.
> Below is a section of the ceph-volume's systemd file:
> 
> ```
> Environment=CEPH_VOLUME_TIMEOUT=10000
> ExecStart=/bin/sh c 'timeout $CEPH_VOLUME_TIMEOUT /usr/sbin/ceph-volume-systemd %i'
> ```
> 
> Based on this, user most likely will get an assumption that ceph-volume will by default try 10000 seconds before it gives up.

A user shouldn't be assuming things like that because that is not what is happening here. On extremely dense systems, the activation for a single OSD can take a while. The `timeout` value here is to ensure that after all those seconds the operation will get killed.

> But it's not true, since ceph-volume-systemd by default will give up after 300 seconds, Hence it will make ceph-volume quit after 300 seconds.

No. In that case, you are assuming that the execution of the activation is taking 0 seconds and failing immediately - which *can* happen, and indeed the tool will internally stop at 300 seconds. If ceph-volume is taking 10 seconds every try, then things are way more different, and the 300 seconds no longer apply.

**Comment by taodd** [comment]
> > @alfredodeza I understand user can always set this value through environment variable.
> > this patch is trying to change the default value to match CEPH_VOLUME_TIMEOUT which is already 10000 seconds.
> > Below is a section of the ceph-volume's systemd file:
> > ```
> > Environment=CEPH_VOLUME_TIMEOUT=10000
> > ExecStart=/bin/sh c 'timeout $CEPH_VOLUME_TIMEOUT /usr/sbin/ceph-volume-systemd %i'
> > ```
> > 
> > 
> > Based on this, user most likely will get an assumption that ceph-volume will by default try 10000 seconds before it gives up.
> 
> A user shouldn't be assuming things like that because that is not what is happening here. On extremely dense systems, the activation for a single OSD can take a while. The `timeout` value here is to ensure that after all those seconds the operation will get killed.
> 
> > But it's not true, since ceph-volume-systemd by default will give up after 300 seconds, Hence it will make ceph-volume quit after 300 seconds.
> 
> No. In that case, you are assuming that the execution of the activation is taking 0 seconds and failing immediately - which _can_ happen, and indeed the tool will internally stop at 300 seconds. If ceph-volume is taking 10 seconds every try, then things are way more different, and the 300 seconds no longer apply.

**Pull request closed without merging**
