### PR TITLE
RGW: bucket notification - hide auto generated topics when listing topics

### PR DESCRIPTION
**Pull request by AliMasarweh**
RGW: bucket notification - hide auto generated topics when listing topics
https://tracker.ceph.com/issues/50412

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by yuvalif** [comment]
jenkins test make check

**Comment by yuvalif** [comment]
can you please run the bucket notification suite locally against a vstart cluster (before going through teuthology).
instruction are here: https://github.com/ceph/ceph/tree/main/src/test/rgw/bucket_notification
note that you dont need to setup amqp and kafka test, idea is to make sure that in the tests we don't expect the autogenerated topics. so just run with `-a 'basic_test`

**Review by yuvalif — APPROVED** [review]

**Comment by yuvalif** [comment]
jenkins test api

**Comment by yuvalif** [comment]
teuthology results: http://pulpito.front.sepia.ceph.com/yuvalif-2023-04-30_13:06:45-rgw:notifications-wip-alimasa-pubsub-hide-autogen-topics-distro-default-smithi/

**Comment by AliMasarweh** [comment]
teuthology result http://pulpito.front.sepia.ceph.com/yuvalif-2023-04-30_13:06:45-rgw:notifications-wip-alimasa-pubsub-hide-autogen-topics-distro-default-smithi/

**Pull request merged**
