### PR TITLE
mgr/dashboard: update cypress to 9.7.0

### PR DESCRIPTION
**Pull request by nizamial09**
While regenerating the npm packages, I've found out that swagger-ui has some issues recently[ due to one of their inner dependency with swagger-client.](https://github.com/swagger-api/swagger-ui/issues/8018). So I had to update its version too. And that basically had some issues again with the jest runner where some of the inner dependencies were not formatted according to the jest compliance, which is ignored using the `transformIgnorePatterns` option in the jest-config.

Fixes: https://tracker.ceph.com/issues/56426
Signed-off-by: Nizamudeen A <nia@redhat.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by nizamial09** [comment]
jenkins test api

**Comment by nizamial09** [comment]
jenkins test dashboard cephadm

**Comment by nizamial09** [comment]
jenkins test make check

**Comment by nizamial09** [comment]
https://tracker.ceph.com/issues/56122
```
 Services page
    ✓ should check if rgw service is created
    ✓ should create an mds service (21027ms)
    ✓ should stop a daemon (25949ms)
    ✓ should restart a daemon (11748ms)
    ✓ should redeploy a daemon (31700ms)
    1) should start a daemon
    ✓ should delete an mds service (15612ms)
    ✓ should create and delete snmp-gateway service with version V2c (27680ms)
    ✓ should create and delete snmp-gateway service with version V3 (20787ms)
    ✓ should create and delete snmp-gateway service with version V3 and w/o privacy protocol (37674ms)


  9 passing (3m)
  1 failing

  1) Services page
       should start a daemon:
     Error: The following error originated from your application code, not from Cypress.

  > NG0100: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'A few seconds ago'. Current value: 'A minute ago'.. Find more at https://angular.io/errors/NG0100

When Cypress detects uncaught errors originating from your application it will automatically fail the current test.

This behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.
```

**Comment by nizamial09** [comment]
jenkins test dashboard cephadm

**Comment by nizamial09** [comment]
jenkins test make check

**Comment by nizamial09** [comment]
jenkins test windows

**Review by Pegonzal — APPROVED** [review]

**Review by aaSharma14 — APPROVED** [review]

**Pull request merged**
