### PR TITLE
rgw: make sending Content-Length in 204 and 304 responses controllable

### PR DESCRIPTION
**Pull request by rzarzynski**

### CODE REVIEW

**Comment by wido** [comment]
Always nasty to violate RFCs, but understandable. In which situation is this required?

Code looks good to me.

**Comment by rzarzynski** [comment]
@wido: thanks for the review. We need the configurable to pass RefStack due to the following test case:
```
tempest.api.object_storage.test_object_services.ObjectTest.test_delete_object
```
You might also want to take a look on the PR #9188. Anyway, I'm putting the _DNM_ tag. There is a new hope for fixing the issue in Tempest.

**Comment by wido** [comment]
Ok, great! I wouldn't want to encourage people to violate RFCs, they are there for a reason.

Don't mind if this gets merged though.

**Comment by yehudasa** [comment]
@rzarzynski do we still need this?

**Comment by rzarzynski** [comment]
@yehudasa: fortunately no :-) as our [fix in Tempest](https://review.openstack.org/#/c/272062) has been merged. I will push https://github.com/ceph/ceph/pull/10156/commits/93629c07c73e89c16b5969fd3b2ad0f53bda3279 in a separated pull request. Closing this one.

**Comment by rzarzynski** [comment]
@mattbenjamin: I've just pushed a version ported to current `master`. DNM till testing on the morning.

**Comment by rzarzynski** [comment]
@mattbenjamin:

Manual testing:
* For `rgw_print_prohibited_content_length = false` (default):
```
$ curl -i "${publicURL}/cont/obj10" -X DELETE -H "X-Auth-Token: ${token}" 
HTTP/1.1 204 No Content
X-Trans-Id: tx00000000000000000000b-0058a6eb39-1018-default
Content-Type: text/plain; charset=utf-8
Date: Fri, 17 Feb 2017 12:23:21 GMT

```
* For `rgw_print_prohibited_content_length = true`:
```
$ curl -i "${publicURL}/cont/obj10" -X DELETE -H "X-Auth-Token: ${token}" 
HTTP/1.1 204 No Content
X-Trans-Id: tx000000000000000000010-0058a6ea8c-1015-default
Content-Type: text/plain; charset=utf-8
Content-Length: 0
Date: Fri, 17 Feb 2017 12:20:28 GMT

```

However, Tempest has found a regression in `tempest.api.object_storage.test_container_services.ContainerTest.test_list_container_contents_with_end_marker`. However, most likely it is unrelated to the change. I'm working on this.

**Comment by rzarzynski** [comment]
@mattbenjamin: definitely the regression in Tempest is unrelated to the change. Removing the DNM flag.

**Comment by rzarzynski** [comment]
Created a ticket to track the issue: http://tracker.ceph.com/issues/18977.

**Pull request merged**
