### PR TITLE
bluestore/NVMEDevice:  fix compiling and fd leak

### PR DESCRIPTION
**Pull request by xiexingguo**

### CODE REVIEW

**Comment by xiexingguo** [comment]
@yuyuyu101 WOW, I haven't noticed you are in charge of this part now. No offense, I was trying to rebase https://github.com/ceph/ceph/pull/7460 when found this small fixes.  Wish you a very very happy Chinese New Year:-)

**Comment by yuyuyu101** [comment]
tested locally.

**Comment by yuyuyu101** [comment]
I will cherry-pick this PR into my local branch and push later after merge #7503 .

**Comment by xiexingguo** [comment]
Sure, suit yourself and feel free to close this one after that is done:-)

**Pull request merged**
