### PR TITLE
nautilus: os/bluestore: fix huge (>4GB) bluefs reads

### PR DESCRIPTION
**Pull request by ifed01**
Signed-off-by: Igor Fedotov <ifedotov@suse.com>
(cherry picked from commit fe558c4dd12b25b2d523987f22fde5b5898cfb83)

 Conflicts:
 (trivial)	src/os/bluestore/BlueFS.cc
 (trivial)	src/os/bluestore/BlueFS.h
 (trivial)	src/os/bluestore/BlueRocksEnv.cc
 (trivial)	src/test/objectstore/test_bluefs.cc

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by aclamk** [comment]
It is extremely interesting failure.
Copying from make check so it does not get lost:
`
[ RUN      ] BlueFS.very_large_write
2021-02-03 12:53:47.340 7effbaf7b280  1 bdev create path ceph_test_bluefs.tmp.block.31428.5 type kernel
2021-02-03 12:53:47.340 7effbaf7b280  1 bdev(0x561dbba10d00 ceph_test_bluefs.tmp.block.31428.5) open path ceph_test_bluefs.tmp.block.31428.5
2021-02-03 12:53:47.340 7effbaf7b280  1 bdev(0x561dbba10d00 ceph_test_bluefs.tmp.block.31428.5) open size 8589934592 (0x200000000, 8 GiB) block_size 4096 (4 KiB) rotational discard supported
2021-02-03 12:53:47.340 7effbaf7b280  1 bluefs add_block_device bdev 1 path ceph_test_bluefs.tmp.block.31428.5 size 8 GiB
2021-02-03 12:53:47.340 7effbaf7b280  1 bluefs _add_block_extent bdev 1 0x100000~1fff00000 skip 0
2021-02-03 12:53:47.340 7effbaf7b280  1 bluefs mkfs osd_uuid 00000000-0000-0000-0000-000000000000
2021-02-03 12:53:47.340 7effbaf7b280  1 bluefs _init_alloc id 1 alloc_size 0x10000 size 0x200000000
2021-02-03 12:53:47.340 7effbaf7b280  1 bluefs mkfs uuid e0ba5906-f099-4ca7-b034-8923f59d8589
2021-02-03 12:53:47.368 7effbaf7b280  1 bluefs mount
2021-02-03 12:53:47.368 7effbaf7b280  1 bluefs _init_alloc id 1 alloc_size 0x10000 size 0x200000000
tcmalloc: large alloc 3221217280 bytes == 0x561e7c76a000 @  0x7effba8fab6b 0x7effba91a379 0x7effb16bbd30 0x7effb16b2dd5 0x7effb16b2e67 0x7effb16b5e03 0x561db9766387 0x561db96e5170 0x561db96e6371 0x561db96e6e53 0x561db967deb0 0x561db96718e4 0x561db96bcbdb 0x561db96b68cb 0x561db969a108 0x561db969aa3c 0x561db969b0d5 0x561db96a2049 0x561db96bdb47 0x561db96b7857 0x561db96a0c03 0x561db967c66e 0x561db9679f44 0x7effaeda4bf7 0x561db966dc7a
tcmalloc: large alloc 2147459072 bytes == 0x561e7c766000 @  0x7effba8fab6b 0x7effba91a379 0x7effb16bbd30 0x7effb16b2dd5 0x7effb16b2e67 0x7effb16b5e03 0x561db9766387 0x561db96e5170 0x561db96e6371 0x561db96e6e53 0x561db967deb0 0x561db967194e 0x561db96bcbdb 0x561db96b68cb 0x561db969a108 0x561db969aa3c 0x561db969b0d5 0x561db96a2049 0x561db96bdb47 0x561db96b7857 0x561db96a0c03 0x561db967c66e 0x561db9679f44 0x7effaeda4bf7 0x561db966dc7a
read got mismatch at offset 2359284750 r 242
/home/jenkins-build/build/workspace/ceph-pull-requests/src/test/objectstore/test_bluefs.cc:187: Failure
      Expected: 0
To be equal to: r
      Which is: 242
2021-02-03 12:54:25.348 7effbaf7b280  1 bdev(0x561dbba10d00 ceph_test_bluefs.tmp.block.31428.5) close
[  FAILED  ] BlueFS.very_large_write (38268 ms)
`

**Comment by aclamk** [comment]
jenkins make check please

**Comment by aclamk** [comment]
jenkins make check please

**Comment by aclamk** [comment]
jenkins test make check

**Comment by ifed01** [comment]
Closing in favor of https://github.com/ceph/ceph/pull/39698

**Pull request closed without merging**
