### PR TITLE
client: enable fuse_use_invalidate_cb by default

### PR DESCRIPTION
**Pull request by ukernel**
Fixes: http://tracker.ceph.com/issues/15634
Signed-off-by: Yan, Zheng <zyan@redhat.com>

### CODE REVIEW

**Comment by gregsfortytwo** [comment]
So it turns out we haven't been running this in the nightlies at all either. :/ I'm not sure if we should just merge the config change after a quick testing run or if we want to delay setting it until we have a lot of testing time under our belt.

**Comment by ukernel** [comment]
we are in the early days of K release, I think we can have a quick merge

**Comment by jcsp** [comment]
This appears to be causing a crash on unmount:

```
ceph version 10.2.0-1355-g0dafa37 (0dafa374b8abcccd1656a98fac75bafb4d75be89)
 1: (()+0x29b5b2) [0x5583fe4ab5b2]
 2: (()+0x10340) [0x7f900cbf2340]
 3: (Client::get_root_ino()+0x10) [0x5583fe3ae650]
 4: (CephFuse::Handle::make_fake_ino(inodeno_t, snapid_t)+0x175) [0x5583fe3ac335]
 5: (()+0x19c372) [0x5583fe3ac372]
 6: (Client::_async_invalidate(boost::intrusive_ptr<Inode>&, long, long)+0x95) [0x5583fe3daed5]
 7: (Context::complete(int)+0x9) [0x5583fe41e1b9]
 8: (Finisher::finisher_thread_entry()+0x206) [0x5583fe4cf0f6]
 9: (()+0x8182) [0x7f900cbea182]
 10: (clone()+0x6d) [0x7f900b55b47d]
```

http://pulpito.front.sepia.ceph.com/jspray-2016-05-25_19:00:36-fs-wip-jcsp-testing-20160526---basic-mira/215378
http://pulpito.front.sepia.ceph.com/jspray-2016-05-25_19:00:36-fs-wip-jcsp-testing-20160526---basic-mira/215388
http://pulpito.front.sepia.ceph.com/jspray-2016-05-25_19:00:36-fs-wip-jcsp-testing-20160526---basic-mira/215410

**Comment by jcsp** [comment]
@ukernel do you have any ideas about the crash that was seen in testing?

**Comment by jcsp** [comment]
I've created a ticket for the crash separately, as this is presumably something that users could already see if they happened to have enabled fuse_use_invalidate_cb
http://tracker.ceph.com/issues/16137

**Comment by jcsp** [comment]
(this PR now blocked on http://tracker.ceph.com/issues/16137)

**Pull request merged**
