### PR TITLE
pacific: cephfs-mirror backports

### PR DESCRIPTION
**Pull request by vshankar**
https://tracker.ceph.com/issues/50241
backport #40524
https://tracker.ceph.com/issues/50629
https://tracker.ceph.com/issues/50541
backport #41064
https://tracker.ceph.com/issues/50871
https://tracker.ceph.com/issues/50877
https://tracker.ceph.com/issues/50537
https://tracker.ceph.com/issues/50917
https://tracker.ceph.com/issues/50876
https://tracker.ceph.com/issues/50993

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by vshankar** [comment]
@yuriw please pick this up for next pacific test run.

**Comment by leseb** [comment]
@vshankar is it easier for you or @yuriw to put the commits from https://github.com/ceph/ceph/pull/41044, in the PR too? Thanks!

**Comment by vshankar** [comment]
> @vshankar is it easier for you or @yuriw to put the commits from #41044, in the PR too? Thanks!

I guess @yuriw has already picked this up for testing since I see the testing label on it.

**Review by batrick — APPROVED** [review]
Run looks good except for some kclient testing branch failures which are known.

**Comment by vshankar** [comment]
Just FYI, mirror,libcephfs test run: https://pulpito.ceph.com/vshankar-2021-06-07_12:19:36-fs-wip-cephfs-mirror-pacific-backports-20210607-054957-distro-basic-smithi/

**Pull request merged**
