### PR TITLE
cmake/modules/BuildRocksDB: add uring to rocksdb's link library

### PR DESCRIPTION
**Pull request by rosinL**
if liburing is found and rocksdb built with it, but librocksdb.a didn't linked the uring library, compile error occurs. So add liburing to rocksdb's link library.

Fixes: https://tracker.ceph.com/issues/61244

Signed-off-by: luo rixin <luorixin@huawei.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by rosinL** [comment]
jenkins retest this please

**Comment by rosinL** [comment]
jenkins retest this please

**Review by tchaikov — APPROVED** [review]

**Comment by rosinL** [comment]
@yuriw @ljflores Would you help to do the qa test?

**Comment by rosinL** [comment]
@ljflores Would you help to test this？

**Comment by ljflores** [comment]
@rosinL yes, sorry for missing your earlier message.

**Comment by cbodley** [comment]
@rosinL @batrick can you please check whether this was already resolved in https://github.com/ceph/ceph/pull/54042?

**Comment by batrick** [comment]
> @rosinL @batrick can you please check whether this was already resolved in #54042?

It looks like it. Let's close this.

Sorry @rosinL your PR got forgotten.

**Comment by rosinL** [comment]
@batrick the bug have been fixed finally, please update or close the issue https://tracker.ceph.com/issues/61244, thanks

**Pull request closed without merging**
