### PR TITLE
mgr/volumes: improve volume deletion process

### PR DESCRIPTION
**Pull request by jschmid1**
Instead of checking if the --yes-i-really-mean-it
flag was set _after_ removing the MDS daemon, we
need to check if before starting any removal operation.

Signed-off-by: Joshua Schmid <jschmid@suse.de>

### CODE REVIEW

**Comment by joscollin** [comment]
@jschmid1 Do a QA run and check `test_volume_rm` test result.

**Comment by jschmid1** [comment]
> @jschmid1 Do a QA run and check `test_volume_rm` test result.

Could you forward me to a doc on how to do that?

**Comment by ajarr** [comment]
@jschmid1 please create a Ceph tracker ticket so that we don't forget to backport it to nautilus.

**Comment by jschmid1** [comment]
> @jschmid1 please create a Ceph tracker ticket so that we don't forget to backport it to nautilus, and have the commit mention that it `Fixes: <tracker ticket link>`.

done @ajarr

**Comment by batrick** [comment]
> @jschmid1 Do a QA run and check `test_volume_rm` test result.

@joscollin Please schedule the run yourself.

**Comment by joscollin** [comment]
http://pulpito.front.sepia.ceph.com/jcollin-2019-11-21_22:40:05-fs-mds_removal_ssh_unused_var_static_typing_testing-distro-basic-smithi/

**Comment by joscollin** [comment]
Test passed:
http://pulpito.front.sepia.ceph.com/jcollin-2019-11-22_05:40:26-fs-mds_removal_ssh_unused_var_testing-distro-basic-smithi/

**Comment by joscollin** [comment]
```
2019-11-22T06:46:36.371 INFO:tasks.cephfs_test_runner:test_volume_rm (tasks.cephfs.test_volumes.TestVolumes) ... ok
2019-11-22T06:46:36.371 INFO:tasks.cephfs_test_runner:
2019-11-22T06:46:36.372 INFO:tasks.cephfs_test_runner:----------------------------------------------------------------------
2019-11-22T06:46:36.372 INFO:tasks.cephfs_test_runner:Ran 43 tests in 2675.803s
2019-11-22T06:46:36.372 INFO:tasks.cephfs_test_runner:
2019-11-22T06:46:36.372 INFO:tasks.cephfs_test_runner:OK

2019-11-22T06:48:16.438 INFO:tasks.cephfs_test_runner:test_volume_rm (tasks.cephfs.test_volumes.TestVolumes) ... ok
2019-11-22T06:48:16.439 INFO:tasks.cephfs_test_runner:
2019-11-22T06:48:16.439 INFO:tasks.cephfs_test_runner:----------------------------------------------------------------------
2019-11-22T06:48:16.439 INFO:tasks.cephfs_test_runner:Ran 43 tests in 2621.792s
2019-11-22T06:48:16.439 INFO:tasks.cephfs_test_runner:
2019-11-22T06:48:16.439 INFO:tasks.cephfs_test_runner:OK
```

**Pull request merged**
