### PR TITLE
mon: mark mgr reports as no_reply

### PR DESCRIPTION
**Pull request by tchaikov**
see also: #20517

Fixes: http://tracker.ceph.com/issues/22114
Signed-off-by: Kefu Chai <kchai@redhat.com>

### CODE REVIEW

**Comment by tchaikov** [comment]
it should address the failures in http://pulpito.ceph.com/kchai-2018-03-27_08:29:32-rados-wip-kefu-testing-2018-03-27-1407-distro-basic-smithi/

```
$ zgrep -A2 'DEBUG SLOW OP' remote/smithi020/log/ceph-mon.b.log.gz|grep desc | cut -d: -f2 | sort | uniq
 "monmgrreport(1 checks)",
 "monmgrreport(2 checks)",
$ zgrep -A2 'DEBUG SLOW OP' remote/smithi008/log/ceph-mon.c.log.gz|grep desc | cut -d: -f2 | sort | uniq
 "monmgrreport(0 checks)",
 "monmgrreport(1 checks)",
 "monmgrreport(2 checks)",
 "monmgrreport(3 checks)",
```

**Comment by tchaikov** [comment]
http://pulpito.ceph.com/kchai-2018-03-27_15:55:56-rados-wip-kefu-testing-2018-03-27-2116-distro-basic-smithi/

**Comment by tchaikov** [comment]
@jecluis @gregsfortytwo ping?

**Comment by jecluis** [comment]
@tchaikov is the failed job related to this?

**Comment by tchaikov** [comment]
@jecluis @rjfd  no. the dashboard test failure it's due to missing zstd compressor plugin on monitor. i have not looked into that issue further. but i am sure it's not caused by dashboard or my change.

**Comment by jecluis** [comment]
@tchaikov gotcha. thanks

**Comment by yuriw** [comment]
@theanalyst this needs to be backported see #21016

**Comment by tchaikov** [comment]
strange enough, we still have SLOW_OPS  in http://pulpito.ceph.com/kchai-2018-03-29_13:20:02-rados-wip-slow-mon-ops-kefu-distro-basic-smithi/2334154/ .

**Comment by tchaikov** [comment]
@gregsfortytwo i am not sure if that's possible or a better way.  as i think, no_reply() is an decision by the upper layer of the application stack, not the call of messenger, where the messages are decoded.
also, as some of the messages are encapsulated in the "MForward" message, and it is again the upper layer (Monitor::handle_forward()) who extract the encapsulated message and dispatch it manually. so we need to do the markings when we handle the certain messages.

or probably i misunderstand you completely.

**Comment by jecluis** [comment]
If @gregsfortytwo was suggesting having the message marked at construction by the sender, then this could possibly be feasible, but I think we have too many exceptions in the monitors to drop/no_reply vs handle that this may be even trickier than addressing individual instances.

It would be nice if we knew exactly which messages are not expecting a reply, so that we could simply mark them as such in their ctor or something. But I'm guessing those would be a small subset of the messages we actually handle as no_reply() _[he said, without actually looking at the code]_.

On the other hand, if we were to identify those that are typically no_reply, and mark them as such by default, and only reply to them in selected cases... then that may help with things a little. However, this doesn't seem a trivial task to accomplish either.

**Comment by gregsfortytwo** [comment]
Yes, I meant what Joao says: the peon monitor could mark them as no-reply, that gets flagged (in the MRoute or similar) and the leader's PaxosService dispatch machinery can be responsible for sending back the blank "handled" message to the peon once the message is resolved.

This might be useless, in that it merely moves responsibility for noticing it from the recipient to the sender. Or it might be easier, since we can identify categories of messages that don't need a response and set it all up in their constructors as an obvious decision the author needs to make, instead of something to maintain in far-off code without obvious failures. (So far, they are all static: MMonMgrReport, MOSDFailure, MOSDPGCreated, MOSDBeacon, and MMgrBeacon.) (Or maybe now that we are noticing slow mon ops we don't care any more.)

**Pull request merged**
