### PR TITLE
mimic: mgr/dashboard: RGW is not working if an URL prefix is defined

### PR DESCRIPTION
**Pull request by votdev**
Fixes https://tracker.ceph.com/issues/25068

This is the backport of #23200. It's not possible to cherry-pick it because the code has been changed too much from Mimic -> Nautilus.

Signed-off-by: Volker Theile <vtheile@suse.com>

### CODE REVIEW

**Comment by ricardoasmarques** [comment]
@votdev I've noticed that this open PR is also using an URL that starts with a slash: https://github.com/ceph/ceph/pull/22670/files#diff-0a729d63f185cb3c722b720d9738bca2R78

**Comment by votdev** [comment]
@ricardoasmarques Thx for the tip, i've adressed it.

**Comment by votdev** [comment]
@smithfarm Commit message has been modified.

**Comment by smithfarm** [comment]
Please don't merge until v13.2.1 is released. We are not merging any mimic PRs now.

**Comment by s0nea** [comment]
@yuriw if I get it right, we normally run the rados/mgr suite and filter for the dashboard related tests, e.g. "teuthology-suite -k distro --priority 101 --suite rados/mgr --email <email-address> --ceph <branch to test> --machine-type smithi --filter dashboard". So it makes sense to me to run these tests for this PR as well.

**Comment by yuriw** [comment]
[wip-yuri-testing-2018-08-20-1524-mimic](https://trello.com/c/A6vEVe9V/376-wip-yuri-testing-2018-08-20-1524-mimic)

**Pull request merged**
