### PR TITLE
hammer: When logging to a file fails, ceph logs excessively to stderr

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/15081

### CODE REVIEW

**Comment by smithfarm** [comment]
This replaces #8077 which was causing an extra blank line to be written to the log after every log entry.

**Comment by smithfarm** [comment]
Hey Jenkins, test this please !

**Comment by smithfarm** [comment]
@liewegas This PR is in the latest round of hammer-backports integration tests, which passed a rados run (the only failures are a valgrind false positive that has since been fixed by https://github.com/ceph/teuthology/pull/915 and http://tracker.ceph.com/issues/15139 which is an infrastructure issue with two of the tests) - for details, see: http://tracker.ceph.com/issues/15895#note-18

I can also confirm that this PR fixed the "extra blank line" issue referred to in https://github.com/ceph/ceph/pull/10227#issuecomment-231537923

OK to merge?

**Comment by athanatos** [comment]
lgtm

**Pull request merged**
