### PR TITLE
doc: Fixes typo.

### PR DESCRIPTION
**Pull request by spotz**
Fixes: http://tracker.ceph.com/issues/24924

Signed-off-by: Amy Marrich <amy@demarco.com>

- [X ] References tracker ticket
- [ X] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by batrick** [comment]
Please annotate the commit which fixes/resolves a Ceph tracker issue with:

`Fixes: http://tracker.ceph.com/issues/...`

This is essential when examining the history of the repository (this commit fixes what) and helps merge scripts identify issues that have been resolved by a merge.

**Comment by spotz** [comment]
Fixes: line in commit message has been updated

Amy

**Comment by spotz** [comment]
Fixes link updated

**Comment by tchaikov** [comment]
@spotz commit message is different than the first comment of your pull request. you might need to `git commit --amend` your commit message locally, and `git push -f` to your `wip-doc-24924` remote repo to update this PR.

**Comment by spotz** [comment]
New commit published

**Comment by tchaikov** [comment]
@spotz ping?

**Comment by spotz** [comment]
New commit message was submitted a few weeks ago.

**Comment by tchaikov** [comment]
@spotz would you please squash these commit into a single one? see https://github.com/todotxt/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit

**Comment by spotz** [comment]
*@tchaikov <https://github.com/tchaikov> it should be squashed into one now*

**Comment by tchaikov** [comment]
@spotz no, i don't think so. there are 5 commits in this PR now.

**Comment by tchaikov** [comment]
already fixed by #25953

**Pull request closed without merging**
