### PR TITLE
kraken: rgw: Swift API: spurious newline after http body causes weird errors

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/18780

### CODE REVIEW

**Comment by smithfarm** [comment]
@yehudasa This passed an RGW suite at http://tracker.ceph.com/issues/19009#note-8

Please review/approve if you agree it can be merged.

**Comment by smithfarm** [comment]
@yehudasa This PR passed another RGW suite at http://tracker.ceph.com/issues/19009#note-18

Waiting for review.

**Comment by smithfarm** [comment]
Could someone please review this PR.

**Comment by oritwas** [comment]
jenkins test this please

**Comment by cbodley** [comment]
jenkins test this please

**Pull request merged**
