### PR TITLE
nautilus: ceph-iscsi: selinux fixes

### PR DESCRIPTION
**Pull request by dillaman**
https://tracker.ceph.com/issues/46725

### CODE REVIEW

**Comment by yuriw** [comment]
@dillaman pls rebase

**Comment by dillaman** [comment]
> @dillaman pls rebase

done

**Review by badone — APPROVED** [review]

**Comment by badone** [comment]
jenkins retest this

**Comment by dmick** [comment]
retest this please

**Comment by dmick** [comment]
jenkins test api

**Pull request merged**
