### PR TITLE
ceph.spec.in: remove duplicate BuildRequires

### PR DESCRIPTION
**Pull request by smithfarm**
Signed-off-by: Nathan Cutler <ncutler@suse.com>

### CODE REVIEW

**Comment by tchaikov** [comment]
looks good. probably, could add a commit to sort them also?

**Comment by dachary** [comment]
Watch out for #4878 as it may create a merge conflict (but one that should not be difficult to resolve)

**Comment by dachary** [comment]
xmlstarlet and yasm are a few line above

BuildRequires:	python-sphinx
BuildRequires:	net-tools

is duplicated two lines apart

<pre>
Reviewed-by: Loic Dachary &lt;ldachary@redhat.com>
</pre>

**Comment by smithfarm** [comment]
@tchaikov: good idea, but I will do that in a later PR to avoid potential merge conflicts with #4880 and #4881

**Comment by dachary** [comment]
The bot failure comes from the rebase that occurred after the jenkins job started (jenkins does not know how to deal with that). Since this on ubuntu and the change is for spec files, it can be ignored.

http://jenkins.ceph.dachary.org/job/ceph/LABELS=ubuntu-14.04&&x86_64/5711/console

**Comment by smithfarm** [comment]
@ktdreyer rebased to current master

**Pull request merged**
