### PR TITLE
mimic: deb/rpm: add python-six as build-time and run-time dependency

### PR DESCRIPTION
**Pull request by tchaikov**
http://tracker.ceph.com/issues/24885

---

python-six is used by dashboard's controllers. please note,
${python:Depends} is able to fill the installation dependencies for
debian package. so python-six is not added to Requires of ceph-mgr.

Signed-off-by: Kefu Chai <kchai@redhat.com>
(cherry picked from commit e53bb2c5a32e9b458a55fe01b28f23bdf952b6f7)

### CODE REVIEW

**Comment by tchaikov** [comment]
sure, will do.

**Comment by smithfarm** [comment]
@tchaikov https://github.com/ceph/ceph/pull/22950 has been merged - could you cherry-pick both commits into this PR?

**Comment by tchaikov** [comment]
@smithfarm done.

**Comment by yuriw** [comment]
[wip-yuri2-testing-2018-07-17-1644-mimic](https://trello.com/c/ycgXE6aA/349-wip-yuri2-testing-2018-07-17-1644-mimic)

**Pull request merged**
