### PR TITLE
cephfs-top: display average read/write/metadata latency

### PR DESCRIPTION
**Pull request by vshankar**
## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by vshankar** [comment]
jenkins test make check

**Comment by lxbsz** [comment]
Will test and review it tomorrow.

**Comment by lxbsz** [comment]
It displays nothing but the titiles:

Screenshot from 2021-06-11 20-41-22

I have two mounters(one kclient and one fuse):

```
192.168.0.105:40673,192.168.0.105:40675,192.168.0.105:40677:/ on /tmp/tmpoyait5v5/mnt.1 type ceph (rw,relatime,name=1,secret=<hidden>,acl)
ceph-fuse on /mnt/cephfs type fuse.ceph-fuse (rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other)
192.168.0.105:40414,192.168.0.105:40416,192.168.0.105:40418:/ on /mnt/kcephfs type ceph (rw,relatime,acl)
```

**Comment by vshankar** [comment]
> It displays nothing but the titiles:

That's strange. I refreshed the image in the docs here: https://ceph--41397.org.readthedocs.build/en/41397/cephfs/cephfs-top/

I'll take a look next week. Thanks for reviewing @lxbsz

**Comment by lxbsz** [comment]
> > It displays nothing but the titiles:
> 
> That's strange. I refreshed the image in the docs here: https://ceph--41397.org.readthedocs.build/en/41397/cephfs/cephfs-top/
> 
> I'll take a look next week. Thanks for reviewing @lxbsz

Without this PR it works:

Screenshot from 2021-06-11 21-40-26

**Comment by vshankar** [comment]
> Without this PR it works:

Not sure what changed. I'll take a look.

**Comment by vshankar** [comment]
@lxbsz The client entries show up in cephfs-top:
Selection_048

Could you share the output of:

```
ceph fs perf stats
```

**Comment by lxbsz** [comment]
```
$ ceph fs perf stats
{"version": 1, "global_counters": ["cap_hit", "read_latency", "write_latency", "metadata_latency", "dentry_lease", "opened_files", "pinned_icaps", "opened_inodes", "avg_read_latency", "stdev_read_latency", "avg_write_latency", "stdev_write_latency", "avg_metadata_latency", "stdev_metadata_latency"], "counters": [], "client_metadata": {}, "global_metrics": {}, "metrics": {"delayed_ranks": []}}
```

Tried it again, actually it worked for me, I just didn't wait enough time because before without this PR it would show the entries very quickly. 

With this PR for the first time to run the `cephfs-top`, usually I just need to wait for almost 15 seconds or more longer that the client entries showed in `cephfs-top`.

**Review by lxbsz — APPROVED** [review]
LGTM.

Without this PR sometimes I also can get the same result, which will delay 15 seconds to show the client entries for the first time to run the `cephfs-top`.

So this shouldn't be introduced by this PR.

**Comment by vshankar** [comment]
> LGTM.
> 
> Without this PR sometimes I also can get the same result, which will delay 15 seconds to show the client entries for the first time to run the `cephfs-top`.
> 
> So this shouldn't be introduced by this PR.

Thanks for testing @lxbsz

**Comment by vshankar** [comment]
Hey @lxbsz -- does the kclient have these metrics? https://tracker.ceph.com/issues/48621 mentions kernel patchwork link which does not seem to show anything.

**Comment by lxbsz** [comment]
> Hey @lxbsz -- does the kclient have these metrics? https://tracker.ceph.com/issues/48621 mentions kernel patchwork link which does not seem to show anything.

The patchwork seems being cleaned.

Yeah, the kclient already support the total/min/max/average/stdev latency metrics for read/write/metadta in the beginning long time ago and it will show them in the debugfs file, but currently it will only send the total latencies to MDS daemon, please see:

https://github.com/ceph/ceph-client/commit/97e27aaa9a2cbd6238c66b3251d397e0eacc9968
https://github.com/ceph/ceph-client/commit/70c948206f0616c7e46130a26165b6a5d98bade4

**Comment by vshankar** [comment]
> Yeah, the kclient already support the total/min/max/average/stdev latency metrics for read/write/metadta in the beginning long time ago and it will show them in the debugfs file, but currently it will only send the total latencies to MDS daemon, please see:

OK. I'll add support to send them to MDS then.

**Review by batrick — APPROVED** [review]

**Comment by vshankar** [comment]
jenkins test api

**Comment by vshankar** [comment]
jenkins test api

**Comment by vshankar** [comment]
updated with fixes for calculating stdev (track sum of squares and calculate stdev when sending metrics to mds).

**Comment by vshankar** [comment]
I got to this pretty late. Sorry for that.

With this update, clients do not have to periodically compute stdev and forward it to the MDS - they just forward whatever is required to calculate stdev (which is then calculated by cephfs-top). I'll post the kclient changes tomorrow.

**Comment by vshankar** [comment]
jenkins test make check

**Comment by lxbsz** [comment]
This looks good to me.

**Comment by vshankar** [comment]
> This looks good to me.

I'll send the kclient changes too.

**Comment by vshankar** [comment]
https://tracker.ceph.com/projects/cephfs/wiki/Master#2022-Mar-08

**Pull request merged**
