### PR TITLE
rgw/test: allow passing vstart parameters to multisite tests script

### PR DESCRIPTION
**Pull request by yuvalif**
via the VSTART_PARAMETERS env variable

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [x] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by yuvalif** [comment]
jenkins test make check

**Comment by yuvalif** [comment]
jenkins test make check

**Comment by yuvalif** [comment]
teuthology results: http://pulpito.front.sepia.ceph.com/yuvalif-2023-07-17_14:44:32-rgw:multisite-wip-yuval-multisite-vstart-params-distro-default-smithi/
are these expected:
```
rgw_multi.tests.test_resharded_bucket_full_sync_after_data_sync_init ... FAIL
rgw_multi.tests.test_bucket_incremental_sync_after_data_sync_init ... FAIL
rgw_multi.tests.test_resharded_bucket_incremental_sync_latest_after_data_sync_init ... FAIL
rgw_multi.tests.test_resharded_bucket_incremental_sync_oldest_after_data_sync_init ... FAIL
test_sync_policy_config_zonegroup: ... FAIL
test_sync_flow_symmetrical_zonegroup_all: ... FAIL
test_sync_flow_symmetrical_zonegroup_select: ... FAIL
test_sync_flow_directional_zonegroup_select: ... FAIL
test_sync_single_bucket: ... FAIL
test_sync_different_buckets: ... FAIL
test_sync_multiple_buckets_to_single: ... FAIL
test_sync_single_bucket_to_multiple: ... FAIL
```

**Comment by yuvalif** [comment]
jenkins test make check

**Review by cbodley — APPROVED** [review]

**Pull request merged**
