### PR TITLE
osd: WeightedPriorityQueue: move to intrusive containers

### PR DESCRIPTION
**Pull request by rldleblanc**
My microbenchmarks is showing a 60-70% execution time compared to the previous version and PrioritizedQueue. Unittests also complete without issues.

However, I'm stuck with an issue that I could use some help on. The OSDs will start up and recover just fine, but as soon as client traffic happens, it gets an assert (i.e. rbd -p rbd ls). I've looked at it through gdb and r has a value of 22 which I believes means EINVAL which means that the mutex does not refer to an initialized mutex object. However dumping the mutex object looks initialized to me. So I'm not really sure what is going on and could use some help. Don't forget to set "osd_op_queue = wpq" so the error shows up.

     0> 2016-02-15 18:21:28.448629 7f94e7a6b700 -1 *** Caught signal (Aborted) **
 in thread 7f94e7a6b700

 ceph version 10.0.3-1037-g91339ad (91339ade26f26b41af9d950190b1c7793289c0af)
 1: (()+0x91ab55) [0x55b481344b55]
 2: (()+0xf8d0) [0x7f9504c0b8d0]
 3: (gsignal()+0x37) [0x7f9502c31107]
 4: (abort()+0x148) [0x7f9502c324e8]
 5: (ceph::__ceph_assert_fail(char const*, char const*, int, char const*)+0x256) [0x55b48144b9f6]
 6: (Mutex::Lock(bool)+0x194) [0x55b4813fa5c4]
 7: (TrackedOp::mark_event(std::string const&)+0x74) [0x55b481346124]
 8: (OpRequest::mark_flag_point(unsigned char, std::string const&)+0x14) [0x55b480e10714]
 9: (OSD::dequeue_op(boost::intrusive_ptr<PG>, std::shared_ptr<OpRequest>, ThreadPool::TPHandle&)+0x3ec) [0x55b480d86b6c]
 10: (PGQueueable::RunVis::operator()(std::shared_ptr<OpRequest>&)+0x6a) [0x55b480d86dfa]
 11: (OSD::ShardedOpWQ::_process(unsigned int, ceph::heartbeat_handle_d*)+0x769) [0x55b480da1e59]
 12: (ShardedThreadPool::shardedthreadpool_worker(unsigned int)+0x8b6) [0x55b48143b5d6]
 13: (ShardedThreadPool::WorkThreadSharded::entry()+0x10) [0x55b48143d590]
 14: (()+0x80a4) [0x7f9504c040a4]
 15: (clone()+0x6d) [0x7f9502ce204d]
 NOTE: a copy of the executable, or `objdump -rdS <executable>` is needed to interpret this.

Aborted

(gdb) frame 3
#3  0x0000555555f245c4 in Mutex::Lock (this=this@entry=0x55555fdf9448, no_lockdep=no_lockdep@entry=false) at common/Mutex.cc:113
113       assert(r == 0);
(gdb) list
108                      ceph_clock_now(cct) - start);
109       } else {
110         r = pthread_mutex_lock(&_m);
111       }
112
113       assert(r == 0);
114       if (lockdep && g_lockdep) _locked();
115       _post_lock();
116
117     out:
(gdb) print _m
$1 = {__data = {__lock = 0, __count = 0, __owner = 0, __nusers = 0, __kind = -1, __spins = 0, __elision = 0, __list = {__prev = 0x0, __next = 0x0}}, 
  __size = '\000' <repeats 16 times>, "\377\377\377\377", '\000' <repeats 19 times>, __align = 0}
(gdb) p r
$2 = 22
(gdb) 

Thanks

### CODE REVIEW

**Comment by somnathr** [comment]
@rldleblanc I think it's a race. I got similar error in some cases and all turned out because of race condition. Probably mutex is becoming invalid because TrackedOP (Actual op) is getting deleted (?).
You may want to try with the config option "osd_enable_op_tracker = false" so that this part of the code won't be executed and hopefully will crash somewhere else to be more sure..

**Comment by rldleblanc** [comment]
@somnathr Thanks for the suggestion. I am getting a different error with disabling the op tracker. I'll have to look into it a bit more tomorrow.

common/buffer.cc: In function 'void ceph::buffer::ptr::copy_out(unsigned int, unsigned int, char*) const' thread 7fffd7326700 time 2016-02-16 05:54:10.860295
common/buffer.cc: 847: FAILED assert(_raw)
 ceph version 10.0.3-1037-g91339ad (91339ade26f26b41af9d950190b1c7793289c0af)
 1: (ceph::__ceph_assert_fail(char const*, char const*, int, char const*)+0x82) [0x555555f75822]
 2: (()+0xa26eba) [0x555555f7aeba]
 3: (ceph::buffer::list::iterator_impl<false>::copy(unsigned int, char*)+0x5b) [0x555555f81f2b]
 4: (ReplicatedPG::do_op(std::shared_ptr<OpRequest>&)+0x99) [0x555555a45759]
 5: (ReplicatedPG::do_request(std::shared_ptr<OpRequest>&, ThreadPool::TPHandle&)+0x707) [0x5555559d7227]
 6: (OSD::dequeue_op(boost::intrusive_ptr<PG>, std::shared_ptr<OpRequest>, ThreadPool::TPHandle&)+0x420) [0x5555558b0ba0]
 7: (PGQueueable::RunVis::operator()(std::shared_ptr<OpRequest>&)+0x6a) [0x5555558b0dfa]
 8: (OSD::ShardedOpWQ::_process(unsigned int, ceph::heartbeat_handle_d*)+0x769) [0x5555558cbe59]
 9: (ShardedThreadPool::shardedthreadpool_worker(unsigned int)+0x8b6) [0x555555f655d6]
 10: (ShardedThreadPool::WorkThreadSharded::entry()+0x10) [0x555555f67590]
 11: (()+0x80a4) [0x7ffff6c340a4]
 12: (clone()+0x6d) [0x7ffff4d3804d]
 NOTE: a copy of the executable, or `objdump -rdS <executable>` is needed to interpret this.

**Comment by somnathr** [comment]
@rldleblanc Yes, expected, your Op is getting invalidated somehow...
Probably adding some print or gdb breakpoint to OpRequest/TrackedOp destructor would help(?)..

**Comment by rldleblanc** [comment]
With @athanatos 's help the assert is resolved. This is showing about a 6.5% increase in 4K SSD performance in my tests. Eyeballing top, there seems to be a slight reduction in CPU and RAM. I did run the queue through valgrind and it came back clean. I didn't test 4M SSD because my SSDs were already maxed out and it didn't yield any increase.

**Comment by rldleblanc** [comment]
I was trying to use move semantics to improve things, but I couldn't get any more performance from my attempts. I think this is as good as I can get it.

**Pull request merged**
