### PR TITLE
cephadm: remove trailing white spaces

### PR DESCRIPTION
**Pull request by jmolmo**
Following:

https://www.python.org/dev/peps/pep-0008/#other-recommendations

I removed trailing white spaces from cephadm 

Signed-off-by: Juan Miguel Olmo Martínez <jolmomar@redhat.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Review by smithfarm — COMMENTED** [review]
I'm against cosmetic cleanups of this kind, because they create havoc in the backporting process. See https://github.com/ceph/ceph/pull/38881#issuecomment-768926233 for a slightly more wordy statement of this position.

**Comment by jmolmo** [comment]
> I'm against cosmetic cleanups of this kind, because they create havoc in the backporting process. See [#38881 (comment)](https://github.com/ceph/ceph/pull/38881#issuecomment-768926233) for a slightly more wordy statement of this position.

@smithfarm : What kind of solution do you prefer?

**Comment by smithfarm** [comment]
> @smithfarm : What kind of solution do you prefer?

Address cosmetic issues in the review process of master PRs. Add checks for trailing whitespace to the linter which is run as part of "make check", or create a Jenkins check for trailing whitespaces, so no PR can be merged if it introduces them.

Once the code is in, refrain from making cosmetic changes.

**Comment by jmolmo** [comment]
> Once the code is in, refrain from making cosmetic changes.

I'm afraid, but I disagree completely with you:

To have better code, improve readability, and follow coding standards is always good.

In the same way that we fix "bugs" , we must address "code style" or "cosmetic" issues.  If a "cosmetic" problem has been introduced in the code, we must fix it.

It seems that your major problem for you  with this modification is about "backports". Do you think that this kind of  modification is going to cause conflicts difficult to solve?

**Comment by sebastian-philipp** [comment]
> > Once the code is in, refrain from making cosmetic changes.

:+1:

plus I'd second Greg form https://github.com/ceph/ceph/pull/33848#pullrequestreview-373001914 

@jmolmo do you want to add improve our auto-formatter that automatically does these changes instead? That would make @mgfritch super happy!

**Comment by jmolmo** [comment]
> > > Once the code is in, refrain from making cosmetic changes.
> 
> 
> 
> plus I'd second Greg form [#33848 (review)](https://github.com/ceph/ceph/pull/33848#pullrequestreview-373001914)
> 
so following Greg suggestion, maybe we can discard this pr and use the original one https://github.com/ceph/ceph/pull/38881

> @jmolmo do you want to add improve our auto-formatter that automatically does these changes instead? That would make @mgfritch super happy!

@sebastian-philipp , @mgfritch ... like this one?
https://github.com/ceph/ceph/pull/39148

**Comment by jmolmo** [comment]
Closed because negative karma and grey aura around the white spaces

**Pull request closed without merging**
