### PR TITLE
Revert "mgr/dashboard: Generate NPM dependencies manifest"

### PR DESCRIPTION
**Pull request by nizamial09**
This reverts commit 825ea98915bcb0ab4bbaefb478ee0a0b8e506933.

Reverts: https://tracker.ceph.com/issues/50515
Signed-off-by: Nizamudeen A <nia@redhat.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by nizamial09** [comment]
jenkins test dashboard

**Review by epuertat — APPROVED** [review]
😞

**Review by Waadkh7 — APPROVED** [review]

**Comment by nizamial09** [comment]
jenkins test dashboard

**Comment by nizamial09** [comment]
jenkins test dashboard

**Pull request merged**
