### PR TITLE
common: various fixes from SCA runs

### PR DESCRIPTION
**Pull request by dalgaaf**
Several type of fixes:
- remove unused variables
- prefer ++operator for non-primitive iterators
- fix compare same variables with itself
- change some ctors to explicit
- fix same variable names in parent and derived class
- init member variables in constructor
- remove unused code
- replace inefficient string::find() w/ compare()
- reduce scope of variables
- update .gitignore

### CODE REVIEW

**Comment by gregsfortytwo** [comment]
Client and MDS patches look fine. Didn't check the others.

**Comment by tchaikov** [comment]
all commits reviewed.

**Comment by tchaikov** [comment]
lgtm.

**Comment by dalgaaf** [comment]
rebased, dropped one patch that was already merged with an alternative patch

**Comment by dillaman** [comment]
librbd changes lgtm

**Pull request merged**
