### PR TITLE
mgr/dashboard: test_standby* (tasks.mgr.test_dashboard.TestDashboard) failed locally

### PR DESCRIPTION
**Pull request by votdev**
Fixes: https://tracker.ceph.com/issues/48449

Signed-off-by: Volker Theile <vtheile@suse.com>

## Checklist
- [x] References tracker ticket
- [ ] Updates documentation if necessary
- [x] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by votdev** [comment]
jenkins test make check

**Comment by votdev** [comment]
jenkins test make check

**Review by callithea — APPROVED** [review]
Lgtm

**Comment by callithea** [comment]
- [pkg build](https://shaman.ceph.com/builds/ceph/wip-laura-testing-octopus-batch-37973-38094-38331-38405/)
- [QA run](https://pulpito.ceph.com/laura-2020-12-08_17:50:24-rados:dashboard-wip-laura-testing-octopus-batch-37973-38094-38331-38405-distro-basic-smithi/) [9/9 passed]

**Comment by callithea** [comment]
- [pkg build](https://shaman.ceph.com/builds/ceph/wip-laura-testing-38435/) [WIP]
- QA run [PENDING]

**Review by s0nea — APPROVED** [review]
:+1: I tested the PR locally.

**Pull request merged**
