### PR TITLE
nautilus: rgw: multisite: Verify if the synced object is identical to source

### PR DESCRIPTION
**Pull request by yanghonggang**
backport trackers:

* https://tracker.ceph.com/issues/48857
* https://tracker.ceph.com/issues/49045
* https://tracker.ceph.com/issues/49382

---

backport of:

* https://github.com/ceph/ceph/pull/33492
* https://github.com/ceph/ceph/pull/37238
* https://github.com/ceph/ceph/pull/39569

parent trackers:

* https://tracker.ceph.com/issues/48801
* https://tracker.ceph.com/issues/45992
* https://tracker.ceph.com/issues/49357

### CODE REVIEW

**Review by cbodley — CHANGES_REQUESTED** [review]
this is missing the fixes from https://github.com/ceph/ceph/pull/37238. i would prefer not to backport this feature at all, unless there's real interest from the community

**Comment by yanghonggang** [comment]
> this is missing the fixes from #37238. i would prefer not to backport this feature at all, unless there's real interest from the community

@cbodley 

As a rgw multisite user myself, I originally thought object integrity already can be ensured when object is synced to the dest zone. If we don't check data integrity, the data on the slave cluster may not be trusted.

Why you suggest not to backport this import feature?

**Comment by yanghonggang** [comment]
> this is missing the fixes from #37238. i would prefer not to backport this feature at all, unless there's real interest from the community

ok, I will pick #37238.

**Comment by cbodley** [comment]
@yanghonggang there shouldn't be merge commits in your PR. please use `git cherry-pick -x` to cherry-pick the individual commits

**Comment by smithfarm** [comment]
@yanghonggang A couple things that might help:

1. https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst contains lots of information about Ceph backporting
2. particularly relevant to this PR: https://github.com/ceph/ceph/pull/38981 is the equivalent octopus backport. The nautilus backport should look like that.

**Comment by yanghonggang** [comment]
@cbodley @smithfarm done

**Comment by smithfarm** [comment]
LGTM. Removing DNM and queuing for integration test.

**Comment by cbodley** [comment]
seems to be causing multisite failures in https://pulpito.ceph.com/yuriw-2021-02-12_17:45:41-rgw-wip-yuri3-testing-2021-02-12-0757-nautilus-distro-basic-gibba/

there are several mismatch errors about a multipart upload:
```
rgw.c1.client.1.log.gz:2021-02-13 18:30:41.579 7f70f467f700  0 ERROR: source and destination objects don't match. Expected etag:59adb24ef3cdbe0297f05b395827453f-1 Computed etag:d41d8cd98f00b204e9800998ecf8427e
rgw.c1.client.1.log.gz:2021-02-13 18:30:42.083 7f70f5681700  0 ERROR: source and destination objects don't match. Expected etag:59adb24ef3cdbe0297f05b395827453f-1 Computed etag:d41d8cd98f00b204e9800998ecf8427e
rgw.c1.client.1.log.gz:2021-02-13 18:30:43.091 7f70f1679700  0 ERROR: source and destination objects don't match. Expected etag:59adb24ef3cdbe0297f05b395827453f-1 Computed etag:d41d8cd98f00b204e9800998ecf8427e
rgw.c2.client.0.log.gz:2021-02-13 18:30:42.140 7ff295b37700  0 ERROR: source and destination objects don't match. Expected etag:59adb24ef3cdbe0297f05b395827453f-1 Computed etag:d41d8cd98f00b204e9800998ecf8427e
rgw.c2.client.0.log.gz:2021-02-13 18:30:43.084 7ff296338700  0 ERROR: source and destination objects don't match. Expected etag:59adb24ef3cdbe0297f05b395827453f-1 Computed etag:d41d8cd98f00b204e9800998ecf8427e
```

**Comment by yanghonggang** [comment]
> objects don't match

@cbodley @smithfarm 

I think this is a new issue. The single-part-MPU object is treated as a Atomic object.
Because its part_size is 0. This problem maybe also exist in the latest master branch.
 
But start_part_num is not 0 which can be used to distinguish MPU object and Atomic object.
This problem can be fixed by the following change:

```cpp
diff --git a/src/rgw/rgw_etag_verifier.cc b/src/rgw/rgw_etag_verifier.cc
index da809c9..6a9d5cc 100644
--- a/src/rgw/rgw_etag_verifier.cc
+++ b/src/rgw/rgw_etag_verifier.cc
@@ -29,7 +29,7 @@ int create_etag_verifier(CephContext* cct, DataProcessor* filter,
     return -EIO;
   }
 
-  if (rule.part_size == 0) {
+  if (rule.start_part_num == 0) {
     /* Atomic object */
     verifier.emplace<ETagVerifier_Atomic>(cct, filter);
     return 0;
```

I'm glad to create a new pull request to fix this problem and pick it into this backport.

**Comment by cbodley** [comment]
thanks @yanghonggang. i looked through a multisite run against pacific and see those same error messages

> I'm glad to create a new pull request to fix this problem and pick it into this backport.

yes please! the fix looks right to me. i created https://tracker.ceph.com/issues/49357 to track this

**Comment by yanghonggang** [comment]
> thanks @yanghonggang. i looked through a multisite run against pacific and see those same error messages
> 
> > I'm glad to create a new pull request to fix this problem and pick it into this backport.
> 
> yes please! the fix looks right to me. i created https://tracker.ceph.com/issues/49357 to track this

@cbodley done
https://github.com/ceph/ceph/pull/39569

**Comment by yanghonggang** [comment]
jenkins test api

**Comment by yanghonggang** [comment]
@cbodley @smithfarm
https://github.com/ceph/ceph/pull/39569 is picked into this backport.

**Review by cbodley — APPROVED** [review]
multisite tests on nautilus are still a mess, but i don't think this PR is responsible

**Pull request merged**
