### PR TITLE
several fixes for make check

### PR DESCRIPTION
**Pull request by liewegas**
- check-generated now works
 - the unittest_encoding is fixed

### CODE REVIEW

**Comment by dachary** [comment]
run-make-check.sh succeeds

**Comment by dachary** [comment]
http://ceph.com/gitbuilder.cgi has a number of failures but I'm guessing this is because of the C++11 switch. If so, 

<pre>
Reviewed-by: Loic Dachary &lt;ldachary@redhat.com>
</pre>

**Comment by dzafman** [comment]
I was thinking about using a testing mode to encode unordered_map as map making it deterministic.

**Comment by dzafman** [comment]
I'll push a branch soon to show my idea.

**Comment by dzafman** [comment]
:+1:  I gave up on special casing the binary encoding for testing.

**Comment by liewegas** [comment]
Another thought I had was to make the json output comparisons pipe through 'sort' first. They'll be less precise, but they'll many/most misencodings, and not be sensitive to order...

**Pull request merged**
