### PR TITLE
mgr/dashboard: Remove unused variable

### PR DESCRIPTION
**Pull request by votdev**
Signed-off-by: Volker Theile <vtheile@suse.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by bk201** [comment]
jenkins test make check

**Comment by bk201** [comment]
LGTM, just wonder if we should remove others at the same time:
```
frontend/src/app/ceph/block/rbd-list/rbd-list.component.ts:342:      metaType: 'RBD',
frontend/src/app/ceph/block/rbd-trash-list/rbd-trash-list.component.ts:178:      metaType: 'RBD',
frontend/src/app/ceph/block/rbd-trash-move-modal/rbd-trash-move-modal.component.spec.ts:39:    component.metaType = 'RBD';
frontend/src/app/ceph/block/rbd-trash-move-modal/rbd-trash-move-modal.component.ts:21:  metaType: string;```
```
Maybe @tspmelo has some insight about this variable.

**Comment by votdev** [comment]
> LGTM, just wonder if we should remove others at the same time:
> 
> ```
> frontend/src/app/ceph/block/rbd-list/rbd-list.component.ts:342:      metaType: 'RBD',
> frontend/src/app/ceph/block/rbd-trash-list/rbd-trash-list.component.ts:178:      metaType: 'RBD',
> frontend/src/app/ceph/block/rbd-trash-move-modal/rbd-trash-move-modal.component.spec.ts:39:    component.metaType = 'RBD';
> frontend/src/app/ceph/block/rbd-trash-move-modal/rbd-trash-move-modal.component.ts:21:  metaType: string;```
> ```
> 
> Maybe @tspmelo has some insight about this variable.

Fixed

**Comment by epuertat** [comment]
Just curious: how was this found? tslint, tsc, ...?

**Comment by votdev** [comment]
> Just curious: how was this found? tslint, tsc, ...?

As for me, i found this while doing a code review.

**Comment by tspmelo** [comment]
This was used on an older version of DeletionModal: https://github.com/ceph/ceph/commit/8ba41c5e2b082c11ab07a9f431c4945e83c80f9d

Since the components we use with this states don't have this, it must have been a bad copy/paste.

**Comment by bk201** [comment]
> This was used on an older version of DeletionModal: [8ba41c5](https://github.com/ceph/ceph/commit/8ba41c5e2b082c11ab07a9f431c4945e83c80f9d)
> 
> Since the components we use with this states don't have this, it must have been a bad copy/paste.

Thanks for the explanation!

**Pull request merged**
