### PR TITLE
mds: disable `defer_client_eviction_on_laggy_osds' by default

### PR DESCRIPTION
**Pull request by vshankar**
This config can result in a single client holding up mds to service other clients since once a client is deferred from eviction due to laggy OSD(s), a new clients cap acquire request can be possibly blocked until the other laggy client resumes operation, i.e., when the laggy OSD is considered non-laggy anymore.

Disable the config by default till the issue is fixed.

Fixes: http://tracker.ceph.com/issues/64685

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Comment by dparmar18** [comment]
> We might need some test case fixes (which assume the config is enabled by default)

use https://github.com/ceph/ceph/pull/55784, just change the config to false and you're good to go.

**Comment by vshankar** [comment]
> > We might need some test case fixes (which assume the config is enabled by default)
> 
> use #55784, just remove the config set func call of `defer_client_eviction_on_laggy_osds` and you're good to go.

Yeh, I know that :)

What I meant was that I haven't yet seen if this change will break existing tests.

**Comment by dparmar18** [comment]
> > > We might need some test case fixes (which assume the config is enabled by default)
> > 
> > 
> > use #55784, just remove the config set func call of `defer_client_eviction_on_laggy_osds` and you're good to go.
> 
> Yeh, I know that :)
> 
> What I meant was that I haven't yet seen if this change will break existing tests.

I dont think so. The only issue known before the latest one is the laggy clients warnings experienced in API tests.

**Comment by vshankar** [comment]
> > > > We might need some test case fixes (which assume the config is enabled by default)
> > > 
> > > 
> > > use #55784, just remove the config set func call of `defer_client_eviction_on_laggy_osds` and you're good to go.
> > 
> > 
> > Yeh, I know that :)
> > What I meant was that I haven't yet seen if this change will break existing tests.
> 
> I dont think so. The only issue known before the latest one is the laggy clients warnings experienced in API tests.

`test_client_eviction_if_config_is_set` explicitly enables this config. We should disable that test for now.

**Comment by vshankar** [comment]
> those test cases are working fine since they don't reproduce this issue.

Yeh, I'm fine with leaving those as it is even if they fail :)

**Comment by vshankar** [comment]
jenkins retest this please

**Comment by vshankar** [comment]
https://pulpito.ceph.com/?branch=wip-vshankar-testing-20240307.013758

(test run review pending)

**Comment by vshankar** [comment]
https://tracker.ceph.com/projects/cephfs/wiki/Main#14th-March-2024

**Review by dparmar18 — CHANGES_REQUESTED** [review]
this needs a test case that makes sure https://github.com/ceph/ceph/pull/55784 (after some changes ofc) passes. e.g.:

```
    def test_mounting_clients_after_killed_with_an_osd_laggy(self):
        self.config_set('mds', 'mds_defer_session_stale', 'true')
        self.assertEqual(self.config_get('mds', 'mds_defer_session_stale'),
                                     'true')
        self.assertEqual(self.config_get(
            'mds', 'defer_client_eviction_on_laggy_osds'), 'false')

        # make an OSD laggy
        osd = self.get_a_random_osd()
        self.make_osd_laggy(osd)

        mount_a_gid = self.mount_a.get_global_id()
        self.mount_a.kill()
        self.assert_session_state(mount_a_gid, "open")

        time.sleep(self.fs.get_var("session_timeout") * 1.5)

        with contextutil.safe_while(sleep=120, tries=1) as proceed:
            while proceed():
                with self.assert_cluster_log("1 client(s) laggy due to"
                                             " laggy OSDs",
                                             timeout=60,
                                             invert_match = True):
                    self.assert_session_count(1)
                    break

        self.mount_a.umount_wait()
        self.mount_a.mount_wait()
        self.mount_a.create_destroy()

        self.mount_b.umount_wait()
        self.mount_b.mount_wait()
        self.mount_b.create_destroy()
```

**Comment by vshankar** [comment]
> this needs a test case that makes sure #55784 (after some changes ofc) passes. e.g.:

This change defaults the old behaviour and passes tests. We'll run test in #55784 through this anyway.

**Comment by dparmar18** [comment]
> > this needs a test case that makes sure #55784 (after some changes ofc) passes. e.g.:
> 
> This change defaults the old behaviour and passes tests. We'll run test in #55784 through this anyway.

it turns on the config before doing anything i guess that PR will need some modifications then.

**Comment by vshankar** [comment]
> > > this needs a test case that makes sure #55784 (after some changes ofc) passes. e.g.:
> > 
> > 
> > This change defaults the old behaviour and passes tests. We'll run test in #55784 through this anyway.
> 
> it turns on the config before doing anything i guess that PR will need some modifications then.

Right. Normally, config reverts should be merged asap and any fallouts are fixed on priority.

**Review by dparmar18 — APPROVED** [review]

**Pull request merged**
