### PR TITLE
nautilus: ls -S command produces AttributeError: 'str' object has no attribute 'decode'

### PR DESCRIPTION
**Pull request by smithfarm**
https://tracker.ceph.com/issues/39217
https://tracker.ceph.com/issues/39260

### CODE REVIEW

**Comment by yuriw** [comment]
[wip-yuri5-testing-2019-04-12-1916-nautilus](https://trello.com/c/tRDDEFxc/592-wip-yuri5-testing-2019-04-12-1916-nautilus)

**Comment by batrick** [comment]
This backport was missing https://github.com/ceph/ceph/pull/27345/commits/417836de308a8b642fec5f03d819800142155b34 for some reason. I'll open a PR that add the revert. @smithfarm was that an accident?

**Comment by smithfarm** [comment]
@batrick Yes, that was an unfortunate accident. Thanks for cleaning up my mess.

**Comment by batrick** [comment]
no problem!

**Pull request merged**
