### PR TITLE
qa/suites/krbd: rbd_xfstests job overhaul

### PR DESCRIPTION
**Pull request by idryomov**
I've been test running this for about a week.  There is a small list of one-off failures that I'll keep an eye for, but I think it's reliable enough now.

### CODE REVIEW

**Comment by idryomov** [comment]
Test run: http://pulpito.front.sepia.ceph.com/dis-2017-08-29_08:11:28-krbd-luminous-testing-basic-smithi/

**Comment by vasukulkarni** [comment]
I think we should port this to luminous, I tried to cherry-pick for a PR but strangely it doesn't apply cleanly without conflict.

**Comment by idryomov** [comment]
@vasukulkarni That's the plan.  I wanted to delay it until all the one-offs were sorted out though.

**Comment by idryomov** [comment]
luminous backport: https://github.com/ceph/ceph/pull/17970.

**Pull request merged**
