### PR TITLE
rados: fix typo in 'df' column name

### PR DESCRIPTION
**Pull request by idryomov**
Signed-off-by: Ilya Dryomov <idryomov@gmail.com>

### CODE REVIEW

**Comment by gregsfortytwo** [comment]
@idryomov, broken test (cli output matching, presumably)

**Comment by idryomov** [comment]
@gregsfortytwo 
```
The following tests FAILED:
	  5 - cephtool-test-mon.sh (Timeout)
```
Looks like it's been failing all day.

**Comment by joscollin** [comment]
Jenkins Retest this please

**Comment by tchaikov** [comment]
retest this please.

**Pull request merged**
