### PR TITLE
RGW - Swift retarget needs bucket set on object

### PR DESCRIPTION
**Pull request by prazumovsky**
cherry-pick of https://github.com/ceph/ceph/pull/46719 from 'quincy' to 'main' branch

Originally found missing patch for Ceph Reef https://tracker.ceph.com/issues/63684.

----

When a bucket list is retargeted to an object get, then the object may not yet have it's bucket set.  Ensure the bucket is set on the object.

Fixes: https://tracker.ceph.com/issues/56029

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Comment by cbodley** [comment]
thanks @prazumovsky!

@dang i see that your https://github.com/ceph/ceph/pull/46719 was targeted at the ceph:quincy branch so didn't get carried forward. i updated https://tracker.ceph.com/issues/63684 with reef and squid backport tags

cc @ivancich since you were looking into this

**Review by cbodley — APPROVED** [review]

**Comment by prazumovsky** [comment]
Reef backport is here: https://github.com/ceph/ceph/pull/56004. Do I need to make squid backport as well? @cbodley

**Comment by cbodley** [comment]
> Reef backport is here: #56004. Do I need to make squid backport as well? @cbodley

thanks @prazumovsky, but let's test and merge this to main first. backports should use 'cherry-pick -x' so the commit message references the commit hash that merged to main (see https://github.com/ceph/ceph/blob/main/SubmittingPatches-backports.rst#cherry-picking-rules)

**Comment by prazumovsky** [comment]
Does this PR ready to be merged now?

**Pull request merged**
