### PR TITLE
DNM: kraken: An OSD was seen getting ENOSPC even with osd_failsafe_full_ratio passed

### PR DESCRIPTION
**Pull request by shinobu-x**
http://tracker.ceph.com/issues/19340

### CODE REVIEW

**Comment by dzafman** [comment]
Commit d972938ddcb105245f0cb174b58bc172c37c22d2 only needs to mention one sha1 that was the commit in master.
(cherry picked from commit f7723e5.............)

**Comment by shinobu-x** [comment]
@dzafman Got you.

**Comment by shinobu-x** [comment]
retest this please

**Comment by shinobu-x** [comment]
@dzafman would you review again when you get a chance?

**Comment by dzafman** [comment]
Needs rebase

**Comment by shinobu-x** [comment]
There were conflicts suggested by GitHub as below.
Since there was nothing new related to any contexts which could cause mis-behaviour in code pathes (e.g., params, methods, whatever), I modified conflicts manually.

```
> <<<<<<< wip-15912-kraken
> 	  msg = "ENOSPC from disk filesystem, misconfigured cluster";
> =======
> 	  msg = "ENOSPC handling not implemented";
> >>>>>>> kraken
```

**Comment by smithfarm** [comment]
@shinobu-x When github reports conflicts, the proper way to fix that is via `git rebase`. Assuming `git remote -v` says:

```
ceph    https://github.com/ceph/ceph.git (fetch)
ceph    https://github.com/ceph/ceph.git (push)
```

then the commands you would enter are:

```
git fetch ceph
git checkout  wip-15912-kraken
git rebase ceph/kraken
```

(But this won't work now - you would need to remove your manual fix 3857906 first)

**Comment by shinobu-x** [comment]
@smithfarm Thanks for your suggestion. I will follow you.

**Pull request closed without merging**
