### PR TITLE
osd: Hash Index path lookup perf/memory improvement

### PR DESCRIPTION
**Pull request by varadakari**
Using static array to convert uint32_t key to string components
removing the need of sprintf.
path component strings are directly pushed into to path, reducing string allocations,
vector operations and removing loop iteration to populate path_component vector.

Signed-off-by: Varada Kari <varada.kari@sandisk.com>

### CODE REVIEW

**Comment by varadakari** [comment]
Haven't measured the performance completely, seen some small improvement though!(measured through rdtsc for 300 sec run of fio)

**Comment by varadakari** [comment]
Did a rados bench for 120 secs run with and without optimizations on single osd.
There are the results in microsecs using rdtsc
Without the change:
Num of iterations(lookup calls): 246437
Total time spent(microsecs): 6601064

With the change:
Num of iterations(lookup calls): 234572
Total time spent(microsecs): 5136205

**Comment by varadakari** [comment]
@yuyuyu101 @liewegas could you please review the changes?

**Comment by liewegas** [comment]
Can you rebase this on master please?

**Comment by varadakari** [comment]
@liewegas Rebased to the recent master. Please review the changes.

**Comment by liewegas** [comment]
does not build,

os/filestore/HashIndex.cc: In member function 'virtual int HashIndex::_lookup(const ghobject_t&, std::vector >*, std::string*, int*)':
error: os/filestore/HashIndex.cc:393:53: 'hardlink' was not declared in this scope
return get_mangled_name(*path, oid, mangled_name, hardlink);
^
warning: os/filestore/HashIndex.cc:394:1: control reaches end of non-void function [-Wreturn-type]
}
^

**Comment by varadakari** [comment]
@liewegas Sorry, there was parameter name change. Fixed it now. Please review.

**Comment by liewegas** [comment]
2016-02-03T15:24:41.556 INFO:teuthology.orchestra.run.mira030.stdout:test/objectstore/store_test.cc:2417: Failure
2016-02-03T15:24:41.556 INFO:teuthology.orchestra.run.mira030.stdout:Value of: listed.size() == created.size()
2016-02-03T15:24:41.556 INFO:teuthology.orchestra.run.mira030.stdout:  Actual: false
2016-02-03T15:24:41.557 INFO:teuthology.orchestra.run.mira030.stdout:Expected: true
2016-02-03T15:24:41.557 INFO:teuthology.orchestra.run.mira030.stderr:listed.size() is 327 and created.size() is 10000
2016-02-03T15:24:41.569 INFO:teuthology.orchestra.run.mira030.stderr:2016-02-03 23:24:41.569530 7fd1dde56500  1 journal close store_test_temp_journal
2016-02-03T15:24:41.572 INFO:teuthology.orchestra.run.mira030.stdout:==> rm -r store_test_temp_dir
2016-02-03T15:24:41.625 INFO:teuthology.orchestra.run.mira030.stdout:[  FAILED  ] ObjectStore/StoreTest.HashCollisionTest/1, where GetParam() = "filestore" (91693 ms)

**Comment by liewegas** [comment]
ceph_test_objectstore --gtest_filter=ObjectStore/StoreTest.HashCollisionTest/1

**Comment by liewegas** [comment]
This is buggy...

**Comment by varadakari** [comment]
will fix the problems and reopen this PR.

**Pull request closed without merging**
