### PR TITLE
mimic: qa: install python36-{cephfs,rados} instead of python34-*

### PR DESCRIPTION
**Pull request by tchaikov**
http://tracker.ceph.com/issues/39237

### CODE REVIEW

**Comment by tchaikov** [comment]
@b-ranto actually, i am concerned about this change. as our users would be forced to switch their python34 based stack to python36 one for upgrading to a newer Ceph mimic.

i think, we have two options

1. to enforce python34 on pre-octopus releases. as you might know, `python-srpm-macros-3-22.el7` is the last release that use python34. see https://src.fedoraproject.org/cgit/rpms/python-rpm-macros.git/commit/?h=epel7. and we are not likely to install `python-srpm-macros-3-22.el7` from the EPEL7 mirrors anymore for building pre-octopus releases.
2. to start using `python3_other_*` macros for building **both** python34 and python36 packages.

what do you think?

**Comment by b-ranto** [comment]
@tchaikov I was hoping we could use `python3-{cephfs,rados}` after we added the latest `Provides:`. I get your concern about switching from `python34` to `python36` in a stable release but that is a change epel made for us and  the recommended way to deal with it from epel is to rebuild everything and use `python36` everywhere. As long as we properly test the change with teuthology, I think we should be fine.

btw: If the note at the end of https://fedoraproject.org/wiki/User:Bkabrda/EPEL7_Python3#Guidelines is right, then you should only use `python3_other_pkgversion` when going from an older to a newer pkg version but we are already past that point in epel.

**Comment by tchaikov** [comment]
changelog

- cherry-picked the PendingReleaseNotes from #27490

**Comment by yuriw** [comment]
[wip-yuri4-testing-2019-04-09-1656-mimic](https://trello.com/c/i09gJmMj/586-wip-yuri4-testing-2019-04-09-1656-mimic)

**Comment by yuriw** [comment]
built OK
https://shaman.ceph.com/builds/ceph/wip-yuri4-testing-2019-04-10-2015-mimic/

**Comment by yuriw** [comment]
@kchiu see this run http://pulpito.ceph.com/yuriw-2019-04-10_22:50:46-rados-wip-yuri4-testing-2019-04-10-2015-mimic-distro-basic-smithi/

**Comment by tchaikov** [comment]
@yuriw i added "qa/tasks/ceph_deploy: install python3.6 instead of python3.4 for py3 " to address this issue

**Pull request merged**
