### PR TITLE
fix 'rados ls' issue if using keyvaluestore as objectstore backend

### PR DESCRIPTION
**Pull request by xinxinsh**
Fixes: #12637

Signed-off-by: xinxin shu <xinxin.shu@intel.com>

### CODE REVIEW

**Comment by liewegas** [comment]
Hrm?  That doesn't seem right. Why would this fix KeyValueStore?  I don't think is_min() should be true for anything other than hobject_t() ...

**Comment by xinxinsh** [comment]
@liewegas , i agreed that is_min() shoud be true only if object is hobject_t(), but https://github.com/ceph/ceph/blob/master/src/os/GenericObjectMap.cc#L1060, the object type is ghobject_t, in ghobject_t.is_min(), it will check if generation is equal,  in https://github.com/ceph/ceph/blob/master/src/osd/PGBackend.cc#L111, the generation is set to 0,  so ghobject_t.is_min() is false, then assert fails.  other codes that call is_min is by hobject_t.

**Comment by yuyuyu101** [comment]
@liewegas I think we should modify (https://github.com/ceph/ceph/blob/master/src/osd/PGBackend.cc#L111) line, it should be NO_GEN and NO_SHARD or 0 and shard_id. Do you think so?

**Comment by liewegas** [comment]
On Thu, 6 Aug 2015, xinxin shu wrote:
> @liewegas , i agreed that is_min() shoud be true only if object is hobject_t(), but
> https://github.com/ceph/ceph/blob/master/src/os/GenericObjectMap.cc#L1060, the object type is ghobject_t, in ghobject_t.is_min(), it will check
> if generation is equal, in https://github.com/ceph/ceph/blob/master/src/osd/PGBackend.cc#L111, the generation is set to 0, so ghobject_t.is_min()
> is false, then assert fails. other codes that call is_min is by hobject_t.

Can we fix this instead by changing PGBackend.cc to do

 ghobject_t _next;
 if (!begin.is_min)
   _next = ghobject_t(begin, 0, get_parent()->whoami_shard().shard);

?

**Comment by xinxinsh** [comment]
@liewegas ， updated

**Comment by liewegas** [comment]
It fixes the problem?

**Comment by xinxinsh** [comment]
@liewegas , yes, i build a smaller cluster , it works well

**Comment by liewegas** [comment]
I'm going to cherry-pick this into wip-newstore-sort, which is about to go through the test suite!

**Pull request closed without merging**
