### PR TITLE
mimic: qa/tests - added pg log settings to luminous-x, rados/upgrade

### PR DESCRIPTION
**Pull request by yuriw**
Fixes: https://github.com/ceph/ceph/pull/24308
Signed-off-by: Yuri Weinstein <yweinste@redhat.com>

- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by yuriw** [comment]
http://pulpito.ceph.com/yuriw-2018-11-05_23:34:37-upgrade:luminous-x-mimic-distro-basic-smithi

http://pulpito.front.sepia.ceph.com:80/yuriw-2018-11-05_23:36:16-rados:upgrade:luminous-x-singleton-mimic-distro-basic-smithi/

**Comment by yuriw** [comment]
[wip-yuri-testing-2018-11-07-2043-mimic](https://trello.com/c/ke06H7NU/465-wip-yuri-testing-2018-11-07-2043-mimic)

**Comment by yuriw** [comment]
DNM per @jdurgin till this is fixed http://tracker.ceph.com/issues/36686

**Comment by neha-ojha** [comment]
Replaced by https://github.com/ceph/ceph/pull/26206/commits/e89cdfcc52f7309be869434d1ee425528f03727f

**Comment by neha-ojha** [comment]
closing in favor of https://github.com/ceph/ceph/pull/26206

**Pull request closed without merging**
