### PR TITLE
qa: snap_schedule test debugging

### PR DESCRIPTION
**Pull request by batrick**
Signed-off-by: Patrick Donnelly <pdonnell@redhat.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by batrick** [comment]
https://pulpito.ceph.com/pdonnell-2021-03-24_03:53:29-fs-wip-pdonnell-testing-20210324.014451-distro-basic-smithi/

@vshankar with #40353, this cleaned up pretty well but there are still some racy failures. I don't have time to presently debug those failures but this PR should help. I think we can merge this as-is.

**Comment by vshankar** [comment]
> @vshankar with #40353, this cleaned up pretty well but there are still some racy failures. I don't have time to presently debug those failures but this PR should help. I think we can merge this as-is.

Sure. I'll take a look soon.

**Comment by batrick** [comment]
https://pulpito.ceph.com/pdonnell-2021-03-24_23:26:35-fs-wip-pdonnell-testing-20210324.190252-distro-basic-smithi/

- https://tracker.ceph.com/issues/49500
    qa: "Assertion `cb_done' failed."
- https://tracker.ceph.com/issues/50019
    qa: mount failure with cephadm "probably no MDS server is up?"
- https://tracker.ceph.com/issues/50020
    qa: "RADOS object not found (Failed to operate read op for oid cephfs_mirror)"
- https://tracker.ceph.com/issues/48773
    qa: scrub does not complete
- https://tracker.ceph.com/issues/45434
    qa: test_full_fsync (tasks.cephfs.test_full.TestClusterFull) failed
- https://tracker.ceph.com/issues/48805
    mds: "cluster [WRN] Scrub error on inode 0x1000000039d (/client.0/tmp/blogbench-1.0/src/blogtest_in) see mds.a log and `damage ls` output for details"
- https://tracker.ceph.com/issues/48772
    qa: pjd: not ok 9, 44, 80
- https://tracker.ceph.com/issues/50021
    qa: snaptest-git-ceph failure during mon thrashing
- https://tracker.ceph.com/issues/48771
    qa: iogen: workload fails to cause balancing
- https://tracker.ceph.com/issues/50016
    qa: test_damage: "RuntimeError: 2 mutations had unexpected outcomes"
- https://tracker.ceph.com/issues/49466
    qa: "Command failed on gibba030 with status 1: 'set -ex\nsudo dd of=/tmp/tmp.ZEeZBasJer'"

**Comment by batrick** [comment]
Good to merge.

**Comment by batrick** [comment]
https://pulpito.ceph.com/pdonnell-2021-04-01_00:45:34-fs-wip-pdonnell-testing-20210331.222326-distro-basic-smithi/

- https://tracker.ceph.com/issues/48772
    qa: pjd: not ok 9, 44, 80
- https://tracker.ceph.com/issues/50177
    osd: "stalled aio... buggy kernel or bad device?"
- https://tracker.ceph.com/issues/48771
    qa: iogen: workload fails to cause balancing
- https://tracker.ceph.com/issues/49845
    qa: failed umount in test_volumes
- https://tracker.ceph.com/issues/48773
    qa: scrub does not complete
- https://tracker.ceph.com/issues/48805
    mds: "cluster [WRN] Scrub error on inode 0x1000000039d (/client.0/tmp/blogbench-1.0/src/blogtest_in) see mds.a log and `damage ls` output for details"
- https://tracker.ceph.com/issues/50178
    qa: "TypeError: run() got an unexpected keyword argument 'shell'"
- https://tracker.ceph.com/issues/45434
    qa: test_full_fsync (tasks.cephfs.test_full.TestClusterFull) failed

**Comment by batrick** [comment]
ping @vshankar

**Comment by vshankar** [comment]
> ping @vshankar

will take a look.

**Review by vshankar — APPROVED** [review]
LGTM

**Pull request merged**
