### PR TITLE
msg/async: connect authorizer fix + recv_buf size

### PR DESCRIPTION
**Pull request by idryomov**

### CODE REVIEW

**Comment by yuyuyu101** [comment]
cool, I have poor know on auth .... Good catch.

**Comment by yuyuyu101** [comment]
minor: ssize_t AsyncConnection::handle_connect_msg(ceph_msg_connect &connect, bufferlist &authorizer_bl,  bufferlist &authorizer_reply) has local variable named "authorizer_bl", plz change any of these.

**Comment by idryomov** [comment]
@yuyuyu101 Will do.  Do you agree with the MIN -> MAX change - I assume it was a typo?

**Comment by yuyuyu101** [comment]
@idryomov yep, the change makes sense

**Comment by idryomov** [comment]
@yuyuyu101 Updated.

**Comment by yuyuyu101** [comment]
@idryomov BTW I hope you can create a tracker issue to prepare backport this..

**Comment by tchaikov** [comment]
needs rebase?

**Comment by idryomov** [comment]
Rebased.  @yuyuyu101 Can we merge this?

**Comment by yuyuyu101** [comment]
I will put this on my next testing

**Comment by yuyuyu101** [comment]
passed http://pulpito.ceph.com/haomai-2016-07-13_02:16:37-rados-wip-haomai-testing-distro-basic-vps/

**Pull request merged**
