### PR TITLE
common/StackStringStream: don't reserve before every insert

### PR DESCRIPTION
**Pull request by idryomov**

### CODE REVIEW

**Comment by batrick** [comment]
>  Reserving the exact number of elements before every append is harmful: vector will likely reallocate each time and grow linearly instead of geometrically.

Are you saying the vector will just resize exactly to whatever you `reserve`? This seems counter to all of what I've read elsewhere but it wouldn't surprise me.

**Comment by idryomov** [comment]
Yes, reserve() is allowed to reallocate exactly to whatever you ask for and will typically do so. 
Implementations assume that reserve() is called for a reason, i.e. because the caller wants that exact capacity.

A range insert() at the end is guaranteed to preserve geometric growth.

**Comment by liewegas** [comment]
@neha-ojha @jdurgin this!

**Comment by batrick** [comment]
We still want to merge this but I want to note here that it does not resolve http://tracker.ceph.com/issues/36182

````
2018-10-25T02:56:01.322 INFO:tasks.ceph.osd.0.smithi200.stderr:2018-10-25 02:56:01.314 7f7094d66700 -1 osd.0 25 get_health_metrics reporting 2 slow ops, oldest is osd_op(mds.0.16:3 2.1 2.a12255 (undecoded) ondisk+retry+read+known_if_redirected+full_force e24)
2018-10-25T02:56:01.552 INFO:tasks.ceph.osd.1.smithi200.stderr:2018-10-25 02:56:01.546 7fc8a52a9700 -1 osd.1 25 get_health_metrics reporting 4 slow ops, oldest is osd_op(mds.0.16:4 2.2 2.4b2c82a6 (undecoded) ondisk+retry+read+known_if_redirected+full_force e23)
````

See: `/ceph/teuthology-archive/pdonnell-2018-10-24_23:40:49-fs-wip-pdonnell-testing-20181024.213729-distro-basic-smithi/3180794/teuthology.log`

**Pull request merged**
