### PR TITLE
rgw: maintain bucket instance xattrs during successful & cancelled reshard

### PR DESCRIPTION
**Pull request by ivancich**
With the new resharding code, some bucket metadata that is stored as xattrs (e.g., ACLs, life-cycle policies) were not sent with the updated bucket instance data when resharding completed. As a result, resharding has a regression where that metadata is lost after a successful reshard.
    
The first commit restores the variable in the RGWBucketReshard class that maintains the bucket attributes, so they can be saved when the bucket instance object is updated.

There appears to be a long-standing bug in RGW such that when resharding is cancelled and the bucket instance is updated to reflect the new resharding status, the xattrs were lost. The xattrs are used to store metadata such as ACLs and LifeCycle policies.
    
The second commit makes sure that all call paths that lead to a cancelled reshard provide the xattrs, so they can be included when the bucket instance info is updated.

Additionally, @cbodley contributed tests.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [x] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [x] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by cbodley** [comment]
not compiling yet, but it looks like the right approach 👍 

can you please pull in the commit from https://github.com/ceph/ceph/pull/44643 so we can verify this branch in teuthology? we'll want to merge them at the same time

**Review by cbodley — APPROVED** [review]

**Comment by cbodley** [comment]
builds pending in https://shaman.ceph.com/builds/ceph/pr-44788/

**Comment by ivancich** [comment]
I've heard that this fix may work for manual resharding but not dynamic resharding. I've added the DNM label until I can look into this.

**Comment by ivancich** [comment]
My own testing appears to show that it does work with dynamic resharding. I'm waiting for further information from the reporter.

**Comment by mattbenjamin** [comment]
> My own testing appears to show that it does work with dynamic resharding. I'm waiting for further information from the reporter.

yay

**Comment by cbodley** [comment]
first qa run failed with `Not found or unloadable (MGR_MODULE_ERROR)` errors in https://pulpito.ceph.com/cbodley-2022-01-28_18:51:25-rgw-pr-44788-distro-default-smithi/

i added the fix and rescheduled in https://pulpito.ceph.com/cbodley-2022-01-31_18:53:37-rgw-pr-44788-distro-default-smithi/

**Comment by ivancich** [comment]
jenkins test make check

**Comment by cbodley** [comment]
pushed to wip-rgw-multisite-reshard, thanks

**Pull request closed without merging**
