### PR TITLE
test: gtest/gtest.h file not found with <angled> include; use "quotes" instead

### PR DESCRIPTION
**Pull request by Liuchang0812**
build pass

Signed-off-by: liuchang0812 <liuchang0812@gmail.com>

### CODE REVIEW

**Comment by wjwithagen** [comment]
@Liuchang0812 
I have not come accross this at all whilest compiling with Clang.
So what do you do to get these warnings?
- extra options??

**Comment by Liuchang0812** [comment]
@wjwithagen 

hi, wjwithagen, it's a semantic code analysis. I have used [woboq](https://woboq.com/)  create a Ceph online source browser that gives above warns. 

http://ceph.liuchang0812.com/src/test/test_rgw_admin_opstate.cc.html#43

image

**Comment by wjwithagen** [comment]
@Liuchang0812 
Oke I understand now....
Does this tool understand that there is an extra `-I .....` to point to the place where googletest stuff is?
like: `-I/home/wjw/Ceph/work.new/ceph/src/googletest/googletest/include`
So I would not consider this to be worth changing, as it functions as it is designed, but that is just me...

**Comment by Liuchang0812** [comment]
@wjwithagen 

yes, it knows all building options.  it needs CMake's "-DCMAKE_EXPORT_COMPILE_COMMANDS=ON" for those informations.

<angled> is used for system library, "quote" is used for custom library. I prefer to apply this changes to ceph . :smiley:

**Comment by Liuchang0812** [comment]
I close it now. we could reopen it if we need this.

**Pull request closed without merging**
