### PR TITLE
mgr/cephadm: cleanup daemon keyring on failed daemon deploy

### PR DESCRIPTION
**Pull request by sebastian-philipp**
Fixes: https://tracker.ceph.com/issues/48164
Signed-off-by: Sebastian Wagner <sebastian.wagner@suse.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Review by jmolmo — APPROVED** [review]
LGTM

**Comment by sebastian-philipp** [comment]
https://pulpito.ceph.com/swagner-2021-02-04_11:24:34-rados:cephadm-wip-swagner4-testing-2021-02-03-1650-distro-basic-smithi/
https://pulpito.ceph.com/swagner-2021-02-05_09:14:24-rados:cephadm-wip-swagner4-testing-2021-02-03-1650-distro-basic-smithi/

* https://tracker.ceph.com/issues/49190

**Comment by sebastian-philipp** [comment]
jenkins test make check

**Comment by sebastian-philipp** [comment]
jenkins test make check

**Comment by sebastian-philipp** [comment]
regression: https://tracker.ceph.com/issues/49872

**Pull request merged**
