### PR TITLE
Trino/RGW alignments  & adding JSON queries to s3tests

### PR DESCRIPTION
**Pull request by galsalomon66**
- Trino gains efficiency upon issuing multiple requests per single Query. the return results by RGW should be aligned with Trino expectations (otherwise queries are rejected or results are not accurate).
- upon aggregation statement (count) Trino pushes down a *non* aggregation statement, which retrieves an empty column. Trino issue parallel multiple s3select-requests, it seems that deviation in the result relates to the number of parallel requests.
- adding JSON queries to s3-tests https://github.com/ceph/s3-tests/pull/506
- [Trino integration with s3select](https://issues.redhat.com/browse/RGW-265)

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [x] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [x] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [x] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by galsalomon66** [comment]
http://pulpito.front.sepia.ceph.com/gsalomon-2023-03-14_05:29:32-rgw:verify-json_s3tests_and_more-distro-default-smithi/

all test_s3select had passed successfully (parser issue resolved)

there is a valgrind issue to resolve
`Conditional jump or move depends on uninitialized value(s)`

**Comment by galsalomon66** [comment]
http://pulpito.front.sepia.ceph.com/gsalomon-2023-03-14_18:56:53-rgw:verify-json_s3tests_and_more-distro-default-smithi/

all tests had passed successfully

**Comment by galsalomon66** [comment]
http://pulpito.front.sepia.ceph.com/gsalomon-2023-04-05_15:15:25-rgw:verify-json_s3tests_and_more-distro-default-smithi/

12 had passed, 12 had failed 
the `test_progress_expressions` had failed the test.

**Comment by galsalomon66** [comment]
https://github.com/ceph/s3-tests/pull/506/commits/bc2a3b0b705277e313b4b13532a921d5599ed167 
http://pulpito.ceph.com/gsalomon-2023-04-09_12:06:08-rgw:verify-json_s3tests_and_more-distro-default-smithi/
 
6 tests had failed : `test_progress_expressions`  for incorrect progress:byteScanned calculation

**Comment by cbodley** [comment]
> all jobs had failed. the jobs did not reach s3select s3tests

thanks, i opened https://tracker.ceph.com/issues/59423 to track this

**Comment by galsalomon66** [comment]
http://pulpito.front.sepia.ceph.com/gsalomon-2023-05-01_10:25:32-rgw:verify-json_s3tests_and_more-distro-default-smithi/

all jobs had failed
wrong `Progress-byte-scanned-calculation`

**Comment by galsalomon66** [comment]
https://pulpito.ceph.com/gsalomon-2023-05-01_15:23:57-rgw:verify-json_s3tests_and_more-distro-default-smithi/

3(of 6) had passed with success 
all s3select tests had passed with success (fixed bug)

there are **valgrind** issues not **related to s3select stack**

**Comment by cbodley** [comment]
> there are **valgrind** issues not **related to s3select stack**

https://tracker.ceph.com/issues/59490 maybe?

**Comment by galsalomon66** [comment]
> > there are **valgrind** issues not **related to s3select stack**
> 
> https://tracker.ceph.com/issues/59490 maybe?
yes, it's identical to one of the call stacks.(there are also `D3nDataCache` calls)

**Comment by galsalomon66** [comment]
http://pulpito.front.sepia.ceph.com/gsalomon-2023-05-06_04:06:24-rgw:verify-json_s3tests_and_more-distro-default-smithi/

15 had passed with success(out of 24)
all 24 s3select tests had passed with success
the valgrind issues are not related to s3select.

**Comment by galsalomon66** [comment]
http://pulpito.front.sepia.ceph.com/gsalomon-2023-05-07_19:42:54-rgw:verify-json_s3tests_and_more-distro-default-smithi/

all 24 s3select tests had passed with success
no failures related to s3select changes

**Comment by galsalomon66** [comment]
jenkins test make check

**Comment by galsalomon66** [comment]
https://pulpito.ceph.com/gsalomon-2023-05-09_15:06:47-rgw-json_s3tests_and_more-distro-default-smithi/

55 had passed with success (out of 69)
all s3select tests had passed with success

**Review by cbodley — APPROVED** [review]

**Pull request merged**
