### PR TITLE
qa: fix keystone in rgw/crypt/barbican.yaml

### PR DESCRIPTION
**Pull request by alimaredia**
## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by alimaredia** [comment]
@tobias-urdin here is the latest run in teuthology. I ran the crypt suite with the same version of keystone as in the tempest suite: http://qa-proxy.ceph.com/teuthology/amaredia-2023-07-17_20:37:05-rgw:crypt-main-distro-default-smithi/7342409/teuthology.log

**Comment by tobias-urdin** [comment]
@alimaredia I've verified that you indeed need to run atleast Python 3.8 available on c8s/RHEL 8 but recommend Python 3.9 on c9s/RHEL 9 since that is the targeted runtime for the 2023.1 release. Looks like that job ran on RHEL 8 based with Python 3.6

**Comment by tobias-urdin** [comment]
Hello @alimaredia – this PR plus the below patch and running it on Ubuntu 22.04 Jammy or CentOS Stream 9 should make it pass.

```
diff --git a/qa/tasks/barbican.py b/qa/tasks/barbican.py
index 70bd734053a..771304fba92 100644
--- a/qa/tasks/barbican.py
+++ b/qa/tasks/barbican.py
@@ -136,9 +136,8 @@ def set_authtoken_params(ctx, cclient, cconfig):
                         ['sed', '-i',
                          '/[[]filter:authtoken]/{p;s##'+'auth_uri = {}'.format(url)+'#;}',
                          'etc/barbican/barbican-api-paste.ini'])
-    admin_host, admin_port = ctx.keystone.admin_endpoints[keystone_role]
-    admin_url = 'http://{host}:{port}/v3'.format(host=admin_host,
-                                                 port=admin_port)
+    admin_url = 'http://{host}:{port}/v3'.format(host=public_host,
+                                                 port=public_port)
     run_in_barbican_dir(ctx, cclient,
                         ['sed', '-i',
                          '/[[]filter:authtoken]/{p;s##'+'auth_url = {}'.format(admin_url)+'#;}',
```

**Comment by alimaredia** [comment]
@tobias-urdin thank you! That fix did work. I verified it on centos 9 and ubuntu 22.04:

Centos latest run: https://pulpito.ceph.com/amaredia-2023-08-03_16:51:32-rgw:crypt-main-distro-default-smithi/

Ubunutu latest run: https://pulpito.ceph.com/amaredia-2023-08-03_19:23:02-rgw:crypt-main-distro-default-smithi/

@cbodley for the time being can I pin the crypt suite to one of those 2 distros so that the subsuite will be fully green and then work out fixes on earlier centos and ubuntus?

**Comment by cbodley** [comment]
> @cbodley for the time being can I pin the crypt suite to one of those 2 distros so that the subsuite will be fully green and then work out fixes on earlier centos and ubuntus?

sure, just make sure we create a new tracker to work through issues on the other distros

**Comment by alimaredia** [comment]
Opened up this tracker issue and assigned it to myself to make sure the two suites that use keystone are not pinned to `ubuntu_latest` anymore:

https://tracker.ceph.com/issues/62324

**Comment by alimaredia** [comment]
jenkins test make check

**Comment by alimaredia** [comment]
jenkins test make check

**Comment by cbodley** [comment]
thanks @alimaredia @tobias-urdin! i moved https://tracker.ceph.com/issues/61772 to pending-backport

**Pull request merged**
