### PR TITLE
mgr: add messenger policies for different message types

### PR DESCRIPTION
**Pull request by cfanz**
Different throttlers are used in mgr, but they are all bound to the
default policy. Thus only the last bound throttler will act and 
undertake all throttle works despite the type of message.

To make different throttlers work as expected, corresponding policies
should be added, just like what monitor or mds does.

Fixes: https://tracker.ceph.com/issues/56675
Signed-off-by: songxinying <songxinying.ftd@gmail.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by kamoltat** [comment]
@cfanz Can please amend the commit message to the proper format:

```
mgr: add messenger policies for different message types

<description of the problem>

<solution to the problem>

Fixes:
Signed-off-by:
```

Also, put that in the PR description as well.

**Comment by kamoltat** [comment]
jenkins test windows

**Comment by cfanz** [comment]
> @cfanz Can please amend the commit message to the proper format:
> 
> ```
> mgr: add messenger policies for different message types
> 
> <description of the problem>
> 
> <solution to the problem>
> 
> Fixes:
> Signed-off-by:
> ```
> 
> Also, put that in the PR description as well.

@kamoltat Done, please recheck, thanks!

**Comment by kamoltat** [comment]
@cfanz I'm not very familiar with this code, so I want to check my understanding of this PR. Basically, the problem was that we did not set a policy for types: MON, OSD, CLIENT, or MDS. Therefore, if let's say a message type MON came through, there is a chance it will not use the values``mon_byte_throttler.get()`` or ``mon_msg_throttler.get()`` leading to all types of messages sharing the same throttle work which leads to throttler to be full.

@neha-ojha can you or anyone from core verify my understanding? Thank you!

**Comment by kamoltat** [comment]
Also, @cfanz since I couldn't find a teuthology run link to the tracker, I'm assuming that you encountered this locally. Is there any way you can paste a snippet of the log that indicates the issue? Or if you can provide a bug reproducer, that will be even better.

**Comment by cfanz** [comment]
> Also, @cfanz since I couldn't find a teuthology run link to the tracker, I'm assuming that you encountered this locally. Is there any way you can paste a snippet of the log that indicates the issue? Or if you can provide a bug reproducer, that will be even better.

@kamoltat I added some logs and analysis and reproduce step at https://tracker.ceph.com/issues/56675?next_issue_id=56672&prev_issue_id=56688

**Pull request closed without merging**
