### PR TITLE
Wip interactive ceph cli

### PR DESCRIPTION
**Pull request by tchaikov**
http://tracker.ceph.com/issues/11279 

Fixes: #11279

### CODE REVIEW

**Comment by dachary** [comment]
@tchaikov it looks great ! Because ceph.in is used intensively in various contexts, it would be good to run a set of qa tests, just to be sure.

Reviewed-by: after a QA run

**Comment by tchaikov** [comment]
@dachary thanks for the review !

**Comment by jecluis** [comment]
This looks sane to me too.

**Comment by tchaikov** [comment]
@jecluis thank you for looking at this PR !

**Pull request merged**
