### PR TITLE
mon/PGMap: calc min_last_epoch_clean when decode

### PR DESCRIPTION
**Pull request by tchaikov**
introduced in 208959a0dcacba40116730702021090a24865eb3
http://tracker.ceph.com/issues/13112 Fixes: #13112, 

Signed-off-by: Kefu Chai <kchai@redhat.com>

### CODE REVIEW

**Comment by dachary** [comment]
@tchaikov I'm not sure how the failure can be related with your change.
<pre>
../qa/workunits/ceph-helpers.sh:800: objectstore_tool:  ceph-objectstore-tool --data-path testdir/osd-scrub-repair/1 --journal-path testdir/osd-scrub-repair/1/journal SOMETHING remove
remove 1:2/847441d7/SOMETHING/head
common/Mutex.cc: In function 'void Mutex::Lock(bool)' thread 2b9bc3517700 time 2015-09-16 08:43:02.421793
common/Mutex.cc: 105: FAILED assert(r == 0)
 ceph version 9.0.3-1679-g1f22687 (1f226872b371a0d4f8376478af26a31a80fd8a76)
 1: (ceph::__ceph_assert_fail(char const*, char const*, int, char const*)+0x8b) [0x2b9bbbc5822b]
 2: (Mutex::Lock(bool)+0x19c) [0x2b9bbbc1832c]
 3: (FileStore::_journaled_ahead(FileStore::OpSequencer*, FileStore::Op*, Context*)+0x1ea) [0x2b9bbba7feca]
 4: (Context::complete(int)+0x9) [0x2b9bbb7ed969]
 5: (Finisher::finisher_thread_entry()+0x158) [0x2b9bbbba1518]
 6: (()+0x8182) [0x2b9bbef2d182]
 7: (clone()+0x6d) [0x2b9bc085247d]
 NOTE: a copy of the executable, or `objdump -rdS <executable>` is needed to interpret this.
terminate called after throwing an instance of 'ceph::FailedAssertion'
*** Caught signal (Aborted) **
</pre>
but it's the first time I'm seing this. Would you mind re-pushing to trigger another run and confirm it's a false negative ?

**Comment by tchaikov** [comment]
@dachary rebased and repushed.

**Comment by dachary** [comment]
@tchaikov thanks, filed http://tracker.ceph.com/issues/13113 to track that should it happen again

**Comment by liewegas** [comment]
sigh.. annoying we missed this.  Reviewed-by:

**Comment by liewegas** [comment]
Can we adjust the unit test to catch this case?

**Comment by tchaikov** [comment]
> Can we adjust the unit test to catch this case?

will do.

**Comment by tchaikov** [comment]
@liewegas test added

**Comment by liewegas** [comment]
@tchaikov we shoudl backport this to hammer, yeah?

**Comment by tchaikov** [comment]
@liewegas yes. http://tracker.ceph.com/issues/13112 is now pending backport.

**Pull request merged**
