### PR TITLE
doc/release-notes: kraken release notes (draft)

### PR DESCRIPTION
**Pull request by liewegas**
Signed-off-by: Sage Weil <sage@redhat.com>

### CODE REVIEW

**Comment by theanalyst** [comment]
ack

**Comment by yuyuyu101** [comment]
@liewegas 

"The OSDs now quiesce scrubbing when recovery or rebalancing is in progress."

OPTION(osd_scrub_during_recovery, OPT_BOOL, true) // Allow new scrubs to start while recovery is active on the OSD

I think by default value is true which keep the same behavior. do we need to change to false to match your thought?

**Comment by liewegas** [comment]
Oh, right.  Hmm, perhaps we should make it default false, actually--I 
think that's probably the best behavior?

**Comment by xiexingguo** [comment]
> Oh, right. Hmm, perhaps we should make it default false, actually--I think that's probably the best behavior?

Agree!

**Comment by liewegas** [comment]
ttps://github.com/ceph/ceph/pull/12402

**Pull request merged**
