### PR TITLE
cls/queue: add unit tests

### PR DESCRIPTION
**Pull request by yuvalif**
Signed-off-by: Yuval Lifshitz <yuvalif@yahoo.com>

2 code issue was found by UT and fixed in the 2 commits of this review

### CODE REVIEW

**Comment by pritha-srivastava** [comment]
looks good to me.

**Comment by yuvalif** [comment]
> looks good to me.

thanks. could you please approve?

**Comment by pritha-srivastava** [comment]
#33372 - referencing this PR here, the second commit needs to be reviewed before it goes in.

**Comment by yuvalif** [comment]
> #33372 - referencing this PR here, the second commit needs to be reviewed before it goes in.

@pritha-srivastava since your PR is merged, I removed the commit, rebased and pushed

**Pull request merged**
