### PR TITLE
tests: sync ceph-erasure-code-corpus for using 'arch' not 'uname -p'

### PR DESCRIPTION
**Pull request by tchaikov**
Signed-off-by: Kefu Chai <kchai@redhat.com>

### CODE REVIEW

**Comment by wjwithagen** [comment]
@tchaikov 
If this part is called from FreeBSD it will now fail, due to FreeBSD not having `arch(1)`

**Comment by tchaikov** [comment]
@wjwithagen, i don't have a FreeBSD env around. could you enlighten me on how to enable FreeBSD to detect the arch?

**Comment by wjwithagen** [comment]
@tchaikov 
arch detection is thru uname(1):
```
     -m      Write the type of the current hardware platform to standard out-
             put.
     -p      Write the type of the machine processor architecture to standard
             output.
```
Both return amd64 on my platform (or i386 on the older platforms).
And it is part of the basetools.

Alternative is to use sysctl(1), also in basetools:
kern.supported_archs: amd64 i386
hw.machine: amd64
hw.machine_arch: amd64
hw.snd.version: 2009061500/amd64

**Comment by tchaikov** [comment]
@wjwithagen `uname -p` does not work on archlinux and debian. it returns "unknown". sysctl is used to set kernel param at runtime on GNU/Linux. probably it's different from that on FreeBSD? could you share me the exact command line?

**Pull request merged**
