### PR TITLE
ceph-volume: update the OS before deploying Ceph

### PR DESCRIPTION
**Pull request by guits**
ceph-volume tests are failing, OSDs never get up and running. For some reason, updating the OS early in the testing workflow addresses that issue in the CI.

-- to be continued ... --

### CODE REVIEW

**Comment by guits** [comment]
jenkins test centos8-bluestore-create

**Comment by guits** [comment]
jenkins test lvm centos8-bluestore-create

**Review by asm0deuz — APPROVED** [review]
LGTM

**Comment by guits** [comment]
jenkins test ceph-volume lvm centos8-bluestore-prepare_activate

**Comment by guits** [comment]
jenkins test ceph-volume lvm centos8-bluestore-dmcrypt

**Comment by guits** [comment]
jenkins test ceph-volume lvm centos8-bluestore-create

**Comment by guits** [comment]
jenkins test api

**Pull request merged**
