### PR TITLE
mon: Monitor: set MMonJoin's op type as service

### PR DESCRIPTION
**Pull request by jecluis**
Otherwise, when the MonmapMonitor's PaxosService::dispatch() handles the
message, it will assert (as it should) because the op is marked as being
a monitor op. And this function should never handle monitor ops.

`Signed-off-by: Joao Eduardo Luis <joao@suse.de>`

### CODE REVIEW

**Comment by jecluis** [comment]
This is the proper fix for the behavior #5454 was meant to fix. #5454 does fix it, but it's fixing a symptom rather than the cause, and we must not allow PaxosService::dispatch() handle monitor ops -- instead, we must make sure the ops are properly marked as being service ops.

**Comment by tchaikov** [comment]
@jecluis test added. tested locally. and i believe it's a safe change

LGTM.

**Comment by jecluis** [comment]
@tchaikov In the future, running even a 'safe change' like this through a monthrash suite would be advisable. Just to make sure this doesn't have unexpected side-effects.

**Comment by tchaikov** [comment]
i see, will run a monthrash suite next time.

**Pull request merged**
