### PR TITLE
doc: rgw: Fixed bug on wrong name for user_id for OPA

### PR DESCRIPTION
**Pull request by clwluvw**

### CODE REVIEW

**Comment by theanalyst** [comment]
missing a signed-off-by, and while at it, it'd be great if you could amend the commit title like the PR title https://github.com/ceph/ceph/blob/master/SubmittingPatches.rst#sign-your-work 
This can be done by amending the commit and then force-pushing

**Comment by clwluvw** [comment]
Done

**Comment by clwluvw** [comment]
I don't have any idea why tests failed when docs edited :confused:

**Comment by cbodley** [comment]
the test failures are from SSHOrchestrator and should be fixed in https://github.com/ceph/ceph/pull/31969. can you try rebasing over the current master branch?

**Comment by clwluvw** [comment]
I have rebased it with master but still tests fails!

**Comment by cbodley** [comment]
jenkins test make check

**Comment by clwluvw** [comment]
Tests passed :heavy_check_mark:

**Pull request merged**
