### PR TITLE
doc: removed OpenStack Kilo references in Keystone docs

### PR DESCRIPTION
**Pull request by falcon78921**
- [x] References tracker ticket
- [x] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

Removed Kilo references in Keystone docs. Updated documentation
to align with Ocata & later releases.

Fixes: https://tracker.ceph.com/issues/38721
Signed-off-by: James McClune <jmcclune@mcclunetechnologies.net>

### CODE REVIEW

**Comment by falcon78921** [comment]
jenkins render docs

**Comment by falcon78921** [comment]
See: http://docs.ceph.com/ceph-prs/27203/radosgw/keystone/

**Comment by tchaikov** [comment]
@sebastian-philipp could you please help review this change?

**Comment by falcon78921** [comment]
Thanks! @tchaikov @sebastian-phillip :)

**Pull request merged**
