### PR TITLE
quincy: win32_deps_build: avoid pip

### PR DESCRIPTION
**Pull request by petrutlucian94**
backport tracker: https://tracker.ceph.com/issues/59479

---

backport of https://github.com/ceph/ceph/pull/50916
backport of https://github.com/ceph/ceph/pull/48147
parent tracker: https://tracker.ceph.com/issues/59354

this backport was staged using ceph-backport.sh version 16.0.0.6848
find the latest version at https://github.com/ceph/ceph/blob/master/src/script/ceph-backport.sh

### CODE REVIEW

**Review by idryomov — COMMENTED** [review]
This happens to be pulling in some of https://github.com/ceph/ceph/pull/48147?  If so, let's cherry pick both commits from there explicitly.

**Comment by petrutlucian94** [comment]
By the way, memstore keeps crashing with a seg fault: https://tracker.ceph.com/issues/61416. I think we may have to switch to bluestore.

**Review by idryomov — COMMENTED** [review]
- Commits "win32: install wget when building on ubuntu" and "win32: install deps with DEBIAN_FRONTEND=noninteractive" need to be swapped so that they come in the same order as in https://github.com/ceph/ceph/pull/48147 to spare noise in the diff context.
- Commit "win32_deps_build: avoid pip" had a conflict with a resolution of dropping a diff hunk, right?  The "Conflicts" marker generated by git should have been uncommented and an explanation along the lines of "commit 4954fe19e559 ("win32: add rhel option") not in quincy" added.

The end result would be the same so this is more about following good backporting practices than anything else ;)

**Comment by petrutlucian94** [comment]
> * Commits "win32: install wget when building on ubuntu" and "win32: install deps with DEBIAN_FRONTEND=noninteractive" need to be swapped so that they come in the same order as in [win32: ubuntu platform build fixes #48147](https://github.com/ceph/ceph/pull/48147) to spare noise in the diff context.
> * Commit "win32_deps_build: avoid pip" had a conflict with a resolution of dropping a diff hunk, right?  The "Conflicts" marker generated by git should have been uncommented and an explanation along the lines of "commit [4954fe1](https://github.com/ceph/ceph/commit/4954fe19e5594ca5cac1d639fcfa49941abbbfa9) ("win32: add rhel option") not in quincy" added.
> 
> The end result would be the same so this is more about following good backporting practices than anything else ;)

Good point, thanks! I've updated the PR.

**Comment by petrutlucian94** [comment]
jenkins test api

**Review by idryomov — APPROVED** [review]

**Pull request merged**
