### PR TITLE
mgr/dashboard: Remove the "Last change" column in Pools table

### PR DESCRIPTION
**Pull request by avanthakkar**
Removing the "Last change" column from the Pool table, as info is already visible in the Pool's details and it's not a relevant info to be exposed in the table
 
Fixes: https://tracker.ceph.com/issues/47807

Signed-off-by: Avan Thakkar <athakkar@redhat.com>

Before:
Screenshot from 2020-10-21 21-26-31

After:
Screenshot from 2020-10-21 21-23-09

## Checklist
- [x] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by nizamial09** [comment]
@avanthakkar Small suggestion -> Change the title to `mgr/dashboard: Remove the "Last change" column in Pools table` to add a bit more context. Maybe in the commit title too.

**Comment by avanthakkar** [comment]
> @avanthakkar Small suggestion -> Change the title to `mgr/dashboard: Remove the "Last change" column in Pools table` to add a bit more context. Maybe in the commit title too.

Done!

**Review by nizamial09 — APPROVED** [review]
LGTM! Thanks

**Review by alfonsomthd — APPROVED** [review]

**Review by tspmelo — APPROVED** [review]

**Review by epuertat — APPROVED** [review]
Looks good. Could you please add B&A screenshots to the PR summary? Thanks @avanthakkar !

**Comment by avanthakkar** [comment]
> Looks good. Could you please add B&A screenshots to the PR summary? Thanks @avanthakkar !

Done!

**Pull request merged**
