### PR TITLE
nautilus: core: Give recovery for inactive PGs a higher priority

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/39504

### CODE REVIEW

**Comment by smithfarm** [comment]
@dzafman OK, I'm running that standalone test in a build tree, but it seems to be stuck in a wait_for_clean loop, with messages like these repeated, seemingly endlessly:

```
...
.../qa/standalone/ceph-helpers.sh:1543: wait_for_clean:  get_num_pgs
.../qa/standalone/ceph-helpers.sh:1319: get_num_pgs:  ceph --format json status
.../qa/standalone/ceph-helpers.sh:1319: get_num_pgs:  jq .pgmap.num_pgs
../qa/standalone/ceph-helpers.sh:1543: wait_for_clean:  test 0 == 0
../qa/standalone/ceph-helpers.sh:1544: wait_for_clean:  sleep 1
.../qa/standalone/ceph-helpers.sh:1543: wait_for_clean:  get_num_pgs
.../qa/standalone/ceph-helpers.sh:1319: get_num_pgs:  ceph --format json status
.../qa/standalone/ceph-helpers.sh:1319: get_num_pgs:  jq .pgmap.num_pgs
../qa/standalone/ceph-helpers.sh:1543: wait_for_clean:  test 0 == 0
../qa/standalone/ceph-helpers.sh:1544: wait_for_clean:  sleep 1
.../qa/standalone/ceph-helpers.sh:1543: wait_for_clean:  get_num_pgs
.../qa/standalone/ceph-helpers.sh:1319: get_num_pgs:  ceph --format json status
.../qa/standalone/ceph-helpers.sh:1319: get_num_pgs:  jq .pgmap.num_pgs
../qa/standalone/ceph-helpers.sh:1543: wait_for_clean:  test 0 == 0
../qa/standalone/ceph-helpers.sh:1544: wait_for_clean:  sleep 1
...

**Comment by smithfarm** [comment]
@dzafman typescript of test output https://gist.github.com/smithfarm/41001b4b2a2f59adb409f6bc04ee34f4

**Comment by dzafman** [comment]
@smithfarm check_pool_priority() isn't a test, but rather a common function for the 5 tests: 
TEST_pool_pos_only_prio TEST_pool_neg_only_prio TEST_pool_both_prio TEST_pool_both_prio_no_neg TEST_pool_both_prio_no_pos

So the following will run all the tests:

../qa/run-standalone.sh osd-pool-create.sh TEST_pool_pos_only_prio TEST_pool_neg_only_prio TEST_pool_both_prio TEST_pool_both_prio_no_neg TEST_pool_both_prio_no_pos

**Comment by smithfarm** [comment]
@dzafman This time the test seemed to pass, but I'm confused by the output. I captured it all here: https://gist.github.com/smithfarm/584789ffba4921455afee7611f14dec4

First, I thought it was supposed to run just the 5 tests mentioned on the command line, but instead it seems to run *all* the tests in `osd-pool-create.sh`.

Second, I expected the last line to read "ALL 5 TESTS PASSED" but instead it says "ALL 1 TESTS PASSED"?

**Comment by dzafman** [comment]
@smithfarm Oops, I missed the double quotes that are needed.   But you ran all the test cases in that test, so it passed.  This is the correct syntax:

../qa/run-standalone.sh "test1.sh TEST_subtest1 TEST_subtest5" "test2.sh TEST_s2 TEST_s8" ....
Output for passing this run would be "ALL 2 TESTS PASSED" for this example.

So I should have said:

../qa/run-standalone.sh "osd-pool-create.sh TEST_pool_pos_only_prio TEST_pool_neg_only_prio TEST_pool_both_prio TEST_pool_both_prio_no_neg TEST_pool_both_prio_no_pos"

**Comment by yuriw** [comment]
[wip-yuri6-testing-2019-05-07-2112-nautilus](https://trello.com/c/yR9GnUT6/610-wip-yuri6-testing-2019-05-07-2112-nautilus)

**Pull request merged**
