### PR TITLE
rgw: fix default_placement containing "/" when storage_class is standard

### PR DESCRIPTION
**Pull request by mkogan1**
The user default placement contains an extraneous slash:
`"default_placement": "/" `
and the zonegroup defaut placement contains a trailing slash
` "default_placement": "default-placement/",`

```
radosgw-admin --keyring=/etc/ceph/keyring-store/keyring --mon-host=$ROOK_CEPH_MON_HOST --name=client.radosgw.gateway  metadata get user:cosbench
"default_placement": "/" 
-------------------->^^^

radosgw-admin --keyring=/etc/ceph/keyring-store/keyring --mon-host=$ROOK_CEPH_MON_HOST --name=client.radosgw.gateway  zonegroup get
{
    "placement_targets": [
        {
            "name": "default-placement",
            "tags": []
        }
    ],
    "default_placement": "default-placement/",
------------------------------------------>^
    "realm_id": "52539210-99bc-449b-9bae-00e60bd5064a" 
}
```

fixes: http://tracker.ceph.com/issues/39380

Signed-off-by: mkogan1 <mkogan@redhat.com>

- [x] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by cbodley** [comment]
@mkogan1 i agree with @yehudasa that `from_str()` should clear `storage_class` in the cases where it isn't assigned, ie:
```diff
diff --git a/src/rgw/rgw_common.h b/src/rgw/rgw_common.h
index 8ff03a554d..8ca2d1722c 100644
--- a/src/rgw/rgw_common.h
+++ b/src/rgw/rgw_common.h
@@ -721,12 +721,11 @@ struct rgw_placement_rule {
     size_t pos = s.find("/");
     if (pos == std::string::npos) {
       name = s;
+      storage_class.clear();
       return;
     }
     name = s.substr(0, pos);
-    if (pos < s.size() - 1) {
-      storage_class = s.substr(pos + 1);
-    }
+    storage_class = s.substr(pos + 1);
   }
 
   bool standard_storage_class() const {
```

**Comment by ivancich** [comment]
Pulpito results:
http://pulpito.ceph.com/ivancich-2019-04-23_19:53:03-rgw-wip-eric-testing-1-distro-basic-smithi/
http://pulpito.ceph.com/ivancich-2019-04-23_19:52:23-rgw-wip-eric-testing-1-distro-basic-smithi/

**Comment by ivancich** [comment]
@cbodley @yehudasa @mattbenjamin This passed my QA. It still needs a review, though....

**Comment by ivancich** [comment]
@mkogan1 What do you think of Yehuda's comment?

**Comment by mkogan1** [comment]
@cbodley @ivancich @yehudasa @mattbenjamin  Thank you very much, checked on a branch with additional logging and it looks OK.

**Comment by cbodley** [comment]
jenkins test make check

**Comment by mkogan1** [comment]
jenkins test make check

**Comment by ivancich** [comment]
jenkins test docs

**Comment by theanalyst** [comment]
Passed http://pulpito.ceph.com/abhi-2019-05-11_08:17:09-rgw-wip-abhi2-testing-2019-05-10-1803-distro-basic-smithi/

**Pull request merged**
