### PR TITLE
examples/librados: Makefile

### PR DESCRIPTION
**Pull request by zhanghe9702**
fix make error, make cpp target will failed because the old c++ standard compile param
`../../src/include/rados/buffer.h:866:6: error: init-statement in selection statements only available with ‘-std=c++17’ or ‘-std=gnu++17’ [-Werror]`
Signed-off-by: zhanghe9702@163.com

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by tchaikov** [comment]
could you add a "`Signed-off-by`" line at the end of your commit message? "git commit -s" will do the trick for you. see https://github.com/ceph/ceph/blob/master/SubmittingPatches.rst#sign-your-work. specifically, your Signed-off-by line reads

```
Signed-off-by: zhanghe9702@163.com
```
while it's required that the format of Signed-off-by line looks like
```
Signed-off-by: He Zhang <zhanghe9702@163.com>
```

assuming your first name is He, and last name is Zhang.

**Review by tchaikov — APPROVED** [review]

**Comment by tchaikov** [comment]
jenkins test make check

**Comment by tchaikov** [comment]
@rzarzynski i believe the FTBFS which is supposed to be fixed by this change is caused by https://github.com/ceph/ceph/blob/bd85f2c1c5bd4073566c8806788da7c4e9501a0c/src/include/buffer.h#L868. the bigger question is: shall we be C++11 compatible when it comes to librados. as the _init-statement_ in the `if` statement was introduced in C++17.

**Comment by rzarzynski** [comment]
@tchaikov: Hello Kefu!

> the bigger question is: shall we be C++11 compatible when it comes to librados

This is a very good question. In the past we declared C++11 dependency and we even got a teuthology task that is supposed to verify that. AFAIK nothing has changed since then. Therefore the C++17 in `buffer.h` is a bug.

However, the situation spurs another question I don't have a response to: is guaranteeing nothing-above-C++11 is a good idea in 2022?

**Comment by rzarzynski** [comment]
@zhanghe9702: do we have a tracker for the C++11 buildability issue?

**Comment by zhanghe9702** [comment]
> AFAIK

:), no tracker for it, i am just build a ceph cluster from source code, then test librados client and found this problem.

**Comment by rzarzynski** [comment]
> :), no tracker for it, i am just build a ceph cluster from source code, then test librados client and found this problem.

OK, will create. The crux is we need to backport the fix and the tracking is useful here.

**Comment by tchaikov** [comment]
> 
> However, the situation spurs another question I don't have a response to: is guaranteeing nothing-above-C++11 is a good idea in 2022?

good q.. personally, i think the requirement of C++17 is fair. but probably everything has exception(s). 8-(

**Pull request closed without merging**
