### PR TITLE
octopus: mgr/dashboard: ECP modal enhancement

### PR DESCRIPTION
**Pull request by callithea**
backport tracker: https://tracker.ceph.com/issues/45370

---

backport of https://github.com/ceph/ceph/pull/34448
parent tracker: https://tracker.ceph.com/issues/44621

this backport was staged using ceph-backport.sh version 15.1.1.389
find the latest version at https://github.com/ceph/ceph/blob/master/src/script/ceph-backport.sh

### CODE REVIEW

**Comment by callithea** [comment]
jenkins test dashboard

**Comment by Devp00l** [comment]
jenkins test dashboard

**Comment by callithea** [comment]
jenkins test dashboard

**Comment by yuriw** [comment]
[wip-yuri2-testing-2020-06-15-1645-octopus](https://trello.com/c/h9HO5XLe/937-wip-yuri2-testing-2020-06-15-1645-octopus)

**Pull request merged**
