### PR TITLE
Wip 12983

### PR DESCRIPTION
**Pull request by dzafman**
This also includes a change which fixes a false "Bad hash" if chunks are read out of order.

### CODE REVIEW

**Comment by dachary** [comment]
@dzafman this is another occurrence of http://tracker.ceph.com/issues/13176. If you re-push you will most likely not hit it.

**Comment by dzafman** [comment]
An assert was hit with a diagnostic version of this branch proving I've found the issue.  Re-running with the test with this branch.

**Comment by liewegas** [comment]
The 'Bad has' message triggered twice on my wip-sage-testing runt hat included this:

/a/sage-2015-09-24_20:43:22-rados-wip-sage-testing---basic-multi/1067946
/a/sage-2015-09-24_20:43:22-rados-wip-sage-testing---basic-multi/1068002

**Comment by dzafman** [comment]
@liewegas Since I can't find the sha1 for the runs above I checked the current wip-sage-testing.  It does NOT include the commit with the fix (e6ccd4af231f5c14284bf6ea88dc41cca9b3287f)   Also, looking at all the osd logs for the runs above I never see the following text "Remove hinfo_key from".  I have a passing run where that message was produce many times.

**Comment by liewegas** [comment]
I pushed wip-sage-testing-before to github.com/liewegas/ceph, which 
appears to contain e6ccd4a

**Comment by dzafman** [comment]
I reviewed @athanatos version of the changes and they look good.  Fixes an issue I introduced in one of my commits and implements the other in a better way.

**Comment by athanatos** [comment]
Oops, david fixed it, reopening.

**Comment by athanatos** [comment]
Tested, good to merge.  We should probably get a review other than mine and david's.

**Comment by liewegas** [comment]
lgtm

**Comment by liewegas** [comment]
merged manually to infernalis

**Pull request closed without merging**
