### PR TITLE
luminous: mon: High MON cpu usage when cluster is changing

### PR DESCRIPTION
**Pull request by xiaoxichen**
http://tracker.ceph.com/issues/23912

luminous: backport  PR #21605

### CODE REVIEW

**Comment by theanalyst** [comment]
there is one more commit in the master pr that isn't present here, is that intentional

**Comment by liewegas** [comment]
If you mean "messages/MOSDMap: fix compat_version for MOSDMap" then yeah, that was a fix for a bug introduced during the mimic dev cycle.

**Comment by theanalyst** [comment]
ack, thanks

**Comment by yuriw** [comment]
[wip-yuri-testing-2018-06-06-1207-luminous](https://trello.com/c/qM70OGgc/320-wip-yuri-testing-2018-06-06-1207-luminous)

**Comment by smithfarm** [comment]
@yuriw Did this get run through `upgrade/jewel-x` as @liewegas requested?

**Pull request merged**
