### PR TITLE
librbd: aio calls may block

### PR DESCRIPTION
**Pull request by dillaman**
http://tracker.ceph.com/issues/11769

### CODE REVIEW

**Comment by dillaman** [comment]
Passed RBD teuthology suite

**Comment by dachary** [comment]
@dillaman it would be good to have comments in the commit messages regarding conflict resolution (reminder ;-)

**Comment by smithfarm** [comment]
@dachary @dillaman wrote that this PR has already passed an RBD suite, but in view of its complexity should we put it in the next integration test round so it gets tested some more?

**Comment by dachary** [comment]
@dillaman would you be so kind as to rebase & re-push this PR so that it triggers the make check bot ? I do not remember why I changed to DNM, I suspect it's just because it failed compilation in the integration branch. But I failed to mention the reason for the change.

**Comment by dillaman** [comment]
@dachary Rebased and pushed.  @smithfarm This fix is actually already available within the downstream Red Hat Ceph Storage 1.2.x product, so the sooner we can get it in upstream, the better in my humble opinion.

**Comment by dachary** [comment]
@dillaman is the patch id of all the commits the same ? How much testing did it see ?

**Comment by smithfarm** [comment]
@dillaman: JFYI the tracker issue says "DNM until Josh provides +1"

**Comment by dillaman** [comment]
@jdurgin Thoughts?

**Comment by smithfarm** [comment]
(We will run integration tests on this before merging it in any case.)

**Comment by dachary** [comment]
@dillaman @smithfarm my concern here is to avoid having a significant amount of commits that look like they are different in hammer and in another context (redhat or suse product), because of tiny differences that change the patch id. For all intent and purposes such commits are the same but from the point of view of a tool, they are different (git cherry will find them different) and it takes a human being to compare them and decide the difference is not significant.

If the commits that exist elsewhere did not see much testing and have not been released yet, the commits from this pull request could probably just be used to replace them. If the commits that exist elsewhere have been extensively tested, and if their patch-id is different, it is very little effort to update this pull request with them (replace the current ones), for the sake of having a clean history.

Hopefully that clarifies a little the context in which I asked "is the patch id of all the commits the same ? How much testing did it see ? ".

Sorry for being so terse ;-)

**Comment by dachary** [comment]
All but two commits have the same patch-id in v0.80.8.2. The reason for these divergences are explained in the "reconciliation between firefly and v0.80.8.2" mail on ceph-devel.

**Comment by dachary** [comment]
@smithfarm no further comment, all is well :-)

**Comment by jdurgin** [comment]
No problems from this in master. Looks good to me once it passes through the rbd suite. Generally you can assume that for trivial backports, or ones with just trivial conflicts, I'm fine with merging them after an rbd suite run.

**Comment by smithfarm** [comment]
jdurgin: it passed the rbd suite. OK to merge?

**Comment by jdurgin** [comment]
@smithfarm yup, lgtm

**Pull request merged**
