### PR TITLE
doc/releases/octopus.rst: format tweaks

### PR DESCRIPTION
**Pull request by tchaikov**
it's a regression introduced by 26db06cf212be029e5628a40de3410632c0b86a0

Signed-off-by: Kefu Chai <kchai@redhat.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by tchaikov** [comment]
jenkins render docs

**Comment by liewegas** [comment]
retest this please

**Comment by tchaikov** [comment]
jenkins render docs

**Comment by tchaikov** [comment]
see 

- https://docs.ceph.com/docs/master/cephadm/#deploying-osds
- https://docs.ceph.com/ceph-prs/33971/cephadm/#deploying-osds

**Comment by tchaikov** [comment]
jenkins test make check

**Comment by tchaikov** [comment]
jenkins render docs

**Comment by liewegas** [comment]
retest this please

**Pull request merged**
