### PR TITLE
pacific: common: Use double instead of long double to improve performance

### PR DESCRIPTION
**Pull request by rosinL**
To convert namoseconds to seconds, the precision needs to be 10, and the precision of double is 15, which is enough to use. On aarch64, double division uses the div instruction, while long double uses the gcc buildin _divtf3, which has poor performance. Therefore, use double instead of long double for better performance.

backport tracker: https://tracker.ceph.com/issues/61475

Signed-off-by: Chunsong Feng <fengchunsong@huawei.com>
Signed-off-by: luo rixin <luorixin@huawei.com>
(cherry picked from commit 58753cf50e89cc3d7169447aa83d13cd3a8c0347)

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by rosinL** [comment]
jenkins retest this please

**Comment by markhpc** [comment]
@rosinL Any chance you have any performance or perf data showing an improvement (even cycles/op) for the change?

**Comment by rosinL** [comment]
Hi @markhpc, we have tested on aarch64, we get about 1% performance(IOPS) improvement for 4k randwrite.

**Review by markhpc — APPROVED** [review]
LGTM

**Comment by rosinL** [comment]
Can we merge this? @markhpc @rzarzynski

**Review by rzarzynski — APPROVED** [review]

**Comment by rzarzynski** [comment]
The main PR has been merged in 2021: https://github.com/ceph/ceph/pull/42082.

**Comment by rzarzynski** [comment]
@rosinL: one purely organization thing: may we get-or-create a ticket for tracing?

**Comment by rosinL** [comment]
> 

I have added a backport tracker https://tracker.ceph.com/issues/61475. Would you help to update the tracker status?

**Comment by rosinL** [comment]
> @rosinL: one purely organization thing: may we get-or-create a ticket for tracing?

I have added a backport tracker https://tracker.ceph.com/issues/61475. Would you help to update the tracker status?

**Comment by ljflores** [comment]
Rados suite review: https://tracker.ceph.com/projects/rados/wiki/PACIFIC#httpstrellocomcqQnRTrLO1792-wip-yuri8-testing-2023-06-22-1309-pacific-old-wip-yuri8-testing-2023-06-22-1004-pacific-old-wip-yuri8-testing-2023-06-22-0834-pa

**Pull request merged**
