### PR TITLE
jewel: mds: enforce a dirfrag limit on entries

### PR DESCRIPTION
**Pull request by xiaoxichen**
http://tracker.ceph.com/issues/16560

### CODE REVIEW

**Comment by dachary** [comment]
@xiaoxichen I'm setting milestone jewel since this is targeting jewel really. If that's a mistake please let me know.

**Comment by dachary** [comment]
@jcsp does this backport look good to merge ? It passed the fs suite http://tracker.ceph.com/issues/16344#note-21 (except for unrelated valgrind failures and one transient failure that is, I believe, unrelated ).

**Comment by gregsfortytwo** [comment]
This looks okay to me on a skim but hopefully Patrick can sign-off on this since John's on vacation another week.

**Comment by gregsfortytwo** [comment]
@batrick ^

**Comment by batrick** [comment]
`Reviewed-by: Patrick Donnelly <pdonnell@redhat.com>`

**Pull request merged**
