### PR TITLE
cmake: bump liburing from 0.7 to 2.5

### PR DESCRIPTION
**Pull request by tchaikov**
this allows us to use newer liburing features. Seastar is using some of them which are not provided by liburing 0.7. v2.5 is the latest release of liburing at the time of writing.

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Comment by cbodley** [comment]
hopefully we can just rely on system packages once we drop focal and centos 8 support?

https://packages.ubuntu.com/jammy/liburing-dev
https://centos.pkgs.org/9-stream/centos-crb-x86_64/liburing-devel-2.3-2.el9.x86_64.rpm.html

**Review by cbodley — APPROVED** [review]

**Comment by tchaikov** [comment]
yeah, I think so. The Builduring.cmake script was added to address the missing liburing on ancient distro releases.

**Comment by tchaikov** [comment]
changelog

- pass `--use-libc` to `configure` to address following FTBFS

```
CMake Error at /home/jenkins-build/build/workspace/ceph-pull-requests/build/liburing_ext-prefix/src/liburing_ext-stamp/liburing_ext-build-Debug.cmake:37 (message):
  Command failed: 2

   '/usr/bin/gmake' 'CFLAGS= -fPIC' '-C' 'src' '-s'

  See also

    /home/jenkins-build/build/workspace/ceph-pull-requests/build/liburing_ext-prefix/src/liburing_ext-stamp/liburing_ext-build.log


-- Log output is:
ar: creating liburing.a
ar: creating liburing-ffi.a
/usr/bin/ld: register.os: in function `io_uring_register_buffers_sparse':
register.c:(.text+0x15b): undefined reference to `memset'
/usr/bin/ld: register.os: in function `io_uring_register_files_sparse':
register.c:(.text+0x2cb): undefined reference to `memset'
/usr/bin/ld: register.os: in function `io_uring_unregister_buf_ring':
register.c:(.text+0xa3b): undefined reference to `memset'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
gmake: *** [Makefile:82: liburing.so.2.5] Error 1
```

**Comment by rosinL** [comment]
Do we need to turn on `WITH_SYSTEM_LIBURING` to use system liburing-dev package ?

**Comment by tchaikov** [comment]
jenkins test make check

**Comment by tchaikov** [comment]
> Do we need to turn on `WITH_SYSTEM_LIBURING` to use system liburing-dev package ?

i think so. it's `OFF` by default.

**Comment by rosinL** [comment]
> > Do we need to turn on `WITH_SYSTEM_LIBURING` to use system liburing-dev package ?
> 
> i think so. it's `OFF` by default.

Turn on `WITH_SYSTEM_LIBURING` in this pr?

**Comment by tchaikov** [comment]
> hopefully we can just rely on system packages once we drop focal and centos 8 support?
> 
> https://packages.ubuntu.com/jammy/liburing-dev https://centos.pkgs.org/9-stream/centos-crb-x86_64/liburing-devel-2.3-2.el9.x86_64.rpm.html

@rosinL why? why is this in the scope of this change? and did we drop the support of these distro?

**Comment by rosinL** [comment]
> > hopefully we can just rely on system packages once we drop focal and centos 8 support?
> > https://packages.ubuntu.com/jammy/liburing-dev https://centos.pkgs.org/9-stream/centos-crb-x86_64/liburing-devel-2.3-2.el9.x86_64.rpm.html
> 
> @rosinL why? why is this in the scope of this change? and did we drop the support of these distro?

No, I mistakenly think we need to use system liburing-dev package according to previous message.

**Comment by tchaikov** [comment]
jenkins test api

**Comment by cbodley** [comment]
> No, I mistakenly think we need to use system liburing-dev package according to previous message.

@rosinL sorry for the confusion. let's follow up on that part once we drop support for focal and centos 8

**Comment by cbodley** [comment]
> ERROR: test_list_enabled_module (tasks.mgr.dashboard.test_mgr_module.MgrModuleTest)

**Comment by cbodley** [comment]
jenkins test api

**Comment by tchaikov** [comment]
changelog:

- updated `make-dist` accordingly.

being built at https://shaman.ceph.com/builds/ceph/wip-pr-55825-kefu/838878cc20486ba1649ce2157ff980dff0d38722/

**Comment by tchaikov** [comment]
jenkins test api

**Comment by cbodley** [comment]
a heads-up for anyone seeing build issues like this:
```
FAILED: liburing_ext-prefix/src/liburing_ext-stamp/liburing_ext-configure /home/ali/ceph/main/build/liburing_ext-prefix/src/liburing_ext-stamp/liburing_ext-configure 
cd /home/ali/ceph/main/build/src/liburing && /usr/bin/cmake -P /home/ali/ceph/main/build/liburing_ext-prefix/src/liburing_ext-stamp/liburing_ext-configure-Debug.cmake && /usr/bin/cmake -E touch /home/ali/ceph/main/build/liburing_ext-prefix/src/liburing_ext-stamp/liburing_ext-configure
CMake Error at /home/ali/ceph/main/build/liburing_ext-prefix/src/liburing_ext-stamp/liburing_ext-configure-Debug.cmake:37 (message):
  Command failed: 1

   'env' 'CC=/usr/lib64/ccache/gcc' 'CXX=/usr/lib64/ccache/g++' '/home/ali/ceph/main/build/src/liburing/configure' '--use-libc'

  See also

    /home/ali/ceph/main/build/liburing_ext-prefix/src/liburing_ext-stamp/liburing_ext-configure.log


-- Log output is:
ERROR: unknown option --use-libc
Try '/home/ali/ceph/main/build/src/liburing/configure --help' for more information

CMake Error at /home/ali/ceph/main/build/liburing_ext-prefix/src/liburing_ext-stamp/liburing_ext-configure-Debug.cmake:47 (message):
  Stopping after outputting logs.
```
you can work around that by deleting that `liburing_ext-prefix` subdirectory to force cmake to clone the updated branch

**Pull request merged**
