### PR TITLE
ceph.in: Add blocking mode for scrub and deep-scrub

### PR DESCRIPTION
**Pull request by badone**
Signed-off-by: Brad Hubbard <bhubbard@redhat.com>

### CODE REVIEW

**Comment by jdurgin** [comment]
this looks good to me. Could you add a couple calls using it to qa/workunits/cephtool/test.sh to make sure it stays working (at least by not crashing)

**Comment by badone** [comment]
Done

**Comment by yuriw** [comment]
[wip-yuri4-testing-2018-01-10-1652](https://trello.com/c/5TGShjFD/227-wip-yuri4-testing-2018-01-10-1652)

**Comment by badone** [comment]
Added updated documentation. Shouldn't affect testing.

**Pull request merged**
