### PR TITLE
I46832 debug

### PR DESCRIPTION
**Pull request by batrick**
https://tracker.ceph.com/issues/46832

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by alfonsomthd** [comment]
jenkins test api

**Comment by ajarr** [comment]
@vshankar 's  ongoing testing,
https://pulpito.ceph.com/vshankar-2020-08-06_11:33:24-fs-wip-pdonnell-testing-20200806.033244-nautilus-distro-basic-smithi/

**Comment by vshankar** [comment]
> @vshankar 's ongoing testing,
> https://pulpito.ceph.com/vshankar-2020-08-06_11:33:24-fs-wip-pdonnell-testing-20200806.033244-nautilus-distro-basic-smithi/

All pass. @batrick @ajarr

**Comment by ajarr** [comment]
@ShyamsundarR ^^

**Comment by batrick** [comment]
https://tracker.ceph.com/issues/46832#note-5

**Pull request closed without merging**
