### PR TITLE
osd/PrimaryLogPG: fix LOST_REVERT on primary

### PR DESCRIPTION
**Pull request by Matan-B**
Commit 3a0467749b6f27a21483de304fde46b03c3836ca introduced pulling old version to revert to in LOST_REVERT:
```
osd: pull old version to revert to
If we are the primary, and are doing a LOST_REVERT, pull the old version
of the object and update the version when we get it.
```
A dedicated `revert` boolean was used under the `if (is_primary())` scope.

Commit 1bf037bf76d0c3f85421657a5aaf8b7478937e02 refactored the push and pull code. The refactor dropped the `revert` boolean and instead asserted that we are primary. The assertion was correct since this bit was moved to `submit_push_complete` which was called in `handle_pull_response` that was called from `sub_op_push` only on *primary*.

Commit 7da308bba0d60b1435cda9698a3320d97050699b moved this logic into the common `on_local_recover`. Now `on_local_recover` was called from `handle_pull_response` not only on *primary*. Therfore, `on_local_recover` included a `is_primary` check in the end since it was called also from non primaries.

However, the LOST_REVERT logic should be used only on primary so we need to bring back the `revert` boolean same as 3a0467749b6f27a21483de304fde46b03c3836ca did.

Fixes:  https://tracker.ceph.com/issues/50608

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Comment by rzarzynski** [comment]
jenkins test api

**Comment by rzarzynski** [comment]
```
2024-05-06 17:24:18,437.437 INFO:__main__:requests.exceptions.ConnectionError: HTTPSConnectionPool(host='172.21.2.16', port=7790): Max retries exceeded with url: /api/mgr/module (Caused by NewConnectionError(': Failed to establish a new connection: [Errno 111] Connection refused'))
```

**Comment by rzarzynski** [comment]
jenkins test api

**Review by athanatos — APPROVED** [review]

**Comment by Matan-B** [comment]
The change itself is correct in way. However it doesn't address the actual bug since the condition: 
```
  if (!is_delete && recovery_state.get_pg_log().get_missing().is_missing(recovery_info.soid) &&
      recovery_state.get_pg_log().get_missing().get_items().find(recovery_info.soid)->second.need > recovery_info.version
```
is expected to be true indeed only on primary.

I will follow up with more logs around this assert to get more information.
Closing until then.

CC: @athanatos

**Pull request closed without merging**
