### PR TITLE
mon/PGMap: Remove unnecessary header

### PR DESCRIPTION
**Pull request by shinobu-x**
Signed-off-by: Shinobu Kinjo <shinobu@redhat.com>

### CODE REVIEW

**Comment by tchaikov** [comment]
could you remove "| cleanup" from the title of your commit message?

**Comment by joscollin** [comment]
@tchaikov Yes, I'm fed up with removing that.

**Comment by shinobu-x** [comment]
test this please

**Comment by tchaikov** [comment]
the failures are either caused by #19117 or tracked by http://tracker.ceph.com/issues/9356 .

**Pull request merged**
