### PR TITLE
hammer: rgw: Setting ACL on Object removes ETag

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/13820

### CODE REVIEW

**Comment by dachary** [comment]
@yehudasa does this backport look good to merge ? It passed a run of the hammer rgw suite ( see http://tracker.ceph.com/issues/13356#note-36 ) except two occurrences of a known subuser bug ( http://tracker.ceph.com/issues/14375).

**Comment by odivlad** [comment]
Hi all!

Today I've tested this patch in our testing environment and it worked, but since I'm not a ceph developer or maintainer, I don't know if it's okay or not. I noticed that "tag" field changed. Furthermore, "ETag" field was concatenated with string: `\u0000`. In amazon ETag doesn't change, when you modify meta or ACL.

object before changing ACL:
```
# radosgw-admin bi list --bucket=eee --object=7127.mp3
[
    {
        "type": "plain",
        "idx": "7127.mp3",
        "entry": {
            "name": "7127.mp3",
            "instance": "",
            "ver": {
                "pool": 9,
                "epoch": 1731
            },
            "locator": "",
            "exists": "true",
            "meta": {
                "category": 1,
                "size": 5853677,
                "mtime": "2016-01-20 20:52:41.000000Z",
                "etag": "5b8a290265f502f38b81340051c2efb5",
                "owner": "4f33e60b-ad60-4dde-803a-bf866f9b3eff",
                "owner_display_name": "user",
                "content_type": "audio\/mp3",
                "accounted_size": 5853677
            },
            "tag": "default.54109.15",
            "flags": 0,
            "pending_map": [],
            "versioned_epoch": 0
        }
    }

]
```

Modify S3 ACL via API:

```
# radosgw-admin bi list --bucket=eee --object=7127.mp3
[
    {
        "type": "plain",
        "idx": "Beep_Long.mp3",
        "entry": {
            "name": "Beep_Long.mp3",
            "instance": "",
            "ver": {
                "pool": 9,
                "epoch": 1704
            },
            "locator": "",
            "exists": "true",
            "meta": {
                "category": 1,
                "size": 17553,
                "mtime": "2016-01-20 22:21:26.000000Z",
                "etag": "d41d8cd98f00b204e9800998ecf8427e\u0000",
                "owner": "4f33e60b-ad60-4dde-803a-bf866f9b3eff",
                "owner_display_name": "user@cloud.croc.ru",
                "content_type": "audio\/mp3\u0000",
                "accounted_size": 17553
            },
            "tag": "_7tO2IrV7EHLtsbudCdACAQ_6Ysx6aYx",
            "flags": 0,
            "pending_map": [],
            "versioned_epoch": 0
        }
    }

]
```

Well, the object's ETag didn't delete, but modified and "tag" and "content_type" are changed (concatenated `\u0000`)

After I modified meta information with `s3cmd modify --add-header`:

```
$ s3cmd modify --add-header='Cache-Control: public' s3://eee/Beep_Long.mp3
File s3://eee/Beep_Long.mp3 modified
$ s3cmd modify --add-header='content-type: 111' s3://eee/Beep_Long.mp3
File s3://eee/Beep_Long.mp3 modified
```

```
# radosgw-admin bi list --bucket=eee --object=7127.mp3
[
    {
        "type": "plain",
        "idx": "Beep_Long.mp3",
        "entry": {
            "name": "Beep_Long.mp3",
            "instance": "",
            "ver": {
                "pool": 9,
                "epoch": 1706
            },
            "locator": "",
            "exists": "true",
            "meta": {
                "category": 1,
                "size": 17553,
                "mtime": "2016-01-20 22:22:09.000000Z",
                "etag": "d41d8cd98f00b204e9800998ecf8427e\u0000",
                "owner": "4f33e60b-ad60-4dde-803a-bf866f9b3eff",
                "owner_display_name": "user@cloud.croc.ru",
                "content_type": "111\u0000",
                "accounted_size": 17553
            },
            "tag": "_sV8L4SCRZLFUWXksQlphYZL312ITgwa",
            "flags": 0,
            "pending_map": [],
            "versioned_epoch": 0
        }
    }

]
```

Same situation. And where is meta (there are no "cache control" and "max-age" variables in the output)?
Though, there are no new symbols in curl output:
```
$ curl -X HEAD -I http://my_s3_server/Beep_Long.mp3
HTTP/1.1 200 OK
Date: Wed, 20 Jan 2016 22:28:36 GMT
Accept-Ranges: bytes
ETag: "d41d8cd98f00b204e9800998ecf8427e"
Cache-Control: public
Content-Length: 17553
Last-Modified: Wed, 20 Jan 2016 22:28:03 GMT
Connection: close
Content-Type: 111
```

Is it an expected behaviour?

**Comment by smithfarm** [comment]
@ovidiad You might want to post your question as an issue in the RGW issue tracker: http://tracker.ceph.com/projects/rgw/issues/new

**Comment by odivlad** [comment]
@smithfarm, okay, thank you.

**Comment by dachary** [comment]
@yehudasa ping ?

**Comment by yehudasa** [comment]
@dachary backport looks good

**Comment by Aran85** [comment]
@yehudasa the acl attr setting will not clear other attrs, they are independent. the PR seems useless...am i wrong?

**Pull request merged**
