### PR TITLE
changes to port part of ceph to osx (part 0 of some)

### PR DESCRIPTION
**Pull request by tchaikov**
based on @ukernel 's work

i will try to update the ceph-fuse to enable it to work on osx again.

### CODE REVIEW

**Comment by wjwithagen** [comment]
@tchaikov 
`ENODATA != ENOATTR` is probably going to raise its nasty head here as well.
But I do not have an MAC to check it.

**Comment by tchaikov** [comment]
@wjwithagen 
it's been take care of by 5db6915d80f2ad5d5bf1896d26060cfac5fdb502

**Comment by wjwithagen** [comment]
@tchaikov 
Are you sure that the ENODATA that is used there is not the ENODATA from the boost lib?
Which would be the case unless APPLE also defines __FreeBSD__.
Otherwise the ENODATA in compat.h needs to be seperated out and also enabled for APPLE.

**Comment by tchaikov** [comment]
@wjwithagen fixed and repushed.

**Comment by wjwithagen** [comment]
@tchaikov 
I'll run it trhu my jenkins-master.

**Comment by wjwithagen** [comment]
@tchaikov 
Jenkins complains at:
    `http://cephdev.digiware.nl:8180/jenkins/job/ceph-master/1209/console`
But I currently have to attend otehr business.
Perhaps I can check what is wrong tonight.

**Comment by wjwithagen** [comment]
@tchaikov 
Log output is full with 
```
/home/jenkins/workspace/ceph-master/src/test/encoding/readable.sh: line 105: 47207 Segmentation fault      (core dumped) $CEPH_DENCODER type $type import $vdir/objects/$type/$f decode dump_json > $tmp1
```
Perhaps I should revert some of the changes to the dencoder-code?

**Comment by tchaikov** [comment]
@wjwithagen i suspect it's c47d4e7, will take a closer look at it this weekend. thanks for reviewing/testing this PR!

**Comment by wjwithagen** [comment]
@tchaikov 
I'll try and revert it, and see if it passes.
Will let you know

**Comment by wjwithagen** [comment]
@tchaikov 
Removing the patch to `msg_types.h` fixes build and testing.

**Comment by tchaikov** [comment]
@wjwithagen fixed and repushed.

**Comment by tchaikov** [comment]
using:

```
PKG_CONFIG_PATH=/usr/local/Cellar/nss/3.31/lib/pkgconfig \
cmake .. -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_COMPILER=clang \
-DWITH_EMBEDDED=OFF -DWITH_MANPAGE=OFF -DWITH_LIBCEPHFS=OFF \
-DWITH_XFS=OFF -DWITH_KRBD=OFF -DWITH_NSS=ON -DWITH_LTTNG=OFF \
-DWITH_BABELTRACE=OFF -DCMAKE_BUILD_TYPE=Debug -DWITH_CCACHE=ON \
-DWITH_RADOSGW=OFF
```

**Comment by wjwithagen** [comment]
@tchaikov 
I'll download the PR.diff and kick off another testrun. 
As always you can check at:
cephdev.digiware.nl:8180/jenkins/job/ceph-master/lastBuild/console

**Comment by tchaikov** [comment]
changelog

- rebased against master

**Comment by tchaikov** [comment]
retest this please.

**Comment by tchaikov** [comment]
http://pulpito.ceph.com/kchai-2017-09-15_19:26:05-rados-wip-kefu-testing-2017-09-16-0123-distro-basic-mira/

**Pull request merged**
