### PR TITLE
mgr/vol: fix flake8 warnings

### PR DESCRIPTION
**Pull request by rishabh-d-dave**
Fix warnings printed by the command "flake8 --select=F,E9
--exclude=venv,.tox src/pybind/mgr/volumes/".

While working with mgr/vol, syntax errors are not printed anywhere. Any
attempt to run vstart.sh after such faulty patch causes vstart.sh to go
in a infinite loop. And running "ceph fs volume" command prints "no such
command exists". This doesn't tell the actual issue and causes
confusion.

When a flake8 is run, the issue is not apparent due to so many warnings.
Therefore, fix these warnings so that it becomes easier to spot such
critical issues here onwards.

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [x] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by rishabh-d-dave** [comment]
https://pulpito.front.sepia.ceph.com/rishabh-2023-11-03_12:04:16-fs:volumes-rishabh-mgr-vol-flake-warnings-testing-default-smithi/

**Comment by rishabh-d-dave** [comment]
https://pulpito.ceph.com/rishabh-2023-11-03_12:04:16-fs:volumes-rishabh-mgr-vol-flake-warnings-testing-default-smithi/

**Comment by rishabh-d-dave** [comment]
https://pulpito.ceph.com/rishabh-2023-11-03_16:41:12-fs:volumes-rishabh-mgr-vol-flake-warnings-testing-default-smithi/

**Comment by rishabh-d-dave** [comment]
jenkins test make check

**Comment by rishabh-d-dave** [comment]
https://jenkins.ceph.com/job/ceph-pull-requests/124900/

**Comment by rishabh-d-dave** [comment]
https://jenkins.ceph.com/job/ceph-api/64607/

**Comment by vshankar** [comment]
jenkins test make check

**Comment by vshankar** [comment]
@rishabh-d-dave please run this through teuthology since an updated has been pushed lately.

**Comment by rishabh-d-dave** [comment]
https://jenkins.ceph.com/job/ceph-pull-requests/124975/

**Comment by rishabh-d-dave** [comment]
https://jenkins.ceph.com/job/ceph-pull-requests/124986/

**Review by mchangir — APPROVED** [review]
LGTM

**Comment by mchangir** [comment]
jenkins test make check

**Review by neesingh-rh — COMMENTED** [review]
We can add this change https://github.com/ceph/ceph/pull/54396/files#r1386317911 into this. Rest LGTM

**Comment by vshankar** [comment]
@rishabh-d-dave ping?

**Comment by rishabh-d-dave** [comment]
@neesingh-rh @vshankar 
> We can add this change https://github.com/ceph/ceph/pull/54396/files#r1386317911 into this. Rest LGTM

I created a separate PR because I wanted this one to be merged sooner.

**Comment by neesingh-rh** [comment]
jenkins test make check

**Comment by rishabh-d-dave** [comment]
https://jenkins.ceph.com/job/ceph-pull-requests/125423/consoleFull#1769453669e840cee4-f4a4-4183-81dd-42855615f2c1

**Comment by rishabh-d-dave** [comment]
https://pulpito.ceph.com/rishabh-2023-11-23_13:33:32-fs:volumes-mgr-vol-misc2-testing-default-smithi/

**Comment by rishabh-d-dave** [comment]
```
2023-11-23T14:31:45.311 INFO:tasks.cephfs_test_runner:======================================================================
2023-11-23T14:31:45.311 INFO:tasks.cephfs_test_runner:ERROR: test_subvolume_group_quota_mds_path_restriction_to_group_path (tasks.cephfs.test_volumes.TestSubvolumeGroups)
2023-11-23T14:31:45.311 INFO:tasks.cephfs_test_runner:Tests subvolumegroup quota enforcement with mds path restriction set to group.
2023-11-23T14:31:45.311 INFO:tasks.cephfs_test_runner:----------------------------------------------------------------------
2023-11-23T14:31:45.311 INFO:tasks.cephfs_test_runner:Traceback (most recent call last):
2023-11-23T14:31:45.311 INFO:tasks.cephfs_test_runner:  File "/home/teuthworker/src/git.ceph.com_ceph-c_90f297b062770cf2d9b04612fd691b6922a8a984/qa/tasks/cephfs/test_volumes.py", line 1129, in test_subvolume_group_quota_mds_path_restriction_to_group_path
2023-11-23T14:31:45.311 INFO:tasks.cephfs_test_runner:    guest_keyring_path = self._configure_guest_auth(
2023-11-23T14:31:45.311 INFO:tasks.cephfs_test_runner:  File "/home/teuthworker/src/git.ceph.com_ceph-c_90f297b062770cf2d9b04612fd691b6922a8a984/qa/tasks/cephfs/test_volumes.py", line 397, in _configure_guest_auth
2023-11-23T14:31:45.311 INFO:tasks.cephfs_test_runner:    guest_mount.client_remote.write_file(guest_keyring_path, keyring_txt,
2023-11-23T14:31:45.311 INFO:tasks.cephfs_test_runner:  File "/home/teuthworker/src/git.ceph.com_teuthology_2442239d2653456406c25ae0c71b689c8f2657b6/teuthology/orchestra/remote.py", line 295, in write_file
2023-11-23T14:31:45.311 INFO:tasks.cephfs_test_runner:    self.run(args=args, stdin=data, quiet=True)
2023-11-23T14:31:45.311 INFO:tasks.cephfs_test_runner:  File "/home/teuthworker/src/git.ceph.com_teuthology_2442239d2653456406c25ae0c71b689c8f2657b6/teuthology/orchestra/remote.py", line 522, in run
2023-11-23T14:31:45.311 INFO:tasks.cephfs_test_runner:    r = self._runner(client=self.ssh, name=self.shortname, **kwargs)
2023-11-23T14:31:45.311 INFO:tasks.cephfs_test_runner:  File "/home/teuthworker/src/git.ceph.com_teuthology_2442239d2653456406c25ae0c71b689c8f2657b6/teuthology/orchestra/run.py", line 455, in run
2023-11-23T14:31:45.312 INFO:tasks.cephfs_test_runner:    r.wait()
2023-11-23T14:31:45.312 INFO:tasks.cephfs_test_runner:  File "/home/teuthworker/src/git.ceph.com_teuthology_2442239d2653456406c25ae0c71b689c8f2657b6/teuthology/orchestra/run.py", line 161, in wait
2023-11-23T14:31:45.312 INFO:tasks.cephfs_test_runner:    self._raise_for_status()
2023-11-23T14:31:45.312 INFO:tasks.cephfs_test_runner:  File "/home/teuthworker/src/git.ceph.com_teuthology_2442239d2653456406c25ae0c71b689c8f2657b6/teuthology/orchestra/run.py", line 181, in _raise_for_status
2023-11-23T14:31:45.312 INFO:tasks.cephfs_test_runner:    raise CommandFailedError(
2023-11-23T14:31:45.312 INFO:tasks.cephfs_test_runner:teuthology.exceptions.CommandFailedError: Command failed on smithi040 with status 1: 'set -ex\nsudo dd of=/tmp/tmp.h1A5IBnHAz'
2023-11-23T14:31:45.312 INFO:tasks.cephfs_test_runner:
2023-11-23T14:31:45.312 INFO:tasks.cephfs_test_runner:----------------------------------------------------------------------
2023-11-23T14:31:45.312 INFO:tasks.cephfs_test_runner:Ran 37 tests in 1923.353s
```

**Comment by rishabh-d-dave** [comment]
https://pulpito.ceph.com/rishabh-2023-11-24_05:41:33-fs:volumes-rishabh-mgr-vol-misc-testing-default-smithi
https://pulpito.ceph.com/rishabh-2023-11-24_07:31:48-fs:volumes-rishabh-mgr-vol-misc-testing-default-smithi

**Comment by rishabh-d-dave** [comment]
https://pulpito.ceph.com/rishabh-2023-11-24_08:24:50-fs:volumes-rishabh-mgr-vol-misc-testing-default-smithi/

**Comment by rishabh-d-dave** [comment]
https://pulpito.ceph.com/rishabh-2023-11-24_16:45:14-fs:volumes-rishabh-mgr-vol-misc-testing-default-smithi/

**Comment by rishabh-d-dave** [comment]
> https://pulpito.ceph.com/rishabh-2023-11-24_16:45:14-fs:volumes-rishabh-mgr-vol-misc-testing-default-smithi/

All tests passed.

**Comment by rishabh-d-dave** [comment]
https://pulpito.ceph.com/rishabh-2023-11-26_06:51:12-fs:volumes-rishabh-mgr-vol-misc-testing-default-smithi/
https://pulpito.ceph.com/rishabh-2023-11-28_12:42:13-fs:volumes-rishabh-mgr-vol-misc-testing-default-smithi/
https://pulpito.ceph.com/rishabh-2023-11-29_11:43:01-fs:volumes-mgr-vol-misc-2023nov3-testing-default-smithi/

**Comment by rishabh-d-dave** [comment]
https://pulpito.ceph.com/rishabh-2023-11-29_12:25:49-fs:volumes-mgr-vol-misc-2023nov3-testing-default-smithi/

Tests ran successfully.

**Review by vshankar — APPROVED** [review]
LGTM

**Pull request merged**
