### PR TITLE
octopus: nfs backport

### PR DESCRIPTION
**Pull request by varshar16**
https://tracker.ceph.com/issues/46401
https://tracker.ceph.com/issues/45953
https://tracker.ceph.com/issues/46003
https://tracker.ceph.com/issues/46106
https://tracker.ceph.com/issues/46085
https://tracker.ceph.com/issues/46155
https://tracker.ceph.com/issues/46156
https://tracker.ceph.com/issues/46292
https://tracker.ceph.com/issues/46291
https://tracker.ceph.com/issues/46290
https://tracker.ceph.com/issues/46289

---

Backport of https://github.com/ceph/ceph/pull/35743, https://github.com/ceph/ceph/pull/35417, https://github.com/ceph/ceph/pull/35739, https://github.com/ceph/ceph/pull/35674 (only test_nfs.py commit 981a7cc), https://github.com/ceph/ceph/pull/35646, https://github.com/ceph/ceph/pull/35724, https://github.com/ceph/ceph/pull/35702, https://github.com/ceph/ceph/pull/35609, https://github.com/ceph/ceph/pull/35649, https://github.com/ceph/ceph/pull/35602, https://github.com/ceph/ceph/pull/35530, https://github.com/ceph/ceph/pull/35344, https://github.com/ceph/ceph/pull/34672, https://github.com/ceph/ceph/pull/32297

~~Note: Don't merge before other nfs pr's are merged in master~~ All required prs are merged in master

### CODE REVIEW

**Comment by varshar16** [comment]
Tests Failed: http://qa-proxy.ceph.com/teuthology/varsha-2020-06-09_15:53:12-rados-wip-octopus-nfs-backport-distro-basic-smithi/

```
2020-06-09T16:07:37.902 ERROR:teuthology.run_tasks:Saw exception from tasks.
Traceback (most recent call last):
  File "/home/teuthworker/src/git.ceph.com_git_teuthology_master/teuthology/run_tasks.py", line 91, in run_tasks
    manager = run_one_task(taskname, ctx=ctx, config=config)
  File "/home/teuthworker/src/git.ceph.com_git_teuthology_master/teuthology/run_tasks.py", line 69, in run_one_task
    task = get_task(taskname)
  File "/home/teuthworker/src/git.ceph.com_git_teuthology_master/teuthology/run_tasks.py", line 33, in get_task
    module = _import('tasks', module_name, task_name, fail_on_import_error=True)
  File "/home/teuthworker/src/git.ceph.com_git_teuthology_master/teuthology/run_tasks.py", line 57, in _import
    0,
  File "/home/teuthworker/src/git.ceph.com_ceph-c_wip-octopus-nfs-backport/qa/tasks/cephadm.py", line 18, in <module>
    from ceph_manager import CephManager
ModuleNotFoundError: No module named 'ceph_manager'
```

**Comment by sebastian-philipp** [comment]
did you run your test with `-teuthology-branch py2`?

**Comment by varshar16** [comment]
> did you run your test with `-teuthology-branch py2`?

No, I ran the test with: `teuthology-suite -v --machine-type smithi --email varao@redhat.com -p 54 --ceph wip-octopus-nfs-backport --suite rados --filter test_orch_cli`

**Comment by sebastian-philipp** [comment]
octopus is still on py2. until @kshtsk merges his PR.

**Comment by varshar16** [comment]
Tests have failed again due incompatibility with python2.
http://qa-proxy.ceph.com/teuthology/varsha-2020-06-10_08:05:10-rados-wip-octopus-nfs-backport-distro-basic-smithi/
```
2020-06-10T08:20:50.852 ERROR:teuthology.run_tasks:Saw exception from tasks.
Traceback (most recent call last):
  File "/home/teuthworker/src/git.ceph.com_git_teuthology_py2/teuthology/run_tasks.py", line 90, in run_tasks
    manager.__enter__()
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/home/teuthworker/src/git.ceph.com_ceph-c_wip-octopus-nfs-backport/qa/tasks/cephfs_test_runner.py", line 166, in task
    module_suites.append(decorating_loader.loadTestsFromName(mod_name))
  File "/home/teuthworker/src/git.ceph.com_ceph-c_wip-octopus-nfs-backport/qa/tasks/cephfs_test_runner.py", line 36, in loadTestsFromName
    result = super(DecoratingLoader, self).loadTestsFromName(name, module)
  File "/usr/lib/python2.7/unittest/loader.py", line 91, in loadTestsFromName
    module = __import__('.'.join(parts_copy))
  File "/home/teuthworker/src/git.ceph.com_git_teuthology_py2/virtualenv/local/lib/python2.7/site-packages/gevent/builtins.py", line 96, in __import__
    result = _import(*args, **kwargs)
  File "/home/teuthworker/src/git.ceph.com_ceph-c_wip-octopus-nfs-backport/qa/tasks/cephfs/test_nfs.py", line 81
    res = self._sys_cmd(['rados', '-p', 'nfs-ganesha', '-N', self.cluster_id, 'get', f'export-{export_id}', '-'])
                                                                                                         ^
SyntaxError: invalid syntax
```

**Comment by kshtsk** [comment]
> octopus is still on py2. until @kshtsk merges his PR.

yeah... till that, the backporting means make it py2 compatible

**Comment by varshar16** [comment]
Thanks @sebastian-philipp and @kshtsk 
Tests have passed after making it py2 compatible .
http://qa-proxy.ceph.com/teuthology/varsha-2020-06-10_09:22:37-rados-wip-octopus-nfs-backport-distro-basic-smithi/

**Comment by batrick** [comment]
@varshar16 note that @tchaikov has announced octopus is now py3 compatible.

**Comment by batrick** [comment]
jenkins test dashboard backend

**Comment by batrick** [comment]
jenkins test docs

**Comment by varshar16** [comment]
Tests are failing due to image pull error.
```
70318dea2197d181f2f159675e21fd1017447: unable to pull image: Error initializing source docker://quay.io/ceph-ci/ceph:0e570318dea2197d181f2f159675e21fd1017447: Error reading manifest 0e570318dea2197d181f2f159675e21fd1017447 in quay.io/ceph
-ci/ceph: manifest unknown: manifest unknown
```
 http://qa-proxy.ceph.com/teuthology/varsha-2020-06-23_09:32:05-rados-wip-octopus-nfs-backport-distro-basic-smithi/

Testing again with commit https://github.com/ceph/ceph/commit/d8edde0c53b80d01c3797c521c5adfc2ac0a99bb

**Comment by varshar16** [comment]
Tests Fail with expected errors(https://tracker.ceph.com/issues/46046,  https://tracker.ceph.com/issues/46104):
http://qa-proxy.ceph.com/teuthology/varsha-2020-06-23_13:36:39-rados-wip-octopus-nfs-backport-distro-basic-smithi/

**Comment by varshar16** [comment]
Tests failed:
```
2020-06-23T17:25:05.004 INFO:tasks.cephfs_test_runner:======================================================================
2020-06-23T17:25:05.005 INFO:tasks.cephfs_test_runner:FAIL: test_export_create_and_delete (tasks.cephfs.test_nfs.TestNFS)
2020-06-23T17:25:05.005 INFO:tasks.cephfs_test_runner:----------------------------------------------------------------------
2020-06-23T17:25:05.005 INFO:tasks.cephfs_test_runner:Traceback (most recent call last):
2020-06-23T17:25:05.006 INFO:tasks.cephfs_test_runner:  File "/home/teuthworker/src/git.ceph.com_ceph-c_wip-octopus-nfs-backport/qa/tasks/cephfs/test_nfs.py", line 106, in test_export_create_and_delete
2020-06-23T17:25:05.006 INFO:tasks.cephfs_test_runner:    self._test_delete_cluster()
2020-06-23T17:25:05.006 INFO:tasks.cephfs_test_runner:  File "/home/teuthworker/src/git.ceph.com_ceph-c_wip-octopus-nfs-backport/qa/tasks/cephfs/test_nfs.py", line 69, in _test_delete_cluster
2020-06-23T17:25:05.006 INFO:tasks.cephfs_test_runner:    self.assertEqual("No services reported\n", orch_output)
2020-06-23T17:25:05.007 INFO:tasks.cephfs_test_runner:AssertionError: 'No services reported\n' != 'NAME              RUNNING  REFRESHED  AGE [228 chars]  \n'
2020-06-23T17:25:05.007 INFO:tasks.cephfs_test_runner:- No services reported
2020-06-23T17:25:05.007 INFO:tasks.cephfs_test_runner:+ NAME              RUNNING  REFRESHED  AGE  PLACEMENT    IMAGE NAME                                                          IMAGE ID   
2020-06-23T17:25:05.008 INFO:tasks.cephfs_test_runner:+ nfs.ganesha-test      1/0  15s ago    -    <unmanaged>  quay.ceph.io/ceph-ci/ceph:a3379a08cef1352dcbcea86351ba22b06727a082  <unknown> 
```
http://qa-proxy.ceph.com/teuthology/varsha-2020-06-23_17:05:19-rados-wip-octopus-nfs-backport-distro-basic-smithi/

**Comment by varshar16** [comment]
Missed commit: 0caa54bae89dc3f3f47348129c1bc137b44a6a4d

**Comment by varshar16** [comment]
Tests passed:  http://pulpito.ceph.com/varsha-2020-06-24_02:43:13-rados-wip-octopus-nfs-backport-distro-basic-smithi/

**Comment by varshar16** [comment]
Added PRs https://github.com/ceph/ceph/pull/35674 (only test_nfs.py commit 981a7cc923) and https://github.com/ceph/ceph/pull/35739.

**Comment by varshar16** [comment]
jenkins test dashboard backend

**Comment by varshar16** [comment]
Tests Passed:  http://qa-proxy.ceph.com/teuthology/varsha-2020-06-25_06:00:27-rados-wip-octopus-nfs-backport-distro-basic-smithi/

**Comment by sebastian-philipp** [comment]
> Tests Passed: http://qa-proxy.ceph.com/teuthology/varsha-2020-06-25_06:00:27-rados-wip-octopus-nfs-backport-distro-basic-smithi/

what is your plan now? are you ok with merging this after the next octopus release?

**Comment by varshar16** [comment]
> > Tests Passed: http://qa-proxy.ceph.com/teuthology/varsha-2020-06-25_06:00:27-rados-wip-octopus-nfs-backport-distro-basic-smithi/
> 
> what is your plan now? are you ok with merging this after the next octopus release?

Yes, after PR https://github.com/ceph/ceph/pull/35417 and PR https://github.com/ceph/ceph/pull/35743 are merged in master

**Comment by batrick** [comment]
@varshar16 please rebase.

**Comment by varshar16** [comment]
> @varshar16 please rebase.

Done.

**Comment by varshar16** [comment]
Tests Passed: http://qa-proxy.ceph.com/teuthology/varsha-2020-07-01_06:53:16-rados-wip-octopus-nfs-backport-distro-basic-smithi/

**Comment by varshar16** [comment]
Rebased and added pr https://github.com/ceph/ceph/pull/35743

**Comment by varshar16** [comment]
jenkins retest this please

**Comment by varshar16** [comment]
Tests Passed: http://qa-proxy.ceph.com/teuthology/varsha-2020-07-08_07:00:28-rados-wip-octopus-nfs-backport-distro-basic-smithi/

**Pull request merged**
