### PR TITLE
rgw: add support for metadata on Swift account

### PR DESCRIPTION
**Pull request by rzarzynski**
Hello Guys,

I would like to ask for review of changeset adding support for metadata on Swift accounts (X-Account-Meta-{} etc.). It's highly experimental, definitely needs refactoring and implementing the TempURL-related stuff. I'm sending it to get a feedback as early as possible.

### CODE REVIEW

**Comment by yehudasa** [comment]
@rzarzynski generally speaking it's the right idea, however, you should create a new RGWOp for this operation, will make code paths clearer.

**Comment by rzarzynski** [comment]
@yehudasa _RGWPutMetadata_ is currently used to handle metadata write operation for all types of resource: account, container, object. Maybe is it a good idea to split the second and third one as well?

**Comment by yehudasa** [comment]
@rzarzynski yes, I don't see why not.

**Comment by rzarzynski** [comment]
_RGWPutMetadata_ has been split. I'm attaching the fix #10668 issue as well.
There is a chance that unification of _RGWPutMetadataAccount_ with _RGWSetTempUrl_ will be ready tomorrow.

**Comment by rzarzynski** [comment]
_RGWPutMetadataAccount_ and _RGWSetTempUrl_ classes have been unified.
The patches rectify issue #11037 as well.

**Comment by rzarzynski** [comment]
@yehudasa does it look ready-to-merge to you? Is there anything I can improve?

**Comment by yehudasa** [comment]
@rzarzynski I'll need to take another look at it, didn't forget about it

**Comment by yehudasa** [comment]
@rzarzynski I went over the first few commits again. The problem that I now see with setting the metadata on the user's buckets list object is that it's not going to work across zones and regions. We need to have the metadata api control this info, probably put that as part of the user's info, similar to what we do with the buckets.

**Comment by dachary** [comment]
@rzarzynski please ignore the false negative from the bot

**Pull request merged**
