### PR TITLE
MDSMonitor: handle MDSBeacon messages properly

### PR DESCRIPTION
**Pull request by theanalyst**
http://tracker.ceph.com/issues/11979

### CODE REVIEW

**Comment by theanalyst** [comment]
Hi @tchaikov I've looked up on the original issue and added the corresponding pull requests (there were two)  onto the backport. Does this look okay to you?

**Comment by tchaikov** [comment]
@theanalyst LGTM, but i'm just wondering if we should also backport http://tracker.ceph.com/issues/11481 (#4658) to at least hammer. @gregsfortytwo and @jcsp  what do you think?

**Comment by gregsfortytwo** [comment]
I've moved that ticket to the Pending Backport state, but there's no need for them to happen in the same PR.

**Comment by gregsfortytwo** [comment]
Sorry @theanalyst; I'm not sure what buttons I'm supposed to twiddle on the tracker so you'll have to do that. :)

**Pull request merged**
