### PR TITLE
RFC: BlueStore: Usersapce nvme driver

### PR DESCRIPTION
**Pull request by yuyuyu101**
this is not a ideal implementation, I need to more time to realize the BlueStore IO pattern like "buffered" flag to control NVMEDevice behavior.

### CODE REVIEW

**Comment by liewegas** [comment]
This looks great!  Can you restructure this a bit so that the first few patches do just the BlockDevice virtual interface change before adding the NVMEDevice?  Then we can merge that right away (well, as soon as the current wip-bluestore merges, which adds read_buffered etc).

What's the deal with the patch disabling flush?  What is slow about it?  Note that there is a hack in the current bdev that makes flush a no-op if no IO has been done since the last flush.

**Comment by yuyuyu101** [comment]
Since no cache in nvme initiator side, I guess it will ok not to use force flush command. Of course, I'm going to get more precise info from nvme vendor.

**Comment by yuyuyu101** [comment]
@liewegas I tested locally, the main performance bottleneck is the sync read in BlueStore such as _do_wal_op which will block write op until read completed. Currently the spdk backend only support aio read and we don't have pagecache compared to kernel device, so _do_wal_op will consume lots of time to do sync read.

In my local env, without sync read problem, NVMEDevice behavior much better than KernelDevice under the same nvme physical device. So do you have plan or idea to change sync read in BlueStore? If shared, I guess I also have time to do this.

**Comment by liewegas** [comment]
There are 2 places where aio read can help:

1- large read over several extents.  (queue multiples reads, wait 
for all to complete, aggregate result.)  i've been ignoring it for now 
because I want to first show that it is a problem and because i'm not sure 
what the async read path is going to look like in the OSD...

2- the wal reads.  I think this can be largely mitigated by increasing the 
number of WAL threads, since it only needs to serialize by the sequencers, 
and there should be many 10's of those per OSD.

**Comment by yuyuyu101** [comment]
@liewegas currently it's a workable branch, next I will care about the read cache and misc things to make  spdk easy to use. Before these, I hope you can have a view at this, I don't want to keep these sync with master each time...... Anyway, the good news is I could get a little performance improved for spdk now even if the io path isn't ideal.

**Comment by liewegas** [comment]
ok, I will pull this down and clean it up a bit so it can be merged now.  
yay!

**Comment by liewegas** [comment]
@yuyuyu101 Should this be merged in it's current for (after a rebase) or do you want to keep working on it?  The main piece I wanted to get in quickly is the BlockDevice abstraction (so we can add NVRAM support and avoid conflicts, e.g. https://github.com/ceph/ceph/pull/7460).

**Comment by yuyuyu101** [comment]
@liewegas rebased, I hope we can merge this firstly since I guess it will be convienent to you and me to continue bluestore work.

**Comment by liewegas** [comment]
merged manually

**Pull request closed without merging**
