### PR TITLE
jewel: [rbd-nbd] Fedora does not register resize events

### PR DESCRIPTION
**Pull request by pdvian**
http://tracker.ceph.com/issues/22173

### CODE REVIEW

**Comment by pdvian** [comment]
@dillaman @smithfarm

**Comment by tchaikov** [comment]
retest this please

**Comment by smithfarm** [comment]
jenkins retest this please

**Comment by smithfarm** [comment]
jenkins retest this please

**Comment by smithfarm** [comment]
This PR is included in the integration run at: http://tracker.ceph.com/issues/21742#note-13

So far, one rbd suite with 78 jobs passed. Another one, with 154 jobs, is scheduled.

**Comment by smithfarm** [comment]
RBD integration run passed at http://tracker.ceph.com/issues/21742#note-13

**Pull request merged**
