### PR TITLE
rgw: correct typo UNKOWN to UNKNOWN

### PR DESCRIPTION
**Pull request by qrGitHub**
Signed-off-by: Bingyin Zhang <zhangbingyin@cloudin.cn>

### CODE REVIEW

**Comment by qrGitHub** [comment]
hi, @cbodley, @adamemerson, would you help to review this? thanks!

**Comment by shinobu-x** [comment]
@qrGitHub There are more:
```
doc/man/8/ceph-detect-init.rst:   If the init system of the host operating system is unkown, return
src/os/ObjectStore.h:        assert(0 == "Unkown OP");
```
Can you fix these typo as well?

**Comment by qrGitHub** [comment]
@shinobu-x  Sure, thanks for your advice.

**Comment by joscollin** [comment]
retest this please

**Comment by qrGitHub** [comment]
hi @cbodley, can this be merged?

**Pull request merged**
