### PR TITLE
jewel: core: interval_set: optimize intersect_of insert operations

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/21232

### CODE REVIEW

**Comment by liu-chunmei** [comment]
what kind of benefit do we get by this patch?

**Comment by smithfarm** [comment]
@liu-chunmei The commit messages describe performance benefits.

**Comment by smithfarm** [comment]
Passed a rados suite at http://tracker.ceph.com/issues/20613#note-48 with some failures that are, I believe, unrelated.

**Comment by smithfarm** [comment]
@liewegas OK to have this in jewel?

**Pull request merged**
