### PR TITLE
librbd: journal replay should honor inter-event dependencies

### PR DESCRIPTION
**Pull request by dillaman**
AIO write/discard operations are not marked as committed until safely flushed to disk (explicitly or automatically after enough unflushed events build-up in replay).  Simple maintenance operations (ones that cannot affect IO operations) are delayed until after the OpFinish event is processed.  Complex maintenance operations (which can affect IO) are partially executed until the point where internal state is consistent before journal event processing continues.

### CODE REVIEW

**Comment by dillaman** [comment]
@jdurgin some light reading for the New Year :wink:

**Comment by jdurgin** [comment]
"only"  7k lines changed

**Comment by dillaman** [comment]
@dachary looks like new Jenkin's slave needs more memory(?)

**Comment by dachary** [comment]
@dillaman that would be a request for @alfredodeza or @andrewschoen. I don't know what kind of jenkins slaves are selected to run the bot.

**Comment by alfredodeza** [comment]
a bummer, yes, I think we need to tweak this for more memory

**Comment by jdurgin** [comment]
lgtm once it runs through a rbd suite.
may want to make the low/high water mark configurable in the future

**Comment by dillaman** [comment]
I'll kick off a suite run tomorrow.

**Comment by dillaman** [comment]
Lots of environment noise, but no failures from these changes:

http://pulpito.ceph.com/jdillaman-2016-01-13_17:39:05-rbd-wip-14006---basic-multi/

http://pulpito.ceph.com/jdillaman-2016-01-13_18:36:42-rbd-wip-14006---basic-multi/

**Pull request merged**
