### PR TITLE
squid: log: save/fetch thread name infra

### PR DESCRIPTION
**Pull request by mchangir**
TODO: Squid Tracker
Signed-off-by: Milind Changire <mchangir@redhat.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Comment by mchangir** [comment]
jenkins test api

**Comment by mchangir** [comment]
jenkins test windows

**Comment by mchangir** [comment]
* sync with updated main PR

**Comment by mchangir** [comment]
jenkins test api

**Comment by mchangir** [comment]
jenkins test make check

**Comment by mchangir** [comment]
jenkins test api

**Comment by mchangir** [comment]
* minor change to set `m_thread_name[15] = '\0';` in `class Entry` ctor

**Review by kamoltat — APPROVED** [review]
LGTM, I reviewed the runs and also compared the main PR that the commits were cherry-picked to this PR.

**Comment by kamoltat** [comment]
RADOS approved: RADOS Approved:
https://tracker.ceph.com/projects/rados/wiki/SQUID#httpstrackercephcomissues68553

**Comment by mchangir** [comment]
eeks! the commit and PR are missing the backport tracker

**Comment by batrick** [comment]
@mchangir please do backport for https://tracker.ceph.com/issues/68691

**Comment by mchangir** [comment]
> @mchangir please do backport for https://tracker.ceph.com/issues/68691

I'm not sure what exactly needs to be done here.
Should I be posting backports for your PR ?
Since this a squid PR, it has already been merged.
Also, this PR wasn't created using the standard `ceph-backport.sh` script.
So, its missing the backport and original tracker references.

PRs for other branches have also been posted (without using `ceph-backport.sh` and so are missing the tracker references.

**Pull request merged**
