### PR TITLE
qa/workunits: Remove redundant Xenial cmake3 requirements

### PR DESCRIPTION
**Pull request by badone**
Fixes: https://tracker.ceph.com/issues/45561

## Checklist
- [x] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by tchaikov** [comment]
@badone could you fill me with more context? we don't build nautilus on xenial anymore?

**Comment by badone** [comment]
> @badone could you fill me with more context? we don't build nautilus on xenial anymore?

The test still runs on Xenial. Is Nautilus supported on Xenial? If not I guess we could remove Xenail from this test instead but the code's redundant anyway right?

**Comment by tchaikov** [comment]
> > @badone could you fill me with more context? we don't build nautilus on xenial anymore?
> 
> The test still runs on Xenial. Is Nautilus supported on Xenial? If not I guess we could remove Xenail from this test instead but the code's redundant anyway right?

i am not sure. that's why i am asking.

**Comment by badone** [comment]
This forms part of the resolution for https://tracker.ceph.com/issues/44981

**Comment by tchaikov** [comment]
http://pulpito.ceph.com/kchai-2020-05-21_10:34:02-rados-wip-kefu-testing-2020-05-21-1652-distro-basic-smithi/

the failures are either tracked or fixed by

- https://tracker.ceph.com/issues/44595
- https://tracker.ceph.com/issues/45647
- https://tracker.ceph.com/issues/45631
- https://tracker.ceph.com/issues/44990
- #35139

**Comment by tchaikov** [comment]
i am leaving https://tracker.ceph.com/issues/45561 open. as i am not sure if nautilus on xenial is still being built or tested, if you could paste any link / document as a reference, that'd be great.

**Comment by badone** [comment]
https://shaman.ceph.com/builds/ceph/wip-nautilus-badone-testing/ built xenial 7 days ago.

**Comment by badone** [comment]
> i am leaving https://tracker.ceph.com/issues/45561 open. as i am not sure if nautilus on xenial is still being built or tested, if you could paste any link / document as a reference, that'd be great.

@tchaikov https://shaman.ceph.com/builds/ceph/nautilus/fd80879112559f6509c42370d6cb41114d5e54d0/ is building on Xenial today.

**Comment by badone** [comment]
http://pulpito.front.sepia.ceph.com/bhubbard-2020-05-22_22:46:42-rados-nautilus-distro-basic-smithi/

**Comment by badone** [comment]
http://qa-proxy.ceph.com/teuthology/bhubbard-2020-05-22_22:46:42-rados-nautilus-distro-basic-smithi/5083578/teuthology.log <--- This is the specific failure in Nautilus HEAD this PR is designed to resolve.

**Comment by tchaikov** [comment]
> It's no longer necessary to handle Xenial as a special case.

so we still need to handle xenial, right?

**Comment by badone** [comment]
> > It's no longer necessary to handle Xenial as a special case.
> 
> so we still need to handle xenial, right?

Right, but not as a special case.

**Comment by tchaikov** [comment]
the commit message reads:

> It's no longer necessary to handle Xenial as a special case.

and i did read it. you reply repeats it in a slightly different way.

the reason why we install cmake3 on xenial was we used cmake3 for compiling nautilus on xenial. and because we claimed to drop the xenial by then but was still using it. so i have to package cmake3 for xenial then.

i think it's a cleanup but not a fix, because we don't built the master branch on xenial anymore. please note i compiled cmake3 using the a recent toolchain offered by PPA, that's why "libstdc++6 (>= 6)" is required.

so far, i cannot find enough information connecting the issue with the fix.

**Comment by badone** [comment]
I've removed 'bug fix' and added 'cleanup'. I think that's what you want? My argument is that it may be a clean up on master but I believe it's a bug fix on nautilus. My objective is to get the nautilus test to pass. This seemed like a reasonable way to achieve that. Please make or suggest any adjustments you deem necessary for this discussion to reach an end.

**Comment by tchaikov** [comment]
this does not make difference anymore, as this PR has been merged. Brad, i was reviewing this change in hope to help you. what i can now, is to make sure the tracker issue is not closed because of a "maybe" fix. if i have enough bandwidth, i would make or suggest.

**Comment by badone** [comment]
> this does not make difference anymore, as this PR has been merged. Brad, i was reviewing this change in hope to help you. what i can now, is to make sure the tracker issue is not closed because of a "maybe" fix. if i have enough bandwidth, i would make or suggest.

I appreciate your help but am just not clear on why you consider it to be a "maybe" fix. Perhaps you could elaborate on what is required to convince you it is an actual fix?

**Comment by tchaikov** [comment]
i tried to put my understanding of the issue in https://github.com/ceph/ceph/pull/35082#issuecomment-633170195 . if you think otherwise, i will give up on understanding the "why". if you could paste a link to pulpito of the passed fix on nautilus with backport of this change, that'd suffice.

**Comment by badone** [comment]
https://paste.centos.org/view/d989151f

http://pulpito.front.sepia.ceph.com/bhubbard-2020-05-24_06:06:48-rados-wip-nautilus-badone-testing-distro-basic-smithi/

**Pull request merged**
