### PR TITLE
mon/Monitor: allow probe if MMonProbe::mon_release == 0

### PR DESCRIPTION
**Pull request by jecluis**
Fixes: http://tracker.ceph.com/issues/38850

Signed-off-by: Joao Eduardo Luis \<joao@suse.com>

### CODE REVIEW

**Comment by smithfarm** [comment]
@jecluis This doesn't need to get backported any further than to nautilus, right?

**Comment by rjfd** [comment]
> @jecluis This doesn't need to get backported any further than to nautilus, right?

@smithfarm correct

**Comment by smithfarm** [comment]
The commits are in master and they cherry-pick to nautilus cleanly.

**Comment by smithfarm** [comment]
```The following tests FAILED:
	157 - unittest_rgw_reshard_wait (Failed)
	162 - unittest_rgw_dmclock_scheduler (Failed)

**Comment by jecluis** [comment]
> 159/171 Test #162: unittest_rgw_dmclock_scheduler ..........***Failed    0.51 sec
> did not load config file, using default settings.
> 2019-05-28 10:51:36.998 7f50d28cc200 -1 Errors while parsing config file!

This one failed for reasons that don't seem to be affected by this PR. The other one requires investigating.

**Comment by rjfd** [comment]
jenkins retest this please

**Comment by theanalyst** [comment]
```154/171 Test #157: unittest_rgw_reshard_wait ...............***Failed    0.41 sec
Running main() from gmock_main.cc
[==========] Running 5 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 5 tests from ReshardWait
[ RUN      ] ReshardWait.wait_block
[       OK ] ReshardWait.wait_block (14 ms)
[ RUN      ] ReshardWait.stop_block
[       OK ] ReshardWait.stop_block (10 ms)
[ RUN      ] ReshardWait.wait_yield
/home/jenkins-build/build/workspace/ceph-pull-requests/src/test/rgw/test_rgw_reshard_wait.cc:78: Failure
Expected: (wait_duration) <= (elapsed), actual: 0.01s vs 0.0091993s
[  FAILED  ] ReshardWait.wait_yield (9 ms)
[ RUN      ] ReshardWait.stop_yield
[       OK ] ReshardWait.stop_yield (10 ms)
[ RUN      ] ReshardWait.stop_multiple
[       OK ] ReshardWait.stop_multiple (14 ms)
[----------] 5 tests from ReshardWait (58 ms total)

[----------] Global test environment tear-down
[==========] 5 tests from 1 test case ran. (58 ms total)
[  PASSED  ] 4 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] ReshardWait.wait_yield

 1 FAILED TEST```


While the test failure is unrelated to this pr, it is still unexpected (and not reproducible locally for me), adding @cbodley if this was seen before

**Comment by jecluis** [comment]
do not merge: we now get an assert on mdsmon when upgrading the last luminous monitor. investigating.

**Comment by jecluis** [comment]
doesn't appear to be related to this patch as we've been able to reproduce it without the patch itself.

**Comment by cbodley** [comment]
thanks @theanalyst, the nautilus backport of that fix is still open in https://github.com/ceph/ceph/pull/27779

**Comment by liewegas** [comment]
retest this please

**Comment by smithfarm** [comment]
`7/171 Test   #3: test_objectstore_memstore.sh ............***Failed    8.23 sec`

**Comment by smithfarm** [comment]
jenkins re-test this please

**Comment by yuriw** [comment]
[wip-yuri5-testing-2019-05-29-1613-nautilus](https://trello.com/c/q7wFCEp3/622-wip-yuri5-testing-2019-05-29-1613-nautilus)

**Comment by yuriw** [comment]
[wip-yuri4-testing-2019-05-30-2109-nautilus](https://trello.com/c/gp7jSQKF/626-wip-yuri4-testing-2019-05-30-2109-nautilus)

**Pull request merged**
