### PR TITLE
CephFS: misc. cleanups and remove legacy cephfs tool

### PR DESCRIPTION
**Pull request by jcsp**

### CODE REVIEW

**Comment by jcsp** [comment]
Tested here: http://pulpito.ceph.com/jspray-2016-07-11_03:45:31-fs-wip-mds-minor-distro-basic-mira/

**Comment by smithfarm** [comment]
Could you add a line Fixes: http://tracker.ceph.com/issues/16035 to d67affc ?

Also, see http://tracker.ceph.com/issues/16035#note-4

**Comment by jcsp** [comment]
@smithfarm it already had the Fixes line I think?

Pushed a rebase of this anyway.  I'd suggest that the ceph-common/ceph-fs-common refactor be done separately to this PR

Any objections to merging?

**Comment by smithfarm** [comment]
> Any objections to merging?

Definitely not! I am eager to remove the legacy tool.

**Comment by smithfarm** [comment]
I looked at the test failures, which fall into the following categories:

* infrastructure noise (can't SSH to a test machine)
* valgrind issues (which I gather we are ignoring in MDS)
* failed java tests
* failed test_data_isolated

**Comment by smithfarm** [comment]
JFYI, I opened http://tracker.ceph.com/issues/16808 for the ceph-common/ceph-fs-common refactor.

**Pull request merged**
