### PR TITLE
osd: fix OpRequest and tracked op dump information

### PR DESCRIPTION
**Pull request by Yan-waller**
if we use command `ceph daemon osd.# dump_historic_ops` to check the history tracked ops, the `client_addr` is always dumped as `-` which result in clients indistinguishable from each other.

```c++
"description": "osd_op(client.24123.0:328 3.36 3:6ec0d61b:::rbd_data.10472ae8944a.0000000000000289:head [write 4141056~4096 [fadvise_seque
ntial]] snapc 0=[] ondisk+write+known_if_redirected e36)",
            "initiated_at": "2017-07-22 14:24:25.925633",
            "age": 4.893190,
            "duration": 0.272642,
            "type_data": {
                "flag_point": "commit sent; apply or cleanup",
                "client_info": {
                    "client": "client.24123",
                    "client_addr": "-",
                    "tid": 328
                },
```
It is because `connection` was reset to nullptr in function `_unregistered` before the op has been inserted into history, so the `get_orig_source_addr` always return an empty entity addr.

Signed-off-by: Yan Jun <yan.jun8@zte.com.cn>

### CODE REVIEW

**Comment by xiexingguo** [comment]
good patch:-)

**Comment by scienceluo** [comment]
Jenkins retest this please

**Comment by xiexingguo** [comment]
retest this please

**Comment by liewegas** [comment]
http://pulpito.ceph.com/sage-2017-07-24_03:44:49-rados-wip-sage-testing-distro-basic-smithi/

**Pull request merged**
