### PR TITLE
osd/PrimaryLogPG: erase gather op during op cancel

### PR DESCRIPTION
**Pull request by NitzanMordhai**
The erase exist, but it try to delete iter and not the name of the soid

Fixes: https://tracker.ceph.com/issues/64258
Signed-off-by: Nitzan Mordechai <nmordech@redhat.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Comment by NitzanMordhai** [comment]
jenkins test api

**Review by ljflores — APPROVED** [review]

**Comment by athanatos** [comment]
@NitzanMordhai What's wrong with invoking erase on the iterator?  Invoking erase on the iterator should have the same effect as invoking it on the key, but much more efficiently (constant time rather than logarithmic).  I don't see a mechanism that would allow this to fix the bug linked in the ticket.

**Review by athanatos — CHANGES_REQUESTED** [review]
See above comment.

**Comment by NitzanMordhai** [comment]
> @NitzanMordhai What's wrong with invoking erase on the iterator? Invoking erase on the iterator should have the same effect as invoking it on the key, but much more efficiently (constant time rather than logarithmic). I don't see a mechanism that would allow this to fix the bug linked in the ticket.

seeing that. will rework that.

**Comment by NitzanMordhai** [comment]
@athanatos Since we are not have new interval, the cancel was not invoked, i added logic to cancel the ops if we already have them in the map (just like copy ops)

**Comment by athanatos** [comment]
> @athanatos it looks like the peering process didn't call start_peering_interval which is supposed to call on_change which triggers the cleanup and cancel of the gather. we also have finish methode in the gather (struct C_gather) that getting r=-125) but doesn't clear the cls_gather_ops map, that can solve the issue as well

If peering really skipped start_peering_interval, that would be an incredibly huge bug.  Do you have logs?

**Comment by NitzanMordhai** [comment]
> If peering really skipped start_peering_interval, that would be an incredibly huge bug. Do you have logs?

@athanatos i was able to recreate the error with my local build, can you check the logs on folio03? /home/nmordech/output_gather

or should i move them to somewhere else?

**Comment by athanatos** [comment]
@NitzanMordhai See my comment https://tracker.ceph.com/issues/64258 -- there was no interval change.  The entry is there because the op was retried and the previous attempt was still in progress.  This feature was implemented as an experiment, but I'm not aware of any serious users.  For now, I suggest:
1. move this test into an experimental suite and don't consider it for normal testing
2. mark cls_gather deprecated in squid.  If someone steps up to finish the implementation and maintain it going foward we can un-deprecate it.  Otherwise, we'll remove it in T.

@NitzanMordhai Can you take care of the above?

**Comment by NitzanMordhai** [comment]
> @NitzanMordhai Can you take care of the above?

@athanatos thanks for reviewing it, will do that

**Comment by rzarzynski** [comment]
Just to the record:

```
$ grep -r cls_cxx_gather 
crimson/osd/objclass.cc:int cls_cxx_gather(cls_method_context_t hctx, const std::set<std::string> &src_objs, const std::string& pool,
Binary file crimson/osd/.objclass.cc.swp matches
objclass/objclass.h:extern int cls_cxx_gather(cls_method_context_t hctx, const std::set<std::string> &src_objs, const std::string& pool,
cls/test_remote_reads/cls_test_remote_reads.cc:    r = cls_cxx_gather(hctx, src_objects, pool, cls.c_str(), method.c_str(), *in);
osd/objclass.cc:int cls_cxx_gather(cls_method_context_t hctx, const std::set<std::string> &src_objs, const std::string& pool
```

```
$ grep -r cls_cxx_get_gathered_data ./
./crimson/osd/objclass.cc:int cls_cxx_get_gathered_data(cls_method_context_t hctx, std::map<std::string, bufferlist> *results)
Binary file ./crimson/osd/.objclass.cc.swp matches
./objclass/objclass.h:extern int cls_cxx_get_gathered_data(cls_method_context_t hctx, std::map<std::string, bufferlist> *results);
./cls/test_remote_reads/cls_test_remote_reads.cc:  int r = cls_cxx_get_gathered_data(hctx, &src_obj_buffs);
./osd/objclass.cc:int cls_cxx_get_gathered_data(cls_method_context_t hctx, std::map<std::string, bufferlist> *results)
```

**Pull request closed without merging**
