### PR TITLE
mon: add 'osd destroy-new' command that only destroys NEW osd slots

### PR DESCRIPTION
**Pull request by liewegas**
http://tracker.ceph.com/issues/24428

### CODE REVIEW

**Comment by vasukulkarni** [comment]
can this be part of osd destroy itself? will be easier .

**Comment by liewegas** [comment]
It's a separate command because the boostrap-osd role has to allow this and not something else, and it's pattern-matching abilities are limited.  I'd rather just make a separate command name then rely on delicate matching of arguments.

**Comment by alfredodeza** [comment]
would this get backported all the way back to Luminous? So that we make sure that ceph-volume changes match those versions

**Comment by liewegas** [comment]
It's easy to backport.. let's do it.

**Comment by tchaikov** [comment]
http://pulpito.ceph.com/kchai-2018-06-09_08:01:13-rados-wip-kefu-testing-2018-06-09-1418-distro-basic-smithi/

2646113 can be reproduce on master, see http://pulpito.ceph.com/kchai-2018-06-09_11:50:19-rados-master-distro-basic-smithi/#, tracked by http://tracker.ceph.com/issues/24479

**Comment by alfredodeza** [comment]
The behavior we were looking forward to is to remove the OSD ID from the cluster in such a way that `osd new` could return the unused ID and reuse it for creating the OSD.

This is described here: http://tracker.ceph.com/issues/22704 and ceph-volume fixed this behavior by using `osd destroy` (which requires the admin keyring).

However, trying to use `destroy-new` we are back to the initial problem:

* ceph-volume tries and fails to create the OSD, `osd new` is called, on failure it calls `destroy-new`.
* ceph-volume is called again, however the ID is incremented by 1, and `ceph -s` shows the previous OSD as down

Fail to deploy for the third time, see another OSD (id 3) incremented:

    $ ceph-deploy osd create --data /dev/sdh node9
    ...
    [node9][INFO  ] Running command: sudo /usr/sbin/ceph-volume --cluster ceph lvm create --bluestore --data /dev/sdh
    [node9][WARNIN] -->  RuntimeError: command returned non-zero exit status: 5
    [node9][DEBUG ] Running command: /usr/bin/ceph-authtool --gen-print-key
    [node9][DEBUG ] Running command: /usr/bin/ceph --cluster ceph --name client.bootstrap-osd --keyring /var/lib/ceph/bootstrap-osd/ceph.keyring -i - osd new 9857a645-b6db-4bc6-814b-d5305be20279
    [node9][DEBUG ] Running command: /sbin/vgcreate --force --yes ceph-ba0163da-e8a1-4c47-a203-d03fbe9cf985 /dev/sdh
    [node9][DEBUG ]  stderr:
    [node9][DEBUG ]  stderr: Physical volume '/dev/sdh' is already in volume group 'ceph-6ea3112a-dd47-478d-bbf7-6977de447fbe'
    [node9][DEBUG ]  stderr:
    [node9][DEBUG ]  stderr:
    [node9][DEBUG ]  stderr: Unable to add physical volume '/dev/sdh' to volume group 'ceph-ba0163da-e8a1-4c47-a203-d03fbe9cf985'.
    [node9][DEBUG ]  stderr:
    [node9][DEBUG ] --> Was unable to complete a new OSD, will rollback changes
    [node9][DEBUG ] Running command: /usr/bin/ceph --cluster ceph --name client.bootstrap-osd --keyring /var/lib/ceph/bootstrap-osd/ceph.keyring osd destroy-new osd.3 --yes-i-really-mean-it
    [node9][DEBUG ]  stderr: destroyed osd.3
    [node9][ERROR ] RuntimeError: command returned non-zero exit status: 1
    [ceph_deploy.osd][ERROR ] Failed to execute command: /usr/sbin/ceph-volume --cluster ceph lvm create --bluestore --data /dev/sdh
    [ceph_deploy][ERROR ] GenericError: Failed to create 1 OSDs
    

Number of OSDs is incremented in `ceph -s`

    root@node9:/home/vagrant# ceph -s
      ...
      services:
        mon: 1 daemons, quorum node2
        mgr: no daemons active
        osd: 4 osds: 1 up, 1 in


Deploy again with failure, get another ID:

    $ ceph-deploy osd create --data /dev/sdh node9
    ...
    [node9][INFO  ] Running command: sudo /usr/sbin/ceph-volume --cluster ceph lvm create --bluestore --data /dev/sdh
    [node9][WARNIN] -->  RuntimeError: command returned non-zero exit status: 5
    [node9][DEBUG ] Running command: /usr/bin/ceph-authtool --gen-print-key
    [node9][DEBUG ] Running command: /usr/bin/ceph --cluster ceph --name client.bootstrap-osd --keyring /var/lib/ceph/bootstrap-osd/ceph.keyring -i - osd new 551327e5-eeb6-46c8-aeeb-523a83b27cde
    [node9][DEBUG ] Running command: /sbin/vgcreate --force --yes ceph-7293b0b3-54af-4a54-a532-63a0846d89b6 /dev/sdh
    [node9][DEBUG ]  stderr:
    [node9][DEBUG ]  stderr: Physical volume '/dev/sdh' is already in volume group 'ceph-6ea3112a-dd47-478d-bbf7-6977de447fbe'
    [node9][DEBUG ]  stderr:
    [node9][DEBUG ]  stderr:
    [node9][DEBUG ]  stderr: Unable to add physical volume '/dev/sdh' to volume group 'ceph-7293b0b3-54af-4a54-a532-63a0846d89b6'.
    [node9][DEBUG ]  stderr:
    [node9][DEBUG ] --> Was unable to complete a new OSD, will rollback changes
    [node9][DEBUG ] Running command: /usr/bin/ceph --cluster ceph --name client.bootstrap-osd --keyring /var/lib/ceph/bootstrap-osd/ceph.keyring osd destroy-new osd.4 --yes-i-really-mean-it
    [node9][DEBUG ]  stderr: destroyed osd.4
    [node9][ERROR ] RuntimeError: command returned non-zero exit status: 1
    [ceph_deploy.osd][ERROR ] Failed to execute command: /usr/sbin/ceph-volume --cluster ceph lvm create --bluestore --data /dev/sdh
    [ceph_deploy][ERROR ] GenericError: Failed to create 1 OSDs
 
Another OSD shows up in status:

    root@node9:/home/vagrant# ceph -s
      ...
      services:
        mon: 1 daemons, quorum node2
        mgr: no daemons active
        osd: 5 osds: 1 up, 1 in

**Comment by liewegas** [comment]
I'll take a look at how to improve the destroy-new behavior so that IDs get reused.  In the meantime, ceph-volume is doing the "right" thing, and the incrementing osd ids is a purely cosmetic issue.

**Pull request merged**
