### PR TITLE
*/: fix typos in docs,messages,logs,comments

### PR DESCRIPTION
**Pull request by tchaikov**
the typos are identified by [codespell](https://github.com/codespell-project/codespell). and screened out the false alarms manually.

### CODE REVIEW

**Comment by tchaikov** [comment]
@libingyang-zte @xiexingguo in case you are interested.

**Comment by xiexingguo** [comment]
Cool!

**Comment by xiexingguo** [comment]
This fails the cli test

**Comment by tchaikov** [comment]
@xiexingguo fixed and repushed.

**Comment by tchaikov** [comment]
- http://pulpito.ceph.com/kchai-2018-09-19_14:35:21-rados-wip-kefu-testing-2018-09-19-1821-distro-basic-mira/
- http://pulpito.ceph.com/kchai-2018-09-20_12:40:38-rados-wip-kefu-testing-2018-09-19-1821-distro-basic-smithi/

**Comment by tchaikov** [comment]
changelog

- rebase onto master.

**Pull request merged**
