### PR TITLE
nautilus: osd/PG: discover missing objects when an OSD peers and PG is degraded

### PR DESCRIPTION
**Pull request by ashishkumsingh**
https://tracker.ceph.com/issues/39432

### CODE REVIEW

**Comment by smithfarm** [comment]
jenkins test docs

**Comment by TheJJ** [comment]
Just to make sure this lands in the next nautilus release, is there something holding back the patch? If yes, I'm ready to help out.

**Comment by smithfarm** [comment]
jenkins retest this please

**Comment by smithfarm** [comment]
@TheJJ It is not building properly for the Jenkins "make check" test, but this is currently happening in other nautilus PRs as well. Anyway, you shouldn't worry - the PR will get into an integration testing run in due course.

**Comment by smithfarm** [comment]
jenkins re-test this please

**Comment by smithfarm** [comment]
jenkins test docs

**Comment by yuriw** [comment]
[wip-yuri4-testing-2019-05-23-2026-nautilus](https://trello.com/c/LpO6mvVB/617-wip-yuri4-testing-2019-05-23-2026-nautilus)

**Pull request merged**
