### PR TITLE
mgr: move "osd pool stats" to mgr

### PR DESCRIPTION
**Pull request by tchaikov**
Signed-off-by: Kefu Chai <kchai@redhat.com>

### CODE REVIEW

**Comment by tchaikov** [comment]
```
The following tests FAILED:
	  3 - ceph_objectstore_tool.py (Timeout)
```

retest this please

**Comment by liewegas** [comment]
retest this please

**Comment by dzafman** [comment]
@tchaikov This ceph_objectstore_tool.py test sets MGR=0 for vstart.  Just change that to 1 and it shouldn't hang.

**Comment by tchaikov** [comment]
@dzafman thanks for looking at this hang. just realized that it's me who added "MGR=0"!

**Comment by liewegas** [comment]
http://pulpito.ceph.com/sage-2017-04-07_19:53:23-rados-wip-sage-testing---basic-smithi/

**Pull request merged**
