### PR TITLE
mgr/cephadm: disable asyncssh logging by default

### PR DESCRIPTION
**Pull request by liewegas**
## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by sebastian-philipp** [comment]
can we just hard code it? Is there a need to have it configurable?

**Comment by liewegas** [comment]
I wasn't sure.  I assumed that since it was true originally that there was some value...?

**Comment by liewegas** [comment]
jenkins test make check

**Comment by liewegas** [comment]
jenkins test dashboard cephadm

**Comment by liewegas** [comment]
jenkins test dashboard cephadm

**Review by sebastian-philipp — APPROVED** [review]

**Comment by liewegas** [comment]
jenkins test dashboard cephadm

**Pull request merged**
