### PR TITLE
mgr/test_orchestrator: Add dummy data

### PR DESCRIPTION
**Pull request by votdev**
Add a JSON file containing dummy data for testing the orchestrator.

Signed-off-by: Volker Theile <vtheile@suse.com>

## Checklist
- [ ] References tracker ticket
- [x] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by sebastian-philipp** [comment]
Can you make use of it? Just adding the data seems a bit pointless

**Comment by votdev** [comment]
> Can you make use of it? Just adding the data seems a bit pointless

I can use it to test the Dashboard, but nothing more.

**Comment by sebastian-philipp** [comment]
> > Can you make use of it? Just adding the data seems a bit pointless
> 
> I can use it to test the Dashboard UI, but nothing more.

What do you think about unifying this with

https://github.com/ceph/ceph/blob/2da7330e7e102217f8c86d6c0d296d3ac7335b3e/src/python-common/ceph/tests/test_inventory.py#L6-L8

?

**Comment by sebastian-philipp** [comment]
Ping

**Comment by votdev** [comment]
jenkins test make check

**Comment by sebastian-philipp** [comment]
can we close this in favor of #32182 ?

**Pull request closed without merging**
