### PR TITLE
librbd: do not shut down exclusive lock while acquiring

### PR DESCRIPTION
**Pull request by dillaman**
Fixes: http://tracker.ceph.com/issues/16260
Signed-off-by: Jason Dillaman <dillaman@redhat.com>

### CODE REVIEW

**Comment by dillaman** [comment]
(included in my wip-jd-testing branch for Jewel)

**Comment by dillaman** [comment]
Passed teuthology test: http://pulpito.ceph.com/jdillaman-2016-06-13_18:56:29-rbd-master---basic-smithi/257304/

**Comment by trociny** [comment]
lgtm

**Comment by dillaman** [comment]
@trociny Any objection to me merging this? It passed a jewel suite run and the two branches are basically the same right now.

**Comment by trociny** [comment]
@dillaman No objection, just was waiting for this to finish:

http://pulpito.ceph.com/trociny-2016-06-14_00:07:28-rbd-wip-mgolub-testing---basic-vps/

But the most already done, and no new failures are observed.

**Pull request merged**
