### PR TITLE
doc: do not recommend pulling cephadm from git

### PR DESCRIPTION
**Pull request by phlogistonjohn**
First off, these instructions are wrong because the file has been
renamed to cephadm.py, and will not succeed as written. Amusingly, due
to curl's default behavior (and my lack of access to a time machine) the
initial command will seem to have succeeded until the user discovers
that HTML delivered as part of the body of a 404 response is not an
executable script.

Furthermore, in preparation for Reef we updated the documentation in the
cephadm subsection to use the results of a build, rather than source
files, because reef now contains a "compiled" cephadm. Currently, the
contents of the compilation is essentially the same-old cephadm script
but that will no longer be the case in the very near future (see
https://github.com/ceph/ceph/commit/7c6a2cad96405616719b85c740aabd98558c93ac). We missed this general
section of the Ceph docs that repeats the instructions to copy a raw
python file out of the Ceph tree on GitHub.  Update the section to
contain a simplified version of the instruction found in
doc/cephadm/install.rst.

In addition,
* Don't call cephadm a script, it could be misleading
* Use the current release in the example for copy-pasters
* Improve grammar (I think)

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [x] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [x] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by phlogistonjohn** [comment]
I don't know what the backport policy/process is for docs, but I would like to see a backport for these changes to Reef. I'd file a tracker, but I didn't find a project for doc...?  Maybe I'm tool lazy and did not look hard enough.

**Review by adk3798 — APPROVED** [review]

**Comment by zdover23** [comment]
https://github.com/ceph/ceph/pull/52997 - Reef backport

**Comment by zdover23** [comment]
> I don't know what the backport policy/process is for docs, but I would like to see a backport for these changes to Reef. I'd file a tracker, but I didn't find a project for doc...? Maybe I'm tool lazy and did not look hard enough.

@phlogistonjohn, see https://github.com/ceph/ceph/pull/52989#issuecomment-1678765687 for the backport to Reef. If this should be backported to Quincy, let me know and I'll do that.

As for the process for requesting backports: just send me a message at zac.dover@proton.me or on Slack. I work every day of the year, so if you send messages to both of those places you will, at worst, get a message from me explaining why it'll have to wait a few hours.

If you think that there should be a more formal process for making documentation requests, I'll meet with you for half an hour and we can hammer it out.

**Comment by phlogistonjohn** [comment]
> > I don't know what the backport policy/process is for docs, but I would like to see a backport for these changes to Reef. I'd file a tracker, but I didn't find a project for doc...? Maybe I'm tool lazy and did not look hard enough.
> 
> @phlogistonjohn, see [#52989 (comment)](https://github.com/ceph/ceph/pull/52989#issuecomment-1678765687) for the backport to Reef. If this should be backported to Quincy, let me know and I'll do that.
> 

Thanks. No backport to quincy is necessary, only Reef contains the renamed & compiled cephadm.

> As for the process for requesting backports: just send me a message at [zac.dover@proton.me](mailto:zac.dover@proton.me) or on Slack. I work every day of the year, so if you send messages to both of those places you will, at worst, get a message from me within twenty-four hours explaining why it'll have to wait a few hours.
> 

OK. I do hope you take some breaks ;-)


> If you think that there should be a more formal process for making documentation requests, I'll meet with you for half an hour and we can hammer it out.

Not necessary, although I appreciate the offer. I previously assumed there would be a tracker component, but I assumed wrong. I really don't like the tracker/redmine very much so I don't mind if the docs team eschews it. :-)

**Comment by zdover23** [comment]
> OK. I do hope you take some breaks ;-)

I've found that my work is easier if I just keep at it, continually, incrementally. Due to the highly contextual and specific nature of the various parts of the Ceph project and my absurdly broad remit of the entire Ceph documentation suite as "the upstream Ceph docs person", I find that if I let my attention wander I have to spend more time figuring out what finicky little math problem I was in the middle of than I spend just keeping the finicky little math problem warm in my mind. 

After I wrote that I work every day of the year, I spent about half an hour thinking that I shall not work on the first of May. So: I have worked every day for the past year, but I will take May 1, 2024 off.

**Pull request merged**
