### PR TITLE
docs: Clarify the relationship of min_size to EC pool recovery

### PR DESCRIPTION
**Pull request by badone**
Signed-off-by: Brad Hubbard <bhubbard@redhat.com>

### CODE REVIEW

**Comment by badone** [comment]
@liewegas 9549943 broke this so I'm trying to correct that specifically for the EC case. Would you mind taking a look at this when you get a chance?

**Comment by badone** [comment]
Test this please

**Comment by liewegas** [comment]
Hmm, I was under the impression that we fixed this last year (changing min_size wasn't needed for recovery to progress)?

**Comment by badone** [comment]
Test this please

@liewegas doesn't you comment in #12971 indicate min_size is still relevant for EC pools?

**Pull request merged**
