### PR TITLE
crimson/seastore: dump crimson perf counters

### PR DESCRIPTION
**Pull request by liu-chunmei**
Signed-off-by: chunmei-liu <chunmei.liu@intel.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by liu-chunmei** [comment]
@athanatos please review.

**Comment by athanatos** [comment]
@ronen-fr Did you end up creating test scripts for admin socket commands that we could wire this into?

**Comment by liu-chunmei** [comment]
@athanatos this PR can be test by "ceph daemon osd.0 perfcounters_dump " after start crimson-osd by vstart.sh.

**Comment by liu-chunmei** [comment]
@athanatos please review it.

**Review by athanatos — APPROVED** [review]

**Pull request merged**
