### PR TITLE
rgw : catch non int exception

### PR DESCRIPTION
**Pull request by BryceCao**
Fixes: https://tracker.ceph.com/issues/48034
Signed-off-by: caolei <halei15848934852@163.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by pponnuvel** [comment]
Would it be better to print it with `std::current_exception()`?

**Comment by BryceCao** [comment]
> Would it be better to print it with `std::current_exception()`?

I'm not sure of the exception type here, although std::exception can solve most problems. Do you have any suggestions about this?

**Comment by pponnuvel** [comment]
Yeah, `std::exception` would be an imrovement. Something like is probably ok:
```
catch (const std::exception& e) {
...
}
catch (...) {
...
}
```

**Comment by cbodley** [comment]
@BryceCao are you still working on this one? i'd like to see the `catch (const std::exception& e) {` added back, but without the `catch(...)`

**Comment by BryceCao** [comment]
@cbodley   i  closed this PR by mistake, have opened anthor: https://github.com/ceph/ceph/pull/37926

**Pull request closed without merging**
