### PR TITLE
mgr/dashboard: Add filtered rows number in table footer

### PR DESCRIPTION
**Pull request by tspmelo**
The new filtered number will only show if it is different from the total.
image

### CODE REVIEW

**Comment by tspmelo** [comment]
jenkins retest this please

**Comment by LenzGr** [comment]
Does "filtered" mean that these rows are not displayed? Or are these the ones that are being shown?

**Comment by ricardoasmarques** [comment]
@LenzGr I had that question too, and I'm not sure how we can improve it.

"filtered" means the number of rows that are being shown after the filter is applied

**Comment by votdev** [comment]
How about using "found" instead of "filtered"?

**Pull request merged**
