### PR TITLE
pacific: mgr/dashboard: monitoring: refactor into ceph-mixin

### PR DESCRIPTION
**Pull request by MrFreezeex**
backport tracker: https://tracker.ceph.com/issues/54138

---

backport of https://github.com/ceph/ceph/pull/44059
parent tracker: https://tracker.ceph.com/issues/53374

this backport was staged using ceph-backport.sh version 16.0.0.6848
find the latest version at https://github.com/ceph/ceph/blob/master/src/script/ceph-backport.sh

---

Also backport https://tracker.ceph.com/issues/54176

### CODE REVIEW

**Comment by MrFreezeex** [comment]
Those are the same jsonnet files from master (so same dashboards essentially). There were small fixes in these files that are not brought in the pacific branch:
      monitoring/ceph-mixin/dashboards_out/osds-overview.json
      monitoring/ceph-mixin/dashboards_out/pool-overview.json
      monitoring/ceph-mixin/dashboards_out/rbd-details.json

I wasn't able to find the backport that was not done, quickly looking at the tracker there was nothing that looks related... It's really small so maybe it's fine like that?

**Comment by aaSharma14** [comment]
jenkins test dashboard

**Comment by aaSharma14** [comment]
jenkins test dashboard

**Comment by epuertat** [comment]
The commits in this PR will be delivered in https://github.com/ceph/ceph/pull/45980. Closing.

**Pull request closed without merging**
