### PR TITLE
Doc: Fixed command syntax error for creating secret keys

### PR DESCRIPTION
**Pull request by YankunLi**
Signed-off-by: YankunLi <lioveni99@gmail.com>

- [ ] References tracker ticket
- [x] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by YankunLi** [comment]
Hi @cbodley I don't seem to have caused the mistake

**Comment by cbodley** [comment]
no worries, the 'make check (arm64)' failures happen on master too

**Comment by YankunLi** [comment]
> no worries, the 'make check (arm64)' failures happen on master too

OK， thinks！

**Comment by ukernel** [comment]
code in current master branch does not request explict 'allow'

**Comment by batrick** [comment]
@ukernel @YankunLi so does this only affect luminous?

**Comment by batrick** [comment]
The command works in Luminous. I'm closing this as the change does not appear to be necessary.

**Pull request closed without merging**
