### PR TITLE
mgr/dashboard: introduce multi cluster management and monitoring in ceph dashboard 

### PR DESCRIPTION
**Pull request by aaSharma14**
introduce multi cluster management and monitoring in ceph dashboard

Signed-off-by: Aashish Sharma <aasharma@redhat.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Comment by aaSharma14** [comment]
jenkins test make check

**Comment by aaSharma14** [comment]
jenkins test make check

**Comment by nizamial09** [comment]
jenkins test dashboard

**Comment by nizamial09** [comment]
jenkins test dashboard cephadm

**Comment by nizamial09** [comment]
jenkins retest this please

**Comment by nizamial09** [comment]
@aaSharma14 this looks like an actual e2e failure
```
  Shared pages
    ✓ should display the vertical menu by default
    ✓ should hide the vertical menu
    1) should navigate to the correct page


  2 passing (4m)
  1 failing

  1) Shared pages
       should navigate to the correct page:
     AssertionError: Timed out retrying after 120000ms: Expected to find content: 'Pools' within the element: <li.nav-item.tc_menuitem_multi_cluster> and with the selector: 'ul.list-unstyled li a' but never did.
      at Context.eval (cypress/e2e/ui/navigation.po.ts:93:11)

```

**Comment by nizamial09** [comment]
jenkins test make check

**Comment by nizamial09** [comment]
the e2e error is still there btw
```
    1) should navigate to the correct page


  2 passing (4m)
  1 failing

  1) Shared pages
       should navigate to the correct page:
     AssertionError: Timed out retrying after 120000ms: Expected to find content: 'Pools' within the element: <li.nav-item.tc_menuitem_multi_cluster.active> and with the selector: 'ul.list-unstyled li a' but never did.
      at Context.eval (cypress/e2e/ui/navigation.po.ts:100:11)
 ```

**Review by nizamial09 — APPROVED** [review]

**Pull request merged**
