### PR TITLE
rgw/cmake: stop building all of radosgw a shared lib

### PR DESCRIPTION
**Pull request by cbodley**
Fixes: https://tracker.ceph.com/issues/57050

this reverts most of https://github.com/ceph/ceph/pull/32404

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by cbodley** [comment]
@kalebskeithley it's unfortunate that we have to backtrack on zipper here, but loadable modules shouldn't require *all* of radosgw to be in a shared library. we should only need to expose a relatively small number of dependencies to sal modules

**Comment by cbodley** [comment]
ceph test api

**Review by dang — APPROVED** [review]
I have to admit, I don't understand how this fixes things, but if it gets us back to passing, we can work around other issues later.

**Comment by cbodley** [comment]
> I have to admit, I don't understand how this fixes things, but if it gets us back to passing, we can work around other issues later.

it's not exactly clear to me either. the segfault was in `std::locale::operator==(std::locale const&) const () from /usr/lib/ceph/libceph-common.so.2`, but there was another copy of libstdc++ linked into the `libradosgw.so`. `std::locale` manages global state - maybe only one of them gets initialized, or they somehow disagree on that state?

**Comment by cbodley** [comment]
jenkins test api

**Comment by cbodley** [comment]
passed qa https://pulpito.ceph.com/cbodley-2022-08-09_17:54:34-rgw-wip-cbodley-testing-distro-default-smithi/

**Pull request merged**
