### PR TITLE
rgw/multisite: testcase for datalog sync across multiple periods

### PR DESCRIPTION
**Pull request by soumyakoduri**
Include a new  multisite test case to verify datalog sync over multiple periods. 

Signed-off-by: Soumya Koduri <skoduri@redhat.com>

### CODE REVIEW

**Comment by tchaikov** [comment]
jenkins retest this please

**Review by adamemerson — APPROVED** [review]

**Review by cbodley — COMMENTED** [review]
not sure this is really a useful test case. we have `test_multi_period_incremental_sync()` for metadata sync, where we track a separate mdlog for each period - so it tests the logic that transitions between different mdlog periods

for data sync we only have the global datalog, so there isn't any transition logic to test

**Comment by ivancich** [comment]
@soumyakoduri I'm going to test this. But please edit the initial comment so it's in the correct format, so it's ready to merge if testing passes. Thanks!!

**Comment by soumyakoduri** [comment]
> @soumyakoduri I'm going to test this. But please edit the initial comment so it's in the correct format, so it's ready to merge if testing passes. Thanks!!

Thanks Casey & Eric. This testcase needs some cleanup.
With mdlog fifo changes (https://github.com/ceph/ceph/pull/37251),  'test_multi_period_incremental_sync' (- mdlog sync over multiple periods ) was failing and hence had added this testcase to test &verify the same scenario for datalog sync as well. 
This new testcase was also failing on the master branch then (haven't RCA'ed it ). I am not sure if it succeeds now.

**Comment by cbodley** [comment]
> not sure this is really a useful test case. we have `test_multi_period_incremental_sync()` for metadata sync, where we track a separate mdlog for each period - so it tests the logic that transitions between different mdlog periods
> 
> for data sync we only have the global datalog, so there isn't any transition logic to test

i still don't think this PR is worth pursuing. sync of the datalog doesn't have any interesting behavior around transitions from one period to another, unlike the mdlog which tracks separate objects for each

and this new test case is still using the 'mdlog list' and 'mdlog autotrim' commands (not 'datalog'), so i don't think it's really testing what you expect it to

**Comment by soumyakoduri** [comment]
> > not sure this is really a useful test case. we have `test_multi_period_incremental_sync()` for metadata sync, where we track a separate mdlog for each period - so it tests the logic that transitions between different mdlog periods
> > for data sync we only have the global datalog, so there isn't any transition logic to test
> 
> i still don't think this PR is worth pursuing. sync of the datalog doesn't have any interesting behavior around transitions from one period to another, unlike the mdlog which tracks separate objects for each
> 
> and this new test case is still using the 'mdlog list' and 'mdlog autotrim' commands (not 'datalog'), so i don't think it's really testing what you expect it to

got it ..thanks!

**Pull request closed without merging**
