### PR TITLE
rgw: support obj encryption stack on compression

### PR DESCRIPTION
**Pull request by Zhiwei-Dai**
add implementation for obj encryption stack on compression. Compressing first and then encrypting.

Fixes: https://tracker.ceph.com/issues/19988

Signed-off-by: Dai Zhiwei daizhiwei3@huawei.com
Signed-off-by: luo rixin luorixin@huawei.com

### CODE REVIEW

**Comment by Zhiwei-Dai** [comment]
Security and trustworthiness framework of ceph is important for data storage. Now, cephx and https base on openssl enhance the security of transport layer, and rgw encrytion implementation supports data protection for object store.
Nevertheless, as issues said, #36539, space usage and data security are exclusive.
`New compression and encryption filters do not stack, but logically could do so. Users must choose between at rest data reduction and data security.`
The pr solves this problem. Why compressing first and then encrypting, discussion about data encryption and compression has answer
https://crypto.stackexchange.com/questions/33737/is-it-better-to-encrypt-before-compression-or-vice-versa

**Comment by mattbenjamin** [comment]
@Zhiwei-Dai sorry, can you rebase please?

**Comment by Zhiwei-Dai** [comment]
@mattbenjamin OK, I have recommitted the pr because of base repository lost. #38639

**Comment by Zhiwei-Dai** [comment]
close since [#46188](https://github.com/ceph/ceph/pull/46188) could replace it.

**Pull request closed without merging**
