### PR TITLE
nautilus: osd: take heartbeat_lock when calling heartbeat()

### PR DESCRIPTION
**Pull request by pdvian**
http://tracker.ceph.com/issues/39514

### CODE REVIEW

**Comment by smithfarm** [comment]
```
[ 97%] Building CXX object src/test/librbd/CMakeFiles/unittest_librbd.dir/managed_lock/test_mock_GetLockerRequest.cc.o
/usr/bin/ld: warning: libboost_context.so.1.67.0, needed by //opt/ceph/lib/x86_64-linux-gnu/libboost_coroutine.so.1.67.0, not found (try using -rpath or -rpath-link)
//opt/ceph/lib/x86_64-linux-gnu/libboost_coroutine.so.1.67.0: undefined reference to `jump_fcontext'
//opt/ceph/lib/x86_64-linux-gnu/libboost_coroutine.so.1.67.0: undefined reference to `make_fcontext'
collect2: error: ld returned 1 exit status

Link Error: RGW library not found
src/pybind/rgw/CMakeFiles/cython_rgw.dir/build.make:57: recipe for target 'src/pybind/rgw/CMakeFiles/cython_rgw' failed
make[3]: *** [src/pybind/rgw/CMakeFiles/cython_rgw] Error 1
```

**Comment by smithfarm** [comment]
Note that nautilus PRs are not building currently... the failure is almost certainly not related to the patch in this PR.

**Comment by smithfarm** [comment]
jenkins re-test this please

**Comment by yuriw** [comment]
[wip-yuri3-testing-2019-05-23-2026-nautilus](https://trello.com/c/ofkznvrv/618-wip-yuri3-testing-2019-05-23-2026-nautilus)

**Pull request merged**
