### PR TITLE
reef: osd: mClock recovery/backfill cost fixes

### PR DESCRIPTION
**Pull request by sseshasa**
This PR addresses the issue of slow backfill/recoveries due to non-ideal
cost settings for recovery/backfill operations. 

This is a backport of PR: https://github.com/ceph/ceph/pull/49975.

The following summarizes the changes:

1. Set cost for PGRecovery item based on average size of objects in PG.
2. Set cost for PGRecoveryContext item (Replicated and EC backend) based on the aggregate cost of impending pushes.
3. PushReplyOp cost set to min cost and PullOp cost is set based on the remaining bytes to be pushed.
4. Modify IO cost model to incorporate device characteristics like random write IOPS and sequential bandwidth capacity.
5. Represent QoS cost in terms bytes instead of secs.
6. Consider degraded object recoveries with greater urgency than backfill recovery. 
7. Categorize backfill operations as best-effort client.
8. Change QoS parameter allocation in terms of proportions and optimize mClock profiles.
9. Set 'balanced' profile as the default mClock profile.
10. Restore backfill/recovery limits to original defaults.
11. Update mClock configuration document to reflect all the changes.

NOTE: Corresponding reef trackers will be created. Currently the below
trackers are used to track changes in 'main' branch.

Fixes: https://tracker.ceph.com/issues/58529
Fixes: https://tracker.ceph.com/issues/58606
Fixes: https://tracker.ceph.com/issues/58607
Fixes: https://tracker.ceph.com/issues/59080
Signed-off-by: Samuel Just <sjust@redhat.com>
Signed-off-by: Sridhar Seshasayee <sseshasa@redhat.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [x] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [x] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by sseshasa** [comment]
jenkins test make check

**Comment by sseshasa** [comment]
jenkins test make check

**Comment by sseshasa** [comment]
**Rados Suite Run:**
This is after introducing additional changes summarized below:
1. Consider backfill ops as best-effort client of mClock
2. Give greater urgency to degraded recovery ops 
3. Set 'balanced' profile as the default mClock profile
4. Change mClock profile allocations in view of the above changes
5. For the tests, set 'high_recovery_ops' as the running profile for OSDs

**Original Run:**
https://pulpito.ceph.com/sseshasa-2023-05-01_11:18:49-rados-wip-sseshasa3-testing-2023-05-01-1420-distro-default-smithi/

**Final Result across runs:** 12/312 Failed

Fixed issue in the standalone scrub tests to ensure 'high_recovery_ops' profile is active after OSDs restart within tests.

**Re-run Failed Jobs:**
https://pulpito.ceph.com/sseshasa-2023-05-02_03:12:27-rados-wip-sseshasa3-testing-2023-05-01-2154-distro-default-smithi/

**Re-run Dead Jobs:**
https://pulpito.ceph.com/sseshasa-2023-05-02_03:13:48-rados-wip-sseshasa3-testing-2023-05-01-2154-distro-default-smithi/
 
**Unrelated Failures:**
There were infra related failures and the following unrelated failures:

1. https://tracker.ceph.com/issues/59057 - rados/test_envlibrados_for_rocksdb.sh: No rule to make target 'rocksdb_env_librados_test' on centos 8
2.  https://tracker.ceph.com/issues/57754 - test_envlibrados_for_rocksdb.sh: update-alternatives: error: alternative path /usr/bin/gcc-11 doesn't exist
3. https://tracker.ceph.com/issues/59142 - mgr/dashboard: fix e2e for dashboard v3
4. https://tracker.ceph.com/issues/59597 - test_envlibrados_for_rocksdb.sh: 'cannot install the best candidate for the job' error when installing gcc-c++.x86_64
5. https://tracker.ceph.com/issues/59196 - ceph_test_lazy_omap_stats segfault while waiting for active+clean

**Review by athanatos — APPROVED** [review]

**Comment by sseshasa** [comment]
jenkins test make check

**Pull request merged**
