### PR TITLE
cephadm: Add alertmanager adopt

### PR DESCRIPTION
**Pull request by swiftgist**
Signed-off-by: Eric Jackson <swiftgist@gmail.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by swiftgist** [comment]
Note that this is based on the prometheus-alertmanager package which works for SUSE and Ubuntu.  I need confirmation if this is suitable for RedHat.

**Comment by liewegas** [comment]
I have a general question.. what kind of state does alertmanager have?  If it doesn't have any, it's probably easier to just throw out the old one and provision a new one.  Adoption should only really be important for mon and osd... and maybe mgr in order to get a fresh cephadm 'bootstrapped'.

**Comment by jsuchenia** [comment]
@liewegas AlertManager stores timestamp of first alert occurrence, list of all silents and peers - so it's not a critical datastore but worth to preserve it during upgrade

**Comment by liewegas** [comment]
please rebase and retarget octopus?

**Comment by sebastian-philipp** [comment]
> please rebase and retarget octopus?

actually, I think it would make sense to target master now.

**Pull request merged**
