### PR TITLE
osd/ECBackend: don't get result code of subchunk-read overwritten

### PR DESCRIPTION
**Pull request by Songweibin**
Fixes: http://tracker.ceph.com/issues/21769

Signed-off-by: songweibin <song.weibin@zte.com.cn>

### CODE REVIEW

**Comment by Songweibin** [comment]
retest this please

**Comment by Songweibin** [comment]
@dzafman  ping? Rebased from master. Thank you.

**Comment by xiexingguo** [comment]
retest this please

**Comment by Songweibin** [comment]
@dzafman  I think when `r < 0` and break the internal `for` loop, it will break the external loop as well since `error` is true, so the error code of `r` will not be overwritten. Thank you.

**Comment by dzafman** [comment]
@Songweibin Oops, I didn't see the "&& !error" in the for(;;)

**Comment by Songweibin** [comment]
@dzafman  Eh -- I didn't see this tracker and PR (https://github.com/ceph/ceph/pull/18266) before. Already add tracker info to the commit comment. Thank you.

**Comment by dzafman** [comment]
@Songweibin Let's put this through a rados suite run.

**Pull request merged**
