### PR TITLE
osd: a few fast dispatch optimizations

### PR DESCRIPTION
**Pull request by liewegas**

### CODE REVIEW

**Comment by liewegas** [comment]
retest this please

**Comment by dachary** [comment]
test this please (eio)

**Comment by yuriw** [comment]
test this please

**Comment by dachary** [comment]
jenkins test this please (eio now ignored on master)

**Comment by yuriw** [comment]
http://pulpito.ceph.com/yuriw-2016-11-22_16:38:08-rados-wip-yuri-testing2_2016_11_21-distro-basic-smithi/

http://pulpito.ceph.com/yuriw-2016-11-22_16:38:08-rados-wip-yuri-testing2_2016_11_21-distro-basic-smithi/

**Pull request merged**
