### PR TITLE
[WIP] octopus: mgr/dashboard: Create Ceph services via Orchestrator by using ServiceSpec

### PR DESCRIPTION
**Pull request by callithea**
backport tracker: https://tracker.ceph.com/issues/46963

---

backport of https://github.com/ceph/ceph/pull/36119
parent tracker: https://tracker.ceph.com/issues/44831

this backport was staged using ceph-backport.sh version 15.1.1.389
find the latest version at https://github.com/ceph/ceph/blob/master/src/script/ceph-backport.sh

### CODE REVIEW

**Comment by callithea** [comment]
jenkins test make check

**Comment by votdev** [comment]
I fear this PR needs some refactoring because it is based on https://github.com/ceph/ceph/commit/d3436f068b51a1cc82a0e76d43d92663f5c461f7#diff-58cac1cb522e0d3844bc1b5652499772 which is not available in Octopus (til now).

**Comment by callithea** [comment]
jenkins test make check

**Comment by callithea** [comment]
jenkins test make check

**Comment by callithea** [comment]
Latest failure:
```
[build:en-US -- -- --progress=false] ERROR in app/ceph/cluster/services/service-form/service-form.component.ts:227:47 - error TS2339: Property 'typeahead' does not exist on type 'ServiceFormComponent'.
[build:en-US -- -- --progress=false] 
[build:en-US -- -- --progress=false] 227       this.labelClick.pipe(filter(() => !this.typeahead.isPopupOpen()))
[build:en-US -- -- --progress=false]                                                   ~~~~~~~~~
[build:en-US -- -- --progress=false] app/ceph/cluster/services/service-form/service-form.component.ts:240:45 - error TS2315: Type 'ProgressEvent' is not generic.
[build:en-US -- -- --progress=false] 
[build:en-US -- -- --progress=false] 240     reader.addEventListener('load', (event: ProgressEvent<FileReader>) => {
[build:en-US -- -- --progress=false]                                                 ~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by votdev** [comment]
Superseded by https://github.com/ceph/ceph/pull/38888.

**Pull request closed without merging**
