### PR TITLE
osd/OSD: apply_changes() updated by "config set"

### PR DESCRIPTION
**Pull request by gmayyyha**
Fixes: http://tracker.ceph.com/issues/20803

Signed-off-by: Yanhu Cao <gmayyyha@gmail.com>

### CODE REVIEW

**Comment by gmayyyha** [comment]
```c
[root@ceph14 build]# ceph daemon osd.0 dump_reservations
{
    "local_reservations": {
        "max_allowed": 10,
        "min_priority": 0,
        "queues": [],
        "in_progress": []
    },
    "remote_reservations": {
        "max_allowed": 10,
        "min_priority": 0,
        "queues": [],
        "in_progress": []
    }
}
[root@ceph14 build]# ceph tell osd.0 config set osd_max_backfills 9
2017-07-31 13:11:47.000115 7fe6cf543700 -1 WARNING: all dangerous and experimental features are enabled.
2017-07-31 13:11:47.159317 7fe6cf543700 -1 WARNING: all dangerous and experimental features are enabled.
Set osd_max_backfills to 9
osd_max_backfills = '9' 
[root@ceph14 build]# ceph daemon osd.0 dump_reservations
{
    "local_reservations": {
        "max_allowed": 9,
        "min_priority": 0,
        "queues": [],
        "in_progress": []
    },
    "remote_reservations": {
        "max_allowed": 9,
        "min_priority": 0,
        "queues": [],
        "in_progress": []
    }
}
```

**Comment by varadakari** [comment]
@gmayyyha i think you are looking at different values, can you please check "config get" on the same variable?

**Comment by gmayyyha** [comment]
@varadakari observers need to know the configuration options that they care about which have changed.

**Comment by varadakari** [comment]
@gmayyyha got it! thanks. LGTM

**Comment by tchaikov** [comment]
@gmayyyha

could you revise the title of your commit message?
```
ceph tell osd.N config set osd_max_backfill does not work
```

reads like a bug a report, but not a summary of a patch or a commit.

**Comment by gmayyyha** [comment]
@tchaikov sorry to make confused. done.

**Comment by gmayyyha** [comment]
retest this please

**Comment by gmayyyha** [comment]
retest this please

**Comment by tchaikov** [comment]
- http://pulpito.ceph.com/kchai-2017-07-31_14:22:05-rados-wip-kefu-testing-distro-basic-mira/
- http://pulpito.ceph.com/kchai-2017-08-01_01:45:00-rados-wip-kefu-testing-distro-basic-mira/
- http://pulpito.ceph.com/kchai-2017-08-01_08:12:19-rados-wip-kefu-testing-distro-basic-smithi/

**Comment by tchaikov** [comment]
@gmayyyha this PR passes the rados qa tests, but #16700 fixes the mds and mon also. i have no strong preference on either fix. @liewegas what do you think?

**Comment by liewegas** [comment]
I'm not sure the apply_changes stream arg is needed with set_val also says what it did (and apply_changes may race with something else i suppose).  I'd go with #16700

**Comment by tchaikov** [comment]
@gmayyyha thanks for identifying the issue and for fixing it. closing in favor of #16700

**Pull request closed without merging**
