### PR TITLE
msg: default to debug_ms=0

### PR DESCRIPTION
**Pull request by liewegas**
These have a measurable impact on performance and have a limited (although
not non-existent!) track record of providing debugging value.

### CODE REVIEW

**Comment by liewegas** [comment]
Re-reading our last discussion on this from August, we didn't come to a clear conclusion.  I note that upon re-reading, @gregsfortytwo's objection doesn't seem as vehement as I remember :)

https://marc.info/?t=153425788600001&r=1&w=2

**Comment by dillaman** [comment]
I'm all for it. I've already set it to 0/0 for non-daemons [1], so I guess that kludge could be removed now.

[1] https://github.com/ceph/ceph/commit/a3a40413f7908b08c40dec4020034cca4a0c4798#diff-bf7584882a8a115d30fcdbdcde26b64a

**Comment by gregsfortytwo** [comment]
I may have said something stronger in a videoconference than I did over email?
Anyway, I'm still disturbed about it. I'd much rather we
1) Make a simple dump of messages (presumably with a more consistent format and less customization of the outputs) that is a lot cheaper to generate
2) at least generate those message dumps in memory, though not anything else in the messenger.

But if nobody else finds these messages useful in debugging I'm not going to stand in the way. It's possible their utility has dropped as we improve other things.

**Comment by batrick** [comment]
@rzarzynski 's analysis is probably somewhat out-of-date with the changes I made last September. Logging avoids most heap allocations now which was killer for performance. Personally, I'd rather us do `debug_ms=0/1` as a stepping stone first.

**Comment by rzarzynski** [comment]
@batrick: I recall that one of the problems was the [costly calls to `getnameinfo`](https://gist.github.com/rzarzynski/21cc66dbcc1d62edcbc9afa56210b8d8). Maybe, at the expense of some complexity increase, we could introduce caching. Alternative is to change logging format or lower levels.

Still, I can say nothing about the actual value of those messages. :-( What about asking people from customer support?

**Comment by liewegas** [comment]
This latest resurrection of the topic was prompted my @markhpc 's profiling in CPU-limited situations, where he saw:

1) ProtocolV2::write_message is spending around half it's time in ceph::logging::Log::submit_entry waiting on a lock and another quarter of it's time doing ostream appends in: 
      - ProtocolV2::_conn_prefix
      - In some cases this is worse with slow calls to getnameinfo
      - ProtocolV2::write_message itself.

2) More overhead in ostream appends in fast_dispatch:
   - DispatchQueue::pre_dispatch
   - DispatchQueue::post_dispatch

3) and at a higher level in ProtocolV2::handle_message_complete()

tp_osd_tp:

1) More ostream appends in AsyncConnection::send_message

2) More time spent waiting on a lock in ceph::logging::Log::submit_entry in AsyncConnection::send_message

3) More time sent in ProtocolV2::_conn_prefix (not much, but it adds up!) in AsyncConnection::send_message (via ProtcolV2::send_message)

**Comment by liewegas** [comment]
@markhpc can you repeat that profiling with debug_ms=0?

**Comment by markhpc** [comment]
Hi Folks, I added support for reverse callgraphs in gdbpmp and pasted some of the profiling data for these runs in the perf meeting for last week:

 - normal output: https://paste.fedoraproject.org/paste/jIoPAz6e9adF9oze1F0Z6A
 - inverse output: https://paste.fedoraproject.org/paste/8K~7EumDcq4fHrdzXV3ZbA

More importantly though, our attempts to use inet_ntop directly didn't really help much:

https://docs.google.com/spreadsheets/d/1Zi3MFtvwLzCFfObL6evQKYtINQVQIjZ0SXczG78AnJM/edit?usp=sharing

I'm looking into it further and will try playing around with a couple of ideas, but right now this is the performance impact we're seeing on the incerta nodes under CPU constrained scenarios.

**Comment by markhpc** [comment]
Looks like the past expired, so I've attached both the normal and inverted callgraphs for the debug_ms=0 and debug_ms=1 cases.
[debug_ms-1_normal.txt](https://github.com/ceph/ceph/files/2997104/debug_ms-1_normal.txt)
[debug_ms-1_inverted.txt](https://github.com/ceph/ceph/files/2997105/debug_ms-1_inverted.txt)
[debug_ms-0_normal.txt](https://github.com/ceph/ceph/files/2997106/debug_ms-0_normal.txt)
[debug_ms-0_inverted.txt](https://github.com/ceph/ceph/files/2997107/debug_ms-0_inverted.txt)

**Comment by tchaikov** [comment]
@markhpc i have 404 when trying to access the normal and inverse outputs.

**Pull request merged**
