### PR TITLE
common: extend Formatter API with a unique_ptr-returning static function

### PR DESCRIPTION
**Pull request by ronen-fr**
The necessity of such an interface is evident from the multiple instances 
in the code (mostly in testing code, but not just there) of the following short sequence:
- dyn-allocating a Formatter;
- using it in its 'naked pointer' form;
- deleting it;
which is not a recommended practice.

Signed-off-by: Ronen Friedman <rfriedma@redhat.com>

### CODE REVIEW

**Comment by Matan-B** [comment]
LGTM, can you please update few instances? (as an example for future users)

**Comment by ronen-fr** [comment]
> LGTM, can you please update few instances? (as an example for future users)

done

**Comment by Matan-B** [comment]
```
/home/jenkins-build/build/workspace/ceph-pull-requests/src/osd/PrimaryLogPG.cc:15078:23: error: no viable conversion from 'std::unique_ptr<Formatter>' to 'ceph::Formatter *'
    agent_state->dump(f);
                      ^
/home/jenkins-build/build/workspace/ceph-pull-requests/src/osd/TierAgentState.h:117:30: note: passing argument to parameter 'f' here
  void dump(ceph::Formatter *f) const {
```

Missed this line: `agent_state->dump(f.get());`

**Review by Matan-B — APPROVED** [review]

**Comment by ljflores** [comment]
Rados suite review: https://pulpito.ceph.com/?branch=wip-yuri-testing-2023-01-23-0926

Failures, unrelated:
    1. https://tracker.ceph.com/issues/58587 -- new tracker
    2. https://tracker.ceph.com/issues/58585
    3. https://tracker.ceph.com/issues/58098 -- fix merged to latest main
    4. https://tracker.ceph.com/issues/58256 -- fix merged to latest main
    5. https://tracker.ceph.com/issues/57900
    6. https://tracker.ceph.com/issues/58475
    7. https://tracker.ceph.com/issues/58560

Details:
    1. test_dedup_tool.sh: test_dedup_object fails when pool 'dedup_chunk_pool' does not exist - Ceph - RADOS
    2. rook: failed to pull kubelet image - Ceph - Orchestrator
    3. qa/workunits/rados/test_crash.sh: crashes are never posted - Ceph - RADOS
    4. ObjectStore/StoreTestSpecificAUSize.SpilloverTest/2: Expected: (logger->get(l_bluefs_slow_used_bytes)) >= (16 * 1024 * 1024), actual: 0 vs 16777216 - Ceph - RADOS
    5. mon/crush_ops.sh: mons out of quorum - Ceph - RADOS
    6. test_dashboard_e2e.sh: Conflicting peer dependency: postcss@8.4.21 - Ceph - Mgr - Dashboard
    7. test_envlibrados_for_rocksdb.sh failed to subscrib repo - Ceph

**Pull request merged**
