### PR TITLE
mimic: test: fix CLI unit formatting tests

### PR DESCRIPTION
**Pull request by liewegas**

### CODE REVIEW

**Comment by liewegas** [comment]
http://pulpito.ceph.com/sage-2018-05-27_17:12:12-upgrade:luminous-x-wip-sage3-testing-2018-05-27-0958-distro-basic-smithi/

**Comment by yuriw** [comment]
We need this on `jewel` and `luminous`

**Comment by smithfarm** [comment]
@yuriw I created http://tracker.ceph.com/issues/24733 and the associated backport tracker issues. Regarding the luminous and jewel backports, could you please post links to the luminous and jewel test failures? The commits do not cherry-pick cleanly, so I need cross-check my conflict resolution against the logs of the failed tests. Thanks!

**Comment by yuriw** [comment]
@smithfarm 
http://pulpito.ceph.com/teuthology-2018-07-02_01:50:02-upgrade:client-upgrade-luminous-mimic-distro-basic-smithi/
http://pulpito.ceph.com/teuthology-2018-07-02_01:47:03-upgrade:client-upgrade-jewel-mimic-distro-basic-smithi/

**Pull request merged**
