### PR TITLE
cephfs-shell: prints warning, hangs and aborts when launched

### PR DESCRIPTION
**Pull request by rishabh-d-dave**
Occured because Python module "pkg_resources" has been deprecated.

Fixes: https://tracker.ceph.com/issues/64538

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Comment by neesingh-rh** [comment]
jenkins test make check

**Review by joscollin — APPROVED** [review]

**Review by neesingh-rh — APPROVED** [review]

**Review by rishabh-d-dave — COMMENTED** [review]
I had to do multiple QA runs and re-runs due to build issues (due to one of the PRs in testing branch), unrelated issues in FS test suite, unrelated issues in testing kernel and new failures in every run that needed to ensured that they were unrelated to PRs in testing branch.

I finally have a run that is better than others - https://tracker.ceph.com/projects/cephfs/wiki/Main#4-Apr-2024. Sorry for the delay.

**Comment by rishabh-d-dave** [comment]
Updated nothing more than the commit title and commit message.

**Comment by rishabh-d-dave** [comment]
Will merge this PR as soon as CI is green for it.

**Comment by rishabh-d-dave** [comment]
On last make check (https://jenkins.ceph.com/job/ceph-pull-requests/132730/), `unittest_posix_bucket_cache` failed. This is unrelated to this PR.

**Comment by rishabh-d-dave** [comment]
jenkins test make check

**Comment by rishabh-d-dave** [comment]
https://github.com/ceph/ceph/pull/55711#pullrequestreview-1979706809

**Pull request merged**
