### PR TITLE
osd: MOSDRepOp and pg_log_entry_t optimization

### PR DESCRIPTION
**Pull request by XinzeChi**
1. reuse payload in MOSDRepOp if all remote peers have same payload
2. reuse pg log encode and checksum from primary

### CODE REVIEW

**Comment by XinzeChi** [comment]
@liewegas , does it make sense?

**Comment by liewegas** [comment]
I think the first patch makes sense, although I don't like that for the 2x case we're moving the encode_payload into the caller (whereas now it happens in the messenger thread).  I get the feeling that we should make this optional, at least initially.

The second patch looks like a lot of complexity.  I think we need to see that it has a measurable impact before considering it.

**Comment by XinzeChi** [comment]
@liewegas , the pg_log_entry_t::encode_with_checksum take up about 1.5% cpu utilization.

**Comment by liewegas** [comment]
@athanatos what do you think?

**Comment by athanatos** [comment]
I think this is too complicated as is.  I also want to see numbers showing the actual difference in performance.  pglog_with_checksum is also problematic because it exposes the keys used by the OSD to write down the PGLog -- currently, that can be changed without a compatibility issue.  At least, I'd want that to be an eversion_t rather than a string.  In such a case, I also do not want PGLog to be filling in the map, the encoded version of the buffer is entirely a function of the log entry and has nothing to do with the larger log.  You'd probably instead just change PGLog to take a map<eversion_t, bufferlist> of the already encoded log entries.  I'm closing this since it would at least require significant changes.  Feel free to open a new one with a simpler approach.

**Pull request closed without merging**
