### PR TITLE
mgr/dashboard: fix user expiration test

### PR DESCRIPTION
**Pull request by bk201**
Currently, the expiration time of a user is recorded in seconds.
If user creation is completed within the second which the test is
started, the test will fail. Relax the check to include this situation.

Fixes: https://tracker.ceph.com/issues/43395
Signed-off-by: Kiefer Chang <kiefer.chang@suse.com>

## Checklist
- [x] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by bk201** [comment]
jenkins test dashboard backend

**Comment by s0nea** [comment]
Hey @bk201 are you sure the issue is still happening since https://github.com/ceph/ceph/pull/32461 has been merged? - The tracker issue was created 20 days ago...

**Comment by callithea** [comment]
> jenkins test dashboard backend

Unfortunately the tests failed (on several PRs), still looking into it:
```Using guessed paths /home/jenkins-build/build/workspace/ceph-dashboard-pr-backend/build/lib/ ['/home/jenkins-build/build/workspace/ceph-dashboard-pr-backend/qa', '/home/jenkins-build/build/workspace/ceph-dashboard-pr-backend/build/lib/cython_modules/lib.3', '/home/jenkins-build/build/workspace/ceph-dashboard-pr-backend/src/pybind']
Traceback (most recent call last):
  File "../qa/tasks/vstart_runner.py", line 1545, in <module>
    exec_test()
  File "../qa/tasks/vstart_runner.py", line 1365, in exec_test
    remote.run(args, env=vstart_env, timeout=(3 * 60))
  File "../qa/tasks/vstart_runner.py", line 390, in run
    proc.wait()
  File "../qa/tasks/vstart_runner.py", line 190, in wait
    raise CommandFailedError(self.args, self.exitstatus)
teuthology.exceptions.CommandFailedError: Command failed with status 127: ['../src/vstart.sh', '-n', '-d', '--nolockdep']
```

**Comment by bk201** [comment]
> Hey @bk201 are you sure the issue is still happening since #32461 has been merged? - The tracker issue was created 20 days ago...

My bad! I saw the issue on tracker in urgent and checked it with my WIP branch.
Thanks for reminding.

**Pull request closed without merging**
