### PR TITLE
By O_RDWR into O_RDONLY fsid open way, prevent fsid_fd is modified

### PR DESCRIPTION
**Pull request by renhwztetecs**
By O_RDWR into O_RDONLY fsid open way, prevent fsid_fd is modified

Fixes: #13289
Signed-off-by: sky_atlantis@sina.com

### CODE REVIEW

**Comment by yuyuyu101** [comment]
please commit your changes with "git -s"

**Comment by renhwztetecs** [comment]
sorry, I don't know how to commit my changes with "git -s"
does GitHub Client  get used? 
Thank you

**Comment by dzafman** [comment]
From your wip-renhw-13289 branch
This will toss away the 2 revert commits that you don't need
# git reset --hard HEAD^^

# git rebase -i HEAD^^
Change both lines word "pick" to "e" and write out and quit editor
Do this to add the Signed-off-by line assuming you have git config correctly

This will add the signed-of-by to the first commit
# git commit --amend -s
Moving on to the next
# git rebase --continue
This will add the signed-of-by to the second commit
# git commit --amend -s
Complete the rebase
# git rebase --continue
"Successfully rebased and updated refs/heads...."

**Comment by renhwztetecs** [comment]
@dzafman 
thank you 
I update it

**Comment by renhwztetecs** [comment]
FileStore::lock_fsid & KeyValueStore::lock_fsid
use  l.l_type = F_WRLCK
I'm not sure whether can be amended as:  l.l_type = F_RDLCK

**Comment by tchaikov** [comment]
@renhwztetecs 

we should not close the fsid in `FileStore::mount()`. because we are supposed to lock the fsid file to prevent two or more ceph-osd instances messing around the same filestore backend at the same time, we can not close the `fsid_fd` before we unmount the filestore.

> I'm not sure whether can be amended as: l.l_type = F_RDLCK

we cannot.  we need to acquire the exclusive lock (wlock) of the fsid file, so we can not open it using `O_RDONLY` mode. if we open it using `O_RDONLY`, the `fcntl()` call fails with `F_WRLCK`.

so i am closing your pull request. please feel free to let me know if i am wrong.

**Comment by renhwztetecs** [comment]
@tchaikov 
You are right
From the design, the purpose of fsid_fd is used in file lock, if closed fsid_fd, then lock file does not exist.
I originally closed fsid_fd or to open O_RDONLY fsid purpose, is to want to handle to fsid_fd may not be rewritten

**Pull request closed without merging**
