### PR TITLE
jewel: build/ops: extended, customizable systemd ceph-disk timeout

### PR DESCRIPTION
**Pull request by asheplyakov**
http://tracker.ceph.com/issues/19910

### CODE REVIEW

**Comment by smithfarm** [comment]
Jenkins re-test this please

**Comment by gaudenz** [comment]
I just got bitten by the timeout issue and had to resort to add a systemd drop-in configuration to increase the timeout. It would be really nice if this could be backported to jewel.

**Comment by smithfarm** [comment]
@asheplyakov Could you please cherry pick into this PR? Thanks!

**Comment by smithfarm** [comment]
This passed a ceph-disk suite at http://tracker.ceph.com/issues/20613#note-9

**Pull request merged**
