### PR TITLE
kraken: osd: condition object_info_t encoding on required (not up) features

### PR DESCRIPTION
**Pull request by shinobu-x**
http://tracker.ceph.com/issues/18814

### CODE REVIEW

**Comment by shinobu-x** [comment]
@smithfarm This time, I'm pretty not sure if I did *some* properly or not.

**Comment by smithfarm** [comment]
@shinobu-x Looks good. Please delete what is currently in the PR description and put there (only) the URL of the backport tracker issue.

**Comment by smithfarm** [comment]
There were no conflicts when you cherry-picked, right?

**Comment by shinobu-x** [comment]
@smithfarm AFAIK I didn't see any conflict. But my brain could have been wrong :)

**Comment by smithfarm** [comment]
@shinobu-x Cool :-) When a cherry-pick produces a conflict, you can't miss it :-)

**Pull request closed without merging**
