### PR TITLE
ocf: drop ceph Resource Agent

### PR DESCRIPTION
**Pull request by smithfarm**
This RA wraps the ceph sysvinit script. As of Jewel, none of the supported
distros are using sysvinit anymore. So, drop it.

Incidentally, Pacemaker can control systemd units without any wrappers.

References: http://tracker.ceph.com/issues/14828
Signed-off-by: Nathan Cutler <ncutler@suse.com>

### CODE REVIEW

**Comment by smithfarm** [comment]
This passed gitbuilder when it was part of #8720

**Comment by tserong** [comment]
LGTM

`Reviewed-by: Tim Serong <tserong@suse.com>`

**Comment by smithfarm** [comment]
Rebased

**Comment by smithfarm** [comment]
@ktdreyer I'm flagging this for backport . . . any objections?

**Comment by ktdreyer** [comment]
Sounds good for backporting

**Pull request merged**
