### PR TITLE
doc/corpus: update to adapt the change from autotools to cmake

### PR DESCRIPTION
**Pull request by tchaikov**
Signed-off-by: Kefu Chai <kchai@redhat.com>

- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by iotcg** [comment]
@tchaikov 
Please update below section at the same time:
       ==> Import the corpus (this will take a few minutes)

**Comment by tchaikov** [comment]
@iotcg updated and repushed.

**Comment by iotcg** [comment]
@tchaikov I'll give feedback later.

**Comment by iotcg** [comment]
@liewegas Hold merge this patch since it still needs to be refined as being said in the comment.

**Comment by tchaikov** [comment]
@iotcg could you be more specific on the suggested change?

**Comment by iotcg** [comment]
"../test" should be "../src/test" when running the command under build directory.

**Comment by tchaikov** [comment]
@iotcg thanks! fixed and repushed.

**Comment by iotcg** [comment]
LGTM

**Pull request merged**
