### PR TITLE
qa/suites/upgrade/jewel-x/point-to-point-x: tweak packages list

### PR DESCRIPTION
**Pull request by smithfarm**
Fixes: http://tracker.ceph.com/issues/19681
Signed-off-by: Nathan Cutler <ncutler@suse.com>

### CODE REVIEW

**Comment by smithfarm** [comment]
Pushed `wip-19681` to Shaman

**Comment by smithfarm** [comment]
`teuthology-suite -k distro --machine-type smithi --priority 101 --email ncutler@suse.com --ceph-repo https://github.com/ceph/ceph --ceph master --suite-repo https://github.com/smithfarm/ceph --suite-branch wip-19681 --suite upgrade/jewel-x/point-to-point-x --newest 10`

**running** http://pulpito.front.sepia.ceph.com:80/smithfarm-2017-07-08_17:37:34-upgrade:jewel-x:point-to-point-x-master-distro-basic-smithi/

**Comment by liewegas** [comment]
Hmm is this still needed?

**Comment by smithfarm** [comment]
@liewegas Nope.

**Pull request closed without merging**
