### PR TITLE
mgr/progress/module.py: s/events/_events/

### PR DESCRIPTION
**Pull request by kamoltat**
Fixes time out failure because the module was trying to accessing 
attribute `events` line 437 in this block of code:

 

435         if marked == "in":
436             for ev_id in list(self._events):
437                 ev = self.events[ev_id]
438                 if isinstance(ev, PgRecoveryEvent) and osd_id in ev.which_osds:
439                     self.log.info("osd.{0} came back in, cancelling event".format(
440                         osd_id
441                     ))
442                     self._complete(ev)

Therefore, it wouldn't trigger an event

Fixes: https://tracker.ceph.com/issues/40618

Signed-off-by: Kamoltat (Junior) Sirivadhna <ksirivad@redhat.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test docs`
- `jenkins render docs`

</details>

### CODE REVIEW

**Comment by tchaikov** [comment]
@kamoltat thanks Junior, i think we can improve your commit message in two ways.

the title could be more concise: i'd suggest put something like

> mgr/progress/module.py: s/events/_events/

might want to make the fix issue line more consistent with our convention, so it could be

> Fixes: https://tracker.ceph.com/issues/40618

and, i don't quite understand how this change could address the failure of http://pulpito.ceph.com/kchai-2019-08-12_14:45:48-rados-wip-kefu-testing-2019-08-12-1306-distro-basic-mira/4211314/. even although it's correct and fix another issue.

as the failure is that 
```py
        self.wait_until_equal(lambda: len(self._events_in_progress()), 1,
                              timeout=self.EVENT_CREATION_PERIOD)
```
timed out after 5 seconds. not because of an `AttributeError` exception.

**Comment by kamoltat** [comment]
> @kamoltat thanks Junior, i think we can improve your commit message in two ways.
> 
> the title could be more concise: i'd suggest put something like
> 
> > mgr/progress/module.py: s/events/_events/
> 
> might want to make the fix issue line more consistent with our convention, so it could be
> 
> > Fixes: https://tracker.ceph.com/issues/40618
> 
> and, i don't quite understand how this change could address the failure of http://pulpito.ceph.com/kchai-2019-08-12_14:45:48-rados-wip-kefu-testing-2019-08-12-1306-distro-basic-mira/4211314/. even although it's correct and fix another issue.
> 
> as the failure is that
> 
> ```python
>         self.wait_until_equal(lambda: len(self._events_in_progress()), 1,
>                               timeout=self.EVENT_CREATION_PERIOD)
> ```
> 
> timed out after 5 seconds. not because of an `AttributeError` exception.

@tchaikov Hi Kefu, sorry for the bad commit message, will change it now. As for why correcting the attribute name leads to fixing, I tested this on my local machine by marking osd in and out and observing the event creation. So with the incorrect attributte name, the progress module still kept on going, only notify that it couldn't access the variable once. Therefore this leads to me thinking that fixing this attribute error would fix the problem but I could be wrong.

**Comment by kamoltat** [comment]
@tchaikov Just to follow up on this, I think you are right that this is not a fix for Time out for 5 seconds. Will investigate further into this

**Comment by tchaikov** [comment]
@kamoltat please note the commit message is different from the first comment in a PR. probably you could revise your commit using `git commit --amend` and repush to update your PR?

**Comment by tchaikov** [comment]
- http://pulpito.ceph.com/kchai-2019-08-16_15:30:43-rados-wip-kefu-testing-2019-08-16-2103-distro-basic-mira/
- http://pulpito.ceph.com/kchai-2019-08-19_10:42:03-rados-wip-kefu-testing-2019-08-16-2103-distro-basic-smithi/
- http://pulpito.ceph.com/kchai-2019-08-20_11:55:18-rados-wip-kefu-testing-2019-08-20-1558-distro-basic-smithi/

**Pull request merged**
