### PR TITLE
os/bluestore: avoid race between split_cache and get/put pin/unpin

### PR DESCRIPTION
**Pull request by liewegas**
The Onode get() and put() methods may call pin() and unpin() when we
transition between 1 and >1 ref.  To do this they make use of the
OSDShard *s pointer without taking any additional locks.  This runs afoul
of Collection::split_cache(), which moves an onode between shards.

It would be very complicated to address this race head-on: we ultimately
need to be under the protction of the OSDShard lock to do the pin/unpin,
but if OSDShard *s is changing, we don't know which lock to take.  And if
it is null, what do we do?  It might be null when we test but then get
set by split_cache.  And what if there is a put() followed by a get(),
and they managed to acquire the appropriate lock(s), but the get() thread
gets it first?  And so on.

We can avoid this whole mess by preventing a put() or get() from making
this transition (and looking at OSDShard *s) at all--we simply have to
take an additional ref in split_cache() so that we are certain nref >= 2.

Fixes: https://tracker.ceph.com/issues/43147
Fixes: https://tracker.ceph.com/issues/43131
Signed-off-by: Sage Weil <sage@redhat.com>

### CODE REVIEW

**Comment by liewegas** [comment]
> So this feels pretty hacky to me, but the only alternatives I can think of are:
> 
> 1. a new lock in the onode to fully protect s
> 2. we make s write-once, don't allow a given onode to migrate between caches, and protect s via DCLP ala https://preshing.com/20130930/double-checked-locking-is-fixed-in-cpp11/
> 
> 2 would be faster than 1 for reads but still slow for Onode cache insertion.
> 
> In the end Sage is probably right that this is the better approach though we should probably document that the onode's get/put methods are not thread-safe in the Onode struct. We may still want the slight optimization from #32536

After looking at this a bit more closely, the only reasdon nref ever was allows to drop below 2 in the first place was the subtle ordering of the update.  Before, we would

1. remove from old collection onode_map
2. fiddle with osd shard
3. add to new collection onode_map

The fix just changes this ordering to

1. remove from old collection onode_map
2. add to new collection onode_map
3. fiddle with osd shard

and we now know that nref is always >= 2 while the osdshard fiddling is going on and the race is no longer possible.

**Comment by markhpc** [comment]
@liewegas So the new version of this PR looks almost exactly like https://github.com/ceph/ceph/pull/32536 but with o->c = dest moved to happen between _rm and _add.  Is there something I'm missing where moving that line resolves the assert we hit there?

**Comment by liewegas** [comment]
The problem is that in that PR, line 3739 needs to happen before _rm and _add calls.  That's what keeps nref >= 2 at all times.

**Comment by markhpc** [comment]
@liewegas I must be missing something, I think that's exactly what's in the other PR?

https://github.com/ceph/ceph/blob/598208daf2dbb51ad31fd542d82b3a263c87128a/src/os/bluestore/BlueStore.cc#L3734-L3740

**Comment by liewegas** [comment]
> @liewegas I must be missing something, I think that's exactly what's in the other PR? Does the placement of the o->c = dest line matter here?
> 
> https://github.com/ceph/ceph/blob/598208daf2dbb51ad31fd542d82b3a263c87128a/src/os/bluestore/BlueStore.cc#L3734-L3740
> 
> vs
> 
> https://github.com/ceph/ceph/blob/828da5b672e5941c8b4f30e85e29709bc6eac7b3/src/os/bluestore/BlueStore.cc#L3739-L3750

Hmm, yeah my reading is that the other PR at https://github.com/ceph/ceph/blob/598208daf2dbb51ad31fd542d82b3a263c87128a/src/os/bluestore/BlueStore.cc#L3734-L3740 should also have fixed it.  Did it not?

**Comment by markhpc** [comment]
@liewegas Kefu's testing didn't show the original issue after my PR, but did hit the assert we were speaking about earlier during thrash (especially EC thrash) tests.  Presuambly your PR should hit the same issue since it's almost identical.

**Comment by ifed01** [comment]
IMO pin logic can be totally simplified.
As far as I understand the primarily goal for pin/unpin logic is to bypass multireferenced (nref > 1) onodes while doing trimming in Onode cache. Can we achieve the same by simply removing such onodes from cache when nref becomes greater than 1 and tagging them with pinned flag.  And likely the latter isn't necessary too as ref counter is the good marker for 'pinned' state.
Keeping shard ref in onode isn't necessary in this case too - put/get methods can use c->shard to do _add/_rm from the cache. 
Let me try to implement this and submit a different PR

**Pull request merged**
