### PR TITLE
Fix mount root for ceph_mount users and change tarball format

### PR DESCRIPTION
**Pull request by jtlayton**
This PR is a backport of the fix for this bug:

http://tracker.ceph.com/issues/18307

...and also what I think is a fix for:

http://tracker.ceph.com/issues/18312

...which I hit while building soon after the ceph-qa-suite was integrated.

### CODE REVIEW

**Comment by jtlayton** [comment]
The first commit is a jewel backport of what already went into kraken. The second one, I think will fix the build break that I hit with tracker bug 18312.

Assigning @alfredodeza as he has also seen the build break. @liewegas because he did the most recent ceph-qa-suite merge, and @dachary as he merged commit 396702aabf67453d4151d9e5fadfd01edf7e053b which changed this to ustar before.

Thoughts on that latter piece?

**Comment by alfredodeza** [comment]
The fix for the `tar` problem looks OK to me

**Comment by jtlayton** [comment]
...and one more commit to hopefully fix an automated pre-merge PR check that failed.

**Comment by smithfarm** [comment]
@jtlayton Did this go through regression testing?

**Comment by dachary** [comment]
@smithfarm it did not. I assume @jtlayton was not aware of the backport procedure. f15c8da is redundant with another backport already in jewel-next (which was merged in jewel today). We'll have to keep an eye on the other two commits in case tests fail in the near future.

**Pull request merged**
