### PR TITLE
osd/ReplicatedPG: force promotion for watch/notify ops

### PR DESCRIPTION
**Pull request by wonzhq**
Watch/notify ops can't be proxied.

Signed-off-by: Zhiqiang Wang <zhiqiang.wang@intel.com>

### CODE REVIEW

**Comment by wonzhq** [comment]
OK, let's do it in that way.

**Comment by wonzhq** [comment]
Updated. Pls review again. @liewegas

**Comment by liewegas** [comment]
I think this needs a rebase onto latest master (there is a merge conflict), otherwise Reviewed-by:.  Thanks!!

**Comment by wonzhq** [comment]
Rebased and solved the merge conflict.

**Pull request merged**
