### PR TITLE
crimson/os/seastore: initialize logical pins before exposing to cache

### PR DESCRIPTION
**Pull request by athanatos**
<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by athanatos** [comment]
@xxhdx1985126 How about this?

**Comment by xxhdx1985126** [comment]
> @xxhdx1985126 How about this?

Hi, sam, it seems that `BtreeLBAManager::get_physical_extent_if_live()` would still initialize logical extents after getting the extent, which looks to me a possible pin leak. Am I right?

**Comment by athanatos** [comment]
Yeah, I'll have to refactor that as well, will get to it tomorrow.

**Comment by xxhdx1985126** [comment]
Ah, sorry, `BtreeLBAManager::get_physical_extent_if_live()` is only used when getting physical extents, I thought it might also be called to get logical extents as it calls `LBABtree::init_cached_extent()` which deals with cases in which the passed extent is a logical one. My mistake, sorry.

**Comment by athanatos** [comment]
Unfortunately, I think it's still a problem, internal btree nodes also have pins that need to be initialized.  I'll take a closer look in the morning.

**Comment by athanatos** [comment]
Ok, repushed.  @xxhdx1985126 did we have an easy way to reproduce the problem?

**Comment by xxhdx1985126** [comment]
> Ok, repushed. @xxhdx1985126 did we have an easy way to reproduce the problem?

Um...I haven't found one. Right now, I have to compile crimson osd with RelWithDebInfo/Release and run it for like half an hour to meet the problem.

**Comment by athanatos** [comment]
@xxhdx1985126 @cyx1231st Ok, this actually passes make check now.

**Review by cyx1231st — APPROVED** [review]
LGTM

**Review by xxhdx1985126 — APPROVED** [review]

**Pull request merged**
