### PR TITLE
rgw: Cloud Sync Module fixes

### PR DESCRIPTION
**Pull request by gleamicus**
Tracker issue: https://tracker.ceph.com/issues/41540

Please let me know if you need more details, documentation, etc.

### CODE REVIEW

**Comment by yehudasa** [comment]
@gleamicus sorry, I only noticed this PR now. I'll start reviewing it, but it seems to me that this might benefit from being split into multiple separate issues and PRs.

**Comment by gleamicus** [comment]
Yeah, I'm OK abandoning it. There are some bugs in it, and I've given up on the cloud sync module anyway. Thanks!

**Comment by yehudasa** [comment]
@gleamicus there are some bug fixes there that probably need to go int

**Comment by gleamicus** [comment]
> @gleamicus there are some bug fixes there that probably need to go in

OK. There's a bug either in these fixes or in the original sync module that causes corruption past 4gb of an object, at least in my environment. Everything after the 4GB mark is bit-different from the source file, and additionally the destination object is a round multiple of the multipart chunk size, rather than the same size as the original. These could be two separate but overlapping bugs, or one. I'm not sure.

**Comment by yehudasa** [comment]
@gleamicus I see, will definitely need to dig deeper into it then.

**Comment by mattbenjamin** [comment]
@yehudasa did you plan to take ownership of this?

**Comment by yehudasa** [comment]
@mattbenjamin yeah, thanks for the reminder

**Pull request closed without merging**
