### PR TITLE
RGW - Make sure PostObj set bucket on s->object

### PR DESCRIPTION
**Pull request by dang**
s->bucket is guaranteed to exist at this point, since this is a bucket OP (and we use it earlier in the function).

Fixes: https://tracker.ceph.com/issues/57911

Signed-off-by: Daniel Gryniewicz <dang@redhat.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by cbodley** [comment]
cc @theanalyst

**Review by cbodley — APPROVED** [review]

**Review by alimaredia — APPROVED** [review]

**Comment by alimaredia** [comment]
@cbodley @dang Do you think we need some kind of extra test coverage to check scenarios like the one that the issue this fixes originated from?

**Comment by theanalyst** [comment]
Hi this still leaves some paths open as s->bucket may not exist on certain requests esp PostObject (I've updated #48491 to reflect this)

**Comment by dang** [comment]
https://pulpito.ceph.com/dang-2022-12-21_09:11:10-rgw-wip-dang-bucket-policy-distro-default-smithi/

**Comment by jgraichen** [comment]
Should this PR have appeared in any latest or latest-dev branch?

Our tests against the daily container images [are still failing](https://github.com/jgraichen/ceph-rgw-51574/actions/runs/4101522306) for `latest`, `latest-devel`, `
latest-quincy`, `latest-quincy-devel`? Is there something missing, or is this another bug appearing in the same test scenario?

**Pull request merged**
