### PR TITLE
luminous: osd/ReplicatedPG.cc: recover_replicas: object added to missing set for backfill, but is not in recovering, error!

### PR DESCRIPTION
**Pull request by pdvian**
http://tracker.ceph.com/issues/22069

### CODE REVIEW

**Comment by badone** [comment]
@dzafman This looks good to me. Mind taking a look?

**Comment by dzafman** [comment]
@badone @pdvian We should consider cherry-picking all or most of ceph/ceph#17708.  I'm nervous about changes made here which are really part of that pull request.

**Comment by badone** [comment]
@dzafman Then http://tracker.ceph.com/issues/22069 shouldn't exist and we need another tracker since what you are suggesting is definitely not a backport of the fix for http://tracker.ceph.com/issues/18162 in isolation is it?

**Comment by pdvian** [comment]
@dzafman @badone thanks for comments. @dzafman would you like to reference PR ceph/ceph#17708 on tracker#22069 and advise to pull all changes from PR#17708 ?

**Comment by dzafman** [comment]
ceph/ceph#20081 backports this trivially by including 2 other small pull requests

**Pull request closed without merging**
