### PR TITLE
mgr/dashboard: can't scroll to the end of the page

### PR DESCRIPTION
**Pull request by dnyanee1997**
Fixes: https://tracker.ceph.com/issues/67549
          https://tracker.ceph.com/issues/67550

Signed-off-by: Dnyaneshwari Talwekar<dtalweka@redhat.com>

Upgrade-scroll-issue
ExpandClusterScrollIssue

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [x] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Review by nizamial09 — APPROVED** [review]
LGTM, thank you

**Comment by epuertat** [comment]
@dnyanee1997 I noticed a similar issue with the landing or the multi-cluster page (the bottom of the page was *sometimes* unreachable/unscrollable). Will this fix that too? If you haven't seen that or can't reproduce it, I'll share that the next time I face it ;-)

**Comment by dnyanee1997** [comment]
@epuertat Yes, this will resolve scroll issue from landing and multi-cluster page too. Please find attached screenshot for your reference.

Please correct me if attached screenshot is not the same page which you were refering.

DashboardScroll
Multi-Cluster-Scroll-issue

**Comment by cloudbehl** [comment]
jenkins test api

**Comment by epuertat** [comment]
yep @dnyanee1997 those where what I meant! Great to see those fixed too. Thanks!

**Comment by dnyanee1997** [comment]
jenkins test api

**Comment by dnyanee1997** [comment]
jenkins test make check arm64

**Comment by nizamial09** [comment]
looks like some jenkins outage on tests
```
ERROR: Error cloning remote repo 'origin'
hudson.plugins.git.GitException: Command "git fetch --tags --force --progress --depth=1 -- https://github.com/ceph/ceph.git +refs/heads/*:refs/remotes/origin/*" returned status code 128:
stdout: 
stderr: fatal: unable to access 'https://github.com/ceph/ceph.git/': Could not resolve host: github.com

	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2846)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandWithCredentials(CliGitAPIImpl.java:2185)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$1.execute(CliGitAPIImpl.java:635)
```

**Comment by afreen23** [comment]
jenkins test api

**Comment by afreen23** [comment]
jenkins test make check arm64

**Comment by afreen23** [comment]
jenkins test make check arm64

**Comment by dnyanee1997** [comment]
Thanks @afreen23

**Pull request merged**
