### PR TITLE
mgr/smb: add sqlite internal store backend for smb mgr module

### PR DESCRIPTION
**Pull request by phlogistonjohn**
Add a new store backend for internal smb module configuration resources. This layer is based on the Ceph MGR's sqlite3 db stored in RADOS. The aim is to improve the performance with regards to searching certain fields of the resources for duplicate values, mainly to prevent the same cluster + share name pair being used for different share resources. This uses sqlite3's JSON support and indexes to achieve the performance improvement.

In order to to significantly change the module's stance with regards to potentially sensitive information the db store provides a subclass that can mirror objects in a different store. We use this to keep all the possibly sensitive info in the mon config key store (like how cephadm stores certs etc).

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [x] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [x] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Comment by phlogistonjohn** [comment]
jenkins test api

**Comment by phlogistonjohn** [comment]
https://pulpito.ceph.com/phlogistonjohn-2024-07-10_15:44:52-orch:cephadm-wip-phlogistonjohn-testing-2024-07-10-0917-distro-default-smithi/

Fixed the major issue preventing the teuthology jobs from succeeding with sqlite3 db store.

**Comment by phlogistonjohn** [comment]
jenkins test make check

**Comment by phlogistonjohn** [comment]
jenkins test api

**Comment by adk3798** [comment]
https://pulpito.ceph.com/adking-2024-07-11_11:10:32-orch:cephadm-wip-adk-testing-2024-07-10-1548-distro-default-smithi/

Failures

- 3 mds_upgrade_sequence failures, known issue
- 2 staggered upgrade `ceph orch ps` vs. `ceph versions` mismatch, known issue
- 1 failure in test_cephadm task. This was actually caused by a PR in the run (have commented about it on that PR)
- thrash and rgw_ingress tests timing out, known issue

Should only block merging for the one PR breaking the test_cephadm task test

**Comment by adk3798** [comment]
jenkins test api

**Comment by adk3798** [comment]
jenkins test api

**Review by adk3798 — APPROVED** [review]

**Pull request merged**
