### PR TITLE
auth/krb: fix Kerberos compile error

### PR DESCRIPTION
**Pull request by hjwsm1989**
Signed-off-by: huangjun <huangjun@xsky.com>

- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by hjwsm1989** [comment]
@oliveiradan do you have time to take a look, thanks!

**Comment by tchaikov** [comment]
it's a regression introduced by 7dfca035ac84a880a18e3bcdcf11c81d609a5a4c

**Comment by tchaikov** [comment]
```
tcmalloc: large alloc 2147483648 bytes == 0xfafde000 @  0xffff8da56310 0xffff8da583dc 0xffff8da77dd0 0xffff84c54494 0xffff84c4a7cc 0xffff84c4a860 0xffff84c4dbe4 0x630d6c 0x5cdb84 0x5cea1c 0x5cf2b4 0x55d9b4 0x553564 0x5a6258 0x59e818 0x57c4a0 0x57cdac 0x57d490 0x587dc0 0x5a762c 0x59faa4 0x5867fc 0x55c150 0x559084 0xffff82c10d64 0x55064c
2019-05-16 01:14:08.549 ffff815fd5d0 -1 bdev(0x3a2b7000 ceph_test_bluefs.tmp.block.29513.5) aio to 5242880~2147479552 but returned: 2147418112
/home/jenkins-build/build/workspace/ceph-pull-requests/src/os/bluestore/KernelDevice.cc: In function 'void KernelDevice::_aio_thread()' thread ffff815fd5d0 time 2019-05-16 01:14:08.560258
/home/jenkins-build/build/workspace/ceph-pull-requests/src/os/bluestore/KernelDevice.cc: 543: ceph_abort_msg("unexpected aio return value: does not match length")
 ceph version Development (no_version) octopus (dev)
 1: (ceph::__ceph_abort(char const*, int, char const*, std::string const&)+0xe0) [0xffff848b2b94]
 2: (KernelDevice::_aio_thread()+0xc2c) [0x62d610]
 3: (KernelDevice::AioCompletionThread::entry()+0x18) [0x6358c0]
 4: (Thread::entry_wrapper()+0x8c) [0xffff848544b0]
 5: (Thread::_entry_func(void*)+0x14) [0xffff84854414]
 6: (()+0x7bb0) [0xffff8dd37bb0]
 7: (()+0xdb4c0) [0xffff82ccb4c0]
2019-05-16 01:14:08.559 ffff815fd5d0 -1 /home/jenkins-build/build/workspace/ceph-pull-requests/src/os/bluestore/KernelDevice.cc: In function 'void KernelDevice::_aio_thread()' thread ffff815fd5d0 time 2019-05-16 01:14:08.560258
/home/jenkins-build/build/workspace/ceph-pull-requests/src/os/bluestore/KernelDevice.cc: 543: ceph_abort_msg("unexpected aio return value: does not match length")

 ceph version Development (no_version) octopus (dev)
 1: (ceph::__ceph_abort(char const*, int, char const*, std::string const&)+0xe0) [0xffff848b2b94]
 2: (KernelDevice::_aio_thread()+0xc2c) [0x62d610]
 3: (KernelDevice::AioCompletionThread::entry()+0x18) [0x6358c0]
 4: (Thread::entry_wrapper()+0x8c) [0xffff848544b0]
 5: (Thread::_entry_func(void*)+0x14) [0xffff84854414]
 6: (()+0x7bb0) [0xffff8dd37bb0]
 7: (()+0xdb4c0) [0xffff82ccb4c0]

*** Caught signal (Aborted) **
 in thread ffff815fd5d0 thread_name:bstore_aio
 ceph version Development (no_version) octopus (dev)
 1: /home/jenkins-build/build/workspace/ceph-pull-requests/build/bin/unittest_bluefs() [0x6573cc]
 2: [0xffff8dd906c0]
 3: (gsignal()+0x4c) [0xffff82c242c8]
 4: (abort()+0x11c) [0xffff82c25940]
 5: (ceph::__ceph_abort(char const*, int, char const*, std::string const&)+0x2c0) [0xffff848b2d74]
 6: (KernelDevice::_aio_thread()+0xc2c) [0x62d610]
 7: (KernelDevice::AioCompletionThread::entry()+0x18) [0x6358c0]
 8: (Thread::entry_wrapper()+0x8c) [0xffff848544b0]
 9: (Thread::_entry_func(void*)+0x14) [0xffff84854414]
 10: (()+0x7bb0) [0xffff8dd37bb0]
 11: (()+0xdb4c0) [0xffff82ccb4c0]
2019-05-16 01:14:08.579 ffff815fd5d0 -1 *** Caught signal (Aborted) **
 in thread ffff815fd5d0 thread_name:bstore_aio
```

this is the first time the test failure in unittest_bluefs was observed on amd64. previously, it was only found on arm64 builders.

retest this please.

**Comment by hjwsm1989** [comment]
retest this please.

**Comment by oliveiradan** [comment]
@hjwsm1989, Sorry! By the time I read the update, @tchaikov had already taken care of.

**Pull request merged**
