### PR TITLE
os/bluestore: Fix code rot in ZonedAllocator.

### PR DESCRIPTION
**Pull request by agayev**
Signed-off-by: Abutalib Aghayev <agayev@psu.edu>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Review by ifed01 — APPROVED** [review]

**Review by tchaikov — COMMENTED** [review]
@agayev could you be more specific in the title to explain that the change happens in ZonedAllocator, like

> os/bluestore: Fix code rot in ZonedAllocator

?

**Comment by agayev** [comment]
> @agayev could you be more specific in the title to explain that the change happens in ZonedAllocator, like
> 
> > os/bluestore: Fix code rot in ZonedAllocator
> 
> ?

Done.

**Review by tchaikov — APPROVED** [review]

**Comment by agayev** [comment]
@tchaikov anything I can do to get the libzbd into test servers? :-)

**Comment by agayev** [comment]
> @tchaikov anything I can do to get the libzbd into test servers? :-)

Oh, I just saw your email. Never mind. I will reply there.

**Pull request merged**
