### PR TITLE
mgr/balancer: pool-specific optimization support and bug fixes

### PR DESCRIPTION
**Pull request by xiexingguo**

### CODE REVIEW

**Comment by tchaikov** [comment]
http://pulpito.ceph.com/kchai-2018-01-31_01:48:16-rados-wip-kefu-testing-2018-01-31-0034-distro-basic-mira/

failure tracked at http://tracker.ceph.com/issues/22846

**Comment by tchaikov** [comment]
@xiexingguo shall we backport 52e336efc1000e55feb36d82c7324c087d2061c1 to luminous. IMO, it's a bug fix of balance mgr plugin.

**Comment by xiexingguo** [comment]
Thanks @tchaikov for merging.

> shall we backport 52e336e to luminous? IMO, it's a bug fix of balancer mgr plugin. the same applies to #20180.

I am still testing and verifying this module and  I'll prepare a batch of fixes back into luminous later by myself when everything is done :-)

**Comment by tchaikov** [comment]
@xiexingguo thanks in advance.

**Comment by liewegas** [comment]
thanks @xiexingguo !

**Pull request merged**
