### PR TITLE
osd: add device_id to list_devices to help get smart info easily

### PR DESCRIPTION
**Pull request by shun-s**
Signed-off-by: Song Shun <song.shun3@zte.com.cn>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test docs`
- `jenkins render docs`

</details>

### CODE REVIEW

**Comment by shun-s** [comment]
before:  
   ```
[root@xx build]# ceph daemon osd.0 list_devices
{
        "device": "/dev/sda",
        "device": "/dev/sdc"
}
```
after:   
```
[root@xx build]# ceph daemon osd.0 list_devices
[
     {
        "device": "/dev/sda",
        "device_id": "TOSHIBA_AL13SEB600_75E0A05RFTR7"
    },
    {
        "device": "/dev/sdc",
        "device_id": "TOSHIBA_AL13SEB600_75E0A04XFTR7"
    }
]
```

then we can easily get smart info by run

``ceph daemon osd.0 smart device_id``

**Comment by shun-s** [comment]
unittest failed seems no relation with this pr
@tchaikov please help review this ?

**Comment by shun-s** [comment]
@tchaikov @liewegas ping

**Comment by liewegas** [comment]
yeah, you can ignore the arm64 failure for the moment

**Pull request merged**
