### PR TITLE
nautilus: mds: reset heartbeat during long-running loops in recovery

### PR DESCRIPTION
**Pull request by batrick**
http://tracker.ceph.com/issues/40223

### CODE REVIEW

**Comment by smithfarm** [comment]
@batrick I see you removed some labels - does this mean this PR is not meant to go into nautilus v14.2.2?

**Comment by batrick** [comment]
It has a conflict with another backport. Dropped the labels until the other one is merged so I can rebase.

**Comment by yuriw** [comment]
[wip-yuri5-testing-2019-06-19-1417-nautilus](https://trello.com/c/zTkUBICo/647-wip-yuri5-testing-2019-06-19-1417-nautilus)

**Comment by batrick** [comment]
`Reviewed-by: Patrick Donnelly <pdonnell@redhat.com>`

**Pull request merged**
