### PR TITLE
qa/suites/rados/verify/validater/valgrind: increase op thread timeout

### PR DESCRIPTION
**Pull request by Matan-B**
Fixes: https://tracker.ceph.com/issues/62992

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Review by athanatos — APPROVED** [review]

**Review by rzarzynski — APPROVED** [review]

**Comment by ljflores** [comment]
@Matan-B I don't think this needs to go through the whole rados suite- we can just run your QA branch against the affected jobs on main. WDYT?

**Comment by ljflores** [comment]
jenkins test make check

**Comment by Matan-B** [comment]
https://pulpito.ceph.com/matan-2023-11-22_08:14:32-rados:verify-main-distro-default-smithi/

**Comment by Matan-B** [comment]
> @Matan-B I don't think this needs to go through the whole rados suite- we can just run your QA branch against the affected jobs on main. WDYT?

@ljflores, this test is currently failing due to https://tracker.ceph.com/issues/61774
So we can't really test this patch independently.

Blocked-by: #52639

**Comment by Matan-B** [comment]
@ljflores, @yuriw - Can we include this in the next run please?
I'll backport it to R since it's causing failures in test runs

**Comment by ljflores** [comment]
@Matan-B yes, it will be tested along with https://github.com/ceph/ceph/pull/52639.

**Comment by amathuria** [comment]
Rados approved: https://tracker.ceph.com/projects/rados/wiki/MAIN#httpstrellocomcxPMmTzrv1977-wip-yuri6-testing-2024-03-15-0709-old-wip-yuri6-testing-2024-03-12-0858

**Pull request merged**
