### PR TITLE
nautilus: mgr/dashboard: inconsistent result when editing a RBD image's features

### PR DESCRIPTION
**Pull request by bk201**
http://tracker.ceph.com/issues/39993

### CODE REVIEW

**Comment by bk201** [comment]
jenkins test dashboard

**Comment by rjfd** [comment]
jenkins retest this please

**Comment by votdev** [comment]
jenkins retest this please

**Comment by yuriw** [comment]
[wip-yuri5-testing-2019-05-29-1613-nautilus](https://trello.com/c/q7wFCEp3/622-wip-yuri5-testing-2019-05-29-1613-nautilus)

**Comment by yuriw** [comment]
jenkins re-test this please

**Pull request merged**
