### PR TITLE
mgr/dashboard: fix typo: Filesystems to File Systems

### PR DESCRIPTION
**Pull request by navinbarnwal**
filesystems

Fixes: https://tracker.ceph.com/issues/50341
Signed-off-by: Navin Barnwal <knbarnwal@gmail.com>

### CODE REVIEW

**Review by pereman2 — APPROVED** [review]

**Review by batrick — APPROVED** [review]

**Review by nizamial09 — CHANGES_REQUESTED** [review]
Just a minor one. Need to change the breadcrumb for this too.

**Comment by navinbarnwal** [comment]
> Just a minor one. Need to change the breadcrumb for this too.

Done !!

**Comment by nizamial09** [comment]
Don't worry. @navinbarnwal Its not related to your PR. Its happening for every PRs

**Comment by nizamial09** [comment]
jenkins retest this please

**Comment by navinbarnwal** [comment]
`Reading package lists...
E: Failed to fetch https://1.chacra.ceph.com/r/libzbd/master/1fadde94b08fab574b17637c2bebd2b1e7f9127b/ubuntu/focal/flavors/default/dists/focal/main/binary-i386/Packages  404  Not Found [IP: 158.69.67.31 443]
E: Some index files failed to download. They have been ignored, or old ones used instead.
Build step 'Execute shell' marked build as failure`

@epuertat  How do I solve this issue?

**Comment by nizamial09** [comment]
> How do I solve this Ceph Dashboard

just rerun the test and hope it will pass ;)

**Comment by epuertat** [comment]
@navinbarnwal in this very case, only the dashboard test failed, so you could simply write "jenkins test dashboard". However let's first check [that the failures are not real ones](https://dashboard.cypress.io/projects/k7ab29/runs/3053/overview):
image

So those probably require that you update as well the files you see there.

**Comment by navinbarnwal** [comment]
> @navinbarnwal in this very case, only the dashboard test failed, so you could simply write "jenkins test dashboard". However let's first check [that the failures are not real ones](https://dashboard.cypress.io/projects/k7ab29/runs/3053/overview):
> image
> 
> So those probably require that you update as well the files you see there.

Thankx, I hope it's fixed now !

**Review by nizamial09 — APPROVED** [review]

**Comment by epuertat** [comment]
Thank you, @navinbarnwal! Another PR from yours got merged!

**Comment by navinbarnwal** [comment]
Thankx, I'm Glad !!

**Pull request merged**
