### PR TITLE
tests: ceph-helpers kill_daemons fails when kill fails

### PR DESCRIPTION
**Pull request by dachary**
Instead of silently leaving the daemons running, it returns failure so
the caller can decide what to do with this situation. The timeout is
also extended to minutes instead of seconds to gracefully handle the
rare situations when a machine is extra slow for some reason.

http://tracker.ceph.com/issues/11398 Fixes: #11398

Signed-off-by: Loic Dachary <ldachary@redhat.com>

### CODE REVIEW

**Comment by dachary** [comment]
@tchaikov it's not exactly the same error as the initial 11398 as it turns out (you observed that the kill was successful). But it was close enough that I thought it was the same. Only a few minutes ago, reading back the comments you made did I realize it's probably different. In any case, the fix for this one makes sense to me. Does it look good to you ?

**Comment by tchaikov** [comment]
@dachary , lgtm, other than a minor comment regarding to the doxygen comment.

**Comment by dachary** [comment]
@tchaikov added the ``delays`` documentation. I thought I would not document it because it's only for test purposes. But you're right : as soon as an interface is available for whatever reason it should be documented. I was being lazy :-)

**Comment by tchaikov** [comment]
@dachary oh, i found that we have comments for existing parameters, so maybe you missed the newly added one. thanks for the very detailed doc. will merge it shortly after the build bot returns.

**Comment by dachary** [comment]
@tchaikov I've been very careful with this file to make sure the documentation is reliable and up to date. Thanks for saving me from my own lazyness ;-)

**Comment by dachary** [comment]
http://jenkins.ceph.dachary.org/job/ceph/5091/ ran ok

**Pull request merged**
