### PR TITLE
nautilus: mgr/ansible: Host ls implementation 

### PR DESCRIPTION
**Pull request by sebastian-philipp**
http://tracker.ceph.com/issues/39559

### CODE REVIEW

**Comment by sebastian-philipp** [comment]
```
Conflicts:
	src/pybind/mgr/orchestrator.py
```

**Comment by jmolmo** [comment]
I think that the Ansible Orchestrator was not included in Nautilus (because we haven't got any kind of integration tests for this orchestrator).
So in my opinion any of the changes related with the Ansible Orchestrator should not be merged in Nautilus.

**Comment by sebastian-philipp** [comment]
Actually - it is included

**Comment by jmolmo** [comment]
> Actually - it is included. there was never a PR to remove that from Nautilus. And in any case, having re-adding support for this in a patch release was planned anyway.

mmm... so it was not complete at all... i think that it would be more easy to remove it completely from Nautilus. (for sure nobody is using it... but probably this will break any convention about how to do things)
So... probably is more wise and we can save time/effort if we avoid to do backporting of any Ansible Orchestratror PR until the moment that we close functionality for Octopus. In this moment we can merge all the orchestrator and fix any kind of problem.

**Comment by yuriw** [comment]
[wip-yuri2-testing-2019-06-05-1524-nautilus](https://trello.com/c/fgHamZml/630-wip-yuri2-testing-2019-06-05-1524-nautilus)

**Pull request merged**
