### PR TITLE
pacific: mgr/dashboard: monitoring: replace Grafana JSON with Grafonnet based code

### PR DESCRIPTION
**Pull request by aaSharma14**
backport tracker: https://tracker.ceph.com/issues/52135

---

backport of https://github.com/ceph/ceph/pull/42194
parent tracker: https://tracker.ceph.com/issues/45184

this backport was staged using ceph-backport.sh version 16.0.0.6848
find the latest version at https://github.com/ceph/ceph/blob/master/src/script/ceph-backport.sh

### CODE REVIEW

**Review by avanthakkar — APPROVED** [review]

**Review by alfonsomthd — APPROVED** [review]

**Comment by smithfarm** [comment]
This PR appears to make it impossible to build Ceph on a machine that doesn't have a network connection :-(

**Comment by smithfarm** [comment]
@alfonsomthd Did you run this through teuthology before merging it into pacific (a stable branch)?

Even if there is no teuthology test coverage for it, teuthology tests packages (DEB, RPM), so the act of running a teuthology suite can discover bugs, which would allow such bugs to be fixed before merge.

Another thing to consider: would it make sense for the lead (@epuertat in this case) to sign off on feature backports?

**Comment by smithfarm** [comment]
Fortunately, we already have a process whereby you can ask for your backport PRs to be run through a teuthology suite: just add the "needs-qa" and "pacific-batch-1" labels after ensuring all the mandatory PR checks have passed.

**Comment by alfonsomthd** [comment]
> @alfonsomthd Did you run this through teuthology before merging it into pacific (a stable branch)?
> 
> Even if there is no teuthology test coverage for it, teuthology tests packages (DEB, RPM), so the act of running a teuthology suite can discover bugs being introduced into the {DEB,RPM} build process.
> 
> Another thing to consider: would it make sense for the lead (@epuertat in this case) to sign off on feature backports?

The jenkins job "jenkins test api" runs the Dashboard and Mgr self-test tests and they passed as well as all the addiitonal checks we have in place.

**Comment by smithfarm** [comment]
@alfonsomthd Thanks! I guess what I'm trying to say is that teuthology testing is a must for any PR that changes build-related code (cmake, spec files, debian/, etc.).

> The jenkins job "jenkins test api" runs the teuthology Dashboard and Mgr self-test tests

It runs some tests, but not using teuthology, right? Or do we have Jenkins triggering Shaman builds and teuthology runs, now? (If so, could you point me to the teuthology run for this PR?)

**Comment by smithfarm** [comment]
> as all the checks passed I merged it

The PR changes code that gets triggered by the RPM build process, but my understanding is that no RPM build was triggered as part of the checks.

**Comment by alfonsomthd** [comment]
> @alfonsomthd Thanks! I guess what I'm trying to say is that teuthology testing is a must for any PR that changes build-related code (cmake, spec files, debian/, etc.) in order to avoid introducing regressions that show up when RPMs are being built.
> 
@smithfarm I get your point: I agree.

> > The jenkins job "jenkins test api" runs the teuthology Dashboard and Mgr self-test tests
> 
> It runs some tests, but not using teuthology, right? Or do we have Jenkins triggering Shaman builds and teuthology runs, now? (If so, could you point me to the teuthology run for this PR?)

Right, not using Teuthology environment: `run-backend-api-tests.sh` make use of the Teuthology framework in order to run the aforementioned tests against a `vstart` cluster.

**Comment by alfonsomthd** [comment]
> > as all the checks passed I merged it
> 
> The PR changes code that gets triggered by the RPM build process, but my understanding is that no RPM build was triggered as part of the checks.
> 
> If they are to remain "stable", stable branches need a higher bar for merging PRs into them. That's why we have a process for putting backport PRs through integration tests.

@smithfarm Understood!

**Pull request merged**
