### PR TITLE
crimson: seastore add OP_ZERO support

### PR DESCRIPTION
**Pull request by liu-chunmei**
Signed-off-by: chunmei-liu <chunmei.liu@intel.com>
                       Samuel Just <sjust@redhat.com>

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by athanatos** [comment]
Needs unit test.

**Comment by liu-chunmei** [comment]
> Needs unit test.

add unit test for seastore::zero.

**Comment by athanatos** [comment]
We don't actually need to write buffers with zero's in them -- reserved regions serve that purpose already without needing to actually store a buffer.  Also, zerowrite() is really similar to overwrite().  How about something like:

https://github.com/athanatos/ceph/tree/sjust/wip-seastore-zero

**Comment by liu-chunmei** [comment]
>

**Comment by liu-chunmei** [comment]
> We don't actually need to write buffers with zero's in them -- reserved regions serve that purpose already without needing to actually store a buffer. Also, zerowrite() is really similar to overwrite(). How about something like:
> 
> https://github.com/athanatos/ceph/tree/sjust/wip-seastore-zero

@athanatos merged it in.  FYI.

**Comment by athanatos** [comment]
My branch also had more detailed tests, I think.  Can we grab that commit as well?

**Comment by liu-chunmei** [comment]
> My branch also had more detailed tests, I think. Can we grab that commit as well?

oh, sorry, I didn't checkout your branch so not see the other commit, just use the web link to grab the latest patch.  merged all of them .

**Review by athanatos — APPROVED** [review]

**Pull request merged**
