### PR TITLE
mgr/zabbix template improvements

### PR DESCRIPTION
**Pull request by scoopex**
The changes need some review because i am currently not able to test this in a environment.
- added a host screen which displays all graphs in a convenient way
- replaced AVG by MAX Function in Graphs where maximum values are of
  high interest from operational view
- changed graph type to stacked where combined behavior is of interest
  (i.e. bandwidth and storage consumption)

### CODE REVIEW

**Comment by wido** [comment]
Thanks! It is difficult to test this one as I currently do not have a Zabbix env where I can load this template. Let me think about that for a moment.

**Comment by scoopex** [comment]
I am not currently using luminous. My changes where trivial but based on my enhanced zabbix knowledge. If you have a test system where you can provide access, i can perform further enhancements.

**Comment by wido** [comment]
LGTM!

**Comment by jcsp** [comment]
@wido does your tick indicate that you've had a chance to try this out?

**Comment by wido** [comment]
Yes, I was able to do so

**Comment by jcsp** [comment]
@scoopex this is ready to merge, but we just need the commit message to be reformatted to the Ceph style: please could you start the first line with "mgr/zabbix: ", and add a "Signed-off-by" line at the end (https://github.com/ceph/ceph/blob/master/SubmittingPatches.rst#signing-contributions)

**Comment by yuriw** [comment]
[wip-yuri2-testing-2018-01-09-1813](https://trello.com/c/x6we0BIB/224-wip-yuri2-testing-2018-01-09-1813)

**Comment by scoopex** [comment]
Sorry, i accidentally messed up my pull request.

I created a new one which includes the requested modifications by jcsp: https://github.com/ceph/ceph/pull/19901

Just merge this pull request, and i will drop this request. I'm sorry.

**Pull request closed without merging**
