### PR TITLE
luminous: tests: do not take ceph.conf.template from ceph/teuthology.git

### PR DESCRIPTION
**Pull request by smithfarm**
backport tracker: https://tracker.ceph.com/issues/42264

---

parent tracker: https://tracker.ceph.com/issues/42261

this backport was staged using ceph-backport.sh version 15.0.0.5775
find the latest version at https://github.com/ceph/ceph/blob/master/src/script/ceph-backport.sh

### CODE REVIEW

**Comment by neha-ojha** [comment]
https://github.com/ceph/ceph/pull/30841#pullrequestreview-300012634 applies here as well

**Comment by smithfarm** [comment]
@neha-ojha Ack. Once the mimic version is approved, I'll cherry-pick it into this PR for luminous.

**Comment by smithfarm** [comment]
@neha-ojha Ready for review

**Comment by smithfarm** [comment]
Note: 0483c1c was omitted from https://github.com/ceph/ceph/pull/30298 so I added it here.

**Comment by smithfarm** [comment]
@yuriw Since https://github.com/ceph/teuthology/pull/1308 was not merged, I think this PR is needed for smooth luminous v12.2.13 QE testing. 

@neha-ojha Do you agree?

**Comment by yuriw** [comment]
[wip-yuri8-testing-2019-10-31-1518-luminous](https://trello.com/c/zOlYlKZP/741-wip-yuri8-testing-2019-10-31-1518-luminous)

**Pull request merged**
