### PR TITLE
[ceph-fuse] fix ceph-fuse writing to stale log file after log rotation

### PR DESCRIPTION
**Pull request by david-z**
http://tracker.ceph.com/issues/12350

### CODE REVIEW

**Comment by ukernel** [comment]
looks good

**Comment by liewegas** [comment]
:+1:

**Comment by david-z** [comment]
@dachary  this failure seems not to be related to this change. Could you pls take a look? Thanks.

**Comment by gregsfortytwo** [comment]
This looks good to me. Can you get it in the stable hammer when that's processing, @dachary? :)

**Comment by dachary** [comment]
@gregsfortytwo there need to be a backport issue for this to happen, please see http://tracker.ceph.com/projects/ceph-releases/wiki/HOWTO for details

**Comment by david-z** [comment]
@dachary 

I changed this tracker: http://tracker.ceph.com/issues/12350 according to this wiki: http://tracker.ceph.com/projects/ceph-releases/wiki/HOWTO_schedule_an_issue_for_backporting. I can only do the first stage, pls let me know if there is anything needs me to do.

**Comment by dachary** [comment]
@david-z could you please amend the commit message to explain why this fix is hammer specific ? It's useful for later reference. Most backports are cherry-picked from master but it's also ok to create a fix for a problem that only shows on a stable branch. @gregsfortytwo may be able to help with the rationale.

**Comment by dachary** [comment]
@gregsfortytwo assigning to you because I can't assign it to david-z, although he is next to act.

**Comment by dachary** [comment]
@david-z could you please amend the commit so that the signed-off-by shows your email betwee *&lt;>** ? thanks !

**Comment by david-z** [comment]
@dachary done, pls help to review. thanks!

**Pull request merged**
