### PR TITLE
common/config: fix return type of string::find and use string::npos

### PR DESCRIPTION
**Pull request by Yan-waller**
Signed-off-by: Yan Jun yan.jun8@zte.com.cn

### CODE REVIEW

**Comment by Yan-waller** [comment]
retest this please

**Comment by Yan-waller** [comment]
retest this please

**Comment by Yan-waller** [comment]
@tchaikov ,  How do you think about this PR, could you take a look at it again?

**Comment by yuriw** [comment]
http://pulpito.ceph.com/yuriw-2017-01-13_21:05:46-rados-wip-yuri-testing2_2017_1_13-distro-basic-smithi/

http://pulpito.ceph.com/yuriw-2017-01-14_16:29:03-rados-wip-yuri-testing2_2017_1_13---basic-smithi/

(see http://tracker.ceph.com/issues/18478)

centos run
http://pulpito.front.sepia.ceph.com/yuriw-2017-01-14_16:34:35-rados-wip-yuri-testing2_2017_1_13-distro-basic-vps/

**Pull request merged**
