### PR TITLE
mimic: rbd: krbd: return -ETIMEDOUT in polling

### PR DESCRIPTION
**Pull request by pdvian**
http://tracker.ceph.com/issues/38976

### CODE REVIEW

**Comment by smithfarm** [comment]
The "make check" failure is happening in other mimic PRs as well. See, e.g.: https://github.com/ceph/ceph/pull/27587

**Comment by smithfarm** [comment]
jenkins re-test this please

**Comment by yuriw** [comment]
[wip-yuri5-testing-2019-04-30-2026-mimic](https://trello.com/c/9KYPzFev/602-wip-yuri5-testing-2019-04-30-2026-mimic)

**Comment by yuriw** [comment]
[wip-yuri5-testing-2019-05-03-1956-mimic](https://trello.com/c/uJsMtpy3/606-wip-yuri5-testing-2019-05-03-1956-mimic)

**Pull request merged**
