### PR TITLE
ceph-volume: prepare: use *-slots arguments for implicit sizing

### PR DESCRIPTION
**Pull request by jan--f**
I added these arguments a while ago, but forgot to actually wire them up for some reason. This is a foundation for a larger batch refactor, but should also be handy for direct usage with prepare and create.

Adding multi-device OSDs should be much easier this way. For example user now can do this:
```
for d in /dev/sd[b-f]; do
  ceph-volume prepare --data $d --block.db /dev/nvme0n1 --block.db-slots 5
done
```
And the nvme LVs will be sized accordingly.

Fixes: https://tracker.ceph.com/issues/44494

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by jan--f** [comment]
jenkins test ceph-volume all

**Comment by guits** [comment]
jenkins test ceph-volume all

**Comment by guits** [comment]
it needs ceph/ceph-ansible#5139 first

**Comment by guits** [comment]
jenkins test ceph-volume all

**Comment by guits** [comment]
jenkins test ceph-volume batch centos8-bluestore-mixed_type

**Pull request merged**
