### PR TITLE
mon/pg: take osd_max_pg_per_osd_hard_ratio into account when check ma…

### PR DESCRIPTION
**Pull request by Rethan**
…x pgs

Signed-off-by: haoyixing <haoyixing@kuaishou.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Review by neha-ojha — COMMENTED** [review]
Can you please provide an explanation in the commit message as to why this change is required

**Comment by Rethan** [comment]
> Can you please provide an explanation in the commit message as to why this change is required

updated :)

**Comment by tchaikov** [comment]
- https://pulpito.ceph.com/kchai-2021-05-28_02:36:20-rados-wip-kefu-testing-2021-05-28-0853-distro-basic-smithi/
- https://pulpito.ceph.com/kchai-2021-05-28_13:33:45-rados-wip-kefu-testing-2021-05-28-1806-distro-basic-smithi/
- https://pulpito.ceph.com/kchai-2021-05-29_02:33:40-rados-wip-kefu-testing-2021-05-28-1806-distro-basic-smithi/

failures tracked by

- https://tracker.ceph.com/issues/45423
- https://tracker.ceph.com/issues/50151

**Review by tchaikov — CHANGES_REQUESTED** [review]
i think this change breaks the test of https://pulpito.ceph.com/kchai-2021-05-29_02:33:40-rados-wip-kefu-testing-2021-05-28-1806-distro-basic-smithi/6141007/

```
2021-05-29T04:42:42.336 INFO:tasks.workunit.client.0.smithi006.stdout:                 api_list: [ RUN      ] LibRadosList.EnumerateObjectsSplit
2021-05-29T04:42:42.336 INFO:tasks.workunit.client.0.smithi006.stdout:                 api_list: /home/jenkins-build/build/workspace/ceph-dev-new-build/ARCH/x86_64/AVAILABLE_ARCH/x86_64/AVAILABLE_DIST/centos8/DIST/centos8/MACHINE_SIZE/gigantic/release/17.0.0-4732-g594b33d
a/rpm/el8/BUILD/ceph-17.0.0-4732-g594b33da/src/test/librados/list.cc:483: Failure
2021-05-29T04:42:42.337 INFO:tasks.workunit.client.0.smithi006.stdout:                 api_list: Value of: set_pg_num(&s_cluster, pool_name, 11).empty()
2021-05-29T04:42:42.337 INFO:tasks.workunit.client.0.smithi006.stdout:                 api_list:   Actual: false
2021-05-29T04:42:42.337 INFO:tasks.workunit.client.0.smithi006.stdout:                 api_list: Expected: true
2021-05-29T04:42:42.337 INFO:tasks.workunit.client.0.smithi006.stdout:                 api_list: [  FAILED  ] LibRadosList.EnumerateObjectsSplit (3608412 ms)
```

**Comment by tchaikov** [comment]
@Rethan ping?

**Comment by Rethan** [comment]
> @Rethan ping?

Sorry about the delay, but I don't quite understand why it leads to fail.

**Comment by Rethan** [comment]
I have a 3-osd test cluster by vstart (mon_max_pg_per_osd set to 300), which has 4 pools like below:
image

This assigns each osd 256 pgs, under mon_max_pg_per_osd, while some of these pgs are replicas.
When I try set pool rbd pg_num to 128, got fail message:

bin/ceph osd pool set rbd pg_num 128
Error ERANGE: pool id 4 pg_num 128 size 3 would mean 960 total pgs, which exceeds max 900 (mon_max_pg_per_osd 300 * num_in_osds 3)

supposed to be ok since osd_max_pg_per_osd_hard_ratio is 3 (replica factor) if we consider the replicas.

**Pull request closed without merging**
