### PR TITLE
crimson: update seastar submodule to fix prometheus build error

### PR DESCRIPTION
**Pull request by athanatos**
<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Comment by athanatos** [comment]
Building at https://shaman.ceph.com/builds/ceph/wip-sjust-seastar-64589/

**Review by rzarzynski — APPROVED** [review]

**Comment by athanatos** [comment]
The centos 8 build is breaking -- it seems to be picking up a different verison of libproto some of the time and that breaks the container build.

**Comment by athanatos** [comment]
Hmm, that failure seems to happen some of the time anyway https://jenkins.ceph.com/job/ceph-dev-new-build/ARCH=x86_64,AVAILABLE_ARCH=x86_64,AVAILABLE_DIST=centos8,DIST=centos8,MACHINE_SIZE=gigantic/77212//consoleFull

**Comment by Matan-B** [comment]
Sub-module branch was updated to:
https://github.com/ceph/seastar/commits/sjust/wip-64589

**Review by idryomov — COMMENTED** [review]
This issue affects squid as well, which makes sense because there seastar submodule is at the same commit as it was before this PR on main.  Not sure about other releases?

**Pull request merged**
