### PR TITLE
librbd: fix were_all_throttled() to avoid incorrect ret-value

### PR DESCRIPTION
**Pull request by yangdongsheng**
Signed-off-by: Dongsheng Yang <dongsheng.yang@easystack.cn>

- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by yangdongsheng** [comment]
@dillaman  please help to review.

**Comment by yangdongsheng** [comment]
Fixes: http://tracker.ceph.com/issues/38504

**Comment by dillaman** [comment]
retest this please

**Comment by dillaman** [comment]
retest this please

**Pull request merged**
