### PR TITLE
mailmap: Willem Jan Withagen affiliation

### PR DESCRIPTION
**Pull request by wjwithagen**
Signed-off-by: Willem Jan Withagen <wjw@digiware.nl>

### CODE REVIEW

**Comment by tchaikov** [comment]
could you prefix the title of your commit message with the subcomponent your are changing ? see https://github.com/ceph/ceph/blob/master/SubmittingPatches.rst#3-describe-your-changes, in this case, it's "mailmap: ".

**Comment by wjwithagen** [comment]
@theanalyst 
I actaully work for 2 companies: digiware and nefos.
Both are paying my bills currently.
Looking at the content of the organisationmap, it looks like there are more people in the same situation?

**Comment by theanalyst** [comment]
@wjwithagen ah ok, I assumed it was a change of companies, then it is ok, I believe we don't need an entry in the .peoplemap then, I also think the mailmap entry is not needed here and only the organizationmap would suffice, as otherwise all the digiware commits would show up as nefos, without the mailmap entry it would show up as two seperate organizations depending on the email, which is what you want. I could be wrong, I'll let @dachary confirm.

**Comment by dachary** [comment]
I confirm.

**Pull request merged**
