### PR TITLE
DNM: jewel: rbd-mirror: use sparse read during image sync

### PR DESCRIPTION
**Pull request by Abhishekvrshny**
http://tracker.ceph.com/issues/17879
http://tracker.ceph.com/issues/18215
http://tracker.ceph.com/issues/18137

### CODE REVIEW

**Comment by trociny** [comment]
It is better to backport this together with this fix http://tracker.ceph.com/issues/18146

**Comment by Abhishekvrshny** [comment]
@trociny : Done backporting a2cfc17d25ca8b61a54afc88a05e70df415d6da7 from https://github.com/ceph/ceph/pull/12368. It was a non-trivial backport. Please review.

**Comment by trociny** [comment]
@Abhishekvrshny I think you had a conflict due to this change [1] that is going to be backported too[2].

Could you please cherry-pick 1167865e before a2cfc17 (but after b5db8bcb)?

[1] https://github.com/ceph/ceph/pull/12280
[2] http://tracker.ceph.com/issues/18137

**Comment by Abhishekvrshny** [comment]
@trociny : Did as suggested, but the build still fails with the error 
```
test/rbd_mirror/test_ImageSync.cc: In member function 'virtual void rbd::mirror::TestImageSync_Resize_Test::TestBody()':
test/rbd_mirror/test_ImageSync.cc:158:331: error: no matching function for call to 'librbd::Operations<librbd::ImageCtx>::resize(uint64_t&, bool, librbd::NoOpProgressContext&)'
   ASSERT_EQ(0, m_remote_image_ctx->operations->resize(size, true,
                                                                                                                                                                                                                                                                                                                                           ^
test/rbd_mirror/test_ImageSync.cc:158:331: note: candidate is:
In file included from test/rbd_mirror/test_ImageSync.cc:14:0:
./librbd/Operations.h:34:7: note: int librbd::Operations< <template-parameter-1-1> >::resize(uint64_t, librbd::ProgressContext&) [with ImageCtxT = librbd::ImageCtx; uint64_t = long unsigned int]
   int resize(uint64_t size, ProgressContext& prog_ctx);
       ^
./librbd/Operations.h:34:7: note:   candidate expects 2 arguments, 3 provided
```
This is probably due to the commit d1f2c557b2c039730baca9efa3f5244bc19dcb1a, which is not yet present in jewel.

**Comment by trociny** [comment]
@Abhishekvrshny You could manually resolve the conflict when cherry-picking a2cfc17 (just remove `true` param in `operations->resize()` call), but I would like more if #9878 were also backported to jewel. Unfortunately there is no a tracker ticket for it, but it looks useful and would ease backporting.

@dillaman What do you think?

**Comment by dillaman** [comment]
@trociny I've been avoiding backporting #9878 since it's a new feature and we need to draw a line in the sand at some point about what we do and do not backport. That one in the past has been trivial to work around since it just involves removing the extra param.

**Comment by trociny** [comment]
@dillaman ok
@Abhishekvrshny Could you please try to resolve this as I suggested earlier?

**Comment by Abhishekvrshny** [comment]
@trociny @dillaman : Done. All checks have passed 👍

**Comment by dachary** [comment]
mark as DNM because it conflicts with another pull request

**Comment by dillaman** [comment]
I would like to avoid backporting sparse object reads to jewel unless required -- cache hints are safe to backport (http://tracker.ceph.com/issues/18137)

**Comment by smithfarm** [comment]
@dillaman IIRC we can close/reject/unstage these two backports?

* http://tracker.ceph.com/issues/17879
* http://tracker.ceph.com/issues/18215

**Comment by smithfarm** [comment]
Ah, should have looked - they are already closed.

**Pull request closed without merging**
