### PR TITLE
octopus: mgr/telemetry: fix device id splitting when anonymizing serial

### PR DESCRIPTION
**Pull request by bk201**
backport tracker: https://tracker.ceph.com/issues/47192

---

backport of https://github.com/ceph/ceph/pull/36855
parent tracker: https://tracker.ceph.com/issues/46977

this backport was staged using ceph-backport.sh version 15.1.1.389
find the latest version at https://github.com/ceph/ceph/blob/master/src/script/ceph-backport.sh

### CODE REVIEW

**Comment by bk201** [comment]
@yaarith I tried to backport this back to Octopus and didn't see a conflict mentioned in https://tracker.ceph.com/issues/46977#note-8. Did I miss anything?

**Review by LenzGr — APPROVED** [review]
LGTM! Thank you.

**Comment by yaarith** [comment]
Thanks, @bk201! You are right, there are no conflicts here. I thought there might be due to the new 'serial' definition, but everything looks right.

**Review by yaarith — APPROVED** [review]

**Comment by bk201** [comment]
> Thanks, @bk201! You are right, there are no conflicts here. I thought there might be due to the new 'serial' definition, but everything looks right.

Thanks for the review!

**Comment by yuriw** [comment]
[wip-yuri5-testing-2020-09-29-0919-octopus](https://trello.com/c/kGYaCHPv/1026-wip-yuri5-testing-2020-09-29-0919-octopus)

**Pull request merged**
