### PR TITLE
mgr/orchestrator: "addr" is optional for constructing InventoryNode

### PR DESCRIPTION
**Pull request by tchaikov**
this addresses a regression introduced by 5276871e15

Signed-off-by: Kefu Chai <kchai@redhat.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by tchaikov** [comment]
this should fix the failure of http://pulpito.ceph.com/kchai-2020-02-15_02:54:06-rados-wip-kefu-testing-2020-02-15-0003-distro-basic-smithi/4765187/

**Comment by tchaikov** [comment]
- http://pulpito.ceph.com/kchai-2020-02-15_08:08:06-rados-wip-kefu-testing-2020-02-15-1240-distro-basic-smithi/
- http://pulpito.ceph.com/kchai-2020-02-15_10:48:33-rados-wip-kefu-testing-2020-02-15-1240-distro-basic-smithi/

**Comment by tchaikov** [comment]
@bk201 the test still fails but due to another reason
```
2020-02-15T11:02:31.249+0000 7f8490f15700 -1 Remote method threw exception: Traceback (most recent call last):
  File "/usr/share/ceph/mgr/orchestrator.py", line 879, in list_daemons
    raise NotImplementedError()
NotImplementedError

2020-02-15T11:02:31.249+0000 7f8490f15700 -1 mgr handle_command module 'orchestrator_cli' command handler threw exception: Remote method threw exception: Traceback (most recent call last):
  File "/usr/share/ceph/mgr/orchestrator.py", line 879, in list_daemons
    raise NotImplementedError()
NotImplementedError

2020-02-15T11:02:31.249+0000 7f8490f15700 20 mgr ~Gil Destroying new thread state 0x55922c75d600
2020-02-15T11:02:31.249+0000 7f8490f15700 -1 mgr.server reply reply (22) Invalid argument Traceback (most recent call last):
  File "/usr/share/ceph/mgr/mgr_module.py", line 1069, in _handle_command
    return CLICommand.COMMANDS[cmd['prefix']].call(self, cmd, inbuf)
  File "/usr/share/ceph/mgr/mgr_module.py", line 309, in call
    return self.func(mgr, **kwargs)
  File "/usr/share/ceph/mgr/orchestrator.py", line 143, in wrapper
    return func(*args, **kwargs)
  File "/usr/share/ceph/mgr/orchestrator_cli/module.py", line 302, in _list_daemons
    refresh=refresh)
  File "/usr/share/ceph/mgr/orchestrator.py", line 1539, in inner
    completion = self._oremote(method_name, args, kwargs)
  File "/usr/share/ceph/mgr/orchestrator.py", line 1609, in _oremote
    return mgr.remote(o, meth, *args, **kwargs)
  File "/usr/share/ceph/mgr/mgr_module.py", line 1429, in remote
    args, kwargs)
RuntimeError: Remote method threw exception: Traceback (most recent call last):
  File "/usr/share/ceph/mgr/orchestrator.py", line 879, in list_daemons
    raise NotImplementedError()
NotImplementedError
```

i think the root cause is that `TestOrchestrator.list_daemons` is not implemented yet. could you help update the test accordingly?

**Comment by bk201** [comment]
Will investigate this, create an issue to track:
https://tracker.ceph.com/issues/44165

> see http://pulpito.ceph.com/kchai-2020-02-15_10:48:33-rados-wip-kefu-testing-2020-02-15-1240-distro-basic-smithi/
> 
> i think the root cause is that `TestOrchestrator.list_daemons` is not implemented yet. could you help update the test accordingly?

**Comment by tchaikov** [comment]
@bk201 seems @liewegas is already working on this , see #33359

**Pull request merged**
