### PR TITLE
squid: mgr/dashboard: Nvme mTLS support and service name changes 

### PR DESCRIPTION
**Pull request by afreen23**
Backport trackers:
https://tracker.ceph.com/issues/68096
https://tracker.ceph.com/issues/68095

Backport of: https://github.com/ceph/ceph/pull/59805

Conflict in https://github.com/ceph/ceph/pull/59819/commits/d4fb21735a5112ff7121957fc86b68f07eea4682 due to SSO changes in service form which are not required to be backported

test faiulure due to usage of same spec name `enable_auth` for SSO and mTLS. Hence some extra modifications.
Comments below highlight the issues for the test failures.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [x] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [x] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Comment by afreen23** [comment]
jenkins test api

**Comment by afreen23** [comment]
jenkins test make check

**Comment by afreen23** [comment]
jenkins test dashboard

**Comment by afreen23** [comment]
jenkins test dashboard cephadm

**Comment by afreen23** [comment]
Tests failing due to this, SSO was adding this in main , hence missing here:

```
Error: src/app/ceph/cluster/services/service-form/service-form.component.ts:591:77 - error TS2339: Property 'enable_auth' does not exist on type 'CephServiceAdditionalSpec'.

591               this.serviceForm.get('enable_auth').setValue(response[0].spec.enable_auth);
```

**Comment by afreen23** [comment]
update: Fixed failing service form tests:

```
 Why you should do it regularly: https://github.com/browserslist/update-db#readme
.............................
  ● ServiceFormComponent › should create

    TypeError: Cannot read properties of undefined (reading 'value')

```

**Review by Pegonzal — APPROVED** [review]
Thanks @afreen23 LGTM,

one thing, this tracker https://tracker.ceph.com/issues/68095 has the wrong pull request ID attached to it, right?

**Comment by afreen23** [comment]
> Thanks @afreen23 LGTM,
> 
> one thing, this tracker https://tracker.ceph.com/issues/68095 has the wrong pull request ID attached to it, right?

Yep, fixed that m thanks @Pegonzal

**Pull request merged**
