### PR TITLE
rgw_file: not check max_objects when creating file

### PR DESCRIPTION
**Pull request by taoCH**
Fixed: https://tracker.ceph.com/issues/36654
Signed-off-by: Tao Chen <chentao@umcloud.com>

- [x] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by taoCH** [comment]
If NFS3 is using, NFS Client will not get informed of ENOSPC as 'close' operation is invoked by Librgw. As a consequence, the file will be empty, though we write data into it successfully with rgw_write().

**Comment by mattbenjamin** [comment]
I don't see why;  the WRITE should fail, not non-existent CLOSE, in that case

**Comment by taoCH** [comment]
Hi Matt, thanks for reply in detail. 

I think we should check quota during the WRITE. As NFS3 is stateless, the NFS Client will never know if user's quota has exceed, unless he check the directory and find the all the files he created are empty. 

However, I think we should also check quota during the WRITE in NFS4, too. Assuming a super large file(> 10GB ) is written to NFS, the NFS Client will be informed the quota exceed error at the end, though the quota has already been exceeded at the beginning of the WRITE, which looks not reasonable to me. If we check quota during the WRTIE, then we can return the error as soon as we find the quota is really exceed.

**Comment by yuriw** [comment]
[wip-yuri2-testing-2018-11-15-2111](https://trello.com/c/NmUyiuZp/472-wip-yuri2-testing-2018-11-15-2111)

**Pull request merged**
