### PR TITLE
jewel: rgw: multisite: after CreateBucket is forwarded to master, local bucket may use different value for bucket index shards

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/19758

### CODE REVIEW

**Comment by smithfarm** [comment]
@cbodley Please see http://tracker.ceph.com/issues/19745#note-6

**Comment by smithfarm** [comment]
Jenkins re-test this please

@cbodley Ping

**Comment by cbodley** [comment]
@smithfarm thanks. i did the cherry-pick for https://github.com/ceph/ceph/pull/15010 and resolved the `init_bucket_index()` conflict. i pushed the branch to https://github.com/cbodley/ceph/commits/wip-19758. you can pull in that last commit https://github.com/cbodley/ceph/commit/1a50cc3fc15b4e7798569660f9df67289bb359a2

**Comment by smithfarm** [comment]
@cbodley Thanks! Updated. This enabled me to do the kraken backport as well. While I was working on it, I realized that I left out a potentially significant aspect of the conflict resolution from the first commit, i.e. 9379937 - could you look at it again to see if it's sane?

**Comment by smithfarm** [comment]
This passed an rgw suite at http://tracker.ceph.com/issues/20613#note-18 and @cbodley has already approved it, so I'll merge unless there are objections.

**Pull request merged**
