### PR TITLE
mgr/dashboard: Improve e2e script

### PR DESCRIPTION
**Pull request by valentinbajrami**
replaces PR #29008

Signed-off-by: Valentin Bajrami <valentin.bajrami@target-holding.nl>

- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by callithea** [comment]
jenkins test dashboard

**Comment by callithea** [comment]
jenkins test dashboard

**Comment by valentinbajrami** [comment]
> Hi, please update your commit message to:
> 
> ```
> mgr/dashboard: Improve e2e script
> 
> Passing -r flag to jq to remove quotes. sed not needed
> Using $() command substitution instead of the legacy backticks `...`
> 
> Signed-off-by: Valentin Bajrami <valentin.bajrami@gmail.com>
> ```
> 
> The differences are:
> 
>     1. The commit title needs to start with `mgr/dashboard:`
> 
>     2. I would suggest using `Improve e2e script` as the title, as it seems a bit more clear.
> 
>     3. typo in `lagacy`
> 
> 
> I would also suggest not to use `master` as the branch where you develop a new feature, since it can conflict with the upstream master and other branches you are working on.

Hi Tiago,  

Thank you for the feedback I just applied the changes you mentioned above. Next time I'll not use the master branch but will instead use an appropriate name for the branch.

**Comment by tchaikov** [comment]
jenins, retest this please

@valentinbajrami you need to use `git commit --amend` to revise your commit message and `git push -f` to your remote branch to update the commit message.

**Comment by valentinbajrami** [comment]
> jenins, retest this please
> 
> @valentinbajrami you need to use `git commit --amend` to revise your commit message and `git push -f` to your remote branch to update the commit message.

Thanks Kefu. Just did.

**Comment by tspmelo** [comment]
Hi, seems you forgot to update the commit message title to `mgr/dashboard: Improve e2e script`

**Pull request merged**
