### PR TITLE
common: change default value for perfcounter description ("NO_INFO_FIX">...

### PR DESCRIPTION
**Pull request by Ved-vampir**
...NULL)

Signed-off-by: Alyona Kiseleva <akiselyova@mirantis.com>

### CODE REVIEW

**Comment by dachary** [comment]
Why not just replace **"NO_INFO_FIX"** with **""** ?

**Comment by Ved-vampir** [comment]
@dachary, because of this conversation
https://github.com/ceph/ceph/pull/3763#issuecomment-75744912
I can change to "", if is needed, no matter for me.

**Comment by Ved-vampir** [comment]
I forgot to add test changes

**Comment by jcsp** [comment]
Looks good, thanks

**Pull request merged**
