### PR TITLE
pybind/mgr/cephadm/serve: don't remove ceph.conf which leads to qa failure

### PR DESCRIPTION
**Pull request by dparmar18**
- Removal of ceph.conf during qa run causes command failure: [teuthology-failure-log1](http://pulpito.front.sepia.ceph.com/pdonnell-2022-06-12_05:08:12-fs:workload-wip-pdonnell-testing-20220612.004943-distro-default-smithi/6875276/), [teuthology-failure-log2](http://pulpito.front.sepia.ceph.com/pdonnell-2022-06-12_05:08:12-fs:workload-wip-pdonnell-testing-20220612.004943-distro-default-smithi/6875321/). 

- This is fixed by not removing the ceph.conf during the process of deleting old files.

Fixes: https://tracker.ceph.com/issues/56024

Signed-off-by: Dhairya Parmar <dparmar@redhat.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by rkachach** [comment]
Did you test this change in a real deployment? specially when adding a new host (just to make sure

**Comment by dparmar18** [comment]
> Did you test this change in a real deployment? specially when adding a new host (just to make sure configuration propagation to new hosts is working properly)

@rkachach I just built a quay image `quay.io/dparmar/ceph:cephadmbuildtesting` and did a bootstrap on a VM where I tested adding/removing hosts and their `_admin` labels, the `ceph.conf` stays there intact.

**Comment by dparmar18** [comment]
jenkins test api

**Comment by vshankar** [comment]
@dparmar18 - you could try running failed test

        https://pulpito.ceph.com/vshankar-2022-06-19_08:22:46-fs-wip-vshankar-testing1-20220619-102531-testing-default-smithi/6886677/

with this fix.

**Comment by dparmar18** [comment]
> @dparmar18 - you could try running failed test
> 
> ```
>     https://pulpito.ceph.com/vshankar-2022-06-19_08:22:46-fs-wip-vshankar-testing1-20220619-102531-testing-default-smithi/6886677/
> ```
> 
> with this fix.

@vshankar thanks! I'll try it out with this fix.

**Comment by adk3798** [comment]
> > > @dparmar18 - you could try running failed test
> > > ```
> > >     https://pulpito.ceph.com/vshankar-2022-06-19_08:22:46-fs-wip-vshankar-testing1-20220619-102531-testing-default-smithi/6886677/
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > with this fix.
> > 
> > 
> > @vshankar thanks! I'll try it out with this fix.
> 
> @vshankar Tested with same parameters and here is the result: http://pulpito.front.sepia.ceph.com/dparmar-2022-06-20_13:38:42-fs-wip-dparmar-cephadm-56024-distro-default-smithi/6887843/

I'm going to also run this through the orch suite mostly as a formality and then we should be good here I think

**Review by adk3798 — APPROVED** [review]

**Comment by vshankar** [comment]
@adk3798 please run this through fs:upgrade suite too.

**Comment by adk3798** [comment]
https://pulpito.ceph.com/adking-2022-07-01_05:11:14-orch:cephadm-wip-adk-testing-2022-06-30-2110-distro-default-smithi/

4 Failed tests from
```
Command failed on smithi162 with status 123: "find /home/ubuntu/cephtest/archive/syslog -name '*.log' -print0 | sudo xargs -0 --no-run-if-empty -- gzip --"
```
and 1 dead test from
```
{'smithi050.front.sepia.ceph.com': {'attempts': 12, 'censored': "the output has been hidden due to the fact that 'no_log: true' was specified for this result", 'changed': True}}
```
I believe these are all infra issues and I did see these same failures in another run with different PRs (and notably, not on the same tests) in 
https://pulpito.ceph.com/adking-2022-07-01_05:08:10-orch:cephadm-wip-adk3-testing-2022-06-30-2111-distro-default-smithi/

Quite confident the failures are unrelated to PRs in the run, so I think we're good here.


Still need to do fs upgrade suite. Will run that next

**Comment by adk3798** [comment]
fs/upgrade suite

https://pulpito.ceph.com/adking-2022-07-01_19:57:19-fs:upgrade-wip-adk-testing-2022-06-30-2110-distro-default-smithi/

Just 1 infra failure:
```
Command failed on smithi026 with status 123: "find /home/ubuntu/cephtest/archive/syslog -name '*.log' -print0 | sudo xargs -0 --no-run-if-empty -- gzip --"
```

**Pull request merged**
