### PR TITLE
erasure code: shec performance optimization by SIMD instructions

### PR DESCRIPTION
**Pull request by t-miyamae**
added shec's performance optimization
- SIMD instructions

### CODE REVIEW

**Comment by t-miyamae** [comment]
@dachary thanks in advance

**Comment by dachary** [comment]
@t-miyamae awesome :-) could you also please update the ceph-erasure-code-corpus accordingly ? You will find an example of how to do so with the jerasure test that verify all optimized variants encode / decode exactly in the same way.

**Comment by dachary** [comment]
Also could you split this in two separate pull requests ? They are different topics really.

**Comment by t-miyamae** [comment]
@dachary Thank you for your comments. At first we have created a pull request for updating ceph-erasure-code-corpus (https://github.com/ceph/ceph-erasure-code-corpus/pull/1).

**Comment by t-miyamae** [comment]
@dachary We have split this pull request into two. Decoding cache is moved to #5257.

**Comment by dachary** [comment]
@t-miyamae I merged your pull request to ceph-erasure-code-corpus. You now need to modify this pull request so that it also changes to ceph-erasure-code-corpus to include your change. You can do that with
<pre>
git submodule update --remote ceph-erasure-code-corpus
git add ceph-erasure-code-corpus
git push --force
</pre>
when the make check bot runs, it will pick your modified version of ceph-erasure-code-corpus and verify it runs ok. Since it is running on a machine with sse4, it will verify generic, sse3 and sse4 which will be proof enough that it works.

**Comment by t-miyamae** [comment]
@dachary We have updated ceph-erasure-code-corpus as you told.

**Comment by dachary** [comment]
I've also double checked manually.

**Pull request merged**
