### PR TITLE
quincy: build: Remove ceph-libboost* packages in install-deps

### PR DESCRIPTION
**Pull request by adamemerson**
backport tracker: https://tracker.ceph.com/issues/62102

---

backport of https://github.com/ceph/ceph/pull/52559 + a quincy-only patch
parent tracker: https://tracker.ceph.com/issues/62097

### CODE REVIEW

**Comment by adamemerson** [comment]
jenkins, retest this please

**Comment by adamemerson** [comment]
jenkins, retest this please

**Comment by cbodley** [comment]
jenkins test make check

**Comment by idryomov** [comment]
> No analogous commit exists in main as while main's Jammy case installs ceph-libboost, we just need a system package here.

We are also missing `ensure_decent_gcc_on_ubuntu 11 focal` call from main's Focal case.  This script is definitely not the most coherent thing in the world...

**Comment by idryomov** [comment]
jenkins test make check

**Review by idryomov — APPROVED** [review]

**Comment by cbodley** [comment]
oh dear, the [make check](https://jenkins.ceph.com/job/ceph-pull-requests/119485/consoleFull#1317379859e4bfde06-44c1-4b3c-8379-d9ee175fb257) failures look related to https://tracker.ceph.com/issues/62203:
```
/home/jenkins-build/build/workspace/ceph-pull-requests/src/seastar/include/seastar/core/bitset-iter.hh:123:34: error: 'iterator<std::input_iterator_tag, int>' is deprecated [-Werror,-Wdeprecated-declarations]
class set_iterator : public std::iterator<std::input_iterator_tag, int>
                                 ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/bits/stl_iterator_base_types.h:127:12: note: 'iterator<std::input_iterator_tag, int>' has been explicitly marked deprecated here
    struct _GLIBCXX17_DEPRECATED iterator
           ^
```
some jenkins nodes have upgraded to gcc12 and, while these builds use clang-14 as the compiler, they still select gcc12's standard library. as i commented in the tracker, that gcc12 upgrade may have been my fault. ideally these branches would build against gcc12 too, but i'll work with Dan to try to clean this up

in the meantime i'll rerun the check in the hope that jenkins chooses a different node

**Comment by cbodley** [comment]
jenkins test make check

**Comment by cbodley** [comment]
run-tox-qa failing. looks like the same issues from https://github.com/ceph/ceph/pull/52701
```
flake8: install_deps /home/jenkins-build/build/workspace/ceph-pull-requests/src/pybind/mgr> python -I -m pip install flake8
flake8: freeze /home/jenkins-build/build/workspace/ceph-pull-requests/src/pybind/mgr> python -m pip freeze --all
flake8: flake8==6.1.0,mccabe==0.7.0,pip==22.3.1,pycodestyle==2.11.0,pyflakes==3.1.0,setuptools==65.6.3,wheel==0.38.4
flake8: commands[0] /home/jenkins-build/build/workspace/ceph-pull-requests/src/pybind/mgr> flake8 --config=tox.ini alerts balancer cephadm cli_api crash devicehealth diskprediction_local hello iostat localpool nfs orchestrator prometheus rgw selftest
cephadm/tests/fixtures.py:93:91: E231 missing whitespace after ','
cephadm/tests/fixtures.py:95:104: E231 missing whitespace after ','
cephadm/tests/test_upgrade.py:95:86: E231 missing whitespace after ','
cephadm/tests/test_upgrade.py:97:47: E231 missing whitespace after ','
cephadm/tests/test_upgrade.py:99:75: E231 missing whitespace after ','
crash/module.py:12:100: E231 missing whitespace after ','
6     E231 missing whitespace after ','
flake8: exit 1 (0.86 seconds) /home/jenkins-build/build/workspace/ceph-pull-requests/src/pybind/mgr> flake8 --config=tox.ini alerts balancer cephadm cli_api crash devicehealth diskprediction_local hello iostat localpool nfs orchestrator prometheus rgw selftest pid=1949344
flake8: FAIL ✖ in 2.86 seconds
```

**Comment by cbodley** [comment]
prepared that quincy backport in https://github.com/ceph/ceph/pull/52770

**Comment by idryomov** [comment]
Since `run-tox-mgr` is the only failure and it can't possibly be related to this PR, we could have a admin override `make check` here and merge as is.  @cbodley If you agree, I can try doing that.

**Comment by adamemerson** [comment]
> > prepared that quincy backport in #52770
> 
> @adamemerson it seems that backport won't pass checks without this PR, and this PR won't pass checks without that backport. can you please pull that commit into this one?

Done

**Comment by cbodley** [comment]
surely the checks will pass this time 🤞

**Pull request merged**
