### PR TITLE
librados: Wip 10425

### PR DESCRIPTION
**Pull request by rzarzynski**
Proposal of fix for issue #10425 and two bugs related with it.
For details please refer http://tracker.ceph.com/issues/10425

### CODE REVIEW

**Comment by liewegas** [comment]
do you mind creating a unit test case for this?  test/librados/misc.cc seems like a good place.  feed it a bad monitor address or whatever to induce the failure?

**Comment by rzarzynski** [comment]
I prepared the unit test for calling ceph_connect() twice. It is here: https://github.com/rzarzynski/ceph/compare/wip-10425-unittest

**Comment by rzarzynski** [comment]
I have just created #3519 in case of merging the unit test eventually.

**Comment by liewegas** [comment]
@rzarzynski would it make more sense to make sure objecter is freed in the first connect() attempt's failure path?

**Comment by rzarzynski** [comment]
It would be much more elegant solution in my opinion. However, a potential obstacle exists. Please take a look at the _librados::RadosClient::wait_for_osdmap()_. There is "_objecter == NULL_" guard while others methods perform explicit check on state of _RadosClient_ instance (i.e. _"state == CONNECTED"_). Is it intensional? I'm afraid that early free might lead to subtle change of interface.

**Comment by liewegas** [comment]
On Thu, 29 Jan 2015, rzarzynski wrote:
> It would be much more elegant solution in my opinion. However, a 
> potential obstacle exists. Please take a look at the 
> _librados::RadosClient::wait_for_osdmap()_. There is "_objecter == 
> NULL_" guard while others methods perform explicit check on state of 
> _RadosClient_ instance (i.e. _"state == CONNECTED"_). Is it intensional? 
> I'm afraid that early free might lead to subtle change of interface.

Oh, I think that is an accident.  Pretty sure the check should be 
consistent with everything else.  Users have no business calling 
wait_for_osdmap when connect() has failed.  :)

**Comment by rzarzynski** [comment]
I'm not afraid anymore. :-) I will fix the guard too.

**Comment by dachary** [comment]
Could you please rebase the changes in just two commits ? The message for the commit that fixes must contain the Fixes: #10688 (as you did in the first commit). And the body of the commit message must explain the original problem (feel free to pick from the issue description). This commit will be backported and having a nice commit message and a single commit will make it easier. The second commit should be https://github.com/rzarzynski/ceph/commit/cd1f7f17789e91fb8ed09703839ebd9792b2ea09

**Comment by rzarzynski** [comment]
@dachary no problem. But what about the unit test from #3519? Should I add it as the third commit or just include as a part ot the first one?

**Comment by dachary** [comment]
@rzarzynski it would make sense for the tests #3519 to be part of the commit that fixes #10688 since the test file already existed back in dumpling.

**Comment by rzarzynski** [comment]
@dachary thank you. Rebased version with unit test onboard has been pushed.

**Comment by dachary** [comment]
@rzarzynski thanks. It will now be picked for integration testing (that's what needs-qa is about) and be merged if it comes out clean.

**Comment by jdurgin** [comment]
Reviewed-by:

**Pull request merged**
