### PR TITLE
jewel: pre-jewel "osd rm" incrementals are misinterpreted

### PR DESCRIPTION
**Pull request by shinobu-x**
http://tracker.ceph.com/issues/19210

### CODE REVIEW

**Comment by shinobu-x** [comment]
retest please

**Comment by shinobu-x** [comment]
retest this

**Comment by shinobu-x** [comment]
please retest this

**Comment by shinobu-x** [comment]
retest this please

**Comment by smithfarm** [comment]
@liewegas @jdurgin This passed a rados run at http://tracker.ceph.com/issues/19538#note-49

**Pull request merged**
