### PR TITLE
rgw: fix init_bucket_for_sync retcode

### PR DESCRIPTION
**Pull request by shashalu**
init_bucket_for_sync error retcode should be negative

Signed-off-by: Shasha Lu <lu.shasha@eisoo.com>

### CODE REVIEW

**Comment by theanalyst** [comment]
jenkins test this please

**Comment by theanalyst** [comment]
can you remove the merge commit

**Comment by cbodley** [comment]
can you rebase please?

**Comment by shashalu** [comment]
@cbodley 
I don't know how to deal with this before, thanks for you remind.  Already rebased.

**Pull request merged**
