### PR TITLE
mds: fix stray purging in 'stripe_count > 1' case

### PR DESCRIPTION
**Pull request by ukernel**
Fixes: #15050
Signed-off-by: Yan, Zheng <zyan@redhat.com>

### CODE REVIEW

**Comment by ukernel** [comment]
qa https://github.com/ceph/ceph-qa-suite/pull/867

**Comment by gregsfortytwo** [comment]
LGTM, testing

**Comment by jcsp** [comment]
Here's an instance of this passing: http://qa-proxy.ceph.com/teuthology/jspray-2016-03-14_05:50:11-fs-wip-jcsp-testing---basic-mira/58829/teuthology.log

**Comment by gregsfortytwo** [comment]
Also here: http://pulpito.ceph.com/gregf-2016-03-15_04:07:43-fs-greg-fs-testing-314---basic-mira/

**Pull request merged**
