### PR TITLE
Add support for Oracle Linux 8

### PR DESCRIPTION
**Pull request by ea1363**
Oracle Linux 8 is compatible with RHEL 8.  So it can be treated the same way as RHEL 8.

Signed-off-by: ea1363 <76113928+ea1363@users.noreply.github.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ x] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ x ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by adk3798** [comment]
@ea1363 ususally the process we go for for getting patches in is to first make a patch against main branch and then backport to stable release branches. Would you be okay with retargeting this patch to main branch then we could backport to quincy afterward?

**Comment by phlogistonjohn** [comment]
I'll add that the checklist job is failing because you didn't tick off all the expected items. The checklist is subtly encouraging you to file a tracker ticket. Having a ticket makes the backport process easy (easier at least) and thus targeting your patch as @adk3798 is suggesting and filing a matching tracker ticket will simplify the process to get your patch on the quincy branch.

**Comment by ea1363** [comment]
I’m OK with whatever you suggest.  I’m a newbie in terms of working with github and such.  It may be easier for another developer to make the patch (it’s literally one line).  But I’ll give it a try. I’ll also try and create a ticket so I can tick off all the required boxes. 

—
Edsel Adap
***@***.***

**Comment by adk3798** [comment]
> I’m OK with whatever you suggest. I’m a newbie in terms of working with github and such. It may be easier for another developer to make the patch (it’s literally one line). But I’ll give it a try. I’ll also try and create a ticket so I can tick off all the required boxes. — Edsel Adap ***@***.***
> […](#)
> On Aug 3, 2022, at 12:13 PM, Adam King ***@***.***> wrote: ﻿ @ea1363 ususally the process we go for for getting patches in is to first make a patch against main branch and then backport to stable release branches. Would you be okay with retargeting this patch to main branch then we could backport to quincy afterward? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.

I can open a new PR for this

**Comment by adk3798** [comment]
> I’m OK with whatever you suggest. I’m a newbie in terms of working with github and such. It may be easier for another developer to make the patch (it’s literally one line). But I’ll give it a try. I’ll also try and create a ticket so I can tick off all the required boxes. — Edsel Adap ***@***.***
> […](#)
> On Aug 3, 2022, at 12:13 PM, Adam King ***@***.***> wrote: ﻿ @ea1363 ususally the process we go for for getting patches in is to first make a patch against main branch and then backport to stable release branches. Would you be okay with retargeting this patch to main branch then we could backport to quincy afterward? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.

made a new PR https://github.com/ceph/ceph/pull/47523 and tracker https://tracker.ceph.com/issues/57080

**Pull request closed without merging**
