### PR TITLE
nautilus: osd/PrimaryLogPG: update oi.size on write op implicitly truncating ob…

### PR DESCRIPTION
**Pull request by pdvian**
https://tracker.ceph.com/issues/41703

### CODE REVIEW

**Comment by badone** [comment]
jenkins test make check

**Comment by badone** [comment]
jenkins render docs

**Comment by badone** [comment]
jenkins test docs

**Comment by badone** [comment]
This failed to build with 7.4 yet built successfully with 8.3. See https://github.com/ceph/ceph/pull/30283 for the solution to the build failure when using 7.4

**Comment by yuriw** [comment]
[wip-yuri5-testing-2019-10-02-0010-nautilus](https://trello.com/c/mCVmvIqP/702-wip-yuri5-testing-2019-10-02-0010-nautilus)

**Pull request merged**
