### PR TITLE
rbd: rbd order will be place in 22, when set to 0 in the config_opt

### PR DESCRIPTION
**Pull request by renhwztetecs**
rbd: rbd order will be place in 22, when set to 0 in the config_opt

Fixes: #14047
Signed-off-by: huanwen ren <ren.huanwen@zte.com.cn>

### CODE REVIEW

**Comment by dachary** [comment]
@renhwztetecs please ignore the bot failure, it is a false negative ( see http://tracker.ceph.com/issues/13986 for more information). You can reschedule a run by rebasing and repushing.

**Comment by jdurgin** [comment]
This looks good, but needs to modify the defaults test: https://github.com/ceph/ceph/blob/master/src/test/pybind/test_rbd.py#L170

**Comment by dillaman** [comment]
@renhwztetecs Did you not need to modify the test @jdurgin pointed out?

**Comment by renhwztetecs** [comment]
@dillaman
I will try to modify the test
Thank you

**Comment by renhwztetecs** [comment]
@dillaman @jdurgin 
I have modified the test, Please have a look at:
https://github.com/ceph/ceph/pull/6995

**Comment by dillaman** [comment]
@renhwztetecs Can you just append that commit to this PR instead of opening a new PR?

**Comment by renhwztetecs** [comment]
@dillaman 
Oh, I have already,The test is not to mention alone?

**Comment by dillaman** [comment]
I recommend that you ```git cherry-pick bea6a0a1b349f21ce70868f31ce02372d1820cb0``` into the ssssztes:renhw-wip-14047 branch and repush so it is part of this PR.

**Comment by jdurgin** [comment]
While you're at it, can you set the git author field too? configure it via:

```
git config --global user.name "huanwen ren"
git config --global user.email "ren.huanwen@zte.com.cn"
```
With this configuration, whenever you 'git commit -s' your signed-off-by line will be automatically added to the commit message.

To change the author of your existing commits, ```git rebase -i HEAD~3`` (assuming there are 3 commits you want to change), select e to edit for each commit to change, and for each commit run 

```
git commit --amend --author "huanwen ren <ren.huanwen@zte.com.cn>"
git rebase --continue
```

**Comment by renhwztetecs** [comment]
@ jdurgin 
Many thanks for your kind help

**Comment by renhwztetecs** [comment]
@dillaman 
I have put the test into the PR
thank for you recommend

**Comment by jdurgin** [comment]
looks good, thanks!

**Pull request merged**
