### PR TITLE
librados: aio_operate support mtime set

### PR DESCRIPTION
**Pull request by tianshan**
Signed-off-by: Tianshan Qu <tianshan@xsky.com>

### CODE REVIEW

**Comment by tianshan** [comment]
@tchaikov  please help review

**Comment by neha-ojha** [comment]
The `make check` failure seems related. Needs to be fixed.

**Comment by tianshan** [comment]
test this please

**Comment by tianshan** [comment]
test this please

**Comment by tianshan** [comment]
test this please

**Comment by tchaikov** [comment]
@tianshan sorry for getting to this after such a long time. could you help me understand why the use case of specifying a mtime to `aio_operate()`?

**Comment by tianshan** [comment]
@tchaikov  If we want to do some modify but not change the mtime, some versioned op in rgw will need this, rgw use mtime as modify time.
And seems aio interface is not necessary, this can be closed.

**Pull request closed without merging**
