### PR TITLE
jewel: FileStore: fiemap cannot be totally retrieved in xfs when the number of extents > 1364 

### PR DESCRIPTION
**Pull request by Abhishekvrshny**
http://tracker.ceph.com/issues/17877

### CODE REVIEW

**Comment by dachary** [comment]
jenkins test this please (jenkins stuck)

**Comment by smithfarm** [comment]
@tchaikov As wrote in the hammer backport PR, we might want to cherry-pick c3748fa also once #12148 is merged.

**Comment by tchaikov** [comment]
#12148 is merged, and the commit to be cherry-picked in that PR is c3748fa7737b6c43de2dae5d957fcff01322515c

**Comment by dachary** [comment]
It passed the rados (http://tracker.ceph.com/issues/17851#note-12) suite. It also passed the upgrade/jewel-x and upgrade/hammer-x (http://tracker.ceph.com/issues/17851#note-15) suites. Note that it won't be included in 10.2.4, reason why it targets jewel-next.

**Comment by dachary** [comment]
@Abhishekvrshny could you please add the commit as suggested by @tchaikov at https://github.com/ceph/ceph/pull/11998#issuecomment-263469714 ?

**Comment by Abhishekvrshny** [comment]
@dachary @tchaikov : Added commit c3748fa7737b6c43de2dae5d957fcff01322515c . Please review and remove DNM if A-OK.

**Comment by liewegas** [comment]
lgtm!

**Comment by dachary** [comment]
this updated PR will be scheduled in the next round of testing

**Comment by smithfarm** [comment]
This passed another rados run at http://tracker.ceph.com/issues/17851#note-45 with some unrelated failures.

**Comment by smithfarm** [comment]
This passed another rados run at http://tracker.ceph.com/issues/17851#note-53

**Pull request merged**
