### PR TITLE
luminous: rgw segfaults after running radosgw-admin data sync init 

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/22181

### CODE REVIEW

**Comment by smithfarm** [comment]
```
CMake Error at src/CMakeLists.txt:676 (add_subdirectory):
  The source directory

    /home/jenkins-build/build/workspace/ceph-pull-requests/src/lua

  does not contain a CMakeLists.txt file.


CMake Error at cmake/modules/MergeStaticLibraries.cmake:21 (message):
  liblua not a valid target
Call Stack (most recent call first):
  src/cls/CMakeLists.txt:269 (merge_static_libraries)
```

**Comment by smithfarm** [comment]
Jenkins re-test this please

**Comment by smithfarm** [comment]
Looks like luminous has a transient crash in `test_objectstore_memstore.sh` . . . this is the second PR I'm seeing it in.

```
    -2> 2017-11-21 11:09:05.985217 7f4c3b836700 -1 --- buffer lengths mismatch expected 0x56a61 != actual 0x3f232
    -1> 2017-11-21 11:09:05.994612 7f4c3b836700 -1 --- buffer mismatch between offset 0x3f232 and 0x0, total 0x3f232
     0> 2017-11-21 11:09:06.016278 7f4c3b836700 -1 /home/jenkins-build/build/workspace/ceph-pull-requests/src/test/objectstore/store_test.cc: In function 'virtual void SyntheticWorkloadState::C_SyntheticOnReadable::finish(int)' thread 7f4c3b836700 time 2017-11-21 11:09:06.015226
/home/jenkins-build/build/workspace/ceph-pull-requests/src/test/objectstore/store_test.cc: 3358: FAILED assert(bl_eq(state->contents[hoid].data, r2))

 ceph version 12.2.1-832-g6bf51da (6bf51dab4b61500e74ca89ad221b3178163ccaae) luminous (stable)
 1: (ceph::__ceph_assert_fail(char const*, char const*, int, char const*)+0x102) [0x7f4c403dce02]
 2: (SyntheticWorkloadState::C_SyntheticOnReadable::finish(int)+0x372) [0x557b6b5ce532]
 3: (Context::complete(int)+0x9) [0x557b6b5a8aa9]
 4: (Finisher::finisher_thread_entry()+0x460) [0x7f4c403db010]
 5: (()+0x76ba) [0x7f4c497326ba]
 6: (clone()+0x6d) [0x7f4c3f0713dd]
 NOTE: a copy of the executable, or `objdump -rdS <executable>` is needed to interpret this.
```

**Comment by yuriw** [comment]
[luminous rgw => wip-yuri3-testing-2018-01-18-0053](https://trello.com/c/fu2gGLvL/233-luminous-rgw-wip-yuri3-testing-2018-01-18-0053)

**Comment by yuriw** [comment]
@smithfarm @theanalyst @cbodley ready for merge

**Comment by yuriw** [comment]
test this please

**Pull request merged**
