### PR TITLE
Feature10891

### PR DESCRIPTION
**Pull request by stiopaa1**
This will only output all the values applicable to a given type of pool.
So for example for a pool that is not a tier pool values like HIT_SET_TYPE,
HIT_SET_PERIOD, HIT_SET_COUNT etc. will be ignored.

Feature: #10891
Signed-off-by: Michal Jarzabek <stiopa@gmail.com>

### CODE REVIEW

**Comment by tchaikov** [comment]
@stiopaa1 Michal, could you revise your commit log a little bit?
- start the commit log with a brief line covering  what the change is for, which is followed by an empty line. i'd suggest start this brief line with ``mon/OSDMonitor:`` so we can have an idea of what area this change touches at the first glance. 
- and put the details in another line
- as you are fixing 10891, would be better if you could replace `Feature: #10891` with `Fixes: #10891`? so tracker can log this commit and connect it with this ticket.

you can see more commit log examples using `git log src/mon/OSDMonitor.cc`.

@athanatos sam, could you take a look at this change at your convenience? i am just not sure if i missed anything or too picky sometimes.

**Comment by tchaikov** [comment]
@stiopaa1 
to update your pull request, you should *squash* your existing commit https://github.com/stiopaa1/ceph/commit/122ad832107f0dd244b73a556335644f73f16480 with your changes https://github.com/stiopaa1/ceph/commit/9a750579f529ff9a3853abe60602a0c9724c5216 to address the comments. personally, i use `git rebase -i HEAD~2` to do this job.

**Comment by stiopaa1** [comment]
I have removed assert, fixed << indentation and renamed enum_var and enum_var_it variables.
I have also squashed the commits - I have never done this before, so I hope it was done correctly...

**Comment by tchaikov** [comment]
@jecluis sorry, i just saw your comment after pushing the "merge" button. will address your concerns in another commit.

**Comment by jecluis** [comment]
oh, right... and I've been dropping comments throughout ;)

**Comment by stiopaa1** [comment]
@tchaikov, I can correct the parts that @jecluis is not happy about if you haven't yet...

**Comment by tchaikov** [comment]
@stiopaa1 i haven't. that would be awesome, thanks!

**Comment by stiopaa1** [comment]
cool, will do:)

**Pull request merged**
