### PR TITLE
mds: function parameter 'newstate' should be passed by reference

### PR DESCRIPTION
**Pull request by x11562**
Signed-off-by: Na Xie <xie.na@h3c.com>

### CODE REVIEW

**Comment by gregsfortytwo** [comment]
It's just an integer; is there some point to passing by reference I'm missing?
I admit the use of the const keyword there is a little confusing, but...*shrug*

**Comment by x11562** [comment]
references reduce memory copy,
‘const’ is most of the time a flag of unchangable, i think

**Comment by x11562** [comment]
i think it is better to pass by reference as it can reduce memory copy,

**Comment by tchaikov** [comment]
well, instead of copying the enum (int), a pointer will be passed in. and the enum would be **referenced** by this pointer. which could also slow it down. i don't think it help with the performance in any way.

**Pull request closed without merging**
