### PR TITLE
quincy: pybind/mgr: reopen database handle on blocklist

### PR DESCRIPTION
**Pull request by batrick**
backport tracker: https://tracker.ceph.com/issues/62023

---

backport of https://github.com/ceph/ceph/pull/50291
parent tracker: https://tracker.ceph.com/issues/55606

this backport was staged using ceph-backport.sh version 16.0.0.6848
find the latest version at https://github.com/ceph/ceph/blob/main/src/script/ceph-backport.sh

### CODE REVIEW

**Comment by batrick** [comment]
jenkins test make check

**Comment by batrick** [comment]
jenkins test make check

**Comment by batrick** [comment]
jenkins test make check

**Comment by ljflores** [comment]
Rados approved: https://tracker.ceph.com/projects/rados/wiki/QUINCY#httpstrellocomcPbdnG4C31918-wip-yuri3-testing-2024-01-02-1236-quincy

**Comment by rzarzynski** [comment]
@ajarr: this backport is ready for a review. It also passed the QA.

**Review by ljflores — APPROVED** [review]
Approved core-wise.

**Pull request merged**
