### PR TITLE
bluestore: replace max, min macros with standard ones

### PR DESCRIPTION
**Pull request by shinobu-x**
Reference: #19614

Signed-off-by: Shinobu Kinjo <shinobu@redhat.com>

### CODE REVIEW

**Comment by shinobu-x** [comment]
test this please

**Comment by tchaikov** [comment]
merge conflict with my test branch. dropping.

**Comment by liewegas** [comment]
@shinobu-x rebase please

**Comment by liewegas** [comment]
needs rebase

**Comment by liewegas** [comment]
This was covered by an earlier PR

**Pull request closed without merging**
