### PR TITLE
MDSMonitor.cc: fix mdsmap.<namespace> subscriptions

### PR DESCRIPTION
**Pull request by ukernel**
Signed-off-by: Yan, Zheng <zyan@redhat.com>

### CODE REVIEW

**Comment by jcsp** [comment]
Looks good, what was noticing this bug, #8386?

**Comment by jcsp** [comment]
It's weird that TestMultiFilesystems.test_clients was passing in spite of this bug, worth investigating

**Comment by ukernel** [comment]
I found that if mount non-default namespae, client does not reconnect to mds when mds restarts

**Comment by jcsp** [comment]
http://pulpito.front.sepia.ceph.com/jspray-2016-05-25_19:00:36-fs-wip-jcsp-testing-20160526---basic-mira/

**Pull request merged**
