### PR TITLE
ceph-volume: drop filestore support

### PR DESCRIPTION
**Pull request by guits**
FileStore support has been dropped as of Ceph Reef, let's drop it in ceph-volume too.

### CODE REVIEW

**Comment by guits** [comment]
jenkins test ceph-volume tox

**Comment by guits** [comment]
jenkins test ceph-volume tox

**Comment by guits** [comment]
jenkins test ceph-volume tox

**Comment by guits** [comment]
http://pulpito.front.sepia.ceph.com/gabrioux-2023-03-28_15:32:23-orch:cephadm-wip-guits-testing-4-2023-03-28-0857-distro-default-smithi/

**Review by adk3798 — APPROVED** [review]

**Comment by Svelar** [comment]
jenkins test api

**Comment by guits** [comment]
http://pulpito.ceph.com/gabrioux-2023-05-15_12:49:24-orch:cephadm-wip-guits-testing-4-2023-05-15-1111-distro-default-smithi/

**Pull request merged**
