### PR TITLE
ceph-disk: erase 110MB for nuking existing bluestore

### PR DESCRIPTION
**Pull request by tchaikov**
10M is not enough for erasing the data partition *and* db partition,
let's make it 110M.

Fixes: http://tracker.ceph.com/issues/22354
Signed-off-by: Kefu Chai <kchai@redhat.com>

### CODE REVIEW

**Comment by tchaikov** [comment]
@alfredodeza i think we can apply a similar fix to `zap_data()` in `zap.py`. what do you think?

**Comment by alfredodeza** [comment]
Yes, that sounds sensible to me!

**Comment by wido** [comment]
Looks good to me! However, what I've been doing lately is using *blkdiscard* to fully wipe a SSD. This will erase all bits within ~15 sec on a SSD. It just tells the controller to erase all cells.

We might want to add that

**Comment by alfredodeza** [comment]
hrmn, but then we need to do extra detection to see what kind of device we are handling?

**Comment by wido** [comment]
Yes, you will need to check the *rotational* flag in sysfs to see it it's a SSD. It's very effective though! I can recommend it.

But that's not in scope for this PR, just wanted to bring it to the table for future option.

**Comment by tchaikov** [comment]
changelog:

- fixed a PEP-8 warning
```
ceph_disk/main.py:1613:80: E501 line too long (80 > 79 characters)
```

**Comment by tchaikov** [comment]
http://pulpito.ceph.com/kchai-2018-02-12_15:49:42-ceph-disk-wip-22354-kefu-distro-basic-vps/

**Comment by tchaikov** [comment]
http://pulpito.ceph.com/kchai-2018-02-22_06:22:20-ceph-disk-wip-22354-kefu-distro-basic-vps/

**Comment by kobigi** [comment]
Hi Guys,
i'm getting the same warning in the logs,
and OSD's is trying to get up and fails over and over again.

My deployment is with containers using ceph-ansible.

i can not find the same code (ok i guess you did not merged yet)
My question is ?
if i ll change the default value of count fro 10 to 100 in the zap function , will it be sufficient ?
or maybe it should be 110 ?

File: "/usr/lib/python2.7/site-packages/ceph_disk/main.py"
rpm: ceph-common-12.2.2-0.el7.x86_64

def zap_linux(dev):
    try:
        # Thoroughly wipe all partitions of any traces of
        # Filesystems or OSD Journals
        #
        # In addition we need to write 10M of data to each partition
        # to make sure that after re-creating the same partition
        # there is no trace left of any previous Filesystem or OSD
        # Journal

        LOG.debug('Writing zeros to existing partitions on %s', dev)

        for partname in list_partitions(dev):
            partition = get_dev_path(partname)
            command_check_call(
                [
                    'wipefs',
                    '--all',
                    partition,
                ],
            )

            command_check_call(
                [
                    'dd',
                    'if=/dev/zero',
                    'of={path}'.format(path=partition),
                    'bs=1M',
                    'count=10',
                ],
            )

**Comment by tchaikov** [comment]
@kobigi are you zapping a device which was used for bluestore ? if yes, it should be 110.

**Comment by kobigi** [comment]
Hi  @tchaikov - yes indeed with bluestore,
which is the default in luminous,
and as far as i understood should have Performance wise X2 faster.
 will try 110
thx

**Comment by kobigi** [comment]
hi @tchaikov  some progress now
But now i 'm getting authentication failed ,
any help would be appreciated  - thx

+ echo '2018-02-23 08:55:43  entrypoint.sh: SUCCESS'
2018-02-23 08:55:43  entrypoint.sh: SUCCESS
+ return 0
+ exec /usr/bin/ceph-osd --cluster ceph -f -i 1 --setuser ceph --setgroup disk
+ trap _term SIGTERM
+ child_for_exec=52493
+ echo 'exec: PID 52493: spawning /usr/bin/ceph-osd --cluster ceph -f -i 1 --setuser ceph --setgroup disk'
exec: PID 52493: spawning /usr/bin/ceph-osd --cluster ceph -f -i 1 --setuser ceph --setgroup disk
+ wait 52493
+ /usr/bin/ceph-osd --cluster ceph -f -i 1 --setuser ceph --setgroup disk
starting osd.1 at - osd_data /var/lib/ceph/osd/ceph-1 /var/lib/ceph/osd/ceph-1/journal
2018-02-23 08:55:45.517387 7f016e33ed00 -1 osd.1 44 log_to_monitors {default=true}
2018-02-23 08:55:45.521824 7f016e33ed00 -1 osd.1 44 init authentication failed: (1) Operation not permitted

**Pull request merged**
