### PR TITLE
mgr/dashboard: handle infinite values for pools

### PR DESCRIPTION
**Pull request by afreen23**
Fixes https://tracker.ceph.com/issues/64724

### Issue:
Json parsing is failing because of Infinity values present in pools meteadata. "read_balance": {"score_acting": Infinity, "score_stable": Infinity,}
Due to this entire pool list is not rendered.

### Fix:
Added a handler for checking "inf" values and replacing them with a string "Infinity" so that json parsing does not fail on frontend.

------------------
### Before 
Screenshot from 2024-03-06 16-41-50

### After
Screenshot from 2024-03-07 01-26-30

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [x] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Comment by afreen23** [comment]
jenkins test make check

**Comment by afreen23** [comment]
jenkins test make check

**Review by nizamial09 — APPROVED** [review]
Thank you!

**Review by Pegonzal — APPROVED** [review]

**Comment by afreen23** [comment]
jenkins test api

**Comment by afreen23** [comment]
All required tests passing and cephadm test failing for some unrelated reason evrytime I push new changes.
for dashboard visual test failing

**Pull request merged**
