### PR TITLE
rgw/rgw_main.cc : fixes #12038

### PR DESCRIPTION
**Pull request by stiopaa1**
http://tracker.ceph.com/issues/12038

plus some cleanup

### CODE REVIEW

**Comment by yehudasa** [comment]
@stiopaa1 while I don't see anything wrong with these commits, I'm not sure of the actual purpose they serve. With regard to the declaration order, through most of the code the private variables come first, so I'm not sure that there is a good reason for changing that. We can add the const definitions.

**Comment by stiopaa1** [comment]
>With regard to the declaration order, through most of the code the private variables come first, so I'm not sure that there is a good reason for changing that

Just following this:
http://google-styleguide.googlecode.com/svn/trunk/cppguide.html#Declaration_Order
which according to 
https://github.com/ceph/ceph/blob/master/CodingStyle
I thought we should be following?


>while I don't see anything wrong with these commits, I'm not sure of the actual purpose they serve.

You mentioned declaration order commit and adding consts commit. Are you talking about the first commit here as well?

**Comment by yehudasa** [comment]
@stiopaa1 didn't talk about the first commit

**Comment by stiopaa1** [comment]
@yehudasa 

>what if the following theoretical configuration was passed:
rgw frontends = civetweb foo bar

>key_value will now hold 'foo bar'


I wasn't aware that this is a possible input, I thought that only possible inputs are :
[FRAMEWORK_NAME] [KEY]
or 
[FRAMEWORK_NAME] [KEY] = [VALUE]

It would be really helpful If you could provide me with a few examples of possible inputs this is supposed to be parsing.

**Comment by yehudasa** [comment]
Looking at the code now, and at the different civetweb configurable, I don't see a case where there's a need for a key without value specified. That been said, it'd be nice to be able to support it. But at the moment here are some existing options:

@stiopaa1 e.g.,

rgw frontends = civetweb port = 80
or
rgw frontends =  fastcgi socket_host=localhost socket_port = 9000
or
rgw frontends =  civetweb port=80, fastcgi socket_host = localhost socket_port = 9000

**Comment by stiopaa1** [comment]
Thanks, will fix this soon

**Comment by dachary** [comment]
> Thanks, will fix this soon

@stiopaa1 feel free to re-open when you have time to work on this one

**Pull request closed without merging**
