### PR TITLE
[DNM] jewel: msg: fast fail on connection refused

### PR DESCRIPTION
**Pull request by ddiss**
http://tracker.ceph.com/issues/18760
http://tracker.ceph.com/issues/18761

This is a Jewel backport of @branch-predictor 's "osd fast fail on connection refused" patch-set, which greatly improves OSD disk failure propagation delays, by having the OSDs immediately report pier OSDs as down if they refuse to accept connections, rather than waiting for intermittent heartbeat exchanges to detect the outage.

A number of other messenger changes are also picked up with this backport, to ensure that the "osd fast fail on connection refused" patch-set applies as cleanly as possible.

Tracker: http://tracker.ceph.com/issues/18760

### CODE REVIEW

**Comment by liewegas** [comment]
@ddiss This is probably a good time to also do a straight diff of msg/async against master and backport any async bug fixes to jewel as well.

**Comment by ddiss** [comment]
@liewegas : Sure, will take a look and raise a separate tracker for the async bug fix backports - thanks for the feedback!

**Comment by ddiss** [comment]
Jewel async bug fix backports tracker: http://tracker.ceph.com/issues/18761

**Comment by smithfarm** [comment]
Temporarily marking DNM while I track down a conflict between staged jewel PRs.

**Comment by yuriw** [comment]
Is being tested by @smithfarm as part of backporting

**Comment by ddiss** [comment]
Ping, anything I can do to move this along?

**Comment by smithfarm** [comment]
@ddiss This will be included in the next round of jewel integration tests. If you'd like to help me analyze test failures, that would certainly help move things along.

**Comment by ddiss** [comment]
@smithfarm sure, ping me with the logs if there are failures that need to be analysed.

**Comment by smithfarm** [comment]
**Note: this PR is targeting the 10.2.8 release - not to be merged until v10.2.7 tag is added!**

@ddiss @liewegas This PR was included in the rados run at http://tracker.ceph.com/issues/19538#note-4 which had the following results:

* of 227 total jobs:
** 222 passed on first try
** 3 passed on second try
** remaining 2 are problematic

(see http://tracker.ceph.com/issues/19538#note-4 for details)

Do you think this run is sufficient to merge this PR once the v10.2.7 tag has been added?

Any idea what might be causing the troubles at http://pulpito.ceph.com:80/smithfarm-2017-04-09_20:57:12-rados-wip-jewel-backports-distro-basic-smithi/ where I ran the two problematic jobs 5 times each?

**Comment by ddiss** [comment]
http://pulpito.ceph.com/smithfarm-2017-04-09_20:57:12-rados-wip-jewel-backports-distro-basic-smithi/1005562/
"ceph tell osd.0 flush_pg_stats" is failing with ENXIO:
This appears to already be tracked via: http://tracker.ceph.com/issues/14793

**Comment by smithfarm** [comment]
@ddiss Regarding the valgrind failure, @jdurgin wrote at #13212: "Of the failures, the only one I think is real is the valgrind one - it's detected what looks to be a leak of a message, and of async messenger's connection." 

Could that one be related to this PR?

**Comment by smithfarm** [comment]
@ddiss I extracted the valgrind logs in question and am sending them to you.

**Comment by ddiss** [comment]
@smithfarm thanks, taking a look now...

**Comment by ddiss** [comment]
>     <frame>
>       <ip>0xCAC9EA</ip>
>       <obj>/usr/bin/ceph-osd</obj>
>       <fn>AsyncConnection::_process_connection()</fn>
>       <dir>/tmp/buildd/ceph-10.2.6-264-g4054c12/src/msg/async</dir>
>       <file>AsyncConnection.cc</file>
>       <line>1185</line>
>  1161     case STATE_CONNECTING_SEND_CONNECT_MSG:
>  1162       {
>  ...
>  1183         bl.append((char*)&connect_msg, sizeof(connect_msg));
>  1184         if (authorizer) {
>  1185           bl.append(authorizer->bl.c_str(), authorizer->bl.length());
>  1186         }

It looks as though the async connect_msg authorizer blob is being leaked. It looks as though merging the async messenger fixes listed in http://tracker.ceph.com/issues/18761 would be a good start here. I'll start on that now.

**Comment by yuyuyu101** [comment]
I have no idea on leaking, since jewel's default msgr type is simple, maybe you can only backport simple connection refused method.

**Comment by jdurgin** [comment]
@yuyuyu101 one of the facets of the suite is msgr type - each of the valgrind failures is explicitly setting it to async (e.g. msgr/async.yaml in the description of the jobs with valgrind failures here: http://pulpito.ceph.com/smithfarm-2017-04-09_20:57:12-rados-wip-jewel-backports-distro-basic-smithi/)

**Comment by smithfarm** [comment]
@ddiss Please remove the DNM and ping me when you're ready to re-test this.

**Comment by smithfarm** [comment]
I re-populated the integration branch without this PR and the reproducer now passes: http://tracker.ceph.com/issues/19538#note-25

**Comment by smithfarm** [comment]
@ddiss Could you rebase this to latest jewel?

**Comment by smithfarm** [comment]
I opened https://github.com/ceph/ceph/pull/15804 as a companion to this PR and will include both in the next round of jewel integration tests.

@ddiss @yuyuyu101 Do you see any other async messenger fixes that might need to be backported, that are not covered by http://tracker.ceph.com/issues/18761 ?

**Comment by smithfarm** [comment]
Reproducer is: `teuthology-suite --ceph-repo https://github.com/ceph/ceph.git --ceph jewel --suite-repo https://github.com/ceph/ceph.git --suite-branch jewel --rerun smithfarm-2017-04-09_13:21:35-rados-wip-jewel-backports-distro-basic-smithi --machine-type smithi`

**Comment by smithfarm** [comment]
Pushed `fix_async_msgr_dispatch_econnrefused_down_jewel` to ceph-ci -> it's a combination of this PR and #15804

**Comment by smithfarm** [comment]
**running** http://pulpito.front.sepia.ceph.com:80/smithfarm-2017-06-21_21:42:58-rados-fix_async_msgr_dispatch_econnrefused_down_jewel-distro-basic-smithi/

**Comment by smithfarm** [comment]
@ddiss Here's another async msgr fix for jewel: https://github.com/ceph/ceph/pull/15726

(It doesn't explicitly mention memory leaks, though.)

**Pull request closed without merging**
