### PR TITLE
luminous: common/throttle: start using 64-bit values

### PR DESCRIPTION
**Pull request by pdvian**
http://tracker.ceph.com/issues/22698

### CODE REVIEW

**Comment by pdvian** [comment]
@ifed01 do we need to assert on lock.is_locked failure in _reset_max ?

**Comment by smithfarm** [comment]
@adamemerson @cbodley @jdurgin @tchaikov What's your opinion on backporting dd8aec3 to luminous? It's a big patch but:

1. we are still early in the luminous release cycle
2. bringing it in now will presumably prevent lots of cherry-pick conflicts

**Comment by ifed01** [comment]
@pdvian - my original commit didn't touch that assert on lock. You probably wrongly resolved some conflict during cherry-picking.

**Comment by ifed01** [comment]
@smithfarm - not sure if it makes sense to bring anything large/complex just to apply that stuff smoothly. As my original commit is pretty trivial it's much simpler to resolve the  conflicts manually. Just IMHO not sure what''s your policy/strategy for such backports

**Comment by adamemerson** [comment]
@smithfarm I'm in favor, since it'll mean we can run make check on Luminous without it hanging up on modern glibc/kernels.

**Comment by jdurgin** [comment]
@smithfarm common/Throttle.* typically has few backports - there was only 1 for jewel. I'd rather go with this minimal patch.

@pdvian no need to remove the assert - it's there to make sure we are always holding the right lock when we call _reset_max(), so we don't accidentally introduce a race that results in a bad throttle value

**Comment by tchaikov** [comment]
IMHO, backport dd8aec3cc896667d4d668bf479f93dc357826955 is good idea, but not just because it helps to backport this very change smoothly, but because it is a fix by itself as Adam pointed out.

**Comment by pdvian** [comment]
@ifed01 @jdurgin I did not find the assert statement to check whether mutex is locked or not in PR #19759 and master branch also does not have assert statement. Are we doing mutex lock check before calling _reset_max ? I was not clear on it so wanted to clarify from @ifed01 .

Here is the _reset_max definition from #19759 (and master branch too has same definition) :
void Throttle::_reset_max(int64_t m)
  {
    // lock must be held.
 -  if (static_cast<int64_t>(max) == m)
 +  if (max == m)
      return;
    if (!conds.empty())
      conds.front().notify_one();
   if (logger)
     logger->set(l_throttle_max, m);
   max = m;
 }

I have modified this PR and added assert on mutex lock condition failure.

Shall we wait till commit-id dd8aec3 backported to luminous ?

**Comment by pdvian** [comment]
Previous comment did not add clear _reset_max definition, here it is:

void Throttle::_reset_max(int64_t m)
{
  // lock must be held.
  if (max == m)
    return;
  if (!conds.empty())
    conds.front().notify_one();
  if (logger)
    logger->set(l_throttle_max, m);
  max = m;
}

**Comment by yuriw** [comment]
[wip-yuri4-testing-2018-01-29-1824-luminous](https://trello.com/c/PmEPazkj/249-wip-yuri4-testing-2018-01-29-1824-luminous)

**Comment by yuriw** [comment]
[wip-yuri4-testing-2018-01-31-1605-luminous](https://trello.com/c/96xgqD8p/251-wip-yuri4-testing-2018-01-31-1605-luminous)

**Pull request merged**
