### PR TITLE
mgr/nfs: do not suppress errors while updating export

### PR DESCRIPTION
**Pull request by dparmar18**
for any failure while updating export, it reports error like this:

$ ceph nfs export apply my-nfs -i export.conf
[
  {
    "msg": "Failed to apply export: export FSAL user_id must be 'nfs.my-nfs.1'",
    "state": "error"
  }
]
Error EIO:

This makes it always return code 5, no matter what the actual errno was/should be. This must be changed to report the correct errno, and a single line containing error message instead of a dict, i.e. with this patch it would be like this:

$ ceph nfs export apply my-nfs -i export.conf
Error EINVAL: export FSAL user_id must be 'nfs.my-nfs.1'

This looks much better, neat and correct IMO.

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Review by phlogistonjohn — COMMENTED** [review]
I think part of the issue here is that you're testing with a simplified case. The function name is a bit of a misnomer `apply_export` should really be called `apply_exports` because `export_config` could contain >1 export to update.

The idea behind creating a specialized AppliedExportResults class is to gather the results from each individual update and report on them. There can be all successes, all errors, or a mix of successes and errors.  As you point out the new(er) output is not as neat when there's only one input - and therefore only one item to report on.

First, I think returning after calling `aeresults.append` is a bug. It will break out of the loop and fail to apply the configuration for any export after the first. I also think removing `_change_export` is not ideal. Inlining this block of code makes it a bit harder to read and understand each step of the code individually.

What I would do is enhance `AppliedExportResults` so that it automatically "flattens" the results in the case of one error. In other words, if `AppliedExportResults' attribute `changes` contains only one item it should help provide a (more) simplified result.

There's only one downside to my plan, and it can be resolved in one of two ways. The issue is that a object_format doesn't currently provide a way for a result (as opposed to an exception) to give a status. This can be resolved by either: (1) adding code to object_format.py to give types a way to supply the status value or (2) raising an exception *after* determining the list only contains one error condition.

I think (1) is more correct but (2) is simpler to get done in the short term. Doing (2) also avoids you from having to touch object_format.py.

Here's some totally untested psudo-code diff to try and illustrate the changes I'm suggesting for (2).
```diff
diff --git a/src/pybind/mgr/nfs/export.py b/src/pybind/mgr/nfs/export.py
index 5887c898fef..6f0a0b2f134 100644
--- a/src/pybind/mgr/nfs/export.py
+++ b/src/pybind/mgr/nfs/export.py
@@ -166,10 +166,14 @@ class AppliedExportResults:
 
     def __init__(self) -> None:
         self.changes: List[Dict[str, str]] = []
+        self._exceptions: List[Exception] = []
         self.has_error = False
 
     def append(self, value: Dict[str, str]) -> None:
-        if value.get("state", "") == "error":
+        exc = value.pop('exception', None)
+        if exc is not None:
+            self._exceptions.append(exc)
+        if exc is not None or value.get("state", "") == "error":
             self.has_error = True
         self.changes.append(value)
 
@@ -179,6 +183,10 @@ class AppliedExportResults:
     def mgr_return_value(self) -> int:
         return -errno.EIO if self.has_error else 0
 
+    def raise_if_exception(self) -> None:
+        if self.has_error and len(self._exceptions) == 1:
+            raise self._exceptions[0]
+
 
 class ExportMgr:
     def __init__(
@@ -502,6 +510,7 @@ class ExportMgr:
         aeresults = AppliedExportResults()
         for export in exports:
             aeresults.append(self._change_export(cluster_id, export))
+        aeresults.raise_if_exception()
         return aeresults
 
     def _read_export_config(self, cluster_id: str, export_config: str) -> List[Dict]:
@@ -543,7 +552,7 @@ class ExportMgr:
         except Exception as ex:
             msg = f'Failed to apply export: {ex}'
             log.exception(msg)
-            return {"state": "error", "msg": msg}
+            return {"state": "error", "msg": msg, 'exception': ex}
 
     def _update_user_id(
             self,
```

Try this out for yourself (you may have to fix some errors/typos) and see if this works like you want it to for the single export case but retains the ability to handle multiple errors or a mix of successes and errors for the other case.

I also have no problem if you want to change the default error in `AppliedExportResults.mgr_return_value`. I think I picked it because it was general, but I honestly don't remember.

**Comment by phlogistonjohn** [comment]
I forgot to say, if you do fix this by method (2) - I think you could file a tracker to add the ability of a type to return a specific status. I would be open to implementing it later and then helping circle back to simplify AppliedExportResults.

**Comment by dparmar18** [comment]
> First, I think returning after calling aeresults.append is a bug. It will break out of the loop and fail to apply the configuration for any export after the first

Yeah that was a mistake on my part.

> What I would do is enhance AppliedExportResults so that it automatically "flattens" the results in the case of one error. In other words, if AppliedExportResults' attribute changes` contains only one item it should help provide a (more) simplified result.

I think  always sending EIO is still a problem even in case we have multiple errors. Solving case of only one error is an incomplete solution IMO but sending multiple return codes would not be possible and in this case we need to agree with a errno  and EIO might be the best option. This is a complicated case where we try to update multiple exports at the same time. I was checking quincy code and it looks a lot different, i see usage of `exception_handler` there are this new layer `_change_export()` doesn't exist, since you mentioned it makes it easier to understand the steps better; i'm curious what was the reason to stop using `exception_handler()`? We were able to handle multiple export modifications even in quincy right?

**Comment by dparmar18** [comment]
one more thing, I now understand the reason to send out a dict even if there were errors modifying exports; but even then the output is a bit confusing, lets say in case of multiple failures, the dict sent to CLI will be like this right:

```
[
  {
    "msg": "Failed to apply export: export FSAL user_id must be 'nfs.my-nfs.1'",
    "state": "error"
  }
],
[
  {
    "msg": "Failed to apply export: Export ID changed, Cannot update export'",
    "state": "error"
  }
]
```
we don't know which export failed because of the unknown/invalid user and which one is the export where it's ID was tried to change. I think this dict needs addition of an identifier like an export's path or pseudo or ID, like this:

```
[
  {
    "Export ID": 3,
    "msg": "Failed to apply export: export FSAL user_id must be 'nfs.my-nfs.1'",
    "state": "error"
  }
],
[
  {
    "Export ID": 5,
    "msg": "Failed to apply export: Export ID changed, Cannot update export'",
    "state": "error"
  }
]
```
this way its more meaningful, also i got an idea, why not added the return code to the dict itself? like

```
[
  {
    "Export ID": 3,
    "msg": "Failed to apply export: export FSAL user_id must be 'nfs.my-nfs.1'",
    "state": "error",
    "rcode": 22
  }
],
[
  {
    "Export ID": 5,
    "msg": "Failed to apply export: Export ID changed, Cannot update export'",
    "state": "error",
    "rcode": 22
  }
]
```

and for overall errno, instead of EIO, EPERM/EAGAIN/EACCES suits much better

**Comment by dparmar18** [comment]
> The idea behind creating a specialized AppliedExportResults class is to gather the results from each individual update and report on them. There can be all successes, all errors, or a mix of successes and errors. As you point out the new(er) output is not as neat when there's only one input - and therefore only one item to report on.

@phlogistonjohn 
By this i was assuming that for every export change, there will be an entry in the dict whether it's a success or an error. I tried it with two export blocks in a conf file with both having some error, IIUC i should get two key-val pairs inside the dict for both the exports like

```
[
  {
    "msg": "Failed to apply export: export FSAL user_id must be 'nfs.my-nfs.1'",
    "state": "error"
  }
],
[
  {
    "msg": "Failed to apply export: Export ID changed, Cannot update export'",
    "state": "error"
  }
]
```

but it gave me just one:
```
$ ceph nfs export apply my-nfs -i export.conf 
[
  {
    "msg": "Failed to apply export: Export ID changed, Cannot update export",
    "state": "error"
  }
]
```

this means sending status of every export doesn't happen. It just reports a single error and throws me to the CLI. So I'm now confused whether having this setup actually serves our purpose. Do correct me if i'm misinterpreting anything here.

**Comment by dparmar18** [comment]
i just checked, all of the test cases present in `qa/tasks/cephfs/test_nfs.py` that tests `nfs export apply` interface uses uses only one export, we never actually have tested multiple export block changes 0_o

**Comment by phlogistonjohn** [comment]
> > The idea behind creating a specialized AppliedExportResults class is to gather the results from each individual update and report on them. There can be all successes, all errors, or a mix of successes and errors. As you point out the new(er) output is not as neat when there's only one input - and therefore only one item to report on.
> 
> @phlogistonjohn By this i was assuming that for every export change, there will be a dict whether it's a success or an error. I tried it with two export blocks in a conf file with both having some error, IIUC i should get two dicts like
> 
> ```
> [
>   {
>     "msg": "Failed to apply export: export FSAL user_id must be 'nfs.my-nfs.1'",
>     "state": "error"
>   },
>  {
>     "msg": "Failed to apply export: export FSAL user_id must be 'nfs.my-nfs.2'",
>     "state": "error"
>  }
> ]
> ```
> 

That's what I'd expect too.


> but it gave me just one:
> 
> ```
> $ ceph nfs export apply my-nfs -i export.conf 
> [
>   {
>     "msg": "Failed to apply export: export FSAL user_id must be 'nfs.my-nfs.2'",
>     "state": "error"
>   }
> ]
> ```
> 

Hmmm.....

> this is the export.conf content:
> 
> ```
> { 
>  "export_id": 1,
>   "path": "/non_existent_path",
>   "cluster_id": "my-nfs",
>   "pseudo": "/ceph",
>   "access_type": "RW",
>   "squash": "none",
>   "security_label": true,
>   "protocols": [
>     4
>   ],
>   "transports": [
>     "TCP" 
>   ],
>   "fsal": {
>     "name": "CEPH",
>     "user_id": "nfs.dddnfs-cephfs.1",
>     "fs_name": "myfs" 
>   },
>   "clients": [],
>  "export_id": 2,
>   "path": "/non_existent_path1",
>   "cluster_id": "my-nfs",
>   "pseudo": "/ceph1",
>   "access_type": "RW",
>   "squash": "none",
>   "security_label": true,
>   "protocols": [
>     4
>   ],
>   "transports": [
>     "TCP" 
>   ],
>   "fsal": {
>     "name": "CEPH",
>     "user_id": "nfs.nfsddd-cephfs.2",
>     "fs_name": "myfs" 
>   },
>   "clients": []
> }
> ```

The json above looks a little funny to me. Maybe it's a copy and paste thing but I don't see a terminating curly brace for export_id 1 above export_id 2

If I run the above through JQ it reports:
```
$ jq < x
{
  "export_id": 2,
  "path": "/non_existent_path1",
  "cluster_id": "my-nfs",
  "pseudo": "/ceph1",
  "access_type": "RW",
  "squash": "none",
  "security_label": true,
  "protocols": [
    4
  ],
  "transports": [
    "TCP"
  ],
  "fsal": {
    "name": "CEPH",
    "user_id": "nfs.nfsddd-cephfs.2",
    "fs_name": "myfs"
  },
  "clients": []
}
```

> 
> this means sending status of every export doesn't happen. It just reports a single error(that too is quite confusing to understand) and throws me to the CLI. So I'm now unsure whether having this setup actually serves our purpose. Do correct me if i'm misinterpreting anything here.

Based on the above I think there's a "bug" in your test json. Let me know if it's not clear why. Also, let me know if you want assistance generating suitable test inputs.

**Comment by dparmar18** [comment]
> Based on the above I think there's a "bug" in your test json. Let me know if it's not clear why. Also, let me know if you want assistance generating suitable test inputs.

My bad, i missed adding those export blocks within an array; now with correct cfg file, it is as per the expectation.

With this, there's still one more thing that is pending https://github.com/ceph/ceph/pull/53140#issuecomment-1692446244

It's cumbersome to know which error is for which export in case there are excessive amount of exports to be updated. Thus the above proposed change might be helpful

**Comment by dparmar18** [comment]
@phlogistonjohn check this out https://github.com/ceph/ceph/pull/53177

**Comment by dparmar18** [comment]
Since it is necessary to send status of every export update regardless of success or failure, it is necessary to send dict for every export update.

Generalised errno being EIO is still something I feel can be changed to EINVAL indicating that the json/conf file contains invalid entries, I'll try to push that change in https://github.com/ceph/ceph/pull/53177 and let's switch these conversations to that PR.

**Pull request closed without merging**
