### PR TITLE
Wip switch to breathe

### PR DESCRIPTION
**Pull request by tchaikov**
see https://github.com/ceph/asphyxiate/pull/2 for the context and background of this change.

### CODE REVIEW

**Comment by tchaikov** [comment]
was #4084 , now targeting master. and pushing to a ceph/ceph branch to validate if it works.

**Comment by tchaikov** [comment]
sphinx ran out of the memory
```
 preparing documents... done
writing output... [ 0%] api/index
writing output... [ 0%] api/libcephfs-java
writing output... [ 1%] architecture

Exception occurred:
File "/usr/lib/python2.7/subprocess.py", line 1133, in _execute_child
self.pid = os.fork()

    Error: OS [Errno 12] Cannot allocate memory 
```
see http://gitbuilder.sepia.ceph.com/gitbuilder-doc/log.cgi?log=754546c9e04a53e2b347c503eaf3f3f06fc9476d .

**Comment by dmick** [comment]
sigh.  oh, good.

**Comment by tchaikov** [comment]
@dachary is there anything we can do to offer the gitbuilder more memory, is it a limit of the process, user or the (virtual) machine?

**Comment by dachary** [comment]
@dmick "oh, good" or "oh, god!" ? ;-)

**Comment by dachary** [comment]
@tchaikov I'll explore how to increase the memory of the doc gitbuilder machine.

**Comment by dachary** [comment]
@dmick I looked at the infrastructure doc but could not find a hint. I added a question in case someone know the answer. Meanwhile we'll have to wait before this can be merged. 

@tchaikov I think to remember there are a massive amount of files being processed by sphinx that do not contain any useful information. For instance almost all Ceph sources are scanned by doxygen where only a tiny part is going to be published. Could it be the reason for the massive memory usage ?

**Comment by tchaikov** [comment]
@dachary could be, we are only referencing no more than three of the doxygen generated files. maybe i can whitelist them! will try it out tomorrow.

**Comment by tchaikov** [comment]
@dachary i made it! see http://gitbuilder.sepia.ceph.com/gitbuilder-doc/log.cgi?log=8a3ca0075b3523ff8100ae4204c484ee38496922

as the next step, i will move the generated man pages out of the git repo after making sure that the rst is in sync with them. maybe we can include them in the released tarball to avoid bloating the `Build-Depends` section?

**Comment by dachary** [comment]
> we can include them in the released tarball to avoid bloating the Build-Depends section

If I'm not mistaken, as of now, the recommended way to make a tarbal is to run install-deps.sh + autogen.sh + configure + make dist. Since install-deps.sh uses Build-Depends/Buid-Requires, I'm not sure this will save something. Maybe I misunderstand what you suggest ?

**Comment by dachary** [comment]
I think
<pre>
Fixes: 6115,11077
</pre>
need to be
<pre>
Fixes: #6115
Fixes: #11077
</pre>
because redmine is very picky. I'm not even sure if two lines will be interpretted correctly. I would be very surprised if **6115,11077** does what you expect it to do.

**Comment by tchaikov** [comment]
> If I'm not mistaken, as of now, the recommended way to make a tarbal is to run install-deps.sh + autogen.sh + configure + make dist. Since install-deps.sh uses Build-Depends/Buid-Requires, I'm not sure this will save something. Maybe I misunderstand what you suggest ?

ahh, i see. then we need to make the sphinx an additional dependency when preparing the tar ball.

**Pull request merged**
