### PR TITLE
mgr: remove default cert; disable both restful and dashboard by default

### PR DESCRIPTION
**Pull request by liewegas**
- no auto-cert creation by package
- both restful and dashboard lose the default addr, so they will not start if the admin hasn't explicitly set server_addr

I don't think we want to enable either of these by default.  And once the admin has to type in or cut&paste a command to turn on restful, they can also paste another 3 lines to generate and insert a self-signed cert (if they choose).

### CODE REVIEW

**Comment by liewegas** [comment]
http://tracker.ceph.com/issues/20239

**Comment by liewegas** [comment]
retest this please

**Comment by tchaikov** [comment]
retest this please.

**Comment by b-ranto** [comment]
a couple of things:
- won't this break the rados test suite now that the restful test case is part of it?
- if we are going to expect admins to do most of this on their own can we make it part of the ~same interface and use something like `ceph tell mgr restful_generate_cert/restful_set_cert` or even a do-it-all `ceph tell mgr restful_init`

**Comment by liewegas** [comment]
Sigh, yeah, this will break the test. It needs to generate the cert (or we need to do that in ceph.py).

I like 'ceph tell mgr restful generate-cert'.  Did we come to a conclusion about whether we can use the internal helper function to generate an anon cert?  IIRC there was a question about whether the dependencies were present..

There is no auth on dashboard so we can't enable it by default.  And the thinking with restful is that in order to use it properly the admin should make some conscious decision about the cert and bind address, which means there is some manual setup anyway and no need to auto-gen a cert that is probably wrong anyway.  The 'generate-cert' command is nice because it's easy and an active step taken by the admin here.

**Comment by liewegas** [comment]
@b-ranto did we come to a conclusion about the implicitly python openssl dependency?

**Comment by b-ranto** [comment]
@liewegas It should be ok to use it for certificate generation (both implicitly and directly). AFAIK, only the certificate verification part of the library was deprecated in favour of the standard `ssl` python library.

**Comment by liewegas** [comment]
@b-ranto in that case, what do you think of a 'ceph tell mgr restful create-self-signed-cert' command on top of these patches?

**Comment by b-ranto** [comment]
@liewegas yep, something like that would make sense, we could use the create_cert function as removed by commit https://github.com/ceph/ceph/pull/14457/commits/f59e9bf0bbda870311c608474b9aad63f4323c43#diff-1f1c563ffb053d5d63ef3c18a00af2a9L346 for that (we can just remove the C, ST, L metadata to create a more generic certificate).

**Comment by liewegas** [comment]
@jcsp suggestions on how to make the module be able to restart itself?

**Comment by jcsp** [comment]
@liewegas module should block itself in serve() if it's waiting to be configured, e.g. with a python threading.event() object.  If it needs to restart after starting that's (hopefully) something that web framework of choice should handle.

**Comment by b-ranto** [comment]
@liewegas I am thinking we can make `_serve` method reloadable in `serve` method via something like this (not tested)
```
def serve(self):
  while True:
    try:
      self._serve()
      break
    except:
      self.log.error(str(traceback.format_exc()))
```

With that we should be able to reload the server by throwing an exception while we would still be able to finish cleanly on a regular shutdown.

**Comment by jcsp** [comment]
If you wanted to use an exception for restarting (I don't know if this web framework passes exceptions from workers up to the original caller?) then it should definitely be a specific RestartMePlease class, rather than restarting the server on any exception.  If we restarted on any exception then something that e.g. couldn't bind a network port would sit there spinning and spamming the log with the same exception.

**Comment by jcsp** [comment]
I also don't know where the exception would come from if we were e.g. restarting the server because of a config change -- surely it wouldn't come from inside the _serve method?

**Comment by b-ranto** [comment]
I was playing with it a bit and I was able to implement a restart method that is fairly safe in wip-commit https://github.com/b-ranto/ceph/commit/2c8727f3859b91f2f6fa42edd92a6ea5d6580b16

The thing is it won't start the daemon if it was not running (or failed) before. That would require some more changes to the mechanism.

**Comment by b-ranto** [comment]
This wip-commit should cover even the case when it failed to start https://github.com/b-ranto/ceph/commit/d9fcc5fab92b1f522f64552532c06677f5676c9c

The module keeps running in polling mode (once a second) until something tells it to try to start again. create-self-signed cert sends a signal to try to boot again. The shutdown method sends a signal to go down.

**Comment by jcsp** [comment]
I've added comments to https://github.com/b-ranto/ceph/commit/d9fcc5fab92b1f522f64552532c06677f5676c9c

**Comment by b-ranto** [comment]
This should cover the comments https://github.com/b-ranto/ceph/commit/81e05dfa48622afff3af06a3114f7e1e456e75f1

**Comment by liewegas** [comment]
@b-ranto ok, closer, but now since the cert create happens quickly i get a 'Address already in use' error.  Need to add the OS_REUSEADDR option to the socket, but I'm having a hard time seeing how that should be done with make_server()....

**Comment by b-ranto** [comment]
@liewegas I was hitting the same error until I added the `self.server.socket.close()` call.

Did you by any chance hit this when you hit an exception in the _serve method? That would explain it and in that case we should move the `self.server.socket.close()` call outside the try: statement in the `serve` method.

**Comment by liewegas** [comment]
didn't work :/

**Comment by b-ranto** [comment]
Hmm, I am reading

https://engineering.imvu.com/2014/03/06/charming-python-how-to-actually-close-a-socket-by-calling-shutdown-before-calling-close/

and it looks like we should probably call `server.socket.shutdown()` instead of `server.socket.close()`. Any help when doing that?

**Comment by b-ranto** [comment]
This seemed to work best for me https://github.com/b-ranto/ceph/commit/c8b65ff4b1f7f274d7799e1b4c42318eea25c1a5

Can you retry?

**Comment by liewegas** [comment]
Okay, fixed.  I worked around it by not trying to make_server when there is no cert.  The root of the problem seems to be that make_server binds to the socket before setting up ssl, and then bails out.  But at that point it's too late... it is either not tearing down the socket properly or we just have to use SO_REUSEADDR to rebind to it, and that isn't that easy.

Anyway, this is more graceful anyway!

**Comment by liewegas** [comment]
http://pulpito.ceph.com/sage-2017-06-22_01:17:23-rados-wip-sage-testing-distro-basic-smithi/

**Pull request merged**
