### PR TITLE
mds: use LogSegment dump for debugging

### PR DESCRIPTION
**Pull request by batrick**
Looks like:

```
./remote/smithi159/log/dc13d9da-5179-11ee-9ab7-7b867c8bd7da/ceph-mds.b.log.gz:2023-09-12T14:47:52.937+0000 7fddc11e9700  5 mds.0.log try_expire expiring LogSegment(2/0x400030 events=34)
./remote/smithi159/log/dc13d9da-5179-11ee-9ab7-7b867c8bd7da/ceph-mds.b.log.gz:2023-09-12T14:47:52.937+0000 7fddc11e9700 20 mds.0.log _trim_expired_segments: examining LogSegment(1/0x400000 events=1)
./remote/smithi159/log/dc13d9da-5179-11ee-9ab7-7b867c8bd7da/ceph-mds.b.log.gz:2023-09-12T14:47:52.937+0000 7fddc11e9700 10 mds.0.log _trim_expired_segments: maybe expiring LogSegment(1/0x400000 events=1)
./remote/smithi159/log/dc13d9da-5179-11ee-9ab7-7b867c8bd7da/ceph-mds.b.log.gz:2023-09-12T14:47:52.937+0000 7fddc11e9700 20 mds.0.log _trim_expired_segments: examining LogSegment(2/0x400030 events=34)
./remote/smithi159/log/dc13d9da-5179-11ee-9ab7-7b867c8bd7da/ceph-mds.b.log.gz:2023-09-12T14:47:52.937+0000 7fddc11e9700 10 mds.0.log _trim_expired_segments: expiring up to this major segment seq=2
./remote/smithi159/log/dc13d9da-5179-11ee-9ab7-7b867c8bd7da/ceph-mds.b.log.gz:2023-09-12T14:47:52.937+0000 7fddc11e9700 20 mds.0.log _trim_expired_segments: expiring LogSegment(1/0x400000 events=1)
./remote/smithi159/log/dc13d9da-5179-11ee-9ab7-7b867c8bd7da/ceph-mds.b.log.gz:2023-09-12T14:47:52.937+0000 7fddc11e9700 10 mds.0.log _trim_expired_segments waiting for expiry LogSegment(2/0x400030 events=34)
./remote/smithi159/log/dc13d9da-5179-11ee-9ab7-7b867c8bd7da/ceph-mds.b.log.gz:2023-09-12T14:47:52.938+0000 7fddc11e9700 20 mds.0.log _trim_expired_segments: examining LogSegment(2/0x400030 events=34)
./remote/smithi159/log/dc13d9da-5179-11ee-9ab7-7b867c8bd7da/ceph-mds.b.log.gz:2023-09-12T14:47:52.938+0000 7fddc11e9700 10 mds.0.log _trim_expired_segments waiting for expiry LogSegment(2/0x400030 events=34)
```

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [x] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by batrick** [comment]
https://tracker.ceph.com/projects/cephfs/wiki/Main#2023-Sep-12

ready for merge

**Comment by batrick** [comment]
@ceph/cephfs please review.

**Review by vshankar — APPROVED** [review]
Handy!

**Review by leonid-s-usov — APPROVED** [review]
I approve :D
Some of the changes I've also implemented on my side, but mostly not. Will be happy to rebase over this once it's merged

**Pull request merged**
