### PR TITLE
cmake: add missing RadosDump.cc, RadosImport.cc and PoolDump.cc

### PR DESCRIPTION
**Pull request by oritwas**
Signed-off-by: Orit Wasserman <owasserm@redhat.com>

### CODE REVIEW

**Comment by tchaikov** [comment]
@oritwas i am testing your patch.

BTW, could you advice me how you run cmake in ceph source tree? i was troubled by http://tracker.ceph.com/issues/10999 couple months ago. i guess it's not just me. but not sure, though.

**Comment by oritwas** [comment]
Maybe it is a configuration problem ? I have gcc 4.9.2 and cmake works for me.
I run configure with --without-lttng (could not make it work otherwise).

**Comment by tchaikov** [comment]
@oritwas probably. i was using gcc 4.9.2. now i am using 5.0. will try again without out-of-source build.

without this patch
---
```
Scanning dependencies of target rados
Linking CXX executable rados
CMakeFiles/rados.dir/tools/rados/rados.cc.o: In function `rados_tool_common(std::map<std::string, std::string, std::less<std::string>, std::allocator<std::pair<std::string const, std::string> > > const&, std::vector<char const*, std::allocator<char const*> >&)':
/home/kefu/dev/ceph/src/tools/rados/rados.cc:2645: undefined reference to `PoolDump::dump(librados::IoCtx*)'
/home/kefu/dev/ceph/src/tools/rados/rados.cc:2690: undefined reference to `RadosImport::import(librados::IoCtx&, bool)'
collect2: error: ld returned 1 exit status
src/CMakeFiles/rados.dir/build.make:123: recipe for target 'src/rados' failed
make[2]: *** [src/rados] Error 1
CMakeFiles/Makefile2:1466: recipe for target 'src/CMakeFiles/rados.dir/all' failed
make[1]: *** [src/CMakeFiles/rados.dir/all] Error 2
Makefile:116: recipe for target 'all' failed
make: *** [all] Error 2
```

with this patch
---
```
Scanning dependencies of target rados
Linking CXX executable rados
....
~/dev/ceph/build $ src/rados ### i am building in ceph/build
2015-06-16 00:19:21.792577 7f0426df77c0 -1 did not load config file, using default settings.
rados: you must give an action. Try --help
```

**Comment by jcsp** [comment]
@oritwas thanks for adding these, I hadn't realised we were maintaining the CMakeLists.txt everywhere now, will bear that in mind.

**Pull request merged**
