### PR TITLE
qa: remove all bluestore signatures on devices

### PR DESCRIPTION
**Pull request by guits**
We must ensure BlueStore signatures are removed altogether since multiple BlueStore label replications have been introduced.

Fixes: https://tracker.ceph.com/issues/68171

### CODE REVIEW

**Comment by guits** [comment]
jenkins test api

**Comment by guits** [comment]
jenkins test api

**Comment by adk3798** [comment]
jenkins test windows

**Review by adk3798 — APPROVED** [review]

**Comment by guits** [comment]
https://pulpito.ceph.com/gabrioux-2024-09-21_11:23:40-orch:cephadm-wip-guits-main-2024-09-21-0842-distro-default-smithi/

**Comment by guits** [comment]
jenkins test windows

**Comment by guits** [comment]
jenkins test windows

**Comment by guits** [comment]
jenkins test windows

**Pull request merged**
