### PR TITLE
Zlib compression plugin

### PR DESCRIPTION
**Pull request by Ved-vampir**
Add new plugin to compressor system

### CODE REVIEW

**Comment by liewegas** [comment]
compressor/zlib/CompressionPluginZlib.cc: In member function 'virtual int CompressionPluginZlib::factory(CompressorRef*, std::ostream*)':
error: compressor/zlib/CompressionPluginZlib.cc:35:56: cannot allocate an object of abstract type 'CompressionZlib'
CompressionZlib *interface = new CompressionZlib();
^
In file included from compressor/zlib/CompressionPluginZlib.cc:19:0:
compressor/zlib/CompressionZlib.h:25:7: note: because the following virtual functions are pure within 'CompressionZlib':
class CompressionZlib : public Compressor {
^
In file included from ./compressor/CompressionPlugin.h:23:0,
from compressor/zlib/CompressionPluginZlib.cc:18:
./compressor/Compressor.h:28:15: note: virtual int Compressor::compress(const bufferlist&, ceph::bufferlist&)
virtual int compress(const bufferlist &in, bufferlist &out) = 0;
^
./compressor/Compressor.h:29:15: note: virtual int Compressor::decompress(const bufferlist&, ceph::bufferlist&)
virtual int decompress(const bufferlist &in, bufferlist &out) = 0;
^

**Comment by Ved-vampir** [comment]
@liewegas  ./run-make-check.sh's output is successful localy, is default check scripts use another test?

**Comment by liewegas** [comment]
hmm, should be the same.  maybe there was something in master that broke it, rebuilding here...

**Comment by liewegas** [comment]
I get the same build error with master merged with this branch on my dev machine.

**Comment by Ved-vampir** [comment]
@liewegas Thanks for tip, it really was a conflict with last master

**Pull request merged**
