### PR TITLE
mon: ignore messages from disconnected clients; clean up session checks

### PR DESCRIPTION
**Pull request by liewegas**

### CODE REVIEW

**Comment by liewegas** [comment]
@tchaikov Mind taking a look?

**Comment by tchaikov** [comment]
@liewegas , generally looks good, will look at it closer tomorrow morning.

**Comment by liewegas** [comment]
@jecluis ended up doing a bunch of cleanup here.  mind taking a quick look?

**Comment by liewegas** [comment]
passed wip-sage-testing.  I think this needs another review, though!  @jecluis or @tchaikov ?

**Comment by jecluis** [comment]
This all looks good to me. I'm just waiting on this branch to build to test the last patch (mon: allow ping through...) -- something is not feeling right, but it maybe nothing...

**Comment by jecluis** [comment]
Nevermind. It works.

LGTM

**Pull request merged**
