### PR TITLE
quincy: Cephadm: Allow multiple virtual IP addresses for keepalived and haproxy

### PR DESCRIPTION
**Pull request by adk3798**
Backport of https://github.com/ceph/ceph/pull/47513

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by tchaikov** [comment]
jenkins test make check

**Review by anthonyeleven — APPROVED** [review]
docs lgtm

**Comment by adk3798** [comment]
jenkins retest this please

**Comment by adk3798** [comment]
https://pulpito.ceph.com/adking-2022-09-03_23:13:39-orch:cephadm-wip-adk3-testing-2022-09-03-1327-quincy-distro-default-smithi/

Failure tracked by

- https://tracker.ceph.com/issues/55347
- https://tracker.ceph.com/issues/55319
- an instance of timing out waiting for OSDs to be up, which I suspect is also https://tracker.ceph.com/issues/55319

The 2nd and 3rd failure are uncommon transient but known failures while the first is currently quite common

ran all 3 failed tests 3 more times, only the first failure https://tracker.ceph.com/issues/55347 popped up again, everything else passed. https://pulpito.ceph.com/adking-2022-09-04_03:58:20-orch:cephadm-wip-adk3-testing-2022-09-03-1327-quincy-distro-default-smithi/

Overall, no new failures being caused by PRs in the run

**Comment by adk3798** [comment]
jenkins test make check

**Review by anthonyeleven — APPROVED** [review]

**Pull request merged**
