### PR TITLE
msg/async: fix stuck stateful sessions

### PR DESCRIPTION
**Pull request by nmgyeyun**
http://tracker.ceph.com/issues/37499

### CODE REVIEW

**Comment by nmgyeyun** [comment]
@yuyuyu101

**Comment by nmgyeyun** [comment]
@yuyuyu101 The timer Where should I put it

**Comment by yuyuyu101** [comment]
what's the root cause of state stucking?

**Comment by nmgyeyun** [comment]
> what's the root cause of state stucking?

for example: client connect to Server
Client in state CONNECTING, send "CEPH_BANNER", tcp socket send "CEPH_BANNER" success and  recv TCP ACK, then Client will wait for "server_banner". if B poweroff or rbooting,  the connection is broken, but Client don't kown peer is dead.

**Comment by yuyuyu101** [comment]
why existing tick() can't play the same role?

**Comment by nmgyeyun** [comment]
> why existing tick() can't play the same role?

tick() do this after state OPENED, before OPENED nothing do this.

**Comment by nmgyeyun** [comment]
> why it will stuck? tcp will timeout then trigger fault

tcp Client send packet, and tcp stack recv the TCP ACK packet from Server, then server poweroff or rebooting without send TCP FIN. 
tcp keepalive default is off, event if tcp keepalive is on, default time is 7200 seconds. 
Client kown nothing about peer is down.  

net.ipv4.tcp_keepalive_intvl = 75
net.ipv4.tcp_keepalive_probes = 9
net.ipv4.tcp_keepalive_time = 7200

**Comment by nmgyeyun** [comment]
> > what's the root cause of state stucking?
> 
> for example: Client connect to Server
> Client in state CONNECTING, send "CEPH_BANNER", tcp socket send "CEPH_BANNER" success and recv TCP ACK, then Client will wait for "server_banner". if Server poweroff or rebooting, the connection is broken, but Client don't kown peer is dead. Client may need something to determine whether the connection is still up and running or if it has broken.

In this sate, Client only wait for recv. if Client send packet out, will trigger tcp timeout or recive RST from peer, then trigger fault.

**Comment by yuyuyu101** [comment]
but what benefit can we get from  this change? wait for the network back or not?

**Comment by yuyuyu101** [comment]
actually I hope upper logic can handle this timeout and make it configurable according to the scene.

**Comment by liewegas** [comment]
needs rebase

**Comment by xiexingguo** [comment]
@nmgyeyun We've encountered the same issue and I think this is the right cure.

Can you rebase?  I'd be love to schedule QA and do some local testing.

**Comment by xiexingguo** [comment]
@nmgyeyun Please drop the merge commit as you are going to rebase.

Thanks!

**Comment by xiexingguo** [comment]
Well, on second thought instead of doing this,  may be we should override default TCP_USER_TIMEOUT[1] by a __very carefully__ chosen value since we could be stuck at any stage?

@yuyuyu101 @liewegas @rjfd  What do you think?
 
---
http://man7.org/linux/man-pages/man7/tcp.7.html

**Comment by liewegas** [comment]
I'm confused how this relates to
```
    inactive_timeout_us(cct->_conf->ms_tcp_read_timeout*1000*1000),
```
...which i thought imposed an overall 15 min default timeout?

**Comment by xiexingguo** [comment]
> I'm confused how this relates to
>```
>    inactive_timeout_us(cct->_conf->ms_tcp_read_timeout*1000*1000),
>```
>...which i thought imposed an overall 15 min default timeout?

Nope. The default 15 min timeout implies we should tear down the connection which has no read/write activities at both sides (namely connection is __idle__), whereas the issue we discussed here is that a connection could be stuck at a specific STAGE forever during connecting, e.g., because we encounter some host, network or switch problems.

By manually creating some loop back connections on the switches of our test cluster, we can almost 100% reproduce http://tracker.ceph.com/issues/37499

By the way, I think the ms_tcp_read_timeout is mis-named. Maybe we should rename it to `ms_connection_idle_timeout`, which is less confusing...

**Comment by xiexingguo** [comment]
Replaced by https://github.com/ceph/ceph/pull/27337

**Pull request closed without merging**
