### PR TITLE
mgr/cephadm: add commands to set services to managed/unmanaged

### PR DESCRIPTION
**Pull request by adk3798**
Fixes: https://tracker.ceph.com/issues/58713

Signed-off-by: Adam King <adking@redhat.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [x] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [x] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [x] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [x] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Review by anthonyeleven — APPROVED** [review]
docs lgtm, no comment re code

**Review by phlogistonjohn — APPROVED** [review]
Looks OK to me.

**Review by rkachach — APPROVED** [review]
LGTM

**Comment by adk3798** [comment]
https://pulpito.ceph.com/adking-2023-03-06_16:09:09-orch:cephadm-wip-adk-testing-2023-03-04-1231-distro-default-smithi/

Failed/dead jobs reruns: https://pulpito.ceph.com/adking-2023-03-06_21:04:02-orch:cephadm-wip-adk-testing-2023-03-04-1231-distro-default-smithi/

After reruns, 6 failed, 2 dead jobs:

- 2 dead jobs were teuthology/infra issues (`Could not get lock /var/lib/dpkg/lock-frontend`, `SSH connection to smithi038 was lost`)
- 1 job failed installing a kernel `[Errno 2] No such file or directory: '/var/cache/dnf/CentOS-BaseOS-7c3d8b2bb640713c/packages/kernel-4.18.0-448.el8.x86_64.rpm'` unrelated to our tests
- 2 instances of https://tracker.ceph.com/issues/58535
- 3 jobs failed due to changes made to `ceph nfs cluster create` command in another PR in the run

Overall, should only block merging for PRs related to nfs

**Pull request merged**
