### PR TITLE
QatAccel: account for recent QATzip API change

### PR DESCRIPTION
**Pull request by tj90241**
Upstream change QATAPP-26616 changed the API extensively to allow for different compression modes.
    
This commit introduces a small fix so that the QatAccel component builds against both new and old versions of QATzip, without adding support for the newer compression modes.

Signed-off-by: Tyler J. Stachecki <stachecki.tyler@gmail.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by tj90241** [comment]
I recognize this may not be the best way to fix this quite yet, but wanted to get a PR/tracker up so others are aware.

cc @hualongfeng @majianpeng

**Comment by tj90241** [comment]
Sorry - I don't mean to abandon this PR... I've mostly goofed around with QAT in my spare time as a hobby of sorts.

I can try to pick this back up if there's genuine interest in getting it fixed up, but TBH working with QAT in Ceph has a been a bit of an exercise in frustration. I still have not been able to get this to work with RBD workloads, so as-is this commit was effectively compile tested and nothing more.

**Comment by mattbenjamin** [comment]
@tj90241 @rzarzynski there is interest from my team in the changes in this PR
@mkogan1 ^^

**Comment by rzarzynski** [comment]
IIRC Adam Kupczyk was looking in this area for the sake of BlueStore's compression optimization. Looping.

CC: @aclamk.

**Comment by tj90241** [comment]
Also be curious to know if anyone felt it was improper to just drop the old version of the API outright so as to get rid of the macros.

**Comment by mattbenjamin** [comment]
@mkogan1 @cbodley can we also review this?

**Comment by mkogan1** [comment]
@tj90241 attempted to cherry-pick and build over build current _main_, conflict not trivial, may kindly ask to rebase please

**Comment by tj90241** [comment]
> @tj90241 attempted to cherry-pick and build over build current _main_, conflict not trivial, may kindly ask to rebase please

Sure, give me a couple days/this weekend and I'll push a rebased PR.

**Comment by tj90241** [comment]
Hi, this is taking a bit longer than expected to fix.

The new API change also seems to require changes to other parts of the code, as I get this when I boot up:
```
2024-01-28T21:47:55.374+0000 7f3b127e96c0  1 QatAccel: Error userStartMultiProcess-1switch to SW if permitted
```

Still working on it.

**Comment by tj90241** [comment]
Big caveat: testing was performed on Intel Atom C3xxx SoC with integrated QAT as part of the SoC. YMMV with beefier cores and QAT hardware.

That being said, it seems to result in a tremendous hit to IOPS at the moment. QAT definitely saves on CPU cycles if that's what you are after, but the 1M block write results... I really hoped for better, SoC version or not.

QAT enabled, compression enabled, 8k randwrite, 32 concurrent I/Os:
```
Average IOPS:           6664
Stddev IOPS:            48.5777
Average Latency(s):     0.00479813
Stddev Latency(s):      0.00147389
```

QAT disabled, compression enabled, 8k randwrite, 32 concurrent I/Os (mostly to show that it's working):
```
Average IOPS:           7109
Stddev IOPS:            43.0121
Average Latency(s):     0.00449819
Stddev Latency(s):      0.00110598
```

QAT disabled, compression disabled, 8k randwrite, 32 concurrent I/Os:
```
Average IOPS:           8538
Stddev IOPS:            55.4217
Average Latency(s):     0.00374574
Stddev Latency(s):      0.000804018
```
```
QAT enabled, compression enabled, 1M block writes, 32 concurrent I/Os:

Average IOPS:           207
Stddev IOPS:            9.33333
Average Latency(s):     0.152771
Stddev Latency(s):      0.1415
```

QAT disabled, compression enabled, 1M block writes, 32 concurrent I/Os:
```
Average IOPS:           421
Stddev IOPS:            10.3328
Average Latency(s):     0.0758227
Stddev Latency(s):      0.0324589
```

QAT disabled, compression disabled, 1M block writes, 32 concurrent I/Os:
```
Average IOPS:           608
Stddev IOPS:            18.564
Average Latency(s):     0.0525643
Stddev Latency(s):      0.0290951
```

**Comment by tj90241** [comment]
This was fixed here: https://github.com/ceph/ceph/pull/52447

**Pull request closed without merging**
