### PR TITLE
pybind: replace __del__ with __dealloc__ for rbd

### PR DESCRIPTION
**Pull request by jdurgin**
Also update .gitignore so gitbuilders will not fail due to 'added files'

### CODE REVIEW

**Comment by jdurgin** [comment]
@marcan @sileht does this look ok to you? passes test_rbd.py

**Comment by marcan** [comment]
Ha, I had no idea about __dealloc__. Almost seems like cython should complain if there's a __del__ method then. LGTM.

**Comment by jdurgin** [comment]
just discovered it since @sileht fixed the same thing in rados.pyx

**Comment by sileht** [comment]
__del__ is just never called if the class is a "cdef class".

**Pull request merged**
