### PR TITLE
ceph-disk:  support lvm2 volumes

### PR DESCRIPTION
**Pull request by wind0204**
Hi, it's very naive and simple implementation; hope a ceph developer will polish it up a bit.

I still need to do a 'partprobe' and a 'udevadm trigger' on every boot-up so that 1) the device-mapped virtual block devices for the lvm partitions show up and 2) the udev rule populates the directory /dev/disk/by-partuuid which is used by the symbolic link of the filestore journal prepared by ceph-disk.

a related mailing list thread : https://www.mail-archive.com/ceph-users@lists.ceph.com/msg36362.html

Signed-off-by: Gunwoo Gim (a.k.a. Nicho1as) <wind8702@gmail.com>

### CODE REVIEW

**Comment by wind0204** [comment]
I'm afraid to say I just found out after rebooting two osd nodes that the osds don't get up and running by the udev rules in /lib/udev/rules.d/95-ceph-osd.rules; I had to run:

> thename=hdd1 && /usr/sbin/ceph-disk --log-stdout -v trigger /dev/mapper/vg--${thename}-lv--${thename}p1
>  thename=hdd2 && /usr/sbin/ceph-disk --log-stdout -v trigger /dev/mapper/vg--${thename}-lv--${thename}p1
>  thename=hdd3 && /usr/sbin/ceph-disk --log-stdout -v trigger /dev/mapper/vg--${thename}-lv--${thename}p1
>  thename=hdd4 && /usr/sbin/ceph-disk --log-stdout -v trigger /dev/mapper/vg--${thename}-lv--${thename}p1
>  thename=hdd5 && /usr/sbin/ceph-disk --log-stdout -v trigger /dev/mapper/vg--${thename}-lv--${thename}p1
>  thename=hdd6 && /usr/sbin/ceph-disk --log-stdout -v trigger /dev/mapper/vg--${thename}-lv--${thename}p1
>  thename=hdd7 && /usr/sbin/ceph-disk --log-stdout -v trigger /dev/mapper/vg--${thename}-lv--${thename}p1
>  thename=hdd8 && /usr/sbin/ceph-disk --log-stdout -v trigger /dev/mapper/vg--${thename}-lv--${thename}p1
>  thename=hdd9 && /usr/sbin/ceph-disk --log-stdout -v trigger /dev/mapper/vg--${thename}-lv--${thename}p1
>  thename=hdd10 && /usr/sbin/ceph-disk --log-stdout -v trigger /dev/mapper/vg--${thename}-lv--${thename}p1

**Comment by wind0204** [comment]
Just made a mistake, Please let me make a new PR.

**Comment by wind0204** [comment]
I made the second commit a couple of hours ago with error and then I just now forced an update of the second commit for the sake of concise git log. now the problem of the udev rule not being triggered when a ceph-osd lvm2 partition is added is fixed. but the fix I just uploaded is very naive; please check out the message of the commit: https://github.com/ceph/ceph/pull/13994/commits/be63ff637b90cf9544ef48b1ccb6cbd241730978

**Comment by smithfarm** [comment]
Needs rebase

**Comment by dachary** [comment]
would you be so kind as to add integration tests as well to demonstrate it works as expected ? See qa/workunits/ceph-disk. And let me know if you need help with it ;)

**Comment by alfredodeza** [comment]
hey @wind0204 we are going to have a separate tool for deploying OSDs from LVM volumes, ceph-disk is not going to support this.

The documentation is at http://docs.ceph.com/ceph-lvm/master/index.html and we should have a release in the next few months. Let us know if you have any ideas/feedback.

Thank you!

**Pull request closed without merging**
