### PR TITLE
src/crush: extra logging to debug CPU burn in test_with_fork()

### PR DESCRIPTION
**Pull request by ideepika**
related: https://tracker.ceph.com/issues/57782

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by ideepika** [comment]
hey @rzarzynski I added relevant debugging for investigation, but am not able to see `CrustTester` logs when I create pool locally even if debug_crush is set to 20, can you help me understand if I am missing something?

**Comment by rzarzynski** [comment]
If this was a separated app, then adding `--log_to_stderr=true` might help/

**Review by rzarzynski — APPROVED** [review]
LGTM under the assumption the logs finally become visible.

**Comment by ideepika** [comment]
@rzarzynski am able to see logs now.

**Comment by ljflores** [comment]
Rados suit review:

http://pulpito.front.sepia.ceph.com/?branch=wip-yuri4-testing-2022-11-10-1051

Failures, unrelated:
    1. https://tracker.ceph.com/issues/57311
    2. https://tracker.ceph.com/issues/58097
    3. https://tracker.ceph.com/issues/55347
    4. https://tracker.ceph.com/issues/57731
    5. https://tracker.ceph.com/issues/57790
    6. https://tracker.ceph.com/issues/52321
    7. https://tracker.ceph.com/issues/58046
    8. https://tracker.ceph.com/issues/54372
    9. https://tracker.ceph.com/issues/56000
    10. https://tracker.ceph.com/issues/58098

Details:
    1. rook: ensure CRDs are installed first - Ceph - Orchestrator
    2. qa/workunits/post-file.sh: kex_exchange_identification: read: Connection reset by peer - Infrastructure
    3. SELinux Denials during cephadm/workunits/test_cephadm - Ceph - Orchestrator
    4. Problem: package container-selinux conflicts with udica < 0.2.6-1 provided by udica-0.2.4-1 - Infrastructure
    5. Unable to locate package libcephfs1 - Infrastructure
    6. qa/tasks/rook times out: 'check osd count' reached maximum tries (90) after waiting for 900 seconds - Ceph - Orchestrator
    7. qa/workunits/rados/test_librados_build.sh: specify redirect in curl command - Ceph - RADOS
    8. No module named 'tasks' - Infrastructure
    9. task/test_nfs: ERROR: Daemon not found: mds.a.smithi060.ujwxef. See `cephadm ls` - Ceph - Orchestrator
    10. qa/workunits/rados/test_crash.sh: workunit checks for crashes too early - Ceph - RADOS

**Pull request merged**
