### PR TITLE
osd: remove assert when osd io error happens. Instead, report to moni…

### PR DESCRIPTION
**Pull request by liupan1111**
…tor and exit.

Signed-off-by:Pan Liu <pan.liu@istuary.com>

### CODE REVIEW

**Comment by liupan1111** [comment]
When io error happens, assertion will be happened on osd, and it is not proper.

The new behavior is:
1) report error to monitor first.
2) exit.

**Comment by liupan1111** [comment]
@liewegas or @tchaikov , please help take a look.

**Comment by liewegas** [comment]
I don't think an orderly shutdown actually accomplishes anything. Either way, the OSD goes down.  In teh "clean" shutdown case, though, it means that we propogate an EIO error up the call chain where people aren't prepared to deal with it.  

Is there some specific situation you have in mind that you're concerned about?

**Comment by liupan1111** [comment]
@liewegas thanks for comment. My case is:
When our QA hot-pullout a SSD card, assertion happens on a OSD in this SSD. And IOPS drops a lot and return to Normal only when the monitor finds this OSD is down by receiving reports from other OSDs. The customer needs this drop down could be recovered asap. So I replace assertion with:
1) report to monitor first
2) then, exit. EIO still there, but not assertion, but exit.

What is your opinion?

**Comment by liewegas** [comment]
On Tue, 13 Dec 2016, liupan1111 wrote:
> @liewegas thanks for comment. My case is:
> When our QA hot-pullout a SSD card, assertion happens on a OSD in this SSD. And IOPS drops a lot
> and return to Normal only when the monitor finds this OSD is down by receiving reports from other
> OSDs. The customer needs this drop down could be recovered asap. So I replace assertion with:
> 
>  1. report to monitor first
>  2. then, exit. EIO still there, but not assertion, but exit.
> 
> What is your opinion?

This is avoided in kraken because the messenger detects a connection 
refused and we immediately mark down the OSD (vs the case where the OSD is 
just not responding and we have ot wait for the timeout).

**Comment by liupan1111** [comment]
@liewegas Cool, thanks!

**Pull request closed without merging**
