### PR TITLE
jewel: librbd: fail IO request when exclusive lock cannot be obtained

### PR DESCRIPTION
**Pull request by dillaman**
http://tracker.ceph.com/issues/20515

### CODE REVIEW

**Comment by smithfarm** [comment]
@dillaman Can you cherry-pick 98061bb3d7ce6309ddb04ea4d7e9d44a7ecd09c6 into this PR?

**Comment by dillaman** [comment]
@smithfarm done

**Comment by smithfarm** [comment]
@dillaman This passed an rbd suite at http://tracker.ceph.com/issues/20613#note-59 with one failure that passed on rerun.

OK to merge?

**Comment by dillaman** [comment]
@smithfarm lgtm -- I need to investigate that failure since it appears like an OSD crashed and then data became corrupt (unrelated to this PR).

**Pull request merged**
