### PR TITLE
Update get-packages.rst

### PR DESCRIPTION
**Pull request by ibravo**
Updated references to point now to Jewel and el7

### CODE REVIEW

**Comment by theanalyst** [comment]
missing a signed-off-by

**Comment by ibravo** [comment]
Signed-off-by: Ignacio Bravo <ibravo@hotmail.com>

**Comment by liewegas** [comment]
@ibravo can you put the Signed-off-by line in the git commit message please?  (git commit --amend, git push origin -f patch-1)

**Comment by tchaikov** [comment]
@ibravo could you embrace your mail address with brackets ? like
```
Signed-off-by: Ignacio Bravo <ibravo@hotmail.com>
```

**Comment by theanalyst** [comment]
@ibravo ping

**Comment by tchaikov** [comment]
the master has fixed the issues addressed by this PR. closing.

**Pull request closed without merging**
