### PR TITLE
rgw/account: add bucket_quota to RGWAccountInfo

### PR DESCRIPTION
**Pull request by cbodley**
support bucket quotas per account the same way as for user

Fixes: https://tracker.ceph.com/issues/65551

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Review by dang — APPROVED** [review]

**Comment by cbodley** [comment]
passed qa in https://pulpito.ceph.com/cbodley-2024-04-20_23:54:57-rgw-wip-65551-distro-default-smithi/

**Review by BBoozmen — APPROVED** [review]
Looks great. Thank you for the quick turnaround!

Just a nit-pick. Although we don't use `rgw bucket default quota max ...` config knob to set default bucket limits for users, I have looked into it before this fix as a potential workaround.

When a default limit is set in ceph.conf, a new user picks up this limit but a new account doesn't:

```
$ ... user create --display-name=myuserX --uid=myuserX
...
    "bucket_quota": {
        "enabled": true,    <<<
        "check_on_raw": false,
        "max_size": -1,
        "max_size_kb": 0,
        "max_objects": 4 <<< from ceph.conf "rgw bucket default quota max objects = 4"
    }

A new account doesn't pick the default limit:

$ ... account create --account-name=accX
...
    "bucket_quota": {
        "enabled": false,
        "check_on_raw": false,
        "max_size": -1,
        "max_size_kb": 0,
        "max_objects": -1
    },
```

**Comment by cbodley** [comment]
thanks @BBoozmen, default bucket quotas are now applied on account creation. i also added 'account' variants of 
rgw_user_default_quota_max_objects/size for use there too

with config options set thusly:
```
rgw account default quota max size = 1G
rgw bucket default quota max objects = 10
```
i see the following quota settings on account creation:
```
    "quota": {
        "enabled": true,
        "check_on_raw": false,
        "max_size": 1000000000,
        "max_size_kb": 976563,
        "max_objects": -1
    },
    "bucket_quota": {
        "enabled": true,
        "check_on_raw": false,
        "max_size": -1,
        "max_size_kb": 0,
        "max_objects": 10
    },
```

**Comment by cbodley** [comment]
updated branch passed qa with rerun https://pulpito.ceph.com/cbodley-2024-04-23_12:16:49-rgw-wip-65551-distro-default-smithi/

**Pull request merged**
