### PR TITLE
[DNM] luminous: client: fix failure in quota size limitation when using samba

### PR DESCRIPTION
**Pull request by joscollin**
http://tracker.ceph.com/issues/37696

### CODE REVIEW

**Comment by smithfarm** [comment]
```
In file included from /home/jenkins-build/build/workspace/ceph-pull-requests/src/client/Client.cc:83:0:
/home/jenkins-build/build/workspace/ceph-pull-requests/src/client/Client.h:769:16: warning: ‘C_Client_Remount’ is already a friend of ‘Client’ [enabled by default]
   friend class C_Client_Remount;
                ^
/home/jenkins-build/build/workspace/ceph-pull-requests/src/client/Client.cc: In member function ‘int Client::_write(Fh*, int64_t, uint64_t, const char*, const iovec*, int)’:
/home/jenkins-build/build/workspace/ceph-pull-requests/src/client/Client.cc:9395:40: error: ‘quota_roots’ was not declared in this scope
     if (is_quota_bytes_approaching(in, quota_roots)) {
                                        ^
make[3]: *** [src/client/CMakeFiles/client.dir/Client.cc.o] Error 1
```

**Comment by joscollin** [comment]
retest this please

**Comment by joscollin** [comment]
@smithfarm So the reason is with this cherry-pick, the function `is_quota_bytes_approaching(` is getting called and it can't find `quota_roots`.

**Comment by joscollin** [comment]
@smithfarm https://github.com/ceph/ceph/commit/3caa4d233633fb7a67747f2c79c4a0ab89112294#diff-fbcd8ab0dd666648c8e021177ce875d2L8637 shows that there are multiple changes on that code, over a period of time, which were not back-ported.

**Comment by smithfarm** [comment]
@joscollin If the backport is non-trivial, maybe close this PR and mark the tracker "Need more info"?

**Pull request closed without merging**
