### PR TITLE
rgw : add MD5 in forward_request

### PR DESCRIPTION
**Pull request by BryceCao**
Fixes: https://tracker.ceph.com/issues/47869
Signed-off-by: caolei <halei15848934852@163.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Review by ofriedma — APPROVED** [review]
lgtm

**Comment by harishmunjulur** [comment]
[wip-hmunjulu01-testing-2020-11-05-2002](https://trello.com/c/G5VdmXw2/1059-wip-hmunjulu01-testing-2020-11-05-2002)

**Comment by harishmunjulur** [comment]
[wip-hmunjulu01-testing-2020-11-19-1318](https://trello.com/c/n5O8Q7dA/1071-wip-hmunjulu01-testing-2020-11-19-1318)

**Comment by cbodley** [comment]
seeing this crash in testing:
```
2020-11-20T00:16:37.479 INFO:teuthology.orchestra.run.smithi143.stderr: in thread 7f8007f3b0c0 thread_name:radosgw-admin
2020-11-20T00:16:37.479 INFO:teuthology.orchestra.run.smithi143.stderr:
2020-11-20T00:16:37.479 INFO:teuthology.orchestra.run.smithi143.stderr: ceph version 16.0.0-7352-gf65238c8 (f65238c87eab73928db788e2757a6f12f573cad8) pacific (dev)
2020-11-20T00:16:37.479 INFO:teuthology.orchestra.run.smithi143.stderr: 1: /lib/x86_64-linux-gnu/libpthread.so.0(+0x12980) [0x7f7ffd507980]
2020-11-20T00:16:37.480 INFO:teuthology.orchestra.run.smithi143.stderr: 2: gsignal()
2020-11-20T00:16:37.480 INFO:teuthology.orchestra.run.smithi143.stderr: 3: abort()
2020-11-20T00:16:37.480 INFO:teuthology.orchestra.run.smithi143.stderr: 4: /usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0x8c957) [0x7f7ffc921957]
2020-11-20T00:16:37.480 INFO:teuthology.orchestra.run.smithi143.stderr: 5: /usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0x92ae6) [0x7f7ffc927ae6]
2020-11-20T00:16:37.480 INFO:teuthology.orchestra.run.smithi143.stderr: 6: /usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0x92b21) [0x7f7ffc927b21]
2020-11-20T00:16:37.481 INFO:teuthology.orchestra.run.smithi143.stderr: 7: /usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0x92d54) [0x7f7ffc927d54]
2020-11-20T00:16:37.481 INFO:teuthology.orchestra.run.smithi143.stderr: 8: /usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0x8e79f) [0x7f7ffc92379f]
2020-11-20T00:16:37.481 INFO:teuthology.orchestra.run.smithi143.stderr: 9: radosgw-admin(+0x68183e) [0x55ed0e94583e]
2020-11-20T00:16:37.481 INFO:teuthology.orchestra.run.smithi143.stderr: 10: (RGWRESTSimpleRequest::forward_request(RGWAccessKey&, req_info&, unsigned long, ceph::buffer::v15_2_0::list*, ceph::buffer::v15_2_0::list*, optional_yield)+0x3a3) [0x55ed0e94a953]
2020-11-20T00:16:37.481 INFO:teuthology.orchestra.run.smithi143.stderr: 11: (RGWRESTConn::forward(rgw_user const&, req_info&, obj_version*, unsigned long, ceph::buffer::v15_2_0::list*, ceph::buffer::v15_2_0::list*, optional_yield)+0x439) [0x55ed0e952159]
2020-11-20T00:16:37.482 INFO:teuthology.orchestra.run.smithi143.stderr: 12: radosgw-admin(+0x262ba7) [0x55ed0e526ba7]
2020-11-20T00:16:37.482 INFO:teuthology.orchestra.run.smithi143.stderr: 13: radosgw-admin(+0x265d81) [0x55ed0e529d81]
2020-11-20T00:16:37.482 INFO:teuthology.orchestra.run.smithi143.stderr: 14: radosgw-admin(+0x266644) [0x55ed0e52a644]
2020-11-20T00:16:37.482 INFO:teuthology.orchestra.run.smithi143.stderr: 15: main()
2020-11-20T00:16:37.483 INFO:teuthology.orchestra.run.smithi143.stderr: 16: __libc_start_main()
2020-11-20T00:16:37.483 INFO:teuthology.orchestra.run.smithi143.stderr: 17: _start()
```

**Comment by BryceCao** [comment]
@cbodley have any detailed information about which “radosgw-admin ” command? please. Because the card isn't accessed for me.

**Comment by BryceCao** [comment]
@cbodley  the case of not passing MD5 caused null pointer before, I modified the code, add the check of the point.

**Comment by harishmunjulur** [comment]
http://pulpito.ceph.com/hmunjulu-2021-01-22_21:41:59-rgw-wip-hmunjulu01-testing-2021-01-22-0910-distro-basic-smithi/

https://trello.com/c/TdmME0JD

**Pull request merged**
