### PR TITLE
jewel: rgw: 15912 15673 (Fix duplicate tag removal during GC, cls/refcount: store and use list of retired tags)

### PR DESCRIPTION
**Pull request by mattbenjamin**
http://tracker.ceph.com/issues/20719

### CODE REVIEW

**Comment by smithfarm** [comment]
@mattbenjamin Ping, please `git cherry-pick -x` to get the "(cherry picked from . . .)" lines added, or explain in the commit message why cherry-pick is not possible/feasible.

**Comment by smithfarm** [comment]
Jenkins re-test this please

**Comment by smithfarm** [comment]
@mattbenjamin Ping

**Comment by smithfarm** [comment]
@mattbenjamin Please re-do the cherry-picks with `git cherry-pick -x` so we get the "(cherry picked from . . .)" lines. This is a requirement for all backports.

**Comment by smithfarm** [comment]
@mattbenjamin Ping, waiting for action from you

**Comment by smithfarm** [comment]
Already partially backported by https://github.com/ceph/ceph/pull/17166

**Comment by mattbenjamin** [comment]
@smithfarm done?

**Comment by smithfarm** [comment]
Integration testing: http://tracker.ceph.com/issues/21742#note-11

Will post a summary to the PR when the testing is complete.

**Comment by smithfarm** [comment]
This PR passed two RGW runs at http://tracker.ceph.com/issues/21742#note-11

It will be merged soon, unless there any objections.

**Pull request merged**
