### PR TITLE
crush: add a new flag HASHPSPOOL2 for the congruential pps algorithm

### PR DESCRIPTION
**Pull request by yukohe**
We did some optimization for the issue of unbalanced pg distribution among osds in previous work. Please refer to <a href="https://github.com/ceph/ceph/pull/2402">#2402</a> for details.

In this commit, we updated codes for adding a new hashpspool flag HASHPSPOOL2 for the new congruential pps hash algorithm as per previous comments.

### CODE REVIEW

**Comment by yukohe** [comment]
@liewegas hi sage, the patch breakdown has been finished. Thanks!

**Comment by liewegas** [comment]
what do you think about an additional linear parameter to make it a bit more flexible?  if there are parameters that may be useful later i'd like to add them now as these algorithms are very hard to change

**Comment by yukohe** [comment]
@liewegas Yes I think that checking whether the rule applies for linear bucket before calling the adaptive strategy is a good idea. But I'm not sure what the additional linear parameter is used for?

**Comment by liewegas** [comment]
A general risk with doing % n is that the input sequence might follow (a multiple of) n, so that you are always hitting the same subset of nodes.  I'm not sure which circumstances might cause that in this case, but it might be helpful to have something at this level that would let you mitigate it.  Does that make sense?  This will work perfectly fine for 1,2,3,4 but will fail horribly if size == 4 and we feed it 0,4,8,12,....

**Comment by yukohe** [comment]
How about that we add an additional array to the linear bucket, with each element  associate with the items in the bucket to relive the case you mentioned?

**Comment by liewegas** [comment]
see https://github.com/ceph/ceph/pull/3541

**Pull request closed without merging**
