### PR TITLE
doc: Add a Ceph Foundation footer to docs.ceph.com

### PR DESCRIPTION
**Pull request by dvanders**
Add an info box to the footer of every docs page inviting visitors to support the Ceph Foundation.

### CODE REVIEW

**Review by zdover23 — APPROVED** [review]

**Comment by dvanders** [comment]
@zdover23 I re-pushed because I think it will look better without the link in the title.

**Comment by zdover23** [comment]
@dvanders You've got the approval. Merge at will and I'll make the backports.

**Review by anthonyeleven — APPROVED** [review]

**Comment by dvanders** [comment]
https://ceph--52802.org.readthedocs.build/en/52802/

**Comment by zdover23** [comment]
LGTM. Are you ready to merge?

**Review by zdover23 — APPROVED** [review]

**Comment by dvanders** [comment]
@zdover23 @anthonyeleven yes it's ready, pls merge

**Comment by dvanders** [comment]
(and backport to supported releases pls, if that is easy for you)

**Pull request merged**
