### PR TITLE
reef: librbd: make diff-iterate in fast-diff mode aware of encryption

### PR DESCRIPTION
**Pull request by idryomov**
backport tracker: https://tracker.ceph.com/issues/66743

---

backport of https://github.com/ceph/ceph/pull/58201
parent tracker: https://tracker.ceph.com/issues/66570

### CODE REVIEW

**Comment by idryomov** [comment]
Temporarily based on https://github.com/ceph/ceph/pull/58211 to avoid conflicts in `src/test/librbd/test_librbd.cc`.

**Review by ajarr — APPROVED** [review]

**Review by ajarr — APPROVED** [review]

**Comment by idryomov** [comment]
jenkins test make check

**Comment by idryomov** [comment]
Rebased after https://github.com/ceph/ceph/pull/58211 merged.

**Comment by idryomov** [comment]
jenkins test api

**Pull request merged**
