### PR TITLE
nautilus: batch functional idempotency test fails since message is now on stderr

### PR DESCRIPTION
**Pull request by jan--f**
https://tracker.ceph.com/issues/41299

### CODE REVIEW

**Comment by jan--f** [comment]
jenkins test ceph-volume batch all

**Comment by jan--f** [comment]
test failure are due to changes in ansible. Fix in #29694

**Comment by jan--f** [comment]
jenkins test ceph-volume batch all

**Comment by jan--f** [comment]
jenkins test ceph-volume batch all

**Comment by alfredodeza** [comment]
jenkins test ceph-volume batch all

**Comment by jan--f** [comment]
jenkins test ceph-volume all

**Comment by jan--f** [comment]
jenkins test ceph-volume all

**Pull request merged**
