### PR TITLE
more rocksdb configuration

### PR DESCRIPTION
**Pull request by XinzeChi**
1. add tow compression config for rocksdb, lz4 and lz4hc
2. add compression_per_level for each level

Signed-off-by: Xinze Chi <xmdxcxz@gmail.com>

### CODE REVIEW

**Comment by xiaoxichen** [comment]
I think we don't want to expose all RocksDB/LevelDB tunable into ceph.conf... There are tons of tunable and will be a trouble for us to interpret them from Ceph.conf to RocksDB::options/LevelDB::options.

Not sure if we could have a better way,I will survey ont that.But I suggest before that ,let's prevent adding more tunable unless they have clear user scenarios or performance benefit.

**Comment by XinzeChi** [comment]
i want to use rocksdb in kvstore to save up disk.  I just want to use its compression feature. at low level, lz4 is suitable because it is faster.  But at high level,  maybe zlib is more suitable because it has high compression rate.

**Comment by markhpc** [comment]
We want to avoid having options available in production builds that could get users into trouble (disabling sync, etc).  Some of these are useful for testing though, so we are considering a build flag to enable unsafe options.  Potentially if something like this were enabled, I think it would need to only be enabled in non-production builds and then we selectively enable specific safe features for production.

See: http://tracker.ceph.com/issues/11521

**Comment by XinzeChi** [comment]
I see. I close it first.

**Comment by tchaikov** [comment]
for a more flexible solution to for rocksdb configurations, see #4622

**Pull request closed without merging**
