### PR TITLE
jewel: ceph-disk: factor out the retry logic into a decorator

### PR DESCRIPTION
**Pull request by tchaikov**
http://tracker.ceph.com/issues/21730

backport of #18162

### CODE REVIEW

**Comment by smithfarm** [comment]
@tchaikov Did you also stage a luminous backport PR?

**Comment by smithfarm** [comment]
ah, mercifully the docs build check is no longer mandatory to merge a jewel PR.

**Comment by tchaikov** [comment]
http://pulpito.ceph.com/kchai-2017-10-09_11:11:32-ceph-disk-wip-bz1494543-jewel-kefu-distro-basic-vps/

**Comment by tchaikov** [comment]
@smithfarm sure will do!

**Comment by smithfarm** [comment]
@tchaikov ACK, luminous backport tracker is http://tracker.ceph.com/issues/21729 (JFYI)

**Pull request merged**
