### PR TITLE
octopus: mgr: set debug_mgr=2/5 (so INFO goes to mgr log by default)

### PR DESCRIPTION
**Pull request by callithea**
backport tracker: https://tracker.ceph.com/issues/51423

---

backport of https://github.com/ceph/ceph/pull/41933
parent tracker: https://tracker.ceph.com/issues/48311

this backport was staged using ceph-backport.sh version 16.0.0.6848
find the latest version at https://github.com/ceph/ceph/blob/master/src/script/ceph-backport.sh

### CODE REVIEW

**Comment by callithea** [comment]
jenkins retest this please

**Comment by callithea** [comment]
jenkins test make check

**Comment by neha-ojha** [comment]
jenkins test make check

**Comment by ljflores** [comment]
http://pulpito.front.sepia.ceph.com/yuriw-2022-01-24_18:01:47-rados-wip-yuri10-testing-2022-01-24-0810-octopus-distro-default-smithi/

Failures, unrelated:
    https://tracker.ceph.com/issues/50280
    https://tracker.ceph.com/issues/45318

Details:
    Bug_#50280: cephadm: RuntimeError: uid/gid not found - Ceph
    Bug_#45318: octopus: Health check failed: 2/6 mons down, quorum b,a,c,e (MON_DOWN)" in cluster log running tasks/mon_clock_no_skews.yaml

**Review by yuriw — APPROVED** [review]

**Pull request merged**
