### PR TITLE
mimic: mgr/dashboard: Escape regex pattern in DeletionModalComponent

### PR DESCRIPTION
**Pull request by pdvian**
http://tracker.ceph.com/issues/26920

### CODE REVIEW

**Comment by tspmelo** [comment]
Tests are failing because `testValidation` was added in a PR that was not backported:  https://github.com/ceph/ceph/commit/5cba67a5d29922e8e3e6ad31dfb51c6e66f2f232#diff-3b97fa7352e39cce428b2c53b1d77d9bR262

**Comment by tspmelo** [comment]
@smithfarm That commit would require we backport a few more commits.
I think the best solution is to edit this backport and replace `testValidation` with `testInvalidControl` in lines 288 and 290.
`testInvalidControl` is the old method we used and has the same logic as `testValidation`.

**Comment by smithfarm** [comment]
@tspmelo OK. Marking DNM pending that change.

**Comment by LenzGr** [comment]
Any news on this one? @pdvian - can you please take care of the requested changes?

**Comment by pdvian** [comment]
@LenzGr Let me do the requested changes. Thanks

**Comment by pdvian** [comment]
@tspmelo @LenzGr @smithfarm Updated PR with changes requested. Kindly review it.

**Comment by pdvian** [comment]
@tspmelo Yes, I was thinking of same. Thanks for inputs, updated PR with commit message to reflect changes.

**Pull request merged**
