### PR TITLE
mgr/dashboard_v2: Removed unused `tools.detail_route()`

### PR DESCRIPTION
**Pull request by sebastian-philipp**
Refactored corresponding `RESTControllerTest`:

* Made `RESTControllerTest` inherent from `ControllerTestCase`
* Refactored `ControllerTestCase`
* Simplified all tests that inherent from  `ControllerTestCase`

Signed-off-by: Sebastian Wagner <sebastian.wagner@suse.com>

### CODE REVIEW

**Comment by tchaikov** [comment]
retest this please

**Comment by sebastian-philipp** [comment]
@tchaikov looks like the dashboard_v2 smoke test needs an improvement.

**Comment by tchaikov** [comment]
@sebastian-philipp i believe the improvement has been merged as a part of #20768 =)

**Comment by rjfd** [comment]
@sebastian-philipp the backend API tests are failing:

```
2018-03-07 11:58:25,137.137 INFO:tasks.mgr.dashboard_v2.helper:request POST to http://rdias-suse-laptop.rdias.home.pt:7789//api/auth
2018-03-07 11:58:25,380.380 INFO:tasks.mgr.dashboard_v2.helper:request GET to http://rdias-suse-laptop.rdias.home.pt:7789//api/cluster_conf/admin_socket
2018-03-07 11:58:25,391.391 INFO:__main__:test_get (tasks.mgr.dashboard_v2.test_cluster_configuration.ClusterConfigurationTest) ... FAIL
2018-03-07 11:58:25,391.391 INFO:__main__:run args=['./bin/ceph', 'log', 'Ended test tasks.mgr.dashboard_v2.test_cluster_configuration.ClusterConfigurationTest.test_get']
2018-03-07 11:58:25,391.391 INFO:__main__:Running ['./bin/ceph', 'log', 'Ended test tasks.mgr.dashboard_v2.test_cluster_configuration.ClusterConfigurationTest.test_get']
2018-03-07 11:58:25,657.657 INFO:__main__:Stopped test: test_get (tasks.mgr.dashboard_v2.test_cluster_configuration.ClusterConfigurationTest) in 1.896289s
2018-03-07 11:58:25,658.658 INFO:__main__:
2018-03-07 11:58:25,658.658 INFO:__main__:======================================================================
2018-03-07 11:58:25,658.658 INFO:__main__:FAIL: test_get (tasks.mgr.dashboard_v2.test_cluster_configuration.ClusterConfigurationTest)
2018-03-07 11:58:25,658.658 INFO:__main__:----------------------------------------------------------------------
2018-03-07 11:58:25,658.658 INFO:__main__:Traceback (most recent call last):
2018-03-07 11:58:25,658.658 INFO:__main__:  File "/home/rdias/Work/ceph/qa/tasks/mgr/dashboard_v2/helper.py", line 23, in decorate
2018-03-07 11:58:25,658.658 INFO:__main__:    return func(self, *args, **kwargs)
2018-03-07 11:58:25,658.658 INFO:__main__:  File "/home/rdias/Work/ceph/qa/tasks/mgr/dashboard_v2/test_cluster_configuration.py", line 43, in test_get
2018-03-07 11:58:25,658.658 INFO:__main__:    self.assertStatus(200)
2018-03-07 11:58:25,659.659 INFO:__main__:  File "/home/rdias/Work/ceph/qa/tasks/mgr/dashboard_v2/helper.py", line 119, in assertStatus
2018-03-07 11:58:25,659.659 INFO:__main__:    self.assertEqual(self._resp.status_code, status)
2018-03-07 11:58:25,659.659 INFO:__main__:AssertionError: 500 != 200
2018-03-07 11:58:25,659.659 INFO:__main__:
2018-03-07 11:58:25,659.659 INFO:__main__:----------------------------------------------------------------------
```

**Comment by rjfd** [comment]
@sebastian-philipp I just caught the same failure while testing another PR, maybe the failure is caused by some commit merged to master recently and not your PR.

**Comment by sebastian-philipp** [comment]
@rjfd This fixes my issue:
```diff
git diff src/common/config.cc | cat 
diff --git a/src/common/config.cc b/src/common/config.cc
index a1f0fbdbf2..1932e0d3b3 100644
--- a/src/common/config.cc
+++ b/src/common/config.cc
@@ -503,7 +503,9 @@ void md_config_t::config_options(Formatter *f)
   f->open_array_section("options");
   for (const auto& i: schema) {
     const Option &opt = i.second;
+    f->open_object_section("option");
     opt.dump(f);
+    f->close_section();
   }
   f->close_section();
 }
```

**Comment by rjfd** [comment]
@sebastian-philipp that part of the of `common/config.cc` code was not changed in the last two months. 
Although it might fix the problem I would like to know what was the commit that introduced the bug and why does it cause a failure, so that we can fix it properly in a different PR.

**Comment by rjfd** [comment]
I created an issue in http://tracker.ceph.com/issues/23265 to keep track of this bug

**Comment by sebastian-philipp** [comment]
See #20782

**Comment by sebastian-philipp** [comment]
@rjfd commit is now split in two.

**Comment by rjfd** [comment]
dashboard QA suite ran successfully:
http://pulpito.ceph.com/kchai-2018-03-12_09:20:19-rados-wip-rdias-testing-distro-basic-mira/

**Pull request merged**
