### PR TITLE
tests: be more generous with mon tests timeouts

### PR DESCRIPTION
**Pull request by dachary**
Change the timeouts of the TEST_mon_add_to_single_mon tests to be 120
seconds. They have value to guard against blocking forever. The exact
timing does not matter as long as the operation completes.

When a timeout is too short, it will create false negatives when running
on slow machines. It could be argued that being too generous with
timeout in general may hide problems. But not in this specific case.

Signed-off-by: Loic Dachary <ldachary@redhat.com>

### CODE REVIEW

**Comment by dachary** [comment]
Here is a recent false negative: http://jenkins.ceph.dachary.org/job/ceph/LABELS=ubuntu-14.04&&x86_64/7002/console

<pre>
./test/mon/misc.sh:116: TEST_mon_add_to_single_mon:  num_mons=2
./test/mon/misc.sh:117: TEST_mon_add_to_single_mon:  '[' 2 == 2 ']'
./test/mon/misc.sh:119: TEST_mon_add_to_single_mon:  timeout 1 ceph mon add b 127.0.0.1:7118
*** DEVELOPER MODE: setting PATH, PYTHONPATH and LD_LIBRARY_PATH ***
./test/mon/misc.sh:119: TEST_mon_add_to_single_mon:  return 1
./test/mon/misc.sh:31: run:  return 1
../qa/workunits/ceph-helpers.sh:1174: main:  code=1
</pre>

**Comment by dachary** [comment]
Another false negative at http://jenkins.ceph.dachary.org/job/ceph/LABELS=ubuntu-14.04&&x86_64/7006/console

**Comment by dachary** [comment]
@tchaikov repushed

**Comment by tchaikov** [comment]
@dachary

is your repo down?
```
+ cd ../ceph-docker/src
+ git fetch --force origin master pull/5555
fatal: unable to access 'http://workbench.dachary.org/ceph/ceph.git/': Could not resolve host: workbench.dachary.org
```

**Comment by tchaikov** [comment]
`Reviewed-by: Kefu Chai <kchai@redhat.com>` once the pr is confirmed by the build bot

**Comment by dachary** [comment]
rebased & repushed (no change) to trigger the bot

**Pull request merged**
