### PR TITLE
octopus: mgr/cephadm: on ssh connection error, advice chmod 0600

### PR DESCRIPTION
**Pull request by mgfritch**
backport of #39259

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Review by adk3798 — APPROVED** [review]

**Comment by mgfritch** [comment]
jenkins retest this please

**Comment by mgfritch** [comment]
jenkins test api

**Comment by mgfritch** [comment]
jenkins test docs

**Comment by sebastian-philipp** [comment]
jenkins test docs

**Comment by smithfarm** [comment]
It can be hard to tell which octopus release a backport PR went into when it has no backport tracker issue associated.

This one went into the 15.2.13 release.

**Comment by sebastian-philipp** [comment]
> It can be hard to tell which octopus release a backport PR went into when it has no backport tracker issue associated.
> 
> This one went into the 15.2.13 release.

Right. the changelog is listing this PR as part of .13: https://docs.ceph.com/en/latest/releases/octopus/

**Pull request merged**
