### PR TITLE
Transaction Id added in S3 and Swift response 

### PR DESCRIPTION
**Pull request by abhidixit**
Transaction Id added in both S3 and swift response.
S3 will have id in x-amz-request-id header and Swift have X-Trans-Id header.
For S3, id is concatenation of gateway id and request id.
Swift will have additional timestamp appended in human readable format.

Signed-off-by: Abhishek Dixit dixitabhi@gmail.com

### CODE REVIEW

**Comment by abhidixit** [comment]
@yehudasa The only place we can initialize i.e. modify and append time information to req_id is at <s->req_id = store->unique_id(req->id);>. So we can modify s->req_id after this step or we can modify inside store function itself or we can have new string to contain modified value. This will give same req_id value containing time info for both Swift and S3 usage.
Still in this case also we will need dump_trans_id function as Swift and S3 headers are different.
Kindly advise on which way to proceed. In current implementation, we use req_id only at last moment without modifying any other.

**Comment by yehudasa** [comment]
@abhidixit it would be cleaner to take the timestamp at the start of the request processing, not at the end. While doing it we can generate the transaction id string, and keep it on the req_state. Having this string at hand might be useful for other stuff (e.g., debug logging).

**Comment by yehudasa** [comment]
@abhidixit note that we fixed the req_id issue in civetweb recently, can you take a look at it now? I still think we should set it on the req_state in one place.

**Comment by abhidixit** [comment]
@yehudasa I looked into the req_id changes for civetweb. The changes looks good to me as they  have addressed both issues of duplicate req_id possibility and uninitialized req_id via civetweb  callback path.
Also i have made changes for transaction id in response as per your suggestions. Kindly look into it and provide feedback/approval.

**Comment by yehudasa** [comment]
@abhidixit can you squash the two commits? it'll make it easier to review it this way

**Comment by abhidixit** [comment]
@yehudasa I have squashed the commits. Please provide feedback. Thanks

**Comment by abhidixit** [comment]
@yehudasa Can you please review this and provide feedback?

**Comment by yehudasa** [comment]
@abhidixit see my comment. Almost there.

**Comment by abhidixit** [comment]
@yehudasa I have moved the changes to rgw_common.cc as per your feedback. Making single function set_req_id for setting req_id and trans_id did not worked as req_id is generated using store->unique_id which can not be moved inside req_state method. I tried but it gave forward declaration error for store which will need changing header files include order. So i think, we can keep req_id generation as it is and add new changes purely for Trans_id.

**Comment by yehudasa** [comment]
@abhidixit ok, that will be fine. Just note that it doesn't merge cleanly now, will need you to rebase it on top of current master.

**Comment by abhidixit** [comment]
@yehudasa Done rebasing.

**Pull request closed without merging**
