### PR TITLE
DNM: jewel: rgw: bucket resharding

### PR DESCRIPTION
**Pull request by dang**
An offline tool to reshard a bucket's index. Usage:

$ radosgw-admin bucket reshard --bucket= --num-shards=

This will create a new linked bucket instance that points to the newly created index objects. The old bucket instance still exists and currently it's up to the user to manually remove the old bucket index objects.

Backported from PR# 11230

### CODE REVIEW

**Comment by dachary** [comment]
Marking as DNM to remember that it should not be merged before the [matching master pull request](https://github.com/ceph/ceph/pull/11230) is merged.

**Comment by dachary** [comment]
@dang could you please use **git cherry-pick -x** so that it automatically adds a reference to the commit being picked ? If there are conflicts, a short explanation about how it was resolved and why it happens would be helpful.

**Comment by dang** [comment]
@dachary Should I redo this PR?

**Comment by dachary** [comment]
@dang if you give me a list of commits from which these commits have been cherry picked, I can do it for you.

**Comment by dang** [comment]
@dachary All the commits in PR# 11230.  I just rebased that onto jewel.

**Comment by dachary** [comment]
@dang ok, I will assume you did not have any conflicts then. Thanks for the confirmation. I'll open an alternative PR with the commits cherry picked with **git cherry-pick -x**.

**Comment by robbat2** [comment]
@dang @dachary I don't see a Jewel PR for this; did it ever happen (so it can go into jewel-next for 10.2.6)

**Comment by smithfarm** [comment]
@robbat2 AFAICT it has not been implemented for jewel yet. @oritwas did a hammer implementation here https://github.com/ceph/ceph/pull/12227 which is queued for release in 0.94.10.

**Comment by robbat2** [comment]
Should I try to forward-port the Hammer implementation, or work on back-porting the Kraken implementation? Would be a shame to have it in Hammer but not Jewel.

**Comment by oritwas** [comment]
@robbat2 , you should not use the hammer version.
The master version should apply cleanly.

**Comment by smithfarm** [comment]
@robbat2 Just please use `git cherry-pick -x` and describe how all conflicts were resolved.

**Comment by robbat2** [comment]
New backport at https://github.com/ceph/ceph/pull/13341
Needs testing

**Pull request closed without merging**
