### PR TITLE
[DNM] qa/suites/rados/verify/validater/valgrind: set longer timeout for healthy()

### PR DESCRIPTION
**Pull request by tchaikov**
Fixes: http://tracker.ceph.com/issues/19113

### CODE REVIEW

**Comment by tchaikov** [comment]
this change depends on https://github.com/ceph/teuthology/pull/1036

**Comment by smithfarm** [comment]
@tchaikov Is the valgrind delay related to boost being in a submodule (statically linked?) now?

**Comment by liewegas** [comment]
This will probably avoid the failures, but somethign changed that is making this happen now.. we weren't seeing these failures before.  I'm wondering if some other process on the machine is eating up CPU or RAM or something?  Those are *really* long stalls that we're seeing!

**Comment by tchaikov** [comment]
will hold on until we root cause this (fail to do so!)

**Comment by tchaikov** [comment]
closing in favor of #13748.

**Pull request closed without merging**
