### PR TITLE
nautilus: mds: avoid journaling overhead for setxattr("ceph.dir.subvolume") for no-op case

### PR DESCRIPTION
**Pull request by batrick**
https://tracker.ceph.com/issues/51337

### CODE REVIEW

**Comment by smithfarm** [comment]
jenkins test make check

**Comment by batrick** [comment]
jenkins test make check

**Comment by batrick** [comment]
jenkins test api

**Comment by batrick** [comment]
jenkins test make check

**Comment by batrick** [comment]
jenkins test make check

**Comment by batrick** [comment]
jenkins test make check

**Comment by batrick** [comment]
jenkins test make check

**Comment by batrick** [comment]
(this is fun)

**Comment by smithfarm** [comment]
@batrick Looks like the build is segfaulting.

**Comment by batrick** [comment]
> @batrick Looks like the build is segfaulting.

Quite right. Wasn't grepping for that! Any suggestions?

**Comment by smithfarm** [comment]
Sorry. I haven't the slightest idea why it's segfaulting.

**Comment by smithfarm** [comment]
@batrick Can you reproduce the segfault locally?

**Comment by batrick** [comment]
> @batrick Can you reproduce the segfault locally?

If this weren't an EOL release I would try. I don't really have much time to debug this. I was hoping this is a transient issue.

**Comment by batrick** [comment]
EOL

**Pull request closed without merging**
