### PR TITLE
rbd: minor cleanup 

### PR DESCRIPTION
**Pull request by yangdongsheng**

### CODE REVIEW

**Comment by yangdongsheng** [comment]
@dillaman Just two minor cleanups, please help to take a look. thanx

**Comment by dachary** [comment]
jenkins test this please (unittest_journal)

**Comment by dillaman** [comment]
@yangdongsheng Can you fix the commit message that has a semicolon after "librbd" and change it to a colon?

**Comment by yangdongsheng** [comment]
@dillaman Oh, sure, thanx.

**Pull request merged**
