### PR TITLE
ObjectCacher: fix bh_read_finish offset logic

### PR DESCRIPTION
**Pull request by gregsfortytwo**
If we have an incoming read split across multiple BufferHeads, we want to
line up the BufferHead's bl with the incoming OSDOp's bl at the right offset. We
were erroneously using this nonsense calculation (always equal to zero!) when
a much simpler comparison of the BufferHead's logical object offset to the
incoming OSDOp's logical offset will do the trick nicely.

Fixes: http://tracker.ceph.com/issues/16002

Signed-off-by: Greg Farnum <gfarnum@redhat.com>

### CODE REVIEW

**Comment by gregsfortytwo** [comment]
This was tested in situ and functions correctly. I'm working on a test for it but the existing ObjectCacher testing framework was insufficient (it doesn't actually store any data so you can't test data-driven failures like this) and doing so ballooned a bit more than I had planned for.

**Comment by liewegas** [comment]
Reviewed-by:

**Comment by gregsfortytwo** [comment]
This now has a test! If you run it without the ObjectCacher patch, it fails; and the test is included as part of the stress_objectcacher.sh script so it will automatically get tested in the RADOS teuthology suite.

**Comment by jdurgin** [comment]
lgtm, if we add more tests like this in the future it'd be nice to use gtest for them, but for just 2 tests this looks good

**Comment by jcsp** [comment]
@gregsfortytwo Did this go into a rados suite run yet?

**Comment by jdurgin** [comment]
Looks like only two tests in the rados suite would use the objectcacher - singleton-nomsgr/all/cache-fs-trunc.yaml and objectstore/objectcacher-stress.yaml.

The rbd and fs suites will get more coverage.

**Comment by gregsfortytwo** [comment]
http://pulpito.ceph.com/gregf-2016-06-27_22:02:48-fs-greg-fs-testing-627---basic-mira/ looks good, just 3 infra timeouts

The rbd suite is still running.

**Comment by gregsfortytwo** [comment]
Jason tells me http://pulpito.ceph.com/gregf-2016-06-27_22:28:07-rbd-greg-fs-testing-627---basic-mira/ is a fine result right now.

**Pull request merged**
