### PR TITLE
tests: pin flake8 to avoid behavior changes

### PR DESCRIPTION
**Pull request by dachary**
Fixes: http://tracker.ceph.com/issues/17898

Signed-off-by: Loic Dachary <loic@dachary.org>

### CODE REVIEW

**Comment by dachary** [comment]
jenkins test this please (looks like it's stuck)

**Comment by ktdreyer** [comment]
Using the python-flake8 system packages would bring some stability instead of using the latest releases directly from PyPI

**Comment by ktdreyer** [comment]
Can we add two spaces before the classes to avoid this error? It's been a warning for a while, right?

**Comment by ktdreyer** [comment]
I'm wrong, it hasn't been a warning for a while.

https://github.com/ceph/ceph/pull/11973 is an alternate approach that fixes the error instead of pinning.

**Comment by dachary** [comment]
@ktdreyer I agree this should be fixed. And flake8 should also be pinned so that we can choose when to upgrade flake8 instead of relying on the maintainer to keep it backward compatible.

**Comment by dachary** [comment]
the ceph-disk & ceph-detect-init pass, only the usual suspect fail

**Comment by ktdreyer** [comment]
> And flake8 should also be pinned so that we can choose when to upgrade flake8

When will we choose to update? (There are many old dependencies pinned throughout the ceph project.)

**Comment by dachary** [comment]
I'll revert this since you think it's a bad idea

**Pull request merged**
