### PR TITLE
doc: Update multisite-sync-policy.rst

### PR DESCRIPTION
**Pull request by ypdai**
Signed-off-by: ypdai <self19900924@gmail.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by zdover23** [comment]
jenkins test api

**Comment by zdover23** [comment]
jenkins render docs

**Review by zdover23 — APPROVED** [review]

**Comment by zdover23** [comment]
@ypdai: we need a verifiable email address.

**Review by zdover23 — CHANGES_REQUESTED** [review]
We need a verifiable email address.

**Comment by ypdai** [comment]
> We need a verifiable email address.

emm... I need to make any?

**Comment by zdover23** [comment]
> > We need a verifiable email address.
> 
> emm... I need to make any?

What?

**Comment by zdover23** [comment]
> @ypdai @zdover23 any updates on this PR? It looks like there was confusion about the requested changes.

@ljflores I apologize for leaving you hanging so long on this one. I agree that it seems that there was confusion. I am not expert in the ways of RGW, so I'll ask Neha to take a look at this or delegate it to someone with expertise. If they say this passes muster, I'll cherry-pick the commit into a clean branch, credit ypdai to the best of my ability, and close this PR.

@neha-ojha: do the changes in this PR (which seem to me to be wildcards that replace ranges and the removal of a command-line flag) meet with your approval?

**Pull request closed without merging**
