### PR TITLE
crimson/net: better connections management in msgr

### PR DESCRIPTION
**Pull request by cyx1231st**
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by cyx1231st** [comment]
@cbodley @tchaikov 
Did some cross-check with existing msgr implementations related to connection managements, looking forward to your opinions, thanks!

**Comment by cbodley** [comment]
thanks for taking this on! this looks like a step in the right direction

i have a feeling that most of the error handling/retry logic belongs in the Messenger instead, which can deal with them at a higher level and ultimately notify the Dispatcher with calls to ms_handle_reset() etc.

SocketMessenger::dispatch() is the only place that tries to do this currently, so we should make sure any errors in Connection make their way back there. once we're back in SocketMessenger, it should be safe to call close() and unregister the connection.

with respect to register_conn(), i agree with your changes - but i think SocketMessenger should drive that part too. effectively, that means SocketMessenger::accept() registering the connection before calling server_handshake(), and SocketMessenger::connect() registering after client_handshake(). that way we don't need to expose public functions for [un]register_conn() at all

---

then as a next step, we can rework that to handle lossless connections. dispatch() is called by accept() and connect(), which will both want to handle these errors differently - so we should move that .handle_exception_type() block out to the callers. then:

* connect() for lossless connections will want to reconnect, redo client handshake, and resend any queued requests

* accept() is the server side, which doesn't try to reestablish connections. but we do need to keep the Connection around in case the client reconnects, so we can resend its queued requests after server handshake

implementing this could get messy, especially if we want to keep the same ConnectionRef instance so that reconnects are seamless to the application. it might help to break things up further by introducing a new Session class for that, which contains all of the state that survives reconnects. then on reconnect, the messenger could swap the new Connection into the existing Session

**Comment by cyx1231st** [comment]
> i have a feeling that most of the error handling/retry logic belongs in the Messenger instead

@cbodley I agree! Current implementations (both async and simple) use a single `Connection` class to expose high-level lossless/lossy sessioned connection to callers, meanwhile, it also tries to manage low-level sockets in the same class. These mixed responsibilities introduce unnecessary messy logic inside the `Connection` class, not to mention that the `Messenger` needs to extract related events from inside the `Connection`, and then redirect them to `Dispatcher`. I tried to draw the abstracted architecture for illustration ("XXX" part for the mixed responsibilities):
```
             +---------+
             | Callers |
             +----^----+
                  |
 Connections +----+----+
             |/////////|
           +-|---------|---+
           |\|XXXXXXXXX|\\\|
           |\|XXXXXXXXX|\+-------------+
 Messenger |\|XXXXXXXXX+-> Dispatchers |
           |\|XXXXXXXXX|\+-------------+
           |\|XXXXXXXXX|\\\|
           +-|---------|---+
             |/////////|
             +----^----+
                  |
             +----+----+
             | Sockets |
             +---------+
```
> it might help to break things up further by introducing a new Session class for that

Yes, if I am correct, it is to divide the caller-side responsibilities of the existing `Connection` class into a new class `SessionedConnection`. And let `Messenger` handle the failures of the low-level `SocketConnection`, arrange them to `SessionedConnection` according to lossless/lossy policy, and meanwhile, dispatch intermediate events to `Dispatcher`. In this way, we can achieve a better design by better decoupling and encapsulation, illustrated below:
```
            +---------+
            | Callers |
            +----^----+
                 |
Sessioned   +----+----+
Connections |/////////|
          +-|/////////|---+
          |\+---------+\\\|
Better    |\\\\\\\\\\\\\+-------------+
Messenger |\\\\\\\\\\\\\| Dispatchers |
          |\\\\\\\\\\\\\+-------------+
          |\+---------+\\\|
          +-|/////////|---+
Socket      |/////////|
Connections +----^----+
                 |
            +----+----+
            | Sockets |
            +---------+
```
Then it should be more natural to have the following designs:
> SocketMessenger::dispatch() is the only place that tries to do this {i.e. the dispatching work}

> with respect to register_conn() {snipped} i think SocketMessenger should drive that part too.

> we can rework that to handle lossless connections. dispatch() is called by accept() and connect(), which will both want to handle these errors differently - so we should move that .handle_exception_type() block out to the callers {i.e. into the SocketMessenger}

**Comment by tchaikov** [comment]
the layered design makes more sense than what we have now! and yeah, i tend to agree with @cbodley 's suggestion: we could extract the status of connection like state transition, connection replacing, pending messages to a dedicated class, leaving the details of messenger protocol to `SocketConnection` , and expose the `Connection` to its user.

@cyx1231st one reason why we want to keep `Connection` is that, as per @cbodley , we could use the `DirectMessenger` and `DirectConnection` in future for profiling the stack. by then, we can switch the OSD to the `Direct` implementation with minimal changes in it, because it's using the `Connection` interface.

**Comment by cyx1231st** [comment]
Thanks for the great inputs!
I'm looking towards the following steps:
1. Split the responsibilities of `SocketConnection` class, make sure the overall architecture looks good and lossy policy workable.
2. Implement sharded messenger, so multiple lossy connections can be established across cores.
3. Implement lossless connection policy and deal with handshake racing.

**Comment by cbodley** [comment]
sounds good! step 3 is gonna be the ~~scary~~ fun one!

**Comment by cyx1231st** [comment]
Close this.. please refer to #24576 for the refactoring.

**Pull request closed without merging**
