### PR TITLE
rgw: fix compatible with Swift URL

### PR DESCRIPTION
**Pull request by chiehtu**
Add support for "/AUTH_(project ID)" path when integrating with
OpenStack Keystone.

Fixes: http://tracker.ceph.com/issues/19264
Signed-off-by: Albert Tu <albert.t@inwinstack.com>

### CODE REVIEW

**Comment by yehudasa** [comment]
@chiehtu it's not clear to me what this fixes. It doesn't look like tracker issue this bug points at corresponds to this fix. Also, looking at this fix, I'm not sure it's not breaking other stuff. For example, you drop the use of g_conf->rgw_swift_tenant_name.

**Comment by chiehtu** [comment]
@yehudasa This fixes public access to container on OpenStack Horizon, it needs to set correct Swift URL to working right. 

I don't drop the use of `g_conf->rgw_swift_tenant_name`, it's implemented on line 2347.

And this PR isn't about forbidden character, I think the most related issue is http://tracker.ceph.com/issues/19268

**Comment by Herr-Herner** [comment]
@rzarzynski 
Can you please explain why only the public endpoint requires a modified URL whereas all other endpoints still point to `http://radosgw.example.com:8080/swift/v1`.

**Comment by rzarzynski** [comment]
@Herr-Herner: what do you mean? Currently RadosGW requires account-in-Keystone-endpoint's (or not) depending on the config options `rgw_swift_account_in_url` or `rgw_swift_tenant_name`. This pull request tries to introduce:
* some kind of *auto-detection* for the presence of the account part,
* a documentation change about setting **only** the public URL to contain the account part.

At the moment I believe none of those is valid but let's wait for author's response.

**Comment by Herr-Herner** [comment]
Right... But in your section "As of Newton" (https://github.com/chiehtu/ceph/blob/1937d9112069beb889ee0210476594616bd3c80e/doc/radosgw/keystone.rst) only the public endpoint contains the path `AUTH_$(project_id)s`. The internal as well as the admin endpoint do not contain the suffix. I do not understand why. In my environment, this setup does not make sense, because e.g. Ceilometer uses the internal and not the public endpoint to communicate with the object store.

**Comment by rzarzynski** [comment]
@Herr-Herner: I think we still have a misunderstanding here. ;-) The link you've quoted refers  @chiehtu's repository, **not mine**.

**Comment by Herr-Herner** [comment]
@rzarzynski: Upps! You are right. I am sorry for the confusion I have caused.

**Comment by rzarzynski** [comment]
@chiehtu: I'm closing this PR. Feel free to re-open/create new one in any case. :-)

**Comment by chiehtu** [comment]
@rzarzynski Thanks for your replies. `rgw swift account in url = true` seems work, I will add the setting to documentation. And if someone has a container named `AUTH_LOG_2017_APRIL`, they need replace `/AUTH_LOG_2017_APRIL` with `/AUTH_{{ project ID }}/AUTH_LOG_2017_APRIL` when visiting.

@Herr-Herner The public endpoint was changed because public access requires it to create public URL like above. Also, `AUTH_` is the [default prefix](https://github.com/openstack/swift/blob/stable/mitaka/swift/common/middleware/keystoneauth.py#L73) in OpenStack Swift.

**Pull request closed without merging**
