### PR TITLE
Objecter: don't hold session lock when sending message

### PR DESCRIPTION
**Pull request by yuyuyu101**
Signed-off-by: Haomai Wang <haomai@xsky.com>

### CODE REVIEW

**Comment by yuyuyu101** [comment]
caller call send_message under AsyncMessenger will do all the things inline(encode, enter kernel space ..), so with OSDSession::lock hold, the performance will be throttled by lock contention.

From my very simple test, fio with randread, with this patch, async messenger could improve from 22k to 35k and beat simple messenger now!

@branch-predictor I think this patch will solve your async performance before, plz let me if you have time to test this!

**Comment by yuyuyu101** [comment]
simple performance test result from @branch-predictor http://ceph.predictor.org.pl/async_7508-4k.txt

the first is async the second is simple.

**Comment by branch-predictor** [comment]
Another one for 64k op: 
http://ceph.predictor.org.pl/async_7508-64k.txt
And for 4M:
http://ceph.predictor.org.pl/async_7508.txt
In all cases, async msgr was faster but not by much in 4M case.

**Comment by yuyuyu101** [comment]
retest this please

**Comment by branch-predictor** [comment]
I've tested different variations, including async messenger without Haomai's MSG_MORE patch, without Objecter patch, and with Simple messenger, for comparison purposes.
Some fancy graphs below, and complete data sheet is available here: http://ceph.predictor.org.pl/asyncmsgr_7508.xlsx

Rand read:
7508_randread

Write:
7508_write

My conclusion is that adding MSG_MORE hurts performance when used too often, so I'll be investigating if it'll be possible to find a sweet spot between throughput and packet count. Objecter patch caused Async msgr performance to become jumpy at higher IO sizes, not dropping much below previous version, so it works - no doubts about that.

**Comment by branch-predictor** [comment]
LGTM after rebase and qa run.

**Comment by liewegas** [comment]
I'm seeing out of order op assertions on the OSD... which saw the messsages arrive out of order:

 -1280> 2016-02-24 03:19:22.206851 7f13da8a8700  1 -- 172.21.15.51:6800/7300 <== client.4123 172.21.15.37:0/3849449969 12 ==== osd_op(client.4123.0:6952 12.e25d763a (undecoded) ack+ondisk+write+known_if_redirected e35) v7 ==== 272+0+524288 (669440835 0 2038671816) 0x7f1412aa6dc0 con 0x7f1411ca5c00
 -1016> 2016-02-24 03:19:22.210377 7f13da8a8700  1 -- 172.21.15.51:6800/7300 <== client.4123 172.21.15.37:0/3849449969 13 ==== osd_op(client.4123.0:6956 11.7ddb2b43 (undecoded) ack+ondisk+write+known_if_redirected e35) v7 ==== 234+0+266 (3919170029 0 2144316173) 0x7f1412aa9180 con 0x7f1411ca5c00
 -1004> 2016-02-24 03:19:22.210496 7f13da8a8700  1 -- 172.21.15.51:6800/7300 <== client.4123 172.21.15.37:0/3849449969 14 ==== osd_op(client.4123.0:6957 6.1b1483f6 (undecoded) ack+ondisk+write+known_if_redirected e35) v7 ==== 250+0+344 (105259709 0 110944995) 0x7f14118a4840 con 0x7f1411ca5c00
  -943> 2016-02-24 03:19:22.210962 7f13da8a8700  1 -- 172.21.15.51:6800/7300 <== client.4123 172.21.15.37:0/3849449969 15 ==== osd_op(client.4123.0:6954 11.7ddb2b43 (undecoded) ack+ondisk+write+known_if_redirected e35) v7 ==== 234+0+264 (2529802619 0 1432294824) 0x7f14127fc580 con 0x7f1411ca5c00
  -819> 2016-02-24 03:19:22.211565 7f13da8a8700  1 -- 172.21.15.51:6800/7300 <== client.4123 172.21.15.37:0/3849449969 16 ==== osd_op(client.4123.0:6958 12.e25d763a (undecoded) ack+ondisk+write+known_if_redirected e35) v7 ==== 272+0+524288 (4279288151 0 4037375747) 0x7f14138f8ec0 con 0x7f1411ca5c00

**Comment by yuyuyu101** [comment]
Hmm, looks like sharding OSDSession is the only way.....

**Pull request closed without merging**
