### PR TITLE
[DNM] rbd-mirror: ImageReplayer async start/stop

### PR DESCRIPTION
**Pull request by trociny**

### CODE REVIEW

**Comment by trociny** [comment]
It is still WIP: after adding additional tests I have found some issues with the current code. E.g. `delete m_local_image_ctx`  should be executed in the caller's context. Also `m_remote_journaler->shutdown()` hangs in Error_on_start_remote_journaler_init test (this might the test problem though, need to investigate).

**Comment by trociny** [comment]
So, I think in the case of async start failure, cleanup (`delete m_local_image_ctx`, `m_remote_journaler->shutdown()`) should be executed in the caller context.

I think we could use similar approach that is used in aio_close: i.e something like:
```
ImageReplayerCompletion comp;
replayer->start(&comp);
...
r = comp.wait_for_complete();
comp.release(); // Cleanup executed here.
``

Or just add completion methods to ImageReplayer:
```
replayer->start();
r = replayer->wait_for_start_complete();
r = replayer->is_start_complete();
r = replayer->get_return_value();
r = replayer->start_completion_release();
```

I don't like very much both ways but right now can't think up a better solution. May be provide async methods for image context release and journaler shutdown (I have not looked yet how complicated it)?

 Do you have any suggestions?

**Comment by dillaman** [comment]
@trociny Definitely agree that we want async journal shut down -- there is an open tracker ticket for that.  There should already be support for async ImageCtx (PR #7839 removes the blocking unwatch call).

**Comment by trociny** [comment]
@dillaman Thanks. I failed to find the ticket for 'async journal shut down' but I will work on this.

**Comment by dillaman** [comment]
Here is is: http://tracker.ceph.com/issues/14530

**Comment by trociny** [comment]
@dillaman 

> There should already be support for async ImageCtx (PR #7839 removes the blocking unwatch call).

It still hangs for me here:

https://github.com/trociny/ceph/blob/473f38ef6f036f9bcb92949cf411357f75b8b67f/src/tools/rbd_mirror/ImageReplayer.cc#L685

in op_work_queue drain:

```
#1  0x0000555555937e15 in Wait (mutex=..., this=0x7fffc8002ff0) at common/Cond.h:56
#2  ThreadPool::drain (this=0x7fffc8002f20, wq=wq@entry=0x7fffd0003d80) at common/WorkQueue.cc:266
#3  0x00005555557a71e3 in drain (this=0x7fffd0003d80) at ./common/WorkQueue.h:361
#4  librbd::ImageCtx::~ImageCtx (this=0x7fffd000d480, __in_chrg=<optimized out>) at librbd/ImageCtx.cc:218
#5  0x000055555577dafb in rbd::mirror::ImageReplayer::on_stop_local_image_close_finish (this=0x55555edb1c30, r=0) at tools/rbd_mirror/ImageReplayer.cc:685
```

**Comment by dillaman** [comment]
@trociny Well, long term, rbd-mirror will need its own ThreadPool and SafeTimer (since we don't want each journaler to start its own).  Therefore, you should pass a WorkQueue  to the ImageReplayer, it can use that pool to wrap the callback to ```on_stop_local_image_close_finish``` to execute the callback outside of librbd's WorkQueue.  See ```librbd::util::create_async_context_callback```

**Comment by trociny** [comment]
Rebased after adding WorkQueue and fixing on start/stop hangs.

**Comment by trociny** [comment]
@dillaman The valgrind error I mentioned on sync is also reproduced on ceph_test_librbd:

```
[ RUN      ] TestLibRBD.ResizeAndStat
using new format!
==15886== Thread 40:
==15886== Invalid write of size 8
==15886==    at 0x650F2B: Objecter::handle_osd_op_reply(MOSDOpReply*) (Objecter.cc:3234)
==15886==    by 0x6587EA: Objecter::ms_dispatch(Message*) (Objecter.cc:934)
==15886==    by 0x82C6B5: ms_fast_dispatch (Messenger.h:555)
==15886==    by 0x82C6B5: DispatchQueue::fast_dispatch(Message*) (DispatchQueue.cc:71)
==15886==    by 0x84580A: Pipe::reader() (Pipe.cc:1650)
==15886==    by 0x84D24C: Pipe::Reader::entry() (Pipe.h:52)
==15886==    by 0xABD20A3: start_thread (pthread_create.c:309)
==15886==    by 0xC8BD04C: clone (clone.S:111)
==15886==  Address 0x22cb0108 is 168 bytes inside a block of size 360 free'd
==15886==    at 0xA9BF360: operator delete(void*) (vg_replace_malloc.c:507)
==15886==    by 0x452388: Context::complete(int) (Context.h:64)
==15886==    by 0x6AB7BD: Finisher::finisher_thread_entry() (Finisher.cc:68)
==15886==    by 0xABD20A3: start_thread (pthread_create.c:309)
==15886==    by 0xC8BD04C: clone (clone.S:111)
==15886== 
```

So it looks like the valgrind error I observe is not due to ImageReplayer.

**Comment by dillaman** [comment]
@trociny Probably this issue: https://github.com/ceph/ceph/pull/7864

**Comment by trociny** [comment]
@dillaman The valgrind error I mentioned on sync is also reproduced on ceph_test_librbd:

```
[ RUN      ] TestLibRBD.ResizeAndStat
using new format!
==15886== Thread 40:
==15886== Invalid write of size 8
==15886==    at 0x650F2B: Objecter::handle_osd_op_reply(MOSDOpReply*) (Objecter.cc:3234)
==15886==    by 0x6587EA: Objecter::ms_dispatch(Message*) (Objecter.cc:934)
==15886==    by 0x82C6B5: ms_fast_dispatch (Messenger.h:555)
==15886==    by 0x82C6B5: DispatchQueue::fast_dispatch(Message*) (DispatchQueue.cc:71)
==15886==    by 0x84580A: Pipe::reader() (Pipe.cc:1650)
==15886==    by 0x84D24C: Pipe::Reader::entry() (Pipe.h:52)
==15886==    by 0xABD20A3: start_thread (pthread_create.c:309)
==15886==    by 0xC8BD04C: clone (clone.S:111)
==15886==  Address 0x22cb0108 is 168 bytes inside a block of size 360 free'd
==15886==    at 0xA9BF360: operator delete(void*) (vg_replace_malloc.c:507)
==15886==    by 0x452388: Context::complete(int) (Context.h:64)
==15886==    by 0x6AB7BD: Finisher::finisher_thread_entry() (Finisher.cc:68)
==15886==    by 0xABD20A3: start_thread (pthread_create.c:309)
==15886==    by 0xC8BD04C: clone (clone.S:111)
==15886== 
```

So it looks like the valgrind error I observe is not due to ImageReplayer.

**Comment by trociny** [comment]
It looks like I unintentionally closed this PR. Will reopen new one.

@dillaman Yes, #7864 fixes valgrind errors to me, thanks

**Comment by trociny** [comment]
@dillaman reopened as #7944

**Pull request closed without merging**
