### PR TITLE
osd/PG: handle flushed event directly

### PR DESCRIPTION
**Pull request by wumingqiao**
same logic as before, but avoid queueing and thread switching

Signed-off-by: wumingqiao <wumingqiao@inspur.com>

### CODE REVIEW

**Comment by liewegas** [comment]
I'm thinking about even odds that this works.  I'm suspicoius there is an ordering dependency for the flushing vs the other peering events, but I don't see it looking at the code.  Let's see how this handles the test suite!

**Comment by tchaikov** [comment]
- http://pulpito.ceph.com/kchai-2017-11-18_15:01:48-rados-wip-kefu-testing-2017-11-18-2124-distro-basic-mira/
- http://pulpito.ceph.com/kchai-2017-11-20_05:45:10-rados-wip-kefu-testing-2017-11-18-2124-distro-basic-mira/
- http://pulpito.ceph.com/kchai-2017-11-20_06:28:09-rados-wip-kefu-testing-2017-11-18-2124-distro-basic-mira/

**Comment by liewegas** [comment]
Ok, I'd like to keep this in testing limbo for several runs.  In particular, I'd like to combine it with https://github.com/ceph/ceph/pull/18752 .  The flush evt behavior dates back to 2012 so I'm a bit paranoid :)

**Comment by tchaikov** [comment]
http://pulpito.ceph.com/kchai-2017-12-01_08:15:14-rados-wip-kefu-testing-2017-12-01-1256-distro-basic-mira/

**Comment by tchaikov** [comment]
@wumingqiao needs rebase.

**Comment by wumingqiao** [comment]
@tchaikov make check failed in rocksdb??

**Comment by liewegas** [comment]
can you rebase this onto master please so that the merge commit goes away?

**Comment by wumingqiao** [comment]
@liewegas Sorry, i have met some trouble in rebasing, so reopen this pr in https://github.com/ceph/ceph/pull/19441

**Pull request closed without merging**
