### PR TITLE
qa/suites/orch: whitelist warnings that are expected in test environments

### PR DESCRIPTION
**Pull request by ljflores**
The idea here is to ignore warnings that we know are happening because of deliberate testing conditions.

An alternative to the solution proposed in https://github.com/ceph/ceph/pull/55498.

Fixes: https://tracker.ceph.com/issues/64343

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [x] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Comment by ljflores** [comment]
Here's an example link to a main test run that experienced a lot of failures due to `MON_DOWN` warnings. In these tests, this warning is expected, so it's not ideal to have them fail. Affected tests are `rados/cephadm` and `rados/thrash-old-clients`.
https://pulpito.ceph.com/yuriw-2024-02-07_00:12:44-rados-wip-yuri2-testing-2024-02-06-1154-distro-default-smithi/

Here are some test runs I scheduled with the changes applied:
`rados/cephadm`: https://pulpito.ceph.com/lflores-2024-02-08_22:34:31-rados-wip-yuri2-testing-2024-02-06-1154-distro-default-smithi/
`rados/thrash-old-clients`: https://pulpito.ceph.com/lflores-2024-02-08_22:37:00-rados-wip-yuri2-testing-2024-02-06-1154-distro-default-smithi/
Here are som

**Review by athanatos — APPROVED** [review]

**Comment by ljflores** [comment]
Still seeing errors like this in the "after" results:
```
"2024-02-08T23:08:41.185384+0000 mon.a (mon.0) 197 : cluster 3 [WRN] MON_DOWN: 1/3 mons down, quorum a,c" in cluster log
```

I think I need to whitelist `MON_DOWN` rather than `(MON_DOWN)`.

**Comment by athanatos** [comment]
Most likely.

**Comment by ljflores** [comment]
> Still seeing errors like this in the "after" results:
> 
> ```
> "2024-02-08T23:08:41.185384+0000 mon.a (mon.0) 197 : cluster 3 [WRN] MON_DOWN: 1/3 mons down, quorum a,c" in cluster log
> ```
> 
> I think I need to whitelist `MON_DOWN` rather than `(MON_DOWN)`.

New "after" results:
`rados/cephadm`: https://pulpito.ceph.com/lflores-2024-02-08_23:30:13-rados-wip-yuri2-testing-2024-02-06-1154-distro-default-smithi/
`rados/thrash-old-clients`: https://pulpito.ceph.com/lflores-2024-02-08_23:34:25-rados-wip-yuri2-testing-2024-02-06-1154-distro-default-smithi/

**Comment by markhpc** [comment]
Looked through the original test results and saw that 35 of the 54 failures were from MON_DOWN.  Laura mentioned that she looked through all of them and the other seemed to be for unrelated things so I won't dig through them as well.  I'll try to keep an eye on this run as it progresses.

**Comment by ljflores** [comment]
Latest test run: https://pulpito.ceph.com/lflores-2024-02-09_16:40:54-rados-wip-yuri2-testing-2024-02-06-1154-distro-default-smithi/

Looking to clear up instances of `OSD_DOWN` and `OSDMAP_FLAGS`.

**Comment by markhpc** [comment]
@ljflores Nice improvements!  I'm out for an hour or two, but I'll try to check in after that.  If there's anything you need to help keep things moving, please reach out.

**Comment by markhpc** [comment]
In the last run, we ignorelist both `MON_DOWN` and `OSD_DOWN` in 7554107, 7554108, and 7554109.  We also are also ignoring `\(PG_`, but I wonder if we also need to ignore `PG_AVAILABILITY` similar to the others.

**Comment by ljflores** [comment]
@markhpc yes, looks like we need `PG_DEGRADED`, `PG_AVAILABILITY`, and `POOL_APP_NOT_ENABLED` based on latest results. Making those changes..

**Comment by ljflores** [comment]
Latest runs:

https://pulpito.ceph.com/lflores-2024-02-09_19:54:56-rados-wip-yuri2-testing-2024-02-06-1154-distro-default-smithi/

**Comment by ljflores** [comment]
@markhpc latest runs passed! If all looks good to you, I think we are good to merge. I suspect a few more warnings might pop up in subsequent runs, as these failures are nondeterministic, but this PR takes care of the majority. We can always raise a part 2 to knock down any more that might arise.

**Review by markhpc — APPROVED** [review]
This looks good to me!  Just eyeballing it, I don't think any of the ignorelists here are clearly incorrect, but it's been a while since I've looked over the nuance of the different suites.  Either way, I'd take overly broad ignore-lists over the old behavior any day.

Thank you so much Laura for putting in the effort to make this happen! :muscle:

**Pull request merged**
