### PR TITLE
mgr, mgr/prometheus: Fix regression with prometheus metrics

### PR DESCRIPTION
**Pull request by pdvian**
The ceph dameons on host are inheriting ceph version from the host.
This introduces a wrong interpretation in prometheus metrics as well
as in dump_server. Each ceph daemon should represent it's own
ceph version based on the ceph binary is use for that daemon.

Consider a situation where partial upgrade is done on host, some daemons
which are restarted should have ceph version tag as upgraded version
and rest should have older ceph version but presently all inherites
host version. In containerized environment, all daemons are
using ceph version of last daemon registered as a service on the host.

Fixes: https://tracker.ceph.com/issues/54611

Signed-off-by: Prashant D <pdhange@redhat.com>

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Review by ljflores — APPROVED** [review]
Looks good @pdvian! The modifications logically make sense, and I appreciate the changes to the variable names for better clarity. This would be good to test on either the LRC or Gibba if we go through another upgrade process.

**Comment by neha-ojha** [comment]
> Looks good @pdvian! The modifications logically make sense, and I appreciate the changes to the variable names for better clarity. This would be good to test on either the LRC or Gibba if we go through another upgrade process.

Do our upgrade tests in teuthology have any coverage for this?

**Comment by pdvian** [comment]
> > > Looks good @pdvian! The modifications logically make sense, and I appreciate the changes to the variable names for better clarity. This would be good to test on either the LRC or Gibba if we go through another upgrade process.
> > 
> > 
> > Do our upgrade tests in teuthology have any coverage for this?
> 
> No. I suppose to add teuthology upgrade test for this scenario last week but failed to do so. Let me add it as earliest as possible. Thanks for reminder.

Opened #46162 to add teuthology upgrade test for this PR.

**Comment by epuertat** [comment]
@avanthakkar @pereman2 in case this be a concern for the new ceph metrics exporter.

**Pull request merged**
