### PR TITLE
jewel: rgw: backport merge of static sites fixes

### PR DESCRIPTION
**Pull request by robbat2**
Passes s3-tests including s3website suite.

Fixes: http://tracker.ceph.com/issues/15531
Fixes: http://tracker.ceph.com/issues/15532
Fixes: http://tracker.ceph.com/issues/15555
Signed-off-by: Robin H. Johnson <robin.johnson@dreamhost.com>

### CODE REVIEW

**Comment by robbat2** [comment]
Please add: milestone:jewel label:rgw

**Comment by robbat2** [comment]
@athanatos ping for your Jewel backports request; just the last commit in the set is waiting for Orit's final yay.

**Comment by dachary** [comment]
Marking as DNM because it contains a backport of a commit that is not yet merged in master ( 3c4ad75 which is in https://github.com/ceph/ceph/pull/9354 to resolve http://tracker.ceph.com/issues/15975)

**Comment by dachary** [comment]
@robbat2 if it makes sense for the individual commits to be merged independently, you can create a pull request for each of them and have them tested / merged. So that #9354 does not hold up unrelated commits.

**Comment by robbat2** [comment]
#9354 makes sense on it's own, but the rest should be grouped because they collectively fix staticsites; I'll repush this branch without #9354.

**Comment by dachary** [comment]
@robbat2 thanks :)

**Comment by robbat2** [comment]
@dachary what's blocked this from being merged? I was hoping to have it in 10.2.2 :-(

**Comment by dachary** [comment]
@robbat2 the integration test runs keep being killed, nothing passed in the last three weeks or so

**Comment by dachary** [comment]
@robbat2 assigning @yehudasa in case he feels that can be merged

**Comment by dachary** [comment]
@yehudasa does this backport look good to merge ? It passed the rgw suite http://tracker.ceph.com/issues/16344#note-6 (except for one failure which I believe to be unrelated).

**Comment by yehudasa** [comment]
@dachary we should merge these, yes

**Comment by robbat2** [comment]
Commit 46aae19eeb91bf3ac78a94c9d4812a788d9042a8 from the master branch looks to have gone missing, and needs to be in Jewel as well.

**Comment by dachary** [comment]
@robbat2 it appears to be because http://tracker.ceph.com/issues/16182 was targeting master instead of jewel. I fixed that and it will be in the next round of backport.

**Comment by dachary** [comment]
@robbat2 46aae19  has been merged as part of https://github.com/ceph/ceph/pull/10693

**Pull request merged**
