### PR TITLE
update developer and organization for Alibaba Group

### PR DESCRIPTION
**Pull request by jupiturliu**
Organization update for Alibaba
Signed-off-by: james.liu <james.liu@alibaba-inc.com>

### CODE REVIEW

**Comment by liupan1111** [comment]
@jupiturliu could you also help remove our old information in same commit? Jianjian, you, and me.

**Comment by dachary** [comment]
The outdated information at  	046f982 must stay because there are commits in the log history that need them.

**Comment by liupan1111** [comment]
@dachary ok, thanks.

**Comment by jupiturliu** [comment]
@dachary Adding back the deleted one. In the mean time, one more developer was added from Alibaba

**Comment by dachary** [comment]
could you please squash this into a single commit ?

**Comment by jupiturliu** [comment]
Sure, will do

**Pull request closed without merging**
