### PR TITLE
jewel: osd: also check if the clones' object context exists when determining whether to promote those clones

### PR DESCRIPTION
**Pull request by xxhdx1985126**
Also check if the clones' object context exists for OPs
whose snapid is CEPH_SNAPDIR in ReplicatedPG::do_op

If the incoming request's snapid is CEPH_SNAPDIR and the object context
of clones of its targeting object doesn't exist, also promote those clones

Fix: http://tracker.ceph.com/issues/17445
Signed-off-by: Xuehan Xu <xuxuehan@360.cn>

### CODE REVIEW

**Comment by tchaikov** [comment]
could you prefix the title of your commit message with the subcomponent your are changing ? see https://github.com/ceph/ceph/blob/master/SubmittingPatches.rst#3-describe-your-changes, in this case, it would be "osd: ".

and also, you need to explain why this change is not cherry-picked from master in the commit message. and the Fixes line should start with "Fixes: ", not "Fix: ". like:
```
This cannot be cherry-picked from master because ReplicatedPG::do_op() in "master" branch has been completely reconstructed.

Fixes: http://tracker.ceph.com/issues/17445
Signed-off-by: Xuehan Xu <xxhdx1985126@163.com>
```

**Comment by smithfarm** [comment]
Also, are we sure that the bug does not exist in master?

**Comment by xxhdx1985126** [comment]
@tchaikov The commit message has been changed as suggested:-)
@smithfarm Hi, I haven't test this case for the master branch. And, as the related source code has changed a lot in master, I can't judge whether this bug exists in master:-)

**Comment by smithfarm** [comment]
@xxhdx1985126 Thanks. The general idea is to fix bugs in master, first, and then backport if it makes sense to do so. The Jewel codestream will only live for a short time, while master is the source of all future releases. If a bug is fixed in Jewel only, the fix dies with Jewel dies. If a bug is fixed in master, it is fixed in all future releases (barring a regression, of course).

Here's another way of looking at it: if a bug is fixed in Jewel but not fixed in master, the bug will be present in the next stable release, and that will look like a regression.

**Comment by smithfarm** [comment]
If the code has completely changed in master, as you say, then this PR can be used as a "manual backport", but only after the bug has been fixed (or verified to not exist) in master.

**Comment by xxhdx1985126** [comment]
@smithfarm Hi, I just read the source code of master branch, and I don't think master branch has this problem. Since, in the master branch, "list-snaps"'s result has been moved from ObjectContext::obs.oi.snaps to ObjectContext::ssc.snapset.clone_snaps and the cache eviction only empty ObjectContext::obs.oi, I think even though "list-snaps" get an object context whose oi field is empty, its snapset is still valid. So, the result of "list-snaps" won't cause problems.

**Comment by xxhdx1985126** [comment]
Um... Does anyone know why the make check failed? It succeeded the first I submit the pull request. And the later submission only change commit message.....Why failed?

**Comment by gregsfortytwo** [comment]
(Although I think the issue does apply to Kraken.)

**Comment by liewegas** [comment]
I think we want this in master, too.  This 'librados clients specify snapid=snapdir when listing snaps and clones' is the last use of SNAPDIR in master, and I think this fix applies there as well.

**Comment by liewegas** [comment]
Hrm, it's been totally rewritten, though.  I'm not seeing the analogous code there. 

We should really add a test to test/librados/tier.cc that creates a the situation where not all clones are in the cache, and then do a listsnaps and asserts we get the right result.

**Comment by xxhdx1985126** [comment]
OK, I'll try to add a test case for this:-)

**Comment by xxhdx1985126** [comment]
Hi, everyone.

I'm trying to write a new test case in tier.cc. However, when I try to
test that test case by running "make check", it seems that "make
check" only run ceph_test_object_map, no other "ceph_test_XXX"
runnables are run including "ceph_test_rados_api_tier". Why? And how
to run other ceph_test_XXX runnables?

**Comment by xxhdx1985126** [comment]
Hi, everyone.

I've just add a new list-snaps test which can test whether this problem exists in master branch: https://github.com/ceph/ceph/pull/17017. And the result shows that master doesn't have the same bug.

Sorry for taking so long. I've been very busy in the past month. Please forgive me.

**Comment by smithfarm** [comment]
@xxhdx1985126 Great, please cherry-pick #17017 into this PR.

**Comment by xxhdx1985126** [comment]
Done:-)

**Comment by smithfarm** [comment]
Passed a rados suite at http://tracker.ceph.com/issues/20613#note-48 with some failures that are, I believe, unrelated.

**Comment by smithfarm** [comment]
@liewegas OK to have this in jewel? The test case has been added, and rados suite passed.

**Comment by smithfarm** [comment]
@liewegas Ping?

**Comment by liewegas** [comment]
see https://github.com/ceph/ceph/pull/17707

**Pull request closed without merging**
