### PR TITLE
librbd: allow cloning from non-user snapshots

### PR DESCRIPTION
**Pull request by idryomov**
## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [x] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Review by ajarr — APPROVED** [review]
PR looks good.

Why was  snap ID  chosen over snap name  to specify the non-user snapshot to clone from?

**Comment by idryomov** [comment]
Pushing a fixup for `ceph api`:
```
FAIL: test_clone (tasks.mgr.dashboard.test_rbd.RbdTest)
...
2024-06-11 09:08:40,762.762 INFO:__main__:Traceback (most recent call last):
2024-06-11 09:08:40,762.762 INFO:__main__:  File "/home/jenkins-build/build/workspace/ceph-api/qa/tasks/mgr/dashboard/helper.py", line 483, in assertSchema
2024-06-11 09:08:40,763.763 INFO:__main__:    return _validate_json(data, schema)
2024-06-11 09:08:40,763.763 INFO:__main__:  File "/home/jenkins-build/build/workspace/ceph-api/qa/tasks/mgr/dashboard/helper.py", line 711, in _validate_json
2024-06-11 09:08:40,763.763 INFO:__main__:    result = all(
2024-06-11 09:08:40,763.763 INFO:__main__:  File "/home/jenkins-build/build/workspace/ceph-api/qa/tasks/mgr/dashboard/helper.py", line 712, in 
2024-06-11 09:08:40,763.763 INFO:__main__:    _validate_json(val[key], sub_schema, path + [key])
2024-06-11 09:08:40,763.763 INFO:__main__:  File "/home/jenkins-build/build/workspace/ceph-api/qa/tasks/mgr/dashboard/helper.py", line 710, in _validate_json
2024-06-11 09:08:40,763.763 INFO:__main__:    raise _ValError('unknown keys: {}'.format(unknown_keys), path)
2024-06-11 09:08:40,763.763 INFO:__main__:tasks.mgr.dashboard.helper._ValError: In `input['parent']`: unknown keys: {'image_id', 'trash', 'pool_id', 'snap_id', 'snap_namespace_type'}
```

**Comment by idryomov** [comment]
> Why was snap ID chosen over snap name to specify the non-user snapshot to clone from?

The snap name by itself can be ambiguous.  Each non-user snapshot types forms its own namespace -- see "[rbd snap ls --all" output in the commit message of the last commit for an example.

The alternative to taking a snap ID would be to take an additional `snap_namespace` argument, but there is no precedent for that in the public API.

**Comment by idryomov** [comment]
jenkins test api

**Comment by idryomov** [comment]
jenkins test dashboard

**Comment by idryomov** [comment]
jenkins test dashboard

**Comment by idryomov** [comment]
No failures (`rbd/nvmeof` job isn't expected to work):

https://pulpito.ceph.com/dis-2024-06-10_19:09:24-rbd-wip-dis-testing-distro-default-smithi/
https://pulpito.ceph.com/dis-2024-06-11_07:52:38-rbd-wip-dis-testing-distro-default-smithi/
https://pulpito.ceph.com/dis-2024-06-11_10:44:00-rbd-wip-dis-testing-distro-default-smithi/

**Comment by idryomov** [comment]
jenkins test dashboard

**Comment by idryomov** [comment]
jenkins test make check

**Comment by idryomov** [comment]
@afreen23 or @aaSharma14 I'd appreciate your ack for changes to `qa/tasks/mgr/dashboard/test_rbd.py` here.

**Review by afreen23 — APPROVED** [review]

**Pull request merged**
