### PR TITLE
jewel: osd: recover_replicas: object added to missing set for backfill, but is not in recovering, error!

### PR DESCRIPTION
**Pull request by dzafman**
6cb93f7d3406efb8955770aef21e2dc791958b0a from ceph/ceph#11921
6a78b81f37fd6fb495672142fe9d135d144391c6 from ceph/ceph#11926
ceph/ceph#12170
ceph/ceph#12526
574b3cd3d416a3ba3611775f871646ab137266f5 from ceph/ceph#16709
50e08b0a5d7dc30a164313c1480b6cc829b6ec65 from ceph/ceph#17703
ceph/ceph#17920

2 commits from ceph/ceph#18145 (5 additional commits excluded until I know if we need them.)
6a02bfef3d44a13589c1a90bec29ff0ac64f97aa
b9de5eec267627c8bc5ff0759ddea6c4a8aa7bce

### CODE REVIEW

**Comment by dzafman** [comment]
Jewel doesn't pass checks: See https://github.com/ceph/ceph/pull/18692

**Comment by dzafman** [comment]
Tests passed:

http://pulpito.ceph.com/dzafman-2017-11-02_23:10:26-rados:thrash-erasure-code-wip-1508935-distro-basic-smithi/

http://pulpito.ceph.com/dzafman-2017-11-02_23:34:16-rados:thrash-erasure-code-big-wip-1508935-distro-basic-smithi

**Comment by prallabh** [comment]
@dzafman Can you please clarify if we would require https://github.com/ceph/ceph/pull/18145/commits/7f8b0ce9e681f727d8217e3ed74a1a3355f364f3 and https://github.com/ceph/ceph/pull/18145/commits/689bff354a6bfa1cf47b0d0a04fa9f1b2ef68f75 in this context? Curious to know under what scenarios would those 2 new PG states be useful. Thanks!

**Comment by dzafman** [comment]
@prallabh It would have been nice include those commits, but it would pull in too many other commits.  My initial look at this required pull requests ceph/ceph#14760 and ceph/ceph#18025 which contain a total of 39 commits before adding 7f8b0ce and 689bff3 and the rest of ceph/ceph#18145.

**Comment by smithfarm** [comment]
test this please

**Comment by dzafman** [comment]
I did run tests but still need to analyze results. 

http://pulpito.ceph.com/dzafman-2017-11-02_20:30:28-rados:thrash-wip-1508935-distro-basic-smithi/

1 failure clock sync off
9 dead

**Comment by tchaikov** [comment]
retest this please.

**Comment by dzafman** [comment]
retest this please

**Comment by smithfarm** [comment]
@dzafman @tchaikov It looks like jewel make check is back to green, which is great news. Any chance of getting your help on the jewel rados suite? 

http://tracker.ceph.com/issues/21742#note-10

(Slightly off-topic here - sorry.)

**Pull request merged**
