### PR TITLE
Filestore:: avoid apply threadpool pause when sync journal 

### PR DESCRIPTION
**Pull request by jack-changtao**
1) add a map<pthread_t,atomic64_t> applying_seq  to record the seq applying in a thread

2) when sync journal, if applying_seq map is empty, use max_applied_seq as current sync_seq, else
use  min_seq-1 of current applying thread as  current sync_seq

3) For parallel journal, journal commit and journal apply operations are executed in parallel. Journal commit operation may leg behind of journal applied operation,so when journal sync,  get min of journaled_seq and applyed_seq as sync_seq

### CODE REVIEW

**Comment by jack-changtao** [comment]
@liewegas  @yuyuyu101  @XinzeChi  

please have time to review this PR, is it make sence ? Thanks very much!

**Comment by jack-changtao** [comment]
@liewegas @yuyuyu101 @XinzeChi please have time to review this PR, ? Thanks very much!

**Comment by xiaoxichen** [comment]
mark

**Comment by athanatos** [comment]
I'm reluctant to change much of anything in FileStore at this point.  Do you have numbers indicating how much of a difference it actually makes?

**Comment by jack-changtao** [comment]
@yuyuyu101 
I have no environment to test it! Do you have some intertest to this commit ? You can push it, you cab do it anything at you will ! Thanks very much!

**Comment by xiaoxichen** [comment]
This is something "technically works", waiting for testing data. @jack-changtao , if you willing to do and environment is the problem you can ping @markhpc about the community lab

**Comment by yuyuyu101** [comment]
it depends ...

**Comment by markhpc** [comment]
If you would like access to the sepia lab for running teuthology tests, the instructions are here:

http://ceph.github.io/sepia/adding_users/

I tend to agree with Sam though.  We want to keep filestore stable at this point as we transition to bluestore unless there is a really clear big win.

**Comment by athanatos** [comment]
It doesn't look like anyone is generating numbers for this one, so I'm going to close it for now.  If someone wants to do the leg work to quantify the improvement, it can be reopened (a good first step would be using ceph_smalliobenchfs locally).

**Pull request closed without merging**
