### PR TITLE
quincy: ceph-exporter: cephadm changes

### PR DESCRIPTION
**Pull request by adk3798**
Fixes: https://tracker.ceph.com/issues/55046
Signed-off-by: Avan Thakkar <athakkar@redhat.com>

Includes changes required for introducing ceph-exporter container in cephadm.

(cherry picked from commit 0253053dbfb1e98d38cf2f522751d2a4c780adc0)

Conflicts:
	src/pybind/mgr/cephadm/module.py
	src/pybind/mgr/cephadm/service_discovery.py
	src/pybind/mgr/cephadm/services/cephadmservice.py
	src/pybind/mgr/cephadm/services/monitoring.py
	src/pybind/mgr/cephadm/tests/test_services.py
	src/python-common/ceph/deployment/service_spec.py

Pretty heavy merge conflicts and required changes in this backport. Had to convert the prometheus parts from the service discovery back to static configs setup since we don't use service discovery in quincy. Was able to get it so prometheus seemed to be scraping the ceph-exporter endpoints alright in testing.

image

There's a weird bit with one of the host's FQDN coming out as "host.containers.internal" but that's unrelated to this change.

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [x] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [x] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by avanthakkar** [comment]
jenkins test dashboard cephadm

**Review by avanthakkar — APPROVED** [review]
LGTM! Thanks @adk3798 for taking care of backport.

**Review by jmolmo — APPROVED** [review]
LGTM

**Comment by adk3798** [comment]
https://pulpito.ceph.com/adking-2023-02-15_21:05:54-orch:cephadm-wip-adk3-testing-2023-02-15-0956-quincy-distro-default-smithi/

1 failure in test_cephadm task due to mistake in another PR that made task bootstrap with main image rather than quincy.

1 dead job in nfs-ingress test due to failure to re-image machine. Other nfs-ingress  tests in the run passed okay so didn't bother with rerun.

**Comment by idryomov** [comment]
This caused a regression and getting backed out in https://github.com/ceph/ceph/pull/51053.

**Pull request merged**
