### PR TITLE
octopus: ceph-volume: prepare: use *-slots arguments for implicit sizing

### PR DESCRIPTION
**Pull request by jan--f**
backport tracker: https://tracker.ceph.com/issues/48304

---

backport of https://github.com/ceph/ceph/pull/33787
parent tracker: https://tracker.ceph.com/issues/44494

this backport was staged using ceph-backport.sh version 15.1.1.389
find the latest version at https://github.com/ceph/ceph/blob/master/src/script/ceph-backport.sh

### CODE REVIEW

**Comment by rishabh-d-dave** [comment]
jenkins test ceph-volume tox

**Comment by rishabh-d-dave** [comment]
jenkins test ceph-volume all

**Comment by rishabh-d-dave** [comment]
@jan--f I don't understand what do you mean by "pick ours" in first commit. Perhaps it would be better to elaborate it.

**Comment by smithfarm** [comment]
jenkins test api

**Comment by smithfarm** [comment]
jenkins test make check

**Review by yuriw — APPROVED** [review]

**Pull request merged**
