### PR TITLE
test: Use grep -E variant to be more generic and update some patterns

### PR DESCRIPTION
**Pull request by dzafman**
Fixes: http://tracker.ceph.com/issues/35845

Signed-off-by: David Zafman <dzafman@redhat.com>

- [x] References tracker ticket

### CODE REVIEW

**Comment by dzafman** [comment]
Testing PASSED
http://pulpito.ceph.com/dzafman-2018-09-07_18:07:43-rados-wip-35845-distro-basic-smithi/

The problem was seen on Mimic, but this passes master on the same distribution Ubuntu 16.04

**Comment by dzafman** [comment]
Now I'm not sure why this is passing on my build machine which is Ubuntu 16.04 but not on a teuthology test machine unless my machine needs updating or someone is picking up a different version of grep.

**Comment by liewegas** [comment]
retest this please

**Comment by dzafman** [comment]
I found the real problem will close and open a different pull request.

**Pull request closed without merging**
