### PR TITLE
common/options: change default erasure-code-profile to k=2 m=2

### PR DESCRIPTION
**Pull request by liewegas**
Signed-off-by: Sage Weil <sage@redhat.com>

### CODE REVIEW

**Comment by liewegas** [comment]
@emmericp how about this?

**Comment by dzafman** [comment]
@liewegas I see more places that use k=2 m=1.

$ git grep -l "k=2 m=1" .. | grep -v "options.cc\|osd-erasure-code-profile.sh"
../doc/releases/luminous.rst
../qa/erasure-code/ec-feature-plugins-v3.yaml
../qa/standalone/crush/crush-classes.sh
../qa/standalone/erasure-code/test-erasure-code.sh
../qa/standalone/osd/osd-backfill-stats.sh
../qa/standalone/osd/osd-recovery-stats.sh
../qa/standalone/scrub/osd-scrub-repair.sh
../qa/standalone/special/ceph_objectstore_tool.py
../qa/tasks/ceph.conf.template
../qa/workunits/cephtool/test.sh
../qa/workunits/rados/test_alloc_hint.sh
../qa/workunits/rados/test_rados_tool.sh
../src/vstart.sh

**Comment by liewegas** [comment]
> we should also update the mentions of default erasure code profile in doc/rados/operations/erasure-code.rst and rados/operations/erasure-code-lrc.rst

updated!

**Comment by neha-ojha** [comment]
> we should also update the mentions of default erasure code profile in doc/rados/operations/erasure-code.rst and rados/operations/erasure-code-lrc.rst
> updated!

looks good, doc/dev/erasure-coded-pool.rst needs an update too.

**Pull request merged**
