### PR TITLE
osd: Sign in early SIGHUP signal

### PR DESCRIPTION
**Pull request by renhwztetecs**
In the process of starting the osd process,if system just call the
logratote("killall -q -1 ceph-mon ceph-mgr ceph-mds ceph-osd ceph-fuse radosgw...")
it will cause osd'init failed to start,
in addition, osd init slower than before, will increase the chances of the error.
Other modules(mon\mds\mgr...) also have type problems, but the most serious osd problem,
I can then make other modules similar changes.

Signed-off-by: huanwen ren <ren.huanwen@zte.com.cn>

### CODE REVIEW

**Comment by tchaikov** [comment]
makes sense to me. might need to update the commit message to note down the rationale of the change, also the point of moving the calls to register the sighandler is to register the SIGHUP before the first blocking call, which is, `OSD::peek_meta()` i guess.

**Comment by renhwztetecs** [comment]
@tchaikov 
thank you, I add Fixes: http://tracker.ceph.com/issues/22746 in the commit info

**Comment by renhwztetecs** [comment]
@tchaikov 
maybe need to be placed after g_ceph_context is initialized, before new osd, as it is now.
ping @jcsp

**Comment by jcsp** [comment]
Yep, seems sensible that these calls should come right after common_init_finish

**Comment by tchaikov** [comment]
- http://pulpito.ceph.com/kchai-2018-02-01_09:17:08-rados-wip-kefu-testing-2018-02-01-1258-distro-basic-mira/
- http://pulpito.ceph.com/kchai-2018-02-02_05:30:30-rados-wip-kefu-testing-2018-02-01-1258-distro-basic-mira/

**Comment by tchaikov** [comment]
@renhwztetecs as we discussed, this change also applies to other daemons of ceph whose log messages are logroated. do you want to do it in this PR, or leave it for future? i am good either way =)

**Comment by renhwztetecs** [comment]
@tchaikov 
ok ,I will add other in this PR.

**Comment by renhwztetecs** [comment]
added it

**Comment by tchaikov** [comment]
http://pulpito.ceph.com/kchai-2018-02-07_01:22:25-rados-wip-kefu-testing-2018-02-06-1514-distro-basic-mira/

**Pull request merged**
