### PR TITLE
msg/async: reset the V1's session_security in proper EventCenter.

### PR DESCRIPTION
**Pull request by rzarzynski**
Fixes: https://tracker.ceph.com/issues/43070
Signed-off-by: Radoslaw Zarzynski <rzarzyns@redhat.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by tchaikov** [comment]
jenkins test make check

**Comment by tchaikov** [comment]
- http://pulpito.ceph.com/kchai-2019-12-21_03:01:01-rados-wip-kefu-testing-2019-12-21-0133-distro-basic-mira/
- http://pulpito.ceph.com/kchai-2019-12-23_16:20:31-rados-wip-kefu-testing-2019-12-21-0133-distro-basic-smithi/

failures tracked by

- https://tracker.ceph.com/issues/43396
- https://tracker.ceph.com/issues/43415
- https://tracker.ceph.com/issues/43414
- https://tracker.ceph.com/issues/43416
- https://tracker.ceph.com/issues/43394

**Comment by tchaikov** [comment]
jenkins test make check

**Comment by tchaikov** [comment]
```
190/191 Test  #15: smoke.sh ................................***Timeout 3600.07 sec
```

```
in thread 7f5f7046f700 thread_name:msgr-worker-0
 ceph version Development (no_version) octopus (dev)
 1: (()+0xd17b70) [0x562025f64b70]
 2: (()+0x12890) [0x7f5f7473c890]
 3: (operator<<(std::ostream&, entity_addr_t const&)+0x15) [0x7f5f76f1fa6d]
 4: (std::ostream& std::operator<< <entity_addr_t, std::allocator<entity_addr_t> >(std::ostream&, std::vector<entity_addr_t, std::allocator<entity_addr_t> > const&)+0xb6) [0x7f5f76d8c082]
 5: (operator<<(std::ostream&, entity_addrvec_t const&)+0x75) [0x7f5f76d8b7f4]
 6: (ProtocolV1::_conn_prefix(std::ostream*)+0x42) [0x7f5f76f46982]
 7: (()+0x18b0802) [0x7f5f76f54802]
 8: (()+0x18c2f90) [0x7f5f76f66f90]
 9: (EventCenter::process_events(unsigned int, std::chrono::duration<unsigned long, std::ratio<1l, 1000000000l> >*)+0x932) [0x7f5f76fabc20]
 10: (()+0x1914694) [0x7f5f76fb8694]
 11: (()+0x1915b6a) [0x7f5f76fb9b6a]
 12: (std::function<void ()>::operator()() const+0x32) [0x7f5f76fb7f8e]
 13: (void std::__invoke_impl<void, std::function<void ()>>(std::__invoke_other, std::function<void ()>&&)+0x20) [0x7f5f76fb7f3e]
 14: (std::__invoke_result<std::function<void ()>>::type std::__invoke<std::function<void ()>>(std::function<void ()>&&)+0x20) [0x7f5f76fb7ef3]
 15: (void std::thread::_Invoker<std::tuple<std::function<void ()> > >::_M_invoke<0ul>(std::_Index_tuple<0ul>)+0x28) [0x7f5f76fb7ea0]
 16: (std::thread::_Invoker<std::tuple<std::function<void ()> > >::operator()()+0x18) [0x7f5f76fb7e76]
 17: (std::thread::_State_impl<std::thread::_Invoker<std::tuple<std::function<void ()> > > >::_M_run()+0x1c) [0x7f5f76fb7e5a]
 18: (()+0xd0870) [0x7f5f7441a870]
 19: (()+0x76db) [0x7f5f747316db]
 20: (clone()+0x3f) [0x7f5f73ac488f]
2019-12-24T06:05:36.488+0000 7f5f7046f700 -1 *** Caught signal (Segmentation fault) **
 in thread 7f5f7046f700 thread_name:msgr-worker-0
```

in

**Comment by tchaikov** [comment]
jenkins test make check

**Comment by tchaikov** [comment]
jenkins test make check

**Comment by tchaikov** [comment]
@rzarzynski seems the failure is reproducible. could you take a look?

**Comment by rzarzynski** [comment]
@tchaikov: will take a look just after the Epiphany holiday (which is today in Europe). DNM for now.

**Comment by rzarzynski** [comment]
The fix depends on #32732.

**Comment by tchaikov** [comment]
- http://pulpito.ceph.com/kchai-2020-01-25_04:55:56-rados-wip-kefu-testing-2020-01-25-0051-distro-basic-smithi/
- http://pulpito.ceph.com/kchai-2020-01-24_02:23:44-rados-wip-kefu-testing-2020-01-23-2212-distro-basic-smithi/

failures tracked by 

- https://tracker.ceph.com/issues/43703
- https://tracker.ceph.com/issues/43653
- https://tracker.ceph.com/issues/36353

**Pull request merged**
