### PR TITLE
NVMEDevice: fix bug in data_buf_next_sge

### PR DESCRIPTION
**Pull request by optimistyzy**
Also leverage spdk_zmalloc

Signed-off-by: optimistyzy <optimistyzy@gmail.com>

### CODE REVIEW

**Comment by yuyuyu101** [comment]
I think this is a refactor instead of bug?

**Comment by liupan1111** [comment]
@yuyuyu101, osd cannot be invoked without this change. We download The change and try, find it works well now.

**Comment by yuyuyu101** [comment]
@optimistyzy could we update the commit message about why original codes matters?

**Comment by optimistyzy** [comment]
@yuyuyu101 updated.

**Comment by yuyuyu101** [comment]
thanks

**Pull request merged**
