### PR TITLE
librbd: mirror image enable/disable should enable/disable journaling

### PR DESCRIPTION
**Pull request by trociny**
Fixes: https://tracker.ceph.com/issues/40071
Signed-off-by: Mykola Golub <mgolub@suse.com>

- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by trociny** [comment]
@dillaman It is only slightly tested. I would like to discuss though what to do with the exclusive lock feature. Right now if it is not enabled I enable it too (instead of returning an error), which looks ok to me. But when disabling mirroring, should I disable the exclusive lock too, if there are no other features that depend on it. This is what my current code does, but I am not sure it is a good idea.

Usually the "exclusive lock" is added as auxiliary feature to object map or journaling, but there are cases when user would enable "exclusive lock" feature explicitly and would be unpleasantly surprised if it was implicitly disabled. On the other hand leaving "exclusive lock" after disabling mirroring if the user did not enabled it explicitly does look good to (though seems to be a little better).

**Comment by dillaman** [comment]
@trociny I'd vote to just leave the exclusive-lock feature enabled when disabling mirroring.

**Comment by trociny** [comment]
@dillaman updated

**Comment by dillaman** [comment]
retest this please

**Pull request merged**
