### PR TITLE
mgr/restful: allow shutdown before we've fully started up

### PR DESCRIPTION
**Pull request by liewegas**

### CODE REVIEW

**Comment by callithea** [comment]
jenkins test dashboard backend

**Comment by callithea** [comment]
Hm, the dashboard backend tests failed with:
```2019-12-04 14:27:26,024.024 INFO:__main__:Found ps line for daemon: 13953 ?        Ssl    5:02 ./bin/./ceph-mgr -i y
2019-12-04 14:27:27,025.025 INFO:__main__:Running ['ps', 'ww', '-u1001']
2019-12-04 14:27:27,046.046 INFO:__main__:Found ps line for daemon: 13953 ?        Ssl    5:03 ./bin/./ceph-mgr -i y
2019-12-04 14:27:28,047.047 INFO:__main__:Running ['ps', 'ww', '-u1001']
2019-12-04 14:27:28,063.063 INFO:__main__:Found ps line for daemon: 13953 ?        Ssl    5:04 ./bin/./ceph-mgr -i y
2019-12-04 14:27:29,064.064 INFO:__main__:Running ['ps', 'ww', '-u1001']
2019-12-04 14:27:29,081.081 INFO:__main__:Found ps line for daemon: 13953 ?        Ssl    5:05 ./bin/./ceph-mgr -i y
2019-12-04 14:27:30,082.082 INFO:__main__:Running ['ps', 'ww', '-u1001']
2019-12-04 14:27:30,096.096 INFO:__main__:Found ps line for daemon: 13953 ?        Ssl    5:06 ./bin/./ceph-mgr -i y
2019-12-04 14:27:31,097.097 INFO:__main__:Running ['ps', 'ww', '-u1001']
2019-12-04 14:27:31,114.114 INFO:__main__:Found ps line for daemon: 13953 ?        Ssl    5:07 ./bin/./ceph-mgr -i y
2019-12-04 14:27:32,115.115 INFO:__main__:Running ['ps', 'ww', '-u1001']
2019-12-04 14:27:32,132.132 INFO:__main__:Found ps line for daemon: 13953 ?        Ssl    5:08 ./bin/./ceph-mgr -i y
2019-12-04 14:27:33,133.133 INFO:__main__:Running ['ps', 'ww', '-u1001']
2019-12-04 14:27:33,151.151 INFO:__main__:Found ps line for daemon: 13953 ?        Ssl    5:09 ./bin/./ceph-mgr -i y
2019-12-04 14:27:34,151.151 INFO:__main__:Running ['ps', 'ww', '-u1001']
2019-12-04 14:27:34,166.166 INFO:__main__:Found ps line for daemon: 13953 ?        Ssl    5:10 ./bin/./ceph-mgr -i y
2019-12-04 14:27:35,167.167 INFO:__main__:Running ['ps', 'ww', '-u1001']
2019-12-04 14:27:35,184.184 INFO:__main__:Found ps line for daemon: 13953 ?        Ssl    5:11 ./bin/./ceph-mgr -i y
2019-12-04 14:27:36,185.185 INFO:__main__:Running ['ps', 'ww', '-u1001']
2019-12-04 14:27:36,207.207 INFO:__main__:Found ps line for daemon: 13953 ?        Ssl    5:12 ./bin/./ceph-mgr -i y
2019-12-04 14:27:37,208.208 INFO:__main__:Running ['ps', 'ww', '-u1001']
2019-12-04 14:27:37,226.226 INFO:__main__:Found ps line for daemon: 13953 ?        Ssl    5:13 ./bin/./ceph-mgr -i y
2019-12-04 14:27:37,228.228 INFO:__main__:ERROR
2019-12-04 14:27:37,228.228 INFO:__main__:
2019-12-04 14:27:37,228.228 INFO:__main__:======================================================================
2019-12-04 14:27:37,228.228 INFO:__main__:ERROR: setUpClass (tasks.mgr.dashboard.test_cluster_configuration.ClusterConfigurationTest)
2019-12-04 14:27:37,229.229 INFO:__main__:----------------------------------------------------------------------
2019-12-04 14:27:37,229.229 INFO:__main__:Traceback (most recent call last):
2019-12-04 14:27:37,229.229 INFO:__main__:  File "/home/jenkins-build/build/workspace/ceph-dashboard-pr-backend/qa/tasks/mgr/dashboard/helper.py", line 112, in setUpClass
2019-12-04 14:27:37,229.229 INFO:__main__:    super(DashboardTestCase, cls).setUpClass()
2019-12-04 14:27:37,229.229 INFO:__main__:  File "/home/jenkins-build/build/workspace/ceph-dashboard-pr-backend/qa/tasks/mgr/mgr_test_case.py", line 104, in setUpClass
2019-12-04 14:27:37,229.229 INFO:__main__:    cls.setup_mgrs()
2019-12-04 14:27:37,229.229 INFO:__main__:  File "/home/jenkins-build/build/workspace/ceph-dashboard-pr-backend/qa/tasks/mgr/mgr_test_case.py", line 66, in setup_mgrs
2019-12-04 14:27:37,230.230 INFO:__main__:    daemon.stop()
2019-12-04 14:27:37,230.230 INFO:__main__:  File "../qa/tasks/vstart_runner.py", line 443, in stop
2019-12-04 14:27:37,230.230 INFO:__main__:    self.daemon_type, self.daemon_id))
2019-12-04 14:27:37,230.230 INFO:__main__:MaxWhileTries: Timed out waiting for daemon mgr.y
2019-12-04 14:27:37,230.230 INFO:__main__:
2019-12-04 14:27:37,230.230 INFO:__main__:----------------------------------------------------------------------
2019-12-04 14:27:37,231.231 INFO:__main__:Ran 24 tests in 582.776s
2019-12-04 14:27:37,231.231 INFO:__main__:
2019-12-04 14:27:37,231.231 INFO:__main__:FAILED (errors=1)
2019-12-04 14:27:37,231.231 INFO:__main__:
2019-12-04 14:27:37,231.231 INFO:__main__:======================================================================
2019-12-04 14:27:37,231.231 INFO:__main__:ERROR: setUpClass (tasks.mgr.dashboard.test_cluster_configuration.ClusterConfigurationTest)
2019-12-04 14:27:37,232.232 INFO:__main__:----------------------------------------------------------------------
2019-12-04 14:27:37,232.232 INFO:__main__:Traceback (most recent call last):
2019-12-04 14:27:37,232.232 INFO:__main__:  File "/home/jenkins-build/build/workspace/ceph-dashboard-pr-backend/qa/tasks/mgr/dashboard/helper.py", line 112, in setUpClass
2019-12-04 14:27:37,232.232 INFO:__main__:    super(DashboardTestCase, cls).setUpClass()
2019-12-04 14:27:37,232.232 INFO:__main__:  File "/home/jenkins-build/build/workspace/ceph-dashboard-pr-backend/qa/tasks/mgr/mgr_test_case.py", line 104, in setUpClass
2019-12-04 14:27:37,232.232 INFO:__main__:    cls.setup_mgrs()
2019-12-04 14:27:37,232.232 INFO:__main__:  File "/home/jenkins-build/build/workspace/ceph-dashboard-pr-backend/qa/tasks/mgr/mgr_test_case.py", line 66, in setup_mgrs
2019-12-04 14:27:37,232.232 INFO:__main__:    daemon.stop()
2019-12-04 14:27:37,233.233 INFO:__main__:  File "../qa/tasks/vstart_runner.py", line 443, in stop
2019-12-04 14:27:37,233.233 INFO:__main__:    self.daemon_type, self.daemon_id))
2019-12-04 14:27:37,233.233 INFO:__main__:MaxWhileTries: Timed out waiting for daemon mgr.y```

**Comment by runsisi** [comment]
i am wondering why should we need both `restful` and `dashboard` ? .. the community should concentrate on one of them and do it better :)

**Comment by callithea** [comment]
I applied this patch to my local system and was able to reproduce the failure.
https://gist.github.com/callithea/8ca13dbf7257c3b79df6f596d8ce5b64
@liewegas please let me know if you need other logs as well.

**Comment by liewegas** [comment]
I think we should fix this issue regardless... does this fix look correct?

**Pull request merged**
