### PR TITLE
mimic: cephfs: ceph-fuse client can't read or write due to backward cap_gen

### PR DESCRIPTION
**Pull request by jonsger**
http://tracker.ceph.com/issues/36463

### CODE REVIEW

**Comment by yuriw** [comment]
[wip-yuri3-testing-2018-11-16-1727-mimic](https://trello.com/c/d2JXs5ik/475-wip-yuri3-testing-2018-11-16-1727-mimic)

**Comment by ukernel** [comment]
don't merge this. The original commit may have issue

**Comment by smithfarm** [comment]
@vshankar @yuriw Did you guys see @ukernel's comment https://github.com/ceph/ceph/pull/25091#issuecomment-439614608 ?

**Comment by smithfarm** [comment]
@ukernel Should we revert this?

**Comment by ukernel** [comment]
I reverted it

**Comment by vshankar** [comment]
> @vshankar @yuriw Did you guys see @ukernel's comment [#25091 (comment)](https://github.com/ceph/ceph/pull/25091#issuecomment-439614608) ?

I mentioned it here: https://trello.com/c/d2JXs5ik/475-wip-yuri3-testing-2018-11-16-1727-mimic

but didn't add DNM tag to the PR.

**Pull request merged**
