### PR TITLE
octopus: bluestore: mempool's finer granularity + adding missed structs

### PR DESCRIPTION
**Pull request by ifed01**
Fixes: https://tracker.ceph.com/issues/47668

Signed-off-by: Igor Fedotov <ifedotov@syse.com>

## Checklist
- [x] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by smithfarm** [comment]
jenkins test api

**Comment by smithfarm** [comment]
jenkins test api

**Review by aclamk — APPROVED** [review]
Yep, seems ok.

**Review by ideepika — APPROVED** [review]
lgtm! thanks @ifed01 !

**Comment by yuriw** [comment]
[wip-yuri5-testing-2020-09-29-0919-octopus](https://trello.com/c/kGYaCHPv/1026-wip-yuri5-testing-2020-09-29-0919-octopus)

**Pull request merged**
