### PR TITLE
qa/suites: do not test luminous-x upgrade path

### PR DESCRIPTION
**Pull request by tchaikov**
in this change,

* suites/rados/upgrade: luminous-x-singleton => mimic-x-singleton
* suites/upgrade: luminous-x => nautilus-x

we support upgrade from n to n+2 release. otherwise monitor refuses to
do so:

mon.a@-1(probing) e1 current monmap has min_mon_release 15 (luminous)
which is >2 releases older than me 15 (octopus), stopping.

Signed-off-by: Kefu Chai <kchai@redhat.com>

- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by tchaikov** [comment]
i found following failures
```
2019-03-22T04:38:27.387 INFO:teuthology.orchestra.run.mira041:> sudo adjust-ulimits ceph-coverage /home/ubuntu/cephtest/archive/coverage timeout 120 ceph --cluster ceph -- tell 'mon.*' injectargs --mon_health_to_clog=true
2019-03-22T04:38:27.498 INFO:tasks.ceph.mon.a.mira041.stderr:2019-03-22 04:38:27.497 7f6b52006e80 -1 mon.a@-1(probing) e1 current monmap has min_mon_release 15 (luminous) which is >2 releases older than me 15 (octopus), stopping.
2019-03-22T04:38:27.575 INFO:tasks.ceph.mon.b.mira058.stderr:2019-03-22 04:38:27.570 7f67b3a8ae80 -1 mon.b@-1(probing) e1 current monmap has min_mon_release 15 (luminous) which is >2 releases older than me 15 (octopus), stopping.
2019-03-22T04:40:27.467 DEBUG:teuthology.orchestra.run:got remote process result: 124
```

in http://pulpito.ceph.com/kchai-2019-03-22_03:22:17-rados-wip-kefu-testing-2019-03-21-0010-distro-basic-mira/3758401/

**Comment by neha-ojha** [comment]
@tchaikov Here's the tracker issue for this https://tracker.ceph.com/issues/38845.

**Comment by tchaikov** [comment]
changelog

- added "Fixes:" line in the commit message.

**Comment by yuriw** [comment]
I also think we need to clean up tests so we don't have suite duplicates, like for example for `luminous-x` suite:

https://github.com/ceph/ceph/tree/mimic/qa/suites/upgrade 
and 
https://github.com/ceph/ceph/tree/master/qa/suites/upgrade

The logic I see is:

`-x` suite is always on the `next` release branch, e.g.:

`luminous-x` on 'mimic'
'mimic-x' on `nautilus`
`nautilus-x` on `master` (future `octopus`)

**Comment by liewegas** [comment]
> `-x` suite is always on the `next` release branch, e.g.:
> 
> `luminous`

The -x is whatever branch you're running it on.. i.e. the branch you're in.   Maybe these would be less confusingly named from-mimic isntead of mimic-x, from-luminous instead of luminous-x, etc.  The mimic branch needs luminous-x, nautilius branch needs luminous-x *and* mimic-x, and master branch needs mimic-x and nautilus-x.

**Pull request merged**
