### PR TITLE
nautilus: rgw: beast: multiple v4 and v6 endpoints with the same port will cause failure

### PR DESCRIPTION
**Pull request by pdvian**
http://tracker.ceph.com/issues/39746

### CODE REVIEW

**Comment by smithfarm** [comment]
```
169/171 Test #126: mgr-dashboard-frontend-unittests ........***Failed  596.03 sec
```

**Comment by smithfarm** [comment]
@theanalyst Could you look at this "make check" failure? I suspect there is a separate test fix that needs to be cherry-picked in.

**Comment by theanalyst** [comment]
not really sure what has caused this, doesn't look related to this changeset, as rgw probably wasn't running in the tests

**Comment by theanalyst** [comment]
jenkins test this please

**Comment by theanalyst** [comment]
For the record, this was the e2e failure 
```
.........
  ● TableComponent › after useData › should prevent propagation of mouseenter event

    Timeout - Async callback was not invoked within the 5000ms timeout specified by jest.setTimeout.

      88 |     });
      89 | 
    > 90 |     it('should prevent propagation of mouseenter event', (done) => {
         |     ^
      91 |       fixture.detectChanges();
      92 |       const mouseEvent = new MouseEvent('mouseenter');
      93 |       mouseEvent.stopPropagation = () => done();

      at Spec (node_modules/jest-jasmine2/build/jasmine/Spec.js:92:20)
      at env.(anonymous function) (node_modules/jest-zone-patch/index.js:87:27)
      at src/app/shared/datatable/table/table.component.spec.ts:90:5
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invoke (node_modules/zone.js/dist/zone.js:391:26)
      at Zone.Object.<anonymous>.Zone.run (node_modules/zone.js/dist/zone.js:150:43)
      at Suite.<anonymous> (node_modules/jest-zone-patch/index.js:39:40)
      at env.(anonymous function) (node_modules/jest-zone-patch/index.js:69:27)
      at src/app/shared/datatable/table/table.component.spec.ts:58:3
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invoke (node_modules/zone.js/dist/zone.js:391:26)
      at Zone.Object.<anonymous>.Zone.run (node_modules/zone.js/dist/zone.js:150:43)
      at Suite.<anonymous> (node_modules/jest-zone-patch/index.js:39:40)
      at env.(anonymous function) (node_modules/jest-zone-patch/index.js:69:27)
      at Object.<anonymous> (src/app/shared/datatable/table/table.component.spec.ts:13:1)

.................................................................................................................................................................................................

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ceph-dashboard@0.0.0 test:ci: `npm run test:config && JEST_SILENT_REPORTER_DOTS=true jest --coverage --reporters jest-silent-reporter`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ceph-dashboard@0.0.0 test:ci script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/jenkins-build/.npm/_logs/2019-06-14T03_28_33_979Z-debug.log
Linting "ceph-dashboard"...
```

**Comment by theanalyst** [comment]
passed on rerun

**Comment by smithfarm** [comment]
@theanalyst Thanks

**Comment by yuriw** [comment]
[wip-yuri6-testing-2019-06-16-1630-nautilus](https://trello.com/c/1dNzQfkJ/644-wip-yuri6-testing-2019-06-16-1630-nautilus)

**Pull request merged**
