### PR TITLE
rbd: recognize rxbounce map option

### PR DESCRIPTION
**Pull request by idryomov**
## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [x] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [x] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by idryomov** [comment]
make check is blocked on https://github.com/ceph/ceph/pull/44832

**Comment by idryomov** [comment]
https://pulpito.ceph.com/dis-2022-01-31_14:22:06-krbd-wip-krbd-rxbounce-option-testing-default-smithi/

**Review by ideepika — APPROVED** [review]
lgtm! Just a question, should we be also testing facets with new rbd default map options?

**Comment by idryomov** [comment]
I'm not sure what you mean by new rbd default map options.  "rxbounce" is new, but it isn't default.

**Comment by ideepika** [comment]
> I'm not sure what you mean by new rbd default map options. `rxbounce` is new, but it isn't default.

I meant some facets of `qa/suites/krbd/basic/ms_mode`, I think you are already run one ;-)
https://pulpito.ceph.com/dis-2022-01-31_14:22:52-krbd-wip-krbd-rxbounce-option-testing-default-smithi/

**Comment by idryomov** [comment]
Ah, you mean whether the entire test suite should be run?  Of course it should be ;)  I just linked the new test while chasing down some most likely unrelated failures.

**Comment by ideepika** [comment]
jenkins test make check please

**Comment by idryomov** [comment]
Tweaked the man page.

**Pull request merged**
