### PR TITLE
osd: reduce rados_max_object_size from 100 GB -> 128 MB

### PR DESCRIPTION
**Pull request by liewegas**
I'm not sure why we had this so huge!  128 MB is a pretty reasonable size.

qa
- [x] rados

### CODE REVIEW

**Comment by gregsfortytwo** [comment]
We should be cautious about this. We already (separately) limit the size of a write to 100MB, which will stop naive users from doing something inappropriate, and I seem to recall 128MB is the default Hadoop chunk these days. I think some (admittedly odd) users have wanted sparse objects of small size but very large offsets, which this would prevent.
Why so small an object for the default? (I'm not sure about deep scrub, but recovery works in sub-chunks of separately-configured size and ought to handle much larger ones just fine).

**Comment by liewegas** [comment]
http://pulpito.ceph.com/sage-2017-06-06_21:54:14-rados-wip-sage-testing-distro-basic-smithi/

**Comment by liewegas** [comment]
Recovery and scrub do small IOs, but they block requests at object granularity, so it still interrupts service.  This is similar to why big rgw index objects are so problematic.  :(

**Comment by jdurgin** [comment]
This is a default. It can always be changed for crazy use cases. I'm happy with 128MB. Even 64 or 32 would likely be fine for the vast majority of users.

**Comment by jcsp** [comment]
Mentioning this in the cephfs docs too https://github.com/ceph/ceph/pull/15550 for benefit of anyone who  tries to set their stripe size too high and hits this limit.

**Comment by gregsfortytwo** [comment]
Fair enough, I'm on board. :)

**Pull request merged**
