### PR TITLE
rgw: When finding bucket owner info, handle account name being empty

### PR DESCRIPTION
**Pull request by vedanshbhartia**
## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [x] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by yuvalif** [comment]
this seems to be introduced by zipper 10 commit: 72d1a36
but before that there were no restrictios on whether the "account_name" is empty or not.

@dang do you think this is the right solution or should be fetch the user even if the account name is empty?

**Comment by dang** [comment]
I tend to agree.  I think a better solution would be something like this:

`diff --git a/src/rgw/rgw_rest_swift.cc b/src/rgw/rgw_rest_swift.cc
index dc28b77090a..11e7c647c7d 100644
--- a/src/rgw/rgw_rest_swift.cc
+++ b/src/rgw/rgw_rest_swift.cc
@@ -2081,6 +2081,7 @@ void RGWFormPost::get_owner_info(const req_state* const s,
   const string& bucket_name = s->init_state.url_bucket;
 
   std::unique_ptr<rgw::sal::User> user;
+  std::string bucket_tenant;
 
   /* TempURL in Formpost only requires that bucket name is specified. */
   if (bucket_name.empty()) {
@@ -2108,11 +2109,13 @@ void RGWFormPost::get_owner_info(const req_state* const s,
        throw -EPERM;
       }
     }
+
+    bucket_tenant = user->get_tenant();
   }
 
   /* Need to get user info of bucket owner. */
   std::unique_ptr<rgw::sal::Bucket> bucket;
-  int ret = driver->get_bucket(s, user.get(), user->get_tenant(), bucket_name, &bucket, s->yield);
+  int ret = driver->get_bucket(s, user.get(), bucket_tenant, bucket_name, &bucket, s->yield);
   if (ret < 0) {
     throw ret;
   }
`

**Comment by dang** [comment]
<sigh>  That didn't paste well, and github won't let me attach a patch.   Try this: https://gist.github.com/dang/9eed70d1ebc2bf3c7562cb7f6f38d430

**Comment by yuvalif** [comment]
jenkins test make check

**Review by dang — APPROVED** [review]

**Comment by yuvalif** [comment]
jenkins test make check

**Comment by yuvalif** [comment]
jenkins test make check

**Comment by yuvalif** [comment]
teuthology results: http://pulpito.ceph.com/yuvalif-2023-07-23_21:13:34-rgw-wip-yuval-test-gsco1-distro-default-smithi/

**Comment by yuvalif** [comment]
> teuthology results: http://pulpito.ceph.com/yuvalif-2023-07-23_21:13:34-rgw-wip-yuval-test-gsco1-distro-default-smithi/

all issues are kown:
* see: https://github.com/ceph/ceph/pull/52273#issuecomment-1647989729
* amqp crash: https://tracker.ceph.com/issues/61498

**Pull request merged**
