### PR TITLE
luminous: rgw_file: full enumeration needs new readdir whence strategy, plus recursive rm side-effect of FLAG_EXACT_MATCH found

### PR DESCRIPTION
**Pull request by shinobu-x**
http://tracker.ceph.com/issues/21919

### CODE REVIEW

**Comment by yuriw** [comment]
[rgw => wip-yuri4-testing-2018-01-25-1744-luminous](https://trello.com/c/qvWoKh2O/243-rgw-wip-yuri4-testing-2018-01-25-1744-luminous)

**Comment by yuriw** [comment]
@mattbenjamin ready for merge, pls approve

**Comment by yuriw** [comment]
[wip-yuri5-testing-2018-01-29-1654-luminous](https://trello.com/c/DeG5uriq/248-wip-yuri5-testing-2018-01-29-1654-luminous)

**Comment by yuriw** [comment]
@mattbenjamin ready for merge

**Comment by mattbenjamin** [comment]
@smithfarm I could use your help with this one.  From this PR, 9f7d877a0e1a32711b74d69ac7f47252df2a4287 should merge, but the "disable flag exact match" commit should be discarded.  I have requested the author to do this, and he has not updated.  I need the variant readdir commit to reach luminous quickly.

**Comment by smithfarm** [comment]
@mattbenjamin Looks like you already did it in https://github.com/ceph/ceph/pull/18801 and it was released in 12.2.2 . . . reopen if I'm wrong?

**Comment by mattbenjamin** [comment]
@smithfarm whew--cool;  thanks

**Pull request closed without merging**
