### PR TITLE
crimson: cleanups to use `IsFullKey` concept

### PR DESCRIPTION
**Pull request by tchaikov**
the goal is to have less redirections and less repeatings.

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by tchaikov** [comment]
jenkins test api

**Comment by tchaikov** [comment]
jenkins test api

**Review by cyx1231st — APPROVED** [review]

**Comment by tchaikov** [comment]
```
2022-08-19 02:27:05,073.073 INFO:__main__:test_get_status (tasks.mgr.dashboard.test_cluster.ClusterTest) ... ERROR
2022-08-19 02:27:05,073.073 INFO:__main__:
2022-08-19 02:27:05,073.073 INFO:__main__:======================================================================
2022-08-19 02:27:05,073.073 INFO:__main__:ERROR: test_get_status (tasks.mgr.dashboard.test_cluster.ClusterTest)
2022-08-19 02:27:05,073.073 INFO:__main__:----------------------------------------------------------------------
2022-08-19 02:27:05,074.074 INFO:__main__:Traceback (most recent call last):
2022-08-19 02:27:05,074.074 INFO:__main__:  File "/home/jenkins-build/build/workspace/ceph-api/qa/tasks/mgr/dashboard/test_cluster.py", line 7, in setUp
2022-08-19 02:27:05,074.074 INFO:__main__:    super().setUp()
2022-08-19 02:27:05,074.074 INFO:__main__:  File "/home/jenkins-build/build/workspace/ceph-api/qa/tasks/mgr/dashboard/helper.py", line 271, in setUp
2022-08-19 02:27:05,074.074 INFO:__main__:    self.wait_for_health_clear(self.TIMEOUT_HEALTH_CLEAR)
2022-08-19 02:27:05,074.074 INFO:__main__:  File "/home/jenkins-build/build/workspace/ceph-api/qa/tasks/ceph_test_case.py", line 175, in wait_for_health_clear
2022-08-19 02:27:05,074.074 INFO:__main__:    self.wait_until_true(is_clear, timeout)
2022-08-19 02:27:05,074.074 INFO:__main__:  File "/home/jenkins-build/build/workspace/ceph-api/qa/tasks/ceph_test_case.py", line 212, in wait_until_true
2022-08-19 02:27:05,074.074 INFO:__main__:    raise TestTimeoutError("Timed out after {0}s and {1} retries".format(elapsed, retry_count))
2022-08-19 02:27:05,074.074 INFO:__main__:tasks.ceph_test_case.TestTimeoutError: Timed out after 60s and 0 retries
```

**Comment by tchaikov** [comment]
jenkins test api

**Comment by tchaikov** [comment]
jenkins test api

**Pull request merged**
