### PR TITLE
rbd-nbd: don't ignore --read-only option in BLKROSET ioctl

### PR DESCRIPTION
**Pull request by liupan1111**

### CODE REVIEW

**Comment by liupan1111** [comment]
@trociny , please help take a look.

**Comment by trociny** [comment]
@liupan1111 I am not sure about the redundant line break. It separates rbd-nbd specific options from ceph generic options, and this looks ok to me. Also this is what i.g. ceph-osd does.

I would more happy if one decreases number of space characters between an option name and its description. This can be done in the same commit where you fix "an image" (I don't see a point in having many commits for updating help info).

As for "readonly" redundant setting, I suppose it was done this way because NBD_SET_FLAGS may fail on older kernels, so this is like a safety guard. See how it is handled in qemu [1]. I would do similarly or leave it as is now.

[1] https://github.com/qemu/qemu/blob/master/nbd/client.c#L669

**Comment by liupan1111** [comment]
> @liupan1111 I am not sure about the redundant line break. It separates rbd-nbd specific options from ceph generic options, and this looks ok to me. Also this is what i.g. ceph-osd does.
OK, agree, let's keep it.

**Comment by trociny** [comment]
>  for NBD_SET_FLAGS, it will both check snapname and readonly option. But for this "double check", it only checks snapname, so I think it is a bug and will change the right value.

Agreed.

>   In the qemu code you referred, it will set NBD_SET_FLAGS first, if failed, then call this "double check". How about we keep the style?

You can only fix setting `read_only` properly or if you like do similar to what qemu does. Both ways are ok to me.

**Comment by liupan1111** [comment]
@trociny updated.

**Pull request merged**
