### PR TITLE
include/rados: fix typo in librados.h

### PR DESCRIPTION
**Pull request by wumingqiao**
rados_read_op_opeprate ->rados_read_op_operate

Signed-off-by: wumingqiao <wumingqiao@inspur.com>

### CODE REVIEW

**Comment by wumingqiao** [comment]
How to rebase from myown fork? should I resubmit this pr?

**Comment by joscollin** [comment]
@wumingqiao 

Try this:
```
1. $ git rebase upstream/master
2. Verify your changes and commit
3. $ git push origin master -f
```
You should always create a new branch for a PR and then do your work on it: `$git checkout -b wip-fix-typo`

**Comment by joscollin** [comment]
@weiqiaomiao 
Please read: https://github.com/ceph/ceph/blob/master/SubmittingPatches.rst#preparing-and-sending-patches

**Comment by wumingqiao** [comment]
OK, Thanks a lot. I will read it exactly and retry later

**Pull request closed without merging**
