### PR TITLE
tools/cephfs: Use sharded pgls in cephfs-data-scan

### PR DESCRIPTION
**Pull request by jcsp**

### CODE REVIEW

**Comment by jcsp** [comment]
Is tested by: https://github.com/ceph/ceph-qa-suite/pull/776

**Comment by jcsp** [comment]
> should we use metadata_io here?

Good catch, thank you.  I've updated it.

**Comment by jcsp** [comment]
Updated to fix the place where it was using data_io instead of ioctx in forall_objects (thanks zheng)

**Comment by jcsp** [comment]
Passing tests here: http://pulpito.ceph.com/jspray-2016-01-06_16:00:46-fs-wip-jcsp-testing---basic-smithi/15866

(other failures in that suite are all either infrastructure or attributed to other patches)

**Comment by jcsp** [comment]
Note to self: failure here: http://pulpito.ceph.com/gregf-2016-01-13_16:10:54-fs-greg-fs-speculative-1---basic-mira/28336/

**Comment by jcsp** [comment]
Rebased

**Comment by gregsfortytwo** [comment]
@jcsp, @ukernel, does this need more review for the changes? Ready for integration testing?

**Comment by jcsp** [comment]
Although I've got a passing test run here: http://pulpito.ceph.com/jspray-2016-01-29_03:42:31-fs-wip-sharded-scan---basic-mira/ ...

... I gave it another couple of passes locally and there's an issue, so hold fire.

**Comment by jcsp** [comment]
This problem was that find_or_create_dirfrag wasn't handling EEXIST properly, so when two workers tried to create the same frag concurrently one of them was erroring out.  Fixed now, test passes locally, ready for re-test.

**Comment by gregsfortytwo** [comment]
I've got this in a testing branch but the unit test builder there failed on some monitor thing...probably just noise or a broken master but FYI.

**Comment by gregsfortytwo** [comment]
http://pulpito.ceph.com/gregf-2016-02-17_22:27:35-fs-greg-pr-7034---basic-mira/
Valgrind failure is known (http://tracker.ceph.com/issues/14794)
Other failure is infrastructure noise; that test has passed previous integration branches including this code.

**Pull request merged**
