### PR TITLE
win32_deps_build: skip patching removed boost files

### PR DESCRIPTION
**Pull request by petrutlucian94**
We're attempting to patch some Python files that have been removed from recent Boost versions.

Now that the Boost version has been bumped, we'll need to address this in order to unblock the Windows build.

Note that we'll also have to skip ``test_back_trace`` when using mingw-gcc as it triggers an ICE with recent Boost versions. However, this issue does not affect mingw-llvm.

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [x] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Review by idryomov — APPROVED** [review]

**Comment by idryomov** [comment]
jenkins test windows

**Comment by idryomov** [comment]
jenkins test make check

**Comment by petrutlucian94** [comment]
jenkins test windows

**Comment by idryomov** [comment]
The ICE when compiling `src/test/common/test_back_trace.cc` persists.

**Comment by petrutlucian94** [comment]
> The ICE when compiling `src/test/common/test_back_trace.cc` persists.

Indeed, I'll have to investigate it further.

**Comment by petrutlucian94** [comment]
@idryomov looks like the ICE only occurs with mingw-gcc and recent Boost versions, mingw-llvm works fine.

Considering that we're planning on switching to mingw-llvm, I've added another commit that just skips the test when using mingw-gcc. Talking of mingw-llvm, @adamemerson do you think you could review the timespan changes as requested by Ilya? https://github.com/ceph/ceph/pull/51197#discussion_r1209549155

**Comment by petrutlucian94** [comment]
jenkins test windows

**Comment by idryomov** [comment]
jenkins test make check

**Comment by idryomov** [comment]
jenkins test windows

**Comment by idryomov** [comment]
Windows check is failing as follows repeatedly:
```
Reading package lists...
Building dependency tree...
Reading state information...
dpkg-dev is already the newest version (1.21.1ubuntu2.2).
dpkg-dev set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 3 not upgraded.
504+ EXIT_CODE=22
+ [[ 22 -eq 124 ]]
+ return 22

real	1m6.647s
user	0m0.069s
sys	0m0.153s
Build step 'Execute shell' marked build as failure
```

**Comment by petrutlucian94** [comment]
@idryomov @adamemerson The new boost shaman url doesn't work, I reproduced the ``install-deps.sh`` failure locally:

https://github.com/ceph/ceph/commit/244c5ebbd4d5683da7f57612cc02e946aae7fd73#diff-1335d27b188d672bf9a9b572f40df7c4699b8d9998fb16ba284f4acb4e77077c
```
sudo curl --silent --fail --write-out '%{http_code}' --location https://shaman.ceph.com/api/repos/libboost/master/2804368f5b807ba8334b0ccfeb8af191edeb996f/ubuntu/jammy/repo --output /etc/apt/sources.list.d/libboost.list
504
```

I don't see the new hash here: https://shaman.ceph.com/api/repos/libboost/master/

**Comment by idryomov** [comment]
> I don't see the new hash here: https://shaman.ceph.com/api/repos/libboost/master/

I think this is supposed to come from https://github.com/ceph/ceph-boost and the last time this was done David and/or Kefu were involved.  @adamemerson I see that you had made some changes to that repo as part of switching to 1.82, could you please follow up on the missing build?

**Comment by adamemerson** [comment]
> > I don't see the new hash here: https://shaman.ceph.com/api/repos/libboost/master/
> 
> I think this is supposed to come from https://github.com/ceph/ceph-boost and the last time this was done David and/or Kefu were involved. @adamemerson I see that you had made some changes to that repo as part of switching to 1.82, could you please follow up on the missing build?

Working on it. We had a build uploaded, I don't know why it went away. I'm talking to the infrastructure team right now.

**Comment by adamemerson** [comment]
> > > I don't see the new hash here: https://shaman.ceph.com/api/repos/libboost/master/
> > 
> > 
> > I think this is supposed to come from https://github.com/ceph/ceph-boost and the last time this was done David and/or Kefu were involved. @adamemerson I see that you had made some changes to that repo as part of switching to 1.82, could you please follow up on the missing build?
> 
> Working on it. We had a build uploaded, I don't know why it went away. I'm talking to the infrastructure team right now.

Infrastructure team says that old builds are periodically removed, they said they'll have to look into how to protect them. I'm re-uploading.

**Comment by adamemerson** [comment]
jenkins test make check

**Comment by petrutlucian94** [comment]
jenkins test windows

**Comment by petrutlucian94** [comment]
jenkins test make check

**Comment by petrutlucian94** [comment]
> `make check` is impacted by an unrelated issue across PRs but the Windows check also failed:
> 
> ```
> [2023-07-18T07:40:30.000Z] [isolated][googletest] ceph_test_libcephfs failed. Error: Command returned non-zero code(3): "cmd /c 'C:\ceph\ceph_test_libcephfs.exe --gtest_output=xml:C:\workspace\test_results\out\ceph_test_libcephfs\ceph_test_libcephfs_results.xml --gtest_filter="*" >> C:\workspace\test_results\out\ceph_test_libcephfs\ceph_test_libcephfs_results.log 2>&1'".
> ```

I'll trigger a recheck to see if it's a flaky test:

```
/home/ubuntu/ceph/src/test/libcephfs/deleg.cc:225: Failure
Expected equality of these values:
  opened.load()
    Which is: true
  false
terminate called without an active exception
```

**Comment by petrutlucian94** [comment]
jenkins test windows

**Comment by petrutlucian94** [comment]
``ASSERT_EQ(opened.load(), false)`` occasionally fails when running ``LibCephFS.DelegMultiClient``:

```
/home/ubuntu/ceph/src/test/libcephfs/deleg.cc:225: Failure
Expected equality of these values:
  opened.load()
    Which is: true
  false
terminate called without an active exception
```

The test performs a r/w open and expects the delegation to be recalled, so far so good. The problem is that it waits 1ms and then asserts that the ``opened`` flag hasn't been set, which is flaky. I'd have a few questions, maybe @jtlayton or @vshankar could  help:

* why are we asserting that ``opened`` is false after the delegation was recalled? I assume we're ensuring that the delegation is revoked before the open completes.
* what's the purpose of the 1ms sleep in between? The test passes if we drop that line.

For what is worth, we're running this test in a multi-node setup (well, separate vms). It used to pass, so maybe the timing has changed slightly as a result of a recent change. I guess we just have to update the assertions or maybe drop that ``usleep``.

https://github.com/ceph/ceph/blob/21ad52551d325ba83705d2c18247dddb177a798e/src/test/libcephfs/deleg.cc#L210-L229

**Comment by petrutlucian94** [comment]
The last Windows job failed because of git errors, issuing a recheck. 

```
fatal: unable to access 'https://github.com/ceph/seastar.git/': The requested URL returned error: 500
fatal: clone of 'https://github.com/ceph/seastar.git' into submodule path '/home/ubuntu/ceph/src/seastar' failed
Failed to clone 'src/seastar' a second time, aborting
+ EXIT_CODE=1
+ [[ 1 -eq 124 ]]
```

**Comment by petrutlucian94** [comment]
jenkins test windows

**Comment by petrutlucian94** [comment]
jenkins test make check

**Comment by petrutlucian94** [comment]
jenkins test make check

**Comment by idryomov** [comment]
jenkins test make check

**Comment by petrutlucian94** [comment]
Looks like we still have some racy libcephfs tests, I'm preparing a separate PR with the changes proposed by @vshankar.

**Pull request merged**
