### PR TITLE
luminous: librbd: discard should wait for in-flight cache writeback to complete

### PR DESCRIPTION
**Pull request by dillaman**
http://tracker.ceph.com/issues/23604

### CODE REVIEW

**Comment by smithfarm** [comment]
jenkins test docs

**Comment by yuriw** [comment]
[wip-yuri-testing-2018-09-12-2202-luminous](https://trello.com/c/fPyesptD/402-wip-yuri-testing-2018-09-12-2202-luminous)

**Comment by dillaman** [comment]
Fixed memory leak (```C_DiscardRequest``` instance wasn't being deleted).

**Comment by yuriw** [comment]
@dillaman will retest

**Comment by yuriw** [comment]
[wip-yuri-testing-2018-09-17-1932-luminous](https://trello.com/c/iElrKDGB/406-wip-yuri-testing-2018-09-17-1932-luminous)

**Pull request merged**
