### PR TITLE
cmake: ensure fmt lib is at least 8.1.1

### PR DESCRIPTION
**Pull request by theanalyst**
Since we depend on newer api features like `group_digits` ensure that the system version of fmt we use is at least as new as the submodules we bring.

Signed-Off-By: Abhishek Lekshmanan <abhishek.l@cern.ch>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [x] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by theanalyst** [comment]
There is ceph.spec.in also where we set fmt-devel >= 6.3.1, I suppose this can also be changed? But not so sure if many distros package such a newer version.

**Comment by Matan-B** [comment]
> fmt-devel

Let's update ceph.spec.in as well since we already introduced fmtlib 8.1 features. @ronen-fr

**Review by tchaikov — APPROVED** [review]

**Comment by theanalyst** [comment]
> > There is ceph.spec.in also where we set fmt-devel >= 6.3.1, I suppose this can also be changed? But not so sure if many distros package such a newer version.
> 
> Let's update ceph.spec.in as well since we already introduced fmtlib 8.1 features. @ronen-fr

So tried this on my centos8 box and here since we don't have system packages of fmtlib > 8.1.1 the install-deps step fails. Don't know what the current distro support matrix is for master (I see fc36 packages newer version), but since we do use fmt as a submodule and anyway can build regardless of system packages don't know whether it is worth failing install-deps. Happy to update `ceph.spec.in` or keep this pr as it is based on the opinion here.

**Comment by yehudasa** [comment]
I ran into this issue now. This will fix compilation, but my question is whether the original usage of `fmt::group_digits()` is worth dropping a system package in favor of the submodule version. We should at least figure out which systems that would affect. I think the original change can be easily adapted to avoid the need for the package upgrade.

**Comment by ktdreyer** [comment]
I'm sorry, I cannot review this PR now with my other priorities

**Review by ktdreyer — APPROVED** [review]
I've made time to look at this today, since I've hit this build failure myself.
```
../src/osd/scrubber/osd_scrub_sched.cc:552:24: error: ‘group_digits’ is not a member of ‘fmt’
            fmt::group_digits(conf()->osd_scrub_max_interval),
```

On RHEL 8:
 - fmt is in EPEL 8, `fmt-6.2.1-1.el8`
 - In [an el8 build](https://cbs.centos.org/kojifiles/packages/ceph/18.1.2/0.1.el8s/data/logs/x86_64/build.log): `-DWITH_FMT_HEADER_ONLY:BOOL=ON` leads to `Could not find fmt, will build it`

On RHEL 9:
 - fmt is in EPEL 9, `fmt-8.1.1-5.el9`
 - In [an el9 build](https://cbs.centos.org/kojifiles/packages/ceph/18.1.2/0.1.el9s/data/logs/x86_64/build.log), `-DWITH_FMT_HEADER_ONLY:BOOL=ON` uses the system package, though CMake's `find_package()` does not print the version it successfully found (maybe the `QUIET` option hides that success output?)

I'm good with merging this and backporting to reef.

_Separately,_ I do think the version mis-match in `ceph.spec.in` is confusing (`7.0.0` and `8.1.1` here in CMake vs `6.2.1` in `ceph.spec.in`). If we bump that number in the RPM packaging, though, then we'll fail to build on el8, since EPEL 8 will no longer be able to satisfy that. My recommendation (_separate PR_!) is:
- Set `BuildRequires:  fmt-devel >= 8.1.1` behind a conditional so it takes effect only on Fedora and RHEL 9+, not on RHEL 8
- [Better yet, drop el8 altogether for `main`](https://www.spinics.net/lists/ceph-users/msg73213.html)

**Comment by ronen-fr** [comment]
@ktdreyer 
> * Better yet, drop el8 altogether for `main`

I'm wholeheartedly for that.
Note that when discussed in some meetings, the question that was raised was
how dropping centos 8 affects old RHEL support.

**Comment by ktdreyer** [comment]
@ronen-fr Do you mind giving your approval on this PR so we can merge it to `main`?

**Review by ronen-fr — APPROVED** [review]

**Comment by ktdreyer** [comment]
@theanalyst could you rebase this onto the latest `main`?

**Comment by rosinL** [comment]
> Separately, I do think the version mis-match in ceph.spec.in is confusing (7.0.0 and 8.1.1 here in CMake vs 6.2.1 in ceph.spec.in). 

yeah, It is really confusing. 

> On RHEL 8:
> fmt is in EPEL 8, fmt-6.2.1-1.el8
> In [an el8 build](https://cbs.centos.org/kojifiles/packages/ceph/18.1.2/0.1.el8s/data/logs/x86_64/build.log): -DWITH_FMT_HEADER_ONLY:BOOL=ON leads to Could not find fmt, will build it

Why not always building the fmt? 
As I remove `BuildRequires:	fmt-devel >= 6.2.1` from ceph.spec and remove the fmt-devel packages, ceph building works fine, so I think the  BuildRequires of fmt-devel in ceph.spec.in is not really needed.

**Comment by ktdreyer** [comment]
Right @tchaikov . Also, pre-built packages lower Ceph's build times.

**Comment by theanalyst** [comment]
> @theanalyst could you rebase this onto the latest `main`?

done!

**Review by ktdreyer — APPROVED** [review]

**Comment by idryomov** [comment]
jenkins test make check

**Review by idryomov — COMMENTED** [review]
I went ahead and merged since this has been pending for months.  Highlighting Ken's recommendation:

> _Separately,_ I do think the version mis-match in `ceph.spec.in` is confusing (`7.0.0` and `8.1.1` here in CMake vs `6.2.1` in `ceph.spec.in`). If we bump that number in the RPM packaging, though, then we'll fail to build on el8, since EPEL 8 will no longer be able to satisfy that. My recommendation (_separate PR_!) is:
> 
>  - Set `BuildRequires:  fmt-devel >= 8.1.1` behind a conditional so it takes effect only on Fedora and RHEL 9+, not on RHEL 8
> 
> - [Better yet, drop el8 altogether for `main`](https://www.spinics.net/lists/ceph-users/msg73213.html)

**Comment by idryomov** [comment]
Opened a reef backport since `fmt::group_digits` is used there too.

**Pull request merged**
