### PR TITLE
cephfs-top: fix help text for delay

### PR DESCRIPTION
**Pull request by joscollin**
Fixes: https://tracker.ceph.com/issues/59553

Updates:

```
  -d {1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25}, --delay {1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25}
                        Refresh interval in seconds (default: 1)
```

to

```
  -d DELAY, --delay DELAY
                        Refresh interval in seconds (default: 1, range: 1 - 25)
```

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by vshankar** [comment]
@neesingh-rh ping?

**Review by neesingh-rh — APPROVED** [review]
help text is better now. LGTM

**Comment by vshankar** [comment]
@joscollin please create a tracker and link it in the commit - we'd need to backport this.

**Comment by joscollin** [comment]
> @joscollin please create a tracker and link it in the commit - we'd need to backport this.

Done.

**Comment by vshankar** [comment]
> Fixes: https://tracker.ceph.com/issues/59553
> 
> Updates:
> 
> ```
>   -d {1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25}, --delay {1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25}
>                         Refresh interval in seconds (default: 1)
> ```
> 
> to
> 
> ```
>   -d DELAY, --delay DELAY
>                         Refresh interval in seconds (default: 1, range: 1 - 25)

You might want to put up the above explanation in the commit message.

**Comment by vshankar** [comment]
Otherwise LGTM.

**Comment by joscollin** [comment]
> > Fixes: https://tracker.ceph.com/issues/59553
> > Updates:
> > ```
> >   -d {1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25}, --delay {1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25}
> >                         Refresh interval in seconds (default: 1)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > to
> > ```
> >   -d DELAY, --delay DELAY
> >                         Refresh interval in seconds (default: 1, range: 1 - 25)
> > ```
> 
> You might want to put up the above explanation in the commit message.

Done.

**Comment by vshankar** [comment]
jenkins test make check

**Comment by vshankar** [comment]
jenkins test make check arm64

**Comment by joscollin** [comment]
jenkins test make check

**Review by vshankar — APPROVED** [review]

**Comment by joscollin** [comment]
jenkins test make check

**Comment by vshankar** [comment]
jenkins test make check

**Comment by joscollin** [comment]
jenkins test make check

**Comment by joscollin** [comment]
jenkins test make check

**Comment by joscollin** [comment]
jenkins test windows

**Pull request merged**
