### PR TITLE
rgw: Multipart upload may failed when object size is large

### PR DESCRIPTION
**Pull request by mdw-at-linuxbox**
[ revised to use common rgw logic to parse oids.  - Marcus Watts <mwatts@redhat.com ]

Fixes:http://tracker.ceph.com/issues/21565

Signed-off-by: Sibei Gao <gaosb@inspur.com>

### CODE REVIEW

**Comment by mattbenjamin** [comment]
@gaosibei , @mdw-at-linuxbox confirms this fix to be important, but I'm a bit confused how it arises, and also about the string parsing as a mechanism;  can you provide some detail on how / when this case reproduces, and maybe on the choice of approaches for solving?

**Comment by mattbenjamin** [comment]
@gaosibei ok, I understand the reproducer from the tracker;  I think we need (and @yehudasa agrees we need) a different mechanism to detect such a case

**Comment by gaosibei** [comment]
@mattbenjamin 

Do you need me to provider a new method to fix this bug？

**Comment by mattbenjamin** [comment]
@gaosibei yes, we'd like a new mechanism--if protocol change is required, we can motivate it in Mimic

**Comment by gaosibei** [comment]
Before geive a new method. I want to konw What conditions need to meet for the new mechanism?  And what are the disadvantages of the current method?

**Comment by mattbenjamin** [comment]
@gaosibei my intuition was, we shouldn't need to parse object names in order to identify the full operation being performed is completing a multipart upload;  @mdw-at-linuxbox , @yehudasa , do you want to amplify?

**Comment by gaosibei** [comment]
@mattbenjamin @mdw-at-linuxbox 
Now， I give a new method to fix this bug which don't need  parse object names.

The PR is:  https://github.com/ceph/ceph/pull/17960

**Comment by liewegas** [comment]
closing this on preference to #17960

**Pull request closed without merging**
