### PR TITLE
octopus: common: remove log_early configuration option

### PR DESCRIPTION
**Pull request by idryomov**
Backport of https://github.com/ceph/ceph/pull/37175.

I kept chasing my tail trying to make sense of a set of nautilus logs, where a few key lines were missing due to `log-early` not being on by default in nautilus.  What would have been obvious in an instant took almost three days...  Fix this for octopus as well.

### CODE REVIEW

**Review by liewegas — APPROVED** [review]

**Comment by tchaikov** [comment]
- https://pulpito.ceph.com/kchai-2021-04-12_02:35:25-rados-wip-kefu-octopus-testing-2021-04-11-2349-distro-basic-gibba/
- https://pulpito.ceph.com/kchai-2021-04-12_13:55:39-rados-wip-kefu-octopus-testing-2021-04-11-2349-distro-basic-smithi/

i think most of cephadm test failures are caused by https://tracker.ceph.com/issues/49293

**Comment by idryomov** [comment]
jenkins test api

**Comment by idryomov** [comment]
jenkins test docs

**Comment by idryomov** [comment]
jenkins test docs

**Comment by idryomov** [comment]
jenkins test api

**Pull request merged**
