### PR TITLE
ceph-volume: fix a bug in _check_generic_reject_reasons

### PR DESCRIPTION
**Pull request by caffeinism**
ceph-volume: fix a bug in _check_generic_reject_reasons

The types of "removable" and "ro" are wrong. Here, both filters are not
working at all. Changed this from integer to string and corrected the test
data.

Delete redundant logic in get_block_devs_sysfs. Given the name of the
function, I think it is correct to judge from _check_generic_reject_reasons,
and in fact it was before v17.2.4.

Fixes: https://tracker.ceph.com/issues/58591
Signed-off-by: Kim Minjong <caffeinism@puzzle-ai.com>

### CODE REVIEW

**Comment by caffeinism** [comment]
@satoru-takeuchi Could you please do a review?

https://tracker.ceph.com/issues/38833 

Referring to this issue, it seems that the basic principle is that removable devices are not supported by default, so the vendor=='USB' logic was excluded. (And this doesn't seem to work very well. I guess I need to refer to udevadm to filter out the USB.)
However, still logic in rejected_reason is a bug. That part has been modified to make the previous code work well.

I have compiled the results by version and patch. sda, sdc, sdd are removable SATA and sde, sdf, dfg are non-removalbe SATA.

Versions prior to 17.2.14 work as follows.
```
Device Path               Size         rotates available Model name
/dev/sda                  3.49 TB      False   True      SAMSUNG MZ7L33T8
/dev/sdb                  1.75 TB      False   False     SAMSUNG MZ7L31T9
/dev/sdc                  3.49 TB      False   True      SAMSUNG MZ7L33T8
/dev/sdd                  3.49 TB      False   True      SAMSUNG MZ7L33T8
/dev/sde                  3.49 TB      False   True      SAMSUNG MZ7L33T8
/dev/sdf                  3.49 TB      False   True      SAMSUNG MZ7L33T8
/dev/sdg                  3.49 TB      False   True      SAMSUNG MZ7L33T8
```

From version 17.2.14 onwards, it works as follows.
```
Device Path               Size         rotates available Model name
/dev/sde                  3.49 TB      False   True      SAMSUNG MZ7L33T8
/dev/sdf                  3.49 TB      False   True      SAMSUNG MZ7L33T8
/dev/sdg                  3.49 TB      False   True      SAMSUNG MZ7L33T8
```

The current commit behaves like
```
Device Path               Size         rotates available Model name
/dev/sda                  3.49 TB      False   False     SAMSUNG MZ7L33T8
/dev/sdb                  1.75 TB      False   False     SAMSUNG MZ7L31T9
/dev/sdc                  3.49 TB      False   False     SAMSUNG MZ7L33T8
/dev/sdd                  3.49 TB      False   False     SAMSUNG MZ7L33T8
/dev/sde                  3.49 TB      False   True      SAMSUNG MZ7L33T8
/dev/sdf                  3.49 TB      False   True      SAMSUNG MZ7L33T8
/dev/sdg                  3.49 TB      False   True      SAMSUNG MZ7L33T8
```

Behavior I wanted (but not allowed in issue above)
```
Device Path               Size         rotates available Model name
/dev/sda                  3.49 TB      False   True      SAMSUNG MZ7L33T8
/dev/sdb                  1.75 TB      False   False      SAMSUNG MZ7L31T9
/dev/sdc                  3.49 TB      False   True      SAMSUNG MZ7L33T8
/dev/sdd                  3.49 TB      False   True      SAMSUNG MZ7L33T8
/dev/sde                  3.49 TB      False   True      SAMSUNG MZ7L33T8
/dev/sdf                  3.49 TB      False   True      SAMSUNG MZ7L33T8
/dev/sdg                  3.49 TB      False   True      SAMSUNG MZ7L33T8
```

**Comment by caffeinism** [comment]
I also added code to allow removable device but remove usb. I checked the ID_BUS field of udevadm and excluded it in case of usb.

It works like "Behavior I wanted" in the comment above.

**Comment by nikhiljha** [comment]
Additional support for this: Certain SuperMicro servers have firmware that reports hotswap disks as removable. Ceph obviously should try to support datacenter storage servers.

**Comment by zmc** [comment]
I think this looks reasonable but @guits is a better choice for a reviewer

**Comment by kcalmond** [comment]
@caffeinism - Will this fix allow you to override "exclude USB" for us home lab'ers running experimental ceph on pi clusters and wishing to use USB flash drives? BTW, my current cluster (running in RPi 4bs - lastest firmware) has no problem consuming SATA SSD's connected to same USB3 ports when using [this StarTech USB3 to SATA III adapter](https://www.amazon.com/gp/product/B00HJZJI84/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&psc=1).

**Review by satoru-takeuchi — APPROVED** [review]
> Note: Unlike the issue, the existing code fully reflects the actual size, but the removable device is excluded from the list, causing sys_api to become an empty dictionary and generate a Insufficient space message

I read the code again and found that I was wrong.

**Comment by caffeinism** [comment]
> Will this fix allow you to override "exclude USB" for us home lab'ers running experimental ceph on pi clusters and wishing to use USB flash drives? BTW, my current cluster (running in RPi 4bs - lastest firmware) has no problem consuming SATA SSD's connected to same USB3 ports when using [this StarTech USB3 to SATA III adapter](https://www.amazon.com/gp/product/B00HJZJI84/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&psc=1).

Unfortunately, this PR fixes the behavior of removable disks that originally did not work (in fact, what should not have worked in the past worked) and at the same time disables USB. I think it was intentional to make ceph-volume not work for USB in the past.

However, you can use it by injecting code into ceph-volume for experimentation. Since ceph-volume is written in Python, it can be modified and used just by injecting it. Assuming the PR is merged, delete the `('id_bus', 'usb', 'id_bus'),` line in device.py and run ceph-volume. If you're using docker, you could write a Dockerfile like this:
```
FROM quay.io/ceph/ceph:[merged_release]
RUN sed -e '/('\''id_bus'\'', '\''usb'\'', '\''id_bus'\''),/ s/^#*/#/' -i /usr/lib/python3.6/site-packages/ceph_volume/util/device.py
```

**Comment by nanderson94** [comment]
Would like to toss in that importing this patch into my cephadm cluster has permitted me to finally add my new OSDs. With `ceph/ceph:v17.2.5`, all my disks were being rejected since the controller (Adaptec 71605) is flagging hot-pluggable drives as removable. With the patch:

```
nas2         /dev/sdb  hdd   ATA_ST16000NM000G-xxx        16.0T  Yes        100s ago
nas2         /dev/sdc  hdd   ATA_ST16000NM000G-xxx        16.0T  Yes        100s ago
nas2         /dev/sdd  hdd   ATA_ST16000NM000G-xxx        16.0T  Yes        100s ago
nas2         /dev/sde  hdd   ATA_ST16000NM000G-xxx        16.0T  Yes        100s ago
nas2         /dev/sdf  hdd   ATA_ST16000NM000G-xxx        16.0T  Yes        100s ago
nas2         /dev/sdg  hdd   ATA_ST16000NM000G-xxx        16.0T  Yes        100s ago
nas2         /dev/sdh  hdd   ATA_ST16000NM000G-xxx        16.0T  Yes        100s ago
```

Great success, thank you @caffeinism !

**Comment by caffeinism** [comment]
> Hi!
> 
> Any news for this request?
> 
> We have some problem with gigabyte servers have firmware that reports hotswap disks as removable.

Unfortunately, it doesn't seem to be an issue that is getting much attention. If version doesn't matter to you, try v17.2.3, or if you want a later version, you'll have to modify the module as I wrote above.

**Comment by BotoX** [comment]
I'm affected by this, had to make my own ceph-path image and push it to a docker registry...
https://hub.docker.com/r/botox/ceph-patch/tags
then use ceph orch upgrade start --image "docker.io/botox/ceph-patch:v17.2.6"
to apply it to all nodes of my cluster

completely insane, changing a few lines of code has to push multiple gbs of data through some cloud service wtf...

**Comment by reidbk** [comment]
This issue is present on Asus AMD Milan and Genoa server platforms. The embedded SATA controller marks the hot plug disks as removable and unusable to cephadm. This patch resolves the problem.

**Comment by elliotcourant** [comment]
Running into this issue as well.

Looks like its also being referenced here: https://tracker.ceph.com/issues/58306 ?

**Comment by caffeinism** [comment]
@guits This PR is over 8 months old and still pings me occasionally, can you review this? My email changed, so I re-signed the unverified commit and rebased it as requested by the bot.

**Comment by bhudgens** [comment]
> I'm affected by this, had to make my own ceph-path image and push it to a docker registry... https://hub.docker.com/r/botox/ceph-patch/tags then use ceph orch upgrade start --image "docker.io/botox/ceph-patch:v17.2.6" to apply it to all nodes of my cluster
> 
> completely insane, to change a few lines of code I have to push multiple gbs of data through some cloud service wtf... or alternatively setup my own registry lmao is there no easier way to patch ceph?

Thank you for making this patch. I wanted to use some Sandisk USB drives in my homelab. The documentation all over the internet is stale and several places recommended USB drives in a Raspberry Pi lab. After getting it all built out, I was disappointed to finally stumble on this bug. I did not find reliable documentation suggesting "Removable" drives would not be supported until it didn't work. Several Raspberry Pi guides recommend using USB drives.

I was able to piggy back off your patch but also include @caffeinism's recommendation for patching the `/usr/lib/python3.6/site-packages/ceph_volume/util/device.py` file.

> ... If you're using docker, you could write a Dockerfile like this:
> 
> ```
> FROM quay.io/ceph/ceph:[merged_release]
> RUN sed -e '/('\''id_bus'\'', '\''usb'\'', '\''id_bus'\''),/ s/^#*/#/' -i /usr/lib/python3.6/site-packages/ceph_volume/util/device.py
> ```

The steps I followed to get OSD's working with USB drives:

- Setup a 4 node raspberry pi cluster with cephadm
- Patch all nodes: `ceph orch upgrade start "docker.io/bhudgens/ceph-use-usb-patch:v17.2.6"`
- Made sure the drives were cleaned up: `wipefs -a /dev/sd#`

Everything "just worked" after applying you guys' patches. Thanks for making it easy.

**Comment by NUABO** [comment]
hi @caffeinism,  Can the problem recorded in this link be solved through this patch? ( https://lists.ceph.io/hyperkitty/list/ceph-users@ceph.io/thread/OPMWHJ4ZFCOOPUY6ST4WAJ4G4ASJFALM/ ) thanks

**Review by zmc — APPROVED** [review]
This popped up in my notifications and I was disappointed to see that it has been sitting for so long with no review.

I pushed your branch to ceph-ci.git so that it would get built, then scheduled a small suite: https://pulpito-ng.ceph.com/zack-2023-10-20_19:22:42-orch:cephadm:smoke-small-fix-bug-in-ceph-volume-device-distro-default-smithi/

All tests passed, so I feel pretty comfortable that this PR doesn't regress, and I see the change is helping some other users.

Thank you for your contribution - and sorry for the poor experience!

**Comment by travisn** [comment]
@zmc What would it take to get this backported to Reef and Quincy?

**Comment by guits** [comment]
> This popped up in my notifications and I was disappointed to see that it has been sitting for so long with no review.

@zmc @caffeinism  I'm truly sorry, please accept my apologies. I got behind things and missed this 😞 
I'm currently catching up, I'll better watch out for future PRs. Hopefully that bad experience won't prevent you from contributing again.

**Comment by telmich** [comment]
@guits Sorry for the ping, but we have multiple clusters that are now affected by this bug and it seems that netiher 17.2.7 nor 18.2.1 seem to be fixed.

**Comment by valentin-ed** [comment]
Hi there !
Why the patch has been merged only in v19.0 and not in the others release?

I'm facing the same issue. I'm building my own docker image but i would like to know why it's not push en "18.x".

THanks

**Comment by flaminmoe** [comment]
> Hi there ! Why the patch has been merged only in v19.0 and not in the others release?
> 
> I'm facing the same issue. I'm building my own docker image but i would like to know why it's not push en "18.x".
> 
> THanks

yes, please backport it to 18.2.x.

**Comment by clertes** [comment]
> Hi!
> 
> Any news for this request?
> 
> We have some problem with gigabyte servers have firmware that reports hotswap disks as removable.

Same issues with Supermicro servers (A+ Server 2123BT-HTR / Mainboard H11DST-B). Drives are marked as "Removable" even if the HotSwap settings in BIOS are disabled.

**Comment by pyte1** [comment]
I'm still affected by this issue even on v18.2.2. Disk are attached to a Adaptec Controller in HBA Mode and as such are marked by the Kernel with RM flag. Ceph is not showing the disks.

**Comment by halittiryaki** [comment]
instead of having patched custom images, what speaks against to use udev rules on the host?

eg. for all usb devices:
```
ACTION=="add", ENV{ID_TYPE}=="disk", ENV{ID_BUS}=="usb", ENV{ID_BUS}="scsi"
ACTION=="change", ENV{ID_TYPE}=="disk", ENV{ID_BUS}=="usb", ENV{ID_BUS}="scsi"
ACTION=="online", ENV{ID_TYPE}=="disk", ENV{ID_BUS}=="usb", ENV{ID_BUS}="scsi"
```
makes osd spin up at least. without more insights how devices:id-bus is utilized further, time will show what can go wrong.

anyways, there should be a simple config option in ceph, with a side note: only for test envs.

**Comment by halittiryaki** [comment]
> > I'm affected by this, had to make my own ceph-path image and push it to a docker registry... https://hub.docker.com/r/botox/ceph-patch/tags then use ceph orch upgrade start --image "docker.io/botox/ceph-patch:v17.2.6" to apply it to all nodes of my cluster
> > completely insane, to change a few lines of code I have to push multiple gbs of data through some cloud service wtf... or alternatively setup my own registry lmao is there no easier way to patch ceph?
> 
> Thank you, @BotoX, for making [this patch](https://github.com/ceph/ceph/pull/49954#issuecomment-1631582443). I wanted to use some Sandisk USB drives in my homelab. The documentation all over the internet is stale and several places recommended USB drives in a Raspberry Pi lab. After getting it all built out, I was disappointed to finally stumble on this bug. I did not find reliable documentation suggesting "Removable" drives would not be supported until it didn't work. Several Raspberry Pi guides recommend using USB drives.
> 
> I was able to piggy back off your patch but also include @caffeinism's recommendation for patching the `/usr/lib/python3.6/site-packages/ceph_volume/util/device.py` file.
> 
> > ... If you're using docker, you could write a Dockerfile like this:
> > ```
> > FROM quay.io/ceph/ceph:[merged_release]
> > RUN sed -e '/('\''id_bus'\'', '\''usb'\'', '\''id_bus'\''),/ s/^#*/#/' -i /usr/lib/python3.6/site-packages/ceph_volume/util/device.py
> > ```
> 
> The steps I followed to get OSD's working with USB drives:
> 
> * Setup a 4 node raspberry pi cluster with cephadm
> * Patch all nodes: `ceph orch upgrade start "docker.io/bhudgens/ceph-use-usb-patch:v17.2.6"`
> * Made sure the drives were cleaned up: `wipefs -a /dev/sd#`
> 
> Everything "just worked" after applying you guys' patches. Thanks for making it easy.

instead of having patched custom images, what speaks against to use udev rules on the host?

eg. for all usb disks:

```
ACTION=="add", ENV{ID_TYPE}=="disk", ENV{ID_BUS}=="usb", ENV{ID_BUS}="scsi"
ACTION=="change", ENV{ID_TYPE}=="disk", ENV{ID_BUS}=="usb", ENV{ID_BUS}="scsi"
ACTION=="online", ENV{ID_TYPE}=="disk", ENV{ID_BUS}=="usb", ENV{ID_BUS}="scsi"
```

makes osd spin up at least. without more insights how devices:id-bus is utilized further, time will show what can go wrong.

anyways, there should be a simple config option in ceph, with a side note: only for test envs.

**Comment by guits** [comment]
> anyways, there should be a simple config option in ceph, with a side note: only for test envs.

We have always been clear that we shouldn't, and don't want to introduce or support code specifically for development or testing purposes. Although I had to give in on supporting loop devices, I don't want to repeat that mistake.

**Comment by rafaribe** [comment]
> > anyways, there should be a simple config option in ceph, with a side note: only for test envs.
> 
> We have always been clear that we shouldn't, and don't want to introduce or support code specifically for development or testing purposes. Although I had to give in on supporting loop devices, I don't want to repeat that mistake.

I would like to know why USB devices are a no-go for ceph maintainers, I totally get it with pendrives and generally slow devices, but with USB 3.1 USB drives that support fast r/w speeds what is the blocker to not allow them?

**Pull request merged**
