### PR TITLE
luminous: mon/mgr: sync "mgr_command_descs","osd_metadata" and "mgr_metadata" prefixes to new mons 

### PR DESCRIPTION
**Pull request by tchaikov**
http://tracker.ceph.com/issues/21647

### CODE REVIEW

**Comment by renhwztetecs** [comment]
luminous branch not “override”

**Comment by renhwztetecs** [comment]
In the virtual void get_store_prefixes() no const in the luminous branch.

**Comment by tchaikov** [comment]
@renhwztetecs fixed and repushed.

**Comment by songbaisen** [comment]
@tchaikov  You close this pr. But the pr you said can fix the prolem, it is not useful. I have merge that pr code and rebuild ceph-mon and reboot all the mon.. but it contiue core dump.  look like diffrent prolem. like below:

root@node-1151:/usr/bin# ceph-mon -i node-1151
2017-10-30 17:24:06.663421 7fbb2641cf00 -1 mon.node-1151@-1(probing).mgr e10829 Failed to load mgr commands: (2) No such file or directory
root@node-1151:/usr/bin# 
root@node-1151:/usr/bin# 
root@node-1151:/usr/bin# ceph osd perf
osd commit_latency(ms) apply_latency(ms) 
  2                  0                 0 
  1                  2                 2 
  0                  0                 0 
root@node-1151:/usr/bin# ceph osd perf
^CCluster connection interrupted or timed out
root@node-1151:/usr/bin# ps -ef|grep ceph-mon
root      11991  11058  0 17:24 pts/0    00:00:00 grep --color=auto ceph-mon
root@node-1151:/usr/bin# ll /corefile/
total 10288
drwxrwxrwx  2 root root      4096 Oct 25 17:23 ./
drwxr-xr-x 24 root root      4096 Oct 24 14:30 ../
-rw-------  1 root root 318910464 Oct 25 17:23 core-ms_dispatch-29998-1508923395
root@node-1151:/usr/bin#

**Comment by songbaisen** [comment]
@renhwztetecs  ping! have a look? 😄

**Comment by liewegas** [comment]
http://pulpito.ceph.com/sage-2017-11-02_14:19:46-rados-wip-sage2-testing-2017-11-02-0729-distro-basic-smithi/

**Comment by liewegas** [comment]
@jecluis does @songbaisen's crash above make sense to you?

**Comment by songbaisen** [comment]
@liewegas  Yes sage, use the new master code, it will not core dump.

**Comment by tchaikov** [comment]
@songbaisen also, i am not able to reproduce the issue with latest luminous branch, following the steps you put in https://github.com/ceph/ceph/pull/18620#issuecomment-340388781

**Comment by renhwztetecs** [comment]
@songbaisen 
maybe need backpoint this PR https://github.com/ceph/ceph/pull/17846

**Comment by liewegas** [comment]
already backported to luminous branch...

**Pull request merged**
