### PR TITLE
DNM: squash root

### PR DESCRIPTION
**Pull request by liewegas**

### CODE REVIEW

**Comment by gregsfortytwo** [comment]
Hmm. Don't we want to do root squash by default, and make *skipping* it be the thing that requires permissions?

**Comment by liewegas** [comment]
On Fri, 20 Mar 2015, Gregory Farnum wrote:
> Hmm. Don't we want to do root squash by default, and make skipping it be the thing that requires permissions?

that might be better.  and look, here's what man exports says:

root_squash
 Map requests from uid/gid 0 to the anonymous uid/gid. Note that this does 
 not apply to any other uids or gids that might be equally sensitive, such 
 as user bin or group staff.
no_root_squash
 Turn off root squashing. This option is mainly useful for diskless 
 clients.
all_squash
 Map all uids and gids to the anonymous user. Useful for NFS-exported 
 public FTP directories, news spool directories, etc. The opposite option 
 is no_all_squash, which is the default setting.
anonuid and anongid
 These options explicitly set the uid and gid of the anonymous account. 
 This option is primarily useful for PC/NFS clients, where you might want 
 all requests appear to be from one user. As an example, consider the 
 export entry for /home/joe in the example section below, which maps all 
 requests to uid 150 (which is supposedly that of user joe).

root_squash is the default.  And we should probably implement all of 
these...?

**Comment by gregsfortytwo** [comment]
Hmm, I'm not quite sure what all those mappings would mean for the FS and
our permissions mappings. It's additive, so I think we'd have to default to
only the anonymous UID/GID, then have permission grants for specifying any
non-root uid/gid, and then another one for allowing root?

And at that point you might as well also include "allow
uid=XXX,gid=XXX,YYY,ZZZ", which is probably the only tweak that end users
will be interested in besides root_squash.

**Comment by liewegas** [comment]
As far as i can tell the current way MDSAuthCaps separates match vs spec 
is broken.  At least, uid should be there; the path part could work.  But 
in the end, we'll probably need to have the permissions check function 
iterate over each allow/grant, see if the path matches, apply the rules it 
specifies that remap uids, and do the check.  if it fails, continue and 
try the next one.

I think our previous conception of specifying a uid/gid here is really 
equivalent to all_squash uid=x gid=y[,y2,y3].  IMO we may as well adopt 
the NFS style syntax that users are likely to be familiar with.

**Comment by gregsfortytwo** [comment]
As we discussed verbally, I don't think that we want to adopt the NFS-style
names since our grants are additive and a client permissions capability can
include access to multiple UIDs, whereas NFS grants work server-side and
are based around selecting one from a group of possible behaviors.

**Pull request closed without merging**
