### PR TITLE
os/bluestore/BlueStore: remove unused code.

### PR DESCRIPTION
**Pull request by majianpeng**
Signed-off-by: Jianpeng Ma <jianpeng.ma@intel.com>

### CODE REVIEW

**Comment by majianpeng** [comment]
Ok, i'll do by your suggestions.

**Comment by majianpeng** [comment]
update.

**Comment by joscollin** [comment]
`/home/jenkins-build/build/workspace/ceph-pull-requests/src/test/osd/osd-dup.sh:45: TEST_filestore_to_bluestore:  return 1`

**Comment by joscollin** [comment]
Jenkins retest this please

**Comment by joscollin** [comment]
Jenkins retest this please

**Comment by tchaikov** [comment]
- http://pulpito.ceph.com/kchai-2017-07-26_09:36:13-rados-wip-kefu-testing2-distro-basic-smithi/
- http://pulpito.ceph.com/kchai-2017-07-26_14:52:23-rados-wip-kefu-testing2-distro-basic-smithi/

**Pull request merged**
