### PR TITLE
ceph-volume: don't use container classes in api/lvm.py

### PR DESCRIPTION
**Pull request by rishabh-d-dave**
Use `get_lvs`, `get_vgs` and `get_pvs` instead. The hallmark difference
between usage of these methods and container classes is that these methods
use option `-S` to filter LVM devs. See `lvs -S --help` for more details on
these filters.

Changes to api/lvm.py will be merged separately; see PR #32231. Only
devices/lvm/listing.py is an exception in this PR since refactoring on this
file happens on a separate PR (see #31700).

These containers classes will be removed from api/lvm.py on a separate PR
after this and related PR merges.

Note: not using these container classes means LVM devs would no more be
cached by ceph-volume.

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by rishabh-d-dave** [comment]
Rebased the PR, unit tests are passing locally. Please review the PR. @jan--f

**Comment by jan--f** [comment]
retest this please

**Comment by jan--f** [comment]
jenkins test ceph-volume tox

**Comment by rishabh-d-dave** [comment]
Just a rebase. Unit tests were passing locally.

**Comment by rishabh-d-dave** [comment]
jenkins test ceph-volume tox

**Comment by rishabh-d-dave** [comment]
jenkins test ceph-volume tox

**Comment by jan--f** [comment]
Sorry...couldn't avoid those conflicts.

**Comment by rishabh-d-dave** [comment]
No worries.

**Comment by rishabh-d-dave** [comment]
jenkins test ceph-volume tox

**Comment by rishabh-d-dave** [comment]
@jan--f Unit tests passed.

**Comment by jan--f** [comment]
Same issue as in #31700. But one of these two PRs needs a rebase after the other merged anyway.

**Comment by rishabh-d-dave** [comment]
jenkins test ceph-volume tox

**Comment by rishabh-d-dave** [comment]
jenkins test ceph-volume tox

**Comment by rishabh-d-dave** [comment]
@jan--f Rebased and tox tests have passed.

**Comment by rishabh-d-dave** [comment]
jenkins test ceph-volume tox

**Comment by rishabh-d-dave** [comment]
Replaced `get_lv` by `get_first_lv` was being used in `util/lvm.py`. See - https://github.com/ceph/ceph/pull/32493/files#diff-6993397b6f0532424603186ca62822bcL246.

**Comment by rishabh-d-dave** [comment]
@jan--f Please take a look.

**Comment by rishabh-d-dave** [comment]
jenkins test ceph-volume tox

**Comment by rishabh-d-dave** [comment]
@jan--f PTAL

**Comment by rishabh-d-dave** [comment]
jenkins test ceph-volume all

**Comment by rishabh-d-dave** [comment]
jenkins test ceph-volume all

**Comment by rishabh-d-dave** [comment]
jenkins test ceph-volume all

**Comment by rishabh-d-dave** [comment]
jenkins test ceph-volume all

**Comment by rishabh-d-dave** [comment]
jenkins test ceph-volume all

**Comment by rishabh-d-dave** [comment]
jenkins test ceph-volume tox

**Comment by rishabh-d-dave** [comment]
jenkins test ceph-volume all

**Comment by rishabh-d-dave** [comment]
Hi @jan--f, 

I need a little help fixing the errors on CI right now. I see two kinds of them. Here's the error message on the [first one](https://jenkins.ceph.com/job/ceph-volume-prs-batch-centos8-bluestore-mixed_type_dmcrypt/15/consoleFull#-1721273226c19247c4-fcb7-4c61-9a5d-7e2b9731c678) -
```
RuntimeError: Command failed with exit code 250: /bin/ceph-osd --cluster test --osd-objectstore bluestore --mkfs -i 0 --monmap /var/lib/ceph/osd/test-0/activate.monmap --keyfile - --bluestore-block-db-path /dev/ceph-block-efb174a5-8296-4173-b01d-316ea03d4d95/osd-block-dab5dee1-651c-461a-8535-824c73e1fe9a --osd-data /var/lib/ceph/osd/test-0/ --osd-uuid 939a14f9-3c97-4662-a2d5-1c9888dc965f --setuser ceph --setgroup ceph
```

I don't see the reason for failure so I took at look at the [osd log](https://jenkins.ceph.com/job/ceph-volume-prs-batch-centos8-bluestore-mixed_type_dmcrypt/15/artifact/logs/osd0/test-osd.0.log) and I find the following entries that probably indicate problem -
```
2020-04-17T10:39:15.534+0000 7f8955287ec0  1 bdev(0x55ceaf148700 /var/lib/ceph/osd/test-0//block.db) open path /var/lib/ceph/osd/test-0//block.db
2020-04-17T10:39:15.534+0000 7f8955287ec0 -1 bdev(0x55ceaf148700 /var/lib/ceph/osd/test-0//block.db) _lock flock failed on /var/lib/ceph/osd/test-0//block.db
2020-04-17T10:39:15.534+0000 7f8955287ec0 -1 bdev(0x55ceaf148700 /var/lib/ceph/osd/test-0//block.db) open failed to lock /var/lib/ceph/osd/test-0//block.db: (11) Resource temporarily unavailable
2020-04-17T10:39:15.534+0000 7f8955287ec0 -1 bluestore(/var/lib/ceph/osd/test-0/) _minimal_open_bluefs add block device(/var/lib/ceph/osd/test-0//block.db) returned: (11) Resource temporarily unavailable
```

Here's the error message on the [second kind of failure](https://jenkins.ceph.com/job/ceph-volume-prs-batch-centos8-filestore-single_type/15/consoleFull#1064864757c19247c4-fcb7-4c61-9a5d-7e2b9731c678) -

```
   def test_osd_are_mounted(self, node, host):
        # TODO: figure out way to paramaterize node['osd_ids'] for this test
        for osd_id in node["osd_ids"]:
            osd_path = "/var/lib/ceph/osd/{cluster}-{osd_id}".format(
                cluster=node["cluster_name"],
                osd_id=osd_id,
            )
>           assert host.mount_point(osd_path).exists
E           assert False
E            +  where False = <[KeyError("u'device'") raised in repr()] SafeRepr object at 0x7f80a6d70518>.exists
E            +    where <[KeyError("u'device'") raised in repr()] SafeRepr object at 0x7f80a6d70518> = <class 'testinfra.modules.base.LinuxMountPoint'>('/var/lib/ceph/osd/test-0')
E            +      where <class 'testinfra.modules.base.LinuxMountPoint'> = <testinfra.host.Host object at 0x7f80a6d10250>.mount_point

../../../../tests/osd/test_osds.py:33: AssertionError
```

I don't understand how's this failure relates to the changes and what part of my patch should I start looking at.

It would be great if can get few hints on both of these.

**Comment by andrewschoen** [comment]
jenkins test ceph-volume batch centos8-bluestore-mixed_type_dmcrypt

**Comment by rishabh-d-dave** [comment]
jenkins test ceph-volume tox

**Comment by rishabh-d-dave** [comment]
jenkins test ceph-volume all

**Comment by rishabh-d-dave** [comment]
jenkins test ceph-volume all

**Comment by rishabh-d-dave** [comment]
The CI results for this PR are a mess. Few jobs in last run ended with `/tmp/jenkins161253791766741144.sh: line 1086: cd: /home/jenkins-build/build/workspace/ceph-volume-prs-batch-centos8-bluestore-mixed_type/src/ceph-volume/ceph_volume/tests/functional: No such file or directory`  and many are still jobs are marked yellow even though they ran to fail/succeed. Re-triggering tests again

**Comment by rishabh-d-dave** [comment]
jenkins test ceph-volume all

**Comment by rishabh-d-dave** [comment]
jenkins test ceph-volume all

**Comment by rishabh-d-dave** [comment]
Following is first where an OSD fails to start -
```
TASK [ceph-osd : wait for all osd to be up] ************************************
task path: /tmp/tox.eyyDMg6p5q/centos8-bluestore-mixed_type_dmcrypt_explicit/tmp/ceph-ansible/roles/ceph-osd/tasks/main.yml:75
skipping: [mon0] => {
    "changed": false, 
    "skip_reason": "Conditional result was False"
}
FAILED - RETRYING: wait for all osd to be up (60 retries left).
FAILED - RETRYING: wait for all osd to be up (59 retries left).
FAILED - RETRYING: wait for all osd to be up (58 retries left).
FAILED - RETRYING: wait for all osd to be up (57 retries left).
FAILED - RETRYING: wait for all osd to be up (56 retries left).

FAILED - RETRYING: wait for all osd to be up (4 retries left).
FAILED - RETRYING: wait for all osd to be up (3 retries left).
FAILED - RETRYING: wait for all osd to be up (2 retries left).
FAILED - RETRYING: wait for all osd to be up (1 retries left).
fatal: [osd0 -> mon0]: FAILED! => {
    "attempts": 60, 
    "changed": false, 
    "cmd": [
        "ceph", 
        "--cluster", 
        "test", 
        "-s", 
        "-f", 
        "json"
    ], 
    "delta": "0:00:00.579524", 
    "end": "2020-05-11 11:13:18.382274", 
    "rc": 0, 
    "start": "2020-05-11 11:13:17.802750"
}
```

I found this entry in logs interesting and related -
```
2020-05-11T11:02:15.670+0000 7f6706777ec0  1 bdev(0x55f8a9200700 /var/lib/ceph/osd/test-1/block.db) open path /var/lib/ceph/osd/test-1/block.db
2020-05-11T11:02:15.672+0000 7f6706777ec0 -1 bdev(0x55f8a9200700 /var/lib/ceph/osd/test-1/block.db) _lock flock failed on /var/lib/ceph/osd/test-1/block.db
2020-05-11T11:02:15.672+0000 7f6706777ec0 -1 bdev(0x55f8a9200700 /var/lib/ceph/osd/test-1/block.db) open failed to lock /var/lib/ceph/osd/test-1/block.db: (11) Resource temporarily unavailable
2020-05-11T11:02:15.672+0000 7f6706777ec0 -1 bluestore(/var/lib/ceph/osd/test-1) _minimal_open_bluefs add block device(/var/lib/ceph/osd/test-1/block.db) returned: (11) Resource temporarily unavailable
```
Here's the link to the log - https://jenkins.ceph.com/job/ceph-volume-prs-batch-centos8-bluestore-mixed_type_dmcrypt_explicit/22/artifact/logs/osd0/test-osd.1.log


These are the CI jobs where I spot these errors -
https://jenkins.ceph.com/job/ceph-volume-prs-batch-centos8-bluestore-mixed_type/23/consoleFull#1315971580c19247c4-fcb7-4c61-9a5d-7e2b9731c678
https://jenkins.ceph.com/job/ceph-volume-prs-batch-centos8-bluestore-mixed_type_dmcrypt/23/consoleFull#-1721273226c19247c4-fcb7-4c61-9a5d-7e2b9731c678
https://jenkins.ceph.com/job/ceph-volume-prs-batch-centos8-bluestore-mixed_type_dmcrypt_explicit/22/consoleFull#1467995669c19247c4-fcb7-4c61-9a5d-7e2b9731c678

**Comment by rishabh-d-dave** [comment]
Second issue is where `test_osds_listen_on_cluster_network` fails -
```
    def test_osds_listen_on_public_network(self, node, host):
        # TODO: figure out way to paramaterize this test
        nb_port = (node["num_osds"] * node["num_osd_ports"])
>       assert host.check_output(
            "netstat -lntp | grep ceph-osd | grep %s | wc -l" % (node["address"])) == str(nb_port)  # noqa E501
E       AssertionError: assert '4' == '8'
E         - 4
E         + 8
```

I understand the error per se about I am clueless about what change in ceph-volume codebase led to this.
Here's the CI job - https://jenkins.ceph.com/job/ceph-volume-prs-batch-centos8-bluestore-mixed_type_explicit/22/consoleFull#1264254799c19247c4-fcb7-4c61-9a5d-7e2b9731c678

This one too has `Resource temporarily unavailable` message -
```
2020-05-11T10:55:19.458+0000 7f618de4eec0 -1 bdev(0x559f1799a700 /var/lib/ceph/osd/test-0/block.db) _lock flock failed on /var/lib/ceph/osd/test-0/block.db
2020-05-11T10:55:19.458+0000 7f618de4eec0 -1 bdev(0x559f1799a700 /var/lib/ceph/osd/test-0/block.db) open failed to lock /var/lib/ceph/osd/test-0/block.db: (11) Resource temporarily unavailable
2020-05-11T10:55:19.458+0000 7f618de4eec0 -1 bluestore(/var/lib/ceph/osd/test-0) _minimal_open_bluefs add block device(/var/lib/ceph/osd/test-0/block.db) returned: (11) Resource temporarily unavailable
```
https://jenkins.ceph.com/job/ceph-volume-prs-batch-centos8-bluestore-mixed_type_explicit/22/artifact/logs/osd0/test-osd.0.log

**Comment by rishabh-d-dave** [comment]
jenkins test ceph-volume all

**Comment by rishabh-d-dave** [comment]
jenkins test ceph-volume all

**Comment by rishabh-d-dave** [comment]
jenkins test ceph-volume all

**Comment by rishabh-d-dave** [comment]
jenkins test ceph-volume all

**Comment by rishabh-d-dave** [comment]
In context to my last comment (https://github.com/ceph/ceph/pull/32493#issuecomment-626693178) -

The bug was was due a call to `get_first_lv()` in activate.py's `get_osd_device_path()` that didn't pass appropriate LVM tags in the parameter `tags`.

**Comment by andrewschoen** [comment]
jenkins test ceph-volume tox

**Comment by rishabh-d-dave** [comment]
Locally tox tests ran successfully -

```
================================================================================================= 1877 passed, 1 skipped in 60.87s (0:01:00) =================================================================================================
flake8 create: /home/fedora31/repos/ceph/cv/src/ceph-volume/.tox/flake8
flake8 installdeps: flake8
flake8 inst: /home/fedora31/repos/ceph/cv/src/ceph-volume/.tox/.tmp/package/1/ceph-volume-1.0.0.zip
flake8 installed: ceph-volume @ file:///home/fedora31/repos/ceph/cv/src/ceph-volume/.tox/.tmp/package/1/ceph-volume-1.0.0.zip,flake8==3.8.3,importlib-metadata==1.6.1,mccabe==0.6.1,pycodestyle==2.6.0,pyflakes==2.2.0,zipp==3.1.0
flake8 run-test-pre: PYTHONHASHSEED='123449490'
flake8 run-test: commands[0] | flake8 ceph_volume
__________________________________________________________________________________________________________________ summary ___________________________________________________________________________________________________________________
  py27: commands succeeded
  py35: commands succeeded
  py36: commands succeeded
  flake8: commands succeeded
  congratulations :)
[fedora31@fedora31 ceph_volume]$ echo $?
0
[fedora31@fedora31 ceph_volume]$ git branch
* cv-use-dash-S-everywhere
  cv-use-dash-S-everywhere-bugfixed
  master
[fedora31@fedora31 ceph_volume]$ git show
commit ef22f59d8bd7c90e5fbf367fb252ed31ae11df87 (HEAD -> cv-use-dash-S-everywhere, ghfork/cv-use-dash-S-everywhere)
Author: Rishabh Dave <ridave@redhat.com>
Date:   Sat Jan 4 13:54:58 2020 +0530
```

Triggering tox tests again.

**Comment by rishabh-d-dave** [comment]
jenkins test ceph-volume tox

**Comment by rishabh-d-dave** [comment]
tox tests passed.

**Comment by rishabh-d-dave** [comment]
@andrewschoen Thanks for reviewing!

**Comment by jan--f** [comment]
Hmm something still not quite right here. I finally managed to track down a fix for the lvm function suite (see https://github.com/ceph/ceph-ansible/pull/5413). A local run fails and warrants a closer look.

The failure starts here https://github.com/ceph/ceph/blob/master/src/ceph-volume/ceph_volume/tests/functional/lvm/playbooks/test_bluestore.yml#L117
An LV with the same name (but different VG) is setup and then zapped. This fails cause ceph-volume tries to zap `test_group/data-lv1` instead of `test_zap/data-lv1` (note the differing VG name).
Given that this PR reworks how LVs are retrieved, I'd like to hold this up for now.

**Comment by rishabh-d-dave** [comment]
jenkins test ceph-volume all

**Comment by rishabh-d-dave** [comment]
jenkins test ceph-volume all

**Comment by rishabh-d-dave** [comment]
jenkins test ceph-volume all

**Comment by rishabh-d-dave** [comment]
jenkins test ceph-volume all

**Comment by rishabh-d-dave** [comment]
jenkins test ceph-volume all

**Comment by rishabh-d-dave** [comment]
jenkins test ceph-volume all

**Comment by rishabh-d-dave** [comment]
jenkins test ceph-volume all

**Comment by rishabh-d-dave** [comment]
@andrewschoen @jan--f LVM functional tests to passed. Please take a look again.

The changes that fixed these jobs are https://github.com/ceph/ceph/pull/32493/files#diff-c3f8cf10c8e54b3638351ad4790ebcb9R35 and https://github.com/ceph/ceph/pull/32493/files#diff-27451525913c597da5fe65a3dd974a1bR241.

**Comment by jan--f** [comment]
jenkins test ceph-volume tox

**Comment by rishabh-d-dave** [comment]
jenkins test ceph-volume all

**Comment by rishabh-d-dave** [comment]
jenkins test ceph-volume tox

**Comment by rishabh-d-dave** [comment]
jenkins test ceph-volume tox

**Comment by rishabh-d-dave** [comment]
Can't reproduce the error on tox job, tried fedora 31 as well as centos 8.

**Comment by rishabh-d-dave** [comment]
jenkins test ceph-volume tox

**Comment by rishabh-d-dave** [comment]
@jan--f @andrewschoen tox tests too passed.

**Comment by rishabh-d-dave** [comment]
Rebased my branch since "make check" wasn't passing and the failure isn't related to this PR.

**Comment by rishabh-d-dave** [comment]
jenkins test ceph-volume tox

**Comment by rishabh-d-dave** [comment]
jenkins test ceph-volume all

**Comment by rishabh-d-dave** [comment]
jenkins test ceph-volume tox

**Comment by rishabh-d-dave** [comment]
jenkins test ceph-volume all

**Pull request merged**
