### PR TITLE
mon: standardize Ceph removal commands

### PR DESCRIPTION
**Pull request by yangdongsheng**
Many commands do remove/rm/del/delete, and we're sort of random about which verb applies to which command.  This PR make the all behaviour works in "remove" subcommand. For the backforward compatibility, I am keeping the all other subcommands here, just adding a "remove" subcommand as an alias for them.

Fix 14363 & 11385

### CODE REVIEW

**Comment by liewegas** [comment]
I'm inclined to standardize on 'rm' instead of 'remove', but that's just me.. any other opinions?

**Comment by jdurgin** [comment]
+1 to `rm` - that matches the `rados`, `rbd`, and most of `radosgw-admin`, though the latter could use some synonyms for consistency.

**Comment by yangdongsheng** [comment]
Hi @liewegas and @jdurgin , "matching with rados, rbd and most of radosgw-admin" makes sense to me. Will update this branch to 'rm'. Thanx for your sugguestion. :)

**Comment by yangdongsheng** [comment]
@liewegas and @jdurgin  updated, please help to take a look.

**Comment by jdurgin** [comment]
lgtm, needs a rebase now

**Comment by yangdongsheng** [comment]
@jdurgin rebased! In addition, there is another commit to change 'fs remove_data_pool' to 'fs rm_data_pool'. As 'fs remove_data_pool' is newly introduced command, let's change it to 'fs rm_data_pool' immediately rather than introduce another alias for it. What do you think about it? @liewegas and @jdurgin  :)

**Comment by jdurgin** [comment]
looks good, there's just one other reference I see to 'fs remove_data_pool' to change in doc/cephfs/administration.rst

**Comment by jdurgin** [comment]
@jcsp may want to see the last commit too

**Comment by yangdongsheng** [comment]
@jdurgin Thanx, I will update the doc soon. @jcsp Please help to take a look at the change about 'fs rm_data_pool'. thanx :)

**Comment by yangdongsheng** [comment]
@jdurgin updated, @jcsp Please help to take a look at the last commit. thanx :)

**Comment by jdurgin** [comment]
lgtm, thanks!

**Pull request merged**
