### PR TITLE
make the all osd/filestore thread pool suicide timeouts separately configurable

### PR DESCRIPTION
**Pull request by theanalyst**
http://tracker.ceph.com/issues/11701

### CODE REVIEW

**Comment by dachary** [comment]
could you please amend a1f895d to state how the conflict was resolved ?

**Comment by athanatos** [comment]
@theanalyst ^

**Comment by theanalyst** [comment]
@athantos.. sorry that was a case of me wrongly picking the option during a merge conflict.. fixing...

**Comment by theanalyst** [comment]
@athanatos / @dachary  updated..

**Comment by athanatos** [comment]
Looks right to me.

**Pull request merged**
