### PR TITLE
test/objectstore: include missing headerfile for get_csum_type_string

### PR DESCRIPTION
**Pull request by wjwithagen**
Otherwise during linking there is no matching definition:
```
[ 88%] Linking CXX executable ../../../bin/unittest_bluestore_types
/usr/local/bin/ld: CMakeFiles/unittest_bluestore_types.dir/test_bluestore_types.cc.o: in function `bluestore_blob_t_csum_bench_Test::TestBody()':
/home/jenkins/workspace/ceph-master-compile/src/test/objectstore/test_bluestore_types.cc:332: undefined reference to `std::__1::basic_ostream<char, std::__1::char_traits<char> >& std::operator<< <long long, std::__1::ratio<1l, 1000000000l> >(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> > const&)'
```

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by tchaikov** [comment]
@wjwithagen i don't understand how come including this header file could address the link issue. in my case, 

```console
$ nm -C ./src/common/CMakeFiles/common-common-objs.dir/ceph_time.cc.o | grep 'chrono::duration' | grep 'operator<<'
0000000000000000 W std::ostream& std::operator<< <long, std::ratio<1l, 1000000000l> >(std::ostream&, std::chrono::duration<long, std::ratio<1l, 1000000000l> > const&)
0000000000000000 W std::ostream& std::operator<< <long, std::ratio<1l, 1000l> >(std::ostream&, std::chrono::duration<long, std::ratio<1l, 1000l> > const&)
0000000000000000 W std::ostream& std::operator<< <long, std::ratio<1l, 1l> >(std::ostream&, std::chrono::duration<long, std::ratio<1l, 1l> > const&)
0000000000000000 W std::ostream& std::operator<< <unsigned long, std::ratio<1l, 1000000000l> >(std::ostream&, std::chrono::duration<unsigned long, std::ratio<1l, 1000000000l> > const&)

$ nm -C -D /var/ssd/ceph/build/lib/libceph-common.so.2  | grep 'chrono::duration' | grep 'operator<<'
000000000179b70e T operator<<(std::ostream&, boost::variant<boost::blank, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, unsigned long, long, double, bool, entity_addr_t, entity_addrvec_t, std::chrono::duration<long, std::ratio<1l, 1l> >, std::chrono::duration<long, std::ratio<1l, 1000l> >, Option::size_t, uuid_d> const&)
00000000016eb91a W std::ostream& std::operator<< <long, std::ratio<1l, 1000000000l> >(std::ostream&, std::chrono::duration<long, std::ratio<1l, 1000000000l> > const&)
00000000016eb97a W std::ostream& std::operator<< <long, std::ratio<1l, 1000l> >(std::ostream&, std::chrono::duration<long, std::ratio<1l, 1000l> > const&)
00000000016eb94a W std::ostream& std::operator<< <long, std::ratio<1l, 1l> >(std::ostream&, std::chrono::duration<long, std::ratio<1l, 1l> > const&)
00000000016eb8ea W std::ostream& std::operator<< <unsigned long, std::ratio<1l, 1000000000l> >(std::ostream&, std::chrono::duration<unsigned long, std::ratio<1l, 1000000000l> > const&)

$ ldd  bin/unittest_bluestore_types | grep ceph-common
        libceph-common.so.2 => /var/ssd/ceph/build/lib/libceph-common.so.2 (0x00007f9259c17000)
```

the symbol of `std::ostream& std::operator<< <unsigned long, std::ratio<1l, 1000000000l> >(std::ostream&, std::chrono::duration<unsigned long, std::ratio<1l, 1000000000l> > const&)` is used. and since `unittest_bluestore_types` links against ceph-common, i think linker should be able to find it. could you paste the output of the command lines above?

**Comment by wjwithagen** [comment]
@tchaikov 
I checked this "fix" on the commandline, and there building completed just fine....
But then this morning Jenkins still complains. 

So i'll try and figure it out allong the lines you suggested, which was my second idea.
But things seemed fixed after this PR...

I'll be back

**Comment by wjwithagen** [comment]
Seems everything is there:

```
[~/master] wjw@cephdev12.digiware.nl> nm -C ./build/src/common/CMakeFiles/common-common-objs.dir/ceph_time.cc.o | grep 'chrono::duration' | grep 'operator<<'
0000000000000000 W std::__1::basic_ostream<char, std::__1::char_traits<char> >& std::operator<< <long, std::__1::ratio<1l, 1000000000l> >(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, std::__1::chrono::duration<long, std::__1::ratio<1l, 1000000000l> > const&)
0000000000000000 W std::__1::basic_ostream<char, std::__1::char_traits<char> >& std::operator<< <unsigned long, std::__1::ratio<1l, 1000000000l> >(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, std::__1::chrono::duration<unsigned long, std::__1::ratio<1l, 1000000000l> > const&)
0000000000000000 W std::__1::basic_ostream<char, std::__1::char_traits<char> >& std::operator<< <long long, std::__1::ratio<1l, 1000l> >(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000l> > const&)
0000000000000000 W std::__1::basic_ostream<char, std::__1::char_traits<char> >& std::operator<< <long long, std::__1::ratio<1l, 1l> >(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1l> > const&)
[~/master] wjw@cephdev12.digiware.nl> nm -C -D ./build/lib/libceph-common.so.2 | grep 'chrono::duration' | grep 'operator<<'                      000000000128a9e0 W std::__1::basic_ostream<char, std::__1::char_traits<char> >& std::operator<< <long, std::__1::ratio<1l, 1000000000l> >(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, std::__1::chrono::duration<long, std::__1::ratio<1l, 1000000000l> > const&)
000000000128a920 W std::__1::basic_ostream<char, std::__1::char_traits<char> >& std::operator<< <unsigned long, std::__1::ratio<1l, 1000000000l> >(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, std::__1::chrono::duration<unsigned long, std::__1::ratio<1l, 1000000000l> > const&)
000000000128ab60 W std::__1::basic_ostream<char, std::__1::char_traits<char> >& std::operator<< <long long, std::__1::ratio<1l, 1000l> >(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000l> > const&)
000000000128aaa0 W std::__1::basic_ostream<char, std::__1::char_traits<char> >& std::operator<< <long long, std::__1::ratio<1l, 1l> >(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1l> > const&)
000000000134ea40 T operator<<(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, boost::variant<boost::blank, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, unsigned long, long, double, bool, entity_addr_t, entity_addrvec_t, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1l> >, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000l> >, Option::size_t, uuid_d> const&)
[~/master] wjw@cephdev12.digiware.nl>
```
Since linking does not complete, I cannot check for the correct linkage on the executable.

But these should match?? 
Or is `std::ostream&` versus `td::__1::basic_ostream<char, std::__1::char_traits<char> >&` te problem?
```
Error: std::ostream& std::operator<< <unsigned long, std::ratio<1l, 1000000000l> >(std::ostream&, std::chrono::duration<unsigned long, std::ratio<1l, 1000000000l> > const&)
from lib: 000000000128a920 W std::__1::basic_ostream<char, std::__1::char_traits<char> >& std::operator<< <unsigned long, std::__1::ratio<1l, 1000000000l> >(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, std::__1::chrono::duration<unsigned long, std::__1::ratio<1l, 1000000000l> > const&)
```

**Comment by tchaikov** [comment]
i see, the Rep template parameter used to instantiate the `std::chrono::duration<>` template class in `src/test/objectstore/test_bluestore_types.cc` is `long long` + `std::nano`. while we only instantiate following combinations

- `uint64_t` + `std::nano` => `unsigned long` on FreeBSD + amd64 + clang + libc++
- `int64_t` + `std::nano` => `long` on FreeBSD + amd64 + clang + libc++
- `long long` + ``
- `long long` + `milliseconds`

i think the reason why you ran into this issue is that libc++ `std::chrono::nanoseconds::rep` is `long long` instead of `long`. 

ceph::mono_clock::time_point` should be represented using `long long` instead of `long` or `unsigned long`. so i think the right fix is probably to cast the duration to a "known" type.  i created #38882  to address this issue. could you please help review and test it?

**Pull request closed without merging**
