### PR TITLE
rgw: add list user admin OP API

### PR DESCRIPTION
**Pull request by oshynsong**
The radosgw-admin tool support the `user list` subcommand to list radosgw users, but there is no user listing function for the admin OP API. It needs to support this API.

Signed-off-by: Oshyn Song <dualyangsong@gmail.com>

### CODE REVIEW

**Comment by cbodley** [comment]
it looks like RGWOp_Metadata_List can already list users at /admin/metadata/user. i'm not against adding an alias to RGWHandler_User, but we should find a way to share the code instead of duplicating it

**Comment by cbodley** [comment]
the admin api tests are located in qa/tasks/radosgw_admin_rest.py. i don't think they can be run manually, but i'm happy to help run any changes through our test suite

**Comment by weiqiaomiao** [comment]
user list command is already add to master in this pr : https://github.com/ceph/ceph/pull/10000/

**Comment by cbodley** [comment]
thanks @weiqiaomiao, that covers the radosgw-admin command. but we also expose many admin operations through a rest api under /admin/, and that's what this pr is adding

**Comment by oshynsong** [comment]
@cbodley the unit tests are added and please have a review, thanks.

**Comment by cbodley** [comment]
i started the radosgw_admin_rest.py tests here: http://pulpito.ceph.com/cbodley-2018-11-26_21:48:21-rgw-wip-pr-25073-distro-basic-smithi/

**Comment by cbodley** [comment]
oops, it looks like http://pulpito.ceph.com/cbodley-2018-11-26_21:48:21-rgw-wip-pr-25073-distro-basic-smithi/ didn't actually run these new tests, and we're seeing failures there now. i've opened https://github.com/ceph/ceph/pull/25305 to fix a couple issues with the test

**Comment by cbodley** [comment]
i'm also wondering if it makes more sense to expose this request as `GET /admin/users` instead of `GET /admin/user/?list`, but i'm hesitant to change that if the dashboard is already using it as is

**Comment by oshynsong** [comment]
> i'm also wondering if it makes more sense to expose this request as `GET /admin/users` instead of `GET /admin/user/?list`, but i'm hesitant to change that if the dashboard is already using it as is

I think `GET /admin/user/?list` is just OK which is more friendly with the method implementation of `RGWHandler_User::op_get()` in `src/rgw/rgw_rest_user.cc`.

**Comment by votdev** [comment]
@cbodley 
The dashboard PR #25300 is still open, so feel free to fix that. I would like to see a clean interface, too.

**Comment by votdev** [comment]
I would also like to see the feature to collect all user info with one call, not only the names of the available users.

Currently the Ceph Dashboard needs to get the list of users and then call N times /admin/user?uid=xxx to retrieve the required information. Additionally the ability to filter on server side would be great, too. See https://tracker.ceph.com/issues/22168 for more information.

P.S.: Sorry for hijacking this thread.

**Pull request merged**
