### PR TITLE
squid: RADOS: Generalize stretch mode pg temp handling to be usable without stretch mode

### PR DESCRIPTION
**Pull request by kamoltat**
### ATTENTION:
THIS PR SHOULD BE TESTED IN CONJUNCTION WITH https://github.com/ceph/ceph/pull/57381
Recommend merging https://github.com/ceph/ceph/pull/57381 before this PR.

In the command `ceph osd pool stretch set`

```
<pool> <peering_crush_bucket_count>
<peering_crush_bucket_target> <peering_crush_bucket_barrier> <crush_rule> <size> <min_size>
```

user has the option of setting the value of `peering_crush_bucket_{count|target|barrier}`.
This will then allow the utilization `calc_replicated_acting_stretch`,
since with `peering_crush_bucket_count != 0`
the pool is now a stretch_pool and we can handle pg_temp
better by setting barriers and limits to how much OSDs
should be in a `pg_temp`.

This will enable the specify pool to
handle `pg_temp` properly during `create_acting`, as a stretch pool
should.

Users can also use the command:
`osd pool stretch show <pool> `

to show all the stretch related information for the pool

pool: cephfs.a.data
pool_id: 3
is_stretch_pool: 1
peering_crush_bucket_count: 3
peering_crush_bucket_target: 3
peering_crush_bucket_barrier: 8
crush_rule: replicated_rule_custom
size: 3
min_size: 2

Users can also unset the stretch pool with the command:
`osd pool stretch unset <pool>`

However, the pool must be a stretch pool.

Backporting relevant commit(s) from main PR(s):

https://github.com/ceph/ceph/pull/56233

Fixes: https://tracker.ceph.com/issues/64802

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [x] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [x] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Comment by kamoltat** [comment]
I was running this PR + https://github.com/ceph/ceph/pull/59083 against the RADOS suite: https://pulpito.ceph.com/ksirivad-2024-08-20_21:44:57-rados-wip-ksirivad-59083-and-59084-distro-default-smithi/

Failed a netsplit test: https://pulpito.ceph.com/ksirivad-2024-08-20_21:44:57-rados-wip-ksirivad-59083-and-59084-distro-default-smithi/7864599/

Realized that it is because we rely on a change in this particular commit: 8060ea39047f1aad0c348011022e170e2b13c664
in this PR: https://github.com/ceph/ceph/pull/58669.

Therefore, will rebuild again with a new branch that will include all the commits in https://github.com/ceph/ceph/pull/58669/commits.

**Comment by kamoltat** [comment]
re-running with the included https://github.com/ceph/ceph/pull/58669/commits: https://pulpito.ceph.com/ksirivad-2024-08-22_23:52:06-rados:singleton-wip-ksirivad-59083-and-59084-and-58669-distro-default-smithi/7867623/

Lets see if we this solves the issue

**Comment by kamoltat** [comment]
[### RADOS Approved: 
**The branch wip-ksirivad-59083-and-59084-and-58669 includes PRs:** 
(we should merge these PRs in this order)
- https://github.com/ceph/ceph/pull/58669 
- https://github.com/ceph/ceph/pull/59083
- https://github.com/ceph/ceph/pull/59084 

/a/[ksirivad-2024-08-24_03:10:26-rados-wip-ksirivad-59083-and-59084-and-58669-distro-default-smithi](https://pulpito.ceph.com/ksirivad-2024-08-24_03:10:26-rados-wip-ksirivad-59083-and-59084-and-58669-distro-default-smithi/#collapseOne)
 Failure, dead Unrelated:

-  https://tracker.ceph.com/issues/65824 - rados/thrash-old-clients: cluster [WRN] Health detail: HEALTH_WARN noscrub flag(s) set" in cluster log
- https://tracker.ceph.com/issues/67684 - cephadm: orch/cephadm suite tasks using nvme-loop on centos 9 failing on `nvme connect` command
- https://tracker.ceph.com/issues/64870 - Health check failed: 1 osds down (OSD_DOWN)" in cluster log
- https://tracker.ceph.com/issues/65826 - test_default_progress_test (tasks.mgr.test_progress.TestProgress) remove_pool assert pool_name in self.pool
- https://tracker.ceph.com/issues/59380 - test failing from "Health check failed: 1 full osd(s) (OSD_FULL)" and "Health check failed: 1 filesystem is offline (MDS_ALL_DOWN)"
- https://tracker.ceph.com/issues/66602 - rados/upgrade: Health check failed: 1 pool(s) do not have an application enabled (POOL_APP_NOT_ENABLED)](https://github.com/ceph/ceph/pull/59084)

**Comment by kamoltat** [comment]
@gregsfortytwo need your approval for this backport

**Review by athanatos — APPROVED** [review]

**Comment by kamoltat** [comment]
jenkins test api

**Comment by kamoltat** [comment]
jenkins test make check

**Pull request merged**
