### PR TITLE
nautilus: mgr/dashboard: Validate iSCSI controls min/max value…

### PR DESCRIPTION
**Pull request by ricardoasmarques**
This PR includes multiple backports in order to avoid merging conflicts.

**nautilus: mgr/dashboard: Validate iSCSI controls**
- backport tracker: https://tracker.ceph.com/issues/40830
- backport of https://github.com/ceph/ceph/pull/28942
- parent tracker: https://tracker.ceph.com/issues/38018

---

**nautilus: mgr/dashboard: Error editing iSCSI image advanced settings**
- backport tracker: https://tracker.ceph.com/issues/42024
- backport of https://github.com/ceph/ceph/pull/30100
- parent tracker: https://tracker.ceph.com/issues/41388

---

**nautilus: mgr/dashboard: Error during iSCSI target edition**
- backport tracker: https://tracker.ceph.com/issues/42030
- backport of https://github.com/ceph/ceph/pull/30349
- parent tracker: https://tracker.ceph.com/issues/41779

---

**nautilus: mgr/dashboard: Support iSCSI target-level CHAP authentication**
- backport tracker: https://tracker.ceph.com/issues/42065
- backport of https://github.com/ceph/ceph/pull/30011
- parent tracker: https://tracker.ceph.com/issues/41576

---

**nautilus: mgr/dashboard: iSCSI control inputs should be rendered based on control "type"**
- backport tracker: https://tracker.ceph.com/issues/42066
- backport of https://github.com/ceph/ceph/pull/30208
- parent tracker: https://tracker.ceph.com/issues/41682

---

**nautilus: mgr/dashboard: Should be possible to set the iSCSI disk WWN and LUN number from the UI**

- backport tracker: https://tracker.ceph.com/issues/42679
- backport of #31056
- parent tracker: https://tracker.ceph.com/issues/41749

----------

**nautilus: mgr/dashboard: iSCSI target details should display the disk WWN and LUN number**

- backport tracker: https://tracker.ceph.com/issues/42356
- backport of #30288
- parent tracker: https://tracker.ceph.com/issues/41742

### CODE REVIEW

**Comment by ricardoasmarques** [comment]
jenkins test docs

**Comment by ricardoasmarques** [comment]
I'll include more backports in this PR to prevent conflicts.

**Comment by epuertat** [comment]
@smithfarm any idea about when this PR will become merged? It's needed for https://github.com/ceph/ceph/pull/30011 to be (smoothly) backported. Meanwhile, dashboard ceph-iscsi in nautilus is broken (version 10-11 mismatch): https://tracker.ceph.com/issues/42613

**Comment by smithfarm** [comment]
@yuriw Can you include this in your next nautilus integration run?

**Comment by smithfarm** [comment]
@epuertat If you can (1) post a passing teuthology run including `dashboard.yaml` and (2) confirm that you checked and that this PR does not touch anything outside of `src/pybind/mgr/dashboard`, then you are free to merge it.

**Comment by epuertat** [comment]
Thanks, @smithfarm! 

@ricardoasmarques as this PR already seems to be a placeholder for iSCSI related fixes, would it make sense to have https://github.com/ceph/ceph/pull/30011 grouped here? Thanks!

**Comment by smithfarm** [comment]
@epuertat #30011 is already included in this PR, though?

**Comment by ricardoasmarques** [comment]
@epuertat @smithfarm https://github.com/ceph/ceph/pull/30011 is already included in this PR.

**Comment by epuertat** [comment]
> @epuertat @smithfarm #30011 is already included in this PR.

:man_facepalming: today's not my day! Thank you, guys!

**Comment by epuertat** [comment]
Run [rados/mgr dashboard tasks](http://pulpito.front.sepia.ceph.com/epuertat-2019-11-06_10:29:55-rados:mgr-wip-epuertat-testing-2019-11-05-1725-distro-basic-smithi/) and, after ~45 min running, got 4/4 failure rate:
> Failure Reason:
> "2019-11-06 11:21:05.965297 mds.c (mds.0) 1 : cluster [WRN] evicting unresponsive client smithi117:x (7889), after 304.918 seconds" in cluster log

I'm digging into the logs (270 MB), and I'd say it's completely unrelated to this PR, but for me it's hard to understand how many tests have succeeded.

**Comment by smithfarm** [comment]
@epuertat Can you do a run on tip of nautilus?

**Comment by smithfarm** [comment]
@epuertat Also, did you rebase this PR on top of latest nautilus before pushing it to `ceph/ceph-ci.git`?

**Comment by callithea** [comment]
> Run [rados/mgr dashboard tasks](http://pulpito.front.sepia.ceph.com/epuertat-2019-11-06_10:29:55-rados:mgr-wip-epuertat-testing-2019-11-05-1725-distro-basic-smithi/) and, after ~45 min running, got 4/4 failure rate:
> 
> > Failure Reason:
> > "2019-11-06 11:21:05.965297 mds.c (mds.0) 1 : cluster [WRN] evicting unresponsive client smithi117:x (7889), after 304.918 seconds" in cluster log

This error should be fixed with PR #31114 - so if you would include this in your QA run those errors should be gone.

**Comment by epuertat** [comment]
> @epuertat Also, did you rebase this PR on top of latest nautilus before pushing it to `ceph/ceph-ci.git`?

Nope, unfortunately I didn't do that, but as @callithea mentioned the fix has been merged, I'll rebuild packages on top of latest Nautilus. Thank you both for your help!

**Comment by epuertat** [comment]
Shaman [build only succeeded on 2 distros](https://shaman.ceph.com/builds/ceph/wip-epuertat-testing-2019-11-06-1635/): centos and opensuse (and this took 3h30min to finish, so I launched the QA run before). Both results are OK:
- [4477149](http://pulpito.ceph.com/epuertat-2019-11-06_20:30:17-rados:mgr-wip-epuertat-testing-2019-11-06-1635-distro-basic-smithi/)
- [4477147](http://pulpito.ceph.com/epuertat-2019-11-06_20:29:58-rados:mgr-wip-epuertat-testing-2019-11-06-1635-distro-basic-smithi/)

**Comment by ricardoasmarques** [comment]
I've now pushed the following additional backports into this PR:

**nautilus: mgr/dashboard: iSCSI target details should display the disk WWN and LUN number**

- backport tracker: https://tracker.ceph.com/issues/42356
- backport of #30288
- parent tracker: https://tracker.ceph.com/issues/41742

----------

**nautilus: mgr/dashboard: Should be possible to set the iSCSI disk WWN and LUN number from the UI**

- backport tracker: https://tracker.ceph.com/issues/42679
- backport of #31056
- parent tracker: https://tracker.ceph.com/issues/41749

**Comment by epuertat** [comment]
Thanks, @ricardoasmarques ! Building and soon running QA for this one.

**Comment by ricardoasmarques** [comment]
> Thanks, @ricardoasmarques ! Building and soon running QA for this one.

Note that I've re-submitted one commit to fix a "make check" failure. So please make sure you are using the latest version of this PR :)

**Comment by smithfarm** [comment]
> I've now pushed the following additional backports into this PR

Appended the new backports to PR body/description so the `backport-resolve-issues` picks them up.

**Comment by LenzGr** [comment]
jenkins test dashboard

**Comment by callithea** [comment]
jenkins test dashboard

**Comment by epuertat** [comment]
QA ongoing:
- [Packages](https://shaman.ceph.com/repos/ceph/wip-epuertat-testing-2019-11-08-1153/9625f4b589842809ab34e0484aaab97fa4697834/)
- [Teuthology run](http://pulpito.ceph.com/epuertat-2019-11-08_13:51:30-rados:mgr-wip-epuertat-testing-2019-11-08-1153-distro-basic-smithi/)

**Pull request merged**
