### PR TITLE
mgr/cephadm: clean-up service module type checking

### PR DESCRIPTION
**Pull request by mgfritch**
Signed-off-by: Michael Fritch <mfritch@suse.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by sebastian-philipp** [comment]
hm. still getting 

```
================= 851 passed, 3 skipped, 6 warnings in 14.14s ==================
mypy create: /home/jenkins-build/build/workspace/ceph-pull-requests/src/pybind/mgr/.tox/mypy
mypy installdeps: cython, -rrequirements.txt, mypy==0.782
mypy installed: -f /home/jenkins-build/build/workspace/ceph-pull-requests/src/pybind/mgr/wheelhouse,apipkg==1.5,attrs==19.3.0,cachetools==4.1.1,-e git+https://github.com/ceph/ceph.git@a3e11a0ebb8470f98a7a7e43d2c9d78dfc6dc8bf#egg=ceph&subdirectory=src/python-common,certifi==2020.6.20,cffi==1.14.0,chardet==3.0.4,coverage==5.2,cryptography==2.9.2,Cython==0.29.21,execnet==1.7.1,google-auth==1.19.1,idna==2.10,importlib-metadata==1.7.0,Jinja2==2.11.2,kubernetes==11.0.0,MarkupSafe==1.1.1,more-itertools==8.4.0,mypy==0.782,mypy-extensions==0.4.3,oauthlib==3.1.0,packaging==20.4,pluggy==0.13.1,prettytable==0.7.2,py==1.9.0,pyasn1==0.4.8,pyasn1-modules==0.2.8,pycparser==2.20,pyfakefs==4.1.0,pyOpenSSL==19.1.0,pyparsing==2.4.7,pytest==5.4.3,pytest-cov==2.7.1,python-dateutil==2.8.1,PyYAML==5.3.1,remoto==1.2.0,requests==2.24.0,requests-mock==1.8.0,requests-oauthlib==1.3.0,rsa==4.6,six==1.15.0,typed-ast==1.4.1,typing-extensions==3.7.4.2,urllib3==1.25.9,wcwidth==0.2.5,websocket-client==0.57.0,zipp==3.1.0
mypy run-test-pre: PYTHONHASHSEED='86848187'
mypy run-test: commands[0] | mypy --config-file=../../mypy.ini cephadm/module.py mgr_module.py dashboard/module.py prometheus/module.py mgr_util.py orchestrator/__init__.py progress/module.py rook/module.py osd_support/module.py test_orchestrator/module.py volumes/__init__.py
cephadm/module.py: note: In member "_config_fn" of class "CephadmOrchestrator":
cephadm/module.py:1797: error: Incompatible return value type (got "Optional[function]", expected "Optional[Callable[[ServiceSpec], None]]")
Found 1 error in 1 file (checked 11 source files)
ERROR: InvocationError for command /home/jenkins-build/build/workspace/ceph-pull-requests/src/pybind/mgr/.tox/mypy/bin/mypy --config-file=../../mypy.ini cephadm/module.py mgr_module.py dashboard/module.py prometheus/module.py mgr_util.py orchestrator/__init__.py progress/module.py rook/module.py osd_support/module.py test_orchestrator/module.py volumes/__init__.py (exited with code 1)
```

in jenkins: https://jenkins.ceph.com/job/ceph-pull-requests/55766/consoleFull#1352998141e840cee4-f4a4-4183-81dd-42855615f2c1

**Comment by mgfritch** [comment]
> cephadm/module.py: note: In member "_config_fn" of class "CephadmOrchestrator":
> cephadm/module.py:1797: error: Incompatible return value type (got "Optional[function]", expected "Optional[Callable[[ServiceSpec], None]]")
> Found 1 error in 1 file (checked 11 source files)

huh I don't see this locally ... maybe use a mypy cast?

**Comment by mgfritch** [comment]
jenkins test dashboard backend

**Comment by sebastian-philipp** [comment]
https://pulpito.ceph.com/swagner-2020-07-20_10:53:40-rados:cephadm-wip-swagner-testing-2020-07-20-1103-distro-basic-smithi/

**Comment by sebastian-philipp** [comment]
jenkins test dashboard backend

**Pull request merged**
