### PR TITLE
 doc/rados/operations: Fix typo in erasure-code.rst

### PR DESCRIPTION
**Pull request by Sainithin-bit**
## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [x] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by zdover23** [comment]
@Sainithin-bit: Follow the instructions in Step 2 here: https://docs.ceph.com/en/quincy/start/documenting-ceph/#get-the-source

That will set up your local git environment so that the command "git commit -s" will append a signed-off-by line automatically.

**Comment by zdover23** [comment]
> ok , i am sorry , i am irritating

You are not irritating. I am watching you go through exactly the same process of learning that I went through back in 2020 and 2021. I will help you with the process of making a clean PR for as long as you want my help.

If you want to see irritating, look at me back in 2020: https://github.com/ceph/ceph/pull/33545

**Comment by zdover23** [comment]
> It was a pleasure meeting you. I wanted to let you know that I think you're a really nice person. I wouldn't have completed this without your help. Thank you very much for your support.

@Sainithin-bit,

Well, thank you. I'm the Docs Lead for Upstream Ceph, so I am the ally of anyone who catches typos in the Ceph documentation. I have time for anyone who wants to make documentation better. 

If you want to keep making improvements to the Ceph docs (and you want to get more practice in a low-risk, congenial forum interactively rebasing), let me know and I'll help you find a project.

**Comment by zdover23** [comment]
> Thank you for your offer to assist with the Ceph documentation! I appreciate your willingness to help improve the quality of the documentation and your support for those who contribute to this effort.
> 
> I would definitely be interested in learning more about potential projects where I could contribute and gain experience with interactive rebasing. Please let me know
> 
> Thanks again for your offer to help, and I look forward to working with you to make the Ceph documentation even better.

New business: I recommend looking through the Architecture documentation for typos and malformed sentences: https://docs.ceph.com/en/quincy/architecture/ . The Architecture documentation gives the best aerial-view  that we currently have in the Ceph documentation, and it is also the document that I am least likely to have time to line-edit this year.

Old business: as soon as this PR passes its required checks, I will merge it. After that, I will backport it. When I do that, I will make you a reviewer of the backports. Just approve them, and I'll merge them. After that, your change will be live on docs.ceph.com.

**Review by zdover23 — APPROVED** [review]

**Comment by Sainithin-bit** [comment]
Thank you for the update.
reviewing the Architecture documentation for typos and malformed sentences is a great suggestion It is always a good idea to ensure that documentation is error-free and easy to understand for readers. it's good to see that the PR is merged.

**Comment by zdover23** [comment]
https://github.com/ceph/ceph/pull/50751 - Reef backport
https://github.com/ceph/ceph/pull/50752 - Quincy backport
https://github.com/ceph/ceph/pull/50753 - Pacific backport

**Comment by zdover23** [comment]
https://github.com/ceph/ceph/pull/50659 - original PR, superseded by this PR

**Pull request merged**
