### PR TITLE
luminous: discover_all_missing() not always called during activating

### PR DESCRIPTION
**Pull request by pdvian**
http://tracker.ceph.com/issues/26992

### CODE REVIEW

**Comment by pdvian** [comment]
@dzafman need review.

**Comment by smithfarm** [comment]
@dzafman Just to be sure, the following procedure for running `run-standalone.sh` is correct?

```
./run-make-check.sh
cd build
qa/run-standalone.sh
```

**Comment by dzafman** [comment]
@smithfarm The path to run-standalone.sh from build is ../qa/run-standalone.sh

**Comment by yuriw** [comment]
[wip-yuri4-testing-2018-09-15-1645-luminous](https://trello.com/c/ixvfj7WY/405-wip-yuri4-testing-2018-09-15-1645-luminous)

**Pull request merged**
