### PR TITLE
release-notes: draft v0.94.1 release notes

### PR DESCRIPTION
**Pull request by dachary**
Signed-off-by: Loic Dachary <ldachary@redhat.com>

### CODE REVIEW

**Comment by dachary** [comment]
@tchaikov would you have time to review this ? the idea is to help sage write the final release notes. The list of commits and their matching issue is something that cannot conveniently be done via a program although the script written by Alistair http://tracker.ceph.com/projects/ceph-releases/wiki/HOWTO_write_the_release_notes helps

**Comment by tchaikov** [comment]
@dachary sorry i didn't get a chance to look at this PR. will review it later on.

**Comment by dachary** [comment]
@tchaikov no worries, we're rushing things to get v0.94.1 out as quickly as possible :-)

**Comment by tchaikov** [comment]
ahh, 0.94.1 is going be release very soon. i will look at it sooner next time.

**Pull request merged**
