### PR TITLE
qa: TestMDSMetrics.test_delayed_metrics failure

### PR DESCRIPTION
**Pull request by neesingh-rh**
TestMDSMetrics.test_delayed_metrics is failing due to
the absence of omit_sudo parameter in the remote.run()
of set_inter_mds_block() in qa/tasks/cephfs/filesystem.py

Fixes: https://tracker.ceph.com/issues/56065
Signed-off-by: Neeraj Pratap Singh <neesingh@redhat.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by joscollin** [comment]
@neesingh-rh Can you link the failed run?

**Comment by neesingh-rh** [comment]
> @neesingh-rh Can you link the failed run?

```
2022-06-16 15:12:22,609.609 INFO:__main__:======================================================================
2022-06-16 15:12:22,609.609 INFO:__main__:ERROR: test_delayed_metrics (tasks.cephfs.test_mds_metrics.TestMDSMetrics)
2022-06-16 15:12:22,609.609 INFO:__main__:----------------------------------------------------------------------
2022-06-16 15:12:22,609.609 INFO:__main__:Traceback (most recent call last):
2022-06-16 15:12:22,609.609 INFO:__main__:  File "/home/neerajpratapsingh/projects/ceph/qa/tasks/cephfs/test_mds_metrics.py", line 245, in test_delayed_metrics
2022-06-16 15:12:22,609.609 INFO:__main__:    self.fs.set_inter_mds_block(True, mds_id_rank0, mds_id_rank1)
2022-06-16 15:12:22,609.609 INFO:__main__:  File "/home/neerajpratapsingh/projects/ceph/qa/tasks/cephfs/filesystem.py", line 452, in set_inter_mds_block
2022-06-16 15:12:22,609.609 INFO:__main__:    self._one_or_all((mds_rank_1, mds_rank_2), set_block, in_parallel=False)
2022-06-16 15:12:22,609.609 INFO:__main__:  File "/home/neerajpratapsingh/projects/ceph/qa/tasks/cephfs/filesystem.py", line 320, in _one_or_all
2022-06-16 15:12:22,609.609 INFO:__main__:    cb(mds_id)
2022-06-16 15:12:22,609.609 INFO:__main__:  File "/home/neerajpratapsingh/projects/ceph/qa/tasks/cephfs/filesystem.py", line 435, in set_block
2022-06-16 15:12:22,610.610 INFO:__main__:    remote.run(
2022-06-16 15:12:22,610.610 INFO:__main__:  File "/home/neerajpratapsingh/projects/ceph/build/../qa/tasks/vstart_runner.py", line 415, in run
2022-06-16 15:12:22,610.610 INFO:__main__:    return self._do_run(**kwargs)
2022-06-16 15:12:22,610.610 INFO:__main__:  File "/home/neerajpratapsingh/projects/ceph/build/../qa/tasks/vstart_runner.py", line 454, in _do_run
2022-06-16 15:12:22,610.610 INFO:__main__:    proc.wait()
2022-06-16 15:12:22,610.610 INFO:__main__:  File "/home/neerajpratapsingh/projects/ceph/build/../qa/tasks/vstart_runner.py", line 256, in wait
2022-06-16 15:12:22,610.610 INFO:__main__:    raise CommandFailedError(self.args, self.exitstatus)
2022-06-16 15:12:22,610.610 INFO:__main__:teuthology.exceptions.CommandFailedError: Command failed with status 4: '\nsudo() {\n    "$@"\n}\nsudo iptables -A INPUT -p tcp --dport 6814 -j REJECT -m comment --comment teuthology'
2022-06-16 15:12:22,610.610 INFO:__main__:
```

**Review by nmshelke — APPROVED** [review]
LGTM

**Review by vshankar — APPROVED** [review]
https://tracker.ceph.com/projects/cephfs/wiki/Master#2022-June-20

**Pull request merged**
