### PR TITLE
qa/mgr: Remove _wait_for_expected_get_result

### PR DESCRIPTION
**Pull request by tspmelo**
Fixes: https://tracker.ceph.com/issues/47793

Signed-off-by: Tiago Melo <tmelo@suse.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by tspmelo** [comment]
jenkins test dashboard

**Comment by s0nea** [comment]
jenkins test dashboard

**Comment by s0nea** [comment]
jenkins test make check

**Review by s0nea — APPROVED** [review]
LGTM :+1: Thank you for the cleanup!

**Review by alfonsomthd — APPROVED** [review]

**Comment by tchaikov** [comment]
- https://pulpito.ceph.com/kchai-2020-10-13_01:10:32-rados-wip-kefu-testing-2020-10-12-1615-distro-basic-smithi
- https://pulpito.ceph.com/kchai-2020-10-14_11:01:53-rados-wip-kefu-testing-2020-10-14-1541-distro-basic-smithi/
- https://pulpito.ceph.com/kchai-2020-10-15_08:32:19-rados-wip-kefu-testing-2020-10-14-1541-distro-basic-smithi/
- https://pulpito.ceph.com/kchai-2020-10-15_10:09:42-rados-wip-kefu-testing-2020-10-14-1541-distro-basic-smithi/

**Pull request merged**
