### PR TITLE
rgw: set_olh when set versioned object attrs

### PR DESCRIPTION
**Pull request by inspur-wyq**
Fixes: https://tracker.ceph.com/issues/51465

Signed-off-by: wangyunqing <wangyunqing@inspur.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by cbodley** [comment]
@inspur-wyq thanks for explaining the issue in https://tracker.ceph.com/issues/51465#note-2, i see why this only applies to versioned objects. would you be willing to write some test cases in https://github.com/ceph/s3-tests/ to cover this for both versioned and non-versioned objects, and check that their mtime increases?

**Comment by inspur-wyq** [comment]
> @inspur-wyq thanks for explaining the issue in https://tracker.ceph.com/issues/51465#note-2, i see why this only applies to versioned objects. would you be willing to write some test cases in https://github.com/ceph/s3-tests/ to cover this for both versioned and non-versioned objects, and check that their mtime increases?

https://github.com/ceph/s3-tests/pull/406
It is my first time to do it. I am not sure whether it is right or not.

**Comment by cbodley** [comment]
ping @ofriedma can you help with review and testing?

**Comment by ofriedma** [comment]
LGTM, I will run a teuthology test with the new s3 test

**Pull request closed without merging**
