### PR TITLE
pacific: Revert mon/OSDMonitor: Added extra check before mon.go_recovery_stretch_mode()

### PR DESCRIPTION
**Pull request by kamoltat**
PR https://github.com/ceph/ceph/pull/48803 introduces
a regression found only in the Pacific branch resulting in
the following issue:  https://tracker.ceph.com/issues/58239

Reverting the following commits from the Pacific branch:

94dc97005bf6406d13c3fd5a3664a1fe2f7efec9
025d3fa6b928d6fe2a794011e81db0c52d0c9cc0

Fixes: https://tracker.ceph.com/issues/58239

Signed-off-by: Kamoltat <ksirivad@redhat.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Review by ljflores — APPROVED** [review]

**Comment by kamoltat** [comment]
jenkins test signed

**Comment by kamoltat** [comment]
jenkins test docs

**Comment by kamoltat** [comment]
jenkins render docs

**Comment by ljflores** [comment]
https://pulpito.ceph.com/ksirivad-2022-12-14_20:49:09-rados:standalone-wip-lflores-testing-2022-12-14-1707-pacific-distro-default-smithi/

All failures are unrelated infra.

**Pull request merged**
