### PR TITLE
luminous: auth: ceph auth add does not sanity-check caps

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/23670

### CODE REVIEW

**Comment by liewegas** [comment]
This probably warrants a release note since we're doing more validation than we used to in a minor release.

**Comment by smithfarm** [comment]
@liewegas Done, please have a look.

**Comment by yuriw** [comment]
@smithfarm pls rebase

--- pr 21361 --- pulling https://github.com/smithfarm/ceph.git branch wip-23670-luminous
remote: Counting objects: 21, done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 21 (delta 16), reused 16 (delta 16), pack-reused 1
Unpacking objects: 100% (21/21), done.
From https://github.com/smithfarm/ceph
 * branch            wip-23670-luminous -> FETCH_HEAD
Auto-merging PendingReleaseNotes
CONFLICT (content): Merge conflict in PendingReleaseNotes
Automatic merge failed; fix conflicts and then commit the result.
Traceback (most recent call last):
  File "/home/yuriw/wip_master/src/script/build-integration-branch", line 62, in <module>
    assert not r
AssertionError

**Comment by theanalyst** [comment]
moved the doc changes to https://github.com/ceph/ceph/pull/22475

**Comment by jdurgin** [comment]
it looks like another test needs updating: http://pulpito.ceph.com/yuriw-2018-06-11_16:27:32-rados-wip-yuri3-testing-2018-06-11-1421-luminous-distro-basic-smithi/2654694/

**Comment by yuriw** [comment]
@smithfarm I hope IRC chatter below makes better sense to you:

> 
(04:58:04 PM) neha: wait, don't merge 21361
(04:59:03 PM) neha: you can merge the rest
(04:59:43 PM) neha: http://pulpito.ceph.com/yuriw-2018-06-11_16:27:32-rados-wip-yuri3-testing-2018-06-11-1421-luminous-distro-basic-smithi/2654727/ maybe related to 21361
(04:59:55 PM) yuriw: let me look
(05:00:02 PM) neha: so you could let the author of that pr know and rerun as well
(05:01:25 PM) neha: look at the last comment https://tracker.ceph.com/issues/23492#change-115532
(05:03:00 PM) neha: For this test http://pulpito.ceph.com/yuriw-2018-06-11_16:27:32-rados-wip-yuri3-testing-2018-06-11-1421-luminous-distro-basic-smithi/2654795/, we need to whitelist "OBJECT_UNFOUND"
(05:03:45 PM) yuriw: ok I will comment on PR
(05:03:49 PM) neha: and for http://pulpito.ceph.com/yuriw-2018-06-11_16:27:32-rados-wip-yuri3-testing-2018-06-11-1421-luminous-distro-basic-smithi/2654818/, we need to whitelist "PG_AVAILABILITY"

**Comment by smithfarm** [comment]
@neha-ojha @jdurgin Can you take another look here? It's not immediately apparent to me what the next step is. I gather this PR was implicated in a test failure. Maybe @yuriw could re-run that test?

**Comment by liewegas** [comment]
I'm not sure how important it is the backport this at all tbh...

**Comment by smithfarm** [comment]
@liewegas It's in jewel already, though: https://github.com/ceph/ceph/pull/21367

Probably best for someone else to do it, though, if it needs to be done.

**Pull request closed without merging**
