### PR TITLE
common: Malformed JSON command output when non-ASCII strings are present 

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/7387

### CODE REVIEW

**Comment by smithfarm** [comment]
This second commit cherry-picked from 6b68b2 fixes a FTBFS introduced by the fix for http://tracker.ceph.com/issues/7387

There is a separate tracker issue http://tracker.ceph.com/issues/11574 open for it, but since it depends on this commit, it makes sense to combine.

**Comment by smithfarm** [comment]
Hmm:
```
run_mon: 37: ./ceph-mon --id a --mkfs --mon-data=osd-pool-create/a --run-dir=osd-pool-create/a --public-addr
parse error setting 'public_addr' to '--fsid=c2773ade-e03d-4f6c-a8e8-1dee02e28e18'

./ceph-mon: mon.noname-a 127.0.0.1:6789/0 is local, renaming to mon.a
./ceph-mon: generated monmap has no fsid; use '--fsid <uuid>'
```

**Comment by dachary** [comment]
The 69dbd5c fix is correct. Could you make that an integral part of the backport, with a "Conflict" section to explain why it had to be done ? In a nutshell the CEPH_MON was introduced after firefly to allow tests to run in parallel. Back in firefly all tests use the same port because 127.0.0.1 was hardcoded. We can't conveniently backport all that's necessary for tests to run in parallel, therefore we keep the 127.0.0.1 hardcoded.

**Comment by smithfarm** [comment]
OK, how does it look now?

**Comment by dachary** [comment]
@smithfarm looks good :-)

**Comment by dachary** [comment]
@smithfarm #4788 conflicts with #4635 #4636 #4597, could you make it so they play nice together ?

**Comment by dachary** [comment]
Not only does the unit test passes, http://pulpito.ceph.com/loic-2015-07-09_21:09:04-rados-firefly-backports---basic-multi also passed. Like every teuthology suite, the rados suite heavily uses the ceph cli: it is proof enough that this change did not introduce a regression.

**Pull request merged**
