### PR TITLE
[DNM] cmake: bump to PMDK v1.10 and disable documentation

### PR DESCRIPTION
**Pull request by cyx1231st**
see https://github.com/pmem/pmdk/releases

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by cyx1231st** [comment]
@tchaikov how to let ceph/pmdk.git to include the latest changes?

**Comment by tchaikov** [comment]
@cyx1231st i've sync'ed ceph/pmdk with pmem/pmdk. all set now.

**Comment by cyx1231st** [comment]
@tchaikov thanks!

I will hold this PR for a while, seems there are some other dependencies.

**Comment by cyx1231st** [comment]
close in favor of https://github.com/ceph/ceph/pull/40493

**Pull request closed without merging**
