### PR TITLE
pacific: mds: standby-replay daemon always removed in MDSMonitor::prepare_beacon

### PR DESCRIPTION
**Pull request by batrick**
https://tracker.ceph.com/issues/56712

### CODE REVIEW

**Comment by batrick** [comment]
jenkins test api

**Comment by batrick** [comment]
jenkins test api

**Comment by batrick** [comment]
```
/home/jenkins-build/build/workspace/ceph-api/src/rgw/rgw_string.cc: In function 'bool ci_char_eq(char, char)':
/home/jenkins-build/build/workspace/ceph-api/src/rgw/rgw_string.cc:13:10: error: 'tolower' was not declared in this scope
   13 |   return tolower(c1) == tolower(c2);
      |          ^~~~~~~
```

cc @cbodley

**Comment by cbodley** [comment]
@batrick looks like we bumped the compiler version somewhere. this was fixed for quincy in https://tracker.ceph.com/issues/50924. i've just backported that to pacific in https://github.com/ceph/ceph/pull/47304

**Comment by ljflores** [comment]
Rados suite review: https://pulpito.ceph.com/?branch=wip-yuri6-testing-2022-08-04-0617-pacific

Failures, unrelated:
    1. https://tracker.ceph.com/issues/45721
    2. https://tracker.ceph.com/issues/56573
    3. https://tracker.ceph.com/issues/53501
    4. https://tracker.ceph.com/issues/53939
    5. https://tracker.ceph.com/issues/52321
    6. https://tracker.ceph.com/issues/54071
    7. https://tracker.ceph.com/issues/56097

Details:
    1. CommandFailedError: Command failed (workunit test rados/test_python.sh) FAIL: test_rados.TestWatchNotify.test - Ceph - RADOS
    2. test_cephadm.sh: KeyError: 'TYPE' - Ceph - Orchestrator
    3. Exception when running 'rook' task. - Ceph - Orchestrator
    4. ceph-nfs-upgrade, pacific: Upgrade Paused due to UPGRADE_REDEPLOY_DAEMON: Upgrading daemon osd.0 on host smithi103 failed - Ceph - Orchestrator
    5. qa/tasks/rook times out: 'check osd count' reached maximum tries (90) after waiting for 900 seconds - Ceph - Rook
    6. rados/cephadm/osds: Invalid command: missing required parameter hostname(<string>)
    7. Timeout on `sudo adjust-ulimits ceph-coverage /home/ubuntu/cephtest/archive/coverage timeout 120 ceph --cluster ceph tell osd.1 flush_pg_stats` - Ceph - RADOS

**Comment by ljflores** [comment]
jenkins test api

**Review by kotreshhr — APPROVED** [review]

**Comment by kotreshhr** [comment]
jenkins test api

**Review by vshankar — APPROVED** [review]

**Comment by yuriw** [comment]
jenkins test api

**Comment by kotreshhr** [comment]
jenkins test api

**Comment by yuriw** [comment]
jenkins test api

**Comment by kotreshhr** [comment]
@batrick Please "Rebase on #47625 to resolve API failure"

**Comment by kotreshhr** [comment]
jenkins test api

**Comment by yuriw** [comment]
@batrick this is ready for merging but API still failing :(

**Comment by batrick** [comment]
jenkins test api

**Comment by batrick** [comment]
jenkins test make check

**Comment by vshankar** [comment]
jenkins test make check

**Comment by vshankar** [comment]
jenkins test api

**Comment by tchaikov** [comment]
jenkins test make check

**Comment by tchaikov** [comment]
jenkins test api

**Pull request merged**
