### PR TITLE
reef: mgr: fix some flake8 complaints

### PR DESCRIPTION
**Pull request by nizamial09**
Signed-off-by: Nizamudeen A <nia@redhat.com>
(cherry picked from commit d199782fb5f3c22f1cd5fda6ddf1d64f40a92726)

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by nizamial09** [comment]
@adk3798 looks like its failing in reef. not sure about quincy or pacific

**Comment by adk3798** [comment]
> @adk3798 looks like its failing in reef. not sure about quincy or pacific

I don't know either. I see make check failing on all recent PRs in against those branches, but they're failing for other things. Not sure yet if that's masking this issue in those branches or it doesn't exist there. Might have to wait until whatever other failures are happening are resolved.

**Review by adk3798 — APPROVED** [review]

**Comment by nizamial09** [comment]
> > @adk3798 looks like its failing in reef. not sure about quincy or pacific
> 
> I don't know either. I see make check failing on all recent PRs in against those branches, but they're failing for other things. Not sure yet if that's masking this issue in those branches or it doesn't exist there. Might have to wait until whatever other failures are happening are resolved.

yeah exactly. seeing a lot of unrelated errors there!

**Comment by cbodley** [comment]
> @adk3798 looks like its failing in reef. not sure about quincy or pacific

@nizamial09 i do see quincy builds failing here: https://github.com/ceph/ceph/pull/52564#issuecomment-1662625588

**Comment by cbodley** [comment]
i opened the quincy backport in https://github.com/ceph/ceph/pull/52770. the commit didn't apply cleanly on pacific

**Comment by cbodley** [comment]
> the commit didn't apply cleanly on pacific

the change to src/pybind/mgr/crash/module.py wasn't needed on pacific, but the other two changes were: https://github.com/ceph/ceph/pull/52772

**Comment by nizamial09** [comment]
great, thank you! @cbodley

**Pull request merged**
