### PR TITLE
jewel: rgw: work around curl_multi_wait bug with non-blocking reads

### PR DESCRIPTION
**Pull request by cbodley**
pulls in some earlier fixes to resolve merge conflicts

Backport tracker: http://tracker.ceph.com/issues/17343
http://tracker.ceph.com/issues/17846

### CODE REVIEW

**Comment by cbodley** [comment]
closing until https://github.com/ceph/ceph/pull/11630 merges to master - it should be backported at the same time

**Comment by dachary** [comment]
@cbodley could you please rebase against jewel-next ? A number of backports have been merged since the last check and it would be good to get another make check with a more recent rebase.

**Comment by cbodley** [comment]
thanks @dachary, rebased and waiting on checks

**Comment by dachary** [comment]
jenkins test this please (general jenkins failure)

**Comment by dachary** [comment]
@cbodley 
<pre>
CXX      rgw/librgw_la-rgw_metadata.lo
rgw/rgw_http_client.cc:365:8: error: 'once_flag' in namespace 'std' does not name a type
 static std::once_flag detect_flag;
        ^
rgw/rgw_http_client.cc: In member function 'int RGWHTTPManager::set_threaded()':
rgw/rgw_http_client.cc:805:3: error: 'call_once' is not a member of 'std'
   std::call_once(detect_flag, detect_curl_multi_wait_bug, cct,
   ^
rgw/rgw_http_client.cc:805:18: error: 'detect_flag' was not declared in this scope
   std::call_once(detect_flag, detect_curl_multi_wait_bug, cct,
                  ^
make[3]: *** [rgw/librgw_la-rgw_http_client.lo] Error 1
</pre>

**Comment by cbodley** [comment]
@dachary eek, interesting.. it must be getting the `<mutex>` header from somewhere else in master. i added a commit for `#include <mutex>`, hopefully that helps

**Comment by dachary** [comment]
@cbodley yeah !

**Comment by dachary** [comment]
@cbodley could you please amend the commit of 47abc13 to explain why it has to be a commit unique to jewel and not a cherry-pick -x of a commit from master ?

**Comment by cbodley** [comment]
@dachary added this:
```
this fix was added directly to the jewel branch rather than backporting
from master, because the code on master compiles without this specific
include - it's likely included by another header, but backporting would
involve pulling in unrelated changes
```
sound okay?

**Comment by dachary** [comment]
@cbodley yes, thanks !

**Comment by dachary** [comment]
hey jenkins, do you best this time, test this please (jenkins general failure)

**Comment by cbodley** [comment]
well done jenkins, i knew you had it in you! :)

**Comment by dachary** [comment]
It passed the rgw suite http://tracker.ceph.com/issues/17851#note-3 . Note that it will not be in 10.2.4, reason why it targets jewel-next.

**Pull request merged**
