### PR TITLE
luminous: mds: stopping MDS with a large cache (40+GB) causes it to miss heartbeats

### PR DESCRIPTION
**Pull request by batrick**
http://tracker.ceph.com/issues/38130
http://tracker.ceph.com/issues/38132

### CODE REVIEW

**Comment by batrick** [comment]
Based on #26215

**Comment by batrick** [comment]
http://pulpito.ceph.com/pdonnell-2019-02-02_05:34:52-fs-wip-pdonnell-testing-20190202.040530-luminous-distro-basic-smithi/

**Comment by yuriw** [comment]
@batrick pls rebase

--- pr 26232 --- pulling https://github.com/batrick/ceph.git branch i38132-i38130
remote: Enumerating objects: 96, done.
remote: Counting objects: 100% (96/96), done.
remote: Total 110 (delta 96), reused 96 (delta 96), pack-reused 14
Receiving objects: 100% (110/110), 63.57 KiB | 0 bytes/s, done.
Resolving deltas: 100% (96/96), completed with 28 local objects.
From https://github.com/batrick/ceph
 * branch            i38132-i38130 -> FETCH_HEAD
Auto-merging src/test/mds/TestSessionFilter.cc
CONFLICT (content): Merge conflict in src/test/mds/TestSessionFilter.cc
Auto-merging src/mds/SessionMap.h
CONFLICT (content): Merge conflict in src/mds/SessionMap.h
Auto-merging src/mds/SessionMap.cc
Auto-merging src/mds/Server.cc
Auto-merging src/mds/MDSRank.cc
Auto-merging src/mds/MDCache.h
Auto-merging src/mds/MDCache.cc
Auto-merging src/common/options.cc
Auto-merging PendingReleaseNotes
Automatic merge failed; fix conflicts and then commit the result.
Traceback (most recent call last):
  File "/home/yuriw/wip_master/src/script/build-integration-branch", line 62, in <module>
    assert not r
AssertionError

**Comment by yuriw** [comment]
[wip-yuri-testing-2019-03-04-2023-luminous](https://trello.com/c/MFoZe9mq/551-wip-yuri-testing-2019-03-04-2023-luminous)

**Comment by batrick** [comment]
`Reviewed-by: Patrick Donnelly <pdonnell@redhat.com>`

**Pull request merged**
