### PR TITLE
Revert "vstart_runner: rotate logs between testcases"

### PR DESCRIPTION
**Pull request by epuertat**
Reverts ceph/ceph#35824
Fixes: https://tracker.ceph.com/issues/47032
Signed-off-by: Ernesto Puerta <epuertat@redhat.com>

### CODE REVIEW

**Comment by LenzGr** [comment]
Fixes: https://tracker.ceph.com/issues/47032

**Comment by epuertat** [comment]
[ceph api fails](https://jenkins.ceph.com/job/ceph-api/1218/consoleFull#-4947842103c6d33f2-5c31-4f43-a3da-0086a2749b01) but at a later stage.

**Comment by epuertat** [comment]
jenkins test api

**Comment by epuertat** [comment]
jenkins test api

**Comment by epuertat** [comment]
jenkins test api

**Comment by batrick** [comment]
I'm good to merge this @epuertat. cc @rishabh-d-dave

**Comment by batrick** [comment]
jenkins test api

**Pull request merged**
