### PR TITLE
mgr/dashboard: Fix path to dash_devel.rst

### PR DESCRIPTION
**Pull request by votdev**
Signed-off-by: Volker Theile <vtheile@suse.com>

## Checklist
- [ ] References tracker ticket
- [x] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Review by s0nea — APPROVED** [review]

**Comment by votdev** [comment]
jenkins test dashboard

**Comment by s0nea** [comment]
jenkins test api

**Comment by tchaikov** [comment]
could you prefix the title of your commit message with the subcomponent your are changing ? see https://github.com/ceph/ceph/blob/master/SubmittingPatches.rst#3-describe-your-changes . in this case, i'd suggest use something like "pybind/mgr:".

**Review by nizamial09 — APPROVED** [review]

**Comment by s0nea** [comment]
jenkins test api

**Comment by s0nea** [comment]
jenkins test dashboard

**Review by Devp00l — APPROVED** [review]

**Review by callithea — APPROVED** [review]

**Comment by votdev** [comment]
jenkins test dashboard

**Review by epuertat — APPROVED** [review]

**Comment by epuertat** [comment]
jenkins test dashboard

**Pull request merged**
