### PR TITLE
nautilus/rgw/usage:fix the bug when trim usage by specifying  user

### PR DESCRIPTION
**Pull request by lcwlovefamily**
when we trim usage by specifying user,  it is possible to trim other users’ usage.

Fixes:https://tracker.ceph.com/issues/48208

Signed-off-by: chengwu liang  <liangchengw@chinatelecom.cn>

### CODE REVIEW

**Comment by lcwlovefamily** [comment]
@batrick @tchaikov @jdurgin please, review. thanks

**Comment by jdurgin** [comment]
does this affect master or octopus? the usual flow is to merge a fix to master, then backport it to the affected stable branches.

**Comment by lcwlovefamily** [comment]
> does this affect master or octopus? the usual flow is to merge a fix to master, then backport it to the affected stable branches.
I checked the master and octopus，yes，it affects. i found this problem in v14.2.8 and i was told by my colleague that i should merge it to the the branch which i found and let u to merge it to the master. if u want,i can create another PR in master and close this one.

**Comment by tchaikov** [comment]
> i was told by my colleague that i should merge it to the the branch which i found and let u to merge it to the master. 

@lcwlovefamily hi chengwu, we do this the other way around. namely

1. fix the issues in master
1. backport the fix to LTS branches.

> if u want,i can create another PR in master and close this one.

i just tried to retarget this PR to master, but these two branches diverge with each other too much. so does not work. so, yeah, please create another PR targeting master. and close this one.

**Comment by lcwlovefamily** [comment]
According to the plan, new PR have been created:https://github.com/ceph/ceph/pull/38123,close this one.

**Pull request closed without merging**
