### PR TITLE
osd/PG: add pool read/write op latency

### PR DESCRIPTION
**Pull request by Yan-waller**
add it so we can get op latency of different pools as below:
```
# ceph pg dump pools
dumped pools
POOLID OBJECTS MISSING_ON_PRIMARY DEGRADED MISPLACED UNFOUND BYTES      LOG   DISK_LOG OP_LATENCY RD_LATENCY WR_LATENCY 
2           21                  0        0         0       0       2246    49       49          0          0          0 
1            0                  0        0         0       0          0     0        0          0          0          0 
0          470                  0        0         0       0 1929109701 24241    24241       1850        365       7870 
```

### CODE REVIEW

**Comment by liewegas** [comment]
This information should already be available (in greater detail) via the perfcounter metrics.  I'm not sure we should duplicate the information here?

**Comment by Yan-waller** [comment]
retest this please

**Comment by Yan-waller** [comment]
@liewegas  thanks, did you mean we can get op latency information via `ceph daemon  xxx.asok perf dump`  for an OSD?   maybe we need this when we perfer to latency about per pool?  It seems to be useful if we use different storage medium pool.

**Comment by liewegas** [comment]
Hmm, yeah, we don't currently separate this info out by device class.  Right now stats are handled by something extenral so it's up to that system to sum/average/whatever the different classes of osds.  I still think that this is a problem better solved by the external tool, or later e.g. by a ceph-mgr module operating on the existing metrics data.

**Comment by Yan-waller** [comment]
okay, close it...

**Pull request closed without merging**
