### PR TITLE
mimic: mon: restrict mon, osd, mds caps by network/host

### PR DESCRIPTION
**Pull request by liewegas**

### CODE REVIEW

**Comment by smithfarm** [comment]
Please rebase?

**Comment by smithfarm** [comment]
@liewegas Build failure:

```
In file included from /home/jenkins-build/build/workspace/ceph-pull-requests/src/osd/PG.h:39:0,
                 from /home/jenkins-build/build/workspace/ceph-pull-requests/src/osd/PrimaryLogPG.h:22,
                 from /home/jenkins-build/build/workspace/ceph-pull-requests/src/objclass/class_api.cc:8:
/home/jenkins-build/build/workspace/ceph-pull-requests/src/osd/Session.h: In constructor 'Session::Session(CephContext*, Connection*)':
/home/jenkins-build/build/workspace/ceph-pull-requests/src/osd/Session.h:156:23: error: 'class Connection' has no member named 'get_peer_socket_addr'; did you mean 'get_peer_addr'?
     socket_addr(con_->get_peer_socket_addr()),
                       ^~~~~~~~~~~~~~~~~~~~
                       get_peer_addr
src/CMakeFiles/cls_references_objs.dir/build.make:62: recipe for target 'src/CMakeFiles/cls_references_objs.dir/objclass/class_api.cc.o' failed
make[3]: *** [src/CMakeFiles/cls_references_objs.dir/objclass/class_api.cc.o] Error 1
CMakeFiles/Makefile2:1718: recipe for target 'src/CMakeFiles/cls_references_objs.dir/all' failed
```

**Comment by yuriw** [comment]
test this please

**Comment by yuriw** [comment]
@liewegas @smithfarm do we want this in 13.2.2 ?

**Comment by liewegas** [comment]
no hurry..

**Comment by liewegas** [comment]
@yuriw this one's ready to retest

**Comment by neha-ojha** [comment]
needs rebase

**Comment by yuriw** [comment]
@liewegas needs rebasing

--- pr 23613 --- pulling https://github.com/liewegas/ceph.git branch wip-hostcaps-mimic
remote: Enumerating objects: 103, done.
remote: Counting objects: 100% (103/103), done.
remote: Compressing objects: 100% (15/15), done.
remote: Total 106 (delta 88), reused 88 (delta 88), pack-reused 3
Receiving objects: 100% (106/106), 75.31 KiB | 0 bytes/s, done.
Resolving deltas: 100% (90/90), completed with 35 local objects.
From https://github.com/liewegas/ceph
 * branch            wip-hostcaps-mimic -> FETCH_HEAD
Auto-merging src/test/mds/TestSessionFilter.cc
CONFLICT (content): Merge conflict in src/test/mds/TestSessionFilter.cc
Auto-merging src/osd/PG.cc
Auto-merging src/osd/OSD.cc
Auto-merging src/mon/OSDMonitor.cc
Auto-merging src/mds/SessionMap.h
Auto-merging src/mds/SessionMap.cc
Auto-merging src/mds/MDSRank.cc
Automatic merge failed; fix conflicts and then commit the result.
Traceback (most recent call last):
  File "/home/yuriw/wip_master/src/script/build-integration-branch", line 62, in <module>
    assert not r
AssertionError

**Comment by smithfarm** [comment]
@liewegas Please rebase again?

**Pull request closed without merging**
