### PR TITLE
common/options/crimson: increase crimson_osd_obc_lru_size to 512

### PR DESCRIPTION
**Pull request by cyx1231st**
When recover-missing phase becomes an issue, the blocking request is mostly calling with_obc(), and the lru hit ratio can below 10%.

By increasing the lru size, crimson/alienstore 4KB random read (1 replica) got **~49%** inprovements at 32 cores, roughly **~55%** better than classic in my local test.

Interestingly, random write performance cannot be improved with this tunable. I think it is because OSD is mostly writing to new objects.

That is to say, the direction forward might be to refactor loading obcs into concurrent ordered phase(s).

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Comment by Matan-B** [comment]
I think that having a "limited" lru_size is useful for debugging and testing, maybe we should have a performance config that will tune the lru_size and other options we find useful in the future for debugging+testing or performance?

**Comment by cyx1231st** [comment]
Ceph config doesn't seem to support multiple defaults yet, but I'm good with not merging it for stabilization purposes.

Added DNM lable.

**Comment by athanatos** [comment]
Configs should fit how we expect users to use the system, not how we test it.  Let's go ahead and update the config value to 512 as @cyx1231st 's testing recommends.  However, let's also add an override to teuthology to force a smaller more test friendly value for our testing.

**Comment by Matan-B** [comment]
> Configs should fit how we expect users to use the system, not how we test it. Let's go ahead and update the config value to 512 as @cyx1231st 's testing recommends. However, let's also add an override to teuthology to force a smaller more test friendly value for our testing.

@cyx1231st, I added a commit

**Comment by cyx1231st** [comment]
Does this PR need QA?

**Review by Matan-B — APPROVED** [review]
I'm ok with merging as is, @athanatos

**Pull request merged**
