### PR TITLE
mimic: rgw: data sync drains lease stack on lease failure

### PR DESCRIPTION
**Pull request by pdvian**
http://tracker.ceph.com/issues/38530

### CODE REVIEW

**Comment by smithfarm** [comment]
```
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ceph-dashboard@0.0.0 build: `ng build "--prod"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ceph-dashboard@0.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/jenkins-build/.npm/_logs/2019-03-05T05_49_15_864Z-debug.log
src/pybind/mgr/dashboard/CMakeFiles/mgr-dashboard-frontend-build.dir/build.make:1435: recipe for target '../src/pybind/mgr/dashboard/frontend/dist' failed
make[3]: *** [../src/pybind/mgr/dashboard/frontend/dist] Error 1
CMakeFiles/Makefile2:4878: recipe for target 'src/pybind/mgr/dashboard/CMakeFiles/mgr-dashboard-frontend-build.dir/all' failed
```

@callithea @ricardoasmarques @sebastian-philipp Any idea why "make check" is now failing with the above error on (all?) mimic PRs?

**Comment by sebastian-philipp** [comment]
@smithfarm http://tracker.ceph.com/issues/38590 (cc @Exotelis )

**Comment by smithfarm** [comment]
I marked https://tracker.ceph.com/issues/38602 as related - I did not examine the failures closely, but it looks like there are two ways that `mgr-dashboard-frontend-unittests` is failing on the tip of mimic.

**Comment by smithfarm** [comment]
jenkins re-test this please

**Comment by yuriw** [comment]
[wip-yuri-testing-2019-05-13-1904-mimic](https://trello.com/c/b7ZMIYPQ/613-wip-yuri-testing-2019-05-13-1904-mimic)

**Pull request merged**
