### PR TITLE
mgr/volumes: minor fixes

### PR DESCRIPTION
**Pull request by ajarr**
mgr/volumes: cleanup FS subvolume or subvolume group path
    
    ... on best effort basis when FS subvolume or subvolumegroup create
    command fails.
    
    Fixes: https://tracker.ceph.com/issues/41371
    Signed-off-by: Ramana Raja <rraja@redhat.com>

    mgr/volumes: give useful error message
    
    ... when creating FS subvolume or subvolume group with invalid
    data pool layout.
    
    Fixes: https://tracker.ceph.com/issues/41337
    Signed-off-by: Ramana Raja <rraja@redhat.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test docs`
- `jenkins render docs`

</details>

### CODE REVIEW

**Comment by ajarr** [comment]
@batrick, I also want to push a fix tonight for https://tracker.ceph.com/issues/41371 in this PR. Can you please wait on QAing this?

**Comment by batrick** [comment]
sure

**Comment by ajarr** [comment]
> @batrick, I also want to push a fix tonight for https://tracker.ceph.com/issues/41371 in this PR. Can you please wait on QAing this?

Done

**Comment by ajarr** [comment]
@batrick PTAL

**Comment by batrick** [comment]
retest this please

**Comment by batrick** [comment]
retest this please

**Pull request merged**
