### PR TITLE
Don't crash on copy when metadata directive not supplied

### PR DESCRIPTION
**Pull request by adamemerson**
Fixes: http://tracker.ceph.com/issues/40416

### CODE REVIEW

**Comment by adamemerson** [comment]
```
$ S3TEST_CONF=s3tests.conf ./virtualenv/bin/nosetests -a '!fails_on_rgw,!lifecycle_expiration,!fails_strict_rfc2616'
................SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS.....SSSSSSSSS........SSSSSSSSSSSSSSSSSSSSSSSSSSSSS............................................................................................................................................................................................................................................................................................................................................................................................................................................SSSS...................................................................
----------------------------------------------------------------------
Ran 602 tests in 173.217s

OK (SKIP=79)
```

**Comment by tchaikov** [comment]
@adamemerson  could you prefix the title of your commit message with the subcomponent your are changing ? see https://github.com/ceph/ceph/blob/master/SubmittingPatches.rst#3-describe-your-changes . in this case, it's could be "rgw: ".

**Comment by adamemerson** [comment]
@tchaikov Sorry, thought I did that. Fixed!

**Comment by adamemerson** [comment]
@cbodley DO you think we need to put this through Teuthology or just put it in when it passes make check?

**Pull request merged**
