### PR TITLE
rgw : fix python script using s3cmd with error code 403

### PR DESCRIPTION
**Pull request by BryceCao**
Fixes: https://tracker.ceph.com/issues/54104
Signed-off-by: caolei <cao.leilc@inspur.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by cbodley** [comment]
thanks @BryceCao, i added this to my https://github.com/cbodley/ceph/commits/wip-qa-rgw-verify-ubuntu branch and scheduled some ubuntu rgw/verify jobs to try it out:

https://pulpito.ceph.com/cbodley-2022-12-08_15:33:58-rgw:verify-wip-cbodley-testing-distro-default-smithi/

**Comment by tchaikov** [comment]
jenkins test make check

**Comment by cbodley** [comment]
still seeing those SignatureDoesNotMatch failures :(
```
2022-12-09T06:27:03.235 DEBUG:teuthology.orchestra.run.smithi161:> cat /etc/os-release
2022-12-09T06:27:03.284 INFO:teuthology.orchestra.run.smithi161.stdout:NAME="Ubuntu"
2022-12-09T06:27:03.348 INFO:teuthology.orchestra.run.smithi161.stdout:VERSION="20.04.5 LTS (Focal Fossa)"
...
2022-12-09T06:39:42.641 INFO:tasks.workunit.client.0.smithi161.stderr:INFO:root:s3cmd config written
2022-12-09T06:39:42.641 INFO:tasks.workunit.client.0.smithi161.stderr:DEBUG:root:exec_cmd(s3cmd --access_key=NX5QOQKC6BH2IDN8HC7A --secret_key=LnEsqNNqZIpkzauboDcLXLcYaWwLQ3Kop0zAnKIn -c /home/ubuntu/cephtest/mnt.0/client.0/tmp/s3cfg --host=http://localhost:80 mb s3://datacachebucket)
2022-12-09T06:39:43.048 INFO:tasks.workunit.client.0.smithi161.stderr:ERROR:root:command failed
2022-12-09T06:39:43.048 INFO:tasks.workunit.client.0.smithi161.stderr:ERROR:root:error: b'ERROR: S3 error: 403 (SignatureDoesNotMatch)\n'
2022-12-09T06:39:43.049 INFO:tasks.workunit.client.0.smithi161.stderr:returncode: 77
2022-12-09T06:39:43.049 INFO:tasks.workunit.client.0.smithi161.stderr:DEBUG:root:exec_cmd(s3cmd --access_key=NX5QOQKC6BH2IDN8HC7A --secret_key=LnEsqNNqZIpkzauboDcLXLcYaWwLQ3Kop0zAnKIn -c /home/ubuntu/cephtest/mnt.0/client.0/tmp/s3cfg --host=http://localhost:80 put /home/ubuntu/cephtest/mnt.0/client.0/tmp/7M.dat s3://datacachebucket)
2022-12-09T06:39:43.874 INFO:tasks.workunit.client.0.smithi161.stderr:ERROR:root:command failed
2022-12-09T06:39:43.874 INFO:tasks.workunit.client.0.smithi161.stderr:ERROR:root:error: b'ERROR: S3 error: 403 (SignatureDoesNotMatch)\n'
2022-12-09T06:39:43.874 INFO:tasks.workunit.client.0.smithi161.stderr:returncode: 77
2022-12-09T06:39:43.875 INFO:tasks.workunit.client.0.smithi161.stderr:DEBUG:root:exec_cmd(s3cmd --access_key=NX5QOQKC6BH2IDN8HC7A --secret_key=LnEsqNNqZIpkzauboDcLXLcYaWwLQ3Kop0zAnKIn -c /home/ubuntu/cephtest/mnt.0/client.0/tmp/s3cfg --host=http://localhost:80 get s3://datacachebucket/7M.dat /home/ubuntu/cephtest/mnt.0/client.0/tmp/7M-get.dat --force)
2022-12-09T06:39:44.071 INFO:tasks.workunit.client.0.smithi161.stderr:ERROR:root:command failed
2022-12-09T06:39:44.071 INFO:tasks.workunit.client.0.smithi161.stderr:ERROR:root:error: b'ERROR: S3 error: 403 (SignatureDoesNotMatch)\n'
2022-12-09T06:39:44.071 INFO:tasks.workunit.client.0.smithi161.stderr:returncode: 77
```
http://qa-proxy.ceph.com/teuthology/cbodley-2022-12-08_15:33:58-rgw:verify-wip-cbodley-testing-distro-default-smithi/7108357/teuthology.log

**Comment by BryceCao** [comment]
> still seeing those SignatureDoesNotMatch failures :(
> 
> ```
> 2022-12-09T06:27:03.235 DEBUG:teuthology.orchestra.run.smithi161:> cat /etc/os-release
> 2022-12-09T06:27:03.284 INFO:teuthology.orchestra.run.smithi161.stdout:NAME="Ubuntu"
> 2022-12-09T06:27:03.348 INFO:teuthology.orchestra.run.smithi161.stdout:VERSION="20.04.5 LTS (Focal Fossa)"
> ...
> 2022-12-09T06:39:42.641 INFO:tasks.workunit.client.0.smithi161.stderr:INFO:root:s3cmd config written
> 2022-12-09T06:39:42.641 INFO:tasks.workunit.client.0.smithi161.stderr:DEBUG:root:exec_cmd(s3cmd --access_key=NX5QOQKC6BH2IDN8HC7A --secret_key=LnEsqNNqZIpkzauboDcLXLcYaWwLQ3Kop0zAnKIn -c /home/ubuntu/cephtest/mnt.0/client.0/tmp/s3cfg --host=http://localhost:80 mb s3://datacachebucket)
> 2022-12-09T06:39:43.048 INFO:tasks.workunit.client.0.smithi161.stderr:ERROR:root:command failed
> 2022-12-09T06:39:43.048 INFO:tasks.workunit.client.0.smithi161.stderr:ERROR:root:error: b'ERROR: S3 error: 403 (SignatureDoesNotMatch)\n'
> 2022-12-09T06:39:43.049 INFO:tasks.workunit.client.0.smithi161.stderr:returncode: 77
> 2022-12-09T06:39:43.049 INFO:tasks.workunit.client.0.smithi161.stderr:DEBUG:root:exec_cmd(s3cmd --access_key=NX5QOQKC6BH2IDN8HC7A --secret_key=LnEsqNNqZIpkzauboDcLXLcYaWwLQ3Kop0zAnKIn -c /home/ubuntu/cephtest/mnt.0/client.0/tmp/s3cfg --host=http://localhost:80 put /home/ubuntu/cephtest/mnt.0/client.0/tmp/7M.dat s3://datacachebucket)
> 2022-12-09T06:39:43.874 INFO:tasks.workunit.client.0.smithi161.stderr:ERROR:root:command failed
> 2022-12-09T06:39:43.874 INFO:tasks.workunit.client.0.smithi161.stderr:ERROR:root:error: b'ERROR: S3 error: 403 (SignatureDoesNotMatch)\n'
> 2022-12-09T06:39:43.874 INFO:tasks.workunit.client.0.smithi161.stderr:returncode: 77
> 2022-12-09T06:39:43.875 INFO:tasks.workunit.client.0.smithi161.stderr:DEBUG:root:exec_cmd(s3cmd --access_key=NX5QOQKC6BH2IDN8HC7A --secret_key=LnEsqNNqZIpkzauboDcLXLcYaWwLQ3Kop0zAnKIn -c /home/ubuntu/cephtest/mnt.0/client.0/tmp/s3cfg --host=http://localhost:80 get s3://datacachebucket/7M.dat /home/ubuntu/cephtest/mnt.0/client.0/tmp/7M-get.dat --force)
> 2022-12-09T06:39:44.071 INFO:tasks.workunit.client.0.smithi161.stderr:ERROR:root:command failed
> 2022-12-09T06:39:44.071 INFO:tasks.workunit.client.0.smithi161.stderr:ERROR:root:error: b'ERROR: S3 error: 403 (SignatureDoesNotMatch)\n'
> 2022-12-09T06:39:44.071 INFO:tasks.workunit.client.0.smithi161.stderr:returncode: 77
> ```
> 
> http://qa-proxy.ceph.com/teuthology/cbodley-2022-12-08_15:33:58-rgw:verify-wip-cbodley-testing-distro-default-smithi/7108357/teuthology.log

code has been updated, replacing `localhost` with `127.0.0.1` can solve this problem. PTAL

**Comment by cbodley** [comment]
testing the update in https://pulpito.ceph.com/cbodley-2022-12-12_15:09:56-rgw:verify-wip-cbodley-testing-distro-default-smithi/

**Comment by cbodley** [comment]
```
2022-12-12T15:31:23.783 INFO:tasks.workunit.client.0.smithi092.stderr:DEBUG:root:exec_cmd(s3cmd --access_key=NX5QOQKC6BH2IDN8HC7A --secret_key=LnEsqNNqZIpkzauboDcLXLcYaWwLQ3Kop0zAnKIn --config=/home/ubuntu/cephtest/mnt.0/client.0/tmp/s3cfg --host=http://127.0.0.1:80 mb s3://datacachebucket)
2022-12-12T15:31:24.178 INFO:tasks.workunit.client.0.smithi092.stderr:ERROR:root:command failed
2022-12-12T15:31:24.178 INFO:tasks.workunit.client.0.smithi092.stderr:ERROR:root:error: b'ERROR: S3 error: 403 (SignatureDoesNotMatch)\n'
2022-12-12T15:31:24.178 INFO:tasks.workunit.client.0.smithi092.stderr:returncode: 77
```

**Comment by mkogan1** [comment]
@cbodley https requests required additional handling

**Review by cbodley — APPROVED** [review]

**Comment by mkogan1** [comment]
with the additional commit 2cb94411801201b53789b3b9b509abccb63c4b1f

passing the flow in teuthology with _--host=http**S**://..._ that previously failed with 403 :
http://qa-proxy.ceph.com/teuthology/mkogan-2023-03-21_14:16:48-rgw:verify-wip-ubu-SigDoesNotMatch-i01-distro-default-smithi/7215321/teuthology.log
```
│2023-03-21T14:55:28.633 INFO:tasks.workunit.client.0.smithi149.stderr:DEBUG:root:exec_cmd(s3cmd --access_key=NX5QOQKC6BH2IDN8HC7A --secret_key=LnEsqNNqZIpkzauboDcLXLcYaWwLQ3Kop0zAnKIn --config=/home/ubuntu/cephtest/mnt.0/client.0/tmp/s3cfg --no-check-hostname --host=https://127.0.0.1:443 mb s3://datacachebucket)                             │
│2023-03-21T14:55:28.856 INFO:tasks.workunit.client.0.smithi149.stderr:INFO:root:command succeeded                                                                                                                                                                                                                                                     │
│2023-03-21T14:55:28.856 INFO:tasks.workunit.client.0.smithi149.stderr:INFO:root:b"Bucket 's3://datacachebucket/' created\n"                                                                                                                                                                                                                           │
│2023-03-21T14:55:28.857 INFO:tasks.workunit.client.0.smithi149.stderr:DEBUG:root:exec_cmd(s3cmd --access_key=NX5QOQKC6BH2IDN8HC7A --secret_key=LnEsqNNqZIpkzauboDcLXLcYaWwLQ3Kop0zAnKIn --config=/home/ubuntu/cephtest/mnt.0/client.0/tmp/s3cfg --no-check-hostname --host=https://127.0.0.1:443 put /home/ubuntu/cephtest/mnt.0/client.0/tmp/7M.dat s│
│2023-03-21T14:55:29.250 INFO:tasks.workunit.client.0.smithi149.stderr:INFO:root:command succeeded                                                                                                                                                                                                                                                     │
│2023-03-21T14:55:29.250 INFO:tasks.workunit.client.0.smithi149.stderr:INFO:root:b"upload: '/home/ubuntu/cephtest/mnt.0/client.0/tmp/7M.dat' -> 's3://datacachebucket/7M.dat' (7340032 bytes in 0.2 seconds, 36.38 MB/s) [1 of 1]\n"                                                                                                                   │
│2023-03-21T14:55:29.250 INFO:tasks.workunit.client.0.smithi149.stderr:DEBUG:root:exec_cmd(s3cmd --access_key=NX5QOQKC6BH2IDN8HC7A --secret_key=LnEsqNNqZIpkzauboDcLXLcYaWwLQ3Kop0zAnKIn --config=/home/ubuntu/cephtest/mnt.0/client.0/tmp/s3cfg --no-check-hostname --host=https://127.0.0.1:443 get s3://datacachebucket/7M.dat /home/ubuntu/cephtest│
│2023-03-21T14:55:29.489 INFO:tasks.workunit.client.0.smithi149.stderr:INFO:root:command succeeded                                                                                                                                                                                                                                                     │
│2023-03-21T14:55:29.489 INFO:tasks.workunit.client.0.smithi149.stderr:INFO:root:b"download: 's3://datacachebucket/7M.dat' -> '/home/ubuntu/cephtest/mnt.0/client.0/tmp/7M-get.dat' (7340032 bytes in 0.1 seconds, 132.53 MB/s)\n"    
```

**Comment by mkogan1** [comment]
jenkins test docs

**Comment by mkogan1** [comment]
jenkins render docs

**Comment by mkogan1** [comment]
jenkins test make check

**Comment by mkogan1** [comment]
jenkins render docs

**Comment by cbodley** [comment]
thanks @BryceCao @mkogan1!

**Comment by cbodley** [comment]
@mkogan1 i still saw these signature mismatch errors against ubuntu 20.04 in http://qa-proxy.ceph.com/teuthology/cbodley-2023-03-30_18:07:30-rgw:verify-main-distro-default-smithi/7226781/teuthology.log

that was using the suite-branch https://github.com/cbodley/ceph/commits/wip-qa-rgw-distros, which does contain your fixes
```
2023-03-30T18:48:19.654 INFO:tasks.workunit.client.0.smithi031.stderr:INFO:root:Creating s3cmd config...
2023-03-30T18:48:19.654 INFO:tasks.workunit.client.0.smithi031.stderr:INFO:root:proto for s3cmd config is https
2023-03-30T18:48:19.654 INFO:tasks.workunit.client.0.smithi031.stderr:INFO:root:s3cmd config written
2023-03-30T18:48:19.655 INFO:tasks.workunit.client.0.smithi031.stderr:DEBUG:root:exec_cmd(s3cmd --access_key=NX5QOQKC6BH2IDN8HC7A --secret_key=LnEsqNNqZIpkzauboDcLXLcYaWwLQ3Kop0zAnKIn --config=/home/ubuntu/cephtest/mnt.0/client.0/tmp/s3cfg --no-check-hostname --host=https://127.0.0.1:443 mb s3://datacachebucket)
2023-03-30T18:48:19.848 INFO:tasks.workunit.client.0.smithi031.stderr:ERROR:root:command failed
2023-03-30T18:48:19.848 INFO:tasks.workunit.client.0.smithi031.stderr:ERROR:root:error: b'ERROR: S3 error: 403 (SignatureDoesNotMatch)\n'
2023-03-30T18:48:19.848 INFO:tasks.workunit.client.0.smithi031.stderr:returncode: 77
```
is it possible that focal doesn't understand that `--no-check-hostname` option?

**Pull request merged**
