### PR TITLE
script/run_tox.sh: use WITH_PYTHON{2,3} to ensure python is installed

### PR DESCRIPTION
**Pull request by tchaikov**
before this change, run_tox.sh is hardwired to python2.7,
`setup-virtualenv.sh` use it as the default python version. after this
change, we use python3 if WITH_PYTHON3 is enabled, and fallback to
python2 otherwise.

this is not quite right, as WITH_PYTHON2 and WITH_PYTHON3 are used to
specify what python version our python binding should be built. it's not
directly related to what python we should use for creating venv which is
in turn used for running tox based test.

but we can use these settings to ensure that the python interpreter is
available for creating the venv environment. normally, the venv is
prepared by `${name}-venv` target if one runs "make tests" for preparing
the dependencies for running "ctest" or "make check". but we should
allow user to use `run_tox.sh` directly for performing tox tests without
running "make tests" first.

Signed-off-by: Kefu Chai <kchai@redhat.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`

</details>

### CODE REVIEW

**Comment by tchaikov** [comment]
@epuertat i think i am trying to please the users who don't want to use "make tests". actually i am one of them =)

**Comment by epuertat** [comment]
> @epuertat i think i am trying to please the users who don't want to use "make tests". actually i am one of them =)

Yeah, it fully makes sense to. I'm just saying that in that case, why not removing the duplicate steps from the ctest function and leave them just in the run-tox script?

**Comment by wjwithagen** [comment]
Running it thru FreeBSD-jenkins, but visual inspection seems oke

**Comment by tchaikov** [comment]
@epuertat because i like @wjwithagen 's change more. as it's more *correct* in the sense that it uses  `find_package(Python...)` to use the greatest python version available in the system. while this patch abuses WITH_PYTHON3 and WITH_PYTHON2.

**Comment by jecluis** [comment]
Oh, and an addendum to my review, this PR does not make the `make test`, or even `run_tox.sh` properly setup a virtualenv in a machine without python2.

**Comment by wjwithagen** [comment]
@jecluis 
Since FreeBSD has the possibility to run both 2.7 and several 3.x python versions in the same system.
So my cmake call always contain something like:
`-DWITH_PYTHON2=ON -DWITH_PYTHON3=OFF -DMGR_PYTHON_VERSION=2.7`

**Comment by smithfarm** [comment]
@tchaikov If you could, please ping someone from SUSE (for example me, @jecluis, @kshtsk, etc.) for review on PRs that touch the tox tests, so someone tests them in the openSUSE py3-only environment before they merge. (Master "make check" was passing in that environment up until, like, last month.)

**Comment by tchaikov** [comment]
@smithfarm i did ping Joao on this. actually, i made this fix in hope to address the problem he mentioned on ceph-devel IRC channel. am i missing anything?

**Comment by jecluis** [comment]
@wjwithagen I could, technically, also run python2 in the machine, but that's hardly the point I think, given python2 is going away soon-ish. And regardless of whether the build is compiled with `-DWITH_PYTHON2=OFF` or not, as is, `run-make-checks.sh` is not looking for that when when passing the python version to the virtualenv script.

Note that, in bash, `$with_python2` is different from `$WITH_PYTHON2`. Even then, I'm not sure how the script would be grabbing that information from cmake. From the PR that initially split this test into what it is now (which sha I can't find right now, sorry), there used to be two command-line arguments that would set those `$with_python?` variables.

**Comment by jecluis** [comment]
@tchaikov this patch also makes the whole thing go boom, as is, because the virtualenv script call does not use python3 either - regardless of whether cmake was run with `-DWITH_PYTHON3=ON -DWITH_PYTHON2=OFF` (and no python2 present on the system). @smithfarm patch does work though, given the virtualenv defaults to python3, but I can imagine this now breaking python2 tests (although I haven't tested it).

**Comment by tchaikov** [comment]
@jecluis i am closing this one in favor of #30379 . as the venv created by `setup-virtualenv.sh` in `run_tox.sh` is merely for bootstrap tox. so any python available would work as tox supports both python2 and python3.

**Pull request closed without merging**
