### PR TITLE
krbd: add support for msgr2 (kernel 5.11)

### PR DESCRIPTION
**Pull request by idryomov**

### CODE REVIEW

**Comment by idryomov** [comment]
jenkins render docs

**Comment by idryomov** [comment]
jenkins test make check

**Review by dillaman — APPROVED** [review]
lgtm

**Comment by idryomov** [comment]
jenkins test make check

**Comment by idryomov** [comment]
A rather persistent issue with `unittest-seastar-messenger`, looks like https://tracker.ceph.com/issues/48672.

**Comment by idryomov** [comment]
https://pulpito.ceph.com/dis-2021-01-23_15:51:01-krbd-wip-krbd-msgr2-testing-basic-smithi/

**Pull request merged**
