### PR TITLE
drop permissions of rgw/civetweb after startup

### PR DESCRIPTION
**Pull request by kmroz**
http://tracker.ceph.com/issues/13600

Start rgw/civetweb as root, then rely on civetweb to drop permissions to specified user (or "ceph" by default).

In order to tighten this solution even more, the following commits should be backported to the civetweb submodule:
https://github.com/civetweb/civetweb/commit/5e753cc
https://github.com/civetweb/civetweb/commit/a3c460c
My understanding is that a new branch would need to be created under ceph/civetweb with these commits added, followed by civetweb submodule commit. @yehudasa - is that something you might be able to help with?

### CODE REVIEW

**Comment by yehudasa** [comment]
@kmroz I pushed a branch to ceph/civetweb.git (wip-13600). Maybe @liewegas can help with reviewing this one.

**Comment by liewegas** [comment]
Oh, I see... civetweb does it.  In that case, I think just dropping the --setuser and --setgroup entirely will do the trick.  But.. we also need a group= so that we setgid as well.

**Comment by kmroz** [comment]
@liewegas Correct, civetweb is actually responsible for calling setuid(). Agreed that explicitly calling 
--setuser/--setgroup in the service file is not needed. I'll remove that.

From civetweb.c, gid is derived via getpwnam(uid). As long as the admin as correctly added user "ceph" to group "ceph", this should be valid. Do we want to be explicit here and add a "run_in_group" option to civetweb? Any chance this could be abused (ie. an invalid group set for the user)?

**Comment by liewegas** [comment]
Hmm, yeah, it works for the ceph user, which is probably good enough.

My main concern is that if someone changes the rgw frontend to not use civetweb, or already has it configured to something else (after an upgrade), e.g., because they are setting the port, then they won't drop privileges.

What would be nice is if rgw_main could check if the civetweb backend is in use, and if so, intercept the --setuser setting so that the setuid is done by civetweb instead of global_init (or whatever it is).  Otherwise I think we'll have lots of use who inadvertantly end up running as root instead of ceph...

**Comment by kmroz** [comment]
Ahhh... this is a good point.

I think detecting the frontend from rgw_main isn't a big problem. As I recall, civetweb == class Mongoose (or something like that). However, intercepting --setuser/--setgroup from systemd at the point when we know which frontend we'll use... that one needs pondering :)

**Comment by liewegas** [comment]
I think rgw_main would, if civetweb is in use, clear the g_conf->setuser 
and setgroup fields, and set some private flag that is passed into 
civetweb to do the setuid.  From systemd's perspective nothing changes.

**Comment by kmroz** [comment]
I looked a little more into this... some thoughts:

rgw_main.cc:main() would need to determine what frontends are configured in rgw_frontends _before_ global_init() is called. However, to access g_conf->setuser, etc, global_pre_init() needs to first get invoked (to setup all the global g_ceph_context, g_conf, etc variables). Now, main() continues and if civetweb is configred as a frontend for rgw, it clears g_conf->setuser and g_conf->setgroup before invoking global_init().

Since global_pre_init() is also invoked from global_init(), global_init() would need "bool run_pre_init" added to it's API signature with a default value of true. We would use this to prevent the assert() from getting tripped inside global_pre_init(). Or change out the assert() for a return if g_ceph_context is already allocated. Something like this.

main() continues to allocate the frontends and invokes their run() functions. Civetweb parses the "user=" variables from it's config or uses "ceph" as default in order to drop permissions of radosgw.

I will test something like this today. @sage @yehudasa - what are your thoughts?

**Comment by liewegas** [comment]
Hrm, this is tricky.  The reason why we do the setuid very early is so that when the core ceph code opens log files and such it drops privileges.  We could easily make it defer the setuid (maybe pass a flag into global_init that says NO_SETUSER or something, and then do it explicitly later if civetweb isn't being used), but then the log file will be opened/created by the wrong user.

The reason why we want civetweb to do it is because... it would let us bind to port 80?

**Comment by kmroz** [comment]
This was basically what I was preparing here: https://github.com/kmroz/ceph/commits/wip-upstream-civetweb-low-ports-2.1

However, you're right that /var/log/ceph-radosgw:
-rw-r--r-- 1 root root 61842 Jan 28 15:26 /var/log/ceph-radosgw/ceph.client.radosgw.sle12-ses3-1.log

And /var/run/ceph-radosgw:
srwxr-xr-x  1 root root    0 Jan 29 08:17 ceph.client.radosgw.sle12-ses3-1.asok=
srwxrwxrwx  1 ceph users   0 Jan 28 15:25 ceph.client.radosgw.sle12-ses3-1.fastcgi.sock=

Curious about the fcgi socket though...

Correct, the reason why we want civetweb to do this is so that it can bind to privileged ports, read ssl certs that are readable only by root, etc.

**Comment by liewegas** [comment]
Perhaps the thing to do is make 2 additional changes:

- when logging code opens a file, and getuid is 0, it will chown/chgrp to 
the setuser/setgroup user.

- ditto when creating the asok file.

I suppose a helper in g_ceph_context that fixes file permissions for an 
open fd will work for both cases.

**Comment by liewegas** [comment]
Note that that still lets you create a log file in a directory that you 
would otherwise be able to write to, but I'm not sure we can get around 
that gracefully.

**Comment by kmroz** [comment]
@sage, @yehudasa:

As a result of looking into when rgw creates it's logfile, I found what appears to be a problem in ceph/master. In a vanilla copy (without any of my changes), the radosgw logfile is created with root:root (or root:ceph if /var/log/ceph has setgid bit). I've created a separate tracker for this: http://tracker.ceph.com/issues/14613 with some preliminary analysis.

**Comment by liewegas** [comment]
I think #7313 is a prereq.

**Comment by liewegas** [comment]
@kmroz Okay, I added patches in #7313 to let you defer the drop privileges.  When you do that, cct->get_set_uid() and get_set_gid() will return the uid/gid we should use (or 0 if no priv change is needed).  It also has a kludge to fix the log file and asok ownership.

I think you just need to use that flag for global_init, then check if those are non-zero, and then (if so) add them to the civetweb config line?

**Comment by kmroz** [comment]
@sage - I've added a global_init flag in a followup to this: https://github.com/kmroz/ceph/commits/wip-upstream-civetweb-low-ports-2.1. Perhaps there is something of use there?

Could you point me at what you grabbed and your additional changes?

Thanks!

**Comment by liewegas** [comment]
0. rebase on top of #7313,
1. I think the first commit 9bdbcfb should be dropped,
2. the second one f96643e should be updated to not use the user option, but instead tell civetweb to drop privs based on cct->get_set_uid() and gid (or g_ceph_context instead of cct if it's not there).
3. drop teh systemd commit entirely
4. i would drop the vstart.sh one too.. if you specify the rgw port it's your job to make sure you are a user that can bind to it.

**Comment by kmroz** [comment]
Resultant rebase on @liewegas pull#7545 (Marked as DNM until pull#7545 is merged).

One thing I'm still seeing, is the creation of /var/run/ceph/ceph.client.radosgw.asok as root:root. No chown() errors present in any logs.

**Comment by kmroz** [comment]
Rebased on top of ceph/master. Needs a quick test - tomorrow.

**Comment by kmroz** [comment]
OK - tested locally and permissions drop with frontend=civetweb happens correctly (ie. global_init defers the drop to be handled by civetweb). When frontend=fastcgi, the drop happens from global_init as usual.

@liewegas - Could you please have a glance at this finalized version to see if you're OK with the direction. Thanks!

**Comment by liewegas** [comment]
Looks good to me!  Are you sure civetweb can't just take the uid directly?  It'd be nice to avoid the user -> uid -> user -> uid translations.  I suppose we could store the original user string in CephContext too (along with the uid) to avoid the reverse mapping..

**Comment by kmroz** [comment]
Sadly not :( The set_uid_option() in civetweb pulls the "run_as_user" option into a char * and operates on it.

**Comment by kmroz** [comment]
https://github.com/kmroz/ceph/commit/1003da6d5dc3057b909a3814376f19b1c33d16b9
Maybe something like this? Then I can change this PR to grab the user string directly.

**Comment by liewegas** [comment]
That isn't quite right I think because the uid update may be conditional (setuser might get ignored if the path ownership is different, for example).  If what you have is tested and works, let's just go with it.

**Comment by kmroz** [comment]
Sure thing. However now I'm a bit worried when you say "update may be conditional....setuser might get ignored if the path ownership is different". Can you elaborate please?

**Comment by kmroz** [comment]
Ah... I think I see it. There are some additional checks in global_init related to setuser_match_path, etc... where you reset uid and gid to 0.

**Comment by liewegas** [comment]
https://github.com/ceph/ceph/blob/master/src/global/global_init.cc#L185

This makes the setuid conditional on whether the data path has been 
chowned.  It eases the pain of upgrades, so that if 
/var/lib/ceph/osd/ceph-123 is owned by root still the daemon will 
stay as root.

If we went the string path we'd just need to make sure the uid = 0; gid = 
0; steps cleared the strings too that get stored in the g_ceph_context.

**Comment by kmroz** [comment]
@liewegas - Hi Sage. I put together https://github.com/ceph/ceph/pull/8019 which also clears out uid_string/gid_string when zeroing uid/gid per your comment above. https://github.com/ceph/ceph/pull/8019 makes RGWMongooseFrontend::run() a little cleaner :)

**Pull request closed without merging**
