### PR TITLE
Wip 32bits ceph fuse

### PR DESCRIPTION
**Pull request by ukernel**
make ceph-fuse work on 32-bits machine and FreeBSD (FreeBSD uses 32 bits inode number on 64bits architecture)

### CODE REVIEW

**Comment by gregsfortytwo** [comment]
This translation layer looks good to me in theory, but I've got some practical concerns.
The big one is that we need to be able to test it on an ongoing basis. That means being able to run it in the nightlies, and right now we don't have any 32-bit machines. Ideally, we set a config option "fuse_fake_ino_numbers" (or whatever) and even 64-bit machines will run through this code path. Of course, that would mean expanding the Inode struct even if we don't need it; maybe we could do something with a subclass to avoid doing that in the general case, except when testing?

My other question is, I don't remember how we handle compressing the snapid into the inode. But should we try and unify that with the 32-bit translation? The big downside I can think of is that we want to export the real inode if we can, and this might make it more difficult.

**Comment by ukernel** [comment]
For direct libceph use, snapid is stored in struct stat::st_dev. For fuse, snapid is encoded in the upper 16-bits of ino_t. this is OK for 64-bits ino_t because ceph inode number only uses 48-bits. 

Since there are two cases, I don't think we can unify the code easily.

**Comment by gregsfortytwo** [comment]
This looks good to me and doesn't appear to have broken 64-bit functionality. We need to add some qa-suite tests which enable the fake inodes (in a small subset) and make sure that works before merging; I'll get to it eventually or you can add a PR for that @ukernel!

**Comment by ukernel** [comment]
https://github.com/ceph/ceph-qa-suite/pull/575

**Comment by gregsfortytwo** [comment]
This passed a simple set of my own tests, and those ones are better, so merging!

**Pull request merged**
