### PR TITLE
osd: add command ceph pg <pgid> find_unfound_object <objname> for rec…

### PR DESCRIPTION
**Pull request by jianwei1216**
Author: Jianwei Zhang <jianwei1216@qq.com>
Date:   Mon May 16 15:46:57 2022 +0800

    osd: add command ceph pg <pgid> find_unfound_object <objname> for recovery_unfound
    
    problem:
    ec(4+2) The original 3 nodes, open ec folding, the ratio is 2, expand 2 nodes to the cluster
    ec(2+1) The original 3 nodes, open ec folding, the ratio is 2, expand 2 nodes to the cluster
    all osds status of ceph cluster are exists&up&in
    but some PGs have been stuck in recovery_unfound state and cannot be recovered
    note: after one-by-one adding a new osd to the ceph cluster, pg stuck recovery_unfound
    
    root cause:
    1. The pg acting set has missing objects that needs to recover.
    2. But the source osd of the missing objects is in the backfill_targets(up) set,
    3. Since the source osd in the backfill_targets(up) set needs to restart backfill, set the pg info.last_backfill to MIN,
    4. Since the pg info.last_backfill of source osd is MIN, when MissingLoc::add_source_info, filter the source osd that has missing object,
    5. These missing objects cannot recover and the pg status changes to recovery_unfound.
    
    Solution:
    <pgid> : pg.id
    <objname> : ceph pg <pgid> list_unfound

    example:
    ceph pg 3.20 list_unfound
    {
        "num_missing": 1,
        "num_unfound": 1,
        "objects": [
            {
                "oid": {
                    "oid": "202000000000095.00000005",
                    "key": "",
                    "snapid": -2,
                    "hash": 1807777312,
                    "max": 0,
                    "pool": 3,
                    "namespace": ""
                },
                "need": "303'1222",
                "have": "0'0",
                "flags": "none",
                "clean_regions": "clean_offsets: [], clean_omap: 0, new_object: 1",
                "locations": [
                    "1(5)",
                    "46(1)"
                ]
            }
        ],
        "more": false
    }
    
    ceph pg 3.20 find_unfound_object 202000000000095.00000005
    pg has 3:047e03d6:::202000000000095.00000005:head object unfound
            missing 303'1222 flags = none clean_offsets: [], clean_omap: 0, new_object: 1
            old_location 1(5),46(1)
            new_location 1(5),32(2),34(0),42(4),46(1)
            and find all might have unfound source
    
    Signed-off-by: Jianwei Zhang <jianwei1216@qq.com>

### CODE REVIEW

**Comment by jianwei1216** [comment]
find_unfound_object

**Comment by jianwei1216** [comment]
add @neha-ojha

**Comment by jianwei1216** [comment]
add @tchaikov

**Comment by jianwei1216** [comment]
make check error should not be related to this commit, because I didn't modify src/crimson/osd/osd.cc:532
please verify

**Comment by jianwei1216** [comment]
add @athanatos

**Comment by jianwei1216** [comment]
Since I was developing on ceph15.2.13, I did not adapt to the master.
If there is no problem with the review, consider porting to the master branch.

**Comment by athanatos** [comment]
This adds an entire new message and recovery pathway for recovering an object that is stuck unfound.  Is that right?

This is *way* too complicated.  It's not clear why we need a new message for this purpose -- there are already messages within the recovery pathway for pulling data and metadata from peers.  For rare emergency commands like this, it's important to keep the implementation as simple as possible, ideally reusing the existing recovery pathways, messages, and data structures.  There would also need to be tests added to the rados suite to ensure that it will work safely (and continue to work safely) under a broad range of cluster states.

Please file a bug with more information on how this state came into existence -- fixing that bug is likely the better place to focus.  Consider the ceph-objectstore-tool as an offline way of resolving this problem.

**Comment by rzarzynski** [comment]
Just to record: there is [a ticket](https://tracker.ceph.com/issues/55668) for this already created.

**Comment by jianwei1216** [comment]
```
all osds exists&up&in

# ceph pg 3.2f2 list_unfound
{
    "oid": {
        "oid": "101000000000133.0000001d",
        "key": "",
        "snapid": -2,
        "hash": 1021279986,
        "max": 0,
        "pool": 3,
        "namespace": "" 
    },
    "need": "374'872",
    "have": "0'0",
    "flags": "none",
    "clean_regions": "clean_offsets: [], clean_omap: 0, new_object: 1",
    "locations": [
        "36(0)" 
    ]
}
```

In this scenario, the ec recovery_unfound does not really lose data. The version of the object required for recovery exists on the disk completely, 
acting osd missing object
```
2022-03-18T11:57:17.609 epoch 493 up [75,59,41] -> [76,59,41], acting [57,41,37] -> [57,41,37], acting_primary 57(0) -> 57, up_primary 75(0) -> 76, role -1 -> -1

missing
3.2f2s0.osd57.log {'object': '3:4f7efb3c:::101000000000133.0000001d:head', 'need': "374'872", 'have': "0'0", 'flags': 'none', 'clean_regions': 'clean_offsets: [], clean_omap: 0, new_object: 1'}
3.2f2s1.osd41.log {'object': '3:4f7efb3c:::101000000000133.0000001d:head', 'need': "374'872", 'have': "0'0", 'flags': 'none', 'clean_regions': 'clean_offsets: [], clean_omap: 0, new_object: 1'}
3.2f2s2.osd37.log {'object': '3:4f7efb3c:::101000000000133.0000001d:head', 'need': "374'872", 'have': "0'0", 'flags': 'none', 'clean_regions': 'clean_offsets: [], clean_omap: 0, new_object: 1'}
```



recover_unfound object on disk version
```
ceph-object-tool: (object_info_t and check bluestore)
3.2f2s0.101000000000133.0000001d.osd36.object_info_t {'oid': {'oid': '101000000000133.0000001d', 'key': '', 'snapid': -2, 'hash': 1021279986, 'max': 0, 'pool': 3, 'namespace': ''}, 'version': "374'872", 'prior_version': "374'871", 'last_reqid': 'client.133562.0:359556', 'user_version': 872, 'size': 4194304, 'mtime': '2022-03-18T11:41:39.433611+0800', 'local_mtime': '2022-03-18T11:41:39.436761+0800', 'lost': 0, 'flags': ['dirty'], 'truncate_seq': 0, 'truncate_size': 0, 'data_digest': '0xffffffff', 'omap_digest': '0xffffffff', 'expected_object_size': 0, 'expected_write_size': 0, 'alloc_hint_flags': 0, 'manifest': {'type': 0}, 'watchers': {}}
3.2f2s1.101000000000133.0000001d.osd59.object_info_t {'oid': {'oid': '101000000000133.0000001d', 'key': '', 'snapid': -2, 'hash': 1021279986, 'max': 0, 'pool': 3, 'namespace': ''}, 'version': "374'872", 'prior_version': "374'871", 'last_reqid': 'client.133562.0:359556', 'user_version': 872, 'size': 4194304, 'mtime': '2022-03-18T11:41:39.433611+0800', 'local_mtime': '2022-03-18T11:41:39.436761+0800', 'lost': 0, 'flags': ['dirty'], 'truncate_seq': 0, 'truncate_size': 0, 'data_digest': '0xffffffff', 'omap_digest': '0xffffffff', 'expected_object_size': 0, 'expected_write_size': 0, 'alloc_hint_flags': 0, 'manifest': {'type': 0}, 'watchers': {}}
3.2f2s2.101000000000133.0000001d.osd41.object_info_t {'oid': {'oid': '101000000000133.0000001d', 'key': '', 'snapid': -2, 'hash': 1021279986, 'max': 0, 'pool': 3, 'namespace': ''}, 'version': "374'872", 'prior_version': "374'871", 'last_reqid': 'client.133562.0:359556', 'user_version': 872, 'size': 4194304, 'mtime': '2022-03-18T11:41:39.433611+0800', 'local_mtime': '2022-03-18T11:41:39.436761+0800', 'lost': 0, 'flags': ['dirty'], 'truncate_seq': 0, 'truncate_size': 0, 'data_digest': '0xffffffff', 'omap_digest': '0xffffffff', 'expected_object_size': 0, 'expected_write_size': 0, 'alloc_hint_flags': 0, 'manifest': {'type': 0}, 'watchers': {}}
```

but when peering-->activating pg, these osds are not found as the source for the object to be recovered. 
activate()-->add_source_info() 
```
search_for_missing 3:4f7efb3c:::101000000000133.0000001d:head 374'872 also missing on osd.41(2) (past last_backfill MIN) ///3.2f2s2.101000000000133.0000001d.osd41.object_info_t(disk exists), unchecked
search_for_missing 3:4f7efb3c:::101000000000133.0000001d:head 374'872 also missing on osd.59(1) (past last_backfill MIN) ///3.2f2s1.101000000000133.0000001d.osd59.object_info_t(disk exists), unchecked                                                                                        
search_for_missing 3:4f7efb3c:::101000000000133.0000001d:head 374'872 is on osd.36(0)                                    ///3.2f2s0.101000000000133.0000001d.osd36.object_info_t(disk exists), selected

MissingLoc::add_source_info
{
    for ()
    ...
        if (p->first >= oinfo.last_backfill) {
            // FIXME: this is _probably_ true, although it could conceivably
            // be in the undefined region!  Hmm!
            ldout(cct, 10) << "search_for_missing " << soid << " " << need << " also missing on osd." << fromosd
                           << " (past last_backfill " << oinfo.last_backfill << ")" << dendl;
            continue;
        }
     ...
}
```

Since the osdmap is constantly changing, the pg up/acting is constantly changing, and it was previously in the same position of up/acting (ec-shard) osd,
```
2022-03-18T11:38:09.782 epoch 366 up [36,57,41] -> [36,59,41], acting [36,-1,41] -> [36,-1,41], acting_primary 36(0) -> 36, up_primary 36(0) -> 36, role 0 -> 0,
```
In the osdmap change, the same position of up/acting (ec-shard) osd not select as up/acting and became past interval,
```
2022-03-18T11:41:49.350 epoch 376 up [36,59,41] -> [57,41,39], acting [36,-1,41] -> [36,-1,41], acting_primary 36(0) -> 36, up_primary 36(0) -> 57, role 0 -> 0
2022-03-18T11:41:49.896 epoch 377 up [57,41,39] -> [57,41,39], acting [36,-1,41] -> [-1,41,39], acting_primary 36(0) -> 41, up_primary 57(0) -> 57, role 0 -> -1
2022-03-18T11:45:33.471 epoch 390 up [57,41,39] -> [57,41,37], acting [-1,41,39] -> [-1,41,39], acting_primary 41(1) -> 41, up_primary 57(0) -> 57, role -1 -> -1
2022-03-18T11:45:34.461 epoch 391 up [57,41,37] -> [57,41,37], acting [-1,41,39] -> [57,41,-1], acting_primary 41(1) -> 57, up_primary 57(0) -> 57, role -1 -> -1
```
In the osdmap change, the osd at the same location (ec-shard) is recalculated as up/acting, 
```
2022-03-18T11:55:30.707 epoch 484 up [73,59,41] -> [73,59,41], acting [57,41,-1] -> [57,41,37], acting_primary 57(0) -> 57, up_primary 73(0) -> 73, role -1 -> -1
2022-03-18T11:57:14.897 epoch 490 up [73,59,41] -> [75,59,41], acting [57,41,37] -> [57,41,37], acting_primary 57(0) -> 57, up_primary 73(0) -> 75, role -1 -> -1
2022-03-18T11:57:17.609 epoch 493 up [75,59,41] -> [76,59,41], acting [57,41,37] -> [57,41,37], acting_primary 57(0) -> 57, up_primary 75(0) -> 76, role -1 -> -1
```
but at this time the pglog (head, tail) of these osd (ec-shard) does not intersect with the authoritative log, and the backfill needs to be restarted. And set last_backfill=MIN (this is very important, it is about adding source osd to object),
But the version of the object required for recovery exists in these osds to be backfilled
```
grep 'starting backfill to osd.' ceph.log |grep 3.2f2
2022-03-18T11:55:31.749062+0800 osd.57 (osd.57) 340 : cluster [DBG] 3.2f2s0 starting backfill to osd.41(2) from (0'0,375'884] MAX to 482'1907
2022-03-18T11:55:31.758747+0800 osd.57 (osd.57) 341 : cluster [DBG] 3.2f2s0 starting backfill to osd.59(1) from (0'0,375'884] MAX to 482'1907
```

```
    void PeeringState::activate(ObjectStore::Transaction &t, epoch_t activation_epoch, PeeringCtxWrapper &ctx)
    {
            ...
            else if (pg_log.get_tail() > pi.last_update ||                         ///①The tail of the primary osd log is larger than the head of the replica osd log, indicating that the logs have no intersection, and data recovery can only be performed through backfill.
                    pi.last_backfill == hobject_t() ||                            ///②The last_backfill pointer of the replica osd is MIN, which means that after the last peering is completed, after the replica osd is set to MIN, it has not had time to backfill, died, and then got up again.
                   (backfill_targets.count(*i) && pi.last_backfill.is_max())) {    ///③The replica osd exists in the backfill_targets target list, and the last_backfill pointer of the replica osd is MAX, which means that the replica osd belongs to the up set and needs backfill
                /* ^ This last case covers a situation where a replica is not contiguous
                 * with the auth_log, but is contiguous with this replica.  Reshuffling
                 * the active set to handle this would be tricky, so instead we just go
                 * ahead and backfill it anyway.  This is probably preferrable in any
                 * case since the replica in question would have to be significantly
                 * behind.
                 */
                // backfill
                pl->get_clog_debug() << info.pgid << " starting backfill to osd." << peer << " from (" << pi.log_tail << "," << pi.last_update << "] " << pi.last_backfill << " to " << info.last_update;

                pi.last_update = info.last_update;
                pi.last_complete = info.last_update;
                pi.set_last_backfill(hobject_t());                                 ///reset last_backfill to MIN
                pi.last_epoch_started = info.last_epoch_started;
                pi.last_interval_started = info.last_interval_started;
                pi.history = info.history;
                pi.hit_set = info.hit_set;
                // Save num_bytes for reservation request, can't be negative
                peer_bytes[peer] = std::max<int64_t>(0, pi.stats.stats.sum.num_bytes);
                pi.stats.stats.clear();
                pi.stats.stats.sum.num_bytes = peer_bytes[peer];

                // initialize peer with our purged_snaps.
                pi.purged_snaps = info.purged_snaps;

                m = new MOSDPGLog(i->shard, pg_whoami.shard, get_osdmap_epoch(), pi,
                                  last_peering_reset /* epoch to create pg at */);

                // send some recent log, so that op dup detection works well.
                m->log.copy_up_to(cct, pg_log.get_log(), cct->_conf->osd_max_pg_log_entries);
                m->info.log_tail = m->log.tail;
                pi.log_tail = m->log.tail;  // sigh...

                pm.clear();
            }
            ...
    }

commit b99e135848ca5666308344cf5ecc9c7f95f30137
Author: Sage Weil <sage@inktank.com>
Date:   Mon Dec 5 17:25:21 2011 -0800

    osd: make backfill (basically) work again

    Still need to handle concurrent updates, log recovery vs backfill, etc.

    Signed-off-by: Sage Weil <sage.weil@dreamhost.com>
```

**Comment by jianwei1216** [comment]
@athanatos @rzarzynski @neha-ojha We can discuss the logic behind this problem

**Pull request closed without merging**
