### PR TITLE
jewel:  osd: Implement asynchronous scrub sleep

### PR DESCRIPTION
**Pull request by badone**
http://tracker.ceph.com/issues/20032

### CODE REVIEW

**Comment by badone** [comment]
Jenkins retest this please

**Comment by smithfarm** [comment]
@jdurgin @badone This passed a rados suite with two failures, one of which is scrub-related. See http://pulpito.front.sepia.ceph.com/smithfarm-2017-06-22_11:36:26-rados-wip-jewel-backports-distro-basic-smithi/

I'll be grateful for any help you can provide diagnosing these failures.

**Comment by smithfarm** [comment]
Note that this is one of the backports requested for inclusion in 10.2.8.

**Comment by jdurgin** [comment]
@smithfarm http://pulpito.front.sepia.ceph.com/smithfarm-2017-06-22_11:36:26-rados-wip-jewel-backports-distro-basic-smithi/1316533/ failed due to running out of space on osd.3:

```
2017-06-22 13:25:29.894162 7f9bbcce7700 10 filestore(/var/lib/ceph/osd/ceph-3) error opening file /var/lib/ceph/osd/ceph-3/current/0.d_head/DIR_D/DIR_9/DIR_2/obj-sgQ6vtDUfFGJMMT__head_D616229D__0 with flags=66:
 (28) No space left on device
2017-06-22 13:25:29.894174 7f9bbcce7700  0 filestore(/var/lib/ceph/osd/ceph-3) write couldn't open 0.d_head/#0:b944686b:::obj-sgQ6vtDUfFGJMMT:head#: (28) No space left on device
2017-06-22 13:25:29.894180 7f9bbcce7700 10 filestore(/var/lib/ceph/osd/ceph-3) write 0.d_head/#0:b944686b:::obj-sgQ6vtDUfFGJMMT:head# 81523~1 = -28
2017-06-22 13:25:29.894183 7f9bbcce7700  0 filestore(/var/lib/ceph/osd/ceph-3)  error (28) No space left on device not handled on operation 0x7f9bdabfb060 (95452.1.0, or op 0, counting from 0)
2017-06-22 13:25:29.894186 7f9bbcce7700  0 filestore(/var/lib/ceph/osd/ceph-3) ENOSPC handling not implemented
```

this has popped up more recently on smithis due to their smaller disks. It is not a bug in the backports.

The rgw failure is unrelated to this pr - it's failing slo and dlo tests, which I'm not sure are implemented in hammer or jewel - @yehudasa ?

**Comment by yehudasa** [comment]
@jdurgin @badone I assume that running against swift master branch? we added a couple of tests now, and these would fail in jewel.

**Comment by smithfarm** [comment]
> I assume that running against swift master branch? 

Indeed. The swift task in jewel does:

```
git clone git://git.ceph.com/git/swift.git /home/ubuntu/cephtest/swift
radosgw-admin to create a user
radosgw-admin to create another user
cd /home/ubuntu/cephtest/swift && ./bootstrap
```

I looked at https://github.com/ceph/swift and I see only two branches: "master" and "stable/diablo". Could you make a "jewel" branch that doesn't have the incompatible tests? I'll patch the jewel task to use it.

**Comment by smithfarm** [comment]
@jdurgin Given that the failures are unrelated, can this be merged?

**Comment by smithfarm** [comment]
Sorry, I didn't notice it was already reviewed.

**Comment by cbodley** [comment]
@smithfarm i pushed a `ceph-jewel` branch with those new slo/dlo tests removed

**Comment by smithfarm** [comment]
Argh!!! The swift task is in teuthology!

**Comment by smithfarm** [comment]
Can we simply transplant it into ceph/ceph.git master/kraken/jewel/hammer ?

**Comment by cbodley** [comment]
@smithfarm i also thought that was strange. i support moving it into ceph

**Comment by smithfarm** [comment]
@cbodley I'm discussing that with @zmc now. The move has to be done in a way that preserves git history.

**Comment by smithfarm** [comment]
Agreed that I will do the move tomorrow.

**Comment by smithfarm** [comment]
Since teuthology tasks in teuthology itself take precedence over ones in ceph of the same name, we can add the task to the ceph branches, first, and rip out the task from teuthology, second.

**Comment by smithfarm** [comment]
Phase one:

* master: https://github.com/ceph/ceph/pull/15859
* kraken: https://github.com/ceph/ceph/pull/15869
* jewel:  https://github.com/ceph/ceph/pull/15870
* hammer: https://github.com/ceph/ceph/pull/15871

**Comment by badone** [comment]
"The rgw failure is unrelated to this pr"

Should discussion and work to do with the rgw failure take place in a tracker rather than a merged and unrelated PR? Just asking...

**Comment by smithfarm** [comment]
@badone Sorry for the hijack. Let's move the discussion to http://tracker.ceph.com/issues/20392

**Comment by badone** [comment]
@smithfarm Not a problem of course mate, just thought it seemed a little odd.

**Pull request merged**
