### PR TITLE
doc/dev/developer_guide: What Is Merged and When?" could be less colloquial

### PR DESCRIPTION
**Pull request by anthonyeleven**
doc/dev/developer_guide: "What Is Merged and When?" could be less colloquial

... and misc cleanup and formatting.

Fixes: https://tracker.ceph.com/issues/46364
Signed-off-by: Anthony D'Atri <anthony.datri@gmail.com>

@zdover23 PTAL.  I've endeavored to not change any _meaning_ but welcome a second pair of eyes given that git branching can be subtle.

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by anthonyeleven** [comment]
jenkins test make check

**Comment by anthonyeleven** [comment]
jenkins test make check

**Comment by anthonyeleven** [comment]
jenkins test api

**Review by zdover23 — APPROVED** [review]
LGTM.

**Pull request merged**
