### PR TITLE
src/test/rgw/rgw_multi/tests.py: set fails_on_rgw attribute for not reliable tests

### PR DESCRIPTION
**Pull request by rkhudov**
Set `fails_on_rgw` attribute for tests:
- test_bucket_reshard_incremental
- test_bucket_reshard_full

Reason: Fails with following error on multiple configuration setups for rgw multisite test suite:
```
FAIL: test_multi.test_bucket_reshard_full
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/usr/local/lib/python3.9/site-packages/nose/util.py", line 620, in newfunc
    return func(*arg, **kw)
  File "/ceph-src/src/test/rgw/rgw_multi/tests.py", line 1730, in test_bucket_reshard_full
    zonegroup_bucket_checkpoint(zonegroup_conns, bucket.name)
  File "/ceph-src/src/test/rgw/rgw_multi/tests.py", line 401, in zonegroup_bucket_checkpoint
    target_conn.check_bucket_eq(source_conn, bucket_name)
  File "/ceph-src/src/test/rgw/rgw_multi/zone_rados.py", line 84, in check_bucket_eq
    check_object_eq(k1, k2)
  File "/ceph-src/src/test/rgw/rgw_multi/zone_rados.py", line 34, in check_object_eq
    eq(k1.owner.id, k2.owner.id)
AssertionError: 'RGW11111111111111111' != ''
```

Unset `fails_on_rgw` attribute for tests:
- test_bucket_full_sync_after_data_sync_init
- test_bucket_incremental_sync_after_data_sync_init
- test_sync_policy_config_zonegroup
- test_sync_single_bucket
- test_sync_different_buckets
- test_sync_single_bucket_to_multiple

Reason: Works with multiple configuration file setup.

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [x] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Comment by rkhudov** [comment]
jenkins test make check arm64

**Comment by rkhudov** [comment]
jenkins test make check

**Comment by rkhudov** [comment]
@smanjara  @cbodley mind take a look at it?

**Comment by rkhudov** [comment]
jenkins test make check

**Comment by smanjara** [comment]
thanks @rkhudov . 
for `test_bucket_reshard_incremental` and `test_bucket_reshard_full` @cbodley has some comments [here](https://github.com/ceph/ceph/pull/57060#discussion_r1673935081). we are waiting on [54393](https://github.com/ceph/ceph/pull/54393) to merge. these tests should pass with that pr. 

as for the tests that you unset `fails_on_rgw`, they weren't reliably passing our qa automation suite [teuthology](https://github.com/ceph/teuthology) which is why we had to disable them.

some of the `sync_policy` testcases that you have enabled might still pass. will soon schedule a run and post the results here.

**Comment by rkhudov** [comment]
> thanks @rkhudov . for `test_bucket_reshard_incremental` and `test_bucket_reshard_full` @cbodley has some comments [here](https://github.com/ceph/ceph/pull/57060#discussion_r1673935081). we are waiting on [54393](https://github.com/ceph/ceph/pull/54393) to merge. these tests should pass with that pr.
> 
> as for the tests that you unset `fails_on_rgw`, they weren't reliably passing our qa automation suite [teuthology](https://github.com/ceph/teuthology) which is why we had to disable them.
> 
> some of the `sync_policy` testcases that you have enabled might still pass. will soon schedule a run and post the results here.

Thank you for an update @smanjara 
The reason why I removed `fails_on_rgw` attribute from subset of the tests, because they were working fine for me with multiple configurations. But I agreed to wait for teuthology run to double check it

**Comment by adamemerson** [comment]
Is this still a going conern?

**Comment by smanjara** [comment]
> Is this still a going concern?

hey @adamemerson. there are many tests that still fail in our multisite suite on teuthology. I am actively working on a few of them. unfortunately, we will have to keep them disabled until they are fixed. we have a small set of tests that consistently pass (barring the autotrim) to run against pr's on main.

**Comment by adamemerson** [comment]
> > Is this still a going concern?
> 
> hey @adamemerson. there are many tests that still fail in our multisite suite on teuthology. I am actively working on a few of them. unfortunately, we will have to keep them disabled until they are fixed. we have a small set of tests that consistently pass (barring the autotrim) to run against pr's on main.

Thanks! I wasn't sure if this had been superseded by another PR, and I'm just on a sweep to try to make sure there isn't any PR stalled out needing attention.

**Comment by rkhudov** [comment]
Looks like `test_bucket_reshard_incremental` and `test_bucket_reshard_full` were fixed. This PR can be closed now

**Pull request closed without merging**
