### PR TITLE
common: reorder bl::iter to reduce its size from 40 to 32 on x86_64.

### PR DESCRIPTION
**Pull request by rzarzynski**

### CODE REVIEW

**Comment by tchaikov** [comment]
this breaks the ABI.

**Comment by gregsfortytwo** [comment]
Oh crap, thanks @tchaikov. This is getting a little tedious! :)

**Comment by rzarzynski** [comment]
jenkins retest this please

**Comment by rzarzynski** [comment]
Removed the *DNM* label as https://github.com/ceph/ceph/pull/24229 has been merged and it looks we have open season on API/ABI changes. :-)

**Pull request merged**
