### PR TITLE
RGW: a subuser with no permission can still list buckets and create buckets

### PR DESCRIPTION
**Pull request by shreyanshjain7174**
A S3 subuser having no permissions was able to do a normal user ops, from aws docs there's no functionality for a s3 subuser as we do have with swift. The fix here is to check the "subuser perm mask" before going forward with "no_acl" check.

Fixes: https://tracker.ceph.com/issues/63791

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [x] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Review by thotz — APPROVED** [review]

**Comment by shreyanshjain7174** [comment]
jenkins test make check

**Comment by cbodley** [comment]
passed qa in https://pulpito.ceph.com/cbodley-2024-04-09_13:16:23-rgw-wip-cbodley-testing-distro-default-smithi/

**Comment by cbodley** [comment]
this broke permissions in https://github.com/ceph/ceph/pull/54333 which is a high priority for the squid release, so i've opened https://github.com/ceph/ceph/pull/56838 to revert for now

**Comment by cbodley** [comment]
> this broke permissions in #54333 which is a high priority for the squid release, so i've opened #56838 to revert for now

@shreyanshjain7174 to expand on this, the value of this `perm` argument comes from `rgw::IAM::op_to_perm()` in rgw_iam_policy.h. this function only maps the permissions of s3 actions: https://github.com/ceph/ceph/blob/62ed3a0/src/rgw/rgw_iam_policy.h#L256-L259

non-s3 actions map to RGW_PERM_INVALID. these requests had previously succeeded because of the "S3 doesn't support account ACLs, so user_acl will be uninitialized" case that was moved by this pr. after this change, these requests now fail

before we can apply this fix for subusers, we would need to update `op_to_perm()` to cover all of these actions too: https://github.com/ceph/ceph/blob/62ed3a0/src/rgw/rgw_iam_policy.h#L115-L149 (and note that https://github.com/ceph/ceph/pull/54333 adds several more)

**Comment by shreyanshjain7174** [comment]
Got it, Thanks! @cbodley for the detailed explanation, will be sure to look after the merge of `users account` implementation.

**Pull request merged**
