### PR TITLE
mimic: osd: do_sparse_read(): Verify checksum earlier so we will try to repair

### PR DESCRIPTION
**Pull request by dzafman**

### CODE REVIEW

**Comment by dzafman** [comment]
Unrelated test failures
dzafman-2018-08-02_11:36:11-rados-wip-24875-mimic-distro-basic-smithi
[2854516]  Dead - mon_clock_skew_check
[2854435]  radosbench failure
[2854370]  rados_mon_workunits - Error ENOENT: no weight-set for pool 'cold'
[2854567]  mon/test_mon_osdmap_prune.sh - failure
[2854525]  rados_api_tests/thrashers - objects misplaced messages in log

**Comment by dzafman** [comment]
@smithfarm ceph/ceph#23377 has merged

**Comment by dzafman** [comment]
@smithfarm ceph/ceph#23377 has merged and sha1s match.

**Comment by yuriw** [comment]
[wip-yuri5-testing-2018-08-20-2118-mimic](https://trello.com/c/19sTEq0s/380-wip-yuri5-testing-2018-08-20-2118-mimic)

**Pull request merged**
