### PR TITLE
os/kstore: support db statistic

### PR DESCRIPTION
**Pull request by yanghonggang**
Signed-off-by: Yang Honggang <yanghonggang@umcloud.com>

### CODE REVIEW

**Comment by yanghonggang** [comment]
@liewegas just as what is done in bluestore :)

**Comment by tchaikov** [comment]
- http://pulpito.ceph.com/kchai-2018-04-20_05:42:59-rados-wip-kefu-testing-2018-04-20-1141-distro-basic-smithi/
- http://pulpito.ceph.com/kchai-2018-04-20_14:33:42-rados-wip-kefu-testing-2018-04-20-1141-distro-basic-mira/

the failures are addressed by 

- #21549
- #21579

**Comment by yanghonggang** [comment]
@tchaikov  ping

**Comment by tchaikov** [comment]
@yanghonggang please be patient, i will merge it after mimic is released.

**Pull request merged**
