### PR TITLE
cmake: require RocksDB 5.14 or higher

### PR DESCRIPTION
**Pull request by IlsooByun**
Signed-off-by: Ilsoo Byun <ilsoobyun@linecorp.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`

</details>

### CODE REVIEW

**Comment by tchaikov** [comment]
@IlsooByun why do you think we need rocksdb 5.10? i am not against this change, just want to understand the reason why we depend on this version and up.

**Comment by IlsooByun** [comment]
> @IlsooByun why do you think we need rocksdb 5.10? i am not against this change, just want to understand the reason why we depend on this version and up.

This is because when using an external rockdb library, build failed before versions 5.10 because the definition of the Env class is different. I tested it by increasing version up, and succeeded to build in 5.10.

**Comment by tchaikov** [comment]
@IlsooByun in that case, could you include the failure or the error message in the commit message? and revise the commit message to something like

> cmake: require RocksDB 5.10 or higher

?

**Comment by tchaikov** [comment]
http://pulpito.ceph.com/kchai-2019-10-28_03:11:42-rados-wip-kefu-testing-2019-10-28-0018-distro-basic-smithi/

**Comment by IlsooByun** [comment]
@tchaikov I tested it again and found there is additional change. 
In the current master version, RocksDBStore class uses Env::SetAllowNonOwnerAccess method.
But this method is added in 5.14. So I changed the required version from 5.8 to 5.14.

**Comment by tchaikov** [comment]
for posterity, the new API was introduced by https://github.com/facebook/rocksdb/commit/a0102aa6d7a09a2abbc39c17964cbf2447f6654e

**Pull request merged**
