### PR TITLE
quincy: qa/tasks/cephadm: enable mon_cluster_log_to_file

### PR DESCRIPTION
**Pull request by adk3798**
https://tracker.ceph.com/issues/64468

### CODE REVIEW

**Review by idryomov — APPROVED** [review]

**Comment by idryomov** [comment]
jenkins test make check

**Comment by idryomov** [comment]
jenkins test windows

**Comment by idryomov** [comment]
Not assigning to 17.2.x milestone until there is clarity on https://tracker.ceph.com/issues/64343.

**Review by ljflores — CHANGES_REQUESTED** [review]
Blocking this until we have a commit to whitelist appropriate warnings in the rados/orch suite (I can help with this). We can put this PR through the rados suite, and then use the results to create the whitelist commit.

(addressing @idryomov's comment)

**Pull request closed without merging**
