### PR TITLE
DragonDisk fails to create directories via S3: MissingContentLength

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/12041

### CODE REVIEW

**Comment by smithfarm** [comment]
@robbat2 @yehudasa This PR is included in the integration branch http://tracker.ceph.com/issues/11644 that just passed an rgw suite http://pulpito.ceph.com/smithfarm-2015-08-10_12:30:50-rgw-firefly-backports---basic-multi/ - do you think it's OK to merge?

**Comment by robbat2** [comment]
+2 from me

**Comment by dachary** [comment]
@yehudasa ping ?

**Comment by smithfarm** [comment]
Probably irrelevant, but this has passed a rados suite as well.

**Comment by smithfarm** [comment]
@robbat2 Do you still need/want this in firefly?

**Comment by smithfarm** [comment]
(It is already in hammer - if that is sufficient, we could leave it out of firefly.)

**Comment by robbat2** [comment]
Hammer is sufficient for this fix, but the strict_strtoll issue from #5997 does need to be in firefly.

**Comment by smithfarm** [comment]
Agreed with @robbat2 and @yehudasa to leave this fix out of firefly.

**Pull request closed without merging**
