### PR TITLE
ceph::buffer, Add cached_crc and cached_crc_adjust count in perf dump

### PR DESCRIPTION
**Pull request by mslovy**
In order to track the hit rate and efficiency of crc_cache

Signed-off-by: Ning Yao <zay11022@gmail.com>

### CODE REVIEW

**Comment by liewegas** [comment]
please rebase?

**Comment by mslovy** [comment]
@liewegas, rebase to master

**Comment by dachary** [comment]
@mslovy please ignore the bot failure, it is a known false negative (http://tracker.ceph.com/issues/13592). You can rebase and repush to trigger another run.

**Comment by mslovy** [comment]
rebase and repush again

**Pull request merged**
