### PR TITLE
rgw: avoid memory leaks

### PR DESCRIPTION
**Pull request by x11562**
Signed-off-by: Na Xie <xie.na@h3c.com>

### CODE REVIEW

**Comment by x11562** [comment]
@tchaikov  OK

**Comment by ifed01** [comment]
@x11562, IMO this fixes nothing - you simply enabled passing NULL pointers to free call..

**Comment by tchaikov** [comment]
@x11562 i think it should be 
```c
if (bin_)
  free(bin_);
```
and again, could remove the following 
```
bin_ = NULL;
```

**Comment by x11562** [comment]
@tchaikov 

I think we may not delete the line
```
bin_ = NULL;
```
after free() the pointer is assigned  to NULL, it is in line with most people's habits

**Comment by yehudasa** [comment]
@x11562 thanks for pointing this issue. Note that this code is not being used anywhere, and this entire function will be removed in the nfs work merge very soon, so I'm closing this PR.

**Pull request closed without merging**
