### PR TITLE
nautilus: qa/distros: add rhel 7.9

### PR DESCRIPTION
**Pull request by rakeshgm**
Signed-off-by: rakeshgm <rakeshgm@redhat.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Review by yuriw — APPROVED** [review]
Pls test before merging

**Comment by rakeshgm** [comment]
I ran one test on rhel 7.9.  The test passed. 
https://pulpito.ceph.com/rakesh-2020-11-23_08:26:54-rgw:singleton-nautilus-distro-basic-gibba/ 

rhel 8.3 test is failing because of a package not found. will work on it.

**Comment by rakeshgm** [comment]
I initially added rhel_8 distros too. I deleted the distros from here cause due to python3 packages issues in rhel_8.
I will send rhel_8 distros in a separate PR

**Comment by rakeshgm** [comment]
jenkins retest this please

**Comment by badone** [comment]
Build failure is due to importlib-metadata being updated in the last couple of days and breaking the build. Fix proposed in https://github.com/ceph/ceph/pull/38296

**Comment by badone** [comment]
Please rebase.

**Comment by batrick** [comment]
This broke symbolic links causing kcephfs suite to not run. I'll write up a fix in a follow-up PR.

**Comment by batrick** [comment]
#38772

**Pull request merged**
