### PR TITLE
squid: dencoder: update ceph-object-corpus submodule for 18.2.0 coverage

### PR DESCRIPTION
**Pull request by cbodley**
squid backport for https://github.com/ceph/ceph/pull/54735, no associated tracker issue

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Review by rzarzynski — APPROVED** [review]
LGTM assuming it passes make check.

**Comment by rzarzynski** [comment]
Oops, a dencoding problem in `squid`?

```
        /home/jenkins-build/build/workspace/ceph-pull-requests/ceph-object-corpus/archive/18.2.0/objects/cls::rbd::MirrorImageSiteStatus
        /home/jenkins-build/build/workspace/ceph-pull-requests/ceph-object-corpus/archive/18.2.0/objects/cls::rbd::ImageSnapshotSpec
        /home/jenkins-build/build/workspace/ceph-pull-requests/ceph-object-corpus/archive/18.2.0/objects/cls::rbd::MirrorImageMap
/tmp/test_object_1-o7xvhGDIo /tmp/test_object_2-FzDlJL1uM differ: byte 133, line 8
**** reencode of /home/jenkins-build/build/workspace/ceph-pull-requests/ceph-object-corpus/archive/18.2.0/objects/chunk_refs_t/ccb69d9ecd572c1f6ed9598899773cf1 resulted in a different dump ****
8c8
<             "hash": 329509888,
---
>             "hash": 2743578624,
13c13
<             "hash": 329509889,
---
>             "hash": 2743578625,
18c18
<             "hash": 329509890,
---
>             "hash": 2743578626,
23c23
<             "hash": 329509891,
---
>             "hash": 2743578627,
28c28
<             "hash": 329509892,
---
>             "hash": 2743578628,
33c33
<             "hash": 329509893,
---
>             "hash": 2743578629,
38c38
<             "hash": 329509894,
---
>             "hash": 2743578630,
43c43
<             "hash": 329509895,
---
>             "hash": 2743578631,
48c48
<             "hash": 329509888,
---
>             "hash": 2743578624,
53c53
<             "hash": 329509889,
---
>             "hash": 2743578625,
58c58
<             "hash": 329509890,
---
>             "hash": 2743578626,
63c63
<             "hash": 329509891,
---
>             "hash": 2743578627,
68c68
<             "hash": 329509892,
---
>             "hash": 2743578628,
73c73
<             "hash": 329509893,
---
>             "hash": 2743578629,
78c78
<             "hash": 329509894,
---
>             "hash": 2743578630,
83c83
<             "hash": 329509895,
---
>             "hash": 2743578631,
88c88
<             "hash": 329509888,
---
>             "hash": 2743578624,
93c93
<             "hash": 329509889,
---
>             "hash": 2743578625,
98c98
<             "hash": 329509890,
---
>             "hash": 2743578626,
103c103
<             "hash": 329509891,
---
>             "hash": 2743578627,
108c108
<             "hash": 329509892,
---
>             "hash": 2743578628,
113c113
<             "hash": 329509893,
---
>             "hash": 2743578629,
118c118
<             "hash": 329509894,
---
>             "hash": 2743578630,
123c123
<             "hash": 329509895,
---
>             "hash": 2743578631,
128c128
<             "hash": 329509888,
---
>             "hash": 2743578624,
133c133
<             "hash": 329509889,
---
>             "hash": 2743578625,
138c138
<             "hash": 329509890,
---
>             "hash": 2743578626,
143c143
<             "hash": 329509891,
---
>             "hash": 2743578627,
148c148
<             "hash": 329509892,
---
>             "hash": 2743578628,
153c153
<             "hash": 329509893,
---
>             "hash": 2743578629,
158c158
<             "hash": 329509894,
---
>             "hash": 2743578630,
163c163
<             "hash": 329509895,
---
>             "hash": 2743578631,
168c168
<             "hash": 329509888,
---
>             "hash": 2743578624,
173c173
<             "hash": 329509889,
---
>             "hash": 2743578625,
178c178
<             "hash": 329509890,
---
>             "hash": 2743578626,
183c183
<             "hash": 329509891,
---
>             "hash": 2743578627,
188c188
<             "hash": 329509892,
---
>             "hash": 2743578628,
193c193
<             "hash": 329509893,
---
>             "hash": 2743578629,
198c198
<             "hash": 329509894,
---
>             "hash": 2743578630,
203c203
<             "hash": 329509895,
---
>             "hash": 2743578631,
208c208
<             "hash": 329509888,
---
>             "hash": 2743578624,
213c213
<             "hash": 329509889,
---
>             "hash": 2743578625,
218c218
<             "hash": 329509890,
---
>             "hash": 2743578626,
223c223
<             "hash": 329509891,
---
>             "hash": 2743578627,
228c228
<             "hash": 329509892,
---
>             "hash": 2743578628,
233c233
<             "hash": 329509893,
---
>             "hash": 2743578629,
238c238
<             "hash": 329509894,
---
>             "hash": 2743578630,
243c243
<             "hash": 329509895,
---
>             "hash": 2743578631,
248c248
<             "hash": 329509888,
---
>             "hash": 2743578624,
253c253
<             "hash": 329509889,
---
>             "hash": 2743578625,
258c258
<             "hash": 329509890,
---
>             "hash": 2743578626,
263c263
<             "hash": 329509891,
---
>             "hash": 2743578627,
268c268
<             "hash": 329509892,
---
>             "hash": 2743578628,
273c273
<             "hash": 329509893,
---
>             "hash": 2743578629,
278c278
<             "hash": 329509894,
---
>             "hash": 2743578630,
283c283
<             "hash": 329509895,
---
>             "hash": 2743578631,
288c288
<             "hash": 329509888,
---
>             "hash": 2743578624,
293c293
<             "hash": 329509889,
---
>             "hash": 2743578625,
298c298
<             "hash": 329509890,
---
>             "hash": 2743578626,
303c303
<             "hash": 329509891,
---
>             "hash": 2743578627,
308c308
<             "hash": 329509892,
---
>             "hash": 2743578628,
313c313
<             "hash": 329509893,
---
>             "hash": 2743578629,
318c318
<             "hash": 329509894,
---
>             "hash": 2743578630,
323c323
<             "hash": 329509895,
---
>             "hash": 2743578631,
328c328
<             "hash": 329509888,
---
>             "hash": 2743578624,
333c333
<             "hash": 329509889,
---
>             "hash": 2743578625,
338c338
<             "hash": 329509890,
---
>             "hash": 2743578626,
343c343
<             "hash": 329509891,
---
>             "hash": 2743578627,
348c348
<             "hash": 329509892,
---
>             "hash": 2743578628,
353c353
<             "hash": 329509893,
---
>             "hash": 2743578629,
358c358
<             "hash": 329509894,
---
>             "hash": 2743578630,
363c363
<             "hash": 329509895,
---
>             "hash": 2743578631,
368c368
<             "hash": 329509888,
---
>             "hash": 2743578624,
373c373
<             "hash": 329509889,
---
>             "hash": 2743578625,
378c378
<             "hash": 329509890,
---
>             "hash": 2743578626,
383c383
<             "hash": 329509891,
---
>             "hash": 2743578627,
388c388
<             "hash": 329509892,
---
>             "hash": 2743578628,
393c393
<             "hash": 329509893,
---
>             "hash": 2743578629,
398c398
<             "hash": 329509894,
---
>             "hash": 2743578630,
403c403
<             "hash": 329509895,
---
>             "hash": 2743578631,
408c408
<             "hash": 329509888,
---
>             "hash": 2743578624,
413c413
<             "hash": 329509889,
---
>             "hash": 2743578625,
418c418
<             "hash": 329509890,
---
>             "hash": 2743578626,
423c423
<             "hash": 329509891,
---
>             "hash": 2743578627,
428c428
<             "hash": 329509892,
---
>             "hash": 2743578628,
433c433
<             "hash": 329509893,
---
>             "hash": 2743578629,
438c438
<             "hash": 329509894,
---
>             "hash": 2743578630,
443c443
<             "hash": 329509895,
---
>             "hash": 2743578631,
448c448
<             "hash": 329509888,
---
>             "hash": 2743578624,
453c453
<             "hash": 329509889,
---
>             "hash": 2743578625,
458c458
<             "hash": 329509890,
---
>             "hash": 2743578626,
463c463
<             "hash": 329509891,
---
>             "hash": 2743578627,
468c468
<             "hash": 329509892,
---
>             "hash": 2743578628,
473c473
<             "hash": 329509893,
---
>             "hash": 2743578629,
478c478
<             "hash": 329509894,
---
>             "hash": 2743578630,
483c483
<             "hash": 329509895,
---
>             "hash": 2743578631,
488c488
<             "hash": 329509889,
---
>             "hash": 2743578625,

287/292 Test #259: unittest-omap-manager .....................   Passed  1254.05 sec
288/292 Test #266: unittest-fltree-onode-manager .............   Passed  1287.32 sec
289/292 Test #253: unittest-transaction-manager ..............   Passed  1517.28 sec
290/292 Test  #31: run-rbd-unit-tests-1.sh ...................   Passed  1584.36 sec
291/292 Test  #32: run-rbd-unit-tests-61.sh ..................   Passed  1683.86 sec
292/292 Test #147: check-generated.sh ........................   Passed  1824.70 sec

99% tests passed, 1 tests failed out of 292

Total Test time (real) = 1826.69 sec

The following tests FAILED:
	148 - readable.sh (Failed)
Errors while running CTest
+ sleep 5
```

**Comment by cbodley** [comment]
> The following tests FAILED:
	148 - readable.sh (Failed)

**Comment by cbodley** [comment]
waiting on https://github.com/ceph/ceph/pull/56697 then

**Comment by cbodley** [comment]
jenkins test make check

**Pull request merged**
