### PR TITLE
rbd: drop initd-based systems for rbdmap

### PR DESCRIPTION
**Pull request by lxbsz**
Ceph versions jewel and above only support systemd.

Fixes: https://tracker.ceph.com/issues/48305
Signed-off-by: Xiubo Li <xiubli@redhat.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Review by trociny — APPROVED** [review]
:+1:

**Comment by dillaman** [comment]
I don't think we actually support initd-based systems anymore. Maybe just delete this file?

**Comment by lxbsz** [comment]
> I don't think we actually support initd-based systems anymore [1]. Maybe just delete this file?
> 
> [1] [2ca6dd2](https://github.com/ceph/ceph/commit/2ca6dd250b6a049f27fa17c5e8ca11674acb63f6)

Yeah, this looks good to me.

**Review by dillaman — APPROVED** [review]
lgtm -- thx

**Review by trociny — APPROVED** [review]
LGTM

**Pull request merged**
