### PR TITLE
src/test/objectstore/allocism/ops_replayer.cc: fix rados import

### PR DESCRIPTION
**Pull request by rkhudov**
Fix import from rados inside src/test/objectstore/allocism/ops_replayer.cc to fix following error during Ceph build:

```
fatal error: rados/buffer_fwd.h: No such file or directory
```

Commit reference: https://github.com/ceph/ceph/commit/3f4ffe0703e8482d2784102ea3a3cb57b8364673

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [x] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Comment by pereman2** [comment]
https://github.com/ceph/ceph/issues/58465 fixed here btw, sorry for the issue

**Comment by rkhudov** [comment]
> #58465 fixed here btw, sorry for the issue

It's alright. Which PR do you want to merge first?
Mine, because I opened it before yours?

**Comment by rkhudov** [comment]
> > #58465 fixed here btw, sorry for the issue
> 
> It's alright. Which PR do you want to merge first? Mine, because I opened it before yours?

@pereman2 ^

**Comment by pereman2** [comment]
Let's do this one as you took the time. Let's wait for make check to pass and merge

**Review by pereman2 — APPROVED** [review]

**Comment by Svelar** [comment]
jenkins test make check arm64

**Comment by ivancich** [comment]
@pereman2, out of curiosity what's the policy there in terms of running PRs through shaman/teuthology prior to merge?

The commit that caused this issue hadn't been run through shaman prior to merge as far as I can tell, and it then caused issues for others. Shaman is already slow as it is without having to run things through multiple times.

So is there a policy on your side of things?

**Pull request merged**
