### PR TITLE
jewel: rgw multisite: obsolete 'radosgw-admin period prepare' command

### PR DESCRIPTION
**Pull request by gaurav36**
Fixes: http://tracker.ceph.com/issues/17507

### CODE REVIEW

**Comment by gaurav36** [comment]
@cbodley

**Comment by cbodley** [comment]
@gaurav36 thanks! could you please use `git cherry-pick -x`, so that this backport commit includes your original comments, Signed-off-by, and the line `(cherry picked from commit 1508c70d36baae06377629416ff05b4138ccfbd4)` so we can associate it with the commit in master?

i'll update the ticket to reference this pr

**Comment by gaurav36** [comment]
@cbodley  Sure, Will do it in next PR

**Comment by dachary** [comment]
@gaurav36 closing this one and waiting for the next PR. Note that you could also **git push --force ** to update this PR (this is generally preferred).

**Comment by gaurav36** [comment]
@dachary  @cbodley  done https://github.com/ceph/ceph/pull/11574 , Thank you  :)

**Pull request closed without merging**
