### PR TITLE
nautilus: mgr/orchestrator: Remove "(add|test|remove)_stateful_service_rule"

### PR DESCRIPTION
**Pull request by sebastian-philipp**
http://tracker.ceph.com/issues/38808

#26772

### CODE REVIEW

**Comment by liewegas** [comment]
http://pulpito.ceph.com/sage-2019-03-22_15:28:27-rados-wip-sage4-testing-2019-03-22-0507-distro-basic-smithi/

**Comment by sebastian-philipp** [comment]
jenkins retest this please

**Comment by sebastian-philipp** [comment]
QA successful http://pulpito.ceph.com/swagner-2019-05-28_16:57:01-rados:mgr-wip-swagner-testing-nautilus-distro-basic-smithi/

**Comment by yuriw** [comment]
[wip-yuri-testing-2019-06-24-1916-nautilus](https://trello.com/c/1Y7sLJ0P/650-wip-yuri-testing-2019-06-24-1916-nautilus)

**Pull request merged**
