### PR TITLE
quincy: qa: account for rbd_trash object in krbd_data_pool.sh + related ceph{,adm} task fixes

### PR DESCRIPTION
**Pull request by idryomov**
backport tracker: https://tracker.ceph.com/issues/66909

---

backport of https://github.com/ceph/ceph/pull/58507
parent tracker: https://tracker.ceph.com/issues/66886

### CODE REVIEW

**Review by adk3798 — APPROVED** [review]

**Review by ajarr — APPROVED** [review]

**Comment by idryomov** [comment]
jenkins test make check

**Comment by yuriw** [comment]
ref: https://tracker.ceph.com/issues/66072

@idryomov pls merge when all checks passed, it was tested and approved

**Comment by idryomov** [comment]
jenkins test make check

**Comment by idryomov** [comment]
jenkins test make check

**Comment by idryomov** [comment]
https://pulpito.ceph.com/dis-2024-07-13_07:27:22-krbd-wip-yuri-testing-2024-07-11-0918-quincy-testing-default-smithi/

**Pull request merged**
