### PR TITLE
reef: doc/mgr: document lack of MSWin NFS 4.x support

### PR DESCRIPTION
**Pull request by zdover23**
Document that no version of Microsoft Windows supports mounting an NFS v4.x export natively, as of the time of this commit.

This commit has been made in response to an anonymous note left on https://pad.ceph.com/p/Report_Documentation_Bugs.

Signed-off-by: Zac Dover <zac.dover@proton.me>
(cherry picked from commit 03656c02a70d4ab719cbcf605517f8a2e9e81117)

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [x] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [x] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Review by anthonyeleven — APPROVED** [review]

**Comment by mattbenjamin** [comment]
well there is an open source client originally produced by University of Michigan, that is now getting some maintenance at DESY:

> From: Roland Mainz <[roland.mainz@nrubsig.org](mailto:roland.mainz@nrubsig.org)>
> Date: Sat, Dec 30, 2023 at 4:34 PM
> Subject: [Ms-nfs41-client-devel] ANN: NFSv4.1 Windows driver binaries
> for Windows 10 for testing, 2023-12-30 ...
> To: <[ms-nfs41-client-devel@lists.sourceforge.net](mailto:ms-nfs41-client-devel@lists.sourceforge.net)>
> 
> 
> Hi!
> 
> ----
> 
> I've created a set of test binaries for the NFSv4.1 filesystem driver
> for Windows, based on https://github.com/kofemann/ms-nfs41-client
> (commit id #43852f547ce80b3b33bb05c2e993e322d2264dfa), for testing and
> feedback (download URL below).
> Please send comments, bugs, test reports, complaints etc. to
> https://sourceforge.net/projects/ms-nfs41-client/lists/ms-nfs41-client-devel

**Comment by zdover23** [comment]
> well there is an open source client originally produced by University of Michigan, that is now getting some maintenance at DESY:
> 
> > From: Roland Mainz <[roland.mainz@nrubsig.org](mailto:roland.mainz@nrubsig.org)>
> > Date: Sat, Dec 30, 2023 at 4:34 PM
> > Subject: [Ms-nfs41-client-devel] ANN: NFSv4.1 Windows driver binaries
> > for Windows 10 for testing, 2023-12-30 ...
> > To: <[ms-nfs41-client-devel@lists.sourceforge.net](mailto:ms-nfs41-client-devel@lists.sourceforge.net)>
> > Hi!
> > 
> > I've created a set of test binaries for the NFSv4.1 filesystem driver
> > for Windows, based on https://github.com/kofemann/ms-nfs41-client
> > (commit id #43852f547ce80b3b33bb05c2e993e322d2264dfa), for testing and
> > feedback (download URL below).
> > Please send comments, bugs, test reports, complaints etc. to
> > https://sourceforge.net/projects/ms-nfs41-client/lists/ms-nfs41-client-devel

@mattbenjamin: Well, this is an exciting development that for some reason only just now, thirteen hours after the time of your comment, arrived in my inbox. Do you think we should mention ms-nfs41-client in the upstream docs?

**Comment by mattbenjamin** [comment]
well, it's at least as relevant as there *not* being one;  I am pretty sure it's at least a year away from being a production client even if this work takes off, though.

**Comment by zdover23** [comment]
> well, it's at least as relevant as there _not_ being one; I am pretty sure it's at least a year away from being a production client even if this work takes off, though.

@mattbenjamin: Would you tell me which list Roland Mainz's email was sent to? I've been thinking today about including this MS NFS client in the documentation, and the more I think about it, the more I like the idea of the the upstream documentation playing a role in bringing attention to bleeding-edge stuff that is fresh out of the oven.

**Comment by mattbenjamin** [comment]
@zdover23 linux-nfs, I believe

**Pull request merged**
