### PR TITLE
ceph-disk: change the lockbox partition number to 5

### PR DESCRIPTION
**Pull request by shangzhong**
Fixes: http://tracker.ceph.com/issues/20556
Signed-off-by: Shangzhong Zhu <zhu.shangzhong@zte.com.cn>

### CODE REVIEW

**Comment by shangzhong** [comment]
test this please

**Comment by shangzhong** [comment]
when we use ceph-disk tool to prepare an osd device with --dmcrypt option, and both --block.db and --block.wal are specified to be the same whole device, the ceph-disk will fail. 

The root cause is that lockbox partition and block.db partition are using the same number 3，and the block.wal partition number was set to 4 as default. 

So the lockbox partition number should be change to 5 as default.

**Comment by tchaikov** [comment]
nit, the fixes line should be
```
Fixes: http://tracker.ceph.com/issues/20556
```
which sits right before your "Signed-off-by" line.

**Comment by shangzhong** [comment]
Thanks Kefu Chai, it's OK now.

**Comment by shangzhong** [comment]
Only remove the blank line between the "Signed-off-by" line and "Fixes" line.

**Comment by tchaikov** [comment]
http://pulpito.ceph.com/kchai-2017-07-24_12:22:52-ceph-disk-wip-kefu-testing-distro-basic-vps/

**Pull request merged**
