### PR TITLE
mgr/dashboard: disable NFSv3 support 

### PR DESCRIPTION
**Pull request by epuertat**
Rather than removing lots of code supporting v3 NFS exports, I'm just
disabling the NFSv3 selector, so new exports cannot be set to NFSv3. For
the existing ones, this cannot be modified either.

image

Fixes: https://tracker.ceph.com/issues/49718
Signed-off-by: Ernesto Puerta <epuertat@redhat.com>

## Checklist
- [x] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by epuertat** [comment]
jenkins test dashboard

**Comment by epuertat** [comment]
jenkins test dashboard

**Comment by epuertat** [comment]
jenkins test make check

**Comment by epuertat** [comment]
jenkins test dashboard

**Comment by kalebskeithley** [comment]
<ykaul email>Has this been consulted with the PM downstream? I'm not sure this is OK - have we verified customers are not using it?
<ykaul email>(As an example, when we think about migration from RHGS - Gluster's internal NFS implementation was a v3 only).

If we have customers running legacy systems using ceph storage via NFS — e.g. Solaris, HP/UX, or AIX — they may need NFSv3 for some time.

A change like this needs lots of advance warning IMO.

Ganesha supports NFSv3 and NFSv4.x.  What is the rationale for disabling it in mgr?

**Comment by epuertat** [comment]
jenkins test make check

**Comment by tchaikov** [comment]
jenkins test make check

**Comment by epuertat** [comment]
Closing as this will be undertaken as part of the NFSv4 fixing: https://tracker.ceph.com/issues/49925

**Comment by votdev** [comment]
> Closing as this will be undertaken as part of the NFSv4 fixing: [tracker.ceph.com/issues/49925](https://tracker.ceph.com/issues/49925)

Are there any plans to backport all these changes mentioned in https://tracker.ceph.com/issues/49925 to Octopus? If not, i would suggest to reopen this PR and backport it to `Pacific` and `Octopus`.

NFSv3 is not supported in `Octopus` according to:
- https://github.com/ceph/ceph/blob/octopus/doc/cephfs/fs-nfs-exports.rst#L201
- https://docs.ceph.com/en/octopus/cephfs/fs-nfs-exports/#mount
- https://github.com/ceph/ceph/pull/37484#issuecomment-702180404

**Pull request closed without merging**
