### PR TITLE
rados: Add units to rados bench output

### PR DESCRIPTION
**Pull request by guzhongyan**
Fixes: #12248
Signed-off-by: Gu Zhongyan <guzhongyan@360.com>

### CODE REVIEW

**Comment by guzhongyan** [comment]
The first time  when I used rados bench,  I got a little confused about the latency unit of rados bench output. only diving into source code, then you can figure out the exact unit.
add the units to make rados bench output more friendly.

**Comment by liewegas** [comment]
This conflicts with https://github.com/ceph/ceph/pull/7195.  If you have a moment to rebase on top of that branch, that would be great.  Otherwise I can do it (since your branch came before mine :).

**Comment by guzhongyan** [comment]
Hi Sage,
WIll be greatly appreciated if you can help do the rebase work. I'm just in the learning process to how to use git and not quite familiar yet. 

Thanks,
Zhongyan

**Comment by liewegas** [comment]
merged manually, 669b932934d60bbfa751cebd9340f11bd95e2853

**Pull request closed without merging**
