### PR TITLE
mgr/telemetry: anonymize daemons in telemetry `perf_counters`

### PR DESCRIPTION
**Pull request by ljflores**
In the telemetry perf channel we collect 'perf_counters' of individual daemons.
The monitors appear with their full name, which includes the host name.
The host name part must be anonymized.

To err on the safe side, I have anonymized all daemons except for osds,
since they are not attached to host names.

Result looks like this in the perf report:
```
perf_counters": {
        "mds.a448b49e613b841b131352d4fc887042b62ae81c": {
            "mds": {
                "caps": {
                    "value": 2
                },
                "ceph_cap_op_flush_ack": {
                    "value": 0
                },
                "ceph_cap_op_flushsnap_ack": {
                    "value": 0
                },
                "ceph_cap_op_grant": {
                    "value": 0
                },
                "ceph_cap_op_revoke": {
                    "value": 0
                },
                "ceph_cap_op_trunc": {
                    "value": 0
...
          "mon.1b1b829ba9298527f4934053a4742a1710937007": {
                      "mon": {
                          "election_call": {
                              "value": 2
                          },
                          "election_lose": {
                              "value": 0
                          },
                          "election_win": {
                              "value": 2
```
And a debug message available in the mgr log reveals the mapping of anonymized --> real names:
```
2022-04-11T15:46:24.694+0000 7f77e5b36700  0 [telemetry DEBUG root] Anonymized daemon mapping for telemetry perf_counters (anonymized: real): {'mds.b9fc993c21092114db570f866593f7536a556994': 'mds.c', 'mon.8e7ea78d9cb1fbf6a49b02a6a3bb9bcafd519e72': 'mon.a', 'mon.bf83acd7973418dbc272d6ac6aac0bceb025bddc': 'mon.b', 'mon.b9fc993c21092114db570f866593f7536a556994': 'mon.c', 'rgw.370b0e5b51a0724d58933dfebe0fcc5cefa74968': 'rgw.4410', 'rgw.50e6f6d90018f436cb1a4936bbdcb3d617838c69': 'rgw.4417'}
```

Fixes: https://tracker.ceph.com/issues/55229
Signed-off-by: Laura Flores <lflores@redhat.com>

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by ljflores** [comment]
jenkins test make check

**Comment by ljflores** [comment]
jenkins test api

**Comment by ljflores** [comment]
jenkins test make check

**Review by yaarith — COMMENTED** [review]
Pushed a couple of changes; output looks good.
Edited PR description to match the actual output.

**Comment by yaarith** [comment]
@neha-ojha @ljflores this looks good to go and ready for qa.
Please have a look before approval.

**Comment by yaarith** [comment]
@ljflores can't add you as a reviewer since you're the pr author...

**Comment by yaarith** [comment]
jenkins test make check

**Review by yaarith — APPROVED** [review]

**Pull request merged**
