### PR TITLE
client: fstat should take CEPH_STAT_CAP_INODE_ALL

### PR DESCRIPTION
**Pull request by ukernel**
Fixes: http://tracker.ceph.com/issues/15723
Signed-off-by: Noah Watkins <nwatkins@redhat.com>
Signed-off-by: Yan, Zheng <zyan@redhat.com>

### CODE REVIEW

**Comment by gregsfortytwo** [comment]
This shouldn't get merged yet; @noahdesu reported he was getting cap deadlock behavior with it turned on. I doubt this is the actual trigger but we should work it out first.

**Comment by noahdesu** [comment]
Anything I can do to help speed this up by getting logs etc... or is it pretty clear what's going on?

**Comment by gregsfortytwo** [comment]
I haven't looked, have you @ukernel?

**Comment by noahdesu** [comment]
I'm running this again and I'm not able to reproduce it. I think that the prior experiment had an unclean shutdown path in the application and starting it back up caused hang waiting around on timeouts or what not.

**Comment by ukernel** [comment]
I can reproduce it by using following program. 
while this program is running, truncating 'testfile' on other client blocks infinitely. But the behaviour is constant with this patch or without this patch. 

<pre>
#define _FILE_OFFSET_BITS 64
#include <features.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <time.h>
#include <stdio.h>
#include <errno.h>
#include <cephfs/libcephfs.h>


int main(int argc, char *argv[]) {
        struct ceph_mount_info *cmount = NULL;

        ceph_create(&cmount, "admin");
        ceph_conf_read_file(cmount, NULL);
        ceph_mount(cmount, NULL);

        int fd = ceph_open(cmount, "testfile", O_RDWR|O_CREAT, 0666);
        int count = 0;
        time_t start = time(NULL);
        for (;;) {
                count++;
                struct stat st;
                int ret = ceph_fstat(cmount, fd, &st);
                if (ret < 0)
                        break;
                if (time(NULL) > start) {
                        printf("%d\n", count);
                        count = 0;
                        start = time(NULL);
                }
        }
        
        ceph_unmount(cmount);
        return 0;
}
</pre>

**Comment by jcsp** [comment]
@ukernel  do you think we should wait for https://github.com/ceph/ceph/pull/8965 before merging this one?

**Comment by ukernel** [comment]
no, I don't think we need to wait #8965

**Comment by jcsp** [comment]
Passing here: http://pulpito.ceph.com/jspray-2016-06-02_01:58:41-fs-wip-jcsp-testing-20160601---basic-mira/

**Pull request merged**
