### PR TITLE
[DNM] luminous: In upgrade/jewel-x/point-to-point-x, the -x s3-tests runs before client is upgraded to -x

### PR DESCRIPTION
**Pull request by shinobu-x**
http://tracker.ceph.com/issues/21520

### CODE REVIEW

**Comment by yuriw** [comment]
[wip-yuri-testing-2018-01-29-1733-luminous](https://trello.com/c/H8Vf62lm/245-wip-yuri-testing-2018-01-29-1733-luminous)

**Comment by yuriw** [comment]
not sure how to test this..

http://pulpito.ceph.com/yuriw-2018-01-29_20:38:20-upgrade:luminous-x:point-to-point-x-wip-yuri-testing-2018-01-29-1733-luminous-distro-basic-smithi/

**Comment by yuriw** [comment]
@shinobu-x @smithfarm I am having mental block testing this PR, suggest merging it ?

**Comment by yuriw** [comment]
@shinobu-x can you pls help testing this?  I am having trouble to run tests.
I think we need to run upgrade/luminous-x/point-to-point-x test only

**Comment by yuriw** [comment]
indeed mental block, i was using the wrong suite
testing again http://pulpito.ceph.com/yuriw-2018-01-31_20:30:16-upgrade:jewel-x:point-to-point-x-wip-yuri-testing-2018-01-29-1733-luminous-distro-basic-smithi/

**Comment by yuriw** [comment]
@shinobu-x pls check out test results, lots of  TestClsRbd failures on client.1
Add `luminous-batch-1` back for retesting when done

**Comment by smithfarm** [comment]
Closing in accordance with http://tracker.ceph.com/issues/22888 (the entire jewel-x/point-to-point-x subsuite will be dropped in luminous).

**Pull request closed without merging**
