### PR TITLE
nautilus: mgr/volumes: per subvolume trash can

### PR DESCRIPTION
**Pull request by ajarr**
## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by ajarr** [comment]
https://shaman.ceph.com/builds/ceph/nautilus-ajarr-fix-47147/

**Comment by ShyamsundarR** [comment]
> https://shaman.ceph.com/builds/ceph/nautilus-ajarr-fix-47147/

Unfortunately we need https://github.com/ceph/ceph/pull/36404 for the tests to pass, which was not mentioned in the parent PR. The build above does not contain that additional cherry-pick.

Discussed with @ajarr and I will take his fix into my PR #36883 and start a build (and a subsequent test).

**Comment by smithfarm** [comment]
@ShyamsundarR Can you give us an update? What is currently needed to unblock this PR?

**Comment by ShyamsundarR** [comment]
> @ShyamsundarR Can you give us an update? What is currently needed to unblock this PR?

The additional commit in this PR has been absorbed into #36833 (I made a typo earlier that it was in #36883 (8 instead of 3)).

The commit can be found here: https://github.com/ceph/ceph/pull/36833/commits/ef17a6dfc7adc8878bdaa10f2b74f82b69e77902
The PR that contains the commit is already merged: https://github.com/ceph/ceph/pull/36833

This PR can hence be closed and should not be merged.

**Pull request closed without merging**
