### PR TITLE
rgw/rgw_lua_utils: return error using luaL_error()

### PR DESCRIPTION
**Pull request by tchaikov**
it's found on aarch64, the exception is not caught even if we do
catch exactly the same type of thrown exception, and the uncaught
exception ends up with a std::terminate() call. it could be the ABI
mismatch in aarch64, so the C++ runtime failed to find the catch block.

in this change, luaL_error() is used to populate the error to the
caller instead to workaround this issue.

Signed-off-by: Kefu Chai <kchai@redhat.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by tchaikov** [comment]
jenkins test make check arm64

**Comment by tchaikov** [comment]
jenkins test make check arm64

**Comment by yuvalif** [comment]
thanks @tchaikov ! 
according to this: https://www.lua.org/manual/5.3/manual.html#4.6
using `lua_errro` the correct way to handle errors since C++ exception support depends on how lua was compiled.

**Review by yuvalif — APPROVED** [review]

**Comment by tchaikov** [comment]
@yuvalif i tested this change locally using `unittest_rgw_lua`. am i supposed to run the rgw suite to verify this change?

**Comment by yuvalif** [comment]
> @yuvalif i tested this change locally using `unittest_rgw_lua`. am i supposed to run the rgw suite to verify this change?

there are no lua tests in the rgw tests suites. so, IMO, not needed.
we have at least 2 unit tests (for invalid fields) that should cover at least some of the code changes

**Comment by tchaikov** [comment]
@yuvalif Yuval, thank you for your review and confirmation.

**Pull request merged**
