### PR TITLE
librados,test,rgw: cleanups to deprecate safe_cb related functions

### PR DESCRIPTION
**Pull request by tchaikov**
it's a follow-up of #12607 

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`

</details>

### CODE REVIEW

**Comment by tchaikov** [comment]
jenkins test make check

**Comment by tchaikov** [comment]
@neha-ojha @liewegas mind taking a look?

**Comment by tchaikov** [comment]
@dillaman because this change is backward compatible. sure, will update the stub accordingly.

**Comment by dillaman** [comment]
> @dillaman because this change is backward compatible. sure, will update the stub accordingly.

How so? The method signature was `_ZN8librados7v14_2_05Rados21aio_create_completionEPvPFvS2_S2_ES4_` but now librbd is calling a method w/ a signature of `_ZN8librados7v14_2_05Rados21aio_create_completionEPvPFvS2_S2_E` which does not have a definition available in `librados_test_stub`

**Comment by tchaikov** [comment]
```
#0  _rados_aio_create_completion2 (cb_arg=0x5555585bbe60,
    cb_complete=0x555557874d10 <librbd::util::detail::rados_state_callback<librbd::image::OpenRequest<librbd::ImageCtx>, &librbd::image::OpenRequest<librbd::ImageCtx>::handle_v2_detect_header, true>(void*, void*)>, pc=0x7fffffffd080) at ../src/librados/librados_c.cc:2247
#1  0x00007ffff7dd314d in librados::v14_2_0::Rados::aio_create_completion (cb_arg=0x5555585bbe60,
    cb_complete=0x555557874d10 <librbd::util::detail::rados_state_callback<librbd::image::OpenRequest<librbd::ImageCtx>, &librbd::image::OpenRequest<librbd::ImageCtx>::handle_v2_detect_header, true>(void*, void*)>) at ../src/librados/librados_cxx.cc:2805
#2  0x0000555557874a24 in librbd::util::create_rados_callback<librbd::image::OpenRequest<librbd::ImageCtx>, &librbd::image::OpenRequest<librbd::ImageCtx>::handle_v2_detect_header, true> (
    obj=0x5555585bbe60) at ../src/librbd/Utils.h:145
#3  0x000055555786eb5b in librbd::image::OpenRequest<librbd::ImageCtx>::send_v2_detect_header (this=0x5555585bbe60) at ../src/librbd/image/OpenRequest.cc:102
#4  0x000055555786e35a in librbd::image::OpenRequest<librbd::ImageCtx>::send (this=0x5555585bbe60) at ../src/librbd/image/OpenRequest.cc:49
#5  0x00005555577662d0 in librbd::ImageState<librbd::ImageCtx>::send_open_unlock (this=0x5555585b3cf0) at ../src/librbd/ImageState.cc:588
#6  0x0000555557765d9a in librbd::ImageState<librbd::ImageCtx>::execute_next_action_unlock (this=0x5555585b3cf0) at ../src/librbd/ImageState.cc:517
#7  0x0000555557765ed3 in librbd::ImageState<librbd::ImageCtx>::execute_action_unlock (this=0x5555585b3cf0, action=..., on_finish=0x7fffffffd3b0) at ../src/librbd/ImageState.cc:542
#8  0x0000555557764370 in librbd::ImageState<librbd::ImageCtx>::open (this=0x5555585b3cf0, flags=0, on_finish=0x7fffffffd3b0) at ../src/librbd/ImageState.cc:270
#9  0x0000555557764156 in librbd::ImageState<librbd::ImageCtx>::open (this=0x5555585b3cf0, flags=0) at ../src/librbd/ImageState.cc:249
#10 0x00005555574c754d in TestFixture::open_image (this=0x5555583dc070, image_name="image1", ictx=0x5555583dc130) at ../src/test/librbd/test_fixture.cc:83
#11 0x0000555556c70c4a in TestMockDeepCopyRequest::SetUp (this=0x5555583dc070) at ../src/test/librbd/test_mock_DeepCopyRequest.cc:153
#12 0x00005555579cc16b in testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void> (object=0x5555583dc070, method=&virtual testing::Test::SetUp(), location=0x555557c97223 "SetUp()")
    at ../src/googletest/googletest/src/gtest.cc:2439
#13 0x00005555579c5cb3 in testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void> (object=0x5555583dc070, method=&virtual testing::Test::SetUp(), location=0x555557c97223 "SetUp()")
    at ../src/googletest/googletest/src/gtest.cc:2475
#14 0x00005555579a3fd1 in testing::Test::Run (this=0x5555583dc070) at ../src/googletest/googletest/src/gtest.cc:2509
#15 0x00005555579a49c1 in testing::TestInfo::Run (this=0x5555583dbdc0) at ../src/googletest/googletest/src/gtest.cc:2690
#16 0x00005555579a50cd in testing::TestSuite::Run (this=0x5555583d6b50) at ../src/googletest/googletest/src/gtest.cc:2822
#17 0x00005555579b0b45 in testing::internal::UnitTestImpl::RunAllTests (this=0x5555583c6220) at ../src/googletest/googletest/src/gtest.cc:5332
#18 0x00005555579cd548 in testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool> (object=0x5555583c6220,
    method=(bool (testing::internal::UnitTestImpl::*)(testing::internal::UnitTestImpl * const)) 0x5555579b072c <testing::internal::UnitTestImpl::RunAllTests()>,
    location=0x555557c97c68 "auxiliary test code (environments or event listeners)") at ../src/googletest/googletest/src/gtest.cc:2439
#19 0x00005555579c6d5b in testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool> (object=0x5555583c6220,
    method=(bool (testing::internal::UnitTestImpl::*)(testing::internal::UnitTestImpl * const)) 0x5555579b072c <testing::internal::UnitTestImpl::RunAllTests()>,
    location=0x555557c97c68 "auxiliary test code (environments or event listeners)") at ../src/googletest/googletest/src/gtest.cc:2475
#20 0x00005555579af433 in testing::UnitTest::Run (this=0x55555836b200 <testing::UnitTest::GetInstance()::instance>) at ../src/googletest/googletest/src/gtest.cc:4920
#21 0x0000555556b983b7 in RUN_ALL_TESTS () at ../src/googletest/googletest/include/gtest/gtest.h:2472
#22 0x0000555556b981f8 in main (argc=1, argv=0x7fffffffdaf8) at ../src/test/librbd/test_main.cc:71
```

**Comment by tchaikov** [comment]
changelog

- fix `test/libradosstriper/aio.cc`: no need to wait for the semaphore twice. as `set_completion_safe()` was removed.

**Comment by tchaikov** [comment]
- http://pulpito.ceph.com/kchai-2019-10-30_09:06:39-rados-wip-kefu-testing-2019-10-30-0922-distro-basic-mira/
- http://pulpito.ceph.com/kchai-2019-10-31_15:08:58-rados-wip-kefu-testing-2019-10-30-0922-distro-basic-mira/
- http://pulpito.ceph.com/kchai-2019-11-01_07:20:07-rados-wip-kefu-testing-2019-11-01-0944-distro-basic-smithi/

**Comment by dillaman** [comment]
Failures in `unittest_journal` seem to be cropping up since this merged [1][2]

[1] https://jenkins.ceph.com/job/ceph-pull-requests/37653/consoleText
[2] https://tracker.ceph.com/issues/42598

**Pull request merged**
