### PR TITLE
[backport] qa/tasks: systemd test backport to jewel

### PR DESCRIPTION
**Pull request by vasukulkarni**
http://tracker.ceph.com/issues/19718

backports for jewel(also needed for kraken)

### CODE REVIEW

**Comment by vasukulkarni** [comment]
@smithfarm that is what i did,  Are you seeing anything missing?

**Comment by smithfarm** [comment]
@vasukulkarni I think you must have omitted the `-x` because there is no `(cherry picked from . . .)` line in the commit message.

**Comment by vasukulkarni** [comment]
@smithfarm thanks, fixed.

**Comment by smithfarm** [comment]
@vasukulkarni I opened trackers for this:

master: http://tracker.ceph.com/issues/19717
kraken: http://tracker.ceph.com/issues/19719
jewel: http://tracker.ceph.com/issues/19718

I couldn't assign them to you because you don't seem to be in Redmine - maybe you could ask @ktdreyer to add you?

**Comment by vasukulkarni** [comment]
I am in redmine, I will check with David even I dont see a way to assign it to myself.

**Comment by smithfarm** [comment]
@vasukulkarni Oh, OK - I added you to the "ceph developers" group and you should now be able to assign the issues to yourself.

**Comment by vasukulkarni** [comment]
Thanks that worked!

**Pull request merged**
