### PR TITLE
msg: add const overload to entity_addr_t functions

### PR DESCRIPTION
**Pull request by Adirl**
in order to have a cleaner code adding const overload
functions in4_addr and in6_addr

Signed-off-by: Adir Lev <adirl@mellanox.com>

### CODE REVIEW

**Comment by Adirl** [comment]
@mattbenjamin @cbodley This is the patch i promised to create regarding entity_addr_t const functions

**Comment by yuyuyu101** [comment]
👍

**Comment by Adirl** [comment]
@cbodley @mattbenjamin Anything else needed here? Thanks

**Comment by cbodley** [comment]
@Adirl sorry, it took me a bit to get a dev environment with the necessary libs to build and drivers to test. looks good, thank you

**Comment by Adirl** [comment]
@cbodley  Thanks

**Pull request merged**
