### PR TITLE
jewel: build/ops: install-deps.sh based on /etc/os-release

### PR DESCRIPTION
**Pull request by jan--f**
http://tracker.ceph.com/issues/18199
http://tracker.ceph.com/issues/18466

### CODE REVIEW

**Comment by jan--f** [comment]
Fixes http://tracker.ceph.com/issues/18198

**Comment by smithfarm** [comment]
**original description**

Avoid shaky distro detection by package manager. Use /etc/os-release instead.

Fixed by commits
85a370e35fc42031a7f7e24dea9e50a649c0f309
fd37e87f6de0b8e272a2859ec52d6ceab277db7a

and present in master and Kraken.

Would be useful to have this in Jewel too.

**Comment by smithfarm** [comment]
@jan--f Please get rid of the merge commit.

**Comment by smithfarm** [comment]
@dachary IIRC there is nothing in the integration test suites that exercises install-deps.sh, correct?

**Comment by smithfarm** [comment]
@jan--f Please rebase to the latest jewel (i.e. something like `git fetch ceph ; git rebase ceph/jewel ; git push -f`)

**Comment by smithfarm** [comment]
The tox test failure is benign.

**Comment by smithfarm** [comment]
Jenkins, retest this please

**Comment by smithfarm** [comment]
@jan--f Please cherry-pick 266f4d4f into this PR. When you do please remind me to:

* add http://tracker.ceph.com/issues/18466 to this PR description
* add this PR's URL to the description of http://tracker.ceph.com/issues/18466
* change http://tracker.ceph.com/issues/18466 status to In progress

**Comment by jan--f** [comment]
Fixes: http://tracker.ceph.com/issues/18466

**Comment by smithfarm** [comment]
Jenkins, retest this please

**Comment by smithfarm** [comment]
@jan--f Excellent, thanks!

**Pull request merged**
