### PR TITLE
osd: concurrently read when finish promote

### PR DESCRIPTION
**Pull request by XinzeChi**
when finish promote, osd would kick the proxy read in flight.
But the requeue read would not read object until the promoted object
writen to filestore. I think this latency maybe not less
than do_proxy_read in some case.
 
Signed-off-by: Xinze Chi <xmdxcxz@gmail.com>

### CODE REVIEW

**Comment by dachary** [comment]
please ignore the bot failure on ubuntu, it was because of a problem that was fixed earlier today

**Comment by liewegas** [comment]
In order to merge this we'd have to test the new false path too in QA.

Have you done an experiment to see whether this is a better strategy?  If so, should we default to false?

**Comment by XinzeChi** [comment]
@liewegas, Yes,  I have use the PR in my test cluster. This should be a better strategy. But I am not so sure whether it is good for all workload.

**Comment by dachary** [comment]
@XinzeChi could you please rebase ?

**Pull request closed without merging**
