### PR TITLE
crimson/osd/ops_executor: queue pg log entry for CLONE at the front

### PR DESCRIPTION
**Pull request by xxhdx1985126**
This is consistent with the order of ops in ceph::os::Transaction

Signed-off-by: Xuehan Xu <xuxuehan@qianxin.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [x] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Comment by xxhdx1985126** [comment]
jenkins test api

**Comment by xxhdx1985126** [comment]
jenkins test api

**Review by Matan-B — COMMENTED** [review]
@rzarzynski, from #48527, was the order intentionally preserved or simply wasn't part of the PR's scope?
```
3. It also creates a pg_log_entry which is appended at the end of log_entires at the flush
(preserved the orignal logic, havent't experimented with it yet).
```

**Comment by xxhdx1985126** [comment]
@rzarzynski Please take a look, thanks:-)

**Comment by liu-chunmei** [comment]
@xxhdx1985126  does the patch got merged at some other place? I have already seen the code in the main branch.  BTW, pg log need guarantee sequence, why we use insert here?

**Comment by xxhdx1985126** [comment]
> @xxhdx1985126 does the patch got merged at some other place? I have already seen the code in the main branch. BTW, pg log need guarantee sequence, why we use insert here?

Ah, yes, it seems that this PR's commit has already been committed, I'll close this PR. The reason for this commit is that OP_CLONE should be in front of the corresponding OP_WRITE.

**Pull request closed without merging**
