### PR TITLE
rgw: parallel executing in block phase of reshard

### PR DESCRIPTION
**Pull request by liangmingyuanneo**
There may be high client io in logrecord phase of reshard, so we just parallelizing the second phase. 

Signed-off-by: Mingyuan Liang <liangmingyuan@baidu.com>

https://tracker.ceph.com/issues/68401

### CODE REVIEW

**Comment by liangmingyuanneo** [comment]
@cbodley This pr is Draft, that does't implement parallelism completely.
`flush()` is asynchronous, but `bi_list()` is not. So I want to use `io_context_pool` in src/common/async/context_pool.h for real multiple cpu parallel. Or use `std::async` as https://github.com/ceph/ceph/pull/56757 does. Which way do you think is better?

**Comment by liangmingyuanneo** [comment]
@cbodley  thanks for your detailed explanation, letting me know the latest progress. 

> we're starting to adopt c++20 coroutines elsewhere in rgw

So, I prefer the way https://github.com/ceph/ceph/pull/59887 does instead of stackful corutines too.

**Comment by cbodley** [comment]
> the main thing that's still missing for c++20 coroutines is the interface to read/write bucket instance metadata, including the interaction with the system object cache

we still haven't decided between stackful vs. stackless coroutines, but i'm leaning toward stackful to avoid duplicating these metadata interfaces

> if we instead decide to stick with stackful coroutines (boost::asio::spawn() and boost::asio::yield_context), we can add an overload of with_lease() for that and adjust https://github.com/ceph/ceph/pull/59887 accordingly

to that end, i built the stackful version of `with_lease()` in https://github.com/ceph/ceph/pull/60264, and adapted the async reshard writer in https://github.com/ceph/ceph/pull/60329

**Comment by cbodley** [comment]
i've opened a draft https://github.com/ceph/ceph/pull/60475 that uses with_lease() to manage the reshard locks

**Comment by mattbenjamin** [comment]
I don't think "avoiding duplicating interfaces" is a sufficient motivation for forcing stackful coroutines.  The apparently much greater scalability of stackless in other systems, for me, was the underlying motivation for coroutines in the first place.

**Comment by cbodley** [comment]
> I don't think "avoiding duplicating interfaces" is a sufficient motivation for forcing stackful coroutines. The apparently much greater scalability of stackless in other systems, for me, was the underlying motivation for coroutines in the first place.

@mattbenjamin i did a more thorough investigation to see what all needs duplicating just to read/write/delete bucket instance metadata:
```
RGWRados::get_bucket_instance_info
- RGWBucketCtl::read_bucket_instance_info
-- RGWSI_Bucket_SObj::read_bucket_instance_info
--- RGWSI_Bucket_SObj::do_read_bucket_instance_info
---- rgw_get_system_obj
----- RGWSI_SysObj::Obj::ROp::read
------ RGWSI_SysObj_Core::read
------- RGWSI_SysObj_Cache::read

RGWRados::put_bucket_instance_info
- RGWBucketCtl::store_bucket_instance_info
-- RGWSI_Bucket_SObj::store_bucket_instance_info
--- RGWSI_BucketIndex_RADOS::handle_overwrite
---- RGWSI_BILog_RADOS::log_start
---- RGWSI_BILog_RADOS::log_stop
---- RGWDataChangesLog::add_entry
--- rgw_put_system_obj
---- RGWSI_SysObj::Obj::WOp::write
----- RGWSI_SysObj_Core::write
----- RGWSI_SysObj_Cache::write
------ RGWSI_SysObj_Cache::distribute_cache
------- RGWSI_Notify::distribute
-------- RGWSI_Notify::robust_notify
---- RGWSI_SysObj::Obj::WOp::write_data
----- RGWSI_SysObj_Core::write_data
----- RGWSI_SysObj_Cache::write_data
------ RGWSI_SysObj_Cache::distribute_cache
------- RGWSI_Notify::distribute
-------- RGWSI_Notify::robust_notify
--- RGWSI_Bucket_Sync_SObj::handle_bi_update
---- RGWSI_Bucket_Sync_SObj_HintIndexManager::update_hints
----- RGWSI_BS_SObj_HintIndexObj::update
------ RGWSI_BS_SObj_HintIndexObj::read
------ RGWSI_BS_SObj_HintIndexObj::flush
--- RGWSI_MDLog::complete_entry
---- RGWSI_MDLog::add_entry
----- RGWMetadataLog::add_entry

RGWBucketCtl::remove_bucket_instance_info
- RGWSI_Bucket_SObj::remove_bucket_instance_info
-- rgw_delete_system_obj
--- RGWSI_SysObj::Obj::WOp::remove
---- RGWSI_SysObj_Core::remove
---- RGWSI_SysObj_Cache::remove
----- RGWSI_SysObj_Cache::distribute_cache
------ RGWSI_Notify::distribute
------- RGWSI_Notify::robust_notify
-- RGWSI_Bucket_Sync_SObj::handle_bi_removal
--- RGWSI_Bucket_Sync_SObj_HintIndexManager::update_hints
---- RGWSI_BS_SObj_HintIndexObj::update
----- RGWSI_BS_SObj_HintIndexObj::read
----- RGWSI_BS_SObj_HintIndexObj::flush
-- RGWSI_MDLog::complete_entry
--- RGWSI_MDLog::add_entry
---- RGWMetadataLog::add_entry
```
resharding also depends on several operations that write to every index shard using CLSRGWConcurrentIO which waits on a condition variable for completion. in https://github.com/ceph/ceph/pull/58797 i started rewriting some of those using AioThrottle for optional_yield support, but we don't have a design to do that with c++20 coroutines yet
```
RGWRados::trim_reshard_log_entries
RGWRados::bucket_set_reshard
RGWSI_BucketIndex_RADOS::init_index
RGWSI_BucketIndex_RADOS::clean_index
RGWSI_BILog_RADOS::log_start
RGWSI_BILog_RADOS::log_stop
```

**Comment by cbodley** [comment]
> i've opened a draft #60475 that uses with_lease() to manage the reshard locks

i pushed another draft https://github.com/ceph/ceph/pull/60628 that finally adds parallel processing of source shards. that depends on several other prs and needs cleanup/squashing, but it's passing qa/workunits/rgw/test_rgw_reshard.py

**Comment by cbodley** [comment]
> resharding also depends on several operations that write to every index shard using CLSRGWConcurrentIO which waits on a condition variable for completion. in #58797 i started rewriting some of those using AioThrottle for optional_yield support, but we don't have a design to do that with c++20 coroutines yet

reconsidering the use of AioThrottle, i'm exploring new concurrent read/write algorithms for this stuff in https://github.com/ceph/ceph/pull/60670. these use asio's CompletionToken concept to support calls from blocking functions and stackful/stackless coroutines. each is implemented as a stackless coroutine using [co_composed()](https://www.boost.org/doc/libs/1_85_0/doc/html/boost_asio/reference/experimental__co_composed.html)

**Pull request closed without merging**
