### PR TITLE
nautilus: tests: rados/mgr/tasks/module_selftest: whitelist mgr client getting blacklisted

### PR DESCRIPTION
**Pull request by pdvian**
https://tracker.ceph.com/issues/40944

### CODE REVIEW

**Comment by callithea** [comment]
Hi,
I included this PR in a Nautilus QA run and still got the error, not sure if anyone else can confirm this.
http://pulpito.ceph.com/laura-2019-10-11_12:53:37-rados:mgr-wip-laura-testing-nautilus-29485-29649-distro-basic-mira/

**Comment by smithfarm** [comment]
@callithea This PR doesn't address those failures. In master they were fixed by https://github.com/ceph/ceph/pull/29114

**Comment by callithea** [comment]
> @callithea This PR doesn't address those failures. In master they were fixed by #29114

Right, sorry for the noise!

**Comment by neha-ojha** [comment]
@yuriw let's merge try to test and merge this PR to eliminate one consistent failure in nautilus rados runs

**Comment by yuriw** [comment]
[wip-yuri5-testing-2019-11-07-2203-nautilus](https://trello.com/c/74sn1TLH/751-wip-yuri5-testing-2019-11-07-2203-nautilus)

**Pull request merged**
