### PR TITLE
rgw_file: fix double unref on rgw_fh for rename

### PR DESCRIPTION
**Pull request by guihecheng**
Skip unref after unlink to fix the problem.

Signed-off-by: Gui Hecheng <guihecheng@cmss.chinamobile.com>

### CODE REVIEW

**Comment by mattbenjamin** [comment]
@guihecheng I think you're right about the double unref (not double free, since we are refcounting), but I think my intent (see comment in case 1 /*!LOCKED, -ref */) in the code was that the unlink would be the last valid access to rgw_fh, so rather than omitting to unlock and unref in unlink, we should goto out or return here in rename, because we are not supposed to touch rgw_fh after unlinking it.  Can you buy that?

**Comment by guihecheng** [comment]
@mattbenjamin ok, it is reasonable that unlink should always be the one to kill an fh, thanks.

**Comment by dmick** [comment]
My fault the submodule test failed, ignore

**Comment by mattbenjamin** [comment]
@guihecheng this appears to work perfectly, combined w/Dan's version of the nfs-ganesha invalidate-for-rename change (sorry again that was lost, and thanks for root-causing and proposing a fix!)

**Comment by mattbenjamin** [comment]
verified f23

**Pull request merged**
