### PR TITLE
[DNM] mimic: osd: Remove useless conditon.

### PR DESCRIPTION
**Pull request by Ranjitha-G**
Signed-off-by: Jianpeng Ma <jianpeng.ma@intel.com>
(cherry picked from commit 8e300474fb4dc8f4448262e5974857fb6f1fd42b)

- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by Ranjitha-G** [comment]
@LenzGr Should i send this as two pull requests as they are unrelated?

**Comment by smithfarm** [comment]
@Ranjitha-G Please open a tracker ticket listing which master commits you think should be backported, to which stable releases, and why.

**Comment by smithfarm** [comment]
@Ranjitha-G Ping?

**Comment by smithfarm** [comment]
no response; closing

**Pull request closed without merging**
