### PR TITLE
mimic: core: Change osd_objectstore default to bluestore

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/37994

### CODE REVIEW

**Comment by smithfarm** [comment]
jenkins test docs

**Comment by neha-ojha** [comment]
retest this please

**Comment by yuriw** [comment]
[wip-yuri4-testing-2019-02-05-1539-mimic](https://trello.com/c/r3b0ba08/529-wip-yuri4-testing-2019-02-05-1539-mimic)

**Comment by yuriw** [comment]
test this please

**Comment by yuriw** [comment]
@smithfarm we suspect this PR caused 
7 - run-tox-ceph-disk (Failed)
and can't pass `make check`
Pls take a look and add tags back for retesting.

**Comment by neha-ojha** [comment]
This looks like a failure in `test_init_filestore_dev`, needs to be investigated.

**Comment by liewegas** [comment]
I do't think this is wroth backporting.  It's just a bunch of churn fixing tests, when in reality the osd_objectstore setting only affects things like vstart.sh and ceph-helpers.  Real systems are deployed with ceph-disk or ceph-volume, which don't use this option.

**Pull request closed without merging**
