### PR TITLE
cephfs qos: implement cephfs qos base on tokenbucket algorighm.

### PR DESCRIPTION
**Pull request by cooboos**
The basic idea is as follows:
1. Set QoS info as one of the dir's xattrs;
2. All clients that can access the same dirs with the same QoS setting.
3. Follow the Quota's config flow. when the MDS receives the QoS setting, it'll also broadcast the message to all clients.
4. We can change the limit online. 

[support]:
limit && burst config

[usage]: 
`setfattr -n ceph.qos.limit.iops -v 200 /mnt/cephfs/testdirs/`
`setfattr -n ceph.qos.burst.read_bps -v 200 /mnt/cephfs/testdirs/`
`getfattr  -n ceph.qos.limit.iops /mnt/cephfs/testdirs/`
`getfattr  -n ceph.qos /mnt/cephfs/testdirs/`

[problems]:
Because there is no queue in CephFS IO path, If the bps is lower than the request's block size, the whole Client will be blocked until it gets enough token.

Signed-off-by: Wang Songbo <wangsongbo@sensetime.com>

### CODE REVIEW

**Comment by batrick** [comment]
Please also include this PR description in the commit message itself any pertinent information you also shared in your mailing list post.

A tracker ticket would also be appropriate so we can account for this feature during release credits.

**Comment by cooboos** [comment]
@batrick Thanks for your suggestion, and the tracker URL is:https://tracker.ceph.com/issues/40986

**Comment by batrick** [comment]
Sorry for the delay reviewing this. We'll take a look in the next month as things cool down for Octopus.

**Comment by tchaikov** [comment]
@cephfs ping?

**Comment by Rethan** [comment]
Is there anyone still working on this? Wonder if there are an available and mature CephFS QOS mechanism. If we let all clients accessing the same dir have same Qos setting, what would happen if a dir have thousands of mount?

**Comment by tchaikov** [comment]
@batrick ping?

**Comment by mkuchnik** [comment]
@batrick I'm also interested in the status of QoS for CephFS. What has to be done for this PR or similar to be merged (e.g., anything that I/someone else can help with)?

**Comment by WilliamDEdwards** [comment]
Also interested in QoS for CephFS. Although the risk may be minimal in practice, it is nice to be able to assign at least some kind of resource limit on shared CephFS environments.

**Comment by chenxianpao** [comment]
Is there anyone still working on this? Is there any available and mature CephFS QOS mechanism?

**Comment by PhantomPhreak** [comment]
Also looking forward for having per-directory QoS setting to limit IO rate issued by CephFS clients

**Comment by mullumaus** [comment]
Hi

Is there any plan to get this merged? We are also looking  forward for having QoS setting to limit IO rate

**Comment by m-yosefpor** [comment]
ping /unstale

**Comment by WilliamDEdwards** [comment]
Ping.

**Comment by lumir-sliva** [comment]
Ping, can we please re-open this?

**Pull request closed without merging**
