### PR TITLE
utf8 and old gcc breakage on RHEL6.5

### PR DESCRIPTION
**Pull request by theanalyst**
http://tracker.ceph.com/issues/11716

### CODE REVIEW

**Comment by dachary** [comment]
@theanalyst retitled all issues and this pull request. My initial choice for a title was very poor to say the least. And quite confusing when applied to a backport ;-)

**Comment by dachary** [comment]
it appears this is a duplicate of #4890

**Comment by dachary** [comment]
@theanalyst @smithfarm this is an interesting case of one pull request fixing two issues. We're organized to deal with one pull request fixing exactly one issue. When it's not the case we face that kind of duplicate. I'm not sure what kind of convention we could have in place to reduce the chance of this happening ?

**Comment by theanalyst** [comment]
@dachary @smithfarm  this is a duplicate. I think when the initial PR was submitted, we didn't have a backport tracker yet... so when the issue appeared in the tracker.. it was in a new state and didn't refer to #4687 yet.. so I kind of started backporting all issues in hammer backports tracker which weren't assigned.. Closing this & updated the tracker

**Comment by smithfarm** [comment]
@dachary @theanalyst Personally, I like our "one backport per issue" policy and I think it is reasonable to expect that any deviation from it (like mine in this case) will cause confusion. The solution is simple: vigilance and atomicity. We should not create PRs that fix multiple issues, and if it happens we should break them up.

That said, there is always the possibility of multiple tracker issues being opened for a single bug.

**Comment by dachary** [comment]
@smithfarm and there also is the (rare) case when an backport does not work solo and needs to be backported along with others. But it's rare so ... let's talk again when/if we run into this a few more times :-)

**Pull request closed without merging**
