### PR TITLE
mgr/dashboard: Display the "destroyed" state in OSD list

### PR DESCRIPTION
**Pull request by tspmelo**
FireShot Capture 008 - Ceph - localhost

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`

</details>

### CODE REVIEW

**Comment by rjfd** [comment]
@tspmelo is it possible for a "destroyed" OSD to be "up" or "in"?

**Comment by tspmelo** [comment]
You need to put the OSD `down` before destroying it, but it will still stay `in`.
FireShot Capture 009 - Ceph - localhost

**Comment by rjfd** [comment]
> You need to put the OSD `down` before destroying it, but it will still stay `in`.

Then we don't need to show "down" and "destroyed" at the same time, since "destroyed" already implies "down"

**Comment by tspmelo** [comment]
@rjfd Fixed.

**Comment by tchaikov** [comment]
jenkins test make check

**Pull request merged**
