### PR TITLE
rgw: fix 2 null versionID after convert_plain_entry_to_versioned

### PR DESCRIPTION
**Pull request by RickyMaRui**
After convert plain entry to versioned, the converted entry epoch is 1.
Setting this ensures that there is only one null version.

Fixes: https://tracker.ceph.com/issues/62013

Signed-off-by: rui ma <marui1@chinatelecom.cn>
Signed-off-by: zhuo li <lizhuo@chinatelecom.cn>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by huynp1999** [comment]
Hi, I applied this patch to v16.2.13 but the issue is still there

**Comment by RickyMaRui** [comment]
> Hi, I applied this patch to v16.2.13 but the issue is still there

v16.2.13 has a different lines of code，did you modify it here
https://github.com/ceph/ceph/blob/v16.2.13/src/cls/rgw/cls_rgw.cc#L1778C29-L1779C3

**Comment by huynp1999** [comment]
> > Hi, I applied this patch to v16.2.13 but the issue is still there
> 
> v16.2.13 has a different lines of code，did you modify it here https://github.com/ceph/ceph/blob/v16.2.13/src/cls/rgw/cls_rgw.cc#L1778C29-L1779C3

Yes, that's what I do

**Comment by RickyMaRui** [comment]
> > > Hi, I applied this patch to v16.2.13 but the issue is still there
> > 
> > 
> > v16.2.13 has a different lines of code，did you modify it here https://github.com/ceph/ceph/blob/v16.2.13/src/cls/rgw/cls_rgw.cc#L1778C29-L1779C3
> 
> Yes, that's what I do

Testing this with a new bucket or object should be normal.  This patch does not fix the existing 2 null versionID object.

**Comment by RickyMaRui** [comment]
> @RickyMaRui there are some existing s3test cases like [test_versioning_obj_plain_null_version_overwrite](https://github.com/ceph/s3-tests/blob/73b340a0e2042d48753f16e0c9bc050040af27cc/s3tests_boto3/functional/test_s3.py#L7242C5-L7273) and [test_versioning_obj_plain_null_version_overwrite_suspended](https://github.com/ceph/s3-tests/blob/73b340a0e2042d48753f16e0c9bc050040af27cc/s3tests_boto3/functional/test_s3.py#L7275-L7305) that i would have expected to fail the same way. any idea why this bug only happens during lifecycle transition, but not normal overwrites?

Thank you  @cbodley   for the test case https://github.com/ceph/s3-tests/pull/524.
The trigger conditions for this bug are as follows:
1. Bucket versioning is enabled
2. An Existing object with null versionID and has not been converted to olh type (`olh_found == false`)
3. Call function `rgw_bucket_link_olh` with `op.key.instance.empty()` ( or `obj.key.instance.empty()` )

obj.set_epoch(1) makes obj.write(olh.get_epoch(), promote) unlink epoch 1 and write epoch 2, left only epoch 2 for null versionID.

Here is the code  [obj.write](https://github.com/ceph/ceph/blob/5378749ba6be3a0868b51803968ee9cde4833a3e/src/cls/rgw/cls_rgw.cc#L1365C1-L1382C4) .

[test_versioning_obj_plain_null_version_overwrite](https://github.com/ceph/s3-tests/blob/73b340a0e2042d48753f16e0c9bc050040af27cc/s3tests_boto3/functional/test_s3.py#L7242C5-L7273) does not meet condition 3.
[test_versioning_obj_plain_null_version_overwrite_suspended](https://github.com/ceph/s3-tests/blob/73b340a0e2042d48753f16e0c9bc050040af27cc/s3tests_boto3/functional/test_s3.py#L7275-L7305) does not meet condition 1.

**Comment by ivancich** [comment]
Passed QE:
* https://pulpito.ceph.com/ivancich-2023-09-06_18:12:39-rgw-wip-eric-testing-1-distro-default-smithi/
* https://pulpito.ceph.com/ivancich-2023-09-06_18:12:09-rgw-wip-eric-testing-1-distro-default-smithi/

**Pull request merged**
