### PR TITLE
nautilus: mgr/dashboard: Avoid merge conflicts in messages.xlf by auto-generating it at build time?

### PR DESCRIPTION
**Pull request by tspmelo**
http://tracker.ceph.com/issues/39658

### CODE REVIEW

**Comment by tspmelo** [comment]
This should be merged after https://github.com/ceph/ceph/pull/28062, otherwise it will cause conflicts in the PR.

**Comment by LenzGr** [comment]
retest this please

**Comment by tspmelo** [comment]
jenkins test make check

**Comment by yuriw** [comment]
[wip-yuri2-testing-2019-06-05-1524-nautilus](https://trello.com/c/fgHamZml/630-wip-yuri2-testing-2019-06-05-1524-nautilus)

**Pull request merged**
