### PR TITLE
Rgw subuser fixes

### PR DESCRIPTION
**Pull request by zhouyuan**

### CODE REVIEW

**Comment by zhouyuan** [comment]
@oritwas Can you please help to have a look on this? Thanks!

**Comment by oritwas** [comment]
For user we only fail is it is an exclusive op , see RGWUser::execute_add
I think we need to do the same for subuser

**Comment by yehudasa** [comment]
@zhouyuan why do we want to fail? wouldn't it be better to have an idempotent subuser creation?

**Comment by zhouyuan** [comment]
@yehudasa, I'm a little confused here. The behavior I saw now is:


a) create a existing subuser with 'user create' command returns error
./radosgw-admin user create --subuser=test:tester
could not create user: unable to create user, user: test exists

b) create a existing subuser with 'subuser create' command passed and some
redudant access_key generated.
./radosgw-admin subuser create --subuser=test:tester
{
    "user_id": "test",
    "display_name": "Tester-Subuser",
    "email": "",
    "suspended": 0,
    "max_buckets": 1000,
    "auid": 0,
    "subusers": [
        {
            "id": "test:tester",
            "permissions": "<none>"
        }
    ],
    "keys": [
        {
            "user": "test:tester",
            "access_key": "0FYA0CARA5YE85OJDIEU",
            "secret_key": ""
        },
        {
            "user": "test:tester",
            "access_key": "0IX56KAC41CH8ID4Q62M",
            "secret_key": ""
        },
    ],
    "swift_keys": [
        {
            "user": "test:tester",
            "secret_key": "B3pnxRBsyxTJmONWRDMTn9ZsZCyH7X8ZzxkNKIrQ"
        }
    ],
    "caps": [],
    "op_mask": "read, write, delete",
    "default_placement": "",
    "placement_tags": [],
    "bucket_quota": {
        "enabled": false,
        "max_size_kb": -1,
        "max_objects": -1
    },
    "user_quota": {
        "enabled": false,
        "max_size_kb": -1,
        "max_objects": -1
    },
    "temp_url_keys": []
}

This patch just check if the subuser exits and report our error if exists,
just the same as the 'user create' command.

'idempotent' means we should sliently skip the key generating and dump the
existing subuser also? Is my understanding right?



Sincerely, Yuan

**Comment by yehudasa** [comment]
@zhouyuan I don't want to change current behavior, as some clients might rely on this operation to not fail.

**Pull request closed without merging**
