### PR TITLE
osd/OSD.cc: use refrence instead of copying

### PR DESCRIPTION
**Pull request by stiopaa1**
Signed-off-by: Michal Jarzabek <stiopa@gmail.com>

### CODE REVIEW

**Comment by liewegas** [comment]
This is only a few bytes to copy; i doubt it'll be slower than a pointer indirection

**Comment by cbodley** [comment]
note that this is an example of the map anti-pattern `if (map.count(key)) { access map[key]; }` which does two searches. can you change that to `auto i = map.find(key); if (i != map.end()) { ...` while you're at it?

**Comment by stiopaa1** [comment]
@liewegas 
You are probably right - haven't noticed that it's so small.

@cbodley 
Yes, this was supposed to be my next commit:)

**Comment by liewegas** [comment]
@stiopaa1 ping

**Comment by stiopaa1** [comment]
@liewegas
 I've closed this.

**Pull request closed without merging**
