### PR TITLE
rgw: fixing compilation errors

### PR DESCRIPTION
**Pull request by ronen-fr**
Removing pessimizing moves and unused captures.

Signed-off-by: Ronen Friedman <rfriedma@redhat.com>

### CODE REVIEW

**Review by mattbenjamin — APPROVED** [review]
ok;

**Review by yuvalif — APPROVED** [review]

**Review by dang — APPROVED** [review]

**Review by adamemerson — APPROVED** [review]

**Comment by wjwithagen** [comment]
This sort of equals/duplicates:  #38312
Which is already waiting for 14 days to get merged.

**Comment by mattbenjamin** [comment]
> 
> 
> This sort of equals/duplicates: #38312
> Which is already waiting for 14 days to get merged.

@wjwithagen that's true, in part;  if we can get a teuthology run of the former, we could start with it

Matt

**Comment by ronen-fr** [comment]
Reviewed-by: Willem Jan Withagen (@wjwithagen)
Reviewed-by: Matt Benjamin <mbenjamin@redhat.com> 
Reviewed-by: Daniel Gryniewicz <dang@redhat.com> <dang@fprintf.net>
Reviewed-by: Adam C. Emerson <aemerson@redhat.com>
Reviewed-by: Yuval Lifshitz <ylifshit@redhat.com>

**Comment by tchaikov** [comment]
@ronen-fr the reviewed-by lines in the merge commit reads

```
Reviewed-by: Willem Jan Withagen (@wjwithagen)
Reviewed-by: Matt Benjamin mbenjamin@redhat.com
Reviewed-by: Daniel Gryniewicz dang@redhat.com dang@fprintf.net
Reviewed-by: Adam C. Emerson aemerson@redhat.com
Reviewed-by: Yuval Lifshitz ylifshit@redhat.com
```

the format of emails does not look right. and we don't use the GitHub handle for the alias of email. please see the output of `git log` for more examples.

**Pull request merged**
