### PR TITLE
jewel: disable virtual hosting of buckets when no hostnames are configured

### PR DESCRIPTION
**Pull request by Abhishekvrshny**
http://tracker.ceph.com/issues/17769

### CODE REVIEW

**Comment by dachary** [comment]
jenkins test this please (unittest_pglog failed)

**Comment by dachary** [comment]
jenkins test this please (general jenkins failure)

**Comment by dachary** [comment]
@oritwas does this backport look good to merge ? It passed the rgw suite http://tracker.ceph.com/issues/17851#note-3 . Note that it will not be in 10.2.4, reason why it targets jewel-next.

**Comment by robbat2** [comment]
This is on `ceph:jewel-next`, but when it will be merged to `ceph:jewel` for release in the 10.2.6 release?

**Comment by smithfarm** [comment]
@robbat2 The commits in this PR are in `jewel`, too. I just checked.

**Comment by robbat2** [comment]
Yes, I see in 5b402f8a7b5a763852e93cd0a5decd34572f4518 that `jewel-next` got merged to `jewel` on Dec 22nd.

**Pull request merged**
