### PR TITLE
cmake: introduce Boost::MPL interface library for increasing BOOST_MPL_LIMIT_LIST_SIZE

### PR DESCRIPTION
**Pull request by tchaikov**
## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Review by dzafman — APPROVED** [review]
I don't know enough about cmake to verify those changes.  I wish the commit message mentioned that it was setting BOOST_MPL_CFG_NO_PREPROCESSED_HEADERS and BOOST_MPL_LIMIT_LIST_SIZE=30 as the purpose of that commit.

**Review by neha-ojha — APPROVED** [review]
Thanks @tchaikov, this why I had asked for your opinion https://github.com/ceph/ceph/pull/36397#discussion_r469439889

**Comment by tchaikov** [comment]
> Thanks @tchaikov, this why I had asked for your opinion [#36397 (comment)](https://github.com/ceph/ceph/pull/36397#discussion_r469439889)

could add me as a reviewer next time. i must have missed your ping.

**Comment by tchaikov** [comment]
https://pulpito.ceph.com/kchai-2020-09-18_12:08:05-rados-wip-kefu-testing-2020-09-18-1517-distro-basic-smithi/

**Comment by tchaikov** [comment]
> I don't know enough about cmake to verify those changes. I wish the commit message mentioned that it was setting BOOST_MPL_CFG_NO_PREPROCESSED_HEADERS and BOOST_MPL_LIMIT_LIST_SIZE=30 as the purpose of that commit.

ahh, i hit the merge button too soon. do you mean i should add this in the commit message of https://github.com/ceph/ceph/pull/37224/commits/0cf2e8994868cbb94304e7226d123c32ad625e90 ? i put it in as a comment in the source code. so i thought there was no need to replicate it in the commit message.

**Comment by dzafman** [comment]
No problem the comment is sufficient.

**Pull request merged**
