### PR TITLE
test: Fix failure test to find message anywhere in stderr

### PR DESCRIPTION
**Pull request by dzafman**
Jenkins is seeing errors because of a race with experimental feature warnings and expected error output of the ceph-objectstore-tool command.  This improves the test case to find a matching message anywhere in the stderr output.

### CODE REVIEW

**Comment by dzafman** [comment]
Waiting for a good Jenkins run.  I caused the failure while DNM was set to look at the logging output of the test.

**Comment by dzafman** [comment]
@tchaikov Fixed indent issue.  Thanks

**Comment by dachary** [comment]
<pre>
Reviewed-by: Loic Dachary &lt;ldachary@redhat.com>
</pre>

**Comment by tchaikov** [comment]
weird, jenkins is happy so python was fine with the indentation...

lgtm.

**Pull request merged**
