### PR TITLE
rbd: don't default empty pool name unless namespace is specified

### PR DESCRIPTION
**Pull request by idryomov**
## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [x] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Review by chrisphoffman — APPROVED** [review]
What are your thoughts on keeping it as is and adding a -R or --recursive flag to get desired "all" output? That functionality would then be similar to "mirror snapshot schedule ls -R".

That being said, I see that the patch includes reverting back to functionality that was before regression and have no issues with that way either.

LGTM.

**Comment by idryomov** [comment]
> That being said, I see that the patch includes reverting back to functionality that was before regression and have no issues with that way either.

Breaking existing interfaces is a huge no-no, so I just resurrected the lost functionality.  It's unfortunate that pool specs implementation here is inconsistent with the implementation of level specs in mirror snapshot and trash purge schedules, but they aren't really the same at a high level either, so I think it's fine.

**Comment by idryomov** [comment]
jenkins test api

**Comment by idryomov** [comment]
Tweaked the test case to avoid separate data pools (e.g. due to `pool/ec-data-pool` facet).

**Review by trociny — APPROVED** [review]

**Comment by idryomov** [comment]
jenkins test windows

**Comment by idryomov** [comment]
No actual failures:

https://pulpito.ceph.com/dis-2022-07-17_14:22:10-rbd-wip-dis-testing-distro-default-smithi/
https://pulpito.ceph.com/dis-2022-07-17_22:13:58-rbd-wip-dis-testing-distro-default-smithi/
https://pulpito.ceph.com/dis-2022-07-18_06:38:41-rbd-wip-dis-testing-distro-default-smithi/

**Pull request merged**
