### PR TITLE
[DNM] systemd: set osd_request_timeout in rbdmap.service stopping

### PR DESCRIPTION
**Pull request by yangdongsheng**
Signed-off-by: Dongsheng Yang <dongsheng.yang@easystack.cn>

### CODE REVIEW

**Comment by yangdongsheng** [comment]
@idryomov  I sent a patch in ceph-devel: "[PATCH] ceph: make osd_request_timeout changable online in debugfs". This PR is an example to use that feature. Let's wait for the feature discussed in ceph-devel.

**Comment by yangdongsheng** [comment]
Yes, but before the unmapping with --force or even --full-force in future, we need to do a fs umounting, this would be blocked, if osd_request_timeout is 0 and the ceph cluster is not working well. And the umounting process would be in D state.

**Comment by idryomov** [comment]
@yangdongsheng You wouldn't need to umount _before_ unmapping with `-o full-force`, because rbd would ignore the fact that the device is open by the filesystem and proceed to fail all outstanding requests and tear itself down.  You would umount _after_ `rbd unmap` returns -- at least that's how I imagine it working.

**Comment by yangdongsheng** [comment]
Okey let‘s wait for the full-force. Thanx guys.’

**Pull request closed without merging**
