### PR TITLE
mgr/dashboard: extend doc by Grafana setting

### PR DESCRIPTION
**Pull request by p-se**
Signed-off-by: Patrick Seidensal <pseidensal@suse.com>

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by bk201** [comment]
Seems rendered as a quoted block on Github (Not sure if this is intended):
preview

I add one more space to the changed lines (previous lines are indented with 3 spaces) and the block is indented correctly. Please see https://github.com/bk201/ceph/commit/fcb766aed430fd0dde3b740ea7aebda037a55b64

**Comment by p-se** [comment]
jenkins render docs

**Comment by zdover23** [comment]
I have some commits that I've made locally to explain how this kind of formatting works since we started using the bash lexer. I'll make a pull request in the next couple of days to get this formatting somewhere into the documentation, because it was a terribly frustrating day-long trial-and-error-process of learning exactly these indentation-related formatting matters.

**Comment by p-se** [comment]
Thanks for checking! The docs render correctly when built with `admin/build-doc` and also using `jenkins render docs`. I've seen indentations in the `dashboard.rst` that aren't two space wide (three to four or even more spaces), but considered this to be a mistake (I wanted to fix but haven't). Because I think more than two spaces indentation is a mistake (and because it works how it's supposed to work with two, except for GitHub's rendering), I'd rather fix all other places than convert this addition to three spaces. This change would result in a document with unified indentations and I can imagine that GitHub will also be able to render them correctly.

**Comment by p-se** [comment]
Apparently, there's more to this than I thought. I'm looking forward to your explanation or examples @zdover23.

**Comment by zdover23** [comment]
@p-se : My notes don't yet constitute an exact science, which is why I won't make a PR just yet. I'd say that I'm still in the phlogiston-is-always-associated-with-combustion phase of the hypothesizing about Sphinx's lexer behavior. What I feel confident asserting already, though, is that this is badly documented and consequently extremely, extremely frustrating.

**Comment by p-se** [comment]
jenkins test docs

**Comment by p-se** [comment]
Considering the requirement to have the docs rendered correctly on https://docs.ceph.com/docs/master/mgr/dashboard/ (Sphinx) and my lack of time to investigate the differences between Sphinx's and Github's ReStructuredText implementation, I propose to continue with merging this PR, as the docs will render correctly for Sphinx. Leaving the possible enhancement to fit both flavors for a different PR.

**Comment by zdover23** [comment]
jenkins make check

**Comment by s0nea** [comment]
jenkins test docs

**Comment by s0nea** [comment]
I'm not sure if 
```
/home/jenkins-build/build/workspace/ceph-pr-docs/doc/mgr/dashboard.rst:366: WARNING: Literal block expected; none found.
```
is an actual issue? Saw it on the 'Docs: build check' output.

**Comment by LenzGr** [comment]
jenkins test docs

**Comment by LenzGr** [comment]
jenkins render docs

**Comment by LenzGr** [comment]
I can't merge this PR until the following issue has been fixed:
```
/home/jenkins-build/build/workspace/ceph-pr-docs/doc/mgr/dashboard.rst:366: WARNING: Literal block expected; none found.
```

**Comment by LenzGr** [comment]
jenkins render docs

**Comment by callithea** [comment]
jenkins test dashboard

**Pull request merged**
