### PR TITLE
osd: Remove override for osd_async_recovery_min_cost for mclock profiles

### PR DESCRIPTION
**Pull request by sseshasa**
Overriding osd_async_recovery_min_cost as part of enabling a built-in
mclock profile has the undesirable side effect of peers not choosing
the correct async recovery targets if osds are using mixed schedulers
(this could happen during upgrades or if "debug_random" is set for
osd_op_queue config option). Due to the above, osds get into a
"choose_acting" loop during peering.

The solution is to remove the override of osd_async_recovery_min_cost.

Fixes: https://tracker.ceph.com/issues/48906
Signed-off-by: Sridhar Seshasayee <sseshasa@redhat.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by sseshasa** [comment]
jenkins test api

**Review by sunnyku — COMMENTED** [review]
`osd_async_recovery_min_cost` can be removed form tracked keys`KEYS[ ]`.

**Review by sunnyku — APPROVED** [review]

**Comment by sseshasa** [comment]
> `osd_async_recovery_min_cost` can be removed form tracked keys`KEYS[ ]`.

Done.

**Review by jdurgin — APPROVED** [review]

**Review by neha-ojha — APPROVED** [review]
this is good for now

**Comment by sseshasa** [comment]
Pulpito run:
https://pulpito.ceph.com/sseshasa-2021-01-18_19:18:25-rados-wip-sseshasa-testing-2021-01-18-2145-distro-basic-smithi/

**Comment by neha-ojha** [comment]
https://pulpito.ceph.com/sseshasa-2021-01-20_16:00:06-rados-wip-sseshasa-testing-2021-01-18-2145-distro-basic-smithi/ - no failures

**Pull request merged**
