### PR TITLE
Pacific: mds: add read/write io size metrics support

### PR DESCRIPTION
**Pull request by lxbsz**
backport tracker: https://tracker.ceph.com/issues/53121

---

backport of #40514
parent tracker: https://tracker.ceph.com/issues/49811

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Review by vshankar — APPROVED** [review]

**Comment by vshankar** [comment]
@lxbsz please check https://tracker.ceph.com/issues/53314

**Comment by lxbsz** [comment]
> @lxbsz please check https://tracker.ceph.com/issues/53314

Yeah, already working on it.

**Comment by lxbsz** [comment]
@patrick Have switched to use the fuse client instead to fix this.

The root cause is that in `pacific` stable code, the commit is 3cbe25cde3cfa028984618ad32de9edc4c1eaed0:

```
2021-11-17T15:35:10.205379+00:00 smithi059 conmon[33049]: mds.0) 1 : cluster [DBG] reconnect by client.24307 v1:172.21.15.59:0/1262207260 after 0.0209997
2021-11-17T15:35:10.301751+00:00 smithi059 conmon[80899]: /home/jenkins-build/build/workspace/ceph-build/ARCH/x86_64/AVAILABLE_ARCH/x86_64/AVAILABLE_DIST/centos8/DIST/centos8/MACHINE_SIZE/gigantic/release/16.2.4/rpm/el8/BUILD/ceph-16.2.4/src/include/cephfs/metrics/Types.h: In function 'std::ostream& operator<<(std::ostream&, const ClientMetricType&)' thread 7f11d4d57700 time 2021-11-17T15:35:10.300697+0000
2021-11-17T15:35:10.302010+00:00 smithi059 conmon[80899]: /home/jenkins-build/build/workspace/ceph-build/ARCH/x86_64/AVAILABLE_ARCH/x86_64/AVAILABLE_DIST/centos8/DIST/centos8/MACHINE_SIZE/gigantic/release/16.2.4/rpm/el8/BUILD/ceph-16.2.4/src/include/cephfs/metrics/Types.h: 56: ceph_abort_msg("abort() called")
2021-11-17T15:35:10.302060+00:00 smithi059 conmon[80899]: ceph version 16.2.4 (3cbe25cde3cfa028984618ad32de9edc4c1eaed0) pacific (stable)
2021-11-17T15:35:10.302098+00:00 smithi059 conmon[80899]: 1: (ceph::__ceph_abort(char const*, int, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)+0xe5) [0x7f11dd9b8cdc]
2021-11-17T15:35:10.302136+00:00 smithi059 conmon[80899]: 2: (operator<<(std::ostream&, ClientMetricType const&)+0x10e) [0x7f11ddc3d42e]
2021-11-17T15:35:10.302178+00:00 smithi059 conmon[80899]: 3: (MClientMetrics::print(std::ostream&) const+0x1a1) [0x7f11ddc3d601]
2021-11-17T15:35:10.302216+00:00 smithi059 conmon[80899]: 4: (DispatchQueue::pre_dispatch(boost::intrusive_ptr<Message> const&)+0x710) [0x7f11ddbf0c30]
2021-11-17T15:35:10.302253+00:00 smithi059 conmon[80899]: 5: (DispatchQueue::entry()+0xdeb) [0x7f11ddbf269b]
2021-11-17T15:35:10.302289+00:00 smithi059 conmon[80899]: 6: (DispatchQueue::DispatchThread::entry()+0x11) [0x7f11ddca2b71]
2021-11-17T15:35:10.302325+00:00 smithi059 conmon[80899]: 7: /lib64/libpthread.so.0(+0x814a) [0x7f11dc75a14a]
2021-11-17T15:35:10.302377+00:00 smithi059 conmon[80899]: 8: clone()
```

When it see any unknow metric type it will just abort the MDS, which has been fixed already in pacific, but the pacific base code won't contain it:

```
 29 inline std::ostream &operator<<(std::ostream &os, const ClientMetricType &type) {
 30   switch(type) {
 31   case ClientMetricType::CLIENT_METRIC_TYPE_CAP_INFO:
 32     os << "CAP_INFO";
 33     break;
 34   case ClientMetricType::CLIENT_METRIC_TYPE_READ_LATENCY:
 35     os << "READ_LATENCY";
 36     break;
 37   case ClientMetricType::CLIENT_METRIC_TYPE_WRITE_LATENCY:
 38     os << "WRITE_LATENCY";
 39     break;
 40   case ClientMetricType::CLIENT_METRIC_TYPE_METADATA_LATENCY:
 41     os << "METADATA_LATENCY";
 42     break;
 43   case ClientMetricType::CLIENT_METRIC_TYPE_DENTRY_LEASE:
 44     os << "DENTRY_LEASE";
 45     break;
 46   case ClientMetricType::CLIENT_METRIC_TYPE_OPENED_FILES:
 47     os << "OPENED_FILES";      
 48     break;
 49   case ClientMetricType::CLIENT_METRIC_TYPE_PINNED_ICAPS:
 50     os << "PINNED_ICAPS";
 51     break;
 52   case ClientMetricType::CLIENT_METRIC_TYPE_OPENED_INODES:
 53     os << "OPENED_INODES";
 54     break;
 55   default:
 56     ceph_abort();                                                                                                                                  
 57   }
 58    
 59   return os;
 60 }  

```

And currently the kernel client testing branch has already support the read/write metrics, so if we use the kclient to test the upgrade we will always hit the crash just like this.

**Comment by lxbsz** [comment]
Depend on https://github.com/ceph/ceph/pull/44034.

**Comment by yuriw** [comment]
See comment by @kotreshhr `it's found out that the PR 43784 is not the culprit for the tracker https://tracker.ceph.com/issues/53314 . That can be merged. It's been approved, could you please merge it ?`

**Pull request merged**
