### PR TITLE
debian/control: added missing Python dependeny in manager

### PR DESCRIPTION
**Pull request by jmolmo**
This is the Ubuntu equivalent for:
https://github.com/ceph/ceph/pull/26144

Fixes: https://tracker.ceph.com/issues/37584
Signed-off-by: Juan Miguel Olmo Martínez <jolmomar@redhat.com>

### CODE REVIEW

**Comment by sebastian-philipp** [comment]
According to @tserong 's answer in the ticket, you need to add that to `Build-Depeds` in `ceph/debian/control:10` instead

**Comment by jmolmo** [comment]
> Looks like the change is in the right place, but might need to be `python3-requests` if we're going with python3 only in future (see #25969)

@tserong: in  #25969, it seems that other python packages with versions for Python 2 and 3, are no modified. 
@alfredodeza , can you explain that?

**Comment by alfredodeza** [comment]
Go ahead with non-python3 libraries, we can update the pending PR once Nautilus is released

**Comment by tchaikov** [comment]
superseded by #26402 and #26617

**Pull request closed without merging**
