### PR TITLE
octopus: cephadm: batch backport March

### PR DESCRIPTION
**Pull request by sebastian-philipp**
Backport of #34062, #34061, #34248, #34295, #34250, #34206, #34361, #34330, #34367, #34384, #34296, #34385, #34374

### CODE REVIEW

**Comment by smithfarm** [comment]
"make check" failure happened in `run-tox-mgr` because it failed to `import rados`

**Comment by sebastian-philipp** [comment]
> "make check" failure happened in `run-tox-mgr` because it failed to `import rados`

sigh. looks like I need to backport @jan--f 's commit as well.

**Comment by smithfarm** [comment]
What about https://github.com/ceph/ceph/pull/33954 ? Is that one being cherry-picked via some other PR?

**Comment by sebastian-philipp** [comment]
QA Passed. 

* http://pulpito.ceph.com/swagner-2020-04-09_21:46:02-rados-wip-swagner2-testing-2020-04-09-1541-distro-basic-smithi/

Failue is tracked at https://tracker.ceph.com/issues/44715

**Pull request merged**
