### PR TITLE
doc/mgr/dashboard: fix TLS typo

### PR DESCRIPTION
**Pull request by mcpreston**
Change "SSL/TSL" to "SSL/TLS"

Signed-off-by: Mindy Preston <mcpreston@icecube.wisc.edu>

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [x] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [x] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

### CODE REVIEW

**Review by zdover23 — APPROVED** [review]

**Review by anthonyeleven — APPROVED** [review]

**Review by nizamial09 — APPROVED** [review]

**Comment by mcpreston** [comment]
I would appreciate another look at this. I'm guessing "Pull Request Checklist" is failing because I filled out the checklist incorrectly from the start :grimacing:

**Comment by anthonyeleven** [comment]
Easy to do - looks like Zac took care of that.  Thanks for contributing!

**Comment by zdover23** [comment]
https://github.com/ceph/ceph/pull/59031 - Squid backport
https://github.com/ceph/ceph/pull/59032 - Reef backport
https://github.com/ceph/ceph/pull/59033 - Quincy backport

**Comment by zdover23** [comment]
@mcpreston, If only the checklist check was failing, then it could have been merged anyway. The only reason this wasn't merged sooner is that it just fell through the cracks while I was working on other stuff. Sorry about that, and thanks for contributing!

**Pull request merged**
