### PR TITLE
rgw: RGWRadosGetOmapKeysCR takes shared_ptr to map

### PR DESCRIPTION
**Pull request by cbodley**
parent coroutines that spawn RGWRadosGetOmapKeysCR as a child can't
guarantee that they will outlive the child coroutine, so it's not safe
for them to pass in pointers to member variables. use a shared_ptr to
extend the lifetime of this shared data

Fixes: http://tracker.ceph.com/issues/21154

### CODE REVIEW

**Comment by yuriw** [comment]
[wip-yuri4-testing-2017-11-17-1645](https://trello.com/c/covJSIzf/204-wip-yuri4-testing-2017-11-17-1645)

**Comment by cbodley** [comment]
teuthology run showing the same valgrind issues: http://qa-proxy.ceph.com/teuthology/yuriw-2017-11-17_22:01:38-rgw-wip-yuri4-testing-2017-11-17-1645-distro-basic-smithi/1858516/remote/smithi130/log/valgrind/c1.client.1.log.gz

**Comment by yuriw** [comment]
needs retesting untagged

**Comment by yehudasa** [comment]
@cbodley lgtm, but where do we stand with this one?

**Comment by cbodley** [comment]
@yehudasa this doesn't fix the valgrind issue, so i'm still investigating. i'll include any further changes in this pr

**Pull request closed without merging**
