### PR TITLE
hammer: rpm package building fails if the build machine has lttng and babeltrace development packages installed locally

### PR DESCRIPTION
**Pull request by dachary**
http://tracker.ceph.com/issues/15382

### CODE REVIEW

**Comment by dachary** [comment]
Comparing the diffs after conflict resolution shows something strange:
<pre>
$ commit=77a4ed0 ; picked_from=$(git show --no-patch --pretty=%b $commit  | perl -ne 'print if(s/.*cherry picked from commit (\w+).*/$1/)') ; diff -u --ignore-matching-lines '^[^+-]'   <(git show $picked_from) <(git show $commit)
--- /dev/fd/63	2016-04-05 12:01:09.705058342 +0200
+++ /dev/fd/62	2016-04-05 12:01:09.709058309 +0200
@@ -30,12 +35,13 @@
 +%if 0%{?fedora} || 0%{?rhel} >= 6 || 0%{?suse_version} == 1315
 +%bcond_without lttng
 +%endif
- 
++
  %if (0%{?el5} || (0%{?rhel_version} >= 500 && 0%{?rhel_version} <= 600))
  %{!?python_sitelib: %global python_sitelib %(%{__python} -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())")}
-@@ -62,11 +66,6 @@ restorecon -R /var/log/radosgw > /dev/null 2>&1;
- %{!?tmpfiles_create: %global tmpfiles_create systemd-tmpfiles --create}
- %endif
+ %{!?python_sitearch: %global python_sitearch %(%{__python} -c "from distutils.sysconfig import get_python_lib; print(get_python_lib(1))")}
+@@ -8,11 +13,6 @@
+ 
+ %{!?_udevrulesdir: %global _udevrulesdir /lib/udev/rules.d}
  
 -# LTTng-UST enabled on Fedora, RHEL 6, and SLES 12
 -%if 0%{?fedora} || 0%{?rhel} == 6 || 0%{?suse_version} == 1315
</pre>
I believe this is because moving the
<pre>
# LTTng-UST enabled on Fedora, RHEL 6+, and SLES 12
</pre>
block up in the ceph.spec.in file confuses diff into thinking the **distutil.sysconfig** lines also changed although they did not.

**Comment by dachary** [comment]
@tchaikov how does that look ?

**Comment by tchaikov** [comment]
@dachary lgtm.

**Comment by dachary** [comment]
For the record: http://tracker.ceph.com/issues/15383

**Comment by dachary** [comment]
Passed an upgrade suite in addition to the gitbuilders http://tracker.ceph.com/issues/14692#note-52

**Pull request merged**
