### PR TITLE
common: Remove the clock skew

### PR DESCRIPTION
**Pull request by adamemerson**

### CODE REVIEW

**Comment by tchaikov** [comment]
why did we introduce `clock_offset`? i am wondering...

**Comment by liewegas** [comment]
for tests like this... but it's not really necessary or worth it.

**Comment by liewegas** [comment]
Sorry, tests like this: https://github.com/ceph/ceph-qa-suite/pull/1257

**Comment by tchaikov** [comment]
```
/srv/autobuild-ceph/gitbuilder.git/build/out~/ceph-11.0.2-1609-g4ba5713/src/mds/Mutation.cc: In member function ‘virtual void MDRequestImpl::dump(ceph::Formatter*) const’:
error: /srv/autobuild-ceph/gitbuilder.git/build/out~/ceph-11.0.2-1609-g4ba5713/src/mds/Mutation.cc:318:38: too many arguments to function ‘utime_t ceph_clock_now()’
_dump(ceph_clock_now(g_ceph_context), f);
^
In file included from /srv/autobuild-ceph/gitbuilder.git/build/out~/ceph-11.0.2-1609-g4ba5713/src/common/dout.h:22:0,
from /srv/autobuild-ceph/gitbuilder.git/build/out~/ceph-11.0.2-1609-g4ba5713/src/include/Context.h:19,
from /srv/autobuild-ceph/gitbuilder.git/build/out~/ceph-11.0.2-1609-g4ba5713/src/mds/MDSCacheObject.h:14,
from /srv/autobuild-ceph/gitbuilder.git/build/out~/ceph-11.0.2-1609-g4ba5713/src/mds/Mutation.h:22,
from /srv/autobuild-ceph/gitbuilder.git/build/out~/ceph-11.0.2-1609-g4ba5713/src/mds/Mutation.cc:15:
/srv/autobuild-ceph/gitbuilder.git/build/out~/ceph-11.0.2-1609-g4ba5713/src/common/Clock.h:22:16: note: declared here
extern utime_t ceph_clock_now();
^
```

see http://gitbuilder.sepia.ceph.com/gitbuilder-ceph-deb-trusty-amd64-basic/log.cgi?log=4ba57138c3f556922ab6ded55c49c253acad5746

**Comment by dachary** [comment]
jenkins test this please (eio now ignored in master)

**Comment by adamemerson** [comment]
I'll happily make the change. Is there some flag to pass to
cmake to provoke this error?

**Comment by adamemerson** [comment]
@tchaikov It seems to pass gitbuilder now

**Comment by tchaikov** [comment]
@adamemerson ceph-mds is compiled by default, you could just try "make mds".

**Comment by tchaikov** [comment]
http://pulpito.ceph.com/kchai-2016-11-22_09:44:32-rados-wip-kefu-testing---basic-mira/

**Pull request closed without merging**
