### PR TITLE
mimic: rgw: rgw_file: use correct secret key to check auth

### PR DESCRIPTION
**Pull request by pdvian**
http://tracker.ceph.com/issues/38502

### CODE REVIEW

**Comment by smithfarm** [comment]
`155/156 Test #122: mgr-dashboard-frontend-unittests ........***Failed`

Looks unrelated

**Comment by smithfarm** [comment]
jenkins re-test this please

**Comment by smithfarm** [comment]
`155/156 Test #122: mgr-dashboard-frontend-unittests ........***Failed`

Again.

**Comment by smithfarm** [comment]
@callithea Looks like the mgr/dashboard "make check" is somewhat broken on the tip of mimic :-(

**Comment by callithea** [comment]
> @callithea Looks like the mgr/dashboard "make check" is somewhat broken on the tip of mimic :-(

@smithfarm was the previous error the same?
Created https://tracker.ceph.com/issues/38602

**Comment by smithfarm** [comment]
@callithea Apparently not. The other error is tracked by http://tracker.ceph.com/issues/38590.

**Comment by smithfarm** [comment]
jenkins test make check

**Comment by yuriw** [comment]
[wip-yuri2-testing-2019-03-14-1925-mimic](https://trello.com/c/JBX44C5H/559-wip-yuri2-testing-2019-03-14-1925-mimic)

**Pull request merged**
