### PR TITLE
rgw: add optional_yield to http client interface

### PR DESCRIPTION
**Pull request by cbodley**
enables blocking http client interfaces to instead suspend/resume the coroutine when used with the beast frontend. all external callers pass null_yield, so existing behavior is unchanged

### CODE REVIEW

**Comment by cbodley** [comment]
http://pulpito.ceph.com/cbodley-2018-12-11_14:43:34-rgw-wip-cbodley-testing-distro-basic-smithi/

**Comment by theanalyst** [comment]
unstale this, friendly robot

**Comment by cbodley** [comment]
rebased

**Comment by cbodley** [comment]
http://pulpito.ceph.com/cbodley-2019-03-29_19:48:48-rgw-wip-cbodley-testing-distro-basic-smithi/

lots of ceph-mon valgrind issues from http://tracker.ceph.com/issues/38827, otherwise clean

**Pull request merged**
