### PR TITLE
pacific: qa: test_ls_H_prints_human_readable_file_size failure

### PR DESCRIPTION
**Pull request by batrick**
https://tracker.ceph.com/issues/51499

### CODE REVIEW

**Comment by batrick** [comment]
/ceph/teuthology-archive/yuriw-2021-07-08_23:33:26-fs-wip-yuri2-testing-2021-07-08-1142-pacific-distro-basic-smithi/6260232/teuthology.log

**Comment by batrick** [comment]
New fix in latest commit -- needs rerun through qa.

**Comment by joscollin** [comment]
jenkins test make check

**Review by joscollin — COMMENTED** [review]
Looks good, but `make check` failed.
I think `./tasks/cephfs/cephfs_test_case.py:7:1: F401 'io.StringIO' imported but unused`

**Comment by batrick** [comment]
> Looks good, but `make check` failed.
> I think `./tasks/cephfs/cephfs_test_case.py:7:1: F401 'io.StringIO' imported but unused`

Thanks, fix pushed.

**Comment by joscollin** [comment]
> /ceph/teuthology-archive/yuriw-2021-07-08_23:33:26-fs-wip-yuri2-testing-2021-07-08-1142-pacific-distro-basic-smithi/6260232/teuthology.log

Created a tracker for this error too: https://tracker.ceph.com/issues/51704. Please amend the commit.

**Comment by batrick** [comment]
> > /ceph/teuthology-archive/yuriw-2021-07-08_23:33:26-fs-wip-yuri2-testing-2021-07-08-1142-pacific-distro-basic-smithi/6260232/teuthology.log
> 
> Created a tracker for this error too: https://tracker.ceph.com/issues/51704. Please amend the commit.

Done.

**Review by joscollin — APPROVED** [review]

**Pull request merged**
