### PR TITLE
common:  intrusive_lru destructor add

### PR DESCRIPTION
**Pull request by alimaredia**
Values allocated during inserts that are
unreferenced are sometimes not freed because evict()
does not delete values unless set.size() > lru_target_size.

For example, this condition is not met if the number
of entries in the intrusive_lru are less than or
equal to lru_target_size at the time of the
intrusive_lru's destruction.

Memory leaks due to the above scenario can be
reproduced if this commit is removed and
unittest_intrusive_lru is run under valgrind.

ex:

valgrind --tool=memcheck --leak-check=yes ./bin/unittest_intrusive_lru

Fixes: https://tracker.ceph.com/issues/57573

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by alimaredia** [comment]
A quick reproducer for memory-leak caused by a lack of a desctructor is from this stripped down unit test seen here:
https://paste.sh/BBUK3sR5#_ZG1-8rLPGKFBCh4c55AbRiA

**Comment by kamoltat** [comment]
Please reference a commit or add tracker

**Review by cbodley — COMMENTED** [review]
looks correct to me, but would appreciate Radek's eyes on it

we use this lru for multisite in rgw_bucket_sync_cache.h, but haven't been able to enable valgrind against multisite so didn't notice leaks here

**Review by rzarzynski — APPROVED** [review]

**Comment by cbodley** [comment]
@rzarzynski i scheduled this against the rgw suite. if you'd like to schedule some crimson tests, feel free to use my builds from https://shaman.ceph.com/builds/ceph/wip-cbodley-testing/

**Comment by cbodley** [comment]
passed rgw qa in https://pulpito.ceph.com/cbodley-2022-09-30_16:47:21-rgw-wip-cbodley-testing-distro-default-smithi/

**Comment by cbodley** [comment]
@rzarzynski is this ok to merge?

**Pull request merged**
