### PR TITLE
erasure code: fix shec's recovery issues found in teuthology test

### PR DESCRIPTION
**Pull request by t-miyamae**
Fixed shec's recovery issues found in Teuthology test after moving content of obsolete
shec.cc into ErasureCodeShec.cc.
Added TestErasureCodeShec_arguments.cc and it verifies shec's fixed logic to pass
Teuthology test.
We have tested following items.
  (1) compile error / warning
  (2) gtest
  (3) erasure code corpus
  (4) teuthology (ops=400)

### CODE REVIEW

**Comment by t-miyamae** [comment]
@dachary I thought 9021226 and 9c0c8c0 should not be included in this pull request, but I don't know how to handle it. May I simply remove these commits from our branch?

**Comment by dachary** [comment]
You can
<pre>
git reset --hard ceph/master
git cherry-pick 561047d 07825e2 bc7060f
git push --force 
</pre>

**Comment by t-miyamae** [comment]
@dachary Thanks! It seemed to be a nice way!

**Comment by t-miyamae** [comment]
@dachary As you may know, one of our important goals is RHCS 1.3. If so, do we have to hurry? (We know you are quite busy now, so please keep up your pace.)

**Comment by dachary** [comment]
@t-miyamae I'm currently at the red hat summit all week, thanks for your patience :-)

**Comment by dachary** [comment]
@t-miyamae could you please open a pull request in https://github.com/ceph/ceph-qa-suite with the tests for shec ? I will run them against this branch for verification. Other than that it looks good :-)

**Comment by dachary** [comment]
building wip-mshec-fixlogic2 in http://ceph.com/gitbuilder.cgi to be able to run teuthology suites

**Comment by t-miyamae** [comment]
@dachary We have submitted a pull request for shec's ceph-qa-suite (https://github.com/ceph/ceph-qa-suite/pull/476). Thanks in advance!

**Comment by dachary** [comment]
<pre>
./virtualenv/bin/teuthology-suite --suite rados/thrash-erasure-code-shec --suite-branch t-miyamae-wip-10886 --distro ubuntu --email loic@dachary.org --ceph wip-mshec-fixlogic2 --machine-type plana,burnupi,mira
</pre>

running at http://pulpito.ceph.com/loic-2015-07-03_18:19:13-rados:thrash-erasure-code-shec-wip-mshec-fixlogic2---basic-multi/

**Comment by dachary** [comment]
The test passed (one of them did not because there was not enough machines to run it). @t-miyamae would you be so kind as to re-base and repush so it can be merged ? A minor change in the ErasureCode API has been merged recently, hence the conflict. Nothing that should have any impact on your work.

**Comment by t-miyamae** [comment]
@dachary We have rebased the commits. Could you check it out?

**Pull request merged**
