### PR TITLE
mon: give AUTH_NONE clients a Monmap when allowed

### PR DESCRIPTION
**Pull request by gregsfortytwo**
This is a minimal fix that continues a messy interface, but we expect it
to go away with msgrv2.

### CODE REVIEW

**Comment by liewegas** [comment]
Weird, I thought I fixed this with https://github.com/ceph/ceph/pull/24202 .. at least it fixed it for @markhpc.

**Comment by liewegas** [comment]
FWIW my preference is probably the first patch just because it's a more minimal change, and with msgr2 we likely won't be using this code.

**Comment by dillaman** [comment]
> Weird, I thought I fixed this with #24202 .. at least it fixed it for @markhpc.

When using a master-branch cluster and master-branch clients, I don't have any issue. The problem is backwards compatibility w/ a master-branch cluster and older clients.

**Comment by gregsfortytwo** [comment]
Okay, I've stripped it down to just that one patch. Should be good to go!
(I also pushed the old version of this branch to my github https://github.com/gregsfortytwo/ceph/tree/wip-36300-defined-interface)

**Comment by D1294906482** [comment]
> Okay, I've stripped it down to just that one patch. Should be good to go! (I also pushed the old version of this branch to my github https://github.com/gregsfortytwo/ceph/tree/wip-36300-defined-interface)

hello, @gregsfortytwo. I have met an issue similar to BUG #56487. It seems that during OSD initialization, the update_crush_device_class function is executed before handling the monmap in AUTH_NONE.

I found a difference between AUTH_CEPHX and AUTH_NONE:
AUTH_CEPHX :                                             AUTH_NONE :
osd --------- mon                                           osd --------- mon
auth ------->                                                  auth ------->
        <------- auth_reply                                         <------- auth_reply
auth ------->                                                           <------- monmap
        <------- auth_reply
        <------- monmap
auth ------->
        <------- auth_reply

In AUTH_CEPHX, the handshake occurs three times, allowing the monmap to be handled during the handshake process. However, in AUTH_NONE, the handshake occurs only once. If the monmap cannot be handled for some reason before update_crush_device_class, it can lead to the "fisd == 0" issue.

I have an idea to deal with this problem by changing the order in prep_auth function (AuthMonitor.cc)

AUTH_CEPHX :                                             AUTH_NONE :
osd --------- mon                                           osd --------- mon
auth ------->                                                  auth ------->
        <------- auth_reply                                         <------- monmap
auth ------->                                                           <------- auth_reply
        <------- monmap
        <------- auth_reply
auth ------->
        <------- auth_reply

By handling the monmap before the auth_reply, we ensure that the monmap is processed properly. Could you please review this idea and let me know your thoughts?

change likes:

 (AuthMonitor.cc)
prep_auth:
...
if (finished) {
          // always send the latest monmap.
          if (m->monmap_epoch < mon->monmap->get_epoch())
              mon->send_latest_monmap(m->get_connection().get());

          mon->configmon()->check_sub(s);
      }
reply = new MAuthReply(proto, &response_bl, ret, s->con->peer_global_id);
             mon->send_reply(op, reply);
...

I look forward to your reply!  Best wishes to you!

**Pull request merged**
