### PR TITLE
mgr/dashboard_v2: add mgr to the list of perf counters

### PR DESCRIPTION
**Pull request by tspmelo**
Opening the perf counter page for a mgr service was throwing a 404.

### CODE REVIEW

**Comment by tspmelo** [comment]
jenkins retest this please

**Comment by sebastian-philipp** [comment]
Two things:
1. 
screenshot_20180308_130738
Looks like the mgr no longer has a hostname ?!
2. I don't have any performance data for my mgr. Do you get data for your mgr?

**Comment by sebastian-philipp** [comment]
Regarding the hostname: just created http://tracker.ceph.com/issues/23286

**Comment by tspmelo** [comment]
@rjfd, added a test for the request of mgr perf counters.

**Comment by rjfd** [comment]
QA tests look good:
http://pulpito.ceph.com/rdias-2018-03-13_16:52:27-rados:mgr-wip-rdias-testing-distro-basic-mira/

**Pull request merged**
