### PR TITLE
mimic: mgr/restful: fix py got exception when get osd info

### PR DESCRIPTION
**Pull request by b-ranto**
http://tracker.ceph.com/issues/38183

### CODE REVIEW

**Comment by smithfarm** [comment]
jenkins re-test this please

**Comment by smithfarm** [comment]
jenkins test docs

**Comment by smithfarm** [comment]
jenkins test docs

**Comment by yuriw** [comment]
[wip-yuri-testing-2019-02-12-2211-mimic](https://trello.com/c/nM3nbQT5/536-wip-yuri-testing-2019-02-12-2211-mimic)

**Comment by tchaikov** [comment]
needs #26421 also

**Comment by b-ranto** [comment]
The #26421 was merged to master and back-ported, returning the old labels (all but wip-yuri-testing, that might need an update).

**Comment by yuriw** [comment]
[wip-yuri-testing-2019-02-18-1714-mimic](https://trello.com/c/vJf3xQOH/539-wip-yuri-testing-2019-02-18-1714-mimic)

**Comment by yuriw** [comment]
[wip-yuri-testing-2019-02-20-1755-mimic](https://trello.com/c/G3p1tb0I/543-wip-yuri-testing-2019-02-20-1755-mimic)

**Pull request merged**
