### PR TITLE
tests: reduce make check verbosity

### PR DESCRIPTION
**Pull request by dachary**
Move check-local scripts

   src/test/run-cli-tests
   encode-decode-non-regression.sh
   test/encoding/readable.sh

to check_SCRIPTS. Their output is captured in .log file when running
with a recent automake. This reduces the output of make check by an
order of magnitude.

Signed-off-by: Loic Dachary <ldachary@redhat.com>

### CODE REVIEW

**Comment by dachary** [comment]
It's nice to see ~150KB output instead of ~700KB :-)

**Comment by dachary** [comment]
scheduling the gitbuilders, just to be extra sure

**Comment by tchaikov** [comment]
the gitbuilder chokes on something unrelated:

- http://gitbuilder.sepia.ceph.com/gitbuilder-ceph-tarball-precise-amd64-basic/log.cgi?log=6170eb5c67740c22242d640cb3f17281b9996137
```
test_mon_crushmap_validation: 1553: ceph tell 'mon.*' injectargs --crushtool crushtool
*** DEVELOPER MODE: setting PATH, PYTHONPATH and LD_LIBRARY_PATH ***
test_mon_crushmap_validation: 1: rm -fr /tmp/cephtool29135
make[4]: make[2]: *** [check-TESTS] Terminated
```
- http://gitbuilder.sepia.ceph.com/gitbuilder-ceph-tarball-trusty-i386-basic/log.cgi?log=6170eb5c67740c22242d640cb3f17281b9996137
```
FAIL: test/ceph_objectstore_tool.py

Test --op dump-journal
Journal max_size = 104857600
WARNING: No entries in journal found, probably a problem
ERROR: {u'header': {u'committed_up_to': 0, u'start': 884736, u'flags': 1, u'alignment': 4096, u'start_seq': 202, u'block_size': 4096, u'fsid': u'430481c6-dd8e-4fb2-aafc-5a5ec19c65ef', u'max_size': 104857600}, u'entries': []}
```

i am rerunning the "make check" locally.

**Comment by dachary** [comment]
http://gitbuilder.sepia.ceph.com/gitbuilder-ceph-tarball-precise-amd64-basic/log.cgi?log=6170eb5c67740c22242d640cb3f17281b9996137

had a number of ceph-mon / ceph-osd lingering. I killed them and force-rebuilt.

**Comment by dachary** [comment]
http://gitbuilder.sepia.ceph.com/gitbuilder-ceph-tarball-trusty-i386-basic/log.cgi?log=6170eb5c67740c22242d640cb3f17281b9996137

also had number of ceph-mon / ceph-osd lingering. I killed them and force-rebuilt.

**Comment by dachary** [comment]
http://gitbuilder.sepia.ceph.com/gitbuilder-ceph-tarball-trusty-i386-basic/log.cgi?log=6170eb5c67740c22242d640cb3f17281b9996137
<pre>
    error: Added files: 

+ cat .git/added-files
qa/workunits/erasure-code/encode-decode-non-regression.sh.log
qa/workunits/erasure-code/encode-decode-non-regression.sh.trs 
</pre>

**Comment by dachary** [comment]
re-running on the gitbuilders

**Comment by tchaikov** [comment]
just ran the "make check" with and without the change:
```
# with the change
$ make check 2>&1 | tee ~/wip-make-check-verbose.log
$ ls -lh ~/wip-make-check-verbose.log
-rw-rw-r-- 1 kchai kchai 16K May 17 08:42 /home/kchai/wip-make-check-verbose.log

# without the change
$ make check 2>&1 | tee ~/make-check.log
$ ls -lh ~/make-check.log
-rw-rw-r-- 1 kchai kchai 50K May 17 10:40 /home/kchai/make-check.log
```

**Comment by dachary** [comment]
@tchaikov I'm surprised the run without the change is not bigger. But that's ok ;-)

**Comment by dachary** [comment]
running on the gitbuilders, the previous run failed on tarbals because of an unrelated error

**Comment by tchaikov** [comment]
> @tchaikov I'm surprised the run without the change is not bigger. But that's ok ;-)

@dachary, the run without the change is 50K, while the one with the change is 16K. so the latter is considerably smaller.

**Pull request merged**
