### PR TITLE
octopus: test/store_test: refactor bluestore spillover test

### PR DESCRIPTION
**Pull request by ifed01**
Fixes:

* https://tracker.ceph.com/issues/45426
* https://tracker.ceph.com/issues/46055

Backports:

* https://tracker.ceph.com/issues/44880

Signed-off-by: Igor Fedotov <ifedotov@suse.com>
(cherry picked from commit 81e46e708a35873defe6deaaee4229024c213f7f)

---

To Do:

- [x] https://github.com/ceph/ceph/pull/35656 merged
- [x] https://github.com/ceph/ceph/pull/35656 cherry-picked into this PR
- [x] remove DNM
- [x] include in next integration run

### CODE REVIEW

**Comment by yuriw** [comment]
[wip-yuri7-testing-2020-05-19-2300-octopus](https://trello.com/c/EOVJPJeu/911-wip-yuri7-testing-2020-05-19-2300-octopus)

**Comment by neha-ojha** [comment]
Looks like the test is still failing http://pulpito.ceph.com/yuriw-2020-05-20_15:33:53-rados-wip-yuri7-testing-2020-05-19-2300-octopus-distro-basic-smithi/5073256/

**Comment by yuriw** [comment]
[wip-yuri4-testing_5.28.20](https://trello.com/c/PKtbZc6M/917-wip-yuri4-testing52820)

**Comment by ifed01** [comment]
@yuriw, @neha-ojha - this now has both fixes from master and hence is ready for the next QA run.

**Comment by neha-ojha** [comment]
@ifed01  https://pulpito.ceph.com/nojha-2020-06-29_21:46:49-rados:objectstore-wip-ifed-fix-spillover-octopus-distro-basic-smithi/

branch: https://github.com/ceph/ceph-ci/commits/wip-ifed-fix-spillover-octopus

```
2020-06-30T02:16:49.725 INFO:teuthology.orchestra.run.smithi042.stdout:/home/jenkins-build/build/workspace/ceph-dev-new-build/ARCH/x86_64/AVAILABLE_ARCH/x86_64/AVAILABLE_DIST/centos8/DIST/centos8/MACHINE_SIZE/gigantic/release/15.2.3-554-gde90997fcf4/rpm/el8/BUILD/ceph-15.2.3-554-gde90997fcf4/src/test/objectstore/store_test.cc:8281: Failure
2020-06-30T02:16:49.725 INFO:teuthology.orchestra.run.smithi042.stdout:Expected: (logger->get(l_bluefs_slow_used_bytes)) >= (16 * 1024 * 1024), actual: 0 vs 16777216
2020-06-30T02:16:49.736 INFO:teuthology.orchestra.run.smithi042.stdout:
2020-06-30T02:17:23.099 INFO:teuthology.orchestra.run.smithi042.stdout:==> rm -r bluestore.test_temp_dir
2020-06-30T02:17:23.270 INFO:teuthology.orchestra.run.smithi042.stdout:[  FAILED  ] ObjectStore/StoreTestSpecificAUSize.SpilloverTest/2, where GetParam() = "bluestore" (70127 ms)
```

**Comment by ifed01** [comment]
@yuriw, @neha-ojha - finally disabled the check which was causing the test case to fail. Please re-run QA.

**Comment by yuriw** [comment]
[wip-yuri7-testing-2020-07-06-1754-octopus](https://trello.com/c/VGUTyb8R/952-wip-yuri7-testing-2020-07-06-1754-octopus)

**Pull request merged**
