### PR TITLE
hammer: librados: bad flags can crash the osd

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/16432

### CODE REVIEW

**Comment by smithfarm** [comment]
@liewegas This backport passed a rados suite at http://tracker.ceph.com/issues/17151#note-7 with failures that I believe have been addressed (except for http://tracker.ceph.com/issues/15139 which is caused by the build system no longer providing dumpling-era packages).

I have rebuilt the integration branch to include the two fixes and scheduled a new run at http://tracker.ceph.com/issues/17151#note-14

Do you think it's OK to merge provided the second run succeeds?

**Comment by smithfarm** [comment]
Second run succeeded; third run here: http://pulpito.front.sepia.ceph.com/smithfarm-2016-11-21_11:52:41-rados-hammer-backports---basic-smithi/

**Comment by smithfarm** [comment]
@liewegas @athanatos This passed another rados run, see http://tracker.ceph.com/issues/17151#note-23

Do you think it can be merged?

**Comment by athanatos** [comment]
@jdurgin @liewegas Wait a minute.  This changes the librados header.  That seems bad.

I think the only part we want to backport is the ReplicatedPG bit that avoid crashing the osd.

**Comment by liewegas** [comment]
Yeah I think i brought this up on the jewel backprot, but we can't backport the remove() fucntion addition because it goes from not overloaded to overloaded, which breaks the ABI.

**Comment by athanatos** [comment]
Changed to DNM

**Comment by smithfarm** [comment]
> I think i brought this up on the jewel backprot, but we can't backport the remove() fucntion addition because it goes from not overloaded to overloaded, which breaks the ABI.

The jewel backport  of 1aa807f uses remove() without needing any additional commits, so apparently librados supports remove() in jewel.

**Comment by liewegas** [comment]
yeah, let's just drop the test

**Comment by smithfarm** [comment]
@liewegas So, in the first commit, I dropped just the test that uses `remove()` - is that OK or did you mean to drop the entire commit?

**Comment by smithfarm** [comment]
@athanatos This just passed a rados run at http://tracker.ceph.com/issues/17151#note-38 and I dropped the test that was using `remove()`.

Do you think it's OK to merge now?

**Pull request merged**
