### PR TITLE
kv: add column family support to KeyValueDB and RocksDBStore

### PR DESCRIPTION
**Pull request by jjhuo**
Column family is a very useful feature which RocksDB provides, basically user can create a dedicated column family for one kind of prefixed keys, and RocksDB will create dedicated LSM tree for it, still a transaction includes multiple kv updates into different CFs can be atomic.

This PR adds CF support into KeyValueDB interface and RocksDBStore implementation. The basic model is, the default column family can still have multiple prefixes, while each explicitly created column family can only have on prefix which is the name of the CF. All old APIs are kept backward compatible, user will have to call new API to create column families for some prefixes, then use old get/set APIs to access prefixed keys. RocksDBStore internally will remember all opened column families, if prefix matches name of created column family, it will go to that column family. By doing this, current modules who are using RocksDB only need small changes during init to enable this feature.

### CODE REVIEW

**Comment by yuyuyu101** [comment]
👍

**Comment by yuyuyu101** [comment]
From rocksdb internal impl, do you think what benefit we can get from column family in bluestore/filestore omap case?

**Comment by liewegas** [comment]
Hmm, do we really need to define a new type for ColumnFamilyIterator?  We already have the virtual interface defined vai WholeSpaceIterator.  Can't the implementation instantiate a different implementation in the cf case?

**Comment by jjhuo** [comment]
@yuyuyu101 In general, I think storing different data(onode, omap, bitmap...) into different column families(CF) will help, since rocksdb compaction will happen within each CF and each will have only its own data to compact and it will reduce write-amp. Yesterday, I just learned that ZetaScale bluestore integration also store omap in a separate ZS namespace(same as rocksdb CF); another benefit is, each CF can be individually configured, right now bluestore can only use same config options for all rocksdb data, however as people do more rocksdb tuning and will find some option may be good for one kind of data but not fit well for another kind of data in rocksdb; also it'll help db get as well, as different data are stored in different CF, each CF will have less levels than merged all together, and then Get() will have less levels to traverse.

**Comment by liewegas** [comment]
It might also be useful/important to put multiple prefixes in the same column family.  We get that with the default CF, but we might want ot think about whther that'll be sufficient for bluestore.  Adding new CF's isn't free.. it means we'll write out multiple SSTs (one for each CF) when the wal/log gets flushed.

**Comment by jjhuo** [comment]
@liewegas I second you, for very small data set, it's not worth putting it on an individual CF. Current implementation still supports multiple prefixes stored in the default CF, but a new CF only uses one prefix. Yes, adding new CF's isn't free, probably it makes more sense for SSD not HDD.

Thank you very much for reviewing the interface, regarding to the iterator, I defined this new CF type because WholeSpaceIterator has this four functions which take prefix parameter. Essentially, WholeSpaceIterator supports multiple prefixes, but ColumnFamilyIterator only use one fixed prefix.
    virtual int seek_to_first(const std::string &prefix) = 0;
    virtual int seek_to_last(const std::string &prefix) = 0;
    virtual int upper_bound(const std::string &prefix, const std::string &after) = 0;
    virtual int lower_bound(const std::string &prefix, const std::string &to) = 0;

**Comment by yuyuyu101** [comment]
after some basic investigate on rocksdb, I think Prefix Seek API(https://github.com/facebook/rocksdb/wiki/Prefix-Seek-API-Changes) may be more suitable.

**Comment by jjhuo** [comment]
@yuyuyu101 Prefixed seek will mostly benefit seeking which may be not in IO path, while CF has broader impact to I/O performance as I stated above.

**Comment by jjhuo** [comment]
@liewegas @yuyuyu101  Could you please review this? I think this PR is ready for merge. I added test cases in test_kv, both test_kv and ceph_test_objectstore passed. This PR only provides this feature for potential users, like filestore, bluestore and mon. I will create another PR for bluestore to use column family later. Thanks!

**Comment by Jeegn-Chen** [comment]
When the cluster grows large, monitor store's performance will need more and more consideration as well.
CF may also be a good choice there since different monitor services are using different prefixes for separation.

**Comment by yuyuyu101** [comment]
@jjhuo sorry for the delay. I scan the changes and the goal looks ok to me.

But I think whether it's worth to hijack prefix to check column family. Do we consider to introduce a new api to set column family for transaction instead? Otherwise, it looks a little hack to caller. And I think only rocksdb supports this feature, it maybe just a individual api.

**Comment by jjhuo** [comment]
@yuyuyu101 Thanks for your review! Yes, it has a little hack, in order to make things much easier. I thought about the other choice of creating new APIs for column family too in the first beginning, that would require more changes: a new API for each kvdb operations(get/put/rm/iterator...), and change all current kv calls to use those new APIs. That's why I went down this path, users just call one API to create CF to use it, and that's it; also, this make enabling/disabling use of CF much easier with a new option in the config option file(e.g. SSD to turn it on, HDD to turn it off);  last, one unique feature this approach can provide is, it's possible and easy to implement configurable CF policies: for example, users can specify which prefix/prefixes of bluestore goes into dedicated CFs in config file.

**Comment by jjhuo** [comment]
@liewegas Hi Sage, could you please review this when you have time? thanks!

**Comment by yuyuyu101** [comment]
Actually I'm still worry about the extra lookup overhead for each api! It maybe not expensive but really unnecessary. I vote to add a new set of apis, and I think it will be more clear without too much works, like rocksdb api did:
  void Put(ColumnFamilyHandle* column_family, const Slice& key,
           const Slice& value) override;
  void Put(const Slice& key, const Slice& value) override {
    Put(nullptr, key, value);
  }

I'm not sure whether column family could help to the current single rocksdb thread submit bottleneck, but this will be a good try because memtable will be different which should be help for reducing submit latency and rocksdb internal table lock contention......

@liewegas do you think this pr is eager to push now? or the CF introduce way suggestion?

**Comment by liewegas** [comment]
@yuyuyu101 I've been waiting on this PR until we stabilizing the on-disk format and then do some performance characterization to see where column families will help.

I agree the lookup overhead is worrying... I like the handle approach.

**Comment by markhpc** [comment]
I did some testing with this over the weekend.  I had to fix a couple of things to get it to apply to master and also modified bluestore to create the column families.  It works for a while, but ends up crashing in various ways.  "allocate failed... wtf" failures in bluefs (despite seemingly having enough space), or if I reduce the size of the level0 memtables via smaller WAL buffers, stupidallocator failures (though again after memtable creation):

```
    -6> 2016-11-12 08:12:21.783803 7f7368d07700  4 rocksdb: [default] New memtable created with log file: #463. Immutable memtables: 0.

    -5> 2016-11-12 08:12:21.783863 7f7368d07700  4 rocksdb: [O] New memtable created with log file: #463. Immutable memtables: 0.

    -4> 2016-11-12 08:12:21.783898 7f7368d07700  4 rocksdb: [M] New memtable created with log file: #463. Immutable memtables: 0.

    -3> 2016-11-12 08:12:21.783910 7f7368d07700  4 rocksdb: [L] New memtable created with log file: #463. Immutable memtables: 0.

    -2> 2016-11-12 08:12:21.790888 7f7356ce3700  4 rocksdb: [L] [JOB 355] Generated table #462: 340 keys, 1429858 bytes
    -1> 2016-11-12 08:12:21.790947 7f7356ce3700  4 rocksdb: EVENT_LOG_v1 {"time_micros": 1478956341790908, "cf_name": "L", "job": 355, "event": "table_file_creation", "file_number": 462, "file_size": 1429858, "table_properties": {"data_size": 1419500, "index_size": 9514, "filter_size": 0, "raw_key_size": 5440, "raw_average_key_size": 16, "raw_value_size": 1408280, "raw_average_value_size": 4142, "num_data_blocks": 340, "num_entries": 340, "filter_policy_name": "", "kDeletedKeys": "0", "kMergeOperands": "0"}}
     0> 2016-11-12 08:12:21.794961 7f7356ce3700 -1 /home/ubuntu/src/markhpc/ceph/src/os/bluestore/StupidAllocator.cc: In function 'virtual void StupidAllocator::commit_start()' thread 7f7356ce3700 time 2016-11-12 08:12:21.791124
/home/ubuntu/src/markhpc/ceph/src/os/bluestore/StupidAllocator.cc: 333: FAILED assert(committing.empty())

 ceph version 10.0.4-11150-g73e5006 (73e50062d3e5a4df508ccf854eb0a9f4d78c89a5)
 1: (ceph::__ceph_assert_fail(char const*, char const*, int, char const*)+0x85) [0x55eacb51f325]
 2: (StupidAllocator::commit_start()+0x2c4) [0x55eacb37c914]
 3: (BlueFS::sync_metadata()+0x22e) [0x55eacb35496e]
 4: (BlueRocksDirectory::Fsync()+0xd) [0x55eacb36881d]
 5: (rocksdb::CompactionJob::Run()+0x2a7) [0x55eacb4a9f67]
 6: (rocksdb::DBImpl::BackgroundCompaction(bool*, rocksdb::JobContext*, rocksdb::LogBuffer*, void*)+0x9a7) [0x55eacb3ab647]
 7: (rocksdb::DBImpl::BackgroundCallCompaction(void*)+0x281) [0x55eacb3bbca1]
 8: (rocksdb::ThreadPoolImpl::BGThread(unsigned long)+0x1a1) [0x55eacb4d6841]
 9: (()+0xa3f923) [0x55eacb4d6923]
 10: (()+0x7dc5) [0x7f7382125dc5]
 11: (clone()+0x6d) [0x7f738100cced]
 NOTE: a copy of the executable, or `objdump -rdS <executable>` is needed to interpret this.

--- logging levels ---
   0/ 5 none
   0/ 0 lockdep
   0/ 0 context
   0/ 0 crush
   0/ 0 mds
   0/ 0 mds_balancer
   0/ 0 mds_locker
   0/ 0 mds_log
   0/ 0 mds_log_expire
   0/ 0 mds_migrator
   0/ 0 buffer
   0/ 0 timer
   0/ 0 filer
   0/ 1 striper
   0/ 0 objecter
   0/ 0 rados
   0/ 0 rbd
   0/ 5 rbd_mirror
   0/ 5 rbd_replay
   0/ 0 journaler
   0/ 0 objectcacher
   0/ 0 client
   0/ 0 osd
   0/ 0 optracker
   0/ 0 objclass
   0/ 0 filestore
   0/ 0 journal
   0/ 0 ms
   0/ 0 mon
   0/ 0 monc
   0/ 0 paxos
   0/ 0 tp
   0/ 0 auth
   1/ 5 crypto
   0/ 0 finisher
   0/ 0 heartbeatmap
   0/ 0 perfcounter
   0/ 0 rgw
   1/10 civetweb
   1/ 5 javaclient
   0/ 0 asok
   0/ 0 throttle
   0/ 0 refs
   1/ 5 xio
   1/ 5 compressor
   1/ 5 newstore
   0/ 0 bluestore
   0/ 0 bluefs
   0/ 0 bdev
   1/ 5 kstore
   4/ 5 rocksdb
   4/ 5 leveldb
   4/ 5 memdb
   1/ 5 kinetic
   1/ 5 fuse
   1/ 5 mgr
   1/ 5 mgrc
   1/ 5 dpdk
  -2/-2 (syslog threshold)
  -1/-1 (stderr threshold)
  max_recent     10000
  max_new         1000
  log_file /tmp/cbt/ceph/log/osd.4.log
--- end dump of recent events ---
2016-11-12 08:12:21.906894 7f7356ce3700 -1 *** Caught signal (Aborted) **
 in thread 7f7356ce3700 thread_name:rocksdb:bg0

 ceph version 10.0.4-11150-g73e5006 (73e50062d3e5a4df508ccf854eb0a9f4d78c89a5)
 1: (()+0x8fdb9a) [0x55eacb394b9a]
 2: (()+0xf100) [0x7f738212d100]
 3: (gsignal()+0x37) [0x7f7380f4b5f7]
 4: (abort()+0x148) [0x7f7380f4cce8]
 5: (ceph::__ceph_assert_fail(char const*, char const*, int, char const*)+0x267) [0x55eacb51f507]
 6: (StupidAllocator::commit_start()+0x2c4) [0x55eacb37c914]
 7: (BlueFS::sync_metadata()+0x22e) [0x55eacb35496e]
 8: (BlueRocksDirectory::Fsync()+0xd) [0x55eacb36881d]
 9: (rocksdb::CompactionJob::Run()+0x2a7) [0x55eacb4a9f67]
 10: (rocksdb::DBImpl::BackgroundCompaction(bool*, rocksdb::JobContext*, rocksdb::LogBuffer*, void*)+0x9a7) [0x55eacb3ab647]
 11: (rocksdb::DBImpl::BackgroundCallCompaction(void*)+0x281) [0x55eacb3bbca1]
 12: (rocksdb::ThreadPoolImpl::BGThread(unsigned long)+0x1a1) [0x55eacb4d6841]
 13: (()+0xa3f923) [0x55eacb4d6923]
 14: (()+0x7dc5) [0x7f7382125dc5]
 15: (clone()+0x6d) [0x7f738100cced]
 NOTE: a copy of the executable, or `objdump -rdS <executable>` is needed to interpret this.

--- begin dump of recent events ---
     0> 2016-11-12 08:12:21.906894 7f7356ce3700 -1 *** Caught signal (Aborted) **
 in thread 7f7356ce3700 thread_name:rocksdb:bg0

 ceph version 10.0.4-11150-g73e5006 (73e50062d3e5a4df508ccf854eb0a9f4d78c89a5)
 1: (()+0x8fdb9a) [0x55eacb394b9a]
 2: (()+0xf100) [0x7f738212d100]
 3: (gsignal()+0x37) [0x7f7380f4b5f7]
 4: (abort()+0x148) [0x7f7380f4cce8]
 5: (ceph::__ceph_assert_fail(char const*, char const*, int, char const*)+0x267) [0x55eacb51f507]
 6: (StupidAllocator::commit_start()+0x2c4) [0x55eacb37c914]
 7: (BlueFS::sync_metadata()+0x22e) [0x55eacb35496e]
 8: (BlueRocksDirectory::Fsync()+0xd) [0x55eacb36881d]
 9: (rocksdb::CompactionJob::Run()+0x2a7) [0x55eacb4a9f67]
 10: (rocksdb::DBImpl::BackgroundCompaction(bool*, rocksdb::JobContext*, rocksdb::LogBuffer*, void*)+0x9a7) [0x55eacb3ab647]
 11: (rocksdb::DBImpl::BackgroundCallCompaction(void*)+0x281) [0x55eacb3bbca1]
 12: (rocksdb::ThreadPoolImpl::BGThread(unsigned long)+0x1a1) [0x55eacb4d6841]
 13: (()+0xa3f923) [0x55eacb4d6923]
 14: (()+0x7dc5) [0x7f7382125dc5]
 15: (clone()+0x6d) [0x7f738100cced]
 NOTE: a copy of the executable, or `objdump -rdS <executable>` is needed to interpret this.

--- logging levels ---
   0/ 5 none
   0/ 0 lockdep
   0/ 0 context
   0/ 0 crush
   0/ 0 mds
   0/ 0 mds_balancer
   0/ 0 mds_locker
   0/ 0 mds_log
   0/ 0 mds_log_expire
   0/ 0 mds_migrator
   0/ 0 buffer
   0/ 0 timer
   0/ 0 filer
   0/ 1 striper
   0/ 0 objecter
   0/ 0 rados
   0/ 0 rbd
   0/ 5 rbd_mirror
   0/ 5 rbd_replay
   0/ 0 journaler
   0/ 0 objectcacher
   0/ 0 client
   0/ 0 osd
   0/ 0 optracker
   0/ 0 objclass
   0/ 0 filestore
   0/ 0 journal
   0/ 0 ms
   0/ 0 mon
   0/ 0 monc
   0/ 0 paxos
   0/ 0 tp
   0/ 0 auth
   1/ 5 crypto
   0/ 0 finisher
   0/ 0 heartbeatmap
   0/ 0 perfcounter
   0/ 0 rgw
   1/10 civetweb
   1/ 5 javaclient
   0/ 0 asok
   0/ 0 throttle
   0/ 0 refs
   1/ 5 xio
   1/ 5 compressor
   1/ 5 newstore
   0/ 0 bluestore
   0/ 0 bluefs
   0/ 0 bdev
   1/ 5 kstore
   4/ 5 rocksdb
   4/ 5 leveldb
   4/ 5 memdb
   1/ 5 kinetic
   1/ 5 fuse
   1/ 5 mgr
   1/ 5 mgrc
   1/ 5 dpdk
  -2/-2 (syslog threshold)
  -1/-1 (stderr threshold)
  max_recent     10000
  max_new         1000
  log_file /tmp/cbt/ceph/log/osd.4.log
--- end dump of recent events ---
```

**Comment by markhpc** [comment]
Testing branch is here:

https://github.com/markhpc/ceph/commits/wip-column-family

**Comment by jjhuo** [comment]
@markhpc maybe we can try this over xfs instead of bluefs; if that works, means this crash is related to bluefs/allocator?

**Comment by markhpc** [comment]
Switching to the bitmap allocator appears to have resolved the above bug, however I have not yet discovered anything in the stupidallocator commit code that would have caused this.  After a much longer running test, I did hit a CRC check assert when using the bitmap allocator:

```
    -1> 2016-11-15 09:54:54.291496 7f8f3f154700 -1 bluestore(/tmp/cbt/mnt/osd-device-2-data) _verify_csum bad crc32c/0x1000 checksum at blob offset 0x24000, got 0x53d2e26, expected 0x3de51385, device location [0x257adc000~1000], object #1:58d04ce9:::rbd_data.10556b8b4567.000000000000039e:head#
     0> 2016-11-15 09:54:54.296419 7f8f3f154700 -1 /home/ubuntu/src/markhpc/ceph/src/os/bluestore/BlueStore.cc: In function 'virtual int BlueStore::read(ObjectStore::CollectionHandle&, const ghobject_t&, uint64_t, size_t, ceph::bufferlist&, uint32_t, bool)' thread 7f8f3f154700 time 2016-11-15 09:54:54.291571
/home/ubuntu/src/markhpc/ceph/src/os/bluestore/BlueStore.cc: 5039: FAILED assert(allow_eio || r != -5)

 ceph version 10.0.4-11150-g73e5006 (73e50062d3e5a4df508ccf854eb0a9f4d78c89a5)
 1: (ceph::__ceph_assert_fail(char const*, char const*, int, char const*)+0x85) [0x563fb9b9b325]
 2: (BlueStore::read(boost::intrusive_ptr<ObjectStore::CollectionImpl>&, ghobject_t const&, unsigned long, unsigned long, ceph::buffer::list&, unsigned int, bool)+0x833) [0x563fb99141d3]
 3: (ReplicatedBackend::build_push_op(ObjectRecoveryInfo const&, ObjectRecoveryProgress const&, ObjectRecoveryProgress*, PushOp*, object_stat_sum_t*, bool)+0x26b) [0x563fb97cf29b]
 4: (ReplicatedBackend::prep_push(std::shared_ptr<ObjectContext>, hobject_t const&, pg_shard_t, eversion_t, interval_set<unsigned long>&, std::map<hobject_t, interval_set<unsigned long>, hobject_t::BitwiseComparator, std::allocator<std::pair<hobject_t const, interval_set<unsigned long> > > >&, PushOp*, bool)+0x4a0) [0x563fb97d5610]
 5: (ReplicatedBackend::prep_push_to_replica(std::shared_ptr<ObjectContext>, hobject_t const&, pg_shard_t, PushOp*, bool)+0x1a7) [0x563fb97d5aa7]
 6: (ReplicatedBackend::start_pushes(hobject_t const&, std::shared_ptr<ObjectContext>, ReplicatedBackend::RPGHandle*)+0x174) [0x563fb97d6704]
 7: (ReplicatedBackend::recover_object(hobject_t const&, eversion_t, std::shared_ptr<ObjectContext>, std::shared_ptr<ObjectContext>, PGBackend::RecoveryHandle*)+0xfb) [0x563fb97d690b]
 8: (ReplicatedPG::prep_backfill_object_push(hobject_t, eversion_t, std::shared_ptr<ObjectContext>, std::vector<pg_shard_t, std::allocator<pg_shard_t> >, PGBackend::RecoveryHandle*)+0x5f3) [0x563fb96921b3]
 9: (ReplicatedPG::recover_backfill(unsigned long, ThreadPool::TPHandle&, bool*)+0x14c9) [0x563fb96ea069]
 10: (ReplicatedPG::start_recovery_ops(unsigned long, ThreadPool::TPHandle&, unsigned long*)+0x950) [0x563fb96efa50]
 11: (OSD::do_recovery(PG*, unsigned int, unsigned long, ThreadPool::TPHandle&)+0x40c) [0x563fb9566c5c]
 12: (OSD::ShardedOpWQ::_process(unsigned int, ceph::heartbeat_handle_d*)+0x76d) [0x563fb956d91d]
 13: (ShardedThreadPool::shardedthreadpool_worker(unsigned int)+0x947) [0x563fb9ba0f97]
 14: (ShardedThreadPool::WorkThreadSharded::entry()+0x10) [0x563fb9ba30f0]
 15: (()+0x7dc5) [0x7f8f61584dc5]
 16: (clone()+0x6d) [0x7f8f6046bced]
 NOTE: a copy of the executable, or `objdump -rdS <executable>` is needed to interpret this.

--- logging levels ---
   0/ 5 none
   0/ 0 lockdep
   0/ 0 context
   0/ 0 crush
   0/ 0 mds
   0/ 0 mds_balancer
   0/ 0 mds_locker
   0/ 0 mds_log
   0/ 0 mds_log_expire
   0/ 0 mds_migrator
   0/ 0 buffer
   0/ 0 timer
   0/ 0 filer
   0/ 1 striper
   0/ 0 objecter
   0/ 0 rados
   0/ 0 rbd
   0/ 5 rbd_mirror
   0/ 5 rbd_replay
   0/ 0 journaler
   0/ 0 objectcacher
   0/ 0 client
   0/ 0 osd
   0/ 0 optracker
   0/ 0 objclass
   0/ 0 filestore
   0/ 0 journal
   0/ 0 ms
   0/ 0 mon
   0/ 0 monc
   0/ 0 paxos
   0/ 0 tp
   0/ 0 auth
   1/ 5 crypto
   0/ 0 finisher
   0/ 0 heartbeatmap
   0/ 0 perfcounter
   0/ 0 rgw
   1/10 civetweb
   1/ 5 javaclient
   0/ 0 asok
   0/ 0 throttle
   0/ 0 refs
   1/ 5 xio
   1/ 5 compressor
   1/ 5 newstore
   0/ 0 bluestore
   0/ 0 bluefs
   0/ 0 bdev
   1/ 5 kstore
   4/ 5 rocksdb
   4/ 5 leveldb
   4/ 5 memdb
   1/ 5 kinetic
   1/ 5 fuse
   1/ 5 mgr
   1/ 5 mgrc
   1/ 5 dpdk
  -2/-2 (syslog threshold)
  -1/-1 (stderr threshold)
  max_recent     10000
  max_new         1000
  log_file /tmp/cbt/ceph/log/osd.2.log
--- end dump of recent events ---
2016-11-15 09:54:54.363490 7f8f3f154700 -1 *** Caught signal (Aborted) **
 in thread 7f8f3f154700 thread_name:tp_osd_tp

 ceph version 10.0.4-11150-g73e5006 (73e50062d3e5a4df508ccf854eb0a9f4d78c89a5)
 1: (()+0x8fdb9a) [0x563fb9a10b9a]
 2: (()+0xf100) [0x7f8f6158c100]
 3: (gsignal()+0x37) [0x7f8f603aa5f7]
 4: (abort()+0x148) [0x7f8f603abce8]
 5: (ceph::__ceph_assert_fail(char const*, char const*, int, char const*)+0x267) [0x563fb9b9b507]
 6: (BlueStore::read(boost::intrusive_ptr<ObjectStore::CollectionImpl>&, ghobject_t const&, unsigned long, unsigned long, ceph::buffer::list&, unsigned int, bool)+0x833) [0x563fb99141d3]
 7: (ReplicatedBackend::build_push_op(ObjectRecoveryInfo const&, ObjectRecoveryProgress const&, ObjectRecoveryProgress*, PushOp*, object_stat_sum_t*, bool)+0x26b) [0x563fb97cf29b]
 8: (ReplicatedBackend::prep_push(std::shared_ptr<ObjectContext>, hobject_t const&, pg_shard_t, eversion_t, interval_set<unsigned long>&, std::map<hobject_t, interval_set<unsigned long>, hobject_t::BitwiseComparator, std::allocator<std::pair<hobject_t const, interval_set<unsigned long> > > >&, PushOp*, bool)+0x4a0) [0x563fb97d5610]
 9: (ReplicatedBackend::prep_push_to_replica(std::shared_ptr<ObjectContext>, hobject_t const&, pg_shard_t, PushOp*, bool)+0x1a7) [0x563fb97d5aa7]
 10: (ReplicatedBackend::start_pushes(hobject_t const&, std::shared_ptr<ObjectContext>, ReplicatedBackend::RPGHandle*)+0x174) [0x563fb97d6704]
 11: (ReplicatedBackend::recover_object(hobject_t const&, eversion_t, std::shared_ptr<ObjectContext>, std::shared_ptr<ObjectContext>, PGBackend::RecoveryHandle*)+0xfb) [0x563fb97d690b]
 12: (ReplicatedPG::prep_backfill_object_push(hobject_t, eversion_t, std::shared_ptr<ObjectContext>, std::vector<pg_shard_t, std::allocator<pg_shard_t> >, PGBackend::RecoveryHandle*)+0x5f3) [0x563fb96921b3]
 13: (ReplicatedPG::recover_backfill(unsigned long, ThreadPool::TPHandle&, bool*)+0x14c9) [0x563fb96ea069]
 14: (ReplicatedPG::start_recovery_ops(unsigned long, ThreadPool::TPHandle&, unsigned long*)+0x950) [0x563fb96efa50]
 15: (OSD::do_recovery(PG*, unsigned int, unsigned long, ThreadPool::TPHandle&)+0x40c) [0x563fb9566c5c]
 16: (OSD::ShardedOpWQ::_process(unsigned int, ceph::heartbeat_handle_d*)+0x76d) [0x563fb956d91d]
 17: (ShardedThreadPool::shardedthreadpool_worker(unsigned int)+0x947) [0x563fb9ba0f97]
 18: (ShardedThreadPool::WorkThreadSharded::entry()+0x10) [0x563fb9ba30f0]
 19: (()+0x7dc5) [0x7f8f61584dc5]
 20: (clone()+0x6d) [0x7f8f6046bced]
 NOTE: a copy of the executable, or `objdump -rdS <executable>` is needed to interpret this.

--- begin dump of recent events ---
     0> 2016-11-15 09:54:54.363490 7f8f3f154700 -1 *** Caught signal (Aborted) **
 in thread 7f8f3f154700 thread_name:tp_osd_tp

 ceph version 10.0.4-11150-g73e5006 (73e50062d3e5a4df508ccf854eb0a9f4d78c89a5)
 1: (()+0x8fdb9a) [0x563fb9a10b9a]
 2: (()+0xf100) [0x7f8f6158c100]
 3: (gsignal()+0x37) [0x7f8f603aa5f7]
 4: (abort()+0x148) [0x7f8f603abce8]
 5: (ceph::__ceph_assert_fail(char const*, char const*, int, char const*)+0x267) [0x563fb9b9b507]
 6: (BlueStore::read(boost::intrusive_ptr<ObjectStore::CollectionImpl>&, ghobject_t const&, unsigned long, unsigned long, ceph::buffer::list&, unsigned int, bool)+0x833) [0x563fb99141d3]
 7: (ReplicatedBackend::build_push_op(ObjectRecoveryInfo const&, ObjectRecoveryProgress const&, ObjectRecoveryProgress*, PushOp*, object_stat_sum_t*, bool)+0x26b) [0x563fb97cf29b]
 8: (ReplicatedBackend::prep_push(std::shared_ptr<ObjectContext>, hobject_t const&, pg_shard_t, eversion_t, interval_set<unsigned long>&, std::map<hobject_t, interval_set<unsigned long>, hobject_t::BitwiseComparator, std::allocator<std::pair<hobject_t const, interval_set<unsigned long> > > >&, PushOp*, bool)+0x4a0) [0x563fb97d5610]
 9: (ReplicatedBackend::prep_push_to_replica(std::shared_ptr<ObjectContext>, hobject_t const&, pg_shard_t, PushOp*, bool)+0x1a7) [0x563fb97d5aa7]
 10: (ReplicatedBackend::start_pushes(hobject_t const&, std::shared_ptr<ObjectContext>, ReplicatedBackend::RPGHandle*)+0x174) [0x563fb97d6704]
 11: (ReplicatedBackend::recover_object(hobject_t const&, eversion_t, std::shared_ptr<ObjectContext>, std::shared_ptr<ObjectContext>, PGBackend::RecoveryHandle*)+0xfb) [0x563fb97d690b]
 12: (ReplicatedPG::prep_backfill_object_push(hobject_t, eversion_t, std::shared_ptr<ObjectContext>, std::vector<pg_shard_t, std::allocator<pg_shard_t> >, PGBackend::RecoveryHandle*)+0x5f3) [0x563fb96921b3]
 13: (ReplicatedPG::recover_backfill(unsigned long, ThreadPool::TPHandle&, bool*)+0x14c9) [0x563fb96ea069]
 14: (ReplicatedPG::start_recovery_ops(unsigned long, ThreadPool::TPHandle&, unsigned long*)+0x950) [0x563fb96efa50]
 15: (OSD::do_recovery(PG*, unsigned int, unsigned long, ThreadPool::TPHandle&)+0x40c) [0x563fb9566c5c]
 16: (OSD::ShardedOpWQ::_process(unsigned int, ceph::heartbeat_handle_d*)+0x76d) [0x563fb956d91d]
 17: (ShardedThreadPool::shardedthreadpool_worker(unsigned int)+0x947) [0x563fb9ba0f97]
 18: (ShardedThreadPool::WorkThreadSharded::entry()+0x10) [0x563fb9ba30f0]
 19: (()+0x7dc5) [0x7f8f61584dc5]
 20: (clone()+0x6d) [0x7f8f6046bced]
 NOTE: a copy of the executable, or `objdump -rdS <executable>` is needed to interpret this.

--- logging levels ---
   0/ 5 none
   0/ 0 lockdep
   0/ 0 context
   0/ 0 crush
   0/ 0 mds
   0/ 0 mds_balancer
   0/ 0 mds_locker
   0/ 0 mds_log
   0/ 0 mds_log_expire
   0/ 0 mds_migrator
   0/ 0 buffer
   0/ 0 timer
   0/ 0 filer
   0/ 1 striper
   0/ 0 objecter
   0/ 0 rados
   0/ 0 rbd
   0/ 5 rbd_mirror
   0/ 5 rbd_replay
   0/ 0 journaler
   0/ 0 objectcacher
   0/ 0 client
   0/ 0 osd
   0/ 0 optracker
   0/ 0 objclass
   0/ 0 filestore
   0/ 0 journal
   0/ 0 ms
   0/ 0 mon
   0/ 0 monc
   0/ 0 paxos
   0/ 0 tp
   0/ 0 auth
   1/ 5 crypto
   0/ 0 finisher
   0/ 0 heartbeatmap
   0/ 0 perfcounter
   0/ 0 rgw
   1/10 civetweb
   1/ 5 javaclient
   0/ 0 asok
   0/ 0 throttle
   0/ 0 refs
   1/ 5 xio
   1/ 5 compressor
   1/ 5 newstore
   0/ 0 bluestore
   0/ 0 bluefs
   0/ 0 bdev
   1/ 5 kstore
   4/ 5 rocksdb
   4/ 5 leveldb
   4/ 5 memdb
   1/ 5 kinetic
   1/ 5 fuse
   1/ 5 mgr
   1/ 5 mgrc
   1/ 5 dpdk
  -2/-2 (syslog threshold)
  -1/-1 (stderr threshold)
  max_recent     10000
  max_new         1000
  log_file /tmp/cbt/ceph/log/osd.2.log
--- end dump of recent events ---
```

**Comment by jjhuo** [comment]
Thanks! @markhpc Should we turn off checksum just for performance benchmarking purpose? also, I would suggest to have only PREFIX_OBJ, PREFIX_OMAP and PREFIX_WAL stored in their own column families, others(relatively small data sets) still share the default column family. @liewegas what do you think?

**Comment by somnathr** [comment]
@markhpc @liewegas I think quite a bit of WAL keys are leaking into L0 as the L0 is increasing very fast in case of 16K min_alloc_size. It is not matching my calculation of writing only ~600 bytes  (only onode) per IO. So, IMO, putting PREFIX_WAL to different CF could help.
Can we separate Onode and shards to different CF  , probably not as they share similar prefix ?

**Comment by varadakari** [comment]
I am not sure if we want to keep shards and onode differently will give any benefit. If they are close in spatial locality, we might find them in adjacent pages in cache. If we separate them, we might loose some cache effect there. But only empirical data can prove that now.

**Comment by markhpc** [comment]
jjhuo:  Definitely would like to see obj, omap, and wal in their own column families.  I'm not sure how much the others matter in practice.  We get slightly more useful reporting if they are in their own CF.  AFAIK rocksdb will autoflush them if they accumulate too many keys in the WAL, but I haven't really looked closely enough to really know what the code does.

somnath:  That's what I thought too, but when I tested this it looked like there wasn't very much WAL compaction traffic at all relative to omap and obj overhead.  I'd expect in the statistics we'd see a really high number of injest and dropped keys, but that doesn't seem to be the case.  I have a suspicion though that we're seeing much better behavior with keys in their own column families.  Before things crash, I'm seeing higher performance with column families. I don't know if it's only because we now have parallel L0->L1 compaction threads (per column family) or if the WAL flushing behavior is better as well.

varada: indeed, probably best to just test it.  At the very least getting independent compaction statistics from rocksdb would be useful for testing.

**Comment by dachary** [comment]
needs a rebase

**Comment by liewegas** [comment]
I have a cleaned up version of this branch; see https://github.com/ceph/ceph/pull/12164

**Pull request closed without merging**
