### PR TITLE
mds: fix handling of removexattr when there are none

### PR DESCRIPTION
**Pull request by jtlayton**
This fixes some brokenness I noticed while working on ganesha's FSAL_CEPH xattr implementation. It's just a subtle logic bug. If we don't have any xattrs at all then we still need to return -ENODATA.

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Review by batrick — APPROVED** [review]

**Review by vshankar — APPROVED** [review]
nice catch

**Review by sidharthanup — APPROVED** [review]

**Comment by batrick** [comment]
Jeff, did  you see this issue? https://tracker.ceph.com/issues/49873 Might be related.

**Comment by jtlayton** [comment]
> Jeff, did you see this issue? https://tracker.ceph.com/issues/49873 Might be related.

Yeah, it might be. I'll comment in the tracker.

**Comment by batrick** [comment]
https://pulpito.ceph.com/pdonnell-2021-03-18_13:46:31-fs-wip-pdonnell-testing-20210318.024145-distro-basic-smithi/

- https://tracker.ceph.com/issues/49466
    qa: "Command failed on gibba030 with status 1: 'set -ex\nsudo dd of=/tmp/tmp.ZEeZBasJer'"
- https://tracker.ceph.com/issues/48773
    qa: scrub does not complete
- https://tracker.ceph.com/issues/48805
    mds: "cluster [WRN] Scrub error on inode 0x1000000039d (/client.0/tmp/blogbench-1.0/src/blogtest_in) see mds.a log and `damage ls` output for details"
- https://tracker.ceph.com/issues/45434
    qa: test_full_fsync (tasks.cephfs.test_full.TestClusterFull) failed
- https://tracker.ceph.com/issues/49845
    qa: failed umount in test_volumes
- https://tracker.ceph.com/issues/49605
    mgr: drops command on the floor
- https://tracker.ceph.com/issues/48203 (stock kernel update required)
    qa: quota failure
- https://tracker.ceph.com/issues/49928
    client: items pinned in cache preventing unmount x2

**Pull request merged**
