### PR TITLE
os/bluestore: When the folder is not empty, you can delete it

### PR DESCRIPTION
**Pull request by ShiqiCooperation**
Signed-off-by: shiqi <1454927420@qq.com>

### CODE REVIEW

**Comment by ShiqiCooperation** [comment]
Why it build failed, it build ok in my develop environment.

**Comment by tchaikov** [comment]
retest this please.

**Comment by ShiqiCooperation** [comment]
retest it please

**Comment by liewegas** [comment]
When does rmdir get called on a non-empty dir?  I wouldn't expect rocksdb to ever call rmdir, actually...

**Pull request closed without merging**
