### PR TITLE
common/admin_socket: always validate the parameters

### PR DESCRIPTION
**Pull request by tchaikov**
## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by tchaikov** [comment]
thanks to @badone for pointing out what the root cause is.

**Review by jdurgin — APPROVED** [review]
lgtm, may want to use earlier c++ syntax to ease backporting

**Review by neha-ojha — APPROVED** [review]

**Comment by tchaikov** [comment]
> lgtm, may want to use earlier c++ syntax to ease backporting

i will take care of the backport if we have FTBFS on nautilus with these two commits. but FWIW, nautilus is already using C++17 standard.

**Comment by tchaikov** [comment]
https://pulpito.ceph.com/kchai-2020-09-12_03:23:31-rados-wip-kefu-testing-2020-09-12-0647-distro-basic-smithi/

**Comment by tchaikov** [comment]
- https://pulpito.ceph.com/kchai-2020-09-12_03:23:31-rados-wip-kefu-testing-2020-09-12-0647-distro-basic-smithi/
- https://pulpito.ceph.com/kchai-2020-09-12_13:41:38-rados-wip-kefu-testing-2020-09-12-2016-distro-basic-smithi/

failures tracked by

- https://tracker.ceph.com/issues/47423

**Review by badone — APPROVED** [review]
This passed my local tests and resolves https://tracker.ceph.com/issues/47179

**Pull request merged**
