### PR TITLE
mimic: ceph_volume_client: py3 compatible

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/26850

### CODE REVIEW

**Comment by neha-ojha** [comment]
@yuriw @batrick Let's run the `rados:upgrade` suite on this PR, in order to test if we need https://github.com/ceph/ceph/pull/24479 for mimic.

**Comment by smithfarm** [comment]
@yuriw Please run `rados:upgrade` as requested by @neha-ojha, above.

**Comment by yuriw** [comment]
[wip-yuri2-testing-2018-10-30-1927-mimic](https://trello.com/c/UBu0fx9W/457-wip-yuri2-testing-2018-10-30-1927-mimic)

**Comment by neha-ojha** [comment]
Need to handle mimic failures such as http://pulpito.ceph.com/yuriw-2018-11-16_02:51:56-rados-wip-yuri5-testing-2018-11-16-0044-mimic-distro-basic-smithi/3259308/ caused due to this PR.

**Pull request merged**
