### PR TITLE
build/ops: deb: move python-jinja2 dependency to mgr

### PR DESCRIPTION
**Pull request by smithfarm**
87399bea8321a7a9ab554085be3a3d5e0563f27f introduced an explicit dependency on
python-jinja2, but mistakenly as an overall build dependency instead of as a
runtime dependency of ceph-mgr as intended.

Fixes: http://tracker.ceph.com/issues/22457
Signed-off-by: Nathan Cutler <ncutler@suse.com>
(cherry picked from commit b7e638f7e42ac232958f2ca2f16f8202cb5ae5bf)

### CODE REVIEW

**Comment by smithfarm** [comment]
ceph-disk tox tests fail with:

```
py27 runtests: commands[0] | coverage run --append --source=ceph_disk /home/jenkins-build/build/workspace/ceph-pull-requests/src/ceph-disk/.tox/py27/bin/py.test -vv /home/jenkins-build/build/workspace/ceph-pull-requests/src/ceph-disk/tests/test_main.py
ERROR: InvocationError: could not find executable 'coverage'
```

retest this please

**Comment by smithfarm** [comment]
ah the coverage issue is not due to this PR - it's happening in other luminous PRs as well

**Comment by tchaikov** [comment]
retest this please

**Comment by yuriw** [comment]
[wip-yuri2-testing-2018-04-03-1604-luminous](https://trello.com/c/IhzuMQzr/284-wip-yuri2-testing-2018-04-03-1604-luminous)

**Pull request merged**
