### PR TITLE
osd: fix Incremental decode for new/old_pg_upmap_primary

### PR DESCRIPTION
**Pull request by ljflores**
Should have been included in commit e9921ee76c060122d64e61a2fe483318a49bc0a9. The impact is not major; the effect is that the osdmap is not properly updated whenever the Incremental is reused. Since the current read balancer offline tool uses a new Incremental every time it's run, the balancing works as expected. This fix will be necessary, however, for the mgr module integration in https://github.com/ceph/ceph/pull/53988 since we will need to reuse the Incremental.

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [x] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Review by JoshSalomon — APPROVED** [review]
lgtm

**Comment by JoshSalomon** [comment]
jenkins test make check

**Comment by JoshSalomon** [comment]
jenkins help

**Comment by JoshSalomon** [comment]
jenkins test ceph API tests

**Comment by JoshSalomon** [comment]
jenkins test api

**Comment by JoshSalomon** [comment]
jenkins test make check arm64

**Comment by ronen-fr** [comment]
@Matan-B is this related to your changes re incremental maps?

**Comment by Matan-B** [comment]
> @Matan-B is this related to your changes re incremental maps?

Nope, thanks for the ping though!

**Comment by ronen-fr** [comment]
RADOS approves:
https://tracker.ceph.com/projects/rados/wiki/MAIN#httpstrellocomc6sy6WQmn1915-wip-yuri10-testing-2023-12-23-0824

**Pull request merged**
