### PR TITLE
Cleaning up dead stuff

### PR DESCRIPTION
**Pull request by ErwanAliasr1**
Hi fellows,

This is my first contribution to Ceph and started by some low hanging fruits. I've been reading some code and found some dead code.

This PR is a set of commits trying to remove this dead/useless code.

Hope that will match your quality criteria,

### CODE REVIEW

**Comment by tchaikov** [comment]
@ErwanAliasr1 you might need to sign-off your commits using "git commit -s"? see https://github.com/ceph/ceph/blob/master/SubmittingPatches#L61 ?

**Comment by ErwanAliasr1** [comment]
@tchaikov Updated & repushed. Sorry for the missing.

**Comment by tchaikov** [comment]
lgtm.

**Comment by liewegas** [comment]
This doesn't compile:

osd/OSD.cc: In member function ‘void TestOpsSocketHook::test_ops(OSDService*, ObjectStore*, std::string, cmdmap_t&, std::ostream&)’:
error: osd/OSD.cc:4224:5: ‘r’ was not declared in this scope
r = service->cct->_conf->set_val("osd_recovery_delay_start",
^

**Comment by tchaikov** [comment]
@ErwanAliasr1 ping.

**Comment by ErwanAliasr1** [comment]
My bad... I'm really sorry. Will be fixed by tomorrow.

**Comment by ErwanAliasr1** [comment]
This is now fixed & rebased against master.
Sorry about this error.

**Comment by tchaikov** [comment]
compiles fine, and lgtm

**Comment by ErwanAliasr1** [comment]
Thanks for the merge.

**Comment by liewegas** [comment]
Of course, thanks for the patches!

**Pull request merged**
