### PR TITLE
osd: update dmclock library w git subtree pull

### PR DESCRIPTION
**Pull request by ivancich**
The dmclock library has had a number of updates, some allowing all components to be compiled with gcc 7.1.1. We should pull it in.

### CODE REVIEW

**Comment by ivancich** [comment]
pulpito: http://pulpito.ceph.com/ivancich-2017-09-13_22:11:33-rados-wip-pull-updated-dmclock---basic-smithi/

**Comment by joscollin** [comment]
Jenkins retest this please

**Comment by ivancich** [comment]
@joscollin Yeah, when you do a `git subtree pull `it turns into two commits, the first of which you don't have the opportunity to sign. Someone with sufficient rights can do the merge despite that.

**Comment by joscollin** [comment]
@ivancich Do you mean you cannot `amend` it too ?

**Comment by joscollin** [comment]
@ivancich See this attempt https://github.com/ceph/ceph/pull/17716/commits

**Comment by ivancich** [comment]
@joscollin It's the first of two commits that `git subtree pull` does that needs the amending. So when you get back to the command-line it's two commits back, and to my knowledge `git commit --amend` cannot touch it. A `git rebase -i` would generally work, although there's an issue when you try to replay a commit in a git subtree -- it loses the prefix to the paths and applies the patches to the wrong files.

Can you outline the commands/process you're suggesting?

**Comment by tchaikov** [comment]
http://pulpito.ceph.com/kchai-2017-09-15_19:26:05-rados-wip-kefu-testing-2017-09-16-0123-distro-basic-mira/

**Comment by joscollin** [comment]
@ivancich I was suggesting `git rebase -i sha`. Sorry for the wrong word `amend` in the previous comment. But if it creates a problem (applies the patches to the wrong files) then leave it. May be someone with more rights can merge without `Signed-off-by`, not sure though.

**Comment by tchaikov** [comment]
@ivancich for some reason, the title of this PR has `[DNM]` in it. so let's hold on until `[DNM]` is removed.

**Comment by joscollin** [comment]
@tchaikov I think `DNM` is put by @ivancich himself, as the first notification email in my inbox shows `@ivancich requested your review on: ceph/ceph#17737 [DNM] osd: update dmclock library w git subtree pull.`

**Comment by ivancich** [comment]
DNM removed. In the past these have been merge-able. I'm guessing @liewegas can do it.

**Pull request merged**
