### PR TITLE
doc: Remove inactive Ceph mirrors.

### PR DESCRIPTION
**Pull request by mty22**
## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [x] Doc update (no ticket needed)
  - [x] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [x] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

### CODE REVIEW

**Review by anthonyeleven — APPROVED** [review]

**Comment by anthonyeleven** [comment]
Jenkins please retest this

**Comment by anthonyeleven** [comment]
jenkins retest this please

**Comment by tchaikov** [comment]
jenkins test make check

**Comment by anthonyeleven** [comment]
jenkins retest this please

**Comment by anthonyeleven** [comment]
jenkins retest this please

**Comment by anthonyeleven** [comment]
jenkins retest this please

**Comment by anthonyeleven** [comment]
jenkins test api

**Pull request merged**
