### PR TITLE
jewel: multisite sync races with deletes

### PR DESCRIPTION
**Pull request by theanalyst**
http://tracker.ceph.com/issues/16589

### CODE REVIEW

**Comment by theanalyst** [comment]
@cbodley @yehudasa this is a backport for http://tracker.ceph.com/issues/16464 contains #9481 #9851 (which should fix the delete issue) I had to pick #9295 as well for a clean backport, this looks harmless enough  to be backported for jewel we can drop it. What do you think of adding #9295?

**Comment by cbodley** [comment]
#9295 should be harmless to pull in :+1:

**Comment by yehudasa** [comment]
@theanalyst yeah, we can pull it in

**Comment by theanalyst** [comment]
jenkins retest this please

**Pull request merged**
