### PR TITLE
pybind/rbd: make the code more concise

### PR DESCRIPTION
**Pull request by zy751713126**
Signed-off-by: Zheng Yin <zhengyin@cmss.chinamobile.com>

- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by tchaikov** [comment]
> making output information more concise

the commit message is misleading. IIUC, this change is merely a refactory. and it does not change the output message.

**Comment by tchaikov** [comment]
also, your Signed-off-by line does not look right. "git commit -s" will do the trick for you. see https://github.com/ceph/ceph/blob/master/SubmittingPatches.rst#1-sign-your-work

**Comment by zy751713126** [comment]
@tchaikov this patch should make the code more concise, thanks a lot.

**Comment by tchaikov** [comment]
- http://pulpito.ceph.com/kchai-2018-08-22_06:33:19-rados-wip-kefu-testing-2018-08-22-1055-distro-basic-mira/
- http://pulpito.ceph.com/kchai-2018-08-23_05:31:20-rados-wip-kefu-testing-2018-08-22-1055-distro-basic-mira/
- http://pulpito.ceph.com/kchai-2018-08-23_10:10:43-rados-wip-kefu-testing-2018-08-22-1055-distro-basic-mira/
- http://pulpito.ceph.com/kchai-2018-08-23_11:09:48-rados-wip-kefu-testing-2018-08-22-1055-distro-basic-mira/

**Pull request merged**
