### PR TITLE
mgr/zabbix: Backports to Luminous

### PR DESCRIPTION
**Pull request by wido**
This PR is a backport of all kinds of fixes in the master branch for the Zabbix module to the Luminous branch/release.

### CODE REVIEW

**Comment by tchaikov** [comment]
retest this please

**Comment by wido** [comment]
The test seems to fail on a ceph-disk Python test. Can we kick the tests again?

**Comment by jcsp** [comment]
retest this please (jenkins)

**Comment by wido** [comment]
All checks have passed. Can we merge this one so it makes it into the next luminous?

**Comment by smithfarm** [comment]
@wido Added "luminous-batch-1" to get it into a future round of luminous integration testing.

**Comment by yuriw** [comment]
[wip-yuri5-testing-2018-03-27-1535-luminous](https://trello.com/c/0zxXqm9m/281-wip-yuri5-testing-2018-03-27-1535-luminous)

**Pull request merged**
