### PR TITLE
Wip ceph spec mandir

### PR DESCRIPTION
**Pull request by osynge**
This removes a breakage in fedora build see here for details.

https://build.opensuse.org/package/live_build_log/home:osynge:ceph:wip:wip_obs_fedora/master+4898/Fedora_22/x86_64

### CODE REVIEW

**Comment by osynge** [comment]
corrected spelling in this bug fix.

**Comment by osynge** [comment]
yes we can dispense with the %{_mandir}/man8/*.8* lines.

**Comment by osynge** [comment]
can use %{_mandir} instead?

I try and test it using the same form.

**Comment by osynge** [comment]
In include them specifically as some man pages are included in other packages.

**Comment by osynge** [comment]
I moved back to explicit inclusion as more than one rpm includes man pages

**Comment by osynge** [comment]
/usr/share/man/man8/librados-config.8.gz was in conflict in last commit working on a tested fix.

**Comment by osynge** [comment]
Running tests here

https://build.opensuse.org/package/show/home:osynge:ceph:wip:wip_obs_fedora/master+4920
https://build.opensuse.org/package/show/home:osynge:ceph:wip:wip_obs_fedora/master+4920+4918

**Comment by osynge** [comment]
tests failed but latest version that should pass is here

**Comment by osynge** [comment]
tests pass again with this update :)

**Comment by osynge** [comment]
master+4920+4918+4898 -> work on suse + fedora on OBS allowing them to use OBS for their SUSE work.

(This patch is more critical for OBS users working on fedora or verifying they dont break fedora)

**Comment by osynge** [comment]
now under new testing do not yet merge

**Comment by osynge** [comment]
this also needs a fix to the dependencies to resolve this.

**Comment by dachary** [comment]
@branto1 The merge message has 
<pre>
The file lists in spec files do expect that man pages are built so we better explicitly state that intention in spec file.
</pre>
Could you please add a Reviewed-by line like it's done with other merge messages the next time ?

**Comment by branto1** [comment]
@dachary: Ok, will do next time.

**Pull request merged**
