### PR TITLE
msg/async: avoid creating unnecessary AsyncConnectionRef

### PR DESCRIPTION
**Pull request by batrick**
Signed-off-by: Patrick Donnelly <pdonnell@redhat.com>

### CODE REVIEW

**Comment by batrick** [comment]
From #26348

**Comment by batrick** [comment]
retest this please

**Comment by batrick** [comment]
I'll add a comment and

> Or put the ConnectionRef& type in the callers instead of auto&& to communicate the danger...

sure

**Comment by batrick** [comment]
done

**Comment by tchaikov** [comment]
- http://pulpito.ceph.com/kchai-2019-04-09_12:51:48-rados-wip-kefu-testing-2019-04-09-1348-distro-basic-mira/
- http://pulpito.ceph.com/kchai-2019-04-11_01:06:08-rados-wip-kefu-testing-2019-04-09-1348-distro-basic-smithi/

the only genuine failure is https://tracker.ceph.com/issues/23947

**Comment by tchaikov** [comment]
@liewegas good to merge?

**Comment by tchaikov** [comment]
@batrick needs rebase

**Comment by liewegas** [comment]
> @batrick needs rebase

only because i just merged it :)

**Pull request merged**
