### PR TITLE
jewel: add max_part and nbds_max options in rbd nbd map, in order to keep consistent with  

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/18214

### CODE REVIEW

**Comment by smithfarm** [comment]
@trociny This PR passed an RBD suite at http://tracker.ceph.com/issues/17851#note-41 
with a single failure [1] that was not reproducible in a subsequent run.

[1] The failure was a reoccurrence of http://tracker.ceph.com/issues/17695
which was supposed to have been fixed in jewel by https://github.com/ceph/ceph/pull/11644

**Comment by trociny** [comment]
BTW Jason wants to merge #12890, which includes API methods to acquire and release the exclusive lock. So I think we can also backport rbd nbd `--exlusive` option [1] then, and there would not be conflicts in this PR and in #12754.

@dillaman what do you think?

[1] http://tracker.ceph.com/issues/17488

**Comment by dillaman** [comment]
@smithfarm @trociny I'd prefer to limit feature creep back to Jewel if at all possible. The conflicts look like they should be trivial to resolve.

**Comment by smithfarm** [comment]
I wholeheartedly agree with @dillaman - what is the point of having a stable release if we are going to backport anything and everything to it. Ideally we would backport bugfixes only.

**Comment by smithfarm** [comment]
This passed another RBD suite at http://tracker.ceph.com/issues/17851#note-59

**Pull request merged**
