### PR TITLE
pacific: osd: fix to recover adjacent clone when set_chunk is called

### PR DESCRIPTION
**Pull request by cfsnyder**
backport tracker: https://tracker.ceph.com/issues/51952

---

backport of https://github.com/ceph/ceph/pull/42279
parent tracker: https://tracker.ceph.com/issues/51627

this backport was staged using ceph-backport.sh version 16.0.0.6848
find the latest version at https://github.com/ceph/ceph/blob/master/src/script/ceph-backport.sh

### CODE REVIEW

**Review by neha-ojha — APPROVED** [review]

**Comment by neha-ojha** [comment]
@myoungwon I am seeing the following failure https://pulpito.ceph.com/yuriw-2021-09-10_14:30:41-rados-wip-yuri3-testing-2021-09-09-1028-pacific-distro-basic-smithi/6383307/ in the teuthology run, can you please check if it is related? We have already backported the fix for https://tracker.ceph.com/issues/48915.

```
2021-09-11T07:43:02.814 INFO:tasks.workunit.client.0.smithi150.stdout:              api_tier_pp: [ RUN      ] LibRadosTwoPoolsPP.ManifestFlushDupCount
2021-09-11T07:43:02.815 INFO:tasks.workunit.client.0.smithi150.stdout:              api_tier_pp: require_osd_release = pacific
2021-09-11T07:43:02.815 INFO:tasks.workunit.client.0.smithi150.stdout:              api_tier_pp: /home/jenkins-build/build/workspace/ceph-dev-new-build/ARCH/x86_64/AVAILABLE_ARCH/x86_64/AVAILABLE_DIST/centos8/DIST/centos8/MACHINE_SIZE/gigantic/release/16.2.5-564-g5719b5fe/rpm/el8/BUILD/ceph-16.2.5-564-g5719b5fe/src/test/librados/tier_cxx.cc:5328: Failure
2021-09-11T07:43:02.815 INFO:tasks.workunit.client.0.smithi150.stdout:              api_tier_pp: Expected equality of these values:
2021-09-11T07:43:02.816 INFO:tasks.workunit.client.0.smithi150.stdout:              api_tier_pp:   1u
2021-09-11T07:43:02.816 INFO:tasks.workunit.client.0.smithi150.stdout:              api_tier_pp:     Which is: 1
2021-09-11T07:43:02.816 INFO:tasks.workunit.client.0.smithi150.stdout:              api_tier_pp:   refs.count()
2021-09-11T07:43:02.817 INFO:tasks.workunit.client.0.smithi150.stdout:              api_tier_pp:     Which is: 2
```

Full run: https://pulpito.ceph.com/yuriw-2021-09-10_14:30:41-rados-wip-yuri3-testing-2021-09-09-1028-pacific-distro-basic-smithi/

**Comment by yuriw** [comment]
@myoungwon any updates ?

**Comment by yuriw** [comment]
see tests and chat here https://trello.com/c/e5aNZMmQ

add `needs-qa` tag if needs retesting

**Comment by myoungwon** [comment]
Sorry for the delay. I'll take a look.

**Comment by myoungwon** [comment]
@neha-ojha @yuriw  I think this issue was resolved (see https://github.com/ceph/ceph/pull/42302), but the PR is not merged yet to pacific branch.

**Comment by myoungwon** [comment]
https://github.com/ceph/ceph/pull/43306

**Comment by neha-ojha** [comment]
> #43306

@myoungwon Thanks for creating the backport PR. @yuriw could you please test https://github.com/ceph/ceph/pull/43099 and https://github.com/ceph/ceph/pull/43306 together?

**Pull request merged**
