### PR TITLE
jewel: mds: optimize getattr file size

### PR DESCRIPTION
**Pull request by pdvian**
http://tracker.ceph.com/issues/23014

### CODE REVIEW

**Comment by smithfarm** [comment]
@pdvian Please rebase (merge conflict).

**Comment by smithfarm** [comment]
@batrick How important is this backport in terms of getting it into jewel?

**Comment by batrick** [comment]
It is not essential.

**Comment by smithfarm** [comment]
@pdvian Please rebase. The PR may not make it into 10.2.11, that's all.

**Comment by pdvian** [comment]
@smithfarm sure. Let me rebase and push the changes.

**Comment by pdvian** [comment]
@smithfarm Rebased and pushed the changes. Kindly review.

**Comment by smithfarm** [comment]
Jewel is EOL

**Pull request closed without merging**
