### PR TITLE
jewel: rgw: Do not decrement stats cache when the cache values are zero

### PR DESCRIPTION
**Pull request by prallabh**
http://tracker.ceph.com/issues/20821
http://tracker.ceph.com/issues/21136

### CODE REVIEW

**Comment by prallabh** [comment]
@oritwas can you please help review.
@smithfarm I've back ported this to Jewel by cherry picking from the master PR. Wanted this to be in the next release of Jewel pretty badly, thanks!

**Comment by smithfarm** [comment]
@prallabh Looks good, will include it in the next jewel integration branch.

**Comment by smithfarm** [comment]
@prallabh Could you please cherry-pick 634215eea1ddd4e4f5dc0066c4a2e745cfc20475 into this PR? (Ping me if/when you do so, and I'll add http://tracker.ceph.com/issues/21136 to the PR description.)

**Comment by prallabh** [comment]
@smithfarm Have done so, updated the description, rebased as well.

**Comment by smithfarm** [comment]
Thanks!

**Comment by smithfarm** [comment]
This passed an rgw suite at http://tracker.ceph.com/issues/20613#note-53

**Pull request merged**
