### PR TITLE
nautilus: rgw: multisite: DELETE Bucket CORS is not forwarded to master zone

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/40515

### CODE REVIEW

**Comment by smithfarm** [comment]
```
ERROR in ./src/app/ceph/cluster/osd/osd-list/osd-list.component.scss
Module build failed (from ./node_modules/sass-loader/lib/loader.js):
Error: Cannot find module 'node-sass'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.sassLoader (/home/jenkins-build/build/workspace/ceph-pull-requests/src/pybind/mgr/dashboard/frontend/node_modules/sass-loader/lib/loader.js:46:72)
ERROR in ./src/styles.scss (./node_modules/@angular-devkit/build-angular/src/angular-cli-files/plugins/raw-css-loader.js!./node_modules/postcss-loader/src??embedded!./node_modules/sass-loader/lib/loader.js??ref--14-3!./src/styles.scss)
Module build failed (from ./node_modules/sass-loader/lib/loader.js):
Error: Cannot find module 'node-sass'
... (etc. etc.)
```

Can't see how the dashboard front end build failure would be related to this PR, though.

**Comment by smithfarm** [comment]
jenkins re-test this please

**Comment by smithfarm** [comment]
```
Traceback (most recent call last):
  File "/home/jenkins-build/build/workspace/ceph-pull-requests/build/src/pybind/mgr/dashboard/node-env/bin/nodeenv", line 10, in <module>
    sys.exit(main())
  File "/home/jenkins-build/build/workspace/ceph-pull-requests/build/src/pybind/mgr/dashboard/node-env/local/lib/python2.7/site-packages/nodeenv.py", line 1076, in main
    create_environment(env_dir, opt)
  File "/home/jenkins-build/build/workspace/ceph-pull-requests/build/src/pybind/mgr/dashboard/node-env/local/lib/python2.7/site-packages/nodeenv.py", line 905, in create_environment
    install_node(env_dir, src_dir, opt)
  File "/home/jenkins-build/build/workspace/ceph-pull-requests/build/src/pybind/mgr/dashboard/node-env/local/lib/python2.7/site-packages/nodeenv.py", line 692, in install_node
    download_node_src(node_url, src_dir, opt, prefix)
  File "/home/jenkins-build/build/workspace/ceph-pull-requests/build/src/pybind/mgr/dashboard/node-env/local/lib/python2.7/site-packages/nodeenv.py", line 542, in download_node_src
    dl_contents = io.BytesIO(urlopen(node_url).read())
  File "/usr/lib/python2.7/socket.py", line 355, in read
    data = self._sock.recv(rbufsize)
  File "/usr/lib/python2.7/httplib.py", line 612, in read
    s = self.fp.read(amt)
  File "/usr/lib/python2.7/socket.py", line 384, in read
    data = self._sock.recv(left)
  File "/usr/lib/python2.7/ssl.py", line 756, in recv
    return self.read(buflen)
  File "/usr/lib/python2.7/ssl.py", line 643, in read
[ 53%] Building CXX object src/librbd/CMakeFiles/rbd_internal.dir/operation/EnableFeaturesRequest.cc.o
    v = self._sslobj.read(len)
socket.error: [Errno 104] Connection reset by peer
src/pybind/mgr/dashboard/CMakeFiles/mgr-dashboard-nodeenv.dir/build.make:60: recipe for target 'src/pybind/mgr/dashboard/node-env/bin/npm' failed
make[3]: *** [src/pybind/mgr/dashboard/node-env/bin/npm] Error 1
CMakeFiles/Makefile2:5567: recipe for target 'src/pybind/mgr/dashboard/CMakeFiles/mgr-dashboard-nodeenv.dir/all' failed
make[2]: *** [src/pybind/mgr/dashboard/CMakeFiles/mgr-dashboard-nodeenv.dir/all] Error 2
```

**Comment by smithfarm** [comment]
@tmelo Do you understand why Jenkins is failing to build the dashboard front-end here?

**Comment by smithfarm** [comment]
jenkins test make check

**Comment by yuriw** [comment]
[wip-yuri-testing-2019-07-25-1441-nautilus](https://trello.com/c/ImUN401a/676-wip-yuri-testing-2019-07-25-1441-nautilus)

**Pull request merged**
