### PR TITLE
nautilus: mds: reject sessionless messages

### PR DESCRIPTION
**Pull request by smithfarm**
backport trackers:

* https://tracker.ceph.com/issues/41853
* https://tracker.ceph.com/issues/43345

possibly a backport of

* https://github.com/ceph/ceph/pull/29059
* https://github.com/ceph/ceph/pull/29594
* https://github.com/ceph/ceph/pull/32318

parent trackers:

* https://tracker.ceph.com/issues/40784
* https://tracker.ceph.com/issues/41329

---

updated using ceph-backport.sh version 15.0.0.6950

### CODE REVIEW

**Comment by smithfarm** [comment]
jenkins test docs

**Comment by smithfarm** [comment]
```
/home/jenkins-build/build/workspace/ceph-pull-requests/src/mds/Server.cc: In member function 'void Server::handle_client_session(const const_ref&)':
/home/jenkins-build/build/workspace/ceph-pull-requests/src/mds/Server.cc:445:18: error: 'make_message' was not declared in this scope
     auto reply = make_message<MClientSession>(CEPH_SESSION_REJECT);
                  ^~~~~~~~~~~~
/home/jenkins-build/build/workspace/ceph-pull-requests/src/mds/Server.cc:445:18: note: suggested alternative: 'decode_message'
     auto reply = make_message<MClientSession>(CEPH_SESSION_REJECT);
                  ^~~~~~~~~~~~
                  decode_message
/home/jenkins-build/build/workspace/ceph-pull-requests/src/mds/Server.cc:445:45: error: expected primary-expression before '>' token
     auto reply = make_message<MClientSession>(CEPH_SESSION_REJECT);
                                             ^
/home/jenkins-build/build/workspace/ceph-pull-requests/src/mds/Server.cc: In member function 'void Server::handle_client_reconnect(const const_ref&)':
/home/jenkins-build/build/workspace/ceph-pull-requests/src/mds/Server.cc:1240:18: error: 'make_message' was not declared in this scope
     auto reply = make_message<MClientSession>(CEPH_SESSION_REJECT);
                  ^~~~~~~~~~~~
/home/jenkins-build/build/workspace/ceph-pull-requests/src/mds/Server.cc:1240:18: note: suggested alternative: 'decode_message'
     auto reply = make_message<MClientSession>(CEPH_SESSION_REJECT);
                  ^~~~~~~~~~~~
                  decode_message
/home/jenkins-build/build/workspace/ceph-pull-requests/src/mds/Server.cc:1240:45: error: expected primary-expression before '>' token
     auto reply = make_message<MClientSession>(CEPH_SESSION_REJECT);
                                             ^
src/mds/CMakeFiles/mds.dir/build.make:153: recipe for target 'src/mds/CMakeFiles/mds.dir/Server.cc.o' failed
make[3]: *** [src/mds/CMakeFiles/mds.dir/Server.cc.o] Error 1

**Comment by batrick** [comment]
Will need #32318

**Comment by smithfarm** [comment]
@batrick Added the additional backport you requested, updated the PR description. Please have another look?

**Comment by smithfarm** [comment]
```
/home/jenkins-build/build/workspace/ceph-pull-requests/src/mds/Server.cc: In member function 'void Server::handle_client_reconnect(const const_ref&)':
/home/jenkins-build/build/workspace/ceph-pull-requests/src/mds/Server.cc:1263:18: error: 'make_message' was not declared in this scope
     auto reply = make_message<MClientSession>(CEPH_SESSION_CLOSE);
                  ^~~~~~~~~~~~
/home/jenkins-build/build/workspace/ceph-pull-requests/src/mds/Server.cc:1263:18: note: suggested alternative: 'decode_message'
     auto reply = make_message<MClientSession>(CEPH_SESSION_CLOSE);
                  ^~~~~~~~~~~~
                  decode_message
/home/jenkins-build/build/workspace/ceph-pull-requests/src/mds/Server.cc:1263:45: error: expected primary-expression before '>' token
     auto reply = make_message<MClientSession>(CEPH_SESSION_CLOSE);
                                             ^
src/mds/CMakeFiles/mds.dir/build.make:230: recipe for target 'src/mds/CMakeFiles/mds.dir/Server.cc.o' failed
make[3]: *** [src/mds/CMakeFiles/mds.dir/Server.cc.o] Error 1
make[3]: *** Waiting for unfinished jobs....
[ 43%] Building CXX object src/rgw/CMakeFiles/rgw_common.dir/rgw_lc.cc.o
[ 43%] Building CXX object src/librbd/CMakeFiles/rbd_internal.dir/LibrbdAdminSocketHook.cc.o
CMakeFiles/Makefile2:6012: recipe for target 'src/mds/CMakeFiles/mds.dir/all' failed
make[2]: *** [src/mds/CMakeFiles/mds.dir/all] Error 2
```

**Comment by batrick** [comment]
Looks good for QA.

**Comment by yuriw** [comment]
[wip-yuri3-testing-2020-02-09-2109-nautilus](https://trello.com/c/uOvzPFHl/821-wip-yuri3-testing-2020-02-09-2109-nautilus)

**Pull request merged**
