### PR TITLE
cls: optimize header file dependency

### PR DESCRIPTION
**Pull request by cxwshawn**
same work as https://github.com/ceph/ceph/pull/9539, https://github.com/ceph/ceph/pull/9336, https://github.com/ceph/ceph/pull/9307, https://github.com/ceph/ceph/pull/9287,

### CODE REVIEW

**Comment by cxwshawn** [comment]
@dillaman @liewegas  please help review, thanks.

**Comment by badone** [comment]
@cxwshawn I'd like to reopen this PR and to help get this in. Alternatively, I would be happy to take over this work as I am doing similar things at the moment? Please let me know.

**Comment by liewegas** [comment]
rebase please?

**Comment by badone** [comment]
Closing this, will attempt to complete the work in https://github.com/ceph/ceph/pull/15165

**Pull request closed without merging**
