### PR TITLE
kraken: PendingReleaseNotes on 19119

### PR DESCRIPTION
**Pull request by liewegas**

### CODE REVIEW

**Comment by shinobu-x** [comment]
jenkins test this please

**Comment by smithfarm** [comment]
@liewegas Could you change the heading s/11.1.1/11.2.1/ - thanks

**Comment by smithfarm** [comment]
@liewegas Ideally we would make this change in #13253 to avoid merge conflicts when populating the integration branches.

**Comment by smithfarm** [comment]
@liewegas If you agree, we could close this in favor of #14506

**Pull request closed without merging**
