### PR TITLE
[DNM] mimic: cephfs: ceph_volume_client: d_name needs to be converted to string before using

### PR DESCRIPTION
**Pull request by smithfarm**
https://tracker.ceph.com/issues/40325

### CODE REVIEW

**Comment by smithfarm** [comment]
jenkins test docs

**Comment by smithfarm** [comment]
doc build failure:

```
+ ./admin/build-doc
./admin/build-doc: missing required packages, please install them:
sudo apt-get install -o APT::Install-Recommends=true cython
```

**Comment by smithfarm** [comment]
jenkins test docs

**Comment by smithfarm** [comment]
test this please

**Comment by smithfarm** [comment]
`Docs: build check` fails with:

```
+ ./admin/build-doc
./admin/build-doc: missing required packages, please install them:
sudo apt-get install -o APT::Install-Recommends=true cython
```

**Comment by yuriw** [comment]
[wip-yuri6-testing-2019-10-07-1952-mimic](https://trello.com/c/Dvb371pJ/711-wip-yuri6-testing-2019-10-07-1952-mimic)

**Comment by smithfarm** [comment]
@yuriw ACK. It sounds like @vshankar is analyzing the test failures.

**Comment by vshankar** [comment]
> @yuriw ACK. It sounds like @vshankar is analyzing the test failures.

yeh -- this failed in another teuthology run (for mimic) where this PR is not included. So, it doesn't seem to be related to this PR. I'll double check and approve.

**Comment by vshankar** [comment]
@smithfarm the teuthology failure is caused by this PR due to the commit 75614420c99dc4b2b1de028a2ca0fd57f6257e30 ("admin/build-doc: use python3"). The original PR runs fine with python: https://github.com/ceph/ceph/pull/28196.

Marking as DNM for now.

**Comment by rishabh-d-dave** [comment]
Came across [this issue](https://tracker.ceph.com/issues/42317) while reproducing the issue on this PR.

**Comment by batrick** [comment]
Closing as Mimic is EOL.

**Pull request closed without merging**
