### PR TITLE
squid: rgw: compatibility issues on BucketPublicAccessBlock

### PR DESCRIPTION
**Pull request by cbodley**
backport tracker: https://tracker.ceph.com/issues/64795

---

backport of https://github.com/ceph/ceph/pull/55652
parent tracker: https://tracker.ceph.com/issues/64492

this backport was staged using ceph-backport.sh version 16.0.0.6848
find the latest version at https://github.com/ceph/ceph/blob/main/src/script/ceph-backport.sh

### CODE REVIEW

**Comment by cbodley** [comment]
qa needs to include https://github.com/ceph/s3-tests/pull/551

**Review by dang — APPROVED** [review]

**Comment by cbodley** [comment]
passed qa in https://pulpito.ceph.com/cbodley-2024-03-10_14:50:40-rgw-wip-cbodley2-testing-distro-default-smithi/

**Comment by cbodley** [comment]
jenkins test this please

**Comment by cbodley** [comment]
> The following tests FAILED:
	  7 - run-tox-mgr-dashboard-py3 (Failed)

**Comment by cbodley** [comment]
jenkins test make check

**Comment by cbodley** [comment]
> The following tests FAILED:
	 33 - run-rbd-unit-tests-109.sh (Failed)

**Comment by cbodley** [comment]
jenkins test make check

**Pull request merged**
