### PR TITLE
[DNM NEEDS REBASE] nautilus: qa: add dashboard tests to upgrades/mimic-x

### PR DESCRIPTION
**Pull request by jdurgin**
Adjust dashboard tests slightly to work across versions and after other tests have run.

### CODE REVIEW

**Comment by jdurgin** [comment]
Running here: http://pulpito.ceph.com/yuriw-2019-08-15_21:56:33-upgrade:mimic-x:parallel-nautilus-distro-basic-smithi/

**Comment by rjfd** [comment]
@jdurgin what's the status, are teuthology tests now working?

**Comment by jdurgin** [comment]
not yet, same issues as https://github.com/ceph/ceph/pull/29055#issuecomment-526634577

**Comment by jdurgin** [comment]
latest run: http://pulpito.ceph.com/joshd-2019-10-16_00:27:29-upgrade:mimic-x:parallel-nautilus-distro-basic-smithi/

**Comment by callithea** [comment]
There seems to be an issue with the following test case where the telemetry module is supposed to get disabled but _is_ already disabled:

```2019-10-17T09:12:17.359 INFO:tasks.ceph.mgr.y.smithi171.stderr:[17/Oct/2019:09:12:17] ENGINE Serving on :::7791
2019-10-17T09:12:17.359 INFO:tasks.ceph.mgr.y.smithi171.stderr:[17/Oct/2019:09:12:17] ENGINE Bus STARTED
2019-10-17T09:12:18.124 INFO:teuthology.orchestra.run.smithi096.stderr:module 'telemetry' is already disabled
2019-10-17T09:12:18.137 INFO:tasks.mgr.dashboard.helper:command result:
2019-10-17T09:12:18.137 INFO:tasks.cephfs_test_runner:
2019-10-17T09:12:18.137 INFO:tasks.cephfs_test_runner:======================================================================
2019-10-17T09:12:18.137 INFO:tasks.cephfs_test_runner:ERROR: test_disable (tasks.mgr.dashboard.test_mgr_module.MgrModuleTelemetryTest)
2019-10-17T09:12:18.137 INFO:tasks.cephfs_test_runner:----------------------------------------------------------------------
2019-10-17T09:12:18.138 INFO:tasks.cephfs_test_runner:Traceback (most recent call last):
2019-10-17T09:12:18.138 INFO:tasks.cephfs_test_runner:  File "/home/teuthworker/src/github.com_jdurgin_ceph_wip-dash-nautilus/qa/tasks/mgr/dashboard/test_mgr_module.py", line 186, in test_disable
2019-10-17T09:12:18.138 INFO:tasks.cephfs_test_runner:    self.wait_until_rest_api_accessible()
2019-10-17T09:12:18.138 INFO:tasks.cephfs_test_runner:  File "/home/teuthworker/src/github.com_jdurgin_ceph_wip-dash-nautilus/qa/tasks/mgr/dashboard/test_mgr_module.py", line 35, in wait_until_rest_api_accessible
2019-10-17T09:12:18.138 INFO:tasks.cephfs_test_runner:    self.wait_until_true(_check_connection, timeout=30)
2019-10-17T09:12:18.138 INFO:tasks.cephfs_test_runner:  File "/home/teuthworker/src/github.com_jdurgin_ceph_wip-dash-nautilus/qa/tasks/ceph_test_case.py", line 167, in wait_until_true
2019-10-17T09:12:18.138 INFO:tasks.cephfs_test_runner:    time.sleep(period)
2019-10-17T09:12:18.138 INFO:tasks.cephfs_test_runner:  File "/home/teuthworker/src/git.ceph.com_git_teuthology_master/virtualenv/local/lib/python2.7/site-packages/gevent/hub.py", line 169, in sleep
2019-10-17T09:12:18.139 INFO:tasks.cephfs_test_runner:    hub.wait(loop.timer(seconds, ref=ref))
2019-10-17T09:12:18.139 INFO:tasks.cephfs_test_runner:  File "/home/teuthworker/src/git.ceph.com_git_teuthology_master/virtualenv/local/lib/python2.7/site-packages/gevent/hub.py", line 651, in wait
2019-10-17T09:12:18.139 INFO:tasks.cephfs_test_runner:    result = waiter.get()
2019-10-17T09:12:18.139 INFO:tasks.cephfs_test_runner:  File "/home/teuthworker/src/git.ceph.com_git_teuthology_master/virtualenv/local/lib/python2.7/site-packages/gevent/hub.py", line 899, in get
2019-10-17T09:12:18.139 INFO:tasks.cephfs_test_runner:    return self.hub.switch()
2019-10-17T09:12:18.139 INFO:tasks.cephfs_test_runner:  File "/home/teuthworker/src/git.ceph.com_git_teuthology_master/virtualenv/local/lib/python2.7/site-packages/gevent/hub.py", line 630, in switch
2019-10-17T09:12:18.139 INFO:tasks.cephfs_test_runner:    return RawGreenlet.switch(self)
2019-10-17T09:12:18.139 INFO:tasks.cephfs_test_runner:NoSuchProcess: psutil.NoSuchProcess process no longer exists (pid=20265)
2019-10-17T09:12:18.140 INFO:tasks.cephfs_test_runner:
2019-10-17T09:12:18.140 INFO:tasks.cephfs_test_runner:----------------------------------------------------------------------
2019-10-17T09:12:18.140 INFO:tasks.cephfs_test_runner:Ran 163 tests in 1610.999s
2019-10-17T09:12:18.140 INFO:tasks.cephfs_test_runner:
2019-10-17T09:12:18.140 INFO:tasks.cephfs_test_runner:FAILED (errors=1, skipped=1)
```

Not sure if it's expected that the module is disabled during upgrade testing at that point?

**Comment by smithfarm** [comment]
Ping. How can we move this PR forward?

Adding DNM for the meanwhile.

**Comment by smithfarm** [comment]
@jdurgin Do you still intend to work on this?

**Comment by jdurgin** [comment]
I haven't had time to work on this lately - if someone else would like to pick it up that would be great. I expect there are a few more tests that would need fixing.

**Comment by epuertat** [comment]
@jdurgin shall we close this one or is it worthy to get it merged?

**Comment by epuertat** [comment]
Let's close it, since Nautilus is long frozen.

**Pull request closed without merging**
