### PR TITLE
build: Make boost_url a list

### PR DESCRIPTION
**Pull request by adamemerson**
Cmake 3.29 does not appreciate a space separated string being substituted in.

https://tracker.ceph.com/issues/66598

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Review by cbodley — APPROVED** [review]
can you please push to ceph-ci to test for build regressions?

**Comment by cbodley** [comment]
from https://tracker.ceph.com/issues/66265#note-10 it sounds like https://github.com/ceph/ceph/pull/57581 may have passed qa. just waiting for:
> Either way I'll post the analysis of the rest of the failures so the other PRs can be merged.

**Comment by cbodley** [comment]
from https://jenkins.ceph.com/job/ceph-api/76479/
> AssertionError: timeout expired in wait_for_all_osds_up

**Comment by cbodley** [comment]
jenkins test api

**Review by kshtsk — APPROVED** [review]

**Comment by cbodley** [comment]
the fix merged in https://github.com/ceph/ceph/pull/57581, and i've prepared the quincy/reef/squid backports for https://tracker.ceph.com/issues/66598

**Pull request closed without merging**
