### PR TITLE
mimic: osd/PrimaryLogPG: handle object !exists in handle_watch_timeout

### PR DESCRIPTION
**Pull request by pdvian**
http://tracker.ceph.com/issues/38507

### CODE REVIEW

**Comment by smithfarm** [comment]
jenkins re-test this please

**Comment by smithfarm** [comment]
@xiexingguo Please don't add `needs-qa` and `mimic-batch-1` labels until the PR has passed "make check".

**Comment by xiexingguo** [comment]
@smithfarm Sorry and Ack :-(

**Comment by smithfarm** [comment]
jenkins test make check

**Comment by yuriw** [comment]
[wip-yuri3-testing-2019-04-29-1935-mimic](https://trello.com/c/1OdZ5zIb/598-wip-yuri3-testing-2019-04-29-1935-mimic)

**Comment by yuriw** [comment]
[wip-yuri4-testing-2019-04-30-1543-mimic](https://trello.com/c/A2lSYsdc/600-wip-yuri4-testing-2019-04-30-1543-mimic)

**Pull request merged**
