### PR TITLE
hammer: Wrong ceph get mdsmap assertion

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/14668

### CODE REVIEW

**Comment by smithfarm** [comment]
@dachary This looks like a simple fix - can it be squeezed into 0.94.6?

**Comment by smithfarm** [comment]
@gregsfortytwo This PR passed a cephfs integration run with two failures. Both failures are reproducible in both hammer-backports and hammer itself. One failure is due to http://tracker.ceph.com/issues/11258 ("cephfs-java ftruncate unit test failure") which is fixed in master, but the hammer backport is non-trivial. The second failure is probably an issue with some of the tests. For details, see http://tracker.ceph.com/issues/15895#note-21 

Do you think this PR can be merged?

**Comment by gregsfortytwo** [comment]
Yeah, looks fine to me. @jcsp got backports along with tech lead, though. :)

**Comment by smithfarm** [comment]
@gregsfortytwo Oh, OK. We tend to ask whoever merged the master PR.

**Comment by smithfarm** [comment]
@jcsp OK to merge this?

**Pull request merged**
