### PR TITLE
rocksdb: Upgrade rocksdb to latest facebook's v7.9.2

### PR DESCRIPTION
**Pull request by yanghonggang**
- RocksDB community has confirmed the bad performance when compacting in 6.x and fixed in 7.5.3
  * https://github.com/facebook/rocksdb/issues/9423
  * https://github.com/apache/incubator-kvrocks/pull/1056
- new features(e.g., wal compression)

Signed-off-by: Yang Honggang <yanghonggang_yewu@cmss.chinamobile.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [x] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by markhpc** [comment]
@yanghonggang very interesting!  We'll need to run through testing, but https://github.com/facebook/rocksdb/issues/9423 sounds like a good rationale to upgrade.

**Comment by ormandj** [comment]
@markhpc with https://github.com/ceph/ceph/pull/47221 merged, in light of our production findings, we would be very interested in this moving forward since it should address compaction performance impact which would be one of the downsides of the other patch (and continued progress in that regard).

**Comment by yanghonggang** [comment]
> It looks like 7.8.3 is out, and there have been some bugfixes since 7.7.3, so I do suggest that the PR be updated to reflect the newer version if we're going to spend the effort testing/validating safety/performance.

Upgrade rocksdb to latest v7.8.3.
@ormandj @markhpc

**Comment by markhpc** [comment]
@yanghonggang We discussed this at the performance meeting last week.  I think we definitely want to get this into testing for Reef.  We are still recovering from an infrastructure failure in the lab, but hopefully we can get this into testing soon.

**Review by markhpc — CHANGES_REQUESTED** [review]
@yanghonggang 

Unfortunately we can't switch over to RocksDB's repo.  We still need this commit for our builds to fix a bug that was introduced several years ago:

https://github.com/ceph/rocksdb/commit/6a2bb9473340846d75d32aa8f3eac91c744f92d8

That's why we've had to continue to use the custom versions in the ceph rocksdb repo.  We discussed dropping it at the perf meeting, but I think we still want to leave the fix in place for now.  Can you make a new branch with that commit applied based on the newest version and we can try switching to that?

Mark

**Comment by jianwei1216** [comment]
Looks like we still have the baggage of history, can't give up ceph/rocksdb

**Comment by yanghonggang** [comment]
> @yanghonggang
> 
> Unfortunately we can't switch over to RocksDB's repo. We still need this commit for our builds to fix a bug that was introduced several years ago:
> 
> [ceph/rocksdb@6a2bb94](https://github.com/ceph/rocksdb/commit/6a2bb9473340846d75d32aa8f3eac91c744f92d8)
> 
> That's why we've had to continue to use the custom versions in the ceph rocksdb repo. We discussed dropping it at the perf meeting, but I think we still want to leave the fix in place for now. Can you make a new branch with that commit applied based on the newest version and we can try switching to that?
> 
> Mark

@markhpc https://github.com/yanghonggang/rocksdb/tree/7.9.2.fb this is the new branch with [ceph/rocksdb@6a2bb94](https://github.com/ceph/rocksdb/commit/6a2bb9473340846d75d32aa8f3eac91c744f92d8) applied. But I don't know how to make a PR to create a new branch in ceph/rocksdb.

**Comment by jianwei1216** [comment]
```
1. git clone git@github.com:ceph/rocksdb.git
2. vim .git/config ==> url = git@github.com:facebook/rocksdb.git
3. git pull
4. git checkout v7.9.2
5. git checkout -b 7.9.2.fb
6. vim .git/config  ==> url = git@github.com:ceph/rocksdb.git
7. git push origin 7.9.2.fb:7.9.2.fb

error  :  
# git push origin 7.9.2.fb:7.9.2.fb 
ERROR: Permission to ceph/rocksdb.git denied to jianwei1216.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by jianwei1216** [comment]
Unable to push 7.9.2.fb branch to ceph/rocksdb

image

**Comment by jianwei1216** [comment]
Another way is to sync fork directly in ceph/rocksdb

55e2ee867cc6125a2c6963acd50c42c

**Comment by markhpc** [comment]
@jianwei1216 Let me see if I can find out who controls that repo and what the policy is

**Comment by markhpc** [comment]
@yanghonggang out of curiosity, does it work to fork the ceph rocksdb branch, make your own branch with the update from that one, and issue a pull request rather than trying to push a branch on the ceph rocksdb fork directly?

**Comment by yanghonggang** [comment]
>

**Comment by yanghonggang** [comment]
> @yanghonggang out of curiosity, does it work to fork the ceph rocksdb branch, make your own branch with the update from that one, and issue a pull request rather than trying to push a branch on the ceph rocksdb fork directly?


@markhpc 

In order to create a pull request, I have to specify a dest branch. But now all the existing ceph/rocksdb branches are not suitable. The ceph/rocksdb owner(or someone with privilege) can create a 7.9.2.fb branch, then I can create a pull request with [ceph/rocksdb@6a2bb94](https://github.com/ceph/rocksdb/commit/6a2bb9473340846d75d32aa8f3eac91c744f92d8) applied.

To create a 7.9.2.fb branch:

```text
/// $ cd ceph/rocksdb.git/
$ git remote add upstream https://github.com/facebook/rocksdb.git
$ git fetch upstream v7.9.2
$ git checkout -b 7.9.2.fb 444b3f4
$ git push origin 7.9.2.fb
```

**Comment by markhpc** [comment]
@yanghonggang ok, let me see what I can do.  Sorry for the slow responses, but I do really want to get this in for Reef (which now is delays for 3 months, so we have a little more breathing room).

**Comment by markhpc** [comment]
@rzarzynski  mentioned he can take a look as well as he has updated RocksDB via this method in the past as well.

**Comment by rzarzynski** [comment]
I think we should:

1. rebase (or perhaps cherry-pick) `c540de6f709b66efd41436694f72d6f7986a325b` (we really need it due to historic issues) on top of upstream v7.8.3.
2. Push such the branch to our RocksDB's fork.
3. Update the submodule in the `main` of `ceph.git`.

WIP.

**Comment by rzarzynski** [comment]
Just pushed https://github.com/ceph/rocksdb/tree/ceph-reef-v7.8.fb.
The cherry-pick commit is https://github.com/ceph/rocksdb/commit/97bc382f571ee9330d62ec00df9da3a0acf1829e.
Not tested yet.

**Comment by ormandj** [comment]
> Just pushed https://github.com/ceph/rocksdb/tree/ceph-reef-v7.8.fb. The cherry-pick commit is [ceph/rocksdb@97bc382](https://github.com/ceph/rocksdb/commit/97bc382f571ee9330d62ec00df9da3a0acf1829e). Not tested yet.

@rzarzynski is it possible to use the current upstream release, as this PR is quite old - the title just wasn't updated?: https://github.com/facebook/rocksdb/releases

7.9.2 is the current upstream release. Thank you for doing this!

**Comment by rzarzynski** [comment]
I took the previous one from the submodule update of the current commit (f615ccd8b9f5001941ae00ed275678c30464d244) in this PR.

Pushed https://github.com/ceph/rocksdb/tree/ceph-reef-v7.9.2.

**Comment by yanghonggang** [comment]
@rzarzynski thank you
@markhpc  pr is updated to use https://github.com/ceph/rocksdb/tree/ceph-reef-v7.9.2

```text
2023-02-13T15:39:07.444+0000 7fa1763ce640  4 rocksdb: RocksDB version: 7.9.2

2023-02-13T15:39:07.444+0000 7fa1763ce640  4 rocksdb: Git sha 473534bffa129e8f49e25c75020b0190d528572d
2023-02-13T15:39:07.444+0000 7fa1763ce640  4 rocksdb: Compile date 2018-08-21 21:47:48
2023-02-13T15:39:07.444+0000 7fa1763ce640  4 rocksdb: DB SUMMARY
```

**Comment by yanghonggang** [comment]
ping @markhpc

**Comment by markhpc** [comment]
@rzarzynski I hear you.  It's always scary doing these, but I think we've got to at least try given some of the fixes/improvements.

**Review by markhpc — APPROVED** [review]

**Comment by ljflores** [comment]
Hi @yanghonggang, we tested your PR in teuthology and found some failures that look related:

http://pulpito.ceph.com/lflores-2023-02-20_21:22:20-rados-wip-yuri-testing-2023-02-16-0839-distro-default-smithi/

/a/lflores-2023-02-20_21:22:20-rados-wip-yuri-testing-2023-02-16-0839-distro-default-smithi/7181478
/a/lflores-2023-02-20_21:22:20-rados-wip-yuri-testing-2023-02-16-0839-distro-default-smithi/7181480
/a/lflores-2023-02-20_21:22:20-rados-wip-yuri-testing-2023-02-16-0839-distro-default-smithi/7181483
/a/lflores-2023-02-20_21:22:20-rados-wip-yuri-testing-2023-02-16-0839-distro-default-smithi/7181485
/a/lflores-2023-02-20_21:22:20-rados-wip-yuri-testing-2023-02-16-0839-distro-default-smithi/7181488
/a/lflores-2023-02-20_21:22:20-rados-wip-yuri-testing-2023-02-16-0839-distro-default-smithi/7181498

These all show the same valgrind memory leak error:
```
<error>
  <unique>0x9455c16</unique>
  <tid>1</tid>
  <threadname>ceph-mon</threadname>
  <kind>Leak_StillReachable</kind>
  <xwhat>
    <text>8 bytes in 1 blocks are still reachable in loss record 3 of 173</text>
    <leakedbytes>8</leakedbytes>
    <leakedblocks>1</leakedblocks>
  </xwhat>
  <stack>
    <frame>
      <ip>0x4C38B6F</ip>
      <obj>/usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so</obj>
      <fn>operator new[](unsigned long)</fn>
      <dir>/builddir/build/BUILD/valgrind-3.19.0/coregrind/m_replacemalloc</dir>
      <file>vg_replace_malloc.c</file>
      <line>640</line>
    </frame>
    <frame>
      <ip>0x908F71</ip>
      <obj>/usr/bin/ceph-mon</obj>
      <fn>allocate</fn>
      <dir>/opt/rh/gcc-toolset-11/root/usr/include/c++/11/ext</dir>
      <file>new_allocator.h</file>
      <line>127</line>
    </frame>
    <frame>
      <ip>0x908F71</ip>
      <obj>/usr/bin/ceph-mon</obj>
      <fn>allocate</fn>
      <dir>/opt/rh/gcc-toolset-11/root/usr/include/c++/11/bits</dir>
      <file>alloc_traits.h</file>
      <line>464</line>
    </frame>
    <frame>
      <ip>0x908F71</ip>
      <obj>/usr/bin/ceph-mon</obj>
      <fn>_M_allocate</fn>
      <dir>/opt/rh/gcc-toolset-11/root/usr/include/c++/11/bits</dir>
      <file>stl_vector.h</file>
      <line>346</line>
    </frame>
    <frame>
      <ip>0x908F71</ip>
      <obj>/usr/bin/ceph-mon</obj>
      <fn>void std::vector&lt;std::unique_ptr&lt;rocksdb::ObjectLibrary::Entry, std::default_delete&lt;rocksdb::ObjectLibrary::Entry&gt; &gt;, std::allocator&lt;std::unique_ptr&lt;rocksdb::ObjectLibrary::Entry, std::default_delete&lt;rocksdb::ObjectLibrary::Entry&gt; &gt; &gt; &gt;::_M_realloc_insert&lt;std::unique_ptr&lt;rocksdb::ObjectLibrary::Entry, std::default_delete&lt;rocksdb::ObjectLibrary::Entry&gt; &gt; &gt;(__gnu_cxx::__normal_iterator&lt;std::unique_ptr&lt;rocksdb::ObjectLibrary::Entry, std::default_delete&lt;rocksdb::ObjectLibrary::Entry&gt; &gt;*, std::vector&lt;std::unique_ptr&lt;rocksdb::ObjectLibrary::Entry, std::default_delete&lt;rocksdb::ObjectLibrary::Entry&gt; &gt;, std::allocator&lt;std::unique_ptr&lt;rocksdb::ObjectLibrary::Entry, std::default_delete&lt;rocksdb::ObjectLibrary::Entry&gt; &gt; &gt; &gt; &gt;, std::unique_ptr&lt;rocksdb::ObjectLibrary::Entry, std::default_delete&lt;rocksdb::ObjectLibrary::Entry&gt; &gt;&amp;&amp;)</fn>
      <dir>/opt/rh/gcc-toolset-11/root/usr/include/c++/11/bits</dir>
      <file>vector.tcc</file>
      <line>440</line>
    </frame>
    <frame>
      <ip>0xA2D64E</ip>
      <obj>/usr/bin/ceph-mon</obj>
      <fn>std::once_flag::_Prepare_execution::_Prepare_execution&lt;std::call_once&lt;rocksdb::FileChecksumGenFactory::CreateFromString(rocksdb::ConfigOptions const&amp;, std::__cxx11::basic_string&lt;char, std::char_traits&lt;char&gt;, std::allocator&lt;char&gt; &gt; const&amp;, std::shared_ptr&lt;rocksdb::FileChecksumGenFactory&gt;*)::{lambda()#1}&gt;(std::once_flag&amp;, rocksdb::FileChecksumGenFactory::CreateFromString(rocksdb::ConfigOptions const&amp;, std::__cxx11::basic_string&lt;char, std::char_traits&lt;char&gt;, std::allocator&lt;char&gt; &gt; const&amp;, std::shared_ptr&lt;rocksdb::FileChecksumGenFactory&gt;*)::{lambda()#1}&amp;&amp;)::{lambda()#1}&gt;(rocksdb::FileChecksumGenFactory::CreateFromString(rocksdb::ConfigOptions const&amp;, std::__cxx11::basic_string&lt;char, std::char_traits&lt;char&gt;, std::allocator&lt;char&gt; &gt; const&amp;, std::shared_ptr&lt;rocksdb::FileChecksumGenFactory&gt;*)::{lambda()#1}&amp;)::{lambda()#1}::_FUN()</fn>
      <dir>/opt/rh/gcc-toolset-11/root/usr/include/c++/11/bits</dir>
      <file>vector.tcc</file>
      <line>121</line>
    </frame>
    <frame>
      <ip>0x7DD8E66</ip>
      <obj>/usr/lib64/libpthread-2.28.so</obj>
      <fn>__pthread_once_slow</fn>
    </frame>
    <frame>
      <ip>0xA2D9A0</ip>
      <obj>/usr/bin/ceph-mon</obj>
      <fn>UnknownInlinedFun</fn>
      <dir>/opt/rh/gcc-toolset-11/root/usr/include/c++/11/x86_64-redhat-linux/bits</dir>
      <file>gthr-default.h</file>
      <line>700</line>
    </frame>
    <frame>
      <ip>0xA2D9A0</ip>
      <obj>/usr/bin/ceph-mon</obj>
      <fn>call_once&lt;rocksdb::FileChecksumGenFactory::CreateFromString(const rocksdb::ConfigOptions&amp;, const string&amp;, std::shared_ptr&lt;rocksdb::FileChecksumGenFactory&gt;*)::&lt;lambda()&gt; &gt;</fn>
      <dir>/opt/rh/gcc-toolset-11/root/usr/include/c++/11</dir>
      <file>mutex</file>
      <line>783</line>
    </frame>
    <frame>
      <ip>0xA2D9A0</ip>
      <obj>/usr/bin/ceph-mon</obj>
      <fn>rocksdb::FileChecksumGenFactory::CreateFromString(rocksdb::ConfigOptions const&amp;, std::__cxx11::basic_string&lt;char, std::char_traits&lt;char&gt;, std::allocator&lt;char&gt; &gt; const&amp;, std::shared_ptr&lt;rocksdb::FileChecksumGenFactory&gt;*)</fn>
      <dir>/usr/src/debug/ceph-18.0.0-2342.g35d33aea.el8.x86_64/src/rocksdb/util</dir>
      <file>file_checksum_helper.cc</file>
      <line>159</line>
    </frame>
    <frame>
      <ip>0x96A452</ip>
      <obj>/usr/bin/ceph-mon</obj>
      <fn>operator()</fn>
      <dir>/usr/src/debug/ceph-18.0.0-2342.g35d33aea.el8.x86_64/src/rocksdb/include/rocksdb/utilities</dir>
      <file>options_type.h</file>
      <line>495</line>
    </frame>
    <frame>
      <ip>0x96A452</ip>
      <obj>/usr/bin/ceph-mon</obj>
      <fn>__invoke_impl&lt;rocksdb::Status, rocksdb::OptionTypeInfo::AsCustomSharedPtr&lt;rocksdb::FileChecksumGenFactory&gt;(int, rocksdb::OptionVerificationType, rocksdb::OptionTypeFlags)::&lt;lambda(const rocksdb::ConfigOptions&amp;, const string&amp;, const string&amp;, void*)&gt;&amp;, const rocksdb::ConfigOptions&amp;, const std::__cxx11::basic_string&lt;char, std::char_traits&lt;char&gt;, std::allocator&lt;char&gt; &gt;&amp;, const std::__cxx11::basic_string&lt;char, std::char_traits&lt;char&gt;, std::allocator&lt;char&gt; &gt;&amp;, void*&gt;</fn>
      <dir>/opt/rh/gcc-toolset-11/root/usr/include/c++/11/bits</dir>
      <file>invoke.h</file>
      <line>61</line>
    </frame>
    <frame>
      <ip>0x96A452</ip>
      <obj>/usr/bin/ceph-mon</obj>
      <fn>__invoke_r&lt;rocksdb::Status, rocksdb::OptionTypeInfo::AsCustomSharedPtr&lt;rocksdb::FileChecksumGenFactory&gt;(int, rocksdb::OptionVerificationType, rocksdb::OptionTypeFlags)::&lt;lambda(const rocksdb::ConfigOptions&amp;, const string&amp;, const string&amp;, void*)&gt;&amp;, const rocksdb::ConfigOptions&amp;, const std::__cxx11::basic_string&lt;char, std::char_traits&lt;char&gt;, std::allocator&lt;char&gt; &gt;&amp;, const std::__cxx11::basic_string&lt;char, std::char_traits&lt;char&gt;, std::allocator&lt;char&gt; &gt;&amp;, void*&gt;</fn>
      <dir>/opt/rh/gcc-toolset-11/root/usr/include/c++/11/bits</dir>
      <file>invoke.h</file>
      <line>116</line>
    </frame>
    <frame>
      <ip>0x96A452</ip>
      <obj>/usr/bin/ceph-mon</obj>
      <fn>std::_Function_handler&lt;rocksdb::Status (rocksdb::ConfigOptions const&amp;, std::__cxx11::basic_string&lt;char, std::char_traits&lt;char&gt;, std::allocator&lt;char&gt; &gt; const&amp;, std::__cxx11::basic_string&lt;char, std::char_traits&lt;char&gt;, std::allocator&lt;char&gt; &gt; const&amp;, void*), rocksdb::OptionTypeInfo::AsCustomSharedPtr&lt;rocksdb::FileChecksumGenFactory&gt;(int, rocksdb::OptionVerificationType, rocksdb::OptionTypeFlags)::{lambda(rocksdb::ConfigOptions const&amp;, std::__cxx11::basic_string&lt;char, std::char_traits&lt;char&gt;, std::allocator&lt;char&gt; &gt; const&amp;, std::__cxx11::basic_string&lt;char, std::char_traits&lt;char&gt;, std::allocator&lt;char&gt; &gt; const&amp;, void*)#1}&gt;::_M_invoke(std::_Any_data const&amp;, rocksdb::ConfigOptions const&amp;, std::__cxx11::basic_string&lt;char, std::char_traits&lt;char&gt;, std::allocator&lt;char&gt; &gt; const&amp;, std::__cxx11::basic_string&lt;char, std::char_traits&lt;char&gt;, std::allocator&lt;char&gt; &gt; const&amp;, void*&amp;&amp;)</fn>
      <dir>/opt/rh/gcc-toolset-11/root/usr/include/c++/11/bits</dir>
      <file>std_function.h</file>
      <line>291</line>
    </frame>
    <frame>
      <ip>0x9814A3</ip>
      <obj>/usr/bin/ceph-mon</obj>
      <fn>operator()</fn>
      <dir>/opt/rh/gcc-toolset-11/root/usr/include/c++/11/bits</dir>
      <file>std_function.h</file>
      <line>590</line>
    </frame>
    <frame>
      <ip>0x9814A3</ip>
      <obj>/usr/bin/ceph-mon</obj>
      <fn>rocksdb::OptionTypeInfo::Parse(rocksdb::ConfigOptions const&amp;, std::__cxx11::basic_string&lt;char, std::char_traits&lt;char&gt;, std::allocator&lt;char&gt; &gt; const&amp;, std::__cxx11::basic_string&lt;char, std::char_traits&lt;char&gt;, std::allocator&lt;char&gt; &gt; const&amp;, void*) const</fn>
      <dir>/usr/src/debug/ceph-18.0.0-2342.g35d33aea.el8.x86_64/src/rocksdb/options</dir>
      <file>options_helper.cc</file>
      <line>938</line>
    </frame>
    <frame>
      <ip>0x9622DC</ip>
      <obj>/usr/bin/ceph-mon</obj>
      <fn>rocksdb::Configurable::ParseOption(rocksdb::ConfigOptions const&amp;, rocksdb::OptionTypeInfo const&amp;, std::__cxx11::basic_string&lt;char, std::char_traits&lt;char&gt;, std::allocator&lt;char&gt; &gt; const&amp;, std::__cxx11::basic_string&lt;char, std::char_traits&lt;char&gt;, std::allocator&lt;char&gt; &gt; const&amp;, void*)</fn>
      <dir>/usr/src/debug/ceph-18.0.0-2342.g35d33aea.el8.x86_64/src/rocksdb/options</dir>
      <file>configurable.cc</file>
      <line>251</line>
    </frame>
```

Take a look and see what you think. @markhpc FYI

**Comment by ljflores** [comment]
@markhpc @rzarzynski I reran the same tests that failed without this PR, and they passed. Just wanted to confirm with you guys that this PR is solely responsible.
http://pulpito.front.sepia.ceph.com/lflores-2023-02-23_17:54:36-rados-wip-yuri-testing-2023-02-22-2037-distro-default-smithi/

**Comment by ljflores** [comment]
Rados suite review: http://pulpito.front.sepia.ceph.com/?branch=wip-yuri-testing-2023-02-16-0839

Some failures were related to https://github.com/ceph/ceph/pull/49006, but were fixed locally due to lab issues.

Failures, unrelated:
   1. https://tracker.ceph.com/issues/58585
   2. https://tracker.ceph.com/issues/58560
   3. https://tracker.ceph.com/issues/58496
   4. https://tracker.ceph.com/issues/49961
   5. https://tracker.ceph.com/issues/58861
   6. https://tracker.ceph.com/issues/58797
   7. https://tracker.ceph.com/issues/49428

Details:
   1. rook: failed to pull kubelet image - Ceph - Orchestrator
   2. test_envlibrados_for_rocksdb.sh failed to subscribe to repo - Infrastructure
   3. osd/PeeringState: FAILED ceph_assert(!acting_recovery_backfill.empty()) - Ceph - RADOS
   4. scrub/osd-recovery-scrub.sh: TEST_recovery_scrub_1 failed - Ceph - RADOS
   5. OSError: cephadm config file not found - Ceph - Orchestrator
   6. scrub/osd-scrub-dump.sh: TEST_recover_unexpected fails from "ERROR: Unexpectedly low amount of scrub reservations seen during test" - Ceph - RADOS
   7. ceph_test_rados_api_snapshots fails with "rados_mon_command osd pool create failed with error -22" - Ceph - RADOS

**Pull request merged**
