### PR TITLE
test/librbd: improve TestLibRBD.QuiesceWatchTimeout

### PR DESCRIPTION
**Pull request by trociny**
On teuthology 13 sec timeout was not always enough for
rbd_quiesce_notification_attempts = 2: if a socket failure is
injected after quiesce notification is sent the request is resent
and the notifier timeout (and as a result the next notification
attempt) is delayed.

Signed-off-by: Mykola Golub <mgolub@suse.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by dillaman** [comment]
(test failure tied to #35074)

**Comment by dillaman** [comment]
jenkins test make check

**Comment by dillaman** [comment]
Hmm -- looks like this still periodically fails w/ -ETIMEDOUT on `snap_create`. If the `ASSERT_EQ` fails, it leads to a crash since the `quiesceXYZ` thread hasn't been joined prior to the test aborting.

> 2020-05-28T01:56:37.837 INFO:tasks.workunit.client.0.smithi174.stdout:Expected equality of these values:
> 2020-05-28T01:56:37.838 INFO:tasks.workunit.client.0.smithi174.stdout:  -110
> 2020-05-28T01:56:37.838 INFO:tasks.workunit.client.0.smithi174.stdout:  image.snap_create("snap2")
> 2020-05-28T01:56:37.838 INFO:tasks.workunit.client.0.smithi174.stdout:    Which is: 0

http://qa-proxy.ceph.com/teuthology/jdillaman-2020-05-27_21:29:06-rbd-wip-jd-testing-distro-basic-smithi/5097410/teuthology.log

**Comment by trociny** [comment]
@dillaman Thanks. I will look at it.

**Comment by trociny** [comment]
@dillaman It looks like it failed for the branch (sha1: 9e29f0ba0b905ec7cfcbca33bf15148d512b1f3e) that does not include this fix?

**Comment by dillaman** [comment]
> @dillaman It looks like it failed for the branch (sha1: 9e29f0ba0b905ec7cfcbca33bf15148d512b1f3e) that does not include this fix?

Odd -- I thought it was fully rebased but perhaps not. I'll rebase and retest. Sorry for the noise in the interim.

**Comment by trociny** [comment]
And yes, I think the new version is going to crash too if the snap_create test fails due to not joined thread. Do you think it is worth improving this too? I suppose replacing all `ASSERT_*` between the thread spawn and join with `EXPECT_*` should do the trick.

**Pull request merged**
