### PR TITLE
jewel: rbd: rbd-mirror: failover and failback of unmodified image results in split-brain

### PR DESCRIPTION
**Pull request by dillaman**
http://tracker.ceph.com/issues/19873

### CODE REVIEW

**Comment by smithfarm** [comment]
Jenkins re-test this please

**Comment by smithfarm** [comment]
The following three rbd-related PRs were included in a recent jewel integration branch:

* https://github.com/ceph/ceph/pull/14663
* https://github.com/ceph/ceph/pull/14874
* https://github.com/ceph/ceph/pull/14977

An rbd suite was run on said branch, and it failed rather spectacularly: http://pulpito.front.sepia.ceph.com/smithfarm-2017-08-21_20:07:45-rbd-wip-jewel-backports-distro-basic-smithi/

@dillaman Could you rebase/repush `wip-19873-jewel` to ceph-ci? I'll run an rbd suite on this single PR. Or do you have another suggestion?

**Comment by dillaman** [comment]
@smithfarm https://shaman.ceph.com/builds/ceph/wip-19873-jewel/

**Comment by smithfarm** [comment]
@dillaman Thanks. Now that luminous testing got underway again, I'm no longer doing runs for individual PRs. This PR was included in this run, which is exhibiting a new failure: http://pulpito.ceph.com/smithfarm-2017-08-24_15:58:59-rbd-wip-jewel-backports-distro-basic-smithi/

**Comment by trociny** [comment]
The teuthology failures do not look related.

**Comment by smithfarm** [comment]
@dillaman This passed an rbd suite at http://tracker.ceph.com/issues/20613#note-22 and a rados suite at http://tracker.ceph.com/issues/20613#note-20

Please review.

**Pull request merged**
