### PR TITLE
luminous: rgw: LC: handle resharded buckets

### PR DESCRIPTION
**Pull request by taodd**
backport tracker: https://tracker.ceph.com/issues/38884

---

partial backport of #26564
parent tracker https://tracker.ceph.com/issues/36512

Backport rationale:

Since it's almost not possible to backport the entire PR #26564. The dependencies make it difficult and not proper to back port all of them. 
I only backported the 2 commits that fixes the lifecycle not taking effect after resharding.
I think this is the main pain for ceph user, as you can't expect lifecycle to work with dynamic resharding enabled. 

The other part of  PR #26564, is about adding a command to radosgw-admin "radosgw-admin lc reshard fix" which can re-add the lifecycle to the old bucket. 
This part is not proper for backport. 
And user can always reset their lifecycle to the old bucket via commands like "s3cmd setlifecycle" as a workaround.  I think we can leave this part for now.

### CODE REVIEW

**Comment by taodd** [comment]
I've tested with these two commits, it works good. 
the resharded bucket won't lose its lifecycle

**Comment by taodd** [comment]
@smithfarm  thank you so much for the review and note. I've changed the commit message now. 
please help to take a look. thx !

**Comment by smithfarm** [comment]
@cbodley @theanalyst This is a minimal backport of #26564 - does it look OK to begin integration testing?

**Comment by smithfarm** [comment]
@cbodley @theanalyst Ping - see https://github.com/ceph/ceph/pull/29122#issuecomment-537007161

**Comment by taodd** [comment]
@smithfarm @cbodley @theanalyst could you please take a review for this. Without this patch, you can't expect lifecycle to work when dynamic resharding enabled in luminous,  this is a critical issue for luminous.

**Comment by taodd** [comment]
@smithfarm It's now approved, is it ok start the testing ?
 It would be great if this can be available at 12.2.13.

**Comment by yuriw** [comment]
[wip-yuri2-testing-2019-11-18-1527-luminous](https://trello.com/c/mroVe20D/767-wip-yuri2-testing-2019-11-18-1527-luminous)

**Pull request merged**
