### PR TITLE
mgr/status: fix 'ceph fs status' AttributeError

### PR DESCRIPTION
**Pull request by gmayyyha**
Signed-off-by: Yanhu Cao <gmayyyha@gmail.com>

- [x] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by gmayyyha** [comment]
> Please create a [tracker issue](https://tracker.ceph.com/) so that this issue can be tracked for backporting.
> 
> Then, please annotate the commit which fixes/resolves a Ceph tracker issue with:
> 
> `Fixes: http://tracker.ceph.com/issues/...`
> 
> This is essential when examining the history of the repository (this commit fixes what) and helps merge scripts identify issues that have been resolved by a merge.

@batrick done.

**Comment by sebastian-philipp** [comment]
I don't think this needs backporting. Mimic should not be affected by this.

Anyway. this is a type error that should never have been gone undetected. It's typically the job of the type checker to find those. Unfortunately, this specific error didn't popped up in my #26715

Is this code executed in any QA or make check test?

**Comment by batrick** [comment]
> I don't think this needs backporting. Mimic should not be affected by this.

That's good to know but generally we try to make tracker tickets for any bug so that it helps the PTL consider whether it needs to be backported before marking the issue resolved.

**Comment by sebastian-philipp** [comment]
http://tracker.ceph.com/issues/38122

**Comment by batrick** [comment]
@gmayyyha sorry, the issue already existed. Please change your commit message to cite this ticket: http://tracker.ceph.com/issues/38122

**Comment by gmayyyha** [comment]
> @gmayyyha sorry, the issue already existed. Please change your commit message to cite this ticket: http://tracker.ceph.com/issues/38122

updated.

**Pull request merged**
