### PR TITLE
pacific: mgr/cephadm: iscsi username and password defaults to admin

### PR DESCRIPTION
**Pull request by adk3798**
backport tracker: https://tracker.ceph.com/issues/58203

---

backport of https://github.com/ceph/ceph/pull/48304
parent tracker: https://tracker.ceph.com/issues/57730

this backport was staged using ceph-backport.sh version 16.0.0.6848
find the latest version at https://github.com/ceph/ceph/blob/main/src/script/ceph-backport.sh

### CODE REVIEW

**Review by nizamial09 — APPROVED** [review]

**Comment by adk3798** [comment]
jenkins retest this please

**Comment by adk3798** [comment]
jenkins test api

**Comment by adk3798** [comment]
jenkins test make check

**Comment by adk3798** [comment]
jenkins test dashboard

**Pull request merged**
