### PR TITLE
client: add option to control how directory size is calculated

### PR DESCRIPTION
**Pull request by ukernel**
"recursive size" VS "number of entries"

Signed-off-by: Yan, Zheng <zyan@redhat.com>

### CODE REVIEW

**Comment by ukernel** [comment]
tested by running following commands

tar -xzf ~/linux-doc.tar.gz  ; sync ; tar c linux/Documentation/ >/dev/null; 

when client_dirsize_rbytes is true, there are errors like:

tar: linux/Documentation/i2c: file changed as we read it

when client_dirsize_rbytes is false, there is no error:

**Comment by jcsp** [comment]
If this is otherwise going to get spurious warnings on `tar`, we should think about making the number of dentries the default.  Most users probably won't change this setting.

Having the rbytes in ls output is a nice party trick, but I don't know if many people will really miss it?

**Comment by gregsfortytwo** [comment]
@ukernel, can you write a qa-suite test that covers the tar issue?

**Comment by gregsfortytwo** [comment]
Does outputting the number of dentries get us much of anything, rather than just providing a standard 4KB or whatever?

**Comment by ukernel** [comment]
On Wed, Jan 27, 2016 at 2:25 AM, Gregory Farnum <notifications@github.com>
wrote:

> Does outputting the number of dentries get us much of anything, rather
> than just providing a standard 4KB or whatever?
>
> —
>
I think there is a standard for directory size. extN is blocks used by the
directory. btrfs is sum of dentry name length.

**Comment by gregsfortytwo** [comment]
@liewegas, do you have any objections to changing this default?

@ukernel, I'd like to see us expose our rstats to users somehow. The most obvious way is through another virtual xattr.

**Comment by liewegas** [comment]
it makes me sad :(.  having the dir size be the rsize is one of the more 
compelling features of cephfs, imo.  the problem is that it changes 
shortly after it's written i guess?  the client update behavior around 
nestlock is all sloppy, unfortunately.  :(

btw the rstats are already exposed via a virtual xattr.

**Comment by gregsfortytwo** [comment]
Oh duh re: xattr.

It makes me sad too. :( For most applications (obviously, given we haven't encountered this issue before) it's fine, but tar keeps noticing changing sizes and thinks the data has changed out from underneath it. I suppose if we either made rstats synchronous on the client (yeah, right) or else figured out how to detect a workload that cares and then avoid changing them for userspace until the workload had ended...yuck.

**Comment by liewegas** [comment]
hmm, it's possible to ensure that this trivial workload (single client 
writing out files/dirs) isn't getting synchronous updates.

**Comment by liewegas** [comment]
btw we should definitely add this option (pretty sure it exists on the 
kernel client already), my only complaint is the change of default.

**Comment by gregsfortytwo** [comment]
> hmm, it's possible to ensure that this trivial workload (single client
> writing out files/dirs) isn't getting synchronous updates.

No, it's when tarring data up, not untarring it. The artificial
example we have is a user untarring something and then immediately
generating a new tarball from it, but one can envision other scenarios
like, say, compiling and then trying to tar up the output.

**Comment by liewegas** [comment]
this really seems like a tar bug... it shouldn't care about a size change 
on a directory.

it's just a warning, right?

**Comment by gregsfortytwo** [comment]
On Tue, Feb 2, 2016 at 10:43 AM, Sage Weil <notifications@github.com> wrote:
>
> this really seems like a tar bug... it shouldn't care about a size change
> on a directory.
>
> it's just a warning, right?

Mmm, I suppose it is. Nobody else has run across this so maybe we're
okay just giving them their own option for now.

**Comment by gregsfortytwo** [comment]
Okay, I ran http://pulpito.ceph.com/gregf-2016-02-17_22:30:22-fs-greg-pr-7323---basic-mira/ *without* my changes to the config default and moving this workunit into a "norstats" directory, and everything except for the (obviously missing) norstats test passed.

Then I fixed that and ran it through again (http://pulpito.ceph.com/gregf-2016-02-18_09:42:57-fs-greg-pr-7323---basic-mira/). The norstats tests passed, and the two failures were valgrind noise in the Objecter and a networking issue.

So all-in-all, I'm feeling pretty good about the code. ;)

**Pull request merged**
