### PR TITLE
rgw:add a s3 API of make torrent for a object

### PR DESCRIPTION
**Pull request by zhouruisong**
When you execute the command gettorrent of a object, a torrent file will be produced and returned.
The torrent also will be save into a pool named default.rgw.torrent.
If the torrent of a object exists in default.rgw.torrent, it will be returned.

Signed-off-by: zhouruisong <236131368@qq.com>

### CODE REVIEW

**Comment by zhouruisong** [comment]
@dang
#9589
this PR is closed and has some problem. I create a new PR, please merge this PR. thanks!

**Comment by dang** [comment]
@zhouruisong Sorry, one more rebase.  The lifecycle merge caused a conflict.

**Comment by dang** [comment]
In addition, rgw_torrent.cc needs to be added to rgw_a_srcs in src/rgw/CMakeLists.txt

**Comment by zhouruisong** [comment]
@dang What do you mean about adding to rgw_a_srcs in src/rgw/CMakeLists.txt? Is like this:

add_executable(ceph_rgw_multiparser
  rgw_multiparser.cc
  **rgw_torrent.cc**)
target_link_libraries(ceph_rgw_multiparser
  rgw_a
  global)

install(TARGETS
  ceph_rgw_jsonparser
  ceph_rgw_multiparser
  DESTINATION bin)

**Comment by zhouruisong** [comment]
@dang 
I have update my code, please merge again,thanks!

**Comment by zhouruisong** [comment]
@dang 
please merge again， thanks！

**Pull request merged**
