### PR TITLE
hammer: Linking to -lrbd causes process startup times to balloon

### PR DESCRIPTION
**Pull request by Vicente-Cheng**
http://tracker.ceph.com/issues/15360

### CODE REVIEW

**Comment by badone** [comment]
lgtm

**Comment by yuyuyu101** [comment]
test/perf_local.cc
test/msgr/perf_msgr_client.cc?

**Comment by yuyuyu101** [comment]
lgtm

**Comment by Vicente-Cheng** [comment]
@badone @yuyuyu101 
thanks for review : )

**Comment by smithfarm** [comment]
@jdurgin This passed an rbd suite - see http://tracker.ceph.com/issues/15895#note-2 for details. Do you think it's OK to merge?

The master commit is 1c2831a2c1277c69f9649200d74a75c04a4b0296 - it does not have a PR but it looks like you merged it, that's why I'm asking you.

**Comment by jdurgin** [comment]
lgtm

**Pull request merged**
