### PR TITLE
ceph-disk: ceph-disk list fails on /dev/cciss!c0d0

### PR DESCRIPTION
**Pull request by dachary**
http://tracker.ceph.com/issues/13970

### CODE REVIEW

**Comment by dachary** [comment]
Passed the ceph-disk suite on ubuntu infernalis because http://tracker.ceph.com/issues/13988 breaks the ceph-disk suite on master. 

* *pass*

**Comment by dachary** [comment]
<pre>
teuthology-openstack --verbose --key-filename ~/Downloads/myself --key-name myself --teuthology-git-url http://github.com/dachary/teuthology --teuthology-branch wip-suite --ceph-qa-suite-git-url http://github.com/ceph/ceph-qa-suite --suite-branch master --ceph-git-url http://github.com/dachary/ceph --ceph wip-13970-ceph-disk-cciss --suite ceph-disk --filter ubuntu_14.04
</pre>

* *running*

**Comment by dachary** [comment]
<pre>
cw ceph-qa-suite --verbose --ceph-qa-suite-git-url http://github.com/ceph/ceph-qa-suite --suite-branch master --ceph-git-url http://github.com/dachary/ceph --ceph wip-13970-ceph-disk-cciss --suite ceph-disk --upload
</pre>

* *running* http://167.114.238.126:8081/ubuntu-2016-01-04_14:48:20-ceph-disk-wip-13970-ceph-disk-cciss---basic-openstack/

**Comment by dachary** [comment]
<pre>
cw ceph-qa-suite --verbose --ceph-qa-suite-git-url http://github.com/ceph/ceph-qa-suite --suite-branch master --ceph-git-url http://github.com/dachary/ceph --ceph wip-13970-ceph-disk-cciss --suite ceph-disk --upload
</pre>

* *pass* http://167.114.238.126:8081/ubuntu-2016-01-06_13:04:03-ceph-disk-wip-13970-ceph-disk-cciss---basic-openstack/

**Comment by dachary** [comment]
@liewegas it passes the ceph-disk suite ( http://teuthology-logs.public.ceph.com/ubuntu-2016-01-06_13%3a04%3a03-ceph-disk-wip-13970-ceph-disk-cciss---basic-openstack/ ) and fixes a few stability issues (that show up frequently during testing but are probably rare in reality).

**Comment by liewegas** [comment]
:+1:

**Pull request merged**
