### PR TITLE
osd: do monitor report without holding the osd_lock

### PR DESCRIPTION
**Pull request by guangyy**
Fixes:12722
Guang Yang <yguang@yahoo-inc.com>

### CODE REVIEW

**Comment by liewegas** [comment]
Oh bother, this conflicts with the wip-bigbang scaling fixing I'm doing--I wish I'd noticed this earlier.

**Comment by guangyy** [comment]
Hi @liewegas , thanks for the heads up. Should I rebase against wip-bigbang now to proceed? Or wait until that one is merged?

**Comment by liewegas** [comment]
On Fri, 18 Sep 2015, Guang Yang wrote:
> Hi @liewegas , thanks for the heads up. Should I rebase against wip-bigbang now to proceed? Or wait until that one is merged?

It will take a while to merge, but rebasing on top of that would be great.  

A ton of this stuff is using osd_lock and I'm pretty sure almost none of 
it needs to, so switching it to map_lock.get_read() or whatever would be 
great!

**Comment by guangyy** [comment]
@liewegas , sure, I will do that. Thanks!

**Comment by guangyy** [comment]
Hi @liewegas  @jecluis , rebased against the wip-bigbang branch, please help to review again. Thanks!

**Comment by tchaikov** [comment]
@guangyy only reviewed your commit, lgtm.

**Comment by guangyy** [comment]
Hi @liewegas , rebased according to latest wip-bigbang, and add one more change to make testing pass. Please help to review. Thanks.

**Comment by liewegas** [comment]
merged this manually into wip-bigbang

**Pull request closed without merging**
