### PR TITLE
mimic: tests: qa/tasks/ceph.py: pass cluster_name to get_mons

### PR DESCRIPTION
**Pull request by smithfarm**
Fixes: 276c2b80fd9ce58c5249001bfc98fd84249782cb
Fixes: https://tracker.ceph.com/issues/42658
Signed-off-by: Nathan Cutler <ncutler@suse.com>

### CODE REVIEW

**Comment by smithfarm** [comment]
@yuriw This is needed for mimic v13.2.7 but please wait for @dillaman to review.

**Comment by smithfarm** [comment]
@yuriw This is needed for mimic v13.2.7 but please wait for @dillaman to review.

**Comment by dillaman** [comment]
this can be quickly verified using the RBD suite and filtered by "rbd-mirror"

**Comment by smithfarm** [comment]
`teuthology-suite -k distro --priority 50 --suite rbd --email ncutler@suse.cz --ceph-repo https://github.com/ceph/ceph.git --ceph mimic --newest 10 --machine-type smithi --suite-repo https://github.com/smithfarm/ceph.git --suite-branch wip-fix-get-mons-mimic --filter 'rbd-mirror'`

**running** http://pulpito.ceph.com/smithfarm-2019-11-05_18:20:42-rbd-mimic-distro-basic-smithi/

**Comment by smithfarm** [comment]
The test run fails with:

```
2019-11-05T18:32:18.137 INFO:teuthology.orchestra.run.smithi067:> sudo ceph --cluster cluster1 osd crush tunables default
2019-11-05T18:32:18.198 INFO:tasks.ceph.cluster1.mon.a.smithi067.stderr:2019-11-05 18:32:18.199 7f20c0db0a80 -1 no public_addr or public_network specified, and mon.a not present in monmap or ceph.conf
```

**Comment by smithfarm** [comment]
`teuthology-suite -k distro --priority 50 --suite rbd --email ncutler@suse.cz --ceph-repo https://github.com/ceph/ceph.git --ceph mimic --newest 10 --machine-type smithi --suite-repo https://github.com/smithfarm/ceph.git --suite-branch wip-fix-get-mons-mimic --filter 'rbd-mirror' --limit 1`

**running** http://pulpito.ceph.com/smithfarm-2019-11-06_07:08:34-rbd-mimic-distro-basic-smithi/

**Comment by smithfarm** [comment]
from a passing nautilus rbd-mirror test:

```
2019-11-01T21:29:52.906 INFO:teuthology.orchestra.run.smithi152:> adjust-ulimits ceph-coverage /home/ubuntu/cephtest/archive/coverage monmaptool --create --clobber --enable-all-features --add a 172.21.15.152 --print /home/ubuntu/cephtest/cluster1.monmap
2019-11-01T21:29:53.016 INFO:teuthology.orchestra.run.smithi152.stdout:monmaptool: monmap file /home/ubuntu/cephtest/cluster1.monmap
2019-11-01T21:29:53.017 INFO:teuthology.orchestra.run.smithi152.stdout:monmaptool: generated fsid 0e1baa7c-bce7-4566-9f8a-f9edeb2ce597
2019-11-01T21:29:53.017 INFO:teuthology.orchestra.run.smithi152.stdout:epoch 0
2019-11-01T21:29:53.017 INFO:teuthology.orchestra.run.smithi152.stdout:fsid 0e1baa7c-bce7-4566-9f8a-f9edeb2ce597
2019-11-01T21:29:53.018 INFO:teuthology.orchestra.run.smithi152.stdout:last_changed 2019-11-01 21:29:53.016242
2019-11-01T21:29:53.018 INFO:teuthology.orchestra.run.smithi152.stdout:created 2019-11-01 21:29:53.016242
2019-11-01T21:29:53.019 INFO:teuthology.orchestra.run.smithi152.stdout:min_mon_release 0 (unknown)
2019-11-01T21:29:53.019 INFO:teuthology.orchestra.run.smithi152.stdout:0: [v2:172.21.15.152:3300/0,v1:172.21.15.152:6789/0] mon.a
2019-11-01T21:29:53.019 INFO:teuthology.orchestra.run.smithi152.stdout:monmaptool: writing epoch 0 to /home/ubuntu/cephtest/cluster1.monmap (1 monitors)
```

from a failing mimic rbd-mirror test case:

```
2019-11-06T07:37:53.035 INFO:teuthology.orchestra.run.smithi095:> adjust-ulimits ceph-coverage /home/ubuntu/cephtest/archive/coverage monmaptool --create --clobber --print /home/ubuntu/cephtest/cluster1.monmap
2019-11-06T07:37:53.128 INFO:teuthology.orchestra.run.smithi095.stdout:monmaptool: monmap file /home/ubuntu/cephtest/cluster1.monmap
2019-11-06T07:37:53.128 INFO:teuthology.orchestra.run.smithi095.stdout:monmaptool: generated fsid 322c49ab-da33-47ed-b34f-b553ffcd3db4
2019-11-06T07:37:53.128 INFO:teuthology.orchestra.run.smithi095.stdout:epoch 0
2019-11-06T07:37:53.129 INFO:teuthology.orchestra.run.smithi095.stdout:fsid 322c49ab-da33-47ed-b34f-b553ffcd3db4
2019-11-06T07:37:53.129 INFO:teuthology.orchestra.run.smithi095.stdout:last_changed 2019-11-06 07:37:53.128852
2019-11-06T07:37:53.129 INFO:teuthology.orchestra.run.smithi095.stdout:created 2019-11-06 07:37:53.128852
2019-11-06T07:37:53.129 INFO:teuthology.orchestra.run.smithi095.stdout:monmaptool: writing epoch 0 to /home/ubuntu/cephtest/cluster1.monmap (0 monitors)
```

**Comment by smithfarm** [comment]
**running** http://pulpito.ceph.com/smithfarm-2019-11-06_08:48:46-rbd-mimic-distro-basic-smithi/

**Comment by smithfarm** [comment]
`teuthology-suite -k distro --priority 50 --suite rbd --email ncutler@suse.cz --ceph-repo https://github.com/ceph/ceph.git --ceph mimic --newest 10 --machine-type smithi --suite-repo https://github.com/smithfarm/ceph.git --suite-branch wip-fix-get-mons-mimic --filter 'rbd-mirror' --subset 0/1000`

**running** http://pulpito.ceph.com/smithfarm-2019-11-06_10:28:44-rbd-mimic-distro-basic-smithi/

**Comment by dillaman** [comment]
Thx! Looks like it's working again.

**Comment by smithfarm** [comment]
@dillaman The `rbd/mirror-thrash` failure is expected?

**Comment by dillaman** [comment]
@smithfarm unrelated

**Pull request merged**
