### PR TITLE
mon: fix min/max variance for 'cpeh osd df' when osds are marked out

### PR DESCRIPTION
**Pull request by liewegas**

### CODE REVIEW

**Comment by liewegas** [comment]
should backport to hammer too

**Comment by liewegas** [comment]
@trociny I thinkt the average_util calc is off, see comment in second commit?

**Comment by trociny** [comment]
@liewegas I am happy to work on fixing average_util calc, if you don't mind. It may be delayed by other activities up to a couple of days though.

**Comment by liewegas** [comment]
No problem.  Thanks, Mykola!

**Comment by trociny** [comment]
I have created a pull request that fixes average_util calculation (#4399)

**Pull request merged**
