### PR TITLE
mgr/prometheus: use rbd metadata as labels

### PR DESCRIPTION
**Pull request by pereman2**
Include image metadata in image metrics as labels.

```sh
[root@ceph ceph]# curl localhost:9283/metrics | grep rbd_read_latency_count
# TYPE ceph_rbd_read_latency_count counter
ceph_rbd_read_latency_count{pool="rbd",namespace="",image="aa",foo="var",foo2="var2",foo4="var",k="v"} 0.0
[root@ceph ceph]# rbd image-meta set rbd/aa newkey newvalue
[root@ceph ceph]# curl localhost:9283/metrics | grep rbd_read_latency_count
# TYPE ceph_rbd_read_latency_count counter
ceph_rbd_read_latency_count{pool="rbd",namespace="",image="aa",foo="var",foo2="var2",foo4="var",k="v",newkey="newvalue"} 0.0
[root@ceph ceph]# curl localhost:9283/metrics | grep rbd_read_latency_count^C
[root@ceph ceph]# rbd image-meta set rbd/aa newkey reset
[root@ceph ceph]# curl localhost:9283/metrics | grep rbd_read_latency_count
# TYPE ceph_rbd_read_latency_count counter
ceph_rbd_read_latency_count{pool="rbd",namespace="",image="aa",foo="var",foo2="var2",foo4="var",k="v",newkey="reset"} 0.0
```

Signed-off-by: Pere Diaz Bou <pdiazbou@redhat.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Review by jmolmo — COMMENTED** [review]
The changes seems pretty sensible. Only one doubts about performance.
Could it be possible to include in the PR some numbers about time needed to retrieve the metrics for 1000 images with 3 custom labels each one?

**Review by idryomov — COMMENTED** [review]
This was discussed quite extensively with both @pereman2 and @jmolmo but all concerns raised in that discussion appear to have been ignored here:

- What happens if a user adds an image metadata whose key isn't a valid label name (`[a-zA-Z_][a-zA-Z0-9_]*`)?
- What happens if a user adds an image metadata whose value isn't valid UTF-8?
- The number of labels added from image metadata isn't limited here.
- While the number of labels added from image metadata could be easily limited, the set of label values is essentially infinite.  This is what Prometheus explicitly warns against:
  
  > CAUTION: Remember that every unique combination of key-value label pairs represents a new time series, which can dramatically increase the amount of data stored. Do not use labels to store dimensions with high cardinality (many different label values), such as user IDs, email addresses, or other unbounded sets of values.

Let's take a step back and go over the use cases (and document them here in the PR at least).  Why is this needed?  Who is going to use this?  Are there other ways of satisfying those use cases?

**Comment by aaSharma14** [comment]
jenkins test dashboard

**Comment by jmolmo** [comment]
> This was discussed quite extensively but all concerns raised in that discussion appear to have been ignored here:
> 
You right, we discussed, but i think  that having an opened PR we can progress more .

> * What happens if a user adds an image metadata whose key isn't a valid label name (`[a-zA-Z_][a-zA-Z0-9_]*`)?
I think this problem might be solved at the command level:
rbd image-meta set image-spec key value
must return and error if the key does not meet the syntax rule.

> * What happens if a user adds an image metadata whose value isn't valid UTF-8?
I think this problem might be solved at the command level:
rbd image-meta set image-spec key value
must return and error if the the value does not meet the syntax rule (UTF-8).

> * The number of labels added from image metadata isn't limited here.
Here we are not adding any labels. Just getting the list of lables. 
If we want to limit the number of custom labels in image metadata, probably we need to manage it as a new requeriment.

> * While the number of labels added from image metadata could be easily limited, the set of label values is essentially infinite.  This is what Prometheus explicitly warns against:
>   > CAUTION: Remember that every unique combination of key-value label pairs represents a new time series, which can dramatically increase the amount of data stored. Do not use labels to store dimensions with high cardinality (many different label values), such as user IDs, email addresses, or other unbounded sets of values.
> 
Yes, you are right. But we are talking about "custom labels" , is the final user who decides what labels to use, Obviously,  the final user can drive the monitoring system to a problem , using labels with unbound values. But a a great power, requires also a great responsibility. This happens in lot of other things... a wrong use of the functionality can drive to disaster. I think we can warn about this kid of usage in the documentation.


> Let's take a step back and go over the use cases (and document them here in the PR at least). Why is this needed? Who is going to use this? Are there other ways of satisfying those use cases?

The use case:
The final user has a Ceph cluster installed in a baremetal environment with his own monitoring stack. The user wants to use rbd images in this cluster to provide storage in a Rook cluster (PVs) and also wants to have monitoring information in RBD images about the Persistent volume backed by the RBD image.
In the Ceph Cluster there is no way to know what PV is using what image , because all this information is managed in the Rook cluster.
Because of that problem, the following solutions were implemented in the CSI and Rook projects:
- It was added a [new feature to CSI drivers](https://github.com/ceph/ceph-csi/pull/2898) in order to provide this information in form of custom labels in the images..
- It was also included the support for [this new functionality in Rook cluster](https://github.com/rook/rook/pull/10736)s.

The only part that it is needed now is to provide these three new labels (pvcNameKey, pvcNamespaceKey, pvNameKey) as part of the image metadata we get in image metrics. And this is what we are trying to achieve here.

**Comment by jmolmo** [comment]
@pereman2 : What about the performance ? can you provide an assessment?

**Pull request closed without merging**
