### PR TITLE
mimic: rgw: beast: set a default port for endpoints

### PR DESCRIPTION
**Pull request by pdvian**
http://tracker.ceph.com/issues/39049

### CODE REVIEW

**Comment by cbodley** [comment]
unrelated test failure:
> 122/157 Test #129: unittest_fastbmap_allocator .............***Failed    6.11 sec

**Comment by cbodley** [comment]
jenkins test make check

**Comment by smithfarm** [comment]
jenkins re-test this please

**Comment by smithfarm** [comment]
jenkins test docs

**Comment by yuriw** [comment]
[wip-yuri-testing-2019-05-02-2259-mimic](https://trello.com/c/j1rN3QVx/604-wip-yuri-testing-2019-05-02-2259-mimic)

**Pull request merged**
