### PR TITLE
rgw: multipart upload copy

### PR DESCRIPTION
**Pull request by yehudasa**
This builds on top of Javier's branch. Adds the following:
 - read source object in chunks
 - cleanups, parsing changes
 - versioning support

### CODE REVIEW

**Comment by jmunhoz** [comment]
@yehudasa the new patches look good to me. Bear in mind I am not very familiar with the versioning code under the hood but the code look good on my side. The branch is compiling and it works with my manual tests too. I got some some auth errors (forbidden and sig not match) using the s3-tests but I think they could be related to my testing environment and not the feature.

**Comment by yehudasa** [comment]
@jmunhoz which tests failed exactly, are these aws4?

**Comment by jmunhoz** [comment]
@yehudasa  s3-tests in commit 866411b1acaffc8645bc643470c658f5b34015ac. aws2 and aws4 are failing. As mentioned it is very possible my s3-test environment is broken now after a hard pulling. Are they working on your side?

**Comment by yehudasa** [comment]
@jmunhoz yes, but I tested it against a branch that consisted of some other fixes. Also, there is another broken test that will fail anyway, and some other tests that need special backend config.

**Comment by jmunhoz** [comment]
@yehudasa I set up a new s3-tests environment and ran some tests. As mentioned, it works with manual testing (http://tracker.ceph.com/attachments/download/2426/multipart-uploads-cp-test.py) between allowed buckets, etc. but if I use s3-tests all related test case raise errors on aws4 only. I uploaded a text file with the errors by category. It is available here:

http://tracker.ceph.com/attachments/download/2542/20160930-s3-tests-debug.txt

On my side, and using the s3-tests branch with commit 866411b1acaffc8645bc643470c658f5b34015ac I see errors related to versioning, lifecycle and acl granting.

It is interesting the multipart copy errors show all errors related to auth (404 forbidden) and not existent buckets. I wonder if the versioning and acl support could be failing and some test cases related to multipart could be failing due to not allowed permissions, etc. Does it make sense?

**Comment by yehudasa** [comment]
@jmunhoz there are a few known issues in that branch. Also, you need to run nose with `-a !fails_on_rgw`, so that it filters out other tests that are not supposed to pass. I'm preparing a branch with fixes to some of the known issues.

**Comment by yehudasa** [comment]
@jmunhoz see this branch: https://github.com/yehudasa/ceph/tree/wip-multipart-uploads-cp-2

**Comment by jmunhoz** [comment]
@yehudasa with the new branch the only multipart test case expecting pass and failing is test_multipart_copy_versioned under aws4

**Comment by yehudasa** [comment]
@jmunhoz tested it now, adding your boto aws4 compat branch: bugfix-16463-presigned-url, still see it failing, but not sure it's not a boto bug:
boto created the following canonical header:
`
...
x-amz-copy-source:yehuda-alerinj78zh4llqssrivq5-1/foo
x-amz-copy-source-range:bytes=0-5242879
...
`
whereas rgw created this:
`
x-amz-copy-source:yehuda-alerinj78zh4llqssrivq5-1/foo
x-amz-copy-source-range:bytes=0-5242879
`

It looks like boto is sorting by the whole strings, whereas we do it by the key names. Which is the correct way? In any case, this is not a regression due to the new code.

**Comment by yehudasa** [comment]
@jmunhoz after reading the aws4 spec, and having this test failing also when running it against aws, it really looks like boto bug.

**Comment by jmunhoz** [comment]
@yehudasa I think it could be a boto bug. I think the right case is sorting by the key names. As you mention it is coherent with the aws behaviour. In the minio-go implementation they are sorting by key too https://github.com/minio/minio-go/blob/master/request-signature-v4.go#L126-L134

**Comment by cbodley** [comment]
looks good to me - does it need a run through teuthology?

**Comment by yehudasa** [comment]
@cbodley that can [almost] never hurt

**Pull request merged**
