### PR TITLE
reef: build: opentelemetry-cpp

### PR DESCRIPTION
**Pull request by aliakseimakarau**
Building debian packages (make-debs.sh) in a host with several gcc versions triggers an LTO error:

lto1: fatal error: bytecode stream in file
'opentelemetry-cpp/sdk/src/trace/libopentelemetry_trace.a' generated with LTO version 12.0 instead of the expected 11.3.

Fixed by passing the CMake parameter set.

Fixes: https://tracker.ceph.com/issues/62488

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by tuan-hoang1** [comment]
friendly reminder @yuriw

**Comment by aliakseimakarau** [comment]
Hi Ken @ktdreyer , 
could you please have a look?
Thank you very much!!!

**Comment by ChristinaMeno** [comment]
You filed a bug for this. Seems a bit unusual to me I would expect builders to be not having several versions of any language implementation. Would you please say more about where you find this issue? Otherwise the fix seems harmless.

**Comment by aliakseimakarau** [comment]
Hi Christina @ChristinaMeno,
I was able to build ceph in a system with several gcc versions (cmake selected the latest one) but this is no a good way. Lets close this fix.

**Pull request closed without merging**
