### PR TITLE
msg: Fix typos in socket creation error message

### PR DESCRIPTION
**Pull request by badone**
Signed-off-by: Brad Hubbard <bhubbard@redhat.com>

### CODE REVIEW

**Comment by xiexingguo** [comment]
This looks definitely right.

However, I think you misunderstand the label `mgr`, which is a newly added module in charge of collecting and reporting statistics, hence it is quite another thing from messenger...

**Comment by badone** [comment]
@xiexingguo of course you're right. I wish we would make these things less ambiguous so people wouldn't fall into these traps. Anyway, I've changed it to core which I hope is appropriate?

**Comment by xiexingguo** [comment]
> I've changed it to core which I hope is appropriate?

yeah.

**Comment by badone** [comment]
Test this please

**Pull request merged**
