### PR TITLE
mon: small optimize on the Elector handle_propose function

### PR DESCRIPTION
**Pull request by songbaisen**
mon: small optimize on the Elector handle_propose function   

Signed-off-by: songbaisen <song.baisen@zte.com.cn>

### CODE REVIEW

**Comment by tchaikov** [comment]
i think the original code is clearer and more readable.

**Comment by xiexingguo** [comment]
@songbaisen 
I am with @tchaikov.

**Comment by scienceluo** [comment]
@songbaisen 
I am with @tchaikov too ^_^

**Comment by songbaisen** [comment]
@tchaikov  Thank you sir! The change it is look good to me here.There is not need to judge twice.I want the code here more simple.@scienceluo Do you insomnia last night in there.Remember take back a turkey leg for me.

**Comment by xiexingguo** [comment]
> here is not need to judge twice.

But I think we can afford this, imho,  for a better explanation, which I think can be great help to the newcomers to Ceph.

**Comment by songbaisen** [comment]
@xiexingguo  HE HE。

**Comment by liewegas** [comment]
The compiler should optimize this away.. and even if it doesn't this isn't a hot path.  I think readability wins here.  THanks!

**Pull request closed without merging**
