### PR TITLE
Deprecate or free up a bunch of feature bits

### PR DESCRIPTION
**Pull request by athanatos**

### CODE REVIEW

**Comment by athanatos** [comment]
Tested: /a/samuelj-2016-03-17_15:18:53-rados-wip-sam-working-distro-basic-smithi

**Comment by athanatos** [comment]
Just scheduled hammer-x and infernalis-x

**Comment by athanatos** [comment]
Actually, something interesting in one of the crashes, hold off for a bit.

**Comment by athanatos** [comment]
Nvm, two crashes, neither related to this branch.

**Comment by liewegas** [comment]
lgtm!

**Comment by athanatos** [comment]
I'm hitting http://tracker.ceph.com/issues/13878 on infernalis-x

**Comment by liewegas** [comment]
Down to just a 2 upgrade failures, not related to feature bits.

**Pull request merged**
