### PR TITLE
mgr: fix the desc typo for mds PyCFunction methods

### PR DESCRIPTION
**Pull request by lxbsz**
Signed-off-by: Xiubo Li <xiubli@redhat.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Review by tchaikov — APPROVED** [review]

**Comment by tchaikov** [comment]
```
2021-03-30T05:34:45.690+0000 7fb06da4eb80  1 mgr[py] Loading python module 'progress'
2021-03-30T05:34:45.750+0000 7fb06da4eb80 -1 mgr[py] Class not found in module 'progress'
2021-03-30T05:34:45.750+0000 7fb06da4eb80 -1 mgr[py] Error loading module 'progress': (22) Invalid argument
```

**Comment by tchaikov** [comment]
jenkins test api

**Comment by lxbsz** [comment]
jenkins test api

**Comment by tchaikov** [comment]
jenkins test api

**Comment by tchaikov** [comment]
- https://pulpito.ceph.com/kchai-2021-04-02_15:50:13-rados-wip-kefu-testing-2021-04-02-1506-distro-basic-gibba/
- https://pulpito.ceph.com/kchai-2021-04-03_11:44:43-rados-wip-kefu-testing-2021-04-03-1318-distro-basic-smithi/

**Pull request merged**
