### PR TITLE
os/bluestore: improve bluefs stats reporting

### PR DESCRIPTION
**Pull request by ifed01**
This includes:
 - add corresponding command to ceph-bluestore-tool
 - show file count in bluefs statistics.

Signed-off-by: Igor Fedotov <ifedotov@suse.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by yuriw** [comment]
[wip-yuri7-testing-2020-04-22-1640-master](https://trello.com/c/9Z6XfbyH/878-wip-yuri7-testing-2020-04-22-1640-master)

**Comment by yuriw** [comment]
[wip-yuri-testing-2020-04-24-1941-master](https://trello.com/c/GFVGvIbx/883-wip-yuri-testing-2020-04-24-1941-master)

**Comment by badone** [comment]
Test run failed, see https://trello.com/c/GFVGvIbx/883-wip-yuri-testing-2020-04-24-1941-master#comment-5eaa251a65d46e61fddf3a3f

**Comment by badone** [comment]
Seems to be a recurrence of https://tracker.ceph.com/issues/20236 @ifed01 can you comment on whether you think it's related to one of the three PRs being tested? This, https://github.com/ceph/ceph/pull/34575 and https://github.com/ceph/ceph/pull/34602

**Comment by ifed01** [comment]
> Seems to be a recurrence of https://tracker.ceph.com/issues/20236 @ifed01 can you comment on whether you think it's related to one of the three PRs being tested? This, #34575 and #34602

@badone - I don't think either of these is related. Looks like just a coincidence.

**Comment by badone** [comment]
@ifed01 thanks

**Pull request merged**
