### PR TITLE
test: update log-ignorelist for fs:mirror test

### PR DESCRIPTION
**Pull request by vshankar**
Signed-off-by: Venky Shankar <vshankar@redhat.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by vshankar** [comment]
@batrick this updates ignorelist in `qa/cephfs/overrides/whitelist_health.yaml` which is symlinked by `qa/suites/fs/mirror/overrides/whitelist_health.yaml` (and possibly other overrides under qa/suites/fs). Would that be a problem for possibly other tests?

**Comment by batrick** [comment]
needs the `Fixes...` line

**Comment by vshankar** [comment]
fixed and updated -- fs:mirror uses its own specific override yaml

**Review by batrick — APPROVED** [review]

**Comment by batrick** [comment]
https://tracker.ceph.com/projects/cephfs/wiki/Master#2021-June-03

**Pull request merged**
