### PR TITLE
vstart.sh: add options to enable PMEM bluestore backend

### PR DESCRIPTION
**Pull request by tchaikov**
Signed-off-by: Kefu Chai <tchaikov@gmail.com>

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [x] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by optimistyzy** [comment]
@tchaikov LGTM.  I tested my patch with this change, and it should be ok

**Comment by tchaikov** [comment]
jenkins test make check

**Comment by tchaikov** [comment]
jenkins test api

**Comment by tchaikov** [comment]
jenkins test make check

**Comment by tchaikov** [comment]
jenkins test api

**Comment by tchaikov** [comment]
jenkins test api

**Comment by tchaikov** [comment]
jenkins test api

**Comment by tchaikov** [comment]
@rzarzynski hi Radek, could you help review this change. per the @optimistyzy this works for him when testing his recent PMEM related change on bluestore.

**Comment by tchaikov** [comment]
jenkins test api

**Comment by tchaikov** [comment]
jenkins test make check

**Comment by optimistyzy** [comment]
> @rzarzynski hi Radek, could you help review this change. per the @optimistyzy this works for him when testing his recent PMEM related change on bluestore.

Yes, I tested with this patch, it works for me all using vstart.sh to do a all in one test.

**Comment by tchaikov** [comment]
@rzarzynski ping?

**Comment by tchaikov** [comment]
@rzarzynski ping?

**Comment by tchaikov** [comment]
@rzarzynski @neha-ojha @jdurgin  ping?

**Review by neha-ojha — APPROVED** [review]
looks fine to me, @tchaikov I will leave the testing and merge to you.

**Review by rzarzynski — APPROVED** [review]
LGTM!

I apologize, Kefu, for missing all your pings :-(. Messed up with my e-mail filtering. Fixing this!

**Comment by rzarzynski** [comment]
Regression testing
==============
I've cherry-picked 499609a089d0f2a811fa9dcf2f8ea9acc08c2c5b into my local branch to look for a regression with a broad impact. The following two commands executed without any issue:

* `MON=2 MDS=3 OSD=2 RGW=0 ../src/vstart.sh -b --without-dashboard -i 127.0.0.1 -n`,
* `../src/vstart.sh -b -l`.

I'm going to merge this.

**Pull request merged**
