### PR TITLE
Lifecycle feature[commits squash for bug fix]

### PR DESCRIPTION
**Pull request by chenji-kael**
As same as amazon S3 interface,"PUT Bucket lifecycle" and
"DELETE Bucket lifecycle" have been implemented,
"GET Bucket lifecycle" not realized yet as S3cmd has not
realize it also.
The feature`s main point is to remove expire file per day.
Files transfer from hot layer to cold layer is not supported.
ToDo:Maybe to transfer from replicate pool to EC pool or
from ssd to sata pool will be valuable.

Now put all buckets which should do lifecycle into shard
objects in .rgw.lc pool.

lifecycle config file format:
<LifecycleConfiguration>
    <Rule>
        <ID>sample-rule</ID>
        <Prefix></Prefix>
        <Status>enable</Status>
        <Expiration>
           <Days>1</Days>
        </Expiration>
    </Rule>
</LifecycleConfiguration>

Signed-off-by: Ji Chen <insomnia@139.com>

### CODE REVIEW

**Comment by tchaikov** [comment]
@chenji-kael need rebase.

**Comment by chenji-kael** [comment]
@tchaikov hi, yehuda suggest me to squash all commits and overwrite this branch directly
@yehudasa

**Comment by chenji-kael** [comment]
@tchaikov ping
@yehudasa ping

**Comment by yehudasa** [comment]
@chenji-kael we'll get to this branch after we finish up the jewel work. In the mean time you can rebase it on top of current master. Thanks.

**Comment by chenji-kael** [comment]
@oritwas @yehudasa  
sorry, I am now doing rebase, maybe I overwrite my branch by mistake ,so this PR was closed automatically, I will push a new PR, after I check it works well

**Pull request closed without merging**
