### PR TITLE
Wip 11258

### PR DESCRIPTION
**Pull request by ukernel**

### CODE REVIEW

**Comment by jcsp** [comment]
This looks sane.  So for #11258, was it that the client's handle_client_setattr was going onto the waiting_for_nolaggy list, and then the handle_client_getattr was executing ahead of it after the mds stopped being laggy?

An alternative might be to add a second _advance_queues() call into MDS::_dispatch, before the call to handle_deferrable_message, so that we don't have to wait for ProgressThread to do this

**Comment by ukernel** [comment]
the cap message that updates file size goes into waiting_for_nolaggy list. then the setattr request is handled before the cap message.

**Comment by gregsfortytwo** [comment]
@jcsp if we hit this branch we immediately call into _advance_queues(), right? So no waiting on another thread. It'd be nice if we could do this without adding a default argument, but I can't think of a simpler formulation.
Please merge when/if happy.

**Comment by jcsp** [comment]
>if we hit this branch we immediately call into _advance_queues(), right? So no waiting on another thread. 

Oh yeah, you're right.  In that case :+1:

**Pull request merged**
