### PR TITLE
rgw: TempURL should not allow PUTs with the X-Object-Manifest.

### PR DESCRIPTION
**Pull request by rzarzynski**
Fixes: http://tracker.ceph.com/issues/20797
Signed-off-by: Radoslaw Zarzynski <rzarzyns@redhat.com>

### CODE REVIEW

**Comment by mattbenjamin** [comment]
@rzarzynski @mdw-at-linuxbox still valid?

**Comment by rzarzynski** [comment]
@mattbenjamin last time Tempest wasn't verifying for the check but functional tests of Swift actually did. Thus, in my pesonal opinion, the behavior is a part of the *Swift API* **but not** *OpenStack Object Storage API*. However, I'm aware many people might disagree and argue that both are the same.

**Comment by mattbenjamin** [comment]
@rzarzynski in your view, then is the behavior introduced in this change (in)correct?  something that should be configurable?

**Comment by tchaikov** [comment]
@yuriw could you include this change in your next batch?

**Comment by cbodley** [comment]
passed qa in http://pulpito.ceph.com/cbodley-2019-05-30_18:03:29-rgw-wip-cbodley-testing-distro-basic-smithi/

**Pull request merged**
