### PR TITLE
mgr/dashboard: fix API tests

### PR DESCRIPTION
**Pull request by alfonsomthd**
* test_perf_counters_mgr_get
* test_selftest_cluster_log

Fixes: https://tracker.ceph.com/issues/45170
Fixes: https://tracker.ceph.com/issues/45246

Signed-off-by: Alfonso Martínez <almartin@redhat.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by callithea** [comment]
jenkins test dashboard backend

**Comment by alfonsomthd** [comment]
> Thanks! A py2->py3 issue.
> Do we need to backport this to octopus?

@bk201 I added octopus as backport in issue.

**Comment by callithea** [comment]
- [pkg build](https://shaman.ceph.com/builds/ceph/wip-laura-testing-34680-34685/519eb48f4250ccb1940bf55b14fa290f240071e8/)
- [QA run](http://pulpito.ceph.com/laura-2020-04-23_12:52:47-rados:dashboard-wip-laura-testing-34680-34685-distro-basic-smithi/) [WIP]

**Comment by bk201** [comment]
jenkins test dashboard backend

**Comment by callithea** [comment]
jenkins test dashboard backend

**Comment by callithea** [comment]
> jenkins test dashboard backend

The [previous build](https://jenkins.ceph.com/job/ceph-dashboard-pr-backend/743/consoleFull) failed with:
```
2020-04-24 04:09:14,827.827 INFO:__main__:Running ['./bin/ceph', 'mgr', 'self-test', 'cluster-log', 'cluster', 'info', 'foo bar info']
2020-04-24 04:09:15,472.472 INFO:__main__:Running ['./bin/ceph', 'log', 'Ended test tasks.mgr.test_module_selftest.TestModuleSelftest.test_selftest_cluster_log']
2020-04-24 04:09:16,709.709 INFO:__main__:test_selftest_cluster_log (tasks.mgr.test_module_selftest.TestModuleSelftest) ... ERROR
2020-04-24 04:09:16,709.709 INFO:__main__:Stopped test: test_selftest_cluster_log (tasks.mgr.test_module_selftest.TestModuleSelftest) in 26.651564s
2020-04-24 04:09:16,710.710 INFO:__main__:
2020-04-24 04:09:16,710.710 INFO:__main__:======================================================================
2020-04-24 04:09:16,710.710 INFO:__main__:ERROR: test_selftest_cluster_log (tasks.mgr.test_module_selftest.TestModuleSelftest)
2020-04-24 04:09:16,710.710 INFO:__main__:----------------------------------------------------------------------
2020-04-24 04:09:16,711.711 INFO:__main__:Traceback (most recent call last):
2020-04-24 04:09:16,711.711 INFO:__main__:  File "/home/jenkins-build/build/workspace/ceph-dashboard-pr-backend/qa/tasks/mgr/test_module_selftest.py", line 321, in test_selftest_cluster_log
2020-04-24 04:09:16,711.711 INFO:__main__:    priority, message)
2020-04-24 04:09:16,711.711 INFO:__main__:  File "/home/jenkins-build/build/workspace/ceph-dashboard-pr-backend/qa/tasks/ceph_test_case.py", line 111, in __exit__
2020-04-24 04:09:16,711.711 INFO:__main__:    if self.match():
2020-04-24 04:09:16,711.711 INFO:__main__:  File "/home/jenkins-build/build/workspace/ceph-dashboard-pr-backend/qa/tasks/ceph_test_case.py", line 99, in match
2020-04-24 04:09:16,711.711 INFO:__main__:    found = expected_pattern in self.watcher_process.stdout.getvalue()
2020-04-24 04:09:16,711.711 INFO:__main__:TypeError: a bytes-like object is required, not 'str'
2020-04-24 04:09:16,711.711 INFO:__main__:
2020-04-24 04:09:16,712.712 INFO:__main__:----------------------------------------------------------------------
2020-04-24 04:09:16,712.712 INFO:__main__:Ran 266 tests in 3407.885s
2020-04-24 04:09:16,712.712 INFO:__main__:
2020-04-24 04:09:16,712.712 INFO:__main__:FAILED (errors=1)
2020-04-24 04:09:16,712.712 INFO:__main__:
2020-04-24 04:09:16,712.712 INFO:__main__:======================================================================
2020-04-24 04:09:16,712.712 INFO:__main__:ERROR: test_selftest_cluster_log (tasks.mgr.test_module_selftest.TestModuleSelftest)
2020-04-24 04:09:16,712.712 INFO:__main__:----------------------------------------------------------------------
2020-04-24 04:09:16,713.713 INFO:__main__:Traceback (most recent call last):
2020-04-24 04:09:16,713.713 INFO:__main__:  File "/home/jenkins-build/build/workspace/ceph-dashboard-pr-backend/qa/tasks/mgr/test_module_selftest.py", line 321, in test_selftest_cluster_log
2020-04-24 04:09:16,713.713 INFO:__main__:    priority, message)
2020-04-24 04:09:16,713.713 INFO:__main__:  File "/home/jenkins-build/build/workspace/ceph-dashboard-pr-backend/qa/tasks/ceph_test_case.py", line 111, in __exit__
2020-04-24 04:09:16,713.713 INFO:__main__:    if self.match():
2020-04-24 04:09:16,713.713 INFO:__main__:  File "/home/jenkins-build/build/workspace/ceph-dashboard-pr-backend/qa/tasks/ceph_test_case.py", line 99, in match
2020-04-24 04:09:16,713.713 INFO:__main__:    found = expected_pattern in self.watcher_process.stdout.getvalue()
2020-04-24 04:09:16,713.713 INFO:__main__:TypeError: a bytes-like object is required, not 'str'
```

**Comment by callithea** [comment]
jenkins test dashboard backend

**Comment by callithea** [comment]
- [pkg build](https://shaman.ceph.com/builds/ceph/wip-laura-testing-34680-34705/)
- [QA run](http://pulpito.ceph.com/laura-2020-04-24_13:44:31-rados:dashboard-wip-laura-testing-34680-34705-distro-basic-smithi/) [WIP]

**Comment by tchaikov** [comment]
@alfonsomthd i think the right fix is to use StringIO for capturing strings. see #34752

**Comment by tchaikov** [comment]
closing in favor of #34752

**Pull request closed without merging**
