### PR TITLE
 log: clear thread-local stream's ios flags on reuse

### PR DESCRIPTION
**Pull request by cbodley**
when reusing a thread-local std::ostream for a new log entry, clear any
ios flags (ie eofbit/failbit/badbit) that may have been set during its
previous use

without this, any stream errors (for example, passing a nullptr to
operator<< sets the badbit) will cause all log output on that thread
to be blank for the remainder of the process

### CODE REVIEW

**Comment by tchaikov** [comment]
```
/home/jenkins-build/build/workspace/ceph-pull-requests/src/common/CachedPrebufferedStreambuf.cc: In static member function 'static CachedPrebufferedStreambuf* CachedPrebufferedStreambuf::create(prebuffered_data*)':
/home/jenkins-build/build/workspace/ceph-pull-requests/src/common/CachedPrebufferedStreambuf.cc:51:5: error: invalid use of member 'CachedPrebufferedStreambuf::os' in static member function
     os.clear();
     ^~
In file included from /home/jenkins-build/build/workspace/ceph-pull-requests/src/common/CachedPrebufferedStreambuf.cc:1:0:
/home/jenkins-build/build/workspace/ceph-pull-requests/src/common/CachedPrebufferedStreambuf.h:69:16: note: declared here
   std::ostream os;
                ^~
```

**Comment by aclamk** [comment]
@cbodley Would you care to incorporate #20185 for automated behavioral test?

**Comment by cbodley** [comment]
jenkins test docs please

**Comment by tchaikov** [comment]
http://pulpito.ceph.com/kchai-2018-01-31_01:48:16-rados-wip-kefu-testing-2018-01-31-0034-distro-basic-mira/

failure tracked at http://tracker.ceph.com/issues/22846

**Comment by cbodley** [comment]
see fix for unittest_log segfault in libc++ at https://github.com/ceph/ceph/pull/20233

**Pull request merged**
