### PR TITLE
luminous: common: (mon) command sanitization accepts floats when Int type is defined resulting in exception fault in ceph-mon

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/26919

### CODE REVIEW

**Comment by smithfarm** [comment]
@liewegas wrote to let this one "bake", so let's leave it for 12.2.10

**Comment by smithfarm** [comment]
I checked for master commits mentioning any of these, and found one:

```
smithfarm@wilbur:~/src/ceph/smithfarm/ceph> git log --grep fecb902
smithfarm@wilbur:~/src/ceph/smithfarm/ceph> git log --grep b684f02
smithfarm@wilbur:~/src/ceph/smithfarm/ceph> git log --grep 5945b55
smithfarm@wilbur:~/src/ceph/smithfarm/ceph> git log --grep bd565bc
commit e02a5d55472bdd8473604730f969fad2dc5eafac
Author: Sage Weil <sage@redhat.com>
Date:   Tue Aug 7 20:43:49 2018 -0500

    mgr/localpool: pg_num is an int arg to 'osd pool create'
    
    In bd565bca3f42d7946c392b2833bb3d9982a8ac5d we start returning EINVAL if
    the pg_num argument is not valid, whereas before it was silently ignored.
    
    Signed-off-by: Sage Weil <sage@redhat.com>
smithfarm@wilbur:~/src/ceph/smithfarm/ceph> git log --grep efd9de4
```

**Comment by smithfarm** [comment]
@jecluis @liewegas Ping (see previous comment)

**Comment by jecluis** [comment]
@smithfarm the patch seems okay to me. @liewegas ?

**Comment by smithfarm** [comment]
@jecluis @liewegas I'm specifically looking for an answer to the question I posed in https://github.com/ceph/ceph/pull/24374#issuecomment-442205782

**Comment by liewegas** [comment]
@smithfarm no need to backport that patch since that behavior change is in luminous only.

**Comment by smithfarm** [comment]
OK, thanks, queueing for integration test.

**Comment by yuriw** [comment]
[wip-yuri3-testing-2019-01-03-1654-luminous](https://trello.com/c/vFwbW3TH/497-wip-yuri3-testing-2019-01-03-1654-luminous)

**Comment by yuriw** [comment]
@liewegas pls approve it passed tests

**Comment by sebastian-philipp** [comment]
possibly related: https://tracker.openattic.org/browse/OP-3188 cc @callithea

**Comment by callithea** [comment]
Thanks for the hint @sebastian-philipp!

**Pull request merged**
