### PR TITLE
os/bluestore: miscellaneous fixes to BitAllocator

### PR DESCRIPTION
**Pull request by xiexingguo**
@chhabaramesh Some more improvements to the BitAllocator submodule.
These patches have already passed my local tests. Please take a look when you are available.

Thanks.

### CODE REVIEW

**Comment by liewegas** [comment]
retest this please

**Comment by liewegas** [comment]
<pre>
[ RUN      ] BitAllocator.test_bmap_alloc_concurrent
Spawning 16 threads for parallel test. Mode Cont = 0.....
Starting thread 0Starting thread 1Starting thread 2Starting thread 3Starting thread 4Starting thread 5Starting thread 6Starting thread 7Starting thread 8Starting thread 9Starting thread 10Starting thread 11Starting thread 12Starting thread 13Starting thread 14Starting thread 15/home/sage/src/ceph/src/os/bluestore/BitAllocator.cc: In function 'void BitAllocator::free_blocks_dis(int64_t, ExtentList*)' thread 7f856969b700 time 2016-12-31 11:14:08.064051
/home/sage/src/ceph/src/os/bluestore/BitAllocator.cc: 1484: FAILED assert(get_used_blocks() >= 0)
 ceph version 11.1.0-6413-g78707bd (78707bd3a400b064aa9b148cdbdc7f8e50b371cf)
 1: (ceph::__ceph_assert_fail(char const*, char const*, int, char const*)+0x79) [0x557c6cf705b9]
 2: (()+0x13bf74) [0x557c6cf59f74]
 3: (do_work_dis(BitAllocator*)+0x137) [0x557c6cf2af77]
 4: (worker(void*)+0x34) [0x557c6cf2b1f4]
 5: (()+0x76ca) [0x7f856f0806ca]
 6: (clone()+0x5f) [0x7f856bb5af6f]
 NOTE: a copy of the executable, or `objdump -rdS <executable>` is needed to interpret this.
2016-12-31 11:14:08.064672 7f856969b700 -1 /home/sage/src/ceph/src/os/bluestore/BitAllocator.cc: In function 'void BitAllocator::free_blocks_dis(int64_t, ExtentList*)' thread 7f856969b700 time 2016-12-31 11:14:08.064051
</pre>

**Comment by liewegas** [comment]
hmm nevermind, got it without this too

**Comment by liewegas** [comment]
@varadakari care to review?

**Comment by chhabaramesh** [comment]
@xiexingguo  , @liewegas , I reviewed the changes. Some of the changes are not required that I commented on. @xiexingguo  please drop those changes and update the pull request.

**Comment by xiexingguo** [comment]
@chhabaramesh You reviewed and commented on https://github.com/ceph/ceph/pull/12661 instead of this one...

**Comment by xiexingguo** [comment]
@chhabaramesh @varadakari Ping

**Comment by chhabaramesh** [comment]
@xiexingguo ,  I have given my comments on individual commits in this pull requests.

summary:

os/bluestore/BitAllocator: kill find_any_free_bits() 
 and 

  os/bluestore: replace m_max_alloc_size with m_max_blocks 

   looks ok and other two changes are not required.

**Comment by xiexingguo** [comment]
> @xiexingguo , I have given my comments on individual commits in this pull requests.

Well, I can not see anything about that.  Github bug, perhaps?
Dropped the other two changes anyway.

**Comment by chhabaramesh** [comment]
@xiexingguo ,  possible and surprising :(. I have comments 3 days ago. 

" chhabaramesh commented 3 days ago

@xiexingguo , @liewegas , I reviewed the changes. Some of the changes are not required that I commented on. @xiexingguo please drop those changes and update the pull request."


I am ok with the pull request now.

**Pull request merged**
