### PR TITLE
common: clarify some obj_bencher code

### PR DESCRIPTION
**Pull request by dachary**

### CODE REVIEW

**Comment by dachary** [comment]
@dmitryya would you have time to review this ? It will help with https://github.com/ceph/ceph/pull/4151 don't you think ?

**Comment by liewegas** [comment]
needs rebase?

**Comment by dachary** [comment]
review comment to be addressed (got lost in the rebase):

@dachary looks good for me, except few things: 
 - the comment to commit can confuse (why "unused"?), because you can use the following:
<code>
rados -p rbd --num-objects 60 bench 6000 write
</code>
The option will take affect and the result will be something like:
<pre><code>
 Total time run:         32.559595
Total writes made:      60
Write size:             4194304
Bandwidth (MB/sec):     7.371 
</code></pre>
But '--num-object' here is used with inappropriate command  - it is "LOAD GEN OPTIONS" and has to be used only with <b>load-gen</b> command. 

- also, I think will be good to write an error message when '--num-objects' is used not for <b>load-gen</b>. I think there are number of people who use <b>bench</b> with '--num-object' for testing and without error message they will be a little confused why tests work in wrong way.

just think about: It will be great to have the same signature for all test functions (write_bench, seq_read_bench, rand_read_bench) that give us possibility to make small optimisation and change <code>if(OP_RAND_READ == operation){...}else if(...){} </code> block with access through func array. 
In any case we can change this block to <code> switch(operation){...} </code> which is also small optimisation.

**Comment by dachary** [comment]
@dmitryya 

> the comment to commit can confuse (why "unused"?) 

in 1ac7279 I remove the maxObjectsToCreate variable because it actually not used anywhere.

> also, I think will be good to write an error message when '--num-objects' is used not for load-gen. I think there are number of people who use bench with '--num-object' for testing and without error message they will be a little confused why tests work in wrong way.

I agree. Now that your pull request has been merged, would you like to add this warning ? I'm hesitant to add that to this pull request because it only contains changes that have no user visible impact. It just clarifies code that confused me when I tried to understand it.

> just think about: It will be great to have the same signature for all test functions (write_bench, seq_read_bench, rand_read_bench) 

+1 ! It's a sizeable effort though and unless you think otherwise it would be better to do it in a different pull request.

**Comment by dachary** [comment]
rebased & repushed

**Comment by dmitryya** [comment]
@dachary OK. I will take care about a warning and also think about how to do *_bench calls optimization in the best way.

**Comment by dachary** [comment]
@dmitryya cool :-)

**Pull request merged**
