### PR TITLE
osd: should accept delete op when full

### PR DESCRIPTION
**Pull request by l11625**
Fixes: #13110
Signed-off-by: Xuan Liu <liu.xuan@h3c.com>

### CODE REVIEW

**Comment by xinxinsh** [comment]
if pool is pool ,  delete op will blocked on the client, this op should never be sent to osd

**Comment by dachary** [comment]
> Failed building wheel for coverage
Please ignore the false negative from the bot.

**Comment by yangruifeng** [comment]
@xinxinsh we will test the case that pool is full, and modify again, thanks.

**Comment by tchaikov** [comment]
@l11625 agree with @xinxinsh. Objecter will hold the request if the existing osdmap shows that the pool is full, and cancel this request if the latest osdmap from mon confirms it. so you might need to mark this pull request `DNM: ` and remove this label when it's ready for review.

**Comment by l11625** [comment]
@xinxinsh and @tchaikov, I have modified this problem, please check again, thanks a lot .

**Comment by l11625** [comment]
@liewegas , I have fixed  bug #13110, please check and merge, thank you very much .

**Comment by liewegas** [comment]
The first half of a fix for this is in #6052, which will let the OSD process an op if it doesn't increase the overall utilization.  The missing piece is some logic in Objecter to allow requests through if we expect them to reduce space (e.g., they are a simple delete).  For now, we can make that a simple check (is it a single delete op?)--eventually we can also expose a librados flag that forces it to be sent through to the OSD even though the objecter doesn't know if it will succeed or not.

However, there is one annoying twist: in order to preserve op ordering, I think we need to keep track of any ops that are blocked by a full pool/cluster, and prevent even delete ops from going through if there is a prior op queued on that object.  I'll send a message to the list with some detail since I'm not certain about the right approach here..

**Pull request closed without merging**
