### PR TITLE
packaging: do not package unused unittests in deb

### PR DESCRIPTION
**Pull request by tchaikov**

### CODE REVIEW

**Comment by tchaikov** [comment]
@mattbenjamin and @ktdreyer mind taking a look?

**Comment by tchaikov** [comment]
tested at 

- http://pulpito.ceph.com/kchai-2016-06-04_19:52:10-rados-wip-kefu-testing---basic-mira/
- http://pulpito.ceph.com/kchai-2016-06-04_09:44:21-rados-wip-kefu-testing---basic-mira/
- http://pulpito.ceph.com/kchai-2016-06-04_05:52:02-rados-wip-kefu-testing---basic-mira/

the failures are caued by environmental problem, test suite issues [1], and teuthology issue[2]

--
[1] https://github.com/ceph/ceph-qa-suite/pull/1031 
[2] http://tracker.ceph.com/issues/16142

**Comment by liewegas** [comment]
Can you add a note to PendingReleaseNOtes?

**Comment by tchaikov** [comment]
changelog

- rebased against master
- updated PendingReleaseNotes

**Comment by tchaikov** [comment]
@liewegas does this change look better now?

**Comment by liewegas** [comment]
lgtm!

**Comment by tchaikov** [comment]
tested in my last qa run.

**Pull request merged**
