### PR TITLE
common/SubProcess: Updated stdin, stdout, stderr method names to avoid g++ error.

### PR DESCRIPTION
**Pull request by dx9**
In file included from /usr/include/fortify/stdio.h:20:0,
                 from /usr/include/c++/5.2.0/cstdio:42,
                 from /usr/include/c++/5.2.0/ext/string_conversions.h:43,
                 from /usr/include/c++/5.2.0/bits/basic_string.h:5247,
                 from /usr/include/c++/5.2.0/string:52,
                 from /build/ceph/src/include/stringify.h:4,
                 from /build/ceph/src/crush/CrushTester.cc:4:
/build/ceph/src/common/SubProcess.h:155:17: error: expected unqualified-id before '(' token
 int SubProcess::stdin() const {
                 ^
/build/ceph/src/common/SubProcess.h:162:17: error: expected unqualified-id before '(' token
 int SubProcess::stdout() const {
                 ^
/build/ceph/src/common/SubProcess.h:169:17: error: expected unqualified-id before '(' token
 int SubProcess::stderr() const {

### CODE REVIEW

**Comment by liewegas** [comment]
This change looks good. Can you please add a Signed-off-by: line to the git commit message (see SubmittingPatches).  Thanks!

**Comment by dx9** [comment]
oops, didn't hit this with the cmake build. I'll take a look.

**Comment by dx9** [comment]
Just had to run ```make check``` to reproduce the failure above. Unit test needed to be updated to use new method names.

72% of unit tests are passing on Alpine, nice to see them run.

**Comment by dx9** [comment]
https://github.com/ceph/ceph/commit/671ab30a fixed it

**Pull request closed without merging**
