### PR TITLE
librbd: diff_iterate should issue concurrent ops

### PR DESCRIPTION
**Pull request by dillaman**

### CODE REVIEW

**Comment by LiumxNL** [comment]
It seems the write diff-file jobs are submitted asynchronously and will complete out of order.  That is, the diff descriptions in the generated diff file are not in the order of object occurence in the RBD. If the understanding is correct, then the merge-diff tool could not process the diff file, maybe we need add an option to export-diff command to explicitly generate such out of order diff file. The other minor thing, if the write are done asynchronously and completed out of order, it seems unnecessary to excute m_callback() sequentially in invoke_callback(), fix me if I am wrong

**Comment by dillaman** [comment]
@LiumxNL The callbacks should be executed in order with this PR.  Each diff request is associated to a sequence number within ```DiffContext::start_op```.  Within ```DiffContext:: invoke_callback```, it will only invoke the callbacks for which is has registered results -- stopping if there is a gap in the sequence.  Therefore, all callbacks are invoked sequentially in the same order as if this change wasn't made.

As an aside, the export-diff tool doesn't care what order the diffs arrive in since it encodes the offset of the diff within the export file.  If you had a "fancy" striped RBD image, the diff iterate callbacks would be out-of-order since it operates on each object sequentially.

**Comment by LiumxNL** [comment]
> the export-diff tool doesn't care what order the diffs arrive in since it encodes the offset of the diff within the export file.
with this reason,i think there is no need to invoke callbacks sequentially,that is to say,we can invoke callback directly when any diff request finished,without comparing the sequence number first.

**Comment by LiumxNL** [comment]
> the export-diff tool doesn't care what order the diffs arrive in since it encodes the offset of the diff within the export file.
with this reason,i think there is no need to invoke callbacks sequentially,that is to say,we can invoke callback directly when any diff request finished,without comparing the sequence number first.

**Comment by dillaman** [comment]
@LiumxNL The callbacks cannot be invoked from the librados AIO callback since that would block other IO operations.  Therefore, either the callbacks need to occur from another thread or via the original caller's thread context.  Since in both cases the results would be serialized, this implementation chooses the latter for simplicity. 

In the case of export-diff, when it receives the (serialized) callback, it kicks off its own AIO read operation, so in effect this serialization point isn't a real bottleneck.

**Comment by LiumxNL** [comment]
@dillaman I guess that mean if callback invoked i need it return then start a new op to get diffs.but we may delay to start an writing export file op.i am afraid it's hard to say which is better.in my test,if client is in low speed device,invoke callback directly will be better,on the contrary,be serial is better,in both case the performance is just a little difference.

**Comment by LiumxNL** [comment]
@dillaman I guess that mean if callback invoked i need it return then start a new op to get diffs.but we may delay to start an writing export file op.i am afraid it's hard to say which is better.in my test,if client is in low speed device,invoke callback directly will be better,on the contrary,be serial is better,in both case the performance is just a little different.

**Pull request merged**
