### PR TITLE
Doc: Typo in the apt-get command

### PR DESCRIPTION
**Pull request by cholcombe973**
Quick PR :)

### CODE REVIEW

**Comment by dachary** [comment]
@cholcombe973 could you add a **Signed-off-by** to the commit message ? And whil you're at it, prefixing the commit message title with doc: would be appreciated :-)

**Comment by cholcombe973** [comment]
@dachary done.  Thanks :)

**Comment by dachary** [comment]
@cholcombe973 nitpicking: there need to be an empty line between the commit title and the Signed-off-by. And there must be a space before the &lt; ;-)

**Comment by dachary** [comment]
Here is how it should be:
<pre>
Signed-off-by: Chris Holcombe &lt;xfactor973@gmail.com>
</pre>

**Comment by cholcombe973** [comment]
@dachary If it needs to be that exact why not just have a git commit hook to reject anything that doesn't meet the spec?  Is there some automation that runs that requires it to be formatted like that?  It already says in the git log that I committed it.  I'm kinda curious why there needs to be a signed-off-by line also.

**Comment by dachary** [comment]
> If it needs to be that exact why not just have a git commit hook to reject anything that doesn't meet the spec? 

Because it was not done yet. It would be useful.

> I'm kinda curious why there needs to be a signed-off-by line also. 

The rationale is explained at https://github.com/ceph/ceph/blob/master/SubmittingPatches#L12

Cheers

**Comment by dachary** [comment]
@cholcombe973 the format of the Signed-off-by: is good but there must be an empty line before it.

**Pull request merged**
