### PR TITLE
test: disable osd-scrub-repair and test-erasure-eio

### PR DESCRIPTION
**Pull request by dmick**
After Sage's suggestion of earlier today, in now-closed
PR #11970, which can't be resurrected just now

Signed-off-by: Dan Mick <dan.mick@redhat.com>

### CODE REVIEW

**Comment by dmick** [comment]
Perhaps presciently, this failed in test-erasure-eio.sh, and the error log is 523MB so beware looking.

I'll ask it to test again

**Comment by dmick** [comment]
test this please

**Comment by dzafman** [comment]
@dmick Disable the test-erasure-eio.sh here and merge it if it passes.  I'm working on that one in ceph/ceph#11926

**Comment by dmick** [comment]
Added another commenting-out to disable test-erasure-eio as well

**Comment by dzafman** [comment]
@dmick  Strange only osd-fast-mark-down.sh failed, which I've never seen before.

**Comment by dachary** [comment]
hey jenkins, test this please ( osd-fast-mark-down.sh failure )

**Pull request merged**
