### PR TITLE
rgw: fix dbstore test init env wrong

### PR DESCRIPTION
**Pull request by joke-lee**
fix https://tracker.ceph.com/issues/54174

Signed-off-by: yuliyang_yewu <yuliyang_yewu@cmss.chinamobile.com>

@cbodley would you mind help to review

### CODE REVIEW

**Comment by soumyakoduri** [comment]
jenkins test api

**Comment by cbodley** [comment]
@soumyakoduri how would you like to verify fixes like this? do the dbstore tests run as part of 'make check' or do we need to run those manually?

**Comment by soumyakoduri** [comment]
> @soumyakoduri how would you like to verify fixes like this? do the dbstore tests run as part of 'make check' or do we need to run those manually?

As of now, they need to be run manually. The test executable gets built as part of make but I wasn't aware that it can be run via 'make check'. Could you please point me to any code on how to do it? 
Is it via "add_test(..)"  ?

**Comment by cbodley** [comment]
yep, ceph has a `add_ceph_unittest()` that wraps `add_test()` and adds it to the 'check' target. you can find examples in src/test/rgw/CMakeLists.txt

**Comment by soumyakoduri** [comment]
> yep, ceph has a `add_ceph_unittest()` that wraps `add_test()` and adds it to the 'check' target. you can find examples in src/test/rgw/CMakeLists.txt

Thanks! Will include these tests.

**Comment by cbodley** [comment]
@soumyakoduri this PR looks simple enough to merge without testing, but i'll let you decide whether you want to run manual tests on it first

**Comment by soumyakoduri** [comment]
> @soumyakoduri this PR looks simple enough to merge without testing, but i'll let you decide whether you want to run manual tests on it first

ack. Thanks @joke-lee for fixing it.

**Pull request merged**
