### PR TITLE
qa/rgw: fix s3 java tests by forcing gradle to run on Java 8

### PR DESCRIPTION
**Pull request by ivancich**
During testing sets JAVA_HOME to refer to the java interpreter for Java 8, so there aren't any issues with gradle.

Fixes: https://tracker.ceph.com/issues/69204

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [x] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Comment by ivancich** [comment]
@cbodley This seems to solve the issue but it's currently *very* clunky. I'm thinking it'd be better just to use `alternatives` to set Java 8 the default version. (Also, the second commit is just for testing purposes.) What do you think?

**Comment by ivancich** [comment]
Also, here's a successful run: https://pulpito.ceph.com/ivancich-2024-12-10_02:44:46-rgw-wip-eric-testing-1-distro-default-smithi/

**Comment by cbodley** [comment]
> What do you think?

i love it if it works! have you tried running this against a ubuntu worker? i'm not familiar with the `alternatives` command, so can't tell whether or not it's specific to rpm-based distros

**Comment by ivancich** [comment]
> > What do you think?
> 
> i love it if it works! have you tried running this against a ubuntu worker? i'm not familiar with the `alternatives` command, so can't tell whether or not it's specific to rpm-based distros

So it works on both centos and ubuntu. See: https://pulpito.ceph.com/ivancich-2024-12-11_15:44:29-rgw-wip-eric-testing-1-distro-default-smithi/

**Review by cbodley — APPROVED** [review]

**Pull request merged**
