### PR TITLE
doc: Fixed example sintax in Absolute Sizing

### PR DESCRIPTION
**Pull request by isserrano**
from: ceph osd pool hot-storage target_max_bytes 1000000000000
to: ceph osd pool set hot-storage target_max_bytes 1000000000000

### CODE REVIEW

**Comment by dachary** [comment]
Could you please add a *Signed-of-by:* line (see with git log for examples) at the end of the commit message with *git --amend* ? 

Nice catch ;-)

**Comment by isserrano** [comment]
Signed-of-by added

**Comment by dachary** [comment]
You need to squash the commits. I recommend you do that:
<pre>
git reset --hard 1a843e0
git commit --amend
</pre>
when the editor opens and show you the commit message, make it look like:
<pre>
doc: s/osd pool hot-storage/osd pool set hot-storage/

Signed-off-by: Ismael Serrano &lt;ismael.serrano@gmail.com>
</pre>
only replace the mail with your real mail ;-) and then push with
<pre>
git push --force
</pre>

**Comment by isserrano** [comment]
Hi Loic,
Done, thank you very much for your help, I will follow these guidelines next time.

**Pull request merged**
