### PR TITLE
qa/tasks/ceph: simplify ceph deployment slightly

### PR DESCRIPTION
**Pull request by liewegas**

### CODE REVIEW

**Comment by liewegas** [comment]
retest this please

**Comment by liewegas** [comment]
http://pulpito.ceph.com/sage-2017-06-27_05:44:05-rados-wip-sage-testing-distro-basic-smithi/1331651

need to have a ceph.py option to add osd to crush map for upgrade tests (teuthology doesn't use systemd unit which runs the old prestart.sh which does it)

**Comment by liewegas** [comment]
http://pulpito.ceph.com/sage-2017-06-27_16:20:27-rados:upgrade-wip-sage-testing-distro-basic-smithi/

**Comment by liewegas** [comment]
gets past previous failure: http://pulpito.ceph.com/sage-2017-06-27_16:53:03-rados:upgrade-wip-sage-testing-distro-basic-smithi

**Comment by dillaman** [comment]
Note: this broke rbd-mirror test cases since it assumes a cluster name of ```ceph``` when copying the fsid

**Pull request merged**
