### PR TITLE
doc: mailmap for v9.0.2 release

### PR DESCRIPTION
**Pull request by theanalyst**

### CODE REVIEW

**Comment by dachary** [comment]
One seems to be missing affiliation, otherwise the output looks perfect. 
<pre>
$ bash ../credits.sh tags/v9.0.1..ceph/next
...
Reviews, by organizations (one review spans multiple commits)
...
    11	      1 Kernel Neophyte <neophyte.hacker001@gmail.com>
</pre>

**Comment by theanalyst** [comment]
@dachary yeah that was the one I mentioned in irc, the one I couldn't find any details at all .. the relevant commit is #4663

**Comment by dachary** [comment]
@theanalyst then we can have Kernel Neophyte be unaffiliated ?

**Comment by theanalyst** [comment]
@dachary sure ... adding

**Comment by theanalyst** [comment]
@dachary updated

**Comment by theanalyst** [comment]
@dachary mails sent on July 15th .. guess we have given this sufficient time for reviews

**Pull request merged**
