### PR TITLE
admin: Fix check if PR or release branch docs build

### PR DESCRIPTION
**Pull request by djgalloway**
Uses built-in RTD vars.  https://docs.readthedocs.io/en/stable/environment-variables.html.

Follow up to https://github.com/ceph/ceph/pull/46917#discussion_r942359130.

Signed-off-by: David Galloway <dgallowa@redhat.com>
(cherry picked from commit f92133ca527b5608b7ba8b79396568b03fa686b3)

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [x] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by idryomov** [comment]
This is a backport of https://github.com/ceph/ceph/pull/47737, waiting for it to merge.

**Review by idryomov — APPROVED** [review]

**Comment by idryomov** [comment]
jenkins test api

**Comment by idryomov** [comment]
RTD build is failing on a unrelated issue:

> [rtd-command-info] start-time: 2022-08-22T21:47:07.132047Z, end-time: 2022-08-22T21:47:08.309255Z, duration: 1, exit-code: 1
> /home/docs/checkouts/readthedocs.org/user_builds/ceph/envs/47742/bin/python -m pip install --exists-action=w --no-cache-dir -r admin/doc-pybind.txt
> ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'admin/doc-pybind.txt'

Since octopus is EOL does it make sense to attempt to address it?  If not addressed, we are not going to get anything out of merging this PR, are we?

**Comment by djgalloway** [comment]
Not sure how that's even possible.  I just wanted to update Octopus because of some feedback on the lists about folks still actively using it.  But you're right.  Will close.

**Pull request closed without merging**
