### PR TITLE
make journal support compress/decompress.

### PR DESCRIPTION
**Pull request by majianpeng**

### CODE REVIEW

**Comment by yuyuyu101** [comment]
Actually, I would like to know how we can enjoy the benefit from journal compress, it could guide users to choose whether enabling journal compress. Could you give a benchmark result?

**Comment by xiaoxichen** [comment]
@yuyuyu101 I think this is not performance critial but aiming to protect the SSD lifetime...It's hard to benchmark since FIO can only generate all-zero or random data, which is either too-compress-able or non-compress-able.

**Comment by dachary** [comment]
@majianpeng this needs rebasing. This will also re-trigger the bot that shows it can't find the required libraries, IIRC.

**Comment by dachary** [comment]
@majianpeng  feel free to re-open when you have time to rebase

**Pull request closed without merging**
