### PR TITLE
rgw: urlencode ' ( ) ! in s3 CanonicalizedResource

### PR DESCRIPTION
**Pull request by joke-lee**
hi,
   when i use s3brower to upload file named 中'    urlencode is  %E4%B8%AD%27 
i found s3brower compute the Authorization header with %E4%B8%AD%27 while the uri  is 
```
< PUT /test/%E4%B8%AD' HTTP/1.1
< Host: 127.0.0.1:8000
< Content-Length: 3
< Accept-Encoding: gzip, deflate
< Accept: */*
< User-Agent: python-requests/2.6.0 CPython/2.7.5 Linux/3.10.0-327.el7.x86_64
< Connection: keep-alive
< date: Wed, 03 Jan 2018 12:51:00 GMT
< Content-Type: application/octet-stream
< Authorization: AWS yly:qyZodt+z89iS/RYiosf7CON+yjs=         <=compute base on %E4%B8%AD%27
```
the bucket named test

so , when rgw caculate the auth ,it use  %E4%B8%AD'  instead  %E4%B8%AD%27 which cause signatuer not match,  but in amazon s3, i upload the same object success, i think amazon may urlencode again  %E4%B8%AD' to  %E4%B8%AD%27   (' urlencode is  %27). so maybe we need to add aws2_uri_encode to ensure urlencode correctly

Signed-off-by: yuliyang <yuliyang@cmss.chinamobile.com>

### CODE REVIEW

**Comment by joke-lee** [comment]
hi, @cbodley do you mind to help review this ? thanks

**Comment by mattbenjamin** [comment]
@joke-lee I think we can tighten the style a bit here, but conceptually this is a very good find, much appreciated;

@mdw-at-linuxbox could you take a look at this?

**Comment by yuriw** [comment]
[wip-yuri3-testing-2018-01-04-1748](https://trello.com/c/AqGwkXDb/217-wip-yuri3-testing-2018-01-04-1748)

**Comment by cbodley** [comment]
it looks like this is causing an s3test failure:
> ======================================================================
FAIL: s3tests.functional.test_s3.test_bucket_create_naming_bad_punctuation
\----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ubuntu/cephtest/s3-tests/virtualenv/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/ubuntu/cephtest/s3-tests/s3tests/functional/test_s3.py", line 3313, in test_bucket_create_naming_bad_punctuation
    check_bad_bucket_name('alpha!soup')
  File "/home/ubuntu/cephtest/s3-tests/s3tests/functional/test_s3.py", line 3119, in check_bad_bucket_name
    eq(e.status, 400)
AssertionError: 403 != 400
-------------------- >> begin captured logging << --------------------

**Comment by yuriw** [comment]
removed from testing batch batch, pls mark "needs-qa" when ready

**Comment by joke-lee** [comment]
hi  @cbodley  ,i update the code urlencode the key only

**Comment by joke-lee** [comment]
https://github.com/ceph/ceph/pull/21286

**Pull request closed without merging**
