### PR TITLE
nautilus: mgr/volumes: synchronize ownership (for symlinks) and inode timestamps for cloned subvolumes

### PR DESCRIPTION
**Pull request by ajarr**
Fixes: https://tracker.ceph.com/issues/44484
Fixes: https://tracker.ceph.com/issues/44521

Also cherry-picked python bindings, test and doc fixes to allow for a clean cherry-pick.

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by ajarr** [comment]
http://pulpito.front.sepia.ceph.com/rraja-2020-03-12_18:11:13-fs-wip-sync-attrs-nautilus-distro-basic-smithi/

**Comment by ajarr** [comment]
> http://pulpito.front.sepia.ceph.com/rraja-2020-03-12_18:11:13-fs-wip-sync-attrs-nautilus-distro-basic-smithi/

See the following in centos 7.5 that I didn't hit in local testing,
```
2020-03-12 19:12:36.154 7f6917bca700  1 mgr[volumes] thread [cloner.0] encountered fatal error: (attempt# 1/10)
2020-03-12 19:12:36.155 7f6917bca700  1 mgr[volumes] traceback: <span style="background-color:#FCE94F"><font color="#2E3436">Trace</font></span>back (most recent call last):
  File &quot;/usr/share/ceph/mgr/volumes/fs/async_job.py&quot;, line 43, in run
    self.async_job.execute_job(vol_job[0], vol_job[1], should_cancel=lambda: thread_id.should_cancel())
  File &quot;/usr/share/ceph/mgr/volumes/fs/async_cloner.py&quot;, line 245, in execute_job
    clone(self.vc, volname, job[0].decode(&apos;utf-8&apos;), job[1].decode(&apos;utf-8&apos;), self.state_table, should_cancel)
  File &quot;/usr/share/ceph/mgr/volumes/fs/async_cloner.py&quot;, line 220, in clone
    start_clone_sm(volume_client, volname, index, groupname, subvolname, state_table, should_cancel)
  File &quot;/usr/share/ceph/mgr/volumes/fs/async_cloner.py&quot;, line 200, in start_clone_sm
    (next_state, finished) = handler(volume_client, volname, index, groupname, subvolname, should_cancel)
  File &quot;/usr/share/ceph/mgr/volumes/fs/async_cloner.py&quot;, line 157, in handle_clone_in_progress
    do_clone(volume_client, volname, groupname, subvolname, should_cancel)
  File &quot;/usr/share/ceph/mgr/volumes/fs/async_cloner.py&quot;, line 153, in do_clone
    bulk_copy(fs_handle, src_path, dst_path, should_cancel)
  File &quot;/usr/share/ceph/mgr/volumes/fs/async_cloner.py&quot;, line 144, in bulk_copy
    cptree(source_path, dst_path)
  File &quot;/usr/share/ceph/mgr/volumes/fs/async_cloner.py&quot;, line 134, in cptree
    sync_attrs(fs_handle, d_full_dst, stx)
  File &quot;/usr/share/ceph/mgr/volumes/fs/async_cloner.py&quot;, line 77, in sync_attrs
    fs_handle.lchown(target_path, source_statx[&quot;uid&quot;], source_statx[&quot;gid&quot;])
  File &quot;cephfs.pyx&quot;, line 931, in cephfs.LibCephFS.lchown (/home/jenkins-build/build/workspace/ceph-dev-new-build/ARCH/x86_64/AVAILABLE_ARCH/x86_64/AVAILABLE_DIST/centos7/DIST/centos7/MACHINE_SIZE/huge/MACHINE_TYPE/braggi/release/14.2.8-83-g2757cae/rpm/el7/BUILD/ceph-14.2.8-83-g2757cae/build/src/pybind/cephfs/pyrex/cephfs.c:9836)
  File &quot;cephfs.pyx&quot;, line 907, in cephfs.LibCephFS.chown (/home/jenkins-build/build/workspace/ceph-dev-new-build/ARCH/x86_64/AVAILABLE_ARCH/x86_64/AVAILABLE_DIST/centos7/DIST/centos7/MACHINE_SIZE/huge/MACHINE_TYPE/braggi/release/14.2.8-83-g2757cae/rpm/el7/BUILD/ceph-14.2.8-83-g2757cae/build/src/pybind/cephfs/pyrex/cephfs.c:9507)
TypeError: uid must be an int
```

**Comment by ajarr** [comment]
http://pulpito.front.sepia.ceph.com:80/rraja-2020-03-13_19:04:05-fs-wip-sync-attrs-type-fix-nautilus-distro-basic-smithi/

**Comment by ajarr** [comment]
> http://pulpito.front.sepia.ceph.com:80/rraja-2020-03-13_19:04:05-fs-wip-sync-attrs-type-fix-nautilus-distro-basic-smithi/

@vshankar the tests passed. can you please review?

**Comment by vshankar** [comment]
> @vshankar the tests passed. can you please review?

sure -- I'll do that asap.

**Comment by vshankar** [comment]
minor nit: 

* commit c49df1c0b999f1a403f27545da524cbf5c82fb3a mentions `copy_clone` -- should be `copy_file`
* for the other supporting commits that have been cherry picked, wouldn't the respective tracker ticket need mention in this PR (first comment?)

rest looks good!

**Comment by smithfarm** [comment]
```
=================================== FAILURES ===================================
_______________________ HomeTest.test_home_default_lang ________________________

self = <dashboard.tests.test_home.HomeTest testMethod=test_home_default_lang>

    def test_home_default_lang(self):
        self._get('/')
>       self.assertStatus(200)

tests/test_home.py:19: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../../../../build/dashboard/py27-cov/local/lib/python2.7/site-packages/cheroot/test/webtest.py:392: in assertStatus
    self._handlewebError(msg)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <dashboard.tests.test_home.HomeTest testMethod=test_home_default_lang>
msg = 'Status 404 Not Found does not match 200'

    def _handlewebError(self, msg):
        print('')
        print('    ERROR: %s' % msg)
    
        if not self.interactive:
>           raise self.failureException(msg)
E           AssertionError: Status 404 Not Found does not match 200
```

The same exact error is happening now in https://github.com/ceph/ceph/pull/33965

It appears to be blocking "make check" in nautilus.

**Comment by ajarr** [comment]
> or nit:
> 
> * commit [c49df1c](https://github.com/ceph/ceph/commit/c49df1c0b999f1a403f27545da524cbf5c82fb3a) mentions `copy_clone` -- should be `copy_file`



> minor nit:
> 
> * commit [c49df1c](https://github.com/ceph/ceph/commit/c49df1c0b999f1a403f27545da524cbf5c82fb3a) mentions `copy_clone` -- should be `copy_file`

fixed commit message. This was the only change in this update. Do I've to re-test in teuthology?

> * for the other supporting commits that have been cherry picked, wouldn't the respective tracker ticket need mention in this PR (first comment?)
> 

I am not sure which commits you're referring to. The supporting doc commits (https://github.com/ceph/ceph/pull/33877/commits/2508ad1faf7180b812ec711f7039a3defaa2574d , https://github.com/ceph/ceph/pull/33877/commits/5ef2aaf68732f6009437335975c1ef168f73bc47) were the ones that were missed in the original backport that have already been marked as resolved.
The statx commit https://github.com/ceph/ceph/pull/33877/commits/bee705c4332459268 doesn't have a original tracker ticket. The other commit are part of the cephfs shell tracker tickets that we agreed not to backport to nautilus.

> rest looks good!

**Comment by vshankar** [comment]
> > minor nit:
> > 
> > * commit [c49df1c](https://github.com/ceph/ceph/commit/c49df1c0b999f1a403f27545da524cbf5c82fb3a) mentions `copy_clone` -- should be `copy_file`
> 
> @vshankar fixed commit message. This was the only change in this update. Do I've to re-test in teuthology?

not needed.

> 
> > * for the other supporting commits that have been cherry picked, wouldn't the respective tracker ticket need mention in this PR (first comment?)
> 
> I am not sure which commits you're referring to. The supporting doc commits ([2508ad1](https://github.com/ceph/ceph/commit/2508ad1faf7180b812ec711f7039a3defaa2574d) , [5ef2aaf](https://github.com/ceph/ceph/commit/5ef2aaf68732f6009437335975c1ef168f73bc47)) were the ones that were missed in the original backport that have already been marked as resolved.
> The statx commit [bee705c](https://github.com/ceph/ceph/commit/bee705c4332459268) doesn't have a original tracker ticket. The other commit are part of the cephfs shell tracker tickets that we 
agreed not to backport to nautilus.

ack -- makes sense. thanks!

> 
> > rest looks good!

**Comment by ajarr** [comment]
jenkins test make check

**Comment by smithfarm** [comment]
make check failure is the same as is happening in all nautilus PRs:

```
E           AssertionError: Status 404 Not Found does not match 200
```

So: unrelated.

**Comment by gregsfortytwo** [comment]
http://pulpito.front.sepia.ceph.com/gregf-2020-03-17_18:33:07-fs-wip-greg-nautilus-nautilus-testing-317-distro-basic-smithi/
(And multimds http://pulpito.front.sepia.ceph.com:80/gregf-2020-03-17_20:27:31-multimds-wip-greg-nautilus-nautilus-testing-317-distro-basic-smithi but I don't think that's checking this one.)
Looking good so far.

**Comment by smithfarm** [comment]
jenkins test make check

**Pull request merged**
