### PR TITLE
qa/tests: trying using more ditro for clients upgrade tests

### PR DESCRIPTION
**Pull request by yuriw**
Signed-off-by: Yuri Weinstein <yweinste@redhat.com>

### CODE REVIEW

**Comment by yuriw** [comment]
http://pulpito.ceph.com/teuthology-2018-05-18_01:52:11-upgrade:client-upgrade-hammer-mimic-distro-basic-ovh/

**Comment by liewegas** [comment]
er, actually, drop rhel and 18.04, we don't have old builds for those?

**Comment by yuriw** [comment]
@liewegas actually that was the point - testing `hammer` clients on `mimic` cluster
We will have a PR that would use `filter` for `crontab` items like:

`DISTRO_MIMIC="ubuntu_16.04,ubuntu_18.04,centos_7.4,rhel_7.5"`
`45 01 * * *  CEPH_BRANCH=mimic; MACHINE_NAME=ovh; /home/teuthology/bin/cron_wrapper teuthology-suite -v -c $CEPH_BRANCH  -n 7 -m $MACHINE_NAME -s upgrade/client-upgrade-hammer -k distro -e $CEPH_QA_EMAIL --suite-branch hammer --filter $DISTRO_MIMIC`

**Comment by yuriw** [comment]
`CEPH_BRANCH=mimic; MACHINE_NAME=ovh; teuthology-suite -v -c $CEPH_BRANCH  -n 7 -m $MACHINE_NAME -s upgrade/client-upgrade-luminous -k distro -e $CEPH_QA_EMAIL --suite-repo https://github.com/yuriw/ceph  --suite-branch wip-yuriw-clients-fix-luminous --filter "ubuntu_16.04,ubuntu_18.04,centos_7.4,rhel_7.5" -p 70`

http://pulpito.ceph.com/teuthology-2018-05-18_19:56:11-upgrade:client-upgrade-luminous-mimic-distro-basic-ovh/

**Comment by yuriw** [comment]
agreed with @jdurgin remove

**Pull request closed without merging**
