### PR TITLE
cmake: pass static linkflags to the linker who links libcommon

### PR DESCRIPTION
**Pull request by tchaikov**
Signed-off-by: Kefu Chai <kchai@redhat.com>

### CODE REVIEW

**Comment by tchaikov** [comment]
this should address the failure of http://pulpito.ceph.com/kchai-2018-01-03_10:15:28-rados-wip-kefu-testing-2018-01-03-1138-distro-basic-mira/2019418/

**Comment by tchaikov** [comment]
the test still fails. see http://qa-proxy.ceph.com/teuthology/kchai-2018-01-03_15:09:09-rados-wip-kefu-testing-2018-01-03-2154-distro-basic-mira/2019863/teuthology.log
```
2018-01-03T16:06:27.777 INFO:teuthology.orchestra.run.mira056.stdout: ceph-test : Depends: libradosstriper1 but it is not going to be installed
2018-01-03T16:06:27.777 INFO:teuthology.orchestra.run.mira056.stdout:             Depends: libstdc++6 (>= 6) but 5.4.0-6ubuntu1~16.04.5 is to be installed
```

**Comment by cbodley** [comment]
@tchaikov looking at the teuthology log i'm seeing failures like `Depends: libstdc++6 (>= 6) but 5.4.0-6ubuntu1~16.04.5 is to be installed`. is the issue that our binaries were still pulling in the shared libstdc++, and that was somehow being reflected in the deb dependencies?

**Comment by tchaikov** [comment]
@cbodley sadly, yes. that's exactly what i am trying to fix here.

**Comment by cbodley** [comment]
okay - is this happening on master too? i see that your testing branch includes adam's update to c++17, but i'm not sure what else in there would cause this. i also don't see where we're enabling this `WITH_STATIC_LIBSTDCXX` option for our builds

**Comment by tchaikov** [comment]
@cbodley this is happening on master too. `WITH_STATIC_LIBSTDCXX` is enabled at https://github.com/ceph/ceph-build/blob/master/scripts/build_utils.sh#L510 .

**Comment by tchaikov** [comment]
being tested at http://pulpito.ceph.com/kchai-2018-01-04_11:59:52-rados-wip-kefu-testing-2018-01-04-1836-distro-basic-smithi/ . the fix works.

@cbodley thanks for your reminder. i checked the flags passed to cmake, the `WITH_STATIC_LIBSTDCXX` was missing! https://github.com/ceph/ceph-build/pull/942/commits/182455da0e75ffed8a8d20e1f778a0f31bd85544 should address this issue.

**Pull request merged**
