### PR TITLE
[DNM] jewel: osd/ECBackend.cc: 201: FAILED assert(res.errors.empty())

### PR DESCRIPTION
**Pull request by dzafman**
http://tracker.ceph.com/issues/17970
http://tracker.ceph.com/issues/17857

Backport of pull request #11449 (makes next backport go cleaner)
Backport of pull request #9304 
Backport of pull request #11914

### CODE REVIEW

**Comment by dzafman** [comment]
The last commit is empty, so it may be removed before we merge this.

**Comment by dachary** [comment]
jenkins test this please

**Comment by dachary** [comment]
@tchaikov does this backport look good to merge ? It passed the rados (http://tracker.ceph.com/issues/17851#note-12) suite. It also passed the upgrade/jewel-x and upgrade/hammer-x (http://tracker.ceph.com/issues/17851#note-15) suites. Note that it won't be included in 10.2.4, reason why it targets jewel-next.

**Comment by tchaikov** [comment]
note, commit 5bc5533 "test: Disable tests due to recovery race" is not included in jewel-next, so 1fceb344bef86895b8e449aeec2f369eb929c5d3  is not backported.

**Comment by smithfarm** [comment]
At http://tracker.ceph.com/issues/17970#note-4 someone just reported that they are getting OSD crashes with this PR.

**Comment by dachary** [comment]
DNM while waiting for clarification at http://tracker.ceph.com/issues/17970#note-5

**Comment by aarontc** [comment]
New bug opened at http://tracker.ceph.com/issues/18162 in response to http://tracker.ceph.com/issues/17970

**Comment by dzafman** [comment]
Added commit that fixed a problem with the original fix.

**Comment by aarontc** [comment]
Running the changeset with the latest commit, based on either 10.2.3 or 10.2.4, resolves the specific issue this PR is against on my cluster. The new bug report I've opened seems unrelated to this PR IMHO.

**Comment by dachary** [comment]
DNM because it conflicts with another pull request

**Comment by dzafman** [comment]
@dachary I've created a version of this rebased on a common commit between this an the other conflicting pull request.  Not those two merge onto jewel cleanly.  I'm going to make sure that it build, then I'll push it here and get rid of the DNM  on both.

**Comment by dachary** [comment]
@dzafman ack !

**Comment by dzafman** [comment]
No longer conflicts with ceph/ceph#12288

**Comment by smithfarm** [comment]
Conflicts, possibly with #12978

**Comment by dzafman** [comment]
Merged with ceph/ceph#13146

**Pull request closed without merging**
