### PR TITLE
DNM: hammer: ceph-disk: wrong log level of command

### PR DESCRIPTION
**Pull request by jordan41177**
Backport: http://tracker.ceph.com/issues/15775

### CODE REVIEW

**Comment by jordan41177** [comment]
Can it run CI again? It seems that build fail at the beginning.

**Comment by tchaikov** [comment]
thanks Desmond!

> Can it run CI again?

yeah, i think so. you can rebase your changes and "git push -f" to your remote branch to update this PR so the CI can be triggered again.

but i don't think it's a transient issue, see https://github.com/ceph/ceph/pull/8987, which also failed due to the same problem. so re-running the CI might also fail. but it's worth a try =)

**Comment by dachary** [comment]
@jordan41177 could you please amend the description of the commits 8a66e892883e84c97c279c91322856088d750d6b and 9b91f69ad3104d70574421880caf29a0ccf04729 to explain how the conflict was resolved and what it was about ?

**Comment by dachary** [comment]
There should be no need to add new commits to a backport. If there is, you need to clearly explain why this is necessary, in the commit message. If you don't feel confortable writing this in english, give it a try in your native language first and we'll work from that.

**Comment by jordan41177** [comment]
@dachary 
Sorry.. I missed some commits that can avoid the conflict happened.
I repushed and this time it doesn't need my fix anymore.
I want this backport fix because that I want to enhance the 'ceph-deploy' in all supported version.
There are fixed in Infernails and Jewel, but not yet in Hammer.

https://github.com/ceph/ceph-deploy/pull/392

**Comment by smithfarm** [comment]
@dachary Does this still need to be DNM?

**Comment by smithfarm** [comment]
@dachary ping, does this still need to be DNM?

**Comment by jordan41177** [comment]
@dachary Done.

**Comment by liewegas** [comment]
@jordan41177 ping? do we care about this anymore?  please reopen if so; hamme ris getting old though!

**Comment by jordan41177** [comment]
@liewegas  this's not important though. thx..

**Pull request closed without merging**
