### PR TITLE
man/conf.py: replace f-string with format

### PR DESCRIPTION
**Pull request by sebastian-philipp**
I'm pretty sure this is causing https://jenkins.ceph.com/job/ceph-dev-new-build/ARCH=x86_64,AVAILABLE_ARCH=x86_64,AVAILABLE_DIST=centos7,DIST=centos7,MACHINE_SIZE=gigantic/42172//consoleFull

---
I hope this fixes:

```
Running Sphinx v1.1.3

Configuration error:
There is a syntax error in your configuration file: invalid syntax (conf.py, line 53)
make[2]: *** [doc/man/ceph-syn.8] Error 1
make[1]: *** [doc/man/CMakeFiles/manpages.dir/all] Error 2
```

Signed-off-by: Sebastian Wagner <sebastian.wagner@suse.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by tchaikov** [comment]
@sebastian-philipp discussed with the team. we believe that octopus for el7 is suffice for our user to upgrade from an older version on el7 to octopus and newer releases.

**Comment by tchaikov** [comment]
i will prepare a PR to disable the master build on el7.

**Comment by tchaikov** [comment]
https://github.com/ceph/ceph-build/pull/1597

**Comment by sebastian-philipp** [comment]
@bk201  @tchaikov note that in case we backport the PR to octopus, we might need this one as well.

**Pull request closed without merging**
