### PR TITLE
doc/release/nautilus: 14.2.2 changes redone

### PR DESCRIPTION
**Pull request by liewegas**
I don't understand how the origina;l notes were done.  I took the ceph-release-notes output, cleaned up the nautilus: prefixes, s/*  /* /, and sorted.. but it looks like the original changelog as edited manually?

I just needed to get the last minute PRs included.  Is there a better process for doing this?

### CODE REVIEW

**Comment by theanalyst** [comment]
> I don't understand how the origina;l notes were done. I took the ceph-release-notes output, cleaned up the nautilus: prefixes, s/* /* /, and sorted.. but it looks like the original changelog as edited manually?
For backport releases there is a --strict option, there is always some manual cleanup involved for PR titles that don't mention much, also many qa:* prs are usually dropped, but this is fine for now
> I just needed to get the last minute PRs included. Is there a better process for doing this?

**Comment by theanalyst** [comment]
jenkins render docs

**Comment by theanalyst** [comment]
> > I don't understand how the origina;l notes were done. I took the ceph-release-notes output, cleaned up the nautilus: prefixes, s/* /* /, and sorted.. but it looks like the original changelog as edited manually?
For backport releases there is a --strict option, there is always some manual cleanup involved for PR titles that don't mention much, also many qa:* prs are usually dropped, but this is fine for now
> > I just needed to get the last minute PRs included. Is there a better process for doing this?

**Comment by smithfarm** [comment]
Yeah, in addition to adding the missing PRs, this seems to have reverted some of the manual edits I did to the raw script output to make it more palatable. Sorry you had to deal with it, @liewegas - I was on vacation last week.

**Comment by smithfarm** [comment]
> I just needed to get the last minute PRs included. Is there a better process for doing this?

I would have checked `git log` for the PRs and manually copy-pasted their titles into the changelog.

**Comment by smithfarm** [comment]
> but it looks like the original changelog as edited manually?

Yes, it was. I standardized the component prefixes (which are all over the place) before sorting, and engaged in some punctuation pedantry.

**Comment by smithfarm** [comment]
Oops, this replaced the 14.2.1 changelog with the 14.2.2 one :-1:

**Pull request merged**
