### PR TITLE
run-make-check.sh: use clang-17 if available

### PR DESCRIPTION
**Pull request by tchaikov**
now that clang-17 has been released, let's use it if available.

Signed-off-by: Kefu Chai <tchaikov@gmail.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by tchaikov** [comment]
jenkins test make check arm64

**Comment by tchaikov** [comment]
jenkins test make check

**Comment by yuvalif** [comment]
don't we need https://github.com/ceph/ceph/pull/49403 to be merged first, so boost compilation does not fail for clang16?

**Comment by tchaikov** [comment]
> don't we need #49403 to be merged first, so boost compilation does not fail for clang16?

yes, it needs review first and then we can gets it merged.

**Comment by yuvalif** [comment]
> > don't we need #49403 to be merged first, so boost compilation does not fail for clang16?
> 
> yes, it needs review first and then we can gets it merged.

#49403 reviwed and tested with clang16. 
note that https://github.com/ceph/ceph/pull/48828 is still needed in order to pass compilation, so probably also needs to be merged first

**Comment by tchaikov** [comment]
@yuvalif hi, Yuval, thanks for the suggestion. will hold back until #48828 is merged.

**Comment by yuvalif** [comment]
> @yuvalif hi, Yuval, thanks for the suggestion. will hold back until #48828 is merged.

above PR is merged. clang16 builds ceph without any errors (there are some warnings).

**Review by yuvalif — APPROVED** [review]

**Comment by yuvalif** [comment]
@tchaikov can you please rebase?

**Comment by tchaikov** [comment]
@yuvalif rebased.

**Pull request merged**
