### PR TITLE
pacific: mgr/dashboard: Predefine labels in create host form 

### PR DESCRIPTION
**Pull request by nizamial09**
backport tracker: https://tracker.ceph.com/issues/53377

---

backport of https://github.com/ceph/ceph/pull/43996
parent tracker: https://tracker.ceph.com/issues/53315

this backport was staged using ceph-backport.sh version 16.0.0.6848
find the latest version at https://github.com/ceph/ceph/blob/master/src/script/ceph-backport.sh

### CODE REVIEW

**Comment by nizamial09** [comment]
jenkins test dashboard

**Comment by nizamial09** [comment]
jenkins test dashboard cephadm

**Comment by nizamial09** [comment]
jenkins test dashboard

**Comment by nizamial09** [comment]
jenkins test dashboard cephadm

**Review by alfonsomthd — APPROVED** [review]

**Review by avanthakkar — APPROVED** [review]

**Comment by nizamial09** [comment]
@epuertat: e2e's are failing for different reasons which is being fixed over here: https://github.com/ceph/ceph/pull/44086 The newly added test is passing anyway.
```
  ✓ should add a host with some predefined labels and verify it (6748ms)
```

**Pull request merged**
