### PR TITLE
pacific: pybind/mgr: fix flake8

### PR DESCRIPTION
**Pull request by adk3798**
Backport of #47385

Signed-off-by: Avan Thakkar <athakkar@redhat.com>
(cherry picked from commit a124f6c47b119a8741f347ea5a809f3fb48d6679)

### CODE REVIEW

**Review by guits — APPROVED** [review]

**Comment by guits** [comment]
jenkins test api

**Review by idryomov — APPROVED** [review]

**Comment by avanthakkar** [comment]
jenkins test make check

**Comment by idryomov** [comment]
jenkins test make check

**Comment by idryomov** [comment]
jenkins test make check

**Comment by idryomov** [comment]
jenkins test make check

**Pull request merged**
