### PR TITLE
rgw: add support for Keystone v3

### PR DESCRIPTION
**Pull request by rzarzynski**
This PR is basing on #6337 by Mark Barnes which seems to be abandoned by the original author. The reworked version addresses some issues and avoids extensive code shuffling (number of affected lines has been significantly reduced).

@yehudasa Although commit messages mention about the authorship, I think this is not enough. What is the practice for handling cases like this one? Can we add ```Signed-off-by``` from the original commit there?

TODO:
* ~~rework parsing in ```KeystoneToken``` to be proof for fixes in ```S3Extension``` of Keystone~~ (done).

### CODE REVIEW

**Comment by yehudasa** [comment]
@rzarzynski overall ok, see my comments

**Comment by rzarzynski** [comment]
@yehudasa the PR has been rebased according to your comments. The new version needs validation with Tempest and s3-tests. The test matrix is pretty big, so I added the _DNM_ tag once again.

**Comment by rzarzynski** [comment]
@yehudasa s3-tests and Tempest haven't found any regression in the new version of this PR. I'm removing the _DNM_ tag right now.

**Comment by yehudasa** [comment]
@rzarzynski this PR has some conflicts now (probably due to nfs branch merged in)

**Comment by rzarzynski** [comment]
@yehudasa I've just rebased the PR. Previous version is [available](https://github.com/rzarzynski/ceph/tree/wip-rgw-keystone-v3-rzarzynski-old-5) as well.

**Comment by rzarzynski** [comment]
@yehudasa replaced/removed assertions from the last commit.

**Comment by MartinHoustonOccado** [comment]
That build had a single failure:
[  FAILED  ] TestImageWatcher.NotifyAcquiredLock (10015 ms)
Maybe just retry?

**Comment by mattbenjamin** [comment]
We seem to have not noticed when the original author pushed some updates to his original change, on Feb. 18

https://github.com/ocadotechnology/ceph/commit/716f51a37a8593e03f54fe6a98607abef4cc1cd2

**Comment by rzarzynski** [comment]
During rebase something went wrong. I had to push rectified version. Matt's comments are available [here](https://github.com/rzarzynski/ceph/commits/wip-rgw-keystone-v3-rzarzynski-old-8).

**Comment by yehudasa** [comment]
merged on a separate PR (with slightly modified commit messages). See https://github.com/ceph/ceph/pull/7719

**Pull request closed without merging**
