### PR TITLE
ceph-mixin: Update mixin to include alerts for the nvmeof gateway(s)

### PR DESCRIPTION
**Pull request by pcuzner**
This change adds alerts based on the metrics emitted from the embedded prometheus exporter in the nvmeof gateway.

Fixes: https://tracker.ceph.com/issues/64335 

Signed-off-by: Paul Cuzner <pcuzner@ibm.com>
## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [x] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Comment by pcuzner** [comment]
jenkins retest this please

**Comment by pcuzner** [comment]
jenkins retest this please

**Review by aaSharma14 — APPROVED** [review]
Since all the linting and syntax checks pass, LGTM! Thanks @pcuzner

**Comment by pcuzner** [comment]
@aaSharma14 will you be merging?

**Comment by cloudbehl** [comment]
@pcuzner can you raise backport of it in Squid and Reef in upstream

**Pull request merged**
