### PR TITLE
jewel: rgw: fix chained cache invalidation to prevent cache size growth

### PR DESCRIPTION
**Pull request by mattbenjamin**
http://tracker.ceph.com/issues/22584

### CODE REVIEW

**Comment by tchaikov** [comment]
retest this please.

**Comment by mkogan1** [comment]
jenkins test this please

**Comment by mkogan1** [comment]
jenkins test this please

**Comment by mkogan1** [comment]
jenkins test this please

**Comment by adamemerson** [comment]
Jenkins, retest this please.

**Comment by smithfarm** [comment]
JFYI jewel make check is currently broken

**Comment by adamemerson** [comment]
Jenkins, retest this please

**Comment by smithfarm** [comment]
Integration testing: http://tracker.ceph.com/issues/21742#note-11

Will post a summary to the PR when the testing is complete.

**Comment by smithfarm** [comment]
This PR passed two RGW runs at http://tracker.ceph.com/issues/21742#note-11

It will be merged soon, unless there any objections.

**Comment by adamemerson** [comment]
@smithfarm No objections from me!

**Comment by mattbenjamin** [comment]
@smithfarm 👍

**Pull request merged**
