### PR TITLE
mon/MonClient: fix potential access violation

### PR DESCRIPTION
**Pull request by xiexingguo**
Signed-off-by: xie xingguo <xie.xingguo@zte.com.cn>

- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by xiexingguo** [comment]
@liewegas  Just saw this in http://qa-proxy.ceph.com/teuthology/sage-2019-03-26_03:52:56-rados-wip-sage-testing-2019-03-25-1934-distro-basic-smithi/3774206/teuthology.log

**Comment by xiexingguo** [comment]
retest this please

**Comment by tchaikov** [comment]
@xiexingguo i am proposing an alternative, see #27196

**Comment by liewegas** [comment]
Nice catch!  @tchaikov 's fix is nicer tho

**Pull request closed without merging**
