### PR TITLE
mon: MonitorDBStore: get_next_key() only if prefix matches

### PR DESCRIPTION
**Pull request by jecluis**
http://tracker.ceph.com/issues/12483

### CODE REVIEW

**Comment by dachary** [comment]
@jecluis could this backport be the cause of these failures : http://pulpito.ceph.com/loic-2015-08-15_22:14:11-upgrade:hammer-hammer-backports---basic-multi/ ? (see more at http://tracker.ceph.com/issues/12701#note-10)

**Comment by jecluis** [comment]
@dachary I don't think so, but feel free to test without it.

Besides, the stack trace in the tracker issue feels a lot more related with memory issues rather than the store itself, but I may be wrong.

**Comment by dachary** [comment]
@jecluis thanks for taking a look. Running the upgrade suite again to figure out if it's a permanent error or something else. http://pulpito.ceph.com/loic-2015-08-19_12:26:39-upgrade:hammer-hammer-backports---basic-vps/

**Comment by dachary** [comment]
@jecluis running the hammer upgrade suite after removing this commit works. It's easy to reproduce, it fails all upgrade jobs.

**Comment by dachary** [comment]
Also cherry-pick https://github.com/ceph/ceph/pull/5834

**Comment by jecluis** [comment]
patch to be cherry-picked is 70d31082fd3dc8c7857994104577f1a3631c678c

**Comment by jecluis** [comment]
Patch has been cherry-picked. Okay to test.

**Comment by dachary** [comment]
@jecluis thanks !

**Pull request merged**
