### PR TITLE
nautilus: mgr/dashboard: iSCSI should allow exporting an RBD image with Journaling enabled

### PR DESCRIPTION
**Pull request by ricardoasmarques**
https://tracker.ceph.com/issues/39616

### CODE REVIEW

**Comment by yuriw** [comment]
[wip-yuri2-testing-2019-05-16-1555-nautilus](https://trello.com/c/VvCEDimT/616-wip-yuri2-testing-2019-05-16-1555-nautilus)

**Comment by ricardoasmarques** [comment]
jenkins test make check

**Comment by smithfarm** [comment]
`135/168 Test #160: unittest_rgw_amqp .......................***Failed    8.20 sec`

Note that this unrelated failure is happening in other nautilus PRs, too, at the moment.

**Comment by ricardoasmarques** [comment]
jenkins retest this

**Comment by ricardoasmarques** [comment]
jenkins retest this please

**Comment by ricardoasmarques** [comment]
Adding `nautilus-batch-1` since make check is now passing.

**Pull request merged**
