### PR TITLE
cryptic error message in ceph interactive mode

### PR DESCRIPTION
**Pull request by stiopaa1**
Fixes: #11459
Signed-off-by: Michal Jarzabek <stiopa@gmail.com>

### CODE REVIEW

**Comment by dzafman** [comment]
I propose that like at a bash shell prompt that exit should work.  Probably better than quit, but leave quit for compatibility.

$ git diff ceph.in
diff --git a/src/ceph.in b/src/ceph.in
index 317b259..5f7d34c 100755
--- a/src/ceph.in
+++ b/src/ceph.in
@@ -337,7 +337,7 @@ if sys.stdin.isatty():
     def read_input():
         while True:
             line = raw_input(PROMPT).rstrip()
-            if line in ['q', 'quit', 'Q']:
+            if line in ['q', 'quit', 'Q', 'exit']:
                 return None
             if line:
                 return line

**Comment by dachary** [comment]
@stiopaa1 +1 on @dzafman proposal

**Comment by tchaikov** [comment]
yeah, that's probably the best we can do at this moment, maybe we'd better have a `help` command.

**Comment by stiopaa1** [comment]
I was thinking myself why wouldn't we just add exit, but thought that maybe there was some specific reason of not doing so. 

So what's the process now? Should I change this commit to what @dzafman proposed?

**Comment by dachary** [comment]
> Should I change this commit to what @dzafman proposed? 

If you agree to the change (and it looks like you do), yes please amend your fix to match @dzafman proposal.

**Pull request merged**
