### PR TITLE
mds: skip openfiletable's node prefetch

### PR DESCRIPTION
**Pull request by xxhdx1985126**
The kernel client keeps files' relative caps so that it wouldn't need to
consult mds for the caps unless they're revoke explicitly, which could
leave large amounts of files open on the mdses. To prevent the mds from
loading large amounts not really opened files, the client would drop those
caps when reconnecting to mdses.

However, when the mdses recover from some kind of disaster, files cached
by clients before the reconnect are still "opened" in the openfiletable,
which makes the inodes prefetch phase of openfiletable load large amounts
inodes whose caps are probably already dropped by clients. The worst scenario
is that mdses can never come to up:active unless administrators adjust the
heartbeat grace to a very large value.

Fixes: http://tracker.ceph.com/issues/40159
Signed-off-by: Xuehan Xu <xuxuehan@360.cn>

- [x] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by ukernel** [comment]
mds must load open_file_table for inodes with writebale_range
 
please check if following change help.
```
diff --git a/src/mds/OpenFileTable.cc b/src/mds/OpenFileTable.cc
index 57f6d577e2..a90108c546 100644
--- a/src/mds/OpenFileTable.cc
+++ b/src/mds/OpenFileTable.cc
@@ -1017,6 +1017,12 @@ void OpenFileTable::_open_ino_finish(inodeno_t ino, int r)
 
 void OpenFileTable::_prefetch_dirfrags()
 {
+  {
+    prefetch_state = FILE_INODES;
+    _prefetch_inodes();
+    return;
+  }
+
   dout(10) << __func__ << dendl;
   ceph_assert(prefetch_state == DIRFRAGS);

```

**Comment by xxhdx1985126** [comment]
> mds must load open_file_table for inodes with writebale_range
> 
> please check if following change help.
> 
> ```
> diff --git a/src/mds/OpenFileTable.cc b/src/mds/OpenFileTable.cc
> index 57f6d577e2..a90108c546 100644
> --- a/src/mds/OpenFileTable.cc
> +++ b/src/mds/OpenFileTable.cc
> @@ -1017,6 +1017,12 @@ void OpenFileTable::_open_ino_finish(inodeno_t ino, int r)
>  
>  void OpenFileTable::_prefetch_dirfrags()
>  {
> +  {
> +    prefetch_state = FILE_INODES;
> +    _prefetch_inodes();
> +    return;
> +  }
> +
>    dout(10) << __func__ << dendl;
>    ceph_assert(prefetch_state == DIRFRAGS);
> ```

Hi, zheng yan. Thanks for your review:-)

However, I don't quite follow you. IIUC, the openfiletable is loaded before openfiletable prefetch inodes, and if inodes with writeable range is really needed by clients, they will be fetched in subsequent code, pasted belew, in MDCache::process_imported_caps() method that opens all the inodes in MDCache::cap_imports. So as far as I can see, mds doesn't need to fetch all inodes in the openfiletable. Am I right about this? Thanks:-)

```
	for (auto p = cap_imports.begin(); p != cap_imports.end(); ++p) {
		CInode *in = get_inode(p->first);
		if (in) {
			ceph_assert(in->is_auth());
			cap_imports_missing.erase(p->first);
			continue;
		}
		if (cap_imports_missing.count(p->first) > 0)
			continue;

		cap_imports_num_opening++;
		dout(10)
					<< "  opening missing ino " << p->first << dendl;
		open_ino(p->first, (int64_t) -1,
				new C_MDC_RejoinOpenInoFinish(this, p->first), false);
		if (!(cap_imports_num_opening % 1000))
			mds->heartbeat_reset();
	}
```

**Comment by xxhdx1985126** [comment]
@ukernel If I'm right, the only thing that needs to be corrected is making process_imported_caps wait for the openfiletable loading to finish before trying to open inodes in MDCache::caps_imported. Am I right? Thanks:-)

**Comment by ukernel** [comment]
it's for MDCache::identify_files_to_recover

**Comment by xxhdx1985126** [comment]
@ukernel Hi, I've tried your suggestion:-)

However, since we have hundreds of millions of files to recover, the "rejoin" phase still took a very long time, which is not acceptable to our users. So, we changed the code to skip the "prefetch" phase and to recover only the files that the clients needs when reconnecting to mdses, the rest opened files are recovered asynchronously after mds booting up. Please take a look:-) Thanks.

**Comment by xxhdx1985126** [comment]
retest this, please

**Comment by ukernel** [comment]
One goal of open file table is avoid using MDCache::open_ino().  MDCache::open_ino() is slow it needs to fetch backtrace for each inode.

**Comment by xxhdx1985126** [comment]
@ukernel @batrick Hi, I've modified this PR to do asynchronous inodes recovery while retaining the efficiency obtained using OpenFileTable:-) Please take a look:-) Thanks:-)

**Comment by xxhdx1985126** [comment]
please unmark

**Comment by xxhdx1985126** [comment]
jenkins retest this, please

**Comment by xxhdx1985126** [comment]
please unmark

**Comment by gregsfortytwo** [comment]
@xxhdx1985126 also needs rebase, @ukernel ping

**Pull request closed without merging**
