### PR TITLE
qa/tasks/cephfs/mount.py: use brctl instead on Ubuntu releases

### PR DESCRIPTION
**Pull request by lxbsz**
To fix:
sudo bash -c 'nmcli connection up ceph-brx'
stderr:Error: Connection activation failed: Activation failed because the device is unmanaged

Fixes: https://tracker.ceph.com/issues/45459
Signed-off-by: Xiubo Li <xiubli@redhat.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by lxbsz** [comment]
Ubuntu 20.04 has the same issue.

**Comment by lxbsz** [comment]
> Guess Canonical hasn't yet figured out that brctl is being deprecated. Honestly, I wonder if we should convert this to use 'ip link add ... type bridge' instead for future-proofness, but we can deal with that when this becomes a real problem.

Sounds a good idea. Let me have a try of this later in the CentOS/Ubuntu's different versions and  releases, since this failure has blocked the integration qa test cases, I will open a new PR for this later.

Thanks Jeff.
BRs

**Comment by lxbsz** [comment]
> Guess Canonical hasn't yet figured out that brctl is being deprecated. Honestly, I wonder if we should convert this to use 'ip link add ... type bridge' instead for future-proofness, but we can deal with that when this becomes a real problem.

@jtlayton I have fixed it here, please check.
Thanks.

**Comment by batrick** [comment]
http://pulpito.ceph.com/pdonnell-2020-05-12_18:14:38-fs-master-distro-basic-smithi/

**Pull request merged**
