### PR TITLE
mgr/rbd_support: fix type annotation of mirror_info

### PR DESCRIPTION
**Pull request by tchaikov**
Signed-off-by: Kefu Chai <kchai@redhat.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Review by trociny — APPROVED** [review]
LGTM (not tested though)

**Comment by trociny** [comment]
BTW, for `get_mirror_mode` callback, the `mode` arg is not a string but an integer (enum). And for `create_snapshot` callback, the `snap_id` is an integer too.

**Comment by tchaikov** [comment]
@trociny Thank you Mykola! fixed and repushed.

**Review by trociny — APPROVED** [review]

**Comment by sebastian-philipp** [comment]
looks like rbd.pyi would benefit from type annotations as well :smile:

**Pull request merged**
