### PR TITLE
buffer: optimize get_contiguous

### PR DESCRIPTION
**Pull request by majianpeng**
misc fix about buffer.

### CODE REVIEW

**Comment by yuyuyu101** [comment]
Why not alloc a enough buffer to store contiguous instead of call "rebuild" again.

**Comment by liewegas** [comment]
if you alloc the requested len instead of tmp.length() you end up duplicating only part of the last buffer, leaving the second half still pinned in memory and wasted.  this approach potentially copies more data but doesn't waste memory.

in a vacuum i would probably lean toward less copying vs wasted memory, but i think that approach would also fragment heavily if you did get_contiguous over successive blocks of the bufferlist, turning it into a chain of buffers the size of the requested contiguous len.  this approach seems like a nice middle ground between that and a blanket rebuild().

the implementation looks right to me!

**Comment by liewegas** [comment]
i'm a little worried that adding asserts in all these methods will serve to slow down the already expensive encode path which does a lot of set_length() calls...

**Comment by majianpeng** [comment]
@liewegas . Update & review again, Thanks!

**Comment by yuandong1222** [comment]
I am not sure it is the most efficient way to impl get_contiguous, since now the Transaction::iterator is the only one which uses this method. Transaction::iterator uses bufferlist::get_contiguous to get char* from op_bl while there are many bufferptrs in op_bl and each one represent an op. 

It seems the op_bl is composed of many bufferptrs, but there is only one bufferraw in most cases. So indeed the bufferlist is contiguous already, and what we need is a new bufferptr whose length equals the whole bufferlist.

**Comment by liewegas** [comment]
@yuandong1222 If we have contiguous but distinct bufferptrs, we should fix the bufferlist append code to avoid that situation in the first place... can you tell where they are coming from?

This looks like the right way to do get_contiguous(), assuming the bufferlist isn't malformed in that way.

**Comment by ukernel** [comment]
this PR breaks MDS.  see http://tracker.ceph.com/issues/11526

**Comment by majianpeng** [comment]
@ukernel . Can you test this https://github.com/ceph/ceph/pull/4537? Thanks!

**Pull request merged**
