### PR TITLE
doc/rados/operations: enhance primary affinity section

### PR DESCRIPTION
**Pull request by anthonyeleven**
doc/rados/operations: enhance primary affinity section

Incorporate enhancements suggested by Frank Schilder <frans@dtu.dk>

Signed-off-by: Anthony D'Atri <anthony.datri@gmail.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by anthonyeleven** [comment]
This is a WIP

**Comment by anthonyeleven** [comment]
@zdover23 Might you be able to help me sort out the reference that's breaking the build check here?  I'm trying to reference a section in a different file.

**Comment by anthonyeleven** [comment]
jenkins test make check

**Comment by anthonyeleven** [comment]
jenkins test make

**Comment by anthonyeleven** [comment]
jenkins test make check

**Comment by zdover23** [comment]
jenkins render docs

**Review by zdover23 — APPROVED** [review]
LGTM

**Pull request merged**
