### PR TITLE
src/common: add rabin chunking for dedup

### PR DESCRIPTION
**Pull request by myoungwon**
Rabin chunking and fingerprint for dedup

Signed-off-by: Hsuan-Heng, Wu <bbiiggppiigg@gmail.com>
Signed-off-by: Myoungwon Oh <ommw@sk.com>

- [x] add rabin fingerprint class
- [x] make test cases

### CODE REVIEW

**Comment by myoungwon** [comment]
@liewegas @bbiiggppiigg Can you take a look?

**Comment by myoungwon** [comment]
- 1. Rabin-karp algorithm
As you know, Rabin-karp algorithm is string-searching algorithm based
on rolling-hash [1][2].
But rolling-hash is not enough to do deduplication because we don't
know the chunk boundary.
So, we need content-based slicing using a rolling hash for
content-defined chunking.
This PR implements the simplest approach (calculate the dynamic chunks
is to calculate the rolling hash and if it matches a pattern (like the
lower N bits are all zeroes) then it’s a chunk boundary).

- 2. Fixed chunk vs content-defined chunk
Actually, content-defined chunking may or may not be optimal solution.
For example,
Data chunk A : abcdefgabcdefgabcdefg
Let's think about Data chunk A's deduplication. Ideal chunk offset is
from 1 to 7 (abcdefg). So, if we use fixed chunk, 7 is optimal chunk
length.
But, in the case of content-based slicing, the optimal chunk length
could not be found (dedup ratio will not be 100%). 
Because we need to find optimal parameter [3] such
as boundary bit, window size and prime value. This is as easy as fixed chunk.
But, content defined chunking is very effective in below case.
Data chunk B : abcdefgabcdefgabcdefg
Data chunk C : Tabcdefgabcdefgabcdefg

- 3. Usage
Users who want to use deduplication need to find the ideal chunk offset. 
To find out ideal chunk offset, Users should discover
the optimal configuration for their data workload via cephdeduptool.
And then, this chunking information will be used for object chunking through
set-chunk api. 


[1] https://en.wikipedia.org/wiki/Rabin%E2%80%93Karp_algorithm
[2]: https://www.infoarena.ro/blog/rolling-hash
[3]: https://moinakg.wordpress.com/tag/rabin-fingerprint/

**Comment by myoungwon** [comment]
@liewegas 
- 1. Rabin-karp algorithm
As you know, Rabin-karp algorithm is string-searching algorithm based
on rolling-hash [1][2].
But rolling-hash is not enough to do deduplication because we don't
know the chunk boundary.
So, we need content-based slicing using a rolling hash for
content-defined chunking.
This PR implements the simplest approach (calculate the dynamic chunks
is to calculate the rolling hash and if it matches a pattern (like the
lower N bits are all zeroes) then it’s a chunk boundary).

- 2. Fixed chunk vs content-defined chunk
Actually, content-defined chunking may or may not be optimal solution.
For example,
Data chunk A : abcdefgabcdefgabcdefg
Let's think about Data chunk A's deduplication. Ideal chunk offset is
from 1 to 7 (abcdefg). So, if we use fixed chunk, 7 is optimal chunk
length.
But, in the case of content-based slicing, the optimal chunk length
could not be found (dedup ratio will not be 100%). 
Because we need to find optimal parameter [3] such
as boundary bit, window size and prime value. This is as easy as fixed chunk.
But, content defined chunking is very effective in below case.
Data chunk B : abcdefgabcdefgabcdefg
Data chunk C : Tabcdefgabcdefgabcdefg

- 3. Usage
Users who want to use deduplication need to find the ideal chunk offset. 
To find out ideal chunk offset, Users should discover
the optimal configuration for their data workload via cephdeduptool.
And then, this chunking information will be used for object chunking through
set-chunk api. 


[1] https://en.wikipedia.org/wiki/Rabin%E2%80%93Karp_algorithm
[2]: https://www.infoarena.ro/blog/rolling-hash
[3]: https://moinakg.wordpress.com/tag/rabin-fingerprint/

**Comment by liewegas** [comment]
The rabin addition look fine. When I tried to test the dedup tool I ran into a few other things though:

- cephdeduptool -> ceph-dedup-tool
- ```
diff --git a/src/tools/ceph_dedup_tool.cc b/src/tools/ceph_dedup_tool.cc
index 1e7e0398a42..372e41084fa 100644
--- a/src/tools/ceph_dedup_tool.cc
+++ b/src/tools/ceph_dedup_tool.cc
@@ -288,9 +288,10 @@ void EstimateDedupRatio::print_status(Formatter *f, ostream &out)
     f->dump_string("PID", stringify(get_pid()));
     for (auto p : local_chunk_statistics) {
       f->open_object_section("fingerprint object");
-      f->dump_string("fingperint", p.first);
+      f->dump_string("fingerprint", p.first);
       f->dump_string("count", stringify(p.second.first));
       f->dump_string("chunk_size", stringify(p.second.second));
+      f->close_section();
     }
```
- when i tried to run this on a large pool it seems to try to enumerate all objects (or at least build a list of a lot of them) instead of processing them as it goes.

**Comment by myoungwon** [comment]
@liewegas Multiple threads will examine each object's chunk offset and fingerprint, and then store its result to temporary store (std::map). This result will be printed out if all of object in the pool are enumerated or SIGINT is received. So, it seems to try to enumerate all objects. 
Do we need print its result when each chunk's calculation is finished?
like 
(object a : dedup ratio --> xx%
offset 0: length: 40 fp: aaa
offset 40: length: 80 fp: bbb)

**Comment by liewegas** [comment]
The behavior doesn't look like that, though.  When I run on a smallish pool i see each objec tname printed out and periodic dumps of json with counts.  On a very large pool, it just sits there, and when i look at debug_ms=1 all it is doing is enumerating objects.. not reading them.

**Comment by myoungwon** [comment]
@liewegas How many objects did you test? I run this on my test pool (~500 objects) several times. But I can  not reproduce the issue you mentioned. Please let me know the cli command and cluster configuration.

**Comment by myoungwon** [comment]
@liewegas hmm.. as you said, it seems that the tool just enumerate objects. Please let me know what cli command did you test because i can not see /ceph/post/ 1aeea859-944d-411e-ba57-fce7b1c710a5/user (permission denied). 
I tested nearly 1M objects on my test pool (using ./bin/ceph-dedup-tool --op estimate --pool dedup_pool --min-chunk 1025  --chunk-algorithm rabin --fingerprint-algorithm rabin). But, I can not re-produce that issue.

**Comment by myoungwon** [comment]
@liewegas Sorry for my mistake. This is because my test code. count_object() enumerate all objects on the target pool to count the number of objects.
I forgot to replace it with pool_stat_t.

**Comment by liewegas** [comment]
rm -f c && bin/cephdeduptool --op estimate --pool ar_data 
--chunk-algorithm rabin --fingerprint-algorithm rabin  --min-chunk 65536 
--max-chunk 512000 --key AQC+sWZYRyxGABAA9/ImKgmTT8dqmIROXVVlSw== -m cpach 
--log-file c --debug-ms 1 --log-to-stderr

this is a branch rebased on master, in case that matters.  see 
github.com/liewegas/ceph wip-rabin

**Comment by liewegas** [comment]
Great, this is working for me now, thanks!  Lots of cleanup we can do here, but that doesn't need to block merging this.

**Comment by liewegas** [comment]
BTW, one thing I noticed is I did ``--min-chunk 65536 --max-chunk 512000`` and all my chunks came out as ~64k.

**Comment by myoungwon** [comment]
@liewegas It depends on --chunk-mask-bit which determine chunk boundary. If you increase this value to 4095 or higher, you can get broader distribution than before.

**Comment by liewegas** [comment]
```
2019-04-23T14:39:49.868 INFO:tasks.workunit.client.0.smithi022.stderr:+ /usr/bin/rados -p dedup_pool put test_rados_obj ./test_rabin_object
2019-04-23T14:39:49.883 INFO:tasks.workunit.client.0.smithi022.stderr:++ /usr/bin/ceph-dedup-tool --op estimate --pool dedup_pool --min-chunk 1015 --chunk-algorithm rabin --fingerprint-algorithm rabin --debug
2019-04-23T14:39:49.883 INFO:tasks.workunit.client.0.smithi022.stderr:++ grep result -a
2019-04-23T14:39:49.883 INFO:tasks.workunit.client.0.smithi022.stderr:++ awk '{print$4}'
2019-04-23T14:39:51.090 INFO:tasks.workunit.client.0.smithi022.stderr:+ RESULT=4438
2019-04-23T14:39:51.090 INFO:tasks.workunit.client.0.smithi022.stderr:+ echo 4438
2019-04-23T14:39:51.090 INFO:tasks.workunit.client.0.smithi022.stderr:+ '[' 4096 -ne 4438 ']'
2019-04-23T14:39:51.091 INFO:tasks.workunit.client.0.smithi022.stderr:+ die 'Estimate failed expecting 7168 result 4438'
2019-04-23T14:39:51.091 INFO:tasks.workunit.client.0.smithi022.stderr:+ echo 'Estimate failed expecting 7168 result 4438'
2019-04-23T14:39:51.091 INFO:tasks.workunit.client.0.smithi022.stderr:+ exit 1
2019-04-23T14:39:51.091 INFO:tasks.workunit.client.0.smithi022.stdout:4438
2019-04-23T14:39:51.091 INFO:tasks.workunit.client.0.smithi022.stdout:Estimate failed expecting 7168 result 4438
```
/a/sage-2019-04-23_06:47:48-rados-wip-sage3-testing-2019-04-22-2146-distro-basic-smithi/3882242

**Comment by myoungwon** [comment]
@liewegas Fixed

**Pull request merged**
