### PR TITLE
  mon/PGMonitor: avoid uint64_t overflow when checking pool 'target/m…

### PR DESCRIPTION
**Pull request by hjwsm1989**
…ax' status.

  Fix http://tracker.ceph.com/issues/12401

  Signed-off-by: huangjun <hjwsm1989@gmail.com>

### CODE REVIEW

**Comment by hjwsm1989** [comment]
@tchaikov would you have time to review it?

**Comment by tchaikov** [comment]
@hjwsm1989, looks good, but i am not sure if "Fix http://tracker.ceph.com/issues/12401" can be recognized by all of our tools/services. could you use the line of

```
Fixes: #12401
```

or 

```
http://tracker.ceph.com/issues/12401 Fixes: #12401
```

just to make sure your commit log has "Fixes: #12401". thanks!

**Comment by hjwsm1989** [comment]
@tchaikov fixed it

**Comment by tchaikov** [comment]
will merge it once the build bot returns.

**Pull request merged**
