### PR TITLE
qa/cephadm: Add cephfs_setup()

### PR DESCRIPTION
**Pull request by varshar16**
Signed-off-by: Varsha Rao <varao@redhat.com>

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by sebastian-philipp** [comment]
Fixes: https://tracker.ceph.com/issues/45595

**Comment by sebastian-philipp** [comment]
relates to

https://github.com/ceph/ceph/blob/59576d17f7fdf155ed411ded8596510b4717fc37/qa/tasks/cephfs/filesystem.py#L615-L630

**Comment by varshar16** [comment]
https://pulpito.ceph.com/varsha-2021-02-03_16:22:38-rados-wip-fix-fs-error-cephadm-test-distro-basic-smithi/
@sebastian-philipp  It just repeatedly deploys mds

```
2021-02-03T16:57:11.562 INFO:journalctl@ceph.mds.a.smithi135.stdout:Feb 03 16:57:11 smithi135 systemd[1]: Stopped Ceph mds.a for f28a2638-663f-11eb-8fbe-001a4aab830c.
2021-02-03T16:57:11.562 INFO:journalctl@ceph.mds.a.smithi135.stdout:Feb 03 16:57:11 smithi135 systemd[1]: Starting Ceph mds.a for f28a2638-663f-11eb-8fbe-001a4aab830c...
2021-02-03T16:57:12.633 INFO:journalctl@ceph.mds.a.smithi135.stdout:Feb 03 16:57:12 smithi135 bash[87669]: 0c86135e7a39a28447cbc112c9fc4983e5d86bd5d805361cdb73d5e0dc647cf5
2021-02-03T16:57:12.633 INFO:journalctl@ceph.mds.a.smithi135.stdout:Feb 03 16:57:12 smithi135 systemd[1]: Started Ceph mds.a for f28a2638-663f-11eb-8fbe-001a4aab830c.
2021-02-03T16:57:15.633 INFO:journalctl@ceph.mds.a.smithi135.stdout:Feb 03 16:57:15 smithi135 systemd[1]: Stopping Ceph mds.a for f28a2638-663f-11eb-8fbe-001a4aab830c...
2021-02-03T16:57:17.005 INFO:journalctl@ceph.mds.a.smithi135.stdout:Feb 03 16:57:16 smithi135 podman[88444]: 0c86135e7a39a28447cbc112c9fc4983e5d86bd5d805361cdb73d5e0dc647cf5
2021-02-03T16:57:19.615 INFO:journalctl@ceph.mds.a.smithi135.stdout:Feb 03 16:57:16 smithi135 systemd[1]: Stopped Ceph mds.a for f28a2638-663f-11eb-8fbe-001a4aab830c.
2021-02-03T16:57:19.616 INFO:journalctl@ceph.mds.a.smithi135.stdout:Feb 03 16:57:17 smithi135 systemd[1]: Starting Ceph mds.a for f28a2638-663f-11eb-8fbe-001a4aab830c...
2021-02-03T16:57:19.616 INFO:journalctl@ceph.mds.a.smithi135.stdout:Feb 03 16:57:17 smithi135 bash[88570]: b9e5946675e9e18125a1d217aed7f503b186141a109c9b0e6d2f259e230058f0
2021-02-03T16:57:19.617 INFO:journalctl@ceph.mds.a.smithi135.stdout:Feb 03 16:57:17 smithi135 systemd[1]: Started Ceph mds.a for f28a2638-663f-11eb-8fbe-001a4aab830c.
```

**Comment by sebastian-philipp** [comment]
fascinating

**Comment by varshar16** [comment]
And here is the test, without this patch: https://pulpito.ceph.com/varsha-2021-02-03_16:38:44-rados-wip-fix-fs-error-cephadm-test-distro-basic-smithi/

I don't see mgr logs being saved for the tests.

**Comment by liewegas** [comment]
Super weird!

I can't decide which way to move forward here.  It feels like we either go down this path of making cephadm fit into the old teuthology role-based mode, which will be somewhat painful but hopefully allow old teuthology tasks to run unchanged.  Or, we throw that away and make the tests deploy MDSs the way a user would, but calling 'ceph fs volume create foo'.  I think the latter gets us to a better end point because we're testing the system the way a user would have it deployed, but it will take some work to fill in various gaps... like waiting for the MDSs to be up, and setting up the internal teuthology state to correspond to deployed daemons.  And mds thrashing etc will of course be tricky.

**Comment by sebastian-philipp** [comment]
What I'm seeing is:

1. `WARNING:tasks.cephfs.filesystem:Unhealthy mds state gid_14441:up:reconnect` (mds.a)

https://github.com/ceph/ceph/blob/f447291c3ac4ecd005083b5dd4ea88b1dcb1067a/qa/tasks/cephfs/filesystem.py#L892

but the mds log looks like so:

```
-- Logs begin at Wed 2021-02-03 16:43:14 UTC. --
Feb 03 16:53:19 smithi135 systemd[1]: Starting Ceph mds.a for f28a2638-663f-11eb-8fbe-001a4aab830c...
Feb 03 16:53:20 smithi135 bash[48998]: 1a707a0e2602c83b8e06c989b5a0b4db38ebbedf288ccf37ff71d3b632e628ed
Feb 03 16:53:20 smithi135 systemd[1]: Started Ceph mds.a for f28a2638-663f-11eb-8fbe-001a4aab830c.
Feb 03 16:53:23 smithi135 systemd[1]: Stopping Ceph mds.a for f28a2638-663f-11eb-8fbe-001a4aab830c...
Feb 03 16:53:27 smithi135 podman[49936]: 1a707a0e2602c83b8e06c989b5a0b4db38ebbedf288ccf37ff71d3b632e628ed
Feb 03 16:53:28 smithi135 systemd[1]: Stopped Ceph mds.a for f28a2638-663f-11eb-8fbe-001a4aab830c.
Feb 03 16:53:28 smithi135 systemd[1]: Starting Ceph mds.a for f28a2638-663f-11eb-8fbe-001a4aab830c...
Feb 03 16:53:29 smithi135 bash[50543]: 97ad1614a5c621f43d173ed98aa8479fad22907c89d4902bbb61519c9bcf198c
Feb 03 16:53:29 smithi135 systemd[1]: Started Ceph mds.a for f28a2638-663f-11eb-8fbe-001a4aab830c.
Feb 03 16:53:32 smithi135 systemd[1]: Stopping Ceph mds.a for f28a2638-663f-11eb-8fbe-001a4aab830c...
Feb 03 16:53:33 smithi135 podman[51606]: 97ad1614a5c621f43d173ed98aa8479fad22907c89d4902bbb61519c9bcf198c
Feb 03 16:53:34 smithi135 systemd[1]: Stopped Ceph mds.a for f28a2638-663f-11eb-8fbe-001a4aab830c.
Feb 03 16:53:34 smithi135 systemd[1]: Starting Ceph mds.a for f28a2638-663f-11eb-8fbe-001a4aab830c...
Feb 03 16:53:34 smithi135 bash[51851]: 40d1e12e763acd13c5d30a9a1ec69c070dca7855c84f25957f7803cb05ab6ba1
Feb 03 16:53:34 smithi135 systemd[1]: Started Ceph mds.a for f28a2638-663f-11eb-8fbe-001a4aab830c.
Feb 03 16:53:38 smithi135 systemd[1]: Stopping Ceph mds.a for f28a2638-663f-11eb-8fbe-001a4aab830c...
Feb 03 16:53:43 smithi135 podman[52940]: 40d1e12e763acd13c5d30a9a1ec69c070dca7855c84f25957f7803cb05ab6ba1
Feb 03 16:53:44 smithi135 systemd[1]: Stopped Ceph mds.a for f28a2638-663f-11eb-8fbe-001a4aab830c.
Feb 03 16:53:44 smithi135 systemd[1]: Starting Ceph mds.a for f28a2638-663f-11eb-8fbe-001a4aab830c...
Feb 03 16:53:45 smithi135 bash[53715]: 0ae7c19548b37115e1aa6ff7273912224173e17bb3ed5844b23c637919ce8f08
Feb 03 16:53:45 smithi135 systemd[1]: Started Ceph mds.a for f28a2638-663f-11eb-8fbe-001a4aab830c.
Feb 03 16:53:49 smithi135 systemd[1]: Stopping Ceph mds.a for f28a2638-663f-11eb-8fbe-001a4aab830c...
Feb 03 16:53:54 smithi135 podman[54853]: 0ae7c19548b37115e1aa6ff7273912224173e17bb3ed5844b23c637919ce8f08
Feb 03 16:53:54 smithi135 systemd[1]: Stopped Ceph mds.a for f28a2638-663f-11eb-8fbe-001a4aab830c.
Feb 03 16:53:54 smithi135 systemd[1]: Starting Ceph mds.a for f28a2638-663f-11eb-8fbe-001a4aab830c...
Feb 03 16:53:55 smithi135 bash[55620]: 0c162877348e5a1344ffa8730f3dfd1e615bddc0e99a1ccf56d2bf462dfc9ae1
Feb 03 16:53:55 smithi135 systemd[1]: Started Ceph mds.a for f28a2638-663f-11eb-8fbe-001a4aab830c.
Feb 03 16:53:59 smithi135 systemd[1]: Stopping Ceph mds.a for f28a2638-663f-11eb-8fbe-001a4aab830c...
Feb 03 16:54:03 smithi135 podman[56807]: 0c162877348e5a1344ffa8730f3dfd1e615bddc0e99a1ccf56d2bf462dfc9ae1
Feb 03 16:54:03 smithi135 systemd[1]: Stopped Ceph mds.a for f28a2638-663f-11eb-8fbe-001a4aab830c.
Feb 03 16:54:04 smithi135 systemd[1]: Starting Ceph mds.a for f28a2638-663f-11eb-8fbe-001a4aab830c...
Feb 03 16:54:05 smithi135 bash[57460]: bcf7820da5a0541b95764962a4a1230534a5153979e2246d75c1ce1f42711318
Feb 03 16:54:05 smithi135 systemd[1]: Started Ceph mds.a for f28a2638-663f-11eb-8fbe-001a4aab830c.
```

while we are stuck in `are_daemons_healthy`:
```
DEBUG:tasks.cephfs.filesystem:are_daemons_healthy: 0/1                                    ...snip...
DEBUG:tasks.cephfs.filesystem:are_daemons_healthy: mds map: {'epoch': 27, 'flags': 18, 'ev...snip...
DEBUG:tasks.cephfs.filesystem:are_daemons_healthy: 0/1                                    ...snip...
DEBUG:tasks.cephfs.filesystem:are_daemons_healthy: mds map: {'epoch': 28, 'flags': 18, 'ev...snip...
WARNING:tasks.cephfs.filesystem:Unhealthy mds state gid_14281:up:replay                   ...snip...
DEBUG:tasks.cephfs.filesystem:are_daemons_healthy: mds map: {'epoch': 29, 'flags': 18, 'ev...snip...
WARNING:tasks.cephfs.filesystem:Unhealthy mds state gid_14281:up:reconnect                ...snip...
DEBUG:tasks.cephfs.filesystem:are_daemons_healthy: mds map: {'epoch': 31, 'flags': 18, 'ev...snip...
DEBUG:tasks.cephfs.filesystem:are_daemons_healthy: 0/1                                    ...snip...
DEBUG:tasks.cephfs.filesystem:are_daemons_healthy: mds map: {'epoch': 31, 'flags': 18, 'ev...snip...
DEBUG:tasks.cephfs.filesystem:are_daemons_healthy: 0/1                                    ...snip...
DEBUG:tasks.cephfs.filesystem:are_daemons_healthy: mds map: {'epoch': 31, 'flags': 18, 'ev...snip...
DEBUG:tasks.cephfs.filesystem:are_daemons_healthy: 0/1                                    ...snip...
DEBUG:tasks.cephfs.filesystem:are_daemons_healthy: mds map: {'epoch': 34, 'flags': 18, 'ev...snip...
WARNING:tasks.cephfs.filesystem:Unhealthy mds state gid_14291:up:reconnect                ...snip...
DEBUG:tasks.cephfs.filesystem:are_daemons_healthy: mds map: {'epoch': 35, 'flags': 18, 'ev...snip...
WARNING:tasks.cephfs.filesystem:Unhealthy mds state gid_14291:up:rejoin                   ...snip...
DEBUG:tasks.cephfs.filesystem:are_daemons_healthy: mds map: {'epoch': 36, 'flags': 18, 'ev...snip...
DEBUG:tasks.cephfs.filesystem:are_daemons_healthy: 0/1                                    ...snip...
DEBUG:tasks.cephfs.filesystem:are_daemons_healthy: mds map: {'epoch': 38, 'flags': 18, 'ev...snip...
WARNING:tasks.cephfs.filesystem:Unhealthy mds state gid_14301:up:replay                   ...snip...
DEBUG:tasks.cephfs.filesystem:are_daemons_healthy: mds map: {'epoch': 39, 'flags': 18, 'ev...snip...
WARNING:tasks.cephfs.filesystem:Unhealthy mds state gid_14301:up:reconnect                ...snip...
DEBUG:tasks.cephfs.filesystem:are_daemons_healthy: mds map: {'epoch': 41, 'flags': 18, 'ev...snip...
DEBUG:tasks.cephfs.filesystem:are_daemons_healthy: 0/1                                    ...snip...
```

https://pulpito.ceph.com/varsha-2021-02-03_16:22:38-rados-wip-fix-fs-error-cephadm-test-distro-basic-smithi/

> I don't see mgr logs being saved for the tests.

Me neither. I also don't see the mds.a logs.

**Comment by sebastian-philipp** [comment]
close?

**Comment by varshar16** [comment]
> close?

Don't you want to fix the issue ? Or are you fine with explicit deployment quick fix for now ?

**Comment by sebastian-philipp** [comment]
https://github.com/ceph/ceph/pull/39251#issuecomment-772704298

**Pull request closed without merging**
