### PR TITLE
testGetContentType and testHead failed

### PR DESCRIPTION
**Pull request by dachary**
http://tracker.ceph.com/issues/12246
http://tracker.ceph.com/issues/12632
http://tracker.ceph.com/issues/12634
http://tracker.ceph.com/issues/12859
http://tracker.ceph.com/issues/12918

### CODE REVIEW

**Comment by dachary** [comment]
It fails consistently with:
<pre>
filter="rgw/multifs/{overrides.yaml clusters/fixed-2.yaml frontend/civetweb.yaml fs/xfs.yaml rgw_pool_type/replicated.yaml tasks/rgw_swift.yaml}" 
./virtualenv/bin/teuthology-suite --priority 101 --suite rgw --filter="$filter" --suite-branch hammer --distro ubuntu --email loic@dachary.org --ceph hammer-backports-loic --machine-type plana,burnupi,mira
</pre>
where **hammer-backports-loic** is a a branch with hammer and only this pull request on top of it. Here is an example of a failure : http://pulpito.ceph.com/loic-2015-09-01_00:12:35-rgw-hammer-backports-loic---basic-multi. The same job run with the hammer suite succeeds: this is not an environmental problem.

**Comment by dachary** [comment]
@oritwas I'm afraid I'm going to need your expertise on this one. I don't know enough of rgw to figure out why it fails.

**Comment by oritwas** [comment]
This is strange. I will look at it

**Comment by dachary** [comment]
@oritwas thanks ! Note that it's not blocking anything. I got confused at first because there were many pull request in the same branch. Now that it's isolated and easy to reproduce, we'll just set it aside.

**Comment by oritwas** [comment]
@dachary , it apears we missed two commits, see https://github.com/ceph/ceph/tree/wip-swift-backports-hammer

**Comment by dachary** [comment]
@oritwas picked the commits, many thanks ! I also created http://tracker.ceph.com/issues/12918 to link 4b7dbf6 to its original issue http://tracker.ceph.com/issues/12158. I presume 4c5ac21 is a commit that belongs to http://tracker.ceph.com/issues/12157#note-7.

**Comment by dachary** [comment]
<pre>
filter="rgw/multifs/{overrides.yaml clusters/fixed-2.yaml frontend/civetweb.yaml fs/xfs.yaml rgw_pool_type/replicated.yaml tasks/rgw_swift.yaml}" 
./virtualenv/bin/teuthology-suite --priority 101 --suite rgw --filter="$filter" --suite-branch hammer --distro ubuntu --email loic@dachary.org --ceph wip-12859-hammer-loic --machine-type plana,burnupi,mira
</pre>

* *running*

**Comment by dachary** [comment]
@yehudasa does this backport look good to merge ? It passed a run of the hammer rgw suite ( see http://tracker.ceph.com/issues/13356#note-5 for details ).

**Pull request merged**
