### PR TITLE
mimic: mds: stopping MDS with a large cache (40+GB) causes it to miss heartbeats

### PR DESCRIPTION
**Pull request by thmour**
http://tracker.ceph.com/issues/38131
http://tracker.ceph.com/issues/38129

Based on #26230

### CODE REVIEW

**Comment by batrick** [comment]
https://github.com/ceph/ceph/pull/28452/commits/f47493fd1362e26dbef341f91974d0ad063f7dd8

seems to be referring to the wrong commit in the commit message:

`(cherry picked from commit ce153b8)`

It should be referring to: https://github.com/ceph/ceph/pull/26038/commits/ef46216d8d0b659549925481b4eff6bd7d2c43c9

?

**Comment by thmour** [comment]
these are cherry-picks of commits from the luminous merged pr

**Comment by smithfarm** [comment]
@batrick I looked at f47493fd1362e26dbef341f91974d0ad063f7dd8 and it seems to be OK, i.e.: it says "cherry picked from ce153b811263932b42b04a7b8abe63e8241d0ddc" and that commit is in master.

**Comment by yuriw** [comment]
@thmour pls rebase

--- pr 28452 --- pulling https://github.com/thmour/ceph.git branch mimic_test
remote: Enumerating objects: 73, done.
remote: Counting objects: 100% (73/73), done.
remote: Total 85 (delta 73), reused 73 (delta 73), pack-reused 12
Unpacking objects: 100% (85/85), done.
From https://github.com/thmour/ceph
 * branch            mimic_test -> FETCH_HEAD
Auto-merging src/mds/SessionMap.h
CONFLICT (content): Merge conflict in src/mds/SessionMap.h
Auto-merging src/mds/SessionMap.cc
Auto-merging src/mds/Server.cc
Auto-merging src/mds/MDCache.h
Auto-merging src/mds/MDCache.cc
Auto-merging src/common/options.cc
Auto-merging src/common/legacy_config_opts.h
Automatic merge failed; fix conflicts and then commit the result.
Traceback (most recent call last):
  File "/home/yuriw/wip_master/src/script/build-integration-branch", line 62, in <module>
    assert not r
AssertionError

**Comment by thmour** [comment]
@yuriw done

**Comment by batrick** [comment]
needs rebased

**Comment by thmour** [comment]
@batrick bump

**Comment by yuriw** [comment]
@thmour pls rebase
--- pr 28452 --- pulling https://github.com/thmour/ceph.git branch mimic_test
remote: Enumerating objects: 73, done.
remote: Counting objects: 100% (73/73), done.
remote: Total 85 (delta 73), reused 73 (delta 73), pack-reused 12
Unpacking objects: 100% (85/85), done.
From https://github.com/thmour/ceph
 * branch            mimic_test -> FETCH_HEAD
Auto-merging src/mds/MDSRank.cc
Auto-merging src/mds/MDSDaemon.cc
Auto-merging src/mds/MDCache.cc
Auto-merging src/common/options.cc
Auto-merging qa/tasks/cephfs/test_client_limits.py
Auto-merging PendingReleaseNotes
CONFLICT (content): Merge conflict in PendingReleaseNotes
Automatic merge failed; fix conflicts and then commit the result.
Traceback (most recent call last):
  File "/home/yuriw/wip_master/src/script/build-integration-branch", line 62, in <module>
    assert not r
AssertionError

**Comment by thmour** [comment]
I am sorry I don't get any conflicts...
```
# git checkout mimic
Switched to branch 'mimic'
Your branch is up-to-date with 'origin/mimic'.
# git checkout -b mimic_thmour
Switched to a new branch 'mimic_thmour'
# git pull thmour mimic_test
From https://github.com/thmour/ceph
 * branch            mimic_test -> FETCH_HEAD
Auto-merging src/common/options.cc
Merge made by the 'recursive' strategy.
 PendingReleaseNotes                                       |  22 ++++++++++++++-
 qa/suites/fs/bugs/client_trim_caps/tasks/trim-i22073.yaml |  19 +++++++++++++
 qa/tasks/cephfs/test_client_limits.py                     |  38 ++++++++++++++++++++-----
 src/common/legacy_config_opts.h                           |   1 -
 src/common/options.cc                                     |  40 ++++++++++++++++++++++----
 src/mds/Beacon.cc                                         |  44 +++++++++++------------------
 src/mds/MDCache.cc                                        |  62 +++++++++++++++++++++++++++-------------
 src/mds/MDCache.h                                         |  11 +++++---
 src/mds/MDSDaemon.cc                                      |   5 +++-
 src/mds/MDSRank.cc                                        |  87 ++++++++++++++++++++++++++++++++++++++++----------------
 src/mds/Server.cc                                         | 143 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++------------------------
 src/mds/Server.h                                          |  16 +++++++++--
 src/mds/SessionMap.cc                                     | 101 +++++++++++++++++++++++++++++++++++++++++++----------------------
 src/mds/SessionMap.h                                      | 101 ++++++++++++++++++++++++++++++++++++++---------------------------
 src/test/mds/TestSessionFilter.cc                         |  18 ++++++------
 15 files changed, 493 insertions(+), 215 deletions(-)
 create mode 100644 qa/suites/fs/bugs/client_trim_caps/tasks/trim-i22073.yaml
```

**Comment by smithfarm** [comment]
@thmour What @yuriw means is this PR conflicts with some other mimic-targeting PR that is currently open. You'll only see the conflicts if you make an integration branch based on mimic with the open PRs merged on top.

**Comment by smithfarm** [comment]
Also, it looks to me that the conflict is only in PendingReleaseNotes - in all likelihood, it's conflicting with this PR: https://github.com/ceph/ceph/pull/29210

@yuriw Could you test this PR and https://github.com/ceph/ceph/pull/29210 in separate runs? Also, this PR is older so it should get priority IMHO.

**Comment by thmour** [comment]
i fixed the pending release notes, hope we dont't run into any problems now

**Comment by thmour** [comment]
@batrick The end result is the same with the luminous PR, if you check the "files changed" tab of both PRs, there is only a small difference in SessionMap.h, setting loaded_legacy to false, I can fix that. Maybe during the merge conflicts I put some changes in the wrong commits, because I applied them in bulk. I will try to do a cleanup if that is needed.

**Comment by batrick** [comment]
> @batrick The end result is the same with the luminous PR, if you check the "files changed" tab of both PRs, there is only a small difference in SessionMap.h, setting loaded_legacy to false, I can fix that. Maybe during the merge conflicts I put some changes in the wrong commits, because I applied them in bulk. I will try to do a cleanup if that is needed.

I understand the end result may be the same but there may still be small differences. It's extremely difficult to attribute where a change came from if the cherry-picks are squashed. Looking at this the other way, I may also look at a commit in master and do a quick grep on the log for mimic and wrongly think that a commit has not been backported. 

It's bothersome work to do these types of backports but it's important we get this right. The process is there to make these releases more stable and accountable.

**Comment by vshankar** [comment]
@thmour any progress on this? this backport would be needed for https://tracker.ceph.com/issues/38339

**Comment by thmour** [comment]
I am on vacations until Sept 9, sorry that I didn't inform you guys earlier. When I come back I will fix it.

**Comment by thmour** [comment]
hello, i've fixed the commits, can the makecheck be restarted, it failed due to some 404 error with some centos repo

**Comment by smithfarm** [comment]
jenkins test make check

**Comment by vshankar** [comment]
retest this please

**Comment by smithfarm** [comment]
This doesn't build because:

```
/home/jenkins-build/build/workspace/ceph-pull-requests/src/mds/SessionMap.cc: In member function 'void SessionMap::handle_conf_change(const md_config_t*, const std::set<std::__cxx11::basic_string<char> >&)':
/home/jenkins-build/build/workspace/ceph-pull-requests/src/mds/SessionMap.cc:1057:5: error: 'it' was not declared in this scope
     it = by_state.find(Session::STATE_STALE);
     ^~
/home/jenkins-build/build/workspace/ceph-pull-requests/src/mds/SessionMap.cc:1057:5: note: suggested alternative: 'int'
     it = by_state.find(Session::STATE_STALE);
     ^~
     int
src/mds/CMakeFiles/mds.dir/build.make:478: recipe for target 'src/mds/CMakeFiles/mds.dir/SessionMap.cc.o' failed
make[3]: *** [src/mds/CMakeFiles/mds.dir/SessionMap.cc.o] Error 1
```

**Comment by thmour** [comment]
ah thats and old error, it seems I forgot to push the latest update

**Comment by smithfarm** [comment]
I'm happy with the way it looks, now, but - obviously - @batrick has the final word here.

**Comment by batrick** [comment]
Looks ready for QA.

Good work!

**Comment by smithfarm** [comment]
@batrick Please dismiss your negative review.

**Comment by yuriw** [comment]
@thmour pls rebease

--- pr 28452 --- pulling https://github.com/thmour/ceph.git branch mimic_test
remote: Enumerating objects: 88, done.
remote: Counting objects: 100% (88/88), done.
remote: Total 107 (delta 88), reused 88 (delta 88), pack-reused 19
Receiving objects: 100% (107/107), 104.46 KiB | 0 bytes/s, done.
Resolving deltas: 100% (92/92), completed with 34 local objects.
From https://github.com/thmour/ceph
 * branch            mimic_test -> FETCH_HEAD
Auto-merging src/mds/MDSRank.cc
Auto-merging src/mds/MDCache.h
Auto-merging src/mds/MDCache.cc
CONFLICT (content): Merge conflict in src/mds/MDCache.cc
Auto-merging src/common/options.cc
Auto-merging src/common/legacy_config_opts.h
Auto-merging PendingReleaseNotes
Automatic merge failed; fix conflicts and then commit the result.
Traceback (most recent call last):
  File "/home/yuriw/wip_master/src/script/build-integration-branch", line 62, in <module>
    assert not r
AssertionError

**Comment by smithfarm** [comment]
@thmour Now it conflicts with one of these three: #29224, #29232, #29479 

@yuriw This PR is older than the other three and @thmour has already rebased it once. Should we give this one priority the next time around?

**Comment by batrick** [comment]
> @yuriw This PR is older than the other three and @thmour has already rebased it once. Should we give this one priority the next time around?

Yes. Let's skip the other three until this is merged.

**Comment by batrick** [comment]
@thmour sorry this will need rebased. Those other three PRs were merged.

**Comment by thmour** [comment]
hello I have done the rebase, hoo do we fix this doc problem, it doesn't seem like it has any thing to do with my pr

**Comment by smithfarm** [comment]
@tchaikov Lately the `Docs: build check` has been failing much more frequently than before.

```
Using shallow clone
```

Do we have to get rid of the shallow clone here, too, as was done for the submodule check?

**Comment by smithfarm** [comment]
@yuriw Can we get this one into v13.2.7 ?

**Comment by yuriw** [comment]
[wip-yuri3-testing-2019-10-22-1848-mimic](https://trello.com/c/R54td5wd/729-wip-yuri3-testing-2019-10-22-1848-mimic)

**Comment by tchaikov** [comment]
@smithfarm i don't see the connection between the failure and shallow clone. could you help me understand it?

**Comment by smithfarm** [comment]
Sigh, this needs rebasing **again**.

**Comment by smithfarm** [comment]
@yuriw Is it possible you are merging newer PRs before older ones? It should be the other way around. @thmour had to rebase this three times already, and now he has to rebase a fourth time. That's not fair.

**Comment by smithfarm** [comment]
@tchaikov Presumably, the docs build test failure was an instance of https://tracker.ceph.com/issues/42403 fixed for mimic by https://github.com/ceph/ceph/pull/31090

**Comment by smithfarm** [comment]
I went ahead and rebased it on behalf of @thmour

**Comment by smithfarm** [comment]
```
IOError: CRC check failed 0xa97912f2 != 0x650305fbL
src/pybind/mgr/dashboard/CMakeFiles/mgr-dashboard-nodeenv.dir/build.make:60: recipe for target 'src/pybind/mgr/dashboard/node-env/bin/npm' failed
```

(not related to this PR)

**Comment by smithfarm** [comment]
jenkins test make check

**Pull request merged**
