### PR TITLE
jewel: librbd: cannot disable journaling or remove non-mirrored, non-primary image

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/17060

### CODE REVIEW

**Comment by smithfarm** [comment]
@dillaman This backport appears to need https://github.com/ceph/ceph/commit/d5fa466d which is non-trivial to do. How do you suggest we proceed?

**Comment by smithfarm** [comment]
@dillaman Nevermind, I think I figured it out, just waiting for Jenkins build to complete.

**Comment by dachary** [comment]
@trociny does this backport look good to merge ? It passed the rbd suite http://tracker.ceph.com/issues/17487#note-10 (except for two failures that are unrelated http://tracker.ceph.com/issues/17590 and http://tracker.ceph.com/issues/17262)

**Comment by dillaman** [comment]
@dachary @trociny is out for a couple weeks -- lgtm

**Pull request merged**
