### PR TITLE
mon crashes when "ceph osd tree 85 --format json"

### PR DESCRIPTION
**Pull request by tchaikov**
http://tracker.ceph.com/issues/11975

### CODE REVIEW

**Comment by ktdreyer** [comment]
I think the make-check bot failure above is spurious. Can you please re-push so it will trigger a new build attempt?

**Comment by tchaikov** [comment]
@ktdreyer @theanalyst removed the commit included in #5122 from this pr and repushed.

**Comment by tchaikov** [comment]
since this pr has been tested per http://tracker.ceph.com/issues/11990, before the commit from #5122 was removed. it's good to merge along with #5122 .

**Comment by dachary** [comment]
It looks like the bot failure is an actual problem. See also http://gitbuilder.sepia.ceph.com/gitbuilder-ceph-tarball-trusty-i386-basic/log.cgi?log=552772025cb8d5f51ffb3a069d1bd93bc73f1123. I think to remember a pull request fixed racing code in ceph-helpers or something. I'll dig into this.

**Pull request merged**
