### PR TITLE
mimic: tests: Add hashinfo testing for dump command of ceph-objectstore-tool

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/38141

### CODE REVIEW

**Comment by dzafman** [comment]
Testing this would fail WITHOUT ceph/ceph#25721.  The only test case requires manually running the following:

cd build
../qa/run-standalone.sh ceph_objectstore_tool.py

**Comment by smithfarm** [comment]
jenkins test docs

**Comment by yuriw** [comment]
[wip-yuri-testing-2019-02-18-1714-mimic](https://trello.com/c/vJf3xQOH/539-wip-yuri-testing-2019-02-18-1714-mimic)

**Comment by yuriw** [comment]
[wip-yuri-testing-2019-02-20-1755-mimic](https://trello.com/c/G3p1tb0I/543-wip-yuri-testing-2019-02-20-1755-mimic)

**Pull request merged**
