### PR TITLE
rgw: keep underscore in metatdata key

### PR DESCRIPTION
**Pull request by IlsooByun**
Fixes: https://tracker.ceph.com/issues/48716

Signed-off-by: Ilsoo Byun <ilsoobyun@linecorp.com>

## Checklist
- [x] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by mattbenjamin** [comment]
pushed this https://github.com/ceph/s3-tests/pull/387

**Review by mattbenjamin — APPROVED** [review]
lgtm

**Comment by ivancich** [comment]
Teuthology QA results -- no regressions:
- http://pulpito.ceph.com/ivancich-2021-04-06_19:13:33-rgw-wip-eric-testing-2-distro-basic-smithi/
- http://pulpito.ceph.com/ivancich-2021-04-06_19:14:15-rgw-wip-eric-testing-2-distro-basic-smithi/

**Comment by ivancich** [comment]
@IlsooByun and @mattbenjamin Right now there's no backport listed on the tracker. I'd like to add backports and change status to Pending Backports. Any objection?

**Comment by cbodley** [comment]
> if we change swift to use `lowercase_underscore_http_attr()` to match this new format, we'd still be unable to remove any user metadata written in the old format (before this PR)

this seems like the best compromise to me, so i opened https://github.com/ceph/ceph/pull/44599 with this change

**Pull request merged**
