### PR TITLE
luminous: rbd-ggate: tool to map images on FreeBSD via GEOM Gate

### PR DESCRIPTION
**Pull request by dillaman**

### CODE REVIEW

**Comment by wjwithagen** [comment]
@dillaman 
Arrgh, just missed this. the rights on:
```
./src/test/rbd-ggate.sh
./qa/workunits/rbd/rbd-ggate.sh
```
Both need to be 755, and at least one has 664, so the test fails.
Not major, since it is for testing, but a good start would be better.

**Comment by dillaman** [comment]
@wjwithagen Can you open a new PR for the issue?

**Comment by dillaman** [comment]
... both files have 0775 permissions on my master and luminous branch

**Comment by wjwithagen** [comment]
@dillaman 
Right, I checkout master to be 100% sure, but they land just fine with correct rights,
So we're oke there.
Sorry for the noise

**Pull request merged**
