### PR TITLE
rbd: add '--whole-object' option for 'rbd du' command as 'rbd diff'

### PR DESCRIPTION
**Pull request by jimmyway**
Signed-off-by: Tang Jin <tang.jin@istuary.com>

'rbd du' command doesn't have the 'whole-object' option, so I add this option in order to calculate the disk usage of image optionally by 'whole-object' or not 'whole-object' as  they were used by 'rbd diff' command.

### CODE REVIEW

**Comment by jimmyway** [comment]
@liupan1111 
pls have a look, thanks

**Comment by liupan1111** [comment]
@dillaman @jimmyway if "rbd du" needs this option, how about "rados df"?

**Comment by dillaman** [comment]
@jimmyway The disk usage command was limited to whole object approximation since otherwise it would take way to long to calculate the disk usage. Your change now makes the default behavior much slower.

**Comment by dillaman** [comment]
@liupan1111 The librbd diff has the whole object diff because (1) it could have hundreds of thousands of backing objects, (2) it now has object map enabled by default for efficient lookup.

**Comment by liupan1111** [comment]
@dillaman, what is The mean of backing objects?

**Comment by dillaman** [comment]
@liupan1111 An RBD image is not stored as a single object in RADOS, instead it is striped over hundreds, thousands, or hundreds of thousands of backing RADOS objects.

**Comment by liupan1111** [comment]
@dillaman, very clear now, thanks.

**Comment by jimmyway** [comment]
@dillaman @liupan1111 , thanks, I will close it.
I added these code because it's inconvenient to use 'rbd diff | awk ...' to get the real disk usage of image.
It really has large difference of result between two method: with --whole-object or without --whole-object, and finally I found that 'rbd diff' and 'rbd du' also invoke the same function 'diff_iterate2', so I think they have much in common essentially.

**Comment by dillaman** [comment]
@jimmyway I should clarify -- I'm fine w/ the idea in practice, but it should use some new optional to indicate that you prefer to use the slow but more accurate method. Of course, the slow method doesn't properly track the amount of space used by snapshots -- so either way, it's a rough estimate.

**Comment by jimmyway** [comment]
@dillaman, thinks, 
what about adding a new option like '--no-whole-object' instead ? It won't change the default behavior of 'rbd du'

**Pull request closed without merging**
