### PR TITLE
pacific: mds/client: check the cephx mds auth access in client side

### PR DESCRIPTION
**Pull request by lxbsz**
backport tracker: https://tracker.ceph.com/issues/63832

---

backport of https://github.com/ceph/ceph/pull/48027 and https://github.com/ceph/ceph/pull/53887
parent tracker: https://tracker.ceph.com/issues/57154

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Comment by vshankar** [comment]
@lxbsz I think we can leave this out for the last pacific release. The nature of changes is pretty sizeable. WDYT?

**Comment by lxbsz** [comment]
> @lxbsz I think we can leave this out for the last pacific release. The nature of changes is pretty sizeable. WDYT?

Yeah, it is. Please note this will block another [bug's](https://tracker.ceph.com/issues/63551) fixing backporting.

**Comment by vshankar** [comment]
> > @lxbsz I think we can leave this out for the last pacific release. The nature of changes is pretty sizeable. WDYT?
> 
> Yeah, it is. Please note this will block another [bug's](https://tracker.ceph.com/issues/63551) fixing backporting.

Argh! That fix an important fix. Does that fix depend on this change? AFAICT, that fix would send `tid` in renew caps requests.

**Comment by lxbsz** [comment]
> > > @lxbsz I think we can leave this out for the last pacific release. The nature of changes is pretty sizeable. WDYT?
> > 
> > 
> > Yeah, it is. Please note this will block another [bug's](https://tracker.ceph.com/issues/63551) fixing backporting.
> 
> Argh! That fix an important fix. Does that fix depend on this change? AFAICT, that fix would send `tid` in renew caps requests.

Yeah, without this PR I am afraid that will introduce some potential issues.

**Comment by vshankar** [comment]
> > > > @lxbsz I think we can leave this out for the last pacific release. The nature of changes is pretty sizeable. WDYT?
> > > 
> > > 
> > > Yeah, it is. Please note this will block another [bug's](https://tracker.ceph.com/issues/63551) fixing backporting.
> > 
> > 
> > Argh! That fix an important fix. Does that fix depend on this change? AFAICT, that fix would send `tid` in renew caps requests.
> 
> Yeah, without this PR I am afraid that will introduce some potential issues.

@lxbsz Could you explain a bit about the "potential issues"? I'm not 100% clear how sending the oldest_client_tid in renew caps would be effected without this change.

**Comment by lxbsz** [comment]
> > > > > @lxbsz I think we can leave this out for the last pacific release. The nature of changes is pretty sizeable. WDYT?
> > > > 
> > > > 
> > > > Yeah, it is. Please note this will block another [bug's](https://tracker.ceph.com/issues/63551) fixing backporting.
> > > 
> > > 
> > > Argh! That fix an important fix. Does that fix depend on this change? AFAICT, that fix would send `tid` in renew caps requests.
> > 
> > 
> > Yeah, without this PR I am afraid that will introduce some potential issues.
> 
> @lxbsz Could you explain a bit about the "potential issues"? I'm not 100% clear how sending the oldest_client_tid in renew caps would be effected without this change.

This will increase the header version for `MClientSession` and at the same time will add the following member:

`std::vector<MDSCapAuth> cap_auths;`

If we just skip backporting this PR there will be several cases could be potentially buggy as we hit before:

case1:  old ceph and new user space client including this
case2:  new ceph with this with old kclient
case3:  old ceph with new kclient including this feature
case4:  new ceph with this with old user space client

If backporting this is really not acceptable, then I can try to skip it anyway.

Thanks

**Comment by vshankar** [comment]
> > > > > > @lxbsz I think we can leave this out for the last pacific release. The nature of changes is pretty sizeable. WDYT?
> > > > > 
> > > > > 
> > > > > Yeah, it is. Please note this will block another [bug's](https://tracker.ceph.com/issues/63551) fixing backporting.
> > > > 
> > > > 
> > > > Argh! That fix an important fix. Does that fix depend on this change? AFAICT, that fix would send `tid` in renew caps requests.
> > > 
> > > 
> > > Yeah, without this PR I am afraid that will introduce some potential issues.
> > 
> > 
> > @lxbsz Could you explain a bit about the "potential issues"? I'm not 100% clear how sending the oldest_client_tid in renew caps would be effected without this change.
> 
> This will increase the header version for `MClientSession` and at the same time will add the following member:
> 
> `std::vector<MDSCapAuth> cap_auths;`
> 
> If we just skip backporting this PR there will be several cases could be potentially buggy as we hit before:
> 
> case1: old ceph and new user space client including this case2: new ceph with this with old kclient case3: old ceph with new kclient including this feature case4: new ceph with this with old user space client
> 
> If backporting this is really not acceptable, then I can try to skip it anyway.

The only thing is that this is the last pacific release and its best to avoid any unnecessary surprises since we cannot ask users to upgrade to the next pacific version. So, given the nature of changes, I'd say we skip this backport. @lxbsz ?

**Comment by vshankar** [comment]
> > > > > > > > @lxbsz I think we can leave this out for the last pacific release. The nature of changes is pretty sizeable. WDYT?
> > > > > > > 
> > > > > > > 
> > > > > > > Yeah, it is. Please note this will block another [bug's](https://tracker.ceph.com/issues/63551) fixing backporting.
> > > > > > 
> > > > > > 
> > > > > > Argh! That fix an important fix. Does that fix depend on this change? AFAICT, that fix would send `tid` in renew caps requests.
> > > > > 
> > > > > 
> > > > > Yeah, without this PR I am afraid that will introduce some potential issues.
> > > > 
> > > > 
> > > > @lxbsz Could you explain a bit about the "potential issues"? I'm not 100% clear how sending the oldest_client_tid in renew caps would be effected without this change.
> > > 
> > > 
> > > This will increase the header version for `MClientSession` and at the same time will add the following member:
> > > `std::vector<MDSCapAuth> cap_auths;`
> > > If we just skip backporting this PR there will be several cases could be potentially buggy as we hit before:
> > > case1: old ceph and new user space client including this case2: new ceph with this with old kclient case3: old ceph with new kclient including this feature case4: new ceph with this with old user space client
> > > If backporting this is really not acceptable, then I can try to skip it anyway.
> > 
> > 
> > The only thing is that this is the last pacific release and its best to avoid any unnecessary surprises since we cannot ask users to upgrade to the next pacific version. So, given the nature of changes, I'd say we skip this backport. @lxbsz ?
> 
> Okay, let me do that. thanks!

Oh, I meant to close this backport and the dependent backport too (that fixes the oldest client tid issue for pacific release).

**Comment by lxbsz** [comment]
> > > > > > > > > @lxbsz I think we can leave this out for the last pacific release. The nature of changes is pretty sizeable. WDYT?
> > > > > > > > 
> > > > > > > > 
> > > > > > > > Yeah, it is. Please note this will block another [bug's](https://tracker.ceph.com/issues/63551) fixing backporting.
> > > > > > > 
> > > > > > > 
> > > > > > > Argh! That fix an important fix. Does that fix depend on this change? AFAICT, that fix would send `tid` in renew caps requests.
> > > > > > 
> > > > > > 
> > > > > > Yeah, without this PR I am afraid that will introduce some potential issues.
> > > > > 
> > > > > 
> > > > > @lxbsz Could you explain a bit about the "potential issues"? I'm not 100% clear how sending the oldest_client_tid in renew caps would be effected without this change.
> > > > 
> > > > 
> > > > This will increase the header version for `MClientSession` and at the same time will add the following member:
> > > > `std::vector<MDSCapAuth> cap_auths;`
> > > > If we just skip backporting this PR there will be several cases could be potentially buggy as we hit before:
> > > > case1: old ceph and new user space client including this case2: new ceph with this with old kclient case3: old ceph with new kclient including this feature case4: new ceph with this with old user space client
> > > > If backporting this is really not acceptable, then I can try to skip it anyway.
> > > 
> > > 
> > > The only thing is that this is the last pacific release and its best to avoid any unnecessary surprises since we cannot ask users to upgrade to the next pacific version. So, given the nature of changes, I'd say we skip this backport. @lxbsz ?
> > 
> > 
> > Okay, let me do that. thanks!
> 
> Oh, I meant to close this backport and the dependent backport too (that fixes the oldest client tid issue for pacific release).

Okay, I am okay with it.

**Pull request closed without merging**
