### PR TITLE
quincy: qa/distros: add centos stream 9 as supported distro

### PR DESCRIPTION
**Pull request by ljflores**
Backport of https://github.com/ceph/ceph/pull/50441 since centos 8 is EOL.

Fixes: https://tracker.ceph.com/issues/66334

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [x] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [x] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Comment by ljflores** [comment]
Ah, I need to take out the remaining c8 references.. addressing that..

**Comment by ljflores** [comment]
Part or all of this needs to be backported: https://github.com/ceph/ceph/pull/53517

Evaluating..

**Comment by idryomov** [comment]
> Part or all of this needs to be backported: #53517

I'd assume that just part because neither rhel 8 nor ubuntu 20.04 shut off the repos like centos 8 did?

**Comment by idryomov** [comment]
> Fixes: https://tracker.ceph.com/issues/66334

That ticket talks about both quincy and reef.  I think it's OK to use it for both, but if you want strict PR linkage, it would need to be cloned.

**Comment by ljflores** [comment]
Closing since @cbodley would be best to create this special backport.

**Comment by cbodley** [comment]
> Closing since @cbodley would be best to create this special backport.

please don't expect me to do all of this

**Comment by ljflores** [comment]
@cbodley I understand; I only thought you would be best since you raised the original PR(s), and the cherry-picks are not clean.

I don't have all the background to understand all of what needs to be backported (I'm guessing https://github.com/ceph/ceph/pull/50441 and https://github.com/ceph/ceph/pull/53517), but if you can advise on this, perhaps we can enlist someone else to actually stage the backport.

**Pull request closed without merging**
