### PR TITLE
doc: create links to multisite sync policy in index

### PR DESCRIPTION
**Pull request by theanalyst**
Signed-off-by: Abhishek Lekshmanan <abhishek@suse.com>

### CODE REVIEW

**Comment by theanalyst** [comment]
jenkins render docs

**Comment by theanalyst** [comment]
jenkins test this please

**Comment by cbodley** [comment]
jenkins test make check

**Comment by cbodley** [comment]
@theanalyst it's not obvious to me exactly what this changes. was there a broken link somewhere?

**Comment by theanalyst** [comment]
current docs do not show this page even as there isn't a link in the index https://docs.ceph.com/docs/master/radosgw/

**Comment by cbodley** [comment]
are you sure the current docs for master have been updated? for example, i also don't see the following text in [multisite.rst](https://docs.ceph.com/docs/master/radosgw/multisite/#requirements-and-assumptions):

> See Sync Policy Config for instructions on defining fine grained bucket sync policy rules.

**Comment by theanalyst** [comment]
Guess this might've been just a cache issue closing

**Pull request closed without merging**
