### PR TITLE
mon: fix crush testing for new pools

### PR DESCRIPTION
**Pull request by liewegas**
only test hte relevant ruleset!

### CODE REVIEW

**Comment by liewegas** [comment]
@jecluis can you take a look?

**Comment by dachary** [comment]
<pre>
Reviewed-by: Loic Dachary &lt;ldachary@redhat.com>
</pre>
once the make check bot approves.

**Comment by tchaikov** [comment]
@dachary again:

2015-09-18 15:21:15.233992 7f6ea07f5700 -1 asok(0x7f6e98000fd0) AdminSocketConfigObs::init: failed: AdminSocket::bind_and_listen: The UNIX domain socket path /home/jenkins/workspace/ceph/LABELS/ceph-centos-7-jenkins/src/testdir/test-7202/out/client.xx-profile-rw.1613.asok is too long! The maximum length on this system is 107

**Comment by dachary** [comment]
@tchaikov ack. I'm tempted to wait it out until jenkins goes away.

**Pull request merged**
