### PR TITLE
rgw: remove redundant parenthesis in logs

### PR DESCRIPTION
**Pull request by qrGitHub**
Signed-off-by: Bingyin Zhang <zhangbingyin@cloudin.cn>

### CODE REVIEW

**Comment by qrGitHub** [comment]
hi @cbodley, @yehudasa, can this be merged?

**Comment by cbodley** [comment]
jenkins test this please

**Comment by cbodley** [comment]
jenkins test docs

**Comment by qrGitHub** [comment]
Hi @cbodley, can this be merged?

**Comment by qrGitHub** [comment]
Hi @joscollin @yehudasa, would you help to merge this? Thanks.

**Comment by joscollin** [comment]
@qrGitHub This is waiting for qa. Somebody (Mostly @yuriw ) will pick up after the holidays.

**Comment by cbodley** [comment]
since this only changes log strings and is compiling successfully, i'm merging without a qa run

**Pull request merged**
