### PR TITLE
hammer: rgw: radosgw server abort when user passed bad parameters to set quota

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/15257

### CODE REVIEW

**Comment by mattbenjamin** [comment]
@smithfarm any update on this?  (pending_backport in tracker 14191)

**Comment by smithfarm** [comment]
@mattbenjamin It is included in the current integration testing round. Status is always available at http://tracker.ceph.com/issues/15895

**Comment by smithfarm** [comment]
Any idea what could be causing this crash? http://tracker.ceph.com/issues/16323

**Comment by smithfarm** [comment]
@oritwas This PR passed an rgw suite with some valgrind-related failures that appear harmless - see http://tracker.ceph.com/issues/15895#note-19 

Do you think this PR is ready to merge?

**Comment by oritwas** [comment]
lgtm

**Pull request merged**
