### PR TITLE
cephadm: shell: keep .bash_history in /var/log/ceph/$fsid

### PR DESCRIPTION
**Pull request by liewegas**
This makes the shell much more friendly to humans.

Signed-off-by: Sage Weil <sage@redhat.com>

### CODE REVIEW

**Comment by sebastian-philipp** [comment]
with this PR we're heading into a different direction than Rook: Rook uses a persistent "toolbox" that is accessible via remote shell from anywhere. Which this PR, our goal is a non-persistent container that mounts stuff from $HOME. 

I don't know which approach is better, but we should be sure that this is the right direction.

**Comment by liewegas** [comment]
I'm not sure how a persistent container would actually work.  IIUC you can make a podman container stick around after it stops, but that doesn't mean you can start it again.. only that it is still in the 'ps' output.  (I don't really understand why it works this way, TBH.)

In any case, though, I don't think it makes sense to have it "running" the whole time, since it's not like you'd have persistent processes in there.  If you have something like a watch or less or whatever, it can go in your shell, and the shell can go away when you exit from bash.

**Comment by sebastian-philipp** [comment]
> In any case, though, I don't think it makes sense to have it "running" the whole time,

actually that's exactly what Rook is doing. the persistent process is simply `bash`, waiting for users to attach to it. Which is typically faster than spawning up a new container!

>  since it's not like you'd have persistent processes in there. If you have something like a watch or less or whatever, it can go in your shell, and the shell can go away when you exit from bash.

**Comment by liewegas** [comment]
What happens if you connect to it twice in rook?

I think that model makes more sense in k8s because there is a way to attach to a remote pod.  I'm not sure what we would do here to attach.  (And what the value of having the persistent bash is, beyond startup time.. which in my experience has been pretty quick?)

**Comment by sebastian-philipp** [comment]
> What happens if you connect to it twice in rook?

never tried tbh.
> 
> I think that model makes more sense in k8s because there is a way to attach to a remote pod.

**remote** is the keyword here. There is no way to attach to a remote toolbox without first ssh the the host, which makes things cumbersome. 

> I'm not sure what we would do here to attach. (And what the value of having the persistent bash is, beyond startup time.. which in my experience has been pretty quick?).

Hm. In my experience starting a container was a bit annoyingly slow. 

Anyway. what do you think about mounting `/var/log/ceph/$fsid` (or a sub dir) as $HOME into the container? that would make it possible to have the impression of a long-running toolbox.

**Comment by liewegas** [comment]
> > What happens if you connect to it twice in rook?
> 
> never tried tbh.
> 
> > I think that model makes more sense in k8s because there is a way to attach to a remote pod.
> 
> **remote** is the keyword here. There is no way to attach to a remote toolbox without first ssh the the host, which makes things cumbersome.
> 
> > I'm not sure what we would do here to attach. (And what the value of having the persistent bash is, beyond startup time.. which in my experience has been pretty quick?).
> 
> Hm. In my experience starting a container was a bit annoyingly slow.

It is when the cluster is running a non-default container, and then the first shell has to download the default container.  But that is probably a separate issue of having some way of controlling "which container should the shell use"?

> Anyway. what do you think about mounting `/var/log/ceph/$fsid` (or a sub dir) as $HOME into the container? that would make it possible to have the impression of a long-running toolbox.

Hmm, we could do /var/log/ceph/$fsid/home, and put the .bash_completion in there, perhaps?  We already have one other "special" directory there (crash).

**Comment by liewegas** [comment]
Alternatively, we could map the host's $HOME (/root) to /root.  Doing *just* that would mean that the bash history is shared with the host, though, which we probably don't want.

**Comment by mgfritch** [comment]
> Alternatively, we could map the host's $HOME (/root) to /root. Doing _just_ that would mean that the bash history is shared with the host, though, which we probably don't want.

:-1: for history shared with the host  ... putting the history under `/var/log/ceph/$fsid` makes more sense to me...

**Pull request merged**
