### PR TITLE
osd: do not dump an osd multiple times

### PR DESCRIPTION
**Pull request by jhonxue**
Fixes: https://tracker.ceph.com/issues/49627

Signed-off-by: Xue Yantao <jhonxue@tencent.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by jhonxue** [comment]
@batrick @tchaikov @jecluis please, review. thanks

**Comment by jhonxue** [comment]
when two or more crush rule sets have some same osds, the dump result of ceph osd df has duplicate infos

for an example
1、ceph osd df tree  result

ID   CLASS WEIGHT  REWEIGHT SIZE    RAW USE DATA    OMAP    META     AVAIL   %USE  VAR  PGS STATUS TYPE NAME
-104       0.94899        - 972 GiB 190 GiB 109 GiB 166 MiB  8.8 GiB 782 GiB 19.55 1.02   -        root hdd_root_21
  -7       0.42200        - 432 GiB  90 GiB  54 GiB  83 MiB  3.9 GiB 342 GiB 20.94 1.09   -            host c101
  10   hdd 0.10500  1.00000 108 GiB  24 GiB  15 GiB  24 MiB 1000 MiB  84 GiB 22.26 1.16 534     up         osd.10
  12   hdd 0.10500  1.00000 108 GiB  21 GiB  12 GiB  19 MiB 1005 MiB  87 GiB 19.59 1.02 495     up         osd.12
  13   hdd 0.10500  1.00000 108 GiB  23 GiB  14 GiB  16 MiB 1008 MiB  85 GiB 21.51 1.12 500     up         osd.13
  14   hdd 0.10500  1.00000 108 GiB  22 GiB  13 GiB  24 MiB 1000 MiB  86 GiB 20.41 1.07 519     up         osd.14
  -5       0.52699        - 540 GiB 100 GiB  55 GiB  84 MiB  4.9 GiB 440 GiB 18.43 0.96   -            host c152
   5   hdd 0.10500  1.00000 108 GiB  20 GiB  11 GiB  19 MiB 1005 MiB  88 GiB 18.57 0.97 515     up         osd.5
   6   hdd 0.10500  1.00000 108 GiB  20 GiB  11 GiB  15 MiB 1009 MiB  88 GiB 18.77 0.98 502     up         osd.6
   7   hdd 0.10500  1.00000 108 GiB  19 GiB  10 GiB  18 MiB 1006 MiB  89 GiB 17.56 0.92 526     up         osd.7
   8   hdd 0.10500  1.00000 108 GiB  21 GiB  12 GiB  14 MiB 1010 MiB  87 GiB 19.00 0.99 501     up         osd.8
   9   hdd 0.10500  1.00000 108 GiB  20 GiB  11 GiB  18 MiB 1006 MiB  88 GiB 18.26 0.95 516     up         osd.9
-102       0.94899        - 972 GiB 190 GiB 109 GiB 180 MiB  8.8 GiB 782 GiB 19.55 1.02   -        root hdd_root_31
  -7       0.42200        - 432 GiB  90 GiB  54 GiB  83 MiB  3.9 GiB 342 GiB 20.94 1.09   -            host c101
  10   hdd 0.10500  1.00000 108 GiB  24 GiB  15 GiB  24 MiB 1000 MiB  84 GiB 22.26 1.16 534     up         osd.10
  12   hdd 0.10500  1.00000 108 GiB  21 GiB  12 GiB  19 MiB 1005 MiB  87 GiB 19.59 1.02 495     up         osd.12
  13   hdd 0.10500  1.00000 108 GiB  23 GiB  14 GiB  16 MiB 1008 MiB  85 GiB 21.51 1.12 500     up         osd.13
  14   hdd 0.10500  1.00000 108 GiB  22 GiB  13 GiB  24 MiB 1000 MiB  86 GiB 20.41 1.07 519     up         osd.14
  -3       0.52699        - 540 GiB 100 GiB  55 GiB  97 MiB  4.9 GiB 440 GiB 18.43 0.96   -            host c153
   0   hdd 0.10500  1.00000 108 GiB  20 GiB  11 GiB  24 MiB 1000 MiB  88 GiB 18.79 0.98 523     up         osd.0
   1   hdd 0.10500  1.00000 108 GiB  19 GiB  10 GiB  22 MiB 1002 MiB  89 GiB 18.03 0.94 510     up         osd.1
   2   hdd 0.10500  1.00000 108 GiB  19 GiB 9.9 GiB  13 MiB 1011 MiB  89 GiB 17.49 0.91 513     up         osd.2
   3   hdd 0.10500  1.00000 108 GiB  20 GiB  11 GiB  17 MiB 1007 MiB  88 GiB 18.62 0.97 491     up         osd.3
   4   hdd 0.10500  1.00000 108 GiB  21 GiB  12 GiB  21 MiB 1003 MiB  87 GiB 19.24 1.00 523     up         osd.4
-100       1.05399        - 1.1 TiB 199 GiB 109 GiB 181 MiB  9.8 GiB 881 GiB 18.43 0.96   -        root hdd_root_32
  -5       0.52699        - 540 GiB 100 GiB  55 GiB  84 MiB  4.9 GiB 440 GiB 18.43 0.96   -            host c152
   5   hdd 0.10500  1.00000 108 GiB  20 GiB  11 GiB  19 MiB 1005 MiB  88 GiB 18.57 0.97 515     up         osd.5
   6   hdd 0.10500  1.00000 108 GiB  20 GiB  11 GiB  15 MiB 1009 MiB  88 GiB 18.77 0.98 502     up         osd.6
   7   hdd 0.10500  1.00000 108 GiB  19 GiB  10 GiB  18 MiB 1006 MiB  89 GiB 17.56 0.92 526     up         osd.7
   8   hdd 0.10500  1.00000 108 GiB  21 GiB  12 GiB  14 MiB 1010 MiB  87 GiB 19.00 0.99 501     up         osd.8
   9   hdd 0.10500  1.00000 108 GiB  20 GiB  11 GiB  18 MiB 1006 MiB  88 GiB 18.26 0.95 516     up         osd.9
  -3       0.52699        - 540 GiB 100 GiB  55 GiB  97 MiB  4.9 GiB 440 GiB 18.43 0.96   -            host c153
   0   hdd 0.10500  1.00000 108 GiB  20 GiB  11 GiB  24 MiB 1000 MiB  88 GiB 18.79 0.98 523     up         osd.0
   1   hdd 0.10500  1.00000 108 GiB  19 GiB  10 GiB  22 MiB 1002 MiB  89 GiB 18.03 0.94 510     up         osd.1
   2   hdd 0.10500  1.00000 108 GiB  19 GiB 9.9 GiB  13 MiB 1011 MiB  89 GiB 17.49 0.91 513     up         osd.2
   3   hdd 0.10500  1.00000 108 GiB  20 GiB  11 GiB  17 MiB 1007 MiB  88 GiB 18.62 0.97 491     up         osd.3
   4   hdd 0.10500  1.00000 108 GiB  21 GiB  12 GiB  21 MiB 1003 MiB  87 GiB 19.24 1.00 523     up         osd.4
  -1       1.47598        - 1.5 TiB 290 GiB 164 GiB 263 MiB   14 GiB 1.2 TiB 19.15 1.00   -        root default
  -7       0.42200        - 432 GiB  90 GiB  54 GiB  83 MiB  3.9 GiB 342 GiB 20.94 1.09   -            host c101
  10   hdd 0.10500  1.00000 108 GiB  24 GiB  15 GiB  24 MiB 1000 MiB  84 GiB 22.26 1.16 534     up         osd.10
  12   hdd 0.10500  1.00000 108 GiB  21 GiB  12 GiB  19 MiB 1005 MiB  87 GiB 19.59 1.02 495     up         osd.12
  13   hdd 0.10500  1.00000 108 GiB  23 GiB  14 GiB  16 MiB 1008 MiB  85 GiB 21.51 1.12 500     up         osd.13
  14   hdd 0.10500  1.00000 108 GiB  22 GiB  13 GiB  24 MiB 1000 MiB  86 GiB 20.41 1.07 519     up         osd.14
  -5       0.52699        - 540 GiB 100 GiB  55 GiB  84 MiB  4.9 GiB 440 GiB 18.43 0.96   -            host c152
   5   hdd 0.10500  1.00000 108 GiB  20 GiB  11 GiB  19 MiB 1005 MiB  88 GiB 18.57 0.97 515     up         osd.5
   6   hdd 0.10500  1.00000 108 GiB  20 GiB  11 GiB  15 MiB 1009 MiB  88 GiB 18.77 0.98 502     up         osd.6
   7   hdd 0.10500  1.00000 108 GiB  19 GiB  10 GiB  18 MiB 1006 MiB  89 GiB 17.56 0.92 526     up         osd.7
   8   hdd 0.10500  1.00000 108 GiB  21 GiB  12 GiB  14 MiB 1010 MiB  87 GiB 19.00 0.99 501     up         osd.8
   9   hdd 0.10500  1.00000 108 GiB  20 GiB  11 GiB  18 MiB 1006 MiB  88 GiB 18.26 0.95 516     up         osd.9
  -3       0.52699        - 540 GiB 100 GiB  55 GiB  97 MiB  4.9 GiB 440 GiB 18.43 0.96   -            host c153
   0   hdd 0.10500  1.00000 108 GiB  20 GiB  11 GiB  24 MiB 1000 MiB  88 GiB 18.79 0.98 523     up         osd.0
   1   hdd 0.10500  1.00000 108 GiB  19 GiB  10 GiB  22 MiB 1002 MiB  89 GiB 18.03 0.94 510     up         osd.1
   2   hdd 0.10500  1.00000 108 GiB  19 GiB 9.9 GiB  13 MiB 1011 MiB  89 GiB 17.49 0.91 513     up         osd.2
   3   hdd 0.10500  1.00000 108 GiB  20 GiB  11 GiB  17 MiB 1007 MiB  88 GiB 18.62 0.97 491     up         osd.3
   4   hdd 0.10500  1.00000 108 GiB  21 GiB  12 GiB  21 MiB 1003 MiB  87 GiB 19.24 1.00 523     up         osd.4
                      TOTAL 1.5 TiB 290 GiB 164 GiB 263 MiB   14 GiB 1.2 TiB 19.15
MIN/MAX VAR: 0.91/1.16  STDDEV: 1.34


2、the old  ceph osd df result

ID CLASS WEIGHT  REWEIGHT SIZE    RAW USE DATA    OMAP    META     AVAIL   %USE  VAR  PGS STATUS
10   hdd 0.10500  1.00000 108 GiB  24 GiB  15 GiB  24 MiB 1000 MiB  84 GiB 22.26 1.16 534     up
12   hdd 0.10500  1.00000 108 GiB  21 GiB  12 GiB  19 MiB 1005 MiB  87 GiB 19.59 1.02 495     up
13   hdd 0.10500  1.00000 108 GiB  23 GiB  14 GiB  16 MiB 1008 MiB  85 GiB 21.51 1.12 500     up
14   hdd 0.10500  1.00000 108 GiB  22 GiB  13 GiB  24 MiB 1000 MiB  86 GiB 20.41 1.07 519     up
 5   hdd 0.10500  1.00000 108 GiB  20 GiB  11 GiB  19 MiB 1005 MiB  88 GiB 18.57 0.97 515     up
 6   hdd 0.10500  1.00000 108 GiB  20 GiB  11 GiB  15 MiB 1009 MiB  88 GiB 18.77 0.98 502     up
 7   hdd 0.10500  1.00000 108 GiB  19 GiB  10 GiB  18 MiB 1006 MiB  89 GiB 17.56 0.92 526     up
 8   hdd 0.10500  1.00000 108 GiB  21 GiB  12 GiB  14 MiB 1010 MiB  87 GiB 19.00 0.99 501     up
 9   hdd 0.10500  1.00000 108 GiB  20 GiB  11 GiB  18 MiB 1006 MiB  88 GiB 18.26 0.95 516     up
10   hdd 0.10500  1.00000 108 GiB  24 GiB  15 GiB  24 MiB 1000 MiB  84 GiB 22.26 1.16 534     up
12   hdd 0.10500  1.00000 108 GiB  21 GiB  12 GiB  19 MiB 1005 MiB  87 GiB 19.59 1.02 495     up
13   hdd 0.10500  1.00000 108 GiB  23 GiB  14 GiB  16 MiB 1008 MiB  85 GiB 21.51 1.12 500     up
14   hdd 0.10500  1.00000 108 GiB  22 GiB  13 GiB  24 MiB 1000 MiB  86 GiB 20.41 1.07 519     up
 0   hdd 0.10500  1.00000 108 GiB  20 GiB  11 GiB  24 MiB 1000 MiB  88 GiB 18.79 0.98 523     up
 1   hdd 0.10500  1.00000 108 GiB  19 GiB  10 GiB  22 MiB 1002 MiB  89 GiB 18.03 0.94 510     up
 2   hdd 0.10500  1.00000 108 GiB  19 GiB 9.9 GiB  13 MiB 1011 MiB  89 GiB 17.49 0.91 513     up
 3   hdd 0.10500  1.00000 108 GiB  20 GiB  11 GiB  17 MiB 1007 MiB  88 GiB 18.62 0.97 491     up
 4   hdd 0.10500  1.00000 108 GiB  21 GiB  12 GiB  21 MiB 1003 MiB  87 GiB 19.24 1.00 523     up
 5   hdd 0.10500  1.00000 108 GiB  20 GiB  11 GiB  19 MiB 1005 MiB  88 GiB 18.57 0.97 515     up
 6   hdd 0.10500  1.00000 108 GiB  20 GiB  11 GiB  15 MiB 1009 MiB  88 GiB 18.77 0.98 502     up
 7   hdd 0.10500  1.00000 108 GiB  19 GiB  10 GiB  18 MiB 1006 MiB  89 GiB 17.56 0.92 526     up
 8   hdd 0.10500  1.00000 108 GiB  21 GiB  12 GiB  14 MiB 1010 MiB  87 GiB 19.00 0.99 501     up
 9   hdd 0.10500  1.00000 108 GiB  20 GiB  11 GiB  18 MiB 1006 MiB  88 GiB 18.26 0.95 516     up
 0   hdd 0.10500  1.00000 108 GiB  20 GiB  11 GiB  24 MiB 1000 MiB  88 GiB 18.79 0.98 523     up
 1   hdd 0.10500  1.00000 108 GiB  19 GiB  10 GiB  22 MiB 1002 MiB  89 GiB 18.03 0.94 510     up
 2   hdd 0.10500  1.00000 108 GiB  19 GiB 9.9 GiB  13 MiB 1011 MiB  89 GiB 17.49 0.91 513     up
 3   hdd 0.10500  1.00000 108 GiB  20 GiB  11 GiB  17 MiB 1007 MiB  88 GiB 18.62 0.97 491     up
 4   hdd 0.10500  1.00000 108 GiB  21 GiB  12 GiB  21 MiB 1003 MiB  87 GiB 19.24 1.00 523     up
10   hdd 0.10500  1.00000 108 GiB  24 GiB  15 GiB  24 MiB 1000 MiB  84 GiB 22.26 1.16 534     up
12   hdd 0.10500  1.00000 108 GiB  21 GiB  12 GiB  19 MiB 1005 MiB  87 GiB 19.59 1.02 495     up
13   hdd 0.10500  1.00000 108 GiB  23 GiB  14 GiB  16 MiB 1008 MiB  85 GiB 21.51 1.12 500     up
14   hdd 0.10500  1.00000 108 GiB  22 GiB  13 GiB  24 MiB 1000 MiB  86 GiB 20.41 1.07 519     up
 5   hdd 0.10500  1.00000 108 GiB  20 GiB  11 GiB  19 MiB 1005 MiB  88 GiB 18.57 0.97 515     up
 6   hdd 0.10500  1.00000 108 GiB  20 GiB  11 GiB  15 MiB 1009 MiB  88 GiB 18.77 0.98 502     up
 7   hdd 0.10500  1.00000 108 GiB  19 GiB  10 GiB  18 MiB 1006 MiB  89 GiB 17.56 0.92 526     up
 8   hdd 0.10500  1.00000 108 GiB  21 GiB  12 GiB  14 MiB 1010 MiB  87 GiB 19.00 0.99 501     up
 9   hdd 0.10500  1.00000 108 GiB  20 GiB  11 GiB  18 MiB 1006 MiB  88 GiB 18.26 0.95 516     up
 0   hdd 0.10500  1.00000 108 GiB  20 GiB  11 GiB  24 MiB 1000 MiB  88 GiB 18.79 0.98 523     up
 1   hdd 0.10500  1.00000 108 GiB  19 GiB  10 GiB  22 MiB 1002 MiB  89 GiB 18.03 0.94 510     up
 2   hdd 0.10500  1.00000 108 GiB  19 GiB 9.9 GiB  13 MiB 1011 MiB  89 GiB 17.49 0.91 513     up
 3   hdd 0.10500  1.00000 108 GiB  20 GiB  11 GiB  17 MiB 1007 MiB  88 GiB 18.62 0.97 491     up
 4   hdd 0.10500  1.00000 108 GiB  21 GiB  12 GiB  21 MiB 1003 MiB  87 GiB 19.24 1.00 523     up
                    TOTAL 1.5 TiB 290 GiB 164 GiB 263 MiB   14 GiB 1.2 TiB 19.15
3、the new ceph osd df result

ID CLASS WEIGHT  REWEIGHT SIZE    RAW USE DATA    OMAP    META     AVAIL   %USE  VAR  PGS STATUS
10   hdd 0.10500  1.00000 108 GiB  24 GiB  15 GiB  24 MiB 1000 MiB  84 GiB 22.26 1.16 534     up
12   hdd 0.10500  1.00000 108 GiB  21 GiB  12 GiB  19 MiB 1005 MiB  87 GiB 19.59 1.02 495     up
13   hdd 0.10500  1.00000 108 GiB  23 GiB  14 GiB  16 MiB 1008 MiB  85 GiB 21.51 1.12 500     up
14   hdd 0.10500  1.00000 108 GiB  22 GiB  13 GiB  24 MiB 1000 MiB  86 GiB 20.41 1.07 519     up
 5   hdd 0.10500  1.00000 108 GiB  20 GiB  11 GiB  19 MiB 1005 MiB  88 GiB 18.57 0.97 515     up
 6   hdd 0.10500  1.00000 108 GiB  20 GiB  11 GiB  15 MiB 1009 MiB  88 GiB 18.77 0.98 502     up
 7   hdd 0.10500  1.00000 108 GiB  19 GiB  10 GiB  18 MiB 1006 MiB  89 GiB 17.56 0.92 526     up
 8   hdd 0.10500  1.00000 108 GiB  21 GiB  12 GiB  14 MiB 1010 MiB  87 GiB 19.00 0.99 501     up
 9   hdd 0.10500  1.00000 108 GiB  20 GiB  11 GiB  18 MiB 1006 MiB  88 GiB 18.26 0.95 516     up
 0   hdd 0.10500  1.00000 108 GiB  20 GiB  11 GiB  24 MiB 1000 MiB  88 GiB 18.79 0.98 523     up
 1   hdd 0.10500  1.00000 108 GiB  19 GiB  10 GiB  22 MiB 1002 MiB  89 GiB 18.03 0.94 510     up
 2   hdd 0.10500  1.00000 108 GiB  19 GiB 9.9 GiB  13 MiB 1011 MiB  89 GiB 17.49 0.91 513     up
 3   hdd 0.10500  1.00000 108 GiB  20 GiB  11 GiB  17 MiB 1007 MiB  88 GiB 18.62 0.97 491     up
 4   hdd 0.10500  1.00000 108 GiB  21 GiB  12 GiB  21 MiB 1003 MiB  87 GiB 19.24 1.00 523     up
                    TOTAL 1.5 TiB 290 GiB 164 GiB 263 MiB   14 GiB 1.2 TiB 19.15

**Review by tchaikov — APPROVED** [review]

**Comment by tchaikov** [comment]
@jhonxue could you revise the title of the commit message? as we don't use the ceph command as the prefix. how about using something like:

> osd: ignore already dumped osd in dump_item()

?

**Comment by jhonxue** [comment]
> @jhonxue could you revise the title of the commit message? as we don't use the ceph command as the prefix. how about using something like:
> 
> > osd: ignore already dumped osd in dump_item()
> 
> ?

ok, i will. thanks

**Review by tchaikov — APPROVED** [review]

**Comment by tchaikov** [comment]
- https://pulpito.ceph.com/kchai-2021-03-09_12:22:01-rados-wip-kefu-testing-2021-03-09-1847-distro-basic-smithi/
- https://pulpito.ceph.com/kchai-2021-03-10_06:55:19-rados-wip-kefu-testing-2021-03-09-1847-distro-basic-gibba/

the crash of 

- https://pulpito.ceph.com/kchai-2021-03-10_06:55:19-rados-wip-kefu-testing-2021-03-09-1847-distro-basic-gibba/5952985/
- https://pulpito.ceph.com/kchai-2021-03-10_06:55:19-rados-wip-kefu-testing-2021-03-09-1847-distro-basic-gibba/5952993/

are new ones. but they are not likely to be related to this change as this change is not on the io path.

**Comment by tchaikov** [comment]
jenkins test make check

**Pull request merged**
