### PR TITLE
rbd-nbd: don't map an image with size 0.

### PR DESCRIPTION
**Pull request by liupan1111**
Fixes: http://tracker.ceph.com/issues/19347
Signed-off-by: Pan Liu <liupan1111@gmail.com>

### CODE REVIEW

**Comment by liupan1111** [comment]
@trociny a new bug fix.

**Comment by trociny** [comment]
@liupan1111 I am not sure that just because `lsblk` skips 0 size devices we should disallow mapping for 0 size images.

Note, later you may do `rbd resize` and then `lsblk` will be happy.

Or vice versa, you can successfully map a non-zero image and then shrink it to zero. (BTW, that is why I was not very happy with size check  we added recently -- we can check the size on start, but we can't do anything from preventing a user to insanely change the size later).

@dillaman what do you think?

**Comment by dillaman** [comment]
@trociny @liupan1111 Honestly -- if it doesn't crash, I really would prefer to not worry about cases like this. We support creating zero byte images for the fact that we need to provide a limit and "how small is too small?".

**Comment by liupan1111** [comment]
@trociny @dillaman I agree, I will close this pr, thanks.

**Pull request closed without merging**
