### PR TITLE
librbd: integrate journaling support for IO operations

### PR DESCRIPTION
**Pull request by dillaman**

### CODE REVIEW

**Comment by jdurgin** [comment]
I haven't gotten through all of this yet (up to the meat of it now, 'librdb: initial interface with journal library', but have a couple comments. I really like the i/o path refactoring - much more consistent now.

For enabling the journal, we'd mentioned doing a hidden snapshot as a basis for mirroring at that point. Were you thinking of doing that at another time, like when mirroring is enabled, or just didn't need it yet?

The cmake files will need updating for this (probably in later branches too).

**Comment by dillaman** [comment]
@jdurgin I punted on the maintenance level stuff for the time being.  The hidden snapshot for mirroring should be added later -- I was thinking as part of the mirroring daemon since it makes for a consistent workflow (it will already need to remove the snapshot after it catches up).

**Comment by jdurgin** [comment]
Looking good in general. Will run through a subset of the rbd suite to check for regressions.

**Comment by jdurgin** [comment]
At least a couple real failures here, from copy.sh and read-flags.sh:

http://pulpito.ceph.com/joshd-2015-11-16_22:08:47-rbd-wip-11287-rebased---basic-vps/

**Comment by dillaman** [comment]
@jdurgin The read-flags tests are only working on the jewel branch (needs merged back to master).  I'll take a look at the other failures.

http://qa-proxy.ceph.com/teuthology/teuthology-2015-11-13_23:00:08-rbd-master---basic-multi/1148949/teuthology.log

**Comment by dillaman** [comment]
@jdurgin I had fixes for the exposed issues on my other journaling branch.  I cherry-picked and locally retested librbd_python and copy.sh successfully.

**Pull request merged**
