### PR TITLE
qa/workunits: switch to OpenStack Ocata release for RBD testing

### PR DESCRIPTION
**Pull request by dillaman**
Signed-off-by: Jason Dillaman <dillaman@redhat.com>

### CODE REVIEW

**Comment by dillaman** [comment]
All stable branches of devstack + tempest are currently broken due to a setuptools dependency issue upstream. Once fixed, it's probably a good idea to start testing ocata now that it's been released.

**Comment by liewegas** [comment]
@dillaman has this been tested?

**Comment by dillaman** [comment]
@liewegas Python dependencies are still broken upstream -- Devstack fails to install tempest. I need to figure out how they jerry-rigged it to properly work upstream while the PIP/setuptools/etc dependencies are all messed up.

**Comment by dillaman** [comment]
Worked around the Python setuptools issue that was preventing devstack from running. The Ocata release is now functional w/ the one known upstream Cinder test failure [1][2].

[1] http://pulpito.ceph.com/jdillaman-2017-05-02_16:48:44-rbd-wip-librbd-devstack-tempest-distro-basic-smithi/
[2] https://bugs.launchpad.net/cinder/+bug/1686278

**Comment by trociny** [comment]
@ceph-jenkins retest this please

**Pull request merged**
