### PR TITLE
msg/async: update to work with dpdk shipped with spdk v17.10

### PR DESCRIPTION
**Pull request by tchaikov**

### CODE REVIEW

**Comment by tchaikov** [comment]
@liu-chunmei

**Comment by liu-chunmei** [comment]
@tchaikov if we use iova instead of phy addr, what driver module should be installed? can I still just use igb_uio kernel module?

**Comment by liu-chunmei** [comment]
@tchaikov do you do the async/dpdk test ?  or you just test spdk?

**Comment by tchaikov** [comment]
> if we use iova instead of phy addr, what driver module should be installed? can I still just use igb_uio kernel module?

@liu-chunmei see https://github.com/spdk/dpdk/blob/spdk-17.11/lib/librte_eal/common/include/rte_memory.h#L104 and https://github.com/spdk/dpdk/blob/spdk-17.11/lib/librte_eal/common/include/rte_malloc.h#L340

> do you do the async/dpdk test ? or you just test spdk?

i just fix the build =)

**Pull request merged**
