### PR TITLE
qa: Add ceph-ansible installer.

### PR DESCRIPTION
**Pull request by wusui**
Also fix iso rhel handling in openstack script
Updated openstack README.

Fixes: http://tracker.ceph.com/issues/16770
Signed-off-by: Warren Usui wusui@redhat.com

### CODE REVIEW

**Comment by tmuthamizhan** [comment]
in our lab setup, we have stock and non stock images[comes with RH subscription manager settings by default]
it would be nice to check and see if RH subscription manager is enabled on the test setup before enabling subscription manager settings [so as to avoid enabling RH subscription on an already enabled system]. I believe these are independent scripts designed to run on any test setup.

for testing ceph packages downstream, we don't need the following values to be set in "qa/qa_scripts/openstack/ceph_install_w_ansible/execs/ceph_ansible.sh" : ceph_origin=distro and
ceph_stable=true 

please reconsider hardcoding the values for "monitor_interface" and "public_network" as currently its values pertain to magna nodes.

**Comment by wusui** [comment]
I am pushing a new version with tests for making sure the subscription manager is not run if already enabled.  Also, the monitor_interface and public_network values will be made configurable, using their current values as defaults if none are specified.  I will document this.

While retesting these changes, it appears that ceph_origin=distro and ceph_stable=true are both needed to get ceph-ansible to build properly.  The upstream value for ceph_origin breaks the ceph-ansible run almost immediately, and the ceph-stable value, when not set, seems to cause the OSD installations to hang.

I am going to push an new version that should be squished when checked in.

**Comment by dachary** [comment]
jenkins test this please (no logs)

**Comment by liewegas** [comment]
Is this safe to merge?

**Comment by tmuthamizhan** [comment]
@liewegas , i think this is safe to merge as it wont interfere with any existing tasks/suites.

**Pull request merged**
