### PR TITLE
osd: do_recovery cleanup

### PR DESCRIPTION
**Pull request by wonzhq**

### CODE REVIEW

**Comment by liewegas** [comment]
Reviewed-by:

**Comment by wonzhq** [comment]
@tchaikov I've run the teuthology testing for this PR and #5453 in our local cluster. There were 2 failures. One is fixed by #5679. And the other is the same as that in #5680. These two failures are not relevant to these 2 PRs. So I'm considering they've passed the testing.

**Comment by tchaikov** [comment]
@wonzhq what is the subset of rados suite you were running? something like n/20 would suffice. just want to make sure #5415 and #5453 have enough coverage.

**Comment by wonzhq** [comment]
@tchaikov actually I was running 1/7 subset. And used the '--filter-out' option to filter out some cases which are not able to run in our cluster. Totally 175 test cases were exercised.

**Comment by tchaikov** [comment]
:+1:

**Pull request merged**
