### PR TITLE
crush: don't normalize input of crush_ln iteratively

### PR DESCRIPTION
**Pull request by branch-predictor**
Use __builtin_clz() supported by GCC and Clang to figure out
how many bits we should shift instead of shifting by a bit
in a loop until the value gets normalized. Improves performance
of this function by up to 3x in worst-case scenario and overall
straw2 performance by ~10%.
Remove extra x1 variable while at it, it's just temporary
placeholder that clutters the code unnecessarily.

Signed-off-by: Piotr Dałek <git@predictor.org.pl>

### CODE REVIEW

**Comment by liewegas** [comment]
This is awesome!  Can you put the x1 cleanup in a separate commit?

**Comment by dachary** [comment]
<pre>
Reviewed-by: Loic Dachary &lt;ldachary@redhat.com>
</pre>

**Comment by branch-predictor** [comment]
@liewegas sure, done!

**Comment by tchaikov** [comment]
tested at http://pulpito.ceph.com/kchai-2016-09-10_15:46:37-rados-wip-kefu-testing---basic-mira/408471/

the failed test of http://pulpito.ceph.com/kchai-2016-09-10_15:46:37-rados-wip-kefu-testing---basic-mira/408471/ is irrelevant.

**Comment by idryomov** [comment]
Pulling this into the kernel for 4.9.

**Pull request merged**
