### PR TITLE
luminous: qa: drop upgrade/luminous-x

### PR DESCRIPTION
**Pull request by smithfarm**
This suite would typically be run from the mimic or master branches, not
luminous.

This commit is intentionally not a cherry-pick, since it is relevant to
luminous only.

Signed-off-by: Nathan Cutler <ncutler@suse.com>

### CODE REVIEW

**Comment by smithfarm** [comment]
After this, we have left in `upgrade/`:

```
client-upgrade
client-upgrade-luminous
hammer-jewel-x
jewel-x
kraken-x
luminous-p2p
```

@yuriw What is the difference between "client-upgrade" and "client-upgrade-luminous" ?

**Comment by yuriw** [comment]
on master I think we need no suites in upgrade at all except `mimic-x` which is being worked on, we have now:
client-upgrade
client-upgrade-luminous
hammer-jewel-x
jewel-x
kraken-x
luminous-p2p

**Comment by smithfarm** [comment]
> was doing the same at the same time

@yuriw Sorry for stepping on your toes. Regarding the cleanup in `master` branch, do you want me to open a PR for that?

**Comment by yuriw** [comment]
@smithfarm np at all :) pls do

**Comment by smithfarm** [comment]
@yuriw See #23305

**Pull request merged**
