### PR TITLE
crush: remove invalid upmap items

### PR DESCRIPTION
**Pull request by hjwsm1989**
We can not cancel in verify_upmap if remap an osd to different root bucket,

cluster topology:
osd.0 ~ osd.29 belongs to datacenter 1
osd30 ~ osd.59 belongs to datacenter 2
crush rule:
  take datacenter 1
  chooseleaf 2 host
  emit
  take datacenter 2
  chooseleaf 2 host
  emit
The pg's primary osd in datacenter 1.

We should cancel the pgid from upmap_items like below
1) from [26,12,54,46] to [30,12,54,46]
pg_upmap_items [26,30]

2) from [16,25,53,31] to [40,25,53,0]
pg_upmap_items [16,20,31,0]

Fixes: https://tracker.ceph.com/issues/42485
Fixes: https://tracker.ceph.com/issues/43124

Signed-off-by: huangjun <huangjun@xsky.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by hjwsm1989** [comment]
@liewegas @xiexingguo 
did this make sense to resolve the bug?
or we should work out a more robust way？

**Comment by tchaikov** [comment]
http://pulpito.ceph.com/kchai-2019-12-09_12:39:45-rados-wip-kefu-testing-2019-12-09-1434-distro-basic-smithi/

failure tracked / fixed by
- https://tracker.ceph.com/issues/43192
- https://tracker.ceph.com/issues/42764
- https://tracker.ceph.com/issues/43070
- #32143

**Comment by hjwsm1989** [comment]
@xiexingguo any comments?

**Comment by xiexingguo** [comment]
@dzafman David, mind double-checking this?

**Comment by dzafman** [comment]
I put this pull request in https://tracker.ceph.com/issues/43124

**Comment by hjwsm1989** [comment]
> nit: I think your second example in the commit message should be pg_upmap_items [16,40,31,0]

yes

**Pull request merged**
