### PR TITLE
octopus: mgr/dashboard: Remove username, password fields from Manager Modules/dashboard,influx

### PR DESCRIPTION
**Pull request by aaSharma14**
backport tracker: https://tracker.ceph.com/issues/50049

---

backport of https://github.com/ceph/ceph/pull/39908
parent tracker: https://tracker.ceph.com/issues/49645

this backport was staged using ceph-backport.sh version 16.0.0.6848
find the latest version at https://github.com/ceph/ceph/blob/master/src/script/ceph-backport.sh

### CODE REVIEW

**Review by pereman2 — COMMENTED** [review]
It seems that https://github.com/ceph/ceph/pull/40489 and this PR are duplicated

**Comment by aaSharma14** [comment]
> It seems that #40489 and this PR are duplicated

#40489 is the pacific branch backport. This is the octopus branch backport.

**Comment by aaSharma14** [comment]
jenkins retest this please

**Comment by aaSharma14** [comment]
jenkins retest this please

**Review by nizamial09 — APPROVED** [review]

**Comment by aaSharma14** [comment]
jenkins test api

**Review by avanthakkar — APPROVED** [review]

**Comment by epuertat** [comment]
@tchaikov please confirm whether your testing was positive or not? Thanks!

**Review by Waadkh7 — APPROVED** [review]

**Comment by tchaikov** [comment]
- https://pulpito.ceph.com/kchai-2021-04-12_02:35:25-rados-wip-kefu-octopus-testing-2021-04-11-2349-distro-basic-gibba/
- https://pulpito.ceph.com/kchai-2021-04-12_13:55:39-rados-wip-kefu-octopus-testing-2021-04-11-2349-distro-basic-smithi/

i think most of cephadm test failures are caused by https://tracker.ceph.com/issues/49293

**Review by idryomov — DISMISSED** [review]
Please get rid of the merge commit.

**Review by idryomov — COMMENTED** [review]
My concern has been addressed.

**Pull request merged**
