### PR TITLE
rgw: don't overwrite bucket / object owner when setting acls

### PR DESCRIPTION
**Pull request by dachary**
Fixes: #10978
Backport: hammer, firefly

Signed-off-by: Yehuda Sadeh <yehuda@redhat.com>
(cherry picked from commit eb13f2d4b60c031f16139f7cc4237c012644dd78)

### CODE REVIEW

**Comment by dachary** [comment]
@yehudasa the "req_state::object" data member was removed in 1dcdea37860a2fc4350289e857f45d14ee9b8a34 and restored 7f26ab76d63ad84f0ee817d4997c368e6a0b003f but with a different semantic. I'm not sure how this patch should be backported. Feel free to submit a different pull request if it's easier to do than to explain ;-)

**Comment by yehudasa** [comment]
@dachary please look at wip-dho, it's done against firefly

**Comment by dachary** [comment]
When I compare https://github.com/dachary/ceph/commit/6ca6791650ac714cf4a7ae7288a298af41716307 with https://github.com/dachary/ceph/commit/898ec55b786c7eb27ef29b3c16a146100221f826 . Looking further.

**Comment by dachary** [comment]
@yehudasa nevermind, forgot to update with wip-dho changes from tonight ;-)

**Pull request merged**
