### PR TITLE
bug fix: librados segmentation fault, when two read ops share one Aio…

### PR DESCRIPTION
**Pull request by cmgitdream**
As we know,  AioCompletionImpl is mapped to one async io request. 
Buf if there are two or more aio requests bind to one AioCompletionImpl, 
some unexpected result will happen.
      this bug fix is about two aio read opeatons bind to one AioCompletionImpl 
causing segmentaion fault. 

I use a simple librados client to test the bug, the main logic is:

rados_read_op_read(read_op, 0, len, buf, &bytes_read, &ret);
rados_read_op_read(read_op2, 0, len, buf2, &bytes_read2, &ret2);
ret = rados_aio_read_op_operate(read_op, ioctx, read_completion, object, 0);
ret = rados_aio_read_op_operate(read_op2, ioctx, read_completion, object, 0);
ret = rados_aio_wait_for_complete(read_completion);

and other misc binds are:
aio_write, aio_write
aio_read, aio_write
aio_stat, aio_read
aio_write, aio_stat
......

Maybe some binds not causing segmentaion fault, but we 
still need to make AioCompletionImpl semantic right.

### CODE REVIEW

**Comment by liewegas** [comment]
lgtm

**Comment by athanatos** [comment]
Caused crashes in testing, removing wip-sam-testing for now:

2015-08-25T21:16:26.588 INFO:teuthology.run_tasks:Running task radosbench...
2015-08-25T21:16:26.589 INFO:tasks.radosbench:Beginning radosbench...
2015-08-25T21:16:26.589 INFO:tasks.ceph.ceph_manager:creating pool_name unique_pool_0
2015-08-25T21:16:26.589 INFO:teuthology.orchestra.run.burnupi59:Running: 'adjust-ulimits ceph-coverage /home/ubuntu/cephtest/archive/coverage ceph osd pool create unique_pool_0 16'
2015-08-25T21:16:27.655 INFO:teuthology.orchestra.run.burnupi59.stderr:marked out osd.0.
2015-08-25T21:16:27.670 INFO:teuthology.orchestra.run.burnupi59.stderr:pool 'unique_pool_0' created
2015-08-25T21:16:27.693 INFO:teuthology.orchestra.run.burnupi59:Running: "/bin/sh -c 'adjust-ulimits ceph-coverage /home/ubuntu/cephtest/archive/coverage rados --no-log-to-stderr --name client.0 -b 4194304 -p unique_pool_0 bench 1800 write'"
2015-08-25T21:16:27.760 DEBUG:teuthology.run_tasks:Unwinding manager radosbench
2015-08-25T21:16:27.760 INFO:tasks.radosbench:joining radosbench (timing out after 9000s)
2015-08-25T21:16:27.823 INFO:tasks.radosbench.radosbench.0.burnupi59.stderr:warning: line 28: 'osd_pool_default_size' in section 'global' redefined
2015-08-25T21:16:27.844 INFO:tasks.radosbench.radosbench.0.burnupi59.stdout:Maintaining 16 concurrent writes of 4194304 bytes for up to 1800 seconds
2015-08-25T21:16:27.844 INFO:tasks.radosbench.radosbench.0.burnupi59.stdout:Object prefix: benchmark_data_burnupi59_25963
2015-08-25T21:16:27.885 INFO:tasks.radosbench.radosbench.0.burnupi59.stdout:  sec Cur ops   started  finished  avg MB/s  cur MB/s  last lat   avg lat
2015-08-25T21:16:27.885 INFO:tasks.radosbench.radosbench.0.burnupi59.stdout:    0       0         0         0         0         0         -         0
2015-08-25T21:16:27.885 INFO:tasks.radosbench.radosbench.0.burnupi59.stderr:librados/IoCtxImpl.cc: In function 'librados::IoCtxImpl::C_aio_Ack::C_aio_Ack(librados::AioCompletionImpl*)' thread 7f911c0cf840 time 2015-08-25 21:16:27.876588
2015-08-25T21:16:27.885 INFO:tasks.radosbench.radosbench.0.burnupi59.stderr:librados/IoCtxImpl.cc: 1302: FAILED assert(!c->io)
2015-08-25T21:16:27.894 INFO:tasks.radosbench.radosbench.0.burnupi59.stderr: ceph version 9.0.3-879-g09b1303 (09b1303a19d2aaeca4e44585d4724ef3f92f4d77)
2015-08-25T21:16:27.894 INFO:tasks.radosbench.radosbench.0.burnupi59.stderr: 1: (()+0x1581fb) [0x7f91197c81fb]
2015-08-25T21:16:27.894 INFO:tasks.radosbench.radosbench.0.burnupi59.stderr: 2: (()+0xadbda) [0x7f911971dbda]
2015-08-25T21:16:27.894 INFO:tasks.radosbench.radosbench.0.burnupi59.stderr: 3: (()+0xb2159) [0x7f9119722159]
2015-08-25T21:16:27.894 INFO:tasks.radosbench.radosbench.0.burnupi59.stderr: 4: (librados::IoCtx::aio_write(std::string const&, librados::AioCompletion*, ceph::buffer::list const&, unsigned long, unsigned long)+0x44) [0x7f91196e6bf4]
2015-08-25T21:16:27.894 INFO:tasks.radosbench.radosbench.0.burnupi59.stderr: 5: (ObjBencher::write_bench(int, int, std::string const&)+0x53d) [0x7f911bed7d7d]
2015-08-25T21:16:27.895 INFO:tasks.radosbench.radosbench.0.burnupi59.stderr: 6: (ObjBencher::aio_bench(int, int, int, int, bool, std::string const&, bool)+0x20a) [0x7f911bed916a]
2015-08-25T21:16:27.895 INFO:tasks.radosbench.radosbench.0.burnupi59.stderr: 7: (()+0x1debc) [0x7f911bebdebc]
2015-08-25T21:16:27.895 INFO:tasks.radosbench.radosbench.0.burnupi59.stderr: 8: (main()+0x2ca) [0x7f911beb11fa]
2015-08-25T21:16:27.896 INFO:tasks.radosbench.radosbench.0.burnupi59.stderr: 9: (__libc_start_main()+0xf5) [0x7f9115da2ec5]
2015-08-25T21:16:27.896 INFO:tasks.radosbench.radosbench.0.burnupi59.stderr: 10: (()+0x132a7) [0x7f911beb32a7]
2015-08-25T21:16:27.896 INFO:tasks.radosbench.radosbench.0.burnupi59.stderr: NOTE: a copy of the executable, or `objdump -rdS <executable>` is needed to interpret this.
2015-08-25T21:16:27.896 INFO:tasks.radosbench.radosbench.0.burnupi59.stderr:terminate called after throwing an instance of 'ceph::FailedAssertion'
2015-08-25T21:16:27.897 INFO:tasks.radosbench.radosbench.0.burnupi59.stderr:*** Caught signal (Aborted) **
2015-08-25T21:16:27.897 INFO:tasks.radosbench.radosbench.0.burnupi59.stderr: in thread 7f911c0cf840
2015-08-25T21:16:27.897 INFO:tasks.radosbench.radosbench.0.burnupi59.stderr: ceph version 9.0.3-879-g09b1303 (09b1303a19d2aaeca4e44585d4724ef3f92f4d77)
2015-08-25T21:16:27.898 INFO:tasks.radosbench.radosbench.0.burnupi59.stderr: 1: (()+0x407ea) [0x7f911bee07ea]
2015-08-25T21:16:27.898 INFO:tasks.radosbench.radosbench.0.burnupi59.stderr: 2: (()+0x10340) [0x7f9116b7b340]
2015-08-25T21:16:27.898 INFO:tasks.radosbench.radosbench.0.burnupi59.stderr: 3: (gsignal()+0x39) [0x7f9115db7f89]
2015-08-25T21:16:27.898 INFO:tasks.radosbench.radosbench.0.burnupi59.stderr: 4: (abort()+0x148) [0x7f9115dbb398]
2015-08-25T21:16:27.898 INFO:tasks.radosbench.radosbench.0.burnupi59.stderr: 5: (__gnu_cxx::__verbose_terminate_handler()+0x155) [0x7f91166c36b5]
2015-08-25T21:16:27.898 INFO:tasks.radosbench.radosbench.0.burnupi59.stderr: 6: (()+0x5e836) [0x7f91166c1836]
2015-08-25T21:16:27.898 INFO:tasks.radosbench.radosbench.0.burnupi59.stderr: 7: (()+0x5e863) [0x7f91166c1863]
2015-08-25T21:16:27.899 INFO:tasks.radosbench.radosbench.0.burnupi59.stderr: 8: (()+0x5eaa2) [0x7f91166c1aa2]
2015-08-25T21:16:27.899 INFO:tasks.radosbench.radosbench.0.burnupi59.stderr: 9: (()+0x1583e8) [0x7f91197c83e8]
2015-08-25T21:16:27.899 INFO:tasks.radosbench.radosbench.0.burnupi59.stderr: 10: (()+0xadbda) [0x7f911971dbda]
2015-08-25T21:16:27.899 INFO:tasks.radosbench.radosbench.0.burnupi59.stderr: 11: (()+0xb2159) [0x7f9119722159]
2015-08-25T21:16:27.899 INFO:tasks.radosbench.radosbench.0.burnupi59.stderr: 12: (librados::IoCtx::aio_write(std::string const&, librados::AioCompletion*, ceph::buffer::list const&, unsigned long, unsigned long)+0x44) [0x7f91196e6bf4]
2015-08-25T21:16:27.900 INFO:tasks.radosbench.radosbench.0.burnupi59.stderr: 13: (ObjBencher::write_bench(int, int, std::string const&)+0x53d) [0x7f911bed7d7d]
2015-08-25T21:16:27.900 INFO:tasks.radosbench.radosbench.0.burnupi59.stderr: 14: (ObjBencher::aio_bench(int, int, int, int, bool, std::string const&, bool)+0x20a) [0x7f911bed916a]
2015-08-25T21:16:27.900 INFO:tasks.radosbench.radosbench.0.burnupi59.stderr: 15: (()+0x1debc) [0x7f911bebdebc]
2015-08-25T21:16:27.900 INFO:tasks.radosbench.radosbench.0.burnupi59.stderr: 16: (main()+0x2ca) [0x7f911beb11fa]
2015-08-25T21:16:27.900 INFO:tasks.radosbench.radosbench.0.burnupi59.stderr: 17: (__libc_start_main()+0xf5) [0x7f9115da2ec5]
2015-08-25T21:16:27.901 INFO:tasks.radosbench.radosbench.0.burnupi59.stderr: 18: (()+0x132a7) [0x7f911beb32a7]
2015-08-25T21:16:27.901 INFO:tasks.radosbench.radosbench.0.burnupi59.stderr:2015-08-25 21:16:27.889101 7f911c0cf840 -1 *** Caught signal (Aborted) **
2015-08-25T21:16:27.901 INFO:tasks.radosbench.radosbench.0.burnupi59.stderr: in thread 7f911c0cf840
2015-08-25T21:16:27.901 INFO:tasks.radosbench.radosbench.0.burnupi59.stderr:

**Comment by cmgitdream** [comment]
@athanatos  
The crash is caused by aio_write, 
and I just have pushed another commit to support aio_write and series methods, 
please test again!

**Comment by cmgitdream** [comment]
@liewegas 
@athanatos 
please review and test again!

**Comment by jdurgin** [comment]
lgtm

**Comment by tchaikov** [comment]
tested at 
- http://pulpito.ceph.com/kchai-2015-09-08_02:39:25-rados-wip-kefu-testing---basic-multi/
- http://pulpito.ceph.com/kchai-2015-09-08_10:19:56-rados-wip-kefu-testing---basic-multi/
- http://pulpito.ceph.com/kchai-2015-09-08_18:05:34-rados-wip-kefu-testing---basic-multi/

**Pull request merged**
