### PR TITLE
mgr/dashboard_v2: Add toggle able columns

### PR DESCRIPTION
**Pull request by Devp00l**
It's now possible to toggle columns on and off in the data table.

Signed-off-by: Stephan Müller <smueller@suse.com>

### CODE REVIEW

**Comment by rjfd** [comment]
jenkins retest this please

**Comment by votdev** [comment]
Are there plans to store the settings on client side (e.g. cookie or local storage)?

**Comment by Devp00l** [comment]
@votdev Yes and it's already done but it's depends on this PR and the table search PR, but I will create the  WIP PR of it today.

**Comment by Devp00l** [comment]
@rjfd Added some missing type declarations as requested by you in the search improvement PR

**Pull request merged**
