### PR TITLE
rgw: fix Content-Range header in response for ranged GET on Swift's DLO

### PR DESCRIPTION
**Pull request by rzarzynski**

### CODE REVIEW

**Comment by rzarzynski** [comment]
@yehudasa rebased to ```master```.

**Comment by zaitcev** [comment]
Looks okay, except I'm not entirely sure about ofs and if everything is all right with prefetch.

**Comment by liewegas** [comment]
@rzarzynski needs rebase.  is this otherwise still ready for review/merge?

**Comment by rzarzynski** [comment]
@liewegas the commits have been merged with PR #6643. I've forgotten to close this one. :-( Sorry.

**Comment by liewegas** [comment]
no problem, thanks.  mind taking a quick look at other PRs you have open 
to see if others should be closed?  thanks!

**Pull request closed without merging**
