### PR TITLE
os/bluestore: fix bitmap allocator issues

### PR DESCRIPTION
**Pull request by ifed01**
Fixes: https://tracker.ceph.com/issues/38760
Fixes: https://tracker.ceph.com/issues/38761

Signed-off-by: Igor Fedotov <ifedotov@suse.com>

- [x] References tracker ticket
- [ ] Updates documentation if necessary
- [x] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by liewegas** [comment]
Is there an open ticket for this?

**Comment by ifed01** [comment]
> Is there an open ticket for this?

@liewegas - no. Do you want me to create one?

**Comment by markhpc** [comment]
In the future it would be really helpful to have a short description of what the PR does rather than having to dig through the code to find out. :D

**Comment by liewegas** [comment]
> > Is there an open ticket for this?
> 
> @liewegas - no. Do you want me to create one?

yes please, so we can ensure it gets backported

**Comment by ifed01** [comment]
@liewegas, @markhpc - tickets created and referenced

**Comment by liewegas** [comment]
```
2019-03-19T22:52:44.441 INFO:teuthology.orchestra.run.smithi070.stdout:[ RUN      ] ObjectStore/StoreTest.allocateBlueFSTest/2
2019-03-19T22:52:46.018 INFO:teuthology.orchestra.run.smithi070.stderr:/home/jenkins-build/build/workspace/ceph-dev-new-build/ARCH/x86_64/AVAILABLE_ARCH/x86_64/AVAILABLE_DIST/centos7/DIST/centos7/MACHINE_SIZE/huge/release/14.2.0-87-gc1d40be/rpm/el7/BUILD/ceph-14.2
.0-87-gc1d40be/src/include/interval_set.h: In function 'void interval_set<T, Map>::insert(T, T, T*, T*) [with T = long unsigned int; Map = std::map<long unsigned int, long unsigned int>]' thread 7f9a12b92000 time 2019-03-19 22:52:46.061658
2019-03-19T22:52:46.018 INFO:teuthology.orchestra.run.smithi070.stderr:/home/jenkins-build/build/workspace/ceph-dev-new-build/ARCH/x86_64/AVAILABLE_ARCH/x86_64/AVAILABLE_DIST/centos7/DIST/centos7/MACHINE_SIZE/huge/release/14.2.0-87-gc1d40be/rpm/el7/BUILD/ceph-14.2
.0-87-gc1d40be/src/include/interval_set.h: 447: FAILED ceph_assert(len > 0)
2019-03-19T22:52:46.019 INFO:teuthology.orchestra.run.smithi070.stderr: ceph version 14.2.0-87-gc1d40be (c1d40be576032dba3d092395d34afab71b312325) nautilus (stable)
2019-03-19T22:52:46.020 INFO:teuthology.orchestra.run.smithi070.stderr: 1: (ceph::__ceph_assert_fail(char const*, char const*, int, char const*)+0x14a) [0x7f9a07c9f326]
2019-03-19T22:52:46.020 INFO:teuthology.orchestra.run.smithi070.stderr: 2: (ceph::__ceph_assertf_fail(char const*, char const*, int, char const*, char const*, ...)+0) [0x7f9a07c9f4f4]
2019-03-19T22:52:46.020 INFO:teuthology.orchestra.run.smithi070.stderr: 3: (Allocator::release(std::vector<bluestore_pextent_t, mempool::pool_allocator<(mempool::pool_index_t)4, bluestore_pextent_t> > const&)+0x3f0) [0x55769169fd50]
2019-03-19T22:52:46.020 INFO:teuthology.orchestra.run.smithi070.stderr: 4: (BlueStore::allocate_bluefs_freespace(unsigned long, unsigned long, std::vector<bluestore_pextent_t, mempool::pool_allocator<(mempool::pool_index_t)4, bluestore_pextent_t> >*)+0x3e7) [0x557
6915a1097]
2019-03-19T22:52:46.020 INFO:teuthology.orchestra.run.smithi070.stderr: 5: (StoreTest_allocateBlueFSTest_Test::TestBody()+0x21d) [0x5576913bf89d]
2019-03-19T22:52:46.021 INFO:teuthology.orchestra.run.smithi070.stderr: 6: (void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*)+0x77) [0x55769172c127]
2019-03-19T22:52:46.021 INFO:teuthology.orchestra.run.smithi070.stderr: 7: (testing::Test::Run()+0xba) [0x557691722a7a]
2019-03-19T22:52:46.021 INFO:teuthology.orchestra.run.smithi070.stderr: 8: (testing::TestInfo::Run()+0xac) [0x557691722b5c]
2019-03-19T22:52:46.021 INFO:teuthology.orchestra.run.smithi070.stderr: 9: (testing::TestCase::Run()+0xb5) [0x557691722c95]
2019-03-19T22:52:46.021 INFO:teuthology.orchestra.run.smithi070.stderr: 10: (testing::internal::UnitTestImpl::RunAllTests()+0x468) [0x557691723188]
2019-03-19T22:52:46.021 INFO:teuthology.orchestra.run.smithi070.stderr: 11: (bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char cons
t*)+0x77) [0x55769172c617]
2019-03-19T22:52:46.021 INFO:teuthology.orchestra.run.smithi070.stderr: 12: (testing::UnitTest::Run()+0x60) [0x557691723310]
2019-03-19T22:52:46.022 INFO:teuthology.orchestra.run.smithi070.stderr: 13: (main()+0x934) [0x5576912d8354]
2019-03-19T22:52:46.022 INFO:teuthology.orchestra.run.smithi070.stderr: 14: (__libc_start_main()+0xf5) [0x7f9a053c63d5]
2019-03-19T22:52:46.022 INFO:teuthology.orchestra.run.smithi070.stderr: 15: (()+0x2cb850) [0x5576913bb850]
2019-03-19T22:52:46.022 INFO:teuthology.orchestra.run.smithi070.stderr:*** Caught signal (Aborted) **
2019-03-19T22:52:46.022 INFO:teuthology.orchestra.run.smithi070.stderr: in thread 7f9a12b92000 thread_name:ceph_test_objec
2019-03-19T22:52:46.022 INFO:teuthology.orchestra.run.smithi070.stderr: ceph version 14.2.0-87-gc1d40be (c1d40be576032dba3d092395d34afab71b312325) nautilus (stable)
2019-03-19T22:52:46.023 INFO:teuthology.orchestra.run.smithi070.stderr: 1: (()+0xf5d0) [0x7f9a1278b5d0]
2019-03-19T22:52:46.023 INFO:teuthology.orchestra.run.smithi070.stderr: 2: (gsignal()+0x37) [0x7f9a053da207]
```
/a/sage-2019-03-19_18:36:56-rados-wip-sage3-testing-2019-03-19-0529-distro-basic-smithi/3747574

**Comment by ifed01** [comment]
@liewegas - fixed, another issue with 32bit wrapping

**Pull request merged**
