### PR TITLE
doc: enable Read the Docs

### PR DESCRIPTION
**Pull request by tchaikov**
## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by tchaikov** [comment]
see https://ceph.readthedocs.io/en/wip-rtd/

**Comment by tchaikov** [comment]
jenkins render docs

**Comment by tchaikov** [comment]
jenkins render docs

**Comment by tchaikov** [comment]
jenkins render docs

**Comment by LenzGr** [comment]
Very cool, thanks for looking into this!

**Comment by tchaikov** [comment]
jenkins test make check

**Pull request merged**
