### PR TITLE
doc/dev: Dashboard translations release update

### PR DESCRIPTION
**Pull request by s0nea**
Add a note on how to add a new release resource to transifex.

Signed-off-by: Tatjana Dehler <tdehler@suse.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by aaryanporwal** [comment]
jenkins test dashboard

**Comment by aaryanporwal** [comment]
jenkins test dashboard

**Review by nizamial09 — APPROVED** [review]

**Comment by nizamial09** [comment]
jenkins test dashboard

**Review by epuertat — APPROVED** [review]
And thank you very much for updating docs!

**Pull request merged**
