### PR TITLE
 tools/cephfs: make 'cephfs-data-scan scan_links' reconstruct snaptable

### PR DESCRIPTION
**Pull request by ukernel**
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by ukernel** [comment]
QA and Release note added

**Comment by batrick** [comment]
Test fails: /ceph/teuthology-archive/pdonnell-2018-12-13_01:15:37-fs-wip-pdonnell-testing-20181212.231100-distro-basic-smithi/3334850/teuthology.log

**Comment by ukernel** [comment]
Fixed (add 10 seconds wait,  to let mds update removed snaps in osdmap)

**Comment by batrick** [comment]
needs rebase

**Pull request merged**
