### PR TITLE
DNM: jewel: rgw: wip swift info

### PR DESCRIPTION
**Pull request by mattbenjamin**
http://tracker.ceph.com/issues/17208
http://tracker.ceph.com/issues/18526

Pulls Swift /info URI support into Jewel

### CODE REVIEW

**Comment by cbodley** [comment]
looks good. it probably needs a tracker ticket so the backport team knows what to do with it? there's one for the rgw_swift_url_prefix part at http://tracker.ceph.com/issues/17208, but it never went through because of merge conflicts

**Comment by mattbenjamin** [comment]
@cbodley ok, will fix tracker

**Comment by mattbenjamin** [comment]
@cbodley ok, updated 17208 and added 18526

**Comment by rzarzynski** [comment]
@mattbenjamin, @cbodley: I guess that at least some parts of this backport are covered with https://github.com/ceph/ceph/pull/11497.

**Comment by smithfarm** [comment]
#11497 was just merged, closing this one.

**Pull request closed without merging**
