### PR TITLE
mgr/dashboard: Language dropdown box is partly hidden on login page

### PR DESCRIPTION
**Pull request by votdev**
When clicking on the language dropdown combobox on the login page, the menu is partly hidden because it is partly rendered out of the visible area. Additionally the scrollbars are displayed.

Before:
screenshot

After:
Bildschirmfoto vom 2022-03-16 16-54-33

Fixes: https://tracker.ceph.com/issues/54591

Signed-off-by: Volker Theile <vtheile@suse.com>

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [x] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by votdev** [comment]
jenkins test dashboard

**Comment by votdev** [comment]
jenkins test dashboard

**Comment by votdev** [comment]
jenkins test dashboard

**Comment by votdev** [comment]
Is there any chance to get rid of those unit tests that are using this proprietary applitools tool? Why removing:

- If tests fail, the reason can not be seen by every Dashboard developer. An account is required
- These tests always fail IMO
- Without an account it is impossible to fix the PR

If we stay on these tools, someone with an account at applitools.com must fix the PR issues.

**Comment by epuertat** [comment]
> Is there any chance to get rid of those unit tests that are using this proprietary applitools tool? Why removing:

Sure. What visual regression testing tool you would suggest instead?

> * If tests fail, the reason can not be seen by every Dashboard developer. An account is required
> * Without an account it is impossible to fix the PR

I just sent you an invite to the Applitools web.

> * These tests always fail IMO

These failures are due to breaking changes in browsers (Chrome 99.0 and Firefox 98.0) and they need to be manually inspected and approved.

> * An OSS project like Ceph and proprietary tools do not match

You're writing this in Github, which is a propietary tool that requires you to create an account. Same applies for Transifex, Cypress, etc.

> If we stay on these tools, someone with an account at applitools.com must fix the PR issues.

That's what's happening, but we don't have a 24/7 team to fix test issues.

**Comment by epuertat** [comment]
jenkins test dashboard

**Review by epuertat — APPROVED** [review]

**Review by nizamial09 — APPROVED** [review]

**Comment by votdev** [comment]
jenkins test dashboard

**Comment by votdev** [comment]
> > Is there any chance to get rid of those unit tests that are using this proprietary applitools tool? Why removing:
> 
> Sure. What visual regression testing tool you would suggest instead?

I have none to suggest. But i'm asking myself whether they are really needed. According to my feeling they make more troubles than they help.

> 
> > * If tests fail, the reason can not be seen by every Dashboard developer. An account is required
> > * Without an account it is impossible to fix the PR
> 
> I just sent you an invite to the Applitools web.

Thanks

> 
> > * These tests always fail IMO
> 
> These failures are due to breaking changes in browsers (Chrome 99.0 and Firefox 98.0) and they need to be manually inspected and approved.
> 
> > * An OSS project like Ceph and proprietary tools do not match
> 
> You're writing this in Github, which is a propietary tool that requires you to create an account. Same applies for Transifex, Cypress, etc.

I think there is a difference. It's my own choice to create an GitHub or Transifex account to participate on the project. But i am forced to create an account at Applitools if there are problems with a PR, otherwise i'm not able to check what happens and the PR will not get merged. The sad thing is when if comes out that the code of the PR is not responsible for the failure of the Applitools tests. It is really intransparent process. IMO a PR should be merged even if there are Applitools test failures.

> > If we stay on these tools, someone with an account at applitools.com must fix the PR issues.
> 
> That's what's happening, but we don't have a 24/7 team to fix test issues.

As said above, in this case Applitools failures should not block PRs to be merged.

**Comment by votdev** [comment]
jenkins test dashboard

**Comment by epuertat** [comment]
@votdev applitools tests are not blocking any merging (not "required" by Github), we just need to ensure that the failures are unrelated.

**Pull request merged**
