### PR TITLE
os/bluestore: more verbose debug output on leaked shared blobs

### PR DESCRIPTION
**Pull request by liewegas**
See http://tracker.ceph.com/issues/22039

Signed-off-by: Sage Weil <sage@redhat.com>

### CODE REVIEW

**Comment by liewegas** [comment]
I think we can't because it keeps segfaulting on that line; want to avoid any dereference first to get a peek at the pointer value.

**Comment by batrick** [comment]
http://pulpito.ceph.com/pdonnell-2017-11-06_22:14:57-fs-wip-pdonnell-testing-20171106.200337-testing-basic-smithi/

**Comment by batrick** [comment]
http://tracker.ceph.com/issues/22039#note-5

**Comment by ifed01** [comment]
@liewegas most probably it will print nref value on invalid object as well - as you can see from the crash dump it segfaults in operator<<(std::ostream&, bluestore_extent_ref_map_t const&) hence previous stuff output  (e.g. bluestore_shared_blob_t::sbid) is supposed to be accessed/printed OK. So IMO makes sense to try...
BTW SharedBlob output operator isn't that verbose as well - nref, coll, bc are omitted. Perhaps worth to add...

**Pull request closed without merging**
