### PR TITLE
nautilus: mgr/dashboard: internationalization support with AOT enabled 

### PR DESCRIPTION
**Pull request by rjfd**
backport tracker: https://tracker.ceph.com/issues/42283

---

backport of https://github.com/ceph/ceph/pull/30694
parent tracker: https://tracker.ceph.com/issues/41988

this backport was staged using https://github.com/ceph/ceph/blob/master/src/script/ceph-backport.sh

### CODE REVIEW

**Comment by smithfarm** [comment]
@rjfd You skipped `mgr/dashboard: Remove support for older browsers` intentionally?

**Comment by rjfd** [comment]
@smithfarm yes. That change is to be only in octopus

**Comment by rjfd** [comment]
@smithfarm the backport is ready from my end

**Comment by smithfarm** [comment]
This backport is ready. Reviewers, please review.

**Comment by callithea** [comment]
QA run was successful: http://pulpito.ceph.com/laura-2019-11-11_11:54:21-rados:mgr-wip-laura-nautilus-dashboard-batch-2-distro-basic-mira/

**Comment by yuriw** [comment]
[wip-yuri3-testing-2019-11-18-2140-nautilus](https://trello.com/c/Ij7gxvpz/768-wip-yuri3-testing-2019-11-18-2140-nautilus)

**Comment by yuriw** [comment]
[wip-yuri3-testing-2019-11-18-2140-nautilus](https://trello.com/c/Ij7gxvpz/768-wip-yuri3-testing-2019-11-18-2140-nautilus)

**Pull request merged**
