### PR TITLE
mgr/dashboard: avoid using document.write()

### PR DESCRIPTION
**Pull request by avanthakkar**
Fixes: https://tracker.ceph.com/issues/49220
Signed-off-by: Avan Thakkar <athakkar@redhat.com>

## Checklist
- [x] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Review by epuertat — COMMENTED** [review]
I just tried with an `ng new` command and this is what it generates (Angular 10): 
```html
<!doctype html>                                                                                                        
<html lang="en">                                                                                     
<head>                                                                                               
  <meta charset="utf-8">                                                                             
  <title>Ceph</title>                                                                                
  <base href="/">                                                                                    
                                                                                                     
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="icon" type="image/x-icon" id="cdFavicon" href="favicon.ico"></head>                                                                                              
<body>                                                                                               
  <app-root></app-root>                                                                              
</body>                                                                                              
</html> 
```

Perhaps we can simply use this one without any extra magic?

**Review by epuertat — APPROVED** [review]
Are we sure this is really making any improvement over the document.write? If I understood it correctly, it basically rewrites the DOM too.

What about this approach?

https://medium.com/@anandshende1994/setting-base-href-dynamically-in-angular-6-b7fe824848cf

**Comment by avanthakkar** [comment]
> Are we sure this is really making any improvement over the document.write? If I understood it correctly, it basically rewrites the DOM too.
> 
Yeah I was not sure about the approach. But I'll look if I get something better.
> What about this approach?
> 
> https://medium.com/@anandshende1994/setting-base-href-dynamically-in-angular-6-b7fe824848cf
Will take a look. Thanks @epuertat

**Comment by epuertat** [comment]
> > Are we sure this is really making any improvement over the document.write? If I understood it correctly, it basically rewrites the DOM too.
> 
> Yeah I was not sure about the approach. But I'll look if I get something better.
> 
> > What about this approach?
> > [medium.com/@anandshende1994/setting-base-href-dynamically-in-angular-6-b7fe824848cf](https://medium.com/@anandshende1994/setting-base-href-dynamically-in-angular-6-b7fe824848cf)
> > Will take a look. Thanks @epuertat

[This one](https://www.xspdf.com/help/50627439.html) has even more examples (some of them don't require modifying anything in index.html and everything is on the JS side).

**Review by epuertat — APPROVED** [review]
I like it! Thanks @avanthakkar !

**Review by aaSharma14 — APPROVED** [review]

**Comment by MatthiasGrandl** [comment]
@epuertat @avanthakkar  Are you guys aware that this broke prefixed reverse proxies? In our case angular doesn't load and thus `<base href...` never gets updated and the assets never get loaded. We tried setting `mgr/dashboard/url_prefix` but that didn't help.


Could we maybe get a solution that doesn't rely on Angular like the old one?

**Comment by epuertat** [comment]
Hi @MatthiasGrandl, thanks for letting us know! Sorry to hear that. Recently we were also bringing support for `X-Forward-For` (and the like) headers just to deal with the complexities of reverse proxying.

Would you mind opening a [tracker issue](https://tracker.ceph.com/projects/dashboard/issues/new) with the following details?:
* Release where you reproduced this,
* Details on the reverse proxy config (proxy server, proxy mode: tcp/http/ssl termination, `X-Forward-for`/similar headers, etc.) and deployment.
* ceph-mgr logs and browser console error (if any). A screenshot of the failed request like the following would also be useful:
image

**Comment by MatthiasGrandl** [comment]
@epuertat well the first release that broke was the one with this change :) We are 100% sure that it still worked when it still made use of the `document.write` script. As you can see none of the assets get loaded, which is why the new solution won't be applied. 

image

**Comment by epuertat** [comment]
Thanks @MatthiasGrandl for the screenshot. This is the tracker issue: https://tracker.ceph.com/issues/50655.

**Pull request merged**
