### PR TITLE
jewel: crushtool --compile is create output despite of missing item

### PR DESCRIPTION
**Pull request by dachary**
http://tracker.ceph.com/issues/17334

### CODE REVIEW

**Comment by dachary** [comment]
<pre>
src/test/cli/crushtool/compile-decompile-recompile.t: failed
--- /home/jenkins-build/build/workspace/ceph-pull-requests/src/test/cli/crushtool/compile-decompile-recompile.t
+++ ./src/test/cli/crushtool/compile-decompile-recompile.t.err
@@ -11,5 +11,5 @@
   $ cmp nto.compiled nto.recompiled
 
   $ crushtool -c missing-bucket.crushmap.txt
-  in rule 'rule-bad' item 'root-404' not defined
-  [1]
+  input file missing-bucket.crushmap.txt not found
+  [254]
</pre>

**Comment by dachary** [comment]
It passed the rados (http://tracker.ceph.com/issues/17487#note-12), upgrade/jewel-x and upgrade/hammer-x (http://tracker.ceph.com/issues/17487#note-15) suites (except for two bugs that are, I believe, unrelated)

**Comment by dachary** [comment]
rebased

**Comment by dachary** [comment]
the missing-bucket.crushmap.txt file in jewel is not located at the same place, hence the error: figure out where it should be

**Comment by dachary** [comment]
jenkins test this please (logs are gone)

**Comment by dachary** [comment]
jenkins test this please (logs are gone)

**Comment by dachary** [comment]
genuine error at https://jenkins.ceph.com/job/ceph-pull-requests/14423/

**Comment by badone** [comment]
Test this please

**Comment by tchaikov** [comment]
@dachary might need to cherry-pick 404043980d7882f320f48fbaed4b18f31bb15eb7 also.

**Comment by dachary** [comment]
@badone @tchaikov cherry-picked the missing commit, rebased & repushed.

**Pull request merged**
