### PR TITLE
Wip kill warnings

### PR DESCRIPTION
**Pull request by tchaikov**

### CODE REVIEW

**Comment by tchaikov** [comment]
@badone i am fixing the warning we discussed just now here.

**Comment by liewegas** [comment]
needs rebase

**Comment by tchaikov** [comment]
with this change and https://github.com/ceph/civetweb/pull/8, we will be closer to a green build in master.

**Comment by tchaikov** [comment]
@liewegas rebased and added more fixes.

**Comment by tchaikov** [comment]
@cbodley could you help review the cmake bits in this pr?

as @yehudasa gave his blessing to the civetweb change at https://github.com/ceph/civetweb/pull/8, so i assume the submodule change is good.

**Comment by tchaikov** [comment]
i also pushed the branch to gitbuilder, see http://gitbuilder.sepia.ceph.com/gitbuilder-ceph-tarball-trusty-amd64-cmake/#origin/wip-kill-warnings . it's green now.

**Pull request merged**
