### PR TITLE
os/kstore: fix statfs problem and add vstart.sh support

### PR DESCRIPTION
**Pull request by yanghonggang**
Fixes: http://tracker.ceph.com/issues/23590
Signed-off-by: Yang Honggang <yanghonggang@umcloud.com>

### CODE REVIEW

**Comment by smithfarm** [comment]
@Lenz @rjfd Could you look at the test-mgr-dashboard failures in the make check run here?

**Comment by rjfd** [comment]
@smithfarm a recent dashboard PR introduced an random bug in the unit tests. I just created the PR #21290 to fix it.

**Comment by xiexingguo** [comment]
kstore is dead(deprecated by BlueStore) and not maintained any more.

**Comment by yanghonggang** [comment]
@xiexingguo  I can see the latest update is abd58ad0b9a by @liewegas in 2018.01. I know KeyValueStore is deprecated, are you sure kstore is also deprecated?

**Comment by gregsfortytwo** [comment]
It appears we still test kstore (eg https://github.com/ceph/ceph/blob/master/src/test/objectstore/store_test.cc#L5771) so we should keep taking improvements...

**Comment by tchaikov** [comment]
http://pulpito.ceph.com/kchai-2018-04-12_15:56:07-rados-wip-kefu-testing-2018-04-12-2211-distro-basic-mira/

failed tests are 

- tracked by http://tracker.ceph.com/issues/23699
- caused by #19117, #21188
- fixed by #21406

**Pull request merged**
