### PR TITLE
qa/suites/upgrade/octopus-x: bunch of fixes and cleanup

### PR DESCRIPTION
**Pull request by neha-ojha**
## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [x] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by neha-ojha** [comment]
https://pulpito.ceph.com/nojha-2021-12-01_02:48:34-upgrade:octopus-x-wip-yuriw-master-11.24.21-distro-basic-smithi/

**Comment by neha-ojha** [comment]
jenkins test make check

**Review by yuriw — APPROVED** [review]

**Review by sseshasa — APPROVED** [review]
LGTM

**Comment by neha-ojha** [comment]
> https://pulpito.ceph.com/nojha-2021-12-01_02:48:34-upgrade:octopus-x-wip-yuriw-master-11.24.21-distro-basic-smithi/

no related failures, ragweed failures are the same as the ones seen in baseline master http://pulpito.front.sepia.ceph.com/yuriw-2021-11-25_15:20:41-upgrade-wip-yuriw-master-11.24.21-distro-basic-smithi/

**Pull request merged**
