### PR TITLE
mgr/dashboard: Update bootstrap

### PR DESCRIPTION
**Pull request by tspmelo**
- Updated bootstrap to latest version.
- Replaced `awesome-bootstrap-checkbox` with the new bootstrap custom checkbox
- Replaced `ng2-toastr` with `ngx-toastr`
- Use `ng-bootstrap-form-validation`
- Use bootstrap `custom-select`

TODO:
- [x] Display green text/border/symbol when a form group is valid? [preview](https://github.com/ceph/ceph/pull/25188#issuecomment-500846579)
- [x] After https://github.com/ceph/ceph/pull/27277

Future work:
- [Use Bootstrap responsive font sizes](http://tracker.ceph.com/issues/38890)
- [Use more bootstrap variables](http://tracker.ceph.com/issues/38891)
- [Fix the border radius of buttons/inputs](http://tracker.ceph.com/issues/38953)

### CODE REVIEW

**Comment by tspmelo** [comment]
@votdev 
> Button is rendered incorrect.

For some reason Firefox is setting the background white, I have set it to transparent to fix it.

> The color of the info box should match the color of a selected table row.

I have change the color of the table selection to match the new color from bootstrap

> Input groups (class `input-group-append`) are not rendered correct.

Fixed.

> Badges are too small in my opinion.

Fixed.

> Text is not centered.

the text is centered inside the badge, but the bottom part of the `p` and other letter like it are ignore for this.

> Totally corrupted field labels.

Fixed.

> The buttons of the number input are not rendered correct.

It renders correctly on my machine, tested in chrome and firefox and both look as before.

**Comment by callithea** [comment]
Seems like the "Advanced..."-option in the bottom right corner is no longer highlighted as a link:
screenshot_20181127_165429

The "EC Overwrites"-text moved a bit up (compared to the checkbox):
screenshot_20181127_165151

The first field of the "Add erasure code profile"-dialog has moved a bit:
screenshot_20181127_165328

**Comment by tspmelo** [comment]
@callithea Done. Just missing the checkbox problem.

**Comment by callithea** [comment]
The toasty error message looks a bit strange (the icon on the left is missing and there are two closing buttons now)
screenshot_2018-11-28 ceph 2

compared to:
screenshot_2018-11-28 ceph 3

(Using Firefox 63.0.3)

**Comment by tspmelo** [comment]
@callithea ngx-toastr changed the error icon for the error.
Since we already use the same icon in the error-panel, I change the icon on the notification menu.

**Comment by callithea** [comment]
> @callithea ngx-toastr changed the error icon for the error.
> Since we already use the same icon in the error-panel, I change the icon on the notification menu.

I think I would remove the X-icon on the left completely then (because it's a bit confusing with the icon on the left and to have the "close"-action on the top right corner).

**Comment by tspmelo** [comment]
@alfonsomthd I tried to simplify whenever possible, so some styles changed a little bit.

> * Logs link has lost its link style so user won't notice it's a link.

Fixed.

> * Charts lost their vertical centering regarding card.

I added a little padding between the title and "body" of the card.

> * Card title font size has been diminished. Is it on purpose?

I removed the dynamic size to simplify code and use the bootstrap default. I think it is readable like this, but I can change back is necessary.

> * For 1366x768 Perf. and Capacity cards had -before this- 4 cards in a row (in order to allow charts to be a little bit bigger), now they're 5 in a row and the charts are little bit smaller. Is it on purpose?

I tested this in a 13" laptop and it looks good. Dashboard is more compact and I can get more info on screen.

**Comment by tspmelo** [comment]
@callithea 
> I think I would remove the X-icon on the left completely then (because it's a bit confusing with the icon on the left and to have the "close"-action on the top right corner).

I think it would be better to remove the close button, since it's not really necessary.
Removing the error/success icon would leave the notification a bit plain.

**Comment by tspmelo** [comment]
> The font size of drop-down menus and forms seems to be smaller in general.

Bootstrap now sets the font-size of elements based on the font-size define for the body. 
Since we have a smaller font-size, some elements are looking smaller.
I will have to see if its better to increase the global font-size or increase particular elements.

**Comment by LenzGr** [comment]
FWIW, [Bootstrap 4.2.1 has been released in the meanwhile](https://blog.getbootstrap.com/2018/12/21/bootstrap-4-2-1/). It probably makes sense to rebase against that version.

**Comment by tspmelo** [comment]
I think this PR is ready to be tested again.
I have rebased to the latest version of master and updated all files.
Since I think all previous comments have been addressed, I have hidden them all to clean the page a bit.

**Comment by alfonsomthd** [comment]
Before:

bootstrap3

Now:

bootstrap4

**Comment by alfonsomthd** [comment]
On iPad size, the Dashboard "Health Heart" icon is misplaced:

bootstrap4-heart

**Comment by tspmelo** [comment]
@alfonsomthd the whole menu is a bit buggy. I will work on it.

**Comment by epuertat** [comment]
> @alfonsomthd the whole menu is a bit buggy. I will work on it.

@tspmelo I'm currently refactoring the navbar menu (https://github.com/ceph/ceph/pull/27241) to generate it from a data structure (kind of `Routes` array). I've found that the heartbeat health widget is hard to keep with this approach (that'd mean having a menu entry with 'typescript/angular code' within), so I was thinking on moving that to a separate menu entry, or even moving it somewhere else in the navbar menu (close to the Ceph log? or to the top-right menu?).

**Comment by julienlim** [comment]
@alfonsomthd @epuertat In looking at the before and after screenshots, is it possible for us to get the logo above the navigation bar (so it's not part of the navigation bar) as it looks like a menu option.

The navigational menu looks rather buggy based on the above.  Any updates on how this is progressing?

**Comment by a2batic** [comment]
@julienlim @alfonsomthd @epuertat, It seems to have resolved now, navigation looks as before:-
Screenshot from 2019-04-03 12-01-23

**Comment by tspmelo** [comment]
@s0nea @callithea Fixed.

**Comment by tspmelo** [comment]
jenkins test dashboard please

**Comment by tspmelo** [comment]
jenkins test dashboard

**Comment by alfonsomthd** [comment]
@tspmelo tested locally with Firefox: LGTM
Just a minor observation: is the PG Status popover in 1440x900 (not common screen size)
is positioned to the left, overlapping with PGs per OSD:

bootstrap4-1440x900

**Comment by tspmelo** [comment]
@callithea I have removed all `btn-sm`. All buttons should be the same size now.

**Comment by votdev** [comment]
jenkins test submodules

**Comment by votdev** [comment]
jenkins retest this please

**Comment by tspmelo** [comment]
jenkins test dashboard

**Comment by tspmelo** [comment]
Preview of how a valid form looks like:
image
Should we keep it like this or remove the success validation colors?

**Comment by callithea** [comment]
> Preview of how a valid form looks like:
> image
> Should we keep it like this or remove the success validation colors?

I like the success validation colors! 
The only thing that bugs me is that the input field is not completely surrounded by the green line, not sure if that is something that can be fixed easily.

However, I'll retest your PR on my local system.

**Comment by rjfd** [comment]
@LenzGr let's merge this one soon?

**Comment by tspmelo** [comment]
@ricardoasmarques I have fixed the iSCSI and NFS problems.
I'm currently looking into the color annoyance, but if everything else if ready to merge I think we could fix this after the merge.

**Comment by tspmelo** [comment]
If possible please check if the recent pages that you modified are OK.

**Comment by tspmelo** [comment]
Fixed the checkbox colors.

**Comment by s0nea** [comment]
There is also an issue with the 'PG scrub options' form. I currently don't know what's the reason and I'm investigating it.

**Comment by LenzGr** [comment]
In forms that provide a context help icon, the related option is enabled just by clicking on the icon. I would expect this click to only open the help text, not to accidentally enable a checkbox.

Peek 2019-07-10 15-52

**Comment by s0nea** [comment]
> There is also an issue with the 'PG scrub options' form. I currently don't know what's the reason and I'm investigating it.

Meh https://github.com/ceph/ceph/blob/master/src/pybind/mgr/dashboard/frontend/src/app/shared/components/config-option/config-option.component.ts#L28 needs to be changed to `icons = Icons;`

**Comment by tspmelo** [comment]
@s0nea 
1. The icon is correct.
What I don't know is why chrome is changing the background color of the inputs.
Seems to be related to the autofill feature of chrome, but it doesn't happen in master. 
It also doesn't happen in firefox.

2. The icon is in the same position as in master. We can change it in the future, but is not related to this PR.

3. Yeah, it seems to happen in master also. It should be fixed in a separate PR to backport.

**Comment by tspmelo** [comment]
@LenzGr This also happens in master. It should be fixed in a separate PR.

**Comment by LenzGr** [comment]
When clicking "NFS" without having NFS Ganesha configured, the URL seen in the browser's address changes to "https://192.168.178.84:41456/#/nfs/501/Ganesha%20config%20location%20is%20not%20configured.%20Please%20set%20the%20GANESHA_RADOS_POOL_NAMESPACE%20setting." - not sure if that's intended?

Dito when clicking "Object Gateway" without having RGW configured:

"https://192.168.178.84:41456/#/rgw/501/No%20RGW%20credentials%20found,%20please%20consult%20the%20documentation%20on%20how%20to%20enable%20RGW%20for%20the%20dashboard."

**Comment by s0nea** [comment]
@
> 3. Yeah, it seems to happen in master also. It should be fixed in a separate PR to backport.

https://github.com/ceph/ceph/pull/28961

**Comment by tspmelo** [comment]
@s0nea  fixed the color problem in the login page

**Comment by callithea** [comment]
jenkins test dashboard

**Comment by LenzGr** [comment]
> LGTM. I think we should remove the success/green feedback from all input fields, but this can be done in a separate PR.

Agreed. @tspmelo can you please create a tracker issue about this and make sure this gets addressed? Thank you!

**Pull request merged**
