### PR TITLE
rpm: build-depends on "cunit-devel" for suse

### PR DESCRIPTION
**Pull request by tchaikov**

### CODE REVIEW

**Comment by smithfarm** [comment]
I don't know. . . I like having the distro-specific code blocks as self-contained wholes (IIRC we had if/else before and it was overly complicated and hard to figure out, especially when nesting of if/else blocks was involved). Unless there's a specific bug or problem with the current code, I don't see a compelling reason to refactor it. @b-ranto, @ktdreyer Your thoughts?

**Comment by tchaikov** [comment]
@smithfarm i think it'd be better to be explicit about mutual exclusive conditions. yes, this refactor commit is not for fixing a bug or a problem, it's just a cosmetic change. if none of you is interested in it, and believes it's bad. i am going to drop it.

**Comment by smithfarm** [comment]
@tchaikov I don't think the idea is bad, per se, and in a real programming language (with subroutines and indentation) your way would be cleaner. But given the limitations of RPM syntax, I've found it's better to keep the `if` blocks as small as possible. Still, I'm interested to hear what others think.

**Comment by smithfarm** [comment]
Any use of `%else` (including `%elseif`) can potentially give rise to confusion when `%if` blocks are nested (and we have had buggy spec file patches for this reason in the past), but if this patch makes the code easier to read for someone, I drop my objection.

**Comment by tchaikov** [comment]
@smithfarm okay, i am creating #19126, and assigning it to you. so once the OBS bug gets fixed, we can  test and merge it.

**Pull request merged**
