### PR TITLE
blk:BlockDevice.cc: use pending_aios instead of iovec size as ios num

### PR DESCRIPTION
**Pull request by weixinwei**
We have a ceph cluster(v 14.2.9) with 3 hosts, and there are 6 HDD OSDs on each host.
An EC pool was created with the default erasure-code-profile(k=2,m=1), and nothing changes in ceph.conf

After we use 'rados bench 30 write -b 2M -t 256 -p ecpool clean-up' to test the bandwidth, and use iostat to monitor disk utilization. Got the results: 30MB/s per disk.
With osd perf dump we found lots throttle-bluestore_throttle_bytes, it seems that BlueStore.cc::queue_transactions() was blocked in throttle_bytes.get(txc->cost);

Then we open blustore log and rerun the aboving test. In ceph-osd.log, appeared some logs "_txc_calc_cost 0x564c308b0b00 cost 173240518 (257 ios * 670000 + 1050518 bytes)". It seems the transactions packaged by ECBackend consist of many address discontinuity 4K IO, but these IO will be write once to kernel by pwritev.

Last, we simply set 'bluestore_throttle_bytes = 0', the bandwidth was up(80MB/s per disk).

So in _txc_calc_cost(), would it be more appropriate to calc potential cost in terms of pending_aio size instead of iovec size?

Signed-off-by: weixinwei <xinweiwei90@gmail.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by weixinwei** [comment]
@ifed01 ping?

**Comment by ifed01** [comment]
IMO this makes sense indeed. Currently we estimate transaction cost (number of ios specifically) based on number of input continuous memory(!) chunks - that's what summing over p.iov.size() actually results in. I.e. writing a single 8K buffer and 2x4K buffers to a continuous 8K disk extent have different cost. Which doesn't look valid.
Instead we should estimate the cost using individual disk writes (disk head seeks) - pending_aios.size() looks like a proper parameter then.
We might want to have some more robust benchmarking for this sort of chnges though...

**Comment by ifed01** [comment]
@markhpc , @jdurgin, @neha-ojha, @aclamk - what do you think?

**Comment by aclamk** [comment]
I agree that it does make sense. Definitely counting ios should rather refer to distinct regions on target device, not amount of memory region we operate from.

**Comment by tchaikov** [comment]
- https://pulpito.ceph.com/kchai-2020-07-13_15:11:10-rados-wip-kefu-testing-2020-07-13-2108-distro-basic-smithi/
- https://pulpito.ceph.com/kchai-2020-07-15_09:19:03-rados-wip-kefu-testing-2020-07-13-2108-distro-basic-smithi/

failures tracked / fixed by

- https://tracker.ceph.com/issues/46323
- #36091

**Comment by tchaikov** [comment]
@weixinwei if you want to have this change backported to v14 and/or v15, you might want to create a tracker ticket for it.

**Comment by weixinwei** [comment]
> @weixinwei if you want to have this change backported to v14 and/or v15, you might want to create a tracker ticket for it.

https://tracker.ceph.com/issues/46626

**Pull request merged**
