### PR TITLE
debian: start ceph-mon-all and ceph-osd-all on package install …

### PR DESCRIPTION
**Pull request by liewegas**

### CODE REVIEW

**Comment by ktdreyer** [comment]
Those "ceph-*-all" upstart targets are buggy and I can't wait to drop them (they easily get out of sync with the state of the daemons :(

That said, I guess this is ok with me

**Comment by liewegas** [comment]
:+1:

**Comment by dmick** [comment]
Do we *really* want to start services on installation?  I know traditionally we have done, but it's absolutely forbidden in Fedora, and the reason is justifiable: installing a package should not open ports, I should have to do that consciously.  I know a lot of Debian packages violate this, but I think it's a bad idea overall.

Stopping on package removal makes total sense.

**Comment by ktdreyer** [comment]
I think Debian policy is to start on install, right?

**Comment by dmick** [comment]
I misunderstood what was actually being started; *-all don't actually start daemons, they just need to themselves be in the right state so they can be stopped later

**Pull request merged**
