### PR TITLE
mimic: mgr/dashboard: Improve error message when backend is unreachable

### PR DESCRIPTION
**Pull request by Exotelis**
http://tracker.ceph.com/issues/36334

### CODE REVIEW

**Comment by ricardoasmarques** [comment]
Make check is failing because the `unit-test-helper` file was moved to a different path.

You have to fix the import manually or backport https://github.com/ceph/ceph/pull/22857 before this one.

**Comment by Exotelis** [comment]
> Make check is failing because the `unit-test-helper` file was moved to a different path.
> 
> You have to fix the import manually or backport #22857 before this one.

It seems, that the file does not exist in Mimic. I'm going to put the imports and providers in the beforeEach block. This should resolve the problem.

**Comment by LenzGr** [comment]
I wonder if it would make sense to backport #22857 in order to make it easier for frontend PRs to be backported without having to make changes. @ricardoasmarques or @tspmelo - what do you think?

**Comment by smithfarm** [comment]
@LenzGr I created http://tracker.ceph.com/issues/39941 to track the backport of #22857

**Pull request closed without merging**
