### PR TITLE
qa: whitelist "foo bar" for cluster/audit log test

### PR DESCRIPTION
**Pull request by tchaikov**
otherwise we have failures like

"2018-10-21 16:22:51.124328 mgr.x (mgr.5673) 6 : cluster [SEC] foo bar
security" in cluster log

see also: 95746ecc

Signed-off-by: Kefu Chai <kchai@redhat.com>

- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by liewegas** [comment]
mind retargetting this at nautilus branch?

**Comment by tchaikov** [comment]
i just pushed the change rebased on nautilus, but the PR failed to update. will re-push the branch or create another PR if necessary after github is back to normal.

**Comment by tchaikov** [comment]
retest this please

**Comment by tchaikov** [comment]
@liewegas turns out the commit based on which i was testing does not contain b833d35d9b83c5516d0ab6fc0d189af9c3594334. closing this PR.

**Pull request closed without merging**
