### PR TITLE
Update placement-groups.rst

### PR DESCRIPTION
**Pull request by RobertJansen1**
corrected some confusing numbers

### CODE REVIEW

**Comment by dachary** [comment]
Nice catch ! Could you please add a Signed-off-by: line to the commit message with git commit --amend ? You will find examples of such lines with git log. Thanks !

**Comment by RobertJansen1** [comment]
can i do this from the webinterface? i did not clone the code yet

**Comment by dachary** [comment]
@RobertJansen1 maybe you can by closing this pull request and opening a new one with the same patch. At that point, when asked for a commit comment you probably have the opportunity to add the Signed-off-by:

**Comment by dachary** [comment]
ah, just noticed you proposed the patch against the "last" branch. It should be against the branch "master". Changing the branch is only possible by re-creating a pull request: that's your opportunity to make it right ;-)

**Pull request closed without merging**
