### PR TITLE
mgr/telemetry: add leaderboard description and documentation

### PR DESCRIPTION
**Pull request by yaarith**
Users who are opted-in to telemetry can also opt-in to participating in a leaderboard in the telemetry public dashboards
(https://telemetry-public.ceph.com/).

Users can also add a description of the cluster to publicly appear in the leaderboard.

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [x] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [x] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by yaarith** [comment]
Docs preview:
https://ceph--50699.org.readthedocs.build/en/50699/mgr/telemetry/

**Review by ljflores — APPROVED** [review]
Built your branch and tried the config option. Seems to work well!

**Comment by ljflores** [comment]
Docs also look good.

**Review by zdover23 — APPROVED** [review]
@yaarith: I'm going to make a follow-up PR to put in the unselectable BASH prompt here. 

Approved.

**Comment by ljflores** [comment]
jenkins test api

**Comment by ljflores** [comment]
@yaarith the api failure actually seems related:

```
2023-03-28 17:57:22,830.830 INFO:__main__:FAIL: test_module_options (tasks.mgr.dashboard.test_mgr_module.MgrModuleTest)
2023-03-28 17:57:22,830.830 INFO:__main__:----------------------------------------------------------------------
2023-03-28 17:57:22,830.830 INFO:__main__:Traceback (most recent call last):
2023-03-28 17:57:22,830.830 INFO:__main__:  File "/home/jenkins-build/build/workspace/ceph-api/qa/tasks/mgr/dashboard/helper.py", line 483, in assertSchema
2023-03-28 17:57:22,830.830 INFO:__main__:    return _validate_json(data, schema)
2023-03-28 17:57:22,830.830 INFO:__main__:  File "/home/jenkins-build/build/workspace/ceph-api/qa/tasks/mgr/dashboard/helper.py", line 710, in _validate_json
2023-03-28 17:57:22,830.830 INFO:__main__:    raise _ValError('unknown keys: {}'.format(unknown_keys), path)
2023-03-28 17:57:22,830.830 INFO:__main__:tasks.mgr.dashboard.helper._ValError: In `input`: unknown keys: {'leaderboard_description'}
2023-03-28 17:57:22,830.830 INFO:__main__:
2023-03-28 17:57:22,830.830 INFO:__main__:During handling of the above exception, another exception occurred:
2023-03-28 17:57:22,830.830 INFO:__main__:
2023-03-28 17:57:22,830.830 INFO:__main__:Traceback (most recent call last):
2023-03-28 17:57:22,830.830 INFO:__main__:  File "/home/jenkins-build/build/workspace/ceph-api/qa/tasks/mgr/dashboard/test_mgr_module.py", line 121, in test_module_options
2023-03-28 17:57:22,830.830 INFO:__main__:    self.assertSchema(data, schema)
2023-03-28 17:57:22,830.830 INFO:__main__:  File "/home/jenkins-build/build/workspace/ceph-api/qa/tasks/mgr/dashboard/helper.py", line 485, in assertSchema
2023-03-28 17:57:22,830.830 INFO:__main__:    self.assertEqual(data, str(e))
```

**Comment by ljflores** [comment]
Removed "needs-qa" for now, but we can add it back after this is addressed. See what you think

**Comment by yaarith** [comment]
@ljflores thanks, looks like it needs to be added to the dashboard schema, will fix

**Comment by yaarith** [comment]
ceph API tests failure:

```
Python Unit-test Error

ERROR: setUpClass (tasks.mgr.dashboard.test_health.HealthTest)
⇒ Check for [already reported issues](https://tracker.ceph.com/search?q=ERROR:%20setUpClass%20%28tasks.mgr.dashboard.test_health.HealthTest%29&open_issues=1) on "ERROR: setUpClass (tasks.mgr.dashboard.test_health.HealthTest)" in Ceph Tracker...
... or open [a new issue](https://tracker.ceph.com/projects/dashboard/issues/new?issue[subject]=ERROR:%20setUpClass%20%28tasks.mgr.dashboard.test_health.HealthTest%29&issue[category_id]=212&issue[assigned_to_id]=&issue[description]=%3Cpre%3EPlease%20copy%20here%20the%20console%20error%20message%3C/pre%3E).


2023-03-30 15:58:36,597.597 INFO:__main__:----------------------------------------------------------------------
2023-03-30 15:58:36,597.597 INFO:__main__:
2023-03-30 15:58:36,597.597 INFO:__main__:Traceback (most recent call last):
2023-03-30 15:58:36,597.597 INFO:__main__:  File "/home/jenkins-build/build/workspace/ceph-api/qa/tasks/mgr/dashboard/helper.py", line 222, in setUpClass
2023-03-30 15:58:36,598.598 INFO:__main__:    cls.mds_cluster.mds_stop()
2023-03-30 15:58:36,598.598 INFO:__main__:  File "/home/jenkins-build/build/workspace/ceph-api/qa/tasks/cephfs/filesystem.py", line 346, in mds_stop
2023-03-30 15:58:36,598.598 INFO:__main__:    self._one_or_all(mds_id, lambda id_: self.mds_daemons[id_].stop())
2023-03-30 15:58:36,598.598 INFO:__main__:  File "/home/jenkins-build/build/workspace/ceph-api/qa/tasks/cephfs/filesystem.py", line 320, in _one_or_all
2023-03-30 15:58:36,598.598 INFO:__main__:    with parallel() as p:
2023-03-30 15:58:36,598.598 INFO:__main__:  File "/tmp/tmp.X9s9OsmABz/venv/lib/python3.10/site-packages/teuthology/parallel.py", line 84, in __exit__
2023-03-30 15:58:36,598.598 INFO:__main__:    for result in self:
2023-03-30 15:58:36,598.598 INFO:__main__:  File "/tmp/tmp.X9s9OsmABz/venv/lib/python3.10/site-packages/teuthology/parallel.py", line 98, in __next__
2023-03-30 15:58:36,598.598 INFO:__main__:    resurrect_traceback(result)
2023-03-30 15:58:36,598.598 INFO:__main__:  File "/tmp/tmp.X9s9OsmABz/venv/lib/python3.10/site-packages/teuthology/parallel.py", line 30, in resurrect_traceback
2023-03-30 15:58:36,599.599 INFO:__main__:    raise exc.exc_info[1]
2023-03-30 15:58:36,599.599 INFO:__main__:  File "/tmp/tmp.X9s9OsmABz/venv/lib/python3.10/site-packages/teuthology/parallel.py", line 23, in capture_traceback
2023-03-30 15:58:36,599.599 INFO:__main__:    return func(*args, **kwargs)
2023-03-30 15:58:36,599.599 INFO:__main__:  File "/home/jenkins-build/build/workspace/ceph-api/qa/tasks/cephfs/filesystem.py", line 346, in 
2023-03-30 15:58:36,599.599 INFO:__main__:    self._one_or_all(mds_id, lambda id_: self.mds_daemons[id_].stop())
2023-03-30 15:58:36,599.599 INFO:__main__:  File "/home/jenkins-build/build/workspace/ceph-api/build/../qa/tasks/vstart_runner.py", line 528, in stop
2023-03-30 15:58:36,599.599 INFO:__main__:    raise MaxWhileTries(
2023-03-30 15:58:36,599.599 INFO:__main__:teuthology.exceptions.MaxWhileTries: Timed out waiting for daemon mds.a
2023-03-30 15:58:36,599.599 INFO:__main__:
Cannot find device "ceph-brx"
2023-03-30 15:58:36,621.621 INFO:__main__:
2023-03-30 15:58:36,621.621 INFO:__main__:----------------------------------------------------------------------
2023-03-30 15:58:36,621.621 INFO:__main__:Ran 72 tests in 1210.857s
```

**Comment by yaarith** [comment]
jenkins test api

**Comment by yaarith** [comment]
jenkins test api

**Comment by ljflores** [comment]
jenkins test api

**Review by nizamial09 — APPROVED** [review]
@yaarith would it also makes sense to show this in the ceph dashboard wizard for telemetry? if so I can create a tracker for it and deal with it later..

**Comment by yaarith** [comment]
@nizamial09 yes, that would be great, thanks!

**Comment by nizamial09** [comment]
https://tracker.ceph.com/issues/59331, let me know which versions this is going to be backported and I'll update the tracker

**Comment by ljflores** [comment]
Rados suite review:
https://pulpito.ceph.com/?branch=wip-yuri4-testing-2023-03-31-1237
http://pulpito.front.sepia.ceph.com/?branch=wip-yuri4-testing-2023-04-07-1825

Failures, unrelated:
    1. https://tracker.ceph.com/issues/17945
    2. https://tracker.ceph.com/issues/59049
    3. https://tracker.ceph.com/issues/59196
    4. https://tracker.ceph.com/issues/56393
    5. https://tracker.ceph.com/issues/58946
    6. https://tracker.ceph.com/issues/49287
    7. https://tracker.ceph.com/issues/55347
    8. https://tracker.ceph.com/issues/59057
    9. https://tracker.ceph.com/issues/59380

Details:
    1. ceph_test_rados_api_tier: failed to decode hitset in HitSetWrite test - Ceph - RADOS
    2. WaitReplicas::react(const DigestUpdate&): Unexpected DigestUpdate event - Ceph - RADOS
    3. ceph_test_lazy_omap_stats segfault while waiting for active+clean - Ceph - RADOS
    4. failed to complete snap trimming before timeout - Ceph - RADOS
    5. cephadm: KeyError: 'osdspec_affinity' - Ceph - Orchestrator
    6. podman: setting cgroup config for procHooks process caused: Unit libpod-$hash.scope not found - Ceph - Orchestrator
    7. SELinux Denials during cephadm/workunits/test_cephadm - Ceph - Orchestrator
    8. rados/test_envlibrados_for_rocksdb.sh: No rule to make target 'rocksdb_env_librados_test' on centos 8 - Ceph - RADOS
    9. rados/singleton-nomsgr: test failing from "Health check failed: 1 full osd(s) (OSD_FULL)" and "Health check failed: 1 filesystem is offline (MDS_ALL_DOWN)" - Ceph - RADOS

**Comment by ljflores** [comment]
@yaarith looks good!

**Comment by yaarith** [comment]
@ljflores great! I'll merge and create the reef backport

**Comment by yaarith** [comment]
@nizamial09 thanks! We'll backport to reef for now, probably to quincy too

**Pull request merged**
