### PR TITLE
mon: periodic scrub

### PR DESCRIPTION
**Pull request by jecluis**
Every 3600 seconds after the last scrub finishes or the first election.  Could have made it a bit smarter, but given we expose 'ceph scrub' to the user we'll let the administrator schedule a manual scrub if they really want it at a specific time.

Also, scrub is now happening in chunks instead of performing a full store sweep.  This will maintain quorum while the scrub is in progress.

`Signed-off-by: Joao Eduardo Luis <joao@suse.de>`

### CODE REVIEW

**Comment by liewegas** [comment]
This looks pretty simple and reasonable to me.  We should modify the ceph.conf for teuthology to scrub every minute or two, maybe?

**Comment by liewegas** [comment]
Let's add an option teuthology.git with a short interval, merge that, and then add needs-qa so this gets fully exercised!

**Comment by jecluis** [comment]
woohoo! fully green monthrash run :D

**Comment by liewegas** [comment]
lgtm!

**Comment by jecluis** [comment]
awesome :)  I'll squash stuff together.

**Comment by jecluis** [comment]
squashed a few commits and edited a commit message.

**Pull request merged**
