### PR TITLE
mgr/cephadm: default to empty string nvmeof group name rather than requiring it

### PR DESCRIPTION
**Pull request by adk3798**
It was decided that since upgrades of nvmeof services with empty string names, which was chosen previously as the default, would cause the group name to be updated to a different value that we should instead stick with just defaulting to an empty string. 

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Comment by adk3798** [comment]
https://pulpito.ceph.com/adking-2024-09-05_04:20:41-orch:cephadm-wip-adk-testing-2024-09-04-1621-distro-default-smithi/

Failures:
- two instances of https://tracker.ceph.com/issues/67758, known issue
- 1 failure staggered upgrade with agent, known issue
- `Test failure: test_nfs_export_creation_without_cmount_path (tasks.cephfs.test_nfs.TestNFS)` caused by a PR in the run
- a couple SMB tests failing with either `in cluster log` stray daemon warnings or SELinux denials, known issue
- deploy raw OSD test timing out, known issue
- mds_upgrade_sequence and rgw-ingress tests timing out, known issue

Nothing to block merging the PRs in the run other than the NFS failure related one

**Comment by adk3798** [comment]
jenkins test api

**Review by phlogistonjohn — APPROVED** [review]
a tad bit confusing to follow the evolution of this, but code seems OK to me.

**Comment by adk3798** [comment]
https://pulpito.ceph.com/adking-2024-09-10_02:59:23-orch:cephadm-wip-adk-testing-2024-09-09-1904-distro-default-smithi/

Failures:
- stray daemon warning in smb test, known issue
- `Test failure: test_nfs_export_creation_without_cmount_path (tasks.cephfs.test_nfs.TestNFS)` caused by a PR in the run
- 2x agent on staggered upgrade failure, known issue
- deploy raw test timed out, known issue
- `test_rgw_multisite` test failed to generate token on realm bootstrap, somewhat new but not the first time I've seen it and it's unrelated to PRs in this run
- 4x mds_upgrade_sequence failures, known issue
- rgw-ingress tests timed out, known issue

Nothing to block merging PRs in the run other than the NFS failure related one

**Comment by adk3798** [comment]
jenkins test api

**Comment by adk3798** [comment]
jenkins test api

**Comment by adk3798** [comment]
https://pulpito.ceph.com/adking-2024-09-18_05:05:01-orch:cephadm-wip-adk-testing-2024-09-17-1139-distro-default-smithi/

Failures:
- nfs task failed due to PR in the run
- 3x mds_upgrade sequence failures, known issue
- 2x SMB test Selinux denials, known issue
- staggered upgrade with agent enabled failure, known issue
- 2x infra/teuth failures `Permission denied (publickey)`, `Failed to reconnect to smithi179`
- rgw-ingress tests timing out, known issue

Only PR in the run that can't be merged based off the results is the one causing the nfs test failure

**Comment by adk3798** [comment]
jenkins test api

**Pull request merged**
