### PR TITLE
src/script: Ignore files created by `run_mypy.sh`

### PR DESCRIPTION
**Pull request by p-na**
Signed-off-by: Patrick Nawracay <pnawracay@suse.com>

- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by sebastian-philipp** [comment]
I'd prefer to reduce the foot-print of run_mypy instead of adding this to .gitignore.

**Comment by p-na** [comment]
> I'd prefer to reduce the foot-print of run_mypy instead of adding this to .gitignore.

If it's about cleaning up, that sounds good to me, but that would increase the time to run the script, if run repeatedly, wouldn't it?

**Comment by sebastian-philipp** [comment]
> > I'd prefer to reduce the foot-print of run_mypy instead of adding this to .gitignore.
> 
> If it's about cleaning up, that sounds good to me, but that would increase the time to run the script, if run repeatedly, wouldn't it?

maybe we can `rm mypy.ini` and just print out warnings, instead of writing to `mypy_report.txt`

**Comment by sebastian-philipp** [comment]
Made the changes in #27118

**Pull request closed without merging**
