### PR TITLE
ceph-volume: rearrange api/lvm.py

### PR DESCRIPTION
**Pull request by rishabh-d-dave**
And allow `get_pv()` and `get_vg()` to accept list of PVs and VGs respectively
so that calling code can pass these methods the list if it has it already.

## Checklist
- [x] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`

</details>

### CODE REVIEW

**Comment by jan--f** [comment]
jenkins test ceph-volume all

**Comment by jan--f** [comment]
@rishabh-d-dave looks like you need to rebase this on top of master.

**Comment by rishabh-d-dave** [comment]
Yep, conflicts with my own patch.

**Comment by rishabh-d-dave** [comment]
Rebased the branch.

**Comment by rishabh-d-dave** [comment]
@jan--f 
Do we need tracker tickets?

**Comment by rishabh-d-dave** [comment]
jenkins test ceph-volume tox

**Comment by rishabh-d-dave** [comment]
jenkins test ceph-volume all

**Comment by rishabh-d-dave** [comment]
@jan--f Tests on CI passed.

**Comment by jan--f** [comment]
> @jan--f
> Do we need tracker tickets?

Either create a tracker ticket or create the backport PRs to mimic and nautilus yourself.

**Comment by rishabh-d-dave** [comment]
jenkins test ceph-volume tox

**Comment by rishabh-d-dave** [comment]
jenkins test ceph-volume all

**Comment by rishabh-d-dave** [comment]
jenkins test ceph-volume tox

**Comment by rishabh-d-dave** [comment]
@jan--f Tests on CI passed.

**Pull request merged**
