### PR TITLE
pacific: rgw_reshard: drop olh entries with empty name

### PR DESCRIPTION
**Pull request by dvanders**
backport tracker: https://tracker.ceph.com/issues/55250

---

backport of https://github.com/ceph/ceph/pull/45304
parent tracker: https://tracker.ceph.com/issues/54500

this backport was staged using ceph-backport.sh version 16.0.0.6848
find the latest version at https://github.com/ceph/ceph/blob/master/src/script/ceph-backport.sh

### CODE REVIEW

**Review by cbodley — APPROVED** [review]

**Comment by yuriw** [comment]
@dvanders Please sign the PR

**Comment by ljflores** [comment]
Rados suite results:
http://pulpito.front.sepia.ceph.com/?branch=wip-yuri-testing-2022-06-06-1014-pacific

Failures, unrelated:
    1. https://tracker.ceph.com/issues/54992
    2. https://tracker.ceph.com/issues/53939
    3. https://tracker.ceph.com/issues/54071
    4. https://tracker.ceph.com/issues/53501
    5. https://tracker.ceph.com/issues/52321
    6. https://tracker.ceph.com/issues/53855
    7. https://tracker.ceph.com/issues/55741
    8. https://tracker.ceph.com/issues/51234 -- pending Pacific backport

Details:
    1. cannot stat '/etc/containers/registries.conf': No such file or directory - Ceph - Orchstrator
    2. ceph-nfs-upgrade, pacific: Upgrade Paused due to UPGRADE_REDEPLOY_DAEMON: Upgrading daemon osd.0 on host smithi103 failed - Ceph - Orchestrator
    3. rados/cephadm/osds: Invalid command: missing required parameter hostname(<string>) - Ceph - Orchestrator
    4. Exception when running 'rook' task. - Ceph - Orchestrator
    5. qa/tasks/rook times out: 'check osd count' reached maximum tries (90) after waiting for 900 seconds - Ceph - Orchestrator
    6. rados/test.sh hangs while running LibRadosTwoPoolsPP.ManifestFlushDupCount - Ceph - RADOS
    7. cephadm/test_dashboard_e2e.sh: Unable to find element `cd-modal .custom-control-label` when testing on orchestrator/01-hosts.e2e-spec.ts - Ceph - Mgr - Dashboard
    8. LibRadosService.StatusFormat failed, Expected: (0) != (retry), actual: 0 vs 0 - Ceph - RADOS

**Comment by ljflores** [comment]
jenkins test signed

**Comment by ljflores** [comment]
jenkins test windows

**Pull request merged**
