### PR TITLE
tasks/cephadm: Update remote cephadm URL

### PR DESCRIPTION
**Pull request by zmc**
See https://github.com/ceph/ceph/commit/18fcfb022d19af1e69addf1729d4593272e4ac20

Signed-off-by: Zack Cerza <zack@redhat.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [x] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by zmc** [comment]
More specifically, [this is where the file was renamed](https://github.com/ceph/ceph/commit/18fcfb022d19af1e69addf1729d4593272e4ac20#diff-2bc083a616d69767b3cb29ad7910698521b38a2c7d078bc7f1401b76d07ef9fa)

**Comment by phlogistonjohn** [comment]
Hi, there. I'm not the original author of the patch but I was "leading" the "compile cephadm" effort for the last few months.  I would like to understand better if this caused any issues for you.
I don't think this change is what we want because the function in question "_fetch_cephadm_from_github" is designed to support teuthology tests that install using older versions of ceph where the ".py" extension is not present. In short, it's meant to fetch older versions (only).

Tests that execute with the current version of ceph/cephadm are expected to use the "compiled" cephadm code path. In the not too distant future, copying cephadm.py and treating it just like "cephadm" will no longer work because eventually that file will be broken up into multiple python source files. We're aware that no code path for using the compiled cephadm from older versions of ceph, but since that case doesn't exist at the moment we haven't tried solving it yet.

If you have teuthology test failures that you think are due to the change of cephadm from single source script to "compiled cephdm", please share them. Feel free to open a tracker as well if there's no "quick fix" and hand it off to the orch. team (if you wish).

**Comment by zmc** [comment]
I did hit what looked like a failure to download `cephadm` from github while doing some testing, but after looking at this function and its caller more closely, I don't understand why `_fetch_cephadm_from_github` would have been called at all. All of this happened inside containers which are now destroyed, of course. I'm going to close this now, and in the unlikely even that I hit something like this again I'll dig deeper and possibly reopen.

I'm glad to hear cephadm is being split up! I would be thrilled if we could make it pip-installable.

**Comment by phlogistonjohn** [comment]
> 
> I'm glad to hear cephadm is being split up! I would be thrilled if we could make it pip-installable.

It's come up in discussion before but not much serious thought has gone into that aspect. What is your use case? Would you also expect it to be available at pypi?

**Pull request closed without merging**
