### PR TITLE
pacific: rgw: do not permit locked object version removal

### PR DESCRIPTION
**Pull request by ifed01**
Fixes: https://tracker.ceph.com/issues/55766

Signed-off-by: Igor Fedotov <igor.fedotov@croit.io>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Review by mattbenjamin — COMMENTED** [review]
The reasoning in https://tracker.ceph.com/issues/55766 (last comment) seems cogent, in particular, wrt the Pacific code paths.  Suggest to add a brief remark on that to the commit message.

**Review by mattbenjamin — APPROVED** [review]
as above

**Comment by ifed01** [comment]
> thanks @ifed01! two requests:
> 
> * our normal backport process is to fix bugs on main, then cherry-pick the same commits to release branches. since this PR does not follow that normal process, could you please add a comment to the commit message describing why? essentially, that the bug was fixed on quincy/main as part of a larger change that we can't backport
> * since our testing didn't catch this regression, that implies that we're missing some important test coverage. can you please add one or more tests to https://github.com/ceph/s3-tests/ that fail without this fix?

Thanks @cbodley!

Commit message updated, will add a test case a bit later...

**Comment by ifed01** [comment]
> Commit message updated, will add a test case a bit later...

Please find one at:
https://github.com/ceph/s3-tests/pull/461

**Comment by ifed01** [comment]
@cbodley, @mattbenjamin - this patch has been updated a bit to pass s3-tests suite. Please see the rationale in the commit description.

**Comment by cbodley** [comment]
> Please see the rationale in the commit description.

understood, thanks

builds are pending at https://shaman.ceph.com/builds/ceph/pr-47041/, and i'll schedule the qa with- and without that s3test case

**Comment by ifed01** [comment]
@cbodley - any updates?

**Comment by cbodley** [comment]
not sure why, but i haven't been able to get packages to build successfully https://shaman.ceph.com/builds/ceph/pr-47041/

**Comment by ifed01** [comment]
> not sure why, but i haven't been able to get packages to build successfully https://shaman.ceph.com/builds/ceph/pr-47041/
hmm... failures look unrelated... So what's the plan then?

**Pull request merged**
