### PR TITLE
nautilus: mgr/dashboard: Unify the look of dashboard charts

### PR DESCRIPTION
**Pull request by tspmelo**
http://tracker.ceph.com/issues/39961

### CODE REVIEW

**Comment by smithfarm** [comment]
jenkins re-test this please

**Comment by tspmelo** [comment]
This should be merged after https://github.com/ceph/ceph/pull/28178, otherwise it will require modifications to the original commit.

**Comment by ricardoasmarques** [comment]
jenkins test make check

**Comment by tchaikov** [comment]
retest this please

**Comment by tspmelo** [comment]
jenkins retest this please

**Comment by yuriw** [comment]
[wip-yuri6-testing-2019-06-10-1956-nautilus](https://trello.com/c/QGfZaPf9/635-wip-yuri6-testing-2019-06-10-1956-nautilus)

**Pull request merged**
