### PR TITLE
osdmaptool: enhancements to --mark-in/out/up/down, output, and misc

### PR DESCRIPTION
**Pull request by huww98**
This PR first fixed some issues in osdmaptool.

Then improved the cmd arg parse (error handling, etc.)

Then added support for marking multiple OSD in/out/up/down.

Then a breaking change that replace `--save` with `--outfn <file>`

Finally, support for persistent OSD in/out/up/down changes.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [x] New feature (ticket optional)
  - [x] Doc update (no ticket needed)
  - [x] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [x] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by huww98** [comment]
jenkins test api

**Comment by huww98** [comment]
@alram @tchaikov Could you please help review this PR?

**Comment by tchaikov** [comment]
Will do this weekend.

**Comment by vumrao** [comment]
jenkins retest this please!

**Comment by tchaikov** [comment]
> Will do this weekend.

this PR fell through a crack in my table. will try to review it this week.

**Comment by vumrao** [comment]
> > Will do this weekend.
> 
> this PR fell through a crack in my table. will try to review it this week.

Thank you, Kefu.

**Pull request closed without merging**
