### PR TITLE
Ingress service: Fix HAProxy to listen on IPv4 and IPv6 

### PR DESCRIPTION
**Pull request by thegreenbear**
(My) Previous commit to make HAProxy listen on both IPv4 and IPv6 was buggy and generated a non-valid HAProxy config file.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [x] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

### CODE REVIEW

**Comment by thegreenbear** [comment]
Reference doc is there: https://www.haproxy.com/documentation/haproxy-configuration-manual/latest/#4.2-bind
Not necessarily obvious, but setting `[::]` makes HAProxy bind on interfaces for both IPv4 and IPv6.

**Review by adk3798 — APPROVED** [review]
We only have IPv4 in the sepia lab where we do tests currently, so integration testing won't catch IPv6 errors. Taking your word that this was working though.

**Comment by adk3798** [comment]
jenkins test api

**Comment by adk3798** [comment]
https://pulpito.ceph.com/adking-2024-06-28_04:58:18-orch:cephadm-wip-adk-testing-2024-06-27-0902-distro-default-smithi/

Failures all fell under

- cluster log failures (known issue, being cleaned up)
- mds_upgrade_Sequence (known issue)
- staggered upgrade with agent on (known issue)

Nothing to block merging

**Pull request merged**
