### PR TITLE
msg: fix format specifier for unsigned value id

### PR DESCRIPTION
**Pull request by atheism**
Signed-off-by: Weibing Zhang <zhangweibing@unitedstack.com>

### CODE REVIEW

**Comment by atheism** [comment]
jenkins, retest this please

**Comment by atheism** [comment]
jenkins, retest this please

**Comment by atheism** [comment]
jenkins, retest this please

**Comment by atheism** [comment]
@tchaikov How about this pr now? Is there anything wrong with the test?
Thanks

**Comment by tchaikov** [comment]
tested at http://pulpito.ceph.com/kchai-2016-10-09_12:58:06-rados-wip-kefu-testing---basic-mira/

failed tests are tracked at
- http://tracker.ceph.com/issues/16943
- http://tracker.ceph.com/issues/17540

**Pull request merged**
