### PR TITLE
ceph-volume lvm list 

### PR DESCRIPTION
**Pull request by alfredodeza**
List all devices associated with Ceph that have been prepared by `ceph-volume lvm`. This may include both physical and logical.

Resolves: https://bugzilla.redhat.com/show_bug.cgi?id=1491250

It also allows json formatting, and single device listing.

Sample output for full listing:

    $ ceph-volume lvm list
    
    
    ====== osd.1 =======
    
      [journal]    /dev/journals/journal1
    
          journal uuid              C65n7d-B1gy-cqX3-vZKY-ZoE0-IEYM-HnIJzs
          osd id                    1
          cluster fsid              ce454d91-d748-4751-a318-ff7f7aa18ffd
          type                      journal
          osd fsid                  661b24f8-e062-482b-8110-826ffe7f13fa
          data uuid                 SlEgHe-jX1H-QBQk-Sce0-RUls-8KlY-g8HgcZ
          journal device            /dev/journals/journal1
          data device               /dev/test_group/data-lv2
    
      [data]    /dev/test_group/data-lv2
    
          journal uuid              C65n7d-B1gy-cqX3-vZKY-ZoE0-IEYM-HnIJzs
          osd id                    1
          cluster fsid              ce454d91-d748-4751-a318-ff7f7aa18ffd
          type                      data
          osd fsid                  661b24f8-e062-482b-8110-826ffe7f13fa
          data uuid                 SlEgHe-jX1H-QBQk-Sce0-RUls-8KlY-g8HgcZ
          journal device            /dev/journals/journal1
          data device               /dev/test_group/data-lv2
    

Single listing (for lv):

    $ ceph-volume lvm list test_group/data-lv1
    
    
    ====== osd.0 =======
    
      [data]    /dev/test_group/data-lv1
    
          journal uuid              cd72bd28-002a-48da-bdf6-d5b993e84f3f
          osd id                    0
          cluster fsid              ce454d91-d748-4751-a318-ff7f7aa18ffd
          type                      data
          osd fsid                  943949f0-ce37-47ca-a33c-3413d46ee9ec
          data uuid                 TUpfel-Q5ZT-eFph-bdGW-SiNW-l0ag-f5kh00
          journal device            /dev/sdd1
          data device               /dev/test_group/data-lv1

Single listing for a device:

    $ ceph-volume lvm list /dev/sdd1
    
    
    ====== osd.0 =======
    
      [journal]    /dev/sdd1
    
          PARTUUID                  cd72bd28-002a-48da-bdf6-d5b993e84f3f

### CODE REVIEW

**Comment by alfredodeza** [comment]
jenkins render docs

**Comment by alfredodeza** [comment]
jenkins test ceph-volume tox

**Comment by andrewschoen** [comment]
jenkins render docs

**Comment by andrewschoen** [comment]
jenkins test ceph-volume tox

**Comment by andrewschoen** [comment]
jenkins test ceph-volume tox

**Comment by andrewschoen** [comment]
jenkins test docs

**Pull request merged**
