### PR TITLE
ceph-volume: drop `ceph-bluestore-tool` call in Device._parse()

### PR DESCRIPTION
**Pull request by guits**
disk.has_bluestore_label() does the same thing without a subprocess call.

Fixes: https://tracker.ceph.com/issues/56622

Signed-off-by: Guillaume Abrioux <gabrioux@redhat.com>

### CODE REVIEW

**Comment by guits** [comment]
jenkins test ceph-volume tox

**Comment by guits** [comment]
jenkins test ceph-volume tox

**Comment by guits** [comment]
jenkins test ceph-volume tox

**Comment by guits** [comment]
jenkins test ceph-volume tox

**Comment by guits** [comment]
jenkins test ceph-volume tox

**Comment by guits** [comment]
jenkins test ceph-volume tox

**Comment by guits** [comment]
jenkins test ceph-volume tox

**Comment by guits** [comment]
jenkins test ceph-volume tox

**Comment by guits** [comment]
jenkins test ceph-volume tox

**Comment by guits** [comment]
jenkins test ceph-volume tox

**Comment by guits** [comment]
jenkins test ceph-volume tox

**Comment by guits** [comment]
jenkins test ceph-volume tox

**Comment by guits** [comment]
jenkins test ceph-volume tox

**Comment by guits** [comment]
http://pulpito.front.sepia.ceph.com/gabrioux-2022-07-21_09:04:55-orch:cephadm-wip-guits-testing-2022-07-20-1940-distro-default-smithi/

**Comment by guits** [comment]
jenkins test api

**Comment by guits** [comment]
jenkins test windows

**Comment by guits** [comment]
jenkins test ceph-volume tox

**Comment by guits** [comment]
jenkins test ceph-volume tox

**Comment by guits** [comment]
jenkins test ceph-volume tox

**Comment by guits** [comment]
jenkins test ceph-volume tox

**Comment by guits** [comment]
http://pulpito.front.sepia.ceph.com/gabrioux-2022-07-26_06:00:34-orch:cephadm-wip-guits-testing-2022-07-25-2017-distro-default-smithi/

**Comment by guits** [comment]
jenkins test ceph-volume tox

**Comment by guits** [comment]
jenkins test ceph-volume tox

**Comment by guits** [comment]
http://pulpito.front.sepia.ceph.com/gabrioux-2022-07-26_06:00:34-orch:cephadm-wip-guits-testing-2022-07-25-2017-distro-default-smithi/

**Comment by guits** [comment]
jenkins test ceph-volume tox

**Comment by guits** [comment]
jenkins test windows

**Comment by guits** [comment]
jenkins test ceph-volume tox

**Comment by guits** [comment]
jenkins test api

**Comment by guits** [comment]
https://pulpito.ceph.com/gabrioux-2022-07-26_18:26:57-orch:cephadm-wip-guits-testing-2022-07-26-1518-distro-default-smithi/
https://pulpito.ceph.com/gabrioux-2022-07-26_20:05:56-orch:cephadm-wip-guits-testing-2022-07-26-1518-distro-default-smithi/

**Review by adk3798 — APPROVED** [review]

**Comment by guits** [comment]
jenkins test ceph-volume tox

**Comment by guits** [comment]
jenkins test windows

**Comment by guits** [comment]
jenkins test windows

**Comment by guits** [comment]
http://pulpito.front.sepia.ceph.com/gabrioux-2022-07-27_11:10:25-orch:cephadm-wip-guits-testing-2022-07-27-0800-distro-default-smithi/

**Pull request merged**
