### PR TITLE
osd: heartbeat peers need to be updated when a new OSD added into an existed cluster

### PR DESCRIPTION
**Pull request by liupan1111**
The case is: 
There is a storage node which has two osds. nearly one min later, a new OSD joins in. Monitor sees it as "up", and no heatbeat from existing two osds to this new one. When we kill this new OSD, no osd reports this to monitor, so monitor still treats it as "up". Then, if the user invokes fio, io may hang there.

### CODE REVIEW

**Comment by liupan1111** [comment]
@liewegas @tchaikov , please help take a look.

**Comment by liewegas** [comment]
Note that this only happens if the new OSD gets no PGs mapped to it, which is pretty rare. Still, let's fix it!

**Comment by yuyuyu101** [comment]
@liewegas yes, I'm confusing why io will hang if no pg mapping

**Comment by yuyuyu101** [comment]
the problem solved here is fixing incorrect "up" status in mon I think. @liupan1111 is it right?

**Comment by liupan1111** [comment]
@yuyuyu101, at this case when a new osd joins, and then be killed, monitor still treat it as up, So client will still take this osd in its computing scope.

**Comment by liewegas** [comment]
We add osdid +1 and -1 to the peer set so that we ensure we always ping all osds and the graph is fully connected. See maybe_update_heartbeat_peers()

**Comment by yuriw** [comment]
http://pulpito.ceph.com/yuriw-2016-11-22_16:38:08-rados-wip-yuri-testing2_2016_11_21-distro-basic-smithi/

http://pulpito.ceph.com/yuriw-2016-11-22_16:38:08-rados-wip-yuri-testing2_2016_11_21-distro-basic-smithi/

**Comment by yuriw** [comment]
@liupan1111 - I see no tracker ticket reference, it'd be useful if you can link it.

**Comment by liupan1111** [comment]
@yuriw , done. Thank you for reminding.

**Pull request merged**
