### PR TITLE
pybind: fix open flags calculation

### PR DESCRIPTION
**Pull request by ukernel**
(O_WRONLY | O_RDWR) is not vaiid open flags

Fixes: http://tracker.ceph.com/issues/19890
Signed-off-by: "Yan, Zheng" <zyan@redhat.com>

### CODE REVIEW

**Comment by batrick** [comment]
@ukernel I'll add this to my integration branch.

**Comment by jcsp** [comment]
Do we know which code change caused this failure?  It seems like we're working around it at the python layer, perhaps we should be fixing the underlying code to tolerate (O_WRONLY | O_RDWR) the way I guess it used to?

**Comment by ukernel** [comment]
commit "fs: normalize file open flags internally used by cephfs" reveals this bug. linux kernel does not tolerate (O_WRONLY | O_RDWR), I don't think we should do

**Comment by ukernel** [comment]
different bug reveals http://pulpito.ceph.com/jspray-2017-05-11_14:40:13-fs-wip-jcsp-testing-20170511-distro-basic-smithi/1124353/. Fixed by the second commit

**Comment by ukernel** [comment]
test passed http://pulpito.ceph.com/zyan-2017-05-16_07:55:36-fs-wip-zyan-integration-testing-basic-mira/

**Pull request merged**
