### PR TITLE
tests: --osd-scrub-load-threshold=2000 for more consistency

### PR DESCRIPTION
**Pull request by dachary**
In a test environment, consistency is more important than
performances. Effectively disable the test that would postpone a scrub
depending on the load average. It is assumed that a machine with a load
average higher than 2000 won't be useable anyway.

http://tracker.ceph.com/issues/13986 Fixes: #13986

Signed-off-by: Loic Dachary <loic@dachary.org>

### CODE REVIEW

**Comment by dachary** [comment]
running 
<pre>
while : ; do echo -n . ; test/osd/osd-scrub-snaps.sh > test.out 2>&1 || break ; done
</pre>
and some workload to stress the machine (high load average).

**Comment by dachary** [comment]
failed again

**Comment by dachary** [comment]
<pre>
2015-12-08 21:20:55.496277 7f6c0b776700 20 osd.0 19 can_inc_scrubs_pending0 -> 1 (max 1, active 0)
2015-12-08 21:20:55.496282 7f6c0b776700 20 osd.0 19 scrub_time_permit should run between 0 - 24 now 21 = yes
2015-12-08 21:20:55.496311 7f6c0b776700 20 osd.0 19 scrub_load_below_threshold loadavg 20.32 < max 2000 = yes
2015-12-08 21:20:55.496333 7f6c0b776700 20 osd.0 19 sched_scrub load_is_low=1
2015-12-08 21:20:55.496335 7f6c0b776700 10 osd.0 19 sched_scrub 1.0 schedued at 2015-12-10 01:21:45.152250 > 2015-12-08 21:20:55.496280
2015-12-08 21:20:55.496343 7f6c0b776700 20 osd.0 19 sched_scrub done
</pre>

**Comment by XinzeChi** [comment]
@dachary , Last evening,  I run test/osd/osd-scrub-snaps.sh about 700 times, all of them return ok.

**Comment by dachary** [comment]
will re-open after doing more tests

**Pull request closed without merging**
