### PR TITLE
octopus: rgw/notification: support GetTopicAttributes API

### PR DESCRIPTION
**Pull request by yuvalif**
backport tracker: https://tracker.ceph.com/issues/48462

---

fixes: https://tracker.ceph.com/issues/46296

Signed-off-by: Yuval Lifshitz <ylifshit@redhat.com>
(cherry picked from commit 3906884aa66b7b6c976d6165cc3b5dfaa8f754c4)

Conflicts:
	PendingReleaseNotes
	src/rgw/rgw_rest_pubsub.cc
        manually removed reference to "persistent notifications"

---

backport of: #38171

parent tracker: https://tracker.ceph.com/issues/46296

(replaces: #40754)

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by smithfarm** [comment]
@yuvalif Thanks for taking this on!

I took the liberty of crosslinking this PR with the backport tracker issues so the latter gets closed properly when this PR goes in. (This crosslinking would have been done by the `ceph-backport.sh` script had it been used to create the PR.)

**Comment by yuriw** [comment]
test this please

**Comment by cbodley** [comment]
> manually removed reference to "persistent notifications"

in the future, make sure you document the conflicts in the commit message itself

**Review by cbodley — APPROVED** [review]

**Comment by cbodley** [comment]
jenkins test api

**Comment by cbodley** [comment]
jenkins test docs

**Pull request merged**
