### PR TITLE
mon,osd: add require_min_compat_client setting to enforce and clarify client compatibility

### PR DESCRIPTION
**Pull request by liewegas**
- [x] tests
- [x] qa suite update
- [x] rename config option to include 'require'

### CODE REVIEW

**Comment by dachary** [comment]
Having a feature bit makes things easier for http://tracker.ceph.com/issues/19836, great !

**Comment by dachary** [comment]
Should we add a CrushWrapper method encode_with_choose_args_pre_luminuous_if_possible to be called instead of encode if the client is pre-luminous ? Or should that be done outside of CrushWrapper ?

**Comment by liewegas** [comment]
I think you can just look at the features argumetn in 
CrushWrapper::encode.  If has_chooseargs() and 
!HAVE_FEATURE(CRUSH_CHOOSEARGS) then do the compat encoding.

**Comment by dachary** [comment]
Ok.

**Comment by dachary** [comment]
The UNIX domain socket path /home/jenkins-build/build/workspace/ceph-pull-requests/build/src/test/td/t-7202/out/client.xx-profile-ro.15033.asok is too long

jenkins test this please

**Comment by dachary** [comment]
The UNIX domain socket path /home/jenkins-build/build/workspace/ceph-pull-requests/build/src/test/td/t-7202/out/client.xx-profile-ro.15033.asok is too long

jenkins test this please

**Comment by dachary** [comment]
https://github.com/ceph/ceph/pull/15002 has the modified CrushWrapper::encode

**Comment by liewegas** [comment]
http://pulpito.ceph.com/sage-2017-05-09_03:37:05-rados-wip-crush-compat---basic-smithi/

**Comment by liewegas** [comment]
squashed commits and fixed cli test!

**Pull request merged**
