### PR TITLE
DNM: jewel: FAILED assert(m_image_ctx.journal == nullptr)

### PR DESCRIPTION
**Pull request by dachary**
http://tracker.ceph.com/issues/17134
http://tracker.ceph.com/issues/17261
http://tracker.ceph.com/issues/17243
http://tracker.ceph.com/issues/17242

### CODE REVIEW

**Comment by dachary** [comment]
@dillaman I would very much appreciate your review on the two conflicts resolutions https://github.com/ceph/ceph/pull/10869/commits/312d217e83a594baaefdb96a442d8b7c894f76cd and https://github.com/ceph/ceph/pull/10869/commits/88922c13a242a996f3295f2d8544791de83a4083

**Comment by dillaman** [comment]
@dachary lgtm -- not sure if you were planning to get this in for 10.2.3, but I'd like to hold for 10.2.4 if possible to give more runtime on the master branch.

**Comment by dachary** [comment]
Jenkins test this please (bluefs crash)

**Comment by dachary** [comment]
Set DNM because it conflicts with other pull requests targetting jewel.

**Comment by dachary** [comment]
Must cherry-pick https://github.com/ceph/ceph/pull/11034/commits which is the commit for http://tracker.ceph.com/issues/17261

**Comment by dachary** [comment]
Cherry-pick commits from http://tracker.ceph.com/issues/17243 as found at https://github.com/ceph/ceph/pull/10945 on top of these

git log --no-merges --oneline --cherry-mark --left-right ceph/jewel...ceph/master -- src/librbd/ExclusiveLock.cc

> f99dbbd librbd: potential null pointer dereference when requesting exclusive lock
> 5a68e33 librbd: use counter to track exclusive lock block/unblock requests
> 3dc1306 librbd: deadlock when replaying journal during image open
> 583ac91 librbd: interlock image refresh and lock operations
> d0d97fc librbd: integrate asynchronous image rewatch state machine
> 66c6055 librbd: exclusive lock now supports reacquiring a lost lock
> aa53f74 librbd: store exclusive lock cookie instead of recalculating
= ecea6dc librbd: delay acquiring exclusive lock if watch has failed
> d8e7946 librbd: always respond to "release lock" request if lock owner
= dfe9f3e librbd: delay acquiring exclusive lock if watch has failed
= ebce8ce librbd: optionally block proxied requests with an error code
= 93e2faf librbd: optionally block proxied requests with an error code
= 895c975 librbd: block RPC requests while updating features
= db7aaff librbd: block RPC requests while updating features

**Comment by dachary** [comment]
Cherry-pick commits from http://tracker.ceph.com/issues/17242 as found at https://github.com/ceph/ceph/pull/10974/commits on top of these

**Comment by dachary** [comment]
@dillaman I think these four backports should be done together

http://tracker.ceph.com/issues/17134
http://tracker.ceph.com/issues/17261
http://tracker.ceph.com/issues/17243
http://tracker.ceph.com/issues/17242

if that looks right to you I'll keep going. If it feels wrong, just let me know and I'll figure it out ;-)

**Comment by dillaman** [comment]
@dachary lgtm

**Comment by dillaman** [comment]
BTW -- I'll perform a sanity check of commits between jewel and master once the majority of open rbd jewel PRs have been merged just to ensure we haven't missed anything important.

**Comment by dachary** [comment]
@dillaman ack

**Comment by dillaman** [comment]
Requires PR #11465 when merged

**Comment by dachary** [comment]
rebased and the conflicts are still relevant as well as how they were resolved

**Comment by dachary** [comment]
"librbd: integrate asynchronous image rewatch state machine" looks like it is meaningfull only if https://github.com/ceph/ceph/commit/65d44d57ddc2a3d7592915ffe58ce43335f0f2c9 librbd: asynchronous image creation state machine  is backported. Meaning http://tracker.ceph.com/issues/17008 needs to be backported before this.

**Comment by dachary** [comment]
jason already has a backport for this one

**Pull request closed without merging**
