### PR TITLE
luminous: osd/PGLog: preserve original_crt to check rollbackability

### PR DESCRIPTION
**Pull request by pdvian**
http://tracker.ceph.com/issues/38905
http://tracker.ceph.com/issues/39042

### CODE REVIEW

**Comment by athanatos** [comment]
Yeah, that makes sense.

**Comment by pdvian** [comment]
@neha-ojha @athanatos accommodated 38905 changes (resolved minor conflict for ceph_assert) here.

**Comment by smithfarm** [comment]
jenkins test docs

**Comment by yuriw** [comment]
[wip-yuri2-testing-2019-06-07-2039-luminous](https://trello.com/c/jPJYEz25/634-wip-yuri2-testing-2019-06-07-2039-luminous)

**Pull request merged**
