### PR TITLE
test/old: remove stale tests

### PR DESCRIPTION
**Pull request by tchaikov**
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by tchaikov** [comment]
jenkins, retest this please

**Comment by tchaikov** [comment]
retest this please

**Comment by sebastian-philipp** [comment]
I'd be :+1:  to `/src/test/python/ceph` as well here.

**Comment by tchaikov** [comment]
http://pulpito.ceph.com/kchai-2019-07-22_16:29:12-rados-wip-kefu-testing-2019-07-22-1948-distro-basic-mira/

http://pulpito.ceph.com/kchai-2019-07-24_01:28:15-rados-wip-kefu-testing-2019-07-22-1948-distro-basic-smithi/

- "evicting unresponsive client": tracked by http://tracker.ceph.com/issues/40867
- tasks.mgr.test_progress.TestProgress: addressed by #29111
- tasks.mgr.dashboard.test_health.HealthTest: already fixed by #29172
 

@liewegas ping?

**Comment by tchaikov** [comment]
@sebastian-philipp probably we need to get @alfredodeza 's blessings on that one.

**Pull request merged**
