### PR TITLE
mgr/dashboard: cephfs subvolume list

### PR DESCRIPTION
**Pull request by nizamial09**
Fixes: https://tracker.ceph.com/issues/62182

https://github.com/ceph/ceph/assets/71764184/ae27ee50-e06a-4d50-a364-17495256b996

with namespace-isolation! 

Screenshot from 2023-08-01 14-04-52

Truncated path and copy to clipboard button
Screenshot from 2023-08-03 14-54-20

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by nizamial09** [comment]
these are all the values I can expose
```
atime: access time of the subvolume path in the format “YYYY-MM-DD HH:MM:SS”

mtime: modification time of the subvolume path in the format “YYYY-MM-DD HH:MM:SS”

ctime: change time of the subvolume path in the format “YYYY-MM-DD HH:MM:SS”

uid: uid of the subvolume path

gid: gid of the subvolume path

mode: mode of the subvolume path

mon_addrs: list of monitor addresses

bytes_pcent: quota used in percentage if quota is set, else displays undefined

bytes_quota: quota size in bytes if quota is set, else displays infinite

bytes_used: current used size of the subvolume in bytes

created_at: creation time of the subvolume in the format “YYYY-MM-DD HH:MM:SS”

data_pool: data pool to which the subvolume belongs

path: absolute path of a subvolume

type: subvolume type indicating whether it’s clone or subvolume

pool_namespace: RADOS namespace of the subvolume

features: features supported by the subvolume

state: current state of the subvolume
```
based on the discsussion today, i''ve exposed some. but if something needs to be prioritized i can also include that!

**Comment by cloudbehl** [comment]
Tested the PR locally mostly looks good. small Nits

1. If the sub volume is namespaced we are not showing that and the path to the namespace. Probably another tag next to  clone we can add as namespace. The tooltip can show the namespace path.
2. If i'm creating the subvolume from CLI, its not pooling in UI so the page doesn't get automatically updated. I need to change the tab and come back.
3. Information of Details tab is still being pooled in subVolume page.
4. I think we should mention count of Snapshots created. if not the list right now.
5

image

**Review by Pegonzal — APPROVED** [review]
Great job as per usual @nizamial09, thanks!

I'm still not a fan of the multiple tags in the name column and the usuage column for limitless subvolumes, neither of the "used and quota" text for the tooltip. 
But gets the job done, so looks good to me!

**Review by pereman2 — APPROVED** [review]
LGTM

**Comment by nizamial09** [comment]
> Tested the PR locally mostly looks good. small Nits
> 
> 1. If the sub volume is namespaced we are not showing that and the path to the namespace. Probably another tag next to  clone we can add as namespace. The tooltip can show the namespace path.

Updated this, thanks.


> 2. If i'm creating the subvolume from CLI, its not pooling in UI so the page doesn't get automatically updated. I need to change the tab and come back.

Its because of the changeDetection Strategy I am using now. I'll need to use the `fetchData` of the table component to probably make it work. But it might be a bit complicated with the async pipes. I'll need to check it though but I can do it on the follow ups.

> 3. Information of Details tab is still being pooled in subVolume page.

didn't understood this one.

> 4. I think we should mention count of Snapshots created. if not the list right now.

It might mess up the API. Because there will be lot of nesting inside the api to fetch the snapshot data's. I'll need to test this before going for the actual implementation because it could cause the same problem we had in the hosts page.

>    5
> 
> image

**Comment by nizamial09** [comment]
> Great job as per usual @nizamial09, thanks!
> 
> I'm still not a fan of the multiple tags in the name column and the usage column for limitless subvolumes, neither of the "used and quota" text for the tooltip. But gets the job done, so looks good to me!

Thanks @Pegonzal , for the multiple tags in the name column, it is better than having empty columns in the table. and for the usage, yeah that could have some room for improvements.

**Review by epuertat — APPROVED** [review]
Awesome @nizamial09!

Only observation:
* **Path**:
  * this can be potentially a large string. I've observed in other UIs that they usually shorten large strings by skipping the middle part: `/very/large/path/lorem/ipsum/blah/blah` to `/very/../blah`, and the whole path is displayed as a tool-tip or via copy-to-clipboard widget. What about adding a `pipe` for that?
  * Additionally, I'd format this as a `monospaced` font.

**Comment by cloudbehl** [comment]
jenkins test make check

**Comment by nizamial09** [comment]
> Awesome @nizamial09!
> 
> Only observation:
> 
> * **Path**:
>   
>   * this can be potentially a large string. I've observed in other UIs that they usually shorten large strings by skipping the middle part: `/very/large/path/lorem/ipsum/blah/blah` to `/very/../blah`, and the whole path is displayed as a tool-tip or via copy-to-clipboard widget. What about adding a `pipe` for that?
>   * Additionally, I'd format this as a `monospaced` font.

thanks done!

**Pull request merged**
