### PR TITLE
admin: pass --use-feature=2020-resolver to pip

### PR DESCRIPTION
**Pull request by tchaikov**
to silence the warning like

follow the suggestion from pip

ERROR: After October 2020 you may experience errors when installing or updating packages. This is because pip will change the way that it resolves dependency conflicts.

We recommend you use --use-feature=2020-resolver to test your packages with the new resolver before it becomes the default.

Fixes: https://tracker.ceph.com/issues/47636
Signed-off-by: Kefu Chai <kchai@redhat.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by smithfarm** [comment]
Tracker issue for backporting? (I assume pip will produce the same error for all active branches)

**Comment by tchaikov** [comment]
> Tracker issue for backporting? (I assume pip will produce the same error for all active branches)

done. i am not sure the is a fatal error, but anyway.

**Comment by smithfarm** [comment]
@tchaikov Any idea why `Docs: build check` is failing in this and other PRs atm?

**Comment by tchaikov** [comment]
> @tchaikov Any idea why `Docs: build check` is failing in this and other PRs atm?
```
+ sudo apt-get install -y gcc python3-dev python3-pip python3-virtualenv libxml2-dev libxslt-dev doxygen graphviz ant ditaa cython3
E: dpkg was interrupted, you must manually run 'sudo dpkg --configure -a' to correct the problem. 
```

need to ping @djgalloway on this.

**Comment by djgalloway** [comment]
> > @tchaikov Any idea why `Docs: build check` is failing in this and other PRs atm?
> 
> ```
> + sudo apt-get install -y gcc python3-dev python3-pip python3-virtualenv libxml2-dev libxslt-dev doxygen graphviz ant ditaa cython3
> E: dpkg was interrupted, you must manually run 'sudo dpkg --configure -a' to correct the problem. 
> ```
> 
> need to ping @djgalloway on this.

It was just that one slave.  Looks like maybe a job was aborted during an `apt` transaction and broke the package db.  I manually ran `sudo dpkg --configure -a` on it then was able to do the `apt-get install` command.

**Comment by tchaikov** [comment]
@djgalloway thanks!

**Comment by tchaikov** [comment]
@smithfarm  ping?

**Comment by smithfarm** [comment]
jenkins test api

**Review by neha-ojha — APPROVED** [review]

**Pull request merged**
