### PR TITLE
osd, messenger, librados: lttng oid tracing

### PR DESCRIPTION
**Pull request by yehudasa**
This PR is a cleaned up version of #12330

### CODE REVIEW

**Comment by liewegas** [comment]
[ 22%] Building CXX object src/tools/rbd_mirror/CMakeFiles/rbd_mirror_internal.dir/image_replayer/CreateImageRequest.cc.o
/home/jenkins-build/build/workspace/ceph-pull-requests/src/common/EventTrace.cc:29:32: fatal error: tracing/eventtrace.h: No such file or directory
 #include "tracing/eventtrace.h"
                                ^
compilation terminated.

**Comment by rchagam** [comment]
This is missing one additional commit e1f233322cdeeccc4c83642c04e43b399282e5e8 from prior pull request #12330. I have made one additional change to track BlueStore events - would like to push this to yehudasa/wip-func-oid-tracing branch if I can get access to push.

**Comment by rchagam** [comment]
https://github.com/rchagam/ceph/tree/wip-func-oid-tracing has all the changes too

**Comment by yehudasa** [comment]
@rchagam does that also fix this build failure? https://github.com/ceph/ceph/pull/12492#issuecomment-267633173

**Comment by yehudasa** [comment]
@rchagam I now see this commit:
https://github.com/rchagam/ceph/commit/3590b160ab924d45f36d6b68e0abeb8ae5057461

So which one do we need to apply?

**Comment by yehudasa** [comment]
retest this please

**Comment by liewegas** [comment]
Needs rebase

**Comment by rchagam** [comment]
Rebased, changed to new ceph_clock_now() function and tested. Pl pull in all files from https://github.com/rchagam/ceph/tree/wip-func-oid-tracing (commit: 5899e99f9dcea5274e4338b33412a701bc5db728). I will test your branch once you merge my latest commit files.

**Comment by yehudasa** [comment]
@rchagam I pushed a new version, can you look at it, make sure that everything is in?

**Comment by rchagam** [comment]
@yehudasa tested with and without tracing enabled and everything is good to go. 
Thx a lot for your help.

**Pull request merged**
