### PR TITLE
mgr/dashboard: fix retention add for subvolume

### PR DESCRIPTION
**Pull request by ivoalmeida**
Fixes: https://tracker.ceph.com/issues/64524

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [x] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

Adding snap schedule for subvolume with retention:

[Screencast from 2024-02-22 09-58-46.webm](https://github.com/ceph/ceph/assets/1071297/5b06bf55-54fa-437a-a62f-23a2a3eba77b)

Adding and removing snap schedules with same path and retention policy:

[Screencast from 2024-03-18 11-48-58.webm](https://github.com/ceph/ceph/assets/1071297/f218a176-12bb-4e81-8b85-abd47412ce57)

### CODE REVIEW

**Comment by ivoalmeida** [comment]
jenkins test make check

**Comment by ivoalmeida** [comment]
jenkins test api

**Comment by cloudbehl** [comment]
Worked fine for first time as shown in recording but if I delete and try again it fails with the below error.
[Screencast from 2024-02-21 20-15-22.webm](https://github.com/ceph/ceph/assets/6695156/7854b89e-3729-4def-b0c1-63e10bb77830)

**Comment by ivoalmeida** [comment]
> Worked fine for first time as shown in recording but if I delete and try again it fails with the below error. [Screencast from 2024-02-21 20-15-22.webm](https://github.com/ceph/ceph/assets/6695156/7854b89e-3729-4def-b0c1-63e10bb77830)

hi @cloudbehl  this is very new because it didn't use to happen before. I amended the delete endpoint to receive the retention policies and delete them as well as the snap schedule. Before it was enough to delete the snap schedule.

**Comment by ivoalmeida** [comment]
jenkins test api

**Comment by cloudbehl** [comment]
@ivoalmeida  Looks like now the retention is getting deleted with snap schedule. 

@vshankar any idea why this is happening, is it the new change that is making it fail?

**Comment by ivoalmeida** [comment]
> Worked fine for first time as shown in recording but if I delete and try again it fails with the below error. [Screencast from 2024-02-21 20-15-22.webm](https://github.com/ceph/ceph/assets/6695156/7854b89e-3729-4def-b0c1-63e10bb77830)

I am now explicitly removing retention policies when the last snap schedule for a given path is removed. So it fixes this problem too.

**Comment by cloudbehl** [comment]
I tested it and I see that the issue while deleting still persists. 

image

**Comment by ivoalmeida** [comment]
> I tested it and I see that the issue while deleting still persists.
> 
> image

This has been resolved already.

**Comment by cloudbehl** [comment]
jenkins test dashboard cephadm

**Review by cloudbehl — APPROVED** [review]
LGTM

**Comment by Pegonzal** [comment]
[screen-capture (34).webm](https://github.com/ceph/ceph/assets/106810838/a1669dbe-75fc-4a4f-94b7-0a6e89e88cb8)

```
2024-03-22T06:49:35.349+0000 7fafe7b3e700  0 [dashboard ERROR exception] Dashboard Exception
Traceback (most recent call last):
  File "/ceph/src/pybind/mgr/dashboard/services/exception.py", line 47, in dashboard_exception_handler
    return handler(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/cherrypy/_cpdispatch.py", line 54, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/ceph/src/pybind/mgr/dashboard/controllers/_base_controller.py", line 263, in inner
    ret = func(*args, **kwargs)
  File "/ceph/src/pybind/mgr/dashboard/controllers/_rest_controller.py", line 191, in wrapper
    return func(*vpath, **params)
  File "/ceph/src/pybind/mgr/dashboard/controllers/cephfs.py", line 1103, in delete_snapshot
    f'Failed to remove retention policy for path {path}: {err}'
dashboard.exceptions.DashboardException: Failed to remove retention policy for path /volumes/_nogroup/subv1/2ba59db1-3d9f-4bfd-b320-133384220fc8/..: Retention for d: 1 was not set for /volumes/_nogroup/subv1/2ba59db1-3d9f-4bfd-b320-133384220fc8/.. can't remove
```

**Pull request merged**
