### PR TITLE
jewel: librbd: discard after write can result in assertion failure

### PR DESCRIPTION
**Pull request by dillaman**
http://tracker.ceph.com/issues/17695

### CODE REVIEW

**Comment by dillaman** [comment]
@dachary I have this building right now and then I'll kick off a new set of fsx test runs against it.

**Comment by dachary** [comment]
s/properly/proper/ ?

**Comment by dillaman** [comment]
@dachary indeed -- I'll re-push after tests are run

**Comment by dillaman** [comment]
Teuthology test run:
http://pulpito.ceph.com/jdillaman-2016-10-25_13:37:55-rbd-wip-17695-distro-basic-smithi/

**Comment by dillaman** [comment]
@dachary two rbd-nbd tests are going to fail, one environment failure, and one unrelated failure in ceph_test_rbd_mirror. Looks fine to me.

**Comment by dillaman** [comment]
... and commit message now fixed

**Pull request merged**
