### PR TITLE
rgw: refactor selected files for better above- vs below-the-line

### PR DESCRIPTION
**Pull request by kalebskeithley**
Based on https://github.com/ceph/ceph/pull/48272, separate selected methods into new files for above-the-line vs below-the-line linkage. This is more of the work to prepare for eventual merging of the loadable module implementation.

"Utility" functions that don't reference the Store are moved, e.g. from rgw_zone.cc, into the new rgw_zone_utils.cc. Methods in the new *_utils.cc files are above-the-line.

Signed-off-by: Kaleb S. KEITHLEY <kkeithle@redhat.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [x] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [x] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [x] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by kalebskeithley** [comment]
jenkins test make check arm64

**Comment by kalebskeithley** [comment]
jenkins test make check arm64

**Comment by kalebskeithley** [comment]
jenkins test api

**Comment by kalebskeithley** [comment]
jenkins test api

**Comment by kalebskeithley** [comment]
jenkins test windows

**Review by dang — APPROVED** [review]
This looks quite plausible.  It's nice to get things moved to store/rados

**Comment by kalebskeithley** [comment]
jenkins test make check arm64

**Comment by kalebskeithley** [comment]
jenkins test make check arm64

**Comment by kalebskeithley** [comment]
jenkins test api

**Comment by kalebskeithley** [comment]
jenkins test api

**Comment by kalebskeithley** [comment]
jenkins test api

**Comment by kalebskeithley** [comment]
jenkins test api

**Comment by kalebskeithley** [comment]
jenkins test windows

**Comment by kalebskeithley** [comment]
http://pulpito.front.sepia.ceph.com/kkeithle-2022-11-29_13:14:43-rgw-wip-kkeithley-zipper1-distro-default-smithi/

70 out of 72 tests pass

**Comment by kalebskeithley** [comment]
http://pulpito.front.sepia.ceph.com/kkeithle-2022-11-29_23:54:37-rgw-wip-kkeithley-zipper2-distro-default-smithi/

69 of 72 tests passed.  (I don't know the tests well enough to judge if these are significant)

**Comment by kalebskeithley** [comment]
jenkins test make check arm64

**Comment by kalebskeithley** [comment]
jenkins test make check arm64

**Comment by dang** [comment]
I think this is okay, but I'm not sure about the multisite failures.

**Pull request merged**
