### PR TITLE
[WIP] mds: dmClock based subvolume QoS scheduler

### PR DESCRIPTION
**Pull request by yongseokoh**
This PR presents a volume QoS scheduler based on the dmClock algorithm for MDS. Our idea has previously been discussed with maintainers and developers in the dev mailing list. (Please, refer to the details [here](https://lists.ceph.io/hyperkitty/list/dev@ceph.io/thread/XO33ZPJ3BONNIKWMGN6A7K62F74C5AJO/).)

With this feature, MDS assigns QoS to throttle client metadata requests (e.g., create, mkdir, lookup, and so on) to subvolumes, where each subvolume QoS is shared among multiple client sessions at that time. For instance, there are four client sessions running on /volumes/_nogroup/subvolume configured with 100 QoS. The aggregated performance of the four clients will satisfy 100 metadata IOPS to an MDS. Key features are summarized below.

## Key features

- **dmClock scheduler per MDS** (e.g., similar to RGW dmClock). 
- **Per subvolume MDS QoS**. QoS capacity is shared among clients on the same subvolume.
- **QoS configuration through asok command**. The QoS options can be manipulated by the asok command on the fly. 
- **Per subvolume QoS management using virtual extended attributes**. An administrator can assign different QoS options to subvolumes through vxattr. 

### QoS default configuration through asok command
```
ceph --admin-daemon /var/run/ceph/mds.a.asok config set mds_dmclock_enable true
ceph --admin-daemon /var/run/ceph/mds.a.asok config set mds_dmclock_reservation 1000
ceph --admin-daemon /var/run/ceph/mds.a.asok config set mds_dmclock_weight 1500
ceph --admin-daemon /var/run/ceph/mds.a.asok config set mds_dmclock_limit 2000
```

These are considered as QoS default configuration that is inherited to subvolumes that don't maintain QoS vxattr.

### Create user subvolume

```
ceph fs subvolume create a subvolume --size $((100*1024*1024*1024))
ceph fs subvolume getpath a subvolume
/volumes/_nogroup/subvolume/1cc11247-dd8c-4c6b-a3d5-5f1525d4ac46
```

###  Subvolume QoS through vxattr
```
ceph-fuse -n client.admin -c ceph.conf -k keyring —client-mountpoint=/ mnt
setfattr -n ceph.dmclock.mds_reservation -v 1000 /mnt/volumes/_nogroup/subvolume/
setfattr -n ceph.dmclock.mds_weight -v 1000 /mnt/volumes/_nogroup/subvolume/
setfattr -n ceph.dmclock.mds_limit -v 1000 /mnt/volumes/_nogroup/subvolume/
```

Similar to quota and other things in MDS, QoS is configured using virtual extended attributes. For simplicity, QoS values are configured only to subvolume root path (e.g., /volumes/_nogroup/subvolume/). We internally check whether the specified inode has the SUBVOLUME flag. If you attempt to set QoS values to a non-subvolume directory like "/" or "/volumes", it fails. This manipulation is also only allowed for administrators.

### Client subvolume mount

```
ceph-fuse -n client.user -c ceph.conf -k keyring —client-mountpoint=/volumes/_nogroup/subvolume/1cc11247-dd8c-4c6b-a3d5-5f1525d4ac46 /mnt_user
```

The user can satify 1,000 MDS IOPS under /volume/_nogroup/subvolume.

### QoS Per Volume Metrics

```
ceph --admin-daemon /var/run/ceph/mds.a.asok dump qos
[
    {
        "qos_enabled": true,
        "state": "RUNNING",
        "default_reservation": 1000,
        "default_weight": 1500,
        "default_limit": 2000,
        "mds_dmclock_queue_size": 0,
        "inflight_requests": 0
    },
    [
       {
            "volume_id": "/volumes/_nogroup/subvolume",
            "use_default": false,
            "reservation": 1000,
            "weight": 1000,
            "limit": 1000,
            "inflight_requests": 0,
            "session_cnt": 1,
            "session_list": [
                "4265"
            ]
        }
    ]
]
```

### Disable subvolume QoS

```
setfattr -x ceph.dmclock.mds_reservation /mnt_user
setfattr -x ceph.dmclock.mds_weight /mnt_user
setfattr -x ceph.dmclock.mds_limit /mnt_user
```

If the QoS vxattr is removed, the subvolume follows the QoS default configuration. 

## QA Test Results using vstart_runner.py

test_mds_dmclock_qos has been newly implemented to evaluate our scheduler. To do a side effect test, numerous existing test cases in qa/tasks/cephfs/*.py have passed with --enable-mds-qos option successfully. Additionally, the rest of the other existing tests not mentioned here is not working regardless of our option in our test environment. We would like to utilize your Teuthology environment for further investigation if available.

 ``` 
source ~/venv/bin/activate (described in https://docs.ceph.com/en/latest/dev/developer_guide/running-tests-locally)

python ../qa/tasks/vstart_runner.py tasks.cephfs.test_mds_dmclock_qos --enable-mds-qos (newly added)

python ../qa/tasks/vstart_runner.py tasks.cephfs.test_admin.py --enable-mds-qos
python ../qa/tasks/vstart_runner.py tasks.cephfs.test_backtrace.py --enable-mds-qos
python ../qa/tasks/vstart_runner.py tasks.cephfs.test_fragment.py --enable-mds-qos
python ../qa/tasks/vstart_runner.py tasks.cephfs.test_multifs_auth.py --enable-mds-qos
python ../qa/tasks/vstart_runner.py tasks.cephfs.test_pool_perm.py --enable-mds-qos
python ../qa/tasks/vstart_runner.py tasks.cephfs.test_quota.py --enable-mds-qos
python ../qa/tasks/vstart_runner.py tasks.cephfs.test_readahead.py --enable-mds-qos
python ../qa/tasks/vstart_runner.py tasks.cephfs.test_recovery_pool.py --enable-mds-qos
python ../qa/tasks/vstart_runner.py tasks.cephfs.test_scrub.py --enable-mds-qos
 ```

## Unit Test
We have made a unit test including nine sub test cases. 
```
bin/unittest_mds_dmclock_sched (9/9 passed)
```

## dmClock Submodule Dependency
We have reported that the push priority queue, on which our scheduler relies, suffers from the following two issues. For development, the 073fcfb is conditionally applied in our work (currently disabled). 

- [https://github.com/ceph/dmclock/pull/84 (merged)](https://github.com/ceph/dmclock/pull/84)

## Future Work
- Volume QoS scheduler for OSD

## Tracker

- https://tracker.ceph.com/issues/48509

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by yongseokoh** [comment]
jenkins test api

**Comment by yongseokoh** [comment]
jenkins test api

**Comment by yongseokoh** [comment]
@batrick Hi,
Would you please provide your comments? There is no activity since we made this PR last month. We are just wondering if our work will help improve MDS QoS.

**Comment by batrick** [comment]
안녕하세요! I'm sorry this fell through the cracks. I don't think this can make the Pacific dev freeze on January 15th so I think this is something we can look at for the Q release. We will dedicate some time to reviewing it late February I think. Thanks for your patience.

**Comment by batrick** [comment]
@yongseokoh I want to have a look at this next week -- sorry for the delay! Can you drop the merge commits and rebase?

**Comment by yongseokoh** [comment]
jenkins test make check

**Comment by yongseokoh** [comment]
@batrick the commits are rebased now.

**Comment by yongseokoh** [comment]
jenkins test make check

**Comment by yongseokoh** [comment]
jenkins test make check

**Comment by yongseokoh** [comment]
jenkins test make check

**Comment by yongseokoh** [comment]
jenkins test api

**Comment by yongseokoh** [comment]
jenkins test make check

**Comment by yongseokoh** [comment]
jenkins retest this please

**Comment by jinmyeonglee** [comment]
jenkins test make check

**Comment by tchaikov** [comment]
https://github.com/ceph/dmclock/pull/84 has been merged.

**Comment by yongseokoh** [comment]
@batrick Could you please take a look at this PR?

**Comment by tchaikov** [comment]
#41341 has been merged to pick up mClock fixes of https://tracker.ceph.com/issues/48317

**Comment by yongseokoh** [comment]
jenkins test make check

**Comment by yongseokoh** [comment]
jenkins test make check arm64

**Comment by yongseokoh** [comment]
jenkins test make check

**Comment by yongseokoh** [comment]
jenkins test api

**Comment by yongseokoh** [comment]
@batrick We would like to share our progress. This work has been integrated into our production clusters based on the latest version of Nautilus. To evaluate our work's quality and reliability, we have configured KVM based Teuthology and also develop an in-house testing framework called Verdology. The detailed information related to our test environment and results is available at https://www.slideshare.net/YongseokOh1/revisiting-cephfs-mds-and-mclock-qos-scheduler. We have seen that 40 and 16 test cases are passed for Teuthology and Verdology. Specifically, we have been concentrating on MDS recovery test that randomly and abruptly restarts MDS daemons. As some issues were found during the evaluation, we have made modifications. Now, it works in our production clusters without any failures.

**Comment by yongseokoh** [comment]
jenkins retest this please

**Comment by yongseokoh** [comment]
jenkins retest this please

**Comment by yongseokoh** [comment]
@vshankar Can someone review this pr?

**Comment by yongseokoh** [comment]
jenkins test make check arm64

**Comment by robbat2** [comment]
For other readers, here's the video about this work:
https://www.youtube.com/watch?v=pDURll6Y-Ug

**Comment by robbat2** [comment]
@yongseokoh this needs rebasing again, but also figuring our why the checks failed. The old check results aren't available anymore, so you'l have to see about them when it runs again.

**Comment by robbat2** [comment]
I'm also wondering if you can split the PR meaningfully, to make the review process easier.

**Comment by yongseokoh** [comment]
@robbat2 I'll first check why the PR check is failing. I believe it's possible to separate this PR. I will go over it and let you know. Do you plan to review this PR?

**Comment by robbat2** [comment]
@yongseokoh yes, to the best of my skills, which is why splitting it is definitely going to ease the work.

**Comment by yongseokoh** [comment]
jenkins test make check arm64

**Comment by yongseokoh** [comment]
We can separate the major implementation into mds dmclock scheduler and virtual xattr based QoS management function. The remaining QA, unittest, and doc will be included in the PR or create another PR depending on the progress of the review. Do you have any additional comments?

It would be nice to hear from @vshankar and @batrick from the CephFS team.

**Comment by vshankar** [comment]
> We can separate the major implementation into mds dmclock scheduler and virtual xattr based QoS management function. The remaining QA, unittest, and doc will be included in the PR or create another PR depending on the progress of the review. Do you have any additional comments?
> 
> It would be nice to hear from @vshankar and @batrick from the CephFS team.

Frankly, I haven't looked into this yet. But I'll plan it out.

**Comment by yongseokoh** [comment]
jenkins test make check arm64

**Comment by yongseokoh** [comment]
For simplicity and easier review, only MDS scheduler implementation has been separated into a new PR https://github.com/ceph/ceph/pull/52147.

**Pull request closed without merging**
