### PR TITLE
luminous: mds: Assertion in EImportStart::replay should be a damaged()

### PR DESCRIPTION
**Pull request by shinobu-x**
http://tracker.ceph.com/issues/21870

### CODE REVIEW

**Comment by yuriw** [comment]
@shinobu-x @jcsp pls add area tag (e.g. core, mon etc)

**Comment by yuriw** [comment]
[wip-yuri3-testing-2018-01-29-1703-luminous](https://trello.com/c/Ti9d35jC/247-wip-yuri3-testing-2018-01-29-1703-luminous)

**Comment by batrick** [comment]
@yuriw please retest this one with the next batch.

**Comment by yuriw** [comment]
[wip-yuri-testing-2018-01-31-2202-luminous](https://trello.com/c/W5H3D6j7/253-wip-yuri-testing-2018-01-31-2202-luminous)

**Comment by batrick** [comment]
I have a suspicion the dead jobs in

http://pulpito.ceph.com/yuriw-2018-01-31_23:48:28-fs-wip-yuri-testing-2018-01-31-2202-luminous-testing-basic-smithi/

are possibly caused or not fixed by this. I need to investigate more.

**Pull request merged**
