### PR TITLE
luminous: rbd-mirror: sync image metadata when transfering remote image

### PR DESCRIPTION
**Pull request by dillaman**
http://tracker.ceph.com/issues/21644

### CODE REVIEW

**Comment by smithfarm** [comment]
```
[ 17%] Building CXX object CMakeFiles/rocksdb.dir/db/log_reader.cc.o
[ 17%] Building CXX object CMakeFiles/rocksdb.dir/db/log_writer.cc.o
[ 17%] Building CXX object CMakeFiles/rocksdb.dir/db/managed_iterator.cc.o
/home/jenkins-build/build/workspace/ceph-pull-requests/src/rocksdb/db/log_reader.cc: In member function ‘bool rocksdb::log::Reader::ReadRecord(rocksdb::Slice*, std::__cxx11::string*, rocksdb::WALRecoveryMode)’:
/home/jenkins-build/build/workspace/ceph-pull-requests/src/rocksdb/db/log_reader.cc:150:9: error: this statement may fall through [-Werror=implicit-fallthrough=]
         if (wal_recovery_mode == WALRecoveryMode::kAbsoluteConsistency) {
         ^~
/home/jenkins-build/build/workspace/ceph-pull-requests/src/rocksdb/db/log_reader.cc:156:7: note: here
       case kEof:
       ^~~~
/home/jenkins-build/build/workspace/ceph-pull-requests/src/rocksdb/db/log_reader.cc:170:9: error: this statement may fall through [-Werror=implicit-fallthrough=]
         if (wal_recovery_mode != WALRecoveryMode::kSkipAnyCorruptedRecords) {
         ^~
/home/jenkins-build/build/workspace/ceph-pull-requests/src/rocksdb/db/log_reader.cc:186:7: note: here
       case kBadRecord:
       ^~~~
cc1plus: all warnings being treated as errors
CMakeFiles/rocksdb.dir/build.make:854: recipe for target 'CMakeFiles/rocksdb.dir/db/log_reader.cc.o' failed
```

**Comment by smithfarm** [comment]
jenkins re-test this please

**Comment by trociny** [comment]
@ceph-jenkins retest this please

**Comment by yuriw** [comment]
[rbd => wip-yuri2-testing-2018-01-24-1620-luminous](https://trello.com/c/tD5oVOpi/242-rbd-wip-yuri2-testing-2018-01-24-1620-luminous)

**Pull request merged**
