### PR TITLE
qa/suites/rados/thrash: increase async and partial recovery test coverage

### PR DESCRIPTION
**Pull request by neha-ojha**
This should increase the amount of async and partial recovery and hopefully let us catch more bugs during thrashing.

Signed-off-by: Neha Ojha <nojha@redhat.com>

### CODE REVIEW

**Comment by jdurgin** [comment]
Did you look at results from this to see how much partial or async recovery happens? I wonder if more extreme values (e.g. min_cost 1, max clean 1000) would be more reliable in triggering partial/async recovery

**Comment by neha-ojha** [comment]
> Did you look at results from this to see how much partial or async recovery happens? I wonder if more extreme values (e.g. min_cost 1, max clean 1000) would be more reliable in triggering partial/async recovery

The run is in progress http://pulpito.ceph.com/nojha-2019-10-02_20:30:27-rados:thrash-master-distro-basic-smithi/, but sure I could that low/high to guarantee that we hit edge conditions.

**Comment by neha-ojha** [comment]
we should backport b62377561fae178d13c8f5765d3567e3af683496 to nautilus

**Comment by neha-ojha** [comment]
note to self: fix commit message for b62377561fae178d13c8f5765d3567e3af683496 to reflect 1, after the latest run finishes

http://pulpito.ceph.com/nojha-2019-10-02_21:21:43-rados:thrash-master-distro-basic-smithi/

**Comment by neha-ojha** [comment]
Test results: http://pulpito.ceph.com/nojha-2019-10-02_21:21:43-rados:thrash-master-distro-basic-smithi/

4352386 - https://tracker.ceph.com/issues/42178
4352402 - https://tracker.ceph.com/issues/40026
4352403 - https://tracker.ceph.com/issues/42177
4352384 - https://tracker.ceph.com/issues/42177
4352410 - https://tracker.ceph.com/issues/42175
4352415 - https://tracker.ceph.com/issues/42175

**Comment by neha-ojha** [comment]
> note to self: fix commit message for [b623775](https://github.com/ceph/ceph/commit/b62377561fae178d13c8f5765d3567e3af683496) to reflect 1, after the latest run finishes
> 
> http://pulpito.ceph.com/nojha-2019-10-02_21:21:43-rados:thrash-master-distro-basic-smithi/

done.

**Pull request merged**
