### PR TITLE
rgw: add admin rest api for bucket sync

### PR DESCRIPTION
**Pull request by zhangsw**
Add admin rest api for enable/disable bucket sync:

> PUT /admin/bucket?sync&format=json
> parameters:
> bucket: 
>   Description: The bucket name;
>   Type: String
>   Required: Yes
> sync: 
>   Description: Flag of enable/disable sync. 
>   Type: bool
>   Required: No. Default value is true.

Signed-off-by: Zhang Shaowen <zhangshaowen@cmss.chinamobile.com>

### CODE REVIEW

**Comment by mattbenjamin** [comment]
@cbodley is this interesting?  needs rebase

**Comment by cbodley** [comment]
@zhangsw there have been some significant changes in rgw_bucket.cc. i'd still like to take this if you're willing to work through the rebase

**Comment by zhangsw** [comment]
@cbodley I've rebased it.

**Comment by cbodley** [comment]
passed qa in http://pulpito.ceph.com/cbodley-2019-09-18_14:51:41-rgw-wip-cbodley-testing-distro-basic-smithi/

(slow ops failures tracked in https://tracker.ceph.com/issues/41834)

**Pull request merged**
