### PR TITLE
librados: use ceph::async::Completion for asio bindings

### PR DESCRIPTION
**Pull request by cbodley**
uses the generic async::Completion from https://github.com/ceph/ceph/pull/21914 to simplify the asio interface for librados

### CODE REVIEW

**Comment by cbodley** [comment]
cc @tchaikov if you're interested in tracking this

**Comment by tchaikov** [comment]
need to run it thru rados qa suite, at least those involving `rados_api_tests.yaml`.

**Comment by tchaikov** [comment]
http://pulpito.ceph.com/kchai-2018-05-31_23:47:34-rados-wip-kefu-testing-2018-06-01-0025-distro-basic-smithi/

**Comment by cbodley** [comment]
thanks @tchaikov!

**Pull request merged**
