### PR TITLE
doc: cleanup CephFS Landing Page

### PR DESCRIPTION
**Pull request by mchangir**
Fixes: https://tracker.ceph.com/issues/41952
Signed-off-by: Milind Changire <mchangir@redhat.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`

</details>

### CODE REVIEW

**Comment by mchangir** [comment]
jenkins render docs

**Comment by joscollin** [comment]
> https://docs.ceph.com/ceph-prs/30542/cephfs/#mounting-cephfs

Why do you need those blank headings now? May be, describe them briefly under [Using CephFS](https://docs.ceph.com/ceph-prs/30542/cephfs/#using-cephfs) and drop the headings?

**Comment by mchangir** [comment]
> > https://docs.ceph.com/ceph-prs/30542/cephfs/#mounting-cephfs
> 
> Why do you need those blank headings now? May be, describe them briefly under [Using CephFS](https://docs.ceph.com/ceph-prs/30542/cephfs/#using-cephfs) and drop the headings?

So far, I've figured that having those headings inserts a bullet item in Table of Contents on the left side and keeps the items grouped under that bullet item.

Now, if any wise soul can suggest a way to hide the headings, it'll be perfect.

**Comment by joscollin** [comment]
@mchangir The easiest way to achieve is to move those headings to a different hierarchy level. Please checkout [Ceph Volume - Existing OSDs](https://docs.ceph.com/docs/master/ceph-volume/#existing-osds ) doc design. https://github.com/ceph/ceph/blob/master/doc/ceph-volume/index.rst#existing-osds.

There might be a keyword to hide them, but [caption](http://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html?#directive-toctree) is what I found.

**Comment by mchangir** [comment]
@joscollin I've changed the heading level. So the headings aren't hurting the eyes anymore.

The `:caption:` directive doesn't seem to do much. It doesn't affect the bullets that are generated in the **Table of Contents** on the left. I too had the impression that it would solve the problem of hiding the headings. But no such luck.

**Comment by joscollin** [comment]
Jenkins render docs

**Comment by mchangir** [comment]
jenkins render docs

**Comment by mchangir** [comment]
@joscollin @batrick The headings are hidden now. We could have the headings back if we decide to add some section summary for each section though.

**Comment by joscollin** [comment]
@mchangir I didn't get a chance to look at your fix. Anyway, the landing page looks good now.

**Pull request merged**
