### PR TITLE
doc: rgw: Rewrite Java swift examples

### PR DESCRIPTION
**Pull request by hrchu**
cloudfiles is both unavailabe in maven and github.
https://github.com/rackerlabs/java-cloudfiles
https://search.maven.org/#search%7Cga%7C1%7Cjava-cloudfiles

Rewrite examples with http://joss.javaswift.org/.

Disclaimer: I have no relationship with the joss project

### CODE REVIEW

**Comment by liewegas** [comment]
retest this please

**Comment by oritwas** [comment]
jenkins test this please

**Comment by hrchu** [comment]
@oritwas Should I add the test here?: https://github.com/ceph/ceph/tree/master/qa/suites/rgw

**Comment by oritwas** [comment]
That will be great!

**Comment by oritwas** [comment]
lgtm

**Pull request merged**
