### PR TITLE
mgr/cephadm: fix 'auth get-or-create' call

### PR DESCRIPTION
**Pull request by liewegas**
If get-or-create caps doesn't work, we do 'auth caps' to update caps,
but this can also fail if the mons are running 15.2.0 (the 'mgr' profile
was updated to allow 'auth caps' in 15.2.1, see 467a27a66edb61d0d698ac596c645b67145395e6).

Signed-off-by: Sage Weil <sage@newdream.net>

### CODE REVIEW

**Comment by adk3798** [comment]
Is this specifically to fix upgrades from a version < 15.2.1 to a version > 15.2.1 where this is a temporary issue while the mgr daemons have already been upgraded but the mon daemons have not been upgraded yet? I'm guessing we can't just leave it in a state like this where we call 'auth get-or-create' without caps then add them in after with 'auth caps' if 'auth caps' doesn't work because then any newly created daemons wouldn't have their caps set.

**Comment by liewegas** [comment]
> Is this specifically to fix upgrades from a version < 15.2.1 to a version > 15.2.1 where this is a temporary issue while the mgr daemons have already been upgraded but the mon daemons have not been upgraded yet? I'm guessing we can't just leave it in a state like this where we call 'auth get-or-create' without caps then add them in after with 'auth caps' if 'auth caps' doesn't work because then any newly created daemons wouldn't have their caps set.

Right. And I think the first question is how and why did the mgr caps change to cause this problem.  Reproducing again to get a closer look...

**Comment by liewegas** [comment]
jenkins test make check

**Review by adk3798 — APPROVED** [review]
LGTM, do we still want a log message when the 'auth caps' call fails like you had originally?

**Comment by liewegas** [comment]
@adk3798 added another patch that adds the warning and allows the upgrade to proceed (instead of failing hard, which breaks our rados/cephadm/upgrade tests that start from 15.2.0)

**Pull request merged**
