### PR TITLE
rbd-ggate: fix syntax error.

### PR DESCRIPTION
**Pull request by wjwithagen**
Signed-off-by: Willem Jan Withagen <wjw@digiware.nl>

### CODE REVIEW

**Comment by wjwithagen** [comment]
@trociny 
Can you merge or should we ask @liewegas or @tchaikov

**Comment by wjwithagen** [comment]
FreeBSD-Jenkins is oke with this:
http://cephdev.digiware.nl:8180/jenkins/job/ceph-master/1667/consoleFull

**Comment by trociny** [comment]
@wjwithagen I will merge, but I need to wait for make check to successfull complete before merging.

**Comment by wjwithagen** [comment]
@trociny 
Great, thanx.

**Pull request merged**
