### PR TITLE
jewel: rgw: add option to log custom HTTP headers (rgw_log_http_headers)

### PR DESCRIPTION
**Pull request by mattbenjamin**
http://tracker.ceph.com/issues/18891

### CODE REVIEW

**Comment by dachary** [comment]
@mattbenjamin could you please amend the commit messages to explain why these cannot be cherry-picked from master ? If they are cherry-picked from master, could you update them with **git cherry-pick -x** so that they reference the original commit SHA ? Thanks !

**Comment by mattbenjamin** [comment]
@dachary sure--yes, it cannot be trivially cherry-picked, I'll update it

**Comment by mattbenjamin** [comment]
@dachary ok, done;  waiting for build checks

**Comment by dachary** [comment]
It passed the rgw suite at http://tracker.ceph.com/issues/17851#note-66.

**Pull request merged**
