### PR TITLE
Wip make dist rpm 3

### PR DESCRIPTION
**Pull request by osynge**
replaces https://github.com/ceph/ceph/pull/4905

### CODE REVIEW

**Comment by dachary** [comment]
@osynge would you mind rebasing instead of creating new pull requests ? Unless there is a specific reason to do so, it saves a little time with pull request triage :-)

**Comment by osynge** [comment]
@dachary sure, I will do in future, some thing funny happened when I tried to reorder so no commit would break anything (for bisecting)

**Comment by ktdreyer** [comment]
The general concept is good here.

One detail regarding implementation: I'd really like this RPM generation process to be outside of autoconf entirely. The fact that we have to do a full `./configure` run just to get a version number for an SRPM adds a lot of time onto the build process, since `./configure` takes so long.

Sage wrote a `./make_dist.sh` script (currently in master) that we're going use in place of "`make dist`" soon. This will allow us to get a tarball very quickly, without having to run `./configure`.

Can we do the same thing with a "`./make_rpm.sh`" ? (it could take an `--srpm` flag if you want to have it build both SRPMs and RPMs, as this PR currently does with `make rpm` and `make srpm`.)

**Comment by ktdreyer** [comment]
Re: my comment above, there's some background information about the "`make dist`" transition in this ceph-devel thread (http://www.spinics.net/lists/ceph-devel/msg23958.html)

**Comment by osynge** [comment]
@ktdreyer do you have any reason apart from performance ? This is a very bad idea in my opinion.

By not using configure to set the paths in the spec file.
* You have to set the paths in the code base of ceph for debian.
* You have to set the paths in the code base of ceph for redhat.
* You have to set the paths in the code base of ceph for SUSE.
* You have to make conditionals for all the paths for each OS.


A good example would be the file :

   src/ceph-osd-prestart.sh

By using configure we in a wrapper script such as ./make_rpm.sh we can set the paths to distribution in one place :)

**Comment by ktdreyer** [comment]
The RPMs and DEBs will still run `./configure` during the actual builds. For example, the RPMs will run `./configure` during `%prep`. The point is that we shouldn't have to run `./configure` just to get a tarball or SRPM.

The problem is that right now we have to run `./configure` twice: once to simply build a tarball with the proper version number, and once within `rpmbuild` itself.

**Comment by osynge** [comment]
@ktdreyer this seems a very small issue compared to the potentially lost features.

I answered on the mailing list in more depth why I feel this is wrong.

**Comment by osynge** [comment]
@ktdreyer 

First execution.
* Defaulting all release values as specified into all templated files such as ceph.spec.
Second execution.
* The subprocess of executing a rpm processed build that will result in and rpm.

**Comment by osynge** [comment]
Note "./make_rpm.sh" and "make rpm" applications provide different features.

 * making tar balls for publishing on the web.
 * makes rpm, srpm, and version tar ball.

They are two different use cases addressed.

**Comment by ktdreyer** [comment]
> @ktdreyer this seems a very small issue compared to the potentially lost features.

It's not clear to me what features we'd be losing by moving this out of autoconf and into a standalone script.

**Comment by osynge** [comment]
You will loose the ability to apply templates to things like "ceph.spec"

**Comment by osynge** [comment]
Maybe I should have merged this patch and the https://github.com/ceph/ceph/pull/4871 and suggested they be used together.

**Comment by ktdreyer** [comment]
> You loose sane default values and replace them with hard coded values.

can you give some further examples?

> Have to put a lot of conditionals in ceph.sepc.in

This is annoying. Ceph's .spec is a lot messier than anything else I've worked on. But os-specific conditionals have to go somewhere, and this follows the conventions that a lot of other projects and packages follow.

> You can support configure time calculation of default values eg "git hash"

Right, that's what "`make_dist.sh`" does, entirely independent of autoconf, and a lot faster than autoconf.

**Comment by osynge** [comment]
So we are agreed the arguments about this duplicating functionality of  "make_dist.sh" is irrelevant?

You agree now that I only need to provide examples of why variables are useful well I have to make a union of a few patches to show you :)

**Comment by osynge** [comment]
Being able to make nearly everything a variable in ceph.sec will prevent he turbulence caused by different conditionals being merged, ie where does this go?

    %if (0%{?rhel} && 0%{?rhel} < 7)
    install -m 0644 -D udev/95-ceph-osd-alt.rules $RPM_BUILD_ROOT/lib/udev/rules.d/95-ceph-osd.rules
    %else
    install -m 0644 -D udev/95-ceph-osd.rules $RPM_BUILD_ROOT/lib/udev/rules.d/95-ceph-osd.rules
    %endif

clearly in the spec file it would be nice to be:

    install -m 0644 -D udev/95-ceph-osd-alt.rules $RPM_BUILD_ROOT/@udev-dir@/95-ceph-osd.rules

Clearly the second line is better. We could even have configure find the directory, on every distribution if not set in the options :)

Its just a few lines in configure.ac and its done making the job easier :)

**Comment by osynge** [comment]
In summary I think autotools autodetection is a good way to insulate a project from the operating system configuration.

tip: If you explicitly set autotools options it can some times run faster, as it does not have to find out a default. Explicitly turning off java may help in configure run time.

**Comment by ktdreyer** [comment]
Using `@udev-dir@` in `ceph.spec.in` is not the way to go. Adding more autoconf variables into `ceph.spec.in` means building more layers of complexity on a system that's already horribly complex.

The particular example with the `95-ceph-osd.rules` file vs `95-ceph-osd-alt.rules` is a good example of a bad convention that was done as an expedient hack years ago to fix http://tracker.ceph.com/issues/4632. The two files have diverged since then, and the proper solution is to make `./configure` detect the system's udev version and conditionally install the correct `.rules` file during `make install`.

**Comment by osynge** [comment]
Adding more autoconf variables into ceph.spec.in means building more layers of complexity to allow the variables, to be variable and stored else wear.

In the end it comes down to isolating the changed values from the debian defaults to SUSE and redhat and making them variable, and handling the conditionals in a language with nicer conditionals the an rpm spec file makes a lot of sence.

**Comment by osynge** [comment]
when tested on fedora it did not work reasons where:

 1 not adding patch file to sources for fedora builds.

    +cp rpm/init-ceph.in-fedora.patch  $(rpmtopdir)/SOURCES

 2 fedora already defines _topodir so typo in _topdir definition caused failures.

    -       rpmbuild --define "_rpmtopdir $(rpmtopdir)" -ba @PACKAGE@.spec
    +       rpmbuild --define "_topdir $(rpmtopdir)" -ba @PACKAGE@.spec

These are now fixed in latest commit.

**Comment by osynge** [comment]
Added a comment between testing and making patch that caused build to fail. This comment is now in style of previous comments and no longer produces interesting errors.

**Comment by osynge** [comment]
@ktdreyer "using @udev-dir@ in ceph.spec.in is not the way to go."

(1) Please note this patch foes not contain @udev-dir@ type changes.

On that subject, the only strong contender not to just put more logic into autotools defaults as in https://github.com/ceph/ceph/pull/4871

**Comment by dachary** [comment]
@osynge this needs rebasing. And maybe a gentle ping ;-)

**Comment by dachary** [comment]
@osynge feel free to re-open when you have time to rebase

**Pull request closed without merging**
