### PR TITLE
kv/RocksDBStore: use bounded iterators in rm_range_keys

### PR DESCRIPTION
**Pull request by ifed01**
Fixes: https://tracker.ceph.com/issues/58463
Signed-off-by: Igor Fedotov <igor.fedotov@croit.io>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by ifed01** [comment]
jenkins test make check

**Comment by ifed01** [comment]
jenkins test make check

**Comment by ifed01** [comment]
jenkins test make check

**Comment by ifed01** [comment]
jonkins test ceph api

**Comment by ifed01** [comment]
jenkins test api

**Comment by ifed01** [comment]
jenkins test windows

**Review by cfsnyder — APPROVED** [review]
lgtm!

**Comment by ifed01** [comment]
jenkins test api

**Comment by markhpc** [comment]
@yuriw @ljflores can we get this added to a QA run?

**Comment by ljflores** [comment]
@markhpc yes, it's in the yuri4 batch!

**Comment by ljflores** [comment]
Rados suite review: https://pulpito.ceph.com/?branch=wip-yuri4-testing-2023-03-15-1418

Failures, unrelated:
    1. https://tracker.ceph.com/issues/58946
    2. https://tracker.ceph.com/issues/56393
    3. https://tracker.ceph.com/issues/59123
    4. https://tracker.ceph.com/issues/58585
    5. https://tracker.ceph.com/issues/58560
    6. https://tracker.ceph.com/issues/59127

Details:
    1. cephadm: KeyError: 'osdspec_affinity' - Ceph - Orchestrator
    2. thrash-erasure-code-big: failed to complete snap trimming before timeout - Ceph - RADOS
    3. Timeout opening channel - Infrastructure
    4. rook: failed to pull kubelet image - Ceph - Orchestrator
    5. test_envlibrados_for_rocksdb.sh failed to subscribe to repo - Infrastructure
    6. Job that normally complete much sooner last almost 12 hours - Infrastructure

**Pull request merged**
