### PR TITLE
nautilus: ceph-volume: reject disks smaller then 5GB in inventory

### PR DESCRIPTION
**Pull request by jan--f**
backport trackers:

* https://tracker.ceph.com/issues/42703
* https://tracker.ceph.com/issues/42753

---

backport of: 

* https://github.com/ceph/ceph/pull/29041
* https://github.com/ceph/ceph/pull/31492

parent trackers:

* https://tracker.ceph.com/issues/40776
* https://tracker.ceph.com/issues/42710

### CODE REVIEW

**Comment by sebastian-philipp** [comment]
Ok, do we also need to add #31492 to this PR in order to not create a regression?

**Comment by jan--f** [comment]
> Ok, do we also need to add (cherry-pick) #31492 to this PR in order to not create a regression?

We certainly do but the regression fix will only cherry-pick cleanly after this was merged.

**Comment by smithfarm** [comment]
@jan--f It will cherry-pick cleanly into this branch, though, right? We commonly gang together multiple backports into a single PR, especially when the subsequent ones are related.

**Comment by smithfarm** [comment]
jenkins test make check

**Comment by smithfarm** [comment]
@jan--f Nautilus merge season is open again. Can you trigger tests on this?

**Comment by jan--f** [comment]
jenkins test ceph-volume all

**Comment by jan--f** [comment]
jenkins test ceph-volume tox

**Comment by jan--f** [comment]
jenkins test ceph-volume all

**Pull request merged**
