### PR TITLE
[DNM SHOULD TARGET MASTER] nautilus: mgr/volumes: remove unused semicolon

### PR DESCRIPTION
**Pull request by lmgdlmgd**
## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by lmgdlmgd** [comment]
commit error

**Comment by lmgdlmgd** [comment]
hava a wrong commit

**Comment by lmgdlmgd** [comment]
hava a wrong commit

**Review by smithfarm — CHANGES_REQUESTED** [review]
Thanks for contributing to Ceph!

This fix can't be accepted as-is because it is targeting the wrong branch. Please re-target so the change goes into master, first.

To facilitate backporting, could you please also open a tracker issue at https://tracker.ceph.com and mention it in the commit message and pull request?

See https://github.com/ceph/ceph/blob/master/SubmittingPatches.rst for more information.

**Pull request closed without merging**
