### PR TITLE
Backport of pull request 3633 to hammer : Fixed write_full behavior in libradosstriper

### PR DESCRIPTION
**Pull request by sponce**
It was returning ENOENT when the file did not exists, while it should just have created it without complaining.

Signed-off-by: Sebastien Ponce <sebastien.ponce@cern.ch>

### CODE REVIEW

**Comment by dachary** [comment]
this needs to be against hammer, not master, right ?

**Comment by sponce** [comment]
yes, this is the backport against hammer, no that the branch has been separated from master.
I've also rebased it on latest hammer and repicked my latest modif to the master branch

**Comment by dachary** [comment]
you need to close this pull request and open a new one against hammer instead of master. Unfortunately github does not allow you to change the target branch once a pull request is open. https://github.com/sponce/ceph/commit/96304a4ee075239e20c5bff4c346b4292e742e99 is otherwise perfect :-)

**Comment by sponce** [comment]
Oh, got you know : I misclicked when creating it and created it against master. I did not notice so far.
So #3650 replaces it.

**Pull request closed without merging**
