### PR TITLE
Batch backport of nvmeof service configuration

### PR DESCRIPTION
**Pull request by afreen23**
Backporting nvmeof service confoguration with its regressions.
Hence,  a manual cherrypick of:

https://tracker.ceph.com/issues/66480
https://tracker.ceph.com/issues/66856
https://tracker.ceph.com/issues/66876

original PRs:
https://github.com/ceph/ceph/pull/57801
https://github.com/ceph/ceph/pull/58068/commits/1da0a4f8cb234ef84729c24cc9a82397361e9534
https://github.com/ceph/ceph/pull/57864/commits/27a8b2f2883fcc1fc4128b3e8995a7819a5ae51e

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [x] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [x] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Comment by afreen23** [comment]
jenkinst test dashboard

**Comment by afreen23** [comment]
jenkinst test dashboard

**Comment by nizamial09** [comment]
jenkins test dashboard

**Comment by nizamial09** [comment]
jenkins test dashboard cephadm

**Comment by afreen23** [comment]
jenkins test make check

**Comment by afreen23** [comment]
jenkins test dashboard cephadm

**Comment by afreen23** [comment]
jenkins test dashboard

**Comment by afreen23** [comment]
jenkins test make check

**Comment by afreen23** [comment]
jenkins test docs

**Comment by afreen23** [comment]
jenkins test make check

**Comment by afreen23** [comment]
jenkins test make check

**Review by Pegonzal — APPROVED** [review]
Thanks @afreen23! 

PR looks good to me!

There is just one small issue on the second commit [mgr/dashboard: fix service page e2e tests](https://github.com/ceph/ceph/pull/58477/commits/ec070f19c77e315231c63be165643ac0e1c4e401), as there are two different commits being referenced on the cherry-pick

(cherry picked from commit https://github.com/ceph/ceph/commit/5a718229dc43953f140a16342f19523a1c075863)
(cherry picked from commit https://github.com/ceph/ceph/commit/1da0a4f8cb234ef84729c24cc9a82397361e9534)

Could you get that solved?

**Comment by afreen23** [comment]
> Thanks @afreen23!
> 
> PR looks good to me!
> 
> There is just one small issue on the second commit [mgr/dashboard: fix service page e2e tests](https://github.com/ceph/ceph/pull/58477/commits/ec070f19c77e315231c63be165643ac0e1c4e401), as there are two different commits being referenced on the cherry-pick
> 
> (cherry picked from commit [5a71822](https://github.com/ceph/ceph/commit/5a718229dc43953f140a16342f19523a1c075863)) (cherry picked from commit [1da0a4f](https://github.com/ceph/ceph/commit/1da0a4f8cb234ef84729c24cc9a82397361e9534))
> 
> Could you get that solved?

Its present in original PR as well. See here https://github.com/ceph/ceph/commit/1da0a4f8cb234ef84729c24cc9a82397361e9534
Thats because @nizamial09 cherrypicked my changes and created a PR

**Pull request merged**
