### PR TITLE
OSD crash with Hammer to Jewel Upgrade: void FileStore::init_temp_collections()

### PR DESCRIPTION
**Pull request by dzafman**

### CODE REVIEW

**Comment by athanatos** [comment]
LGTM!

**Comment by dzafman** [comment]
Passed dzafman-2016-08-03_16:16:17-rados-wip-zafman-testing-distro-basic-smithi

**Comment by knandya** [comment]
@dzafman : We hit this issue during 10.2.2 testing. Do you know whether this PR is going to be merged for 10.2.3  release? Is there a defect corresponding to this fix?
Thanks for the help!

**Comment by athanatos** [comment]
@knandya Looks like it's in current jewel, but not 10.2.2.

**Comment by knandya** [comment]
@athanatos, In that case it is safe to assume the PR is going to be in 10.2.3 ? Asking this because, I'm unable to locate a defect corresponding to this PR in 10.2.3 closed defect list: 
http://tracker.ceph.com/projects/ceph/issues?fixed_version_id=518&set_filter=1&status_id=%2A

**Comment by athanatos** [comment]
@knandya Oh, that's not the closed defect list for 10.2.3, that's the list of tickets to track things that needed to be backported less urgently.  @dzafman did the backport himself, so it never got a backport ticket.  This should be in 10.2.3.

**Comment by knandya** [comment]
@athanatos Nice!  Any estimated availability date of 10.2.3?

**Comment by athanatos** [comment]
@knandya Not from me!

**Pull request merged**
