### PR TITLE
qa: do not iterate list being modified

### PR DESCRIPTION
**Pull request by batrick**
Fixes: https://tracker.ceph.com/issues/65022

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Comment by batrick** [comment]
@leonid-s-usov please take a look at the quiescdb `make check` failure in this PR.

**Comment by leonid-s-usov** [comment]
> @leonid-s-usov please take a look at the quiescdb `make check` failure in this PR.

@batrick I ran the test locally x1000 without reproduction. It looks like a test issue rather than a bug. Please re-run the test here while I try to reproduce it. I'll then submit a separate update to make the test more robust or fix an issue if any

**Comment by batrick** [comment]
jenkins test make check

**Comment by batrick** [comment]
jenkins test make check arm64

**Review by leonid-s-usov — APPROVED** [review]

**Review by lxbsz — APPROVED** [review]
Good catch @batrick

**Review by vshankar — APPROVED** [review]
Nice catch. But I wonder, what caused this test to trip _now_. My guess would be a change that started to spawn more background jobs.

**Comment by batrick** [comment]
> Nice catch. But I wonder, what caused this test to trip _now_. My guess would be a change that started to spawn more background jobs.

It is a regression caused by bb71023ced2d97a2590b98c4b820e7af6f1801b3

**Comment by batrick** [comment]
> > I ran the test locally x1000 without reproduction. It looks like a test issue rather than a bug. Please re-run the test here while I try to reproduce it. I'll then submit a separate update to make the test more robust or fix an issue if any
> 
> @batrick I can't reproduce [this test failure](https://jenkins.ceph.com/job/ceph-pull-requests/132584/consoleFull#-1902646324e840cee4-f4a4-4183-81dd-42855615f2c1), and there are no improvements I'd like to make in the test, as it should work well the way it is now. And maybe, it does :)
> 
> I guess we'll have to wait and see if this ever gets reproduced again

ack

**Comment by lxbsz** [comment]
jenkins test make check arm64

**Comment by leonid-s-usov** [comment]
> jenkins test make check arm64

don't bother, it's broken forever

**Comment by batrick** [comment]
This PR is under test in [https://tracker.ceph.com/issues/65530](https://tracker.ceph.com/issues/65530).

**Comment by batrick** [comment]
This PR is under test in [https://tracker.ceph.com/issues/65562](https://tracker.ceph.com/issues/65562).

**Comment by batrick** [comment]
This PR is under test in [https://tracker.ceph.com/issues/65596](https://tracker.ceph.com/issues/65596).

**Comment by batrick** [comment]
https://tracker.ceph.com/projects/cephfs/wiki/Main#2024-04-20

**Pull request merged**
