### PR TITLE
qa/rgw: put PG_AVAILABILITY ignorelist override in its own file

### PR DESCRIPTION
**Pull request by cbodley**
now covers the sts and multifs subsuites

re: https://tracker.ceph.com/issues/45802

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by cbodley** [comment]
hi @neha-ojha, we're seeing these PG_AVAILABILITY warnings in the rgw/sts and rgw/multifs suites too

**Comment by neha-ojha** [comment]
> hi @neha-ojha, we're seeing these PG_AVAILABILITY warnings in the rgw/sts and rgw/multifs suites too

hey @cbodley, can you share one of these new failures? I want to make sure it has the same root cause as https://tracker.ceph.com/issues/45802#note-3, most likely needs to be ignored.

**Comment by cbodley** [comment]
they aren't really new; the rgw/sts suite itself is relatively new, and they've been showing up in rgw/multifs for quite a while

rgw/multifs: http://qa-proxy.ceph.com/teuthology/cbodley-2021-03-15_14:08:48-rgw-wip-cbodley-testing-distro-basic-smithi/5967308/teuthology.log
rgw/sts: http://qa-proxy.ceph.com/teuthology/cbodley-2021-03-15_14:08:48-rgw-wip-cbodley-testing-distro-basic-smithi/5967282/teuthology.log

**Review by neha-ojha — APPROVED** [review]

**Comment by cbodley** [comment]
@neha-ojha thanks!

**Pull request merged**
