### PR TITLE
luminous: Random 500 errors in Swift PutObject

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/22574
http://tracker.ceph.com/issues/22583

### CODE REVIEW

**Comment by smithfarm** [comment]
Please review for overall completeness, as well as correctness of conflict resolution in 3421341

**Comment by adamemerson** [comment]
I staged https://github.com/ceph/ceph/pull/19788 yesterday. Rather than pulling in the deque patch and Casey's fix, I just left both out, though I didn't include mkogan's patch so this might be better.

You're missing 405ecc974f17973295cc2b5e9e910d90d4c79092 though.

**Comment by mattbenjamin** [comment]
@smithfarm due to the reverted cache fixes and so on, we should take https://github.com/ceph/ceph/pull/19788

**Comment by smithfarm** [comment]
@adamemerson OK. I'm thinking, though, that it might be expedient to bring mkogan's patch into your PR, since it touches the same code?

**Pull request closed without merging**
