### PR TITLE
mgr/dashboard: configure dependabot

### PR DESCRIPTION
**Pull request by epuertat**
https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates

Signed-off-by: Ernesto Puerta <epuertat@redhat.com>

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [x] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by epuertat** [comment]
@djgalloway the dependabot needs to be enabled in https://github.com/ceph/ceph/settings/security_analysis (I don't have access to that, can you please check it?). Thanks!

**Comment by djgalloway** [comment]
> @djgalloway the dependabot needs to be enabled in https://github.com/ceph/ceph/settings/security_analysis (I don't have access to that, can you please check it?). Thanks!

Done

**Comment by epuertat** [comment]
jenkins test api

**Comment by epuertat** [comment]
jenkins test make check arm64

**Comment by epuertat** [comment]
jenkins test dashboard

**Comment by epuertat** [comment]
> > @djgalloway the dependabot needs to be enabled in [ceph/ceph/settings/security_analysis](https://github.com/ceph/ceph/settings/security_analysis) (I don't have access to that, can you please check it?). Thanks!
> 
> Done

Thanks, @djgalloway !

**Review by nizamial09 — APPROVED** [review]

**Review by avanthakkar — APPROVED** [review]

**Review by alfonsomthd — APPROVED** [review]

**Pull request merged**
