### PR TITLE
mds: add 'p' flag in auth caps to control setting pool in layout

### PR DESCRIPTION
**Pull request by jcsp**
Related test: https://github.com/ceph/ceph-qa-suite/pull/703

### CODE REVIEW

**Comment by ukernel** [comment]
maybe we can apply this restriction check completely in ceph-fuse. check if client can write to a pool, if not, forbid operation that change layout.pool to the pool.

**Comment by jcsp** [comment]
@ukernel I want to avoid trusting the client

**Comment by ukernel** [comment]
the usage of the 'p' flag seems unnatural, what's the use case of it?

**Comment by jcsp** [comment]
The idea is that sometimes we have clients that are supposed to be consumers of some pre-configured directory that's pointing to a particular pool.  For example, in Manila we create a directory, set the pool on it, and then tell the client to mount that directory.

In cases like that, we don't want the client to be able to switch their directory to using a different pool.  They are already restricted from writing to those pools by their OSD caps, but I want to also restrict them from modifying their layouts.

I would expect most users to use "allow rw" most of the time and restrict "allow rwp" or "allow *" to some dedicated admin account.

**Comment by jcsp** [comment]
@gregsfortytwo @liewegas any opinions about the style of this?  the 'rwp' thing is just off the top of my head (and was straightforward to add the to parser)

**Comment by liewegas** [comment]
Maybe 'l' for layout is more natural?  I guess there are cases where we want to allow some layout changes (stripe size) and not pool?  Others might be

q = quota
s = snapshot
p = pool
l = layout (except for pool)
* = all of the above

?

**Comment by jcsp** [comment]
@liewegas those suggestions make sense to me, that would leave the current patch okay as-is, right?  Pool modification is what we're controlling here and we would only add 'l' et al later

**Comment by liewegas** [comment]
Yep!

**Comment by jcsp** [comment]
The new test is: https://github.com/ceph/ceph-qa-suite/pull/703  -- merge it at the same time as this.

See it passing here: http://pulpito.ceph.com/jspray-2015-11-30_02:06:10-fs-wip-testing-jcsp---basic-multi/1163861

**Pull request merged**
