### PR TITLE
librados: do cleanup

### PR DESCRIPTION
**Pull request by xiexingguo**
Remove unused local variables and perform explicit cast when call ioctx methods.
Signed-off-by: xie xingguo xie.xingguo@zte.com.cn

### CODE REVIEW

**Comment by xiexingguo** [comment]
@tchaikov Some more cleanups...
Sorry for discover them late and not batch them up :)

**Comment by tchaikov** [comment]
@xiexingguo  you might need to fix your `Signed-off-by` line in 9014daa4c8b5000806352cfe93cdc2b1d5472f05 and put more details in your commit message instead simply putting "Do some cleanup." in c705f579a86eb06d162217e3b749538869d75ffc

**Comment by xiexingguo** [comment]
@tchaikov fixup. please review.
Thanks a lot.

**Comment by sponce** [comment]
Looks all fine to me.

**Comment by sponce** [comment]
Sorry for the wrong closing : "the Clsoe and comment" button was too close from the "comment" one for my fat fingers...

**Comment by tchaikov** [comment]
lgtm also.

**Review by NelsonSolis90 — APPROVED** [review]

**Pull request merged**
