### PR TITLE
src/rados: rewrite bluestore-cache_autotune_interv

### PR DESCRIPTION
**Pull request by zdover23**
This commit rewrites one sentence in the "Bluestore
Config Reference". The sentence does not itself appear
in the directory structure under /docs/rados/, but is
instead in /src/common/options/global.yaml.in and is
included in the Bluestore Config Reference by means of
a confval directive.

The rewritten sentence has been rewritten from the passive
voice to the active voice, and a "how"-formation has been
removed. The removal of the "how"-formation, in my opinion,
makes the sentence go down much smoother for the first-time
reader.

Signed-off-by: Zac Dover <zac.dover@gmail.com>

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [x] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [x] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Review by ljflores — APPROVED** [review]

**Comment by ljflores** [comment]
@neha-ojha this can bypass teuthology testing, correct?

**Review by neha-ojha — CHANGES_REQUESTED** [review]
Please update the commit title according to https://github.com/ceph/ceph/blob/master/SubmittingPatches.rst#describe-your-changes, this is not a doc directory change.

**Comment by zdover23** [comment]
> Please update the commit title according to https://github.com/ceph/ceph/blob/master/SubmittingPatches.rst#describe-your-changes, this is not a doc directory change.

Thanks, Neha. I've made the change.

**Comment by ljflores** [comment]
jenkins test make check

**Comment by zdover23** [comment]
jenkins test make check

**Comment by ljflores** [comment]
@zdover23 there was a PR merged to fix the make check failure. Perhaps your PR needs to be rebased to include the change?

**Comment by zdover23** [comment]
> @zdover23 there was a PR merged earlier to fix the make check failure. Perhaps your PR needs to be rebased to include the change?

I'm a nightmare at rebasing. I'll pull in 4000 commits no one wants.

Here's a PR to do what this one tried and failed to do: https://github.com/ceph/ceph/pull/44711

**Pull request closed without merging**
