### PR TITLE
RGW Zipper - Make sure bucket list progresses

### PR DESCRIPTION
**Pull request by dang**
The bucket list wrapper lost the automatic advancement of the marker for
each iteration.  Some places manually set that marker, and it worked
fine, but some depended on it being automatically set.  Fix it so that
the marker advances automatically each iteration.

Signed-off-by: Daniel Gryniewicz <dang@redhat.com>

Addresses tracker: https://tracker.ceph.com/issues/49892

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Review by ivancich — APPROVED** [review]
LGTM

**Comment by cbodley** [comment]
zipper 10 was after pacific forked, or before?

**Comment by mattbenjamin** [comment]
I don't see a tracker ticket;  @dang does this apply to pacific?

**Comment by ivancich** [comment]
On the current pacific branch, headed by an Apr 1 merge of a Kefu commit (e010a7aeb144b1d2e29c547cd26d140834c7544e), Zipper 9 is in, but Zipper 10 is not.

**Comment by ivancich** [comment]
jenkins test api

**Comment by ivancich** [comment]
Passes teuthology:
- https://pulpito.ceph.com/ivancich-2021-04-06_04:00:38-rgw-wip-eric-testing-1-distro-basic-smithi/
- https://pulpito.ceph.com/ivancich-2021-04-06_04:01:05-rgw-wip-eric-testing-1-distro-basic-smithi/

**Pull request merged**
