### PR TITLE
[DNM] jewel: librbd: API methods to directly acquire and release the exclusive lock

### PR DESCRIPTION
**Pull request by dillaman**
http://tracker.ceph.com/issues/18337

### CODE REVIEW

**Comment by trociny** [comment]
@dillaman As we have rbd_lock_acquire lock only in the master (and not released kraken) so far, may be it is not too late to change API to include force_break_lock from #12639 to lock_acquire method, so we would not require lock_acquire2? This could be a separate commit to add it as noop, until #12639 is merged.

**Comment by dachary** [comment]
jenkins test this please (retarget to jewel)

**Comment by dillaman** [comment]
@trociny I had a similar thought and was on the fence. What really swayed me was that I thought there are different use-cases for each API method, so perhaps instead of ```lock_acquire2```, it should be ```lock_force_acquire```(?)

**Comment by dillaman** [comment]
This PR is included in PR #12890

**Comment by dillaman** [comment]
Merged with other PR

**Pull request closed without merging**
