### PR TITLE
rgw: skip re-sent part if previous attempt succeeded

### PR DESCRIPTION
**Pull request by trociny**
If by some reason a client re-sent a part of multipart upload, the reference to the previously successfully uploaded part was lost and it ended up in orphans.

To avoid orphans skip the newly uploaded part if the previous attempt succeeded (the first that comes wins).

Fixes: https://tracker.ceph.com/issues/44660
Signed-off-by: Mykola Golub <mgolub@suse.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by mattbenjamin** [comment]
does this generalize to all cases?  work is ongoing that will do so

**Comment by trociny** [comment]
This is an attempt to fix https://tracker.ceph.com/issues/44660

It is not complete as it uses rados backend specific `omap_get_vals_by_keys` that does not support other backends. And the additional problem with the current `omap_get_vals_by_keys` that it uses sync rados call.

But before working on the improvement I would like to see what other people think about the approach. Is it look right?

**Comment by mattbenjamin** [comment]
I don't think so, to be honest (but I appreciate the effort a lot, this defect has been around a long while).  My proposed approach is to just use CLS to accumulate all generated part names for an uploaded part (https://github.com/ceph/ceph/pull/37260).  Yixin Jin ( @yima77 ) came up with a revised version after reading my 2020 PR, and we've been working to combine the changes and finish the cleanup steps.

**Comment by trociny** [comment]
> does this generalize to all cases? work is ongoing that will do so

@mattbenjamin I am not sure I understand the question. I was not aware someone had already been working on this. If it is true and there will be a more generic solution, I will be happy to close this PR.

**Comment by trociny** [comment]
> I don't think so, to be honest (but I appreciate the effort a lot, this defect has been around a long while). My proposed approach is to just use CLS to accumulate all generated part names for an uploaded part (#37260). Yixin Jin ( @yima77 ) came up with a revised version after reading my 2020 PR, and we've been working to combine the changes and finish the cleanup steps.

Ah, great new! I was not aware of it. Then this PR may be closed.

**Comment by cbodley** [comment]
thanks @trociny

**Pull request closed without merging**
