### PR TITLE
osd: support cmpext operation on EC-backed pools

### PR DESCRIPTION
**Pull request by dillaman**
Slightly refactored COPY_FROM and async read handling to utilize a common approach to re-execute the ```OpContext```. The CMPEXT operation can now perform an async read when on an EC pool and later block the guarded write should the compare fail.

### CODE REVIEW

**Comment by dillaman** [comment]
This PR blocks #14868

**Comment by dillaman** [comment]
The current design of the OSD async read cannot handle restarting the remaining operations so the ```cmpext``` op doesn't actually guard write ops.

**Comment by dillaman** [comment]
retest this please

**Comment by liewegas** [comment]
needs rebase

**Comment by dillaman** [comment]
@liewegas rebased

**Comment by liewegas** [comment]
<pre>
2017-07-19T03:15:38.275 INFO:tasks.workunit.client.0.smithi040.stdout:                 api_tier: checking fo        api_aio: To be equal to: ret
2017-07-19T03:15:38.275 INFO:tasks.workunit.client.0.smithi040.stdout:                  api_aio:       Which is: -4095
2017-07-19T03:15:38.275 INFO:tasks.workunit.client.0.smithi040.stdout:                  api_aio: /build/ceph-12.1.1-156-g9345f8b/src/test/librados/aio.cc:4197: Failure
2017-07-19T03:15:38.275 INFO:tasks.workunit.client.0.smithi040.stdout:                  api_aio:       Expected: 0
2017-07-19T03:15:38.275 INFO:tasks.workunit.client.0.smithi040.stdout:                  api_aio: To be equal to: rd_cmpext_cmpl->get_return_value()
2017-07-19T03:15:38.276 INFO:tasks.workunit.client.0.smithi040.stdout:                  api_aio:       Which is: -4095
2017-07-19T03:15:38.276 INFO:tasks.workunit.client.0.smithi040.stdout:                  api_aio: /build/ceph-12.1.1-156-g9345f8b/src/test/librados/aio.cc:4198: Failure
2017-07-19T03:15:38.276 INFO:tasks.workunit.client.0.smithi040.stdout:                  api_aio:       Expected: 0
2017-07-19T03:15:38.276 INFO:tasks.workunit.client.0.smithi040.stdout:                  api_aio: To be equal to: ret
2017-07-19T03:15:38.276 INFO:tasks.workunit.client.0.smithi040.stdout:                  api_aio:       Which is: -4095
2017-07-19T03:15:38.276 INFO:tasks.workunit.client.0.smithi040.stdout:                  api_aio: [  FAILED  ] LibRadosAio.RoundTripCmpExtPP2 (3424 ms)
</pre>
/a/sage-2017-07-19_02:35:42-rados-wip-sage-testing-distro-basic-smithi/1415059

**Comment by dillaman** [comment]
@liewegas fixed -- but I am going to re-run through teuthology tomorrow.

**Comment by dillaman** [comment]
http://pulpito.ceph.com/jdillaman-2017-07-21_11:09:54-rados-wip-osd-cmpext-ec-pool-distro-basic-smithi/

**Comment by yuriw** [comment]
ready for merge
http://pulpito.ceph.com/yuriw-2017-07-25_14:51:59-rados-wip-yuri-testing2_2017_7_24-distro-basic-smithi/

http://pulpito.front.sepia.ceph.com/yuriw-2017-07-24_20:00:01-rados-wip-yuri-testing2_2017_7_24-distro-basic-smithi/

**Pull request merged**
