### PR TITLE
mgr/cephadm: customize blink_device_light cmd via j2

### PR DESCRIPTION
**Pull request by sebastian-philipp**
Blink a device light. Calling something like:

    lsmcli local-disk-ident-led-on --path $path

If you must, you can customize this via:

    ceph config-key set mgr/cephadm/lsmcli_blink_lights_cmd '<my jinja2 template>'

where my jinja2 template is something like:

    lsmcli local-disk-{{ ident_fault }}-led-{{'on' if on else 'off'}} --path '{{ path or dev }}'

If this ever comes as a feature request in the tracker, I'm happy to add a documentation 
section for it. Till then I'd be happy to leave it out.

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Review by votdev — COMMENTED** [review]
IMO it makes sense to completely allow the customization of the command line, e.g. if you need to use a different tool like `lsmcli`.

**Comment by LenzGr** [comment]
> IMO it makes sense to completely allow the customization of the command line, e.g. if you need to use a different tool like `lsmcli`.

Agreed. Please see the original [DeepSea implementation](https://github.com/SUSE/DeepSea/pull/1474/files#diff-94e9a9a02ae0c4183518e9095ed8f900) for reference.

**Comment by p-se** [comment]
@votdev @LenzGr The implementation allows the user to set the whole template. This already enables to customize the tool to be used. It is not limited to `lsmcli`.

**Comment by sebastian-philipp** [comment]
green: https://pulpito.ceph.com/swagner-2020-09-03_10:59:29-rados:cephadm-wip-swagner-testing-2020-09-03-1046-distro-basic-smithi/

**Pull request merged**
