### PR TITLE
octopus: ceph-volume: work around phantom atari partitions 

### PR DESCRIPTION
**Pull request by guits**
backport tracker: https://tracker.ceph.com/issues/52132

---

backport of https://github.com/ceph/ceph/pull/42469
parent tracker: https://tracker.ceph.com/issues/52060

this backport was staged using ceph-backport.sh version 16.0.0.6848
find the latest version at https://github.com/ceph/ceph/blob/master/src/script/ceph-backport.sh

### CODE REVIEW

**Comment by guits** [comment]
jenkins test ceph-volume tox

**Comment by dsavineau** [comment]
See https://github.com/ceph/ceph/pull/42753#issuecomment-896998417

**Comment by guits** [comment]
jenkins test ceph-volume tox

**Comment by guits** [comment]
jenkins test ceph-volume all

**Review by dsavineau — APPROVED** [review]

**Pull request merged**
