### PR TITLE
qa: enable quotas for pre-luminous quota tests

### PR DESCRIPTION
**Pull request by batrick**
Fixes: http://tracker.ceph.com/issues/20412

Signed-off-by: Patrick Donnelly <pdonnell@redhat.com>

### CODE REVIEW

**Comment by batrick** [comment]
@jcsp please take a quick look.

**Comment by smithfarm** [comment]
@batrick Needs to target jewel.

**Comment by smithfarm** [comment]
@batrick Also please include a sentence in the commit message to the effect of: "This cannot be cherry-picked from master because client_quota is true by default in master."

**Comment by batrick** [comment]
@smithfarm please take another look.

**Comment by smithfarm** [comment]
@batrick I prefer the formulation "This cannot be cherry-picked from master because . . ." since we have a backporting policy that says all bugfixes in stable releases should be cherry-picked from master when possible.

**Comment by smithfarm** [comment]
Anyway, I'll test it and report the result here.

**Comment by batrick** [comment]
@smithfarm I updated the message.

**Comment by smithfarm** [comment]
Confirm this makes the test pass: http://tracker.ceph.com/issues/19538#note-77

**Pull request merged**
