### PR TITLE
ceph-volume: handle leading whitespace/tabs in ceph.conf

### PR DESCRIPTION
**Pull request by alfredodeza**
Fixes: http://tracker.ceph.com/issues/22280

### CODE REVIEW

**Comment by alfredodeza** [comment]
jenkins test ceph-volume tox

**Comment by alfredodeza** [comment]
jenkins test ceph-volume lvm centos7-bluestore-create

**Comment by alfredodeza** [comment]
jenkins test ceph-volume lvm xenial-bluestore-create

**Comment by alfredodeza** [comment]
jenkins test ceph-volume lvm centos7-filestore-create

**Comment by alfredodeza** [comment]
jenkins test ceph-volume lvm xenial-filestore-create

**Comment by alfredodeza** [comment]
jenkins test ceph-volume lvm centos7-bluestore-create

**Comment by andrewschoen** [comment]
jenkins test ceph-volume lvm xenial-bluestore-create

**Comment by andrewschoen** [comment]
jenkins test ceph-volume lvm xenial-filestore-create

**Comment by alfredodeza** [comment]
Error: The requested URL returned error: 503 Service Unavailable

Trying again

**Comment by alfredodeza** [comment]
jenkins test ceph-volume lvm xenial-filestore-create

**Comment by alfredodeza** [comment]
jenkins test ceph-volume lvm xenial-bluestore-create

**Comment by alfredodeza** [comment]
@andrewschoen I am satisfied with the jobs that passed. This isn't scenario dependant, so if one passes I am expecting everything else to be OK.

**Comment by alfredodeza** [comment]
jenkins test ceph-volume tox

**Comment by alfredodeza** [comment]
jenkins test ceph-volume tox

**Pull request merged**
