### PR TITLE
luminous: rgw: fetch_remote_obj filters out olh attrs

### PR DESCRIPTION
**Pull request by cbodley**
backport tracker https://tracker.ceph.com/issues/38081 for prs https://github.com/ceph/ceph/pull/25794 and https://github.com/ceph/ceph/pull/26157

### CODE REVIEW

**Comment by yuriw** [comment]
@cbodley pls rebase

**--- pr 26191 --- pulling https://github.com/cbodley/ceph.git branch wip-38081-luminous
remote: Enumerating objects: 31, done.
remote: Counting objects: 100% (31/31), done.
remote: Total 37 (delta 31), reused 31 (delta 31), pack-reused 6
Unpacking objects: 100% (37/37), done.
From https://github.com/cbodley/ceph
 * branch            wip-38081-luminous -> FETCH_HEAD
Auto-merging src/test/rgw/rgw_multi/tests.py
CONFLICT (content): Merge conflict in src/test/rgw/rgw_multi/tests.py
Automatic merge failed; fix conflicts and then commit the result.
Traceback (most recent call last):
  File "/home/yuriw/wip_master/src/script/build-integration-branch", line 62, in <module>
    assert not r
AssertionError
**

**Comment by cbodley** [comment]
@yuriw looks like the conflict was with some other multisite pr in your branch. i'd have to rebase after that batch merges

**Comment by yuriw** [comment]
[wip-yuri6-testing-2019-02-25-1645-luminous](https://trello.com/c/c6AxymL8/547-wip-yuri6-testing-2019-02-25-1645-luminous)

**Comment by yuriw** [comment]
See multisite test failures http://pulpito.ceph.com/yuriw-2019-02-28_14:42:38-rgw-wip-yuri6-testing-2019-02-27-2042-luminous-distro-basic-smithi
add tags pls when ready

**Comment by yuriw** [comment]
[wip-yuri3-testing-2019-03-12-1629-luminous](https://trello.com/c/XyQRq6ri/555-wip-yuri3-testing-2019-03-12-1629-luminous)

**Comment by yuriw** [comment]
[wip-yuri4-testing-2019-03-27-2009-luminous](https://trello.com/c/wBvzoctn/567-wip-yuri4-testing-2019-03-27-2009-luminous)

**Comment by yuriw** [comment]
[wip-yuri4-testing-2019-04-01-1924-luminous](https://trello.com/c/rBPcQR14/572-wip-yuri4-testing-2019-04-01-1924-luminous)

**Pull request merged**
