### PR TITLE
ceph-volume: fix device unittest, mock has_bluestore_label

### PR DESCRIPTION
**Pull request by jan--f**
This also adds a test case for has_bluestore_label.

Fixes: https://tracker.ceph.com/issues/43611

Signed-off-by: Jan Fajerski <jfajerski@suse.com>

Fixes regression introduced by #32095

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by jan--f** [comment]
jenkins test ceph-volume tox

**Comment by jan--f** [comment]
Sorry that was premature.

**Comment by jan--f** [comment]
jenkins test ceph-volume tox

**Comment by liewegas** [comment]
retest this please

**Comment by jan--f** [comment]
retest this please

**Comment by jan--f** [comment]
jenkins test ceph-volume tox

**Pull request merged**
