### PR TITLE
doc: remove the description of deleted options

### PR DESCRIPTION
**Pull request by minshenglin**
Fixes: http://tracker.ceph.com/issues/17041

Signed-off-by: MinSheng Lin <minsheng.l@inwinstack.com>

### CODE REVIEW

**Comment by smithfarm** [comment]
added http://tracker.ceph.com/issues/17038 to the PR description

**Comment by minshenglin** [comment]
@smithfarm done.

**Comment by tchaikov** [comment]
@minshenglin could you put this way,

```
Fixes: http://tracker.ceph.com/issues/17041
Fixes: http://tracker.ceph.com/issues/17038
```

sorry for being picky.

**Comment by tchaikov** [comment]
@minshenglin BTW, i guess we can just close http://tracker.ceph.com/issues/17038 as "won't fix".

**Comment by minshenglin** [comment]
@tchaikov Do you mean we can close issue 17038 as "won't fix" and remove "Fixes: http://tracker.ceph.com/issues/17038" in commit message?

**Comment by smithfarm** [comment]
@minshenglin I marked it WON'T FIX. Now you can remove "Fixes: http://tracker.ceph.com/issues/17038" in commit message.

**Comment by minshenglin** [comment]
@smithfarm done.

**Comment by tchaikov** [comment]
lgtm.

**Pull request merged**
