### PR TITLE
pybind/ceph_argparse: validate csv if desc.N

### PR DESCRIPTION
**Pull request by tchaikov**
Fixes: https://tracker.ceph.com/issues/51145

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by liewegas** [comment]
Is the ability to comma-separate values for an ``n=N`` argument new?  If not, when did it break?

**Comment by tchaikov** [comment]
> Is the ability to comma-separate values for an `n=N` argument new? If not, when did it break?

i don't think it exists before.

**Comment by batrick** [comment]
> Is the ability to comma-separate values for an `n=N` argument new? If not, when did it break?

I'm not really sure. The documentation from [1] says:

> where scrubopts is a comma delimited list of recursive, force, or repair

but I don't know if that actually worked. We weren't testing it upstream. What **did** work was something like:

````
ceph tell mds.foo scrub start / recursive force <tag>
````

So you could do space-delimited choices. The final tag argument makes parsing more interesting but apparently it worked.

[1] https://docs.ceph.com/en/latest/cephfs/scrub/

**Review by batrick — APPROVED** [review]

**Comment by batrick** [comment]
I will QA with https://github.com/ceph/ceph/pull/41771

**Comment by batrick** [comment]
I've not yet dug into the failures yet but this PR breaks a number of tests, apparently. Here's the run:

https://pulpito.ceph.com/pdonnell-2021-06-12_03:45:26-fs-wip-pdonnell-testing-20210612.002730-distro-basic-smithi/

I'll take a deeper look next week.

**Comment by tchaikov** [comment]
changelog

- in addition to validate the arg, also collect the validated args in `args` and pass it to `store_arg()` explicitly.

**Comment by tchaikov** [comment]
@batrick thanks for testing this changeset. i addressed the test failures (hopefully) in the latest revision.

**Comment by tchaikov** [comment]
- https://pulpito.ceph.com/kchai-2021-06-13_08:30:20-rados-wip-kefu-testing-2021-06-13-1215-distro-basic-smithi/
- https://pulpito.ceph.com/kchai-2021-06-13_13:23:30-rados-wip-kefu-testing-2021-06-13-2001-distro-basic-smithi/

**Comment by tchaikov** [comment]
@batrick would you mind rescheduling a cephfs run with the updated changeset?

**Comment by batrick** [comment]
In 3h: https://pulpito.ceph.com/?branch=wip-pdonnell-testing-20210613.172157

**Comment by batrick** [comment]
@tchaikov saw your comments in #41771. I have a run to be scheduled with the latest changes as of this comment in 3 hours: https://pulpito.ceph.com/?branch=wip-pdonnell-testing-20210614.030817

Please kill it if you don't think this PR is ready.

**Review by ronen-fr — APPROVED** [review]

**Comment by tchaikov** [comment]
@batrick  i reran the failed tests in your batch at https://pulpito.ceph.com/kchai-2021-06-14_02:54:57-fs-wip-51145-kefu-1-distro-basic-smithi/ with the latest revision of this changeset. it looks much better than your batch, as the latest revision includes the support of `--choices-option choice1,choice2`. but there were still some failures in it.

some of them look like
```
ceph --cluster ceph fs snap-schedule list path=snap_test_dir1 format=json fs=cephfs

2021-06-14T03:13:51.999 INFO:teuthology.orchestra.run.smithi093.stderr:Invalid command: Unexpected argument 'fs=cephfs'
2021-06-14T03:13:51.999 INFO:teuthology.orchestra.run.smithi093.stderr:fs snap-schedule list <path> [<subvol>] [--recursive] [--fs <value>] [--format <value>] :  Get current snapshot schedule for <path>
```

which is tracked by https://tracker.ceph.com/issues/51182.  this syntax is new to me. it does not match with any of the following syntaxes:

- `prefix --foo=bar`
- `prefix --for bar`
- `prefix bar1 bar2`
- `prefix --yes-or-no`

how about changing `TestSnapSchedules.fs_snap_schedule_cmd()` to accept key-worded arguments, like
```py
def fs_snap_schedule_cmd(self, *args, **kwargs):
    kwargs['fs'] = self.volname
    for name, val in kwargs.items():
        args += [f'--{name}', str(val)]
    res = self._fs_cmd('snap-schedule', *args)
    log.debug(f'res={res}')
    return res
```
  
what do you think?

**Comment by tchaikov** [comment]
jenkins test make check

**Comment by batrick** [comment]
Yes, your change is good. I opened #41840.

I'll do one more round of testing today.

**Comment by batrick** [comment]
https://tracker.ceph.com/projects/cephfs/wiki/Master#2021-June-14

**Pull request merged**
