### PR TITLE
mon: cosmetic fixes for NVMeofGwMon files

### PR DESCRIPTION
**Pull request by athanatos**
<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Comment by athanatos** [comment]
This PR should not contain behavior changes.  The vast majority of the changes are simply retabs of otherwise unmodified lines.  I suggest reviewing this commit-by-commit in gitk with the "Ignore space change" checkbox checked (on the same line as the "Lines of context" option).  Github's interface has a similar checkbox "Hide whitespace" in the "Files changed" tab under the gear menu in the same row as the green "Review changes" button.

**Comment by athanatos** [comment]
I wanted to get this one out quickly as it's likely to conflict with any other in-progress work.  I'll follow up with subsequent PRs to do less cosmetic cleanups and other changes.

**Review by baum — APPROVED** [review]
@athanatos 🙏

**Review by leonidc — APPROVED** [review]

**Comment by oritwas** [comment]
LGTM

**Review by caroav — APPROVED** [review]

**Comment by athanatos** [comment]
jenkins retest this please

**Comment by athanatos** [comment]
@yuriw Can we include this one in the next batch?  It should be very low risk.

**Review by leonidc — APPROVED** [review]

**Comment by athanatos** [comment]
jenkins test make check

**Comment by athanatos** [comment]
Given the low risk and that the failures in https://pulpito.ceph.com/yuriw-2024-08-06_00:06:48-rados-wip-yuri13-testing-2024-08-05-0926-distro-default-smithi/ don't seem to be related, I'm going to go ahead and merge this one.

**Pull request merged**
