### PR TITLE
qa: add REST API method support for ceph-iscsi

### PR DESCRIPTION
**Pull request by lxbsz**
## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by lxbsz** [comment]
@dillaman This will depends on https://github.com/ceph/ceph-iscsi/pull/229, and after the ceph-iscsi PR get merged we need to build the ceph-iscsi package.

Thanks.

**Comment by dillaman** [comment]
Test failures:

http://qa-proxy.ceph.com/teuthology/jdillaman-2021-01-06_22:22:40-rbd-wip-jd-testing-distro-basic-smithi/5761732/teuthology.log

**Comment by lxbsz** [comment]
> Test failures:
> 
> http://qa-proxy.ceph.com/teuthology/jdillaman-2021-01-06_22:22:40-rbd-wip-jd-testing-distro-basic-smithi/5761732/teuthology.log

@dillaman Have fixed it and I have fired one teuthology test yesterday, but I couldn't open the Pulpito webset till now, so I couldn't check the result of it. And from tommorrow for the whole week I am afraid I won't be available.
Thanks.

**Comment by lxbsz** [comment]
Test passed:

https://pulpito.ceph.com/xiubli-2021-02-02_03:06:52-rbd:iscsi:-wip-jd-testing-distro-basic-smithi/

**Review by dillaman — APPROVED** [review]
lgtm

**Comment by dillaman** [comment]
pacific backport appended to #39305

**Pull request merged**
