### PR TITLE
build/ops: python-numpy-devel build dependency for SUSE

### PR DESCRIPTION
**Pull request by smithfarm**
Fixes: http://tracker.ceph.com/issues/21176
Signed-off-by: Nathan Cutler <ncutler@suse.com>

### CODE REVIEW

**Comment by smithfarm** [comment]
test this please

**Comment by tchaikov** [comment]
i think there is a way to disable the numpy extension when building libboost_python. but the jamfile is too abstruse to me.

**Comment by smithfarm** [comment]
@alfredodeza Here's a typical example of the infrastructure-related docs build check failure I was talking about.

**Comment by alfredodeza** [comment]
@smithfarm that is something we can't really control, as it is github itself failing/closing the connection:

    Command "git fetch --tags --progress https://github.com/ceph/ceph +refs/pull/*:refs/remotes/origin/pr/*" returned status code 128:
    stderr: error: RPC failed; curl 18 transfer closed with outstanding read data remaining

**Comment by smithfarm** [comment]
@alfredodeza Yeah, just wishing the check could be turned off for jewel. . .

**Comment by smithfarm** [comment]
jenkins test docs

**Comment by smithfarm** [comment]
@alfredodeza Can you do something with retry-backoff loops? (Just thinking out loud . . .)

**Comment by smithfarm** [comment]
luminous backport is https://github.com/ceph/ceph/pull/17692

**Pull request merged**
