### PR TITLE
PriorityCache: use "generic.current_allocated_bytes" to update tuned_mem

### PR DESCRIPTION
**Pull request by ZhiqiangLiu26**
When enable tcmalloc with 2M hugepage, in bstore_mempool thread, ceph_heap_release_free_memory() cannot free memory in free lists (page heap freelist, central freelist, thread freelist). Once the heap_size is greater than target_mem, the tuned_mem will continue to be decreased until a very small value. Actually, there are already many memory in free lists which cannot be used by the OSD.

The tuned_memory should be adjusted by current actual used memory by the OSD. However, `"generic.heap_size"-"tcmalloc.pageheap_unmapped_bytes"` not only includes memory used by the OSD, but also includes free memory in free lists.

We can use ceph_heap_get_numeric_property("generic.current_allocated_bytes", &current_allocated_byte) to indicate how much memory used by OSD, which not include freelists(page heap freelist, central freelist, thread freelist).

fix issue: https://tracker.ceph.com/issues/61493
Signed_off_by: Zhiqiang Liu <liuzhiqiang26@huawei.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by markhpc** [comment]
@ZhiqiangLiu26 Ok, let me recap to make sure I understand:  When you use 2MB huge pages, you end up with memory fragmentation, so pages aren't able to be released by ceph_heap_release_free_memory() and the freelist size grows to be quite large, making it so that the PriorityCache starts actively trying to free memory to allow some pages to be freed.   This doesn't work well because memory is so fragmented that nothing can be freed anyway so it basically shrinks the cache sizes to the minimum because memory is so fragmented that that OSD is hitting the target despite nothing being in the cache even though it can reuse some of the memory that's in the huge pages.  IE The goal of this PR is to basically ignore memory fragmentation when looking at the consumption of memory.  Do I have it right?  

I don't think we can realistically do that unless memory quotas for things like containers also ignore memory fragmentation.  The goal of the current behavior is that we release enough cache to let the kernel reclaim some of those pages and hit our targets, then fill the memory back in hopefully using holes in the huge pages and not growing the OSD larger than the target.  2MB hugepages might just be too coarse to do that effectively.  IE the problem here is not with the current priority cache behavior, but that 2MB hugepages are simply too large to effectively use in an environment with lots of small memory allocations where you are also trying to keep memory consumption from the kernel's perspective under a certain upper bounds.

I think we should instead only target large huge pages for allocations that can be easily freed in their entirety.

**Comment by baergj** [comment]
An idea here after talking about this at the perf meeting today: It looks like tcmalloc has an experimental pageheap implementation called Temeraire that tries to improve fragmentation on hugepages: https://google.github.io/tcmalloc/temeraire.html

https://github.com/google/tcmalloc/blob/master/docs/stats.md#experiments talks about some flags but I don't see these in the codebase, so I'm not quite certain how it gets enabled, but something that might be worth investigating for this usecase.

**Comment by ZhiqiangLiu26** [comment]
> An idea here after talking about this at the perf meeting today: It looks like tcmalloc has an experimental pageheap implementation called Temeraire that tries to improve fragmentation on hugepages: https://google.github.io/tcmalloc/temeraire.html
> 
> https://github.com/google/tcmalloc/blob/master/docs/stats.md#experiments talks about some flags but I don't see these in the codebase, so I'm not quite certain how it gets enabled, but something that might be worth investigating for this usecase.

Thanks for your reply.
Actually, we use gperftools tcmalloc `https://github.com/gperftools/gperftools` instead of google tcmalloc `https://github.com/google/tcmalloc`. In gperftools tcmalloc, hugepages from hugetlb will never be released to OS.

**Comment by ZhiqiangLiu26** [comment]
> @ZhiqiangLiu26 Ok, let me recap to make sure I understand: When you use 2MB huge pages, you end up with memory fragmentation, so pages aren't able to be released by ceph_heap_release_free_memory() and the freelist size grows to be quite large, making it so that the PriorityCache starts actively trying to free memory to allow some pages to be freed. This doesn't work well because memory is so fragmented that nothing can be freed anyway so it basically shrinks the cache sizes to the minimum because memory is so fragmented that that OSD is hitting the target despite nothing being in the cache even though it can reuse some of the memory that's in the huge pages. IE The goal of this PR is to basically ignore memory fragmentation when looking at the consumption of memory. Do I have it right?
> 
> I don't think we can realistically do that unless memory quotas for things like containers also ignore memory fragmentation. The goal of the current behavior is that we release enough cache to let the kernel reclaim some of those pages and hit our targets, then fill the memory back in hopefully using holes in the huge pages and not growing the OSD larger than the target. 2MB hugepages might just be too coarse to do that effectively. IE the problem here is not with the current priority cache behavior, but that 2MB hugepages are simply too large to effectively use in an environment with lots of small memory allocations where you are also trying to keep memory consumption from the kernel's perspective under a certain upper bounds.
> 
> I think we should instead only target large huge pages for allocations that can be easily freed in their entirety.

Thanks for your patient reply.
I use gperftools tcmalloc `https://github.com/gperftools/gperftools` instead of google tcmalloc `https://github.com/google/tcmalloc`.  The hugepages from hugetlb cannot be released even without memory fragmentation.
So, the performance was decreased until a very small value.  As you say, if we donot consider page freelist, memory fragmentation will cause more memory than user`s setting.

So please ignore this PR, I will try to adjust the limit of huge page and OSD target memory to have a good perfomance.

In addition, I open a new issue for gperftools tcmalloc, https://github.com/gperftools/gperftools/issues/1397

Thank you again.

**Comment by markhpc** [comment]
@ZhiqiangLiu26 Ok, thank you for the PR!  I will close this for now, but please feel free to reopen or open a new pull request if you discover something new.

**Pull request closed without merging**
