### PR TITLE
nautilus: ceph.in: do not preload ASan unless necessary

### PR DESCRIPTION
**Pull request by tchaikov**
## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by alfonsomthd** [comment]
jenkins test dashboard backend

**Comment by callithea** [comment]
Still the same error for the dashboard backend API tests :(
```ERROR: ld.so: object 'ASAN_LIBRARY-NOTFOUND' from LD_PRELOAD cannot be preloaded: ignored.
ERROR: ld.so: object 'ASAN_LIBRARY-NOTFOUND' from LD_PRELOAD cannot be preloaded: ignored.
Can't get admin socket path: unable to get conf option admin_socket for mon.a: ERROR: ld.so: object 'ASAN_LIBRARY-NOTFOUND' from LD_PRELOAD cannot be preloaded: ignored.

2019-11-18 10:06:44,670.670 INFO:__main__:ERROR
2019-11-18 10:06:44,670.670 INFO:__main__:
2019-11-18 10:06:44,671.671 INFO:__main__:======================================================================
2019-11-18 10:06:44,671.671 INFO:__main__:ERROR: setUpClass (tasks.mgr.dashboard.test_cephfs.CephfsTest)
2019-11-18 10:06:44,671.671 INFO:__main__:----------------------------------------------------------------------
2019-11-18 10:06:44,671.671 INFO:__main__:Traceback (most recent call last):
2019-11-18 10:06:44,672.672 INFO:__main__:  File "/home/jenkins-build/build/workspace/ceph-dashboard-pr-backend/qa/tasks/mgr/dashboard/helper.py", line 127, in setUpClass
2019-11-18 10:06:44,672.672 INFO:__main__:    cls.fs = cls.mds_cluster.newfs(create=True)
2019-11-18 10:06:44,672.672 INFO:__main__:  File "../qa/tasks/vstart_runner.py", line 705, in newfs
2019-11-18 10:06:44,672.672 INFO:__main__:    return LocalFilesystem(self._ctx, name=name, create=create)
2019-11-18 10:06:44,672.672 INFO:__main__:  File "../qa/tasks/vstart_runner.py", line 755, in __init__
2019-11-18 10:06:44,673.673 INFO:__main__:    self.create()
2019-11-18 10:06:44,673.673 INFO:__main__:  File "/home/jenkins-build/build/workspace/ceph-dashboard-pr-backend/qa/tasks/cephfs/filesystem.py", line 516, in create
2019-11-18 10:06:44,673.673 INFO:__main__:    pgs_per_fs_pool = self.get_pgs_per_fs_pool()
2019-11-18 10:06:44,673.673 INFO:__main__:  File "../qa/tasks/vstart_runner.py", line 776, in get_pgs_per_fs_pool
2019-11-18 10:06:44,673.673 INFO:__main__:    return 3 * int(self.get_config('mon_pg_warn_min_per_osd'))
2019-11-18 10:06:44,673.673 INFO:__main__:  File "../qa/tasks/vstart_runner.py", line 644, in get_config
2019-11-18 10:06:44,674.674 INFO:__main__:    return self.json_asok(['config', 'get', key], service_type, service_id)[key]
2019-11-18 10:06:44,674.674 INFO:__main__:  File "/home/jenkins-build/build/workspace/ceph-dashboard-pr-backend/qa/tasks/cephfs/filesystem.py", line 178, in json_asok
2019-11-18 10:06:44,674.674 INFO:__main__:    proc = self.mon_manager.admin_socket(service_type, service_id, command, timeout=timeout)
2019-11-18 10:06:44,674.674 INFO:__main__:  File "../qa/tasks/vstart_runner.py", line 618, in admin_socket
2019-11-18 10:06:44,674.674 INFO:__main__:    timeout=timeout
2019-11-18 10:06:44,675.675 INFO:__main__:  File "../qa/tasks/vstart_runner.py", line 301, in run
2019-11-18 10:06:44,675.675 INFO:__main__:    proc.wait()
2019-11-18 10:06:44,675.675 INFO:__main__:  File "../qa/tasks/vstart_runner.py", line 179, in wait
2019-11-18 10:06:44,675.675 INFO:__main__:    raise CommandFailedError(self.args, self.exitstatus)
2019-11-18 10:06:44,675.675 INFO:__main__:CommandFailedError: Command failed with status 22: ['./bin/ceph', 'daemon', 'mon.a', 'config', 'get', 'mon_pg_warn_min_per_osd']
2019-11-18 10:06:44,675.675 INFO:__main__:
2019-11-18 10:06:44,675.675 INFO:__main__:----------------------------------------------------------------------
2019-11-18 10:06:44,675.675 INFO:__main__:Ran 12 tests in 213.805s
2019-11-18 10:06:44,676.676 INFO:__main__:
2019-11-18 10:06:44,676.676 INFO:__main__:FAILED (errors=1)
2019-11-18 10:06:44,676.676 INFO:__main__:
2019-11-18 10:06:44,676.676 INFO:__main__:======================================================================
2019-11-18 10:06:44,676.676 INFO:__main__:ERROR: setUpClass (tasks.mgr.dashboard.test_cephfs.CephfsTest)
2019-11-18 10:06:44,676.676 INFO:__main__:----------------------------------------------------------------------
2019-11-18 10:06:44,676.676 INFO:__main__:Traceback (most recent call last):
2019-11-18 10:06:44,676.676 INFO:__main__:  File "/home/jenkins-build/build/workspace/ceph-dashboard-pr-backend/qa/tasks/mgr/dashboard/helper.py", line 127, in setUpClass
2019-11-18 10:06:44,676.676 INFO:__main__:    cls.fs = cls.mds_cluster.newfs(create=True)
2019-11-18 10:06:44,676.676 INFO:__main__:  File "../qa/tasks/vstart_runner.py", line 705, in newfs
2019-11-18 10:06:44,676.676 INFO:__main__:    return LocalFilesystem(self._ctx, name=name, create=create)
2019-11-18 10:06:44,677.677 INFO:__main__:  File "../qa/tasks/vstart_runner.py", line 755, in __init__
2019-11-18 10:06:44,677.677 INFO:__main__:    self.create()
2019-11-18 10:06:44,677.677 INFO:__main__:  File "/home/jenkins-build/build/workspace/ceph-dashboard-pr-backend/qa/tasks/cephfs/filesystem.py", line 516, in create
2019-11-18 10:06:44,677.677 INFO:__main__:    pgs_per_fs_pool = self.get_pgs_per_fs_pool()
2019-11-18 10:06:44,677.677 INFO:__main__:  File "../qa/tasks/vstart_runner.py", line 776, in get_pgs_per_fs_pool
2019-11-18 10:06:44,677.677 INFO:__main__:    return 3 * int(self.get_config('mon_pg_warn_min_per_osd'))
2019-11-18 10:06:44,677.677 INFO:__main__:  File "../qa/tasks/vstart_runner.py", line 644, in get_config
2019-11-18 10:06:44,677.677 INFO:__main__:    return self.json_asok(['config', 'get', key], service_type, service_id)[key]
2019-11-18 10:06:44,677.677 INFO:__main__:  File "/home/jenkins-build/build/workspace/ceph-dashboard-pr-backend/qa/tasks/cephfs/filesystem.py", line 178, in json_asok
2019-11-18 10:06:44,677.677 INFO:__main__:    proc = self.mon_manager.admin_socket(service_type, service_id, command, timeout=timeout)
2019-11-18 10:06:44,677.677 INFO:__main__:  File "../qa/tasks/vstart_runner.py", line 618, in admin_socket
2019-11-18 10:06:44,677.677 INFO:__main__:    timeout=timeout
2019-11-18 10:06:44,678.678 INFO:__main__:  File "../qa/tasks/vstart_runner.py", line 301, in run
2019-11-18 10:06:44,678.678 INFO:__main__:    proc.wait()
2019-11-18 10:06:44,678.678 INFO:__main__:  File "../qa/tasks/vstart_runner.py", line 179, in wait
2019-11-18 10:06:44,678.678 INFO:__main__:    raise CommandFailedError(self.args, self.exitstatus)
2019-11-18 10:06:44,678.678 INFO:__main__:CommandFailedError: Command failed with status 22: ['./bin/ceph', 'daemon', 'mon.a', 'config', 'get', 'mon_pg_warn_min_per_osd']```

@tchaikov Is there any other way to fix this?
What exactly is requiring the ASan library?

**Comment by callithea** [comment]
@tchaikov Is there any other way to fix this?
What exactly is requiring the ASan library?

**Comment by alfonsomthd** [comment]
jenkins test dashboard backend

**Comment by yuriw** [comment]
[wip-yuri3-testing-2019-11-18-2140-nautilus](https://trello.com/c/Ij7gxvpz/768-wip-yuri3-testing-2019-11-18-2140-nautilus)

**Comment by alfonsomthd** [comment]
@callithea @tchaikov @epuertat Backend API tests passed!

**Comment by callithea** [comment]
@tchaikov thanks a lot for looking into this, much appreciated!

**Pull request merged**
