### PR TITLE
mds: split _prefetch_dirfrags to avoid heartbeat timeout during up:rejoin

### PR DESCRIPTION
**Pull request by yongseokoh**
fixes: https://tracker.ceph.com/issues/53521

Signed-off-by: Yongseok Oh <yongseok.oh@linecorp.com>

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by lxbsz** [comment]
Could you explain more how will this work ? I see it's kicking the heartbeat for each 1000 loop, why it won't work here ?

**Comment by yongseokoh** [comment]
@lxbsz The issue is that the heartbeat timer is not updated until finish_func is called. https://github.com/ceph/ceph/blob/master/src/mds/OpenFileTable.cc#L1104 

If there are a lot of dirs to be fetched, the warning like "MDS internal heartbeat is not healthy!" happens for a while until the prefetch_state is transitioned to FILES_INODES executed by the finisher thread.

**Comment by lxbsz** [comment]
> @lxbsz The issue is that the heartbeat timer is not updated until finish_func is called. https://github.com/ceph/ceph/blob/master/src/mds/OpenFileTable.cc#L1104
> 

The `finish_func()` will be called after all the `dir->fetch()`'s completion callbacks finish. And all the fetches are asynchronous. I think your fixing here really could reduce the number of fetch completion callbacks to 1000 for each batch. But could you be sure that the 1000 won't trigger the timeout ?

The root cause should be there has too many completion callbacks in batch, and it will make the Finisher thread keep running without kicking the heartbeat.

Could you test will https://github.com/lxbsz/ceph/commit/5233045d5c4b8842ccedec158ab0c3f035d26817 work for you ?




> If there are a lot of dirs to be fetched, the warning like "MDS internal heartbeat is not healthy!" happens for a while until the prefetch_state is transitioned to FILES_INODES executed by the finisher thread.

**Comment by yongseokoh** [comment]
> The `finish_func()` will be called after all the `dir->fetch()`'s completion callbacks finish. And all the fetches are asynchronous. I think your fixing here really could reduce the number of fetch completion callbacks to 1000 for each batch. But could you be sure that the 1000 completion callbacks won't trigger the timeout ?
> 
> The root cause should be there has too many completion callbacks in batch, and it will make the Finisher thread keep running without kicking the heartbeat.
> 
> Could you test will [lxbsz@5233045](https://github.com/lxbsz/ceph/commit/5233045d5c4b8842ccedec158ab0c3f035d26817) work for you ?

This approach splitting dir fetches into 1k callbacks may not avoid the timeout issue according to cluster condition. I will cherry-pick your commit and retest it again.

**Comment by yongseokoh** [comment]
FYI. The logs below have been captured when the number of dirs to be fetched is set 500. It takes about 30 seconds to read 500 dirs from the OMAP layer. You can check `next_prefetch_dirfrags` message.

```
2021-12-10 13:46:26.774 7f85bc565700  1 mds.3.openfiles _prefetch_dirfrags start
2021-12-10 13:46:26.776 7f85bc565700  1 mds.3.openfiles _prefetch_dirfrags make fetch_queue done
2021-12-10 13:46:26.811 7f85bc565700  1 mds.3.openfiles next_prefetch_dirfrags continue
2021-12-10 13:46:26.811 7f85bc565700  1 mds.3.openfiles _open_ino_finish done prefetch_state 2
2021-12-10 13:46:53.356 7f85b9d60700  1 heartbeat_map is_healthy 'MDSRank' had timed out after 15
2021-12-10 13:46:53.356 7f85b9d60700  0 mds.beacon.mds003 Skipping beacon heartbeat to monitors (last acked 3.99999s ago); MDS internal heartbeat is not healthy!
2021-12-10 13:46:53.856 7f85b9d60700  1 heartbeat_map is_healthy 'MDSRank' had timed out after 15
2021-12-10 13:46:53.856 7f85b9d60700  0 mds.beacon.mds003 Skipping beacon heartbeat to monitors (last acked 4.49999s ago); MDS internal heartbeat is not healthy!
2021-12-10 13:46:54.357 7f85b9d60700  1 heartbeat_map is_healthy 'MDSRank' had timed out after 15
2021-12-10 13:46:54.357 7f85b9d60700  0 mds.beacon.mds003 Skipping beacon heartbeat to monitors (last acked 5.00099s ago); MDS internal heartbeat is not healthy!
2021-12-10 13:46:54.857 7f85b9d60700  1 heartbeat_map is_healthy 'MDSRank' had timed out after 15
2021-12-10 13:46:54.857 7f85b9d60700  0 mds.beacon.mds003 Skipping beacon heartbeat to monitors (last acked 5.50099s ago); MDS internal heartbeat is not healthy!
2021-12-10 13:46:55.357 7f85b9d60700  1 heartbeat_map is_healthy 'MDSRank' had timed out after 15
2021-12-10 13:46:55.357 7f85b9d60700  0 mds.beacon.mds003 Skipping beacon heartbeat to monitors (last acked 6.00099s ago); MDS internal heartbeat is not healthy!
2021-12-10 13:46:55.857 7f85b9d60700  1 heartbeat_map is_healthy 'MDSRank' had timed out after 15
2021-12-10 13:46:55.857 7f85b9d60700  0 mds.beacon.mds003 Skipping beacon heartbeat to monitors (last acked 6.50099s ago); MDS internal heartbeat is not healthy!
2021-12-10 13:46:56.357 7f85b9d60700  1 heartbeat_map is_healthy 'MDSRank' had timed out after 15
2021-12-10 13:46:56.357 7f85b9d60700  0 mds.beacon.mds003 Skipping beacon heartbeat to monitors (last acked 7.00098s ago); MDS internal heartbeat is not healthy!
2021-12-10 13:46:56.857 7f85b9d60700  1 heartbeat_map is_healthy 'MDSRank' had timed out after 15
2021-12-10 13:46:56.857 7f85b9d60700  0 mds.beacon.mds003 Skipping beacon heartbeat to monitors (last acked 7.50098s ago); MDS internal heartbeat is not healthy!
2021-12-10 13:46:57.357 7f85b9d60700  1 heartbeat_map is_healthy 'MDSRank' had timed out after 15
2021-12-10 13:46:57.357 7f85b9d60700  0 mds.beacon.mds003 Skipping beacon heartbeat to monitors (last acked 8.00098s ago); MDS internal heartbeat is not healthy!
2021-12-10 13:46:57.857 7f85b9d60700  1 heartbeat_map is_healthy 'MDSRank' had timed out after 15
2021-12-10 13:46:57.858 7f85b9d60700  0 mds.beacon.mds003 Skipping beacon heartbeat to monitors (last acked 8.50098s ago); MDS internal heartbeat is not healthy!
2021-12-10 13:46:58.358 7f85b9d60700  1 heartbeat_map is_healthy 'MDSRank' had timed out after 15
2021-12-10 13:46:58.358 7f85b9d60700  0 mds.beacon.mds003 Skipping beacon heartbeat to monitors (last acked 9.00198s ago); MDS internal heartbeat is not healthy!
2021-12-10 13:46:58.443 7f85bc565700  1 mds.mds003 Updating MDS map to version 5567 from mon.0
2021-12-10 13:46:58.443 7f85b5d58700  1 heartbeat_map reset_timeout 'MDSRank' had timed out after 15
2021-12-10 13:46:58.480 7f85b5d58700  1 mds.3.openfiles next_prefetch_dirfrags continue
2021-12-10 13:46:58.480 7f85ba561700  0 log_channel(cluster) log [WRN] : 1 slow requests, 1 included below; oldest blocked for > 32.129866 secs
2021-12-10 13:46:58.480 7f85ba561700  0 log_channel(cluster) log [WRN] : slow request 32.129864 seconds old, received at 2021-12-10 13:46:26.351080: rejoin:client.119991:223081 currently dispatched
2021-12-10 13:46:58.480 7f85bc565700  1 mds.mds003 Updating MDS map to version 5568 from mon.0
2021-12-10 13:46:58.481 7f85bc565700  1 mds.mds003 Updating MDS map to version 5569 from mon.0
2021-12-10 13:47:03.742 7f85ba561700  0 log_channel(cluster) log [WRN] : 1 slow requests, 0 included below; oldest blocked for > 37.391632 secs
2021-12-10 13:47:03.742 7f85bc565700  1 mds.mds003 Updating MDS map to version 5570 from mon.0
2021-12-10 13:47:03.809 7f85bc565700  1 mds.mds003 Updating MDS map to version 5571 from mon.0
2021-12-10 13:47:23.525 7f85ba561700  0 log_channel(cluster) log [WRN] : 1 slow requests, 0 included below; oldest blocked for > 57.174554 secs
2021-12-10 13:47:28.676 7f85ba561700  0 log_channel(cluster) log [WRN] : 1 slow requests, 1 included below; oldest blocked for > 62.325752 secs
2021-12-10 13:47:28.676 7f85ba561700  0 log_channel(cluster) log [WRN] : slow request 62.325749 seconds old, received at 2021-12-10 13:46:26.351080: rejoin:client.119991:223081 currently dispatched
2021-12-10 13:47:32.291 7f85bc565700  1 mds.3.openfiles next_prefetch_dirfrags continue
```

**Comment by lxbsz** [comment]
> FYI. The logs below have been captured when the number of dirs to be fetched is set 500. It takes about 30 seconds to read 500 dirs from the OMAP layer. You can check `next_prefetch_dirfrags` message.
> 

BTW, have you included https://github.com/lxbsz/ceph/commit/5233045d5c4b8842ccedec158ab0c3f035d26817 for this ?

**Comment by yongseokoh** [comment]
> BTW, have you included [lxbsz@5233045](https://github.com/lxbsz/ceph/commit/5233045d5c4b8842ccedec158ab0c3f035d26817) for this ?
Not yet. It will be included next test run. I think calling heartbeat_reset() every callback is costly. Does it affect the performance drop?

**Comment by lxbsz** [comment]
> 



> > BTW, have you included [lxbsz@5233045](https://github.com/lxbsz/ceph/commit/5233045d5c4b8842ccedec158ab0c3f035d26817) for this ?
> 
> Not yet. It will be included next test run. I think calling heartbeat_reset() every callback is costly. Does it affect the performance drop?

You can check the `MDSContext::que finished_queue`, in `MDSRank::_advance_queues()` it's doing the same too. I think we couldn't be sure that what the completion callback will do and how long will it take to finish, IMO kicking the heartbeat timer is needed and it shouldn't affect the perf much.

@vshankar @batrick Any advice about this ?

**Comment by yongseokoh** [comment]
With set to 100 callbacks, heartbeat timeout doesn't happen.

```
2021-12-13 19:02:52.371 7f83e18d1700  1 mds.2.openfiles _prefetch_dirfrags start
2021-12-13 19:02:52.373 7f83e18d1700  1 mds.2.openfiles _prefetch_dirfrags make fetch_queue done size 1660
2021-12-13 19:02:52.384 7f83e18d1700  1 mds.2.openfiles _next_prefetch_dirfrags continue fetch_queue size 1560
2021-12-13 19:02:52.384 7f83e18d1700  1 mds.2.openfiles _open_ino_finish done prefetch_state 2
2021-12-13 19:02:56.405 7f83db0c4700  1 mds.2.openfiles _next_prefetch_dirfrags continue fetch_queue size 1460
2021-12-13 19:03:03.965 7f83e18d1700  1 mds.2.openfiles _next_prefetch_dirfrags continue fetch_queue size 1360
2021-12-13 19:03:10.994 7f83e18d1700  1 mds.2.openfiles _next_prefetch_dirfrags continue fetch_queue size 1260
2021-12-13 19:03:17.660 7f83db0c4700  1 mds.2.openfiles _next_prefetch_dirfrags continue fetch_queue size 1160
2021-12-13 19:03:24.053 7f83db0c4700  1 mds.2.openfiles _next_prefetch_dirfrags continue fetch_queue size 1060
2021-12-13 19:03:30.484 7f83e18d1700  1 mds.2.openfiles _next_prefetch_dirfrags continue fetch_queue size 960
2021-12-13 19:03:37.047 7f83db0c4700  1 mds.2.openfiles _next_prefetch_dirfrags continue fetch_queue size 860
2021-12-13 19:03:43.696 7f83e18d1700  1 mds.2.openfiles _next_prefetch_dirfrags continue fetch_queue size 760
2021-12-13 19:03:50.709 7f83e18d1700  1 mds.2.openfiles _next_prefetch_dirfrags continue fetch_queue size 660
2021-12-13 19:03:57.265 7f83e18d1700  1 mds.2.openfiles _next_prefetch_dirfrags continue fetch_queue size 560
2021-12-13 19:04:03.997 7f83db0c4700  1 mds.2.openfiles _next_prefetch_dirfrags continue fetch_queue size 460
2021-12-13 19:04:10.812 7f83e18d1700  1 mds.2.openfiles _next_prefetch_dirfrags continue fetch_queue size 360
2021-12-13 19:04:17.454 7f83db0c4700  1 mds.2.openfiles _next_prefetch_dirfrags continue fetch_queue size 260
2021-12-13 19:04:23.984 7f83db0c4700  1 mds.2.openfiles _next_prefetch_dirfrags continue fetch_queue size 160
2021-12-13 19:04:30.680 7f83db0c4700  1 mds.2.openfiles _next_prefetch_dirfrags continue fetch_queue size 60
2021-12-13 19:04:37.469 7f83e18d1700  1 mds.2.openfiles _next_prefetch_dirfrags continue fetch_queue size 0
2021-12-13 19:04:41.555 7f83e18d1700  1 mds.2.openfiles _prefetch_inodes state 3
2021-12-13 19:04:41.560 7f83e18d1700  1 mds.2.openfiles _prefetch_inodes finish state 3 num_opening_inodes 1
2021-12-13 19:04:41.560 7f83e18d1700  1 mds.2.openfiles _open_ino_finish start prefetch_state 3
```

**Comment by yongseokoh** [comment]
With https://github.com/lxbsz/ceph/commit/5233045d5c4b8842ccedec158ab0c3f035d26817, heartbeat timeout doesn't happen as well.

```
2021-12-11 18:54:27.991 7fe64b13e700  1 mds.1.openfiles _prefetch_dirfrags start
2021-12-11 18:54:27.992 7fe64b13e700  1 mds.1.openfiles _prefetch_dirfrags make fetch_queue done size 1606
2021-12-11 18:54:28.267 7fe64b13e700  1 mds.1.openfiles next_prefetch_dirfrags continue fetch_queue size 0
2021-12-11 18:54:28.267 7fe64b13e700  1 mds.1.openfiles _open_ino_finish done prefetch_state 2
2021-12-11 18:55:28.134 7fe64b13e700  1 mdsmds004 Updating MDS map to version 1941 from mon.1
2021-12-11 18:56:12.246 7fe644931700  1 mds.1.openfiles _prefetch_inodes state 3
2021-12-11 18:56:12.250 7fe644931700  1 mds.1.openfiles _prefetch_inodes finish state 3 num_opening_inodes 1
2021-12-11 18:56:12.250 7fe644931700  1 mds.1.openfiles _open_ino_finish start prefetch_state 3
```

**Comment by vshankar** [comment]
> You can check the `MDSContext::que finished_queue`, in `MDSRank::_advance_queues()` it's doing the same too. I think we couldn't be sure that what the completion callback will do and how long will it take to finish, IMO kicking the heartbeat timer is needed and it shouldn't affect the perf much.
> 
> @vshankar @batrick Any advice about this ?

Am I correct in understanding that the heartbeat timeouts happen in places where we call into rados to fetch (or update) objects (like fetching lots of dirfrags in this case)? If this is true, there are various places where a heartbeat timeout can be missed since the MDS would wait for the call to return holding the mds_lock.

**Comment by lxbsz** [comment]
> With set to 100 callbacks, heartbeat timeout doesn't happen.
> 

I am afraid this issue still will happen even with 100 callbacks in some cases, such as if the OSDes are in heavy load and a little slow or the dirfrags are large enough and will take a longer time to finish.

**Comment by lxbsz** [comment]
> Am I correct in understanding that the heartbeat timeouts happen in places where we call into rados to fetch (or update) objects (like fetching lots of dirfrags in this case)? If this is true, there are various places where a heartbeat timeout can be missed since the MDS would wait for the call to return holding the mds_lock.

No, it's not holding the `mds_lock` will cause this issue here. The root cause is that when fetching a lot of dirfrags in up:rejoin the `Finisher` thread probably will fire all or most of the fetch callbacks continuously without being scheduled out. Each callback will acquire/release the `mds_lock` here, please see `Line#102` below:

```
 94 void MDSIOContextBase::complete(int r) {                                                                                                           
 95   MDSRank *mds = get_mds();
 96    
 97   dout(10) << "MDSIOContextBase::complete: " << typeid(*this).name() << dendl;
 98   ceph_assert(mds != NULL);    
 99   // Note, MDSIOContext is passed outside the MDS and, strangely, we grab the
100   // lock here when MDSContext::complete would otherwise assume the lock is
101   // already acquired.
102   std::lock_guard l(mds->mds_lock);
103 
104   if (mds->is_daemon_stopping()) {
105     dout(4) << "MDSIOContextBase::complete: dropping for stopping "
106             << typeid(*this).name() << dendl;
107     return;
108   }
...
```

Our previous mds_lock fair mutex related fixing will alleviate this issue, but couldn't fix it thoroughly.

So we need to make sure the Finisher thread could kick the heartbeat in long time running case.

**Comment by vshankar** [comment]
> No, it's not holding the `mds_lock` will cause this issue here. The root cause is that when fetching a lot of dirfrags in up:rejoin the `Finisher` thread probably will fire all or most of the fetch callbacks continuously without being scheduled out.

I meant the same thing - mds_lock being held for long with calling into heartbeat_reset. In that case https://github.com/lxbsz/ceph/commit/5233045d5c4b8842ccedec158ab0c3f035d26817 seems to be the correct approach.

**Comment by yongseokoh** [comment]
I was looking for a solution to this tineout issue. I didn't know the proper location of heartbeat_reset to relieve. https://github.com/lxbsz/ceph/commit/5233045d5c4b8842ccedec158ab0c3f035d26817 is simpler.

**Comment by lxbsz** [comment]
> > No, it's not holding the `mds_lock` will cause this issue here. The root cause is that when fetching a lot of dirfrags in up:rejoin the `Finisher` thread probably will fire all or most of the fetch callbacks continuously without being scheduled out.
> 
> I meant the same thing - mds_lock being held for long with calling into heartbeat_reset. In that case [lxbsz@5233045](https://github.com/lxbsz/ceph/commit/5233045d5c4b8842ccedec158ab0c3f035d26817) seems to be the correct approach.

Yeah, I think https://github.com/lxbsz/ceph/commit/5233045d5c4b8842ccedec158ab0c3f035d26817 could also fix other potential similar issues.

@yongseokoh You can pick https://github.com/lxbsz/ceph/commit/5233045d5c4b8842ccedec158ab0c3f035d26817 in this PR.

**Comment by lxbsz** [comment]
> I was looking for a solution to this tineout issue. I didn't know the proper location of heartbeat_reset to relieve. [lxbsz@5233045](https://github.com/lxbsz/ceph/commit/5233045d5c4b8842ccedec158ab0c3f035d26817) is simpler.

Before we have hit a similar issue, that is the unfair mutex for `mds_lock` could let one thread keep running for a very long time.

**Comment by yongseokoh** [comment]
> @yongseokoh You can pick [lxbsz@5233045](https://github.com/lxbsz/ceph/commit/5233045d5c4b8842ccedec158ab0c3f035d26817) in this PR.

lxbsz@5233045 has been cherry-picked and my commits have been removed in this PR.

**Review by lxbsz — APPROVED** [review]

**Review by vshankar — APPROVED** [review]

**Comment by vshankar** [comment]
https://tracker.ceph.com/projects/cephfs/wiki/Master#2022-Jan-03

**Pull request merged**
