### PR TITLE
nautilus: mgr/prometheus: replace whitespaces in metrics' names

### PR DESCRIPTION
**Pull request by alfonsomthd**
https://tracker.ceph.com/issues/39459

### CODE REVIEW

**Comment by b-ranto** [comment]
Hey Alfonso, any plans on back-porting the PR that removes the spaces from the rgw perf counters?

**Comment by alfonsomthd** [comment]
> Hey Alfonso, any plans on back-porting the PR that removes the spaces from the rgw perf counters?

@theanalyst Any updates on this?

**Comment by cbodley** [comment]
@alfonsomthd pr https://github.com/ceph/ceph/pull/27725 was associated with the same tracker issue https://tracker.ceph.com/issues/39434, so it's probably best for you to cherry-pick it into this pr

**Comment by alfonsomthd** [comment]
> please cherry-pick [97fb4ee](https://github.com/ceph/ceph/commit/97fb4eeae0e69ad4778ca6d38221a776cad39f6f) into this PR as requested by @cbodley

Hi @cbodley @smithfarm It seems that commit d611fe9954d234ae15345cc99eb705ecbb03964f
is not backported to nautilus branch, so file "src/rgw/rgw_sync_counters.cc" does not exist.
How should we proceed?

**Comment by cbodley** [comment]
oops, thanks @alfonsomthd. i just did the backport for that in https://github.com/ceph/ceph/pull/27921, and pulled in the extra commit https://github.com/ceph/ceph/commit/97fb4eeae0e69ad4778ca6d38221a776cad39f6f there

**Pull request merged**
