### PR TITLE
nautilus: librbd: improve journal performance to match expected degredation

### PR DESCRIPTION
**Pull request by dillaman**
https://tracker.ceph.com/issues/40511

### CODE REVIEW

**Comment by dillaman** [comment]
retest this please

**Comment by trociny** [comment]
@dillaman Don't we need 340726ec8 too? Although it fixes 83461c42b, which is not backported, your changes provide the logic -- overflow detection. And it seems the situation is still possible that buffer is empty when overflow is detected and flush may complete when "advance object set" is still in flight.

And if we need 340726ec8, then although 83461c42b is not necessary because it is rewritten, may be it makes sense to cherry-pick it too to just to have less conflicts? I suppose it would be much easier for review.

**Comment by dillaman** [comment]
... sure, I can do that.

**Comment by dillaman** [comment]
@trociny update pushed

**Comment by yuriw** [comment]
[wip-yuri3-testing-2019-08-19-1619-nautilus](https://trello.com/c/m0BVlUfw/694-wip-yuri3-testing-2019-08-19-1619-nautilus)

**Pull request merged**
