### PR TITLE
mon/LogMonitor: Fix mon_cluster_log_file_level

### PR DESCRIPTION
**Pull request by pdvian**
After code refactoring of LogMonitor::update_from_paxos
(commit : 7c84e06e6f84), Controlling the verbosity of
cluster logs which are getting logged to the cluster log
file is broken. Allow logging of a log entry to the
cluster log file if le.prio >= mon_cluster_log_file_level.

Fixes: https://tracker.ceph.com/issues/57049

Signed-off-by: Prashant D <pdhange@redhat.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Review by sseshasa — COMMENTED** [review]
It will probably be helpful for tracking purposes to include the refactoring commit details in the commit message that resulted in the original behavior to break.

**Review by sseshasa — APPROVED** [review]
Apart from my comment related to include the refactoring commit, the changes LGTM.

**Comment by pdvian** [comment]
> Apart from my comment related to include the refactoring commit, the changes LGTM.

Thanks @sseshasa. I have added relevant refactoring commit id in the commit message. We probably need to close this PR in favor of PR#47502.

**Comment by vumrao** [comment]
jenkins retest this please

**Comment by rzarzynski** [comment]
jenkins test api

**Comment by pdvian** [comment]
Close this PR in favor of PR #47502.

**Pull request closed without merging**
