### PR TITLE
rgw: append user policies to existing policies

### PR DESCRIPTION
**Pull request by theanalyst**
Drop emptiness check and then appending to the policy

Signed-off-by: Abhishek Lekshmanan <abhishek@suse.com>

### CODE REVIEW

**Comment by adamemerson** [comment]
Jenkins, retest this please.

**Comment by theanalyst** [comment]
jenkins test this please

**Comment by theanalyst** [comment]
unstale me

**Comment by ivancich** [comment]
jenkins test docs.*

**Comment by ivancich** [comment]
@theanalyst Should this get backports and therefore does it need a tracker?

**Comment by ivancich** [comment]
QA results:
- http://pulpito.ceph.com/ivancich-2020-06-08_20:10:46-rgw-wip-eric-testing-1-distro-basic-smithi/
- http://pulpito.ceph.com/ivancich-2020-06-08_20:11:05-rgw-wip-eric-testing-1-distro-basic-smithi/

**Pull request merged**
