### PR TITLE
mgr: improvements for dynamic osd perf counters

### PR DESCRIPTION
**Pull request by trociny**
And process collected stats accordingly.

Signed-off-by: Mykola Golub <mgolub@suse.com>

- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by trociny** [comment]
BTW, interesting result when writing to a journaling image:
```
adonis:~/ceph/ceph/build% rbd bench -p rbd --io-type write --io-threads 1 --rbd-cache=false --io-size 4K --io-total 1024K test
bench  type write io_size 4096 io_threads 1 bytes 1048576 pattern sequential
  SEC       OPS   OPS/SEC   BYTES/SEC
    1        33     34.69  142108.81
    2        66     33.43  136944.71
    3        98     33.04  135351.03
    4       131     33.03  135305.87
    5       163     32.91  134782.65
    6       197     32.77  134243.95
    7       230     32.91  134782.65
elapsed:     7  ops:      256  ops/sec:    32.82  bytes/sec: 134435.37
adonis:~/ceph/ceph/build% ceph osd perf counters get 0                                                                        
counters for the query id 0 for the last 45 sec
+---------+--------------+-----------+----------+-----------------+----------------+---------------------+--------------------+
| pool_id | rbd image_id | write_ops | read_ops | write_bytes/sec | read_bytes/sec | write_latency(msec) | read_latency(msec) |
+---------+--------------+-----------+----------+-----------------+----------------+---------------------+--------------------+
|    1    | 104753c5c90e |    514    |   266    |     45.18Ki     |    334.47Ki    |        12.51        |       13.43        |
+---------+--------------+-----------+----------+-----------------+----------------+---------------------+--------------------+
adonis:~/ceph/ceph/build% ceph osd perf counters get 1
counters for the query id 1 for the last 48 sec
+-------------+------------------------------+---------+-----------+--------+-------+----------------------------------------+---------+-----------+----------+
|  client_id  |        client_address        | pool_id | namespace | osd_id | pg_id |              object_name               | snap_id | write_ops | read_ops |
+-------------+------------------------------+---------+-----------+--------+-------+----------------------------------------+---------+-----------+----------+
| client.4640 | 10.100.96.59:56312/891592970 |    1    |           |   0    |  1.1b |     journal_data.1.104753c5c90e.15     |   head  |     64    |    66    |
| client.4640 | 10.100.96.59:56312/891592970 |    1    |           |   0    |  1.1c |     journal_data.1.104753c5c90e.12     |   head  |     65    |    67    |
| client.4640 | 10.100.96.59:56312/891592970 |    1    |           |   1    |  1.0  |        rbd_header.104753c5c90e         |   head  |     5     |    19    |
| client.4640 | 10.100.96.59:56312/891592970 |    1    |           |   1    |  1.1a |                rbd_info                |   head  |     0     |    1     |
| client.4640 | 10.100.96.59:56312/891592970 |    1    |           |   1    |  1.3  | rbd_data.104753c5c90e.0000000000000000 |   head  |    256    |    0     |
| client.4640 | 10.100.96.59:56312/891592970 |    1    |           |   1    |  1.8  |          journal.104753c5c90e          |   head  |     5     |    24    |
| client.4640 | 10.100.96.59:56312/891592970 |    1    |           |   1    |  1.8  |     journal_data.1.104753c5c90e.13     |   head  |     65    |    67    |
| client.4640 | 10.100.96.59:56312/891592970 |    1    |           |   2    |  1.14 |      rbd_object_map.104753c5c90e       |   head  |     2     |    3     |
| client.4640 | 10.100.96.59:56312/891592970 |    1    |           |   2    |  1.18 |     journal_data.1.104753c5c90e.14     |   head  |     64    |    66    |
| client.4640 | 10.100.96.59:56312/891592970 |    1    |           |   2    |  1.18 |              rbd_id.test               |   head  |     0     |    2     |
+-------------+------------------------------+---------+-----------+--------+-------+----------------------------------------+---------+-----------+----------+
```
So the query counts many read ops to journal. Some are real journal object reads, but the most I believe are due to journal.guard_append, which mark the ops read-write. Do we want to improve this somehow in `DynamicPerfStats::add`? For example we could skip adding the op to reads, if it  is `op.may_read()` but `outb` is 0? But then I suppose we will have a wrong stats when reading from an empty object region.

**Comment by trociny** [comment]
Another interesting question illustrated by this PR is that with the current perf query implementation and the proposed object_name regex, for journaling case we will have two keys per image (one for data and one for journal), which is probably not very good if a limit is used.

I don't see how the regex could be modified so both rbd_data and journal_data objects gave the same key for an image. It could be solved though if we built the key with matches[1..n] (group matches), that is skipping matches[0] (full regex match). That would require that a query regex had to have at least one group.

**Comment by dillaman** [comment]
@trociny I think it's OK that the journal stat is treated as a read op. If the journal object context isn't in the OSD's in-memory cache, it would require a disk hit. 

As for rbd_data / journal_data causing two different keys, I can really only think of kludgy fixes. If you could group sub-keys (where all sub-keys in a group need to match), you could perhaps have something like the following that either uses the pool_id and image_id from the object name (if the object doesn't have a pool id embedded) or falls back to extracting the pool_id from the object name as well as the image_id.

```
'key_descriptor': [
  [
    {'type': 'pool_id', 'regex': '^.+$'},
    {'type': 'object_name', 'regex': '^(?:rbd|journal)_data\.([^.]+)\.[^.]+$'}
  ],
  [
    {'type': 'object_name', 'regex': '^(?:rbd|journal)_data\.([0-9]+)\.[^.]+\.'},
    {'type': 'object_name', 'regex': '^(?:rbd|journal)_data\.[0-9]+\.([^.]+)\.'}
  ],
]
```

You could also support replacing empty match groups with metavariables:
```
'key_descriptor': [
  {'type': 'object_name', 'regex': '^(?:rbd|journal)_data\.([^.]+)\.[^.]+$',
   regex-group-defaults: {1: {type: 'pool_id'}}}
]
```

**Comment by trociny** [comment]
Ah, I forgot about pool id. I thought the only problem that made 2 keys was rbd_data/journa_data prefixes. The pool id complicates it much more. So I'd rather leave it  as it is now (two keys for journaling images) and did not complicate query rules, if it looked ok for you too.

**Comment by dillaman** [comment]
> I thought the only problem that made 2 keys was rbd_data/journa_data prefixes

Do you compare the full match string or just the capture groups? I wonder if it would make more sense to only group keys on capture groups (if present) since if you wanted the prefixes, you could just capture them as well.

**Comment by trociny** [comment]
> Do you compare the full match string or just the capture groups? I wonder if it would make more sense to only group keys on capture groups (if present) since if you wanted the prefixes, you could just capture them as well.

Yes, it is exactly what I proposed earlier when I thought the problem was only with the prefix -- don't push `match[0]` in the sub_key array here [1]. `match[0]` is redundant, it is probably nice to use it in many cases like pool_id match, but is not necessary. If you think it makes sense I will push an additional PR that remove `match[0]` and updates all affected query usage cases.

[1] https://github.com/ceph/ceph/blob/master/src/osd/DynamicPerfStats.h#L156

**Comment by trociny** [comment]
@dillaman updated: changed to include only captured groups in subkeys and fixed some regressions.

**Pull request merged**
