### PR TITLE
osd: OSD device smart data include additional nvme data

### PR DESCRIPTION
**Pull request by hsiang41**
Add nvme addition data into the deveh health data. That use nvme tool
and command syntax "nvme \<vendor\> smart-log-add \<dev\> -json". The nvme
json output append in the dev smart "nvme_smart_health_information_add_log".

Signed-off-by: Rick Chen <rick.chen@prophetstor.com>

- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by hsiang41** [comment]
@liewegas Please help me review my changed.

**Comment by hsiang41** [comment]
retest this please.

**Comment by liewegas** [comment]
rebased and incorporated into https://github.com/ceph/ceph/pulls/liewegas

**Comment by liewegas** [comment]
https://github.com/ceph/ceph/pull/25672 rather

**Pull request closed without merging**
