### PR TITLE
luminous: osd: do_sparse_read(): Verify checksum earlier so we will try to repair and missed backport

### PR DESCRIPTION
**Pull request by dzafman**
Includes backport of https://github.com/ceph/ceph/pull/18353

### CODE REVIEW

**Comment by dzafman** [comment]
dzafman-2018-08-02_11:15:32-rados-wip-zafman-testing-luminous-distro-basic-smithi
[2853581]  "cluster [ERR] 5.bs0 shard 2(0) missing" in log trashing ec-radosbench
[2853684]  REQUEST_SLOW writing rados bench
[2853838]  Dead - Infrastructure locking machines

**Comment by dzafman** [comment]
@smithfarm ceph/ceph#23377 has merged

**Comment by yuriw** [comment]
[wip-yuri4-testing-2018-08-07-2054-luminous](https://trello.com/c/D7QGdxAl/368-wip-yuri4-testing-2018-08-07-2054-luminous)

**Comment by yuriw** [comment]
@dzafman pls add `needs-qa` and `12.2.8` when addressed @smithfarm request

**Comment by dzafman** [comment]
@smithfarm Master pull request has merged, and I verified sha1s

**Comment by dzafman** [comment]
@yuriw Didn't you already test this and removed the needs-qa?  I added it back per your latest comment but nothing has changed.

**Pull request merged**
