### PR TITLE
various python 3.12 fixes

### PR DESCRIPTION
**Pull request by phlogistonjohn**
The goal for this set of patches was to get all default tox envs (so `tox r`) succeeding for src/{pybind/mgr,python-common,cephadm} for python 3.12.

Most of these changes are mechanical and should be pretty obvious. None of them should change any behavior. In a couple places I took the opportunity to update the type annotations from comments to actual annotations. But in some cases I simply did `noqa` hacks if the file had lots of old style comments and/or it was a file largely unfamiliar to me.

One judgement call that I made was to not pin the flake8 version in all tox.ini files. src/pybind/mgr was alredy this way. The other two were both using old versions of flake8 that caused it to do strange things like consider backtick characters in fstrings as invalid (it was treating the entire f-string, not just the embedded expressions like python code AFAICT).
An alternative would be to continue to pin flake8, but do so with a version that is newer, python3.12 compatible, and consistent across the subtrees. IMO, that's more work in the short term as well as more work in thel long term because somebody needs to keep on top of it (like we were not doing).
If we want to argue about something, we can argue about that. :-)

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [x] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [x] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), <s>opened tracker ticket</s>
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No NEW tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Comment by phlogistonjohn** [comment]
jenkins test make check

**Comment by phlogistonjohn** [comment]
note: having working python 3.12 support is needed to build/test on ubuntu 24.04 as it ships with python 3.12:
```
$ podman run --rm -it ceph-build:jjm-containerized-build-pyalt.ubuntu24.04  python3 --version
Python 3.12.3
```

**Comment by phlogistonjohn** [comment]
jenkins test windows

**Comment by adk3798** [comment]
https://pulpito.ceph.com/adking-2024-11-19_02:02:13-orch:cephadm-wip-adk-testing-2024-11-18-1758-distro-default-smithi/

Failures:

- lots of upgrade failures, primarily because the dashboard cherrypy backports issue fix was still not present in reef when these tests ran
- 1 `MON_DOWN` cluster log warning, seen this before, need to update the ignoreslist for this test
- 1 selinux denial failure in an smb ctdb test, known issue
- 2 new mgmt-gateway tests being added by a PR in the run failed
- 1 strange failure applying an SMB spec. Seems like it could be a bug that is just rarely hit in that test, as no SMB related PRs were included in the run

I wouldn't merge any SMB changes or the new tests off of this run, but otherwise it's okay.

**Review by adk3798 — APPROVED** [review]

**Pull request merged**
