### PR TITLE
crimson/osd/ops_executor: apply delta stats for pure read ops

### PR DESCRIPTION
**Pull request by xxhdx1985126**
Signed-off-by: Xuehan Xu <xxhdx1985126@gmail.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [x] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Review by Matan-B — COMMENTED** [review]
Can we apply the stats unconditionally for both read/write without `else`? (by moving `apply_stats` from l.477 to l.486?)

**Comment by xxhdx1985126** [comment]
> Can we apply the stats unconditionally for both read/write without `else`? (by moving `apply_stats` from l.477 to l.486)

Yeah, modified and repushed.

**Review by athanatos — APPROVED** [review]

**Comment by Matan-B** [comment]
jenkins test docs

**Comment by Matan-B** [comment]
jenkins test api

**Comment by Matan-B** [comment]
Test results  LGTM
http://pulpito.front.sepia.ceph.com/matan-2023-02-12_11:21:05-crimson-rados-wip-matanb-crimson-only-testing-12.2-distro-crimson-smithi/
```
4f02cb2d3f6 Merge branch 'wip-crimson-obcregistry-per-pg' into wip-matanb-crimson-only-testing-12.2                                                   
24c60d130cd Merge branch 'wip-sync-peering-backfill' into wip-matanb-crimson-only-testing-12.2                         
e9c09fdf42d Merge branch 'wip-pg-remove' into wip-matanb-crimson-only-testing-12.2                                     
4d1f67b1b6c Merge branch 'wip-obc-watchers-checkonload' into wip-matanb-crimson-only-testing-12.2                      
c014aa5ee0f Merge branch 'wip-pg-stats-read' into wip-matanb-crimson-only-testing-12.2                                 
74179c8ba76 Merge branch 'wip-matanb-c-pg-pipeline' into wip-matanb-crimson-only-testing-12.2                          
02b59b3ed3f Merge branch 'wip-crimson-fix-zeroed-startevent' into wip-matanb-crimson-only-testing-12.2  
```

**Comment by Matan-B** [comment]
jenkins test api

**Pull request merged**
