### PR TITLE
FileStore: remove unnecessary get_index call

### PR DESCRIPTION
**Pull request by wonzhq**
Signed-off-by: Zhiqiang Wang <zhiqiang.wang@intel.com>

### CODE REVIEW

**Comment by yuyuyu101** [comment]
The deleted codes are aimed to ensure the acquired object is existed.

**Comment by wonzhq** [comment]
> yuyuyu101 commented 15 hours ago
> The deleted codes are aimed to ensure the acquired object is existed. Although I can't remember the actual corner case of this.

This should already be done in lfn_open at the beginning of these functions.

**Comment by dachary** [comment]
@wonzhq could you explain why it is redundant, in detail, in the commit message ? It will help people reading this patch in the future as well as the review. As it is, as @yuyuyu101 pointed out, it is a little mysterious ;-)

**Comment by wonzhq** [comment]
Sure, I'll add it.

**Comment by yuyuyu101** [comment]
@liewegas What do you think of this patch? In my idea, it will be right if remove it but it may destroy the ObjectStore serious semantic? For example, actually Index is represented to protect any op associated to this object, but in current impl the Index isn't really needed because of upper constraints.

**Comment by liewegas** [comment]
I think we've already gone down the road where the upper layer is responsible for isolation in that writes will be fed to different Sequencers.  For read vs write, its mostly teh OSD's responsibility to flush writes before reads for a given object, but in a few cases we do unlocked reads and are okay getting the old or new value.  As long as we get *something* though and don't crash or something..

I think that's right.. @athanatos ?

**Comment by yuyuyu101** [comment]
@liewegas I only concern it may broken origin design principle and destroy something corner by accident.

I prefer we don't change it(it can't really improve much for performance?) now and redesign the new backend for KeyFileBackend and apply new ideas to it?

**Comment by liewegas** [comment]
Agreed.

**Pull request closed without merging**
