### PR TITLE
FileJournal：delete FULL_WAIT state

### PR DESCRIPTION
**Pull request by jack-changtao**
For file joural , I think  FULL_WAIT of file journal state is useless

### CODE REVIEW

**Comment by branch-predictor** [comment]
Can you explain why it is useless?

**Comment by jack-changtao** [comment]
@branch-predictor 
I am not sure about this, because I am not sure of  FULL_WAIT state is usefull ?

**Comment by branch-predictor** [comment]
This code was added to handle the case when journal was filled up and no space is left for new journal entries - in that case, entries will not be written to disk but queued and written once some space will be reclaimed. Once you remove this code, journaling will be no longer reliable in that case.
Also, you removed a call to journal->commit_start() in JournalingObejctstore which will prevent committing changes to underlying journal if there's any.

**Comment by jack-changtao** [comment]
@branch-predictor 

Thanks for you reply! 

I still has some confused!   Every time before journal write, it calls check_for_full to check journal space. If it has no journal space, the journal entry is still on writeq and will be written once some space will be reclaimed.

why " journaling will be no longer reliable" ?

**Comment by branch-predictor** [comment]
@jack-changtao FULL_WAIT causes journaling code to keep flushing entries while still queuing new entries (i. e. remains in state similar to FULL_FULL, except it actually isn't full anymore). See the description of FULL_WAIT in original comment:
```
  /*
   * full states cycle at the beginnging of each commit epoch, when commit_start()
   * is called.
   *   FULL - we just filled up during this epoch.
   *   WAIT - we filled up last epoch; now we have to wait until everything during
   *          that epoch commits to the fs before we can start writing over it.
   *   NOTFULL - all good, journal away.
   */
```

**Comment by jack-changtao** [comment]
@branch-predictor 

sorry， I still can‘t got it. If it is remote, what is   "no longer reliable" it will happen? can you gave a use case ? Thanks very much !

**Comment by branch-predictor** [comment]
@jack-changtao I gave an use case above (ensuring that once journal gets filled up, it will be emptied entirely before accepting new entry).

**Comment by jack-changtao** [comment]
@branch-predictor 

Once journal gets filled up , the journal commit will wait untill there is space.
The journal should be trimmed all if it all has been applied!

**Comment by jack-changtao** [comment]
@liewegas  @yuyuyu101  @XinzeChi   

Do you have time to review this ?  or point out the state FULL_WAIT use ?

Thanks very much !

**Comment by athanatos** [comment]
It's necessary for some annoying parallel journaling edge case iirc.  If the journal fills up and the filesystem actually write ahead of the current journal state, we need to sync twice for some reason.

**Pull request closed without merging**
