### PR TITLE
rgw: stop bucket lease only after draining object sync operations

### PR DESCRIPTION
**Pull request by yehudasa**
Fixes: http://tracker.ceph.com/issues/16143

Signed-off-by: Yehuda Sadeh <yehuda@redhat.com>

### CODE REVIEW

**Comment by yehudasa** [comment]
@cbodley I added a couple of commits here, probably needs retesting

**Comment by cbodley** [comment]
@yehudasa ok! there were some environmental failures in the last run, so it needs another run anyway

**Comment by theanalyst** [comment]
I kind of saw the resync issue again after applying :/ logs at weekend, logs at id: 38727c3e-abac-481b-a8ae-6657df972e40 didn't see a lot of occurences of `squash` kick in though

**Comment by yehudasa** [comment]
@theanalyst did it converge correctly eventually? Resync is expected to happen a bit, can only be solved completely with tombstones.

**Comment by theanalyst** [comment]
@yehudasa yeah this time it didn;t converge to a deletion for this one object.. it ended being still present

**Comment by yehudasa** [comment]
@theanalyst can you provide the bucket index log entries for both zones? e.g., `radosgw-admin bilog list --rgw-zone=... --bucket=...`
also, is doing any write operation on that bucket (e.g., create a new object there) makes any difference wrt object7?

**Comment by theanalyst** [comment]
@yehudasa zone-> secondary (where the obj. was uploaded) http://ix.io/PzU
zone-> primary http://ix.io/PzV

**Comment by yehudasa** [comment]
@theanalyst Can you add this commit and reproduce?
https://github.com/ceph/ceph/pull/9531/commits/97ef16c0cc0ad8345b5a897108717d83ab0aa9ab

Should make things easier to understand.

**Comment by theanalyst** [comment]
@yehudasa new run: 48892640-ff00-4da6-80a2-23d917a0d14d object8 bucket: trial4 I've put in the bilogs in the same folder

**Comment by yehudasa** [comment]
@theanalyst the uploaded file is corrupt, can you resend it?

**Comment by theanalyst** [comment]
@yehudasa 8e45a219-1f65-4960-ab0e-5b41722656ee

**Comment by yehudasa** [comment]
@theanalyst I think I tracked down the issue. It seems that some operations aren't recorded on the bucket index because of the dir_suggest mechanism. I'll work on a fix.

**Comment by theanalyst** [comment]
@yehudasa nice to hear that :)

**Comment by yehudasa** [comment]
@theanalyst pushed a few more commits to deal with the dir_suggest issue.

**Comment by theanalyst** [comment]
@yehudasa still seeing the issue.. posted 61779d0d-016f-443f-b23e-689ed13b1089 (trial1/object5)

**Comment by cbodley** [comment]
teuthology run was clean, but didn't include those last 3 cls commits

**Comment by yehudasa** [comment]
@theanalyst did you restart osds? Change is also in objclass

**Comment by theanalyst** [comment]
@yehudasa yeah it was a fresh run, new cluster 90ab9ca (today's master) + this pr and the logging one. the issue is no longer always reproducible though, but still seeing it once in a few runs

**Comment by yehudasa** [comment]
@theanalyst that tarball is corrupt again

**Comment by yehudasa** [comment]
@cbodley @theanalyst pushed two more commits. I haven't tested this one much, but it adds a tombstone cache that should hopefully improve things. @cbodley please take over this

**Comment by theanalyst** [comment]
@yehudasa uploaded the old log again at 83c5c718-711c-4374-aa8b-926f8750f3d5, I haven't yet tried after the 2 new commits you've pushed though

**Comment by cbodley** [comment]
@theanalyst i'm catching up on the "RGW Multisite delete wierdness" thread to help with this. is this script the most reliable way to reproduce?
```
for i in {1..20}; do s3 -us put foobar/foo$i filename=test.img && sleep 3 && s3 -us delete foobar/foo$i;  done
```

**Comment by theanalyst** [comment]
@cbodley yeah I used a script like this pretty much.. only that the sleep 3 might be too much if it is say a vstart cluster on an SSD, try reducing the sleep to 2 or 1.5 range.. basically the sleep should sort of allow for the remote zone to atleast get the head object or something like this before the primary gets a delete req.

**Comment by theanalyst** [comment]
@yehudasa @cbodley still seeing the same issue with the newer commits as well (id: 881df5cc-ba83-433d-8152-b8cc781e66e7 ) (trial1/object1)

**Comment by cbodley** [comment]
@theanalyst finally got a chance to look through your logs. i traced trial1:object1 through sync, and see the tombstone code trigger on radosgw.8001 to send a correct `HTTP_IF_MODIFIED_SINCE: 2016-06-13 15:33:16.122724430Z` header. but when radosgw.8002 gets this request, it's getting the obj_time_weight comparison wrong due to the pgv:
`If-Modified-Since: 2016-06-13 17:33:16.0.122724s[zid=771377308, pgv=0] Last-Modified: 2016-06-13 17:33:16.0.122724s[zid=771377308, pgv=91]`

**Comment by cbodley** [comment]
@theanalyst I'm happy with everything else in this branch, so I'll go ahead and merge. I'll add a fix for the pgv comparison in a separate PR.

**Pull request merged**
