### PR TITLE
osd: return EIO if object's size mismatch hinfo

### PR DESCRIPTION
**Pull request by hjwsm1989**
in ec overwrite mode

So it can read extra shards to get data but not
crash osd.

Fixes: http://tracker.ceph.com/issues/21769

Signed-off-by: huangjun <huangjun@xsky.com>

### CODE REVIEW

**Comment by hjwsm1989** [comment]
test please

**Comment by hjwsm1989** [comment]
retest this please

**Comment by hjwsm1989** [comment]
@jdurgin @dzafman  please review.

**Comment by dzafman** [comment]
@hjwsm1989 This needs a rebase.  Have this been run through testing?

**Comment by hjwsm1989** [comment]
@dzafman it didn't scheduled for QA

**Comment by dzafman** [comment]
retest this please

**Comment by liewegas** [comment]
http://pulpito.ceph.com/sage-2018-08-31_18:31:48-rados-wip-sage-testing-2018-08-31-1010-distro-basic-smithi/ (pass)

**Comment by hjwsm1989** [comment]
@dzafman sorry for late reply, i think #21611 is a good way to resolve this, will close this now

**Pull request closed without merging**
