### PR TITLE
pacific: mgr/dashboard: fix orchestrator/02-hosts-inventory.e2e failure 

### PR DESCRIPTION
**Pull request by nizamial09**
backport tracker: https://tracker.ceph.com/issues/53780

---

backport of https://github.com/ceph/ceph/pull/44388
parent tracker: https://tracker.ceph.com/issues/53499

this backport was staged using ceph-backport.sh version 16.0.0.6848
find the latest version at https://github.com/ceph/ceph/blob/master/src/script/ceph-backport.sh

### CODE REVIEW

**Comment by nizamial09** [comment]
jenkins test dashboard

**Comment by nizamial09** [comment]
jenkins test dashboard cephadm

**Review by pereman2 — APPROVED** [review]

**Comment by nizamial09** [comment]
jenkins test make check

**Review by Waadkh7 — APPROVED** [review]

**Review by alfonsomthd — APPROVED** [review]

**Comment by nizamial09** [comment]
@epuertat Looks like its good to go: https://trello.com/c/qoIF7T3R/1416-wip-yuri-testing-2022-01-07-0928-pacific

**Pull request merged**
