### PR TITLE
install-deps.sh: preload wheel for all mgr requirements.txt files

### PR DESCRIPTION
**Pull request by liewegas**
- add all mgr requirements.txt to the venv/wheel/whatever
- make scipy a build dep so that make check works

### CODE REVIEW

**Comment by callithea** [comment]
jenkins test dashboard backend

**Comment by callithea** [comment]
jenkins test dashboard

**Comment by callithea** [comment]
jenkins test dashboard

**Comment by callithea** [comment]
jenkins test dashboard

**Comment by callithea** [comment]
jenkins test dashboard

**Comment by liewegas** [comment]
jenkins test dashboard backend

**Comment by bk201** [comment]
jenkins test dashboard

**Comment by bk201** [comment]
jenkins test dashboard backend

**Comment by votdev** [comment]
I tested it locally but it does not help. I think the problem in my Docker vstart environment is that all Python packages must be installed via the systems package manager because we use the system interpreter and no venv.

**Comment by bk201** [comment]
> I tested it locally but it does not help. I think the problem in my Docker vstart environment is that all Python packages must be installed via the systems package manager because we use the system interpreter and no venv.

Yes, vstart seems using system interpreter to spawn mgr modules.
BTW, I created a PR for ceph-dev-docker: https://github.com/ricardoasmarques/ceph-dev-docker/pull/92

**Comment by liewegas** [comment]
> > I tested it locally but it does not help. I think the problem in my Docker vstart environment is that all Python packages must be installed via the systems package manager because we use the system interpreter and no venv.
> 
> Yes, vstart seems using system interpreter to spawn mgr modules.
> BTW, I created a PR for ceph-dev-docker: [ricardoasmarques/ceph-dev-docker#92](https://github.com/ricardoasmarques/ceph-dev-docker/pull/92)

I'm confused, then, because

```
> I tested it locally but it does not help. I think the problem in my Docker vstart environment is that all Python packages must be installed via the systems package manager because we use the system interpreter and no venv.

Yes, vstart seems using system interpreter to spawn mgr modules.
BTW, I created a PR for ceph-dev-docker: [ricardoasmarques/ceph-dev-docker#92](https://github.com/ricardoasmarques/ceph-dev-docker/pull/92)
```

install-deps.sh should be installing the system version...

**Comment by bk201** [comment]
> install-deps.sh should be installing the system version...

Is it because scipy is in `Requires:` section but not in `BuildRequires:` section? 
https://github.com/ceph/ceph/blob/2ad13f5d489d6ffe275bd7f03e7ee70efcf17a63/install-deps.sh#L416
https://github.com/ceph/ceph/blob/master/ceph.spec.in#L551

**Comment by liewegas** [comment]
jenkins test dashboard backend

**Comment by callithea** [comment]
jenkins test dashboard backend

**Comment by liewegas** [comment]
this breaks opensuse 15.1 build it seems.

can't tell if this fixes the scipy problem because we're now hitting
```
[15:37:23] E/protractor - Could not find Angular on page https://ceph-builders:41522/#/login : retries looking for angular exceeded
```

**Comment by callithea** [comment]
Latest dashboard backend API test run failed with:
```
Error EINVAL: Traceback (most recent call last):
  File "/home/jenkins-build/build/workspace/ceph-dashboard-pr-backend/src/pybind/mgr/mgr_module.py", line 1062, in _handle_command
    return self.handle_command(inbuf, cmd)
  File "/home/jenkins-build/build/workspace/ceph-dashboard-pr-backend/src/pybind/mgr/selftest/module.py", line 143, in handle_command
    r = self.remote(command['module'], "self_test")
  File "/home/jenkins-build/build/workspace/ceph-dashboard-pr-backend/src/pybind/mgr/mgr_module.py", line 1424, in remote
    args, kwargs)
ImportError: Module not found

2019-12-11 18:24:35,293.293 INFO:__main__:test_diskprediction_local (tasks.mgr.test_module_selftest.TestModuleSelftest) ... ERROR
2019-12-11 18:24:35,294.294 INFO:__main__:Running ['./bin/ceph', 'log', 'Ended test tasks.mgr.test_module_selftest.TestModuleSelftest.test_diskprediction_local']
2019-12-11 18:24:36,472.472 INFO:__main__:Stopped test: test_diskprediction_local (tasks.mgr.test_module_selftest.TestModuleSelftest) in 33.961712s
2019-12-11 18:24:36,473.473 INFO:__main__:
2019-12-11 18:24:36,473.473 INFO:__main__:======================================================================
2019-12-11 18:24:36,473.473 INFO:__main__:ERROR: test_diskprediction_local (tasks.mgr.test_module_selftest.TestModuleSelftest)
2019-12-11 18:24:36,473.473 INFO:__main__:----------------------------------------------------------------------
2019-12-11 18:24:36,473.473 INFO:__main__:Traceback (most recent call last):
2019-12-11 18:24:36,473.473 INFO:__main__:  File "/home/jenkins-build/build/workspace/ceph-dashboard-pr-backend/qa/tasks/mgr/test_module_selftest.py", line 51, in test_diskprediction_local
2019-12-11 18:24:36,473.473 INFO:__main__:    self._selftest_plugin("diskprediction_local")
2019-12-11 18:24:36,474.474 INFO:__main__:  File "/home/jenkins-build/build/workspace/ceph-dashboard-pr-backend/qa/tasks/mgr/test_module_selftest.py", line 34, in _selftest_plugin
2019-12-11 18:24:36,474.474 INFO:__main__:    "mgr", "self-test", "module", module_name)
2019-12-11 18:24:36,474.474 INFO:__main__:  File "../qa/tasks/vstart_runner.py", line 937, in raw_cluster_cmd
2019-12-11 18:24:36,474.474 INFO:__main__:    proc = self.controller.run([os.path.join(BIN_PREFIX, "ceph")] + list(args), **kwargs)
2019-12-11 18:24:36,474.474 INFO:__main__:  File "../qa/tasks/vstart_runner.py", line 390, in run
2019-12-11 18:24:36,474.474 INFO:__main__:    proc.wait()
2019-12-11 18:24:36,474.474 INFO:__main__:  File "../qa/tasks/vstart_runner.py", line 190, in wait
2019-12-11 18:24:36,474.474 INFO:__main__:    raise CommandFailedError(self.args, self.exitstatus)
2019-12-11 18:24:36,474.474 INFO:__main__:CommandFailedError: Command failed with status 22: ['./bin/ceph', 'mgr', 'self-test', 'module', 'diskprediction_local']
```

**Comment by liewegas** [comment]
> Latest dashboard backend API test run failed with:
> 
> ```
> Error EINVAL: Traceback (most recent call last):
>   File "/home/jenkins-build/build/workspace/ceph-dashboard-pr-backend/src/pybind/mgr/mgr_module.py", line 1062, in _handle_command
>     return self.handle_command(inbuf, cmd)
>   File "/home/jenkins-build/build/workspace/ceph-dashboard-pr-backend/src/pybind/mgr/selftest/module.py", line 143, in handle_command
>     r = self.remote(command['module'], "self_test")
>   File "/home/jenkins-build/build/workspace/ceph-dashboard-pr-backend/src/pybind/mgr/mgr_module.py", line 1424, in remote
>     args, kwargs)
> ImportError: Module not found
> 
> 2019-12-11 18:24:35,293.293 INFO:__main__:test_diskprediction_local (tasks.mgr.test_module_selftest.TestModuleSelftest) ... ERROR
> 2019-12-11 18:24:35,294.294 INFO:__main__:Running ['./bin/ceph', 'log', 'Ended test tasks.mgr.test_module_selftest.TestModuleSelftest.test_diskprediction_local']
> 2019-12-11 18:24:36,472.472 INFO:__main__:Stopped test: test_diskprediction_local (tasks.mgr.test_module_selftest.TestModuleSelftest) in 33.961712s
> 2019-12-11 18:24:36,473.473 INFO:__main__:
> 2019-12-11 18:24:36,473.473 INFO:__main__:======================================================================
> 2019-12-11 18:24:36,473.473 INFO:__main__:ERROR: test_diskprediction_local (tasks.mgr.test_module_selftest.TestModuleSelftest)
> 2019-12-11 18:24:36,473.473 INFO:__main__:----------------------------------------------------------------------
> 2019-12-11 18:24:36,473.473 INFO:__main__:Traceback (most recent call last):
> 2019-12-11 18:24:36,473.473 INFO:__main__:  File "/home/jenkins-build/build/workspace/ceph-dashboard-pr-backend/qa/tasks/mgr/test_module_selftest.py", line 51, in test_diskprediction_local
> 2019-12-11 18:24:36,473.473 INFO:__main__:    self._selftest_plugin("diskprediction_local")
> 2019-12-11 18:24:36,474.474 INFO:__main__:  File "/home/jenkins-build/build/workspace/ceph-dashboard-pr-backend/qa/tasks/mgr/test_module_selftest.py", line 34, in _selftest_plugin
> 2019-12-11 18:24:36,474.474 INFO:__main__:    "mgr", "self-test", "module", module_name)
> 2019-12-11 18:24:36,474.474 INFO:__main__:  File "../qa/tasks/vstart_runner.py", line 937, in raw_cluster_cmd
> 2019-12-11 18:24:36,474.474 INFO:__main__:    proc = self.controller.run([os.path.join(BIN_PREFIX, "ceph")] + list(args), **kwargs)
> 2019-12-11 18:24:36,474.474 INFO:__main__:  File "../qa/tasks/vstart_runner.py", line 390, in run
> 2019-12-11 18:24:36,474.474 INFO:__main__:    proc.wait()
> 2019-12-11 18:24:36,474.474 INFO:__main__:  File "../qa/tasks/vstart_runner.py", line 190, in wait
> 2019-12-11 18:24:36,474.474 INFO:__main__:    raise CommandFailedError(self.args, self.exitstatus)
> 2019-12-11 18:24:36,474.474 INFO:__main__:CommandFailedError: Command failed with status 22: ['./bin/ceph', 'mgr', 'self-test', 'module', 'diskprediction_local']
> ```

this is fixed by https://github.com/ceph/ceph/pull/32189

**Comment by callithea** [comment]
> this breaks opensuse 15.1 build it seems.
> 
> can't tell if this fixes the scipy problem because we're now hitting
> 
> ```
> [15:37:23] E/protractor - Could not find Angular on page https://ceph-builders:41522/#/login : retries looking for angular exceeded
> ```

#32204 is a temporary workaround
Before we ran into the "Could not find Angular on page" this patch https://github.com/ceph/ceph-build/pull/1448 has been manually applied for the dashboard e2e test Jenkins job - if we want to test your patch again I would need to revert my changes again.
The ceph dashboard backend API tests are not affected.

**Comment by tchaikov** [comment]
@liewegas i updated your change

- list `python-scipy` as the source package's "Build-Depends"
- comment it out as "Make-Check". as we don't really use it when building the package. it's only needed when performing the tests. `install-deps.sh` will uncomment it and install it as a build dependency.

**Comment by callithea** [comment]
jenkins test dashboard backend

**Pull request merged**
