### PR TITLE
test: Fix a blocklist API test

### PR DESCRIPTION
**Pull request by gregsfortytwo**
This test case was added in #44151, but I screwed up and did less testing on that PR than I thought I had before merging. :/

Fixes: https://tracker.ceph.com/issues/55419

Signed-off-by: Greg Farnum <gfarnum@redhat.com>

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by gregsfortytwo** [comment]
This is entirely untested as a fix because I can't figure out how to run the cephtool test locally just yet, but from log inspection this is the issue.

**Comment by gregsfortytwo** [comment]
@ljflores you reported this; don't suppose you know how to run individual tests like this locally? Otherwise I guess I'll spin up a small suite run that invokes it.

**Comment by ljflores** [comment]
@gregsfortytwo yeah, there's a way we can rerun the exact test that it originally failed. I can look into doing that on Monday.

**Comment by ljflores** [comment]
jenkins test make check

**Review by ljflores — APPROVED** [review]
Tested this on one of Yuri's qa runs, where the cephtool test failed. Re-running that branch with the suite repo set to this branch passed all the cephtool tests:

http://pulpito.front.sepia.ceph.com/lflores-2022-04-25_16:23:25-rados-wip-yuri2-testing-2022-04-22-0500-distro-default-smithi/

**Comment by ljflores** [comment]
The make check failure is a recent regression. See more details here: https://github.com/ceph/ceph/pull/43413#issuecomment-1108843403

**Comment by ljflores** [comment]
jenkins test make check

**Comment by ljflores** [comment]
@neha-ojha this test passed when run against Yuri's master branch (wip-yuri2-testing-2022-04-22-0500). Would you say that's thorough enough, or should this go through the whole rados suite?

**Comment by neha-ojha** [comment]
> @neha-ojha this test passed when run against Yuri's master branch (wip-yuri2-testing-2022-04-22-0500). Would you say that's thorough enough, or should this go through the whole rados suite?

This is enough.

**Pull request merged**
