### PR TITLE
nautilus: mgr/dashboard: list configured prometheus alerts

### PR DESCRIPTION
**Pull request by votdev**
backport tracker: https://tracker.ceph.com/issues/44690

---

backport of https://github.com/ceph/ceph/pull/31937
parent tracker: https://tracker.ceph.com/issues/42877

this backport was staged using ceph-backport.sh version 15.1.1.389
find the latest version at https://github.com/ceph/ceph/blob/master/src/script/ceph-backport.sh

### CODE REVIEW

**Comment by smithfarm** [comment]
"make check" failure is tracked by https://tracker.ceph.com/issues/44683

no reason to assume it's related to this PR, since it's happening in all nautilus PRs

**Comment by votdev** [comment]
jenkins test make check

**Comment by votdev** [comment]
jenkins test dashboard

**Comment by callithea** [comment]
- [pkg build](https://shaman.ceph.com/builds/ceph/wip-laura-testing-nautilus-34373/) [WIP]

**Pull request merged**
