### PR TITLE
jewel: rgw multisite: preserve zone's extra pool

### PR DESCRIPTION
**Pull request by theanalyst**
http://tracker.ceph.com/issues/16778

### CODE REVIEW

**Comment by theanalyst** [comment]
retest this please

**Comment by smithfarm** [comment]
Hey Jenkins, test this please (unrelated failure)

**Comment by dachary** [comment]
@theanalyst could this cause http://pulpito.ceph.com/loic-2016-08-12_08:10:12-rgw-jewel-backports---basic-smithi/359320/ ?

**Comment by dachary** [comment]
Running http://tracker.ceph.com/issues/16344#note-19 failed tests to check if this pull request is responsible for the failures:

* http://pulpito.front.sepia.ceph.com:80/loic-2016-08-15_12:15:37-rgw-wip-16778-jewel---basic-smithi/

**Comment by dachary** [comment]
Must be merged together with the fix for http://tracker.ceph.com/issues/17025

**Comment by oritwas** [comment]
@dachary @theanalyst  the fix to teuthology is merged, after passing rgw suite it can be merged

**Comment by dachary** [comment]
The rgw run http://tracker.ceph.com/issues/16344#note-27 was scheduled the same day the fix was merged and I'm not sure if it's before or after (the log output does not show the ceph-qa-suite sha1). I guess we can wait for the next one to be sure, unless there is a pressing need for this to be merged for 10.2.3.

**Comment by dachary** [comment]
Ah, nevermind, it contains it otherwise we would have seen the same four failures.

**Pull request merged**
