### PR TITLE
grep -P is not recognised under FreeBSD.

### PR DESCRIPTION
**Pull request by wjwithagen**
grep -P is not recognised under FreeBSD.
grep -E is required by Posix and as such has a better chance of
being portable. Difference now is that this grep will allow ANY
whitespace (only once char) at the beginning of the line.

Signed-off-by: Willem Jan Withagen <wjw@digiware.nl>

### CODE REVIEW

**Comment by liewegas** [comment]
Looks good, thanks!  WIll run it through the test suite shortly.

**Comment by wjwithagen** [comment]
On 4-12-2015 02:05, Sage Weil wrote:
> Looks good, thanks! WIll run it through the test suite shortly.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ceph/ceph/pull/6794#issuecomment-161841920>.

Hi,

Checked both failures, first 1 ran out of time during one of the test
Second is too incomprehensible for,

But pulls only get 2 runs before they are "discarded"?

--WjW

**Comment by dachary** [comment]
@wjwithagen that's unlucky ( you ran into http://tracker.ceph.com/issues/13969 ) and for the timeout I'm not sure what could have caused it. Would you mind rebasing & repushing to get a new run ?

**Comment by wjwithagen** [comment]
@dachary 
Being new to git (and not very fluent in SVN), you mean:
git rebase
git push 
in my wip-wjw-freebsd repo?

**Comment by dachary** [comment]
@wjwithagen yes :-) git pull --rebase + git push --force should be good

**Comment by wjwithagen** [comment]
@dachary Thanx will do.

**Comment by wjwithagen** [comment]
@dachary I think it went the wrong way.
Now a new commit was tested: 
Commit 3d33df856ab999daeb952aa83e475228a67c08da by wjw
FreeBSD Malloc lives in stdlib.h (also on Linux)

I could touch the few files with the grep and recommit?

**Comment by dachary** [comment]
@wjwithagen jenkins display can be confusing. http://jenkins.ceph.dachary.org/job/ceph/LABELS=centos-7&&x86_64/9849/consoleFull shows 
<pre>
HEAD is now at 8ae7042 Merge 3d33df856ab999daeb952aa83e475228a67c08da into b91cd9d495a7e59ffbdfcc40ea20aa848b0065c8
</pre>
which is good :-) No need for another run.

**Comment by wjwithagen** [comment]
@dachary thanx for the explanation, but the original commit fixing the grep -E's was 
875240d ....
I have a separate ceph/master/HEAD tree to 'git pull' and see what is current in the tree, and 875240d is not there.

**Comment by dachary** [comment]
@wjwithagen 3d33df856ab999daeb952aa83e475228a67c08da parent is 875240d

**Comment by tchaikov** [comment]
@wjwithagen to update your commit message "git rebase -i 875240d~" and the default git editor will be fired up, which allows you to edit the commit message with the "r" command.

**Comment by dachary** [comment]
@wjwithagen please ignore the bot failure, it is a false negative (see http://tracker.ceph.com/issues/13997 for more information). You can re-schedule a job by rebasing your branch and repushing.

**Comment by dachary** [comment]
@wjwithagen also please remove the Merge commit: a pull request should only have regular commits in it. Thanks :-)

**Comment by wjwithagen** [comment]
@dachary I'm getting deeper and deeper in the git tips and tricks. 
It probably all started by me not having a correct Signed-off-by: line. I used ()'s around the email address. Fixing that got me/us in where we are now.
So before I make it even worse, can you give me a fairly detailed set of things to do?
Rebasing is:
# git stash
# git rebase

Remove the merge is?
# git rm 2dc6b55

And then push
# git push

**Comment by dachary** [comment]
@wjwithagen there are very few changes, I suggest you re-apply them manually after a git reset --hard origin/master, it will be simpler.

**Comment by wjwithagen** [comment]
@dachary I'm all in favour for simple things....
So git reset --hard
Redo the changes.

And then commit with the right <wjw@digiware.nl> and push again?

**Comment by dachary** [comment]
@wjwithagen exactly !

**Comment by tchaikov** [comment]
@wjwithagen "git rm" is used to remove a certain file from the repo.

assuming "origin" is the origin ceph repo (`git remote -v` to show all your remote repos), you can
```
git rebase --hard origin/master
git cherry-pick f4f9366 53570a1
```

and `git push -f` to your `wip-wjw-freebsd` branch again.

**Comment by wjwithagen** [comment]
+ 2dc6b55...b5abd81 wip-wjw-freebsd -> wip-wjw-freebsd (forced update)

**Comment by dachary** [comment]
@wjwithagen please ignore the bot failure, it is a false negating. Could you please **git pull --rebase** and **git push --force** ?

**Comment by liewegas** [comment]
Hmm, can you rebase please?  Sorry for the delay!  I'll catch it in the next batch.

**Comment by wjwithagen** [comment]
@liewegas I have cleaned the full tree for a complete new build and test.
And some commit are in the local tree.
So to be carefull it'll have to wait until that is finished. And it's already taking too long :(
it about 02:52 in the night here, so I'm off to bed.

**Comment by wjwithagen** [comment]
@liewegas rebased.... But I think some shell debugging escape out into the real world.

**Comment by tchaikov** [comment]
@wjwithagen you are introducing some unrelated commits in your pull request. could you remove them and push again? you can reset to master and cherry-pick you own changes.

fwiw, next time to rebase against the origin/master, you can simply "git pull --rebase origin master".

and merry xmas!

**Comment by wjwithagen** [comment]
On 24-12-2015 07:19, Kefu Chai wrote:
> @wjwithagen <https://github.com/wjwithagen> you are introducing some
> unrelated commits in your pull request. could you remove them and push
> again? you can reset to master and cherry-pick you own changes.
>
> fwiw, next time to rebase against the origin/master, you can simply "git
> pull --rebase origin master".

Hi Kefu Chai,

Attribute this to my lack of experience in Git... :(
So you'll have to hand-hold me a bit more... and give me an outline of
the things to do. Perhaps use one of my commits as example.
Probably I can work from there, and not mess it up again.

The other thing is that I'd like to keep my wip-tree close to the master 
head
as to keep up with other things that are fixed.
So your last suggestion was more than welcome.

Alternative is to thrash this WIP and start a new one?
Perhaps a bit more work, but if I need to start cherry-picking anyways.

Thanx for the help,
--WjW

**Comment by wjwithagen** [comment]
@tchaikov
[Repost]

Hi Kefu Chai, 
Attribute this to my lack of experience in Git... :( 
So you'll have to hand-hold me a bit more... and give me an outline of the things to do. Perhaps use one of my commits as example. 
Probably I can work from there, and not mess it up again. 

The other thing is that I'd like to keep my wip-tree close to the master head as to keep up with other things that are fixed. 

So your last suggestion was more than welcome. 
Alternative is to thrash this WIP and start a new one? 
Perhaps a bit more work, but if I need to start cherry-picking anyways. 

Thanx for the help, 
--WjW

**Comment by tchaikov** [comment]
@wjwithagen sorry for the latency!

i'd suggest you to start a new branch from the latest master, and cherry-pick your changes from your wip-tree. assuming that 
- your local branch is also named `wip-wjw-freebsd`,
- and the ceph remote repo is named `origin`.

```
$ git fetch origin
$ git co -b wip-freebsd origin/master
$ for sha1 in `git log master..wip-wjw-freebsd --format="%aE %H" --grep=wjw | cut -d' ' -f2`; do  
  git cherry-pick $sha1
done
# resolve all conflicts
$ git push -f wjw wip-freebsd:wip-wjw-freebsd
```

et voilà! =)

**Comment by tchaikov** [comment]
@wjwithagen seems your pull request contains others commits again. could you remove them and repush? BTW, probably you can split your pr into smaller ones so it can be reviewed and merged more quickly, also to reduce the risk of conflicting with the master as a whole pr ?

**Comment by wjwithagen** [comment]
@tchaikov
Your comments are very welcomed, and if it seems that I don't really listen: I try to comply as much as I can. But the home/work front is a bit busy at the moment, so I only have strange blocks of time to work at this. 
Note that I do also value the fact that the code is run thru jenkins. But if that is a too heavy load because I mess up some of the FreeBSD <-> Linux differences, feel free to disable that.

0) I'm currently using this WIP to also move these changes to a CentOS vps and a FreeBSD 10.2-stable system, to make sure that it compiles and tests there as well. So that is why odd commits are in my WIP. Compiling and testing does take a lot more time than Jenkins does.
1) "updates to several files" is really not a commit message that should be out in the open. Sorry about that.
2) About getting others commits in the tree... 
I think they are still leftovers from out previous discussion about this? I have not build a new wip, because I first wanted to make my work as far as I have it now complete in the old WIP to make sure that I do not lose anything.
In the new WIP i'd like to start grouping changes into commits which are about the same subject, so reviewing is nog going to be the major pain that you foresee. 

But first I have to work out most of the errors in running 'gmake check'
Things I'm going to look at is getting:
 ceph-detect-init/run-tox.sh generate some usefull FreeBSD info.
Find out why both erasure-code runs are failing once again...

**Comment by wjwithagen** [comment]
@tchaikov 
I'm trying to build myself a new branch but whatever I try to do, I seem be stuck in my own fork.....
There is nothing I can do to get git to forward to the HEAD of ceph/ceph and give me a new WIP on that.
# git remote -v
origin  https://github.com/wjwithagen/ceph (fetch)
origin  https://github.com/wjwithagen/ceph (push)

The current branch I have worked in is called wip-wjw-freebsd, but that one is relative to ceph/ceph HEAD from about 27 days ago.
The new branch would be wip-wjw-freebsd-2

Could you tell me how to get back to the actual master code again?

**Comment by liewegas** [comment]
git rebase origin/master

**Comment by wjwithagen** [comment]
@liewegas 
Thanx, that worked. Going to figure out what's next to reorganize the changes I have.

**Comment by wjwithagen** [comment]
@liewegas 

\# git status
git status
On branch ceph/master
Your branch and 'remotes/ceph/master' have diverged,
and have 557 and 730 different commits each, respectively.
  (use "git pull" to merge the remote branch into yours)
All conflicts fixed but you are still merging.
  (use "git commit" to conclude merge)
Changes to be committed:
        modified:   doc/release-notes.rst
        modified:   doc/releases.rst
        modified:   src/osd/OSD.cc
        modified:   src/pybind/rbd.pyx

If I commit these, than I've again commit changes that er not mine. But looks like I'm not yet quite there?

**Comment by wjwithagen** [comment]
@liewegas 
That was not really what I was looking for.
I would like to have a WIP that I can use as starting point to actually apply the patches I extracted from my current WIP.
So the new WIP will contain cleaned patches grouped per sort.
So evaluating the effects are "easy" to grasp, and commiting goes in smaller batches

**Comment by liewegas** [comment]
git checkout -b wip-thing1
git cherry-pick commit1
git cherry-pick commit2

git checkout -b wip-thing2
git cherry-pick commit3

...
like so?

**Comment by wjwithagen** [comment]
I now have a up to date master... at least when I look a the ID of HEAD.
So I guess that would be the next sequence, 
..... other than cherry picking, I would be apply my sorted patches to really cleanup from the mess I made in between.
Then I would psuh, and create a pull for that specific WIP, for others to review and possibly to commit.

**Comment by liewegas** [comment]
something like this might be helpful reading:
https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History

**Comment by wjwithagen** [comment]
@liewegas 
Thanx, will read it. fortunately it's not too long.
There is some much to read.

**Comment by wjwithagen** [comment]
@liewegas 
Guess that the "squashing commits" would be a good on for this.

**Comment by wjwithagen** [comment]
I've have all the buildtool changes in:
https://github.com/ceph/ceph/pull/7239

**Pull request closed without merging**
