### PR TITLE
doc: add descriptions for mon/mgr options

### PR DESCRIPTION
**Pull request by tchaikov**
Signed-off-by: Kefu Chai <kchai@redhat.com>

### CODE REVIEW

**Comment by tchaikov** [comment]
@johnwilkins it's still a work-in-progress. will finish it tomorrow.

**Comment by tchaikov** [comment]
@johnwilkins i just finished updating the missing doc for mon options.

**Comment by tchaikov** [comment]
@jecluis could you help proof-read the descriptions for the mon options?

**Comment by vasukulkarni** [comment]
Nice Explanation! :+1:

**Comment by tchaikov** [comment]
@jecluis could you take a quick look at this PR? just in case i am terribly wrong about some of the options.

**Pull request merged**
