### PR TITLE
ceph-volume: don't try to test lvm zap on simple tests

### PR DESCRIPTION
**Pull request by jan--f**
Fixes: https://tracker.ceph.com/issues/41245

Signed-off-by: Jan Fajerski <jfajerski@suse.com>

### CODE REVIEW

**Comment by jan--f** [comment]
jenkins test ceph-volume all

**Comment by alfredodeza** [comment]
errrr, why are these batch failing now?

```
--> Aborting because strategy changed from filestore.MixedType to filestore.SingleType after filtering
```

**Comment by jan--f** [comment]
hmm one is a bug (about to fix that). Another is the idempotency test batch failing...looking into it.

**Comment by jan--f** [comment]
jenkins test ceph-volume all

**Pull request merged**
