### PR TITLE
qa/cephadm: Test again podman on ubuntu 20.04

### PR DESCRIPTION
**Pull request by sebastian-philipp**
This is a cherry-pick of #39494 as podman on ubuntu 18.04 is broken right now.

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Review by liewegas — APPROVED** [review]

**Comment by liewegas** [comment]
retest this please

**Comment by sebastian-philipp** [comment]
jenkins test make check

**Comment by sebastian-philipp** [comment]
https://pulpito.ceph.com/swagner-2021-02-25_11:28:56-rados:cephadm-wip-swagner-testing-2021-02-24-1710-distro-basic-smithi/

Failurs:

* untracked bug making the upgrade end up in an infinite loop
* https://tracker.ceph.com/issues/49456
* https://tracker.ceph.com/issues/48502

**Comment by sebastian-philipp** [comment]
jenkins test make check

**Comment by sebastian-philipp** [comment]
jenkins test make check

**Pull request merged**
