### PR TITLE
Make it more difficult to delete pools in firefly

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/11801

### CODE REVIEW

**Comment by smithfarm** [comment]
This backport was requested by Wido.

**Comment by wido** [comment]
Thanks! Would be great if this made it back into Firefly.

**Comment by dachary** [comment]
for the record it was also marked as backport to firefly by sage in the original commit message

**Comment by smithfarm** [comment]
@dachary: rebased to fix 127.0.0.1 - thanks for debugging!

**Comment by dachary** [comment]
@smithfarm #4788 conflicts with #4635 #4636 #4597, could you make it so they play nice together ?

**Comment by smithfarm** [comment]
@dachary done - can be merged provided make check succeeds

**Comment by smithfarm** [comment]
@liewegas Hi, this is a backport of 6b982e4 which you authored and merged. It has passed a rados suite as detailed by http://tracker.ceph.com/issues/11644#rados . Do you think it's ready to merge?

**Comment by liewegas** [comment]
:+1:

**Pull request merged**
