### PR TITLE
fix reuse of osd ids

### PR DESCRIPTION
**Pull request by liewegas**
http://tracker.ceph.com/issues/13988

### CODE REVIEW

**Comment by liewegas** [comment]
pg_temp is not osd-based, and the mon cleans it up. yes on primary affinity.  same for state.  repushing!

**Comment by dachary** [comment]
<pre>
Reviewed-by: Loic Dachary &lt;ldachary@redhat.com>
</pre>

**Comment by dachary** [comment]
Running the ceph-disk suite which hits the bug every time on master

<pre>
teuthology-openstack --verbose --key-filename ~/Downloads/myself --key-name myself --teuthology-git-url http://github.com/dachary/teuthology --teuthology-branch wip-suite --ceph-qa-suite-git-url http://github.com/ceph/ceph-qa-suite --suite-branch master --ceph-git-url http://github.com/liewegas/ceph --ceph wip-13988 --suite ceph-disk --filter ubuntu_14.04
</pre>

* *running*

**Comment by dachary** [comment]
@liewegas could you update the commit message regarding the upgrade ? Since it has no influence on anything user visible, I assume the merge commit can be empty and not be highlighted in the release notes.

**Comment by dachary** [comment]
@liewegas the bot failure is from http://tracker.ceph.com/issues/13986 and should be ignored.

**Pull request merged**
