### PR TITLE
[WIP] iSCSI management UI (read-only)

### PR DESCRIPTION
**Pull request by tspmelo**
After: #25590

- [ ] References tracker ticket
- [ ] Includes tests for new functionality or reproducer for bug
- [ ] Improve UI

### CODE REVIEW

**Comment by tspmelo** [comment]
image

**Comment by tspmelo** [comment]
image

**Comment by tspmelo** [comment]
Now it shows an info panel and hides the table when not available.
image

**Comment by tchaikov** [comment]
retest this please.

**Pull request closed without merging**
