### PR TITLE
[DNM] doc: RGW pools naming convention

### PR DESCRIPTION
**Pull request by vumrao**
Currently RGW pools document was missing that
we still need Period for starting RGW pools name.

Signed-off-by: Vikhyat Umrao <vumrao@redhat.com>

### CODE REVIEW

**Comment by vumrao** [comment]
http://tracker.ceph.com/issues/12594

**Comment by tchaikov** [comment]
@yehudasa @vumrao it looks good to me per the discussion between you guys. and i took a glimpse at the code of rgw
```c++
int RGWZoneParams::get_pool_name(CephContext *cct, string *pool_name)
{
  *pool_name = cct->_conf->rgw_zone_root_pool;
  if (pool_name->empty()) {
    *pool_name = RGW_DEFAULT_ZONE_ROOT_POOL;
  } else if ((*pool_name)[0] != '.') {
    derr << "ERROR: zone root pool name must start with a period" << dendl;
    return -EINVAL;
  }

  return 0;
}
```

to double confirm this requirement of naming convention. so this change LGTM. will merge it tomorrow if no objections.

**Comment by vumrao** [comment]
@tchaikov @yehudasa  thanks !

**Comment by theanalyst** [comment]
@tchaikov / @vumrao BTW, there is a patch (#4944) for making the dots go away for the default pools in the future.

**Comment by tchaikov** [comment]
@theanalyst wow, thanks a lot ! i will look at #4944 and close this one if it won't be true once #4944 is merged.

**Comment by vumrao** [comment]
@theanalyst  thanks !

**Comment by tchaikov** [comment]
@vumrao i will close this once #4944 gets merged.

**Comment by vumrao** [comment]
@tchaikov thanks yes as then we do not need it.

**Comment by tchaikov** [comment]
quote from Yehuda

> closing, it's already part of new multi site branch

**Pull request closed without merging**
