### PR TITLE
librados: get_pool_name() should not return ref of a local variable

### PR DESCRIPTION
**Pull request by tchaikov**
Signed-off-by: Kefu Chai <kchai@redhat.com>

### CODE REVIEW

**Comment by tchaikov** [comment]
test this please.

**Comment by gregsfortytwo** [comment]
Are we allowed to change the signature on this function? It's part of the public interface

**Comment by jdurgin** [comment]
to not break the ABI in jewel (assuming we want to backport this) I think we should add get_pool_name2() instead, and mark the original deprecated

**Comment by jdurgin** [comment]
nevermind, @athanatos points out this was just introduced recently, and works in jewel.

So I'm fine with this fix.

**Comment by xiexingguo** [comment]
@tchaikov Thanks!

**Pull request merged**
