### PR TITLE
pybind/rados: use rados_set_pool_full_try instead of the deprecated one

### PR DESCRIPTION
**Pull request by tchaikov**
this change silences the warning when compiling the cythonized python
binding:

build/src/pybind/rados/pyrex/rados.c:64435:9: warning: 'rados_set_osdmap_full_try' is deprecated [-Wdeprecated-declarations]
         rados_set_osdmap_full_try(__pyx_v_self->io);
         ^~~~~~~~~~~~~~~~~~~~~~~~~

Signed-off-by: Kefu Chai <kchai@redhat.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by tchaikov** [comment]
jenkins test make check

**Comment by tchaikov** [comment]
jenkins test make check

**Comment by tchaikov** [comment]
jenkins test make check

**Comment by tchaikov** [comment]
- https://pulpito.ceph.com/kchai-2020-12-03_06:25:29-rados-wip-kefu-testing-2020-12-02-2319-distro-basic-smithi/
- https://pulpito.ceph.com/kchai-2020-12-04_02:12:52-rados-wip-kefu-testing-2020-12-02-2319-distro-basic-smithi/

**Review by neha-ojha — APPROVED** [review]

**Pull request merged**
