### PR TITLE
reef: osd/OpRequest: Add detail description for delayed op in osd log file

### PR DESCRIPTION
**Pull request by pdvian**
backport tracker: https://tracker.ceph.com/issues/62993

backport of https://github.com/ceph/ceph/pull/50531

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Review by neha-ojha — APPROVED** [review]

**Comment by neha-ojha** [comment]
jenkins test make check

**Comment by amathuria** [comment]
Rados approved, unrelated failures tracked in:

1. https://tracker.ceph.com/issues/59196
2. https://tracker.ceph.com/issues/62992
3. https://tracker.ceph.com/issues/61774
4. https://tracker.ceph.com/issues/61786

Details:
1. ceph_test_lazy_omap_stats segfault while waiting for active+clean
2. Heartbeat crash in osd
3. centos 9 testing reveals rocksdb "Leak_StillReachable" memory leak in mons
4. test_dashboard_e2e.sh: Can't run because no spec files were found; couldn't determine Mocha version

**Comment by yuriw** [comment]
jenkins test api

**Comment by yuriw** [comment]
@pdvian pls merge when checks passed
ref: https://trello.com/c/Ommn2Wqm

**Pull request merged**
