### PR TITLE
os/bluestore: add some slow count for bluestore

### PR DESCRIPTION
**Pull request by YiteGu**
Add slow count as below:
    - l_bluestore_slow_aio_wait_count
    - l_bluestore_slow_committed_kv_count
    - l_bluestore_slow_read_onode_meta_count
    - l_bluestore_slow_read_wait_aio_count

    We can get a count while bluestore happens slowly,
    in some cases, this is more useful than average latency.
    Add it to prometheus, we can get it from the dashboard.

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [x] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by ifed01** [comment]
@YiteGu - make check failure looks relevant. Please fix!

**Comment by YiteGu** [comment]
> @YiteGu - make check failure looks relevant. Please fix!

done, but have a not relevant fail.

**Comment by YiteGu** [comment]
@ifed01 should we also add slow count for aio_wait and read？

**Comment by YiteGu** [comment]
we can get stat as below
```
# ceph daemon asok/osd.0.asok perf dump | grep -A4 "slow_aio_wait_count"
        "slow_aio_wait_count": 0,
        "slow_committed_kv_count": 0,
        "slow_read_onode_meta_count": 0,
        "slow_read_wait_aio_count": 0
    },
```

**Comment by YiteGu** [comment]
jenkins test make check

**Comment by YiteGu** [comment]
Hi, @ifed01 help me code review

**Review by ifed01 — APPROVED** [review]

**Comment by pdvian** [comment]
https://pulpito.ceph.com/lflores-2023-09-06_18:19:12-rados-wip-yuri6-testing-2023-08-28-1308-distro-default-smithi/

Failures, unrelated:
1. https://tracker.ceph.com/issues/59142
2. https://tracker.ceph.com/issues/59196
3. https://tracker.ceph.com/issues/55347 
4. https://tracker.ceph.com/issues/62084
5. https://tracker.ceph.com/issues/62975                 <<<---- New Tracker
6. https://tracker.ceph.com/issues/62449
7. https://tracker.ceph.com/issues/61774
8. https://tracker.ceph.com/issues/53345

Details:
1. mgr/dashboard: fix e2e for dashboard v3 - Ceph - Mgr - Dashboard
2. ceph_test_lazy_omap_stats segfault while waiting for active+clean - Ceph - RADOS
3. SELinux Denials during cephadm/workunits/test_cephadm
4. task/test_nfs: AttributeError: 'TestNFS' object has no attribute 'run_ceph_cmd' - Ceph - CephFS
5. site-packages/paramiko/channel.py: OSError: Socket is closed - Infrastructure
6. test/cls_2pc_queue: TestCls2PCQueue.MultiProducer and TestCls2PCQueue.AsyncConsumer failure - Ceph - RGW
7. centos 9 testing reveals rocksdb "Leak_StillReachable" memory leak in mons - Ceph - RADOS
8. Test failure: test_daemon_restart (tasks.cephadm_cases.test_cli.TestCephadmCLI) - Ceph - Orchestrator

**Pull request merged**
