### PR TITLE
cmake: Fix FCGI include directory

### PR DESCRIPTION
**Pull request by tserong**
config-h.in.cmake and rgw_fcgi.{cc,h} all expect FASTCGI_INCLUDE_DIR to
be set when FastCGI headers are in /usr/include/fastcgi.  Unfortunately,
Findfcgi.cmake sets FCGI_INCLUDE_DIR, i.e. the name doesn't match.  This
breaks the cmake build on SUSE distros (and presumably any other distro
which has the FastCGI headers in /usr/include/fastcgi).

Signed-off-by: Tim Serong <tserong@suse.com>

### CODE REVIEW

**Comment by tchaikov** [comment]
quote from `rgw_fcgi.cc`

```c++
#include "acconfig.h"
#ifdef FASTCGI_INCLUDE_DIR
# include "fastcgi/fcgiapp.h"
#else
# include "fcgiapp.h"
#endif
```

and `Findfcgi.cmake` searches for `fcgio.h` in *both* `/usr/include` and `/usr/include/fastcgi`. so 

- if fastcgi header files are installed into `/usr/include/fastcgi`, `FCGI_INCLUDE_DIR` is set, and `#include "fcgiapp.h` is chosen. with this patch, `# include "fastcgi/fcgiapp.h"` is chosen, good.
- if fastcgi header files are installed into `/usr/include`, `FCGI_INCLUDE_DIR` is set, and `#include "fcgiapp.h` is chosen. good. with this patch, `# include "fastcgi/fcgiapp.h"` is chosen, d'oh!

so maybe a better approach is to 

1. always `#include <fcgiapp.h>` in `rgw_fcgi.cc`, please note that we have `find_package(fcgi REQUIRED)` in `CMakeLists.txt`
1. update `src/rgw/CMakeLists.txt`, to add
```
include_directories(${FCGI_INCLUDE_DIR})
```
into it.

**Comment by tserong** [comment]
@tchaikov, ah, thanks for the explanation! I'll try alternate approach... Although, how about this:

````
#ifdef FASTCGI_INCLUDE_DIR
# include "fastcgi/fcgiapp.h"
#else
# include <fcgiapp.h>
#endif
````

That means autotools builds will still pick up the FASTCGI_INCLUDE_DIR branch if necessary, and everything else will use the `<fcgiapp.h>` form.

**Comment by tchaikov** [comment]
so you suggest we keep `FCGI_INCLUDE_DIR` unchanged in the `Findfcgi.cmake`? if that's the case, it works albeit a little bit tricky. personally, i don't really like this way, even it involves less change.

**Comment by tserong** [comment]
Yeah, leave `FCGI_INCLUDE_DIR` unchanged in `Findfcgi.cmake`, add `include_directories(${FCGI_INCLUDE_DIR})` to `src/rgw/CMakeLists.txt` as you suggested earlier, and put `#include <fcgiapp.h>` in the `#else` case in `rgw_fcgi.cc`. That should be the minimal change to fix the cmake build.

If I get rid of the `#ifdef FASTCGI_INCLUDE_DIR` section and always make it `#include <fcgiapp.h>`, that probably breaks the autotools build. But if we don't care about that anymore, then that's actually not a problem :-)

**Comment by tchaikov** [comment]
you are right. the change i suggested breaks autotools build. the autotools part needs more work if we remove `#ifdef FASTCGI_INCLUDE_DIR`.

**Comment by tchaikov** [comment]
lgtm.

**Comment by tchaikov** [comment]
tested at 

* http://pulpito.ceph.com/kchai-2016-07-02_20:22:26-rados-wip-kefu-testing---basic-smithi/
* http://pulpito.ceph.com/kchai-2016-07-02_09:03:22-rados-wip-kefu-testing---basic-mira/

**Pull request merged**
