### PR TITLE
librbd: cannot clone all image-metas if we have more than 64 key/value pairs

### PR DESCRIPTION
**Pull request by PCzhangPC**
Signed-off-by: PCzhangPC <pengcheng.zhang@easystack.cn>

### CODE REVIEW

**Comment by PCzhangPC** [comment]
@dillaman ok, thx

**Comment by dillaman** [comment]
@PCzhangPC Can you open a tracker ticket for this issue so that we can get it backported correctly? Thanks.

**Comment by PCzhangPC** [comment]
@dillaman http://tracker.ceph.com/issues/21814

**Comment by PCzhangPC** [comment]
@dillaman updated, please help to review

**Comment by dillaman** [comment]
@PCzhangPC lgtm -- can you add a small unit test for clone to verify it copies >64 metadata keys? Thanks!

**Comment by PCzhangPC** [comment]
ok，thx for your review :） @dillaman

**Comment by PCzhangPC** [comment]
@ceph-jenkins retest this please

**Comment by PCzhangPC** [comment]
@ceph-jenkins retest this please

**Comment by PCzhangPC** [comment]
will check the failure later

**Comment by PCzhangPC** [comment]
@dillaman sorry for late.  test case added, please have a look

**Comment by PCzhangPC** [comment]
@dillaman please help to review this if convenient for you

**Comment by yuriw** [comment]
[wip-yuri3-testing-2017-10-30-1937](https://trello.com/c/1XlYdRCZ/190-wip-yuri3-testing-2017-10-30-1937)

**Pull request merged**
