### PR TITLE
reef: mds: add a command to dump directory information

### PR DESCRIPTION
**Pull request by joscollin**
Backported: https://github.com/ceph/ceph/pull/49756
Fixes: https://tracker.ceph.com/issues/64743

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [x] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Review by batrick — DISMISSED** [review]
How did this go from one commit [1] to three?

https://github.com/ceph/ceph/pull/54202/commits

There must be an explanation in the PR description.

**Comment by batrick** [comment]
https://tracker.ceph.com/projects/cephfs/wiki/Reef#11th-March-2024

**Comment by joscollin** [comment]
> How did this go from one commit [1] to three?
> 
> https://github.com/ceph/ceph/pull/54202/commits
> 
> There must be an explanation in the PR description.

There's no tracker for the parent PR. So updated the PR url in the description.

**Review by vshankar — APPROVED** [review]
https://tracker.ceph.com/projects/cephfs/wiki/Reef#19th-March-2024

**Comment by vshankar** [comment]
@batrick re-requested a review from you. The original change was not a backport candidate. On request from some community members, it was picked up for backporting. Should have had a tracker created at that point. It's not late to do so right now though. WDYT?

**Comment by yuriw** [comment]
@joscollin pls merge when ready
ref: https://trello.com/c/mF32rpDn

**Comment by joscollin** [comment]
> @joscollin pls merge when ready ref: https://trello.com/c/mF32rpDn

@vshankar FYI^

**Pull request merged**
