### PR TITLE
mon,osd: add crush_version to OSDMap, and allow crush map updates to gate on crush_version

### PR DESCRIPTION
**Pull request by liewegas**
This allows safe offline updates to the crush map.  The caller can fetch the map,
note the version, go make some changes, and when reinjecting the map, specify the
same version to ensure there weren't intervening updates.

### CODE REVIEW

**Comment by liewegas** [comment]
Since crush_version is an OSDMap field and it's updated in OSDMap::apply_incremental(), it should capture *any* change to the crush map, since that's the only path for it to update in OSDMap.

**Comment by dachary** [comment]
nice !

**Comment by yuriw** [comment]
test this please

**Comment by yuriw** [comment]
failed tests 
http://pulpito.ceph.com/yuriw-2017-06-08_22:17:58-rados-wip-yuri-testing_2017_7_9_2-distro-basic-smithi/

http://pulpito.ceph.com/yuriw-2017-06-09_00:49:08-rados-wip-yuri-testing_2017_7_9_2-distro-basic-smithi/

**Comment by liewegas** [comment]
retest this please

**Comment by liewegas** [comment]
retest this please

**Comment by liewegas** [comment]
http://pulpito.ceph.com/sage-2017-06-19_19:32:29-rados-wip-sage-testing-distro-basic-smithi/

**Pull request merged**
