### PR TITLE
small bugs or clean up about ReplicatedPG

### PR DESCRIPTION
**Pull request by majianpeng**

### CODE REVIEW

**Comment by majianpeng** [comment]
@tchaikov . Have you time review this? Thanks!

**Comment by majianpeng** [comment]
@tchaikov . updated and please review again! Thanks!

**Comment by tchaikov** [comment]
`Reviewed-by: Kefu Chai <kchai@redhat.com>` after the qa run.

**Comment by tchaikov** [comment]
@majianpeng i scheduled a run with this pull request only at http://pulpito.ceph.com/ubuntu-2015-06-25_21:04:06-rados-wip-kefu-testing---basic-multi/ , but it failed. would you mind testing it again in the lab?

**Comment by majianpeng** [comment]
@dachary . Those patch can't pass ceph_test_rados_api_aio. But can pass run-make-check.sh. Why? In run-make-check, is it not call ceph_test*? Thanks

**Comment by tchaikov** [comment]
@majianpeng, `ceph_test_rados_api_aio` is called by qa/workunits/rados/test.sh which is in turn a workunit. it is not exercised by `make check` .

**Comment by tchaikov** [comment]
i re-ran `ceph_test_rados_api_io --gtest_filter=LibRadosAioEC.RoundTripWriteFull`. it passed. @majianpeng could you mind sharing with me what you changed in the latest pull request compared with the last version? is it the `force_changesize` change?

thanks.

**Comment by tchaikov** [comment]
reviewed, would be better if we can handle the case where length=0.

**Comment by majianpeng** [comment]
Now this PR queue in sepia(in localhost it can pass ceph_test_rados_api_io/aio). 
For "reviewed, would be better if we can handle the case where length=0." what's mean? 
Thanks!

**Comment by tchaikov** [comment]
> For "reviewed, would be better if we can handle the case where length=0." what's mean? 

see 
https://github.com/majianpeng/ceph/commit/a211908f9651f86799e3963de2bc5d556f894a85#commitcomment-11968378

**Comment by majianpeng** [comment]
@tchaikov . test in our lab and pass. Remove one patch about calc crc only for replicated object. Because cache tier promote erasure object will need erasue object crc of whole object. So i remove the patch. Please review again. Thanks!

**Comment by tchaikov** [comment]
@majianpeng, may i know what suite you did run? and what subset? something like n/20 would suffice, i presume.

**Comment by tchaikov** [comment]
tested at:
http://pulpito.ceph.com/ubuntu-2015-07-03_23:36:35-rados-wip-kefu-testing---basic-multi/
http://pulpito.ceph.com/ubuntu-2015-07-04_23:36:15-rados-wip-kefu-testing---basic-multi/

**Pull request merged**
