### PR TITLE
luminous: mds: track average session uptime

### PR DESCRIPTION
**Pull request by vshankar**
http://tracker.ceph.com/issues/35937 (backport https://github.com/ceph/ceph/pull/23314)

### CODE REVIEW

**Comment by smithfarm** [comment]
@vshankar Note that when you cherry-pick with `git cherry-pick -x`, git generates the Conflicts section automatically - you just have to uncomment it.

**Comment by vshankar** [comment]
yeh -- slipped in this instance... will update.

**Comment by yuriw** [comment]
[wip-yuri-testing-2018-10-04-2118-luminous](https://trello.com/c/mJOJX7iH/435-wip-yuri-testing-2018-10-04-2118-luminous)

**Comment by smithfarm** [comment]
@batrick May be true, but for Ceph backporting I always emphasize the `-x` :-)

**Pull request merged**
