### PR TITLE
pybind/mgr/selftest: add selftest to mypy and cleanups

### PR DESCRIPTION
**Pull request by tchaikov**
## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by tchaikov** [comment]
jenkins test api

**Comment by tchaikov** [comment]
jenkins test api

**Comment by tchaikov** [comment]
- https://pulpito.ceph.com/kchai-2021-04-15_08:31:03-rados-wip-kefu-testing-2021-04-15-1359-distro-basic-smithi/
- https://pulpito.ceph.com/kchai-2021-04-16_02:02:40-rados-wip-kefu-testing-2021-04-15-1359-distro-basic-gibba/

the valgrind issue is tracked by https://tracker.ceph.com/issues/50299

**Comment by tchaikov** [comment]
@sebastian-philipp @jdurgin could you help review this PR?

**Review by sebastian-philipp — APPROVED** [review]

**Pull request merged**
