### PR TITLE
ceph_release: octopus rc 15.1.0

### PR DESCRIPTION
**Pull request by liewegas**
Signed-off-by: Sage Weil <sage@redhat.com>

### CODE REVIEW

**Comment by tchaikov** [comment]
```
62 - unittest_lockdep (Timeout)
```

**Comment by liewegas** [comment]
retest this please

**Comment by liewegas** [comment]
Shell we tag the first RC?

**Comment by dillaman** [comment]
:+1: from RBD

**Comment by liewegas** [comment]
retest this please

**Comment by liewegas** [comment]
retest this please

**Comment by LenzGr** [comment]
:+1: from Dashboard - thank you!

**Pull request merged**
