### PR TITLE
mgr/dashboard: remove feedback module as always-on

### PR DESCRIPTION
**Pull request by epuertat**
It was mistakenly left as always-on

Fixes: https://tracker.ceph.com/issues/53950
Signed-off-by: Ernesto Puerta <epuertat@redhat.com>

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Review by avanthakkar — APPROVED** [review]

**Comment by epuertat** [comment]
Shaman [packages launched](https://shaman.ceph.com/builds/ceph/wip-epuertat-testing-2022-01-20-1324/444da26e794615cfa9db8e2522b954ec80e82a4d/default/292674/).

**Comment by epuertat** [comment]
jenkins test make check

**Comment by nizamial09** [comment]
jenkins test make check

**Review by alfonsomthd — APPROVED** [review]

**Comment by alfonsomthd** [comment]
@epuertat I found this error in make check:
```
openapi-check run-test: commands[1] | diff openapi.yaml /home/jenkins-build/build/workspace/ceph-pull-requests/src/pybind/mgr/dashboard/.tox/openapi-check/tmp/openapi.yaml
10520c10520
< - description: Feedback
---
> - description: Feedback API
ERROR: InvocationError for command /usr/bin/diff openapi.yaml .tox/openapi-check/tmp/openapi.yaml (exited with code 1)
___________________________________ summary ____________________________________
ERROR:   openapi-check: commands failed
```

**Comment by avanthakkar** [comment]
jenkins test make check

**Comment by nizamial09** [comment]
jenkins test dashboard cephadm

**Review by nizamial09 — APPROVED** [review]

**Comment by nizamial09** [comment]
jenkins test dashboard

**Comment by epuertat** [comment]
Teuthology [run launched](https://pulpito.ceph.com/epuertat-2022-01-20_17:11:14-rados:dashboard-wip-epuertat-testing-2022-01-20-1324-distro-basic-smithi/).

**Comment by avanthakkar** [comment]
jenkins test make check

**Comment by avanthakkar** [comment]
jenkins test make check

**Comment by avanthakkar** [comment]
jenkins test dashboard

**Comment by epuertat** [comment]
Teuthology tests are queued 🙈 ... Ok, it's pretty evident that the main issue is caused by the module declared as always-on, so let's get this merged and have a separate debugging on why the module is failing to load.

**Pull request merged**
