### PR TITLE
[DNM] mimic: cephfs: make cephfs-data-scan reconstruct snaptable

### PR DESCRIPTION
**Pull request by madwizard**
https://tracker.ceph.com/issues/37906

### CODE REVIEW

**Comment by batrick** [comment]
Has a build error: https://jenkins.ceph.com/job/ceph-pull-requests/13480/

**Comment by smithfarm** [comment]
@madwizard Did those commits cherry-pick without any conflicts?

**Comment by madwizard** [comment]
There was a small merge conflict. I must have mixed something with cherry-pick. When I patched things manually it compiled without issue. I'll re-do this.

**Comment by smithfarm** [comment]
@madwizard When cherry-picking, please always use `git cherry-pick -x` and include the Conflicts section that git produces (you have to uncomment it).

Ideally, after the Conflicts section you could append a brief note explaining what the conflicts were and how you resolved them. This is optional, but the full Conflicts section produced by git (including the list of files that had conflicts) is mandatory. Thanks!

**Comment by madwizard** [comment]
@smithfarm I'll close this PR and open a new one once I get this clean. No reason to let this hang in the air. Thank you for pointers.

**Pull request closed without merging**
