### PR TITLE
luminous: CLI unit formatting tests are broken

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/24740

### CODE REVIEW

**Comment by smithfarm** [comment]
@yuriw Here is the luminous backport you requested. Please post links to logs of the failed luminous tests you believe this will fix.

**Comment by smithfarm** [comment]
http://pulpito.ceph.com/teuthology-2018-07-02_01:50:02-upgrade:client-upgrade-luminous-mimic-distro-basic-smithi/
http://pulpito.ceph.com/teuthology-2018-07-02_01:47:03-upgrade:client-upgrade-jewel-mimic-distro-basic-smithi/

**Comment by smithfarm** [comment]
```
/home/jenkins-build/build/workspace/ceph-pull-requests/src/librbd/image/CloneRequest.cc: In member function ‘void librbd::image::CloneRequest<ImageCtxT>::send_create()’:
/home/jenkins-build/build/workspace/ceph-pull-requests/src/librbd/image/CloneRequest.cc:190:35: error: ‘RBD_FEATURES_IMPLICIT_ENABLE’ was not declared in this scope
     m_features = (m_p_features & ~RBD_FEATURES_IMPLICIT_ENABLE);
                                   ^
src/librbd/CMakeFiles/rbd_internal.dir/build.make:686: recipe for target 'src/librbd/CMakeFiles/rbd_internal.dir/image/CloneRequest.cc.o' failed
make[3]: *** [src/librbd/CMakeFiles/rbd_internal.dir/image/CloneRequest.cc.o] Error 1
```

**Comment by smithfarm** [comment]
@dillaman Am I on the right track here, or digging deeper into something undesirable?

**Comment by smithfarm** [comment]
Looking at the log from one of the failed tests, I see the commands immediately preceding the first Traceback do appear to be something this PR might conceivably fix:

```
2018-07-02T08:02:42.088 INFO:tasks.workunit.client.0.smithi150.stderr:+ rbd info testimg_import
2018-07-02T08:02:42.088 INFO:tasks.workunit.client.0.smithi150.stderr:+ grep 'stripe unit'
2018-07-02T08:02:42.088 INFO:tasks.workunit.client.0.smithi150.stderr:+ awk '{print $3}'
2018-07-02T08:02:42.088 INFO:tasks.workunit.client.0.smithi150.stderr:+ grep -Ei '(4K|4096)'
2018-07-02T08:02:42.137 INFO:tasks.workunit.client.0.smithi150.stderr:+ rm -rf /tmp/rbd_import_export_29410
2018-07-02T08:02:42.138 INFO:tasks.workunit:Stopping ['rbd/import_export.sh'] on client.0...
```

Wouldn't it be nice, though, if the teuthology log included both stderr and stdout here, so we could see the output of the `rbd info testimg_import` command?

**Comment by dillaman** [comment]
@smithfarm I'll open a new PR w/ the fixes that will be required for backport. This current PR is pulling in too many unrelated changes and not enough ```import_export.sh``` changes due to all the spaghetti-like tangles in the commit history.

**Comment by smithfarm** [comment]
@dillaman Thanks!

**Pull request closed without merging**
