### PR TITLE
mimic: tests: make get_mon_status use mon addr

### PR DESCRIPTION
**Pull request by smithfarm**
Follow-on fix for #31424 which was itself a follow-on fix for https://github.com/ceph/ceph/pull/30841

Fixes: https://tracker.ceph.com/issues/42658

### CODE REVIEW

**Comment by smithfarm** [comment]
```
99% tests passed, 1 tests failed out of 157

Total Test time (real) = 1003.74 sec

The following tests FAILED:
	 64 - unittest_throttle (Failed)
```

**Comment by smithfarm** [comment]
jenkins test make check

**Comment by smithfarm** [comment]
@yuriw One more rados suite for this PR and then start QE on mimic?

**Comment by yuriw** [comment]
[wip-yuri7-testing-2019-11-07-1547-mimic](https://trello.com/c/AnrpG9Of/750-wip-yuri7-testing-2019-11-07-1547-mimic)

**Comment by smithfarm** [comment]
Yeah, upon hindsight https://github.com/ceph/ceph/pull/30841 was probably a bad idea...

**Comment by smithfarm** [comment]
http://pulpito.ceph.com/yuriw-2019-11-08_02:27:49-rados-wip-yuri7-testing-2019-11-07-1547-mimic-distro-basic-smithi/

this looks much better - thanks @yuriw

**Pull request merged**
