### PR TITLE
cephfs-shell: Fix flake8 errors (F841, E302, E502, E128, E305 and E222)

### PR DESCRIPTION
**Pull request by ADI10HERO**
cephfs-shell: Fixed cephfs-shell flake8 errors (F841, E302, E502, E128, E305 and E222)

image
Fixes: https://tracker.ceph.com/issues/44657
Signed-off-by: Aditya Srivastava <adityasrivastava301199@gmail.com>

## Checklist
- [x] References tracker ticket
- [x] Updates documentation if necessary
- [x] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by varshar16** [comment]
The commit message is jumbled up. Please fix it.

**Comment by varshar16** [comment]
Also split the commit into different commits to fix a single type of error.

**Comment by ADI10HERO** [comment]
@varshar16 Rebased 2.0 xD

**Comment by varshar16** [comment]
Commit title still needs to be fixed. Read this part again: https://github.com/ceph/ceph/blob/master/SubmittingPatches.rst#commit-title
Don't add line number in commit title and use

**Comment by ADI10HERO** [comment]
1. Just one space before "Fixes" ?
Or you want me to indent it along with the lines above it?

2. Signed-off line needs any modification? 

3. So i got to change "made x change at line y, z, w" to
     A. "Made x change in abc function"
     Or
     B. "Made x change" 

And I fixed only the 6 mentioned bugs in the tracker ticket, didn't I?

**Comment by varshar16** [comment]
> @varshar16
> 
>     1. Just one space before "Fixes" ?
>        Or you want me to indent it along with the lines above it?
> 
Just add a blank line.

>     2. Signed-off line needs any modification?
> 
It is fine.

>     3. So i got to change "made x change at line y, z, w" to
>        A. "Made x change in abc function"
Preferably this one.

>        Or
>        B. "Made x change"
> 
> 
> And I fixed only the 6 mentioned bugs in the tracker ticket, didn't I?

No. You need to fix errors starting from `line 1488`.

**Comment by ADI10HERO** [comment]
@varshar16 
Should I rebase or Can I just commit undoing the changes not in the tracker?

**Comment by ADI10HERO** [comment]
Hi @varshar16 ,
I hope I did it correct this time
- Imperative mood
- Blank line before "Fixes: "
- Changes from line 1488
- No line numbers in commit messages
- Specified function name whenever possible

**Comment by ADI10HERO** [comment]
> The commits look better. 

Thankyou :)
> Title of commit [66a72e8](https://github.com/ceph/ceph/commit/66a72e8f4ab1abdf40264fd7730beb43d6384af1) is not right. Two blank lines are required between functions. See pep 8 [style guide](https://www.python.org/dev/peps/pep-0008/#blank-lines).

Yeah I know about pep8 styles, but couldn't think of a short-sweet yet imperative mood title, can i use ```Two blank lines are required between functions``` as title?
 
> Even title of this commit [669e8d0](https://github.com/ceph/ceph/commit/669e8d0e15ba186c41da0ab69226195b7824be43) can be shortened: Indent 'under-indented' code in read_ceph_conf()

Willl change that now.
<hr>
Strict git discipline is followed in ceph I see :D, its exhilarating!! Getting to learn a lot :)

**Comment by varshar16** [comment]
> > The commits look better.
> 
> Thankyou :)
> 
> > Title of commit [66a72e8](https://github.com/ceph/ceph/commit/66a72e8f4ab1abdf40264fd7730beb43d6384af1) is not right. Two blank lines are required between functions. See pep 8 [style guide](https://www.python.org/dev/peps/pep-0008/#blank-lines).
> 
> Yeah I know about pep8 styles, but couldn't think of a short-sweet yet imperative mood title, can i use `Two blank lines are required between functions` as title?
> 
No, don't use it. Maybe something like "Add blank line before & after get_bool_vals_for_boolopts() definition"

> > Even title of this commit [669e8d0](https://github.com/ceph/ceph/commit/669e8d0e15ba186c41da0ab69226195b7824be43) can be shortened: Indent 'under-indented' code in read_ceph_conf()
> 
> Willl change that now.
> Strict git discipline is followed in ceph I see :D, its exhilarating!! Getting to learn a lot :)

**Comment by ADI10HERO** [comment]
@varshar16 Made those changes :)

**Comment by varshar16** [comment]
> Looks good but I'll prefer to have all changes under a single commit since 27 line of changes across 6 commits is a bit too much.

Preferred way is to group logical changes into individual commits. See https://github.com/ceph/ceph/blob/master/SubmittingPatches.rst#separate-your-changes

**Comment by rishabh-d-dave** [comment]
IMHO, a single small commit in log saying "fix flake8 errors" is more preferable than a series of further smaller commits describing 2-4 lines of change. That said, I'll approve the PR since I agree with set of changes here and leave how the code should be arranged to you and the PR author.  :)

**Comment by varshar16** [comment]
> IMHO, a single small commit in log saying "fix flake8 errors" is more preferable than a series of further smaller commits describing 2-4 lines of change. That said, I'll approve the PR since I agree with set of changes here and leave how the code should be arranged to you and the PR author. :)

I understand but then we may end up with many commits titled fix flake8 errors. It will be easier to differentiate with a brief description of flake8 errors.

**Comment by rishabh-d-dave** [comment]
> I understand but then we may end up with many commits titled fix flake8 errors. It will be easier to differentiate with a brief description of flake8 errors.

We add a description to the commit message to avoid that kind of confusion.

**Comment by varshar16** [comment]
> > I understand but then we may end up with many commits titled fix flake8 errors. It will be easier to differentiate with a brief description of flake8 errors.
> 
> We add a description to the commit message to avoid that kind of confusion.

Usually for preparing release changelog only commit title is used.
@gregsfortytwo Let us know the preferred way here.

**Comment by varshar16** [comment]
Tests have passed: http://pulpito.ceph.com/varsha-2020-04-03_15:00:00-fs-wip-varsha-testing-distro-basic-smithi/

**Comment by gregsfortytwo** [comment]
I'd probably try and stick "flake8" at the beginning of the commit message and then describe the fix, or just name flake8 and the file. These look fine to me as-is, though.

**Comment by gregsfortytwo** [comment]
http://pulpito.front.sepia.ceph.com/gregf-2020-04-21_21:12:13-fs-wip-greg-testing-421-1-distro-basic-smithi/ looks good; few infra bugs and known issues

**Pull request merged**
