### PR TITLE
mimic: core: Health warnings on long network ping times

### PR DESCRIPTION
**Pull request by dzafman**
https://tracker.ceph.com/issues/41696

### CODE REVIEW

**Comment by dzafman** [comment]
Need to merge ceph/ceph#30220 first in case sha1 changes.

**Comment by dzafman** [comment]
jenkins test make check

**Comment by smithfarm** [comment]
@dzafman Sorry, other mimic PRs got merged and this one now needs rebasing.

**Comment by smithfarm** [comment]
```
1 tests failed out of 157

Total Test time (real) = 3768.40 sec

The following tests FAILED:
	125 - unittest_chain_xattr (Timeout)
```

**Comment by smithfarm** [comment]
jenkins test make check

**Comment by yuriw** [comment]
[wip-yuri3-testing-2019-10-22-1848-mimic](https://trello.com/c/R54td5wd/729-wip-yuri3-testing-2019-10-22-1848-mimic)

**Comment by batrick** [comment]
Causes: https://tracker.ceph.com/issues/42570

**Pull request merged**
