### PR TITLE
octopus: os/bluestore: fix erroneous SharedBlob record removal during repair

### PR DESCRIPTION
**Pull request by ifed01**
backport tracker: https://tracker.ceph.com/issues/51650
backport of #42267 
parent tracker: https://tracker.ceph.com/issues/51619

Signed-off-by: Igor Fedotov <ifedotov@suse.com>

## Checklist
- [x] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Review by neha-ojha — APPROVED** [review]

**Review by tchaikov — APPROVED** [review]

**Comment by ideepika** [comment]
@ifed01 do we also need this change in pacific, if that's the case can we also have it's backport, thanks!

**Comment by ifed01** [comment]
> @ifed01 do we also need this change in pacific, if that's the case can we also have it's backport, thanks!

@ideepika - here it is: https://github.com/ceph/ceph/pull/42423

**Comment by ideepika** [comment]
> > @ifed01 do we also need this change in pacific, if that's the case can we also have it's backport, thanks!
> 
> @ideepika - here it is: https://github.com/ceph/ceph/pull/42423

Awesome! Thanks @ifed01 ! @yuriw can you add it to your testing batch, thanks!

**Comment by neha-ojha** [comment]
pacific PR https://github.com/ceph/ceph/pull/42423 waiting on testing

**Pull request merged**
