### PR TITLE
rgw: `radosgw-admin bucket stats` on indexless bucket crashes

### PR DESCRIPTION
**Pull request by ivancich**
The new bucket layout code didn't check whether the bucket is
indexless prior to asking for the last entry in the layout log. The
layout log appears to be empty for an indexless bucket, thereby
putting the runtime in an undefined state that later may cause a
failed assertion.

This commit adds two safety checks and returns -EINVAL along with
putting useful information on stderr when either stats are requested
on an indexless bucket or when the layout log is empty.

Signed-off-by: J. Eric Ivancich <ivancich@redhat.com>

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by ivancich** [comment]
@cbodley : unclear of all the rules with this branch...is a tracker needed?

**Comment by ivancich** [comment]
Steps to Reproduce:
1. radosgw-admin zonegroup placement add --rgw-zonegroup="default" --placement-id="indexless-placement"
2. radosgw-admin zone placement add --rgw-zone="default" --placement-id="indexless-placement" --data-pool="default.rgw.buckets.data" --index-pool="default.rgw.buckets.index" --data_extra_pool="default.rgw.buckets.non-ec" --placement-index-type="indexless"
3. radosgw-admin zonegroup placement default --placement-id="indexless-placement"
4. Restart the service
5. Create a bucket using boto3
6. Upload an object to the newly created bucket using boto3
7. radosgw-admin bucket stats --bucket <name>

**Review by mattbenjamin — APPROVED** [review]
I don't know what side effects this change could have, but, as far as it goes, it seems correct

**Comment by ivancich** [comment]
jenkins test make check

**Comment by ivancich** [comment]
jenkins test docs

**Comment by cbodley** [comment]
looks good, thanks @ivancich. we haven't been using tracker issues for this branch, i just cherry-pick things to it after manual testing

**Comment by ivancich** [comment]
jenkins test make check

**Pull request merged**
