### PR TITLE
crimson: capture "this" explicitly

### PR DESCRIPTION
**Pull request by tchaikov**
to silence warnings like:

```
alien_store.cc:577:64: warning: implicit capture of ‘this’ via ‘[=]’ is deprecated in C++20 [-Wdeprecated]
 577 |     return
 tp->submit(ch->get_cid().hash_to_shard(tp->size()),
  [=, &bl] {
  |
  ^
```

this change is a follow-up of a11d7eb0a845e819f35f9a099c17f9706702cfa7

some warnings were not spotted by then.

Signed-off-by: Kefu Chai <tchaikov@gmail.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [x] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by tchaikov** [comment]
this change is a subset of #47423. it is extracted to a dedicated PR in hope to get reviewed and merged sooner.

**Review by athanatos — APPROVED** [review]

**Comment by cyx1231st** [comment]
I saw more warning related to "this" issue, see https://github.com/ceph/ceph/pull/47425/commits/2792d8421e44169f74dd3d85e67bc8bd6d06de9e

Will split the commit to a PR.

**Comment by cyx1231st** [comment]
see https://github.com/ceph/ceph/pull/47426

**Comment by tchaikov** [comment]
jenkins test make check

**Comment by tchaikov** [comment]
closing in favor of #47426

**Pull request closed without merging**
