### PR TITLE
mgr/dashboard: block mirroring page results in internal server error

### PR DESCRIPTION
**Pull request by dillaman**
## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>
Fixes: https://tracker.ceph.com/issues/43029

### CODE REVIEW

**Comment by s0nea** [comment]
Hi @dillaman and @epuertat can you tell which test suites are required in order to get the pull request tested?

**Comment by dillaman** [comment]
@s0nea If you can run it through rados/mgr, I think we are good-to-go.

**Comment by s0nea** [comment]
> @s0nea If you can run it through rados/mgr and rados/dashboard, I think we are good-to-go.

Thanks, I'll take care of it.

**Comment by s0nea** [comment]
rados/dashboard: http://pulpito.ceph.com/compare/?branch=wip-tdehler-testing-31907&suite=rados:dashboard
QA test run was successful. The failure is caused by https://tracker.ceph.com/issues/43192

rados/mgr: http://pulpito.ceph.com/compare/?branch=wip-tdehler-testing-31907&suite=rados:mgr
Some jobs failed or are dead. I'm re-running them currently.

**Comment by s0nea** [comment]
Unfortunately a few jobs failed again: http://pulpito.ceph.com/compare/?branch=wip-tdehler-testing-31907&suite=rados:mgr
@dillaman could you please possibly check if they're related?

**Comment by dillaman** [comment]
No, they don't look related:

> 2019-12-06T11:21:48.005 INFO:tasks.cephfs_test_runner:AssertionError: {u'insights_health_check_0': {u'HEALTH_WARN': {u'detail': [u'detail'], u'summary': [u'summary']}}, u'insights_health_check': {u'HEALTH_WARN': {u'detail': [u'detail'], u'summary': [u'summary']}}} is not false

> 2019-12-06T13:42:05.832 INFO:tasks.cephfs_test_runner:CommandFailedError: Command failed on mira088 with status 124: 'sudo adjust-ulimits ceph-coverage /home/ubuntu/cephtest/archive/coverage timeout 120 ceph --cluster ceph mgr self-test module diskprediction_local'

> 2019-12-06T11:20:30.417 INFO:teuthology.orchestra.run.mira057.stderr:2019-12-06T11:20:30.411+0000 7f17305cd700 20 mgrc start_command cmd: [{"prefix": "orchestrator host add", "host": "raise_bug", "target": ["mon-mgr", ""]}]
> 2019-12-06T11:20:30.417 INFO:teuthology.orchestra.run.mira057.stderr:2019-12-06T11:20:30.411+0000 7f17305cd700  1 -- 172.21.6.136:0/1174929895 --> [v2:172.21.6.136:6812/14892,v1:172.21.6.136:6813/14892] -- mgr_command(tid 0: {"prefix": "orchestrator host add", "host": "raise_bug", "target": ["mon-mgr", ""]}) v1 -- 0x7f17280554e0 con 0x7f1710056a60
> 2019-12-06T11:20:30.421 INFO:tasks.ceph.mgr.x.mira057.stderr:2019-12-06T11:20:30.419+0000 7f7ed326e700 -1 mgr handle_command module 'orchestrator_cli' command handler threw exception:
> 2019-12-06T11:20:30.424 INFO:tasks.ceph.mgr.x.mira057.stderr:2019-12-06T11:20:30.419+0000 7f7ed326e700 -1 mgr.server reply reply (22) Invalid argument Traceback (most recent call last):
> 2019-12-06T11:20:30.424 INFO:tasks.ceph.mgr.x.mira057.stderr:  File "/usr/share/ceph/mgr/mgr_module.py", line 1062, in _handle_command
> 2019-12-06T11:20:30.424 INFO:tasks.ceph.mgr.x.mira057.stderr:    return CLICommand.COMMANDS[cmd['prefix']].call(self, cmd, inbuf)
> 2019-12-06T11:20:30.424 INFO:tasks.ceph.mgr.x.mira057.stderr:  File "/usr/share/ceph/mgr/mgr_module.py", line 303, in call
> 2019-12-06T11:20:30.424 INFO:tasks.ceph.mgr.x.mira057.stderr:    return self.func(mgr, **kwargs)
> 2019-12-06T11:20:30.424 INFO:tasks.ceph.mgr.x.mira057.stderr:  File "/usr/share/ceph/mgr/orchestrator.py", line 131, in wrapper
> 2019-12-06T11:20:30.425 INFO:tasks.ceph.mgr.x.mira057.stderr:    return func(*args, **kwargs)
> 2019-12-06T11:20:30.425 INFO:tasks.ceph.mgr.x.mira057.stderr:  File "/usr/share/ceph/mgr/orchestrator_cli/module.py", line 154, in _add_host
> 2019-12-06T11:20:30.425 INFO:tasks.ceph.mgr.x.mira057.stderr:    orchestrator.raise_if_exception(completion)
> 2019-12-06T11:20:30.425 INFO:tasks.ceph.mgr.x.mira057.stderr:  File "/usr/share/ceph/mgr/orchestrator.py", line 631, in raise_if_exception
> 2019-12-06T11:20:30.425 INFO:tasks.ceph.mgr.x.mira057.stderr:    raise e
> 2019-12-06T11:20:30.425 INFO:tasks.ceph.mgr.x.mira057.stderr:ZeroDivisionError
>

**Comment by callithea** [comment]
> Unfortunately a few jobs failed again: http://pulpito.ceph.com/compare/?branch=wip-tdehler-testing-31907&suite=rados:mgr
> @dillaman could you please check if they're related?

(sorry, did not mean to edit the original message, @s0nea)

FYI:
`test_mon_update` (should be fixed, the related PR has been merged two days ago):
- https://tracker.ceph.com/issues/43132

`test_health_history`:
- https://tracker.ceph.com/issues/38539

**Comment by s0nea** [comment]
I'm removing my test labels now. Please re-add them if you think there is anything left to do.

**Comment by dillaman** [comment]
> I'm removing my test labels now. Please re-add them if you think there is anything left to do.

merge? :man_shrugging:

**Comment by LenzGr** [comment]
LGTM, but I'm hesitant to merge this one myself, as it touches C++ code...
@liewegas or @tchaikov - could you take care of merging this one?

**Pull request merged**
