### PR TITLE
jewel: build/ops: fixed compilation error when --with-radowsgw=no

### PR DESCRIPTION
**Pull request by liupan1111**
If cannot disable radosgw, the user has to always compile radosgw part, even only want to use block device or file storage. Cherry-pick cannot be done because ceph master doesn't have Makefile.am any more.

http://tracker.ceph.com/issues/18512

### CODE REVIEW

**Comment by liupan1111** [comment]
@dachary, Any comment?

**Comment by tchaikov** [comment]
tested. it does address the FTBFS with "--with-radowsgw=no". 

lgtm.

**Comment by dachary** [comment]
@liupan1111 could you please amend the commit message to explain why they are not cherry-picked from master ? Is there an issue open that relates to this problem ?

**Comment by liupan1111** [comment]
@dachary done, thanks.

**Comment by tchaikov** [comment]
> could you please amend the commit message to explain why they are not cherry-picked from master ?
this comment is not addressed.

@liupan1111 you were revising the comment of this PR, but not the commit message.

**Comment by tchaikov** [comment]
@liupan1111  could you take a look at https://github.com/ceph/ceph/pull/12857? seems it failed to get your attention.

**Comment by liupan1111** [comment]
>  you were revising the comment of this PR, but not the commit message
Yeah... will update. Thanks.

**Comment by liupan1111** [comment]
> could you take a look at #12857? seems it failed to get your attention.

Just comment, sorry for the late.

**Comment by liupan1111** [comment]
@tchaikov done, thanks.

**Comment by smithfarm** [comment]
OK, I will include this in the next integration round.

**Comment by dachary** [comment]
It passed the rgw suite at http://tracker.ceph.com/issues/17851#note-66.

Please **git cherry-pick -x** the commits and repush (same as the other pull request). Thanks !

**Comment by liupan1111** [comment]
@dachary , is this one similar as #12239?

**Comment by dachary** [comment]
yes

**Pull request merged**
