### PR TITLE
Revert "os/bluestore: use single allocator for shared bluestore/bluef…

### PR DESCRIPTION
**Pull request by tchaikov**
Reverts ceph/ceph#30838

for testing https://tracker.ceph.com/issues/46886

### CODE REVIEW

**Comment by tchaikov** [comment]
retesting the failed upgrade test at https://pulpito.ceph.com/kchai-2020-08-15_04:27:27-rados-wip-kefu-testing-2020-08-14-1457-distro-basic-smithi/

**Comment by neha-ojha** [comment]
@ifed01 will you have time to look at https://tracker.ceph.com/issues/46886 soon enough? else we can go ahead with this revert.

**Comment by ifed01** [comment]
> @ifed01 will you have time to look at https://tracker.ceph.com/issues/46886 soon enough? else we can go ahead with this revert.

@neha-ojha - yeah, looking into this.. Hopefully will submit a fix soon

**Comment by yuriw** [comment]
[wip-yuri3-testing-2020-08-10-1537-master (old wip-35628-2020-07-28)](https://trello.com/c/G7zQZKfe/981-wip-yuri3-testing-2020-08-10-1537-master-old-wip-35628-2020-07-28)

**Pull request closed without merging**
