### PR TITLE
debian: package mgr/rgw in ceph-mgr-modules-core

### PR DESCRIPTION
**Pull request by tchaikov**
in 110db72e, we added the rgw mgr module to ceph-mgr-modules-core rpm package. but we didn't add this module to the corresponding debian package.

rgw mgr module provides a simple interface to deploy RGW multisite setup. so it would be nice to have it in ceph's debian packages as well.

despite that rgw is not part of the core features, since this module is already in ceph-mgr-modules-core rpm package, and it is relatively small and does not pulling extra dependencies, let's added to the debian packge with the same name. we can revisit this decision and extract it out in a following up change if it is necessary in future.

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Comment by tchaikov** [comment]
being built at https://shaman.ceph.com/builds/ceph/wip-debian-mgr-rgw-kefu/53f992810aaf6788c7c27244327cdcc3427c938c/

**Comment by mcv21** [comment]
Thanks for this, looks good to me :)

**Review by idryomov — APPROVED** [review]
Also tagging @ceph/rgw for an ack.

**Comment by mcv21** [comment]
Is it going to be possible to get this backported to squid/reef, please?

**Comment by k0ste** [comment]
> Is it going to be possible to get this backported to squid/reef, please?

If someone create tracker issue...

**Comment by mcv21** [comment]
https://tracker.ceph.com/issues/66326 opened.

**Pull request merged**
