### PR TITLE
cmake: s/bortli_libs/brotli_libs/

### PR DESCRIPTION
**Pull request by tchaikov**
it's merely a typo.

Signed-off-by: Kefu Chai <kchai@redhat.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`

</details>

### CODE REVIEW

**Comment by tchaikov** [comment]
retest this please.

**Comment by tchaikov** [comment]
jenkins test ceph-volume tox

**Comment by tchaikov** [comment]
jenkins test ceph-volume tox

**Comment by cbodley** [comment]
a few `Unable to find executable:` errors from ctest prevented it from running all of the tests. is that somehow related?

**Comment by tchaikov** [comment]
jenkins test docs

**Comment by tchaikov** [comment]
jenkins test make check

**Comment by tchaikov** [comment]
@cbodley no, it's not related.

**Comment by tchaikov** [comment]
http://pulpito.ceph.com/kchai-2019-09-14_01:11:05-rados-wip-kefu-testing-2019-09-14-0046-distro-basic-mira/

**Pull request merged**
