### PR TITLE
quincy: msg: fix deadlock when handling existing but closed v2 connection

### PR DESCRIPTION
**Pull request by rzarzynski**
backport tracker: https://tracker.ceph.com/issues/56723

---

backport of https://github.com/ceph/ceph/pull/46732
parent tracker: https://tracker.ceph.com/issues/55355

this backport was staged using ceph-backport.sh version 16.0.0.6848
find the latest version at https://github.com/ceph/ceph/blob/main/src/script/ceph-backport.sh

### CODE REVIEW

**Comment by idryomov** [comment]
jenkins test make check

**Review by idryomov — APPROVED** [review]

**Comment by yuriw** [comment]
jenkins test make check

**Comment by ljflores** [comment]
Rados suite review: http://pulpito.front.sepia.ceph.com/?branch=wip-yuri10-testing-2022-09-04-0811-quincy

Failures, unrelated:
    1. https://tracker.ceph.com/issues/56951
    2. https://tracker.ceph.com/issues/57165
    3. https://tracker.ceph.com/issues/57368
    4. https://tracker.ceph.com/issues/57290 -- pending Quincy backport
    5. https://tracker.ceph.com/issues/57386
    6. https://tracker.ceph.com/issues/52124 -- pending Quincy backport
    7. https://tracker.ceph.com/issues/49524

Details:
    1. rook/smoke: Updating cephclusters/rook-ceph is forbidden - Ceph - Orchestrator
    2. expected valgrind issues and found none - Ceph - RADOS
    3. The CustomResourceDefinition "installations.operator.tigera.io" is invalid: metadata.annotations: Too long: must have at most 262144 bytes - Ceph - RADOS
    4. orch/cephadm: task/test_cephadm failure due to: ERROR: A cluster with the same fsid '00000000-0000-0000-0000-0000deadbeef' already exists. - Ceph - Orchestrator
    5. cephadm/test_dashboard_e2e.sh: Expected to find content: '/^foo$/' within the selector: 'cd-modal .badge' but never did - Ceph - Mgr - Dashboard
    6. Invalid read of size 8 in handle_recovery_delete() - Ceph - RADOS
    7. rados/test.sh: api_watch_notify failures - Ceph - RADOS

**Comment by yuriw** [comment]
jenkins test make check

**Pull request merged**
