### PR TITLE
qa/upgrade: consistently use the tip of the branch as the start version

### PR DESCRIPTION
**Pull request by yuriw**
Also corrected line to use image: quay.ceph.io/ceph-ci/ceph:* In order to make sure that latest versions of ceph is used as initial install

Fixes: https://tracker.ceph.com/issues/58914

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [x] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Review by jdurgin — APPROVED** [review]

**Comment by ljflores** [comment]
jenkins test api

**Comment by yuriw** [comment]
@ljflores 

I think a run of `pacific-x` is not needed for the `main` ATM

https://pulpito.ceph.com/yuriw-2023-03-30_18:08:11-upgrade:quincy-x-main-distro-default-smithi

**Review by idryomov — COMMENTED** [review]
This seems right to me (as opposed to https://github.com/ceph/ceph/pull/50747 and https://github.com/ceph/ceph/pull/50758) but I'm holding the approval until the standing of those PRs is clarified in case it's just my confusion.

**Review by idryomov — APPROVED** [review]
Approving following discussion in #50747.  Please update the commit title accordingly.

**Pull request merged**
