### PR TITLE
doc: update get-involved for cephfs

### PR DESCRIPTION
**Pull request by joscollin**
## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by joscollin** [comment]
jenkins render docs

**Comment by joscollin** [comment]
jenkins render docs

**Review by batrick — APPROVED** [review]

**Comment by joscollin** [comment]
jenkins render docs

**Comment by joscollin** [comment]
jenkins render docs

**Comment by joscollin** [comment]
jenkins render docs

**Comment by joscollin** [comment]
jenkins retest this please

**Comment by joscollin** [comment]
Merged after checking the `docs/readthedocs.org:ceph` jenkins build.

**Pull request merged**
