### PR TITLE
luminous: os/bluestore: backport fixes around _reap_collection

### PR DESCRIPTION
**Pull request by ifed01**

### CODE REVIEW

**Comment by xiexingguo** [comment]
@ifed01 Can you switch to using the `-x` option for backporting so we don't lost track of original fix in master? Thanks!

**Comment by smithfarm** [comment]
@ifed01 Also, is this the fix for https://tracker.ceph.com/issues/21259 ? For backporting purposes it's good to have a tracker associated with the PR.

**Comment by ifed01** [comment]
@xiexingguo @smithfarm - updated with -x flag

**Comment by ifed01** [comment]
> @ifed01 Also, is this the fix for https://tracker.ceph.com/issues/21259 ? For backporting purposes it's good (but not required) to have a tracker associated with the PR.

@smithfarm - there are SOME chances it  fixes this ticket but  I can't reproduce the bug so far. And still unable to 100% explain what happens there. Hence I'd refrain from linking to that ticket. 
But anyway the current _reap_collection implementation in Luminous look invalid hence backporting...

**Comment by smithfarm** [comment]
@ifed01 Could you go over the cherry-picks to make sure they are really from master? I checked the first one only - it is not present in master.

If you need to resolve conflicts, the commit message should include a "Conflicts" section indicating which files contained the conflicts (ideally along with a brief commentary).

**Comment by ifed01** [comment]
@smithfarm - sorry, cherry picked wrong commits. Fixed.

**Comment by yuriw** [comment]
[wip-yuri5-testing-2018-03-27-1535-luminous](https://trello.com/c/0zxXqm9m/281-wip-yuri5-testing-2018-03-27-1535-luminous)

**Pull request merged**
