### PR TITLE
mgr/dashboard: Feature 54330 osd creation workflow 

### PR DESCRIPTION
**Pull request by pereman2**
## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/master/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [x] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [x] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [x] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Review by nizamial09 — APPROVED** [review]

**Comment by epuertat** [comment]
jenkins test dashboard

**Comment by epuertat** [comment]
jenkins test dashboard cephadm

**Comment by epuertat** [comment]
[e2e failure](https://jenkins.ceph.com/job/ceph-dashboard-pull-requests/10752/consoleFull#-206978584273a8703b-5adb-41c5-84a0-8cf4e065ba3d):
```
 Notification page
    1) "before all" hook for "should open notification sidebar"
    2) "after all" hook for "should open notification sidebar"


  0 passing (8s)
  2 failing

  1) Notification page
       "before all" hook for "should open notification sidebar":
     CypressError: `cy.type()` failed because it targeted a disabled element.

The element typed into was:

  > <input _ngcontent-aro-c323="" id="pgNum" name="pgNum" formcontrolname="pgNum" min="1" type="number" required="" class="form-control ng-untouched ng-pristine ng-valid" ng-reflect-form-control-name="pgNum" ng-reflect-name="pgNum" ng-reflect-min="1" ng-reflect-required="">

Ensure the element does not have an attribute named `disabled` before typing into it.

https://on.cypress.io/type

Because this error occurred during a `before all` hook we are skipping the remaining tests in the current suite: `Notification page`

Although you have test retries enabled, we do not retry tests when `before all` or `after all` hooks fail
      at https://172.21.5.36:41950/__cypress/runner/cypress_runner.js:154002:86
      at tryCatcher (https://172.21.5.36:41950/__cypress/runner/cypress_runner.js:13212:23)
      at Promise._settlePromiseFromHandler (https://172.21.5.36:41950/__cypress/runner/cypress_runner.js:11147:31)
      at Promise._settlePromise (https://172.21.5.36:41950/__cypress/runner/cypress_runner.js:11204:18)
      at Promise._settlePromise0 (https://172.21.5.36:41950/__cypress/runner/cypress_runner.js:11249:10)
      at Promise._settlePromises (https://172.21.5.36:41950/__cypress/runner/cypress_runner.js:11329:18)
      at _drainQueueStep (https://172.21.5.36:41950/__cypress/runner/cypress_runner.js:7919:12)
      at _drainQueue (https://172.21.5.36:41950/__cypress/runner/cypress_runner.js:7912:9)
      at ../../node_modules/bluebird/js/release/async.js.Async._drainQueues (https://172.21.5.36:41950/__cypress/runner/cypress_runner.js:7928:5)
      at Async.drainQueues (https://172.21.5.36:41950/__cypress/runner/cypress_runner.js:7798:14)
  From Your Spec Code:
      at PoolPageHelper.edit_pool_pg (https://172.21.5.36:41950/__cypress/tests?p=cypress/integration/ui/notification.e2e-spec.ts:327:37)
      at Context.eval (https://172.21.5.36:41950/__cypress/tests?p=cypress/integration/ui/notification.e2e-spec.ts:378:15)

  2) Notification page
       "after all" hook for "should open notification sidebar":
     CypressError: `cy.click()` failed because it requires a DOM element.

The subject received was:

  > `undefined`

The previous command that ran was:

  > `cy.get()`

Because this error occurred during a `after all` hook we are skipping the remaining tests in the current suite: `Notification page`

Although you have test retries enabled, we do not retry tests when `before all` or `after all` hooks fail
      at ensureElement (https://172.21.5.36:41950/__cypress/runner/cypress_runner.js:162713:85)
      at validateType (https://172.21.5.36:41950/__cypress/runner/cypress_runner.js:162538:18)
      at Object.ensureSubjectByType (https://172.21.5.36:41950/__cypress/runner/cypress_runner.js:162574:11)
      at pushSubjectAndValidate (https://172.21.5.36:41950/__cypress/runner/cypress_runner.js:171783:17)
      at Context.<anonymous> (https://172.21.5.36:41950/__cypress/runner/cypress_runner.js:172119:20)
  From Your Spec Code:
      at PageHelper.delete (https://172.21.5.36:41950/__cypress/tests?p=cypress/integration/ui/notification.e2e-spec.ts:257:50)
      at Context.eval (https://172.21.5.36:41950/__cypress/tests?p=cypress/integration/ui/notification.e2e-spec.ts:384:21)
```

**Comment by epuertat** [comment]
jenkins test dashboard

**Comment by epuertat** [comment]
[cephadm failure](https://jenkins.ceph.com/job/ceph-dashboard-cephadm-e2e/3794/consoleFull#200605192773a8703b-5adb-41c5-84a0-8cf4e065ba3d):
```
Host Page
    ✓ should create rgw services (9910ms)
    1) should check if rgw daemon is running on all hosts
    ✓ should force maintenance and exit (23790ms)
    ✓ should drain, remove and add the host back (61027ms)


  3 passing (2m)
  1 failing

  1) Host Page
       should check if rgw daemon is running on all hosts:
     Error: The following error originated from your application code, not from Cypress.

  > NG0100: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'A few seconds ago'. Current value: 'A minute ago'.. Find more at https://angular.io/errors/NG0100

When Cypress detects uncaught errors originating from your application it will automatically fail the current test.

This behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.

[https://on.cypress.io/uncaught-exception-from-application](https://on.cypress.io/uncaught-exception-from-application%1B[0m%1B[90m)
      at throwErrorIfNoChangesMode (https://192.168.100.100:8443/vendor.js:21228:11)
      at bindingUpdated (https://192.168.100.100:8443/vendor.js:27441:17)
      at interpolation1 (https://192.168.100.100:8443/vendor.js:27548:23)
      at Module.ɵɵtextInterpolate1 (https://192.168.100.100:8443/vendor.js:31953:26)
      at ServiceDaemonListComponent_ng_template_6_ul_0_li_1_Template (https://192.168.100.100:8443/main.js:13360:70)
      at executeTemplate (https://192.168.100.100:8443/vendor.js:24051:9)
      at refreshView (https://192.168.100.100:8443/vendor.js:23917:13)
      at refreshEmbeddedViews (https://192.168.100.100:8443/vendor.js:25042:17)
      at refreshView (https://192.168.100.100:8443/vendor.js:23941:9)
      at refreshEmbeddedViews (https://192.168.100.100:8443/vendor.js:25042:17)
```

**Comment by epuertat** [comment]
jenkins test dashboard cephadm

**Comment by avanthakkar** [comment]
jenkins test dashboard cephadm

**Review by avanthakkar — APPROVED** [review]

**Comment by epuertat** [comment]
Dashboard End-to-End Test Failure (Cypress)

[1 of 10 failed (10%)](https://tracker.ceph.com/issues/55741,)

**Pull request merged**
