### PR TITLE
quincy: test: No direct use of nose

### PR DESCRIPTION
**Pull request by tserong**
backport tracker: https://tracker.ceph.com/issues/55615

---

backport of https://github.com/ceph/ceph/pull/45064
parent tracker: https://tracker.ceph.com/issues/54252

this backport was staged using ceph-backport.sh version 16.0.0.6848
find the latest version at https://github.com/ceph/ceph/blob/master/src/script/ceph-backport.sh

### CODE REVIEW

**Comment by tserong** [comment]
jenkins test api

**Comment by tserong** [comment]
jenkins test windows

**Comment by ljflores** [comment]
http://pulpito.front.sepia.ceph.com/yuriw-2022-05-19_18:50:25-rados-wip-yuri4-testing-2022-05-19-0831-quincy-distro-default-smithi/

Failures, unrelated:
    1. https://tracker.ceph.com/issues/52321
    2. https://tracker.ceph.com/issues/52657
    3. https://tracker.ceph.com/issues/51076

Details:
    1. qa/tasks/rook times out: 'check osd count' reached maximum tries (90) after waiting for 900 seconds - Ceph - Orchestrator
    2. MOSDPGLog::encode_payload(uint64_t): Assertion `HAVE_FEATURE(features, SERVER_NAUTILUS)' - Ceph - RADOS
    3. "wait_for_recovery: failed before timeout expired" during thrashosd test with EC backend. - Ceph - RADOS

**Review by yuriw — APPROVED** [review]
Reviewed-by: Casey Bodley <cbodley@redhat.com>

**Pull request merged**
