### PR TITLE
rgw: adding option /--rgw_mallopt/ , in which set ARENA_MAX

### PR DESCRIPTION
**Pull request by galsalomon66**
MMAP_THRESHOLD to optimize radosgw memory-consumption

fixes: https://tracker.ceph.com/issues/41425

Signed-off-by: gal salomon <gsalomon@dhcp-4-164.tlv.redhat.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`

</details>

### CODE REVIEW

**Comment by galsalomon66** [comment]
jenkins test make check

**Comment by mattbenjamin** [comment]
@galsalamon66 this actually works only when radosgw iis build with libc malloc, right?

**Comment by markhpc** [comment]
@mattbenjamin FWIW, I'm thinking about the possibility of using the prioritycachemanager in RGW to keep the overall process size close to a hypothetical rgw_memory_target similar to what we do in the OSD.  Right now that would only work with tcmalloc though.

Does RGW tend to do better with any specific memory allocator?

**Comment by galsalomon66** [comment]
> @mattbenjamin FWIW, I'm thinking about the possibility of using the prioritycachemanager in RGW to keep the overall process size close to a hypothetical rgw_memory_target similar to what we do in the OSD. Right now that would only work with tcmalloc though.
> 
> Does RGW tend to do better with any specific memory allocator?

*) as for /prioritycachemanager/ will check that issue separately.
*) need to benchmark Libc.vs.TCmalloc (with radosgw) , and then make a decision. TPCDS runs "challenged" Libc-alloctor and cause memory growth, those parameters fix that (its give tuning options) .

**Comment by galsalomon66** [comment]
> @mattbenjamin FWIW, I'm thinking about the possibility of using the prioritycachemanager in RGW to keep the overall process size close to a hypothetical rgw_memory_target similar to what we do in the OSD. Right now that would only work with tcmalloc though.
> 
> Does RGW tend to do better with any specific memory allocator?

should bare in mind that it gives the user an indication whether RGW is leaking or not, without that its difficult to know that.

**Comment by galsalomon66** [comment]
> @galsalamon66 this actually works only when radosgw iis build with libc malloc, right?

correct, works only with libc-malloc , has no impact on tcmalloc (it has its own options).

**Comment by cbodley** [comment]
needs rebase

**Pull request closed without merging**
