### PR TITLE
kv/RocksDBStore: implement rm_range_keys operator interface and test

### PR DESCRIPTION
**Pull request by yuyuyu101**
Signed-off-by: Haomai Wang <haomai@xsky.com>

### CODE REVIEW

**Comment by yuyuyu101** [comment]
replacing #11198

**Comment by liewegas** [comment]
// Removes the database entries in the range ["begin_key", "end_key"), i.e.,
  // including "begin_key" and excluding "end_key". Returns OK on success, and
  // a non-OK status on error. It is not an error if no keys exist in the range
  // ["begin_key", "end_key").
  //
  // This feature is currently an experimental performance optimization for
  // deleting very large ranges of contiguous keys. Invoking it many times or on
  // small ranges may severely degrade read performance; in particular, the
  // resulting performance can be worse than calling Delete() for each key in
  // the range. Note also the degraded read performance affects keys outside the
  // deleted ranges, and affects database operations involving scans, like flush
  // and compaction.
  //
  // Consider setting ReadOptions::ignore_range_deletions = true to speed
  // up reads for key(s) that are known to be unaffected by range deletions.

This scared me away before.  It would be great, though, to avoid the current flush() we have to do in BlueStore to support this today (to ensure recent new keys are applied so that they get deleted).  Any sense of whether this warning is as scary as it sounds?

(Also, rebase?)

**Comment by yuyuyu101** [comment]
ok, let's pending this PR. because I see active contributes on this area in rocksdb upstream. compared before, this api just can work.

**Comment by liewegas** [comment]
we could add this api, use it, and just make a rocksdb config option 
controlling whether we do the iterate-and-delete or delete range...

**Comment by yuyuyu101** [comment]
retest this please

**Comment by liewegas** [comment]
2017-03-23T23:35:50.279 INFO:teuthology.orchestra.run.smithi028.stdout:[  FAILED  ] KeyValueDB/KVTest.RMRange/0, where GetParam() = "leveldb"
2017-03-23T23:35:50.279 INFO:teuthology.orchestra.run.smithi028.stdout:[  FAILED  ] KeyValueDB/KVTest.RMRange/1, where GetParam() = "rocksdb"
2017-03-23T23:35:50.279 INFO:teuthology.orchestra.run.smithi028.stdout:[  FAILED  ] KeyValueDB/KVTest.RMRange/2, where GetParam() = "memdb"

**Comment by yuyuyu101** [comment]
[----------] Global test environment tear-down
[==========] 21 tests from 1 test case ran. (3637 ms total)
[  PASSED  ] 21 tests.

**Comment by yuyuyu101** [comment]
fixed!

**Pull request merged**
