### PR TITLE
rgw: support store head/tail into different pools

### PR DESCRIPTION
**Pull request by mikulely**
This is the first phrase to implement s3 storage class in the rgw.
Similar work with https://github.com/ceph/ceph/pull/16325 , but this
implement is simpler.

This pr is a draft for review. Currently only passed single/multipart Get/Put
test, there're several things need to been addressed and test later:

+ object rewrite
+ object copy

@yehudasa @fangyuxiangGL  your comments are very appreciated.  ；-）

### CODE REVIEW

**Comment by fangyuxiangGL** [comment]
@mikulely 

Looks almost same as my pr except you just indroduce a flag in Manifset and use offset to get the right pool, but I'm not quite sure we really need it. the rgw_obj_select got out from RGWObjManifest::get_implicit_location is already marked as a tail object, so it will be put in the right pool surely according to current progress. I think this is redundant.

Besides, never forgot do_complete of Multipart will do write_meta, that will set some xattrs on the first tail object. As your implemention, that will introduce some redundant objects in the head pool, that is wrong.

**Comment by mikulely** [comment]
@fangyuxiangGL 

> Looks almost same as my PR except you indroduce a flag in Manifset 

The flag is used for backward compatible, already written object without using tail_data_pool would be read correctly.

> Besides, never forgot do_complete of Multipart will do write_meta, which should set some xattrs on the first tail object. As your implemention, that will introduce some redundant objects in the head pool, that is wrong.

Yes, there're objects with same name in the data/tail_data pool but server for different purpose. The one in the data pool server as metadata storage, the one in the tail data pool server as real rgw-obj data storage.

The final goal is to implement s3  storage class, if we only introduce tail_data_pool, small rgw-obj(smaller than `rgw_max_chunk_size`) would violate the storage class definition.

So we need to separate rgw-obj metadata/data into different pools, the second phrase is to store head metadata in the data pool, and head's real data into the tail_data_pool(with same object name)

**Comment by fangyuxiangGL** [comment]
> The flag is used for backward compatible, already written object without using tail_data_pool would be read correctly.

Yes, you are right.

>So we need to separate rgw-obj metadata/data into different pools, the second phrase is to store head metadata in the data pool(get_obj_state should use the data pool), and head's real data into the tail_data_pool(with same object name)

Perhaps, we have totally different idea about adding the data-tail-pool. As what mentioned in #16325 and mail list, my goal is to leverage performance and capacity. In other words, put small objects in replicated pool and large objects(or the tail portion of large objects) in erasure pool. 

Obvious, there is no specific methodology for me to  separate head and tail objects, I just aim the real require in our production.

Maybe i'm not familiar with s3 storage class, but i'd like to know how will you use this head-tail-separate in your methodology?

**Comment by mikulely** [comment]
We can leverage those requirements, Let's define a placement rule like the following:

```
    {
        "key": "STANDARD",
        "val": {
            "index_pool": "us-east-1.rgw.buckets.index",
            "data_pool": "us-east-1.rgw.buckets.3replica",
            "tail_data_pool": "us-east-1.rgw.buckets.ec",
            "data_extra_pool": "us-east-1.rgw.buckets.non-ec",
            "index_type": 0,
            "compression": "",
            "inline_head": 1
        }
    },
```

+ `inline_head = 0`  indicates that smaller object(smaller than `rgw_max_chunk_size`) would be stored in the `data_pool` , objects that bigger than `rgw_max_chunk_size`, its head would be stored in the `data_pool` , its tail would be stored in the `tail_data_pool` .(Is this the behaviour you want?)
+ `inline_head = 1`  indicates all real data of object would be stored in the `tail_data_pool` , even if object is smaller than `rgw_max_chunk_size` (this is the desired storage class behaviour)

**Comment by fangyuxiangGL** [comment]
> inline_head = 1 indicates all real data of object would be stored in the tail_data_pool , even if object is smaller than rgw_max_chunk_size (this is the desired storage class behaviour)

I am not sure why we have this restriction.

In http://docs.aws.amazon.com/AmazonS3/latest/dev/storage-class-intro.html, I just see s3 define server kinds of storage class to supply service of different level of durability, availability and so on. Why do you conclude such scheme technically? 

Separate meta and data of objects will lead to lower performance for small object access, and will bring 2x rados objects. which will degrade the number of containable rest objects. Containable number, storage capacity and performance are most importance of cloud object storage. We should not break one of them down if not compelled, which we lost more than we gain in.

**Comment by fangyuxiangGL** [comment]
If you deep into objectstore(e.g filestore), you will find that rados cluster have limitation of object number, which is not very good yet.

**Comment by fangyuxiangGL** [comment]
In addition to, I think associate rados pool with s3 storage class strictly is very far-fetched.

e.g how can we express this character of STANDARD_IA,(from s3 doc)
> STANDARD_IA – This storage class (IA, for infrequent access) is optimized for long-lived and less frequently accessed data, for example backups and older data where frequency of access has diminished, but the use case still demands high performance.

and how can we express character of GLACIER?

It seems that we can just express RRS and STANDARD by resorting 2x pool and 3x pool.

**Comment by mikulely** [comment]
>>inline_head = 1 indicates all real data of object would be stored in the tail_data_pool , even if object is smaller than rgw_max_chunk_size (this is the desired storage class behaviour)

> I am not sure why we have this restriction.

Suppose we're not introducing `inline_head`,  then we're using a placement rule with 3replica `data_pool` ,  2replica `tail_data_pool` to present a RRS storage class ,  if we've put a object with size smaller than `rgw_max_chunk_size`, the actual object will be replicated by 3, which is violated the meaning of the RSS storage class(store the object with 2 replica). 

> In http://docs.aws.amazon.com/AmazonS3/latest/dev/storage-class-intro.html, I just see s3 define several kinds of storage class to supply service of different level of durability, availability and so on. Why do you conclude such scheme technically?

The storage pool is the place we can set the storage policy, do you have better option? 

> Separate meta and data of objects will lead to lower performance for small object access, and will bring 2x rados objects.

Yes, here need trade-off. We can make this behaviour optional, or do we have better solution?

> and how can we express character of GLACIER?

We're talking the direct storage class, which means the storage class can be used directly during the  put operation, Glacier can only be used during lifecycle management.

> It seems that we can express RRS and STANDARD by resorting 2x pool and 3x pool.

It depends on how we set the placement rule.

**Comment by fangyuxiangGL** [comment]
> Suppose we're not introducing inline_head, then we're using a placement rule with 3replica data_pool , 2replica tail_data_pool to present a RRS storage class , if we've put a object with size smaller than rgw_max_chunk_size, the actual object will be replicated by 3, which is violated the meaning of the RSS storage class(store the object with 2 replica).

for RRS, we just define 2x replica data_pool and let tail_data_pool empty, all data will be stored in data_pool.

**Comment by mikulely** [comment]
> for RRS, we just define 2x replica data_pool and let tail_data_pool empty, all data will be stored in data_pool.

we're exposing different storage classes with different placement rules, those placement rules should use the same `index_pool` and ` data_pool` .

**Comment by fangyuxiangGL** [comment]
> Why do you conclude such scheme technically?
Just for storing meta and head separately, i thought that you concluded from s3 technology doc. For storage policy, we surely have the only one choice that we are talking about.

> we're exposing different storage classes with different placement rules, those placement rules should use the same index_pool and data_pool .
Is this necessary and why?

**Comment by mikulely** [comment]
>> we're exposing different storage classes with different placement rules, those placement rules should use the same index_pool and data_pool .

> Is this necessary and why?

If I understand correctly , for the using of same `data_pool`, we're assumed that head object is located in the `data_pool` of `bucket_info.placement_rule`  . If we've set the head object to use other placement rule, there's no way that we find the head object later(except searching).

**Comment by fangyuxiangGL** [comment]
<If we've set the head object to use other placement rule, there's no way that we can find the head object later(except searching).

I'm not sure about the circumstance mentioned by you, could you give an example in detail?

**Comment by fangyuxiangGL** [comment]
> It means placement rule per rgw-obj level(s3 storage class is object level placement.not current bucket level placement.)

got you

**Comment by fangyuxiangGL** [comment]
@mikulely 

when considering object-level storage class, it's surely necessary to store meta data in same pool. But there are things we must consider as mentioned previous and most of which is the containable numbers of rgw-obj, which may cause a function to be 'chicken ribs'. When we introduce any feature, we must consider it is applicable in production, isn't it?

**Comment by mikulely** [comment]
> there are things we must consider as mentioned previous and most important of which is the containable numbers of rgw-obj, which may cause a function to be 'chicken ribs'. 

Have you quantified the object number limits issue? I'm interested about the upper bound and the reason. 

> When we introduce any feature, we must consider it is applicable in production, isn't it?

The `inline_head`  should be config as a option of the placement rule, both of us would be happy. ;-)

**Comment by fangyuxiangGL** [comment]
> Have you quantified the object number limits issue? I'm interested about the upper bound and the reason.
Determined by kinds of factors, you can get the result if you use cosbench to do a test

**Comment by mikulely** [comment]
This is not necessary to introduce such concept to implement head/tail into different pools.  closing.

**Pull request closed without merging**
