### PR TITLE
mgr/cephadm: move Grafana's subpath handling logic to grafan config

### PR DESCRIPTION
**Pull request by rkachach**
Error message when Grafana fails to load:

image

Fixes: https://tracker.ceph.com/issues/68315
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2317794

So far, Grafana's subpath handling has been managed on the Nginx server side using a rewrite rule. Let's move this logic to the Grafana side to make it consistent with the rest of the monitoring services.

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [x] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [x] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Comment by rkachach** [comment]
jenkins retest this please

**Review by epuertat — APPROVED** [review]

**Comment by rkachach** [comment]
jenkins test make check

**Comment by rkachach** [comment]
jenkins test dashboard cephadm

**Review by nizamial09 — APPROVED** [review]

**Comment by rkachach** [comment]
jenkins test make check

**Comment by rkachach** [comment]
jenkins test make check

**Comment by adk3798** [comment]
https://pulpito.ceph.com/phlogistonjohn-2024-10-15_13:29:56-orch:cephadm-wip-adk-testing-2024-10-14-1530-distro-default-smithi/

Failures:
- 3x failures in smb ctdb tests due to either stray daemon warnings or selinux denials, known issue
- 3x misc. infra/teuthology failures
- 3x mds_upgrade sequence timeouts or cluster log warnings, known issue
- 2x rgw ingress test timeouts, known issue
- mgr-nfs-upgrade failure, looks like it tried to check all the daemons were upgraded while only the first mgr had been upgraded. It looks like maybe something went wrong with the check to make sure the upgrade had completed.

Would maybe hold off on merging upgrade related PRs, but everything else should be okay.

**Review by adk3798 — APPROVED** [review]

**Pull request merged**
