### PR TITLE
mgr/dashboard: remove transition-through-oci image workaround in grafana  build

### PR DESCRIPTION
**Pull request by aaSharma14**
remove transition-through-oci image workaround in grafana  build

The ceph-grafana-build is failing with this error -
```
+ make push
# this transition-through-oci image is a workaround for
# https://github.com/containers/buildah/issues/3253 and
# can be removed when that is fixed and released.  The
# --format v2s2 on push is to convert oci back to docker format.
sudo podman push ceph-grafana:8.2.6-x86_64 --format=oci dir://tmp/oci-image
Getting image source signatures
Copying blob sha256:bce624159a7606daa904a85f0e600a78bf7d2903de877653defe064f731c2793
Copying config sha256:9756a21e11f8999c31a6e5928d3adcdb9a1b1ed3a28ad638feaacb3a20b8e45d
Writing manifest to image destination
Storing signatures
sudo podman pull dir://tmp/oci-image
Getting image source signatures
Copying blob sha256:bce624159a7606daa904a85f0e600a78bf7d2903de877653defe064f731c2793
Copying config sha256:9756a21e11f8999c31a6e5928d3adcdb9a1b1ed3a28ad638feaacb3a20b8e45d
Writing manifest to image destination
Storing signatures
9756a21e11f8999c31a6e5928d3adcdb9a1b1ed3a28ad638feaacb3a20b8e45d
sudo rm -rf /tmp/oci-image
sudo podman tag localhost/tmp/oci-image docker.io/ceph/ceph-grafana:8.2.6-x86_64
Error: localhost/tmp/oci-image: image not known
make: *** [Makefile:82: push] Error 125
Build step 'Execute shell' marked build as failure
New run name is '#45 master, x86_64'
[Checks API] No suitable checks publisher found.
Finished: FAILURE
```
Removing the above workaround should fix this.

Fixes: https://tracker.ceph.com/issues/54311
Signed-off-by: Aashish Sharma <aasharma@redhat.com>

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [x] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by dmick** [comment]
I don't understand the failure, and don't agree that the workaround should be removed without 1) understanding why the code was failing, and 2) being certain that all versions of podman now in use have the fix for the original issue https://github.com/containers/buildah/issues/3253, purported to be fixed by https://github.com/containers/buildah/pull/3250.

The workaround code may no longer be necessary, but it also should not be failing in this way.

**Comment by epuertat** [comment]
> I don't understand the failure, and don't agree that the workaround should be removed without 1) understanding why the code was failing, and 2) being certain that all versions of podman now in use have the fix for the original issue [containers/buildah#3253](https://github.com/containers/buildah/issues/3253), purported to be fixed by [containers/buildah#3250](https://github.com/containers/buildah/pull/3250).
> 
> The workaround code may no longer be necessary, but it also should not be failing in this way.

@dmick I understand your point, but neither @aaSharma14 nor myself could reproduce that failure right now (and we don't have a CentOS 8 box at hand) and to make things worse this is blocking ongoing Quincy release.

Regarding you 2nd point, I checked that and it was fixed in [buildah v1.22](https://github.com/containers/buildah/releases/tag/v1.22.0#:~:text=containerImageRef()%3A%20squashed%20images%20have%20no%20parent%20images), while CentOS 8 Stream features 1.24.2 (in case we're still using [CentOS 8, the very 1.22.3](https://centos.pkgs.org/8/centos-appstream-x86_64/buildah-1.22.3-2.module_el8.5.0+911+f19012f9.x86_64.rpm.html) is the latest version available):
```sh
# docker run --rm -ti quay.io/centos/centos:stream8 dnf info buildah
CentOS Stream 8 - AppStream                                                                                                                                                            20 MB/s |  21 MB     00:01    
CentOS Stream 8 - BaseOS                                                                                                                                                               13 MB/s |  21 MB     00:01    
CentOS Stream 8 - Extras                                                                                                                                                               38 kB/s |  18 kB     00:00    
Available Packages
Name         : buildah
Epoch        : 1
Version      : 1.24.2
...
```
Since this is an urgent matter, I'll proceed to merge this, trigger the Grafana container image build and see what happens next. We can continue with the debugging after this if you want.

**Review by epuertat — APPROVED** [review]

**Comment by epuertat** [comment]
Ok, the build passed that error but failed [at a later step](https://jenkins.ceph.com/job/ceph-grafana/46/console):
```
sudo podman login --authfile=auth.json -u **** -p **** docker.io
Error: error logging into "docker.io": invalid username/password
```
It seems that we're no longer pushing to ceph/ceph-grafana, so I agreed with @djgalloway to also remove that image so that users don't point their cephadms to that one.

**Comment by dmick** [comment]
> we don't have a CentOS 8 box at hand

We have a lab full.  but okay.  I like root causes.

**Pull request merged**
