### PR TITLE
osd/PeeringState: Avoid past interval start mismatch

### PR DESCRIPTION
**Pull request by Matan-B**
Following b79442efce479fde7f8bda8fdadf86e91003a327. When merging, we solve the similar issue by adjusting the the past interval start (pg_history) backwards to match `last_epoch_started`. 

> In this case, the source will have a past_intervals start that is later than the last_epoch_clean implied in the pg_pool_t.
This situation is harmless because we do not allow the actual mappings of source and target to diverge during the merge window, so if the source's past intervals was adjusted we can still use it.

* The suggested strategy here is added both to `PeeringState::GetInfo::GetInfo()` and `PeeringState::Reset::react()` before `check_past_interval_bounds`.

  Failures from related trackers:
  ```
  1: (ceph::__ceph_abort(...) [0x56463c23fb99]
  2: (PeeringState::check_past_interval_bounds() const+0x6d5) [0x56463c6357c5]
  3: (PeeringState::Reset::react(...) [0x56463c64ecdc]
  ```
  ```
  1: (ceph::__ceph_abort(...) [0x55aed1c5a7e0]
  2: (PeeringState::check_past_interval_bounds() const+0x6ed) [0x55aed1fdc62d]
  3: (PeeringState::GetInfo::GetInfo(...) [0x55aed2009d95]
  ```

* A different approach is preventing this situation beforehand by adjusting (if needed) the start epoch when splitting the pgs. (Therefore, This PR is marked as draft for now)

Tracker: https://tracker.ceph.com/issues/49689

For more details on the tracker see: https://gist.github.com/Matan-B/ca564b6789f6ae6fc2ebc6a5b7e2aa69

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by athanatos** [comment]
@Matan-B First, while it's certainly nice to have an explanation in the PR description, the PR description won't go into the commit history and will be of no use to future readers -- always ensure that all such information is present in commit messages and comments.

Second,  https://github.com/ceph/ceph/commit/b79442efce479fde7f8bda8fdadf86e91003a327 adjusts past_intervals due to a specific condition that arises during pg merge -- we shouldn't need to do this in general.  Unconditionally changing the past_intervals start like this won't fix the bug that is causing the mismatch -- it'll just hide it and cause it to pop back up in other ways.  Have you identified why this is happening?

**Review by athanatos — CHANGES_REQUESTED** [review]
See above.

**Comment by Matan-B** [comment]
> @Matan-B First, while it's certainly nice to have an explanation in the PR description, the PR description won't go into the commit history and will be of no use to future readers -- always ensure that all such information is present in commit messages and comments.
> 
> Second, [b79442e](https://github.com/ceph/ceph/commit/b79442efce479fde7f8bda8fdadf86e91003a327) adjusts past_intervals due to a specific condition that arises during pg merge -- we shouldn't need to do this in general. Unconditionally changing the past_intervals start like this won't fix the bug that is causing the mismatch -- it'll just hide it and cause it to pop back up in other ways. Have you identified why this is happening?

I am still uncertain on why this is happening, trying to reproduce it. (last occurred 6 months ago) 
Most failures consisted `thrashers/mapgap` and `crc-failures/bad_map_crc_failure` on rhel with bluestore.
I have adjusted the suite for better failure probability  https://github.com/ceph/ceph/commit/87d1d40b578cc383732153d25ffa28926f2c716e and still no luck for now.
https://pulpito.ceph.com/matan-2022-09-20_09:50:04-rados:thrash-main-distro-default-smithi/

**Comment by rzarzynski** [comment]
@Matan-B: I'm attaching the gist (https://gist.github.com/Matan-B/ca564b6789f6ae6fc2ebc6a5b7e2aa69#-wip-interval-trimming) to have everything in single place.

**Comment by rzarzynski** [comment]
Looks it superseded by [48706](https://github.com/ceph/ceph/pull/48706).

**Pull request closed without merging**
