### PR TITLE
doc: style fix for doc/cephfs/client-config-ref.rst

### PR DESCRIPTION
**Pull request by drunkard**
Also fixed:
 - Reference symbol, i.e. s/`/``/
 - Hyperlink typo at ``client_trace``

### CODE REVIEW

**Comment by tchaikov** [comment]
@drunkard could you drop the formatting change?

**Comment by drunkard** [comment]
Trying to make it the same style as others, any other reason not doing this?

**Comment by tchaikov** [comment]
@drunkard just wanted to avoid format only changes which obscure the history of changes.

**Comment by drunkard** [comment]
I see. Reworked typo changes.

**Pull request merged**
