### PR TITLE
crimson: pick up a recent seastar version and cleanups

### PR DESCRIPTION
**Pull request by tchaikov**
## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by tchaikov** [comment]
jenkins test crimson perf

**Comment by tchaikov** [comment]
> Maybe we could take `ret` by `auto&&` similarly to other occurrences in the commit? However, `do_pgnls_common()` doesn't seem to be a part of our hot paths, so the extra copy is neglectable while no `&&` improves readability. Hmm, no strong opinion here.

updated and repushed.

**Comment by tchaikov** [comment]
```
16:05:10 - INFO     - cbt      - prefill/incerta03.front.sepia.ceph.com/0: bandwidth: (or (greater) (near 0.05)):: 31.4064/31.9995  => accepted
16:05:10 - INFO     - cbt      - prefill/incerta03.front.sepia.ceph.com/0: iops_avg: (or (greater) (near 0.05)):: 8040.0/8191.0  => accepted
16:05:10 - INFO     - cbt      - prefill/incerta03.front.sepia.ceph.com/0: iops_stddev: (or (less) (near 2.00)):: 32.078/120.666  => accepted
16:05:10 - INFO     - cbt      - prefill/incerta03.front.sepia.ceph.com/0: latency_avg: (or (less) (near 0.05)):: 0.00198358/0.00193848  => accepted
16:05:10 - INFO     - cbt      - prefill/incerta03.front.sepia.ceph.com/1: bandwidth: (or (greater) (near 0.05)):: 30.2227/31.1486  => accepted
16:05:10 - INFO     - cbt      - prefill/incerta03.front.sepia.ceph.com/1: iops_avg: (or (greater) (near 0.05)):: 7737.0/7974.0  => accepted
16:05:10 - WARNING  - cbt      - prefill/incerta03.front.sepia.ceph.com/1: iops_stddev: (or (less) (near 2.00)):: 121.706/33.0606  => rejected
16:05:10 - INFO     - cbt      - prefill/incerta03.front.sepia.ceph.com/1: latency_avg: (or (less) (near 0.05)):: 0.00205022/0.00199319  => accepted
16:05:10 - INFO     - cbt      - rand/incerta03.front.sepia.ceph.com/0: bandwidth: (or (greater) (near 0.05)):: 254.265/250.028  => accepted
16:05:10 - INFO     - cbt      - rand/incerta03.front.sepia.ceph.com/0: iops_avg: (or (greater) (near 0.05)):: 65091.0/64007.0  => accepted
16:05:10 - INFO     - cbt      - rand/incerta03.front.sepia.ceph.com/0: iops_stddev: (or (less) (near 2.00)):: 454.962/1470.95  => accepted
16:05:10 - INFO     - cbt      - rand/incerta03.front.sepia.ceph.com/0: latency_avg: (or (less) (near 0.05)):: 0.000242924/0.000246892  => accepted
16:05:10 - INFO     - cbt      - rand/incerta03.front.sepia.ceph.com/1: bandwidth: (or (greater) (near 0.05)):: 251.112/254.977  => accepted
16:05:10 - INFO     - cbt      - rand/incerta03.front.sepia.ceph.com/1: iops_avg: (or (greater) (near 0.05)):: 64284.0/65274.0  => accepted
16:05:10 - WARNING  - cbt      - rand/incerta03.front.sepia.ceph.com/1: iops_stddev: (or (less) (near 2.00)):: 1131.73/327.322  => rejected
16:05:10 - INFO     - cbt      - rand/incerta03.front.sepia.ceph.com/1: latency_avg: (or (less) (near 0.05)):: 0.000245863/0.000242302  => accepted
16:05:10 - WARNING  - cbt      - 2 tests failed out of 16
```

**Comment by rzarzynski** [comment]
```
16:50:30 - DEBUG    - cbt      - Nodes : incerta04.front.sepia.ceph.com
16:50:30 - DEBUG    - cbt      - Nodes : incerta04.front.sepia.ceph.com
16:50:30 - DEBUG    - cbt      - Nodes : incerta04.front.sepia.ceph.com
16:50:30 - INFO     - cbt      - prefill/incerta04.front.sepia.ceph.com/0: bandwidth: (or (greater) (near 0.05)):: 62.2395/60.5769  => accepted
16:50:30 - INFO     - cbt      - prefill/incerta04.front.sepia.ceph.com/0: iops_avg: (or (greater) (near 0.05)):: 15933.0/15507.0  => accepted
16:50:30 - INFO     - cbt      - prefill/incerta04.front.sepia.ceph.com/0: iops_stddev: (or (less) (near 2.00)):: 241.194/257.948  => accepted
16:50:30 - INFO     - cbt      - prefill/incerta04.front.sepia.ceph.com/0: latency_avg: (or (less) (near 0.05)):: 0.00100221/0.00102928  => accepted
16:50:30 - WARNING  - cbt      - prefill/incerta04.front.sepia.ceph.com/1: bandwidth: (or (greater) (near 0.05)):: 55.4346/65.0883  => rejected
16:50:30 - WARNING  - cbt      - prefill/incerta04.front.sepia.ceph.com/1: iops_avg: (or (greater) (near 0.05)):: 14191.0/16662.0  => rejected
16:50:30 - INFO     - cbt      - prefill/incerta04.front.sepia.ceph.com/1: iops_stddev: (or (less) (near 2.00)):: 153.871/96.9072  => accepted
16:50:30 - WARNING  - cbt      - prefill/incerta04.front.sepia.ceph.com/1: latency_avg: (or (less) (near 0.05)):: 0.00112542/0.000957964  => rejected
16:50:30 - INFO     - cbt      - rand/incerta04.front.sepia.ceph.com/0: bandwidth: (or (greater) (near 0.05)):: 232.602/239.048  => accepted
16:50:30 - INFO     - cbt      - rand/incerta04.front.sepia.ceph.com/0: iops_avg: (or (greater) (near 0.05)):: 59546.0/61196.0  => accepted
16:50:30 - INFO     - cbt      - rand/incerta04.front.sepia.ceph.com/0: iops_stddev: (or (less) (near 2.00)):: 4140.09/3605.48  => accepted
16:50:30 - INFO     - cbt      - rand/incerta04.front.sepia.ceph.com/0: latency_avg: (or (less) (near 0.05)):: 0.000265291/0.000258115  => accepted
16:50:30 - INFO     - cbt      - rand/incerta04.front.sepia.ceph.com/1: bandwidth: (or (greater) (near 0.05)):: 254.353/242.465  => accepted
16:50:30 - INFO     - cbt      - rand/incerta04.front.sepia.ceph.com/1: iops_avg: (or (greater) (near 0.05)):: 65114.0/62071.0  => accepted
16:50:30 - INFO     - cbt      - rand/incerta04.front.sepia.ceph.com/1: iops_stddev: (or (less) (near 2.00)):: 3510.1/3205.09  => accepted
16:50:30 - INFO     - cbt      - rand/incerta04.front.sepia.ceph.com/1: latency_avg: (or (less) (near 0.05)):: 0.000242789/0.000254828  => accepted
16:50:30 - WARNING  - cbt      - 3 tests failed out of 16
```

**Comment by rzarzynski** [comment]
jenkins test crimson perf

**Pull request merged**
