### PR TITLE
test/store_test: fix FTBFS as Sequencer is removed

### PR DESCRIPTION
**Pull request by tchaikov**
Signed-off-by: Kefu Chai <kchai@redhat.com>

### CODE REVIEW

**Comment by tchaikov** [comment]
as #18494 got merged after #20173...

**Comment by tchaikov** [comment]
as test_objectstore_memstore.sh is exercised by "make check", probably it would suffice. i will also schedule a rados qa run involving qa/suites/rados/objectstore/objectstore.yaml ASAP.

**Comment by badone** [comment]
:thumbsup:

**Comment by tchaikov** [comment]
http://pulpito.ceph.com/kchai-2018-02-09_08:09:49-rados-wip-kefu-testing-2018-02-09-1438-distro-basic-smithi/

**Comment by liewegas** [comment]
Thanks!

**Pull request merged**
