### PR TITLE
quincy: librbd/crypto: fix issue when live-migrating from encrypted export

### PR DESCRIPTION
**Pull request by idryomov**
backport tracker: https://tracker.ceph.com/issues/67442

---

backport of https://github.com/ceph/ceph/pull/58882 and https://github.com/ceph/ceph/pull/44366
parent tracker: https://tracker.ceph.com/issues/53674

### CODE REVIEW

**Comment by idryomov** [comment]
jenkins test api

**Review by ajarr — COMMENTED** [review]
I wasn't able to figure out the conflict for this commit,
https://github.com/ceph/ceph/pull/59144/commits/705a6570627b4a4e560dfea7c96dbf0e1f5c976c
I went through NativeFormat.cc mentioned in the Conflicts section of the commit message
```
Conflicts:
	src/librbd/migration/NativeFormat.cc [ ImageArea support not in
	  quincy ]
```
Would you mind pointing out where the above conflict was resolved in the file?

**Comment by idryomov** [comment]
> Would you mind pointing out where the above conflict was resolved in the file?

In `ImageDispatch::read()` and `ImageDispatch::list_snaps()`/`C_MapSnapshotDelta` where they check for `IMAGE_DISPATCH_FLAG_CRYPTO_HEADER` and use `area_to_raw_offset()` and `raw_to_area_offset()` in main.

**Comment by ajarr** [comment]
Did you mean this line,
https://github.com/ceph/ceph/pull/59144/commits/705a6570627b4a4e560dfea7c96dbf0e1f5c976c#diff-05bd677a4428de2af754925b249fc5de5ffba75c82a8f98e8ac86069f9464077L327 ?

I don't see ImageDispatch::read() or ImageDispatch::list_snaps() being called in NativeFormat.cc before and after the change?

**Comment by idryomov** [comment]
> Did you mean this line, [705a657#diff-05bd677a4428de2af754925b249fc5de5ffba75c82a8f98e8ac86069f9464077L327](https://github.com/ceph/ceph/commit/705a6570627b4a4e560dfea7c96dbf0e1f5c976c#diff-05bd677a4428de2af754925b249fc5de5ffba75c82a8f98e8ac86069f9464077L327) ?

Yes -- there is an additional `io::ImageArea::DATA` argument passed there in main.

> 
> I don't see ImageDispatch::read() or ImageDispatch::list_snaps() being called in NativeFormat.cc before and after the change?

Sorry, I missed that the question was specifically about commit https://github.com/ceph/ceph/commit/705a6570627b4a4e560dfea7c96dbf0e1f5c976c.

**Review by ajarr — APPROVED** [review]
Not a trivial backport. Code changes makes sense. Need to check teuthology runs before merge.

**Pull request merged**
