### PR TITLE
install-deps.sh: install libpmem libraries if WITH_PMEM is set

### PR DESCRIPTION
**Pull request by tchaikov**
Signed-off-by: Kefu Chai <kchai@redhat.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Review by batrick — APPROVED** [review]

**Comment by tchaikov** [comment]
tested using
```sh
WITH_PMEM=true ./run-make-check.sh
```

on a focal machine.

@batrick thanks for your review. i just realized that i forgot to update `run-make-check.sh`. could you please take another look?

@trociny @CongMinYin @cyx1231st hi folks, as Jason pointed out we need to have the pmem cache support by default. but pmem v1.10 is not packaged by ubuntu focal. so i compiled and uploaded the latest libpmem packages and its dependencies to chacra, so we can at least build-test it in "make check".

**Review by trociny — COMMENTED** [review]
:+1:  Thanks!

**Review by batrick — APPROVED** [review]

**Comment by djgalloway** [comment]
This is still somehow creating mangled `pmem.list` files on our Jenkins builders.

Do we need to install a special version built and hosted by us in shaman or is the distro-provided version okay?

**Comment by tchaikov** [comment]
#46773

**Pull request merged**
