### PR TITLE
octopus: mgr/dashboard: CLI commands: read passwords from file

### PR DESCRIPTION
**Pull request by alfonsomthd**
backport tracker: https://tracker.ceph.com/issues/48654

---

backport of https://github.com/ceph/ceph/pull/38284
parent tracker: https://tracker.ceph.com/issues/48355

this backport was staged using ceph-backport.sh version 16.0.0.6848
find the latest version at https://github.com/ceph/ceph/blob/master/src/script/ceph-backport.sh

### CODE REVIEW

**Comment by callithea** [comment]
I removed the octopus batch label for now because not all of the checks passed.

**Comment by callithea** [comment]
jenkins test api

**Comment by callithea** [comment]
jenkins test dashboard

**Comment by callithea** [comment]
Is the commit "_mgr/dashboard: fix conflict resolution_" supposed to be a separate commit or should it be a fixup?
Just wondering because I compared the original PR targeting master (two commits) vs the backport (three commits).

**Comment by alfonsomthd** [comment]
> Is the commit "_mgr/dashboard: fix conflict resolution_" supposed to be a separate commit or should it be a fixup?
> Just wondering because I compared the original PR targeting master (two commits) vs the backport (three commits).

@callithea I backported the 2 original commits and then realized that a conflict was resolved in a wrong way, so I added the proper fix.

**Comment by callithea** [comment]
> > Is the commit "_mgr/dashboard: fix conflict resolution_" supposed to be a separate commit or should it be a fixup?
> > Just wondering because I compared the original PR targeting master (two commits) vs the backport (three commits).
> 
> @callithea I backported the 2 original commits and then realized that a conflict was resolved in a wrong way, so I added the proper fix.

I think this commit could be squashed then and a note should be added to the conflicts section.
Otherwise it would be confusing to have three commits in the backport while there are two commits in the original backport IMHO.
If you think it makes sense to have a third commit for the conflict resolution I'd suggest to explain in the commit message, why there's an additional commit and what the purpose of the commit is.

**Comment by alfonsomthd** [comment]
> I'd suggest to explain in the commit message, why there's an additional commit and what the purpose of the commit is.
It seemed to me that the commit message was self-explanatory:
``` 
mgr/dashboard: fix conflict resolution …

in file: qa/tasks/mgr/dashboard/test_auth.py
from commit: f0e2b08
``` 
Nevertheless, I'll squash the 3rd commit with the 1st one.

**Review by callithea — APPROVED** [review]
Lgtm, thank you!

**Review by avanthakkar — APPROVED** [review]

**Pull request merged**
