### PR TITLE
mgr/dashboard: download setuptools_scm explicitly

### PR DESCRIPTION
**Pull request by tchaikov**
otherwise we will fail to install the build dependencies of
`lazy-object-proxy` from the wheelhouse. as `lazy-object-proxy` does not
add `setuptools_scm` in its `setup.py`, instead it lists
`setuptools_scm` in `setup.cfg` and `pyproject.toml` as a `build-system`
requires. but unfortunately, `pip download` only downloads the
install/run-time dependencies at this moment. and `lazy-object-proxy`
does not offer binary package for at least python2.7.

ideally, `pip` should collects its dependencies like

Collecting setuptools_scm>=3.3.1 (from lazy-object-proxy->astroid<3,>=2.2.0->pylint->-r requirements-lint.txt (line 1))

so we have to list its build-time dependencies explicitly.

see also https://github.com/pypa/pip/issues/6222

Signed-off-by: Kefu Chai <kchai@redhat.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`

</details>

### CODE REVIEW

**Comment by tchaikov** [comment]
this should address the build failures like

```
Collecting lazy-object-proxy (from astroid<2.0,>=1.6->pylint->-r requirements-lint.txt (line 1))
  Installing build dependencies: started
  Installing build dependencies: finished with status 'error'
ERROR: Command errored out with exit status 1: /home/jenkins-build/build/workspace/ceph-pull-requests-arm64/build/mgr-dashboard-virtualenv/bin/python2.7 /home/jenkins-build/build/workspace/ceph-pull-requests-arm64/build/mgr-dashboard-virtualenv/lib/python2.7/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-N2KIOY/overlay --no-warn-script-location -v --no-binary :none: --only-binary :none: --no-index --find-links file:///home/jenkins-build/build/workspace/ceph-pull-requests-arm64/src/pybind/mgr/dashboard/wheelhouse -- 'setuptools>=30.3.0' wheel 'setuptools_scm>=3.3.1' Check the logs for full command output.
```

**Comment by epuertat** [comment]
>  but unfortunately, pip download only downloads the install/run-time dependencies at this moment. and lazy-object-proxy

Would it make sense to go back to `pip wheel`, instead of `pip download`. I changed that in #28696, but if it fixes this issue, I'd rather prefer that, instead of pinning dependencies in + requirements-*.txt`?

BTW, it sounds a bit intriguing that Pypa folks seem not to have a clear understanding/agreement on what flags like `--no-binary` were initially meant for :worried:

**Comment by epuertat** [comment]
jenkins retest this please

**Comment by tchaikov** [comment]
@epuertat why did you change `pip wheel` to `pip download`?

**Comment by epuertat** [comment]
BTW, I already have a PR for locking pytlint version (https://github.com/ceph/ceph/pull/29802/files#diff-bc000fea578b43e7898821c4833c29eaR1). Cannot say if that fixes the issue, because there's this`make`/`sphinx` issue happening before.

**Comment by tchaikov** [comment]
@epuertat i am testing `pip wheel` at https://github.com/ceph/ceph/pull/29903. i don't have enough bandwidth or savvy to investigate this issue further. so please feel free to close / merge them if you see appropriate.

**Comment by epuertat** [comment]
> @epuertat why did you change `pip wheel` to `pip download`?

I checked a couple of recipes for caching and they all used `pip download` and the `pip install --no-index --find-links=...`, and that worked in the PR. No other reason, so if that's causing the issue with `pylint`, let's put wheel back there.

**Pull request closed without merging**
