### PR TITLE
osd: list_missing should query missing_loc.needs_recovery_map

### PR DESCRIPTION
**Pull request by guangyy**
Fixes: 13441
Signed-off-by: Guang Yang <yguang@yahoo-inc.com>

### CODE REVIEW

**Comment by guangyy** [comment]
Manual testings looks good, working on automation.

**Comment by guangyy** [comment]
Hi @athanatos , this is ready for review.

One thing that is missing is a test case for unfound objects in *replicated* pool, I didn't figure out a way to do it easily. (I tried to remove all three copies from file system and then did a repair of the PG, it did not show unfound object, I guess that is another bug).

**Comment by guangyy** [comment]
@dachary , the bot failure seems unrelated to the changes in this PR, is it a known pattern?

**Comment by dachary** [comment]
@guangyy I saw this false negative once yesterday but could not figure it out. Could you please rebase and repush to verify it goes away ? Thanks for letting me know :-)

**Comment by guangyy** [comment]
Thanks @dachary , rebased and repushed, let us see the check this time :)

**Comment by guangyy** [comment]
Ping @athanatos  :)

**Comment by guangyy** [comment]
As discussed with @athanatos , we will add a test case into ceph-qa-suite for this.

**Comment by guangyy** [comment]
Hi @athanatos ,
If the code looks good, could you help to push it to ceph's repository, so that I can run some teuthology test? Thanks!

**Comment by liewegas** [comment]
@guangyy I've added you to the ceph project, so you can push wip- branches.  Be careful not to touch the main ones!

Alternatively, you can use teuthology-openstack, which does its own local builds and doesn't rely on any upstream access.

**Comment by dachary** [comment]
@guangyy for your convenience, here is the command line you need to run the test:

<pre>
teuthology-openstack --verbose --key-name myself --key-filename ~/Downloads/myself --suite rados/thrash --ceph-qa-suite-git-url https://github.com/ceph/ceph-qa-suite.git --suite-branch ceph --ceph-git-url https://github.com/guangyy/ceph.git --ceph wip-13441 --subset 2/3
</pre>

to verify that teuthology-openstack works for you, please follow the instructions at https://github.com/dachary/teuthology/tree/openstack#openstack-backend

Let me know if you need help.

**Comment by guangyy** [comment]
Thanks @liewegas @dachary , I will give it a try.

**Comment by guangyy** [comment]
Newly added ceph-qa-suite passed, ready for review and merge.

Test case: https://github.com/ceph/ceph-qa-suite/pull/755
Job: 
http://qa-proxy.ceph.com/teuthology/yguang-2015-12-04_17:18:17-rados-wip-13441---basic-multi/1167683/teuthology.log

**Comment by guangyy** [comment]
@athanatos .

**Comment by athanatos** [comment]
lgtm, does it still need a full suite run?

**Comment by guangyy** [comment]
Thanks @athanatos , yeah I think it would be helpful to run along with a full suite.

**Pull request merged**
