### PR TITLE
mimic: mgr/dashboard: Remove fieldsets when using CdTable

### PR DESCRIPTION
**Pull request by tspmelo**
Fixes: http://tracker.ceph.com/issues/27851

### CODE REVIEW

**Comment by smithfarm** [comment]
Reason for DNM: @smithfarm I was told that https://github.com/ceph/ceph/pull/24183 might be backported to mimic.
If that is the case, this PR would already be included and merging it would created conflicts.

The same applies to https://github.com/ceph/ceph/pull/24478.

**Comment by epuertat** [comment]
@smithfarm #24183 would be hard to backport to Mimic as it currently is: it includes changes to work around Mimic-master features missing in Luminous (centralized config, new RBD feature flags, CephMgr refactor, etc).

As that 4th backporting chunk exceeded the features present in Mimic, the agreement with @LenzGr , @jcsp, @liewegas, etc.,  was no to backport it to Luminous, and just leave it open for the case some 'luminous-dashboard' branch was ever created (or someone else wants to patch their sources to bring dashboard_v2 to Luminous).

However, this other PR #24026 is fully suitable for being merged to Luminous (encompasses commits from #23271 and #23804 as well), as it respects 'feature' parity with Mimic (13.2.0 release, all later bugfixes are missing there though).

**Comment by smithfarm** [comment]
@epuertat I was just noting @tspmelo 's comment explaining why DNM was added. As far as I'm concerned, any backport PR is fine to go in once the relevant dev lead ( @LenzGr in this case ) approves and it passes integration testing.

**Comment by yuriw** [comment]
@tspmelo pls add `needs-qa` when `DNM` removed

**Pull request merged**
