### PR TITLE
qa/tasks/cephadm: fix ceph.conf so it includes *all* mons

### PR DESCRIPTION
**Pull request by liewegas**
Needs backport to octopus

### CODE REVIEW

**Comment by sebastian-philipp** [comment]
Hm, to me this looks more like a bug in cephadm itself. if cephadm cannot properly refresh the ceph.conf, something is broken?

**Comment by liewegas** [comment]
> Hm, to me this looks more like a bug in cephadm itself. if cephadm cannot properly refresh the ceph.conf, something is broken?

This is is the ceph.conf outside of the container, on the host. We haven't designed/implemented anything to manage that (or, say, installed packages) on the host yet.

**Comment by liewegas** [comment]
(I agree that cephadm should have a way to manage ceph.conf files outside of the containers themselves, though... just not sure how to approach that problem.)

**Comment by sebastian-philipp** [comment]
https://tracker.ceph.com/issues/44792

**Comment by liewegas** [comment]
exposes bug fixed by #34266

**Pull request merged**
