### PR TITLE
Possible crash while concurrently writing and shrinking an image

### PR DESCRIPTION
**Pull request by dillaman**
http://tracker.ceph.com/issues/12236

**Note:** contains commits included in PR #5296 that can be rebased away once they merge.

### CODE REVIEW

**Comment by dachary** [comment]
Marked DNM to ack that it is on top of PR #5280 and PR #5296

**Comment by dachary** [comment]
@dillaman could you please rebase now that #5280 is merged ?

**Comment by dillaman** [comment]
@dachary should I just wait until #5296 merges as well?

**Comment by dachary** [comment]
Passes the rbd suite http://tracker.ceph.com/issues/12701#rbd

**Pull request merged**
