### PR TITLE
[DNM] rgwlib:  implement usage accounting

### PR DESCRIPTION
**Pull request by mattbenjamin**
Signed-off-by: Matt Benjamin <mbenjamin@redhat.com>

### CODE REVIEW

**Comment by mattbenjamin** [comment]
@theanalyst here's a first pass at the RGWLib implementation of byte accounting
@rzarzynski does this look complete?

**Comment by mattbenjamin** [comment]
Looks like this vaguely works :)
Breakpoint 2, rgw::RGWLibIO::get_bytes_received (this=0x7fffa67f62f0) at /home/mbenjamin/ceph-noob/src/rgw/rgw_lib.h:102
102	      return rx_bytes;
(gdb) display rx_bytes 
2: rx_bytes = 5904

**Comment by theanalyst** [comment]
I tried to set the env. to enable usage logging via
```diff
@@ -67,7 +67,9 @@ namespace rgw {
       : user_info(_user_info), rx_bytes(0), tx_bytes(0)
       {}

-    void init_env(CephContext *cct) override {}
+    void init_env(CephContext *cct) override {
+      env.init(cct);
+    }

```

However this lead to hitting the assert, without that usage stats still seemed to be logging 0 values, not sure whether this is necessary

**Comment by theanalyst** [comment]
this is the assert I'm hitting, seems to be hitting even without the env. changes

```-1 /ssd/builds/cpp/ceph_cmake_new/src/rgw/rgw_lib.h: In function 'rgw::
RGWLibIO* rgw::RGWLIB_IO(req_state*)' thread 7f7455fe3700 time 2017-10-10 17:45:09.081565
/ssd/builds/cpp/ceph_cmake_new/src/rgw/rgw_lib.h: 113: FAILED assert(ptr != nullptr)

 ceph version 13.0.0-1658-g2cc7a4f0e7 (2cc7a4f0e7890e92b97f5d6d2eb9348777668085) mimic (dev)
 1: (ceph::__ceph_assert_fail(char const*, char const*, int, char const*)+0x136) [0x7f7591db90b6]
 2: (()+0x741aab) [0x7f759de36aab]
 3: (rgw::RGWWriteRequest::exec_continue()+0x78a) [0x7f759de3ec48]
 4: (rgw::RGWFileHandle::write(unsigned long, unsigned long, unsigned long*, void*)+0x792) [0x7f759de3d6b4]
 5: (rgw_write()+0x8e) [0x7f759de40bd4]
 6: (rgw_fsal_write2()+0x111) [0x7f758ab9a4c4]
 7: (mdcache_write2()+0xa8) [0x54299c]
 8: (fsal_write2()+0x94) [0x43549b]
 9: /usr/bin/ganesha.nfsd() [0x4885c4]
 10: (nfs4_op_write()+0x33) [0x4887f1]
 11: (nfs4_Compound()+0xa1e) [0x462850]
 12: (nfs_rpc_execute()+0x1d6c) [0x44f329]
 13: /usr/bin/ganesha.nfsd() [0x44fb33]
 14: /usr/bin/ganesha.nfsd() [0x50bd9a]
 15: (()+0x8744) [0x7f759c120744]
 16: (clone()+0x6d) [0x7f759ba09aad]
 ```

**Comment by theanalyst** [comment]
How is the cio initialized in case of a RGWWriteRequest (I could be missing something )

**Comment by theanalyst** [comment]
@mattbenjamin are you able to see the assert?

**Comment by theanalyst** [comment]
needs rebase

**Comment by mattbenjamin** [comment]
@theanalyst I'll recheck this

**Comment by theanalyst** [comment]
needs rebase

**Comment by LenzGr** [comment]
I think this would be useful for consumption by the dashboard. Any chances that this can be resurrected and merged?

**Comment by cbodley** [comment]
hi @LenzGr, the [rgw usage log](http://docs.ceph.com/docs/master/radosgw/admin/#usage) is an existing feature (though it's expensive, and off by default), with [admin apis](http://docs.ceph.com/docs/master/radosgw/adminops/#get-usage) that the dashboard could make use of. this pr just fixes some of the accounting when accessed through the nfs view

**Comment by mattbenjamin** [comment]
unstale -- working on update

**Comment by theanalyst** [comment]
can we resurrect this again :)

**Comment by cbodley** [comment]
@mattbenjamin can you please rebase?

**Comment by mattbenjamin** [comment]
@cbodley will do

**Comment by cbodley** [comment]
ping @mattbenjamin

**Comment by mattbenjamin** [comment]
unstale

**Pull request closed without merging**
