### PR TITLE
jewel: mon/osdmonitor: decouple adjust_heartbeat_grace and min_down_reporters

### PR DESCRIPTION
**Pull request by dachary**
http://tracker.ceph.com/issues/17056

### CODE REVIEW

**Comment by dachary** [comment]
@tchaikov does this backport look good to merge ? It passed the rados suite http://tracker.ceph.com/issues/17487#note-4 (except for one known bug that is, I believe, unrelated and one environmental failure on an erasure code job).

**Comment by dachary** [comment]
It passed the rados, upgrade/jewel-x and upgrade/hammer-x suites (except for two bugs that are, I believe, unrelated)

**Comment by dachary** [comment]
It passed the rados (http://tracker.ceph.com/issues/17487#note-19) suite except for two jobs that are, I believe unrelated. It also passed the upgrade/jewel-x and upgrade/hammer-x (http://tracker.ceph.com/issues/17487#note-22) suites.

**Comment by tchaikov** [comment]
lgtm.

**Pull request merged**
