### PR TITLE
osd/PrimaryLogPG: Avoid accessing destroyed references in finish_degr…

### PR DESCRIPTION
**Pull request by cxytt**
…aded_object

As follows:
```c++
for (auto i = callbacks_for_degraded_object.begin(); i != callbacks_for_degraded_object.end();) {
    finish_degraded_object((i++)->first);
}

void PrimaryLogPG::finish_degraded_object(const hobject_t oid)
{
  if (callbacks_for_degraded_object.count(oid)) {
    contexts.swap(callbacks_for_degraded_object[oid]);
    callbacks_for_degraded_object.erase(oid);   // Release
  }

  map<hobject_t, snapid_t>::iterator i = objects_blocked_on_degraded_snap.find(
    oid.get_head());  // Access
  ...
}
```
Signed-off-by: Tao Ning <ningtao@sangfor.com.cn>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test docs`
- `jenkins render docs`

</details>

### CODE REVIEW

**Comment by tchaikov** [comment]
@cxytt could you please file a tracker ticket against this issue? so we can backport your fix to our LTS branches?

**Comment by cxytt** [comment]
@tchaikov 
Has been created, see https://tracker.ceph.com/issues/41250

**Comment by tchaikov** [comment]
@cxytt i revised your commit message to add 
```
Fixes: https://tracker.ceph.com/issues/41250
```

**Comment by tchaikov** [comment]
- http://pulpito.ceph.com/kchai-2019-08-15_06:56:12-rados-wip-kefu-testing-2019-08-15-1125-distro-basic-mira/
- http://pulpito.ceph.com/kchai-2019-08-16_05:52:53-rados-wip-kefu-testing-2019-08-16-0928-distro-basic-smithi/
- http://pulpito.ceph.com/kchai-2019-08-16_11:16:42-rados-wip-kefu-testing-2019-08-16-1501-distro-basic-smithi/

**Pull request merged**
