### PR TITLE
osd: do not promote evicted data when reading a manifest chunked object

### PR DESCRIPTION
**Pull request by myoungwon**
The existing ceph-dedup-tool scans target objects in the base pool, then performs deduplication.
This process is repeated until the daemon is terminated. If the target objects are deduplicated successfully,
it has chunks, each of which is a missing state (evicted).

However, if the ceph-dedup-tool reads a partial deduped object---the object has 
a few deduped chunks that are marked as missing state, 
the current implementation promotes all missing chunks from the lower pool, 
resulting in unnecessary writing. Note that the current implementation
issues a proxy-read only if the requested range is within a chunk range, otherwise
it promotes all missing chunks---we don't need to promote the missing chunks unless
`tier_promote `is called explicitly.

To avoid this, this PR modifies the current approach not to promote chunk data by issuing
proxy operations to the lower pool without promotion.

As is: call a proxy-read only if the requested range is within the chunk range, otherwise call promote
To be: call proxy-reads to get all missing chunks without promotion when handling a read op
 

Signed-off-by: Myoungwon Oh <myoungwon.oh@samsung.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Comment by myoungwon** [comment]
jenkins test make check

**Comment by myoungwon** [comment]
https://pulpito.ceph.com/myoungwon-2024-01-04_15:38:09-rados:thrash-wip-remove-promote-when-read-missing-chunks-distro-default-smithi/

**Comment by rzarzynski** [comment]
The cache tiering has been deprecated in reef.

**Comment by rzarzynski** [comment]
Letting @neha-ojha know in case we want to reopen.

**Comment by myoungwon** [comment]
@neha-ojha @rzarzynski This isn't related to cache tiering. Deduplication work (manifest objects) has a separate path, like maybe_handle_manifest_detail().

**Pull request closed without merging**
