### PR TITLE
mimic: qa/rgw: don't use ceph-ansible in s3a-hadoop suite

### PR DESCRIPTION
**Pull request by smithfarm**
backport tracker: https://tracker.ceph.com/issues/40124

---

backport of https://github.com/ceph/ceph/pull/28068
parent tracker: https://tracker.ceph.com/issues/39706

this backport was staged using https://github.com/ceph/ceph/blob/master/src/script/ceph-backport.sh

### CODE REVIEW

**Comment by yuriw** [comment]
[wip-yuri2-testing-2019-10-04-0015-mimic](https://trello.com/c/xfBj13mW/707-wip-yuri2-testing-2019-10-04-0015-mimic)

**Comment by cbodley** [comment]
this caused a number of test failures in http://pulpito.ceph.com/yuriw-2019-10-04_19:42:08-rgw-wip-yuri2-testing-2019-10-04-0015-mimic-distro-basic-smithi/

can we please pull in the additional fixes from https://github.com/ceph/ceph/pull/28631?

**Comment by smithfarm** [comment]
@cbodley Yup, done.

**Comment by smithfarm** [comment]
Rebased following the recent wave of merges - now, of the 7 commits, only one has a cherry-pick conflict, and it's trivial.

**Comment by yuriw** [comment]
[wip-yuri6-testing-2019-10-10-2057-mimic](https://trello.com/c/kE9yOfx3/714-wip-yuri6-testing-2019-10-10-2057-mimic)

**Pull request merged**
