### PR TITLE
luminous: client: increase verbosity level for log messages in helper methods

### PR DESCRIPTION
**Pull request by batrick**
https://tracker.ceph.com/issues/24190#change-116816

### CODE REVIEW

**Comment by batrick** [comment]
@smithfarm fixed

**Comment by yuriw** [comment]
@batrick need rebase

--- pr 23014 --- pulling https://github.com/batrick/ceph.git branch i24190
remote: Counting objects: 5, done.
remote: Total 5 (delta 4), reused 4 (delta 4), pack-reused 1
Unpacking objects: 100% (5/5), done.
From https://github.com/batrick/ceph
 * branch            i24190     -> FETCH_HEAD
Auto-merging src/client/Client.cc
CONFLICT (content): Merge conflict in src/client/Client.cc
Automatic merge failed; fix conflicts and then commit the result.
Traceback (most recent call last):
  File "/home/yuriw/wip_master/src/script/build-integration-branch", line 62, in <module>
    assert not r
AssertionError

**Comment by batrick** [comment]
Fixed

**Comment by yuriw** [comment]
[wip-yuri5-testing-2018-08-03-2114-luminous](https://trello.com/c/O6q0j5Gf/366-wip-yuri5-testing-2018-08-03-2114-luminous)

**Comment by batrick** [comment]
`Reviewed-by: Patrick Donnelly <pdonnell@redhat.com>`

**Pull request merged**
