### PR TITLE
librbd: namespace create/remove/list support

### PR DESCRIPTION
**Pull request by dillaman**

### CODE REVIEW

**Comment by trociny** [comment]
@dillaman you might want to update doc/man/8/rbd.rst

**Comment by dillaman** [comment]
@trociny done

**Comment by trociny** [comment]
@dillaman Not related to this PR, but could you please look at the jenkins build failure (before I rerun it)? Does it look like a real problem in the rbd mirror test?

**Comment by dillaman** [comment]
@trociny have to see if it crops up again -- the non-arm64 builder seems to always cut off the latest log lines when it fails.

**Comment by trociny** [comment]
@ceph-jenkins retest this please

**Pull request merged**
