### PR TITLE
pacific: librados: aio operate functions can set mtimes

### PR DESCRIPTION
**Pull request by cbodley**
backport tracker: https://tracker.ceph.com/issues/61730

---

backport of https://github.com/ceph/ceph/pull/51681
parent tracker: https://tracker.ceph.com/issues/61349

this backport was staged using ceph-backport.sh version 16.0.0.6848
find the latest version at https://github.com/ceph/ceph/blob/main/src/script/ceph-backport.sh

### CODE REVIEW

**Review by ljflores — APPROVED** [review]

**Comment by cbodley** [comment]
updated according to https://github.com/ceph/ceph/pull/52118#issuecomment-1603007363. conflicts are documented in the final commit

**Comment by cbodley** [comment]
build failure from https://jenkins.ceph.com/job/ceph-dev-new-build/ARCH=x86_64,AVAILABLE_ARCH=x86_64,AVAILABLE_DIST=centos8,DIST=centos8,MACHINE_SIZE=gigantic/70766//consoleFull
> error: ‘class AioTestDataPP’ has no member named ‘m_oid’; did you mean ‘m_init’?
>     ASSERT_EQ(0, test_data.m_ioctx.aio_operate(test_data.m_oid, c.get(), &op));

**Comment by cbodley** [comment]
> error: ‘class AioTestDataPP’ has no member named ‘m_oid’; did you mean ‘m_init’?
> ASSERT_EQ(0, test_data.m_ioctx.aio_operate(test_data.m_oid, c.get(), &op));

resolved and documented the conflict from https://github.com/ceph/ceph/pull/49109

**Review by idryomov — APPROVED** [review]
Nit: conflict note should say "on pacific"

> test case for rados_aio_write_op_operate() uses rados_stat() instead of rados_stat2() which doesn't exist on quincy

**Comment by ljflores** [comment]
Rados suite review: https://tracker.ceph.com/projects/rados/wiki/PACIFIC#httpstrellocomcqQnRTrLO1792-wip-yuri8-testing-2023-06-22-1309-pacific-old-wip-yuri8-testing-2023-06-22-1004-pacific-old-wip-yuri8-testing-2023-06-22-0834-pa

**Pull request merged**
