### PR TITLE
luminous: mds: fix occasional dir rstat inconsistency between multi-MDSes

### PR DESCRIPTION
**Pull request by pdvian**
http://tracker.ceph.com/issues/23835

### CODE REVIEW

**Comment by ukernel** [comment]
don't merge for now

**Comment by batrick** [comment]
This needs the fix mentioned here:

https://github.com/ceph/ceph/pull/21166#discussion_r184057143

**Comment by ukernel** [comment]
please also cherry pick https://github.com/ceph/ceph/commit/ca6c8a7a1956691837948c38ff7c5b7c45f2a051

**Comment by pdvian** [comment]
@ukernel @batrick cherry-picked ca6c8a7 and added to this PR. Please review.

**Comment by batrick** [comment]
LGTM

**Pull request merged**
