### PR TITLE
[DNM] ceph-disk, ceph-detect-init: Add missing "six" module

### PR DESCRIPTION
**Pull request by badone**
Fixes problem noted at https://github.com/pypa/setuptools/issues/1042

Signed-off-by: Brad Hubbard <bhubbard@redhat.com>

### CODE REVIEW

**Comment by badone** [comment]
Build failure is expected

**Comment by dmick** [comment]
Let's not do this if they've fixed the upstream

**Comment by tchaikov** [comment]
but we need to wait until they have a new release and push it to pypi.

**Comment by badone** [comment]
Actually, they haven't even merged the fix yet

**Comment by badone** [comment]
Reopening in case we need it as I'm going offline soon.

**Comment by badone** [comment]
Didn't work.

**Pull request closed without merging**
