### PR TITLE
vstart: --osd_num 1 did not take effect in the generated ceph.conf

### PR DESCRIPTION
**Pull request by Ted-Chang**
Signed-off-by: Ted Zhang <ted.g.zhang@live.com>

### CODE REVIEW

**Comment by liewegas** [comment]
is this a problemw ith --num_osd or also the OSD= env var?  I'd like to remove the former.

**Comment by Ted-Chang** [comment]
It's a problem with --num_osd.

**Comment by tchaikov** [comment]
removing these options in #18648

**Comment by tchaikov** [comment]
@Ted-Chang the `--osd_num` options is dropped in #18648 . so i am closing this PR. thanks for your contribution!

**Pull request closed without merging**
