### PR TITLE
[DNM] rgwlc flags and flag ArchiveZone

### PR DESCRIPTION
**Pull request by mattbenjamin**
## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [x] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests
- Teuthology
  - [ ] Completed teuthology run
  - [ ] No teuthology test necessary (e.g., documentation)

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by cbodley** [comment]
ok, so a lifecycle rule that contains:
```xml
<Filter>
  <Flags>ArchiveZone</Flags>
</Filter>
```
would apply only on the archive zone, and any other policy would apply only on normal zones? that sounds right

regarding `Flags` itself, i don't think it's necessary to parse the value for multiple flag names, because you can already compose the filters with `<And>`:
```xml
<Filter>
  <And>
    <Flag>ArchiveZone</Flag>
    <Flag>OtherThing</Flag>
  </And>
</Filter>
```
maybe the 'flags' part is just an implementation detail, and we could express this more directly as:
```xml
<Filter>
  <And>
    <ArchiveZoneOnly />
    <OtherThing />
  </And>
</Filter>
```
what do you think?

**Comment by mattbenjamin** [comment]
> ok, so a lifecycle rule that contains:
> 
> ```
> <Filter>
>   <Flags>ArchiveZone</Flags>
> </Filter>
> ```
> 
> would apply only on the archive zone, and any other policy would apply only on normal zones? that sounds right
> 
> regarding `Flags` itself, i don't think it's necessary to parse the value for multiple flag names, because you can already compose the filters with `<And>`:
> 
> ```
> <Filter>
>   <And>
>     <Flag>ArchiveZone</Flag>
>     <Flag>OtherThing</Flag>
>   </And>
> </Filter>
> ```
> 
> maybe the 'flags' part is just an implementation detail, and we could express this more directly as:
> 
> ```
> <Filter>
>   <And>
>     <ArchiveZoneOnly />
>     <OtherThing />
>   </And>
> </Filter>
> ```
> 
> what do you think?

I think it's at least XML-friendly to permit multiple flag sections, but then it feels less like a flag set.  I don't like the idea of creating new elements for each new thingumbob.  Is the flags with encoded flag bits really a problem?

**Comment by mattbenjamin** [comment]
> > ok, so a lifecycle rule that contains:
> > ```
> > <Filter>
> >   <Flags>ArchiveZone</Flags>
> > </Filter>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > would apply only on the archive zone, and any other policy would apply only on normal zones? that sounds right
> > regarding `Flags` itself, i don't think it's necessary to parse the value for multiple flag names, because you can already compose the filters with `<And>`:
> > ```
> > <Filter>
> >   <And>
> >     <Flag>ArchiveZone</Flag>
> >     <Flag>OtherThing</Flag>
> >   </And>
> > </Filter>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > maybe the 'flags' part is just an implementation detail, and we could express this more directly as:
> > ```
> > <Filter>
> >   <And>
> >     <ArchiveZoneOnly />
> >     <OtherThing />
> >   </And>
> > </Filter>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > what do you think?
> 
> I think it's at least XML-friendly to permit multiple flag sections, but then it feels less like a flag set. I don't like the idea of creating new elements for each new thingumbob. Is the flags with encoded flag bits really a problem?

(one thing I'm trying to avoid is rewriting the entire parsing of Filter, because, we should have just used rapidxml, or something--and instead..we have a whole nest of classes none of whose implementation I really like)

**Comment by mattbenjamin** [comment]
> > > ok, so a lifecycle rule that contains:
> > > ```
> > > <Filter>
> > >   <Flags>ArchiveZone</Flags>
> > > </Filter>
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > would apply only on the archive zone, and any other policy would apply only on normal zones? that sounds right
> > > regarding `Flags` itself, i don't think it's necessary to parse the value for multiple flag names, because you can already compose the filters with `<And>`:
> > > ```
> > > <Filter>
> > >   <And>
> > >     <Flag>ArchiveZone</Flag>
> > >     <Flag>OtherThing</Flag>
> > >   </And>
> > > </Filter>
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > maybe the 'flags' part is just an implementation detail, and we could express this more directly as:
> > > ```
> > > <Filter>
> > >   <And>
> > >     <ArchiveZoneOnly />
> > >     <OtherThing />
> > >   </And>
> > > </Filter>
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > what do you think?
> > 
> > 
> > I think it's at least XML-friendly to permit multiple flag sections, but then it feels less like a flag set. I don't like the idea of creating new elements for each new thingumbob. Is the flags with encoded flag bits really a problem?
> 
> (one thing I'm trying to avoid is rewriting the entire parsing of Filter, because, we should have just used rapidxml, or something--and instead..we have a whole nest of classes none of whose implementation I really like)

(4:17:18 PM) cbodley: my suggestion is extensible in both ways

Ok, I get it, I think.  I agree, we need to deal with multiple Flags elements in some sane manner in any case.

Matt

**Pull request closed without merging**
