### PR TITLE
squid: qa/suites/rados/thrash-old-clients: update supported releases and distro

### PR DESCRIPTION
**Pull request by ljflores**
Backport of https://github.com/ceph/ceph/pull/57934
Fixes: https://tracker.ceph.com/issues/66460
Parent tracker: https://tracker.ceph.com/issues/66398

---------------------------------------------------

thrash-old-clients tests should only support N-3 releases. To fix this for
main, I removed all releases < quincy and have added squid.

Also, we are fully switching to centos.9_stream packages/containers after
the centos.8_stream end of life, so I changed the distro from centos.8_stream
to centos.9_stream.

Modifications:
- For this squid backport, I kept pacific since that fits into N-3 where
  N is squid.
- Pacific does not build c9 packages, so I picked an alternative distro
  that is shared among all represented releases: ubuntu 20.04.

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [x] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Comment by ljflores** [comment]
Before: https://pulpito.ceph.com/lflores-2024-06-12_21:24:38-rados:thrash-old-clients-squid-distro-default-smithi/
After: https://pulpito.ceph.com/lflores-2024-06-12_21:23:44-rados:thrash-old-clients-squid-distro-default-smithi/

**Comment by neha-ojha** [comment]
> Before: https://pulpito.ceph.com/lflores-2024-06-12_21:24:38-rados:thrash-old-clients-squid-distro-default-smithi/ After: https://pulpito.ceph.com/lflores-2024-06-12_21:23:44-rados:thrash-old-clients-squid-distro-default-smithi/

Are the health warnings just a matter of adding to the ignorelist?

**Comment by ljflores** [comment]
> > Before: https://pulpito.ceph.com/lflores-2024-06-12_21:24:38-rados:thrash-old-clients-squid-distro-default-smithi/ After: https://pulpito.ceph.com/lflores-2024-06-12_21:23:44-rados:thrash-old-clients-squid-distro-default-smithi/
> 
> Are the health warnings just a matter of adding to the ignorelist?

Yeah, I'll add a commit to handle that all in the same PR.

**Comment by ljflores** [comment]
> > Before: https://pulpito.ceph.com/lflores-2024-06-12_21:24:38-rados:thrash-old-clients-squid-distro-default-smithi/ After: https://pulpito.ceph.com/lflores-2024-06-12_21:23:44-rados:thrash-old-clients-squid-distro-default-smithi/
> 
> Are the health warnings just a matter of adding to the ignorelist?

Yes, I have added the commit from main that addresses the "mon down" warnings.

There are also some warnings about the no-scrub flag being set, which is still a problem in main. That issue is tracked here and will be fixed in a later PR:
- https://tracker.ceph.com/issues/66474

**Comment by ljflores** [comment]
New "after" results scheduled here:
https://pulpito.ceph.com/lflores-2024-06-13_21:59:44-rados:thrash-old-clients-squid-distro-default-smithi/

**Review by neha-ojha — APPROVED** [review]

**Pull request merged**
