### PR TITLE
test: new librbd discard after write test case

### PR DESCRIPTION
**Pull request by dillaman**
Signed-off-by: Jason Dillaman <dillaman@redhat.com>

### CODE REVIEW

**Comment by vshankar** [comment]
LGTM

**Comment by vshankar** [comment]
@ceph-jenkins retest this please

**Comment by trociny** [comment]
@dillaman @vshankar It looks like it does not handle properly `rbd_skip_partial_discard` config option:

http://qa-proxy.ceph.com/teuthology/trociny-2016-10-31_11:04:00-rbd-wip-mgolub-testing---basic-vps/506131/teuthology.log

**Comment by dillaman** [comment]
@trociny thanks -- I'll tweak it under a new PR

**Comment by dillaman** [comment]
Fixed under PR #11703

**Pull request merged**
