### PR TITLE
common/Formatter: dump inf/nan as null

### PR DESCRIPTION
**Pull request by sajibreadd**
Fixes: https://tracker.ceph.com/issues/66215
Reference PR: https://github.com/ceph/ceph/pull/57695

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [x] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Review by batrick — APPROVED** [review]

**Review by ifed01 — APPROVED** [review]

**Comment by sajibreadd** [comment]
jenkins test make check

**Comment by sajibreadd** [comment]
jenkins test api

**Comment by sajibreadd** [comment]
jenkins test windows

**Comment by sajibreadd** [comment]
jenkins test windows

**Comment by sajibreadd** [comment]
jenkins test windows

**Comment by sajibreadd** [comment]
jenkins test make check

**Comment by sajibreadd** [comment]
jenkins test api

**Comment by sajibreadd** [comment]
jenkins test windows

**Comment by sajibreadd** [comment]
jenkins test make check

**Comment by sajibreadd** [comment]
jenkins test windows

**Comment by petrutlucian94** [comment]
Seems like a legit failure, I think it has something to do with the precision: https://jenkins.ceph.com/job/ceph-windows-pull-requests/43810/artifact/artifacts/test_results/out/unittest_json_formatter/unittest_json_formatter_results.log

**Comment by sajibreadd** [comment]
Not sure why the test is failing in windows.
image
image
Did the exact think in the testing used CachedStackStringStream to convert the double value into string.

But in json it is dumping "inf"(`get_data()`) and in test(`css_max->strv()`) it is showing "1.7976931348623157e+308"
https://jenkins.ceph.com/job/ceph-windows-pull-requests/43815/artifact/artifacts/test_results/out/unittest_json_formatter/unittest_json_formatter_results.log

I am out of my observations, @batrick @ifed01 any thoughts on this?

**Comment by sajibreadd** [comment]
jenkins test windows

**Comment by sajibreadd** [comment]
make check

**Comment by sajibreadd** [comment]
jenkins test make check

**Pull request merged**
