### PR TITLE
qa/multisite: add extra checkpoints in datalog_autotrim testcase

### PR DESCRIPTION
**Pull request by smanjara**
https://tracker.ceph.com/issues/67207

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Comment by smanjara** [comment]
we may have datalog entries being written simultaneously with datalog trim running. at this point, there might still be some datalog entries having their timestamp lower than the datalog status marker timestamp which may not get cleared. for a brief duration sometimes the sync status can show as caught up while they are still processing shards. in the test, we rely on data sync checkpoint before issuing trim to tell us if sync is caught up. I have added a second data checkpoint call including delay timer and a bucket sync checkpoint. hopefully that should give us enough time to ensure that we are fully in sync atleast for the workload we test in multisite suite.

I understand that the error may not occur during every run which is why I ran quite a few jobs to make sure the fix is working. they all pass `test_datalog_autotrim()` test case.

https://pulpito.ceph.com/smanjara-2024-11-01_22:42:15-rgw:multisite-main-distro-default-smithi/7977125/
https://pulpito.ceph.com/smanjara-2024-11-01_22:41:58-rgw:multisite-main-distro-default-smithi/7977122/
https://pulpito.ceph.com/smanjara-2024-11-01_22:41:46-rgw:multisite-main-distro-default-smithi/7977119/
https://pulpito.ceph.com/smanjara-2024-11-01_22:41:31-rgw:multisite-main-distro-default-smithi/7977116/

**Review by cbodley — APPROVED** [review]

**Comment by smanjara** [comment]
jenkins test make check

**Comment by cbodley** [comment]
jenkins test api

**Comment by cbodley** [comment]
jenkins test make check

**Comment by smanjara** [comment]
jenkins test api

**Comment by smanjara** [comment]
passes https://pulpito.ceph.com/smanjara-2024-11-22_22:48:55-rgw:multisite-rgw-multisite-two-zonegroups-distro-default-smithi/

**Pull request merged**
