### PR TITLE
fuse: handle errors appropriately when getting group list

### PR DESCRIPTION
**Pull request by jtlayton**
Currently, the GET_GROUPS macro just ignores errors that can occur when
attempting to get the list of groups. Change it to a real function that
returns an error when getting groups fails, and check for errors in the
callers.

Tracker: http://tracker.ceph.com/issues/23446
Signed-off-by: Jeff Layton <jlayton@redhat.com>

### CODE REVIEW

**Comment by jtlayton** [comment]
Teuthology tests are running now:

    http://pulpito.ceph.com/jlayton-2018-03-23_12:51:39-fs-wip-jlayton-23446-distro-basic-smithi/

**Comment by jtlayton** [comment]
Retest this please

**Comment by ukernel** [comment]
getgroups() may return -ENOSYS. I think ceph-fuse shouldn't reply error in this case. besides, do we really need to reply error immediately. how about just set count to 0

**Comment by jtlayton** [comment]
Thanks @ukernel.

That does make a lot more sense -- let's do that. We can have it log an error when fetching groups fails with a hard error too, which would make it easier to debug problems when they occur. I'll close this request for now, and reopen it once I re-roll the patch to do that.

**Comment by batrick** [comment]
I like the error checking in this patch so let's keep those parts. I agree that using an empty group list makes sense for `-ENOSYS`.

**Pull request closed without merging**
