### PR TITLE
pacific: qa: fsync dir for asynchronous creat on stray tests

### PR DESCRIPTION
**Pull request by ajarr**
---
1.  backport tracker: https://tracker.ceph.com/issues/52680
     backport of https://github.com/ceph/ceph/pull/42763
     parent tracker: https://tracker.ceph.com/issues/51716

---
2. backport tracker: https://tracker.ceph.com/issues/52875
    backport of https://github.com/ceph/ceph/pull/43163
    parent tracker: https://tracker.ceph.com/issues/52606

### CODE REVIEW

**Comment by ajarr** [comment]
the commit in the original PR https://github.com/ceph/ceph/pull/43163/commits/a5675535ba532cfe782238d995751f9bc91f5078 was omitted as it is already available in pacific https://github.com/ceph/ceph/commit/93a13067aa6c

**Comment by ajarr** [comment]
@vshankar if this looks OK, please set the flags so that Yuri is alerted and can test this PR

**Comment by vshankar** [comment]
@ajarr are the two trackers related?

**Comment by ajarr** [comment]
> @ajarr are the two trackers related?
> 
> EDIT: doesn't look related to me.

Initially, I included the other backport of https://tracker.ceph.com/issues/52680 to avoid minor conflicts in test. Then realized that the tracker ticket 52680 has also been overlooked. It's also an important backport that will help during recovery of file systems with single active MDS when monitor databases are recovered after being lost.

**Comment by ajarr** [comment]
@vshankar PTAL

**Comment by vshankar** [comment]
> Initially, I included the other backport of https://tracker.ceph.com/issues/52680 to avoid minor conflicts in test. Then realized that the tracker ticket 52680 has also been overlooked. It's also an important backport that will help during recovery of file systems with single active MDS when monitor databases are recovered after being lost.

Thanks for confirming.

**Review by vshankar — APPROVED** [review]

**Review by vshankar — APPROVED** [review]

**Pull request merged**
