### PR TITLE
rgw: delete bucket does not remove .bucket.meta file

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/11149

### CODE REVIEW

**Comment by zhouyuan** [comment]
@smithfarm thanks for the backport! is it possible to have this merged in 0.80.10 also?

**Comment by smithfarm** [comment]
@zhouyuan I believe 0.80.10 is already frozen -- @dachary, is that right?

**Comment by dachary** [comment]
@zhouyuan like @smithfarm said, it 0.80.10 has been published already

**Comment by smithfarm** [comment]
@dachary This has passed first round of integration testing as detailed in http://tracker.ceph.com/issues/11644

**Comment by dachary** [comment]
For the record, this is http://tracker.ceph.com/issues/11644#teuthology-run-commitb2aaddd3a06ac13c46df659e1f2b3119f5675802-firefly-backports-july-2015

**Comment by smithfarm** [comment]
@yehudasa: This commit has passed integration tests (see the previous comment by @dachary) -- is it OK to merge? I'm asking you because you merged the master commit that this is a backport of: https://github.com/ceph/ceph/pull/4283

**Comment by yehudasa** [comment]
@smithfarm yes

**Pull request merged**
