### PR TITLE
mds: fix mds crash when mds_max_log_events smaller.

### PR DESCRIPTION
**Pull request by majianpeng**
If 'mds max log events' small, it met this bug:

mds/journal.cc: 155: FAILED assert(ls != this)
 ceph version 9.0.1-1117-gb0dc971
(b0dc97198a45791c8b9661d4be8e531e63202005)
 1: (ceph::__ceph_assert_fail(char const*, char const*, int, char
const*)+0x80) [0x16ef7bf]
 2: (LogSegment::try_to_expire(MDS*,
C_GatherBuilderBase<MDSInternalContextBase, MDSGather>&, int)+0x1925)
[0x15475e5]
 3: (MDLog::try_expire(LogSegment*, int)+0x66) [0x14c50a0]
 4: (MDLog::trim(int)+0xd67) [0x14c4511]
 5: (MDS::tick()+0x265) [0x1146e0b]
 6: (MDS::C_MDS_Tick::finish(int)+0x32) [0x11693b2]
 7: (Context::complete(int)+0x27) [0x11611a7]
 8: (MDSInternalContextBase::complete(int)+0x1a4) [0x14977fa]
 9: (SafeTimer::timer_thread()+0x37a) [0x16e28fa]
 10: (SafeTimerThread::entry()+0x1c) [0x16e3c56]
 11: (Thread::entry_wrapper()+0xa8) [0x16df0ee]
 12: (Thread::_entry_func(void*)+0x18) [0x16df03c]
 13: /lib64/libpthread.so.0() [0x30c9c07555]
 14: (clone()+0x6d) [0x30c9901f3d]

Like mds asok command: flush journal, if there is only one segment, we
start a new segment to avoid this. But expect mds is stopping.

Signed-off-by: Jianpeng Ma <jianpeng.ma@intel.com>

### CODE REVIEW

**Comment by majianpeng** [comment]
@gregsfortytwo . see this commit(76635a474561636854e62c8b9a3b5064b2f311a4). Can you review this? Thanks!

**Comment by jcsp** [comment]
There isn't a setting called mds_max_log_events, can you say specifically which setting you mean?

**Comment by jcsp** [comment]
Oh, never mind, mds_log_max_events

**Comment by jcsp** [comment]
Hmm, we could alternatively enforce that mds_log_max_events has to be > mds_log_events_per_segment, to avoid this case.  There isn't a practical use for such small values, right?  Similar: http://tracker.ceph.com/issues/10377

**Comment by ukernel** [comment]
I agree with jcsp, we should enforce that mds_log_max_events > mds_log_events_per_segment

**Comment by majianpeng** [comment]
@ukernel. In face, at default, mds_log_max_events  is  -1. And segments also control the trim. and the the parameter of MDLog::trim(int max) although it don't set. I think add segments.size() > 1 check is simple.

**Comment by gregsfortytwo** [comment]
Yeah, this looks fine to me. Can you change the commit messages so none of them are over 80 characters in a line, please? (They're getting cut off in the github interface and won't play nice with standard terminals.)

**Comment by gregsfortytwo** [comment]
Although maybe we should additionally require that an enforced (ie, not -1) mds_log_max_events value is larger than the number of events in a segment? Requiring that we have multiple segments basically covers that case here but I'm not sure if there are other such oddities or not.

**Comment by majianpeng** [comment]
@gregsfortytwo . updated and please review. Thanks!

**Comment by gregsfortytwo** [comment]
Looks good to me; merging as the available fix. If anybody prefers a different formulation we can revisit.

**Pull request merged**
