### PR TITLE
mgr/dashboard: Allow managing iSCSI Initiator after removing from group

### PR DESCRIPTION
**Pull request by tspmelo**
Fixes: https://tracker.ceph.com/issues/47445

Signed-off-by: Tiago Melo <tmelo@suse.com>

## Checklist
- [x] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by tspmelo** [comment]
jenkins test dashboard

**Review by Devp00l — COMMENTED** [review]
Thanks for the fix but could you please add some tests?

**Comment by tspmelo** [comment]
jenkins test make check

**Review by Devp00l — APPROVED** [review]
LGTM

**Comment by bk201** [comment]
If I remove the group and add a group with a different name in the same round, there is an error after clicking edit. I test the master code and there is a similar problem. Not quite sure if it's a backend problem or frontend problem.

Please see https://imgur.com/a/thydbmV (upload to imgur for better GIF time seek)

**Review by votdev — APPROVED** [review]

**Pull request merged**
