### PR TITLE
Revert "*: remove legacy ceph_volume_client.py library"

### PR DESCRIPTION
**Pull request by kotreshhr**
This reverts commit a3db265ad5b3ff899d8b71164a7f9ea5a426b19e.

The ceph_volume_client is being used by manila and it's
not fully equipped to use mgr/volumes and expects to use
ceph_volume_client for one more release. Hence reverting
this commit.

Fixes: https://tracker.ceph.com/issues/48923
Signed-off-by: Kotresh HR <khiremat@redhat.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by kotreshhr** [comment]
Teuthology Run:

http://pulpito.front.sepia.ceph.com/khiremat-2021-01-19_09:23:16-fs:volumes-wip-khiremat-38960-revert-removal-cephvolclient-distro-basic-smithi/

The failures are know and are tracked below:

1. https://tracker.ceph.com/issues/48830
2. https://tracker.ceph.com/issues/48411

**Comment by kotreshhr** [comment]
@tchaikov PTAL

**Comment by kotreshhr** [comment]
Teuthology Run with fs upgrade tests as well:

http://pulpito.front.sepia.ceph.com/khiremat-2021-01-19_11:48:05-fs-wip-khiremat-38960-revert-removal-cephvolclient-distro-basic-smithi/

**Review by ajarr — APPROVED** [review]
thanks a lot, Kotresh!

**Review by vkmc — APPROVED** [review]
The change looks ok. And definitely it's appreciated so we can have a smooth and safer transition to the new ceph-mgr interface on the manila cephfs drivers. Thanks Kotresh!

**Comment by ajarr** [comment]
@fullerdj can you merge this? or can we go ahead?

**Comment by batrick** [comment]
I've read the email discussion and I'm okay with keeping it for Pacific. However, I would suggest we just apply this to the pacific branch and not master.

**Comment by kotreshhr** [comment]
> I've read the email discussion and I'm okay with keeping it for Pacific. However, I would suggest we just apply this to the pacific branch and not master.

I have raised PR[1] against pacific and closing this PR against master.

[1] https://github.com/ceph/ceph/pull/39014

**Pull request closed without merging**
