### PR TITLE
blkin: Fixed a segfault caused by trace events

### PR DESCRIPTION
**Pull request by mlogic**
Signed-off-by: Yan Li <elliot.li@gmail.com>

### CODE REVIEW

**Comment by tchaikov** [comment]
@liewegas this patch is targeting wip-blkin branch and that branch is diverting from master for a while. so i am removing the "infernalis" tag from it. @xuechendi do you happen to know if we want to merge the blkin changes back into master in near future?

**Comment by xuechendi** [comment]
Hi, kefu

This branch still meet some rados suite test error in blkin branch, and I don’t have much time to fix this in near future, this branch is originally owned by Josh, CC him here

Hi, Josh,
I am thinking , can I divide blkin codes into several commit by osd part, rados part then test separately, so it will be much easier for debugging. What do you think?

Best Regards,
-Chendi

**Comment by tchaikov** [comment]
@xuechendi cool thanks. =)

and shall we merge this change into wip-blkin? it looks like a sane one. let me know if you need any help on merging/pushing it.

**Comment by jdurgin** [comment]
@xuechendi Splitting the commits up like that is a good idea. @cbodley is also interested in blkin, and may be able to help debug it too.

**Pull request merged**
