### PR TITLE
mgr/diskprediction: Add diskprediction local plugin dependencies

### PR DESCRIPTION
**Pull request by hsiang41**
Separate diskprediction local plugin dependencies from the diskprediction clould plugin dependencies requirements.txt.

Signed-off-by: Rick Chen <rick.chen@prophetstor.com>

- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by hsiang41** [comment]
@dmick Redefine the diskprediction local and the diskprediction cloud dependencies requirement file.

**Comment by hsiang41** [comment]
retest this please

**Comment by sebastian-philipp** [comment]
fyi, when installing this with Python 3 (when executing `script/run_mypy.sh`), I'm getting

```
Collecting grpc==0.3.post19 (from -r pybind/mgr/diskprediction_cloud/requirements.txt (line 5))
  Using cached https://files.pythonhosted.org/packages/dd/63/e25fa1e7dbbd44ae4d2d5ceb1bfef517849c854795e73d01bfd3d250a8b1/grpc-0.3-19.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-lm6khbzz/grpc/setup.py", line 7, in <module>
        version_tuple = __import__('grpc').VERSION
      File "/tmp/pip-build-lm6khbzz/grpc/grpc/__init__.py", line 6, in <module>
        from .rpc import *
      File "/tmp/pip-build-lm6khbzz/grpc/grpc/rpc.py", line 141
        except OSError, ex:
                      ^
    SyntaxError: invalid syntax
```

do we need to upgrade the `grpc` dependendy, too?

**Comment by dmick** [comment]
I believe that grpc should be completely removed

**Comment by hsiang41** [comment]
retest this please

**Comment by sebastian-philipp** [comment]
Relates to https://tracker.ceph.com/issues/38088

**Comment by hsiang41** [comment]
retest this please

**Comment by sebastian-philipp** [comment]
@hsiang41 do you want to amend your PR?

**Comment by alfonsomthd** [comment]
> fyi, when installing this with Python 3 (when executing `script/run_mypy.sh`), I'm getting
> 
> ```
> Collecting grpc==0.3.post19 (from -r pybind/mgr/diskprediction_cloud/requirements.txt (line 5))
>   Using cached https://files.pythonhosted.org/packages/dd/63/e25fa1e7dbbd44ae4d2d5ceb1bfef517849c854795e73d01bfd3d250a8b1/grpc-0.3-19.tar.gz
>     Complete output from command python setup.py egg_info:
>     Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "/tmp/pip-build-lm6khbzz/grpc/setup.py", line 7, in <module>
>         version_tuple = __import__('grpc').VERSION
>       File "/tmp/pip-build-lm6khbzz/grpc/grpc/__init__.py", line 6, in <module>
>         from .rpc import *
>       File "/tmp/pip-build-lm6khbzz/grpc/grpc/rpc.py", line 141
>         except OSError, ex:
>                       ^
>     SyntaxError: invalid syntax
> ```
> 
> do we need to upgrade the `grpc` dependendy, too?

I'm facing the same issue.

**Comment by dmick** [comment]
grpc should not be in this requirements list

**Comment by sebastian-philipp** [comment]
@hsiang41 Please prefix the title of your commit message with `mgr/diskprediction`.

**Comment by hsiang41** [comment]
> @hsiang41 Please prefix the title of your commit message with `mgr/diskprediction`.

done.

**Comment by sebastian-philipp** [comment]
We don't need QA tests for this PR. We can just merge it then,

**Comment by joehou89** [comment]
excuse, i have a question,  we have a 3-nodes cluster,  and the deployment on the cluster is version 15.2.17 of Ceph. 
we saw version 15.2.17 of Ceph has some submissions related to disk prediction on the Ceph official website, so we would like to use the disk prediction feature,  however , when i excute the command ' ceph mgr module enable  diskprediction_local ', it replies like this as follows: 

[root@rbd_perf001 ~] ceph mgr module enable  diskprediction_local
Error ENOENT: all mgr daemons do not support module 'diskprediction_local' , pass --force to force enablement 

**so my question is : does version 15.2.17 of Ceph not support disk prediction feature ?**

thanks a lot .

**Pull request merged**
