### PR TITLE
ceph-fuse: link to libtcmalloc or jemalloc

### PR DESCRIPTION
**Pull request by ukernel**
Fixes: http://tracker.ceph.com/issues/16655
Signed-off-by: Yan, Zheng <zyan@redhat.com>

### CODE REVIEW

**Comment by tchaikov** [comment]
shall we backport this fix to jewel? as master is not using autotools anymore.

**Comment by ukernel** [comment]
you mean master is using cmake now? recently I tried using cmake to compile the master several times, most attempts failed.

**Comment by tchaikov** [comment]
both gitbuilders and jenkins "make check" job are using cmake now. if cmake does not work for you, maybe it's the acconfig.h created by `configure`?

**Comment by ktdreyer** [comment]
@tchaikov any objections to merging this?

**Comment by tchaikov** [comment]
@ktdreyer no, not at all.

**Comment by tchaikov** [comment]
but shall we have a more general way to link against the allocator libraries?

**Comment by wjwithagen** [comment]
On 14-7-2016 11:21, Kefu Chai wrote:
> but shall we have a more general way to link against the allocator
> libraries?

My cmake wip (#10024) contains a piece of code where it actually
excludes any allocator libs, since FreeBSD already use jemalloc as
native allocator.

**Comment by jcsp** [comment]
Checked this didn't break anything in http://pulpito.ceph.com/jspray-2016-07-13_08:15:02-fs-wip-jcsp-testing-20160713-distro-basic-mira/

@tchaikov @ktdreyer feel free to merge if this is the needed change for jewel (I held off because the last couple of comments made me uncertain)

**Comment by tchaikov** [comment]
thanks for your input, @wjwithagen.  i am merging this change as it is. let's figure out a better way to address it later on.

**Comment by tchaikov** [comment]
thanks for your input, @wjwithagen.  i am merging this change as it is. let's figure out a better way to address it later on.

**Comment by wjwithagen** [comment]
On 14-7-2016 14:28, Kefu Chai wrote:
> thanks for your input, @wjwithagen <https://github.com/wjwithagen>. i am
> merging this change as it is. let's figure out a better way to address
> it later on.

As long as `${ALLOC_LIBS}` is used it'll keep working as planned.
Because that is the definition I wrapped, and stays empty on FreeBSD.
So as long as this VAR only uses the type of allocator lib, and no more
things will work.

**Comment by tchaikov** [comment]
okay, actually i don't really like how `$ALLOC_LIBS` is initialized, we should set it to variabls like `${Tcmalloc_LIBRARIES}`, but that's another story.

**Pull request merged**
