### PR TITLE
pacific: mgr/dashboard: Notification banners at the top of the UI have fixed height 

### PR DESCRIPTION
**Pull request by votdev**
backport tracker: https://tracker.ceph.com/issues/53929

---

backport of https://github.com/ceph/ceph/pull/44238
parent tracker: https://tracker.ceph.com/issues/51575

this backport was staged using ceph-backport.sh version 16.0.0.6848
find the latest version at https://github.com/ceph/ceph/blob/master/src/script/ceph-backport.sh

### CODE REVIEW

**Comment by votdev** [comment]
Bildschirmfoto vom 2022-01-24 16-45-41

**Comment by votdev** [comment]
jenkins test make check

**Comment by nizamial09** [comment]
jenkins test dashboard

**Comment by nizamial09** [comment]
jenkins test dashboard cephadm

**Comment by nizamial09** [comment]
@votdev you might need to backport https://github.com/ceph/ceph/pull/44693 too else it'll break the e2e testing.

**Review by nizamial09 — APPROVED** [review]

**Review by pereman2 — APPROVED** [review]

**Review by avanthakkar — APPROVED** [review]

**Pull request merged**
