### PR TITLE
qa/suites/rados/objectstore: enable experimental features for testing bluestore

### PR DESCRIPTION
**Pull request by tchaikov**

### CODE REVIEW

**Comment by tchaikov** [comment]
@dmick this PR is based on your #13448, please feel free to cherry pick it.

**Comment by tchaikov** [comment]
tested at http://pulpito.ceph.com/kchai-2017-02-16_12:07:59-rados-wip-kefu-testing---basic-mira/822139/

but it still failed:
```
2017-02-16T12:11:22.499 INFO:tasks.workunit.client.0.mira056.stderr:+ ceph-objectstore-tool --op mkfs --data-path store_test_fuse_dir --type bluestore
2017-02-16T12:11:22.506 INFO:tasks.workunit.client.0.mira056.stderr:2017-02-16 12:11:22.509112 7f8757415dc0 -1 did not load config file, using default settings.
2017-02-16T12:11:22.507 INFO:tasks.workunit.client.0.mira056.stderr:Unable to create store of type bluestore
```

**Comment by tchaikov** [comment]
maybe we should pass the path to ceph.conf to cot.

**Comment by dmick** [comment]
One can supply it with CEPH_CONF in the env, or just supply the switch with --enable....=bluestore (or *) on the commandline.  Not sure which is better, or if it matters.

**Comment by dmick** [comment]
c-o-t ought to be reading ceph.conf.  The problem is it's written by the ceph task, but fusestore.yaml doesn't call ceph, only install and workunit.  Somehow ceph.conf needs writing.

**Comment by dmick** [comment]
So, I'm trying and failing to figure out just how to add in a write_conf() or the like into workunit, but I think that's the answer here

**Comment by tchaikov** [comment]
@dmick i updated the test, so we pass `--enable....=bluestore` via an environmental variable as you suggested. it's more straightforward, imo.

**Comment by dmick** [comment]
Well, the thing is, other workunits may well need ceph.conf if they don't run ceph, and for all I know, already are trying to pass other things besides the experimental flag...

**Comment by tchaikov** [comment]
test passed at http://pulpito.ceph.com/kchai-2017-02-17_05:01:32-rados-wip-qa-objectstore-kefu---basic-mira/

**Pull request merged**
