### PR TITLE
pacific: cmake, ceph.spec.in: build with header only fmt on RHEL

### PR DESCRIPTION
**Pull request by tchaikov**
backport of #42464 

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by ktdreyer** [comment]
@b-ranto looks like we'll want to add this to the RHEL 9 ceph package.

**Review by jdurgin — APPROVED** [review]

**Comment by b-ranto** [comment]
My downstream testing suggests that we are still linking against libfmt even after these patches were applied. After I removed libfmt-devel from the build requires, it made matters even worse as it started requiring a non-existing version of libfmt (libfmt.so.6 instead of libfmt.so.7 that was available on the system).

**Comment by tchaikov** [comment]
> FYI: My downstream testing suggests that we are still linking against libfmt even after these patches were applied. After I removed libfmt-devel from the build requires, it made matters even worse as it started requiring a non-existing version of libfmt (libfmt.so.6 instead of libfmt.so.7 that was available on the system).

@b-ranto hi Boris, could you be more specific? which library or executable is still linked against libfmt? i tested on CentOS stream. and i checked 

- ceph-osd
- rados
- libceph-common.so
- librados.so

using `ldd`.

none of them is linked against libfmt.

**Comment by b-ranto** [comment]
My back-port might be incomplete I suppose (it is based on 16.2.4 with these three patches). I was testing this on the `ceph-dencoder` binary and I could still see `libfmt.so.X` in the `ldd` output.

You can see my spec file/back-ported patches for RHEL 9, here:

https://gitlab.com/redhat/centos-stream/rpms/ceph

**Comment by tchaikov** [comment]
```
[kchai@o10 build]$ ldd bin/ceph-dencoder
	linux-vdso.so.1 (0x00007fff453b7000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007fe38fc27000)
	librt.so.1 => /lib64/librt.so.1 (0x00007fe38fa1f000)
	libresolv.so.2 => /lib64/libresolv.so.2 (0x00007fe38f808000)
	libtcmalloc.so.4 => /lib64/libtcmalloc.so.4 (0x00007fe38f40c000)
	libceph-common.so.2 => /home/kchai/ceph/build/lib/libceph-common.so.2 (0x00007fe38e59e000)
	libblkid.so.1 => /lib64/libblkid.so.1 (0x00007fe38e34b000)
	libcrypto.so.1.1 => /lib64/libcrypto.so.1.1 (0x00007fe38de63000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fe38dc43000)
	libudev.so.1 => /lib64/libudev.so.1 (0x00007fe38d9ad000)
	libibverbs.so.1 => /lib64/libibverbs.so.1 (0x00007fe38d78d000)
	librdmacm.so.1 => /lib64/librdmacm.so.1 (0x00007fe38d572000)
	libz.so.1 => /lib64/libz.so.1 (0x00007fe38d35b000)
	libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007fe38cfc6000)
	libm.so.6 => /lib64/libm.so.6 (0x00007fe38cc44000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007fe38ca2c000)
	libc.so.6 => /lib64/libc.so.6 (0x00007fe38c667000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fe38fe2b000)
	libunwind.so.8 => /lib64/libunwind.so.8 (0x00007fe38c44f000)
	libuuid.so.1 => /lib64/libuuid.so.1 (0x00007fe38c247000)
	libmount.so.1 => /lib64/libmount.so.1 (0x00007fe38bfed000)
	libnl-route-3.so.200 => /lib64/libnl-route-3.so.200 (0x00007fe38bd67000)
	libnl-3.so.200 => /lib64/libnl-3.so.200 (0x00007fe38bb44000)
	libselinux.so.1 => /lib64/libselinux.so.1 (0x00007fe38b91a000)
	libpcre2-8.so.0 => /lib64/libpcre2-8.so.0 (0x00007fe38b696000)
[kchai@o10 build]$ ldd lib/libceph-common.so.2
	linux-vdso.so.1 (0x00007ffd272e8000)
	libresolv.so.2 => /lib64/libresolv.so.2 (0x00007fd623f24000)
	libblkid.so.1 => /lib64/libblkid.so.1 (0x00007fd623cd1000)
	libcrypto.so.1.1 => /lib64/libcrypto.so.1.1 (0x00007fd6237e9000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fd6235c9000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007fd6233c5000)
	libudev.so.1 => /lib64/libudev.so.1 (0x00007fd62312f000)
	libibverbs.so.1 => /lib64/libibverbs.so.1 (0x00007fd622f0f000)
	librdmacm.so.1 => /lib64/librdmacm.so.1 (0x00007fd622cf4000)
	libz.so.1 => /lib64/libz.so.1 (0x00007fd622add000)
	libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007fd622748000)
	libm.so.6 => /lib64/libm.so.6 (0x00007fd6223c6000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007fd6221ae000)
	libc.so.6 => /lib64/libc.so.6 (0x00007fd621de9000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fd624fa9000)
	libuuid.so.1 => /lib64/libuuid.so.1 (0x00007fd621be1000)
	libmount.so.1 => /lib64/libmount.so.1 (0x00007fd621987000)
	libnl-route-3.so.200 => /lib64/libnl-route-3.so.200 (0x00007fd621701000)
	libnl-3.so.200 => /lib64/libnl-3.so.200 (0x00007fd6214de000)
	libselinux.so.1 => /lib64/libselinux.so.1 (0x00007fd6212b4000)
	librt.so.1 => /lib64/librt.so.1 (0x00007fd6210ac000)
	libpcre2-8.so.0 => /lib64/libpcre2-8.so.0 (0x00007fd620e28000)
```

**Comment by tchaikov** [comment]
@b-ranto thank you, Boris. i will try to apply these patches on top of 16.2.4 tomorrow and to see if i can reproduce this issue.

**Comment by tchaikov** [comment]
@b-ranto https://gist.github.com/tchaikov/f01ee2e01bcf1be1e2d393d41519320c

**Comment by b-ranto** [comment]
@tchaikov I did apply it manually, see the `ceph.spec` file: https://gitlab.com/redhat/centos-stream/rpms/ceph/-/blob/c9s/ceph.spec#L723

I did omit the `BOOL` bit but that should not be an issue, right? I am wondering if this has something to do with the build time optimizations. Could this be caused (again) by optimizations inlining some fmt-related code (or something similar)?

The libfmt still remains a build-time dependency so we would have to have it in RHEL 9 (well, at least in the build root) anyway I suppose.

**Pull request merged**
