### PR TITLE
Revert: qa/suites/rados/thrash-old-clients: use cephadm #32377

### PR DESCRIPTION
**Pull request by sebastian-philipp**
Turns out, CentOS 7.6 is not suitable to run podman reliably.

Fixes: https://tracker.ceph.com/issues/46529

See also: https://github.com/ceph/ceph/pull/35719#issuecomment-660939761

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by jdurgin** [comment]
looks like we've only been running this suite on centos 7 due to needing older packages. For pacific we can drop luminous clients, and the latest distro mimic was built on was bionic. 

Could we switch this suite to use bionic instead of dropping cephadm?

**Comment by sebastian-philipp** [comment]
> looks like we've only been running this suite on centos 7 due to needing older packages. For pacific we can drop luminous clients, and the latest distro mimic was built on was bionic.
> 
> Could we switch this suite to use bionic instead of dropping cephadm?

Great, I can have a look into bionic!

**Comment by tchaikov** [comment]
- https://pulpito.ceph.com/kchai-2020-07-29_04:08:59-rados-wip-kefu-testing-2020-07-29-1027-distro-basic-smithi/
- https://pulpito.ceph.com/kchai-2020-07-29_11:42:32-rados-wip-kefu-testing-2020-07-29-1722-distro-basic-smithi/

**Comment by sebastian-philipp** [comment]
> * https://pulpito.ceph.com/kchai-2020-07-29_04:08:59-rados-wip-kefu-testing-2020-07-29-1027-distro-basic-smithi/
> * https://pulpito.ceph.com/kchai-2020-07-29_11:42:32-rados-wip-kefu-testing-2020-07-29-1722-distro-basic-smithi/

What? That actually worked? On the first try?

**Comment by yuriw** [comment]
`teuthology-suite -v -c $CEPH_BRANCH --ceph-repo https://github.com/ceph/ceph.git --suite-repo https://github.com/yuriw/ceph.git -k distro -n 7 -m $MACHINE_NAME -s rados/thrash-old-clients -t master -e $CEPH_QA_EMAIL -p 90 --suite-branch wip-yuriw-46529-master --force-priority --subset 9/100000`

https://pulpito.ceph.com/yuriw-2020-08-31_23:49:50-rados:thrash-old-clients-master-distro-basic-smithi

**Pull request closed without merging**
