### PR TITLE
qa: add script to test how libceph handles huge osdmaps

### PR DESCRIPTION
**Pull request by idryomov**

### CODE REVIEW

**Comment by idryomov** [comment]
retest this please

**Comment by idryomov** [comment]
retest this please

**Comment by dillaman** [comment]
jenkins test make check

**Comment by idryomov** [comment]
`make check` failures are consistent, but unrelated:
```
The following tests FAILED:
	153 - unittest_ecbackend (Not Run)
	154 - unittest_osdscrub (Not Run)
	155 - unittest_pglog (Not Run)
	156 - unittest_hitset (Not Run)
	157 - unittest_osd_osdcap (Not Run)
	158 - unittest_extent_cache (Not Run)
	159 - unittest_pg_transaction (Not Run)
	160 - unittest_ec_transaction (Not Run)
	161 - unittest_mclock_op_class_queue (Not Run)
	162 - unittest_mclock_client_queue (Not Run)
```
because
```
Start 153: unittest_ecbackend
Could not find executable /home/jenkins-build/build/workspace/ceph-pull-requests/build/bin/unittest_ecbackend
Looked in the following places:
/home/jenkins-build/build/workspace/ceph-pull-requests/build/bin/unittest_ecbackend
/home/jenkins-build/build/workspace/ceph-pull-requests/build/bin/unittest_ecbackend
/home/jenkins-build/build/workspace/ceph-pull-requests/build/bin/Release/unittest_ecbackend
/home/jenkins-build/build/workspace/ceph-pull-requests/build/bin/Release/unittest_ecbackend
/home/jenkins-build/build/workspace/ceph-pull-requests/build/bin/Debug/unittest_ecbackend
/home/jenkins-build/build/workspace/ceph-pull-requests/build/bin/Debug/unittest_ecbackend
/home/jenkins-build/build/workspace/ceph-pull-requests/build/bin/MinSizeRel/unittest_ecbackend
/home/jenkins-build/build/workspace/ceph-pull-requests/build/bin/MinSizeRel/unittest_ecbackend
/home/jenkins-build/build/workspace/ceph-pull-requests/build/bin/RelWithDebInfo/unittest_ecbackend
/home/jenkins-build/build/workspace/ceph-pull-requests/build/bin/RelWithDebInfo/unittest_ecbackend
/home/jenkins-build/build/workspace/ceph-pull-requests/build/bin/Deployment/unittest_ecbackend
/home/jenkins-build/build/workspace/ceph-pull-requests/build/bin/Deployment/unittest_ecbackend
/home/jenkins-build/build/workspace/ceph-pull-requests/build/bin/Development/unittest_ecbackend
/home/jenkins-build/build/workspace/ceph-pull-requests/build/bin/Development/unittest_ecbackend
home/jenkins-build/build/workspace/ceph-pull-requests/build/bin/unittest_ecbackend
home/jenkins-build/build/workspace/ceph-pull-requests/build/bin/unittest_ecbackend
home/jenkins-build/build/workspace/ceph-pull-requests/build/bin/Release/unittest_ecbackend
home/jenkins-build/build/workspace/ceph-pull-requests/build/bin/Release/unittest_ecbackend
home/jenkins-build/build/workspace/ceph-pull-requests/build/bin/Debug/unittest_ecbackend
home/jenkins-build/build/workspace/ceph-pull-requests/build/bin/Debug/unittest_ecbackend
home/jenkins-build/build/workspace/ceph-pull-requests/build/bin/MinSizeRel/unittest_ecbackend
home/jenkins-build/build/workspace/ceph-pull-requests/build/bin/MinSizeRel/unittest_ecbackend
home/jenkins-build/build/workspace/ceph-pull-requests/build/bin/RelWithDebInfo/unittest_ecbackend
home/jenkins-build/build/workspace/ceph-pull-requests/build/bin/RelWithDebInfo/unittest_ecbackend
home/jenkins-build/build/workspace/ceph-pull-requests/build/bin/Deployment/unittest_ecbackend
home/jenkins-build/build/workspace/ceph-pull-requests/build/bin/Deployment/unittest_ecbackend
home/jenkins-build/build/workspace/ceph-pull-requests/build/bin/Development/unittest_ecbackend
home/jenkins-build/build/workspace/ceph-pull-requests/build/bin/Development/unittest_ecbackend
Unable to find executable: /home/jenkins-build/build/workspace/ceph-pull-requests/build/bin/unittest_ecbackend
146/186 Test #153: unittest_ecbackend ......................***Not Run   0.00 sec
```

**Comment by idryomov** [comment]
retest this please

**Comment by idryomov** [comment]
http://pulpito.ceph.com/dis-2019-09-12_19:10:52-krbd-master-testing-basic-smithi/

**Pull request merged**
