### PR TITLE
nautilus: mgr/dashboard: Don't use any xlf file when building the default language

### PR DESCRIPTION
**Pull request by nizamial09**
backport tracker: https://tracker.ceph.com/issues/47753

## Checklist
- [x] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Review by alfonsomthd — APPROVED** [review]

**Comment by nizamial09** [comment]
jenkins test make check

**Comment by alfonsomthd** [comment]
jenkins test make check

**Comment by nizamial09** [comment]
jenkins test make check

**Comment by Exotelis** [comment]
Just out of curiosity, were the tests failing or what is the reason for backporting this to nautilus? I would have to build nautilus to test if the backport might cause other problems. If it's a actual bugfix and it will break nothing else, I'm fine with merging it.

**Comment by nizamial09** [comment]
> Just out of curiosity, were the tests failing or what is the reason for backporting this to nautilus? I would have to build nautilus to test if the backport might cause other problems. If it's a actual bugfix and it will break nothing else, I'm fine with merging it.

In nautilus, if we goto the the Create Pool/ Edit Pool forms, we can see that its missing a whitespace between Create and Pool. 
Same is the case for its button and many other forms.
image

The reason was generating this .xlf file for the default language. By applying this fix, I can see the whitespace appearing in between Create and Pool. 
edut

Also it doesnt seemed to break anything else in the dashboard. @Exotelis

**Review by Exotelis — APPROVED** [review]

**Pull request merged**
