### PR TITLE
doc: add 'flags' for config values in docs

### PR DESCRIPTION
**Pull request by alimaredia**
Signed-off-by: Ali Maredia <amaredia@redhat.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [x] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by alimaredia** [comment]
When I chatted with Josh about these changes he mentioned other components might have inaccurate `runtime` flags for their config vars? Should this PR be part of a bigger one to update those before we add them to the documentation? 

Also should this PR be backported so that older versions docs have the flags as well?

**Comment by mattbenjamin** [comment]
if the flags are likely to be inaccurate, then I think we need more than just a change to render the flag;  it seems like in addition to that, we need at least 3 states:  Yes, No, Unknown?

**Comment by cbodley** [comment]
is the existing `runtime` flag used anywhere? if its uses aren't accurate, i guess it's not used for anything important

maybe we just add a new flag like `requires_restart` and render something like "Changes take effect after daemon restart" if that flag is set

that way we can start adding it to rgw options, and other teams can audit/update their own options as time permits

**Comment by tchaikov** [comment]
also, as 'flags` will be rendered as user-facing document, i'd suggest adding links to https://docs.ceph.com/en/latest/dev/config/#flags . otherwise this information would be less useful to user.

**Comment by zdover23** [comment]
@alimaredia: Is this ready to merge and backport?

**Pull request closed without merging**
