### PR TITLE
rgw: avoid stuck worker thread infinitely when there are PG stuck at peering

### PR DESCRIPTION
**Pull request by guangyy**
At OSD side - if the op has a flag that it does not want to wait, and the PG it is hitting is at peering, reply back immediately with -EAGAIN, rather than queue it into waiting list

At librados side - Extend the API to support a timeout passed from caller, once it is set, it will switch to 'do not wait' mode and retry (polling) at client side until the timeout reaches.

At radosgw - leverage the new API and add a configuration to turn the flag to do timeout when communicating with OSD.

### CODE REVIEW

**Comment by guangyy** [comment]
TODO:
1. Testing - this is completely not tested yet.
2. At librados, instead of busy polling, we properly want some back-off wait.

**Comment by guangyy** [comment]
@liewegas , @yehudasa , @athanatos , would you please take a look if the general flow makes sense or not?

**Comment by liewegas** [comment]
@yehudasa is the rgw piece that simple?

**Comment by liewegas** [comment]
The only place I see that EAGAIN is currently returned by the OSD is when you are sending to replicas and they tell you to go back to the primary.  We probably do want to use a different error code.  EHOSTDOWN?  Or we could define our own...

**Comment by yehudasa** [comment]
@liewegas @guangyy not sure if we want the timeout to apply to all operations or just very specific operations. If we want it to apply to all rados operations then maybe there are a few more places that need to be changed?

**Comment by guangyy** [comment]
Hi @liewegas ,
Could you take a look at this one? Thanks.

**Comment by guangyy** [comment]
Fixed according to @liewegas 's comments, add two commits:
 1. Expose the option for rados tool
 2. Add a test to cover the newly added option

**Comment by dachary** [comment]
@guangyy this needs rebasing

**Comment by guangyy** [comment]
@dachary , sorry for the delayed response. Rebased.

**Comment by dachary** [comment]
@guangyy thanks :-)

**Comment by athanatos** [comment]
I'm a bit worried about this, doesn't it break write ordering on a single object?

**Comment by liewegas** [comment]
Yeah, this would reorder operations.  Unless it was only used on reads?  (It's ok to reorder those, as we do with RWORDERED vs !RWORDERED)

**Comment by liewegas** [comment]
Closing this pull request since it appears to be abandoned.  If you it is not abandoned, and you are still interested in championing this change, please address any review comments so far and reopen the pull request.

**Pull request closed without merging**
