### PR TITLE
pacific: pybind/mgr/pg_autoscaler: change overlapping roots to warning

### PR DESCRIPTION
**Pull request by kamoltat**
Change the log level of overlapping roots
from ``Error`` to ``Warning``.

Point the user to documentation that
explains the overlapping roots.

Added more information regarding overlapping roots
in the autoscaler documentation such as
the step to get rid of the warning.

Backporting relevant commits from the main PR:

https://github.com/ceph/ceph/pull/46242

Backport Tracker:
https://tracker.ceph.com/issues/57075

Fixes: https://tracker.ceph.com/issues/55611

Signed-off-by: Kamoltat <ksirivad@redhat.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [x] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [x] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by kamoltat** [comment]
jenkins test make check

**Review by neha-ojha — APPROVED** [review]

**Comment by kamoltat** [comment]
jenkins test make check

**Comment by ljflores** [comment]
Rados suite review: https://pulpito.ceph.com/?branch=wip-yuri3-testing-2022-08-11-0809-pacific

Failures, unrelated:
    1. https://tracker.ceph.com/issues/55443
    2. https://tracker.ceph.com/issues/53939
    3. https://tracker.ceph.com/issues/53827
    4. https://tracker.ceph.com/issues/52321
    5. https://tracker.ceph.com/issues/57207 -- created a new Tracker; unrelated to PRs in this run
    6. https://tracker.ceph.com/issues/56573
    7. https://tracker.ceph.com/issues/53501
    8. https://tracker.ceph.com/issues/54071
    9. https://tracker.ceph.com/issues/54603
    10. https://tracker.ceph.com/issues/49727 -- pending Pacific backport

Details:
    1. "SELinux denials found.." in rados run - Ceph - Infrastructure
    2. ceph-nfs-upgrade, pacific: Upgrade Paused due to UPGRADE_REDEPLOY_DAEMON: Upgrading daemon osd.0 on host smithi103 failed - Ceph - Orchestrator
    3. cephadm exited with error code when creating osd: Input/Output error. Faulty NVME? - Ceph - Orchestrator
    4. qa/tasks/rook times out: 'check osd count' reached maximum tries (90) after waiting for 900 seconds - Ceph - Rook
    5. AssertionError: Expected to find element: `cd-modal .badge:not(script,style):cy-contains('/^foo$/'), cd-modal .badge[type='submit'][value~='/^foo$/']`, but never found it. - Ceph - Mgr - Dashboard
    6. test_cephadm.sh: KeyError: 'TYPE' - Ceph - Orchestrator
    7. Exception when running 'rook' task. - Ceph - Orchestrator
    8. rados/cephadm/osds: Invalid command: missing required parameter hostname(<string>)
    9. Valgrind reports memory "Leak_IndirectlyLost" errors on ceph-mon. - Ceph - RADOS
    10. lazy_omap_stats_test: "ceph osd deep-scrub all" hangs - Ceph - RADOS

**Comment by ljflores** [comment]
jenkins test make check

**Comment by kamoltat** [comment]
jenkins test make check

**Comment by kamoltat** [comment]
NOTE: awaiting https://github.com/ceph/ceph/pull/47803 to fix the make check failure

**Comment by tchaikov** [comment]
jenkins test make check

**Pull request merged**
