### PR TITLE
mon: map_cache can become inaccurate if osd does not receive the osdmaps

### PR DESCRIPTION
**Pull request by tchaikov**
http://tracker.ceph.com/issues/12835

### CODE REVIEW

**Comment by tchaikov** [comment]
@dachary turns out we should backport "less" than you did in #5756.

- removed the refactory commit from #5756
- and reference the request using `req` directly instead using its wrapper: `MonOpRequestRef`

**Comment by tchaikov** [comment]
needs rebase

**Comment by dachary** [comment]
@tchaikov it fails http://pulpito.ceph.com/loic-2015-09-24_12:27:18-rados-hammer-backports---basic-multi/1066783/ and many other rbd / rados jobs.

**Comment by tchaikov** [comment]
removed the assertion for the MonSession, will rerun some of the failed test once the build is ready.

**Comment by tchaikov** [comment]
@dachary the test passed at http://pulpito.ceph.com/kchai-2015-11-03_00:33:48-rados:thrash-wip-5773-hammer---basic-multi/ could you take a look at this pr again? thanks!

**Comment by dachary** [comment]
@tchaikov ok, thanks !

**Comment by dachary** [comment]
It passed a run of the hammer rados suite ( see http://tracker.ceph.com/issues/13356#note-28 for details ).

**Pull request merged**
