### PR TITLE
run ceph daemons as user and group ceph

### PR DESCRIPTION
**Pull request by liewegas**
- need to do chowning stuff for ceph-osd
- rpm spec file changes are still needed
- need to validate the permissiong choices for /var/log/ceph adn /var/lib/ceph
make sense...  do we want things like qemu to be in group 
ceph?

### CODE REVIEW

**Comment by dachary** [comment]
@liewegas please ignore what seems to be a jenkins malfunction

**Comment by tserong** [comment]
Random thought: This'll presumably have some impact on the quick start docs, which recommend creating a ceph user to run `ceph-deploy` as, and giving that user sudo privileges (http://ceph.com/docs/master/start/quick-start-preflight/#create-a-ceph-user). Can the user you run the deploy as be the same user the daemons run as, or is that a bad idea?

**Comment by dalgaaf** [comment]
@tserong: is it even possible to run ceph-deploy as non-root out of the box? Especially in case ceph-deploy has to touch e.g. zypper repositories and installs packages?

**Comment by dalgaaf** [comment]
@tserong: it should be a separate user (e.g. ceph-deploy or something like that) since the documentation says the ceph user for ceph-deploy should have "password-less sudo/ssh login". And this is something we don't want for the daemon user.

**Comment by tserong** [comment]
@dalgaaf, yep, gotcha. This is potentially going to introduce a small administrative kink for people upgrading who've already got a regular user account named ceph (they'll need to rename it, I guess). Is this work likely to be backported to, say, Hammer, or is it only going into (guessing) Infernalis+?

**Comment by liewegas** [comment]
I doubt it will be practical to backport this to hammer.   Let's focus on 
doing things as "right" as we can for infernalis+.

**Comment by dachary** [comment]
The bot fails because there is no ceph user in the test environment. Should this be enforced if running as a regular non-root user ? I assume a developer running ceph-disk from its local directory may not have the ceph group in /etc/group.

**Comment by liewegas** [comment]
i got one selinux denial, see http://tracker.ceph.com/issues/12755

**Pull request merged**
