### PR TITLE
add fadvise flags for rados/rbd

### PR DESCRIPTION
**Pull request by majianpeng**

### CODE REVIEW

**Comment by liewegas** [comment]
These all look good to me!

**Comment by liewegas** [comment]
Reviewed-by:

**Comment by athanatos** [comment]
This branch doesn't build cleanly after the merge of 16af675 (one more test case needs to be updated).

**Comment by majianpeng** [comment]
@athanatos . updated & please review again! Thanks!

**Comment by athanatos** [comment]
Sorry for the delay again, needs rebase.

**Comment by majianpeng** [comment]
@athanatos . updated and please review again. Thanks!

**Comment by tchaikov** [comment]
tested at:
http://pulpito.ceph.com/ubuntu-2015-07-03_23:36:35-rados-wip-kefu-testing---basic-multi/
http://pulpito.ceph.com/ubuntu-2015-07-04_23:36:15-rados-wip-kefu-testing---basic-multi/

**Pull request merged**
