### PR TITLE
cephadm: Add --container-init again

### PR DESCRIPTION
**Pull request by mgfritch**
This reverts commit 9200b1ea8e5, reversing
changes made to e42bbba9ca8.

For running tests to narrow down the root cause of:
https://tracker.ceph.com/issues/49237

Signed-off-by: Michael Fritch <mfritch@suse.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by sebastian-philipp** [comment]
and again we see https://tracker.ceph.com/issues/49259

**Comment by sebastian-philipp** [comment]
m

**Comment by mgfritch** [comment]
closing in favor of #39739

**Comment by mgfritch** [comment]
closing in favor of #39739

**Pull request closed without merging**
