### PR TITLE
pacific: tools/cephfs-mirror: fix a dangling pointer

### PR DESCRIPTION
**Pull request by vshankar**
https://tracker.ceph.com/issues/49419

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Review by mchangir — APPROVED** [review]
looks good to me

**Comment by rishabh-d-dave** [comment]
jenkins test make check

**Review by rishabh-d-dave — APPROVED** [review]

**Comment by liewegas** [comment]
```
_______________ TestSchedule.test_created_now[simple_schedule3] ________________

self = <snap_schedule.tests.fs.test_schedule.TestSchedule object at 0x7fe334660438>
simple_schedule = <snap_schedule.fs.schedule.Schedule object at 0x7fe3346603c8>

    def test_created_now(self, simple_schedule):
        now = datetime.datetime.now(datetime.timezone.utc)
>       assert simple_schedule.created.minute == now.minute
E       assert 24 == 25
E        +  where 24 = datetime.datetime(2021, 3, 3, 17, 24, 59, 999667, tzinfo=datetime.timezone.utc).minute
E        +    where datetime.datetime(2021, 3, 3, 17, 24, 59, 999667, tzinfo=datetime.timezone.utc) = <snap_schedule.fs.schedule.Schedule object at 0x7fe3346603c8>.created
E        +  and   25 = datetime.datetime(2021, 3, 3, 17, 25, 0, 193, tzinfo=datetime.timezone.utc).minute

snap_schedule/tests/fs/test_schedule.py:65: AssertionError
```

**Comment by vshankar** [comment]
jenkins test make check

**Comment by vshankar** [comment]
> ```
> _______________ TestSchedule.test_created_now[simple_schedule3] ________________
> 
> self = <snap_schedule.tests.fs.test_schedule.TestSchedule object at 0x7fe334660438>
> simple_schedule = <snap_schedule.fs.schedule.Schedule object at 0x7fe3346603c8>
> 
>     def test_created_now(self, simple_schedule):
>         now = datetime.datetime.now(datetime.timezone.utc)
> >       assert simple_schedule.created.minute == now.minute
> E       assert 24 == 25
> E        +  where 24 = datetime.datetime(2021, 3, 3, 17, 24, 59, 999667, tzinfo=datetime.timezone.utc).minute
> E        +    where datetime.datetime(2021, 3, 3, 17, 24, 59, 999667, tzinfo=datetime.timezone.utc) = <snap_schedule.fs.schedule.Schedule object at 0x7fe3346603c8>.created
> E        +  and   25 = datetime.datetime(2021, 3, 3, 17, 25, 0, 193, tzinfo=datetime.timezone.utc).minute
> 
> snap_schedule/tests/fs/test_schedule.py:65: AssertionError
> ```

Failure is not related to this PR. @jan--f perhaps a timing thing?

**Comment by vshankar** [comment]
needs https://github.com/ceph/ceph/pull/40107

**Comment by vshankar** [comment]
https://pulpito.ceph.com/vshankar-2021-03-14_16:48:30-fs-wip-cephfs-mirror-pacific-backports-1-20210314-105034-distro-basic-gibba/

**Pull request merged**
