### PR TITLE
Miscellaneous lost fixes

### PR DESCRIPTION
**Pull request by gregsfortytwo**
This PR includes several small fixes and improvements that had become stale.

In particular, it updates #21296 (msg/async: bug fix 23600 by setting _fd = 1),
#19607 (tools/crushtool: add new Option --bucket-tree to show bucket map tree), and
#16676 (msg/async: add async msg perf counter).

### CODE REVIEW

**Comment by gregsfortytwo** [comment]
This needs some testing but I'm lazy so I'm letting Jenkins do it. Some of the source PRs apparently failed "make check" but the logs are long gone. (In particular I bet there are some crush tool output tests missing?)

**Comment by gregsfortytwo** [comment]
This should be good to go now.

The first two patches were pretty well covered in their original PRs, but if @rjfd or somebody could skim the third one to make sure I didn't mess things up interpreting the Protocols that'd be good. :)

**Comment by gregsfortytwo** [comment]
I re-pushed on latest master to try and get rid of the rook error @neha-ojha saw in http://pulpito.ceph.com/nojha-2019-04-17_01:17:27-rados-wip-stale-prs-distro-basic-smithi/ (although this ought to be fine running in an aggregate testing branch!).

**Comment by neha-ojha** [comment]
@gregsfortytwo test runs are looking good so far

http://pulpito.ceph.com/nojha-2019-04-18_01:38:39-rados-wip-stale-prs-2019-04-17-distro-basic-smithi/
rerun of dead jobs: http://pulpito.ceph.com/nojha-2019-04-18_15:35:03-rados-wip-stale-prs-2019-04-17-distro-basic-smithi/

**Comment by tchaikov** [comment]
- http://pulpito.ceph.com/kchai-2019-04-18_12:56:40-rados-wip-kefu-testing-2019-04-18-1100-distro-basic-mira/
- http://pulpito.ceph.com/kchai-2019-04-19_15:53:30-rados-wip-kefu-testing-2019-04-18-1100-distro-basic-smithi/

**Pull request merged**
