### PR TITLE
luminous: mgr: Services reported with blank hostname

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/21479
http://tracker.ceph.com/issues/22197

### CODE REVIEW

**Comment by jcsp** [comment]
Oops, please don't merge this for now: the patch has been found to have an undesirable side effect (http://tracker.ceph.com/issues/21687)

**Comment by theanalyst** [comment]
@jcsp do we still need this?

**Comment by jcsp** [comment]
Yes, but you need the follow up commit from https://github.com/ceph/ceph/pull/18484 too

**Comment by smithfarm** [comment]
@theanalyst @jcsp Brought in the follow-up commit.

**Comment by yuriw** [comment]
[wip-yuri2-testing-2018-01-29-1733-luminous](https://trello.com/c/Hi2l9Gd8/246-wip-yuri2-testing-2018-01-29-1733-luminous)

**Pull request merged**
