### PR TITLE
doc/cephadm: index.rst: s/suites/suits/ typo fixed.

### PR DESCRIPTION
**Pull request by zdover23**
This commit changes the sentence "Choose the method that best suites
your needs." to "Choose the method that best suits your needs."

Fixes: https://tracker.ceph.com/issues/46359
Signed-off-by: Zac Dover <zac.dover@gmail.com>

## Checklist
- [x] References tracker ticket
- [x] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by tchaikov** [comment]
```
Value of: src_bl.contents_equal(dst_bl)
  Actual: false
Expected: true
[  FAILED  ] TestMigration.StressLive (7363 ms)
...
The following tests FAILED:
	  7 - run-rbd-unit-tests-0.sh (Failed)
```

**Comment by tchaikov** [comment]
@zdover23 would be ideal if you could remove the empty line before your Signed-off-by line in your commit message.

**Comment by tchaikov** [comment]
jenkins test make check

**Comment by tchaikov** [comment]
jenkins test dashboard backend

**Comment by zdover23** [comment]
> @zdover23 would be ideal if you could remove the empty line before your Signed-off-by line in your commit message.

Done. I couldn't remember off the top of my head if there should be line there or not. I guess I guessed wrong. Good lookin' out, kefu.

**Pull request merged**
