### PR TITLE
librbd: avoid "add_blocker" more than once when iops_limit and bps_limit set simultaneously

### PR DESCRIPTION
**Pull request by junxfl**

### CODE REVIEW

**Comment by junxfl** [comment]
Can you take a look at it for me sometime？ many thanks. @dillaman  @yangdongsheng

**Comment by dillaman** [comment]
@junxfl It is failing a couple unit tests now [1]:

TestMockIoImageRequestWQ.BPSQosNoBurst
TestMockIoImageRequestWQ.BPSQosWithBurst

[1] https://jenkins.ceph.com/job/ceph-pull-requests-arm64/30617/console

**Comment by dillaman** [comment]
@yangdongsheng Good point, yes, we would want to avoid incurring an additional delay of being placed at the back of the line after the first throttle completes.

**Comment by junxfl** [comment]
Sorry, I don't quite understand， if BPS and iops set simultaneously，some request 
`handle_throttle_ready` will be called twice,  "this->requeue(item)" will be executed twice, when _void_dequeue executed,  same request  will be  issued two times,  When  this request  executed the second time, librbd appear segment fault.

**Comment by junxfl** [comment]
please help to take a look, many thanks. @yangdongsheng

**Comment by yangdongsheng** [comment]
@junxfl  Did you try it and get segment fault? we will not requeue it twice, we only requeue it when item->were_all_throttled(), that means we will requeue item at the last flag throttled.

BTW, I did a test as below:
```
# ./bin/rbd bench --io-type read test --io-size 1 --io-threads 1 
bench  type read io_size 1 io_threads 1 bytes 1073741824 pattern sequential
  SEC       OPS   OPS/SEC   BYTES/SEC
    1        13     14.00     14.00
    2        23     12.00     12.00
    3        33     11.33     11.33
    4        43     11.00     11.00
    5        53     10.80     10.80
    6        62      9.98      9.98
    7        72      9.98      9.98
    8        82      9.98      9.98
    9        92      9.98      9.98
^C
# ./bin/rbd image-meta list test
There are 2 metadata on this image:

Key                          Value 
conf_rbd_qos_read_bps_limit  40960 
conf_rbd_qos_read_iops_limit 10  
```

**Comment by yangdongsheng** [comment]
@junxfl Please refer to https://github.com/ceph/ceph/pull/26688. there is a bug in were_all_throttled(). Sorry about it.

**Comment by dillaman** [comment]
Closing to PR #26688

**Pull request closed without merging**
