### PR TITLE
24778 dashboard info cards refactor

### PR DESCRIPTION
**Pull request by alfonsomthd**

### CODE REVIEW

**Comment by ricardoasmarques** [comment]
@alfonsomthd instead of creating the `24778-dashboard-info-cards-refactor` branch directly on `ceph/ceph` repository, it's recommended to user your own repository fork to submit this PR from `alfonsomthd/ceph:24778-dashboard-info-cards-refactor` instead of `ceph/ceph:24778-dashboard-info-cards-refactor`.

**Comment by alfonsomthd** [comment]
Ok I'll submit a PR from fork branch.

**Comment by ricardoasmarques** [comment]
@alfonsomthd you should also:

- Provide a description for your PR
- If your PR fixes an issue, your should add the following to your commit message (before the "Signed-off-by" line) - `Fixes: https://tracker.ceph.com/issues/24778`

**Comment by ricardoasmarques** [comment]
Replaced by https://github.com/ceph/ceph/pull/22902

**Pull request closed without merging**
