### PR TITLE
jewel: Proxied operations shouldn't result in error messages if replayed

### PR DESCRIPTION
**Pull request by dachary**
http://tracker.ceph.com/issues/17481

### CODE REVIEW

**Comment by dachary** [comment]
jenkins test this please (unittest_bluefs core)

**Comment by dachary** [comment]
jenkins test this please (timeout ? killed ?)

**Comment by dachary** [comment]
@dillaman does this backport look good to merge ? It passed the rbd suite http://tracker.ceph.com/issues/17487#note-17 (except for two dead nbd jobs)

**Comment by dillaman** [comment]
👍

**Pull request merged**
