### PR TITLE
mgr/dashboard: commands to set SSL certificate and key

### PR DESCRIPTION
**Pull request by rjfd**
Adds two new commands to ceph-dashboard to set the SSL certificate and key:
* `ceph dashboard set-ssl-certificate [mgr_id] -i <cert_filename>`
* `ceph dashboard set-ssl-certificate-key [mgr_id] -i <key_filename>`

Fixes: https://tracker.ceph.com/issues/39123
Signed-off-by: Ricardo Dias <rdias@suse.com>

- [x] References tracker ticket
- [x] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by jmolmo** [comment]
@rjfd ... i didn't know that mgr modules cannot read files. ... that change things ...

**Comment by jmolmo** [comment]
Just checked that is possible to read files, maybe you can use ceph config settings passing the path to the certificate/key files. . Is just a suggestion. :-)

**Comment by rjfd** [comment]
> Just checked that is possible to read files, maybe you can use ceph config settings passing the path to the certificate/key files. . Is just a suggestion. :-)

The problem is not that the mgr is not capable of reading files. The mgr can read files if they are stored in the same host where the mgr instance is running.

Imagine the case where you have an administration node where you have your certificate files, and the mgr instance is running in a different node.
It should be possible to still set the certificate by issuing a ceph CLI command from the administration node.
That's why we use the "-i" option so that instead of just using the file path it actually sends the content of the file to the mgr instance.

The problem is that the "-i" option is not available when using the "ceph config set" interface, and that's why we are adding these two commands.

**Comment by rjfd** [comment]
jenkins retest this please

**Comment by rjfd** [comment]
jenkins test dashboard

**Comment by rjfd** [comment]
jenkins test dashboard

**Comment by rjfd** [comment]
> Is there a test for this?

Not really. Unit test is hard in this case as the CLICommands are functions of the Module class, which cannot be used in unit tests. And I'm not sure how to test SSL certificates within our teuthology tasks.

**Comment by sebastian-philipp** [comment]
This also affects restful: https://tracker.ceph.com/issues/40013

**Comment by rjfd** [comment]
@ricardoasmarques done

**Comment by ricardoasmarques** [comment]
jenkins retest this please

**Comment by ricardoasmarques** [comment]
jenkins test make check arm64

**Pull request merged**
