### PR TITLE
os/bluestore: alter the allow_eio policy regarding kernel's error list.

### PR DESCRIPTION
**Pull request by rzarzynski**

### CODE REVIEW

**Comment by liewegas** [comment]
I wonder if it makes sense to log a message with the kernel-level error code, but translate them all to EIO for the upper layers?

**Comment by tchaikov** [comment]
retest this please.

**Comment by tchaikov** [comment]
- http://pulpito.ceph.com/kchai-2018-04-11_11:18:50-rados-wip-kefu-testing-2018-04-11-1705-distro-basic-mira/
- http://pulpito.ceph.com/kchai-2018-04-10_16:21:36-rados-wip-kefu-testing-2018-04-10-2058-distro-basic-mira/

**Comment by tchaikov** [comment]
@liewegas @rzarzynski i think this change should be backported to luminous. correct me if i am wrong.

**Pull request merged**
