### PR TITLE
ceph-disk/test: fix test_prepare.py::TestPrepare tests

### PR DESCRIPTION
**Pull request by tchaikov**
Signed-off-by: Kefu Chai <kchai@redhat.com>

### CODE REVIEW

**Comment by dachary** [comment]
<pre>
Reviewed-by: Loic Dachary &lt;ldachary@redhat.com>
</pre>

**Comment by tchaikov** [comment]
the failure is 
```
tests/ceph-disk.sh:136: command_fixture:  '[' /home/jenkins-build/build/workspace/ceph-pull-requests/src/ceph-conf = /home/jenkins-build/build/workspace/ceph-pull-requests/src/ceph-disk/ceph-conf ']'
```

it is spotted in my local env, but i thought it was due to the way i started the test. but seem it's not. will look into it later.

**Comment by tchaikov** [comment]
thanks for your quick review @dachary =)

**Comment by tchaikov** [comment]
@dachary fixed in #7554. and happy lunar new year!

**Pull request merged**
