### PR TITLE
quincy: cephfs-top, mgr/stats: multiple file system support with UI

### PR DESCRIPTION
**Pull request by neesingh-rh**
backport tracker: https://tracker.ceph.com/issues/57278, https://tracker.ceph.com/issues/57276 and https://tracker.ceph.com/issues/57330, https://tracker.ceph.com/issues/57273, https://tracker.ceph.com/issues/57283

---

backport of https://github.com/ceph/ceph/pull/46068, https://github.com/ceph/ceph/pull/47079, https://github.com/ceph/ceph/pull/46072
parent tracker: https://tracker.ceph.com/issues/56162, https://tracker.ceph.com/issues/56169 and https://tracker.ceph.com/issues/55861, https://tracker.ceph.com/issues/56483, https://tracker.ceph.com/issues/54978

this backport was staged using ceph-backport.sh version 16.0.0.6848
find the latest version at https://github.com/ceph/ceph/blob/master/src/script/ceph-backport.sh

### CODE REVIEW

**Review by anthonyeleven — APPROVED** [review]
Docs lgtm

**Review by kotreshhr — APPROVED** [review]

**Review by joscollin — CHANGES_REQUESTED** [review]
Please drop the commit titled `mgr/stats: Fixing DeprecationWarning for RegEx`, as it's not associated with any tracker issue. Otherwise, this backport looks good.

**Comment by vshankar** [comment]
@neesingh-rh I see this is marked as `needs-qa`, however, I wanted to check if we there are related backport PRs that depend on this. It's probably better to test those dependent PRs with this.

**Comment by neesingh-rh** [comment]
> @neesingh-rh I see this is marked as `needs-qa`, however, I wanted to check if we there are related backport PRs that depend on this. It's probably better to test those dependent PRs with this.

I guess https://tracker.ceph.com/issues/57283 and https://tracker.ceph.com/issues/57273 needs to be tested along with this.But PR for the former one is yet to be opened.

**Comment by vshankar** [comment]
> > @neesingh-rh I see this is marked as `needs-qa`, however, I wanted to check if we there are related backport PRs that depend on this. It's probably better to test those dependent PRs with this.
> 
> I guess https://tracker.ceph.com/issues/57283 and https://tracker.ceph.com/issues/57273 needs to be tested along with this.But PR for the former one is yet to be opened.

Let's remove `needs-qa` tag and add it back when we have the backports. BTW, mind having a single backport for the dependent PRs?

**Comment by neesingh-rh** [comment]
> > > @neesingh-rh I see this is marked as `needs-qa`, however, I wanted to check if we there are related backport PRs that depend on this. It's probably better to test those dependent PRs with this.
> > 
> > 
> > I guess https://tracker.ceph.com/issues/57283 and https://tracker.ceph.com/issues/57273 needs to be tested along with this.But PR for the former one is yet to be opened.
> 
> Let's remove `needs-qa` tag and add it back when we have the backports. BTW, mind having a single backport for the dependent PRs?

Okay , I will add the commits of the Backports for https://tracker.ceph.com/issues/57283 and https://tracker.ceph.com/issues/57273 in this PR.Makes sense?

**Comment by vshankar** [comment]
> > > > @neesingh-rh I see this is marked as `needs-qa`, however, I wanted to check if we there are related backport PRs that depend on this. It's probably better to test those dependent PRs with this.
> > > 
> > > 
> > > I guess https://tracker.ceph.com/issues/57283 and https://tracker.ceph.com/issues/57273 needs to be tested along with this.But PR for the former one is yet to be opened.
> > 
> > 
> > Let's remove `needs-qa` tag and add it back when we have the backports. BTW, mind having a single backport for the dependent PRs?
> 
> @vshankar Okay , I will add the commits of the Backports for https://tracker.ceph.com/issues/57283 and https://tracker.ceph.com/issues/57273 in this PR.Makes sense? EDIT: Or we can merge commits for https://tracker.ceph.com/issues/57273 in this PR and handle the add filesystem menu https://tracker.ceph.com/issues/57283 backport PR separately after the merge of this PR.

I'm fine with having a single PR with all changes since those are dependent changes for the feature.

**Comment by neesingh-rh** [comment]
@vshankar Have merged the commits of all quincy backports related to mgr/stats and cephfs-top.

**Review by anthonyeleven — APPROVED** [review]
Docs lgtm

**Comment by vshankar** [comment]
This needs rebase after backport PR https://github.com/ceph/ceph/pull/47977 get merged.

**Comment by neesingh-rh** [comment]
Rebased!!

**Comment by vshankar** [comment]
Ready for QA.

**Comment by ljflores** [comment]
Rados suite review: http://pulpito.front.sepia.ceph.com/?branch=wip-yuri6-testing-2022-09-23-1008-quincy

Failures, unrelated:
    1. https://tracker.ceph.com/issues/57386
    2. https://tracker.ceph.com/issues/57311
    3. https://tracker.ceph.com/issues/56951
    4. https://tracker.ceph.com/issues/57165 -- pending Quincy backport

Details:
    1. cephadm/test_dashboard_e2e.sh: Expected to find content: '/^foo$/' within the selector: 'cd-modal .badge' but never did - Ceph - Mgr - Dashboard
    2. rook: ensure CRDs are installed first - Ceph - Orchestrator
    3. ook/smoke: Updating cephclusters/rook-ceph is forbidden - Ceph - Orchestrator
    4. expected valgrind issues and found none - Ceph - RADOS

**Review by vshankar — APPROVED** [review]

**Pull request merged**
