### PR TITLE
octopus: mgr/dashboard: Disabling the form inputs for the read_only modals

### PR DESCRIPTION
**Pull request by nizamial09-zz**
backport tracker: https://tracker.ceph.com/issues/47539

## Checklist
- [x] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Review by smithfarm — CHANGES_REQUESTED** [review]
Please read https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst and follow it for a smoother backporting experience.

Please append a conflicts section to the commit message. It should be at the very end of the commit message and should look like this:

```
Conflicts:
        src/pybind/mgr/dashboard/frontend/src/app/shared/directives/directives.module.ts
- <optional_description_of_the_conflict_and/or_how_it_was_resolved>
```

**Comment by nizamial09** [comment]
Updated the Conflicts section in commit message. @smithfarm

**Comment by smithfarm** [comment]
```
141/196 Test  #14: smoke.sh ................................***Failed  345.17 sec
```

looks unrelated

**Comment by smithfarm** [comment]
jenkins test make check

**Comment by alfonsomthd** [comment]
jenkins test api

**Review by alfonsomthd — APPROVED** [review]

**Review by callithea — APPROVED** [review]
lgtm, thank you!

**Review by s0nea — APPROVED** [review]
LGTM! :+1:

**Pull request merged**
