### PR TITLE
Revert "mon, cephfs: Add auth caps for CephFS fsids"

### PR DESCRIPTION
**Pull request by tchaikov**
Reverts ceph/ceph#32581

### CODE REVIEW

**Comment by tchaikov** [comment]
for testing https://tracker.ceph.com/issues/47423

**Comment by tchaikov** [comment]
https://pulpito.ceph.com/kchai-2020-09-12_13:41:38-rados-wip-kefu-testing-2020-09-12-2016-distro-basic-smithi

i suspect that it is #32581 which broke `test_cluster_set_reset_user_config` in `tasks.cephfs.test_nfs.TestNFS)`

**Comment by ajarr** [comment]
https://tracker.ceph.com/issues/47423#note-3

**Comment by varshar16** [comment]
By reverting, nfs tests pass: http://qa-proxy.ceph.com/teuthology/kchai-2020-09-12_13:41:38-rados-wip-kefu-testing-2020-09-12-2016-distro-basic-smithi/5428301/teuthology.log

**Comment by neha-ojha** [comment]
> https://pulpito.ceph.com/kchai-2020-09-12_13:41:38-rados-wip-kefu-testing-2020-09-12-2016-distro-basic-smithi
> 
> i suspect that it is #32581 which broke `test_cluster_set_reset_user_config` in `tasks.cephfs.test_nfs.TestNFS)`

It is also causing https://tracker.ceph.com/issues/47444, tests pass with this revert https://pulpito.ceph.com/nojha-2020-09-14_18:32:02-rados-wip-kefu-testing-2020-09-12-2016-distro-basic-smithi/

**Review by sebastian-philipp — APPROVED** [review]

**Comment by neha-ojha** [comment]
> > https://pulpito.ceph.com/kchai-2020-09-12_13:41:38-rados-wip-kefu-testing-2020-09-12-2016-distro-basic-smithi
> > i suspect that it is #32581 which broke `test_cluster_set_reset_user_config` in `tasks.cephfs.test_nfs.TestNFS)`
> 
> It is also causing https://tracker.ceph.com/issues/47444, tests pass with this revert https://pulpito.ceph.com/nojha-2020-09-14_18:32:02-rados-wip-kefu-testing-2020-09-12-2016-distro-basic-smithi/

Another one https://tracker.ceph.com/issues/47447

**Review by neha-ojha — COMMENTED** [review]
@rishabh-d-dave Do we think we can resolve the following bugs soon enough? else I am fine going ahead with the revert.

- https://tracker.ceph.com/issues/47444 - @batrick has a fix for this
- https://tracker.ceph.com/issues/47423 
- https://tracker.ceph.com/issues/47447

**Comment by rishabh-d-dave** [comment]
@neha-ojha 
> Do we think we can resolve the following bugs soon enough? else I am fine going ahead with the revert.

I am fairly positive that this can be done in a short amount of time.

PR #37159 should fix tracker #47447. I wrote the same fix for ceph API tests before)

Tracker #47423 needs a bit more investigation. The issue lies around here[[1]](https://github.com/ceph/ceph/blob/master/src/mon/MonCap.cc#L198) and here[[2]](https://github.com/ceph/ceph/blob/master/src/mon/MonCap.h#L204). I've figured out that at [2] `mask` is 4 and `g.allow.val` is 0 which means mgr can't write despite of [1]. The bug fix should be short for this one too.

**Comment by rishabh-d-dave** [comment]
@neha-ojha @batrick 

Raised #37190 for ticket #47423.

**Pull request closed without merging**
