### PR TITLE
client: fix incorrectly showing the .snap size for stat

### PR DESCRIPTION
**Pull request by lxbsz**
We should set the 'stat->size' to the real number of snapshots for
snapdirs.

Fixes: https://tracker.ceph.com/issues/57344
Signed-off-by: Xiubo Li <xiubli@redhat.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Review by batrick — APPROVED** [review]
Normally we'd expose this kind of information using `.nlinks` but technically the immediate subdirectories' `..` link points to its real immediate parent, not the fake `.snap` folder.

We already abuse `st_size` with `client_dirsize_rbytes` so I suppose this is fine. Does the kernel client have the this behavior? If not, it should?

**Comment by lxbsz** [comment]
> Normally we'd expose this kind of information using `.nlinks` but technically the immediate subdirectories' `..` link points to its real immediate parent, not the fake `.snap` folder.
> 
> We already abuse `st_size` with `client_dirsize_rbytes` so I suppose this is fine. Does the kernel client have the this behavior? If not, it should?

Yeah, the kclient also the same and I have fixed it too and the patches is under reviewing.
Thanks @batrick

**Review by vshankar — APPROVED** [review]

**Comment by lxbsz** [comment]
> > Normally we'd expose this kind of information using `.nlinks` but technically the immediate subdirectories' `..` link points to its real immediate parent, not the fake `.snap` folder.
> > We already abuse `st_size` with `client_dirsize_rbytes` so I suppose this is fine. Does the kernel client have the this behavior? If not, it should?
> 
> Yeah, the kclient also the same and I have fixed it too and the patches is under reviewing. Thanks @batrick

The kclient patch is here: https://patchwork.kernel.org/project/ceph-devel/patch/20220914030940.61357-1-xiubli@redhat.com/. And the corresponding tracker is https://tracker.ceph.com/issues/57342.

**Review by rishabh-d-dave — APPROVED** [review]
https://tracker.ceph.com/projects/cephfs/wiki/Main

**Comment by vshankar** [comment]
> https://tracker.ceph.com/projects/cephfs/wiki/Main

You'd need to point to the permalink of the run log in the wiki :)

https://tracker.ceph.com/projects/cephfs/wiki/Main#2022-Sep-29

**Pull request merged**
