### PR TITLE
nautilus: os/bluestore: shallow fsck mode and legacy statfs auto repair.

### PR DESCRIPTION
**Pull request by ifed01**
Backports following PRs:  
https://github.com/ceph/ceph/pull/30264
https://github.com/ceph/ceph/pull/30616
https://github.com/ceph/ceph/pull/30350
and single commit - https://github.com/ceph/ceph/pull/29292/commits/dee8f8cb7e906596693f8c6e22ff74f815169c87 - from https://github.com/ceph/ceph/pull/29292

Signed-off-by: Igor Fedotov <ifedotov@suse.com>

### CODE REVIEW

**Comment by yuriw** [comment]
@ifed01 needs rebase

--- pr 30685 --- pulling https://github.com/ifed01/ceph.git branch wip-ifed-fast-fsck-nau
remote: Enumerating objects: 103, done.
remote: Counting objects: 100% (103/103), done.
remote: Total 118 (delta 103), reused 103 (delta 103), pack-reused 15
Receiving objects: 100% (118/118), 28.47 KiB | 14.23 MiB/s, done.
Resolving deltas: 100% (103/103), completed with 17 local objects.
From https://github.com/ifed01/ceph
 * branch                  wip-ifed-fast-fsck-nau -> FETCH_HEAD
Auto-merging src/test/objectstore/store_test.cc
Auto-merging src/os/bluestore/bluestore_tool.cc
CONFLICT (content): Merge conflict in src/os/bluestore/bluestore_tool.cc
Auto-merging src/os/bluestore/BlueStore.h
CONFLICT (content): Merge conflict in src/os/bluestore/BlueStore.h
Auto-merging src/os/bluestore/BlueStore.cc
Auto-merging src/os/ObjectStore.h
Auto-merging src/common/options.cc
Auto-merging src/common/legacy_config_opts.h
Auto-merging PendingReleaseNotes
Automatic merge failed; fix conflicts and then commit the result.
Traceback (most recent call last):
  File "/home/yuriw/wip_master/src/script/build-integration-branch", line 67, in <module>
    assert not r
AssertionError

**Comment by smithfarm** [comment]
@ifed01 Conflicts with https://github.com/ceph/ceph/pull/29949 - that PR takes precedence because it's older.

**Comment by ifed01** [comment]
> @ifed01 Conflicts with #29949 - that PR takes precedence because it's older.

@smithfarm - so what should I do - rebase on top of 29949 or wait until it's merged?

**Comment by smithfarm** [comment]
@ifed01 You could do either, but waiting for #29949 to be merged might be the easier route.

**Comment by ifed01** [comment]
rebase done

**Comment by yuriw** [comment]
[wip-yuri3-testing-2019-11-18-2140-nautilus](https://trello.com/c/Ij7gxvpz/768-wip-yuri3-testing-2019-11-18-2140-nautilus)

**Pull request merged**
