### PR TITLE
fix PG::all_unfound_are_queried_or_lost for non-existent osds

### PR DESCRIPTION
**Pull request by xinxinsh**
http://tracker.ceph.com/issues/10976

### CODE REVIEW

**Comment by dachary** [comment]
@xinxinsh  could you please explain how the conflict was resolved for e111c96 ? There are explanations about that at http://tracker.ceph.com/projects/ceph-releases/wiki/HOWTO_backport_commits, including a oneliner that can conveniently be used to display the difference between the original commit and the backported commit that required resolution

**Comment by xinxinsh** [comment]
updated

**Comment by dachary** [comment]
@xinxinsh great, will be helpful to @trociny when reviewing :-)

**Comment by trociny** [comment]
The conflict resolution (replace $TEST_POOL with data pool) looks ok to me. Other looks good too.

You might consider though if 7294e8c is going to be backported too in near future, and if it is, then it may be better to do it the first, to avoid double conflict.

Also, actually, taking into the consideration the current state of test_lost.sh and that is not integrated to 'make check', I hardly expect somebody to run these tests on firefly. So we may consider backporting only the fix (883f87f), without the supplementary tests.

**Comment by xinxinsh** [comment]
@trociny @dachary updated

**Comment by trociny** [comment]
It looks ok to me.

**Comment by dachary** [comment]
@athanatos does this backport look good to merge ? It passed a run of the firefly rados suite ( see http://tracker.ceph.com/issues/11090#rados for details ). There was only one failure described at http://tracker.ceph.com/issues/11142#note-5

**Pull request merged**
