### PR TITLE
doc: 16.2.7 Release Notes - picked to pacific

### PR DESCRIPTION
**Pull request by zdover23**
This is a commit that cherry picks the 16.2.7 release
notes from the master branch to the pacific branch.

Signed-off-by: Zac Dover <zac.dover@gmail.com>

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [x] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [x] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by zdover23** [comment]
> copying static files... done
> copying extra files... done
> dumping search index in English (code: en)... done
> dumping object inventory... done
> build finished with problems, 15 warnings.
> + succeed=false
> + false
> + cat /home/jenkins-build/build/workspace/ceph-pr-docs/build-doc-VO8.out
> + github-check --sphinx --sphinx-root=. --owner ceph --repo ceph --pkey-file **** --app-id 62865 --install-id 8465036 --name ceph-pr-docs --sha cd3e7e3db315bc6fa083adf9060b34ce9774f1da --external-id 59447 --details-url https://jenkins.ceph.com/job/ceph-pr-docs/59447/ --title sphinx-build
> + false
> Build step 'Execute shell' marked build as failure
> [Checks API] No suitable checks publisher found.
> Setting status of cd3e7e3db315bc6fa083adf9060b34ce9774f1da to FAILURE with url https://jenkins.ceph.com/job/ceph-pr-docs/59447/ and message: 'Docs: failed with errors
>  '
> Using context: Docs: build check
> Finished: FAILURE

@jdurgin What gives?

**Comment by jdurgin** [comment]
```
/home/jenkins-build/build/workspace/ceph-pr-docs/doc/releases/index.rst:43: WARNING: Error in "ceph_timeline" directive:
12 argument(s) required, 7 supplied.

.. ceph_timeline:: releases.yml dev pacific octopus nautilus mimic luminous
```
This can be fixed by changing this 12 to 7: https://github.com/ceph/ceph/blob/pacific/doc/_ext/ceph_releases.py#L108

It's not pretty, but that's how the table is built today.

The formatting looks a little off around 'pacific' and '16.2.7' in the table here: https://ceph--44716.org.readthedocs.build/en/44716/releases/general/#active-stable-releases

**Comment by zdover23** [comment]
> ```
> /home/jenkins-build/build/workspace/ceph-pr-docs/doc/releases/index.rst:43: WARNING: Error in "ceph_timeline" directive:
> 12 argument(s) required, 7 supplied.
> 
> .. ceph_timeline:: releases.yml dev pacific octopus nautilus mimic luminous
> ```
> 
> This can be fixed by changing this 12 to 7: https://github.com/ceph/ceph/blob/pacific/doc/_ext/ceph_releases.py#L108
> 
> It's not pretty, but that's how the table is built today.
> 
> The formatting looks a little off around 'pacific' and '16.2.7' in the table here: https://ceph--44716.org.readthedocs.build/en/44716/releases/general/#active-stable-releases

Roger this, Josh.

I'm going to wait for our meeting in five hours to step through this with you, so that I can continue this project of mapping this minefield.

**Comment by zdover23** [comment]
> > ```
> > /home/jenkins-build/build/workspace/ceph-pr-docs/doc/releases/index.rst:43: WARNING: Error in "ceph_timeline" directive:
> > 12 argument(s) required, 7 supplied.
> > 
> > .. ceph_timeline:: releases.yml dev pacific octopus nautilus mimic luminous
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This can be fixed by changing this 12 to 7: https://github.com/ceph/ceph/blob/pacific/doc/_ext/ceph_releases.py#L108
> > It's not pretty, but that's how the table is built today.
> > The formatting looks a little off around 'pacific' and '16.2.7' in the table here: https://ceph--44716.org.readthedocs.build/en/44716/releases/general/#active-stable-releases
> 
> Roger this, Josh.
> 
> I'm going to wait for our meeting in five hours to step through this with you, so that I can continue this project of mapping this minefield.

There is some deeper problem with the formatting of that table that has eluded me for the past few days.

Changing the 12 to the 7 in ceph_releases.py fixes the build error.

I will continue to document my difficulties with the formatting of that table.

**Pull request closed without merging**
