### PR TITLE
quincy: mgr/dashboard: BDD approach for the dashboard cephadm e2e

### PR DESCRIPTION
**Pull request by nizamial09**
backport tracker: https://tracker.ceph.com/issues/54624
backport tracker: https://tracker.ceph.com/issues/56035, https://tracker.ceph.com/issues/55452

---

backport of https://github.com/ceph/ceph/pull/44835
parent tracker: https://tracker.ceph.com/issues/54224, https://tracker.ceph.com/issues/55741, https://tracker.ceph.com/issues/55247

this backport was staged using ceph-backport.sh version 16.0.0.6848
find the latest version at https://github.com/ceph/ceph/blob/main/src/script/ceph-backport.sh

### CODE REVIEW

**Comment by nizamial09** [comment]
shaman packages - [ongoing](https://shaman.ceph.com/builds/ceph/wip-nia-testing-2022-06-14-2219/)

**Review by aaSharma14 — APPROVED** [review]

**Review by Sarthak0702 — APPROVED** [review]

**Comment by nizamial09** [comment]
jenkins test api

**Comment by nizamial09** [comment]
jenkins test dashboard

**Comment by nizamial09** [comment]
jenkins test dashboard

**Pull request merged**
