### PR TITLE
PGLog::proc_replica_log: correctly handle case where entries between olog.head and log.tail were split out

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/12389

### CODE REVIEW

**Comment by smithfarm** [comment]
@athanatos This has passed a rados suite (see http://tracker.ceph.com/issues/11644#rados for details). OK to merge, do you think?

**Comment by smithfarm** [comment]
@dachary Seeing as Sam is out, could you take a look?

**Comment by dachary** [comment]
<pre>
diff -u --ignore-matching-lines '^[^+-]' <(git show fdff8ce) <(git show b61e5ae) 
</pre>
shows nothing, hence the tests that triggered the conflict were solely in the context and no test were accidentally removed.

**Comment by dachary** [comment]
@smithfarm this looks sensible. It is however a delicate part of the code and I would prefer @athanatos to confirm that backporting this as far back as firefly in this way is enough.

**Comment by smithfarm** [comment]
@dachary OK, marking DNM until @athanatos can look at it.

**Comment by athanatos** [comment]
Good to go if it passed tests!

**Comment by smithfarm** [comment]
Thanks! We'll put it through another round of tests and merge if those go well.

**Comment by dachary** [comment]
@liewegas does this backport look good to merge ? It passed a run of the firefly rados suite ( see http://tracker.ceph.com/issues/11644#note-110 ). Note that there was a valgrind issues but it is unrelated and fixed by https://github.com/ceph/ceph/pull/6325.

**Comment by liewegas** [comment]
Looks ok to me, but I think this one should wait for @athanatos to return and comment.

**Comment by athanatos** [comment]
Looks good to me as well.

**Pull request merged**
