### PR TITLE
qa/cephadm: sudo_write_file doesn't support unicode

### PR DESCRIPTION
**Pull request by sebastian-philipp**
76524358594a00ef2e7a1acf4e186aae9d39d4d8 was a python 2 fix that was necessary to make octopus compatible to teuthology:py2. Now, let's forward-port this commit to keep both branches aligned. 

Signed-off-by: Sebastian Wagner <sebastian.wagner@suse.com>

(cherry picked from commit 76524358594a00ef2e7a1acf4e186aae9d39d4d8)

Conflicts:
	qa/tasks/cephadm.py

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by sebastian-philipp** [comment]
http://pulpito.ceph.com/swagner-2020-06-02_12:46:10-rados:cephadm-wip-swagner3-testing-2020-06-02-1145-distro-basic-smithi/

**Comment by tchaikov** [comment]
i don't understand why master needs to be py2 compatible.

**Comment by kshtsk** [comment]
> i don't understand why master needs to be py2 compatible.

the only case is to make it easy to back port stuff from master to octopus until octopus switched to py3 only teuthology?

**Comment by tchaikov** [comment]
i disagree. this change literally defeat the whole purpose of using python3.6 features on master and to drop python2 support on master.

**Comment by kshtsk** [comment]
> i disagree. this change literally defeats the whole purpose of using python3.6 features on master and to drop python2 support on master. please note, it has taken me more than 3 months to prepare the backport of nautilus. not sure about octopus. and we switched to python3 because i really wanted the master to use python3 sooner.

I don't understand why you disagree, since py2 compatibility does not mean py3 incompatibility, I was not saying it is NECESSARY, I'm just saying about probably advantage, from my point of view it could be useful to have the same code base, so you don't need to merged next fixes which require back ports. You experience could be different.

So, I am okay either merging it, or not merging it :-)

**Comment by tchaikov** [comment]
we discussed the plan 3 months ago. if i had more bandwidth, i'd started removing all the trace of python2 in master now.  but i've been busy with nautilus backport.

**probably** "useful", but unnecessary complicated, and error prone.

**Comment by kshtsk** [comment]
> we discussed the plan 3 months ago. if i had more bandwidth, i'd started removing all the trace of python2 in master now. but i've been busy with nautilus backport.
> 
> **probably** "useful", but unnecessary complicated, and error prone.

I agree with that, I don't want to interfere that job at all, all I want to say is to making branches py3 compatible is higher priority than getting rid of py2 traces, and we need focus on that, if small py2 compatibility code can help to reach that goal I'm fine with that.

**Comment by kshtsk** [comment]
@sebastian-philipp what do you think? ready to close this PR?

**Comment by kshtsk** [comment]
Also, the title of the PR `qa/cephadm: sudo_write_file doesn't support unicode` does not make sense at all in the context of py3 code, sine *sudo_write_file* supports unicode as far str in py3 are unicode, so it can misguide people, to be accurate you would name this as `teuthology sudo_write_file does not support py2 unicode type`

**Comment by tchaikov** [comment]
> > we discussed the plan 3 months ago. if i had more bandwidth, i'd started removing all the trace of python2 in master now. but i've been busy with nautilus backport.
> > **probably** "useful", but unnecessary complicated, and error prone.
> 
> I agree with that, I don't want to interfere that job at all, all I want to say is to making branches py3 compatible is higher priority than getting rid of py2 traces, and we need focus on that, if small py2 compatibility code can help to reach that goal I'm fine with that.

i think i am the only one working on it now. i am not interested in being reminded that "we need foo or bar".

and again, my next step is to remove py2 stuff. i want to make the job easier if i could. i cannot see how backport py2 change to master can help me.

**Comment by sebastian-philipp** [comment]
> and again, my next step is to remove py2 stuff. i want to make the job easier if i could. i cannot see how backport py2 change to master can help me.

why that? why making it harder for me to backport things to octopus?

**Comment by kshtsk** [comment]
> > > we discussed the plan 3 months ago. if i had more bandwidth, i'd started removing all the trace of python2 in master now. but i've been busy with nautilus backport.
> > > **probably** "useful", but unnecessary complicated, and error prone.
> > 
> > 
> > I agree with that, I don't want to interfere that job at all, all I want to say is to making branches py3 compatible is higher priority than getting rid of py2 traces, and we need focus on that, if small py2 compatibility code can help to reach that goal I'm fine with that.
> 
> i think i am the only one working on it now. i am not interested in being reminded that "we need foo or bar".

that was mostly self-reminder for me, and note for those who wish to help with py3, please, don't be offended...

> and again, my next step is to remove py2 stuff. i want to make the job easier if i could. i cannot see how backport py2 change to master can help me.

I see

**Comment by sebastian-philipp** [comment]
ok folks. I'll leave it up to you to merge or close this PR. I'd be in favor of merging it, as it reduces the delta between master and octopus and helps keeping octopus move towards py3, but that#s just me.

**Comment by sebastian-philipp** [comment]
superseded by #35408

**Comment by tchaikov** [comment]
> > and again, my next step is to remove py2 stuff. i want to make the job easier if i could. i cannot see how backport py2 change to master can help me.
> 
> why that? why making it harder for me to backport things to octopus?

@sebastian-philipp with all due respect, if you think my work makes your life hard. i will stop.

**Comment by tchaikov** [comment]
but please note, i repeated my plan was to port all py3 changes to octopus couple times in both sepia and ceph-devel mailing list. i think i've beeing trying my best to unblock you. if you think otherwise, i have no idea how i can help.

**Comment by sebastian-philipp** [comment]
@tchaikov I'm super sorry for the comment above! Wasn't meant to be harsh. I'm super glad you're helping me to sort things out!

**Comment by sebastian-philipp** [comment]
Thing was: if I want to port things from master to octopus, having fewer differences between those branches might be helpful.

**Pull request closed without merging**
