### PR TITLE
messages: define HEAD_VERSION and COMPAT_VERSION inlined

### PR DESCRIPTION
**Pull request by tchaikov**
otherwise we could have ../lib/libceph-common.so.0: undefined reference
to `MOSDPGNotify::HEAD_VERSION

when the compiler tries to be smart and pass them by reference.

Signed-off-by: Kefu Chai <kchai@redhat.com>

- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by tchaikov** [comment]
@xuxuehan

**Comment by wjwithagen** [comment]
@tchaikov 
Clangs does not seem to be happy about this:
```
/home/jenkins/workspace/ceph-master/src/messages/MClientCaps.h:30:3: error: non-static data member cannot be constexpr; did you intend to make it static?
  constexpr unsigned FLAG_SYNC          = (1<<0);
  ^
  static
/home/jenkins/workspace/ceph-master/src/messages/MClientCaps.h:31:3: error: non-static data member cannot be constexpr; did you intend to make it static?
  constexpr unsigned FLAG_NO_CAPSNAP            = (1<<1); // unused
  ^
  static
/home/jenkins/workspace/ceph-master/src/messages/MClientCaps.h:32:3: error: non-static data member cannot be constexpr; did you intend to make it static?
  constexpr unsigned FLAG_PENDING_CAPSNAP       = (1<<2);
  ^
  static
3 errors generated.
```
But then still the first PR, had the exact issues as you but in the description.

**Comment by tchaikov** [comment]
@wjwithagen the FTBFS in your comment should be addressed by the latest changeset.

**Comment by wjwithagen** [comment]
@tchaikov 
Ah, oke, will try again.
You fixed, while I was testing ;-)

**Comment by xxhdx1985126** [comment]
retest this, please.

**Comment by wjwithagen** [comment]
@tchaikov 
I'm sort of lost....

Really still no go with Clang.
code contains:
```
class MOSDScrub2 : public MessageInstance<MOSDScrub2> {
public:
  friend factory;

  static constexpr int HEAD_VERSION = 1;
  static constexpr int COMPAT_VERSION = 1;
```

But the jenkins run of that still complains:
```
[ 49%] Linking CXX executable ../../bin/unittest_subprocess
cd /home/jenkins/workspace/ceph-master/build/src/test && /usr/local/bin/cmake -E cmake_link_script CMakeFiles/unittest_subprocess.dir/link.txt --verbose=1
ccache /usr/bin/c++   -Wall -Wtype-limits -Wignored-qualifiers -Winit-self -Wpointer-arith -Werror=format-security -fno-strict-aliasing -fsigned-char -Wno-unknown-pragmas -Wno-unused-function -Wno-unused-local-typedef -Wno-varargs -Wno-gnu-designator -Wno-missing-braces -Wno-parentheses -Wno-deprecated-register  -ftemplate-depth-1024 -Wnon-virtual-dtor -Wno-unknown-pragmas -Wno-ignored-qualifiers -Wno-inconsistent-missing-override -Wno-mismatched-tags -Wno-unused-private-field -Wno-address-of-packed-member -fdiagnostics-color=auto -fno-builtin-malloc -fno-builtin-calloc -fno-builtin-realloc -fno-builtin-free  -O0 -g -Wno-unused-command-line-argument -DBEAST_NO_BOOST_STRING_VIEW  -Wl,--export-dynamic CMakeFiles/unittest_subprocess.dir/test_subprocess.cc.o  -o ../../bin/unittest_subprocess  -L/usr/local/lib -Wl,-rpath,/usr/local/lib:/home/jenkins/workspace/ceph-master/build/lib:/usr/local/lib/nss ../../lib/libgmock_main.a ../../lib/libgmock.a ../../lib/libgtest.a -lpthread ../../lib/libglobal.a ../../lib/libceph-common.so.0 ../../lib/libjson_spirit.a ../../lib/libcommon_utf8.a ../../lib/liberasure_code.a ../../lib/libcrc32.a ../../lib/libarch.a /usr/local/lib/libboost_thread.so /usr/local/lib/libboost_chrono.so /usr/local/lib/libboost_atomic.so /usr/local/lib/libboost_random.so /usr/local/lib/libboost_system.so /usr/local/lib/libboost_program_options.so /usr/local/lib/libboost_date_time.so /usr/local/lib/libboost_iostreams.so /usr/local/lib/libboost_regex.so /usr/lib/libexecinfo.so /usr/local/lib/nss/libssl3.so /usr/local/lib/nss/libsmime3.so /usr/local/lib/nss/libnss3.so /usr/local/lib/nss/libnssutil3.so /usr/local/lib/libplds4.so /usr/local/lib/libplc4.so /usr/local/lib/libnspr4.so /usr/local/lib/libssl.so /usr/local/lib/libcrypto.so -lpthread -lrt 
../../lib/libceph-common.so.0: undefined reference to `MOSDRepScrubMap::HEAD_VERSION'
../../lib/libceph-common.so.0: undefined reference to `MOSDRepScrubMap::COMPAT_VERSION'
c++: error: linker command failed with exit code 1 (use -v to see invocation)
gmake[2]: *** [src/test/CMakeFiles/unittest_subprocess.dir/build.make:113: bin/unittest_subprocess] Error 1
```

**Comment by wjwithagen** [comment]
@tchaikov 
Ignore that, manual build after the failure did work.
First it linked shared lib libceph-common.so, and then unittest_subprocess.
And that had no error.
So, retesting

**Comment by gregsfortytwo** [comment]
Not that I object to use of constexpr instead of const, but what could possibly have made the compiler try to pass it by reference? *confused*

**Comment by tchaikov** [comment]
https://shaman.ceph.com/builds/ceph/wip-kefu-testing-2018-08-17-2127/22b5c586465691d0e918d8ca84374c5296838687/

that's interesting and confusing. i haven't gotten a chance to look at the `Messege::ref` change closely. will leave it as a homework for this week-end. let's fix the FTBFS first.

**Comment by ukernel** [comment]
```
#include <list>
  
struct A {
        A(int a) {}
};

struct B {
        static const int V = 1;
        std::list<A> l;
        void foo() {
                l.emplace_back(V);
        }
};

int main(int argc, char *argv[])
{
        B b;
        b.foo();
}
```

**Pull request merged**
