### PR TITLE
mon: node ls improvement

### PR DESCRIPTION
**Pull request by guzhongyan**
output mon/mds name instead of their rank

Signed-off-by: Gu Zhongyan <guzhongyan@360.cn>

### CODE REVIEW

**Comment by guzhongyan** [comment]
daemon name could be more useful than rank, detailed discussion here:
https://github.com/ceph/ceph/pull/20711#discussion_r172198385

**Comment by guzhongyan** [comment]
@jcsp @tchaikov  take a look?

**Comment by jcsp** [comment]
retest this please (jenkins)

**Comment by tchaikov** [comment]
- http://pulpito.ceph.com/kchai-2018-04-01_23:31:58-rados-wip-kefu-testing-2018-04-02-0027-distro-basic-smithi/
- http://pulpito.ceph.com/kchai-2018-04-02_08:26:07-rados-wip-kefu-testing-2018-04-02-0027-distro-basic-mira/

**Pull request merged**
