### PR TITLE
mimic: osd: Better error message when OSD count is less than osd_pool_default_size

### PR DESCRIPTION
**Pull request by smithfarm**
NOTE: I intentionally omitted 0483c1c3e7ffdfa6a6f65c5ef000c45d2f096428 because there is no `qa/tasks/ceph.conf.template` in mimic. As noted below, in mimic the template file in the teuthology repo is used. Therefore, this PR has a companion PR in teuthology.

backport tracker: https://tracker.ceph.com/issues/40083
companion teuthology PR: https://github.com/ceph/teuthology/pull/1308

---

backport of https://github.com/ceph/ceph/pull/27806
parent tracker: https://tracker.ceph.com/issues/38617

this backport was staged using https://github.com/ceph/ceph/blob/master/src/script/ceph-backport.sh

### CODE REVIEW

**Comment by neha-ojha** [comment]
@smithfarm 1ab352dd3105d320bd7ad2c0b37e5de750879dd5 added qa/tasks/ceph.conf.template, before that we've been using teuthology/ceph.conf.template in teuthology.git, I think we can just add it there.

**Comment by smithfarm** [comment]
Also, build failure:

```
/home/jenkins-build/build/workspace/ceph-pull-requests/src/mon/PGMap.cc: In member function 'void PGMap::get_health_checks(CephContext*, const OSDMap&, health_check_map_t*) const':
/home/jenkins-build/build/workspace/ceph-pull-requests/src/mon/PGMap.cc:2573:39: error: request for member 'get_val' in 'cct->CephContext::_conf', which is of pointer type 'md_config_t*' (maybe you meant to use '->' ?)
   auto warn_too_few_osds = cct->_conf.get_val<bool>("mon_warn_on_too_few_osds");
                                       ^~~~~~~
/home/jenkins-build/build/workspace/ceph-pull-requests/src/mon/PGMap.cc:2573:47: error: expected primary-expression before 'bool'
   auto warn_too_few_osds = cct->_conf.get_val<bool>("mon_warn_on_too_few_osds");
                                               ^~~~
/home/jenkins-build/build/workspace/ceph-pull-requests/src/mon/PGMap.cc:2574:43: error: request for member 'get_val' in 'cct->CephContext::_conf', which is of pointer type 'md_config_t*' (maybe you meant to use '->' ?)
   auto osd_pool_default_size = cct->_conf.get_val<uint64_t>("osd_pool_default_size");
                                           ^~~~~~~
/home/jenkins-build/build/workspace/ceph-pull-requests/src/mon/PGMap.cc:2574:59: error: expected primary-expression before '>' token
   auto osd_pool_default_size = cct->_conf.get_val<uint64_t>("osd_pool_default_size");
                                                           ^
src/CMakeFiles/common-objs.dir/build.make:713: recipe for target 'src/CMakeFiles/common-objs.dir/mon/PGMap.cc.o' failed
make[3]: *** [src/CMakeFiles/common-objs.dir/mon/PGMap.cc.o] Error 1
```

**Comment by smithfarm** [comment]
@neha-ojha I opened https://github.com/ceph/teuthology/pull/1308 to go with this.

**Comment by smithfarm** [comment]
@neha-ojha @tchaikov Please take another look - I cherry-picked dcdca44aa45e and cdba0f14201a327e824b6ec48e014233281dee2d

**Comment by smithfarm** [comment]
see also luminous backport PR https://github.com/ceph/ceph/pull/30298

**Comment by yuriw** [comment]
[wip-yuri3-testing-2019-09-30-1547](https://trello.com/c/YpGnOoKt/699-wip-yuri3-testing-2019-09-30-1547)

**Pull request merged**
