### PR TITLE
blk/aio: allocate iocb using small_vector

### PR DESCRIPTION
**Pull request by tchaikov**
there is chance that the batch size is so large that we have stack
overflow when allocating piocb array using VLA. in this change,
piocb is allocated using small_vector<>, as in most circumstances, the
size of an object is 4M when it comes to CephFS, RGW and RBD by default.
so if the client sends 4K / 8K aligned read / write, in general,
that would be translated into 1024 IO requests at most. so,
use 1024 as the size of small_vector would suffice.

also, 1024 is the default bdev_aio_max_queue_depth by default, hence
this setting is able to feed a io_submit() batch.

Fixes: https://tracker.ceph.com/issues/46366
Signed-off-by: Kefu Chai <kchai@redhat.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by tchaikov** [comment]
changelog

- fixed the syntax error in the comment.

**Comment by wvh-github** [comment]
@tchaikov Thanks for the patch.

It looks like the tests are failing because of unavailable space in the jenkins test system. Other tests are also failing because of this:

`/home/jenkins-build/build/workspace/ceph-dashboard-pr-backend/build/bin/ceph-mon -i a -c /home/jenkins-build/build/workspace/ceph-dashboard-pr-backend/build/ceph.conf 
2020-07-07T06:31:40.457+0000 7fbc9729f700 -1 error: monitor data filesystem reached concerning levels of available storage space (available: 3% 14 GiB)
you may adjust 'mon data avail crit' to a lower value to make this go away (default: 5%)`

**Comment by tchaikov** [comment]
@wvh-github hi Wout, thanks for looking into these test failures. yeah, i am contacting our lab administrator to fix this. we've been suffering from this from almost two weeks.

**Comment by RobinGeuze** [comment]
Hey, I don't think this patch will solve the segfaults. I replaced the pciob value with a malloc/free combination and the process would still segfault, and occasionally assert on the assert after the loop comparing left and aios_size.

**Comment by tchaikov** [comment]
@RobinGeuze could you enable debug-osd=20, and debug-bluestore=20, and paste the log to https://tracker.ceph.com/issues/46366 and answer the query of https://tracker.ceph.com/issues/46366#note-6 ? i am also interested in the workload.

**Comment by RobinGeuze** [comment]
@tchaikov I want to get our system back to full stability before I start fiddling with debug settings again. We run RBD using 4+2 erasure code and we use a separate data pool. Maybe to give a bit of context:
- We had a quite catastrophic cluster failure, caused by improperly following the upgrade guide for Nautilus (we found this out eventually)
- In the process of trying to fix this we upgraded to octopus
- Once we finally had all OSD's back online after fixing the nautilus upgrade issue we reenabled recovery. At this point the cluster was paused.
- About 10-15 OSD's started crashing with the segfault this bug report is about.
- We took out this OSD's and manually moved inactive PG's of them to other OSD's. This seemed to fix it for a while.
- After about 4-6 hours or so other OSD's started crashing though.

At this point we tried a bunch of different patches. I attached GDB but I could get very little useful info. This let me to use malloc for allocation piocb, which allowed me to get the proper stacktrace shared in the bug report. Eventually based on that stack trace a colleague of mine noted https://github.com/ceph/ceph/commit/74be30c8b7c. We then tested a build with that patch revert, which solved the crashes and our cluster is now running properly on that patched binary. I only reverted that one single patch.

**Comment by tchaikov** [comment]
@RobinGeuze thanks for your detailed explanation!

so the number of iocb should have been much less than "118712", which was found in the backtrace you uploaded in the ticket, as a 4M RBD object being recovered should not have so many fragments.

**Comment by RobinGeuze** [comment]
@tchaikov yes I think the list being handed into submit_batch is corrupt, which just caused the loop to go on endlessly. In all dumps I made aios_size was larger than left, which means that KernelDevice::aio_submit somehow took more elements from IOContext::pending_aios than the value of IOContext::num_pending, which, as far as I can tell, should not be possible. Hence my theory the list is somehow corrupted.

**Comment by wvh-github** [comment]
@tchaikov the logs of a crashing OSD can be found at:

- https://robing-disk.stackstorage.com/s/eEM0xaCuF6MBdkqg
- https://robing-disk.stackstorage.com/s/KfFPQpAfrOgiCLF9

I'm also wondering if you can confirm the concern of @RobinGeuze regarding this patch in relation to the problems we saw this weekend.

**Comment by ideepika** [comment]
http://pulpito.ceph.com/ideepika-2020-07-07_12:58:57-rados-wip-deepika-testing-2020-06-25-2058-distro-basic-smithi/
http://pulpito.front.sepia.ceph.com/ideepika-2020-07-08_07:00:35-rados-wip-deepika-testing-2020-06-25-2058-distro-basic-smithi/

failures tracked by:
https://tracker.ceph.com/issues/44399
https://tracker.ceph.com/issues/46412

**Comment by tchaikov** [comment]
@wvh-github thank you, Wout! i am still downloading the log files. will start with the smaller one.. not sure if i can finish downloading the larger one in my lifetime though...

**Comment by wvh-github** [comment]
> @wvh-github thank you, Wout! i am still downloading the log files. will start with the smaller one.. not sure if i can finish downloading the larger one in my lifetime though...
Thanks for the update, I'm not sure the larger one will provide more insights compared to the smaller one.

Is there some other place I can upload it so you can grab it faster?

**Comment by wvh-github** [comment]
> @wvh-github thank you, Wout! i am still downloading the log files. will start with the smaller one.. not sure if i can finish downloading the larger one in my lifetime though...

Hi @tchaikov ,

I was wondering if you have had a chance to go over the logs. If so, have you been able to confirm the bug @RobinGeuze has described?

**Comment by wvh-github** [comment]
Hi @tchaikov

Have you been able to look into Robins comment?

> @tchaikov yes I think the list being handed into submit_batch is corrupt, which just caused the loop to go on endlessly. In all dumps I made aios_size was smaller than left, which means that KernelDevice::aio_submit somehow took more elements from IOContext::pending_aios than the value of IOContext::num_pending, which, as far as I can tell, should not be possible. Hence my theory the list is somehow corrupted.

**Comment by wido** [comment]
This PR says it fixes: https://tracker.ceph.com/issues/46366

However, seeing the comment from Robin it doesn't seem to be the case. Something else seems to be the root cause of the issue above.

@xiexingguo can you comment on this and mainly on the issue linked in the start of this PR?

**Review by xiexingguo — CHANGES_REQUESTED** [review]
@wido I withdraw my approval as the root cause is still not clear to me

**Pull request closed without merging**
