### PR TITLE
mgr/dashboard: Add hosts page unit tests

### PR DESCRIPTION
**Pull request by votdev**
Fixes: https://tracker.ceph.com/issues/46448

Signed-off-by: Volker Theile <vtheile@suse.com>

## Checklist
- [x] References tracker ticket
- [ ] Updates documentation if necessary
- [x] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by votdev** [comment]
jenkins retest this please

**Comment by votdev** [comment]
jenkins retest this please

**Comment by votdev** [comment]
jenkins test dashboard backend

**Comment by votdev** [comment]
jenkins test dashboard

**Comment by votdev** [comment]
jenkins test dashboard backend

**Comment by votdev** [comment]
jenkins test dashboard

**Comment by votdev** [comment]
jenkins retest this please

**Comment by bk201** [comment]
The changes in my pending PR test some combination on hosts, do you think they also cover changes in this PR?
https://github.com/ceph/ceph/pull/34918/files#diff-4d5797fcf6a01fcd8ac340a51194fdf7R134

**Comment by votdev** [comment]
jenkins test dashboard

**Pull request merged**
