### PR TITLE
hammer: objects unfound after repair (fixed by repeering the pg)

### PR DESCRIPTION
**Pull request by dzafman**
Backport pull request #4269
Backport pull request #4487 (reverted a commit from #4269)

http://tracker.ceph.com/issues/15002

### CODE REVIEW

**Comment by dzafman** [comment]
@athanatos This includes the test case that runs during make check.

**Comment by dachary** [comment]
Trying to reproduce an error that always shows in the integration branch

<pre>
2016-04-04T08:02:41.777 INFO:tasks.lost_unfound.ceph_manager:recovered!
2016-04-04T08:02:41.777 INFO:tasks.util.rados:rados -p unfound_pool get new_1 -
2016-04-04T08:02:41.778 INFO:teuthology.orchestra.run.target167114252015:Running: 'adjust-ulimits ceph-coverage /home/ubuntu/cephtest/archive/coverage rados -p unfound_pool get new_1 -'
2016-04-04T08:02:41.826 INFO:teuthology.orchestra.run.target167114252015.stderr:error getting unfound_pool/new_1: (2) No such file or directory
2016-04-04T08:02:41.829 INFO:tasks.util.rados:rados -p unfound_pool get existed_1 -
2016-04-04T08:02:41.829 INFO:teuthology.orchestra.run.target167114252015:Running: 'adjust-ulimits ceph-coverage /home/ubuntu/cephtest/archive/coverage rados -p unfound_pool get existed_1 -'
2016-04-04T08:02:41.873 INFO:teuthology.orchestra.run.target167114252015.stderr:error getting unfound_pool/existed_1: (2) No such file or directory
2016-04-04T08:02:41.886 INFO:tasks.util.rados:rados -p unfound_pool get existing_1 -
2016-04-04T08:02:41.886 INFO:teuthology.orchestra.run.target167114252015:Running: 'adjust-ulimits ceph-coverage /home/ubuntu/cephtest/archive/coverage rados -p unfound_pool get existing_1 -'
2016-04-04T08:02:41.935 INFO:teuthology.orchestra.run.target167114252015.stderr:error getting unfound_pool/existing_1: (5) Input/output error
2016-04-04T08:02:41.937 ERROR:teuthology.run_tasks:Saw exception from tasks.
Traceback (most recent call last):
  File "/home/ubuntu/teuthology/teuthology/run_tasks.py", line 66, in run_tasks
    manager = run_one_task(taskname, ctx=ctx, config=config)
  File "/home/ubuntu/teuthology/teuthology/run_tasks.py", line 45, in run_one_task
    return fn(**kwargs)
  File "/home/ubuntu/src/ceph-qa-suite_hammer/tasks/lost_unfound.py", line 151, in task
    assert not err
AssertionError
</pre>

<code>ceph-workbench --verbose ceph-qa-suite --suite rados --ceph-git-url http://github.com/dachary/ceph --ceph wip-15002 --ceph-qa-suite-git-url http://github.com/ceph/ceph-qa-suite --suite-branch hammer --filter='rados/singleton/{all/lost-unfound.yaml fs/btrfs.yaml msgr-failures/many.yaml}'</code>

* *running*

**Comment by dachary** [comment]
Maybe the error is because xfs is used instead of btrfs in master ( https://github.com/ceph/ceph-qa-suite/commit/7e0fb5dd617c2f87ef4bc952f7f5a26b4205db85 ). The lost-unfound task does not seem otherwise modified to handle EIO

**Comment by dachary** [comment]
The same job passes jewel and has not been modified between hammer and jewel.

**Comment by dachary** [comment]
@dzafman I assume something changed in how jewel handles this situation and the EIO never shows in the test. But in hammer it always does. Marking this pull request as DNM until we have a better understanding of what is going on.

**Comment by dzafman** [comment]
@dachary ok

**Comment by dachary** [comment]
it looks like this backport is responsible for the errors listed at http://tracker.ceph.com/issues/15300, namely
<pre>
2016-04-03T23:14:34.423 INFO:tasks.rados.rados.0.target167114243099.stdout:3455: done (15 left)
2016-04-03T23:14:34.423 INFO:tasks.rados.rados.0.target167114243099.stdout:3456: delete oid 7 current snap is 357
2016-04-03T23:14:34.577 INFO:tasks.rados.rados.0.target167114243099.stderr:err -5
2016-04-03T23:14:34.580 INFO:tasks.rados.rados.0.target167114243099.stderr:./test/osd/RadosModel.h: In function 'virtual void SetAttrsOp::_finish(TestOp::CallbackInfo*)' thread 7fdc3bfff700 time 2016-04-03 23:14:34.562701
2016-04-03T23:14:34.581 INFO:tasks.rados.rados.0.target167114243099.stderr:./test/osd/RadosModel.h: 687: FAILED assert(0)
2016-04-03T23:14:34.581 INFO:tasks.rados.rados.0.target167114243099.stderr: ceph version 0.94.6-259-g8cc324d (8cc324df4caf0d043208d9abe88a0e217e861dc3)
2016-04-03T23:14:34.581 INFO:tasks.rados.rados.0.target167114243099.stderr: 1: (ceph::__ceph_assert_fail(char const*, char const*, int, char const*)+0x8b) [0x4e101b]
2016-04-03T23:14:34.581 INFO:tasks.rados.rados.0.target167114243099.stderr: 2: (SetAttrsOp::_finish(TestOp::CallbackInfo*)+0x218) [0x4c7f88]
2016-04-03T23:14:34.581 INFO:tasks.rados.rados.0.target167114243099.stderr: 3: (write_callback(void*, void*)+0x19) [0x4d8619]
2016-04-03T23:14:34.581 INFO:tasks.rados.rados.0.target167114243099.stderr: 4: (()+0x950ed) [0x7fdc54d9d0ed]
2016-04-03T23:14:34.581 INFO:tasks.rados.rados.0.target167114243099.stderr: 5: (()+0x70439) [0x7fdc54d78439]
2016-04-03T23:14:34.582 INFO:tasks.rados.rados.0.target167114243099.stderr: 6: (()+0x134438) [0x7fdc54e3c438]
2016-04-03T23:14:34.582 INFO:tasks.rados.rados.0.target167114243099.stderr: 7: (()+0x8182) [0x7fdc548dc182]
2016-04-03T23:14:34.582 INFO:tasks.rados.rados.0.target167114243099.stderr: 8: (clone()+0x6d) [0x7fdc5326147d]
2016-04-03T23:14:34.582 INFO:tasks.rados.rados.0.target167114243099.stderr: NOTE: a copy of the executable, or `objdump -rdS <executable>` is needed to interpret this.
2016-04-03T23:14:34.583 INFO:tasks.rados.rados.0.target167114243099.stderr:terminate called after throwing an instance of 'ceph::FailedAssertion'
2016-04-03T23:14:34.850 ERROR:teuthology.run_tasks:Manager failed: rados
Traceback (most recent call last):
  File "/home/ubuntu/teuthology/teuthology/run_tasks.py", line 139, in run_tasks
    suppress = manager.__exit__(*exc_info)
  File "/usr/lib/python2.7/contextlib.py", line 24, in __exit__
    self.gen.next()
  File "/home/ubuntu/src/ceph-qa-suite_hammer/tasks/rados.py", line 196, in task
    running.get()
  File "/home/ubuntu/teuthology/virtualenv/local/lib/python2.7/site-packages/gevent/greenlet.py", line 274, in get
    raise self._exception
CommandCrashedError: Command crashed: 'CEPH_CLIENT_ID=0 adjust-ulimits ceph-coverage /home/ubuntu/cephtest/archive/coverage ceph_test_rados --ec-pool --op read 100 --op write 0 --op delete 50 --max-ops 4000 --objects 50 --max-in-flight 16 --size 4000000 --min-stride-size 400000 --max-stride-size 800000 --max-seconds 0 --op snap_create 50 --op snap_remove 50 --op rollback 50 --op setattr 25 --op rmattr 25 --op copy_from 50 --op append 100 --pool unique_pool_0'
2016-04-03T23:14:34.850 DEBUG:teuthology.run_tasks:Unwinding manager thrashosds
</pre>
and similar. Multiple rados run without this pull request does not exhibit this error once.

**Comment by dzafman** [comment]
@dachary I found a revert that should solve the EIO errors because it removed a problem commit from the pull request #4269

**Comment by athanatos** [comment]
@dzafman I don't want to include the commit and the revert, remove them.

**Comment by athanatos** [comment]
@dzafman Given the ease of the workaround, I'm not really convinced that we want to backport this at all.  Thoughts?

**Comment by dzafman** [comment]
@athanatos The reasoning behind including the commit and the revert is to mirror the master branch and make it clear that the entire pull request was backported.

I'm not against keeping this pull request especially because it is non-conflicting and includes a test case.

**Comment by athanatos** [comment]
@dzafman Normally I'd agree with mirroring master branch, but that commit/revert pair merely introduces and fixes a bug, I don't think it's a good idea to intentionally backport the broken commit, someone might see it in hammer and fail to notice the revert.

**Comment by dzafman** [comment]
@athanatos Removed the commit and the revert.

**Comment by dzafman** [comment]
Rados run passed with 1 unrelated failure: http://pulpito.ceph.com/dzafman-2016-07-21_13:18:50-rados-wip-zafman-testing-hammer---basic-smithi/

**Comment by smithfarm** [comment]
@athanatos: I had been having some trouble with the `hammer-backports` testing runs - see http://tracker.ceph.com/issues/15895 for details - so @dzafman took matters into his own hands ;-)

Do you think this hammer backport is good to merge?

**Comment by smithfarm** [comment]
@athanatos This PR is in the latest round of hammer-backports integration tests, which passed a rados run (the only failures are a valgrind false positive that has since been fixed by https://github.com/ceph/teuthology/pull/915 and http://tracker.ceph.com/issues/15139 which is an infrastructure issue with two of the tests) - for details, see: http://tracker.ceph.com/issues/15895#note-18

Do you think this PR is OK to merge?

**Comment by athanatos** [comment]
/2000 is too few tests for hammer, I'd be more comfortable with /200.  That said, the centos run looks ok, I'd like to see the ubuntu failures analyzed before passing final judgement.  If @dzafman is ok with it, I'm ok with it.

**Comment by smithfarm** [comment]
@athanatos Ubuntu /200 run is green IMO - analyzed in http://tracker.ceph.com/issues/15895#note-18

**Comment by athanatos** [comment]
@smithfarm Ok, I'm ok with it if @dzafman is.

**Comment by dzafman** [comment]
👍

**Pull request merged**
