### PR TITLE
os/bluestore: fix wakeup bug

### PR DESCRIPTION
**Pull request by majianpeng**
## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by majianpeng** [comment]
retest this please

**Comment by majianpeng** [comment]
retest this please

**Comment by majianpeng** [comment]
@ifed01, please review this . thanks

**Comment by tchaikov** [comment]
jenkins test make check

**Comment by majianpeng** [comment]
retest this please

**Comment by majianpeng** [comment]
retest this please

**Comment by tchaikov** [comment]
http://pulpito.ceph.com/kchai-2019-12-09_12:39:45-rados-wip-kefu-testing-2019-12-09-1434-distro-basic-smithi/

failure tracked / fixed by
- https://tracker.ceph.com/issues/43192
- https://tracker.ceph.com/issues/42764
- https://tracker.ceph.com/issues/43070
- #32143

**Pull request merged**
