### PR TITLE
WIP/rgw: MDLog over FIFO 

### PR DESCRIPTION
**Pull request by arjune123**
This PR is a work on #37251 for adding MDLog support over FIFO in rgw.

Fixes: https://tracker.ceph.com/issues/55184
Signed-off-by: Arjun Sharma <arjsharm@redhat.com>

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [x] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [x] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [x] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by soumyakoduri** [comment]
@arjune123 .. please open a tracker (https://tracker.ceph.com/issues) as new feature for this PR and update the checklist in the PR description.  I will look into rebase build errors and update

**Comment by arjune123** [comment]
fixes https://tracker.ceph.com/issues/55184?next_issue_id=55183

**Comment by soumyakoduri** [comment]
@arjune123 .. I think the rebase was not done properly.. I see even few files missing in this commit when compared to https://github.com/ceph/ceph/pull/37251/files# (eg., cls_fifo_legacy.cc/h). 

Also IMO, it may not be good to squash entire commit history as we may loose the context & description of all the changes for any future reference. I tried to quickly rebase old PR ( https://github.com/ceph/ceph/pull/37251/commits ) to latest master.. Most of the errors seem to be related to only 'dpp' changes. So it should be easy to resolve each commit & proceed (though time taking :( ).. let me know if it gets really difficult. I will try to update https://github.com/ceph/ceph/pull/37251 to latest master and then you can take it forward..

**Comment by adamemerson** [comment]
> Also IMO, it may not be good to squash entire commit history as we may loose the context & description of all the changes for any future reference. I tried to quickly rebase old PR ( https://github.com/ceph/ceph/pull/37251/commits ) to latest master.. Most of the errors seem to be related to only 'dpp' changes. So it should be easy to resolve each commit & proceed (though time taking :( ).. let me know if it gets really difficult. I will try to update #37251 to latest master and then you can take it forward..

When I'm rebasing, I like to use the `--exec` option. (e.g. `--exec 'cd build && make -jwhatever'`) that way rebase itself will catch any conflicts and the compilation will catch any errors that show up, and I don't have to be manually involved except on things that require intervention.

**Comment by adamemerson** [comment]
I think we can close this since we decided not to pursue FIFO MDlog due to the need to copy the log between zones and the problem of cursor stability.

**Comment by cbodley** [comment]
agreed. thanks @soumyakoduri @arjune123 for investigating this

**Pull request closed without merging**
