### PR TITLE
build/ops: rpm: move RDMA and python-prettytables build dependencies to distro-conditional section

### PR DESCRIPTION
**Pull request by smithfarm**
SUSE ships this package under the name "rdma-core-devel". See
https://build.opensuse.org/package/view_file/openSUSE:Factory/rdma-core/rdma-core.spec?expand=1

Signed-off-by: Nathan Cutler <ncutler@suse.com>

### CODE REVIEW

**Comment by smithfarm** [comment]
This one is only needed for luminous.

**Comment by ktdreyer** [comment]
LGTM, want to edit the PR title to reflect the two changes?

**Comment by smithfarm** [comment]
@ktdreyer thanks; done

**Comment by ktdreyer** [comment]
Thanks!

**Comment by smithfarm** [comment]
https://shaman.ceph.com/builds/ceph/wip-rdma-devel/

**Comment by smithfarm** [comment]
also testing in OBS

**Comment by tchaikov** [comment]
@smithfarm please feel free to merge it once it builds in OBS also.

**Pull request merged**
