### PR TITLE
RBD:  fix an issue of too slow to remove an empty volume

### PR DESCRIPTION
**Pull request by mxdInspur**
RBD: it is too slow to delete an big empty volume (TB)

Signed-off-by: muxiangdong muxiangdong@inspur.com

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test docs`
- `jenkins render docs`

</details>

### CODE REVIEW

**Comment by mxdInspur** [comment]
BUG #41229

**Comment by trociny** [comment]
@mxdInspur I am not sure I understand what exactly problem you are trying to fix with your patch.

I just checked `rbd remove` on master and can admit that there is the issue with slow remove here (and I believe in nautilus). But the problem that I see is that at the moment when `TrimRequest` is executed the `image_ctx.exclusive_lock` is null (and so is `object_map`). And as the result we don't use the object map. But your fix looks like `object_map` was successfully loaded in your case so may be you are observing a  different issue? At what version did you try this?

@dillaman As for the issue with not initialized exclusive lock at the moment when `TrimRequest` is executed, I believe it was introduced in #25438. After moving the image to trash, it calls `Trash::remove` with force flag set. As a result the `RemoveRequest` is also called with force flag and the exclusive lock is shut down in this case (I suppose to avoid potential issues). Previously the `force` option was passed by param to `Image::Remove` and the default was false. Now it is hard coded to true.

**Comment by mxdInspur** [comment]
@trociny hi, I did the experiment on the version of 14.2.1(nautilus,stable). The feature of object-map was enabled.

**Comment by trociny** [comment]
So, do you observe a difference (and how large) with your patch applied? Because according to my experiments with `rbd remove`, at the moment when `TrimRequest<I>::send_remove_objects()` is called, the `image_ctx.object_map` is always null (even if you use object map feature), due to the problem I described above. So I don't see how your code is called in this case.

**Comment by dillaman** [comment]
> Now it is hard coded to true.

I think we would want force to first try it w/ the exclusive lock and if acquiring it fails, fall back to the current path where is just ignores it (and therefore object map).

**Comment by trociny** [comment]
> I think we would want force to first try it w/ the exclusive lock and if acquiring it fails, fall back to the current path where is just ignores it (and therefore object map).

Good idea!

@mxdInspur If you agree that the issue you are observing is due the problem I described, do you wish to work on the fix as suggested by Jason? The necessary changes we are talking about are for `librbd/image/PreRemoveRequest.cc`. Or I can do this.

**Comment by mxdInspur** [comment]
> > I think we would want force to first try it w/ the exclusive lock and if acquiring it fails, fall back to the current path where is just ignores it (and therefore object map).
> 
> Good idea!
> 
> @mxdInspur If you agree that the issue you are observing is due the problem I described, do you wish to work on the fix as suggested by Jason? The necessary changes we are talking about are for `librbd/image/PreRemoveRequest.cc`. Or I can do this.

@trociny thanks for your suggestion, i will try to fix this issue as soon as possible，thanks again

**Comment by trociny** [comment]
@mxdInspur Do you have any difficulties with fixing this? If you do please ask any questions I will be glad to help. The regression is serious and I would really like to see the fix in the next nautilus version. Unfortunately we don't have much time as it is planned to be released by the end of the August.

**Comment by mxdInspur** [comment]
> @mxdInspur Do you have any difficulties with fixing this? If you do please ask any questions I will be glad to help. The regression is serious and I would really like to see the fix in the next nautilus version. Unfortunately we don't have much time as it is planned to be released by the end of the August.

@trociny I review the file librbd/image/PreRemoveRequest.cc as suggested and do not get the point. I think the issue is different from the one you talked about. The issue happened because sending the request of removing objects to RADOS  always happend one by one, according to the num of objects in the volume, regardless of whether the volume is empty. So in order to reducing unnecessary time consumption, i try to check the object-map(the feature of obmap should be enabled) whether the object exists firstly, instead of sending request to RADOS.

**Comment by trociny** [comment]
>  So in order to reducing unnecessary time consumption, i try to check the object-map(the feature of obmap should be enabled) whether the object exists firstly, instead of sending request to RADOS.

The problem is that at the moment when you try to check the object-map, it is null, because the exclusive lock (and therefore the object map) is disabled by `PreRemoveRequest`.

Ok, to make it faster, don't you mind if me or Jason create a separate PR that fixes `PreRemoveRequest` as Jason suggested, and you could try it then?

BTW, a simple way to check if you are observing the issue we are talking about is to change force param from `true` to `false` here [1] and rebuild rbd.

[1] https://github.com/ceph/ceph/blob/master/src/librbd/api/Image.cc#L738

**Comment by trociny** [comment]
@mxdInspur I created a PR [1] that tries to avoid exclusive lock shut down on removal. Do you have a chance to try if it fixes your issue. In my tests the removal of an empty 1T image is fast again after applying that fix.

[1] https://github.com/ceph/ceph/pull/29775

**Comment by mxdInspur** [comment]
> @mxdInspur I created a PR [1] that tries to avoid exclusive lock shut down on removal. Do you have a chance to try if it fixes your issue. In my tests the removal of an empty 1T image is fast again after applying that fix.
> 
> [1] #29775

Sorry to inform you that my build environment has been released. If you can, can you provide your verification results, especially the time difference? Thanks

**Comment by trociny** [comment]
> would you mind providing your verification results, especially the time difference?
```
adonis:~/ceph/ceph.ci/build% rbd create -s 1T test1
adonis:~/ceph/ceph.ci/build% rbd create -s 1T test2
adonis:~/ceph/ceph.ci/build% time rbd rm test1
Removing image: 100% complete...done.
rbd rm test1  104.20s user 23.92s system 51% cpu 4:10.93 total
adonis:~/ceph/ceph.ci/build% time ~/ceph/ceph/build/bin/rbd rm test2
Removing image: 100% complete...done.
~/ceph/ceph/build/bin/rbd rm test2  3.25s user 0.06s system 93% cpu 3.548 total
```
I.e. removing a 1T image with a non-patched rbd took more than 4 minutes. Removing a 1T image with the patched rbd took less than 4 sec.

**Comment by mxdInspur** [comment]
> > would you mind providing your verification results, especially the time difference?
> 
> ```
> adonis:~/ceph/ceph.ci/build% rbd create -s 1T test1
> adonis:~/ceph/ceph.ci/build% rbd create -s 1T test2
> adonis:~/ceph/ceph.ci/build% time rbd rm test1
> Removing image: 100% complete...done.
> rbd rm test1  104.20s user 23.92s system 51% cpu 4:10.93 total
> adonis:~/ceph/ceph.ci/build% time ~/ceph/ceph/build/bin/rbd rm test2
> Removing image: 100% complete...done.
> ~/ceph/ceph/build/bin/rbd rm test2  3.25s user 0.06s system 93% cpu 3.548 total
> ```
> 
> I.e. removing a 1T empty image with a non-patched rbd took more than 4 minutes. Removing a 1T empty image with the patched rbd took less than 4 sec.

That is impressive, thanks

**Comment by dillaman** [comment]
Closing to alternate PR

**Comment by mxdInspur** [comment]
@dillaman @trociny can you add a test to remove a 200T empty image? Maybe it will take over 600 sec.

**Comment by dillaman** [comment]
@mxdInspur Feel free to submit a PR if you so choose

**Pull request closed without merging**
