### PR TITLE
mds: trigger stray reintegration when loading dentry

### PR DESCRIPTION
**Pull request by batrick**
## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [x] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by batrick** [comment]
jenkins test api

**Comment by batrick** [comment]
https://tracker.ceph.com/projects/cephfs/wiki/Master#2021-Dec-22

**Comment by batrick** [comment]
Good to merge with approval.

**Review by lxbsz — APPROVED** [review]
Test this locally and it worked well for me.
Also LGTM.

**Comment by hyb-g** [comment]
Hello, When I merge this commit, there is an assertion error on the MDS when multiple clients perform operations like creating files, creating hard links, and deleting files simultaneously in the same directory using a script. Have you encountered this issue during your testing? Below are the MDS logs and a reproducible script.

mds log:
-1> 2023-12-13 09:14:50.381167 7f10b0a35700 -1 /home/hyb/ceph_a100/ceph/rpmbuild/BUILD/ceph-14.2.19/src/mds/StrayManager.cc: In function 'void StrayManager::_eval_stray_remote(CDentry*, CDentry*)' thread 7f10b0a35700 time 2023-12-13 09:14:50.379378
/home/hyb/ceph_a100/ceph/rpmbuild/BUILD/ceph-14.2.19/src/mds/StrayManager.cc: 623: FAILED ceph_assert(stray_in->inode.nlink >= 1)
 ceph version 14.2.19-1320-g62f3a89d05 (62f3a89d052007052115dcc9e72b9c53d31f2f12) nautilus (stable)
 1: (ceph::__ceph_assert_fail(char const*, char const*, int, char const*)+0x156) [0x7f10bf5a43ea]
 2: (()+0x27e663) [0x7f10bf5a4663]
 3: (StrayManager::_eval_stray_remote(CDentry*, CDentry*)+0x91d) [0x5632bc04c55d]
 4: (StrayManager::eval_remote(CDentry*)+0x4ab) [0x5632bc04caeb]
 5: (Server::_link_local_finish(boost::intrusive_ptr<MDRequestImpl>&, CDentry*, CInode*, unsigned long, unsigned long, bool)+0x3f3) [0x5632bbf1fdd3]
 6: (C_MDS_link_local_finish::finish(int)+0x37) [0x5632bbf7a037]
 7: (MDSContext::complete(int)+0x142) [0x5632bc1922c2]
 8: (MDSIOContextBase::complete(int)+0x18f) [0x5632bc1924ef]
 9: (MDSLogContextBase::complete(int)+0x44) [0x5632bc1928f4]
 10: (Finisher::finisher_thread_entry()+0x17d) [0x7f10bf63a49d]
 11: (()+0x817a) [0x7f10bdf3a17a]
 12: (clone()+0x43) [0x7f10bd08bdf3]

**Comment by hyb-g** [comment]
reproducible script

import os
import sys
import subprocess
import random
import time
import datetime
from multiprocessing import Process
import multiprocessing as mp
def mount(mountpoint, num_clients, dir, fuse_processes):
    if not os.path.exists(mountpoint):
        os.makedirs(mountpoint)
    subprocess.run(['ceph-fuse', mountpoint])
    if not os.path.exists(dir):
        os.makedirs(dir)
    for i in range(num_clients):
        subprocess.run(['mkdir', f'{mountpoint}/dir{i}'], cwd=mountpoint)
    for i in range(num_clients):
        fuse_process = subprocess.Popen(['ceph-fuse', '-r', '/dir', f'{mountpoint}/dir{i}'])
        fuse_processes.append(fuse_process)
    time.sleep(10)
def kill_process(num_clients, fuse_processes):
    for process in processes:
        process.terminate()
    for process in fuse_processes:
        process.terminate()
    for i in range(num_clients):
        subprocess.Popen(['umount', '-lf', f'{mountpoint}/dir{i}'])
    subprocess.run(['umount', '-lf', mountpoint])
def check_cluster_health(last_check):
    try:
        output = subprocess.check_output("ceph -s", shell=True, stderr=subprocess.STDOUT,
                 universal_newlines=True)
        assert "HEALTH_OK" in output
        print("Cluster health check successful")
        return 0
    except subprocess.CalledProcessError as e:
        if last_check == False:
            print("Cluster health check failed")
            return -1
        else:
            print("Cluster health check failed")
            kill_process(num_clients, fuse_processes)
            os._exit(-1)
    except AssertionError:
        if last_check == False:
            print("Cluster health check failed")
            return -1
        else:
            print("Cluster health check failed")
            kill_process(num_clients, fuse_processes)
            os._exit(-1)
def client_operation(client_idx):
    client_dir = f'{mountpoint}/dir{client_idx}'
    while True:
        # create file
        if random.random() < 0.3:
            filename = f'{client_dir}/{random.randint(1, 5000)}.txt'
            try:
                with open(filename, 'w') as f:
                    f.write('Sample content')
            except Exception as e:
                pass
        # create link
        elif random.random() < 0.35:
            try:
                files = os.listdir(client_dir)
                if len(files) > 0:
                    file_to_link = random.choice(files)
                    path_to_link = f'{client_dir}/{file_to_link}'
                    if os.path.isfile(path_to_link):
                        link_destination = f'{client_dir}/{random.randint(1, 5000)}.link'
                        os.link(path_to_link, link_destination)
            except Exception as e:
                pass
        # delete file
        else:
            try:
                files = os.listdir(client_dir)
                if len(files) > 0:
                    file_to_delete = random.choice(files)
                    path_to_delete = f'{client_dir}/{file_to_delete}'
                    if os.path.exists(path_to_delete):
                        os.remove(path_to_delete)
            except Exception as e:
                pass
if __name__ == "__main__":
    mountpoint = '/mnt/fuse'
    num_clients = 20
    dir = '/mnt/fuse/dir/'
    fuse_processes = []
    mount(mountpoint, num_clients, dir, fuse_processes)
    processes = []
    for i in range(num_clients):
        process = mp.Process(target=client_operation, args=(i,))
        process.start()
        processes.append(process)
    process = mp.Process(target=check_cluster_health, args=(False,))
    process.start()
    processes.append(process)
    total_running_time = datetime.datetime.now() + datetime.timedelta(seconds=3600)
    current_time = datetime.datetime.now()
    while current_time < total_running_time:
        result = check_cluster_health(False)
        #if result == 0:
        #    time.sleep(10)
        #else:
            #break
        time.sleep(10)
        current_time = datetime.datetime.now()
    kill_process(num_clients, fuse_processes)
    check_cluster_health(True)

**Comment by hyb-g** [comment]
reproducible script

``
import os
import sys
import subprocess
import random
import time
import datetime
from multiprocessing import Process
import multiprocessing as mp
def mount(mountpoint, num_clients, dir, fuse_processes):
    if not os.path.exists(mountpoint):
        os.makedirs(mountpoint)
    subprocess.run(['ceph-fuse', mountpoint])
    if not os.path.exists(dir):
        os.makedirs(dir)
    for i in range(num_clients):
        subprocess.run(['mkdir', f'{mountpoint}/dir{i}'], cwd=mountpoint)
    for i in range(num_clients):
        fuse_process = subprocess.Popen(['ceph-fuse', '-r', '/dir', f'{mountpoint}/dir{i}'])
        fuse_processes.append(fuse_process)
    time.sleep(10)
def kill_process(num_clients, fuse_processes):
    for process in processes:
        process.terminate()
    for process in fuse_processes:
        process.terminate()
    for i in range(num_clients):
        subprocess.Popen(['umount', '-lf', f'{mountpoint}/dir{i}'])
    subprocess.run(['umount', '-lf', mountpoint])
def check_cluster_health(last_check):
    try:
        output = subprocess.check_output("ceph -s", shell=True, stderr=subprocess.STDOUT,
                 universal_newlines=True)
        assert "HEALTH_OK" in output
        print("Cluster health check successful")
        return 0
    except subprocess.CalledProcessError as e:
        if last_check == False:
            print("Cluster health check failed")
            return -1
        else:
            print("Cluster health check failed")
            kill_process(num_clients, fuse_processes)
            os._exit(-1)
    except AssertionError:
        if last_check == False:
            print("Cluster health check failed")
            return -1
        else:
            print("Cluster health check failed")
            kill_process(num_clients, fuse_processes)
            os._exit(-1)
def client_operation(client_idx):
    client_dir = f'{mountpoint}/dir{client_idx}'
    while True:
        # create file
        if random.random() < 0.3:
            filename = f'{client_dir}/{random.randint(1, 5000)}.txt'
            try:
                with open(filename, 'w') as f:
                    f.write('Sample content')
            except Exception as e:
                pass
        # create link
        elif random.random() < 0.35:
            try:
                files = os.listdir(client_dir)
                if len(files) > 0:
                    file_to_link = random.choice(files)
                    path_to_link = f'{client_dir}/{file_to_link}'
                    if os.path.isfile(path_to_link):
                        link_destination = f'{client_dir}/{random.randint(1, 5000)}.link'
                        os.link(path_to_link, link_destination)
            except Exception as e:
                pass
        # delete file
        else:
            try:
                files = os.listdir(client_dir)
                if len(files) > 0:
                    file_to_delete = random.choice(files)
                    path_to_delete = f'{client_dir}/{file_to_delete}'
                    if os.path.exists(path_to_delete):
                        os.remove(path_to_delete)
            except Exception as e:
                pass
if __name__ == "__main__":
    mountpoint = '/mnt/fuse'
    num_clients = 20
    dir = '/mnt/fuse/dir/'
    fuse_processes = []
    mount(mountpoint, num_clients, dir, fuse_processes)
    processes = []
    for i in range(num_clients):
        process = mp.Process(target=client_operation, args=(i,))
        process.start()
        processes.append(process)
    process = mp.Process(target=check_cluster_health, args=(False,))
    process.start()
    processes.append(process)
    total_running_time = datetime.datetime.now() + datetime.timedelta(seconds=3600)
    current_time = datetime.datetime.now()
    while current_time < total_running_time:
        result = check_cluster_health(False)
        #if result == 0:
        #    time.sleep(10)
        #else:
            #break
        time.sleep(10)
        current_time = datetime.datetime.now()
    kill_process(num_clients, fuse_processes)
    check_cluster_health(True)
``

**Comment by hyb-g** [comment]
reproduce script.
```
import os
import sys
import subprocess
import random
import time
import datetime
from multiprocessing import Process
import multiprocessing as mp
def mount(mountpoint, num_clients, dir, fuse_processes):
    if not os.path.exists(mountpoint):
        os.makedirs(mountpoint)
    subprocess.run(['ceph-fuse', mountpoint])
    if not os.path.exists(dir):
        os.makedirs(dir)
    for i in range(num_clients):
        subprocess.run(['mkdir', f'{mountpoint}/dir{i}'], cwd=mountpoint)
    for i in range(num_clients):
        fuse_process = subprocess.Popen(['ceph-fuse', '-r', '/dir', f'{mountpoint}/dir{i}'])
        fuse_processes.append(fuse_process)
    time.sleep(10)
def kill_process(num_clients, fuse_processes):
    for process in processes:
        process.terminate()
    for process in fuse_processes:
        process.terminate()
    for i in range(num_clients):
        subprocess.Popen(['umount', '-lf', f'{mountpoint}/dir{i}'])
    subprocess.run(['umount', '-lf', mountpoint])
def check_cluster_health(last_check):
    try:
        output = subprocess.check_output("ceph -s", shell=True, stderr=subprocess.STDOUT,
                 universal_newlines=True)
        assert "HEALTH_OK" in output
        print("Cluster health check successful")
        return 0
    except subprocess.CalledProcessError as e:
        if last_check == False:
            print("Cluster health check failed")
            return -1
        else:
            print("Cluster health check failed")
            kill_process(num_clients, fuse_processes)
            os._exit(-1)
    except AssertionError:
        if last_check == False:
            print("Cluster health check failed")
            return -1
        else:
            print("Cluster health check failed")
            kill_process(num_clients, fuse_processes)
            os._exit(-1)
def client_operation(client_idx):
    client_dir = f'{mountpoint}/dir{client_idx}'
    while True:
        # create file
        if random.random() < 0.3:
            filename = f'{client_dir}/{random.randint(1, 5000)}.txt'
            try:
                with open(filename, 'w') as f:
                    f.write('Sample content')
            except Exception as e:
                pass
        # create link
        elif random.random() < 0.35:
            try:
                files = os.listdir(client_dir)
                if len(files) > 0:
                    file_to_link = random.choice(files)
                    path_to_link = f'{client_dir}/{file_to_link}'
                    if os.path.isfile(path_to_link):
                        link_destination = f'{client_dir}/{random.randint(1, 5000)}.link'
                        os.link(path_to_link, link_destination)
            except Exception as e:
                pass
        # delete file
        else:
            try:
                files = os.listdir(client_dir)
                if len(files) > 0:
                    file_to_delete = random.choice(files)
                    path_to_delete = f'{client_dir}/{file_to_delete}'
                    if os.path.exists(path_to_delete):
                        os.remove(path_to_delete)
            except Exception as e:
                pass
if __name__ == "__main__":
    mountpoint = '/mnt/fuse'
    num_clients = 20
    dir = '/mnt/fuse/dir/'
    fuse_processes = []
    mount(mountpoint, num_clients, dir, fuse_processes)
    processes = []
    for i in range(num_clients):
        process = mp.Process(target=client_operation, args=(i,))
        process.start()
        processes.append(process)
    process = mp.Process(target=check_cluster_health, args=(False,))
    process.start()
    processes.append(process)
    total_running_time = datetime.datetime.now() + datetime.timedelta(seconds=3600)
    current_time = datetime.datetime.now()
    while current_time < total_running_time:
        result = check_cluster_health(False)
        #if result == 0:
        #    time.sleep(10)
        #else:
            #break
        time.sleep(10)
        current_time = datetime.datetime.now()
    kill_process(num_clients, fuse_processes)
    check_cluster_health(True)
```

**Pull request merged**
