### PR TITLE
jewel: radosgw-admin: failure for user create after upgrade from hammer to jewel

### PR DESCRIPTION
**Pull request by theanalyst**
http://tracker.ceph.com/issues/16009

### CODE REVIEW

**Comment by dachary** [comment]
test this please (was killed for unknown reasons)

**Comment by theanalyst** [comment]
This was only supposed to contain one commit, the other one is already a part of #9268 rebasing and force-pushing

**Comment by dachary** [comment]
@cbodley does this backport look good to merge ? It passed the rgw suite http://tracker.ceph.com/issues/16344#note-6 (except for one failure which I believe to be unrelated).

**Comment by cbodley** [comment]
@dachary yes, good to merge

**Pull request merged**
