### PR TITLE
doc: switch to sphinx_rtd_theme theme

### PR DESCRIPTION
**Pull request by tchaikov**
## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by tchaikov** [comment]
@liewegas could you take another look? I think it's ready for review.

**Comment by tchaikov** [comment]
@jdurgin @liewegas ping?

**Comment by tchaikov** [comment]
jenkins test make check

**Comment by tchaikov** [comment]
jenkins test make check

**Comment by tchaikov** [comment]
jenkins test make check

**Comment by liewegas** [comment]
The link at the bottom left for selecting the version is weird.. it pops up a window in the bottom *right* (which is the right location for the floating selector in the current version but not for the new theme).

Other than that, I'll miss the footer bar and breadcrumbs in the current them a little bit, but no big deal! The left-side navigation in this theme is way nicer (with the + and - to expand/collapse sections).

**Review by jdurgin — APPROVED** [review]
I agree, the navigation / toctree is much nicer! and the wider area / larger text is better for modern screens

**Comment by jdurgin** [comment]
Is the change in headers to no longer make them uppercase intentional? there are a number of them that no longer have the correct case, so we'd need to update them or change the header style back

**Comment by tchaikov** [comment]
@jdurgin it is. as I thought all-upper title is difficult to read. changed it back as you think it's should be an ALL_UPPERCASE_TITLE.

**Comment by tchaikov** [comment]
@liewegas thanks for your inputs! i just merged this changeset.

> The link at the bottom left for selecting the version is weird.. it pops up a window in the bottom right (which is the right location for the floating selector in the current version but not for the new theme).

fixed. the root cause is that sphinx_rtd_theme locates the "versions.html" div at bottom left, while the css offered by RTD puts it at the bottom right if the name of the theme is not "sphinx_rtd_theme". in this case, we derive a theme named "ceph" from "sphinx_rtd_theme", so RTD infra assume that it should put the "versions.html" at the default place, i.e. bottom-right. i override it in the latest revision.

> 
> Other than that, I'll miss the footer bar and breadcrumbs in the current them a little bit, but no big deal! 
> 

yeah, i put a second thought on this also. the top bar and breadscrumb are already displayed at the top. this renders the bottom one unnecessary. and i found it's difficult to have the footer in a good-looking way. so i gave up after some experiments.

if anything else, i'd like to address them in follow-up changes.

**Pull request merged**
