### PR TITLE
cmake fixes

### PR DESCRIPTION
**Pull request by oritwas**
enable compilation using cmake on fedora without cryptopp.

### CODE REVIEW

**Comment by dachary** [comment]
@oritwas did you notice #4003 ?

**Comment by oritwas** [comment]
no I will look at it

----- Original Message -----

**Comment by dalgaaf** [comment]
could you rebase to master?

**Comment by oritwas** [comment]
done

**Comment by yehudasa** [comment]
Reviewed-by: Yehuda Sadeh <yehuda@redhat.com>

**Pull request merged**
