### PR TITLE
jewel: Add compact operation to ceph-osdomap-tool

### PR DESCRIPTION
**Pull request by dzafman**
This commit was taken from ceph/ceph#18449

### CODE REVIEW

**Comment by ktdreyer** [comment]
we don't have a specific tracker.ceph.com ticket for this backport, but we should take this PR

**Comment by smithfarm** [comment]
transient make check failure: Test test/osd/osd-recovery-scrub.sh failed

retest this please

**Comment by dzafman** [comment]
@zmc The bc command is not available for test script src/test/osd/osd-recovery-scrub.sh

**Comment by dzafman** [comment]
We should re-test this after ceph/ceph#21014 merges.

**Comment by smithfarm** [comment]
#21014 merged

retest this please

**Comment by dzafman** [comment]
Doc build failure

retest this please

**Comment by smithfarm** [comment]
@dzafman You can repeat only the Docs build check by issuing the command:

jenkins test docs

**Comment by smithfarm** [comment]
jenkins test docs

**Comment by smithfarm** [comment]
@dzafman I was going to run it through a rados suite, but OK.

**Comment by dzafman** [comment]
@smithfarm The ceph-osdomap-tool isn't run during any rados tests, so there is no need.

**Pull request merged**
