### PR TITLE
quick-cephfs.rst: dedup

### PR DESCRIPTION
**Pull request by Dmole**
Remove code duplication from the dependency.

Signed-off-by: Tim <elatllat@gmail.com>

- `jenkins test docs`
- `jenkins render docs`

### CODE REVIEW

**Comment by joscollin** [comment]
I don't think this is a duplicate

**Comment by Dmole** [comment]
@joscollin 

The install guide;
    https://docs.ceph.com/docs/jewel/start/#installation-quick
Has a step 1;
    https://docs.ceph.com/docs/jewel/start/quick-start-preflight/
The first paragraph of which has OS recommendations;
    https://docs.ceph.com/docs/jewel/start/os-recommendations/

Why are we covering it again in step 3?
https://docs.ceph.com/docs/jewel/start/quick-cephfs/

Same argument for all the other items in this patch; This is not a standalone page, as noted in the first paragraph;
"you must have executed the procedures in the `Storage Cluster Quick Start`_ guide first."

**Comment by joscollin** [comment]
1. You need to refer to the same branch in-order to clear your doubts. This PR is targeted for the master branch. So refer to the master branch instead of jewel. And then revisit your [comments above](https://github.com/ceph/ceph/pull/32964#issuecomment-584196045).
2. What do you mean by `covering it again in step 3`? I don't see any duplicate in Prerequisites -> step 3 in jewel and in master.

**Comment by Dmole** [comment]
@joscollin
1.  I fixed my links to refer to master
(as a side issue the documentation should be more clear about what version it's showing like [postgresql](https://www.postgresql.org/docs/current/functions-matching.html)"

2. "quick-cephfs" is step 3 of "installation-quick" so any "prerequisites" should not be dropped on the user at such a late stage. (master=wrong place, jewel=duplicated).

**Comment by joscollin** [comment]
>        (as a side issue the documentation should be more clear about what version it's showing like [postgresql](https://www.postgresql.org/docs/current/functions-matching.html)")

We cannot hard code versions in the doc as It would be wrong while back-porting. There would be some other way to achieve this of-course, but we rely on the url now.

>     2. "quick-cephfs" is step 3 of "installation-quick" so any "prerequisites" should not be dropped on the user at such a late stage. (master=wrong place, jewel=duplicated).

As per the work-flow, we mainly fix the issues in the master and the back-port to [active stable releases](https://docs.ceph.com/docs/master/releases/general/) if it is necessary (Jewel is not active). The [Prerequisites you mention](https://docs.ceph.com/docs/master/start/quick-cephfs/#prerequisites) are specific to CephFS and it's use. It's not mandatory in a [basic Ceph cluster setting up](https://docs.ceph.com/docs/master/start/quick-start-preflight/) and that's why it is mentioned separately in Step 3.

**Pull request closed without merging**
