### PR TITLE
Removed unnecessary inclusion of iostream in several files

### PR DESCRIPTION
**Pull request by stiopaa1**
Signed-off-by: Michal Jarzabek <stiopa@gmail.com>

### CODE REVIEW

**Comment by stiopaa1** [comment]
Not sure what happened here - I can build it locally without any problems. 
Is it possible that there was some problem with the machine it was being built on?

**Comment by dachary** [comment]
@stiopaa1 are you able to run **make check** successfully ?

**Comment by dachary** [comment]
feel free to reopen when you confirm make check runs for you

**Comment by stiopaa1** [comment]
@dachary I am able to run make check successfully

**Comment by dachary** [comment]
@stiopaa1 it turns out this cannot be re-open because there was a force push. Could you please open another pull request ?

**Comment by stiopaa1** [comment]
@dachary 
https://github.com/ceph/ceph/pull/4707

**Pull request closed without merging**
