### PR TITLE
rgw: add delimiter to prefix only when path is specified

### PR DESCRIPTION
**Pull request by lebauce**
http://tracker.ceph.com/issues/12960 Fixes: #12960

Signed-off-by: Sylvain Baubeau <sbaubeau@redhat.com>

### CODE REVIEW

**Comment by theanalyst** [comment]
minor nit on the commit message. Could you make `Fixes` on the next line, as the tracker and a few maintainer scripts expect such a format?

**Comment by lebauce** [comment]
@theanalyst Sure. Is it correct now ?

**Comment by yehudasa** [comment]
@rzarzynski any chance you can review and test this one?

**Comment by rzarzynski** [comment]
@yehudasa this PR does look good to me. Also Tempest hasn't found any regressions here.

**Pull request merged**
