### PR TITLE
ceph-volume: pass --filter-for-batch from drive-group subcommand

### PR DESCRIPTION
**Pull request by jan--f**
Otherwise the drive-group spec potentially tries to pull in the root
device (if it fits).

Signed-off-by: Jan Fajerski <jfajerski@suse.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by jan--f** [comment]
jenkins test ceph-volume all

**Comment by jan--f** [comment]
jenkins test ceph-volume tox

**Comment by jan--f** [comment]
jenkins test ceph-volume all

**Comment by jan--f** [comment]
jenkins test ceph-volume tox

**Review by dsavineau — COMMENTED** [review]
I don't see any tests for drive-group subcommand in ceph-volume directory.

Am I missing something or is it covered elsewhere ?

**Comment by jan--f** [comment]
> I don't see any tests for drive-group subcommand in ceph-volume directory.
> 
> Am I missing something or is it covered elsewhere ?

There is not much to test here. The translation from drive group specs to device lists is handle (and tested) in the orchestrator code in https://github.com/ceph/ceph/tree/a6a03d0f5535a053239ae9e49c53ac9208bb0738/src/python-common/ceph. Other than that the inventory code is used.
This bug here is hard to catch since it is very environment dependent.

**Comment by sebastian-philipp** [comment]
ping?

**Comment by jan--f** [comment]
Still waiting on reviews @dsavineau @guits @rishabh-d-dave

**Review by rishabh-d-dave — APPROVED** [review]

**Review by guits — APPROVED** [review]

**Pull request merged**
