### PR TITLE
rgw: feature: storage class

### PR DESCRIPTION
**Pull request by joke-lee**
step to setup:
```
#create realm
./bin/radosgw-admin realm  create --rgw-realm=default
#modify zonegroup use realm created 
./bin/radosgw-admin zonegroup modify --rgw-zonegroup=default  --rgw-realm=default  --master
#modify zone use realm created
./bin/radosgw-admin zone  modify  --rgw-zone=default --rgw-zonegroup=default  --rgw-realm=default  --master
#create pool for rgw obj tail (STANDARD_IA storage class)
./bin/ceph osd pool create default.rgw.buckets.data-ia 8 8
#modify STANDARD storage class placement 
./bin/radosgw-admin zone placement modify --rgw-zone=default --placement-id=default-placement  --index-pool default.rgw.buckets.index  --data-pool default.rgw.buckets.data  --data-extra-pool=default.rgw.buckets.non-ec  --tail-data-pool=default.rgw.buckets.data --placement-storage-class=STANDARD
#add STANDARD_IA storage class placement 
./bin/radosgw-admin zone placement add --rgw-zone=default --placement-id=default-placement-ia  --index-pool default.rgw.buckets.index  --data-pool default.rgw.buckets.data  --data-extra-pool=default.rgw.buckets.non-ec  --tail-data-pool=default.rgw.buckets.data-ia --placement-storage-class=STANDARD_IA
#add to zonegroup
./bin/radosgw-admin zonegroup placement add --placement-id=default-placement --placement-storage-class=STANDARD --rgw-zonegroup=default
#add to zonegroup 
./bin/radosgw-admin zonegroup placement add --placement-id=default-placement-ia --placement-storage-class=STANDARD_IA --rgw-zonegroup=default
#update period
./bin/radosgw-admin period update --commit

add

rgw_realm = default
rgw_zonegroup = default
rgw_zone = default

to ceph.conf  and restart radosgw

```

upload with STANDARD_IA storage class
```
s3cmd put 5M_random  s3://test1/m1  --storage-class=STANDARD_IA  --multipart-chunk-size-mb=5
```
upload with STANDARD storage class
```
s3cmd put 6M_random  s3://test1/6M_ST  --storage-class=STANDARD  --multipart-chunk-size-mb=5
```

head obj
```
< HEAD /test1/m1 HTTP/1.1
< Host: 127.0.0.1:80
< Connection: keep-alive
< Accept-Encoding: gzip, deflate
< Accept: */*
< User-Agent: python-requests/2.18.4
< date: Wed, 20 Jun 2018 00:43:35 GMT
< Authorization: AWS yly:REaZAJiyz4SJxodtsJJKOB4Iom4=
<

> HTTP/1.1 200 OK
> Content-Length: 5242880
> Accept-Ranges: bytes
> Last-Modified: Tue, 19 Jun 2018 11:12:01 GMT
> ETag: "81485c0e873d222199469076b60f30e9-1"
> x-amz-storage-class: STANDARD_IA
> x-amz-request-id: tx000000000000000000004-005b29a337-51917-default
> Content-Type: binary/octet-stream
> Date: Wed, 20 Jun 2018 00:43:35 GMT
> Connection: Keep-Alive
>
```
list bucket
```
< GET /test1 HTTP/1.1
< Host: 127.0.0.1:80
< Connection: keep-alive
< Accept-Encoding: gzip, deflate
< Accept: */*
< User-Agent: python-requests/2.18.4
< date: Wed, 20 Jun 2018 00:44:07 GMT
< Authorization: AWS yly:036rWlrx0+umIExkfPkZTSp0sMk=
<

> HTTP/1.1 200 OK
> x-amz-request-id: tx000000000000000000005-005b29a357-51917-default
> Content-Type: application/xml
> Content-Length: 493
> Date: Wed, 20 Jun 2018 00:44:07 GMT
> Connection: Keep-Alive
>
<?xml version="1.0" encoding="UTF-8"?>
<ListBucketResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
  <Name>test1</Name>
  <Prefix/>
  <Marker/>
  <MaxKeys>1000</MaxKeys>
  <IsTruncated>false</IsTruncated>
  <Contents>
    <Key>6M_ST</Key>
    <LastModified>2018-06-20T00:45:41.779Z</LastModified>
    <ETag>"b85b671783f71782e00fa82f81a87fa9-2"</ETag>
    <Size>6291456</Size>
    <StorageClass>STANDARD</StorageClass>
    <Owner>
      <ID>yly</ID>
      <DisplayName>yly</DisplayName>
    </Owner>
  </Contents>
  <Contents>
    <Key>m1</Key>
    <LastModified>2018-06-19T11:12:01.432Z</LastModified>
    <ETag>"81485c0e873d222199469076b60f30e9-1"</ETag>
    <Size>5242880</Size>
    <StorageClass>STANDARD_IA</StorageClass>
    <Owner>
      <ID>yly</ID>
      <DisplayName>yly</DisplayName>
    </Owner>
  </Contents>
</ListBucketResult>

```
and ceph df

```
GLOBAL:
    SIZE       AVAIL      RAW USED     %RAW USED
    80 GiB     50 GiB       29 GiB         36.89
POOLS:
    NAME                            ID     USED        %USED     MAX AVAIL     OBJECTS
    .rgw.root                       9      6.6 KiB         0        50 GiB          18
    default.rgw.control             10         0 B         0        50 GiB           8
    default.rgw.meta                11     3.1 KiB         0        50 GiB          21
    default.rgw.log                 12        63 B         0        50 GiB         179
    default.rgw.buckets.data-ia     13       5 MiB         0        50 GiB           2
    default.rgw.buckets.index       14         0 B         0        50 GiB           3
    default.rgw.buckets.data        15       6 MiB      0.01        50 GiB           5
    data                            16         0 B         0        50 GiB           0
    default.rgw.buckets.non-ec      21         0 B         0        50 GiB           0

```

5 MiB for m1 obj (STANDARD_IA storage)
6 MiB for  6M_ST obj (STANDARD storage)

### CODE REVIEW

**Comment by ErwanAliasr1** [comment]
So many commits withtout a single commit message. That would be lovely to get details on them.

**Comment by yehudasa** [comment]
@joke-lee interesting, I just started on a similar/related project. See here: https://github.com/yehudasa/ceph/commits/wip-rgw-tiering
I'll look into incorporating your work in.

**Comment by fangyuxiangGL** [comment]
@yehudasa 
could you share some high level design of it? Is there any mechanism like s3 lifecycle which moves object between different tier? thanks

**Comment by mattbenjamin** [comment]
@yehudasa is this still useful?

**Pull request closed without merging**
