### PR TITLE
#15065: Add standby_for_fscid in MMDSBeacon and handle it

### PR DESCRIPTION
**Pull request by jcsp**
This PR depends on https://github.com/ceph/ceph/pull/7998, the new stuff here starts at the "s/standby_for_ns/standby_for_fscid/" commit

### CODE REVIEW

**Comment by jcsp** [comment]
The tests for this https://github.com/ceph/ceph-qa-suite/pull/905

**Comment by gregsfortytwo** [comment]
Looks good to me. I forget, did you want your standby-replay logic changes to go in here, or separately? (Perhaps post-jewel?)

**Comment by jcsp** [comment]
The standby replay cleanup will be a separate PR

**Comment by gregsfortytwo** [comment]
http://pulpito.ceph.com/gregf-2016-03-23_23:07:15-fs-greg-fs-testing-323-3---basic-mira/ and http://pulpito.ceph.com/gregf-2016-03-24_15:09:06-fs-greg-fs-testing-323-3---basic-mira/

**Pull request merged**
