### PR TITLE
doc/mgr/dashboard: Fix haproxy example to use ssl for backends

### PR DESCRIPTION
**Pull request by vosdev**
HAProxy talks to backends over http by default. Ceph mgr dashboard now only accepts https traffic.
This change configures haproxy to use https for communication with backends. `ssl` implies `check-ssl` making `check-ssl` is no longer neccesary.

Fixes: https://tracker.ceph.com/issues/46678
Signed-off-by: Daniël Vos <danielvos@outlook.com>

## Checklist
- [ ] References tracker ticket
- [x] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by smithfarm** [comment]
Alternatively, you could fix the issue in the `master` branch, first, and then get it backported to octopus.

**Comment by vosdev** [comment]
> 
> 
> Alternatively, you could fix the issue in the `master` branch, first, and then get it backported to octopus.

Thank you. I have changed the PR to be applied onto the `master` branch. @varshar16 re-base is done.

**Comment by varshar16** [comment]
jenkins test dashboard backend

**Comment by varshar16** [comment]
jenkins render docs

**Comment by callithea** [comment]
Hi @vosdev, thanks for your contribution!
Could you please update the PR title prefix as well as the commit message to like like this: "doc/mgr/dashboard:" ? Also if this fix should be backported to octopus we should have a tracker issue for this PR targeting master to make the backport process easier. Please let me know if I should create the tracker issue in case you don't have access/permissions. :) As soon as we have a tracker issue the commit message should be updated with a `Fixes: <tracker-url>`,  see [commit example](https://github.com/ceph/ceph/pull/36098/commits), [tracker issue](https://tracker.ceph.com/issues/46530) example.

**Comment by vosdev** [comment]
Hi @callithea ,
My tracker.ceph.com was recently accepted so I have made issues for each of my pull requests. I have modified my commit messages and PR title accordingly 👍 . 
I will try to make sure my future PRs are fully compliant with the ceph standards to make the code merging smoother.

**Comment by callithea** [comment]
> Hi @callithea ,
> My tracker.ceph.com was recently accepted so I have made issues for each of my pull requests. I have modified my commit messages and PR title accordingly 👍 . 
> I will try to make sure my future PRs are fully compliant with the ceph standards to make the code merging smoother.

Great, thanks a lot for creating the tracker issue and for updating the PR!

**Comment by s0nea** [comment]
jenkins test make check

**Comment by callithea** [comment]
jenkins test dashboard backend

**Comment by callithea** [comment]
jenkins test dashboard backend

**Comment by callithea** [comment]
jenkins test dashboard backend

**Comment by LenzGr** [comment]
Thank you for your contribution, @vosdev!

**Pull request merged**
