### PR TITLE
rgw: replace count with find

### PR DESCRIPTION
**Pull request by stiopaa1**
Signed-off-by: Michal Jarzabek <stiopa@gmail.com>

### CODE REVIEW

**Comment by cbodley** [comment]
were any of these using multimap::count()? isn't map::count() equivalent to find() unless you need the iterator?

**Comment by mattbenjamin** [comment]
agree, I don't see the bad count() AND search idiom in any of these;  iiuc, count() is not generally to be avoided, or something

**Comment by stiopaa1** [comment]
@cbodley 
Yes, it is equivalent when it comes to performance for maps, but not multimaps, so I think it is just better to use it everywhere. I also think it reads better than count. 
If none of the above convinces you then I was just doing this task:
https://trello.com/c/YUlqAp4s/105-use-stl-find-instead-of-count
:)

**Comment by cbodley** [comment]
@stiopaa1 cool, i didn't see that on trello. i don't necessarily agree on readability, especially when it adds repetition like `old_info->swift_keys.find(iter->first) != old_info->swift_keys.end()` and leads to extra line breaks

but i'm happy to let @liewegas make the judgement call - should we replace `count()` with `find() != end()` everywhere, or only in cases like the following where it's misused?
```c++
if (foo.count(bar)) {
  cout << foo[bar] << endl;
}
```

**Comment by liewegas** [comment]
Yeah, my concern was in places where it is misused (usually subsequent uses of operator[]).

**Comment by mattbenjamin** [comment]
I think that we should fix the count() + [] (or equivalent) cases, but NOT behave as if count() is inefficient or deprecated in general for map and set.

**Comment by stiopaa1** [comment]
@cbodley @liewegas @mattbenjamin 
Thanks for your input! 
I'm closing this then.

**Pull request closed without merging**
