### PR TITLE
mon: Sanely set the default CRUSH rule when creating pools in stretch…

### PR DESCRIPTION
**Pull request by gregsfortytwo**
… mode

If we get a pool create request while in stretch mode that does not explicitly
specify a crush rule, look at the stretch-mode pools and their rules, and
select the most common one.

Also update set_up_stretch_mode.sh to add a few more rules that let me test
this locally.

Fixes: https://tracker.ceph.com/issues/51270
Signed-off-by: Greg Farnum <gfarnum@redhat.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by athanatos** [comment]
This approach seems super dangerous.

**Comment by gregsfortytwo** [comment]
> This approach seems super dangerous.

What's the concern? Stretch clusters already require admins (or orchestrators) to have set up an appropriate rule; this only applies to pool create commands which do not set a specific rule; in the vast majority of cases there will only be one rule, which this will apply; it has the convenient property that if an admin changes all the pools to a new rule then this automatically picks up that change for subsequent pool creates.

**Comment by athanatos** [comment]
I don't like setting something as important as the crush rule to something that is neither a fixed default nor explicitly requested by the operator.

**Comment by athanatos** [comment]
Perhaps we could modify the command line invocation to detect a missing crush rule and suggest the one in this heuristic?

**Comment by athanatos** [comment]
Or have it be an explicit flag?

**Comment by athanatos** [comment]
What do we do for the first stretch pool?

**Comment by gregsfortytwo** [comment]
> I don't like setting something as important as the crush rule to something that is neither a fixed default nor explicitly requested by the operator.  This certainly isn't behavior I'd predict as a user.

I've got bad news for you on how crush rules are selected, then...
Seriously, the default crush rule is "-1" which means the lowest-numbered rule the system happens to have". In this case, for all practical cases the crush rule that is going to be selected is the one that the user entered when engaging stretch mode -- I just neglected to write it down explicitly when setting up those data structures.

> Perhaps we could modify the command line invocation to detect a missing crush rule and suggest the one in this heuristic?

The motivating case for this was pools created by the manager on upgrades (in a downstream version where that was possible), and rgw or whatever are not going to be able to supply rules explicitly.

**Review by athanatos — APPROVED** [review]

**Comment by tchaikov** [comment]
jenkins, retest this please.

**Comment by tchaikov** [comment]
- https://pulpito.ceph.com/kchai-2021-06-18_12:04:35-rados-wip-kefu-testing-2021-06-18-1414-distro-basic-smithi/
- https://pulpito.ceph.com/kchai-2021-06-19_08:35:14-rados-wip-kefu-testing-2021-06-18-1414-distro-basic-smithi/
- https://pulpito.ceph.com/kchai-2021-06-19_11:27:01-rados-wip-kefu-testing-2021-06-19-1642-distro-basic-smithi/

i don't think the failures were related to this change.

as i reran the failed tests without this change:

- https://pulpito.ceph.com/kchai-2021-06-19_12:18:10-rados-wip-kefu-testing2-2021-06-19-1707-distro-basic-smithi/

**Pull request merged**
