### PR TITLE
common: optimize encode_utf8

### PR DESCRIPTION
**Pull request by cyb70289**
This patch optimizes utf8 encode function and achieves 30% ~ 50% performance gain on x86 and Arm servers.

Benchmark source code is attached.
[ceph-utf8-encode.zip](https://github.com/ceph/ceph/files/3120181/ceph-utf8-encode.zip)

### CODE REVIEW

**Comment by tchaikov** [comment]
- http://pulpito.ceph.com/kchai-2019-04-27_02:20:42-rados-wip-kefu-testing-2019-04-26-2318-distro-basic-smithi/
- http://pulpito.ceph.com/kchai-2019-04-28_09:14:06-rados-wip-kefu-testing-2019-04-26-2318-distro-basic-smithi/

failed test tracked by https://tracker.ceph.com/issues/39449

**Comment by cyb70289** [comment]
Hi @tchaikov , I see some failed tests in the links in your comment. Are these failures caused by my patch? Shall I investigate the failed tests? Thanks.

**Comment by tchaikov** [comment]
@cyb70289 no, i don't think they are related. your change is just pending on review.

**Comment by cyb70289** [comment]
Hi @tchaikov, would you review this patch when you have time? Thanks a lot :)

**Pull request merged**
