### PR TITLE
mgr/dashboard: enable/disable MFA Delete on RGW bucket

### PR DESCRIPTION
**Pull request by alfonsomthd**
Configure a bucket to enable MFA (multi-factor authentication) Delete.

Test instructions:
https://tracker.ceph.com/issues/42094#note-2

Fixes: https://tracker.ceph.com/issues/42094
Signed-off-by: Alfonso Martínez <almartin@redhat.com>

42094-bucket-mfa-delete-v3

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by alfonsomthd** [comment]
jenkins test dashboard backend

**Comment by callithea** [comment]
jenkins test dashboard

**Comment by alfonsomthd** [comment]
@votdev @tspmelo @LenzGr @callithea @s0nea Rebased & added test instructions in description.

**Comment by LenzGr** [comment]
Thank you! When testing this feature I tried to enable "MFA Delete" without providing a Token Serial Number and PIN and received a "500 Internal Server Error" when clicking "Edit Bucket".

From the `mgr.x.log` file:
```
2020-01-30T16:56:27.633+0000 7f0dddff1700  0 [dashboard] [ERROR] [rest_client] RGW REST API failed PUT req status: 403
2020-01-30T16:56:27.633+0000 7f0dddff1700  0 [dashboard] [ERROR] [request] [::ffff:192.168.178.51:45040] [PUT] [500] [0.238s] [admin] [513.0B] /api/rgw/bucket/testbucket
2020-01-30T16:56:27.633+0000 7f0dddff1700  0 [dashboard] [ERROR] [request] [b'{"status": "500 Internal Server Error", "detail": "The server encountered an unexpected condition which prevented it from fulfilling the request.", "request_id": "eb97f379-c391-4da2-9cc8-889372251674"}                                                                                                                                                                                                                                                                                                                        ']
```
Could you please implement a verification in the form that prevents this from happening?

![Peek-2020-01-30 17-53](https://user-images.githubusercontent.com/263427/73471599-84700f00-4381-11ea-9ea1-99b49b9edd6e.gif)

**Comment by LenzGr** [comment]
The editing of the bucket succeeds when I provide the correct serial number and PIN when submitting the form. However, when the PIN is wrong or no longer valid (when the TOTP app generated a new PIN), I still get an "500 internal server error", without a clear explanation why this is failing.

Dito when I try to disable MFA Delete without providing a valid serial number and PIN. If possible, the dashboard should clearly indicate why this operation failed (invalid MFA credentials).

Lastly, I wonder if we shouldn't be using different widgets for toggling both the bucket versioning and MFA deletion. Instead of having 2x2 radio buttons (Enable/Suspend Versioning & Enable/Disable MFA Delete) wouldn't it be better two have two checkboxes instead?

[ ] Enable Versioning
[ ] Enable MFA Delete

What do you think?

I admit I don't know enough about this feature, but I was still able to simply delete a bucket that had "MFA Delete" enabled. Is this the intended behavior?

Probably a future enhancement, but I wonder if creating the necessary TOTP user and bucket configuration should be more straightforward, e.g. by making it possible to enable that via the dashboard and displaying a QR code that could be scanned?

**Comment by LenzGr** [comment]
With regards to choosing between radio buttons or checkboxes, we had some discussion during today's standup about this. The consensus was that checkboxes would be more appropriate here. The [Patternfly Design Guidelines](https://www.patternfly.org/v4/design-guidelines/usage-and-behavior/data-input/#checkbox) also recommend using checkboxes in this situation:

> You can also use a single checkbox to allow a user enable or disable a feature or setting.

**Comment by LenzGr** [comment]
> I admit I don't know enough about this feature, but I was still able to simply delete a bucket that had "MFA Delete" enabled. Is this the intended behavior?

Turns out it is intended behaviour, as my user has the "system" role - see [issue#43226](https://tracker.ceph.com/issues/43226) for background info.

**Comment by alfonsomthd** [comment]
@LenzGr I addressed all your comments.

**Comment by LenzGr** [comment]
retest this please

**Comment by alfonsomthd** [comment]
jenkins test dashboard backend

**Comment by alfonsomthd** [comment]
jenkins test dashboard backend

**Comment by callithea** [comment]
jenkins test dashboard backend

**Comment by callithea** [comment]
- [pkg build](https://shaman.ceph.com/builds/ceph/wip-laura-testing-31922-33454/) [WIP]

**Comment by alfonsomthd** [comment]
@callithea I ran locally ```tasks.mgr.dashboard.test_rgw``` successfully.
Can you set up another QA run?

**Comment by callithea** [comment]
> @callithea I ran locally `tasks.mgr.dashboard.test_rgw` successfully.
> Can you set up another QA run?

@alfonsomthd: When running `tasks.mgr.dashboard.test_rgw`  locally based on this PR I couldn't reproduce it either. When running all tests I get different failures, so I can't reproduce the QA run failure.
Sure, will trigger another run!

**Comment by callithea** [comment]
- [pkg build](https://shaman.ceph.com/builds/ceph/wip-laura-testing-31922-33178/) [WIP]

**Comment by callithea** [comment]
jenkins test make check

**Comment by callithea** [comment]
jenkins test dashboard backend

**Comment by callithea** [comment]
jenkins test dashboard

**Comment by callithea** [comment]
- [pkg build](https://shaman.ceph.com/builds/ceph/wip-laura-testing-31922/) [WIP]

**Comment by callithea** [comment]
jenkins test dashboard backend

**Comment by callithea** [comment]
- [QA run](http://pulpito.ceph.com/laura-2020-03-02_12:26:59-rados:dashboard-wip-laura-testing-31922-33178-2-distro-basic-smithi/) [WIP]

**Pull request merged**
