### PR TITLE
mgr/volumes: Add nfs cluster list command

### PR DESCRIPTION
**Pull request by varshar16**
This patch series does the following:
* Adds nfs cluster list command (`$ ceph nfs cluster ls`)
* Updates doc and test for ls command
*  Make tests py2 compatible (Required for Octopus backport)

Note: This PR includes commits of https://github.com/ceph/ceph/pull/35417. I will rebase this pr after #35417 is merged.
 <details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by varshar16** [comment]
http://qa-proxy.ceph.com/teuthology/varsha-2020-06-11_08:25:25-rados-wip-add-nfs-cluster-list-distro-basic-smithi/
```
2020-06-11T08:44:13.185 INFO:tasks.cephfs_test_runner:======================================================================
2020-06-11T08:44:13.186 INFO:tasks.cephfs_test_runner:FAIL: test_create_and_delete_cluster (tasks.cephfs.test_nfs.TestNFS)
2020-06-11T08:44:13.186 INFO:tasks.cephfs_test_runner:----------------------------------------------------------------------
2020-06-11T08:44:13.187 INFO:tasks.cephfs_test_runner:Traceback (most recent call last):
2020-06-11T08:44:13.187 INFO:tasks.cephfs_test_runner:  File "/home/teuthworker/src/git.ceph.com_ceph-c_wip-add-nfs-cluster-list/qa/tasks/cephfs/test_nfs.py", line 111, in test_create_and_delete_cluster
2020-06-11T08:44:13.188 INFO:tasks.cephfs_test_runner:    self._test_list_cluster()
2020-06-11T08:44:13.188 INFO:tasks.cephfs_test_runner:  File "/home/teuthworker/src/git.ceph.com_ceph-c_wip-add-nfs-cluster-list/qa/tasks/cephfs/test_nfs.py", line 79, in _test_list_cluster
2020-06-11T08:44:13.188 INFO:tasks.cephfs_test_runner:    self.assertEqual(self.cluster_id, nfs_output)
2020-06-11T08:44:13.189 INFO:tasks.cephfs_test_runner:AssertionError: 'test' != 'test\n'
```

**Comment by varshar16** [comment]
Test passed: http://qa-proxy.ceph.com/teuthology/varsha-2020-06-11_09:25:12-rados-wip-add-nfs-cluster-list-distro-basic-smithi/

**Comment by sebastian-philipp** [comment]
lgtm.

**Comment by jtlayton** [comment]
Note that there seem to be merge conflicts between this and https://github.com/ceph/ceph/pull/35417

**Comment by varshar16** [comment]
> Note that there seem to be merge conflicts between this and #35417

I will rebase this PR after #35417 is merged.

**Comment by varshar16** [comment]
To avoid confusion. I have merged commits from this PR into #35417

**Pull request closed without merging**
