### PR TITLE
mimic: doc: update experimental features - snapshots

### PR DESCRIPTION
**Pull request by joscollin**
https://tracker.ceph.com/issues/24746

---

* drop the experimental warning of multi-MDS
* update snapshotting blocked off version
* update Multiple filesystems availability in Jewel

### CODE REVIEW

**Comment by smithfarm** [comment]
@joscollin Would it make sense to cherry-pick 1586580d33ff3f1ca4b168d9e3bd1182643e031f into this PR?

**Comment by joscollin** [comment]
@smithfarm I'd say: Not necessary as only [this formatting change](https://github.com/ceph/ceph/commit/1586580d33ff3f1ca4b168d9e3bd1182643e031f#diff-ac2c8ff80e2ae5fb86fd1ef6d44fee08R24) is missing in the backport. But from your experience what do you suggest?

**Comment by smithfarm** [comment]
@joscollin Clearly it's not absolutely necessary, but I don't understand the reasoning for not including it. When I cherry-pick 1586580 first, the cherry-pick of 9ed1158 applies without any conflict.

In my experience, given a choice between cherry-picking (a) more commits without conflicts and (b) less commits with conflicts, (a) is preferable PROVIDED the following two conditions hold true:

* Condition #1: the target branch is reasonably young (early in its release cycle)
* Condition #2: I can be reasonably sure that the additional commits will not introduce any regression.

The reason it's preferable in this case is we have the entire mimic release cycle ahead of us, during which we will be doing lots of cherry-picking. By cherry-picking cleanup commits now, we streamline future backports by eliminating conflicts caused by the absence of these cleanup commits.

(Regarding condition #2, it's obvious that 1586580 causes no regression.)

**Comment by joscollin** [comment]
@smithfarm okay, I will cherry-pick https://github.com/ceph/ceph/commit/1586580d33ff3f1ca4b168d9e3bd1182643e031f too. I avoided it only because it is a trivial change.

**Comment by joscollin** [comment]
@smithfarm Done. Please check now.

**Pull request merged**
