### PR TITLE
ceph-disk:  Fix symlink created by ceph-disk to point at by-parttypeuuid

### PR DESCRIPTION
**Pull request by bmeekhof**
This is a fix for the PR at https://github.com/ceph/ceph/pull/17132
There does not seem to be any communication from the author of that PR regarding comments made on it.  His commit is included in this PR.  

Multipath devices do not have entries in /dev/disk/by-partuuid so the symlink that ceph-disk creates to the bluestore block device is invalid - it links to a sub-device of a multipath device instead of a dm-X device.  This doesn't work since the subdevices change, and of course also does not utilize all paths to a device.  

However those devices, along with more typical single devices, do all show up in /dev/disk/by-parttypeuuid.  This PR modifies ceph-disk to create the link to devices in that location. 

If there's a better solution to the issue I'd be more than happy to implement and test...we need this issue fixed to be able to use bluestore devices on our hardware.

### CODE REVIEW

**Comment by bmeekhof** [comment]
Made a small change since first PR submission:  Because of where I re-ordered the space_symlink definition it came after the dmcrypt and reusing_partition codeblocks, but it needs to come before.  Adjusted things accordingly, tested.

**Comment by tchaikov** [comment]
http://pulpito.ceph.com/kchai-2017-10-30_12:23:11-ceph-disk-wip-kefu-testing-2017-10-30-1511-distro-basic-vps/

**Comment by liewegas** [comment]
@bmeekhof ping?

**Comment by bmeekhof** [comment]
There hasn't been any more work on this.  Since ceph-disk is deprecated I decided we should just move on to ceph-volume and I'm waiting on testing with that tool.  If for whatever reason ceph-volume doesn't work for us we may revisit this though we'd probably prefer to submit fixes for ceph-volume in that case.

**Comment by squidboylan** [comment]
It would be nice if this would work with ceph-disk since it looks like that's what ceph-deploy uses currently, we're running into this issue currently and getting around it by symlinking to by-parttypeuuid in a script between osd creation and activation but it would be nice to have a fix upstream.

**Comment by alfredodeza** [comment]
@squidboylan ceph-deploy as of version 2.0.0 no longer uses ceph-disk and uses ceph-volume instead.

**Comment by bmeekhof** [comment]
As the submitter of this:  from my perspective the PR is officially 'abandoned' and at least for my part there won't be any work to fix it or ceph-disk.  We moved forward using ceph-volume and it works well with LV on top of multipath disks (though we create the LV outside ceph-volume first).  Would it be ok to just close this PR or leave around for other interested parties?

**Pull request closed without merging**
