### PR TITLE
jewel: cephfs: fuse client: ::rmdir() uses a deleted memory structure of dentry leads …

### PR DESCRIPTION
**Pull request by pdvian**
http://tracker.ceph.com/issues/22700

### CODE REVIEW

**Comment by smithfarm** [comment]
Jenkins re-test this please

**Comment by tchaikov** [comment]
retest this please.

**Comment by smithfarm** [comment]
jenkins re-test this please

**Comment by tchaikov** [comment]
retest this please.

**Comment by smithfarm** [comment]
retest this please

**Comment by tchaikov** [comment]
retest this please.

**Comment by smithfarm** [comment]
@tchaikov `test_pidfile.sh` failed even though we disabled it?

**Comment by smithfarm** [comment]
FACEPALM jewel uses autotools (geez, I forgot again)

**Comment by smithfarm** [comment]
opened https://github.com/ceph/ceph/pull/20557 to *really* disable the test

**Comment by smithfarm** [comment]
Oh Jenkins, bringer of auspicious test results, show us your favor and re-test this please

**Comment by smithfarm** [comment]
This passed an fs suite at http://tracker.ceph.com/issues/21742#note-18

@batrick OK to merge?

**Comment by smithfarm** [comment]
This passed an fs suite at http://tracker.ceph.com/issues/21742#note-18

@batrick @ukernel OK to merge?

**Pull request merged**
