### PR TITLE
jewel: Object map/fast-diff invalidated if journal replays the same snap remove event

### PR DESCRIPTION
**Pull request by dachary**
http://tracker.ceph.com/issues/16486

### CODE REVIEW

**Comment by dachary** [comment]
test this please (seems to have unrelated errors)

**Comment by dachary** [comment]
Hey, jenkins, test this please ! (no logs)

**Comment by dachary** [comment]
Hey, jenkins, test this please ! (timeout, asserting this is not a transient error)
<pre>
PASS: test/encoding/readable.sh
PASS: unittest_erasure_code_shec_all
PASS: test/osd/osd-scrub-repair.sh
make: *** [check-recursive] Terminated
make[5]: *** Deleting file `unittest_pglog.log'
make[4]: *** wait: No child processes.  Stop.
make[4]: *** Waiting for unfinished jobs....
make[4]: *** wait: No child processes.  Stop.
make[2]: *** [check-recursive] Terminated
make[5]: *** wait: No child processes.  Stop.
make[5]: *** Waiting for unfinished jobs....
make[5]: *** wait: No child processes.  Stop.
make[3]: *** [check-am] Error 2
make[1]: *** [check] Terminated
</pre>

**Comment by trociny** [comment]
lgtm

**Pull request merged**
