### PR TITLE
mon: Clock skew causes missing summary and confuses Calamari

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/11878

This is a cherry-pick of Thorsten Behren's downstream firefly backport of https://github.com/ceph/ceph/pull/3659

### CODE REVIEW

**Comment by smithfarm** [comment]
testing please ignore

**Comment by dachary** [comment]
@smithfarm could you please rebase and repush to trigger the bot ?

**Comment by dachary** [comment]
@jecluis this backport has passed the rados suite ( http://pulpito.ceph.com/loic-2015-07-09_21:09:04-rados-firefly-backports---basic-multi ) do you think it can be merged in firefly ?

**Comment by jecluis** [comment]
sorry, I'm not finding 092ef99 in upstream master. Is this a backport directly from suse's repo? is there no corresponding upstream patch?

**Comment by dachary** [comment]
hum, indeed, that's unexpected. Good catch @jecluis !

**Comment by smithfarm** [comment]
My bad, sorry. Since Thorsten had already done the backport downstream, I cherry-picked from there to avoid extra work. Later I learned this is not allowed, but forgot to go back and re-do this PR.

Rebased to latest firefly and cherry-picked from the master patch.

**Comment by jecluis** [comment]
I'm okay with this backport.

**Pull request merged**
