### PR TITLE
nautilus: rgw: cls_bucket_list_(un)ordered should clear results collection

### PR DESCRIPTION
**Pull request by ivancich**
backport tracker: https://tracker.ceph.com/issues/44470

backport of https://github.com/ceph/ceph/pull/33702

parent tracker: https://tracker.ceph.com/issues/44395

---

Each call to cls_bucket_list_(un)ordered should have an empty
collection to populate with results. Rather than rely on the caller to
insure this, it's more reliable to have these functions do the clear.

Additionally in some cases, a reserve call was added to the collection
to pre-allocate the space needed for the expected number of
results. This will potentially result in fewer re-allocations plus
copies.

Fixes: https://tracker.ceph.com/issues/44470

### CODE REVIEW

**Comment by smithfarm** [comment]
@ivancich Any chance you could start using `src/script/ceph-backport.sh` (just take it from the master branch, copy it into your path, and type:

    ceph-backport.sh BACKPORT_TRACKER_ISSUE_NUMBER

(There is some initial setup required, mainly because the script uses the GitHub API which requires a token, which you have to create. But the script will guide you through that.)

I'm confident this would save both of us a lot of time processing your backports.

**Comment by smithfarm** [comment]
I'm ready to give you (and anyone else) full support in terms of answering any questions regarding the use of `src/script/backport-create-issue` and `src/script/ceph-backport.sh`. Just email me:

    Nathan Cutler <ncutler@suse.com>

**Comment by ivancich** [comment]
> @ivancich Any chance you could start using `src/script/ceph-backport.sh`? Just take it from the master branch, copy it into your path, and type:
> 
> ```
> ceph-backport.sh BACKPORT_TRACKER_ISSUE_NUMBER
> ```
> 
> (There is some initial setup required, mainly because the script uses the GitHub API which requires a token, which you have to create. But the script will guide you through that.)
> 
> I'm confident this would save both of us a lot of time processing your backports.

My apologies, @smithfarm . I will try to remember next time I do a backport.

**Comment by smithfarm** [comment]
Note: `git cherry-pick -x` generates the Conflicts section, but one does have to remember to uncomment it.

**Comment by smithfarm** [comment]
@ivancich This just needs a `git commit --amend` to add the following text to the end of the commit message:

```
Conflicts:
    src/rgw/rgw_admin.cc
    src/rgw/rgw_rados.cc
```

**Comment by ivancich** [comment]
> @ivancich This just needs a `git commit --amend` to add the following text to the end of the commit message:
> 
> ```
> Conflicts:
>     src/rgw/rgw_admin.cc
>     src/rgw/rgw_rados.cc
> ```

Thank you, @smithfarm. I added those two conflicts to the commit message.

**Comment by smithfarm** [comment]
```
  9/170 Test   #3: test_objectstore_memstore.sh ............***Failed    9.85 sec
```

**Comment by smithfarm** [comment]
jenkins test make check

**Comment by yuriw** [comment]
[wip-yuri7-testing-2020-07-22-1609-nautilus](https://trello.com/c/swvMA7ea/975-wip-yuri7-testing-2020-07-22-1609-nautilus)

**Pull request merged**
