### PR TITLE
ceph-volume: Allow the inventory to create Device objects in parallel

### PR DESCRIPTION
**Pull request by pcuzner**
Each Device object runs a number of lvs/pvs/lsblk/blkid etc commands
so processing serially introduces longer runtimes. This patch just uses
a producer/consumer model to attempt to create the Device objects
in parallel to reduce inventory runtimes. Tests have shown 40-50% reduction in 
runtimes.

Fixes: https://tracker.ceph.com/issues/47295

Signed-off-by: Paul Cuzner <pcuzner@redhat.com>

### CODE REVIEW

**Comment by pcuzner** [comment]
@jan--f is there something that this PR is missing? If so, please let me know.

**Comment by jan--f** [comment]
> @jan--f is there something that this PR is missing? If so, please let me know.

Sorry, nothing missing, just not enough hours in the day.

**Review by jan--f — COMMENTED** [review]
Pretty impressive speedup, with how many devices is that?

I think we could get rid of the hard-coded thread count and explicit sync by using https://docs.python.org/3/library/concurrent.futures.html. Any interest in pursuing this here?

**Comment by pcuzner** [comment]
@jan--f TBH, no - not at this point. Probably something to consider when we look at a refactor. For now, simple with standard features is good enough for me.

**Comment by jan--f** [comment]
> @jan--f TBH, no - not at this point. Probably something to consider when we look at a refactor. For now, simple with standard features is good enough for me.

The concurrent package is part of pythons stdlib and the code arguably gets simpler, so not sure what you mean here.
#37274 implements what I had in mind. From my own tests this is on par with your performance improvements here. Any chance you could confirm this in your environment?

**Comment by pcuzner** [comment]
OK, I'll do a bake off.

**Comment by pcuzner** [comment]
I did 10 executions, with a 30sec interval between each with
for i in 1 2 3 4 5 6 7 8 9 10; do time ceph-volume inventory &> /dev/null; sleep 30; done

These are the results;

| Existing | PR | futures |
|------------|------|-----------|
|8.2| 5.2| 4.8|
|6.9| 3.3| 4.4|
|7.5| 4.2| 4.9|
|6.7| 4.5| 4.8|
|7.1| 4.9| 5.9|
|7.8| 3.7| 4.9|
|7.3| 5.1| 6.6|
|7.5| 4.6| 4.6|
|7.1| 3.4| 5.2|
|7.5| 4.2| 5.6|
|----|---|---|
| 7.3 | 4.3 | 5.1 |

The old school way reduces runtime by 41%, and is 17% better than the futures
futures reduces runtime by 30%

thoughts @jan--f ?

**Review by jmolmo — APPROVED** [review]
This speed up things considerably. Good contribution.

**Comment by jan--f** [comment]
@jmolmo Please also see #37274 

Also there is no solution to the broken terminal logging with this or the alternative approach.

**Comment by jan--f** [comment]
Not to mention that this will need testing in conjunction with #37319 .

**Comment by pcuzner** [comment]
Closing since Jan has reimplemented the idea with concurrent.futures - less code, but longer run time.

**Comment by guits** [comment]
> Closing since Jan has reimplemented the idea with concurrent.futures - less code, but longer run time.

we are talking about a difference of ~15 lines of codes though :man_shrugging:

**Comment by jan--f** [comment]
> > Closing since Jan has reimplemented the idea with concurrent.futures - less code, but longer run time.
> 
> we are talking about a difference of only ~15 lines of codes though man_shrugging

15 lines is not far off of 50% of the whole change here. Furthermore #37274 has no hardcoded thread count and no explicit locking and sync code. This is about maintainability. Runtime can be tuned and this assertion of a longer runtime is based one, I assume (and please correct me if I'm wrong here) one test system.

**Comment by dsavineau** [comment]
@jan--f Excuse my ignorance about thread/worker in python but what's the difference between doing:

In this PR (with num_threads=4)
```python
  for n in range(num_threads):
```

and in your PR

```python
 with futures.ThreadPoolExecutor(max_workers=4) as executor:
```

As I understand it, both have the thread/worker to 4 maximum hardcoded.

**Comment by jan--f** [comment]
> As I understand it, both have the thread/worker to 4 maximum hardcoded.

Not quite, the ThreadPoolExecutor approach starts a maximum of 4 threads, whereas this PR always starts 4 threads. Both variables are actually aptly named :)

With `max_workers=4` this might not have a huge impact, but I'm not entirely convinced we'll stay at 4.

**Pull request closed without merging**
