### PR TITLE
pacific: cephfs-top: dump values to stdout and -d [--delay] option fix

### PR DESCRIPTION
**Pull request by joscollin**
Fixes: https://tracker.ceph.com/issues/58807
Fixes: https://tracker.ceph.com/issues/59398
Fixes: https://tracker.ceph.com/issues/59595

**EDIT:**
Also backports following PRs -
* https://github.com/ceph/ceph/pull/47139
* https://github.com/ceph/ceph/pull/48664

## Checklist
- [x] References tracker ticket
- [x] Updates documentation if necessary
- [x] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by joscollin** [comment]
@yuriw This PR is updated with 2 more commits.

**Comment by joscollin** [comment]
jenkins test make check

**Comment by joscollin** [comment]
@yuriw Rebased and added 2 more commits.

**Comment by vshankar** [comment]
@yuriw please drop this from your testing branch - this required additional fixes in main.

**Comment by joscollin** [comment]
> Also backports following PRs -
> 
> * [doc/man/cephfs-top.rst: add missing options: --delay, --conffile #47139](https://github.com/ceph/ceph/pull/47139)
> * [cephfs-top: drop x_coord_map #48664](https://github.com/ceph/ceph/pull/48664)

They are just conflict resolutions.

**Review by kotreshhr — APPROVED** [review]

**Pull request merged**
