### PR TITLE
qa/standalone/scrub/osd-scrub-repair.sh: fix race in TEST_auto_repair_bluestore_failed

### PR DESCRIPTION
**Pull request by neha-ojha**
We need to flush_pg_stats before checking for active+clean.

Fixed: https://tracker.ceph.com/issues/45075
Signed-off-by: Neha Ojha <nojha@redhat.com>

### CODE REVIEW

**Comment by neha-ojha** [comment]
Before:

```
./qa/standalone/scrub/osd-scrub-repair.sh:497: TEST_auto_repair_bluestore_failed:  ceph pg dump pgs
PG_STAT  OBJECTS  MISSING_ON_PRIMARY  DEGRADED  MISPLACED  UNFOUND  BYTES  OMAP_BYTES*  OMAP_KEYS*  LOG  DISK_LOG  STATE              STATE_STAMP                      VERSION  REPORTED  UP     UP_PRIMARY  ACTING  ACTING_PRIMARY  LAST_SCRUB  SCRUB_STAMP                      LAST_DEEP_SCRUB  DEEP_SCRUB_STAMP                 SNAPTRIMQ_LEN
1.0            9                   0         0          0        0     63            0           0   10        10  active+clean+wait  2020-04-16T21:58:09.198308+0000    20'10    40:124  [1,0]           1   [1,0]               1       20'10  2020-04-16T21:58:09.198136+0000            20'10  2020-04-16T21:58:09.198136+0000              0

* NOTE: Omap statistics are gathered during deep scrub and may be inaccurate soon afterwards depending on utilization. See http://docs.ceph.com/docs/master/dev/placement-group/#omap-statistics for further details.
dumped pgs
../qa/standalone/scrub/osd-scrub-repair.sh:498: TEST_auto_repair_bluestore_failed:  ceph pg dump pgs
../qa/standalone/scrub/osd-scrub-repair.sh:498: TEST_auto_repair_bluestore_failed:  grep -q '^1.0.* active+clean '
dumped pgs>
```
After:

```
../qa/standalone/scrub/osd-scrub-repair.sh:498: TEST_auto_repair_bluestore_failed:  ceph pg dump pgs
PG_STAT  OBJECTS  MISSING_ON_PRIMARY  DEGRADED  MISPLACED  UNFOUND  BYTES  OMAP_BYTES*  OMAP_KEYS*  LOG  DISK_LOG  STATE         STATE_STAMP                      VERSION  REPORTED  UP     UP_PRIMARY  ACTING  ACTING_PRIMARY  LAST_SCRUB  SCRUB_STAMP                      LAST_DEEP_SCRUB  DEEP_SCRUB_STAMP                 SNAPTRIMQ_LEN
1.0            9                   0         0          0        0     63            0           0   10        10  active+clean  2020-04-16T18:59:03.184899+0000    21'10    41:124  [1,0]           1   [1,0]               1       21'10  2020-04-16T18:58:57.507677+0000            21'10  2020-04-16T18:58:57.507677+0000              0

* NOTE: Omap statistics are gathered during deep scrub and may be inaccurate soon afterwards depending on utilization. See http://docs.ceph.com/docs/master/dev/placement-group/#omap-statistics for further details.
dumped pgs
../qa/standalone/scrub/osd-scrub-repair.sh:499: TEST_auto_repair_bluestore_failed:  ceph pg dump pgs
../qa/standalone/scrub/osd-scrub-repair.sh:499: TEST_auto_repair_bluestore_failed:  grep -q '^1.0.* active+clean '
```

**Comment by yuriw** [comment]
[wip-yuri7-testing-2020-04-22-1640-master](https://trello.com/c/9Z6XfbyH/878-wip-yuri7-testing-2020-04-22-1640-master)

**Comment by neha-ojha** [comment]
@tchaikov @jdurgin I've added 7c8b627eaa478a97b5694704170336ed4fc40666 to make the test more robust, flush_pg_stats alone cannot deal with the race

**Comment by yuriw** [comment]
[wip-yuri-testing-2020-04-24-1941-master](https://trello.com/c/GFVGvIbx/883-wip-yuri-testing-2020-04-24-1941-master)

**Comment by yuriw** [comment]
[wip-yuri4-testing-2020-04-25-0009-master](https://trello.com/c/b1ICydf9/884-wip-yuri4-testing-2020-04-25-0009-master)

**Comment by badone** [comment]
Test run failed, see https://trello.com/c/GFVGvIbx/883-wip-yuri-testing-2020-04-24-1941-master#comment-5eaa251a65d46e61fddf3a3f

**Comment by neha-ojha** [comment]
> Test run failed, see https://trello.com/c/GFVGvIbx/883-wip-yuri-testing-2020-04-24-1941-master#comment-5eaa251a65d46e61fddf3a3f

@badone How is "2020-04-29T03:09:03.805 INFO:teuthology.orchestra.run.smithi188.stdout:[ FAILED ] ObjectStore/StoreTestSpecificAUSize.Many4KWritesNoCSumTest/2, where GetParam() = "bluestore" (9501 ms)" related to this PR?

This PR has been tested at https://trello.com/c/b1ICydf9/884-wip-yuri4-testing-2020-04-25-0009-master

**Pull request merged**
