### PR TITLE
jewel: mds: issue new caps when sending reply to client

### PR DESCRIPTION
**Pull request by Vicente-Cheng**
http://tracker.ceph.com/issues/20027

### CODE REVIEW

**Comment by smithfarm** [comment]
@Vicente-Cheng Please rebase to get a new Jenkins run.

**Comment by smithfarm** [comment]
@Vicente-Cheng Please rebase.

**Comment by smithfarm** [comment]
Jenkins re-test this please

**Comment by Vicente-Cheng** [comment]
@smithfarm thanks for reminder, I'll rebase all...

**Comment by smithfarm** [comment]
@jcsp This passed a fs suite at http://pulpito.front.sepia.ceph.com/smithfarm-2017-06-22_11:51:56-fs-wip-jewel-backports-distro-basic-smithi/ - one job failed ("Test failure: test_remote_update_write (tasks.cephfs.test_quota.TestQuota)")

**Comment by smithfarm** [comment]
@jcsp Ping

**Comment by smithfarm** [comment]
This one is flagged for inclusion in 10.2.8

**Comment by jcsp** [comment]
Sorry, I was skittish about http://tracker.ceph.com/issues/20412 but now I think that was just a bug in the test config

**Pull request merged**
