### PR TITLE
nautilus: mgr/telemetry: fix device serial number anonymization

### PR DESCRIPTION
**Pull request by yaarith**
backport of https://github.com/ceph/ceph/pull/32492

Please see: https://github.com/ceph/ceph/pull/32926

### CODE REVIEW

**Comment by smithfarm** [comment]
jenkins test make check

**Comment by smithfarm** [comment]
```
CTest Failure
1 tests failed out of 167  Total Test time (real) = 3627.35 sec
The following tests FAILED: 	 51 - unittest_lockdep (Timeout)
```

**Comment by smithfarm** [comment]
jenkins test make check

**Comment by yuriw** [comment]
[wip-yuri2-testing-2020-02-12-1852-nautilus](https://trello.com/c/UIOUawk2/825-wip-yuri2-testing-2020-02-12-1852-nautilus)

**Pull request merged**
