### PR TITLE
msg: randomize client nonces

### PR DESCRIPTION
**Pull request by jdurgin**
http://tracker.ceph.com/issues/13032

### CODE REVIEW

**Comment by liewegas** [comment]
lgtm!

**Comment by gregsfortytwo** [comment]
Is there a particular reason we don't want to include the PID as part of the nonce like libcephfs does? I guess it's not strictly required but it sure seems useful.

**Comment by jdurgin** [comment]
just less chance of collision. have you found the pid useful? I haven't, but I'm not usually worried about mapping multiple clients from the same node to a pid

**Comment by gregsfortytwo** [comment]
I think I've used it in the past, although I can't name an example offhand. I'd imagine it's pretty helpful if you actually have a bunch of clients on one box and they all have the same keys, though...(letting you find the right admin socket to talk to, etc)

**Comment by jdurgin** [comment]
If you have access to the clients (especially their admin sockets) you can distinguish them pretty easily. No need for special meanings in the nonce. Esp. with containers, the client id assigned by the monitors is more helpful than the pid.

**Pull request merged**
