### PR TITLE
nautilus: mgr/dashboard: Add transifex-i18ntool

### PR DESCRIPTION
**Pull request by Exotelis**
backport tracker: https://tracker.ceph.com/issues/42482

### CODE REVIEW

**Comment by callithea** [comment]
jenkins test dashboard

**Comment by callithea** [comment]
jenkins test dashboard

**Comment by LenzGr** [comment]
jenkins test dashboard

**Comment by LenzGr** [comment]
jenkins test dashboard

**Comment by Exotelis** [comment]
jenkins test dashboard

**Comment by callithea** [comment]
jenkins test dashboard

**Comment by callithea** [comment]
jenkins test dashboard

**Comment by callithea** [comment]
jenkins test dashboard

**Comment by callithea** [comment]
jenkins test dashboard

**Comment by callithea** [comment]
jenkins test dashboard

**Comment by callithea** [comment]
QA run [WIP]:
- http://pulpito.ceph.com/laura-2019-11-18_15:26:14-rados:dashboard-wip-laura-testing-dashboard-nautilus-batch-4-distro-basic-mira/

**Pull request merged**
