### PR TITLE
jewel: Hammer (0.94.3) OSD does not delete old OSD Maps in a timely fashion (maybe at all?)

### PR DESCRIPTION
**Pull request by Abhishekvrshny**
http://tracker.ceph.com/issues/15856

### CODE REVIEW

**Comment by smithfarm** [comment]
@tchaikov please review

**Comment by tchaikov** [comment]
thanks @smithfarm and @Abhishekvrshny , we'd better include #9108 also, once it gets reviewed and merged. but since #8828 does not work under some circumstances, i need to revisit it later.

if we can make this PR into the approaching v10.2.1. probably we should just have #8990 in this backport PR, as #9108 is still pending on review and it "needs-qa". what do you think?

**Comment by tchaikov** [comment]
i piggy backed the revised #8828 in #9108.

**Comment by smithfarm** [comment]
@tchaikov Our backport/stable releases tooling is designed on the (loose) assumption that each backport has a corresponding "master bug". Is it possible to give #9108 its own tracker issue separate from http://tracker.ceph.com/issues/13990 ?

**Comment by smithfarm** [comment]
Put more simply, it makes our lives easier if there is a 1:1 correspondence between issues and PRs.

**Comment by tchaikov** [comment]
@smithfarm  then i'd prefer we cherry pick all of them in a single backport PR. what do you think?

**Comment by smithfarm** [comment]
>  i'd prefer we cherry pick all of them in a single backport PR. what do you think?

@tchaikov That would be my preference as well.

**Comment by tchaikov** [comment]
@Abhishekvrshny hi Abhishek, in addition to this commit, could you also cherry-pick 

- 9789c29
- 82b0af7
- 87850e9

i removed the non-critical commits in #9108 from the list. also, this hammer counterpart of this backport is #9090. thanks!

**Comment by Abhishekvrshny** [comment]
@tchaikov : Done. Please review.

**Comment by tchaikov** [comment]
tested at http://pulpito.ceph.com/kchai-2016-05-30_08:11:32-rados-wip-13990-jewel---basic-smithi/

failed ones are addressed by https://github.com/ceph/ceph-qa-suite/pull/1027 .

**Pull request merged**
