### PR TITLE
mgr/dashboard: Jenkins Applitools plugin: add batchId variable

### PR DESCRIPTION
**Pull request by aaryanporwal**
batchId variable is mandatory for the applitools test runner to show up in jenkins build reports, for more details, visit : https://plugins.jenkins.io/applitools-eyes/.

Signed-off-by: Aaryan Porwal <aaryanporwal2233@gmail.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Review by epuertat — APPROVED** [review]
Does that env variable need to be injected in the Jenkins job, as well as you did for the API key one, or is it exported by the e2e script itself?

**Comment by aaryanporwal** [comment]
> Does that env variable need to be injected in the Jenkins job, as well as you did for the API key one, or is it exported by the e2e script itself?

The env variable will be directly exported by Jenkins itself, once the plugin is up and running. Documented at  https://plugins.jenkins.io/applitools-eyes/ under the heading "Updating Your Test Code"

**Review by alfonsomthd — APPROVED** [review]

**Comment by epuertat** [comment]
ARM64 make check failure is unrelated to this (3h timeout: `ninja: build stopped: interrupted by user.`).

**Comment by epuertat** [comment]
BTW @aaryanporwal please remember to add the `Fixes: https://tracker.ceph.com/issues/47497` line to the commit and the PR (well, if you add that to the commit, it'll be automatically added to the PR description). It's needed for when we backport this to previous branches, as it helps relate all the work pieces and move them all together.

**Pull request merged**
