### PR TITLE
crimson/osd/main: Enable multicore cluster messenger

### PR DESCRIPTION
**Pull request by Matan-B**
Taken from: f78e99c (Part 2/2 #52295)

Follow-up to: #55641

Drafted until tested.

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [x] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Review by liu-chunmei — APPROVED** [review]

**Review by liu-chunmei — APPROVED** [review]

**Comment by cyx1231st** [comment]
Added a label ^, should be related.

**Review by athanatos — APPROVED** [review]

**Comment by Matan-B** [comment]
https://shaman.ceph.com/builds/ceph/wip-matanb-crimson-cluster-msgr-testing

**Comment by Matan-B** [comment]
Results [1] look good after removing the assertion in the second commit.
IIUC, this should be ok to handle the request from any core and not only from the **primary core**.
However, the request should be handled from the **primary OSD** of the PG.
@athanatos

[1] https://pulpito.ceph.com/matan-2024-03-10_10:35:56-crimson-rados-wip-matanb-crimson-cluster-msgr-testing-distro-crimson-smithi/

**Comment by athanatos** [comment]
> Results [1] look good after removing the assertion in the second commit. IIUC, this should be ok to handle the request from any core and not only from the **primary core**. However, the request should be handled from the **primary OSD** of the PG. @athanatos
> 
> [1] https://pulpito.ceph.com/matan-2024-03-10_10:35:56-crimson-rados-wip-matanb-crimson-cluster-msgr-testing-distro-crimson-smithi/

The primary-osd constraint isn't relevant here -- it's taken care of otherwise.  Removing this assert as you have done here should be sufficient.

**Review by cyx1231st — APPROVED** [review]

**Comment by Matan-B** [comment]
jenkins test make check

**Comment by Matan-B** [comment]
jenkins test api

**Pull request merged**
