### PR TITLE
mgr/telemetry: specify license when opting in

### PR DESCRIPTION
**Pull request by liewegas**
Choosing not to include this in the docs so that the user is more likely
to see this interactively.  (That is...probably good?)

### CODE REVIEW

**Comment by liewegas** [comment]
@l-mb

**Comment by l-mb** [comment]
I like this, but am unsure whether it's fully sufficient. In particular, I wonder if we should / need to include the license in the telemetry data entry (so that if we ever change the terms, we know under which terms we received it).

Also, if we need to specify who the "Data Provider" is. Because it looks to me the DP is actually the user, and "we" are actually "you": _1.14 “You” or “Your” means any Entity that Receives Data under this Agreement._

**Comment by liewegas** [comment]
Added a field to the report that specifies the license

**Comment by liewegas** [comment]
retest this please

**Pull request merged**
