### PR TITLE
luminous: qa: test_recovery_pool tries asok on wrong node

### PR DESCRIPTION
**Pull request by pdvian**
http://tracker.ceph.com/issues/24929

### CODE REVIEW

**Comment by pdvian** [comment]
@batrick Shall I wait for PR#21885 changes to be merged to luminous ? I had to resolve changes manually for setupfs.

**Comment by batrick** [comment]
@pdvian waiting is fine. Backport issue: http://tracker.ceph.com/issues/24914

**Comment by yuriw** [comment]
[wip-yuri5-testing-2018-08-01-2158-luminous](https://trello.com/c/sUiX40Jw/362-wip-yuri5-testing-2018-08-01-2158-luminous)

**Comment by batrick** [comment]
Causes this failure: http://pulpito.ceph.com/yuriw-2018-08-02_00:15:47-fs-wip-yuri5-testing-2018-08-01-2256-luminous-distro-basic-smithi/2849916/

**Comment by yuriw** [comment]
@pdvian pls tag `needs-qa` when fixed

**Comment by yuriw** [comment]
[wip-yuri5-testing-2018-08-03-2114-luminous](https://trello.com/c/O6q0j5Gf/366-wip-yuri5-testing-2018-08-03-2114-luminous)

**Comment by pdvian** [comment]
@batrick @yuriw Sure. Let me work on it and do the needful.

**Comment by pdvian** [comment]
@batrick Added commit for qa/tasks/cephfs/filesystem.py changes. Kindly review.

**Comment by smithfarm** [comment]
@pdvian Ping - could you please respond to https://github.com/ceph/ceph/pull/23086#pullrequestreview-146931530

**Comment by smithfarm** [comment]
@pdvian Please add the signed-off-by to the last commit?

**Pull request closed without merging**
