### PR TITLE
doc/man/8: Add valid options in ceph-bluestore-tool.rst

### PR DESCRIPTION
**Pull request by Patty8122**
Added valid options for fsck deep flag (*(on|off) or (yes|no) or (1|0) or (true|false)*)
Fixes:  https://tracker.ceph.com/issues/62912
Signed-off-by: Patty8122 <divyapattisapu@uchicago.edu>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [x] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

doc/man/8/ceph-bluestore-tool.rst edited.
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by anthonyeleven** [comment]
Thanks for contributing!  A couple of things:

* The PR and commit titles should be like `doc/man/8: Add valid options in ceph-bluestore-tool.rst`.  Yes, this is subtle.
*  https://github.com/ceph/ceph/pull/53611 also seems to make this same change, along with the usage message change requested in the tracker ticket.

Should this PR perhaps be closed in favor of 53611 as one-stop-shopping?

**Comment by Patty8122** [comment]
Thank you for suggesting the edits, @anthonyeleven!

**Comment by ljflores** [comment]
Hey @Patty8122, you can make changes to as many files as needed all in one PR!

**Comment by ljflores** [comment]
> Thanks for contributing! A couple of things:
> 
>     * The PR and commit titles should be like `doc/man/8: Add valid options in ceph-bluestore-tool.rst`.  Yes, this is subtle.
> 
>     * [mds: Include more information in print statement in MDSRank.cc #53611](https://github.com/ceph/ceph/pull/53611) also seems to make this same change, along with the usage message change requested in the tracker ticket.
> 
> 
> Should this PR perhaps be closed in favor of 53611 as one-stop-shopping?

Relooking at this comment, PR https://github.com/ceph/ceph/pull/53611 addresses a different issue and should be kept separate. It is okay as-is.

**Comment by ljflores** [comment]
@Patty8122 you were right to keep the PRs separate, as they are different issues.

Looking at this one though, I think the actual ceph bluestore tool code should be edited as well to reflect the changes you made in the documentation.

The relevant code is in this file: https://github.com/ceph/ceph/blob/main/src/os/bluestore/bluestore_tool.cc

On your local setup, you can compile this code by following these steps, providing you have run the install-deps.sh script and do_cmake.sh script:
```
cd ceph/build
ninja ceph-bluestore-tool
```

And then you can see the current `--help` descriptions like this:
```
$ ./bin/ceph-bluestore-tool --help
All options:

Options:
  -h [ --help ]          produce help message
  -i arg                 OSD instance. Requires access to monitor/ceph.conf
  --path arg             bluestore path
  --out-dir arg          output directory
  --input-file arg       import file
  --dest-file arg        destination file
  -l [ --log-file ] arg  log file
  --log-level arg        log level (30=most, 20=lots, 10=some, 1=little)
  --dev arg              device(s)
  --devs-source arg      bluefs-dev-migrate source device(s)
  --dev-target arg       target/resulting device
  --deep arg             deep fsck (read all data)
  -k [ --key ] arg       label metadata key name
  -v [ --value ] arg     label metadata value
  --allocator arg        allocator to inspect: 'block'/'bluefs-wal'/'bluefs-db'
  --sharding arg         new sharding to apply
  --resharding-ctrl arg  gives control over resharding procedure details

Positional options:
  --command arg          fsck, qfsck, allocmap, restore_cfb, repair, quick-fix,
                         bluefs-export, bluefs-import, bluefs-bdev-sizes, 
                         bluefs-bdev-expand, bluefs-bdev-new-db, 
                         bluefs-bdev-new-wal, bluefs-bdev-migrate, show-label, 
                         set-label-key, rm-label-key, prime-osd-dir, 
                         bluefs-log-dump, free-dump, free-score, 
                         free-fragmentation, bluefs-stats, reshard, 
                         show-sharding
```

**Comment by ljflores** [comment]
I have also added two people who frequently work on the Bluestore code who can take a look! @aclamk (Adam) and @ifed01 (Igor).

**Review by anthonyeleven — APPROVED** [review]

**Pull request merged**
