### PR TITLE
os/filestore: queue ondisk completion before apply work

### PR DESCRIPTION
**Pull request by liupan1111**
…and improve write op performance.

Signed-off-by: Pan Liu <liupan1111@gmail.com>

### CODE REVIEW

**Comment by liupan1111** [comment]
@ceph-jenkins retest.

**Comment by liupan1111** [comment]
@rhcs-jenkins retest pleast.

**Comment by liupan1111** [comment]
@ceph-jenkins retest it please.

**Comment by shinobu-x** [comment]
retest this please

**Comment by liupan1111** [comment]
@liewegas , please help take a look, thanks!

**Comment by liupan1111** [comment]
@liewegas or @tchaikov , ping.

**Comment by liupan1111** [comment]
@dzafman , could help take a look? Thanks.

**Comment by xinxinsh** [comment]
how much performance improvement can be achieved

**Comment by liupan1111** [comment]
@xinxinsh not big, only few percent, but this change seems reasonable to me.

**Comment by dzafman** [comment]
@liupan1111 I have no idea if the reordering would break something or not.

**Comment by markhpc** [comment]
Ordering changes in filestore make me nervous.  Channeling my inner-Sam, I think we need a really good reason to muck around with it.  A few percent probably isn't enough to take on the risk, at least until bluestore is in production.

**Comment by liupan1111** [comment]
@markhpc, yeah... I agree, I will close it.

**Comment by liupan1111** [comment]
@markhpc 
I made a test today: three hosts with each one has four NVME SSD, pool size = 3.
Fio configuration:
fio --ioengine=rbd --pool=test_pool --clientname=admin --rbdname=image --direct=1 --thread --rw=randwrite -numjobs=1 --iodepth=256 --bs=16k --group_reporting --name=test --time_based --runtime=600
Before change:
image
After change: 
image
Seems there is an improvement of nearly 20%. Please correct me if you have any opinion about this.

**Comment by liupan1111** [comment]
@liewegas What do you think about this change?

**Comment by liupan1111** [comment]
retest this please

**Comment by liupan1111** [comment]
retest this please

**Comment by liewegas** [comment]
This is so simple and should be safe. Let's test!

**Comment by liewegas** [comment]
http://pulpito.ceph.com/sage-2017-07-01_06:55:28-rados-wip-sage-testing2-distro-basic-smithi/ included on suspicious hang, going to try to reproduce that first.

**Comment by tchaikov** [comment]
- http://pulpito.ceph.com/kchai-2017-07-05_03:23:34-rados-wip-kefu-testing-distro-basic-mira/
- http://pulpito.ceph.com/kchai-2017-07-04_08:30:19-rados-wip-kefu-testing-distro-basic-mira/

**Comment by tchaikov** [comment]
could be the cause of http://tracker.ceph.com/issues/20524, i am looking at it.

**Pull request merged**
