### PR TITLE
crush: add --dump to crushtool

### PR DESCRIPTION
**Pull request by dachary**

### CODE REVIEW

**Comment by liewegas** [comment]
Should we try to mirror the other ceph tools which do -f <json|json-pretty|xml|xml-pretty|plain> vs a different 'command' here?  This could be '-d -f json-pretty'.  (No strong opinion here; this is less consistent but probably an easier user experience.)

**Comment by dachary** [comment]
@liewegas I'll do that

**Comment by dachary** [comment]
@liewegas updated & repushed

**Comment by dachary** [comment]
modified to updated the usage and repushed

**Comment by yuriw** [comment]
http://pulpito.front.sepia.ceph.com:80/yuriw-2017-03-03_16:16:25-rados-wip-yuri-testing_2017_3_4-distro-basic-smithi/

http://pulpito.ceph.com/yuriw-2017-03-05_23:28:15-rados-wip-yuri-testing_2017_3_4---basic-smithi/
and reproduce
http://pulpito.ceph.com/yuriw-2017-03-05_23:28:45-rados-wip-yuri-testing_2017_3_4---basic-mira/

**Pull request merged**
