### PR TITLE
quincy: qa: test_rebuild_simple checks status on wrong file system

### PR DESCRIPTION
**Pull request by batrick**
https://tracker.ceph.com/issues/59367

### CODE REVIEW

**Comment by batrick** [comment]
jenkins test api

**Comment by batrick** [comment]
https://tracker.ceph.com/projects/cephfs/wiki/Quincy#2023-Apr-2124

**Review by vshankar — APPROVED** [review]

**Comment by batrick** [comment]
> Just want to leave a note that
> 
> > https://tracker.ceph.com/projects/cephfs/wiki/Quincy#2023-Apr-2124
> 
> included #51030 in the run.
> 
> So still waiting until #51030 is backported to quincy for this to be merged.

https://github.com/ceph/ceph/pull/52241

**Review by batrick — COMMENTED** [review]
https://tracker.ceph.com/projects/cephfs/wiki/Quincy#2023-August-08

`Reviewed-by: Patrick Donnelly <pdonnell@redhat.com>`

**Pull request merged**
