### PR TITLE
cls_rbd: mirroring directory

### PR DESCRIPTION
**Pull request by jdurgin**
Move pool mirroring settings to an 'rbd_mirroring' object, and add a
directory of images that are mirrored, and their remote counterparts.

### CODE REVIEW

**Comment by jdurgin** [comment]
Added some thoughts on what should go on top of this at the end of http://pad.ceph.com/p/rbd_mirror_daemon

**Comment by dillaman** [comment]
Minor: should the new type be added to the ceph-dencoder test?

**Comment by jdurgin** [comment]
yeah, meant to add that

**Comment by dillaman** [comment]
Merged manually -- TestClsRbd.mirror_image test case would fail if TestClsRbd.mirror test case run beforehand.

**Pull request closed without merging**
