### PR TITLE
qa/workunits/rbd: use more recent qemu-iotests that support Bionic

### PR DESCRIPTION
**Pull request by dillaman**
Fixes: http://tracker.ceph.com/issues/24668
Signed-off-by: Jason Dillaman <dillaman@redhat.com>

- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by trociny** [comment]
@dillaman It seems I have not been run qemu-iotests for long time so I don't know the current status but running with your PR they fail [1]. Do you think it is still ok to merge this PR?

[1] http://pulpito.ceph.com/trociny-2019-04-22_05:11:40-rbd-wip-mgolub-testing-distro-basic-smithi/

**Comment by dillaman** [comment]
@trociny I had to tweak the QEMU version for bionic. It looks like the remaining failures are for test 005 for a spurious msgr v2 log message -- I am going to try to repeat on my environment but I suspect it's just a slow cluster causing the failure.

**Comment by trociny** [comment]
@dillaman It still fails [1].

[1] http://pulpito.ceph.com/trociny-2019-04-24_08:25:19-rbd-wip-mgolub-testing-distro-basic-smithi/

**Comment by dillaman** [comment]
It looks like it's always test case 005 due to the msgr log message. I think that counts as an unrelated failure so I've opened [1] to track it.

[1] http://tracker.ceph.com/issues/39448

**Pull request merged**
