### PR TITLE
ceph-disk: fix luks dmcrypt mapping during activation

### PR DESCRIPTION
**Pull request by ddiss**
This patchset fixes some issues with the recently merged ceph-disk activate --dmcrypt support, and additionally adds unit test coverage.

### CODE REVIEW

**Comment by ddiss** [comment]
Ping, any thoughts on this patch set? These changes address some pretty serious bugs in master ceph-disk (for activate --dmcrypt).

**Comment by ddiss** [comment]
Looks like I now need to rebase here.

**Comment by ddiss** [comment]
Rebased. It was just the restorecon change that was conflicting (fix is now upstream via 3aab146b).

Please pull.

**Comment by dachary** [comment]
@ddiss Looks great, sorry for the lag. Now that infernalis was forked this should be against the infernalis branch. It looks good to me. Could you please confirm that you ran the tests and they succeeded ?

**Comment by ddiss** [comment]
Thanks for the feedback Loïc.

The output of the tests before and after the fixes can be found at:

http://paste.opensuse.org/0af11aa2 (with fixes)
http://paste.opensuse.org/ee7585f0 (without fixes)

Regarding the infernalis merge: can I wait for the changes to hit master, then cherry-pick -x and submit, or should I raise a bug to track the backport?

**Comment by dachary** [comment]
master + backporting to infernalis with cherry-pick -x would be what we do after infernalis is released. Right now infernalis is the branch where all bug fixes such as this one should go. And infernalis is merged into master on a regular (daily or so) basis. That's why I'm suggesting you target infernalis instead of master.

**Comment by ddiss** [comment]
Okay, will resubmit against the infernalis - thanks.

**Comment by dachary** [comment]
@ddiss it would also be great if you could create an issue in http://tracker.ceph.com/ to track this and include a **Fixes: #XXX** where appropriate.

**Comment by dachary** [comment]
@ddiss note that the method for testing ceph-disk in infernalis changed significantly. I'm willing to translate your pull request to use them so you don't have to go into the trouble of re-writing the tests you already wrote.

**Pull request closed without merging**
