### PR TITLE
qa/tasks: py3 compat (tasks exercised by rados suites)

### PR DESCRIPTION
**Pull request by tchaikov**
this change is part of the ongoing effort of fixing https://tracker.ceph.com/issues/42871 . and it's a subset of #32262.

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by kshtsk** [comment]
do we need to add Fix tag to commit message? Or it is just enough to add it to PR? Same question to my patchset?

**Comment by kshtsk** [comment]
This PR looks good, however could you please add info in comments which command did you use to test it in sepia if it is not complicated?
Also, do you want me to try and run it on py3 compat teuthology?

**Comment by tchaikov** [comment]
tested using
```
$ teuthology-suite --subset 795/9999 --machine-type smithi --suite rados  --ceph wip-kefu-testing-2020-03-04-1337
```

**Comment by tchaikov** [comment]
> do we need to add Fix tag to commit message? Or it is just enough to add it to PR? Same question to my patchset?

i don't think it's necessary in this case. as it's an ongoing efforts and there would be more commits which "Fixes" the python3 issue. @smithfarm , what do you think?

**Comment by smithfarm** [comment]
I don't think it's useful to add a bunch of tracker issues for this project. 

On the Ceph side, the project will only be "finished" once all the Python 2-isms have been removed from all active branches (master, octopus, nautilus, mimic, luminous). 

So I'm fine with this PR as it is.

**Comment by liewegas** [comment]
> I don't think it's useful to add a bunch of tracker issues for this project.
> 
> On the Ceph side, the project will only be "finished" once all the Python 2-isms have been removed from all active branches (master, octopus, nautilus, mimic, luminous).
> 
> So I'm fine with this PR as it is.

I agree!

**Comment by tchaikov** [comment]
thanks @smithfarm!

**Pull request merged**
