### PR TITLE
qa: run various tests on ubuntu

### PR DESCRIPTION
**Pull request by liewegas**
Pin tests that still need python2 to run on ubuntu only.

### CODE REVIEW

**Comment by cbodley** [comment]
@liewegas we currently have a lot of tests pinned to centos because of the valgrind issues on ubuntu:
```
$ grep -r centos qa/suites/rgw
qa/suites/rgw/verify/validater/valgrind.yaml:os_type: centos
qa/suites/rgw/verify/tasks/0-install.yaml:os_type: centos
qa/suites/rgw/multisite/tasks/test_multi.yaml:os_type: centos
qa/suites/rgw/multisite/valgrind.yaml:os_type: centos
qa/suites/rgw/tempest/distro/valgrind.yaml:os_type: centos
qa/suites/rgw/website/overrides.yaml:os_type: centos
```
the rgw/verify and rgw/website suites both run s3tests, so it looks like we'll need to disable valgrind temporarily for those

**Comment by liewegas** [comment]
> @liewegas we currently have a lot of tests pinned to centos because of the valgrind issues on ubuntu:
> 
> ```
> $ grep -r centos qa/suites/rgw
> qa/suites/rgw/verify/validater/valgrind.yaml:os_type: centos
> qa/suites/rgw/verify/tasks/0-install.yaml:os_type: centos
> qa/suites/rgw/multisite/tasks/test_multi.yaml:os_type: centos
> qa/suites/rgw/multisite/valgrind.yaml:os_type: centos
> qa/suites/rgw/tempest/distro/valgrind.yaml:os_type: centos
> qa/suites/rgw/website/overrides.yaml:os_type: centos
> ```
> 
> the rgw/verify and rgw/website suites both run s3tests, so it looks like we'll need to disable valgrind temporarily for those

Yeah.  I'm kind of hoping we can fix s3-tests before merge, or shortly after, instead of disabling tests...

**Comment by cbodley** [comment]
is there a way to pin a specific centos version? if we could pin centos7, these python2 tests would still run with valgrind coverage

**Comment by cbodley** [comment]
> ImportError: No module named rados

we may have to disable ragweed testing if we don't have python2 bindings for rados

**Comment by liewegas** [comment]
> is there a way to pin a specific centos version? if we could pin centos7, these python2 tests would still run with valgrind coverage

We can pin, yes, but it won't help because there won't be el7 builds at all.  At least not initially... at some point we may add back client-side only, I think (librados etc).

**Comment by liewegas** [comment]
retest this please

**Comment by liewegas** [comment]
> > ImportError: No module named rados
> 
> we may have to disable ragweed testing if we don't have python2 bindings for rados

Okay, I'll update to do that

**Comment by cbodley** [comment]
am i right that commit https://github.com/ceph/ceph/pull/32278/commits/4f3964cb5299e686dda9e06662665fab57362648 is removing the entire verify, multisite, tempest, and website subsuites, rather than just disabling the valgrind coverage? i would like to continue running those under ubuntu with python2 if possible

**Pull request merged**
