### PR TITLE
doc: Modify the format error of the Nautilus version rados help document

### PR DESCRIPTION
**Pull request by ybwang0211**
The "CACHE POOLS OPTIONS:" parameter lacks a newline character, so we modified it

Signed-off-by: ybwang0211 <ybwang0211@163.com>

Fix: https://tracker.ceph.com/issues/53743

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by ljflores** [comment]
jenkins test api

**Comment by ybwang0211** [comment]
您好，这里是王迎彬的邮箱，已经收到您的邮件，谢谢。

**Comment by ljflores** [comment]
Looks like this mistake was already fixed on the master branch with this commit: https://github.com/ceph/ceph/commit/368808d782b6792bcddc59ba838c68811362671e

@neha-ojha perhaps this change needs to be backported?

**Comment by ljflores** [comment]
@ybwang0211 thanks for bringing this to our attention. The question here is whether it would be better to fix this mistake with this PR, or backport the change from a prior commit. Stay tuned for updates.

**Comment by ljflores** [comment]
Hi @ybwang0211, I've looked further into this issue. Since we no longer maintain Nautilus, as it is an end of life version, we cannot accept this fix. However, if you find the same issue in supported versions of Ceph, such as Octopus or Pacific, we can backport a fix for that.

In your case, if you upgrade to a stable version, you may find that the problem has been solved.

**Pull request closed without merging**
