### PR TITLE
qa/workunits: update telemetry quincy workunits with `basic_pool_options_bluestore` collection

### PR DESCRIPTION
**Pull request by ljflores**
To be merged after #49414!!!

Signed-off-by: Laura Flores <ljflores@redhat.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [x] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [x] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by ljflores** [comment]
@yaarith we merged the new bluestore collection to quincy and reef, so I added it to the upgrade tests.

**Review by yaarith — APPROVED** [review]

**Comment by yaarith** [comment]
jenkins test make check arm64

**Comment by yaarith** [comment]
jenkins test windows

**Comment by ljflores** [comment]
Make check (arm64) and windows failures are unrelated.

**Comment by ljflores** [comment]
@yuriw when you do QA for this, can you please make sure tests from the `rados/upgrade` suite *and* `upgrade/telemetry-upgrade` are run?

`upgrade/telemetry-upgrade` suite -- https://github.com/ceph/ceph/tree/main/qa/suites/upgrade/telemetry-upgrade

**Comment by ljflores** [comment]
Unstale

**Comment by NitzanMordhai** [comment]
Rados approved: https://tracker.ceph.com/projects/rados/wiki/MAIN#httpstrellocomc6oYH6qSe1924-wip-yuri3-testing-2024-01-10-0735-old-wip-yuri3-testing-2024-01-09-1342

**Pull request merged**
