### PR TITLE
[DNM] pacific: Updates to fix `make check` failures - also includes 2d3c656 

### PR DESCRIPTION
**Pull request by tserong**
2d3c656 fixes the weird failure to build on openSUSE Tumbleweed with LTO enabled, as mentioned in https://github.com/ceph/ceph/pull/47803#issuecomment-1230124964. I also needed to grab de6c8250a6d91403e6d334aeb901bf9720ba40eb and 404f8b2ce268917c9ce04fa06aaccff4816ad8d6 to add a missing `%dir` line in the spec file.

### CODE REVIEW

**Comment by tserong** [comment]
jenkins test make check

**Comment by tserong** [comment]
jenkins test make check

**Comment by tserong** [comment]
jenkins test make check

**Comment by tserong** [comment]
jenkins test make check

**Comment by tserong** [comment]
braggi15 doesn't like me (https://jenkins.ceph.com/job/ceph-pull-requests/102715/consoleFull#-10404601397641bc0b-bacc-4481-8290-0cf28df0ce68):

```
CMake Error at /opt/ceph/lib/x86_64-linux-gnu/cmake/Boost-1.79.0/BoostConfig.cmake:141 (find_package):
  Found package configuration file:

    /opt/ceph/lib/x86_64-linux-gnu/cmake/boost_python-1.79.0/boost_python-config.cmake

  but it set boost_python_FOUND to FALSE so package "boost_python" is
  considered to be NOT FOUND.  Reason given by package:

  No suitable build variant has been found.

  The following variants have been tried and rejected:

  * libboost_python310.so.1.79.0 (3.10, Boost_PYTHON_VERSION=3.8)

  * libboost_python310.a (3.10, Boost_PYTHON_VERSION=3.8)

Call Stack (most recent call first):
  /opt/ceph/lib/x86_64-linux-gnu/cmake/Boost-1.79.0/BoostConfig.cmake:262 (boost_find_component)
  cmake/modules/FindBoost.cmake:462 (find_package)
  CMakeLists.txt:634 (find_package)
```

**Comment by tserong** [comment]
jenkins test make check

**Comment by rzarzynski** [comment]
jenkins test make check

**Comment by tserong** [comment]
jenkins test make check

**Comment by rzarzynski** [comment]
```
-- Found babeltrace: /usr/include  
CMake Error at /opt/ceph/lib/x86_64-linux-gnu/cmake/Boost-1.79.0/BoostConfig.cmake:141 (find_package):
  Could not find a package configuration file provided by "boost_atomic"
  (requested version 1.79.0) with any of the following names:

    boost_atomicConfig.cmake
    boost_atomic-config.cmake
```

**Comment by rzarzynski** [comment]
jenkins test make check

**Comment by tserong** [comment]
Closing (those three commits have since been added to #47803)

**Pull request closed without merging**
