### PR TITLE
[DNM PENDING CHERRY-PICK RE-DO] nautilus: rgw: backport of "kmip kms" and Hashicorp Vault features to nautilus

### PR DESCRIPTION
**Pull request by mdw-at-linuxbox**
This is a backport of

https://github.com/ceph/ceph/pull/33996

to nautilus.  Since nautilus lacks hashicorp vault support, this PR of necessity also includes additional commits to pull that in.

There is one new submodule here "libkmip".

### CODE REVIEW

**Comment by mdw-at-linuxbox** [comment]
I pushed a fix for at least some of the "make check" problems.

**Review by smithfarm — CHANGES_REQUESTED** [review]
Please add a commit updating `PendingReleaseNotes`

**Comment by mattbenjamin** [comment]
@mdw-at-linuxbox also, has the kmip feature merged to master? (@smithfarm)

**Comment by smithfarm** [comment]
Yeah, the `PendingReleaseNotes` commit should be cherry-picked from master, too.

**Comment by cbodley** [comment]
the work in https://github.com/ceph/ceph/pull/33996 hasn't yet merged to master

**Comment by cbodley** [comment]
nautilus is eol in june. i don't really think it makes sense to take this feature backport

if nautilus already had vault, i could see a benefit in taking the transit enhancements. but for users that are interested in vault/kmip, they've long had the opportunity to upgrade for them

what do you think @mdw-at-linuxbox @mattbenjamin?

**Comment by smithfarm** [comment]
So, as expected, the commits that went into master are different from the ones that were cherry-picked into this PR, so the cherry-picking would need to be re-done.

Also, this PR has 24 commits and the master PR #33996 has only 15, so that would need to be explained somehow, too. (I assume some of the commits originate from other master PRs, but these are not listed.)

Given how mature nautilus has become, I would add - in line with @cbodley 's comment - that this feature backport needs a risk-benefit analysis, too.

**Pull request closed without merging**
