### PR TITLE
kraken: osd: condition object_info_t encoding on required (not up) features

### PR DESCRIPTION
**Pull request by shinobu-x**
http://tracker.ceph.com/issues/18814
http://tracker.ceph.com/issues/18842

### CODE REVIEW

**Comment by smithfarm** [comment]
Agreed to cherry-pick the commit from #13593 into this PR. Marking DNM until that happens.

**Comment by shinobu-x** [comment]
Removed [DNM] tag suggested by @smithfarm (#13593)

**Comment by smithfarm** [comment]
Actually, this wasn't ready to be merged because it lacked a description of the conflict and how it was resolved.

**Comment by badone** [comment]
It was all green and had no DNM?

**Comment by smithfarm** [comment]
@badone No problem; you did nothing wrong. I started using the approval function to mark backport PRs as being properly cherry-picked, and did not communicate this effectively.

Backport PRs are typically merged by members of the backporting team after they go through integration testing and after the person who merged the master commit (Sage in this case) agrees that they are ready.

This is all about preventing regressions in stable releases.

**Comment by smithfarm** [comment]
(I will stop using the approval function in this way)

**Comment by badone** [comment]
@smithfarm understood. This was escalated due to a users ML thread highlighting this as a live issue in kraken distro packages.

**Pull request merged**
