### PR TITLE
mgr: expose CRUSHMap.find_roots()

### PR DESCRIPTION
**Pull request by tchaikov**
so mgr module could use it to enumerate all nodes without parents

See-also: https://tracker.ceph.com/issues/50971
Signed-off-by: Kefu Chai <kchai@redhat.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Review by avanthakkar — APPROVED** [review]
LGTM! Thanks @tchaikov . Btw just a question though (not related to PR), I see some difference in o/p of `ceph osd tree` and crush buckets list, for e.g. 
```
 "id": -1,
          "name": "default",
          "type_id": 11,
          "type_name": "root",
            }
  
          ]
        },
        {
          "id": -2,
          "name": "default~hdd",
          "type_id": 11,
          "type_name": "root",
          ```
this is the crush bucket list, but for crush tree I don't see the `name=default~hdd`. So are these not considered under crush tree?

**Comment by tchaikov** [comment]
not sure what do you mean by "bucket tree", but FWIW, the notation of "default~hdd" is the result of how we compose buckets with class (like "hdd" and "ssd").

**Comment by avanthakkar** [comment]
> not sure what do you mean by "bucket tree", but FWIW, the notation of "default~hdd" is the result of how we compose buckets with class (like "hdd" and "ssd").

No, "crush tree". Ok, yes but I mean to ask that I can't see these buckets (with class hdd, ssd, etc..) in the output of `ceph osd tree` .  But I think now I am clear bcz it has no corresponding tree so it won't be shown in the crush tree.

**Comment by tchaikov** [comment]
- https://pulpito.ceph.com/kchai-2021-05-28_02:36:20-rados-wip-kefu-testing-2021-05-28-0853-distro-basic-smithi/
- https://pulpito.ceph.com/kchai-2021-05-28_13:33:45-rados-wip-kefu-testing-2021-05-28-1806-distro-basic-smithi/
- https://pulpito.ceph.com/kchai-2021-05-29_02:33:40-rados-wip-kefu-testing-2021-05-28-1806-distro-basic-smithi/

failures tracked by

- https://tracker.ceph.com/issues/45423
- https://tracker.ceph.com/issues/50151

**Pull request merged**
