### PR TITLE
qa: decrease pgbench scale factor to 32 for postgresql database test

### PR DESCRIPTION
**Pull request by lxbsz**
The scale factor will depend on the node's performance and disk sizes being used to run the test, and 500 seems too large here as a common test case without knowing the nodes' configuration.

We should just follow the white-book:
https://github.com/ApsaraDB/PolarDB-for-PostgreSQL/blob/distributed/doc/polardb/benchmark.md

Fixes: https://tracker.ceph.com/issues/62700

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [x] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Review by batrick — APPROVED** [review]
I don't recall why I set the scaling factor that high. Assuming this works, I'm okay with it.

**Comment by vshankar** [comment]
> The scale factor will depend on the node's performance and disk sizes being used to run the test, and 500 seems too large here as a common test case without knowing the nodes' configuration.
> 
> We should just follow the white-book: https://github.com/ApsaraDB/PolarDB-for-PostgreSQL/blob/distributed/doc/polardb/benchmark.md

My sql-fu knowledge is very very limited -  I can include in my test branch and see if the "PQputline failed" failure is seen (I have no idea what it is BTW).

**Comment by batrick** [comment]
@lxbsz I think this is only necessary because of this bug: https://tracker.ceph.com/issues/62096 ; i.e. the rename churn is bringing the MDS to its knees such that the command cannot complete in expected time.

Since you will likely have a fix for that in the next day or so, I think we should hold off on merging this.

**Comment by lxbsz** [comment]
> @lxbsz I think this is only necessary because of this bug: https://tracker.ceph.com/issues/62096 ; i.e. the rename churn is bringing the MDS to its knees such that the command cannot complete in expected time.
> 
> Since you will likely have a fix for that in the next day or so, I think we should hold off on merging this.

I am okay with this. 

While from the tracker the failures, some none business with the `reinteragtion` issue as I fixed in https://tracker.ceph.com/issues/62096. And some together with the `rename` issue.

**Review by vshankar — APPROVED** [review]
https://tracker.ceph.com/projects/cephfs/wiki/Main#20-Sep-2023

**Pull request merged**
