### PR TITLE
msg/async/Protocol: unregister con from accept vs mark_down race

### PR DESCRIPTION
**Pull request by liewegas**
If we are accepting a connection and it gets marked down while we are
working on it, unregister it. Otherwise, we leave teh connection CLOSED
and registered and it interferes with the ability to open a new connection.

Fixes: http://tracker.ceph.com/issues/37778
Signed-off-by: Sage Weil <sage@redhat.com>

### CODE REVIEW

**Comment by liewegas** [comment]
before: http://pulpito.ceph.com/sage-2019-01-02_19:43:45-rados:multimon-master-distro-basic-smithi/
after: http://pulpito.ceph.com/sage-2019-01-03_13:15:57-rados:multimon-wip-sage3-testing-2019-01-02-1613-distro-basic-smithi/

**Comment by xiexingguo** [comment]
@liewegas We're suffering this issue back in Luminous. See https://github.com/ceph/ceph/pull/24218.

And here is another one: https://github.com/ceph/ceph/pull/25061

From @gregsfortytwo:

> Digging through the AsyncMessenger a bit:
> The only way AsyncConnections get marked CLOSED is in their _stop() function, which also invokes AsyncMessenger::unregister_conn() whenever that happens
AsyncMessenger::unregister_conn() is the only way for Connections to get into the deleted_conns set, and it inserts them unconditionally
conns.erase() is invoked in four places: shutdown_connections, reap_dead, and the here-changed _lookup_conn and accept_conn.
each of those 4 also invokes deleted_conns.erase() on the same connection.


So I doubt this is the right fix

CC: @gregsfortytwo  @Yan-waller

**Comment by liewegas** [comment]
ok. i'm reliably reproducing a different issue now with the multimon tests so I'm going to squash that one first.. but then i think i'll be able to reproduce this issue with full logs without much trouble.

**Comment by liewegas** [comment]
@xiexingguo I've reproduced this again and am confident there is a problem here.  we

A: drop teh lock
B: shutdown_connections 
A: register the connection
A: retake the lock
A: find that we were marked down and need to unregister

I think you're thinking of a race like

A: drop teh lock
A: register the connection
B: shutdown_connections 
A: retake the lock
A: find that we were marked down and need to unregister

...where yes, the shutdown will unregister the just-registered connection.

anyway, i'm easily reproducing this and this patch is making the failures go away.

**Comment by liewegas** [comment]
retest this please

**Comment by xiexingguo** [comment]
@liewegas I understand it now.

Thank you for catching this!

**Pull request merged**
