### PR TITLE
mgr/dashboard: Fix modals for Identifying Device and Editing O…

### PR DESCRIPTION
**Pull request by votdev**
Fixes: https://tracker.ceph.com/issues/43544

Signed-off-by: Volker Theile <vtheile@suse.com>

## Checklist
- [x] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by votdev** [comment]
jenkins test dashboard

**Comment by tspmelo** [comment]
Could you rename you commit to:
`mgr/dashboard: Fix modals for Identifying Device and Editing OSD`
or 
`mgr/dashboard: Fix Identifying Device and Editing OSD  modals`

**Comment by votdev** [comment]
jenkins test dashboard

**Comment by votdev** [comment]
jenkins test dashboard

**Comment by votdev** [comment]
jenkins test dashboard

**Pull request merged**
