### PR TITLE
cephadm: make host add failure message more friendly

### PR DESCRIPTION
**Pull request by pcuzner**
When a host add fails, the output was showing passed
and failed checks. This patch uses an ERROR prefix for
all failed checks, and then filters on them when showing
the result, so the admin sees only the failed items. The
text has also been tidied up to remove the [] within a
[] syntax

Signed-off-by: Paul Cuzner <pcuzner@redhat.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by pcuzner** [comment]
This PR changes the failure out from 
<pre>
[ceph: root@maint-1 /]# ceph orch host add maint-4                                                                                      
Error EINVAL: New host maint-4 (maint-4) failed check: ['systemctl is present', 'Unit chronyd.service is enabled and running', 'Hostname "maint-4" matches what is expected.', "ERROR: Unable to locate any of ['podman', 'docker']", 'lvcreate binary does not appear to be ins
talled', 'hostname "maint-4.storage.lab" does not match expected hostname "maint-4"'] 
</pre>
to 
<pre>
[ceph: root@maint-1 /]# ceph orch host add maint-4
Error EINVAL: New host maint-4 (maint-4) failed check(s): ['Unable to locate a supported container engine (podman or docker)', 'lvcreate binary does not appear to be installed', 'hostname "maint-4.storage.lab" does not match expected hostname "maint-4"']
</pre>

**Review by jmolmo — APPROVED** [review]

**Review by sebastian-philipp — COMMENTED** [review]
which problem do you try to circumvent here? If I read this right, you need to actually print structured output?

**Comment by pcuzner** [comment]
@sebastian-philipp the problem I'm trying to fix is to remove the output in the error message from tests that passed - since we were saiying the add host failed, then supplied a list that starts with non-errors - which to my mind is pointless.
I've provided before and after examples above - if we have an error we should be clear what the errors are and not mix them in with success messages.

**Review by Daniel-Pivonka — APPROVED** [review]

**Comment by sebastian-philipp** [comment]
https://pulpito.ceph.com/swagner-2021-01-07_14:03:38-rados:cephadm-wip-swagner-testing-2021-01-07-1213-distro-basic-smithi/

* https://tracker.ceph.com/issues/48799
* https://tracker.ceph.com/issues/48715
* https://tracker.ceph.com/issues/48142

**Comment by sebastian-philipp** [comment]
whoops. misclick on the merge button without the reviewed-by lines.

**Pull request merged**
