### PR TITLE
crimson/os/seastore: refine seastore and transaction_manager logs, cleanups

### PR DESCRIPTION
**Pull request by cyx1231st**
Follow up https://github.com/ceph/ceph/pull/59506

This should make the debug logs easier to understand about what SeaStore is doing.

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [x] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Review by Matan-B — APPROVED** [review]

**Comment by Matan-B** [comment]
```
/home/jenkins-build/build/workspace/ceph-pull-requests/src/test/crimson/seastore/test_seastore.cc:537:18: error: 'get_objs_range' is a private member of 'crimson::os::seastore::SeaStore'
        return seastore.get_objs_range(coll, 0).temp_end;
                        ^
```

**Comment by cyx1231st** [comment]
^ Dropped the incorrect change.

**Comment by cyx1231st** [comment]
make check link failed -- FAILED: bin/unittest-seastore 
```
lib/libcrimson-seastore.a(seastore.cc.o):(.data.rel.ro._ZTVN7seastar6logger17lambda_log_writerIZNS0_3logIJPvmRKPKcRKmS9_RmRKjEEEvNS_9log_levelENS0_11format_infoEDpOT_EUlNS_8internal7log_buf17inserter_iteratorEE_EE[_ZTVN7seastar6logger17lambda_log_writerIZNS0_3logIJPvmRKPKcRKmS9_RmRKjEEEvNS_9log_levelENS0_11format_infoEDpOT_EUlNS_8internal7log_buf17inserter_iteratorEE_EE]+0x20): undefined reference to `seastar::logger::lambda_log_writer<seastar::logger::log<void*, unsigned long, char const* const&, unsigned long const&, unsigned long const&, unsigned long&, unsigned int const&>(seastar::log_level, seastar::logger::format_info, void*&&, unsigned long&&, char const* const&, unsigned long const&, unsigned long const&, unsigned long&, unsigned int const&)::{lambda(seastar::internal::log_buf::inserter_iterator)#1}>::operator()(seastar::internal::log_buf::inserter_iterator)'
```

Local build unittest-seastore is successful, though.

**Comment by cyx1231st** [comment]
Identified an incorrect log.

**Comment by cyx1231st** [comment]
jenkins test make check

**Comment by cyx1231st** [comment]
With https://github.com/ceph/ceph/pull/59692/commits/3add76611a441dacd74656de8f32efc73a698d92, the make check has failures:
```
...
/usr/bin/ld: /usr/bin/ld: DWARF error: invalid or unhandled FORM value: 0x23
lib/libcrimson-seastore.a(seastore.cc.o):(.data.rel.ro._ZTVN7seastar6logger17lambda_log_writerIZNS0_3logIJPvmRKPKcRKmS9_RmRKjSA_SA_SA_EEEvNS_9log_levelENS0_11format_infoEDpOT_EUlNS_8internal7log_buf17inserter_iteratorEE_EE[_ZTVN7seastar6logger17lambda_log_writerIZNS0_3logIJPvmRKPKcRKmS9_RmRKjSA_SA_SA_EEEvNS_9log_levelENS0_11format_infoEDpOT_EUlNS_8internal7log_buf17inserter_iteratorEE_EE]+0x20): undefined reference to `seastar::logger::lambda_log_writer<seastar::logger::log<void*, unsigned long, char const* const&, unsigned long const&, unsigned long const&, unsigned long&, unsigned int const&, unsigned long&, unsigned long&, unsigned long&>(seastar::log_level, seastar::logger::format_info, void*&&, unsigned long&&, char const* const&, unsigned long const&, unsigned long const&, unsigned long&, unsigned int const&, unsigned long&, unsigned long&, unsigned long&)::{lambda(seastar::internal::log_buf::inserter_iterator)#1}>::operator()(seastar::internal::log_buf::inserter_iterator)'
/usr/bin/ld: lib/libcrimson-seastore.a(seastore.cc.o):(.data.rel.ro._ZTVN7seastar6logger17lambda_log_writerIZNS0_3logIJPvmRKPKcRKmS9_RmRKjSA_SA_EEEvNS_9log_levelENS0_11format_infoEDpOT_EUlNS_8internal7log_buf17inserter_iteratorEE_EE[_ZTVN7seastar6logger17lambda_log_writerIZNS0_3logIJPvmRKPKcRKmS9_RmRKjSA_SA_EEEvNS_9log_levelENS0_11format_infoEDpOT_EUlNS_8internal7log_buf17inserter_iteratorEE_EE]+0x20): undefined reference to `seastar::logger::lambda_log_writer<seastar::logger::log<void*, unsigned long, char const* const&, unsigned long const&, unsigned long const&, unsigned long&, unsigned int const&, unsigned long&, unsigned long&>(seastar::log_level, seastar::logger::format_info, void*&&, unsigned long&&, char const* const&, unsigned long const&, unsigned long const&, unsigned long&, unsigned int const&, unsigned long&, unsigned long&)::{lambda(seastar::internal::log_buf::inserter_iterator)#1}>::operator()(seastar::internal::log_buf::inserter_iterator)'
...
```

In short, the signatures are:
* `void*, unsigned long, char const* const&, unsigned long const&, unsigned long const&, unsigned long&, unsigned int const&, unsigned long&, unsigned long&, unsigned long&`
* `void*, unsigned long, char const* const&, unsigned long const&, unsigned long const&, unsigned long&, unsigned int const&, unsigned long&, unsigned long&`.

They matches the special signatures introduced by the investigation commit, meaning they are directly related to the linkage issue from make check.

However, they seem to be just simple logs, and my local environment (gcc 11.3.0) doesn't hit into this issue, suggesting this is compiler specific.

**Comment by cyx1231st** [comment]
jenkins test make check

**Comment by cyx1231st** [comment]
^ `core` related change is trivial -- add some formatters in `osd_types_fmt.h`, see https://github.com/ceph/ceph/pull/59692/commits/9475196b5b94a285ec64cd0bd8be46dc0ad6ce5b

**Comment by cyx1231st** [comment]
changeset since approve:
* more cleanups in seastore.h/cc
* workaround the linkage issue: https://github.com/ceph/ceph/pull/59692/commits/cd73c09e4cebc8977787e5a9bdf2e2e4d547f815

**Comment by cyx1231st** [comment]
jenkins test api

**Comment by cyx1231st** [comment]
jenkins test api

**Comment by cyx1231st** [comment]
jenkins test api

**Comment by cyx1231st** [comment]
Changeset: fixed a lambda capture issue in `SeaStore::Shard::_do_transaction_step()`.

**Comment by Matan-B** [comment]
jenkins test api

**Comment by cyx1231st** [comment]
Test results at: https://pulpito.ceph.com/yingxin-2024-10-09_01:27:28-crimson-rados-wip-yingxin-testing-2024-10-08-last-main-2-distro-default-smithi/

Apart from infrastructure failures, all known issue:
* 7940478/7940479: https://tracker.ceph.com/issues/66852

**Pull request merged**
