### PR TITLE
AsyncMessenger: Implement slab memory pool per worker

### PR DESCRIPTION
**Pull request by yuyuyu101**
We know lots of memory allocations happened in messenger layer, rely on system or generic memory library will cause lots of redundant cpu times. Actually async msgr has significant characteristics for memory usage. It will only malloc memory in local thread, then other threads will free them.

Here I implement a special slab memory pool which only allow alloc/reclaim locally, permitting free remotely.

### CODE REVIEW

**Comment by yuyuyu101** [comment]
@liewegas sorry for the late response, I perf with this PR. Because of fast dispatch limited(mentioned previously), I can't find outstanding improvement with iops. But it actually reduce malloc/free to zero for message data. It could help for memory fragmentization and reduce cpu utils

**Comment by yuyuyu101** [comment]
@liewegas 
tested on 
http://pulpito.ceph.com/haomai-2015-11-24_23:30:51-rados-wip-13521-distro-basic-multi/

the failed jobs I guess happened by accident. 
So I reran the failed tests:
http://pulpito.ceph.com/haomai-2015-11-25_07:06:08-rados-wip-13521-distro-basic-multi/
http://pulpito.ceph.com/haomai-2015-11-25_07:04:49-rados-wip-13521-distro-basic-multi/
All seemed good.

My test result showed a great cpu util down via "perf top -t {async thread id}"

**Comment by liewegas** [comment]
Can you quantify the CPU reduction?

(I'm just hesitant because this is a big addition of complexity.)

**Comment by liewegas** [comment]
@athanatos @mattbenjamin Can you guys take a look?

**Comment by yuyuyu101** [comment]
@liewegas 

Two osds and each has one ssd. I adjust async worker to 1 to make single thread cpu util more outstanding. Then I run fio-rbd(limit iops in 5k to keep cpu util stable) and see "top -Hp [osd pid]". The async thread will be the top cpu utilization thread.

With slab alloc, the cpu util is 47.8% compared to 49.5% without slab. And actually this thread consume 6-10% cpu util on malloc/free. This PR only resolve data alloc/free, metadata like message structure is another big one.

**Comment by athanatos** [comment]
If we can't identify a performance improvement, it's not worth moving to a slab allocator here.

**Pull request closed without merging**
