### PR TITLE
crimson/osd: fixes and cleanups around multi-core OSD

### PR DESCRIPTION
**Pull request by cyx1231st**
Follow up https://github.com/ceph/ceph/pull/51147

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Review by liu-chunmei — APPROVED** [review]

**Comment by cyx1231st** [comment]
I'm able to run tests now.

Waiting for https://pulpito.ceph.com/yingxin-2023-07-04_09:04:25-crimson-rados-wip-yingxin-multi-core-crimson-osd-cleanup-1-distro-default-smithi/

**Comment by cyx1231st** [comment]
The above test result looks good.

**Review by athanatos — APPROVED** [review]

**Comment by cyx1231st** [comment]
jenkins test api

**Comment by cyx1231st** [comment]
jenkins test docs

**Comment by cyx1231st** [comment]
Does it look good to you @Matan-B ?

**Comment by Matan-B** [comment]
> Does it look good to you @Matan-B ?

Yes, once API tests will pass, we can merge this based on https://pulpito.ceph.com/yingxin-2023-07-04_09:04:25-crimson-rados-wip-yingxin-multi-core-crimson-osd-cleanup-1-distro-default-smithi/

**Comment by Matan-B** [comment]
jenkins test api

**Comment by Matan-B** [comment]
Unless I'm missing something, I think that the tests run on main (without the changes of this PR) by mistake:
https://github.com/ceph/ceph-ci/commits/wip-yingxin-multi-core-crimson-osd-cleanup-1
It looks like the only diff is a blank commit (f60eec2) which is the one used by the running jobs.

**Comment by cyx1231st** [comment]
> It looks like the only diff is a blank commit (f60eec2) which is the one used by the running jobs.

Ah, I was wondering why I need to add a blank commit to trigger a build ... it is indeed a wrong branch.

I'll test again, sorry about the mistake, and thanks to point it out!

**Comment by Matan-B** [comment]
jenkins test api

**Comment by cyx1231st** [comment]
> Will be merging based on
https://pulpito.ceph.com/yingxin-2023-07-10_06:20:40-crimson-rados-wip-yingxin-multi-core-crimson-osd-cleanup-2-distro-default-smithi/

https://github.com/ceph/ceph-ci/commits/wip-yingxin-multi-core-crimson-osd-cleanup-2 should be correct now.

**Comment by cyx1231st** [comment]
jenkins test api

**Pull request merged**
