### PR TITLE
msg/async: the ceph_abort is needless in handle_connect_msg

### PR DESCRIPTION
**Pull request by shangfufei**
Signed-off-by: shangfufei <shangfufei@inspur.com>

### CODE REVIEW

**Comment by yuyuyu101** [comment]
I'm not sure whether we need to remove it? it could be a safe guard?

**Comment by tchaikov** [comment]
probably we can replace it with `assert(0)`? as it is dead code.

**Comment by yuyuyu101** [comment]
I'm not sure the different potential meaning between ceph_abort and assert(0)

**Comment by tchaikov** [comment]
they are semantically different now. but in future, `ceph_assert()` will not be optimised out, while `assert()` will be.

**Comment by liewegas** [comment]
http://pulpito.ceph.com/sage-2018-05-14_22:14:39-rados-wip-sage3-testing-2018-05-14-1429-distro-basic-smithi/
http://pulpito.ceph.com/sage-2018-05-16_15:59:20-rados-wip-sage3-testing-2018-05-14-1429-distro-basic-smithi/

failures are http://tracker.ceph.com/issues/24150

**Pull request merged**
