### PR TITLE
One Rados Handle to Rule Them All

### PR DESCRIPTION
**Pull request by adamemerson**
Remove deprecated `num_rados_handles` option and code to support it.

### CODE REVIEW

**Comment by cbodley** [comment]
thanks @adamemerson! can you please remove the `rgw num rados handles` section from doc/radosgw/config-ref.rst?

i'd also like to see some kind of documentation for users that relied on handles > 0, so they know to adjust their objecter tunings accordingly - i think PendingReleaseNotes is probably the right place for that

**Comment by adamemerson** [comment]
@cbodley Do we know what advice to give them? (Or who to ask? Should I mail Kyle Bader or do we have something written up?)

**Comment by cbodley** [comment]
@adamemerson you can just say that given rgw_num_rados_handles=N, they should multiply their objecter_inflight_ops and objecter_inflight_op_bytes by N to get the same overall throttle tunings

**Comment by adamemerson** [comment]
@cbodley All right! It is done.

**Comment by cbodley** [comment]
http://pulpito.ceph.com/cbodley-2019-03-22_16:15:39-rgw-wip-cbodley-testing-distro-basic-smithi/

**Pull request merged**
