### PR TITLE
tests/fio: fix build failures and ensure this is covered by run-make-check.sh

### PR DESCRIPTION
**Pull request by ifed01**

### CODE REVIEW

**Comment by tchaikov** [comment]
```
                 from /home/jenkins-build/build/workspace/ceph-pull-requests/src/test/fio/fio_ceph_objectstore.cc:23:
/home/jenkins-build/build/workspace/ceph-pull-requests/build/src/fio/diskutil.h: In function 'void disk_util_mod(disk_util*, int)':
/home/jenkins-build/build/workspace/ceph-pull-requests/build/src/fio/diskutil.h:84:12: error: cannot convert 'flist_head' to 'const int' in initialization
    slave = flist_entry(n, struct disk_util, slavelist);
            ^
/home/jenkins-build/build/workspace/ceph-pull-requests/build/src/fio/diskutil.h:84:12: error: '__mptr' was not declared in this scope
    slave = flist_entry(n, struct disk_util, slavelist);
            ^
/home/jenkins-build/build/workspace/ceph-pull-requests/build/src/fio/diskutil.h:84:12: note: suggested alternative: '__m128'
```

**Comment by ifed01** [comment]
retest this please

**Comment by ifed01** [comment]
retest this please

**Comment by ifed01** [comment]
retest this please

**Comment by ifed01** [comment]
retest this please

**Comment by ifed01** [comment]
retest this please

**Comment by ifed01** [comment]
retest this please

**Comment by ifed01** [comment]
retest this please

**Comment by ifed01** [comment]
retest this please

**Comment by ifed01** [comment]
retest this please

**Comment by ifed01** [comment]
retest this please

**Comment by ifed01** [comment]
retest this please

**Comment by ifed01** [comment]
retest this please

**Comment by ifed01** [comment]
retest this please

**Comment by ifed01** [comment]
retest this please

**Comment by ifed01** [comment]
retest this please

**Comment by tchaikov** [comment]
@ifed01 probably we should instead fix `fio.h` -- to apply following patch
```diff
diff --git a/fio.h b/fio.h
index 4ce4991b..46c49d56 100644
--- a/fio.h
+++ b/fio.h
@@ -14,6 +14,10 @@
 #include <inttypes.h>
 #include <assert.h>

+#ifdef __cplusplus
+#define typeof decltype
+#endif
+
 #include "compiler/compiler.h"
 #include "thread_options.h"
 #include "flist.h"
```
because `typeof` is a GNU extension. or simply replace it with `__typeof__` , as suggested by https://gcc.gnu.org/onlinedocs/gcc/Typeof.html

**Comment by tchaikov** [comment]
@ifed01 i posting #23231 to pick up the change in FIO upstream.

**Comment by ifed01** [comment]
@tchaikov - thanks for looking into that. One strange thing is that occasionally I could see successful build for either "make check" or "make check(arm64)). So it looks like the build environment isn't the same for all the building hosts...

**Comment by ifed01** [comment]
no, it was that original fio build error which was flapping...

**Pull request closed without merging**
