### PR TITLE
fix the autotools and cmake build (the new fusestore needs libfuse)

### PR DESCRIPTION
**Pull request by tchaikov**

### CODE REVIEW

**Comment by branch-predictor** [comment]
Autotools part works for me regardless of whether --without-fuse is used or not.

Reviewed-by: Piotr Dałek piotr.dalek@ts.fujitsu.com

**Comment by tchaikov** [comment]
@cbodley could you help review the cmake changes?

@branch-predictor has helped reviewed and tested the autotools changes.

@liewegas does this make sense to disable fusestore if libfuse-dev/fuse-devel is not installed?

**Comment by tchaikov** [comment]
@cbodley as we discussed over irc, i dropped the change to `Findfuse.cmake`.

**Comment by liewegas** [comment]
@tchaikov Yeah this makes sense. Sorry I missed this!

**Comment by cbodley** [comment]
@tchaikov thanks. looks good on the cmake side :+1:

**Pull request merged**
