### PR TITLE
octopus: mgr/dashboard: Asynchronous unique username validation for User Component

### PR DESCRIPTION
**Pull request by nizamial09**
backport tracker: https://tracker.ceph.com/issues/45346

---

backport of https://github.com/ceph/ceph/pull/34587
parent tracker: https://tracker.ceph.com/issues/36375

this backport was staged using ceph-backport.sh version 15.1.1.389
find the latest version at https://github.com/ceph/ceph/blob/master/src/script/ceph-backport.sh

### CODE REVIEW

**Comment by nizamial09** [comment]
jenkins test make check

**Comment by nizamial09** [comment]
jenkins test dashboard

**Comment by nizamial09** [comment]
jenkins test dashboard

**Comment by nizamial09** [comment]
jenkins test dashboard

**Comment by tspmelo** [comment]
we might need to wait for cypress to be backported for this to pass dashboard tests: https://github.com/ceph/ceph/pull/34910

**Comment by nizamial09** [comment]
> we might need to wait for cypress to be backported for this to pass dashboard tests: #34910

I was wondering about this. Thank you :)

**Comment by nizamial09** [comment]
jenkins test dashboard

**Comment by smithfarm** [comment]
@callithea #34910 has been merged. Could you re-trigger the dashboard Jenkins tests in this PR?

**Comment by smithfarm** [comment]
jenkins test docs

**Comment by smithfarm** [comment]
jenkins test docs

**Comment by smithfarm** [comment]
jenkins test dashboard backend

**Comment by smithfarm** [comment]
@callithea Never mind, as @tspmelo informed me, the docs and dashboard failures are due to https://status.sepia.ceph.com/incidents/3860

**Comment by callithea** [comment]
@smithfarm since this is PR only includes frontend changes for dashboard, we do not need a QA run, do we?

**Comment by smithfarm** [comment]
@callithea I don't know :-) As far as I'm concerned, the dashboard team has the authority to merge it whenever they please.

**Comment by callithea** [comment]
> @callithea I don't know :-) As far as I'm concerned, the dashboard team has the authority to merge it whenever they please.

Unfortunately we do not have the permissions to merge it (@LenzGr tried it) since the required `Doc: build check` is failing. As discussed with @tchaikov on IRC we can add the `ready-to-merge` label to the ready-to-merge PRs and @tchaikov will try to get back to those PRs to re-run the tests once the issue is gone or we could merge it if we believe the tests pass locally (but as mentioned before, this is does not work for dashboard team).

**Comment by tspmelo** [comment]
jenkins test dashboard

**Comment by smithfarm** [comment]
@ceph/backport-admins

**Comment by callithea** [comment]
jenkins test dashboard

**Comment by yuriw** [comment]
[wip-yuri2-testing-2020-06-19-1559-octopus](https://trello.com/c/qPcs7BEX/940-wip-yuri2-testing-2020-06-19-1559-octopus)

**Comment by nizamial09** [comment]
jenkins test dashboard

**Comment by nizamial09** [comment]
jenkins test dashboard

**Comment by callithea** [comment]
jenkins test docs

**Comment by callithea** [comment]
- [QA run](http://pulpito.front.sepia.ceph.com/yuriw-2020-06-22_17:53:59-rados-wip-yuri2-testing-2020-06-19-1559-octopus-distro-basic-smithi/) [5 failed/2 dead/1 passed] 
The failures are not related to this PR (seems like infra issues)

**Pull request merged**
