### PR TITLE
doc/cephadm/host-management: add service spec link

### PR DESCRIPTION
**Pull request by tnyeanderson**
The old "(below)" text is not accurate, the service spec definition is not in the same file at this point in time. This commit adds a ref link to the actual service specification section.

**This is my first time writing `rst` so please make sure I did it right before merging. Thank you!**

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [x] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [x] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by zdover23** [comment]
>This is my first time writing rst so please make sure I did it right before merging. Thank you!

**Comment by zdover23** [comment]
@tnyeanderson 

> This is my first time writing rst so please make sure I did it right before merging. Thank you!

I've been monitoring your work. You got it right. Any time you need help, you can ask me on Slack or at zac.dover@proton.me. Also, hi. I'm Zac. I'm the upstream docs lead for the Ceph project.

**Comment by tnyeanderson** [comment]
Nice to meet you Zac! Appreciate you taking a look and being available for guidance. As I make my way through my own Ceph deployments here, I'll try to contribute where I can :)

**Comment by zdover23** [comment]
> Nice to meet you Zac! Appreciate you taking a look and being available for guidance. As I make my way through my own Ceph deployments here, I'll try to contribute where I can :)

As you work through the documentation, you will undoubtedly encounter many things that could be more elegantly worded or, as in this case, could mislead a reader about the behavior of some aspect of Ceph. I encourage to you make note of those instances here: https://pad.ceph.com/p/Report_Documentation_Bugs and I will, when time permits, get to them. You're welcome to raise PRs yourself in those instances, too, but as you probably have already realized, this stuff takes way more time than you might initially think.

**Comment by tnyeanderson** [comment]
I'll definitely keep that reporting tool in mind, especially for any significant changes or suggestions... Luckily, I'm used to submitting PRs and am getting better with ceph's commit standards and PR requirements ;) I'm also used to PRs sitting for long periods of time without review as I know project maintainers can get very *very* busy so no worries there either. Regardless, I'm happy to contribute by trying to take the simple fixes off your plate when I can!

**Review by zdover23 — APPROVED** [review]

**Comment by zdover23** [comment]
https://github.com/ceph/ceph/pull/50254 - Quincy backport
https://github.com/ceph/ceph/pull/50255 - Pacific backport

**Pull request merged**
