### PR TITLE
doc: updated reference link for CloudStack disk offering

### PR DESCRIPTION
**Pull request by falcon78921**
- [ ] References tracker ticket
- [x] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

Signed-off-by: James McClune <jmcclune@mcclunetechnologies.net>

### CODE REVIEW

**Comment by falcon78921** [comment]
This caused doc build failure:
~~~
Exception occurred:
  File "/home/jenkins-build/build/workspace/ceph-pr-docs/build-doc/virtualenv/local/lib/python2.7/site-packages/breathe/renderer/filter.py", line 320, in __call__
    raise e
AttributeError: 'str' object has no attribute 'node_type'
~~~

**Comment by gregsfortytwo** [comment]
Jenkins rebuild docs

**Comment by gregsfortytwo** [comment]
Jenkins retest this please

**Comment by falcon78921** [comment]
Closing for #27713

**Pull request closed without merging**
