### PR TITLE
rgw: Make OPA signle source of truth on OPA integration

### PR DESCRIPTION
**Pull request by clwluvw**
Add OPA policy url for sending new policies created by bucket policy to OPA server
I think it's so raw and I have no more idea what else should be done with this but the main idea of this pull request is to add a feature for sending new policies that created with bucket policybucket policy command by clients to OPA server.
Thanks.

Signed-off-by: Seena Fallah seenafallah@gmail.com

### CODE REVIEW

**Comment by mattbenjamin** [comment]
This is an interesting change.  Can you illustrate what OPA will do with the policy doc we send?

**Comment by clwluvw** [comment]
@mattbenjamin OPA will apply new policies which we send to its database.

**Comment by clwluvw** [comment]
@mattbenjamin I think it's better to send update request to OPA when policy applied to Ceph. Can you send me a code line where you think we can put it?

**Comment by clwluvw** [comment]
@mattbenjamin What about the last commit?

**Comment by clwluvw** [comment]
@liewegas @cbodley any idea about this pull request?

**Comment by clwluvw** [comment]
@tchaikov any idea about this pull request?

**Comment by mattbenjamin** [comment]
@clwluvw this is definitely better, but I'd like to understand better if the new behavior to mirror our policy to this URL is what OPA integration originally envisioned.  It troubles us that we're potentially sending two sync requests to (different) OPA endpoints when policy is being set--and then I wondered, shouldn't OPA get the policy in its authz step anyway?  Then if it wanted to save the policy, the agent could do so?

**Comment by clwluvw** [comment]
@mattbenjamin When we use OPA as an authorization server, all the authorization policies are set in OPA database and we want to be able to add policies directly to OPA too. So It's needed to store all the policies in OPA server and if client (s3 client) send a bucket policy request to RGW we want to apply it to our OPA Server to be store in out database.
The two OPA endpoint is just a feature that if someone wants to apply policies with different API endpoint. It can be merge with OPA endpoint and implement PUT and DELETE method for OPA endpoint for setting and deleting policies.

As I see I have use wrong method for policies in my code. bucket policy isn't in `req_state` and I should add it. Can you hint me how can I get bucket policy based on `bucket_name` from the code? :)

**Comment by clwluvw** [comment]
@mattbenjamin I have fixed the bug on sending bucket ACL instead of bucket policy to OPA. How is it now?

**Comment by clwluvw** [comment]
@mattbenjamin I have called `rgw_send_bucket_policy_to_opa` in `rgw_op` for because the bucket policy is in there so it's better to use it there and I think it's so cleaner that using in `process_request`

**Comment by clwluvw** [comment]
@mattbenjamin We are missing this feature in our product and waiting for your review :)))

**Comment by clwluvw** [comment]
@mattbenjamin I think it's missing feature in Ceph that we can't have bucket policies on OPA server. Do you need any further information that I can help with it?

**Comment by mattbenjamin** [comment]
@clwluvw hi seena; as a reviewer and someone who was involved with the original discussions with the Styra team on OPA integation, I'm really not clear whether the model this change is proposing is actually the intent of the OPA model--not being an OPA expert, there's plenty of room for gaps, but broadly, the OPA model and integration assumed that OPA was already the source of truth for authentication policy.  In that model, what is the intent of forwarding a (partial!) set of stored RGW bucket policy to OPA?  In general, Casey and I both want to have a larger discussion about how changes like this one play in the wider OPA community, as well as be able to participate in discussion about the model and whether it makes sense for RGW.  I think a good starting point would be an email thread CC'ing the Ceph dev list as well as OPA architects--further discussion conversationally could happen in RGW standups and in the weekly refactoring meeting, as well.

**Comment by clwluvw** [comment]
@mattbenjamin I have sent it to mailing list. Could you please ask the ones who should comment for this pull request?

**Comment by clwluvw** [comment]
rebased with master and used new user get_info method for user_info

**Comment by clwluvw** [comment]
jenkins test make check

**Comment by clwluvw** [comment]
Fixes: https://tracker.ceph.com/issues/44178
Signed-off-by: Seena Fallah seenafallah@gmail.com

**Pull request closed without merging**
