### PR TITLE
common: random: added a deduction guide to make using the function ob…

### PR DESCRIPTION
**Pull request by chardan**
Adds a deduction guide to make the function object interface a bit nicer.

Signed-off-by: Jesse Williamson <nerd.cpp@gmail.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [x] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`

</details>

### CODE REVIEW

**Comment by chardan** [comment]
Jenkins, retest this please.

**Comment by tchaikov** [comment]
jenkins test make check

**Comment by chardan** [comment]
Jenkins retest this please.

**Comment by tchaikov** [comment]
jenkins test make check

**Comment by chardan** [comment]
Jenkins make check.

**Comment by chardan** [comment]
Jenkins retest this please.

**Comment by chardan** [comment]
@tchaikov Look ok to you?

**Comment by chardan** [comment]
ping...

**Pull request merged**
