### PR TITLE
mon: prevent pools with snap metadata from being used as a tier (fix 11493)

### PR DESCRIPTION
**Pull request by liewegas**

### CODE REVIEW

**Comment by liewegas** [comment]
added a test

**Comment by athanatos** [comment]
https://github.com/ceph/ceph/tree/wip-11493 is rebased on master, disallows using an ec pool as a tier as well, and fixes the tests in test/librados/tier.cc to not fail with ENOTEMPTY.

**Comment by liewegas** [comment]
ah, yeah that branch looks even better.

**Comment by NUABO** [comment]
hi @liewegas 
I created two pools, and the information for ceph osd dump is:
>Pool 2 'cache' replicated size 3 min_size 1 crush_rule 1 object_hash rjenkins pg_num 32 pgp_num 32 last_change 57 flags hashpspool, noscrub, nodeep-scrub, replicatewriteback max_bytes 10737418240 stripe_width 0 application rbd
>Pool 4 'perf' replicated size 3 min_size 1 crush_rule 0 object_hash rjenkins pg_num 32 pgp_num 32 last_change 155 flags hashpspool, noscrub, nodeep-scrub, replicatewriteback max_bytes 10737418240 stripe_width 0 application rbd

When I create rbd in the cache pool and delete it, I did not create a snapshot, the ceph osd dump information of the cache pool is:
>Pool 2 'cache' replicated size 3 min_size 1 crush_rule 1 object_hash rjenkins pg_num 32 pgp_num 32 last_change 157 flags hashpspool, noscrub, nodeep-scrub, selfmanaged_snaps, replicatewriteback max_bytes 10737418240 stripe_width 0 application rbd removed_snaps [1~3]

I can't create a cache tier due to the presence of removed_snaps
[root@controller-3 ~]# ceph osd tier add perf cache --force-nonempty
Error ENOTEMPTY: tier pool 'cache' has snapshot state; it cannot be added as a tier without breaking the pool

I found a solution on the Internet from https://tracker.ceph.com/issues/12021, we can set "mon debug unsafe allow tier with nonempty snaps: true" to skip this judgment. But is this way safe? After I delete all the rbds in the cache, will there be any residual data?
I didn't find a way to submit a bug, so I can only explain it here, I am very sorry.

**Comment by liewegas** [comment]
@NUABO after you create and delete the RBD, can you show *both* pool's info? Thanks!

**Pull request closed without merging**
