### PR TITLE
hammer: clock skew report is incorrect by ceph health detail command

### PR DESCRIPTION
**Pull request by xiaoxichen**
http://tracker.ceph.com/issues/15024

### CODE REVIEW

**Comment by smithfarm** [comment]
@jecluis Please review

**Comment by smithfarm** [comment]
@xiaoxichen The commits are missing the "(cherry-picked from . . .)" line - this is added automatically which you provide the `-x` option to `git cherry-pick`. Sorry for the nit - can you please fix?

**Comment by xiaoxichen** [comment]
cherry-pick seems not cleanly, will fix it.

**Comment by smithfarm** [comment]
@xiaoxichen: Could you add to the commit messages a description of the conflicts and how you resolved them? This if debugging/forensics are necessary later, such descriptions can save a lot of time.

**Comment by xiaoxichen** [comment]
@smithfarm  see if it works for you.

**Comment by dachary** [comment]
@liewegas does this backport look good to merge ? It passed the hammer upgrade suite ( http://tracker.ceph.com/issues/14692#note-52 ) and the rados suite http://tracker.ceph.com/issues/14692#note-51).

**Pull request merged**
