### PR TITLE
mon/OSDMonitor: drop stale failure_info after a grace period

### PR DESCRIPTION
**Pull request by tchaikov**
## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by tchaikov** [comment]
#37068 is a better fix of https://tracker.ceph.com/issues/47380, so dropping the fix in this changeset. and repurpose this change set for a cleanup.

**Comment by tchaikov** [comment]
jenkins test make check

**Comment by tchaikov** [comment]
jenkins test api

**Comment by tchaikov** [comment]
jenkins test api

**Comment by tchaikov** [comment]
jenkins test api

**Comment by gregsfortytwo** [comment]
I'm not sure what your attempt at a solution looked like, but the fix for 47380 definitely needs to come from changing how the failure_report tracking interacts with messages and slow op reporting...

**Comment by tchaikov** [comment]
> I'm not sure what your attempt at a solution looked like, but the fix for 47380 definitely needs to come from changing how the failure_report tracking interacts with messages and slow op reporting...

my solution was to drop the stale failure info after a grace period. we would need to find a way to reply the original reporter if we follow your proposal. some times the report is routed by a peon, some time the report is directly received from an OSD. that's some troublesome part.

**Comment by tchaikov** [comment]
jenkins test make check

**Comment by tchaikov** [comment]
jenkins test make check

**Comment by tchaikov** [comment]
jenkins test api

**Comment by tchaikov** [comment]
discussed with @simon-rock offline. two things we need to watch out in this change

- need to limit the number of checked failure info in each tick, so we don't acquire the lock for too long.

**Comment by tchaikov** [comment]
jenkins test make check

**Comment by tchaikov** [comment]
jenkins test make check

**Comment by tchaikov** [comment]
jenkins test make check

**Review by liewegas — APPROVED** [review]
looks good! nice cleanup too

**Comment by tchaikov** [comment]
rebased against master.

**Comment by tchaikov** [comment]
- https://pulpito.ceph.com/kchai-2021-03-20_13:57:49-rados-wip-kefu2-testing-2021-03-20-1320-distro-basic-smithi/
- https://pulpito.ceph.com/kchai-2021-03-22_02:52:16-rados-wip-kefu2-testing-2021-03-21-2353-distro-basic-smithi/

failures tracked by

- https://tracker.ceph.com/issues/49916
- https://tracker.ceph.com/issues/49909

**Pull request merged**
