### PR TITLE
script: build-doc/serve-doc fixes

### PR DESCRIPTION
**Pull request by theanalyst**
`virtualenv` we create for docs would default to system default python which might be python3 in many OSes, this would fail eventually as we use the sphinx-ditaa module which errors out in py3. Also added a small print statement on the port we're serving in serve-doc

### CODE REVIEW

**Comment by theanalyst** [comment]
@tchaikov not sure if pybind for rados/rbd/rgw support py3 yet, if yes, then probably in future, we could fix the https://github.com/ceph/sphinx-ditaa to support py3

**Comment by tchaikov** [comment]
@theanalyst our pybinds do support py3. i am looking at sphinx-ditaa, maybe we can note this down in our tracker.

**Comment by theanalyst** [comment]
@tchaikov ack, created http://tracker.ceph.com/issues/19579

**Comment by tchaikov** [comment]
@theanalyst thanks!

**Pull request merged**
