### PR TITLE
squid: librbd: make diff-iterate in fast-diff mode aware of encryption

### PR DESCRIPTION
**Pull request by idryomov**
backport tracker: https://tracker.ceph.com/issues/66744

---

backport of https://github.com/ceph/ceph/pull/58201
parent tracker: https://tracker.ceph.com/issues/66570

### CODE REVIEW

**Comment by idryomov** [comment]
Temporarily based on https://github.com/ceph/ceph/pull/58212 to avoid conflicts in `src/test/librbd/test_librbd.cc`.

**Review by ajarr — APPROVED** [review]

**Comment by idryomov** [comment]
jenkins test api

**Comment by yuriw** [comment]
@idryomov pls merge when ready
it was tested ref: https://tracker.ceph.com/issues/66939#note-4

**Comment by idryomov** [comment]
Rebased after https://github.com/ceph/ceph/pull/58212 merged.

**Comment by idryomov** [comment]
jenkins test api

**Pull request merged**
