### PR TITLE
client: discard mds map if it is identical to ours

### PR DESCRIPTION
**Pull request by xiexingguo**
It is a pure waste.

Signed-off-by: xie xingguo <xie.xingguo@zte.com.cn>

### CODE REVIEW

**Comment by gregsfortytwo** [comment]
LGTM

**Comment by xiexingguo** [comment]
retest this please

**Comment by xiexingguo** [comment]
Tested at:
http://www.daisycloud.org:9091/xxg-2016-06-23_20:47:59-fs-wip-xxg-testing-fs-2016-06-23---basic-plana/

**Comment by gregsfortytwo** [comment]
http://pulpito.ceph.com/gregf-2016-06-27_22:02:48-fs-greg-fs-testing-627---basic-mira/ looks good, just 3 infra timeouts

**Pull request merged**
