### PR TITLE
mds: check mds up before calling MDSMap::get_mds_info

### PR DESCRIPTION
**Pull request by ukernel**
Fixes: #12676
Signed-off-by: Yan, Zheng <zyan@redhat.com>

### CODE REVIEW

**Comment by liewegas** [comment]
why doesn't MDS::is_stale_message() catch this?  is it on a retry list or something?

would it make sense to call is_stale_message() here instead of checking only for is_up()?

**Comment by ukernel** [comment]
it's on MDS::tick.

**Comment by gregsfortytwo** [comment]
@liewegas this isn't an incoming message; we're generating our own state incorrectly. Or am I missing something else with that question?

**Comment by gregsfortytwo** [comment]
@ukernel the other MDS will discover we don't have the trimmed inodes in cache during its rejoin phase, right? Are there any coherency problems we might have by dropping it arbitrarily?

**Comment by ukernel** [comment]
@gregsfortytwo  this code is for stopping MDS, has nothing do with rejoin phase.

**Comment by gregsfortytwo** [comment]
Oh duh.

**Pull request merged**
