### PR TITLE
rgw: Get canonical storage class when storage class is empty in

### PR DESCRIPTION
**Pull request by xijiacun**
lifecycle configuration.

Fixes: https://tracker.ceph.com/issues/53878
Signed-off-by: zhiming zhang <zhangzhm1@chinatelecom.cn>

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by xijiacun** [comment]
@cbodley Please help to review the code. Thanks

**Comment by xijiacun** [comment]
@cbodley @mattbenjamin Please help to review the code. Thanks

**Review by cbodley — APPROVED** [review]

**Comment by ivancich** [comment]
Teuthology Results:
* https://pulpito.ceph.com/ivancich-2022-08-31_23:19:38-rgw-wip-eric-testing-1-distro-default-smithi/
* https://pulpito.ceph.com/ivancich-2022-08-31_23:19:11-rgw-wip-eric-testing-1-distro-default-smithi/

**Comment by ivancich** [comment]
@xijiacun and @mattbenjamin -- the tracker lists no backports, yet this reads like a bug. I've moved the tracker to resolved, but please update the tracker with backports and status to Pending Backport if they're needed. Thanks!

**Pull request merged**
