### PR TITLE
Update layout.rst

### PR DESCRIPTION
**Pull request by ypdai**
doc: modify the wrong word "defails" to "details".

Signed-off-by: ypdai <self19900924@gmail.com>

- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by LenzGr** [comment]
Thank you for your contribution! Would you mind signing your git commit and prefix the commit description with `doc: `, to match the required format?

Please see https://github.com/ceph/ceph/blob/master/SubmittingPatches.rst for details. You don't need to close this PR, just amend the commit in your branch and force-push the new changeset into your remote repository.

**Comment by ypdai** [comment]
> Thank you for your contribution! Would you mind signing your git commit and prefix the commit description with `doc: `, to match the required format?
> 
> Please see https://github.com/ceph/ceph/blob/master/SubmittingPatches.rst for details. You don't need to close this PR, just amend the commit in your branch and force-push the new changeset into your remote repository.

OK，thanks for your reminder. i have already done this.

**Comment by LenzGr** [comment]
> OK，thanks for your reminder. i have already done this.

Thank you! Some remaining small requests in order to get this merged: can you please squash your git commits into a single changeset and update the PR description accordingly?

Also, I wonder if it's necessary to change the line breaking for just fixing a single typo (resulting in a larger diff), but that's really a minor nit.

**Comment by ypdai** [comment]
@LenzGr @gregsfortytwo please take a review. thx.

**Pull request merged**
