### PR TITLE
hammer: When logging to a file fails, ceph logs excessively to stderr

### PR DESCRIPTION
**Pull request by xiaoxichen**
http://tracker.ceph.com/issues/15081

### CODE REVIEW

**Comment by dachary** [comment]
@xiaoxichen could you please rebase & repush to get a clean run ?

**Comment by dachary** [comment]
test this please

**Comment by dachary** [comment]
the logic of the _flush function in hammer is substantially different from master. this backport needs more work. When logging to stderr, it shows this:
<pre>
2016-04-05T14:32:37.211 INFO:teuthology.orchestra.run.target167114250159.stderr:2016-04-05 14:32:37.141552 7fa8cf8ad700 10
2016-04-05T14:32:37.211 INFO:teuthology.orchestra.run.target167114250159.stderr:2016-04-05 14:32:37.141932 7fa8cf8ad700  1
2016-04-05T14:32:37.211 INFO:teuthology.orchestra.run.target167114250159.stderr:2016-04-05 14:32:37.142110 7fa8cf8ad700  1
2016-04-05T14:32:37.219 INFO:teuthology.orchestra.run.target167114250159.stderr:2016-04-05 14:32:37.143175 7fa8cf8ad700  1
2016-04-05T14:32:37.219 INFO:teuthology.orchestra.run.target167114250159.stderr:2016-04-05 14:32:37.143412 7fa8cf8ad700  1
2016-04-05T14:32:37.219 INFO:teuthology.orchestra.run.target167114250159.stderr:2016-04-05 14:32:37.143422 7fa8cf8ad700  1
2016-04-05T14:32:37.219 INFO:teuthology.orchestra.run.target167114250159.stderr:2016-04-05 14:32:37.143718 7fa8cf8ad700 10
2016-04-05T14:32:37.219 INFO:teuthology.orchestra.run.target167114250159.stderr:2016-04-05 14:32:37.143865 7fa8cf8ad700 10
2016-04-05T14:32:37.219 INFO:teuthology.orchestra.run.target167114250159.stderr:2016-04-05 14:32:37.145114 7fa8cf8ad700 10
etc.
</pre>
i.e. only the beginning of the buffer but not the actual message, which is not very helpful :-)

**Comment by xiaoxichen** [comment]
@dachary ,oops, i will follow

**Comment by xiaoxichen** [comment]
@dachary ,make check passed, could we remove the DMN and try in the next intergration branch?

**Comment by dachary** [comment]
@xiaoxichen yes. Given the extent of the change, you may want to heavily comment on why you resolved the conflict this way.

**Comment by xiaoxichen** [comment]
@dachary ,done. Removed DMN as bot passed.

**Comment by athanatos** [comment]
This seems to be causing an empty line to be printed after each line in the logs.
sjust@teuthology:/a/smithfarm-2016-07-02_01:06:27-rados-hammer-backports---basic-smithi/288070/remote

**Comment by smithfarm** [comment]
Replaced by #10227

**Pull request closed without merging**
