### PR TITLE
PG: pg down state blocked by osd.x, lost osd.x cannot solve peering stuck

### PR DESCRIPTION
**Pull request by cxwshawn**
Fixes #13531

### CODE REVIEW

**Comment by yuyuyu101** [comment]
Why not just ensure public network and cluster_network with mon has successful connection? send_keepalive() can't met? From my side, detect local link down should be only one case for potential network down.

**Comment by yuyuyu101** [comment]
Hmm, I mean before send boot message we can check tcp socket via send_keepalive

**Comment by athanatos** [comment]
This looks right to me, we need to write a teuthology test to go in with this fix, and we need to run it through testing.

**Comment by cxwshawn** [comment]
@athanatos hmm, actually I don't really know how to add test about this modification, so give some hint, so I can know how we will do next.

**Comment by athanatos** [comment]
You can ask in #ceph-devel for help, but it's the ceph-qa-suite git project.  We have ways of running the tests on openstack clusters now.

**Comment by athanatos** [comment]
https://github.com/ceph/ceph-qa-suite/blob/master/tasks/lost_unfound.py is a test which tests lost_unfound handling (for example).

**Comment by tchaikov** [comment]
@cxwshawn, you could join the #ceph-devel channel (see http://ceph.com/resources/mailing-list-irc/ ) to learn more about how to write a test for your change. ping me if you need more help. and you can setup a testbed in minutes by following https://github.com/ceph/teuthology#openstack-backend. teuthology is the infrastructure driving the tests in ceph-qa-suites.

**Comment by tchaikov** [comment]
@cxwshawn ping?

**Comment by cxwshawn** [comment]
@tchaikov sorry, busy for other things lately, can u help me  ?

**Comment by tchaikov** [comment]
@cxwshawn, you can start with https://github.com/ceph/ceph-qa-suite/blob/master/erasure-code/ec-feature-plugins-v3.yaml, by reading yaml you can learn how to start/restart/stop a daemon, and create a test suite in "suites/rados/singleton/all/" (@athanatos  do you think there is a better place for this test?), like:

```yaml
roles:
- - mon.a
  - osd.0
  - osd.1
  - osd.2
- - client.0
tasks:
- install:
- ceph:
    log-whitelist:
    - objects unfound and apparently lost
- exec:
   client.0:
    - rados -p rbd put foo /etc/hosts
# more to come
```

ping me over irc if you want learn more about teuthology and its tests =)

**Comment by liewegas** [comment]
@cxwshawn ping

**Pull request merged**
