### PR TITLE
vstart: fix ganesha cluster id and rados url errors

### PR DESCRIPTION
**Pull request by varshar16**
Fixes: https://tracker.ceph.com/issues/49121, https://tracker.ceph.com/issues/49122
Signed-off-by: Varsha Rao <varao@redhat.com>

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by sebastian-philipp** [comment]
as `test_orchestrator/dummy_data.json` might be used by the daashboard, we should run it through qa

**Comment by callithea** [comment]
- [pkg build](https://shaman.ceph.com/builds/ceph/wip-laura-testing-39249/) [WIP]
- QA run [Pending]

**Review by jtlayton — APPROVED** [review]

**Review by callithea — APPROVED** [review]
Lgtm

**Comment by varshar16** [comment]
ping @sebastian-philipp

**Pull request merged**
