### PR TITLE
quincy: test/{librbd, rgw}: retry when bind fail with port 0

### PR DESCRIPTION
**Pull request by tchaikov**
Backport https://github.com/ceph/ceph/pull/47962 to quincy.

### CODE REVIEW

**Comment by tchaikov** [comment]
should address failures like https://jenkins.ceph.com/job/ceph-pull-requests/103237/

**Comment by tchaikov** [comment]
```
[ RUN      ] TestMockMigrationHttpClient.OpenCloseHttp
unknown file: Failure
C++ exception with description "bind: Address already in use" thrown in SetUp().
[  FAILED  ] TestMockMigrationHttpClient.OpenCloseHttp (9285 ms)
[ RUN      ] TestMockMigrationHttpClient.OpenCloseHttps
unknown file: Failure
C++ exception with description "bind: Address already in use" thrown in SetUp().
[  FAILED  ] TestMockMigrationHttpClient.OpenCloseHttps (9271 ms)
```

**Comment by tchaikov** [comment]
jenkins test make check

**Review by idryomov — APPROVED** [review]
Approving with the hope that this helps some, but if a process can't get a socket after 42 retries spanning 9 seconds, a close look at our Jenkins nodes at the time this happens is really needed...

**Pull request merged**
