### PR TITLE
qa/run-standalone.sh: fix the find option to be compatible with GNU find

### PR DESCRIPTION
**Pull request by tchaikov**
also re-indent to be consistent with other part of this script

Signed-off-by: Kefu Chai <kchai@redhat.com>

### CODE REVIEW

**Comment by xiexingguo** [comment]
@tchaikov Sorry, kefu. There was a power outage in ChangSha yesterday ...

I try to run the test-scripts under qa/standalone via the guide(**qa/standalone/README**) and get following error:
```
[root@gitbuilder-ceph-rpm-centos7-amd64-basic /home/xxg/build/ceph-dev/build]# PATH=$PATH:bin CEPH_ROOT=.. CEPH_LIB=lib ../qa/standalone/mon/misc.sh
+ PS4='${BASH_SOURCE[0]}:$LINENO: ${FUNCNAME[0]}:  '
../qa/standalone/ceph-helpers.sh:1833: main:  export PATH=/tmp/ceph-disk-virtualenv/bin:/tmp/ceph-detect-init-virtualenv/bin:.:/usr/lib64/ccache:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin:bin
../qa/standalone/ceph-helpers.sh:1833: main:  PATH=/tmp/ceph-disk-virtualenv/bin:/tmp/ceph-detect-init-virtualenv/bin:.:/usr/lib64/ccache:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin:bin
../qa/standalone/ceph-helpers.sh:1836: main:  export CEPH_CONF=/dev/null
../qa/standalone/ceph-helpers.sh:1836: main:  CEPH_CONF=/dev/null
../qa/standalone/ceph-helpers.sh:1837: main:  unset CEPH_ARGS
../qa/standalone/ceph-helpers.sh:1839: main:  local code
../qa/standalone/ceph-helpers.sh:1840: main:  run td/misc
../qa/standalone/mon/misc.sh:21: run:  local dir=td/misc
../qa/standalone/mon/misc.sh:22: run:  shift
../qa/standalone/mon/misc.sh:24: run:  export CEPH_MON=127.0.0.1:7102
../qa/standalone/mon/misc.sh:24: run:  CEPH_MON=127.0.0.1:7102
../qa/standalone/mon/misc.sh:25: run:  export CEPH_ARGS
.../qa/standalone/mon/misc.sh:26: run:  uuidgen
../qa/standalone/mon/misc.sh:26: run:  CEPH_ARGS+='--fsid=a768087a-2d10-437f-8be4-c30158bf48a0 --auth-supported=none '
../qa/standalone/mon/misc.sh:27: run:  CEPH_ARGS+='--mon-host=127.0.0.1:7102 '
.../qa/standalone/mon/misc.sh:29: run:  set
.../qa/standalone/mon/misc.sh:29: run:  sed -n -e 's/^\(TEST_[0-9a-z_]*\) .*/\1/p'
../qa/standalone/mon/misc.sh:29: run:  local 'funcs=TEST_mon_add_to_single_mon
TEST_mon_features
TEST_no_segfault_for_bad_keyring
TEST_osd_pool_get_set'
../qa/standalone/mon/misc.sh:30: run:  for func in '$funcs'
../qa/standalone/mon/misc.sh:31: run:  TEST_mon_add_to_single_mon td/misc
../qa/standalone/mon/misc.sh:101: TEST_mon_add_to_single_mon:  local dir=td/misc
.../qa/standalone/mon/misc.sh:103: TEST_mon_add_to_single_mon:  uuidgen
../qa/standalone/mon/misc.sh:103: TEST_mon_add_to_single_mon:  fsid=82ee057e-1534-40b5-b1d2-117dc9dff742
../qa/standalone/mon/misc.sh:104: TEST_mon_add_to_single_mon:  MONA=127.0.0.1:7117
../qa/standalone/mon/misc.sh:105: TEST_mon_add_to_single_mon:  MONB=127.0.0.1:7118
../qa/standalone/mon/misc.sh:106: TEST_mon_add_to_single_mon:  CEPH_ARGS_orig='--fsid=a768087a-2d10-437f-8be4-c30158bf48a0 --auth-supported=none --mon-host=127.0.0.1:7102 '
../qa/standalone/mon/misc.sh:107: TEST_mon_add_to_single_mon:  CEPH_ARGS='--fsid=82ee057e-1534-40b5-b1d2-117dc9dff742 --auth-supported=none '
../qa/standalone/mon/misc.sh:108: TEST_mon_add_to_single_mon:  CEPH_ARGS+='--mon-initial-members=a '
../qa/standalone/mon/misc.sh:109: TEST_mon_add_to_single_mon:  CEPH_ARGS+='--mon-host=127.0.0.1:7117 '
../qa/standalone/mon/misc.sh:111: TEST_mon_add_to_single_mon:  setup td/misc
../qa/standalone/ceph-helpers.sh:128: setup:  local dir=td/misc
../qa/standalone/ceph-helpers.sh:129: setup:  teardown td/misc
../qa/standalone/ceph-helpers.sh:154: teardown:  local dir=td/misc
../qa/standalone/ceph-helpers.sh:155: teardown:  kill_daemons td/misc KILL
.../qa/standalone/ceph-helpers.sh:299: kill_daemons:  shopt -q -o xtrace
.../qa/standalone/ceph-helpers.sh:299: kill_daemons:  echo true
../qa/standalone/ceph-helpers.sh:299: kill_daemons:  local trace=true
../qa/standalone/ceph-helpers.sh:300: kill_daemons:  true
../qa/standalone/ceph-helpers.sh:300: kill_daemons:  shopt -u -o xtrace
../qa/standalone/ceph-helpers.sh:316: kill_daemons:  return 0
.../qa/standalone/ceph-helpers.sh:156: teardown:  uname
../qa/standalone/ceph-helpers.sh:156: teardown:  '[' Linux '!=' FreeBSD ']'
.../qa/standalone/ceph-helpers.sh:157: teardown:  stat -f -c %T .
../qa/standalone/ceph-helpers.sh:157: teardown:  '[' xfs == btrfs ']'
../qa/standalone/ceph-helpers.sh:160: teardown:  rm -fr td/misc
.../qa/standalone/ceph-helpers.sh:161: teardown:  get_asok_dir
.../qa/standalone/ceph-helpers.sh:105: get_asok_dir:  '[' -n '' ']'
.../qa/standalone/ceph-helpers.sh:108: get_asok_dir:  echo /tmp/ceph-asok.185838
../qa/standalone/ceph-helpers.sh:161: teardown:  rm -rf /tmp/ceph-asok.185838
../qa/standalone/ceph-helpers.sh:130: setup:  mkdir -p td/misc
.../qa/standalone/ceph-helpers.sh:131: setup:  get_asok_dir
.../qa/standalone/ceph-helpers.sh:105: get_asok_dir:  '[' -n '' ']'
.../qa/standalone/ceph-helpers.sh:108: get_asok_dir:  echo /tmp/ceph-asok.185838
../qa/standalone/ceph-helpers.sh:131: setup:  mkdir -p /tmp/ceph-asok.185838
../qa/standalone/mon/misc.sh:112: TEST_mon_add_to_single_mon:  run_mon td/misc a --public-addr 127.0.0.1:7117
../qa/standalone/ceph-helpers.sh:392: run_mon:  local dir=td/misc
../qa/standalone/ceph-helpers.sh:393: run_mon:  shift
../qa/standalone/ceph-helpers.sh:394: run_mon:  local id=a
../qa/standalone/ceph-helpers.sh:395: run_mon:  shift
../qa/standalone/ceph-helpers.sh:396: run_mon:  local data=td/misc/a
../qa/standalone/ceph-helpers.sh:399: run_mon:  ceph-mon --id a --mkfs --mon-data=td/misc/a --run-dir=td/misc --public-addr 127.0.0.1:7117
ceph-mon: renaming mon.noname-a 127.0.0.1:7117/0 to mon.a
ceph-mon: set fsid to 82ee057e-1534-40b5-b1d2-117dc9dff742
ceph-mon: created monfs at td/misc/a for mon.a
.../qa/standalone/ceph-helpers.sh:406: run_mon:  get_asok_path
.../qa/standalone/ceph-helpers.sh:113: get_asok_path:  local name=
.../qa/standalone/ceph-helpers.sh:114: get_asok_path:  '[' -n '' ']'
..../qa/standalone/ceph-helpers.sh:117: get_asok_path:  get_asok_dir
..../qa/standalone/ceph-helpers.sh:105: get_asok_dir:  '[' -n '' ']'
..../qa/standalone/ceph-helpers.sh:108: get_asok_dir:  echo /tmp/ceph-asok.185838
.../qa/standalone/ceph-helpers.sh:117: get_asok_path:  echo '/tmp/ceph-asok.185838/$cluster-$name.asok'
../qa/standalone/ceph-helpers.sh:406: run_mon:  ceph-mon --id a --mon-osd-full-ratio=.99 --mon-data-avail-crit=1 --paxos-propose-interval=0.1 --osd-crush-chooseleaf-type=0 --erasure-code-dir lib --plugin-dir lib --osd-class-dir lib --debug-mon 20 --debug-ms 20 --debug-paxos 20 --chdir= --mon-data=td/misc/a '--log-file=td/misc/$name.log' '--admin-socket=/tmp/ceph-asok.185838/$cluster-$name.asok' --mon-cluster-log-file=td/misc/log --run-dir=td/misc '--pid-file=td/misc/$name.pid' --mon-allow-pool-delete --mon-osd-backfillfull-ratio .99 --public-addr 127.0.0.1:7117
too many arguments: [--erasure-code-dir,lib,--plugin-dir,lib,--mon-osd-backfillfull-ratio,.99]
usage: ceph-mon -i monid [flags]
  --debug_mon n
        debug monitor level (e.g. 10)
  --mkfs
        build fresh monitor fs
  --force-sync
        force a sync from another mon by wiping local data (BE CAREFUL)
  --yes-i-really-mean-it
        mandatory safeguard for --force-sync
  --compact
        compact the monitor store
  --osdmap <filename>
        only used when --mkfs is provided: load the osdmap from <filename>
  --inject-monmap <filename>
        write the <filename> monmap to the local monitor store and exit
  --extract-monmap <filename>
        extract the monmap from the local monitor store and exit
  --mon-data <directory>
        where the mon store and keyring are located
  --conf/-c FILE    read configuration from the given configuration file
  --id/-i ID        set ID portion of my name
  --name/-n TYPE.ID set name
  --cluster NAME    set cluster name (default: ceph)
  --version         show version and quit

  -d                run in foreground, log to stderr.
  -f                run in foreground, log to usual location.
  --debug_ms N      set message debug level (e.g. 1)
../qa/standalone/ceph-helpers.sh:424: run_mon:  return 1
../qa/standalone/mon/misc.sh:112: TEST_mon_add_to_single_mon:  return 1
../qa/standalone/mon/misc.sh:31: run:  return 1
```
I know you are expert at these.
Further help would be greatly appreicated.

**Comment by wjwithagen** [comment]
@xiexingguo 
This looks more like a error in the `mon/misc.sg script`
when it looks like ceph-mon is offered too many arguments.
It is a rather long line, but not extreme long. 
Perhaps you can try with a few less options? Like delete all the debug-*, and see if that works

**Comment by wjwithagen** [comment]
@xiexingguo 
That was bad advice above.
There are probably invalid options on the CLI.
You'd have to experiment to find the one(s) that is in error.

**Comment by xiexingguo** [comment]
@wjwithagen Thanks. Still working on it:-(

**Comment by dzafman** [comment]
@xiexingguo @wjwithagen @tchaikov See my pull request with a revamp of run-standalone.sh #16709

**Pull request merged**
