### PR TITLE
rgw: fetch_remote_obj() preserves original part lengths for BlockDecrypt

### PR DESCRIPTION
**Pull request by cbodley**
because multisite replicates multipart objects as a single part, we lose information about the part sizes from the original manifest that is necessary to correctly decrypt across those part boundaries

on replication, parse the part lengths out of the source object's manifest, and store them in a separate RGW_ATTR_CRYPT_PARTS for use on decryption

Fixes: https://tracker.ceph.com/issues/46062

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by cbodley** [comment]
this does seem to fix the `WARNING: MD5 signatures do not match` from the reproducer in https://tracker.ceph.com/issues/46062#note-6

**Comment by cbodley** [comment]
> @cbodley how is this different from what @mdw-at-linuxbox is working on?

it's the same thing. i emailed him about this yesterday

**Comment by cbodley** [comment]
review feedback from @mdw-at-linuxbox:

* add versioning to encoding of RGW_ATTR_CRYPT_PARTS
* support AppendObject on replicated objects by appending to RGW_ATTR_CRYPT_PARTS
* handle chaining replication (site A -> site B -> site C) by preserving source RGW_ATTR_CRYPT_PARTS if they exist

**Comment by cbodley** [comment]
jenkins test make check

**Comment by cbodley** [comment]
jenkins test api

**Comment by cbodley** [comment]
a make check build failure:
```
src/test/rgw/test_rgw_crypto.cc:431:28: error: no matching constructor for initialization of 'RGWGetObj_BlockDecrypt'
    RGWGetObj_BlockDecrypt decrypt(&no_dpp, g_ceph_context, &get_sink, std::move(cbc), null_yield);
                           ^       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
and [multisite tests](https://pulpito.ceph.com/cbodley-2023-08-02_21:27:38-rgw-wip-cbodley-testing-distro-default-smithi/7359016/) showed crashes on realm reload:
```
src/rgw/rgw_coroutine.cc: 117: FAILED ceph_assert(waiters.find(opaque) == waiters.end())
 
 ceph version 18.0.0-5291-gf936671d (f936671d75974064c7553c1944a8f21421a054f8) reef (dev)
 1: (ceph::__ceph_assert_fail(char const*, char const*, int, char const*)+0x12e) [0x7fa0b156107d]
 2: /usr/lib64/ceph/libceph-common.so.2(+0x16123b) [0x7fa0b156123b]
 3: (RGWCompletionManager::wait_interval(void*, utime_t const&, void*)+0x2ec) [0x56162175821c]
 4: (RGWContinuousLeaseCR::operate(DoutPrefixProvider const*)+0x300) [0x561621b23010]
 5: (RGWCoroutinesStack::operate(DoutPrefixProvider const*, RGWCoroutinesEnv*)+0x125) [0x561621762215]
 6: (RGWCoroutinesManager::run(DoutPrefixProvider const*, std::__cxx11::list<RGWCoroutinesStack*, std::allocator<RGWCoroutinesStack*> >&)+0x2b6) [0x561621763a86]
```
i doubt it's caused by this PR (maybe sync fairness?) so i scheduled tests against main in https://pulpito.ceph.com/cbodley-2023-08-03_02:45:05-rgw:multisite-main-distro-default-smithi/

**Comment by cbodley** [comment]
> i doubt it's caused by this PR (maybe sync fairness?) so i scheduled tests against main in https://pulpito.ceph.com/cbodley-2023-08-03_02:45:05-rgw:multisite-main-distro-default-smithi/

i see the same crash there on main. opened https://tracker.ceph.com/issues/62298 with details (cc @smanjara)

**Comment by smanjara** [comment]
@cbodley the pr looks good to me! also ran a quick test locally along with https://github.com/ceph/ceph/pull/51786 and it passes successfully.

i'm looking into the crash.

**Comment by cbodley** [comment]
> @cbodley the pr looks good to me! also ran a quick test locally along with #51786 and it passes successfully.

thanks! could i ask for your approval on https://github.com/ceph/ceph/pull/51786 as well?

**Comment by cbodley** [comment]
i pulled in the commits from https://github.com/ceph/ceph/pull/51842 and added a release note with recovery instructions

**Comment by tobias-urdin** [comment]
@cbodley this was never pulled in to pacific what i can find? this tracker https://tracker.ceph.com/issues/62322

**Pull request merged**
