### PR TITLE
crushtool: add --add-bucket and --move options

### PR DESCRIPTION
**Pull request by tchaikov**

### CODE REVIEW

**Comment by tchaikov** [comment]
http://pulpito.ceph.com/kchai-2018-01-31_01:48:16-rados-wip-kefu-testing-2018-01-31-0034-distro-basic-mira/

failure tracked at http://tracker.ceph.com/issues/22846

**Comment by ktdreyer** [comment]
@tchaikov does this need to go to Luminous now?

**Comment by tchaikov** [comment]
@ktdreyer thanks for your reminder, see #21079

**Comment by ktdreyer** [comment]
Thanks Kefu! And for filing http://tracker.ceph.com/issues/23471 to track this.

**Pull request merged**
