### PR TITLE
osdc: fix the ENOCONN normalization in Objecter::_linger_reconnect()

### PR DESCRIPTION
**Pull request by rzarzynski**
Problem's description: https://tracker.ceph.com/issues/53789#note-12

Fixes: https://tracker.ceph.com/issues/53789
Signed-off-by: Radoslaw Zarzynski <rzarzyns@redhat.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by rzarzynski** [comment]
jenkins test api

**Review by adamemerson — APPROVED** [review]
Looks good to me

**Comment by rzarzynski** [comment]
@yuri, @ljflores: ping.

**Comment by ljflores** [comment]
@rzarzynski not sure how I missed this; it will be included in the next QA run.

**Comment by rzarzynski** [comment]
No worries :-).

**Comment by NitzanMordhai** [comment]
Rados approved: https://tracker.ceph.com/projects/rados/wiki/MAIN#httpstrellocomc6oYH6qSe1924-wip-yuri3-testing-2024-01-10-0735-old-wip-yuri3-testing-2024-01-09-1342

**Comment by yuriw** [comment]
jenkins test make check

**Comment by yuriw** [comment]
@rzarzynski this PR is ready for merge after checks passed
ref: https://trello.com/c/6oYH6qSe

**Pull request merged**
