### PR TITLE
osd/ReplicatedPG: snaptimmer: adjust stats through ctx->delta_stats

### PR DESCRIPTION
**Pull request by liewegas**
Standardize the way that delta_stats are applied: all paths lead to update_ctx_stats(), which is either called explicitly or indirectly via finish_ctx.

This ensures the same checks always apply for racing scrub and backfill, where previously they were inconsistently handled.

### CODE REVIEW

**Comment by liewegas** [comment]
passed wip-sage-testing

**Comment by liewegas** [comment]
grr, caught a failure...

Failure: "2015-09-07 18:23:59.144483 osd.1 10.214.132.25:6809/32667 4 : cluster [ERR] 2.2 scrub stat mismatch, got 50/49 objects, 0/0 clones, 28/28 dirty, 0/0 omap, 1/1 hit_set_archive, 1/1 whiteouts, 147429172/145169791 bytes, 196/196 hit_set_archive bytes." in cluster log
/a/sage-2015-09-07_06:22:35-rados-wip-sage-testing---basic-multi/1046000

**Comment by athanatos** [comment]
I don't think that failure is due to this series, I think it's an existing bug.  Any other instances?

**Comment by liewegas** [comment]
http://pulpito.ceph.com/sage-2015-09-08_17:29:00-rados-wip-sage-testing---basic-multi/1046976

**Pull request merged**
