### PR TITLE
mon: scrub error (osdmap encoding mismatch?) upgrading from 0.80 to ~0.80.2

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/12289
http://tracker.ceph.com/issues/12014
http://tracker.ceph.com/issues/12247

### CODE REVIEW

**Comment by smithfarm** [comment]
@gregsfortytwo This has passed a rados suite (see http://tracker.ceph.com/issues/11644#rados for details). OK to merge, do you think? I'm asking you because you appear to have merged c93da05 .

**Comment by gregsfortytwo** [comment]
@smithfarm, if this was a clean cherry-pick it's probably good, but you'll have to get somebody off the RADOS team to check it. Sorry. I bet @tchaikov is willing and it might be interesting for him. :)

**Comment by smithfarm** [comment]
@tchaikov: Thanks in advance!

**Comment by tchaikov** [comment]
lgtm. dazzled by the involved commits. some of them dates back to 1 year ago!

**Comment by smithfarm** [comment]
@tchaikov Yes, some of these fixes should have been backported earlier :-/

**Pull request merged**
