### PR TITLE
global/global_init: do not apply_changes until after dropping privs

### PR DESCRIPTION
**Pull request by liewegas**
This ensures we open the log file a the final user, not as root.

Signed-off-by: Sage Weil <sage@redhat.com>

### CODE REVIEW

**Comment by smithfarm** [comment]
Methinks commit message needs a "Fixed: #14613"

**Comment by liewegas** [comment]
passed rados suite (twice)

**Comment by jdurgin** [comment]
the rest looks good

**Comment by liewegas** [comment]
@jdurgin can you look at the last commit that does the deferred warnings?  i went around in circles a bit on putting the parse errors in ConfFile vs md_config_t and eventually opted to touch less crufty code

**Comment by jdurgin** [comment]
lgtm - can always change that part later, and it looks like this will work

**Comment by liewegas** [comment]
merged manually

**Pull request closed without merging**
