### PR TITLE
osd/OSDMap.cc: fix duplicated assignment for new_blacklist_entries

### PR DESCRIPTION
**Pull request by KerLiu**
Signed-off-by: Ker Liu kerliu818@gmail.com

### CODE REVIEW

**Comment by KerLiu** [comment]
@tchaikov 
please abandon previous #11799, I re-submitted it with git bash.
sorry for the inconveniences.

**Comment by tchaikov** [comment]
could you prefix the title of your commit message with the subcomponent your are changing ? see https://github.com/ceph/ceph/blob/master/SubmittingPatches.rst#3-describe-your-changes

could you add a "`Signed-off-by`" line at the end of your commit message? "git commit -s" will do the trick for you. see https://github.com/ceph/ceph/blob/master/SubmittingPatches.rst#1-sign-your-work

**Comment by KerLiu** [comment]
@tchaikov 
Done, thanks a lot for your support!

**Comment by tchaikov** [comment]
and the title of your commit message is misleading, instead of "fixing" things, it "simplifies" the loop by replacing it with with a "insert()" call.

**Comment by KerLiu** [comment]
before my code change, the variable "new_blacklist_entries" will be assigned to "true" many times based on the size of new_blacklist, it's duplicated assignment, my code change is to fix it, only do one time assignment.

**Comment by tchaikov** [comment]
oh, right! sorry, i missed it!

**Comment by tchaikov** [comment]
- http://pulpito.ceph.com/kchai-2016-11-13_12:19:00-rados-wip-kefu-testing---basic-mira/

**Pull request merged**
