### PR TITLE
hammer: rgw: default quota params

### PR DESCRIPTION
**Pull request by dachary**
http://tracker.ceph.com/issues/13799

### CODE REVIEW

**Comment by dang** [comment]
LGTM

**Comment by dachary** [comment]
@yehudasa does this backport look good to merge ? It passed a run of the hammer rgw suite ( see http://tracker.ceph.com/issues/13356#note-43 ) except one occurence of a known subuser bug ( http://tracker.ceph.com/issues/14375).

**Comment by dachary** [comment]
@yehudasa ping ?

**Comment by yehudasa** [comment]
@dachary ok

**Pull request merged**
