### PR TITLE
os/bluestore: attach csum for compressed blobs

### PR DESCRIPTION
**Pull request by ifed01**
Fixes: https://tracker.ceph.com/issues/47475
Signed-off-by: Igor Fedotov <ifedotov@suse.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by tchaikov** [comment]
- https://pulpito.ceph.com/kchai-2020-09-16_14:28:48-rados-wip-kefu-testing-2020-09-16-1741-distro-basic-smithi/
- https://pulpito.ceph.com/kchai-2020-09-17_08:46:35-rados-wip-kefu-testing-2020-09-17-1122-distro-basic-smithi/

**Comment by aclamk** [comment]
@ifed01 But hasn't it been an assumption that compressors will sanitize its content?
You think its ability for error detection might not be sufficient?

**Comment by ifed01** [comment]
> @ifed01 But hasn't it been an assumption that compressors will sanitize its content?
> You think its ability for error detection might not be sufficient?

The following ticket has inspired me for this fix: https://tracker.ceph.com/issues/46490
While the root cause for disk read failures is still unclear there one of their consequence is an assertion during decoding of improperly read (and hence invalid) compression header.
Generally I think that's a good idea to have csum for this sort of data, I presume the overhead is neglectable.

**Review by aclamk — APPROVED** [review]
Tested, works.
This is good improvement.

**Pull request merged**
