### PR TITLE
Fix test ceph disk dmcrypt uuid

### PR DESCRIPTION
**Pull request by ddiss**

### CODE REVIEW

**Comment by dachary** [comment]
:+1:

**Comment by smithfarm** [comment]
@ddiss: 38682f9 looks like it should be backported to hammer, but 9dab666 not so much - would it be too much trouble to break them into separate pull requests?

**Comment by smithfarm** [comment]
@ddiss: also could you add 
```
http://tracker.ceph.com/issues/11821 Fixes: #11821
```
to the commit message of 38682f9

**Comment by ddiss** [comment]
Thanks for the feedback. I've resubmitted with the issue tracker tag attached to the btrfs teardown change.

@smithfarm: Which branch should I submit against for hammer - hammer-backports? I'll follow up with you on IRC.

**Pull request closed without merging**
