### PR TITLE
common: Implements simple_spin_t in terms of std::atomic_flag.

### PR DESCRIPTION
**Pull request by chardan**
Note that I'm not sure how this will work on the s360 (but, I /expect/ it to be correct). Similarly, I believe I've picked the most relaxed memory order that will work for the situation, but I'm not 100% sure since I can't try it on all target architectures or stress the concurrency as much as I'd like. Please test carefully!

Signed-off-by: Jesse Williamson <jwilliamson@suse.de>

### CODE REVIEW

**Comment by jecluis** [comment]
@chardan didn't review the patch, but looking at the commit message I would like to suggest you change the title to `common: implement simple_spin_t in terms of std::atomic_flag`, and that you add a brief description of the problem and the fix to the commit message body.

**Comment by liewegas** [comment]
While we're futzing with this, can we kill atomic_t and use the c++ intrinsics

**Comment by badone** [comment]
As suspected the build failure is for the add_executable call to unittest_simple_spin

**Comment by chardan** [comment]
@badone Thanks for catching that! I didn't realize it was part of the test system at first, so I'd taken it out, then put it in back without recommitting-- will fix.

@liewegas Sounds like a good idea to me. Would you rather see that as part of this PR, or another?@smithfarm's PR should make things ok for the s390 WRT this functionality, if there's a delay.

**Comment by smithfarm** [comment]
@chardan I'm not @liewegas but . . . since the immediate problem of the broken s390 build has been addressed there is no hurry and you could just add more commits to this PR.

**Comment by smithfarm** [comment]
@chardan Totally anal nit - could you remove the period from the end of the commit description? The release notes are auto-generated from these descriptions and periods on the end don't work well with the release notes template.

**Comment by smithfarm** [comment]
@chardan Please ignore my totally anal nit. I realized the script processes PR descriptions, not commit descriptions, and we can will strip off any trailing punctuation in the script itself.

**Comment by chardan** [comment]
@smithfarm No worries! (And, fixed anyway.)
@liewegas Looks like there are about 254 occurrences of atomic_t. If I had to vote, I'd say separate PR. Meanwhile, I'll dive in!

**Comment by liewegas** [comment]
IMO A separate PR for atomic_t makes more sense

**Comment by chardan** [comment]
@liewegas Agreed, I'll set it up separately.

**Comment by liewegas** [comment]
http://pulpito.ceph.com/sage-2017-04-07_19:53:23-rados-wip-sage-testing---basic-smithi/

**Pull request merged**
