### PR TITLE
os/fs/FS.cc: condition on WITH_AIO for FreeBSD

### PR DESCRIPTION
**Pull request by wjwithagen**
Signed-off-by: Willem Jan Withagen <wjw@digiware.nl>

### CODE REVIEW

**Comment by tchaikov** [comment]
could you squash these two commits into a single one?

**Comment by wjwithagen** [comment]
@tchaikov 
I though I had squashed, but that did not go thru.
Now it does.

**Comment by tchaikov** [comment]
lgtm.

**Comment by dachary** [comment]
jenkins test this please (no logs)

**Pull request merged**
