### PR TITLE
logmon: check is_leader() before doing any work on get_trim_to()

### PR DESCRIPTION
**Pull request by songbaisen**
logmon: check is_leader() before doing any work on get_trim_to()

Signed-off-by: song baisen <song.baisen@zte.com.cn>

### CODE REVIEW

**Comment by gregsfortytwo** [comment]
Please use a commit message that describes the actual change, not its size. ;) eg
"logmon: check is_leader() before doing any work on get_trim_to()"

**Comment by songbaisen** [comment]
@gregsfortytwo  Thank you! Done it.:)

**Comment by gregsfortytwo** [comment]
this looks fine to me. @jecluis, any concerns?

**Comment by yuriw** [comment]
http://pulpito.ceph.com/yuriw-2016-07-21_15:02:04-rados-wip-yuri-testing2_2016_7_21-distro-basic-smithi/
http://pulpito.ceph.com/yuriw-2016-07-25_09:25:30-rados-wip-yuri-testing2_2016_7_21-distro-basic-smithi/

**Pull request merged**
