### PR TITLE
nautilus: mgr: add mon metada using type of "mon"

### PR DESCRIPTION
**Pull request by tchaikov**
backport of #39937

backport ticket: https://tracker.ceph.com/issues/49705

---

this change addresses a regression introduced by
c037f4cb5d7436879d58c34748ef516b5269781f

also remove the "P" before the json command.

see also: https://tracker.ceph.com/issues/48905

Fixes: https://tracker.ceph.com/issues/49661
Signed-off-by: Kefu Chai <kchai@redhat.com>
(cherry picked from commit 8fc290bfba4d71a60d30c2374ce4bcba37e649de)

 Conflicts:
	src/mgr/Mgr.cc: trivial resolution

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by smithfarm** [comment]
jenkins test signed

**Comment by smithfarm** [comment]
jenkins test make check

**Review by ideepika — APPROVED** [review]
tests looks good: https://trello.com/c/R6ClYBUf/1197-wip-yuri8-testing-2021-04-06-1934-nautilus-old-wip-yuri8-testing-2021-04-05-1412-nautilus-old-wip-yuri8-testing-2021-03-29-0949

**Comment by smithfarm** [comment]
```
The following tests FAILED:
	 57 - unittest_lockdep (Timeout)
```

**Comment by smithfarm** [comment]
jenkins test make check

**Comment by smithfarm** [comment]
@tchaikov Am I seeing correctly that the commit that introduced this bug was released as part of Nautilus 14.2.17? I'm seeing that here: https://tracker.ceph.com/issues/49005

Is this a problem for users of 14.2.17, 14.2.18, and 14.2.19? Would you recommend waiting for this fix to get released before upgrading to these versions?

**Comment by tchaikov** [comment]
> @tchaikov Am I seeing correctly that the commit that introduced this bug was released as part of Nautilus 14.2.17? I'm seeing that here: https://tracker.ceph.com/issues/49005

yes.

> 
> Is this a problem for users of 14.2.17, 14.2.18, and 14.2.19? Would you recommend waiting for this fix to get released before upgrading to these versions?

ideally, yes.

**Pull request merged**
