### PR TITLE
ceph.in: Notify user that 'tell' can't be used in interactive mode

### PR DESCRIPTION
**Pull request by dzafman**
http://tracker.ceph.com/issues/14769

### CODE REVIEW

**Comment by ktdreyer** [comment]
LGTM, thank you @dzafman

**Comment by dzafman** [comment]
@dachary Please merge to Hammer, if that is the appropriate next step.

**Comment by dachary** [comment]
@dzafman thanks !

**Comment by dachary** [comment]
Passed upgrade tests http://tracker.ceph.com/issues/14692#note-14

**Pull request merged**
