### PR TITLE
rgw: fixed "unrecognized arg" error when using "radosgw-admin zone rm".

### PR DESCRIPTION
**Pull request by c744402859**
Fixes: https://tracker.ceph.com/issues/41184
Signed-off-by: Hongang Chen <c744402859@gmail.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`

</details>

### CODE REVIEW

**Comment by c744402859** [comment]
@cbodley I close  https://github.com/ceph/ceph/pull/29573  because I submitted some wrong information.

**Comment by tchaikov** [comment]
@c744402859 please "use the imperative mood in the title". see https://github.com/ceph/ceph/blob/master/SubmittingPatches.rst#3-describe-your-changes

**Comment by c744402859** [comment]
Thanks. @tchaikov

**Comment by smithfarm** [comment]
@tchaikov @cbodley There's also the part in SubmittingPatches.rst that says:

```
then you just add a line saying ::

        Signed-off-by: Random J Developer <random@developer.example.org>

using your real name (sorry, no pseudonyms or anonymous contributions.)
```

Are we no longer enforcing that?

**Comment by cbodley** [comment]
i generally just rely on jenkins to enforce this with the Signed-off check. in this case, the Signed-off-by looks fine - is your issue with the Author part?

**Comment by smithfarm** [comment]
@cbodley I'm in the process of editing `SubmittingPatches.rst` - that's why I'm asking. I don't have an "issue" with it - rather, I noticed that the name given in this case ("root") is . . . how to say it  . . . possibly (likely?) not the author's real name? Yet we say it's supposed to be.

**Comment by smithfarm** [comment]
@cbodley Sorry, it's getting late here. Indeed, the "Author" line threw me. Sorry for the noise.

**Pull request merged**
