### PR TITLE
rgw: disable deprecated tls v1 and v1.1 protocols

### PR DESCRIPTION
**Pull request by trociny**
Fixes: https://tracker.ceph.com/issues/50765
Signed-off-by: Mykola Golub <mgolub@suse.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by trociny** [comment]
before:
```
% testssl.sh https://localhost:8443
...
 SSLv2      not offered (OK)
 SSLv3      not offered (OK)
 TLS 1      offered (deprecated)
 TLS 1.1    offered (deprecated)
 TLS 1.2    offered (OK)
 TLS 1.3    offered (OK): final
 NPN/SPDY   not offered
 ALPN/HTTP2 not offered

```
after:
```
 SSLv2      not offered (OK)
 SSLv3      not offered (OK)
 TLS 1      not offered
 TLS 1.1    not offered
 TLS 1.2    offered (OK)
 TLS 1.3    offered (OK): final
 NPN/SPDY   not offered
 ALPN/HTTP2 not offered
```

In the current version it is hard coded. We could make it optional (disabled by default). I am open to suggestions.

**Comment by mdw-at-linuxbox** [comment]
It's certainly not useful to even think about sslv2/v3.  For the older tls versions; a flag is probably a good thing: somebody probably has a client that needs it and justfification why they can't fix their client.

Rather than try to devise a scheme from scratch it's probably best to make it look like how others do it.  There are 2 dimensions here: "protocol" and "ciphers", and it's useful to have an "all but" negative option.  For instance https://www.haproxy.com/documentation/aloha/latest/traffic-management/lb-layer7/tls/
http://nginx.org/en/docs/http/configuring_https_servers.html

**Comment by k0ste** [comment]
> In the current version it is hard coded. We could make it optional (disabled by default). I am open to suggestions.

Today I've start read docs, to "how to migrate civetweb to beast", cause civetweb was dropped in master. And I came to the conclusion that there is no way due lack of identical options. I was create ticket ([#50932](https://tracker.ceph.com/issues/50932)) for this, later found this PR...

**Comment by mdw-at-linuxbox** [comment]
Many civetweb options can be converted to beast without trouble.  But, for your deployment, the bit that's missing here is what you identified in the tracker issue - protocol/cipher specific stuff -- which perfectly illustrates my comment above "don't invent a unique syntax instead try to do the 'general generic' approach like others do".

**Comment by trociny** [comment]
Thanks for suggestions. I created a new PR #41579 lined to https://tracker.ceph.com/issues/50932, which is more generic than my https://tracker.ceph.com/issues/50765.

I am going to close this one in favor of #41579.

**Pull request closed without merging**
