### PR TITLE
mon/OSDMonitor: Clean up: delete extra S signature for plural

### PR DESCRIPTION
**Pull request by shinobu-x**
Signed-off-by: Shinobu Kinjo <shinobu@redhat.com>

### CODE REVIEW

**Comment by smithfarm** [comment]
@shinobu-x The description of the commit message "Clean up: Delete extra S signature for plural" could be changed to "mon: Delete extra S signature for plural"? The prefix is supposed to denote which Ceph component the patch is changing. 

Thanks for noticing and fixing this!

**Comment by shinobu-x** [comment]
@smithfarm Thanks for your suggestion which is good. I will follow you.

**Comment by tchaikov** [comment]
@shinobu-x the title of the pull request is different from that of the commit(s) in that PR. could you update the commit also?

**Comment by smithfarm** [comment]
@shinobu-x The command to update the commit message is `ceph commit --amend` and then `git push -f` to push the change to github.

**Comment by shinobu-x** [comment]
@tchaikov @smithfarm Thanks for your help. Much appreciated :)

**Pull request merged**
