### PR TITLE
common/obj_bencher.cc: fix verification crashing when there's no objects

### PR DESCRIPTION
**Pull request by branch-predictor**
When specified pool is empty or doesn't contain valid bench objects, rados
can crash because it attempts to memcmp through NULL pointer. Added check
for valid object size (which also fixes the case when objects are there, but
they're truncated), and made object_size being size_t instead of int.

Also, fix lock issue under similar conditions in seq_read_bench().

Signed-off-by: Piotr Dałek <piotr.dalek@ts.fujitsu.com>

### CODE REVIEW

**Comment by dachary** [comment]
@branch-predictor could you add a minimal test case that shows the problem & demonstrate the bug fix ? Otherwise looks great :)

**Comment by branch-predictor** [comment]
Actually all it takes is to do

```
rados -p <pool> bench 10 write --no-cleanup 
```

on one node, then on another node:

```
rados -p <pool> bench <any number> seq 
```

for seq lock failure, and 

```
rados -p <pool> bench <any number> rand 
```

for the segfault with memcmp. The caveat here is that I managed to hit both cases on one particular host in 4-node cluster, with remaining two other nodes not showing up this bug. On node on which I did ```rados bench write``` it obviously worked.

**Comment by dachary** [comment]
The Lock is a race and I can't think of a way to reproduce it reliably.

**Comment by dachary** [comment]
The memcmp crash should be easy to repeat somewhere in src/test/test_rados_tool.sh ?

**Comment by branch-predictor** [comment]
Actually, probably yes. Doing bench then truncating all objects down to 0 bytes should do it. I'll check it and update test if it'll work.

**Comment by dachary** [comment]
@branch-predictor it would also work with bench write one object and truncate it. In the spirit of keepinng it minimal.

**Comment by branch-predictor** [comment]
@dachary There's already some other test involving ```rados bench write --no-cleanup```, so I could reuse it.

**Pull request merged**
