### PR TITLE
crimson/os/seastore: consolidate seastore_journal logs with cleanup and validations

### PR DESCRIPTION
**Pull request by cyx1231st**
## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [x] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by cyx1231st** [comment]
jenkins test api

**Comment by athanatos** [comment]
I'd prefer to keep ExtentReader::scan_extents where it is.  SegmentCleaner is the only current user, but I expect fsck type utilities and tests to use it in the future.

**Review by athanatos — APPROVED** [review]
LGTM otherwise

**Comment by cyx1231st** [comment]
- Dropped commit `crimson/os/seastore: merge scan_extents with SegmentCleaner::gc_reclaim_space`.
- Converted `ExtentReader::scan_extents()` to use seastore logging.

**Comment by cyx1231st** [comment]
Will merge if no further reviews.

**Pull request merged**
