### PR TITLE
 remove grafana dashboard packages 

### PR DESCRIPTION
**Pull request by ideepika**
## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by ideepika** [comment]
https://shaman.ceph.com/builds/ceph/wip-fix-grafana-deepika-testing/dbfbbcf13b711c4b3c34949dd49857877d152d63/

**Comment by tchaikov** [comment]
see also #42194

**Comment by ideepika** [comment]
@aaSharma14 @epuertat I created the PR to address critical build failures, but I am not sure about the intent of maintaining ceph-dashboard/*json do we want to keep existing ones? If we do, keeping install patch might be needed
https://github.com/ceph/ceph/pull/42194/files#diff-90fe51edeba2655428fd5bbeb383b9b2c9b9a393bda2b9355f205eac9046609aL1-L8

**Comment by epuertat** [comment]
> @aaSharma14 @epuertat I created the PR to address critical build failures, but I am not sure about the intent of maintaining ceph-dashboard/*json do we want to keep existing ones? If we do, keeping install patch might be needed
> [#42194 (files)](https://github.com/ceph/ceph/pull/42194/files#diff-90fe51edeba2655428fd5bbeb383b9b2c9b9a393bda2b9355f205eac9046609aL1-L8)

Thanks a lot @ideepika! Let's see if the PR #42766 from @aaSharma14 resolves this issue.

**Pull request closed without merging**
