### PR TITLE
Update index.rst

### PR DESCRIPTION
**Pull request by RahulDas782**
Fixed the broken links to the APIs in the "API Documentation".

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by tchaikov** [comment]
@RahulDas782 could you point me to "the broken links" in https://docs.ceph.com/docs/master/api/ ?

**Comment by RahulDas782** [comment]
Actually, when I clicked on the APIs links provided in the https://github.com/ceph/ceph/blob/master/doc/api/index.rst, it shows an error that the "Page not found".

**Comment by tchaikov** [comment]
we use reStructuredText as the markup language for our document, and render it using Sphinx. the sources of these document are rendered by the GitHub web interface in a hypertext form and the links in them seem to be hyperlinks. but they are not meant to be so as in the source form even they seems to be "clickable".

**Comment by RahulDas782** [comment]
Oh, I got it!
Thanks for helping me.

**Pull request closed without merging**
