### PR TITLE
ceph-volume: fix batch report and respect ceph.conf config values

### PR DESCRIPTION
**Pull request by andrewschoen**
A couple small fixes for `ceph-volume lvm batch`. Respect the value of `bluestore_block_db_size` in ceph.conf and fix
the value of `% of device` in `ceph-volume lvm batch --report`.

https://tracker.ceph.com/issues/50957
https://tracker.ceph.com/issues/50958

### CODE REVIEW

**Comment by andrewschoen** [comment]
jenkins test ceph-volume tox

**Comment by andrewschoen** [comment]
jenkins test ceph-volume all

**Comment by andrewschoen** [comment]
jenkins test ceph-volume lvm centos8-bluestore-dmcrypt

**Review by guits — APPROVED** [review]

**Comment by tchaikov** [comment]
- https://pulpito.ceph.com/kchai-2021-06-05_02:55:59-rados-wip-kefu-testing-2021-06-05-0940-distro-basic-smithi/
- https://pulpito.ceph.com/kchai-2021-06-05_11:22:00-rados-wip-kefu-testing-2021-06-05-0940-distro-basic-smithi/

**Pull request merged**
