### PR TITLE
rpm: drop obsolete libs-compat and python-ceph-compat metapackages

### PR DESCRIPTION
**Pull request by smithfarm**
Fixes: http://tracker.ceph.com/issues/16353

### CODE REVIEW

**Comment by ktdreyer** [comment]
Assuming this passes Gitbuilder, it looks fine to me. Is Teuthology ok with this change?

**Comment by smithfarm** [comment]
Pushed `wip-16353` to gitbuilders.

**Comment by smithfarm** [comment]
> Is Teuthology ok with this change?

Would a single run of `upgrade/hammer-x` on CentOS 7 be sufficient to verify that? That's how we verified #8938

**Comment by ktdreyer** [comment]
Sure!

**Comment by smithfarm** [comment]
gitbuilder likes it

**Comment by smithfarm** [comment]
`./virtualenv/bin/teuthology-suite --verbose --suite upgrade/hammer-x --suite-branch master --ceph wip-nathan-testing --machine-type vps --priority 101 --filter centos_7 --limit 1 machine_types/vps.yaml`

**running** http://pulpito.ceph.com/smithfarm-2016-06-17_02:15:26-upgrade:hammer-x-wip-nathan-testing---basic-vps/

**Comment by smithfarm** [comment]
@ktdreyer Can you look at the teuthology failure? Maybe I need to add a `Provides:` for every `Obsoletes:` ?

**Comment by smithfarm** [comment]
@ktdreyer Nevermind. I added a commit to #9744 and am re-testing.

**Comment by smithfarm** [comment]
**running** http://pulpito.ceph.com/smithfarm-2016-06-17_12:21:29-upgrade:hammer-x-wip-nathan-testing---basic-vps/

**Comment by smithfarm** [comment]
Changelog:
* rebase

**Comment by smithfarm** [comment]
**running** http://pulpito.ceph.com/smithfarm-2016-06-20_00:38:21-upgrade:hammer-x-wip-nathan-testing---basic-vps/

**Comment by smithfarm** [comment]
Will wait until #9744 is merged, then rebase, then test.

**Comment by smithfarm** [comment]
* rebased
* added b7b0412 and f61e243
* repushed to gitbuilders

**Comment by smithfarm** [comment]
Hey Jenkins, test this please (146/146 Test #146: unittest_rbd_mirror .....................***Timeout 3600.05 sec)

**Comment by smithfarm** [comment]
gitbuilder passed

**Comment by smithfarm** [comment]
**running** http://pulpito.ceph.com/smithfarm-2016-08-09_18:57:07-upgrade:jewel-x-wip-16353---basic-smithi/

**Comment by smithfarm** [comment]
@ktdreyer @b-ranto Please review. I added two commits. It passes gitbuilder and the `upgrade/jewel-x` validation test.

**Comment by ktdreyer** [comment]
That change was needed. Thank you.
`Reviewed-by: Ken Dreyer <kdreyer@redhat.com>`

**Comment by b-ranto** [comment]
Why does this introduce devel-compat package? If we do indeed want to (re-)introduce it then it should also be mentioned in the commit message.

**Comment by smithfarm** [comment]
@b-ranto Good catch! I got confused while trying to resolve the rebase conflicts. Should be good to go now, but I will re-test.

**Comment by smithfarm** [comment]
Marking DNM pending merge of #10208.

**Comment by smithfarm** [comment]
* rebased
* removed additional trouble-making divider comments introduced by #10208 
* moved /sbin/ldconfig to `-p` in `%postun -n librbd1` (missed in original patchset)

**Comment by smithfarm** [comment]
**pass** http://pulpito.front.sepia.ceph.com/smithfarm-2016-08-16_14:30:30-upgrade:jewel-x-wip-16353---basic-smithi/

**Comment by smithfarm** [comment]
@ktdreyer Are you brave enough to merge this? ;-)

**Comment by smithfarm** [comment]
The related teuthology mod - https://github.com/ceph/teuthology/commit/4543fb64 - causes http://tracker.ceph.com/issues/17075

I *think* the tests themselves can be tweaked to overcome this.

**Comment by smithfarm** [comment]
I wrote to ceph-devel mailing list. If we want to drop `python-ceph-compat` from rpm, we should probably drop `python-ceph` from deb, too.

**Comment by smithfarm** [comment]
* dropped the commit that was dropping `python-ceph-compat` - we will carry this package as long as there are tests in ceph-qa-suite that install pre-hammer releases
* rebased

**Comment by smithfarm** [comment]
**pass** http://pulpito.front.sepia.ceph.com/smithfarm-2016-08-23_09:57:13-upgrade:jewel-x-wip-16353---basic-smithi/

**Comment by smithfarm** [comment]
@ktdreyer I'm ready for this to be merged. What about you?

**Comment by ktdreyer** [comment]
Let's do it

**Pull request merged**
