### PR TITLE
luminous: rgw: GetBucketCORS API returns Not Found error code when CORS configuration does not exist

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/38887

### CODE REVIEW

**Comment by smithfarm** [comment]
@cbodley Cherry-picking c97ee932f380a673b52ffcb1986b015e06246844 first seemed to be the right thing to do here, but perhaps it's not necessary/desirable?

**Comment by smithfarm** [comment]
@vumrao

**Comment by vumrao** [comment]
thanks @smithfarm

**Comment by yuriw** [comment]
[wip-yuri-testing-2019-06-25-1657-luminous](https://trello.com/c/4pVEYY2I/653-wip-yuri-testing-2019-06-25-1657-luminous)

**Pull request merged**
