### PR TITLE
mgr/cephadm: use fixed Grafana version

### PR DESCRIPTION
**Pull request by p-se**
Fixes: https://tracker.ceph.com/issues/45859

Signed-off-by: Patrick Seidensal <pseidensal@suse.com>

## Checklist
- [x] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by sebastian-philipp** [comment]
would it make sense to also remove the (wrong) defaults in  

https://github.com/ceph/ceph/blob/38e79b666d076d644905497e4ada8157acff6af6/src/cephadm/cephadm#L122

https://github.com/ceph/ceph/blob/38e79b666d076d644905497e4ada8157acff6af6/src/cephadm/cephadm#L135

and

https://github.com/ceph/ceph/blob/38e79b666d076d644905497e4ada8157acff6af6/src/cephadm/cephadm#L143

?

**Comment by sebastian-philipp** [comment]
green: http://pulpito.ceph.com/swagner-2020-06-17_12:51:58-rados:cephadm-wip-swagner3-testing-2020-06-17-1045-distro-basic-smithi/

* https://tracker.ceph.com/issues/46046

**Comment by p-se** [comment]
> would it make sense to also remove the (wrong) defaults in
> 
> https://github.com/ceph/ceph/blob/38e79b666d076d644905497e4ada8157acff6af6/src/cephadm/cephadm#L122
> 
> https://github.com/ceph/ceph/blob/38e79b666d076d644905497e4ada8157acff6af6/src/cephadm/cephadm#L135
> 
> https://github.com/ceph/ceph/blob/38e79b666d076d644905497e4ada8157acff6af6/src/cephadm/cephadm#L143
> 
> and
> 
> https://github.com/ceph/ceph/blob/38e79b666d076d644905497e4ada8157acff6af6/src/cephadm/cephadm#L155
> 
> ?

I'm not sure about that and don't have a strong opinion. `src/cephadm/cephadm` will probably ever only be used directly by developers who want to try out or debug something. It might make sense to deploy the same versions there which we support in `mgr/cephadm`. It might as well make sense to deploy the latest version, I don't know.

But if we decide to keep both versions in sync, we would actually want a unique source where both components take the versions from, which we cannot do as `src/cephadm/cephadm` is required to run as stand-alone as possible.

Do you have a tendency into any direction?

**Comment by sebastian-philipp** [comment]
greenish: http://pulpito.ceph.com/swagner-2020-06-24_11:30:44-rados:cephadm-wip-swagner3-testing-2020-06-24-1025-distro-basic-smithi/

Failed, cause I don't know if the upgrade actually works

* https://tracker.ceph.com/issues/46178 (slow ops)
* https://tracker.ceph.com/issues/46157 (upgrade)

**Comment by sebastian-philipp** [comment]
green: http://pulpito.ceph.com/swagner-2020-06-25_13:58:46-rados:cephadm-wip-swagner-testing-2020-06-25-1435-distro-basic-smithi/

**Pull request merged**
