### PR TITLE
rbd: python bindings fixes and improvements

### PR DESCRIPTION
**Pull request by rjfd**
This PR includes:
* Some python 3 fixes regarding the handling of strings for the data_pool
* Adds a new API function to retrieve the data_pool id
* Forces the returned timestamps to be in UTC

The above changes were made while implementing the "rbd management" functionality for the ceph dashboard https://github.com/rjfd/ceph/tree/wip-dashboard-rbd

### CODE REVIEW

**Comment by dillaman** [comment]
@rjfd Can you do me a favor and create a tracker ticket so that this can be backported to luminous?

**Comment by rjfd** [comment]
@dillaman sure. Do you want separate tickets for each one of the commits?

**Comment by dillaman** [comment]
@rjfd nah -- just one ticket for this entire PR is ok.

**Comment by rjfd** [comment]
@dillaman  http://tracker.ceph.com/issues/23609

Updated commit messages with `Fixes: ...`

**Pull request merged**
