### PR TITLE
osd: check queue_transaction return value

### PR DESCRIPTION
**Pull request by ztczll**
Signed-off-by: zhanglei <243290414@qq.com>

### CODE REVIEW

**Comment by joscollin** [comment]
Jenkins Retest this please

**Comment by joscollin** [comment]
Jenkins Retest this please

**Comment by joscollin** [comment]
Jenkins Retest this please

**Comment by liewegas** [comment]
retest this please

**Comment by liewegas** [comment]
http://pulpito.ceph.com/sage-2017-06-30_18:42:09-rados-wip-sage-testing-distro-basic-smithi/

**Comment by liewegas** [comment]
retest this please

**Comment by liewegas** [comment]
http://pulpito.ceph.com/sage-2017-07-03_15:41:59-rados-wip-sage-testing-distro-basic-smithi/

**Pull request merged**
