### PR TITLE
CMake: For CMake version <= 2.8.11, use LINK_PRIVATE and LINK_PUBLIC 

### PR DESCRIPTION
**Pull request by jack-changtao**
For CMake version <=2.8.11 ,it has no PUBLIC and PRIVATE keywords. It should use LINK_PRIVATE and LINK_PUBLIC instread to compile

Signed-off-by: changtao <changtao@hihuron.com>

### CODE REVIEW

**Comment by tchaikov** [comment]
see https://cmake.org/cmake/help/v2.8.11/cmake.html#command:target_link_libraries , https://cmake.org/cmake/help/v2.8.12/cmake.html#command:target_link_libraries. the PUBLIC and PRIVATE modes are introduced in 2.8.12.

and el7 comes with 2.8.11. while ubuntu 14.04 (trusty) has 2.8.12.

**Comment by tchaikov** [comment]
@cbodley and @alimaredia what do you think?

**Comment by cbodley** [comment]
@tchaikov thanks for the links. i also looked at the docs for v3.5 (https://cmake.org/cmake/help/v3.5/command/target_link_libraries.html), and see that they've kept legacy support for LINK_PUBLIC/PRIVATE without saying anything about deprecating them in the future. so i'm fine with using them instead.

the hard part will be getting everyone to use them going forward, without a buildbot that runs cmake 2.8.11. because PUBLIC is the default behavior for target_link_libraries, I suggest that we remove the 2 instances of LINK_PUBLIC in this patch. then we'll just hope that when someone needs to use PRIVATE, they'll copy-paste from one of the examples of LINK_PRIVATE. and maybe add a comment to the first use of LINK_PRIVATE to point out that it's needed for 2.8.11

**Comment by jack-changtao** [comment]
@tchaikov  @cbodley 

maybe, it is proper to use  two variables to define it .
If some one will need to use PRIVATE or PUBLIC, they will use ${PRIVATE} or ${PUBLIC}

if((CMAKE_MAJOR_VERSION GREATER 2) AND (CMAKE_MINOR_VERSION GREATER 8) AND  (CMAKE_PATCH_VERSION GREATER 11))
  set(PUBLIC PUBLIC)
  set(PRIVATE PRIVATE)
else ((CMAKE_MAJOR_VERSION GREATER 2) AND (CMAKE_MINOR_VERSION GREATER 8) AND  (CMAKE_PATCH_VERSION GREATER 11))
  set(PUBLIC LINK_PUBLIC)
  set(PRIVATE LINK_PRIVATE)
endif((CMAKE_MAJOR_VERSION GREATER 2) AND (CMAKE_MINOR_VERSION GREATER 8) AND  (CMAKE_PATCH_VERSION GREATER 11))

**Comment by tchaikov** [comment]
agree with @cbodley , @jack-changtao please see the inlined comment.  it might be simpler.

**Comment by jack-changtao** [comment]
@tchaikov   @cbodley 

have modified as commented，Thanks ！

**Comment by mattbenjamin** [comment]
This is needed ASAP, can we merge this?

**Pull request merged**
