### PR TITLE
luminous: osd: Warn about objects with too many omap entries 

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/23784

### CODE REVIEW

**Comment by tchaikov** [comment]
@smithfarm and @badone we might want to backport #21410 also.

**Comment by badone** [comment]
@tchaikov good catch. @smithfarm we should definitely grab  #21410 also.

**Comment by yuriw** [comment]
@smithfarm may need rebase

--- pr 21518 --- pulling https://github.com/smithfarm/ceph.git branch wip-23784-luminous
remote: Counting objects: 45, done.
remote: Total 45 (delta 39), reused 39 (delta 39), pack-reused 6
Unpacking objects: 100% (45/45), done.
From https://github.com/smithfarm/ceph
 * branch            wip-23784-luminous -> FETCH_HEAD
Auto-merging src/osd/osd_types.cc
Auto-merging src/mon/PGMap.cc
Merge made by the 'recursive' strategy.
 .../rados/singleton-nomsgr/all/large-omap-object-warnings.yaml  |  22 +++++
 qa/workunits/rados/test_large_omap_detection.py                 | 130 ++++++++++++++++++++++++++++
 src/common/options.cc                                           |  12 +++
 src/mon/PGMap.cc                                                |  33 +++++++
 src/osd/ECBackend.cc                                            |   3 +-
 src/osd/ECBackend.h                                             |   3 +-
 src/osd/PG.cc                                                   |  44 +++++++---
 src/osd/PG.h                                                    |   2 +
 src/osd/PGBackend.cc                                            |  47 +++++++---
 src/osd/PGBackend.h                                             |   9 +-
 src/osd/ReplicatedBackend.cc                                    |  21 ++++-
 src/osd/ReplicatedBackend.h                                     |   3 +-
 src/osd/osd_types.cc                                            |  28 ++++--
 src/osd/osd_types.h                                             |  13 ++-
 14 files changed, 333 insertions(+), 37 deletions(-)
 create mode 100644 qa/suites/rados/singleton-nomsgr/all/large-omap-object-warnings.yaml
 create mode 100755 qa/workunits/rados/test_large_omap_detection.py
--- done. these PRs were included:
Traceback (most recent call last):
  File "/home/yuriw/wip_master/src/script/build-integration-branch", line 64, in <module>
    print('\n'.join(prtext))
UnicodeEncodeError: 'latin-1' codec can't encode character u'\u2026' in position 651: ordinal not in range(256)

**Comment by smithfarm** [comment]
@yuriw OK, rebased, but that output looks more like a merge conflict with one of the other PRs in the integration branch.

**Comment by yuriw** [comment]
@smithfarm thx, looks like it I am having troubles to merge PRs even without this one, see this https://pastebin.com/MCNqRCgZ

**Comment by smithfarm** [comment]
@yuriw I see the problem now. PR https://github.com/ceph/ceph/pull/21655 had a … (Unicode Character 'HORIZONTAL ELLIPSIS' (U+2026)) in it. I removed that character, so you should be unblocked now, and will try to find out why the script doesn't handle that well, and fix it.

**Comment by smithfarm** [comment]
@yuriw I added an ellipsis character to #20401 which is the sole PR with the label `wip-smithfarm-testing` and ran `build-integration-branch wip-smithfarm-testing` - in my (utf-8) environment there was no traceback:

```
smithfarm@wilbur:~/src/ceph/smithfarm/ceph> build-integration-branch wip-smithfarm-testing
--- found 1 issues tagged with wip-smithfarm-testing
--- queried 1 prs
branch wip-smithfarm-testing-2018-05-03-2223
--- creating branch wip-smithfarm-testing-2018-05-03-2223
Switched to a new branch 'wip-smithfarm-testing-2018-05-03-2223'
--- pr 20401 --- pulling https://github.com/smithfarm/ceph.git branch wip-22558
From https://github.com/smithfarm/ceph
 * branch                  wip-22558  -> FETCH_HEAD
Adding qa/suites/rbd/mirror/cluster
Adding qa/suites/rbd/mirror/base
Auto-merging ceph.spec.in
Merge made by the 'recursive' strategy.
 ceph.spec.in | 3 +++
 1 file changed, 3 insertions(+)
--- done. these PRs were included:
https://github.com/ceph/ceph/pull/20401 - build/ops: rpm: provide files moved from ceph-test …
--- perhaps you want to: make && ctest -j12 && git push ci wip-smithfarm-testing-2018-05-03-2223
```

Can you try the same? I suspect your desktop environment's default character encoding is set to "latin1" instead of "utf-8" and that's why you're seeing the error.

**Comment by smithfarm** [comment]
@yuriw Also, in your environment could you try the following python shell commands and tell me what the output is?

```
$ python
Python 2.7.13 (default, Jan 03 2017, 17:41:54) [GCC] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> print sys.getfilesystemencoding()
UTF-8
>>> print sys.stdout.encoding
UTF-8
```

**Comment by yuriw** [comment]
@smithfarm whatever you did - work :+1:   Although I manually merged all PRs before, will wait for you next time :)
Thanks!

--- done. these PRs were included:
https://github.com/ceph/ceph/pull/21778 - luminous: ceph_test_rados_api_aio: fix race with full pool and osdmap
https://github.com/ceph/ceph/pull/21760 - luminous: mon/PGMap: Summarise OSDs in blocked/stuck requests
https://github.com/ceph/ceph/pull/21752 - luminous: osdc/Objecter: prevent double-invocation of linger op callback
https://github.com/ceph/ceph/pull/21740 - luminous: os/bluestore/bluefs_types: make block_mask 64-bit
https://github.com/ceph/ceph/pull/21737 - luminous: osd: publish osdmap to OSDService before starting wq threads
https://github.com/ceph/ceph/pull/21655 - luminous: qa: disable -Werror when compiling env_librados_test
https://github.com/ceph/ceph/pull/21518 - luminous: osd: Warn about objects with too many omap entries

**Pull request merged**
