### PR TITLE
osd: pg_stat_t encoding optimization

### PR DESCRIPTION
**Pull request by XinzeChi**
Signed-off-by: Xinze Chi <xinze@xsky.com>

### CODE REVIEW

**Comment by XinzeChi** [comment]
@liewegas , please review again. Thanks.

**Comment by XinzeChi** [comment]
```
TEST(EncodeBench, BL) {
    bufferlist be[6];
  for (int i = 0; i < 6; i++) {
    int count = 4 + 4 * i;
    for (int j = 0; j < count; j++) {
      be[i].append('x');
    }
  }
  for (int j = 0; j < 1000 * 1000; ++j) {
    bufferlist bll;
    for (int i = 0; i < 6; i++) {
      encode(be[i], bll);
    }
  }
}
```

 Base on the abvoe test case, https://github.com/XinzeChi/ceph/commit/395b210b60ff388d430321ced47cce237e7604cd could reduce from 1.924s to
1.405s on E5-2620 v2 @ 2.10GHz.

**Comment by liewegas** [comment]
Please update the object_stat_sum_t encoding in a single commit (that one is trivial).

pg_stat_t is harder because I'm pretty sure

  pg_t parent;
  __u32 parent_split_bits;

won't stay aligned.  But I suspect we'll get most of the win here just with object_stat_sum_t, even if we don't touch pg_stat_t...

**Comment by XinzeChi** [comment]
@liewegas , what about reorder the pg_stat_t, so we use two step the encode the struct. Using two step would be more easier for adding new members.
1. one step for the simple type member, such is utime_t, uint32_t, uint64_t (we could reorder these types and ensure that there are not padding among them ).  So we could `fast_encoding` these members.
2. The other step is for complex struct, such as pg_t parent, version. we encode these member one by one.

The new strategy is https://github.com/XinzeChi/ceph/commit/b53f087786fa4b72456eec8f578cd7ea0c0f9160.

**Comment by liewegas** [comment]
@XinzeChi I think teh pg_stat strategy makes sense, but we should do it separately as a follow-on, and overlap it with a feature bit we spend on something else (feature bits are getting scarce).  Let's leave it off this PR and get the other 3 types done first as they are simple.

**Comment by XinzeChi** [comment]
@liewegas , I See. Thanks for your quick reply. Please review again. Thanks.

**Comment by liewegas** [comment]
lgtm!

**Pull request merged**
