### PR TITLE
jewel: rgw: multipart uploads copy part support

### PR DESCRIPTION
**Pull request by mattbenjamin**
http://tracker.ceph.com/issues/18714

Replaces merged PR and its revert:
  https://github.com/ceph/ceph/pull/13068
  https://github.com/ceph/ceph/pull/13160 (reverted 13068)

### CODE REVIEW

**Comment by mattbenjamin** [comment]
@smithfarm this is a clean cherry-pick from the version we downstreamed, which had the following clean rgw suite runs:
http://pulpito.ceph.com/mbenjamin-2017-01-30_06:14:56-rgw-wip-jewel-mg-errortrans---basic-smithi/
http://pulpito.ceph.com/mbenjamin-2017-01-30_05:49:07-rgw-wip-jewel-mg-errortrans---basic-smithi/
(only errors seen are valgrind issues otherwise accounted for)

**Comment by smithfarm** [comment]
Hi @mattbenjamin There should be only one "cherry picked from" line in each commit, and it should point to the corresponding commit in master. Conflict resolution should be described. That's the ideal we strive for, anyway.

**Comment by smithfarm** [comment]
Ultimately, though, it's the RGW team that has to live with the code, so if @yehudasa approves we can test and merge it as is.

**Comment by smithfarm** [comment]
@mattbenjamin I looked at the first commit. It is a cherry pick of a commit that is already in jewel. So it can be dropped. Please go through the commits and remove all that are already in jewel.

**Comment by smithfarm** [comment]
Ah, now I see the commits are in jewel but were reverted, and this PR is re-introducing them plus an additional commit fixing the regression. Removing DNM. @mattbenjamin I understand you ran two RGW suites on this - can you post pulpito links?

**Comment by mattbenjamin** [comment]
@ktdreyer, @cbodley invalid extra cherry-picked-from hashes removed

**Comment by mattbenjamin** [comment]
@cbodley could you review (this is already downstreamed)

**Comment by mattbenjamin** [comment]
http://pulpito.ceph.com/mbenjamin-2017-03-27_20:45:25-rgw-wip-rgw-13219---basic-smithi/

**Comment by mattbenjamin** [comment]
@cbodley thanks casey!

**Pull request merged**
