### PR TITLE
test: Make screencandy optional for FreeBSD

### PR DESCRIPTION
**Pull request by wjwithagen**
- FreeBSD diff does not have a side-by-side with termwidth
   So differentiate for that

Signed-off-by: Willem Jan Withagen <wjw@digiware.nl>

### CODE REVIEW

**Comment by wjwithagen** [comment]
@tchaikov 
This is the other half of the PR, which is concenerd about `diff -y -W`

**Comment by dzafman** [comment]
I don't see where color is involved with this change.

**Comment by wjwithagen** [comment]
@dzafman 
I was under the impression from the commit that introduced this that Linux dif side-by-side would also do coloring of the output?

**Comment by dzafman** [comment]
@wjwithagen I don't see color on my terminal with "diff -y" although I see some color with "ls."

**Comment by wjwithagen** [comment]
@dzafman 
You are correct, man page says nothing about color. So removed that from commit and PR

**Comment by tchaikov** [comment]
```
TestMockInstanceWatcher_NotifySync.WaitingOnNonLeaderAcquireLeader
```
segfaulted

retest this please

**Comment by wjwithagen** [comment]
@tchaikov 
Seems like Jenkins is happy

**Pull request merged**
