### PR TITLE
os/bluestore: Restore HM-SMR functionality on BlueStore

### PR DESCRIPTION
**Pull request by agayev**
os/bluestore: Restore HM-SMR functionality on BlueStore

Recent changes have broken compilation and functionality of HM-SMR-related code.  This patch fixes those issues and restores HM-SMR functionality in BlueStore.

### CODE REVIEW

**Comment by agayev** [comment]
Hi @tchaikov and @ifed01.  Please take a look when you get a chance.  Thanks!

**Comment by tchaikov** [comment]
@agayev to prevent the code rot, i think you could package libzbc for CentOS8 or for debian, we can upload your packages to http://apt-mirror.front.sepia.ceph.com/lab-extras/8/ before they are packaged/accepted by Fedora and/or Debian and/or Ubuntu.

**Comment by agayev** [comment]
> @agayev to prevent the code rot, i think you could package libzbc for CentOS8 or for debian, we can upload your packages to http://apt-mirror.front.sepia.ceph.com/lab-extras/8/ before they are packaged/accepted by Fedora and/or Debian and/or Ubuntu.

Agreed.  Will do that.

**Comment by agayev** [comment]
> > @agayev to prevent the code rot, i think you could package libzbc for CentOS8 or for debian, we can upload your packages to http://apt-mirror.front.sepia.ceph.com/lab-extras/8/ before they are packaged/accepted by Fedora and/or Debian and/or Ubuntu.
> 
> Agreed. Will do that.

**Comment by agayev** [comment]
> > @agayev to prevent the code rot, i think you could package libzbc for CentOS8 or for debian, we can upload your packages to http://apt-mirror.front.sepia.ceph.com/lab-extras/8/ before they are packaged/accepted by Fedora and/or Debian and/or Ubuntu.
> 
> Agreed. Will do that.

@tchaikov After a discussion with Western Digital folks, it became clear that I should switch to another library, called libzbd, which supports both zoned SSDs and zoned HDDs.  I will introduce another PR that switches to libzbd and then send you the libzbd RPM.

**Comment by tchaikov** [comment]
- https://pulpito.ceph.com/kchai-2020-08-29_04:43:21-rados-wip-kefu-testing-2020-08-29-1106-distro-basic-smithi/
- https://pulpito.ceph.com/kchai-2020-08-29_13:54:19-rados-wip-kefu-testing-2020-08-29-1945-distro-basic-smithi/
- https://pulpito.ceph.com/kchai-2020-08-31_03:26:38-rados-wip-kefu-testing-2020-08-31-0934-distro-basic-smithi/

failures tracked by

- https://tracker.ceph.com/issues/47179

**Review by ifed01 — APPROVED** [review]

**Review by tchaikov — APPROVED** [review]

**Pull request merged**
