### PR TITLE
osdc/Objecter: fix narrow race with tid assignment

### PR DESCRIPTION
**Pull request by liewegas**
The operation completion could finish and be freed before we
do the info->register_tid assignment.  Avoid this by doing the
assignment in _op_submit itself.

Fixes: #14364
Signed-off-by: Sage Weil <sage@redhat.com>

### CODE REVIEW

**Comment by jdurgin** [comment]
lgtm

**Comment by jdurgin** [comment]
once the int/ceph_tid_t compile error is fixed, lgtm

**Comment by tchaikov** [comment]
```
[ RUN      ] TestJournalPlayer.PrefetchSkippedObject
test/journal/test_JournalPlayer.cc:377: Failure
Value of: wait_for_entries(player, 5, &entries)
  Actual: false
Expected: true
[  FAILED  ] TestJournalPlayer.PrefetchSkippedObject (10006 ms)
```

is this relevant?

**Comment by jdurgin** [comment]
The failure is from journaling changes for rbd - checking it out.

I did look again at the bug this is addressing, and I think the race was in assigning to the completion in librados, which still needs fixing (maybe pass a pointer to it to the objecter methods called in IoCtxImpl so it can be assigned under the lock)

**Comment by liewegas** [comment]
updated to fix the librados caller, too.

**Comment by liewegas** [comment]
passed rados suite in its current form, but doesn't address the other librados callers.

**Comment by jdurgin** [comment]
lgtm, covered all the librados callers

**Pull request merged**
