### PR TITLE
Client: fixup param type and return value

### PR DESCRIPTION
**Pull request by gongchuang**
optimization param type of make_request; 

Signed-off-by: gongchuang <gong.chuang@zte.com.cn>

### CODE REVIEW

**Comment by songbaisen** [comment]
@gongchuang  First you should put your two commit into one commit.
second, here look like build error.

**Comment by yonghengdexin735** [comment]
@gongchuang hi, I think  adding '-' to return value is unnecessary,
`    r = cfuse->init(newargc, newargv);
    if (r != 0) {
      cerr << "ceph-fuse[" << getpid() << "]: fuse failed to initialize" << std::endl;
      goto out_messenger_start_failed;
    }`
here is the judgment for return value.

**Comment by songbaisen** [comment]
@yonghengdexin735  Wa,ou. Bang,Bang.

**Comment by jcsp** [comment]
Was there any particular reason for changing the sign of the error return codes?  Was it breaking something?

The other (mds_rank) type change looks fine.

**Comment by gongchuang** [comment]
@jcsp no ohter reason,because i see FuseStore::start return negative value.for unified forms.

**Comment by jcsp** [comment]
@gongchuang those return codes get passed out as the status on the command line, which is a positive value: I don't think it's helpful to try and pass negative codes there.

Please remove the commit that changes the return values, and I'll merge this.

**Comment by jcsp** [comment]
@gongchuang ping

**Comment by gongchuang** [comment]
retest this please

**Pull request merged**
