### PR TITLE
Update .organizationmap

### PR DESCRIPTION
**Pull request by chenji-kael**

### CODE REVIEW

**Comment by dachary** [comment]
Could you also add
<pre>
Ji Chen &lt;insomnia@139.com> &lt;insomnia@139.com>
</pre>
to the .mailmap file please ?

**Comment by dachary** [comment]
@chenji-kael ping ?

**Comment by chenji-kael** [comment]
@dachary 
HI,I hava already add to the .mailmap

**Comment by dachary** [comment]
@chenji-kael you probably forgot to push to github ? It does not show here.

**Comment by chenji-kael** [comment]
@dachary 
I can find Ji Chen <insomnia@139.com> <insomnia@139.com> in  .mailmap
but  I find "Update .organizationmap #6565" has not been merged

**Comment by dachary** [comment]
@chenji-kael you are correct, thanks !

**Pull request merged**
