### PR TITLE
mimic: mds: extend reconnect period when mds is busy

### PR DESCRIPTION
**Pull request by ukernel**
https://tracker.ceph.com/issues/37740

### CODE REVIEW

**Comment by smithfarm** [comment]
jenkins re-test this please

**Comment by smithfarm** [comment]
@ukernel Ping

**Comment by ukernel** [comment]
fixed, sorry for the delay

**Comment by yuriw** [comment]
[wip-yuri3-testing-2019-02-13-0003-mimic](https://trello.com/c/iIVpcSc1/537-wip-yuri3-testing-2019-02-13-0003-mimic)

**Pull request merged**
