### PR TITLE
mgr/dashboard: Move router.url logic inside html template

### PR DESCRIPTION
**Pull request by bryanmontalvan**
## Description
This PR removes the `this.router.url` logic which was located in the `workbench-layout.component.ts` file and moved it into the HTML template section.

## Related PR
This PR builds upon that of #47016 specifically to the comments/suggestions left on https://github.com/ceph/ceph/pull/47016#pullrequestreview-1045383798

Signed-off-by: bryanmontalvan <bmontalv@redhat.com>
<hr />

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [x] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Review by epuertat — APPROVED** [review]
Nice clean-up @bryanmontalvan !

**Comment by nizamial09** [comment]
inorder for the dashboard cephadm e2e tests to pass I think the feature branch should be rebased with the main branch. For this PR we can ignore it though.

**Comment by nizamial09** [comment]
jenkins test api

**Comment by bryanmontalvan** [comment]
> @bryanmontalvan LGTM!
> 
> the commit title should have been also the same as pr title.
Hey @nizamial09 would you like me to edit the commit? Or were you leaving it as a suggestion for future commits?

**Comment by nizamial09** [comment]
jenkins test dashboard

**Comment by bryanmontalvan** [comment]
jenkins test dashboard

**Comment by bryanmontalvan** [comment]
jenkins test dashboard cephadm

**Comment by aaSharma14** [comment]
jenkins test dashboard cephadm

**Comment by bryanmontalvan** [comment]
jenkins test dashboard cephadm

**Comment by nizamial09** [comment]
> > @bryanmontalvan LGTM!
> > the commit title should have been also the same as pr title.
> > Hey @nizamial09 would you like me to edit the commit? Or were you leaving it as a suggestion for future commits?
> 
> let's merge as it is. we'll be squashing these commits in the end anyway to reduce the number of commits (while we are merging this into the main branch). But from the next commit onwards, it would be good to follow this https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst#commit-title

i am giving a pat to myself for instead of replying to your question i just edited my answer on to it.

**Pull request merged**
