### PR TITLE
mgr/dashboard: upgrade from old 'graph' type panels to the new 'timeseries' panel

### PR DESCRIPTION
**Pull request by aaSharma14**
The graph panel type is deprecated, and disappears after Grafana v9.1 (current version is 10.0) to prevent more old type panels being created. The current graph panels should be migrated to the timeseries panel type, to avoid potential problems with future Grafana versions.

Before - 

[Screencast from 2023-10-06 15-12-51.webm](https://github.com/ceph/ceph/assets/66050535/34acc740-3379-45fe-a53e-7a8f2479760a)

After -

[Screencast from 2023-10-11 12-52-17.webm](https://github.com/ceph/ceph/assets/66050535/8bb1a20b-4872-4001-832f-86c4ab71c969)

Fixes: https://tracker.ceph.com/issues/61720

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Review by nizamial09 — COMMENTED** [review]
@aaSharma14 could you put some screenshots/recordings to understand the changes visually?

**Comment by cloudbehl** [comment]
Graphs are missing the color, only the graph line is colored.

**Comment by aaSharma14** [comment]
> Graphs are missing the color, only the graph line is colored.

Thanks @cloudbehl , Updated the PR and the screen recording

**Comment by cloudbehl** [comment]
Thanks for fixing it, looks better. Is there a way we can remove the points in  line chart and have a line chart without points.

**Review by cloudbehl — APPROVED** [review]
LGTM

**Review by Pegonzal — COMMENTED** [review]
Overall looks good to me! Thanks Aashish.

But are these all the graphs that need to be updated? I still see `"type": "graph"` for a lot of graphs, in `osds-overiew.json`, `radosgw-detail.json`, `rbd-details.json`... to name a few. Is not needed to update these?

**Comment by aaSharma14** [comment]
> Overall looks good to me! Thanks Aashish.
> 
> But are these all the graphs that need to be updated? I still see `"type": "graph"` for a lot of graphs, in `osds-overiew.json`, `radosgw-detail.json`, `rbd-details.json`... to name a few. Is not needed to update these?

Thanks @Pegonzal for pointing this out. Updated all the references now

**Comment by aaSharma14** [comment]
jenkins test make check

**Comment by aaSharma14** [comment]
jenkins test dashboard

**Comment by aaSharma14** [comment]
jenkins test make check

**Comment by cloudbehl** [comment]
Looks like table is also deprecated , do we want to take it as part of this PR or different one?

**Comment by aaSharma14** [comment]
> Looks like table is also deprecated , do we want to take it as part of this PR or different one?

@cloudbehl , I think a different one should be good..Already too many files changed in this PR. Will open a separate tracker for that.

**Comment by aaSharma14** [comment]
jenkins test make check

**Review by Pegonzal — APPROVED** [review]

**Comment by aaSharma14** [comment]
jenkins test api

**Comment by aaSharma14** [comment]
jenkins retest this please

**Comment by aaSharma14** [comment]
jenkins test windows

**Pull request merged**
