### PR TITLE
rbd-nbd: add unmap options to support client behavior NBD_ATTR_CLIENT_FLAGS

### PR DESCRIPTION
**Pull request by gmayyyha**
Signed-off-by: Yanhu Cao <gmayyyha@gmail.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Review by idryomov — COMMENTED** [review]
What is the use case?  I assume to want to expose `NBD_CFLAG_DESTROY_ON_DISCONNECT` and `NBD_CFLAG_DISCONNECT_ON_CLOSE` flags?

I think this is wrong way to do it.  The UX is pretty bad, how should a user know what `--client-flag 1` or `--client-flag 3` mean?

Instead, we need to asses whether each of these flags make sense for `rbd-nbd` and if positive introduce separate boolean options with descriptive names, such as `--unmap-on-last-close` or something like that.

**Comment by gmayyyha** [comment]
> What is the use case? I assume you want to expose `NBD_CFLAG_DESTROY_ON_DISCONNECT` and `NBD_CFLAG_DISCONNECT_ON_CLOSE` flags?

Yes, it is.
> 
> I think this is the wrong way to do it. The UX is pretty bad, how should a user know what `--client-flag 1` or `--client-flag 3` mean?
> 
> Instead, we need to asses whether each of these flags make sense for `rbd-nbd` and if positive introduce separate boolean options with descriptive names, such as `--unmap-on-last-close` or something like that.

Makes sense, will fix it.

**Review by trociny — COMMENTED** [review]
@gmayyyha Could you please explain how the behaviour differs with this options in comparison with the default behaviour? Will "re-attach" (detach + attach) work? When it is supposed to be more useful than the default behaviour?

**Comment by gmayyyha** [comment]
> @gmayyyha Could you please explain how the behaviour differs with this options in comparison with the default behaviour? Will "re-attach" (detach + attach) work? When it is supposed to be more useful than the default behaviour?

Sometimes we get `block nbd0: Connection timed out` and `block nbd0: shutting down sockets` and  then do unmap and map again, the I/O errors are still there. Maybe there is something not cleaned up somewhere. We use ceph-v14, which does not support re-attach.

**Comment by trociny** [comment]
> Sometimes we get `block nbd0: Connection timed out` and `block nbd0: shutting down sockets` and then do unmap and map again, the I/O errors are still there. Maybe there is something not cleaned up somewhere.

And did setting the flag (which one of the twos, both?) help in your case?

I am just trying to understand the behaviour, and it seems reattach will not work in this case and we will need to document it or may be make rbd-nbd output some warnings or refuse `detach` if it was mapped with the flags set (it will not help though if one use a signal instead of `detach` command).

Another thing to discuss is do we need two options? Wouldn't it be the case that users would either use both or none? May be we just need one, e.g. `--unmap-delete`, that would set both flags? Or setting the flags could be the default behaviour disabled with `--allow-reattach` option.

**Pull request closed without merging**
