### PR TITLE
qa/suites/rados/upgrade: whitelist 'slow requests'

### PR DESCRIPTION
**Pull request by liewegas**
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by neha-ojha** [comment]
Should we just whitelist "slow request" instead of "slow requests" in thrashosds-health.yaml?

**Comment by liewegas** [comment]
IIRC the string is used for luminous but not mimic+, so I'm inclined to keep it here...

**Comment by neha-ojha** [comment]
@liewegas we might need similar whitelisting in qa/suites/upgrade/luminous-x

**Comment by liewegas** [comment]
I have a huge pile of fixes in wip-v2-upgrade, but i keep running across other failures that have accumulated.  getting closer!

**Pull request merged**
