### PR TITLE
mgr/dashboard: Reload all CephFS directories

### PR DESCRIPTION
**Pull request by Devp00l**
Now angular tree is used instead of ng2-tree, as it provides a better
way to dynamically load children and it provides a way to update all
children without losing all track of everything.

The loading icon will rotate now on any fetch.

The tree will detect new directories and removed directories.

Fixes: https://tracker.ceph.com/issues/42617
Signed-off-by: Stephan Müller <smueller@suse.com>

---
<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

---

directories-reload-all

### CODE REVIEW

**Comment by votdev** [comment]
What about using this layout?

Before:
Bildschirmfoto vom 2020-01-09 09-26-56

After:
Bildschirmfoto vom 2020-01-09 09-51-08

```
<div class="row">
  <div class="col-sm-4">
    <div class="card">
      <div class="card-header">
        <button type="button"
                [class.disabled]="loadingIndicator"
                class="btn btn-light pull-right"
                (click)="refreshAllDirectories()">
          <i [ngClass]="[icons.large, icons.refresh]"
             [class.fa-spin]="loadingIndicator"></i>
        </button>
      </div>
      <div class="card-body">
        <!--
          ng2-tree can't be used here as it cannot handle the reloading of all nodes
          without loosing all states of the current tree. The difference of both tree components is
          that ng2-tree is defined and configured by each node where as angular-tree
          is configured by a tree structure and consist of nodes that mainly hold data.
          Angular-tree is a lot better for dynamically loaded trees. The downside is that it's not
          possible to set individual icons for each node.
        -->
        <tree-root *ngIf="nodes"
                   [nodes]="nodes"
                   [options]="treeOptions">
          <ng-template #loadingTemplate>
            <i [ngClass]="[icons.spinner, icons.spin]"></i>
          </ng-template>
        </tree-root>
      </div>
    </div>
  </div>
  <!-- Selection details -->
  ...
```

**Comment by Devp00l** [comment]
jenkins test make check

**Comment by Devp00l** [comment]
Thanks @votdev for your suggestion, applied it :)

**Comment by Devp00l** [comment]
Fixed a problem with the reload icon when many directories have to be reloaded, the tree will take a lot longer than the API fetch to rebuild itself, therefore the reload icon didn't rotate until the tree was fully rebuild.

**Comment by bk201** [comment]
Nice work on only fetching a limited-depth of subdirectories when expanding a node.

Some questions:
- Select a non-root(`/`) directory and select the `/` again. The right detail pane still displays the detail of previous directory. Should we remove it?
leaf
root
- A following question is should we allow setting quotas/snapshot of the root directory `/`? I tried create snapshot on `/` manually and it seems works.

**Comment by Devp00l** [comment]
Thanks @tspmelo and @bk201 I will look into these issues.

**Comment by Devp00l** [comment]
@bk201 I implemented the usage of the root directory - which wasn't bevor. Now you can select the root directory and create snapshots of it :)

Addressed all comments :D

**Comment by callithea** [comment]
jenkins test dashboard backend

**Comment by Devp00l** [comment]
jenkins test make check

**Comment by callithea** [comment]
dashboard backend API test failure:
```
2020-01-29 14:31:27,728.728 ERROR:tasks.mgr.dashboard.helper:Request response: {"status": "500 Internal Server Error", "detail": "The server encountered an unexpected condition which prevented it from fulfilling the request.", "request_id": "6cee0438-fbbf-4e19-b54e-1fd5c3174f27"}                                                                                                                                                                                                                                                                                                                        
2020-01-29 14:31:27,729.729 INFO:__main__:test_ls_mk_rm_dir (tasks.mgr.dashboard.test_cephfs.CephfsTest) ... FAIL
2020-01-29 14:31:27,730.730 INFO:__main__:Running ['./bin/ceph', 'log', 'Ended test tasks.mgr.dashboard.test_cephfs.CephfsTest.test_ls_mk_rm_dir']
2020-01-29 14:31:29,196.196 INFO:__main__:Stopped test: test_ls_mk_rm_dir (tasks.mgr.dashboard.test_cephfs.CephfsTest) in 2.052601s
2020-01-29 14:31:29,197.197 INFO:__main__:
2020-01-29 14:31:29,197.197 INFO:__main__:======================================================================
2020-01-29 14:31:29,197.197 INFO:__main__:FAIL: test_ls_mk_rm_dir (tasks.mgr.dashboard.test_cephfs.CephfsTest)
2020-01-29 14:31:29,197.197 INFO:__main__:----------------------------------------------------------------------
2020-01-29 14:31:29,197.197 INFO:__main__:Traceback (most recent call last):
2020-01-29 14:31:29,197.197 INFO:__main__:  File "/home/jenkins-build/build/workspace/ceph-dashboard-pr-backend/qa/tasks/mgr/dashboard/test_cephfs.py", line 182, in test_ls_mk_rm_dir
2020-01-29 14:31:29,198.198 INFO:__main__:    self.ls_dir('/', 2, 3)
2020-01-29 14:31:29,198.198 INFO:__main__:  File "/home/jenkins-build/build/workspace/ceph-dashboard-pr-backend/qa/tasks/mgr/dashboard/test_cephfs.py", line 41, in ls_dir
2020-01-29 14:31:29,198.198 INFO:__main__:    return self._ls_dir(path, expectedLength, depth, "api")
2020-01-29 14:31:29,198.198 INFO:__main__:  File "/home/jenkins-build/build/workspace/ceph-dashboard-pr-backend/qa/tasks/mgr/dashboard/test_cephfs.py", line 52, in _ls_dir
2020-01-29 14:31:29,198.198 INFO:__main__:    self.assertStatus(200)
2020-01-29 14:31:29,198.198 INFO:__main__:  File "/home/jenkins-build/build/workspace/ceph-dashboard-pr-backend/qa/tasks/mgr/dashboard/helper.py", line 364, in assertStatus
2020-01-29 14:31:29,198.198 INFO:__main__:    self.assertEqual(self._resp.status_code, status)
2020-01-29 14:31:29,198.198 INFO:__main__:AssertionError: 500 != 200
2020-01-29 14:31:29,198.198 INFO:__main__:
2020-01-29 14:31:29,199.199 INFO:__main__:----------------------------------------------------------------------
2020-01-29 14:31:29,199.199 INFO:__main__:Ran 25 tests in 219.383s
2020-01-29 14:31:29,199.199 INFO:__main__:
2020-01-29 14:31:29,199.199 INFO:__main__:FAILED (failures=1)
2020-01-29 14:31:29,199.199 INFO:__main__:
2020-01-29 14:31:29,199.199 INFO:__main__:======================================================================
2020-01-29 14:31:29,199.199 INFO:__main__:FAIL: test_ls_mk_rm_dir (tasks.mgr.dashboard.test_cephfs.CephfsTest)
2020-01-29 14:31:29,200.200 INFO:__main__:----------------------------------------------------------------------
2020-01-29 14:31:29,200.200 INFO:__main__:Traceback (most recent call last):
2020-01-29 14:31:29,200.200 INFO:__main__:  File "/home/jenkins-build/build/workspace/ceph-dashboard-pr-backend/qa/tasks/mgr/dashboard/test_cephfs.py", line 182, in test_ls_mk_rm_dir
2020-01-29 14:31:29,200.200 INFO:__main__:    self.ls_dir('/', 2, 3)
2020-01-29 14:31:29,200.200 INFO:__main__:  File "/home/jenkins-build/build/workspace/ceph-dashboard-pr-backend/qa/tasks/mgr/dashboard/test_cephfs.py", line 41, in ls_dir
2020-01-29 14:31:29,200.200 INFO:__main__:    return self._ls_dir(path, expectedLength, depth, "api")
2020-01-29 14:31:29,200.200 INFO:__main__:  File "/home/jenkins-build/build/workspace/ceph-dashboard-pr-backend/qa/tasks/mgr/dashboard/test_cephfs.py", line 52, in _ls_dir
2020-01-29 14:31:29,200.200 INFO:__main__:    self.assertStatus(200)
2020-01-29 14:31:29,201.201 INFO:__main__:  File "/home/jenkins-build/build/workspace/ceph-dashboard-pr-backend/qa/tasks/mgr/dashboard/helper.py", line 364, in assertStatus
2020-01-29 14:31:29,201.201 INFO:__main__:    self.assertEqual(self._resp.status_code, status)
2020-01-29 14:31:29,201.201 INFO:__main__:AssertionError: 500 != 200
2020-01-29 14:31:29,201.201 INFO:__main__:
```

**Comment by callithea** [comment]
jenkins test dashboard

**Comment by Devp00l** [comment]
Oh breaked the test with my "depth" to "level" refactoring at the end... Fixed it.

**Comment by bk201** [comment]
jenkins test dashboard

**Comment by bk201** [comment]
jenkins test make check

**Comment by Devp00l** [comment]
I could not reproduce the E2E error locally. Not sure why it fails.

**Comment by Devp00l** [comment]
jenkins test dashboard

**Comment by callithea** [comment]
jenkins test dashboard

**Comment by callithea** [comment]
- [pkg build](https://shaman.ceph.com/builds/ceph/wip-laura-testing-32552-32829-33178/) [WIP]

**Comment by callithea** [comment]
- Latest [QA run](http://pulpito.ceph.com/laura-2020-02-21_06:19:27-rados:dashboard-wip-laura-testing-32552-32829-33178-distro-basic-smithi/) [6/6 failed]
- failure: `ERROR: setUpClass (tasks.mgr.dashboard.test_host.HostControllerTest)`, created an [issue](https://tracker.ceph.com/issues/44233)

**Pull request merged**
