### PR TITLE
luminous: rgw: remove_olh_pending_entries() does not limit the number of xattrs to remove

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/39177

### CODE REVIEW

**Comment by cbodley** [comment]
jenkins test make check

**Comment by smithfarm** [comment]
jenkins re-test this please

**Comment by smithfarm** [comment]
@cbodley This one seems to be failing "make check"

**Comment by yuriw** [comment]
[wip-yuri6-testing-2019-07-18-1538-luminous](https://trello.com/c/PDHX4Rvo/669-wip-yuri6-testing-2019-07-18-1538-luminous)

**Pull request merged**
