### PR TITLE
ceph-fuse crash in test_client_recovery

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/12882

### CODE REVIEW

**Comment by smithfarm** [comment]
@dachary could you look at the conflict resolution on 2c0d7fe ?

**Comment by dachary** [comment]
<pre>
$ commit=2c0d7fe ; picked_from=$(git show --no-patch --pretty=%b $commit  | perl -ne 'print if(s/.*cherry picked from commit (\w+).*/$1/)') ; diff -u --ignore-matching-lines '^[^+-]'   <(git show $picked_from) <(git show $commit)
--- /dev/fd/63	2015-09-04 17:26:58.337060413 +0200
+++ /dev/fd/62	2015-09-04 17:26:58.337060413 +0200
@@ -65,11 +70,11 @@
  function test_tiering()
  {
    # tiering
-@@ -1686,6 +1729,7 @@ MON_TESTS+=" mon_ping"
- MON_TESTS+=" mon_deprecated_commands"
- 
- OSD_TESTS+=" osd_bench"
-+OSD_TESTS+=" tiering_agent"
- 
- MDS_TESTS+=" mds_tell"
- MDS_TESTS+=" mon_mds"
+@@ -900,6 +943,7 @@ set +x
+ TESTS=(
+   mon_injectargs_SI
+   tiering
++  tiering_agent
+   auth
+   mon_misc
+   mon_mds
</pre>

**Comment by dachary** [comment]
the actual conflict resolution matches the description

**Comment by dachary** [comment]
<pre>
Reviewed-by: Loic Dachary &lt;ldachary@redhat.com>
</pre>
once the tests pass

**Pull request merged**
