### PR TITLE
osd/PG: revert approx size

### PR DESCRIPTION
**Pull request by aclamk**
http://tracker.ceph.com/issues/22654

This pull request is result of binary search on master branch to find why lately I got worse performance from incerta07.

I narrowed it to commit 024b5bcbf0259eeecba234cff882564947c3a525.

Test: 600s FIO/rbd 4K random write.

When enabled:
OSD0 consumed: 1h33:33
OSD1 consumed 1h38:49
FIO/rbd has iops: 29172

When it is reverted:
OSD0 consumed: 56:45
OSD1 consumed: 1h02:53
FIO/rbd has iops: 38344

It is possible that this change was a critical one, yet I am amazed by the scope in performance it caused.

### CODE REVIEW

**Comment by xiexingguo** [comment]
@aclamk I'd suggest do a complete revert of https://github.com/ceph/ceph/pull/18481/commits/46bfe362ed3fff41cee878e685e0d95cd1e41fcf instead of partially reverting it.

Actually the root cause  is lost to me. http://www.cplusplus.com/reference/list/list/size/ says the cost of list.size() is constant now in c++11, then perhaps it is because the compiler is smart enough to don't calculate list.size() at all if there is no consumers? dunno..

**Comment by tchaikov** [comment]
libstdc++'s `list::size()` is O(1) in C++11.

> then perhaps it is because the compiler is smart enough to don't calculate list.size() at all if there is no consumers

i don't follow this. could you expand it?

**Comment by xiexingguo** [comment]
> i don't follow this. could you expand it?

@tchaikov Sorry,  I think the root cause of this significant performance regression is still unclear to me. So probably I am totally wrong about it...

**Comment by liewegas** [comment]
Le's go ahead with reverting this until we understand what's going on?

**Comment by liewegas** [comment]
@xiexingguo what is wrong with this revert?  it looks like the whole thing to me?

**Comment by xiexingguo** [comment]
> what is wrong with this revert? it looks like the whole thing to me?

@liewegas We should revert `PrimaryLogPG::maybe_force_recovery()` also, see
 https://github.com/ceph/ceph/commit/46bfe362ed3fff41cee878e685e0d95cd1e41fcf#diff-fb41013d27e932534adb50eb3de2aaa5R714

**Comment by xiexingguo** [comment]
> Le's go ahead with reverting this until we understand what's going on?

Yeah, fine with me.

**Comment by xiexingguo** [comment]
> what is wrong with this revert? it looks like the whole thing to me?
> 
> @liewegas We should revert PrimaryLogPG::maybe_force_recovery() also, see
> 46bfe36#diff-fb41013d27e932534adb50eb3de2aaa5R714

If the way we count log size is critical, then it might also has a big impact on performance if pg is currently 
degraded/backfilling.

**Comment by songbaisen** [comment]
the  list.size() is O(n)  I prefer some books named <effective c++> and <more effective c++ >  also < stl  实现原理> are all good. like below https://book.douban.com/subject/1110934/  
😄

**Comment by tchaikov** [comment]
@songbaisen https://github.com/gcc-mirror/gcc/blob/master/libstdc%2B%2B-v3/include/bits/stl_list.h#L650

**Comment by liewegas** [comment]
maybe for some reason _GLIBCXX_USE_CXX11_ABI isn't defined when we build?

**Comment by songbaisen** [comment]
// count the number of nodes
      size_t
      _M_node_count() const
{ return std::distance(begin(), end()); }

Yes, that is O(n).
see below analyse:

http://www.cnblogs.com/sfwtoms/p/3952890.html

**Comment by tchaikov** [comment]
i think it's an issue of old libstdc++ implementation.

in libstdc++-5.1 and up
```c++
      /**  Returns the number of elements in the %list.  */
      size_type
      size() const _GLIBCXX_NOEXCEPT
      { return this->_M_node_count(); }
// ....
#if _GLIBCXX_USE_CXX11_ABI
//...
      // return the stored size
      size_t _M_node_count() const { return *_M_impl._M_node._M_valptr(); }
#else
//...
      // count the number of nodes
      size_t _M_node_count() const
      {
    return _S_distance(_M_impl._M_node._M_next,
               std::__addressof(_M_impl._M_node));
      }
#endif
```


in libstdc++-4.9
```c++
      /**  Returns the number of elements in the %list.  */
      size_type
      size() const _GLIBCXX_NOEXCEPT
      { return std::distance(begin(), end()); }
```

see https://github.com/gcc-mirror/gcc/commit/60f5701c7d058e2ad67ae9d0ab508c28dedc2308

and rhel 7.4 comes with gcc-c++-4.8.5-16.el7.x86_64. probably we can install [devtoolset-7](https://www.softwarecollections.org/en/scls/rhscl/devtoolset-7/) on our jenkins nodes and testbeds to address this issue? @aclamk @alfredodeza what do you think?

**Comment by songbaisen** [comment]
@tchaikov  👍 good!

**Comment by tchaikov** [comment]
@liewegas no,` _GLIBCXX_USE_CXX11_ABI` is always defined by default.

**Comment by liewegas** [comment]
I'm worried about having a severe performance regression when an old glibc is present.  Unless we have a cmake guard that breaks the build in that case or something?

@xiexingguo the approx_size is ugly but it isn't really problematic, right?

**Comment by xiexingguo** [comment]
> @xiexingguo the approx_size is ugly but it isn't really problematic, right?

```c++
size_t num_to_trim = pg_log.get_log().approx_size() - target;
if (num_to_trim < cct->_conf->osd_pg_log_trim_min) {
  return;
}
list<pg_log_entry_t>::const_iterator it = pg_log.get_log().log.begin();
     eversion_t new_trim_to;
     for (size_t i = 0; i < num_to_trim; ++i) {
       new_trim_to = it->version;
       ++it;
       if (new_trim_to > limit) {
 	new_trim_to = limit;
 	dout(10) << "calc_trim_to trimming to min_last_complete_ondisk" << dendl;
 	break;
       }
}
```

seems we'll always overestimate the num of logs to trim, hence we might be at risk of access-violation while increasing the `it` without checking against `it != pg_log.get_log().log.end()`

**Comment by songbaisen** [comment]
yes, I agree with sage wail may be someone build the code from source and with the old glibc, who will get bad performance.

**Comment by tchaikov** [comment]
> I'm worried about having a severe performance regression when an old glibc is present.  Unless we have a cmake guard that breaks the build in that case or something?

@liewegas see #18837. it's a little bit too cruel to the users w/ old devtools. and more importantly it will break our CI infrastructure where it's still using gcc 4.8 and libstdc++ 4.8. again a recent devtoolset like [devtoolset-7](https://www.softwarecollections.org/en/scls/rhscl/devtoolset-7/) is necessary to fix this issue and probably other unidentified performance issue if we compare the performance between two builds from gcc 7 and gcc 4.8.

**Comment by liewegas** [comment]
:+1: on the warning.  We still need to revert though :( since our release builds use those distros.

Hmm, is it possible to add the devtoolset to the BuildDepends?

**Comment by liewegas** [comment]
...because then we could turn that warning into an error.  That would be ideal :)

**Comment by tchaikov** [comment]
@liewegas good idea! see https://github.com/ceph/ceph-build/pull/909 and https://github.com/ceph/ceph/pull/18863

**Comment by xiexingguo** [comment]
@tchaikov @aclamk Can we do a complete revert of https://github.com/ceph/ceph/commit/46bfe362ed3fff41cee878e685e0d95cd1e41fcf? There is another path (`PrimaryLogPG::maybe_force_recovery()`) which this PR does not cover.

**Comment by tchaikov** [comment]
- http://pulpito.ceph.com/kchai-2017-11-10_06:12:07-rados-wip-kefu-testing-2017-11-10-1154-distro-basic-mira/
- http://pulpito.ceph.com/kchai-2017-11-12_17:42:28-rados-wip-kefu-testing-2017-11-10-1154-distro-basic-mira/

**Comment by branch-predictor** [comment]
I don't get it. If having the iterator checked for validity (breaking the "for" loop once it == pg_log.get_log().log.end()) is all that needs to be done in order to prevent access violations, then why we're not doing that?

**Comment by tchaikov** [comment]
@aclamk can we close this PR now that we are using GCC-7 for building on centos-7. and we will fail the build on GCC 4.8. see #19344 .

**Comment by tchaikov** [comment]
sorry! @aclamk @liewegas I was wrong. devtoolset-7 disables the new C++ ABI. so as you suspected: `_GLIBCXX_USE_CXX11_ABI=0`

**Comment by liewegas** [comment]
Hmm, how do we go about getting the new ABI then?  Do we need -8 or something?

**Comment by tchaikov** [comment]
@liewegas, I will test with different `-fabi-version=n` and `-fabi-compat-version=m` settings tomorrow, but I am sure `-D_GLIBCXX_USE_CXX11_ABI=1` does not work.

**Comment by tchaikov** [comment]
I am pasting the related discussion at https://www.spinics.net/lists/ceph-devel/msg39412.html:

see
https://git.centos.org/blob/rpms!devtoolset-gcc.git/2e5ef6c7934d4417e095855478736742b35bd0af/SPECS!gcc.spec#L1026
. so,

- “--with-default-libstdcxx-abi=gcc4-compatible”, the DTS-7's
libstdc++'s default ABI is the old one, and
- it does *not* use dual ABI.

hence what we have is the gcc4 compatible ABI, and nothing more, on centos 7.

unless the SCL guys change their minds, or we swing our own GCC build, we can *not* get the new ABI.

**Comment by tchaikov** [comment]
@aclamk could you cherry-pick 46bfe362ed3fff41cee878e685e0d95cd1e41fcf also, as suggested by @xiexingguo .

**Comment by aclamk** [comment]
@tchaikov Maybe I will just close this pull request?

**Comment by liewegas** [comment]
@aclamk @tchaikov Wait.. we need to keep approx_size since we don't have O(1) std::list::size(), right?  Which means we should drop that commit and stick with the original 2 commits?

**Comment by aclamk** [comment]
@tchaikov @liewegas 
1) Deleted 3rd commit.
2) I think we should leave it until we are sure all implementations have list.size() O(1).

**Comment by tchaikov** [comment]
@liewegas @aclamk sorry. i mean, we should revert https://github.com/ceph/ceph/commit/46bfe362ed3fff41cee878e685e0d95cd1e41fcf#diff-fb41013d27e932534adb50eb3de2aaa5R714 also.

**Comment by aclamk** [comment]
@tchaikov 
Reverted.

**Comment by tchaikov** [comment]
- http://pulpito.ceph.com/kchai-2018-01-11_05:03:22-rados-wip-kefu-testing-2018-01-11-1036-distro-basic-smithi/
- http://pulpito.ceph.com/kchai-2018-01-14_09:26:29-rados-wip-kefu-testing-2018-01-11-1036-distro-basic-mira/

failed tests are tracked by 

- http://tracker.ceph.com/issues/20236
- http://tracker.ceph.com/issues/22527
- http://tracker.ceph.com/issues/22668

**Comment by tchaikov** [comment]
for a related list::size() change, see #19813. unlike this one, it will be backported to luminous.

**Pull request merged**
