### PR TITLE
mgr/volumes/fs/operations: fix flake8 issues

### PR DESCRIPTION
**Pull request by anuradhak26**
mgr/volumes/fs/operations: Fix flake8 issues

Fixes : https://tracker.ceph.com/issues/51396

Signed-off-by: Anuradha Kulkarni <anuradhak1990@gmail.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Review by varshar16 — CHANGES_REQUESTED** [review]
Please change the commit title to `mgr/volumes/fs/operations: fix flake8 issues`. Otherwise looks good.

**Comment by varshar16** [comment]
You can amend your commit with `git commit --amend`

**Comment by anuradhak26** [comment]
> You can amend your commit with `git commit --amend`

Changed the commit title to : commit title to mgr/volumes/fs/operations: fix flake8 issues

**Comment by varshar16** [comment]
@anuradhak26 I don't see your new changes. You need to force push the changes. `git push -f <repo-name> <branch-name> `

**Review by varshar16 — APPROVED** [review]
Looks good, thank you!

**Comment by batrick** [comment]
https://tracker.ceph.com/projects/cephfs/wiki/Master#2021-October-02

**Pull request merged**
