### PR TITLE
common: FreeBSD wants the correct struct selection for ipv6

### PR DESCRIPTION
**Pull request by wjwithagen**
Lets see if this also works for Linux

Fixes: http://tracker.ceph.com/issues/21813

Signed-off-by: Willem Jan Withagen <wjw@digiware.nl>

### CODE REVIEW

**Comment by tchaikov** [comment]
@wjwithagen could you add "Fixes: http://tracker.ceph.com/issues/21813" in the commit message?

**Comment by wjwithagen** [comment]
@tchaikov @wido
This is first foremost a check to see if this does compile and execute on Linux.
The second qquestion is of course if this does the same as Wido intended.
FreeBSD/Clang actually complained about missing ipv6-structures, befor the reorganize.

**Comment by wjwithagen** [comment]
@tchaikov 
Will add the fixes: to the commit. 
But I'm not convinced that the test error is due to the code change....

**Comment by tchaikov** [comment]
@wjwithagen no, the test errors are not related to your change. it happens on arm64 recently. and i tried to reproduce them, but failed. =(

**Comment by tchaikov** [comment]
- http://pulpito.ceph.com/kchai-2018-04-01_23:31:58-rados-wip-kefu-testing-2018-04-02-0027-distro-basic-smithi/
- http://pulpito.ceph.com/kchai-2018-04-02_08:26:07-rados-wip-kefu-testing-2018-04-02-0027-distro-basic-mira/

**Pull request merged**
