### PR TITLE
cmake: add add_tox_test()

### PR DESCRIPTION
**Pull request by tchaikov**
to consolidate the tox tests

Signed-off-by: Kefu Chai <kchai@redhat.com>

- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by sebastian-philipp** [comment]
I've carefully crafted the defaults in `run_tox` to support my use case of running tox in my local environment with:

```
cd src/python-common
../script/run_tox.sh
```

Is this still supported?

**Comment by tchaikov** [comment]
no, it's not supported anymore. i need to improve the "try harder" part to use `$(pwd)` as another hint.

**Comment by tchaikov** [comment]
@epuertat i hope so. but see

https://github.com/ceph/ceph/blob/067db76a4c594631765077e8a109696b262205d6/src/pybind/mgr/dashboard/run-tox.sh#L29-L44

dashboard's `run-tox.sh` is more complicated than that of others'. probably we can figure some way to normalize this ? we have following options:

1. just drop it
1. make dashboard a special case in `run_tox.sh`
1. probably we can do some magic in `tox.ini`?

**Comment by tchaikov** [comment]
@sebastian-philipp i managed to add the support to your use case.

**Comment by tchaikov** [comment]
this change also addresses the test failure like
```
  4/180 Test  #10: run-tox-cephfs-shell ....................***Failed    2.93 sec
GLOB sdist-make: /home/jenkins-build/build/workspace/ceph-pull-requests/src/tools/cephfs/setup.py
flake8 create: /home/jenkins-build/build/workspace/ceph-pull-requests/src/tools/cephfs/.tox/flake8
flake8 installdeps: flake8
ERROR: invocation failed, logfile: /home/jenkins-build/build/workspace/ceph-pull-requests/src/tools/cephfs/.tox/flake8/log/flake8-1.log
ERROR: actionid=flake8
msg=getenv
cmdargs=[local('/home/jenkins-build/build/workspace/ceph-pull-requests/src/tools/cephfs/.tox/flake8/bin/pip'), 'install', '--download-cache=/home/jenkins-build/build/workspace/ceph-pull-requests/src/tools/cephfs/.tox/_download', 'flake8']
...
Usage:   
  pip install [options] <requirement specifier> [package-index-options] ...
  pip install [options] -r <requirements file> [package-index-options] ...
  pip install [options] [-e] <vcs project url> ...
  pip install [options] [-e] <local project path> ...
  pip install [options] <archive url/path> ...

no such option: --download-cache

ERROR: could not install deps [flake8]
```

because old tox version does not support newer pip, which dropped `--download-cache` option. see https://github.com/tox-dev/tox/issues/308

**Comment by smithfarm** [comment]
Did anyone test this with `run-make-check.sh` in a py3-only environment?

**Pull request merged**
