### PR TITLE
common/options: fix several out of date defaults and options added during yaml conversion

### PR DESCRIPTION
**Pull request by jdurgin**
Some of these got reset to old values (or old options were added back when they didn't exist anymore).

The ones most likely to have caused issues are the bluestore cache options.

### CODE REVIEW

**Comment by jdurgin** [comment]
I did not verify all the other fields, but type/presence/default values all match the old options.cc now.

**Comment by neha-ojha** [comment]
This fixes https://tracker.ceph.com/issues/50368.

**Review by tchaikov — APPROVED** [review]
thank you, Josh, for fixing and verifying the settings.

**Comment by tchaikov** [comment]
- https://pulpito.ceph.com/kchai-2021-04-17_15:15:57-rados-wip-kefu-testing-2021-04-16-2148-distro-basic-smithi/
- https://pulpito.ceph.com/kchai-2021-04-19_07:13:12-rados-wip-kefu-testing-2021-04-19-1211-distro-basic-smithi/

**Pull request merged**
