### PR TITLE
osdc: a new option to support return -ENOSPC when osd cluster is full.

### PR DESCRIPTION
**Pull request by liupan1111**
Signed-off-by: Pan Liu <liupan1111@gmail.com>

### CODE REVIEW

**Comment by liupan1111** [comment]
When the osd cluster is full, any io write(include create image) will be paused. This behavior is not reasonable for all cases: the user may want to catch this error, and delete some useless image or data.

**Comment by liupan1111** [comment]
@dillaman , could you help take a look? Thanks.

**Comment by jdurgin** [comment]
The LIBRADOS_OPERATION_FULL_TRY does this already - librbd specifically avoids using it because any error will be translated to EIO by virtual machines, often ending up in fs corruption since filesystems do not handle EIO well.

**Comment by dillaman** [comment]
@liupan1111 I agree with @jdurgin

**Comment by liupan1111** [comment]
@dillaman @jdurgin 
Your comment for fs/vm is reasonable to me, thanks. But I think it is about general io write. For the operation "rbd create", are you current behavior is expected? In my opinion, the user wants to get result(no matter success/fail).

**Comment by dillaman** [comment]
@liupan1111 I'm fine for improving the "create" path (even though you really should have better monitoring of your cluster to know you are nearing out-of-space). That would involve using the existing flag, however -- not this bypass route via the config. I think this specific PR should be closed.

**Comment by liupan1111** [comment]
@dillaman yeah. I agree to close this pr.

For  "create", yes, the idealized method is to monitor the capacity on time, but I prefer we could also handle this and return right info to the user. I will improve it later.

Thanks for this review

**Pull request closed without merging**
