### PR TITLE
pacific: cephadm: Fix selinux

### PR DESCRIPTION
**Pull request by jmolmo**
Backport of #39398 #39424 #39490

fixes: https://tracker.ceph.com/issues/49239

No conflicts

## Checklist
- [ x ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Review by sebastian-philipp — APPROVED** [review]

**Review by b-ranto — APPROVED** [review]

**Review by ktdreyer — APPROVED** [review]

**Comment by jmolmo** [comment]
jenkins test make check

**Comment by jmolmo** [comment]
jenkins test make check

**Comment by jmolmo** [comment]
jenkins test make check

**Comment by jmolmo** [comment]
https://pulpito.ceph.com/swagner-2021-02-24_09:34:13-rados:cephadm-wip-swagner2-testing-2021-02-23-1116-pacific-distro-basic-smithi/

1 failed: (bug not related)
https://pulpito.ceph.com/swagner-2021-02-24_09:34:13-rados:cephadm-wip-swagner2-testing-2021-02-23-1116-pacific-distro-basic-smithi/5911668/
https://tracker.ceph.com/issues/49456

2 dead: (seems to be environment creation issues)
https://pulpito.ceph.com/swagner-2021-02-24_09:34:13-rados:cephadm-wip-swagner2-testing-2021-02-23-1116-pacific-distro-basic-smithi/5911671/
https://pulpito.ceph.com/swagner-2021-02-24_09:34:13-rados:cephadm-wip-swagner2-testing-2021-02-23-1116-pacific-distro-basic-smithi/5911703/

**Pull request merged**
