### PR TITLE
nautilus: mgr/dashboard: Updating the inbuilt ssl providers error

### PR DESCRIPTION
**Pull request by nizamial09**
backport tracker: https://tracker.ceph.com/issues/48516

---

backport of https://github.com/ceph/ceph/pull/38484
parent tracker: https://tracker.ceph.com/issues/48490

this backport was staged using ceph-backport.sh version 16.0.0.6848
find the latest version at https://github.com/ceph/ceph/blob/master/src/script/ceph-backport.sh

### CODE REVIEW

**Comment by nizamial09** [comment]
jenkins test make check

**Comment by votdev** [comment]
jenkins test api

**Comment by votdev** [comment]
jenkins test make check

**Comment by votdev** [comment]
jenkins test make check

**Review by votdev — APPROVED** [review]
LGTM

**Review by epuertat — APPROVED** [review]

**Pull request merged**
