### PR TITLE
qa/suites/rados: Move cephadm/dashbard to dashboard/cephadm

### PR DESCRIPTION
**Pull request by sebastian-philipp**
The cephadm developers are typically not experts in reading
Cypress error messages

Signed-off-by: Sebastian Wagner <sebastian.wagner@suse.com>

Reasoning is, that in the past, I wasn't able to deal with **any** issues that came 
up in this suite. Having a backend API workload would have been 
easier for the cephadm folks to debug :cry: Like, e.g. https://tracker.ceph.com/issues/49350 

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by sebastian-philipp** [comment]
ping @ceph/dashboard

**Comment by sebastian-philipp** [comment]
ping @ceph/dashboard

**Comment by callithea** [comment]
jenkins test make check

**Review by epuertat — APPROVED** [review]
LGTM!

@callithea, aren't we already running the e2e in another QA task (or only in Jenkins)? I was grepping `qa/*` for `run-frontend-e2e-tests.sh` but couldn't find any reference.

**Comment by callithea** [comment]
> LGTM!
> 
> @callithea, aren't we already running the e2e in another QA task (or only in Jenkins)? I was grepping `qa/*` for `run-frontend-e2e-tests.sh` but couldn't find any reference.

Hi @epuertat, we do not make use of the `run-frontend-e2e-tests.sh` in teuthology QA runs because it is only able to run the tests against a vstart environment at the moment.
There's another script called `test_dashboard_e2e.sh` which is in `qa/workunits/cephadm/`.

**Review by nizamial09 — APPROVED** [review]
LGTM!

**Comment by tchaikov** [comment]
it conflicts with one of PRs in my batch. so dropped it.

**Comment by tchaikov** [comment]
@sebastian-philipp could you please rebase this change against master? i cannot merge it anymore.

**Pull request closed without merging**
