### PR TITLE
ceph-volume: don't create osd['block.db'] by default

### PR DESCRIPTION
**Pull request by jan--f**
Signed-off-by: Jan Fajerski <jfajerski@suse.com>

Fixes: http://tracker.ceph.com/issues/38472

### CODE REVIEW

**Comment by andrewschoen** [comment]
jenkins test ceph-volume tox

**Comment by andrewschoen** [comment]
jenkins test ceph-volume batch all

**Comment by jan--f** [comment]
@andrewschoen Seems like there's an issue with the ansible tests on xenial? One of the four failures is a failed git clone.

**Comment by jan--f** [comment]
@andrewschoen seems like #25542 was never backported, so luminous and mimic shouldn't be affected right now. Wondering if I should backport #25542 though?

**Comment by andrewschoen** [comment]
@jan--f I think we should backport #25542 as well. In the past we've needed to backport every ceph-volume PR.

**Pull request merged**
