### PR TITLE
rgw: fix default storage class for get_compression_type

### PR DESCRIPTION
**Pull request by cbodley**
if a PUT request does not specify a storage class, use the default STANDARD storage class when looking up its compression type

Fixes: https://tracker.ceph.com/issues/40935

### CODE REVIEW

**Comment by ivancich** [comment]
jenkins test make check

**Comment by ivancich** [comment]
@cbodley: can you see any way this commit might be responsible for this boto failure?
`2019-09-12T20:41:46.347 INFO:teuthology.orchestra.run.smithi101.stderr:s3tests.functional.test_s3.test_append_object ... FAIL`

In my QA/testing branch, this was the 4th of 5 prs applied to master. Everything passed when I had just the first 3 prs, but as soon as I added this to the sequence, I'd this failure.

Just to verify this, I'm building a master + this commit (`wip-eric-testing-1-bisect-7`). And I'm building a master plus prs 1, 2, 3, and 5 -- everything but this (`wip-eric-testing-1-bisect-6`). I'll run them on an abbreviated rgw/verify when built.

If the theory is correct, the former will fail and the latter will succeed (unless the problem is an interaction of this pr one of the 3 previous prs). But I wanted to give you a heads up as to how things are currently looking.

**Comment by cbodley** [comment]
@ivancich this does appear to be the culprit, yeah. append doesn't seem to work with compression enabled

**Comment by cbodley** [comment]
^ cc @mattbenjamin

**Comment by mattbenjamin** [comment]
thanks, casey ++

**Comment by ivancich** [comment]
@cbodley, @mattbenjamin OK, I've removed this from my QA pr set. I adjusted some labels, but I don't know what's next for this honorable pr.

**Comment by cbodley** [comment]
i added an extra commit that disables compression and encryption for Appendable objects. the issue with compression is that each small 3-byte append was overwriting the RGW_ATTR_COMPRESSION metadata, rather than appending to what was already there. that metadata includes the `orig_size` which tracks the uncompressed object size, which Appendable objects use to report the `x-rgw-next-append-position`

**Comment by cbodley** [comment]
with the second commit, appendobject test cases are passing with compression=zlib:
> s3tests.functional.test_s3.test_append_object ... ok
s3tests.functional.test_s3.test_append_normal_object ... ok
s3tests.functional.test_s3.test_append_object_position_wrong ... ok

**Comment by cbodley** [comment]
passed qa in http://pulpito.ceph.com/cbodley-2019-09-18_14:51:41-rgw-wip-cbodley-testing-distro-basic-smithi/

(slow ops failures tracked in https://tracker.ceph.com/issues/41834)

**Comment by ivancich** [comment]
@cbodley Glad it got merged!!

**Comment by hanfengzhe-hi** [comment]
Hello, @cbodley.
 Could you tell me which ceph-version these changes will update?

**Comment by cbodley** [comment]
@hanfengzhe-hi the backport is staged for the next nautilus release in https://github.com/ceph/ceph/pull/31026

**Pull request merged**
