### PR TITLE
doc: add mimic 13.2.3 and 13.2.4 to releases chart

### PR DESCRIPTION
**Pull request by smithfarm**
Signed-off-by: Nathan Cutler <ncutler@suse.com>

- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by smithfarm** [comment]
jenkins render docs

**Comment by smithfarm** [comment]
@noahdesu Looks like this PR exposed a small bug in releases.yml

When the `released` dates of two versions are the same, like this:

```
releases:
  mimic:
    releases:
      - version: 13.2.4
        released: 2019-01-07
      - version: 13.2.3
        released: 2019-01-07
```

The "latest" column gets populated with 13.2.3 instead of 13.2.4.

I know, it's an edge case, but it does happen occasionally. Is is something you can fix easily, or should I change the release date of 13.2.4 to e.g. 2019-01-08?

**Comment by noahdesu** [comment]
@smithfarm very easy to change. will have something shortly

**Comment by noahdesu** [comment]
@smithfarm https://github.com/ceph/ceph/pull/25972

**Pull request merged**
