### PR TITLE
mimic: rbd_mirror: don't report error if image replay canceled

### PR DESCRIPTION
**Pull request by ashishkumsingh**
https://tracker.ceph.com/issues/37909

### CODE REVIEW

**Comment by smithfarm** [comment]
jenkins re-test this please

**Comment by smithfarm** [comment]
jenkins re-test this please

**Comment by yuriw** [comment]
[wip-yuri5-testing-2019-04-30-2026-mimic](https://trello.com/c/9KYPzFev/602-wip-yuri5-testing-2019-04-30-2026-mimic)

**Comment by yuriw** [comment]
[wip-yuri5-testing-2019-05-03-1956-mimic](https://trello.com/c/uJsMtpy3/606-wip-yuri5-testing-2019-05-03-1956-mimic)

**Pull request merged**
