### PR TITLE
cmake,test: run ceph-disk tests with cmake

### PR DESCRIPTION
**Pull request by tchaikov**

### CODE REVIEW

**Comment by tchaikov** [comment]
the failed/not finished tests are

- ceph_objectstore_tool.py
- cephtool-test-rados.sh
- cephtool-test-mon.sh
- test-ceph-helpers.sh

they are not relevant.

**Comment by tchaikov** [comment]
retest this please.

**Comment by liewegas** [comment]
@alimaredia can we merge this?

**Comment by alimaredia** [comment]
just ran it, and it passed on my local machine, lgtm!

**Pull request merged**
