### PR TITLE
librbd:reads larger than cache size hang.

### PR DESCRIPTION
**Pull request by s09816**
Fixes:#13164

Signed-off-by: Lu Shi <shi.lu@h3c.com>

### CODE REVIEW

**Comment by dillaman** [comment]
@s09816 Can you also update the TestLibRBD.LargeCacheRead test case to catch the original issue?

**Comment by s09816** [comment]
@dillaman I have updated the TestLibRBD.LargeCacheRead test case  to catch the original issue. 
Please help to confirm whether it is right,thanks.

**Comment by dillaman** [comment]
@s09816 The unit test didn't catch the issue on my build.  The following changes did catch the issue: http://fpaste.org/270497/44301512/

**Comment by s09816** [comment]
@dillaman I have modified the pull request according to your changes.

**Comment by dillaman** [comment]
LGTM

**Pull request merged**
