### PR TITLE
qa/tasks/rebuild_mondb: grant "mgr:allow *" to client.admin

### PR DESCRIPTION
**Pull request by tchaikov**
Fixes: http://tracker.ceph.com/issues/19439
Signed-off-by: Kefu Chai <kchai@redhat.com>

### CODE REVIEW

**Comment by tchaikov** [comment]
still fails: http://pulpito.ceph.com/kchai-2017-04-02_04:22:48-rados-master---basic-mira/978396/

**Comment by liewegas** [comment]
My guess is that you also need to set the caps properly for the osd and mds daemons (mgr = allow profile foo) and for the mgr daemon itself (mon = allow profile mgr).  and the mon (mgr = allow profile mon).

**Comment by liewegas** [comment]
In any case, this much of the fix is right

**Comment by tchaikov** [comment]
tested at http://pulpito.ceph.com/kchai-2017-05-27_18:21:24-rados-wip-mgr-stats-kefu---basic-mira/

**Pull request merged**
