### PR TITLE
mgr/diskprediction: Document guide add predictor accuracy

### PR DESCRIPTION
**Pull request by hsiang41**
Add local/cloud predictor accuracy value

Signed-off-by: Rick Chen <rick.chen@prophetstor.com>

- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by hsiang41** [comment]
retest this please.

**Comment by sebastian-philipp** [comment]
jenkins render docs please

**Comment by hsiang41** [comment]
jenkins render docs please

**Comment by hsiang41** [comment]
retest this please.

**Comment by hsiang41** [comment]
retest this please.

**Comment by hsiang41** [comment]
retest this please.

**Comment by hsiang41** [comment]
@liewegas Can you help to approve this changed for the document?

**Pull request merged**
