### PR TITLE
quincy: mgr/dashboard: dashboard help command showing wrong syntax for login-banner 

### PR DESCRIPTION
**Pull request by Sarthak0702**
backport tracker: https://tracker.ceph.com/issues/56163

---

backport of https://github.com/ceph/ceph/pull/46765
parent tracker: https://tracker.ceph.com/issues/56137

this backport was staged using ceph-backport.sh version 16.0.0.6848
find the latest version at https://github.com/ceph/ceph/blob/main/src/script/ceph-backport.sh

### CODE REVIEW

**Review by aaSharma14 — APPROVED** [review]

**Comment by Sarthak0702** [comment]
jenkins test dashboard

**Comment by Sarthak0702** [comment]
jenkins test dashboard cephadm

**Comment by Sarthak0702** [comment]
`ceph dashboard cephadm e2e tests` failures looks unrelated to this PR.

**Comment by epuertat** [comment]
Unrelated failure: https://tracker.ceph.com/issues/56122

**Pull request merged**
