### PR TITLE
pacific: pybind/mgr/progress: enforced try and except on accessing event dictionary

### PR DESCRIPTION
**Pull request by kamoltat**
There is a certain race condition scenario where
an event gets deleted while the progress module
iterates through the ``events`` dictionary,
without a ``try and except``, this will cause
an unhandled exception error and will crash
the module.

This commit will enforce ``try and except``
on every part of the code where we are accessing
the ``events`` dictionary.

Fixes: https://tracker.ceph.com/issues/53803

Backporting the relevant commits from master PR:
#44553

Signed-off-by: Kamoltat <ksirivad@redhat.com>

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by kamoltat** [comment]
flake8 error in make check:
`progress/__init__.py:5: note: In module imported here:
progress/module.py: note: In member "_process_pg_summary" of class "Module":
progress/module.py:637: error: Too few arguments for "pg_update" of "PgRecoveryEvent"
progress/module.py:637: error: Argument 2 to "pg_update" of "PgRecoveryEvent" has incompatible type "Logger"; expected "bool"
Found 2 errors in 1 file (checked 17 source files)
 `

**Review by sebastian-philipp — APPROVED** [review]

**Comment by kamoltat** [comment]
jenkins test make check

**Comment by kamoltat** [comment]
jenkins test ceph API

**Comment by kamoltat** [comment]
jenkins test api

**Comment by kamoltat** [comment]
https://pulpito.ceph.com/ksirivad-2022-01-20_14:42:21-rados:mgr-wip-ksirivad-pacific-backport-44553-distro-basic-smithi/6628999/
Failure due to PG recovery event not getting triggered. This is because no pgs were affected by the osd.0 being marked out, this happened because the osd.0 id was not in any of the PG's acting sets (both old osd map and new osd map).

**Comment by kamoltat** [comment]
https://pulpito.ceph.com/ksirivad-2022-01-20_14:42:21-rados:mgr-wip-ksirivad-pacific-backport-44553-distro-basic-smithi/6628995/ 
fails because the test in `test_osd_came_back()` is not deterministic enough.  In `_simulate_back_in()` , although it did correctly found and counted an osd.in event by the time it access the event progress again it already completed.

**Comment by kamoltat** [comment]
This PR addresses a separate issue to the failure we see above, 
https://github.com/ceph/ceph/pull/44745 is the one that addresses the failure that we see above. We can merge this PR first (#44672).

**Pull request merged**
