### PR TITLE
rgw: cmake configure error on fedora-37/rawhide

### PR DESCRIPTION
**Pull request by kalebskeithley**
see
https://kojipkgs.fedoraproject.org//work/tasks/6624/82706624/build.log,
excerpted below

...
CMake Error: The inter-target dependency graph contains the following
strongly connected component (cycle): "rgw_common" of type
STATIC_LIBRARY depends on "dbstore" (weak) depends on "sqlite_db" (weak)
"dbstore" of type SHARED_LIBRARY depends on "rgw_common" (weak) depends
on "sqlite_db" (weak) "sqlite_db" of type SHARED_LIBRARY depends on
"rgw_common" (weak) depends on "dbstore" (weak) At least one of these
targets is not a STATIC_LIBRARY. Cyclic dependencies are allowed only
among static libraries. CMake Generate step failed. Build files cannot
be regenerated correctly.
...

https://tracker.ceph.com/issues/54266

Signed-off-by: Kaleb S. KEITHLEY <kkeithle@redhat.com>

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by kalebskeithley** [comment]
jenkins test docs

**Comment by cbodley** [comment]
thanks @kalebskeithley. i think this PR is fine to merge as is, but we'll have to tackle this as part of the modularization work

**Comment by kalebskeithley** [comment]
jenkins test docs

**Review by soumyakoduri — APPROVED** [review]

**Comment by kalebskeithley** [comment]
http://pulpito.front.sepia.ceph.com/kkeithle-2022-02-15_12:39:25-rgw-wip-kkeithley-rgwcmake-distro-default-smithi/

**Pull request merged**
