### PR TITLE
pacific: cmake: check for python(\d)\.(\d+) when building boost

### PR DESCRIPTION
**Pull request by tchaikov**
now that python3.10 has two digits as its minor version, we should be
able to match it.

this change fixes the build with python3.10. without this change, we'd
have

error: wrong library name 'python310' in the --with-<library> option.

when building with python3.10

Signed-off-by: Kefu Chai <tchaikov@gmail.com>
(cherry picked from commit 66b1e8cecdbabd76a131dc239f6f41d5374fbd32)

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/master/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by tchaikov** [comment]
https://shaman.ceph.com/builds/ceph/pacific-pr-44007/2ac509ce9dbb8201a349b46bafbb642a455c54c2/

**Review by dirkmueller — APPROVED** [review]

**Comment by tserong** [comment]
This fixes the cmake part, but isn't sufficient to get a build. With this patch applied to pacific, I now get:

```
[  182s] libs/python/src/exec.cpp: In function 'boost::python::api::object boost::python::exec_file(const char*, api::object, api::object)':
[  182s] libs/python/src/exec.cpp:109:14: error: '_Py_fopen' was not declared in this scope; did you mean '_Py_wfopen'?
[  182s]   109 |   FILE *fs = _Py_fopen(f, "r");
[  182s]       |              ^~~~~~~~~
[  182s]       |              _Py_wfopen
```

The fix for that's in boost 1.76 (see https://github.com/boostorg/python/commit/cbd2d9f033c61d29d0a1df14951f4ec91e7d05cd) but ceph pacific is using 1.73. Actually, python3.10 builds shouldn't even work in ceph master right now, as that's using boost 1.75...

**Comment by tchaikov** [comment]
> This fixes the cmake part, but isn't sufficient to get a build. With this patch applied to pacific, I now get:
> 
> ```
> [  182s] libs/python/src/exec.cpp: In function 'boost::python::api::object boost::python::exec_file(const char*, api::object, api::object)':
> [  182s] libs/python/src/exec.cpp:109:14: error: '_Py_fopen' was not declared in this scope; did you mean '_Py_wfopen'?
> [  182s]   109 |   FILE *fs = _Py_fopen(f, "r");
> [  182s]       |              ^~~~~~~~~
> [  182s]       |              _Py_wfopen
> ```
> 
> The fix for that's in boost 1.76 (see [boostorg/python@cbd2d9f](https://github.com/boostorg/python/commit/cbd2d9f033c61d29d0a1df14951f4ec91e7d05cd)) but ceph pacific is using 1.73. Actually, python3.10 builds shouldn't even work in ceph master right now, as that's using boost 1.75...

@tserong hi Tim, when building on a bleeding edge distro, probably we should use `WITH_SYSTEM_BOOST=ON`?

**Comment by tserong** [comment]
> @tserong hi Tim, when building on a bleeding edge distro, probably we should use `WITH_SYSTEM_BOOST=ON`?

Good idea, I'll give that a shot.

**Review by tserong — APPROVED** [review]
Approving given this backport works just fine to fix the cmake problem (the issue with `_Py_fopen` will want fixing separately, so no reason to hold this PR up, I think).

**Comment by tserong** [comment]
OK, I've figured out the `_Py_fopen` thing. https://github.com/boostorg/python/commit/cbd2d9f033c61d29d0a1df14951f4ec91e7d05cd against boost 1.76.0 was a red herring. The issue appears to already be fixed in boost 1.75.0, which is included in ceph quincy and newer. Specifically https://github.com/boostorg/python/blob/boost-1.75.0/src/exec.cpp#L107-L115, which uses `fopen` if `PY_VERSION_HEX >= 0x03010000`.

So, should I open a separate upstream tracker issue for ` error: '_Py_fopen' was not declared in this scope` when building Ceph Pacific against Python 3.10? Or should I assume openSUSE is the only place this combination occurs and just fix it downstream?

**Comment by dirkmueller** [comment]
can we backport https://github.com/boostorg/python/commit/d9f06052e28873037db7f98629bce72182a42410 ?

**Comment by tserong** [comment]
> can we backport [boostorg/python@d9f0605](https://github.com/boostorg/python/commit/d9f06052e28873037db7f98629bce72182a42410) ?

Yeah, I think I've figured out a way to do that which doesn't totally suck :-) Will update once I get a test build done.

**Comment by tserong** [comment]
I've got this downstream in https://github.com/SUSE/ceph/pull/483. My trick for getting that boost patch in is https://github.com/SUSE/ceph/pull/483/commits/b1862013b279dc45cb812b7f0e87392d80d169fd. @tchaikov do you think that would be acceptable for upstream too?

**Comment by ljflores** [comment]
http://pulpito.front.sepia.ceph.com/yuriw-2022-06-07_19:48:58-rados-wip-yuri6-testing-2022-06-07-0955-pacific-distro-default-smithi/

Failures, unrelated:
    1. https://tracker.ceph.com/issues/53939
    2. https://tracker.ceph.com/issues/53827
    3. https://tracker.ceph.com/issues/54071
    4. https://tracker.ceph.com/issues/54992
    5. https://tracker.ceph.com/issues/49525
    6. https://tracker.ceph.com/issues/55741
    7. https://tracker.ceph.com/issues/52321
    8. https://tracker.ceph.com/issues/50222
    9. https://tracker.ceph.com/issues/53501
    10. https://tracker.ceph.com/issues/56028 --> opened a new Tracker for this; it is unrelated to the PRs that were tested in this run.

Details:
    1. ceph-nfs-upgrade, pacific: Upgrade Paused due to UPGRADE_REDEPLOY_DAEMON: Upgrading daemon osd.0 on host smithi103 failed - Ceph - Orchestrator
    2. cephadm exited with error code when creating osd: Input/Output error. Faulty NVME? - Ceph - Orchestrator
    3. rados/cephadm/osds: Invalid command: missing required parameter hostname(<string>) - Ceph - Orchestrator
    4. cannot stat '/etc/containers/registries.conf': No such file or directory - Ceph - Orchstrator
    5. found snap mapper error on pg 3.2s1 oid 3:4abe9991:::smithi10121515-14:e4 snaps missing in mapper, should be: dc was r -2...repaired - Ceph - RADOS (pending Pacific backport)
    6. cephadm/test_dashboard_e2e.sh: Unable to find element `cd-modal .custom-control-label` when testing on orchestrator/01-hosts.e2e-spec.ts - Ceph - Mgr - Dashboard
    7. qa/tasks/rook times out: 'check osd count' reached maximum tries (90) after waiting for 900 seconds - Ceph - Orchestrator
    8. osd: 5.2s0 deep-scrub : stat mismatch - Ceph - RADOS
    9. Exception when running 'rook' task. - Ceph - Orchestrator
    10. thrash_cache_writeback_proxy_none: FAILED ceph_assert(version == old_value.version) in src/test/osd/RadosModel.h - Ceph - RADOS

**Pull request merged**
