### PR TITLE
mgr/dashboard: add dueTime to rgw bucket validator

### PR DESCRIPTION
**Pull request by nizamial09**
the unique async validator which checks if the typed bucket name is existing or not in the bucket creation form, sends a request to the backend on each keystroke. Each keystroke will raise an exception if the bucket is not found.

this affects other areas where unique async validator is being reused. eg: dashboard user form...

Fixes: https://tracker.ceph.com/issues/66221

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Comment by nizamial09** [comment]
jenkins retest this please

**Review by Pegonzal — COMMENTED** [review]
Thanks @nizamial09 for the PR. It would be nice to get rid of all the error messages, but to me seems a little bit risky to add a window of time (500ms) where you can incorrectly create a bucket, as seen in the video:

[screen-capture (47).webm](https://github.com/ceph/ceph/assets/106810838/f79b1b5d-8ca8-4a8d-b3e4-2d831256e763)

What do you think?

**Comment by nizamial09** [comment]
> Thanks @nizamial09 for the PR. It would be nice to get rid of all the error messages, but to me seems a little bit risky to add a window of time (500ms) where you can incorrectly create a bucket, as seen in the video:
> 
>  screen-capture.47.webm 
> What do you think?

Thank you for catching that. I added a check to make sure that we proceed with the submit only when all the validations are completed in the form.

The alternate is to disable the submit btn altogether but since we are not doing that anywhere else, I didn't go for it. (Probably its easy to do it globally but not sure if we need to do it?)

**Comment by nizamial09** [comment]
jenkins test dashboard

**Comment by nizamial09** [comment]
jenkins test dashboard cephadm

**Review by Pegonzal — APPROVED** [review]
Thanks @nizamial09, PR looks good to me

**Comment by nizamial09** [comment]
jenkins test dashboard

**Pull request merged**
