### PR TITLE
luminous: ceph_volume_client: fix setting caps for IDs

### PR DESCRIPTION
**Pull request by batrick**
http://tracker.ceph.com/issues/21627

### CODE REVIEW

**Comment by kmroz** [comment]
New PR with resolved merge conflicts: https://github.com/ceph/ceph/pull/18447

**Comment by theanalyst** [comment]
marking this as DNM for integration branch

**Comment by batrick** [comment]
Now that #18037 is merged, I'll resolve the conflicts.

**Comment by batrick** [comment]
@theanalyst this is ready now.

**Comment by theanalyst** [comment]
Passed teuthology run at http://tracker.ceph.com/issues/21830#note-9 and will be merged if approved

**Comment by ajarr** [comment]
@theanalyst , this PR is approved. Whose approval are you looking for? It's a simple fix with a test case. Can we please get this into v12.2.2, and not delay it further?

@batrick, what do you think?

**Comment by batrick** [comment]
@theanalyst I can't approve my own PRs so you could just merge this I think.

**Comment by ajarr** [comment]
@batrick, thanks!

**Pull request merged**
