### PR TITLE
rgw_file: fix bug of kill nfs-ganesha with fsal rgw

### PR DESCRIPTION
**Pull request by cmgitdream**
RGWLib change CODE_ENVIRONMENT_DAEMON to CODE_ENVIRONMENT_LIBRARY

fix bug of kill nfs-ganesha failed
http://tracker.ceph.com/issues/18505

Signed-off-by: Min Chen <chenmin@xsky.com>

### CODE REVIEW

**Comment by cmgitdream** [comment]
@mattbenjamin

**Comment by mattbenjamin** [comment]
@cmgitdream hi; see above comments;  can you agree with the second part?  if you stand by removing join(), please provide more reasoning

**Comment by cmgitdream** [comment]
@mattbenjamin we can use thread::detach() to release resource
actualy, in my test case I find there are two rgw_frontend threads, besides, there are 60 seconds blocked by pthread_join() before thread being killed

**Comment by mattbenjamin** [comment]
@cmgitdream can you revisit this?

**Pull request closed without merging**
