### PR TITLE
init-rbdmap uses distro-specific functions

### PR DESCRIPTION
**Pull request by theanalyst**
http://tracker.ceph.com/issues/13695

### CODE REVIEW

**Comment by theanalyst** [comment]
@branto1 this is a backport of https://github.com/ceph/ceph/pull/6363 which was authored by you. Does this look okay to you?

**Comment by dachary** [comment]
@theanalyst note that https://github.com/ceph/ceph/pull/5790 is going to be merged before this one. You may want to check if it applies cleanly on top of it.

**Comment by branto1** [comment]
lgtm
@dachary: Feel free to merge once the #5790 is merged.

**Comment by theanalyst** [comment]
@dachary noted, will take a look once #5790 gets merged

**Comment by dachary** [comment]
It passed a run of the upgrade/hammer suite ( see http://tracker.ceph.com/issues/13356#note-30 for details ).

**Pull request merged**
