### PR TITLE
pybind/mgr/pg_autoscaler: typo default option scale-up to scale-down

### PR DESCRIPTION
**Pull request by kamoltat**
Typo: `scale-up` should be `scale-down` in Module
Option.

This typo doesn't trigger a bug because we create
a key-value of `scale-down` profile in
the function `create_initial()` in `src/mon/KVMonitor.cc`.
This will override whatever is the default option
in pg_autoscaler/module.py when we start the cluster and
the monitor gets created.

The command: `ceph osd pool set autoscale-profile <option>`
is still the primary command to change the autoscale-profiler
after the pool is created.

Fixes: https://tracker.ceph.com/issues/53203

Signed-off-by: Kamoltat <ksirivad@redhat.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by kamoltat** [comment]
jenkins test api

**Review by neha-ojha — APPROVED** [review]
Let's create a tracker to backport this change for code correctness purposes.

nit about commit message: https://github.com/kamoltat/ceph/blob/master/src/mon/KVMonitor.cc#L51 - this line number is bound to change, might be more useful to describe the function name etc. for reference

**Comment by ljflores** [comment]
http://pulpito.front.sepia.ceph.com/yuriw-2021-11-08_15:14:19-rados-wip-yuri-testing-2021-11-04-0731-distro-basic-smithi/
http://pulpito.front.sepia.ceph.com/yuriw-2021-11-04_20:25:46-rados-wip-yuri-testing-2021-11-04-0731-distro-basic-smithi/


Failures unrelated, tracked in:

    [6485385, 6485585, 6491076, 6491095] -- seen in master: http://pulpito.front.sepia.ceph.com/yuriw-2021-11-06_17:01:58-rados-wip-yuri-testing-master-11.5.21-distro-basic-smithi/6488501/
    [6485484] -- potentially related to https://tracker.ceph.com/issues/21317, but also seen in master run: http://pulpito.front.sepia.ceph.com/yuriw-2021-11-06_17:01:58-rados-wip-yuri-testing-master-11.5.21-distro-basic-smithi/6488467/
    [6485488] -- https://tracker.ceph.com/issues/37657
    [6485616] -- potentially related to https://tracker.ceph.com/issues/45701; also seen in master run: http://pulpito.front.sepia.ceph.com/yuriw-2021-11-06_17:01:58-rados-wip-yuri-testing-master-11.5.21-distro-basic-smithi/6488669/
    [6485669] -- seen in master run: http://pulpito.front.sepia.ceph.com/yuriw-2021-11-06_17:01:58-rados-wip-yuri-testing-master-11.5.21-distro-basic-smithi/6488551/
    [6491087, 6491102, 6485685] -- seen in master run: http://pulpito.front.sepia.ceph.com/yuriw-2021-11-06_17:01:58-rados-wip-yuri-testing-master-11.5.21-distro-basic-smithi/6488803/
    [6485698] -- seen in master run: http://pulpito.front.sepia.ceph.com/yuriw-2021-11-06_17:01:58-rados-wip-yuri-testing-master-11.5.21-distro-basic-smithi/
    [6485733] -- seen in in master run: http://pulpito.front.sepia.ceph.com/yuriw-2021-11-06_17:01:58-rados-wip-yuri-testing-master-11.5.21-distro-basic-smithi/6488712/
    [6485487, 6485492] -- seen in master run: http://pulpito.front.sepia.ceph.com/yuriw-2021-11-06_17:01:58-rados-wip-yuri-testing-master-11.5.21-distro-basic-smithi/6488521/
    [6485497, 6485547, 6485594, 6485649, 6485693] -- seen in master run: http://pulpito.front.sepia.ceph.com/yuriw-2021-11-06_17:01:58-rados-wip-yuri-testing-master-11.5.21-distro-basic-smithi/6488412/

Failure untracked, but likely unrelated:

    [6485465, 6485471] -- similar test passed in master: http://pulpito.front.sepia.ceph.com/yuriw-2021-11-06_17:01:58-rados-wip-yuri-testing-master-11.5.21-distro-basic-smithi/6488581/; http://pulpito.front.sepia.ceph.com/yuriw-2021-11-06_17:01:58-rados-wip-yuri-testing-master-11.5.21-distro-basic-smithi/6488587/
    [6485513] -- similar test passed in master: http://pulpito.front.sepia.ceph.com/yuriw-2021-11-06_17:01:58-rados-wip-yuri-testing-master-11.5.21-distro-basic-smithi/6488630/
    [6485589] -- same test passed in recent master run: http://pulpito.front.sepia.ceph.com/yuriw-2021-11-06_17:01:58-rados-wip-yuri-testing-master-11.5.21-distro-basic-smithi/6488706/; however, failed in a past master run: http://pulpito.front.sepia.ceph.com/teuthology-2021-09-26_07:01:03-rados-master-distro-basic-gibba/6408301/
    [6485485] -- similar test passed in master run: http://pulpito.front.sepia.ceph.com/yuriw-2021-11-06_17:01:58-rados-wip-yuri-testing-master-11.5.21-distro-basic-smithi/6488601/
    [6485495] -- similar test passed in master run: http://pulpito.front.sepia.ceph.com/yuriw-2021-11-06_17:01:58-rados-wip-yuri-testing-master-11.5.21-distro-basic-smithi/6488611/
    [6485498] -- similar test passed in master: http://pulpito.front.sepia.ceph.com/yuriw-2021-11-06_17:01:58-rados-wip-yuri-testing-master-11.5.21-distro-basic-smithi/6488614/
    [6485665] -- similar test passed in master: http://pulpito.front.sepia.ceph.com/yuriw-2021-11-06_17:01:58-rados-wip-yuri-testing-master-11.5.21-distro-basic-smithi/6488783/


Details:
    Bug_#21317: Update VPS with latest distro: RuntimeError: Could not reconnect to ubuntu@vpm129.front.sepia.ceph.com - Infrastructure - Sepia
    Bug_#37657: Command failed on smithi075 with status 1: 'sudo yum install -y kernel' - Ceph
    Bug_#45701: rados/cephadm/smoke-roleless fails due to CEPHADM_REFRESH_FAILED health check - Ceph - Orchestrator

**Comment by yuriw** [comment]
jenkins test make check

**Pull request merged**
