### PR TITLE
ceph-post-file: must be root

### PR DESCRIPTION
**Pull request by liewegas**

### CODE REVIEW

**Comment by dachary** [comment]
<pre>
Reviewed-by: Loic Dachary &lt;ldachary@redhat.com>
</pre>

**Comment by liewegas** [comment]
argh, except it doesn't work.  the files are 600 from make install, and debian/rules (also or re-)chowns them to 600, but the resulting package still has them as 644.  wtf?

**Comment by dachary** [comment]
@liewegas I think git only allows you to change the presence of the x bit in the permissions. It's either 644 or 755 but nothing finer grain. I've not verified that though but faced exactly the same problem with the key files included in teuthology.

**Comment by liewegas** [comment]
pushed the workunit fix to master... the other patch doesn't work tho :(

**Comment by liewegas** [comment]
closing this, but leaving the bug open.

**Pull request closed without merging**
