### PR TITLE
fix bugs for func needs_recovery

### PR DESCRIPTION
**Pull request by majianpeng**

### CODE REVIEW

**Comment by tchaikov** [comment]
@majianpeng could you touch the commit and force-push it ? so the bot can catch this PR and run it through the "make check" ? thanks.

**Comment by dachary** [comment]
ignore the false negative from the bot, it comes from a test instability, it should be fixed by https://github.com/ceph/ceph/pull/4370. running the bot once more.

**Comment by dachary** [comment]
@tchaikov you beat me to it ;-)

**Comment by majianpeng** [comment]
@tchaikov . updated & please review again. Thanks!

**Comment by tchaikov** [comment]
i think this a safe fix. merging it.

**Pull request merged**
