### PR TITLE
os/bluestore/BitMapAllocator: fix reservations vs min_alloc_size

### PR DESCRIPTION
**Pull request by chhabaramesh**
Fixed race condition in getting used blocks from allocator by putting it under single lock.
Signed-off-by: Ramesh Chander <Ramesh.Chander@sandisk.com>

### CODE REVIEW

**Comment by chhabaramesh** [comment]
@liewegas , please have a look.

**Comment by chhabaramesh** [comment]
@liewegas , please review and merge. This race was causing assert hit in unit test case.

**Comment by chhabaramesh** [comment]
@liewegas , code changes for reserving min_alloc before going to a subtree and some more cleanup related to that. Please review. It passes, objectstore and allocator tests.

**Comment by liewegas** [comment]
cherry-picked the race fix; can you rebase teh other patches and rename the PR?  Thanks!

**Comment by chhabaramesh** [comment]
@liewegas , updated as per your comment.

**Comment by liewegas** [comment]
<pre>2017-01-25T23:33:14.665 INFO:tasks.ceph.osd.1.smithi197.stderr:/build/ceph-11.1.0-7031-g7e25bbc/src/os/bluestore/BitAllocator.cc: In function 'virtual int64_t BitMapZone::alloc_blocks_dis(int64_t, int64_t, int64_t, int64_t, ExtentList*)' thread 7ff252beb700 time 2017-01-25 23:33:14.672724
2017-01-25T23:33:14.665 INFO:tasks.ceph.osd.1.smithi197.stderr:/build/ceph-11.1.0-7031-g7e25bbc/src/os/bluestore/BitAllocator.cc: 540: FAILED assert(num_blocks >= min_alloc)
2017-01-25T23:33:14.670 INFO:tasks.ceph.osd.1.smithi197.stderr: ceph version 11.1.0-7031-g7e25bbc (7e25bbcd5e6074cedec30be2e6677ed7fda69415)
2017-01-25T23:33:14.670 INFO:tasks.ceph.osd.1.smithi197.stderr: 1: (ceph::__ceph_assert_fail(char const*, char const*, int, char const*)+0x102) [0x7ff2663299e2]
2017-01-25T23:33:14.670 INFO:tasks.ceph.osd.1.smithi197.stderr: 2: (BitMapZone::alloc_blocks_dis(long, long, long, long, ExtentList*)+0x360) [0x5649b5559000]
2017-01-25T23:33:14.670 INFO:tasks.ceph.osd.1.smithi197.stderr: 3: (BitMapAreaLeaf::alloc_blocks_dis_int(long, long, long, long, ExtentList*)+0xf2) [0x5649b5559242]
2017-01-25T23:33:14.671 INFO:tasks.ceph.osd.1.smithi197.stderr: 4: (BitMapAreaIN::alloc_blocks_dis(long, long, long, long, ExtentList*)+0x13) [0x5649b5556a73]
2017-01-25T23:33:14.671 INFO:tasks.ceph.osd.1.smithi197.stderr: 5: (BitMapAreaIN::alloc_blocks_dis_int_work(bool, long, long, long, long, ExtentList*)+0xf2) [0x5649b5559412]
2017-01-25T23:33:14.672 INFO:tasks.ceph.osd.1.smithi197.stderr: 6: (BitAllocator::alloc_blocks_dis_int(long, long, long, long, ExtentList*)+0x1c) [0x5649b555947c]
2017-01-25T23:33:14.672 INFO:tasks.ceph.osd.1.smithi197.stderr: 7: (BitAllocator::alloc_blocks_dis_work(long, long, long, ExtentList*)+0x95) [0x5649b5559865]
2017-01-25T23:33:14.672 INFO:tasks.ceph.osd.1.smithi197.stderr: 8: (BitMapAllocator::allocate_dis(unsigned long, unsigned long, unsigned long, long, std::vector<AllocExtent, mempool::pool_allocator<(mempool::pool_index_t)7, AllocExtent> >*)+0x5e) [0x5649b5555eee]
2017-01-25T23:33:14.672 INFO:tasks.ceph.osd.1.smithi197.stderr: 9: (BitMapAllocator::allocate(unsigned long, unsigned long, unsigned long, long, std::vector<AllocExtent, mempool::pool_allocator<(mempool::pool_index_t)7, AllocExtent> >*)+0x28e) [0x5649b55561ce]
2017-01-25T23:33:14.673 INFO:tasks.ceph.osd.1.smithi197.stderr: 10: (BlueStore::_balance_bluefs_freespace(std::vector<bluestore_pextent_t, mempool::pool_allocator<(mempool::pool_index_t)6, bluestore_pextent_t> >*)+0xe76) [0x5649b544ea56]
2017-01-25T23:33:14.673 INFO:tasks.ceph.osd.1.smithi197.stderr: 11: (BlueStore::_kv_sync_thread()+0x15f8) [0x5649b5450e78]
2017-01-25T23:33:14.673 INFO:tasks.ceph.osd.1.smithi197.stderr: 12: (BlueStore::KVSyncThread::entry()+0xd) [0x5649b548681d]
2017-01-25T23:33:14.674 INFO:tasks.ceph.osd.1.smithi197.stderr: 13: (()+0x76ba) [0x7ff265b606ba]
</pre>
see /a/sage-2017-01-25_23:09:16-rados-wip-sage-testing---basic-smithi/748424

**Comment by chhabaramesh** [comment]
@liewegas , I found places where allocation want_size was aligned to bluestore->min_alloc_size though allocation is requested with bluefs->min_alloc_size. The third commit fixes this issue. Please reschedule to tests if possible.

**Comment by yuriw** [comment]
Per @liewegas removed from testing batch for now seeing some errors, trying to separate tests.

http://pulpito.ceph.com/yuriw-2017-02-09_01:40:31-rados-wip-yuri-testing2_2017_2_9-distro-basic-smithi/

http://pulpito.ceph.com/yuriw-2017-02-09_04:55:44-rados-wip-yuri-testing2_2017_2_9---basic-smithi/

**Comment by chhabaramesh** [comment]
@liewegas @yuriw , any update on this?

**Comment by tchaikov** [comment]
@chhabaramesh needs rebase

**Comment by chhabaramesh** [comment]
@tchaikov , I will do it within this week.

**Comment by tchaikov** [comment]
could you prefix the title of your commit message with the subcomponent your are changing ? see https://github.com/ceph/ceph/blob/master/SubmittingPatches.rst#3-describe-your-changes

**Comment by tchaikov** [comment]
@chhabaramesh sorry, need rebase again.

**Pull request closed without merging**
