### PR TITLE
librbd: fix rbd pend in 99% sometimes when remove a clone

### PR DESCRIPTION
**Pull request by jimmyway**
http://tracker.ceph.com/issues/19897

Signed-off-by: tang.jin <tang.jin@istuary.com>

### CODE REVIEW

**Comment by jimmyway** [comment]
@liupan1111

**Comment by jimmyway** [comment]
@joscollin , would you check again, please?

**Comment by dillaman** [comment]
@jimmyway The op work queue is a singleton -- it won't be deleted nor drained when the parent ```ImageCtx``` instance is destructed. You might have been playing with an older version of librbd?

**Comment by jimmyway** [comment]
@dillaman , yes, I used an older version of librbd based 10.2.2, I disabled rbd_cache and changed rbd_op_threads to 3 in conf. 
I have checked the latest code in github, the op_work_queue is really moved into ThreadPool, the ImageCtx won't have any op_work_queue instance.So I think it won't happen in the latest version.
As far as I am concerned, moving 'delete ImageCtx->parent ' into ~ImageCtx() is more safe as a rational design which runs in main-thread context, What do you think?

**Comment by dillaman** [comment]
@jimmyway Honestly, I think the change is a bit of a hack. It doesn't make sense to me to keep an instance around past its lifetime.

**Comment by jimmyway** [comment]
@dillaman , you are right, thanks for your attention.

**Comment by dillaman** [comment]
@jimmyway Appreciate the testing with multi-threaded work queue

**Pull request closed without merging**
