### PR TITLE
qa/rgw: verify suite runs s3 website tests

### PR DESCRIPTION
**Pull request by cbodley**
the verify suite configures a second gateway with --rgw-dns-s3website-name to serve static website content. it uses dnsmasq to set up distinct subdomains, and puts the correct hostnames in the s3test configuration file. support for overriding radosgw port numbers was also necessary because the website tests don't add a port to the s3website_domain requests

### CODE REVIEW

**Comment by cbodley** [comment]
some of the routing tests are currently failing, so we'll need to fix those before merging:

http://qa-proxy.ceph.com/teuthology/cbodley-2018-02-23_14:07:16-rgw-master-distro-basic-smithi/2218130/teuthology.log

**Comment by cbodley** [comment]
test failures should be resolved by the redirect error code fix in #19252 and a fix to s3tests in https://github.com/ceph/s3-tests/pull/212

**Comment by cbodley** [comment]
test run: http://pulpito.ceph.com/cbodley-2018-03-05_16:34:44-rgw-wip-cbodley-testing-distro-basic-smithi/

all s3test jobs run the website tests and pass (requries the fix in https://github.com/ceph/ceph/pull/20693)

**Comment by cbodley** [comment]
successful run: http://pulpito.ceph.com/cbodley-2018-03-06_18:40:40-rgw-wip-cbodley-testing-distro-basic-smithi/

the required fix merged in https://github.com/ceph/ceph/pull/20693

**Comment by cbodley** [comment]
seeing test failures when ssl is enabled, because the certificates don't match these s3. and s3website. subdomains:
> CertificateError: hostname 's3.smithi037.front.sepia.ceph.com' doesn't match 'smithi037.front.sepia.ceph.com'

**Comment by smanjara** [comment]
@cbodley is this PR waiting to be reviewed?

**Comment by cbodley** [comment]
hi @smanjara! i had these tests working before, but after ssl tests were added in https://github.com/ceph/ceph/pull/20444, this now fails with the CertificateError listed above

https://github.com/ceph/ceph/blob/master/qa/tasks/openssl_keys.py#L114 is creating these keys using `/CN={remote.hostname}`, but these tests would need certs that include the subdomain piece too. so this stuff needs to be split into a separate suite that generates its own certificates with the subdomain as a prefix to the hostname

**Comment by smanjara** [comment]
@cbodley I am thinking we could add something like 's3subdomain: true" variable to the ctx in the openssl_keys task to tell it if we need the subdomain to be part of the cert name to make the decision in [L114](https://github.com/ceph/ceph/blob/master/qa/tasks/openssl_keys.py#L114)?

**Comment by cbodley** [comment]
@smanjara i think we could just add a `prefix` to the yaml config that defaults to empty, and have the task that runs s3website tests add an override for it

**Comment by cbodley** [comment]
rebased - will revisit the ssl issue

**Comment by cbodley** [comment]
making progress, but now getting errors like this:
> CertificateError: hostname 'test-client.0-eps574aoiz2nllv-424.s3-website.smithi099.front.sepia.ceph.com' doesn't match u's3-website.smithi099.front.sepia.ceph.com'

so the certificates need a wildcard entry, but i don't think you can do that with /CN. i'll look into adding subjectAltName for this, which i've already been planning to do because of the spammy warnings like this:
> SubjectAltNameWarning: Certificate for s3.smithi197.front.sepia.ceph.com has no `subjectAltName`, falling back to check for a `commonName` for now. This feature is being removed by major browsers and deprecated by RFC 2818.

**Pull request closed without merging**
