### PR TITLE
mgr/dashboard: Fix iSCSI Target's validation

### PR DESCRIPTION
**Pull request by tspmelo**
Fixes: https://tracker.ceph.com/issues/42302

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`

</details>

### CODE REVIEW

**Comment by tspmelo** [comment]
localhost_4200_(iPad Pro)

**Comment by tchaikov** [comment]
```
_____________________ ERROR collecting controllers/home.py _____________________
controllers/home.py:19: in <module>
    LANGUAGES = {f for f in os.listdir(mgr.get_frontend_path())
E   OSError: [Errno 2] No such file or directory: './frontend/dist'
collected 278 items / 1 errors

```
in arm64 build.

**Comment by tchaikov** [comment]
jenkins test make check arm64

**Comment by tspmelo** [comment]
jenkins test dashboard

**Comment by tspmelo** [comment]
jenkins test make check arm64

**Pull request merged**
