### PR TITLE
tests: ceph create may consume more than one id

### PR DESCRIPTION
**Pull request by dachary**
http://tracker.ceph.com/issues/11618

### CODE REVIEW

**Comment by dachary** [comment]
@tchaikov assigning you semi-randomly, please feel free to unassign yourself if your plate is full ;-)

**Comment by jecluis** [comment]
LGTM

**Comment by dachary** [comment]
@tchaikov right ! fixed & repushed.

**Comment by tchaikov** [comment]
looks good to me.

**Pull request merged**
