### PR TITLE
jewel: librbd: set deleted parent pointer to null

### PR DESCRIPTION
**Pull request by pdvian**
http://tracker.ceph.com/issues/22170

### CODE REVIEW

**Comment by pdvian** [comment]
@dillaman @tchaikov @smithfarm

**Comment by pdvian** [comment]
retest this please.

**Comment by tchaikov** [comment]
retest this please

**Comment by smithfarm** [comment]
retest this please

**Comment by smithfarm** [comment]
This PR is included in the integration run at: http://tracker.ceph.com/issues/21742#note-13

So far, one rbd suite with 78 jobs passed. Another one, with 154 jobs, is scheduled.

**Comment by smithfarm** [comment]
RBD integration run passed at http://tracker.ceph.com/issues/21742#note-13

**Pull request merged**
