### PR TITLE
mgr/cephadm: Make type annotations for cephadm.services mandatory

### PR DESCRIPTION
**Pull request by sebastian-philipp**
* Found a wrong default for `OSDService.create_single_host`

Signed-off-by: Sebastian Wagner <sebastian.wagner@suse.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Review by mgfritch — APPROVED** [review]
big :+1:  for this, it's caused me grief in the past ...

**Review by Devp00l — APPROVED** [review]

**Comment by sebastian-philipp** [comment]
rebased

**Comment by sebastian-philipp** [comment]
jenkins test make check

**Comment by jschmid1** [comment]
green: https://pulpito.ceph.com/jschmid-2020-09-29_15:42:37-rados:cephadm-wip-jschmid1-testing-2020-09-29-1315-distro-basic-smithi/

**Pull request merged**
