### PR TITLE
mgr/dashboard: refactor dashboard cephadm e2e tests

### PR DESCRIPTION
**Pull request by nizamial09**
I'll be reverting the PR to select/unselect datatables: https://github.com/ceph/ceph/pull/45313

I moved the code for changing the alertmanager_api_host, prometheus_api_host and grafana_api_url from the tests to the script to reduce the complexity of the tests. We are not actually testing anything there just making sure the environment is ready and the urls are okay. Because by default, these urls are set with fqdn and kcli env has issues with the fqdns. 
Also by doing this it reduces some 404 errors coming from the node-exporter and prometheus so that the tests won't be affected by it.

In addition to this I reduced the count of node-exporter to 2 before starting the test. Its because, if we try to drain a host that has  a node-exporter in it, that will cause a 404 error momentarily and that will cause the cypress to fail again. By positioning it into the script itself, this issue won't be there.

There used to appear an [ExpressionChangedAfterChecked](https://angular.io/errors/NG0100) error in the service-daemon-list component because of the relativeDate pipe. And I did some searching and its a known issue with the [date pipes ](https://github.com/AndrewPoyntz/time-ago-pipe/issues/6). The good thing is that this will only happen in the developer environment. The easiest and proper way to catch this is to manually do the changeDetection which I done using a timeout.

There are some minor cleanups too where I do a proper cleanup by deleting the pool as well as the `.kcli` folder. Its to prevent errors like `fedora36 image not found and it causes the vms to not start` and that will make the test to hang there. The downside of doing this is that everytime the test needs to run in an environment it'll need to download the fedora36 image, but it'll make the test a bit more foolproof.

Fixes: https://tracker.ceph.com/issues/57511
Fixes: https://tracker.ceph.com/issues/57386
Signed-off-by: Nizamudeen A <nia@redhat.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [x] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by nizamial09** [comment]
jenkins test dashboard

**Comment by nizamial09** [comment]
shaman [ongoing](https://shaman.ceph.com/builds/ceph/wip-nia-testing-2022-09-30-1401/)

**Review by aaSharma14 — APPROVED** [review]

**Comment by nizamial09** [comment]
teuthology [passed](https://pulpito.ceph.com/nizamial09-2022-10-10_06:29:50-rados:dashboard-wip-nia-testing-2022-10-09-1104-distro-default-smithi/) :heavy_check_mark:

**Comment by nizamial09** [comment]
jenkins test make check

**Comment by nizamial09** [comment]
jenkins test dashboard

**Comment by nizamial09** [comment]
Jenkins test dashboard

**Comment by nizamial09** [comment]
merging this to fix the cephadm e2e ci.

**Pull request merged**
