### PR TITLE
quincy: Revert "qa/fs/mixed-clients: specify distros for tests"

### PR DESCRIPTION
**Pull request by batrick**
This reverts commit 3731fc7779e80bdfe234fec4dae21cfe46c3f193.

~https://github.com/ceph/ceph/pull/49957 as merged by accident without QA.~ The use of 22.04 breaks quincy runs of the `fs` suite scheduling.

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [x] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by vshankar** [comment]
> This reverts commit [3731fc7](https://github.com/ceph/ceph/commit/3731fc7779e80bdfe234fec4dae21cfe46c3f193).
> 
> #49957 as merged by accident without QA. The use of 22.04 breaks quincy runs of the `fs` suite scheduling.

The backport was a part of https://trello.com/c/MMn8gArA/1699-wip-yuri10-testing-2023-02-28-0752-quincy

**Comment by batrick** [comment]
> > This reverts commit [3731fc7](https://github.com/ceph/ceph/commit/3731fc7779e80bdfe234fec4dae21cfe46c3f193).
> > #49957 as merged by accident without QA. The use of 22.04 breaks quincy runs of the `fs` suite scheduling.
> 
> The backport was a part of https://trello.com/c/MMn8gArA/1699-wip-yuri10-testing-2023-02-28-0752-quincy

Yes, I found it was part of another run after I wrote this PR description. I've struck that text.

**Review by vshankar — APPROVED** [review]

**Comment by batrick** [comment]
added signed-off-by

**Comment by batrick** [comment]
https://tracker.ceph.com/projects/cephfs/wiki/Quincy#2023-Apr-2124

**Pull request merged**
