### PR TITLE
nautilus: ceph.spec.in: Enable tcmalloc on IBM Power and Z

### PR DESCRIPTION
**Pull request by smithfarm**
backport tracker: https://tracker.ceph.com/issues/49299

backport of #39379
parent tracker: https://tracker.ceph.com/issues/49296

### CODE REVIEW

**Comment by tchaikov** [comment]
@smithfarm could you use `git cherry-pick -x` for cherry-picking https://github.com/ceph/ceph/pull/39379/commits/2b1e646f7aade3135a98c505111ac7ebef5e93a6 ?

**Comment by smithfarm** [comment]
@tchaikov Oops! I took the version from https://github.com/ceph/ceph/pull/39489, forgetting that it had not been done using `-x`. Should be fixed now.

**Review by ktdreyer — APPROVED** [review]

**Comment by tchaikov** [comment]
@smithfarm just one nit, shall we remove lttng from the title?

**Review by tchaikov — APPROVED** [review]

**Comment by smithfarm** [comment]
@tchaikov OK

**Pull request merged**
