### PR TITLE
mds/quiesce-db: calculate_quiesce_map: aggregate quiesce roots' TTL as `max`

### PR DESCRIPTION
**Pull request by leonid-s-usov**
Fixes: https://tracker.ceph.com/issues/66438

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Comment by leonid-s-usov** [comment]
tested at https://pulpito.ceph.com/leonidus-2024-06-18_17:15:58-fs-wip-lusov-quiesce-distro-default-smithi/, no quiesce errors

**Comment by leonid-s-usov** [comment]
jenkins retest this please

**Comment by leonid-s-usov** [comment]
functional tests green: https://pulpito.ceph.com/leonidus-2024-06-19_07:57:47-fs:functional-wip-lusov-quiesce-distro-default-smithi/

**Comment by leonid-s-usov** [comment]
jenkins test make check

**Comment by leonid-s-usov** [comment]
jenkins test make check arm64

**Review by batrick — APPROVED** [review]

**Pull request merged**
