### PR TITLE
quincy: doc: point to main branch for release info

### PR DESCRIPTION
**Pull request by batrick**
I've fixed links to the release notes in other `.rst` doc files to point to the latest notes. I will forward port these changes to `main` after this is merged.

Note: the TOC no longer has the release notes because the corresponding release `.rst` files are gone. I don't know a good way to fix that. It's the only downside I'm aware of.

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [x] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [x] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by anthonyeleven** [comment]
I think I'll defer to @zdover23 for this

**Review by jdurgin — APPROVED** [review]

**Comment by tchaikov** [comment]
@batrick these changes are not backported from master. would be better to note the reason in the commit message explaining why we cannot do so. 

> I will forward port these changes to `main` after this is merged.

if that's the case, i have follow questions: why do we need to remove `releases/`? i miss the releases timeline in https://docs.ceph.com/en/latest/releases/. it sends a clear message to users about our when the existing releases are EOL'ed. and why do we want to remove https://docs.ceph.com/en/latest/releases/general/ ?

**Comment by tchaikov** [comment]
thanks for the explanations! that makes more sense to me now.

**Comment by tchaikov** [comment]
```
/home/jenkins-build/build/workspace/ceph-pull-requests/qa/standalone/ceph-helpers.sh:1000: wait_for_osd:  (( i < 300 ))
/home/jenkins-build/build/workspace/ceph-pull-requests/qa/standalone/ceph-helpers.sh:1009: wait_for_osd:  return 1
```

**Comment by tchaikov** [comment]
jenkins test make check

**Comment by jdurgin** [comment]
@batrick while looking at another docs issue I noticed https://github.com/ceph/ceph/pull/46917 which tries to address the same problem. It's not quite as up-to-date though, e.g. if there hasn't been a merge to the stable branch triggering a new docs build, the latest changes from main wouldn't be included.

so I think this redirect approach is better overall. If it works we can remove the other one.

**Comment by idryomov** [comment]
> @batrick while looking at another docs issue I noticed #46917 which tries to address the same problem. It's not quite as up-to-date though, e.g. if there hasn't been a merge to the stable branch triggering a new docs build, the latest changes from main wouldn't be included.

I think that was supposed to be addressed with https://github.com/ceph/ceph-build/pull/2044.

> 
> so I think this redirect approach is better overall. If it works we can remove the other one.

This PR is already effectively removes https://github.com/ceph/ceph/pull/46917.

**Review by idryomov — COMMENTED** [review]
> doc: remove release notes for release branch
>
> Instead, RTD will redirect to /latest.

If you figured out a way to make RTD behave and a hard-coded redirect is no longer needed (kudos!), what is the point of removing release notes from release branches?  Can't they just be left there, stale?  Otherwise it sounds like this "purge `doc/releases`" step would be required on every major release.

**Comment by batrick** [comment]
Hey folks, good questions. I've amended the commit messages to try to answer them. Please check.

**Review by idryomov — APPROVED** [review]

**Comment by batrick** [comment]
jenkins test windows

**Comment by batrick** [comment]
jenkins test windows

**Comment by batrick** [comment]
Follow-up: #48945

**Pull request merged**
