### PR TITLE
jewel: tools: snapshotted RBD extent objects can't be manually evicted from a cache tier

### PR DESCRIPTION
**Pull request by ddiss**
In Jewel, snapshotted objects can't be manually evicted from a cache tier using cache-flush-evict-all . Backport three minor changes that implement and test this functionality.

http://tracker.ceph.com/issues/17895

### CODE REVIEW

**Comment by dachary** [comment]
jenkins test this please (general jenkins failure)

**Comment by dachary** [comment]
jenkins test this please (flake8 error now fixed in jewel-next)

**Comment by ddiss** [comment]
@dachary: anything needed from my side here?

**Comment by dachary** [comment]
@ddiss all good, thanks for asking. The error was unrelated to your backport, it was environmental.

**Comment by dachary** [comment]
@tchaikov does this backport look good to merge ? It passed the rados (http://tracker.ceph.com/issues/17851#note-12) suite. It also passed the upgrade/jewel-x and upgrade/hammer-x (http://tracker.ceph.com/issues/17851#note-15) suites. Note that it won't be included in 10.2.4, reason why it targets jewel-next.

**Pull request merged**
