### PR TITLE
pacific: rocksdb: pickup fix to detect PMULL instruction

### PR DESCRIPTION
**Pull request by tchaikov**
Fixes: https://tracker.ceph.com/issues/50579

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Review by jdurgin — CHANGES_REQUESTED** [review]
We need to be cautious upgrading rocksdb - especially in a stable release. @markhpc can you check for any perf impact?

**Comment by jdurgin** [comment]
Mark suggested cherry-picking just the arm build fix for pacific - that seems like a good path to me

**Comment by tchaikov** [comment]
@jdurgin would you kindly take another look?

**Comment by tchaikov** [comment]
https://shaman.ceph.com/builds/ceph/pacific-rocksdb-kefu/57a1328fcdb709af0b6619fd9bd42411aafa5c83/

**Review by jdurgin — APPROVED** [review]

**Review by neha-ojha — APPROVED** [review]

**Review by aclamk — APPROVED** [review]

**Comment by tchaikov** [comment]
@david-caro thank you for testing this change, it really helps!

**Pull request merged**
