### PR TITLE
seastar: pick up upstream change which includes cryptopp fix

### PR DESCRIPTION
**Pull request by tchaikov**
so we don't need to use our own fork.

Signed-off-by: Kefu Chai <tchaikov@gmail.com>

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [x] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by tchaikov** [comment]
see also https://github.com/scylladb/seastar/commit/ce2652d39dc06801c2cfb983d6cd30937937feba

**Comment by tchaikov** [comment]
jenkins test submodules

**Comment by tchaikov** [comment]
jenkins test submodules

**Comment by tchaikov** [comment]
jenkins test submodules

**Comment by tchaikov** [comment]
jenkins test submodules

**Comment by tchaikov** [comment]
jenkins test submodules

**Comment by tchaikov** [comment]
jenkins test submodules

**Comment by tchaikov** [comment]
jenkins test submodules

**Review by ronen-fr — APPROVED** [review]

**Comment by tchaikov** [comment]
jenkins test api

**Pull request merged**
