### PR TITLE
jewel: rgw: TempURL properly handles accounts created with the implicit tenant

### PR DESCRIPTION
**Pull request by rzarzynski**
Fixes: http://tracker.ceph.com/issues/17961. Currently under testing.

CC: @dachary, @yehudasa, @cbodley.

### CODE REVIEW

**Comment by rzarzynski** [comment]
Removed the *DNM* tag after testing. s3-tests nor Tempest haven't found any regression here. Following testcases pass with the patch applied:
```
tempest.api.object_storage.test_object_temp_url.ObjectTempUrlTest.test_get_object_using_temp_url
tempest.api.object_storage.test_object_temp_url.ObjectTempUrlTest.test_get_object_using_temp_url_key_2
tempest.api.object_storage.test_object_temp_url.ObjectTempUrlTest.test_get_object_using_temp_url_with_inline_query_parameter
tempest.api.object_storage.test_object_temp_url.ObjectTempUrlTest.test_head_object_using_temp_url
tempest.api.object_storage.test_object_temp_url.ObjectTempUrlTest.test_put_object_using_temp_url
```

**Comment by rzarzynski** [comment]
Fixed a typo in the commit message. Absolutely no other changes.

**Comment by dachary** [comment]
@rzarzynski would you mind updating the commit message with 
<pre>


This is because in Jewel in the TempURL implementation we aren't trying to rgw_get_user_info_by_uid() on rgw_user with the tenant field filled like in the Keystone auth case.

The bug isn't present in master as we have there a new auth infrastructure.
</pre>
so that it is clear when browsing the git logs why this commit is not cherry-picked from master ?

**Comment by rzarzynski** [comment]
@dachary: updated. Still no other changes except the commit message.

**Comment by dachary** [comment]
@rzarzynski perfect thanks !

**Comment by smithfarm** [comment]
This passed rgw runs at http://tracker.ceph.com/issues/17851#note-50 and http://tracker.ceph.com/issues/17851#note-58

**Comment by smithfarm** [comment]
```
(11:46:45 AM) smithfarm: owasserm: thanks. For jewel integration rgw, then, what it comes down to is verifying that these 6 valgrind failures are all libtcmalloc-related: http://pulpito.front.sepia.ceph.com/smithfarm-2017-01-31_12:35:14-rgw-wip-jewel-backports-distro-basic-smithi/
(11:46:58 AM) smithfarm: owasserm: I will do that now
(11:47:05 AM) owasserm: smithfarm, thanks
(11:47:33 AM) smithfarm: owasserm: and assuming they are tcmalloc related, you said I can directly merge all the rgw PRs? Or do you want me to ask you for review in the PRs first?
(11:47:53 AM) owasserm: smithfarm, yes you can merge them
(11:48:19 AM) smithfarm: ok, will merge and do at least one or two more rgw runs before passing 10.2.6 to QE
```

**Pull request merged**
