### PR TITLE
jewel: ceph-objectstore-tool: "$OBJ get-omaphdr" and "$OBJ list-omap" scan all pgs instead of using specific pg

### PR DESCRIPTION
**Pull request by dzafman**
http://tracker.ceph.com/issues/22912

### CODE REVIEW

**Comment by dzafman** [comment]
retest this please

**Comment by smithfarm** [comment]
jenkins test docs

**Comment by smithfarm** [comment]
This PR passed a rados integration run at http://tracker.ceph.com/issues/21742#note-14 with two bugs reproducing:

* http://tracker.ceph.com/issues/23006
* http://tracker.ceph.com/issues/23007

@jdurgin OK to merge this despite the test failures?

**Comment by dzafman** [comment]
@smithfarm Yes, 23006 and 23007 could not have been caused by this change.

**Comment by smithfarm** [comment]
This passed a rados run at http://tracker.ceph.com/issues/21742#note-15 (with one unrelated failure)

**Pull request merged**
