### PR TITLE
cephfs-top: drop x_coord_map

### PR DESCRIPTION
**Pull request by joscollin**
As we started using curses pads in PR#48090, we don't need x_coord_map anymore. In this patch, the metrics are positioned in cephfs-top based on padding (ITEMS_PAD). This stupid PR doesn't fix any bug, but just drops the `x_coord_map`. So no need of back-porting except to have identical versions.

Signed-off-by: Jos Collin <jcollin@redhat.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [x] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by joscollin** [comment]
jenkins test make check

**Comment by joscollin** [comment]
Please hold on the review. I haven't finalised the changes yet.

**Comment by joscollin** [comment]
jenkins test make check

**Comment by vshankar** [comment]
> As we started using curses pads in PR#48090, we don't need x_coord_map anymore. In this patch, the metrics are positioned in cephfs-top based on padding (ITEMS_PAD). This stupid PR doesn't fix any bug, but just drops the `x_coord_map`. So no need of back-porting except to have identical versions.

This sounds nice. Just for my understanding, ncurses pads manages the positioning all by itself?

**Comment by joscollin** [comment]
> > As we started using curses pads in PR#48090, we don't need x_coord_map anymore. In this patch, the metrics are positioned in cephfs-top based on padding (ITEMS_PAD). This stupid PR doesn't fix any bug, but just drops the `x_coord_map`. So no need of back-porting except to have identical versions.
> 
> This sounds nice. Just for my understanding, ncurses pads manages the positioning all by itself?

The answer is No. The pad doesn't manage the positioning by itself. The benefit of using a pad is we get more space, in this particular case towards the right side of the window. As I understand the purpose of `x_coord_map`, we could've done this change even before introducing the pad. Now that we dropped the horizontal length (hlen) calculations, which raises the question why `x_coord_map`, which is also horizontal position/length store. So dropped it.

**Review by vshankar — COMMENTED** [review]
LGTM. @neesingh-rh PTAL

**Review by neesingh-rh — COMMENTED** [review]
It needs rebase. It still contains the version commits. Rest LGTM

**Review by neesingh-rh — APPROVED** [review]

**Comment by vshankar** [comment]
jenkins test make check arm64

**Comment by joscollin** [comment]
rebased

**Comment by vshankar** [comment]
@neesingh-rh PTAL at the latest update and approve if it looks fine.

**Pull request merged**
