### PR TITLE
nautilus:os/bluestore: do not count pinned entries as trimmed ones.

### PR DESCRIPTION
**Pull request by ifed01**
Signed-off-by: Igor Fedotov <ifedotov@suse.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by yuriw** [comment]
test this please

**Comment by yuriw** [comment]
@ifed01 this is ready but I can't merge as make check failed

**Comment by neha-ojha** [comment]
make check failure is https://tracker.ceph.com/issues/50247 but this time in nautilus. fyi @cbodley

**Comment by neha-ojha** [comment]
jenkins test make check

**Comment by tchaikov** [comment]
jenkins test make check

**Comment by yuriw** [comment]
jenkins test make check

**Review by aclamk — APPROVED** [review]
Looks good.

**Pull request merged**
