### PR TITLE
crimson/common, seastar: bump up to a newer version. Fix a FTBFS

### PR DESCRIPTION
**Pull request by rzarzynski**
It's necessary since [710a1bfdc02202fe9e59df8ea31de5b82b893fb4](https://github.com/scylladb/seastar/commit/710a1bfdc02202fe9e59df8ea31de5b82b893fb4) in Seastar.

This change is a part of the ongoing upgrade of Seastar which will be completed in a follow-up PR, after merging another change with the Seastar's upstream.

Signed-off-by: Radosław Zarzyński <rzarzyns@redhat.com>

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Review by tchaikov — APPROVED** [review]

**Comment by rzarzynski** [comment]
@tchaikov: Hi Kefu! Will push with the Seastar bump-up (luckily, Scylla Folks have just merged it).

**Comment by tchaikov** [comment]
@rzarzynski hi Radek, might want to include 'seastar submodule' in your commit message to appease the "Unmodified Submodule" check.

**Comment by rzarzynski** [comment]
Thanks, Kefu! Repushed.

**Comment by tchaikov** [comment]
jenkins test make check

**Review by tchaikov — APPROVED** [review]

**Pull request merged**
