### PR TITLE
RGW - Admin - Pass user to created bucket

### PR DESCRIPTION
**Pull request by dang**
The user was not being passed to the created bucket.  This means that,
in some operations, radosgw-admin was crashing trying to de-reference
the user.

Fixes: https://tracker.ceph.com/issues/56810

Signed-off-by: Daniel Gryniewicz <dang@redhat.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Review by cbodley — APPROVED** [review]
eventually i'd like to revisit the need for `Bucket` to store a `User` pointer

`Bucket::get_owner()` could just return `rgw_user` out of its `RGWBucketInfo::owner`. if rgw needs a handle to that `User`, it could get one through `store->get_user(owner)`

**Comment by dang** [comment]
https://pulpito.ceph.com/dang-2022-08-19_10:46:51-rgw-wip-dang-admin-user-distro-default-smithi/

Clean except two valgrind errors in s3select.

**Comment by dang** [comment]
jenkins test api

**Comment by cbodley** [comment]
> Clean except two valgrind errors in s3select.

would you mind creating a tracker issue?

**Comment by dang** [comment]
jenkins test api

**Pull request merged**
