### PR TITLE
pacific: cephfs-top: be resilient to missing client metadata keys

### PR DESCRIPTION
**Pull request by joscollin**
Fixes: https://tracker.ceph.com/issues/49973

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by tchaikov** [comment]
jenkins test make check

**Comment by joscollin** [comment]
jenkins test make check

**Comment by batrick** [comment]
jenkins test make check

**Review by vshankar — APPROVED** [review]

**Comment by joscollin** [comment]
jenkins test make check

**Comment by vshankar** [comment]
https://pulpito.ceph.com/vshankar-2021-03-26_14:38:14-fs-wip-cephfs-top-pacific-backports-20210326-081817-distro-basic-smithi/

**Pull request merged**
