### PR TITLE
mgr/dashboard: prometheus alert test dependency docker.io breaks install.sh

### PR DESCRIPTION
**Pull request by p-se**
Trying to install `docker.io` package on a system where `docker-ce` is
installed, results in a dependency issue.

```
The following packages have unmet dependencies:
 docker.io : Depends: containerd (>= 1.2.6-0ubuntu1~)
E: Unable to correct problems, you have held broken packages.
```

Fixes: https://tracker.ceph.com/issues/49764

Signed-off-by: Patrick Seidensal <pseidensal@suse.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by aaSharma14** [comment]
This is related to https://github.com/ceph/ceph/pull/39995. `docker.io` dependency is conflicting with `moby-engine` in Fedora OS as well. Maybe we can fix this in one PR itself.

**Comment by p-se** [comment]
> This is related to #39995. `docker.io` dependency is conflicting with `moby-engine` in Fedora OS as well. Maybe we can fix this in one PR itself.

Thanks for the reference. Currently it does not look like the suggested solution for Fedora would do any good to Ubuntu (which this PR is about). But the solutions seem to be alike and I wouldn't have anything to object if the other PR would fix the issue for Ubuntu, too. On the other hand, if you'd like me to add anything here, please let me know.

**Comment by aaSharma14** [comment]
> > This is related to #39995. `docker.io` dependency is conflicting with `moby-engine` in Fedora OS as well. Maybe we can fix this in one PR itself.
> 
> Thanks for the reference. Currently it does not look like the suggested solution for Fedora would do any good to Ubuntu (which this PR is about). But the solutions seem to be alike and I wouldn't have anything to object if the other PR would fix the issue for Ubuntu, too. On the other hand, if you'd like me to add anything here, please let me know.

Thanks @p-se . We can go with both the PRs then.

**Review by aaSharma14 — APPROVED** [review]

**Comment by aaSharma14** [comment]
The approach of installing docker has been changed here in this PR https://github.com/ceph/ceph/pull/40205.

**Review by nizamial09 — APPROVED** [review]

**Comment by tchaikov** [comment]
I'd suggest use focal for testing the prometheus alert test. see #40205

**Comment by p-se** [comment]
Surpassed by #40205

**Pull request closed without merging**
