### PR TITLE
ceph-exporter: cleanups

### PR DESCRIPTION
**Pull request by tchaikov**
- initialize member variable in-class
- use string_view for file and function name
- remove BlockTimer::ms
- use std::chrono::high_resolution_clock for timing
- drop unused macro
- drop unused function

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [x] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Comment by tchaikov** [comment]
@avanthakkar hi Avan, could you please help review this changeset?

**Review by avanthakkar — APPROVED** [review]
Changes LGTM! Will test it locally just to verify. 
Also can u trigger teuthology run @tchaikov

**Comment by tchaikov** [comment]
> Changes LGTM! Will test it locally just to verify. Also can u trigger teuthology run @tchaikov

@avanthakkar i am not sure if teuthology is able to exercise this change. AFAICT, ceph-exporter is not tested yet. please correct me if i am wrong. but i will push the change to ceph-ci, so we can at least build it to see if the change builds or not on all builders.

**Comment by tchaikov** [comment]
jenkins test windows

**Comment by tchaikov** [comment]
being built at https://shaman.ceph.com/builds/ceph/kefu-pr-55559/331e05b74d27e3dd7308918aef4e06d47c5990c2/

**Comment by tchaikov** [comment]
@avanthakkar hi Avan, have you finished testing this change? does it work in your test environment?

**Comment by avanthakkar** [comment]
> @avanthakkar hi Avan, have you finished testing this change? does it work in your test environment?

Sorry for the delay, it worked in my test env. Thanks!

**Comment by tchaikov** [comment]
thanks for testing this changeset!

**Pull request merged**
