### PR TITLE
quincy: cmake: disable LTO when building pmdk

### PR DESCRIPTION
**Pull request by tchaikov**
See-also: https://tracker.ceph.com/issues/54473
Signed-off-by: Kefu Chai <tchaikov@gmail.com>
(cherry picked from commit 2a97033ba86ac678a2ce5f99c60090c79f5fd257)

Conflicts:
	cmake/modules/Buildpmem.cmake: trivial resolution

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by tchaikov** [comment]
jenkins test make check

**Comment by tchaikov** [comment]
jenkins test api

**Comment by tchaikov** [comment]
jenkins test make check

**Comment by tchaikov** [comment]
jenkins test make check

**Comment by Matan-B** [comment]
LGTM, 11/19 failures failed to fetch packages since we don't build quincy for jammy.

0 Related Failures.
19 Tracked unrelated Failures.
0 Newly Tracked Failures.
0 Tracked dead Jobs.

https://pulpito.ceph.com/yuriw-2022-09-01_15:09:54-rados-wip-yuri2-testing-2022-08-29-0846-quincy-distro-default-smithi/

Rerun of:
https://pulpito.ceph.com/yuriw-2022-08-30_17:06:35-rados-wip-yuri2-testing-2022-08-29-0846-quincy-distro-default-smithi/

Failures, unrelated:
7005337, 7005340, 7005341, 7005344, 7005345, 7005346
7005347, 7005350 , 7005352, 7005354, 7005355: https://tracker.ceph.com/issues/57314
7005338, 7005348, 7005353: https://tracker.ceph.com/issues/57368
7005339, 7005351: https://tracker.ceph.com/issues/57346
7005342, 7005349: https://tracker.ceph.com/issues/57297
7005343: https://tracker.ceph.com/issues/56951

Details:

7005337, 7005340, 7005341, 7005344, 7005345, 7005346
7005347, 7005350 , 7005352, 7005354, 7005355: quincy: rados/cephadm: Failed to fetch package version from https://shaman.ceph.com...
7005338, 7005348, 7005353: The CustomResourceDefinition "installations.operator.tigera.io" is
7005339, 7005351: quincy: expected valgrind issues and found none
7005342, 7005349: quincy: cephadm: RuntimeError: Failed command: apt-get update: E: The repository 'https://download.ceph.com/debian-octopus jammy Release' does not have a Release file.
7005343: rook/smoke: Updating cephclusters/rook-ceph is forbidden

**Review by cbodley — APPROVED** [review]

**Pull request merged**
