### PR TITLE
osd: proxy features with proxied reads; only proxy reads to new peers

### PR DESCRIPTION
**Pull request by liewegas**
If we proxy reads, we need to pass through the original client features, too,
or else things (specifically copy-get and feature-dependent object_copy_data_t
encoding) break.

### CODE REVIEW

**Comment by liewegas** [comment]
Looking good in the upgrade test so far, will continue to pound on it some more.

**Comment by liewegas** [comment]
...and this is now passing my upgrade tests, yay!

**Comment by liewegas** [comment]
passed my wip-sage-testing run... need an ack from @athanatos before merge tho!

**Comment by liewegas** [comment]
changed get_up_osd_features

**Comment by athanatos** [comment]
lgtm, adding to wip-sam-testing

**Pull request merged**
