### PR TITLE
rgw: fix command argument error for radosgw-admin

### PR DESCRIPTION
**Pull request by yaozongyou**
Signed-off-by: Yao Zongyou <yaozongyou@vip.qq.com>

### CODE REVIEW

**Comment by yaozongyou** [comment]
The `radosgw-admin --help` displays reshard process, not reshard execute.
The command help doesn't match with the real command argument.

**Comment by joscollin** [comment]
@yaozongyou See: http://tracker.ceph.com/issues/21617.

You might want to create a tracker for backporting this fix too.

**Comment by yaozongyou** [comment]
@joscollin I have created a tracker:
http://tracker.ceph.com/issues/21723

**Comment by joscollin** [comment]
@yaozongyou Update it in the Commit message.

**Comment by yaozongyou** [comment]
Okay, the Commit message has been updated.

**Comment by yuriw** [comment]
[wip-yuri-testing-2017-10-09-1919](https://trello.com/c/2ungJPgu/175-wip-yuri-testing-2017-10-09-1919)

**Comment by yuriw** [comment]
[wip-yuri-testing-2017-10-10-2113](https://trello.com/c/6grUQb1g/176-wip-yuri-testing-2017-10-10-2113)

**Pull request merged**
