### PR TITLE
install-deps.sh: robust pip and wheel installation

### PR DESCRIPTION
**Pull request by dachary**
The wheel and pip module must not only be installed in each wheelhouse
directory for tox to find. They must also be installed in the virtual
environment that populates the wheelhouse directory. Otherwise older pip
modules such as the one found by default on Ubuntu 12.04 will fail.

Python 2.7.3 on Ubuntu 12.04 also requires that distribute >= 0.7.3 is
installed although it is redundant with setuptools, otherwise it will
fail to run the wheel module.

Signed-off-by: Loic Dachary <ldachary@redhat.com>

### CODE REVIEW

**Comment by dachary** [comment]
@nishtha3rai that should fix the problem you had. Could you please verify that it does ? Sorry for the inconvenience.

**Comment by nishtha3rai** [comment]
@dachary I am still getting the same error.. Here's the command and the output: http://paste2.org/0XOOLEGw

**Comment by dachary** [comment]
@nishtha3rai could you tell me what the output of **git rev-parse HEAD** is ?

**Comment by tchaikov** [comment]
i am not able to reproduce this issue. see http://paste2.org/UZH2Zp3C

- i removed all install-deps-* directory 
- removed ~/.cache/pip
- make clean
- run install-ceps.sh

**Comment by dachary** [comment]
@tchaikov I'll dig further and understand why it happens on flab, thanks for looking

**Comment by nishtha3rai** [comment]
@dachary Here's the output of git rev-parse HEAD: c23ddae457f1dd7fedf40c3fcf0ae42359659242

**Comment by dachary** [comment]
@nishtha3rai the install-deps.sh script that will work for you is in 
<pre>
git clone -b wip-install-deps http://github.com/ceph/ceph
</pre>
which is a871080 not c23ddae457f1dd7fedf40c3fcf0ae42359659242. You can also download it with
<pre>
wget -c https://raw.githubusercontent.com/dachary/ceph/a871080b41bb41839d0c4fb2611512f32b186941/install-deps.sh
</pre>

**Comment by nishtha3rai** [comment]
@dachary I ran the wget command.. here's the error http://paste2.org/mdZe46j3

**Comment by dachary** [comment]
@nishtha3rai could you please run it again with **bash -x install-deps.sh** ? That will give more informaiton about what happens. Are you running this on the **flab** machine ?

**Comment by nishtha3rai** [comment]
@dachary Here'e the output of the command: http://paste2.org/mWBVsMfV
I'm running this on the flab machine.

**Comment by dachary** [comment]
<pre>
Also creating executable in install-deps-python2.7/bin/python
Installing distribute.............................................................................................................................................................................................done.
Installing pip...............done.
Downloading/unpacking wheel
  Downloading wheel-0.24.0.tar.gz (50Kb): 50Kb downloaded
  Running setup.py egg_info for package wheel
    
    no previously-included directories found matching 'wheel/test/*/dist'
    no previously-included directories found matching 'wheel/test/*/build'
Installing collected packages: wheel
  Running setup.py install for wheel
    
    no previously-included directories found matching 'wheel/test/*/dist'
    no previously-included directories found matching 'wheel/test/*/build'
    Installing wheel script to /home/loic/ceph-ubuntu-12.04-loic/install-deps-python2.7/bin
Successfully installed wheel
Cleaning up...
Usage: pip COMMAND [OPTIONS]

pip: error: No command by the name pip wheel
  (maybe you meant "pip help -r requirements.txt -r test-requirements.txt setuptools >= 0.7 pip >= 6.1")
</pre>

**Comment by dachary** [comment]
@tchaikov I was able to reproduce the problem on 12.04 as shows above. I wonder why you can't. What is the SHA of the tree you run ?

**Comment by dachary** [comment]
@nishtha3rai http://paste2.org/mWBVsMfV shows you are not running https://raw.githubusercontent.com/dachary/ceph/a871080b41bb41839d0c4fb2611512f32b186941/install-deps.sh because there is no line where **setuptools >= 0.7** shows but your output has
<pre>
+ pip --timeout 300 wheel -r requirements.txt -r test-requirements.txt 'setuptools >= 0.7' 'pip >= 6.1'
</pre>
 To avoid any confusion could you try
<pre>
wget -O loic-install-deps.sh https://raw.githubusercontent.com/dachary/ceph/a871080b41bb41839d0c4fb2611512f32b186941/install-deps.sh
bash -x loic-install-deps.sh
</pre>

**Comment by dachary** [comment]
@tchaikov I tested with the **wip-install-deps** branch using the same method as https://github.com/ceph/ceph/pull/4799#issuecomment-106894606  after removing the ../ceph-ubuntu-12.04-loic tree entirely and it worked

**Comment by nishtha3rai** [comment]
I ran the commands you asked me to run.. Still producing the same error.. Here's the output: http://paste2.org/pttUdCsd

**Comment by dachary** [comment]
@nishtha3rai almost there :-) you should **make clean** to get rid of the bugous left overs from the previous runs.

**Comment by nishtha3rai** [comment]
@dachary Thanks It worked for me this time... no more error pastes :-D

**Comment by dachary** [comment]
@nishtha3rai great, thanks for your patience !

**Comment by tchaikov** [comment]
> @tchaikov I was able to reproduce the problem on 12.04 as shows above. I wonder why you can't. What is the SHA of the tree you run ?

i removed the my `../ceph-ubuntu-12.04-kchai` tree, and i am able to reproduce this problem also.

**Comment by tchaikov** [comment]
```
 > git checkout -f 5b63ca5a30a541e7e32cac59eb0695d47d7994f5
FATAL: Could not checkout null with start point 5b63ca5a30a541e7e32cac59eb0695d47d7994f5
hudson.plugins.git.GitException: Could not checkout null with start point 5b63ca5a30a541e7e32cac59eb0695d47d7994f5
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$8.execute(CliGitAPIImpl.java:1855)
	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$1.call(RemoteGitImpl.java:152)
	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$1.call(RemoteGitImpl.java:145)
	at hudson.remoting.UserRequest.perform(UserRequest.java:121)
	at hudson.remoting.UserRequest.perform(UserRequest.java:49)
	at hudson.remoting.Request$2.run(Request.java:324)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
```

the failure is due to overwritten commit, i assume. thus not relevant.

**Comment by tchaikov** [comment]
:+1:

**Pull request merged**
