### PR TITLE
cephadm: fix ceph-iscsi deploy with json

### PR DESCRIPTION
**Pull request by matthewoliver**
We were making pool a requirement, even though we say we can use a json
file with `-i` to deploy ceph-iscsi.

This patch fixes this. If your not using `-i <json>` then pool is still
required. But this means tools can deploy with json.

Fixes: https://tracker.ceph.com/issues/45198
Signed-off-by: Matthew Oliver <moliver@suse.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by bk201** [comment]
Created another issue to track the error when applying a ServiceSpec: https://tracker.ceph.com/issues/45249

I'm a bit confused, should these two call paths share the same spec?
From this PR, it seems to accept a data structure like this:
```
{                                                                                                                                                                                                                                             
  "service_id": "iscsi",
  "pool": "iscsi",
  "trusted_ip_list": null,
  "fqdn_enabled": null,
  "api_port": null,
  "api_user": null,
  "api_password": null,
  "api_secure": null,
  "ssl_cert": null,
  "ssl_key": null,
  "service_type": "iscsi",
  "placement": {
    "hosts": [{
      "hostname": "ironic-moliver",
      "name": "",
      "network": "" 
    }],
    "count": 1
  },
  "unmanaged": false
}
```

But when using `orch apply -i <file>`, the spec should look like below ([doc](https://docs.ceph.com/docs/master/mgr/orchestrator/#service-specification)), which arguments for iSCSI is under `spec` key.
```
service_type: iscsi 
service_id: test
placement:
  hosts:
    - osd0
spec:
  pool: rbd
  api_user: admin
  api_password: admin
  trusted_ip_list: 192.168.121.1
```

I'm not sure if two paths should accept the same data.

**Comment by tchaikov** [comment]
- http://pulpito.ceph.com/kchai-2020-04-26_09:25:11-rados-wip-kefu-testing-2020-04-26-1313-distro-basic-smithi/
- http://pulpito.ceph.com/kchai-2020-04-26_13:55:50-rados-wip-kefu-testing-2020-04-26-1314-distro-basic-smithi/
- http://pulpito.ceph.com/kchai-2020-04-27_01:47:10-rados-wip-kefu-testing-2020-04-26-1314-distro-basic-smithi/

need to rerun the failed tests without #34728

**Comment by matthewoliver** [comment]
> I'm not sure if two paths should accept the same data.

That is a great question, and to be honest, I didn't know the apply yaml approach existed, it is a little strange.

**Comment by sebastian-philipp** [comment]
> > I'm not sure if two paths should accept the same data.
> 
> That is a great question, and to be honest, I didn't know the apply yaml approach existed, it is a little strange.

Both are actually the same data. it's just a matter of where we want to unify.

**Comment by mgfritch** [comment]
> +1
> I just noticed that we miss the `-i` option for `apply nfs` and `apply mds`. Something for another PR though.

Do we really want to support two variations of the cli (#34843)?
```
$ ceph orch apply -i nfs.yaml
--and--
$ ceph orch apply nfs [pool] [namespace] -i nfs.yaml
```

**Comment by sebastian-philipp** [comment]
needs rebase

**Comment by sebastian-philipp** [comment]
do we want to close it in favor of #34843 ?

**Pull request closed without merging**
