### PR TITLE
osd/PG: tolerate missing pgmeta object

### PR DESCRIPTION
**Pull request by liewegas**
Bug 10617 left stray PG dirs around in firefly.  Hammer correctly
ignores these, assuming they are leftover cruft.  We broke this
when we dropped compat support in cd4e676e6d45c8166290ef834d73c2a0bda98fa2

Signed-off-by: Sage Weil <sage@redhat.com>

### CODE REVIEW

**Comment by tchaikov** [comment]
@liewegas the failure is not a false alarm.
```
osd/PG.cc: In static member function 'static epoch_t PG::peek_map_epoch(ObjectStore*, spg_t, ceph::bufferlist*)':
osd/PG.cc:2754:386: error: 'this' is unavailable for static member functions
     dout(1) << __func__ << " unable to open pg metadata" << dendl;
                                                                                                                                                                                                                                                                                                                                                                                                  ^
make[3]: *** [osd/libosd_la-PG.lo] Error 1
```

**Comment by liewegas** [comment]
http://pulpito.ceph.com/sage-2015-09-09_19:14:47-rados-wip-sage-testing---basic-multi/

**Comment by tchaikov** [comment]
and the test run of http://pulpito.ceph.com/sage-2015-09-09_19:14:47-rados-wip-sage-testing---basic-multi/ didn't get very far due to environmental issues. am i looking at the right run?

**Comment by liewegas** [comment]
oops, it's

/a/sage-2015-09-09_19:37:11-rados-wip-sage-testing---basic-multi/1047745

**Comment by tchaikov** [comment]
@liewegas checked /a/sage-2015-09-09_19:37:11-rados-wip-sage-testing---basic-multi/1047745 , 
```
$ zgrep 'omap_get_values.*= -' remote/burnupi50/log/ceph-osd.*.log.gz
```
does not show anything. i thought if it fails a negative number should be returned.

**Comment by liewegas** [comment]
Hrm, I need to find teh original failure that made me fix this.  sorry for 
the runaround...

**Comment by liewegas** [comment]
The original failure was /a/sage-2015-09-07_18:07:23-rados-wip-sage-testing---basic-multi/1046304

**Comment by liewegas** [comment]
pool 3 was deleted, pg 3.101 deletion was queued but not completed...
<pre>
2015-09-07 22:37:36.538395 7f9761807700  5 filestore(/var/lib/ceph/osd/ceph-2) queue_transactions existing osr(3.101 0x268f410)/0x268f410
2015-09-07 22:37:36.572277 7f9766f4c700  5 filestore(/var/lib/ceph/osd/ceph-2) _journaled_ahead 0x74d4000 seq 34769 osr(3.101 0x268f410) 0x2d6f840
2015-09-07 22:37:36.572287 7f9766f4c700  5 filestore(/var/lib/ceph/osd/ceph-2) queue_op 0x74d4000 seq 34769 osr(3.101 0x268f410) 893 bytes   (queue has 47 ops and 40458 bytes)
2015-09-07 22:37:36.572345 7f9765f4a700  5 filestore(/var/lib/ceph/osd/ceph-2) _do_op 0x74d4000 seq 34769 osr(3.101 0x268f410)/0x268f410 start
2015-09-07 22:37:36.572354 7f9765f4a700 10 filestore(/var/lib/ceph/osd/ceph-2) collection_setattr /var/lib/ceph/osd/ceph-2/current/3.101_head 'info' len 1
2015-09-07 22:37:36.572404 7f9765f4a700 10 filestore(/var/lib/ceph/osd/ceph-2) collection_setattr /var/lib/ceph/osd/ceph-2/current/3.101_head 'info' len 1 = 1
2015-09-07 22:37:36.595684 7f9765f4a700 10 filestore(/var/lib/ceph/osd/ceph-2) _finish_op 0x74d4000 seq 34769 osr(3.101 0x268f410)/0x268f410
</pre>
subsequent restart ignored the pg dir
<pre>
2015-09-07 22:37:56.245294 7fcb4c3c9800  0 ceph version 0.80.8 (69eaad7f8308f21573c604f121956e64679a52a7), process ceph-osd, pid 31152
...
2015-09-07 22:37:57.860115 7fcb4c3c9800 10 osd.2 11 load_pgs: skipping PG 3.101 because we don't have pool 3
</pre>
and later when infernalis osd starts,
<pre>
    -3> 2015-09-07 23:03:38.467927 7f0b95cfa980 10 osd.2 430 pgid 3.101 coll 3.101_head
    -2> 2015-09-07 23:03:38.467936 7f0b95cfa980 15 filestore(/var/lib/ceph/osd/ceph-2) omap_get_values 3.101_head/3/00000101//head
    -1> 2015-09-07 23:03:38.467982 7f0b95cfa980 15 filestore(/var/lib/ceph/osd/ceph-2) omap_get_values 3.101_head/3/00000101//head = -2 (lfn_find)
     0> 2015-09-07 23:03:38.470447 7f0b95cfa980 -1 osd/PG.cc: In function 'static epoch_t PG::peek_map_epoch(ObjectStore*, spg_t, ceph::bufferlist*)' thread 7f0b95cfa980 time 2015-09-07 23:03:38.467987
osd/PG.cc: 2753: FAILED assert(0 == "unable to open pg metadata")
</pre>
this is because hammer did not see the pg and convert it to the new pgmeta format.

There is a 10 second sleep in the sequence that appearently wasn't enough time for the pg to get fully cleaned up before the osd restarted.

In any case, this fixes the issue...

**Comment by liewegas** [comment]
@tchaikov Oh, now I see what you were saying.. 0 isn't the right value to return here (I misread the if condition).  There is a similar bug in hammer, see http://tracker.ceph.com/issues/13060.  Reworking this...

**Comment by tchaikov** [comment]
@liewegas thanks for explaining the root cause why we have leftover pg dirs. but i don't think /a/sage-2015-09-09_19:37:11-rados-wip-sage-testing---basic-multi/1047745 reproduced the problem we found in /a/sage-2015-09-07_18:07:23-rados-wip-sage-testing---basic-multi/1046304. if there are pg dirs left in OSD's data directory but pgmeta object is missing, we should have at least two lines of error messages for each missing pg dir:
```
2015-09-07 23:03:44.036957 7f98d96a9980 15 filestore(/var/lib/ceph/osd/ceph-0) omap_get_values 3.25a_head/3/0000025a//head = -2 (lfn_find)
```
one is printed by `PG::_has_removal_flag()`. it will accept the failure, BTW. the other comes from `PG::peek_map_epoch()`. and the later is less tolerant. but i cannot find any error messages for the failing `lfn_find` call. i am not surprised, though. cause there are chances that the PGs got cleaned. but the crux is: this does not prove that the fix.

**Comment by tchaikov** [comment]
ahh, nvm. =)

**Comment by liewegas** [comment]
i agree we're not reproducing the issue.  i'm not sure how much time it's worth putting into it, though, as I expect it'll be a bit difficult to do it..

**Comment by liewegas** [comment]
see https://github.com/ceph/ceph/pull/5892

**Comment by liewegas** [comment]
https://github.com/ceph/ceph-qa-suite/pull/563 is the fixed test

**Comment by liewegas** [comment]
passes updated test!

**Comment by liewegas** [comment]
ugh, i merged liewegas instead of ceph branch.

**Pull request merged**
