### PR TITLE
octopus: osd/PeeringState: fix pending want_acting vs osd offline race

### PR DESCRIPTION
**Pull request by smithfarm**
backport tracker: https://tracker.ceph.com/issues/44717

---

backport of https://github.com/ceph/ceph/pull/33841
parent tracker: https://tracker.ceph.com/issues/44507

this backport was staged using ceph-backport.sh version 15.1.0.437
find the latest version at https://github.com/ceph/ceph/blob/master/src/script/ceph-backport.sh

### CODE REVIEW

**Comment by athanatos** [comment]
There's a folowup bug fix for this one, let's put it off for a bit.  @xiexingguo right?

**Comment by xiexingguo** [comment]
@athanatos Itself is a follow-up fix of https://github.com/ceph/ceph/pull/33841, which should have been merged octopus. I think we should backport this one to octopus.

**Comment by athanatos** [comment]
Ah, right, had it backwards.

**Comment by yuriw** [comment]
[wip-yuri7-testing-2020-03-26-1533-octopus](https://trello.com/c/fRQaZ8xS/855-wip-yuri7-testing-2020-03-26-1533-octopus)

**Pull request merged**
