### PR TITLE
cephadm: Make ceph-iscsi SSL aware

### PR DESCRIPTION
**Pull request by matthewoliver**
Ceph-iscsi's `rbd-target-api.py` supports listening over SSL if you
provide an SSL cert and key. Originally the script is opinionated and
requires these files to be named `/etc/ceph/iscsi-gateway.{crt,key}`.

When dealing with containers, having to place files inside a container to
enable SSL isn't very clean. To make things easier, like RGW, you can
now place the SSL cert and key data in the mon config-key store.
Well, we will be able once this PR[0] lands.

This will mean there are 2 ways to enable SSL in ceph-iscsi via orch/cephadm.

1. Push the SSL key and cert into the mon config-key under the keys, below, and
   then make sure api_secure is enabled (requires json):

  iscsi/{clientname}/iscsi-gateway.crt
  iscsi/{clientname}/iscsi-gateway.key

2. Provide the SSL key and cert in the json you pass the orchestrator and
   it'll push them up for you.

NOTE: This patch cannot merge until the ceph-iscsi pr[0] lands.

[0] - https://github.com/ceph/ceph-iscsi/pull/173

Signed-off-by: Matthew Oliver <moliver@suse.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by matthewoliver** [comment]
Just corrected the commit message.

Like patch can't be merged until the related ceph-iscsi PR has: https://github.com/ceph/ceph-iscsi/pull/173

**Comment by dillaman** [comment]
I apparently left my caps comment in a merged PR, but since this one is open, `cephadm` should create a user with `profile osd` caps for `mon` and `osd` -- and the `mon` should have a second cap for `allow command "config-key get" with "key" prefix "iscsi/"`

**Comment by matthewoliver** [comment]
Thanks @dillaman ! I'll make sure I tighten the caps with these and test. Cheers!

**Comment by matthewoliver** [comment]
This version is rebased and has a locked down mon caps.

**Comment by sebastian-philipp** [comment]
http://pulpito.ceph.com/swagner-2020-05-04_13:28:01-rados-wip-swagner-testing-2020-05-04-1211-distro-basic-smithi/

https://tracker.ceph.com/issues/45335

**Pull request merged**
