### PR TITLE
rgw: the http response code of delete bucket should not be 204-no-content

### PR DESCRIPTION
**Pull request by liuchang0812**
Fixes: https://tracker.ceph.com/issues/41925

Signed-off-by: Chang Liu <liuchang0812@gmail.com>

## Checklist
- [x] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`

</details>

### CODE REVIEW

**Comment by liuchang0812** [comment]
@cbodley @yehudasa the nodejs standard library could not parse this http response with wrong http code.

**Comment by liuchang0812** [comment]
> @liuchang0812 i don't see anything in radosgw that reads this info returned in the body. unless @yehudasa objects, i'd prefer to remove that and continue returning 204 like s3 clients would expect
> 
> is there a particular reason your nodejs project needs to use system requests? i don't think we've ever made guarantees about API stability for system requests, so we may make breaking changes in the future (as i hinted at regarding removing the body of this reply)

@cbodley the json info returned in the body is an `objv_tracker.read_version`. we pass a objv_tracker to [rados::delete_bucket](https://github.com/ceph/ceph/blob/master/src/rgw/rgw_op.cc#L3433). should we use the json info to update `objv_tracker` when delete bucket request is processed in slave zone?

**Comment by cbodley** [comment]
> should we use the json info to update objv_tracker when delete bucket request is processed in slave zone?

that would be consistent with the logic around forwarding the `rgwx-ver` to the master, and could detect racing writes to the bucket metadata while it was being deleted on the master

but what would be the right response to races on the secondary zone? since we've already successfully deleted the bucket on the master zone, i don't think it's appropriate to fail the delete op on the secondary zone

**Comment by cbodley** [comment]
@liuchang0812 given my last comment, do you agree that we can safely remove the response body to resolve this issue?

**Comment by liuchang0812** [comment]
> @liuchang0812 given my last comment, do you agree that we can safely remove the response body to resolve this issue?

yes, I agree that. I will update this PR soon. thank you @cbodley

**Comment by liuchang0812** [comment]
ping

**Pull request merged**
