### PR TITLE
tools/cephfs: include lost+found in scan_links

### PR DESCRIPTION
**Pull request by batrick**
Otherwise, any injected dentries have incorrect first snapids.

Fixes: https://tracker.ceph.com/issues/59183

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [x] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by batrick** [comment]
```
2023-03-27T23:19:01.924 INFO:teuthology.orchestra.run.smithi018.stderr:2023-03-27T23:19:01.904+0000 7f37292527c0 10 datascan.scan_links: step 2: handling object 4.00000000
2023-03-27T23:19:01.924 INFO:teuthology.orchestra.run.smithi018.stderr:2023-03-27T23:19:01.904+0000 7f37292527c0  1 -- 172.21.15.18:0/699875016 --> [v2:172.21.15.136:6817/110352,v1:172.21.15.136:6819/110352] -- osd_op(unknown.0.0:68 30.3 30:c0ce80d4:::4.00000000:head [omap-get-vals in=16b] snapc 0=[] ondisk+read+known_if_redirected+supports_pool_eio e234) v8 -- 0x56054d224800 con 0x56054d112800
2023-03-27T23:19:01.924 INFO:teuthology.orchestra.run.smithi018.stderr:2023-03-27T23:19:01.905+0000 7f371a3fc700  1 -- 172.21.15.18:0/699875016 <== osd.6 v2:172.21.15.136:6817/110352 14 ==== osd_op_reply(68 4.00000000 [omap-get-vals out=513b] v0'0 uv2 ondisk = 0) v8 ==== 154+0+513 (crc 0 0 0) 0x56054d0f38c0 con 0x56054d112800
2023-03-27T23:19:01.924 INFO:teuthology.orchestra.run.smithi018.stderr:2023-03-27T23:19:01.905+0000 7f37292527c0 20 datascan.scan_links: injected ino detected
2023-03-27T23:19:01.925 INFO:teuthology.orchestra.run.smithi018.stderr:2023-03-27T23:19:01.905+0000 7f37292527c0 20 datascan.scan_links: adding 0x10000000001 for future processing to fix dnfirst
```

/teuthology/pdonnell-2023-03-27_22:29:12-fs-wip-pdonnell-testing-20230327.200655-distro-default-smithi/7221874/teuthology.log

Fixed now.

**Comment by batrick** [comment]
jenkins test make check arm64

**Comment by batrick** [comment]
jenkins test make check arm64

**Comment by batrick** [comment]
https://pulpito.ceph.com/?branch=wip-pdonnell-testing-20230323.162417

**Comment by vshankar** [comment]
I wonder if the first field corruption is a fallout from this issue? Seems alarmingly close to what we've been seeing.

**Comment by batrick** [comment]
> I wonder if the first field corruption is a fallout from this issue? Seems alarmingly close to what we've been seeing.

We had thought so but it requires running `cephfs-data-scan` which none of the clusters had used (to our knowledge).

**Pull request merged**
