### PR TITLE
build/ops: rpm: make ceph-grafana-dashboards own its directories

### PR DESCRIPTION
**Pull request by smithfarm**
Fixes: http://tracker.ceph.com/issues/37485
Signed-off-by: Nathan Cutler <ncutler@suse.com>

- [x] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by smithfarm** [comment]
From openSUSE spec file guidelines [1]:

"Your package should own all files that are installed as part of the %install process.
...
Directory ownership is a little more complex than file ownership. Although the rule of thumb is the same: own all the directories you create but none of the directories of packages you depend on . . . ."

[1] https://en.opensuse.org/openSUSE:Specfile_guidelines

**Comment by smithfarm** [comment]
@tserong Got your point. I modified the commit, so could you take a look? I'm now thinking that we need to add both `BuildRequires: grafana` and `Requires: grafana` inside suse conditionals, because otherwise we have no assurance that there will be a grafana user in the system?

**Comment by tserong** [comment]
> I'm now thinking that we need to add both `BuildRequires: grafana` and `Requires: grafana` inside suse conditionals, because otherwise we have no assurance that there will be a `grafana` group in the system?

If we add those Requires, there'd be no need for us to own /etc/grafana. But, of course, it means grafana needs to be in the base distro, which it isn't presently.

It's possible to cheat a little bit though (depending on how picky OBS/rpmlint is going to be). I did a quick test here (I made a little package which includes nothing other than /etc/grafana and /etc/grafana/dashboards), and if the grafana user doesn't exist when the package is installed, you get "warning: group grafana does not exist - using root" on install. Later, if you install grafana, the directory ownership gets set correctly, and there's no conflict. So if you're happy to cheat a little bit (and possibly fiddle with rpmlintrc, in case rpmlint whines about missing groups), this may be the path of least resistance.

**Comment by smithfarm** [comment]
@tserong Good to know the non-existent grafana group won't be a fatal error - thanks!

**Comment by b-ranto** [comment]
You can also use a UID/GID directly if the grafana UID/GID gets reserved for the distro. The grafana upstream suggests using 472 as grafana UID/GID. Previously, we did something similar for ceph UID/GID.

**Comment by tserong** [comment]
Unfortunately we don't have an officially reserved grafana UID/GID on openSUSE (the grafana package just runs `groupadd -r grafana ; useradd -r grafana`, so you end up with an arbitrary UID/GID in the system range)

**Comment by smithfarm** [comment]
Changelog:

* rebased on latest master
* pushed to ceph-ci, awaiting build result at http://shaman.ceph.com/builds/ceph/wip-37485/c1083b2f4f16ba910ef00705e615174e55a53b16

**Comment by b-ranto** [comment]
You can always request it to be added there. You can start creating the grafana user with the uid/gid in the spec file for grafana as soon as it gets approved -- you can be sure that uid/gid won't be used by any other package at that point.

**Comment by smithfarm** [comment]
@b-ranto What @tserong described is the openSUSE way of adding new groups. For all practical purposes, there is no such thing as a fixed GID in openSUSE (at least for new projects like ceph, grafana, etc.).

**Pull request merged**
