### PR TITLE
rgw: make RGWLocalAuthApplier::is_admin_of() aware about system users.

### PR DESCRIPTION
**Pull request by rzarzynski**
Fixes: http://tracker.ceph.com/issues/18106

Undergoes testing at the moment.

CC: @cbodley.

### CODE REVIEW

**Comment by cbodley** [comment]
that makes sense - thanks for looking into this! you might want to use `--filter=radosgw-admin-data-sync.yaml` when you schedule in teuthology just to make sure it resolves those "object not deleted in destination zone" failures

**Comment by rzarzynski** [comment]
@cbodley: thanks for the info! I will schedule a run.

Locally both s3-tests and Tempest haven't found any regression in comparison to the current master (3a9bcaa4aa6042587886c0eaae0ce4eeeb8f8164, `Fri Dec 2 14:48:15 2016 +0800`).

s3-tests found an unrelated issue in `master` (so no regression here) which causes a failure in following tests:
```
s3tests.functional.test_s3.test_versioning_multi_object_delete
s3tests.functional.test_s3.test_versioning_multi_object_delete_with_marker
```
I'm going to fill a ticket for that.

**Comment by cbodley** [comment]
@rzarzynski a fix for those s3test failures merged yesterday: https://github.com/ceph/ceph/pull/12262

**Comment by rzarzynski** [comment]
@cbodley: thanks for the link, Casey!

**Comment by cbodley** [comment]
lots of unrelated teuthology failures recently, but I've managed to stitch together enough passes to validate this pr - sorry for the delays

**Comment by rzarzynski** [comment]
@cbodley: do we need to backport this to the `kraken` branch?

**Comment by cbodley** [comment]
@rzarzynski as far as i know, the kraken branch has not yet diverged from master

**Pull request merged**
