### PR TITLE
mds: misc load balancer fixes

### PR DESCRIPTION
**Pull request by ukernel**

### CODE REVIEW

**Comment by ktdreyer** [comment]
Would you please file a tracker.ceph.com ticket to ensure this is backported to luminous?

**Comment by batrick** [comment]
http://pulpito.ceph.com/?branch=wip-pdonnell-testing-20180329.205635

**Comment by batrick** [comment]
http://pulpito.ceph.com/?branch=wip-pdonnell-testing-20180405.233852

**Comment by batrick** [comment]
retest this please

**Comment by batrick** [comment]
http://pulpito.ceph.com/?branch=wip-pdonnell-testing-20180410.183536

**Pull request merged**
