### PR TITLE
Refine build configuration for hammer

### PR DESCRIPTION
**Pull request by borix**
I worked on ceph build time configuration refinement for some time. To achieve this I propose to add several new configure options:

--enable/disable-server
--enable/disable-client

These two option would divide all the code to four parts:

shared/common     -- this will be build every time, necessary for both server as well as client
client            -- if client build is enabled
server            -- if server build is enabled
server and client -- if both server and client build is enabled

The difference between first and last category is that the first category contains libraries (like libcommon) while the last one contains mostly binaries. (for instance some of the tests require both server and
client)

I also added several other options that would further refine all of the four categories:

--with/without-rados
--with/without-rbd
--with/without-cephfs
--with/without-radosgw (this one is actually already there)
--with/without-radosstriper
--with/without-mon
--with/without-osd
--with/without-mds

Implementing all of this in a single Makefile.am file would result in a lot of mess. Hence, I propose to split the Makefile.am files (where appropriate) and introduce two new files:

Makefile-client.am
Makefile-server.am

As for the four categories, the shared/common stuff would still go to Makefile.am, the client stuff would go to Makefile-client.am and the other two categories would go to Makefile-server.am.

### CODE REVIEW

**Comment by dalgaaf** [comment]
For what are these two options needed:
--with/without-mon
--with/without-osd

Why would you build e.g. the server target without these two? I understand that you may want to build server without radosgw or cephfs/mds but without mon or osd? These are essential core components for server. It increases the complexity and may introduce unintended errors while building packages.

**Comment by branto1** [comment]
@dalgaaf: Hi, they might seem like an overkill but actually, those two are not very difficult to handle (**). I suppose this could help with the porting/basic compilation code testing.

(**) I've used WITH_OSD only 8 times in the patches and WITH_MON only 4 times.

**Comment by liewegas** [comment]
This passes my smoke test, FWIW; I think it's safe to merge!

**Comment by dachary** [comment]
please ignore the over zealous bot building closed pull requests

**Pull request merged**
