### PR TITLE
jewel: rgw: add_zone only clears master_zone if --master=false

### PR DESCRIPTION
**Pull request by cbodley**
http://tracker.ceph.com/issues/16086

### CODE REVIEW

**Comment by dachary** [comment]
@cbodley could you please repush with cherry-pick -x so that the commit has a reference to the corresponding master commit ?

**Comment by cbodley** [comment]
@dachary done, thank you

**Comment by dachary** [comment]
@cbodley thanks !

**Comment by Abhishekvrshny** [comment]
test this please

**Comment by dachary** [comment]
It passed the rgw suite http://tracker.ceph.com/issues/16344#note-6 (except for one failure which I believe to be unrelated).

**Pull request merged**
