### PR TITLE
qa: cleanup journal repair mds manipulation

### PR DESCRIPTION
**Pull request by batrick**

### CODE REVIEW

**Comment by batrick** [comment]
jenkins test make check arm64

**Comment by batrick** [comment]
https://tracker.ceph.com/projects/cephfs/wiki/Master#2021-July-30

**Comment by batrick** [comment]
Ready to merge after approval.

**Comment by batrick** [comment]
https://tracker.ceph.com/projects/cephfs/wiki/Master#2021-August-27

**Comment by batrick** [comment]
ping @ceph/cephfs

**Review by vshankar — APPROVED** [review]
LGTM

**Pull request merged**
