### PR TITLE
cephadm: Clarify no container engine message

### PR DESCRIPTION
**Pull request by sebastian-philipp**
Multiple people didn't understand the message. Let's try to impove it.

Signed-off-by: Sebastian Wagner <sewagner@redhat.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Review by adk3798 — APPROVED** [review]

**Review by dsavineau — APPROVED** [review]

**Comment by sebastian-philipp** [comment]
https://pulpito.ceph.com/swagner-2021-07-20_10:26:40-rados:cephadm-wip-swagner2-testing-2021-07-19-1105-distro-basic-smithi/

failure caused by #42389

**Comment by sebastian-philipp** [comment]
cephadm:1984: error: Generator has incompatible item type "Callable[[ContainerEngine], str]"; expected "str"

**Comment by tchaikov** [comment]
- https://pulpito.ceph.com/kchai-2021-07-29_08:05:42-rados-wip-kefu-testing-2021-07-29-1336-distro-basic-smithi/
- https://pulpito.ceph.com/kchai-2021-07-30_04:58:53-rados-wip-kefu-testing-2021-07-30-0947-distro-basic-smithi/
- https://pulpito.ceph.com/kchai-2021-07-30_10:20:53-rados-wip-kefu-testing-2021-07-30-1358-distro-basic-smithi/

**Comment by tchaikov** [comment]
jenkins test make check

**Comment by tchaikov** [comment]
jenkins test make check

**Pull request merged**
