### PR TITLE
crimson: fix incorrect interval check in PG::submit_transaction

### PR DESCRIPTION
**Pull request by athanatos**
Removes incorrect interval check in PG::submit_transaction as well as a few other checks which duplicate IOInterruptCondition.  This PR also adds logging improvements that were helpful in tracking down the bug.

Fixes: https://tracker.ceph.com/issues/58486

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by athanatos** [comment]
https://pulpito.ceph.com/sjust-2023-01-30_19:56:26-crimson-rados-wip-sjust-58486-distro-default-smithi/ -- failures due to rbd issues

**Comment by athanatos** [comment]
Modifies common/dout.h, but I'm disinclined to do a rados run since there's a large backlog of tests pending and it's a pretty trivial change more likely to cause a build issue than a runtime one.

**Review by xxhdx1985126 — APPROVED** [review]

**Comment by xxhdx1985126** [comment]
@athanatos I think this PR is laying the ground work for fixing https://tracker.ceph.com/issues/58486, am I right?

**Comment by athanatos** [comment]
@xxhdx1985126 The last commit should fix it.

**Comment by xxhdx1985126** [comment]
> @xxhdx1985126 The last commit should fix it.

Ah, yes, pg's acting/up set may be the same in different osd maps, am I right?

**Comment by athanatos** [comment]
@xxhdx1985126 Precisely.  For any specific PG, the vast majority of map changes do not affect the up or acting set.  Many map changes contain only changes to things like snapshot metadata and therefore affect no pg's up/acting set.  For a specific PG, we call a contiguous sequence of map epochs with no changes to the up/acting set (or a few other things) an interval.  See osd_types.h PastIntervals::is_new_interval() for the precise definition of when two consecutive maps constitute an interval change.

**Pull request merged**
