### PR TITLE
rgw: optimize gc chain size calculation

### PR DESCRIPTION
**Pull request by lightmelodies**
Reduce time complexity of gc chain size calculation from O(n^2) to O(n). 

The time cost of deleting a 50GB object reduces from 20s to 0.05s with this patch.

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [x] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Review by cbodley — APPROVED** [review]
looks correct, thanks

**Comment by cbodley** [comment]
cc @pritha-srivastava. can you think of a good way to test/verify this?

**Comment by lightmelodies** [comment]
Sadly we still have many slow deletions when a set of large objects been deleted or overwrite together.  The gc queue becomes full quickly and rgw has to delete objs inline. The workaround of https://github.com/ceph/ceph/pull/46020 does not help in these cases. It might be better to completely rewrite gc logic with just **RGWObjManifest** instead of the large **gc chain**.

**Comment by cbodley** [comment]
> It might be better to completely rewrite gc logic with just **RGWObjManifest** instead of the large **gc chain**.

thanks @lightmelodies (and cc @mattbenjamin @pritha-srivastava)

RGWObjManifest does have a big advantage for large multipart objects, in that it can potentially represent all parts with a single rule. this gives us a very compact representation that's still able to generate all of the tail object names

only for part reuploads does it have to insert new rules to override the part prefixes. in extreme cases with *lots* of reuploaded parts, the manifest may still grow larger than osd_max_write_size so we'd need a way to 'split' such a manifest. i believe that the AppendObject op adds a new rule for each append, so could also grow very large

the CompleteMultipartUpload op already has to merge together the manifests of each part into the final multipart manifest, so it may not be too difficult to support this splitting as well

the alternative to relying on RGWObjManifest directly would be to teach gc chains a similar form of compression

**Comment by mattbenjamin** [comment]
yeah, I'm not sure if we should really send the entire manifest here;  I like the idea of upleveling the gc protocol to accept a pattern rule as an alternative to object list (and building some flexibility in to do future things), as I think @cbodley is suggesting;  it won't address the cost of actually processing the deletes, but it sounds like that's not the bottleneck you are seeing.

**Comment by cbodley** [comment]
> yeah, I'm not sure if we should really send the entire manifest here; I like the idea of upleveling the gc protocol to accept a pattern rule as an alternative to object list (and building some flexibility in to do future things), as I think @cbodley is suggesting; it won't address the cost of actually processing the deletes, but it sounds like that's not the bottleneck you are seeing.

i think both strategies would work. can we try to weigh pros/cons?

both seem to have the same considerations for backward-compatibility. the gc chain's encoding would either add an RGWObjManifest or some similar custom structure. gc would need to interpret new entries vs. old, and avoid writing new gc chains until all radosgws are upgraded to a version that understands them

since RGWObjManifest is the thing that knows most about the object's layout, it does seem reasonable for gc to use it too. do we gain much by hiding it?

conversely, if we build new/separate logic into gc chains to generate tail object names, there's a risk of divergence if we make later changes to RGWObjManifest

currently, gc is tightly coupled to the rados backend, and RGWObjManifest is exposed 'above the line' by all backends. even if we wanted to change both of those decisions, the gc chain could contain an opaque bufferlist that the rados backend interprets as a RGWObjManifest

**Comment by mattbenjamin** [comment]
@cbodley my intuition is that the obj manifest might end up containing information which we do not want to send to gc, or prefer not to send all at once (you mentioned one example, the append stuff [which we might have been better off without, but...].  It's true that an RGWObjManifest *can* now be decoded in cls, and I was partly thinking of this kind of thing when doing the UploadPartInfo change.  I somehow have the intuition that the manifest is going to bring more coupling.

**Comment by cbodley** [comment]
passed qa in https://pulpito.ceph.com/cbodley-2024-02-02_18:51:03-rgw-wip-cbodley2-testing-distro-default-smithi/

**Comment by cbodley** [comment]
> It might be better to completely rewrite gc logic with just RGWObjManifest instead of the large gc chain.

@pritha-srivastava @mattbenjamin just a friendly reminder about our discussion here. i'm continuing to see upstream reports about major performance regressions when the gc queue fills up. this is easy to reproduce with large multipart uploads

from @BBoozmen on slack:
> uploading a 750GB object timed out. 128MB chunk size was used (5K+ parts/chunks). All parts were uploaded (PUT requests) successfully but the final POST request to complete the MPU took almost 10 mins to complete.

**Pull request merged**
