### PR TITLE
luminous: rgw recalculate stats option added 

### PR DESCRIPTION
**Pull request by theanalyst**
http://tracker.ceph.com/issues/23691

### CODE REVIEW

**Comment by yuriw** [comment]
[wip-yuri3-testing-2018-04-12-1932-luminous](https://trello.com/c/34KBemql/294-wip-yuri3-testing-2018-04-12-1932-luminous)

**Comment by smithfarm** [comment]
@yuriw @theanalyst The master PR https://github.com/ceph/ceph/pull/20853 is still open?

**Comment by smithfarm** [comment]
And two of the commit messages have two "cherry-picked from" lines.

**Comment by theanalyst** [comment]
@smithfarm thanks for cleaning this up, I had the branch staged on luminous before-hand and did a cherry-pick -x instead of a cherry-pick causing the double cherry-picked from message, sorry about that.

**Pull request merged**
