### PR TITLE
cmake: pass -d0 to b2 if not CMAKE_VERBOSE_MAKEFILE

### PR DESCRIPTION
**Pull request by tchaikov**
Signed-off-by: Kefu Chai <kchai@redhat.com>

### CODE REVIEW

**Comment by tchaikov** [comment]
jenkins retest this please

**Comment by tchaikov** [comment]
so the ./b2 is less chatty when building/installing.

**Comment by cbodley** [comment]
looks okay to me - what controls this `CMAKE_VERBOSE_MAKEFILE` variable?

**Comment by tchaikov** [comment]
@cbodley
```sh
cmake -DCMAKE_VERBOSE_MAKEFILE=ON
```
=)

and per https://cmake.org/cmake/help/v3.0/variable/CMAKE_VERBOSE_MAKEFILE.html, `project()` sets it to `FALSE`.

**Comment by tchaikov** [comment]
@cbodley can i take your comment as a LGTM =)

**Comment by tchaikov** [comment]
retest this please

**Pull request merged**
