### PR TITLE
nautilus: mgr/progress: make it so progress bar does not get stuck forever

### PR DESCRIPTION
**Pull request by kamoltat**
Fixing an issue with mgr/progress module, where the progress bar gets stuck forever, by back porting the relevant commits from master PRs:

#28368
#28498
#28695
#29111
#38107

Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1826224

### CODE REVIEW

**Review by neha-ojha — COMMENTED** [review]
could you please use "git cherry-pick -x" to reference the original commits

**Comment by kamoltat** [comment]
> could you please use "git cherry-pick -x" to reference the original commits

Hi Neha, so I did use "git cherry-pick-x"  for all the commits except the last commit 5de899b since that was changing some code to deal with merge conflicts

**Review by jdurgin — APPROVED** [review]

**Comment by smithfarm** [comment]
@kamoltat Could you tell me which master PRs you are backporting here?

If you used `git cherry-pick -x` to create the commits, I don't understand why the commit messages are edited?

I guess this is your first backport... the Ceph project has so many backports, that if we allowed each backporter to prepare backporters in his/her own way, chaos would be the result.

Over years of backporting, we have developed a set of practices (we call them "cherry-picking rules"). These rules are relatively simple, but they do need to be followed to avoid the chaos. Please take a look:

https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst#cherry-picking-rules

Now, this particular backport appears to be cherry-picking commits from several PRs. Could you tell us the PR numbers? For example, I guess one of them must be https://github.com/ceph/ceph/pull/28368

**Comment by yuriw** [comment]
[wip-yuri7-testing-2020-10-26-0802-nautilus](https://trello.com/c/aTkrbBpe/1046-wip-yuri7-testing-2020-10-26-0802-nautilus)

**Comment by kamoltat** [comment]
>  [wip-yuri7-testing-2020-10-26-0802-nautilus](https://trello.com/c/aTkrbBpe/1046-wip-yuri7-testing-2020-10-26-0802-nautilus)

@yuriw I can't access the trello board. Is there a way to invite me to the board? Thank you

**Comment by kamoltat** [comment]
> @kamoltat Could you tell me which master PRs you are backporting here?
> 
> If you used `git cherry-pick -x` to create the commits, I don't understand why the commit messages are edited?
> 
> I guess this is your first backport... the Ceph project has so many backports, that if we allowed each backporter to prepare backporters in his/her own way, chaos would be the result.
> 
> Over years of backporting, we have developed a set of practices (we call them "cherry-picking rules"). These rules are relatively simple, but they do need to be followed to avoid the chaos. Please take a look:
> 
> https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst#cherry-picking-rules
> 
> Now, this particular backport appears to be cherry-picking commits from several PRs. Could you tell us the PR numbers? For example, I guess one of them must be #28368

@smithfarm 

#28368
	db4596e
	c612f71
	9bf5bbf
#28498
	fa18a71
	29cb104
	36af6ed
#28695
	a7c9a3a

**Comment by smithfarm** [comment]
@kamoltat Thanks! I added that information to the PR description.

**Comment by ideepika** [comment]
@neha-ojha @kamoltat saw a failure related to progess module in teuthology tests, I suspect it might be something related, can you verify: 
```
http://qa-proxy.ceph.com/teuthology/yuriw-2020-11-10_16:01:13-rados-wip-yuri7-testing-2020-11-09-0731-nautilus-distro-basic-smithi/5609289/teuthology.log
conn(0x7f42b40227d0 0x7f42b4024cd0 unknown :-1 s=CLOSED pgs=48 cs=0 l=1 rev1=1 rx=0 tx=0).stop
2020-11-10T23:57:01.390 INFO:teuthology.orchestra.run.smithi014.stderr:2020-11-10 23:57:01.392 7f42d6cfb700  1 --2- 172.21.15.14:0/1914796073 >> [v2:172.21.15.14:3301/0,v1:172.21.15.14:6790/0] conn(0x7f42d018d360 0x7f42d018b580 unknown :-1 s=CLOSED pgs=0 cs=0 l=1 rev1=1 rx=0 tx=0).stop
2020-11-10T23:57:01.390 INFO:teuthology.orchestra.run.smithi014.stderr:2020-11-10 23:57:01.392 7f42d6cfb700  1 -- 172.21.15.14:0/1914796073 >> 172.21.15.14:0/1914796073 conn(0x7f42d01981b0 msgr2=0x7f42d0180540 unknown :-1 s=STATE_NONE l=0).mark_down
2020-11-10T23:57:01.390 INFO:teuthology.orchestra.run.smithi014.stderr:2020-11-10 23:57:01.392 7f42d6cfb700  1 -- 172.21.15.14:0/1914796073 shutdown_connections
2020-11-10T23:57:01.390 INFO:teuthology.orchestra.run.smithi014.stderr:2020-11-10 23:57:01.392 7f42d6cfb700  1 -- 172.21.15.14:0/1914796073 wait complete.
2020-11-10T23:57:01.402 INFO:tasks.cephfs_test_runner:test_osd_came_back (tasks.mgr.test_progress.TestProgress) ... FAIL
2020-11-10T23:57:01.402 INFO:tasks.cephfs_test_runner:
2020-11-10T23:57:01.403 INFO:tasks.cephfs_test_runner:======================================================================
2020-11-10T23:57:01.403 INFO:tasks.cephfs_test_runner:FAIL: test_osd_came_back (tasks.mgr.test_progress.TestProgress)
2020-11-10T23:57:01.403 INFO:tasks.cephfs_test_runner:----------------------------------------------------------------------
2020-11-10T23:57:01.403 INFO:tasks.cephfs_test_runner:Traceback (most recent call last):
2020-11-10T23:57:01.403 INFO:tasks.cephfs_test_runner:  File "/home/teuthworker/src/github.com_ceph_ceph-c_wip-yuri7-testing-2020-11-09-0731-nautilus/qa/tasks/mgr/test_progress.py", line 178, in test_osd_came_back
2020-11-10T23:57:01.404 INFO:tasks.cephfs_test_runner:    self.assertTrue(self._is_quiet())
2020-11-10T23:57:01.404 INFO:tasks.cephfs_test_runner:AssertionError: False is not true
2020-11-10T23:57:01.404 INFO:tasks.cephfs_test_runner:
2020-11-10T23:57:01.404 INFO:tasks.cephfs_test_runner:----------------------------------------------------------------------
2020-11-10T23:57:01.404 INFO:tasks.cephfs_test_runner:Ran 1 test in 68.711s
2020-11-10T23:57:01.405 INFO:tasks.cephfs_test_runner:
2020-11-10T23:57:01.405 INFO:tasks.cephfs_test_runner:FAILED (failures=1)
2020-11-10T23:57:01.405 INFO:tasks.cephfs_test_runner:
2020-11-10T23:57:01.405 INFO:tasks.cephfs_test_runner:======================================================================
2020-11-10T23:57:01.405 INFO:tasks.cephfs_test_runner:FAIL: test_osd_came_back (tasks.mgr.test_progress.TestProgress)
2020-11-10T23:57:01.406 INFO:tasks.cephfs_test_runner:----------------------------------------------------------------------
2020-11-10T23:57:01.406 INFO:tasks.cephfs_test_runner:Traceback (most recent call last):
2020-11-10T23:57:01.406 INFO:tasks.cephfs_test_runner:  File "/home/teuthworker/src/github.com_ceph_ceph-c_wip-yuri7-testing-2020-11-09-0731-nautilus/qa/tasks/mgr/test_progress.py", line 178, in test_osd_came_back
2020-11-10T23:57:01.406 INFO:tasks.cephfs_test_runner:    self.assertTrue(self._is_quiet())
2020-11-10T23:57:01.406 INFO:tasks.cephfs_test_runner:AssertionError: False is not true
2020-11-10T23:57:01.407 INFO:tasks.cephfs_test_runner:
2020-11-10T23:57:01.407 ERROR:teuthology.run_tasks:Saw exception from tasks.
Traceback (most recent call last):
  File "/home/teuthworker/src/git.ceph.com_git_teuthology_master/teuthology/run_tasks.py", line 93, in run_tasks
    manager.__enter__()
  File "/usr/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/home/teuthworker/src/github.com_ceph_ceph-c_wip-yuri7-testing-2020-11-09-0731-nautilus/qa/tasks/cephfs_test_runner.py", line 207, in task
    raise RuntimeError("Test failure: {0}".format(", ".join(bad_tests)))
```
http://qa-proxy.ceph.com/teuthology/yuriw-2020-11-10_16:01:13-rados-wip-yuri7-testing-2020-11-09-0731-nautilus-distro-basic-smithi/5609289/teuthology.log

**Comment by kamoltat** [comment]
@ideepika Yes you're right, will investigate that right away. Thank you!

**Comment by ideepika** [comment]
> @ideepika Yes you're right, will investigate that right away. Thank you!

no worries, I think reruning this batch with teuthology-suite, to test your fix might help: 
http://pulpito.front.sepia.ceph.com/yuriw-2020-11-11_20:55:56-rados-wip-yuri7-testing-2020-11-09-0731-nautilus-distro-basic-smithi/

**Comment by kamoltat** [comment]
@yuriw rerunning your test: 
https://pulpito.ceph.com/ksirivad-2020-11-17_06:41:24-rados-wip-ksirivad-nautilus-backports-distro-basic-smithi/

**Comment by kamoltat** [comment]
jenkins make check

**Comment by kamoltat** [comment]
jenkins test make check

**Comment by kamoltat** [comment]
jenkins retest this please

**Comment by ideepika** [comment]
> @yuriw Seems like the extra cherry-pick commit fixed it, let me know if I need to run more tests
> https://pulpito.ceph.com/ksirivad-2020-11-17_08:56:00-rados-wip-ksirivad-nautilus-backports-distro-basic-smithi/

This looks good! thanks @kamoltat !

**Comment by kamoltat** [comment]
@yuriw @neha-ojha this PR looks good to me, let me know if I need to run any more tests or do anything further

**Review by neha-ojha — COMMENTED** [review]
- 362cc3aaf29c3a016ca474beaaf81387b4c78f70 and d9b324e5235cf7a8873af92fb66bac7c22418d06 don't follow https://github.com/ceph/ceph/blob/master/SubmittingPatches.rst#commit-title

- if you need to add any commits specific to nautilus, please  add an explanation in the commit description

- do any of these commits need to land in octopus? can you please share corresponding tracker issues

**Comment by kamoltat** [comment]
@neha-ojha done! and none of the commits needed to land on octopus since it already has all these commits in it.

**Comment by yuriw** [comment]
[wip-yuri-testing-2020-12-01-0809-nautilus](https://trello.com/c/jfVBzhvW/1075-wip-yuri-testing-2020-12-01-0809-nautilus)

**Comment by ideepika** [comment]
@kamoltat seeing https://tracker.ceph.com/issues/48217 in teuthology job: 
http://qa-proxy.ceph.com/teuthology/yuriw-2020-12-02_16:10:23-rados-wip-yuri-testing-2020-12-01-0809-nautilus-distro-basic-smithi/5675715/teuthology.log

do we need 52fe9dbdae87b65a99a6c3bac3519c9528f22ea2 as well?

**Comment by kamoltat** [comment]
@ideepika you are right, good catch, thank you so much!

**Comment by smithfarm** [comment]
It looks like 52fe9dbdae87b65a99a6c3bac3519c9528f22ea2 might be needed in octopus as well?

**Comment by kamoltat** [comment]
> It looks like [52fe9db](https://github.com/ceph/ceph/commit/52fe9dbdae87b65a99a6c3bac3519c9528f22ea2) might be needed in octopus as well?

@smithfarm Yes I think you are right

**Comment by yuriw** [comment]
[wip-yuri6-testing-2020-12-14-0835-nautilus](https://trello.com/c/V64V4YDT/1085-wip-yuri6-testing-2020-12-14-0835-nautilus)

**Comment by ideepika** [comment]
@kamoltat can you take a look into this issue: https://tracker.ceph.com/issues/48824

**Pull request merged**
