### PR TITLE
rbd-mirror: make RemoveImmediateUpdate test synchronous

### PR DESCRIPTION
**Pull request by MrFreezeex**
Try fixing sporadic failure in RemoveImmediateUpdate by removing
asynchronous from the test.

Fixes: https://tracker.ceph.com/issues/53375
Signed-off-by: Arthur Outhenin-Chalandre <arthur.outhenin-chalandre@cern.ch>

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [x] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests
- Teuthology
  - [ ] Completed teuthology run
  - [x] No teuthology test necessary (e.g., documentation)

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by MrFreezeex** [comment]
Hopefully this make the trick... i wasn't able to reproduce it on my end so I can't say for sure :/.

**Comment by ideepika** [comment]
> LGTM though it would be nice to reproduce the issue somehow and make sure this is the correct fix.
> 
> @ideepika may be you will have a luck?
> 
> Just thinking, may be adding some sleep in the code may help to reproduce this...

will try that thanks @trociny @MrFreezeex

**Comment by ideepika** [comment]
jenkins test make check

**Comment by ideepika** [comment]
feel free to test with jenkins command, I see every 5-7th task failing with rbd-unit test https://jenkins.ceph.com/job/ceph-pull-requests/

**Comment by ideepika** [comment]
jenkins make check

**Comment by ideepika** [comment]
jenkins test make check

**Comment by ideepika** [comment]
jenkins test make check

**Comment by ideepika** [comment]
jenkins test make check

**Comment by trociny** [comment]
jenkins test make check

**Comment by trociny** [comment]
@ideepika Ah, it seems you were referring to librbd unittest hangs for `TestLibRBD.ConcurentOperations`, which I was able to reproduce with the last jenkins run [1].

This PR fixes a hang in rbd mirror unit tests, and is not related. We need a separate tracker ticket for  `TestLibRBD.ConcurentOperations` failure if we don't have yet.

[1] https://jenkins.ceph.com/job/ceph-pull-requests/86178/console

**Comment by trociny** [comment]
jenkins test make check

**Comment by trociny** [comment]
In the tracker I found `TestLibRBD.ConcurentOperations` mentioned here [1]. Though this ticket seems to be rather a mix of non-related librbd unit test failures.

[1] https://tracker.ceph.com/issues/47596#note-3

**Comment by ideepika** [comment]
jenkins test make check

**Comment by ideepika** [comment]
> > In the tracker I found `TestLibRBD.ConcurentOperations` mentioned here [1]. Though this ticket seems to be rather a mix of non-related librbd unit test failures.
> > [1] https://tracker.ceph.com/issues/47596#note-3
> 
> did not see this failure explictly, in any of the failing runs, no failed test, only timeout.

seeing this one locally: https://tracker.ceph.com/issues/43274#note-6 I agree, it's a mix bag

**Pull request merged**
