### PR TITLE
qa: export DIFF_LENGTH env parameter to print the full git diff

### PR DESCRIPTION
**Pull request by lxbsz**
From the xfstests-dev's README doc set DIFF_LENGTH to 0 will print
the full diff instead of the default 10.

This will be very helpful to debug the test failures, or we will
lose many valuable debug infomation.

Signed-off-by: Xiubo Li <xiubli@redhat.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by lxbsz** [comment]
Locally the test passed, while not in the [qa lab](http://qa-proxy.ceph.com/teuthology/xiubli-2023-02-21_08:56:46-fs:fscrypt-wip-fscrypt-20230216-1802-distro-default-smithi/7182583/teuthology.log), I will debug it further:

```
2023-02-21T09:33:51.693 DEBUG:teuthology.orchestra.run.smithi111:running tests for dummy_encryption from xfstests-dev> (cd /tmp/tmp.8pLTA97eTOxfstests-dev && exec 'evn DIFF_LENGTH=0 sudo ./check generic/317')
2023-02-21T09:33:51.798 INFO:teuthology.orchestra.run.smithi111.stderr:bash: /tmp/tmp.8pLTA97eTOxfstests-dev/evn DIFF_LENGTH=0 sudo ./check generic/317: No such file or directory
2023-02-21T09:33:51.800 DEBUG:teuthology.orchestra.run:got remote process result: 127
```

**Comment by lxbsz** [comment]
The `env` works and the test passed.

**Comment by lxbsz** [comment]
Both the relevant [qa acls tests](https://pulpito.ceph.com/xiubli-2023-02-21_23:56:45-fs:functional-wip-fscrypt-20230215-0834-distro-default-smithi/) and [qa fscrypt tests](https://pulpito.ceph.com/xiubli-2023-02-21_13:59:34-fs:fscrypt-wip-fscrypt-20230216-1802-distro-default-smithi) passed.

**Comment by dparmar18** [comment]
> Locally the test passed, while not in the [qa lab](http://qa-proxy.ceph.com/teuthology/xiubli-2023-02-21_08:56:46-fs:fscrypt-wip-fscrypt-20230216-1802-distro-default-smithi/7182583/teuthology.log), I will debug it further:
> 
> ```
> 2023-02-21T09:33:51.693 DEBUG:teuthology.orchestra.run.smithi111:running tests for dummy_encryption from xfstests-dev> (cd /tmp/tmp.8pLTA97eTOxfstests-dev && exec 'evn DIFF_LENGTH=0 sudo ./check generic/317')
> 2023-02-21T09:33:51.798 INFO:teuthology.orchestra.run.smithi111.stderr:bash: /tmp/tmp.8pLTA97eTOxfstests-dev/evn DIFF_LENGTH=0 sudo ./check generic/317: No such file or directory
> 2023-02-21T09:33:51.800 DEBUG:teuthology.orchestra.run:got remote process result: 127
> ```

What was the reason for this failure? Infra issue?

**Comment by lxbsz** [comment]
> > Locally the test passed, while not in the [qa lab](http://qa-proxy.ceph.com/teuthology/xiubli-2023-02-21_08:56:46-fs:fscrypt-wip-fscrypt-20230216-1802-distro-default-smithi/7182583/teuthology.log), I will debug it further:
> > ```
> > 2023-02-21T09:33:51.693 DEBUG:teuthology.orchestra.run.smithi111:running tests for dummy_encryption from xfstests-dev> (cd /tmp/tmp.8pLTA97eTOxfstests-dev && exec 'evn DIFF_LENGTH=0 sudo ./check generic/317')
> > 2023-02-21T09:33:51.798 INFO:teuthology.orchestra.run.smithi111.stderr:bash: /tmp/tmp.8pLTA97eTOxfstests-dev/evn DIFF_LENGTH=0 sudo ./check generic/317: No such file or directory
> > 2023-02-21T09:33:51.800 DEBUG:teuthology.orchestra.run:got remote process result: 127
> > ```
> 
> What was the reason for this failure? Infra issue?

There is one typo, which is `evn`. And the `exec` usage is incorrect:

`exec 'cmd ...'`

The correct way should be:

`ecec cmd ...`

There shouldn't include any `'`.

**Comment by lxbsz** [comment]
With this fix we can see the full git diff for failure test case:

```
FSTYP         -- ceph
PLATFORM      -- Linux/x86_64 smithi190 6.2.0-rc7-ceph-gd9ba97321a89 #1 SMP PREEMPT_DYNAMIC Tue Feb 14 13:33:35 UTC 2023
MKFS_OPTIONS  -- 172.21.15.26:6789:/scratch
MOUNT_OPTIONS -- -o name=admin,secret=AQCtoPVjzadMJBAAEt/mJ0jEsP2dGBGgnth1cQ==,test_dummy_encryption -o context=system_u:object_r:root_t:s0 172.21.15.26:6789:/scratch /tmp/tmp.UQSNqoEhOWscratch

generic/317       - output mismatch (see /tmp/tmp.L1dYhg07Eyxfstests-dev/results//generic/317.out.bad)
    --- tests/generic/317.out	2023-02-22 04:59:08.905078789 +0000
    +++ /tmp/tmp.L1dYhg07Eyxfstests-dev/results//generic/317.out.bad	2023-02-22 05:04:33.846088157 +0000
    @@ -4,9 +4,7 @@
       Size: 0            Filetype: Regular File
       Mode: (0644/-rw-r--r--)         Uid: (qa_user)  Gid: (qa_user)
     From user_ns
    -  File: "$SCRATCH_MNT/file1"
    -  Size: 0            Filetype: Regular File
    -  Mode: (0644/-rw-r--r--)         Uid: (0)  Gid: (0)
    +execvp: Permission denied
     
     *** Remounting ***
     
    @@ -15,6 +13,4 @@
       Size: 0            Filetype: Regular File
       Mode: (0644/-rw-r--r--)         Uid: (qa_user)  Gid: (qa_user)
     From user_ns
    -  File: "$SCRATCH_MNT/file1"
    -  Size: 0            Filetype: Regular File
    -  Mode: (0644/-rw-r--r--)         Uid: (0)  Gid: (0)
    +execvp: Permission denied
Ran: generic/317
Failures: generic/317
Failed 1 of 1 tests
```

While without this it will be:

```
FSTYP         -- ceph
PLATFORM      -- Linux/x86_64 smithi174 6.2.0-rc7-ceph-gd9ba97321a89 #1 SMP PREEMPT_DYNAMIC Tue Feb 14 13:33:35 UTC 2023
MKFS_OPTIONS  -- 172.21.15.46:6789:/scratch
MOUNT_OPTIONS -- -o name=admin,secret=AQCMmfVjN+yuMRAAecyeGODiJkNuenmJ4vbLkg==,test_dummy_encryption -o context=system_u:object_r:root_t:s0 172.21.15.46:6789:/scratch /tmp/tmp.C68Mp70KSBscratch

generic/317       - output mismatch (see /tmp/tmp.wcwwQUp4P8xfstests-dev/results//generic/317.out.bad)
    --- tests/generic/317.out	2023-02-22 04:28:46.723214112 +0000
    +++ /tmp/tmp.wcwwQUp4P8xfstests-dev/results//generic/317.out.bad	2023-02-22 04:34:12.454854035 +0000
    @@ -4,9 +4,7 @@
       Size: 0            Filetype: Regular File
       Mode: (0644/-rw-r--r--)         Uid: (qa_user)  Gid: (qa_user)
     From user_ns
    -  File: "$SCRATCH_MNT/file1"
    -  Size: 0            Filetype: Regular File
    -  Mode: (0644/-rw-r--r--)         Uid: (0)  Gid: (0)
    +execvp: Permission denied
    ...
    (Run 'diff -u /tmp/tmp.wcwwQUp4P8xfstests-dev/tests/generic/317.out /tmp/tmp.wcwwQUp4P8xfstests-dev/results//generic/317.out.bad'  to see the entire diff)
Ran: generic/317
Failures: generic/317
Failed 1 of 1 tests
```
And we will lose a lot of debug logs.

**Review by dparmar18 — APPROVED** [review]
LGTM

**Comment by lxbsz** [comment]
Rebased and resolved conflicts.

**Comment by lxbsz** [comment]
Both the relevant [qa acls tests](https://pulpito.ceph.com/xiubli-2023-02-22_06:18:23-fs:functional-wip-fscrypt-20230215-0834-distro-default-smithi/) and [qa fscrypt tests](https://pulpito.ceph.com/xiubli-2023-02-22_06:18:07-fs:fscrypt-wip-fscrypt-20230215-0834-distro-default-smithi/) passed.

**Comment by lxbsz** [comment]
jenkins test api

**Review by vshankar — APPROVED** [review]

**Comment by vshankar** [comment]
Nice debug improvement.

**Pull request merged**
