### PR TITLE
rgw: add zonegroup.api_name in /admin/bucket?zonegroup&bucket={bucketname}

### PR DESCRIPTION
**Pull request by joke-lee**
we may need  zonegroup info in some  case  
we have zonegroup zgp1 and zonegroup zgp2, bucket zgp1b4 is created with s3cmd --bucket-location=zgp1 and bucket zgp2b4 is created with s3cmd --bucket-location=zgp2

zgp1 endpoint 127.0.0.1:8001
zgp2 endpoint 127.0.0.1:8002

[root@localhost build]# ceph-request get "/admin/bucket?zonegroup&bucket=zgp2b4" -c admin.request
{"zonegroup":"zgp2"}
[root@localhost build]# ceph-request get "/admin/bucket?zonegroup&bucket=zgp1b4" -c admin.request
{"zonegroup":"zgp1"}
```

Signed-off-by: yuliyang <yuliyang@cmss.chinamobile.com>

### CODE REVIEW

**Comment by cbodley** [comment]
hi @joke-lee, the `bucket-instance` metadata api already exposes a `zonegroup` field, is that not sufficient?

i really don't like how this change breaks the abstraction between `RGWMetadataManager` and `RGWBucket[Instance]MetadataHandler`

**Comment by joke-lee** [comment]
hi @cbodley , if we want to get zonegroup from the bucket-instance metadata api ,we had to get bucket instance at first, so we have to send 2 requests, it is  low efficiency.

**Comment by cbodley** [comment]
> hi @cbodley , if we want to get zonegroup from the bucket-instance metadata api ,we had to get bucket instance at first, so we have to send 2 requests, it is low efficiency.

but it also adds some overhead to the normal `bucket` requests to add information that won't be used by metadata sync

**Comment by joke-lee** [comment]
@cbodley or maybe we can add rest api like 
```
/admin/metadata/zonegroup?bucket=test1
```
to achieve this. any better suggestion?

**Comment by cbodley** [comment]
hi @joke-lee, is this not the same thing that the `RGWGetBucketLocation` op does?

**Comment by joke-lee** [comment]
through the admin rest api,we can get the location of any bucket while RGWGetBucketLocation can get only  buckets owned by user. in some case, is usefull, for example,   i have a openresty server and use lua to query bucket location through admin api and then pass_by to cluster own the bucket, like
```
location / {
            set $backend  '';
            rewrite_by_lua_file  /usr/local/openresty/nginx/conf/lua/router.lua;
            proxy_pass http://$backend;
        }

router.lua will query master zonegroup where the bucket located and set the backend to that cluster

local function get_endpoint(zonegroup)
  if zonegroup == "zgp1" then
   ngx.var.backend = ngx.var.host .. ":8001"   -- the 8001 rgw instance's rgw_zonegroup is zgp1
  end
  if zonegroup == "zgp2" then
    ngx.var.backend = ngx.var.host .. ":8002"  -- the 8002 rgw instance's rgw_zonegroup is zgp2
  end
end

```

**Comment by cbodley** [comment]
hi @joke-lee, i see `RGWOp_Bucket_Info` in `rgw_rest_bucket.cc` that serves bucket info (including zonegroup) at `admin/bucket`. does that work?

**Comment by joke-lee** [comment]
yes ,it can get zonegroup id. close this
```
ceph-request get "/admin/bucket?format=json&bucket=zgp2b2" -c admin.request.8001 --verbose
< GET /admin/bucket?format=json&bucket=zgp2b2 HTTP/1.1
< Host: 127.0.0.1:8001
< Connection: keep-alive
< Accept-Encoding: gzip, deflate
< Accept: */*
< User-Agent: python-requests/2.18.4
< date: Sat, 21 Jul 2018 23:43:59 GMT
< Authorization: AWS adminak:HpjZ71YqMFQK33OpW4tjcpxJwBM=
<

> HTTP/1.1 200 OK
> x-amz-request-id: tx0000000000000000000ab-005b53c53f-232f8-zgp1-z1
> Content-Length: 526
> Date: Sat, 21 Jul 2018 23:43:59 GMT
> Connection: Keep-Alive
>
{"bucket":"zgp2b2","zonegroup":"60355b00-1920-4164-b2a5-feb05c74b886","placement_rule":"default-placement","explicit_placement":{"data_pool":"","data_extra_pool":"","index_pool":""},"id":"78b728c6-33c3-4faf-add9-18687d479741.144120.2","marker":"78b728c6-33c3-4faf-add9-18687d479741.144120.2","index_type":"Normal","owner":"yly","ver":"0#1","master_ver":"0#0","mtime":"2018-07-22 07:42:25.310148","max_marker":"0#","usage":{},"bucket_quota":{"enabled":false,"check_on_raw":false,"max_size":-1,"max_size_kb":0,"max_objects":-1}}
```

**Pull request closed without merging**
