### PR TITLE
mgr/cephadm: make j2 teamplates overwritable

### PR DESCRIPTION
**Pull request by sebastian-philipp**
This adds an escape hatch, if the configs generated
by cephadm are not flexible enough.

Downside is obviously that future upgrades might
break the daemons. Use at your own risk.

Signed-off-by: Sebastian Wagner <sebastian.wagner@suse.com>

Fixes: https://tracker.ceph.com/issues/47335

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by sebastian-philipp** [comment]
green: https://pulpito.ceph.com/swagner-2020-09-11_17:54:34-rados:cephadm-wip-swagner-testing-2020-09-11-1625-distro-basic-smithi/

**Review by p-se — APPROVED** [review]
Looks good to me, thank you!

**Comment by jschmid1** [comment]
Fixes: https://tracker.ceph.com/issues/47335
should be in the commit message

**Review by bk201 — APPROVED** [review]
Would it be better to add a prefix to the key names?
To overwrite template `services/foo/bar.j2`, currently it expects a store named `mgr/cephadm/services_foo_bar`. How about prefixing it to `mgr/cephadm/custom_templates/services_foo_bar` to avoid unexpected name conflict?

**Comment by mgfritch** [comment]
Green:
https://pulpito.ceph.com/mgfritch-2020-09-21_20:24:35-rados:cephadm-wip-mgfritch-testing-2020-09-21-1034-distro-basic-smithi/

Failure:
https://tracker.ceph.com/issues/47591

**Comment by sebastian-philipp** [comment]
> Green:
> https://pulpito.ceph.com/mgfritch-2020-09-21_20:24:35-rados:cephadm-wip-mgfritch-testing-2020-09-21-1034-distro-basic-smithi/
> 
> Failure:
> https://tracker.ceph.com/issues/47591

I think it's unrelated

**Pull request merged**
