### PR TITLE
rgw: fix a typo in rgw_perms[]

### PR DESCRIPTION
**Pull request by luomuyao**
Signed-off-by: luomuyao <luo.muyao@zte.com.cn>

### CODE REVIEW

**Comment by cbodley** [comment]
wow thanks @luomuyao, that looks like an obvious mistake! would you be willing to add a test case to https://github.com/ceph/s3-tests that covers this? if you haven't used s3-tests, there's a `qa/workunits/rgw/run-s3tests.sh` that can help you get started

**Comment by luomuyao** [comment]
@cbodley  I'm sorry about my late reply. I've been busy preparing for my wedding recently and back to work today. I'd be happy to write the test cases, But i can't find any document in https://github.com/ceph/s3-tests about how to write an useful test cases. Can you give me more information to help me write it faster? Thanks in advance!

**Comment by cbodley** [comment]
hi @luomuyao, in general it just means adding a test function to `s3tests/function/test_s3.py` that uses the boto2 client. you can see a good example [commit here](https://github.com/ceph/s3-tests/commit/9506ac220f3de25608fe768574c5eb2d5b5eb142)

but looking closer at this `rgw_perms[]` variable, it's only being used for `rgw_perm_to_str()` when we display a `RGWUserInfo`, and we're only doing that in `radosgw-admin` and the `/admin` rest api. no s3 operations would notice a difference here, so i don't think it's necessary to add a test after all

however, i also found that `rgw_perms[]` is duplicated in rgw_json_enc.cc for `perm_to_str()`. could you please fix that one too?

**Comment by luomuyao** [comment]
@cbodley  Thanks for your tips, and i have fix it, please have a look again!

**Comment by yuriw** [comment]
[wip-yuri2-testing-2018-02-14-2134](https://trello.com/c/9ZVL9Aqx/263-wip-yuri2-testing-2018-02-14-2134)

**Pull request merged**
