### PR TITLE
[DO NOT MERGE] mds: derive wrlocks from excl caps

### PR DESCRIPTION
**Pull request by ukernel**
Fixes: http://tracker.ceph.com/issues/39354
Signed-off-by: "Yan, Zheng" <zyan@redhat.com>

- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by ukernel** [comment]
The code does not handle dir/subtree freeze properly.  unstable lock prevents dir/subtree from becoming frozen. caps hold by client prevent unstable lock from becoming stable.  needs to update the 'defer request 
logical' for freezing dir/subtree .

**Comment by sebastian-philipp** [comment]
There is a new feature of GitHub called "[Draft Pull Request](https://github.blog/2019-02-14-introducing-draft-pull-requests/)".

**Comment by gregsfortytwo** [comment]
Can we start adding *more* documentation as we update the caps and locking, instead of making them more complicated with a single-sentence description in both the tracker and commit?

I see this is for handling unlinks (presumably so we can do async unlinks eventually), but some explanation of how the out-of-order stuff interacts with other invariants would be valuable. Is there e plan for dealing with freezing and the lock transitions?

**Comment by jtlayton** [comment]
@gregsfortytwo : Absolutely. This really, really needs some extensive comments and documentation. So much of the "rules" of cephfs are enshrined in this file, and this patch will make some big changes. Let's ensure that we document how all of this is supposed to work. Client implementers need this.

**Comment by jtlayton** [comment]
I spent some time testing against a server with this patchset today along with my full async unlink kernel series on the client. I have occasionally hit some sort of condition where an rmdir request gets stuck. Those are synchronous and it looked like the mds had considered the client to be unresponsive and blacklisted it -- it may be trying to recall caps, but I'm not sure which ones yet.

I tried ramping up the debug logging in the mds, but when I did I couldn't get it to reproduce. I'll keep playing with it though.

**Comment by ukernel** [comment]
I fixed a bug, please try again

**Comment by jtlayton** [comment]
Thanks, @ukernel.

I reworked my patch to not require Lx caps (and to just return Ls, as we do for a synchronous unlink).

It seemed to do the right thing, so I then tried running xfstests on that setup and it crashed:

```
2019-04-22 14:41:57.756 7fb66144d700 -1 *** Caught signal (Segmentation fault) **
 in thread 7fb66144d700 thread_name:ms_dispatch                                 
                                                                                
 ceph version 15.0.0-556-g895a80974b43 (895a80974b434263e14e68de163f99a356f7d0ed) octopus (dev)
 1: (()+0x13070) [0x7fb665dab070]                                               
 2: (Locker::_drop_locks(MutationImpl*, std::set<CInode*, std::less<CInode*>, std::allocator<CInode*> >*, bool)+0x171) [0x558441af3b11]
 3: (Locker::acquire_locks(boost::intrusive_ptr<MDRequestImpl>&, MutationImpl::LockOpVec&, CInode*, bool)+0x2d13) [0x558441af8f93]
 4: (Server::handle_client_rename(boost::intrusive_ptr<MDRequestImpl>&)+0x1d81) [0x5584419dba81]
 5: (Server::dispatch_client_request(boost::intrusive_ptr<MDRequestImpl>&)+0xb7b) [0x5584419e952b]
 6: (MDCache::dispatch_request(boost::intrusive_ptr<MDRequestImpl>&)+0x2f) [0x558441a75a8f]
 7: (MDSContext::complete(int)+0x7f) [0x558441be29df]                           
 8: (MDSCacheObject::finish_waiting(unsigned long, int)+0x29e) [0x558441bfb6ae] 
 9: (SimpleLock::finish_waiters(unsigned long, int)+0xb8) [0x558441aff128]      
 10: (Locker::derive_wrlock_from_excl_cap(boost::intrusive_ptr<MDRequestImpl>&, SimpleLock*)+0x244) [0x558441adfc34]
 11: (Server::handle_client_unlink(boost::intrusive_ptr<MDRequestImpl>&)+0xa85) [0x5584419d4b15]
 12: (Server::dispatch_client_request(boost::intrusive_ptr<MDRequestImpl>&)+0xb0b) [0x5584419e94bb]
 13: (Server::handle_client_request(boost::intrusive_ptr<MClientRequest const> const&)+0x308) [0x5584419e99a8]
 14: (Server::dispatch(boost::intrusive_ptr<Message const> const&)+0x122) [0x5584419f52c2]
 15: (MDSRank::handle_deferrable_message(boost::intrusive_ptr<Message const> const&)+0x6ec) [0x558441969d1c]
 16: (MDSRank::_dispatch(boost::intrusive_ptr<Message const> const&, bool)+0x79b) [0x55844196c15b]
 17: (MDSRankDispatcher::ms_dispatch(boost::intrusive_ptr<Message const> const&)+0x40) [0x55844196c780]
 18: (MDSDaemon::ms_dispatch2(boost::intrusive_ptr<Message> const&)+0x108) [0x55844195aa18]
 19: (DispatchQueue::entry()+0x16b9) [0x7fb666986379]                           
 20: (DispatchQueue::DispatchThread::entry()+0xd) [0x7fb666a1a8bd]              
 21: (()+0x858e) [0x7fb665da058e]                                               
 22: (clone()+0x43) [0x7fb665527683]                                            
```

**Comment by jtlayton** [comment]
Here's the gdb backtrace (with a bit more info):
```
#0  0x00007fb665daaf0f in raise () from /lib64/libpthread.so.0
#1  0x0000558441c67406 in reraise_fatal (signum=11) at /home/jlayton/git/ceph/src/global/signal_handler.cc:326
#2  handle_fatal_signal (signum=11) at /home/jlayton/git/ceph/src/global/signal_handler.cc:326
#3  <signal handler called>
#4  0x0000558441af3b11 in Locker::_drop_locks (this=0x558442e234a0, mut=0x5584462b7800, pneed_issue=0x7fb661449ea0, drop_rdlocks=true) at /home/jlayton/git/ceph/src/mds/Locker.cc:746
#5  0x0000558441af8f93 in Locker::acquire_locks (this=<optimized out>, mdr=..., lov=..., auth_pin_freeze=<optimized out>, auth_pin_nonblock=auth_pin_nonblock@entry=false) at /home/jlayton/git/ceph/src/mds/Locker.cc:625
#6  0x00005584419dba81 in Server::handle_client_rename (this=0x558443aba120, mdr=...) at /home/jlayton/git/ceph/src/mds/Server.cc:7569
#7  0x00005584419e952b in Server::dispatch_client_request (this=0x558443aba120, mdr=...) at /home/jlayton/git/ceph/src/mds/Server.cc:2370
#8  0x0000558441a75a8f in MDCache::dispatch_request (this=<optimized out>, mdr=...) at /home/jlayton/git/ceph/src/mds/MDCache.cc:9271
#9  0x0000558441be29df in Context::complete (r=0, this=0x55844531c460) at /home/jlayton/git/ceph/src/include/Context.h:77
#10 MDSContext::complete (this=0x55844531c460, r=0) at /home/jlayton/git/ceph/src/mds/MDSContext.cc:29
#11 0x0000558441bfb6ae in finish_contexts<std::vector<MDSContext*, std::allocator<MDSContext*> > > (result=0, finished=std::vector of length 0, capacity 0, cct=0x558442ee8000) at /home/jlayton/git/ceph/src/log/SubsystemMap.h:72
#12 MDSCacheObject::finish_waiting (this=<optimized out>, mask=<optimized out>, result=0) at /home/jlayton/git/ceph/src/mds/MDSCacheObject.cc:13
#13 0x0000558441aff128 in SimpleLock::finish_waiters (this=<optimized out>, mask=<optimized out>, r=<optimized out>) at /usr/include/c++/8/ext/new_allocator.h:79
#14 0x0000558441adfc34 in Locker::derive_wrlock_from_excl_cap (this=0x558442e234a0, mdr=..., lock=lock@entry=0x5584472d6ca8) at /home/jlayton/git/ceph/src/mds/Locker.cc:680
#15 0x00005584419d4b15 in Server::handle_client_unlink (this=0x558443aba120, mdr=...) at /home/jlayton/git/ceph/src/mds/Server.cc:6638
#16 0x00005584419e94bb in Server::dispatch_client_request (this=0x558443aba120, mdr=...) at /home/jlayton/git/ceph/src/mds/Server.cc:2367
#17 0x00005584419e99a8 in Server::handle_client_request (this=0x558443aba120, req=...) at /home/jlayton/git/ceph/src/mds/Server.cc:2222
#18 0x00005584419f52c2 in Server::dispatch (this=0x558443aba120, m=...) at /home/jlayton/git/ceph/src/common/RefCountedObj.h:172
#19 0x0000558441969d1c in MDSRank::handle_deferrable_message (this=0x558443b28000, m=...) at /home/jlayton/git/ceph/src/mds/MDSRank.cc:1185
#20 0x000055844196c15b in MDSRank::_dispatch (this=0x558443b28000, m=..., new_msg=<optimized out>) at /home/jlayton/git/ceph/src/mds/MDSRank.cc:1039
#21 0x000055844196c780 in MDSRankDispatcher::ms_dispatch (this=this@entry=0x558443b28000, m=...) at /home/jlayton/git/ceph/src/mds/MDSRank.cc:1021
#22 0x000055844195aa18 in MDSDaemon::ms_dispatch2 (this=0x558442e99200, m=...) at /home/jlayton/git/ceph/src/common/RefCountedObj.h:172
#23 0x00007fb666986379 in Messenger::ms_deliver_dispatch (m=..., this=0x558442e98900) at /home/jlayton/git/ceph/src/msg/DispatchQueue.cc:198
#24 DispatchQueue::entry (this=0x558442e98c60) at /home/jlayton/git/ceph/src/msg/DispatchQueue.cc:197
#25 0x00007fb666a1a8bd in DispatchQueue::DispatchThread::entry (this=<optimized out>) at /home/jlayton/git/ceph/src/msg/DispatchQueue.h:102
#26 0x00007fb665da058e in start_thread () from /lib64/libpthread.so.0
#27 0x00007fb665527683 in clone () from /lib64/libc.so.6
```

**Comment by jtlayton** [comment]
A little bit more info:
```
(gdb) f 4
#4  0x000055b6ee714b11 in Locker::_drop_locks (this=0x55b6f06df4a0, mut=0x55b6f3b5c000, pneed_issue=0x7ff7b73faea0, drop_rdlocks=true)
    at /home/jlayton/git/ceph/src/mds/Locker.cc:746
warning: Source file is more recent than executable.
746	    MDSCacheObject *obj = lock->get_parent();
(gdb) p lock
$1 = (SimpleLock *) 0x109b
(gdb) p *lock
Cannot access memory at address 0x109b
(gdb) p it
$2 = {lock = 0x109b, flags = 4053081792, wrlock_target = 21942}
(gdb) p mut->locks
$6 = std::set with 0 elements
```
So looks like some sort of lock_set corruption? Perhaps it changed while we were iterating over it?

**Comment by jtlayton** [comment]
xfstests generic/013 (which does an fsstress run) really seems to fall over with this patchset. Right now, it's stuck, and I see this in the MDS log, repeating indefinitely every few seconds.

`2019-04-23 08:17:09.303 7f32a847d700  0 log_channel(cluster) log [WRN] : slow request 33.953507 seconds old, received at 2019-04-23 08:16:35.350177: client_request(client.4239:85192 rename #0x1000000eb76/d31 #0x1000000eb8d/d26 2019-04-23 08:16:35.346640 caller_uid=0, caller_gid=0{}) currently failed to xlock, waiting`

**Comment by ukernel** [comment]
was ceph-mds compiled from the newest code? I fixed a bug that can cause  'failed to xlock'

**Comment by jtlayton** [comment]
Built your latest branch and got a new crash today:
```
 ceph version 15.0.0-481-g74cef6ae4446 (74cef6ae4446a7276e3a872d123ef186b5c535e7) octopus (dev)
 1: (ceph::__ceph_assert_fail(char const*, char const*, int, char const*)+0x152) [0x7fdf170e7246]
 2: (()+0x27841e) [0x7fdf170e741e]
 3: (MDCache::predirty_journal_parents(boost::intrusive_ptr<MutationImpl>, EMetaBlob*, CInode*, CDir*, int, int, snapid_t)+0x226d) [0x55c4e4a27c6d]
 4: (Server::_link_local(boost::intrusive_ptr<MDRequestImpl>&, CDentry*, CInode*)+0x31a) [0x55c4e49c54aa]
 5: (Server::handle_client_link(boost::intrusive_ptr<MDRequestImpl>&)+0x500) [0x55c4e49c72d0]
 6: (Server::dispatch_client_request(boost::intrusive_ptr<MDRequestImpl>&)+0xa6b) [0x55c4e49e416b]
 7: (MDCache::dispatch_request(boost::intrusive_ptr<MDRequestImpl>&)+0x2f) [0x55c4e4a7104f]
 8: (MDSContext::complete(int)+0x7f) [0x55c4e4bdecaf]
 9: (MDSCacheObject::finish_waiting(unsigned long, int)+0x29e) [0x55c4e4bf797e]
 10: (SimpleLock::finish_waiters(unsigned long, int)+0xb8) [0x55c4e4afab68]
 11: (Locker::eval_gather(SimpleLock*, bool, bool*, std::vector<MDSContext*, std::allocator<MDSContext*> >*)+0x1228) [0x55c4e4ae6348]
 12: (Locker::xlock_finish(std::_Rb_tree_const_iterator<MutationImpl::LockOp> const&, MutationImpl*, bool*)+0x35e) [0x55c4e4aeef9e]
 13: (Locker::_drop_locks(MutationImpl*, std::set<CInode*, std::less<CInode*>, std::allocator<CInode*> >*, bool)+0x1fb) [0x55c4e4aef2cb]
 14: (Locker::drop_non_rdlocks(MutationImpl*, std::set<CInode*, std::less<CInode*>, std::allocator<CInode*> >*)+0x5a) [0x55c4e4aefa6a]
 15: (Server::reply_client_request(boost::intrusive_ptr<MDRequestImpl>&, boost::intrusive_ptr<MClientReply> const&)+0x494) [0x55c4e49aed14]
 16: (Server::respond_to_request(boost::intrusive_ptr<MDRequestImpl>&, int)+0x1c9) [0x55c4e49af619]
 17: (Server::_unlink_local_finish(boost::intrusive_ptr<MDRequestImpl>&, CDentry*, CDentry*, unsigned long)+0x35b) [0x55c4e49cb27b]
 18: (MDSContext::complete(int)+0x7f) [0x55c4e4bdecaf]
 19: (MDSIOContextBase::complete(int)+0x177) [0x55c4e4bdef37]
 20: (MDSLogContextBase::complete(int)+0x40) [0x55c4e4bdf170]
 21: (Finisher::finisher_thread_entry()+0x17f) [0x7fdf171629cf]
 22: (()+0x858e) [0x7fdf166d158e]
 23: (clone()+0x43) [0x7fdf15e58683]

     0> 2019-04-23 12:30:56.043 7fdf0bd72700 -1 *** Caught signal (Aborted) **
 in thread 7fdf0bd72700 thread_name:fn_anonymous
```

To reproduce this, I'm just running xfstests on a kernel with my patchset against @ukernel's MDS branch. Test generic/013 seems to trigger it. That test just seems to run a particular fsstress workload.

**Comment by jtlayton** [comment]
My async unlink branch is here, if anyone is interested in playing with it:

https://git.kernel.org/pub/scm/linux/kernel/git/jlayton/linux.git/log/?h=ceph-async-unlink

**Comment by jtlayton** [comment]
Also generic/013 seems to pass, and the MDS does not crash when I run this test with a kernel client that doesn't do async unlink (commit 915be74002). So maybe the MDS is relying on some sort of implicit synchronization that is no longer in play with an asynchronous unlink?

**Comment by ukernel** [comment]
the crash is fixed by 
````
diff --git a/src/mds/Locker.cc b/src/mds/Locker.cc
index 9b574dd2ae..855a4cb4f5 100644
--- a/src/mds/Locker.cc
+++ b/src/mds/Locker.cc
@@ -675,8 +675,12 @@ bool Locker::derive_wrlock_from_excl_cap(MDRequestRef& mdr, SimpleLock *lock)
       mdr->auth_pin(in);
 
       // wake up all waiters. they will drop locks when encountering the lock
-      if (!lock->is_stable())
-       lock->finish_waiters(SimpleLock::WAIT_STABLE|SimpleLock::WAIT_WR|SimpleLock::WAIT_RD|SimpleLock::WAIT_XLOCK);
+      if (!lock->is_stable()) {
+       MDSContext::vec finished;
+       lock->take_waiting(SimpleLock::WAIT_STABLE|SimpleLock::WAIT_WR|SimpleLock::WAIT_RD|SimpleLock::WAIT_XLOCK);
+       mds->queue_waiter_front(finished);
+      }
+
       return true;
     }
   }
````

**Comment by ukernel** [comment]
the 'stuck request' issue is related to remote linkage. running fsstress with '-f link=0' option can workaround it for now

**Comment by jtlayton** [comment]
> the 'stuck request' issue is related to remote linkage. running fsstress with '-f link=0' option can workaround it for now

I'm not sure about that. I ran the test again today -- the only outstanding mds call is an unlink. I got this in the MDS log:

```
2019-04-24 14:01:31.641 7f9867612700  0 log_channel(cluster) log [WRN] : slow request 241.473809 seconds old, received at 2019-04-24 13:57:30.169079: client_request(mds.0:48 rename #0x1/test/fsstress.6506.3/p2/dd/dcb/dc8/d9c/dbb/dbd/d6b/dd5/fda #0x100/stray9/10000009f3d caller_uid=0, caller_gid=0{}) currently failed to wrlock, waiting
2019-04-24 14:01:31.641 7f9867612700  0 log_channel(cluster) log [WRN] : slow request 241.473065 seconds old, received at 2019-04-24 13:57:30.169824: client_request(client.4224:87142 unlink #0x10000009f14/fda 2019-04-24 13:57:30.170465 caller_uid=0, caller_gid=0{}) currently dispatched
2019-04-24 14:01:31.642 7f9867612700  0 log_channel(cluster) log [WRN] : client.4224 isn't responding to mclientcaps(revoke), ino 0x10000009f14 pending pAsLsXs issued pAsLsXsFsx, sent 241.473812 seconds ago
```
In this case, `/mnt/test/fsstress.6506.3/p2/dd/dcb/dc8/d9c/dbb/dbd/d6b/dd5` is inode 0x10000009f14.

I think the MDS is renaming the inode into the strays directory in order to process the unlink and that is likely triggering a Fsx cap recall. The client won't return those caps until the unlink is done. So, deadlock.

**Comment by jtlayton** [comment]
That patch didn't quite build. I'm testing this one now:

```
diff --git a/src/mds/Locker.cc b/src/mds/Locker.cc
index c80e483981f7..ef4e55af6e43 100644
--- a/src/mds/Locker.cc
+++ b/src/mds/Locker.cc
@@ -676,8 +676,12 @@ bool Locker::derive_wrlock_from_excl_cap(MDRequestRef& mdr, SimpleLock *lock)
       mdr->auth_pin(in);
 
       // wake up all waiters. they will drop locks when encountering the lock
-      if (!lock->is_stable())
-       lock->finish_waiters(SimpleLock::WAIT_STABLE|SimpleLock::WAIT_WR|SimpleLock::WAIT_RD|SimpleLock::WAIT_XLOCK);
+      if (!lock->is_stable()) {
+        MDSContext::vec finished;
+        lock->take_waiting(SimpleLock::WAIT_STABLE|SimpleLock::WAIT_WR|SimpleLock::WAIT_RD|SimpleLock::WAIT_XLOCK, finished);
+        mds->queue_waiters_front(finished);
+      }
+
       return true;
     }
   }
```

**Comment by ukernel** [comment]
now I ran fsstress for an hour without problem,  thanks for helping debug this code.

**Comment by jtlayton** [comment]
Testing a branch of master with this branch merged in today, and I hit this crash while generic/011 was running. I'll see if I can reproduce it, but it may be unrelated to this work.

```
/home/jlayton/git/ceph/src/mds/MDCache.cc: 9197: FAILED ceph_assert(p != active_requests.end())

 ceph version 15.0.0-705-g79dd8ef5ac3e (79dd8ef5ac3ebcd67693685b9001ecb468076e5b) octopus (dev)
 1: (ceph::__ceph_assert_fail(char const*, char const*, int, char const*)+0x152) [0x7f1740bc4274]
 2: (()+0x26044c) [0x7f1740bc444c]
 3: (MDCache::request_get(metareqid_t)+0xcc) [0x55775f76bbbc]
 4: (Server::journal_close_session(Session*, int, Context*)+0xb55) [0x55775f6c7525]
 5: (Server::kill_session(Session*, Context*)+0x234) [0x55775f6cb224]
 6: (()+0x15afbf) [0x55775f699fbf]
 7: (()+0x1542c9) [0x55775f6932c9]
 8: (FunctionContext::finish(int)+0x2c) [0x55775f683f7c]
 9: (Context::complete(int)+0x9) [0x55775f681eb9]
 10: (Finisher::finisher_thread_entry()+0x17f) [0x7f1740c3fb9f]
 11: (()+0x858e) [0x7f17401c658e]
 12: (clone()+0x43) [0x7f173f94d683]
```

**Comment by jtlayton** [comment]
Haven't reproduced the last crash as of yet, but you are correct that setting '-f link=0' in fsstress works around the deadlock I was seeing. I guess that makes sense, as I believe we only rename into the strays dir when a file being unlinked has another hardlink.

Once that potential deadlock is resolved, then I think the only problem remaining that I see is what cap bit we're going to use to allow an async dirops.

**Comment by jtlayton** [comment]
I assume that this is going to be superseded by https://github.com/ceph/ceph/pull/27866 , correct? If so, maybe we should close this one out.

**Pull request closed without merging**
