### PR TITLE
msg: make async backend default

### PR DESCRIPTION
**Pull request by yuyuyu101**
Signed-off-by: Haomai Wang <haomai@xsky.com>

### CODE REVIEW

**Comment by yuyuyu101** [comment]
@yuriw @tchaikov and others... I hope anyone who ran a lot of qa suites can pick up this pr.

**Comment by yuyuyu101** [comment]
http://pulpito.ceph.com/haomai-2016-08-17_01:23:30-rados-wip-async-default-distro-basic-mira/

**Comment by yuriw** [comment]
@yuyuyu101 it will be part of wip-yuri-testing2_2016_08_22 tests, pls remove DNM as you see fit

**Comment by yuriw** [comment]
@yuyuyu101 can this be merged ?
Test run passed http://pulpito.ceph.com/yuriw-2016-08-26_22:32:43-rados-wip-yuri-testing_2016_08_26-distro-basic-smithi

**Comment by yuyuyu101** [comment]
@liewegas @athanatos would you think this is a good time point?

**Comment by yuriw** [comment]
Caution - we saw some unit tests failing which we (Josh and me)
initially thought were not related to the PRs (and this one in
particular), and I'm not so confident now as all tests verified passed
on master yesterday.

1 - test-ceph-helpers.sh (Failed)
5 - cephtool-test-mon.sh (Failed)
14 - run-tox-ceph-disk (Failed)
15 - run-tox-ceph-detect-init (Failed)

**Comment by liewegas** [comment]
assuming the unit test failures aren't related to async msgr (seems 
unlikely!) i'm all for switching the default again.  

iirc there was a cephfs deadlock issue.. did that get fixed?

**Comment by yuyuyu101** [comment]
yes, I don't think the uniitests failed related to async msgr too. I guess cephfs's problem is related to process spawn? @tchaikov @jcsp

**Comment by yuriw** [comment]
@jdurgin FYI ^

**Comment by jcsp** [comment]
Is there a log of the cephfs failure mentioned here?

**Comment by liewegas** [comment]
I just remember hearing something about it a few months ago.  IIRC fast 
dispatch related? @gregsfortytwo knows I think

**Comment by gregsfortytwo** [comment]
It wouldn't have been fast dispatch for the FS; I think it was the command with the bad locking that Doug fixed.

**Comment by yuriw** [comment]
unit tests failing b/c incorrect reg exp match issue, so tests actually passed per @jdurgin

related fix https://github.com/ceph/ceph/pull/10943

**Comment by yuriw** [comment]
I am reclaiming wip-yuri-teting tag, place it back to queue if it needs retesting   retesting

**Comment by yuyuyu101** [comment]
Hmm, I guess we could merge now.

**Pull request merged**
