### PR TITLE
rocksdb: build with ppc64

### PR DESCRIPTION
**Pull request by tchaikov**
changes included:

- cmake: check -momit-leaf-frame-pointer before using it
- util/thread_local.h: silence a clang-build warning

Signed-off-by: Kefu Chai <kchai@redhat.com>

### CODE REVIEW

**Comment by smithfarm** [comment]
@tchaikov Did you push this wip branch to ceph-ci.git ?

**Comment by tchaikov** [comment]
@smithfarm yes, https://shaman.ceph.com/builds/ceph/wip-12908/.

**Comment by smithfarm** [comment]
@tchaikov Are you OK to merge this before the upstream PRs are accepted?

**Comment by tchaikov** [comment]
@smithfarm yeah, i am fine.

**Pull request merged**
