### PR TITLE
osd: don't send stale hb msgr's addresses in MOSDBoot

### PR DESCRIPTION
**Pull request by rzarzynski**
See comments in the ticket for the RCA.

NOTE: we can't just hold a reference to what `get_myaddrs()` returns as the `safe_item_history` is involved:

```cpp
template<class T>
class safe_item_history {
  //...
  T *current = nullptr;

  // ...
  const T& operator=(const T& other) {
    std::lock_guard l(lock);
    history.push_back(other);
    current = &history.back();
    return *current;
  }
```

Fixes: https://tracker.ceph.com/issues/58915

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by ljflores** [comment]
jenkins test make check

**Review by ljflores — APPROVED** [review]

**Comment by ljflores** [comment]
@rzarzynski I had to open this new tracker, which reproduced twice: https://tracker.ceph.com/issues/59333

Can you check that this is not related to your PR? If it's not, feel free to merge.

Rados suite review:
https://pulpito.ceph.com/?branch=wip-yuri11-testing-2023-03-28-0950
https://pulpito.ceph.com/?branch=wip-yuri11-testing-2023-03-31-1108

Failures, unrelated:
    1. https://tracker.ceph.com/issues/58585
    2. https://tracker.ceph.com/issues/58946
    3. https://tracker.ceph.com/issues/58265
    4. https://tracker.ceph.com/issues/59271
    5. https://tracker.ceph.com/issues/59057
    6. https://tracker.ceph.com/issues/59333
    7. https://tracker.ceph.com/issues/59334
    8. https://tracker.ceph.com/issues/59335

Details:
    1. rook: failed to pull kubelet image - Ceph - Orchestrator
    2. cephadm: KeyError: 'osdspec_affinity' - Ceph - Orchestrator
    3. TestClsRbd.group_snap_list_max_read failure during upgrade/parallel tests - Ceph - RBD
    4. mon: FAILED ceph_assert(osdmon()->is_writeable()) - Ceph - RADOS
    5. rados/test_envlibrados_for_rocksdb.sh: No rule to make target 'rocksdb_env_librados_test' on centos 8 - Ceph - RADOS
    6. PgScrubber: timeout on reserving replicas - Ceph - RADOS
    7. test_pool_create_with_quotas: Timed out after 60s and 0 retries - Ceph - Mgr - Dashboard
    8. Found coredumps on smithi related to sqlite3 - Ceph - Cephsqlite

**Comment by ljflores** [comment]
@rzarzynski ping

**Comment by rzarzynski** [comment]
Thanks for resurrecting this, @ljflores! Let's get it into`main`, though I don't perceive the bug a deal breaker.

**Pull request merged**
