### PR TITLE
jewel: ceph-disk: using a regular file as a journal fails

### PR DESCRIPTION
**Pull request by dachary**
http://tracker.ceph.com/issues/17707
http://tracker.ceph.com/issues/17715

### CODE REVIEW

**Comment by dachary** [comment]
<pre>
teuthology-suite -k distro --verbose --suite ceph-disk --suite-branch jewel --ceph wip-17707-jewel --machine-type vps --priority 101 machine_types/vps.yaml
</pre>

* **running** http://pulpito.ceph.com/loic-2016-10-26_09:21:33-ceph-disk-wip-17707-jewel-distro-basic-vps/

**Comment by dachary** [comment]
In addition to the backports for http://tracker.ceph.com/issues/17707 and http://tracker.ceph.com/issues/17715, the series of python3 compatibility changes from https://github.com/ceph/ceph/pull/9936 were cherry-picked merely to avoid conflicts due to syntactic changes.

**Comment by dachary** [comment]
@tchaikov jenkins' broken right now but the ceph-disk suite passed (above). Would you have time to look into this backport ?

**Comment by tchaikov** [comment]
@dachary lgtm.

**Pull request merged**
