### PR TITLE
doc: hide page contents for Ceph Internals

### PR DESCRIPTION
**Pull request by mchangir**
Fixes: https://tracker.ceph.com/issues/42414
Signed-off-by: Milind Changire <mchangir@redhat.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`

</details>

### CODE REVIEW

**Comment by mchangir** [comment]
jenkins render docs

**Comment by theanalyst** [comment]
What is the reasoning behind hiding the dev/index? it is not as if the docs themselves are removed, wouldn't just a note mentioning that some of the dev docs may be outdated suffice instead of simply hiding the index?

**Comment by mchangir** [comment]
> What is the reasoning behind hiding the dev/index? it is not as if the docs themselves are removed, wouldn't just a note mentioning that some of the dev docs may be outdated suffice instead of simply hiding the index?

The Contents listing is available on the left hand side anyway.
Some of the docs may be outdated, I agree. Updating those docs will be taken up in due course of time.
This effort is just one of the efforts to eliminate visual bloat or redundancy.

**Comment by batrick** [comment]
> > What is the reasoning behind hiding the dev/index? it is not as if the docs themselves are removed, wouldn't just a note mentioning that some of the dev docs may be outdated suffice instead of simply hiding the index?
> 
> The Contents listing is available on the left hand side anyway.
> Some of the docs may be outdated, I agree. Updating those docs will be taken up in due course of time.
> This effort is just one of the efforts to eliminate visual bloat or redundancy.

This explanation should be in the commit message!

**Comment by batrick** [comment]
Page in question: https://docs.ceph.com/ceph-prs/31046/dev/internals/

**Comment by tchaikov** [comment]
```
187/187 Test  #14: test_objectstore_memstore.sh ............***Timeout 3600.02 sec
```
jenkins test make check

**Comment by tchaikov** [comment]
jenkins test make check

**Pull request merged**
