### PR TITLE
RFC: new style pgls

### PR DESCRIPTION
**Pull request by jcsp**

### CODE REVIEW

**Comment by jcsp** [comment]
@liewegas @athanatos see what you think of this so far?

The tests don't actually pass; I'm finding that the filestore is not actually returning items in the expected order (i.e. sorted by bit-reversed hash) -- assuming that there's something in its implementation causing that (haven't looked).

The math in  ReplicatedPG::do_pg_op to calculate the hash offset of the start of the next PG is a bit hacky (takes account of non-power-of-two pg_num though), there is probably a simpler way of expressing that.

**Comment by liewegas** [comment]
On Wed, 10 Jun 2015, John Spray wrote:
> @liewegas @athanatos see what you think of this so far?
> 
> The tests don't actually pass; I'm finding that the filestore is not actually returning items in the expected order (i.e. sorted by bit-reversed
> hash) -- assuming that there's something in its implementation causing that (haven't looked).

oh.. yeah, there is.  the DIR_$hexdigit dirs are sorted lexicographically 
now instead of in reverse bit order.  my branch fixing all this up is 
still half baked, sorry.  focusing on getting wip-temp merged first!

**Comment by liewegas** [comment]
wip-newstore-sort is the branch to rebase this onto

**Comment by liewegas** [comment]
see wip-9663-sage

**Comment by liewegas** [comment]
I think we should do this after infernalis unless there is a real pressing need for it there

**Comment by dachary** [comment]
@jcsp this needs to be rebased

**Comment by jcsp** [comment]
Closed in favour of https://github.com/ceph/ceph/pull/6405

**Pull request closed without merging**
