### PR TITLE
mimic: rbd-mirror: clone v2 mirroring improvements 

### PR DESCRIPTION
**Pull request by trociny**
backport trackers: https://tracker.ceph.com/issues/42727, https://tracker.ceph.com/issues/42700

---

backport of https://github.com/ceph/ceph/pull/31161, https://github.com/ceph/ceph/pull/31260
parent tracker: https://tracker.ceph.com/issues/42488, https://tracker.ceph.com/issues/42405

this backport was staged using ceph-backport.sh version 15.0.0.6950
find the latest version at https://github.com/ceph/ceph/blob/master/src/script/ceph-backport.sh

### CODE REVIEW

**Comment by trociny** [comment]
I have combined two backport trackers in one PR because the second tracker depends on the first.

**Comment by trociny** [comment]
need to include #31608 when it is merged

**Comment by smithfarm** [comment]
@trociny I tweaked the PR body because I'm not sure if `backport-resolve-issue` can handle multiple backport tracker URLs on a single line. (I will check the code of that script - I think it's a good thing to support.)

**Comment by yuriw** [comment]
[wip-yuri2-testing-2020-02-17-1636-mimic](https://trello.com/c/zBWEaMtK/828-wip-yuri2-testing-2020-02-17-1636-mimic)

**Pull request merged**
