### PR TITLE
mimic: rgw/beast: drop privileges after binding ports

### PR DESCRIPTION
**Pull request by emmericp**
https://tracker.ceph.com/issues/36332

---

I've also included https://github.com/cbodley/ceph/commit/8e0d0f3283460181d6e6cf59d9869a1c229a1c32 in this backport despite not being merged into master yet, is that okay?

### CODE REVIEW

**Comment by emmericp** [comment]
I'll also do it for luminous after you let me know if this looks okay with the tests. We are eager to get that fixed upstream sooner than later because this avoids some ugly code on our side (and we don't want to diverge too much on our builds)

**Comment by cbodley** [comment]
> I've also included [cbodley@8e0d0f3](https://github.com/cbodley/ceph/commit/8e0d0f3283460181d6e6cf59d9869a1c229a1c32) in this backport despite not being merged into master yet, is that okay?

good question. that commit was necessary to validate the fix, but i didn't propose merging it because i'm not sure we want to test privileged ports exclusively. i'll bring it up in the rgw standup today and see what others think

**Comment by cbodley** [comment]
@emmericp lets just drop that test commit for now. if we decide to follow up on it later, we would merge it to master and backport it separately. sound okay?

**Comment by yuriw** [comment]
[wip-yuri-testing-2018-10-12-2130-mimic](https://trello.com/c/4plgCp1c/439-wip-yuri-testing-2018-10-12-2130-mimic)

**Pull request merged**
