### PR TITLE
rgw: document and label mstart.sh and related scripts

### PR DESCRIPTION
**Pull request by cbodley**
<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Review by smanjara — APPROVED** [review]

**Comment by cbodley** [comment]
https://jenkins.ceph.com/job/ceph-pull-requests/145112/
> The following tests FAILED:
	247 - unittest_rbd_mirror (Failed)

commented in https://tracker.ceph.com/issues/68279

**Comment by cbodley** [comment]
jenkins test make check

**Comment by cbodley** [comment]
https://jenkins.ceph.com/job/ceph-api/83407/
> 2024-10-15 22:16:45,540.540 INFO:__main__:> ./bin/ceph mgr module enable zabbix --force
2024-10-15 22:16:46,880.880 INFO:__main__:> ./bin/ceph mgr dump --format=json-pretty
Build step 'Execute shell' marked build as failure
[PostBuildScript] - [INFO] Executing post build scripts.
[PostBuildScript] - [INFO] Build does not have any of the results [ABORTED]. Did not execute build step #0.

not clear why api tests failed

**Comment by cbodley** [comment]
jenkins test make check

**Pull request merged**
