### PR TITLE
nautilus: rgw/rgw_op: Remove get_val from hotpath via legacy options

### PR DESCRIPTION
**Pull request by pdvian**
https://tracker.ceph.com/issues/41624

### CODE REVIEW

**Comment by smithfarm** [comment]
jenkins test docs

**Comment by smithfarm** [comment]
jenkins test make check

**Comment by smithfarm** [comment]
```
GitHub pull request #30160 of commit 35c188b05a6f863c3f231152f07dacce0ec3ad17, no merge conflicts.
Running as SYSTEM
Setting status of 35c188b05a6f863c3f231152f07dacce0ec3ad17 to PENDING with url https://jenkins.ceph.com/job/ceph-pull-requests/33299/ and message: 'running make check'
Using context: make check
ERROR: Issue with creating launcher for agent 167.114.245.183+xenial_trusty_pbuilder_huge__5bf0ba44-6c78-4d6c-bac7-5995754c69fa. The agent has not been fully initialized yet
[EnvInject] - Loading node environment variables.
Building remotely on 167.114.245.183+xenial_trusty_pbuilder_huge__5bf0ba44-6c78-4d6c-bac7-5995754c69fa (jessie stretch trusty-pbuilder x86_64 bionic huge rebootable xenial trusty amd64)ERROR: 167.114.245.183+xenial_trusty_pbuilder_huge__5bf0ba44-6c78-4d6c-bac7-5995754c69fa seems to be offline
[PostBuildScript] - Executing post build scripts.
ERROR: Build step failed with exception
```

**Comment by smithfarm** [comment]
test this please

**Comment by smithfarm** [comment]
@pdvian In case you're interested, I have been working on the `ceph-backport.sh` script. You might find it useful? The current state is in https://github.com/ceph/ceph/pull/30106 - your review/testing is most welcome.

**Comment by yuriw** [comment]
[wip-yuri8-testing-2019-10-02-1628-nautilus](https://trello.com/c/ftSTonIP/704-wip-yuri8-testing-2019-10-02-1628-nautilus)

**Pull request merged**
