### PR TITLE
mimic: mgr/DaemonServer: fix Session leak

### PR DESCRIPTION
**Pull request by liewegas**
Fixes: https://tracker.ceph.com/issues/35998

### CODE REVIEW

**Comment by tomzo** [comment]
I have tested exactly this change with valgrind and it fixes leak on mimic.

**Comment by jcsp** [comment]
@liewegas was this mimic-specific PR just because that's where the fix was being tested?  Looks like we have the same issue on master.

**Comment by smithfarm** [comment]
@jcsp The commit message says: "This bug does not exist in master." Are you saying that statement is false?

**Comment by jcsp** [comment]
@smithfarm oops, in this case I'm just failing to read commit messages :-)

Never mind!

**Comment by jcsp** [comment]
When I suggested we had the same issue on master it was just that the same LOC was unchanged there, I'm guessing that Sage already checked through and the reference counting was correct in master

**Comment by yuriw** [comment]
[wip-yuri2-testing-2018-10-03-1527-mimic](https://trello.com/c/aC81XEdb/432-wip-yuri2-testing-2018-10-03-1527-mimic)

**Comment by gucki** [comment]
Could this please released soon? Some of my msgr daemons eat several GB of ram within a few days and they always need to be restarted periodically....

**Comment by smithfarm** [comment]
@gucki mimic 13.2.3 will be released soon, yes.

**Comment by tomzo** [comment]
@gucki can you have a look at https://tracker.ceph.com/issues/36471 and see if maybe you have similar problems as I do? I am a bit confused if there is still a problem in ceph or is it my deployment only.

**Comment by gucki** [comment]
@smithfarm I'm sorry, but what's the definition of soon? According to the release schedule a point release is done every 4-6 weeks. However the last release was done in 09/18 so at least 10 weeks ago... :-(

**Pull request merged**
