### PR TITLE
octopus: mgr/dashboard: Remove redundant pytest requirement

### PR DESCRIPTION
**Pull request by badone**
Fixes: https://tracker.ceph.com/issues/50228

Signed-off-by: Brad Hubbard <bhubbard@redhat.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by nizamial09** [comment]
jenkins test make check

**Comment by tchaikov** [comment]
might want to backport eab195566d54122f826debd8efb7f36db78fa4e1

**Review by epuertat — APPROVED** [review]
LGTM. Thanks, @badone !

**Comment by epuertat** [comment]
jenkins test make check

**Comment by epuertat** [comment]
```
Installing collected packages: filelock, distlib, virtualenv, toml, py, pluggy, tox
  Attempting uninstall: distlib
    Found existing installation: distlib 0.3.0
INFO: pip is looking at multiple versions of cryptography to determine which version is compatible with other requirements. This could take a while
...
(similar trace)
...
INFO: pip is looking at multiple versions of ceph to determine which version is compatible with other requirements. This could take a while.
  CC cmdline_vt100.o
ERROR: Cannot install -r requirements-test.txt (line 3) and pytest<4 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested pytest<4
    pytest-cov 2.11.1 depends on pytest>=4.6

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies
```

**Comment by epuertat** [comment]
I wonder why we were requiring `pytest` in `requirements.txt` (prod-deps) and `-lint` (linting-deps) envs, shouldn't it only be in `requirements-test.txt` (test-deps)?

**Comment by badone** [comment]
Cherry picked the commits @tchaikov suggested (should have looked for those before creating my commit). Needs a fresh review.

**Comment by badone** [comment]
jenkins retest this please

**Comment by badone** [comment]
jenkins test make check

**Comment by badone** [comment]
jenkins test make check

**Comment by badone** [comment]
jenkins test api

**Comment by avanthakkar** [comment]
jenkins test make check

**Review by alfonsomthd — APPROVED** [review]

**Review by Waadkh7 — APPROVED** [review]

**Comment by badone** [comment]
The 'make check' failures look like they are to do with the pytest change. I'll take a look in the next few days.

**Comment by tchaikov** [comment]
jenkins test make check

**Comment by epuertat** [comment]
@tchaikov I think you already dealt with the `pytest 4` issue in the past. Perhaps [we didn't backport those changes](https://github.com/ceph/ceph/pull/37692/files).

**Comment by tchaikov** [comment]
@epuertat i didn't get a chance to look into the latest failures. looks like so.

**Comment by badone** [comment]
jenkins test make check

**Comment by badone** [comment]
@epuertat @tchaikov I've included what seemed to be the relevant commits as indicated by Ernesto and they appear to have done the trick.

**Review by tchaikov — APPROVED** [review]

**Review by epuertat — APPROVED** [review]

**Pull request merged**
