### PR TITLE
configure.ac: add --disable-gitversion

### PR DESCRIPTION
**Pull request by dalgaaf**
During development each git commit cause currently a complete
rebuild of the source tree. By passing --disable-gitversion to
configure we set a generic version string for ceph to prevent
getting after each commit a new version set.

remove src/check_version and replace with a extended version
of src/make_check which allows detecting changes in .git_version
and ceph_ver.h to avoid not needed updates.

This change also forces to call make_version each time to make
sure that changes from configure or the NO_VERSION env variable
are processed.

Signed-off-by: Danny Al-Gaaf <danny.al-gaaf@bisect.de>

### CODE REVIEW

**Comment by dalgaaf** [comment]
split from #4000

**Comment by dachary** [comment]
Reviewed-by: as soon as gitbuilder + make check bot are ok.

**Comment by liewegas** [comment]
:+1:

**Comment by tchaikov** [comment]
love this change ! but we might want to fix the git repo detection in `make_version`.

**Comment by dalgaaf** [comment]
fixed and added check if git command is intalled at all.

**Comment by tchaikov** [comment]
looks good to me.

**Comment by dachary** [comment]
A few little things otherwise looks good to me :-)

**Comment by dalgaaf** [comment]
Updated. Also changed the tmpfile handling to make use of mktemp.

**Pull request merged**
