### PR TITLE
rgw-multisite: fix endless loop in RGWBucketShardIncrementalSyncCR

### PR DESCRIPTION
**Pull request by cfanz**
Fixes: http://tracker.ceph.com/issues/24603

Signed-off-by: cfanz <songxinying@sensetime.com>

### CODE REVIEW

**Comment by cfanz** [comment]
@cbodley Could you explain more detailedly？It seems this is the reason leading to the endless loop. I agree with the idea that avoids running remaining stuff after `sync_status !=0 ` is detected.

**Comment by cfanz** [comment]
@cbodley Could you explain more detailedly？It seems this is the reason leading to the endless loop. I agree with the idea that avoids running remaining stuff after `sync_status !=0 ` is detected.

**Comment by tianshan** [comment]
@cbodley  I think should also set sync_status to some error value such as -EAGAIN in this situation, since we already have sync_status == 0 judge in do while loop, if that didn't break, maybe the another key is successful.
We have meet this situation once, the record is we have one key has two same timestamp complete op cause this, but I've forgot how that happened.

**Comment by cbodley** [comment]
hi @tianshan, i don't quite follow - what changes when you overwrite sync_status with -EAGAIN in this case?

**Comment by tianshan** [comment]
@cbodley  when get into marker_tracker.can_do_op(key) = false, judge num_spawned() == 0, if so, set sync_status = -EAGAIN, will break the big do while loop.

**Comment by cbodley** [comment]
> @cbodley when get into marker_tracker.can_do_op(key) = false, judge num_spawned() == 0, if so, set sync_status = -EAGAIN, will break the big do while loop.

@tianshan hmm, ok. given two bilog entries with the same op and timestamp, i see that the squash_map will compare == for both entries. past that, it looks like it would spawn a BucketSyncSingle for the first, and then the second would loop on can_do_op() until the first finished. so either BucketSyncSingle succeeds and can_do_op() eventually returns true, or BucketSyncSingle fails and the check for sync_status in this pr avoids the infinite loop

however, since it's wasteful to sync the same thing twice in a row, i think we should use the squash_map to reject one of them. how about adding the bilog entry's id to the squash_map, so that only one of the comparisons succeed?

meanwhile, i plan to go ahead with testing on this pr as is

**Comment by cbodley** [comment]
http://pulpito.ceph.com/cbodley-2018-06-22_19:13:17-rgw-wip-cbodley-testing-distro-basic-smithi/

**Pull request merged**
