### PR TITLE
luminous: osd: race condition opening heartbeat connection

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/36636

### CODE REVIEW

**Comment by smithfarm** [comment]
@batrick I was under the impression that compilation fails if I put `std::lock_guard` instead of `Mutex::Locker`. Let me try it again.

**Comment by smithfarm** [comment]
Aha! In C++11 it has to be `std::lock_guard<std::mutex>`

**Comment by smithfarm** [comment]
```
In file included from /home/jenkins-build/build/workspace/ceph-pull-requests/src/test/osd/TestOSDMap.cc:2:0:
/home/jenkins-build/build/workspace/ceph-pull-requests/src/googletest/googletest/include/gtest/gtest.h: In instantiation of ‘testing::AssertionResult testing::internal::CmpHelperEQ(const char*, const char*, const T1&, const T2&) [with T1 = int; T2 = long unsigned int]’:
/home/jenkins-build/build/workspace/ceph-pull-requests/src/googletest/googletest/include/gtest/gtest.h:1421:23:   required from ‘static testing::AssertionResult testing::internal::EqHelper<lhs_is_null_literal>::Compare(const char*, const char*, const T1&, const T2&) [with T1 = int; T2 = long unsigned int; bool lhs_is_null_literal = false]’
/home/jenkins-build/build/workspace/ceph-pull-requests/src/test/osd/TestOSDMap.cc:511:3:   required from here
/home/jenkins-build/build/workspace/ceph-pull-requests/src/googletest/googletest/include/gtest/gtest.h:1392:11: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   if (lhs == rhs) {
           ^
[ 75%] Linking CXX executable ../../../bin/unittest_osdmap
/home/jenkins-build/build/workspace/ceph-pull-requests/src/osd/OSD.cc: In member function ‘bool OSD::heartbeat_reset(Connection*)’:
/home/jenkins-build/build/workspace/ceph-pull-requests/src/osd/OSD.cc:5258:47: error: no matching function for call to ‘std::lock_guard<std::mutex>::lock_guard(Mutex&)’
   std::lock_guard<std::mutex> l(heartbeat_lock);
                                               ^
In file included from /home/jenkins-build/build/workspace/ceph-pull-requests/src/include/mempool.h:24:0,
                 from /home/jenkins-build/build/workspace/ceph-pull-requests/src/osd/PG.h:29,
                 from /home/jenkins-build/build/workspace/ceph-pull-requests/src/osd/OSD.cc:34:
/usr/include/c++/5/mutex:388:7: note: candidate: std::lock_guard<_Mutex>::lock_guard(std::lock_guard<_Mutex>::mutex_type&, std::adopt_lock_t) [with _Mutex = std::mutex; std::lock_guard<_Mutex>::mutex_type = std::mutex]
       lock_guard(mutex_type& __m, adopt_lock_t) : _M_device(__m)
       ^
/usr/include/c++/5/mutex:388:7: note:   candidate expects 2 arguments, 1 provided
/usr/include/c++/5/mutex:385:16: note: candidate: std::lock_guard<_Mutex>::lock_guard(std::lock_guard<_Mutex>::mutex_type&) [with _Mutex = std::mutex; std::lock_guard<_Mutex>::mutex_type = std::mutex]
       explicit lock_guard(mutex_type& __m) : _M_device(__m)
                ^
/usr/include/c++/5/mutex:385:16: note:   no known conversion for argument 1 from ‘Mutex’ to ‘std::lock_guard<std::mutex>::mutex_type& {aka std::mutex&}’
src/osd/CMakeFiles/osd.dir/build.make:62: recipe for target 'src/osd/CMakeFiles/osd.dir/OSD.cc.o' failed
make[3]: *** [src/osd/CMakeFiles/osd.dir/OSD.cc.o] Error 1
CMakeFiles/Makefile2:4848: recipe for target 'src/osd/CMakeFiles/osd.dir/all' failed
make[2]: *** [src/osd/CMakeFiles/osd.dir/all] Error 2
make[2]: *** Waiting for unfinished jobs....
```

@batrick I wonder if it's worth the effort to get it working with `std::lock_guard`, when it was working fine with `Mutex::Locker` ?

**Comment by liewegas** [comment]
There is no significant difference bteween Mutex::Locker and lock_guard (in fact, in master, Mutex::locker has become a lock_guard typedef). Just use the Locker one because we know it works in this release and doesn't have compiler dependencies.

**Comment by smithfarm** [comment]
OK, reverted.

**Comment by yuriw** [comment]
[wip-yuri3-testing-2018-11-27-2241-luminous](https://trello.com/c/ntdQZjkB/481-wip-yuri3-testing-2018-11-27-2241-luminous)

**Pull request merged**
