### PR TITLE
AsyncMessenger: Bind thread to core, use buffer read and fix some bugs

### PR DESCRIPTION
**Pull request by yuyuyu101**
1. Bind limited threads to specified cores
2. Using buffer read like what pipe done
3. discard poll call
4. add ms_inject_* to async
5. fix replace process
6. fix memory leak
7. lots of small bug fixed

impl feature #10172 #10396

### CODE REVIEW

**Comment by dachary** [comment]
@yuyuyu101 the master branch is broken http://tracker.ceph.com/issues/10547

**Comment by yuyuyu101** [comment]
@liewegas Do you have time to give a look?  Mainly ms_inject* is added to async and a synthetical messenger stress and inject-error test is added to test_msgr.cc. Lots of async bugs are fixed.

This async version is very near to run qa-suite I think.

**Comment by dachary** [comment]
@yuyuyu101 not that since unittest_msgr do not run as part of make check because of http://tracker.ceph.com/issues/10494 it is recommended to manually run **while unittest_msgr ; do : ; done** for a few minutes to check that it works as expected

**Comment by yuyuyu101** [comment]
@dachary yeah, of couse. I have ran this command nearly one hour without error still now.:-)

**Comment by dachary** [comment]
@yuyuyu101 good news ! maybe you could also update the src/test/Makefile.am to re-activate the test then ?

**Comment by yuyuyu101** [comment]
@dachary I can't find error in this page(http://paste2.org/zAvccMOw). Am I missing something?

**Comment by liewegas** [comment]
I looked through most of it and it all sonds find, but I dont have time for a detailed review of teh asyncmsgr changes.  I assume you're fine with those changes though so I say let's just rebase (there's a merge conflict) and add needs-qa!

**Comment by yuyuyu101** [comment]
@dachary I guess "make check" think it's timeout? Actually new unittest_msgr will ran much time than before.

**Comment by dachary** [comment]
please ignore the latest fail of the bot.
is there a reason for unittest_msg to take more than two minutes ?

**Comment by dachary** [comment]
@yuyuyu101 if I'm not mistaken the reason why the tests take more time is because you increased the timers in CHECK_AND_WAIT_TRUE. The problem with this approach is that it will not fix the root of the problem which is that the tests are racy and will fail depending on how slow / fast the machine is. Increasing the timers will only make the problems less frequent, it will not fix them. It means that someone working on an unrelated part of Ceph may see the test_msgr.cc fail and it will be quite difficult for her/him to figure out that  it is because test_msgr.cc will sometime fail but not most of the time. 

If I missed the real fix, please ignore me ;-)

**Comment by yuyuyu101** [comment]
@dachary No, CHECK_AND_WAIT_TRUE isn't the root cause. For example, if we run this test in a slow vm, it need more time to build tcp connection and shakehands. Previously, it only left 1ms let it build and now I changed it to 0.5s at max. It doesn't hidden any potential bug.

The last assert fail reason is that the test mark_down a connection but peer detect closed connection need more time than I expected, the detect time depends on OS and network. So I add a lock/cond method instead of a fixed waiting time.

Why we ran this test more than two minutes is that SyntheticStressTest and SyntheticInjecteTest are added which will consuming nearly 5mins even if in my physical server. The time changed for CHECK_AND_WAIT_TRUE is very little.

I hope I clarify the reason :-)

**Comment by dachary** [comment]
@yuyuyu101 
>  The last assert fail reason is that the test mark_down a connection but peer detect closed connection need more time than I expected, the detect time depends on OS and network. So I add a lock/cond method instead of a fixed waiting time.

This is exactly what I mean, thanks for clarifying. My point is that every time you use CHECK_AND_WAIT_TRUE you can replace it with a lock/cond. That will make the test bullet proof and impossible to fail, no matter how slow the machine is. 

Does that make sense or is there a CHECK_AND_WAIT_TRUE call that will never fail ?

**Comment by yuyuyu101** [comment]
@dachary Yes, current all CHECK_AND_WAIT_TRUE has been reviewed again. I think it shouldn't fail again if others well. 

And you suggest that unittest_msgr ran too long for "make check", now unittest_msgr will ran nearly 7-8mins in my physical server. But I think if we decrease op num to reduce it under 1min, it may can't met test purpose. So I consider it may be move to qa-suite.

@liewegas Updated, add to qa?

**Pull request merged**
