### PR TITLE
mon: do not recalculate 'to_remove' when it's known

### PR DESCRIPTION
**Pull request by songbaisen**
mon: do not recalculate 'to_remove' when it's known

Signed-off-by:song baisen <song.baisen@zte.com.cn>

### CODE REVIEW

**Comment by tchaikov** [comment]
@songbaisen the change looks good to me.

but could you revise your commit message (and title) to be more specific? imho, "small change in paxos assignment" is not very helpful. something like "do not recalculate 'to_remove' when it's known" would be better.

**Comment by songbaisen** [comment]
@tchaikov  Thank you sir! Done it!

**Comment by tchaikov** [comment]
lgtm.

**Comment by tchaikov** [comment]
tested in http://pulpito.ceph.com/kchai-2016-07-10_07:48:29-rados-wip-kefu-testing---basic-mira/ 

the non-environmental failures are addressed by #10234 .

**Pull request merged**
