### PR TITLE
mgr/cephadm: Revert changes introduced in order to use "split cgroup strategy for podman"

### PR DESCRIPTION
**Pull request by jmolmo**
Avoid to break OSD replacement.

Revert partially the changes introduced in pr #40025 until we know what is the problem in Systemd services when using `Delegate=yes`

Fixes: https://tracker.ceph.com/issues/50998

Signed-off-by: Juan Miguel Olmo Martínez <jolmomar@redhat.com>

## Checklist
- [x] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by sebastian-philipp** [comment]
@huww98 could you have a look at this, please? Maybe we can find a better solution that to revert this.

**Comment by jmolmo** [comment]
jenkins test make check

**Comment by sebastian-philipp** [comment]
ping @huww98

**Comment by huww98** [comment]
I will try to reproduce this at this weekend.

**Review by sebastian-philipp — CHANGES_REQUESTED** [review]
is #41829 a better fix???

**Comment by jmolmo** [comment]
Closed in favour of https://github.com/ceph/ceph/pull/41829

**Pull request closed without merging**
