### PR TITLE
nautilus: rgw: protect AioResultList by a lock to avoid race condition

### PR DESCRIPTION
**Pull request by IlsooByun**
Fixes: https://tracker.ceph.com/issues/39660

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`

</details>

### CODE REVIEW

**Comment by mattbenjamin** [comment]
@cbodley looks interesting

**Comment by cbodley** [comment]
this looks correct, and we don't need this change on master because the BlockingAioThrottle does cover these cases with a lock. we _could_ consider backporting https://github.com/ceph/ceph/pull/26461 and https://github.com/ceph/ceph/pull/26173 instead, but they bring in several unrelated changes as groundwork for data caching and async stuff that aren't needed in nautilus

cc @smithfarm

**Comment by liewegas** [comment]
@yuriw let's make sure this makes the next nautilus

**Comment by smithfarm** [comment]
@IlsooByun Could you please make the following two changes:

1. drop the `nautilus: ` from the commit message
2. add to the commit message the following sentence: "This change is not cherry-picked from master because, in master, the BlockingAioThrottle does cover these cases with a lock."

Thanks!

**Comment by smithfarm** [comment]
@cbodley @liewegas Should this fix be applied to mimic as well?

**Comment by cbodley** [comment]
> Should this fix be applied to mimic as well?

no, this code isn't present in mimic

**Comment by IlsooByun** [comment]
> @IlsooByun Could you please make the following two changes:
> 
> 1. drop the `nautilus: ` from the commit message
> 2. add to the commit message the following sentence: "This change is not cherry-picked from master because, in master, the BlockingAioThrottle does cover these cases with a lock."
> 
> Thanks!

@smithfarm I fixed as you commented. Thank you.

**Comment by yuriw** [comment]
[wip-yuri7-testing-2019-11-12-2103-nautilus](https://trello.com/c/WyvBSbE0/757-wip-yuri7-testing-2019-11-12-2103-nautilus)

**Pull request merged**
