### PR TITLE
doc/glossary: add "ceph monitor" entry

### PR DESCRIPTION
**Pull request by zdover23**
This commit adds information to the "ceph monitor" entry in glossary.rst.

Signed-off-by: Zac Dover <zac.dover@gmail.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [x] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [x] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Review by anthonyeleven — APPROVED** [review]
@zdover23 Approved, though I suggest adding a sentence that monitor daemons and the nodes on which they run are frequently referred to as "mons".

**Review by anthonyeleven — APPROVED** [review]
Approved, cf. my suggestion in the other PR to add a sentence nothing that monitor daemons and the nodes on which they run are frequently referred to as "mons".

**Comment by zdover23** [comment]
> Approved, cf. my suggestion in the other PR to add a sentence nothing that monitor daemons and the nodes on which they run are frequently referred to as "mons".

@anthonyeleven: I agree. I've added such a sentence.

**Comment by anthonyeleven** [comment]
I woulda left out the double quotes, ymmv

**Comment by zdover23** [comment]
https://github.com/ceph/ceph/pull/48447 - Quincy backport
https://github.com/ceph/ceph/pull/48448 - Pacific backport

**Pull request merged**
