### PR TITLE
mgr/PyModule: correctly remove config options

### PR DESCRIPTION
**Pull request by tserong**
Previously, incorrect parameters were being passed to "config rm",
causing it to do nothing.  This commit also ensures the correct
error message is shown for both the set and remove failure cases.

Fixes: https://tracker.ceph.com/issues/42958
Signed-off-by: Tim Serong <tserong@suse.com>

### CODE REVIEW

**Comment by sebastian-philipp** [comment]
This is a regression. I already fixed `set backend ''` in the past at least once. Can we verify that this is not going to break again in the future? Eg adding a test to

https://github.com/ceph/ceph/blob/77226cd2011ce0b452d961b0c5aa6a894f6588b3/qa/tasks/mgr/test_orchestrator_cli.py#L14

or

https://github.com/ceph/ceph/blob/77226cd2011ce0b452d961b0c5aa6a894f6588b3/src/pybind/mgr/selftest/module.py#L263

?

**Comment by sebastian-philipp** [comment]
Or can we make

https://github.com/ceph/ceph/blob/77226cd2011ce0b452d961b0c5aa6a894f6588b3/src/pybind/mgr/orchestrator_cli/module.py#L662

Actually verify this fix?

**Comment by tserong** [comment]
Having done some further testing, I don't think #29042 fixed the issue completely; it works transiently, but the option was still never removed from the config. Here's some test output from a vstart cluster:

```
> ./bin/ceph orchestrator set backend ssh
> ./bin/ceph orchestrator status
Backend: ssh
Available: True
> ./bin/ceph config get mgr mgr/orchestrator_cli/orchestrator
ssh
> ./bin/ceph orchestrator set backend ''
> ./bin/ceph orchestrator status
Error ENOENT: No orchestrator configured (try `ceph orchestrator set backend`)
> ./bin/ceph config get mgr mgr/orchestrator_cli/orchestrator
ssh
```

Note how the orchestrator module thinks no backend is configured, but the option is still set? If you restart at this point, it comes back up set to "ssh" again.

**Comment by tserong** [comment]
...this is of course because the value is set in (or removed from) the config map in PyModuleConfig::set_config() (https://github.com/ceph/ceph/blob/master/src/mgr/PyModule.cc#L151-L155) prior to persisting the value. If I move that piece so it happens *after* the value is persisted successfully, the current check in orchestrator_cli's self_test() will probably work correctly.

**Comment by tserong** [comment]
Yep, that works.

**Pull request merged**
