### PR TITLE
ceph-volume: Require lvm2, move to osd package

### PR DESCRIPTION
**Pull request by thmour**
Fixes: http://tracker.ceph.com/issues/22443

Signed-off-by: Theofilos Mouratidis <t.mour@cern.ch>

### CODE REVIEW

**Comment by alfredodeza** [comment]
This looks OK to me. Unsure if the Debian control files will need it to.

**Comment by ktdreyer** [comment]
If it's just ceph-volume that needs the LVM utils, we can put this requirement in the "ceph-osd" package instead of "ceph-base".

Good call on the `debian/control` file @alfredodeza . We do need "Depends: lvm2" as well for the ceph-osd package there.

**Comment by smithfarm** [comment]
ceph-disk used to be in the ceph-osd package, but was moved to ceph-base by https://github.com/ceph/ceph/pull/14871

ceph-volume has been in ceph-base since its inception, but I'm not sure there's a good reason for that. . . for example, it means ceph-volume will be included on mon-only nodes, mds-only nodes, etc.

It seems strange to put the `Requires: lvm2` in ceph-osd when ceph-volume itself is in ceph-base. On the other hand, putting the dependency in ceph-base just adds further dead weight to non-OSD nodes (and, now, containers - which are supposed to be lightweight?).

Would it be worth considering to move both ceph-volume and its lvm2 dependency to ceph-osd?

**Comment by alfredodeza** [comment]
I don't think ceph-volume should be in anything other than ceph-osd, and I think it should be moved.

**Comment by liewegas** [comment]
@b-ranto can you confirm that there's no reason for ceph-volume to be in ceph-base now?  (was ceph-disk only needed there in order to support the previous upgrade?)

**Comment by ktdreyer** [comment]
> ceph-volume has been in ceph-base since its inception

Good call. It's a discrepancy between the Debian and RPM packaging (ceph-volume is in `debian/ceph-osd.install`)

I think ceph-volume should be in the ceph-osd package for both distro families.

**Comment by tchaikov** [comment]
i concur with @smithfarm and @ktdreyer .

**Comment by thmour** [comment]
`ceph-volume` is now moved to the osd package, along with the lvm2 dependency

**Comment by alfredodeza** [comment]
I'll let others take a look as well, building these changes now so we can run some tests:

https://shaman.ceph.com/builds/ceph/pr19529/

**Comment by ktdreyer** [comment]
Would you mind making the change to the `/debian/control` file as well? We need "Depends: lvm2" for the ceph-osd package there.

**Comment by b-ranto** [comment]
@liewegas Yep, we only needed ceph-disk binary in ceph-base so that we could use the `ceph-disk fix` command during the package upgrades. The ceph_disk python library was already in ceph-base before that and I am not sure what it was needed there for.

**Comment by alfredodeza** [comment]
This does not work on the Debian/Ubuntu side of things. Unsure what to suggest here.

    '/usr/bin/apt-get -y -o "Dpkg::Options::=--force-confdef" -o "Dpkg::Options::=--force-confold"     install 'ceph'' failed: E: Unable to correct problems, you have held broken packages.

    The following packages have unmet dependencies:
     ceph : Depends: ceph-mgr (= 13.0.0-4262-g02bc369-1xenial) but it is not going to be installed
            Depends: ceph-mon (= 13.0.0-4262-g02bc369-1xenial) but it is not going to be installed
            Depends: ceph-osd (= 13.0.0-4262-g02bc369-1xenial) but it is not going to be installed
            Recommends: ceph-mds (= 13.0.0-4262-g02bc369-1xenial) but it is not going to be installed
    
    E: Unable to correct problems, you have held broken packages.

**Comment by alfredodeza** [comment]
centos7-bluestore certainly worked fine

**Comment by tchaikov** [comment]
```
$ apt-cache show  ceph-mgr | grep libstdc++
Depends: ceph-base (= 13.0.0-4262-g02bc369-1xenial), python-cherrypy3, python-openssl, python-pecan, python-werkzeug, init-system-helpers (>= 1.18~), libc6 (>= 2.17), libgcc1 (>= 1:3.0), libgoogle-perftools4, libibverbs1 (>= 1.1.2), libnspr4 (>= 2:4.9-2~) | libnspr4-0d (>= 1.8.0.10), libnss3 (>= 2:3.13.4-2~) | libnss3-1d (>= 3.12.9~beta2), libpython2.7 (>= 2.7), libstdc++6 (>= 6), zlib1g (>= 1:1.1.4)
```

turns out ceph-mgr was linked against libstdc++6 from the PPA repo dynamically.

@alfredodeza you need to rebase your branch against master to include https://github.com/ceph/ceph/commit/75c5e5cc26ae202bc0560fdfc38a3ecce1188ad7, and rebuild it. sorry for the inconvenience =(

**Comment by alfredodeza** [comment]
This is good to go.

**Comment by tchaikov** [comment]
- http://pulpito.ceph.com/kchai-2018-01-08_13:52:40-rados-wip-kefu-testing-2018-01-08-1914-distro-basic-mira/
- http://pulpito.ceph.com/kchai-2018-01-09_13:55:16-rados-wip-kefu-testing-2018-01-09-1600-distro-basic-mira/

**Pull request merged**
