### PR TITLE
squid: kv/RocksDBStore: Configure compact-on-deletion for all CFs

### PR DESCRIPTION
**Pull request by k0ste**
backport tracker: https://tracker.ceph.com/issues/65915

---

backport of https://github.com/ceph/ceph/pull/55676
parent tracker: https://tracker.ceph.com/issues/64511

this backport was staged using ceph-backport.sh version 16.0.0.6848
find the latest version at https://github.com/ceph/ceph/blob/main/src/script/ceph-backport.sh

### CODE REVIEW

**Comment by ifed01** [comment]
jenkins test api

**Review by ifed01 — APPROVED** [review]

**Comment by yuriw** [comment]
Approved by @ronen-fr 
https://tracker.ceph.com/projects/rados/wiki/SQUID#httpstrackercephcomissues66792

**Comment by yuriw** [comment]
jenkins test api

**Comment by yuriw** [comment]
@k0ste pls merge when all checks passed
it was tested re: https://tracker.ceph.com/issues/66792#change-268163

**Comment by k0ste** [comment]
> @k0ste pls merge when all checks passed

I can't merge, but rebased for last changes from squid branch

**Comment by ifed01** [comment]
jenkins test make check

**Comment by gardran** [comment]
jenkins test make check

**Pull request merged**
