### PR TITLE
mgr/dashboard: change privacy protocol field from required to optional

### PR DESCRIPTION
**Pull request by avanthakkar**
Fixes: https://tracker.ceph.com/issues/54270
Signed-off-by: Avan Thakkar <athakkar@redhat.com>

Privacy protocol field must be optional and adding validation for snmp v3 engine id along with some cleanups.

Before:
Screenshot from 2022-02-14 20-02-20

After:
Screenshot from 2022-02-14 20-03-00

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [x] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [x] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Review by pereman2 — COMMENTED** [review]
the expected outcome of this pr looks good, but I saw this generic error while trying to create a service after adding a random engine id:
image

I think a descriptive error would help me understand why this isn't correct.

**Comment by sunilangadi2** [comment]
> the expected outcome of this pr looks good, but I saw this generic error while trying to create a service after adding a random engine id: image
> 
> I think a descriptive error would help me understand why this isn't correct.

+1 with Pere, @avanthakkar can you add a descriptive error message instead of 500 error
So that it helps users to configure their SNM MIB system thoroughly

**Comment by avanthakkar** [comment]
> > the expected outcome of this pr looks good, but I saw this generic error while trying to create a service after adding a random engine id: image
> > I think a descriptive error would help me understand why this isn't correct.
> 
> +1 with Pere, @avanthakkar can you add a descriptive error message instead of 500 error So that it helps users to configure their SNMP MIB system thoroughly

@sunilangadi2 I'm gonna add the validation for engine id as well, so the user will know before hand if it's invalid!

**Review by sunilangadi2 — CHANGES_REQUESTED** [review]
Screenshot from 2022-02-15 13-30-47
@avanthakkar I think even we can hide this **unmanaged** option for this SNMP service,
 as it's not like other cephadm services like mon,mgr for managing from cephadm with option unmanaged 
 So please remove that option or provide a proper error message to it instead of a 500 error?

**Review by pereman2 — APPROVED** [review]
worked fine for me, LGTM

**Comment by avanthakkar** [comment]
jenkins test dashboard

**Comment by sunilangadi2** [comment]
@avanthakkar Can you please attach a screenshot, also some of the dashboard tests got failed, Can you please check that?

**Comment by avanthakkar** [comment]
jenkins test dashboard

**Comment by avanthakkar** [comment]
> @avanthakkar Can you please attach a screenshot, also some of the dashboard tests got failed, Can you please check that?

Removed unmanaged:
Screenshot from 2022-02-16 12-50-18

Validation for Engine Id:
Screenshot from 2022-02-16 12-54-23

**Comment by nizamial09** [comment]
> Removed unmanaged:
> Screenshot from 2022-02-16 12-50-18

@avanthakkar just to point out a minor thing, if there are no fields in the `Credentials` shouldn't the heading itself hidden?

**Review by nizamial09 — APPROVED** [review]

**Comment by avanthakkar** [comment]
> > Removed unmanaged:
> > Screenshot from 2022-02-16 12-50-18
> 
> @avanthakkar just to point out a minor thing, if there are no fields in the `Credentials` shouldn't the heading itself hidden?

Umm ok..but well the version selection is mandatory anyways so it doesn't matter I guess!

**Review by sunilangadi2 — APPROVED** [review]
@avanthakkar LGTM, Thanks for adding changes to it.

**Comment by epuertat** [comment]
@avanthakkar Kudos for showing initiative and merging your own PR! Just a couple of details you have to take into account when doing so:
* You need to add a `Reviewed-by: FirstName LastName <email>` line per reviewer. The best way to do that is with a Chrome/Firefox extension Tiago created (https://chrome.google.com/webstore/detail/ceph-github-helper/ikpfebikkeabmdnccbimlomheocpgkmn)
* You should remember to delete the branch used for the PR. I just [enabled the auto-delete on the RHCS Ceph repo](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-the-automatic-deletion-of-branches), but I'm not sure if that should be enabled in the main Ceph repo too.
* And, in this very case, you need to add the "needs-quincy-backport".

**Pull request merged**
