### PR TITLE
rgw: delete some unused code about std::regex

### PR DESCRIPTION
**Pull request by baixueyu**
Delete some unused code about std::regex in  rgw_iam_policy.cc. 
Signed-off-by: Xueyu Bai \<baixueyu@inspur.com\>

### CODE REVIEW

**Comment by cbodley** [comment]
jenkins test make check

**Comment by tchaikov** [comment]
@baixueyu 
could you prefix the title of your commit message with the subcomponent your are changing ? see https://github.com/ceph/ceph/blob/master/SubmittingPatches.rst#3-describe-your-changes . in this case, the prefix could be "rgw: ".

and you also need to update your Signed-off-by line, to quote your email address with "<>", so it looks like
```
Signed-off-by: Xueyu Bai <baixueyu@inspur.com>
```

**Comment by tchaikov** [comment]
@baixueyu ping?

**Comment by baixueyu** [comment]
hi， can you help me merge this pull request?

**Comment by tchaikov** [comment]
@baixueyu could you address the comment of https://github.com/ceph/ceph/pull/23221#issuecomment-431686595 first ? then it'd be good to merge.

**Comment by baixueyu** [comment]
> @baixueyu
> could you prefix the title of your commit message with the subcomponent your are changing ? see https://github.com/ceph/ceph/blob/master/SubmittingPatches.rst#3-describe-your-changes . in this case, the prefix could be "rgw: ". and the title could be more specific, like the one changed by Casey. so it should look like
> 
> ```
> rgw: delete some unused code about std::regex
> ```
> and you also need to update your Signed-off-by line, to quote your email address with "<>", so it looks like
> 
> ```
> Signed-off-by: Xueyu Bai <baixueyu@inspur.com>
> ```

is it OK now ?

**Comment by baixueyu** [comment]
> @baixueyu please note the first comment of a PR is different from the commit message. could you update the commit message and push it again?

**Comment by baixueyu** [comment]
OK, i will update the commit message and push it again, thanks

**Pull request merged**
