### PR TITLE
test/rgw/notifications: split tests between basic, kafka and amqp

### PR DESCRIPTION
**Pull request by yuvalif**
see comment: https://tracker.ceph.com/issues/64184#note-3

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [x] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [x] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Comment by yuvalif** [comment]
teuthology results: https://pulpito.ceph.com/yuvalif-2024-02-21_12:07:04-rgw:notifications-main-distro-default-smithi/
testing against "main"

**Comment by cbodley** [comment]
this duplicates a lot between the basic/amqp/kafka jobs. currently the tasks are laid out as:
```
~/ceph/qa/suites/rgw/notifications $ ls tasks
+  0-install.yaml  test_amqp.yaml  test_kafka.yaml  test_others.yaml
```
the `+` tells teuthology to concatenate those yaml fragments into a single job. if we changed that to a `%` instead (or just remove the `+`), it would create separate jobs for each. we'd just need to move out the 0-install.yaml so it's included for each job. something like this maybe?
```
rgw/notifications/
                  0-install.yaml
                  1-brokers/
                            %
                            test_amqp.yaml
                            test_kafka.yaml
                            test_basic.yaml
                  (everything else the same)
```

**Comment by yuvalif** [comment]
> this duplicates a lot between the basic/amqp/kafka jobs. currently the tasks are laid out as:
> 
> ```
> ~/ceph/qa/suites/rgw/notifications $ ls tasks
> +  0-install.yaml  test_amqp.yaml  test_kafka.yaml  test_others.yaml
> ```
> 
> the `+` tells teuthology to concatenate those yaml fragments into a single job. if we changed that to a `%` instead (or just remove the `+`), it would create separate jobs for each. we'd just need to move out the 0-install.yaml so it's included for each job. something like this maybe?
> 
> ```
> rgw/notifications/
>                   0-install.yaml
>                   1-brokers/
>                             %
>                             test_amqp.yaml
>                             test_kafka.yaml
>                             test_basic.yaml
>                   (everything else the same)
> ```

i do want a different distro setup for the tests.
currently, i have amqp install script specific to centos, but the other tests can run on any distro
so, instead of writing the amqp install script for ubuntu (https://tracker.ceph.com/issues/63893), i kept amqp to be centos9, and the other tests to be a random distro

**Comment by cbodley** [comment]
could try something like this then?
```
1-brokers/
  amqp/
    +
    centos_latest.yaml
    test_amqp.yaml
  basic/
    +
    supported-random-distro$
    test_basic.yaml
  kafka/
    +
    supported-random-distro$
    test_kafka.yaml
```

**Comment by yuvalif** [comment]
the 3 tests are passing: https://pulpito.ceph.com/yuvalif-2024-02-22_09:59:48-rgw:notifications-main-distro-default-smithi/
the amqp test if failing to cleanup. @TRYTOBE8TME i remember we had this issue i nthe past. can you have a look?

**Comment by yuvalif** [comment]
all pass now: https://pulpito.ceph.com/yuvalif-2024-02-22_17:36:31-rgw:notifications-main-distro-default-smithi/

**Comment by cbodley** [comment]
i rebased https://github.com/ceph/ceph/pull/55657 to pick up these changes, rerunning qa there

**Pull request merged**
