### PR TITLE
mgr/cephadm: spec.virtual_ip  param should be used by the ingress daemon

### PR DESCRIPTION
**Pull request by fmount**
When the ingress spec is built a virtual_ip parameter is provided and it's expected to see the
haproxy instance using the defined value.
The defined VIP is properly configured using the keepalived instance and, as per doc [1],
the ingress should be able to use this value as entrypoint for the haproxy frontend.

[1] https://docs.ceph.com/en/latest/cephadm/services/rgw/#high-availability-service-for-rgw

Fixes: https://tracker.ceph.com/issues/53684
Signed-off-by: Francesco Pantano <fpantano@redhat.com>

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [x] Updates documentation if necessary
  - [x] Includes tests for new functionality or reproducer for bug
- Component impact
  - [x] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by sebastian-philipp** [comment]
would be great, if you could look into writing a unit test similar to 

https://github.com/ceph/ceph/blob/1f28c06f2afbd885a3e0ce527408d4ba5ea7a6c3/src/pybind/mgr/cephadm/tests/test_services.py#L236-L278

to verify this change. Let's avoid future regressions here.

**Comment by fmount** [comment]
> would be great, if you could look into writing a unit test similar to
> 
> https://github.com/ceph/ceph/blob/1f28c06f2afbd885a3e0ce527408d4ba5ea7a6c3/src/pybind/mgr/cephadm/tests/test_services.py#L236-L278
> 
> to verify this change. Let's avoid future regressions here.

ack, I'm going to draft a unit test by EOD

**Review by sebastian-philipp — APPROVED** [review]

**Comment by sebastian-philipp** [comment]
https://pulpito.ceph.com/swagner-2022-01-03_15:37:23-orch:cephadm-wip-swagner-testing-2022-01-03-1230-distro-default-smithi/

* Failures are due to the environment

**Comment by fmount** [comment]
@sebastian-philipp should we backport this PR to pacific?

**Pull request merged**
