### PR TITLE
squid: mgr/cephadm: add some NVMEof gateway fields to be configurable by cephadm

### PR DESCRIPTION
**Pull request by adk3798**
backport tracker: https://tracker.ceph.com/issues/65124

---

backport of https://github.com/ceph/ceph/pull/56369
parent tracker: https://tracker.ceph.com/issues/64821

this backport was staged using ceph-backport.sh version 16.0.0.6848
find the latest version at https://github.com/ceph/ceph/blob/main/src/script/ceph-backport.sh

### CODE REVIEW

**Review by phlogistonjohn — APPROVED** [review]

**Review by epuertat — APPROVED** [review]
LGTM!

**Comment by adk3798** [comment]
jenkins test make check

**Comment by adk3798** [comment]
jenkins test api

**Comment by adk3798** [comment]
jenkins test make check

**Comment by adk3798** [comment]
jenkins test make check

**Comment by adk3798** [comment]
jenkins test make check

**Pull request merged**
