### PR TITLE
os: remove unused btrfs_ioctl.h and tests

### PR DESCRIPTION
**Pull request by cbodley**
remove unused header whose GPL license was potentially problematic

Fixes: https://tracker.ceph.com/issues/68083

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Review by batrick — APPROVED** [review]

**Comment by cbodley** [comment]
https://jenkins.ceph.com/job/ceph-api/81752/
> dashboard.exceptions.DashboardException: Orchestrator is unavailable

**Comment by cbodley** [comment]
jenkins test api

**Review by rzarzynski — APPROVED** [review]

**Comment by ljflores** [comment]
jenkins test make check

**Review by anthonyeleven — APPROVED** [review]

**Comment by amathuria** [comment]
Rados approved: https://tracker.ceph.com/projects/rados/wiki/MAIN#httpstrackercephcomissues68375

**Pull request merged**
