### PR TITLE
mimic: osd: Don't include user changeable flag in snaptrim related assert

### PR DESCRIPTION
**Pull request by dzafman**
http://tracker.ceph.com/issues/39698

### CODE REVIEW

**Comment by athanatos** [comment]
This backport look ok to me, but did we fix the underlying race?

**Comment by dzafman** [comment]
@athanatos I considered it a race with the assert.  I assumed that if snap trim got as far as WaitReservation::react(const SnapTrimReserved&), can_trim() includes nosnaptrim and wouldn't proceed.  Before nosnaptrim was added, the assert was correct.  But afterwards the assert raced with the user setting nosnaptrim.

**Comment by athanatos** [comment]
Ah, so setting CEPH_OSDMAP_NOSNAPTRIM doesn't necessarily cancel an in-progress trim.  Ok, LGTM.

**Comment by yuriw** [comment]
[wip-yuri-testing-2019-06-26-1612-mimic](https://trello.com/c/JaOACLNP/655-wip-yuri-testing-2019-06-26-1612-mimic)

**Pull request merged**
