### PR TITLE
luminous: mon: restrict mon,osd,mds caps by host/network

### PR DESCRIPTION
**Pull request by liewegas**

### CODE REVIEW

**Comment by smithfarm** [comment]
jenkins re-test this please

**Comment by smithfarm** [comment]
Ah, now I see, the commits are cherry-picked from some earlier incarnation of https://github.com/ceph/ceph/pull/23613 (?)

@liewegas You could probably just drop the second cherry-picked line in the commits that have two?

And drop it altogether in the "mark constructors as explicit" commit?

**Comment by smithfarm** [comment]
I'm guessing the build failure might be the same as in the mimic PR: https://github.com/ceph/ceph/pull/23613#issuecomment-417741315

**Comment by neha-ojha** [comment]
retest this please

**Pull request closed without merging**
