### PR TITLE
Narrow journal aio_lock locking scope in write_aio_bl

### PR DESCRIPTION
**Pull request by david-z**
Aio io_submit in write_aio_bl with aio_lock might take long time to return, so write_finish_thread_entry can't process completed aio when io_submit is blocking. Try to narrow aio_lock locking scope to help those completed aio to get processed asap.

Fixes: #12789
Signed-off-by: Zhi Zhang zhangz.david@outlook.com

### CODE REVIEW

**Comment by david-z** [comment]
@yuyuyu101

Haomai, can you pls take a look or schedule some one to do? Thanks.

**Comment by yuyuyu101** [comment]
LGTM
I think we also could avoid extra new:
line 1414: iovec *iov = new iovec[max];

**Comment by david-z** [comment]
@yuyuyu101 

Sorry, can you be more specific on avoiding extra new at line 1414?
I think bl.splice will reduce the length of original bl. If the length is still large than 0, another aio should be generated. And we have to extra new iovec with current size and pass iovec to this aio because aio.iov need to hold the pointer of this iovec until aio is done and freed.

**Comment by yuyuyu101** [comment]
never mind, it's ok for this PR to reduce lock scope

**Comment by david-z** [comment]
thanks.

**Comment by yuyuyu101** [comment]
LGTM

**Pull request merged**
