### PR TITLE
fix "pg ls" with states of "recovering" and/or "repair"

### PR DESCRIPTION
**Pull request by tchaikov**

### CODE REVIEW

**Comment by tchaikov** [comment]
thanks @jecluis ! what if the "recovery" state has never worked before? the `pg_string_state()` function was introduced in 61378f25, and the "pg ls*" commands were added in

- "pg ls-by-pool" 25d98373
- "pg ls-by-primary" 4be91c63
- "pg ls-by-osd" 39e26401
- "pg ls" a1f634b5

all of above commands are using "recovery" in their command spec. 

but if you think that there is chance that our user is using "recovery" in his/her script but the script never gets a chance to pass "recovery" to any of these commands, and hence survives this assertion. i agree these commands should also go though the "deprecate", "obsolete" process. and i will wait until your change lands on the git repo, then update this pull request accordingly.

**Comment by gregsfortytwo** [comment]
@jecluis, this code is pretty new (January) and I don't think it's ever functioned correctly (thus this bug), so shouldn't we be okay just changing it?

Reviewed-by: from me as it currently stands. :)

**Comment by liewegas** [comment]
yeah, lgtm

**Comment by jecluis** [comment]
this fell through the cracks; yeah, given this is a new set of commands it does look good.  maybe just worth mentioning on the pending release notes if this went into hammer prior to its release.

**Comment by tchaikov** [comment]
they are in hammer. @jecluis will update the pending release notes .

**Comment by tchaikov** [comment]
revise the pending release notes at #4643

**Pull request merged**
