### PR TITLE
nautilus: qa/cephfs: remove use of CentOS 7 kernel testing builds

### PR DESCRIPTION
**Pull request by ajarr**
... that is no longer available in shaman.

This is a nautilus only fix as master, and octopus already don't
use CentOS 7 kernel testing builds. They use CentOS 8 kernel testing
builds instead.

Fixes: https://tracker.ceph.com/issues/47642
Signed-off-by: Ramana Raja <rraja@redhat.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by ajarr** [comment]
This PR is an alternate fix for https://tracker.ceph.com/issues/47642
The other approach is also in review, https://github.com/ceph/ceph/pull/37437

**Comment by ajarr** [comment]
Testing to make sure that centos 7 kernel testing builds aren't used on clients,
teuthology-suite -v --ceph-repo https://github.com/ceph/ceph-ci.git --suite-repo https://github.com/ajarr/ceph --suite-branch wip-47642-remove-centos7-testing-kernel  -c $CEPH_BRANCH -m $MACHINE_NAME -s kcephfs -p 50 -e $CEPH_QA_MAIL --filter-all thrash,workloads/kclient_workunit_suites_iozone,bluestore-bitmap

Results, http://pulpito.front.sepia.ceph.com/rraja-2020-10-01_12:50:14-kcephfs-wip-ajarr-nautilus-47642-update-1-distro-basic-smithi/

**Review by batrick — CHANGES_REQUESTED** [review]
I don't remember why we need to use the testing kernel in the `multimds:verify` suite. I couldn't find an explanation from the commit history. I _think_ we could fix it to have `verify/mount/` be changed to a symlink to `.qa/cephfs/mount/`.

We can't remove rhel/centos_latest from the supported distros. That's not the issue. We need to remove instead `qa/cephfs/mount/kclient/overrides/distro/random`.

**Review by batrick — APPROVED** [review]

**Comment by ajarr** [comment]
Testing to make sure that  kernel testing builds aren't used when scheduling a particular kcephfs suite workload (please see --filter-all arguments of the following command),
$ teuthology-suite -v --ceph-repo https://github.com/ceph/ceph-ci.git --suite-repo https://github.com/ajarr/ceph --suite-branch wip-47642-remove-centos7-testing-kernel -c $CEPH_BRANCH -m $MACHINE_NAME -s kcephfs -p 50 -e $CEPH_QA_MAIL --filter-all thrash,workloads/kclient_workunit_suites_iozone,bluestore-bitmap

Jobs are in waiting here,
http://pulpito.front.sepia.ceph.com/rraja-2020-10-01_17:03:16-kcephfs-wip-ajarr-nautilus-47642-update-1-distro-basic-smithi/

**Comment by batrick** [comment]
Testing looks good. Merging.

**Comment by smithfarm** [comment]
@ajarr The `nautilus: ` prefix is needed in the PR title only (to make it obvious when perusing https://github.com/ceph/ceph/pulls which PRs are targeting stable branches), but not in the commit title.

I suppose it does not do any harm to put this prefix in the commit title. On the other hand, it does not serve any useful purpose to do it.

**Comment by ajarr** [comment]
> @ajarr The `nautilus: ` prefix is needed in the PR title only (to make it obvious when perusing https://github.com/ceph/ceph/pulls which PRs are targeting stable branches), but not in the commit title.
> 
> I suppose it does not do any harm to put this prefix in the commit title. On the other hand, it does not serve any useful purpose.

Got it.

**Pull request merged**
