### PR TITLE
rgw: remove trailing :port from host for purposes of subdomain matching

### PR DESCRIPTION
**Pull request by robbat2**
http://tracker.ceph.com/issues/13224

### CODE REVIEW

**Comment by dachary** [comment]
@robbat2 could you please 

<pre>
git cherry-pick -x abe4ec293d08b0314bf5c081ace2456073f3a22c
</pre>
note the **-x** that will include a reference to the original commit, which is convenient to figure out where the backport comes from.

Thanks !

**Comment by robbat2** [comment]
@dachary done

**Comment by yehudasa** [comment]
@robbat2 @dachary there's a regression due to this commit, we'll need also to pull in the fix to issue 13239.

**Comment by dachary** [comment]
@yehudasa ack, setting DNM for now

**Comment by robbat2** [comment]
@yehudasa I added your commit to fix it per issue 13239.

**Comment by dachary** [comment]
@yehudasa does this backport look good to merge ? It passed a run of the hammer rgw suite ( see http://tracker.ceph.com/issues/13356#note-5 for details ).

**Pull request merged**
