### PR TITLE
 tools/rest_bench.cc: bucket is not mandatory bc we have a default one

### PR DESCRIPTION
**Pull request by hjwsm1989**
And fix typo of https protocol.

 Signed-off-by: huangjun <hjwsm1989@gmail.com>

### CODE REVIEW

**Comment by tchaikov** [comment]
@hjwsm1989 i am not the best person to review this change. probably @yehudasa could give more insights on it.

**Comment by tchaikov** [comment]
@hjwsm1989 

- would you mind removing the https protocol fix from commit 5ed8613 ?
- i am not sure if we want a default one or not. if we do, could also remove either the line which set the default value at https://github.com/hjwsm1989/ceph/commit/5ed8613bdbcad32f84fa381d40738b8414017490#diff-dd76bf654ce550a2c7b66c2bc1a9430dR670 or https://github.com/hjwsm1989/ceph/commit/5ed8613bdbcad32f84fa381d40738b8414017490#diff-dd76bf654ce550a2c7b66c2bc1a9430dR766 @yehudasa , could you advise which way we should go with?
- the title of commit a64bbab does not help: would use use a more informative way to explain what you fix in that commit?

**Comment by hjwsm1989** [comment]
@tchaikov 
a do you mean use git reset or git revert to remove the https modify, and then use git rebase master?
b what title of commit a64bbab should be?

**Comment by tchaikov** [comment]
> a do you mean use git reset or git revert to remove the https modify, and then use git rebase master?

i guess the https change can not be "git revert"'ed. it lives with another change. you can either 
1. remove that change by editing the code. 
1. and create a new commit on top of your existing changes
1. squash the new commit with the commit which has the https fix

or start with a fresh new branch.

> b what title of commit a64bbab should be?

it's now "tools/rest_bench.cc: "

could be "rest_bench: drain the work queue to fix a crash"

**Comment by hjwsm1989** [comment]
@tchaikov the problem related to no --run_name was resolved in new clean_up api.
so there is no need to change it.
here are two main commits: 
a) bucketname is not mandatory
b) the rest-bench process will corupt in some cases, for which we don't stop the threadpool

**Comment by tchaikov** [comment]
tested. before this change, when 2 second elapses:
```
$ ./rest-bench -t 1 --seconds 2 --api-host=localhost:8000  --access-key=0555b35654ad1656d804 --secret=h7GhxuBLTrlhVUyxSPUKUV8r/2EI4ngqJxD7iBdBYLhw
luN30JaT3Q== --bucket=foo write
host=localhost:8000
Maintaining 1 concurrent writes of 4194304 bytes for up to 2 seconds
Object prefix: benchmark_data_gen8_17629
  sec Cur ops   started  finished  avg MB/s  cur MB/s  last lat   avg lat
    0       0         0         0         0         0         -         0
    1       1         3         2   7.99767         8  0.571909   0.42269
    2       1         4         3   5.99879         4  0.574656  0.473345
    3       1         5         4   5.33242         4   1.25541  0.668863
    4       1         5         4   3.99938         0         -  0.668863
Total time run:         4.229827
Total writes made:      5
Write size:             4194304
Bandwidth (MB/sec):     4.73
Stddev Bandwidth:       2.31
Max bandwidth (MB/sec): 8
Min bandwidth (MB/sec): 4
Average IOPS:           1
Stddev IOPS:            1
Max IOPS:               32767
Min IOPS:               0
Average Latency:        0.846
Stddev Latency:         0.535
Max latency:            1.55
Min latency:            0.273
common/WorkQueue.cc: In function 'virtual ThreadPool::~ThreadPool()' thread 7f07c5b557c0 time 2015-07-16 11:45:34.075752
common/WorkQueue.cc: 68: FAILED assert(_threads.empty())
 ceph version Development (no_version)
 1: (ceph::__ceph_assert_fail(char const*, char const*, int, char const*)+0x80) [0x85161d]
 2: (ThreadPool::~ThreadPool()+0x54) [0x849b52]
 3: (RESTDispatcher::~RESTDispatcher()+0x2f) [0x832e3d]
 4: (main()+0xa3b) [0x82fd27]
 5: (__libc_start_main()+0xf0) [0x7f07c36e7850]
 6: (_start()+0x29) [0x82ea69]
 NOTE: a copy of the executable, or `objdump -rdS <executable>` is needed to interpret this.
2015-07-16 11:45:34.077306 7f07c5b557c0 -1 common/WorkQueue.cc: In function 'virtual ThreadPool::~ThreadPool()' thread 7f07c5b557c0 time 2015-07-16 11:45:34.075752
common/WorkQueue.cc: 68: FAILED assert(_threads.empty())

 ceph version Development (no_version)
 1: (ceph::__ceph_assert_fail(char const*, char const*, int, char const*)+0x80) [0x85161d]
 2: (ThreadPool::~ThreadPool()+0x54) [0x849b52]
 3: (RESTDispatcher::~RESTDispatcher()+0x2f) [0x832e3d]
 4: (main()+0xa3b) [0x82fd27]
 5: (__libc_start_main()+0xf0) [0x7f07c36e7850]
 6: (_start()+0x29) [0x82ea69]
 NOTE: a copy of the executable, or `objdump -rdS <executable>` is needed to interpret this.

--- begin dump of recent events ---
   -22> 2015-07-16 11:45:27.267606 7f07c5b557c0  5 asok(0x3e9fc60) register_command perfcounters_dump hook 0x3e71160
   -21> 2015-07-16 11:45:27.267647 7f07c5b557c0  5 asok(0x3e9fc60) register_command 1 hook 0x3e71160
   -20> 2015-07-16 11:45:27.267653 7f07c5b557c0  5 asok(0x3e9fc60) register_command perf dump hook 0x3e71160
   -19> 2015-07-16 11:45:27.267659 7f07c5b557c0  5 asok(0x3e9fc60) register_command perfcounters_schema hook 0x3e71160
   -18> 2015-07-16 11:45:27.267663 7f07c5b557c0  5 asok(0x3e9fc60) register_command 2 hook 0x3e71160
   -17> 2015-07-16 11:45:27.267667 7f07c5b557c0  5 asok(0x3e9fc60) register_command perf schema hook 0x3e71160
   -16> 2015-07-16 11:45:27.267674 7f07c5b557c0  5 asok(0x3e9fc60) register_command perf reset hook 0x3e71160
   -15> 2015-07-16 11:45:27.267680 7f07c5b557c0  5 asok(0x3e9fc60) register_command config show hook 0x3e71160
   -14> 2015-07-16 11:45:27.267687 7f07c5b557c0  5 asok(0x3e9fc60) register_command config set hook 0x3e71160
   -13> 2015-07-16 11:45:27.267693 7f07c5b557c0  5 asok(0x3e9fc60) register_command config get hook 0x3e71160
   -12> 2015-07-16 11:45:27.267699 7f07c5b557c0  5 asok(0x3e9fc60) register_command config diff hook 0x3e71160
   -11> 2015-07-16 11:45:27.267704 7f07c5b557c0  5 asok(0x3e9fc60) register_command log flush hook 0x3e71160
   -10> 2015-07-16 11:45:27.267708 7f07c5b557c0  5 asok(0x3e9fc60) register_command log dump hook 0x3e71160
    -9> 2015-07-16 11:45:27.267716 7f07c5b557c0  5 asok(0x3e9fc60) register_command log reopen hook 0x3e71160
    -8> 2015-07-16 11:45:27.280336 7f07c5b557c0  5 asok(0x3e9fc60) init /home/kefu/dev/ceph/src/out/client.admin.17629.asok
    -7> 2015-07-16 11:45:27.280349 7f07c5b557c0  5 asok(0x3e9fc60) bind_and_listen /home/kefu/dev/ceph/src/out/client.admin.17629.asok
    -6> 2015-07-16 11:45:27.280397 7f07c5b557c0  5 asok(0x3e9fc60) register_command 0 hook 0x3e713f0
    -5> 2015-07-16 11:45:27.280409 7f07c5b557c0  5 asok(0x3e9fc60) register_command version hook 0x3e713f0
    -4> 2015-07-16 11:45:27.280414 7f07c5b557c0  5 asok(0x3e9fc60) register_command git_version hook 0x3e713f0
    -3> 2015-07-16 11:45:27.280419 7f07c5b557c0  5 asok(0x3e9fc60) register_command help hook 0x3e71730
    -2> 2015-07-16 11:45:27.280424 7f07c5b557c0  5 asok(0x3e9fc60) register_command get_command_descriptions hook 0x3e71660
    -1> 2015-07-16 11:45:27.280474 7f07bce84700  5 asok(0x3e9fc60) entry start
     0> 2015-07-16 11:45:34.077306 7f07c5b557c0 -1 common/WorkQueue.cc: In function 'virtual ThreadPool::~ThreadPool()' thread 7f07c5b557c0 time 2015-07-16 11:45:34.075752
common/WorkQueue.cc: 68: FAILED assert(_threads.empty())

 ceph version Development (no_version)
 1: (ceph::__ceph_assert_fail(char const*, char const*, int, char const*)+0x80) [0x85161d]
 2: (ThreadPool::~ThreadPool()+0x54) [0x849b52]
 3: (RESTDispatcher::~RESTDispatcher()+0x2f) [0x832e3d]
 4: (main()+0xa3b) [0x82fd27]
 5: (__libc_start_main()+0xf0) [0x7f07c36e7850]
 6: (_start()+0x29) [0x82ea69]
 NOTE: a copy of the executable, or `objdump -rdS <executable>` is needed to interpret this.
//// and more bt and log
```
after this change, it takes more time to wait for the work q to drain, and worker thread to join, but no crash any more:
```
$ ./rest-bench -t 5 --seconds 2 --api-host=localhost:8000  --access-key=0555b35654ad1656d804 --secret=h7GhxuBLTrlhVUyxSPUKUV8r/2EI4ngqJxD7iBdBYLhwluN30JaT3Q== --bucket=buckA write
host=localhost:8000
Maintaining 5 concurrent writes of 4194304 bytes for up to 2 seconds
Object prefix: benchmark_data_gen8_42448
  sec Cur ops   started  finished  avg MB/s  cur MB/s  last lat   avg lat
    0       5         5         0         0         0         -         0
    1       5         5         0         0         0         -         0
    2       5         6         1   1.96419         2   1.98384   1.98384
    3       5         6         1   1.31728         0         -   1.98384
    4       5         7         2   1.98184         2   3.11732   2.55058
Total time run:         4.685195
Total writes made:      7
Write size:             4194304
Bandwidth (MB/sec):     5.98
Stddev Bandwidth:       0
Max bandwidth (MB/sec): 2
Min bandwidth (MB/sec): 2
Average IOPS:           1
Stddev IOPS:            0
Max IOPS:               32766
Min IOPS:               -168189936
Average Latency:        3.31
Stddev Latency:         1.32
Max latency:            4.68
Min latency:            1.57
```

**Pull request merged**
