### PR TITLE
Objecter: fix bus about objecter.

### PR DESCRIPTION
**Pull request by majianpeng**

### CODE REVIEW

**Comment by liewegas** [comment]
Reviewed-by: 

Good fixes!

**Comment by liewegas** [comment]
I got several librados api tests failing iwth -ECANCELED on my qa run...

/a/sage-2015-08-29_05:13:00-rados-wip-sage-testing---basic-multi 1037676 1037713 1037810

probably running ceph_test_rados_api_watch_notify in a loop will reproduce this?  with some light osd thrashing (mark osds in out, restart daemons)?

**Comment by majianpeng** [comment]
@liewegas . Update and please review again. Thanks!

**Comment by liewegas** [comment]
sorry, i missed this update.. will catch it in my next run

**Pull request merged**
