### PR TITLE
luminous: mon: more aggressively convert crush rulesets -> distinct rules

### PR DESCRIPTION
**Pull request by tchaikov**
backport of #17508

### CODE REVIEW

**Comment by liewegas** [comment]
needs rebase.. there's a build error

**Comment by tchaikov** [comment]
retest this please.

**Comment by theanalyst** [comment]
this is stil causing a build error, there is one more place where the ruleset/rules change needs to be made
```
/ssd/builds/cpp/ceph_cmake_new/src/osd/OSDMap.cc:4046:31: error: ‘crush_ruleset_in_use’ was not declared in this scope
```

**Comment by tchaikov** [comment]
retest this please.

**Comment by tchaikov** [comment]
rebased against master and fixed the build.

**Comment by liewegas** [comment]
http://pulpito.ceph.com/sage-2017-10-26_18:02:19-rados-wip-sage-testing-2017-10-26-1137-distro-basic-smithi/

**Pull request merged**
