### PR TITLE
crimson: allow pg creation to be canceled if pool is removed

### PR DESCRIPTION
**Pull request by athanatos**
<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by liu-chunmei** [comment]
@athanatos which commit do you use? I checkout the latest main and apply this PR and the other #48353, ./bin/ceph_test_rados_api_aio_pp test case PoolEIOFlag run a long time, can't return, I never meet it before.  I check the background osd log, it seems it still handle the seastore omap cache cleaner and client request operation, Will try more times to see.

**Comment by liu-chunmei** [comment]
@athanatos which commit do you use? I checkout the latest main and apply this PR and the other https://github.com/ceph/ceph/pull/48353, ./bin/ceph_test_rados_api_aio_pp test case PoolEIOFlag run a long time, can't return, I never meet it before. I check the background osd log, it seems it still handle the seastore omap cache cleaner and client request operation, I tested 2 times, every time meet this.

I try main branch again, it seems the main branch has this issue, not your PR bugs, but I don't know which PR bring this bug to main branch.

**Review by liu-chunmei — APPROVED** [review]
LGTM, but I can't verify it since main branch has another hang yet.

**Comment by athanatos** [comment]
@liu-chunmei Thanks.  At the moment I'm focused on getting the crimson-rados suite to pass on alienstore, I'll switch to seastore once it passes reliably.

**Comment by liu-chunmei** [comment]
@athanatos I think it is my fault, I used a new server to do test, my old server I always worked on was corrupted by some mistake yesterday, I got hang on that new server, but after I recovered my old server, I tested it again, then the hang disappear, I have verified the PR and it works by running the test cases several times within which I always got hang before.  I don't know why my new server has problem.

**Comment by athanatos** [comment]
Oh, cool!  No worries, you're likely hitting another bug -- we'll get to it!

**Pull request merged**
