### PR TITLE
osd/PG.h: change PGRecoveryStats struct to class

### PR DESCRIPTION
**Pull request by stiopaa1**
Signed-off-by: Michal Jarzabek stiopa@gmail.com

### CODE REVIEW

**Comment by yuriw** [comment]
test this please

**Comment by dachary** [comment]
jenkins test this please (no logs)

**Comment by dachary** [comment]
jenkins test this please (eio now ignored in master)

**Comment by tchaikov** [comment]
http://pulpito.ceph.com/kchai-2016-11-22_09:44:32-rados-wip-kefu-testing---basic-mira/

**Pull request merged**
