### PR TITLE
osd: use separate waitlist for scrub

### PR DESCRIPTION
**Pull request by liewegas**

### CODE REVIEW

**Comment by liewegas** [comment]
testing this in isolation

**Comment by liewegas** [comment]
http://pulpito.ceph.com/sage-2017-02-01_01:48:13-rados-wip-scrub-waitlist---basic-smithi/

**Comment by liewegas** [comment]
teuthology-2017-01-31_16:06:03-upgrade:firefly-x-hammer---basic-smithi

**Comment by athanatos** [comment]
LGTM

**Pull request merged**
