### PR TITLE
qa: whitelist trim error during powercycle tests

### PR DESCRIPTION
**Pull request by batrick**
Fixes: http://tracker.ceph.com/issues/20566

Signed-off-by: Patrick Donnelly <pdonnell@redhat.com>

### CODE REVIEW

**Comment by batrick** [comment]
http://pulpito.front.sepia.ceph.com:80/pdonnell-2017-07-25_20:23:15-powercycle-wip-pdonnell-testing-20170725-distro-basic-smithi/

**Comment by tchaikov** [comment]
all tests failed due to
```
2017-07-25T21:54:34.107 INFO:teuthology.orchestra.run.smithi012:Running: 'sudo adjust-ulimits ceph-coverage /home/ubuntu/cephtest/archive/coverage ceph-authtool --create-keyring /e
tc/ceph/ceph.keyring'
2017-07-25T21:54:34.238 INFO:teuthology.orchestra.run.smithi012.stderr:Schema is missing legacy field 'max_ratio_caps_per_client'
2017-07-25T21:54:34.239 INFO:teuthology.orchestra.run.smithi012.stderr:/home/jenkins-build/build/workspace/ceph-dev-new-build/ARCH/x86_64/AVAILABLE_ARCH/x86_64/AVAILABLE_DIST/centos7/DIST/centos7/MACHINE_SIZE/huge/release/12.1.1-578-gbc7dc4a/rpm/el7/BUILD/ceph-12.1.1-578-gbc7dc4a/src/common/config.cc: In function 'void md_config_t::validate_schema()' thread 7f7549132180 time 2017-07-25 21:54:34.237569
2017-07-25T21:54:34.239 INFO:teuthology.orchestra.run.smithi012.stderr:/home/jenkins-build/build/workspace/ceph-dev-new-build/ARCH/x86_64/AVAILABLE_ARCH/x86_64/AVAILABLE_DIST/centos7/DIST/centos7/MACHINE_SIZE/huge/release/12.1.1-578-gbc7dc4a/rpm/el7/BUILD/ceph-12.1.1-578-gbc7dc4a/src/common/config.cc: 174: FAILED assert(false)
2017-07-25T21:54:34.240 INFO:teuthology.orchestra.run.smithi012.stderr: ceph version 12.1.1-578-gbc7dc4a (bc7dc4a9c51e999063eb7650db25b100999931a5) luminous (rc)
2017-07-25T21:54:34.240 INFO:teuthology.orchestra.run.smithi012.stderr: 1: (ceph::__ceph_assert_fail(char const*, char const*, int, char const*)+0x110) [0x7f753eb2ef10]
2017-07-25T21:54:34.240 INFO:teuthology.orchestra.run.smithi012.stderr: 2: (md_config_t::validate_schema()+0x1aa) [0x7f753ed8c2fa]
2017-07-25T21:54:34.240 INFO:teuthology.orchestra.run.smithi012.stderr: 3: (md_config_t::md_config_t(bool)+0x225eb) [0x7f753edb3d7b]
2017-07-25T21:54:34.241 INFO:teuthology.orchestra.run.smithi012.stderr: 4: (CephContext::CephContext(unsigned int, int)+0x62) [0x7f753ed635d2]
2017-07-25T21:54:34.241 INFO:teuthology.orchestra.run.smithi012.stderr: 5: (common_preinit(CephInitParameters const&, code_environment_t, int, char const*)+0xb2) [0x7f753ed5d182]
2017-07-25T21:54:34.241 INFO:teuthology.orchestra.run.smithi012.stderr: 6: (global_pre_init(std::vector<char const*, std::allocator<char const*> >*, std::vector<char const*, std::allocator<char const*> >&, unsigned int, code_environment_t, int, char const*)+0x91) [0x7f754915ba91]
2017-07-25T21:54:34.241 INFO:teuthology.orchestra.run.smithi012.stderr: 7: (global_init(std::vector<char const*, std::allocator<char const*> >*, std::vector<char const*, std::allocator<char const*> >&, unsigned int, code_environment_t, int, char const*, bool)+0x74) [0x7f754915d204]
2017-07-25T21:54:34.241 INFO:teuthology.orchestra.run.smithi012.stderr: 8: (main()+0x10a) [0x7f7549156ffa]
2017-07-25T21:54:34.241 INFO:teuthology.orchestra.run.smithi012.stderr: 9: (__libc_start_main()+0xf5) [0x7f753d803b35]
2017-07-25T21:54:34.241 INFO:teuthology.orchestra.run.smithi012.stderr: 10: (()+0x9ff0) [0x7f7549158ff0]
```

**Comment by batrick** [comment]
Yup thanks @tchaikov, there was a bad PR in the test branch. I'll retest soon.

**Comment by batrick** [comment]
http://pulpito.front.sepia.ceph.com:80/pdonnell-2017-07-26_18:03:00-powercycle-wip-pdonnell-testing-20170725-distro-basic-smithi/

**Comment by batrick** [comment]
This should be `MDS_TRIM` (`HEALTH_` is stripped in `MMDSBeacon.h`). Example:

`2017-07-26 22:16:23.111589 mon.a mon.0 172.21.15.64:6789/0 2351 : cluster [WRN] Health check failed: 1 MDSs behind on trimming (MDS_TRIM)`

**Comment by batrick** [comment]
http://pulpito.front.sepia.ceph.com/pdonnell-2017-07-27_23:04:42-powercycle-wip-pdonnell-testing-20170727-distro-basic-smithi/

**Comment by batrick** [comment]
Test showing whitelist working properly: /ceph/teuthology-archive/pdonnell-2017-07-27_23:04:42-powercycle-wip-pdonnell-testing-20170727-distro-basic-smithi/1453905/teuthology.log

````
$ find -name ceph.log.gz -exec zgrep -H TRIM {} +
./1453905/remote/smithi197/log/ceph.log.gz:2017-07-27 23:52:56.231914 mon.a mon.0 172.21.15.197:6789/0 546 : cluster [WRN] Health check failed: 1 MDSs behind on trimming (MDS_TRIM)
./1453905/remote/smithi197/log/ceph.log.gz:2017-07-27 23:52:56.231914 mon.a mon.0 172.21.15.197:6789/0 546 : cluster [WRN] Health check failed: 1 MDSs behind on trimming (MDS_TRIM)
./1453905/remote/smithi197/log/ceph.log.gz:2017-07-27 23:52:56.231914 mon.a mon.0 172.21.15.197:6789/0 546 : cluster [WRN] Health check failed: 1 MDSs behind on trimming (MDS_TRIM)
./1453905/remote/smithi197/log/ceph.log.gz:2017-07-27 23:52:59.443112 mon.a mon.0 172.21.15.197:6789/0 558 : cluster [INF] Health check cleared: MDS_TRIM (was: 1 MDSs behind on trimming)
./1453905/remote/smithi197/log/ceph.log.gz:2017-07-27 23:52:59.443112 mon.a mon.0 172.21.15.197:6789/0 558 : cluster [INF] Health check cleared: MDS_TRIM (was: 1 MDSs behind on trimming)
./1453905/remote/smithi197/log/ceph.log.gz:2017-07-27 23:52:59.443112 mon.a mon.0 172.21.15.197:6789/0 558 : cluster [INF] Health check cleared: MDS_TRIM (was: 1 MDSs behind on trimming)
````

**Pull request merged**
