### PR TITLE
Changes related to command line parsing, fix for Bug # 2862

### PR DESCRIPTION
**Pull request by knrajnambiar76**
The changes are to fix Bug # 2862
-- It will identify any missing option values and will also give better user friendly error messages
-- Did some other optimization for logging cli errors

Output of some wrong arguments with these changes
===========================================
ubuntu@Host-CephAdmin:~/myrepo/ceph/src/.libs$ ./rbd create rbd/rbd_img3 --size 10 --order 0
rbd: order must be between 12 (4 KB) and 25 (32 MB)

ubuntu@Host-CephAdmin:~/myrepo/ceph/src/.libs$ ./rbd create --size --image rbd_10
rbd: Missing option value

ubuntu@Host-CephAdmin:~/myrepo/ceph/src/.libs$ ./rbd create --image rbd_img4 --size
Option --size requires an argument.

ubuntu@Host-CephAdmin:~/myrepo/ceph/src/.libs$ ./rbd create rbd/img_abc --size 10g
rbd: The option value '10g' is invalid

ubuntu@Host-CephAdmin:~/myrepo/ceph/src/.libs$ ./rbd create rbd/img_abc --size 10.12
rbd: The option value '10.12' is invalid

ubuntu@Host-CephAdmin:~/myrepo/ceph/src/.libs$ ./rbd create rbd/img_abc --size 10#@#
rbd: The option value '10#@#' is invalid

ubuntu@Host-CephAdmin:~/myrepo/ceph/src/.libs$ ./rbd create rbd/rbd_img2 --size 10240000000000000000
rbd: The option value '10240000000000000000' seems to be invalid

### CODE REVIEW

**Comment by dachary** [comment]
Nice ! Could you please git --amend your commit message with a message that looks like
<pre>
rbd: create command throws inappropriate error messages 

(explain what the fix is about).

Fixes: #2862

Signed-off-by: ....
</pre>
It would be good to split the fix in two: one for rbd and one for common: where it fixes the parsing.

**Comment by knrajnambiar76** [comment]
Hi,

I have done the changes as suggested by you.

Thanks & Rgds
Rajesh

**Comment by dachary** [comment]
@knrajnambiar76 nice :-) Could you please squash the commits together ? At the moment you have 3 commits including a merge, it's probably not what you intended.

**Comment by knrajnambiar76** [comment]
Sorry to ask this question, being new to Git not sure how can I squash the
commits in this case.
Can you please help me out.

If I give below command from my repository
git rebase -i HEAD~1

It gives below output

pick b815cf6 mds: pin inode when openning snap parent
pick c173cea mds: disable snapshot rstat temporarily
pick 142a99d mds: fix purging stale snapshot dentries
pick 635d792 mds: purge stale snap data in CInode with snaprealm
pick 7ae66c4 mds: fix fnode.snap_purged_thru check
pick 7f2ddf5 mds: check snapset in journal_cow_dentry()
pick 1bb4a9d mds: fix purging snapshotted stray inode
pick 1956e68 mds: pick head inode when caps follows is zero
pick 0dfab5d mds: don't crash MDS when snapshot data not found
pick 2395ee1 mds: skip inode that is being puring when opening snap past
parent
pick abed3e9 rbd: create command throws inappropriate error messages Fixes:
#2862
pick 23d29a1 Changes related to command line parsing, fix for Bug # 2862

**Comment by knrajnambiar76** [comment]
Hi,

I created a new pull request (#4156) with the changes suggested by you.

Thanks & Rgds
Rajesh

**Pull request closed without merging**
