### PR TITLE
nautilus: mgr/volumes: add CephFS subvolumes library

### PR DESCRIPTION
**Pull request by ajarr**
Fixes:
https://tracker.ceph.com/issues/39934
https://tracker.ceph.com/issues/40157
https://tracker.ceph.com/issues/40158
https://tracker.ceph.com/issues/40321
https://tracker.ceph.com/issues/40338

### CODE REVIEW

**Comment by smithfarm** [comment]
@ajarr I just noticed you prefixed the PR title with "WIP", which (I guess?) means you're still working on it and more commits will be added?

**Comment by batrick** [comment]
@smithfarm yes, there are a few more things to backport.

**Comment by ajarr** [comment]
@smithfarm, added DNM label to make things clear. sorry about the confusion.

**Comment by ajarr** [comment]
@batrick , PTAL

**Comment by batrick** [comment]
Okay with me. Let's see how it does in QA but I don't expect any real issues since @vshankar 's test revamp is not yet merged.

**Comment by yuriw** [comment]
[wip-yuri6-testing-2019-06-12-1556-nautilus](https://trello.com/c/QgifdsCI/639-wip-yuri6-testing-2019-06-12-1556-nautilus)

**Comment by batrick** [comment]
#28407 and #27856 will be added to this PR and then it's done.

**Comment by ajarr** [comment]
@vshankar can you check if the rewrite test commits are good?

**Comment by ajarr** [comment]
@batrick  can I backport this PR as well, https://github.com/ceph/ceph/pull/27374

**Comment by smithfarm** [comment]
Commits got added after start of integration testing. Adding DNM label to make sure it doesn't get merged by mistake.

**Comment by batrick** [comment]
@ajarr yes, go ahead.

**Comment by batrick** [comment]
>  [wip-yuri6-testing-2019-06-12-1556-nautilus](https://trello.com/c/QgifdsCI/639-wip-yuri6-testing-2019-06-12-1556-nautilus)

These test results can be ignored. This PR needs to be run again in the next batch.

**Comment by yuriw** [comment]
[wip-yuri5-testing-2019-06-13-1941-nautilus](https://trello.com/c/MOtW7wIA/641-wip-yuri5-testing-2019-06-13-1941-nautilus)

**Pull request merged**
