### PR TITLE
mgr/dashboard: rgw daemon list: add realm column

### PR DESCRIPTION
**Pull request by alfonsomthd**
- Some refactoring and cleanup.
Screenshot from 2021-11-17 09-22-30

Fixes: https://tracker.ceph.com/issues/53301
Signed-off-by: Alfonso Martínez <almartin@redhat.com>

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
- Component impact
  - [x] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [x] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests
- Teuthology
  - [ ] Completed teuthology run
  - [x] No teuthology test necessary (e.g., documentation)

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by sebastian-philipp** [comment]
AFAIK There is a hirachy: realm -> zonegroup -> zone . See https://github.com/rook/rook/blob/master/design/ceph/object/ceph-multisite-overview.md . Makes sense to order those columns accordingly?

**Comment by alfonsomthd** [comment]
> AFAIK There is a hirachy: realm -> zonegroup -> zone . See https://github.com/rook/rook/blob/master/design/ceph/object/ceph-multisite-overview.md . Makes sense to order those columns accordingly?

@sebastian-philipp I went for the reverse hierarchy due to:
1. When single-site (no multi-site) there is no realm info so I put that column at the end.
2. From quincy CDS feedback we realized that zone selection is what it's more interesting to the user so I put that column first.

That said, columns can be re-ordered following consensus @epuertat thoughts?

**Comment by epuertat** [comment]
@alfonsomthd @sebastian-philipp this is an interesting UX (almost epistemological) debate. One logical approach would be to start from the top-level instance to the low level one (e.g.: the [Reverse Domain Name](https://en.wikipedia.org/wiki/Reverse_domain_name_notation) convention in Java's [UTI's](https://en.wikipedia.org/wiki/Uniform_Type_Identifier): `org.xml.sax.helpers`). However usually [the quantify of information](https://en.wikipedia.org/wiki/Quantities_of_information) is higher in the finer grained levels (as in DNS: `service.example.com` and not `com.example.service`).

For left-to-right reading languages (yes, we support translations to languages with other text directionalities like Japanese, Persian, etc., but the layout is not adapted accordingly), IMHO we should put he highest quantity of info in the left-most part of the screen, so as you're reading to the right side the information becomes more sparse. There are exceptions to this, but in general this should work ok for most pages.

What do you folks (@ceph/dashboard ) think?

**Comment by sebastian-philipp** [comment]
I'm ok with anything as long as it's consistent.

**Review by avanthakkar — APPROVED** [review]
LGTM!

**Review by nizamial09 — APPROVED** [review]
LGTM

> What do you folks (@ceph/dashboard ) think?

The current approach looks good to me.

**Review by Waadkh7 — APPROVED** [review]

**Comment by alfonsomthd** [comment]
jenkins test dashboard

**Comment by alfonsomthd** [comment]
jenkins test dashboard cephadm

**Comment by alfonsomthd** [comment]
jenkins test dashboard

**Pull request merged**
