### PR TITLE
tools/crushdiff: new tool to test crushmap change

### PR DESCRIPTION
**Pull request by trociny**
A tool to test the effect (number of pgs, objects, bytes moved)
of a crushmap change. This is a wrapper around osdmaptool, hardly
relying on its --test-map-pgs-dump option to get the list of
changed pgs.  Additionally it uses pg stats to calculate the
numbers of objects and bytes moved.

Signed-off-by: Mykola Golub <mykola.golub@clyso.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by trociny** [comment]
Typical usage:
```
# Get current crushmap
$ crushdiff export cm.txt
# Edit the map
$ $EDITOR cm.txt
# Check the result
$ crushdiff compare cm.txt
# Install the updated map
$ crushdiff import cm.txt
```

**Comment by neha-ojha** [comment]
I like the idea! Could you please a manpage for this just like https://docs.ceph.com/en/latest/man/8/osdmaptool/, with an example.

**Comment by trociny** [comment]
jenkins render docs

**Comment by trociny** [comment]
jenkins render docs

**Comment by trociny** [comment]
@neha-ojha The man page is added.

As the tool parses the osdmaptool output and is rather sensitive to its format change and may break in the future I also added a simple teuthology test to catch this. I just tired it on teuthology [1].

[1] https://pulpito.ceph.com/trociny-2021-08-04_14:09:21-rados-wip-mgolub-testing-distro-basic-smithi/

**Review by neha-ojha — APPROVED** [review]
overall looks good, left some minor comments

**Comment by neha-ojha** [comment]
https://ceph--41912.org.readthedocs.build/en/41912/man/8/crushdiff/

**Comment by trociny** [comment]
jenkins render docs

**Comment by trociny** [comment]
@neha-ojha I have updated according to your comments. Thanks.

Not sure why the doc redner is still based on the old version though.

**Comment by tchaikov** [comment]
@trociny it did render using the latest revision. see https://ceph--41912.org.readthedocs.build/en/41912/man/8/crushdiff/

**Comment by trociny** [comment]
> @trociny it did render using the latest revision. see https://ceph--41912.org.readthedocs.build/en/41912/man/8/crushdiff/

Ah, my browser was showing the cached page. I had to force refresh. Thanks.

**Comment by neha-ojha** [comment]
jenkins test make check

**Comment by neha-ojha** [comment]
releavant tests have passed https://pulpito.ceph.com/trociny-2021-08-27_14:46:12-rados-wip-mgolub-testing-distro-basic-smithi/

**Pull request merged**
