### PR TITLE
debian: fix typo in cephadm user gecos

### PR DESCRIPTION
**Pull request by sebastian-philipp**
Signed-off-by: Alexey Miasoedov <alexey.miasoedov@gmail.com>

replaces #34557

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by tchaikov** [comment]
```
183/194 Test  #14: smoke.sh ................................***Failed  550.83 sec
```

**Comment by tchaikov** [comment]
jenkins test make check

**Comment by tchaikov** [comment]
the title of the commit message does not look right, as this change does not touch the rpm recipe.

**Comment by sebastian-philipp** [comment]
> i am not sure how mgr is connected with this newly created user. but in the sense of consistency, the change LGTM.

had the same thought. What about `cephadm user`?

**Comment by tchaikov** [comment]
@sebastian-philipp could you please update the title of the commit message?

**Comment by sebastian-philipp** [comment]
done

**Comment by tchaikov** [comment]
http://pulpito.ceph.com/kchai-2020-05-05_13:45:45-rados-wip-kefu-testing-2020-05-05-1333-distro-basic-smithi/

**Pull request merged**
