### PR TITLE
S3 rest api extend for usage show

### PR DESCRIPTION
**Pull request by chenji-kael**
This api is used to let every S3 user know
their total usage.
Before this, only cluster manager can use
radosgw-admin usage show --uid to find total
resource a user has used.
As amazon does not expose this api.So I defined
it by myself.

format:
GET /?usage&start-date=<DATE>&end-date=<DATE> HTTP/1.1
Host: s3.amazonaws.com
Date: date
Authorization: authorization string

start-date := "YYYY-MM-DD[ hh:mm:ss]"       
end-date := "YYYY-MM-DD[ hh:mm:ss]"

Signed-off-by: Ji Chen <insomnia@139.com>

### CODE REVIEW

**Comment by chenji-kael** [comment]
@yehudasa ping
Hi ,how about this pull request ,I found nobody take interest in it. Do you think it`s usefull? We have put this function to our customer, because they want to know the usage by themselves.

**Comment by yehudasa** [comment]
@chenji-kael can you squash the commits together?

**Comment by chenji-kael** [comment]
@yehudasa hi, I have squash two commits together, but still can not find where is for unsigned sub resources, can you point it out for me , thanks a lot

**Comment by chenji-kael** [comment]
@yehudasa ping

**Comment by yehudasa** [comment]
@chenji-kael the branch needs to be rebase on top of current master

**Comment by chenji-kael** [comment]
@yehudasa 
ok, rebase done now

**Comment by yehudasa** [comment]
@chenji-kael take a look at the following branch:
https://github.com/ceph/ceph/tree/wip-rgw-usage

I fixed a few things, and removed 'usage' from the signed subresources.

**Comment by chenji-kael** [comment]
@yehudasa 
I have tested this branch by using s3cmd, but I found "usage" has been removed from sub-resources
The api I suggested should be like this "GET /?usage&start-date=XX&end-date=XX"
In S3cmd, this request will have a SignHeaders: 'GET\n\n\n\nx-amz-date:Mon, 07 Mar 2016 09:12:04 +0000\n/?usage', So if usage removed from sub-resource in rgw will cause 403  because of a signature error
Does that mean I must change the format of api?
Need you help, thanks

**Comment by yehudasa** [comment]
@chenji-kael that was on purpose. It is not part of the list of subresources specified by amazon as the ones that need to be signed, therefore other clients (e.g., boto) won't sign it.

**Pull request merged**
