### PR TITLE
qa: test the "ms_mode" option in kclient workflows

### PR DESCRIPTION
**Pull request by jtlayton**
Note that I didn't bother adding the prefer-* options for ms_mode, as I
figure it's better to be definite. We could add them though.

Fixes: https://tracker.ceph.com/issues/52068
Signed-off-by: Jeff Layton <jlayton@redhat.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by jtlayton** [comment]
This is a prelude to making "copyfrom" the default in v5.15 (which I think we should do). I think we should also consider making "ms_mode=prefer-secure" the default in a future release, but I'm not sure how we'll want to time that.

@idryomov: thoughts?

**Comment by jtlayton** [comment]
jenkins test make check

**Comment by luis-henrix** [comment]
This looks good to me, although I'm really not sure about how much code will be tested with this.  For example, I'm not sure there's any test case that will exercise the kernel client copy_file_range code (or the corresponding OSDs 'copy_from2' operation).

I've took a quick look and came up with this commit: https://github.com/luis-henrix/ceph/commit/5a28a90cc1cf7f15bb2a55ea214373dfb8bbd204 .  It's completely untested, of course, but it's an attempt to simply run 'check ceph/*' in xfstests (yeah, it contains an arbitrary 30m timeout...).  Would something like that make sense, or is that simply wrong?

**Review by idryomov — COMMENTED** [review]
I second Luis' concern about `copyfrom` coverage, `ms_mode` bits look fine.

**Comment by idryomov** [comment]
> I think we should also consider making "ms_mode=prefer-secure" the default in a future release, but I'm not sure how we'll want to time that.
> 
> @idryomov: thoughts?

I think you meant `ms_mode=prefer-crc`.  The problem is that if we do that in the kernel (i.e. change what happens when `ms_mode` isn't specified) then userspace (and particularly old userspace) would break because it would still supply
v1 addresses.

I think what we need to do is change `rbd` and the mount helper to pass v2 addresses and `ms_mode=prefer-crc` unless the user says otherwise and backport that to pacific.  The kernel would have to default to msgr1 indefinitely, I'm afraid.

**Comment by jtlayton** [comment]
We do have qa/tasks/cephfs/xfstests_dev.py, which clones git://git.ceph.com/xfstests-dev.git, and that seems to have been updated to the state of upstream xfstests repo recently. It looks like that just gets referenced by some ACL tests, but ISTR that @lxbsz did some work a while back to integrate xfstests into teuthology.

 What I'm not clear on is which tests actually use it and whether any run the ceph/ tests in there.

**Comment by jtlayton** [comment]
> I think you meant `ms_mode=prefer-crc`. The problem is that if we do that in the kernel (i.e. change what happens when `ms_mode` isn't specified) then userspace (and particularly old userspace) would break because it would still supply v1 addresses.

Why would we want to default to unsecured communications? Is there enough perf impact to make "secure" problematic as a default?

> 
> I think what we need to do is change `rbd` and the mount helper to pass v2 addresses and `ms_mode=prefer-crc` unless the user says otherwise and backport that to pacific. The kernel would have to default to msgr1 indefinitely, I'm afraid.

Yeah, you're right that we'll need to fix that in the mount helper. The problem there of course is that that starting to pass v2 addresses by default will be problematic on old kernels. OTOH, at some point we have to just give up on the "old kernel + new userspace" combo.

What may be best for that actually is to just integrate this into @vshankar 's work to add a new mount syntax. We're already making a clean break with the past with that, so we could just ensure that when someone uses the new syntax that they end up using ms_mode=prefer-secure by default. I'll comment on that in his mount helper PR (https://github.com/ceph/ceph/pull/41334).

**Comment by idryomov** [comment]
> Why would we want to default to unsecured communications? Is there enough perf impact to make "secure" problematic as a default?

Yes.  We default to "crc" for client <-> OSD communication in userspace for a reason ;)

> 
> > I think what we need to do is change `rbd` and the mount helper to pass v2 addresses and `ms_mode=prefer-crc` unless the user says otherwise and backport that to pacific. The kernel would have to default to msgr1 indefinitely, I'm afraid.
> 
> Yeah, you're right that we'll need to fix that in the mount helper. The problem there of course is that that starting to pass v2 addresses by default will be problematic on old kernels. OTOH, at some point we have to just give up on the "old kernel + new userspace" combo.

The failure mode would be very straightforward though: "ms_mode option is not supported".

> 
> What may be best for that actually is to just integrate this into @vshankar 's work to add a new mount syntax. We're already making a clean break with the past with that, so we could just ensure that when someone uses the new syntax that they end up using ms_mode=prefer-secure by default. I'll comment on that in his mount helper PR (#41334).

Yup, merging these together sounds like the right thing to do to me.  Make sure that is `ms_mode=prefer-crc` though.

**Review by batrick — DISMISSED** [review]
Let's split `copyfrom` into a separate PR until it's clear that it will actually be tested.

`ms_mode` changes look good to me.

**Comment by batrick** [comment]
I'd also like to backport the `ms_mode` testing to Pacific. Can you create a ticket?

**Comment by batrick** [comment]
> We do have qa/tasks/cephfs/xfstests_dev.py, which clones git://git.ceph.com/xfstests-dev.git, and that seems to have been updated to the state of upstream xfstests repo recently. It looks like that just gets referenced by some ACL tests, but ISTR that @lxbsz did some work a while back to integrate xfstests into teuthology.

@rishabh-d-dave actually.

**Comment by jtlayton** [comment]
> > We do have qa/tasks/cephfs/xfstests_dev.py, which clones git://git.ceph.com/xfstests-dev.git, and that seems to have been updated to the state of upstream xfstests repo recently. It looks like that just gets referenced by some ACL tests, but ISTR that @lxbsz did some work a while back to integrate xfstests into teuthology.
> 
> @rishabh-d-dave actually.

Ahh, thanks! I think we can extend his work to do the copy_file_range tests in xfstests too.

I'll drop the copyfrom changes from this PR for now. We can do that in a separate change.

**Review by idryomov — APPROVED** [review]

**Comment by jtlayton** [comment]
Hmm. One thing that may be problematic...

What sort of monaddrs are being passed into these tests? I'll note that `qa/tasks/cephfs/xfstests_dev.py` seems to be hardcoded to use v1 sockets. Are there other examples of that? We probably need to make most of these tests let the mount helper determine the sockets to use.

**Comment by jtlayton** [comment]
> Hmm. One thing that may be problematic...
> 
> What sort of monaddrs are being passed into these tests? I'll note that `qa/tasks/cephfs/xfstests_dev.py` seems to be hardcoded to use v1 sockets. Are there other examples of that? We probably need to make most of these tests let the mount helper determine the sockets to use.

After looking more closely, I think we're ok here. Most tests use the yaml files to build options and mount device strings, and those seem to already dtrt.

**Comment by jtlayton** [comment]
jenkins test make check

**Comment by jtlayton** [comment]
Rebased to try and clear up the make check problems.

**Comment by batrick** [comment]
https://tracker.ceph.com/projects/cephfs/wiki/Master#2021-August-27

**Comment by batrick** [comment]
This PR probably causes https://tracker.ceph.com/issues/52438 but it's not significant enough to block merging.

**Pull request merged**
