### PR TITLE
mimic: os/bluestore: backport new bitmap allocator

### PR DESCRIPTION
**Pull request by ifed01**
https://tracker.ceph.com/issues/38779

### CODE REVIEW

**Comment by yuriw** [comment]
[wip-yuri-testing-2019-03-20-2018-mimic](https://trello.com/c/eYs8FKUW/562-wip-yuri-testing-2019-03-20-2018-mimic)

**Comment by yuriw** [comment]
@ifed01 also broken yaml config:

CEPH_QA_MAIL="ceph-qa@lists.ceph.com"; MACHINE_NAME=smithi; CEPH_BRANCH=wip-yuri-testing-2019-03-20-2018-mimic

teuthology-suite -v --ceph-repo https://github.com/ceph/ceph-ci.git --suite-repo https://github.com/ceph/ceph-ci.git  -c $CEPH_BRANCH -m $MACHINE_NAME -s rados --subset 35/2999 -k distro -p 90 -e $CEPH_QA_MAIL --suite-branch $CEPH_BRANCH
2019-03-22 20:18:35,117.117 INFO:teuthology.suite:Using random seed=7853
2019-03-22 20:18:35,118.118 INFO:teuthology.suite.run:kernel sha1: distro
2019-03-22 20:18:35,380.380 DEBUG:teuthology.repo_utils:git ls-remote https://github.com/ceph/ceph-ci wip-yuri-testing-2019-03-20-2018-mimic -> 1467b0d781b1e0fbef738a1f80be854d708681ef
2019-03-22 20:18:35,380.380 INFO:teuthology.suite.run:ceph sha1: 1467b0d781b1e0fbef738a1f80be854d708681ef
2019-03-22 20:18:35,381.381 DEBUG:teuthology.suite.util:Defaults for machine_type smithi distro centos: arch=x86_64, release=centos/7, pkg_type=rpm
2019-03-22 20:18:35,381.381 DEBUG:teuthology.packaging:Querying https://shaman.ceph.com/api/search?status=ready&project=ceph&flavor=default&distros=centos%2F7%2Fx86_64&sha1=1467b0d781b1e0fbef738a1f80be854d708681ef
2019-03-22 20:18:35,548.548 INFO:teuthology.suite.run:ceph version: 13.2.5-98.g1467b0d
2019-03-22 20:18:35,548.548 INFO:teuthology.suite.run:teuthology branch: master
2019-03-22 20:18:35,801.801 DEBUG:teuthology.repo_utils:git ls-remote https://github.com/ceph/ceph-ci.git wip-yuri-testing-2019-03-20-2018-mimic -> 1467b0d781b1e0fbef738a1f80be854d708681ef
2019-03-22 20:18:36,042.042 DEBUG:teuthology.repo_utils:git ls-remote https://github.com/ceph/ceph-ci.git wip-yuri-testing-2019-03-20-2018-mimic -> 1467b0d781b1e0fbef738a1f80be854d708681ef
2019-03-22 20:18:36,042.042 INFO:teuthology.suite.run:ceph-ci branch: wip-yuri-testing-2019-03-20-2018-mimic 1467b0d781b1e0fbef738a1f80be854d708681ef
2019-03-22 20:18:36,046.046 INFO:teuthology.repo_utils:/home/yuriw/src/github.com_ceph_ceph-c_wip-yuri-testing-2019-03-20-2018-mimic was just updated; assuming it is current
2019-03-22 20:18:36,046.046 INFO:teuthology.repo_utils:Resetting repo at /home/yuriw/src/github.com_ceph_ceph-c_wip-yuri-testing-2019-03-20-2018-mimic to branch wip-yuri-testing-2019-03-20-2018-mimic
2019-03-22 20:18:36,134.134 DEBUG:teuthology.suite.run:Suite rados in /home/yuriw/src/github.com_ceph_ceph-c_wip-yuri-testing-2019-03-20-2018-mimic/qa/suites/rados
2019-03-22 20:18:36,134.134 INFO:teuthology.suite.build_matrix:Subset=35/2999
Traceback (most recent call last):
  File "/home/yuriw/teuthology/virtualenv/bin/teuthology-suite", line 11, in <module>
    load_entry_point('teuthology', 'console_scripts', 'teuthology-suite')()
  File "/home/yuriw/teuthology/scripts/suite.py", line 152, in main
    return teuthology.suite.main(args)
  File "/home/yuriw/teuthology/teuthology/suite/__init__.py", line 144, in main
    run.prepare_and_schedule()
  File "/home/yuriw/teuthology/teuthology/suite/run.py", line 343, in prepare_and_schedule
    num_jobs = self.schedule_suite()
  File "/home/yuriw/teuthology/teuthology/suite/run.py", line 494, in schedule_suite
    build_matrix(suite_path, subset=self.args.subset, seed=self.args.seed)
  File "/home/yuriw/teuthology/teuthology/suite/build_matrix.py", line 57, in build_matrix
    mat, first, matlimit = _get_matrix(path, subset)
  File "/home/yuriw/teuthology/teuthology/suite/build_matrix.py", line 67, in _get_matrix
    mat = _build_matrix(path, mincyclicity=outof)
  File "/home/yuriw/teuthology/teuthology/suite/build_matrix.py", line 146, in _build_matrix
    fn)
  File "/home/yuriw/teuthology/teuthology/suite/build_matrix.py", line 130, in _build_matrix
    item=fn)
  File "/home/yuriw/teuthology/teuthology/suite/build_matrix.py", line 146, in _build_matrix
    fn)
  File "/home/yuriw/teuthology/teuthology/suite/build_matrix.py", line 84, in _build_matrix
    raise IOError('%s does not exist (abs %s)' % (path, os.path.abspath(path)))
IOError: /home/yuriw/src/github.com_ceph_ceph-c_wip-yuri-testing-2019-03-20-2018-mimic/qa/suites/rados/singleton-bluestore/objectstore/bluestore.yaml does not exist (abs /home/yuriw/src/github.com_ceph_ceph-c_wip-yuri-testing-2019-03-20-2018-mimic/qa/suites/rados/singleton-bluestore/objectstore/bluestore.yaml)

**Comment by ifed01** [comment]
@yuriw - yeah, the same here. Already fixed.

**Comment by yuriw** [comment]
[wip-yuri5-testing-2019-03-22-2035-mimic](https://trello.com/c/P1591H7t/566-wip-yuri5-testing-2019-03-22-2035-mimic)

**Comment by yuriw** [comment]
@ifed01 same issue:

CEPH_QA_MAIL="ceph-qa@lists.ceph.com"; MACHINE_NAME=smithi; CEPH_BRANCH=wip-yuri5-testing-2019-03-22-2035-mimic

teuthology-suite -v --ceph-repo https://github.com/ceph/ceph-ci.git --suite-repo https://github.com/ceph/ceph-ci.git  -c $CEPH_BRANCH -m $MACHINE_NAME -s rados --subset 31/2999 -k distro -p 90 -e $CEPH_QA_MAIL -l 150
2019-03-25 15:34:28,653.653 INFO:teuthology.suite:Using random seed=4005
2019-03-25 15:34:28,654.654 INFO:teuthology.suite.run:kernel sha1: distro
2019-03-25 15:34:28,924.924 DEBUG:teuthology.repo_utils:git ls-remote https://github.com/ceph/ceph-ci wip-yuri5-testing-2019-03-22-2035-mimic -> bb6749df9c1e0a83d2f41f74bb925d7fafd19dfd
2019-03-25 15:34:28,924.924 INFO:teuthology.suite.run:ceph sha1: bb6749df9c1e0a83d2f41f74bb925d7fafd19dfd
2019-03-25 15:34:28,924.924 DEBUG:teuthology.suite.util:Defaults for machine_type smithi distro centos: arch=x86_64, release=centos/7, pkg_type=rpm
2019-03-25 15:34:28,925.925 DEBUG:teuthology.packaging:Querying https://shaman.ceph.com/api/search?status=ready&project=ceph&flavor=default&distros=centos%2F7%2Fx86_64&sha1=bb6749df9c1e0a83d2f41f74bb925d7fafd19dfd
2019-03-25 15:34:29,135.135 INFO:teuthology.suite.run:ceph version: 13.2.5-70.gbb6749d
2019-03-25 15:34:29,135.135 INFO:teuthology.suite.run:teuthology branch: master
2019-03-25 15:34:29,379.379 DEBUG:teuthology.repo_utils:git ls-remote https://github.com/ceph/ceph-ci.git wip-yuri5-testing-2019-03-22-2035-mimic -> bb6749df9c1e0a83d2f41f74bb925d7fafd19dfd
2019-03-25 15:34:29,615.615 DEBUG:teuthology.repo_utils:git ls-remote https://github.com/ceph/ceph-ci.git wip-yuri5-testing-2019-03-22-2035-mimic -> bb6749df9c1e0a83d2f41f74bb925d7fafd19dfd
2019-03-25 15:34:29,616.616 INFO:teuthology.suite.run:ceph-ci branch: wip-yuri5-testing-2019-03-22-2035-mimic bb6749df9c1e0a83d2f41f74bb925d7fafd19dfd
2019-03-25 15:34:29,629.629 INFO:teuthology.repo_utils:Cloning https://github.com/ceph/ceph-ci.git wip-yuri5-testing-2019-03-22-2035-mimic from upstream
2019-03-25 15:34:34,580.580 INFO:teuthology.repo_utils:Resetting repo at /home/yuriw/src/github.com_ceph_ceph-c_wip-yuri5-testing-2019-03-22-2035-mimic to branch wip-yuri5-testing-2019-03-22-2035-mimic
2019-03-25 15:34:35,048.048 DEBUG:teuthology.suite.run:Suite rados in /home/yuriw/src/github.com_ceph_ceph-c_wip-yuri5-testing-2019-03-22-2035-mimic/qa/suites/rados
2019-03-25 15:34:35,048.048 INFO:teuthology.suite.build_matrix:Subset=31/2999
Traceback (most recent call last):
  File "/home/yuriw/teuthology/virtualenv/bin/teuthology-suite", line 11, in <module>
    load_entry_point('teuthology', 'console_scripts', 'teuthology-suite')()
  File "/home/yuriw/teuthology/scripts/suite.py", line 152, in main
    return teuthology.suite.main(args)
  File "/home/yuriw/teuthology/teuthology/suite/__init__.py", line 144, in main
    run.prepare_and_schedule()
  File "/home/yuriw/teuthology/teuthology/suite/run.py", line 343, in prepare_and_schedule
    num_jobs = self.schedule_suite()
  File "/home/yuriw/teuthology/teuthology/suite/run.py", line 494, in schedule_suite
    build_matrix(suite_path, subset=self.args.subset, seed=self.args.seed)
  File "/home/yuriw/teuthology/teuthology/suite/build_matrix.py", line 57, in build_matrix
    mat, first, matlimit = _get_matrix(path, subset)
  File "/home/yuriw/teuthology/teuthology/suite/build_matrix.py", line 67, in _get_matrix
    mat = _build_matrix(path, mincyclicity=outof)
  File "/home/yuriw/teuthology/teuthology/suite/build_matrix.py", line 146, in _build_matrix
    fn)
  File "/home/yuriw/teuthology/teuthology/suite/build_matrix.py", line 130, in _build_matrix
    item=fn)
  File "/home/yuriw/teuthology/teuthology/suite/build_matrix.py", line 146, in _build_matrix
    fn)
  File "/home/yuriw/teuthology/teuthology/suite/build_matrix.py", line 84, in _build_matrix
    raise IOError('%s does not exist (abs %s)' % (path, os.path.abspath(path)))
IOError: /home/yuriw/src/github.com_ceph_ceph-c_wip-yuri5-testing-2019-03-22-2035-mimic/qa/suites/rados/singleton-bluestore/objectstore/bluestore-bitmap.yaml does not exist (abs /home/yuriw/src/github.com_ceph_ceph-c_wip-yuri5-testing-2019-03-22-2035-mimic/qa/suites/rados/singleton-bluestore/objectstore/bluestore-bitmap.yaml)

**Comment by yuriw** [comment]
@ifed01 let me know when I can retry

**Comment by ifed01** [comment]
@yuriw - thanks a lot for you efforts, hopefully fixed.

**Comment by yuriw** [comment]
@ifed01 looks better now, thx !
Running tests http://pulpito.ceph.com/yuriw-2019-03-27_16:56:23-rados-wip-yuri5-testing-2019-03-27-1505-mimic-distro-basic-smithi

**Comment by yuriw** [comment]
tests passed, @liewegas please approve/merge (re: https://trello.com/c/P1591H7t)

**Pull request merged**
