### PR TITLE
stop.sh: do not try to contact mon unless cluster is up

### PR DESCRIPTION
**Pull request by tchaikov**
## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by tchaikov** [comment]
cc @kotreshhr

**Comment by kotreshhr** [comment]
> cc @kotreshhr

My bad. LGTM.

**Comment by batrick** [comment]
Thanks for fixing this @tchaikov !

**Comment by liewegas** [comment]
Yes!

**Pull request merged**
