### PR TITLE
cmake changes

### PR DESCRIPTION
**Pull request by tchaikov**
no regression found, and there's a substantial reduction in the size of
generated librados library (both stripped and not).

Signed-off-by: Kefu Chai <kchai@redhat.com>

### CODE REVIEW

**Comment by liewegas** [comment]
rebase?

**Comment by tchaikov** [comment]
@liewegas rebased.

**Comment by alimaredia** [comment]
@tchaikov looks fine to me, one question I have: is CMAKE_INSTALL_LIBDIR replacing "lib" as the DESTINATION everywhere in the code or just in the places in your commit?

**Comment by tchaikov** [comment]
@alimaredia i tried to fix this inconsistency whenever i see it. ideally we should use `${CMAKE_INSTALL_LIBDIR}` everywhere.

**Pull request merged**
