### PR TITLE
[DNM] mgr/dashboard: Add RBD create functionality (frontend)

### PR DESCRIPTION
**Pull request by ricardoasmarques**
_This PR should be merged after we have a "Block > RBDs" menu entry, that lists all RBD images._

----

This PR is the frontend part of RBD create functionality.

screenshot from 2018-03-12 16-30-28

This PR also adds a detail view of the selected RBD:

screenshot from 2018-03-12 16-40-47

And also adds some shared components that can be reused by other forms:
- DimlessBinaryDirective
- Helper component

### CODE REVIEW

**Comment by LenzGr** [comment]
Could you please take a look at the "make check" test failure in Jenkins?

**Comment by ricardoasmarques** [comment]
jenkins retest this please

**Comment by LenzGr** [comment]
FYI, #20751 is merged now.

**Comment by ricardoasmarques** [comment]
This PR is now rebased, and ready for review.

**Pull request closed without merging**
