### PR TITLE
pacific: mgr/stats: change in structure of perf_stats o/p

### PR DESCRIPTION
**Pull request by joscollin**
Fixes: https://tracker.ceph.com/issues/57279
Fixes: https://tracker.ceph.com/issues/57277
Fixes: https://tracker.ceph.com/issues/57331

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by joscollin** [comment]
jenkins test make check

**Comment by anthonyeleven** [comment]
Docs Lgtm.  Code requires approval by someone else

**Comment by joscollin** [comment]
jenkins test make check

**Comment by joscollin** [comment]
jenkins test make check

**Review by neesingh-rh — CHANGES_REQUESTED** [review]
It still contains two versions of `test_client_metrics_and_metadata`.To keep it similar to quincy and mainline, pls delete the first patch and retain the second one.

**Comment by joscollin** [comment]
> It still contains two versions of `test_client_metrics_and_metadata`.To keep it similar to quincy and mainline, pls delete the first patch and retain the second one.

I've spent sometime checking why this happened. This seems to be the wrong order of backporting the previous PRs of test_mds_metrics.py, probably the conflict resolution should've done in a better way. There's nothing we can do now and dropping the old `test_client_metrics_and_metadata` seems to be the only option. Will fix it.

**Comment by vshankar** [comment]
> > It still contains two versions of `test_client_metrics_and_metadata`.To keep it similar to quincy and mainline, pls delete the first patch and retain the second one.
> 
> I've spent sometime checking why this happened. This seems to be the wrong order of backporting the previous PRs of test_mds_metrics.py, probably the conflict resolution should've done in a better way. There's nothing we can do now and dropping the old `test_client_metrics_and_metadata` seems to be the only option. Will fix it.

Why are there two versions of the same test? The PR for the main branch seems fine.

**Comment by vshankar** [comment]
> > > It still contains two versions of `test_client_metrics_and_metadata`.To keep it similar to quincy and mainline, pls delete the first patch and retain the second one.
> > 
> > 
> > I've spent sometime checking why this happened. This seems to be the wrong order of backporting the previous PRs of test_mds_metrics.py, probably the conflict resolution should've done in a better way. There's nothing we can do now and dropping the old `test_client_metrics_and_metadata` seems to be the only option. Will fix it.
> 
> Why are there two versions of the same test? The PR for the main branch seems fine.

EDIT: The conflict resolution (if any) should have been done with utmost care, isn't it?

**Comment by joscollin** [comment]
> > > > It still contains two versions of `test_client_metrics_and_metadata`.To keep it similar to quincy and mainline, pls delete the first patch and retain the second one.
> > > 
> > > 
> > > I've spent sometime checking why this happened. This seems to be the wrong order of backporting the previous PRs of test_mds_metrics.py, probably the conflict resolution should've done in a better way. There's nothing we can do now and dropping the old `test_client_metrics_and_metadata` seems to be the only option. Will fix it.
> > 
> > 
> > Why are there two versions of the same test? The PR for the main branch seems fine.
> 
> EDIT: The conflict resolution (if any) should have been done with utmost care, isn't it?

Yes, the main branch is fine. As I checked the recent pacific backports that involves test_mds_metrics.py, this issue happened because of the wrong order of back-porting and thus git couldn't find the older version of `test_client_metrics_and_metadata` automatically. I tried to revert those commits and cherry-pick them again to fix it, but that ended up in another revert conflict involving other files. So better edited the cherry-picked commit 9e849cebb70cb7941309c6680731fda8a697e639 in this PR to drop the redundant version of `test_client_metrics_and_metadata`, mentioning the reason in the Conflicts section.

**Comment by joscollin** [comment]
jenkins test make check

**Comment by joscollin** [comment]
> @joscollin Pls add all the commits for pacific backport in this PR similar to quincy #47820 ,as asked by @vshankar . Trackers: https://tracker.ceph.com/issues/57274 and https://tracker.ceph.com/issues/57282 EDIT: After merging pls close this:#47866

I don't want to modify a PR which is under testing.

**Comment by neesingh-rh** [comment]
> > @joscollin Pls add all the commits for pacific backport in this PR similar to quincy #47820 ,as asked by @vshankar . Trackers: https://tracker.ceph.com/issues/57274 and https://tracker.ceph.com/issues/57282 EDIT: After merging pls close this:#47866
> 
> I don't want to modify a PR which is under testing.

Oh, it has been put for testing now.Ok, then we should keep them as it is.

**Review by neesingh-rh — APPROVED** [review]

**Comment by joscollin** [comment]
jenkins test make check

**Comment by vshankar** [comment]
jenkins test api

**Pull request merged**
