### PR TITLE
pacific: osd/OSD: introduce reset_purged_snaps_last

### PR DESCRIPTION
**Pull request by Matan-B**
backport tracker: https://tracker.ceph.com/issues/63179

---

backport of https://github.com/ceph/ceph/pull/53579
parent tracker: https://tracker.ceph.com/issues/62981

this backport was staged using ceph-backport.sh version 16.0.0.6848
find the latest version at https://github.com/ceph/ceph/blob/master/src/script/ceph-backport.sh

### CODE REVIEW

**Review by athanatos — APPROVED** [review]

**Review by rzarzynski — APPROVED** [review]

**Comment by Matan-B** [comment]
jenkins test make check

**Comment by Matan-B** [comment]
jenkins test api

**Comment by yuriw** [comment]
@Matan-B I suspect this PR is breaking the build:

[ 63%] Building CXX object src/librbd/CMakeFiles/rbd_internal.dir/journal/DemoteRequest.cc.o
/home/jenkins-build/build/workspace/ceph-dev-new-build/ARCH/x86_64/AVAILABLE_ARCH/x86_64/AVAILABLE_DIST/centos8/DIST/centos8/MACHINE_SIZE/gigantic/release/16.2.14-106-g6e5b7fb8/rpm/el8/BUILD/ceph-16.2.14-106-g6e5b7fb8/src/osd/OSD.cc: In member function ‘void OSD::asok_command(std::string_view, const cmdmap_t&, ceph::Formatter*, const bufferlist&, std::function<void(int, const std::__cxx11::basic_string<char>&, ceph::buffer::v15_2_0::list&)>)’:
/home/jenkins-build/build/workspace/ceph-dev-new-build/ARCH/x86_64/AVAILABLE_ARCH/x86_64/AVAILABLE_DIST/centos8/DIST/centos8/MACHINE_SIZE/gigantic/release/16.2.14-106-g6e5b7fb8/rpm/el8/BUILD/ceph-16.2.14-106-g6e5b7fb8/src/osd/OSD.cc:3039:40: error: no matching function for call to ‘OSD::write_superblock(ceph::common::CephContext*&, OSDSuperblock&, ObjectStore::Transaction&)’
     write_superblock(cct, superblock, t);

https://jenkins.ceph.com/job/ceph-dev-new-build/ARCH=x86_64,AVAILABLE_ARCH=x86_64,AVAILABLE_DIST=centos8,DIST=centos8,MACHINE_SIZE=gigantic/73541//consoleFull

Pls take a look

**Comment by Matan-B** [comment]
> @Matan-B I suspect this PR is breaking the build:
> Pls take a look

@yuriw fixed, thank you.

**Comment by Matan-B** [comment]
jenkins test make check

**Comment by ljflores** [comment]
@yuriw we need to include this in a new batch.

**Comment by ljflores** [comment]
> @yuriw we need to include this in a new batch.

Ignore this- I thought the PR was dropped from the batch. But it was retested.

Rados approved: https://tracker.ceph.com/projects/rados/wiki/PACIFIC#httpstrellocomcXxBiaEyT1874-wip-yuri5-testing-2023-10-24-0737-pacific-old-wip-yuri5-testing-2023-10-23-1158-pacific

**Comment by Matan-B** [comment]
> Ignore this- I thought the PR was dropped from the batch. But it was retested.
> 
> Rados approved: https://tracker.ceph.com/projects/rados/wiki/PACIFIC#httpstrellocomcXxBiaEyT1874-wip-yuri5-testing-2023-10-24-0737-pacific-old-wip-yuri5-testing-2023-10-23-1158-pacific

Merging based on:
https://trello.com/c/XxBiaEyT/1874-wip-yuri5-testing-2023-10-24-0737-pacific-old-wip-yuri5-testing-2023-10-23-1158-pacific

**Pull request merged**
