### PR TITLE
msg: reimplement sigpipe blocking

### PR DESCRIPTION
**Pull request by gregsfortytwo**

### CODE REVIEW

**Comment by gregsfortytwo** [comment]
I tested this on my box using the #define swap you see in the last two commits there.

**Comment by wjwithagen** [comment]
@gregsfortytwo 
If you want me to give this a testrun on FreeBSD before commiting, just let me know.

**Comment by liewegas** [comment]
Looks nice and clean to me!  @wjwithagen if you can test that would be very helpful!

**Comment by gregsfortytwo** [comment]
Rebased on latest master because "make check" had a weird white space error in it.

**Comment by wjwithagen** [comment]
@liewegas @gregsfortytwo 
Running FreeBSD build/test:
    http://cephdev.digiware.nl:8180/jenkins/job/ceph-master/1282/console

**Comment by wjwithagen** [comment]
@liewegas @gregsfortytwo
All oke but one test.

Which is probably due to me messing about with tools and other tests:
'''
The following tests FAILED:
	143 - unittest_rbd_mirror (SEGFAULT)
Errors while running CTest
'''

**Comment by gregsfortytwo** [comment]
Excellent. (There's no way an rbd mirroring test would expose problems if nothing else did.)

**Comment by smithfarm** [comment]
luminous backport: https://github.com/ceph/ceph/pull/18126

**Pull request merged**
