### PR TITLE
mimic: qa/rgw: reduce number of multisite log shards

### PR DESCRIPTION
**Pull request by cbodley**
backport tracker http://tracker.ceph.com/issues/38609

### CODE REVIEW

**Comment by smithfarm** [comment]
jenkins test make check

**Comment by yuriw** [comment]
[wip-yuri3-testing-2019-04-29-1935-mimic](https://trello.com/c/1OdZ5zIb/598-wip-yuri3-testing-2019-04-29-1935-mimic)

**Comment by yuriw** [comment]
[wip-yuri4-testing-2019-04-30-1543-mimic](https://trello.com/c/A2lSYsdc/600-wip-yuri4-testing-2019-04-30-1543-mimic)

**Comment by yuriw** [comment]
[wip-yuri2-testing-2019-05-02-2259-mimic](https://trello.com/c/ZIBIbboi/605-wip-yuri2-testing-2019-05-02-2259-mimic)

**Pull request merged**
