### PR TITLE
rgw,common: instrumentation to log key reshard events at level 5

### PR DESCRIPTION
**Pull request by ivancich**
rgw: instrumentation to log key reshard events at level 5
    
Much of the current logging surrounding bucket index resharding happens at a high level. These should be relatively uncommon events, such that we can monitor key events when a reshard takes place without raising the log level too high.

rgw: provide an error form of the dpp logging

Previously, the dpp form of logging was added. But while there's a regular version there was not an error version. This adds it.

Signed-off-by: J. Eric Ivancich <ivancich@redhat.com>

### CODE REVIEW

**Review by adamemerson — APPROVED** [review]

**Comment by ivancich** [comment]
jenkins render docs

**Comment by ivancich** [comment]
jenkins render docs

**Comment by ivancich** [comment]
jenkins render docs

**Review by cbodley — APPROVED** [review]

**Comment by cbodley** [comment]
the docs build has been really flaky. since this is targeting wip-rgw-multisite-reshard, don't worry about the jenkins checks - we can just manually push this to wip-rgw-multisite-reshard when it's ready

**Pull request closed without merging**
