### PR TITLE
test: Remove mimic-x* upgrade testing in master

### PR DESCRIPTION
**Pull request by dzafman**
Signed-off-by: David Zafman <dzafman@redhat.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by dzafman** [comment]
@yuriw @neha-ojha  I don't understand upgrade/mimic-x/stress-split/mon_election/connectivity failure with this change:

http://qa-proxy.ceph.com/teuthology/dzafman-2020-10-23_22:00:18-upgrade-wip-zafman-46264-2-distro-basic-smithi/5552322/teuthology.log

**Comment by jdurgin** [comment]
looks like a bad rebase or something introduced those directories, upgrade/mimic-x has nothing in it except for bad symlinks. The whole directory should be removed in master

**Comment by neha-ojha** [comment]
> @yuriw @neha-ojha I don't understand upgrade/mimic-x/stress-split/mon_election/connectivity failure with this change:
> 
> http://qa-proxy.ceph.com/teuthology/dzafman-2020-10-23_22:00:18-upgrade-wip-zafman-46264-2-distro-basic-smithi/5552322/teuthology.log

There no tests here https://github.com/ceph/ceph/tree/master/qa/suites/upgrade/mimic-x/stress-split, we don't support mimic->pacific upgrades and hence 3c7d5291dedd0e5565a7aa2916efba1e8deaaf82 - let's get rid of the directory.

**Comment by dzafman** [comment]
> looks like a bad rebase or something introduced those directories, upgrade/mimic-x has nothing in it except for bad symlinks. The whole directory should be removed in master

Are you saying remove upgrade/mimic-x in its entirety.

**Comment by jdurgin** [comment]
On 10/23/20 4:49 PM, David Zafman wrote:
>     looks like a bad rebase or something introduced those directories,
>     upgrade/mimic-x has nothing in it except for bad symlinks. The whole
>     directory should be removed in master
> 
> Are you saying remove upgrade/mimic-x in its entirety. 

Yes

**Review by neha-ojha — APPROVED** [review]

**Review by yuriw — APPROVED** [review]

**Comment by yuriw** [comment]
testing http://pulpito.ceph.com/teuthology-2020-10-26_20:53:49-upgrade-master-distro-basic-smithi/

**Comment by dzafman** [comment]
Testing PASSED:

https://pulpito.ceph.com/dzafman-2020-11-09_17:18:57-upgrade-wip-zafman-testing-46264-2-distro-basic-smithi
Rerun 5 dead jobs
https://pulpito.ceph.com/dzafman-2020-11-10_09:38:54-upgrade-wip-zafman-testing-46264-2-distro-basic-smithi/

**Pull request merged**
