### PR TITLE
  osd/ECBackend: Send write message to peers first, then do local write,

### PR DESCRIPTION
**Pull request by hjwsm1989**
like ReplicatedBackend.
  Signed-off-by: huangjun <hjwsm1989@gmail.com>

### CODE REVIEW

**Comment by hjwsm1989** [comment]
@tchaikov the failed check related to the PR?

**Comment by tchaikov** [comment]
@hjwsm1989 no, it's a known issue. http://tracker.ceph.com/issues/17857

**Comment by liewegas** [comment]
Why do this?

**Comment by hjwsm1989** [comment]
@liewegas In my test cluster, i found it first do local write and then send write to peer shards, but in ReplicatedBackend, it send write message out first, and then do write. As local write was in async mode, but it maybe helps when the filestore queue is full.

**Comment by liewegas** [comment]
Hmm, fair enough.  But keep in mind @athanatos has a huge PR that is about to replace most of this code anyway.. see #11701 for an early version.  Let's wait until that merges and then do this?

**Comment by hjwsm1989** [comment]
ok, looking forward to it.

**Pull request closed without merging**
