### PR TITLE
mds: reply session reject for open request from blacklisted client

### PR DESCRIPTION
**Pull request by ukernel**
Signed-off-by: "Yan, Zheng" <zyan@redhat.com>
Fixes: https://tracker.ceph.com/issues/24053

### CODE REVIEW

**Comment by tchaikov** [comment]
retest this please

**Comment by batrick** [comment]
Also fixes: https://tracker.ceph.com/issues/10915 ?

We had decided to ignore MDS rejections in #21065 ? I suppose a good reason to do this is that old kernel clients will handle blacklisting more gracefully/correctly? Otherwise I don't see the point.

**Comment by ukernel** [comment]
It doesn't fix issue 10915 for libcephfs.

kernel client's closing session code has timeout mechanism, libcephfs does not have. The reason I don't use blacklist in kclient is that blacklist is not in client-usable data part of osdmap.  osdmap format is complex, writing code to decode blacklist is not easy,

**Comment by batrick** [comment]
Sorry, I linked the wrong issue. I mean this PR also fixes https://tracker.ceph.com/issues/24054 ?

**Comment by batrick** [comment]
> kernel client's closing session code has timeout mechanism, libcephfs does not have. The reason I don't use blacklist in kclient is that blacklist is not in client-usable data part of osdmap. osdmap format is complex, writing code to decode blacklist is not easy,

Okay, sounds good to me. Please add comments explaining that.

**Comment by batrick** [comment]
@ukernel this may break the fuse client since it expects the MDS to close the session if it's going to request a new OSDMap. I think we will also need to add a request for the next OSDMap in the handling for `CEPH_SESSION_REJECT`?

**Comment by ukernel** [comment]
the code that closes client session on blacklisted is still there, this RP does not change it

**Comment by batrick** [comment]
@ukernel you have fixed two issues but only listed one in the commit message (and it's in the wrong commit).

Please amend the commits and then I'll merge.

**Pull request merged**
