### PR TITLE
mds: add scrub_info_t into mempool

### PR DESCRIPTION
**Pull request by howard0su**
mds: add scrub_info_t into mempool

Signed-off-by: Jun Su <howard0su@gmail.com>

### CODE REVIEW

**Comment by sebastian-philipp** [comment]
https://tracker.ceph.com/issues/44063

**Comment by sebastian-philipp** [comment]
jenkins test make check

**Comment by tchaikov** [comment]
jenkins test make check

**Comment by howard0su** [comment]
> Please split the commit into two. One:
> 
> `mds: remove unused CDir members`
> 
> and the other:
> 
> `mds: add scrub_info_t into mempool`

okay. i will

**Comment by tchaikov** [comment]
@howard0su i think what Patrick suggests is to split the commit into two, we have have them in the same PR though. as each PR will introduce a new merge commit. it would be better to have them into one PR. if the "piggybacked" commit is not risky or is not touching other components.

**Comment by howard0su** [comment]
got it. i repurpose this PR for the #2 PR. and I already submitted another one as #1. check #33227

**Pull request merged**
