### PR TITLE
Set Security Hardening Globally

### PR DESCRIPTION
**Pull request by sidhax**
Please test it before merging into master I am still working on it

### CODE REVIEW

**Comment by sidhax** [comment]
It would build normally , but dont merge until someone gets to do a debian build.

**Comment by liewegas** [comment]
pushed to wip-debian-harden so the gitbuilders can chew on it

**Comment by sidhax** [comment]
ubuntu build failed because of "error: unrecognized command line option '-fstack-protector-strong'" afaik -fstack-protector-strong was added in gcc-4.9 and ubuntu used to build this is running gcc-4.8

**Comment by sidhax** [comment]
This should fix build failures on distributions complaining for fstack-protector-strong which have GCC < 4.9

**Comment by sidhax** [comment]
will fix stuff locally on ubuntu first and then will open new pull request

**Pull request closed without merging**
