### PR TITLE
client: fix potential memory leak

### PR DESCRIPTION
**Pull request by xiexingguo**
Signed-off-by: xie xingguo <xie.xingguo@zte.com.cn>

### CODE REVIEW

**Comment by xiexingguo** [comment]
retest this please

**Comment by xiexingguo** [comment]
retest this please

**Comment by xiexingguo** [comment]
@jcsp Please help to confirm this one too, thanks.

**Comment by xiexingguo** [comment]
@jcsp  One more. Thanks!

**Comment by ukernel** [comment]
Reviewed-by

**Pull request merged**
