### PR TITLE
librbd: flush all queued object IO from simple scheduler

### PR DESCRIPTION
**Pull request by dillaman**
Normally IO is tracked via the AioCompletion's async_op but the
scheduler will "complete" writes while the IO might be still
executing. Therefore, prior to shutting down this dispatch layer
we need to wait for all IO to complete.

Fixes: https://tracker.ceph.com/issues/46668
Signed-off-by: Jason Dillaman <dillaman@redhat.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by trociny** [comment]
@dillaman Just FYI, jenkins failed with the same error I saw in my PR for parent cache:
```
[----------] 7 tests from DiffIterateTest/1, where TypeParam = DiffIterateParams<true>
terminate called after throwing an instance of 'std::system_error'
  what():  Resource deadlock avoided
/home/jenkins-build/build/workspace/ceph-pull-requests/src/test/run-rbd-unit-tests.sh: line 20:  2684 Aborted                 (core dumped) RBD_FEATURES=$i unittest_librbd
```

**Comment by dillaman** [comment]
> Just FYI, jenkins failed with the same error I saw in my PR for parent cache:

Thanks -- this one fixes a jenkins crash caught during an MDS PR.

**Comment by dillaman** [comment]
jenkins test make check

**Comment by dillaman** [comment]
jenkins test dashboard backend

**Comment by trociny** [comment]
jenkins test dashboard backend

**Pull request merged**
