### PR TITLE
doc: mention ENXIO change in the 10.2.6 release notes

### PR DESCRIPTION
**Pull request by smithfarm**

### CODE REVIEW

**Comment by theanalyst** [comment]
I'll update the blog a s well with the same content

**Comment by theanalyst** [comment]
jenkins test this please

**Comment by theanalyst** [comment]
jenkins test this please

**Comment by smithfarm** [comment]
Looks like this might be the culprit:

```
+ git submodule update --init --recursive
Submodule 'ceph-erasure-code-corpus' (https://github.com/ceph/ceph-erasure-code-corpus.git) registered for path 'ceph-erasure-code-corpus'
Submodule 'ceph-object-corpus' (https://github.com/ceph/ceph-object-corpus.git) registered for path 'ceph-object-corpus'
No submodule mapping found in .gitmodules for path 'ceph-qa-suite'
```

Fix is pending in #13880

**Comment by yehudasa** [comment]
@smithfarm #13880 merged

**Comment by smithfarm** [comment]
Thanks; rebased.

**Pull request merged**
