### PR TITLE
pacific: osd/PeeringState: fix acting_set_writeable min_size check

### PR DESCRIPTION
**Pull request by smithfarm**
backport tracker: https://tracker.ceph.com/issues/50154

---

backport of https://github.com/ceph/ceph/pull/40572
parent tracker: https://tracker.ceph.com/issues/48613

this backport was staged using ceph-backport.sh version 16.0.0.6848
find the latest version at https://github.com/ceph/ceph/blob/master/src/script/ceph-backport.sh

### CODE REVIEW

**Comment by smithfarm** [comment]
@athanatos Can you suggest how the second commit could be backported to `{octopus,nautilus}`? It's not clear to me.

**Comment by smithfarm** [comment]
jenkins test docs

**Comment by athanatos** [comment]
@smithfarm 95bec9 recently consolidated those calls to a single place -- fixing those calls individually would likely suffice.  @ideepika Is there a version of the validation test you used we can backport as well to test it?

**Comment by smithfarm** [comment]
@athanatos Thanks. I linked to your comment in the relevant backport issues so whoever takes them up will be able to benefit from your advice.

**Comment by athanatos** [comment]
This seems to have a bunch of extra commits in it now?

**Comment by smithfarm** [comment]
@athanatos Yes, the current state can be ignored, I think. At some point, the extra commits will magically disappear :-)

**Review by neha-ojha — APPROVED** [review]

**Comment by neha-ojha** [comment]
jenkins test docs

**Comment by ideepika** [comment]
> @smithfarm 95bec9 recently consolidated those calls to a single place -- fixing those calls individually would likely suffice. @ideepika Is there a version of the validation test you used we can backport as well to test it?

@athanatos will create backports for validation tests, sorry missed notification earlier

**Pull request merged**
