### PR TITLE
msg/async: DPDKStack as AsyncMessenger backend

### PR DESCRIPTION
**Pull request by yuyuyu101**

### CODE REVIEW

**Comment by uniqueyehu** [comment]
To use DPDKStack as AsyncMessenger backend, I have changed some place in the code:

1. ceph/src/common/config_opts.h
`OPTION(ms_type, OPT_STR, "simple")` to `OPTION(ms_type, OPT_STR, "async")`
`OPTION(ms_async_transport_type, OPT_STR, "posix")` to `OPTION(ms_async_transport_type, OPT_STR, "dpdk")`


2. ceph/CMakeList.txt
`option(WITH_DPDK "Enable DPDK messaging" OFF)` to `option(WITH_DPDK "Enable DPDK messaging" ON)`

But the cmake can't find DPDK, missing DPDK_INCLUDE_DIR and check_LIBRARIES. Do you have some tips or advice to modify the code to use DPDKStack as AsyncMessenger backend ?

**Comment by yuyuyu101** [comment]
I will rebase this  pr later

**Comment by uniqueyehu** [comment]
Good! What's the simplest way for me to test the DPDKStack in Ceph? I want to see the result of running DPDKStack.

**Comment by yuyuyu101** [comment]
@liewegas let's create a ceph/dpdk repo. dpdk repo isn't in github. so a empty repo that I could push is enough

**Comment by liewegas** [comment]
https://github.com/ceph/dpdk

**Comment by tchaikov** [comment]
@yuyuyu101  needs rebase

**Comment by yuyuyu101** [comment]
@tchaikov done

**Comment by tchaikov** [comment]
@yuyuyu101, could you fix the conflicts in `src/CMakeLists.txt`?

**Comment by yuyuyu101** [comment]
@tchaikov oh, sorry. missing conflicting..

**Comment by liewegas** [comment]
ok to merge as long as the cmake bits look okay to @alimaredia 

@yuyuyu101 can you rebase to resolve the boost submodule conflict?

**Comment by alimaredia** [comment]
@liewegas the cmake looks fine to me, only questions I have are does it build and test ok? and the test added to src/test/msgr/CMakeLists.txt is meant to be stand alone and not a unit test run via make-check right?

**Comment by yuyuyu101** [comment]
@alimaredia sure.

**Comment by candychencan** [comment]
Hi @yuyuyu101，I'm sorry to disturb you, but I'd like to ask you a question.We want to enable dpdk in the asynmessage module, Based on master branch our configuration is:
> ms_async_op_threads = 2
> ms_dpdk_coremask = 0x7
> ms_type = async+dpdk
> ms_dpdk_gateway_ipv4_addr=100.100.5.1
> ms_dpdk_host_ipv4_addr=100.100.5.229
> ms_dpdk_netmask_ipv4_addr=255.255.0.0

However, it has not been run successfully. Whether or not bound the igb_uio drive to the network port, ceph-s will report the following error:

> EAL: Detected 40 lcore(s)
> EAL: Detected 2 NUMA nodes
> EAL: Multi-process socket /var/run/dpdk/rte_client.admin/mp_socket
> EAL: Probing VFIO support...
> EAL: Error - exiting with code: 1
> Cause: No Ethernet ports - bye

Our questions:  
If we want to enable dpdk in the asynmessage module

> (1)Which version of ceph fully supports dpdk?
> (2)What are the correct configuration and operation steps?

Thank you!

**Pull request merged**
