### PR TITLE
doc: Correcting the sample python tempurl generation script.

### PR DESCRIPTION
**Pull request by diwakargoel**

### CODE REVIEW

**Comment by theanalyst** [comment]
LGTM, thanks for gettting this

**Comment by diwakargoel** [comment]
Can this be merged please?
Thanks!

**Comment by xiexingguo** [comment]
@diwakargoel 
Sorry. I am not familiar with RGW.

I am forwarding this to @theanalyst  and @yehudasa

**Comment by dicodeadmin** [comment]
thanks @xiexingguo 
just that it's been a while this got merged :)

**Pull request merged**
