### PR TITLE
monitoring/ceph-mixin: clean up prometheus_alerts.yml

### PR DESCRIPTION
**Pull request by anthonyeleven**
monitoring/ceph-mixin: clean up prometheus_alerts.yml

Fix various spelling and punctuation errors, improve wording.  Parallel changes to Rook via https://github.com/rook/rook/pull/10626

Signed-off-by: Anthony D'Atri <anthonyeleven@users.noreply.github.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [x] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Review by pereman2 — COMMENTED** [review]
Looks good! After tests are fixed I'll approve
```
[Test Result](https://jenkins.ceph.com/job/ceph-pull-requests/100155/testReport/) (1 failure / +1)
[projectroot.monitoring.ceph-mixin.run_promtool_unittests](https://jenkins.ceph.com/job/ceph-pull-requests/100155/testReport/junit/projectroot.monitoring/ceph-mixin/run_promtool_unittests/)
```

**Comment by anthonyeleven** [comment]
jenkins retest this please

**Comment by anthonyeleven** [comment]
Looks like I need to update tests to match.

**Comment by aaSharma14** [comment]
> Looks like I need to update tests to match.

Thanks @anthonyeleven for this PR. Yes, you need to update the test_alerts.yml file as well in sync with these changes.

**Comment by zdover23** [comment]
jenkins test make check

**Comment by anthonyeleven** [comment]
This PR sure turned out to be a rabbit-hole.  Hopefully this latest push will pass the promtool check.

**Comment by aaSharma14** [comment]
jenkins test dashboard

**Comment by aaSharma14** [comment]
jenkins test dashboard cephadm

**Comment by aaSharma14** [comment]
jenkins test windows

**Review by aaSharma14 — APPROVED** [review]
LGTM.! Thanks @anthonyeleven

**Review by pereman2 — APPROVED** [review]

**Pull request merged**
