### PR TITLE
mimic: restful: Query nodes_by_id for items

### PR DESCRIPTION
**Pull request by badone**
https://tracker.ceph.com/issues/42572

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`

</details>

### CODE REVIEW

**Comment by smithfarm** [comment]
@badone The 13.2.7 release is imminent and we're trying to get it ready for QE. Is this "stop the presses" urgent?

**Comment by smithfarm** [comment]
Apparently, it is. From the luminous PR:

```
Note: (06:05:23 PM) badone: yuriw: this one is going downstream so it would good if it gets in
``

**Comment by badone** [comment]
Luminous is, mimic isn't.

**Comment by b-ranto** [comment]
If I understand it right, we are doing last upstream version for luminous so it would be nice to get it in. It would get us to a weird state where luminous would have the fix before mimic but I wouldn't object to that.

**Comment by yuriw** [comment]
[wip-yuri7-testing-2019-10-31-2007-mimic](https://trello.com/c/u0xH4ulY/742-wip-yuri7-testing-2019-10-31-2007-mimic)

**Pull request merged**
