### PR TITLE
test: Improve scrub abort test

### PR DESCRIPTION
**Pull request by dzafman**
This works with ceph/ceph#38111

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by dzafman** [comment]
@ronen-fr @neha-ojha Based on the original test for deep-scrub abort, why wouldn't we see deep_scrub -> abort -> scrub.  How does setting of nodeep-scrub NOT trigger the log message "nodeep_scrub set, aborting"?

**Comment by ronen-fr** [comment]
Testing it now

**Comment by dzafman** [comment]
obsolete

**Comment by dzafman** [comment]
obsolete

**Pull request closed without merging**
