### PR TITLE
luminous: On pg repair the primary is not favored as was intended

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/22213

### CODE REVIEW

**Comment by smithfarm** [comment]
@dzafman I cherry-picked https://github.com/ceph/ceph/commit/689bff354a6bfa1cf47b0d0a04fa9f1b2ef68f75 as well, to avoid a conflict.

**Comment by Yan-waller** [comment]
retest this please

**Comment by Yan-waller** [comment]
jenkins retest this please

**Comment by dzafman** [comment]
@smithfarm Please remove 7532cbdd0806fe7c1a7328601f297433ca8d6c7b (the cherry-pick of 689bff3) and resolve the conflict so code diff looks like:

```
@@ -10806,10 +10813,6 @@ void PrimaryLogPG::mark_all_unfound_lost(
          }
        }

-       for (auto& p : waiting_for_unreadable_object) {
-         release_backoffs(p.first);
-       }
-       requeue_object_waiters(waiting_for_unreadable_object);
        queue_recovery();

        stringstream ss;
```

**Comment by dzafman** [comment]
@smithfarm Or wait for ceph/ceph#18965 to merge.

**Comment by smithfarm** [comment]
@dzafman OK, I'll consider this dependent upon #18965.

**Comment by dzafman** [comment]
retest this please

**Comment by yuriw** [comment]
[wip-yuri2-testing-2018-01-29-1733-luminous](https://trello.com/c/Hi2l9Gd8/246-wip-yuri2-testing-2018-01-29-1733-luminous)

**Pull request merged**
