### PR TITLE
common/pick_address: define in_addr_t if it is not defined

### PR DESCRIPTION
**Pull request by tchaikov**
mingw does not have in_addr_t defined, so define it if it is not
defined.

Signed-off-by: Kefu Chai <kchai@redhat.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by tchaikov** [comment]
cc @petrutlucian94

**Comment by tchaikov** [comment]
https://shaman.ceph.com/builds/ceph/wip-in_addr_t-kefu/b1dd995ae2ef657a09962a1d6b52a29c033ad9c1/

**Comment by tchaikov** [comment]
jenkins test docs

**Comment by tchaikov** [comment]
jenkins test make check

**Review by jdurgin — APPROVED** [review]

**Pull request merged**
