### PR TITLE
mon: refine check_remove_tier checks

### PR DESCRIPTION
**Pull request by jcsp**
Fixes: #11504
Signed-off-by: John Spray <john.spray@redhat.com>

### CODE REVIEW

**Comment by jcsp** [comment]
Quick patch, might need test updates...

**Comment by gregsfortytwo** [comment]
Reviewed-by:, but you're right we should check it on a few test runs first. (Not just FS tests)

**Comment by gregsfortytwo** [comment]
Actually, we have a bunch of tests around tiering but none that check its interaction with the FS. Please add some. (There are some tests for tiering manipulation in src/test/librados/tier.cc which I think we could reasonably extend to cover this.)

**Comment by gregsfortytwo** [comment]
What's here is in tonight's greg-fs-testing just to be sure we aren't all dumb.

**Comment by gregsfortytwo** [comment]
ping @jcsp. Doesn't appear to be breaking anything obvious but we do need to add some tests.

**Comment by jcsp** [comment]
@gregsfortytwo updated the cephtool test for these cases and added check for readonly tiers

**Comment by gregsfortytwo** [comment]
That failure was on a ceph-detect-init/run-tox.sh issue installing Pip.... @dachary, is that a common failure mode? I don't think we broke it here. ;)

**Comment by gregsfortytwo** [comment]
(have not reviewed code updates, will get them today)

**Comment by tchaikov** [comment]
i ran a 1/18 rados suite with this pull request at http://pulpito.ceph.redhat.com/kchai-2015-06-03_05:51:30-rados-wip-kefu-testing---basic-magna/ and the re-ran the failed ones at http://pulpito.ceph.redhat.com/kchai-2015-06-04_10:57:04-rados-wip-kefu-testing---basic-magna and http://pulpito.ceph.redhat.com/kchai-2015-06-04_10:56:19-rados-wip-kefu-testing---basic-magna, and the two failed tests passed.

**Comment by gregsfortytwo** [comment]
http://pulpito.ceph.com/gregf-2015-06-03_14:53:22-fs-greg-fs-testing-3---basic-multi/

**Pull request merged**
