### PR TITLE
build, DNM: pass -D_GLIBCXX_ASSERTIONS for all builds types.

### PR DESCRIPTION
**Pull request by rzarzynski**
Just for unveiling the `free()`-on-BSS in `std::string` that happened on incerta07. For details see: https://gist.github.com/rzarzynski/6a8916a6da28d40b87bef3f27c6d72d4.

Signed-off-by: Radoslaw Zarzynski <rzarzyns@redhat.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by rzarzynski** [comment]
Please be careful with the patch – it's supposed to actually fail a run.

**Comment by tchaikov** [comment]
see also #32387. i'd avoid adding this check for non-debug builds.

**Comment by wjwithagen** [comment]
> 
> 
> Please be careful with the patch – it's supposed to actually fail a run.

Then I'm not sure what to evaluate.
None the less, there is nothing like that defined on FreeBSD.
FreeBSD uses libc++ from the llvm project.
```
[/usr/srcs/head] wjw@zfs.digiware.nl> grep -R GLIBCXX_ASSERTIONS *
Exit 1
```
and as such we will run tinto the

**Comment by rzarzynski** [comment]
http://pulpito.front.sepia.ceph.com/rzarzynski-2020-03-18_14:44:45-free-on-bss-screening-wip-build-glibc-asserts-alwayson-distro-basic-smithi/

The patch is not supposed for merge. It's rationale was just to verify at sepia lab which of our supported distros are affected. Luckily, it looks the result is none. Closing.

**Pull request closed without merging**
