### PR TITLE
rgw/gc: Check for valid RadosStore for `radosgw-admin gc` cmd

### PR DESCRIPTION
**Pull request by soumyakoduri**
Signed-off-by: Soumya Koduri <skoduri@redhat.com>
Fixes: https://tracker.ceph.com/issues/59216

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by soumyakoduri** [comment]
@dang @cbodley  this issue (https://tracker.ceph.com/issues/59216) will arise for many of the radosgw-admin commands, which are applicable for only RadosStore. 

But since  'radosgw-admin gc' is included as part of generic teuthology cleanup, I have fixed it for only this command for now. Please let me know if this needs to be addressed for all the other cmds as well as part of this PR.

**Comment by dang** [comment]
> @dang @cbodley this issue (https://tracker.ceph.com/issues/59216) will arise for many of the radosgw-admin commands, which are applicable for only RadosStore.
> 
> But since 'radosgw-admin gc' is included as part of generic teuthology cleanup, I have fixed it for only this command for now. Please let me know if this needs to be addressed for all the other cmds as well as part of this PR.

No, I think we can just do the commands that hit in testing.  I have a mostly-done rework of radosgw-admin that restructures commands into common and per-store commands that will take care of them all.

**Comment by soumyakoduri** [comment]
> > @dang @cbodley this issue (https://tracker.ceph.com/issues/59216) will arise for many of the radosgw-admin commands, which are applicable for only RadosStore.
> > But since 'radosgw-admin gc' is included as part of generic teuthology cleanup, I have fixed it for only this command for now. Please let me know if this needs to be addressed for all the other cmds as well as part of this PR.
> 
> No, I think we can just do the commands that hit in testing. I have a mostly-done rework of radosgw-admin that restructures commands into common and per-store commands that will take care of them all.

thank Dan. Teuthology tests seem to be expecting this cmd to succeed. So I have updated the fix to throw warning instead and return 0.

**Comment by soumyakoduri** [comment]
http://pulpito.front.sepia.ceph.com/soumyakoduri-2023-04-05_03:56:38-rgw:dbstore-wip-skoduri-gc-cmd-distro-default-smithi/

**Comment by soumyakoduri** [comment]
jenkins test make check

**Pull request merged**
