### PR TITLE
doc/dev: Updated component leads table

### PR DESCRIPTION
**Pull request by LenzGr**
Updated the list [per our discussion on ceph-community](http://lists.ceph.com/pipermail/ceph-community-ceph.com/2018-September/000290.html) by adding some
component leads mentioned on https://ceph.com/team/

Signed-off-by: Lenz Grimmer <lgrimmer@suse.com>

- [ ] References tracker ticket
- [x] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by LenzGr** [comment]
jenkins render docs

**Comment by LenzGr** [comment]
Updated table: http://docs.ceph.com/ceph-prs/24238/dev/#leads

**Comment by LenzGr** [comment]
jenkins render docs

**Comment by LenzGr** [comment]
Removed @jcsp from the list per our conversation on IRC.

**Comment by liewegas** [comment]
retest this please

**Pull request merged**
