### PR TITLE
pacific: rgw/sts: adding code for aws:RequestTags as part

### PR DESCRIPTION
**Pull request by pritha-srivastava**
backport tracker: https://tracker.ceph.com/issues/52789

---

backport of https://github.com/ceph/ceph/pull/39849
parent tracker: https://tracker.ceph.com/issues/52788

this backport was staged using ceph-backport.sh version 16.0.0.6848
find the latest version at https://github.com/ceph/ceph/blob/master/src/script/ceph-backport.sh

### CODE REVIEW

**Review by anthonyeleven — APPROVED** [review]

**Comment by yuriw** [comment]
jenkins test this please

**Comment by yuriw** [comment]
jenkins test make check

**Comment by yuriw** [comment]
@pritha-srivastava @cbodley  this was tested but failed `make check` ref: https://trello.com/c/HMTzFEQO

**Comment by yuriw** [comment]
jenkins test make check

**Comment by adk3798** [comment]
jenkins test make check

**Comment by adk3798** [comment]
jenkins test make check

**Pull request merged**
