### PR TITLE
mimic: mgr/dashboard: cephfs multimds graphs stack together

### PR DESCRIPTION
**Pull request by bk201**
http://tracker.ceph.com/issues/40660

### CODE REVIEW

**Comment by bk201** [comment]
jenkins test dashboard

**Comment by bk201** [comment]
The `ceph dashboard tests` job fails with an error, need to re-test this PR after it's fixed.

**Comment by bk201** [comment]
Need to rebase and re-test after https://github.com/ceph/ceph/pull/28954 is merged.

**Comment by bk201** [comment]
rebased and retested because https://github.com/ceph/ceph/pull/28954 is merged.

**Comment by yuriw** [comment]
[wip-yuri4-testing-2019-07-23-1633-mimic](https://trello.com/c/G8TDc8rz/672-wip-yuri4-testing-2019-07-23-1633-mimic)

**Pull request merged**
