### PR TITLE
octopus: librbd: allow interrupted trash move request to be restarted

### PR DESCRIPTION
**Pull request by singuliere**
backport tracker: https://tracker.ceph.com/issues/49766

---

backport of https://github.com/ceph/ceph/pull/40010
parent tracker: https://tracker.ceph.com/issues/49716

this backport was staged using ceph-backport.sh version 16.0.0.6848
find the latest version at https://github.com/ceph/ceph/blob/master/src/script/ceph-backport.sh

### CODE REVIEW

**Comment by singuliere** [comment]
jenkins test this please

**Comment by singuliere** [comment]
jenkins test this please

**Comment by singuliere** [comment]
https://jenkins.ceph.com/job/ceph-pull-requests/74373/consoleText

```
189/198 Test  #10: run-rbd-unit-tests-61.sh ................***Failed  164.52 sec
++ dirname /home/jenkins-build/build/workspace/ceph-pull-requests/src/test/run-rbd-unit-tests.sh
+ source /home/jenkins-build/build/workspace/ceph-pull-requests/src/test/detect-build-env-vars.sh
++ '[' -n /home/jenkins-build/build/workspace/ceph-pull-requests/build ']'
++ '[' -n /home/jenkins-build/build/workspace/ceph-pull-requests ']'
++ '[' -n /home/jenkins-build/build/workspace/ceph-pull-requests/build/bin ']'
++ '[' -n /home/jenkins-build/build/workspace/ceph-pull-requests/build/lib ']'
++ echo 'Enivronment Variables Already Set'
Enivronment Variables Already Set
+ PATH=/home/jenkins-build/build/workspace/ceph-pull-requests/build/bin:/home/jenkins-build/build/workspace/ceph-pull-requests/build/bin:/home/jenkins-build/build/workspace/ceph-pull-requests/src:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
+ '[' 1 = 0 ']'
+ '[' 1 = 1 -a 61 = N ']'
+ TESTS=61
+ for i in ${TESTS}
+ RBD_FEATURES=61
+ unittest_librbd
seed 3836070
[==========] Running 977 tests from 88 test suites.
[----------] Global test environment set-up.
[----------] 2 tests from TestMockConfigWatcher
[ RUN      ] TestMockConfigWatcher.GlobalConfig
Failed to load class: cas (/home/jenkins-build/build/workspace/ceph-pull-requests/build/lib/libcls_cas.so): /home/jenkins-build/build/workspace/ceph-pull-requests/build/lib/libcls_cas.so: undefined symbol: _Z13cls_has_chunkPvNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
Failed to load class: log (/home/jenkins-build/build/workspace/ceph-pull-requests/build/lib/libcls_log.so): /home/jenkins-build/build/workspace/ceph-pull-requests/build/lib/libcls_log.so: undefined symbol: _Z24cls_cxx_map_write_headerPvPN4ceph6buffer7v15_2_04listE
Failed to load class: rgw (/home/jenkins-build/build/workspace/ceph-pull-requests/build/lib/libcls_rgw.so): /home/jenkins-build/build/workspace/ceph-pull-requests/build/lib/libcls_rgw.so: undefined symbol: _Z19cls_current_versionPv
Failed to load class: user (/home/jenkins-build/build/workspace/ceph-pull-requests/build/lib/libcls_user.so): /home/jenkins-build/build/workspace/ceph-pull-requests/build/lib/libcls_user.so: undefined symbol: _Z24cls_cxx_map_write_headerPvPN4ceph6buffer7v15_2_04listE
```

**Comment by singuliere** [comment]
jenkins run make check

**Comment by singuliere** [comment]
jenkins test make check

**Review by idryomov — APPROVED** [review]

**Pull request merged**
