### PR TITLE
common/Thread: cleanup

### PR DESCRIPTION
**Pull request by stiopaa1**

### CODE REVIEW

**Comment by dachary** [comment]
Here is an idea to factorize the review effort related to cleanups with bug fixes (in the spirit of https://github.com/ceph/ceph/blob/master/CONTRIBUTING.rst). You could keep these commits stashed locally and have a daily cron job that verifies they merge cleanly against all existing pull requests. As soon as you find a conflict, it means another pull request is doing work in the same area of the code. When that happens you can contribute the commit to the corresponding pull request and hitchhike on the pull request review.
By doing that you would have quicker reviews and the code quality would improve without a significant overhead. Although the iostream header changed was diligently reviewed, it is a good example of how time consuming code cleanup can be. And since they are code cleanups, they will always be at the bottom of the review list.
This is a little extra effort on your part (running the cron job and hitchhiking pull requests) but that's the best idea I have right now. What do you think ?

**Comment by stiopaa1** [comment]
>What do you think ?

I think that the code clean up(excluding coding style or whitespace modifications) shouldn't be only allowed as a part of a patch that fixes a bug or implements a feature(as per https://github.com/ceph/ceph/blob/master/CONTRIBUTING.rst). For a new person(like me) that doesn't yet know the codebase it makes it MUCH easier to understand what's going on if the code isn't misleading - example being the copy constructor and assignment operator being public in one of the changes above. I think that even if it will take one person some time to review things like that now, it will probably save much more for many people trying to understand the same code later. 
I imagine that there are parts of code that aren't modified very often, so how many people will waste some time trying to understand them(which could have been avoided), before they will be fixed as a part of patch?

Also what would be allowed as a clean up without fixing a bug? 
removing unnecessary header file? 
adding const to a function method?

I don't have to do code clean ups(even though it's going to be very difficult to stop myself from doing it:)), but it's just easy and convenient when I read through unknown code and I thought it would be useful for others. 

>You could keep these commits stashed locally and have a daily cron job that verifies they merge cleanly against all existing pull requests. As soon as you find a conflict, it means another pull request is doing work in the same area of the code.

I guess it can take months(or never) for some changes to find a conflict

>And since they are code cleanups, they will always be at the bottom of the review list.

And again here I think they shouldn't be, clean code is easier to understand and saves time in a long run.

**Comment by dachary** [comment]
Your advocacy for code cleanup makes sense. As #4707 demonstrates, the  https://github.com/ceph/ceph/blob/master/CONTRIBUTING.rst policy regarding cleanup is not 100% strictly applied. It is here primarily to make sure reviewers can point to it when code cleanups take a very long time to review, because there always are more important reviews in front of them. 

My suggestion really was a way to accelerate code reviews for your code cleanups. You are right, it may take months for a conflict to happen, but it may take even longer for a reviewer to find time to review a code cleanup such as https://github.com/stiopaa1/ceph/commit/0297d90a03595069d8e2c4e671fde188ae8f2617 because it requires very careful cross platform verification to assert the include really is unecessary. 

If you submit https://github.com/stiopaa1/ceph/commit/805ecacb7a9f0b1cefbdd8e6866e3f6beaadef01 as a separate pull request it will be accepted right away because there is no way for that to be wrong except if the compilation fails.

If you submit https://github.com/stiopaa1/ceph/commit/f074d39f5b9636cdc09b0b8580b72dfa12c93ffc as a separate commit it is probably less complicated than https://github.com/stiopaa1/ceph/commit/0297d90a03595069d8e2c4e671fde188ae8f2617 to verify but not as trivial as https://github.com/stiopaa1/ceph/commit/805ecacb7a9f0b1cefbdd8e6866e3f6beaadef0. For one, it removes the **explicit** from the contructor: it was added by d508510d708762ab95e6e20814e14269ad1320a6 and it would be worth asking @dalgaaf why it was necessary.

Today is Sunday and I don't mind spending time on non-essential task. And I very much appreciate your persistence and patience regarding cleanups. I hope you understand my point of view and won't be discouraged despite very long review delays.

**Comment by stiopaa1** [comment]
>For one, it removes the explicitfrom the contructor: it was added by d508510 and it would be worth asking @dalgaaf why it was necessary.

Explicit prevents implicitly calling copy constructor, but in this case it can't be called at all, since it's not defined. Danny Al-Gaaf didn't make any comment on adding the explicit keyword, which made me believe that the change was trivial and he probably got mislead by the copy constructor being public.

>You are right, it may take months for a conflict to happen, but it may take even longer for a reviewer to find time to review a code cleanup such as stiopaa1@0297d90 because it requires very careful cross platform verification to assert the include really is unecessary.

You are right here, after checking the history of when this was added, according to a comment it turns out it actually is needed on OS X - my mistake. Will remove this commit.

>My suggestion really was a way to accelerate code reviews for your code cleanups.
I don't mind waiting and from now on will try to submit them in as separate pull requests as possible.

> I hope you understand my point of view and won't be discouraged despite very long review delays.
I'm not that easily discouraged :)

**Comment by stiopaa1** [comment]
I'll submit those changes separately

**Pull request closed without merging**
