### PR TITLE
mgr/zabbix: Fix typo in key name for PGs in backfill_wait state

### PR DESCRIPTION
**Pull request by wido**
Fixes: http://tracker.ceph.com/issues/39666

Signed-off-by: Wido den Hollander <wido@42on.com>

### CODE REVIEW

**Comment by liewegas** [comment]
rebsae please?

**Comment by wido** [comment]
Rebased :-)

**Comment by tchaikov** [comment]
retest this please

**Comment by tchaikov** [comment]
- http://pulpito.ceph.com/kchai-2019-05-27_10:18:11-rados-wip-kefu-testing-2019-05-27-1206-distro-basic-smithi/
- http://pulpito.ceph.com/kchai-2019-05-28_01:35:41-rados-wip-kefu-testing-2019-05-27-1206-distro-basic-mira/

failures tracked by

- http://tracker.ceph.com/issues/23947
- http://tracker.ceph.com/issues/39644

**Pull request merged**
