### PR TITLE
rgw: removing account/tenant from the constructor

### PR DESCRIPTION
**Pull request by pritha-srivastava**
of bucket/object ARNs as Resourc ARNs do not have
an account.

This bug caused bucket policy evaluation to fail for cross-tenant access and same tenant access (except for same tenant access in the global/empty tenant).

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Comment by cbodley** [comment]
still thinking about this.. the problem with removing tenant names from bucket ARNs is that a tenant-level identity policy that Allows access to a Resource `arn:aws:s3:::bucketname` would grant access to that `bucketname` under all tenants

as discussed in https://github.com/ceph/ceph/pull/54333#discussion_r1499003596, we rely on [// You can't specify resources for someone ELSE'S account](https://github.com/ceph/ceph/blob/528a1eb/src/rgw/rgw_iam_policy.cc#L690-L694) to limit the scope of Resource conditions

for account-level identity policy, this isn't a problem because 'cross-account policy evaluation' requires the requested bucket to also have a resource policy that Allows the requesting principal

for resources other than buckets, we do include the 'account' part of their resource ARNs (where 'account' is the owning account id if one exists, or the tenant name otherwise). for bucket ARNs, we still don't want to include account ids, but i think we do need the tenant name after all

**Comment by pritha-srivastava** [comment]
> still thinking about this.. the problem with removing tenant names from bucket ARNs is that a tenant-level identity policy that Allows access to a Resource `arn:aws:s3:::bucketname` would grant access to that `bucketname` under all tenants
> 
> as discussed in [#54333 (comment)](https://github.com/ceph/ceph/pull/54333#discussion_r1499003596), we rely on [// You can't specify resources for someone ELSE'S account](https://github.com/ceph/ceph/blob/528a1eb/src/rgw/rgw_iam_policy.cc#L690-L694) to limit the scope of Resource conditions
> 
> for account-level identity policy, this isn't a problem because 'cross-account policy evaluation' requires the requested bucket to also have a resource policy that Allows the requesting principal
> 
> for resources other than buckets, we do include the 'account' part of their resource ARNs (where 'account' is the owning account id if one exists, or the tenant name otherwise). for bucket ARNs, we still don't want to include account ids, but i think we do need the tenant name after all

ok, I will look into this further. We can revert the change in get_iam_policy_from_attr(), but again we need to think about other failures that this might introduce

**Comment by cbodley** [comment]
> We can revert the change in get_iam_policy_from_attr(), but again we need to think about other failures that this might introduce

i do see the iam_account tests still passing with those `get_iam_policy_from_attr()` bits from https://github.com/ceph/ceph/commit/7d99cbdd09bcad81619b1c4770a663fde2b30563 reverted. i pushed a draft commit for that to https://github.com/cbodley/ceph/commit/706bb5dbb8b059d7c2f5b3c6fb9cfe75beb82b9d if you'd like to test/build on it

**Comment by pritha-srivastava** [comment]
I have updated the commit with the test results, hence will be closing this PR

**Pull request closed without merging**
