### PR TITLE
mon: allow removal of tier of ec overwritable pool

### PR DESCRIPTION
**Pull request by pdvian**
http://tracker.ceph.com/issues/22971

### CODE REVIEW

**Comment by kwaegema** [comment]
Is there a build for this on shaman/chakra.ceph.com for this PR? (We would like to use the rpms temporary on our mons to get rid of our cache pool)

**Comment by tchaikov** [comment]
@kwaegema i just pushed a branch to ceph-ci, see https://shaman.ceph.com/builds/ceph/wip-20433-luminous/ff06b298b04be35c10df5794b1061ae50ec2146b/ . hopefully the build will be available in 2 hours top.

**Comment by kwaegema** [comment]
thanks!

**Comment by yuriw** [comment]
[wip-yuri3-testing-2018-03-28-1639-luminous](https://trello.com/c/4teUwpYf/282-wip-yuri3-testing-2018-03-28-1639-luminous)

**Pull request merged**
