### PR TITLE
monitoring/ceph-mixin: add RGW host to label info

### PR DESCRIPTION
**Pull request by s0nea**
Add the missing information about the RGW instance to the labels of the "Average GET/PUT Latencies" panel on the "RGW Overview" dashboard.

Fixes: https://tracker.ceph.com/issues/57166
Signed-off-by: Tatjana Dehler <tdehler@suse.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [x] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Review by MrFreezeex — APPROVED** [review]
LGTM but wondering if this graph is really useful compared to "Get latencies by RGW instance" and "PUT Latencies by RGW instance"? Maybe one of them should be removed?

**Comment by pereman2** [comment]
jenkins test api

**Review by pereman2 — APPROVED** [review]

**Comment by s0nea** [comment]
> LGTM but wondering if this graph is really useful compared to "Get latencies by RGW instance" and "PUT Latencies by RGW instance"? Maybe one of them should be removed?

Oh, yes, you're right. These two panels look very similar to what I was planning to archive with the PR.

I'm not sure if we should just remove the "Average GET/PUT Latencies" panel. I'm wondering if the actual reason for this panel was to show the average GET/PUT latencies over all instances? That way we will have one graph for "GET AVG" and one for "PUT AVG".

**Comment by MrFreezeex** [comment]
> > LGTM but wondering if this graph is really useful compared to "Get latencies by RGW instance" and "PUT Latencies by RGW instance"? Maybe one of them should be removed?
> 
> Oh, yes, you're right. These two panels look very similar to what I was planning to archive with the PR.
> 
> I'm not sure if we should just remove the "Average GET/PUT Latencies" panel. I'm wondering if the actual reason for this panel was to show the average GET/PUT latencies over all instances? That way we will have one graph for "GET AVG" and one for "PUT AVG".

Usually for those types of panel you would get the average, and the q50, q99 quantiles. That way it would probably be more useful... But I don't think there is the metrics to do that. We probably need to expose an histogram to prometheus and the mgr prometheus module doesn't even support that right now...

**Comment by s0nea** [comment]
I spoke to the dashboard team about the PR in the stand-up. We agreed on keeping the PR. Even though it doesn't add much additional information it is still improving the average latencies panel.

**Comment by s0nea** [comment]
jenkins test dashboard cephadm

**Pull request merged**
