### PR TITLE
msg/simple: close the failed socket fds

### PR DESCRIPTION
**Pull request by Yan-waller**
Maybe we should close the socket file descriptor 
while bind/listen failed, avoid consuming socket fds.

Signed-off-by: Yan Jun <yan.jun8@zte.com.cn>

### CODE REVIEW

**Comment by Yan-waller** [comment]
retest this please

**Comment by Yan-waller** [comment]
@tchaikov , Hi sir, How do you think about this?

**Comment by tchaikov** [comment]
@Yan-waller will take a look this PR tomorrow.

**Comment by liewegas** [comment]
lgtm

**Comment by yuriw** [comment]
http://pulpito.ceph.com/yuriw-2016-09-19_19:42:27-rados-wip-yuri-testing2_2016_09_19-distro-basic-smithi/

rerun http://pulpito.ceph.com/yuriw-2016-09-20_14:50:21-rados-wip-yuri-testing2_2016_09_19-distro-basic-smithi/

**Pull request merged**
