### PR TITLE
mgr/dashboard: allow selecting all daemons for Orchestrator NFS clusters

### PR DESCRIPTION
**Pull request by bk201**
Allow users to select or deselect all daemons with a single click in NFS
export form when the cluster type is Orchestrator.

Fixes: https://tracker.ceph.com/issues/48176
Signed-off-by: Kiefer Chang <kiefer.chang@suse.com>

## Screenshots

For **User (legacy)** clusters, the behavior is the same as before. An individual daemon can be selected or deselected:

Screen Shot 2020-11-11 at 12 36 13 PM

Screen Shot 2020-11-11 at 12 36 45 PM

For **Orchestrator** clusters, user can click the button to select or deselect all daemons at once.

Screen Shot 2020-11-11 at 12 36 34 PM

Screen Shot 2020-11-11 at 12 36 56 PM

## Checklist
- [x] References tracker ticket
- [x] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by tchaikov** [comment]
jenkins test make check

**Review by alfonsomthd — APPROVED** [review]

**Comment by bk201** [comment]
jenkins test dashboard

**Review by mgfritch — APPROVED** [review]

**Comment by bk201** [comment]
jenkins test dashboard

**Comment by bk201** [comment]
jenkins test api

**Comment by bk201** [comment]
jenkins test dashboard

**Comment by bk201** [comment]
jenkins test dashboard

**Comment by avanthakkar** [comment]
jenkins test dashboard

**Review by avanthakkar — APPROVED** [review]

**Comment by bk201** [comment]
jenkins test dashboard

**Comment by bk201** [comment]
jenkins test dashboard

**Comment by bk201** [comment]
jenkins test dashboard

**Comment by bk201** [comment]
jenkins test dashboard

**Pull request merged**
