### PR TITLE
debian/control: fix python3-cherrypy*3* dependency

### PR DESCRIPTION
**Pull request by koenkooi**
The trailing '3' was missed in one instance, ceph-mgr-cephadm, leading to:

	Some packages could not be installed. This may mean that you have
	requested an impossible situation or if you are using the unstable
	distribution that some required packages have not yet been created
	or been moved out of Incoming.
	The following information may help to resolve the situation:

	The following packages have unmet dependencies:
	 ceph-mgr-cephadm : Depends: python3-cherrypy but it is not installable

Which makes the installation fail.

Fixes: 78983ad0d0cce422da32dc4876ac186f6d32c3f5
Signed-off-by: Koen Kooi <koen@softiron.com>

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [x] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Review by adk3798 — APPROVED** [review]
Thanks for catching this!

**Comment by koenkooi** [comment]
Any ETA on when this will go in? It would be nice to have debian packages that actually install for quincy and master.

**Comment by tchaikov** [comment]
just pushed this change to ceph-ci, see https://shaman.ceph.com/builds/ceph/pr-45142-kefu/b7b381fe91c0711249a7185b31f3dd60064f3b5a/ 

if it compiles fine, should be good to merge.

**Comment by cbodley** [comment]
we've been seeing shaman build failures only on ubuntu since yesterday. for example, in https://shaman.ceph.com/builds/ceph/wip-cbodley-testing/d1a030e728c6f55fb9a372cc96c5180a96de7833/default/299888/ i'm seeing this failure:
```
dh_install: warning: Cannot find (any matches for) "usr/lib/python3*/dist-packages/ceph_argparse.py" (tried in ., debian/tmp)

dh_install: warning: python3-ceph-argparse missing files: usr/lib/python3*/dist-packages/ceph_argparse.py
dh_install: warning: Cannot find (any matches for) "usr/lib/python3*/dist-packages/ceph_daemon.py" (tried in ., debian/tmp)

dh_install: warning: python3-ceph-argparse missing files: usr/lib/python3*/dist-packages/ceph_daemon.py
dh_install: error: missing files, aborting
```
is it possible that this PR is related?

**Comment by cbodley** [comment]
^ sorry for the false alarm, it looks like this broke in https://github.com/ceph/ceph/pull/45648

**Pull request merged**
