### PR TITLE
reef: mgr/dashboard: Cloning subvolume not listing _nogroup if no subvolume

### PR DESCRIPTION
**Pull request by dnyanee1997**
backport tracker: https://tracker.ceph.com/issues/68200

backport of: https://github.com/ceph/ceph/pull/59595

parent tracker: https://tracker.ceph.com/issues/67891

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [x] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Review by afreen23 — CHANGES_REQUESTED** [review]
There is no cherry-pick commit here.
The right process is to use backport script and resolve conflicts, see [this](https://github.com/ceph/ceph/blob/main/SubmittingPatches-backports.rst#the-ceph-backportsh-script).

If you get conflicts during cherry picking, make sure to uncomment conflicts section.
See [this](https://github.com/ceph/ceph/pull/59819/commits/8f055c18fc859706f99d8d1b2fff5ddd4f27fc77) for example.

Also if you are new to cherrypicking see [this](https://www.atlassian.com/git/tutorials/cherry-pick#:~:text=Cherry%20picking%20is%20the%20act,to%20where%20it%20should%20belong.) to get an idea.

Thanks

**Comment by dnyanee1997** [comment]
@afreen23 Can you please check now. I have updated the PR.

**Comment by dnyanee1997** [comment]
@afreen23 Can you please help me this fail test run Run actions/add-to-project@4756e6330fe1e0a736690d3cfd9f11c9399c2ed4
Error: Request failed due to following response errors:
 - Could not resolve to a ProjectV2 with the number 2.

**Comment by dnyanee1997** [comment]
jenkins test make check

**Comment by dnyanee1997** [comment]
jenkins test dashboard cephadm

**Comment by nizamial09** [comment]
> Can you please help me this fail test run->>

i fixed that a long ago but its not backported to reef i guess. in any case we can ignore it for now,

**Review by nizamial09 — APPROVED** [review]

**Review by afreen23 — APPROVED** [review]

**Pull request merged**
