### PR TITLE
rbd: add continuous burst capability for rbd

### PR DESCRIPTION
**Pull request by maydaycc**
This commit modify the design of token bucket to support duration controllable continuous burst

Fixes: https://tracker.ceph.com/issues/45313
Signed-off-by: Wencong Wan <wanwc@chinatelecom.cn>

## Checklist
- [x] References tracker ticket
- [x] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by maydaycc** [comment]
@xiexingguo Sorry, I forgot to label it. it seems that no body see this PR. please have a look.Thank you.

**Comment by maydaycc** [comment]
libvirt supports burst duration control since 2.4.0 (QEMU version >= 2.6), this PR gives RBD throttle the same capabilities.

burst duration can be controlled by burst length

e.g. set iops_limit = 1000、iops_burst = 5000、iops_burst_length = 60 , the duration t meets formula
5000*60 + 1000*t = 5000*t  =>  t = 75 seconds

**Comment by dillaman** [comment]
As a heads-up, the QoS layer is being refectored so this will need to wait until after that gets merged [1] in the next couple weeks.

[1] https://github.com/dillaman/ceph/blob/wip-45137/src/librbd/io/QosImageDispatch.cc

**Comment by maydaycc** [comment]
> As a heads-up, the QoS layer is being refectored so this will need to wait until after that gets merged [1] in the next couple weeks.
> 
> [1] https://github.com/dillaman/ceph/blob/wip-45137/src/librbd/io/QosImageDispatch.cc

Got it

**Comment by dillaman** [comment]
Needs to be rebased on the new `QoSImageDispatch` class

**Comment by maydaycc** [comment]
@dillaman I moved the work to another PR，https://github.com/ceph/ceph/pull/35138

**Pull request closed without merging**
