### PR TITLE
nautilus: bluestore: 50-100% iops lost due to bluefs_preextend_wal_files = false

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/40281

### CODE REVIEW

**Comment by yuriw** [comment]
[wip-yuri4-testing-2019-07-31-1623-nautilus](https://trello.com/c/Tqzpc0wj/680-wip-yuri4-testing-2019-07-31-1623-nautilus)

**Comment by umuzhaohui** [comment]
really

**Comment by smithfarm** [comment]
@umuzhaohui 

> ceph version：13.2.1 mimic

This fix was released in Nautilus 14.2.3 - it's definitely not in Mimic 13.2.1. That version is very old.

**Comment by liewegas** [comment]
This performance difference only happens for the first bit of data written after a brand new bluestore instance is created.  It mostly only matters for performance testing on test clusters and users to run a performance test as the very first thing on an empty cluster.  Once rocksdb has written a few wal files the performance is the same.

**Pull request merged**
