### PR TITLE
DNM: debian: build using cmake

### PR DESCRIPTION
**Pull request by liewegas**

### CODE REVIEW

**Comment by liewegas** [comment]
This built on our one-off xenial builder; @dmick is updating the others now.  Once it's green on all of them we can merge!

**Comment by liewegas** [comment]
Actually, no, we also need to run it through teuthology to make sure the generated code isn't broken somehow.

**Comment by tchaikov** [comment]
tested at http://pulpito.ceph.com/kchai-2016-06-26_19:17:04-rados-wip-cmake-debian---basic-mira/

**Comment by tchaikov** [comment]
tested at http://pulpito.ceph.com/kchai-2016-06-27_01:53:11-rados-wip-cmake-debian---basic-mira/

**Comment by tchaikov** [comment]
```
2016-06-27T07:09:17.284 INFO:teuthology.orchestra.run.mira012:Running: 'adjust-ulimits ceph-coverage /home/ubuntu/cephtest/archive/coverage rados --cluster ceph rmpool unique_pool_0 unique_pool_0 --yes-i-really-really-mean-it'
2016-06-27T07:09:17.315 INFO:teuthology.orchestra.run.mira082:Running: 'sudo adjust-ulimits ceph-coverage /home/ubuntu/cephtest/archive/coverage timeout 30 ceph --cluster ceph --admin-daemon /var/run/ceph/ceph-osd.3.asok dump_historic_ops'
2016-06-27T07:09:17.323 INFO:teuthology.orchestra.run.mira012.stderr:warning: line 36: 'osd_pool_default_size' in section 'global' redefined
2016-06-27T07:09:17.336 INFO:teuthology.orchestra.run.mira012.stderr:2016-06-27 14:09:17.646058 7fe2b8b9e640 -1 WARNING: the following dangerous and experimental features are enabled: *
2016-06-27T07:09:17.336 INFO:teuthology.orchestra.run.mira012.stderr:2016-06-27 14:09:17.646250 7fe2b8b9e640 -1 WARNING: the following dangerous and experimental features are enabled: *
2016-06-27T07:09:17.337 INFO:teuthology.orchestra.run.mira012.stderr:2016-06-27 14:09:17.647750 7fe2b8b9e640 -1 WARNING: the following dangerous and experimental features are enabled: *
2016-06-27T07:09:17.494 INFO:teuthology.orchestra.run.mira082:Running: 'sudo adjust-ulimits ceph-coverage /home/ubuntu/cephtest/archive/coverage timeout 30 ceph --cluster ceph --admin-daemon /var/run/ceph/ceph-osd.5.asok dump_ops_in_flight'
2016-06-27T07:09:17.672 INFO:teuthology.orchestra.run.mira082:Running: 'sudo adjust-ulimits ceph-coverage /home/ubuntu/cephtest/archive/coverage timeout 30 ceph --cluster ceph --admin-daemon /var/run/ceph/ceph-osd.5.asok dump_blocked_ops'
2016-06-27T07:09:17.854 INFO:teuthology.orchestra.run.mira082:Running: 'sudo adjust-ulimits ceph-coverage /home/ubuntu/cephtest/archive/coverage timeout 30 ceph --cluster ceph --admin-daemon /var/run/ceph/ceph-osd.5.asok dump_historic_ops'
2016-06-27T07:09:17.937 INFO:teuthology.orchestra.run.mira012:Running: 'sudo adjust-ulimits ceph-coverage /home/ubuntu/cephtest/archive/coverage timeout 120 ceph --cluster ceph osd set noscrub'
2016-06-27T07:09:17.951 INFO:teuthology.orchestra.run.mira012.stdout:successfully deleted pool unique_pool_0
2016-06-27T07:09:17.955 INFO:teuthology.orchestra.run.mira012.stderr:*** Error in `rados': double free or corruption (fasttop): 0x0000000000946af0 ***
2016-06-27T07:09:17.956 INFO:teuthology.orchestra.run.mira012.stderr:*** Caught signal (Aborted) **
2016-06-27T07:09:17.956 INFO:teuthology.orchestra.run.mira012.stderr: in thread 7fe2b8b9e640 thread_name:rados
2016-06-27T07:09:17.971 INFO:teuthology.orchestra.run.mira012.stderr: ceph version v10.2.0-2789-gebb2be0 (ebb2be0bc1b1d73f8ceb880a7265b578d151200b)
2016-06-27T07:09:17.971 INFO:teuthology.orchestra.run.mira012.stderr: 1: (ceph::BackTrace::BackTrace(int)+0x2d) [0x7fe2af874fff]
2016-06-27T07:09:17.971 INFO:teuthology.orchestra.run.mira012.stderr: 2: (()+0x1f0a307) [0x7fe2afa45307]
2016-06-27T07:09:17.971 INFO:teuthology.orchestra.run.mira012.stderr: 3: (()+0x10340) [0x7fe2a3fb0340]
2016-06-27T07:09:17.971 INFO:teuthology.orchestra.run.mira012.stderr: 4: (gsignal()+0x39) [0x7fe2a31edcc9]
2016-06-27T07:09:17.972 INFO:teuthology.orchestra.run.mira012.stderr: 5: (abort()+0x148) [0x7fe2a31f10d8]
2016-06-27T07:09:17.972 INFO:teuthology.orchestra.run.mira012.stderr: 6: (()+0x73394) [0x7fe2a322a394]
2016-06-27T07:09:17.972 INFO:teuthology.orchestra.run.mira012.stderr: 7: (()+0x7f66e) [0x7fe2a323666e]
2016-06-27T07:09:17.972 INFO:teuthology.orchestra.run.mira012.stderr: 8: (librados::NObjectIterator::~NObjectIterator()+0x29) [0x7fe2af31d521]
2016-06-27T07:09:17.972 INFO:teuthology.orchestra.run.mira012.stderr: 9: (__cxa_finalize()+0x9a) [0x7fe2a31f35ea]
2016-06-27T07:09:17.972 INFO:teuthology.orchestra.run.mira012.stderr: 10: (()+0xd0ffc3) [0x7fe2a4ecdfc3]
```

see http://qa-proxy.ceph.com/teuthology/kchai-2016-06-27_01:53:11-rados-wip-cmake-debian---basic-mira/279593/teuthology.log in http://pulpito.ceph.com/kchai-2016-06-27_01:53:11-rados-wip-cmake-debian---basic-mira/279593/

**Comment by tchaikov** [comment]
i tested the deb package in situ. no "double free" error spotted when using rados cli. maybe should try test in sepia instead.

**Comment by tchaikov** [comment]
changelog

- added fix for "double free"
- set `CMAKE_POSITION_INDEPENDENT_CODE` instead of adding `-fPIC` in `CMAKE_C_FLAGS`

**Comment by tchaikov** [comment]
tested at http://pulpito.ceph.com/kchai-2016-06-29_03:52:56-rados-wip-cmake-debian---basic-smithi/

**Comment by tchaikov** [comment]
closing, this changeset was already merged by accident.

**Pull request closed without merging**
