### PR TITLE
doc/release_notes: fix spacing in bulleted list

### PR DESCRIPTION
**Pull request by zdover23**
Signed-off-by: Zac Dover <zac.dover@gmail.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by liewegas** [comment]
jenkins render docs

**Comment by liewegas** [comment]
retest this please

**Comment by tchaikov** [comment]
i'd suggest use subsections instead of unordered lists for representing the components.

**Comment by tchaikov** [comment]
see #33940

**Comment by tchaikov** [comment]
closing in favor of #33940

**Pull request closed without merging**
