### PR TITLE
add monitoring subdir and Grafana cluster dashboard

### PR DESCRIPTION
**Pull request by jan--f**
Signed-off-by: Jan Fajerski <jfajerski@suse.com>

### CODE REVIEW

**Comment by jcsp** [comment]
:+1: seems like a reasonable place to start

**Comment by LenzGr** [comment]
Adding the "dashboard" label, as the Ceph Mgr dashboard intends to embed these Grafana dashboards into its UI (see #21644 for details)

**Comment by LenzGr** [comment]
Thanks for testing @YWatchman ! I'd be in favor of merging this dashboard, in order to have a "placeholder" and something that we can test the embedding into the Mgr Dashboard against. We could then extend and improve this incrementally.

**Comment by jan--f** [comment]
Thx indeed @YWatchman. Ready to merge...the failing make check has nothing to do with this PR.

**Comment by YWatchman** [comment]
Good to hear that @jan--f ! I hope to see it merged soon.

**Comment by jcsp** [comment]
@pcuzner @epuertat any thoughts?  I don't think any competing PRs have appeared, so shall we merge this?

**Comment by pcuzner** [comment]
No issues from me - makes complete sense at least to validate the grafana integration.

**Pull request merged**
