### PR TITLE
Updated jest to fix cache failure

### PR DESCRIPTION
**Pull request by Devp00l**
Fixes: https://tracker.ceph.com/issues/45545
Signed-off-by: Stephan Müller <smueller@suse.com>

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by Devp00l** [comment]
Unit tests have passed :) Much quicker than without using the cache in only 10m 43s :)
 
> 195/195 Test #141: mgr-dashboard-frontend-unittests ........   Passed  643.29 sec

**Comment by Devp00l** [comment]
jenkins test make check

**Comment by tspmelo** [comment]
jenkins test make check

**Comment by tspmelo** [comment]
jenkins test make check

**Comment by alfonsomthd** [comment]
@Devp00l @tspmelo Should this be backported to octopus?

**Pull request merged**
