### PR TITLE
osd: mark modified region as dirty when tier-evict is called

### PR DESCRIPTION
**Pull request by myoungwon**
This commit adds missing part that marks dirty after making sparse file. Without this change, existing code causes wrong range calculation when making push op---send push op with wrong dataset.

Signed-off-by: Myoungwon Oh <myoungwon.oh@samsung.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Review by athanatos — APPROVED** [review]

**Comment by myoungwon** [comment]
https://pulpito.ceph.com/lflores-2022-10-14_15:19:18-rados-wip-yuri6-testing-2022-10-05-0912-distro-default-smithi/

@ljflores  Hm.. all failures are not related to this PR. Any other issues?

**Comment by ljflores** [comment]
Hey @myoungwon, my apologies for missing your message. I remember what happened with this run; there were some infrastructure failures that made it hard to determine if jobs were truly passing or not. Then, the sepia lab went down and delayed us for several weeks.

Yuri is currently rerunning some tests on this PR so we can get clean runs w/o infrastructure failures. I'll report here with a summary.

**Comment by myoungwon** [comment]
@ljflores Great. Thanks for your kind explanation. I'll look forward to your report.

**Comment by ljflores** [comment]
Rados suite review: https://pulpito.ceph.com/?branch=wip-yuri6-testing-2022-11-23-1348

Failures, unrelated:
    1. https://tracker.ceph.com/issues/58098
    2. https://tracker.ceph.com/issues/58096
    3. https://tracker.ceph.com/issues/57311
    4. https://tracker.ceph.com/issues/58097
    5. https://tracker.ceph.com/issues/57731
    6. https://tracker.ceph.com/issues/57311
    7. https://tracker.ceph.com/issues/51945

Details:
    1. qa/workunits/rados/test_crash.sh: crashes are never posted - Ceph - RADOS
    2. test_cluster_set_reset_user_config: NFS mount fails due to missing ceph directory - Ceph - Orchestrator
    3. rook: ensure CRDs are installed first - Ceph - Orchestrator
    4. qa/workunits/post-file.sh: kex_exchange_identification: read: Connection reset by peer - Infrastructure
    5. Problem: package container-selinux conflicts with udica < 0.2.6-1 provided by udica-0.2.4-1 - Infrastructure
    6. qa/tasks/rook times out: 'check osd count' reached maximum tries (90) after waiting for 900 seconds - Ceph - Orchestrator
    7. qa/workunits/mon/caps.sh: Error: Expected return 13, got 0 - Ceph - RADOS

**Comment by ljflores** [comment]
@myoungwon this looks good! Merging.

**Pull request merged**
