### PR TITLE
 nautilus:  mgr/dashboard: Queue notifications as default

### PR DESCRIPTION
**Pull request by Devp00l**
http://tracker.ceph.com/issues/39560

### CODE REVIEW

**Comment by yuriw** [comment]
[wip-yuri2-testing-2019-05-16-1555-nautilus](https://trello.com/c/VvCEDimT/616-wip-yuri2-testing-2019-05-16-1555-nautilus)

**Comment by smithfarm** [comment]
jenkins retest this please

**Comment by ricardoasmarques** [comment]
jenkins retest this please

**Comment by smithfarm** [comment]
jenkins re-test this please

**Comment by smithfarm** [comment]
Test failure is possibly caused by:

```
+ source /etc/os-release
./do_cmake.sh: 9: ./do_cmake.sh: source: not found
```

Fix pending at https://github.com/ceph/ceph/pull/28181 (needs review)

**Comment by smithfarm** [comment]
jenkins re-test this please

**Comment by smithfarm** [comment]
jenkins re-test this please

**Comment by yuriw** [comment]
@Devp00l  @LenzGr this passed tests. pls merge at will, I am hesitant as see ceph dashboard tests failed

**Comment by epuertat** [comment]
jenkins test dashboard

**Comment by epuertat** [comment]
jenkins test dashboard

**Comment by callithea** [comment]
jenkins test dashboard

**Comment by callithea** [comment]
jenkins test dashboard

**Comment by callithea** [comment]
jenkins test dashboard

**Pull request merged**
