### PR TITLE
rgw: fix set removed zone master will affect original zonegroup

### PR DESCRIPTION
**Pull request by tianshan**
make period epoch always go forward in spite of switch master

Fixes: http://tracker.ceph.com/issues/36027

Signed-off-by: Tianshan Qu <tianshan@xsky.com>

### CODE REVIEW

**Comment by tianshan** [comment]
The issue is: zonegroup have zones z1, z2; (e.g. realm_epoch 2, period epoch 3)
operations order:
1.zonegroup remove z2 in cluster z1, period update --commit (realm_epoch 2, period epoch 4)
2.zone modify master in z2 (realm_epoch 3, period epoch 1)
then, zonegroup will have two zones again in cluster z1, and z1 become slave zone, which is not expected.

I'm not sure this is a good fix, we still should remove z1 in cluster z2 right after switch master,  to ensure not affect z1 in future.

And another idea is record a predecessor_epoch = <realm_epoch>.<period_epoch>, but will make switch master much more strict.

**Comment by tianshan** [comment]
@cbodley  any suggestions?

**Comment by cbodley** [comment]
thanks @tianshan - so the intent of those commands is to split those zones into two distinct multisite configurations?

i think the best way to do that would be to create a new realm on that second cluster, and add use `zone modify --master --realm-id` to add its zone to a zonegroup in that new realm. this way you start with a fresh period that's completely disconnected from the original

**Comment by tianshan** [comment]
@cbodley  yes, recreate realm will solve the issue. at fist I think we should add some measure to prevent mis operation, since removed zone come back is not big issue, we may leave this to somewhere in document.

**Pull request closed without merging**
