### PR TITLE
reef: mds: fix stray evaluation using scrub and introduce new option

### PR DESCRIPTION
**Pull request by dparmar18**
Backport tracker: https://tracker.ceph.com/issues/59260, https://tracker.ceph.com/issues/59263
Backport of https://github.com/ceph/ceph/pull/47649
Parent tracker: https://tracker.ceph.com/issues/53724, https://tracker.ceph.com/issues/51824

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [x] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [x] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by ljflores** [comment]
Rados suite review: https://pulpito.ceph.com/?branch=wip-yuri6-testing-2023-04-26-1247-reef

Failures, unrelated:
    1. https://tracker.ceph.com/issues/59049
    2. https://tracker.ceph.com/issues/59057
    3. https://tracker.ceph.com/issues/59142
    4. https://tracker.ceph.com/issues/58797

Details:
    1. WaitReplicas::react(const DigestUpdate&): Unexpected DigestUpdate event - Ceph - RADOS
    2. rados/test_envlibrados_for_rocksdb.sh: No rule to make target 'rocksdb_env_librados_test' on centos 8 - Ceph - RADOS
    3. mgr/dashboard: fix e2e for dashboard v3 - Ceph - Mgr - Dashboard
    4. scrub/osd-scrub-dump.sh: TEST_recover_unexpected fails from "ERROR: Unexpectedly low amount of scrub reservations seen during test" - Ceph - RADOS

**Comment by yuriw** [comment]
ref: https://trello.com/c/A5LEquRG

**Comment by dparmar18** [comment]
> @dparmar18
> 
> IRC chat:
> 
> dparmar: #50813 dparmar: A follow up fix is required for the above backport, yes? IIRC, there is a ticket related to an MDS crash when scrubbing mdsdir...

this already addresses the crash

**Comment by dparmar18** [comment]
> > > @dparmar18
> > > IRC chat:
> > > dparmar: #50813 dparmar: A follow up fix is required for the above backport, yes? IIRC, there is a ticket related to an MDS crash when scrubbing mdsdir...
> > 
> > 
> > this already addresses the crash
> 
> Update from IRC chat:
> 
> > dparmar: first two commits in the pr address it
> > overclk: dparmar: https://tracker.ceph.com/issues/59350
> > overclk: Isn't this issue related to scrubbing mdsdir?
> > overclk: So,  there is a bug lurking somewhere that needs fixing.
> > dparmar: https://tracker.ceph.com/issues/59350#note-6
> > dparmar: i had tested this rigorously at the time of publishing this pr and also ran some jobs at the time of reporting this tracker https://tracker.ceph.com/issues/59350#note-5 and it went fine. somehow output's "scrubs" key is empty
> > overclk: dparmar: but it does seem like there is a bug somewhere - probably in the qa suite.
> > overclk: Let's hold back merging the backport till this is RCA'd

Comment addressed in #51539, added its commits

**Comment by vshankar** [comment]
jenkins test make check

**Comment by vshankar** [comment]
jenkins test make check

**Review by vshankar — APPROVED** [review]
https://tracker.ceph.com/projects/cephfs/wiki/Reef#31-July-2023

**Pull request merged**
