### PR TITLE
pacific: debian: mark "make check" deps with "pkg.ceph.check" build

### PR DESCRIPTION
**Pull request by djgalloway**
instead of inventing our way for defining "make check" dependencies, use
build profile for adding "make check" specific dependencies. see
https://wiki.debian.org/BuildProfileSpec

Signed-off-by: Kefu Chai <kchai@redhat.com>
(cherry picked from commit c0fad448e98d58fc977631a086a91c3decfef0ce)

### CODE REVIEW

**Comment by djgalloway** [comment]
This _still_ isn't putting jsonnet into the ceph-build-deps package...

**Comment by djgalloway** [comment]
@tchaikov when/if you have a moment, could you take a look at this please?  I'm not sure what I'm missing.  Trying to resolve https://tracker.ceph.com/issues/55059

**Comment by tchaikov** [comment]
> > @djgalloway .
> > > @tchaikov when/if you have a moment, could you take a look at this please? I'm not sure what I'm missing. Trying to resolve https://tracker.ceph.com/issues/55059
> > 
> > 
> > hi David, i think this change should do the trick. could you paste the link to the "this still isn't putting ..." failure?
> 
> https://jenkins.ceph.com/job/ceph-pull-requests/92516/ Ctrl+F "jsonnet" ... nowhere in the job.

@djgalloway 

neither does it include `libgoogle-perftools-dev` or `libexpat1-dev` despite that they are listed as a `Build-Depends` in `debian/control` . in other words, i don't think `jsonnet` have to exist in the output if it is considered as one of the `Build-Depends` and is installed by `mk-build-deps`.

**Comment by djgalloway** [comment]
Ah fair point.  Okay.  Thank you Kefu.

**Comment by ljflores** [comment]
Closing this, as Pacific is going EOL. Feel free to reopen and add it to https://github.com/ceph/ceph/milestone/17 if it needs to be there.

**Pull request closed without merging**
