### PR TITLE
osd/pg_scrubber: do not print log in dtors

### PR DESCRIPTION
**Pull request by tchaikov**
## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by tchaikov** [comment]
@ronen-fr what do you think about the commits of 

- osd/pg_scrubber: use tab-width:8 (043356c)
- osd/pg_scrubber: use unsigned for PgScrubber::m_left (3b5bebf)

can we have them in master?

**Comment by ronen-fr** [comment]
> @ronen-fr what do you think about the commits of
> 
> * osd/pg_scrubber: use tab-width:8 ([043356c](https://github.com/ceph/ceph/commit/043356c0b1f84eda83071e8dbff380feeba2a99f))
> * osd/pg_scrubber: use unsigned for PgScrubber::m_left ([3b5bebf](https://github.com/ceph/ceph/commit/3b5bebfe73c470b7d6ea2cfc7b09c8ad80c82b50))
> 
> can we have them in master?

The tab - sure. My mistake in getting this temp change into the code. Was trying to force vscode to behave.

Re the uint change: I subscribe to the "unsigned should only be used for bitmasks" school. See, for example,
Google styleguide:
"You should not use the unsigned integer types such as uint32_t, unless there is a valid reason such as representing a bit pattern rather than a number, or you need defined overflow modulo 2^N. In particular, do not use unsigned types to say a number will never be negative. Instead, use assertions for this."

I would suggest that using an unsigned in a role that involves some subtract and compare operations leads to compiler warnings, extra checks, and bugs.

**Comment by tchaikov** [comment]
@ronen-fr thanks for your reply. will create a separate PR for the tab stuff.

**Comment by neha-ojha** [comment]
jenkins retest this please

**Comment by tchaikov** [comment]
- https://pulpito.ceph.com/kchai-2021-01-12_15:40:50-rados-wip-kefu2-testing-2021-01-12-2040-distro-basic-smithi/
- https://pulpito.ceph.com/kchai-2021-01-12_15:33:40-rados-wip-kefu-testing-2021-01-12-2045-distro-basic-smithi/

**Comment by neha-ojha** [comment]
testing it here: https://pulpito.ceph.com/nojha-2021-01-12_23:56:52-rados-wip-48777-2021-01-12-distro-basic-smithi/

**Comment by tchaikov** [comment]
/a/nojha-2021-01-12_23:56:52-rados-wip-48777-2021-01-12-distro-basic-smithi/5781416: https://tracker.ceph.com/issues/48712

**Comment by tchaikov** [comment]
@ronen-fr i don't think the failures are related. could you help review this change?

**Comment by ronen-fr** [comment]
> @ronen-fr i don't think the failures are related. could you help review this change?

Going over logs as we speak...

**Review by ronen-fr — APPROVED** [review]
Clean change. Test failures I checked are unrelated

**Comment by ronen-fr** [comment]
BTW - https://pulpito.ceph.com/nojha-2021-01-12_23:56:52-rados-wip-48777-2021-01-12-distro-basic-smithi/5781231/ leads me to add another "just in case" check in https://github.com/ceph/ceph/pull/38730. Will update that PR shortly.

**Comment by badone** [comment]
Original tracker was accidentally deleted by me so I have recreated it at https://tracker.ceph.com/issues/49072

**Pull request merged**
