### PR TITLE
rgw: Swift API. Allows setting attributes with COPY object operation.

### PR DESCRIPTION
**Pull request by diurchenko**
http://developer.openstack.org/api-ref-objectstorage-v1.html says: "With COPY, you can add additional metadata to the object."

Fixes: #10662
Reported-by: Ahmad Faheem <ahmad.faheem@ril.com>
Signed-off-by: Dmytro Iurchenko <diurchenko@mirantis.com>

### CODE REVIEW

**Comment by diurchenko** [comment]
@yehudasa Should I add "Backport: hammer" to every bugfix related to Swift API?

**Comment by yehudasa** [comment]
@diurchenko yes, hammer is frozen, so everything should go at the moment into master (other than rc related fixes)

**Comment by diurchenko** [comment]
@yehudasa But the original code contradicts the statement *The intra region use case is separate from everything*. No matter if it is an intra region op or not, the original code will overwrite source attrs depending on the operation mode. Does that mean that the original code had a bug?

**Comment by yehudasa** [comment]
@diurchenko here's the original function:

static void set_copy_attrs(map<string, bufferlist>& src_attrs, map<string, bufferlist>& attrs, bool replace_attrs, bool intra_region)
{
  if (replace_attrs) {
    if (!attrs[RGW_ATTR_ETAG].length())
      attrs[RGW_ATTR_ETAG] = src_attrs[RGW_ATTR_ETAG];

    src_attrs = attrs;
  } else {
    /* copying attrs from source, however acls should only be copied if it's intra-region operation */
    if (!intra_region)
      src_attrs[RGW_ATTR_ACL] = attrs[RGW_ATTR_ACL];
  }
}

In the intra_region case it doesn't do anything. intra_region will not be set if replace_attrs is set, which is an implicit anti dependency. I'd rather make stuff more explicit.

**Comment by diurchenko** [comment]
@yehudasa So what do we got here: A function that should not do anything if a specific argument is set to true. I think it is not only me, who can get confused.
There two places where *set_copy_attrs* is invoked:
```
set_copy_attrs(src_attrs, attrs, attrs_mod, !source_zone.empty());
```
and
```
set_copy_attrs(src_attrs, attrs, attrs_mod, false);
```
I think the best would be to get rid of intra_region parameter and enclose the first invocation in a conditional statement.

**Comment by yehudasa** [comment]
@diurchenko looks good, can you send a new pull request against master?

**Comment by diurchenko** [comment]
@yehudasa I've created a pull request against master.

**Pull request closed without merging**
