### PR TITLE
jewel: mon: OSDs marked OUT wrongly after monitor failover

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/17884

### CODE REVIEW

**Comment by dachary** [comment]
@tchaikov does this backport look good to merge ? It passed the rados (http://tracker.ceph.com/issues/17851#note-12) suite. It also passed the upgrade/jewel-x and upgrade/hammer-x (http://tracker.ceph.com/issues/17851#note-15) suites. Note that it won't be included in 10.2.4, reason why it targets jewel-next.

**Comment by smithfarm** [comment]
@tchaikov Ping

**Comment by tchaikov** [comment]
@dachary and @smithfarm sorry for the latency, good to merge!

**Comment by smithfarm** [comment]
This passed another rados run at http://tracker.ceph.com/issues/17851#note-45 with some unrelated failures.

**Pull request merged**
