### PR TITLE
script: make backport scripts know about pacific

### PR DESCRIPTION
**Pull request by smithfarm**

### CODE REVIEW

**Comment by smithfarm** [comment]
This may be slightly premature, since cherry-picking to pacific hasn't started yet AFAICT, but when it does start all that is needed is to merge this PR: I tested it just now and it creates pacific backport issues.

**Comment by smithfarm** [comment]
jenkins test api

**Review by jdurgin — APPROVED** [review]

**Comment by smithfarm** [comment]
@liewegas Has pacific been split already? Or are you still planning to merge master into pacific at some point?

**Review by nizamial09 — COMMENTED** [review]
@smithfarm Just curious, shouldn't there be a similar change made to the ceph-backport.sh file to add the milestone for pacific? 
https://github.com/ceph/ceph/blob/master/src/script/ceph-backport.sh#L1086

**Comment by tchaikov** [comment]
@smithfarm hi Nathan, i double checked with Josh. we do backport a little bit differently this time before releasing a new release officially -- we just backport the fixes once the LTS branch is cut. in other words, we don't merge master back to pacific.

**Comment by smithfarm** [comment]
@nizamial09 @tchaikov OK, I repurposed the PR so it makes the necessary modifications to all three backport scripts.

**Comment by smithfarm** [comment]
@tchaikov @jdurgin Could we get the master tag bumped to `v17.0.0`? It's confusing for pacific and master to have the same version.

**Review by batrick — APPROVED** [review]

**Pull request merged**
