### PR TITLE
msg/async:  reset fd to -1 after closing it

### PR DESCRIPTION
**Pull request by shangfufei**
After listen_socket was closed, it entered  the start() process magically. so I think we should make '_fd = -1' when listen_socket was closed. And  in the start process, determine the value of listen_socket, if it equal to -1, return the process.
Fixes: https://tracker.ceph.com/issues/23600
Signed-off-by: shangfufei <shangfufei@inspur.com>

### CODE REVIEW

**Comment by yuyuyu101** [comment]
when listen_socket abort, the socket will be reset. what happen if server_socket exists and fd==-1?

**Comment by shangfufei** [comment]
this time will run the Processor::stop function,just delete listen socket fd from epoll event.

**Comment by tchaikov** [comment]
- http://pulpito.ceph.com/kchai-2018-04-16_09:06:16-rados-wip-kefu-testing-2018-04-16-1515-distro-basic-smithi/
- http://pulpito.ceph.com/kchai-2018-04-15_23:41:27-rados-wip-kefu-testing-2018-04-15-2317-distro-basic-smithi/

the failed tests are caused by #21338

**Comment by tchaikov** [comment]
@shangfufei again, please *summarize* the change in the title of your commit message. and please remove  "bug fix 23600" from the title.

**Comment by liewegas** [comment]
I'm definitely on board with setting fd to -1 on close; not doing so can lead to all kinds of problems with data written to the wrong socket or file (!!!), and writing to -1 at least will error out instead of causing more damage.

**Comment by tchaikov** [comment]
@shangfufei please note the commit message and title of the PR are different. also please rebase. modulo these nits, lgtm.

**Comment by shangfufei** [comment]
get it, i'm doing now,

**Comment by tchaikov** [comment]
@shangfufei please remove the merge commit from the PR. you might want to rebase onto the master or just cherry-pick your change.

**Comment by liewegas** [comment]
@shangfufei can you rebase this on top of current master so it is a single git commit?

**Comment by shangfufei** [comment]
> @shangfufei can you rebase this on top of current master so it is a single git commit?

Do you mean I need to submit it directly in the master branch?

**Comment by shangfufei** [comment]
This modification is currently in the wip-async-bugfix-23600 branch, which needs to be merged into the master trunk branch if detection is not a problem with conventional operations.

**Comment by smithfarm** [comment]
@shangfufei I think what @liewegas is asking for is to squash the three commits in this PR [1] (using `git rebase -i`) into a single commit so the PR has only one commit instead of three.

[1] https://github.com/ceph/ceph/pull/21296/commits

**Comment by xiexingguo** [comment]
@liewegas Already merged by https://github.com/ceph/ceph/pull/27599

**Pull request closed without merging**
