### PR TITLE
jewel: tests: eliminate race condition in Thrasher constructor

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/19063

### CODE REVIEW

**Comment by tchaikov** [comment]
@dzafman this PR is the cure of http://tracker.ceph.com/issues/19417 .

**Comment by smithfarm** [comment]
@tchaikov Thanks for correlating and cross-linking!

**Comment by dzafman** [comment]
@tchaikov Why not backport b519d38fb1967628ad8a1c46fcfb3f984de58790 which is where the fix got into master?  That sha1 cleanly applies to Kraken which needs the change too.  The Jewel cherry-pick has a trivial conflict to fix.

**Comment by tchaikov** [comment]
@dzafman  this PR is indeed a cherry-pick of b519d38fb1967628ad8a1c46fcfb3f984de58790. and @smithfarm put a very good commit message explaining the conflict resolution. also, please refer to http://tracker.ceph.com/issues/18799 to see the kraken backport.

**Comment by smithfarm** [comment]
This passed a rados run at http://tracker.ceph.com/issues/19538#note-39

**Pull request merged**
