### PR TITLE
mgr/dashboard: Fix issues in user form

### PR DESCRIPTION
**Pull request by votdev**
Link labels with correct form fields.

Signed-off-by: Volker Theile <vtheile@suse.com>
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by tspmelo** [comment]
jenkins retest this please

**Comment by votdev** [comment]
jenkins retest this please

**Comment by votdev** [comment]
jenkins retest this please

**Comment by s0nea** [comment]
jenkins test make check

**Comment by votdev** [comment]
jenkins test dashboard

**Pull request merged**
