### PR TITLE
pacific: mon: Modifying trim logic to change paxos_service_trim_max dynamically

### PR DESCRIPTION
**Pull request by singuliere**
backport tracker: https://tracker.ceph.com/issues/50124

---

backport of https://github.com/ceph/ceph/pull/40168
parent tracker: https://tracker.ceph.com/issues/50004

this backport was staged using ceph-backport.sh version 16.0.0.6848
find the latest version at https://github.com/ceph/ceph/blob/master/src/script/ceph-backport.sh

### CODE REVIEW

**Review by amathuria — APPROVED** [review]

**Comment by dvanders** [comment]
Is this a problem? https://github.com/ceph/ceph/pull/40168#discussion_r610931497
Setting to 0 won't disable the new multiplier -- it would trim by (trim_max+to_remove) / 2

**Comment by singuliere** [comment]
jenkins test this please

**Comment by neha-ojha** [comment]
jenkins test api

**Comment by neha-ojha** [comment]
jenkins test docs

**Pull request merged**
