### PR TITLE
[DNM] jewel: qa/workunits/rbd: improvements for rbd-mirror tests

### PR DESCRIPTION
**Pull request by trociny**
http://tracker.ceph.com/issues/18012

It is expected to reduce amount of false negatives when testing jewel branch.

### CODE REVIEW

**Comment by dachary** [comment]
jenkins test this please (move the base to jewel-next)

**Comment by trociny** [comment]
Just FYI. I was running teuthology with these updated tests, still was observing sporadic test failures (though not related to the fixes in this PR). I was able to trace the failures to yet another problem in rbd_mirror.sh test script (relevant for the master too) and created a PR for this: #12195

With that test fix, teuthology runs look much better:
http://pulpito.ceph.com/trociny-2016-11-28_07:01:37-rbd-wip-mgolub-testing-jewel---basic-vps/
http://pulpito.ceph.com/trociny-2016-11-28_07:01:17-rbd-wip-mgolub-testing-jewel---basic-mira/

**Comment by smithfarm** [comment]
@dachary Is DNM still needed here? The fix referred to by @trociny in the previous comment has already been merged to jewel.

**Comment by smithfarm** [comment]
@trociny Could you merge #12321 into this PR?

**Comment by smithfarm** [comment]
This appears to conflict with multiple other PRs: #12321 and #12425 at least

**Comment by trociny** [comment]
@smithfarm I am not sure I get you right here, so...

I think it was wrong in #12425 that you manually resolved  ">&2" conflict in qa/workunits/rbd/rbd_mirror_helpers.sh. You just had to merge this PR first (or at least cherry-pick the first commit from here).

I can try merge all these 3 PRs in right order, which I expect should resolve conflicts automatically. Do you want me do this in this PR?

**Comment by smithfarm** [comment]
@trociny Thanks for the hint. I merged all three PRs together in #12425 - please take a look.

**Comment by smithfarm** [comment]
I started with this PR as a base, then cherry-picked the commit in #12321, and then the commits in #12425. There were no conflicts.

**Pull request closed without merging**
