### PR TITLE
luminous: qa/workunits/rbd: adapt import_export test to handle multiple units

### PR DESCRIPTION
**Pull request by dillaman**
http://tracker.ceph.com/issues/24740

### CODE REVIEW

**Comment by smithfarm** [comment]
@dillaman Thanks! This is a much more straightforward way to fix the bug than cherry-picking.

**Comment by dillaman** [comment]
@smithfarm This PR should be a good cherry-pick source for the Jewel backport as well.

**Comment by smithfarm** [comment]
@liewegas This is the cherry-pick source for https://github.com/ceph/ceph/pull/22913 which just merged. Shall we merge this one, too?

**Comment by liewegas** [comment]
sure

**Pull request merged**
