### PR TITLE
crimson/osd/pg: make sure ops are sent to backfill targets if and only if the object has been pushed.

### PR DESCRIPTION
**Pull request by xxhdx1985126**
Fixes: https://tracker.ceph.com/issues/68661
Signed-off-by: Xuehan Xu <xuxuehan@qianxin.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Comment by athanatos** [comment]
It's not clear to me that this makes sense.  "pushing" doesn't mean that the object has entirely been recovered -- suppose it needs multiple messages to be fully pushed to the peer?

I think the intended invariant is that everything between last_backfill_started and peer_info.last_backfill is either pushed or still locked for recovery.  At least, it seems to me that we *must* block writes (via the obc lock) while a push is in progress.  Perhaps I'm missing something?

**Comment by xxhdx1985126** [comment]
> I think the intended invariant is that everything between last_backfill_started and peer_info.last_backfill is either pushed or still locked for recovery. At least, it seems to me that we _must_ block writes (via the obc lock) while a push is in progress.

Yes, you're right. And in the current implementation, client writes are already blocked when a push is in progress through obc locks.

The problem is that, there's a gap between checking whether the object needs recovery and locking obcs in the io path, so we need to make sure locking obcs and determining that the object doesn't need to recover happens in the same continuation. However, between those two phases (checking recovery and lock obcs), we also need to check whether there are clones that need recoveries and do multiple pipeline enter/exit all of which may block. So making sure those two phases happen in the same continuation may not be easy.

On the other hand, since the ultimate goal is to make sure that the primary osd sends ops to backfill targets if and only if the object is already backfilled, so, with client writes and object pushes already mutual exclusive, it may not be necessary to make the above two phases happen in the same continuation if we can keep the follow invariants:

1. the primary doesn't send ops to backfill targets if the object is already queued for push and the push hasn't happened yet;
2. the finish of the push and the increase of peer_info.last_backfill happen in the same continuation;

This PR makes sure these two invariants are kept.

Am I right?

**Comment by xxhdx1985126** [comment]
> * the primary doesn't send ops to backfill targets if the object is already queued for push and the push hasn't happened yet;
> * the increase of peer_info.last_backfill happen before the release of the push's obc lock

@athanatos @Matan-B I've just rebased this PR on top of #60185 , since it needs #60185 to keep these two invariants. Please take a look again, thanks.

**Comment by athanatos** [comment]
From the bug, at step "PG 3.1e7 starts to backfill rbd_data.1dca58cb98a9.00000000000062d5:head, however hangs waiting for its lock to be released", I think that the backfill logic should not have advanced last_backfill_started to include rbd_data.1dca58cb98a9.00000000000062d5:head until it actually got the lock.  That should ensure that every object in [last_backfill, last_backfill, last_backfill_started] is either recovered or locked.

**Comment by xxhdx1985126** [comment]
> From the bug, at step "PG 3.1e7 starts to backfill rbd_data.1dca58cb98a9.00000000000062d5:head, however hangs waiting for its lock to be released", I think that the backfill logic should not have advanced last_backfill_started to include rbd_data.1dca58cb98a9.00000000000062d5:head until it actually got the lock. That should ensure that every object in [last_backfill, last_backfill, last_backfill_started] is either recovered or locked.

Yeah, will try this approach.

**Comment by xxhdx1985126** [comment]
> From the bug, at step "PG 3.1e7 starts to backfill rbd_data.1dca58cb98a9.00000000000062d5:head, however hangs waiting for its lock to be released", I think that the backfill logic should not have advanced last_backfill_started to include rbd_data.1dca58cb98a9.00000000000062d5:head until it actually got the lock. That should ensure that every object in [last_backfill, last_backfill, last_backfill_started] is either recovered or locked.

Hi, sam, I'm sorry that I wasn't thinking this issue right. Given that the client writes are already mutual exclusive with object pushes, at the time of determining whether to send ops to backfill targets, the object is either fully backfilled or hasn't started the push at all. So, as long as we can make sure that BackfillState's `ObjectPushed` event is processed by `BackfilState::state_machine` before the obc lock held by the object's backfill is released, we don't have to check whether the object is started to backfill to decide whether to send backfill targets ops.

On the other hand, to increase `last_backfill_started` after the obc lock is acquired, we might have to order the pushes of objects, which may involve major changes the recovery implementation.

So, based on the above analysis, I moved to making sure BackfillState's `ObjectPushed` event is processed by `BackfilState::state_machine` before the obc lock held by the object's backfill is released.

**Comment by Matan-B** [comment]
Please ping once this is ready to review again

**Comment by xxhdx1985126** [comment]
> Given that the client writes are already mutual exclusive with object pushes, at the time of determining whether to send ops to backfill targets, the object is either fully backfilled or hasn't started the push at all.

@athanatos @Matan-B I moved to use `peering_state.get_peer_missing(peer).is_missing(hoid)` to determine whether the object is backfilled, please take a look, thanks:-)

**Comment by ronen-fr** [comment]
@xxhdx1985126 : is this error scenario possible in legacy code? txs

**Comment by athanatos** [comment]
@ronen-fr This is a crimson-specific implementation error.

**Review by athanatos — APPROVED** [review]
Ah, I'd forgotten that we add it to the missing set.  That should work.

**Comment by Matan-B** [comment]
https://shaman.ceph.com/builds/ceph/wip-matanb-crimson-testing-nov-3/

**Comment by Matan-B** [comment]
https://pulpito.ceph.com/matan-2024-11-03_10:45:16-crimson-rados-wip-matanb-crimson-testing-nov-3-distro-crimson-smithi/

7978413, 7978439 - https://tracker.ceph.com/issues/67791
Seastore:
7978417 - https://tracker.ceph.com/issues/67823
7978430 - https://tracker.ceph.com/issues/68809
Infra:
7978415 - Error reimaging machines

**Pull request merged**
