### PR TITLE
DNM: jewel: rgw: for the create_bucket api, if the input creation_time is zero, w…

### PR DESCRIPTION
**Pull request by fnordahl**
…e should set it to 'now"

Fixes: http://tracker.ceph.com/issues/16597

Signed-off-by: weiqiaomiao wei.qiaomiao@zte.com.cn

### CODE REVIEW

**Comment by fnordahl** [comment]
It would be really good to have this landed for Jewel 10.2.4.

I belive the releated fixes in #11335 are incomplete without this patch. What do you think, @mattbenjamin ?

**Comment by fnordahl** [comment]
retest this please

**Comment by dachary** [comment]
@fnordahl it won't be in 10.2.4 I'm afraid. It is now in the scope of 10.2.5. Could you please explain in the commit message why it cannot be fixed with a **git cherry-pick -x** of a commit from master ?

**Comment by fnordahl** [comment]
> @fnordahl it won't be in 10.2.4 I'm afraid. It is now in the scope of 10.2.5. Could you please explain in the commit message why it cannot be fixed with a git cherry-pick -x of a commit from master ?

@dachary Thank you for your feedback. Commit message updated per request. Done.

PS:
I just discovered that a second PR attempting to merge the exact same patch has emerged in #11990. Feel free to pick which one you want to merge.

**Comment by dachary** [comment]
Closing in favor of #11990 because it already is being tested in the integration branch. Thanks for cross referencing that properly @fnordahl !

**Pull request closed without merging**
