### PR TITLE
rbd-mirror: fix races in snapshot-based mirroring deletion propagation

### PR DESCRIPTION
**Pull request by idryomov**
## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [x] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by idryomov** [comment]
make check is blocked on https://github.com/ceph/ceph/pull/44706.

**Review by MrFreezeex — APPROVED** [review]
I am surprised to learn that the disabling state issue was only fixed for journaling as the issue was originally spotted on snapshot with teuthology. Maybe fixing it for journaling just reduced the rate of the race by two and we got lucky...

Small nit in the commit message of https://github.com/ceph/ceph/pull/44714/commits/79caf5443ce7d020a2e52480193392fb7c99e280 there is a 'd' missing at the beginning of the first commit hash otherwise LGTM

**Comment by idryomov** [comment]
> I am surprised to learn that the disabling state issue was only fixed for journaling as the issue was originally spotted on snapshot first with teuthology. Maybe fixing it for journaling just reduced the rate of the race by two and we got lucky...

Not sure, but it's definitely there.  I observed it on the CLI a few times and confirmed with the new unit tests.

> 
> Small nit in the commit message of [79caf54](https://github.com/ceph/ceph/commit/79caf5443ce7d020a2e52480193392fb7c99e280) there is a 'd' missing at the beginning of the first commit hash otherwise LGTM

Fixed.

**Review by trociny — APPROVED** [review]
LGTM

**Comment by idryomov** [comment]
jenkins test api

**Comment by idryomov** [comment]
jenkins test make check

**Comment by idryomov** [comment]
No related failures:

https://pulpito.ceph.com/dis-2022-01-21_20:35:25-rbd-wip-dis-testing-distro-default-smithi/
https://pulpito.ceph.com/dis-2022-01-22_10:52:09-rbd-wip-dis-testing-distro-default-smithi/

**Pull request merged**
