### PR TITLE
FileStore calls syncfs(2) even it is not supported

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/12587

### CODE REVIEW

**Comment by dachary** [comment]
@smithfarm could you please rebase and repush ?

**Comment by smithfarm** [comment]
@dachary done

**Comment by dachary** [comment]
@tchaikov does this backport look good to merge ? It passed a run of the hammer rados suite ( see http://tracker.ceph.com/issues/13356#note-11 and  for details ).

**Comment by tchaikov** [comment]
@dachary lgtm

**Pull request merged**
