### PR TITLE
jewel: mon:when client without write premission ,it also can add blacklist

### PR DESCRIPTION
**Pull request by pyrl247**
Signed-off-by: Guang Yang Developer <pyrl247@gmail.com>

### CODE REVIEW

**Comment by tchaikov** [comment]
@pyrl247 what's the point of moving this definition around?

**Comment by pyrl247** [comment]
@tchaikov in Monitor.cc handle_command,if the command is "osd blacklist add",the prefix should be "osd blacklist",when it traverses all commands ，it stop at "osd blacklist ls" command,so it get the wrong premisson.

**Comment by tchaikov** [comment]
@pyrl247 i guess what you mean is `OSDMonitor::handle_command()`.  do you have a reproducer? i don't really follow you. sounds like we have a bug while parsing/building a correct `cmd` json string in MMonCommand ? but i am not sure how to trigger this issue.

**Comment by pyrl247** [comment]
@tchaikov yes,i have.You can use ceph-jewel and add a user with caps 'mon "allow r" osd "allow *"',than you exec following command (with the user!!!!!): rbd lock add ***& rbd lock rm****** ,it will return success,but we expect Permission denied in rbd lock rm,because it do not have the write premission.In luminous it turns the result we expect.

**Comment by jecluis** [comment]
@pyrl247 but... how is this patch addressing the issue when all it does is moving the definition of the command a few hundred lines up in the file? This does not seem like it would affect the permission validation, and certainly doesn't seem like it should fix the behavior you are describing.

**Comment by pyrl247** [comment]
@jecluis the moncommands are push in a vector in order of MonCommands.h.In jewel ,cmd "osd blacklist add" has the prefix "osd blacklist",when it needs to get the cmd premission,it  gets the premission of "osd blacklist ls" 's premission;but cmd "osd blacklist ls" has the prefix "osd blacklist ls",so it won't stop when it comes to "osd blacklist",exchange the order of commands could fix this.In function Monitor::_get_moncommand,the cmdstring.compare only compares the sizeof prefix.

**Comment by jecluis** [comment]
Yeah, if that is the case, then this is the wrong fix. The patch should address the root cause instead, and that means fixing the string matching algorithm that decides which command is being called upon.

**Comment by pyrl247** [comment]
@jecluis I agree with u.I'm afraid of effect other commands,so I came out this easy way to fix this.Sorry not helping.

**Pull request closed without merging**
