### PR TITLE
kv/MemDB: making memdb code adapt to generic maps

### PR DESCRIPTION
**Pull request by chhabaramesh**
Changing code to use generic map for MemDB implementation.

Signed-off-by: Ramesh Chander <Ramesh.Chander@sandisk.com>

### CODE REVIEW

**Comment by chhabaramesh** [comment]
@liewegas , please review and merge this, code changes are to make types generic to try different maps

**Comment by yuyuyu101** [comment]
why change to std::map, performance reason?

**Comment by chhabaramesh** [comment]
@yuyuyu101 , yes, seems btree map is not scaling much and is compute intensive.  Std::map also does not help much with just this change. But change is more of making it use any map by single line change.

**Comment by liewegas** [comment]
This also lets us avoid the annoying iterator invalidation logic.  Can you add a flag for that too?

**Comment by chhabaramesh** [comment]
@liewegas , will do it today, apologies for the delay in responding.

**Comment by chhabaramesh** [comment]
@liewegas , Iterartor invalidation works this way now:

. If seq does not change, it is valid
. if using btree and seq no has changed, restart iter.
. If not using btree and seq no has changed, but current key still exists, iter is valid.
. If not using btree and seq not has changed and current key does not exists, restart the iter.

I am still keeping seqno logic for all maps since it should be faster then checking "if key exists" every time.

**Comment by liewegas** [comment]
Looks good, thanks!

**Pull request merged**
