### PR TITLE
Wip osx port

### PR DESCRIPTION
**Pull request by ukernel**

### CODE REVIEW

**Comment by ukernel** [comment]
make ceph-fuse work on OSX

**Comment by yuyuyu101** [comment]
Does fuse need to link messenger?

**Comment by ukernel** [comment]
On Tue, Jul 7, 2015 at 4:21 PM, Haomai Wang <notifications@github.com>
wrote:

> Does fuse need to link messenger?
>
yes, of course

**Comment by yuyuyu101** [comment]
Previously I also setup a osx compatible patch, could you give a look at this(https://github.com/yuyuyu101/ceph/commit/08503796bf2003d6ef4c7665da2e5898ebf91ee1)?

**Comment by ukernel** [comment]
This is based on Dennis Schafroth's https://github.com/ceph/ceph/compare/port/new branch. I think that branch includes most of your changes

**Comment by yuyuyu101** [comment]
Cool, is this branch could be made to merge? It would be for macer :-)

**Comment by tchaikov** [comment]
yup, i'd love to see them in master!

**Comment by tchaikov** [comment]
LGTM other than some minor comment. @noahdesu was also trying to port ceph to improve the portability [0], and did substantial work in this area . but seems the wip-port branch was removed somehow.

---
[0] https://wiki.ceph.com/Planning/Blueprints/Emperor/Increasing_Ceph_portability

**Comment by ukernel** [comment]
On Wed, Jul 8, 2015 at 2:17 PM, Kefu Chai <notifications@github.com> wrote:

> LGTM other than some minor comment. @noahdesu
> <https://github.com/noahdesu> was also trying to port ceph to improve the
> portability [0], and did substantial work in this area . but seems the
> wip-port branch was removed somehow.
>

I thinks his branch is at https://github.com/ceph/ceph/commits/port/old.
But he didn't update that branch for about a year



------------------------------

**Comment by ukernel** [comment]
I'm not familiar with authconfig. how to write code to locate header files in configure.ac? In my case, osxfuse headers are in /opt/local/include/osxfuse/

**Comment by tchaikov** [comment]
>  how to write code to locate header files in configure.ac?

i will try to pull together a patch on top of yours tomorrow. seems it installs a pc file somewhere:

```
$ pkg-config --cflags fuse
-D_FILE_OFFSET_BITS=64 -D_DARWIN_USE_64_BIT_INODE -I/usr/local/include/osxfuse/fuse
$ pkg-config --cflags fuse
-D_FILE_OFFSET_BITS=64 -D_DARWIN_USE_64_BIT_INODE -I/usr/local/include/osxfuse/fuse
```

@ukernel what the corresponding output on your mac?

**Comment by ukernel** [comment]
pkg-config --cflags osxfuse
-D_FILE_OFFSET_BITS=64 -D_DARWIN_USE_64_BIT_INODE -I/opt/local/include/osxfuse/fuse 
zhyan-laptop:ceph zhyan$ pkg-config --cflags fuse
-D_FILE_OFFSET_BITS=64 -D_DARWIN_USE_64_BIT_INODE -I/opt/local/include/osxfuse/fuse

**Comment by tchaikov** [comment]
done.

**Comment by ukernel** [comment]
@tchaikov It seems your change does not work on linux

**Comment by tchaikov** [comment]
@ukernel fixed. i should use only "fuse" instead of "fuse osxfuse" when
PKG_CHECK_MODULES.

**Comment by ukernel** [comment]
it works. thank you

**Comment by gregsfortytwo** [comment]
So does this only make ceph-fuse build on OS X, or do the other components work now as well?

**Comment by gregsfortytwo** [comment]
@dmick can you look at the sockaddr_storage commit (presently 5ec54cebb65d225a220100348b5267cd57f00465)? I believe you were reviewing some similar compatibility things.

**Comment by ukernel** [comment]
On Fri, Jul 10, 2015 at 7:09 PM, Gregory Farnum <notifications@github.com>
wrote:

> So does this only make ceph-fuse build on OS X, or do the other components
> work now as well?
>
>
this branch is based on port/new branch. this branch make ceph-fuse build
and be able to mount cephfs on OSX

**Comment by noahdesu** [comment]
I pushed up port/new from Dennis Schafroth's work a few days ago that he sent me. I had build errors on my Mac, but wasn't getting a response from Dennis. @gregsfortytwo the patches looked similar in nature to port/old which had RADOS working in some form at the very least, but no extensive testing. @ukernel  I think it'd be a good idea to merge these patches into port/new and starting testing there.

**Comment by noahdesu** [comment]
Compiles for me using Homebrew and `./configure --without-tcmalloc --without-libaio --without-libxfs`

**Comment by tchaikov** [comment]
looks good to me.

**Pull request merged**
