### PR TITLE
cephfs-shell: Fix multiple flake8 errors

### PR DESCRIPTION
**Pull request by varshar16**
This patch set fixes the following flake8 errors and warnings:
* E722 do not use bare 'except'
* E303 too many blank lines
* W605 invalid escape sequence '\/'
* F841 local variable 'flag' is assigned to but never used
* E201 whitespace after '('

Fixes: https://tracker.ceph.com/issues/39717

### CODE REVIEW

**Comment by batrick** [comment]
@varshar16 it's awesome doing this kind of cleanup but shouldn't we also automate running flake8 on cephfs-shell?

@alfredodeza I see you did commits to this file which mentions flake8 [1] but I don't see where/how we run flake8 on our python code. Can you point us in the right direction?

[1] https://github.com/ceph/ceph-qa-suite/commits/master/tox.ini?author=alfredodeza

**Comment by alfredodeza** [comment]
There isn't a universal flake8 run on the Ceph repo. The ceph-volume project does it only for its code, and you can see where in src/ceph-volume/tox.ini 

Once defined in tox.ini run `tox -e flake8` and tox will make sure that the right version of tox (along with the project) is used. I can assist if that is the way you want to go.

**Comment by batrick** [comment]
retest this please

**Comment by varshar16** [comment]
@batrick 
I have submitted the patch for it. Please review it. [#28239]
@alfredodeza 
Is there a way to clean up .tox and .egg-info files ?

**Pull request merged**
