### PR TITLE
doc/cephadm: Restructure orchestrator docs

### PR DESCRIPTION
**Pull request by sebastian-philipp**
This PR mainly moves chapters around. 

* move all host sections to a single host chapter
* move all {service-type} chapters to a dedicated {service-type}.rst

# TODOs:

- [x] No idea how to handle the install guide without duplicating things to much. 
- [ ] mgr/rook ?
- [x] iscsi
- [x] nfs
- [x] cephfs
- [ ] deal with miscellaneous  services (rbd-mirror, crash)

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by sebastian-philipp** [comment]
jenkins render docs

**Review by jmolmo — APPROVED** [review]
Good Work!! 
I think that now  is more easy to understand and over all more easy for the final user to get information about specific issues/topic. 

**Related with the "todo":**

_No idea how to handle the install guide without duplicating things to much._

What do you8 mean by "install guide"...
i think it is covered in the "DEPLOYING A NEW CEPH CLUSTER" section

 _mgr/rook ?_
I think that it is just another point at the same level as "cephadm" in the docs. I do not mind to repeat the cephadm structure inside the rook point.

 _iscsi
 nfs
 cephfs
 deal with miscellaneous services (rbd-mirror, crash)_
We have the entry point or a very clear idea about where to insert the new doc. item.
And yes!! we need to make a more clear explanation of the use of this services. But it is something that can be done in next prs!.

Happy with this change Sebastian!!

**Comment by sebastian-philipp** [comment]
@zdover23 could you give this a review? I'd like to unblock other doc changes

**Comment by sebastian-philipp** [comment]
```
checking consistency... /home/jenkins-build/build/workspace/ceph-pr-docs/doc/cephadm/mds.rst: WARNING: document isn't included in any toctree

/home/jenkins-build/build/workspace/ceph-pr-docs/doc/cephadm/install.rst:241: WARNING: undefined label: cephadm-cephfs (if the link has no caption the label must precede a section header)

**Comment by zdover23** [comment]
jenkins render docs

**Review by zdover23 — APPROVED** [review]
LGTM. 

Fire when ready.

**Pull request merged**
