### PR TITLE
pacific: qa/config/rados: add dispatch delay testing params

### PR DESCRIPTION
**Pull request by ideepika**
these parameters have proven to catch some of the uncaught bugs such as:
https://tracker.ceph.com/issues/48417, adopting them will help in
preventing more such hard to debug bugs.

Signed-off-by: Deepika Upadhyay <dupadhya@redhat.com>
(cherry picked from commit b2c2a4326c89b45a61b129c09ac7838c27188a0a)

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by ideepika** [comment]
testing configs for: https://github.com/ceph/ceph/pull/40572

**Review by neha-ojha — APPROVED** [review]

**Comment by smithfarm** [comment]
Looks like it needs a rebase

**Comment by neha-ojha** [comment]
@ideepika can you please verify https://trello.com/c/PazMYJ8X/1235-wip-yuri2-testing-2021-05-11-1032-pacific#comment-609c5ab1fc7334131954f7da?

**Comment by ideepika** [comment]
> @ideepika can you please verify https://trello.com/c/PazMYJ8X/1235-wip-yuri2-testing-2021-05-11-1032-pacific#comment-609c5ab1fc7334131954f7da?

@neha-ojha could not access osd logs since the runs timedout. On rerun, the dead jobs seems to be passing:
tracked known issue: https://tracker.ceph.com/issues/50042
http://pulpito.front.sepia.ceph.com/?branch=wip-yuri2-testing-2021-05-11-1032-pacific
will reverify

**Comment by ideepika** [comment]
> > @ideepika can you please verify https://trello.com/c/PazMYJ8X/1235-wip-yuri2-testing-2021-05-11-1032-pacific#comment-609c5ab1fc7334131954f7da?
> 
> @neha-ojha could not access osd logs since the runs timedout. On rerun, the dead jobs seems to be passing:
> tracked known issue: https://tracker.ceph.com/issues/50042
> http://pulpito.front.sepia.ceph.com/?branch=wip-yuri2-testing-2021-05-11-1032-pacific
> will reverify

am able to reproduce a running task which is degraded: http://qa-proxy.ceph.com/teuthology/ideepika-2021-05-17_10:16:28-rados-wip-yuri2-testing-2021-05-11-1032-pacific-distro-basic-smithi/6118165/teuthology.log 
investing...

**Comment by ideepika** [comment]
> > > @ideepika can you please verify https://trello.com/c/PazMYJ8X/1235-wip-yuri2-testing-2021-05-11-1032-pacific#comment-609c5ab1fc7334131954f7da?
> > 
> > 
> > @neha-ojha could not access osd logs since the runs timedout. On rerun, the dead jobs seems to be passing:
> > tracked known issue: https://tracker.ceph.com/issues/50042
> > http://pulpito.front.sepia.ceph.com/?branch=wip-yuri2-testing-2021-05-11-1032-pacific
> > will reverify
> 
> am able to reproduce a running task which is degraded: http://qa-proxy.ceph.com/teuthology/ideepika-2021-05-17_10:16:28-rados-wip-yuri2-testing-2021-05-11-1032-pacific-distro-basic-smithi/6118165/teuthology.log
> investing...

dead job caused by: https://tracker.ceph.com/issues/50842 not related to this change

**Pull request merged**
