### PR TITLE
qa: various fixes for fs:verify

### PR DESCRIPTION
**Pull request by batrick**
## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Review by rishabh-d-dave — APPROVED** [review]

**Comment by batrick** [comment]
We still see this:

````
5917494/teuthology.log:2021-02-27T04:27:32.469 INFO:tasks.ceph.mds.b.smithi159.stderr:==00:00:51:00.831 40907== EXEC FAILED: I can't recover from execve() failing, so I'm dying.
5917494/teuthology.log:2021-02-27T04:27:51.026 INFO:tasks.ceph.mds.f.smithi159.stderr:==00:00:51:19.383 40908== EXEC FAILED: I can't recover from execve() failing, so I'm dying.
5917580/teuthology.log:2021-02-27T05:52:37.813 INFO:tasks.ceph.mds.d.smithi073.stderr:==00:01:03:20.556 41218== EXEC FAILED: I can't recover from execve() failing, so I'm dying.
5917663/teuthology.log:2021-02-27T07:41:15.013 INFO:tasks.ceph.mds.b.smithi141.stderr:==00:01:49:02.385 40740== EXEC FAILED: I can't recover from execve() failing, so I'm dying.
5917663/teuthology.log:2021-02-27T07:41:15.014 INFO:tasks.ceph.mds.c.smithi076.stderr:==00:01:49:02.280 35639== EXEC FAILED: I can't recover from execve() failing, so I'm dying.
5917663/teuthology.log:2021-02-27T07:41:15.027 INFO:tasks.ceph.mds.d.smithi141.stderr:==00:01:49:02.376 40742== EXEC FAILED: I can't recover from execve() failing, so I'm dying.
5917663/teuthology.log:2021-02-27T07:41:15.180 INFO:tasks.ceph.mds.a.smithi076.stderr:==00:01:49:02.461 35638== EXEC FAILED: I can't recover from execve() failing, so I'm dying.
5917663/teuthology.log:2021-02-27T07:41:15.193 INFO:tasks.ceph.mds.e.smithi076.stderr:==00:01:49:02.446 35640== EXEC FAILED: I can't recover from execve() failing, so I'm dying.
````

From: https://pulpito.ceph.com/pdonnell-2021-02-26_23:40:39-fs-wip-pdonnell-testing-20210226.181017-distro-basic-smithi/

Even get this when deleting an fs. Need to rethink the approach to this.

**Comment by batrick** [comment]
TODO: raise slow op threshold:

````
2021-02-27T05:54:27.644 INFO:teuthology.orchestra.run.smithi002.stdout:2021-02-27T05:20:24.513041+0000 mds.d (mds.0) 1 : cluster [WRN] 1 slow requests, 1 included below; oldest blocked for > 183.680676 secs
````

**Comment by batrick** [comment]
https://pulpito.ceph.com/pdonnell-2021-03-03_02:45:23-fs:verify-wip-pdonnell-testing-20210301.234318-distro-basic-smithi/

This is ready for review.

@tchaikov / @neha-ojha PTAL as I'm touching some qa bits that could affect core.

**Comment by batrick** [comment]
Also @neha-ojha, it's now possible to run valgrind on ubuntu. I noticed rados has the same restriction: https://github.com/ceph/ceph/blob/master/qa/suites/rados/verify/validater/valgrind.yaml#L2

**Comment by batrick** [comment]
(fixing tox failures)

**Comment by neha-ojha** [comment]
> Also @neha-ojha, it's now possible to run valgrind on ubuntu. I noticed rados has the same restriction: https://github.com/ceph/ceph/blob/master/qa/suites/rados/verify/validater/valgrind.yaml#L2

yeah, we can get rid of that now and include other distros in 
 https://github.com/ceph/ceph/blob/master/qa/suites/rados/verify

**Comment by batrick** [comment]
https://pulpito.ceph.com/pdonnell-2021-03-03_22:38:41-fs:verify-wip-pdonnell-testing-20210303.195715-distro-basic-smithi/

**Comment by batrick** [comment]
https://pulpito.ceph.com/?branch=wip-pdonnell-testing-20210303.195715

Failures are:
- https://tracker.ceph.com/issues/49607
- https://tracker.ceph.com/issues/48773
- https://tracker.ceph.com/issues/48805
- https://tracker.ceph.com/issues/49466
- https://tracker.ceph.com/issues/49605
- https://tracker.ceph.com/issues/49511
- https://tracker.ceph.com/issues/45434
- https://tracker.ceph.com/issues/44631

**Pull request merged**
