### PR TITLE
qa: automate distro/kernel matrix for kclient

### PR DESCRIPTION
**Pull request by batrick**
It's no longer necessary to pass `-k testing` to teuthology-suite. We're also
now regularly testing RHEL 7.5 kernel in upstream testing.

This work is prep for eventually integrating kclient into fs.

Fixes: http://tracker.ceph.com/issues/26995

Signed-off-by: Patrick Donnelly <pdonnell@redhat.com>

### CODE REVIEW

**Comment by batrick** [comment]
This is not quite perfect, the `kcephfs/mixed-clients` suite is mounting the kclient before executing the mixed clients. This should be fixed, possibly by unmounting the kernel mounts (done via `mixed-clients/kclient`) first.

**Comment by batrick** [comment]
http://pulpito.ceph.com/pdonnell-2018-08-21_17:57:32-kcephfs-master-distro-basic-smithi/

**Comment by batrick** [comment]
As feared, the mixed-clients issue noted about caused problems:

http://pulpito.ceph.com/pdonnell-2018-08-21_17:57:32-kcephfs-master-distro-basic-smithi/2932552/

**Comment by batrick** [comment]
http://pulpito.ceph.com/?branch=wip-pdonnell-testing-20180904.143045

**Comment by batrick** [comment]
`Tested-by: Patrick Donnelly <pdonnell@redhat.com>`

**Comment by batrick** [comment]
`Reviewed-by: Patrick Donnelly <pdonnell@redhat.com>`

**Comment by vasukulkarni** [comment]
Good to see separate between testing and distro kernel!

**Pull request merged**
