### PR TITLE
build: Use .S suffix for ppc64le assembly files

### PR DESCRIPTION
**Pull request by kestrels**
The assembly file name suffix was changed from .S to .s,
which caused a build break on ppc64le architecture.

To fix this issue, the suffix will be changed back to .S
for ppc64le assembly files only.  The x86 assembly files
can retain the .s suffix.

Fixes: http://tracker.ceph.com/issues/20106
Signed-off-by: Andrew Solomon <asolomon@us.ibm.com>

### CODE REVIEW

**Comment by kestrels** [comment]
@tchaikov 
@branch-predictor 
@smatzek

Different way of fixing the ppc64le build break, which #15358 is also attempting to fix.  
This issue is blocking my progress on #15100.

**Comment by kestrels** [comment]
@smithfarm 
@bassam 

Please let me know what you think.

**Comment by bassam** [comment]
@kestrels the revert looks OK to me to unblock you, however it might still cause issues with ccache v3.3.3 as described in #15142.

**Comment by tchaikov** [comment]
i am good with this change. @bassam as this change only affects s390 build, so i guess ccache will still work fine with your change in #15142?

**Comment by bassam** [comment]
@tchaikov yes that's correct. we can revisit if someone complains about ccache on s390.

**Pull request merged**
