### PR TITLE
mimic: Fix ceph-mgr restarts

### PR DESCRIPTION
**Pull request by b-ranto**
This PR contains a mimic back-port for shutdown/restart fix for prometheus module and a patch to fix the shutdown/restart with dashboard module enabled in the similar way.

### CODE REVIEW

**Comment by rjfd** [comment]
@s0nea could you run the dashboard QA tests with this PR? (notice this is targeting mimic)

**Comment by s0nea** [comment]
@rjfd yes, I'm going to try it (I'm not really sure if this will be successful because of the issues I'm currently facing in Teuthology).

**Comment by s0nea** [comment]
The QA test run was successful: http://pulpito.ceph.com/tdehler-2018-05-17_12:16:04-rados:mgr-wip-tdehler-testing-distro-basic-mira/

**Comment by b-ranto** [comment]
That is great. @rjfd ok to merge?

**Comment by jcsp** [comment]
Possibly related: http://tracker.ceph.com/issues/24166

**Comment by tchaikov** [comment]
already tested. so no need to run rados qa suite again.

**Pull request merged**
