### PR TITLE
rgw: fix core dump if lifecycle request rule has no ID

### PR DESCRIPTION
**Pull request by yaozongyou**
Signed-off-by: Yao Zongyou <yaozongyou@vip.qq.com>

### CODE REVIEW

**Comment by ZVampirEM77** [comment]
@yaozongyou Thank you~ But I have fix this issue in https://github.com/ceph/ceph/pull/18534

**Comment by yaozongyou** [comment]
okay~~

**Comment by ZVampirEM77** [comment]
@yaozongyou Sorry, it is my fault for not updating the tracker issue timely. Thank you~

**Comment by yaozongyou** [comment]
@ZVampirEM77 It's okay, never mind~~

**Pull request closed without merging**
