### PR TITLE
rgw: Keystone PKI token expiration is not enforced #11367

### PR DESCRIPTION
**Pull request by aakso**
http://tracker.ceph.com/issues/11367

### CODE REVIEW

**Comment by dachary** [comment]
@aakso could you please update http://tracker.ceph.com/issues/11367 with a link to this backport as suggested at http://tracker.ceph.com/projects/ceph-releases/wiki/HOWTO_backport_commits ? 
<pre>
Add a link to the pull request in the issue formatted as follows :
* $release backport http://github.com/ceph/ceph/pull/XXX*
</pre>

**Comment by gregsfortytwo** [comment]
Uh, shouldn't this patch go to master and get backported from there?

**Comment by gregsfortytwo** [comment]
@yehudasa ^

**Comment by aakso** [comment]
@gregsfortytwo Should I recreate this pull request and create patch for master branch?

**Comment by yehudasa** [comment]
@aakso yes

**Comment by dachary** [comment]
closing according to comments

**Comment by dachary** [comment]
@aakso would you have time to re-create this pull request against the master branch please ?

**Comment by aakso** [comment]
new pull request: https://github.com/ceph/ceph/pull/4617

**Pull request closed without merging**
