### PR TITLE
jewel: mds: damage reporting by ino number is useless

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/19679
http://tracker.ceph.com/issues/20294

### CODE REVIEW

**Comment by smithfarm** [comment]
@jcsp Getting "cluster [WRN] Scrub error on inode" (warning in mds log) in the latest jewel integration runs. [1] Do you think it could be caused by this PR? 

[1] http://tracker.ceph.com/issues/19538#note-45

**Comment by jcsp** [comment]
@smithfarm yes, looks like there was a followup commit that fixed the tests to whitelist the log messages:
```
commit 795094628b65eb9c3f5d51c6c895fe1443c5f4cf
Author: John Spray <john.spray@redhat.com>
Date:   Thu Sep 29 17:14:54 2016 +0100

    suites: update log whitelist for scrub msg
    
    Fixes: http://tracker.ceph.com/issues/16016
    Signed-off-by: John Spray <john.spray@redhat.com>
```

**Comment by jcsp** [comment]
@smithfarm could you update this PR to cherry pick in that log whitelist update?

**Comment by smithfarm** [comment]
@jcsp Done!

**Comment by smithfarm** [comment]
@jcsp Should I cherry-pick in the other commits related to http://tracker.ceph.com/issues/16016 as well? I.e. the three from https://github.com/ceph/ceph/pull/11136 ?

**Comment by jcsp** [comment]
The other ones from #11136 are probably a bit too invasive for a backport -- if the log whitelists are in sync with the code now then we're good to go.

**Comment by jcsp** [comment]
Sorry, I'm contradicting myself -- it was me that set the backport field on the other ticket to begin with!

So yes, let's go ahead and bring that change in too.

**Comment by smithfarm** [comment]
@jcsp I don't care one way or the other, but did notice that the backport field had been set.

**Comment by smithfarm** [comment]
Backport needs to be re-done (The 16016 commits need to go in first). Marking DNM and putting it on my todo list.

**Comment by smithfarm** [comment]
@batrick @ukernel @jcsp This passed an fs suite at http://tracker.ceph.com/issues/20613#note-7 with two occurrences of the following transient failure: http://tracker.ceph.com/issues/16881

I see @batrick has already approved, but I'll leave it to you guys to merge after considering the implications of http://tracker.ceph.com/issues/16881 - thanks!

**Pull request merged**
