### PR TITLE
osd: Remove unused osdmap flags full, nearfull from output

### PR DESCRIPTION
**Pull request by dzafman**
Signed-off-by: David Zafman <dzafman@redhat.com>

## Checklist
- [x] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`

</details>

### CODE REVIEW

**Comment by tchaikov** [comment]
- http://pulpito.ceph.com/kchai-2019-09-25_01:32:27-rados-wip-kefu-testing-2019-09-24-1556-distro-basic-mira/
- http://pulpito.ceph.com/kchai-2019-09-27_03:53:11-rados-wip-kefu-testing-2019-09-24-1556-distro-basic-smithi/

**Comment by tchaikov** [comment]
@dzafman why are these flags not used?

**Comment by xiexingguo** [comment]
@tchaikov The cluster-wide full flags are removed back into https://github.com/ceph/ceph/pull/17371. I think it is the correct time for us to drop this safely, so my +1 vote for this as long as tests are happy.

**Comment by tchaikov** [comment]
thanks @xiexingguo , @xiexingguo  and @dzafman , i think we can go further, see #30614

**Pull request merged**
