### PR TITLE
libcephfs: extend support for changing file access/modification time

### PR DESCRIPTION
**Pull request by vshankar**

### CODE REVIEW

**Comment by ukernel** [comment]
For the 'timeval' version functions, please just convert timeval to timespce and call the timespec counterparts.

**Comment by vshankar** [comment]
> For the 'timeval' version functions, please just convert timeval to timespce and call the timespec counterparts.

Only `futimens()` has been added w/ this PR.

**Comment by ukernel** [comment]
I mean 
int Client::futimes(int fd, struct timeval times[2], const UserPerm& perms)
{
struct timespec _times[2];

// convert times to _times

return futimens(fd,  _times, perms)
}

**Comment by ukernel** [comment]
Another option is only add timespec variant.  We don't have backword  compat burden, no need to add timeval variant and timespec variant at the same time

**Comment by vshankar** [comment]
> Another option is only add timespec variant. We don't have backword compat burden, no need to add timeval variant and timespec variant at the same time

I added the `timeval` variants for completeness.

**Comment by vshankar** [comment]
> I mean
> int Client::futimes(int fd, struct timeval times[2], const UserPerm& perms)
> {
> struct timespec _times[2];
> 
> // convert times to _times
> 
> return futimens(fd, _times, perms)
> }

fair enough -- I think we should keep the `timeval` variants.

**Comment by vshankar** [comment]
@ukernel @batrick fixed and updated.

For timeval to timespec conversion, there's `TIMEVAL_TO_TIMESPEC()` in `<sys/time.h>`, but I'm not sure how portable the call would be, so, that's not used here.

**Comment by vshankar** [comment]
> please also add utimens/lutimens

I though the preferred way for path based call for timespec variant is `utimensat()`. Is there `[l]utimens()` call?

**Comment by vshankar** [comment]
retest this please

**Comment by vshankar** [comment]
@ukernel @batrick ping?

**Comment by jtlayton** [comment]
Blech, what's the use-case for all of these extra API calls? We have a ceph_fsetattrx() -- is there something that this provides that that existing call doesn't?

**Pull request merged**
