### PR TITLE
ceph-volume: add Ceph's device id to inventory

### PR DESCRIPTION
**Pull request by sebastian-philipp**
This will benefit the orchestrator and dashboard to show a unified view of devices with SMART data

Signed-off-by: Sebastian Wagner <sebastian.wagner@suse.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`

</details>

### CODE REVIEW

**Comment by sebastian-philipp** [comment]
> Please add this field to `report_fields` so that it also shows up on the detailed per-device inventory.

better?

**Comment by jan--f** [comment]
> > Please add this field to `report_fields` so that it also shows up on the detailed per-device inventory.
> 
> better?

Yes. I assume this should be backported? Please either add a tracker ticket to the commit so we can properly track the backport or provide the backport PRs yourself.

**Comment by sebastian-philipp** [comment]
> Yes. I assume this should be backported?

I don't need this changeset in pre-octopus. But we could backport this in order to keep ceph-volume to behave the same in all active branches.

> Please either add a tracker ticket to the commit so we can properly track the backport or provide the backport PRs yourself.

I can create the backports myself.

**Comment by sebastian-philipp** [comment]
jenkins test ceph-volume all

**Comment by jan--f** [comment]
jenkins test ceph-volume tox

**Comment by jan--f** [comment]
There is on unit test that needs updating. See https://github.com/ceph/ceph/blob/master/src/ceph-volume/ceph_volume/tests/test_inventory.py#L64

**Comment by sebastian-philipp** [comment]
> There is on unit test that needs updating. See https://github.com/ceph/ceph/blob/master/src/ceph-volume/ceph_volume/tests/test_inventory.py#L64

Thanks! tox passes locally now:

```
  py27: commands succeeded
SKIPPED:  py35: InterpreterNotFound: python3.5
  py36: commands succeeded
  flake8: commands succeeded
  congratulations :)
```

**Comment by sebastian-philipp** [comment]
cc @jmolmo

**Pull request merged**
