### PR TITLE
pacific: ceph-fuse: add dedicated snap stag map for each directory

### PR DESCRIPTION
**Pull request by lxbsz**
backport tracker: https://tracker.ceph.com/issues/56056

---

backport of https://github.com/ceph/ceph/pull/45614
parent tracker: https://tracker.ceph.com/issues/54653

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by luis-henrix** [comment]
(copying comment from the original PR, see also tracker comment)

@lxbsz This is breaking my build with `FUSE_VERSION > FUSE_MAKE_VERSION(3, 0)`:
```
/home/miguel/dev/ceph/ceph/src/client/fuse_ll.cc: In constructor ‘CephFuse::Handle::Handle(Client*, int)’:
/home/miguel/dev/ceph/ceph/src/client/fuse_ll.cc:1379:1: error: expected identifier before ‘{’ token
 1379 | {
      | ^
```

**Comment by lxbsz** [comment]
> (copying comment from the original PR, see also tracker comment)
> 
> @lxbsz This is breaking my build with `FUSE_VERSION > FUSE_MAKE_VERSION(3, 0)`:
> 
> ```
> /home/miguel/dev/ceph/ceph/src/client/fuse_ll.cc: In constructor ‘CephFuse::Handle::Handle(Client*, int)’:
> /home/miguel/dev/ceph/ceph/src/client/fuse_ll.cc:1379:1: error: expected identifier before ‘{’ token
>  1379 | {
>       | ^
> ```

It should be caused by:
https://github.com/ceph/ceph/pull/46949/files#diff-27ee28966b05e5763e76677ae87f8626985eae114814c25bdc45eef15c3455f0L1162, and I will fix it.

**Comment by lxbsz** [comment]
> (copying comment from the original PR, see also tracker comment)
> 
> @lxbsz This is breaking my build with `FUSE_VERSION > FUSE_MAKE_VERSION(3, 0)`:
> 
> ```
> /home/miguel/dev/ceph/ceph/src/client/fuse_ll.cc: In constructor ‘CephFuse::Handle::Handle(Client*, int)’:
> /home/miguel/dev/ceph/ceph/src/client/fuse_ll.cc:1379:1: error: expected identifier before ‘{’ token
>  1379 | {
>       | ^
> ```

Fixed in https://github.com/ceph/ceph/pull/47026.

**Comment by vshankar** [comment]
jenkins test api

**Review by kotreshhr — APPROVED** [review]

**Comment by lxbsz** [comment]
Backported https://github.com/ceph/ceph/pull/47026.

**Comment by yuriw** [comment]
jenkins test this please

**Comment by yuriw** [comment]
@lxbsz this is ready for merge but filing make check

**Comment by lxbsz** [comment]
Rebased it.

**Comment by lxbsz** [comment]
Rebased it.

**Comment by yuriw** [comment]
jenkins test this please

**Comment by tchaikov** [comment]
jenkins test make check

**Comment by tchaikov** [comment]
jenkins test api

**Pull request merged**
