### PR TITLE
librbd: tweaks to increase IOPS and reduce CPU usage

### PR DESCRIPTION
**Pull request by dillaman**
**random reads @ 4K**
57.2k (librbd) @ 308% CPU (185 IOPS/%CPU)
70.3k IOPS (librbd+tweaks) @ 352 % CPU (200 IOPS/%CPU)
97.8k IOPS (krbd)

**random writes @ 4K**
48.9K IOPS (librbd) @ 318% CPU (153 IOPS/%CPU)
57.4k IOPS (librbd+tweaks) @ 343% CPU (167 IOPS/%CPU)
85.2k IOPS (krbd)

### CODE REVIEW

**Comment by dillaman** [comment]
(adding cephfs tag just to ensure its tests are run since it also uses Striper)

**Comment by trociny** [comment]
@dillaman It needs rebase after #27999 is merged

**Comment by dillaman** [comment]
@trociny rebase pushed

**Comment by dillaman** [comment]
http://pulpito.ceph.com/jdillaman-2019-05-15_12:42:41-fs-wip-jd-testing-distro-basic-smithi/

**Comment by batrick** [comment]
@dillaman I'll run this through the cephfs suites in a day or two.

**Comment by dillaman** [comment]
@batrick Thx, note that I have a 'fs' suite running right now (see link above)

**Comment by batrick** [comment]
@dillaman that's even better. Ping me by email when it's done and I'll look at any failures.

**Comment by dillaman** [comment]
@batrick To my untrained eye, it seems like the FS tests are good (only "TestVolumeClient" and "wait_until_healthy" errors).

**Comment by batrick** [comment]
@dillaman looks good!

**Pull request merged**
