### PR TITLE
rgw: initialize curl handle cache in rgw_admin

### PR DESCRIPTION
**Pull request by cbodley**
Fixes: http://tracker.ceph.com/issues/23203

### CODE REVIEW

**Comment by theanalyst** [comment]
@cbodley do you mind if this is incorporated in https://github.com/ceph/ceph/pull/20390/ itself? I just added a commit that calls the curl handle setup and teardown as a part of the curl setup/teardown functions.

**Comment by cbodley** [comment]
@theanalyst i don't mind, no - i guess it just depends on whether we'll want to backport yours - if so, we should keep them separate

**Comment by theanalyst** [comment]
my idea was to backport both https://github.com/ceph/ceph/pull/20390 and https://github.com/ceph/ceph/pull/20635 in one pr; since adding one will create conflicts

**Comment by theanalyst** [comment]
@cbodley https://github.com/ceph/ceph/pull/20722 was my idea for a Luminous backport

**Comment by cbodley** [comment]
thanks @theanalyst, i'll close this and you can carry it forward :+1:

**Pull request closed without merging**
