### PR TITLE
Port Python-based tests and remaining Python bindings to Python 3

### PR DESCRIPTION
**Pull request by BlaXpirit**
Compatibility with Python 2.6+ is kept.

The tests I've ran: https://gist.github.com/6ce78ee907b2d13a9fce8de859173dc8
(Probably best to *Download ZIP* and look at the text files locally)

### CODE REVIEW

**Comment by jdurgin** [comment]
these fixes all look good to me - minor point, could you add a subsystem to each commit message subject, e.g. tests: make foo tests compatible with python 3, or pybind: ... - it helps make the git log more easily filterable

**Comment by jdurgin** [comment]
@jcsp may want to look at the cephfs.pyx change

**Comment by BlaXpirit** [comment]
The cephfs.pyx change: instead of forcing a file mode like "r+" to be turned into a bytestring (which during iteration later in the code yields numbers) it's just required to be a normal string.

**Comment by BlaXpirit** [comment]
Rebased due to conflict and added subjects

**Comment by jcsp** [comment]
Looks fine but please don't merge until I've run this through the fs suite

**Comment by jdurgin** [comment]
lgtm

**Comment by jcsp** [comment]
This is failing to build RPMs:

```
Failed to import the site module
Traceback (most recent call last):
File "/srv/autobuild-ceph/gitbuilder.git/build/install-deps-python3/lib64/python3.4/site.py", line 67, in
import os
File "/srv/autobuild-ceph/gitbuilder.git/build/install-deps-python3/lib64/python3.4/os.py", line 616, in
from _collections_abc import MutableMapping
Error: Import No module named '_collections_abc'
Using base prefix '/usr'
New python executable in /srv/autobuild-ceph/gitbuilder.git/build/install-deps-python3/bin/python3
Also creating executable in /srv/autobuild-ceph/gitbuilder.git/build/install-deps-python3/bin/python
ERROR: The executable /srv/autobuild-ceph/gitbuilder.git/build/install-deps-python3/bin/python3 is not functioning
ERROR: It thinks sys.prefix is '/srv/autobuild-ceph/gitbuilder.git/build/src/ceph-detect-init' (should be '/srv/autobuild-ceph/gitbuilder.git/build/install-deps-python3')
ERROR: virtualenv is not compatible with this system or executable
Running virtualenv with interpreter /bin/python3
./install-deps.sh: line 150: /srv/autobuild-ceph/gitbuilder.git/build/install-deps-python3/bin/activate: No such file or directory
Requirement already satisfied (use --upgrade to upgrade): setuptools>=0.8 in /srv/autobuild-ceph/gitbuilder.git/build/install-deps-python2.7/lib/python2.7/site-packages
Requirement already satisfied (use --upgrade to upgrade): pip>=7.0 in /srv/autobuild-ceph/gitbuilder.git/build/install-deps-python2.7/lib/python2.7/site-packages
Requirement already satisfied (use --upgrade to upgrade): wheel>=0.24 in /srv/autobuild-ceph/gitbuilder.git/build/install-deps-python2.7/lib/python2.7/site-packages
./install-deps.sh: line 156: /srv/autobuild-ceph/gitbuilder.git/build/install-deps-python3/bin/activate: No such file or directory
```

http://gitbuilder.sepia.ceph.com/gitbuilder-ceph-rpm-centos7-amd64-basic/log.cgi?log=941e9185bc5dd49af508f90e3daf9aed677521be

**Comment by BlaXpirit** [comment]
@jcsp There is some work-in-progress regarding the packaging, indeed it fails on RPMs but we've progressed in that regard since then: this particular error was fixed in https://github.com/ceph/ceph/pull/10289/commits/2699b6d89b8c1c193fd86b5233d1ea86458753a0 (see [this run](http://gitbuilder.sepia.ceph.com/gitbuilder-ceph-rpm-centos7-amd64-basic/log.cgi?log=86ea56b481318b6816479e3faa0856eb41bcc512) which progresses beyond that point). The next problem is that the RPM builder wants to bytecompile every Python file so it can't succeed until everything is ported (and ceph_volume_client is not my task).

**Comment by BlaXpirit** [comment]
On the other hand, this does not seem to have regressions regarding Python 2, so it's OK to merge, just don't enable Python 3 package building yet.

I'm also doing some Python 3 testing on Sepia (excluded CentOS). Will post a build result tomorrow.

**Comment by jcsp** [comment]
This is failing tests:
```
2016-07-14T11:38:14.446 INFO:tasks.workunit.client.0.mira110.stderr:======================================================================
2016-07-14T11:38:14.450 INFO:tasks.workunit.client.0.mira110.stderr:ERROR: test_cephfs.test_fsync
2016-07-14T11:38:14.451 INFO:tasks.workunit.client.0.mira110.stderr:----------------------------------------------------------------------
2016-07-14T11:38:14.451 INFO:tasks.workunit.client.0.mira110.stderr:Traceback (most recent call last):
2016-07-14T11:38:14.451 INFO:tasks.workunit.client.0.mira110.stderr:  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
2016-07-14T11:38:14.451 INFO:tasks.workunit.client.0.mira110.stderr:    self.test(*self.arg)
2016-07-14T11:38:14.451 INFO:tasks.workunit.client.0.mira110.stderr:  File "/home/ubuntu/cephtest/mnt.0/client.0/tmp/test_cephfs.py", line 53, in test_fsync
2016-07-14T11:38:14.452 INFO:tasks.workunit.client.0.mira110.stderr:    fd = cephfs.open(b'file-1', u'w', 0o755)
2016-07-14T11:38:14.452 INFO:tasks.workunit.client.0.mira110.stderr:  File "cephfs.pyx", line 614, in cephfs.LibCephFS.open (/srv/autobuild-ceph/gitbuilder.git/build/out~/ceph-11.0.0-642-g941e918/obj-x86_64-linux-gnu/src/pybind/cephfs/pyrex/cephfs.c:8115)
2016-07-14T11:38:14.452 INFO:tasks.workunit.client.0.mira110.stderr:TypeError: flags must be a string
2016-07-14T11:38:14.452 INFO:tasks.workunit.client.0.mira110.stderr:
2016-07-14T11:38:14.453 INFO:tasks.workunit.client.0.mira110.stderr:----------------------------------------------------------------------
```

**Comment by jcsp** [comment]
Unclear what you mean by saying this does not have regressions, the build is still failing on the last gitbuilder link you posted?

**Comment by BlaXpirit** [comment]
@jcsp Hmm, thank you, that must be my mistake. I added that `u''` trying to fix an error but then I realized to go the other way &mdash; the `u` shouldn't be there.
But I was sure that I tested it on Python 2 afterwards!

---

The build on gitbuilder is failing because the branch also contains changes from my other pull request that adds packages for Python 3 &mdash; and I need those because otherwise I can't test on Sepia. Unfortunately, until everything is ported to Python 3 I don't see a good way to build RPM packages.

Without building the Python 3 packages &ndash; on Python 2 everything is supposed to work the same. Except for this problem that you found in cephfs :(

**Comment by BlaXpirit** [comment]
So the reason that my Python 2 re-test didn't catch the bug was that I didn't rebuild the binding for Python 2 after modifying it. I was able to reproduce this problem, and easily fixed it.

**Comment by BlaXpirit** [comment]
Alright, so I've merged master to resolve the merge conflict and ported the change to cephfs that was made since.

And I made an error (typo) while doing that half an hour ago, so I re-pushed the last commit just now

**Comment by jcsp** [comment]
Could you rebase on master instead of merging master?  That way we avoid the extra merge commits in the history after something is merged to master.

**Comment by BlaXpirit** [comment]
@jcsp OK, did that. Also checked that the overall diff didn't change.

https://github.com/ceph/ceph/compare/master...BlaXpirit:ceph-tests-py3-backup
https://github.com/ceph/ceph/compare/master...BlaXpirit:ceph-tests-py3

**Comment by cbodley** [comment]
`nosetests-3.4 ../src/test/rgw/test_multi.py` ran and passed :+1:

**Comment by jcsp** [comment]
Has anyone re-run fs tests since this was last failing them?  Otherwise I will do so now (pushed ceph-tests-py3 to gitbuilders earlier)

**Comment by BlaXpirit** [comment]
@jcsp I ran cephfs unittests locally after fixing the failure on Python 2 that you pointed out, but other than that I don't know about anyone running tests.

**Comment by jdurgin** [comment]
not yet, the lab cluster was having issues when I was going to run several suites last week

**Comment by jcsp** [comment]
This didn't throw up any issues on my fs suite run so it's good to merge from my POV.  @jdurgin are you waiting for any tests?

**Pull request merged**
