### PR TITLE
mgr/cephadm: add ability for cephadm to generate frontend cert for rgw

### PR DESCRIPTION
**Pull request by adk3798**
If users are okay with a self-signed cert and would prefer to
just let cephadm generate it for them rather than creating it
themselves. Additionally, if the zonegroup_hostnames field is
set, add those entries to the SANs entries for the cert in
order to facilitate virtual host bucket access

Docs and Teuthology test TODO after initial testing

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [x] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Review by phlogistonjohn — APPROVED** [review]
looks OK to me.

**Comment by adk3798** [comment]
https://pulpito.ceph.com/adking-2024-08-18_19:40:37-orch:cephadm-wip-adk-testing-2024-08-18-1323-distro-default-smithi/

Failures:
- test_nfs task failed due to a PR in the run
- mds_upgrade_sequence tests timing out, known issue
- upgrade test `ceph versions` and `ceph orch ps` mismatch, known issue
- a couple tests failed with 
```
2024-08-18T20:03:02.589 INFO:teuthology.orchestra.run.smithi003.stderr:RuntimeError: Failed command: /usr/bin/docker run --rm --ipc=host --stop-signal=SIGTERM --ulimit nofile=1048576 --net=host --entrypoint /usr/bin/ceph --init -e CONTAINER_IMAGE=quay-quay-quay.apps.os.sepia.ceph.com/ceph-ci/ceph:403f237cd90a2ef02e936d8d5c271b25a5b8ad17 -e NODE_NAME=smithi003 -v /var/log/ceph/96ccc1cc-5d9c-11ef-bccf-c7b262605968:/var/log/ceph:z -v /tmp/ceph-tmpqiz8079v:/etc/ceph/ceph.client.admin.keyring:z -v /tmp/ceph-tmp4thgwijv:/etc/ceph/ceph.conf:z quay-quay-quay.apps.os.sepia.ceph.com/ceph-ci/ceph:403f237cd90a2ef02e936d8d5c271b25a5b8ad17 orch set backend cephadm: Error ENOTSUP: Warning: due to ceph-mgr restart, some PG states may not be up to date
2024-08-18T20:03:02.589 INFO:teuthology.orchestra.run.smithi003.stderr:Module 'orchestrator' is not enabled/loaded (required by command 'orch set backend'): use `ceph mgr module enable orchestrator` to enable it
```
which is strange. I think these would pass in a rerun, but due ot issues with the nvme loop devices we can't get the reruns in.
- monitoring stack test broken since monitoring stack versions were bumped

Only failure related to a PR in the run is the test_nfs task. Nothing blocking merging of the other PRs

**Comment by adk3798** [comment]
jenkins test api

**Comment by adk3798** [comment]
https://pulpito.ceph.com/adking-2024-08-27_12:51:47-orch:cephadm-wip-adk-testing-2024-08-26-1718-distro-default-smithi/

Failures:
- 6 `in cluster log` type failures, all of which are either known issue or not serious
- 1 `adjust-ulimits` command failing. Not something I'm familiar with but appears unrelated to orchestration
- 1 timeout in deploy raw OSDs test, seems unrelated to PRs in the run
- `test_create_export_via_apply` failure, caused by a specific PR in the run
- 2 `ceph orch ps`, `ceph versions` mismatch failures, known issue
- 2 mds_upgrade_sequence timeout failures, known issue
- 2 rgw-ingress timeout failures, known issue
- 2 dead jobs due to teuth/infra issues 

Only issue related to PRs in the run was the `test_create_export_via_apply` failure

**Comment by adk3798** [comment]
jenkins test api

**Comment by adk3798** [comment]
jenkins test api

**Comment by adk3798** [comment]
https://pulpito.ceph.com/adking-2024-09-05_04:20:41-orch:cephadm-wip-adk-testing-2024-09-04-1621-distro-default-smithi/

Failures:
- two instances of https://tracker.ceph.com/issues/67758, known issue
- 1 failure staggered upgrade with agent, known issue
- `Test failure: test_nfs_export_creation_without_cmount_path (tasks.cephfs.test_nfs.TestNFS)` caused by a PR in the run
- a couple SMB tests failing with either `in cluster log` stray daemon warnings or SELinux denials, known issue
- deploy raw OSD test timing out, known issue
- mds_upgrade_sequence and rgw-ingress tests timing out, known issue

Nothing to block merging the PRs in the run other than the NFS failure related one

**Comment by adk3798** [comment]
https://pulpito.ceph.com/adking-2024-09-10_02:59:23-orch:cephadm-wip-adk-testing-2024-09-09-1904-distro-default-smithi/

Failures:
- stray daemon warning in smb test, known issue
- `Test failure: test_nfs_export_creation_without_cmount_path (tasks.cephfs.test_nfs.TestNFS)` caused by a PR in the run
- 2x agent on staggered upgrade failure, known issue
- deploy raw test timed out, known issue
- `test_rgw_multisite` test failed to generate token on realm bootstrap, somewhat new but not the first time I've seen it and it's unrelated to PRs in this run
- 4x mds_upgrade_sequence failures, known issue
- rgw-ingress tests timed out, known issue

Nothing to block merging PRs in the run other than the NFS failure related one

**Pull request merged**
