### PR TITLE
osd/scrub: use the actual active set when requesting replicas to scrub

### PR DESCRIPTION
**Pull request by ronen-fr**
Note that get_acting_set() may differ from
get_acting_recovery_backfill() - if we are backfilling or recovering.

Fixes: https://tracker.ceph.com/issues/57698

### CODE REVIEW

**Comment by ronen-fr** [comment]
jenkins retest this please

**Comment by athanatos** [comment]
So, this seems right.  I'm not sure I understand how this could result in a bug, however, since we only scrub when active+clean?

**Comment by neha-ojha** [comment]
> So, this seems right. I'm not sure I understand how this could result in a bug, however, since we only scrub when active+clean?

This isn't true when osd_scrub_during_recovery is set to true.

**Comment by athanatos** [comment]
> > So, this seems right. I'm not sure I understand how this could result in a bug, however, since we only scrub when active+clean?
> 
> This isn't true when osd_scrub_during_recovery is set to true.

Ahah!  LGTM.

**Comment by ronen-fr** [comment]
@athanatos , @neha-ojha : the case were I've noticed the failure caused by this bug did not have 'scrub_during_recovery' (as Neha has already pointed out: we unfortunately never test with that flag On). Instead the PG was
active+clean+remapped
Here, too, the two sets differ.

**Comment by ronen-fr** [comment]
> Or wait, do we not scrub backfill/async recovery peers?

The fix can go either way, but must be consistent. Either we "reserve" resources with the full set and request their scrub results, or we only use the current active set for both.

**Comment by ronen-fr** [comment]
@athanatos, @neha-ojha: to add some context:
 
I am working on two scrub-related client issues:

The first involves omap_digest errors (possibly scrub_backend bug), and another involves long tails of PGs not being scrubbed. That one is possibly caused by stuck scrub sessions that keep specific OSDs from scrubbing neigher as primary nor as replica, thus affecting multiple PGs.

As part of this investigation, I have implemented the first stage of "stuck scrub detection" (a formal client request. I am working on cleaning the code up for a PR). And the first run with the new code has detected the "active set" issue.

**Comment by athanatos** [comment]
Looking at PeeringState, I'm not convinced that an active+clean+remapped pg could have backfill or async_recover osds.  Can you update the bug with a summary of the peering interval in which you saw the problem?  Did the pg actually do backfill or async recovery during that interval?  What peering states did it go through?

**Comment by ronen-fr** [comment]
@athanatos : please see the updated content in the bug report (https://tracker.ceph.com/issues/57698).
My understanding is that we are just after the backfilling, and thus active+clean+remapped. And the main
issue the is remapped, as the acting-set differs from the up-set (or the acting_recovery_backfill one)

**Review by athanatos — APPROVED** [review]

**Comment by athanatos** [comment]
jenkins test api

**Comment by ronen-fr** [comment]
Will be merging, based on http://pulpito.front.sepia.ceph.com/?branch=wip-rf-acting

**Pull request merged**
