### PR TITLE
qa/ceph-ansible: Set ceph_stable_release to mimic

### PR DESCRIPTION
**Pull request by badone**
Fixes: http://tracker.ceph.com/issues/38231

Signed-off-by: Brad Hubbard <bhubbard@redhat.com>

- [x] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by tchaikov** [comment]
http://pulpito.ceph.com/kchai-2019-02-16_15:31:40-ceph-ansible-wip-sage-testing-2019-02-16-1748-distro-basic-smithi/

**Comment by badone** [comment]
@tchaikov That's interesting. I don't see that issue on my branch based on an earlier commit, http://pulpito.ceph.com/bhubbard-2019-02-18_07:30:56-ceph-ansible-wip-badone-testing-distro-basic-ovh/ There does however appear to be a problem with the test-restful.sh script. I'll look into both issues further.

**Comment by vasukulkarni** [comment]
This issue is due to smithi having nvme drives and lvm batch command returning non zero exit cod, I filed a tracker for this for ceph-volume http://tracker.ceph.com/issues/38390

**Comment by tchaikov** [comment]
the failures on ovh nodes are like
```
2019-02-18T15:31:34.511 INFO:tasks.workunit.client.0.ovh059.stderr:++ dirname /home/ubuntu/cephtest/clone.client.0/qa/workunits/rest/test-restful.sh
2019-02-18T15:31:34.515 INFO:tasks.workunit.client.0.ovh059.stderr:+ mydir=/home/ubuntu/cephtest/clone.client.0/qa/workunits/rest
2019-02-18T15:31:34.516 INFO:tasks.workunit.client.0.ovh059.stderr:++ ceph config-key get mgr/restful/keys/admin
2019-02-18T15:31:35.242 INFO:tasks.workunit.client.0.ovh059.stderr:obtained 'mgr/restful/keys/admin'
2019-02-18T15:31:35.261 INFO:tasks.workunit.client.0.ovh059.stderr:+ secret=349b8bf1-8b1a-48df-82f4-8fe961b143d5
2019-02-18T15:31:35.262 INFO:tasks.workunit.client.0.ovh059.stderr:++ ceph mgr dump
2019-02-18T15:31:35.262 INFO:tasks.workunit.client.0.ovh059.stderr:++ jq -r .active_name
2019-02-18T15:31:36.104 INFO:tasks.workunit.client.0.ovh059.stdout:active ovh059  admin secret 349b8bf1-8b1a-48df-82f4-8fe961b143d5
2019-02-18T15:31:36.105 INFO:tasks.workunit.client.0.ovh059.stderr:+ active=ovh059
2019-02-18T15:31:36.105 INFO:tasks.workunit.client.0.ovh059.stderr:+ echo 'active ovh059  admin secret 349b8bf1-8b1a-48df-82f4-8fe961b143d5'
2019-02-18T15:31:36.105 INFO:tasks.workunit.client.0.ovh059.stderr:+ prefix=mgr/restful/ovh059
2019-02-18T15:31:36.105 INFO:tasks.workunit.client.0.ovh059.stderr:++ ceph config-key get mgr/restful/ovh059/server_addr
2019-02-18T15:31:36.711 INFO:tasks.workunit.client.0.ovh059.stderr:Error ENOENT: error obtaining 'mgr/restful/ovh059/server_addr': (2) No such file or directory
```

**Pull request merged**
